### ISSUE TITLE
Benedicts chest gives no loot

### ISSUE THREAD

**Issue by kelsul** [Atlantiss/NetherwingBugtracker#10]
[//]: # (Enclose links to things related to the bug using http://wowhead.com or any other TBC database.)
[//]: # (You can use screenshot ingame to visual the issue.)
[//]: # (Write your tickets according to the format:)
[//]: # ([Quest][Azuremyst Isle] Red Snapper - Very Tasty!)
[//]: # ([NPC] Magistrix Erona)
[//]: # ([Spell][Mage] Fireball)
[//]: # ([Npc][Drop] Ghostclaw Lynx)
[//]: # ([Web] Armory doesnt work)

**Description**: 
When you open it, it gives no loot.
https://www.wowhead.com/object=3239/benedicts-chest
**Current behaviour**:
When you open it ti gives no loot.
**Expected behaviour**: 
Give me loot.
**Server Revision**:

**Comment by Evolvee** [comment]
![image](https://user-images.githubusercontent.com/1942409/45921468-9781ed80-beb6-11e8-89ab-548cdc18e005.png)

works for me just fine, try to delete cache or record the problem

**Comment by RealZwox** [comment]
The Item has pro a Respawntimer in the Chest right now. Check that. Common on other servers.

**Comment by Evolvee** [comment]
I just looted 3 within 20 sec... Are you sure you werent on the quest already that the looted item starts?

**Comment by Sothanwow** [comment]
This one is really annoying you can't tell when it has respawned and it takes your key when you try to open it even if there is no letter. It really should get switched to despawn when the letter isn't in there.

**Comment by xmesaj2** [comment]
the bug is actually with gobject despawn, loot is picked up but gobject stays in its place while loot resets after some time

**Comment by kelsul** [comment]
tried it 2 more times and didnt get anything

**Comment by Jezofine** [comment]
Ate my key 2 times.

**Comment by lynxzor** [comment]
I looted first time without issue

**Comment by The14me** [comment]
Just retested.Work fine to me.Please re-open if happen again.

**Comment by sefamurat** [comment]
It still exists. Me and my friend couldnt get anything from the chest and it ate 3 keys. Deleting WDB didnt work.

**Comment by WarriorTSW** [comment]
Tried 3 times today and wasnt able to loot anything out of the chest.

**Comment by Greytt** [comment]
Tried 3 times personally and 3 others tried as well. Same problem. No loot. Key consumed every time.

**Comment by IGNPoint** [comment]
Still has no letter in it...

**Comment by Manaci** [comment]
Fixed
