### ISSUE TITLE
Mob Stealth

### ISSUE THREAD

**Issue by Erodraeda** [Atlantiss/NetherwingBugtracker#1000]
[//]: # (Enclose links to things related to the bug using http://wowhead.com or any other TBC database.)
[//]: # (You can use screenshot ingame to visual the issue.)
[//]: # (Write your tickets according to the format:)
[//]: # ([Quest][Azuremyst Isle] Red Snapper - Very Tasty!)
[//]: # ([NPC] Magistrix Erona)
[//]: # ([Spell][Mage] Fireball)
[//]: # ([Npc][Drop] Ghostclaw Lynx)
[//]: # ([Web] Armory doesnt work)

**Description**: 
I'm being able to see mobs in stealth, while they are pretty far away, as shown on the printscreen. Meanwhile, the mob that's right in front of me disappears with a few steps backwards.
Edit: Seems to be only with that one mob (5615)
**Current behaviour**:
![screenshot_516](https://user-images.githubusercontent.com/40346279/46267292-79e20300-c50a-11e8-8430-1a32363a940c.png)
**Expected behaviour**: 
Shouldn't be able to see that far ahead.
**Server Revision**:

**Comment by Wolffenstein** [comment]
Fixed in rev 2102.
