### ISSUE TITLE
[NPC][Loot]Ro'bark#14278 (rare) didn't drop uncommon item

### ISSUE THREAD

**Issue by Tenoutoften** [Atlantiss/NetherwingBugtracker#1002]
**Description**: 
[Ro'bark#14278](https://db.excalibur.ws/?npc=14278), who is a rarespawn [didn't drop an uncommon item](https://i.gyazo.com/48963b250666071e598ac9b239e3c77d.png) as he should indicated by:

https://wow.gamepedia.com/Ro%27Bark
https://youtu.be/P4ojy6SB-kc?t=34 (Significantly later patch)

Generally all rares drop a green.

**Current behaviour**:
At least sometimes does not drop a green.

**Expected behaviour**: 
Expected to drop a green like most rare spawns.

**Server Revision**: 
2105

**Comment by aresbrutus** [comment]
All rare loot tables are being worked on. #578
