### ISSUE TITLE
[NPC][Hunter] Bloodmyst Hatchling's untameable

### ISSUE THREAD

**Issue by TerawattHF** [Atlantiss/NetherwingBugtracker#1004]
![image](https://user-images.githubusercontent.com/28246480/46277050-561fcb00-c5a5-11e8-9d47-b2b6237b2a0e.png)

**Description**: Bloodmyst Hatchling's on Bloodmyst Isle can't be tamed.

**Current behaviour**: Targetting a Bloodmyst Hatchling and casting Tame Beast returns with an "Invalid target" error.

**Expected behaviour**: Bloodmyst Hatchling should be tameable as a hunter pet.

Additionally, they don't appear to be dropping loot either.

**Server Revision**: 2105

**Comment by Evolvee** [comment]
https://www.wowhead.com/npc=17525/bloodmyst-hatchling#comments
![image](https://user-images.githubusercontent.com/1942409/46284972-0677da00-c57a-11e8-8853-17b4b3dc314c.png)
![image](https://user-images.githubusercontent.com/1942409/46284981-10014200-c57a-11e8-8017-e8e7c2e0918c.png)
