### ISSUE TITLE
[Loot] Battered Chest contain items of a too high level

### ISSUE THREAD

**Issue by Gniddikon** [Atlantiss/NetherwingBugtracker#1005]
**Description**: It looks like loot of Battered Chests (the lowest possible quality of chests) contain items that are too high level. For example loooted a Forest Leather Mantle (Level 20 green shoulders) form it in ghostlands.

It's hard for me to provide any proof right now but it should be clear that this is not intended and the level of items contained in these kinds of chests should be < Level 15 at least.

**Current behaviour**: Items in Battered Chests are too high level.
Examples from what I have experienced so far:

- Shoulders Level 20
- Shield Level 18
- Heavy Stone

**Expected behaviour**: Item level should be reduced.

**Server Revision**: 2105

**Comment by Gniddikon** [comment]
I want to add that a Battered Chest in Dun Morogh contained only loot of the appropriate level (a level 5 sword and rough stone). So it might be just specific chests having a wrong loot table.

The one I reported above is a chest in the gnoll camp in Ghostlands.

**Comment by totaemoeggerli** [comment]
found a level 40 item in a chest with level 36 mobs around (drywhisker gorge arathi)
https://imgur.com/a/AIYmjms

**Comment by Manaci** [comment]
A [Battered Chest](https://db.excalibur.ws/?object=2849) in Ghostlands with those items in its droptable.
