### ISSUE TITLE
[NPC] Scalding Elemental

### ISSUE THREAD

**Issue by totaemoeggerli** [Atlantiss/NetherwingBugtracker#1006]
[//]: # (Enclose links to things related to the bug using http://wowhead.com or any other TBC database.)
[//]: # (You can use screenshot ingame to visual the issue.)
[//]: # (Write your tickets according to the format:)
[//]: # ([Quest][Azuremyst Isle] Red Snapper - Very Tasty!)
[//]: # ([NPC] Magistrix Erona)
[//]: # ([Spell][Mage] Fireball)
[//]: # ([Npc][Drop] Ghostclaw Lynx)
[//]: # ([Web] Armory doesnt work)

**Description**: 
[Scalding Elemental](https://www.wowhead.com/npc=10756/scalding-elemental) doesn't leave water and resets aggro.

**Current behaviour**:
https://gfycat.com/OrnateSkinnyCopepod

**Expected behaviour**: 
Mob should move to the player and attack him.

**Server Revision**: 2083

**Comment by Evolvee** [comment]
@Wolffenstein idk what rev this is, but maybe u fixed it witht he height rev? seems like either mmap/height problem

the elemental has proper flags/inhabit type and moves out of water just fine

**Comment by Easyfraggy** [comment]
Appears fixed. Reopen if new info.
