### ISSUE TITLE
[NPC] Grimtotem Bandit minds his own buisness

### ISSUE THREAD

**Issue by totaemoeggerli** [Atlantiss/NetherwingBugtracker#1007]
[//]: # (Enclose links to things related to the bug using http://wowhead.com or any other TBC database.)
[//]: # (You can use screenshot ingame to visual the issue.)
[//]: # (Write your tickets according to the format:)
[//]: # ([Quest][Azuremyst Isle] Red Snapper - Very Tasty!)
[//]: # ([NPC] Magistrix Erona)
[//]: # ([Spell][Mage] Fireball)
[//]: # ([Npc][Drop] Ghostclaw Lynx)
[//]: # ([Web] Armory doesnt work)

**Description**: 
[Grimtotem Bandit](https://www.wowhead.com/npc=10758/grimtotem-bandit) doesn't engage in combat.

**Current behaviour**:
Another palyer reset the mob. It didn't attack and returned to its patrol.
https://gfycat.com/gifs/detail/FatalKlutzyIslandcanary

**Expected behaviour**: 
Mob should fight back.

**Server Revision**: 2083

**Comment by Evolvee** [comment]
some evade issue probably @Wolffenstein

**Comment by Tereneckla** [comment]
Fixed
