### ISSUE TITLE
[NPC]Magistrate Burnside's#2335 Fire Nova#11969 & Inferno Shell#7739 costs no mana

### ISSUE THREAD

**Issue by Tenoutoften** [Atlantiss/NetherwingBugtracker#1008]
**Description**: 
[Magistrate Burnside's#2335](https://db.excalibur.ws/?npc=2335#abilities) has three abilities and they should all cost mana according too [excalibur's database](https://db.excalibur.ws/?npc=2335#abilities), and on wowhead this exact [NPC ID(removed with later patch) has no abilities](https://www.wowhead.com/npc=2335/magistrate-burnside) but his new [NPC ID does](https://www.wowhead.com/npc=47790/magistrate-burnside#abilities) and they all cost the same & have same spellID's as those in Excalibur's database:

Exclai. Database.
[Fire Nova#11969](https://db.excalibur.ws/?spell=11969) - **95 mana**
[Inferno Shell#7739](https://db.excalibur.ws/?spell=7739) - **300 mana**
[Fireball#20811](https://db.excalibur.ws/?spell=20811) - **90 mana**(seems to cost mana already)

Wowhead database:
[Fire Nova#11969](https://www.wowhead.com/spell=11969/fire-nova)
[Inferno Shell#7739](https://www.wowhead.com/spell=7739/inferno-shell)
[Fireball#20811](https://www.wowhead.com/spell=20811/fireball)

It makes the most sense that if he is to cast these spells that they would cost mana.

**Current behaviour**:
[Me fighting him with combat log open](https://www.youtube.com/watch?v=fbOGytLWBhk&feature=youtu.be), displaying zero mana spent while casting [Fire Nova#11969](https://db.excalibur.ws/?spell=11969) & [Inferno Shell#7739](https://db.excalibur.ws/?spell=7739)

**Expected behaviour**: 
Expect spells to cost mana.

**Server Revision**: 
2105

**Comment by Evolvee** [comment]
rev xdd

good report 👍
