### ISSUE TITLE
[NPC] Ranged/caster mobs reset too early

### ISSUE THREAD

**Issue by totaemoeggerli** [Atlantiss/NetherwingBugtracker#1009]
[//]: # (Enclose links to things related to the bug using http://wowhead.com or any other TBC database.)
[//]: # (You can use screenshot ingame to visual the issue.)
[//]: # (Write your tickets according to the format:)
[//]: # ([Quest][Azuremyst Isle] Red Snapper - Very Tasty!)
[//]: # ([NPC] Magistrix Erona)
[//]: # ([Spell][Mage] Fireball)
[//]: # ([Npc][Drop] Ghostclaw Lynx)
[//]: # ([Web] Armory doesnt work)

**Description**: 
Ranged mobs seem to reset combat too early.

**Current behaviour**:
The issue bothered me since launch but this encounter was pretty striking. The ranged mob is closer when engaging combat (piller doesn't break los btw, not sure if it's supposed to be)., but it resets earlier then the melee mob. This isn't unique to this ranged mob, it feels the same with caster mobs and it makes it hard to pull caster mobs back because they reset alot earlier then I'm used to.
https://gfycat.com/gifs/detail/UnselfishWarpedGibbon

**Expected behaviour**: 
Ranged mobs shouldn't reset that fast. They should reset when the mob itself moves to far from their starting position, not the player.

**Server Revision**: 2083

**Comment by Easyfraggy** [comment]
Should be fixed. Retest and reopen if not.
