### ISSUE TITLE
[NPC][Spell] Witch Doctor Mai'jin - totems

### ISSUE THREAD

**Issue by Firroth** [Atlantiss/NetherwingBugtracker#1010]
[NPC] Witch Doctor Mai'jin http://wowwiki.wikia.com/wiki/Witch_Doctor_Mai%27jin
[Spell] Healing Ward https://db.excalibur.ws/?spell=5605
[Spell] Magma Totem https://db.excalibur.ws/?spell=8190

**Current behaviour**:
When he uses "Healing Ward totem", in 1-3s later he puts another one "Magma totem". Issue lays with when he puts magma totem, healing ward totem is "overwrote?" it disappears cause new one was put on the floor (they shouldn't be same element for sure, but it looks like they are here). So in the end this healing ward is meaningless cause it will tick once and just disappear without player bothering about it.

**Expected behaviour**: 
Healing Ward totem should still lay on the ground, even when magma totem is put down making 2 totems on the floor be at the same time.

**Server Revision**: 
2105

**Comment by Tereneckla** [comment]
#396 probably related.

**Comment by The14me** [comment]
A global issue with NPC's that use more than one totem.

**Comment by Wolffenstein** [comment]
Those totems share the same totem slot. Blizzlike.
