### ISSUE TITLE
[Quest objects][Core] Looting Objects can agro NPCs standing out of line of sight

### ISSUE THREAD

**Issue by Tenoutoften** [Atlantiss/NetherwingBugtracker#1011]
**Description**: 
After killing [[NPC]Magistrate Burnside's#2335](https://github.com/Atlantiss/NetherwingBugtracker/issues/1008) who seemingly had a few issues, I went to loot [[Item]Hillsbrad Town Registry#3657](https://db.excalibur.ws/?item=3657) from [[Object]#1659](https://db.excalibur.ws/?object=1759) for [[Quest]Battle of Hillsbrad#532](https://db.excalibur.ws/?quest=532), unfortunately I didn't catch this on recording - but shortly after two [[NPC]Hillsbrad Councilman#2387](https://db.excalibur.ws/?npc=2387) agroed on to me, even though the room I was in was empty.

I suspect what happened is they agroed through the wall, I think I looted the object right as the patrol, on the other side of the wall, was close by. It patrols very closely to the spot where you [loot the object(Video of patrol)](https://www.youtube.com/watch?v=nsOrwCvVx0k&feature=youtu.be).
The patrol must then have dragged the guarding [[NPC]Hillsbrad Councilman#2387](https://db.excalibur.ws/?npc=2387) with him into the house. The object you loot is quite close to the corner of the building

It's difficult for me to provide a perfect video of this scenario because both [[NPC]Clerk Horrace Whitesteed#2448](https://db.excalibur.ws/?npc=2448) & [[NPC]Magistrate Burnside#2335](https://db.excalibur.ws/?npc=2335) has a very short respawn timer.

**Expected behaviour**: 
I'd expect looting objects shouldn't agro NPC's through the wall.

**Server Revision**: 
2105

**Comment by Evolvee** [comment]
@Wolffenstein The "gob alert opening" send to NPCs should probably obay LoS if it doesnt already

**Comment by Wolffenstein** [comment]
It does check for LoS though...

**Comment by The14me** [comment]
do the same thing for 10 time's,never happen to me.Please re-open if happen again.
