### ISSUE TITLE
[Hunter][Talent] Thick Hide not increasing pet armor properly

### ISSUE THREAD

**Issue by Gniddikon** [Atlantiss/NetherwingBugtracker#1012]
**Description**: The hunter talent "Thick Hide" is not increasing my own and my pet's armor values properly

**Current behaviour**: 1 talent point in "Thick Hide" only increased my pet's armor from 867 to 869, even though according to the tooltip it should be a 7% increase. At the same time it does not properly increase my own armor contribution by from items by 4%.

**Expected behaviour**: Increase pet's armor by 7% and my own armor contribution form items by 4% for each talent point spent.

**Server Revision**: 2105

**Comment by Gniddikon** [comment]
This talent still has no effect whatsoever on the pet.

**Comment by Manaci** [comment]
Fixed
