### ISSUE TITLE
Tooga not wandering

### ISSUE THREAD

**Issue by Tinnoan** [Atlantiss/NetherwingBugtracker#1013]
Tooga is just standing around, not wandering around like he should according to comments in [Tooga's Quest](https://web.archive.org/web/20070425191932/http://www.wowhead.com/?quest=1560) and [Tooga](https://web.archive.org/web/20070629171155/http://www.wowhead.com:80/?npc=5955#z0z) from wowhead 2007.

He should be wandering around the south west area of Tanaris, in and around the Thistleshrub area.

![tooga](https://user-images.githubusercontent.com/25431721/46286016-d5010d80-c57d-11e8-9b0b-4506e4f20eb9.PNG)

**Comment by The14me** [comment]
Confirm

**Comment by aresbrutus** [comment]
Fixed in one of the next updates.
