### ISSUE TITLE
Dar'Khan's Lieutenants quest, Masophet the black not showing.

### ISSUE THREAD

**Issue by Giantulol** [Atlantiss/NetherwingBugtracker#1014]
**Description**: 
Mini boss Masophet the black not showing.

**Current behaviour**:
The Mage boss Masophet the black should be in his temple surrounded by his channeling mages/locks, the mages/locks are there but he's not on his plateau.

**Expected behaviour**: 
The Mage boss Masophet the black should be in his temple surrounded by his channeling mages/locks, the mages/locks are there but he's not on his plateau.

**Server Revision**: 
2105

https://www.youtube.com/watch?v=nbkkMM7aHdM 

Video were you see Masophet the black standing on his platea inside his little temple surrounded by the mages/locks.

**Comment by ttghnw** [comment]
I completed it yesterday and he was there :O

**Comment by Giantulol** [comment]
I waited for around 30 minutes and he did not show up so something wrong..

**Comment by The14me** [comment]
Its here https://imgur.com/a/Os9nEPj

**Comment by ttghnw** [comment]
Ah yes Whiterlimb - the rare elite - 's respawn is way too fast, when I was there, I killed him in one ziggurat and he was already on the one after LUL.

**Comment by ttghnw** [comment]
I killed him four times in the leveling to 20, on the twin ziggs and twice in deatholme xD

But yes Masophet might have bugged his respawn shd be quite fast

**Comment by Giantulol** [comment]
> Its here https://imgur.com/a/Os9nEPj

Well I seriously waited for atleast 30 minutes, just departed.

**Comment by The14me** [comment]
u waited on the wrong place.Wisp Smaily on Disco.

**Comment by ttghnw** [comment]
I also opened a separate ticket on whiterlimb.

**Comment by Giantulol** [comment]
> u waited on the wrong place.Wisp Smaily on Disco.

Okay thanks, at least its not bugged then :). Sorry about the hassle then.

**Comment by The14me** [comment]
Mob have more than one spawn point.Will close the issue.
