### ISSUE TITLE
Dr. Whiterlimb respawning too much

### ISSUE THREAD

**Issue by ttghnw** [Atlantiss/NetherwingBugtracker#1015]
[//]: # (Enclose links to things related to the bug using http://wowhead.com or any other TBC database.)
[//]: # (You can use screenshot ingame to visual the issue.)
[//]: # (Write your tickets according to the format:)
[//]: # ([Quest][Azuremyst Isle] Red Snapper - Very Tasty!)
[//]: # ([NPC] Magistrix Erona)
[//]: # ([Spell][Mage] Fireball)
[//]: # ([Npc][Drop] Ghostclaw Lynx)
[//]: # ([Web] Armory doesnt work)

**Description**: 
The rare elite of the ziggurats currently has a too fast respawn. On a deatholme questing session, I managed to find him twice in two ziggurats under 5-7 minutes, I'm not entirely sure this is normal for a rare elite. Before on the course of leveling I also killed him in the twin ziggurats, please investigate.

**Expected behaviour**: 
Likely a reduced respawn rate.
**Server Revision**:

**Comment by Evolvee** [comment]
Should be 2 hours.

**Comment by Evolvee** [comment]
lol someone forgot to pool him so he is spawned X times ^^

**Comment by Evolvee** [comment]
rev xdd

**Comment by ttghnw** [comment]
=D =D

**Comment by aresbrutus** [comment]
This is actually how it is supposed to work, so it will be reverted https://www.wowhead.com/npc=22062/dr-whitherlimb#comments

**Comment by ttghnw** [comment]
Yes well, I don't quite recall him from retail, some commentaries do refer a 2 hour spawn and some say they killed him consecutively. Since rare elites usually have slow respawns, this makes it wierd for him to spawn so much specially always dropping green loot. Like this you can literally farm him since it's possible to solo.

**Comment by Shanghi** [comment]
The thing about being in a few places at once is normal even though it makes no sense. There's an elf in one of the TBC Alliance starting places that acts the same way too.

**Comment by Tereneckla** [comment]
Seems like multiple spawns with 2 hours timer as described in those comments now.
Fixed, I think.
