### ISSUE TITLE
[Environment] Rain in Dun Morogh

### ISSUE THREAD

**Issue by Gniddikon** [Atlantiss/NetherwingBugtracker#1016]
**Description**: It's currently raining in Dun Morogh, despite snow being all around.

**Current behaviour**: Rain in Dun Morogh.

**Expected behaviour**: There should only be snow in Dun Morogh.

**Server Revision**: 2105

**Comment by The14me** [comment]
Confirm https://wow.gamepedia.com/Weather_effects

**Comment by pelekon** [comment]
this zone doesn't have rain assigned, closing as invalid
