### ISSUE TITLE
[NPC] Stromgarde Keep - missing NPC's in one room.

### ISSUE THREAD

**Issue by Firroth** [Atlantiss/NetherwingBugtracker#1017]
[NPC] Syndicate Conjuror, Syndicate Thief

**Current behaviour**:
There is no NPC's in lower floor on Stromgarde Keep.

![screenshot_1](https://user-images.githubusercontent.com/43505196/46288311-8eafac80-c585-11e8-9bb2-39dfc292f801.png)

**Expected behaviour**: 
There should be at least 2 NPC's in lower room of Stromgarde Keep, as seen on the video.

![screenshot_2](https://user-images.githubusercontent.com/43505196/46288327-95d6ba80-c585-11e8-808c-74ee77ec5600.png)

https://www.youtube.com/watch?v=RxA-Jmc3Wf4 at 1:57

**Server Revision**: 
2105

**Comment by Evolvee** [comment]
rev xdd
