### ISSUE TITLE
[NPC]Foreman Bonds's#2305 adds [NPC]Dun Garok Soldier#736 don't despawn quick enough

### ISSUE THREAD

**Issue by Tenoutoften** [Atlantiss/NetherwingBugtracker#1018]
**Description**: 
[[NPC]Foreman Bonds#2305](https://db.excalibur.ws/?npc=2305#abilities) will spawn two adds [[NPC]Dun Garok Soldier#7360](https://db.excalibur.ws/?npc=7360#abilities) when he is about to die. These are indicated to despawn rather quickly by [wowhead comment - Patch 2.0.1](https://www.wowhead.com/quest=539/deprecated-battle-of-hillsbrad#comments:id=14060)

> I then pulled Bonds, using fear and Mind Flay when the dwarves appeared. The dwarves will die automatically a short after Bonds' death because I only killed one of them but they both died. 

[wowhead comment - patch 2.1.3](https://www.wowhead.com/quest=539/deprecated-battle-of-hillsbrad#comments:id=119399)
> The Dwarfs can be a problem, but you can just run a little away, then they stop following you, and dissappear... you dont have to run far away before they turn back...

Also indicates that reset mechanics like vanish will force despawn the adds, being a paladin I cant test this.
[wowhead comment - patch 2.4.2](https://www.wowhead.com/quest=539/deprecated-battle-of-hillsbrad#comments:id=292355)
> * When foreman dies, hit Vanish and Sprint to a safe area. His adds will disappear and not give chase.

**Current behaviour**:
[[NPC]Dun Garok Soldier#7360](https://db.excalibur.ws/?npc=7360#abilities) will hang around for ~5-7 minutes or so

**Expected behaviour**: 
I'd expect the adds to be automatically despawned within 1 minute, maybe 30 seconds.

**Server Revision**: 
2105

**Comment by Evolvee** [comment]
rev xdd
