### ISSUE TITLE
[NPC][Spell] Syndicate Sentry - Shield Wall

### ISSUE THREAD

**Issue by Firroth** [Atlantiss/NetherwingBugtracker#1019]
[NPC] [Syndicate Sentry ](http://wowwiki.wikia.com/wiki/Syndicate_Sentry)
[Spell] Shield Wall

**Current behaviour**:
He uses Shield wall on timer 30-35s, during this time he is dead so he won't even activate the spell in most cases.

![screenshot_1](https://user-images.githubusercontent.com/43505196/46289990-e69ce200-c58a-11e8-99a9-fdf0a25997c7.png)

**Expected behaviour**: 
Most mobs use it when low on hp (20-30%) so I assume here should be no exception.

**Server Revision**: 
2105

**Comment by The14me** [comment]
Duplicate of https://github.com/Atlantiss/NetherwingBugtracker/issues/924

**Comment by Firroth** [comment]
Why has this issue been marked as duplicate? xD 
Sure it's about the same "NPC" but not about the same mechanic. #924 was about missing skills, and this one is about mechanic/use the skill. So it shouldn't be duplicate from my point of view.

**Comment by Easyfraggy** [comment]
Shield wall is updated to be on % instead of timer on rev xdd once it is applied (not yet). It was discussed on discord sorry that it didn't reflect from the comments on the other thread.
