### ISSUE TITLE
[Quest][Durotar] Dark Storms

### ISSUE THREAD

**Issue by Thugli** [Atlantiss/NetherwingBugtracker#102]
Quest ID: 806

**Description**: 
Fizzle Darkstorm's imp minion did not despawn once Fizzle died.
**Current behaviour**:
Upon killing Fizzle Darkstorm, his imp minion did not despawn and continued casting at me until I killed him separately. 
**Expected behaviour**: 
I'm not entirely sure how npc pets are supposed to act, but I had thought that imps were meant to despawn once their owner was killed.
**Server Revision**:

**Comment by Wolffenstein** [comment]
They despawn after evade (if their master is dead). Blizzlike.
