### ISSUE TITLE
[NPC]Foreman Bonds's#2305 adds [NPC]Dun Garok Soldier#736 don't attack right away

### ISSUE THREAD

**Issue by Tenoutoften** [Atlantiss/NetherwingBugtracker#1020]
**Description**: 
[[NPC]Foreman Bonds#2305](https://db.excalibur.ws/?npc=2305#abilities) will spawn two adds [[NPC]Dun Garok Soldier#7360](https://db.excalibur.ws/?npc=7360#abilities) when he is about to die. 
When they are spawned they sit there doing nothing for about 2 seconds before they finally start to attack.

**Expected behaviour**: 
I'd expect them to attack immediately

**Server Revision**: 
2105

**Comment by Evolvee** [comment]
rev xdd
