### ISSUE TITLE
Pick Lock + Lockbox + Mail = Bug.

### ISSUE THREAD

**Issue by Neophrone** [Atlantiss/NetherwingBugtracker#1021]
[//]: # (Enclose links to things related to the bug using http://wowhead.com or any other TBC database.)
[//]: # (You can use screenshot ingame to visual the issue.)
[//]: # (Write your tickets according to the format:)
[//]: # ([Quest][Azuremyst Isle] Red Snapper - Very Tasty!)
[//]: # ([NPC] Magistrix Erona)
[//]: # ([Spell][Mage] Fireball)
[//]: # ([Npc][Drop] Ghostclaw Lynx)
[//]: # ([Web] Armory doesnt work)

**Description**: If I opened Lockbox by Pick Lock - Lockbox became simple box, that any player can open just by right-clicking on it. But if I'll send this opened lockbox by mail - on delivery lockbox will be locked again.

Screenshots:
1) Locked Lockbox (before I used Pick Lock on it).
![wowscrnshot_100118_161454](https://user-images.githubusercontent.com/43533040/46293122-38e5ff00-c59b-11e8-9ca7-f52b494f1cb6.jpg)
2) Opened Lockbox (after I used Pick Lock on it).
![wowscrnshot_100118_161450](https://user-images.githubusercontent.com/43533040/46293149-4c916580-c59b-11e8-8bc4-63033e3302d2.jpg)
3) The same Lockbox after delivery by mail.
![wowscrnshot_100118_161612](https://user-images.githubusercontent.com/43533040/46293150-4ef3bf80-c59b-11e8-9e35-e90259fd230f.jpg)

**Current behaviour**: Opened lockboxes became locked again after mail delivery. This bug can be abuse, simply by opening lockboxes - sending them to alt, and then send them back and open again. So you can level up u'r pick lock skill easier. Also since I can't send to people their lockboxes in opened state, I must take the content of boxes (greens and sometimes blues) and send it to players, which isn't safe because it can be a way of cheating, simply by changing item with another worse item.

**Expected behaviour**: After opening, lockboxes should never become locked again, even after sending it by mail.

**Server Revision**: 2105.

**Comment by toto6** [comment]
Fixed in Server Revision 2134.

There is however a visual issue that shows the box as locked in the mail interface. 
But when you loot the item from the mail and look at it in your inventory, it is as expected unlocked.
