### ISSUE TITLE
[NPC] [Spell] Mudrock Spikeshell Barbs ability triggering twice on hit

### ISSUE THREAD

**Issue by FrozenBread** [Atlantiss/NetherwingBugtracker#1022]
[//]: # (Enclose links to things related to the bug using http://wowhead.com or any other TBC database.)
[//]: # (You can use screenshot ingame to visual the issue.)
[//]: # (Write your tickets according to the format:)
[//]: # ([Quest][Azuremyst Isle] Red Snapper - Very Tasty!)
[//]: # ([NPC] Magistrix Erona)
[//]: # ([Spell][Mage] Fireball)
[//]: # ([Npc][Drop] Ghostclaw Lynx)
[//]: # ([Web] Armory doesnt work)

**Description**: Mudrock Spikeshell's (ID:4397) trigger on hit (receiving) ability Barbs (ID:8393) is currently triggering twice per hit received.

**Current behaviour**: Mudrock Spikeshell's (ID:4397) trigger on hit (receiving) ability Barbs (ID:8393) is currently triggering twice per hit received.

**Expected behaviour**: The ability should trigger only once, emulating a thorns effect type aura.

**Server Revision**: 
2105

**Comment by Evolvee** [comment]
works fine for me, u could screenshot combat log?
