### ISSUE TITLE
[NPC]Foreman Bonds#2305 doesn't use Devotion Aura#643 on spawn

### ISSUE THREAD

**Issue by Tenoutoften** [Atlantiss/NetherwingBugtracker#1023]
**Description**: 
[[NPC]Foreman Bonds#2305](https://db.excalibur.ws/?npc=2305#abilities) first activates his [[Spell]Devotion Aura#643](https://db.excalibur.ws/?spell=643) on pull. Much like a lot of other NPCs who keep their Ice/Frost Armor up and Lightning Shield as I have reported previously here(fixed already): https://github.com/Atlantiss/NetherwingBugtracker/issues/516 I don't see why [[NPC]Foreman Bonds#2305](https://db.excalibur.ws/?npc=2305#abilities) wouldn't keep his [[Spell]Devotion Aura#643](https://db.excalibur.ws/?spell=643) up. And on disengage he deactivates his aura.

**Expected behaviour**: 
Expected to keep [[Spell]Devotion Aura#643](https://db.excalibur.ws/?spell=643) activated out of combat

**Server Revision**: 
2105

**Comment by Evolvee** [comment]
rev xdd
