### ISSUE TITLE
Net cancelling food eating

### ISSUE THREAD

**Issue by Erodraeda** [Atlantiss/NetherwingBugtracker#1025]
[//]: # (Enclose links to things related to the bug using http://wowhead.com or any other TBC database.)
[//]: # (You can use screenshot ingame to visual the issue.)
[//]: # (Write your tickets according to the format:)
[//]: # ([Quest][Azuremyst Isle] Red Snapper - Very Tasty!)
[//]: # ([NPC] Magistrix Erona)
[//]: # ([Spell][Mage] Fireball)
[//]: # ([Npc][Drop] Ghostclaw Lynx)
[//]: # ([Web] Armory doesnt work)

**Description**: 
Whenever I'm killing a mob that nets me on the ground, and start eating while the debuff is still on me, when the net debuff ends, the food eating is cancelled.
**Current behaviour**:
The food eating is getting cancelled by the other aura's finish
**Expected behaviour**: 
Shouldn't cancel the food eating proccess.
**Server Revision**: 2105

**Comment by Tenoutoften** [comment]
Possibly dublicate with https://github.com/Atlantiss/NetherwingBugtracker/issues/843
I've also had a guildie tell me that when DoTs effect expire his drinking/eating is interrupted.

**Comment by Evolvee** [comment]
duplicate ^^
