### ISSUE TITLE
Wolves Across the Border, wrong text in the progress section

### ISSUE THREAD

**Issue by fishworld** [Atlantiss/NetherwingBugtracker#1026]
**Description**: 

One extremely minor bug, but still a bug. Also I reckon there are plenty more of this variety. When you're about to turn in the quest Wolves Across the Border, the progress section reads:
 
"Hey [player name]. How goes the hunt for **diseased young wolves**?"

a) these wolves are not diseased, they got diseased in some WotlK patch
b) it should read: 

"Hey <name>. I'm getting hungry...did you get that tough wolf meat?"

Source: http://db.hellfire-tbc.com/?quest=33

It's strange that a 2.4.3 version is using the updated version (3.x) of quests

**Comment by Evolvee** [comment]
rev xdd
