### ISSUE TITLE
[Quest] Cuergo's Gold event doesn't work.

### ISSUE THREAD

**Issue by Jezofine** [Atlantiss/NetherwingBugtracker#1028]
**Description**:
[Cuergo's Gold](https://www.wowhead.com/quest=2882)

**Current behaviour**:
There is [Inconspicuous Landmark](https://www.wowhead.com/object=142189) , but after using it nothing happens. It cannot be used again for some time, resets after about 5 mins.

**Expected behaviour**: 
> 2008/06/04 (Patch 2.4.2)
> 5 Pirates spawn, each of them have about 25% chance to drop the key. Chest will also spawn so when you get the key you turn it in right there and get your booty.

[Pirate's Treasure](https://www.wowhead.com/object=142194/pirates-treasure)
[Spawned pirates](https://www.wowhead.com/search?q=treasure+hunting#npcs)
Also comments on Cuergo's Gold state that there can be multiple Landmarks at the same time, but it's not clear how it should work with quest completion.

**Server Revision**: 2105

**Comment by Evolvee** [comment]
fully rewritten in rev xdd
