### ISSUE TITLE
[NPC] Bleakheart Shadowstalker - Bleakheart Satyr

### ISSUE THREAD

**Issue by Retinus** [Atlantiss/NetherwingBugtracker#1029]
**Description**: From [Bleakheart Satyr](https://wow.gamepedia.com/Bleakheart_Satyr)
Bleakheart Satyrs were once able to cast a 3 min curse upon the player, the curse was often considered one of the most annoying spells in the game, since it had a chance to afflict you with the following debuff:
Chest Pains — Agonizing chest pains afflict the target, stunning it for 5 sec.

**Current behaviour**: When you pull Bleakheart Shadowstalker Or Bleakheart Satyr there is a chance that they will debuff themselves with Chest Pains.

**Expected behaviour**: Bleakheart Shadowstalker And Bleakheart Satyr shouldn't be affected with Chest Pains debuff. Also Bleakheart Satyr should debuff you with a curse (dunno the name) that has a chance to apply the Chest Pains.

**Server Revision**: 2105

**Comment by Evolvee** [comment]
its already reported https://github.com/Atlantiss/NetherwingBugtracker/issues/497
