### ISSUE TITLE
Dark Iron Steamsmith

### ISSUE THREAD

**Issue by Piledriversn** [Atlantiss/NetherwingBugtracker#1030]
https://www.wowhead.com/npc=5840/dark-iron-steamsmith

![image](https://user-images.githubusercontent.com/43560552/46304682-fad5e480-c574-11e8-9e99-049c82e6f9b5.png)

[//]: # ([Quest][Searing Gorge] STOLEN: Smithing Tuyere and Lookout's Spyglass)
[//]: # ([NPC] Dark Iron Steamsmith)
**Description**: There is a total of 5 spawn points. With the drop rate of about 12% it makes it hard to get the Smithing Tuyere.

**Current behaviour**:

**Expected behaviour**: 

**Server Revision**:

**Comment by Thorgrimme** [comment]
This is not a bug though, it is as it should be from retail as far as I rememer.

**Comment by aresbrutus** [comment]
https://i.imgur.com/946HxqU.png

https://www.wowhead.com/item=18959/smithing-tuyere#comments

Blizzlike mob spawns + drop chance.
