### ISSUE TITLE
Skinning Before Beast is Looted

### ISSUE THREAD

**Issue by DeadlyMemory** [Atlantiss/NetherwingBugtracker#1031]
[//]: # (Enclose links to things related to the bug using http://wowhead.com or any other TBC database.)
http://wowwiki.wikia.com/wiki/Skinning
A skinner can skin corpses that were killed by other characters as long the corpse has been looted and the other character has not skinned it already.
[//]: # (You can use screenshot ingame to visual the issue.)
https://imgur.com/a/jpzl0OS
[//]: # (Write your tickets according to the format:)
[//]: # ([NPC] Plainstrider)
[//]: # ([Spell][Profession] Skinning)

**Description**: 
Beasts can be skinned prior to being looted.
**Current behaviour**:
Beasts can be skinned prior to being looted.
**Expected behaviour**: 
Beasts must be looted prior to be eligible for skinning.

**Server Revision**: 
Alter profession requirement to require beats be looted prior to allowing for skinning to take place.

**Comment by Easyfraggy** [comment]
Need confirmation that this is actually happening.

**Comment by cabapek** [comment]
Just tried it on revision 2304

You can not skin it while the other person has not looted it yet. Your cursor changes to the "skinning icon", which I do not know if is how it should be or not.

**Comment by nullfoxh** [comment]
At level 40 something and I have grouped a lot. I have never been able to skin something before it's looted. 

However I'm pretty sure you shouldn't be getting the skinning cursor before the mob is looted by others players and is actually skinnable (as happens now.)

**Comment by Tereneckla** [comment]
Fixed
