### ISSUE TITLE
Fearie Fire not stopping stealth

### ISSUE THREAD

**Issue by Erodraeda** [Atlantiss/NetherwingBugtracker#1032]
[//]: # (Enclose links to things related to the bug using http://wowhead.com or any other TBC database.)
[//]: # (You can use screenshot ingame to visual the issue.)
[//]: # (Write your tickets according to the format:)
[//]: # ([Quest][Azuremyst Isle] Red Snapper - Very Tasty!)
[//]: # ([NPC] Magistrix Erona)
[//]: # ([Spell][Mage] Fireball)
[//]: # ([Npc][Drop] Ghostclaw Lynx)
[//]: # ([Web] Armory doesnt work)

**Description**: 
The mob Highvale Ranger (2694)'s Fearie Fire isn't making you unable to stealth.
**Current behaviour**:
![screenshot_517](https://user-images.githubusercontent.com/40346279/46306694-5f03a300-c58b-11e8-9253-f220191b0065.png)
**Expected behaviour**: 
Shouldn't be able to stealth while afflicted by Fearie Fire
**Server Revision**: 2105

**Comment by Evolvee** [comment]
https://github.com/Atlantiss/NetherwingBugtracker/issues/315
