### ISSUE TITLE
[Quest][Ashenvale] Supplies to Auberdine

### ISSUE THREAD

**Issue by Moistowelette** [Atlantiss/NetherwingBugtracker#1033]
[//]: # (Enclose links to things related to the bug using http://wowhead.com or any other TBC database.)
[//]: # (You can use screenshot ingame to visual the issue.)
[//]: # (Write your tickets according to the format:)
[//]: # ([Quest][Azuremyst Isle] Red Snapper - Very Tasty!)
[//]: # ([NPC] Magistrix Erona)
[//]: # ([Spell][Mage] Fireball)
[//]: # ([Npc][Drop] Ghostclaw Lynx)
[//]: # ([Web] Armory doesnt work)

**Description**: 
In this quest you are supposed to escort NPC [Feero Ironhand] from Maestra's Post Ashenvale to the border of Darkshore. During the escort mission you get ambushed three times by various types of enemies. https://db.excalibur.ws/?quest=976 
**Current behaviour**:
If Feero Ironhand dies his body glides across the ground towards the next ambush point, where the ambush won't take place and the quest ultimately can no longer be finished. After you abandon the quest you can take it again. It took me a few tries to finish it, because the quest is quite hard for it's level (not a bug). But I finished it even though Feero died after the third ambush, yet his dead body slid to the final destination.
**Expected behaviour**: 
After Feero Ironhide dies the quest should indicate that it has failed and should reset at the NPC in Maestra's Post.
**Server Revision**: 
2105

**Comment by Evolvee** [comment]
should be better in rev `xdd`
