### ISSUE TITLE
Joonho's Mercy (Sword, on hit effect)

### ISSUE THREAD

**Issue by Erodraeda** [Atlantiss/NetherwingBugtracker#1036]
[//]: # (Enclose links to things related to the bug using http://wowhead.com or any other TBC database.)
[//]: # (You can use screenshot ingame to visual the issue.)
[//]: # (Write your tickets according to the format:)
[//]: # ([Quest][Azuremyst Isle] Red Snapper - Very Tasty!)
[//]: # ([NPC] Magistrix Erona)
[//]: # ([Spell][Mage] Fireball)
[//]: # ([Npc][Drop] Ghostclaw Lynx)
[//]: # ([Web] Armory doesnt work)

**Description**: 
The sword Joonho's Mercy has a on hit chance of casting an Arcane Blast on that target. The proc chance seems off, since it's not proccing as often as it should.
**Current behaviour**:
I killed 20-30 mobs, and only had 1 or 2 procs.
**Expected behaviour**: 
https://www.wowhead.com/item=17054/joonhos-mercy#comments
According to the comment below, the effect should proc often
![screenshot_518](https://user-images.githubusercontent.com/40346279/46307732-1b5e6880-c58e-11e8-9c36-d921b1ad039a.png)
**Server Revision**:

**Comment by Evolvee** [comment]
the current PPM change is same as TC335 rn, I would need more evidence/info on what it should be to change this...

**Comment by SwiftieTBC** [comment]
2 Comments from alla 
 Posted: Oct 29th 2006 11:20pm | IP: Logged | Reply to thistcwleblanc
Score: Decent
according to the dps cosmos ui its proc'd 40 times in 2000 swings, though it is in my offhand. still...i dont think thats too good...

Sabrr
11 posts
Score: Decent
You'll be looking at ~3% proc rate with this sword. It doesn't seem like much, but it really does proc quite often for the amount of damage the proc does.

**Comment by Peglaa** [comment]
One thottbot comment also implied it doesn't proc very often but didn't provide any numbers.

**Comment by The14me** [comment]
proc later from player side isnt flat.May proc 2 time's in 10 hit's...may proc 2 time's in 50 hit's.Please if find More info/number's PM to re-open the issue.
