### ISSUE TITLE
[Pathfinding][Mob AI] Mobs not following / waiting for players?

### ISSUE THREAD

**Issue by Unfairy** [Atlantiss/NetherwingBugtracker#1037]
There is some problem with mobs AI / pathfinding, I saw it few times when you pull the mob and run to them, sometimes they stay and wait for you to come to them.
Also I recorded the video of mob staying and not following you when you do backside jumps, I think those two thigns are related, if needed can try to record proof for 1st one.
Proof for 2nd:
![pathfinding problem](https://user-images.githubusercontent.com/41975070/46308994-62af1e00-c5bb-11e8-82c5-c614b3508670.gif)
![pathfinding problem 2](https://user-images.githubusercontent.com/41975070/46309006-6b075900-c5bb-11e8-9193-f5b582a7f454.gif)

**Comment by Easyfraggy** [comment]
Duplicate https://github.com/Atlantiss/NetherwingBugtracker/issues/972
