### ISSUE TITLE
Low HP visual bug.

### ISSUE THREAD

**Issue by Unfairy** [Atlantiss/NetherwingBugtracker#1038]
Players sometimes have low HP visual bug outside of party / when you buff them (if they outside of party).
Pets including.
![wowscrnshot_100118_213034](https://user-images.githubusercontent.com/41975070/46309144-cd605980-c5bb-11e8-8d65-9ee9f4248b8e.jpg)
![wowscrnshot_100118_213033](https://user-images.githubusercontent.com/41975070/46309145-cd605980-c5bb-11e8-93e2-80ca09fd5cf5.jpg)

**Comment by Easyfraggy** [comment]
https://github.com/Atlantiss/NetherwingBugtracker/issues/175

**Comment by Wolffenstein** [comment]
Fixed in rev 2211.
