### ISSUE TITLE
[NPC][Desolace] Kodo Apparition

### ISSUE THREAD

**Issue by DeltaLoads** [Atlantiss/NetherwingBugtracker#1039]
[//]: # (Enclose links to things related to the bug using http://wowhead.com or any other TBC database.)
[//]: # (You can use screenshot ingame to visual the issue.)
[//]: # (Write your tickets according to the format:)
[//]: # ([Quest][Azuremyst Isle] Red Snapper - Very Tasty!)
[//]: # ([NPC] Magistrix Erona)
[//]: # ([Spell][Mage] Fireball)
[//]: # ([Npc][Drop] Ghostclaw Lynx)
[//]: # ([Web] Armory doesnt work)
https://www.wowhead.com/npc=11521/kodo-apparition
**Description**: 
During Bone Collection quest these kodos spawn as you pick up Kodo Bones and after you kill them they are skinnable, which they shouldn't be as they are spirits
**Current behaviour**:
Kodo Apparition are skinnable
**Expected behaviour**: 
Kodo Apparition shouldn't be skinnable

![wowscrnshot_100118_205744 - copy](https://user-images.githubusercontent.com/43690147/46309787-c1759700-c5bd-11e8-9462-931793c7fbf2.jpg)

**Comment by Evolvee** [comment]
rev xdd
