### ISSUE TITLE
[NPC] Ferocitas the Soul Eater

### ISSUE THREAD

**Issue by DoctorRaymos** [Atlantiss/NetherwingBugtracker#104]
> Discord user Reisteel#2932

Reports that Ferocitas the Soul Eater respawn timer is too high currently. If you kill him and die immediately afterwards, you won't be able to loot the corpse even if you respawn in approximately 1 minute after death.

**Comment by aresbrutus** [comment]
Are you saying that his corpse despawns too fast and that you are unable to loot him when you run back from a corpse run?

**Comment by DoctorRaymos** [comment]
Yes, that is what the player is reporting.

**Comment by Wolffenstein** [comment]
Fixed in rev 2026.
