### ISSUE TITLE
[NPC][Spell] Venture Co. Strip Miner

### ISSUE THREAD

**Issue by Firroth** [Atlantiss/NetherwingBugtracker#1040]
[NPC] [Venture Co. Strip Miner](https://www.wowhead.com/npc=674/venture-co-strip-miner#abilities)
[Spell] [Throw Dynamite](https://www.wowhead.com/spell=7978/throw-dynamite)

**Current behaviour**:
Just tank and spank.

**Expected behaviour**: 
He should throw dynamites at the player.
[Throw Dynamite](https://www.wowhead.com/spell=7978/throw-dynamite)

**Server Revision**: 
2105

**Comment by Evolvee** [comment]
the spell had 10-40 yard range requirement, meaning u had to be in that range in order for the mob to cast the dynamite on you

replaced the spell ID in rev xdd
