### ISSUE TITLE
[NPC] Mob just froze not taking damage anymore.

### ISSUE THREAD

**Issue by Jezofine** [Atlantiss/NetherwingBugtracker#1041]
**Current behaviour**:
I used some spells on mob then started wanding him, then he just stuck with 22 hp not receiving any damage. He was in this state for several minutes, cause I thought that server died.
He likely was fleeing, but stuck for some reason.
I received weapon points from hitting him. After using Mind Control on him, he instantly died.
[GIF is too big to embed](https://giphy.com/gifs/xWC0Gq0QrE0duvmiB9/fullscreen)
I don't know WTF happened, did nothing special.

**Server Revision**: 2105

**Comment by Easyfraggy** [comment]
When it's a specific mob it helps if you do .npc info on it and post entry+id - for next time =)

**Comment by Jezofine** [comment]
I don't think it's mob specific, I was farming this area and this particular spawn for a long time.

**Comment by Manaci** [comment]
GIF is dead so useless, Most likely the invincible mobs in Blasted lands that you need to click a stone to kill
