### ISSUE TITLE
[Quest][Stormwind] The Attack! doesnt work correctly.

### ISSUE THREAD

**Issue by toki90** [Atlantiss/NetherwingBugtracker#1042]
**Description**: 
Cant complete the quest at the moment.

**Current behaviour**:
The mobs spawn and talk as they should but then you dont get credit for overhearing them. They turn yellow at some point and you can attack them. After a short time (before I could kill both) Lord Gregor Lescovar turns green and just walks back into the library.

**Expected behaviour**: 
https://www.youtube.com/watch?v=Io8EsfNb3Mw first part in this video. Should get the credit for the q after listening to the convo. Also not turn green halfway through (I dont have a source for this, maybe its timed for some odd reason).

**Server Revision**:

**Comment by Mikik3jr** [comment]
It worked for me.

**Comment by Evolvee** [comment]
slightly tweaked, make sure u are in line of sight when watching the conversation in order to get the credit

**Comment by Evolvee** [comment]
rev hehexd
