### ISSUE TITLE
Undercity elevators aren't working

### ISSUE THREAD

**Issue by Erodraeda** [Atlantiss/NetherwingBugtracker#1043]
[//]: # (Enclose links to things related to the bug using http://wowhead.com or any other TBC database.)
[//]: # (You can use screenshot ingame to visual the issue.)
[//]: # (Write your tickets according to the format:)
[//]: # ([Quest][Azuremyst Isle] Red Snapper - Very Tasty!)
[//]: # ([NPC] Magistrix Erona)
[//]: # ([Spell][Mage] Fireball)
[//]: # ([Npc][Drop] Ghostclaw Lynx)
[//]: # ([Web] Armory doesnt work)

**Description**: 
all the 3 elevators have stopped.
**Current behaviour**:
![screenshot_519](https://user-images.githubusercontent.com/40346279/46312512-a4c86780-c59b-11e8-96dd-f359d742e2af.png)
![screenshot_520](https://user-images.githubusercontent.com/40346279/46312514-a4c86780-c59b-11e8-932e-34d7bad1c59c.png)
**Expected behaviour**: 
Should work
**Server Revision**: 2105

**Comment by Peglaa** [comment]
rev 2100 must have broken it. @Wolffenstein

**Comment by Tenoutoften** [comment]
Worked fine for me earlier today

**Comment by Wolffenstein** [comment]
Possibly fixed in rev 2108. Please reopen if the problem still exists.
