### ISSUE TITLE
[NPC]Searing Infernal#6073 doesn't use [Spell]Fire Shield#18968

### ISSUE THREAD

**Issue by Tenoutoften** [Atlantiss/NetherwingBugtracker#1044]
**Description**: 
[[NPC]Searing Infernal#6073](https://www.wowhead.com/npc=6073/searing-infernal#abilities) doesn't use it's [[Spell]Fire Shield](https://db.excalibur.ws/?spell=18968) ability. Killed 10 and never saw it.

I found some videos from retail using their [[Spell]Fire Shield#32749](https://www.wowhead.com/spell=32749/fire-shield),figured I'd post them for what it is worth. Note that this is a different spellID and a 1 sec cast time rather than being instant.
https://youtu.be/ouHBxol8Ufo?t=38
https://youtu.be/2sZOZlLKqWk?t=125

**Current behaviour**:
[[NPC]Searing Infernal#6073](https://www.wowhead.com/npc=6073/searing-infernal#abilities) doesn't use any abilities.

**Expected behaviour**: 
I'd expect them to use [[Spell]Fire Shield](https://db.excalibur.ws/?spell=18968), and perhaps keep this buff up outside of combat as well as it has a 10 min duration.

**Server Revision**: 
2105

**Comment by Evolvee** [comment]
rev Xd
