### ISSUE TITLE
[NPC] Dark Iron Agent

### ISSUE THREAD

**Issue by Mikik3jr** [Atlantiss/NetherwingBugtracker#1045]
[//]: # (Enclose links to things related to the bug using http://wowhead.com or any other TBC database.)
[//]: # (You can use screenshot ingame to visual the issue.)
[//]: # (Write your tickets according to the format:)
[//]: # ([Quest][Azuremyst Isle] Red Snapper - Very Tasty!)
[//]: # ([NPC] Magistrix Erona)
[//]: # ([Spell][Mage] Fireball)
[//]: # ([Npc][Drop] Ghostclaw Lynx)
[//]: # ([Web] Armory doesnt work)

**Description**: 
We went to Gnomeregan and met some Dark Iron Agents. They put down Dark Iron Land Mines, that after 10 seconds they detonate and if you step on them they deal dmg
**Current behaviour**:
They don't deal any damage at all.
![image](https://user-images.githubusercontent.com/43505031/46315068-ac543480-c5cc-11e8-8549-8631d69166d9.png)
**Expected behaviour**: 
Sadly I don't know how much damage they deal, but they have to deal some dmg.
https://www.wowhead.com/spell=11802/dark-iron-land-mine#summons
**Server Revision**: 
2105

**Comment by Wolffenstein** [comment]
It will be fixed in revision 2107.
