### ISSUE TITLE
Gnomeregan passable pillar

### ISSUE THREAD

**Issue by Mikik3jr** [Atlantiss/NetherwingBugtracker#1046]
[//]: # (Enclose links to things related to the bug using http://wowhead.com or any other TBC database.)
[//]: # (You can use screenshot ingame to visual the issue.)
[//]: # (Write your tickets according to the format:)
[//]: # ([Quest][Azuremyst Isle] Red Snapper - Very Tasty!)
[//]: # ([NPC] Magistrix Erona)
[//]: # ([Spell][Mage] Fireball)
[//]: # ([Npc][Drop] Ghostclaw Lynx)
[//]: # ([Web] Armory doesnt work)

**Description**: 
There is a usual way in Gnomeregan to make the dungeon shorter. At Launch Bay part you can jump down to the lower level which is over the ground and from that you can jump to a pillar. That pillar's wall is not solid and you can walk over it.
**Current behaviour**:
![image](https://user-images.githubusercontent.com/43505031/46315306-621f8300-c5cd-11e8-962f-ae6e925789a7.png)
**Expected behaviour**: 
I shouldn't be able to cross walls.
**Server Revision**: 
2105

**Comment by Wolffenstein** [comment]
Clientside and blizzlike.
