### ISSUE TITLE
[NPC] Mechanized Sentry daze from front

### ISSUE THREAD

**Issue by Mikik3jr** [Atlantiss/NetherwingBugtracker#1047]
[//]: # (Enclose links to things related to the bug using http://wowhead.com or any other TBC database.)
[//]: # (You can use screenshot ingame to visual the issue.)
[//]: # (Write your tickets according to the format:)
[//]: # ([Quest][Azuremyst Isle] Red Snapper - Very Tasty!)
[//]: # ([NPC] Magistrix Erona)
[//]: # ([Spell][Mage] Fireball)
[//]: # ([Npc][Drop] Ghostclaw Lynx)
[//]: # ([Web] Armory doesnt work)

**Description**: 
There are some Mechanized Sentrys in Gnomeregan that you have to clear.
**Current behaviour**:
If this NPC attacks you from the front they can daze you. 
![image](https://user-images.githubusercontent.com/43505031/46315552-0acde280-c5ce-11e8-9873-185c7f006108.png)
**Expected behaviour**: 
I don't think they should daze you when they are attacking you face.
**Server Revision**: 
2105

**Comment by Fungiqt** [comment]
Think you made a mistake , its the concussive shot ability that the leparous defender have. https://www.wowhead.com/npc=6223/leprous-defender - altho it doesnt list this ability in 2.4.3 im almost certain they had this ability

**Comment by Easyfraggy** [comment]
If its concussive shot then they are using it in melee which is also wrong.

**Comment by Mikik3jr** [comment]
Then I am sorry, I didn't see the shot effect while tanking. That gnome back has the daze ability.

https://classicdb.ch/?npc=6223#abilities

**Comment by Fungiqt** [comment]
They arent using it as melee tho, from the screenshot you can see the lep gnome in the back thats the ranged mob that has the concussive shot.

**Comment by Easyfraggy** [comment]
I'll retest when i get home, im pretty sure i only had agro on the sentries when i tested it.

**Comment by Evolvee** [comment]
![image](https://user-images.githubusercontent.com/1942409/46557344-d0c05180-c8e9-11e8-9494-b4dfbb8a1fe3.png)

🤦‍♂️ 

rev Xd
