### ISSUE TITLE
[NPC] Hamhock gives Bloodlust out of combat

### ISSUE THREAD

**Issue by Mikik3jr** [Atlantiss/NetherwingBugtracker#1048]
[//]: # (Enclose links to things related to the bug using http://wowhead.com or any other TBC database.)
[//]: # (You can use screenshot ingame to visual the issue.)
[//]: # (Write your tickets according to the format:)
[//]: # ([Quest][Azuremyst Isle] Red Snapper - Very Tasty!)
[//]: # ([NPC] Magistrix Erona)
[//]: # ([Spell][Mage] Fireball)
[//]: # ([Npc][Drop] Ghostclaw Lynx)
[//]: # ([Web] Armory doesnt work)

**Description**: 
In The Stockade there is an ogre boss called Hamhock:
![image](https://user-images.githubusercontent.com/43505031/46315766-98113700-c5ce-11e8-997a-d660e5697168.png)
**Current behaviour**:
If I pull something that is in buff range of the boss the boss gives bloodlust to the enemies even when the boss is not in combat. He even says "I'll crush you!"
![image](https://user-images.githubusercontent.com/43505031/46315784-a52e2600-c5ce-11e8-82cf-bca8eb8f7e66.png)
**Expected behaviour**: 
I think the boss should give buffs when the boss is not in combat.
**Server Revision**: 
2015

**Comment by pelekon** [comment]
fixed in rev 2574
