### ISSUE TITLE
respawning at wrong graveyard

### ISSUE THREAD

**Issue by DarthNekr0s** [Atlantiss/NetherwingBugtracker#105]
**Description**:  i died at sunsail anchorage in the waters and it sent me all the way back to the graveyard in sunstrider isle

**Current behaviour**: being sent to very far away graveyard

**Expected behaviour**:  should be spawning at the graveyard in fairbreeze village like while you die if on land
![wowscrnshot_092318_111031](https://user-images.githubusercontent.com/16113944/45923167-8ae6af00-bf21-11e8-9115-aaa5f7733bb4.jpg)

**Server Revision**:

**Comment by toto6** [comment]
Fixed in Rev 2029
