### ISSUE TITLE
[NPC] Green Sludge, Jade Ooze - missing abilities.

### ISSUE THREAD

**Issue by Firroth** [Atlantiss/NetherwingBugtracker#1050]
[NPC] [Green Sludge](https://www.wowhead.com/npc=2655/green-sludge#abilities)
[Spell] [Corrosive Ooze](https://www.wowhead.com/spell=9459/corrosive-ooze)

[NPC] [Jade Ooze](https://www.wowhead.com/npc=2656/jade-ooze#abilities)
[Spell] [Diseased Slime](https://www.wowhead.com/spell=6907/diseased-slime)

**Current behaviour**:
Green Sludge and Jade Ooze doesn't use their respective skills. (currently tank and spank)

**Expected behaviour**: 
Green Sludge should use [Spell] [Corrosive Ooze](https://www.wowhead.com/spell=9459/corrosive-ooze), and Jade Ooze should be using [Spell] [Diseased Slime](https://www.wowhead.com/spell=6907/diseased-slime)

**Server Revision**: 
2108

**Comment by The14me** [comment]
Dont suppose to have this abilities in TBC.
https://i.imgur.com/2j9mEjz.png
https://i.imgur.com/7bF4UFW.png
Please if find any proof of it re-open it.
