### ISSUE TITLE
Maraudon, Landslide Boss

### ISSUE THREAD

**Issue by Erodraeda** [Atlantiss/NetherwingBugtracker#1051]
[//]: # (Enclose links to things related to the bug using http://wowhead.com or any other TBC database.)
[//]: # (You can use screenshot ingame to visual the issue.)
[//]: # (Write your tickets according to the format:)
[//]: # ([Quest][Azuremyst Isle] Red Snapper - Very Tasty!)
[//]: # ([NPC] Magistrix Erona)
[//]: # ([Spell][Mage] Fireball)
[//]: # ([Npc][Drop] Ghostclaw Lynx)
[//]: # ([Web] Armory doesnt work)

**Description**: 
The boss uses an ability called Landslide, which is channeled. It get's cancelled out of nowhere, as shown is the clip
**Current behaviour**:
https://clips.twitch.tv/ExuberantClumsyPeppermintTebowing
**Expected behaviour**: 
Shouldn't been cancelled
**Server Revision**:

**Comment by Easyfraggy** [comment]
https://github.com/Atlantiss/AtlantissTBCBT/issues/3971

**Comment by Evolvee** [comment]
fixed in rev Zeno FeelsWeirdMan
