### ISSUE TITLE
[NPC] Venture Co. Tinkerer

### ISSUE THREAD

**Issue by manslaughter** [Atlantiss/NetherwingBugtracker#1052]
**Description**: Level 40ish goblins in the middle of STV that summon a mechanical reaper minion.

**Current behaviour**: They summon the reaper as soon as they spawn even if not in combat.  The reaper then despawns a bit later and they won't use the summon in combat.

**Expected behaviour**: Attempts to summon the mechanical reaper in combat.

**Server Revision**: 2108

**Comment by Tereneckla** [comment]
Fixed
