### ISSUE TITLE
[Spell][NPC] Burning Tar

### ISSUE THREAD

**Issue by mbzz88** [Atlantiss/NetherwingBugtracker#1053]
**Description**: Burning Tar is triggered by non fire spells.

**Current behaviour**: Non fire attacks trigger debuff on mob
https://www.wowhead.com/spell=14797/burning-tar#comments
Used by NPCs https://www.wowhead.com/npc=6517 https://www.wowhead.com/npc=6518 https://www.wowhead.com/npc=6519 and https://www.wowhead.com/npc=6527/tar-creeper

**Expected behaviour**: Only fire attacks should trigger debuff

**Server Revision**: 2108

**Comment by Evolvee** [comment]
![image](https://user-images.githubusercontent.com/1942409/46574676-5229e980-c9a7-11e8-952a-e866a4c8f6dd.png)

**Comment by Jezofine** [comment]
Could not trigger Burning Tar debuff with spriest spells, but got it on nature wand damage.

**Comment by Tereneckla** [comment]
Could trigger Burning Tar with Shadowbolts.

**Comment by Wolffenstein** [comment]
Fixed in rev 3368.
