### ISSUE TITLE
[Core][Loot] Quest starter items that you've already used causes creatures to be lootable forever but with no loot shown

### ISSUE THREAD

**Issue by mbzz88** [Atlantiss/NetherwingBugtracker#1054]
**Description**: Occasionally, gorillas are permanently "lootable"

**Current behaviour**: Player loots items from mob, mob continues to sparkle, clicking results in looting animation but no result
https://youtu.be/opePKMNhCxg
Also, sometimes these mobs are looted correctly, but attempting to skin results in "Creature must be looted first"
![wowscrnshot_100218_150019](https://user-images.githubusercontent.com/43509267/46325249-ea486b80-c653-11e8-88db-62bd0967e6a1.jpg)
http://db.hellfire-tbc.com/?npc=6513 http://db.hellfire-tbc.com/?npc=6514 http://db.hellfire-tbc.com/?npc=6516

**Expected behaviour**: Correctly looted

**Server Revision**: 2108

**Comment by Erodraeda** [comment]
Happening not only to those, but to several mobs in the world.
![screenshot_521](https://user-images.githubusercontent.com/40346279/46356808-e0197380-c639-11e8-9e91-e7eb91c3ded9.png)
Here's an example. They always leave an empty slot behind.

**Comment by Jezofine** [comment]
This is Mangled Journal dropping multiple times. There are [comments on that in another issue](https://github.com/Atlantiss/NetherwingBugtracker/issues/1134#issuecomment-426575190) (#1134)

**Comment by Mikik3jr** [comment]
I confirm that it happens on multiple enemies in Un'Goro Crater.

**Comment by Mikik3jr** [comment]
Another note: In Winterspring the furbolgs drop quest starter item. I noticed after I got the item AFTER that this bug appeared.

**Comment by Tereneckla** [comment]
Fixed
