### ISSUE TITLE
[NPC] Sheri doesn't offer food

### ISSUE THREAD

**Issue by Regeneration19** [Atlantiss/NetherwingBugtracker#1056]
[//]: # (Enclose links to things related to the bug using http://wowhead.com or any other TBC database.)
[//]: # (You can use screenshot ingame to visual the issue.)
[//]: # (Write your tickets according to the format:)
[//]: # ([Quest][Azuremyst Isle] Red Snapper - Very Tasty!)
[//]: # ([NPC] Magistrix Erona)
[//]: # ([Spell][Mage] Fireball)
[//]: # ([Npc][Drop] Ghostclaw Lynx)
[//]: # ([Web] Armory doesnt work)

**Description**: 
Sheri at the Inn in the ruins of silvermoon doesn't sell anything to eat.
NPC Entry: 16259
https://www.wowhead.com/npc=16259/sheri#sells
**Current behaviour**:
Only sells water.
**Expected behaviour**: 
Should sell water and food.
**Server Revision**:

**Comment by Shanghi** [comment]
For some reason she didn't have food during TBC/WotLK: [Allakhazam](https://web.archive.org/web/20080508042459/http://wow.allakhazam.com:80/db/mob.html?wmob=16259) / [Thottbot](https://web.archive.org/web/20100225220809/http://thottbot.com/c16259) / [Wowhead](https://web.archive.org/web/20080430160521/http://www.wowhead.com:80/?npc=16259)

Maybe they were just trying to be fancy and force people to go to the cheese vendor outside!
