### ISSUE TITLE
Camp Mojache Inn

### ISSUE THREAD

**Issue by manslaughter** [Atlantiss/NetherwingBugtracker#1057]
**Description**: Inn in the horde outpost of Camp Mojache in Feralas.

**Current behaviour**: Does not give rested status.

**Expected behaviour**: Gives rested status.

**Server Revision**: 2108

**Comment by Wolffenstein** [comment]
Fixed in rev 2143.

**Comment by maxturtlesc2** [comment]
After further testing: when you're outside if you enter on the right side of the entrance, it does not give rested status; works fine if you enter in the middle or on the left of the entrance.

**Comment by agraff16** [comment]
> After further testing: when you're outside if you enter on the right side of the entrance, it does not give rested status; works fine if you enter in the middle or on the left of the entrance.

tested and works this way. annoying but at least it works

**Comment by Tereneckla** [comment]
Fixed
