### ISSUE TITLE
[Quest] A Little Help From My Friends

### ISSUE THREAD

**Issue by mbzz88** [Atlantiss/NetherwingBugtracker#1058]
**Description**: Ringo runs at players current speed
https://www.wowhead.com/quest=4491/a-little-help-from-my-friends

**Current behaviour**: Ringo https://www.wowhead.com/npc=9999/ringo follows player at players current speed, even mount speed when mounted

**Expected behaviour**: Ringo should move at running speed, regardless of players speed

**Server Revision**: 2108

**Comment by Tereneckla** [comment]
#5356
