### ISSUE TITLE
[Quest] Catch of the day

### ISSUE THREAD

**Issue by kkumbaya** [Atlantiss/NetherwingBugtracker#1059]
[//]: # (Enclose links to things related to the bug using http://wowhead.com or any other TBC database.)
[//]: # (You can use screenshot ingame to visual the issue.)
[//]: # (Write your tickets according to the format:)
[//]: # ([Quest][Azuremyst Isle] Red Snapper - Very Tasty!)
[//]: # ([NPC] Magistrix Erona)
[//]: # ([Spell][Mage] Fireball)
[//]: # ([Npc][Drop] Ghostclaw Lynx)
[//]: # ([Web] Armory doesnt work)

Mobs spawned by Shellfish traps don't attack the player

**Server Revision**: 2108

**Comment by Jezofine** [comment]
They did attack me, although not instantly.
