### ISSUE TITLE
Bat creature in Eversong

### ISSUE THREAD

**Issue by deku100** [Atlantiss/NetherwingBugtracker#106]
[//]: # (Enclose links to things related to the bug using http://wowhead.com or any other TBC database.)
[//]: # (You can use screenshot ingame to visual the issue.)
[//]: # (Write your tickets according to the format:)
[//]: # ([Quest][Azuremyst Isle] Red Snapper - Very Tasty!)
[//]: # ([NPC] Magistrix Erona)
[//]: # ([Spell][Mage] Fireball)
[//]: # ([Npc][Drop] Ghostclaw Lynx)
[//]: # ([Web] Armory doesnt work)

**Description**: Misplaced Bat Enemy

**Current behaviour**: Mistbat located outside Farstrider's Retreat, Eversong Woods.
![wowscrnshot_092218_211125](https://user-images.githubusercontent.com/43505181/45923180-8207c600-beac-11e8-8a9b-e078f2defb3a.jpg)

**Expected behaviour**: Mistbats shouldn't be in this area.

**Server Revision**:

**Comment by aresbrutus** [comment]
Will be fixed in the next rev.
