### ISSUE TITLE
[NPC] Jaedenar Hound

### ISSUE THREAD

**Issue by mbzz88** [Atlantiss/NetherwingBugtracker#1062]
**Description**: Jaedenar Hound has no cooldown on Mana Burn spell
http://db.hellfire-tbc.com/?npc=7125

**Current behaviour**: Mob spams mana burn the entire fight

**Expected behaviour**: Cooldown on Mana Burn

**Server Revision**: 2108

**Comment by Evolvee** [comment]
rev Xd
