### ISSUE TITLE
[NPC] Khan Dez'hepah

### ISSUE THREAD

**Issue by totaemoeggerli** [Atlantiss/NetherwingBugtracker#1063]
[//]: # (Enclose links to things related to the bug using http://wowhead.com or any other TBC database.)
[//]: # (You can use screenshot ingame to visual the issue.)
[//]: # (Write your tickets according to the format:)
[//]: # ([Quest][Azuremyst Isle] Red Snapper - Very Tasty!)
[//]: # ([NPC] Magistrix Erona)
[//]: # ([Spell][Mage] Fireball)
[//]: # ([Npc][Drop] Ghostclaw Lynx)
[//]: # ([Web] Armory doesnt work)

**Description**: 
Quest : https://www.wowhead.com/quest=1365/khan-dezhepah
NPC: https://www.wowhead.com/npc=5600/khan-dezhepah
Not sure if he should spawn on its own or after you kill mobs. 

**Current behaviour**:
Wasn't able to spawn the NPC. Killed mobs in the area for +20min. Khan Dez'hepah didn't spawn.

**Expected behaviour**:
By Dazer (376 – 1·5) on 2007/12/28 (Patch 2.3.0)
> He spawns in one of the two big tents. Can be either one.

This comment suggests that you have to kill mobs to make him spawn:
By Kreynor (1,938 – 10·27) on 2009/11/15 (Patch 3.2.2)
> The problem here is that the Battle Lords share spawnpoints with Destroyers and Windchasers too... so good luck farming the place to make that dude show up.

**Server Revision**: 2108

**Comment by Easyfraggy** [comment]
https://web.archive.org/web/20070616012705/http://www.wowhead.com:80/?npc=5600#M0z
> He shares spawnpoints with all the Kolkar Battle Lords.

**Comment by Jezofine** [comment]
I've seen him in 2 different tents, didn't have to kill any centaurs.

**Comment by aresbrutus** [comment]
There is no real mention of killing centaurs to make him spawn. Not in the quest text or comments. People often mistake that killing produces a named mob cause they didn't know he has multiple spawn points. 

Right now on NW he has 2 spawn points he can spawn on just like what the comments mention.

**Comment by femtaur** [comment]
doesnt spawn

**Comment by aresbrutus** [comment]
He does spawn, he has 2 possible locations where he can spawn though so you might have missed him.

**Comment by femtaur** [comment]
sry for not being more precise but last night he spawned initially after a crash and then never again. trust. everyone was talking about it in general and i know about his spawns. not trying to be rude but hes actually bugged.

**Comment by aresbrutus** [comment]
Crashes do cause a lot of issues so it could be very possible that it somehow stopped spawning. For now he seems to be working fine and will keep an eye on future issues with this guy. Thank you for reporting the issue.

**Comment by Jovzin** [comment]
Hello he is still not spawning. We were a group of 5 guys patrolling around the whole camp / checking the big two tents and he did not spawn at all. We were there for about 40-60 minutes and nothing.   
So he is still bugged

**Comment by Boxxy** [comment]
Adding to this thread that he is Spawning on a server restart, but he is not **Re**spawning.

**Comment by ShadyWins** [comment]
The issue persists.

We were a group of 5 people camping the two spawn points for nearly 90 minutes. Killing all mobs inside and outside the two large huts - still no spawn of the infamous Khan Dez'hepah.

**Comment by Huuhailija** [comment]
Just spent 2 hours killing centaurs and waiting spawn to either one of the tents. Didn't get any spawns. The issues persists.

**Comment by danbopes** [comment]
Can we reopen this? Seems to be related to #4569, and this issue still persists. Confirmed by me, reported by 3 others in #support channel/in game.

**Comment by Evolvee** [comment]
it is related, thats why this issue is closed
no need to have multiple reports open for 1 issue

**Comment by thestranger064** [comment]
hello! as of today 05/02 -2019 its still not working properly.

steps: killed battle lords at every location, and nothing
killed windchasers and maulers , just incase
camped both big tents

and nothing. sadly this one of those quest that everyone knows about, but nothing is done about it.

**Comment by danbopes** [comment]
@thestranger064 and anyone else who happens upon this. Open up a ticket, and the Game Masters can assist.

**Comment by Evolvee** [comment]
fixed in rev 2971
