### ISSUE TITLE
[Quest] Hints of a new plague?

### ISSUE THREAD

**Issue by Needorfeed** [Atlantiss/NetherwingBugtracker#1065]
**Description**: 
After having a failed go at the escort-part of this chain, both partymembers abandoned, to re-take the quest.
Only one player got to even see there was a new quest available, from the same npc.

**Current behaviour**:
Quest is not available to pick up after abandoning, in some cases.

**Expected behaviour**: 
Quest NPC should respawn after a while, reset, with a new quest, given the old one is abandoned.

**Server Revision**:

**Comment by Wolffenstein** [comment]
Fixed in rev 2138.
