### ISSUE TITLE
Scepter of Celebras Portal

### ISSUE THREAD

**Issue by Tinnoan** [Atlantiss/NetherwingBugtracker#1069]
Portal to inner Maraudon locks up after the 1st person uses the portal.

**Comment by sakxp** [comment]
Probably also happens with Mage's portals (same bug ocurred in felmyst)

**Comment by 5f3759** [comment]
IIRC on Felmyst it happened after the portal summoner entered the portal. Might be a similar bug.

**Comment by Tereneckla** [comment]
Fixed
