### ISSUE TITLE
[NPC][Loot] Crawler Mucus

### ISSUE THREAD

**Issue by DoctorRaymos** [Atlantiss/NetherwingBugtracker#107]
> Discord user Warnoxx#9697
> 
> Reporting that while doing the quest, "A Solvent Spirit", when killing Surf Crawlers, the drop rate for Crawler Mucus seems way too low.

Current research shows it at about 66% drop rate, but can do additional investigation if required.

**Comment by Wolffenstein** [comment]
Fixed in rev 2026.
