### ISSUE TITLE
[NPC] [Ashenvale] Warsong Peon bugged

### ISSUE THREAD

**Issue by toki90** [Atlantiss/NetherwingBugtracker#1070]
**Description**: 

**Current behaviour**:
Mob (87/55.2) stands there and doesnt find a path to you. Doesnt bug out though & evade spells. (https://imgur.com/LTCASw4)

**Expected behaviour**: 
Should find a path to you to fight you.

**Server Revision**:

**Comment by aresbrutus** [comment]
Works fine for me. Please comment if you can reproduce it still with more proof and step by step guide.
