### ISSUE TITLE
Investigating The Blue Recluse Quest bugged

### ISSUE THREAD

**Issue by samemari** [Atlantiss/NetherwingBugtracker#1071]
[//]: # (Enclose links to things related to the bug using http://wowhead.com or any other TBC database.)
[//]: # (You can use screenshot ingame to visual the issue.)
[//]: # (Write your tickets according to the format:)
[//]: # ([Quest][Azuremyst Isle] Red Snapper - Very Tasty!)
[//]: # ([NPC] Magistrix Erona)
[//]: # ([Spell][Mage] Fireball)
[//]: # ([Npc][Drop] Ghostclaw Lynx)
[//]: # ([Web] Armory doesnt work)

**Description**: 
There is class quest for mages in Ally side https://classicdb.ch/?quest=1920 It's bugged atm

**Current behaviour**:
Mage cannot get stun debuff on mob when quest item could be used, mage cannot kill the mob to try to use quest item on mob's remains. https://cdn.discordapp.com/attachments/297494762834100225/496633336303714314/WoWScrnShot_100218_131656.jpg

**Expected behaviour**: 
Successful using of the quest item on the mob with debuff you can see on this video (start viewing from 135s)
https://youtu.be/t0jFkP1k2ag?t=135
**Server Revision**: 
2108

**Comment by danbopes** [comment]
Confirmed. This may be a similar issue to #5518.

**Comment by Evolvee** [comment]
rev 2971

**Comment by q7w7e7r** [comment]
the problem is urgent
