### ISSUE TITLE
[Quest][Desolace]Portals of the Legion

### ISSUE THREAD

**Issue by totaemoeggerli** [Atlantiss/NetherwingBugtracker#1072]
[//]: # (Enclose links to things related to the bug using http://wowhead.com or any other TBC database.)
[//]: # (You can use screenshot ingame to visual the issue.)
[//]: # (Write your tickets according to the format:)
[//]: # ([Quest][Azuremyst Isle] Red Snapper - Very Tasty!)
[//]: # ([NPC] Magistrix Erona)
[//]: # ([Spell][Mage] Fireball)
[//]: # ([Npc][Drop] Ghostclaw Lynx)
[//]: # ([Web] Armory doesnt work)

**Description**:
[The quest](https://www.wowhead.com/quest=5581/portals-of-the-legion) can be completed without any problems. But there are few inaccuracies.

**Current behaviour**:
-cast time (5sec?)
-felguard doesn't attack
-portal despawns few moments after you've klicked it

**Expected behaviour**: 
Joana with time stamp: https://youtu.be/WMGp3FKj_6k?t=1m37s

-instantly, no cast time to klick portal use item
-felguard should attack immediatly (this happens with many objects/summoned creatures https://github.com/Atlantiss/NetherwingBugtracker/issues/1059)
-poral should despawn after the felguard is dead

I thought the range to klick it is way to high but that is legit:
By laerhof (5,792 – 4·14·56) on 2008/01/16 (Patch 2.3.2)

> You can stand at a long range away from the portals and thus the spawning Felgaurd when activating a portal. This is most useful for ranged classes, and warriors can then still charge the enemy.

**Server Revision**: 2108

**Comment by Wolffenstein** [comment]
Fixed in rev 3404.
