### ISSUE TITLE
[Quest][Bloodmyst Isle] Ending Their World

### ISSUE THREAD

**Issue by narayagh** [Atlantiss/NetherwingBugtracker#1073]
[//]: # (Enclose links to things related to the bug using http://wowhead.com or any other TBC database.)
[//]: # (You can use screenshot ingame to visual the issue.)
[//]: # (Write your tickets according to the format:)
[//]: # ([Quest][Azuremyst Isle] Red Snapper - Very Tasty!)
[//]: # ([NPC] Magistrix Erona)
[//]: # ([Spell][Mage] Fireball)
[//]: # ([Npc][Drop] Ghostclaw Lynx)
[//]: # ([Web] Armory doesnt work)

**Description**: 
Typo in the dialog on quest completion.

**Current behaviour**:
https://imgur.com/a/sePuaHK

**Server Revision**: 
2108

**Comment by danbopes** [comment]
Fixed rev 3118
