### ISSUE TITLE
[Quest][Desolace] Gelkris Alliance

### ISSUE THREAD

**Issue by totaemoeggerli** [Atlantiss/NetherwingBugtracker#1074]
[//]: # (Enclose links to things related to the bug using http://wowhead.com or any other TBC database.)
[//]: # (You can use screenshot ingame to visual the issue.)
[//]: # (Write your tickets according to the format:)
[//]: # ([Quest][Azuremyst Isle] Red Snapper - Very Tasty!)
[//]: # ([NPC] Magistrix Erona)
[//]: # ([Spell][Mage] Fireball)
[//]: # ([Npc][Drop] Ghostclaw Lynx)
[//]: # ([Web] Armory doesnt work)

**Description**: 
https://www.wowhead.com/quest=1368/gelkis-alliance
Reputation gain for Gelkris Clan Centaur is too high. Probably the same the other way around (didn't test).

**Current behaviour**:
https://imgur.com/a/y8qd4dz
+100 Gelkris
-500 Magram

**Expected behaviour**: 
+20 Gelkris
-100 Magram

Comment from WotLK
By paraffin (402 – 5·2) on 2009/06/09 (Patch 3.1.3)
> ...Each Magram you kill gain 20 reputation with Gelkis while decreasing 100 with Magram....

**Server Revision**: 2108

**Comment by Evolvee** [comment]
fixed in next rev
