### ISSUE TITLE
Rogue stealth in party 

### ISSUE THREAD

**Issue by Fungiqt** [Atlantiss/NetherwingBugtracker#1075]
**Description**: Rogue in party goes stealth not able to see him or heal him

**Current behaviour**: So im leveling with a rogue friend and when he goes stealth i cannot see him anymore even tho we are in a party and also cannot heal or shield him (playing priest myself). Looks like the stealth behaviour in party is the same as if we where not in a party.

**Expected behaviour**: Should be able to see the rogue in stealth if he is in party and heal him aswell.
Source: https://youtu.be/KO7Ht29IqBE?t=2m15s - as u can see the rogue vanishes but hydra is still able to see him and dispell/heal him

**Server Revision**: 2108

**Comment by Wolffenstein** [comment]
Fixed in rev 2110.

**Comment by totaemoeggerli** [comment]
this has been reported earlier: https://github.com/Atlantiss/NetherwingBugtracker/issues/248
