### ISSUE TITLE
[Quest][Bloodmyst Isle] Matis the Cruel - quest text showing completed without doing objectives

### ISSUE THREAD

**Issue by snerfy** [Atlantiss/NetherwingBugtracker#1076]
**Description**: 
Player can bring up quest rewards for Matis the Cruel without capturing Matis or completing any of the objectives.
**Current behaviour**:
![image](https://user-images.githubusercontent.com/43623148/46347354-3aeea300-c619-11e8-979a-4fea80043695.png)
![image](https://user-images.githubusercontent.com/43623148/46347369-4215b100-c619-11e8-98ef-b333294fb73f.png)

The player can click "Complete Quest" but nothing happens.
**Expected behaviour**: 
Quest should not display awards, but give intermediary quest text. Intermediary text according to http://web.archive.org/web/20080323075101/http://thottbot.com:80/q9711
> A soldier of Matis' stature won't be traveling alone. Be careful out there.

**Server Revision**: 
2108

**Comment by Evolvee** [comment]
fixed in next rev
