### ISSUE TITLE
[NPC] Snapjaw dmg is not right?

### ISSUE THREAD

**Issue by Mikik3jr** [Atlantiss/NetherwingBugtracker#1077]
[//]: # (Enclose links to things related to the bug using http://wowhead.com or any other TBC database.)
[//]: # (You can use screenshot ingame to visual the issue.)
[//]: # (Write your tickets according to the format:)
[//]: # ([Quest][Azuremyst Isle] Red Snapper - Very Tasty!)
[//]: # ([NPC] Magistrix Erona)
[//]: # ([Spell][Mage] Fireball)
[//]: # ([Npc][Drop] Ghostclaw Lynx)
[//]: # ([Web] Armory doesnt work)

**Description**: 
There are turtles in Hillsbrad Foothills. They are like lv 29-31 lvls high I am lv33 prot paladin at the moment.
**Current behaviour**:
Every time they attack they do constant dmg. Only 5, 5, 5, 5, 5. Its like the minimum and maximum dmg is the same for them, and not just that, but weak as well. I checked them with different amount of armor and without buffs.
![wowscrnshot_100218_145735](https://user-images.githubusercontent.com/43505031/46349935-c553f880-c653-11e8-948a-5d265e88d5ab.jpg)
![wowscrnshot_100218_144706](https://user-images.githubusercontent.com/43505031/46349940-c71dbc00-c653-11e8-9700-e62c1ab8d079.jpg)
![wowscrnshot_100218_144741](https://user-images.githubusercontent.com/43505031/46349943-c84ee900-c653-11e8-9a55-b56db7003c4b.jpg)
![wowscrnshot_100218_145144](https://user-images.githubusercontent.com/43505031/46349944-c84ee900-c653-11e8-9c8f-c8129afb2fb9.jpg)

**Expected behaviour**: 
I think they should hit stronger, or at least not constant the same dmg all the time.
**Server Revision**: 
2108

**Comment by The14me** [comment]
https://i.imgur.com/1jT3r6x.png

**Comment by Bildo** [comment]
Snapjaw is dealing correct dmg now
![image](https://user-images.githubusercontent.com/3138020/49696803-c05d7900-fbaf-11e8-8995-1b1c27c5312a.png)
