### ISSUE TITLE
hunter pet constantly using das

### ISSUE THREAD

**Issue by clogau** [Atlantiss/NetherwingBugtracker#1078]
[//]: # (Enclose links to things related to the bug using http://wowhead.com or any other TBC database.)
[//]: # (You can use screenshot ingame to visual the issue.)
[//]: # (Write your tickets according to the format:)
[//]: # ([Quest][Azuremyst Isle] Red Snapper - Very Tasty!)
[//]: # ([NPC] Magistrix Erona)
[//]: # ([Spell][Mage] Fireball)
[//]: # ([Npc][Drop] Ghostclaw Lynx)
[//]: # ([Web] Armory doesnt work)

**Description**: pet uses dash as soon as its highlighted on pet bar, and after each cooldown, constantly
having to manually select dash as and when its needed
**Current behaviour**:

**Expected behaviour**: dash should be used while pet is approach targeted mob

**Server Revision**:

**Comment by mbzz88** [comment]
Dive does the same thing, should only autocast in combat.
Currently autocasts when not in combat.

**Comment by Phibs77** [comment]
https://www.youtube.com/watch?v=MKeUnZH1y7Y

Dash on autocast. Doesn't get activated when combat starts. Around 0:24 you can see that dash gets activated as soon as he sends his pet onto the boss. Same around 3:36 and maybe a few times more in between, haven't checked.

Hope this helps.

**Comment by Wolffenstein** [comment]
Fixed in rev 2114.
