### ISSUE TITLE
Rogue Ice Thistle

### ISSUE THREAD

**Issue by Thorgrimme** [Atlantiss/NetherwingBugtracker#1079]
[//]: # http://db.hellfire-tbc.com/?npc=7457#abilities
[//]: # (You can use screenshot ingame to visual the issue.)
[//]: # (Write your tickets according to the format:)
[//]: # ([Quest][Azuremyst Isle] Red Snapper - Very Tasty!)
[//]: # ([NPC] Rogue Ice Thistle
[//]: # ([Spell][Mage] Fireball)
[//]: # ([Npc][Drop] Ghostclaw Lynx)
[//]: # ([Web] Armory doesnt work)

**Description**: Uses the spell Tendon Rip, but applies on itself, also doesn't seem to use Ice Blast which should freeze player solid.

**Current behaviour**: 

**Expected behaviour**: 

**Server Revision**:

**Comment by Evolvee** [comment]
rev Xd
