### ISSUE TITLE
Fishing Animation

### ISSUE THREAD

**Issue by deku100** [Atlantiss/NetherwingBugtracker#108]
[//]: # (Enclose links to things related to the bug using http://wowhead.com or any other TBC database.)
[//]: # (You can use screenshot ingame to visual the issue.)
[//]: # (Write your tickets according to the format:)
[//]: # ([Quest][Azuremyst Isle] Red Snapper - Very Tasty!)
[//]: # ([NPC] Magistrix Erona)
[//]: # ([Spell][Mage] Fireball)
[//]: # ([Npc][Drop] Ghostclaw Lynx)
[//]: # ([Web] Armory doesnt work)

**Description**:  Extra Fishing Animation

**Current behaviour**: When a fish bites, the bob makes the splashing animation twice.

**Expected behaviour**: The bob should only splash once.

**Server Revision**:

**Comment by anonyReporter** [comment]
Confirmed: https://streamable.com/1e7zu

**Comment by xmesaj2** [comment]
2128

**Comment by V3n1m** [comment]
fishing pop is dissappearing without any fish biting
