### ISSUE TITLE
Islen Waterseer missing

### ISSUE THREAD

**Issue by Tinnoan** [Atlantiss/NetherwingBugtracker#1080]
Islen Waterseer south of Ratchet at the cape seems to be missing, she is targetable through /target but she is nowhere to be found. An attempt to find her using Mind Vision was unsuccesful because she was out of range.

![waterseer missing](https://user-images.githubusercontent.com/25431721/46351275-334def00-c657-11e8-9b3e-37abf8cc321a.PNG)

**Comment by mbzz88** [comment]
I had turned in the quest Seeking Spiritual Aid http://db.hellfire-tbc.com/?quest=5158 not that long before this, in case it was the RP event that made her go missing.

**Comment by GrumpyOldNoob** [comment]
![wowscrnshot_100818_133136](https://user-images.githubusercontent.com/43961253/46613382-c1284f00-cb1b-11e8-9a3f-5994bb332f1e.jpg)
She is still hiding somewhere under the rock. No water totem for my shaman  :(

**Comment by aresbrutus** [comment]
I think she breaks after 1 of her events.

**Comment by Evolvee** [comment]
rev hehexd
