### ISSUE TITLE
[Hunter][Talent] Improved Aspect of the Monkey not working

### ISSUE THREAD

**Issue by Gniddikon** [Atlantiss/NetherwingBugtracker#1081]
**Description**: The talent "Improved Aspect of the Monkey" does not increase your dodge bonus. 

**Current behaviour**: The talent "Improved Aspect of the Monkey" does not increase your dodge bonus. 

**Expected behaviour**: Should increase the dodge bonus from Aspect of the Monkey by 2% per talent point spent.

**Server Revision**: 2108

**Comment by Easyfraggy** [comment]
Are you sure that you have checked your character sheet, the tooltip of Aspect of the Monkey wont change based on how many points you have in the talent. Only on character sheet.

**Comment by Wolffenstein** [comment]
Fixed in rev 2116.
