### ISSUE TITLE
[Spell][Druid] Aquatic form

### ISSUE THREAD

**Issue by totaemoeggerli** [Atlantiss/NetherwingBugtracker#1082]
[//]: # (Enclose links to things related to the bug using http://wowhead.com or any other TBC database.)
[//]: # (You can use screenshot ingame to visual the issue.)
[//]: # (Write your tickets according to the format:)
[//]: # ([Quest][Azuremyst Isle] Red Snapper - Very Tasty!)
[//]: # ([NPC] Magistrix Erona)
[//]: # ([Spell][Mage] Fireball)
[//]: # ([Npc][Drop] Ghostclaw Lynx)
[//]: # ([Web] Armory doesnt work)

**Description**: 
Aquatic form doesn't break if you jump over the water surface.

**Current behaviour**:
https://gfycat.com/FriendlyDefinitiveGrayreefshark it's cool that it doesn't break but sadly not blizzlike
and leads to strange results: https://gfycat.com/LividHandyCurassow (this isn't the server crashing btw). 

**Expected behaviour**: 
Aquatic form should break when you jump over the water surface. It breaks the way you expect it when going on land.

**Server Revision**: 2108

**Comment by Wolffenstein** [comment]
Fixed in rev 2205.

**Comment by linxz1** [comment]
I am just going to add that switching to aquatic form while drowning will not stop it, you will die anyway.
