### ISSUE TITLE
Fenris Isle (Silverpine Forest) LOS issue

### ISSUE THREAD

**Issue by staryfox** [Atlantiss/NetherwingBugtracker#1083]
[//]: # (Enclose links to things related to the bug using http://wowhead.com or any other TBC database.)
[//]: # (You can use screenshot ingame to visual the issue.)
[//]: # (Write your tickets according to the format:)
[//]: # ([Quest][Azuremyst Isle] Red Snapper - Very Tasty!)
[//]: # ([NPC] Magistrix Erona)
[//]: # ([Spell][Mage] Fireball)
[//]: # ([Npc][Drop] Ghostclaw Lynx)
[//]: # ([Web] Armory doesnt work)

**Description**:  Mobs at Fenris Isle, Particularly the ones inside the keep, ignore LOS. 

**Current behaviour**: when walking outside the keep players will pull mobs from inside. 

**Expected behaviour**:  Mobs should not aggro through walls

**Server Revision**:

**Comment by Wolffenstein** [comment]
Could you provide a video of that happening?

**Comment by staryfox** [comment]
i did record a video but it looks like it didnt happen a third time

i can still send it in if you want so you are aware of the location?

**Comment by Wolffenstein** [comment]
Sure, post it

**Comment by Kidcudi123** [comment]
I thought noone was gonna test Silverpine <3

**Comment by Tereneckla** [comment]
Fixed
