### ISSUE TITLE
[NPC]Galak Scout#4094 doesn't run away while fighting

### ISSUE THREAD

**Issue by Tenoutoften** [Atlantiss/NetherwingBugtracker#1084]
**Description**: 
[[NPC]Galak Scout#4094](https://db.excalibur.ws/?npc=4094#abilities) should run away while fighting to get ranged from the player in order to use [[Spell]Shoot#660](https://db.excalibur.ws/?spell=6660). Currently [wont run away(video)](https://www.youtube.com/watch?v=zY5490NosXg&feature=youtu.be).

Should run away indicated by [wowhead comment 1 (Patch 2.4.2)](https://www.wowhead.com/quest=4841/pacify-the-centaur#comments:id=297550)
> The scouts are a nightmare in all honesty, they are quite random as to wether they will stand still and fight you, or they will just keep running about and trying to shoot you with their bow, if this does happen, prepare for adds unless your trapping them in the tent like mentioned above.

[wowhead comment 2 (Patch 2.4.1)](https://www.wowhead.com/quest=4841/pacify-the-centaur#comments:id=275141)

> When dealing with the Galak scouts and Galak wrangler as a melee class I can advise finding one of the fully enclosed tents (There are a number of them spread about the camp). Kill the inhabitant, then pull the wranglers and scouts into the tent by running into it and standing just around the corner of the doorway. First of all this gets them away from the rest of the Galak. Second of all, even if they do run (with or without netting you first), they will move out of line-of-sight and come running back within seconds.

[wowhead comment 3 (Patch 2.1.3)](https://www.wowhead.com/quest=4841/pacify-the-centaur#comments:id=122728)
> Most of them try to run at low health, so take them out quick or be ready for adds. The Windchasers can heal themselves to full when they get low, so try and stun them when you see them casting. If you have any back attacks like backstab or shred, **you can use them on the scouts for quicker kills, because they will often try to run away from you to use their bow**.

**Expected behaviour**: 
[[NPC]Galak Scout#4094](https://db.excalibur.ws/?npc=4094#abilities) expected to rather frequently attempt to run away from the player to use [[Spell]Shoot#660](https://db.excalibur.ws/?spell=6660) 

**Server Revision**: 
2108

**Comment by Tenoutoften** [comment]
I can't find video evidence for this, but I how the comments are enough. Perhaps there is something on Lightbringer bugtracker? They have it working as described.

**Comment by The14me** [comment]
Work perfect to me.Go in mele range and attack..after 3-4 sec u cast Net on you and go back to attack you with the bow.Please retest and if its somehow bugged to you make a vid/gif.
