### ISSUE TITLE
[Quest][Stranglethorn Vale] Venture Company Mining

### ISSUE THREAD

**Issue by DeltaLoads** [Atlantiss/NetherwingBugtracker#1085]
Singing Blue Crystal examples for drop rate:
- https://tbc-twinhead.twinstar.cz/?item=3917
- https://classicdb.ch/?item=3917
**Description**: 
Drop rate of Singing Blue Crystals is way too low for 2.4.3 patch
**Current behaviour**:
Current drop rate for Singing Blue Crystal is at about 5%
**Expected behaviour**: 
Drop rate for Singing Blue Crystal should be at about 80%
**Server Revision**: 
2108

**Comment by Jezofine** [comment]
[Thottbot link](http://web.archive.org/web/20080913211907/http://thottbot.com:80/i3917)

**Comment by DeltaLoads** [comment]
That was pre-nerf droprate, after 2.4.3 drop rate increased as part of pre-expansion easier leveling update

**Comment by Tenoutoften** [comment]
I think the leadership has decided to go with 2.3 leveling roughly

**Comment by aresbrutus** [comment]
Fixed in one of the upcoming updates.
