### ISSUE TITLE
[Discord][Weebs]

### ISSUE THREAD

**Issue by Thugli** [Atlantiss/NetherwingBugtracker#1086]
[//]: # (Enclose links to things related to the bug using http://wowhead.com or any other TBC database.)
[//]: # (You can use screenshot ingame to visual the issue.)
[//]: # (Write your tickets according to the format:)
[//]: # ([Quest][Azuremyst Isle] Red Snapper - Very Tasty!)
[//]: # ([NPC] Magistrix Erona)
[//]: # ([Spell][Mage] Fireball)
[//]: # ([Npc][Drop] Ghostclaw Lynx)
[//]: # ([Web] Armory doesnt work)

**Description**: 
Weebs are present on discord, this is not working as intended.

**Current behaviour**:
Weebs are roaming about discord as they please.

**Expected behaviour**: 
Weebs should be banished from discord.

**Server Revision**: 
2108

**Comment by Wolffenstein** [comment]
...
