### ISSUE TITLE
[NPC]Needles Cougar#4124 x2 standing completely still in Thousand Needles

### ISSUE THREAD

**Issue by Tenoutoften** [Atlantiss/NetherwingBugtracker#1087]
**Description**: 
[[NPC]Needles Cougar#4124](https://db.excalibur.ws/?npc=4124) standing completely still at [This](https://i.gyazo.com/47d546265c7423b5f61dd00e514b6c0d.png) and [this](https://i.gyazo.com/cff6b1fc588d6f1948248fb374a92254.png) spot. 

[.npc info](https://i.gyazo.com/234a6d35494051b7bdf743bec10baf1b.png)

**Expected behaviour**: 
Expected to move around on their spot a bit

**Server Revision**: 
2108

**Comment by aresbrutus** [comment]
I just checked and both of them actually do random walk.
