### ISSUE TITLE
[Quest] Gordunni Cobalt

### ISSUE THREAD

**Issue by manslaughter** [Atlantiss/NetherwingBugtracker#1088]
**Description**: Horde quest in Feralas involving using a shovel to dig up Gordunni Cobalt.  Blue glows in the ground indicate areas to dig.

**Current behaviour**:
- Shovel is only usable at blue glows in Gordunni Ogre camp.

**Expected behaviour**: 
- Shovel is usable anywhere (only uses on blue glows have a chance to give cobalt)
- Dirt mounds dug using the shovel have a blue glow if they contain a Gordunni Cobalt.
https://classicdb.ch/?quest=2987

**Server Revision**: 
2108

**Comment by Tenoutoften** [comment]
[[Object]Gordunni Dirt Mound#144064](https://db.excalibur.ws/?object=144064) summoned by [[Spell]Summon Gordunni chest(COBALT)#11756](https://db.excalibur.ws/?spell=11756) has **2 effects**:

1. [[Object]Gordunni Dirt Mound#144064](https://db.excalibur.ws/?object=144064)
2. [[Object]Gordunni Cobalt Visual (DND)#177683](https://db.excalibur.ws/?object=177683)

I suppose [[Object]Gordunni Cobalt Visual (DND)#177683](https://db.excalibur.ws/?object=177683) is simply not added in or broken in current patch?

Neither [[Object]Gordunni Cobalt Visual (DND)#177683](https://db.excalibur.ws/?object=177683) or [[Spell]Summon Gordunni chest(COBALT)#11756](https://db.excalibur.ws/?spell=11756) can be found on wowhead, only [[Object]Gordunni Dirt Mound#144064](https://db.excalibur.ws/?object=144064) remain.

**Comment by duzyizly** [comment]
Expected behaviour:

1. Shovel is usable anywhere (only uses on blue glows have a chance to give cobalt) - it is usable anywhere (tested with rev 3390 ptr)
2. Dirt mounds dug using the shovel have a blue glow if they contain a Gordunni Cobalt.
https://classicdb.ch/?quest=2987 - dirt mounds are not glowing (same rev)

**Comment by Wolffenstein** [comment]
Fixed in rev 3391.
