### ISSUE TITLE
[Quest]Free at Last#4904 spawned mobs are slow to engage(5-6s)

### ISSUE THREAD

**Issue by Tenoutoften** [Atlantiss/NetherwingBugtracker#1089]
**Description**: 
The [[NPC]Grimtotem Bandit](https://db.excalibur.ws/?npc=10758) spawning roughly at https://youtu.be/ZVidTqo5KhQ?t=133 takes about 6 seconds to engage.

After finishing off two mobs in a three mob pull at https://youtu.be/ZVidTqo5KhQ?t=208 I remain in combat with the third, while quest [[NPC]Lakota Windsong#10646](https://db.excalibur.ws/?npc=10646) stuck. Unstucks as I eventually pull it closer. Perhaps a general issue with escort AI when player is in combat with a creature a bit out of range?

Second pack of [[NPC]Grimtotem Bandit](https://db.excalibur.ws/?npc=10758) at https://youtu.be/ZVidTqo5KhQ?t=265 one of the [[NPC]Grimtotem Bandit](https://db.excalibur.ws/?npc=10758) takes 5 seconds to react and spawns with the face in a strange angle.

Third pack of [[NPC]Grimtotem Bandit](https://db.excalibur.ws/?npc=10758) https://youtu.be/ZVidTqo5KhQ?t=427 same thing.

[wowhead comment (Patch 3.1.3)](https://www.wowhead.com/quest=4904/free-at-last#comments:id=786390)
> On the first ambush, I sapped the mob that spawned near the bridge almost instantly. After we killed the unsapped mob, the sapped one despawned. I to do it on the third ambush, but it didn't work. Maybe I wasn't fast enough or he was too close?

They are suppose to able to be sapped if done very quickly, but I believe 5-6 seconds is a bit to excessive.

**Expected behaviour**: 
I'd expect the spawned mobs to engange quicker

**Server Revision**: 
2108

**Comment by Evolvee** [comment]
https://www.youtube.com/watch?v=kOc02LX4g0s

**Comment by Evolvee** [comment]
requires full work - shit stock cpp

**Comment by Wolffenstein** [comment]
Fixed in rev 3387.
