### ISSUE TITLE
(Possible) Rogue: Auto-Attak stops after dodged

### ISSUE THREAD

**Issue by padomu** [Atlantiss/NetherwingBugtracker#109]
[//]: # (Enclose links to things related to the bug using http://wowhead.com or any other TBC database.)
[//]: # (You can use screenshot ingame to visual the issue.)
[//]: # (Write your tickets according to the format:)
[//]: # ([Quest][Azuremyst Isle] Red Snapper - Very Tasty!)
[//]: # ([NPC] Magistrix Erona)
[//]: # ([Spell][Mage] Fireball)
[//]: # ([Npc][Drop] Ghostclaw Lynx)
[//]: # ([Web] Armory doesnt work)

**Description**: 

**Current behaviour**:
If a mob dodges my gouge, my char stops auto-attaking

**Expected behaviour**: 
After  gouge gets dodged, it should keep auto-attacking

!! I'm not sure if that's blizzlike. !! No idea how to research that. :/

**Server Revision**: 
2020

**Comment by ahlens** [comment]
I believe it should work this way but can't find any proof as well. Still, your proposition for fix might be quite comfortable for us if implemented.

**Comment by bloodwindz** [comment]
I Played rogue in retail tbc (hardcore pve and pvp) and i remember this too it should not stop auto attack if it gets dodged 

+1

**Comment by padomu** [comment]
Ofc it stops auto-attack, if it is not dodged. The issue is when it is dodged. I might do some research if I have time.

**Comment by Tereneckla** [comment]
Looks like the upright, not auto attack position to me.

**Comment by SwiftieTBC** [comment]
Literally within the tool-tip is states it turns off auto attacks, This can 100% be closed especially with the supporting evidence from dract.
