### ISSUE TITLE
[Spell][Hunter] Feign death is not making me lose all aggro sometimes

### ISSUE THREAD

**Issue by queeb3** [Atlantiss/NetherwingBugtracker#1090]
[//]: # (Enclose links to things related to the bug using http://wowhead.com or any other TBC database.)
[//]: # (You can use screenshot ingame to visual the issue.)
[//]: # (Write your tickets according to the format:)
[//]: # ([Quest][Azuremyst Isle] Red Snapper - Very Tasty!)
[//]: # ([NPC] Magistrix Erona)
[//]: # ([Spell][Mage] Fireball)
[//]: # ([Npc][Drop] Ghostclaw Lynx)
[//]: # ([Web] Armory doesnt work)

https://imgur.com/a/5qGoiZV
**Description**: 
while using FD ive noticed that sometimes enemies will not stop attacking you even when you have the full buff and are laying down.
**Current behaviour**:
feign death is not making everything stop targeting you.
**Expected behaviour**: 
Feign death should make everything click off you and not notice you.
**Server Revision**:

**Comment by Firroth** [comment]
From my knowledge Feign Death CAN RESIST too - not aggro drop. Even in Survival talents you have talents to reduce it's resist. Why would it be for then? :D 

Nothing to change here, since it works fine.

**Comment by Wolffenstein** [comment]
Feign death has a chance to resist.
