### ISSUE TITLE
[Pathing][Core Mechanic]Broke a [NPC]Scalding Elemental#10756 jumping up and down a cliff

### ISSUE THREAD

**Issue by Tenoutoften** [Atlantiss/NetherwingBugtracker#1091]
**Description & Current Behavior**: 
[[NPC]Scalding Elemental#10756](https://db.excalibur.ws/?npc=10756)

[.gps & .npc info](https://i.gyazo.com/556b5502e1e8a2bbab99b509d031bc96.png)

I first made it evade a few times jumping up from the water and reseting it jumping back into the water until it eventually let me kill it without fighting back.
[Video of the event](https://www.youtube.com/watch?v=DdVvd2aylDc&feature=youtu.be)

**Expected behaviour**: 
I'd expect the [[NPC]Scalding Elemental#10756](https://db.excalibur.ws/?npc=10756) to follow me up and down without evading, and never get to a point where it just stands there receiving damage without fighting back.

**Server Revision**: 
2108

**Comment by Wolffenstein** [comment]
Should be fixed in rev 2120.
