### ISSUE TITLE
[NPC] Seer Wiserunner

### ISSUE THREAD

**Issue by eryczek1615** [Atlantiss/NetherwingBugtracker#1092]
Description: 
 NPC in Mulgore - https://www.wowhead.com/npc=2984/seer-wiserunner , https://classicdb.ch/?npc=2984 , 

Current behaviour: 
After we completed quest Rite of Vision(https://classicdb.ch/?quest=772) he says: I have been expecting you,<name>

Expected behaviour: 
He souldn't say anything:
https://youtu.be/R6KLsRDujOw?t=8m38s
https://youtu.be/aHKR-HDIiOU?t=5m15s
https://imgur.com/pcrQNNJ

Server Revision: 
2108

**Comment by Wolffenstein** [comment]
Footage you posted is from private servers, invalid.
