### ISSUE TITLE
[Quest] Aquementas

### ISSUE THREAD

**Issue by mbzz88** [Atlantiss/NetherwingBugtracker#1093]
**Description**: Silver Totem of Aquementas https://www.wowhead.com/item=11522 not given to player after killing Aquementas https://www.wowhead.com/npc=9453/aquementas

**Current behaviour**: Killing NPC with required quest items in bag, and remaining within the summoning circle, does not result in totem being added to inventory

**Expected behaviour**: Receive totem after killing NPC

**Server Revision**: 2108

**Comment by xmesaj2** [comment]
fixed in 2139

**Comment by aresbrutus** [comment]
Did you fix the RP from https://github.com/Atlantiss/AtlantissTBCBT/issues/1870 ?

**Comment by xmesaj2** [comment]
2042
