### ISSUE TITLE
[NPC] Silithid Swarm - easy money making

### ISSUE THREAD

**Issue by Firroth** [Atlantiss/NetherwingBugtracker#1094]
[NPC] [Centipaar Swarmer](https://www.wowhead.com/npc=5457/centipaar-swarmer)
[NPC] [Silithid Swarm](https://www.wowhead.com/npc=4196/silithid-swarm)

**Current behaviour**:
[Centipaar Swarmer](https://www.wowhead.com/npc=5457/centipaar-swarmer) summons very fast mob called [Silithid Swarm](https://www.wowhead.com/npc=4196/silithid-swarm) (this mob has 1hp) on which you can farm money, since 1 drops 2-5 silver or even more (my best was 5s60c). 

![screenshot_2](https://user-images.githubusercontent.com/43505196/46374346-c9ead200-c690-11e8-9345-4550fd5275be.png)

Now imagine some tankadin pulling several of [Centipaar Swarmer](https://www.wowhead.com/npc=5457/centipaar-swarmer) so they would be spawning [Silithid Swarm](https://www.wowhead.com/npc=4196/silithid-swarm) in masses for how long this player would want and getting around 1g if not more in around 30 seconds.

It's not that "super bad", but still can make some players rich fast.

**Expected behaviour**: 
They should drop no money at all or very little.

**Server Revision**: 
2108

**Comment by Jezofine** [comment]
[Centipaar Swarmer (npc=5457)](http://db.hellfire-tbc.com/?npc=5457) does the same thing. Better check all swarmers.

**Comment by Shanghi** [comment]
This should be fixed in revision 2152.
