### ISSUE TITLE
[STV][Desolace] Fatigue

### ISSUE THREAD

**Issue by totaemoeggerli** [Atlantiss/NetherwingBugtracker#1095]
[//]: # (Enclose links to things related to the bug using http://wowhead.com or any other TBC database.)
[//]: # (You can use screenshot ingame to visual the issue.)
[//]: # (Write your tickets according to the format:)
[//]: # ([Quest][Azuremyst Isle] Red Snapper - Very Tasty!)
[//]: # ([NPC] Magistrix Erona)
[//]: # ([Spell][Mage] Fireball)
[//]: # ([Npc][Drop] Ghostclaw Lynx)
[//]: # ([Web] Armory doesnt work)

**Description**: 
Fatigue caused by trench in STV veil reef and Desolace naga area.

**Current behaviour**:
https://imgur.com/a/qDYu4h9

**Expected behaviour**: 
The trenches are "dark blue" on the minimap but enclosed by "light blue" water. I don't have any proof how it was but I don't think it should be like this. 
Fatigue isn't really a game mechanic that adds depth to the game but a fancy invisible wall to keep players within boundries.

**Server Revision**: 2108

**Comment by Manaci** [comment]
Not a bug
