### ISSUE TITLE
[NPC][Drop] Flatland Cougar

### ISSUE THREAD

**Issue by eryczek1615** [Atlantiss/NetherwingBugtracker#1096]
Description: NPC in Mulgore - https://classicdb.ch/?npc=3035 this npc drops Cougar Claws (https://classicdb.ch/?item=4802)

Current behaviour:
To get 6 Claws I had to killed something around 25-30

Expected behaviour: 
There is 80% chance for drop.

Server Revision: 
2108

**Comment by aresbrutus** [comment]
Blizzlike values.

The website you linked uses stock stats and are incorrect.
