### ISSUE TITLE
[STV] Pillar doesn't break LoS

### ISSUE THREAD

**Issue by totaemoeggerli** [Atlantiss/NetherwingBugtracker#1097]
[//]: # (Enclose links to things related to the bug using http://wowhead.com or any other TBC database.)
[//]: # (You can use screenshot ingame to visual the issue.)
[//]: # (Write your tickets according to the format:)
[//]: # ([Quest][Azuremyst Isle] Red Snapper - Very Tasty!)
[//]: # ([NPC] Magistrix Erona)
[//]: # ([Spell][Mage] Fireball)
[//]: # ([Npc][Drop] Ghostclaw Lynx)
[//]: # ([Web] Armory doesnt work)

**Description**: 
Pillar doesn't break LoS
Ruins of Zul'Kunda top area with Headhunters/Beastmasters/Berserker

**Current behaviour**:
https://gfycat.com/FreshRingedBrontosaurus

**Expected behaviour**: 
Mob should walk up to the corner, not shoot through it.

**Server Revision**: 2108

**Comment by Wolffenstein** [comment]
Not a bug, some objects just don't block LoS.
