### ISSUE TITLE
[NPC] Ranshalla

### ISSUE THREAD

**Issue by mbzz88** [Atlantiss/NetherwingBugtracker#1098]
**Description**: NPC ignores all mobs on escort quest, even when they are attacking her
http://db.hellfire-tbc.com/?quest=4901

**Current behaviour**: Ranshalla http://db.hellfire-tbc.com/?npc=10300 ignores all mobs during escort quest, will continue on path while being attacked

**Expected behaviour**: NPC reacts to mobs

**Server Revision**: 2108

**Comment by The14me** [comment]
move to https://github.com/Atlantiss/NetherwingBugtracker/issues/3678
