### ISSUE TITLE
Bloodpetal Trapper, Un'goro, Loot Table

### ISSUE THREAD

**Issue by Erodraeda** [Atlantiss/NetherwingBugtracker#1099]
[//]: # (Enclose links to things related to the bug using http://wowhead.com or any other TBC database.)
[//]: # (You can use screenshot ingame to visual the issue.)
[//]: # (Write your tickets according to the format:)
[//]: # ([Quest][Azuremyst Isle] Red Snapper - Very Tasty!)
[//]: # ([NPC] Magistrix Erona)
[//]: # ([Spell][Mage] Fireball)
[//]: # ([Npc][Drop] Ghostclaw Lynx)
[//]: # ([Web] Armory doesnt work)

**Description**: 
Bloodpetal Trapper, Entry: 6512, dropped a Dinosaur Bone, item for another quest of the zone. This item should only be dropped by dinosaurs (lol)
**Current behaviour**:
![screenshot_522](https://user-images.githubusercontent.com/40346279/46377310-a4e56780-c66e-11e8-9894-966f316f27cc.png)
**Expected behaviour**: 
That item should not be dropped by said monster.
**Server Revision**:

**Comment by aresbrutus** [comment]
Global loot issue.

**Comment by Shanghi** [comment]
This should be fixed in revision 2152.
