### ISSUE TITLE
Vanish doesn't get rid of "dazed" (slowingeffect)

### ISSUE THREAD

**Issue by padomu** [Atlantiss/NetherwingBugtracker#1100]
[//]: # (Enclose links to things related to the bug using http://wowhead.com or any other TBC database.)
[//]: # (You can use screenshot ingame to visual the issue.)
[//]: # (Write your tickets according to the format:)
[//]: # ([Quest][Azuremyst Isle] Red Snapper - Very Tasty!)
[//]: # ([NPC] Magistrix Erona)
[//]: # ([Spell][Mage] Fireball)
[//]: # ([Npc][Drop] Ghostclaw Lynx)
[//]: # ([Web] Armory doesnt work)

**Description**: 
Vanish should break slowing effects
**Current behaviour**:
A mob dazes me => I move with e.g. 40% speed. Doesn't matter the mob, tested it on quit a few and different zones. I vanish, I'm still dazed. 

**Expected behaviour**: 
If I vanish, the dazing should vanish too.

**Server Revision**: 
2108

**Comment by Easyfraggy** [comment]
I'm not sure that daze counts as a regular slow effect. Doubtful that vanish should remove it.

**Comment by Erodraeda** [comment]
As far as I remember, "dazed" effects are not removed by Vanish. I might be wrong tho, but I don't remember it being the case

**Comment by Wolffenstein** [comment]
Need proof

**Comment by killablink** [comment]
Pretty sure vanish doesn't remove daze.

**Comment by Spaztick** [comment]
> Patch 1.7.0 (patch date:2005-09-22): Fixed a bug where the Dazed ability used by creatures when attacking targets from behind was countered/dispelled by some spells (e.g. Blessing of Freedom).

Daze doesn't get removed with vanish. Not sure on talented sprint.

**Comment by padomu** [comment]
Really? I was sure id did. I'm gonna check it but according to WoWWiki you guys are actually right. http://wowwiki.wikia.com/wiki/Daze (which has a source 2007) I'm also gonna check my own videos from 2007, there's a lot of pvp in there so I think I might find something

**Comment by padomu** [comment]
Maybe I thought so because I basically only did PvP and maybe there was a difference between player daze and mob daze? Like e.g. statet here: https://www.ownedcore.com/forums/world-of-warcraft/world-of-warcraft-guides/192641-class-rogue-guide.html

> "Insignia of the Alliance, Insignia of the Horde, Medallion of the Alliance, and Medallion of the Horde have all been redesigned. The trinkets for all classes now have the same effect: Dispels all movement impairing effects and all effects that cause loss of control of your character."
> This means that Kidney Shot and Cheap Shot, but also the Deadly Throw debuff, Poisons, Sap, Blind and Gouge can be removed by any class at any time. Daze (from Blade Twisting) is surprisingly also affected - this misconception exists because there is in fact a difference between player Daze and mob Daze. Mob Daze is in fact only removable by complete immunity effects (pally bubble, Ice Block), while player Daze is treated as any other movement-impairing effect.

**Comment by Easyfraggy** [comment]
There is no player daze.
