### ISSUE TITLE
Chest's in "The charred vale" are empty

### ISSUE THREAD

**Issue by padomu** [Atlantiss/NetherwingBugtracker#1101]
[//]: # (Enclose links to things related to the bug using http://wowhead.com or any other TBC database.)
[//]: # (You can use screenshot ingame to visual the issue.)
[//]: # (Write your tickets according to the format:)
[//]: # ([Quest][Azuremyst Isle] Red Snapper - Very Tasty!)
[//]: # ([NPC] Magistrix Erona)
[//]: # ([Spell][Mage] Fireball)
[//]: # ([Npc][Drop] Ghostclaw Lynx)
[//]: # ([Web] Armory doesnt work)

**Description**: 
Sadly I don't have to cords, but I was there a lot and all chests (should be two) were empty.

**Current behaviour**:
The two chests in the charred vale in stonetalon mountaine are always empty.

**Expected behaviour**: 
They shouldn't be empty.

**Server Revision**: 
2108

**Comment by manslaughter** [comment]
Just found an empty chest in Duskwood at 35.88, 27.58.  I am horde though, so it may be faction based?

**Comment by Manaci** [comment]
Fixed
