### ISSUE TITLE
Quest Item blink effect way to big in "The charred vale"

### ISSUE THREAD

**Issue by padomu** [Atlantiss/NetherwingBugtracker#1102]
[//]: # (Enclose links to things related to the bug using http://wowhead.com or any other TBC database.)
[//]: # (You can use screenshot ingame to visual the issue.)
[//]: # (Write your tickets according to the format:)
[//]: # ([Quest][Azuremyst Isle] Red Snapper - Very Tasty!)
[//]: # ([NPC] Magistrix Erona)
[//]: # ([Spell][Mage] Fireball)
[//]: # ([Npc][Drop] Ghostclaw Lynx)
[//]: # ([Web] Armory doesnt work)

**Description**: 

**Current behaviour**:
Sadly somehow I couldnt make screenshot. But in The charred vale is a quest where you have to loot these "dirt cluster". You actually have to loot seeds first and then you get a new quests where you have to plant these seeds into these "dirt cluster". In this quest, the blink effect of these dirt cluster are freaking huuge.

**Expected behaviour**: 
the effect should be smaller

**Server Revision**: 
2108

**Comment by Easyfraggy** [comment]
Duplicate https://github.com/Atlantiss/NetherwingBugtracker/issues/597 https://github.com/Atlantiss/NetherwingBugtracker/issues/421
