### ISSUE TITLE
Raptor Captor

### ISSUE THREAD

**Issue by Mewmewww** [Atlantiss/NetherwingBugtracker#1103]
[//]: # (Enclose links to things related to the bug using http://wowhead.com or any other TBC database.)
[//]: # (You can use screenshot ingame to visual the issue.)
[//]: # (Write your tickets according to the format:)
[//]: # ([Quest][Azuremyst Isle] Red Snapper - Very Tasty!)
[//]: # ([NPC] Magistrix Erona)
[//]: # ([Spell][Mage] Fireball)
[//]: # ([Npc][Drop] Ghostclaw Lynx)
[//]: # ([Web] Armory doesnt work)

**Description**: Capture 6 raptors with rope

**Current behaviour**: You can actually capture multiple ropes at once, as long as atleast one of the raptors are low hp. (only worked with 2 at a time)

**Expected behaviour**: Should only work with low level raptors and only single target.

**Server Revision**: 2108

**Comment by xmesaj2** [comment]
fixed in 2139
