### ISSUE TITLE
Withervine Creeper (Dustwallow marsh)

### ISSUE THREAD

**Issue by Mewmewww** [Atlantiss/NetherwingBugtracker#1104]
[//]: # (Enclose links to things related to the bug using http://wowhead.com or any other TBC database.)
[//]: # (You can use screenshot ingame to visual the issue.)
[//]: # (Write your tickets according to the format:)
[//]: # ([Quest][Azuremyst Isle] Red Snapper - Very Tasty!)
[//]: # ([NPC] Magistrix Erona)
[//]: # ([Spell][Mage] Fireball)
[//]: # ([Npc][Drop] Ghostclaw Lynx)
[//]: # ([Web] Armory doesnt work)

**Description**: Elementals Entangling roots

**Current behaviour**: It's 18 seconds and unbreakable. I was getting beat by around 5 mobs and not a single one removed it - unsure though if this is how roots should work

**Expected behaviour**: I assume there should be a chance of the root fading away after taking DMG

**Server Revision**: 2108

**Comment by The14me** [comment]
https://youtu.be/zAYQAgadiWU?t=88 Its MOP,but dont thing they change it.If have TBC vid please Pm me to re-open it.
Thx to @ Fenvarien  for the vid.
