### ISSUE TITLE
[NPC] Morin Cloudstalker

### ISSUE THREAD

**Issue by eryczek1615** [Atlantiss/NetherwingBugtracker#1105]
**Description**: This is Npc in Mulgore - https://www.wowhead.com/npc=2988/morin-cloudstalker ,  https://vanilla-twinhead.twinstar.cz/?npc=2988

**Current behaviour**:
In his quest windows we can see "Greeting, name

**Expected behaviour**: 
I used wowwiki and should be "The Outrunners' duty is to ensure the safty of those who travel across the plains of Mulgore. Those that would threaten the safty of the tauren homeland risk punishment at our hands.".
 http://wowwiki.wikia.com/wiki/Morin_Cloudstalker
https://imgur.com/U8haQln

**Server Revision**: 
2108

**Comment by Wolffenstein** [comment]
Such text does not exist, wowwiki is wrong.

**Comment by Wolffenstein** [comment]
![image](https://user-images.githubusercontent.com/1576644/46429513-e47f8280-c746-11e8-8bcf-7d94b4ec9876.png)
From current retail

**Comment by Wolffenstein** [comment]
Fixed in rev 2123.
