### ISSUE TITLE
[Sunken Temple][NPC] Eranikus

### ISSUE THREAD

**Issue by Knoox** [Atlantiss/NetherwingBugtracker#1106]
**Purposly left some dragonkin alive to verify that his "pull all" mechanic works, doesnt not, was able to pull him out of the room aswell.**: 

**Server Revision 2018
![wowscrnshot_100318_020349](https://user-images.githubusercontent.com/18479169/46383571-455c7b80-c6b1-11e8-9f6c-034dd2ad6b89.jpg)
**:

**Comment by Easyfraggy** [comment]
Which adds did you leave alive? I tested this on closed beta and it worked fine then.

**Comment by Firroth** [comment]
Did it today. Same issue mobs didn't come when started the fight.
After that tested it with Kutsal, 1 pack only came. So I think the issue lies with the "range check" or grabbing all dragon's GUID's in instance.

**Comment by Azalen** [comment]
Is he using this spell: https://classicdb.ch/?spell=11876 ?
killed him twice but did not notice him using it.

**Comment by Easyfraggy** [comment]
![image](https://user-images.githubusercontent.com/36134067/47273366-8e5a6e00-d593-11e8-9a18-f5483cd23736.png)

**Comment by Tereneckla** [comment]
Fixed Fixed and Fixed
