### ISSUE TITLE
[Hunter][Pet] Pet refuses to attack certian mobs and when standing on certian terrain

### ISSUE THREAD

**Issue by Knoox** [Atlantiss/NetherwingBugtracker#1108]
**Refuses to attack, CC mobs, when standing on stairs, some random mobs in sunke temple. When the target is enganged in combat(Doesnt count for ccd) it attacks as normal**: 

**Server Revision 2108**:

**Comment by Wolffenstein** [comment]
Please record a video of it

**Comment by The14me** [comment]
rev 3441. Tested every stair there..cant reproduce(fixed)
Can be closed.
