### ISSUE TITLE
[Sunken Temple][NPC] Zolo

### ISSUE THREAD

**Issue by Knoox** [Atlantiss/NetherwingBugtracker#1109]
**His totems behave like mobs, IE moving and attacking**: 

**Server Revision 2018
![wowscrnshot_100318_005428](https://user-images.githubusercontent.com/18479169/46383662-c87dd180-c6b1-11e8-8864-9b3aec918409.jpg)
**:

**Comment by Wolffenstein** [comment]
Fixed in rev 2137.
