### ISSUE TITLE
[Sunken Temple][NPC] Unlinked mobs

### ISSUE THREAD

**Issue by Knoox** [Atlantiss/NetherwingBugtracker#1110]
**Server Revision 2108
![wowscrnshot_100318_004905](https://user-images.githubusercontent.com/18479169/46383686-ea775400-c6b1-11e8-9b6e-5e06306f0376.jpg)
![wowscrnshot_100318_004649](https://user-images.githubusercontent.com/18479169/46383691-f400bc00-c6b1-11e8-9d41-2936c6a28fa2.jpg)
![wowscrnshot_100318_003907](https://user-images.githubusercontent.com/18479169/46383695-f9f69d00-c6b1-11e8-9b86-d9d943e2ed36.jpg)

**:

**Comment by aresbrutus** [comment]
Fixed in rev `Tycho`.
