### ISSUE TITLE
[Tanaris][Quest] Rescue OOX-17/TN!

### ISSUE THREAD

**Issue by Knoox** [Atlantiss/NetherwingBugtracker#1114]
**Doesnt care about mobs, the event where mobs spawn. They just stand around unless aggroed**: 

**Server Revision 2108
![wowscrnshot_100218_050034](https://user-images.githubusercontent.com/18479169/46383880-fc0d2b80-c6b2-11e8-8f63-db3711a796f0.jpg)
**:

**Comment by Tenoutoften** [comment]
**Description**: 
[[NPC]Homing Robot OOX-17/TN#7784](https://db.excalibur.ws/?npc=7784) 
[[Quest]Rescue 00X-17/TN!#648](https://db.excalibur.ws/?quest=648)

Full video of the quest on Netherwing [here](https://www.youtube.com/watch?v=D3QRwGcV8S0&feature=youtu.be)

**Comment by Mikik3jr** [comment]
Here is a 10yr old video about this quest if you need it:
https://www.youtube.com/watch?v=uJZYfAOPtsc

**Comment by Mikik3jr** [comment]
Every mob should attack the chicken on its way, and the ambushers as well.

**Comment by KevinTyrrell** [comment]
This bug occurs with all of the Homing Robot quests, not just the Tanaris quest.
