### ISSUE TITLE
[Tanaris][NPC] Positioning

### ISSUE THREAD

**Issue by Knoox** [Atlantiss/NetherwingBugtracker#1115]
**Laying and attacking on his bed, need to physicly move him with pet to be able to attack him without evading out**: 

**Server Revision 2018
![wowscrnshot_100218_033505](https://user-images.githubusercontent.com/18479169/46383911-27901600-c6b3-11e8-919b-647a1bb3c108.jpg)
**:

**Comment by aresbrutus** [comment]
I do not see any issues. Please re-test and comment here again if something is wrong.
