### ISSUE TITLE
[Quest] Wretched Ringleader

### ISSUE THREAD

**Issue by DarthNekr0s** [Atlantiss/NetherwingBugtracker#112]
**Description**:  while being in a party, if one member has this quest and the other doesn't, the person without the quest can still loot the head if the quest mob (Aldaron the Reckless) is killed. Have not tested if he drops his head while being solo and also not having the quest, but just assumed it was because the other person in my party did have it so I shared the loot too.

**Current behaviour**: Aldaron giving quest item drop when player doesn't have his quest

**Expected behaviour**: Aldaron should only drop his head for players on Wretched Ringleader quest

**Server Revision**:

**Comment by aresbrutus** [comment]
Will be fixed next rev.
