### ISSUE TITLE
[NPC][Spell] Searing Totem (Witherbark Witch Doctor)

### ISSUE THREAD

**Issue by kkumbaya** [Atlantiss/NetherwingBugtracker#1122]
Totems don't shoot at the player. Possibly issue with all NPC searing totems
**Server Revision**: 2108

**Comment by The14me** [comment]
Related with https://github.com/Atlantiss/NetherwingBugtracker/issues/902

**Comment by The14me** [comment]
Witherbark Witch Doctor have Magma and Healing totem.Maybe wrong NPC name?Please re-open if find the right one.
