### ISSUE TITLE
([NPC] Chieftain Oomooroo / The Kurken in Stillpine Hold - respawn timer only ~1 minute

### ISSUE THREAD

**Issue by Rebelyna** [Atlantiss/NetherwingBugtracker#1123]
**Current behaviour**:
Chieftain Oomooroo / The Kurken have a respawn time of around 1 minute only. The Crazed Wildkin in the Stillpine Hold have as it seems the correct respawn timer.

**Expected behaviour**: 
It should take Chieftain Oomooroo / The Kurken a bit longer to respawn.

**Server Revision**: 
2108

**Comment by aresbrutus** [comment]
This is related to the massive influx of players that will happen on release. Working as intended.
