### ISSUE TITLE
Cauldron Lord Razarch, doubled on the spawnpoint

### ISSUE THREAD

**Issue by Erodraeda** [Atlantiss/NetherwingBugtracker#1124]
[//]: # (Enclose links to things related to the bug using http://wowhead.com or any other TBC database.)
[//]: # (You can use screenshot ingame to visual the issue.)
[//]: # (Write your tickets according to the format:)
[//]: # ([Quest][Azuremyst Isle] Red Snapper - Very Tasty!)
[//]: # ([NPC] Magistrix Erona)
[//]: # ([Spell][Mage] Fireball)
[//]: # ([Npc][Drop] Ghostclaw Lynx)
[//]: # ([Web] Armory doesnt work)

**Description**: 
I aggroed him and vanished. After that, another one spawned, and now there are two of him on the spawn point. Entry: 11076
Edit: Same happened on the fourth cauldron, with Cauldron Lord Soulwrath.
**Current behaviour**:
![screenshot_524](https://user-images.githubusercontent.com/40346279/46390759-ca469580-c6af-11e8-8c8f-45058d56fb20.png)
**Expected behaviour**: 
Shouldn't have 2 of them together
**Server Revision**:

**Comment by Evolvee** [comment]
was fixed in some previous revs
