### ISSUE TITLE
Reputation from mob killing while in group and dead

### ISSUE THREAD

**Issue by Erodraeda** [Atlantiss/NetherwingBugtracker#1125]
[//]: # (Enclose links to things related to the bug using http://wowhead.com or any other TBC database.)
[//]: # (You can use screenshot ingame to visual the issue.)
[//]: # (Write your tickets according to the format:)
[//]: # ([Quest][Azuremyst Isle] Red Snapper - Very Tasty!)
[//]: # ([NPC] Magistrix Erona)
[//]: # ([Spell][Mage] Fireball)
[//]: # ([Npc][Drop] Ghostclaw Lynx)
[//]: # ([Web] Armory doesnt work)

**Description**: 
I was dead, running for my corpse, and got reputation from a party member, while questing in WPL. reputation should only be given to a player who is close to the mob while killed, if in the party.
**Current behaviour**:
I was dead, running for my corpse, and got reputation from a party member, while questing in WPL. 
**Expected behaviour**: 
Reputation should only be given to a player who is close to the mob while killed, if in the party.
**Server Revision**:

**Comment by Wolffenstein** [comment]
I think it still gives you reputation if your corpse is close enough to your party member.

**Comment by Manaci** [comment]
That's how people farmed Timbermaw rep for their twinks yeah
