### ISSUE TITLE
[NPC] position of npc + player in silvermoon clips into the ground

### ISSUE THREAD

**Issue by DarthNekr0s** [Atlantiss/NetherwingBugtracker#1126]
**Description**:  Parnis in silvermoon city (entry 16613) is standing on a rug that his feet clip into, when player walks on it this also happens. looks like the cart behind him also clips a little with its wheels, and you can see the crate sitting on the edge of the rug slightly does it, so possibly other gameobjects on this area too.

**Current behaviour**: clipping

**Expected behaviour**:  the rug should be treated as ground

**Server Revision**:  2108

![wowscrnshot_100318_164226](https://user-images.githubusercontent.com/16113944/46394275-f7388e00-c72b-11e8-89ae-4766eda92191.jpg)

**Comment by aresbrutus** [comment]
This is clientside = blizzlike. Nothing the server can do about this.
