### ISSUE TITLE
[NPC]Arikara <Vengeance>#10882 doesn't despawn/doesn't despawn quick enough after spawned

### ISSUE THREAD

**Issue by Tenoutoften** [Atlantiss/NetherwingBugtracker#1127]
**Description**: 
[[NPC]Arikara <Vengeance>](https://db.excalibur.ws/?npc=10882) doesn't despawn after spawned by using [[Item]Incendia Powder](https://db.excalibur.ws/?item=12785) on [[Object]Sacred Fire of Life#175944(https://db.excalibur.ws/?object=175944), part of the [[Quest]Arikara](https://db.excalibur.ws/?quest=5088). Video of the event [here](https://www.youtube.com/watch?v=kcARV2iiHMQ&feature=youtu.be), including .npc info & .gps. I found the NPC already up when I arrived and it had been up for quite a while.

Should despawn in 10 seconds based upon [wowhead comment 1(Patch 3.1.3)](https://www.wowhead.com/quest=5088/arikara#comments:id=786285)
> This Comment is For Rogues (especially Subtlety spec) and Druids:
> 
> If you're going stealth to fight this mob, move quickly because if she isn't in combat after 10 seconds of being summoned, then she despawns.

[Wowhead comment 2 (Patch 3.0.3)](https://www.wowhead.com/quest=5088/arikara#comments:id=556303)
> Easy quest for a lvl28 rogue. Lit the fire and was able to stealth again, sneak up behind him and Ambush him. Have to get behind him quick though otherwise he'll disappear if not attacked right away. True the rewards weren't the greatest but still an simple quest.

On a side note, something that I can't confirm myself since I don't got any GM commands, another [wowhead comment (Patch 2.3.0)](https://www.wowhead.com/quest=5088/arikara#comments:id=193298) says that if a hunter tames this pet, it should have the spawning animation, a few more does too, apparently it was removed later on though.
> If tamed, this creature will always appear with the same puff of smoke and a rumbling sound effect that it does before the fight starts.

[[NPC]Arikara <Vengeance>](https://db.excalibur.ws/?npc=10882) was apparently an elite before 2.3 [wowhead comment (Patch 2.3.0)](https://www.wowhead.com/quest=5088/arikara#comments:id=185161)
> As of Patch 2.3 she is non-elite therefore easy soloable by any class.

**Expected behaviour**: 
Expected to quickly despawn, 10 seconds.

**Server Revision**: 
2108

**Comment by Evolvee** [comment]
rev 439kcolb
