### ISSUE TITLE
[NPC][Movement][Quest]Test of Endurance#1150 Shouldn't spawn waves of mobs, no waves have patrol, only open 1 box to start.

### ISSUE THREAD

**Issue by Tenoutoften** [Atlantiss/NetherwingBugtracker#1128]
**Description**: 
[[Quest]Test of Endurance#1150](https://db.excalibur.ws/?quest=1150)

Opening just one of the three [[Object]Harpy foodstuffs](https://db.excalibur.ws/?object=20447) should start the event: [Wowhead comment (Patch 2.1.3)](https://www.wowhead.com/quest=1150/test-of-endurance#comments:id=54827:reply=305849)
> Grenka comes with the 3rd (or 4th) wave, not the 3rd box. Open just one of the boxes, opening more will mean having fight through them all more than once.

[wowhead comment 2 (Patch 2.0.12)](https://www.wowhead.com/quest=1150/test-of-endurance#comments:id=71993)
> Destroying only one of the foodstuffs spawns 4 waves of Roguefeathers and Harpies. Grenka comes along with the 4th wave.

[wowhead comment 3 (Patch 2.1.3)](https://www.wowhead.com/quest=1150/test-of-endurance#comments:id=54827:reply=305849)
> Grenka comes with the 3rd (or 4th) wave, not the 3rd box. Open just one of the boxes, opening more will mean having fight through them all more than once.

Currently you have to open all boxes, as can be seen [here](https://www.youtube.com/watch?v=AKutOPj7EI0&feature=youtu.be)

The waves are spawning without any patrol, if you don't agro them immediately they just hang around, I realize [this video](https://youtu.be/_QI3SbSWQ3M?t=92) is from Wrath or later(Where the waves have been removed and it's just Grenka spawning) but perhaps this suggests that the waves should spawn and move towards the boxes? Makes a bit more sense than just spawning in a fixed position.

When the last wave arrives [I pulled Grenka without pulling the add she comes with(vid)](https://youtu.be/AKutOPj7EI0?t=117), these should probably be linked.

A [wowhead comment (Patch 2.0.10)](https://www.wowhead.com/quest=1150/test-of-endurance#comments:id=54827) suggests that they shouldn't despawn if you fail the event, at least for quite some time.
> Grenka was already spawned when I entered the final cave, with five harpies relatively near her. I pulled in two groups (solo 33 warrior) and didn't have much trouble, and looted the claw.
I suggest to not go through with that though.

**Expected behaviour**: 
Expect event to start by opening up just one [[Object]Harpy foodstuffs](https://db.excalibur.ws/?object=20447).
Expect the NPCs coming in waves to be linked with each other.
Expect the waves to have a patrol towards the boxes.

**Server Revision**: 
2108

**Comment by eryczek1615** [comment]
First [comment](https://www.wowhead.com/npc=4490/grenka-bloodscreech#comments)

![image](https://user-images.githubusercontent.com/4455568/47263536-d6ca4b00-d503-11e8-8bd8-01971bd7f8c1.png)

Only Grenka should spawn we we break the crates.

**Comment by Tenoutoften** [comment]
I edited the title, but I also notice another thing [[NPC]Grenka Bloodscreech#4490](https://db.excalibur.ws/?npc=4490) doesn't grant experience
