### ISSUE TITLE
[NPC][Quest] Searing Whelp - Identifying the Brood

### ISSUE THREAD

**Issue by kkumbaya** [Atlantiss/NetherwingBugtracker#1129]
[//]: # (Enclose links to things related to the bug using http://wowhead.com or any other TBC database.)
[//]: # (You can use screenshot ingame to visual the issue.)
[//]: # (Write your tickets according to the format:)
[//]: # ([Quest][Azuremyst Isle] Red Snapper - Very Tasty!)
[//]: # ([NPC] Magistrix Erona)
[//]: # ([Spell][Mage] Fireball)
[//]: # ([Npc][Drop] Ghostclaw Lynx)
[//]: # ([Web] Armory doesnt work)

Searing heart quest item drops significantly less than tongues. After killing 50 of them only received 2 hearts.
The drop chance should be same for both ~25%

**Server Revision**: 2108

**Comment by aresbrutus** [comment]
You seem to have been unlucky. The drop rate is correct.
