### ISSUE TITLE
Ghost Debuff

### ISSUE THREAD

**Issue by Warnoxx** [Atlantiss/NetherwingBugtracker#113]
[//]: # (Enclose links to things related to the bug using http://wowhead.com or any other TBC database.)
[//]: # (You can use screenshot ingame to visual the issue.)
[//]: # (Write your tickets according to the format:)
[//]: # ([Quest][Azuremyst Isle] Red Snapper - Very Tasty!)
[//]: # ([NPC] Magistrix Erona)
[//]: # ([Spell][Mage] Fireball)
[//]: # ([Npc][Drop] Ghostclaw Lynx)
[//]: # ([Web] Armory doesnt work)

**Description**: 
While dead ghost does not need to be a timed debuff
https://puu.sh/BzqGl/4cec2146df.png

**Current behaviour**:

**Expected behaviour**: 

**Server Revision**:

**Comment by aresbrutus** [comment]
https://i.imgur.com/p2xGssB.png

Seems to be an addon issue.
