### ISSUE TITLE
[NPC]Rok'Alim the Pounder should be elite prior to 2.3.0

### ISSUE THREAD

**Issue by Tenoutoften** [Atlantiss/NetherwingBugtracker#1130]
**Description**: 
Not sure if you guys want the quests to be "pre-nerf", I tried to look up answers on discord and searched a bit on github but didn't see anything.

[[NPC]Rok'Alim the Pounder](https://db.excalibur.ws/?npc=4499) should be elite prior to 2.3.0 according to [wowhead comment (Patch 2.3.0)](https://www.wowhead.com/quest=1151/test-of-strength#comments:id=184570)

**Current behaviour**:
Not elite

**Expected behaviour**: 
Should be elite prior to 2.3.0

**Server Revision**: 
2108

**Comment by totaemoeggerli** [comment]
Most NPCs that were elite are normal mobs on the server, this is intended

**Comment by Easyfraggy** [comment]
We are using the 2.3 leveling atm. If there is large demand for reverting the changes it could be done, but it might delay launch a bit doing so.

**Comment by Tenoutoften** [comment]
I think sticking with 2.3 leveling is the best option, especially if changing it would delay launch.
