### ISSUE TITLE
[NPC] Thundering Exile/Drywhisker Kobold

### ISSUE THREAD

**Issue by totaemoeggerli** [Atlantiss/NetherwingBugtracker#1131]
[//]: # (Enclose links to things related to the bug using http://wowhead.com or any other TBC database.)
[//]: # (You can use screenshot ingame to visual the issue.)
[//]: # (Write your tickets according to the format:)
[//]: # ([Quest][Azuremyst Isle] Red Snapper - Very Tasty!)
[//]: # ([NPC] Magistrix Erona)
[//]: # ([Spell][Mage] Fireball)
[//]: # ([Npc][Drop] Ghostclaw Lynx)
[//]: # ([Web] Armory doesnt work)

**Description**: 
[Drywhisker Kobold](https://www.wowhead.com/npc=2572/drywhisker-kobold) drops Thundering Charm
[Thundering Exile](https://www.wowhead.com/npc=2762/thundering-exile) doesn't drop anything at all

**Current behaviour**:
https://imgur.com/a/WxopMAX
This was the only Kobold that droped a Charm, I killed 20 more without any loot anomaly
Not sure if this is live https://github.com/Atlantiss/NetherwingBugtracker/issues/817 but I didn't get any loot from 5 exiles.

**Expected behaviour**: 
Only Thundering Exiles should drop the Charm. 

**Server Revision**: 2108

**Comment by aresbrutus** [comment]
Fixed in one of the upcoming updates.
