### ISSUE TITLE
Crag Boar Rib

### ISSUE THREAD

**Issue by AlteredAli** [Atlantiss/NetherwingBugtracker#1132]
[//]: # (Enclose links to things related to the bug using http://wowhead.com or any other TBC database.)
[//]: # (You can use screenshot ingame to visual the issue.)
[//]: # (Write your tickets according to the format:)
[//]: # ([Quest][Azuremyst Isle] Red Snapper - Very Tasty!)
[//]: # ([NPC] Magistrix Erona)
[//]: # ([Spell][Mage] Fireball)
[//]: # ([Npc][Drop] Ghostclaw Lynx)
[//]: # ([Web] Armory doesnt work)

**Description**: 
Extremely low drop chance
**Current behaviour**:
low drop chance
**Expected behaviour**: 
higher drop chance 
**Server Revision**: 
2108

**Comment by Shanghi** [comment]
This should be fixed in revision 2152.
