### ISSUE TITLE
[NPC] Syndicate Wizard polimorphs other Syndicate members

### ISSUE THREAD

**Issue by Mikik3jr** [Atlantiss/NetherwingBugtracker#1133]
[//]: # (Enclose links to things related to the bug using http://wowhead.com or any other TBC database.)
[//]: # (You can use screenshot ingame to visual the issue.)
[//]: # (Write your tickets according to the format:)
[//]: # ([Quest][Azuremyst Isle] Red Snapper - Very Tasty!)
[//]: # ([NPC] Magistrix Erona)
[//]: # ([Spell][Mage] Fireball)
[//]: # ([Npc][Drop] Ghostclaw Lynx)
[//]: # ([Web] Armory doesnt work)

**Description**: 
There are Syndicate Wizards in Strathbarn in Alterac Mountains. They cast different spells and polimorph ofc.
**Current behaviour**:
I witnessed that one of the mage polimorhped Jailor Borhuin, another syndicate member.
![wowscrnshot_100318_110814](https://user-images.githubusercontent.com/43505031/46401405-21bf2280-c6fd-11e8-8c2a-65493ae0f5ce.jpg)
![wowscrnshot_100318_110821](https://user-images.githubusercontent.com/43505031/46401406-2257b900-c6fd-11e8-83a4-8891d9f8d21e.jpg)
(2nd picture you can see the mage ID)
**Expected behaviour**: 
Well they should respect each other.
**Server Revision**: 
2108

**Comment by Evolvee** [comment]
rev 439kcolb
