### ISSUE TITLE
[Item] A Mangled Journal - High drop rate.

### ISSUE THREAD

**Issue by wowthings** [Atlantiss/NetherwingBugtracker#1134]
[//]: # (Enclose links to things related to the bug using http://wowhead.com or any other TBC database.)
[//]: # (You can use screenshot ingame to visual the issue.)
[//]: # (Write your tickets according to the format:)
[//]: # ([Quest][Azuremyst Isle] Red Snapper - Very Tasty!)
[//]: # ([NPC] Magistrix Erona)
[//]: # ([Spell][Mage] Fireball)
[//]: # ([Npc][Drop] Ghostclaw Lynx)
[//]: # ([Web] Armory doesnt work)

**Description**: 
[Item](http://db.hellfire-tbc.com/?item=11116) the enemies drop at Un'Goro Crater that begins a quest if you have enough luck to loot it.
**Current behaviour**:
Thing is it has a stupidly high drop rate
![vlcsnap-2018-10-03-11h15m18s824](https://user-images.githubusercontent.com/43504905/46401588-bd509300-c6fd-11e8-9edc-d0094b22cd98.png)
![vlcsnap-2018-10-03-11h15m32s685](https://user-images.githubusercontent.com/43504905/46401589-bd509300-c6fd-11e8-8539-90b9ac5afdd2.png)
![vlcsnap-2018-10-03-11h15m42s456](https://user-images.githubusercontent.com/43504905/46401590-bd509300-c6fd-11e8-87cc-a5fe8b070532.png)

Different classic and tbc databases say it should be around 4% and 0,3% depending on the mob.

**Expected behaviour**: 
Should be less common to drop.
**Server Revision**: 
2108

**Comment by Shanghi** [comment]
The reason it has such a low drop rate on old databases is because it's only looted once (if you use it), then every kill after that counts as not having it. 

There's a lot of retail comments about it, like:
> "I got this from a raptor, and it dropped another two or three times in the next 15-20 minutes of running through the zone and killing maybe 10 mobs. It had a very high drop rate for me (or perhaps I was just very lucky). I did not accept the quest yet, though - maybe that's why it dropped multiple times?"
>
> "i had the same experience - mutiple drops after i first got the drop- and i too had not look nor accepted quest yet and also did not loot after first drop"
>
> "the drop rate on these from muculent cant be correct... i got 3 in 4 kills, and that's not 2% drop chance"
>
> "These things drop ALL the time, somtimes in twice a row."
>
> "Anyone have trouble picking this item up? I got three of these drops, but I cannot add any of them to my Inventory."
>
> "getting sick of not being able to skin a mob without having to destroy my current copy to grab the new one..."

**Comment by wowthings** [comment]
I should read the comments more often with these type of things, since it was green I assumed it was rare or something. Thanks Shanghi.
