### ISSUE TITLE
Ogrimmar to STV zep still acting weird (not a repeat, other was closed but it's still bugged)

### ISSUE THREAD

**Issue by Anselm123** [Atlantiss/NetherwingBugtracker#1135]
Other ticket was closed due to being fixed but it's still acting wonky. She still shouts that it's arrived when it hasn't, I waited and it finally turned up. Got on it and then after a loading screen got ported to above Alterac mountains and floating in the air

![wowscrnshot_100318_105234](https://user-images.githubusercontent.com/36844570/46402547-4ff23180-c700-11e8-97c5-0003cec6a6b8.jpg)

After a few minutes it was fine and I got to STV but after i left the zep it turned invisible

**Comment by Emityx** [comment]
It's known issue. Same with boats. It's transporting issue and devs are working on this.

**Comment by Anselm123** [comment]
Cool I just wanted to add another one to it because the shouting for the zep happened again but it was closed due to a fix a few days ago, so just wanted to show that it's still not working that part too
