### ISSUE TITLE
[Quest][Ashenvale] Call of Water

### ISSUE THREAD

**Issue by narayagh** [Atlantiss/NetherwingBugtracker#1136]
[//]: # (Enclose links to things related to the bug using http://wowhead.com or any other TBC database.)
[//]: # (You can use screenshot ingame to visual the issue.)
[//]: # (Write your tickets according to the format:)
[//]: # ([Quest][Azuremyst Isle] Red Snapper - Very Tasty!)
[//]: # ([NPC] Magistrix Erona)
[//]: # ([Spell][Mage] Fireball)
[//]: # ([Npc][Drop] Ghostclaw Lynx)
[//]: # ([Web] Armory doesnt work)

**Description**: 
Text in tooltip for the shrine in Ruins of Stardust

**Current behaviour**:
See here:
![wow_2018-10-03_12-02-30](https://user-images.githubusercontent.com/13250690/46404185-bda05c80-c704-11e8-9068-84c1fa5f63a3.jpg)

**Expected behaviour**: 

**Server Revision**: 
2108

**Comment by xmesaj2** [comment]
fixed in 2139
