### ISSUE TITLE
[Quest] [NPC] Stinky's Escape

### ISSUE THREAD

**Issue by Kidcudi123** [Atlantiss/NetherwingBugtracker#1138]
I managed to bug him out by having mobs already on me and then accepting the quest. He wouldnt move and couldnt retake the quest.

**Comment by Consita** [comment]
tested on rev 3441
both factions work.
still part of [Megathread][Quest] Issues with Escort Quests(React state, Faction, Interaction, Buff reset, Pathing)
#3678

**Comment by Godmatik** [comment]
Can't reproduce - unable to bug him out as described.
