### ISSUE TITLE
[Item] Torch of Retribution

### ISSUE THREAD

**Issue by Firroth** [Atlantiss/NetherwingBugtracker#1139]
[Item] [Torch of Retribution](https://www.wowhead.com/item=10515/torch-of-retribution)

**Current behaviour**:

[Torch of Retribution](https://www.wowhead.com/item=10515/torch-of-retribution) is totally broken, it has 0.5 attack speed with around 50dmg. Making this OP weapon to skill unarmed skill in less than 10min from 0 to max. Smart people will abuse this method.

![screenshot_1](https://user-images.githubusercontent.com/43505196/46405219-d1998d80-c707-11e8-8ab3-5b3312777b42.png)

**Expected behaviour**: 
It should deal 0 damage, and have normal attack speed like without weapons equiped = 2.00 attack speed.

![screenshot_2](https://user-images.githubusercontent.com/43505196/46405622-1671f400-c709-11e8-8617-909d183e66ce.png)

**Server Revision**: 
2108

**Comment by Wolffenstein** [comment]
Fixed in rev 2123.
