### ISSUE TITLE
[Ability] Mana Tap

### ISSUE THREAD

**Issue by networm555** [Atlantiss/NetherwingBugtracker#1141]
Current behaviour : gives player 1 stack of Arcane Energy.
Expected behaviour : gives player 1 stack and reduce's targets mana by x amount.

**Comment by The14me** [comment]
i played pala before like 2h and was fine O.o

**Comment by networm555** [comment]
i tried it one every mob with mana in  starting BE location. used pitbull to monitor mana bar.

**Comment by Wolffenstein** [comment]
It definitely works fine, try disabling any UI addons.
