### ISSUE TITLE
[Core] Mobs don't attack or reset

### ISSUE THREAD

**Issue by totaemoeggerli** [Atlantiss/NetherwingBugtracker#1142]
[//]: # (Enclose links to things related to the bug using http://wowhead.com or any other TBC database.)
[//]: # (You can use screenshot ingame to visual the issue.)
[//]: # (Write your tickets according to the format:)
[//]: # ([Quest][Azuremyst Isle] Red Snapper - Very Tasty!)
[//]: # ([NPC] Magistrix Erona)
[//]: # ([Spell][Mage] Fireball)
[//]: # ([Npc][Drop] Ghostclaw Lynx)
[//]: # ([Web] Armory doesnt work)

**Description**: 
I had two cases where the mob wouldn't attack and my autoattack didn't work. This are the two only cases I've encountered.
What happened to me:
-autoattacks stoped working
-still able to use abilities (no issue with LOS, mobs never evade)
-stealth delay bug https://github.com/Atlantiss/NetherwingBugtracker/issues/295

What happened to the mobs:
-stoped attacking or didn't use abilities for a really long time (ogre)
-don't reset

Some people told me that my own autoattack can "break" from alt tabbing (which I do alot!) and that you can fix this with klicking alt and/or changeing target. I'll try this next time it happened.
However, this didn't only break my autoattack but also break the mob. The kobold doesn't fight back at all, the ogre doesn't do anything for the first half of the fight.
Something similar happened here: https://github.com/Atlantiss/NetherwingBugtracker/issues/1007 but my autoattack didn't break and there was another player involved.
I will try to reproduce the issue with stealth delay and alt tabbing and hopefully get more info.

**Current behaviour**:
![kobold](https://thumbs.gfycat.com/PracticalHandyHuemul-size_restricted.gif)
direct link for better quality: https://gfycat.com/gifs/detail/PracticalHandyHuemul
![orgre](https://thumbs.gfycat.com/ElatedCheeryGyrfalcon-size_restricted.gif)
direct link for better quality: https://gfycat.com/gifs/detail/ElatedCheeryGyrfalcon

**Expected behaviour**: 
Mobs should never be passive like this, if anything goes wrong they should reset and/or evade.

**Server Revision**: 2108

**Comment by totaemoeggerli** [comment]
I was able to reproduce part of this bug. If I provoke the stealth delay bug and attack before the mob resets, I break my own autoattack. You can see this in both examples here. There isn't a single white hit.
https://gfycat.com/DistantAnnualAsiandamselfly
https://gfycat.com/SmugNiftyIraniangroundjay
I haven't seen any other mob not attacking. This issue shouldn't exist when stealth delay bug is fixed.

**Comment by totaemoeggerli** [comment]
I had another mob not attacking back and not resetting.
https://gfycat.com/gifs/detail/ImpeccableGivingDotterel
roots break before starfire hit on the 2. mob
there is this bug https://github.com/Atlantiss/NetherwingBugtracker/issues/869 that happens here too
the mob resets slightly before the starfire hits and buggs out from then on (if I didn't cast starfire I would have left combat)

**Comment by Easyfraggy** [comment]
This doesn't seem to happen anymore - correct?

**Comment by totaemoeggerli** [comment]
I haven't seen this happening anymore
