### ISSUE TITLE
[NPC] Boulderfist Shaman totem race inconsistency

### ISSUE THREAD

**Issue by totaemoeggerli** [Atlantiss/NetherwingBugtracker#1143]
[//]: # (Enclose links to things related to the bug using http://wowhead.com or any other TBC database.)
[//]: # (You can use screenshot ingame to visual the issue.)
[//]: # (Write your tickets according to the format:)
[//]: # ([Quest][Azuremyst Isle] Red Snapper - Very Tasty!)
[//]: # ([NPC] Magistrix Erona)
[//]: # ([Spell][Mage] Fireball)
[//]: # ([Npc][Drop] Ghostclaw Lynx)
[//]: # ([Web] Armory doesnt work)

**Description**: 
[Boulderfist Shamans](https://www.wowhead.com/npc=2570/boulderfist-shaman) uses the horde and draenei totem randomly. Same thing happened here https://github.com/Atlantiss/NetherwingBugtracker/issues/808 (still not working correctly btw)
**Current behaviour**:
Some times the NPC uses the dreanei totem
![draenei totem](https://thumbs.gfycat.com/WigglyTemptingGalago-size_restricted.gif)

**Expected behaviour**: 
It should only use the horde totem
![horde totem](https://thumbs.gfycat.com/NicePaltryAustraliansilkyterrier-size_restricted.gif)

**Server Revision**: 2108

**Comment by totaemoeggerli** [comment]
same thing with [Stonevault Shaman](https://www.wowhead.com/npc=2894/stonevault-shaman)
![clip](https://thumbs.gfycat.com/GiantYawningFattaileddunnart-size_restricted.gif)
and one totem is overwritten by the other the same way I discribed here: https://github.com/Atlantiss/NetherwingBugtracker/issues/902

**Comment by The14me** [comment]
rev 3441.A global issue with NPC that use totems.

**Comment by Wolffenstein** [comment]
Fixed in rev 3449.
