### ISSUE TITLE
[Item] Bloodshot Spider Eye

### ISSUE THREAD

**Issue by mbzz88** [Atlantiss/NetherwingBugtracker#1146]
Description: Bloodshot Spider Eye http://db.hellfire-tbc.com/?item=20610 is dropping for players not on the quest (shaman class quest)

Current behaviour: Dropping for players not on quest. Dropped from Sand Skitterer http://db.hellfire-tbc.com/?npc=11738.

Expected behaviour: Only drops for players doing Spirit Totem quest http://db.hellfire-tbc.com/?quest=8412

Server Revision: 2108

**Comment by Easyfraggy** [comment]
2121
