### ISSUE TITLE
[NPC] Shleipnarr (rare) - missing spells.

### ISSUE THREAD

**Issue by Firroth** [Atlantiss/NetherwingBugtracker#1147]
[NPC] [Shleipnarr](https://web.archive.org/web/20090105214752/http://wow.allakhazam.com:80/db/mob.html?wmob=8280)

**Current behaviour**:
He doesn't use any spells.

**Expected behaviour**: 
He should be using spell [terrify](https://web.archive.org/web/20090105214752/http://wow.allakhazam.com:80/db/spell.html?wspell=7399) and [mana burn](https://classicdb.ch/?spell=13321)

**Server Revision**: 
2108

**Comment by The14me** [comment]
Confirm,have the spell's,but there may be some problem.

**Comment by Evolvee** [comment]
rev Xd

but the NPC wont use mana burn if u have no mana
and the fear is only if u are in melee range ^^
