### ISSUE TITLE
[NPC] Slave Worker 

### ISSUE THREAD

**Issue by Firroth** [Atlantiss/NetherwingBugtracker#1148]
[NPC] [Slave Worker](https://www.wowhead.com/npc=5843/slave-worker)

**Current behaviour**:
1. When [Dark Iron Slaver](https://www.wowhead.com/npc=5844/dark-iron-slaver) / [Taskmaster](https://www.wowhead.com/npc=5846/dark-iron-taskmaster) dies near them, they "flee" something akin to circling and then they stay in some stupid positions, like on center of the cave, depends when debuff wears off of them.
2. When [Dark Iron Slaver](https://www.wowhead.com/npc=5844/dark-iron-slaver) / [Taskmaster](https://www.wowhead.com/npc=5846/dark-iron-taskmaster) is attacked near them by player they don't rush to help [Dark Iron Slaver](https://www.wowhead.com/npc=5844/dark-iron-slaver) / [Taskmaster](https://www.wowhead.com/npc=5846/dark-iron-taskmaster) against the player.
3. Aren't hostile to all players but neutral. (post 2.3)

**Expected behaviour**: 
1. When [Dark Iron Slaver](https://www.wowhead.com/npc=5844/dark-iron-slaver) / [Taskmaster](https://www.wowhead.com/npc=5846/dark-iron-taskmaster) dies near them, they should "flee" something akin to circling and then return back to their ORIGINAL position (which is near walls, they should mine cave walls not the ground).
2. When [Dark Iron Slaver](https://www.wowhead.com/npc=5844/dark-iron-slaver) / [Taskmaster](https://www.wowhead.com/npc=5846/dark-iron-taskmaster) is attacked near them by player they should rush to help them
[Dark Iron Slaver](https://www.wowhead.com/npc=5844/dark-iron-slaver) / [Taskmaster](https://www.wowhead.com/npc=5846/dark-iron-taskmaster) against the player.
3. Should be hostile to all players not neutral. (pre 2.3)

**Server Revision**: 
2108

**Comment by Evolvee** [comment]
fixed in next rev
