### ISSUE TITLE
Spell Delay

### ISSUE THREAD

**Issue by yokothan** [Atlantiss/NetherwingBugtracker#115]
[//]: # (Enclose links to things related to the bug using http://wowhead.com or any other TBC database.)
[//]: # (You can use screenshot ingame to visual the issue.)
[//]: # (Write your tickets according to the format:)
[//]: # ([Quest][Azuremyst Isle] Red Snapper - Very Tasty!)
[//]: # ([NPC] Magistrix Erona)
[//]: # ([Spell][Mage] Fireball)
[//]: # ([Npc][Drop] Ghostclaw Lynx)
[//]: # ([Web] Armory doesnt work)

**Description**: Spell are having anywhere from .5-1 sec delays

**Current behaviour**:

**Expected behaviour**: 

**Server Revision**:

**Comment by DoctorRaymos** [comment]
Intentional, it is blizzlike. You should post video from retail to prove otherwise.

**Comment by Wolffenstein** [comment]
Intended.
