### ISSUE TITLE
[Quest][NPC][Badlands] Broken Alliance/Boss Tho'grun

### ISSUE THREAD

**Issue by totaemoeggerli** [Atlantiss/NetherwingBugtracker#1152]
[//]: # (Enclose links to things related to the bug using http://wowhead.com or any other TBC database.)
[//]: # (You can use screenshot ingame to visual the issue.)
[//]: # (Write your tickets according to the format:)
[//]: # ([Quest][Azuremyst Isle] Red Snapper - Very Tasty!)
[//]: # ([NPC] Magistrix Erona)
[//]: # ([Spell][Mage] Fireball)
[//]: # ([Npc][Drop] Ghostclaw Lynx)
[//]: # ([Web] Armory doesnt work)

**Description**: 
[Boss Tho'grun](https://www.wowhead.com/npc=2944/boss-thogrun) walks into mountain. Adds aren't following him. He respawns without adds.

**Current behaviour**:
His adds aren't escorting him but standing in place.
![escort](https://imgur.com/y5RLY72.jpg)

Boss Tho'grun walks into a mountain.
![clip](https://thumbs.gfycat.com/FirmLongKitty-size_restricted.gif)

Edit: The adds start patroling when the boss catches up to them
![escort2](https://imgur.com/jm8rSpc.jpg)

**Expected behaviour**: 
Adds should follow Boss Tho'grun. His patrol shouldn't go through a mountain.

**Server Revision**: 2108

**Comment by tomatosz** [comment]
Update: I saw part of the adds follow Boss Tho'grun, another one walked by later on.
I saw them (him and his patrols) walking through the mountain at this location:
![image](https://user-images.githubusercontent.com/18441882/72632583-dca51b00-3956-11ea-9e74-60840abddf79.png)

**Comment by Evolvee** [comment]
I made new waypoints, if that doesnt help it, its just scuffed core.
