### ISSUE TITLE
[Quest]Test of Lore#6628 missing RP test on correct answer

### ISSUE THREAD

**Issue by Tenoutoften** [Atlantiss/NetherwingBugtracker#1154]
**Description**: 
[[Quest]Test of Lore](https://www.wowhead.com/quest=6628/test-of-lore) seems to be missing RP text when picking the correct answer. RP text can be seen in this [video of a quite later expansion](https://youtu.be/_QI3SbSWQ3M?t=469)

**Current behaviour**:
Only gives RP text on wrong answer.

**Expected behaviour**: 
Expected to give RP text on correct answer.

[[NPC]Parqual Fintallas](https://db.excalibur.ws/?npc=4488) should say:
>You have done well, <Name>. Contine your serach for knowledge, and remember the history you have learned. 

**Server Revision**: 
2108

**Comment by aresbrutus** [comment]
Confirmed.

He should do /bow emote and then say: `You have done well, $n. Continue your search for knowledge, and remember the history you have learned.` on the CORRECT answer.

**Comment by Evolvee** [comment]
wasnt there some issue where the text would be executes only sometimes like 3 gazilion years ago?

**Comment by Evolvee** [comment]
https://github.com/Atlantiss/AtlantissTbcBTOLD/issues/1273
https://github.com/Atlantiss/AtlantissTbcBTOLD/issues/1274
