### ISSUE TITLE
[NPC] Razormaw - problem with sound

### ISSUE THREAD

**Issue by narayagh** [Atlantiss/NetherwingBugtracker#1156]
[//]: # (Enclose links to things related to the bug using http://wowhead.com or any other TBC database.)
[//]: # (You can use screenshot ingame to visual the issue.)
[//]: # (Write your tickets according to the format:)
[//]: # ([Quest][Azuremyst Isle] Red Snapper - Very Tasty!)
[//]: # ([NPC] Magistrix Erona)
[//]: # ([Spell][Mage] Fireball)
[//]: # ([Npc][Drop] Ghostclaw Lynx)
[//]: # ([Web] Armory doesnt work)

**Description**: 
Problem with sound after killing Razormaw.

**Current behaviour**:
Razormaw sounds keep playing looped after he's dead.
See here: https://streamable.com/r6daf
And here is when the sound finally stopped: https://streamable.com/rgp8n

**Expected behaviour**: 
No sound after death.

**Server Revision**: 
2108

**Comment by Wolffenstein** [comment]
That must be a client bug. He does not send any sounds server-side.
