### ISSUE TITLE
Lorax's Quest, Winterspring, missing

### ISSUE THREAD

**Issue by Tinnoan** [Atlantiss/NetherwingBugtracker#1157]
Lorax should be giving [Lorax's Quest](http://wowwiki.wikia.com/wiki/Quest:Lorax%27s_Tale), and after that there should be a follow up quest for Blackrock Spire called [The Demon Forge](http://wowwiki.wikia.com/wiki/Quest:The_Demon_Forge).

Lorax's Quest should be available at level 55 according to [this](https://web.archive.org/web/20071105195459/http://www.wowhead.com/?quest=5126#comments)

![image](https://user-images.githubusercontent.com/25431721/46425623-75049580-c73c-11e8-9eca-b00dcebd3e01.png)

**Comment by Shanghi** [comment]
They were already set to 55 before, but you need 285 blacksmithing to do them. Do you have that?

**Comment by Tinnoan** [comment]
oh sorry, didn't know you needed that, didn't see that requirement anywhere.

**Comment by Shanghi** [comment]
It's mostly just in comments now since wowwiki didn't mention it like it usually does. Wowhead also lists it as a blacksmithing quest but I didn't even notice that either at first!
