### ISSUE TITLE
Pelt collection. Eversong woods wildlife.

### ISSUE THREAD

**Issue by networm555** [Atlantiss/NetherwingBugtracker#1158]
[Quest][Eversong Woods] Pelt Collection
[Npc] Springpaw Stalker
[Npc] Springpaw Elder

**Description**: 
Missing spawns.  Bottleneck even with 2-3 players on quest . Need more cats with drop. Alot more. Same with dragonhawks. Locations feels empty.

**Comment by aresbrutus** [comment]
There are 99 total of these mobs, we should be fine, especially with dynamic respawn.
