### ISSUE TITLE
[Quest][Badlands] Badlands Reagents Run

### ISSUE THREAD

**Issue by totaemoeggerli** [Atlantiss/NetherwingBugtracker#1159]
[//]: # (Enclose links to things related to the bug using http://wowhead.com or any other TBC database.)
[//]: # (You can use screenshot ingame to visual the issue.)
[//]: # (Write your tickets according to the format:)
[//]: # ([Quest][Azuremyst Isle] Red Snapper - Very Tasty!)
[//]: # ([NPC] Magistrix Erona)
[//]: # ([Spell][Mage] Fireball)
[//]: # ([Npc][Drop] Ghostclaw Lynx)
[//]: # ([Web] Armory doesnt work)

**Description**:
https://www.wowhead.com/quest=2500/badlands-reagent-run
Buzzard Gizzard has an extremly low drop rate.

**Current behaviour**:
Didn't count the buzzards killed but I got 19 Buzzard Wings (around 1/3 drop chance). Only 1 Buzzard Gizzard droped.

**Expected behaviour**: 
There are many Wowhead comment about low drop rate but this is ridiculous.

Zettaraid on 2008/02/27 (Patch 2.3.3)
> Not true, I killed about 10 giant buzzards at 15.61 and got em all (5). 

argenex on 2008/03/19 (Patch 2.3.3)
> after killing exactly 33 of them, I have 1 buzzard gizzard. ...

**Server Revision**: 2108

**Comment by kkumbaya** [comment]
Agree with op, killed 40 of them and 0 dropped

**Comment by aresbrutus** [comment]
Global loot issue.

**Comment by Shanghi** [comment]
I'm not sure when exactly, but a lot of animal loot like this was fixed a while ago. I just tested these and they'll drop at a reasonable rate now. I got 4 just from killing buzzards around one of the giant skeletons.
