### ISSUE TITLE
Durotar -> Grom'gol Zeppelin

### ISSUE THREAD

**Issue by manslaughter** [Atlantiss/NetherwingBugtracker#1160]
**Description**: https://youtu.be/XcrpLqP_Zf8 (You can skip to around 1:20 to see the zeppelin despawn)

**Current behaviour**: Zeppelin arrives late, despawns before reaching tower.

**Expected behaviour**: I can use the zeppelin

**Server Revision**: 2108

**Comment by Wolffenstein** [comment]
Already reported. We're working on it.
