### ISSUE TITLE
[Warlock] Pets and Mounts

### ISSUE THREAD

**Issue by Arnamik12** [Atlantiss/NetherwingBugtracker#1161]
**Description**: 
Pets 'die' when you log off on mount as a warlock
**Current behaviour**:
If you summon a warlock pet, then mount up and log off, your pet doesnt' resummon itself when you dismount, whereas if you dont log off at all it does

**Expected behaviour**: 
Pet resummons itself after dismounting like normal, even if you have logged off/disconnected on mount.
**Server Revision**: 
2108

**Comment by The14me** [comment]
Cant reproduce it .Work just fine  with Imp,void,succub. Tested with the Rocket mount at ground.

**Comment by Arnamik12** [comment]
I think it got fixed somewhere along the way, havent really played the warlock in a while so :)
