### ISSUE TITLE
[NPC] Zukk'ash Worker#5246 fleeing is incorrect.

### ISSUE THREAD

**Issue by Jezofine** [Atlantiss/NetherwingBugtracker#1162]
**Current behaviour**:
[Zukk'ash Worker](https://www.wowhead.com/npc=5246/zukkash-worker#comments) flees at ~15% health, with usual speed.

**Expected behaviour**: 
[Zukk'ash Worker] should flee at 30%, possibly with speed increase.
Maybe should work as [Centipaar Worker](https://www.wowhead.com/npc=5458/centipaar-worker#comments).
2.1.1 comment:
> Unlike many beasts, and like many humanoids, these will run in fear when low on health -- and they're fast little buggers, too.

2.3.0 comment:
>They run also a lot sooner than other running mobs. They flee at about 30% health.

[Joana's reference](https://youtu.be/VMVOsznwNc4?list=PLMeJnlp72R7p-X7PgsMFqqjPtcxhF7kB_&t=2786)

**Server Revision**: 2124

**Comment by Evolvee** [comment]
rev 439kcolb
