### ISSUE TITLE
Twilight Marauder Morna patrol, Silithus

### ISSUE THREAD

**Issue by Erodraeda** [Atlantiss/NetherwingBugtracker#1163]
[//]: # (Enclose links to things related to the bug using http://wowhead.com or any other TBC database.)
[//]: # (You can use screenshot ingame to visual the issue.)
[//]: # (Write your tickets according to the format:)
[//]: # ([Quest][Azuremyst Isle] Red Snapper - Very Tasty!)
[//]: # ([NPC] Magistrix Erona)
[//]: # ([Spell][Mage] Fireball)
[//]: # ([Npc][Drop] Ghostclaw Lynx)
[//]: # ([Web] Armory doesnt work)

**Description**: 
The patrol was composed of several mobs, but they were all stacked on top of each other, instead of walking in a group.
**Current behaviour**:
![screenshot_525](https://user-images.githubusercontent.com/40346279/46433133-74f99b00-c726-11e8-98c7-bd5ccc2dc2ad.png)
**Expected behaviour**: 
Should walk in a group, not stacked.
**Server Revision**:

**Comment by aresbrutus** [comment]
Fixed in one of the upcoming updates.
