### ISSUE TITLE
[NPC] Stinglasher#14661 - abilities, appearance and spawn might be incorrect.

### ISSUE THREAD

**Issue by Jezofine** [Atlantiss/NetherwingBugtracker#1164]
**Description**:
[Stinglasher](https://www.wowhead.com/npc=14661/stinglasher#comments) is a silithid bug in Feralas for a quest with the same name.

**Current behaviour**:
Doesn't use any abilities, only meelee hits.
Seem to spawn on the same spot (77, 61), patrols inside and a little bit outside the hive.
Doesn't have unique aura.

**Expected behaviour**:
[Joana's reference](https://youtu.be/VMVOsznwNc4?list=PLMeJnlp72R7p-X7PgsMFqqjPtcxhF7kB_&t=2820)
2.0 comment:
> He will stack Venom Sting on you, for 11-12 poison damage per 5 seconds a cast. He can Lash, like raptor taillashers do, which sometimes cause you to drop weapon for 5 seconds, in addition to a brief stun. Pretty entertaining as a matter of fight.

2.1.2 comment:
> He does a poison that can stack up to 5 times doing 12 dammage per 5 seconds each application.

I could not find link with these abilities on Stinglasher. Maybe he was nerfed later.
He uses some kind of Venom Sting in Joana's video, maybe like [Stinger's Venom Sting](https://www.wowhead.com/spell=5416/venom-sting).
And icon on Joana's pet in the end of fight looks like [Lash](https://www.wowhead.com/spell=6607/lash) (used by raptors, scorpids etc).

Should have multiple spawns and patrol outside.
Should have unique [greenish aura](https://wow.zamimg.com/uploads/screenshots/normal/76925-stinglasher.jpg).

**Server Revision**: 2124

**Comment by Evolvee** [comment]
@aresbrutus when u are done with pathing, poke me here to add abilities and shit

**Comment by aresbrutus** [comment]
Aight

**Comment by aresbrutus** [comment]
Added multiple spawn points + patrols. You can fix the rest Evolve but I please wait on my rev `Tycho` to be applied first so your stuff does not overwrite.

**Comment by Evolvee** [comment]
rev Block
