### ISSUE TITLE
[Dungeon][Warrior][Spell] Charge bugged out in RFD spiral to Ammenar several times

### ISSUE THREAD

**Issue by FrozenBread** [Atlantiss/NetherwingBugtracker#1165]
[//]: # (Enclose links to things related to the bug using http://wowhead.com or any other TBC database.)
[//]: # (You can use screenshot ingame to visual the issue.)
[//]: # (Write your tickets according to the format:)
[//]: # ([Quest][Azuremyst Isle] Red Snapper - Very Tasty!)
[//]: # ([NPC] Magistrix Erona)
[//]: # ([Spell][Mage] Fireball)
[//]: # ([Npc][Drop] Ghostclaw Lynx)
[//]: # ([Web] Armory doesnt work)

**Description**:  While going up the spiral, I would have my charge make my character walk back to spots close to the charge starting point.
Video evidence: https://streamable.com/c631z

**Current behaviour**: Charge goes to the target, then character automatically starts walking back.

**Expected behaviour**: Charge should stop at the target.

**Server Revision**: 2124

**Comment by Easyfraggy** [comment]
Tried to recreate with around 600 charges and can't get this to happen, possible spell interaction?

In vid I see Draenei Racial and ret aura as only buffs active when charge happens. Healing Stream and Strength of Earth fade right before the charge.

It runs back to a spot a little bit further back than your original charge position. It's extremely weird.

**Comment by Tinnoan** [comment]
Happened to me as well as a Tauren druid in bear form with Feral Charge, I had a Warlock, Hunter and Rogue in the party only at the time

**Comment by Tinnoan** [comment]
I haven't been able to reproduce the bug again, just tried out going to RFD by myself and trying to charge most packs on the way up to the top, was by myself this time.
