### ISSUE TITLE
Quest reward bug.

### ISSUE THREAD

**Issue by Neophrone** [Atlantiss/NetherwingBugtracker#1166]
[//]: # (Enclose links to things related to the bug using http://wowhead.com or any other TBC database.)
[//]: # (You can use screenshot ingame to visual the issue.)
[//]: # (Write your tickets according to the format:)
[//]: # ([Quest][Azuremyst Isle] Red Snapper - Very Tasty!)
[//]: # ([NPC] Magistrix Erona)
[//]: # ([Spell][Mage] Fireball)
[//]: # ([Npc][Drop] Ghostclaw Lynx)
[//]: # ([Web] Armory doesnt work)

**Description**: After ending the quest "Bring The Light", I've got only 1 item (sword) insteed of both item (sword + neck). I had only 1 free slot in my bag, so I think this is the reason for this bug. I hope neck will be deliver me by mail.

**Current behaviour**: I've got 1 item for quest, where I should get 2 items as a reward.

**Expected behaviour**: If player have only 1 free slot in bag, he can't end this quest, and a warning message should appear (u'r bags is full or something like that). 
![wowscrnshot_100318_223341](https://user-images.githubusercontent.com/43533040/46434866-9033cd00-c75d-11e8-95e5-f386faa08c3e.jpg)

**Server Revision**: 2124.

**Comment by Manaci** [comment]
Fixed
