### ISSUE TITLE
[Spell][Hunter]Revive pet

### ISSUE THREAD

**Issue by DeltaLoads** [Atlantiss/NetherwingBugtracker#1167]
**Description**: 
You can use Revive Pet even if your pet is not dead and just dismissed, not a huge problem just abit weird - you should get warning that pet is alive instead
**Current behaviour**:
You can use Revive Pet even if your pet is not dead and just dismissed
**Expected behaviour**: 
You shouldn't be able to Revive Pet if pet is alive and just dismissed
**Server Revision**: 
2124

**Comment by Manaci** [comment]
More detailed with proof [here](https://github.com/Atlantiss/NetherwingBugtracker/issues/3560)
