### ISSUE TITLE
Multiple potions usage at once.

### ISSUE THREAD

**Issue by Erodraeda** [Atlantiss/NetherwingBugtracker#1168]
[//]: # (Enclose links to things related to the bug using http://wowhead.com or any other TBC database.)
[//]: # (You can use screenshot ingame to visual the issue.)
[//]: # (Write your tickets according to the format:)
[//]: # ([Quest][Azuremyst Isle] Red Snapper - Very Tasty!)
[//]: # ([NPC] Magistrix Erona)
[//]: # ([Spell][Mage] Fireball)
[//]: # ([Npc][Drop] Ghostclaw Lynx)
[//]: # ([Web] Armory doesnt work)

**Description**: 
I was gonna drink my good old Noggenfogger elixir, and accidentally pressed both buttons at the same time, and used 2 potions at once (it has a cooldown, shouldn't happen). Then I tried again, with a 10-rightclicks-button, and it used 4 at once. I asked my friend to try it with Mana Potions, thinking of how it can be abused on raids (regen more Mana per 2min-cooldown-tick), and it happened, he drank 2 mana potions at once, getting the benefit of both.
**Current behaviour**:
Multiple clicks in a small time frame are using more than one potion, only then proccing the cooldown, being easily abused in multiple situations.
**Expected behaviour**: 
You should only be able to use one potion per cooldown.
**Server Revision**:

**Comment by Jezofine** [comment]
Can use multiple potions in macro /use.

**Comment by Wolffenstein** [comment]
Can you post the macro? Or is it just 3x /use Mana Potion?

**Comment by Jezofine** [comment]
Yes, simple:
```
/use Mana Potion
/use Mana Potion
/use Mana Potion
```
Rinse and repeat.

**Comment by Evolvee** [comment]
isnt

**Comment by Manaci** [comment]
Fixed
