### ISSUE TITLE
[Core] Combat bug won't wear off.

### ISSUE THREAD

**Issue by Firroth** [Atlantiss/NetherwingBugtracker#1169]
**Current behaviour**:
![screenshot_1](https://user-images.githubusercontent.com/43505196/46437219-261a2880-c75b-11e8-8bd7-6d4aea3dcaa8.png)

As seen on the screen combat won't wear off, even if mob is 100y away from me, and is spamming Cripple on me from this distance (unlimited range I guess this spell have or smth, since I went 200y away and still get crippled).

![screenshot_3](https://user-images.githubusercontent.com/43505196/46437382-84470b80-c75b-11e8-8eaa-33f313ae8561.png)

Recollection how it could occur:
I killed Xavanthras for quest, then started running away from mobs so I would not die and as seen on the screen this mob has 96% hp so I'm pretty sure 
![screenshot_2](https://user-images.githubusercontent.com/43505196/46437533-e43db200-c75b-11e8-865a-9f1be74dcbe4.png) must have procced and perhaps made him this way. So hard to tell if it's the item's fault, or the new update "with leashing" since he didn't unpull cause of dmg he received.

**Expected behaviour**: 
Combat should wear off, and mob should go back to his original place.

**Server Revision**: 
2124

**Comment by Easyfraggy** [comment]
Need recreation steps, otherwise cant fix.

**Comment by Firroth** [comment]
It's just like I wrote, all I did was start running to unpull mobs, since one of them is caster, he hit me with shadowbolt which triggered my waist item proc to hit him back for 100, which I guess "was the trigger" to break him (or it's because of recent update. I will try to break him again,

**Comment by Easyfraggy** [comment]
Yes but if you do it again, does it happen again?

**Comment by Firroth** [comment]
Can't recreate it again. 

Since it happened out of random and can't recreate it anymore and all works fine now, this issue can be dismissed until someone else encounters such a problem again.

**Comment by Mango-Ray** [comment]
> Yes but if you do it again, does it happen again?

Surely you can see the difficulty of testing this without gm controls?
