### ISSUE TITLE
Mob spawn inside horde camp

### ISSUE THREAD

**Issue by Erodraeda** [Atlantiss/NetherwingBugtracker#1170]
[//]: # (Enclose links to things related to the bug using http://wowhead.com or any other TBC database.)
[//]: # (You can use screenshot ingame to visual the issue.)
[//]: # (Write your tickets according to the format:)
[//]: # ([Quest][Azuremyst Isle] Red Snapper - Very Tasty!)
[//]: # ([NPC] Magistrix Erona)
[//]: # ([Spell][Mage] Fireball)
[//]: # ([Npc][Drop] Ghostclaw Lynx)
[//]: # ([Web] Armory doesnt work)

**Description**: 
Monster Rock Stalker (11739) spawning inside the horde camp in Silithus, and walking in and out of it.
**Current behaviour**:
![screenshot_526](https://user-images.githubusercontent.com/40346279/46439033-da08bd00-c735-11e8-8fff-600b46d3f444.png)
**Expected behaviour**: 
There should be no mob spawnpoints inside a NPC camp
**Server Revision**:

**Comment by aresbrutus** [comment]
Fixed in one of the upcoming updates.
