### ISSUE TITLE
[NPC] Dalaran Mage - Front of Ambermill Does Not Leash

### ISSUE THREAD

**Issue by Ceago** [Atlantiss/NetherwingBugtracker#1171]
**Description**:   Occasionally when pulling the Dalaran Mage patrolling the road in front of Ambermill he does not leash and I can run with him indefinitely without doing any additional damage.  I've been able to repeat this 3 times now if I start with frost nova.  The mobs beside him will go back as they should.   Video: https://streamable.com/kmewq

**Current behaviour**:  Will run all the way up to The Sepulcher before i get bored and kill him.

**Expected behaviour**:   Should leash back at a reasonable distance since no additional damage is being done.

**Server Revision**:  2124

**Comment by The14me** [comment]
rev 3441. Cant reproduce anymore (fixed)
Can be closed.
