### ISSUE TITLE
[Object][Ashenvale] Satyrnaar Fel Wood

### ISSUE THREAD

**Issue by Sinyr** [Atlantiss/NetherwingBugtracker#1172]
[//]: # (Enclose links to things related to the bug using http://wowhead.com or any other TBC database.)
[//]: # (You can use screenshot ingame to visual the issue.)
[//]: # (Write your tickets according to the format:)
[//]: # ([Quest][Azuremyst Isle] Red Snapper - Very Tasty!)
[//]: # ([NPC] Magistrix Erona)
[//]: # ([Spell][Mage] Fireball)
[//]: # ([Npc][Drop] Ghostclaw Lynx)
[//]: # ([Web] Armory doesnt work)

**Description**: 
Part of quest A Shameful Waste.

**Current behaviour**:
When you loot this item, it stays visible and sparkling for another 30 seconds or so.

**Expected behaviour**: 
It should despawn immediately after you loot it.

**Server Revision**: 
2094

**Comment by Shanghi** [comment]
This should be fixed in revision 2152.
