### ISSUE TITLE
Bungle in the Jungle

### ISSUE THREAD

**Issue by Thorgrimme** [Atlantiss/NetherwingBugtracker#1173]
[//]: # https://classicdb.ch/?quest=4496
[//]: # (You can use screenshot ingame to visual the issue.)
[//]: # (Write your tickets according to the format:)
[//]: # ([Quest][Ungoro] Bungle in the Jungle
[//]: # ([NPC] Magistrix Erona)
[//]: # ([Spell][Mage] Fireball)
[//]: # ([Npc][Drop] Gorishi Scent Gland
[//]: # (https://classicdb.ch/?item=11837)

**Description**: The drop rate on this item is way to low, killed 20-30 of the mobs that should drop it, with 0 luck.

**Current behaviour**:

**Expected behaviour**: 

**Server Revision**:

**Comment by aresbrutus** [comment]
Fixed in one of the upcoming updates.
