### ISSUE TITLE
Lord Banehollow

### ISSUE THREAD

**Issue by Piledriversn** [Atlantiss/NetherwingBugtracker#1175]
![image](https://user-images.githubusercontent.com/43560552/46446386-a9c71b80-c741-11e8-97e5-51bfbfd944f9.png)

 ([Quest][Felwood] Lord Banehollow)
([NPC] Imp Minion)

**Description**: I get a potion to make me friendly to the denizens of Jaedenar. 

**Current behaviour**:The Imp Minions are still hostile to me and will attack.

**Expected behaviour**: All NPC's are friendly to me in Jaedenar.

**Server Revision**:

**Comment by Evolvee** [comment]
rev 439kcolb

**Comment by Tjemu** [comment]
I found another npc that doesn't take effect from the quest item. Npc name is Rakaiah
![jaedanar bug](https://user-images.githubusercontent.com/1528617/50520640-2b70e000-0aca-11e9-84b7-2d706be91902.png)

**Comment by Evolvee** [comment]
rev 2531
