### ISSUE TITLE
[Warrior][Talent] Blood Frenzy

### ISSUE THREAD

**Issue by manslaughter** [Atlantiss/NetherwingBugtracker#1177]
**Description**: Talent in the Warrior Arms talent tree.

**Current behaviour**: Blood Frenzy is applied when Rend or Deep Wounds is applied to the target as expected, but if a target has > 12 sec of rend left and Deep Wounds is applied, the Blood Frenzy debuff will expire at the same time as Deep Wounds.

**Expected behaviour**: Blood Frenzy will remain on the target until both Rend and Deep Wounds have expired.

**Server Revision**: 2124

**Comment by Wolffenstein** [comment]
Fixed in rev 2443.
