### ISSUE TITLE
Hunter pet doesn't teleport with hunter when entering/leaving Darnassus

### ISSUE THREAD

**Issue by Notmittz** [Atlantiss/NetherwingBugtracker#1178]
**Description**: 
When teleporting from Rut'theran Village to Darnassus, or leaving from Darnassus to Rut'theran Village, the hunter's pet doesn't teleport with the hunter.  Using call pet gives an error of "You already control a summoned creature".

I can force the pet to teleport through the door using the ability "Eyes of the Beast" [ID 1002], which forces the pet to spawn at the door and run to the hunter immediately.

**Current behaviour**:
Pet doesn't teleport with hunter when entering or leaving Darnassus

**Expected behaviour**: 
Teleport with the hunter

**Server Revision**: 
[2124]

**Comment by Wolffenstein** [comment]
Fixed in rev 2194.
