### ISSUE TITLE
[loot][belf areas][database} No cloth drops

### ISSUE THREAD

**Issue by knasen88** [Atlantiss/NetherwingBugtracker#118]
**Description**: 
I leveled to 14 tonight and along the way i looted a total of 0 linen/wool cloth from humanoids/undeads along the way
**Current behaviour**:
0 cloth from mobs, nor did my mate i leveled with.
**Expected behaviour**: 
I expect some kind of cloth since both first aid and tailor is an option at even the first belf city?
**Server Revision**:

**Comment by DarthNekr0s** [comment]
yup can confirm, almost done with eversong woods and had no cloth drops from any mobs

**Comment by Easyfraggy** [comment]
Which area did you level in? I got plenty in Durotar/Barrens few days ago.

**Comment by wtRCH** [comment]
Blood Elves areas

**Comment by Kentamentiu** [comment]
This seems to be anything in Eversong Woods and Ghostlands.

**Comment by Wolffenstein** [comment]
Fixed in rev 2026.
