### ISSUE TITLE
[NPC][Movement]Silithid Ravager#4132 not patroling

### ISSUE THREAD

**Issue by Tenoutoften** [Atlantiss/NetherwingBugtracker#1180]
**Description**: 
[[NPC]Silithid Ravager#4132](https://db.excalibur.ws/?npc=4132) is a rare spawn in Thousand needles: 

**.gps & .npc info:**
![8ac85bf2acbf3aa1f53ad57d62101e6f](https://user-images.githubusercontent.com/34839199/46455608-1bd44a80-c7ac-11e8-8149-f292efa71018.png)

Currently he is just moving slightly on his spot, but indicated by [Wowhead comments](https://www.wowhead.com/npc=4132/krkkkx#comments) he should patrol around the pit and inside the cave. All comments are from wrath, but I think it is safe to say he patrolled the place prior to that.(Note; Npc name changed to Krkk'kx in 4.0.3 but kept the same NPDid#4132)
![987cea44b59956749985009fdde88e00](https://user-images.githubusercontent.com/34839199/46455927-4a9ef080-c7ad-11e8-9d5d-9236ba518c3b.png)
![bb4036ed49befe5e822a49344755b120](https://user-images.githubusercontent.com/34839199/46455930-4e327780-c7ad-11e8-85ec-3769ca9deb29.png)
![c16bcd9bba814e142a3ecc71c2f7ad28](https://user-images.githubusercontent.com/34839199/46455931-4e327780-c7ad-11e8-897a-b26eacc98f74.png)

Pictures of him inside the cave:
![55481-krkkkx](https://user-images.githubusercontent.com/34839199/46455937-5a1e3980-c7ad-11e8-960b-55b855c957b5.jpg)
![81692-krkkkx](https://user-images.githubusercontent.com/34839199/46455938-5ab6d000-c7ad-11e8-85a4-1bdf4e5444b8.jpg)

**Current behaviour**:
Just wobbles a bit around the spot I gave .gps of.

**Expected behaviour**: 
Expected to patrol the entire place.

**Server Revision**: 
2124

**Comment by aresbrutus** [comment]
I added 2 more possible spawn points inside, 1 of which where he patrols.
