### ISSUE TITLE
[Core Mechanic][Movement] Mobs walking in the air entering/leaving Thousand Needles cave

### ISSUE THREAD

**Issue by Tenoutoften** [Atlantiss/NetherwingBugtracker#1181]
**Description**: 
![c16bcd9bba814e142a3ecc71c2f7ad28](https://user-images.githubusercontent.com/34839199/46456828-812a3a80-c7b0-11e8-89ae-aa2651d75373.png)
[Video here](https://youtu.be/COnVqhvMLCg)

**Current behaviour**:
For a brief 1-2 seconds the mobs will jump into the air ~5-8 yards transitioning back and fourth between the outside and inside of the cave.

**Expected behaviour**: 
Expected to not jump into the air.

**Server Revision**: 
2124

**Comment by Tereneckla** [comment]
fixed
