### ISSUE TITLE
[NPC]Silithid Invader#4131 should not spawn outside of the cave

### ISSUE THREAD

**Issue by Tenoutoften** [Atlantiss/NetherwingBugtracker#1182]
**Description**: 
[[NPC]Silithid Invader#4131](https://db.excalibur.ws/?npc=4131) shouldn't spawn outside of the cave with the exception of the two potential spawns just outside. Note that these should only share spawn spot with [[NPC]Silithid Hive Drone#4133](https://db.excalibur.ws/?npc=4133) inside of the cave, as indicated by wowhead comments:
![5f66b83bc30b77129f3da3539b446afc](https://user-images.githubusercontent.com/34839199/46457211-d0249f80-c7b1-11e8-9205-8addee37a68c.png)
![a39aa86e391c29da3726f507380cdfe2](https://user-images.githubusercontent.com/34839199/46457272-09f5a600-c7b2-11e8-991f-7041e9c56b4f.png)

I think some spots might currently be [[NPC]Silithid Invader#4131](https://db.excalibur.ws/?npc=4131) spawn spots only, the specific one I mentioned here I killed 4 times in a row before I left.

**Current behaviour**:
At least one [[NPC]Silithid Invader#4131](https://db.excalibur.ws/?npc=4131) got the possibility of spawning outside.

![72dcdd237cc097f1aca0c46f60be61dd](https://user-images.githubusercontent.com/34839199/46457117-850a8c80-c7b1-11e8-94bd-23cf444feae9.png)
![54a4342ed7c472d8c313e722f09e69b9](https://user-images.githubusercontent.com/34839199/46457120-86d45000-c7b1-11e8-9487-65411510c394.jpg)

**Expected behaviour**: 

**Server Revision**:

**Comment by Shanghi** [comment]
This should be fixed in revision 2152.
