### ISSUE TITLE
[NPC] Lashtail Raptor disarms and knocks you down during stun

### ISSUE THREAD

**Issue by Mikik3jr** [Atlantiss/NetherwingBugtracker#1183]
[//]: # (Enclose links to things related to the bug using http://wowhead.com or any other TBC database.)
[//]: # (You can use screenshot ingame to visual the issue.)
[//]: # (Write your tickets according to the format:)
[//]: # ([Quest][Azuremyst Isle] Red Snapper - Very Tasty!)
[//]: # ([NPC] Magistrix Erona)
[//]: # ([Spell][Mage] Fireball)
[//]: # ([Npc][Drop] Ghostclaw Lynx)
[//]: # ([Web] Armory doesnt work)

**Description**: 
In Stranglethorn Vale there are raptors Called Lashtail Raptor. They knock you down and disarm you time to time.
**Current behaviour**:
I stunned the raptor and after that the raptor knocked me down. The stun didn't happen the same time as the raptor knockdown.
ID:
![wowscrnshot_100418_095316](https://user-images.githubusercontent.com/43505031/46460332-e2a3d680-c7bb-11e8-8151-eadb92efad1c.jpg)
Combat log:
![wowscrnshot_100418_095417](https://user-images.githubusercontent.com/43505031/46460340-ea637b00-c7bb-11e8-9908-e5a60a4c7d65.jpg)
(As you can see I stunned, then I hit the raptor and AFTER that I got the stun)
**Expected behaviour**: 
Enemies under stun should not use their abilities
**Server Revision**: 
2124

**Comment by Evolvee** [comment]
rev Xd
