### ISSUE TITLE
[Item]Hollow Vulture Bone#5848 to low drop rate for [Quest]Load Lightening#1176

### ISSUE THREAD

**Issue by Tenoutoften** [Atlantiss/NetherwingBugtracker#1184]
**Description**: 
[[Item]Hollow Vulture Bone#5848](https://www.wowhead.com/item=5848/hollow-vulture-bone) dropped by [[NPC]Salt Flat Scavenger#4154](https://db.excalibur.ws/?npc=4154) and [[NPC]Salt Flats Vulture#4158](https://db.excalibur.ws/?npc=4158) for [[Quest]Load Lightening#1176](https://www.wowhead.com/quest=1176/load-lightening) should have a 100% drop chance indicated by several wowhead comments [here](https://www.wowhead.com/quest=1176/load-lightening) and [here](https://www.wowhead.com/item=5848/hollow-vulture-bone):
![1cd256964232d0e70369bb12a6145509](https://user-images.githubusercontent.com/34839199/46460894-98bbf000-c7bd-11e8-846c-95b761eaf82b.png)
![2d491ef0488f6ca8cd50b240935b9f76](https://user-images.githubusercontent.com/34839199/46460895-99548680-c7bd-11e8-9b8c-949a168299bb.png)
![7c242c308a1d9f0f9c9eb4013fe962ab](https://user-images.githubusercontent.com/34839199/46460896-99548680-c7bd-11e8-833f-7da06b159376.png)
![97b819c15d643cdef02c86de6540686c](https://user-images.githubusercontent.com/34839199/46460897-99548680-c7bd-11e8-8554-9ccb3342195d.png)
![12611d0fb901b9072462f561d89c3743](https://user-images.githubusercontent.com/34839199/46460899-99548680-c7bd-11e8-818f-2dd948ce50d1.png)
![82965097b17b7cb178e6751142cab35e](https://user-images.githubusercontent.com/34839199/46460900-99548680-c7bd-11e8-8ac7-d439cb5d4b3e.png)

I found one comment saying it is not 100%, but chances are he just screwed something up since 6 people confirm it is 100%.
![fucked up](https://user-images.githubusercontent.com/34839199/46460938-b38e6480-c7bd-11e8-8d1c-601eac0adf8a.png)

**Current behaviour**:
Doesn't drop 100%

**Expected behaviour**: 
Expected 100%.

**Server Revision**: 
2124

**Comment by aresbrutus** [comment]
Fixed in one of the upcoming updates.
