### ISSUE TITLE
Swimming while mounted

### ISSUE THREAD

**Issue by kkumbaya** [Atlantiss/NetherwingBugtracker#1186]
[//]: # (Enclose links to things related to the bug using http://wowhead.com or any other TBC database.)
[//]: # (You can use screenshot ingame to visual the issue.)
[//]: # (Write your tickets according to the format:)
[//]: # ([Quest][Azuremyst Isle] Red Snapper - Very Tasty!)
[//]: # ([NPC] Magistrix Erona)
[//]: # ([Spell][Mage] Fireball)
[//]: # ([Npc][Drop] Ghostclaw Lynx)
[//]: # ([Web] Armory doesnt work)

**Description**: Swimming while mounted

**Current behaviour**: when pushing against the bottom it will not dismount you

**Expected behaviour**: gets dismounted

**Server Revision**: 2124

![wowscrnshot_100418_213722](https://user-images.githubusercontent.com/40691510/46462739-b5d4db00-c81e-11e8-8e0a-73ef420ab75c.jpg)
![wowscrnshot_100418_214214](https://user-images.githubusercontent.com/40691510/46462745-b79e9e80-c81e-11e8-980a-ef3322c60ed2.jpg)

**Comment by Tenoutoften** [comment]
![85a29037ff04e5c850d92fcc27f5f64f](https://user-images.githubusercontent.com/34839199/46473901-d763a180-c7e1-11e8-8ba6-304acfb09b1f.png)
Once you have the mount under water you dont have to hug the bottom, can also jump around but your speed is very slow^^

**Comment by Brasso** [comment]
How to reproduce: https://i.imgur.com/AHV1SdJ.gifv

**Comment by Tereneckla** [comment]
fixed
