### ISSUE TITLE
[NPC][Hunter]Stable Masters

### ISSUE THREAD

**Issue by DeltaLoads** [Atlantiss/NetherwingBugtracker#1187]
[//]: # (Enclose links to things related to the bug using http://wowhead.com or any other TBC database.)
[//]: # (You can use screenshot ingame to visual the issue.)
[//]: # (Write your tickets according to the format:)
[//]: # ([Quest][Azuremyst Isle] Red Snapper - Very Tasty!)
[//]: # ([NPC] Magistrix Erona)
[//]: # ([Spell][Mage] Fireball)
[//]: # ([Npc][Drop] Ghostclaw Lynx)
[//]: # ([Web] Armory doesnt work)

**Description**: 
Stable masters dont display your current pet unless you have it with you, so if you talk to them while you are on a mount or you simply dismiss your pet it will appear as if you have no pet at all.
With pet summoned:
![wowscrnshot_100418_104405](https://user-images.githubusercontent.com/43690147/46462962-16362f00-c7c3-11e8-97c2-d9df8f3cbe1d.jpg)
Without pet summoned:
![wowscrnshot_100418_104418](https://user-images.githubusercontent.com/43690147/46462979-1fbf9700-c7c3-11e8-8906-f58377724108.jpg)

**Current behaviour**:
Stable masters dont display your pet under Current Pet if its not summoned
**Expected behaviour**: 
Stable masters should always display your current pet even if its not summoned
**Server Revision**: 
2124

**Comment by Godmatik** [comment]
Guess it was fixed at some point, shows it just fine for me.

Closing
