### ISSUE TITLE
[NPC][Desolace] Hatefury Betrayer

### ISSUE THREAD

**Issue by Sinyr** [Atlantiss/NetherwingBugtracker#1188]
[//]: # (Enclose links to things related to the bug using http://wowhead.com or any other TBC database.)
[//]: # (You can use screenshot ingame to visual the issue.)
[//]: # (Write your tickets according to the format:)
[//]: # ([Quest][Azuremyst Isle] Red Snapper - Very Tasty!)
[//]: # ([NPC] Magistrix Erona)
[//]: # ([Spell][Mage] Fireball)
[//]: # ([Npc][Drop] Ghostclaw Lynx)
[//]: # ([Web] Armory doesnt work)

**Description**:
https://db.excalibur.ws/?npc=4673

**Current behaviour**:
When you pull a monster linked to Hatefury Betrayer from range, but he is a bit farther away, he targets you but just stands there and does nothing, and then resets after a few seconds.

**Expected behaviour**: 
He should walk forward a bit and then start shooting you.

**Server Revision**: 
2124

**Comment by Easyfraggy** [comment]
Please use .npc info and type entry+id so we know which specific mob you were trying this on.

**Comment by Sinyr** [comment]
Alright, but it works on every Betrayer, tried on 3 different ones.

**Comment by Tereneckla** [comment]
Fixed
