### ISSUE TITLE
[Quest] Fresh Meat

### ISSUE THREAD

**Issue by kkumbaya** [Atlantiss/NetherwingBugtracker#1189]
[//]: # (Enclose links to things related to the bug using http://wowhead.com or any other TBC database.)
[//]: # (You can use screenshot ingame to visual the issue.)
[//]: # (Write your tickets according to the format:)
[//]: # ([Quest][Azuremyst Isle] Red Snapper - Very Tasty!)
[//]: # ([NPC] Magistrix Erona)
[//]: # ([Spell][Mage] Fireball)
[//]: # ([Npc][Drop] Ghostclaw Lynx)
[//]: # ([Web] Armory doesnt work)

Really low drop rate of Monstrous Crawler Legs. Should be around 80% according to classic.db

**Server Revision**: 2124

**Comment by aresbrutus** [comment]
The drop rates are correct. The source you provided shows stock values which are wrong.
