### ISSUE TITLE
[Quest][Orgrimmar] Children's Week

### ISSUE THREAD

**Issue by Thugli** [Atlantiss/NetherwingBugtracker#119]
[//]: # ([NPC] Orcish Orphan)

**Description**: 
Orcish orphan has a permanent yellow question mark above his head.
https://imgur.com/a/QUohVsm
**Current behaviour**:
The quest's summary is to "Use the orcish orphan whistle to talk with the child you will be looking after during children's week" Upon summoning the orcish orphan by using the provided orcish orphan whistle, the orphan has a permanent yellow question mark above his head, implying there is a  quest to turn in, despite the fact that talking to the orphan is not part of any quest, and when you talk to the orphan there is no quest related dialogue, just the normal orphan dialogue that changes every time you right click on them.
**Expected behaviour**: 
Once summoned, the orcish orphan should not have a yellow question mark above its head
**Server Revision**:

**Comment by BamboozleNW** [comment]
Not there anymore, Can be closed.
