### ISSUE TITLE
[Spell][Paladin] Judgement

### ISSUE THREAD

**Issue by BeyondNoMore** [Atlantiss/NetherwingBugtracker#1191]
**Description**: 
Sometimes Judgment effect won't take place (i.e. one would cast judgement, the seal would fade away, but there wouldn't be any damage).
**Current behaviour**:
![wowscrnshot_100418_112639](https://user-images.githubusercontent.com/43840468/46468099-3b816800-c7d8-11e8-8887-4dfc917dd0af.jpg)
![wowscrnshot_100418_113613](https://user-images.githubusercontent.com/43840468/46468116-44723980-c7d8-11e8-88c7-e331b56c312d.jpg)
![wowscrnshot_100418_124043](https://user-images.githubusercontent.com/43840468/46468134-4b994780-c7d8-11e8-9f26-c831262556e5.jpg)
![wowscrnshot_100418_130216](https://user-images.githubusercontent.com/43840468/46468144-53f18280-c7d8-11e8-81ad-5242eafe14a6.jpg)

**Expected behaviour**: 
It should either hit or miss. There should some information about what happened to the judgement.
**Server Revision**:

**Comment by Mikik3jr** [comment]
Yeah same happens to me as well. I always forget to make screenshoot about combat log after that. >.>

**Comment by networm555** [comment]
encountered few times too lvl 9

**Comment by aakyed** [comment]
Can you PLEASE fix it. This is a HUGE DEAL for paladin.
