### ISSUE TITLE
[NPC]Naias#17207 shouldn't use [Spell]Water Bolt

### ISSUE THREAD

**Issue by Tenoutoften** [Atlantiss/NetherwingBugtracker#1193]
**Description**: 
[[NPC]Naias#17207](https://www.wowhead.com/npc=17207/naias#abilities) spawned by [[Item]Gift of Naias#23680](https://www.wowhead.com/item=23680/gift-of-naias) uses [[Spell]Water Bolt](https://db.excalibur.ws/?search=water+bolt), Not sure exactly which spell ID he uses but it deals ~ 371-450 which is very high for a level 37 mob. He also casts [[Spell]Water Shield#34828](https://db.excalibur.ws/?spell=34828) might be wrong ID, full list [here](https://db.excalibur.ws/?search=water+shield#spells).

According to two [wowhead comments](https://www.wowhead.com/npc=17207/naias#comments) he shouldn't cast any spells.

![813287b9027f007e05ea5df766db8123](https://user-images.githubusercontent.com/34839199/46472492-a4b7aa00-c7dd-11e8-8e55-60857095dadd.png)
![b733143f335481dc2a334a6d05586cad](https://user-images.githubusercontent.com/34839199/46472493-a4b7aa00-c7dd-11e8-86e7-3eee8144980a.png)

Both spells listed on [wowhead  currently](https://www.wowhead.com/npc=17207/naias#abilities) looks to be much newer spells [[Spell]Splash#78542](https://www.wowhead.com/spell=78542/splash) & [[Spell]Wave Crash#78799](https://www.wowhead.com/spell=78799/wave-crash), plus they got knock back effects which would have been reported.

Video of how [[NPC]Naias#17207](https://www.wowhead.com/npc=17207/naias#abilities) behaves currently on Netherwing [here](https://www.youtube.com/watch?v=GOsR8qldqjI&feature=youtu.be)

.gps & .npc info here:
![8dac8bb3954cc867e464f051b1eb2740](https://user-images.githubusercontent.com/34839199/46472607-0aa43180-c7de-11e8-8dd9-1d51588503e6.png)

**Expected behaviour**: 
Expected to not use [[Spell]Water Bolt](https://db.excalibur.ws/?search=water+bolt)

**Server Revision**: 
2124

**Comment by The14me** [comment]
Confirm,not suppose to have any spell's.

**Comment by Tenoutoften** [comment]
Thanks dad

**Comment by Evolvee** [comment]
removed all spells in rev Xd
