### ISSUE TITLE
[NPC]Naias#17207 doesn't despawn after summoned.

### ISSUE THREAD

**Issue by Tenoutoften** [Atlantiss/NetherwingBugtracker#1194]
**Description**: 
[[NPC]Naias#17207](https://www.wowhead.com/npc=17207/naias#abilities) spawned by [[Item]Gift of Naias#23680](https://www.wowhead.com/item=23680/gift-of-naias) doesn't appear to be despawning.

![8dac8bb3954cc867e464f051b1eb2740](https://user-images.githubusercontent.com/34839199/46472964-0fb5b080-c7df-11e8-85d3-cfec9d9cbf50.png)

**Current behaviour**:
You can summon [NPC]Naias#17207](https://www.wowhead.com/npc=17207/naias#abilities) and leave him up.

**Expected behaviour**: 
Expected to despawn after a reasonable amount of time.

**Server Revision**: 
2124

**Comment by Evolvee** [comment]
rev Xd
