### ISSUE TITLE
[Core] Loot roll window stays on the screen after expiring

### ISSUE THREAD

**Issue by Sinyr** [Atlantiss/NetherwingBugtracker#1195]
[//]: # (Enclose links to things related to the bug using http://wowhead.com or any other TBC database.)
[//]: # (You can use screenshot ingame to visual the issue.)
[//]: # (Write your tickets according to the format:)
[//]: # ([Quest][Azuremyst Isle] Red Snapper - Very Tasty!)
[//]: # ([NPC] Magistrix Erona)
[//]: # ([Spell][Mage] Fireball)
[//]: # ([Npc][Drop] Ghostclaw Lynx)
[//]: # ([Web] Armory doesnt work)

**Description**: 
![screenshot_21](https://user-images.githubusercontent.com/9539181/46473391-47712800-c7e0-11e8-9c34-13f61802a6e7.png)

**Current behaviour**:
If you let the loot roll timer expire, the loot is distributed but the loot roll window stays on the screen until you close it manually, or click any of the buttons. We tested this multiple times.

**Expected behaviour**: 
Loot roll window should disappear when the loot roll timer expires.

**Server Revision**: 
2124

**Comment by Manaci** [comment]
Fixed
