### ISSUE TITLE
[Item]Encrusted Tail Fin#5796 should have 100% drop rate

### ISSUE THREAD

**Issue by Tenoutoften** [Atlantiss/NetherwingBugtracker#1196]
**Description**: 
[[Item]Encrusted Tail Fin#5796](https://www.wowhead.com/item=5796/encrusted-tail-fin) should have a 100% drop chance from(for [[Quest]Encrusted Tail Fins#1107](https://db.excalibur.ws/?quest=1107):

* [[NPC]Saltscale Warrior#871(https://db.excalibur.ws/?npc=871)
* [[NPC]Saltscale Oracle#873(https://db.excalibur.ws/?npc=873)
* [[NPC]Saltscale Tide Lord#875(https://db.excalibur.ws/?npc=875)
* [[NPC]Saltscale Forager#877(https://db.excalibur.ws/?npc=877)
* [[NPC]Saltscale Hunter#879(https://db.excalibur.ws/?npc=879)

Indicated by several [wowhead comments](https://www.wowhead.com/quest=1107/encrusted-tail-fins)
![43fa61fb4412baaa1cdf1d6a8ef4ea46](https://user-images.githubusercontent.com/34839199/46475031-b18bcc00-c7e4-11e8-9963-3a1c412601a9.png)
![492d890e3dd29bc3fff6a0465dfa55bf](https://user-images.githubusercontent.com/34839199/46475032-b18bcc00-c7e4-11e8-9fcf-c4797e3ffaa7.png)
![ab78ebd646a00ea6285d8bbb6d0bff0a](https://user-images.githubusercontent.com/34839199/46475033-b18bcc00-c7e4-11e8-9e46-b12541f1864f.png)
![7ef0678a27a0aa6a04deab8d4b75e542](https://user-images.githubusercontent.com/34839199/46475041-b5b7e980-c7e4-11e8-9f70-872661834c77.png)
![18c486c39a6109296c4bff66ac3687e4](https://user-images.githubusercontent.com/34839199/46475042-b5b7e980-c7e4-11e8-9a7b-e9fe2ec5822f.png)
![25fc0f8485503739cb1718232856e55e](https://user-images.githubusercontent.com/34839199/46475043-b5b7e980-c7e4-11e8-834c-ea59238c2476.png)

Currently doesn't always drop:
![33f530b1aa019a2dac26de07020a1d71](https://user-images.githubusercontent.com/34839199/46475052-bd778e00-c7e4-11e8-9726-7366c202487a.png)

**Expected behaviour**: 
Expected to always drop.

**Server Revision**: 
2124

**Comment by aresbrutus** [comment]
Upped them to 100% + removed Murkgill from dropping these.
