### ISSUE TITLE
[Movement][Core Mechanic] MMAP error in a specific underwater spot

### ISSUE THREAD

**Issue by Tenoutoften** [Atlantiss/NetherwingBugtracker#1197]
**Description**: 
A few murlocs I encountered around The Vile Reef had some bizarre pathing under water, .gps & .npc info in the videos:
[Video 1](https://www.youtube.com/watch?v=mOemcA_ASVY&feature=youtu.be)
[Video 2](https://www.youtube.com/watch?v=MSwYW7bPbW4&feature=youtu.be)

Some of the NPC also broke around these ruins here:

![3583519b18da13562d1731bc740a3863](https://user-images.githubusercontent.com/34839199/46476265-ffee9a00-c7e7-11e8-836c-8cd1fde3b685.png)

**Current behaviour**:
Seem to move around as if they are in a cave to get to the second level as the player swims higher when there are nearby rocks.

**Expected behaviour**: 
Expected to swim directly towards the player

**Server Revision**: 
2124

**Comment by Tenoutoften** [comment]
Looks similar to me

**Comment by Evolvee** [comment]
5801.520020 822.369202 -7.426865
2185 13

**Comment by Wolffenstein** [comment]
Fixed.
