### ISSUE TITLE
[NPC] [Spell] Moving causes Decayed Strength to not cast.

### ISSUE THREAD

**Issue by Zuntrix** [Atlantiss/NetherwingBugtracker#1198]
[//]: # (Enclose links to things related to the bug using http://wowhead.com or any other TBC database.)
[//]: # (You can use screenshot ingame to visual the issue.)
[//]: # (Write your tickets according to the format:)
[//]: # ([Quest][Azuremyst Isle] Red Snapper - Very Tasty!)
[//]: # ([NPC] Magistrix Erona)
[//]: # ([Spell][Mage] Fireball)
[//]: # ([Npc][Drop] Ghostclaw Lynx)
[//]: # ([Web] Armory doesnt work)

**Description**: 
Moving causes Decayed Strength spell from Leper Gnomes to not go off on you.

**Current behaviour**:
https://i.imgur.com/G0BF1Hd.gifv

When moving while an enemy Leper Gnome is casting Decayed Strength, they will finish their cast but it will not go off.
It is reproducible, and happens with all the leper gnomes in the area. If you stand still, the spell will go off normally and you will be hit.

**Expected behaviour**: 
Finish the cast and the spell goes off on you. Or stop casting if out of range.
(No proof, I am just assuming the spell doesn't have 5 feet range)

**Server Revision**: 
Server is down so i can't check server revision :pepehands: 
mob info is Entry: 1211, SpawnId - (Entry: 1211, id 29) GUIDlow 3921.

**Comment by Wolffenstein** [comment]
SpellRange: (Id 2) "Combat Range":
    MinRange = 0
    MaxRange = 5

Seems to be correct
