### ISSUE TITLE
Needs to be rolled on

### ISSUE THREAD

**Issue by AlteredAli** [Atlantiss/NetherwingBugtracker#12]
[//]: # (Enclose links to things related to the bug using http://wowhead.com or any other TBC database.)
[//]: # (You can use screenshot ingame to visual the issue.)
[//]: # (Write your tickets according to the format:)
[//]: # ([Quest][Azuremyst Isle] Red Snapper - Very Tasty!)
[//]: # ([NPC] Magistrix Erona)
[//]: # ([Spell][Mage] Fireball)
[//]: # ([Npc][Drop] Ghostclaw Lynx)
[//]: # ([Web] Armory doesnt work)

**Description**: 
While in a group, if the loot is not yours, and you try to loot it, it says "needs to be rolled on"
**Current behaviour**:

**Expected behaviour**: 

**Server Revision**:

**Comment by Sinyr** [comment]
This mostly happens when you're both on a loot quest. When looting the quest items you can also see all other items even if the loot is not yours. 

Strangely, it also happened after we completed and turned in a quest ("What Must be Done..." - the one with Mutated Root Lashers). Killing a Lasher allowed me to open the loot window even though loot wasn't mine.

**Comment by EosWoW** [comment]
Also had this issue, but I couldn't loot shovel or linen in the mines, so it was affecting other items not just quest items.

**Comment by aresbrutus** [comment]
https://github.com/Atlantiss/AtlantissTBCBT/issues/4253

**Comment by Tenoutoften** [comment]
https://github.com/Atlantiss/NetherwingBugtracker/issues/3145
https://github.com/Atlantiss/NetherwingBugtracker/issues/3155

**Comment by RandomGuyFromDiscordServer** [comment]
Still happens on revision 2603

**Comment by RandomGuyFromDiscordServer** [comment]
@aresbrutus

**Comment by The14me** [comment]
Work just fine in Rev. 3441
If the loot is not for you,u don't ever see it in the ''corps'' .Tested with 2 chars.
Can be closed.
