### ISSUE TITLE
Bael'dun Digger marked as pvp

### ISSUE THREAD

**Issue by Shakeandbake** [Atlantiss/NetherwingBugtracker#120]
[//]: # (Enclose links to things related to the bug using http://wowhead.com or any other TBC database.)
[//]: # (You can use screenshot ingame to visual the issue.)
[//]: # (Write your tickets according to the format:)
[//]: # ([Quest][Azuremyst Isle] Red Snapper - Very Tasty!)
[//]: # ([NPC] Magistrix Erona)
[//]: # ([Spell][Mage] Fireball)
[//]: # ([Npc][Drop] Ghostclaw Lynx)
[//]: # ([Web] Armory doesnt work)

**Description**: 
Bael'dun Digger in mulgore for quest Dwarven Digging are marked as humanoid pvp, and flag horde for pvp when attacked.
**Current behaviour**:

**Expected behaviour**: 
No pvp flagging.
**Server Revision**:

**Comment by Wolffenstein** [comment]
Fixed in rev 2026.
