### ISSUE TITLE
[hunter][talent][buff][rapid fire] sometimes rapid fire fades right after you get it when killing a mob.

### ISSUE THREAD

**Issue by queeb3** [Atlantiss/NetherwingBugtracker#1201]
[//]: # (Enclose links to things related to the bug using http://wowhead.com or any other TBC database.)
[//]: # (You can use screenshot ingame to visual the issue.)
[//]: # (Write your tickets according to the format:)
[//]: # ([Quest][Azuremyst Isle] Red Snapper - Very Tasty!)
[//]: # ([NPC] Magistrix Erona)
[//]: # ([Spell][Mage] Fireball)
[//]: # ([Npc][Drop] Ghostclaw Lynx)
[//]: # ([Web] Armory doesnt work)

**Description**: 
while i got rapid-fire rank 2 in marksmanship talent tree ive noticed that when i kill a mob there is the most common chance that after getting the rapid-fire buff that it will fade right as the death animation for the enemy stops
**Current behaviour**:
rapid fire fades as if it has been used on a dead enemy
**Expected behaviour**: 
rapid fire should stay when an enemy is killed and gives honor / exp and should not fade until 20 seconds have passed or you use the said attacks on a new enemy
**Server Revision**:

**Comment by Tenoutoften** [comment]
First off this is about the talent that is called [[Spell]Rapid Killing(Rank 2)#34949](https://db.excalibur.ws/?spell=34949), not to be confused with [[Spell]Rapid Fire#3045](https://db.excalibur.ws/?spell=3045) which is a cooldown all hunters have.

Secondly the aura this talent triggers is [[Rapid Killing#35099](https://db.excalibur.ws/?spell=35099) and it had a change on 2018 / 10 / 14 during the beta, which is after this bug report:
[Core/Hunter]: 
- Rapid Killing buff will no longer be removed after casting spells that are not affected by it
- Rapid Killing buff will now be properly reapplied when hunter's target dies from a spell which is affected by it

I've tested it and it is now in arguably a worse state(https://github.com/Atlantiss/NetherwingBugtracker/issues/1674) once you kill something granting experience, this aura now stays on for 20 seconds, as in you can fire as many auto shots, arcane shots or aimed shots and it will affect all of them within those 20 seconds.
