### ISSUE TITLE
[NPC][Burning Stepps] Scalding Drake in Pillar of Ash fly's below ground.

### ISSUE THREAD

**Issue by Firroth** [Atlantiss/NetherwingBugtracker#1203]
[NPC] [Scalding Drake](https://www.wowhead.com/npc=7045/scalding-drake

**Current behaviour**:
As you can see on the screen, he fly's half below the ground. I would have .gps, if he wasn't "patrolling".

![screenshot_4](https://user-images.githubusercontent.com/43505196/46488900-4c47d300-c804-11e8-9213-39965cf0e80b.png)

**Expected behaviour**: 
He should fly above the ground .

**Server Revision**: 
2124

Edit: seems like every Scalding Drake is like that.

**Comment by Evolvee** [comment]
rev Xd
