### ISSUE TITLE
[Quest]Panther Mastery#191 should give 1450xp instead of 1500xp

### ISSUE THREAD

**Issue by Tenoutoften** [Atlantiss/NetherwingBugtracker#1204]
**Description**: 
[[Quest]Panther Mastery#191](https://www.wowhead.com/quest=191/panther-stalking#comments)
 should give 1450xp instead of 1500xp indicated by [wowhead comments](https://www.wowhead.com/quest=191/panther-stalking#comments)

![39de1ea322d848a5e932761c01c13d87](https://user-images.githubusercontent.com/34839199/46490593-b9f5fe00-c808-11e8-8f72-eacbde48aa02.png)
![49b462ce5034d736450775f292fc7ecc](https://user-images.githubusercontent.com/34839199/46490594-b9f5fe00-c808-11e8-8e8f-6af414742cc6.png)

Current behavior: 
![065697fef4a56cc43e9496d0e4b36a22](https://user-images.githubusercontent.com/34839199/46490719-07726b00-c809-11e8-89f3-1a5969404bb8.png)

**Expected behaviour**: 
1450 xp instead of 1500xp

**Server Revision**: 
2124

**Comment by Evolvee** [comment]
The XP is calculated by core based on level difference between your character and the quest level... it doesnt grant static XP. We would have to know your level when you did the quest...
