### ISSUE TITLE
[Loot] Centipaar Insect Parts#8587 drop chance is too low.

### ISSUE THREAD

**Issue by Jezofine** [Atlantiss/NetherwingBugtracker#1205]
**Current behaviour**:
While farming [Centipaar Insect Parts](http://web.archive.org/web/20081016081231/http://thottbot.com:80/i8587) from all different centipaar mobs I got 5 items after 39 loots which roughly translates to 12.8% drop chance. This is worse than lowest values on thottbot.
And if calculate drop from total kills (64 in my case) it becomes a disaster (7.8%).

**Expected behaviour**:
Drop rate should be at least 35%-39% (with exception for tunneller).

**Server Revision**: 2124

**Comment by Firroth** [comment]
Isn't this related to #992? Maybe fix didn't go live yet, since I don't see it in changelog.

**Comment by Jezofine** [comment]
Well, my bad, didn't check quest name on tracker, only item name. But I think it's still too low.
