### ISSUE TITLE
[Quest]Tiger Mastery#186 should give 1450xp rather than 1500xp

### ISSUE THREAD

**Issue by Tenoutoften** [Atlantiss/NetherwingBugtracker#1206]
**Description**: 
[[Quest]Tiger Mastery#186](https://www.wowhead.com/quest=186/tiger-stalking#comments) should give 1450xp rather than 1500xp indicated by [wowhead comment](https://www.wowhead.com/quest=186/tiger-stalking#comments)
![065697fef4a56cc43e9496d0e4b36a22](https://user-images.githubusercontent.com/34839199/46490878-794ab480-c809-11e8-9bed-058bba6a35fd.png)

**Current behaviour**:
![3d81ec854eca5bee3427ec03f6c25e84](https://user-images.githubusercontent.com/34839199/46490896-7ea7ff00-c809-11e8-8a7b-a7866cf00084.png)

**Expected behaviour**: 
Should give 1450xp rather than 1500xp

**Server Revision**: 
2124

**Comment by Evolvee** [comment]
The XP is calculated by core based on level difference between your character and the quest level... it doesnt grant static XP. We would have to know your level when you did the quest...
