### ISSUE TITLE
[Quest]Investigate the camp#201 should give 270xp rather than 250xp

### ISSUE THREAD

**Issue by Tenoutoften** [Atlantiss/NetherwingBugtracker#1207]
**Description**: 
[[Quest]Investigate](https://www.wowhead.com/quest=201/investigate-the-camp) should reward 270xp rather than 250xp based on [wowhead comment](https://www.wowhead.com/quest=201/investigate-the-camp)
![c944ddb346420bfd374eeba6f372f277](https://user-images.githubusercontent.com/34839199/46491243-78665280-c80a-11e8-8763-85cc5e9d3876.png)

**Current behaviour**:
![5ad484018427a8f2d0661646d77e3b5b](https://user-images.githubusercontent.com/34839199/46491248-7ac8ac80-c80a-11e8-80b5-01bb5f076c00.png)

**Expected behaviour**: 
270xp

**Server Revision**: 
2124

**Comment by Evolvee** [comment]
The XP is calculated by core based on level difference between your character and the quest level... it doesnt grant static XP. We would have to know your level when you did the quest...
