### ISSUE TITLE
[Quest]The Rumormonger should give 1750xp rather than 1800xp

### ISSUE THREAD

**Issue by Tenoutoften** [Atlantiss/NetherwingBugtracker#1208]
**Description**: 
[[Quest]The Rumormonger#1115](https://www.wowhead.com/quest=1115/the-rumormonger) should reward 1750xp rather than 1800xp based on [wowhead comment](https://www.wowhead.com/quest=1115/the-rumormonger)
![041dc21e29098f36fcaae53d29ffa606](https://user-images.githubusercontent.com/34839199/46491405-f1fe4080-c80a-11e8-8a7a-ad78e46fe249.png)

**Current behaviour**:
![ae20d372d455f5f0a7573239df9d714a](https://user-images.githubusercontent.com/34839199/46491410-f4609a80-c80a-11e8-9988-b0c09c9daa51.png)

**Expected behaviour**: 
1750xp

**Server Revision**: 
2124

**Comment by Evolvee** [comment]
The XP is calculated by core based on level difference between your character and the quest level... it doesnt grant static XP. We would have to know your level when you did the quest...
