### ISSUE TITLE
[NPC] [Pathing] Firemane Scout

### ISSUE THREAD

**Issue by Kidcudi123** [Atlantiss/NetherwingBugtracker#1209]
Just one specific mob's pathing's weird

![image](https://user-images.githubusercontent.com/33790123/46491551-56b99b00-c80b-11e8-8322-4fbf34a216ee.png)

**Comment by aresbrutus** [comment]
Weird in what way?

**Comment by Kidcudi123** [comment]
It was going below the ground

**Comment by aresbrutus** [comment]
Moved his position a little bit in rev `Tycho`.
