### ISSUE TITLE
[Quest]Supply and Demand#575should reward 1250xp rather than 1300xp

### ISSUE THREAD

**Issue by Tenoutoften** [Atlantiss/NetherwingBugtracker#1210]
**Description**: 
[[Quest]Supply and Demand#575](https://www.wowhead.com/quest=575/supply-and-demand#comments) should reward 1250xp rather than 1300xp based on [wowhead comment](https://www.wowhead.com/quest=575/supply-and-demand#comments)
![62d9c5c83a904f5f46a320e5bcf9959b](https://user-images.githubusercontent.com/34839199/46491641-8ff20b00-c80b-11e8-8219-5942b1790fb5.png)

**Current behaviour**:
![d29b5637719d741fbda85637010678ee](https://user-images.githubusercontent.com/34839199/46491646-92ecfb80-c80b-11e8-8f0f-c9e47ced2657.png)

**Expected behaviour**: 
1250xp rather than 1300xp

**Server Revision**: 
2124

**Comment by Evolvee** [comment]
The XP is calculated by core based on level difference between your character and the quest level... it doesnt grant static XP. We would have to know your level when you did the quest...
