### ISSUE TITLE
Goblin Sponsorship#1181 should reward 370xp rather than 350xp

### ISSUE THREAD

**Issue by Tenoutoften** [Atlantiss/NetherwingBugtracker#1211]
**Description**: 
[[Quest]Goblin Sponsorship#1181](https://www.wowhead.com/quest=1181/goblin-sponsorship) should reward 370xp rather than 350xp based on [wowhead comment](https://www.wowhead.com/quest=1181/goblin-sponsorship)
![cbd55ae152b173e5833a5dff4c41a928](https://user-images.githubusercontent.com/34839199/46491933-6d142680-c80c-11e8-9af3-16ecdb0a596a.png)

**Current behaviour**:
![e2185183d897ffdaa4062007d6a00d8d](https://user-images.githubusercontent.com/34839199/46491936-6f768080-c80c-11e8-9157-859caa16da99.png)

**Expected behaviour**: 
370xp rather than 350xp

**Server Revision**: 
2124

**Comment by Evolvee** [comment]
The XP is calculated by core based on level difference between your character and the quest level... it doesnt grant static XP. We would have to know your level when you did the quest...
