### ISSUE TITLE
[Movement][Game Mechanic]Mobs under water fleeing away in fear will occasionally stand still

### ISSUE THREAD

**Issue by Tenoutoften** [Atlantiss/NetherwingBugtracker#1212]
**Description**: 
Mobs under water fleeing away in fear will occasionally stand still. I have reproduced this a few times, not sure what causes it. Video [here](https://www.youtube.com/watch?v=FyfhBvNAmK8)

**Expected behaviour**: 
Expected to not freeze but run away in fear

**Server Revision**: 
2124

**Comment by Wolffenstein** [comment]
Fixed.
