### ISSUE TITLE
[Quest][Ironforge/Un'goro Crater] A Little Slime Goes a Long Way

### ISSUE THREAD

**Issue by Firroth** [Atlantiss/NetherwingBugtracker#1213]
[Quest] [A Little Slime Goes a Long Way](https://www.wowhead.com/quest=4513/a-little-slime-goes-a-long-way)
[NPC] [Cloned Ooze](https://www.wowhead.com/npc=9477/cloned-ooze)
[Quest Item Required] [Empty Pure Sample Jar](https://www.wowhead.com/item=11953/empty-pure-sample-jar)

**Current behaviour**:
It works fine on original mobs, 1 [vial](https://www.wowhead.com/item=11953/empty-pure-sample-jar) - 1 use -> mob dissapears. Problem occurs when said mob uses "clone" ability and will spawn another slime "[Cloned Ooze](https://www.wowhead.com/npc=9477/cloned-ooze)" on which you can use all [vials](https://www.wowhead.com/item=11953/empty-pure-sample-jar) and it won't despawn like original ones, after 1 use of [vial](https://www.wowhead.com/item=11953/empty-pure-sample-jar).

![screenshot_5](https://user-images.githubusercontent.com/43505196/46496008-342d7f00-c817-11e8-8322-67c4a54ac5d0.png)

**Expected behaviour**: 
[Vials](https://www.wowhead.com/item=11953/empty-pure-sample-jar) shouldn't be usable on [Cloned Ooze](https://www.wowhead.com/npc=9477/cloned-ooze)

![screenshot_1](https://user-images.githubusercontent.com/43505196/46496179-ab631300-c817-11e8-8eb1-7baf0cd0f056.png)
![screenshot_2](https://user-images.githubusercontent.com/43505196/46496184-ae5e0380-c817-11e8-9ee8-89ad1bc35d72.png)

**Server Revision**: 
2124

**Comment by Labteth** [comment]
Current behavior:
Unable to use the vials on any slime or other mob in the area.

Expected behavior:
Able to use the appropriate vial on an ooze corpse listed in the quest once per corpse.

**Comment by zhuk90** [comment]
Felwood quest not working

**Comment by Godmatik** [comment]
Fixed already, looks like issue was just not closed but the others were
