### ISSUE TITLE
[NPC]Venture Co. Mechanic#1097 shouldn't use [Spell]Multi-shot#14443 against solo players

### ISSUE THREAD

**Issue by Tenoutoften** [Atlantiss/NetherwingBugtracker#1214]
**Description**: 
[[NPC]Venture Co. Mechanic#1097](https://db.excalibur.ws/?npc=1097#abilities) shouldn't use [[Spell]Multi-shot#14443](https://db.excalibur.ws/?spell=14443) against solo players according to [wowhead comment](https://www.wowhead.com/npc=1097/venture-co-mechanic#comments:id=591693)
![a5fe0a27e757de57c98edcf93296e54d](https://user-images.githubusercontent.com/34839199/46499242-d0f41a80-c81f-11e8-8b9d-965f5334d8f5.png)

I realize the comment is from Wrath, but I doubt anything changed with it. I tried searching for patch notes of this NPC and didn't find anything.

**Current behaviour**:
Uses [[Spell]Multi-shot#14443](https://db.excalibur.ws/?spell=14443) against solo players
![7147c3fa524d593c5bf4c770e8d1f665](https://user-images.githubusercontent.com/34839199/46499301-fbde6e80-c81f-11e8-8a4b-ba3a61b49f06.png)

**Expected behaviour**: 
Expected to not use [[Spell]Multi-shot#14443](https://db.excalibur.ws/?spell=14443) against solo players
 
**Server Revision**: 
2124

**Comment by The14me** [comment]
Can u find come proof from TBC please? : )

**Comment by Tenoutoften** [comment]
http://wowwiki.wikia.com/wiki/Patch_2.4.3
http://wowwiki.wikia.com/wiki/Patch_2.4.2_(undocumented_changes)
http://wowwiki.wikia.com/wiki/Patch_2.4.3
http://wowwiki.wikia.com/wiki/Patch_2.4.3_(undocumented_changes)
http://wowwiki.wikia.com/wiki/Patch_3.0.2
http://wowwiki.wikia.com/wiki/Patch_3.0.2_(undocumented_changes)
http://wowwiki.wikia.com/wiki/Patch_3.0.3
http://wowwiki.wikia.com/wiki/Patch_3.0.3_(undocumented_changes)
http://wowwiki.wikia.com/wiki/Patch_3.0.8_(undocumented_changes)
http://wowwiki.wikia.com/wiki/Patch_3.0.8

I'll go through these more thoroughly later on and see if I can find any proof of it being used on solo players

**Comment by Tenoutoften** [comment]
I think it looks better leaving this in vs solo players & I have no video evidence so I'll close this. If anyone finds anything you can just open another issue.
