### ISSUE TITLE
[Quest]Tiger Mastery#187 should give 2450xp rather than 2500xp

### ISSUE THREAD

**Issue by Tenoutoften** [Atlantiss/NetherwingBugtracker#1215]
**Description**: 
[[Quest]Tiger Mastery#187](https://www.wowhead.com/quest=187/tiger-prowess#comments) should give 2450xp rather than 2500xp based on wowhead comment.
![e11320af5cc3a91dda11d0df56cf820c](https://user-images.githubusercontent.com/34839199/46499775-444a5c00-c821-11e8-835d-08b4326a8d60.png)

**Current behaviour**:
![6a1d1e291d316375cb747d83eb5544ee](https://user-images.githubusercontent.com/34839199/46499770-3eed1180-c821-11e8-88e9-346ecc53e432.png)

**Expected behaviour**: 
2450xp rather than 2500xp

**Server Revision**: 
2124

**Comment by Evolvee** [comment]
The XP is calculated by core based on level difference between your character and the quest level... it doesnt grant static XP. We would have to know your level when you did the quest...
