### ISSUE TITLE
[Quest]Raptor Mastery#195 should give 1750xp rather than 1800xp

### ISSUE THREAD

**Issue by Tenoutoften** [Atlantiss/NetherwingBugtracker#1216]
**Description**: 
[[Quest]Raptor Mastery#195](https://www.wowhead.com/quest=195/raptor-stalking#comments) should give 1750xp rather than 1800xp based upon [wowhead comment](https://www.wowhead.com/quest=195/raptor-stalking#comments)
![461ffe6c0962bdc2d94d0eaefce8f1a8](https://user-images.githubusercontent.com/34839199/46499923-c5a1ee80-c821-11e8-88c8-323aba9f335d.png)

**Current behaviour**:
![be93863e3108c74105bf2548fceff7eb](https://user-images.githubusercontent.com/34839199/46499917-c175d100-c821-11e8-8134-42faedfeeadb.png)

**Expected behaviour**: 
1750xp rather than 1800xp

**Server Revision**: 
2124

**Comment by Evolvee** [comment]
The XP is calculated by core based on level difference between your character and the quest level... it doesnt grant static XP. We would have to know your level when you did the quest...
