### ISSUE TITLE
[NPC]Sin'dall#729 is suppose to patrol

### ISSUE THREAD

**Issue by Tenoutoften** [Atlantiss/NetherwingBugtracker#1217]
**Description**: 
[[NPC]Sin'dall#729](https://www.wowhead.com/npc=729/sindall#comments) is suppose to patrol according to [wowhead comment](https://www.wowhead.com/npc=729/sindall#comments:id=74738)
![f5d62b75cdc56ef01a93629e8398e4d1](https://user-images.githubusercontent.com/34839199/46500338-e3bc1e80-c822-11e8-893d-6c39acabe535.png)

**Current behaviour**:
Stands still on top of the hill at:
![8d40c6263eb54ffc29c4aa8f98180f1e](https://user-images.githubusercontent.com/34839199/46500331-de5ed400-c822-11e8-9013-939e8b0ee72b.png)

**Expected behaviour**: 
Expected to patrol like described by the comment

**Server Revision**: 
2124

**Comment by aresbrutus** [comment]
Seems he can spawn on top or below where he patrols, similar to other mobs I fixed in the past. So he will have 2 possible points, on top and 1 below where he patrols.
