### ISSUE TITLE
Illegible for The Crimson Courier

### ISSUE THREAD

**Issue by Tinnoan** [Atlantiss/NetherwingBugtracker#1219]
After handing in the quest [The Call to Command](https://www.wowhead.com/quest=14349/the-call-to-command) I'm unable to pick up the follow up quest [The Crimson Courier](https://www.wowhead.com/quest=6145/the-crimson-courier).

I've done all of the quests for Nathanos except Ramstein in Stratholme (not sure if this is a requirement, haven't been able to confirm or not if it is through comments or anything)

![varimathras](https://user-images.githubusercontent.com/25431721/46500624-8b395100-c823-11e8-857c-854c140cdfc0.PNG)

**Comment by Shanghi** [comment]
Ramstein will no longer be a requirement after revision 2175.
