### ISSUE TITLE
Ghostlands mob linking 

### ISSUE THREAD

**Issue by Young991** [Atlantiss/NetherwingBugtracker#122]
[//]: # ([Quest][Ghostlands] The Twin Ziggurats)
[//]: # ([NPC] 16318)

**Description**: 
Quest is damn near unduable because of mob linking.
**Current behaviour**:
All 4-5 mobs link at once
**Expected behaviour**:
Should only be 1-2 mobs at once.
**Server Revision**:

**Comment by Young991** [comment]
Mob ID is 16318 i forgot to add it.

**Comment by Easyfraggy** [comment]
Just to clarify, these are the mobs inside the ziggurats for the quest The Twin Ziggurats 9176.

Having 4 mobs linked seems a bit excessive for a solo quest.

**Comment by ttghnw** [comment]
I can confirm that the mobs are all aggroing on what should be a single pull in the twin ziggs

**Comment by Evolvee** [comment]
they arent linked but the center npc chain pulls for some reason and then he chain pulls the rest

**Comment by Easyfraggy** [comment]
Should maybe have lower chaining range for these mobs.

**Comment by Evolvee** [comment]
I can reduce only their aggro/threat distance, not the actual chain pull range i think, I will just make them either not being able to chain pull or not being able to be chain pulled

**Comment by Evolvee** [comment]
rev xdd
