### ISSUE TITLE
[Quest]Some Assembly Required#577 gives 1800xp rather than 1750xp

### ISSUE THREAD

**Issue by Tenoutoften** [Atlantiss/NetherwingBugtracker#1220]
**Description**: 
[[Quest]Some Assembly Required#577](https://www.wowhead.com/quest=577/some-assembly-required#comments) gives 1800xp rather than 1750xp.
![58cc502228815ce1ec60e7ea13b1ffb0](https://user-images.githubusercontent.com/34839199/46501074-b8d2ca00-c824-11e8-9c01-e32311f4cea3.png)

**Current behaviour**:
![46e18b59d9b09ac5591093e891082675](https://user-images.githubusercontent.com/34839199/46501072-b7a19d00-c824-11e8-8e4a-907213ed9bff.png)

**Expected behaviour**: 
Should give 1750xp rather than 1800xp

**Server Revision**: 
2124

**Comment by Evolvee** [comment]
The XP is calculated by core based on level difference between your character and the quest level... it doesnt grant static XP. We would have to know your level when you did the quest...
