### ISSUE TITLE
[NPC] Thistle Cub's in Darkshore are too high a level

### ISSUE THREAD

**Issue by Notmittz** [Atlantiss/NetherwingBugtracker#1221]
[NPC] Thistle Cub
Entry: 6789, SpawnID - (Entry: 6789, ID: 2), GUIDLow: 72452

**Description**: 
The Thistle Cub's, which surround the Den Mother, are too high a level.  Level's found in server are between 11 & 12.

Per the Wowhead comments, they are supposed to be between level 9 & 10.

https://www.wowhead.com/quest=2139/tharnariuns-hope#comments:id=3444
https://www.wowhead.com/quest=2139/tharnariuns-hope#comments:id=65502
https://www.wowhead.com/quest=2139/tharnariuns-hope#comments:id=206149

**Server Revision**: 
[2126]

**Comment by Evolvee** [comment]
rev Xd
