### ISSUE TITLE
[Quest]Goblin Sponsorship#1183 should give 925xp rather than 900xp

### ISSUE THREAD

**Issue by Tenoutoften** [Atlantiss/NetherwingBugtracker#1222]
**Description**: 
[[Quest]Goblin Sponsorship#1183](https://www.wowhead.com/quest=1183/goblin-sponsorship) should give 925xp rather than 900xp according to [wowhead comment](https://www.wowhead.com/quest=1183/goblin-sponsorship)
![a380583b1d44ecc0ecdf0f7153aa94db](https://user-images.githubusercontent.com/34839199/46501780-bbceba00-c826-11e8-8b61-3f1a4461e096.png)

**Current behaviour**:
![8bf0bfe9dcb3e286f64c220f44d8c5a5](https://user-images.githubusercontent.com/34839199/46501767-b2dde880-c826-11e8-92a5-c1b53dbe3530.png)

**Expected behaviour**: 
925xp rather than 900xp

**Server Revision**: 
2124

**Comment by Evolvee** [comment]
The XP is calculated by core based on level difference between your character and the quest level... it doesnt grant static XP. We would have to know your level when you did the quest...

**Comment by Tenoutoften** [comment]
All these quests were done while it displayed as yellow. Would quests yield more xp when they are orange? or the first level of them being yellow?

**Comment by Evolvee** [comment]
You would have to ask @Wolffenstein how its handled in core ^^

**Comment by Tenoutoften** [comment]
![e142d2b9b2a6578559169467fca7fbfe](https://user-images.githubusercontent.com/34839199/46570774-ff7e0c80-c969-11e8-9cd1-ad47ba426132.png)
I'll try to poke him on discord regarding this
