### ISSUE TITLE
Some abilities not granting combat while mob is attacking something else

### ISSUE THREAD

**Issue by David-Aycock** [Atlantiss/NetherwingBugtracker#1224]
[//]: # (Enclose links to things related to the bug using http://wowhead.com or any other TBC database.)
[//]: # (You can use screenshot ingame to visual the issue.)
[//]: # (Write your tickets according to the format:)
[//]: # ([Quest][Azuremyst Isle] Red Snapper - Very Tasty!)
[//]: # ([NPC] Magistrix Erona)
[//]: # ([Spell][Mage] Fireball)
[//]: # ([Npc][Drop] Ghostclaw Lynx)
[//]: # ([Web] Armory doesnt work)

**Description**: 
Specifically used Serpent's Sting as a level 15 Dwarf Hunter with a Wolf pet in Westfall against one of the Boars.  Reproduced the bug again a minute later.

[Starving Winter Wolf](https://classicdb.ch/?npc=1133)
[Serpent Sting](https://tbc-twinhead.twinstar.cz/?spell=36984) - Could not find correct version of ability.  This one seems to have invalid damage values.
[Boar](https://www.wowhead.com/npc=157/goretusk)

**Current behaviour**:
While the mob is attacking another player, casting Serpent's Sting (possibly other abilities, but did not have the chance to reproduce again, as there were no other nearby players) and putting your pet on follow briefly granted combat before removing it one second later.

**Expected behaviour**: 
When you engage with a mob, even one that is engaged with another player, you should have the full combat timer of 6 seconds assuming that the target does not immediately die.

**Server Revision**: 
[2126]

**Comment by kakeloff** [comment]
Found a very similar bug while in a party. The other party member engages a random NPC and does damage to it. I apply a shadow word: pain and gain combat for a couple of seconds before combat drops again (even after damage ticks). If I also apply Vampiric Embrace combat does not drop until NPC dies, as normal. Couldn't get a .gif small enough for github, but here's a youtube video of sw:p not keeping me in combat.

https://www.youtube.com/watch?v=34qb9kZNXPw&feature=youtu.be

**Comment by Godmatik** [comment]
Was fixed at some point, I am kept in combat if I put a DOT that something being attacked by someone else.

Can close
