### ISSUE TITLE
[NPC] Dalaran Protector

### ISSUE THREAD

**Issue by Norolia** [Atlantiss/NetherwingBugtracker#1225]
[//]: # (Enclose links to things related to the bug using http://wowhead.com or any other TBC database.)
[//]: # (You can use screenshot ingame to visual the issue.)
[//]: # (Write your tickets according to the format:)
[//]: # ([Quest][Azuremyst Isle] Red Snapper - Very Tasty!)
[//]: # ([NPC] Magistrix Erona)
[//]: # ([Spell][Mage] Fireball)
[//]: # ([Npc][Drop] Ghostclaw Lynx)
[//]: # ([Web] Armory doesnt work)

**Description**: 
Seems to be a problem with Dalaran Protectors around Ambermill in Silverpine Forest.  When they aggro they lock up the game. (possibly because of the serpent summon not working properly?) It's happened to me a few times now while running to close to one.
**Current behaviour**:
It locks up the game and when I log back in I am dead.
**Expected behaviour**: 
They should aggro and attack like any other mob without forcing a client closure.
**Server Revision**: 
2129

**Comment by xmesaj2** [comment]
clear cache and try again? cannot reproduce
