### ISSUE TITLE
[Core] Noggenfogger Elixir - zero fall damage

### ISSUE THREAD

**Issue by Firroth** [Atlantiss/NetherwingBugtracker#1228]
**Current behaviour**:
When using [Noggenfogger Elixir](https://www.wowhead.com/item=8529/noggenfogger-elixir) you don't take fall damage (not always though, depends on how high I guess). In my case I jumped from Tanaris to Un'goro Crater, when buff wore off I fallen from at least 60-80yards and didn't take any fall damage. Same thing happened when I jumped from Twin Collossus Mountain in Feralas. Other times I died, 

Needs more proper testing in what cases it occurs, what height is min. / max. etc. I would test it more properly if I didn't had to run to my body each time it failed (1k yards+) so best way to research it is to hire some cliff jumpers xD

**Expected behaviour**: 
When [buff](https://www.wowhead.com/spell=16593/noggenfogger-elixir) from [Noggernfogger Elixir](https://www.wowhead.com/item=8529/noggenfogger-elixir) wears off and you were 15y+ above ground you should get fall damage.

**Server Revision**: 
2126

**Comment by Evolvee** [comment]
Same thing will apply for Slow Fall and Levitate.
question is if this is how its supposed to work or not

**Comment by Firroth** [comment]
It for sure isn't supposed to work that way, if it was it would make fights like "Kael'thas / Archimonde" trivial, since you would f.e on Archimonde use tear // nogger / other spell 100y above and take no dmg after removing it manually.

**Comment by Tereneckla** [comment]
Fixed
