### ISSUE TITLE
Dire Maul East, Alzzin room.

### ISSUE THREAD

**Issue by Erodraeda** [Atlantiss/NetherwingBugtracker#1229]
[//]: # (Enclose links to things related to the bug using http://wowhead.com or any other TBC database.)
[//]: # (You can use screenshot ingame to visual the issue.)
[//]: # (Write your tickets according to the format:)
[//]: # ([Quest][Azuremyst Isle] Red Snapper - Very Tasty!)
[//]: # ([NPC] Magistrix Erona)
[//]: # ([Spell][Mage] Fireball)
[//]: # ([Npc][Drop] Ghostclaw Lynx)
[//]: # ([Web] Armory doesnt work)

**Description**: 
There were no tree-guards around the ramp, and the D2 summon (entry: 16097) was up. Talking about it, the add it summons was friendly to the players, and did nothing during the fight. Alzzin, the boss, Entry: 11492, did not summon the imps when he's at low health and used Wild Regeneration during the wolf phase (not supposed to use it).
**Current behaviour**:
![screenshot_539](https://user-images.githubusercontent.com/40346279/46510115-5cb87780-c81d-11e8-8fe0-788d73b10267.png)
![screenshot_536](https://user-images.githubusercontent.com/40346279/46510116-5cb87780-c81d-11e8-82e4-116d2607d365.png)
![screenshot_537](https://user-images.githubusercontent.com/40346279/46510117-5d510e00-c81d-11e8-8fe1-5df06f630dfe.png)
![screenshot_538](https://user-images.githubusercontent.com/40346279/46510118-5d510e00-c81d-11e8-9b2a-3843f944cbcf.png)
**Expected behaviour**: 
There should be tree-guards, D2 boss shouldn't be up and it's add should attack too, Alzzin should summon imps at the end of the fight (RP which open the hole on the wall behind him so we can go out) and should not cast Wild Regeneration during wolf phase (of the last one, I'm not 100% sure).
**Server Revision**: 2126

**Comment by Godmatik** [comment]
Closing - consolidating all information into one thread
