### ISSUE TITLE
Silverwing Emissaries Exodar

### ISSUE THREAD

**Issue by ttghnw** [Atlantiss/NetherwingBugtracker#123]
[//]: # (Enclose links to things related to the bug using http://wowhead.com or any other TBC database.)
[//]: # (You can use screenshot ingame to visual the issue.)
[//]: # (Write your tickets according to the format:)
[//]: # ([Quest][Azuremyst Isle] Red Snapper - Very Tasty!)
[//]: # ([NPC] Magistrix Erona)
[//]: # ([Spell][Mage] Fireball)
[//]: # ([Npc][Drop] Ghostclaw Lynx)
[//]: # ([Web] Armory doesnt work)

**Description**: 
Wrong position and behavior
**Current behaviour**:
At least one of the emissaries is solo emoting as if talking to the usual pair and standing randomly in the middle of Seat of the Naaru
**Expected behaviour**: 
The emissary should be in a pair or patrolling the city and it is in neither situation.
![wowscrnshot_092318_040945](https://user-images.githubusercontent.com/43508698/45923778-05dea400-bee7-11e8-83c0-105a092921ae.jpg)
![wowscrnshot_092318_041152](https://user-images.githubusercontent.com/43508698/45923779-05dea400-bee7-11e8-8868-6971200f8041.jpg)

Discord: Kittypurrs

**Server Revision**:

**Comment by Wolffenstein** [comment]
Fixed in rev 2027.
