### ISSUE TITLE
[Spell][Warrior] Hamstring

### ISSUE THREAD

**Issue by maxturtlesc2** [Atlantiss/NetherwingBugtracker#1230]
[//]: # (Enclose links to things related to the bug using http://wowhead.com or any other TBC database.)
[//]: # (You can use screenshot ingame to visual the issue.)
[//]: # (Write your tickets according to the format:)
[//]: # ([Quest][Azuremyst Isle] Red Snapper - Very Tasty!)
[//]: # ([NPC] Magistrix Erona)
[//]: # ([Spell][Warrior] Fireball)
[//]: # ([Npc][Drop] Ghostclaw Lynx)
[//]: # ([Web] Armory doesnt work)

**Description**: 
When a NPC is fleeing, Hamstring does not have any slowing effect.
**Current behaviour**:
If the spell is applied before the NPC starts fleeing it works properly, but does not if the spell is applied after the mob starts running away.
**Expected behaviour**: 
Hamstring should slow NPCs down, no matter its current state.
**Server Revision**:

**Comment by maxturtlesc2** [comment]
Nevermind, it seems to correctly applies the slowing effect even when mobs are fleeing.

**Comment by Easyfraggy** [comment]
Need retest of this issue, is this still happening?

**Comment by bloodwindz** [comment]
nope
