### ISSUE TITLE
Dire Maul West

### ISSUE THREAD

**Issue by Erodraeda** [Atlantiss/NetherwingBugtracker#1231]
[//]: # (Enclose links to things related to the bug using http://wowhead.com or any other TBC database.)
[//]: # (You can use screenshot ingame to visual the issue.)
[//]: # (Write your tickets according to the format:)
[//]: # ([Quest][Azuremyst Isle] Red Snapper - Very Tasty!)
[//]: # ([NPC] Magistrix Erona)
[//]: # ([Spell][Mage] Fireball)
[//]: # ([Npc][Drop] Ghostclaw Lynx)
[//]: # ([Web] Armory doesnt work)

**Description**: 
Warpwood Crushers (entry: 13021) aren't patrolling, and there is no mana crystal for the shield there. 

Ironbark the Redeemed (entry: 14241) is there, standing and hostile. 

Tendris (entry: 11489) is in the wrong spot (should be more in the middle of the room), and he also didn't pull unkilled patrols on the upper level, and the door behind was open.

The ghosts on the first room to the right are missing, there are almost no mobs around. 

Magister Kalendris was in the wrong spot (should be a little bit more to the right). 

Illyanna wasnt patrolling and had no pet with her. 

There are missing packs all over the dungeon, and the mana crystals (or whatever it is called) that you have to clear around to deactivate Immol'thar's shield are missing, and the shield is missing too. 

The corridor after Tendris had no ghosts. 

All patrols in Immol'thar's room are missing and the mobs are not the correct ones, Lord Hel'nurath (entry : 14506), summon for the warlock mount quest, was summoned, and all objects (like the dreadsteed spirit) were around the room. 

Immol'thar was missing the 2 night elf ghosts that were supposed to be with him, and Paul's pet got stuck on the air after getting teleported above him, and I got out of combat when the same happened to me. 

Prince Tortheldrin (entry: 11486) should be down the platform, not up (he's neutral because we couldn't kill Immol'thar).
**Current behaviour**:
![screenshot_546](https://user-images.githubusercontent.com/40346279/46510914-000b8b80-c822-11e8-9233-7205802d37ce.png)
![screenshot_547](https://user-images.githubusercontent.com/40346279/46510915-00a42200-c822-11e8-914b-9375e75949f0.png)
![screenshot_548](https://user-images.githubusercontent.com/40346279/46510916-00a42200-c822-11e8-99df-5e60844c4c47.png)
![screenshot_549](https://user-images.githubusercontent.com/40346279/46510917-00a42200-c822-11e8-8a93-5e93fcfff62b.png)
![screenshot_550](https://user-images.githubusercontent.com/40346279/46510918-00a42200-c822-11e8-84bb-1139e669e8d4.png)
![screenshot_551](https://user-images.githubusercontent.com/40346279/46510919-00a42200-c822-11e8-8174-21e79d235ffe.png)
![screenshot_552](https://user-images.githubusercontent.com/40346279/46510920-013cb880-c822-11e8-957d-4a66e59a1fcb.png)
![screenshot_553](https://user-images.githubusercontent.com/40346279/46510921-013cb880-c822-11e8-801f-c78aaf54809c.png)
![screenshot_554](https://user-images.githubusercontent.com/40346279/46510922-01d54f00-c822-11e8-88e1-8567f2cd0146.png)
![screenshot_555](https://user-images.githubusercontent.com/40346279/46510923-01d54f00-c822-11e8-84b1-cba800502f2c.png)
![screenshot_557](https://user-images.githubusercontent.com/40346279/46511011-7ad4a680-c822-11e8-920d-13eee886ab21.png)
![screenshot_556](https://user-images.githubusercontent.com/40346279/46511012-7ad4a680-c822-11e8-9e75-6f8160081512.png)
![screenshot_558](https://user-images.githubusercontent.com/40346279/46511168-61802a00-c823-11e8-8661-8e0dfe95f54d.png)
![screenshot_559](https://user-images.githubusercontent.com/40346279/46511345-7d380000-c824-11e8-963b-90b875ff2e38.png)
**Expected behaviour**: 
Warpwood crusher should patrol around, there should be a mana crystal in the middle of that room, 
Ironbark the Redeemed shouldn't spawn in this instance, 

Tendris should be a little bit more to the right, on the center of the room and the unkilled warpwood crushers should aggro if you engage him, the door should be closed, 

there should be a lot of packs in the room to the right, 

and the corridor towards immol'thar, and upstairs. Illyanna should patrol around with a bear pet, and there should be 2 crystals (one at each side) with mana mobs around to kill and deactivate the crystal. 

Immol'thar room - the warlock mount quest summon shouldn't be there(including all other objects and NPCs of that quest), there should be air elementals patrolling, mana mobs in a circle around immol'thar, mana crystals around to finish deactivating the shield (3 crystals in that room, I think), 

there should be night elfs with immol'thar (that are killed when he is engaged). 

the prince, last boss, should be down that platform, not on the up side.
**Server Revision**: 2126

**Comment by ttghnw** [comment]
After killing Immolthar Prince Tortheldrin remains neutral.

**Comment by Dimbleglim** [comment]
This issue still exists.

**Comment by Godmatik** [comment]
Closing - consolidating all information into one thread
