### ISSUE TITLE
[Spell][Warrior] Intimidating Shout

### ISSUE THREAD

**Issue by maxturtlesc2** [Atlantiss/NetherwingBugtracker#1232]
[//]: # (Enclose links to things related to the bug using http://wowhead.com or any other TBC database.)
[//]: # (You can use screenshot ingame to visual the issue.)
[//]: # (Write your tickets according to the format:)
[//]: # ([Quest][Azuremyst Isle] Red Snapper - Very Tasty!)
[//]: # ([NPC] Magistrix Erona)
[//]: # ([Spell][Mage] Fireball)
[//]: # ([Npc][Drop] Ghostclaw Lynx)
[//]: # ([Web] Armory doesnt work)
https://www.wowhead.com/spell=155582/intimidating-shout
**Description**: 
Intimidating Shout does not work properly.
**Current behaviour**:
The spell currently requires to have a target AND to have that target in front of you to be able to use the spell. Moreover according to wowhead, it does not have a 10 yd range.
**Expected behaviour**: 
Intimidating Shout is an aoe fear that can be used even without target or having any mobs around you (and according to wowhead, it has a 8yd range).
**Server Revision**:

**Comment by bloodwindz** [comment]
http://wow.allakhazam.com/wiki/warrior_abilities_(wow)  

date june 2018  as it says the spell got 8 yards range

**Comment by killablink** [comment]
I'm pretty sure you need a target for Intimidating shout. The person you target with the fear doesn't move while the other people around you move during fear. The person you targeted has their fear broken in one hit while the one running away while feared can take some damage before their fear breaks.

**Comment by Easyfraggy** [comment]
Intimidating shout - Main target has 10 yards range - the aoe effect is 8 yards. You can see this easily on pvp videos where intimidating shout is using on very long range on a main target.

Intimidating shout definitely needs a frontal target.
