### ISSUE TITLE
Slice and Dice overlapping

### ISSUE THREAD

**Issue by Erodraeda** [Atlantiss/NetherwingBugtracker#1233]
[//]: # (Enclose links to things related to the bug using http://wowhead.com or any other TBC database.)
[//]: # (You can use screenshot ingame to visual the issue.)
[//]: # (Write your tickets according to the format:)
[//]: # ([Quest][Azuremyst Isle] Red Snapper - Very Tasty!)
[//]: # ([NPC] Magistrix Erona)
[//]: # ([Spell][Mage] Fireball)
[//]: # ([Npc][Drop] Ghostclaw Lynx)
[//]: # ([Web] Armory doesnt work)

**Description**: 
When you do a higher rank (as in higher number of combo points) of SnD, you shouldn't be able to use a lower rank right after, since the time left is higher (There's a more powerful spell active)
**Current behaviour**:
Slice and dice is being overlapped by lower ranks of it (lower number of combo points)
**Expected behaviour**: 
a message with "There's a more powerful spell active" should appear
**Server Revision**:

**Comment by Evolvee** [comment]
S&D aura stacking is different than other auras(more research on CC github), but it doesnt work anyway since the system is currently disabled and will be fully rewritten

@Easyfraggy add it to the list
