### ISSUE TITLE
Dire Maul North.

### ISSUE THREAD

**Issue by Erodraeda** [Atlantiss/NetherwingBugtracker#1234]
[//]: # (Enclose links to things related to the bug using http://wowhead.com or any other TBC database.)
[//]: # (You can use screenshot ingame to visual the issue.)
[//]: # (Write your tickets according to the format:)
[//]: # ([Quest][Azuremyst Isle] Red Snapper - Very Tasty!)
[//]: # ([NPC] Magistrix Erona)
[//]: # ([Spell][Mage] Fireball)
[//]: # ([Npc][Drop] Ghostclaw Lynx)
[//]: # ([Web] Armory doesnt work)

**Description**: 
The door for DM:W wasn't there. there should be no Gordok Spirits (11446) shouldn't spawn here. There are missing packs and patrols in the whole room, and there's a gordok warlock (11448) in one of those packs (they shouldn't spawn in this room), and the Carrion Swarmers (entry: 13160) should be from ID 4 only, not any other kind of ID.

The courtyard is missing most of the mobs and patrols, and the Guard isn't patrolling. It's also missing the door for the corridor. There's also 2 packs of Carrion Swarmers missing (two red circles in one of the screenshots).

In the corridor, the first pack should be 1 Warlock (11448) with his doomguard and 2 Reavers (11450), and the second one of each.

Slip'kik should be patrolling, and there are some packs missing around, and some mobs that shouldn't be there (like the spirits). Also, the first pack to the right should be a little further away from the Goblin NPC, in a way you can reach him without pulling the pack at lvl 60. The pack right before the ramp should have 2 warlocks and 1 reaver (as far as I remember, of this one I am not sure)

Lots of packs missing from this point onward, and there should be 2 reavers on the door (that is also missing) before Krom'crush's corridor.

The first pack in that corridor should be 4 mob pack, and Krom'crush's adds should only spawn when he's at 50% HP. When Krom'crush is engaged, he yells "Help me crush these punys!", but the sound that went out was "Nobody may challenge the brotherhood" (speech from Edwin VanCleef).

There should be only Captains and Mages on Gordok's room, and the dog patrols (that were also missing).

King Gordok's fight worked well, except for a little evade bug on Cho'rush, and that Cho'rush didn't become friendly after King Gordok was killed.

The Tribute event didn't happen at all, the chest just spawned (at the wrong place lol)

**Current behaviour**:
![screenshot_579](https://user-images.githubusercontent.com/40346279/46513388-a8275180-c82e-11e8-988d-de0a026071b4.png)
![screenshot_580](https://user-images.githubusercontent.com/40346279/46513390-a8275180-c82e-11e8-9286-a4096552dd2c.png)
![screenshot_581](https://user-images.githubusercontent.com/40346279/46513391-a8275180-c82e-11e8-80aa-7d0257e62b8d.png)
![screenshot_582](https://user-images.githubusercontent.com/40346279/46513393-a8275180-c82e-11e8-9f2a-6827946f9ee2.png)
![screenshot_583](https://user-images.githubusercontent.com/40346279/46513394-a8275180-c82e-11e8-8da9-e96dbe2370a5.png)
![screenshot_584](https://user-images.githubusercontent.com/40346279/46513395-a8bfe800-c82e-11e8-803f-5275c146b242.png)
![screenshot_560](https://user-images.githubusercontent.com/40346279/46513396-a8bfe800-c82e-11e8-90c4-f3a6dcc9cf02.png)
![screenshot_561](https://user-images.githubusercontent.com/40346279/46513397-a8bfe800-c82e-11e8-9eec-f14e56c46515.png)
![screenshot_562](https://user-images.githubusercontent.com/40346279/46513398-a8bfe800-c82e-11e8-8e24-38e0654765cb.png)
![screenshot_563](https://user-images.githubusercontent.com/40346279/46513399-a9587e80-c82e-11e8-9ee3-3bfd077f797e.png)
![screenshot_564](https://user-images.githubusercontent.com/40346279/46513400-a9587e80-c82e-11e8-8426-d304b52bf205.png)
![screenshot_565](https://user-images.githubusercontent.com/40346279/46513401-a9587e80-c82e-11e8-9838-8e5b328f13aa.png)
![screenshot_566](https://user-images.githubusercontent.com/40346279/46513402-a9587e80-c82e-11e8-9dcb-37f0c157560e.png)
![screenshot_567](https://user-images.githubusercontent.com/40346279/46513403-a9587e80-c82e-11e8-80e7-f2f696d35fb2.png)
![screenshot_568](https://user-images.githubusercontent.com/40346279/46513404-a9f11500-c82e-11e8-84d7-c7aa73742644.png)
![screenshot_569](https://user-images.githubusercontent.com/40346279/46513405-a9f11500-c82e-11e8-8650-4aa4d404d27e.png)
![screenshot_570](https://user-images.githubusercontent.com/40346279/46513406-a9f11500-c82e-11e8-86e0-8da151f5214b.png)
![screenshot_571](https://user-images.githubusercontent.com/40346279/46513407-aa89ab80-c82e-11e8-98db-cdbcebb7a6d0.png)
![screenshot_572](https://user-images.githubusercontent.com/40346279/46513408-aa89ab80-c82e-11e8-8bed-e06eda1585ed.png)
![screenshot_573](https://user-images.githubusercontent.com/40346279/46513410-ab224200-c82e-11e8-82af-ede631fe1ab1.png)
![screenshot_574](https://user-images.githubusercontent.com/40346279/46513411-ab224200-c82e-11e8-9dba-372f3f1ee183.png)
![screenshot_575](https://user-images.githubusercontent.com/40346279/46513412-ab224200-c82e-11e8-9c71-16b4e74a08dc.png)
![screenshot_576](https://user-images.githubusercontent.com/40346279/46513414-abbad880-c82e-11e8-8498-70466a2db0ad.png)
![screenshot_577](https://user-images.githubusercontent.com/40346279/46513415-abbad880-c82e-11e8-9afa-a6c76cb26120.png)
![screenshot_578](https://user-images.githubusercontent.com/40346279/46513416-abbad880-c82e-11e8-911d-016fe7e898e4.png)

**Expected behaviour**: 
There should be a door between DM:N and the corridor for DM:W.

There should be no Gordok Spirit spawns

There should be way more packs around, and patrols.

There should be only Carrion Swarmers (entry: 13160, ID: 4), no other Carrion Swarmers. (they had different IDs)

There should be several packs and patrols in the Courtyard, including the Guard's patrol.

In the corridor, the first pack should be 1 Warlock (11448) with his doomguard and 2 Reavers (11450), and the second one of each.

Slip'kik should be patrolling, and there should be more mobs around, also some wrong spawns there. Also, the first pack to the right should be a little further away from the Goblin NPC, in a way you can reach him without pulling the pack at lvl 60.

There are several packs missing at this point.

The pack before the last door (before Captain Krom'crush) shuold be 2 Reavers, one at each side of the door.

The pack before Captain Krom'crush should be a 4 mob pack.

Krom'crush's adds should only spawn when he's at 50% HP. When Krom'crush is engaged, he yells "Help me crush these punys!", but the sound that went out was "Nobody may challenge the brotherhood" (speech from Edwin VanCleef).

There should be only Captains and Mages on Gordok's room, and the dog patrols (that were also missing).

King Gordok's fight worked well, except for a little evade bug on Cho'rush. Cho'rush should have become friendly after Gordok has been killed, triggering the Tribute event.

After the Tribute event is triggered, a NPC should run in, telling you you are the king, etc (all that RP event), then spawn the Tribute Chest (loot based on how many guards are alive). After that, you talk to him to become the king, becoming friendly with all mobs in the instance, getting buffs from guards (and a quest from Krom'crush).

**Server Revision**: 2126

**Comment by Derpyous** [comment]
Any news on this issue? The video below shows the courtyard as it was in tbc, which is also how it was in vanilla. 

https://www.youtube.com/watch?v=jDtssm6vAdE

**Comment by ircfelix** [comment]
Is it possible to get the tribute run buff (the one that makes you king of all ogres)? I have heard it currently isn't working.

**Comment by BezawitNW** [comment]
Would love to get tribute event working properly. Being made king would allow you to buy the +25 spirit -5 intellect consumable, which stacks with everything.

**Comment by Godmatik** [comment]
Closing - consolidating all information into one thread
