### ISSUE TITLE
Mind Numbing Poison and Curse of Tongues stacking

### ISSUE THREAD

**Issue by Erodraeda** [Atlantiss/NetherwingBugtracker#1235]
[//]: # (Enclose links to things related to the bug using http://wowhead.com or any other TBC database.)
[//]: # (You can use screenshot ingame to visual the issue.)
[//]: # (Write your tickets according to the format:)
[//]: # ([Quest][Azuremyst Isle] Red Snapper - Very Tasty!)
[//]: # ([NPC] Magistrix Erona)
[//]: # ([Spell][Mage] Fireball)
[//]: # ([Npc][Drop] Ghostclaw Lynx)
[//]: # ([Web] Armory doesnt work)

**Description**: 
Mind-numbing poison and Curse of tongues stacked, resulting in a 120% casting speed slow.
**Current behaviour**:
![screenshot_587](https://user-images.githubusercontent.com/40346279/46515570-08bc8b80-c83b-11e8-9000-bf262e430cc6.png)
**Expected behaviour**: 
Similar effects shouldn't stack.
**Server Revision**:

**Comment by Evolvee** [comment]
aura stacking is currently disabled due to problems with buffs

**Comment by Evolvee** [comment]
@Easyfraggy add it to the list

closing the issue for now as the system will be rewritten entirely
