### ISSUE TITLE
Franclorn Forgewright

### ISSUE THREAD

**Issue by Piledriversn** [Atlantiss/NetherwingBugtracker#1236]
![image](https://user-images.githubusercontent.com/43560552/46517147-66e57080-c833-11e8-98b8-ebf9723cce25.png)
[//]: # ([Quest][Blackrock Depths] Dark Iron Legacy)
[//]: # ([NPC] Franclorn Forgewright)

**Description**: The npc Franclorn Forgewright to pick up the quest Dark Iron Legacy is not available while dead and the npc simply says unknown. 

**Current behaviour**:

**Expected behaviour**: 

**Server Revision**:

**Comment by Evolvee** [comment]
fixed in rev Xd
