### ISSUE TITLE
[Spell][Warlock] Drain Life not causing healing threat

### ISSUE THREAD

**Issue by Rama089** [Atlantiss/NetherwingBugtracker#1238]
[//]: # (Enclose links to things related to the bug using http://wowhead.com or any other TBC database.)
[//]: # (You can use screenshot ingame to visual the issue.)
[//]: # (Write your tickets according to the format:)
[//]: # ([Quest][Azuremyst Isle] Red Snapper - Very Tasty!)
[//]: # ([NPC] Magistrix Erona)
[//]: # ([Spell][Mage] Fireball)
[//]: # ([Npc][Drop] Ghostclaw Lynx)
[//]: # ([Web] Armory doesnt work)

**Description**: 
Drain Life appears to not generate threat for the healing part of the ability.

**Current behaviour**:
Pet bodypulls mob 2 while engaged with mob 1. Warlock casts drain life on mob 1, healing himself. Mob 2 continues attacking pet who is only engaged with mob 1.  Threat table for mob 2 is completely empty according to Omen, despite healing hp on player. Threat table for mob 1 appears to only count the dmg portion of Drain Life, not healing.

**Expected behaviour**: 
Drain Life should generate threat from healing as well. In the above scenario mob 2 shouldve switched targets to the warlock after 1 tick of Drain Life healing went off.
**Server Revision**: 
[2126]

Screenshot depicting issue: Mob 2 is targetted, observe empty threat table.
https://imgur.com/8Q2XhGG

**Comment by Rama089** [comment]
Siphon Life appears to have same issue.

Screenshot: Mob 2 is targetted (pet bodypull), siphon ticks have healed, observe empty threat table.
https://imgur.com/cT0T9hT

**Comment by Evolvee** [comment]
https://github.com/Looking4Group/L4G_Core/issues/2040
https://forum.nostalrius.org/viewtopic.php?f=24&t=16499

**Comment by Evolvee** [comment]
^^ most likely intended, try to find evidence/proof to support your claim

**Comment by Rama089** [comment]
I can only find more references to support that this is indeed, how it worked in retail. My bad, guess it was broken on most private servers!
