### ISSUE TITLE
[Quest][Azshara] Kim'jael Indeed!

### ISSUE THREAD

**Issue by DeltaLoads** [Atlantiss/NetherwingBugtracker#1239]
[//]: # (Enclose links to things related to the bug using http://wowhead.com or any other TBC database.)
[//]: # (You can use screenshot ingame to visual the issue.)
[//]: # (Write your tickets according to the format:)
[//]: # ([Quest][Azuremyst Isle] Red Snapper - Very Tasty!)
[//]: # ([NPC] Magistrix Erona)
[//]: # ([Spell][Mage] Fireball)
[//]: # ([Npc][Drop] Ghostclaw Lynx)
[//]: # ([Web] Armory doesnt work)

**Description**: 
Drop rate for quest items from Kim'jael's Equipment doesn't work correctly, when you open first one you get 1 item as intended, but then drop rate for quest items drops when it shouldnt.
Kim'jael's Equipment - https://classicdb.ch/?object=153123
**Current behaviour**:
Drop rate for quest items in container is too low.
**Expected behaviour**: 
Drop rate for quest items should be 100%
**Server Revision**: 
2126

**Comment by Shanghi** [comment]
classicdb.ch is another private server database so can't be trusted. Sometimes there will be useful retail comments about things like this on [Wowhead](https://www.wowhead.com/quest=3601/kimjael-indeed#comments), [Thottbot](https://web.archive.org/web/20080430230612/http://thottbot.com/q3601), and [Allakhazam](https://web.archive.org/web/20080430230612/http://wow.allakhazam.com:80/db/quest.html?wquest=3601).

It was changed from being 100% because of comments like these (and many more):
> "Got all but the compass in the 3 first boxes i opened. I looted the compass 14 boxes later"
>
> "Confirmed, I got 3/4 in the first 2 boxes, then it took me 17 boxes to get the Wizzlegoober"
>
> ""Confirmed" what? It's random. I got junk in my first ~10 boxes and then I got them nicely, it's just random"
>
> "You need to open the boxes marked kim jael's equipment it does not always have quest items in them but they are found there."
>
> "I am on this quest for over one hour and the 4th items don't want to be looted, I only got some stupid fruits or whatever. Those guys at Blizz seems to enjoy making stupid quests just for the fun to piss off people."
>
> "I got two items out of one box, another from another box, and then found several boxes with just juice."
>
> "Opened at least 20 boxes, none of them had the scope."
>
> "I opened every crate, but it took long before any equipment came out of it."
>
> "I hide behinde the rocks, kill every blood elf there, checked the boxes (got 1 of the items, and some fruits), hide and kill again, wait for the boxes to pop again, got some fruits and cakes, waited n killed again and got the rest of Ki'jael's stuff in the last 2 boxes repopping again"
>
> "3 items in 29 boxes so far..."
>
> "19-20 crates before i had all 4 items"
