### ISSUE TITLE
Ammen Vale Guardian Position

### ISSUE THREAD

**Issue by ttghnw** [Atlantiss/NetherwingBugtracker#124]
[//]: # (Enclose links to things related to the bug using http://wowhead.com or any other TBC database.)
[//]: # (You can use screenshot ingame to visual the issue.)
[//]: # (Write your tickets according to the format:)
[//]: # ([Quest][Azuremyst Isle] Red Snapper - Very Tasty!)
[//]: # ([NPC] Magistrix Erona)
[//]: # ([Spell][Mage] Fireball)
[//]: # ([Npc][Drop] Ghostclaw Lynx)
[//]: # ([Web] Armory doesnt work)

**Description**: 
The Npc position is odd
**Current behaviour**:
The guardian in the attachment stares at the hill instead of the natural position of watching the incoming newbies from the road
**Expected behaviour**: 
Positioned slightly towards the crash site road side
![wowscrnshot_092318_044004](https://user-images.githubusercontent.com/43508698/45923933-14c75580-beeb-11e8-83b9-463c3488d994.jpg)
![wowscrnshot_092318_044010](https://user-images.githubusercontent.com/43508698/45923934-14c75580-beeb-11e8-8da9-6146c79e7f3c.jpg)

**Server Revision**:

**Comment by Wolffenstein** [comment]
Blizzlike, I changed their positions based on retail sniffs. It looks exactly the same (weird) on retail.
