### ISSUE TITLE
 ([Quest][Bloodmyst Isle] The Bear Necessities) Drop rate very low

### ISSUE THREAD

**Issue by Rebelyna** [Atlantiss/NetherwingBugtracker#1240]
**Description**: 
The Quest "The Bear Necessities" wants you to gather 8 Elder Brown Bear Flanks.

**Current behaviour**:
After killing 20 of them, I only got 1 Flank. Is this supposed to be that way?

**Expected behaviour**: 
Somewhat higher drop rate for the quest item.

**Server Revision**: 
2126

**Comment by narayagh** [comment]
I had more luck (got 1 every 3-4 kills) but the droprate is quite low, I think it's supposed to be.

**Comment by Firroth** [comment]
It works like it should.
![screenshot_1](https://user-images.githubusercontent.com/43505196/46534060-30493d80-c8a7-11e8-84d3-7e532c0a12aa.png)

**Comment by Azalen** [comment]
First - which Bears did you kill? Only the elder ones (level 15-16) are supposed to drop it with good chance.

Regarding the drop chances:
http://web.archive.org/web/20080405022929/http://wow.allakhazam.com:80/db/item.html?witem=24026  says 21% which seems low but reasonable
