### ISSUE TITLE
[Item] Shredder Operating Manual pages

### ISSUE THREAD

**Issue by mikefirefly** [Atlantiss/NetherwingBugtracker#1241]
[//]: # (Enclose links to things related to the bug using http://wowhead.com or any other TBC database.)
[//]: # (You can use screenshot ingame to visual the issue.)
[//]: # (Write your tickets according to the format:)
[//]: # ([Quest][Azuremyst Isle] Red Snapper - Very Tasty!)
[//]: # ([NPC] Magistrix Erona)
[//]: # ([Spell][Mage] Fireball)
[//]: # ([Npc][Drop] Ghostclaw Lynx)
[//]: # ([Web] Armory doesnt work)

**Description**: 
Shredder Operating Manual pages in Ashenvale.

**Current behaviour**:
Shredder Operating Manual pages drop for alliance:
![wow_2018-10-05_12-25-08](https://user-images.githubusercontent.com/13250690/46530574-7d72e280-c89a-11e8-8a29-257b66148294.jpg)

**Expected behaviour**: 
According to [http://wowwiki.wikia.com/wiki/Shredder_Operating_Manual_-_Page_1](http://wowwiki.wikia.com/wiki/Shredder_Operating_Manual_-_Page_1):
Patch 1.8.0 (10-Oct-2005): Shredder Operating Manual pages will no longer drop for the Alliance.

**Server Revision**: 
2126

**Comment by Shanghi** [comment]
To anyone that can make core changes: condition 30 needs to be able to target the player that's looting

**Comment by KevinTyrrell** [comment]
Still present as of revision `2893`.

![](https://i.imgur.com/NwbFPUY.png)

**Comment by devo6969** [comment]
Still dropping for alliance on the PTR.

**Comment by Wolffenstein** [comment]
Fixed in rev 3463.
