### ISSUE TITLE
(Ulag The Cleaver) Undead Warrior LvL 10 Quest doesn't show spell rewards 

### ISSUE THREAD

**Issue by AlteredAli** [Atlantiss/NetherwingBugtracker#1242]
[//]: # (Enclose links to things related to the bug using http://wowhead.com or any other TBC database.)
[//]: # (You can use screenshot ingame to visual the issue.)
[//]: # (Write your tickets according to the format:)
[//]: # ([Quest][Azuremyst Isle] Red Snapper - Very Tasty!)
[//]: # ([NPC] Magistrix Erona)
[//]: # ([Spell][Mage] Fireball)
[//]: # ([Npc][Drop] Ghostclaw Lynx)
[//]: # ([Web] Armory doesnt work)

**Description**: 
It should show defensive stance, sunder (rank 1) and taunt as rewards
**Current behaviour**:
Doesn't show any rewards at all
**Expected behaviour**: 
Should show the spells as rewards 
**Server Revision**:

**Comment by Tereneckla** [comment]
https://classic.wowhead.com/spell=8121/path-of-defense
The spell has no icon so I disagree.
