### ISSUE TITLE
[Tanaris][NPC] Hazalli Swarmer

### ISSUE THREAD

**Issue by wtRCH** [Atlantiss/NetherwingBugtracker#1244]
[//]: # (Enclose links to things related to the bug using http://wowhead.com or any other TBC database.)
[//]: # (You can use screenshot ingame to visual the issue.)
[//]: # (Write your tickets according to the format:)
[//]: # ([Quest][Azuremyst Isle] Red Snapper - Very Tasty!)
[//]: # ([NPC] Magistrix Erona)
[//]: # ([Spell][Mage] Fireball)
[//]: # ([Npc][Drop] Ghostclaw Lynx)
[//]: # ([Web] Armory doesnt work)

**Description**: This NPC is walking half in the ground.
![image](https://user-images.githubusercontent.com/11255782/46534524-b44ff500-c8a8-11e8-89aa-5da99f143d83.png)

![wowscrnshot_100518_141149](https://user-images.githubusercontent.com/11255782/46534537-c03bb700-c8a8-11e8-94a5-c1378b0ca743.jpg)

**Comment by Evolvee** [comment]
gm off
