### ISSUE TITLE
[NPC] Slavering Ghoul not using [Spell] Toxic Saliva

### ISSUE THREAD

**Issue by Firroth** [Atlantiss/NetherwingBugtracker#1245]
[NPC] [Slavering Ghoul](https://web.archive.org/web/20090802033520/http://wow.allakhazam.com:80/db/mob.html?wmob=1791)
[Spell] [Toxic Saliva](https://www.wowhead.com/spell=7125/toxic-saliva)

**Current behaviour**:
Doesn't seem to use [Spell] [Toxic Saliva](https://www.wowhead.com/spell=7125/toxic-saliva), 

**Expected behaviour**: 
Should be using [Spell] [Toxic Saliva](https://www.wowhead.com/spell=7125/toxic-saliva)

![screenshot_1](https://user-images.githubusercontent.com/43505196/46535496-dc8d2300-c8ab-11e8-91e0-6e863273559d.png)

**Server Revision**: 
2126

**Comment by Evolvee** [comment]
rev Xd
