### ISSUE TITLE
[NPC] Bloodscalp Shaman uses Fire Nova during stun

### ISSUE THREAD

**Issue by Mikik3jr** [Atlantiss/NetherwingBugtracker#1246]
[//]: # (Enclose links to things related to the bug using http://wowhead.com or any other TBC database.)
[//]: # (You can use screenshot ingame to visual the issue.)
[//]: # (Write your tickets according to the format:)
[//]: # ([Quest][Azuremyst Isle] Red Snapper - Very Tasty!)
[//]: # ([NPC] Magistrix Erona)
[//]: # ([Spell][Mage] Fireball)
[//]: # ([Npc][Drop] Ghostclaw Lynx)
[//]: # ([Web] Armory doesnt work)

**Description**: 
In STV there are the Bloodscalp Shamans that uses Fire Nova (an instant fire spell) time to time.

**Current behaviour**:
I stunned the NPC for 4s, casted a holy light (2.5s) and after that I got hit with a Fire Nova.
ID:
![wowscrnshot_100518_143802](https://user-images.githubusercontent.com/43505031/46536117-c41e0800-c8ad-11e8-9a96-5f38fd9fff28.jpg)
Combat log:
![wowscrnshot_100518_143828](https://user-images.githubusercontent.com/43505031/46536118-c5e7cb80-c8ad-11e8-84ce-cbf8701a7824.jpg)
**Expected behaviour**: 
They shouldn't  use any spell during stun. I have reported a similar issue, so I suspect more enemies have this bug.
**Server Revision**: 
2126

**Comment by Evolvee** [comment]
rev Xd
