### ISSUE TITLE
[Western Plaguelands] Bad Chest Placement

### ISSUE THREAD

**Issue by Firroth** [Atlantiss/NetherwingBugtracker#1248]
**Current behaviour**:
As you can see on screen chest is placed in "bookshelf".

![screenshot_1](https://user-images.githubusercontent.com/43505196/46540033-7529a000-c8b8-11e8-8e47-d5ce2e362fb6.png)

**Expected behaviour**: 
It should be placed in the other corned of the room, not in the current place where it's colliding with other object.

**Server Revision**: 
2124

**Comment by Evolvee** [comment]
rev Xd
