### ISSUE TITLE
Bleakheart Mobs ignore evasion (maybe even never miss)

### ISSUE THREAD

**Issue by padomu** [Atlantiss/NetherwingBugtracker#1249]
[//]: # (Enclose links to things related to the bug using http://wowhead.com or any other TBC database.)
[//]: # (You can use screenshot ingame to visual the issue.)
[//]: # (Write your tickets according to the format:)
[//]: # ([Quest][Azuremyst Isle] Red Snapper - Very Tasty!)
[//]: # ([NPC] Magistrix Erona)
[//]: # ([Spell][Mage] Fireball)
[//]: # ([Npc][Drop] Ghostclaw Lynx)
[//]: # ([Web] Armory doesnt work)

**Description**: 
The demon mobs at Satyrnaar in Ashenvale seem to never miss me. (I'm not sure about that though) but they 100% don't care about evasion.

**Current behaviour**:

**Expected behaviour**: 
The should miss a few hits if I use evasion. It seems to work for the hellcaller, but if they die, their voidwalker wont despawm.

**Server Revision**: 
2126

**Comment by The14me** [comment]
dodge just fine to me.Please retest and if happen again.Re-open.
