### ISSUE TITLE
Bleakheart Mobs have wrong target for "Chest Pain"

### ISSUE THREAD

**Issue by padomu** [Atlantiss/NetherwingBugtracker#1250]
[//]: # (Enclose links to things related to the bug using http://wowhead.com or any other TBC database.)
[//]: # (You can use screenshot ingame to visual the issue.)
[//]: # (Write your tickets according to the format:)
[//]: # ([Quest][Azuremyst Isle] Red Snapper - Very Tasty!)
[//]: # ([NPC] Magistrix Erona)
[//]: # ([Spell][Mage] Fireball)
[//]: # ([Npc][Drop] Ghostclaw Lynx)
[//]: # ([Web] Armory doesnt work)

**Description**: 
The demon mobs at Satyrnaar in Ashenval seem to have a wrong spell target set for the spell chest pain, they stun themselves.

**Current behaviour**:

**Expected behaviour**: 
I should get stunned.
**Server Revision**:

**Comment by Evolvee** [comment]
https://github.com/Atlantiss/NetherwingBugtracker/issues/497
duplicate
