### ISSUE TITLE
[NPC] Gnarlpine Mystic - aggro reset

### ISSUE THREAD

**Issue by narayagh** [Atlantiss/NetherwingBugtracker#1251]
[//]: # (Enclose links to things related to the bug using http://wowhead.com or any other TBC database.)
[//]: # (You can use screenshot ingame to visual the issue.)
[//]: # (Write your tickets according to the format:)
[//]: # ([Quest][Azuremyst Isle] Red Snapper - Very Tasty!)
[//]: # ([NPC] Magistrix Erona)
[//]: # ([Spell][Mage] Fireball)
[//]: # ([Npc][Drop] Ghostclaw Lynx)
[//]: # ([Web] Armory doesnt work)

**Description**: 
Gnarlpine Mystic - aggro reset mechanics are incorrect

**Current behaviour**:
Mob casts a spell and then resets aggro.
See: https://streamable.com/45ryh

**Expected behaviour**: 
Mob should either keep attacking/casting or reset aggro.

**Server Revision**: 
![wow_2018-10-05_16-49-39](https://user-images.githubusercontent.com/13250690/46542438-b2912c00-c8be-11e8-912a-cb80cab30437.png)

**Comment by narayagh** [comment]
https://streamable.com/hqydp

**Comment by The14me** [comment]
Cant reproduce,please Re-test and if still happen Re-open.
