### ISSUE TITLE
[Spell][Warrior] Whirlwind - hitting targets below or on the other side of wall.

### ISSUE THREAD

**Issue by Firroth** [Atlantiss/NetherwingBugtracker#1252]
[Spell][Warrior] [Whirwild](https://www.wowhead.com/spell=1680/whirlwind) - I guess that's correct ID.

**Current behaviour**:
When using [Spell] [Whirwild](https://www.wowhead.com/spell=1680/whirlwind) in house on other floor, you also hit mobs on the lower floor as seen on this gif.

https://gfycat.com/BonyAcademicGibbon

**Expected behaviour**: 
Should only hit target/targets near player on the same floor, not below and not on the other side of the wall.

**Server Revision**: 
2126

**Comment by Easyfraggy** [comment]
Whirlwind/Demo/TC should indeed obey LOS

**Comment by Wolffenstein** [comment]
Fixed in rev 2391.
