### ISSUE TITLE
[NPC] Highlord Demitrian - Finishing default dialog creates the Vessel of Rebirth

### ISSUE THREAD

**Issue by wowthings** [Atlantiss/NetherwingBugtracker#1253]
[//]: # (Enclose links to things related to the bug using http://wowhead.com or any other TBC database.)
[//]: # (You can use screenshot ingame to visual the issue.)
[//]: # (Write your tickets according to the format:)
[//]: # ([Quest][Azuremyst Isle] Red Snapper - Very Tasty!)
[//]: # ([NPC] Magistrix Erona)
[//]: # ([Spell][Mage] Fireball)
[//]: # ([Npc][Drop] Ghostclaw Lynx)
[//]: # ([Web] Armory doesnt work)

**Description**: 

The [Vessel of Rebirth](https://www.wowhead.com/item=19016/vessel-of-rebirth) is an item that you recieve when talking to [Highlord Demitrian](https://www.wowhead.com/npc=14347/highlord-demitrian) at Silithus only if you have one of the [Bindings of the Windseeker](https://www.wowhead.com/item=18563/bindings-of-the-windseeker) as stated in [this comment](https://www.wowhead.com/item=19016/vessel-of-rebirth#comments:id=881369).
If you have one of the Bindings he makes [this conversation](https://www.wowhead.com/npc=14347/highlord-demitrian#comments:id=680857)
**Current behaviour**:
He gives the item when you finish the default dialog.
![image](https://user-images.githubusercontent.com/43504905/46543436-22081b00-c8c1-11e8-85de-523ef336e79c.png)
It will be useless anyway since the first part doesn't give any experience and you still need both of the Bindings and some rare mats to complete this quest.
**Server Revision**: 
2126

**Comment by Evolvee** [comment]
I will just make the item to not be granted after finishing the conversation if the player doesnt have any of these items..

If the option to talk isnt supposed to be there instead at all, reopen the issue pls.


fixed in revision Xd
