### ISSUE TITLE
[Quest][Stormwind] The Missing Diplomat 1447

### ISSUE THREAD

**Issue by scarabadookie** [Atlantiss/NetherwingBugtracker#1254]
[//]: # (Enclose links to things related to the bug using http://wowhead.com or any other TBC database.)
[//]: # (You can use screenshot ingame to visual the issue.)
[//]: # (Write your tickets according to the format:)
[//]: # ([Quest][Azuremyst Isle] Red Snapper - Very Tasty!)
[//]: # ([NPC] Magistrix Erona)
[//]: # ([Spell][Mage] Fireball)
[//]: # ([Npc][Drop] Ghostclaw Lynx)
[//]: # ([Web] Armory doesnt work)

**Description**: 
Dashel Stonefist doesn't know when to give up

**Current behaviour**:
Dashel Stonefist summons his two thugs, and fights to the death. His thugs also fight until the death. Had to wait for him to respawn to be able to turn the quest in to him, and the quest log said both Defeat Dashel Stonefist (Complete) and Dashel Stonefist slain: 1/1 (Complete)

**Expected behaviour**: 
He should go friendly and call off the thugs at low hp. Some old comments at wowhead [https://www.wowhead.com/quest=1447/the-missing-diplomat](url)

**Server Revision**: 
2126

**Comment by Neophrone** [comment]
Worked fine for me few days ago.

**Comment by scarabadookie** [comment]
I can add that I'm a hunter and my pet had aggro on Dashel Stonefist all the time. I did the followup in Menethil Harbor and "Slim" deaggroed and worked just fine there.

**Comment by tcberk12** [comment]
Dashel gave up just fine for me.

Thought it was weird as soon as you finished interacting with him that he was passive and you have to engage him. I think (I don't know for sure, of course) he should immediately attack you.

**Comment by Evolvee** [comment]
I think i scripted this based on retail videos(not 100% sure) and if i didnt make it attack immediately, it wasnt like that on retail either.

**Comment by Evolvee** [comment]
slightly tweaked in  rev 439kcolb, i dont see any problem anyway tho

if it happens again some day, just reopen this and its probably a core issue
