### ISSUE TITLE
[QUEST]  The Essence of Enmity - incorrect using of the quest item

### ISSUE THREAD

**Issue by samemari** [Atlantiss/NetherwingBugtracker#1255]
[//]: # (Enclose links to things related to the bug using http://wowhead.com or any other TBC database.)
[//]: # (You can use screenshot ingame to visual the issue.)
[//]: # (Write your tickets according to the format:)
[//]: # ([Quest][Azuremyst Isle] Red Snapper - Very Tasty!)
[//]: # ([NPC] Magistrix Erona)
[//]: # ([Spell][Mage] Fireball)
[//]: # ([Npc][Drop] Ghostclaw Lynx)
[//]: # ([Web] Armory doesnt work)

**Description**: 
The quest http://db.hellfire-tbc.com/?quest=11161 assumes using of the quest item (Brogg's totem) on the remains of mobs for getting another quest item
**Current behaviour**:
Using totem on one of the two mobs's remains that located close each other makes invalid target both (like you've used totem on both mobs at one time) but you got only one quest essence
![screenshot 26](https://user-images.githubusercontent.com/29822974/46549406-8c798500-c8da-11e8-8266-2f39c8ac9e96.png)

**Expected behaviour**: 
2 mobs - 2 essences
**Server Revision**: 
2130

**Comment by xmesaj2** [comment]
fixed in 2139
