### ISSUE TITLE
[NPC] Cauldron Lord Razarch - too many npc's

### ISSUE THREAD

**Issue by Firroth** [Atlantiss/NetherwingBugtracker#1256]
[NPC] [Cauldron Lord Razarch](https://web.archive.org/web/20080507141528/http://wow.allakhazam.com:80/db/mob.html?wmob=11076)

**Current behaviour**:
Like on the screen, there is too much mobs "[Cauldron Lord Razarch](https://web.archive.org/web/20080507141528/http://wow.allakhazam.com:80/db/mob.html?wmob=11076)"

![2018-10-05_19-04-38](https://user-images.githubusercontent.com/43505196/46549418-343e8500-c8d2-11e8-87d1-70ede44edb60.gif)

**Expected behaviour**: 
There should be only 1 mob called "[Cauldron Lord Razarch](https://web.archive.org/web/20080507141528/http://wow.allakhazam.com:80/db/mob.html?wmob=11076)"

**Server Revision**: 
2130

**Comment by Evolvee** [comment]
Just out of curiosity, how is this mob spawned? Cuz it doesnt seem to be hard spawn in DB... its probably summoned through some event and i rly rly rly hate plaguelands so i know nothing about it :D

**Comment by Evolvee** [comment]
nevermind i see it

**Comment by Evolvee** [comment]
should be fully rewritten in rev Xd
