### ISSUE TITLE
[NPC][Zone] The Hinterlands - Owlkins and skinning

### ISSUE THREAD

**Issue by Firroth** [Atlantiss/NetherwingBugtracker#1257]
I don't have skinning so I can't check this by myself to make screen or gif.

**Current behaviour**:
You can skin Owlkins in The Hinterlands. (info by someone who skinned them, but doesn't want to report on his own for some reason).

**Expected behaviour**: 
Owlkins in The Hinterlands shouldn't be skinnable.

**Server Revision**: 
2130

**Comment by The14me** [comment]
ID 2929 and 2928

**Comment by Firroth** [comment]
Also check ID [7808]
https://www.wowhead.com/npc=7808/marauding-owlbeast

[2927]
https://www.wowhead.com/npc=2927/vicious-owlbeast

**Comment by Evolvee** [comment]
all listed entries ^^ hopefully fixed in rev Xd

**Comment by Evolvee** [comment]
watchout tho, there still might be an issue due to pooling (these owls share spawnpoints with wolfs)
