### ISSUE TITLE
Doomguard Summon

### ISSUE THREAD

**Issue by Piledriversn** [Atlantiss/NetherwingBugtracker#1259]
![image](https://user-images.githubusercontent.com/43560552/46553214-8ebfed00-c8a2-11e8-880a-28822e4cd2f7.png)
![image](https://user-images.githubusercontent.com/43560552/46553487-3b01d380-c8a3-11e8-9fdb-7b9a56e1db62.png)

[//]: # ([NPC] Doomguard)
[//]: # (Enslave Demon)

**Description**: I summoned him in Goldshire and he occasionally targets guards.

**Current behaviour**:When I Enslave him he just stands there and i can't control him at all. He only attacks what is in range. When i put him on aggressive he wants to attack but he is frozen in place.

**Expected behaviour**: He is a level 70 so he should attack all the alliance npc's. He should also follow me when i enslave him.

**Server Revision**:

**Comment by Piledriversn** [comment]
I summoned the doomguard last night in Goldshire. About six hours later I went through there on my alliance alt. He was still alive. Though I do not believe he can be killed there. I did not want to ruin anyone's questing experience.

**Comment by The14me** [comment]
Confirm,suppose to be there for 45 sec or gone after the warlock go offline.

**Comment by Godmatik** [comment]
Rev 4018, doomguard now despawns after enslave ends, and is controllable by player.
It has some scripting issues, but these are already reported in #8737
