### ISSUE TITLE
[Quest][Teldrassil]Taming the Beast

### ISSUE THREAD

**Issue by mbzz88** [Atlantiss/NetherwingBugtracker#126]
When using the quest item "Taming Rod"(wowhead.com/item=15921, wowhead.com/item=15922, wowhead.com/item=15923) to tame the "Webwood Lurker"(www.wowhead.com/npc=1998), "Nightsaber Stalker"(www.wowhead.com/npc=2043) and "Strigid Screecher"(www.wowhead.com/npc=1996), after taming the pet, it is frozen in place, unable to move or attack.

**Comment by wtRCH** [comment]
Worth mentioning that it also happens for any other Taming the Beast quests

**Comment by Gniddikon** [comment]
Can confirm the same happens for  the blood elf hunter questing line.

**Comment by GooseDriver** [comment]
"Taming Rod" also consumes two charges upon use instead of one.

**Comment by GooseDriver** [comment]
After "Taming Rod" is used (successfully or not) you are also stuck in combat and have to restart client in order to drop it.

**Comment by jason-christian-92** [comment]
Can confirm with Horde troll hunter

**Comment by pelekon** [comment]
fixed in rev 2372
