### ISSUE TITLE
[Item] Faintly Glowing Skull incorrect life drain value

### ISSUE THREAD

**Issue by Sunlancer** [Atlantiss/NetherwingBugtracker#1260]
[//]: # (Enclose links to things related to the bug using http://wowhead.com or any other TBC database.)
[//]: # (You can use screenshot ingame to visual the issue.)
[//]: # (Write your tickets according to the format:)
[//]: # ([Quest][Azuremyst Isle] Red Snapper - Very Tasty!)
[//]: # ([NPC] Magistrix Erona)
[//]: # ([Spell][Mage] Fireball)
[//]: # ([Npc][Drop] Ghostclaw Lynx)
[//]: # ([Web] Armory doesnt work)

**Description**: 
the item Faintly Glowing Skull https://www.wowhead.com/item=4945/faintly-glowing-skull is not working  as intended, and I think it is using the current Wowhead value for health gained.
**Current behaviour**:
It deals 75 to 125 damage, like expected. but gives a lower amount of health in return.
**Expected behaviour**: 
It deals 75 to 125 damage, and gives the same amount of health.
**Server Revision**: 
2131

**Comment by wtRCH** [comment]
@Easyfraggy

**Comment by Easyfraggy** [comment]
There are already 3 reports on this but I can't recreate it at all.

**Comment by Easyfraggy** [comment]
Duplicate https://github.com/Atlantiss/NetherwingBugtracker/issues/432
