### ISSUE TITLE
[Spell] Maggot Slime can be parried/dodged.

### ISSUE THREAD

**Issue by Firroth** [Atlantiss/NetherwingBugtracker#1261]
[NPC] [Carrion Grub](https://www.wowhead.com/npc=8603/carrion-grub)
[Spell] [Maggot Slime](https://www.wowhead.com/spell=16449/maggot-slime#used-by-npc)

**Current behaviour**:
[Spell] [Maggot Slime](https://www.wowhead.com/spell=16449/maggot-slime#used-by-npc) can be dodged/parried, perhaps even blocked/missed.

![screenshot_1](https://user-images.githubusercontent.com/43505196/46553617-41fa0780-c8de-11e8-9085-f1447116cdbe.png)

![screenshot_2](https://user-images.githubusercontent.com/43505196/46553619-42929e00-c8de-11e8-80f5-c967c45a03e9.png)

**Expected behaviour**: 
You cannot dodge spells, even if it's "apply on hit", if hit landed on you so will the apply chance (only exception is resist).

**Server Revision**: 
2130

**Comment by Wolffenstein** [comment]
Well apparently its DamageClass = 2 (SPELL_DAMAGE_CLASS_MELEE) so technically it works fine. Needs research

**Comment by Tenoutoften** [comment]
On Thottbot archive it lists the school as nature, so it is a melee attack that's nature effect? Anyway, I read some comments on wowhead found nothing. I'd recommend closing this unless someone finds evidence...
![](https://i.gyazo.com/2390479dd8ad1c63b4de5c1365783508.png)
