### ISSUE TITLE
Rested XP is being generated too fast

### ISSUE THREAD

**Issue by Erodraeda** [Atlantiss/NetherwingBugtracker#1262]
[//]: # (Enclose links to things related to the bug using http://wowhead.com or any other TBC database.)
[//]: # (You can use screenshot ingame to visual the issue.)
[//]: # (Write your tickets according to the format:)
[//]: # ([Quest][Azuremyst Isle] Red Snapper - Very Tasty!)
[//]: # ([NPC] Magistrix Erona)
[//]: # ([Spell][Mage] Fireball)
[//]: # ([Npc][Drop] Ghostclaw Lynx)
[//]: # ([Web] Armory doesnt work)

**Description**: 
The generation of rested XP is way faster than it was on retail.
**Current behaviour**:
around 4 hours for 5%
**Expected behaviour**: 
One bubble of rested XP (5% of a level) is earned for every 8 hours spent resting. A maximum of 30 bubbles (150% of a level) may be earned. 
http://wowwiki.wikia.com/wiki/Rest
https://www.wowhead.com/forums&topic=18223
**Server Revision**: 2130

**Comment by Manaci** [comment]
Invalid now that it has been purposely increased.
