### ISSUE TITLE
[NPC] Venomtail Scorpid spawn on each other

### ISSUE THREAD

**Issue by Sunlancer** [Atlantiss/NetherwingBugtracker#1263]
[//]: # (Enclose links to things related to the bug using http://wowhead.com or any other TBC database.)
[//]: # (You can use screenshot ingame to visual the issue.)
[//]: # (Write your tickets according to the format:)
[//]: # ([Quest][Azuremyst Isle] Red Snapper - Very Tasty!)
[//]: # ([NPC] Magistrix Erona)
[//]: # ([Spell][Mage] Fireball)
[//]: # ([Npc][Drop] Ghostclaw Lynx)
[//]: # ([Web] Armory doesnt work)

**Description**: 
![image](https://user-images.githubusercontent.com/33141932/46555965-20375b00-c8b3-11e8-88c6-3511d8ce2a1a.png)
All of the Venomtail Scorpid here spawn on top of each other, right outside of Orgrimmar
**Current behaviour**:
There are 3 and 4 Venomtail Scorpid in each location, respectively.
**Expected behaviour**: 
There should be, at most, 1 Venomtail Scorpid in each of these locations
**Server Revision**: 
2131

**Comment by Evolvee** [comment]
https://github.com/Atlantiss/NetherwingBugtracker/issues/190
duplicate
