### ISSUE TITLE
[Movement][NPC]Theramore Sentry#5184 x2 missing patrols at North Point Tower

### ISSUE THREAD

**Issue by Tenoutoften** [Atlantiss/NetherwingBugtracker#1264]
**Description**:
Two [[NPC]Theramore Sentry#5184](https://db.excalibur.ws/?npc=5184) are missing patrols at North Point Tower in Dustwallow Marsh, .gps & npc info
![58049081dc78ea459f0cc1bf4d09a89c](https://user-images.githubusercontent.com/34839199/46557845-935cc380-c8eb-11e8-919a-5f070cdcd6b2.png)

Indicated by [wowhead comment (Patch 2.0.6)](https://www.wowhead.com/quest=9437/twilight-of-the-dawn-runner#comments:id=26077)
![ef838aacc9ec845fd1dd672b80320744](https://user-images.githubusercontent.com/34839199/46557883-b5564600-c8eb-11e8-9fca-a01b81ee55d7.png)

**Current behaviour**:
Zero patrols and some very "stock" looking NPCs. Current behavior video [here](https://www.youtube.com/watch?v=CK-fsY5RkoQ&feature=youtu.be)

**Expected behaviour**: 
Two [[NPC]Theramore Sentry#5184](https://db.excalibur.ws/?npc=5184) expected to patrol around the tower.

**Server Revision**: 
2130

**Comment by Evolvee** [comment]
rev Xd
