### ISSUE TITLE
[Quest] A matter of time.

### ISSUE THREAD

**Issue by Firroth** [Atlantiss/NetherwingBugtracker#1265]
[Quest] [A Matter of Time](https://www.wowhead.com/quest=4971/a-matter-of-time)

**Current behaviour**:
You can currently finish the quest on "1 silo" - meaning you can use q item required to summon npc's on only 1 object, which shouldn't be possible. 

![screenshot_3](https://user-images.githubusercontent.com/43505196/46558442-66111500-c8ed-11e8-9286-c898ac329c3c.png)

Mobs spawned currently from 1 silo are always in count of 3.

**Expected behaviour**: 
When using q item on silo, you should not be able to use q item on it again and it should loose glow effect.

Mobs spawned from 1 silo should be: 
1 minimum and 6 maximum from 1 silo.

![screenshot_4](https://user-images.githubusercontent.com/43505196/46558462-76c18b00-c8ed-11e8-9f8c-191bd69cfd6a.png)

![screenshot_5](https://user-images.githubusercontent.com/43505196/46558467-77f2b800-c8ed-11e8-8ca3-9311fd333773.png)

+ Video showing how spawning should be occuring, and silo only being used once per summon.
https://www.youtube.com/watch?v=StzjPVSif5Q

**Server Revision**: 
2130

**Comment by Evolvee** [comment]
1st part done.

todo: number of summoned mobs

**Comment by Evolvee** [comment]
rev 439kcolb

for potential future reopen:

dbc spells = 16619, 16630, 16631
