### ISSUE TITLE
Shouldn't be able to summon [NPC]Zelfrax#23864 while RP event is happening

### ISSUE THREAD

**Issue by Tenoutoften** [Atlantiss/NetherwingBugtracker#1266]
**Description**: 
Shouldn't be able to summon [[NPC]Zelfrax#23864](https://db.excalibur.ws/?npc=23864) with [[Item]Witchbane Torch#33113](https://db.excalibur.ws/?item=33113) for [[Quest]Cleansing Witch Hill#11183](https://db.excalibur.ws/?quest=11183) while [[NPC]Mordant Grimsby#23843](https://db.excalibur.ws/?npc=23843) and [[NPC]"Swamp Eye" Jarl#4792](https://db.excalibur.ws/?npc=4792) are in their RP event according to [wowhead comment (Patch 2.4.3)](https://www.wowhead.com/quest=11183/cleansing-witch-hill#comments:id=346373)
![7d0de002a2dd70e1952d9e3a6123ab13](https://user-images.githubusercontent.com/34839199/46559551-fa30ab80-c8f0-11e8-8d95-108c3eee9211.png)
![3eb582bf27fa679fa1be2e9fcf18a513](https://user-images.githubusercontent.com/34839199/46559619-2ba97700-c8f1-11e8-947a-876a0d6e4b93.png)
![ef4d9616bf67cad461cf7984346ba3dd](https://user-images.githubusercontent.com/34839199/46559622-2e0bd100-c8f1-11e8-844d-82de15f04074.png)

**Current behaviour**:
Currently able to summon [[NPC]Zelfrax#23864](https://db.excalibur.ws/?npc=23864) with [[Item]Witchbane Torch#33113](https://db.excalibur.ws/?item=33113) during the RP event. Making [[NPC]"Swamp Eye" Jarl#4792](https://db.excalibur.ws/?npc=4792) to death animation and get up again once he has another line. Video [here](https://www.youtube.com/watch?v=JvYo6GElH58&feature=youtu.be)

It also looks like if I start the summoning, they can start their event right after also a bit strange.

**Expected behaviour**: 
Shouldn't be able to summon  [[NPC]Zelfrax#23864](https://db.excalibur.ws/?npc=23864) with [[Item]Witchbane Torch#33113](https://db.excalibur.ws/?item=33113) during the RP event

**Server Revision**: 
2130

**Comment by Evolvee** [comment]
low priority for now
