### ISSUE TITLE
dueling- Player health visual bug.

### ISSUE THREAD

**Issue by staryfox** [Atlantiss/NetherwingBugtracker#1268]
[//]: # (Enclose links to things related to the bug using http://wowhead.com or any other TBC database.)
[//]: # (You can use screenshot ingame to visual the issue.)
[//]: # (Write your tickets according to the format:)
[//]: # ([Quest][Azuremyst Isle] Red Snapper - Very Tasty!)
[//]: # ([NPC] Magistrix Erona)
[//]: # ([Spell][Mage] Fireball)
[//]: # ([Npc][Drop] Ghostclaw Lynx)
[//]: # ([Web] Armory doesnt work)

**Description**: Player enemy health pool does not visually drain when dealing damage ( attacking player )
Player health drains when taking damage ( Damaged player )

**Current behaviour**: when dueling player can not see the opposing players health drain when dealing damage. health remains at 100% until execute point, then immediately drops to 10% before duel is finished. 

**Expected behaviour**: player health should drain at the point the damage is caused. 

**Server Revision**:

**Comment by Kidcudi123** [comment]
Well isnt this just spell delay

**Comment by xycz** [comment]
This is still an issue, to recreate, make a group, this is what I have found is the root of the cause, and have the members duel each other. 

Side note: Feign death does not drop target when in same group as the opponent you are dueling, but reactivates the health update
