### ISSUE TITLE
Sheep spell Advantage

### ISSUE THREAD

**Issue by ThriceFilter** [Atlantiss/NetherwingBugtracker#127]
[//]: # (Enclose links to things related to the bug using http://wowhead.com or any other TBC database.)
[//]: # (You can use screenshot ingame to visual the issue.)
[//]: # (Write your tickets according to the format:)
[//]: # ([Quest][Azuremyst Isle] Red Snapper - Very Tasty!)
[//]: # ([NPC] Magistrix Erona)
[//]: # ([Spell][Mage] Fireball)
[//]: # ([Npc][Drop] Ghostclaw Lynx)
[//]: # ([Web] Armory doesnt work)

**Description**: 
Polymorph is failing to aggro the neighboring mob

**Current behaviour**:

**Expected behaviour**: 
Polly morph should be able to aggro a nearby mob 
**Server Revision**:

**Comment by Wolffenstein** [comment]
Nope. If you have any proof for it please post it and reopen the issue. According to our sources it should not until the Polymorph ends.

**Comment by killablink** [comment]
Sheeping a mob next to another mob definitely aggros the other mob. It was changed to not aggro somewhere in retail in WoD~ or legion. It starts aggro at cast and not when it ends. I only played tbc and wotlk and when I restarted for BfA I was actually surprised that poly doesn't aggro mobs anymore (I've played mage TBC and wotlk all my life rank 1 in BG, I know what I'm talking about. I can try to find a clip but he is definitely right.)

**Comment by killablink** [comment]
https://wow.gamepedia.com/Sheep_pull

This was a thing. We always used to pull group of mobs by sheeping in dungeons and raids

**Comment by Dpthx** [comment]
I think this needs clarification. Are you saying that mobs WITHIN assist range don't aggro when you polymorph one of them? Or are you saying that mobs that wander within the assist range of the ALREADY polyed target don't aggro?

**Comment by knasen88** [comment]
They should aggro on pull afaik, but not if a random patrol walks into your already sheeped mob nothing happens (unless it breaks at the same time)
