### ISSUE TITLE
[NPC] Mistress Natalia Mar'Alith - Charming player in a 1vs1 fight

### ISSUE THREAD

**Issue by wowthings** [Atlantiss/NetherwingBugtracker#1272]
[//]: # (Enclose links to things related to the bug using http://wowhead.com or any other TBC database.)
[//]: # (You can use screenshot ingame to visual the issue.)
[//]: # (Write your tickets according to the format:)
[//]: # ([Quest][Azuremyst Isle] Red Snapper - Very Tasty!)
[//]: # ([NPC] Magistrix Erona)
[//]: # ([Spell][Mage] Fireball)
[//]: # ([Npc][Drop] Ghostclaw Lynx)
[//]: # ([Web] Armory doesnt work)

**Description**: 
[This lady](https://www.wowhead.com/npc=15215/mistress-natalia-maralith) from Silithus is an objective of [Into the Maw of Madness](https://www.wowhead.com/quest=8306/into-the-maw-of-madness) and she's guarding another objective for [Glyph Chasing](https://www.wowhead.com/quest=8309/glyph-chasing). 
If you are in a party of 2 or more she casts mind control to one of you...
**Current behaviour**:
But she's casting it anyway in a 1vs1 fight. And since there's none around she immediately evades the fight. Currently you can't finish 2 quests unless you bring someone with you.
Video:
https://streamable.com/65y5f
**Expected behaviour**: 
No mind control when going alone.
**Server Revision**: 
2130

**Comment by Evolvee** [comment]
rev Xd
