### ISSUE TITLE
[NPC] Kreenig Snarlsnout incorrect position/patrol

### ISSUE THREAD

**Issue by Sunlancer** [Atlantiss/NetherwingBugtracker#1275]
[//]: # (Enclose links to things related to the bug using http://wowhead.com or any other TBC database.)
[//]: # (You can use screenshot ingame to visual the issue.)
[//]: # (Write your tickets according to the format:)
[//]: # ([Quest][Azuremyst Isle] Red Snapper - Very Tasty!)
[//]: # ([NPC] Magistrix Erona)
[//]: # ([Spell][Mage] Fireball)
[//]: # ([Npc][Drop] Ghostclaw Lynx)
[//]: # ([Web] Armory doesnt work)

**Description**: 
![image](https://user-images.githubusercontent.com/33141932/46564569-0c512080-c8d6-11e8-8cdc-5e6a58110d25.png)
Kreenig Snarlsnout is moving around when he is a quest mob that is not supposed to
**Current behaviour**:
Kreenig Snarlsnout (Entry 3438, Id 1, GUIDLow 20205) is moving around and a Razormane Mystic (Entry 3271, Id 1, GUIDLow 20203) is in his place, not moving.
**Expected behaviour**: 
Kreenig Snarlsnout should not be moving, in a specific location, and Razormane Mystic should be doing something similar to his patrol
**Server Revision**: 
2131

**Comment by aresbrutus** [comment]
https://i.imgur.com/T39JsxA.png
