### ISSUE TITLE
[Object][Silithus] Silithyst Geyser - can't pick up

### ISSUE THREAD

**Issue by wowthings** [Atlantiss/NetherwingBugtracker#1277]
[//]: # (Enclose links to things related to the bug using http://wowhead.com or any other TBC database.)
[//]: # (You can use screenshot ingame to visual the issue.)
[//]: # (Write your tickets according to the format:)
[//]: # ([Quest][Azuremyst Isle] Red Snapper - Very Tasty!)
[//]: # ([NPC] Magistrix Erona)
[//]: # ([Spell][Mage] Fireball)
[//]: # ([Npc][Drop] Ghostclaw Lynx)
[//]: # ([Web] Armory doesnt work)

**Description**: 
Collecting [Silithyst](https://www.wowhead.com/object=181598/silithyst-geyser) will result in a debuff that slows the character's speed considerably. 
 If you run to your faction's silithyst machine with the aura on you, you gain 10 rep with Cenarion Circle and the Traces of Silithyst buff. The buff increases all damage caused by 5% for 30 minutes.
**Current behaviour**:
No debuff when right clicking this object.
https://streamable.com/gm96m
**Expected behaviour**: 
Right clicking it should give to your character a debuff that slows you down. 
Video evidence 
https://youtu.be/nI6VATVpN8Y?t=113
**Server Revision**: 
2130

**Comment by ttghnw** [comment]
still broken

**Comment by Vyriam** [comment]
This quest/object pick-up is still broken as of patch 2.2

Server Revision : 3119

**Comment by Godmatik** [comment]
Rev 4015 no longer an issue.
Able to pick up and transport the Silithyst
