### ISSUE TITLE
[Quest] Defenders of Darrowshire

### ISSUE THREAD

**Issue by mbzz88** [Atlantiss/NetherwingBugtracker#1278]
**Description**: Spam clicking the spirits that spawn www.wowhead.com/npc=11064 results in multiple quest tally increases
www.wowhead.com/quest=5211

**Current behaviour**: Multiple quest tally increases per mob
https://youtu.be/ZIHfFDMQ2Eg

**Expected behaviour**: 1 per mob

**Server Revision**: 2130

**Comment by Evolvee** [comment]
cant reproduce but i made some adjustments so it gives hopefully only 1 credit per NPC now

rev hehexd
