### ISSUE TITLE
Trogg stone Teeth drop Rate

### ISSUE THREAD

**Issue by ThriceFilter** [Atlantiss/NetherwingBugtracker#128]
[//]: # (Enclose links to things related to the bug using http://wowhead.com or any other TBC database.)
[//]: # (You can use screenshot ingame to visual the issue.)
[//]: # (Write your tickets according to the format:)
[//]: # ([Quest][Azuremyst Isle] Red Snapper - Very Tasty!)
[//]: # ([NPC] Magistrix Erona)
[//]: # ([Spell][Mage] Fireball)
[//]: # ([Npc][Drop] Ghostclaw Lynx)
[//]: # ([Web] Armory doesnt work)

**Description**:  The trogg stone teeth drop rate in loch modan is definetly too low

**Current behaviour**:
I have finished the first defenind the kings lands an still have only 2 trogg stone teeth to show for it
**Expected behaviour**: 
The teeth are supposed to have a higher drop rate 

**Server Revision**:

**Comment by jeff1736** [comment]
All of the 3 drop quests in Loch Modan I completed took ages in a completely empty zone. Rat ears, bear meat, and boar intestines also need far higher drop rate.

**Comment by aresbrutus** [comment]
Slightly increased drop rate in next rev. Please post seperate issues about drop rates @jeff1736
