### ISSUE TITLE
Frostsaber Stalker, Winterspring

### ISSUE THREAD

**Issue by Erodraeda** [Atlantiss/NetherwingBugtracker#1280]
[//]: # (Enclose links to things related to the bug using http://wowhead.com or any other TBC database.)
[//]: # (You can use screenshot ingame to visual the issue.)
[//]: # (Write your tickets according to the format:)
[//]: # ([Quest][Azuremyst Isle] Red Snapper - Very Tasty!)
[//]: # ([NPC] Magistrix Erona)
[//]: # ([Spell][Mage] Fireball)
[//]: # ([Npc][Drop] Ghostclaw Lynx)
[//]: # ([Web] Armory doesnt work)

**Description**: 
They should be stealthed around. mob is Entry: 7432, ID 21
**Current behaviour**:
![screenshot_589](https://user-images.githubusercontent.com/40346279/46567803-3a535680-c910-11e8-9b5b-2c9598894e37.png)
**Expected behaviour**: 
They should be stealthed.
**Server Revision**:

**Comment by Evolvee** [comment]
thats pretty weird, they are stealthed for me, i slightly tweaked it in rev Xd, but still... pretty weird

**Comment by totaemoeggerli** [comment]
they are bugged again
they go into stealth if you reset them but aren't stealthed normaly
https://gfycat.com/upload/results

**Comment by Evolvee** [comment]
@Wolffenstein FeelsWeirdMan

**Comment by The14me** [comment]
Work just fine now.Please re-open if seen it happen again.
