### ISSUE TITLE
[Item]Unpopped Darkmist Eye should have 95% drop chance

### ISSUE THREAD

**Issue by Tenoutoften** [Atlantiss/NetherwingBugtracker#1281]
**Description**: 
[[Item]Unpopped Darkmist Eye](https://db.excalibur.ws/?item=5884) should have 95% drop chance of

* [[NPC]Darkmist Spider#4376](https://db.excalibur.ws/?npc=4376)
* [[NPC]Darkmist Recluse#4378](https://db.excalibur.ws/?npc=4378)
* [[NPC]Darkmist Silkspinner#4379](https://db.excalibur.ws/?npc=4379)
* [[NPC]Darkmist Widow#4380](https://db.excalibur.ws/?npc=4380)

But [[NPC]Darkmist Hatchling#5884](https://db.excalibur.ws/?npc=4377) who is spawned by [[NPC]Darkmist Widow#4380](https://db.excalibur.ws/?npc=4380) using [[Spell]Hatch Spiderlings#43134](https://db.excalibur.ws/?spell=43134) should probably not drop(Fought two, zero dropped)

Indicated by [wowhead comments](https://www.wowhead.com/quest=1206/jarl-needs-eyes#comments):
![3bbc7ba7bca5104cdfb3773ea61289a4](https://user-images.githubusercontent.com/34839199/46568436-3a217e00-c945-11e8-87d6-46c45be3717d.png)
![d0d09d41336f8f0c06d324abfb29bebf](https://user-images.githubusercontent.com/34839199/46568439-3aba1480-c945-11e8-9213-561bda5d817e.png)
![e822d4a34de067872b89a9ca491f22b4](https://user-images.githubusercontent.com/34839199/46568440-3aba1480-c945-11e8-81cf-85ef222a0751.png)
![eea63b11a086ed28a7366736cff33ab0](https://user-images.githubusercontent.com/34839199/46568441-3aba1480-c945-11e8-85a6-c585a25ed03a.png)

.gps:
![69c72e0f75f64d7c9e94348bb466bc9b](https://user-images.githubusercontent.com/34839199/46568519-8faa5a80-c946-11e8-9ce9-82371cd8e671.png)

**Current behaviour**:
Definitely not 95% drop chance or higher.
![79cb71bffea33dce27594330e011b3bd](https://user-images.githubusercontent.com/34839199/46568438-3aba1480-c945-11e8-9931-7a996c432e3f.png)

**Expected behaviour**: 
Expect at least 95% drop chacne

**Server Revision**: 
2130

**Comment by aresbrutus** [comment]
Fixed in one of the next updates.
