### ISSUE TITLE
[NPC] [spell] Ivar the Foul// Foul Odor passive aura

### ISSUE THREAD

**Issue by Dusky1** [Atlantiss/NetherwingBugtracker#1284]
**Description**: This guy seem to have some OP DPS aura. Strange it was, on my seccond attempt he didnt use that aura anymore

**Current behaviour**: his aura was ticking 7x per seccond
![ivar the foul](https://user-images.githubusercontent.com/17127512/46568881-9e940b80-c94c-11e8-9e0e-4b2ec91823ac.jpg)

**Server Revision**:  2130

**Comment by Evolvee** [comment]
@Wolffenstein same as the zombie in EP, problem is passive aura ticking too fast than its supposed to

**Comment by Evolvee** [comment]
should already be fixed @Wolffenstein ?

**Comment by Evgenyx123** [comment]
![ivar the fool](https://user-images.githubusercontent.com/44301820/47238378-4811dd00-d3e2-11e8-85f2-7768d41d619e.jpg)
The aura did 40 attacks per second to me.

**Comment by The14me** [comment]
Look fine to me,Please Pm if still bugged to re-open.

**Comment by The14me** [comment]
The first time when I try to reproduce it--->bugged. After that, I can't reproduce it anymore.

**Comment by Wolffenstein** [comment]
Fixed in rev 3368.
