### ISSUE TITLE
[NPC][Western Plaguelands] Skeletal Flayer - Stuck in place.

### ISSUE THREAD

**Issue by Firroth** [Atlantiss/NetherwingBugtracker#1286]
[NPC] [Skeletal Flayer](https://www.wowhead.com/npc=1783/skeletal-flayer)

GPS:
![screenshot_1](https://user-images.githubusercontent.com/43505196/46570263-c17cea80-c961-11e8-9536-4158454f7e6c.png)

**Current behaviour**:
As seen on gif this NPC is stuck and can't move towards the player, and looses combat cause of it every 4s

![2018-10-06_12-08-44](https://user-images.githubusercontent.com/43505196/46570250-87abe400-c961-11e8-9c9f-de578a4a528a.gif)

**Expected behaviour**: 
He should normally run to the player and engage in meele combat.

**Server Revision**: 
2130

**Comment by Evolvee** [comment]
rev Xd
