### ISSUE TITLE
[NPC][Western Plaguelands] Searing Ghoul - Fire shield.

### ISSUE THREAD

**Issue by Firroth** [Atlantiss/NetherwingBugtracker#1288]
[NPC] [Searing Ghoul](https://www.wowhead.com/npc=1795/searing-ghoul)
[Spell] [Fire Shield ](https://classicdb.ch/?spell=19627)

**Current behaviour**:
They don't have [Spell] [Fire Shield ](https://classicdb.ch/?spell=19627) in their arsenal.

**Expected behaviour**: 
They should have [Spell] [Fire Shield ](https://classicdb.ch/?spell=19627)

![screenshot_3](https://user-images.githubusercontent.com/43505196/46570321-9ba41580-c962-11e8-9d5d-8cbb1a9275c1.png)

![screenshot_2](https://user-images.githubusercontent.com/43505196/46570322-9cd54280-c962-11e8-9763-75403506feba.png)

**Server Revision**: 
2130

**Comment by Evolvee** [comment]
@Easyfraggy bestiary link pls

**Comment by Evolvee** [comment]
rev Xd
