### ISSUE TITLE
Unable to buff/heal [NPC]"Stinky" Ignatz#4880

### ISSUE THREAD

**Issue by Tenoutoften** [Atlantiss/NetherwingBugtracker#1289]
**Description**: 
[[NPC]"Stinky" Ignatz#4880](https://db.excalibur.ws/?npc=4880) doesn't receive any helpful buffs from players, both inside and outside of the escort quest [[Quest]Stinky's Escape#1270](https://db.excalibur.ws/?quest=1270)

Video [here](https://youtu.be/aE5VRy8tzso?t=17) for the full quest [here](https://www.youtube.com/watch?v=aE5VRy8tzso&feature=youtu.be)

**Expected behaviour**: 
Expected to be able to heal / buff [[NPC]"Stinky" Ignatz#4880](https://db.excalibur.ws/?npc=4880)

**Server Revision**: 
2130

**Comment by Evolvee** [comment]
timestamp?

**Comment by Tenoutoften** [comment]
https://youtu.be/aE5VRy8tzso?t=17

**Comment by Tenoutoften** [comment]
This is covered in https://github.com/Atlantiss/NetherwingBugtracker/issues/3678
