### ISSUE TITLE
Moving out of range of spells

### ISSUE THREAD

**Issue by Dajmills** [Atlantiss/NetherwingBugtracker#129]
[//]: # (Enclose links to things related to the bug using http://wowhead.com or any other TBC database.)
[//]: # (You can use screenshot ingame to visual the issue.)
[//]: # (Write your tickets according to the format:)
[//]: # ([Quest][Azuremyst Isle] Red Snapper - Very Tasty!)
[//]: # ([NPC] Magistrix Erona)
[//]: # ([Spell][Mage] Fireball)
[//]: # ([Npc][Drop] Ghostclaw Lynx)
[//]: # ([Web] Armory doesnt work)

**Description**: There should be some leniency when a target moves out of spell range while casting

**Current behaviour**: If the target moves out of range during spell cast then the spell fails

**Expected behaviour**: The spell casts correctly as long as the target does not move a large distance out of range

**Server Revision**:

**Comment by Wolffenstein** [comment]
Already reported.
