### ISSUE TITLE
[Movement][NPC]Mirefin Coastrunner#4362 x2 missing patrol

### ISSUE THREAD

**Issue by Tenoutoften** [Atlantiss/NetherwingBugtracker#1290]
**Description**: 
[[NPC]Mirefin Coastrunner#4362](https://db.excalibur.ws/?npc=4362) doesn't patrol around the shore as seen on https://youtu.be/csiAxwdWQp4?t=34 this might be the same [[NPC]Mirefin Coastrunner#4362](https://db.excalibur.ws/?npc=4362) appearing in another video here, slightly different place: https://youtu.be/YjALnCJf02U?t=120
![bda449735d44ebe2999d686ff0649d79](https://user-images.githubusercontent.com/34839199/46570498-5d5c2580-c965-11e8-8022-5da35d27c7a8.png)

Second patrol seen here(also a [[NPC]Mirefin Coastrunner#4362](https://db.excalibur.ws/?npc=4362)): https://youtu.be/csiAxwdWQp4?t=76 and reappears here https://youtu.be/csiAxwdWQp4?t=98 appears here in another video: https://youtu.be/YjALnCJf02U?t=85

Suppose to be "a lot of patrols around here" according to https://youtu.be/YjALnCJf02U?t=34

**Current behaviour**:
Zero patrols around this specific shore

**Expected behaviour**: 
Expecting at least one patrol around here.

**Server Revision**: 
2130

**Comment by aresbrutus** [comment]
Fixed in one of the next updates.
