### ISSUE TITLE
[Spell][Aura] Corrupted Strength

### ISSUE THREAD

**Issue by Xynaps** [Atlantiss/NetherwingBugtracker#1292]
**Description**: Foulweald Warrior(3743) aura, Corrupted Strength, seems to be applied multiple times per tick. 
This causes the combat log to be spammed with both applied / resist messages.  

**Current behaviour**: Aura is cast effect multiple times.

**Expected behaviour**:  Attempts to apply aura ones per tick. 

**Server Revision**: 2130

![foulweald](https://user-images.githubusercontent.com/5638385/46570617-28e96900-c967-11e8-8c82-f5bdfe4d3e7e.png)

**Comment by Evolvee** [comment]
@Wolffenstein same problem as other passive auras... tick way faster than they supposed to be

they all have periodic time 3000ms

**Comment by Evolvee** [comment]
@Wolffenstein maybe "on reset" event makes this aura stack on top of each other somehow?

**Comment by Evolvee** [comment]
should already be fixed @Wolffenstein ?
