### ISSUE TITLE
[Item][Un'goro Crater]Power Crystals

### ISSUE THREAD

**Issue by DeltaLoads** [Atlantiss/NetherwingBugtracker#1293]
[//]: # (Enclose links to things related to the bug using http://wowhead.com or any other TBC database.)
[//]: # (You can use screenshot ingame to visual the issue.)
[//]: # (Write your tickets according to the format:)
[//]: # ([Quest][Azuremyst Isle] Red Snapper - Very Tasty!)
[//]: # ([NPC] Magistrix Erona)
[//]: # ([Spell][Mage] Fireball)
[//]: # ([Npc][Drop] Ghostclaw Lynx)
[//]: # ([Web] Armory doesnt work)

**Description**: 
Power Crystals of all colors can be found empty all over the zone and dont despawn when looted
![wowscrnshot_100618_131858](https://user-images.githubusercontent.com/43690147/46570818-9c40aa00-c96a-11e8-9611-1948f82a1e44.jpg)
![wowscrnshot_100618_132101](https://user-images.githubusercontent.com/43690147/46570822-b11d3d80-c96a-11e8-8a2a-c2b950913895.jpg)

**Current behaviour**:
Power Crystals are mostly empty and dont respawn
**Expected behaviour**: 
Power Crystals shouldn't be able to be looted once they are empty and should despawn
**Server Revision**: 
2130

**Comment by The14me** [comment]
Maybe related to empty chest issue's.

**Comment by Tenoutoften** [comment]
Based on what I have seen on other servers, all party members will be able to loot the same crystal before it despawns - Perhaps what happened was that someone was in party looting crystals in Un'goro while other party members didn't, perhaps because they weren't even there? Just a guess...

**Comment by Shanghi** [comment]
This should be fixed in revision 2175.

You were right, Tenoutoften!
