### ISSUE TITLE
[The Deadmines] Issues

### ISSUE THREAD

**Issue by Firroth** [Atlantiss/NetherwingBugtracker#1294]
# <h1>[NPC] [Defias Evoker](https://www.wowhead.com/npc=1729/defias-evoker#comments)</h1>

[Spell] [Quick Flame Ward](https://classicdb.ch/?spell=4979)

**Current behaviour**:
Doesn't seem to use [Spell] [Quick Flame Ward](https://classicdb.ch/?spell=4979), waited 1minute and still nothing.

**Expected behaviour**: 
Should be using [Spell] [Quick Flame Ward](https://classicdb.ch/?spell=4979)

![screenshot_1](https://user-images.githubusercontent.com/43505196/46571641-cc8f4500-c978-11e8-99dd-1599ce262642.png)

![screenshot_2](https://user-images.githubusercontent.com/43505196/46571664-48898d00-c979-11e8-9776-eb347d46a50f.png)

**Server Revision**: 
2130

**---------------------------------------------------------------------------------------------------------**

# <h1>[NPC] [Defias Overseer](https://www.wowhead.com/npc=634/defias-overseer)</h1>

[Spell] [Battle Command](https://www.wowhead.com/spell=5115/battle-command)
[Spell] [Pierce]()

**Current behaviour**:
Doesn't seem to use [Spell] [Battle Command](https://www.wowhead.com/spell=5115/battle-command), waited 1minute and still nothing.

**Expected behaviour**: 
Should be using [Spell] [Battle Command](https://www.wowhead.com/spell=5115/battle-command)

Also according to [Allkhazam](https://web.archive.org/web/20100330163327/http://wow.allakhazam.com:80/db/spell.html?wspell=6016) he should be using [Spell] [Pierce](https://web.archive.org/web/20100330163327/http://wow.allakhazam.com:80/db/spell.html?wspell=6016).

**Server Revision**: 
2130

**---------------------------------------------------------------------------------------------------------**

# <h1>[NPC] [Defias Wizard](https://web.archive.org/web/20090417052234/http://wow.allakhazam.com:80/db/mob.html?wmob=4418)</h1>

[Spell] [Quick Flame Ward](https://classicdb.ch/?spell=4979)
[Spell] [Flamestrike](https://web.archive.org/web/20090417025744/http://wow.allakhazam.com:80/db/spell.html?wspell=2120)

**Current behaviour**:
Doesn't seem to use [Spell] [Quick Flame Ward](https://classicdb.ch/?spell=4979), waited 1minute and still nothing.

**Expected behaviour**: 
Should be using [Spell] [Quick Flame Ward](https://classicdb.ch/?spell=4979)

Also according to [Allkhazam](https://web.archive.org/web/20090417025744/http://wow.allakhazam.com:80/db/spell.html?wspell=2120) he should be using [Spell] [Flamestrike](https://web.archive.org/web/20090417025744/http://wow.allakhazam.com:80/db/spell.html?wspell=2120)

**Server Revision**: 
2130

**Comment by Firroth** [comment]
Here you go then, found 1 more. Everything else like patrols etc. / events works flawless. Not sure about loot though since I skipped a lot of mobs and still went out with 14 green items.

# <h1>[NPC] [Defias Wizard](https://web.archive.org/web/20090417052234/http://wow.allakhazam.com:80/db/mob.html?wmob=4418)</h1>


[Spell] [Quick Flame Ward](https://classicdb.ch/?spell=4979)
[Spell] [Flamestrike](https://web.archive.org/web/20090417025744/http://wow.allakhazam.com:80/db/spell.html?wspell=2120)

**Current behaviour**:
Doesn't seem to use [Spell] [Quick Flame Ward](https://classicdb.ch/?spell=4979), waited 1minute and still nothing.

**Expected behaviour**: 
Should be using [Spell] [Quick Flame Ward](https://classicdb.ch/?spell=4979)

Also according to [Allkhazam](https://web.archive.org/web/20090417025744/http://wow.allakhazam.com:80/db/spell.html?wspell=2120) he should be using [Spell] [Flamestrike](https://web.archive.org/web/20090417025744/http://wow.allakhazam.com:80/db/spell.html?wspell=2120)

**Server Revision**: 
2130

**Comment by Evolvee** [comment]
rev Xd

**Comment by Evolvee** [comment]
rev hehexd
