### ISSUE TITLE
Fetid Zombie - Contagion of Rot

### ISSUE THREAD

**Issue by Mewmewww** [Atlantiss/NetherwingBugtracker#1295]
[//]: # (Enclose links to things related to the bug using http://wowhead.com or any other TBC database.)
[//]: # (You can use screenshot ingame to visual the issue.)
[//]: # (Write your tickets according to the format:)
[//]: # ([Quest][Azuremyst Isle] Red Snapper - Very Tasty!)
[//]: # ([NPC] Magistrix Erona)
[//]: # ([Spell][Mage] Fireball)
[//]: # ([Npc][Drop] Ghostclaw Lynx)
[//]: # ([Web] Armory doesnt work)

**Description**: It seems the aura is stacked around 10 times so if you go in its poison radius, you get hit 10 times every second

**Current behaviour**: Do not go close to him, you will take 25 dmg * 10 every second https://imgur.com/a/hZfvdFT

**Expected behaviour**: Should not be this excessive. 

**Server Revision**: 2130

**Comment by The14me** [comment]
NPC ID 10580

**Comment by Evolvee** [comment]
@Wolffenstein same issue as other periodic passive auras....

global problem

**Comment by Evolvee** [comment]
should already be fixed @Wolffenstein ?

**Comment by Tenoutoften** [comment]
@Evolvee not fixed

**Comment by Frankenberryberry** [comment]
I think this is also what caused this:
https://imgur.com/a/tdRBAbb

Got 2 stacks of Contagion of Rot on the final bit of the "Legend of Stalvan" quest line in Duskwood.
Instead of reducing attack speed by 33% it stacks so I had 66%. Don't know if it can stack even higher than x2 and possibly reduce attack speed even further.

**Comment by The14me** [comment]
Work fine for me now.Re-open if happen again.

**Comment by killablink** [comment]
Getting multiple stacks of Contagion of Rot, increasing spellcast time by more than 50%+.
Should only have 1 debuff, and get refreshed

**Comment by Tereneckla** [comment]
Fixed (The OP also used the wrong spell name, so the comment about this contagion of was misplaced)
