### ISSUE TITLE
[NPC]Gyll#2859, alliance Booty Bay Gyrphon master slightly misplaced

### ISSUE THREAD

**Issue by Tenoutoften** [Atlantiss/NetherwingBugtracker#1296]
**Description**: 
[[NPC]Gyll#2859](https://db.excalibur.ws/?npc=2859) looks to be slightly misplaced:
![8fc5012cffd935dfd1fe0713f36a12cb](https://user-images.githubusercontent.com/34839199/46572385-1d0c9f80-c985-11e8-8a0d-30245c786f09.jpg)
![a133f0c6f12eee2ca7f4fda5e732b166](https://user-images.githubusercontent.com/34839199/46572387-2d247f00-c985-11e8-9a26-f86a96167737.png)

**Expected behaviour**: 
Expect him to be here:
https://youtu.be/Epwtmd5YiZw?t=23

**Server Revision**: 
2130

**Comment by Evolvee** [comment]
rev Xd
