### ISSUE TITLE
[NPC][Blackrock Depths] High Interrogator Gerstahn - Mana Burn

### ISSUE THREAD

**Issue by Firroth** [Atlantiss/NetherwingBugtracker#1299]
[NPC] [High Interrogator Gerstahn](https://www.wowhead.com/npc=9018/high-interrogator-gerstahn)
[Spell] [Mana Burn](https://www.wowhead.com/spell=14033/mana-burn)

**Current behaviour**:
She casts it on people even without mana pool (warrior/druid in bear form) etc.

**Expected behaviour**: 
She should only cast this ability on players with mana pool.

**Server Revision**: 
2132

**Comment by Evolvee** [comment]
rev Xd
