### ISSUE TITLE
Being bandaged by another player interrupts eating/drinking

### ISSUE THREAD

**Issue by manslaughter** [Atlantiss/NetherwingBugtracker#130]
**Description**: When you are eating or drinking, if another player uses first aid on you, your eat/drink is interrupted and you stand up.

**Current behaviour**: "

**Expected behaviour**: You continue to eat/drink while they bandage you.

**Server Revision**: 2028

**Comment by Tenoutoften** [comment]
Figured I'd comment that this is still happening in rev 2395

**Comment by Wolffenstein** [comment]
Fixed in rev 2486.

**Comment by killablink** [comment]
Bugged again, standing up when bandaged by a player.
