### ISSUE TITLE
[RP EVENT][Blackrock Depths] Ring of Law - Gate

### ISSUE THREAD

**Issue by Firroth** [Atlantiss/NetherwingBugtracker#1300]
**Current behaviour**:
When party wipes on the Ring of Blood event, gate will remain closed, making another attempts on it impossible. Only solution is to reset instance.

![screenshot_4](https://user-images.githubusercontent.com/43505196/46573569-77166080-c997-11e8-8bf2-77c02d5d6b90.png)

**Expected behaviour**: 
If party wins/wipes gate entrance should open, letting players leave/enter by it.

**Server Revision**: 
2132

**Comment by Tereneckla** [comment]
Fixed
