### ISSUE TITLE
[NPC] Vesprystus - bad position.

### ISSUE THREAD

**Issue by Firroth** [Atlantiss/NetherwingBugtracker#1301]
[NPC] [Vesprystus](https://www.wowhead.com/npc=3838/vesprystus)

**Current behaviour**:
He is standing in bad position.

![screenshot_5](https://user-images.githubusercontent.com/43505196/46573876-40dae000-c99b-11e8-8363-0312721aa722.png)

**Expected behaviour**: 
He should be standing like on the screen, more to the edge.

![screenshot_7](https://user-images.githubusercontent.com/43505196/46574007-3de0ef00-c99d-11e8-85c9-d4c4fe4f13c7.png)

**Server Revision**: 
2132

**Comment by Evolvee** [comment]
rev Xd
