### ISSUE TITLE
[NPC] Wretched Thug/Wretched Hooligan

### ISSUE THREAD

**Issue by CeldorZ** [Atlantiss/NetherwingBugtracker#1302]
Wretched Thug/Wretched Hooligan in Eversong Woods
**Description**: 
Both NPCs aren't casting/using their skills.

**Current behaviour**:
Both NPCs aren't casting/using their skills.

**Expected behaviour**: 
They should cast/use Sinester Strike/ Bitter Withdrawal
https://www.wowhead.com/spell=29098/bitter-withdrawal (here is the link in WOWHead)
**Server Revision**:

**Comment by Evolvee** [comment]
rev Xd

**Comment by Evolvee** [comment]
they do cast these abilities on me btw, i just tweaked timers

**Comment by CeldorZ** [comment]
> they do cast these abilities on me btw, i just tweaked timers

Lol, :s they don't cast on me, maybe cause i'm playing rogue (no mana) :s
