### ISSUE TITLE
[Core mechanic] Stealth triggers wierd mob behaviour if used at close time/distance proximity to entering combat

### ISSUE THREAD

**Issue by Maelareth** [Atlantiss/NetherwingBugtracker#1305]
[//]: # (Enclose links to things related to the bug using http://wowhead.com or any other TBC database.)
[//]: # (You can use screenshot ingame to visual the issue.)
[//]: # (Write your tickets according to the format:)
[//]: # ([Quest][Azuremyst Isle] Red Snapper - Very Tasty!)
[//]: # ([NPC] Magistrix Erona)
[//]: # ([Spell][Mage] Fireball)
[//]: # ([Npc][Drop] Ghostclaw Lynx)
[//]: # ([Web] Armory doesnt work)

**Description**: When using stealth at close time proximity to entering combat, close mobs will run towards the character, exit combat and wonder around/go back to original state.

**Current behaviour**: When using stealth at close time proximity to entering combat, close mobs will run towards the character, exit combat and wonder around/go back to original state.

**Expected behaviour**: If stealth is triggered before entering combat the character should not enter combat. If combat is entered before stealth then stealth should not be able to trigger. At this moment some sort of mash up is possible. 

![untitled3](https://user-images.githubusercontent.com/10581286/46574864-ca45de80-c9aa-11e8-9ccc-0971c6fa6d35.gif)

**Server Revision**: 2135

**Comment by wtRCH** [comment]
Closing due to already being reported.
https://github.com/Atlantiss/NetherwingBugtracker/issues/295
