### ISSUE TITLE
[Spell][Mage] Frostbite

### ISSUE THREAD

**Issue by Thorgrimme** [Atlantiss/NetherwingBugtracker#1306]
[//]: # http://db.hellfire-tbc.com/?spell=12497

[//]: # ([Spell][Mage] Frostbite

**Description**: Frostbite doesn't seem to proc as much as it should.

**Current behaviour**: I don't have any solid data, but been having 3/3 pts into frostbite for 4 lvls now, and it seems to proc way less then it should. Casted roughly 100 frostbolts recenly while i've been tracking it, and seen it proc twice. And the general feel the past 4 lvls is that it rarely procs.

**Expected behaviour**: Gives your Chill effects a 15% chance to freeze the target for 5 sec.

**Server Revision**:

**Comment by Wolffenstein** [comment]
I guarantee it has proper proc chance.

**Comment by Thorgrimme** [comment]
Well it surely doesn't feel like it after playing with it for 28 lvls, but i have no way to track it since it doesnt show up on my dpsmate.
