### ISSUE TITLE
[Dungeon] Razorfen Downs looking through walls when zooming out

### ISSUE THREAD

**Issue by Mikik3jr** [Atlantiss/NetherwingBugtracker#1307]
[//]: # (Enclose links to things related to the bug using http://wowhead.com or any other TBC database.)
[//]: # (You can use screenshot ingame to visual the issue.)
[//]: # (Write your tickets according to the format:)
[//]: # ([Quest][Azuremyst Isle] Red Snapper - Very Tasty!)
[//]: # ([NPC] Magistrix Erona)
[//]: # ([Spell][Mage] Fireball)
[//]: # ([Npc][Drop] Ghostclaw Lynx)
[//]: # ([Web] Armory doesnt work)

**Description**: 
If you are in a place where the celling is close to you, when you look down and zoom out you will see over everything like this:
![wowscrnshot_100618_123547](https://user-images.githubusercontent.com/43505031/46575151-2828f500-c9b0-11e8-971d-903eb7803247.jpg)
**Current behaviour**:
Most of the places where the celling is low and you zoom out you see everything like I showed above
**Expected behaviour**: 
Actually I don't know. Tsu told me to report this anyway just in case.
**Server Revision**: 
2135

**Comment by Easyfraggy** [comment]
Client issue afaik.
