### ISSUE TITLE
[NPC] Wastewanderer Rogue not stealthed

### ISSUE THREAD

**Issue by totaemoeggerli** [Atlantiss/NetherwingBugtracker#1309]
[//]: # (Enclose links to things related to the bug using http://wowhead.com or any other TBC database.)
[//]: # (You can use screenshot ingame to visual the issue.)
[//]: # (Write your tickets according to the format:)
[//]: # ([Quest][Azuremyst Isle] Red Snapper - Very Tasty!)
[//]: # ([NPC] Magistrix Erona)
[//]: # ([Spell][Mage] Fireball)
[//]: # ([Npc][Drop] Ghostclaw Lynx)
[//]: # ([Web] Armory doesnt work)

**Description**: 
https://www.wowhead.com/npc=5615/wastewander-rogue#comments
NPC should be stealthed.

**Current behaviour**:
NPC isn't stealthed.

Edit:
![stalker](https://imgur.com/R8JL0xc.jpg)

**Expected behaviour**: 
By entropicdragon (58,420 – 12·73·452) on 2007/01/09 (Patch 2.0.3)
>These guys wander around stealthed, so keep an ear open for the detect noise when you're in the area :-)

**Server Revision**: 2135

**Comment by Evolvee** [comment]
@Wolffenstein 
.... they are stealthed

**Comment by Wolffenstein** [comment]
Fixed in rev 2138.
