### ISSUE TITLE
[NPC] Silvermane Stalker isn't stealthed

### ISSUE THREAD

**Issue by totaemoeggerli** [Atlantiss/NetherwingBugtracker#1310]
[//]: # (Enclose links to things related to the bug using http://wowhead.com or any other TBC database.)
[//]: # (You can use screenshot ingame to visual the issue.)
[//]: # (Write your tickets according to the format:)
[//]: # ([Quest][Azuremyst Isle] Red Snapper - Very Tasty!)
[//]: # ([NPC] Magistrix Erona)
[//]: # ([Spell][Mage] Fireball)
[//]: # ([Npc][Drop] Ghostclaw Lynx)
[//]: # ([Web] Armory doesnt work)

**Description**: 
https://www.wowhead.com/npc=2926/silvermane-stalker#comments
NPC isn't stealthed.

**Current behaviour**:
NPC isn't stealthed.
Edit:
![stalker](https://imgur.com/xnOH8zA.jpg)

**Expected behaviour**: 
NPC should be stealthed.

By zoorroo4 (386 – 3) on 2009/12/01 (Patch 3.2.2)
>Can´t find these darn wolfs, and don´t answer stupid stuff like, They stealth and stuff, i know, but still i can´t find them ..

**Server Revision**: 2135

**Comment by Evolvee** [comment]
@Wolffenstein REEEEEEEE

**Comment by The14me** [comment]
Related https://github.com/Atlantiss/NetherwingBugtracker/issues/1309

**Comment by totaemoeggerli** [comment]
if you bug them out with the stealth delay bug they stealth quickly and it sais that stealth faded from the mob in the combat log
https://gfycat.com/SpeedyScentedEwe

**Comment by Evolvee** [comment]
@Wolffenstein ^^^^

**Comment by Wolffenstein** [comment]
Fixed in rev 2138.
