### ISSUE TITLE
[NPC]Succubus Minion#10928 Likely using wrong [Spell]Lash of Pain-spell dealing 300dmg at lvl 40

### ISSUE THREAD

**Issue by Tenoutoften** [Atlantiss/NetherwingBugtracker#1311]
**Description**: 
[[NPC]Succubus Minion#10928](https://db.excalibur.ws/?npc=10928#abilities) summoned with [[Spell]Summon Succubus#8722](https://db.excalibur.ws/?spell=8722) by [[NPC]Bloodsail Warlock#1564](https://db.excalibur.ws/?npc=1564#abilities) does an incredibly painful [[Spell]Lash of Pain](https://db.excalibur.ws/?search=lash+of+pain#spells)
![1e71c4ada06f06ab1e149193ea3334d9](https://user-images.githubusercontent.com/34839199/46576095-d9d12180-c9c2-11e8-8387-a9fc0ccadaa2.png)
![4a5ee542b69bae4eb84bc731d8ef8035](https://user-images.githubusercontent.com/34839199/46576096-da69b800-c9c2-11e8-8afb-bd65b2492256.png)
![c096817ae6dac064cb9c65effe9f9849](https://user-images.githubusercontent.com/34839199/46576097-da69b800-c9c2-11e8-906b-8a66f77df419.png)

[[NPC]Succubus Minion#10928](https://db.excalibur.ws/?npc=10928#abilities) is easily out damaging it's master [[NPC]Bloodsail Warlock#1564](https://db.excalibur.ws/?npc=1564#abilities). In comparison a regular Succubus with the max trained rank(7) will deal [~123dmg + spell dmg](https://db.excalibur.ws/?spell=27274). I cant figure out what it is suppose to deal, all I got is a video of it not being used: https://youtu.be/gusbV3RtP44?t=34 but surely it shouldnt deal 2.5 times the flat TBC rank?

**Expected behaviour**: 
I'd expect [[NPC]Succubus Minion#10928](https://db.excalibur.ws/?npc=10928#abilities) to use a (https://db.excalibur.ws/?search=lash+of+pain#spells) that deals about 60-80 damage at this level ~40

**Server Revision**: 
2135

**Comment by Evolvee** [comment]
rev 439kcolb
