### ISSUE TITLE
Seal of Command

### ISSUE THREAD

**Issue by Piledriversn** [Atlantiss/NetherwingBugtracker#1312]
http://wowwiki.wikia.com/wiki/Seal_of_Command_(old)
![image](https://user-images.githubusercontent.com/43560552/46577038-f8bebc00-c9a0-11e8-809f-d69b1b9bf5c6.png)
[//]: # ([Spell][Seal of Command)
**Description**: Seal of Command should not be parried,blocked or dodge. 

**Current behaviour**:Seal of Command is being parried. I have not seen it dodged or blocked yet. I will update this if it dodges or blocks. 

**Expected behaviour**: After patch 1.3 Seal of Command should only be resisted.

**Server Revision**:

**Comment by The14me** [comment]
''Seal of Command - The damage effects can now be resisted instead of dodged, blocked, or parried.'
http://wowwiki.wikia.com/wiki/Patch_1.3.0

**Comment by Evolvee** [comment]
![image](https://user-images.githubusercontent.com/1942409/46638382-eab79980-cb60-11e8-86e2-0f57b7077f6e.png)

**Comment by Wolffenstein** [comment]
Fixed in rev 2151.
