### ISSUE TITLE
NPC ( Minor Issue )

### ISSUE THREAD

**Issue by Varadin** [Atlantiss/NetherwingBugtracker#1313]
[//]: # ([NPC] Antonio Perreli)
https://i.imgur.com/mT0TVCf.jpg
https://i.imgur.com/4B70GP1.jpg
**Description**: 
Was patroling/walking around westfall , when i talked to him he just stood there and haven't moved since.
**Current behaviour**:
Standing and not continuing to walk after interaction/trade and than dissapeared after 5 mins of standing still.
**Expected behaviour**: 
Should start walking after end of conversation.
**Server Revision**: 
2137

**Comment by Evolvee** [comment]
wtf 👺

**Comment by Evolvee** [comment]
@Wolffenstein he even has active mask PepeHands

**Comment by Evolvee** [comment]
I dont see anything wrong tho, maybe its just the delay

oh wait now i see

@Wolffenstein the NPC stop delay refreshes every time someone talks to the NPC, idk if this is intended

so if you click on the NPC, the "stopping" waypoint delay refreshes and starts from the beggining
