### ISSUE TITLE
[Quest][RP Event] Highlord Taelan Fordring, In Dreams, EPL

### ISSUE THREAD

**Issue by Erodraeda** [Atlantiss/NetherwingBugtracker#1314]
[//]: # (Enclose links to things related to the bug using http://wowhead.com or any other TBC database.)
[//]: # (You can use screenshot ingame to visual the issue.)
[//]: # (Write your tickets according to the format:)
[//]: # ([Quest][Azuremyst Isle] Red Snapper - Very Tasty!)
[//]: # ([NPC] Magistrix Erona)
[//]: # ([Spell][Mage] Fireball)
[//]: # ([Npc][Drop] Ghostclaw Lynx)
[//]: # ([Web] Armory doesnt work)

**Description**: 
After you hand in the first quest to him, after picking up the new one, he yells "NOOOOOOO!", and then starts fighting his own guards. After he kills them, you can then pick up In Dreams. But I was doing it with a friend. I turned the quest and the event happened normally. When he turned the quest, tho (the guards were dead), nothing happened, Taelan stood still, and we were unable to get the quest from him. After sometime, when the guards respawn, he then starts attacking them, but still can't grab the quest from him. Apparently, he'll keep killing his guards, forever.
Entry: 1842, ID: 1
**Current behaviour**:
After a second player turns the quest, Taelan stand still, doing nothing. After sometime, when guards respawn, he kills them, and stand still again.
![screenshot_590](https://user-images.githubusercontent.com/40346279/46577213-b3f24f80-c9b7-11e8-8546-7ba96f5f318f.png)
After first time he kills the guards ^
![screenshot_591](https://user-images.githubusercontent.com/40346279/46577216-b8b70380-c9b7-11e8-93fa-bda749926939.png)
After second time ^
**Expected behaviour**: 
He should do the RP event only once, when the first player hands in the quest. He should still yell, but shouldn't have to kill guards again if they are not alive.
Either that, or he should only kill guards after the player takes the next quest from him.
**Server Revision**: 2137

**Comment by Evolvee** [comment]
the "guard attack" event after quest Scarlet Subterfuge will happen only once after rev hehexd
