### ISSUE TITLE
[NPC][Feralas] Rakaiah - Respawn timer.

### ISSUE THREAD

**Issue by Firroth** [Atlantiss/NetherwingBugtracker#1316]
[NPC] [Rakaiah](https://www.wowhead.com/npc=9518/rakaiah#comments)

**Current behaviour**:
Her respawn timer seems to be now 5min. or less.

**Expected behaviour**: 
Her respawn timer should be 15min.

![screenshot_1](https://user-images.githubusercontent.com/43505196/46580417-eb4b1580-ca24-11e8-9854-ef4fb2823e36.png)

**Server Revision**: 
2137

**Comment by aresbrutus** [comment]
This is intended due to private servers having thousands of people starting from the exact point trying to do content with the crowd. This applies to all named mobs.
