### ISSUE TITLE
[Quest][NPC] Rescue From Jaedenar - Spirit of Trey Lightforge

### ISSUE THREAD

**Issue by Firroth** [Atlantiss/NetherwingBugtracker#1318]
[Quest] [Rescue From Jaedenar](https://www.wowhead.com/quest=5203/deprecated-rescue-from-jaedenar)
[NPC] [Spirit of Trey Lightforge](http://wowwiki.wikia.com/wiki/Spirit_of_Trey_Lightforge)
[Spell] [Shadow Bolt](https://vanilla-twinhead.twinstar.cz/?spell=18164)
[Spell] [Holy Light](https://vanilla-twinhead.twinstar.cz/?spell=15493)

**Current behaviour**:
1. He doesn't use [Spell] [Shadow Bolt](https://vanilla-twinhead.twinstar.cz/?spell=18164)
2. He doesn't use [Spell] [Holy Light](https://vanilla-twinhead.twinstar.cz/?spell=15493) when below 50% (should heal him for 1500+)
3. Deals too little meele damage 60 on mail/plate.

![screenshot_2](https://user-images.githubusercontent.com/43505196/46580664-5b5b9a80-ca29-11e8-8388-c4a2f52c90b8.png)

**Expected behaviour**: 
1. He should use [Spell] [Shadow Bolt](https://vanilla-twinhead.twinstar.cz/?spell=18164)
2. He should use [Spell] [Holy Light](https://vanilla-twinhead.twinstar.cz/?spell=15493) when below 50% (should heal him for 1500+)
3.  Should deal meele damage 150 on plate.

![screenshot_3](https://user-images.githubusercontent.com/43505196/46580663-5ac30400-ca29-11e8-9003-2df15739ed52.png)

**Server Revision**: 
2137

**Comment by Evolvee** [comment]
rev hehexd --> added spells and slight dmg adjustment
