### ISSUE TITLE
[NPC]Brutus#2551 should 100% drop [Item]Dizzy's Eye#3897

### ISSUE THREAD

**Issue by Tenoutoften** [Atlantiss/NetherwingBugtracker#1319]
**Description**: 
[[NPC]Brutus#2551](https://www.wowhead.com/npc=2551/brutus#comments) should have a 100% drop chance on [[Item]Dizzy's Eye#3897](https://www.wowhead.com/item=3897/dizzys-eye#comments) or [[Quest]Keep An Eye Out#576](https://www.wowhead.com/quest=576/keep-an-eye-out#comments)  according to lots of [wowhead comments](https://www.wowhead.com/npc=2551/brutus#comments):

![3bddbe18bc8ae7230301293fe6321cca](https://user-images.githubusercontent.com/34839199/46580778-daea6900-ca2b-11e8-8a17-4c2e69fd8013.png)
![5f86df3c2f083418f067c7adf2e14e5e](https://user-images.githubusercontent.com/34839199/46580779-daea6900-ca2b-11e8-9de3-6edb243337ee.png)
![6f65d75ea31f6b463ae418f0c78fde88](https://user-images.githubusercontent.com/34839199/46580780-daea6900-ca2b-11e8-8604-2a66570e6321.png)
![8e45bde5c09958683b84f43d31ed5165](https://user-images.githubusercontent.com/34839199/46580782-daea6900-ca2b-11e8-80ed-fe2f6cabc082.png)
![df981c237efcaf5366f1ab05541398cb](https://user-images.githubusercontent.com/34839199/46580783-daea6900-ca2b-11e8-87d7-6bbac75a93c2.png)
![e9e19b499f8ccda825df329d0ab12a8f](https://user-images.githubusercontent.com/34839199/46580784-daea6900-ca2b-11e8-9918-e38d566fa0eb.png)
![2be957e8e43cb1837073b2ff20179711](https://user-images.githubusercontent.com/34839199/46580785-db82ff80-ca2b-11e8-8364-96e623a6f037.png)
![b1f38891baf87764705d7f497c32ab9f](https://user-images.githubusercontent.com/34839199/46580786-dcb42c80-ca2b-11e8-8b35-d5babbb3de03.png)

.gps & .npc info here:
![97f0d40346d257569d019ce6e03c2205](https://user-images.githubusercontent.com/34839199/46580787-e342a400-ca2b-11e8-8163-a37bfe545657.png)

Currently doesn't drop it:
![15bbd0b7200407bdf0e7a52947326879](https://user-images.githubusercontent.com/34839199/46580789-e9d11b80-ca2b-11e8-985e-95fd9ce28ee2.png)

Video of it not dropping [here](https://www.youtube.com/watch?v=5T-pBQ7PtSQ&feature=youtu.be)

-------------------
Some speculation on my part as I couldn't find any evidence... [[NPC]Brutus#2551](https://www.wowhead.com/npc=2551/brutus#comments) currently has zero abilities but on [wowhead](https://www.wowhead.com/npc=2551/brutus#abilities) he is listed with 3 abilities. All of them have spellIDs currently in the game. Two of them are seemingly used by no one in Excalibur DB:

https://www.wowhead.com/spell=33661/crush-armor => https://db.excalibur.ws/?spell=33661 (Used by a Tailoring trainer in Eversong apparently?)

https://www.wowhead.com/spell=38784/ground-smash => https://db.excalibur.ws/?spell=38784 used by no one

https://www.wowhead.com/spell=38785/ground-smash => https://db.excalibur.ws/?spell=38785 used by no one

Maybe he should have some abilities?

**Expected behaviour**: 
[[NPC]Brutus#2551](https://www.wowhead.com/npc=2551/brutus#comments) should 100% drop [[Item]Dizzy's Eye#3897](https://www.wowhead.com/item=3897/dizzys-eye#comments) for [[Quest]Keep An Eye Out#576](https://www.wowhead.com/quest=576/keep-an-eye-out#comments)

**Server Revision**: 
2137

**Comment by Evolvee** [comment]
@Easyfraggy 2551 bestiary link pls

**Comment by Tenoutoften** [comment]
Comments do say he is pretty easy though, but mention he has high armor hmm

**Comment by The14me** [comment]
https://i.imgur.com/DUzBMyd.png No ability here.

**Comment by Tenoutoften** [comment]
2343054 armor?

**Comment by The14me** [comment]
there are some..lets say error's in the book. :dagger:

**Comment by Evolvee** [comment]
@Easyfraggy can u link the other book?

**Comment by Evolvee** [comment]
rev hehexd
