### ISSUE TITLE
'Already Known' on warlock pet skill books

### ISSUE THREAD

**Issue by Dajmills** [Atlantiss/NetherwingBugtracker#132]
[//]: # (Enclose links to things related to the bug using http://wowhead.com or any other TBC database.)
[//]: # (You can use screenshot ingame to visual the issue.)
[//]: # (Write your tickets according to the format:)
[//]: # ([Quest][Azuremyst Isle] Red Snapper - Very Tasty!)
[//]: # ([NPC] Magistrix Erona)
[//]: # ([Spell][Mage] Fireball)
[//]: # ([Npc][Drop] Ghostclaw Lynx)
[//]: # ([Web] Armory doesnt work)

**Description**: Warlock pet skill books only have the 'Already Known' tag if the rel relevant demon is active.

**Current behaviour**: The 'Already Known' message is only on the skill book if the pet in question is active

**Expected behaviour**: The 'Already Known' message should be present if you know the skill

**Server Revision**:

**Comment by Mou-nw** [comment]
I disagree. The 'already known' text only came up when appropriate pet was out.

**Comment by Easyfraggy** [comment]
Need some evidence of this.

**Comment by lynxzor** [comment]
Working as intended?
https://wow.curseforge.com/projects/project-2146

**Comment by Tereneckla** [comment]
The existence of the addon implies that it only showed the known status of the current pet.
