### ISSUE TITLE
[Quest][Winterpsring] Guardian of The Altar - Escort behaviour.

### ISSUE THREAD

**Issue by Firroth** [Atlantiss/NetherwingBugtracker#1321]
[Quest][Winterpsring] [Guardian of The Altar](https://www.wowhead.com/quest=4901/guardians-of-the-altar)
[NPC] [Ranshalla](https://www.wowhead.com/npc=10300/ranshalla)

**Description**: 
Escort Quest.

**Current behaviour**:
She ignores mobs along the way - they aggro on her, and rather than enter into meele fight with them, she totally ignores them and is still going to her objective. This can AND will make you fight 4+ in total if you aren't fast enough killing them off along the way. Dark Souls mode :D 

When she gets to the first cave,  she starts channeling, but if she "will get hit" by someone, she will stop channeling and leave the cave and go where "mob hit her" and will stay in this place and do nothing - see screenshot.

![screenshot_1](https://user-images.githubusercontent.com/43505196/46581803-c2377e80-ca3e-11e8-9766-f2ac5743cdbf.png)

I forgot to use torch then but it's possible she would "react to it" and continue the escort from the place on screenshot, (she should from the cave though).

**Also when you use "torch" when she is channeling, it will lit for 5-10s and it will reset to not being lit.**

**So from what I found out, the biggest issue here is her ignoring mobs and when she gets hit she will go to her next "waypoint" turn back and go back to the place where she got hit, just to once again from there go to her objective/waypoint.**

**Expected behaviour**: 

1. She should enter into combat with mobs when they aggro on her, and fight them.

2. When player used torch (5 torches in total) they should stay lit until the end of escort (complete message).

**Server Revision**: 
2137

**Comment by FrozenBread** [comment]
This just happened to me too, same issues

**Comment by samemari** [comment]
Same issues, Server Revision 2196
