### ISSUE TITLE
[core][quest] Unable to abandon and re-take failed quests after relog

### ISSUE THREAD

**Issue by Evolvee** [Atlantiss/NetherwingBugtracker#1322]
@Wolffenstein critical issue

Ppl dont get the quest they abandon after relog. The fix is to removed both current and preQ and do the preQ again, after that the current quest is available again. Otherwise it doesnt show up.

Affects especially escorts and timed quests.

**Comment by Wolffenstein** [comment]
Fixed in rev 2138.
