### ISSUE TITLE
[NPC][Ashenvale]Foulweald Totemic

### ISSUE THREAD

**Issue by narayagh** [Atlantiss/NetherwingBugtracker#1323]
[//]: # (Enclose links to things related to the bug using http://wowhead.com or any other TBC database.)
[//]: # (You can use screenshot ingame to visual the issue.)
[//]: # (Write your tickets according to the format:)
[//]: # ([Quest][Azuremyst Isle] Red Snapper - Very Tasty!)
[//]: # ([NPC] Magistrix Erona)
[//]: # ([Spell][Mage] Fireball)
[//]: # ([Npc][Drop] Ghostclaw Lynx)
[//]: # ([Web] Armory doesnt work)

**Description**: 
Foulweald Totemic's Searing Totem doesn't do anything.
ALSO: This totem still looks like a Draenei totem - this was [supposedly fixed in rev 2081](https://github.com/Atlantiss/NetherwingBugtracker/issues/763#issuecomment-425535799) but in fact it wasn't.

**Current behaviour**:
Foulweald Totemic's Searing Totem doesn't do anything. https://streamable.com/maet4

**Expected behaviour**: 
Foulweald Totemic's Searing Totem should attack.

**Server Revision**: 
2137

**Comment by Anonyxx** [comment]
I have found this issue as well. The searing totem is summoned (and actually moved around in one case) but did not attack.

**Comment by Bildo** [comment]
fixed in rev 2413
