### ISSUE TITLE
[Movement][NPC]Venture Co. Strip Miner/Foreman/Surveyor#674/675/676 should flee occasionally on low HP

### ISSUE THREAD

**Issue by Tenoutoften** [Atlantiss/NetherwingBugtracker#1324]
**Description**: 
* [[NPC]Venture Co. Strip Miner#674](https://db.excalibur.ws/?npc=674)
* [[NPC]Venture Co. Foreman#675](https://db.excalibur.ws/?npc=675)
* [[NPC]Venture Co. Surveyor#676](https://db.excalibur.ws/?npc=676)

Doesn't occasionally flee on low HP or I was super lucky, I killed 28 of them without a single flee. [[NPC]Venture Co. Tinkerer#677](https://db.excalibur.ws/?npc=677) at the same location does flee occasionally, though. Didn't get to test the rare spawn [[NPC]Verifonix#14492](https://db.excalibur.ws/?npc=14492) as he wasn't around. 

I am expecting them to flee based on a [wowhead comments](https://www.wowhead.com/item=3917/singing-blue-crystal) and the lower level ones in the north also flee so this would be consistent.
![da766a183f4bf95c25623298e4d12eba](https://user-images.githubusercontent.com/34839199/46582547-e435fe80-ca48-11e8-8f5d-c6b40bd2ed03.png)
![74dd35d294b494692210c4317023eb07](https://user-images.githubusercontent.com/34839199/46582619-08460f80-ca4a-11e8-9e09-bdfe2bb4d97f.png)
![33b1bd69272869cad5a31938496900e9](https://user-images.githubusercontent.com/34839199/46582628-1e53d000-ca4a-11e8-9bdc-d4452a92b0f4.png)

**Expected behaviour**: 
Expected to flee occasionally on low HP:
* [[NPC]Venture Co. Strip Miner#674](https://db.excalibur.ws/?npc=674)
* [[NPC]Venture Co. Foreman#675](https://db.excalibur.ws/?npc=675)
* [[NPC]Venture Co. Surveyor#676](https://db.excalibur.ws/?npc=676)

**Server Revision**: 
2137

**Comment by Evolvee** [comment]
rev sample_text
