### ISSUE TITLE
[NPC]Venture Co. Foreman#675 doesn't use [Spell]Devotion Aura#8258 on spawn/deactivates on disengage

### ISSUE THREAD

**Issue by Tenoutoften** [Atlantiss/NetherwingBugtracker#1325]
**Description**: 
[[NPC]Venture Co. Foreman#675](https://db.excalibur.ws/?npc=675#controlled-abilities) doesn't use [ [[Spell]Devotion Aura#8258](https://db.excalibur.ws/?spell=8258) on spawn. He uses it only when he is engaged and deactivates it afterwards.

Much like https://github.com/Atlantiss/NetherwingBugtracker/issues/1023 (resolved)
Video it [here](https://www.youtube.com/watch?v=IplX-FemiJw&feature=youtu.be)

**Expected behaviour**: 
Expected to always run around with [[Spell]Devotion Aura#8258](https://db.excalibur.ws/?spell=8258)

**Server Revision**: 
2137

**Comment by Evolvee** [comment]
rev 439kcolb
