### ISSUE TITLE
dust cloud - missing description

### ISSUE THREAD

**Issue by duzyizly** [Atlantiss/NetherwingBugtracker#1326]
[//]: # (Enclose links to things related to the bug using http://wowhead.com or any other TBC database.)
[//]: # (You can use screenshot ingame to visual the issue.)
[//]: # (Write your tickets according to the format:)
[//]: # ([Quest][Azuremyst Isle] Red Snapper - Very Tasty!)
[//]: # ([NPC] Magistrix Erona)
[//]: # ([Spell][Mage] Fireball)
[//]: # ([Npc][Drop] Ghostclaw Lynx)
[//]: # ([Web] Armory doesnt work)

**Description**: dust cloud https://db.excalibur.ws/?spell=26072 is missing description

**Current behaviour**: 
![dustcould](https://user-images.githubusercontent.com/43931626/46582869-0d0cc280-ca4e-11e8-94bc-efacc4a2b290.jpg)

**Expected behaviour**: there should be some info about "85% miss chance or so"

**Server Revision**: no idea

**Comment by Wolffenstein** [comment]
Nope. The spell is entirely missing a description in the client. It's not something we can fix unfortunately.
