### ISSUE TITLE
[NPC]Venture Co. Surveyor#676 missing [Spell]Fire Nova?

### ISSUE THREAD

**Issue by Tenoutoften** [Atlantiss/NetherwingBugtracker#1328]
**Description**: 
[[NPC]Venture Co. Surveyor#676](https://www.wowhead.com/npc=676/venture-co-surveyor#abilities) should likely be using [[Spell]Fire Nova](https://db.excalibur.ws/?search=fire+nova#spells). Currently he does nothing, as can be seen in [this video](https://www.youtube.com/watch?v=srQx_U4_xGE&feature=youtu.be) which is strange since:

All of the other NPC at this place does something.
* [[NPC]Venture Co. Foreman#675](https://db.excalibur.ws/?npc=675) has [[Spell]Devotion Aura#8258](https://db.excalibur.ws/?spell=8258)
* [[NPC]Venture Co. Strip Miner#674](https://db.excalibur.ws/?npc=674) has [[Spell]Dynamite](https://www.wowhead.com/spell=8800/dynamite)(Though he uses the wrong rank on NW: https://github.com/Atlantiss/NetherwingBugtracker/issues/1327)
* [[NPC]Venture Co. Tinkerer#677](https://db.excalibur.ws/?npc=677) uses Fireball, Frost Armor, and summons Harvest Reapers.

And he is a mana user, which is usually an indicator that the NPC will do something.
On Wowhead [[NPC]Venture Co. Surveyor#676](https://www.wowhead.com/npc=676/venture-co-surveyor#abilities)  uses [[Spell]Fire Nova#11969](https://www.wowhead.com/spell=11969/fire-nova). This spell doesn't name which patch it was added in, indicating it's an old spell, plus the spellID is rather low..

**Current behaviour**:
[[NPC]Venture Co. Surveyor#676](https://www.wowhead.com/npc=676/venture-co-surveyor#abilities) has no abilities

**Expected behaviour**: 
Expected to have [[Spell]Fire Nova#11969](https://www.wowhead.com/spell=11969/fire-nova) but perhaps another spell

**Server Revision**: 
2137

**Comment by The14me** [comment]
https://i.imgur.com/BB5II5G.png Blizzard

**Comment by Easyfraggy** [comment]
![image](https://user-images.githubusercontent.com/36134067/46585044-cb8b1000-ca6b-11e8-980b-3fb0abe9b884.png)
