### ISSUE TITLE
[Spell][Shaman] Mana Spring Totem

### ISSUE THREAD

**Issue by Retinus** [Atlantiss/NetherwingBugtracker#1329]
My main issue is with Mana Spring Totem, but i ll generally talk about Totem Threat / Aggro.

**Description**: The fire totems generate threat independent of the shaman who placed them (from my tests i think fire nova and magma totem work like they should but searing totem is not [#393](https://github.com/Atlantiss/NetherwingBugtracker/issues/393)). All other totems do not generate threat, although they will aggro mobs if placed within the mobs aggro radius before something/one else.

**Current behavior**: If you body pull a mob and place / have already placed mana spring totem down mob will stop attacking you and go for the totem. You can see it also when pulling more than one mobs. ie pull 3 mobs, hit only 2 of them, 3rd mob will go for the totem and then come to you.

**Expected behavior**: Mana spring totem shouldn't generate aggro.

**Server Revision**: 2137

Below are links with info

[Totem Threat / Aggro](https://github.com/Looking4Group/L4G_Core/issues/402)
[Totems and threat](https://www.wowhead.com/forums&topic=4379/totems-and-threat)

**Comment by samemari** [comment]
Confirming. Mana spring totems generates aggro and is destroyed before mob attacks my shaman

**Comment by Wolffenstein** [comment]
Fixed in rev 2159.

**Comment by Tundra28** [comment]
needs to be revised, mana spring totem is agroing again!

**Comment by Wolffenstein** [comment]
Rev 2612.
