### ISSUE TITLE
[NPC] zalazane - respawn time

### ISSUE THREAD

**Issue by duzyizly** [Atlantiss/NetherwingBugtracker#1330]
[//]: # (Enclose links to things related to the bug using http://wowhead.com or any other TBC database.)
[//]: # (You can use screenshot ingame to visual the issue.)
[//]: # (Write your tickets according to the format:)
[//]: # ([Quest][Azuremyst Isle] Red Snapper - Very Tasty!)
[//]: # ([NPC] Magistrix Erona)
[//]: # ([Spell][Mage] Fireball)
[//]: # ([Npc][Drop] Ghostclaw Lynx)
[//]: # ([Web] Armory doesnt work)

**Description**: zalazane https://db.excalibur.ws/?npc=3205 has around 60 sec respawn time. Not sure if intended because his corpse are still there when he respawns.

**Current behaviour**: 
![wowscrnshot_100718_164423](https://user-images.githubusercontent.com/43931626/46583025-958c6280-ca50-11e8-9a9f-e3e16d418e8c.jpg)

**Expected behaviour**: respawn time should be around 5min.

**Server Revision**:

**Comment by The14me** [comment]
Intended,thx for the report anyway : )
