### ISSUE TITLE
[NPC][Ashenvale] Ilkrud Magthrul & his succubus minions

### ISSUE THREAD

**Issue by Anonyxx** [Atlantiss/NetherwingBugtracker#1331]
**Description**: 

There are two problems with Ilkrud's summoned "Succubus minion".

Firstly, he sometimes encounters a bug where he has two minions spawned. [See here](https://serving.photos.photobox.com/010612740f7f1825e32584038c4e36e214501083f94ae148d59d10b164b41029946e4488.jpg)

Secondly, the minions themselves do too much damage with their "lash of pain" ability and do this ability too frequently.

**Current behaviour**:

Two minions can be summoned at the same time. 

For example, they hit for 16-17 melee damage but do a frequent instant cast ability "Lash of Pain" ability of 126 shadow damage (roughly cast every 2 seconds). This feels wrong, although I could not find an example of what this should be.

**Expected behaviour**: 

Ilkrud Magthrul should not start out the fight with more than one succubus minion.

Lash of Pain should not be cast as frequently as it being done currently and should not do as much damage.

**Server Revision**: 
2137

**Comment by Tenoutoften** [comment]
A bit like https://github.com/Atlantiss/NetherwingBugtracker/issues/1311
Very high damage, frequently used.... ~123-125 damage is equal to that of a max ranked Lash of Pain of a warlock pet without spell dmg taken into consideration [[Spell]Lash of Pain(Rank 7)#27274](https://db.excalibur.ws/?spell=27274)

**Comment by Evolvee** [comment]
rev 439kcolb for succubus

the double spawn is weird, i tweaked it slightly but it should not have happened anyway, possibly core issue if it happens again
