### ISSUE TITLE
Too many Glinting Mud spawns for quest Hilary's Necklace

### ISSUE THREAD

**Issue by Notmittz** [Atlantiss/NetherwingBugtracker#1333]
# ([Quest][Redridge Mountains] Hilary's Necklace)

**Description**: 
All of the glinting mud spawn locations in the lake are all up at the same time and each gives the quest item Hilary's Necklace [Item 10958] (checked this by destroying the necklace and re-looting at a new spawn)

**Current behaviour**:
All possible locations for the glinting mud's are spawned and up at the same time

**Expected behaviour**: 
Only one glinting mud is supposed to be up at a given time and it's location is supposed to be random.

https://www.wowhead.com/quest=3741/hilarys-necklace#comments:id=19150

**Server Revision**: 
[2137][Core] Beta fixes

**Comment by Firroth** [comment]
I can confirm it. ( Forgot to report it when I was lvling there. )

**Comment by aresbrutus** [comment]
There are 10 points, only 4 of those are active at a time. This is due to the influx of players in the area. Else you would see 50 humans swimming, trying to get the next spawn somewhere.
