### ISSUE TITLE
[Quest][Burning Steppes]A Taste of Flame

### ISSUE THREAD

**Issue by DeltaLoads** [Atlantiss/NetherwingBugtracker#1334]
[//]: # (Enclose links to things related to the bug using http://wowhead.com or any other TBC database.)
[//]: # (You can use screenshot ingame to visual the issue.)
[//]: # (Write your tickets according to the format:)
[//]: # ([Quest][Azuremyst Isle] Red Snapper - Very Tasty!)
[//]: # ([NPC] Magistrix Erona)
[//]: # ([Spell][Mage] Fireball)
[//]: # ([Npc][Drop] Ghostclaw Lynx)
[//]: # ([Web] Armory doesnt work)

**Description**: 
Cyrus Therepentous is missing quest completed/uncompleted marker above his head once you complete/accept A Taste of Flame quest.
![wowscrnshot_100718_175143](https://user-images.githubusercontent.com/43690147/46583611-04ba8480-ca5a-11e8-8587-34702b7531c6.jpg)

**Current behaviour**:
Cyrus Therepentous is missing completed/uncompleted marker above his head
**Expected behaviour**: 
Cyrus Therepentous should have completed/uncompleted marker above his head
**Server Revision**: 
2137

**Comment by Shanghi** [comment]
This should be fixed in revision 2152.
