### ISSUE TITLE
[Quest] [Drop] List of mobs / quests with low drop rates.

### ISSUE THREAD

**Issue by Unfairy** [Atlantiss/NetherwingBugtracker#1339]
Soothing Turtle Bisque (ID 7321)
Turtle meat drop is low.
Turtles supposed to drop from 1 to 2 turtle meat and the drop of one is about 100% or so.

Crushridge Bounty (ID 500)
Dirty Knucklebones drop is pretty low.
Was doing it in party of 2 people and we spent pretty much time getting quest done.

Badlands Reagent Run (ID 2500)
Buzzard Gizzard droprate is insanely low. First time for a long period droprate pushing me to ragequit this. And some sources shows the drop about 60-80%. From all kind of Buzzards.
Really? Just really?

**Comment by Firroth** [comment]
Soothing Turtle Bisque (ID 7321)
![screenshot_2](https://user-images.githubusercontent.com/43505196/46584214-dbe9bd80-ca60-11e8-9cfc-02e3f0adfe0c.png)
![screenshot_3](https://user-images.githubusercontent.com/43505196/46584215-dbe9bd80-ca60-11e8-9a76-bfcbbbc190e5.png)

Crushridge Bounty (ID 500)
Worked fine for me, did it in less than 10min.

Badlands Reagent Run (ID 2500) 
No idea, didn't done it yet, but maybe will today.

**Comment by wtRCH** [comment]
> https://classicdb.ch/?item=5797, http://db.hellfire-tbc.com/?item=5797 -> drop rates for stonevaults mobs more than 80%. It seems that on Netherwing drop rates for indurium less than 20%.

These are Databases based on other private servers. Most of the times values aren't Blizzlike.

**Comment by aresbrutus** [comment]
Badlands Reagent Run and Indurium quest drop rates are fixed in rev `Tycho`.
