### ISSUE TITLE
[NPC] Walking next to a hostile enemy that is already in combat with another player will also put you in combat.

### ISSUE THREAD

**Issue by manslaughter** [Atlantiss/NetherwingBugtracker#134]
**Description**: For any NPC that is hostile (red name), if it is already in combat with another player, you will also be put in combat if you get close enough (normal aggro range?)

**Current behaviour**: }

**Expected behaviour**: You will not be put into combat unless the NPC is not currently in combat with another player/NPC.

**Server Revision**: 2028

**Comment by Wolffenstein** [comment]
It will be fixed after the server comes online.
