### ISSUE TITLE
[NPC][Burning Steppes] War Reaver

### ISSUE THREAD

**Issue by DeltaLoads** [Atlantiss/NetherwingBugtracker#1340]
[//]: # (Enclose links to things related to the bug using http://wowhead.com or any other TBC database.)
[//]: # (You can use screenshot ingame to visual the issue.)
[//]: # (Write your tickets according to the format:)
[//]: # ([Quest][Azuremyst Isle] Red Snapper - Very Tasty!)
[//]: # ([NPC] Magistrix Erona)
[//]: # ([Spell][Mage] Fireball)
[//]: # ([Npc][Drop] Ghostclaw Lynx)
[//]: # ([Web] Armory doesnt work)

**Description**: 
War Reavers dont use their uppercut/trash skills on pets - only normal attacks, they only use them on players
**Current behaviour**:
War Reavers dont use their uppercut/trash skills on pets
**Expected behaviour**: 
War Reavers should use their uppercut/trash skills on pets
**Server Revision**: 
2137

**Comment by Evolvee** [comment]
@Wolffenstein possibly ai bug?

**Comment by Tereneckla** [comment]
Fixed
