### ISSUE TITLE
[NPC] [Eastern Plaguelands] Eris Havenfire - hostile

### ISSUE THREAD

**Issue by idsss** [Atlantiss/NetherwingBugtracker#1341]
**Description**: 
![wowscrnshot_100718_182015](https://user-images.githubusercontent.com/43757915/46584147-025b2900-ca60-11e8-99be-e4f3eb427d0f.jpg)

https://www.wowhead.com/npc=14494/eris-havenfire

checked on Eris Havenfire for the priest Benediction quest, could see her with the eye of divinity equipped but she seems to be hostile. Couldnt try out quests for obvious reasons

**Current behaviour**: she's hostile.

**Expected behaviour**:  should be friendly offering "A Warning" and "The Balance of Light and Shadow"

**Server Revision**: 
2137

**Comment by toto6** [comment]
Fixed in Rev 2150
