### ISSUE TITLE
Meven Korgal's langauge type is set incorrectly.

### ISSUE THREAD

**Issue by JamesIsAwkward** [Atlantiss/NetherwingBugtracker#1342]
**Description**: Non-Ally races are able to understand Meven Korgal when he yells text. He's using the wrong language ID I believe.

**Current behaviour**: Undead/Horde players can understand what he yells.

**Expected behaviour**: He should be yelling in "common" language.

**Server Revision**:

**Comment by aresbrutus** [comment]
Fixed in rev: Tycho
