### ISSUE TITLE
[NPC]Firemane Ash Tail#4331 should keep [Spell]Fire Shield#18968 up outside of combat

### ISSUE THREAD

**Issue by Tenoutoften** [Atlantiss/NetherwingBugtracker#1343]
**Description**: 
[[NPC]Firemane Ash Tail#4331](https://www.wowhead.com/npc=4331/firemane-ash-tail#abilities) should keep [[Spell]Fire Shield#18968](https://www.wowhead.com/spell=18968/fire-shield) up outside of combat. Currently doesn't.

This is a [video from a later patch showing it (5 years ago)](https://youtu.be/dhaXNmT__Tk?t=40)

**Expected behaviour**: 
should keep [[Spell]Fire Shield#18968](https://www.wowhead.com/spell=18968/fire-shield) up outside of combat.

**Server Revision**: 
2137

**Comment by Evolvee** [comment]
rev hehexd
