### ISSUE TITLE
[NPC]Firemane Scout#4329 should keep [Spell]Fire Shield#18968 up outside of combat

### ISSUE THREAD

**Issue by Tenoutoften** [Atlantiss/NetherwingBugtracker#1344]
**Description**: 
[[NPC]Firemane Scout#4329](https://www.wowhead.com/npc=4329/firemane-scout#abilities) should keep [[Spell]Fire Shield#18968](https://www.wowhead.com/spell=18968/fire-shield) up outside of combat. Currently doesn't.

This is a [video from a later patch showing it (5 years ago)](https://youtu.be/dhaXNmT__Tk?t=75)

**Expected behaviour**: 
Should keep [[Spell]Fire Shield#18968](https://www.wowhead.com/spell=18968/fire-shield) up outside of combat.

**Server Revision**: 
2137

**Comment by Evolvee** [comment]
rev hehexd
