### ISSUE TITLE
The Lady's Necklace quest chain 

### ISSUE THREAD

**Issue by DemonHunter1992** [Atlantiss/NetherwingBugtracker#1345]
[//]: # (Enclose links to things related to the bug using http://wowhead.com or any other TBC database.)
[//]: # (You can use screenshot ingame to visual the issue.)
[//]: # (Write your tickets according to the format:)
[//]: # ([Quest][Azuremyst Isle] Red Snapper - Very Tasty!)
[//]: # ([NPC] Magistrix Erona)
[//]: # ([Spell][Mage] Fireball)
[//]: # ([Npc][Drop] Ghostclaw Lynx)
[//]: # ([Web] Armory doesnt work)

**Description**: https://www.wowhead.com/quest=9180/journey-to-undercity when the Lady Sylvanas Windrunner start singing and 4 ghosts are spawned behind her

**Current behaviour**: ghosts are facing away from Lady Sylvanas Windrunner

**Expected behaviour**: ghosts are facing towards Lady Sylvanas Windrunner

**Server Revision**: 2140

**Comment by Evolvee** [comment]
![image](https://user-images.githubusercontent.com/1942409/46631130-cea6fe80-cb46-11e8-8cca-2060f3cd0643.png)

**Comment by DemonHunter1992** [comment]
any info, was my bug right or not, here is more info
![wowscrnshot_093018_012113](https://user-images.githubusercontent.com/43724598/46910689-b5d48980-cf48-11e8-9c14-e351a985dbc7.jpg)

**Comment by Shanghi** [comment]
Whenever this is fixed, https://github.com/Atlantiss/AtlantissTBCBT/issues/3656 should be too

**Comment by Wolffenstein** [comment]
Fixed in rev 2406.
