### ISSUE TITLE
[NPC]Drywallow Daggermaw#4345] missing patrol in Dustwallow

### ISSUE THREAD

**Issue by Tenoutoften** [Atlantiss/NetherwingBugtracker#1346]
**Description**: 
[[NPC]Drywallow Daggermaw#4345](https://www.wowhead.com/npc=4345/drywallow-daggermaw) missing patrol, can be seen [here](https://youtu.be/5SgOYJNk8uI?t=41)
![2ac48033799855137603c17910007ea1](https://user-images.githubusercontent.com/34839199/46584640-f4100b80-ca65-11e8-8283-356499d304ea.png)

**Current behaviour**:
No patrols

**Expected behaviour**: 
Expecting some [[NPC]Drywallow Daggermaw#4345](https://www.wowhead.com/npc=4345/drywallow-daggermaw) to patrol the waters

**Server Revision**: 
2137

**Comment by aresbrutus** [comment]
That is not a patrol, just long range of random movement. 

https://gfycat.com/SafeWeakFanworms

**Comment by Tenoutoften** [comment]
Aha

**Comment by aresbrutus** [comment]
The white named croc however does patrol on NW like he is supposed to!
