### ISSUE TITLE
[NPC] Silvermoon Guard

### ISSUE THREAD

**Issue by ircfelix** [Atlantiss/NetherwingBugtracker#1347]
**Description**: 
Silvermoon Guards patrolling between the dead scar and fairbreeze village behave strangely when there is a Springpaw Stalker stealthed nearby.

**Current behaviour**:
They start chasing the Springpaw Stalker, followed by almost instantly resetting, resulting in a very strange looking kind of dance.

**Expected behaviour**: 
They should either kill the stealthed Springpaw Stalkers or not.

**Server Revision**: 
2137

**Comment by Evolvee** [comment]
duplicate https://github.com/Atlantiss/NetherwingBugtracker/issues/158
