### ISSUE TITLE
[NPC] Vengeful Ancient

### ISSUE THREAD

**Issue by Retinus** [Atlantiss/NetherwingBugtracker#1348]
**Description**: Entry: 4030, Id: 2, GUIDLow: 85750

**Current behaviour**: He is not moving at all

**Expected behaviour**: From all the rare mobs i 've seen till now he is the only one not moving. Some wowhead comments say that "Finding this one will take a while. He roams a big portion of a heavily quested area."

**Server Revision**: 2137

**Comment by aresbrutus** [comment]
Fixed in rev `Tycho`.
