### ISSUE TITLE
quest: Protect Kanati Greycloud

### ISSUE THREAD

**Issue by DemonHunter1992** [Atlantiss/NetherwingBugtracker#1349]
[//]: # (Enclose links to things related to the bug using http://wowhead.com or any other TBC database.)
[//]: # (You can use screenshot ingame to visual the issue.)
[//]: # (Write your tickets according to the format:)
[//]: # ([Quest][Azuremyst Isle] Red Snapper - Very Tasty!)
[//]: # ([NPC] Magistrix Erona)
[//]: # ([Spell][Mage] Fireball)
[//]: # ([Npc][Drop] Ghostclaw Lynx)
[//]: # ([Web] Armory doesnt work)

**Description**: https://www.wowhead.com/quest=4966/protect-kanati-greycloud In this quest you need to defend NPC, i failed at protecting NPC and he died 2 days ago, today i was passing same NPC and i saw ? sign so i completed quest !?

**Current behaviour**: even when NPC died and you fail to defend him , when he respawns you can finish quest 

**Expected behaviour**: quest fails when the NPC dies 

**Server Revision**: 2141

**Comment by aresbrutus** [comment]
#947

Duplicate.

**Comment by DemonHunter1992** [comment]
:pepoSad:
