### ISSUE TITLE
[Quest][Dustwallow Marsh] Unleash the Raptors

### ISSUE THREAD

**Issue by Mikik3jr** [Atlantiss/NetherwingBugtracker#1350]
[//]: # (Enclose links to things related to the bug using http://wowhead.com or any other TBC database.)
[//]: # (You can use screenshot ingame to visual the issue.)
[//]: # (Write your tickets according to the format:)
[//]: # ([Quest][Azuremyst Isle] Red Snapper - Very Tasty!)
[//]: # ([NPC] Magistrix Erona)
[//]: # ([Spell][Mage] Fireball)
[//]: # ([Npc][Drop] Ghostclaw Lynx)
[//]: # ([Web] Armory doesnt work)

**Description**: 
In this quest you place down a piece of meat at the middle of a camp and it summons 3 raptors that attack the grimtotem taurens there.
**Current behaviour**:
I saw the 3 raptors that were summoned down. 1 was front and 2 was behind. As I saw the 2 raptor behind followed their leader on the front. They started to patrol, but when they killed 2 taurens the front raptor disappeared and after that the 2 raptors stopped moving. The problem is I came back 1.5 hours later and they were still there.
The time I released them:
![wowscrnshot_100718_154222](https://user-images.githubusercontent.com/43505031/46585139-22ddb000-ca6d-11e8-9cdc-fbf67d74c72a.jpg)
1.5 hours later I killed them:
![wowscrnshot_100718_171923](https://user-images.githubusercontent.com/43505031/46585141-25400a00-ca6d-11e8-8381-102c5dc21ad4.jpg)

**Expected behaviour**: 
Should they despawn? Or patrol until they die? Actually I don't know this sorry
**Server Revision**: 
2137

**Comment by wtRCH** [comment]
More info might be here: #1369

**Comment by Evolvee** [comment]
rev hehexd
