### ISSUE TITLE
[Item] Linken's boomerang 

### ISSUE THREAD

**Issue by Firroth** [Atlantiss/NetherwingBugtracker#1351]
[Item] [Linken's boomerang](https://www.wowhead.com/item=11905/linkens-boomerang#comments)

**Current behaviour**:
Currently it has 100% stun rate. Out of 20 throws 20 stuns. Disarm is also pretty often, around 12 out of 20. Both effects are also added, rather than 1 (stun+disarm).

As of now it's OP trinket for PvP, especially against meele classes.

**Expected behaviour**: 
Only 1 effect should be added to target if proc chance triggers. Proc chance should not be 100% on stun nor disarm, it should be around 20% I guess or even lower.

![screenshot_4](https://user-images.githubusercontent.com/43505196/46585176-a8f9f680-ca6d-11e8-8b5b-d4e1443de2bd.png)

**Server Revision**: 
2137

**Comment by Firroth** [comment]
You mean like me being on lvl 70? or on higher lvl mobs/players?
If latter then I tried it on the same lvl - 60 druid he got stunned and disarmed. Went to AQ20 hit lvl 61-62mob same thing.

So what you want to say, that in vanilla it was supposed to work like that? where two lvl 60's fight, 1 uses it and other gets stunned and disarmed? For sure it wasn't like that. And I can only expect same issue will occur between 2 lvl 70's.

**Comment by wowthings** [comment]
I can vouch on his claims, the trinket has a chance to disarm OR stun, and he stunned and disarmed me with a single use. This item will be really unfair in a pvp situation.

**Comment by Evolvee** [comment]
it doesnt work on level 70 players, there is like 2% chance

**Comment by Firroth** [comment]
Then lvl 70 wise it works, like it should, **but lvl 60wise not.** 
This comment also proves it:
![screenshot_5](https://user-images.githubusercontent.com/43505196/46586157-abaf1880-ca7a-11e8-842e-e84e37380c3e.png)

By taking context from it, it says 25 ppl would need to use it so "disarm" proc would at least apply. Right now? It applies with rate of 90%+, and stun 100%. If it has 100% chance why would be written "chance". 
![screenshot_6](https://user-images.githubusercontent.com/43505196/46586191-0fd1dc80-ca7b-11e8-8629-0ec3c071da5f.png)
It should have deals damage AND stuns / disarms not chance to stun / disarm.

While it may not be an issue on lvl 70, it can and WILL on lvling part up to 70 if people will notice how it works.

**Comment by Tereneckla** [comment]
100% chance to stun on players and npcs at lvl 70.

**Comment by Evolvee** [comment]
@toto6 u fckin hack -.-

**Comment by Evolvee** [comment]
should be fixed @Tereneckla ?

**Comment by Tereneckla** [comment]
¯\_(ツ)_/¯
give ptr update
I threw my live boomerang away

**Comment by Evolvee** [comment]
k test it after update xd and close/comment here after
