### ISSUE TITLE
Steamwheedle Cartel reputation

### ISSUE THREAD

**Issue by samemari** [Atlantiss/NetherwingBugtracker#1352]
[//]: # (Enclose links to things related to the bug using http://wowhead.com or any other TBC database.)
[//]: # (You can use screenshot ingame to visual the issue.)
[//]: # (Write your tickets according to the format:)
[//]: # ([Quest][Azuremyst Isle] Red Snapper - Very Tasty!)
[//]: # ([NPC] Magistrix Erona)
[//]: # ([Spell][Mage] Fireball)
[//]: # ([Npc][Drop] Ghostclaw Lynx)
[//]: # ([Web] Armory doesnt work)

**Description**: 
There is Steamwheedle Cartel in the WoW
![wowscrnshot_100718_223606](https://user-images.githubusercontent.com/29822974/46586058-938ec780-ca81-11e8-8c54-a938f230fe8c.jpg)

**Current behaviour**:
Message about increasing reputation with Steamwheedle Cartel doesn't mean that rep with any city from cartel will be increased (at least with Gadgetzan):
![wowscrnshot_100718_223428](https://user-images.githubusercontent.com/29822974/46586077-de104400-ca81-11e8-934a-836ef48ffb78.jpg)
![wowscrnshot_100718_223256](https://user-images.githubusercontent.com/29822974/46586078-de104400-ca81-11e8-8e52-628ce54440de.jpg)

**Expected behaviour**: 
Increasing reputation with Cartel must increase rep with all cities from Cartel

**Server Revision**: 
2137

**Comment by Evolvee** [comment]
Its because these npcs dont get rep anymore after you are friendly ^^

**Comment by samemari** [comment]
ehm, I was neutral with all other cities - it's the first point. I have addon that autoswitch to the last faction that got rep increase. I didn't got increased rep with any other city from Steamwheedle cartel. Sry, got friendly with all Steamwheedle cartel now, so can't make yet another screenshot :(

**Comment by Evolvee** [comment]
Oh yea, so the issue is probably that the reputation is not given at all except to Gadgetzan.

**Comment by Retinus** [comment]
**Description**: Bloodsail Faction mobs at STV.

**Current behaviour**: Killing the mentioned mobs decreases your rep with Bloodsail Buccaneers faction. 

**Expected behaviour**: Decrease your rep with Bloodsail Buccaneers faction but also increase your rep with Booty Bay.

**Server Revision**: 2207

**Comment by Dimbleglim** [comment]
The Bloodsails in tanaris should give BB rep till exalted without losing bloodsail buckaneers rep. Been that way since vanilla. It's how you get the bloodaisl admiral hat without losing bb access.
https://www.wowhead.com/guides/achievements/reputation/a-guide-for-the-insane#-steamwheedle-cartel
