### ISSUE TITLE
[NPC][Silithus] Hive'Regal Hive Lord

### ISSUE THREAD

**Issue by Firroth** [Atlantiss/NetherwingBugtracker#1353]
[NPC] [Hive'Regal Hive Lord](https://web.archive.org/web/20090615020207/http://wow.allakhazam.com:80/db/mob.html?wmob=11734)
[Spell] [Berserker Charge](https://www.wowhead.com/spell=19471/berserker-charge)

**Current behaviour**:
[NPC] [Hive'Regal Hive Lord](https://web.archive.org/web/20090615020207/http://wow.allakhazam.com:80/db/mob.html?wmob=11734) doesn't seem to use [Spell] [Berserker Charge](https://www.wowhead.com/spell=19471/berserker-charge).

**Expected behaviour**: 
[NPC] [Hive'Regal Hive Lord](https://web.archive.org/web/20090615020207/http://wow.allakhazam.com:80/db/mob.html?wmob=11734) should be using [Spell] [Berserker Charge](https://www.wowhead.com/spell=19471/berserker-charge).

**Server Revision**: 
2137

**Comment by Evolvee** [comment]
rev 439kcolb
