### ISSUE TITLE
[Quest][Silithus] A Pawn on the Eternal Board - crashing server

### ISSUE THREAD

**Issue by Firroth** [Atlantiss/NetherwingBugtracker#1355]
[Quest][Silithus] [A Pawn on the Eternal Board](https://www.wowhead.com/quest=8519/a-pawn-on-the-eternal-board))

**Current behaviour**:
Crashes the server.

**Expected behaviour**: 
Should not crash the server.

If crash is handled then event should look like that:
https://www.youtube.com/watch?v=V_wU8PhIIWU

**Server Revision**: 
2137

**Comment by Wolffenstein** [comment]
Fixed in rev 2143.
