### ISSUE TITLE
[Warrior][Spell] Devastate

### ISSUE THREAD

**Issue by manslaughter** [Atlantiss/NetherwingBugtracker#1356]
**Description**: Warrior Protection final talent

**Current behaviour**: Does expected damage with 1-3 stacks of sunder; does very little damage with 4-5 stacks
https://i.imgur.com/BZzQ1Bp.png

**Expected behaviour**: Damage ramps up with sunder armor stacks

**Server Revision**: 2137

**Comment by manslaughter** [comment]
On further testing, this seems to be an issue with armor underflow, as other abilities/attacks also do much less damage when the armor reduction reaches a certain amount, and the armor reduction amount to cause this to happen varies by enemy level.

**Comment by Wolffenstein** [comment]
Fixed in rev 2151.
