### ISSUE TITLE
Quest: An Aggressive Defense - Foulweald problem CORE Mechanic Rogue stealth

### ISSUE THREAD

**Issue by craigsurbrook** [Atlantiss/NetherwingBugtracker#1357]
lvl 27 rogue against lvl 23 and 24 Foulweald mobs (which are needed for quest An Aggressive Defense).

I can be stealthed, even use "distract" on the mobs, approach from behind to attempt ambush or backstab.

Current Behavior: 100% of the time (every single time),, no matter how quick you are, if you get in Ambush or Backstab range they detect you immediately and attack you.

Expected Behavior: A rogue 3-4 lvls higher than the mob, using distract, approaching directly from behind should NOT be detected so that an Ambush or Backstab or Cheap Shot can be used. Unfortunately, this is, at the moment, impossible with these mobs.

[//]: # (Enclose links to things related to the bug using http://wowhead.com or any other TBC database.)
[//]: # (You can use screenshot ingame to visual the issue.)
[//]: # (Write your tickets according to the format:)
[//]: # ([Quest][Azuremyst Isle] Red Snapper - Very Tasty!)
[//]: # ([NPC] Magistrix Erona)
[//]: # ([Spell][Mage] Fireball)
[//]: # ([Npc][Drop] Ghostclaw Lynx)
[//]: # ([Web] Armory doesnt work)

**Description**: 

**Current behaviour**:

**Expected behaviour**: 

**Server Revision**:

**Comment by duzyizly** [comment]
looks like fixed (probably with recent stealth fixes).
tested on ptr rev 3403, rogue lvl 25 with 0/5 Mater od deception talent.

![WoWScrnShot_062420_111938](https://user-images.githubusercontent.com/43931626/85529010-ebca7c00-b60c-11ea-81ef-a838acb0a2b4.jpg)
![WoWScrnShot_062420_111943](https://user-images.githubusercontent.com/43931626/85529017-ecfba900-b60c-11ea-82c7-e504e2100758.jpg)
![WoWScrnShot_062420_112007](https://user-images.githubusercontent.com/43931626/85529019-ed943f80-b60c-11ea-9106-99dfdef00ed4.jpg)
![WoWScrnShot_062420_112014](https://user-images.githubusercontent.com/43931626/85529020-ee2cd600-b60c-11ea-899a-c25a5fd44765.jpg)
