### ISSUE TITLE
Trying to take taxi while stealthed.

### ISSUE THREAD

**Issue by craigsurbrook** [Atlantiss/NetherwingBugtracker#1358]
[//]: # (Enclose links to things related to the bug using http://wowhead.com or any other TBC database.)
[//]: # (You can use screenshot ingame to visual the issue.)
[//]: # (Write your tickets according to the format:)
[//]: # ([Quest][Azuremyst Isle] Red Snapper - Very Tasty!)
[//]: # ([NPC] Magistrix Erona)
[//]: # ([Spell][Mage] Fireball)
[//]: # ([Npc][Drop] Ghostclaw Lynx)
[//]: # ([Web] Armory doesnt work)

**Description**: 
Rogue, goes stealth, approaches Flight Master, clicks and get map of FP's. When stealthed and an FP is clicked the error message "You can't take a taxi while shapeshifted!" appears.

**Current behaviour**:
When a rogue is stealthed the Flight Master thinks you are "shapeshifted" and not allowed to take the taxi.

**Expected behaviour**: 
When a rogue is stealthed and picks and FP to fly to at the Flight Master, the rogue will unstealth automatically and begin flight to the FP that was selected.

**Server Revision**:

**Comment by TerawattHF** [comment]
Shouldn't the expected behaviour be that the rogue leaves stealth when initially talking to the flight master, before bringing up the flight map?

**Comment by craigsurbrook** [comment]
TerawattHF, now that you mention it, yeah, it should take the rogue out of stealth just like you are dismounted when you click the Flight Master. That doesn't happen though, but, yes I agree with you.

**Comment by Wolffenstein** [comment]
It's working now.
