### ISSUE TITLE
[NPC]Firemane Flamecaller#4334 should keep [Spell]Fire Shield#18968 up outside of combat

### ISSUE THREAD

**Issue by Tenoutoften** [Atlantiss/NetherwingBugtracker#1359]
**Description**: 
[[NPC]Firemane Flamecaller#4334](https://www.wowhead.com/npc=4334/firemane-flamecaller) should keep [[Spell]Fire Shield#18968](https://www.wowhead.com/spell=18968/fire-shield) up outside of combat. Currently doesn't.

[Video here](https://youtu.be/0S-Hrc8gdpc?t=71), also looks like the other ones does it so this would be consistent:
https://github.com/Atlantiss/NetherwingBugtracker/issues/1343
https://github.com/Atlantiss/NetherwingBugtracker/issues/1344

**Expected behaviour**: 
Should keep [[Spell]Fire Shield#18968](https://www.wowhead.com/spell=18968/fire-shield) up outside of combat.

**Server Revision**: 
2137

**Comment by Evolvee** [comment]
rev hehexd
