### ISSUE TITLE
([Spell][Rogue]Steath)

### ISSUE THREAD

**Issue by killablink** [Atlantiss/NetherwingBugtracker#136]
[//]: # (Enclose links to things related to the bug using http://wowhead.com or any other TBC database.)
[//]: # (You can use screenshot ingame to visual the issue.)
[//]: # (Write your tickets according to the format:)
[//]: # ([Quest][Azuremyst Isle] Red Snapper - Very Tasty!)
[//]: # ([NPC] Magistrix Erona)
[//]: # ([Spell][Mage] Fireball)
[//]: # ([Npc][Drop] Ghostclaw Lynx)
[//]: # ([Web] Armory doesnt work)

**Description**: It's taking way to long to stealth possibly due to spell batching

**Current behaviour**: Takes too long to stealth :https://gyazo.com/87c2a672e319513ee529426e72b57921

**Expected behaviour**: Stealthing is pretty much instant https://youtu.be/xF4Rx1sQYQU?t=113

**Server Revision**:

**Comment by Nicemann1089** [comment]
is working fine for me. it is your connection/distance to server maybe?

**Comment by ahlens** [comment]
I have 50 ms via WiFi and I have that delay too. On Sunwell with the same ping issue does not exists. I think author is right.

**Comment by The14me** [comment]
Work fine to me now.If still have a problem please re-open.
