### ISSUE TITLE
[NPC] Anathemus

### ISSUE THREAD

**Issue by ScottieDOESknow** [Atlantiss/NetherwingBugtracker#1360]
**Description**:  Rare elite level 45

**Current behaviour**: Hit nearly 1k non-crushing, non-crit on level 49 leather (1141 armor) 

https://gyazo.com/f0993ec7d89cc9817f9d8c2e06865244

**Expected behaviour**: Damage should be much lower.

TBC - http://db.excalibur.ws/?npc=2754
Classic 1 - https://classicdb.ch/?npc=2754
Classic 2 - https://vanillawowdb.com/?npc=2754

**Server Revision**:

**Comment by The14me** [comment]
https://i.imgur.com/bw8dWhS.png

**Comment by Evolvee** [comment]
rev hehexd
