### ISSUE TITLE
[Movement][NPC]Firemane Scout/Ash Tail#4329/#4331 missing pair patrols

### ISSUE THREAD

**Issue by Tenoutoften** [Atlantiss/NetherwingBugtracker#1361]
**Description**: 
It looks to me that some patrols are off here.
![74235236wa6tw](https://user-images.githubusercontent.com/34839199/46597333-ffa01880-cadf-11e8-81fe-aacbd0983697.png)
One comment indicated patrols are in pairs, just as seen in this video from [5 years ago](https://youtu.be/lEu0MB8ErI0?t=62) although from a different place:
![gps2](https://user-images.githubusercontent.com/34839199/46597502-953ba800-cae0-11e8-99d6-dd3f721cff45.png) 
Perhaps this singular [[NPC]Firemane Ash Tail#4331](https://db.excalibur.ws/?npc=4331) patrol in the cave is incorrect?

At this place:
![0fcd22dd58e430fdf76377273c6ae797](https://user-images.githubusercontent.com/34839199/46597378-29f1d600-cae0-11e8-814c-33c2cbf06b58.png)
There is one [[NPC]Firemane Scout#4329](https://db.excalibur.ws/?npc=4329) & [[NPC]Firemane Ash Tail#4331](https://db.excalibur.ws/?npc=4331)l looking very "stock", they stand completely still like this:
![b1ae85da221c45816df8059d3194894a](https://user-images.githubusercontent.com/34839199/46597410-43931d80-cae0-11e8-9ef8-2011557108a9.jpg)

**Current behaviour**:
No pair patrols.

**Expected behaviour**: 
Expecting some patrols to be in pairs, and there is definitely one missing patrol where the [wowhead comment](https://www.wowhead.com/quest=1169/deprecated-identifying-the-brood#comments:id=49233:reply=291908) suggests.

**Server Revision**: 
2137

**Comment by aresbrutus** [comment]
The pair that is standing still is patrolling a huge area together now, but I am not convinced by the other points. 

Fixed in rev `Tycho`.
