### ISSUE TITLE
[NPC][Movement]Lord Angler#14236 is lacking patrol

### ISSUE THREAD

**Issue by Tenoutoften** [Atlantiss/NetherwingBugtracker#1362]
**Description**: 
[[NPC]Lord Angler#14236](https://www.wowhead.com/npc=14236/lord-angler#comments) should have some sort of patrol and possibly several spawning positions(I can't figure this one out) basing patrol on [wowhead comment](https://www.wowhead.com/npc=14236/lord-angler#comments:id=208039) and pictures:
![24169-lord-angler](https://user-images.githubusercontent.com/34839199/46598371-2fe9b600-cae4-11e8-80a9-8e3cf9339ad8.jpg)
![57925-lord-angler](https://user-images.githubusercontent.com/34839199/46598372-2fe9b600-cae4-11e8-9d96-e917c30338e9.jpg)
![224617-lord-angler](https://user-images.githubusercontent.com/34839199/46598374-30824c80-cae4-11e8-9d59-9f281961d960.jpg)
![256466-lord-angler](https://user-images.githubusercontent.com/34839199/46598375-30824c80-cae4-11e8-9eb3-7fad2e23d117.jpg)
![277015-lord-angler-for-caparison-he-is-a-little-larger-patrols-a-longer-path-and-is-blu](https://user-images.githubusercontent.com/34839199/46598376-30824c80-cae4-11e8-9731-ed14e14e8063.jpg)
![277016-lord-angler-no-longer-spawns-on-a-island-he-remains-underwater-all-the-time-now](https://user-images.githubusercontent.com/34839199/46598377-30824c80-cae4-11e8-86e1-927a0fa950c8.jpg)
![621079-lord-angler-updated-model](https://user-images.githubusercontent.com/34839199/46598378-30824c80-cae4-11e8-91b6-30fed8698c16.jpg)

Currently stands completely still at:
![ce924a27089483735eb7357adf645a94](https://user-images.githubusercontent.com/34839199/46598391-3841f100-cae4-11e8-9f21-db97031d3e53.png)

**Expected behaviour**: 
Expected to move around / patrol

**Server Revision**: 
2137

**Comment by aresbrutus** [comment]
Fixed in rev `Tycho`.
