### ISSUE TITLE
[NPC][Western Plaguelands]Scarlet Hound

### ISSUE THREAD

**Issue by DeltaLoads** [Atlantiss/NetherwingBugtracker#1363]
[//]: # (Enclose links to things related to the bug using http://wowhead.com or any other TBC database.)
[//]: # (You can use screenshot ingame to visual the issue.)
[//]: # (Write your tickets according to the format:)
[//]: # ([Quest][Azuremyst Isle] Red Snapper - Very Tasty!)
[//]: # ([NPC] Magistrix Erona)
[//]: # ([Spell][Mage] Fireball)
[//]: # ([Npc][Drop] Ghostclaw Lynx)
[//]: # ([Web] Armory doesnt work)

**Description**: 
When attacking Scarlet Hunter, you can pull him and then have pet take aggro, then use feign death and his pet Scarlet Hound will despawn.
Example : https://streamable.com/tx3kx
**Current behaviour**:
Scarlet Hound despawns if player pulls aggro on Scarlet Hunter and then uses Feign Death
**Expected behaviour**: 
Scarlet Hound shouldn't despawn and should instead attack pet
**Server Revision**: 
2137

**Comment by Easyfraggy** [comment]
Is this general behavior on mobs with minions or just this particular one?

**Comment by DeltaLoads** [comment]
just tested it on Razormane Hunter in Barrens and same thing happened

**Comment by Easyfraggy** [comment]
it could be a global problem, so if anyone encounters mobs where this is possible/not possible please note them here.

**Comment by Evolvee** [comment]
its problem of individual NPCs because the pet needs to be added through WolfAI to inherit the guardian and pet AI, these npcs had it casted on reset

listed npcs above fixed in rev 439kcolb
