### ISSUE TITLE
[Warrior][Talent-Sword Specialization] UPDATE 3

### ISSUE THREAD

**Issue by bloodwindz** [Atlantiss/NetherwingBugtracker#1365]
[//]: # (Enclose links to things related to the bug using http://wowhead.com or any other TBC database.)
[//]: # (You can use screenshot ingame to visual the issue.)
[//]: # (Write your tickets according to the format:)
[//]: # ([Quest][Azuremyst Isle] Red Snapper - Very Tasty!)
[//]: # ([NPC] Magistrix Erona)
[//]: # ([Spell][Mage] Fireball)
[//]: # ([Npc][Drop] Ghostclaw Lynx)
[//]: # ([Web] Armory doesnt work)

**Description**: 

**Current behaviour** It does not proc  from sunder

**Expected behaviour**: Sword spec should proc from all attacks that do and dont do damage but do   and "require a melee weapon".
 the enemy including hamstring sunder etc  

http://www.arenajunkies.com/topic/13052-sword-spec-proc-confirm   march 12 2008

https://www.wowhead.com/forums&topic=36696  patch 2,43 

https://www.youtube.com/watch?v=VNgGCGl0_S0   on 23:07

**Server Revision**: 2451 17 december

**Comment by Godmatik** [comment]
Rev 4015

Still an issue

Attacks that deal no damage (such as Sunder Armor) are not proccing Sword Spec still

**Comment by Godmatik** [comment]
Check again after new spell proc branch is on PTR

**Comment by Godmatik** [comment]
Fixed in upcoming new proc branch
