### ISSUE TITLE
[Dustwallow Marsh] Raptor Captor

### ISSUE THREAD

**Issue by Azalen** [Atlantiss/NetherwingBugtracker#1366]
**Description**: 
https://www.wowhead.com/quest=27242/raptor-captor
http://db.hellfire-tbc.com/?quest=11146

**Current behaviour**:
Using the Item shows a 4 second channel time cast but after 0.5 seconds the quest objective is fulfilled. Then the channel gets interupted by next attack of the raptor, then the raptor despawns.

**Expected behaviour**: 
0,5 second channel is correct but cast bar needs to be 0,5 second as well.
Proof: https://www.youtube.com/watch?v=kBxhf0mXu_c

**Server Revision**: 
[2137]

**Comment by Azalen** [comment]
Also, there is no indication the item can be used. If I put it into my interface on a button slot the item is blacked/greyed out (telling me i cannot use it) which is correct. But if the mob is below 10% the item should lose that and show me it us ready to use. 
It is usable though just still blacked/greyed out.

**Comment by wtRCH** [comment]
- Make cast bar 0.5 sec channel
- When mob is below 10% this item should be available to use from the action bar

@pelekon

**Comment by Tereneckla** [comment]
All information you provided is from after Cataclysm.
https://www.wowhead.com/quest=11146/deprecated-raptor-captor is the pre-cata quest.

![image](https://user-images.githubusercontent.com/50233983/72886478-2a7ca300-3d0a-11ea-8f98-4a5d09afe8d5.png)
Considering this comment you would not really care about spell-pushback with a 0.5 sec channel.
Capturing the raptor after the full channel of 4 seconds should be correct then.

Item does light up in the action bar now though.

**Comment by Evolvee** [comment]
so whats broken here?

**Comment by Tereneckla** [comment]
The item you use starts a 4 second channel. After 0.5 seconds channeling you get quest credit and keep channeling. That just feels wrong, but I don't have any proof how it should be.

That comment just leads to think it should 4 second channel with quest credit after the full 4 seconds.

**Comment by Evolvee** [comment]
fixed in next rev
