### ISSUE TITLE
0 durability weapon problem

### ISSUE THREAD

**Issue by MattiasWallander** [Atlantiss/NetherwingBugtracker#1367]
**Description**: 
Weapon completely broken at 0 durability but I'm still hitting mobs using my staff while getting unarmed skill increase.

**Current behaviour**:
Staff still being used when attacking (at least animation-wise) while it's at 0 durability.

**Expected behaviour**: 
Should start punching the mobs when weapon breaks.

**Server Revision**: 
no clue

Here's video
https://gfycat.com/UnlawfulGlassAmericanblackvulture

**Comment by Tereneckla** [comment]
Fixed
