### ISSUE TITLE
Hearthstone location

### ISSUE THREAD

**Issue by Thorgrimme** [Atlantiss/NetherwingBugtracker#1368]
[//]: # (Enclose links to things related to the bug using http://wowhead.com or any other TBC database.)
[//]: # (You can use screenshot ingame to visual the issue.)
[//]: # (Write your tickets according to the format:)
[//]: # ([Quest][Azuremyst Isle] Red Snapper - Very Tasty!)
[//]: # ([NPC] Magistrix Erona)
[//]: # ([Spell][Mage] Fireball)
[//]: # ([Npc][Drop] Ghostclaw Lynx)
[//]: # ([Web] Armory doesnt work)

**Description**: 

**Current behaviour**:Currently the tooltip on the hearthstone only mentions which zone it's bound to.

**Expected behaviour**: In some zones there are more then one inn locations, I believe it should say which inn it's bound to not the zone.

**Server Revision**:

**Comment by Thorgrimme** [comment]
Well for example in dustmallow marsh it's 2 inn location, there's no way of knowing which u bound your herthstone to. Ill try i look for evidence how it was back in retail, but who knows.

**Comment by Thorgrimme** [comment]
https://classicdb.ch/?item=6948
![wow_2018-10-08_15-13-29](https://user-images.githubusercontent.com/43525297/46611035-dc3f9280-cb0c-11e8-9348-415d134b0a37.jpg)

Well from this database it says "Use: Returns you to <Home>. Speak to an Innkeeper in a different place to change your home location.", and ingame screenshot do u want to make Booty Bay your new home, but the hs says its bound to stranglethorn vale.

**Comment by Thorgrimme** [comment]
http://web.archive.org/web/20051214031238/http://www.thottbot.com:80/?s=Hearthstone

**Comment by Wolffenstein** [comment]
Fixed in rev 2144.
