### ISSUE TITLE
[Dustwallow Marsh] Unleash the Raptors

### ISSUE THREAD

**Issue by Azalen** [Atlantiss/NetherwingBugtracker#1369]
**Description**: 
https://www.wowhead.com/quest=27243/unleash-the-raptors

**Current behaviour**:
Only one small pack of three raptors spawns and after they killed all mobs they stand still in the middle of the camp not despawning or getting killed.

**Expected behaviour**: 
Event with multiple raptor spawn points them basically overuninng the village

https://www.youtube.com/watch?v=OF3LcLxTBNo
https://www.youtube.com/watch?v=fihYbRrx2H8
https://www.youtube.com/watch?v=Yl3JZ4Cb2wA

Proof that it was like that in 2.3 already:

> Posted: Jan 10th 2008 8:20pm | IP: Logged | Reply to this
> Therezax
> *
> 92 posts
> Score: Decent 
> Yeap, 41, 12 is where I found the village, and just place the meat right next to the giant wind mill, which is kinda hard to miss. 
> 
> This quest was pretty cool. When you set down the meat, about 30 raptors come outta know where and just start owning everyone. Probably the coolest quest I've ever done.
Source: https://web.archive.org/web/20080610105210/http://wow.allakhazam.com:80/db/quest.html?wquest=11147

**Server Revision**: 
[2137]

**Comment by wtRCH** [comment]
Duplicate, refered to #1350
