### ISSUE TITLE
[Spell][Priest] Prayer of Mending heal reaction and batching

### ISSUE THREAD

**Issue by Jezofine** [Atlantiss/NetherwingBugtracker#137]
**Description**:
Prayer of Mending is a reactive spell and should apply heal after taking damage.

**Current behaviour**:
[In video about spell batching](https://youtu.be/r7CSJqQOypc?t=194) Prayer of Mending heal applies in the same batch with taking damage (when Evo hits Pegla) or applies instantly on taking hit (selfhealing vs mob).

**Expected behaviour**:
1. Target takes damage first
2. Some time after takeing damage PoM activates and healing applies.
[Demostration gif](https://j.gifs.com/oQxZ8X.gif)
[Video](https://youtu.be/OxGdQ_7RgBQ?t=89) is from wotlk prepatch (28.10.2008), but there is no info about changing PoM reaction in this patch.. I will try to find more videos later.

UPD.
[10.05.2008](https://youtu.be/WlHCKJjw8Ww?t=195): elem has priest shield and PoM, watch on 0.25x.
1. Absorb
2. -527 - damage, you can see his health bar decreased, although it's kinda blurry.
3. +558 - healing from PoM, health bar restored back to full.

Also self healing should not be batched at all as stated in [blue post](https://www.wowhead.com/bluetracker?topic=13087818929#131814318748). Only damage/healing on other subjects should be batched.

**Comment by Jezofine** [comment]
Well, I rewatched videos and not sure about it. Health bar and PoM animation delay may be caused by latency or UI tikcs.

**Comment by Tenoutoften** [comment]
Request issue to be re-opened if you figure it out
