### ISSUE TITLE
[Dustwallow Marsh] Prisoners of the Grimmtotem

### ISSUE THREAD

**Issue by Azalen** [Atlantiss/NetherwingBugtracker#1370]
**Description**: 
https://web.archive.org/web/20080621170343/http://wow.allakhazam.com:80/db/quest.html?wquest=11145

Droprate of the keys is way too low. From 15 kills I got 1 key so far.

**Expected behaviour**: 
https://web.archive.org/web/20071117024219/http://wow.allakhazam.com:80/db/item.html?witem=33061
says 17% but we cannot be sure because people kill these mobs for other quests as well so the real droprate should always be HIGHER than 17%. What made me post this report is a comment from another quest regarding this quest:

> Posted: Nov 14th 2007 6:22pm | IP: Logged | Reply to this
KccBaby
10 posts
Score: Decent 
Windmill @ 41, 22 
> Do this quest with "Prisoners of the Grimtotems" (Same quest giver). Key drop rate around 80%
> Source: https://web.archive.org/web/20080610105210/http://wow.allakhazam.com:80/db/quest.html?wquest=11147

Maybe 80% isnt the real droprate,too.  But reading this comment we can be pretty sure that 17% isnt the correct one as well. Also, there is no mention of an abysmal low droprate which indicates noone bothered to write because the droprate is decent.

Maybe you guys find smth better but right now it is too low to even bother with this quest at all.

**Server Revision**: 
[2137]

**Comment by Wolffenstein** [comment]
Its around 20% at the moment

**Comment by Thorgrimme** [comment]
Done this quest twice on 2 diff chars now, was fine both the times.

**Comment by Firroth** [comment]
I also had no problems.

**Comment by aresbrutus** [comment]
Fixed in rev `Tycho`.
