### ISSUE TITLE
Lava jumping

### ISSUE THREAD

**Issue by Tinnoan** [Atlantiss/NetherwingBugtracker#1371]
**Description**: Jumping in lava doesn't seem to affect the amount of damage you take versus not jumping at all. As can be seen in [this](https://streamable.com/dkufx) video the rate of damage ticks appear to be the same no matter if you jump or not.

**Expected behaviour**: Jumping in lava should sometimes (if timed right) not do ticks of damage to you at all.

**Server Revision**: 2137

**Comment by Jezofine** [comment]
Maybe [this video](https://youtu.be/2q0oEJjCsZI?t=132) will help, although it's vanilla.

**Comment by KevinTyrrell** [comment]
Can confirm that jumping has no effect on lava ticks. It also seems like the tick rate of the lava is too high. Doing a BRD lava run is actually impossible as of rev. 2936.

**Comment by The14me** [comment]
rev.3441 still active issue.

**Comment by Wolffenstein** [comment]
Fixed in rev 3444.
