### ISSUE TITLE
AOE spells can hit unflagged people?!

### ISSUE THREAD

**Issue by Mewmewww** [Atlantiss/NetherwingBugtracker#1374]
[//]: # (Enclose links to things related to the bug using http://wowhead.com or any other TBC database.)
[//]: # (You can use screenshot ingame to visual the issue.)
[//]: # (Write your tickets according to the format:)
[//]: # ([Quest][Azuremyst Isle] Red Snapper - Very Tasty!)
[//]: # ([NPC] Magistrix Erona)
[//]: # ([Spell][Mage] Fireball)
[//]: # ([Npc][Drop] Ghostclaw Lynx)
[//]: # ([Web] Armory doesnt work)

**Description**: Unflagged people can be hit by flagged peoples aoe or bouncing target spells

**Current behaviour**: Unflagged people can be hit by flagged peoples aoe or bouncing target spells

**Expected behaviour**: Unflagged people should be immune to all dmg

**Server Revision**: 2137

**Comment by Wolffenstein** [comment]
Which spell exactly did you test?

**Comment by Mewmewww** [comment]
Hunter volley, and multishot

**Comment by manslaughter** [comment]
Also confirmed with Warrior abilities Intimidating Shout, Thunder Clap, Cleave, and item M73 Frag Grenade

**Comment by Wolffenstein** [comment]
Fixed in rev 2425.
