### ISSUE TITLE
Untargetable - not quite uninvulnerable

### ISSUE THREAD

**Issue by Mewmewww** [Atlantiss/NetherwingBugtracker#1375]
[//]: # (Enclose links to things related to the bug using http://wowhead.com or any other TBC database.)
[//]: # (You can use screenshot ingame to visual the issue.)
[//]: # (Write your tickets according to the format:)
[//]: # ([Quest][Azuremyst Isle] Red Snapper - Very Tasty!)
[//]: # ([NPC] Magistrix Erona)
[//]: # ([Spell][Mage] Fireball)
[//]: # ([Npc][Drop] Ghostclaw Lynx)
[//]: # ([Web] Armory doesnt work)

**Description**: Untargetable NPC'S can still be killed with traps.

**Current behaviour**: Untargetable NPC'S can still be killed with traps.

**Expected behaviour**: Untargetable NPC'S shouldnt be able to take dmg.

**Server Revision**: 2137

**Comment by Tereneckla** [comment]
Fixed
