### ISSUE TITLE
[Quest][Eastern Plaguelands]Villains of Darrowshire

### ISSUE THREAD

**Issue by DeltaLoads** [Atlantiss/NetherwingBugtracker#1376]
[//]: # (Enclose links to things related to the bug using http://wowhead.com or any other TBC database.)
[//]: # (You can use screenshot ingame to visual the issue.)
[//]: # (Write your tickets according to the format:)
[//]: # ([Quest][Azuremyst Isle] Red Snapper - Very Tasty!)
[//]: # ([NPC] Magistrix Erona)
[//]: # ([Spell][Mage] Fireball)
[//]: # ([Npc][Drop] Ghostclaw Lynx)
[//]: # ([Web] Armory doesnt work)

**Description**: 
Whenever you are near spirits that are around quest items Skull of Horgus (https://www.wowhead.com/item=12956/skull-of-horgus) and Shattered Sword of Marduk (https://www.wowhead.com/item=12957/shattered-sword-of-marduk) you keep getting in and out of combat
**Current behaviour**:
Spectral Corpses, Spectral Marauders and Spectral Defenders are getting player in and out of combat
**Expected behaviour**:  
Spectral Corpses, Spectral Marauders and Spectral Defenders shouldn't get player in and out of combat
**Server Revision**: 
2137

**Comment by wtRCH** [comment]
Confirmed.

- Make Spectral Corpses, Spectral Marauders and Spectral Defenders not putting player near the in combat.

@pelekon

**Comment by Tereneckla** [comment]
It's this Trigger NPC de and respawning. Each time he puts nearby players in combat.
https://www.youtube.com/watch?v=PyU3m8uATeQ

**Comment by Evolvee** [comment]
its brazier

**Comment by Evolvee** [comment]
+todo
![image](https://user-images.githubusercontent.com/1942409/73581419-6db4df80-4489-11ea-8f26-8f8d8f6dd619.png)
![image](https://user-images.githubusercontent.com/1942409/73581423-70173980-4489-11ea-9386-7de94fb2cb30.png)

TARGET_UNIT_DEST_AREA_ENTRY

(linked trap to the purple gob)

**Comment by Evolvee** [comment]
fixed in next rev
