### ISSUE TITLE
Wand dmg afflicted by Curse of Weakness

### ISSUE THREAD

**Issue by Thorgrimme** [Atlantiss/NetherwingBugtracker#1377]
![wow_2018-10-08_19-20-49](https://user-images.githubusercontent.com/43525297/46623921-86c8ad00-cb2f-11e8-97f0-be085d762790.jpg)
![wow_2018-10-08_19-21-25](https://user-images.githubusercontent.com/43525297/46623937-96e08c80-cb2f-11e8-9527-7a58927be032.jpg)
![wow_2018-10-08_19-21-28](https://user-images.githubusercontent.com/43525297/46623943-9ea03100-cb2f-11e8-9946-f8164ebbdf0e.jpg)

**Description**: Wand dmg is affliceted by Curse of weakness as u can see out of these screenshots.

**Current behaviour**:

**Expected behaviour**: Wand dmg is magical dmg and shouldnt be affected by CoW.

**Server Revision**:

**Comment by Tereneckla** [comment]
Put in bigger topic
