### ISSUE TITLE
[Core] Hp update

### ISSUE THREAD

**Issue by Lephidiles** [Atlantiss/NetherwingBugtracker#1379]
[//]: # (Enclose links to things related to the bug using http://wowhead.com or any other TBC database.)
[//]: # (You can use screenshot ingame to visual the issue.)
[//]: # (Write your tickets according to the format:)
[//]: # ([Quest][Azuremyst Isle] Red Snapper - Very Tasty!)
[//]: # ([NPC] Magistrix Erona)
[//]: # ([Spell][Mage] Fireball)
[//]: # ([Npc][Drop] Ghostclaw Lynx)
[//]: # ([Web] Armory doesnt work)

**Description**: 
Hp of friendly player is not updated correctly when joining party but stays 100/XXXX and blinking red low hp until it actually take damage.

Also not correct when targeting / healing a friendly player not in group. Seems to go to 100/100 (percentage) but when it loose hp client think it is loosing actual hp and not percentage hp or something similar. Meaning the friendly player have red hp quite soon after a heal
**Current behaviour**:

**Expected behaviour**: 

**Server Revision**: 
2137

**Comment by Evolvee** [comment]
https://github.com/Atlantiss/NetherwingBugtracker/issues/397
https://github.com/Atlantiss/NetherwingBugtracker/issues/1038
https://github.com/Atlantiss/NetherwingBugtracker/issues/175

**Comment by Wolffenstein** [comment]
Fixed in rev 2211.
