### ISSUE TITLE
[Spell][Hunter]Hunter's Mark

### ISSUE THREAD

**Issue by Kantrul** [Atlantiss/NetherwingBugtracker#138]
[//]: # (Enclose links to things related to the bug using http://wowhead.com or any other TBC database.)
[//]: # (You can use screenshot ingame to visual the issue.)
[//]: # (Write your tickets according to the format:)
[//]: # ([Quest][Azuremyst Isle] Red Snapper - Very Tasty!)
[//]: # ([NPC] Magistrix Erona)
[//]: # ([Spell][Mage] Fireball)
[//]: # ([Npc][Drop] Ghostclaw Lynx)
[//]: # ([Web] Armory doesnt work)

**Description**: 
My female draenei doesn't perform any animation when casting Hunter's Mark
**Current behaviour**:
When Hunter's Mark is casted it does not perform any animation (may be related to draenei only)
**Expected behaviour**: 
Animation should be performed when casting Hunter's Mark
**Server Revision**: 2028

**Comment by Gniddikon** [comment]
Same issue on my female blood elf hunter.

**Comment by Kantrul** [comment]
https://www.youtube.com/watch?v=mJaQJw1Wf2s&list=PLMeJnlp72R7p-X7PgsMFqqjPtcxhF7kB_

Minute 2 applies Hunter's Mark in the centaur with the proper animation (the healing one). I know its vanilla but I don't think Blizzard removed the animation and readded it in wotlk, that makes no sense.

**Comment by Gniddikon** [comment]
You are actually correct. It's really weird, but Blizzard apparently removed the animation in patch 2.0.3 and added it back later on in Wotlk.

Source: https://wow-pl.gamepedia.com/Patch_2.0.3

> Hunter's Mark no longer has a casting animation.

Guess this report has to be closed.

**Comment by Kantrul** [comment]
You are correct, what a weird act lmao.
