### ISSUE TITLE
Tome of Nobility

### ISSUE THREAD

**Issue by SirPhoebos** [Atlantiss/NetherwingBugtracker#1380]
[Quest][Stormwind][Paladin] Tome of Nobility
[NPC] Duthorian Rall

**Description**:  Class Quest Tome of Nobility still available

**Current behaviour**: Quest becomes available at level 40, but gives no reward aside from a small amount of xp.

**Expected behaviour**: Never played a paladin before, but looking at Wowhead this is the quest that granted you the charger mount at level 40.  Since basic mounts are now available at 30, I think this quest should just be disabled.

**Server Revision**:

**Comment by Peglaa** [comment]
https://www.wowhead.com/quest=1661/the-tome-of-nobility#comments:id=183315:reply=20000

should be proof enough I suppose

**Comment by wtRCH** [comment]
- Remove class quest "Tome of Nobility" from the class trainers as the mount was changed to be able to train from Class Trainers.

@pelekon

**Comment by pelekon** [comment]
this quest is not assigned to any npc, closing
