### ISSUE TITLE
[NPC][The Barrens] Peon

### ISSUE THREAD

**Issue by eryczek1615** [Atlantiss/NetherwingBugtracker#1381]
**Description**:
 Peon - https://www.wowhead.com/npc=14901

**Current behaviour**:
There is few peons outside without movement/emote
https://imgur.com/FeIX908

**Expected behaviour**: 
This peons who are outside should have movment/emote

**Server Revision**: 
2137

**Comment by aresbrutus** [comment]
Also fixed guard emotes nearby in rev `Tycho`.
