### ISSUE TITLE
[NPC][Spell] Spawn of Hakkar - Broken Spell

### ISSUE THREAD

**Issue by Firroth** [Atlantiss/NetherwingBugtracker#1383]
[NPC] [Spawn of Hakkar](https://www.wowhead.com/npc=5708/spawn-of-hakkar)
[Spell] [Acid of Hakkar](https://classicdb.ch/?spell=12280)

**Current behaviour**:
[Spell] [Acid of Hakkar](https://classicdb.ch/?spell=12280) does nothing. No damage, no DoT, no visual effect.

**Expected behaviour**
[Spell] [Acid of Hakkar](https://classicdb.ch/?spell=12280) should give on his target undispalable 1min DoT, which deals damage every 2s.

**Server Revision**: 
2137

**Comment by Tereneckla** [comment]
Fixed
