### ISSUE TITLE
[NPC][Huntard][pet][talents] i cant reset pet talents

### ISSUE THREAD

**Issue by queeb3** [Atlantiss/NetherwingBugtracker#1385]
[//]: # (Enclose links to things related to the bug using http://wowhead.com or any other TBC database.)
[//]: # (You can use screenshot ingame to visual the issue.)
[//]: # (Write your tickets according to the format:)
[//]: # ([Quest][Azuremyst Isle] Red Snapper - Very Tasty!)
[//]: # ([NPC] Magistrix Erona)
[//]: # ([Spell][Mage] Fireball)
[//]: # ([Npc][Drop] Ghostclaw Lynx)
[//]: # ([Web] Armory doesnt work)

**Description**: 
cant reset pet talents
**Current behaviour**:
just takes the screen away and does not prompt a spec reset on pet
**Expected behaviour**: 
resets pet skills
**Server Revision**:

**Comment by mbzz88** [comment]
Yep, nothing happens https://youtu.be/P07Rw1HAUaQ

**Comment by Wolffenstein** [comment]
Fixed in rev 2148.
