### ISSUE TITLE
[NPC] Loro - Improved block and Shield Spike

### ISSUE THREAD

**Issue by Firroth** [Atlantiss/NetherwingBugtracker#1388]
[NPC] [Loro](https://www.wowhead.com/npc=5714/loro)

[Spell] [Improved Blocking](https://www.wowhead.com/spell=3639/improved-blocking)
[Spell] [Shield Spike](https://classicdb.ch/?spell=12782)

**Description**: 
Troll Mini-boss in Sunken Temple.

**Current behaviour**:
He uses [Spell] [Improved Blocking](https://www.wowhead.com/spell=3639/improved-blocking) but it does nothing at all, as dual wielding warrior he didn't block anything from me, other warrior and rogue. 
He also doesn't seem to use [Spell] [Shield Spike](https://classicdb.ch/?spell=12782).
When he uses [Spell] [Improved Blocking](https://www.wowhead.com/spell=3639/improved-blocking) he should also in the same time use [Spell] [Shield Spike](https://classicdb.ch/?spell=12782).

**Expected behaviour**: 
[Spell] [Improved Blocking](https://www.wowhead.com/spell=3639/improved-blocking) should block almost all meele attacks on him from the front/side and it should be used relatively often.
[Spell] [Shield Spike](https://classicdb.ch/?spell=12782) should be used and active when [Spell] [Improved Blocking](https://www.wowhead.com/spell=3639/improved-blocking) is in use.

![screenshot_1](https://user-images.githubusercontent.com/43505196/46636175-5a288b80-cb57-11e8-83ec-8ee8a78fe684.png)

**Server Revision**: 
2137

**Comment by Easyfraggy** [comment]
https://github.com/Atlantiss/NetherwingBugtracker/issues/1354

**Comment by Wolffenstein** [comment]
Fixed in rev 3400.
