### ISSUE TITLE
BIG -> Multible bugs found...  (12 Bugs)

### ISSUE THREAD

**Issue by SmokiFurry** [Atlantiss/NetherwingBugtracker#139]
Hello. I Try to remember all the bugs i found during my Rush - Session wth my paladin yesterday.
I will not open a new pannel for every issue ... maybe some of them are already reported.

Start with the class: Paladin (4 Bugs)
- Spell Costs: Spell on level 12 Costs 36s ... admin told me yesterday that is normal but ... on level 14 i don't have that much money.  also spell on level 16 costs 27s ... that,s a little weird ...  14 more than 16??? and it should be normal?  no way.
- Blessing of might cannot be casted if the spell Seal of the Crussader is active running. (More effective buff already active - error)
- Devotion aura sometimes (i think if you buff and click to fast, because aura has not th same global CD like normal spells) goes into a 0sec mode on the top right corner instead of a permanent buff.   it blinks with a timer on 0sec instead without time.... buff also works during that mode.
- Level 12 Revive quest: The npc in Goldhain send me to Durothar Rall in stormwind. there i can end the quest and should get the new one where i get a book and start a quest out of it and instantly end it up on Durothar Rall... The quest where i should recive the book got the error: You don't have the requirements for this quest!  ( i made it with level 14)

NPC's: (6 Bugs)
- Boars in elwyn forest and westfall so far get an enraged mode if they open a fight and i think all 15seconds.  as a paladin this is not that big deal and they are neutral so you can avoid surprises, but a warrior friend i met in the game died almost on every boar because they hit so damn hard ... on level 12 the boar hit me between 35-60 dmg (not critical) i have 280 life... problem here seems that it is not just the initial hit, sometimes it keeps the damage up and gives you up to 3 hits that high... should be just the first hit after engage if i remember correct. (this is also realy hard if you do the quest with Princess ... you got 3 boars at once and nearly get one-hitted)
- Gnolls in Elwyn forest around hogger got a kind of Windfurry effect ... must be the hell if you are a cloth class because they hit for 9-15 3times at once on my mail armor with a shield.  combat log says "melee hit" by every impact, so no effect and i cannot remember on a hundred private realms and also on vanilla, they had that effect.  ...at least not in that low level area.  Gnolls in Westfall don't have the effect, so it's fine. Riverpaw Scout in Westfall sometimes seem to dodge miss parry everything ... without any spell on them... maybe a little to high calculated?
- Murlocs in Elwyn forest (Woodchopper camp and river below) should use a Healing potion with a cast bar if they get low life... i mean it's easier to kill them if they don't so ... up to you to fix that  XD but they seem to not do that.
- Hogger hits with 120-170 non-critical sometimes on mail armor with shield ... to hard?
- Murlocs next to Goldhain run away... not that special, but they run away in a speed like 5 times ursian bolt until they change direction the first time. then they run normal
- Delay on npc dieing... sometimes i die and npc also

Chests: (1 Bug)
- If you are in a group and the chest items get rolled, afther the chest is empty it stays there for ever until you loot the emty box again.  afther that it disapears instantly. Also chests don't get removed after a few minutes if just one item gets removed like it should be... several private servers have this problem as i know (people loot the green and left the crap behind ... forever)

World: (1 Bug)
- Underground railway goes closely equal... wrong timer

To be continued

**Comment by toto6** [comment]
please, report ONLY ONE bug per issue

**Comment by ttghnw** [comment]
Devotion aura sometimes goes into a 0sec mode - I confirm this

**Comment by ttghnw** [comment]
Blessing of might cannot be cast if the spell Seal of the Crusader is active running. - I can confirm this

**Comment by Easyfraggy** [comment]
Need these reported as seperate issues if they still prevail.

**Comment by Wolffenstein** [comment]
Invalid report. One issue per one report.
