### ISSUE TITLE
[Item]Drinking and eating missing animation

### ISSUE THREAD

**Issue by DeltaLoads** [Atlantiss/NetherwingBugtracker#1390]
[//]: # (Enclose links to things related to the bug using http://wowhead.com or any other TBC database.)
[//]: # (You can use screenshot ingame to visual the issue.)
[//]: # (Write your tickets according to the format:)
[//]: # ([Quest][Azuremyst Isle] Red Snapper - Very Tasty!)
[//]: # ([NPC] Magistrix Erona)
[//]: # ([Spell][Mage] Fireball)
[//]: # ([Npc][Drop] Ghostclaw Lynx)
[//]: # ([Web] Armory doesnt work)

**Description**: 
Sometimes when using food and drink sitting down animation doesnt trigger
https://streamable.com/vxt3a
**Current behaviour**:
Drinking/eating sometimes doesnt trigger sitting animation
**Expected behaviour**: 
Drinking/eating should always trigger sitting animation
**Server Revision**: 
2137

**Comment by Manaci** [comment]
Fixed
