### ISSUE TITLE
[Skill][Hunter]Feign Death

### ISSUE THREAD

**Issue by DeltaLoads** [Atlantiss/NetherwingBugtracker#1391]
[//]: # (Enclose links to things related to the bug using http://wowhead.com or any other TBC database.)
[//]: # (You can use screenshot ingame to visual the issue.)
[//]: # (Write your tickets according to the format:)
[//]: # ([Quest][Azuremyst Isle] Red Snapper - Very Tasty!)
[//]: # ([NPC] Magistrix Erona)
[//]: # ([Spell][Mage] Fireball)
[//]: # ([Npc][Drop] Ghostclaw Lynx)
[//]: # ([Web] Armory doesnt work)

**Description**: 
Taking damage any damage while using Feign Death instantly cancels it.
https://streamable.com/i5pzy
From what i remember and from this comment from battle.net forum
![untitled](https://user-images.githubusercontent.com/43690147/46641121-24dc6780-cb70-11e8-8d7f-9c6daf1e9c48.png)
and limitations from wowwiki -http://wowwiki.wikia.com/wiki/Feign_Death
that shouldn't happen

**Current behaviour**:
Feign Death gets cancelled by taking any damage.
**Expected behaviour**: 
Feign Death should only get cancelled by moving or performing any action
**Server Revision**: 
2137

**Comment by xmesaj2** [comment]
rev 2356
