### ISSUE TITLE
[Quest] Bad medicine - drop rate way too low

### ISSUE THREAD

**Issue by Maelareth** [Atlantiss/NetherwingBugtracker#1392]
[//]: # (Enclose links to things related to the bug using http://wowhead.com or any other TBC database.)
[//]: # (You can use screenshot ingame to visual the issue.)
[//]: # (Write your tickets according to the format:)
[//]: # ([Quest][Azuremyst Isle] Red Snapper - Very Tasty!)
[//]: # ([NPC] Magistrix Erona)
[//]: # ([Spell][Mage] Fireball)
[//]: # ([Npc][Drop] Ghostclaw Lynx)
[//]: # ([Web] Armory doesnt work)

**Description**: The current drop rate of Jungle Remedies from Kurzen Medicine Men is too low (none-existant?).

**Current behaviour**: Killing Kurzen Medicine men for the quest Bad Medicine does not seem to yield any Jungle Remedies, regardless of killing around 20 of them. I tried getting them along side doing the quest The Second Rebellion, but didn't get a single remedy regardless of the amout of medicine men i killed.

**Expected behaviour**: Not sure of exact percentage, but it should be higher for sure.

**Server Revision**: 2137

**Comment by Shanghi** [comment]
The drop rate is kind of high already and I got 3 by killing just 5 medicine men, so something else must be happening to cause the problem. I have no idea what though!

**Comment by Maelareth** [comment]
Did another 5-6 kills and got 1 remedy. Dunno if I’m just unlucky or what. Almost 30 kills and 1 remedy, haha

**Comment by Firroth** [comment]
No idea, since didn't test it when lvling, but according to comments "every mob" in the camp should drop it.

![screenshot_1](https://user-images.githubusercontent.com/43505196/46661391-69d8bc00-cbb9-11e8-8c18-fd03bb1ca9b3.png)

![screenshot_2](https://user-images.githubusercontent.com/43505196/46661393-69d8bc00-cbb9-11e8-9d19-1cff43946499.png)

**Comment by aresbrutus** [comment]
The drop rate was fine enough but I did fix something with Jungle Fighters drop rate in rev `Tycho`.
