### ISSUE TITLE
[Quest][Item]Ghost-o-plasm#15849 should have 100% drop chance.

### ISSUE THREAD

**Issue by Tenoutoften** [Atlantiss/NetherwingBugtracker#1393]
**Description**: 
[[Item]Ghost-o-plasm#15849](https://db.excalibur.ws/?item=15849) for [[Quest]Ghost-o-plasm Round Up#6134](https://db.excalibur.ws/?quest=6134) dropped by [[NPC]Magrami Spectre#11560](https://db.excalibur.ws/?npc=11560) should have 100% drop chance indicated by [wowhead comments](https://www.wowhead.com/quest=6134/ghost-o-plasm-round-up#comments)
![3363e92c73b2e1dfbcc9a3706c39aa34](https://user-images.githubusercontent.com/34839199/46654824-17dc6a00-cbaa-11e8-851e-c3a964ffb2d3.png)
![c0a67f043d37734a6216c05aa92226f5](https://user-images.githubusercontent.com/34839199/46654825-17dc6a00-cbaa-11e8-8360-e1adb624a57d.png)
![c8412b37a2f4865e848cbf59f89e64c8](https://user-images.githubusercontent.com/34839199/46654826-18750080-cbaa-11e8-9d3f-1d19f3317ce4.png)
![d4f77ac00a9de927d4154b2e55bcbf9e](https://user-images.githubusercontent.com/34839199/46654827-18750080-cbaa-11e8-978a-198f09d5fa1c.png)

**Current behaviour**:
I had at least one centaur not dropping one.

**Expected behaviour**: 
100% drop chance

**Server Revision**: 
2137

**Comment by aresbrutus** [comment]
Fixed in rev `Tycho`.
