### ISSUE TITLE
[NPC]Magrami Spectre#11560 should walk towards [Object]Ghost Magnet#177746 in [Quest]Ghost-o-plasm Round Up#6134

### ISSUE THREAD

**Issue by Tenoutoften** [Atlantiss/NetherwingBugtracker#1394]
**Description**: 
[[NPC]Magrami Spectre#11560](https://db.excalibur.ws/?npc=11560) spawned by [[Object]Ghost Magnet#177746](https://db.excalibur.ws/?object=177746) which is spawned by [[Spell]Place Ghost Magnet#19588](https://db.excalibur.ws/?spell=19588) by using [[Item]Crate of Ghost Magnets#15848](https://db.excalibur.ws/?item=15848) in the [[Quest]Ghost-o-plasm Round Up#6134](https://db.excalibur.ws/?quest=6134) should walk towards the [[Object]Ghost Magnet#177746](https://db.excalibur.ws/?object=177746) and once it has been reached, patrol around it.

Indicated by [wowhead comment](https://www.wowhead.com/npc=11560/magrami-spectre#comments:id=555237)
![qweqwe](https://user-images.githubusercontent.com/34839199/46655266-64747500-cbab-11e8-96f5-4e61f09b9fee.png)

Didn't get to test this, but apparently once they reach the [[Object]Ghost Magnet#177746](https://db.excalibur.ws/?object=177746) and are suppose to patrol around it the ones with blue aura will turn green, which should mean it will chain pull the rest.
![e529599edbaee7e6c5e4cb362c5c6239](https://user-images.githubusercontent.com/34839199/46655424-e2d11700-cbab-11e8-852a-f695d115e26d.png)
A [video](https://youtu.be/txW9ipKZ7pc?t=92) from a much later patch showing them walk towards the [[Object]Ghost Magnet#177746](https://db.excalibur.ws/?object=177746) 

Some people would stand ranged and just pull blue ones:
![dd99a3783cbc42d49a279016fdb6a17a](https://user-images.githubusercontent.com/34839199/46655595-5d019b80-cbac-11e8-8634-c84881423c47.png)
![0b2a4e01de54a27debd217f545970628](https://user-images.githubusercontent.com/34839199/46655928-2710e700-cbad-11e8-9f8d-ef7e3d2c3a46.png)

I shot a small [video](https://www.youtube.com/watch?v=wCvf8uF8aeE&feature=youtu.be) of the quest, but it was only meant to display that some of them are patrolling under the ground. But you can also see a few issues: They are walking away from the [[Object]Ghost Magnet#177746](https://db.excalibur.ws/?object=177746). They would spawn about 15-20 yards away, and just walk further away.

----------------------------------

Allegedly they aren't suppose to give full xp indicated by this comment:
![0632311e053dfe1661877596976ddaf5](https://user-images.githubusercontent.com/34839199/46655801-db5e3d80-cbac-11e8-9810-9efcd02df93f.png)
in my [video](https://www.youtube.com/watch?v=wCvf8uF8aeE&feature=youtu.be) you can see that I am gaining full experience ~200.

**Current behaviour**:
Walks away from [[Object]Ghost Magnet#177746](https://db.excalibur.ws/?object=177746) and despawns eventually

**Expected behaviour**: 
Should walk towards [[Object]Ghost Magnet#177746](https://db.excalibur.ws/?object=177746), once reached blue auraed-[[NPC]Magrami Spectre#11560](https://db.excalibur.ws/?npc=11560) should change to green, and patrol around it.

**Server Revision**: 
2137

**Comment by Evolvee** [comment]
known issue
its core issue @Wolffenstein because the spawned gameobjects doesnt know its XYZ position and it sends 0/0/0 to these creatures so they are going inside hills instead near the gameobject
