### ISSUE TITLE
[Quest] Ledger from Tanaris

### ISSUE THREAD

**Issue by Kidcudi123** [Atlantiss/NetherwingBugtracker#1395]
Description: Does only yield 4350xp but should be 5050xp according to this comment 
![image](https://user-images.githubusercontent.com/33790123/46656396-3d6b7280-cbae-11e8-8418-3c8893b255de.png)

Expected Behaviour: Should yield 5050xp

**Comment by Azalen** [comment]
Since this comment is from 2.0.1 the quest should reward even more EXP in 2.3 - just sayin.

**Comment by Azalen** [comment]
Patch 2.3.0 hit on November 13, 2007. What I don't know is if there was another EXP increase with Wotlk though but 5050xp is pre 2.3.

![lft1](https://user-images.githubusercontent.com/20336567/46658215-786fa500-cbb2-11e8-9fe3-d888c6f29191.png)
![lft2](https://user-images.githubusercontent.com/20336567/46658859-f2545e00-cbb3-11e8-8620-11ca22732864.png)
![lft3](https://user-images.githubusercontent.com/20336567/46658864-f54f4e80-cbb3-11e8-9146-29db57fc0574.png)


Sources:
https://classicdb.ch/?quest=4450
http://web.archive.org/web/20080701075943/http://wow.allakhazam.com:80/db/quest.html?wquest=4450

**Comment by wtRCH** [comment]
- Make spiders drop from 1 to 5 spiders legs not just one.
- Make quest give 5050 EXP upon complete.

@pelekon

**Comment by Tereneckla** [comment]
Fixed
