### ISSUE TITLE
[Dustwallow Marsh] Bloodfen Screecher wrong spawn point

### ISSUE THREAD

**Issue by Azalen** [Atlantiss/NetherwingBugtracker#1396]
**Description**: 
http://wowwiki.wikia.com/wiki/Bloodfen_Screecher
https://classicdb.ch/?npc=4352

**Current behaviour**:
Entry 4352 ID 17 GUIDLow 29831 is a single raptor at the coast

![wowscrnshot_100918_122529](https://user-images.githubusercontent.com/20336567/46663784-487ace80-cbbf-11e8-8704-ee43592df0f3.jpg)

**Expected behaviour**: 
Makes no sense this mob spawns here. No DB indicates a spawn there. 

**Server Revision**: 
[2137]

**Comment by aresbrutus** [comment]
Fixed in rev `Tycho`.
