### ISSUE TITLE
[Dustwallow Marsh] Dart

### ISSUE THREAD

**Issue by Azalen** [Atlantiss/NetherwingBugtracker#1397]
**Description**: 
https://web.archive.org/web/20071027042813/http://wow.allakhazam.com:80/db/mob.html?wmob=14232
http://db.hellfire-tbc.com/?npc=14232

**Current behaviour**:
Doesnt drop green even though he is a rare mob. I did three kills before writing this report, just in case. I read before there was a discussion about rare mobs dropping green. Allakhazam is pretty clear it isnt 100% but I still think Netherwing got something wrong big time regarding rare mobs. On my way to level 39 I sure killed 20 rares but I maybe got 2-3 greens from them.

**Expected behaviour**: 
Should drop green or better with at least 75%

**Server Revision**: 
[2137]

**Comment by Shanghi** [comment]
Right now rares only have their unique loot (if they have any) set properly. We're waiting on an addition to the global loot system before fixing the general loot part, so most won't drop anything right now. It's planned though, and once it's done all the rares will be fixed at the same time.

**Comment by Tenoutoften** [comment]
https://github.com/Atlantiss/NetherwingBugtracker/issues/611
