### ISSUE TITLE
[Dustwallow Marsh] The Rot

### ISSUE THREAD

**Issue by Azalen** [Atlantiss/NetherwingBugtracker#1400]
**Description**: 
http://db.hellfire-tbc.com/?npc=14235
https://web.archive.org/web/20071027042827/http://wow.allakhazam.com:80/db/mob.html?wmob=14235

**Current behaviour**:
Doesnt drop a green.

**Expected behaviour**: 
Should drop a green or higher quality item. This time Allakhazam says 94%. See also Issue #1397 

**Server Revision**: 
[2137]

**Comment by Tenoutoften** [comment]
They are aware rare spawns don't drop green, they are working on their loot tables in general.
If anything is wrong with [[NPC]The Rot#14235](https://db.excalibur.ws/?npc=14235) it would be that his damage is quite high and described on wowhead as being the same difficulty as the other Oozes.
