### ISSUE TITLE
[Dustwallow Marsh] Corrosion Prevention

### ISSUE THREAD

**Issue by Azalen** [Atlantiss/NetherwingBugtracker#1401]
**Description**: 
http://db.hellfire-tbc.com/?quest=11174
https://web.archive.org/web/20080623084219/http://wow.allakhazam.com:80/db/quest.html?wquest=11174

**Current behaviour**:
Not all Power Core Fragments (http://db.hellfire-tbc.com/?object=186441) apply the buff nessesary to dissolve the Oozes. In particular the Power Core at the Zeppelin doesn't apply the buff.

![wowscrnshot_100918_144103](https://user-images.githubusercontent.com/20336567/46670353-40785a00-cbd2-11e8-8097-58927e9ad876.jpg)
![wowscrnshot_100918_144144](https://user-images.githubusercontent.com/20336567/46670318-25a5e580-cbd2-11e8-9163-c3b80cf17b7e.jpg)

**Expected behaviour**: 
All gameobjects ID=186441 should apply the buff.

**Server Revision**: 
[2137]

**Comment by Azalen** [comment]
On top of that (I noticed it while writing the report and standing still at the gameobject) after some time close to the Power Core it doesn't apply the buff anymore.

**Comment by Tenoutoften** [comment]
I've already reported this https://github.com/Atlantiss/NetherwingBugtracker/issues/1285
