### ISSUE TITLE
[Druid][Spell] Tree of Life - No speed reduction

### ISSUE THREAD

**Issue by wowthings** [Atlantiss/NetherwingBugtracker#1402]
[//]: # (Enclose links to things related to the bug using http://wowhead.com or any other TBC database.)
[//]: # (You can use screenshot ingame to visual the issue.)
[//]: # (Write your tickets according to the format:)
[//]: # ([Quest][Azuremyst Isle] Red Snapper - Very Tasty!)
[//]: # ([NPC] Magistrix Erona)
[//]: # ([Spell][Mage] Fireball)
[//]: # ([Npc][Drop] Ghostclaw Lynx)
[//]: # ([Web] Armory doesnt work)

**Description**: 
As it says in the [spell description](https://tbc-twinhead.twinstar.cz/?spell=33891) "your movement speed is reduced by 20%"...
**Current behaviour**:
... but currently this shapeshift form doesn't reduce the movement. I can run at normal speed.
**Expected behaviour**: 
20% reduced movement speed
**Server Revision**: 
2137

Thanks Smaily for helping me out.

**Comment by Wolffenstein** [comment]
Fixed in rev 2147.
