### ISSUE TITLE
[Movement][NPC]Ana'Thek the Cruel#1059 and his two [NPC]Skullsplitter Spiritchaster#672 have some errors in their patrol path

### ISSUE THREAD

**Issue by Tenoutoften** [Atlantiss/NetherwingBugtracker#1404]
**Description**: 
[[NPC]Ana'Thek the Cruel#1059](https://db.excalibur.ws/?npc=1059) and his two guards, [[NPC]Skullsplitter Spiritchaster#672](https://db.excalibur.ws/?npc=672) have a few errors at their patrol path as they reach the top of the hill by [[NPC]Mogh the Undying#1060](https://db.excalibur.ws/?npc=1060#controlled-abilities) as can be seen in this [video](https://youtu.be/beH6eSSqlng?t=22)

**Expected behaviour**: 
Expected to walk up and down the hill with his guards
**Server Revision**: 
2137

**Comment by aresbrutus** [comment]
Related to https://github.com/Atlantiss/NetherwingBugtracker/issues/826

**Comment by aresbrutus** [comment]
Related to https://github.com/Atlantiss/NetherwingBugtracker/issues/826
