### ISSUE TITLE
[Dustwallow Marsh] Raze Direhorn Post!

### ISSUE THREAD

**Issue by Azalen** [Atlantiss/NetherwingBugtracker#1405]
**Description**: 
http://db.hellfire-tbc.com/?quest=11205
https://web.archive.org/web/20080622170435/http://wow.allakhazam.com:80/db/quest.html?wquest=11150

**Current behaviour**:
Using Tabetha's Torch (item=33072) quest success get triggered but the huts are not starting to burn.

**Expected behaviour**: 
Huts should get burning animation. Proof: https://www.youtube.com/watch?v=YOYwyIJlAvE

**Server Revision**: 
[2137]

**Comment by wtRCH** [comment]
- Make huts burn after using Tabetha's Torch.

@pelekon

**Comment by Evolvee** [comment]
fixed in next rev
