### ISSUE TITLE
[Druid][Spell] Force of Nature - Breaks stealthed characters in targeted area

### ISSUE THREAD

**Issue by wowthings** [Atlantiss/NetherwingBugtracker#1407]
[//]: # (Enclose links to things related to the bug using http://wowhead.com or any other TBC database.)
[//]: # (You can use screenshot ingame to visual the issue.)
[//]: # (Write your tickets according to the format:)
[//]: # ([Quest][Azuremyst Isle] Red Snapper - Very Tasty!)
[//]: # ([NPC] Magistrix Erona)
[//]: # ([Spell][Mage] Fireball)
[//]: # ([Npc][Drop] Ghostclaw Lynx)
[//]: # ([Web] Armory doesnt work)

**Description**: 
When casting Force of Nature at the targeted area this summons 3 treants...
**Current behaviour**:
... but this shouldn't be able to break stealthed characters, if you are lucky enough in a real pvp situation. 
Also the treants are level 70, I think their level scaled with the player level.
Video: 
https://streamable.com/oupje
**Expected behaviour**: 
This happened on retail for a while but they fixed it in[ patch 2.3.0 ](http://wowwiki.wikia.com/wiki/Force_of_Nature#Patch_changes). 
**Server Revision**: 
2137

**Comment by Wolffenstein** [comment]
Fixed in rev 2149.
