### ISSUE TITLE
[Item][Silithus]Wind Stones

### ISSUE THREAD

**Issue by DeltaLoads** [Atlantiss/NetherwingBugtracker#1408]
[//]: # (Enclose links to things related to the bug using http://wowhead.com or any other TBC database.)
[//]: # (You can use screenshot ingame to visual the issue.)
[//]: # (Write your tickets according to the format:)
[//]: # ([Quest][Azuremyst Isle] Red Snapper - Very Tasty!)
[//]: # ([NPC] Magistrix Erona)
[//]: # ([Spell][Mage] Fireball)
[//]: # ([Npc][Drop] Ghostclaw Lynx)
[//]: # ([Web] Armory doesnt work)

**Description**: 
There is a bug that happens when wearing full set of Twilight Trappings (https://www.wowhead.com/item-set=492/twilight-trappings) you get this problem when interacting with Wind Stones
https://streamable.com/6nj6q
Might be because of quest 
**Current behaviour**:
Wind Stones shouldn't have quests in dialog and shouldn't duplicate talking options every time you open them
**Expected behaviour**: 
Wind Stones should only have 1 option for summoning when interacting with them
**Server Revision**: 
2137

**Comment by Tenoutoften** [comment]
I had this happen too but with the ring quest for paladins. On another occasion there was no quest offered.

**Comment by Manaci** [comment]
Fixed
