### ISSUE TITLE
[Quest][Silvermoon] Claiming the Light

### ISSUE THREAD

**Issue by Notmittz** [Atlantiss/NetherwingBugtracker#141]
[Quest][Silvermoon] Claiming the Light
[NPC] Magister Astalor Bloodsworn

**Description**: 
The Paladin quest is unable to be completed and gives an error after using the quest item [24157] Shimmering Vessel, which states "The item was not found" making the quest unable to be completed.

**Current behaviour**:
Quest states to "Use the Shimmering Vessel on **M'uru** to fill it and return to Knight-Lord Bloodvalor in Silvermoon City".

After accepting quest, it changes to be "Use the Shimmering Vessel on the **Blood Elf Magisters**..."

Regardless of target, the item disappears after use and the error "The item was not found" is displayed

**Expected behaviour**: 
Using the item should produce a "Filled Shimmering Vessel" allowing for the quest to be completed

**Comment by Evolvee** [comment]
known problem, we tried to downgrade this quest to its 2.0.3 state but there is some issue with 2.0.3 dbc spell version of the quest item

**Comment by Evolvee** [comment]
https://github.com/Atlantiss/AtlantissTBCBT/issues/919
https://github.com/Atlantiss/AtlantissTBCBT/issues/4014

**Comment by Evolvee** [comment]
I will revert the spell to its 2.4 state (before Muru was stolen) so you can get the chain done but I will try to re-add the 2.0.3 version again in future.

should be working after next hotfix revision

**Comment by Evolvee** [comment]
@Wolffenstein there is a spell issue - check discord

**Comment by Wolffenstein** [comment]
Fixed in rev 2046.
