### ISSUE TITLE
[NPC][Nagrand] Missing formation and movement.

### ISSUE THREAD

**Issue by Easyfraggy** [Atlantiss/NetherwingBugtracker#1411]
**Description**: 

They seem to have been removed on current retail. So don't have precise path.

They should roam (large path) in large packs.

![image](https://user-images.githubusercontent.com/36134067/46684291-aecd1480-cbf2-11e8-922d-a065fe34dc91.png)

18964 ID 1

![image](https://user-images.githubusercontent.com/36134067/46684079-19318500-cbf2-11e8-9eda-a6ade82f010f.png)

18226 ID 2

![image](https://user-images.githubusercontent.com/36134067/46684102-23ec1a00-cbf2-11e8-89f5-e4632acfb3cc.png)

**Server Revision**: 2142

**Comment by Varadin** [comment]
HOW DARE YOU TEST TBC CONTENT WITHOUT US ?!

**Comment by bloodwindz** [comment]
that x2

**Comment by aresbrutus** [comment]
Fixed in rev `Tycho`.
