### ISSUE TITLE
[Quest] [The Barrens] Lost In Battle

### ISSUE THREAD

**Issue by cbitz** [Atlantiss/NetherwingBugtracker#1412]
![wowscrnshot_100918_102006](https://user-images.githubusercontent.com/17559375/46686441-2b3d0480-cbad-11e8-9371-3d91ee7c1532.jpg)

**Current behaviour**:
While on the quest, there is no discernible indicator that the beaten corpse is clickable and the quest can be completed.
**Expected behaviour**: 
Should be one of those little cog wheels that says you are able to interact with the corpse.

**Comment by Easyfraggy** [comment]
Need retail confirmation of this. Sounds like a Cata thing to me.

**Comment by Peglaa** [comment]
Should either be a cog wheel or the more likely one is the white convo bubble. I doubt you will find any proof for this as these things don't show up on pics or videos I believe. I would still suggest changing it to something, it's not that big of a deal and it helps.

**Comment by Jezofine** [comment]
Screenshot from Joana's shows bubble, idk if it was changed in TBC:
![bubble](https://user-images.githubusercontent.com/2833746/49519301-8005ae80-f8c2-11e8-8561-fb8f349e929c.jpg)

**Comment by duzyizly** [comment]
movie from classic: https://www.youtube.com/watch?v=yUXsJxsbIN0
looks like works fine.
