### ISSUE TITLE
[NPC] Hatefury Rogue

### ISSUE THREAD

**Issue by Retinus** [Atlantiss/NetherwingBugtracker#1413]
**Description**: For the quest [Befouled by Satyr](http://db.hellfire-tbc.com/?quest=1434) need to kill some mobs. Hatefury Rogue is one of them.

**Current behaviour**: [Hatefury Rogue](http://db.hellfire-tbc.com/?npc=4670#abilities) is not using stealth [Hide](http://db.hellfire-tbc.com/?spell=6920)

**Expected behaviour**: Use stealth

**Server Revision**: 2137

**Comment by The14me** [comment]
https://i.imgur.com/RQcuYK1.png

**Comment by Firroth** [comment]
Isn't it already fixed though in rev. 2138, since all mobs which use stealth don't use it currently? 
#1338, #1310

**Comment by Wolffenstein** [comment]
Fixed in rev 2154.
