### ISSUE TITLE
[NPC][Blasted Lands] Servant of Razelikh - missing spawn

### ISSUE THREAD

**Issue by Firroth** [Atlantiss/NetherwingBugtracker#1414]
[NPC] [Servant of Razelikh](https://www.wowhead.com/npc=7668/servant-of-razelikh)

**Current behaviour**:
There is only stone, but no [Servant of Razelikh](https://www.wowhead.com/npc=7668/servant-of-razelikh) in it's vicinity.

![screenshot_2](https://user-images.githubusercontent.com/43505196/46688087-c1e4e200-cbfc-11e8-88d6-2ab33a60f685.png)

**Expected behaviour**: 
Near each stone for quest "[The Stones That Binds Us](https://www.wowhead.com/quest=2681/the-stones-that-bind-us)" should be at least 1 servant in it's vicinity (in this case it should be [Servant of Razelikh](https://www.wowhead.com/npc=7668/servant-of-razelikh)).
GPS cords above.

**Server Revision**: 
2137

**Comment by aresbrutus** [comment]
Fixed in rev `Tycho`.
