### ISSUE TITLE
[Spell][Hunter]Pet attack

### ISSUE THREAD

**Issue by DeltaLoads** [Atlantiss/NetherwingBugtracker#1415]
[//]: # (Enclose links to things related to the bug using http://wowhead.com or any other TBC database.)
[//]: # (You can use screenshot ingame to visual the issue.)
[//]: # (Write your tickets according to the format:)
[//]: # ([Quest][Azuremyst Isle] Red Snapper - Very Tasty!)
[//]: # ([NPC] Magistrix Erona)
[//]: # ([Spell][Mage] Fireball)
[//]: # ([Npc][Drop] Ghostclaw Lynx)
[//]: # ([Web] Armory doesnt work)

**Description**: 
Pets dont attack any npc that is stealthed, possibly players aswell if given command to attack them
https://streamable.com/o71l5
**Current behaviour**:
Pets dont attack stealthed npcs if given attack command
**Expected behaviour**: 
Pets should attack stealthed npcs if player gives command to attack
**Server Revision**: 
2137

**Comment by Easyfraggy** [comment]
Probably same problem as mobs that are trapped.

**Comment by bloodwindz** [comment]
yes in tbc you can dps the hunter to death that dont wanna move and stay with feint death thinking he can escape lol

**Comment by DeltaLoads** [comment]
bloodwindz comment is related to https://github.com/Atlantiss/NetherwingBugtracker/issues/1391

**Comment by TerawattHF** [comment]
Could this also be the same issue pets are having with attacking targets in freezing trap when set to passive? #456

**Comment by xycz** [comment]
If it's the same problem as with mobs that are trapped, I'm willing to bet this is also the reason passive pets refuse to attack polymorphed targets. I believe attack command should overwrite passive/defensive mode until target is dead or commanded otherwise. Aggressive mode worked for me while trying to attack polymorph targets though, maybe that could give you a hint of where to look.

**Comment by KevinTyrrell** [comment]
[Twitch Clip](https://clips.twitch.tv/AlertEsteemedWrenAMPEnergyCherry)

More video evidence of this happening. My guess is it is related to the Freezing Trap pet attack bug as well.

**Comment by Brasso** [comment]
https://www.youtube.com/watch?v=dqQ2Rt54RCI Bugged in pvp. Passive and Defensive modes are bugged, Aggressive works.

**Comment by ammenvale** [comment]
By spamming Attack pet can make their way up to the mob in a buggy way
https://streamable.com/8rq8u

**Comment by Manaci** [comment]
Fixed
