### ISSUE TITLE
BRD, Lyceum and Room after

### ISSUE THREAD

**Issue by Erodraeda** [Atlantiss/NetherwingBugtracker#1417]
[//]: # (Enclose links to things related to the bug using http://wowhead.com or any other TBC database.)
[//]: # (You can use screenshot ingame to visual the issue.)
[//]: # (Write your tickets according to the format:)
[//]: # ([Quest][Azuremyst Isle] Red Snapper - Very Tasty!)
[//]: # ([NPC] Magistrix Erona)
[//]: # ([Spell][Mage] Fireball)
[//]: # ([Npc][Drop] Ghostclaw Lynx)
[//]: # ([Web] Armory doesnt work)

**Description**: 
The mobs in Lyceum weren't respawning, even before using the torches. After using the torches, both of them, the door didn't open. And the fire in Magmus' room was hitting in places it shoulnd't hit. The Hitbox felt really bigger.
**Current behaviour**:
Door in Lyceum didn't open, mobs didn't respawn and the fire has a hitbox larger than it should.
**Expected behaviour**: 
Door in Lyceum should open after lighting up both braziers, mobs should respawn each ~30 seconds before that, and the fire on Magmus' room shouldn't have a hitbox so large.
**Server Revision**:

**Comment by devo6969** [comment]
The mobs arn't respawning on the PTR still. Doors though are closed till you use both torches. For Magmus's room though I don't know the exact hit radius but even on classic they seemed large and the only safe spot was in the corner near the throne's door.

**Comment by Godmatik** [comment]
Closing - all BRD information will be consolidated into one thread
