### ISSUE TITLE
Princess Moira -BRD

### ISSUE THREAD

**Issue by Mewmewww** [Atlantiss/NetherwingBugtracker#1418]
[//]: # (Enclose links to things related to the bug using http://wowhead.com or any other TBC database.)
[//]: # (You can use screenshot ingame to visual the issue.)
[//]: # (Write your tickets according to the format:)
[//]: # ([Quest][Azuremyst Isle] Red Snapper - Very Tasty!)
[//]: # ([NPC] Magistrix Erona)
[//]: # ([Spell][Mage] Fireball)
[//]: # ([Npc][Drop] Ghostclaw Lynx)
[//]: # ([Web] Armory doesnt work)

**Description**: Doesn't run up to the throne after her husband is dead.

**Current behaviour**: Doesn't run up to the throne after her husband is dead.

**Expected behaviour**: Should run up to the throne https://www.youtube.com/watch?v=REl62kJuuZQ

**Server Revision**: 2137

**Comment by devo6969** [comment]
Still isnt running up to the throne on the PTR.

PTR - https://www.youtube.com/watch?v=4Lc39qecIDE
Classic Vanilla - https://youtu.be/DXEt2eCD7IQ?t=248

**Comment by Godmatik** [comment]
Closing - all BRD information will be consolidated into one thread
