### ISSUE TITLE
BRD, Emperor Dagran Thaurissan's room

### ISSUE THREAD

**Issue by Erodraeda** [Atlantiss/NetherwingBugtracker#1419]
[//]: # (Enclose links to things related to the bug using http://wowhead.com or any other TBC database.)
[//]: # (You can use screenshot ingame to visual the issue.)
[//]: # (Write your tickets according to the format:)
[//]: # ([Quest][Azuremyst Isle] Red Snapper - Very Tasty!)
[//]: # ([NPC] Magistrix Erona)
[//]: # ([Spell][Mage] Fireball)
[//]: # ([Npc][Drop] Ghostclaw Lynx)
[//]: # ([Web] Armory doesnt work)

**Description**: 
When the boss was pulled, the left pack in the room didn't pull. Princess was pulled alone, not linked to the boss, and when we saved her, she didn't walk up to the throne like supposed to.
**Current behaviour**:
Engaging emperor didn't pull left mobs in the room, Princess wasn't linked to Emperor and didn't walk up to the throne after being saved.
**Expected behaviour**: 
After you engage the emperor, left mobs in the room should pull too, princess should be linked to the emperor and should walk up after saved.
**Server Revision**:

**Comment by ScottieDOESknow** [comment]
(Update) princess is linked to emperor, but still no throne RP

Server Revision: 2214

**Comment by devo6969** [comment]
When I pulled the Emperor the whole room was linked but I didn't see any RP event when the doors opened.

**Comment by Godmatik** [comment]
Closing - all BRD information will be consolidated into one thread
