### ISSUE TITLE
[spell][paladin]Looting objects while invulnerable

### ISSUE THREAD

**Issue by knasen88** [Atlantiss/NetherwingBugtracker#142]
[//]: # (Enclose links to things related to the bug using http://wowhead.com or any other TBC database.)
[//]: # (You can use screenshot ingame to visual the issue.)
[//]: # (Write your tickets according to the format:)
[//]: # ([Quest][Azuremyst Isle] Red Snapper - Very Tasty!)
[//]: # ([NPC] Magistrix Erona)
[//]: # ([Spell][Mage] Fireball)
[//]: # ([Npc][Drop] Ghostclaw Lynx)
[//]: # ([Web] Armory doesnt work)

**Description**: 
Players are able to loot containers while being invulnerable, while they shouldn't be able to.
**Current behaviour**:
They're completely immune as of now, can still loot items
**Expected behaviour**: 
Patch 0.6
Players can no longer loot or use items while invulnerable.
http://wowwiki.wikia.com/wiki/Patch_0.6?oldid=26360
and it was NEVER patched back into the game, because it is un-counterable by 90% of the game.
use items such as interacting with stuff in the world, not bandage or w/e.
**Server Revision**:

**Comment by xmesaj2** [comment]
fixed in rev 2035
