### ISSUE TITLE
BRD, Blazing Fireguards

### ISSUE THREAD

**Issue by Erodraeda** [Atlantiss/NetherwingBugtracker#1420]
[//]: # (Enclose links to things related to the bug using http://wowhead.com or any other TBC database.)
[//]: # (You can use screenshot ingame to visual the issue.)
[//]: # (Write your tickets according to the format:)
[//]: # ([Quest][Azuremyst Isle] Red Snapper - Very Tasty!)
[//]: # ([NPC] Magistrix Erona)
[//]: # ([Spell][Mage] Fireball)
[//]: # ([Npc][Drop] Ghostclaw Lynx)
[//]: # ([Web] Armory doesnt work)

**Description**: 
At several places, there were packs of 2 Blazing Fireguards that should pull together, but weren't linked. For Example, the packs right before Lord Incendius.
**Current behaviour**:
Packs of 2 aren't linked
**Expected behaviour**: 
Those packs should be linked.
**Server Revision**:

**Comment by aresbrutus** [comment]
Fixed in rev `Tycho`.
