### ISSUE TITLE
BRD - Grim guzzler

### ISSUE THREAD

**Issue by Mewmewww** [Atlantiss/NetherwingBugtracker#1422]
[//]: # (Enclose links to things related to the bug using http://wowhead.com or any other TBC database.)
[//]: # (You can use screenshot ingame to visual the issue.)
[//]: # (Write your tickets according to the format:)
[//]: # ([Quest][Azuremyst Isle] Red Snapper - Very Tasty!)
[//]: # ([NPC] Magistrix Erona)
[//]: # ([Spell][Mage] Fireball)
[//]: # ([Npc][Drop] Ghostclaw Lynx)
[//]: # ([Web] Armory doesnt work)

**Description**: Odd knockdown, possibly related to the cork blowing up.

**Current behaviour**: Random knockdown. https://clips.twitch.tv/StrangeSassyAyeayeLitFam

**Expected behaviour**: Shouldn't be random knockdowns.

**Server Revision**: 2137

**Comment by Wolffenstein** [comment]
Fixed? Can't trigger it.
