### ISSUE TITLE
[Spell][Mage] Portal

### ISSUE THREAD

**Issue by Sinyr** [Atlantiss/NetherwingBugtracker#1424]
[//]: # (Enclose links to things related to the bug using http://wowhead.com or any other TBC database.)
[//]: # (You can use screenshot ingame to visual the issue.)
[//]: # (Write your tickets according to the format:)
[//]: # ([Quest][Azuremyst Isle] Red Snapper - Very Tasty!)
[//]: # ([NPC] Magistrix Erona)
[//]: # ([Spell][Mage] Fireball)
[//]: # ([Npc][Drop] Ghostclaw Lynx)
[//]: # ([Web] Armory doesnt work)

**Description**:
Tested this multiple times, mostly with Portal: Theramore.

**Current behaviour**:
When a party member uses your portal, it becomes locked for you, preventing you from using it.

**Expected behaviour**: 
You should be able to use your own portal after other party members have used it.

**Server Revision**: 
2137

**Comment by Easyfraggy** [comment]
Known issue with all portals.

**Comment by Wolffenstein** [comment]
Fixed in rev 2151.
