### ISSUE TITLE
[Quest][Azhara] Arcane Runes)

### ISSUE THREAD

**Issue by Thorgrimme** [Atlantiss/NetherwingBugtracker#1425]
[//]: # http://db.hellfire-tbc.com/?quest=3449
[//]: # ([NPC] Pilot Xiggs Fuselighter

**Description**: Did all the quest just fine upto when i was about to turn it in on the helipad, tried using my flare twice without the npc showing up in his flying machine. Did it earlier on a different char just fine.

**Current behaviour**:

**Expected behaviour**: 

**Server Revision**:

**Comment by Taesti** [comment]
I've just had the same issue. NPC refused to spawn after 2 tries with the flare gun.

After server crash GM Kutsal ported me there to try again and it worked that time. Seems to have problems being called multiple times.

**Comment by powerlol** [comment]
I did use one flare without it appearing, had to use a second, there is defo something wrong with that quest

**Comment by RobGFour** [comment]
Broken for me and another person standing here...2 flares

**Comment by The14me** [comment]
The first time it worked just fine. Once the plane despawns can't call it anymore.
Rev 3441.Still a issue.

**Comment by Godmatik** [comment]
Rev 4016 - no longer an issue

Used flare gun - the plane spawned

Waited for it to despawn, used flare a 2nd time, and the plane appeared again with no issues
