### ISSUE TITLE
[Quest][Dustwallow Marsh] Stinky's Escape

### ISSUE THREAD

**Issue by Sinyr** [Atlantiss/NetherwingBugtracker#1426]
[//]: # (Enclose links to things related to the bug using http://wowhead.com or any other TBC database.)
[//]: # (You can use screenshot ingame to visual the issue.)
[//]: # (Write your tickets according to the format:)
[//]: # ([Quest][Azuremyst Isle] Red Snapper - Very Tasty!)
[//]: # ([NPC] Magistrix Erona)
[//]: # ([Spell][Mage] Fireball)
[//]: # ([Npc][Drop] Ghostclaw Lynx)
[//]: # ([Web] Armory doesnt work)

**Description**: 
Did the alliance version: https://db.excalibur.ws/?quest=1222

**Current behaviour**:
In a party, only the person who started the quest gets quest credit at the end of the escort.

**Expected behaviour**: 
All party members should get quest credit at the end of the escort.

**Server Revision**: 
2137

**Comment by aresbrutus** [comment]
https://github.com/Atlantiss/NetherwingBugtracker/issues/3678
