### ISSUE TITLE
[Object][Dustwallow Marsh] Bogbean Plant

### ISSUE THREAD

**Issue by Sinyr** [Atlantiss/NetherwingBugtracker#1427]
[//]: # (Enclose links to things related to the bug using http://wowhead.com or any other TBC database.)
[//]: # (You can use screenshot ingame to visual the issue.)
[//]: # (Write your tickets according to the format:)
[//]: # ([Quest][Azuremyst Isle] Red Snapper - Very Tasty!)
[//]: # ([NPC] Magistrix Erona)
[//]: # ([Spell][Mage] Fireball)
[//]: # ([Npc][Drop] Ghostclaw Lynx)
[//]: # ([Web] Armory doesnt work)

**Description**: 
Bogbean Plant (20939): https://db.excalibur.ws/?object=20939
"Stinky" Ignatz (4880): https://db.excalibur.ws/?npc=4880
Stinky's Escape (1222): https://db.excalibur.ws/?quest=1222

**Current behaviour**:
Bogbean Plant has longer respawn than "Stinky" Ignatz, which means that when doing the quest Stinky's Escape shortly after someeone else finished it the plant might not be there, and he picks at an empty ground.

(Happened to us because we had to do the quest twice to get the credit. I opened another bug for that.)

**Expected behaviour**: 
Bogbean Plant should probably have the same respawn time as "Stinky" Ignatz, so that it's there each time someone does an escort, or even lower if him dying during the escort means that he respawns faster.

**Server Revision**: 
2137

**Comment by Wolffenstein** [comment]
Fixed in rev 2406.
