### ISSUE TITLE
[NPC][Eastern Plaguelands]Scourge Champion

### ISSUE THREAD

**Issue by DeltaLoads** [Atlantiss/NetherwingBugtracker#1428]
[//]: # (Enclose links to things related to the bug using http://wowhead.com or any other TBC database.)
[//]: # (You can use screenshot ingame to visual the issue.)
[//]: # (Write your tickets according to the format:)
[//]: # ([Quest][Azuremyst Isle] Red Snapper - Very Tasty!)
[//]: # ([NPC] Magistrix Erona)
[//]: # ([Spell][Mage] Fireball)
[//]: # ([Npc][Drop] Ghostclaw Lynx)
[//]: # ([Web] Armory doesnt work)

**Description**: 
Scourge Champion shared spawn doesnt work correctly, there are only 2 in the whole zone and they always respawn in the same place. They should have shared spawn with all the undead npcs in the area - The Fungal Vale and Browman Mill
https://www.wowhead.com/npc=8529/scourge-champion#comments
**Current behaviour**:
Scourge Champion dont have shared spawn with other undead npcs in the area
**Expected behaviour**: 
Scourge Champion should have shared spawn with other undead npcs in the area
**Server Revision**: 
2137

**Comment by The14me** [comment]
Rev . 3441 still an issue. They are very rare.

**Comment by Godmatik** [comment]
Not true at all - it has 14 different spawn points, and checking all of them I found 6 up at one time.

I went to one of the spawn and killed/respawn the ghoul and occasionally it respawned as a Scourge Champion instead.
