### ISSUE TITLE
[Badlands] Tremors of the Earth

### ISSUE THREAD

**Issue by Azalen** [Atlantiss/NetherwingBugtracker#1429]
**Description**: 
https://classicdb.ch/?quest=732

**Current behaviour**:
After Boss Tho'grun (https://classicdb.ch/?npc=2944) dies his patrol stops moving completely until Boss Tho'grun respawns. Then they run to Boss Tho'grun's Position and position themself to walk with him. This can look very weird if the patrol is far away from Boss Tho'grun spawn location.
Also - Boss Tho'grun is not linked to his patrol mates.

**Server Revision**: 
[2137]

**Comment by Evolvee** [comment]
1) he is not supposed to be linked to all of them - blizzlike

2) just scuffed formations @Wolffenstein :))

**Comment by Evolvee** [comment]
I made new waypoints, if that doesnt help it, its just scuffed core.
