### ISSUE TITLE
[Quest][Mulgore] Kodo Hide Bag

### ISSUE THREAD

**Issue by Xynaps** [Atlantiss/NetherwingBugtracker#143]
**Description**: The leatherworking only questy [Kodo Hide Bag](https://vanilla-twinhead.twinstar.cz/?quest=769)  is not completable when you have the required materials. 

**Current behaviour**: The "Continue" button is grey as if you don't have the required materials. This is not solved with a relog. 

**Expected behaviour**: Should be able to complete the quest. 

**Server Revision**: 2028

**Comment by Xynaps** [comment]
After abandoning the quest and retaking it it was completable.

**Comment by aresbrutus** [comment]
Closing this. Reply here if you still think this should be open for other reasons.
