### ISSUE TITLE
[Zone]Winterspring/High Chief Winterfall's cave

### ISSUE THREAD

**Issue by mbzz88** [Atlantiss/NetherwingBugtracker#1430]
**Description**: Cave is zoned as "Alterac Valley"

**Current behaviour**: 
![wowscrnshot_101018_154739](https://user-images.githubusercontent.com/43509267/46710356-f1025e80-cca3-11e8-99ea-6ded33781e45.jpg)

**Expected behaviour**: Should be part of Winterspring

**Server Revision**: 2151

**Comment by Manaci** [comment]
Fixed in [3198]
