### ISSUE TITLE
[NPC] Jaedenar Darkweaver patrol

### ISSUE THREAD

**Issue by totaemoeggerli** [Atlantiss/NetherwingBugtracker#1432]
[//]: # (Enclose links to things related to the bug using http://wowhead.com or any other TBC database.)
[//]: # (You can use screenshot ingame to visual the issue.)
[//]: # (Write your tickets according to the format:)
[//]: # ([Quest][Azuremyst Isle] Red Snapper - Very Tasty!)
[//]: # ([NPC] Magistrix Erona)
[//]: # ([Spell][Mage] Fireball)
[//]: # ([Npc][Drop] Ghostclaw Lynx)
[//]: # ([Web] Armory doesnt work)

**Description**: 
Only one [Jaedenar Darkweaver](https://www.wowhead.com/npc=7118/jaedenar-darkweaver) should be patroling around the circle with the candles.

**Current behaviour**:
![clip](https://thumbs.gfycat.com/ImpassionedWholeKouprey-size_restricted.gif)

**Expected behaviour**: 
One should patrol while the other one stands to the right, opposite of the Jaedenar Warlock.

**Server Revision**: 2151

**Comment by aresbrutus** [comment]
Source?

**Comment by aresbrutus** [comment]
Unless you mean the patrolling so close together, I will check that out yes.

**Comment by aresbrutus** [comment]
They are pathing correctly for me. Must have been combat reset where mob moves to a point right when the other is nearby.
