### ISSUE TITLE
[Quest]Threat from the Sea#1426 [NPC]Marsh Inkspewer#750 takes all spawn slots

### ISSUE THREAD

**Issue by Tenoutoften** [Atlantiss/NetherwingBugtracker#1433]
**Description**: 
These NPCs have previously been reported, but closed with a requested recheck: https://github.com/Atlantiss/NetherwingBugtracker/issues/824 

I figured I'd make a new report since the other one was closed:

------------------------------------

In [[Quest]Threat from the Sea#1426](https://db.excalibur.ws/?quest=1426) you are asked to kill 10 of each type of the following NPCs:

* [[NPC]Marsh Murloc#747](https://db.excalibur.ws/?npc=747)
* [[NPC]Marsh Flesheater#751](https://db.excalibur.ws/?npc=751)
* [[NPC]Marsh Inkspewer#750](https://db.excalibur.ws/?npc=750)

Previously it was reported that
>[[NPC]Marsh Murloc#747](https://db.excalibur.ws/?npc=747) seem to be replaced with [[NPC]Marsh Flesheater#751](https://db.excalibur.ws/?npc=751) on the coast of Swamp of Sorrows.

Currently [[NPC]Marsh Inkspewer#750](https://db.excalibur.ws/?npc=750) is all over the place, it takes all spawns, in the cave, on the beach, and behind the mountains. Killing [[NPC]Marsh Inkspewer#750](https://db.excalibur.ws/?npc=750) wont make [[NPC]Marsh Murloc#747](https://db.excalibur.ws/?npc=747) or [[NPC]Marsh Flesheater#751](https://db.excalibur.ws/?npc=751) respawn either.

**Expected behaviour**: 
* General:
![119c8a8af9e4c5c8f4f41c3b7cc45ee2](https://user-images.githubusercontent.com/34839199/46722029-d4026700-cc74-11e8-8da5-1d77f4dcf3c3.png)

* [[NPC]Marsh Flesheater#751](https://db.excalibur.ws/?npc=751) should be found on the beach and in the cave according to various [wowhead comments](https://www.wowhead.com/npc=751/marsh-flesheater#comments)
![45bd0496c6a0311c1eee52dd9e6bcbe3](https://user-images.githubusercontent.com/34839199/46721879-73732a00-cc74-11e8-9167-25635ba3ba6d.png)

* [[NPC]Marsh Murloc#747](https://db.excalibur.ws/?npc=747)
![96dd3ab8f148e372d03b3d078f8b3860](https://user-images.githubusercontent.com/34839199/46721965-aae1d680-cc74-11e8-840c-63f8add6a550.png)

* [[NPC]Marsh Inkspewer#750](https://db.excalibur.ws/?npc=750)
![5f9459bbe9a7d634967c982d468afa17 1](https://user-images.githubusercontent.com/34839199/46722203-43785680-cc75-11e8-8690-a962a1f4b07e.png)

**Server Revision**: 
2151

**Comment by DemonHunter1992** [comment]
i can confirm

**Comment by eryczek1615** [comment]
I also confirm

**Comment by Asparagoose** [comment]
Confirming aswell, checked entire beach and cave. Inkspewer city!

**Comment by towneh** [comment]
Still an issue, had to abadon quest 2625.

**Comment by Sylphren** [comment]
Can still confirm. Went all over the place, only Inkspewers.

**Comment by Cinx787** [comment]
2647 and still an issue. Its crazy that this was brought up during beta and was said to have been fixed so the issue was closed. Why would you close an issue you THINK is fixed?

**Comment by yesthisisnick** [comment]
2678 still only Inkspewers

**Comment by Evolvee** [comment]
fixed in rev 2685
