### ISSUE TITLE
[NPC][Duskwood] Skeletal Warrior & Skeletal Mage

### ISSUE THREAD

**Issue by Anonyxx** [Atlantiss/NetherwingBugtracker#1435]
**Description**: 

Pathing of Skeletal Warrior and Skeletal mage in the Tranquil Gardens Cemetery, Duskwood is incorrect.

**Current behaviour**:

Both mages and warriors walk over graves and over fences. This happens for many mobs that I have observed. Some mobs do not move at all.

**Expected behaviour**: 

Nearly all mobs here have a movement and it does not involve walking over objects such as fences/graves.

**Server Revision**: 
2151

**Comment by The14me** [comment]
Its blizzlike (believe it or not :D ) for some mob's to walk over the fences/object's,but will let report opened.

**Comment by aresbrutus** [comment]
Blizzlike to walk over objects.
