### ISSUE TITLE
[Quest][Dustwallow Marsh] Direhorn Raiders

### ISSUE THREAD

**Issue by Sinyr** [Atlantiss/NetherwingBugtracker#1436]
[//]: # (Enclose links to things related to the bug using http://wowhead.com or any other TBC database.)
[//]: # (You can use screenshot ingame to visual the issue.)
[//]: # (Write your tickets according to the format:)
[//]: # ([Quest][Azuremyst Isle] Red Snapper - Very Tasty!)
[//]: # ([NPC] Magistrix Erona)
[//]: # ([Spell][Mage] Fireball)
[//]: # ([Npc][Drop] Ghostclaw Lynx)
[//]: # ([Web] Armory doesnt work)

**Description**: 
Quest: Direhorn Raiders (11156): https://db.excalibur.ws/?quest=11156
NPC: Grimtotem Earthbinder (23595): https://db.excalibur.ws/?npc=23595

**Current behaviour**:
Killing Grimtotem Earthbinder gives double quest credit for the quest Direhorn Raiders while in a party.

**Expected behaviour**: 
Killing a single monster should give only 1 quest credit.

**Server Revision**: 
2151

**Comment by Evolvee** [comment]
rev 439kcolb
