### ISSUE TITLE
[Core][Batching][Spell][Paladin] Died in Divine Shield

### ISSUE THREAD

**Issue by Sinyr** [Atlantiss/NetherwingBugtracker#1438]
[//]: # (Enclose links to things related to the bug using http://wowhead.com or any other TBC database.)
[//]: # (You can use screenshot ingame to visual the issue.)
[//]: # (Write your tickets according to the format:)
[//]: # ([Quest][Azuremyst Isle] Red Snapper - Very Tasty!)
[//]: # ([NPC] Magistrix Erona)
[//]: # ([Spell][Mage] Fireball)
[//]: # ([Npc][Drop] Ghostclaw Lynx)
[//]: # ([Web] Armory doesnt work)

**Description**: 
Spell: Divine Shield (Rank 1) - https://db.excalibur.ws/?spell=642

**Current behaviour**:
![screenshot_30](https://user-images.githubusercontent.com/9539181/46727391-c05cfd80-cc80-11e8-9ef1-975ef68bd5b5.png)

I used Divine Shield when I was 1 hit away from death. It successfully cast, went on cooldown and granted the Forbearance debuff. However, it seems like the monster hit me in the same batch and I still died.

On another note, I also have no idea how I actually killed the monster since the combat log doesn't say.

**Expected behaviour**: 
Either you shouldn't be able to die if you take a lethal hit in the same batch as casting Divine Shield, or if you do die, Divine Shield shouldn't go on cooldown. (Needs research on which one is actually correct)

**Server Revision**: 
2151

**Comment by Tenoutoften** [comment]
As far as I understood their previous batching system is disabled/limited and it might cause issues like these.

**Comment by Mikik3jr** [comment]
I used lay on hands on myself, I got the heal, it went on CD. How about that?
![wowscrnshot_093018_095603](https://user-images.githubusercontent.com/43505031/46746413-527bfa80-ccaf-11e8-9bbc-f3c04a5229a1.jpg)

**Comment by Mikik3jr** [comment]
2018.09.30 9:56 server time.

**Comment by Sinyr** [comment]
Now that you mention it, it also happened to me before with Lay on Hands, but I cast it on someone else so I thought that maybe it was intended. It "went through" and went on cooldown but the target still died.

**Comment by Wolffenstein** [comment]
Fixed in rev 2156.
