### ISSUE TITLE
Spirit healer bug

### ISSUE THREAD

**Issue by Dekirayne** [Atlantiss/NetherwingBugtracker#144]
[//]: # (Enclose links to things related to the bug using http://wowhead.com or any other TBC database.)
[//]: # (You can use screenshot ingame to visual the issue.)
[//]: # (Write your tickets according to the format:)
[//]: # ([Quest][Azuremyst Isle] Red Snapper - Very Tasty!)
[//]: # ([NPC] Magistrix Erona)
[//]: # ([Spell][Mage] Fireball)
[//]: # ([Npc][Drop] Ghostclaw Lynx)
[//]: # ([Web] Armory doesnt work)

**Description**: 
When I died I got my ghost returned to the starting zone graveyard, but when I walked to Kharanos spirit healer and asked to take corpse he teleported me to the starting zone spirit healer and ressed me there
**Current behaviour**:

**Expected behaviour**: 
Ress me where I asked the spirit healer at its respected graveyard
**Server Revision**:

**Comment by Peglaa** [comment]
This has already been fixed. The server just hasn't been updated. Check the changelog on discord.

**Comment by The14me** [comment]
Fixed in rev [2029]
