### ISSUE TITLE
[Core] Monsters don't reposition underwater

### ISSUE THREAD

**Issue by Sinyr** [Atlantiss/NetherwingBugtracker#1440]
[//]: # (Enclose links to things related to the bug using http://wowhead.com or any other TBC database.)
[//]: # (You can use screenshot ingame to visual the issue.)
[//]: # (Write your tickets according to the format:)
[//]: # ([Quest][Azuremyst Isle] Red Snapper - Very Tasty!)
[//]: # ([NPC] Magistrix Erona)
[//]: # ([Spell][Mage] Fireball)
[//]: # ([Npc][Drop] Ghostclaw Lynx)
[//]: # ([Web] Armory doesnt work)

**Description**: 
Tested with Mudrock Spikeshell (4397): https://db.excalibur.ws/?npc=4397

**Current behaviour**:
Monsters don't reposition at all underwater. They often clip into the player while attacking.

![screenshot_23](https://user-images.githubusercontent.com/9539181/46729214-f9976c80-cc84-11e8-82d2-67baba52d941.png)

![screenshot_24](https://user-images.githubusercontent.com/9539181/46729226-fe5c2080-cc84-11e8-8429-f4256906d3d5.png)

**Expected behaviour**: 
Monsters should reposition underwater.

**Server Revision**: 
2151

**Comment by Wolffenstein** [comment]
Fixed in rev 3399.
