### ISSUE TITLE
Sarltooth in Wetlands is immune to poison

### ISSUE THREAD

**Issue by craigsurbrook** [Atlantiss/NetherwingBugtracker#1442]
[//]: # (Enclose links to things related to the bug using http://wowhead.com or any other TBC database.)
[//]: # (You can use screenshot ingame to visual the issue.)
[//]: # (Write your tickets according to the format:)
[//]: # ([Quest][Azuremyst Isle] Red Snapper - Very Tasty!)
[//]: # ([NPC] Magistrix Erona)
[//]: # ([Spell][Mage] Fireball)
[//]: # ([Npc][Drop] Ghostclaw Lynx)
[//]: # ([Web] Armory doesnt work)

**Description**: 
Sarltooth is a lvl 29 mob involved in quests for "Omer's Revenge" (last part of chain). You can kill him of course without doing the questline. He might be resistant to "spells", but shouldn't be immune to rogue poisons.

**Current behaviour**:
If any poison effect goes off (as part of a weapon proc or from poisons applied to the blade) you will see the "Immune" floating combat text above him (confirmed with blackvenom blade and applied poisons).

**Expected behaviour**: 
I have no memory of Sarltooth ever having been immune to poisons, nor has an in depth search of the internet on his behavior in the past revealed anyone talking about immunity to poisons. I could be wrong, that memory isn't serving me, but I believe that "poisons" might be getting classified under "spells" for this mob (for which I did find an internet reference that said he was resistant to spells, however that might be the Cata version of him as a "rare" spawn).

**Server Revision**:

**Comment by Wolffenstein** [comment]
Fixed in rev 2406.
