### ISSUE TITLE
Precarious Predicament

### ISSUE THREAD

**Issue by Tinnoan** [Atlantiss/NetherwingBugtracker#1443]
**Description**: During the escort quest [Precarious Predicament](https://www.wowhead.com/quest=4121/precarious-predicament) Grark Logrub is currently helping out the player.

**Expected behaviour**: He should not be helping with fighting. He should according to comments on [wowhead](https://www.wowhead.com/quest=4121/precarious-predicament) simply stand still until all the mobs are defeated.

**Server Revision**: 

First Ambush
![world of warcraft screenshot 2018 10 10 - 00 27 33 19](https://user-images.githubusercontent.com/25431721/46731109-28641180-cc8a-11e8-961a-decaee3259db.png)

Second Ambush
![world of warcraft screenshot 2018 10 10 - 00 33 39 75](https://user-images.githubusercontent.com/25431721/46731082-12eee780-cc8a-11e8-8c23-25058c987948.png)

Third Ambush
![world of warcraft screenshot 2018 10 10 - 00 36 49 54](https://user-images.githubusercontent.com/25431721/46731098-213d0380-cc8a-11e8-9133-e9365d39f0d9.png)

**Comment by wtRCH** [comment]
- Change his (react state maybe?) flag to not assist he player during the escort.

@pelekon

**Comment by Evolvee** [comment]
any proof of the "no help" react state? all i see is one 0 rep comment
