### ISSUE TITLE
[STV] The Monogrammed Sash / Mok'Rash

### ISSUE THREAD

**Issue by Azalen** [Atlantiss/NetherwingBugtracker#1444]
**Description**: 
https://web.archive.org/web/20071105003129/http://wow.allakhazam.com:80/db/mob.html?wmob=1493
https://classicdb.ch/?npc=1493

**Current behaviour**:
Mok'Rash did not drop the quest starter item.

**Expected behaviour**: 
I am pretty sure he should ALWAYS drop one of the quest starter items but not for everyone in the group. Thus the 87% dropchance on Allakhazam. The mob also got a 2h respawn timer on patch 1.4 down from 9h, worth checking as well. But being a 2h respawn mob with a quest starter item I think it makes sense to be 100% - especially after 2.3.

There is also not a single comment on both wowhead and allakhazam indicating that it did not drop from a kill. 

> Posted: Aug 22nd 2007 4:00am | IP: Logged | Reply to this
> Calaedre
> 10 posts
> Score: Decent
> On the little island across from booty bay... only dropped the sash for me (sadly). Lv 48 Hunter. Mended Pet before he even got hit, kept it up the whole fight, stayed in the water and just shot him (serpent sting + arcane shot + multi shot) , only took about 30 seconds. Pet got down to 1/4 health, but was pretty easy fight.

**Server Revision**: 
[2151]

**Comment by Azalen** [comment]
Update: We killed him 2h later again and he dropped the quest starter for both of us.

**Comment by Evolvee** [comment]
rev sample_text
