### ISSUE TITLE
[NPC][Uldaman] Ancient Stone Keeper - trash linking to boss

### ISSUE THREAD

**Issue by Firroth** [Atlantiss/NetherwingBugtracker#1445]
[NPC] [Ancient Stone Keeper](https://www.wowhead.com/npc=7206/ancient-stone-keeper#comments)

**Current behaviour**:
When you pull boss, mobs in the room won't pull to help boss if you didn't clear the room first.

**Expected behaviour**: 
If you didn't clear the room with boss, all mobs should come to help the boss.

Mobs which should pull if not killed before engaging the boss:

1. [Earthen Rocksmasher](https://www.wowhead.com/npc=7011/earthen-rocksmasher)
2. [Earthen Sculptor](https://www.wowhead.com/npc=7012/earthen-sculptor)
3. [Stone Steward](https://www.wowhead.com/npc=4860/stone-steward)

![screenshot_2](https://user-images.githubusercontent.com/43505196/46731859-2307c680-cc8c-11e8-88db-02f5f9c98a31.png)

![screenshot_1](https://user-images.githubusercontent.com/43505196/46731860-23a05d00-cc8c-11e8-9b85-1459b138e223.png)

**Server Revision**: 
2151

**Comment by Evolvee** [comment]
rev sample_text
