### ISSUE TITLE
Minion's and Invader's Scourgestones

### ISSUE THREAD

**Issue by Tinnoan** [Atlantiss/NetherwingBugtracker#1446]
**Description**: Diseased Flayer, Scourge Champion, Dread Weaver and Dark Adept all drop Minion's Scourgestone

**Expected behaviour**: According to the info I've found searching around a few different places it all appears to be the same as wowhead for [Minion's Scourgestone](https://www.wowhead.com/item=12840/minions-scourgestone) and [Invader's Scourgestone](https://www.wowhead.com/item=12841/invaders-scourgestone) says that all of those mobs should be dropping Invader's Scourgestones and not Minion's Scourgestone

**Server Revision**: 2151

![world of warcraft screenshot 2018 10 10 - 13 20 04 39](https://user-images.githubusercontent.com/25431721/46733161-d45c2b80-cc8f-11e8-9929-4ec7ba1b65d5.png)

**Comment by Wolffenstein** [comment]
Isn't this because those mobs used to be elite and got nerfed in 2.3?

**Comment by Tinnoan** [comment]
I don't actually know, but I haven't found any evidence to suggest their scourgestone loot was ever changed.

**Comment by Wolffenstein** [comment]
I made it based on elite status - minion dropping from non-elites and invader from elite undeads.

**Comment by Shanghi** [comment]
These should be fixed after revision 2525.
