### ISSUE TITLE
[Dungeon] Dire Maul North - Lootable tribute run chest without killing the king.

### ISSUE THREAD

**Issue by wowthings** [Atlantiss/NetherwingBugtracker#1448]
[//]: # (Enclose links to things related to the bug using http://wowhead.com or any other TBC database.)
[//]: # (You can use screenshot ingame to visual the issue.)
[//]: # (Write your tickets according to the format:)
[//]: # ([Quest][Azuremyst Isle] Red Snapper - Very Tasty!)
[//]: # ([NPC] Magistrix Erona)
[//]: # ([Spell][Mage] Fireball)
[//]: # ([Npc][Drop] Ghostclaw Lynx)
[//]: # ([Web] Armory doesnt work)

**Description**: 
Chest that spawns when you do a tribute run solo or with a group

**Current behaviour**:

The chest is already there and I'm able to loot it without any problems.
![wowscrnshot_101018_034446](https://user-images.githubusercontent.com/43504905/46740471-31151180-cca3-11e8-9214-2b3f52be900f.jpg)
**Expected behaviour**: 
No chest until King Gordok is dead during a tribute run.

**Server Revision**: 
2151

**Comment by Evolvee** [comment]
rev sample_text
