### ISSUE TITLE
[NPC] Palemane Skinner [Spell] Rejuvenation

### ISSUE THREAD

**Issue by The14me** [Atlantiss/NetherwingBugtracker#145]
**Current behaviour**:Spam Rejuvenation.

**Expected behaviour**:
https://www.wowhead.com/npc=2950/palemane-skinner
Rejuvenation ID : 774
 Suppose to have some CD

**Server Revision**:

**Comment by xmesaj2** [comment]
got a fix for that

**Comment by xmesaj2** [comment]
fixed in rev 2035
