### ISSUE TITLE
[Quest][Azshara] A Crew Under Fire - misplaced text and missing emote

### ISSUE THREAD

**Issue by Firroth** [Atlantiss/NetherwingBugtracker#1450]
[Quest] [A Crew Under Fire](https://www.wowhead.com/quest=3382/a-crew-under-fire)
[NPC] [Captain Vanessa Beltis](https://www.wowhead.com/npc=8380/captain-vanessa-beltis)

**Description**: 
Defending Quest Giver.

**Current behaviour**:

**Issue 1**. I didn't check properly but I think she didn't use "cheer/victory" pose, when all waves have been killed.

**Issue 2**. Also when you finish the quest and go to turn it in to her, you get some text which doesn't belong to this NPC. - It's for someone from horde side.

![screenshot_8](https://user-images.githubusercontent.com/43505196/46752015-709c2780-ccbc-11e8-907c-d13670743034.png)

She should only have "completion text", without text which in most quests is to "ask" if you completed your mission. You should talk to her only once "complete quest" but now you click 2 times "continue->complete quest"

**Expected behaviour**: 

**Issue 1**. She should use victory/cheer pose after killing all waves.

**Issue 2**. You should talk to her only once "complete quest" without "continue" option,.

**Server Revision**: 
2151

**Comment by Evolvee** [comment]
rev 439kcolb
