### ISSUE TITLE
[Quest]Triage#6622 last NPC you rescue glides on the floor to quest giver & dying sound played

### ISSUE THREAD

**Issue by Tenoutoften** [Atlantiss/NetherwingBugtracker#1453]
**Description**: 
Once you rescue the last NPC in [[Quest]Triage#6622](https://db.excalibur.ws/?quest=6622) he will glide to the quest giver, [[NPC]Doctor Gregory Victor#12920](https://db.excalibur.ws/?npc=12920) and any remaining soilders will play the dying sound as they despawn. Video [here](https://youtu.be/0ptl3Ec-tCY?t=140)

[[NPC]Badly Injured Soldier#12924](https://db.excalibur.ws/?npc=12924)
[[NPC]Critically Injured Soldier#12925](https://db.excalibur.ws/?npc=12925)
[[NPC]Injured Soldier#12923](https://db.excalibur.ws/?npc=12923)

**Expected behaviour**: 
Expected to not glide on the floor to quest giver.

**Server Revision**: 
2151

**Comment by Tenoutoften** [comment]
Here for the two other reports I did on this quest(s)
https://github.com/Atlantiss/NetherwingBugtracker/issues/1456
https://github.com/Atlantiss/NetherwingBugtracker/issues/1455

**Comment by Evolvee** [comment]
https://github.com/Atlantiss/NetherwingBugtracker/issues/1533
