### ISSUE TITLE
[NPC] Slitherblade Sorceress

### ISSUE THREAD

**Issue by Retinus** [Atlantiss/NetherwingBugtracker#1454]
**Description**: Quest [Other Fish to Fry](https://wow.gamepedia.com/Other_Fish_to_Fry)

**Current behaviour**: Cant interrupt Slitherblade Sorceress spells with earth shock.

**Expected behaviour**: Able to interrupt her casts. Haven't found any comment that tells its immune to interrupts. Also no message in combat log.

**Server Revision**: 2151

**Comment by Evolvee** [comment]
![image](https://user-images.githubusercontent.com/1942409/46755135-99281f80-ccc4-11e8-9311-8487f1abe299.png)

the spell is not interruptable (0x00000009)
