### ISSUE TITLE
[RP][NPC][Quest]Triage#6622/6624 lacks RP texts from soliders

### ISSUE THREAD

**Issue by Tenoutoften** [Atlantiss/NetherwingBugtracker#1455]
**Description**: 
The NPCs you rescue in [[Quest]Triage#6622](https://db.excalibur.ws/?quest=6622), given by  [[NPC]Doctor Gregory Victor#12920](https://db.excalibur.ws/?npc=12920) only do one RP text which is the same thanks:
>I'm saved! Thank you, doctor!

Video [here](https://www.youtube.com/watch?v=0ptl3Ec-tCY&feature=youtu.be)
Two from retail:
[Vanilla](https://www.youtube.com/watch?v=6cc5Lc54eMs)
[Early Wrath?](https://www.youtube.com/watch?v=3Pn7Eg7u9uo)

-----------------------
**Horde Injured Soliders:**
* [[NPC]Badly Injured Soldier#12924](https://db.excalibur.ws/?npc=12924)
* [[NPC]Critically Injured Soldier#12925](https://db.excalibur.ws/?npc=12925)
* [[NPC]Injured Soldier#12923](https://db.excalibur.ws/?npc=12923)

**Alliance Injured Soliders**
* [[NPC]Badly Injured Alliance Soldier#12936(https://db.excalibur.ws/?npc=12936)
* [[NPC]Critically Injured Alliance Soldier#12937(https://db.excalibur.ws/?npc=12937)
* [[NPC]Injured Alliance Soldier(https://db.excalibur.ws/?npc=12938)

----------------------
They are expected to do several different texts, two different "thank you"-texts
>I'm saved! Thank you, doctor!

>HOORAY! I AM SAVED!

evidence from later expansion [video](https://youtu.be/2BoZk5kKXcY?t=133)
>The good doctor saves the day! HOORAY!

But also a few complaining about pain - I am not sure if they all say it, but I listed the ones I saw in the videos

[[NPC]Injured Soldier#12923](https://db.excalibur.ws/?npc=12923)
>Dying... See the light... gloriouss...

[[NPC]Injured Soldier#12923](https://db.excalibur.ws/?npc=12923)
>Brain encaved... mortar... bas... hed... leaking... dyin... g...

[[NPC]Injured Soldier#12923](https://db.excalibur.ws/?npc=12923)
>I'm not gonna make it... death comes...

[[NPC]Critically Injured Soldier#12925](https://db.excalibur.ws/?npc=12925)
>Heeellp meee... ri... ribss... bro... broken.

[[NPC]Injured Soldier#12923](https://db.excalibur.ws/?npc=12923) (Later patch evidence but might have been ingame) [video](https://youtu.be/2BoZk5kKXcY?t=26)
>I... I think I see Blue...

[wowhead comments](https://www.wowhead.com/quest=6622/triage#comments)
![first aid](https://user-images.githubusercontent.com/34839199/46755562-aeea1480-ccc5-11e8-9a81-fa3ea9ff8aeb.png)[video from later patch](https://youtu.be/2BoZk5kKXcY?t=184)
>Goodbye cruel world...  I'm leavin' you today... goodbye... goodbye... goodbye...

[Video from later patch ~wotlk/cata](https://youtu.be/nTMuoifKnMw?t=45)
>Sweet, sweet embrace... take me...

**Expected behaviour**: 
Expecting several different RP texts I am fairly certain the alliance & horde share texts

**Server Revision**: 
2151

**Comment by Tenoutoften** [comment]
Also did these reports on the same quest(s):
https://github.com/Atlantiss/NetherwingBugtracker/issues/1456
https://github.com/Atlantiss/NetherwingBugtracker/issues/1453

**Comment by Evolvee** [comment]
https://github.com/Atlantiss/NetherwingBugtracker/issues/1533
