### ISSUE TITLE
[[Quest]Triage#6622/6624 doesn't instantly spawn [NPC]Soliders once started

### ISSUE THREAD

**Issue by Tenoutoften** [Atlantiss/NetherwingBugtracker#1456]
**Description**: 
After starting [[Quest]Triage#6622](https://db.excalibur.ws/?quest=6622), given by  [[NPC]Doctor Gregory Victor#12920](https://db.excalibur.ws/?npc=12920)  for horde, and [[Quest]Triage#6624] by [[NPC]Doctor Gustaf VanHowzen#12939](https://db.excalibur.ws/?npc=12939) multiple injured soliders should spawn right away as can be seen in videos below

[Netherwing](https://www.youtube.com/watch?v=0ptl3Ec-tCY&feature=youtu.be)
Two from retail:
[Vanilla](https://www.youtube.com/watch?v=6cc5Lc54eMs)
[Early Wrath?](https://www.youtube.com/watch?v=3Pn7Eg7u9uo)

-----------------------
**Horde Injured Soliders:**
* [[NPC]Badly Injured Soldier#12924](https://db.excalibur.ws/?npc=12924)
* [[NPC]Critically Injured Soldier#12925](https://db.excalibur.ws/?npc=12925)
* [[NPC]Injured Soldier#12923](https://db.excalibur.ws/?npc=12923)

**Alliance Injured Soliders**
* [[NPC]Badly Injured Alliance Soldier#12936](https://db.excalibur.ws/?npc=12936)
* [[NPC]Critically Injured Alliance Soldier#12937](https://db.excalibur.ws/?npc=12937)
* [[NPC]Injured Alliance Soldier#12938](https://db.excalibur.ws/?npc=12938)

----------------------
https://www.wowhead.com/quest=6622/triage#comments
https://www.wowhead.com/quest=6624/triage#comments
![eb4488838631ddef5ec7d61c6a281ba8](https://user-images.githubusercontent.com/34839199/46756292-65022e00-ccc7-11e8-9d9b-15b14f1abf62.png)

**Expected behaviour**: 
Expecting multiple soldiers to instantly spawn once the quest is taken,

**Server Revision**: 
2151

**Comment by wtRCH** [comment]
#1455

**Comment by Tenoutoften** [comment]
I did two other reports on this quest: https://github.com/Atlantiss/NetherwingBugtracker/issues/1455 as mentioned above and https://github.com/Atlantiss/NetherwingBugtracker/issues/1453

**Comment by Evolvee** [comment]
https://github.com/Atlantiss/NetherwingBugtracker/issues/1533
