### ISSUE TITLE
Smoke/Burn animation bug

### ISSUE THREAD

**Issue by maxturtlesc2** [Atlantiss/NetherwingBugtracker#1457]
[//]: # (Enclose links to things related to the bug using http://wowhead.com or any other TBC database.)
[//]: # (You can use screenshot ingame to visual the issue.)
[//]: # (Write your tickets according to the format:)
[//]: # ([Quest][Azuremyst Isle] Red Snapper - Very Tasty!)
[//]: # ([NPC] Magistrix Erona)
[//]: # ([Spell][Mage] Fireball)
[//]: # ([Npc][Drop] Ghostclaw Lynx)
[//]: # ([Web] Armory doesnt work)
https://i.imgur.com/CPCPt2U.gifv
**Description**: 
Animation bug at 87.4, 79.2 on a dead tree in Demon Fall Canyon in Ashenvale
**Current behaviour**:
Animation bugged.
**Expected behaviour**: 
Smooth animation.
**Server Revision**:

**Comment by Evolvee** [comment]
client-side
