### ISSUE TITLE
[NPC][The Barrens] Dishu, Savannah Cub

### ISSUE THREAD

**Issue by eryczek1615** [Atlantiss/NetherwingBugtracker#1458]
**Description**: 
Dishu - https://www.wowhead.com/npc=5865  
Savannah Cub - https://www.wowhead.com/npc=5766  

**Current behaviour**:
After we kill Dishu all Savannah Cub(lvl13) despawn only one is still fighting

**Expected behaviour**: 
After Dishu's death Savannah Cub(lvl9) Shouldn't despawn
Comment from wowhead: (Patch 2.0.6)
"When I found Dishu and attacked him just now; four Savannah Cubs, "Dishu's Guardians", all level 9, appeared when I drew aggro on him. Killed him, but didn't have enough life to slay the cubs. Oh well."

**Server Revision**: 
2152

**Comment by wtRCH** [comment]
Someone, please research it if it was changed in 2.3

**Comment by eryczek1615** [comment]
Yes they fight properly so I don't know maybe that was disposable bug.
