### ISSUE TITLE
[NPC] Lar'korwi Mate does not aggro on spawn.

### ISSUE THREAD

**Issue by Jezofine** [Atlantiss/NetherwingBugtracker#1459]
**Description**: 
[Lar'korwi Mate](https://www.wowhead.com/npc=9683/larkorwi-mate#comments) is an npc spawned near raptor eggs for quest [The Scent of Lar'korwi](https://www.wowhead.com/quest=4291/the-scent-of-larkorwi#comments).

**Current behaviour**:
Stands still after swapning for several seconds, not attacking player.
Also cooldown on their nests is pretty low, about 2 mins, but I don't know if that's an issue.

**Expected behaviour**:
Should aggro on player immediately.

Comments from 2.0-2.4:
([The Scent of Lar'korwi](https://www.wowhead.com/quest=4291/the-scent-of-larkorwi#comments))
> Ravesour Mates only spawn when u run across eggs. Do it and one will come rushing at you.
>
> i have just pulled a ravasaur(that was next to an egg pile) and did not run over the pile of eggs and the mate spawned and aggroed....
>
> Did this quest today on my druid, and I was in shapeshift + prowl and i stood at the eggs and got aggro from the guarding mother.

([Lar'korwi Mate](https://www.wowhead.com/npc=9683/larkorwi-mate#comments))
> As a rogue, standing on the eggs while stealthed didn't baited the mates. A mate appeared a couple of seconds after I unstealthed. Even though I had the time to restealth, the mate went directly for me and attacked me.

Although there's comment from 3.0:
> Sometimes mates can spawn without aggroing on you.

**Server Revision**: 2152

**Comment by wtRCH** [comment]
Probably changed in prepatch of WotLK

**Comment by Tereneckla** [comment]
aggroes on spawn as of 3236
