### ISSUE TITLE
[Quest] [Stormwind City] The Stonewrought Dam, Spooky Lighthouse, The Bough of the Eternals

### ISSUE THREAD

**Issue by Mikik3jr** [Atlantiss/NetherwingBugtracker#146]
[//]: # (Enclose links to things related to the bug using http://wowhead.com or any other TBC database.)
[//]: # (You can use screenshot ingame to visual the issue.)
[//]: # (Write your tickets according to the format:)
[//]: # ([Quest][Azuremyst Isle] Red Snapper - Very Tasty!)
[//]: # ([NPC] Magistrix Erona)
[//]: # ([Spell][Mage] Fireball)
[//]: # ([Npc][Drop] Ghostclaw Lynx)
[//]: # ([Web] Armory doesnt work)

**Description**: 
Alliance children's week begining is a bugfest. The Human Orphan Whistle item which summons you a kid has the "!" mark above his head, but doesn't give any quest. The first 3 quests can be done doing nothing. You take the quest, then finish it.
![wowscrnshot_092318_110831](https://user-images.githubusercontent.com/43505031/45926303-b7023000-bf21-11e8-9243-856debcc04b9.jpg)

**Current behaviour**:
When you take the the first 3 quests that are mentioned in the title (the kid gives it next to the mom thatgives you the whistle item) it automatically completes. I got the quest then I handed in instantly.

**Expected behaviour**: 
(I don't know if you can take quests from your summoned kid sorry)
According to wowhead comments you are supposed to go to the locations and summon the kid there to complete the quest. https://www.wowhead.com/quest=1687/spooky-lighthouse
![wowscrnshot_092318_110848](https://user-images.githubusercontent.com/43505031/45926392-4ad3fc00-bf22-11e8-8455-2a5855756efe.jpg)
![wowscrnshot_092318_110859](https://user-images.githubusercontent.com/43505031/45926395-51627380-bf22-11e8-9e3e-3d70ec635fec.jpg)
![wowscrnshot_092318_110902](https://user-images.githubusercontent.com/43505031/45926400-56bfbe00-bf22-11e8-872a-407f56429415.jpg)
![wowscrnshot_092318_110915](https://user-images.githubusercontent.com/43505031/45926475-a0100d80-bf22-11e8-90ad-fb4d49ac077e.jpg)
![wowscrnshot_092318_110921](https://user-images.githubusercontent.com/43505031/45926476-a2726780-bf22-11e8-8b12-d4bb0d5f9238.jpg)

**Server Revision**: 
2028

**Comment by BamboozleNW** [comment]
No event, does not offer quest, can be closed.
