### ISSUE TITLE
[NPC] Winterfall Runner doesn't assist or attack

### ISSUE THREAD

**Issue by totaemoeggerli** [Atlantiss/NetherwingBugtracker#1462]
[//]: # (Enclose links to things related to the bug using http://wowhead.com or any other TBC database.)
[//]: # (You can use screenshot ingame to visual the issue.)
[//]: # (Write your tickets according to the format:)
[//]: # ([Quest][Azuremyst Isle] Red Snapper - Very Tasty!)
[//]: # ([NPC] Magistrix Erona)
[//]: # ([Spell][Mage] Fireball)
[//]: # ([Npc][Drop] Ghostclaw Lynx)
[//]: # ([Web] Armory doesnt work)

**Description**: 
https://www.wowhead.com/npc=10916/winterfall-runner
3 mobs patroling from Timbermaw Hold to Winterfall Village. 

**Current behaviour**:
https://gfycat.com/gifs/detail/FeistyAngryIcelandgull
They don't aggro if you are close to them and they don't assist if you attack one of them.

**Expected behaviour**: 
They should be linked, all 3 should attack the player. They should aggro if close just like every other mob.

**Server Revision**: 2151

**Comment by Evolvee** [comment]
formation aggro link fixed

the rest of the report is invalid in rev sample_text

![image](https://user-images.githubusercontent.com/1942409/46821334-a60e4700-cd88-11e8-8f11-73d09c84b51f.png)
