### ISSUE TITLE
[NPC]Fardel Dabyrie#4479 lacking alternative spawn spot

### ISSUE THREAD

**Issue by Tenoutoften** [Atlantiss/NetherwingBugtracker#1463]
**Description**: 
[[NPC]Fardel Dabyrie#4479](https://db.excalibur.ws/?npc=4479) is currently only spawning outside the barn. Should also be spawning by/inside the stable and possibly on the other side of the barn as well. NPC is part of the [[Quest]To Steal from Thieves#1164](https://db.excalibur.ws/?quest=1164)

![4d2fe95d6e2438b51ada947be455c923](https://user-images.githubusercontent.com/34839199/46760463-7270e580-ccd2-11e8-8c77-6b9f4f74a78a.png)
![47253c249143b0a8c47a642f00bf6c4e](https://user-images.githubusercontent.com/34839199/46760464-7270e580-ccd2-11e8-952e-c6283d9aaa2d.png)
![649251edc82a7a561aaba0a4c55ddafb](https://user-images.githubusercontent.com/34839199/46760466-7270e580-ccd2-11e8-8782-dca882829a57.png)

[Video](https://youtu.be/vaTES-R1hD8?t=166) from a much later expansion displaying different spawning spot

**Expected behaviour**: 
Expected to also spawn by/inside the stable and other side of the barn.

**Server Revision**: 
2152

**Comment by aresbrutus** [comment]
Fixed in rev `Tycho`.
