### ISSUE TITLE
[NPC]Fardel Dabyrie#4479 should flee on low HP

### ISSUE THREAD

**Issue by Tenoutoften** [Atlantiss/NetherwingBugtracker#1464]
**Description**: 
[[NPC]Fardel Dabyrie#4479](https://db.excalibur.ws/?npc=4479) should flee on low HP. NPC is part of the [[Quest]To Steal from Thieves#1164](https://db.excalibur.ws/?quest=1164)
![cf2a7e2f4d8f4892921ea6f1e5fc0cdd](https://user-images.githubusercontent.com/34839199/46761057-e52e9080-ccd3-11e8-922b-e2a992113bb0.png)

[Video](https://youtu.be/vaTES-R1hD8?t=234) from a much later patch showing he flees.

**Expected behaviour**: 
Expected to occasionally flee on low HP.

**Server Revision**: 
2152

**Comment by Evolvee** [comment]
rev sample_text
