### ISSUE TITLE
[NPC] Winterfall Ambusher

### ISSUE THREAD

**Issue by totaemoeggerli** [Atlantiss/NetherwingBugtracker#1465]
[//]: # (Enclose links to things related to the bug using http://wowhead.com or any other TBC database.)
[//]: # (You can use screenshot ingame to visual the issue.)
[//]: # (Write your tickets according to the format:)
[//]: # ([Quest][Azuremyst Isle] Red Snapper - Very Tasty!)
[//]: # ([NPC] Magistrix Erona)
[//]: # ([Spell][Mage] Fireball)
[//]: # ([Npc][Drop] Ghostclaw Lynx)
[//]: # ([Web] Armory doesnt work)

**Description**: 
These mobs spawn after turning in Winterfall Runners.
https://www.wowhead.com/npc=14372/winterfall-ambusher#comments

**Current behaviour**:
They attack you even if you are out of aggro range and don't stop chasing after you.
https://gfycat.com/ForthrightSlowFerret

**Expected behaviour**: 
They shouldn't attack you if you are far away
they should reset if you run away
By adashiel (276,111 – 15·89·931) on 2007/09/20 (Patch 2.1.3)
> After you complete [DEPRECATED]Winterfall Runners, the quest NPC, Donova Snowden will wander down to the nearby hot spring. These ambushers will spawn, and if you followed her, you'll get attacked. If you want to avoid fighting them, move away from the spring and you'll be fine. The ambushers won't attack her and you don't need to fight them for quest credit.

**Server Revision**: 2151

**Comment by Evolvee** [comment]
rev sample_text
