### ISSUE TITLE
[NPC]Marcel Dabyrie#4481 should flee on low HP

### ISSUE THREAD

**Issue by Tenoutoften** [Atlantiss/NetherwingBugtracker#1466]
**Description**: 
[[NPC]Marcel Dabyrie#4481](https://www.wowhead.com/npc=4481/marcel-dabyrie) should flee on low hp. Basing it off that his friend [[NPC]Fardel Dabyrie#4479](https://db.excalibur.ws/?npc=4479) flees on low hp. Currently doesn't flee

![cf2a7e2f4d8f4892921ea6f1e5fc0cdd](https://user-images.githubusercontent.com/34839199/46761057-e52e9080-ccd3-11e8-922b-e2a992113bb0.png)
[Video](https://youtu.be/vaTES-R1hD8?t=351) from a much later patch showing he flees.

**Expected behaviour**: 
Expected to flee.

**Server Revision**: 
2152

**Comment by Evolvee** [comment]
rev sample_text
