### ISSUE TITLE
[NPC]Kenata Dabyrie#4480 should flee on low HP

### ISSUE THREAD

**Issue by Tenoutoften** [Atlantiss/NetherwingBugtracker#1467]
**Description**: 
[[NPC]Kenata Dabyrie#4480](https://www.wowhead.com/npc=4480/kenata-dabyrie) should flee on low HP. NPC is part of the [[Quest]To Steal from Thieves#1164](https://db.excalibur.ws/?quest=1164) basing it on that her friend does flee
![cf2a7e2f4d8f4892921ea6f1e5fc0cdd](https://user-images.githubusercontent.com/34839199/46761057-e52e9080-ccd3-11e8-922b-e2a992113bb0.png)

And a [Video](https://youtu.be/vaTES-R1hD8?t=424) from a much later patch showing she flees.

**Expected behaviour**: 
Expected to flee on low HP.

**Server Revision**: 
2152

**Comment by Evolvee** [comment]
rev sample_text
