### ISSUE TITLE
[RP EVENT][Blackrock Depths] Ring of Law - Broken Event

### ISSUE THREAD

**Issue by Firroth** [Atlantiss/NetherwingBugtracker#1468]
[NPC] [Dark Screecher](https://wow.gamepedia.com/Dark_Screecher)

**Description**: 
Arena Boss Event

**Current behaviour**:
We tried Ring of Law event 2 times, in this two times we got the same spawns - [NPC] [Dark Screecher](https://wow.gamepedia.com/Dark_Screecher). First wave was 1 [NPC] [Dark Screecher](https://wow.gamepedia.com/Dark_Screecher), 2nd wave was 2 [NPC] [Dark Screecher](https://wow.gamepedia.com/Dark_Screecher), 3rd wave was again 1 [NPC] [Dark Screecher](https://wow.gamepedia.com/Dark_Screecher). After that nothing, no more mobs, event not continuing. Impossible to leave the arena. We needed GM's help 2 times, just to get out of it.

No idea, if it's like that with other spawns too, it's worth checking.

**Expected behaviour**: 
After waves of mobs have been killed, event should continue - Gate where they came from should be closed, and arena announcer should go to second gate and spawn boss afterwards.

**Server Revision**: 
2152

**Comment by paoea** [comment]
I think we got the correct waves. But after wiping the healer used Ankh and rezzed us. The Event didn't start again and we also couldn't get out anymore.
Please Fix

**Comment by Tereneckla** [comment]
Fixed
