### ISSUE TITLE
[NPC][Blackrock Depths] High Justince Grimstone - bad type of saying text

### ISSUE THREAD

**Issue by Firroth** [Atlantiss/NetherwingBugtracker#1469]
[NPC] [High Justince Grimstone](https://www.wowhead.com/npc=10096/high-justice-grimstone)

**Current behaviour**:
Currently when you start Ring of Law event, he "says" all his texts.

**Expected behaviour**: 
He should "Yell" all his texts.

**Server Revision**: 
2152

**Comment by Evolvee** [comment]
rev sample_text
