### ISSUE TITLE
Quest/Tauren Starting Area

### ISSUE THREAD

**Issue by AlteredAli** [Atlantiss/NetherwingBugtracker#147]
[//]: # (Enclose links to things related to the bug using http://wowhead.com or any other TBC database.)
[//]: # (You can use screenshot ingame to visual the issue.)
[//]: # (Write your tickets according to the format:)
[//]: # ([Quest][Azuremyst Isle] Red Snapper - Very Tasty!)
[//]: # ([NPC] Magistrix Erona)
[//]: # ([Spell][Mage] Fireball)
[//]: # ([Npc][Drop] Ghostclaw Lynx)
[//]: # ([Web] Armory doesnt work)

**Description**: 
The quest "The hunt begins" is bugged, plainstrider meat has very low drop chance.
**Current behaviour**:

**Expected behaviour**: 

**Server Revision**: 
2028

**Comment by The14me** [comment]
blizzlike
