### ISSUE TITLE
[Core][Object][Blackrock Depths] The Vault and missing object

### ISSUE THREAD

**Issue by Firroth** [Atlantiss/NetherwingBugtracker#1471]
[NPC] [Dark Keeper Vorfalk](https://www.wowhead.com/npc=9437/dark-keeper-vorfalk) and his nameplate [Object] [Dark Keeper Nameplate](https://www.wowhead.com/object=164820/dark-keeper-nameplate)

[NPC] [Dark Keeper Bethek](https://www.wowhead.com/npc=9438/dark-keeper-bethek) and his nameplate [Object] [Dark Keeper Nameplate](https://www.wowhead.com/object=164821/dark-keeper-nameplate)

[NPC] [Vorfalk Irongourd](https://www.wowhead.com/npc=9437/dark-keeper-vorfalk) and his nameplate [Object] [Dark Keeper Nameplate](https://www.wowhead.com/object=164820/dark-keeper-nameplate)

[NPC] [Dark Keeper Ofgut](https://www.wowhead.com/npc=9442/dark-keeper-ofgut) and his nameplate [Object] [Dark Keeper Nameplate](https://www.wowhead.com/object=164824/dark-keeper-nameplate)

[NPC] [Dark Keeper Pelver](https://www.wowhead.com/npc=9443/dark-keeper-pelver) and his nameplate [Object] [Dark Keeper Nameplate](https://www.wowhead.com/object=164825/dark-keeper-nameplate)

[NPC] [Dark Keeper Uggel](https://www.wowhead.com/npc=9439/dark-keeper-uggel) and his nameplate [Object] [Dark Keeper Nameplate](https://www.wowhead.com/object=164822/dark-keeper-nameplate)

[NPC] [Dark Keeper Zimrel](https://www.wowhead.com/npc=9441/dark-keeper-zimrel) and his nameplate [Object] [Dark Keeper Nameplate](https://www.wowhead.com/object=164823/dark-keeper-nameplate)

**Current behaviour**:
Currently there is no such object (nameplate) on the portrait (or there is but it has set untargetable flag), which makes it harder for players to know which boss spawned and where. Boss himself didn't seem to spawn.

![screenshot_2](https://user-images.githubusercontent.com/43505196/46766747-398d3c80-cce3-11e8-89a7-78e429d9fdf0.png)

**Expected behaviour**: 
When you open the picture, there should be one random "nameplate" on it from the list above, which in turn triggers "spawning the boss" somewhere in BRD depending on which nameplate was on it (1 random nameplate from total of 6). When you click on it you will see name of boss and some description. This makes it easy to know which boss spawned and where.

List of where random boss should spawn depending on which nameplate was on the picture.

![screenshot_3](https://user-images.githubusercontent.com/43505196/46766760-414ce100-cce3-11e8-9918-abed49d4400f.png)

Check 5:10, how it should look like.
https://www.youtube.com/watch?v=q_OnhjzAcYE

**Server Revision**: 
2152

**Comment by Evolvee** [comment]
@aresbrutus u didnt report this pepoGun

**Comment by aresbrutus** [comment]
I didn't report this? I actually went out of my way to spend shit tons on making the report with as much info as possible here: https://github.com/Atlantiss/AtlantissTBCBT/issues/3698

**Comment by aresbrutus** [comment]
2 and 3 are the same pictures and I also wrote it in my closed beta report where they should spawn but still, thanks for showing us anyway.

**Comment by GMThunderan** [comment]
Got a report about this today and checked ingame for objects. The only one I could find was [164825](https://www.wowhead.com/object=164825/dark-keeper-nameplate) . But that wasn't spawning a boss as well. So still needs attention.

**Comment by devo6969** [comment]
I was looking into this as well if you guys need anymore information than what you have please let me know. 

PTR Picture - https://www.youtube.com/watch?v=wvCM8SuCcjo
Retail Picture (Shows Vorfalk) - https://www.youtube.com/watch?v=qQg0MB7Ag1A
Vorfalk Irongourd  Location - https://www.youtube.com/watch?v=5owb83ogjG4

**Comment by Godmatik** [comment]
Closing - all BRD information will be consolidated into one thread
