### ISSUE TITLE
[NPC][Spell][Blackrock Depths] The Seven - Dope'rel Evasion

### ISSUE THREAD

**Issue by Firroth** [Atlantiss/NetherwingBugtracker#1472]
[NPC] [Dope'rel](https://www.wowhead.com/npc=9040/doperel)
[Spell] [Evasion](https://vanilla-twinhead.twinstar.cz/?spell=15087)

**Current behaviour**:
[Spell] [Evasion](https://vanilla-twinhead.twinstar.cz/?spell=15087) from [NPC] [Dope'rel](https://www.wowhead.com/npc=9040/doperel) seems to be broken. When he used it, he should dodge almost all of my attacks (dual wield) but he managed to dodge only 1 attack. Same goes for Rogue from our party, but in his case any of his hits haven't been dodged. Which makes it almost clear that this spell doesn't work.

**Expected behaviour**: 
[Spell] [Evasion](https://vanilla-twinhead.twinstar.cz/?spell=15087) should give the boss 50% dodge chance, which in turn should make him harder to kill for meele classes.

**Server Revision**: 
2152

**Comment by Evolvee** [comment]
works fine for me atleast visually in spell tab

**Comment by Evolvee** [comment]
![image](https://user-images.githubusercontent.com/1942409/46819402-e7e8be80-cd83-11e8-8915-e28e60578426.png)

**Comment by Easyfraggy** [comment]
https://github.com/Atlantiss/NetherwingBugtracker/issues/1354

Maybe related? Also gets the buff but no effect.

**Comment by devo6969** [comment]
I didn't see anything wrong with this while testing on the PTR.
Sample from PTR - https://www.youtube.com/watch?v=sTX3x7JD-Go
