### ISSUE TITLE
[NPC][Eastern Plaguelands] Plagued Swine

### ISSUE THREAD

**Issue by wowthings** [Atlantiss/NetherwingBugtracker#1473]
[//]: # (Enclose links to things related to the bug using http://wowhead.com or any other TBC database.)
[//]: # (You can use screenshot ingame to visual the issue.)
[//]: # (Write your tickets according to the format:)
[//]: # ([Quest][Azuremyst Isle] Red Snapper - Very Tasty!)
[//]: # ([NPC] Magistrix Erona)
[//]: # ([Spell][Mage] Fireball)
[//]: # ([Npc][Drop] Ghostclaw Lynx)
[//]: # ([Web] Armory doesnt work)

**Description**: 
One of the [Plagued Swine](http://db.hellfire-tbc.com/?npc=16117) at Terrordale in Eastern Plaguelands...
**Current behaviour**:
 ...is quite adventurous, he appeared through the ceiling of the Terrorweb Tunnel to return to his default position
![wowscrnshot_101018_232006](https://user-images.githubusercontent.com/43504905/46767358-08157080-cce5-11e8-8eb4-a5664143bf67.jpg)
![wowscrnshot_101018_232159](https://user-images.githubusercontent.com/43504905/46767582-b28d9380-cce5-11e8-8166-3d30240e4c1a.jpg)
![wowscrnshot_101018_232102](https://user-images.githubusercontent.com/43504905/46767588-b9b4a180-cce5-11e8-9293-f8d96014b189.jpg)

**Expected behaviour**: 
Should be wandering around his spawn position, not running around the cave full of spiders.

**Server Revision**: 
2153

**Comment by Evolvee** [comment]
NPC most likely felt through ground -.-

**Comment by Wolffenstein** [comment]
Fixed in rev 2158.
