### ISSUE TITLE
[NPC] Gorishi Hive Guard

### ISSUE THREAD

**Issue by totaemoeggerli** [Atlantiss/NetherwingBugtracker#1474]
[//]: # (Enclose links to things related to the bug using http://wowhead.com or any other TBC database.)
[//]: # (You can use screenshot ingame to visual the issue.)
[//]: # (Write your tickets according to the format:)
[//]: # ([Quest][Azuremyst Isle] Red Snapper - Very Tasty!)
[//]: # ([NPC] Magistrix Erona)
[//]: # ([Spell][Mage] Fireball)
[//]: # ([Npc][Drop] Ghostclaw Lynx)
[//]: # ([Web] Armory doesnt work)

**Description**: 
[Gorishi Hive Guard](https://www.wowhead.com/npc=10040/gorishi-hive-guard#comments) only spawns while doing [Pawn Captures Queen](https://www.wowhead.com/quest=4507/pawn-captures-queen).

**Current behaviour**:
Mob is not on team gorishi. You can pull a hive guard that is ontop of a tunneler and the tunneler won't assist. Same the other way around. The queen is on the same team as the hive guard.
https://gfycat.com/PotableFrayedBuzzard

_Additonally, the hive guards don't despawn which is probably blizzlike. However, if a player fails the quest or doesn't bother killing all of them, the next player has to deal with a bunch of mobs, stacked ontop of each other with a 43% physical damage debuff. If that happens many players will skip the quest and miss something really cool. Making them despawn after few minutes would fit the spirit of easier post 2.3 vanilla elite/group quests. The acctual event is still pretty hard._

**Expected behaviour**: 
Hive Guards and other Gorishi mobs should assist each other in combat.

**Server Revision**: 2151

**Comment by Evolvee** [comment]
rev sample_text

**Comment by zhuk90** [comment]
nice scripted but million bugs, good job devs

**Comment by Evolvee** [comment]
?
