### ISSUE TITLE
Linked packs not linking combat trigger

### ISSUE THREAD

**Issue by Erodraeda** [Atlantiss/NetherwingBugtracker#1476]
[//]: # (Enclose links to things related to the bug using http://wowhead.com or any other TBC database.)
[//]: # (You can use screenshot ingame to visual the issue.)
[//]: # (Write your tickets according to the format:)
[//]: # ([Quest][Azuremyst Isle] Red Snapper - Very Tasty!)
[//]: # ([NPC] Magistrix Erona)
[//]: # ([Spell][Mage] Fireball)
[//]: # ([Npc][Drop] Ghostclaw Lynx)
[//]: # ([Web] Armory doesnt work)

**Description**: 
When a hard CC is used (polymorph or sap, i.e.), combat does not trigger to other party members, unless you directly interact with that member.
**Current behaviour**:
When a mage sheep pull a pack, as I rogue I wouldn't enter in combat with that sheep. So, after killing the other mobs of the pack, I could re-stealth before attacking that mob.
**Expected behaviour**: 
The combat trigger should be linked with the pack pull, not with the target alone.
**Server Revision**:

**Comment by Easyfraggy** [comment]
https://github.com/Atlantiss/NetherwingBugtracker/issues/1224

Maybe related to same systems

**Comment by The14me** [comment]
Fixed in 3441.( tested with sheep in BRD)
