### ISSUE TITLE
[NPC][Blackrock Depths] Ambassador Flamelash

### ISSUE THREAD

**Issue by Firroth** [Atlantiss/NetherwingBugtracker#1477]
[NPC] [Ambassador Flamelash](https://www.wowhead.com/npc=9156/ambassador-flamelash)
[Spell] [Burning Spirit](https://www.wowhead.com/spell=14744/burning-spirit) ID 14744 (buff 5% dmg)
[Spell] [Burning Spirit](https://www.wowhead.com/spell=13489/burning-spirit) ID 13489 (kill himself)
[NPC] [Burning Spirit](https://www.wowhead.com/npc=9178/burning-spirit) ID 9178

**Current behaviour**:
When he spawns adds [Burning Spirit](https://www.wowhead.com/npc=9178/burning-spirit), he spawns them near him and they start attacking players.

**Expected behaviour**: 
He should spawn 6 [Burning Spirit](https://www.wowhead.com/npc=9178/burning-spirit) in 6 different locations (1 [Burning Spirit](https://www.wowhead.com/npc=9178/burning-spirit) per rune, on rune), and they shouldn't start attacking or aggroing on players when spawned. They should go to [NPC] [Ambassador Flamelash](https://www.wowhead.com/npc=9156/ambassador-flamelash) position and if they reach him each one add which got to him should buff him [Spell] [Burning Spirit](https://www.wowhead.com/spell=14744/burning-spirit) ID 14744  (5% dmg done more) and use [Spell] [Burning Spirit](https://www.wowhead.com/spell=13489/burning-spirit) ID 13489 (suicide) on themselves.

If [NPC] [Burning Spirit](https://www.wowhead.com/npc=9178/burning-spirit) is attacked by player, only then he should react and go fight the player rather than go to boss.

4:10
https://youtu.be/T7xnH8lKPbw?t=250

**Server Revision**: 
2152

**Comment by aresbrutus** [comment]
Also posting this from old tracker about the runes visual effects: https://github.com/Atlantiss/AtlantissTBCBT/issues/3719

**Comment by randomuser69** [comment]
@Evolvee 
@wtRCH 

This bug was still in the game when I ran BRD about a month ago. Please check if its still in the game and close ticket if it isnt.

Thanks!

**Comment by The14me** [comment]
rev 3441 still an issue.

**Comment by devo6969** [comment]
Can confirmed still bugged. On the PTR the adds would only spawn once he started taking damage and they are suppose to spawn at the 6 locations around the room (Missing visual effect as well @ locations) Spawns were also hostile once they spawned on the PTR and the boss didn't absorb any cause its targeting the player.

PTR - https://www.youtube.com/watch?v=9gprqkmUvxU
Retail BFA - https://www.youtube.com/watch?v=mxJX3oVVoG8

**Comment by Godmatik** [comment]
Closing - all BRD information will be consolidated into one thread
