### ISSUE TITLE
Enchating

### ISSUE THREAD

**Issue by Piledriversn** [Atlantiss/NetherwingBugtracker#1478]
![image](https://user-images.githubusercontent.com/43560552/46770034-717c8b80-ccb3-11e8-954d-3c10cda05fe5.png)
[//]: # ([Enchanting] (within trade window)
**Description**: I attempted to enchant a fellow guildies bracers and it kept saying must have cloth equipped. I checked and he was wearing the bracers but i don't believe it matters as long as its in the do not be traded window.  

**Current behaviour**:Unable to enchant in trade window.

**Expected behaviour**: Enchant anyone's gear as long as its in the do not be traded window.

**Server Revision**:

**Comment by Tereneckla** [comment]
Fixed
