### ISSUE TITLE
[Core][Blackrock Depths] The Seven Encounter

### ISSUE THREAD

**Issue by Firroth** [Atlantiss/NetherwingBugtracker#1480]
**Current behaviour**:
They enter the battle 1 by 1.
Until the one which entered the battle is not dead, another one won't enter the battle.

**Expected behaviour**: 
Every NPC should be entering the battle each 15-20s in their respective order. Which can make situation that players will be f.e fighting against 2 or more if low on dps.

![screenshot_2](https://user-images.githubusercontent.com/43505196/46770587-43696c80-ccf0-11e8-86e1-13c68a00f3da.png)

![screenshot_1](https://user-images.githubusercontent.com/43505196/46770725-de624680-ccf0-11e8-8268-145084c40dc5.png)

**Server Revision**: 
2152

**Comment by Evolvee** [comment]
@aresbrutus u said i should script it 1 by 1 so, handle this report ^^

**Comment by Evolvee** [comment]
the curse thing is known and reported

**Comment by aresbrutus** [comment]
I remember us deciding on that 1: The other guy comes when the first one dies and 2: the other guy comes if the first one does not die fast enough anyway so people can't keep the event going by keeping 1 dwarf in combat.

**Comment by Evolvee** [comment]
wall of text :puke:

**Comment by Tereneckla** [comment]
Fixed
