### ISSUE TITLE
[NPC] Timbermaw Hold reputation items 

### ISSUE THREAD

**Issue by ScottieDOESknow** [Atlantiss/NetherwingBugtracker#1481]
**Description**: Gorn One Eye - Timbermaw Hold vendor

**Current behaviour**:  Able to purchase Furbolg Medicine Pouch & Totem with neutral standing.

https://gyazo.com/03e3f3f130e1345c0f343653df9e7065

**Expected behaviour**: Vendor should only sell these items once appropriate reputation is achieved.  

https://www.wowhead.com/item=16768/furbolg-medicine-pouch#comments:id=113546

**Server Revision**:  2153

**Comment by Shanghi** [comment]
These will be fixed in revision 2175. The client's cache will have to be deleted to see the change on the items.
