### ISSUE TITLE
[Spell][Paladin][Core Mechanic]You don't get a charge of Mana Tap#28734 if you are in Divine Shield#642

### ISSUE THREAD

**Issue by Tenoutoften** [Atlantiss/NetherwingBugtracker#1482]
**Description**: 
You wont get a stack of 
[[Spell]Mana Tap#28734](https://db.excalibur.ws/?spell=28734) if you have [[Spell]Divine Shield(Rank 1)#642](https://db.excalibur.ws/?spell=642). Suspect this also applies to [[Spell]Divine Shield(Rank 2)#1020](https://db.excalibur.ws/?spell=1020)

Video [NW here](https://www.youtube.com/watch?v=201cQHSL5cs&feature=youtu.be)

**Expected behaviour**: 
Expect to get a charge.

**Server Revision**: 
2153

**Comment by Wolffenstein** [comment]
Fixed in rev 2154.
