### ISSUE TITLE
[Item][Loot] Argent Dawn Commission/Scourgestones

### ISSUE THREAD

**Issue by totaemoeggerli** [Atlantiss/NetherwingBugtracker#1483]
[//]: # (Enclose links to things related to the bug using http://wowhead.com or any other TBC database.)
[//]: # (You can use screenshot ingame to visual the issue.)
[//]: # (Write your tickets according to the format:)
[//]: # ([Quest][Azuremyst Isle] Red Snapper - Very Tasty!)
[//]: # ([NPC] Magistrix Erona)
[//]: # ([Spell][Mage] Fireball)
[//]: # ([Npc][Drop] Ghostclaw Lynx)
[//]: # ([Web] Armory doesnt work)

**Description**: 
[Argent Dawn Commision](https://www.wowhead.com/item=12846/argent-dawn-commission#comments) gives a buff that allows you to acquisition Scourgestones.

**Current behaviour**:
Scourgestones drop if you don't have the trinket equiped. The mob will blink as if it has loot but there is no loot. You can equip the trinket and loot the scourgestone.
https://gfycat.com/GraveZanyBorderterrier
It's a bit too fast so you can't see the loot here is a screenshot:
![loot](https://imgur.com/X3ijXvZ.jpg)

**Expected behaviour**: 
You shouldn't be ablte to kill a mob without the trinket, equip it after the fight and get scourgestones.

By ataylor (7,360 – 3·24·38) on 2006/11/11 (Patch 1.12.2)
> You need to have this equipped for scourgestones to drop from undead.

**Server Revision**: 2153

**Comment by wtRCH** [comment]
Confirmed.

- Make Scrougestones drop only if you have trinket equiped / or buffed with trinket spell effect.

@pelekon

**Comment by Tereneckla** [comment]
Fixed
