### ISSUE TITLE
[NPC]Caretaker Nevlin/Weston/Alaric#2780/2781/2782 should reward elite xp

### ISSUE THREAD

**Issue by Tenoutoften** [Atlantiss/NetherwingBugtracker#1484]
**Description**: 
These NPCs should reward elite XP according to wowhead comments from relevant patchs:
[[NPC]Caretaker Nevlin#2780](https://www.wowhead.com/npc=2780/caretaker-nevlin#comments)
[[NPC]Caretaker Weston#2781](https://www.wowhead.com/npc=2781/caretaker-weston#comments)
[[NPC]Caretaker Alaric#2782](https://www.wowhead.com/npc=2782/caretaker-alaric#drops:mode=)
[wowhead comments](https://www.wowhead.com/quest=646/trolkalar#comments)

![698e1e9a3ba92988a44be06141d6b9b9](https://user-images.githubusercontent.com/34839199/46791333-332dad80-cd41-11e8-9e88-1581773e0c8d.png)
![5905c8a7fc455670e58239a8e382ae9a](https://user-images.githubusercontent.com/34839199/46791334-33c64400-cd41-11e8-8dd8-b14a37aa5b01.png)
![fb592e0808a0e6f77e7e26f85cb75daa](https://user-images.githubusercontent.com/34839199/46791337-33c64400-cd41-11e8-9095-771518023fd8.png)

**Current behaviour**:
![eabb2ff3d393abb4c56739a55688bbff](https://user-images.githubusercontent.com/34839199/46791335-33c64400-cd41-11e8-943a-c3512787aff3.png)

These NPCs are also the only ones to drop [[Item]Holy Diadem#2623](https://db.excalibur.ws/?item=2623) according to a comment. Not sure about this one. Looks like it drops all over the place in private server databases, excali: https://db.excalibur.ws/?item=2623
![30a39532d24ce180b27a397a6debe973](https://user-images.githubusercontent.com/34839199/46791575-c1099880-cd41-11e8-8eb9-1892b3c1fe89.png)

**Expected behaviour**: 
Expected to award XP equivalent of an elite

**Server Revision**: 
2153

**Comment by Shanghi** [comment]
The Holy Diadem loot was already fixed before, so just the experience part is left
