### ISSUE TITLE
[QUEST] ID:9150

### ISSUE THREAD

**Issue by networm555** [Atlantiss/NetherwingBugtracker#1486]
[Quest][Eversong Woods] Salvaging the past

[Npc][Drop]Arcane Devourer , Mana Shifter

Drop rate very low. 10 minutes for 2 items is absurd. Possible bottleneck scenario.
How it should work: https://www.youtube.com/watch?v=1yNzxlhmUy8

**Comment by networm555** [comment]
You should consider to provide all those drop quests with higher chanse numbers . That what  was made at Felmyst. Thats was one of the main reasons people consider it as perfection. Jorney 1-60 was smooth and clean. I dont remember a single drop struggle. Here with empty locations i already see how people will stuck alltogether on some quests.  Higher respawn rate will help at some point but it will not fix bottelneck it will only make some quest even harder (caves, gnoll camps etc.)  Just something to think about.

**Comment by The14me** [comment]
Outland suppose to be fine (hope so ).

**Comment by Easyfraggy** [comment]
Your video is from 2015, all drop rates are severely buffed at this point. Only web archives thottbot and the like is useful for evidence of drop rates.

**Comment by aresbrutus** [comment]
Increased the drop rate a bit in rev Tycho.
