### ISSUE TITLE
[Quest][Item]Triage Bandage

### ISSUE THREAD

**Issue by DeltaLoads** [Atlantiss/NetherwingBugtracker#1490]
[//]: # (Enclose links to things related to the bug using http://wowhead.com or any other TBC database.)
[//]: # (You can use screenshot ingame to visual the issue.)
[//]: # (Write your tickets according to the format:)
[//]: # ([Quest][Azuremyst Isle] Red Snapper - Very Tasty!)
[//]: # ([NPC] Magistrix Erona)
[//]: # ([Spell][Mage] Fireball)
[//]: # ([Npc][Drop] Ghostclaw Lynx)
[//]: # ([Web] Armory doesnt work)

**Description**: 
Quest item Triage Bandage can be used even if you dont have any target selected
![wowscrnshot_101118_143801](https://user-images.githubusercontent.com/43690147/46804767-caa3f800-cd63-11e8-8eb1-d00bfc5c2736.jpg)

**Current behaviour**:
Triage Bandage can be used without target
**Expected behaviour**: 
Triage Bandage should be only usable on Injured, Badly Injured, and Critically Injured Soldiers
**Server Revision**: 
2153

**Comment by Evolvee** [comment]
https://github.com/Atlantiss/NetherwingBugtracker/issues/1533

**Comment by KevinTyrrell** [comment]
Adding to this issue, the bandage is not removed from your inventory after the quest finishes.
