### ISSUE TITLE
[Tanaris] Gadgetzan Water Survey

### ISSUE THREAD

**Issue by Azalen** [Atlantiss/NetherwingBugtracker#1491]
**Description**: 
https://www.wowhead.com/quest=992/gadgetzan-water-survey
https://vanillawowdb.com/?quest=992

**Current behaviour**:
After using Tapped Dowsing Widget (https://vanillawowdb.com/?item=8585) two mobs spawn like they should but they don't trigger combat. They only trigger combat while starting to move which makes it possible to mount up and run away.

**Expected behaviour**: 
They should trigger combat on spawn.
Proof: https://www.youtube.com/watch?v=ItM6pujjQPY

**Server Revision**: 
[2151]

**Comment by Evolvee** [comment]
rev sample_text
