### ISSUE TITLE
[Zul'Farrak] Pyramid Event

### ISSUE THREAD

**Issue by Azalen** [Atlantiss/NetherwingBugtracker#1492]
**Description**: 
http://wowwiki.wikia.com/wiki/Zul%27Farrak?oldid=1709150

**Current behaviour**:

- The neutral NPC's that should aid the party while the event is ongoing are standing still not helping the fight
- The attacking mobs have bad pathing and fly towards the party
- Upon completion of the event it is not possible to speak with the main NPC Sergeant Bly (npc=7604) and start the following event to fight against him and his crew
- it is also not possible to speak with Weegli Blastfuse (npc=7607) in order for him to blast open the gate to the next boss

Video: https://www.youtube.com/watch?v=NdpHX1qNk7E

**Server Revision**: 
[2151]

"Use dots. The Deputy likes dots.".

**Comment by Easyfraggy** [comment]
https://github.com/Atlantiss/AtlantissTBCBT/issues/2216

**Comment by Wolffenstein** [comment]
Fixed in rev 2170.
