### ISSUE TITLE
[Item] Container Items

### ISSUE THREAD

**Issue by soolos** [Atlantiss/NetherwingBugtracker#1494]
[//]: # (Enclose links to things related to the bug using http://wowhead.com or any other TBC database.)
[//]: # (You can use screenshot ingame to visual the issue.)
[//]: # (Write your tickets according to the format:)
[//]: # ([Quest][Azuremyst Isle] Red Snapper - Very Tasty!)
[//]: # ([NPC] Magistrix Erona)
[//]: # ([Spell][Mage] Fireball)
[//]: # ([Npc][Drop] Ghostclaw Lynx)
[//]: # ([Web] Armory doesnt work)

**Description**: 
If you try to open container items such as [Tightly Sealed Trunk](https://tbc-twinhead.twinstar.cz/?item=20708) or Clams while you are dead, the item will get buggy.
**Current behaviour**:
Rightclicking on such items while you are dead will result in an error message which is correct. But the item will grey out and you can not interact with it even after reviving. You will need to relog to use the item again.
**Expected behaviour**: 
You should just see the error message, the item should not grey out.
**Server Revision**: 
2153

**Comment by Wolffenstein** [comment]
Fixed in rev 2155.
