### ISSUE TITLE
[Westfall][NPC] Forlorn Spirit Text

### ISSUE THREAD

**Issue by Anonyxx** [Atlantiss/NetherwingBugtracker#1495]
**Description**: 

Mob does not say correct text. As part of the legend of stalvan quest.

**Current behaviour**:

"Who is the mere $r that meddles with..."

**Expected behaviour**: 

Replace $r with the class so it says (in my case):

"Who is the mere druid that meddles with.."

**Server Revision**: 
2151

**Comment by Evolvee** [comment]
https://github.com/Atlantiss/NetherwingBugtracker/issues/1447
