### ISSUE TITLE
[NPC][The Barrens] Cloned Ectoplasm

### ISSUE THREAD

**Issue by eryczek1615** [Atlantiss/NetherwingBugtracker#1498]
**Description**:  NPC summoned by Devouring Ectoplasm
[Cloned Ectoplasm](https://www.wowhead.com/npc=5780)
[Devouring Ectoplasm](https://www.wowhead.com/npc=3638)
[Spell Clone](https://www.wowhead.com/spell=7952)

**Current behaviour**:
After summon Cloned Ectoplasm doesn't attack us immediately (we have to move).

**Expected behaviour**: 
After summon Cloned Ectoplasm should attack us immediately

**Server Revision**: 
2153

**Comment by Wolffenstein** [comment]
Please test again in rev 2159.
