### ISSUE TITLE
[Feralas] Wandering Shay

### ISSUE THREAD

**Issue by Azalen** [Atlantiss/NetherwingBugtracker#1499]
**Description**: 
https://classicdb.ch/?quest=2845

Issue maybe related to all escort quests with an item to make the npc follow you again.

**Current behaviour**:
Quest works but you can run into an issue doing the following: After Shay wanders off (you have a bell to make her follow you again) and gets aggroed by a mob she will fight the mob and then freeze. This means if I use the item on her again (or any spell) she is on "Evade" mode. 

This does not happen if she aggroes a mob while she is still following the player - only if she just started wandering off.

![wowscrnshot_101118_183025](https://user-images.githubusercontent.com/20336567/46819792-e4096c00-cd84-11e8-9879-26162ff3a8cc.jpg)

**Expected behaviour**: 
She shouldn't be on "Evade" mode so the player can finish the quest.

**Server Revision**: 
[2151]

**Comment by Evolvee** [comment]
@Wolffenstein this requires you to fix as i told you like thousand times before beta: https://github.com/Atlantiss/AtlantissTBCBT/issues/4250

**Comment by Mewmewww** [comment]
Shay never ran away when I did the quest which made the quest really easy. There was no dialogue as well until the end with Rockbiter and her.

**Comment by Evolvee** [comment]
U had her probably in combat most of the time... it requires around 30-60 sec out of combat to trigger.

**Comment by Tenoutoften** [comment]
Related https://github.com/Atlantiss/NetherwingBugtracker/issues/783?

**Comment by Evolvee** [comment]
No

**Comment by Godmatik** [comment]
Rev 4014

Tested having Shay wander off and and aggro a mob (was not easy to do...), did not evade to the bell use after the mob was dead, guess it was fixed at some point.

The 'wander' she does is not blizzlike, she just walks a few yards in one direction and sits there, instead of actually wandering around. But w/e... it works
