### ISSUE TITLE
Hunter pets in water

### ISSUE THREAD

**Issue by mbzz88** [Atlantiss/NetherwingBugtracker#150]
Hunter pets do not move correctly in water, they either freeze in place until the player stops moving, then catch up, or if the player moves far enough away they teleport to the player.
Sending pet to attack mobs in water, either from shore or while swimming, works correctly.
https://youtu.be/tFMSXbUDV9k

**Comment by Arnamik12** [comment]
Same thing happens with Warlock pets.

**Comment by The14me** [comment]
Re-tested.Work just fine now.
