### ISSUE TITLE
[Item]Shattered necklace#7666 shouldn't drop for horde players

### ISSUE THREAD

**Issue by Tenoutoften** [Atlantiss/NetherwingBugtracker#1500]
**Description**: 
[[Item]Shattered necklace#7666](https://db.excalibur.ws/?item=7666#starts) shouldn't drop for horde players as it is an  alliance quest.

Got the item of [[NPC]Shadowforge Surveyor#4844](https://db.excalibur.ws/?npc=4844)
![f767babd9a34667221d261331a86b356](https://user-images.githubusercontent.com/34839199/46822802-b9231600-cd8c-11e8-8e56-4fa08c631e37.png)

**Expected behaviour**: 
Expected to not drop for horde.

**Server Revision**: 
2155

**Comment by Tenoutoften** [comment]
Part of [[Quest]Necklace Recovery#2283](https://db.excalibur.ws/?quest=2283)

**Comment by Easyfraggy** [comment]
???
