### ISSUE TITLE
[Core Mechanic][[Spell]Flash of Light#19941 something bizarre happening causing way to much healing / double healing

### ISSUE THREAD

**Issue by Tenoutoften** [Atlantiss/NetherwingBugtracker#1502]
**Description**: 
[[Spell]Flash of Light#19941](https://db.excalibur.ws/?spell=19941)
[Video here](https://www.youtube.com/watch?v=KordJ3cStx0&feature=youtu.be)

I start off at:
199 Health
+ 223 Flash of Light(R4) 
Should end up at:
422 Health
End up at:
801 health

Then it heals the regular amount once and I end up at~ 1.1k
+225 Flash of Light
Somehow puts me to 1.5k? 
You can see the healing prediction missing it completely, and the health is ticking twice rather than once

Another one [here](https://www.youtube.com/watch?v=xByCpw85BNc&feature=youtu.be)
I lack nearly 1000 hp. I heal for +220 + 221 and I am topped off.

**Expected behaviour**: 
Expected to heal the regular amount

**Server Revision**: 
2161

**Comment by Wolffenstein** [comment]
Fixed in rev 2163.
