### ISSUE TITLE
[CORE] Spammed with "You are facing the wrong way"

### ISSUE THREAD

**Issue by Edhner** [Atlantiss/NetherwingBugtracker#1503]
[//]: # (Enclose links to things related to the bug using http://wowhead.com or any other TBC database.)
[//]: # (You can use screenshot ingame to visual the issue.)
[//]: # (Write your tickets according to the format:)
[//]: # ([Quest][Azuremyst Isle] Red Snapper - Very Tasty!)
[//]: # ([NPC] Magistrix Erona)
[//]: # ([Spell][Mage] Fireball)
[//]: # ([Npc][Drop] Ghostclaw Lynx)
[//]: # ([Web] Armory doesnt work)

**Description**: 
Walking with my lvl5 hunter to bloodhoof village. When I get there I am spammed with the text in red "You are Facing the wrong way" non-stop. I then tried to entered combat and could not hit the wolf. I could add a hunters mark on the target, but for example raptor strike could not land and auto attack with the gun didn't work either. See attached screenshots for details.

**Current behaviour**:
![wowscrnshot_101118_203245](https://user-images.githubusercontent.com/20242103/46826498-68b0b600-cd96-11e8-8179-7f24924f8478.jpg)
![wowscrnshot_101118_202557](https://user-images.githubusercontent.com/20242103/46826499-68b0b600-cd96-11e8-8b1c-1e6474105e14.jpg)

**Expected behaviour**: 

**Server Revision**: Not sure. Happened 2018-10-11 20:40 CEST.

**Comment by Wolffenstein** [comment]
Must be some addon/client issue? Nobody else had anything similar as far as I know.

**Comment by Edhner** [comment]
The only addon I am using is carbonite but sure this is a possibility. I can try to remove it and see if I can reproduce the issue without it.

**Comment by Manaci** [comment]
Fixed
