### ISSUE TITLE
Heavy Silk Bandage

### ISSUE THREAD

**Issue by maxturtlesc2** [Atlantiss/NetherwingBugtracker#1504]
[//]: # (Enclose links to things related to the bug using http://wowhead.com or any other TBC database.)
[//]: # (You can use screenshot ingame to visual the issue.)
[//]: # (Write your tickets according to the format:)
[//]: # ([Quest][Azuremyst Isle] Red Snapper - Very Tasty!)
[//]: # ([NPC] Magistrix Erona)
[//]: # ([Spell][Mage] Fireball)
[//]: # ([Npc][Drop] Ghostclaw Lynx)
[//]: # ([Web] Armory doesnt work)

**Description**: 
Heavy Silk Bandage heals for 1000+. It is supposed to heal for 640. I think every tick counts twice, making the heal way too powerful.
**Current behaviour**:
Heavy Silk Bandage heals too much.
**Expected behaviour**: 
Heavy Silk Bandage should heal for 640.
**Server Revision**:

**Comment by Wolffenstein** [comment]
It should be fixed now.

**Comment by maxturtlesc2** [comment]
Seems like it. Thanks!

**Comment by Neophrone** [comment]
Strange, it was working fine few days ago.

**Comment by tcberk12** [comment]
@Neophrone It was broken by Rev 2156 released earlier today, now fixed again.
