### ISSUE TITLE
[Wailing Caverns]NPC/Pets pathfinding

### ISSUE THREAD

**Issue by DeltaLoads** [Atlantiss/NetherwingBugtracker#1505]
[//]: # (Enclose links to things related to the bug using http://wowhead.com or any other TBC database.)
[//]: # (You can use screenshot ingame to visual the issue.)
[//]: # (Write your tickets according to the format:)
[//]: # ([Quest][Azuremyst Isle] Red Snapper - Very Tasty!)
[//]: # ([NPC] Magistrix Erona)
[//]: # ([Spell][Mage] Fireball)
[//]: # ([Npc][Drop] Ghostclaw Lynx)
[//]: # ([Web] Armory doesnt work)

**Description**: 
Dungeons has alot of pathfinding problems with pets/npc that cause pet to stand still or npcs getting stuck/evade
example of few places:
https://streamable.com/j2p40
**Current behaviour**:
Pets/npcs getting stuck/evade
**Expected behaviour**: 
Pets/npcs shouldn't get stuck
**Server Revision**: 
2163

**Comment by Wolffenstein** [comment]
Fixed in rev 2165.
