### ISSUE TITLE
[Quest][Eastern Plaguelands] Poisoned Water

### ISSUE THREAD

**Issue by Firroth** [Atlantiss/NetherwingBugtracker#1506]
[Quest][Eastern Plaguelands] [Poisoned Water](https://www.wowhead.com/quest=6804/poisoned-water)
[NPC] Plague Ravager ID [8520]
[NPC] Blighted Surge ID [8519]
[NPC] Discordant Surge ID [13279]
[Item] Aspect of Neptulon ID [17310]
[Item] Discordant Bracers ID [17309]
[Spell] Aspect of Neptulon ID [21332]

**Current behaviour**:
When you try to use [Item] Aspect of Neptulon ID [17310] on [NPC] Blighted Surge ID [8519] or [NPC] Plague Ravager ID [8520], you get message "Invalid target".

**Expected behaviour**: 
When you use [Item] Aspect of Neptulon ID [17310] it should cast [Spell] Aspect of Neptulon ID [21332] on [NPC] Blighted Surge ID [8519] or [NPC] Plague Ravager ID [8520], when hit by this spell from this item they should change into [NPC] Discordant Surge ID [13279] which should be dropping [Item] Discordant Bracers ID [17309].

**Server Revision**: 
2163

**Comment by Evolvee** [comment]
fixed in rev 439kcolb
