### ISSUE TITLE
Pet / mob pathing in caves

### ISSUE THREAD

**Issue by Ahmpy** [Atlantiss/NetherwingBugtracker#1508]
[//]: # (Enclose links to things related to the bug using http://wowhead.com or any other TBC database.)
[//]: # (You can use screenshot ingame to visual the issue.)
[//]: # (Write your tickets according to the format:)
[//]: # ([Quest][Azuremyst Isle] Red Snapper - Very Tasty!)
[//]: # ([NPC] Magistrix Erona)
[//]: # ([Spell][Mage] Fireball)
[//]: # ([Npc][Drop] Ghostclaw Lynx)
[//]: # ([Web] Armory doesnt work)

**Description**: 
Pets occasionally clip through cave surfaces when on follow and the player jumps.
**Current behaviour**:
Pets sometimes fly through the roof of caves when the player jumps, most of the time the pet will return on its own; however, occasionally the player will have to return to the spot to 'retrieve' the pet. If there is terrain above the cave it will appear on the surface.

note: This ONLY happens when the player jumps, if you never jump in a cave pathing seems fine.

Examples of current behavior: 
Winterspring - https://youtu.be/lHd1wohGieA
Blackrock Mountain - https://youtu.be/zWH1Hm01N1U

**Expected behaviour**: 
Pets should follow the player as they do outside of caves.

**Server Revision**: 
2165

**Comment by Tenoutoften** [comment]
This is not limited to pets, I buged out regular mobs in the same fashion. Video [here](https://www.youtube.com/watch?v=Wq9-zmX6A_g&feature=youtu.be)

**Comment by Wolffenstein** [comment]
Fixed in rev 2167.
