### ISSUE TITLE
[Respawn] Sometimes mobs respawn in large groups

### ISSUE THREAD

**Issue by Jezofine** [Atlantiss/NetherwingBugtracker#151]
When killing Razormane Quillboars and Scouts at 50 49.5 in Durotar slowly one by one they respawn 3-4 at once instead of single one.
It happened couple of times 2-3 hours after server launch, when zone was pretty overpopulated, but I don't have any proof and cannot reproduce it now alone. 
Also didn't check on other mobs and don't know if it's related to certain cluster or to dynamic respawn in general.

**Comment by Dpthx** [comment]
The dynamic respawn works like that. There is a pool of x mobs, and a % that have to be alive at any given time. So if people were killing razormane Quillboars and they were massively depopulated, if the % is set to 25%, whenever you go below that number they will start popping up randomly, but in their spawn points.

**Comment by Jezofine** [comment]
Well I asked if it's by design and was recommended to report it anyways.

**Comment by wtRCH** [comment]
Invalid due to dynamic respawn system and how it works.
