### ISSUE TITLE
[NPC]Voidwalker Minion#8996 should grant experience gain.

### ISSUE THREAD

**Issue by Tenoutoften** [Atlantiss/NetherwingBugtracker#1512]
**Description**: 
[[NPC]Wastwander Shadow Mage#5617](https://db.excalibur.ws/?npc=5617#abilities)'s [[NPC]Voidwalker Minion#8996](https://db.excalibur.ws/?npc=8996) summoned by [[Spell]Summon Voidwalker#12746](https://db.excalibur.ws/?spell=12746) should grant experience as seen [here](https://youtu.be/x9M61jaHFVM?t=547)

It has been bugging me a bit how I haven't met a single pet from an NPC giving experience...
This spell is used by a lot of other NPCs, and it is a very strong indication that other NPC warlock's pet should potentially give experience.

Also see https://github.com/Atlantiss/NetherwingBugtracker/issues/1747
**Current behaviour**:
Doesn't.

**Expected behaviour**: 
Should grant xp.

**Server Revision**: 
2165

**Comment by Evolvee** [comment]
https://github.com/Atlantiss/NetherwingBugtracker/issues/1945
