### ISSUE TITLE
[NPC]Wastwander Shadow Mage#5617 should be able to spawn in Noonshade Ruins in Tanaris

### ISSUE THREAD

**Issue by Tenoutoften** [Atlantiss/NetherwingBugtracker#1513]
**Description**: 
This video shows a [[NPC]Wastwander Shadow Mage#5617](https://db.excalibur.ws/?npc=5617#abilities) being killed in the Noonshade Ruins in Tanaris, I didn't see any [[NPC]Wastwander Shadow Mage#5617](https://db.excalibur.ws/?npc=5617#abilities) there myself. And after clearing the entire camp, none respawned.

Looks like they should be able to spawn there as well:
[video here](https://youtu.be/x9M61jaHFVM?t=547)

Rough .gps
![caed2fcd5e98bbf16506e1567b6ba3c9](https://user-images.githubusercontent.com/34839199/46853624-f1633c80-cdfe-11e8-801c-ee40ef69da6c.png)

**Current behaviour**:
Doesn't spawn in NoonShade Ruins in Tanaris
**Expected behaviour**: 

**Server Revision**: 
2165

**Comment by aresbrutus** [comment]
Confirmed: https://i.imgur.com/dswzVh5.jpg

**Comment by Evolvee** [comment]
![image](https://user-images.githubusercontent.com/1942409/80840950-b69e4080-8bfe-11ea-9745-38c5a92547f9.png)

classic wowhead
