### ISSUE TITLE
[NPC]Southsea Pirate#7855 should attempt to run away in fear

### ISSUE THREAD

**Issue by Tenoutoften** [Atlantiss/NetherwingBugtracker#1514]
**Description**: 
[[NPC]Southsea Pirate#7855](https://db.excalibur.ws/?npc=7855) should attempt to run away in fear!

Can be seen [here](https://youtu.be/x9M61jaHFVM?t=1454)

**Expected behaviour**: 
Expeceted to run away in fear! on occasion

**Server Revision**: 
2165

**Comment by Evolvee** [comment]
rev 439kcolb
