### ISSUE TITLE
[NPC]Southsea Dock Worker#7857 should attempt to run away in fear.

### ISSUE THREAD

**Issue by Tenoutoften** [Atlantiss/NetherwingBugtracker#1515]
**Description**: 
[[NPC]Southsea Dock Worker#7857](https://www.wowhead.com/npc=7857/southsea-dock-worker#comments) should attempt to run away in fear.
Can be seen [here](https://youtu.be/x9M61jaHFVM?t=2796)

**Current behaviour**:
Doesn't.

**Expected behaviour**: 
Expected to attempt to run away in fear.
**Server Revision**: 
2165

**Comment by Evolvee** [comment]
rev 439kcolb
