### ISSUE TITLE
[NPC]Andre Firebeard#7883 should attempt to run away in fear

### ISSUE THREAD

**Issue by Tenoutoften** [Atlantiss/NetherwingBugtracker#1516]
**Description**: 
[[NPC]Andre Firebeard#7883](https://db.excalibur.ws/?npc=7883) should attempt to run away in fear!
Seen [here](https://youtu.be/x9M61jaHFVM?t=2595)

**Current behaviour**:
Seemingly doesn't, have killed him 4 times.

**Expected behaviour**: 
Expected to attempt to run away in fear!

**Server Revision**: 
2165

**Comment by Evolvee** [comment]
rev 439kcolb
