### ISSUE TITLE
[NPC]Wastewalker Rogue#5615 should attempt to run away in fear

### ISSUE THREAD

**Issue by Tenoutoften** [Atlantiss/NetherwingBugtracker#1517]
**Description**: 
[[NPC]Wastewalker Rogue#5615](https://db.excalibur.ws/?npc=5615) should attempt to run away in fear!
Can be seen [here](https://youtu.be/x9M61jaHFVM?t=5279)
**Current behaviour**:

**Expected behaviour**: 
Expected to attempt to run away in fear
**Server Revision**: 
2165

**Comment by Evolvee** [comment]
rev 439kcolb
