### ISSUE TITLE
[Core] Mob Leashing - resets near home position, if not attacked for a couple of seconds

### ISSUE THREAD

**Issue by Firroth** [Atlantiss/NetherwingBugtracker#1519]
**Current behaviour**:
https://gfycat.com/pl/MaleBitterErne
https://gfycat.com/pl/NiftyShortBrownbutterfly

**Expected behaviour**: 
They shouldn't reset when npc is at least 30-40y near his home position, and it shouldn't matter npc isn't attacked for a couple of seconds if it's still in range of his home position.

**Server Revision**: 
2165

**Comment by Wolffenstein** [comment]
Please retest in rev 2169 and reopen if needed.

**Comment by Firroth** [comment]
Problem still occurs on 2169.

- from what I gathered it occurs only on "ranged mobs", if they shoot/cast on you and you ignore them for 9s+ then run to them to hit them, they "reset" and go out of combat.

Or just LoS them.

![2018-10-13_12-13-49](https://user-images.githubusercontent.com/43505196/46904390-a0794400-cee3-11e8-956c-7577327cd99f.gif)

- when mobs flee and you don't don't run after them they will reset after "fleeing" +1/2s ends.

![2018-10-13_12-24-07](https://user-images.githubusercontent.com/43505196/46904395-a96a1580-cee3-11e8-99be-8247a498c8ce.gif)

**Comment by Easyfraggy** [comment]
Maybe leash timer should be paused when a mob is casting?

**Comment by Retinus** [comment]
same issue? [#1009](https://github.com/Atlantiss/NetherwingBugtracker/issues/1009)

**Comment by Easyfraggy** [comment]
They should reset even though they get solid hits - The mechanic is that if they stand still for 1s while being able to attack the player the reset timer resets. Seems to not work when mobs are casting. 

And y you are right they shouldn't reset within their home position.

**Comment by Drayo** [comment]
It's super simple actually.

**There should not even be a leash timer, at least on retail it did not exist.**

Every mob has a leash range, each time a mob is hit by a melee attack or an active spell cast, his leash range moves to his current position. Imagine it like a flagpole and a circle around it if you want to.

As long as the **creature** itself does not leave it's leash area, or it's target is unreachable, it should **NEVER** reset!

**Comment by Dekirayne** [comment]
I can attest to that, leash mechanics definitely don't work well for now (are not blizzlike) and I really hope they will be fixed because this is a huge no no for me.

**Comment by Easyfraggy** [comment]
https://github.com/Atlantiss/NetherwingBugtracker/issues/1799

**Comment by Drayo** [comment]
Seems to work well now, I can no longer get mobs to reset at weird times so this could be considered fixed, yay!

The leashing range seems to be a tad too low, ~10y more might feel better but this is purely subjective and might be wrong. Need to ask many more players to specifically test this, maybe with a small tag on discord, idk.

Definitely good work.

**Comment by Dekirayne** [comment]
Yes, it feels better, but the range definitely feels too low and needs increasing. And from all the clips I know from vanilla and tbc the range is much bigger then right now on NW.

**Comment by Easyfraggy** [comment]
Leashing does feel alright to me, adding 5-10 yards would maybe be more realistic? Remember that leashing is also tied to level difference, so if you pull a low lvl mob it will reset faster.

**Comment by ttghnw** [comment]
#183

**Comment by Easyfraggy** [comment]
Please reopen if this is still an issue - should be fixed.
