### ISSUE TITLE
[NPC]Homing Robot OOX-17/TN#7784 doesn't aggro anything [Quest]Rescue 00X-17/TN!#648

### ISSUE THREAD

**Issue by Tenoutoften** [Atlantiss/NetherwingBugtracker#1520]
**Description**: 
[[NPC]Homing Robot OOX-17/TN#7784](https://db.excalibur.ws/?npc=7784) wont agro any mobs it passes by or the mobs spawned during [[Quest]Rescue 00X-17/TN!#648](https://db.excalibur.ws/?quest=648). I suspect it has tagged with wrong faction.

Full video of the quest on Netherwing [here](https://www.youtube.com/watch?v=D3QRwGcV8S0&feature=youtu.be)

**Expected behaviour**: 
Expected to help players with mobs, and agro mobs it passes by, and fight the mob spawned during [[Quest]Rescue 00X-17/TN!#648](https://db.excalibur.ws/?quest=648) 

**Server Revision**: 
2165

**Comment by Firroth** [comment]
#1114

**Comment by kkumbaya** [comment]
look for already existing issues before making a new one. This has been reported weeks ago

**Comment by Tenoutoften** [comment]
I searched for two different names for this and it didn't show up, not sure why...
