### ISSUE TITLE
[Pets][Pathfinding]Pets disappearing

### ISSUE THREAD

**Issue by DeltaLoads** [Atlantiss/NetherwingBugtracker#1523]
[//]: # (Enclose links to things related to the bug using http://wowhead.com or any other TBC database.)
[//]: # (You can use screenshot ingame to visual the issue.)
[//]: # (Write your tickets according to the format:)
[//]: # ([Quest][Azuremyst Isle] Red Snapper - Very Tasty!)
[//]: # ([NPC] Magistrix Erona)
[//]: # ([Spell][Mage] Fireball)
[//]: # ([Npc][Drop] Ghostclaw Lynx)
[//]: # ([Web] Armory doesnt work)

**Description**: 
Pets are pulling full on Houdini acts in dungeons and some caves since last update
https://streamable.com/kmxts
**Current behaviour**:
Pets disappear under map in dungeons and some caves
**Expected behaviour**: 
Pets shouldn't disapear
**Server Revision**: 
2165

**Comment by Tenoutoften** [comment]
https://github.com/Atlantiss/NetherwingBugtracker/issues/1508

**Comment by Wolffenstein** [comment]
Fixed in rev 2167.
