### ISSUE TITLE
 [NPC][Zul'Farak] Sandfury Soul Eater [Spell] 11016

### ISSUE THREAD

**Issue by Firroth** [Atlantiss/NetherwingBugtracker#1526]
[NPC] [Sandfury Soul Eater](https://www.wowhead.com/npc=7246/sandfury-shadowhunter) ID [7246]
[Spell] Soul Bite ID [11016]

**Current behaviour**:
[NPC] [Sandfury Soul Eater](https://www.wowhead.com/npc=7246/sandfury-shadowhunter#comments) ID [7246] doesn't seem to be using [Spell] Soul Bite ID [11016] to regain part of it's health and leach mana from their target. 
(maybe because I don't have mana pool, but it shouldn't matter since he should hp leech then)

**Expected behaviour**: 
[NPC] [Sandfury Soul Eater](https://www.wowhead.com/npc=7246/sandfury-shadowhunter) ID [7246] should be using [Spell] Soul Bite ID [11016] to regain part of it's health and leach mana from their target. (even if their target is a player without mana pool, he should use it for hp leeching). 

**Server Revision**: 
2165

**Comment by Evolvee** [comment]
The spell can be currently casted only on targets with mana. Its not a script error. Its how the spell behaves.

So looking for more info if this is how it should be or not, otherwise a core fix would be needed.

**Comment by Wolffenstein** [comment]
Fixed in rev 3400.
