### ISSUE TITLE
[Spell][Blood Elf][Arcane Torrent] Silence on last part of the cast

### ISSUE THREAD

**Issue by Argonn** [Atlantiss/NetherwingBugtracker#1527]
[//]: # (Enclose links to things related to the bug using http://wowhead.com or any other TBC database.)
[//]: # (You can use screenshot ingame to visual the issue.)
[//]: # (Write your tickets according to the format:)
[//]: # ([Quest][Azuremyst Isle] Red Snapper - Very Tasty!)
[//]: # ([NPC] Magistrix Erona)
[//]: # ([Spell][Mage] Fireball)
[//]: # ([Npc][Drop] Ghostclaw Lynx)
[//]: # ([Web] Armory doesnt work)

**Description**: 
I used Arcane torrent on the mana wyrm casting Faerie Fire [#25602] right after the casting bar reached 50%. For some reason (spell batching?) the casting still came trough. Sometimes it works, sometimes it fails (sequence in the batch?)

![image](https://user-images.githubusercontent.com/2676201/46867823-8fb6c880-ce26-11e8-9d4b-6e2b16269e6e.png)

**Current behaviour**:
You cannot interrupt a spell casting on the last moment it seems.

**Expected behaviour**: 
You should be able to successfully interrupt any casting still in progress.

**Server Revision**: 
2165 (patch 203)

**Comment by wtRCH** [comment]
It's due to spell delay.
