### ISSUE TITLE
[NPC][Zul'Farak] Sandfury Shadowhunter [Spell] 18395 and [Spell] 11641

### ISSUE THREAD

**Issue by Firroth** [Atlantiss/NetherwingBugtracker#1528]
[NPC] [Sandfury Shadowhunter ](https://web.archive.org/web/20090806042452/http://wow.allakhazam.com:80/db/mob.html?wmob=7246) ID [7246]
[Spell] Dismounting Blast ID [18395]
[Spell] Hex ID [11641]

**Current behaviour**:

- [NPC] [Sandfury Shadowhunter ](https://web.archive.org/web/20090806042452/http://wow.allakhazam.com:80/db/mob.html?wmob=7246) ID [7246] doesn't seem to use [Spell] Dismounting Blast ID [18395], when player is mounted to dismount him.

- [NPC] [Sandfury Shadowhunter ](https://web.archive.org/web/20090806042452/http://wow.allakhazam.com:80/db/mob.html?wmob=7246)  doesn't seem to use [Spell] Hex ID [11641] if there is only "one" target. (no idea if he uses it, if there is more target's currently).

**Expected behaviour**: 

- [NPC] [Sandfury Shadowhunter ](https://web.archive.org/web/20090806042452/http://wow.allakhazam.com:80/db/mob.html?wmob=7246) should be using [Spell] Dismounting Blast ID [18395] only when any of the players is mounted, to prevent them from running/kiting.

- [NPC] [Sandfury Shadowhunter ](https://web.archive.org/web/20090806042452/http://wow.allakhazam.com:80/db/mob.html?wmob=7246) should be using [Spell] Hex ID [11641] even if there is only "one" target. (if there is more than "one" then he should cast it on his current target, and switch aggro to other "target").

![screenshot_1](https://user-images.githubusercontent.com/43505196/46868175-c80ad680-ce27-11e8-8f51-6032ffa2a605.png)

**Server Revision**: 
2165

**Comment by Evolvee** [comment]
Where did you get the dismount from?

The rest fixed in rev 439kcolb

**Comment by Firroth** [comment]
@Evolvee 
https://web.archive.org/web/20090806042452/http://wow.allakhazam.com:80/db/mob.html?wmob=7246

**Comment by Evolvee** [comment]
rev yummy
