### ISSUE TITLE
[NPC]Hazzali Parasite#7769 spawned by [Spell]Summon Hazzali Parasites are very slow at activating

### ISSUE THREAD

**Issue by Tenoutoften** [Atlantiss/NetherwingBugtracker#1529]
**Description**: 
[[NPC]Hazzali Parasite#7769](https://db.excalibur.ws/?npc=7769) summoned by [[Spell]Summon Hazzali Parasites](https://db.excalibur.ws/?spell=11023) used by:

* [[NPC]Hazzali Stinger](https://db.excalibur.ws/?npc=5450)
* [[NPC]Hazzali Swarmer](https://db.excalibur.ws/?npc=5451)
* [[NPC]Hazzali Worker](https://db.excalibur.ws/?npc=5452)
* [[NPC]Hazzali Tunneler](https://db.excalibur.ws/?npc=5453)
* [[NPC]Hazzali Sandreaver](https://db.excalibur.ws/?npc=5454)

Is very slow at activating video [here](https://www.youtube.com/watch?v=akLyhtMmL8k&feature=youtu.be)

**Expected behaviour**: 
Expected to agro immediately 

**Server Revision**: 
2165

**Comment by Evolvee** [comment]
@Wolffenstein 
![image](https://user-images.githubusercontent.com/1942409/46869420-0acead80-ce2c-11e8-8a55-44ff5f0e8b28.png)

FeelsWeirdMan

**Comment by AxeCell** [comment]
Still the case as of revision 2605. They'll also remain alive for longer than their supposed duration and target the player. They can't however be attacked and they don't cause aggro.
