### ISSUE TITLE
[Quest][Azuremyst Isle] The Kessel Run - Missing Gossip's

### ISSUE THREAD

**Issue by Firroth** [Atlantiss/NetherwingBugtracker#153]
[Quest][Azuremyst Isle] The Kessel Run - Missing Gossip's
https://www.wowhead.com/quest=9663/the-kessel-run

**Current behaviour**:
There are no gossips, all you need to do is run and talk to npc (just click on him) and you get credit.

**Expected behaviour**: 
From what I found out there should be a gossip with "Give Warning" message on it, and when you click on it you get credit required to complete this quest.

These 3 npc's should have it.
https://www.wowhead.com/npc=17440/high-chief-stillpine
https://www.wowhead.com/npc=17116/exarch-menelaous
https://www.wowhead.com/npc=17240/admiral-odesyus

Source: https://www.youtube.com/watch?v=67OHodIeoV0

**Server Revision**: 
2028

**Comment by Peglaa** [comment]
Invalid report. Quest is blizzlike, tested it myself. Close this.
