### ISSUE TITLE
[NPC]Tooga#5955 can have mobs agroed onto him without responding

### ISSUE THREAD

**Issue by Tenoutoften** [Atlantiss/NetherwingBugtracker#1530]
**Description**: 
During [[Quest]Tooga's Quest#1560](https://db.excalibur.ws/?quest=1560) [[NPC]Tooga#5955](https://db.excalibur.ws/?npc=5955) can agro mobs without responding.

Video [here](https://www.youtube.com/watch?v=3rmerRbSmME&feature=youtu.be)

I am not 100% on this, perhaps it is possible that a mob can agro onto escort NPC without escort NPC agroing back in the case that the escort NPC is lower level than the hostile mob so that their agro ranges are different.

**Expected behaviour**: 
Expect [[NPC]Tooga#5955](https://db.excalibur.ws/?npc=5955) to respond immediately when something agros onto him.

**Server Revision**: 
2165

**Comment by Evolvee** [comment]
its probably in defensive react state = not attacking unless being attacked first

**Comment by Tenoutoften** [comment]
Considering a high population on launch its definitely better to leave the escort NPCs in a defense react state, so that it only reacts when the quest taker gets hit / when it get hit. Otherwise what will happen is people will constantly pull their mobs into your escort for "free xp"

**Comment by Tenoutoften** [comment]
The chicken is clearly in defensive mode [here](https://youtu.be/egTuW63-FVg?t=38)
Looks like Tooga is also in defensive mode [here](https://youtu.be/egTuW63-FVg?t=157)
This footage is from wrath: Published on Jun 15, 2010
