### ISSUE TITLE
3 x [NPC]Gadgetzan Bruiser#9460 in Gadgetzan 2x missing at alliance flight path, 1 x missing at horde

### ISSUE THREAD

**Issue by Tenoutoften** [Atlantiss/NetherwingBugtracker#1531]
**Description**: 
[[NPC]Gadgetzan Bruiser#9460](https://db.excalibur.ws/?npc=9460) is missing by the alliance flight path master, [[NPC]Bera Stonehammer#7823](https://www.wowhead.com/npc=7823) in Tanaris
https://youtu.be/KO1iKRoKDyI?t=4541

Looks like it should stand about here:
![18bec18cb85a1c3144cda63dd0206a86](https://user-images.githubusercontent.com/34839199/46871884-ddd1c900-ce32-11e8-8d58-b888724fb53a.png)

Second one missing at the other side, can be seen [here](https://www.youtube.com/watch?v=KO1iKRoKDyI&t=1343s)
![a71697323a81127a257bedad6030bd25](https://user-images.githubusercontent.com/34839199/46872217-d3fc9580-ce33-11e8-9feb-34f6a4334543.png)

Third can be seen [here](https://youtu.be/x9M61jaHFVM?t=7032) by the horde flight path. 

**Current behaviour**:
No guards at both horde and alliance flight path location

**Expected behaviour**: 
Expected to be two guards at alliance flight path, one at horde

**Server Revision**: 
2165

**Comment by Evolvee** [comment]
rev 439kcolb

**Comment by Evolvee** [comment]
Could you screenshot where they should be in these videos pls?

You used .gps while u had one NPC in a target probably so it gives its position and not your desired one, also one of the vids shows nothing, or im blind idk.. ^^

**Comment by Tenoutoften** [comment]
Aha Ill do that sec

**Comment by Tenoutoften** [comment]
![79535-bera-stonehammer](https://user-images.githubusercontent.com/34839199/46873886-0ad4aa80-ce38-11e8-8c85-9ca8688270e0.jpg)
that hand on the right, is a guard that should be here
![68c9da6111626a16b16bcd15bc298fca](https://user-images.githubusercontent.com/34839199/46873926-322b7780-ce38-11e8-992b-aa9c45222109.jpg)

**Comment by Tenoutoften** [comment]
Here is the third guard https://youtu.be/KO1iKRoKDyI?t=8396
![3rd](https://user-images.githubusercontent.com/34839199/46874184-d3b2c900-ce38-11e8-84b0-6df3a9c141dc.jpg)


and now I see a 4th

**Comment by Tenoutoften** [comment]
fourth guard here: https://youtu.be/KO1iKRoKDyI?t=8391
![4th](https://user-images.githubusercontent.com/34839199/46874257-08268500-ce39-11e8-83c7-f0be7a791b34.jpg)

**Comment by Evolvee** [comment]
ok
