### ISSUE TITLE
[NPC]Bera Stonehammer#7823, Alliance Tanaris gryphon master slightly wrong position

### ISSUE THREAD

**Issue by Tenoutoften** [Atlantiss/NetherwingBugtracker#1532]
**Description**: 
[[NPC]Bera Stonehammer#7823](https://db.excalibur.ws/?npc=7823) looks to have the wrong position in Tanaris.

Current position:
![fad360e343c4479d2d194d05c3d76d80](https://user-images.githubusercontent.com/34839199/46872412-4b322980-ce34-11e8-8dd7-7540e2dddcd8.png)
![41e1949fb878ad28dee5aebf17428dbf](https://user-images.githubusercontent.com/34839199/46872038-5e90c500-ce33-11e8-8386-79d1e18bbc39.png)

Judging by the oldest picture on [wowhead from 2008/04/21](https://www.wowhead.com/npc=7823/bera-stonehammer#screenshots:id=611106) and [this video] of vanilla guide. her position should probably be about 
![cc099ecc7dc867962b1a47cef9fb77d5](https://user-images.githubusercontent.com/34839199/46872368-2f2e8800-ce34-11e8-8277-56f801ab5081.png)

this would be consistent with the mountains you can see in the background of the picture

**Expected behaviour**: 
Expected to stand roughly at .gps provided, with two mountains showing in the background of her.

**Server Revision**: 
2165

**Comment by Evolvee** [comment]
rev 439kcolb
