### ISSUE TITLE
Bulkrek Ragefist#7824, horde Wind Rider Master in Tanaris slightly wrong position

### ISSUE THREAD

**Issue by Tenoutoften** [Atlantiss/NetherwingBugtracker#1534]
**Description**: 
[[NPC]BUlkrek Ragefist#7824](https://db.excalibur.ws/?npc=7824)
His position on retail can be seen [here](https://youtu.be/x9M61jaHFVM?t=7032)

**Current behaviour**:
Stand in front of the pillars of horde mounts.
![where he is](https://user-images.githubusercontent.com/34839199/46872918-b8928a00-ce35-11e8-8aff-33a928fd316b.png)

**Expected behaviour**: 
Should stand on the carpet
![should be](https://user-images.githubusercontent.com/34839199/46872931-bdefd480-ce35-11e8-9197-a633282f3da8.png)

**Server Revision**: 
2165

**Comment by Evolvee** [comment]
rev 439kcolb
