### ISSUE TITLE
3 * [NPC]Gadgetzan Sniper#21448 terribly underleveled, 28 should be 67

### ISSUE THREAD

**Issue by Tenoutoften** [Atlantiss/NetherwingBugtracker#1535]
**Description**: 
There are three [[NPC]Gadgetzan Sniper#21448](https://www.wowhead.com/npc=21448/gadgetzan-sniper#comments) on the roofs in Gadgetzan, but they are all currently just level 28 but they should probably be 67 like the other guards

![sniper](https://user-images.githubusercontent.com/34839199/46874795-47090a80-ce3a-11e8-8c6e-ef61e31ab6ca.png)
![4eb22656ebd166ce44674bca61172161](https://user-images.githubusercontent.com/34839199/46874837-6b64e700-ce3a-11e8-9c26-17e22c85018f.png)
![2entry](https://user-images.githubusercontent.com/34839199/46874948-b54dcd00-ce3a-11e8-89b0-3de4db0e4744.png)
![3entry](https://user-images.githubusercontent.com/34839199/46874949-b54dcd00-ce3a-11e8-84fd-cfc920ba33bb.png)

**Expected behaviour**: 
Expected to be level 67 like the other guards

**Server Revision**: 
2165

**Comment by Evolvee** [comment]
rev 439kcolb
