### ISSUE TITLE
[NPC][Silithus] Dust Stormer - Reputation

### ISSUE THREAD

**Issue by Firroth** [Atlantiss/NetherwingBugtracker#1538]
[NPC] [Dust Stormer](https://www.wowhead.com/npc=11744/dust-stormer)

**Current behaviour**:
Currently each kill gives 25 reputation for Hydraxian Waterlords, as non-human race.

![screenshot_1](https://user-images.githubusercontent.com/43505196/46881709-a07a3500-ce4c-11e8-8144-19d816e44a58.png)

**Expected behaviour**: 
Each kill should give 5 reputation as non-human. (only to friendly).

**Server Revision**: 
2165

**Comment by Evolvee** [comment]
rev Block
