### ISSUE TITLE
[World Event] Elemental Invasion

### ISSUE THREAD

**Issue by Firroth** [Atlantiss/NetherwingBugtracker#1539]
**Description**: 
World Event

**Current behaviour**:
Appears every 5-10min in Silithus. I killed "The Windreaver" and after 5-10min he appeared again with zone message of him appearing. 

**Expected behaviour**: 
Elemental Invasion world event should be appearing randomly every couple days, not every 10min in 1 zone (Silithus). There are 4 Elementals, each in other zone, meaning when event is to occur it is randomly rolling which one will appear.

http://wowwiki.wikia.com/wiki/Elemental_Invasions

**Server Revision**: 
2165

**Comment by wtRCH** [comment]
https://github.com/Atlantiss/AtlantissTBCBT/issues/2306

**Comment by Evolvee** [comment]
rev Block
