### ISSUE TITLE
Ghostclaw no drops

### ISSUE THREAD

**Issue by Tinnoan** [Atlantiss/NetherwingBugtracker#154]
Ghostclaw Lynx in ghostlands appear to drop nothing at all when killed, so far from what I can see on different tbc dbs this should not be the case.

[link](http://db.hellfire-tbc.com/?npc=16348) for loot table, from what I've seen most dbs appear to have mostly the same loot table

**Comment by xmesaj2** [comment]
fixed in rev 2035
