### ISSUE TITLE
[NPC][Un'goro Crater] Blazing Invader

### ISSUE THREAD

**Issue by Firroth** [Atlantiss/NetherwingBugtracker#1540]
[NPC] [Blazing Invader](http://wowwiki.wikia.com/wiki/Blazing_Invader)

**Description**: 
They are part of World Event - Elemental Invasions.

**Current behaviour**:
They are spawned like normal mobs in Un'goro Crater in Fire Plume Ridge, even if their "boss" [NPC] [Baron Charr](http://wowwiki.wikia.com/wiki/Baron_Charr) is not spawned.

![screenshot_1](https://user-images.githubusercontent.com/43505196/46883145-59427300-ce51-11e8-8060-941fd7426bb0.png)

**Expected behaviour**: 

**They shouldn't be spawned.** - they should be removed.

They should be spawned ONLY when Event Elemental Invasions started in Un'goro Crater and their boss [NPC] [Baron Charr](http://wowwiki.wikia.com/wiki/Baron_Charr) has appeared. If their boss dies, all of them should "despawn".

**Server Revision**: 
2165

**Comment by wtRCH** [comment]
https://github.com/Atlantiss/AtlantissTBCBT/issues/2306

**Comment by Evolvee** [comment]
rev Block
