### ISSUE TITLE
[NPC][Maraudon] Creeping Sludge - [Spell] Poison Shock Aura [22638]

### ISSUE THREAD

**Issue by Firroth** [Atlantiss/NetherwingBugtracker#1541]
[NPC] [Creeping Sludge](https://www.wowhead.com/npc=12222/creeping-sludge#screenshots)
[Spell] Poison Shock [22638]

**Current behaviour**:
- They don't use [Spell] Poison Shock [22638] **Out of Combat** for visual effect.
- Also they seem to be using [Spell] "Acid Spray" no idea what ID.

**Expected behaviour**: 

- **They should have aura** [Spell] Poison Shock [22638] for visual effect, so they would look like:

![55230-creeping-sludge-a-group-of-creeping-sludges](https://user-images.githubusercontent.com/43505196/46890421-17bcc280-ce67-11e8-9aa8-2da6bcbc637a.jpg)

![screenshot_1](https://user-images.githubusercontent.com/43505196/46890671-d4168880-ce67-11e8-9621-d6f77982d0d2.png)

- **They shouldn't be using [Spell] "Acid Spray"** since they never had it in their arsenal. They were heavy meele oriented mobs, who deal huge dmg in meele range cause of this Poison Shock aura. They are slow for this exact reason, and should only be killed by ranged dps.

Source: https://web.archive.org/web/20090919021612/http://wow.allakhazam.com:80/db/mob.html?wmob=12222

![screenshot_4](https://user-images.githubusercontent.com/43505196/46892892-463e9b80-ce6f-11e8-8834-6db990be8ebb.png)

**Server Revision**: 
2167

**Comment by MAY-THE-ETERNAL-SUN-SHINE-UPON-YOU** [comment]
Can confirm this is still an issue in revision 2825, serious bug

**Comment by Godmatik** [comment]
Rev 4015 still an issue

More importantly they using an ability called "Acid Spray" but it should not exist, they should only melee and deal their AoE damage "Poison Shock"

Low prio

**Comment by EtheriousNW** [comment]
Fixed
