### ISSUE TITLE
[Quest][Dustwallow Marsh] The Essence of Enmity#11161, valid targets incorrect

### ISSUE THREAD

**Issue by Sinyr** [Atlantiss/NetherwingBugtracker#1543]
[//]: # (Enclose links to things related to the bug using http://wowhead.com or any other TBC database.)
[//]: # (You can use screenshot ingame to visual the issue.)
[//]: # (Write your tickets according to the format:)
[//]: # ([Quest][Azuremyst Isle] Red Snapper - Very Tasty!)
[//]: # ([NPC] Magistrix Erona)
[//]: # ([Spell][Mage] Fireball)
[//]: # ([Npc][Drop] Ghostclaw Lynx)
[//]: # ([Web] Armory doesnt work)

**Description**: 
The Essence of Enmity#11161: https://db.excalibur.ws/?quest=11161
Brogg's Totem#33088: https://db.excalibur.ws/?item=33088

**Current behaviour**:
Brogg's Totem can be used on any monster besides the 3 Firemane monsters that are listed on the item. (Tested on Stonemaul Spirit#23786 and Searing Whelp#4324)

Furthermore, using Brogg's Totem on non-Firemane monsters doesn't make those targets invalid for future uses, which means that you could spam it on the same corpse until it despawns, completing the quest very easily.

**Expected behaviour**: 
You shouldn't be able to use Brogg's Totem on non-Firemane monsters.

**Server Revision**: 
2167

**Comment by Labteth** [comment]
Tested the functionality of this quest/item and found that the Brogg's Totem no longer works an any enemies in the zone.

Current behaviour:
Brogg's Totem cannot be used on any NPC alive or dead, looted or unlooted.

Expected behaviour:
You should be able to use Brogg's Totem on the 3 Firemane monsters listed in the quest description.

**Comment by wtRCH** [comment]
- Make it **only** being usable on Firemane NPCs mentioned in the quest.
- NPCs ID: `4328` , `4329` , `4331`

@pelekon

**Comment by Evolvee** [comment]
There is a core problem - of the spell from the quest item. It triggers "invalid target" when trying to use on dead NPCs even tho the spell has 
![image](https://user-images.githubusercontent.com/1942409/50449383-5c64df80-0927-11e9-97d0-2ff1cae5d317.png) ...

Should I make the quest doable by using it on alive NPCs, or rather wait for core fix and then fix it properly as it should be?

**Comment by Wolffenstein** [comment]
wait for core fix

**Comment by Evolvee** [comment]
I made it completeable on alive NPCs, made restrictions to be usable only on these 3 NPCs listed above and gave a 30-60 sec cooldown for it to be usable on the same NPC.

**Comment by Evolvee** [comment]
After the core fix, all that needs to be added are 3 alive conditions.

**Comment by Evolvee** [comment]
rev 2503

**Comment by Frankenberryberry** [comment]
Quest says you should use the totem on the corpses of the NPC's. This is currently not possible. You can only use it on them when they are alive and well :(

**Comment by Evolvee** [comment]
https://github.com/Atlantiss/NetherwingBugtracker/issues/3803
core bug

**Comment by Evolvee** [comment]
rev 2830
