### ISSUE TITLE
[Quest]Rescue OOX-22/FE!#2767 text should say "escort OOX-22/FE to safety" rather than "to the dock..."

### ISSUE THREAD

**Issue by Tenoutoften** [Atlantiss/NetherwingBugtracker#1544]
**Description**: 
[[Quest]Rescue OOX-22/FE!#2767](https://db.excalibur.ws/?quest=2767) currently reads:
![51937c66b906b49529ed20b40baaf0c1](https://user-images.githubusercontent.com/34839199/46894145-be0ec500-ce73-11e8-8af2-99c5b7f19e4e.png)

However, the quest was updated during TBC, so that instead of escorting [[NPC]Homing Robot OOX-22/FE#7807](https://db.excalibur.ws/?npc=7807) to "the dock along the Forgotten Coast" the quest completes a bit after you hit the road, the chicken will then take off. Considering that, I think it is fair to say the quest text should be updated to what it reads on [wowhead](https://www.wowhead.com/quest=2767/rescue-oox-22-fe#comments:40)
![0d68e5fe1f8d00c2dd177dd8cb49988f](https://user-images.githubusercontent.com/34839199/46894061-64a69600-ce73-11e8-83b4-1e517add2600.png)

Escort to safety makes a lot more sense.

**Expected behaviour**: 
Expected to say Escort [[NPC]Homing Robot OOX-22/FE#7807](https://db.excalibur.ws/?npc=7807) to safety.

**Server Revision**: 
2168

**Comment by Firroth** [comment]
This quest wasn't updated in TBC. It was in WoTLK. 
In TBC he should still go to the docks and player need to fight 2-3 ambushes on the path.

![screenshot_1](https://user-images.githubusercontent.com/43505196/46894579-4b064e00-ce75-11e8-88ae-eea7532a9fe7.png)

**Comment by Tenoutoften** [comment]
Makes sense...
![90c2bd90f5d7c74d1899dc5beda2e879](https://user-images.githubusercontent.com/34839199/46894927-79d0f400-ce76-11e8-9904-386869a1e4a2.png)

**Comment by Tenoutoften** [comment]
Closing this one because they are already aware, and this is an open ticket here:
https://github.com/Atlantiss/NetherwingBugtracker/issues/939
