### ISSUE TITLE
[Spell][Warlock] Ritual of Souls using 2 Soul Shards

### ISSUE THREAD

**Issue by Erodraeda** [Atlantiss/NetherwingBugtracker#1546]
[//]: # (Enclose links to things related to the bug using http://wowhead.com or any other TBC database.)
[//]: # (You can use screenshot ingame to visual the issue.)
[//]: # (Write your tickets according to the format:)
[//]: # ([Quest][Azuremyst Isle] Red Snapper - Very Tasty!)
[//]: # ([NPC] Magistrix Erona)
[//]: # ([Spell][Mage] Fireball)
[//]: # ([Npc][Drop] Ghostclaw Lynx)
[//]: # ([Web] Armory doesnt work)

**Description**: 
The skill should use 1 Soul Shard, when the Ritual is finished. Instead of that, it is using 2 Shards, one at cast and one when the ritual is finished. Also the ritual is instant, where there should be a 3-5 seconds cast.
**Current behaviour**:
The spell is using 2 soul shards, instead of one
**Expected behaviour**: 
Only one Soul Shard should be used, when the ritual is finished.
**Server Revision**:

**Comment by Wolffenstein** [comment]
Fixed in rev 2170.
