### ISSUE TITLE
[Maraudon] Missing Mob Linking

### ISSUE THREAD

**Issue by Firroth** [Atlantiss/NetherwingBugtracker#1547]
I will be updating it, if I will find more - first I need to get some ppl for this dungeon.

**Current behaviour**:
- First Slime pack of 4 isn't linked to each other, I pulled 2 without pulling other 2. Made screen of GPS, since I forgot to make screen when they were alive.

![screenshot_2](https://user-images.githubusercontent.com/43505196/46894859-38404900-ce76-11e8-8ca6-f256798f7ee6.png)

**Expected behaviour**: 
All 4 should have pulled.

**Current behaviour**:
- As you can see here only 3 of 4 pulled on me in other pack.

![screenshot_3](https://user-images.githubusercontent.com/43505196/46894860-38d8df80-ce76-11e8-936e-2d947b25bfd1.png)

**Expected behaviour**: 
All 4 should have pulled.

**Current behaviour**:

- You can pull 1 by 1 each "non-elite" Vile Worms in this room.
https://gfycat.com/MindlessMasculineGrasshopper

**Expected behaviour**: 
All Vile Worms in this room should pull, no matter which one you aggro. (all non-elite ones, green ones are the only exception and shouldn't pull).

**Server Revision**: 
2167

**Comment by aresbrutus** [comment]
Both mobs are linked now in rev `Tycho`.
