### ISSUE TITLE
Dueling and totems while in group

### ISSUE THREAD

**Issue by Tinnoan** [Atlantiss/NetherwingBugtracker#1548]
**Description**: 2 other people in my group were dueling, I placed a grounding totem and it absorbed a spell from one of the people dueling.

[video](https://streamable.com/091ba) of the event happening.

All totems seem to have the same problem as this, giving their benefits as long as the people are in group, even if they're dueling.

**Expected behaviour**: The totem should not be able to aid other people in duels

**Server Revision**: 2168

**Comment by Wolffenstein** [comment]
Fixed in rev 2170.
