### ISSUE TITLE
Fishing casting bar

### ISSUE THREAD

**Issue by maxturtlesc2** [Atlantiss/NetherwingBugtracker#1549]
[//]: # (Enclose links to things related to the bug using http://wowhead.com or any other TBC database.)
[//]: # (You can use screenshot ingame to visual the issue.)
[//]: # (Write your tickets according to the format:)
[//]: # ([Quest][Azuremyst Isle] Red Snapper - Very Tasty!)
[//]: # ([NPC] Magistrix Erona)
[//]: # ([Spell][Mage] Fireball)
[//]: # ([Npc][Drop] Ghostclaw Lynx)
[//]: # ([Web] Armory doesnt work)
https://www.dropbox.com/s/9lg2iwrprd21na6/2018-10-13_00-02-35.mp4?dl=0
**Description**: 
The fishing casting bar doesn't disappear when no fish gets hooked. It should.
**Current behaviour**:
The fishing casting bar doesn't disappear when no fish gets hooked.
**Expected behaviour**: 
The fishing casting bar should disappear when no fish gets hooked.
**Server Revision**:

**Comment by wtRCH** [comment]
I think it might be one of your Addons which cause the problem. Try to disable them and comment if it fixed it.

**Comment by maxturtlesc2** [comment]
@wtRCH I did test without addon, the problem is still here even on the default cast bar.

**Comment by Manaci** [comment]
Fixed
