### ISSUE TITLE
Rotting Hearts Ghostlands

### ISSUE THREAD

**Issue by Trix115** [Atlantiss/NetherwingBugtracker#155]
* Rotting Hearts for the quest Rotting Hearts seems exceedingly rare. (0 after 15 Risen Hungerer killed)

**Comment by DarthNekr0s** [comment]
this is actually blizzlike, ive levelled a lot of belf alts on retail and even currently the drop rates on this item are horrible. however on this server ive killed about 10-15 so far and gotten 2 hearts, this may just be really bad luck

**Comment by The14me** [comment]
Blizzlike
