### ISSUE TITLE
[NPC][Desolace] Slitherblade Razortail#4715 and Slitherblade Sea Witch#4719

### ISSUE THREAD

**Issue by Sinyr** [Atlantiss/NetherwingBugtracker#1550]
[//]: # (Enclose links to things related to the bug using http://wowhead.com or any other TBC database.)
[//]: # (You can use screenshot ingame to visual the issue.)
[//]: # (Write your tickets according to the format:)
[//]: # ([Quest][Azuremyst Isle] Red Snapper - Very Tasty!)
[//]: # ([NPC] Magistrix Erona)
[//]: # ([Spell][Mage] Fireball)
[//]: # ([Npc][Drop] Ghostclaw Lynx)
[//]: # ([Web] Armory doesnt work)

**Description**:
Slitherblade Razortail#4715: https://db.excalibur.ws/?npc=4715
Slitherblade Sea Witch#4719: https://db.excalibur.ws/?npc=4719

**Current behaviour**:
These 2 monsters are walking in place and can't be interacted with. It seems like the same bug that was present with some monsters in Azuremyst Isle on day 1 of open beta.

EDIT: Not client side, my leveling buddy experienced it too.

![screenshot_38](https://user-images.githubusercontent.com/9539181/46896837-b523f080-ce7f-11e8-8139-787d1b36ee1f.png)
![screenshot_39](https://user-images.githubusercontent.com/9539181/46896838-b523f080-ce7f-11e8-8d99-3a238777bf92.png)
![screenshot_40](https://user-images.githubusercontent.com/9539181/46896839-b523f080-ce7f-11e8-9283-c04992a31456.png)
![screenshot_41](https://user-images.githubusercontent.com/9539181/46896840-b523f080-ce7f-11e8-92cd-8f5ac3ce4076.png)

**Expected behaviour**: 
They shouldn't be stuck like this.

**Server Revision**: 
2167

**Comment by Sinyr** [comment]
I just encountered that exact Aged Kodo today, and I can confirm that it's the same bug with these monsters.

**Comment by aresbrutus** [comment]
Fixed after rev `2196`
