### ISSUE TITLE
[NPC][Movement]Two mobs stacked on top of each other in "The Watching Deep" missing patrol

### ISSUE THREAD

**Issue by Tenoutoften** [Atlantiss/NetherwingBugtracker#1551]
**Description**: 
![1c18f45bf0e19bcc981f3f456bdf23e2](https://user-images.githubusercontent.com/34839199/46898164-a4777880-ce87-11e8-8737-5400a8d38986.png)
![265c30e7800913f9e5c1ae7f27e31e55](https://user-images.githubusercontent.com/34839199/46898165-a4777880-ce87-11e8-9285-ee8d9f63a048.png)
Looks very bizarre, should probably be a patrol or just not be there.
On retail, in a much later expansion, in the same cave it looks like the [[NPC]Zukk'ash Stinger#5244](https://db.excalibur.ws/?npc=5244) is patroling, video [here](https://youtu.be/rEXT0_aTDwY?t=91)
![1298da755ab042e0cf13e1e5301df6b4](https://user-images.githubusercontent.com/34839199/46898253-4008e900-ce88-11e8-8cd8-9afac3675e44.png)

**Expected behaviour**: 
[[NPC]Zukk'ash Stinger#5244](https://db.excalibur.ws/?npc=5244) expected to patrol

**Server Revision**: 
2169

**Comment by aresbrutus** [comment]
Fixed in rev `Tycho`.
