### ISSUE TITLE
[NPC] Wavethrasher - underground

### ISSUE THREAD

**Issue by mbzz88** [Atlantiss/NetherwingBugtracker#1553]
**Description**: Mob is under the ground/broken pathing

**Current behaviour**: ![wowscrnshot_101318_132221](https://user-images.githubusercontent.com/43509267/46899042-39f82400-ceeb-11e8-9577-532ff0cef219.jpg)
https://youtu.be/aFRF7PV5-f4

**Expected behaviour**: Not underground

**Server Revision**: 2169

**Comment by aresbrutus** [comment]
Fixed in rev `Tycho`.
