### ISSUE TITLE
[NPC] Aged Kodo - unattackable

### ISSUE THREAD

**Issue by tcberk12** [Atlantiss/NetherwingBugtracker#1555]
**Description**: 

This poor Aged Kodo is bugged in the Kodo graveyard.

**Current behaviour**:

On northern rim of the Kodo Graveyard, there's an Aged Kodo that is walking in place and is unattackable. Pet is unable to engage him and all my abilities say "Out of Range" when I try to cast on it. I thought I was crashing but was able to fight and kill any nearby mobs just fine.

<img width="1435" alt="screen shot 2018-10-12 at 6 42 40 pm" src="https://user-images.githubusercontent.com/43530009/46899919-d91b0e00-ce4e-11e8-9048-b654b2fc3656.png">

NPC ID is in the SS

**Expected behaviour**: 

This guy should be able to be engaged.

**Server Revision**: 
2169

**Comment by maxturtlesc2** [comment]
There are other mobs in the same situation as well. I think I came across two in stranglethorn valley (mine were in a running motion, but not moving from their spot) . Most likely a more global problem than one solo NPC bugged out.

**Comment by tcberk12** [comment]
yeah, this is happening in multiple places, ssee #1550 as well

**Comment by The14me** [comment]
Its Core problem with movement,no single mob related.

**Comment by aresbrutus** [comment]
Fixed after rev `2196`
