### ISSUE TITLE
[Quest] The Deserters - Balos Jacken can be killed

### ISSUE THREAD

**Issue by tcberk12** [Atlantiss/NetherwingBugtracker#1556]
**Description**: 

http://classicdb.ch/?quest=1286 - this is the quest. You are supposed to get Balos Jacken to low health, at which point he submits and gives you the information needed to complete the quest objective.

**Current behaviour**:

If you fight Balos Jacken on his spawn point (on top of the decrepit staircase), he will submit at low health as intended. However, if you fight him at the bottom of the stairs inside the tower, he will die. @aresbrutus observed this behavior and can confirm.

When he died, I did not receive credit for the quest. I waited for respawn and killed him on top of the stairs, and it worked.

**Expected behaviour**: 

Balos Jacken should submit at low health and complete the quest objective, regardless of where he is fought.

**Server Revision**: 
2169

**Comment by Evolvee** [comment]
![image](https://user-images.githubusercontent.com/1942409/46906950-8a7f7980-cf0b-11e8-9a15-a3cfd1e3d320.png)

**Comment by Wolffenstein** [comment]
Fixed in rev 2170.
