### ISSUE TITLE
[NPC]Sprite Darter#5278 should have casting time on [Spell]Mana Burn

### ISSUE THREAD

**Issue by Tenoutoften** [Atlantiss/NetherwingBugtracker#1557]
**Description**: 
[[NPC]Sprite Darter#5278](https://db.excalibur.ws/?npc=5278#abilities) seems to be using the wrong [[Spell]Mana Burn#17630](https://db.excalibur.ws/?spell=17630)-spell, currently it is instant cast with amount scaling on level, video [here](https://www.youtube.com/watch?v=l7InHESzdE0&feature=youtu.be). The amount looks fine, but it shouldn't be instant cast:
![bae679e8a7fc15001ecd7fd070ebd82f](https://user-images.githubusercontent.com/34839199/46903136-2b9d0e80-ced1-11e8-8781-070f3b1ccd35.png)
It doesn't make any sense to write that you need to **interrupt** if the cast is instant, you aren't interrupting anything then, or complain about your silence having a cd.

Furthermore [here](https://youtu.be/5_ZPdLEprMg?t=5795) is a video of it being fought in vanilla with casting time.

**Expected behaviour**: 
Expected to have a [[Spell]Mana Burn](https://db.excalibur.ws/?search=mana+burn) with cast time

**Server Revision**: 
2169

**Comment by Evolvee** [comment]
rev yummy
