### ISSUE TITLE
[NPC][Desolace] Nijel's Point Guard - orientation and movement

### ISSUE THREAD

**Issue by Firroth** [Atlantiss/NetherwingBugtracker#1558]
[NPC] Nijel's Point Guard [8151]

**Current behaviour**:

- They are facing the "city" rather than way out of the city. (1rst screenshot)
![screenshot_1](https://user-images.githubusercontent.com/43505196/46904095-5726f580-cedf-11e8-8f92-fcc0dbeb1c26.png)

- They are moving around rather than stand and watch gate of the city. (2nd screenshot)
![screenshot_2](https://user-images.githubusercontent.com/43505196/46904121-c7357b80-cedf-11e8-8a1c-e2d28874d71f.png)

**Expected behaviour**: 

- (1rst screenshoot) They should face exit of the city.

- (2nd screenshot) They shouldn't be roaming around near gate, they should stand still and watch exit from the city.

**Server Revision**: 
2169

**Comment by Evolvee** [comment]
rev yummy
