### ISSUE TITLE
[Core] Crit Calculation

### ISSUE THREAD

**Issue by Azalen** [Atlantiss/NetherwingBugtracker#1559]
**Description**: 
Okay, this will be hard to describe so I'll try it with some pictures but prolly best if you recreate it for yourself in dev-realm. To be sure I deleted Cache again before taking any of the screenshots.

Level 50 Warrior, specced 31/10/0 with Sword Spec and 5% crit in Fury tree.

http://wowwiki.wikia.com/wiki/Critical_strike?oldid=1588281

**Current behaviour**:
Before equipping any weapon: 
![wowscrnshot_101318_122422](https://user-images.githubusercontent.com/20336567/46904349-f6012100-cee2-11e8-8f1c-543df6a67326.jpg)

You can notice that I have 6.63% crit even though the Agility Calculation shows I should have 7.79%. Fyi, without any items the problem still persist.

But now stuff is getting super weird.
1) I equip my 2H sword without any stats and my crit chance increases to 11.95% (+5.32%) even though the talent only adds 5% crit.
![wowscrnshot_101318_123644](https://user-images.githubusercontent.com/20336567/46904459-af142b00-cee4-11e8-8c9e-9773a48b7423.jpg)

2) I unequip my sword and equip an axe resulting in 15.59% crit (no Axe spec!)
![wowscrnshot_101318_123856](https://user-images.githubusercontent.com/20336567/46904482-0914f080-cee5-11e8-9860-3985717d81ab.jpg)

3) Ready for some action? I unequip my Axe and now - without any weapon - I have 10.59% crit chance.
![wowscrnshot_101318_124243](https://user-images.githubusercontent.com/20336567/46904526-82acde80-cee5-11e8-8281-6a28e58011a8.jpg)

I hope this is helpful and I didn't miss something _critical_.

**Expected behaviour**: 
I think Agility Crit should match the shown Crit and idk about the other things.

**Server Revision**: 
[2169]

**Comment by Evolvee** [comment]
are you sure you had the same weapon skill of both weapon types?

wep skill affects it

**Comment by Evolvee** [comment]
^^

**Comment by whissper** [comment]
1 weapon skill adds 0.04% crit chance (but not 100% sure)

**Comment by Evolvee** [comment]
no shit
