### ISSUE TITLE
Instant death after respawn chest opening

### ISSUE THREAD

**Issue by Dekirayne** [Atlantiss/NetherwingBugtracker#156]
[//]: # (Enclose links to things related to the bug using http://wowhead.com or any other TBC database.)
[//]: # (You can use screenshot ingame to visual the issue.)
[//]: # (Write your tickets according to the format:)
[//]: # ([Quest][Azuremyst Isle] Red Snapper - Very Tasty!)
[//]: # ([NPC] Magistrix Erona)
[//]: # ([Spell][Mage] Fireball)
[//]: # ([Npc][Drop] Ghostclaw Lynx)
[//]: # ([Web] Armory doesnt work)

**Description**: 
So i died to 2 wolves while trying to open a chest in duskwood, then i wanted to sneak ninja the chest without aggroing them but as soon as i started doing the chest I get in the combat (i dont know if i aggro them or not for that split second) and i just DIE instantly without mobs even being near me. It happened 3 times in a row.
**Current behaviour**:

**Expected behaviour**: 
Not dying when i open chest and getting into the [combat]
**Server Revision**: 
![wowscrnshot_092318_130632](https://user-images.githubusercontent.com/12075744/45927346-1bc58680-bf32-11e8-8c44-64f6c7343ed4.jpg)

**Comment by The14me** [comment]
Re-tested...now work fine.
