### ISSUE TITLE
[NPC]Gordunni Warlord#5241 should "calls for help!"

### ISSUE THREAD

**Issue by Tenoutoften** [Atlantiss/NetherwingBugtracker#1561]
**Description**: 
[[NPC]Gordunni Warlord#5241](https://db.excalibur.ws/?npc=5241) should "calls for help!"
seen [here](https://youtu.be/5_ZPdLEprMg?t=10782) currently [doesn't](https://www.youtube.com/watch?v=mKO35gMXPlo&feature=youtu.be)

**Expected behaviour**: 
Expected to "calls for help!"

**Server Revision**: 
2169

**Comment by Evolvee** [comment]
rev yummy
