### ISSUE TITLE
[Profession]Fishing - empty loot

### ISSUE THREAD

**Issue by DeltaLoads** [Atlantiss/NetherwingBugtracker#1563]
[//]: # (Enclose links to things related to the bug using http://wowhead.com or any other TBC database.)
[//]: # (You can use screenshot ingame to visual the issue.)
[//]: # (Write your tickets according to the format:)
[//]: # ([Quest][Azuremyst Isle] Red Snapper - Very Tasty!)
[//]: # ([NPC] Magistrix Erona)
[//]: # ([Spell][Mage] Fireball)
[//]: # ([Npc][Drop] Ghostclaw Lynx)
[//]: # ([Web] Armory doesnt work)

**Description**: 
Fishing sometimes gets empty loot, also empty loots always award skillpoint which they shouldn't
![wowscrnshot_101318_165237](https://user-images.githubusercontent.com/43690147/46906798-979b6900-cf09-11e8-8731-787dfc01a3a9.jpg)

**Current behaviour**:
You can get empty loot
**Expected behaviour**: 
Instead of empty loot you should get a message that "Your fish has got away!"
**Server Revision**: 
2169

**Comment by DeltaLoads** [comment]
also you can get message "Your fish has got away!" and you also get a loot
![wowscrnshot_101318_175455](https://user-images.githubusercontent.com/43690147/46907332-34add000-cf11-11e8-82af-635f6957b851.jpg)

**Comment by Jezofine** [comment]
Got this kind of behavior on a single Floating Debris spot at 63 38: empty loot, sometimes skill point, debris never disappear. Also bobber disappears without stopping fishing cast and any warnings much more often than in non-bugged areas. 
Not happening in other schools or clear water around.

**Comment by Tereneckla** [comment]
Fixed
