### ISSUE TITLE
[NPC][Movement] Specific Nether Maiden#4679 has weird pathing

### ISSUE THREAD

**Issue by Sinyr** [Atlantiss/NetherwingBugtracker#1566]
[//]: # (Enclose links to things related to the bug using http://wowhead.com or any other TBC database.)
[//]: # (You can use screenshot ingame to visual the issue.)
[//]: # (Write your tickets according to the format:)
[//]: # ([Quest][Azuremyst Isle] Red Snapper - Very Tasty!)
[//]: # ([NPC] Magistrix Erona)
[//]: # ([Spell][Mage] Fireball)
[//]: # ([Npc][Drop] Ghostclaw Lynx)
[//]: # ([Web] Armory doesnt work)

**Description**: 
Nether Maiden#4679: https://db.excalibur.ws/?npc=4679

**Current behaviour**:
This specific Nether Maiden paths through the ground near the spot in the image, with only her head visible. Also weirdly walks onto the nearby bench, clipping into the wall a little.

![screenshot_43](https://user-images.githubusercontent.com/9539181/46907253-17c4cd00-cf10-11e8-82bc-e6ae4b996fa5.png)

**Expected behaviour**: 
Shouldn't clip into the ground or wall.

**Server Revision**: 
2169

**Comment by aresbrutus** [comment]
Fixed in rev `Tycho`.
