### ISSUE TITLE
[NPC][Linking] Argus Shadow Mage#2318 not linked to any monsters

### ISSUE THREAD

**Issue by Sinyr** [Atlantiss/NetherwingBugtracker#1567]
[//]: # (Enclose links to things related to the bug using http://wowhead.com or any other TBC database.)
[//]: # (You can use screenshot ingame to visual the issue.)
[//]: # (Write your tickets according to the format:)
[//]: # ([Quest][Azuremyst Isle] Red Snapper - Very Tasty!)
[//]: # ([NPC] Magistrix Erona)
[//]: # ([Spell][Mage] Fireball)
[//]: # ([Npc][Drop] Ghostclaw Lynx)
[//]: # ([Web] Armory doesnt work)

**Description**: 
Argus Shadow Mage#2318: https://db.excalibur.ws/?npc=2318

**Current behaviour**:
This NPC isn't linked to any other monster, meaning that you can pull him from the middle of a camp and he will attack you alone while otherwise 4-5 monsters would attack you. It's also weird that inside one of the houses in Strahnbrad where he's talking to a Syndicate Wizard, when you pull one the other just stands there.

**Expected behaviour**: 
Argus Shadow Mage should be linked to Syndicate monsters in the area.

**Server Revision**: 
2167

**Comment by Evolvee** [comment]
rev yummy
