### ISSUE TITLE
[Quest] [Darkwood] The Totem of Infliction

### ISSUE THREAD

**Issue by CiriusDrayke** [Atlantiss/NetherwingBugtracker#1568]
[//]: # (Enclose links to things related to the bug using http://wowhead.com or any other TBC database.)
[//]: # (You can use screenshot ingame to visual the issue.)
[//]: # (Write your tickets according to the format:)
[//]: # ([Quest][Azuremyst Isle] Red Snapper - Very Tasty!)
[//]: # ([NPC] Magistrix Erona)
[//]: # ([Spell][Mage] Fireball)
[//]: # ([Npc][Drop] Ghostclaw Lynx)
[//]: # ([Web] Armory doesnt work)

**Description**: Item in quest: http://db.hellfire-tbc.com/?item=1129#dropped-by Drop on the item.

**Current behaviour**:
Not all the mobs in the area seem to have the drop on item while having the quest example: The mobs southwest of the underground cript around 24, 40 do not drop the item at all. Mobs around 22, 34 seem to drop the item as normal.
**Expected behaviour**: 
All the mobs in the list on DB around the area should be dropping the item.
**Server Revision**: 
2169

**Comment by CiriusDrayke** [comment]
Drop rate seems janky about 35 mobs killed for 10 items need bigger sample size to confirm behaviour.

**Comment by wtRCH** [comment]
@aresbrutus

**Comment by aresbrutus** [comment]
Drop rates are correct, I checked it at https://github.com/Atlantiss/NetherwingBugtracker/issues/879
