### ISSUE TITLE
Spell Batch Experience (Selfbuff+First Aid)

### ISSUE THREAD

**Issue by Kidcudi123** [Atlantiss/NetherwingBugtracker#157]
This is no real bug report with evidence, just sharing.

There's been discussion on discord about spell batch on selfbuffs and such, that it shouldn't occur then.
I battle shouted and started first aiding and it stopped my channeling, maybe hints towards that buffs should be instant?

**Comment by Bleachlol** [comment]
Current PC is shit so can't record it, but here is something that might help: https://imgur.com/a/UhVj9Yn

Casts battle shouts --> First aid --> Will cancel it FA, gets the debuff that I just bandaged but no heal.

**Comment by Easyfraggy** [comment]
Would you mind retesting this after the latest fixes? I cannot reproduce.

**Comment by The14me** [comment]
Re-tested.Work fine now.
