### ISSUE TITLE
[NPC] Shadowforge Surveyor#4844 clipping through ground

### ISSUE THREAD

**Issue by Sinyr** [Atlantiss/NetherwingBugtracker#1570]
[//]: # (Enclose links to things related to the bug using http://wowhead.com or any other TBC database.)
[//]: # (You can use screenshot ingame to visual the issue.)
[//]: # (Write your tickets according to the format:)
[//]: # ([Quest][Azuremyst Isle] Red Snapper - Very Tasty!)
[//]: # ([NPC] Magistrix Erona)
[//]: # ([Spell][Mage] Fireball)
[//]: # ([Npc][Drop] Ghostclaw Lynx)
[//]: # ([Web] Armory doesnt work)

**Description**: 
Shadowforge Surveyor#4844: https://db.excalibur.ws/?npc=4844

**Current behaviour**:
Clipping through this stone, but regularly casting spells and attacking. I was even able to loot him afterward.

![screenshot_44](https://user-images.githubusercontent.com/9539181/46908296-4008f780-cf21-11e8-9660-e1859337c9dc.png)

**Expected behaviour**: 
Shouldn't spawn here of clip through this stone.

**Server Revision**: 
2169

**Comment by Sinyr** [comment]
Fought him again. He spawned at the exact same place, inside the stone. Invisible unless you have nameplates on.

**Comment by aresbrutus** [comment]
Please make sure for the next time if it is NPC related to select the NPC and do `.npc info` before making a screenshot. This way I instantly know which NPC has the issue.

Fixed in rev `Tycho`.
