### ISSUE TITLE
[NPC][The Barrens] Horde Guard

### ISSUE THREAD

**Issue by eryczek1615** [Atlantiss/NetherwingBugtracker#1571]
**Description**: 
[Horde Guard](https://www.wowhead.com/npc=3501/horde-guard)

**Current behaviour**:
Minor bug. One more should patrol around Camp Taurajo
https://imgur.com/MgHPzDE
https://youtu.be/qdTnZm4tvSc?t=356

**Expected behaviour**: 
This one should have movment points.

**Server Revision**: 
2169

**Comment by aresbrutus** [comment]
Added random movement to him in rev `Tycho.`
