### ISSUE TITLE
[NPC][Drop] Ice Thistle Patriarch/Matriarch

### ISSUE THREAD

**Issue by kudryashov-n** [Atlantiss/NetherwingBugtracker#1572]
[//]: # (Enclose links to things related to the bug using http://wowhead.com or any other TBC database.)
[//]: # (You can use screenshot ingame to visual the issue.)
[//]: # (Write your tickets according to the format:)
[//]: # ([Quest][Azuremyst Isle] Red Snapper - Very Tasty!)
[//]: # ([NPC] Magistrix Erona)
[//]: # ([Spell][Mage] Fireball)
[//]: # ([Npc][Drop] Ghostclaw Lynx)
[//]: # ([Web] Armory doesnt work)

**Description**: 

**Current behaviour**:
Drops too much money (8 and 9 silver on screenshot)
**Expected behaviour**: 
Should drop less money after kill i guess.
https://classicdb.ch/?npc=7460#comments
https://db.excalibur.ws/?npc=7460
![wowscrnshot_101318_215744](https://user-images.githubusercontent.com/43183825/46909061-093cdc80-cf35-11e8-8c05-2cacf2291d6c.jpg)

**Server Revision**:

**Comment by Firroth** [comment]
How about those? sources: wowhead and wowwiki.

![screenshot_2](https://user-images.githubusercontent.com/43505196/46910140-a735a480-cf3f-11e8-998f-f10608fe9fa3.png)
![screenshot_3](https://user-images.githubusercontent.com/43505196/46910141-a7ce3b00-cf3f-11e8-9aff-8423306c5bfd.png)
![screenshot_4](https://user-images.githubusercontent.com/43505196/46910142-a7ce3b00-cf3f-11e8-9856-05886311461b.png)

**Comment by aresbrutus** [comment]
Still not good enough, would require ingame footage.

Money drops really varies, like the yeti drops between 2 and 9 silver and not exactly 4.85 like the wowwiki states. I believe the wowwiki just has the averages.

**Comment by SwiftieTBC** [comment]
https://youtu.be/OaNZ3saYZUY?t=86 Vid from tbc showing 8s drops

**Comment by aresbrutus** [comment]
Swiftie with the videos! Thanks.

Seems to be similar to retail on NW: https://gfycat.com/UnsungLittleBirdofparadise
