### ISSUE TITLE
[Dungeon] [Party] Dungeons not getting reseted after getting in party / logging off for long time.

### ISSUE THREAD

**Issue by Unfairy** [Atlantiss/NetherwingBugtracker#1573]
Dungeons not getting reseted after getting in party / logging off for long time.
I killed solo Razorlash in Maraudon and logged off.
After logging on about in 5-6 hours, I got party for Maraudon but when we got to boss spot, he was dead.
Its not supposed to be like that for 2 reasons.
Getting in party outside of dungeon supposed to trigger auto reset.
Long time log off supposed to auto reset dungeon.

**Comment by Tenoutoften** [comment]
https://github.com/Atlantiss/NetherwingBugtracker/issues/1814
