### ISSUE TITLE
[Maraudon] Linking

### ISSUE THREAD

**Issue by Azalen** [Atlantiss/NetherwingBugtracker#1574]
**Description**: 
List of packs that are not linked. See chat for mob ID.

![wowscrnshot_101318_213629](https://user-images.githubusercontent.com/20336567/46909851-8ff3b880-cf39-11e8-8988-57abc00dcf50.jpg)
All those Noxious Slime packs aren't linked.

![wowscrnshot_101318_214129](https://user-images.githubusercontent.com/20336567/46909860-ca5d5580-cf39-11e8-8c51-5917279882e1.jpg)
All those packs containing 1-2 Satyrs and 3-4 Imps aren't linked to each other.

![wowscrnshot_101318_214635](https://user-images.githubusercontent.com/20336567/46909861-d812db00-cf39-11e8-8abc-60f31b48e035.jpg)
Afaik the first two should be linked to each other and the two in the back should be linked to the boss.
Proof: https://www.youtube.com/watch?v=0B_jEpYR_4M (0:40-1:45)
Proof: 
> When you are in front of Lord Vyletongue's building, don't rush in carelessly, there are 2 stealthed satyrs guarding it's entrance, pull them and kill them. Then the only thing you'll be facing will be Lord Vyletongue and his two stealthed guards (those you'll have to fight at the same time as Lord Vyletongue). (http://wow-pro.com/dungeon_and_raid_guides/4052_jame039s_maraudon_guide)

![wowscrnshot_101318_220128](https://user-images.githubusercontent.com/20336567/46909872-f7116d00-cf39-11e8-8418-f805e5e20a7d.jpg)
![wowscrnshot_101318_220521](https://user-images.githubusercontent.com/20336567/46909875-0b556a00-cf3a-11e8-86ad-58df4e5405ed.jpg)
![wowscrnshot_101318_221231](https://user-images.githubusercontent.com/20336567/46909877-2031fd80-cf3a-11e8-9413-670d8b7765f0.jpg)
All those type of packs (packs of 3-4 mobs) aren't linked in the third and final part of Maraudon. Did not get screenshots of all of them since we bodypulled some.

![wowscrnshot_101318_222335](https://user-images.githubusercontent.com/20336567/46909882-27590b80-cf3a-11e8-9d10-51bbae5281d7.jpg)
All packs of this type aren't linked as well (packs of 5-8 non elite worms).
Proof: https://youtu.be/J9OfKdlfzWs?t=1222

**Server Revision**: 
[2169]

**Comment by aresbrutus** [comment]
Will be fixed with rev `Tycho`. 

I have fixed a lot of packs and might have missed some more. Can you please gather a group gain for Maraudon and run it again? Please make a new issue of missed mobs that should be linked. Thank you.
