### ISSUE TITLE
[Maraudon] The Scepter of Celebras

### ISSUE THREAD

**Issue by Azalen** [Atlantiss/NetherwingBugtracker#1575]
**Description**: 
https://classicdb.ch/?quest=7046

**Current behaviour**:
Celebras stay's at the spawn location, nothing happens.

**Expected behaviour**: 
Celebras' Ghost should move up to the spot shown in the video and start the event on quest accept.
Proof: https://www.youtube.com/watch?v=1WpK-kHa_8k

**Server Revision**: 
[2169]

**Comment by Firroth** [comment]
#1067

**Comment by Azalen** [comment]
Sorry only searched for "Maraudon" not for the quest name >.<

**Comment by aresbrutus** [comment]
Duplicate
