### ISSUE TITLE
[Maraudon] Celebras the Cursed

### ISSUE THREAD

**Issue by Azalen** [Atlantiss/NetherwingBugtracker#1576]
**Description**: 
https://classicdb.ch/?npc=12225

**Current behaviour**:
Did not try to summon any additional trees.

**Expected behaviour**: 
Should summon additional trees, root the tank and move away to cast wraith.
Proof: https://youtu.be/-1Uoq27R1UE?t=91

**Server Revision**: 
[2169]

**Comment by Easyfraggy** [comment]
https://github.com/Atlantiss/AtlantissTBCBT/issues/3754

**Comment by Evolvee** [comment]
rev yummy
