### ISSUE TITLE
[Spell] Rapid Killing#35098/35099 fades when killing an enemy with an ability that it buffs

### ISSUE THREAD

**Issue by Ahmpy** [Atlantiss/NetherwingBugtracker#1577]
[//]: # (Enclose links to things related to the bug using http://wowhead.com or any other TBC database.)
[//]: # (You can use screenshot ingame to visual the issue.)
[//]: # (Write your tickets according to the format:)
[//]: # ([Quest][Azuremyst Isle] Red Snapper - Very Tasty!)
[//]: # ([NPC] Magistrix Erona)
[//]: # ([Spell][Mage] Fireball)
[//]: # ([Npc][Drop] Ghostclaw Lynx)
[//]: # ([Web] Armory doesnt work)

**Description**: 
The Hunter Tier 3 Marksmanship talent, Rapid Killing will correctly proc off of the death of enemies regardless of the situation, as long as you or your pet gets the killing blow. The issue here occurs when the hunter gets a killing blow on a mob with any spell that would otherwise "use up" the proc normally, ie: Auto Shot, Arcane Shot, *Multi Shot, or Aimed Shot

**Current behaviour**:
When you kill a mob using Auto Shot, Arcane Shot, *Multi Shot, or Aimed Shot the rapid killing buff is applied as usual and immediately fades as if used.  

Ex. Video: https://youtu.be/vxBApGuGi0s
0:17/0:35/1:10 Pet kills and appropriately player receives Rapid Killing
1:33 Player kills using arcane shot, player's Rapid Killing is used
1:54 Player kills using auto shot, player's Rapid Killing is used
2:13 Pet kills the same second an auto shot hits, player's Rapid Killing is used
2:40/3:02/3:26/3:47/4:16 Pet kills or player kills using a spell not affected by Rapid Killing
4:35 Player kills using multi shot, player's Rapid Killing is used

*Multi Shot is incorrectly being effected by rapid killing (see #1578)

**Expected behaviour**: 

Rapid Killing should not be used up by damaging spells that are affected by the buff.

**Server Revision**: 
2169

**Comment by Wolffenstein** [comment]
Fixed in rev 2170.
