### ISSUE TITLE
[Spell] Rapid Killing#35098/35099 buffs Multi-Shot

### ISSUE THREAD

**Issue by Ahmpy** [Atlantiss/NetherwingBugtracker#1578]
[//]: # (Enclose links to things related to the bug using http://wowhead.com or any other TBC database.)
[//]: # (You can use screenshot ingame to visual the issue.)
[//]: # (Write your tickets according to the format:)
[//]: # ([Quest][Azuremyst Isle] Red Snapper - Very Tasty!)
[//]: # ([NPC] Magistrix Erona)
[//]: # ([Spell][Mage] Fireball)
[//]: # ([Npc][Drop] Ghostclaw Lynx)
[//]: # ([Web] Armory doesnt work)

**Description**: Rapid Killing incorrectly effects Multi-Shot, when tooltip specifically states: "after killing an opponent that yields experience or honor, your next Aimed Shot, Arcane Shot or Auto Shot causes 10% additional damage.

**Current behaviour:**: I'm gathering recount reports to see if it is or isn't being buffed by the talent, it probably is due to it's interaction with Rapid Killing and causing it to fade immediately (see #1577)

**Expected behaviour**: Rapid Killing should only effect Aimed Shot, Arcane Shot, and Auto Shot.

**Server Revision**: 2169

**Comment by Wolffenstein** [comment]
Fixed in rev 2170.
