### ISSUE TITLE
[Searing Gorge] Bad spawn point

### ISSUE THREAD

**Issue by Azalen** [Atlantiss/NetherwingBugtracker#1579]
**Description**: 
Spawn point makes the mob fall through the map when player moves into visibility
![wowscrnshot_101318_233010](https://user-images.githubusercontent.com/20336567/46910179-625e3d80-cf40-11e8-8a32-c90202a36e7a.jpg)

**Server Revision**: 
[2169]

**Comment by aresbrutus** [comment]
Client issue, works fine for me.
