### ISSUE TITLE
[NPC][Eversong Woods] Silvermoon Guardian / Springpaw Stalker behavior

### ISSUE THREAD

**Issue by ffchaosmaster** [Atlantiss/NetherwingBugtracker#158]
[//]: # (Enclose links to things related to the bug using http://wowhead.com or any other TBC database.)
[//]: # (You can use screenshot ingame to visual the issue.)
[//]: # (Write your tickets according to the format:)
[//]: # ([Quest][Azuremyst Isle] Red Snapper - Very Tasty!)
[//]: # ([NPC] Magistrix Erona)
[//]: # ([Spell][Mage] Fireball)
[//]: # ([Npc][Drop] Ghostclaw Lynx)
[//]: # ([Web] Armory doesnt work)

**Description**: 
The two Silvermoon Guardians patrolling in Eversong Woods near the bridge at (45,60) and up the road have a glitch when they are close to the bridge.
**Current behaviour**:
Springpaw Stalkers near the bridge don't spawn properly and it seems like the guards are trying to attack them anyway and glitch around attacking nothing for a few seconds.
Screenshot:
![wowscrnshot_092318_132603](https://user-images.githubusercontent.com/5289978/45927522-9beceb80-bf34-11e8-8fa0-e4057c427721.jpg)

**Expected behaviour**: 
Either the mobs should spawn properly or the guardians shouldn't glitch around trying to target them.

**Server Revision**:

**Comment by Evolvee** [comment]
@Wolffenstein 
its because these cats are in stealth

so they try to aggro stealthed NPCs which they cant so they glitch until the cat is near enough for them to attack it in stealth

**Comment by The14me** [comment]
Fixed long time a go.
