### ISSUE TITLE
[Spell][Hunter]Bestial Wrath

### ISSUE THREAD

**Issue by DeltaLoads** [Atlantiss/NetherwingBugtracker#1580]
[//]: # (Enclose links to things related to the bug using http://wowhead.com or any other TBC database.)
[//]: # (You can use screenshot ingame to visual the issue.)
[//]: # (Write your tickets according to the format:)
[//]: # ([Quest][Azuremyst Isle] Red Snapper - Very Tasty!)
[//]: # ([NPC] Magistrix Erona)
[//]: # ([Spell][Mage] Fireball)
[//]: # ([Npc][Drop] Ghostclaw Lynx)
[//]: # ([Web] Armory doesnt work)

**Description**: 
Skill resets if you mount up while its active... can be abused to last forever
https://streamable.com/aa1ld

**Current behaviour**:
Bestial Wrath resets if you mount up and dismount while its active
**Expected behaviour**: 
Bestial Wrath shouldnt reset when mounting and dismounting
**Server Revision**: 
2169

**Comment by Evolvee** [comment]
yea, maybe if someone bothered to fix my reports in 2k16 ... pepehands

http://tbc.internal.atlantiss.eu/showthread.php?tid=392&highlight=bestial+wrath
http://tbc.internal.atlantiss.eu/showthread.php?tid=1508&highlight=bestial+wrath

**Comment by Wolffenstein** [comment]
Fixed in rev 2170.
