### ISSUE TITLE
[Quest][The Barrens] Ishamuhale

### ISSUE THREAD

**Issue by eryczek1615** [Atlantiss/NetherwingBugtracker#1581]
**Description**:  
[Quest](https://www.wowhead.com/quest=882)
[NPC](https://www.wowhead.com/npc=3257)

**Current behaviour**:
After summoned he doesn't attack us immediately.

**Expected behaviour**: 
Should attack us immediately after summoned

**Server Revision**: 
2169

**Comment by Evolvee** [comment]
![image](https://user-images.githubusercontent.com/1942409/46915257-48a51080-cfa9-11e8-9308-0c8940f07981.png)

slightly updated the script in rev yummy anyway tho
