### ISSUE TITLE
 [Ashenvale Warsong lumber camp] Stuck in combat

### ISSUE THREAD

**Issue by CiriusDrayke** [Atlantiss/NetherwingBugtracker#1582]
[//]: # (Enclose links to things related to the bug using http://wowhead.com or any other TBC database.)
[//]: # (You can use screenshot ingame to visual the issue.)
[//]: # (Write your tickets according to the format:)
[//]: # ([Quest][Azuremyst Isle] Red Snapper - Very Tasty!)
[//]: # ([NPC] Magistrix Erona)
[//]: # ([Spell][Mage] Fireball)
[//]: # ([Npc][Drop] Ghostclaw Lynx)
[//]: # ([Web] Armory doesnt work)

**Description**: 
Stuck in combat forest song ashenvale

**Current behaviour**:
I think the Warsong Peons in warsong lumber camp are bugged.
**Expected behaviour**: 
Disengage once far away enough
**Server Revision**: 
2169

**Comment by aresbrutus** [comment]
Do a `.npc info` while having the specific peon selected. I tested it out for a bit and couldn't find an issue.

**Comment by aresbrutus** [comment]
Still unable to recreate. Can you perhaps record a video of this?

**Comment by aresbrutus** [comment]
https://gfycat.com/SpeedyConcreteAndalusianhorse

https://gfycat.com/ImmediateSafeDipper

Confirmed. Might be related to their ranged attack? @Wolffenstein

**Comment by Tereneckla** [comment]
Fixed
