### ISSUE TITLE
Random Damange (possibly drowning?) when fighting mobs inside duskwood building

### ISSUE THREAD

**Issue by Notmittz** [Atlantiss/NetherwingBugtracker#1583]
https://youtu.be/fKpPYuyh1es

**Description**: 
When I engage in combat inside the building (coordinates of 65.45, 67.58), after a few seconds my character will start to take massive amounts of damage as if I'm drowning.  Nothing shows up on the combat logs showing what I am taking damage from.

Fighting the mobs outside doesn't trigger this.

Pulling a mob from the inside to the outside doesn't trigger this.

Leaving the house after I trigger this doesn't stop the damage either, the damage only stops once I'm dead.

Logging in and out doesn't fix the problem.

**Server Revision**: 
[2170][Core]

**Comment by Shanghi** [comment]
Your pet screeched, which made the invisible high level [Unseen](https://www.wowhead.com/npc=3094/unseen) (3094) angry.

The bug would be that it doesn't show its attacks in the combat log, but I'm not sure if it should because it seemed to change constantly. A 1.11.2 comment says it does. A 2.3 comment says it doesn't. A 2.3.3 comment says it does again. A 5.2 comment says it doesn't any more!

**Comment by Evolvee** [comment]
I dont get why there are these "Unseen" either.. none who isnt hardcore RP roleplayer will know about such thing and it will look like the server is shit -.-

Well, closing for now.

**Comment by Evolvee** [comment]
btw @Shanghi https://github.com/Atlantiss/AtlantissTBCBT/issues/3557 maybe this is the problem?

**Comment by Shanghi** [comment]
No, you're supposed to be able to hit these with AOE so it's ok. I have no idea about how those others should work though! The only problem here is whether or not their attacks should be seen in the combat log. Their death always should be, but it seems the attack part kept changing randomly throughout patches.

**Comment by Notmittz** [comment]
oh wow, I had completely forgotten about the hidden mobs here!  Ok yeah, my bad
