### ISSUE TITLE
Deep wounds

### ISSUE THREAD

**Issue by Mewmewww** [Atlantiss/NetherwingBugtracker#1585]
[//]: # (Enclose links to things related to the bug using http://wowhead.com or any other TBC database.)
[//]: # (You can use screenshot ingame to visual the issue.)
[//]: # (Write your tickets according to the format:)
[//]: # ([Quest][Azuremyst Isle] Red Snapper - Very Tasty!)
[//]: # ([NPC] Magistrix Erona)
[//]: # ([Spell][Mage] Fireball)
[//]: # ([Npc][Drop] Ghostclaw Lynx)
[//]: # ([Web] Armory doesnt work)

**Description**: 
Deep wounds tooltip: Your critical strikes cause the opponent to bleed, dealing 60% of your melee weapon's average damage over 12 seconds
**Current behaviour**:
I'm not sure, but according to the tooltip, all critical strikes dealt by you will cause the opponent to bleed but will make the bleed damage equivalent to 60% of your melee weapon's average damage. Does this mean that ranged attacks, i.e bows/guns should also proc it? If so, then this doesn't work.
**Expected behaviour**: 
I assume ranged attacks should be able to proc deep wounds too?
**Server Revision**: 
2169

**Comment by Easyfraggy** [comment]
Ranged attacks do not proc it.

**Comment by Easyfraggy** [comment]
Need mountains of evidence to consider this. It's not even a big deal, noone uses gun/bow while dpsing and tanks dont use deep wounds.

**Comment by Mewmewww** [comment]
@Easyfraggy 
Messaged you on discord - I do agree with you in that DPSing in PvE is irrelevant with bows/guns, but in PvP, this does make a huge difference since it procs your own weapon damage, and versus mages, you do use it alot once frostnovaed

**Comment by Easyfraggy** [comment]
I still think it's wrong, but lets see if someone has any info.

**Comment by Mewmewww** [comment]
No problem 👍

**Comment by Firroth** [comment]
Well people say it should proc from all, but (not from thunderclap only?) 
https://www.mmo-champion.com/threads/623902-Question-Deep-Wounds

**Comment by Easyfraggy** [comment]
WOTLK changed how deep wounds works entirely, so can't use wotlk comments as source.

**Comment by Firroth** [comment]
WoTLK only changed mechanic to cumulating dmg from crits, before all ticks went off. It's in the patch notes I guess.

**Comment by Easyfraggy** [comment]
![image](https://user-images.githubusercontent.com/36134067/46917136-9a5a9480-cfc3-11e8-82cf-bec3bd70c8d4.png)

**Comment by Firroth** [comment]
Seems like it. 
https://github.com/TrinityCore/TrinityCore/issues/20148

So it works fine. You can close this one I guess.

**Comment by Mewmewww** [comment]
Direct post to easy in discord
I don't think this works as intended - @Firroth 

Deep wounds
https://github.com/azerothcore/azerothcore-wotlk/issues/962
Requires Melee Weapon - If you crit unarmed with spells like pummel, no crit will apply
Pummel is a no-weapon required spell, doesn't crit without weapon - testing to see if it crits w/ weapon - it worked: https://imgur.com/a/65n0gXl

According to the github - "deep wounds" requires melee weapon. but only for it to be equipped so it can DO the MELEE damage. As you can see, it will always do 47 damage as thats 60% of my weapons average damage.

Common sense dictates that, if pummel, an unarmed spell that can apply/refresh deep wounds and that only requires melee weapon to be equipped, who dictates that ranged attacks won't be able to as well, as long as the melee weapon is equipped?
https://github.com/TrinityCore/TrinityCore/issues/20148 - No real answer, but I've just tested it here.

**Comment by Firroth** [comment]
It's like you said with pummel, but unarmed skill is counted towards "fist weapon" either way (bare fists, or weapon fists) deal physical dmg and are type of "meele". Bow/Gun/Thrown are counted as "ranged weapon" that deal "physical damage" but aren't meele. Same goes for thunder clap it's physical dmg, but doesn't proc deep wounds on targets who got crit by it.

**Comment by Mewmewww** [comment]
> It's like you said with pummel, but unarmed skill is counted towards "fist weapon" either way (bare fists, or weapon fists) deal physical dmg and are type of "meele". Bow/Gun/Thrown are counted as "ranged weapon" that deal "physical damage" but aren't meele. Same goes for thunder clap it's physical dmg, but doesn't proc deep wounds on targets who got crit by it.

I don't quite know what you mean. Pummel or unarmed doesn't proc deep wounds on crit, but when I do have a 2hander equipped, pummel will proc it. It would only make sense that the same would happen w/ ranged.

**Comment by SwiftieTBC** [comment]
Good ways to check would be to watch old onyxia videos and see if deep wounds is proced during her air phase.
Ive watched a few videos and im almost 100% sure that it doesnt proc on ranged autos
https://www.youtube.com/watch?v=2fCMUPEpZV4 is a good example multiple procs on ground phase and not a single proc during air phase

**Comment by Mewmewww** [comment]
https://www.youtube.com/watch?v=2fCMUPEpZV4
3:29 deep wound proc, no?

**Comment by Firroth** [comment]
I would say it's still from meele attack, there is one place where you can attack her while she is in the air as meele. This video even should prove it, since she is in the air and has refreshed rend and rupture meaning they get range to use those skills.

https://www.youtube.com/watch?v=A7zChHjvrYI

**Comment by Mewmewww** [comment]
:peepoSad:

**Comment by Easyfraggy** [comment]
Closed again, can't see any proof this should be the case.
