### ISSUE TITLE
[NPC] Silithid Grub stuck in texture

### ISSUE THREAD

**Issue by totaemoeggerli** [Atlantiss/NetherwingBugtracker#1587]
[//]: # (Enclose links to things related to the bug using http://wowhead.com or any other TBC database.)
[//]: # (You can use screenshot ingame to visual the issue.)
[//]: # (Write your tickets according to the format:)
[//]: # ([Quest][Azuremyst Isle] Red Snapper - Very Tasty!)
[//]: # ([NPC] Magistrix Erona)
[//]: # ([Spell][Mage] Fireball)
[//]: # ([Npc][Drop] Ghostclaw Lynx)
[//]: # ([Web] Armory doesnt work)

**Description**: 
Silithid Grub stuck in texture
Barrens 44/72

**Current behaviour**:
![grub](https://imgur.com/qDRIYfL.jpg)

**Expected behaviour**: 
Silithid Grub shouldn't be stuck in texture

**Server Revision**: 2169

**Comment by aresbrutus** [comment]
Fixed in rev `Tycho`.
