### ISSUE TITLE
[Quest]Inoculation

### ISSUE THREAD

**Issue by paoea** [Atlantiss/NetherwingBugtracker#1589]
[//]: # (Enclose links to things related to the bug using http://wowhead.com or any other TBC database.)
[//]: # (You can use screenshot ingame to visual the issue.)
[//]: # (Write your tickets according to the format:)
[//]: # ([Quest][Azuremyst Isle] Red Snapper - Very Tasty!)
[//]: # ([NPC] Magistrix Erona)
[//]: # ([Spell][Mage] Fireball)
[//]: # ([Npc][Drop] Ghostclaw Lynx)
[//]: # ([Web] Armory doesnt work)

**Description**: 
The Quest (https://www.wowhead.com/quest=9303/inoculation) Inoculation doesn't work right anymore.
When I did this quest 2 weeks ago, everything was fine.
**Current behaviour**:
When you use the Inoculating Crystal, nothing happens but when you kill a Nestlewood Owlkin you get 1 point for the quest.
**Expected behaviour**: 
Should only give credit for the quest if you use the crystal.
**Server Revision**:

**Comment by Evolvee** [comment]
cpps... the source of all evil on this world

**Comment by tcberk12** [comment]
#713

**Comment by Fenvarien1** [comment]
![quest worked for one owl](https://i.imgur.com/6QcxTHd.jpg)

i just found this bugged quest but was very suprised by the last mob here. it seems to be working on this owl. but 5/6 didnt.

**Comment by Tenoutoften** [comment]
* Having your channel interrupted and killing the mob doesn't give quest credit, seen [here](https://youtu.be/pGiWRvY8ut0?t=38)
* Completing a channel will instantly give credit & [[NPC]Nestlewood Owlkin#16518](https://www.wowhead.com/npc=16518/nestlewood-owlkin) transforms into [[NPC]Inoculated Nestlewood Owlkin#16534](https://www.wowhead.com/npc=16534/inoculated-nestlewood-owlkin) and does emote "The Inoculated Nestlewood Owlkin nods appreciatively."

**Comment by Easyfraggy** [comment]
Are you saying this quest is working correctly @Tenoutoften ?

**Comment by WhyAintThisFixedYet** [comment]
Using the item Inoculating crystal on the neutral Owlkin does not inoculate them or provide a credit towards the quest. 

You can get credit for the quest by killing them. Upon using the crystal on them, they should transform into an inoculated Owlkin, perform an emote, and provide a credit towards the quest.

**Comment by WhyAintThisFixedYet** [comment]
After testing all of the Owlkin in the area, only 2 of them are shown to be working. Unsure if they provide credit or not as the quest was completed through killing them before I found the working ones.

**Comment by Wolffenstein** [comment]
Fixed in rev 2401. Remember to remove the quest from your log, logout and delete cache.
