### ISSUE TITLE
[Quest][Desolace] Khan Hratha - missing RP

### ISSUE THREAD

**Issue by Firroth** [Atlantiss/NetherwingBugtracker#1590]
[Quest][Desolace] [Khan Hratha](http://wowwiki.wikia.com/wiki/Quest:Khan_Hratha_(Gelkis))

**Current behaviour**:

- Missing RP text, after using Quest Item and during waves.
- Summons waves near your position (where you used q item) boss included.

**Expected behaviour**: 

- There should be "yell" message, after you used Q item to start the event, and when new wave spawned.
- When quest item have been used to summon waves, they should be spawning and running from down the hill up to your position.

How it should work can be seen here (quality is bad, can only see how event should work. Can see text also "yell" that it was used, but can't read it.)
https://www.youtube.com/watch?v=mxGgcYNmcmY

**Server Revision**: 
2169

**Comment by Evolvee** [comment]
https://github.com/Atlantiss/AtlantissTBCBT/issues/2647
