### ISSUE TITLE
[NPC] Grimtotem Raider

### ISSUE THREAD

**Issue by Mewmewww** [Atlantiss/NetherwingBugtracker#1591]
[//]: # (Enclose links to things related to the bug using http://wowhead.com or any other TBC database.)
[//]: # (You can use screenshot ingame to visual the issue.)
[//]: # (Write your tickets according to the format:)
[//]: # ([Quest][Azuremyst Isle] Red Snapper - Very Tasty!)
[//]: # ([NPC] Magistrix Erona)
[//]: # ([Spell][Mage] Fireball)
[//]: # ([Npc][Drop] Ghostclaw Lynx)
[//]: # ([Web] Armory doesnt work)

**Description**: 
Uses a net ability that lasts 9 seconds
**Current behaviour**:
The net lasts 9 seconds, but as the 9 seconds have dissipated, it will recast it immediately after, not allowing me to move
**Expected behaviour**: 
Maybe there should be a cooldown?
**Server Revision**: 
2169

**Comment by Evolvee** [comment]
rev Block
