### ISSUE TITLE
Hunter's wolf Furious Howl

### ISSUE THREAD

**Issue by lemongr** [Atlantiss/NetherwingBugtracker#1592]
[//]: # (Enclose links to things related to the bug using http://wowhead.com or any other TBC database.)
[//]: # (You can use screenshot ingame to visual the issue.)
[//]: # (Write your tickets according to the format:)
[//]: # ([Quest][Azuremyst Isle] Red Snapper - Very Tasty!)
[//]: # ([NPC] Magistrix Erona)
[//]: # ([Spell][Mage] Fireball)
[//]: # ([Npc][Drop] Ghostclaw Lynx)
[//]: # ([Web] Armory doesnt work)

**Description**: 
Wolves and Furious Howl
**Current behaviour**:
There is a problem with this ability, the wolves are constantly throwing it (immediately after finishing), and the skill stops feeding the animals.

When i use Feed Pet (on wolf), he cast Furious Howl and disrupting the feeding.
**Expected behaviour**: 

**Server Revision**:

**Comment by Easyfraggy** [comment]
Can someone elaborate? I don't understand what feeding has to do with this ability.
