### ISSUE TITLE
[Zul'Farrak] Pyramid Event

### ISSUE THREAD

**Issue by Azalen** [Atlantiss/NetherwingBugtracker#1593]
**Current behaviour**:
Mobs that spawn for the event don't reward EXP.

**Expected behaviour**: 
They should. Normal exp for normal/elite mobs.
Proof: https://www.youtube.com/watch?v=tUcBCeTqAKU
(I know the video is bad but you can clearly see purple blurred text in the middle granting exp, all other videos are from lvl 60's :D)

**Server Revision**: 
[2175]

**Comment by Firroth** [comment]
#1528 was rev yummy implemented yet?

**Comment by Evolvee** [comment]
https://github.com/Atlantiss/NetherwingBugtracker/issues/1945
