### ISSUE TITLE
[Zul'Farrak] Dismounting Shot

### ISSUE THREAD

**Issue by Azalen** [Atlantiss/NetherwingBugtracker#1594]
**Description**: 
https://classicdb.ch/?spell=18395

**Current behaviour**:
Not dismounting. See combat log.
![wowscrnshot_101418_200545](https://user-images.githubusercontent.com/20336567/46920355-6c8a4580-cfed-11e8-82fc-b1422f008a70.jpg)

**Expected behaviour**: 
Should dismount the player.

**Server Revision**: 
[2175]

**Comment by Firroth** [comment]
#1528 was rev_yummy implemented yet?

**Comment by Wolffenstein** [comment]
It was

**Comment by Tereneckla** [comment]
Dismounting Shot does not dismount yet.

**Comment by Godmatik** [comment]
It works, can close
