### ISSUE TITLE
[NPC]  All in Pyrewood Village Damage/Health Like Non-Elites

### ISSUE THREAD

**Issue by Ceago** [Atlantiss/NetherwingBugtracker#1595]
**Description**:  The NPC's in Pyrewood Village show as elite but deal damage similar to the non elite mobs in the zone and have about the same health.  

**Current behaviour**:  The mobs all have similar health pools and damage to the non elite mobs in the immediate area around the village.  Can easily take on 2 or 3 as a level 20.

**Expected behaviour**:   From memory this quest should still be a group quest in TBC.  From the Ten Ton Hammer quest guide for silverpine from 2006 it also references this as being a group quest.  Even though I am level 20 the mobs should be more of a challenge.  http://www.tentonhammer.com/guides/silverpine-forest-guide-b4373623-edc8-43a0-afe4-9cd059a18d9d

**Server Revision**: 2177

**Comment by Easyfraggy** [comment]
![image](https://user-images.githubusercontent.com/36134067/46920391-d4409080-cfed-11e8-9018-4907c9f695fa.png)

**Comment by Evolvee** [comment]
rev Block
