### ISSUE TITLE
[Item]Long Elegant Feather#4589 probably too low drop chance on certain NPCs

### ISSUE THREAD

**Issue by Tenoutoften** [Atlantiss/NetherwingBugtracker#1597]
**Description**: 
[[Item]Long Elegant Feather#4589](https://www.wowhead.com/item=4589/long-elegant-feather#comments) probably has a too low drop chance on these NPCs, but potentially more(I killed roughly 60 and got zero.):

[[NPC]Frayfeather Stagwing#5304](https://db.excalibur.ws/?npc=5304)
[[NPC]Frayfeather skystormer#5305](https://db.excalibur.ws/?npc=5305)

-----------------------------

 There are several comments on wowhead on the [[Quest]Another message to the Wildhammer#7842](https://www.wowhead.com/quest=7842/another-message-to-the-wildhammer) and the item itself, [[Item]Long Elegant Feather#4589](https://www.wowhead.com/item=4589/long-elegant-feather#comments) indicating a higher drop chance:
![6cdd065a6b916d57439d71885e816d3c](https://user-images.githubusercontent.com/34839199/46920777-78790600-cff3-11e8-8cb1-5eb71dfdcea6.png)
![9f7d56e26a9c53a71230689ade4611cf](https://user-images.githubusercontent.com/34839199/46920778-78790600-cff3-11e8-9d1d-ff38f2a3ad13.png)
![1915b605ee4f150526a0d6ecd5f98332](https://user-images.githubusercontent.com/34839199/46920779-78790600-cff3-11e8-8d89-5d463b0931ca.png)
![2585aa76b6d0a200475598c88aa8ca55](https://user-images.githubusercontent.com/34839199/46920780-79119c80-cff3-11e8-8a42-31ca9efa1379.png)
![ab4788fbb503f4a5028d60f8928f67b8](https://user-images.githubusercontent.com/34839199/46920781-79119c80-cff3-11e8-91c9-3832e1ff9a2f.png)

**Expected behaviour**: 
Expect to get more than 1x [[Item]Long Elegant Feather#4589](https://www.wowhead.com/item=4589/long-elegant-feather#comments) after killing 60 NPCs.

**Server Revision**: 
2175

**Comment by wtRCH** [comment]
@aresbrutus

**Comment by aresbrutus** [comment]
@Shanghi global loot issue again. I can manually add it to the required mobs but I am not sure how clean that would be compared to fixing it via global loot.

**Comment by Shanghi** [comment]
It's not global loot, but I'm not sure they should have long elegant feathers! The [Frayfeather Hippogryph](https://www.wowhead.com/npc=5300/frayfeather-hippogryph) (5300) certainly should and already drops them, but I can't find anything showing that the [Frayfeather Stagwing](https://www.wowhead.com/npc=5304/frayfeather-stagwing) (5304) or [Frayfeather Skystormer](https://www.wowhead.com/npc=5305/frayfeather-skystormer) (5305) have them after checking old Wowhead, new Wowhead, Thottbot, Allakhazam, and wowwiki.

**Comment by Tenoutoften** [comment]
It's strange if no drop is recorded because a lot of the comments say that all kinds of hippogryphs in Feralas drop them

**Comment by Shanghi** [comment]
I think they just meant the specific "Frayfeather Hippogryph" instead of general hippogryphs.
![image](https://user-images.githubusercontent.com/2672633/46921624-a5b1be00-cfcb-11e8-80b8-5fa25b660a14.png)

I guess the other 2 kinds just aren't as beautiful!

**Comment by aresbrutus** [comment]
Right yeah my bad. I didn't even check the related mobs, I just assumed there was some issue with drops since none-quest item needed for a quest. Closing it then.
