### ISSUE TITLE
[Zone] [Quest] [Spell] [NPC] [Core] Razormaw's Terrifying Roar can cause players to clip through terrain/fall to death

### ISSUE THREAD

**Issue by Spaztick** [Atlantiss/NetherwingBugtracker#1599]
**Description**: 
Razormaw's Terrifying Roar on Bloodmyst Isle can cause players to clip through terrain/fall to death.

**Current behaviour**:
Bad.

**Expected behaviour**: 
Not bad.

**Server Revision**: 
Make bad good.

**Comment by wtRCH** [comment]
Confirmed by me, I was there when it happened

**Comment by The14me** [comment]
Cant reproduce,tested every possible spot.Please re-open if happen again or can reproduce it.
