### ISSUE TITLE
[Warrior] No rage gain from attacking Critters

### ISSUE THREAD

**Issue by Zirda** [Atlantiss/NetherwingBugtracker#16]
**Current behaviour**:
Attacking Critters (Tested on Rabbits in Coldrigde Valley) gives no rage. Same behaviour with critical strikes.

**Expected behaviour**: 
Rage from dealing damage should be given even when the target is a critter.

**Comment by Evolvee** [comment]
https://github.com/Atlantiss/AtlantissTbcBTOLD/issues/110

**Comment by Wolffenstein** [comment]
Fixed in rev 2020.
