### ISSUE TITLE
[Rogue] eviscerate misses lose combo points

### ISSUE THREAD

**Issue by DarthNekr0s** [Atlantiss/NetherwingBugtracker#160]
**Description**:  not entirely sure if this was how its supposed to work on tbc, i know definitely later its wrong, but it doesnt seem right that if your eviscerate misses then you also loose your combo points. parries/dodges dont behave like this and youre able to retain your cp on mobs and try again, but misses clears them

**Current behaviour**: when finishing move eviscerate misses, combo points are lost

**Expected behaviour**:  combo points should be retained

**Server Revision**:

**Comment by wowthings** [comment]
Can confirm, it happens with druids when I miss a Rip

**Comment by Easyfraggy** [comment]
Duplicate: https://github.com/Atlantiss/NetherwingBugtracker/issues/77
