### ISSUE TITLE
[NPC][Movement]Cursed Sycamore#5881 / Wandering Forest Walker#7584 not patroling

### ISSUE THREAD

**Issue by Tenoutoften** [Atlantiss/NetherwingBugtracker#1600]
**Description**: 
[NW video](https://www.youtube.com/watch?v=UczFdqMhGoc&feature=youtu.be) with .gps & .npc info
![192c582b99508c3c535052ec609d617e](https://user-images.githubusercontent.com/34839199/46937484-b3b21e00-d061-11e8-803d-c74191828a28.png)
![506e9f8b8b146a7fdcebe6d66384f7cf](https://user-images.githubusercontent.com/34839199/46937527-cd536580-d061-11e8-9482-98ffa41582d7.png)

Currently stands still.

[[NPC]Cursed Sycamore#5881](https://www.wowhead.com/npc=7584/wandering-forest-walker#comments)
[[NPC]Wandering Forest Walker#7584](https://www.wowhead.com/npc=5881/cursed-sycamore#comments)

**Expected behaviour**: 
Expected to patrol based on wowhead comment & common sense.

**Server Revision**: 
2177

**Comment by Evolvee** [comment]
probably due to shared spawns

**Comment by aresbrutus** [comment]
Fixed in rev `Ilus`.
