### ISSUE TITLE
[Druid, Cat Form] Feral Swiftness talent occasionally not reactivating. 

### ISSUE THREAD

**Issue by Dosdaltherir** [Atlantiss/NetherwingBugtracker#1601]
**Description**: 
The Feral Combat talent "Feral Swiftness"(30 % movement speed while outdoors in Cat Form) will occasionally not grant the 30% increase in movement speed after leaving indoor areas, or after the duration of the ability "Dash" runs out. 
**Current behaviour**:
The 30 % increase in movement speed from the Feral Combat talent "Feral Swiftness" occasionally doesn't reactivate when the above mentioned requirements are met. 
**Expected behaviour**: 
The Feral Combat talent "Feral Swiftness" should grant the 30 % speed bonus whenever the druid reenters outdoor areas, or whenever "Dash" fades, without having to leave and reenter Cat Form. 
**Server Revision**: 
Rev: 2177.

**Comment by kemotix** [comment]
Also happens after leaving Prowl.

**Comment by Wolffenstein** [comment]
Fixed in rev 2207.
