### ISSUE TITLE
([Hunter, Pet] Naming issues

### ISSUE THREAD

**Issue by Rebelyna** [Atlantiss/NetherwingBugtracker#1602]
**Current behaviour**:
Not able to give my hunter pet the name "Alyx". It says I cannot use specific characters.
Was able to give it the name "Baso". Is it maybe because a character on this account is also named Alyx?

**Expected behaviour**: 
You should be able to give a hunter pet any name with the allowed characters.

**Server Revision**: 
2177

**Comment by Rebelyna** [comment]
Retested with another pet, also not able to name it Alyx, also not able to name it Rebelyna, which is another name of a character on my account. Was able to name it Rebelina though. So it is either character names on your account or names with a "y" in it.

**Comment by Easyfraggy** [comment]
Not a bug.

**Comment by Easyfraggy** [comment]
To clarify for future - you cannot name your pet after other players.
