### ISSUE TITLE
[Core][Warrior] Sweeping Strikes and Bloodthirst

### ISSUE THREAD

**Issue by Firroth** [Atlantiss/NetherwingBugtracker#1604]
[Spell][Warrior] [Sweeping Strikes](http://wowwiki.wikia.com/wiki/Sweeping_Strikes)
[Spell][Warrior] [Bloodthirst](https://vanilla-twinhead.twinstar.cz/?spell=23881)

**Current behaviour**:
Bloodthirst doesn't work with Sweeping Strike. 
Tested it in Scarlet Monastery:
- Pulled 3 targets.
- Used Sweeping Strikes.
- Bloothirst Critted for around 900. (60-70% of mobs hp).
- Checked hp of other mobs which should (1 of them) take dmg from this hit too for the same amount. None of them did, they were above 85% hp, while the one which took crit were below 10%.

**Expected behaviour**: 
When Sweeping Strike is active, it should also deal damage to second target from Bloodthirst for full amount. 

Offtopic: It does work with execute when both are below 20% hp, and deals full damage. So in this case it should be like that too.

**Server Revision**: 
2177

**Comment by Kidcudi123** [comment]
Sweeping strikes currently 50% from everything on off target, auto hits aswell

**Comment by killablink** [comment]
Sweeping strikes still not doing full damage. When you crit, the dmg transfered should also be that dmg crit value (sweeping strikes itself doesn't crit, but if you crit your first mob for 1100, it should deal 1400 dmg to the other target)
![image](https://user-images.githubusercontent.com/43510874/49295047-b9818880-f482-11e8-8033-2cf0eea4928a.png)

**Comment by teddys** [comment]
it's counting the armor of the target that should be hit by the cleft attack .. which is incorrect
if you hit for 1k, the cleft target should get hit for 1k as well ... armor doesn't apply in this case

**Comment by Easyfraggy** [comment]
Not at all true teddys.

It is doing exactly half damage atm - not doubledip on armor and what you are saying about it only using main target armor is also wrong. 

It uses raw damage and then calculates dmg based on each targets individual armor.
