### ISSUE TITLE
[Dungeon] Scarlet Monastery - Library Side

### ISSUE THREAD

**Issue by Firroth** [Atlantiss/NetherwingBugtracker#1605]
# <h1>[NPC] Scarlet Gallant 4287, GUID 42995 </h1>

**Current behaviour**:
Rather than stand in place, he wanders near his place.

![screenshot_1](https://user-images.githubusercontent.com/43505196/46946255-7193d700-d077-11e8-8080-5f2b65c9f9ae.png)

**Expected behaviour**: 
Should stand still in his place, just like other one from other side.

**Server Revision**: 
2177

# <h1>[NPC] Scarlet Chaplain 4299</h1>

https://web.archive.org/web/20080617120030/http://wow.allakhazam.com:80/db/mob.html?wmob=4299

**Current behaviour**:

- He uses [Spell] Power Word Shield [6066], far too late and doesn't use it on allies.
- He doesn't use [Spell] Smite [6060]
- He doesn't use [Spell] Holy Fire [15264]
- He doesn't use [Spell] Dispel Magic [988] (had scrolls on myself, which are magic effects)

**Expected behaviour**: 

- He should use [Spell] Power Word Shield [6066], on enter combat, and during combat every 15-20s, on self or ally (on the one who has the least hp).
- He should use [Spell] Smite [6060], every few seconds.
- He should use [Spell] Holy Fire [15264] every few seconds on random target.
- He should use [Spell] Dispel Magic [988] every 10s or so to dispel beneficial spell from enemy, or harmfull spell from ally.

**Server Revision**: 
2177

# <h1>Missing Npc's </h1>

**Current behaviour**:

Missing group of 2-3 random npc's (monk/chaplain/diviner) in gps coords. (situated near the benches)

**Expected behaviour**: 

There should be a group of 2-3 random npc's (monk/chaplain/diviner) on these gps cords. (situated near the benches)

![screenshot_3](https://user-images.githubusercontent.com/43505196/46948398-3d6fe480-d07e-11e8-99a6-f2e23f0d7fe6.png)
![screenshot_4](https://user-images.githubusercontent.com/43505196/46948412-4791e300-d07e-11e8-8d69-40761a664a96.png)
![screenshot_4](https://user-images.githubusercontent.com/43505196/46948528-b707d280-d07e-11e8-9e3f-d4bfb84ac441.png)
![screenshot_5](https://user-images.githubusercontent.com/43505196/46948531-b8d19600-d07e-11e8-84ca-d22a39aa8eab.png)
![screenshot_6](https://user-images.githubusercontent.com/43505196/46948655-1b2a9680-d07f-11e8-865f-f765d7ca9a28.png)
![screenshot_7](https://user-images.githubusercontent.com/43505196/46948656-1bc32d00-d07f-11e8-9d12-fb49fd749c69.png)

**Server Revision**: 
2177

**Comment by Evolvee** [comment]
rev Block
