### ISSUE TITLE
[Druid, Shapeshifting Cat Form]

### ISSUE THREAD

**Issue by Veeli** [Atlantiss/NetherwingBugtracker#1606]
[//]: # (Enclose links to things related to the bug using http://wowhead.com or any other TBC database.)
[//]: # (You can use screenshot ingame to visual the issue.)
[//]: # (Write your tickets according to the format:)
[//]: # ([Quest][Azuremyst Isle] Red Snapper - Very Tasty!)
[//]: # ([NPC] Magistrix Erona)
[//]: # ([Spell][Mage] Fireball)
[//]: # ([Npc][Drop] Ghostclaw Lynx)
[//]: # ([Web] Armory doesnt work)

**Description**: 
When you Shapeshift into any form, the actionbar should switch
**Current behaviour**:
Sometimes when you switch to the cat form, the action bar of the caster form remains visible, but the action bar of the cat form is used
**Expected behaviour**: 

**Server Revision**:

**Comment by Easyfraggy** [comment]
Possibly addon issue. Make sure you aren't using any bar addons and retest.

**Comment by Veeli** [comment]
Jeah didnt thought of it. youre right! tested it and it was gone. My bad with that
