### ISSUE TITLE
[Warrior] [Spell] Improved Thunderclap talent does not actually improve the debuff on enemies.

### ISSUE THREAD

**Issue by lancer1st** [Atlantiss/NetherwingBugtracker#1607]
**Description**: 
Having the Improved Thunderclap affects the tooltip on the thunderclap ability but does not affect mob´s debuff after youve used it.
**Current behaviour**:
Using Thunderclap while having any ammount of talent points in Improved Thunderclap does not improve the debuff on mobs affected by it but instead stays on the default 10% increased time between attacks.
**Expected behaviour**: 
Once gaining atleast a single rank of improved Thunderclap and use the thunderclap ability near an enemy he should get a debuff decreasing his attack speed according to the rank (14%,17% and 20%
**Server Revision**: 
2177

**Comment by Easyfraggy** [comment]
Tooltips are client side, tooltip will never reflect talent improvements, same goes for blessings, improved spirit buff etc. Are you sure that the mob isn't slowed additionally?

**Comment by lancer1st** [comment]
> Tooltips are client side, tooltip will never reflect talent improvements, same goes for blessings, improved spirit buff etc. Are you sure that the mob isn't slowed additionally?

The tooltip improves with the talents but the actuall debuff does not.
![thunderclap](https://user-images.githubusercontent.com/42695368/46952731-01438080-d08c-11e8-88af-4437609cf1c7.png)

**Comment by Easyfraggy** [comment]
The tooltip of your thunderclap aka the debuff on the mob is client side will not update according to your talents. Theres nothing any server can do to change that other than writing a custom client that does it that you have to download.
