### ISSUE TITLE
[Quest] Find OOX - Hinterlands one

### ISSUE THREAD

**Issue by Mewmewww** [Atlantiss/NetherwingBugtracker#1608]
[//]: # (Enclose links to things related to the bug using http://wowhead.com or any other TBC database.)
[//]: # (You can use screenshot ingame to visual the issue.)
[//]: # (Write your tickets according to the format:)
[//]: # ([Quest][Azuremyst Isle] Red Snapper - Very Tasty!)
[//]: # ([NPC] Magistrix Erona)
[//]: # ([Spell][Mage] Fireball)
[//]: # ([Npc][Drop] Ghostclaw Lynx)
[//]: # ([Web] Armory doesnt work)

**Description**: 
Chicken needs to assist and fight those who come to ambush it.
**Current behaviour**:
Doesn't assist or attack ambushers
**Expected behaviour**: 
Ambushers should fight the chicken and the chicken vice versa
**Server Revision**: 
2177

**Comment by Easyfraggy** [comment]
https://github.com/Atlantiss/NetherwingBugtracker/issues/970
