### ISSUE TITLE
[Quest][Thousand Needles] Arikara

### ISSUE THREAD

**Issue by Galawer** [Atlantiss/NetherwingBugtracker#1609]
**Description**: 
[Quest](https://db.excalibur.ws/?quest=5088), [Object](https://db.excalibur.ws/?object=175944), [Item](https://db.excalibur.ws/?item=12785), [NPC](https://db.excalibur.ws/?npc=10882)

**Current behaviour**:
Nothing happens when you light the fire.

**Expected behaviour**: 
You're supposed to get quest credit for lighting the fire and Arikara should spawn.

**Server Revision**: 
2177

**Comment by Easyfraggy** [comment]
https://github.com/Atlantiss/NetherwingBugtracker/issues/1127

**Comment by Easyfraggy** [comment]
Possible addon problem? Worked fine for others.

**Comment by Galawer** [comment]
Doesn't work with or without addons. I click the fire, the cast goes off, the fire starts burning, but then nothing happens.
I've tried in a bunch of different positions, using the item from the inventory instead of clicking the fire and nothing goes.

**Comment by Modzel93** [comment]
Quest still don't work

**Comment by Evolvee** [comment]
because rev Block is not applied on server yet

**Comment by MacaWilly** [comment]
Having issues with this bug again on live.

**Comment by Evolvee** [comment]
What is the issue?

**Comment by The14me** [comment]
Arikara cant be summoned again. Rev: 2678

**Comment by Evolvee** [comment]
works fine for me

![image](https://user-images.githubusercontent.com/1942409/51614794-b5279800-1f26-11e9-83df-e1bcd72f1856.png)
