### ISSUE TITLE
[Dungeon] Scarlet Monastery - Armory

### ISSUE THREAD

**Issue by Firroth** [Atlantiss/NetherwingBugtracker#1610]
# <h1>Missing few spawns of [NPC] [Scarlet Conjuror](https://web.archive.org/web/20080620084020/http://wow.allakhazam.com:80/db/mob.html?wmob=4297) </h1>

**Current behaviour**:
There is only 1 [NPC] [Scarlet Conjuror](https://web.archive.org/web/20080620084020/http://wow.allakhazam.com:80/db/mob.html?wmob=4297) in the first open room. Meaning there are some missing spawns in the area.

**Expected behaviour**: 
There should be more of [NPC] [Scarlet Conjuror](https://web.archive.org/web/20080620084020/http://wow.allakhazam.com:80/db/mob.html?wmob=4297) in the first room. Can be seen on the video.
1 Conjuror always has 1 Fire elemental near him, on the video you can see more than 3 elementals, meaning more than 1 conjuror is there.

https://www.youtube.com/watch?v=fTYvq1dPUjk

**Server Revision**: 
2177

# <h1>[NPC] Scarlet Protector - [Spell] Devotion Aura [8258]</h1>

[Spell] [Devotion Aura](https://www.wowhead.com/spell=8258/devotion-aura) 

**Current behaviour**:
[Spell] [Devotion Aura](https://www.wowhead.com/spell=8258/devotion-aura)  doesn't spread among other friendly targets of this NPC. 

- They gain this effect only when you enter combat with them and he "uses it". They gain it only then.
- If you pull other mob from the pack which is linked to him, this mob won't get aura from protector (range issue?)
- if you pull pack and he uses devotion aura, linked to him mobs will either gain aura or not in some cases. Let's assume they got it, and you went and pulled 1 more pack where there is no protector in it. This new pack should also gain aura if they are in range of the protector, but they do not gain it.

**Expected behaviour**: 
All friendly NPC's of Scarlet Protector should gain this aura and it's benefits. It was one of the reasons why they were focused first in the kill priority list.

- They should gain this effect if they are in range of it (30y).
- if you pull new pack, new pack also should gain the effect of it if they entered the (30y) range.

**Server Revision**: 
2177

# <h1>[NPC] Scarlet Myrmidon- Flurry [12970]</h1>

https://web.archive.org/web/20080617120025/http://wow.allakhazam.com:80/db/mob.html?wmob=4295

**Current behaviour**:

Does not use/gain effect Flurry [12970].

**Expected behaviour**: 
I guess this should work like in warrior's case - when they crit the enemy they should gain this effect to increase their attack speed. (this spell was removed later from the game, so can't research it what should trigger it. I guess some info can be found in Spell.dbc or other file what should trigger it, since mobs crit on tanks less often or not at all, which would make this spell useless and they could simply use it like other spells on timer.) **Need Research**

**Server Revision**: 
2177

# <h1>[NPC] Scarlet Defender- Intimidating Shout [20511]</h1>

https://web.archive.org/web/20080620084025/http://wow.allakhazam.com:80/db/mob.html?wmob=4298

**Current behaviour**:
They doesn't seem to use [Spell] Intimidating Shout [20511]. Waited like for 1min+ nothing. Brought them down to less than 20% hp still nothing. So my assumption is they don't have it.

**Expected behaviour**: 
They should use [Spell] Intimidating Shout [20511] every 30-40s.

**Server Revision**: 
2177

**Comment by DeltaLoads** [comment]
there are also some pathfinding problems
https://streamable.com/eylj4

**Comment by Evolvee** [comment]
rev Block
