### ISSUE TITLE
[NPC] Stranglehorn Raptor

### ISSUE THREAD

**Issue by Retinus** [Atlantiss/NetherwingBugtracker#1612]
Entry: 685, Id: 8, GUIDLow: 91726

This mob stays still with walking animation and cant be attacked.

**Server Revision**: 2177

**Comment by Retinus** [comment]
Same issue with mob (Panther)

Entry: 736, Id: 5, GUIDLow: 21702

**Comment by Kidcudi123** [comment]
Also seen 2 spawns in EPL (try to find it)

**Comment by Mikik3jr** [comment]
I found another one:
https://youtu.be/w0zzw5IhclE

**Comment by Retinus** [comment]
Same issue with mob (Stranglethorn Tigress)

Entry: 772, Id: 23, GUIDLow: 26264

**Comment by aresbrutus** [comment]
Fixed after rev `2196`
