### ISSUE TITLE
Authenticator not working in game

### ISSUE THREAD

**Issue by GioBego** [Atlantiss/NetherwingBugtracker#1613]
**Description**: 
If I activate authenticator in my account management on web, I cannot log in to the game. It requires authenticator and repeatedly claims I am entering the wrong key.
**Current behaviour**:
Game client is not accepting authenticator key at login
**Expected behaviour**: 
The code should work and allow log me in
**Personal Tip**: 
Maybe problem is, blizzard uses 8 digit athenticator and web auth generates 6 digit code. Client could have a problem with this.

**Comment by ircfelix** [comment]
Is this report real life?
Is it just fantasy?

**Comment by wtRCH** [comment]
We are aware of it. To make it work you have to log in to the game like a second before your auth changes on the app. Then it works.

**Comment by Emtec** [comment]
Fixed
