### ISSUE TITLE
[Quest] Melding of Influences

### ISSUE THREAD

**Issue by Kidcudi123** [Atlantiss/NetherwingBugtracker#1614]
Missing completion

**Comment by netherwingbta** [comment]
The Captured Felwood Ooze merged with the primal ooze and caused the Gargantuan Ooze to appear fine, but the Captured Felwood Ooze did not disappear. It just shrank and stayed there. 
![capturedooze](https://user-images.githubusercontent.com/43872263/47404548-0371a300-d74e-11e8-821f-b690d9541726.jpg)

**Comment by bajkorv** [comment]
For me, the Primal ooze killed the little ooze in 1hit and nothing more happened, had to abandon quest, go back to undercity to repick it up again, not gonna do that. Quest broken please fix so others dont have to run into this

**Comment by Manaci** [comment]
Fixed
