### ISSUE TITLE
[Sunken Temple] Linking

### ISSUE THREAD

**Issue by Azalen** [Atlantiss/NetherwingBugtracker#1616]
### The following mobs/packs aren't linked as of rev 2195

**Altar of Hakkar Ring Room**
![wowscrnshot_102118_205942](https://user-images.githubusercontent.com/20336567/47271850-4e888c00-d57d-11e8-9def-29ba328d7090.jpg)
![wowscrnshot_102118_210112](https://user-images.githubusercontent.com/20336567/47271871-91e2fa80-d57d-11e8-96a2-eabd0e105fbd.jpg)
![wowscrnshot_102118_210253](https://user-images.githubusercontent.com/20336567/47271875-a1624380-d57d-11e8-9e67-4dc6e9df00dd.jpg)

**Troll Miniboss Ring Area**
![wowscrnshot_102118_211526](https://user-images.githubusercontent.com/20336567/47271887-b9d25e00-d57d-11e8-9418-86c11d1f6fda.jpg)
![wowscrnshot_102118_212002](https://user-images.githubusercontent.com/20336567/47271890-c35bc600-d57d-11e8-814f-b824999d29cb.jpg)
![wowscrnshot_102118_212059](https://user-images.githubusercontent.com/20336567/47271891-c8b91080-d57d-11e8-98d4-dff2759fd27e.jpg)
![wowscrnshot_102118_212603](https://user-images.githubusercontent.com/20336567/47271895-d66e9600-d57d-11e8-81ac-122f704b7210.jpg)

**Dragonkin Area**
![wowscrnshot_102118_220228](https://user-images.githubusercontent.com/20336567/47271901-ed14ed00-d57d-11e8-9988-f96455b8d535.jpg)

**Server Revision**: 
[2177] -> [2195]

**Comment by Azalen** [comment]
Updated this with screenshots of all unlinked packs. We tried to do rangepulls only.
@aresbrutus

**Comment by aresbrutus** [comment]
Fixed in rev `Ilus`.
