### ISSUE TITLE
[Sunken Temple] Troll Minibosses

### ISSUE THREAD

**Issue by Azalen** [Atlantiss/NetherwingBugtracker#1617]
**Current behaviour**:
Hukku (https://classicdb.ch/?npc=5715) did not summon his minions.
See this: https://youtu.be/7pFzEpnVTdM?t=33

Zolo (https://classicdb.ch/?npc=5712) summons a totem. The totem (http://classicdb.ch/?spell=12506) was able to move which it shouldnt. 

On a sidenote: not a single one of them dropped loot. Same goes for the four dragons. Maybe worth checking.

Troll Minibosses should drop blue with ~10%.
https://web.archive.org/web/20071029141202/http://wow.allakhazam.com:80/db/mob.html?wmob=5712
https://web.archive.org/web/20071029141207/http://wow.allakhazam.com:80/db/mob.html?wmob=5713
https://web.archive.org/web/20071029141212/http://wow.allakhazam.com:80/db/mob.html?wmob=5714

Dragons with ~35%.
https://web.archive.org/web/20071026024048/http://wow.allakhazam.com:80/db/mob.html?wmob=5721
https://web.archive.org/web/20071026024053/http://wow.allakhazam.com:80/db/mob.html?wmob=5722
https://web.archive.org/web/20071026072717/http://wow.allakhazam.com:80/db/mob.html?wmob=5720
https://web.archive.org/web/20071026072717/http://wow.allakhazam.com:80/db/mob.html?wmob=5719

**Server Revision**: 
[2177]

**Comment by Firroth** [comment]
Seems like new updates break more stuff xD. Since minions worked for sure week ago when I was on ST.

**Comment by Azalen** [comment]
Maybe we killed him too fast? Everything has so few hitpoints on Netherwing.

**Comment by Shanghi** [comment]
The loot was fixed about 2 weeks ago.
