### ISSUE TITLE
[Quest][NPC] Bubulo Acerbus

### ISSUE THREAD

**Issue by scarabadookie** [Atlantiss/NetherwingBugtracker#1618]
[//]: # (Enclose links to things related to the bug using http://wowhead.com or any other TBC database.)
[//]: # (You can use screenshot ingame to visual the issue.)
[//]: # (Write your tickets according to the format:)
[//]: # ([Quest][Azuremyst Isle] Red Snapper - Very Tasty!)
[//]: # ([NPC] Magistrix Erona)
[//]: # ([Spell][Mage] Fireball)
[//]: # ([Npc][Drop] Ghostclaw Lynx)
[//]: # ([Web] Armory doesnt work)

**Description**: 
The Gnomeregan Exiles Alliance cloth quartermaster Bubulo Acerbus seems to have his allegiances slightly wrong.

**Current behaviour**:
A Donation of Wool and A Donation of Silk give Ironforge reputation. Haven't been able to test Mageweave and Runecloth yet, needs testing.

**Expected behaviour**: 
As the Gnome quartermaster, he should give Gnomeregan Exiles reputation for his cloth turn-in quests.

**Server Revision**: 
2177

**Comment by Shanghi** [comment]
He should give Gnomeregan Exiles reputation in revision 2221. I checked all the other cloth quests on him and the other cloth people and it was only those 2 that were somehow messed up.
