### ISSUE TITLE
[NPC][Eversong Woods] Sathein icon

### ISSUE THREAD

**Issue by ffchaosmaster** [Atlantiss/NetherwingBugtracker#162]
[//]: # (Enclose links to things related to the bug using http://wowhead.com or any other TBC database.)
[//]: # (You can use screenshot ingame to visual the issue.)
[//]: # (Write your tickets according to the format:)
[//]: # ([Quest][Azuremyst Isle] Red Snapper - Very Tasty!)
[//]: # ([NPC] Magistrix Erona)
[//]: # ([Spell][Mage] Fireball)
[//]: # ([Npc][Drop] Ghostclaw Lynx)
[//]: # ([Web] Armory doesnt work)

**Description**: 
The icon when hovering over the Leatherworking Trainer Sathein in Eversong Woods is an anvil, even though he's not a vendor/repairman.
**Current behaviour**:
Hover icon over Sathein is an anvil instead of a trainer's book.
Screenshot (unfortunately couldn't get the hover icon):
![wowscrnshot_092318_133707](https://user-images.githubusercontent.com/5289978/45927609-2255fd00-bf36-11e8-8dad-ad2f45520270.jpg)

**Expected behaviour**: 
Icon should be the trainer's book.
**Server Revision**:

**Comment by Evolvee** [comment]
fixed in next hotfix revision
