### ISSUE TITLE
[NPC][Quest] Lord Vyletounge, Legends of Maraudon - Celebrian Diamond

### ISSUE THREAD

**Issue by Mewmewww** [Atlantiss/NetherwingBugtracker#1621]
[//]: # (Enclose links to things related to the bug using http://wowhead.com or any other TBC database.)
[//]: # (You can use screenshot ingame to visual the issue.)
[//]: # (Write your tickets according to the format:)
[//]: # ([Quest][Azuremyst Isle] Red Snapper - Very Tasty!)
[//]: # ([NPC] Magistrix Erona)
[//]: # ([Spell][Mage] Fireball)
[//]: # ([Npc][Drop] Ghostclaw Lynx)
[//]: # ([Web] Armory doesnt work)

**Description**: 
Killed boss, only 2/4 were able to pick up the celebrian diamond from Lord Vyletounge. We are unsure what caused this problem. It's either too fast despawn or theres a limit on how many can pick up the diamond.
**Current behaviour**:
Only 2/4 of the party members were able to pick up the diamond (^reasoning above I believe)
**Expected behaviour**: 
All should be able to pick it up. (^reasoning above)
**Server Revision**: 
2177

**Comment by Manaci** [comment]
Fixed
