### ISSUE TITLE
[Quest] The Scepter of Celebras

### ISSUE THREAD

**Issue by Mikik3jr** [Atlantiss/NetherwingBugtracker#1622]
[//]: # (Enclose links to things related to the bug using http://wowhead.com or any other TBC database.)
[//]: # (You can use screenshot ingame to visual the issue.)
[//]: # (Write your tickets according to the format:)
[//]: # ([Quest][Azuremyst Isle] Red Snapper - Very Tasty!)
[//]: # ([NPC] Magistrix Erona)
[//]: # ([Spell][Mage] Fireball)
[//]: # ([Npc][Drop] Ghostclaw Lynx)
[//]: # ([Web] Armory doesnt work)

**Description**: 
When you kill Celebras the Cursed you hand in a quest, THEN you get The Scepter of Celebras. In this quest you start an event to escort the guy the an altair thingy and compeltes a ritual, then it is done.
**Current behaviour**:
1 guy got the quest and it didn't share. Afther he finished the quest we could get it and it shared over the remaining members of the party. The sad thing is that the NPC stucked, and didn't do anything. We asked Tsu for help and he/she even finished the quest for us, but we could not hand it in the quest nor start the event again.

So basicly when someone finishes the quest after the even, it bugs out for the others.
![wowscrnshot_101518_235652](https://user-images.githubusercontent.com/43505031/46980795-09281280-d0d6-11e8-993c-6ef2202f80d6.jpg)
**Expected behaviour**: 
Well it should not bug out after 1 person finishes this Q.
**Server Revision**: 
2177

**Comment by Evolvee** [comment]
Not only 1 guy can get the quest, everyone can.. you just have to wait for everyone to accept it and after that you talk to the guy again...

**Comment by Evolvee** [comment]
I mean at the very begging, when you kill the boss and he spawns with quest.

**Comment by Evolvee** [comment]
should the event be repeatable or only once per dungeon?

**Comment by Mikik3jr** [comment]
When we killed it 1 guy started the quest and we didn't get it. After the event was done we picked the quest up again and it shared to the others as well, but the event didn't start. On Elysium we did the event 5 times for everyone IIRC, but this is not a proof how it was on retail.

**Comment by Evolvee** [comment]
Yea, it currently requires the 1 guy to wait for everyone to pick up the quest and after that start it...

**Comment by Evolvee** [comment]
I will make the pop up box with q accept but it has previous quest requirement so... if u arent fast enough and someone clicks it, ur fucked.

**Comment by samemari** [comment]
My prev run we all clicked Yes and event didn't start at all, NPC didn't move to the stone

**Comment by Evolvee** [comment]
i will make it repeatable in rev Block just in case :/

**Comment by conmigonetherwing** [comment]
i assure you, this is not done and still happens. a few of us got the bug running last night and while i have the quest completed, i cannot turn it in. i'm told i have to what, rerun the whole long thing to get this?

**Comment by Evolvee** [comment]
fixed in next rev
