### ISSUE TITLE
[NPC] Wrathscale Sorceress 

### ISSUE THREAD

**Issue by cterry316** [Atlantiss/NetherwingBugtracker#1623]
[//]: # (Enclose links to things related to the bug using http://wowhead.com or any other TBC database.)
[//]: # (You can use screenshot ingame to visual the issue.)
[//]: # (Write your tickets according to the format:)
[//]: # ([Quest][Azuremyst Isle] Red Snapper - Very Tasty!)
[//]: # ([NPC] Magistrix Erona)
[//]: # ([Spell][Mage] Fireball)
[//]: # ([Npc][Drop] Ghostclaw Lynx)
[//]: # ([Web] Armory doesnt work)

**Description**: 
This specific naga doesn't respond to attacks. It appears to be stuck in a running animation. Whenever I use my spell it displays "Out of range." It ONLY occurs with this specific naga for some reason- the other enemies in Loreth' Aran respond correctly, including the other sorceresses. 

![nagaglitch](https://user-images.githubusercontent.com/44184482/46989007-ed664180-d0c0-11e8-9ac2-a303c9cc79c3.PNG)

P.S. - This is my first bug submission so if it's put together incorrectly please let me know. 
**Current behaviour**:
Stuck in running animation and unresponsive to attacks. 

**Expected behaviour**: 
The naga should be aggressive and attack the player with spells. 

**Server Revision**: 
2177

**Comment by Mikik3jr** [comment]
Same issues here with different mobs:
https://github.com/Atlantiss/NetherwingBugtracker/issues/1612

**Comment by The14me** [comment]
@cterry316  Thx for the report.When u gonna report npc like that please do _.npc info_  on the mob and add Entry and ID to the report.Everything else is fine. : )

**Comment by aresbrutus** [comment]
Fixed after rev `2196`
