### ISSUE TITLE
 [Core Mechanic][Spell]Frost Trap#13809 when 2 traps are placed, the last placed has no effect when first one wears out

### ISSUE THREAD

**Issue by Tenoutoften** [Atlantiss/NetherwingBugtracker#1625]
**Description**: 
Had a few issues with [[Spell]Frost Trap#13809](https://db.excalibur.ws/?spell=13809), seems to happen mostly in angled terrain: A lot of times the mobs are not affected by the trap and run full speed

https://www.youtube.com/watch?v=bQzK_nZQT5o&feature=youtu.be

Didn't do .gps but it's in the beginning of BRD and not to difficult to figure out where, go to the left through the door in the begining, then to the right through another door. Not sure if this is limited to this dungeon, or all dungeons, or entire world.

**Expected behaviour**: 
Expect mobs to be slowed in  [[Spell]Frost Trap#13809](https://db.excalibur.ws/?spell=13809)

**Server Revision**: 
~2175

**Comment by Easyfraggy** [comment]
Put it as low prio as long as it only happens here, please do comment if it happens outside BRD.

**Comment by Tenoutoften** [comment]
Alright, Ill ask it if happens other places

**Comment by Tenoutoften** [comment]
reproduced in stratholme https://www.youtube.com/watch?v=p1khJPPBrm4&feature=youtu.be

Doesnt always work though

**Comment by Ahmpy** [comment]
This bug occurs outside of instances, specifically this bug occurs when you have more than 1 frost trap active at a time. The most recent frost trap seems to stop working once the previous trap duration runs out.

**Comment by Tenoutoften** [comment]
@Easyfraggy

**Comment by letterix** [comment]
Happens outside inn a lot of terrain. Sometimes I get the effect but the area is a lot smaller than the visual effect actually shows. Reproduced all over Hellfire Penisula.

**Comment by 4egito** [comment]
https://drive.google.com/file/d/1zyOiPH0tr6kXyFle66RxqcdDNfWJEFIu/view?usp=sharing
@Tereneckla Still bugged

**Comment by Godmatik** [comment]
Already fixed - can close
