### ISSUE TITLE
[NPC]Magma Elemental#5855 able to cast [Spell]Fire Nova while stunned

### ISSUE THREAD

**Issue by Tenoutoften** [Atlantiss/NetherwingBugtracker#1626]
**Description**: 
[[NPC]Magma Elemental#5855](https://db.excalibur.ws/?npc=5855) are able to cast [[Spell]Fire Nova](https://db.excalibur.ws/?search=fire+nova#spells) while stunned. Video [here](https://www.youtube.com/watch?v=4xwQfZf9xlA&feature=youtu.be)

**Expected behaviour**: 
Probably shouldn't be able to cast spells while stunned.

**Server Revision**: 
2177

**Comment by Evolvee** [comment]
rev maul
