### ISSUE TITLE
[NPC]Overseer Maltorius#14621 wrong guards 2x [NPC]Dark Iron Sentry#8504 should have 1x [NPC]Dark Iron Lookout#8566

### ISSUE THREAD

**Issue by Tenoutoften** [Atlantiss/NetherwingBugtracker#1627]
**Description**: 
In [[Quest]Wanted Overseer Maltorius#7701](https://www.wowhead.com/quest=7701/wanted-overseer-maltorius) you are asked to bring down [[NPC]Overseer Maltorius#14621](https://www.wowhead.com/npc=14621/overseer-maltorius) who is guarded by a [[NPC]Dark Iron Lookout#8566](https://db.excalibur.ws/?npc=8566) according to [wowhead comments](https://www.wowhead.com/npc=14621/overseer-maltorius#comments:id=184414) on  [[NPC]Overseer Maltorius#14621](https://www.wowhead.com/npc=14621/overseer-maltorius)-page:
![41e31480be078d0bfd5d2628daf62d6e](https://user-images.githubusercontent.com/34839199/46999945-5d0f1780-d127-11e8-9b3d-1deaee3065d2.png)

On Netherwing he is protected by 2 x [[NPC]Dark Iron Sentry#8504](https://db.excalibur.ws/?npc=8504), video [here](https://www.youtube.com/watch?v=hf3bRvE5wko&feature=youtu.be)
![58fdfa4f44f8cc6b6682e5112efe7283](https://user-images.githubusercontent.com/34839199/46999826-0acdf680-d127-11e8-9f51-3adf7bd6f46c.png):
![20f312ab07bba88d19f01e8153662636](https://user-images.githubusercontent.com/34839199/46999686-a6129c00-d126-11e8-90b5-bf0d9ff735c8.png)
![43082f0c16ce2846c87f116185560b92](https://user-images.githubusercontent.com/34839199/46999687-a6ab3280-d126-11e8-90b5-655973ef3bf8.png)

**Expected behaviour**: 
1x [[NPC]Dark Iron Lookout#8566](https://db.excalibur.ws/?npc=8566) guard.

**Server Revision**: 
2177

**Comment by netherwingbta** [comment]
Overseer Maltorius also doesn't chain aggro the lookouts and vice versa. 
![screen shot 2018-10-21 at 10 46 48 pm](https://user-images.githubusercontent.com/43872263/47273237-7b469e80-d591-11e8-9f62-ad9ba385f54e.jpg)

**Comment by aresbrutus** [comment]
He currently has his pre-2.3 version. This will get changed to post-2.3 version soon.

**Comment by aresbrutus** [comment]
Both are fixed in rev `Ilus`
