### ISSUE TITLE
[NPC] Mosh'Ogg Warmonger thunderclaps during stun.

### ISSUE THREAD

**Issue by Mikik3jr** [Atlantiss/NetherwingBugtracker#1628]
[//]: # (Enclose links to things related to the bug using http://wowhead.com or any other TBC database.)
[//]: # (You can use screenshot ingame to visual the issue.)
[//]: # (Write your tickets according to the format:)
[//]: # ([Quest][Azuremyst Isle] Red Snapper - Very Tasty!)
[//]: # ([NPC] Magistrix Erona)
[//]: # ([Spell][Mage] Fireball)
[//]: # ([Npc][Drop] Ghostclaw Lynx)
[//]: # ([Web] Armory doesnt work)

**Description**: 
Mosh'Ogg Warmonger (https://www.wowhead.com/npc=709/moshogg-warmonger) usually use Thunderclap (https://www.wowhead.com/spell=8147/thunderclap) spell during the fight.
**Current behaviour**:
https://youtu.be/a3qSaQ2jHP8
**Expected behaviour**: 
Mobs still should not use their abilities during stun. I reported the same issue 2 different mobs:
https://github.com/Atlantiss/NetherwingBugtracker/issues/1183
https://github.com/Atlantiss/NetherwingBugtracker/issues/1246
I start to think it is more a global issue.
**Server Revision**: 
2177

**Comment by Evolvee** [comment]
rev maul
