### ISSUE TITLE
[NPC]Dark Iron Sentry#8504 in Searing Gorge towers should be replaced with [NPC]Dark Iron Lookout#8566

### ISSUE THREAD

**Issue by Tenoutoften** [Atlantiss/NetherwingBugtracker#1629]
**Description**: 
All [[NPC]Dark Iron Sentry#8504](https://db.excalibur.ws/?npc=8504) in towers should be replaced with [[NPC]Dark Iron Lookout#8566](https://db.excalibur.ws/?npc=8566)
![8aaed9aed5425733cc0623e364142458](https://user-images.githubusercontent.com/34839199/47004813-a4e76c00-d132-11e8-8a12-80b5c005c3d5.png)
![aadaf12ea81256eb8072cdbdf83464d1](https://user-images.githubusercontent.com/34839199/47004815-a4e76c00-d132-11e8-9180-46165c7a4bd3.png)
![f9396b9e6efbc57b2942c931929e340b](https://user-images.githubusercontent.com/34839199/47004816-a4e76c00-d132-11e8-9cc9-86f7494f38d2.png)
![ff283a0cb12fa374152a2de177045175](https://user-images.githubusercontent.com/34839199/47004817-a5800280-d132-11e8-8d8d-9601d1ff9d17.png)

According to [wowhead comments](https://www.wowhead.com/quest=3463/set-them-ablaze#comments)
![7546fee63ccfd64e95fefe7f27273faf](https://user-images.githubusercontent.com/34839199/47004419-ceec5e80-d131-11e8-8671-d3a84849c90b.png)

**Expected behaviour**: 
[[NPC]Dark Iron Sentry#8504](https://db.excalibur.ws/?npc=8504) replaced with [[NPC]Dark Iron Lookout#8566](https://db.excalibur.ws/?npc=8566)

**Server Revision**: 
2179

**Comment by Tenoutoften** [comment]
Shouldn't be labeled as [Dungeon]... it's in the open world

**Comment by Evolvee** [comment]
rev Block
