### ISSUE TITLE
[NPC] [QUEST] Dark Storm

### ISSUE THREAD

**Issue by Lephidiles** [Atlantiss/NetherwingBugtracker#163]
[//]: # (Enclose links to things related to the bug using http://wowhead.com or any other TBC database.)
[//]: # (You can use screenshot ingame to visual the issue.)
[//]: # (Write your tickets according to the format:)
[//]: # ([Quest][Azuremyst Isle] Red Snapper - Very Tasty!)
[//]: # ([NPC] Magistrix Erona)
[//]: # ([Spell][Mage] Fireball)
[//]: # ([Npc][Drop] Ghostclaw Lynx)
[//]: # ([Web] Armory doesnt work)

**Description**: 
NPC Fizzle Darkstorm keeps resetting and also had two spawned imps ? (might be correct?)

**Current behaviour**:

**Expected behaviour**: 

**Server Revision**: 
2028

**Comment by xmesaj2** [comment]
will fix

**Comment by xmesaj2** [comment]
fixed in rev 2035

**Comment by Retinus** [comment]
At rev 2040 you can kite imp and get it stucked. It never returns to original position and evades at your attacks. You can then kill fizzle alone. Even when fizzle re-spawns imp is still stucked.

**Comment by Evolvee** [comment]
should be fixed in next hotfix rev
