### ISSUE TITLE
[Pathing][NPC]Ranged mob pulled close to a bridge and kited back will sometimes not use the bridge

### ISSUE THREAD

**Issue by Tenoutoften** [Atlantiss/NetherwingBugtracker#1631]
**Description**: 
https://www.youtube.com/watch?v=sS9bUTAX5lA&feature=youtu.be

**Expected behaviour**: 
Expected to use the bridge

**Server Revision**: 
2179

**Comment by wtRCH** [comment]
Also worth noticing on the video is mob who felt throught the bridge... 🤦‍♀️

**Comment by Tereneckla** [comment]
Video is gone, no information here anymore.
