### ISSUE TITLE
[NPC] Fozruk #2611

### ISSUE THREAD

**Issue by maxturtlesc2** [Atlantiss/NetherwingBugtracker#1632]
[//]: # (Enclose links to things related to the bug using http://wowhead.com or any other TBC database.)
[//]: # (You can use screenshot ingame to visual the issue.)
[//]: # (Write your tickets according to the format:)
[//]: # ([Quest][Azuremyst Isle] Red Snapper - Very Tasty!)
[//]: # ([NPC] Magistrix Erona)
[//]: # ([Spell][Mage] Fireball)
[//]: # ([Npc][Drop] Ghostclaw Lynx)
[//]: # ([Web] Armory doesnt work)

**Description**: 
Fozruk was leashing properly. Then at some point he stopped leashing correctly; and was following me until I was dead. After killing him, I got stuck in combat mode until his dead body disappeared.
**Current behaviour**:
Random leash attitude, stuck in combat after killing him.
**Expected behaviour**: 
Proper leash, out of combat after killing him.
**Server Revision**:

**Comment by The14me** [comment]
Confirm leash part.Cant reproduce the dead part.

**Comment by duzyizly** [comment]
fozruk is leashing (as intended) as 3403 ptr. probably fixed long time ago.

![WoWScrnShot_062420_122224](https://user-images.githubusercontent.com/43931626/85538698-6d260c80-b615-11ea-9093-b27e071a1e42.jpg)
![WoWScrnShot_062420_122226](https://user-images.githubusercontent.com/43931626/85538702-6e573980-b615-11ea-9f3f-668c271c4cb2.jpg)
