### ISSUE TITLE
[Ungoro] Some mob IDs have empty loot window

### ISSUE THREAD

**Issue by Azalen** [Atlantiss/NetherwingBugtracker#1634]
**Description**: 
https://web.archive.org/web/20071031011825/http://wow.allakhazam.com:80/db/mob.html?wmob=6527
https://web.archive.org/web/20071031011810/http://wow.allakhazam.com:80/db/mob.html?wmob=6517

**Current behaviour**:
After killing and looting them they still show the lootable icon when hovering their corpse and if clicking it, it shows empty loot. This happens weither or not they dropped the quest item.

![wowscrnshot_101618_135823](https://user-images.githubusercontent.com/20336567/47015133-78d8e480-d14c-11e8-9449-79750e39b5f0.jpg)

**Expected behaviour**: 
Obviosuly no lootable Icon after looting the mob.

**Server Revision**: 
[2177]

**Comment by Azalen** [comment]
Okay, I killed some more and it seems this is not happening all the time. I will add the mob ID's it happens though or will try to find out whats triggering it.

Entry 6527 ID 4 GUIDLow 49068

**Comment by Azalen** [comment]
Disabled all AddOns and deleted Cache, still persists.

**Comment by Evolvee** [comment]
https://youtu.be/Gaex1Dtth4M?t=198

**Comment by Evolvee** [comment]
happened on retail too

**Comment by Azalen** [comment]
Hm, it's hard to argue against that video but I still think there is some specific issue with those mobs. It never ever happened before in 53 levels if leveling and it does not happen with all mobs of that type but only with a few selected ones.

**Comment by Evolvee** [comment]
yea wolf disabled it for cosmetic purposes, idk why it happens here

**Comment by Azalen** [comment]
That could be the case for https://classicdb.ch/?item=11116. But I tried some of the mobs multiple times. It happens for some IDs and didnt happen for others of the same mob type. Obviously this could still be RNG.

**Comment by Evolvee** [comment]
y im almost positive its that item...

its basically handled in a condition where if u already made that quest, you wont see it in the loot window anymore, but its still there... for other party members etc.

**Comment by Azalen** [comment]
But then the dropchance of that item would be off. It shouldn't drop with ~30%

**Comment by Evolvee** [comment]
source?

**Comment by Azalen** [comment]
https://web.archive.org/web/20071029185130/http://wow.allakhazam.com:80/db/item.html?witem=11116

**Comment by Evolvee** [comment]
It has 1% because it can drop only once....

these websites dont show the real drop chance... they calculate the drop based on how many times the creature was killed and how many times the item dropped...

**Comment by Evolvee** [comment]
it is already in our global loot btw

**Comment by Neophrone** [comment]
When it happens to Gorillas and raptors they became unskinable. So it's a bug for sure.

**Comment by Neophrone** [comment]
Also video that u linked, Evolve. After looting mobs 1 time, they become unlootable after. In our case corpses always lootable,even after u open loot window and took all loot. And when u trying to skin corpse - it says that u should loot corpse before skining. Looks like it's a Journal drop.

**Comment by Evolvee** [comment]
y report that if its not already(i think it is)
