### ISSUE TITLE
[Ungoro] Sticky Tar

### ISSUE THREAD

**Issue by Azalen** [Atlantiss/NetherwingBugtracker#1635]
**Description**: 
https://classicdb.ch/?spell=14178
https://classicdb.ch/?spell=14180

used by

https://web.archive.org/web/20071031011825/http://wow.allakhazam.com:80/db/mob.html?wmob=6527
https://web.archive.org/web/20071031011810/http://wow.allakhazam.com:80/db/mob.html?wmob=6517
https://web.archive.org/web/20071031011820/http://wow.allakhazam.com:80/db/mob.html?wmob=6519
https://web.archive.org/web/20071031011815/http://wow.allakhazam.com:80/db/mob.html?wmob=6518

**Current behaviour**:
This spell has no cooldown. Some of the mobs - the ones that have no other spells to use - use it consecutively which shouldn't be the case. It is worst on the "Tar Beasts".

**Expected behaviour**: 
Disarm effects should never be used consecutively. There should be some seconds inbetween for melee-classes to do some attacks.

**Server Revision**: 
[2177]

**Comment by Evolvee** [comment]
its not a spell on a timer

its a chance on each hit against these mobs ^^

would need some evidence if this is rly the case, if so then this would be a global issue for all passive auras

**Comment by Azalen** [comment]
And the procchance is set to 10%? https://www.wowhead.com/spell=14178/sticky-tar

**Comment by Evolvee** [comment]
on each hit y

**Comment by Evolvee** [comment]
its not rly set... its the spell that handles the chance itself
