### ISSUE TITLE
[RP] [Quest] [NPC] Bath'rah the Windwatcher 

### ISSUE THREAD

**Issue by samemari** [Atlantiss/NetherwingBugtracker#1636]
**Description**: 
After turn-in of the quest Spirit Totem http://db.hellfire-tbc.com/?quest=8412 NPC Bath'rah the Windwatcher ready to give next quest in  the chain.
**Current behaviour**:
Ready to give next quest in the chain, just before testing reagents delivered on the prev quest
**Expected behaviour**: 
NPC goes to test reagents delivered on prev quest in chain, said: "I don't think it's strong enough" and gives next quest in the chain - Da Voodoo
**Server Revision**: 
2179

**Comment by Evolvee** [comment]
![image](https://user-images.githubusercontent.com/1942409/47258088-8a94f180-d496-11e8-840e-cd699b4ac032.png)

**Comment by Tereneckla** [comment]
Fixed
