### ISSUE TITLE
[weapon on-use-effect] Activating the "Manual Crowd Pummeler"'s haste effect will consume 3 charges instead of just 1.

### ISSUE THREAD

**Issue by Dosdaltherir** [Atlantiss/NetherwingBugtracker#1637]
**Description**: 
The "Manual Crowd Pummeler", a lvl 28 2-hander mace from Gnomeregan has an on-use effect(by the name of "haste") that grants the wielder 500 haste for 30 sec. The weapon comes with 3 charges, and once those charges are consumed, you must get another new "Manual Crowd Pummeler", if you wish to make use of the on-use effect again.
**Current behaviour**:
Consuming a charge on the "Manual Crowd Pummeler" will instantly consume all 3 charges. 
**Expected behaviour**: 
Consuming a charge on the "Manual Crowd Pummeler" should only consume 1 charge at once.
**Combat log that shows it**: 
![wowscrnshot_101618_135612](https://user-images.githubusercontent.com/43515247/47017817-952c4f80-d153-11e8-9832-4a2885637ed2.jpg)
Look at the: 
"Dosdaltherir's Haste is refreshed."
"Dosdaltherir's Haste is refreshed."
"Dosdaltherir gains Haste."
**note**: I'm not able to recreate this issue, because my "Manual Crowd Pummeler" has run out of charges. 
**Server Revision**: 
rev: 2179

**Comment by Tereneckla** [comment]
Fixed
