### ISSUE TITLE
[Core][Movement] Fleeing mob target selection and pathing

### ISSUE THREAD

**Issue by Galawer** [Atlantiss/NetherwingBugtracker#1638]
**Current behaviour**:
Usually, when a mob chooses a friendly target to flee to, it will prefer reachable targets, even if they're further away, like so: [Video](https://streamable.com/8jmj2)

But if there are no reachable friendly targets in range, it will ignore terrain, fly straight to the nearest mob and then reset, because it can't find a path back: [Video](https://streamable.com/wqdpj)

**Expected behaviour**: 
Fleeing mobs should ignore unreachable targets.

**Server Revision**: 
2179

**Comment by Tereneckla** [comment]
Fixed
