### ISSUE TITLE
Stromgarde Keep aggro through walls

### ISSUE THREAD

**Issue by maxturtlesc2** [Atlantiss/NetherwingBugtracker#1639]
[//]: # (Enclose links to things related to the bug using http://wowhead.com or any other TBC database.)
[//]: # (You can use screenshot ingame to visual the issue.)
[//]: # (Write your tickets according to the format:)
[//]: # ([Quest][Azuremyst Isle] Red Snapper - Very Tasty!)
[//]: # ([NPC] Magistrix Erona)
[//]: # ([Spell][Mage] Fireball)
[//]: # ([Npc][Drop] Ghostclaw Lynx)
[//]: # ([Web] Armory doesnt work)

**Description**: 
You can aggro mobs through walls in Stromgarde Keep around 27.5 ; 58.
**Current behaviour**:
Aggro through walls.
**Expected behaviour**: 
No aggro when out of line of sight.
**Server Revision**:

**Comment by Easyfraggy** [comment]
Was never able to replicate it.

**Comment by The14me** [comment]
Cant reproduce with any class.Re-open if happen again with Gif or Img.
