### ISSUE TITLE
Zenn's Biding

### ISSUE THREAD

**Issue by loljeema123** [Atlantiss/NetherwingBugtracker#164]
[//]: # (Enclose links to things related to the bug using http://wowhead.com or any other TBC database.)
[//]: # (You can use screenshot ingame to visual the issue.)
[//]: # (Write your tickets according to the format:)
[//]: # ([Quest][Azuremyst Isle] Red Snapper - Very Tasty!)
[//]: # ([NPC] Magistrix Erona)
[//]: # ([Spell][Mage] Fireball)
[//]: # ([Npc][Drop] Ghostclaw Lynx)
[//]: # ([Web] Armory doesnt work)

**Description**: Zenn's Biding pick 3 things from spiders,owl,tiger

**Current behaviour**: It takes like  50 mobs  to  finish quest

**Expected behaviour**: from my experience droprate should be  soooo much higher on this quest

**Server Revision**:

**Comment by aresbrutus** [comment]
You seem to have been unlucky, but rechecking sources, I have increased the drop chance a little bit.
