### ISSUE TITLE
[NPC][Movement][Stonetalon Mountains] The Charred Vale area

### ISSUE THREAD

**Issue by eryczek1615** [Atlantiss/NetherwingBugtracker#1640]
**Description**: 
[Bloodfury Harpy](https://www.wowhead.com/npc=4022)
[Bloodfury Ambusher](https://www.wowhead.com/npc=4025)
[Bloodfury Windcaller](https://www.wowhead.com/npc=4026)
[Bloodfury Slayer](https://www.wowhead.com/npc=4024)
[Bloodfury Storm Witch](https://www.wowhead.com/npc=4027)
[Bloodfury Roguefeather](https://www.wowhead.com/npc=4023)
[Bloodfury Ripper](https://www.wowhead.com/npc=12579)
[Young Chimaera](https://www.wowhead.com/npc=4032)
[Enraged Stone Spirit](https://www.wowhead.com/npc=4034)
[Blackened Basilisk](https://www.wowhead.com/npc=4044)
[Scorched Basilisk](https://www.wowhead.com/npc=4041)
[Blackened Ancient](https://www.wowhead.com/npc=4029)
[Singed Basilisk](https://www.wowhead.com/npc=4042)
[Charred Ancient](https://www.wowhead.com/npc=4028)
[Furious Stone Spirit](https://www.wowhead.com/npc=4035)
[Fledgling Chimaera](https://www.wowhead.com/npc=4031)
[Burning Ravager](https://www.wowhead.com/npc=4037)
[Burning Destroyer](https://www.wowhead.com/npc=4038)
[Rogue Flame Spirit](https://www.wowhead.com/npc=4036)

**Current behaviour**:
Some NPC's don't have movement points.
According to this [Video](https://youtu.be/jMjbGEAzexE?t=355)
https://imgur.com/9ILievZ
https://imgur.com/8nO5jUb
https://imgur.com/qaYXeYh
https://imgur.com/LiThLke

**Expected behaviour**: 
Some of them should patrol this area or have random movement.

**Server Revision**: 
2179

**Comment by wtRCH** [comment]
@aresbrutus

**Comment by Tenoutoften** [comment]
You mean they stand completely still like https://github.com/Atlantiss/NetherwingBugtracker/issues/1378?

**Comment by eryczek1615** [comment]
Some of them

**Comment by aresbrutus** [comment]
Fixed in rev `Nariman`
