### ISSUE TITLE
Sarltooth in Wetlands doesn't respawn

### ISSUE THREAD

**Issue by wilsim** [Atlantiss/NetherwingBugtracker#1641]
**Description**:
Sarltooth, a lvl 29 named quest mob in wetlands.
**Current behaviour**:
It does not respawn after being killed.
**Expected behaviour**:
It should respawn after around 5 mins
**Server Revision**:

**Comment by aresbrutus** [comment]
It does, he has 2 possible spawn points. Please make sure to go look for him at the hill or down below at the ruins.
