### ISSUE TITLE
[Quest][Desolace] Kodo Roundup   Bugged

### ISSUE THREAD

**Issue by TobyBeam** [Atlantiss/NetherwingBugtracker#1642]
[//]: # ([Quest][Desolace] Kodo Roundup)
[//]: # ([NPC] Dying Kodo)
[//]: # ([Quest Item] Kodo Kombobulator)

**Description**: 
using the quest item [Kodo Kombobulator] on Dying Kodo / Ancient Kodo without any effect regarding to the objective

**Current behaviour**:

**Expected behaviour**: 

**Server Revision**:

**Comment by wtRCH** [comment]
https://github.com/Atlantiss/NetherwingBugtracker/issues/371

Atlantiss/AtlantissTBCBT#3460
