### ISSUE TITLE
[NPC][Loot][Dustwallow Marsh] Defias humanoids don't drop money

### ISSUE THREAD

**Issue by scarabadookie** [Atlantiss/NetherwingBugtracker#1643]
[//]: # (Enclose links to things related to the bug using http://wowhead.com or any other TBC database.)
[//]: # (You can use screenshot ingame to visual the issue.)
[//]: # (Write your tickets according to the format:)
[//]: # ([Quest][Azuremyst Isle] Red Snapper - Very Tasty!)
[//]: # ([NPC] Magistrix Erona)
[//]: # ([Spell][Mage] Fireball)
[//]: # ([Npc][Drop] Ghostclaw Lynx)
[//]: # ([Web] Armory doesnt work)

**Description**: 
Defias NPCs in Dustwallow marsh e.g. 23679, 23589, 23590 seem to have lost their purses.

**Current behaviour**:
None of the Defias humanoids drop any coin, other drops seem normal.

**Expected behaviour**: 
They should drop coins like normal humanoids.

**Server Revision**: 
2179

**Comment by wtRCH** [comment]
@aresbrutus

**Comment by Shanghi** [comment]
They finally found some money to steal and will start dropping it after revision 2221.
