### ISSUE TITLE
[NPC][Stonetalon Mountains] Foreman Rigger

### ISSUE THREAD

**Issue by eryczek1615** [Atlantiss/NetherwingBugtracker#1644]
**Description**: 
[Foreman Rigger](https://www.wowhead.com/npc=5931)

**Current behaviour**:
He has random movement

**Expected behaviour**: 
Should patrol Windshire Crag
![image](https://user-images.githubusercontent.com/4455568/47040006-878fbd80-d185-11e8-88fe-0554a88a4500.png)

**Server Revision**: 
2179

**Comment by aresbrutus** [comment]
Fixed in rev `Ilus`.
