### ISSUE TITLE
Healing while dueling

### ISSUE THREAD

**Issue by Erodraeda** [Atlantiss/NetherwingBugtracker#1646]
[//]: # (Enclose links to things related to the bug using http://wowhead.com or any other TBC database.)
[//]: # (You can use screenshot ingame to visual the issue.)
[//]: # (Write your tickets according to the format:)
[//]: # ([Quest][Azuremyst Isle] Red Snapper - Very Tasty!)
[//]: # ([NPC] Magistrix Erona)
[//]: # ([Spell][Mage] Fireball)
[//]: # ([Npc][Drop] Ghostclaw Lynx)
[//]: # ([Web] Armory doesnt work)

**Description**: 
I was dueling with Piled, and we both got healed by Tinno's chain heal while dueling.
**Current behaviour**:
you can chain heal dueling players
**Expected behaviour**: 
You shouldn't be able to interact with players that are dueling.
**Server Revision**:

**Comment by Wolffenstein** [comment]
Fixed in rev 2189.
