### ISSUE TITLE
Wastewander Shadow Mage

### ISSUE THREAD

**Issue by Piledriversn** [Atlantiss/NetherwingBugtracker#1647]
![image](https://user-images.githubusercontent.com/43560552/47055985-dfc3c100-d17f-11e8-9937-7dcc2e17cfba.png)
[//]: # ([NPC] Wastewander Shadow Mage)
[//]: # ([Spell][Npc] Summon Voidwalker)

**Description**: There is 3 Voidwalkers in the screenshot i uploaded.

**Current behaviour**:If you get the Npc to reset or if you die she will continue to summon more and more voidwalkers on each reset.

**Expected behaviour**: The Npc should only summon 1 Voidwalker or keep using the same summoned Voidwalker

**Server Revision**:

**Comment by Evolvee** [comment]
idk must be global wolfAI core issue

**Comment by Tereneckla** [comment]
Fixed
