### ISSUE TITLE
[NPC][Ashenvale] Dark Strand Adept/Dark Strand Cultist) Pets stay and fight after their master dies

### ISSUE THREAD

**Issue by Rebelyna** [Atlantiss/NetherwingBugtracker#1648]
**Description**: 
Was expecting that this is reported already but couldnt find any report for it.

**Current behaviour**:
The pets of the Dark Strand Adept/Dark Strand Cultist stay and keep fighting after their master dies.

**Expected behaviour**: 
The pets should vanish after their master dies.

**Server Revision**: 
2186

**Comment by wtRCH** [comment]
blizzlike

**Comment by Dpthx** [comment]
Pets shouldn't vanish after the master dies.
https://www.youtube.com/watch?v=gusbV3RtP44&feature=youtu.be&t=1m
