### ISSUE TITLE
[Movement][NPC]Spitelash Siren#6195 shouldn't attempt to run away in fear.

### ISSUE THREAD

**Issue by Tenoutoften** [Atlantiss/NetherwingBugtracker#1649]
**Description**: 
[[NPC]Spitelash Siren#6195](https://www.wowhead.com/npc=6195/spitelash-siren#comments) shouldn't attempt to run away in fear.
https://youtu.be/FFx7pDxRRrE?t=472
https://youtu.be/FFx7pDxRRrE?t=544
https://youtu.be/FFx7pDxRRrE?t=581
https://youtu.be/FFx7pDxRRrE?t=701
https://youtu.be/FFx7pDxRRrE?t=748
https://youtu.be/FFx7pDxRRrE?t=802
https://youtu.be/FFx7pDxRRrE?t=935

**Expected behaviour**: 
Shouldn't attempt to run away in fear, currently does.

**Server Revision**: 
2186

**Comment by Evolvee** [comment]
rev Block
