### ISSUE TITLE
[NPC][Eversong Woods] Golden Dragonhawk Hatchling hostile

### ISSUE THREAD

**Issue by ffchaosmaster** [Atlantiss/NetherwingBugtracker#165]
[//]: # (Enclose links to things related to the bug using http://wowhead.com or any other TBC database.)
[//]: # (You can use screenshot ingame to visual the issue.)
[//]: # (Write your tickets according to the format:)
[//]: # ([Quest][Azuremyst Isle] Red Snapper - Very Tasty!)
[//]: # ([NPC] Magistrix Erona)
[//]: # ([Spell][Mage] Fireball)
[//]: # ([Npc][Drop] Ghostclaw Lynx)
[//]: # ([Web] Armory doesnt work)

**Description**: 
(minor) The Golden Dragonhawk Hatchling appears as hostile, but can't be attacked.
**Current behaviour**:
Screenshot:
![wowscrnshot_092318_135147](https://user-images.githubusercontent.com/5289978/45927736-f63b7b80-bf37-11e8-8696-12c8af2884d6.jpg)

**Expected behaviour**: 
Should be neutral
**Server Revision**:

**Comment by xmesaj2** [comment]
will fix

**Comment by Easyfraggy** [comment]
21064 ID 1 also walks on the bookcase in his randomwalk.

![image](https://user-images.githubusercontent.com/36134067/45928139-1c184e80-bf3f-11e8-9da6-4b111cd2a1b8.png)

**Comment by xmesaj2** [comment]
fixed in rev 2035
