### ISSUE TITLE
Some mobs are too close on The Shattered Strand[NPC]

### ISSUE THREAD

**Issue by Tenoutoften** [Atlantiss/NetherwingBugtracker#1650]
**Description**: 
Some mobs are too close on The Shattered Strand, on Netherwing on this spot, they often stand in pairs pretty much.
[[NPC]Spitelash Myrmidon#6196](https://www.wowhead.com/npc=6196/spitelash-myrmidon)
[[NPC]Spitelash Siren#6195](https://www.wowhead.com/npc=6195/spitelash-siren)

![72e77a907e506e760b0b9fa385ebbcb0](https://user-images.githubusercontent.com/34839199/47070056-c27b0b00-d1f0-11e8-82dc-f6f0d7977a8f.png)
![3630a28f1cb51061f94c9eda1880588b](https://user-images.githubusercontent.com/34839199/47070057-c313a180-d1f0-11e8-96a3-72d6fd235130.png)
![d4f845b253632ba8117ea2f724587236](https://user-images.githubusercontent.com/34839199/47070058-c313a180-d1f0-11e8-9e2d-0a37dfc201f8.png)
![e25052fb942b941efd840d5fa32e9006](https://user-images.githubusercontent.com/34839199/47070059-c313a180-d1f0-11e8-87a5-9912c1b11207.png)

Retail
https://youtu.be/FFx7pDxRRrE?t=1459

**Expected behaviour**: 
Perhaps remove a few or spread more. so that they aren't almost standing on top of each other. 

**Server Revision**: 
2186

**Comment by The14me** [comment]
May be the same movement problem (core)

**Comment by Tenoutoften** [comment]
They aren't frozen in place like I have seen other places, but rather patrol a little around on their spots, it just seems that some of them are too close compared to retail video.

**Comment by aresbrutus** [comment]
Fixed in rev `Ilus`.
