### ISSUE TITLE
[NPC][Quest]Betrayed#3505/3506 crystals shouldn't have a 100% chance to spawn Blood elf defender, should despawn at some point, should agro normally if re-engaged

### ISSUE THREAD

**Issue by Tenoutoften** [Atlantiss/NetherwingBugtracker#1652]
**Description**: 
After using turning in [[Quest]Betrayed#3505](https://db.excalibur.ws/?quest=3505) to [[Object]Kaldorei Tome of Summoning#151286](https://db.excalibur.ws/?object=151286) you get [[Quest]Betrayed#3506](https://www.wowhead.com/quest=3506/betrayed#comments) and three [[Object]Arcane Focusing Crystal#150140](https://www.wowhead.com/object=150140/arcane-focusing-crystal#comments) spawns.

Opening one, you have a chance to either face a [[NPC]Blood Elf Defender#8581](https://db.excalibur.ws/?npc=8581) or an [[NPC]Angered Infernal#8608](https://db.excalibur.ws/?npc=8608).

I opened two [[Object]Arcane Focusing Crystal#150140](https://www.wowhead.com/object=150140/arcane-focusing-crystal#comments) spawning a [[NPC]Blood Elf Defender#8581](https://db.excalibur.ws/?npc=8581) both times. I didn't abandon quest to try again, but perhaps it has too high chance or the [[NPC]Angered Infernal#8608](https://db.excalibur.ws/?npc=8608) aren't in? Either way: They don't despawn for quite a while if you run away as can be seen in the video I made [here](https://www.youtube.com/watch?v=Q1wwl0vsM8Q&feature=youtu.be) I started to record after opening up one [[Object]Arcane Focusing Crystal#150140](https://www.wowhead.com/object=150140/arcane-focusing-crystal#comments) already, so you see me opening up the second one.

This triggers the event twice which is a bit funky - at [2min 13sec](https://youtu.be/Q1wwl0vsM8Q?t=133) I engage the non despawning blood elfs(1x [[NPC]Blood Elf Defender#8581](https://db.excalibur.ws/?npc=8581) & 2x [[NPC]Magus Rimtori#8578](https://db.excalibur.ws/?npc=8578)) by attacking one of the [[NPC]Magus Rimtori#8578](https://db.excalibur.ws/?npc=8578). The [[NPC]Blood Elf Defender#8581](https://db.excalibur.ws/?npc=8581) is just standing still and not reacting.

--------------------------------------
Neither [[NPC]Blood Elf Defender#8581](https://db.excalibur.ws/?npc=8581) or [[NPC]Magus Rimtori#8578](https://db.excalibur.ws/?npc=8578) drop any silver. [Wowhead comment](https://www.wowhead.com/quest=3506/betrayed#comments:id=152051)
![1b65fb17135ab2a5527b1f5333977f8d](https://user-images.githubusercontent.com/34839199/47080477-5dcbaa80-d208-11e8-81a2-a3f430050823.png)

-----------------------------------
**Expected behaviour**: 
* Expected to likely spawn [[NPC]Angered Infernal's#8608](https://db.excalibur.ws/?npc=8608) when opening [[Object]Arcane Focusing Crystal#150140](https://www.wowhead.com/object=150140/arcane-focusing-crystal#comments)
* Expect [[NPC]Blood Elf Defender#8581](https://db.excalibur.ws/?npc=8581) / [[NPC]Magus Rimtori#8578](https://db.excalibur.ws/?npc=8578) / [[NPC]Angered Infernal#8608](https://db.excalibur.ws/?npc=8608)(Never saw the behavior) to despawn eventually if you don't engage.
* Expect [[NPC]Blood Elf Defender#8581](https://db.excalibur.ws/?npc=8581) to have an agro radius / be linked with [[NPC]Magus Rimtori#8578](https://db.excalibur.ws/?npc=8578) if he isn't pulled right away.
* Expect [[NPC]Blood Elf Defender#8581](https://db.excalibur.ws/?npc=8581) & [[NPC]Magus Rimtori#8578](https://db.excalibur.ws/?npc=8578) to drop silver/copper.

**Server Revision**: 
2186

**Comment by Shanghi** [comment]
I'm not sure why I was assigned since I have no access to script things, but Magus Rimtori will drop money in revision 2221! Blood Elf Defender is suspicious though and needs more research sometime. I can't find any kind of data about them dropping it and since you should be able to keep summoning them about every 30 seconds (if the respawn time is the same as a comment mentions), maybe stingy Blizzard thought it would be abusable even though that would be a terrible way to make money.

**Comment by Evolvee** [comment]
rev ff15

**Comment by ApexWoW** [comment]
I just finished this quest:
1) Destroyed one Crystal
2) Infernal spawned
3) All Crystals despawned
4) Crystals respawned
5) Destroyed another Crystal
6) Defender and Magus Rimtori spawned
