### ISSUE TITLE
Id:2, GUIDLow: 60421 [Movement][NPC]Stone Guardian#6560 not patrolling in Un'goro

### ISSUE THREAD

**Issue by Tenoutoften** [Atlantiss/NetherwingBugtracker#1653]
**Description**: 
[[NPC]Stone Guardian#6560](https://www.wowhead.com/npc=6560/stone-guardian#comments) not patroling.
![bd4c64a4f1b7561cd6f7bdba047ae1c5](https://user-images.githubusercontent.com/34839199/47082199-26133180-d20d-11e8-8ca6-bcd9f43ddbd8.png)
![2539c2731353689985d69e2e72bac41d](https://user-images.githubusercontent.com/34839199/47082272-52c74900-d20d-11e8-9ee5-33b762f432ea.png)

**Current behaviour**:
Standing still.

**Expected behaviour**: 
All of these are suppose to patrol to my knowledge, 

**Server Revision**:

**Comment by aresbrutus** [comment]
Fixed in rev `Ilus`.
