### ISSUE TITLE
Specific [Object]Power Crystal floating in the air a few yards in Un'goro

### ISSUE THREAD

**Issue by Tenoutoften** [Atlantiss/NetherwingBugtracker#1654]
**Description**: 
[[Object]Blue Power Crystal#164658](https://db.excalibur.ws/?object=164658)
[[Object]Blue Power Crystal#164778](https://db.excalibur.ws/?object=164778)

[[Object]Green Power Crystal#164659](https://db.excalibur.ws/?object=164659)
[[Object]Green Power Crystal#164779](https://db.excalibur.ws/?object=164779)

[[Object]Red Power Crystal#164660](https://db.excalibur.ws/?object=164660)
[[Object]Red Power Crystal#164780](https://db.excalibur.ws/?object=164780)

[[Object]Yellow Power Crystal#164661](https://db.excalibur.ws/?object=164661)
[[Object]Yellow Power Crystal#164781](https://db.excalibur.ws/?object=164781)

![2f41ee63d637e6f3de5fd64822d65496](https://user-images.githubusercontent.com/34839199/47082417-bf424800-d20d-11e8-972e-339878c6be64.png)
![be688350d4007610dcf5833ce414e416](https://user-images.githubusercontent.com/34839199/47082419-bf424800-d20d-11e8-81da-36e8f6c5589c.png)

**Expected behaviour**: 
Probably shouldn't float in the air.

**Server Revision**: 
2186

**Comment by Shanghi** [comment]
Those rude floating crystals should be fixed in revision 2221. There ended up being about 5 or 6 of them.
