### ISSUE TITLE
Water Shield Mana

### ISSUE THREAD

**Issue by Tinnoan** [Atlantiss/NetherwingBugtracker#1658]
**Description**: Letting Water Shield run out of duration applies all 3 globes of water (i.e. giving the mana) at the end of it, reapplying Water Shield or Removing it manually doesn't do this. [Video](https://streamable.com/s1xd0) of it happening.

**Expected behaviour**: Water Shield should not be giving the 3 globes of water from running out of duration.

**Server Revision**: 2186

**Comment by Evolvee** [comment]
![image](https://user-images.githubusercontent.com/1942409/47190426-97540100-d341-11e8-82b6-f5276893bc67.png)

![image](https://user-images.githubusercontent.com/1942409/47190434-a470f000-d341-11e8-86be-400a4c3670e5.png)

working as intended
