### ISSUE TITLE
Id: 5, [Movement][NPC]Stone Guardian#6560 not patrolling in Un'goro

### ISSUE THREAD

**Issue by Tenoutoften** [Atlantiss/NetherwingBugtracker#1659]
**Description**: 
![618cf79ed52445fd4fc99ec5199fbb1b](https://user-images.githubusercontent.com/34839199/47084408-b05e9400-d213-11e8-8567-bc806e34e81b.png)
![2539c2731353689985d69e2e72bac41d](https://user-images.githubusercontent.com/34839199/47082272-52c74900-d20d-11e8-9ee5-33b762f432ea.png)
Standing completely still atm.

Also see: https://github.com/Atlantiss/NetherwingBugtracker/issues/1657

**Expected behaviour**: 
Expected to patrol

**Server Revision**: 
2186

**Comment by aresbrutus** [comment]
Fixed in rev `Ilus`.
