### ISSUE TITLE
[Core] Fish mobs don't loose combat when out of water.

### ISSUE THREAD

**Issue by Firroth** [Atlantiss/NetherwingBugtracker#166]
[Core] Fishes don't loose aggro/combat when player get's out of water.

**Current behaviour**:
Fishes which you can fight with, don't loose aggro/combat when you move onto the land.
https://imgur.com/a/1R2K4SD

**Expected behaviour**: 
Fishes should loose combat/aggro when you get out of the water.

**Server Revision**: 
2028

Edit: checked one more time and now it worked properly, fish wouldn't get out of water in certain parts of the map. So I think the problem will be with mmaps here, since they get out in certain areas of the water, like seen on the screen, that "it can move out of water and still attack player"

**Comment by Easyfraggy** [comment]
If you type .gps ingame and take a screenshot of the info shown in your chatlog you can post it here and we can check it out!

If you have windows 10 you can post screenshots easily by holding win+shift+s and simply dragging the area you want screenshotted. Then you can CTRL+V directly into github, so you don't need to upload to imgur!

**Comment by Firroth** [comment]
![screenshot_3](https://user-images.githubusercontent.com/43505196/45928207-3f8fc900-bf40-11e8-8c4a-70a1c1fb8e1c.png)

It occured 2 times to me at this coords. He also evaded several times - I think cause of his position in water by the time I got out of the water. So to make him leave the water you need to try several times, but it can be done like seen on the screen.

**Comment by The14me** [comment]
There is something wrong with this fish 17673"
other fish's work fine to me (leave combat when out of the water)

**Comment by The14me** [comment]
Work fine now (reset) 3441 rev.
