### ISSUE TITLE
[NPC][Movement][Thousand Needles] Freewind Brave

### ISSUE THREAD

**Issue by eryczek1615** [Atlantiss/NetherwingBugtracker#1660]
**Description**: 
[Freewind Brave](https://www.wowhead.com/npc=9525)

**Current behaviour**:
This one is walking through bonfire.
https://imgur.com/IYQ5Dc8

**Expected behaviour**: 
He shouldn't walks through bonfire.

**Server Revision**: 
2186

**Comment by ircfelix** [comment]
https://i.imgflip.com/2kb0qv.jpg

**Comment by wtRCH** [comment]
@aresbrutus

**Comment by aresbrutus** [comment]
Fixed in rev `Ilus`
