### ISSUE TITLE
OOX-09/HL Distress Beacon

### ISSUE THREAD

**Issue by DemonHunter1992** [Atlantiss/NetherwingBugtracker#1661]
[//]: # (Enclose links to things related to the bug using http://wowhead.com or any other TBC database.)
[//]: # (You can use screenshot ingame to visual the issue.)
[//]: # (Write your tickets according to the format:)
[//]: # ([Quest][Azuremyst Isle] Red Snapper - Very Tasty!)
[//]: # ([NPC] Magistrix Erona)
[//]: # ([Spell][Mage] Fireball)
[//]: # ([Npc][Drop] Ghostclaw Lynx)
[//]: # ([Web] Armory doesnt work)

**Description**: https://classicdb.ch/?quest=485

**Current behaviour**: the escort mob (mechanical chicken) is not taking aggro from mobs on path

**Expected behaviour**: the mob(mechanical chicken) should aggro mobs on path

**Server Revision**: 2186

**Comment by wtRCH** [comment]
known issue, but I will keep it

**Comment by Tenoutoften** [comment]
already reported in https://github.com/Atlantiss/NetherwingBugtracker/issues/970
