### ISSUE TITLE
escape with full hp and no reason

### ISSUE THREAD

**Issue by ayrb13** [Atlantiss/NetherwingBugtracker#1662]
[//]: # (Enclose links to things related to the bug using http://wowhead.com or any other TBC database.)
https://www.wowhead.com/npc=2975/venture-co-hireling
[//]: # (You can use screenshot ingame to visual the issue.)
[//]: # (Write your tickets according to the format:)
[//]: # ([Quest][Azuremyst Isle] Red Snapper - Very Tasty!)
[//]: # ([NPC] Magistrix Erona)
venture co. hireling
[//]: # ([Spell][Mage] Fireball)
[//]: # ([Npc][Drop] Ghostclaw Lynx)
[//]: # ([Web] Armory doesnt work)

**Description**: 
when i was attacked by 3 hirelings, I didnt move, but they escape with full hp and no reason
**Current behaviour**:
escape with full hp and no reason
**Expected behaviour**: 
keep attacking me
**Server Revision**:

**Comment by Easyfraggy** [comment]
Need more specific info closed for now.
