### ISSUE TITLE
[NPC] Zeppelin announcer mistimed

### ISSUE THREAD

**Issue by maxturtlesc2** [Atlantiss/NetherwingBugtracker#1664]
[//]: # (Enclose links to things related to the bug using http://wowhead.com or any other TBC database.)
[//]: # (You can use screenshot ingame to visual the issue.)
[//]: # (Write your tickets according to the format:)
[//]: # ([Quest][Azuremyst Isle] Red Snapper - Very Tasty!)
[//]: # ([NPC] Magistrix Erona)
[//]: # ([Spell][Mage] Fireball)
[//]: # ([Npc][Drop] Ghostclaw Lynx)
[//]: # ([Web] Armory doesnt work)
<img src="https://i.imgur.com/ZVvWbFU.png">
**Description**: 
The NPC announced the zeppelin ~10-15sec before its actual arrival at Orgrimmar.
**Current behaviour**:
Mistimed announce.
**Expected behaviour**: 
Correctly timed announce.
**Server Revision**:

**Comment by Wolffenstein** [comment]
It's correct in TBC. Blizzard patched it in wotlk.
