### ISSUE TITLE
Id 4, [NPC]Bloodpetal Lasher#6509 "out of range" / stuck 

### ISSUE THREAD

**Issue by Tenoutoften** [Atlantiss/NetherwingBugtracker#1666]
**Description**: 
![119b72a73c9f65cd589588ecf0676d3b](https://user-images.githubusercontent.com/34839199/47099247-317a5300-d235-11e8-9c95-cea60b3cc03e.png)
[[NPC]Bloodpetal Lasher#6509](https://db.excalibur.ws/?npc=6509) "out of range" / stuck. On my part I tried to relog didn't change anything. Only this one is not working so far.

Video [here](https://www.youtube.com/watch?v=EiGtwmqreFI&feature=youtu.be)

**Expected behaviour**: 
Expected to be like the others.

**Server Revision**: 
2186

**Comment by aresbrutus** [comment]
Fixed after rev `2196`
