### ISSUE TITLE
[NPC][Thousand Needles] Boilling Elemental - stuck

### ISSUE THREAD

**Issue by eryczek1615** [Atlantiss/NetherwingBugtracker#1667]
**Description**: 
[Boilling Elemental](https://www.wowhead.com/npc=10757)
![image](https://user-images.githubusercontent.com/4455568/47138923-e99e0f00-d2ba-11e8-9eb6-7c6f93ab2642.png)
![image](https://user-images.githubusercontent.com/4455568/47138969-00446600-d2bb-11e8-986d-fc3f5517055c.png)

**Current behaviour**:
One of them stuck in running mode and he is "out of range".(Only this one)
https://imgur.com/71W2zBa
![image](https://user-images.githubusercontent.com/4455568/47100595-2c6ad300-d238-11e8-807b-d9b7b632ac61.png)

**Expected behaviour**: 
Should work like others.

**Server Revision**: 
2186

**Comment by Tenoutoften** [comment]
When this happens remember to do .npc info & .gps at the mob

**Comment by Mewmewww** [comment]
[2196][Core] Fix recent creature movement/evade/out of range issues
