### ISSUE TITLE
[NPC]U'cha#9622 should be patrolling around the stone inside Fungal Rock.

### ISSUE THREAD

**Issue by Tenoutoften** [Atlantiss/NetherwingBugtracker#1668]
**Description**: 
[[NPC]U'cha#9622](https://www.wowhead.com/npc=9622/ucha) should be patrolling around the stone deep into Fungal Rock.
![b12c10915f314cdb53bf208f0431fc86](https://user-images.githubusercontent.com/34839199/47100921-f5e18800-d238-11e8-97a4-9b57cc99c860.png)
Currently stands still, video [here](https://www.youtube.com/watch?v=sNhn0zEqumU&feature=youtu.be)
Should be moving around the stone, video [here](https://youtu.be/1T7DXg88SgQ?t=12681)

**Expected behaviour**: 
Patrolling around the stone deep into Fungal Rock.

**Server Revision**: 
2186

**Comment by aresbrutus** [comment]
Fixed in rev `Ilus`.
