### ISSUE TITLE
[NPC][Thousand Needles] Kanati Greycloud

### ISSUE THREAD

**Issue by eryczek1615** [Atlantiss/NetherwingBugtracker#1669]
**Description**: 
[Kanati Greycloud](https://www.wowhead.com/npc=10638)
![image](https://user-images.githubusercontent.com/4455568/47101319-03e3d880-d23a-11e8-970c-a807b266356f.png)

**Current behaviour**:
He has 42/100% HP but before [Protect Kanati Greycloud](https://www.wowhead.com/quest=4966) he had 100%. 
![image](https://user-images.githubusercontent.com/4455568/47101265-d4cd6700-d239-11e8-900f-19abef8a337d.png)

**Expected behaviour**: 
Should have 100%.

**Server Revision**: 
2186

**Comment by Evolvee** [comment]
![image](https://user-images.githubusercontent.com/1942409/47261257-538d0300-d4cb-11e8-81d4-9dd194447912.png)

**Comment by Manaci** [comment]
Fixed
