### ISSUE TITLE
"The First Trial" not able to be turned in

### ISSUE THREAD

**Issue by rhoxxx** [Atlantiss/NetherwingBugtracker#167]
[//]: # (Enclose links to things related to the bug using http://wowhead.com or any other TBC database.)
[//]: # (You can use screenshot ingame to visual the issue.)
[//]: # (Write your tickets according to the format:)
[//]: # ([Quest][Azuremyst Isle] Red Snapper - Very Tasty!)
[//]: # ([NPC] Magistrix Erona)
[//]: # ([Spell][Mage] Fireball)
[//]: # ([Npc][Drop] Ghostclaw Lynx)
[//]: # ([Web] Armory doesnt work)

**Description**: "The First Trial" not able to be turned in

**Current behaviour**: completed the objective for "The First Trial" but was not able turn the quest in, quest giver had a silver ? still

**Expected behaviour**: had the objective finished should be able to turn it in and get the follow up

**Server Revision**:  2028

**Comment by aresbrutus** [comment]
I just tested it my self and I could turn it in. Can you abandon and retake the quest to try again?

**Comment by davismj** [comment]
Just experienced the same thing today.
