### ISSUE TITLE
[NPC]Uhk'loc#6585 should probably patrol a little

### ISSUE THREAD

**Issue by Tenoutoften** [Atlantiss/NetherwingBugtracker#1670]
**Description**: 
[[NPC]Uhk'loc#6585](https://www.wowhead.com/npc=6585/uhkloc#comments)
![0278f93e21c7e2871a38b87810710ba3](https://user-images.githubusercontent.com/34839199/47102244-78b81200-d23c-11e8-9598-82b1ac3893e5.png)
![edde575395c6cd9ccb57ea946adf3c40](https://user-images.githubusercontent.com/34839199/47102245-7950a880-d23c-11e8-8db7-e97b29bac8d8.png)
![57309-uhkloc](https://user-images.githubusercontent.com/34839199/47102247-7b1a6c00-d23c-11e8-8c5d-f72ee8b4c16a.jpg)
![uhk_loc_gorilla_hunter_pet](https://user-images.githubusercontent.com/34839199/47102248-7b1a6c00-d23c-11e8-9e52-c64148211ed1.jpg)
https://www.wowhead.com/npc=6585/uhkloc#comments

I don't have any solid proof other than two images of his position, both in different locations than current spot on Netherwing, and two not very specific comments. But it seems odd that a rare spawn couldn't patrol in the cave.

I think he is suppose to patrol up and down in the room he is currently in. And according to at least 1 of the comments he is suppose to yell for help when pulled.

**Expected behaviour**: 
Patrol up and down in the room.

**Server Revision**: 
2186

**Comment by aresbrutus** [comment]
Fixed in rev `Ilus`.
