### ISSUE TITLE
[NPC]Primal Ooze#6557 should do emote "begins to make a copy of itself!"

### ISSUE THREAD

**Issue by Tenoutoften** [Atlantiss/NetherwingBugtracker#1671]
**Description**: 
[[NPC]Primal Ooze#6557](https://www.wowhead.com/npc=6557/primal-ooze#comments) should do emote "begins to make a copy of itself!"
Can be seen doing it [here vid.](https://youtu.be/1T7DXg88SgQ?t=6439)

**Expected behaviour**: 
Expected to do provided emote.

**Server Revision**: 
2186

**Comment by Evolvee** [comment]
rev Block
