### ISSUE TITLE
[NPC]Primal Ooze#6557's clone, [NPC]Cloned Ooze#9477 should grant experience.

### ISSUE THREAD

**Issue by Tenoutoften** [Atlantiss/NetherwingBugtracker#1672]
**Description**: 
[[NPC]Primal Ooze#6557](https://www.wowhead.com/npc=6557/primal-ooze#abilities) will often try to once use [[Spell]Clone#14146](https://www.wowhead.com/spell=14146/clone) if successful it spawns a  
[[NPC]Cloned Ooze#9477](https://db.excalibur.ws/?npc=9477). The clone should grant experience, currently doesn't [NW version 0 xp](https://www.youtube.com/watch?v=U6ZoDaW3axI&feature=youtu.be).
Experience gained can be seen [here vid](https://youtu.be/1T7DXg88SgQ?t=6455)

backed by [wowhead comment](https://www.wowhead.com/npc=6557/primal-ooze#comments:id=251128)
>Clone Oozes give full experience, so if you don't mind fighting it, it can be in your favor to let the cast finish, since you will get double the exp per mob.

Should also drop silver/copper apparently, can also be seen in the video.

**Expected behaviour**: 
Expected to grant experience.

**Server Revision**: 
2186

**Comment by Evolvee** [comment]
https://github.com/Atlantiss/NetherwingBugtracker/issues/1945
