### ISSUE TITLE
Specific(Id:14) [[NPC]Frenzied Pterrordax#9167 occasionally patrols inside a rock.

### ISSUE THREAD

**Issue by Tenoutoften** [Atlantiss/NetherwingBugtracker#1673]
**Description**: 
Specific [[NPC]Frenzied Pterrordax#9167](https://www.wowhead.com/npc=9167/frenzied-pterrordax) occasionally patrols into a rock, video [here](https://www.youtube.com/watch?v=tL0n9vNTylg&feature=youtu.be)
![f5dc00ee25a23da3d9dd6ea20de6ea7f](https://user-images.githubusercontent.com/34839199/47106031-dac94500-d245-11e8-9228-441a65b17776.png)

**Expected behaviour**: 
Expected to not patrol into a rock.

**Server Revision**: 
2186

**Comment by aresbrutus** [comment]
Fixed in rev `Ilus`.
