### ISSUE TITLE
[NPC]Gorishi Wasp#6551, Id: 12, stuck in terrain

### ISSUE THREAD

**Issue by Tenoutoften** [Atlantiss/NetherwingBugtracker#1675]
**Description**: 
[[NPC]Gorishi Wasp#6551](https://db.excalibur.ws/?npc=6551) stuck in terrain, video [here](https://www.youtube.com/watch?v=Rb1bpxGsOaA&feature=youtu.be)
.gps & .npc info
![c9846ffe63ad04175749b8ac79657a85](https://user-images.githubusercontent.com/34839199/47109509-b6259b00-d24e-11e8-957b-e68a5100379e.png)

**Expected behaviour**: 
Not to be stuck

**Server Revision**: 
2186

**Comment by aresbrutus** [comment]
Fixed in rev `Ilus`.
