### ISSUE TITLE
[quest item] The quest item"The Third Troll Legend" wrongly contains the text from the quest item "Sully Balloo's Letter".

### ISSUE THREAD

**Issue by Dosdaltherir** [Atlantiss/NetherwingBugtracker#1676]
**Description**: 
The quest item "The Third Troll Legend" that you acquire during the quest "Kurzen's Mystery" in Stranglethorn Vale, wrongly contains the text from the quest item "Sully Balloo's Letter".
**Current behaviour**:
Reading "The Third Troll Legend" will display the text from "Sully Balloo's Letter"
**Expected behaviour**: 
Reading "The Third Troll Legend" should display the actual text from "The Third Troll Legend"
**Screenshot**:
![wowscrnshot_101718_222508](https://user-images.githubusercontent.com/43515247/47114562-749bec80-d25c-11e8-82d8-8bd688094db6.jpg)
**Server Revision**: 
rev: 2186.

**Comment by aresbrutus** [comment]
Text found at: https://www.wowhead.com/item=2007/the-third-troll-legend

**Comment by Shanghi** [comment]
This should be fixed in revision 2221. The client's cache has to be deleted to see any changes though.
