### ISSUE TITLE
[NPC] Elder Lake Skulker - Walking Through Water, Not Leashing

### ISSUE THREAD

**Issue by Ceago** [Atlantiss/NetherwingBugtracker#1677]
**Description**:   Elder Lake Skulker, and all other mobs in the area, walk through water weirdly instead of swimming and seem to chase forever without any additional damage.

**Current behaviour**:  Acting like in video.  https://streamable.com/k2cv4  Don't worry no weeb songs this time.

**Expected behaviour**:   Should swim through water and leash at some point.

**Server Revision**: 2191

**Comment by Tereneckla** [comment]
Leash is fixed.

**Comment by duzyizly** [comment]
these mobs still "walk through the wastr" instead of swiming. Leash is fixed.
rev 3403 ptr.
https://tbcdb.com/?npc=1954
https://tbcdb.com/?npc=1953

![Uploading WoWScrnShot_062420_120543.jpg…]()

**Comment by Wolffenstein** [comment]
Blizzlike, confirmed on classic.
