### ISSUE TITLE
[NPC][Eastern Plaguelands]Mercutio Filthgorger

### ISSUE THREAD

**Issue by DeltaLoads** [Atlantiss/NetherwingBugtracker#1678]
[//]: # (Enclose links to things related to the bug using http://wowhead.com or any other TBC database.)
[//]: # (You can use screenshot ingame to visual the issue.)
[//]: # (Write your tickets according to the format:)
[//]: # ([Quest][Azuremyst Isle] Red Snapper - Very Tasty!)
[//]: # ([NPC] Magistrix Erona)
[//]: # ([Spell][Mage] Fireball)
[//]: # ([Npc][Drop] Ghostclaw Lynx)
[//]: # ([Web] Armory doesnt work)

**Description**: 
Same bug as in https://github.com/Atlantiss/NetherwingBugtracker/issues/1363 (opened this one since that one is closed) his adds (https://www.wowhead.com/npc=11887/crypt-robber#outfit) disappear if you feign death while your pet is attacking him and you they are attacking player
**Current behaviour**:
Adds disappear if you use feign death
**Expected behaviour**: 
Adds should attack pet
**Server Revision**: 
2186

**Comment by Evolvee** [comment]
they are specifically scripted to despawn on evade

so this is a core bug probably that they dont switch to pet instead if you had him in their threatlist - if not, then probably wai
