### ISSUE TITLE
([Spell][Hunter][Pets] Screech)

### ISSUE THREAD

**Issue by Thorgrimme** [Atlantiss/NetherwingBugtracker#1679]
[//]: # http://db.hellfire-tbc.com/?spell=24424

**Description**: The spell screech seems to be working fine, but the "demoshout" of the spell produces hardly any threat to the mobs around the pet that it isn't targeting, one tick of mend pet and mobs go for the hunter instead of the pet.

**Current behaviour**:The "demoshout" effect of the spell screech should produce some aoe threat, atm it seems like it has no threat.

**Expected behaviour**: Screech should produce most threat on the current target of the pet, but also some on mobs in melee range around it.

**Server Revision**:

**Comment by Manaci** [comment]
Fixed in Changelog [3162]
