### ISSUE TITLE
[AI Core mechanic] - mobs using slow skills

### ISSUE THREAD

**Issue by Firroth** [Atlantiss/NetherwingBugtracker#168]
**Current behaviour**:
Mob like Sunhawk Spy http://wowwiki.wikia.com/wiki/Sunhawk_Spy 
Use skill hamstring on player even at 100% health of the player or when he stands in meele and fights him head on.

**Expected behaviour**: 
I assume it should work like on Gummy's Felmyst it worked (I believe he did research on it beforehand) and it worked like that on retail that when player starts to "run away from meele" or player "has low hp 1-30% hp+-" that when mobs possessing such skill (not refering to spells like frostbolt etc. only meele ones) only use them then, to make sure their target won't run away from them alive/out of range.

Right now he uses it on timer, doesn't matter what player does or how much hp has - which I assume is stupid and easy to outplay such mob.

**Server Revision**: 
2028

Will be best if more ppl will comment on this one just to be sure it worked like that on retail.

**Comment by Easyfraggy** [comment]
Will need some retail evidence of this.

**Comment by meowmewo** [comment]
Is this mob even supposed to cast Hamstring?

**Comment by Evolvee** [comment]
Never heard of such mechanic. If you prove it via videos/research we will implement it tho.

**Comment by Firroth** [comment]
Disregard this issue, since it's impossible to find a video which could show anything at all, when all are from later expansions and they 2-3hit kill mobs and never go down low on hp or even start to kite them. And I have no spare time to research it. 
I based it from Gummy's Felmyst server and during lvling, those mobs never used slow on me when I was in was in meele range and high on hp, they only did when i was below certain % or tried to run away from them so I wouldn't die. And since I believe Gummy did implement such thing, I also believe he did research on it beforehand and not just added some custom stuff.

So either close this issue, since all videos which I found only show those mobs use demo shout, heroic strike, and mark - +hamstring was never used in them. Or try to research it on your own if you're interested, since this mechanic added to the difficulty anyway.

**Comment by Evolvee** [comment]
his "research" was proven to not be retail-like many times so Im gonna just close this since there is no evidence to it for now

however, if u in the future find some videos of it, feel free to reopen ^^ it would be an interesting mechanic for sure
