### ISSUE TITLE
[Mechanar] Cache of the Legion

### ISSUE THREAD

**Issue by tcberk12** [Atlantiss/NetherwingBugtracker#1680]
**Description**: 

Currently, only the player that loots the Jagged Blue Crystal and Jagged Red Crystal can receive a Badge of Justice from the Cache of the Legion.

**Current behaviour**:

The Cache of the Legion remains locked to other players after the player with the key (obtained by killing the two Gatewatchers) opens the cache. While the gear is able to be rolled off, the badges have to be looted off the cache, and thus only the player with the key can loot it.

**Expected behaviour**: 

Once opened, the Cache of the Legion should become unlocked so all players in the group may loot it. This allows them to get the Badge of Justice, and can also help in situations where Group Loot is not in use (I'm thinking of if the loot is on ML and the ML is not the person with the key, they would be unable to loot the cache and assign the item.)

Source that the Cache should contain a badge: http://wowwiki.wikia.com/wiki/Patch_2.3.0

> The Cache of the Legion can now only be looted by players who are present during some portion of a successful attempt of the Gatewatcher Gyro-Kill and Gatewatcher Iron-Hand encounters. In addition, on Heroic difficulty Gatewatcher Gyro-Kill and Gatewatcher Iron-Hand no longer drop [Badges of Justice]. **Instead, the Cache of the Legion contains a Badge of Justice for each player present.**

So, pre 2.3, both gatekeepers dropped a badge. After that, only 1 badge was awarded and its contained in the cache.

The cache would need to be unlocked in a way so that only the players present for the killing of each of the Gatewatchers can loot it.

**Server Revision**: 
2186

**Comment by Evolvee** [comment]
rev dung
