### ISSUE TITLE
Bloodscalps can hit through walls

### ISSUE THREAD

**Issue by maxturtlesc2** [Atlantiss/NetherwingBugtracker#1686]
[//]: # (Enclose links to things related to the bug using http://wowhead.com or any other TBC database.)
[//]: # (You can use screenshot ingame to visual the issue.)
[//]: # (Write your tickets according to the format:)
[//]: # ([Quest][Azuremyst Isle] Red Snapper - Very Tasty!)
[//]: # ([NPC] Magistrix Erona)
[//]: # ([Spell][Mage] Fireball)
[//]: # ([Npc][Drop] Ghostclaw Lynx)
[//]: # ([Web] Armory doesnt work)
https://gfycat.com/fr/ForthrightPhonyHomalocephale
**Description**: 
Ranged mobs in the ruins of Zul'Kunda can hit you through some walls.
**Current behaviour**:

**Expected behaviour**: 
You should be safe when out of los.
**Server Revision**:

**Comment by Easyfraggy** [comment]
This is not a bug. Some objects don't give LOS in vanilla/TBC - Ask blizzard.
