### ISSUE TITLE
Ghostclaw Lynx aren't resetting 

### ISSUE THREAD

**Issue by Trix115** [Atlantiss/NetherwingBugtracker#169]
In Ghostlands around Zeb'Nowa, there are trolls called Shadowpine Catlords. They are "hunters" and have a pet Ghostclaw Lynx. The trolls reset when u run away, but the pet follows you endlessly. 
 ##Was not able to recreate, might be just some of them.

**Comment by Trix115** [comment]
Followup: Seems some of them have 2 pets, standing ontop of each other so it's hard to see.

**Comment by Trix115** [comment]
Followup: Was able to recreate the cats not resetting, it was either because i had killed the Shadowpine Catlord or because i had dealt damage to it. Overall these mobs need to be looked at.

**Comment by Easyfraggy** [comment]
Could you provide entry+id of the mob with double spawn? I couldn't find it. 

type .npc info when targetting the Catlord.

**Comment by Trix115** [comment]
Catlord: 16345
Ghostclaw Lynx (pet): 16348

**Comment by Easyfraggy** [comment]
Need the ID aswell it says like this: 
![image](https://user-images.githubusercontent.com/36134067/45928221-90072680-bf40-11e8-8df8-c742cfad5b4e.png)

**Comment by Trix115** [comment]
> handled through ingame chat

**Comment by wtRCH** [comment]
Is it fixed?

**Comment by Evolvee** [comment]
hopefully fixed in next hotfix rev
