### ISSUE TITLE
[NPC][Thousand Needles] Grimtotem Bandit - stuck

### ISSUE THREAD

**Issue by eryczek1615** [Atlantiss/NetherwingBugtracker#1691]
**Description**: 
[Grimtotem Bandit](https://www.wowhead.com/npc=10758/grimtotem-bandit)
![image](https://user-images.githubusercontent.com/4455568/47144079-f0cb1a00-d2c6-11e8-905b-94575bd35c49.png)
![image](https://user-images.githubusercontent.com/4455568/47144109-02142680-d2c7-11e8-9569-60e5542fd759.png)

**Current behaviour**:
One of them stuck and he is "Out of range"
https://imgur.com/gxlbSAk

**Expected behaviour**: 
Should work like others.

**Server Revision**: 
2186

**Comment by wtRCH** [comment]
@aresbrutus

**Comment by aresbrutus** [comment]
Fixed after rev `2196`
