### ISSUE TITLE
[Warlock][Pet] 

### ISSUE THREAD

**Issue by Acodin88** [Atlantiss/NetherwingBugtracker#1692]
When Pet attack trash you can take loot at global servers its work difrend y can attack bay pet andd y get loot

**Comment by wtRCH** [comment]
no priority due to reasearch

**Comment by Easyfraggy** [comment]
I have no idea what this means.

**Comment by tcberk12** [comment]
toto

**Comment by nullv0id** [comment]
On retail, if your pet killed a mob solo, as in you didn't also attack the mob, you got no loot, probably not exp either. This was likely so you couldn't "afk farm" with ur pet.
