### ISSUE TITLE
[Ungoro] Lar'korwi

### ISSUE THREAD

**Issue by Azalen** [Atlantiss/NetherwingBugtracker#1693]
**Description**: 
https://classicdb.ch/?npc=9684#comments

**Current behaviour**:
He just spawns in front of the player not attacking for some seconds before aggroing.

**Expected behaviour**: 
He should spawn further away and run towards the placed meat and aggro player.
Proof: https://www.youtube.com/watch?v=e29fCKrygps

**Server Revision**: 
[2186]

**Comment by Tenoutoften** [comment]
Similar to https://github.com/Atlantiss/NetherwingBugtracker/issues/1529, its known that spawned NPCs are often slow

**Comment by Evolvee** [comment]
rev yummy
