### ISSUE TITLE
[NPC] Monstrous Crawler (Swamp of Sorrows)

### ISSUE THREAD

**Issue by maxturtlesc2** [Atlantiss/NetherwingBugtracker#1695]
[//]: # (Enclose links to things related to the bug using http://wowhead.com or any other TBC database.)
[//]: # (You can use screenshot ingame to visual the issue.)
[//]: # (Write your tickets according to the format:)
[//]: # ([Quest][Azuremyst Isle] Red Snapper - Very Tasty!)
[//]: # ([NPC] Magistrix Erona)
[//]: # ([Spell][Mage] Fireball)
[//]: # ([Npc][Drop] Ghostclaw Lynx)
[//]: # ([Web] Armory doesnt work)
<img src="https://i.imgur.com/qcJDnL3.png">
**Description**: 
Multiple missing spawn points for Monstrous Crawlers according to classicdb and Wow Cartographe (US and FR databases), especially in the top right part of the zone, and in deep water.
<img src="https://i.imgur.com/k4FvZyd.png">
<img src="https://i.imgur.com/8LpahPo.png">
**Current behaviour**:
Missing spawn points.
**Expected behaviour**: 
More spawn points for Monstrous Crawler.
**Server Revision**:

**Comment by aresbrutus** [comment]
Could you provide me the link where you got the map pictures from?

**Comment by maxturtlesc2** [comment]
> Could you provide me the link where you got the map pictures from?

It's not online it's on the Wow cartographe soft.

**Comment by aresbrutus** [comment]
Fixed in rev `Ilus`.
