### ISSUE TITLE
[Quest] Proof of Deed [NPC] Curator Thorius

### ISSUE THREAD

**Issue by Mewmewww** [Atlantiss/NetherwingBugtracker#1696]
[//]: # (Enclose links to things related to the bug using http://wowhead.com or any other TBC database.)
[//]: # (You can use screenshot ingame to visual the issue.)
[//]: # (Write your tickets according to the format:)
[//]: # ([Quest][Azuremyst Isle] Red Snapper - Very Tasty!)
[//]: # ([NPC] Magistrix Erona)
[//]: # ([Spell][Mage] Fireball)
[//]: # ([Npc][Drop] Ghostclaw Lynx)
[//]: # ([Web] Armory doesnt work)

**Description**: 
After giving him Margol the Ragers horn, he walks directly through the horde catapult to his destination. 
**Current behaviour**:
Walks through the horde catapult.
**Expected behaviour**: 
Should walk around it, needs adjusting on his pathing. 
**Server Revision**: 
2186

**Comment by Evolvee** [comment]
@Wolffenstein this was your script

**Comment by Wolffenstein** [comment]
Fixed in rev 3368.
