### ISSUE TITLE
[NPC] Dark Iron Slaver - Net ability

### ISSUE THREAD

**Issue by Mewmewww** [Atlantiss/NetherwingBugtracker#1697]
[//]: # (Enclose links to things related to the bug using http://wowhead.com or any other TBC database.)
[//]: # (You can use screenshot ingame to visual the issue.)
[//]: # (Write your tickets according to the format:)
[//]: # ([Quest][Azuremyst Isle] Red Snapper - Very Tasty!)
[//]: # ([NPC] Magistrix Erona)
[//]: # ([Spell][Mage] Fireball)
[//]: # ([Npc][Drop] Ghostclaw Lynx)
[//]: # ([Web] Armory doesnt work)

**Description**: 
Net ability
**Current behaviour**:
Uses net every single time a previous net has faded. I can't move vs them.
**Expected behaviour**: 
Should have a cooldown, or at least use less frequently
**Server Revision**: 
2186

**Comment by Evolvee** [comment]
rev Block
