### ISSUE TITLE
[NPC]Gordunni Brute#5232 shouldn't be able to use [Spell]Uppercut#10966 while stunned

### ISSUE THREAD

**Issue by Tenoutoften** [Atlantiss/NetherwingBugtracker#1699]
**Description**: 
[[NPC]Gordunni Brute#5232](https://db.excalibur.ws/?npc=5232#abilities) can currently use [[Spell]Uppercut#10966](https://db.excalibur.ws/?spell=10966) while affected by stun, in this case [[Spell]Hammer of Justice#10308](https://db.excalibur.ws/?spell=10308) but I've also heard from a friend that they can use it while affected by [[Spell]Freezing Trap#14310](https://db.excalibur.ws/?spell=14310)

Video demonstration [here](https://www.youtube.com/watch?v=rP8OxmeKATQ&feature=youtu.be)

**Expected behaviour**: 
[[NPC]Gordunni Brute#5232](https://db.excalibur.ws/?npc=5232#abilities) shouldn't be able to [[Spell]Uppercut#10966](https://db.excalibur.ws/?spell=10966) while stunned / trapped

**Server Revision**: 
2186

**Comment by Evolvee** [comment]
rev Block
