### ISSUE TITLE
Food/Drink gets wasted while moving

### ISSUE THREAD

**Issue by kelsul** [Atlantiss/NetherwingBugtracker#17]
[//]: # (Enclose links to things related to the bug using http://wowhead.com or any other TBC database.)
[//]: # (You can use screenshot ingame to visual the issue.)
[//]: # (Write your tickets according to the format:)
[//]: # ([Quest][Azuremyst Isle] Red Snapper - Very Tasty!)
[//]: # ([NPC] Magistrix Erona)
[//]: # ([Spell][Mage] Fireball)
[//]: # ([Npc][Drop] Ghostclaw Lynx)
[//]: # ([Web] Armory doesnt work)

**Description**: 
When you try to eat or drink while moving it doesnt tell you "cannot do this while moving", it just does the animation and wastes the food/drink. 
**Current behaviour**:
^
**Expected behaviour**: 
Should tell you that you cannot do this while moving and not use up the items. 
**Server Revision**:

**Comment by Navedonar** [comment]
.

**Comment by sifiuocz** [comment]
can be closed. Fixed in rev 2417

**Comment by Tenoutoften** [comment]
Confirm fixed [here](https://www.youtube.com/watch?v=IbrpefS8I20&feature=youtu.be)
