### ISSUE TITLE
[NPC][The Barrens]Barrens Kodo

### ISSUE THREAD

**Issue by DeltaLoads** [Atlantiss/NetherwingBugtracker#1702]
[//]: # (Enclose links to things related to the bug using http://wowhead.com or any other TBC database.)
[//]: # (You can use screenshot ingame to visual the issue.)
[//]: # (Write your tickets according to the format:)
[//]: # ([Quest][Azuremyst Isle] Red Snapper - Very Tasty!)
[//]: # ([NPC] Magistrix Erona)
[//]: # ([Spell][Mage] Fireball)
[//]: # ([Npc][Drop] Ghostclaw Lynx)
[//]: # ([Web] Armory doesnt work)

**Description**: 
There are some vanishing Barrens Kodos that should be moving around in pack
https://streamable.com/1t6cj
**Current behaviour**:
Kodos shouldn't be vanishing
**Expected behaviour**: 
Kodos should simply travel in pack
**Server Revision**: 
2186

**Comment by wtRCH** [comment]
@aresbrutus

**Comment by The14me** [comment]
Cant reproduce.
