### ISSUE TITLE
[Itemization] Arena Season 1 Non-Set Epics: Alliance - Wrong Stats

### ISSUE THREAD

**Issue by Azalen** [Atlantiss/NetherwingBugtracker#1704]
### **Description**: 
In Arena Season 1 there were two separate Items for each Alliance and Horde of Non-Set Epics with nametags "General" and "Marshal". This system was abandoned in the following arena seasons for the shared nametags "Veteran" (season 2), "Vindicator" (season 3) and "Guardian" (season 4).

### **Current behaviour**:
Only the horde side season 1 Non-Set Epics ("General) have the correct item stats right now. The alliance versions ("Marshal") have post 2.1 item stats.

There are 36 items affected. (6x cloth, 12x leather, 9x mail, 9xplate) I'll proof this on the example "Dragonhide Bracers". 

**The Horde version** (General's Dragonhide Bracers ID=28445) **is correct** on Netherwing atm:
Patch 2.0.3 (before May 15, 2007)
https://web.archive.org/web/20070418210232/http://www.thottbot.com:80/i28445
Patch 2.1 (after May 15, 2007)
https://web.archive.org/web/20070811110226/http://www.thottbot.com:80/i28445

**The Alliance version** (Marshal's Dragonhide Bracers ID=28978) **is not correct** and needs adjustments:
Patch 2.0.3 (before May 15, 2007)
https://web.archive.org/web/20070510131352/http://www.thottbot.com:80/i28978
Patch 2.1 (after May 15, 2007)
https://web.archive.org/web/20070823104354/http://www.thottbot.com:80/i28978

### **Expected behaviour**: 
All Alliance season 1 Non-Set Epics ("Marshal") need stat adjustments. You can copy the exact stats from the belonging "General" item. To make this easier for you I'll post all linked ID's: (ignore the stuff after the name):

**Cloth Armor:**

		{ 28405, General's Dreadweave Cuffs", "=ds=", "13875 #faction# 20 #wsg#" },
		{ 28981, Marshal's Dreadweave Cuffs", "=ds=", "13875 #faction# 20 #wsg#" },
		{ 28404, General's Dreadweave Belt", "=ds=", "21000 #faction# 40 #ab#" },
		{ 28980, Marshal's Dreadweave Belt", "=ds=", "21000 #faction# 40 #ab#" },
		{ 28402, General's Dreadweave Stalkers", "=ds=", "21000 #faction# 40 #eos#" },
		{ 28982, Marshal's Dreadweave Stalkers", "=ds=", "21000 #faction# 40 #eos#" },

		{ 28411, General's Silk Cuffs", "=ds=", "13875 #faction# 20 #wsg#" },
		{ 29002, Marshal's Silk Cuffs", "=ds=", "13875 #faction# 20 #wsg#" },
		{ 28409, General's Silk Belt", "=ds=", "21000 #faction# 40 #ab#" },
		{ 29001, Marshal's Silk Belt", "=ds=", "21000 #faction# 40 #ab#" },
		{ 28410, General's Silk Footguards", "=ds=", "21000 #faction# 40 #eos#" },
		{ 29003, Marshal's Silk Footguards", "=ds=", "21000 #faction# 40 #eos#" },

**Leather Armor:**

		{ 28445, General's Dragonhide Bracers", "=ds=", "13875 #faction# 20 #wsg#" },
		{ 28978, Marshal's Dragonhide Bracers", "=ds=", "13875 #faction# 20 #wsg#" },
		{ 28443, General's Dragonhide Belt", "=ds=", "21000 #faction# 40 #ab#" },
		{ 28976, Marshal's Dragonhide Belt", "=ds=", "21000 #faction# 40 #ab#" },
		{ 28444, General's Dragonhide Boots", "=ds=", "21000 #faction# 40 #eos#" },
		{ 28977, Marshal's Dragonhide Boots", "=ds=", "21000 #faction# 40 #eos#" },

		{ 31598, General's Kodohide Bracers", "=ds=", "13875 #faction# 20 #wsg#" },
		{ 31599, Marshal's Kodohide Bracers", "=ds=", "13875 #faction# 20 #wsg#" },
		{ 31594, General's Kodohide Belt", "=ds=", "21000 #faction# 40 #ab#" },
		{ 31596, Marshal's Kodohide Belt", "=ds=", "21000 #faction# 40 #ab#" },
		{ 31595, General's Kodohide Boots", "=ds=", "21000 #faction# 40 #eos#" },
		{ 31597, Marshal's Kodohide Boots", "=ds=", "21000 #faction# 40 #eos#" },

		{ 28424, General's Leather Bracers", "=ds=", "13875 #faction# 20 #wsg#" },
		{ 28988, Marshal's Leather Bracers", "=ds=", "13875 #faction# 20 #wsg#" },
		{ 28423, General's Leather Belt", "=ds=", "21000 #faction# 40 #ab#" },
		{ 28986, Marshal's Leather Belt", "=ds=", "21000 #faction# 40 #ab#" },
		{ 28422, General's Leather Boots", "=ds=", "21000 #faction# 40 #eos#" },
		{ 28987, Marshal's Leather Boots", "=ds=", "21000 #faction# 40 #eos#" },

		{ 28448, General's Wyrmhide Bracers", "=ds=", "13875 #faction# 20 #wsg#" },
		{ 29006, Marshal's Wyrmhide Bracers", "=ds=", "13875 #faction# 20 #wsg#" },
		{ 28446, General's Wyrmhide Belt", "=ds=", "21000 #faction# 40 #ab#" },
		{ 29004, Marshal's Wyrmhide Belt", "=ds=", "21000 #faction# 40 #ab#" },
		{ 28447, General's Wyrmhide Boots", "=ds=", "21000 #faction# 40 #eos#" },
		{ 29005, Marshal's Wyrmhide Boots", "=ds=", "21000 #faction# 40 #eos#" },

**Mail Armor:**

		{ 28451, General's Chain Bracers", "=ds=", "13875 #faction# 20 #wsg#" },
		{ 28973, Marshal's Chain Bracers", "=ds=", "13875 #faction# 20 #wsg#" },
		{ 28450, General's Chain Girdle", "=ds=", "21000 #faction# 40 #ab#" },
		{ 28974, Marshal's Chain Girdle", "=ds=", "21000 #faction# 40 #ab#" },
		{ 28449, General's Chain Sabatons", "=ds=", "21000 #faction# 40 #eos#" },
		{ 28975, Marshal's Chain Sabatons", "=ds=", "21000 #faction# 40 #eos#" },

		{ 28605, General's Linked Bracers", "=ds=", "13875 #faction# 20 #wsg#" },
		{ 28989, Marshal's Linked Bracers", "=ds=", "13875 #faction# 20 #wsg#" },
		{ 28629, General's Linked Girdle", "=ds=", "21000 #faction# 40 #ab#" },
		{ 28990, Marshal's Linked Girdle", "=ds=", "21000 #faction# 40 #ab#" },
		{ 28630, General's Linked Sabatons", "=ds=", "21000 #faction# 40 #eos#" },
		{ 28991, Marshal's Linked Sabatons", "=ds=", "21000 #faction# 40 #eos#" },

		{ 28638, General's Mail Bracers", "=ds=", "13875 #faction# 20 #wsg#" },
		{ 28992, Marshal's Mail Bracers", "=ds=", "13875 #faction# 20 #wsg#" },
		{ 28639, General's Mail Girdle", "=ds=", "21000 #faction# 40 #ab#" },
		{ 28993, Marshal's Mail Girdle", "=ds=", "21000 #faction# 40 #ab#" },
		{ 28640, General's Mail Sabatons", "=ds=", "21000 #faction# 40 #eos#" },
		{ 28994, Marshal's Mail Sabatons", "=ds=", "21000 #faction# 40 #eos#" },

**Plate Armor:**

		{ 28643, General's Lamellar Bracers", "=ds=", "13875 #faction# 20 #wsg#" },
		{ 28984, Marshal's Lamellar Bracers", "=ds=", "13875 #faction# 20 #wsg#" },
		{ 28641, General's Lamellar Belt", "=ds=", "21000 #faction# 40 #ab#" },
		{ 28983, Marshal's Lamellar Belt", "=ds=", "21000 #faction# 40 #ab#" },
		{ 28642, General's Lamellar Greaves", "=ds=", "21000 #faction# 40 #eos#" },
		{ 28985, Marshal's Lamellar Greaves", "=ds=", "21000 #faction# 40 #eos#" },

		{ 28381, General's Plate Bracers", "=ds=", "13875 #faction# 20 #wsg#" },
		{ 28996, Marshal's Plate Bracers", "=ds=", "13875 #faction# 20 #wsg#" },
		{ 28385, General's Plate Belt", "=ds=", "21000 #faction# 40 #ab#" },
		{ 28995, Marshal's Plate Belt", "=ds=", "21000 #faction# 40 #ab#" },
		{ 28383, General's Plate Greaves", "=ds=", "21000 #faction# 40 #eos#" },
		{ 28997, Marshal's Plate Greaves", "=ds=", "21000 #faction# 40 #eos#" },

		{ 28646, General's Scaled Bracers", "=ds=", "13875 #faction# 20 #wsg#" },
		{ 28999, Marshal's Scaled Bracers", "=ds=", "13875 #faction# 20 #wsg#" },
		{ 28644, General's Scaled Belt", "=ds=", "21000 #faction# 40 #ab#" },
		{ 28998, Marshal's Scaled Belt", "=ds=", "21000 #faction# 40 #ab#" },
		{ 28645, General's Scaled Greaves", "=ds=", "21000 #faction# 40 #eos#" },
		{ 29000, Marshal's Scaled Greaves", "=ds=", "21000 #faction# 40 #eos#" },

**Server Revision**: 
[2177]

**Comment by Evolvee** [comment]
pvp vendors arent done yet

**Comment by aresbrutus** [comment]
Thank you Azalen, for bringing this to our attention and for making a detailed report so that I could fix it much easier. 

This should be fixed at rev `Nariman` but please recheck.
