### ISSUE TITLE
[NPC][Misc]Willix the Importer

### ISSUE THREAD

**Issue by DeltaLoads** [Atlantiss/NetherwingBugtracker#1705]
[//]: # (Enclose links to things related to the bug using http://wowhead.com or any other TBC database.)
[//]: # (You can use screenshot ingame to visual the issue.)
[//]: # (Write your tickets according to the format:)
[//]: # ([Quest][Azuremyst Isle] Red Snapper - Very Tasty!)
[//]: # ([NPC] Magistrix Erona)
[//]: # ([Spell][Mage] Fireball)
[//]: # ([Npc][Drop] Ghostclaw Lynx)
[//]: # ([Web] Armory doesnt work)

**Description**: 
Small typo in his quote "Egads! Ennemy on me!"
**Current behaviour**:
"Egads! Ennemy on me!"
**Expected behaviour**: 
"Egads! Enemy on me!"
**Server Revision**: 
2186

**Comment by Evolvee** [comment]
rev Block
