### ISSUE TITLE
[Quest][Desolace] Befouled by Satyr

### ISSUE THREAD

**Issue by Galawer** [Atlantiss/NetherwingBugtracker#1706]
**Description**: 
https://www.wowhead.com/quest=1434/befouled-by-satyr

**Current behaviour**:
Quest becomes available after completing [Alliance Relations Part 2](https://www.wowhead.com/quest=1433/alliance-relations)

**Expected behaviour**: 
According to a comment on Wowhead and Zygor's Guide, it should become available after completing [Alliance Relations Part 1](https://www.wowhead.com/quest=1432/alliance-relations)

**Server Revision**: 
2186

**Comment by Shanghi** [comment]
This should be fixed in revision 2221.
