### ISSUE TITLE
[Core] Pulling mobs with totems

### ISSUE THREAD

**Issue by Galawer** [Atlantiss/NetherwingBugtracker#1707]
**Current behaviour**:
If a mob walks into a totem and pulls, it instantly resets: [video](https://streamable.com/r6n1u)

**Expected behaviour**: 
The mob should attack the totem and then the totem's owner.

**Server Revision**: 
2186

**Comment by Galawer** [comment]
rev 2229

Mobs will now kill totems, but they still don't attack the Shaman after: [video](https://streamable.com/edsey)

**Comment by Daggotur** [comment]
Confirmed - they will evade right after they kill a totem

**Comment by Tereneckla** [comment]
Fixed
