### ISSUE TITLE
Eliza despawns too quickly after you kill her in Duskwood

### ISSUE THREAD

**Issue by craigsurbrook** [Atlantiss/NetherwingBugtracker#1709]
[//]: # (Enclose links to things related to the bug using http://wowhead.com or any other TBC database.)
[//]: # (You can use screenshot ingame to visual the issue.)
[//]: # (Write your tickets according to the format:)
[//]: # ([Quest][Azuremyst Isle] Red Snapper - Very Tasty!)
[//]: # ([NPC] Magistrix Erona)
[//]: # ([Spell][Mage] Fireball)
[//]: # ([Npc][Drop] Ghostclaw Lynx)
[//]: # ([Web] Armory doesnt work)

**Description**: 
Eliza in Duskwood, when you click her grave she appears, and shortly after you attack her a bodyguard appears.

**Current behaviour**:
I killed her, then concentrated on her bodyguard until he died, and then looted his body. I then went to loot Eliza's body and her "heart" was briefly seen, and then the loot window disappeared... because her body had already despawned. I had to then do it all over again and make sure to immediately loot her body so that it wouldn't despawn and I could get her heart.

**Expected behaviour**: 
You should be able to kill her, then kill her bodyguard and still have time to loot her body before she despawns.

**Server Revision**:

**Comment by Evolvee** [comment]
rev Block
