### ISSUE TITLE
[NPC][Drop] Siltfin Murloc

### ISSUE THREAD

**Issue by Sinyr** [Atlantiss/NetherwingBugtracker#171]
[//]: # (Enclose links to things related to the bug using http://wowhead.com or any other TBC database.)
[//]: # (You can use screenshot ingame to visual the issue.)
[//]: # (Write your tickets according to the format:)
[//]: # ([Quest][Azuremyst Isle] Red Snapper - Very Tasty!)
[//]: # ([NPC] Magistrix Erona)
[//]: # ([Spell][Mage] Fireball)
[//]: # ([Npc][Drop] Ghostclaw Lynx)
[//]: # ([Web] Armory doesnt work)
**Current behaviour**:
Plans: Copper Chain Vest dropped more than 10 times from Siltfin Murlocs in a span of 5-10 minutes. No other green item dropped in the meantime.
![plans](https://user-images.githubusercontent.com/9539181/45928172-8c26d480-bf3f-11e8-9dec-515cc6ac28b7.png)

**Expected behaviour**: 
Drop rate for Plans: Copper Chain Vest should be way lower.

**Server Revision**: 
2028

**Comment by aresbrutus** [comment]
Will be fixed next rev.
