### ISSUE TITLE
Forsaken courier can get stalled in Arathi Highlands, and they can walk underground.

### ISSUE THREAD

**Issue by craigsurbrook** [Atlantiss/NetherwingBugtracker#1710]
[//]: # (Enclose links to things related to the bug using http://wowhead.com or any other TBC database.)
[//]: # (You can use screenshot ingame to visual the issue.)
[//]: # (Write your tickets according to the format:)
[//]: # ([Quest][Azuremyst Isle] Red Snapper - Very Tasty!)
[//]: # ([NPC] Magistrix Erona)
[//]: # ([Spell][Mage] Fireball)
[//]: # ([Npc][Drop] Ghostclaw Lynx)
[//]: # ([Web] Armory doesnt work)

**Description**: 
The quest to get the document from the Forsaken courier (who is supposed to walk all the way from the Go'shek farm and through the Hillsbrad foothills) can get stuck in the Apothecary shack at the farm. To get it unstuck I had to attack it (used range in this case) and they all ran out, including the Apothecary. I was killed by the mass attack and ran back. The courier was no longer around with his bodyguards, so I figured they finally were out on the road. I mounted and followed the road, until I was seeing, very briefly (as I was almost on top of them) the red nameplates "appear" at road level, and then they would disappear. Running over the top of the nameplates aggro'd them, and as I backed up they popped up to road level (this was about directly below Refuge Point if you look at the map). I was then able to kill the courier and get the documents.
Later on, about an hour later, I saw the courier and his bodyguard walking along the road in Hillsbrad, so it appears as though after unstucking them, they stayed unstuck and walked properly from then on.

**Current behaviour**:
Can get stuck in the Apothecary shack. Can walk underground along some areas of the road in Arathi.

**Expected behaviour**: 
Shouldn't get stuck in the Apothecary shack. Should never walk so that they dip underground along any stretch of the road in Arathi.

**Server Revision**:

**Comment by aresbrutus** [comment]
Related to formations: https://github.com/Atlantiss/NetherwingBugtracker/issues/826
