### ISSUE TITLE
[NPC] couple ashenvale npcs walking on the spot and unattackable

### ISSUE THREAD

**Issue by DarthNekr0s** [Atlantiss/NetherwingBugtracker#1712]
**Description**: ghostpaw howler (entry 3824, id 17) is walking in one place and wont let me attack if i try to, also wont register im there and attack me either. a nearby Foulweald Totemic is also displaying this behaviour (entry 3750, id 1)

**Current behaviour**: https://streamable.com/t6z8v

**Expected behaviour**:  behaving as normal npcs

**Server Revision**:  2186

**Comment by aresbrutus** [comment]
Fixed after rev `2196`
