### ISSUE TITLE
[Quest][Item] Tactical Assignment

### ISSUE THREAD

**Issue by kkumbaya** [Atlantiss/NetherwingBugtracker#1713]
Envelope is empty most of the time. At one point I had to retake the quest 8 times to find the quest starting scroll inside.
![wow_2018-10-19_17-05-21](https://user-images.githubusercontent.com/40691510/47197285-c3af6200-d3c1-11e8-8732-56a3daf449fb.jpg)

**Server Revision**: 2186

**Comment by Wolffenstein** [comment]
Fixed.
