### ISSUE TITLE
[NPC]War Reaver#7039 shouldn't be immune to stun

### ISSUE THREAD

**Issue by Tenoutoften** [Atlantiss/NetherwingBugtracker#1714]
**Description**: 
[[NPC]War Reaver#7039](https://www.wowhead.com/npc=7039/war-reaver#comments) shouldn't be immune to stun, currently are shown here: https://www.youtube.com/watch?v=tsAxFwmZyP0&feature=youtu.be

A [[NPC]War Reaver#7039](https://www.wowhead.com/npc=7039/war-reaver#comments) getting stunned on retail by [[Spell]Intimidation#19577](https://db.excalibur.ws/?spell=19577) https://www.youtube.com/watch?v=EZYdJuVzwhQ

**Expected behaviour**: 
Expected to be vulnerable to stun.

**Server Revision**: 
2186

**Comment by Evolvee** [comment]
timestamp?

**Comment by Tenoutoften** [comment]
https://youtu.be/EZYdJuVzwhQ?t=2089

**Comment by Evolvee** [comment]
rev yummy
