### ISSUE TITLE
[Movement][NPC]War Reaver#7039, lots of missing patrols in Ruins of Thaurissan, Burning Steppes

### ISSUE THREAD

**Issue by Tenoutoften** [Atlantiss/NetherwingBugtracker#1715]
**Description**: 
Watch this https://youtu.be/EZYdJuVzwhQ?t=1760 until https://youtu.be/EZYdJuVzwhQ?t=1828 ~50 seconds. Joana is riding from 
![460820176fb4bbc29e65c8e854a86027](https://user-images.githubusercontent.com/34839199/47200936-4d3a4200-d378-11e8-8cc1-9e3d82cb7b93.png)
into Ruins of Thaurissan. He looks over the camp and all he can see is 2 x [[NPC]War Reaver#7039](https://www.wowhead.com/npc=7039/war-reaver#comments). Eventually get attacked by one patrol from the west, and narrowly escapes a patrol coming from the east that he kills in a few seconds anyway.

He turns around for a second (facing the west) at https://youtu.be/EZYdJuVzwhQ?t=1921 and he can spot another [[NPC]War Reaver#7039](https://www.wowhead.com/npc=7039/war-reaver#comments) suddenly - but when he is done killing his current  [[NPC]War Reaver#7039](https://www.wowhead.com/npc=7039/war-reaver#comments) to head west the  [[NPC]War Reaver#7039](https://www.wowhead.com/npc=7039/war-reaver#comments) he spotted is now gone: https://youtu.be/EZYdJuVzwhQ?t=1949

------------------------

Here is a [video](https://www.youtube.com/watch?v=RQ8UKmPtbH4&feature=youtu.be) of the same place on Netherwing, instead of spotting 2x [[NPC]War Reaver#7039](https://www.wowhead.com/npc=7039/war-reaver#comments) there is 7. None of them have any patrol, 4 of them walk around a little, ID: 1, 3, 11, 16. 3 of them stand completely still, ID: 13,14, 18

----------------------------

Additional two partial patrol routes here: https://youtu.be/EZYdJuVzwhQ?t=2021
![050c8d0e786ab297fef9fc7d66b5a211](https://user-images.githubusercontent.com/34839199/47201964-f33b7b80-d37b-11e8-94c6-b4a4c9e12ad3.png)

---------------------------------

Id: 7 is missing on https://youtu.be/EZYdJuVzwhQ?t=2187
![74d22b453be042008fcc144ec998c714](https://user-images.githubusercontent.com/34839199/47202437-64c7f980-d37d-11e8-9d9a-a11365546563.png)

--------------------------------

Id: 4 is missing on https://youtu.be/EZYdJuVzwhQ?t=2322
![bc73b962278546b6ed9956427032d74d](https://user-images.githubusercontent.com/34839199/47202505-9e990000-d37d-11e8-9c8f-a1568af96b36.png)

----------------------------

Id: 10 missing at https://youtu.be/EZYdJuVzwhQ?t=2395
![5c706cde39094b683d8c3b518542bed5](https://user-images.githubusercontent.com/34839199/47202628-03ecf100-d37e-11e8-81db-8999723bb484.png)

--------------------------------------------

![7aa68e80f825013698a5db3d37324be1](https://user-images.githubusercontent.com/34839199/47201165-3c3e0080-d379-11e8-8bf7-26b310b2602c.png)

**Expected behaviour**: 
Expect a strong majority of these to patrol.

**Server Revision**: 
2186

**Comment by aresbrutus** [comment]
Fixed in rev `Ilus`.
