### ISSUE TITLE
Id: 10, [NPC]Scalding Broodling#7048 "out of range" can't be attacked

### ISSUE THREAD

**Issue by Tenoutoften** [Atlantiss/NetherwingBugtracker#1716]
**Description**: 
Id: 10, [[NPC]Scalding Broodling#7048](https://db.excalibur.ws/?npc=7048) "out of range" can't be attacked
https://www.youtube.com/watch?v=aRo8_pSZ_U0&feature=youtu.be

**Expected behaviour**: 
Expected to work like the others

**Server Revision**: 
2186

**Comment by aresbrutus** [comment]
Fixed after rev `2196`
