### ISSUE TITLE
[NPC] Burning Blade mobs at Thunder Axe Fortress

### ISSUE THREAD

**Issue by Galawer** [Atlantiss/NetherwingBugtracker#1717]
**Current behaviour**:
Most of the mobs there aren't holding weapons at all or are using wrong ones.

**Expected behaviour**: 
~~[Burning Blade Augur](https://www.wowhead.com/npc=4663/burning-blade-augur#screenshots:id=78871) should be using a staff.~~
~~[Burning Blade Reaver](https://www.wowhead.com/npc=4664/burning-blade-reaver#screenshots:id=12881) should be using a 2-handed sword.~~
~~[Burning Blade Adept](https://www.wowhead.com/npc=4665/burning-blade-adept#screenshots:id=41000) should be using a staff.~~
~~[Burning Blade Felsworn](https://www.wowhead.com/npc=4666/burning-blade-felsworn#screenshots:id=12879) should be dual-wielding daggers.~~
[Burning Blade Shadowmage](https://www.wowhead.com/npc=4667/burning-blade-shadowmage#screenshots:id=41007) should be using a staff, currently he's holding a mining pick.

**Server Revision**: 
2186

**Comment by aresbrutus** [comment]
Fixed 4 out of 5 of the issues in rev `Ilus`

**Comment by Wolffenstein** [comment]
Fixed in rev 3400.
