### ISSUE TITLE
Ungoro Crater [NPC] Un'Goro Apes And Ravasaurs

### ISSUE THREAD

**Issue by Mewmewww** [Atlantiss/NetherwingBugtracker#1719]
[//]: # (Enclose links to things related to the bug using http://wowhead.com or any other TBC database.)
[//]: # (You can use screenshot ingame to visual the issue.)
[//]: # (Write your tickets according to the format:)
[//]: # ([Quest][Azuremyst Isle] Red Snapper - Very Tasty!)
[//]: # ([NPC] Magistrix Erona)
[//]: # ([Spell][Mage] Fireball)
[//]: # ([Npc][Drop] Ghostclaw Lynx)
[//]: # ([Web] Armory doesnt work)

**Description**: 
I know this has been reported before but this is so weird. Most of the time I loot these creatures, they give me the loot option again, only to see nothing in the loot window. This stops the progression of skinning and this is occurring way too much if has to be like this.
#1634 
**Current behaviour**:
Out of 3/5 mobs of these kinds, I can't skin because of the loot window having nothing in it. 
**Expected behaviour**: 
Either too high percentage of nothing in the loot window AFTER having looted, bugged or an insane feature :peepoSad:
**Server Revision**: 
2186

**Comment by Tenoutoften** [comment]
Just comment in the other issue instead of starting a new :thinking:

**Comment by Mewmewww** [comment]
If you did click on it, it's closed so I assumed i couldn't post in it? 

> Just comment in the other issue instead of starting a new 🤔

**Comment by Tenoutoften** [comment]
I haven't had any issues commenting on closed issues. What error message do you get?

**Comment by Mewmewww** [comment]
> I haven't had any issues commenting on closed issues. What error message do you get?

I haven't tried, I'm just pointing out that since it was closed for a reason, opening a new thread would be the correct action in my opinion.

**Comment by Azalen** [comment]
https://github.com/Atlantiss/NetherwingBugtracker/issues/1634 for reference; I, too, think this had to be adressed but I got shutdown by bossman.

**Comment by Azalen** [comment]
I think this issue is getting bigger and bigger. I am now in WPL and it continues.

![wowscrnshot_102018_124718](https://user-images.githubusercontent.com/20336567/47254729-70431f80-d466-11e8-95c3-c069849fdde0.jpg)

Probably from the Scourgestones, that are in the loot table but hidden since I dont have the trinket equipped.

**Comment by Azalen** [comment]
Ye confirmed from the Scourgestones. Every 2nd mob there has empty loot windows after looting.

**Comment by Evolvee** [comment]
@Wolffenstein ^^

**Comment by Mikik3jr** [comment]
In Un'Goro I am having the same issue:
![wowscrnshot_102618_194115](https://user-images.githubusercontent.com/43505031/47583295-4e123b80-d957-11e8-9a96-2c03aeaf385b.jpg)
![wowscrnshot_102618_194122](https://user-images.githubusercontent.com/43505031/47583296-4eaad200-d957-11e8-86bd-316141ac95f1.jpg)

**Comment by Tereneckla** [comment]
Not happening as of now
