### ISSUE TITLE
[Quest][Bloodmyst Isle] The Sun Gate

### ISSUE THREAD

**Issue by kudryashov-n** [Atlantiss/NetherwingBugtracker#172]
[//]: # (Enclose links to things related to the bug using http://wowhead.com or any other TBC database.)
[//]: # (You can use screenshot ingame to visual the issue.)
[//]: # (Write your tickets according to the format:)
[//]: # ([Quest][Azuremyst Isle] Red Snapper - Very Tasty!)
[//]: # ([NPC] Magistrix Erona)
[//]: # ([Spell][Mage] Fireball)
[//]: # ([Npc][Drop] Ghostclaw Lynx)
[//]: # ([Web] Armory doesnt work)

**Description**: 
Can't complete the quest
**Current behaviour**:
Getting message "Invalid target" when clicking at the portal.
**Expected behaviour**: 
Clicking should finish the quest
**Server Revision**:

**Comment by Evolvee** [comment]
![image](https://user-images.githubusercontent.com/1942409/45928861-66eb9380-bf4a-11e8-961e-62629ca1c48f.png)
![image](https://user-images.githubusercontent.com/1942409/45928866-6eab3800-bf4a-11e8-83af-7228c0705404.png)

**Comment by Evolvee** [comment]
@Wolffenstein bump

**Comment by Navedonar** [comment]
Rev 2196 now works
![wowscrnshot_102318_164206](https://user-images.githubusercontent.com/1525533/47368944-e8b61480-d6e2-11e8-9460-4c72552ce437.jpg)

**Comment by Evolvee** [comment]
wtf

**Comment by narayagh** [comment]
Bravo! Server revision 2207:
![wow_2018-10-24_22-07-30](https://user-images.githubusercontent.com/13250690/47458268-707e4a80-d7d9-11e8-9bd6-8fb6806ef4fc.jpg)

**Comment by Evolvee** [comment]
is it srsly working fully? 100%? all visuals etc?

**Comment by Evolvee** [comment]
closing then :/ weird
