### ISSUE TITLE
[mob] Defias Rummager not dropping any currency. 

### ISSUE THREAD

**Issue by Dosdaltherir** [Atlantiss/NetherwingBugtracker#1720]
**Description**: 
The mob in Dustwallow marsh named "Defias Rummager" is not dropping any currency, and will only rarely drop some cloth. 
**Current behaviour**:
The mob "Defias Rummager" is not dropping any currency.
**Expected behaviour**: 
The mob "Defias Rummager" should be dropping currency according to wowhead and common sense. https://www.wowhead.com/npc=23589/defias-rummager#comments
**Mob ID**:
Entry: 23589, Id: 4, GUIDlow: 153496
**Server Revision**: 
Rev: 2186.

**Comment by Dosdaltherir** [comment]
Same story with the NPC "Defias Diver"
NPC ID: Entry: 23591, Id: 11, GUIDLow: 28512

**Comment by Shanghi** [comment]
This should be fixed in revision 2221.
