### ISSUE TITLE
[NPC] Gorishi Stinger

### ISSUE THREAD

**Issue by Mewmewww** [Atlantiss/NetherwingBugtracker#1721]
[//]: # (Enclose links to things related to the bug using http://wowhead.com or any other TBC database.)
[//]: # (You can use screenshot ingame to visual the issue.)
[//]: # (Write your tickets according to the format:)
[//]: # ([Quest][Azuremyst Isle] Red Snapper - Very Tasty!)
[//]: # ([NPC] Magistrix Erona)
[//]: # ([Spell][Mage] Fireball)
[//]: # ([Npc][Drop] Ghostclaw Lynx)
[//]: # ([Web] Armory doesnt work)

**Description**: 
Stuck in place, autoattacks doesn't work, but I can deal dmg with range or spells
https://imgur.com/a/WImmwot
**Current behaviour**:
Stuck in place, autoattacks doesn't work, but I can deal dmg with range or spells
**Expected behaviour**: 
Shouldnt be stuck in place
**Server Revision**: 
2186

**Comment by Evolvee** [comment]
probably mmap hole in that place

**Comment by Mewmewww** [comment]
> probably mmap hole in that place

I wanted to say that when I used intercept on him, I was under the map and could fall down to hell if I nudged a tiny bit.

**Comment by aresbrutus** [comment]
Fixed after rev `2196`
