### ISSUE TITLE
[NPC][Linking]Flamekin Spitter/Sprite/Torcher/Rager#9776/9777/9778/9779 Burning Steppes

### ISSUE THREAD

**Issue by Tenoutoften** [Atlantiss/NetherwingBugtracker#1723]
**Description**: 
There are 8 groups of 5 [imps](https://db.excalibur.ws/?search=flamekin) in Burning Steppes, when one is pulled the whole group should link according to [wowhead comment](https://www.wowhead.com/npc=9777/flamekin-sprite#comments):
![3c585f531da9730e1d4fe89b3daf681d](https://user-images.githubusercontent.com/34839199/47226589-4257cf80-d3c1-11e8-8d05-2a1b052aacd0.png)
The imps reward full experience, but are very weak on their own, dealing very low damage compared to regular mobs - which is why it makes sense they should link.

------

Three groups of these imps:
* [[NPC]Flamekin Spitter#9776](https://www.wowhead.com/npc=9776/flamekin-spitter)
* [[NPC]Flamekin Sprite#9777](https://www.wowhead.com/npc=9777/flamekin-sprite)

**Group 1:**
![8dd87140f00ae71b3202680a723f63c6](https://user-images.githubusercontent.com/34839199/47227643-a7acc000-d3c3-11e8-880a-3f307ef062eb.png)
![b5c968c88e53ee7a2d3de6c334e7e801](https://user-images.githubusercontent.com/34839199/47227644-a7acc000-d3c3-11e8-97ca-84489f56971f.png)

**Group 2:**
![bbc84a0ad3901ee0c1d083aa2736f263](https://user-images.githubusercontent.com/34839199/47227673-b5624580-d3c3-11e8-8f4a-b9e9f3150f96.png)
![dd1b11cdbce237b91e7f26b7db9f70f8](https://user-images.githubusercontent.com/34839199/47227674-b5fadc00-d3c3-11e8-975b-554a04111d64.png)

**Group 3:**
![ef23047549ee831c026d3d4f8c831d1b](https://user-images.githubusercontent.com/34839199/47227687-bd21ea00-d3c3-11e8-9fd6-2010ed91b399.png)
![6c7aa31c16a57a9a5444d5a293b06787](https://user-images.githubusercontent.com/34839199/47227686-bd21ea00-d3c3-11e8-88c2-e90f3c8d6bc5.png)

------
Five groups of these imps:
* [[NPC]Flamekin Torcher#9778](https://www.wowhead.com/npc=9778/flamekin-torcher)
* [[NPC]Flamekin Rager#9779](https://www.wowhead.com/npc=9779/flamekin-rager)

**Group 1:**
![9b892fd8283c84e6ab4a5749e45e95b5](https://user-images.githubusercontent.com/34839199/47227845-1722af80-d3c4-11e8-9548-b1d166070403.png)
![b5e8b960db39fe2540d4274619fa1d62](https://user-images.githubusercontent.com/34839199/47227846-1722af80-d3c4-11e8-9b3d-0c8f40687f32.png)

**Group 2:**
![c07b9069839374511dca98a0fb3ed226](https://user-images.githubusercontent.com/34839199/47227853-1be76380-d3c4-11e8-8642-f71f83fbb5e9.png)
![9c1a3303226dd032d2c5426415724f8d](https://user-images.githubusercontent.com/34839199/47227852-1be76380-d3c4-11e8-93e7-31db29d2b206.png)

**Group 3:**
![472494e3afc1769f1f8afeaf5042f692](https://user-images.githubusercontent.com/34839199/47227871-24d83500-d3c4-11e8-81fa-c5e3ca2a883e.png)
![336c472de226a12d9f2c43d24f272a00](https://user-images.githubusercontent.com/34839199/47227870-24d83500-d3c4-11e8-82f9-1f9fe0701e6a.png)

**Group 4:**
![38c8a196f2dd674953ff059674141d16](https://user-images.githubusercontent.com/34839199/47227880-29045280-d3c4-11e8-83b1-23f1451cf269.png)
![00d7b237ba69e16639ac25ade8c920c7](https://user-images.githubusercontent.com/34839199/47227879-29045280-d3c4-11e8-843a-24d9d6e354e1.png)

**Group 5:**
![a680025eefa823a3bce13e70f52be6b0](https://user-images.githubusercontent.com/34839199/47227881-2c97d980-d3c4-11e8-9b57-9976eeb16998.png)
![e83941fa0af5588665839274d161ee39](https://user-images.githubusercontent.com/34839199/47227882-2c97d980-d3c4-11e8-9b8d-1a918f7b2fc9.png)

---------

**Current behaviour**:
Doesn't link.

**Expected behaviour**: 
Link.

**Server Revision**: 
2186

**Comment by Evolvee** [comment]
rev Block
