### ISSUE TITLE
[Quest]Argent Dawn Commission#5503 should reward xp

### ISSUE THREAD

**Issue by Tenoutoften** [Atlantiss/NetherwingBugtracker#1725]
**Description**: 
Rewards 650xp when Joana turns in [here](https://youtu.be/jKPDoC8EraY?t=41)

Rather minor...It looks like this [[Quest]Argent Dawn Comission#5503](https://www.wowhead.com/quest=5503/argent-dawn-commission) was moved from [[NPC]Argent officer Garush#10839](https://db.excalibur.ws/?npc=10839) to [[NPC]Argent Quartermaster Hasana#10856](https://db.excalibur.ws/?npc=10856) during early TBC patches.
![9aeb0f5eff46f0df9c5a765015bb9c69](https://user-images.githubusercontent.com/34839199/47233970-94562080-d3d4-11e8-9dba-3976a825b1ec.png)
![b597a22671e395446c21c4dc60ef027b](https://user-images.githubusercontent.com/34839199/47233971-94562080-d3d4-11e8-8877-8f03a7a247a0.png)
![f2e4b64a7046ec7322d460f39eff73d0](https://user-images.githubusercontent.com/34839199/47233972-94562080-d3d4-11e8-9262-d6ccb6a252ba.png)

**Current behaviour**:
0 xp

**Expected behaviour**: 
At least 650xp, maybe increased in 2.3 or scrapped with update? A very small window of patches to remove xp.

**Server Revision**: 
2186

**Comment by wtRCH** [comment]
- Move quest from Argent Officer Garush `10839` to Argent Quartermaster Hasa `10856`
- Correct QID: `5405`

- Change Argent Officer Purehearth `10840` quest to correct QID
- Correct QID: `5401`

- Upon completing `5405` you shouldn't be able to complete `5401` and vice versa.

- Make quest `5405` and `5401` reward player with 650XP.

@pelekon

**Comment by The14me** [comment]
rev.3451. still an active.

**Comment by Zarant** [comment]
This is not a bug, during patch 2.1 the xp from repeatable turn ins was removed from the game and with that, this quest stopped giving XP.

https://web.archive.org/web/20080209223438/http://thottbot.com/q5503
