### ISSUE TITLE
[[NPC]Scarlet Hound#10979 should grant experience

### ISSUE THREAD

**Issue by Tenoutoften** [Atlantiss/NetherwingBugtracker#1727]
**Description**: 
[[NPC]Scarlet Hound#10979](https://db.excalibur.ws/?npc=10979) should grant experience equal to a normal mob. This NPC is the pet of [[NPC]Scarlet Hunter#1831](https://db.excalibur.ws/?npc=1831) summoned by [[Spell]Summon Scarlet Hound#17164](https://db.excalibur.ws/?spell=17164)
https://youtu.be/jKPDoC8EraY?t=753

**Current behaviour**:
0xp

**Expected behaviour**: 
Xp equivalent of a normal mob

**Server Revision**: 
2186

**Comment by Evolvee** [comment]
https://github.com/Atlantiss/NetherwingBugtracker/issues/1945
