### ISSUE TITLE
Hearthstone Warlock pet dessapear

### ISSUE THREAD

**Issue by Evgenyx123** [Atlantiss/NetherwingBugtracker#1728]
![pet offline](https://user-images.githubusercontent.com/44301820/47235764-4d6b2980-d3da-11e8-8da4-1c5557a832a6.jpg)

Class: Warlock
Issue: Pet dessapearing after using Hearthstone
Details: Any active pet will dessapear after using hearthstone
PS: Screenshot provided

**Comment by Wolffenstein** [comment]
Fixed in rev 2194.
