### ISSUE TITLE
Casting spells range

### ISSUE THREAD

**Issue by Evgenyx123** [Atlantiss/NetherwingBugtracker#1729]
![spells range](https://user-images.githubusercontent.com/44301820/47236206-ae473180-d3db-11e8-9456-cc163234ed72.jpg)

Class: Warlock
Issue: If your target is moving away from you any spells you cast will be interrupted because of range.
There should be a 5 yard tolerance if you already started to cast a spell.

**Comment by Easyfraggy** [comment]
https://github.com/Atlantiss/NetherwingBugtracker/issues/121
