### ISSUE TITLE
[NPC][Undercity]Caged Sheep

### ISSUE THREAD

**Issue by DeltaLoads** [Atlantiss/NetherwingBugtracker#1730]
[//]: # (Enclose links to things related to the bug using http://wowhead.com or any other TBC database.)
[//]: # (You can use screenshot ingame to visual the issue.)
[//]: # (Write your tickets according to the format:)
[//]: # ([Quest][Azuremyst Isle] Red Snapper - Very Tasty!)
[//]: # ([NPC] Magistrix Erona)
[//]: # ([Spell][Mage] Fireball)
[//]: # ([Npc][Drop] Ghostclaw Lynx)
[//]: # ([Web] Armory doesnt work)

**Description**: 
Every time Aphothecary Keever exploads Caged Sheep, instead of despawning one and respawning another, just another one spawns, which starts to cause some serious problems when in that part of Undercity (massive fps drops and lags), could potentionally even cause crash
https://streamable.com/wdxlw
**Current behaviour**:
Caged Sheep keep on spawning without despawning previous one
**Expected behaviour**: 
Caged Sheep should respawn instead of spawning another
**Server Revision**: 
2186

**Comment by DeltaLoads** [comment]
it is definitely causing DCs when you are in that room every few min

**Comment by Evolvee** [comment]
rev yummx
