### ISSUE TITLE
Mudrock Spikeshell doing dmg above level

### ISSUE THREAD

**Issue by craigsurbrook** [Atlantiss/NetherwingBugtracker#1735]
[//]: # (Enclose links to things related to the bug using http://wowhead.com or any other TBC database.)
[//]: # (You can use screenshot ingame to visual the issue.)
[//]: # (Write your tickets according to the format:)
[//]: # ([Quest][Azuremyst Isle] Red Snapper - Very Tasty!)
[//]: # ([NPC] Magistrix Erona)
[//]: # ([Spell][Mage] Fireball)
[//]: # ([Npc][Drop] Ghostclaw Lynx)
[//]: # ([Web] Armory doesnt work)

**Description**: 
As a level 39 rogue against these 35-36 mobs, even if I give myself most advantageous dmg upon attack by stunning with cheap shot, they take down my health to about 20% before they die. Any other mobs in the zone in Dustwallow will take my health down "by" 20% (to 80%), not down "to" 20%.

Note: I could be wrong, and it's "intended" that these mobs hit much harder than all the other mobs.

**Current behaviour**:
They seem to be hitting my toon with dmg from a level 40 mob, not a  level 35-36 mob.

**Expected behaviour**: 
That the dmg of Mudrock Spikeshell should be in line with other mobs of the level of the zone.

**Server Revision**:

**Comment by Easyfraggy** [comment]
![image](https://user-images.githubusercontent.com/36134067/47242182-4a7a3400-d3ee-11e8-8bd4-fafbf3691d2a.png)

**Comment by Evolvee** [comment]
rev Block
