### ISSUE TITLE
[NPC][Azshara]Young Wavetrasher

### ISSUE THREAD

**Issue by DeltaLoads** [Atlantiss/NetherwingBugtracker#1736]
[//]: # (Enclose links to things related to the bug using http://wowhead.com or any other TBC database.)
[//]: # (You can use screenshot ingame to visual the issue.)
[//]: # (Write your tickets according to the format:)
[//]: # ([Quest][Azuremyst Isle] Red Snapper - Very Tasty!)
[//]: # ([NPC] Magistrix Erona)
[//]: # ([Spell][Mage] Fireball)
[//]: # ([Npc][Drop] Ghostclaw Lynx)
[//]: # ([Web] Armory doesnt work)

**Description**: 
Few Young Wavetrashers (one in video Entry:6347 id:1 GUIDLow:24379) have some pathfinding problems 
https://streamable.com/q1oye
**Current behaviour**:
NPC is spazzing out
**Expected behaviour**: 
NPC should have normal movement
**Server Revision**: 
2186

**Comment by Tenoutoften** [comment]
Seems similar to https://github.com/Atlantiss/NetherwingBugtracker/issues/1716
https://github.com/Atlantiss/NetherwingBugtracker/issues/1623
https://github.com/Atlantiss/NetherwingBugtracker/issues/1555
https://github.com/Atlantiss/NetherwingBugtracker/issues/1721

**Comment by Tenoutoften** [comment]
![eb4488838631ddef5ec7d61c6a281ba8](https://user-images.githubusercontent.com/34839199/47270752-78878180-d570-11e8-95cd-44bf0d3890df.png)
same thing with this one

**Comment by aresbrutus** [comment]
Fixed after rev `2196`
