### ISSUE TITLE
[Pathfinding][Razorfen Downs]Mordresh Fire Eye

### ISSUE THREAD

**Issue by DeltaLoads** [Atlantiss/NetherwingBugtracker#1737]
[//]: # (Enclose links to things related to the bug using http://wowhead.com or any other TBC database.)
[//]: # (You can use screenshot ingame to visual the issue.)
[//]: # (Write your tickets according to the format:)
[//]: # ([Quest][Azuremyst Isle] Red Snapper - Very Tasty!)
[//]: # ([NPC] Magistrix Erona)
[//]: # ([Spell][Mage] Fireball)
[//]: # ([Npc][Drop] Ghostclaw Lynx)
[//]: # ([Web] Armory doesnt work)

**Description**: 
Pathfinding problems for pets attacking Mordresh on his pile of bones
https://streamable.com/geq1r
**Current behaviour**:
Pets get stuck underneath pile of bones
**Expected behaviour**: 
Pets should get on top of the pile
**Server Revision**: 
2186

**Comment by Easyfraggy** [comment]
Problem with maps around the bonepile

**Comment by Wolffenstein** [comment]
Fixed in rev 3399.
