### ISSUE TITLE
[NPC][Razorfen Downs]Belnistrasz

### ISSUE THREAD

**Issue by DeltaLoads** [Atlantiss/NetherwingBugtracker#1738]
[//]: # (Enclose links to things related to the bug using http://wowhead.com or any other TBC database.)
[//]: # (You can use screenshot ingame to visual the issue.)
[//]: # (Write your tickets according to the format:)
[//]: # ([Quest][Azuremyst Isle] Red Snapper - Very Tasty!)
[//]: # ([NPC] Magistrix Erona)
[//]: # ([Spell][Mage] Fireball)
[//]: # ([Npc][Drop] Ghostclaw Lynx)
[//]: # ([Web] Armory doesnt work)

**Description**: 
While escorting Belnistrasz for Extinguishing the Idol, if player gets in combat before npc does, he just says his line and stands around
https://streamable.com/gzydq
**Current behaviour**:
Belnistrasz just stands without attacking
**Expected behaviour**: 
Belnistrasz should attack nearest target
**Server Revision**: 
2186

**Comment by Easyfraggy** [comment]
Duplicate https://github.com/Atlantiss/NetherwingBugtracker/issues/1373
