### ISSUE TITLE
[NPC] Mob movement speed too slow

### ISSUE THREAD

**Issue by Gniddikon** [Atlantiss/NetherwingBugtracker#174]
**Description**: The mobs in Sunstrider Isle and Eversong Woods seem to have a movement speed thats too slow. I am able to kite them without any kind of speed increase/buff as a hunter. I don't have any source/proof for this atm but it should be double checked/looked into.

**Comment by Evolvee** [comment]
starter leveling areas have slower mobs

please include mob ID in your report and some proof

**Comment by Easyfraggy** [comment]
To show mob id type .npc info ingame while targetting the mob.

**Comment by Evolvee** [comment]
when you get more info, reopen this please
