### ISSUE TITLE
[NPC]Temporal Parasite#10717 should grant experience

### ISSUE THREAD

**Issue by Tenoutoften** [Atlantiss/NetherwingBugtracker#1740]
**Description**: 
[[NPC]Temporal Parasite#10717](https://db.excalibur.ws/?npc=10717) should grant experience, seen here:
https://youtu.be/fEPo050WscM?t=8169

**Current behaviour**:
No experience granted, [NW video here](https://www.youtube.com/watch?v=5mzP_qpAnRs&feature=youtu.be)

**Expected behaviour**: 
Grant experience.

**Server Revision**: 
2186

**Comment by ircfelix** [comment]
Please also check if they are skinable. On Felmyst they were, even though they are not supposed to be skinable.

**Comment by Tenoutoften** [comment]
They aren't you can see that in the video, not that it is a huge deal anyway...

**Comment by Evolvee** [comment]
https://github.com/Atlantiss/NetherwingBugtracker/issues/1945#issuecomment-433757668
