### ISSUE TITLE
Small typo: Uther the Lightbringer

### ISSUE THREAD

**Issue by Azalen** [Atlantiss/NetherwingBugtracker#1743]
**Description**: 
http://classicdb.ch/?object=2082

**Current behaviour**:
![wowscrnshot_102018_130549](https://user-images.githubusercontent.com/20336567/47254934-e5175900-d468-11e8-80c9-627d1f809cac.jpg)

**Expected behaviour**: 
Question mark at the end of the text should be a "-".

**Server Revision**: 
[2177]

**Comment by Evolvee** [comment]
https://vignette.wikia.nocookie.net/wowwiki/images/6/61/Uther_burial_message.jpg
its blizzlike btw

**Comment by Evolvee** [comment]
rev Block
