### ISSUE TITLE
[NPC] Gordunni Ogres in Feralas wielding wrong weapons

### ISSUE THREAD

**Issue by netherwingbta** [Atlantiss/NetherwingBugtracker#1744]
[//]: # (Enclose links to things related to the bug using http://wowhead.com or any other TBC database.)
[//]: # (You can use screenshot ingame to visual the issue.)
[//]: # (Write your tickets according to the format:)
[//]: # ([Quest][Azuremyst Isle] Red Snapper - Very Tasty!)
[//]: # ([NPC] Magistrix Erona)
[//]: # ([Spell][Mage] Fireball)
[//]: # ([Npc][Drop] Ghostclaw Lynx)
[//]: # ([Web] Armory doesnt work)

**Description**: 
Gordunni Ogres in Feralas are wielding weapons from cata patch.

**Current behaviour**:

> Patch 4.0.3a (2010-11-23): Level reduced from 44 - 45. New weapon.

[Gordunni Mauler](https://www.wowhead.com/npc=5234/gordunni-mauler#screenshots) is wielding wolverine claws instead of hammer and mace.
[Gordunni Shaman](https://www.wowhead.com/npc=5236/gordunni-shaman#screenshots) is dual wielding cata weapon instead of using a staff. Even in the cata screenshot he only has 1 weapon, not two. 
[Gordunni Warlock](https://www.wowhead.com/npc=5240/gordunni-warlock#screenshots) is using the wrong staff.
[Gordunni Mage-Lord](https://www.wowhead.com/npc=5239/gordunni-mage-lord#screenshots) is wielding a 1h and an off-hand instead of a staff.
**Expected behaviour**: 
Listed mobs should use weapons they had in vanilla,tbc and wotlk. 
**Server Revision**: 
2186

**Comment by Evolvee** [comment]
rev Block
