### ISSUE TITLE
[Core][Shaman] Totem aura duration

### ISSUE THREAD

**Issue by Galawer** [Atlantiss/NetherwingBugtracker#1745]
**Current behaviour**:
Sometimes the aura from a totem will show a random duration, I think of some previously gained aura:
![image](https://user-images.githubusercontent.com/1574432/47256211-53194b80-d47c-11e8-9a51-1863c11c27ce.png)
![image](https://user-images.githubusercontent.com/1574432/47256219-73e1a100-d47c-11e8-8e5a-2f478f878fe2.png)
![image](https://user-images.githubusercontent.com/1574432/47256223-822fbd00-d47c-11e8-83a1-fdf77b6e5549.png)
It's only a visual bug, the aura doesn't actually fade when the timer expires, it just stays flashing at "0 s".

**Expected behaviour**: 
Auras from totems should not display any duration.

**Server Revision**: 
2186

**Comment by Daggotur** [comment]
Confirm this as well
![wowscrnshot_111218_112516](https://user-images.githubusercontent.com/44930160/48364907-42b95280-e66f-11e8-920b-758a7dd0984f.jpg)

**Comment by Tereneckla** [comment]
fixed
