### ISSUE TITLE
[NPC]Succubus minion#10928 should grant experience when killed

### ISSUE THREAD

**Issue by Tenoutoften** [Atlantiss/NetherwingBugtracker#1747]
**Description**: 
[[NPC]Succubus minion#10928](https://db.excalibur.ws/?npc=10928) summoned by [[Spell]Summon Succubus#8722](https://db.excalibur.ws/?spell=8722) should grant experience when killed, seen here:
https://youtu.be/gusbV3RtP44?t=43 and here: https://youtu.be/26kkq0F6n7o?t=325

Also see https://github.com/Atlantiss/NetherwingBugtracker/issues/1512

**Current behaviour**:
When I was there it didn't give xp, but I didn't have any evidence so I didn't report it, though Ill report a few now without some evidence because it seems rather obvious "normal pets" of regular mobs should grant xp.

**Expected behaviour**: 
To give xp

**Server Revision**: 
2186

**Comment by Evolvee** [comment]
https://github.com/Atlantiss/NetherwingBugtracker/issues/1945
