### ISSUE TITLE
[NPC]Bloodshot#11614 pet of [NPC]Huntsman Radley#11613 should grant xp

### ISSUE THREAD

**Issue by Tenoutoften** [Atlantiss/NetherwingBugtracker#1749]
**Description**: 
Considering https://github.com/Atlantiss/NetherwingBugtracker/issues/1727 I think it is safe to say that 
[[NPC]Huntsman Radley#11613](https://www.wowhead.com/npc=11613/huntsman-radley#comments)'s pet [[NPC]Bloodshot#11614](https://www.wowhead.com/npc=11614/bloodshot#comments) summoned by [[Spell]Call Bloodshot#18262](https://db.excalibur.ws/?spell=18262) should grant experience/xp since it is a regularly challenging pet.

**Current behaviour**:
Doesn't give xp.

**Expected behaviour**: 
Should give xp.

**Server Revision**: 
2186

**Comment by Evolvee** [comment]
https://github.com/Atlantiss/NetherwingBugtracker/issues/1945
