### ISSUE TITLE
[Core] Party HP visual bug

### ISSUE THREAD

**Issue by Sinyr** [Atlantiss/NetherwingBugtracker#175]
[//]: # (Enclose links to things related to the bug using http://wowhead.com or any other TBC database.)
[//]: # (You can use screenshot ingame to visual the issue.)
[//]: # (Write your tickets according to the format:)
[//]: # ([Quest][Azuremyst Isle] Red Snapper - Very Tasty!)
[//]: # ([NPC] Magistrix Erona)
[//]: # ([Spell][Mage] Fireball)
[//]: # ([Npc][Drop] Ghostclaw Lynx)
[//]: # ([Web] Armory doesnt work)
**Current behaviour**:
Out of party, a friendly level 1 draenei mage's HP shows as 100%. His actual HP is 51, and this is all good. But when you join the party his HP shows as 51% when he's at max HP, instead of 51/51. Presumably this happens when you group up with anyone whose actual HP is under 100.

Also, when leaving a party with someone who has _more_ than 100 HP and then targeting him, his HP is shown as 100/271 when he's at max HP, instead of 100%.

![party health bug](https://user-images.githubusercontent.com/9539181/45928328-0c4e3980-bf42-11e8-84c8-e37be3273a83.png)

Relogging does fix both of these issues.

**Expected behaviour**: 
Displayed HP should change between numeric values and percentages automatically when joining or leaving a party.

**Server Revision**: 
2028

**Comment by Easyfraggy** [comment]
Related? https://github.com/Atlantiss/NetherwingBugtracker/issues/1038

**Comment by Wolffenstein** [comment]
Fixed in rev 2211.
