### ISSUE TITLE
[NPC]Shadowpine Catlord#16345's pet [NPC]Ghostclaw Lynx#16348 should grant experience

### ISSUE THREAD

**Issue by Tenoutoften** [Atlantiss/NetherwingBugtracker#1750]
**Description**: 
[[NPC]Shadowpine Catlord#16345](https://db.excalibur.ws/?npc=16345#abilities)'s pet [[NPC]Ghostclaw Lynx#16348](https://db.excalibur.ws/?npc=16348) summoned by [[Spell]Summon Ghostclaw Lynx#28094](https://db.excalibur.ws/?spell=28904) should give experience based on this [video](https://youtu.be/Ryg1KLVOH9w?t=360) from later expansion, think it is from cataclysm. It looks like pets with a decent difficulty generally gives xp.

Also see, all pets that should without a doubt give xp:
https://github.com/Atlantiss/NetherwingBugtracker/issues/1512
https://github.com/Atlantiss/NetherwingBugtracker/issues/1747
https://github.com/Atlantiss/NetherwingBugtracker/issues/1727

I killed the  [[NPC]Ghostclaw Lynx#16348](https://db.excalibur.ws/?npc=16348)'s here but they don't show up since they didn't give any xp.
![9fdb54c8b3d74b8d614673310d05e5f3](https://user-images.githubusercontent.com/34839199/47256755-3897a000-d485-11e8-86e5-51e516e4d1f7.png)

**Current behaviour**:
0 xp

**Expected behaviour**: 
Expected to grant xp based on video evidence from future patch & common sense.

**Server Revision**: 
2186

**Comment by Evolvee** [comment]
https://github.com/Atlantiss/NetherwingBugtracker/issues/1945
