### ISSUE TITLE
[NPC][Felwood]Vartrus the Ancient

### ISSUE THREAD

**Issue by DeltaLoads** [Atlantiss/NetherwingBugtracker#1751]
[//]: # (Enclose links to things related to the bug using http://wowhead.com or any other TBC database.)
[//]: # (You can use screenshot ingame to visual the issue.)
[//]: # (Write your tickets according to the format:)
[//]: # ([Quest][Azuremyst Isle] Red Snapper - Very Tasty!)
[//]: # ([NPC] Magistrix Erona)
[//]: # ([Spell][Mage] Fireball)
[//]: # ([Npc][Drop] Ghostclaw Lynx)
[//]: # ([Web] Armory doesnt work)

**Description**: 
Vartrus the Ancient is hostile, he should be friendly and should only be visible if you have Ancient Petrified Leaf
https://www.wowhead.com/npc=14524/vartrus-the-ancient#comments
![wowscrnshot_102018_162645](https://user-images.githubusercontent.com/43690147/47256810-e7d47700-d485-11e8-8f3b-0e0ca4711ee3.jpg)

**Current behaviour**:
Vartrus the Ancient is hostile and visible
**Expected behaviour**: 
Vartrus the Ancient should be friendly and invisible unless you are on a quest
**Server Revision**: 
2186

**Comment by DeltaLoads** [comment]
and Hastat the Ancient aswell

**Comment by Evolvee** [comment]
factions changed in rev Block

TODO: invisibility

**Comment by Manaci** [comment]
Fixed
