### ISSUE TITLE
[Objects] Chests loot

### ISSUE THREAD

**Issue by Reykjavikshore** [Atlantiss/NetherwingBugtracker#1753]
**Description**: 
There is almost no diffrence beetween loot in boxes,chests and other containers for example
http://db.hellfire-tbc.com/?object=184793

**Current behaviour**: In containers, boxes and chests we should find a lot of different items. I found 6 chests and drops was always the same for example http://db.hellfire-tbc.com/?item=2962 drop 4 times.

**Expected behaviour**: We should find more different items in boxes and always same

**Server Revision**: 2186

**Comment by Easyfraggy** [comment]
Chest loot is being reworked https://github.com/Atlantiss/NetherwingBugtracker/issues/478
