### ISSUE TITLE
[Spell]Lordaeron's Blessing#30238 doesn't seem to provide the +5% health it should in specific zones

### ISSUE THREAD

**Issue by Tenoutoften** [Atlantiss/NetherwingBugtracker#1755]
**Description**: 

[[Spell]Lordaeron's Blessing#30238](https://db.excalibur.ws/?spell=30238) seems to have no effect. Should give +5% health while in Eastern Plaguelands, Stratholme and Scholomance.

Not sure what this one is, but that might be tied with it.
[[Spell]Lordaeron's Blessing Effect (DND)#31906](https://db.excalibur.ws/?spell=31906)

https://www.youtube.com/watch?v=jCzPt0bVNEw&feature=youtu.be

As you can see the object is also bugging out on occasion, not sure what causes this though
[[Object]Lordaeron Shrine#181955](https://db.excalibur.ws/?object=181955)
[[Object]Lordaeron Shrine#181682](https://db.excalibur.ws/?object=181682)

**Current behaviour**:
No effect

**Expected behaviour**: 
+5% health in stated zones.

**Server Revision**: 
2186

**Comment by Evolvee** [comment]
rev Block
