### ISSUE TITLE
[NPC][Felwood]Jaedenar Darkweaver

### ISSUE THREAD

**Issue by DeltaLoads** [Atlantiss/NetherwingBugtracker#1756]
[//]: # (Enclose links to things related to the bug using http://wowhead.com or any other TBC database.)
[//]: # (You can use screenshot ingame to visual the issue.)
[//]: # (Write your tickets according to the format:)
[//]: # ([Quest][Azuremyst Isle] Red Snapper - Very Tasty!)
[//]: # ([NPC] Magistrix Erona)
[//]: # ([Spell][Mage] Fireball)
[//]: # ([Npc][Drop] Ghostclaw Lynx)
[//]: # ([Web] Armory doesnt work)

**Description**: 
Pets cannot attack Jaedenar Darkweavers that are using casting  at Remains of Trey Lightforge
https://streamable.com/50aa3
**Current behaviour**:
Pets cant attack NPCs that are casting at altar
**Expected behaviour**: 
Pets should be able to attack NPCs
**Server Revision**: 
2186

**Comment by Tereneckla** [comment]
Fixed
