### ISSUE TITLE
[Core Mechanic][Spell][Paladin]Consecration doesn't agro mobs when it deals damage to them

### ISSUE THREAD

**Issue by Tenoutoften** [Atlantiss/NetherwingBugtracker#1757]
**Description**: 
Dealing damage with [[Spell]Consecration](https://db.excalibur.ws/?search=consecration#spells) wont aggro mobs onto you.
![](https://i.gyazo.com/c3b95809134b8dc03375f111507b2619.png)

* [Example video 1, neutral mob](https://youtu.be/ybM2LWiMM2w)
* [Example video 2, hostile mob](https://www.youtube.com/watch?v=_WvTwKzM4tY&feature=youtu.be)

If you are engaged in combat and damage another mob through [[Spell]Consecration](https://db.excalibur.ws/?search=consecration#spells) you will stuck in combat with that mob:
* [Example video 3](https://www.youtube.com/watch?v=HNOqjD56w28&feature=youtu.be)

---

Other issues tied to [[Spell]Consecration](https://db.excalibur.ws/?search=consecration#spells):
* https://github.com/Atlantiss/NetherwingBugtracker/issues/3402

**Expected behaviour**: 
Dealing damage to a mob with [[Spell]Consecration](https://db.excalibur.ws/?search=consecration#spells) should aggro it onto you.

**Server Revision**: 
2431

**Comment by Tenoutoften** [comment]
This issue is not resolved with rev 2366 with these changes
[Core/Paladin]:
- Initial application of Consecration will now properly remove stealth
- Initial application of Consecration will now properly proc certain spells and effects (e.g. Judgement of Wisdom)

**Comment by Easyfraggy** [comment]
Server is still on 2364 please retest in 2366.

**Comment by Arnamik12** [comment]
Still having this issue rev 2382. Also doesnt tag the mobs in BM from the portals either.

**Comment by RandomGuyFromDiscordServer** [comment]
Still having this issue on 2431

**Comment by towneh** [comment]
Saw this again as per my description in the above linked closed issue thread.

**Comment by hearthledger** [comment]
still bugged

**Comment by joceanlab** [comment]
Seems like unless the mob is already targeting someone aoe moves don't do any damage. 

The portal spawns in Black Morass go straight through consecrate every time unless someone directly attacks them first, and then they start taking the damage. Super annoying when tanking.

**Comment by Mormansk** [comment]
> Seems like unless the mob is already targeting someone aoe moves don't do any damage.
> 
> The portal spawns in Black Morass go straight through consecrate every time unless someone directly attacks them first, and then they start taking the damage. Super annoying when tanking.

For me they do take the damage from consecrate but keep on walking towards Medivh. As soon as someone hits them they seem to wake up and head towards me (as long as that hit didnt overaggro the threat made with consecrate).

**Comment by hearthledger** [comment]
made a video of the bug https://youtu.be/DnZIMdVbEPA
server revision 2825

**Comment by Wolffenstein** [comment]
Fixed in rev 2832.
