### ISSUE TITLE
[Dire Maul][The Maul] Event respawn time

### ISSUE THREAD

**Issue by Knoox** [Atlantiss/NetherwingBugtracker#1758]
**After slaying The Razza, Skarr the unbreakable spawned imediatly. The exact event spawn timers need research**: 

**Server Revision 2186**:

**Comment by aresbrutus** [comment]
Confirmed. Skarr respawned 30 seconds or so after the Razza was defeated. 

Also, these texts need some correction:

`The Razza just made more fertilizer for Mushgog!` This should be said by the goblin when The Razza kills someone, not when Razza dies.

`Down goes Frazier!  Down goes Frazier! Down goes...huh?  That wasn't Frazier?` This should be said by the goblin when Skarr kills someone, not when Skarr dies.

**Comment by Evolvee** [comment]
shit yea, i left the script in its testing state xd

rev Block
