### ISSUE TITLE
[Core][Class][Shaman] Totems

### ISSUE THREAD

**Issue by Knoox** [Atlantiss/NetherwingBugtracker#1759]
**Grounding totems Works 1/10th of the time, IE seemingly random**: 

**Server Revision 2186**:

**Comment by Knoox** [comment]
![wowscrnshot_102018_223706](https://user-images.githubusercontent.com/18479169/47260280-c3de5900-d4b8-11e8-8cd7-da477c00a6c9.jpg)

Grounding totem works for partymembers dueling

**Comment by Knoox** [comment]
![wowscrnshot_102018_223915](https://user-images.githubusercontent.com/18479169/47260289-0a33b800-d4b9-11e8-89fe-8c7ded5de45b.jpg)
Flametoung weapon totem buffs partymemeber dueling

**Comment by Knoox** [comment]
Allready reported but closed https://github.com/Atlantiss/NetherwingBugtracker/issues/1548

**Comment by Knoox** [comment]
![wowscrnshot_102018_224519](https://user-images.githubusercontent.com/18479169/47260332-e15ff280-d4b9-11e8-8f4f-834cb3db2368.jpg)

Mana tide bugged aswell

**Comment by Knoox** [comment]
![wowscrnshot_102018_225018](https://user-images.githubusercontent.com/18479169/47260379-ec675280-d4ba-11e8-9b87-e2fd54f29338.jpg)

Odd interaction, blizzlike? IE Grounding has higher prio than spell reflect

**Comment by Knoox** [comment]
![wowscrnshot_102018_230034](https://user-images.githubusercontent.com/18479169/47260447-fb9ad000-d4bb-11e8-9ba1-b405c2dc0051.jpg)
Tremor totem works aswell

**Comment by Knoox** [comment]
Winfury works aswell

**Comment by Easyfraggy** [comment]
Set it as Medium prio untill you are done gathering info on this - Will set high prio when you feel like you have enough totem data.

**Comment by Wolffenstein** [comment]
Fixed in rev 2212.
