### ISSUE TITLE
[Spell] Heroic Strike (ID e.g. 78) queue is not cancelled with Esc

### ISSUE THREAD

**Issue by Jacksn5** [Atlantiss/NetherwingBugtracker#176]
**Description**: 
When [Heroic Strike](https://db.excalibur.ws/?spell=78) is selected and queued for the next swing, pressing escape should cancel it, as indicated by the lit up border around the hotkey, but it isn't. The only way to cancel a Heroic Strike cast now is to stop autoattack (or deselect target, same thing).

**Server Revision**: 
[2028]

**Comment by Easyfraggy** [comment]
Gonna need some proof of this. Also current server rev is 2028 - type .server info ingame to get the correct revision number.

**Comment by totaemoeggerli** [comment]
Same for Druid Maul. Icon stops to lit up when you press Esc but it your next auto attack will still be Maul.
https://gfycat.com/RaggedBriefBedlingtonterrier

**Comment by lynxzor** [comment]
Some comments that may apply

https://www.mmo-champion.com/threads/685893-!-cast-Heroic-Strike:
![image](https://user-images.githubusercontent.com/795881/50052698-39b11a80-0120-11e9-8348-37068c6288c6.png)
https://www.wowhead.com/forums&topic=139048:
![image](https://user-images.githubusercontent.com/795881/50052754-d2e03100-0120-11e9-9645-7da000eeabf6.png)

**Comment by Tereneckla** [comment]
fixed
