### ISSUE TITLE
[Quest][Thousand Needles] Arikara

### ISSUE THREAD

**Issue by eryczek1615** [Atlantiss/NetherwingBugtracker#1760]
**Description**: 
https://github.com/Atlantiss/NetherwingBugtracker/issues/688 This is diffrent problem so I make a new issue 
We need to kill [Arikara](https://www.wowhead.com/npc=10882/deprecated-for-4-x-arikara) to complete[Quest](https://www.wowhead.com/quest=5088) 

**Current behaviour**:
When I light the fire Arikara doesn't appear.

**Expected behaviour**: 
Arikara should appear when we light the fire

**Server Revision**: 
2186

**Comment by Evolvee** [comment]
https://github.com/Atlantiss/NetherwingBugtracker/issues/1609#issuecomment-431606760
