### ISSUE TITLE
Return to Vahlarriel - Dalinda Malem waltzes out without being attacked.

### ISSUE THREAD

**Issue by craigsurbrook** [Atlantiss/NetherwingBugtracker#1761]
[//]: # (Enclose links to things related to the bug using http://wowhead.com or any other TBC database.)
[//]: # (You can use screenshot ingame to visual the issue.)
[//]: # (Write your tickets according to the format:)
[//]: # ([Quest][Azuremyst Isle] Red Snapper - Very Tasty!)
[//]: # ([NPC] Magistrix Erona)
[//]: # ([Spell][Mage] Fireball)
[//]: # ([Npc][Drop] Ghostclaw Lynx)
[//]: # ([Web] Armory doesnt work)

**Description**: 
Quest "Return to Vahlarriel" - you must escort Dalinda Malem out of Thunder-Axe Fortress. She starts walking out, but her name label stays "yellow" instead of turning "green" to match yours, and no one attacks her as she walks out.

**Current behaviour**:
Dalinda Malem isn't attacked while walking out of the fortress. As a rogue I could just stealth walk beside her and get past all the mobs.

**Expected behaviour**: 
Every orc mob that can should aggro to Dalinda Malem and you have to fight them off, it's an escort quest's main feature.

**Server Revision**: 
2186: patch 203

**Comment by Evolvee** [comment]
should be fine after rev Block

try again if u can
