### ISSUE TITLE
Quest: Bone Collector - rogue stealth should despawn the Kodo Apparition

### ISSUE THREAD

**Issue by craigsurbrook** [Atlantiss/NetherwingBugtracker#1762]
[//]: # (Enclose links to things related to the bug using http://wowhead.com or any other TBC database.)
[//]: # (You can use screenshot ingame to visual the issue.)
[//]: # (Write your tickets according to the format:)
[//]: # ([Quest][Azuremyst Isle] Red Snapper - Very Tasty!)
[//]: # ([NPC] Magistrix Erona)
[//]: # ([Spell][Mage] Fireball)
[//]: # ([Npc][Drop] Ghostclaw Lynx)
[//]: # ([Web] Armory doesnt work)

**Description**: 
When collecting the Kodo Bones a Kodo Apparition appears that you must kill.

**Current behaviour**:
The apparition appears and if a rogue uses "Vanish" to go stealth, seeing as the apparition no longer senses the rogue, should vanish. Instead, it stays, so that someone else would have to kill it to even get to the respawned bones where it is at.

**Expected behaviour**: 
The apparition disappears after dying, and also disappears after a rogue vanishes because it's aggro target for getting the bones is gone - making it so that others later don't have to defeat an apparition for no reason.

NOTE: Now, I could be wrong here, seeing as I waited a significant amount of time, and the apparition did finally disappear. Sorry if this is working as intended.

**Server Revision**: 
2186: patch 203

**Comment by Evolvee** [comment]
its intended unless u find other evidence
its handled by blizzards spell that has 300000ms duration 
![image](https://user-images.githubusercontent.com/1942409/47266076-c4670600-d531-11e8-8324-efd48d8ce3da.png) (5min)
