### ISSUE TITLE
Mobs evade in combat

### ISSUE THREAD

**Issue by Reykjavikshore** [Atlantiss/NetherwingBugtracker#1763]
**Description**: Mobs get out of combat in fight/evade when run away in fear at low hp

**Current behaviour**: Even when they had dots they evade when run away too far from their postition
https://www.wowhead.com/npc=16403/withered-grimscale
maybe the issue is the same for others mob in the world which run away from player at low hp

**Expected behaviour**:  They should be still in combat when had dots on them, i saw on film on ats yt channel that even after take dmg from consecration they can walk with character for very long distance

**Server Revision**: 2186

**Comment by Wolffenstein** [comment]
Dots are an exception and don't prolong the combat timer. Consecration is an Area of Effect spell that's not a dot. Evade in this scenario seems to be a correct behaviour.
