### ISSUE TITLE
[EPL] A Game of Towers: Northpass Tower

### ISSUE THREAD

**Issue by Azalen** [Atlantiss/NetherwingBugtracker#1765]
**Description**: 
http://wowwiki.wikia.com/wiki/A_Game_of_Towers

**Current behaviour**:
Gameobject spawns and rewards the buff but the spell itself is not working. My Hitpoints stayed the same.

Spell: Lordaeron's Blessing
https://classicdb.ch/?spell=31906
https://classicdb.ch/?spell=30238
Gameobject: Lordaeron Shrine
https://classicdb.ch/?object=181682

**Expected behaviour**: 
Should increase the hitpoints by 5% while being in EPL, Stratholme and Scholomance.

**Server Revision**: 
[2187]

**Comment by Evolvee** [comment]
it will be working after rev Block

**Comment by Evolvee** [comment]
https://github.com/Atlantiss/NetherwingBugtracker/issues/1755
