### ISSUE TITLE
[NPC] Salia - Shadow Hold

### ISSUE THREAD

**Issue by Mewmewww** [Atlantiss/NetherwingBugtracker#1766]
[//]: # (Enclose links to things related to the bug using http://wowhead.com or any other TBC database.)
[//]: # (You can use screenshot ingame to visual the issue.)
[//]: # (Write your tickets according to the format:)
[//]: # ([Quest][Azuremyst Isle] Red Snapper - Very Tasty!)
[//]: # ([NPC] Magistrix Erona)
[//]: # ([Spell][Mage] Fireball)
[//]: # ([Npc][Drop] Ghostclaw Lynx)
[//]: # ([Web] Armory doesnt work)

**Description**: 
Succubus Salia, her interaction with 2 party members with the use of mind control.
**Current behaviour**:
Uses mind control on 1 person as per usual, ended up resetting/evading afterwards. 
**Expected behaviour**: 
Should not evade by using mind control.
**Server Revision**: 
2186

**Comment by Wolffenstein** [comment]
Fixed.
