### ISSUE TITLE
[EPL] A Game of Towers: Plaguewood Tower

### ISSUE THREAD

**Issue by Azalen** [Atlantiss/NetherwingBugtracker#1767]
**Description**: 
http://wowwiki.wikia.com/wiki/A_Game_of_Towers
http://wowwiki.wikia.com/wiki/William_Kielar
http://wowwiki.wikia.com/wiki/Plaguewood_Tower

**Current behaviour**:
William Kielar (https://classicdb.ch/?npc=17209) spawns but it is not possible to interact with him.

**Expected behaviour**: 
He should act as a flightmaster with Spectral Gryphons (https://wow.gamepedia.com/Spectral_gryphon).
Proof: http://www.furlinedteacup.com/bibleofdreams/2008/10/spectral-grypho.html

**Server Revision**: 
[2187]

**Comment by Evolvee** [comment]
rev Block
