### ISSUE TITLE
[Quest][Silithus]Scrying Materials

### ISSUE THREAD

**Issue by DeltaLoads** [Atlantiss/NetherwingBugtracker#1769]
[//]: # (Enclose links to things related to the bug using http://wowhead.com or any other TBC database.)
[//]: # (You can use screenshot ingame to visual the issue.)
[//]: # (Write your tickets according to the format:)
[//]: # ([Quest][Azuremyst Isle] Red Snapper - Very Tasty!)
[//]: # ([NPC] Magistrix Erona)
[//]: # ([Spell][Mage] Fireball)
[//]: # ([Npc][Drop] Ghostclaw Lynx)
[//]: # ([Web] Armory doesnt work)

**Description**: 
Geologist Larksbane is missing golden "?" for completed quest and quest cannot be completed even if you have all the items required
https://streamable.com/3y18n
**Current behaviour**:
Missing finish quest indicator and unable to turn quest in once completed
**Expected behaviour**: 
Finished quest indicator on NPC and being able to turn quest in
**Server Revision**: 
2186

**Comment by DeltaLoads** [comment]
uploaded wrong video on original link - https://streamable.com/poiri

**Comment by DeltaLoads** [comment]
Ok my bad https://www.wowhead.com/item=21259/logistics-task-briefing-v was missing in my bag thats why i couldnt turn it in, however there is still missing finished quest mark and text when turning it in - "Why, yes... these will be of tremendous aid!  These materials are awfully hard to come by in the desert, <name>.  Thank you."

**Comment by Evolvee** [comment]
so what exactly is the problem in here?

**Comment by DeltaLoads** [comment]
missing golden "?" on top of npc and missng text when turning in quest
![questmissing](https://user-images.githubusercontent.com/43690147/47271058-c9997480-d574-11e8-9bd0-3c99b0a58f68.png)

**Comment by Evolvee** [comment]
![image](https://user-images.githubusercontent.com/1942409/47684228-6b067300-dbd2-11e8-9ff1-53e52cad8335.png)
 rev yummy
