### ISSUE TITLE
[NPC] Portal trainer

### ISSUE THREAD

**Issue by Dekirayne** [Atlantiss/NetherwingBugtracker#177]
[//]: # (Enclose links to things related to the bug using http://wowhead.com or any other TBC database.)
[//]: # (You can use screenshot ingame to visual the issue.)
[//]: # (Write your tickets according to the format:)
[//]: # ([Quest][Azuremyst Isle] Red Snapper - Very Tasty!)
[//]: # ([NPC] Magistrix Erona)
[//]: # ([Spell][Mage] Fireball)
[//]: # ([Npc][Drop] Ghostclaw Lynx)
[//]: # ([Web] Armory doesnt work)

**Description**: 
Portal trainer NPC in mage tower (Stormwind) is missing
**Current behaviour**:
Larimaine Purdue <Portal Trainer> isn't next to the portal where her usual place is

**Expected behaviour**: 
Larimaine Purdue <Portal Trainer> should be next to the portal 
https://vanilla-twinhead.twinstar.cz/?npc=2485#screenshots:id=7554
![image](https://user-images.githubusercontent.com/12075744/45928377-d067a400-bf42-11e8-9d12-c240b90ff796.png)

**Server Revision**:

**Comment by Evolvee** [comment]
fixed in next hotfix revision
