### ISSUE TITLE
[Blasted lands][NPC] Moonwalking in place

### ISSUE THREAD

**Issue by Knoox** [Atlantiss/NetherwingBugtracker#1770]
**Walking animation but is not moving**: 

**Server Revision 2186
![wowscrnshot_102118_171853](https://user-images.githubusercontent.com/18479169/47268798-9a273f80-d555-11e8-842a-eb69985bfacb.jpg)
**:

**Comment by DeltaLoads** [comment]
![wowscrnshot_102118_232809](https://user-images.githubusercontent.com/43690147/47272652-22730800-d589-11e8-8bf3-2375d20bec78.jpg)
also moonwalking and cannot be attacked

**Comment by aresbrutus** [comment]
Fixed after rev `2196`
