### ISSUE TITLE
[Spell][Priest] Mana Burn

### ISSUE THREAD

**Issue by Eidous** [Atlantiss/NetherwingBugtracker#1771]
[//]: # (Enclose links to things related to the bug using http://wowhead.com or any other TBC database.)
[//]: # (You can use screenshot ingame to visual the issue.)
[//]: # (Write your tickets according to the format:)
[//]: # ([Quest][Azuremyst Isle] Red Snapper - Very Tasty!)
[//]: # ([NPC] Magistrix Erona)
[//]: # ([Spell][Mage] Fireball)
[//]: # ([Npc][Drop] Ghostclaw Lynx)
[//]: # ([Web] Armory doesnt work)

**Description**: 
Mana burn only burns half of the mana that it should.

**Current behaviour**:
Mana burn burns the same amount of mana as the damage it deals

**Expected behaviour**: 
Mana burn should burn for twice the amount of mana for the damage it deals

**Server Revision**: 
2194

**Comment by Wolffenstein** [comment]
Fixed in rev 2399.
