### ISSUE TITLE
[Priest] Gift of the Naaru cancels Shadowform

### ISSUE THREAD

**Issue by manslaughter** [Atlantiss/NetherwingBugtracker#1772]
**Description**: Draenei racial ability.

**Current behaviour**: While in shadowform, if you cast it, shadowform is cancelled.

**Expected behaviour**: You should stay in shadowform.
https://wow.gamepedia.com/Gift_of_the_Naaru

**Server Revision**: 2194

**Comment by Eidous** [comment]
https://www.wowhead.com/spell=28880/gift-of-the-naaru#comments

first comment says you shouldnt be able to cast it

**Comment by manslaughter** [comment]
Im bad
