### ISSUE TITLE
[Zone] [BRD] wall clipping in Grim Guzzler

### ISSUE THREAD

**Issue by ScottieDOESknow** [Atlantiss/NetherwingBugtracker#1774]
**Description**:  Camera wall clipping with red background (lava?)

**Current behaviour**: At the southwest corner of Grim Guzzler, by the last empty table & chairs, player camera can clip through the wall even with minimal camera zoom (4-5 clicks)

IMAGE - https://gyazo.com/a89b4439f9ca42ba53f612920eee6782

VIDEO - https://gyazo.com/730cb9640bd197c35f71f4ac3c21449b

**Expected behaviour**: Should not be able to see through the wall.

**Server Revision**: 2193

**Comment by Evolvee** [comment]
client side
