### ISSUE TITLE
[Spell][Hunter] Freezing trap model is too small

### ISSUE THREAD

**Issue by ayrb13** [Atlantiss/NetherwingBugtracker#1775]
**Description**: 
Model is too small
![wowscrnshot_102218_003928](https://user-images.githubusercontent.com/3375743/47269619-23a93280-d593-11e8-8bf2-a1db4ea5fba0.jpg)

**Current behaviour**:
Model is too small
**Expected behaviour**: 
Model should be larger
![default](https://user-images.githubusercontent.com/3375743/47269634-4cc9c300-d593-11e8-8891-805db10c52b1.jpg)

**Server Revision**:

**Comment by The14me** [comment]
Think it scale with the model.

**Comment by Wolffenstein** [comment]
It depends on the creature's model. Not a bug.
