### ISSUE TITLE
[NPC][Dustwallow Marsh] Specific Spikeshell is cucked

### ISSUE THREAD

**Issue by Peglaa** [Atlantiss/NetherwingBugtracker#1776]
[//]: # (Enclose links to things related to the bug using http://wowhead.com or any other TBC database.)
[//]: # (You can use screenshot ingame to visual the issue.)
[//]: # (Write your tickets according to the format:)
[//]: # ([Quest][Azuremyst Isle] Red Snapper - Very Tasty!)
[//]: # ([NPC] Magistrix Erona)
[//]: # ([Spell][Mage] Fireball)
[//]: # ([Npc][Drop] Ghostclaw Lynx)
[//]: # ([Web] Armory doesnt work)

**Description**: 
This dude is running in place and I can't attack him or anything.
![wowscrnshot_102118_184242](https://user-images.githubusercontent.com/15163719/47269689-cc3e9e80-d561-11e8-8b3e-f941a84c02a9.jpg)

**Current behaviour**:

**Expected behaviour**: 

**Server Revision**: 2194

**Comment by Evolvee** [comment]
its all core issue

**Comment by aresbrutus** [comment]
Fixed after rev `2196`
