### ISSUE TITLE
[NPC][Tanaris]Trenton Lighthammer

### ISSUE THREAD

**Issue by DeltaLoads** [Atlantiss/NetherwingBugtracker#1777]
[//]: # (Enclose links to things related to the bug using http://wowhead.com or any other TBC database.)
[//]: # (You can use screenshot ingame to visual the issue.)
[//]: # (Write your tickets according to the format:)
[//]: # ([Quest][Azuremyst Isle] Red Snapper - Very Tasty!)
[//]: # ([NPC] Magistrix Erona)
[//]: # ([Spell][Mage] Fireball)
[//]: # ([Npc][Drop] Ghostclaw Lynx)
[//]: # ([Web] Armory doesnt work)

**Description**: 
Moonwalking on spot
![wowscrnshot_102118_192120](https://user-images.githubusercontent.com/43690147/47270067-a10a7e00-d566-11e8-92b2-c2a8c31b1244.jpg)

**Current behaviour**:
Moonwalking on spot
**Expected behaviour**: 
Standing still and turning to player when talked to
**Server Revision**: 
2194

**Comment by Evolvee** [comment]
![image](https://user-images.githubusercontent.com/1942409/47270834-c9e44080-d571-11e8-86b1-bcdfb2daff3e.png)

hes fine for me, someone probably MCed him and he spazzed out, judging by the bones nearby... its a MC issue not issue of this NPC so closing this report
