### ISSUE TITLE
[Spell][Priest] Spirit of Redemption

### ISSUE THREAD

**Issue by Drayo** [Atlantiss/NetherwingBugtracker#1778]
**Description**: 
The Talent and thus the Spell "Spirit of Redemption" is missing all of it's animations.

**Current behaviour**:
If you die you instantly become a full sized Spirit.

https://www.wowhead.com/spell=20711/spirit-of-redemption

**Expected behaviour**: 
The Spirit should start small and grow large really quickly, a resurrection animation should play while that is happening. 
When the buff runs out, the player should have an increased model size and a red color, he should grow smaller quickly and have a blood effect playing.

All of that can be seen in this video: https://www.youtube.com/watch?v=oyfI4sf6ADg

**Server Revision**:  
2194

**Comment by Wolffenstein** [comment]
The animation was changed in one of the later patches. The Spirit model is now bigger by default, which means there is no growth anymore - you can see it on this video (https://youtu.be/tFDlgauRGk4?t=9s) from SWP (so 2.4+ patch). The red color was also removed. What's missing on Netherwing is the cast animation and blood effect.

**Comment by Drayo** [comment]
Ah, my video must be from the Wrath Pre-Patch then.

Yeah, the "resurrection" visual is missing from pretty much every Private Server, even WotLK ones. It's the one thing that really makes it look proper because it masks the sudden apperance of the Spirit a bit.

I doubt anyone really knows about the blood effect or even notices it so it might be wasted effort if it's annoying to implement it.

**Comment by Wolffenstein** [comment]
Fixed in rev 2399.
