### ISSUE TITLE
[Spell][Mage] Ice blocks makes you immune to friendly buffs

### ISSUE THREAD

**Issue by Brasso** [Atlantiss/NetherwingBugtracker#1779]
[//]: # (Enclose links to things related to the bug using http://wowhead.com or any other TBC database.)
[//]: # (You can use screenshot ingame to visual the issue.)
[//]: # (Write your tickets according to the format:)
[//]: # ([Quest][Azuremyst Isle] Red Snapper - Very Tasty!)
[//]: # ([NPC] Magistrix Erona)
[//]: # ([Spell][Mage] Fireball)
[//]: # ([Npc][Drop] Ghostclaw Lynx)
[//]: # ([Web] Armory doesnt work)

**Description**: 
Ice blocks makes the player immune to buffs during its duration. Tested spells Blessing of Freedom and Blessing of Protection. Healing the player also says immune but the healing goes through anyway.

**Current behaviour**:
![wowscrnshot_102118_195452](https://user-images.githubusercontent.com/44345420/47270481-b08cc580-d56c-11e8-9b60-a0e3dd2b984e.jpg)

**Expected behaviour**: 
The player shouldn't immune to buffs.

**Server Revision**: 
2194

**Comment by Wolffenstein** [comment]
Fixed in rev 2210.
