### ISSUE TITLE
Talent "Anticipation" prevents Defense skillups

### ISSUE THREAD

**Issue by manslaughter** [Atlantiss/NetherwingBugtracker#178]
**Description**: Warrior protection talent Anticipation gives +4 defense per point.

**Current behaviour**: While you get the +4 defense, combat with NPCs does not increase defense past your level x 5.  The bonus defense (I'm assuming) is being included in the skillup chance calculation.

**Expected behaviour**: Defense should be able to eventually reach its displayed cap with enough combat.
![image](https://user-images.githubusercontent.com/4078568/45928444-4fd88180-bf09-11e8-974a-7293e1e1a30a.png)

**Server Revision**: 2028 patch 203

**Comment by MVerschoor** [comment]
Same issue for Paladin talent Anticipation.

**Comment by Mikik3jr** [comment]
Paladins have the same talent and it doesn't work for them as well.

**Comment by SirPhoebos** [comment]
Noticed this issue to on my Paladin, was just going to report it.

**Comment by wtRCH** [comment]
@pelekon

**Comment by Easyfraggy** [comment]
Is this still broken?

**Comment by Mikik3jr** [comment]
No, it works. (lol server rename fucked up again all my addons T_T)
![wowscrnshot_010419_114748](https://user-images.githubusercontent.com/43505031/50684643-99f7f580-1016-11e9-9b48-a76472d3bed1.jpg)

**Comment by Tankerbelle** [comment]
This issue made it into the release version.  My warrior has 5 points in Anticipation and will only cap defense at the default value for the level, not the +20 defense that it should with the points into the skill.

**Comment by arcwizard** [comment]
Same issue with paladin with same talent. I cleared dungeon BFD and got no one def skillup point.
![default](https://user-images.githubusercontent.com/43764742/50829577-997c9900-134d-11e9-8c05-b476ec7b17b7.jpg)

Server Revision 2603. Content patch 203.

**Comment by Pipeboss** [comment]
Re-confirming this is still an issue for Paladins as of 21/1/19.
![brokenpallytalent](https://user-images.githubusercontent.com/46883370/51457038-8cbf6280-1d9b-11e9-936b-67bb3498a473.JPG)

**Comment by hearthledger** [comment]
It's still bugged. Respeccing will fix this issue temporary until you level up, then it will be impossible to reach the missing points.

**Comment by Anselm123** [comment]
Still bugged and is a HUGE bug please help

**Comment by Wolffenstein** [comment]
Fixed in rev 2739.
