### ISSUE TITLE
[Quest] [Western Plaugelands] Locked Away

### ISSUE THREAD

**Issue by Unfairy** [Atlantiss/NetherwingBugtracker#1780]
Wandering skeleton supposed to have 100% chance to drop they key to turn quest "Locked Away". Didn't gave me key on kill.
Entry: 10816
GUID: 42421
![ss1](https://user-images.githubusercontent.com/41975070/47270612-ae2b6b00-d56e-11e8-9813-f9afbda68c14.jpeg)
Farmer Dalson supposed to give me 100% Dalson Kabinet Key to turn quest for Dalson's Cabinet. And it had no loot.
![ss2](https://user-images.githubusercontent.com/41975070/47270623-ce5b2a00-d56e-11e8-83d2-85e156562a94.jpeg)

**Comment by Evolvee** [comment]
Are you sure you had proper quests rewarded? (q 5058 for example)

**Comment by Unfairy** [comment]
You might be right here actually. But I cant test it already.

**Comment by Evolvee** [comment]
I remember testing this quest sequence very clearly and it was fine, so Im closing this for now, if u tell me your ingame character, i can remove you the quests so u can try it again.

**Comment by Unfairy** [comment]
sure, ofc. Nickname: Fairy
Alliance

**Comment by Unfairy** [comment]
just whisper me if you did it pls :)

**Comment by Unfairy** [comment]
Fake news, everyone /sorry
