### ISSUE TITLE
[Spell][NPC]Tirion Fordring#1855 lacking abilities and phrase on engage

### ISSUE THREAD

**Issue by Tenoutoften** [Atlantiss/NetherwingBugtracker#1781]
**Description**: 
[[NPC]Tirion Fordring#1855](https://www.wowhead.com/npc=1855/tirion-fordring#comments) seems to lack his abilities.

He should have:
[[Spell]Holy Light](https://db.excalibur.ws/?search=holy+light#spells)
[[Spell]Exorcism](https://db.excalibur.ws/?search=exorcism#spells)
[[Spell]Hammer of Justice](https://db.excalibur.ws/?search=hammer+of+justice)
[[Spell]Devotion Aura](https://db.excalibur.ws/?search=devotion+aura) ~1100 armor

![2d8dd15f53048901a8a3b62f59ac99d5](https://user-images.githubusercontent.com/34839199/47271183-77f1e980-d576-11e8-956b-821a6b0d9f24.png)
![9dd2130a76274a19de9925730df56b74](https://user-images.githubusercontent.com/34839199/47271184-77f1e980-d576-11e8-8238-78bb834cd42a.png)

>Say hello to my little friend!

I think it is fair to say he should face the other way and be at a slightly different position to, position doesn't matter much, but it looks strange that he is facing towards his house.
https://www.wowhead.com/npc=1855/tirion-fordring#screenshots

1# 2006, December 12th
![6161-tirion-fordring](https://user-images.githubusercontent.com/34839199/47271277-94daec80-d577-11e8-89b9-ac2120f3c0cc.jpg)

2# 2007, June 17th
![29312-tirion-fordring](https://user-images.githubusercontent.com/34839199/47271278-94daec80-d577-11e8-9a8e-38241b8acf76.jpg)

**Current behaviour**:
Seems to only auto attack mobs.

**Expected behaviour**: 
Expected to use abilities, and his devotion aura should apply to horde/alliance characters in addition to healing them if they are low on health.

**Server Revision**: 
2194

**Comment by Evolvee** [comment]
rev yummy
