### ISSUE TITLE
[Spell] [Druid] Poor boomie

### ISSUE THREAD

**Issue by Onsty** [Atlantiss/NetherwingBugtracker#1782]
[//]: # (Enclose links to things related to the bug using http://wowhead.com or any other TBC database.)
[//]: # (You can use screenshot ingame to visual the issue.)
[//]: # (Write your tickets according to the format:)
[//]: # ([Quest][Azuremyst Isle] Red Snapper - Very Tasty!)
[//]: # ([NPC] Magistrix Erona)
[//]: # ([Spell][Mage] Fireball)
[//]: # ([Npc][Drop] Ghostclaw Lynx)
[//]: # ([Web] Armory doesnt work)

**Description**: 
Balance druids talent [Nature's Grace] applying incorrectly.

**Current behaviour**:
Nature's Grace buff occur only AFTER spell deals critical damage (+ 0.4sec with delay system), in this case if I am chain spamming a non-instant spell and a critical occurs, buff not applying for the next cast, so if it's 2 crits in a row i am lost 1 nature's grace buff.

ps. sorry for my googletranslate english

**Expected behaviour**: 
http://wowwiki.wikia.com/wiki/Nature's_Grace
"The Nature's Grace effect occurs when a spell that will crit has finished being cast, meaning that wraths that are still travelling to the target, but are predetermined critical strikes, will proc Nature's Grace before the damage is dealt to the target."
this is how it works right now on retail and this is how it is shown in many different tbc retail videos

examples:
~0:38, ~0:46, ~3:45(best example) --- https://www.youtube.com/watch?v=d1XzHH4yORw (TBC beta)
~1:00 --- https://www.youtube.com/watch?v=I3345gBs1WA
~0:58 --- https://www.youtube.com/watch?v=WB4sL6tfBWA (1 month after TBC release)

**Server Revision**:

**Comment by Tenoutoften** [comment]
I'd really like to see this one fixed... Don't play a druid, but seen other servers fail on it.

**Comment by Wolffenstein** [comment]
Fixed in rev 2204.
