### ISSUE TITLE
[Sunken Temple] Weaver and Dreamscythe wrong EXP

### ISSUE THREAD

**Issue by Azalen** [Atlantiss/NetherwingBugtracker#1784]
**Description**: 
https://classicdb.ch/?npc=5720
https://classicdb.ch/?npc=5721

**Current behaviour**:
Weaver and Dreamscythe (the two that spawn after you kill Jammal) only reward 2 EXP. The other two dragons reward normal exp for their level (in my case 186).

![wowscrnshot_102118_215803](https://user-images.githubusercontent.com/20336567/47271992-8db7dc80-d57f-11e8-9c1d-993fe0df7943.jpg)

**Expected behaviour**: 
They should reward full mob exp.

**Server Revision**: 
[2195]

**Comment by Evolvee** [comment]
the infernal at DP event also rewarded only 2 XP, this is potentially a core issue

**Comment by Azalen** [comment]
Ye it looks like summoned and event spawned mobs only reward 1 EXP (2 EXP if rested). Happens at the Zul'Farak Event as well.
#1593

**Comment by Evolvee** [comment]
https://github.com/Atlantiss/NetherwingBugtracker/issues/1945
