### ISSUE TITLE
[Sunken Temple] Zolo

### ISSUE THREAD

**Issue by Azalen** [Atlantiss/NetherwingBugtracker#1786]
**Description**: 
https://classicdb.ch/?npc=5712
https://classicdb.ch/?spell=12506

**Current behaviour**:
Totem gets placed down but it takes several seconds for it to spawn a skeleton.

**Expected behaviour**: 
Totem should spawn first skeleton on putdown and more skeletons faster as seen here: https://youtu.be/NyNA6liYJkI?t=76

**Server Revision**: 
[2195]

**Comment by Evolvee** [comment]
its every 10 sec atm

**Comment by Evolvee** [comment]
what should be the timer then

**Comment by Azalen** [comment]
Hard to tell but it should definatly summon the first skeleton the second the totem gets put down.
Second proof to back this up and in general great source for Sunken Temple: https://youtu.be/AJshReKneQg?t=266

**Comment by Evolvee** [comment]
I will make it on spawn for sure, but then i need to set some timer for future skeletons ^^ and im pretty lazy at researching pve, on top of it, researching vanilla pve 😸

**Comment by Azalen** [comment]
I'd go with 5 seconds. In the first video at 1:22 you can see that it takes 3 GCD's before 2nd skeleton spawns.

**Comment by Peglaa** [comment]
From a guide in 2006:
![2018-10-27_23h50_42](https://user-images.githubusercontent.com/15163719/47609658-2f896e80-da43-11e8-8f72-ce64147b053e.png)

**Comment by Evolvee** [comment]
rev yummy
