### ISSUE TITLE
Server Restart resets Tower Status in EPL 'A Game of Towers' Event

### ISSUE THREAD

**Issue by Azalen** [Atlantiss/NetherwingBugtracker#1787]
**Description**: 
http://wowwiki.wikia.com/wiki/A_Game_of_Towers

**Current behaviour**:
I conquered all Towers for the Alliance but Server Restart reset it all.

**Expected behaviour**: 
Should not reset all the time.

**Server Revision**: 
[2195]

**Comment by Azalen** [comment]
Found a comment indicating this might be intended. They apparently should reset once a week after server maintenance.

> By eDGe87 on 05/26/2010 (Patch 3.1.3)
A tip is you do this right after the maintenance. The towers will all be neutral, and by being neutral, a quick cap.
You must be flagged for PvP if you play on a normal server.

> This counts towards Loremaster of EK.

**Comment by Tereneckla** [comment]
Retail behaviour
