### ISSUE TITLE
[Sunken Temple] Atal'alarion

### ISSUE THREAD

**Issue by Azalen** [Atlantiss/NetherwingBugtracker#1789]
**Description**: 
https://classicdb.ch/?npc=8580
https://classicdb.ch/?spell=12887

**Current behaviour**:
His Slam ability throws tank into the air and he follows into the air getting stuck. For us he eventually evaded back to full health.
![wowscrnshot_102118_210803](https://user-images.githubusercontent.com/20336567/47272620-716c6d80-d588-11e8-8df3-c9cf481435bd.jpg)

**Expected behaviour**: 
Should not follow a target in the air.

**Server Revision**: 
[2195]

**Comment by Mikik3jr** [comment]
The boss reseted itself, went back to its spawn and shouted the event twice (he says a line when he is summoned)
![wowscrnshot_102118_210852](https://user-images.githubusercontent.com/43505031/47272822-30c22380-d58b-11e8-8362-19f6a2c6b6e1.jpg)

Sadly a worm was still in the air and we couldn't kill it, cuz it evaded our attacks. Somehow we managed to kill it somehow.
![wowscrnshot_102118_211003](https://user-images.githubusercontent.com/43505031/47272809-1b4cf980-d58b-11e8-85fe-fcbae01c4e19.jpg)

**Comment by Mewmewww** [comment]
Must've been some bugfixes that caused this. When I did ST, this was not the case

**Comment by Tereneckla** [comment]
Fixed
