### ISSUE TITLE
Short Mob/NPC Show Up Distance

### ISSUE THREAD

**Issue by ttghnw** [Atlantiss/NetherwingBugtracker#179]
[//]: # (Enclose links to things related to the bug using http://wowhead.com or any other TBC database.)
[//]: # (You can use screenshot ingame to visual the issue.)
[//]: # (Write your tickets according to the format:)
[//]: # ([Quest][Azuremyst Isle] Red Snapper - Very Tasty!)
[//]: # ([NPC] Magistrix Erona)
[//]: # ([Spell][Mage] Fireball)
[//]: # ([Npc][Drop] Ghostclaw Lynx)
[//]: # ([Web] Armory doesnt work)

**Description**: 
I'm not sure this is intended on your side, but when I am able to see the mobs that actually exist in the area I'm almost bumping into them...okay what 50 yards? It's bad enough that a red mob (as in 5+ levels) when its shown will often be at or really close to aggro range as they will elude you easily when you are expecting clear path. Please clarify it this is your intended setup or a bug. I have never seen such short distance to see the existent mobs on any retail or private server.

I believe it is not so relevant but yes I have max view distance on and the environmental details show perfectly.

**Current behaviour**:

**Expected behaviour**: 
I have never seen such short distance to see the existent mobs on any retail or private server.

**Server Revision**:

**Comment by Tenoutoften** [comment]
View distance has been changed a few times now, I believe this report is no longer relevant.
