### ISSUE TITLE
[Dungeon] Party member disappearing visually for 1 person

### ISSUE THREAD

**Issue by nycheia** [Atlantiss/NetherwingBugtracker#1791]
Tank perspective: https://cdn.discordapp.com/attachments/473892562881609748/503686792109883416/afsafaf.png

My perspective: https://prnt.sc/l8p9j3

**Description**: 
I became invisible to our tank (Doggo). He could not see me, he could see i was still in his party, but the hp and mana were not updating in the party frames. He could buff me with battle shout though, and i could heal him and i had no problems. Him relogging solved it.

**Current behaviour**:
Party member not visible in dungeon

**Expected behaviour**: 
Be visible in dungeon to party members at all times

**Server Revision**: 
2194

**Comment by aresbrutus** [comment]
Seems to be a client issue honestly. Since you were able to interact with him meaning he was there next to you.

**Comment by nycheia** [comment]
> Seems to be a client issue honestly. Since you were able to interact with him meaning he was there next to you.

yeah no idea, never experienced this on other tbc servers, so i made the report just in case

**Comment by nullfoxh** [comment]
Pretty sure it's not a client issue. This didn't happen during retail and only happens on some TBC servers. Difficult to pin down tho since it's really random.

**Comment by aresbrutus** [comment]
Could you download the client off the atlantiss page and try playing with this one? Post any further issues related to chars disappearing after using this client. https://beta.atlantiss.eu/open-beta

**Comment by nycheia** [comment]
i'll forward that to him

**Comment by Azalen** [comment]
It never happened to me but almost all the time I went into a 5man dungeon this happened for one of the grp members. Ez fix though if you zone out and in again.

This is by no means a TBC only issue. I remember this issue from early Nostalrius as well but they eventually fixed it.
