### ISSUE TITLE
([Quest][Stranglethorn Vale] Mok'thardin's Enchantment)

### ISSUE THREAD

**Issue by natoxz** [Atlantiss/NetherwingBugtracker#1793]
**Description**: 
Quest: https://db.excalibur.ws/?quest=571
Questitem: https://db.excalibur.ws/?item=3862

**Current behaviour**:
Questitem Aged Gorilla Sinew doesn't drop

**Expected behaviour**: 
Questitem should drop

**Comment by Tenoutoften** [comment]
I have done this quest before and it did drop. It has a very low drop rate(which is intended)
https://www.wowhead.com/quest=571/mokthardins-enchantment
![f1e6cb285f2752e2a8f5ad2562c5dad0](https://user-images.githubusercontent.com/34839199/47280021-9d154500-d5d4-11e8-84ac-ced377bfd218.png)

![51d023bc8fbf4ddea3c12a487e83ac5f](https://user-images.githubusercontent.com/34839199/47280018-9c7cae80-d5d4-11e8-807a-ca1bd057fc31.png)

Try to check out wowhead comments and see what they say about the drop chance before reporting / tell us how many you have killed without getting it.

**Comment by Tenoutoften** [comment]
Dropped for me, has a low chance though.
https://www.wowhead.com/quest=571/mokthardins-enchantment
![51d023bc8fbf4ddea3c12a487e83ac5f](https://user-images.githubusercontent.com/34839199/47281455-80c8d680-d5db-11e8-99c8-dbcd38294e55.png)
![f1e6cb285f2752e2a8f5ad2562c5dad0](https://user-images.githubusercontent.com/34839199/47281456-81616d00-d5db-11e8-9eb7-1e46696b17f1.png)

**Comment by aresbrutus** [comment]
Nothing is wrong with this item. It drops but has a low drop chance so it might give you the illusion that it is not ever going to drop.

**Comment by whispersz** [comment]
about an hour and 10 minutes. 100+ gorrilas killed. 42K xp grinded and still no drop. Seems to work fine
