### ISSUE TITLE
[Sunken Temple] Atal'ai Witch Doctor should run away in fear.

### ISSUE THREAD

**Issue by Azalen** [Atlantiss/NetherwingBugtracker#1796]
**Description**: 
http://classicdb.ch/?npc=5259

**Current behaviour**:
Mob doesn't run away in fear.

**Expected behaviour**: 
Should run away in fear.
Proof: https://youtu.be/AJshReKneQg?t=311

**Server Revision**: 
[2196]

**Comment by Tereneckla** [comment]
Fixed
