### ISSUE TITLE
[Spell][Mage] Polymorph breaking too early

### ISSUE THREAD

**Issue by Dekirayne** [Atlantiss/NetherwingBugtracker#1799]
[//]: # (Enclose links to things related to the bug using http://wowhead.com or any other TBC database.)
[//]: # (You can use screenshot ingame to visual the issue.)
[//]: # (Write your tickets according to the format:)
[//]: # ([Quest][Azuremyst Isle] Red Snapper - Very Tasty!)
[//]: # ([NPC] Magistrix Erona)
[//]: # ([Spell][Mage] Fireball)
[//]: # ([Npc][Drop] Ghostclaw Lynx)
[//]: # ([Web] Armory doesnt work)

**Description**: 
Polymorph spell randomly breaks, much much earlier then the time is remaining on the spell.
**Current behaviour**:
Breaks randomly at half duration or even earlier in some situations, mostly it does it if the mob is pulled from his original position where he stood, he just breaks and evades.
**Expected behaviour**: 
It should NEVER EVER break for "Evade" unless combat is broken and you moved away. Or even break before the spell is finished
**Server Revision**:

**Comment by Easyfraggy** [comment]
https://github.com/Atlantiss/NetherwingBugtracker/issues/1519

**Comment by ttghnw** [comment]
#525

**Comment by Easyfraggy** [comment]
Can you please retest this after the latest Leashing changes?

**Comment by Mewmewww** [comment]
Reopen

**Comment by killablink** [comment]
Still bugged, sheep is breaking early for no reason, happened to me multiple times:
https://gfycat.com/PinkEmptyHarvestmen
