### ISSUE TITLE
Energy while dead

### ISSUE THREAD

**Issue by AlteredAli** [Atlantiss/NetherwingBugtracker#18]
[//]: # (Enclose links to things related to the bug using http://wowhead.com or any other TBC database.)
[//]: # (You can use screenshot ingame to visual the issue.)
[//]: # (Write your tickets according to the format:)
[//]: # ([Quest][Azuremyst Isle] Red Snapper - Very Tasty!)
[//]: # ([NPC] Magistrix Erona)
[//]: # ([Spell][Mage] Fireball)
[//]: # ([Npc][Drop] Ghostclaw Lynx)
[//]: # ([Web] Armory doesnt work)

**Description**: 
Energy as a rogue still shows as 100 while dead in party 
**Current behaviour**:

**Expected behaviour**: 

**Server Revision**:

**Comment by SwiftieTBC** [comment]
This isnt a bug,
A rogue keeps the level of energy he had when he dies, example https://youtu.be/DteFZq5l0og?t=386.
Therefore if your rogue died on 100% energy him showing 100% is correct
