### ISSUE TITLE
[NPC] Tzerak - Double yell message

### ISSUE THREAD

**Issue by Firroth** [Atlantiss/NetherwingBugtracker#180]
[NPC] Tzerak

**Current behaviour**:
He yells the same text at the same time two times.
See chat on the screenshoot.
![screenshot_3](https://user-images.githubusercontent.com/43505196/45928498-fb52f780-bf44-11e8-9c2d-dc3f05c52198.png)

**Expected behaviour**: 
Should only be 1 "yell" message on the chat.

**Server Revision**: 
2029

**Comment by Evolvee** [comment]
@Wolffenstein probably because of your "on respawn/reset" fix from yesterday

**Comment by randomuser69** [comment]
This still happens

**Comment by Wolffenstein** [comment]
Fixed in rev 3155.
