### ISSUE TITLE
Pet aggro table (?) In relation with FD.

### ISSUE THREAD

**Issue by Lecia2134** [Atlantiss/NetherwingBugtracker#1800]
Could be wrong but I'd be remissed if I didnt mention, as it seems off. So I was on the beta made a level 40 hunter and went to tanaris. Killed a few wastewalker npcs and in the process I pulled a group of 3 standing together, with my pet. All 3 landed hits on the pet and then I multi shotted, transfering aggro of all 3 to me. I feigned death and oddly enough 2 of the 3 NPCs reset. The only one to continue attacking my pet was the one it had hit. It's as if its aggro table reset and they didnt know he was there as soon as I pulled from the pet. Also it should be noted that while it is nice that I dont have to run a mile to reset mobs, it seems like they're losing track of me way too easily, in terms of distance from where I pull them from. I only have to walk maybe 40 yards and they reset (maybe this is correct? I've experienced a lot of pserver fun so maybe my memory of retail is shit).

**Comment by Manaci** [comment]
Fixed
