### ISSUE TITLE
[Spell][Mage] Arcane Concentration and Arcane Missiles

### ISSUE THREAD

**Issue by ircfelix** [Atlantiss/NetherwingBugtracker#1801]
**Description**: 
If **Clearcasting** (the buff from **5/5 Arcane Concentration**) is up, **Arcane Missiles** should consume the debuff on cast (not on first missile hit) but ALL five missiles will be affected by the 30% crit bonus from the **3/3 Arcane Potency** talent. (according to this source http://wowwiki.wikia.com/wiki/Talk:Arcane_Potency).
According to http://wowwiki.wikia.com/wiki/Arcane_Potency?oldid=1432062, Arcane Missiles should also be able to get twice the crit bonus from this talent (60% crit!).

**Current behaviour**:
When the Clearcasting buff is up and you start casting Arcane Missiles, the none of the five missiles seems to benefit from the 30% crit bonus. In 14 observed Clearcasts, of which two were double procs and should have had a 60% crit chance, I rarely observed any crits at all, which indicates that the crit bonus does not work as it should for Arcane Missiles.

**Expected behaviour**: 
When you get a Clearcasting proc, all five missiles of the next Arcane Missiles cast should get the 30% crit bonus from Arcane Potency and if you get another proc from the first missile of the second cast, the remaining four missiles of the second cast should get a 60% crit bonus.

**Server Revision**: 
2196

**Comment by ircfelix** [comment]
http://wowwiki.wikia.com/wiki/Arcane_Missiles?oldid=1548485

While you stand and channel, Arcane Missiles launches bolts of arcane energy at your target, dealing the given damage each second. Unlike other channeled spells, each second (or "tick") is considered a separate direct damage missile which passes through the normal direct damage checks (crit, resistance). **Furthermore, both the initial cast of Arcane Missiles and each Missile are considered spell hits, resulting in a maximum amount of 6 hits per cast.**

Like all channeled spells, the mana is deducted before channeling starts, so the full cost is paid regardless of how many missiles are actually launched or needed before the spell is interrupted or the target is dead.

**Comment by Wolffenstein** [comment]
Fixed in rev 2202.

**Comment by ircfelix** [comment]
Just retested, works perfectly. Significantly higher crit chances on clear casting and double clear casting procs.
