### ISSUE TITLE
[NPC]Winterfall Shaman#7439 [Spell]Healing Touch is way to weak ~250-300

### ISSUE THREAD

**Issue by Tenoutoften** [Atlantiss/NetherwingBugtracker#1802]
**Description**: 
[[NPC]Winterfall Shaman#7439](https://www.wowhead.com/npc=7439/winterfall-shaman#abilities)'s [[Spell]Healing Touch](https://db.excalibur.ws/?search=healing+touch#spells) is way to weak:
![fa5a055ca1e7fb92561b1d9f60a230c1](https://user-images.githubusercontent.com/34839199/47303294-d1642200-d623-11e8-8d70-b4a2527d7fd1.png)

Heals about 250 as level 56-57

**Expected behaviour**: 
Expected to heal significantly more

**Server Revision**: 
2196

**Comment by Evolvee** [comment]
rev ff15
