### ISSUE TITLE
[NPC][Thousand Needles] "Plucky" Johnson

### ISSUE THREAD

**Issue by eryczek1615** [Atlantiss/NetherwingBugtracker#1803]
**Description**: 
[Plucky Johnson](https://www.wowhead.com/npc=6626/deprecated-for-4-x-plucky-johnson#comments)

**Current behaviour**:
When you emote /chicken to him he turns into human but doesn't wave at you.

**Expected behaviour**: 
![image](https://user-images.githubusercontent.com/4455568/47303472-459ec580-d624-11e8-85e1-4b880fae7d2c.png)
after emote /chicken he should wave at you and then turn back into chicken

**Server Revision**: 
2196

**Comment by Wolffenstein** [comment]
Fixed in rev 3400.
