### ISSUE TITLE
Jaedenar Darkweaver patrol doesn't attack

### ISSUE THREAD

**Issue by samemari** [Atlantiss/NetherwingBugtracker#1804]
**Description**: 
Jaedenar Darkweaver patrol in the Shadow Hold doesn't attack me or my totem while getting dmg from searing totem
**Current behaviour**:
Mob died from Searing totem and shaman spells like Lighting Bolt and Earth Shock, but didn't make any dmg to shaman or totem, mob didn't get any dmg from melee attacks (white damage from weapon), spell damage only
NPC info is on the screenshot
![wowscrnshot_102218_185308](https://user-images.githubusercontent.com/29822974/47304067-40df0f00-d62e-11e8-8fd2-d5bacf9c876a.jpg)

**Server Revision**: 
2196

**Comment by Tenoutoften** [comment]
This is rape!!!

**Comment by Easyfraggy** [comment]
retest this in current rev, should be fixed.
