### ISSUE TITLE
[Loot] Tortured Druids #12178 and Sentinels#12179 drop invisible loot.

### ISSUE THREAD

**Issue by Jezofine** [Atlantiss/NetherwingBugtracker#1805]
**Current behaviour**:
[Tortured Druid](http://web.archive.org/web/20080229051237/http://thottbot.com:80/c12178)
[Tortured Sentinel](http://web.archive.org/web/20080229062915/http://thottbot.com:80/c12179)
After their death corpses often sparkle and shown as if they contain some loot.
I can make a guess that it is [Scorched Ectoplasm](http://web.archive.org/web/20080229062915/http://thottbot.com:80/c12179) since it's the only quest item. 
I don't even have any quest of this chain.

**Expected behaviour**:
Should drop only for quest.
Also drop rate might be off

**Server Revision**: 2196

**Comment by Wolffenstein** [comment]
Fixed.
