### ISSUE TITLE
[Quest][Tanaris] Screecher Spirits

### ISSUE THREAD

**Issue by Mikik3jr** [Atlantiss/NetherwingBugtracker#1806]
[//]: # (Enclose links to things related to the bug using http://wowhead.com or any other TBC database.)
[//]: # (You can use screenshot ingame to visual the issue.)
[//]: # (Write your tickets according to the format:)
[//]: # ([Quest][Azuremyst Isle] Red Snapper - Very Tasty!)
[//]: # ([NPC] Magistrix Erona)
[//]: # ([Spell][Mage] Fireball)
[//]: # ([Npc][Drop] Ghostclaw Lynx)
[//]: # ([Web] Armory doesnt work)

**Description**: 
In this quest you have to go Feralas, and kill these:
-Vale Screecher (https://www.wowhead.com/npc=5307/vale-screecher)
-Rogue Vale Screecher (https://www.wowhead.com/npc=5308/rogue-vale-screecher
and you have to use Yeh'kinya's Bramble(https://www.wowhead.com/item=10699/yehkinyas-bramble) on the dead bodies to make their spirit appear and talk to them.

**Current behaviour**:
When you right click to talk to the spirits they disappear instantly not allowing you to read the text (you progress the quest)

**Expected behaviour**: 
I don't think a 4-5 row long text would be there if you weren't able to read it.

**Server Revision**: 
2196

**Comment by bimbear** [comment]
Server Revision:2338
Getting "invalid target" message when trying to use quest item on corpses

**Comment by Manaci** [comment]
FIxed
