### ISSUE TITLE
[NPC] Samor Festivus <Shady Dealer> missing

### ISSUE THREAD

**Issue by ScottieDOESknow** [Atlantiss/NetherwingBugtracker#1807]
**Description**:  Samor Festivus <Shady Dealer> sells rogue reagents and zone level health pots

**Current behaviour**: Missing from Deepwater Tavern Inn (Wetlands)

**Expected behaviour**: Should be present leftmost room, after going up stairs.

https://www.wowhead.com/npc=1457/samor-festivus

https://vanillawowdb.com/?npc=1457

http://db.excalibur.ws/?npc=1457

**Server Revision**: 2197

**Comment by aresbrutus** [comment]
Fixed in rev `Eris`
