### ISSUE TITLE
[Core Mechanic][Paladin][Spell]Mobs will reset health when Vindication is applied & mob is dying to seal damage

### ISSUE THREAD

**Issue by Tenoutoften** [Atlantiss/NetherwingBugtracker#1808]
**Description**: 
It seems that when a mob is dying to a seal damage proc together with procing Vindication, it's health is reset. I previously thought this was strictly tied to Seal of Command, but someone in https://github.com/Atlantiss/NetherwingBugtracker/issues/3701 suggested it is from Vindication, but if it was just strictly Vindication it would happen a lot. So I think it is a combination.

[Example 1](https://www.youtube.com/watch?v=s9vouYeq_Ks)
[Example 2](https://www.youtube.com/watch?v=CyhsObHszlQ&feature=youtu.be)
[Example 3](https://www.youtube.com/watch?v=zM-sS5ivtNE&feature=youtu.be)
[Example 4](https://www.youtube.com/watch?v=JK1AzpW-qN0&feature=youtu.be)
[Example 5](https://www.youtube.com/watch?v=8NN67vhRblE&feature=youtu.be)
[Example 6](https://www.youtube.com/watch?v=TMSj1X_5zYY&feature=youtu.be)

---

[Example 7](https://youtu.be/Y6IWTSMhNBs?t=2) provided by https://github.com/Atlantiss/NetherwingBugtracker/issues/3701

I tried to reproduce this purely through Vindication, no seal damage, and it didn't work on an elite mob, tested on a lot of different health percentages. Which might mean it is a combination of seal damage & vindication proc, as it certainly seem to happen when vindication is proced.

1) Vindication procing 
2) Seal damage is being dealt 
3) Mob health is low(Perhaps dying to seal damage)

Debuff
[[Spell]Vindication(Rank 1)#67](https://db.excalibur.ws/?spell=67)
[[Spell]Vindication(Rank 2)#26017](https://db.excalibur.ws/?spell=26017)
[[Spell]Vindication(Rank 3)#26018](https://db.excalibur.ws/?spell=26018)

Which is a chance to proc from talents:
[[Spell]Vindication(Rank 1)#9452](https://db.excalibur.ws/?spell=9452)
[[Spell]Vindication(Rank 2)#26016](https://db.excalibur.ws/?spell=26016)
[[Spell]Vindication(Rank 3)#26021](https://db.excalibur.ws/?spell=26021)

**Expected behaviour**: 
Expect this to not happen.

**Server Revision**: 
2500

**Comment by Tenoutoften** [comment]
had this happen to me today on rev 2255, didn't get a video though, was fighting a wolf at this place
![8115caa3e9807e61bc85e40b313627b4](https://user-images.githubusercontent.com/34839199/48053284-9b3dab00-e1aa-11e8-8807-a1df6b501d05.png)

**Comment by Tenoutoften** [comment]
This is still happening in rev 2079, this time I had it recorded and within a dungeon... imagine this happening to a boss...
https://www.youtube.com/watch?v=zM-sS5ivtNE&feature=youtu.be

**Comment by Tenoutoften** [comment]
https://www.youtube.com/watch?v=8NN67vhRblE&feature=youtu.be

**Comment by Easyfraggy** [comment]
That last one:

![image](https://user-images.githubusercontent.com/36134067/48974321-585a4f00-f055-11e8-83fc-693185164aaa.png)

**Comment by Tenoutoften** [comment]
Its healing fully https://www.youtube.com/watch?v=TMSj1X_5zYY&feature=youtu.be

Anyways I have kind of figured this issue out now

**Comment by Tenoutoften** [comment]
This occurs only with paladin, and is related to seal of command proc damage killing the target

**Comment by Easyfraggy** [comment]
Oh that's cool - I also made a paladin a week ago and it happened to me there on imps in hfp - great you worked it out!

**Comment by Tenoutoften** [comment]
Tag it up my man<3

**Comment by Godmatik** [comment]
Was fixed many years ago, this issue was just never closed out.
