### ISSUE TITLE
[Object][Stranglethorn Vale]Altar of the Tides

### ISSUE THREAD

**Issue by DeltaLoads** [Atlantiss/NetherwingBugtracker#1809]
[//]: # (Enclose links to things related to the bug using http://wowhead.com or any other TBC database.)
[//]: # (You can use screenshot ingame to visual the issue.)
[//]: # (Write your tickets according to the format:)
[//]: # ([Quest][Azuremyst Isle] Red Snapper - Very Tasty!)
[//]: # ([NPC] Magistrix Erona)
[//]: # ([Spell][Mage] Fireball)
[//]: # ([Npc][Drop] Ghostclaw Lynx)
[//]: # ([Web] Armory doesnt work)

**Description**: 
Altar isnt in correct position
![wowscrnshot_102218_190646](https://user-images.githubusercontent.com/43690147/47306971-18efab80-d62e-11e8-8199-9681cd41863b.jpg)
should be on top - https://www.wowhead.com/object=2576/altar-of-the-tides#screenshots:id=59122
**Current behaviour**:
Wrong placement of altar
**Expected behaviour**: 
Should be placed as shown 
**Server Revision**: 
2196

**Comment by Shanghi** [comment]
This should be fixed in revision 2221.
