### ISSUE TITLE
Murloc hunter Westfall -> PET

### ISSUE THREAD

**Issue by SmokiFurry** [Atlantiss/NetherwingBugtracker#181]
The pet of the Murloc hunter (Westfall) follows forever. it shortly runs back and then follows again.  not every npc act like this

**Comment by The14me** [comment]
NPC id (the hunter) 458

**Comment by Evolvee** [comment]
Theres a core problem most likely. When you pull the npc. Pet runs for you and then evades back to owner even though the owner is still chasing you. (incorrectly "working" shared combat/chasing state of pet/owner).

**Comment by The14me** [comment]
Work fine in 3441.Can be closed.
