### ISSUE TITLE
Pet wont attack cc'd target

### ISSUE THREAD

**Issue by Lecia2134** [Atlantiss/NetherwingBugtracker#1810]
Hunter pet wont attack cc'd target on command. Only after I break it will it attack.

**Comment by Easyfraggy** [comment]
https://github.com/Atlantiss/NetherwingBugtracker/issues/456

**Comment by Lecia2134** [comment]
My mistake. Tried to look first didnt see it.

**Comment by Easyfraggy** [comment]
No worries, not easy to search for the issue it was reported in because it was only about freezing trap initially. I just try to close as many duplicates as possible so we can keep the tracker somewhat organized!
