### ISSUE TITLE
id 16[NPC]Crazed Owlbeast#7452 & id 26[NPC]Berserk Owlbeast#7454 standing too close & not moving

### ISSUE THREAD

**Issue by Tenoutoften** [Atlantiss/NetherwingBugtracker#1812]
**Description**: 
id 16[[NPC]Crazed Owlbeast#7452](https://db.excalibur.ws/?npc=7452) &
id 26[[NPC]Berserk Owlbeast#7454](https://db.excalibur.ws/?npc=7454) standing strangely close to each other and not moving at all:

![fa5a055ca1e7fb92561b1d9f60a230c1](https://user-images.githubusercontent.com/34839199/47311817-02038600-d63b-11e8-837f-89c309881442.png)

**Expected behaviour**: 
Expected to be further apart, perhaps there is a patrol in this village? Hard to tell

**Server Revision**: 
2196

**Comment by aresbrutus** [comment]
Fixed in rev `Eris`
