### ISSUE TITLE
[NPC] Firegut Ogre Mage wielding wrong weapon

### ISSUE THREAD

**Issue by netherwingbta** [Atlantiss/NetherwingBugtracker#1813]
[//]: # (Enclose links to things related to the bug using http://wowhead.com or any other TBC database.)
[//]: # (You can use screenshot ingame to visual the issue.)
[//]: # (Write your tickets according to the format:)
[//]: # ([Quest][Azuremyst Isle] Red Snapper - Very Tasty!)
[//]: # ([NPC] Magistrix Erona)
[//]: # ([Spell][Mage] Fireball)
[//]: # ([Npc][Drop] Ghostclaw Lynx)
[//]: # ([Web] Armory doesnt work)

**Description**: 
[Firegut Ogre Mage](https://www.wowhead.com/npc=7034/firegut-ogre-mage) is wielding weapon from cata patch. 
**Current behaviour**:
Wields a 1h mace, same as it is on [retail](http://www.youtube.com/watch?v=f_HL3p29A0o&t=14m59s).
**Expected behaviour**: 
Should wield a [staff](https://www.wowhead.com/spell=6742/bloodlust#screenshots:id=84706).
[A video.](http://www.youtube.com/watch?v=EZYdJuVzwhQ&t=15m50s)
**Server Revision**: 
2196

**Comment by Evolvee** [comment]
rev ff15
