### ISSUE TITLE
[Critical] Dungeon ID does not reset when making new group / player with ID joins existing group

### ISSUE THREAD

**Issue by Azalen** [Atlantiss/NetherwingBugtracker#1814]
**Current behaviour**:
I encountered this issue today while running SM. I made a new group with my brand new level 40 char (no IDs, obviously), invited two more guys and then invited a player who did SM some hours ago. Even though he joined a total new group our group took his ID (we did not notice this at that point ofc ^^) and cleared SM Library trash just to realize that the endboss is not there.

**Expected behaviour**: 
An existing group without any ID's should not take the ID of a joining player with an ID.

**Server Revision**: 
[2196]

**Comment by Tenoutoften** [comment]
Pretty sure I have seen this report before hmm
