### ISSUE TITLE
Unable to bless [NPC]Arko'Narin#11018 during Rescue from Jaedenar 

### ISSUE THREAD

**Issue by Tenoutoften** [Atlantiss/NetherwingBugtracker#1815]
**Description**: 
"A more powerful spell is already active" despite [[NPC]Arko'Narin#11018](https://db.excalibur.ws/?npc=11018) having zero buffs.
https://youtu.be/KMFzGpSUz6c

**Expected behaviour**: 
Expected to be able to bless

**Server Revision**: 
2196

**Comment by The14me** [comment]
Cant reproduce(maybe cuz last fix's) .Please retest and if happen again reopen.
