### ISSUE TITLE
[Quest][Stranglethorn Vale]Stranglethorn Fever

### ISSUE THREAD

**Issue by DeltaLoads** [Atlantiss/NetherwingBugtracker#1816]
[//]: # (Enclose links to things related to the bug using http://wowhead.com or any other TBC database.)
[//]: # (You can use screenshot ingame to visual the issue.)
[//]: # (Write your tickets according to the format:)
[//]: # ([Quest][Azuremyst Isle] Red Snapper - Very Tasty!)
[//]: # ([NPC] Magistrix Erona)
[//]: # ([Spell][Mage] Fireball)
[//]: # ([Npc][Drop] Ghostclaw Lynx)
[//]: # ([Web] Armory doesnt work)

**Description**: 
When trying to get Heart of Mokk, Mokk the Savage and Konda sometimes despawn before they even get inside a cave
https://streamable.com/1aqdo

**Current behaviour**:
Mokk and Konda despawn before even getting inside a cave
**Expected behaviour**: 
Mokk and Konda should always enter cave and attack player or npc
**Server Revision**: 
2196

**Comment by Evolvee** [comment]
rev ff15
