### ISSUE TITLE
[NPC][Stranglethorn Vale]Bloodsail Warlock

### ISSUE THREAD

**Issue by DeltaLoads** [Atlantiss/NetherwingBugtracker#1817]
[//]: # (Enclose links to things related to the bug using http://wowhead.com or any other TBC database.)
[//]: # (You can use screenshot ingame to visual the issue.)
[//]: # (Write your tickets according to the format:)
[//]: # ([Quest][Azuremyst Isle] Red Snapper - Very Tasty!)
[//]: # ([NPC] Magistrix Erona)
[//]: # ([Spell][Mage] Fireball)
[//]: # ([Npc][Drop] Ghostclaw Lynx)
[//]: # ([Web] Armory doesnt work)

**Description**: 
Some Bloodsail Warlocks are missing their pets when patroling around nor do they spawn them when you attack
![wowscrnshot_102218_232515](https://user-images.githubusercontent.com/43690147/47320804-caa0d380-d652-11e8-8bf1-dc847ec583a8.jpg)
![wowscrnshot_102218_233027](https://user-images.githubusercontent.com/43690147/47320807-cc6a9700-d652-11e8-9b8f-7affe09bf7db.jpg)
![untitled](https://user-images.githubusercontent.com/43690147/47320813-cffe1e00-d652-11e8-9642-506822be40f3.png)

**Current behaviour**:
Bloodsail Warlocks missing their pets
**Expected behaviour**: 
Bloodsail Warlocks should always have imp or succubus with them
**Server Revision**: 
2196

**Comment by Kidtoucher** [comment]
They aren´t missing their pets anymore.

**Comment by Tereneckla** [comment]
Fixed
