### ISSUE TITLE
[NPC] Ashenvale Satyr using cata weapons

### ISSUE THREAD

**Issue by netherwingbta** [Atlantiss/NetherwingBugtracker#1818]
[//]: # (Enclose links to things related to the bug using http://wowhead.com or any other TBC database.)
[//]: # (You can use screenshot ingame to visual the issue.)
[//]: # (Write your tickets according to the format:)
[//]: # ([Quest][Azuremyst Isle] Red Snapper - Very Tasty!)
[//]: # ([NPC] Magistrix Erona)
[//]: # ([Spell][Mage] Fireball)
[//]: # ([Npc][Drop] Ghostclaw Lynx)
[//]: # ([Web] Armory doesnt work)

**Description**: 
Almost all the satyrs are using weapons that they were given in the cata patch.
**Current behaviour**:
[Prince Raze](https://www.wowhead.com/npc=10647/prince-raze#screenshots) is wielding a big axe. He should not use it.
>[By DrCheis](https://www.wowhead.com/npc=10647/prince-raze#comments:id=1373962) (49,503 – 6·36·409) on 2011/03/23 (Patch 4.0.6) |   |  
Prince Raze went out and bought himself a nice shiny Axe after the Shattering.

[Xavian Rogue](https://www.wowhead.com/npc=3752/xavian-rogue#screenshots) is currently dual wielding axes. 
[Xavian Betrayer](https://www.wowhead.com/npc=3754/xavian-betrayer#screenshots) is wielding a scythe.
[Bleakheart Trickster](https://www.wowhead.com/npc=3767/bleakheart-trickster#screenshots) is using a dagger in one hand.
[Bleakheart Shadowstalker](https://www.wowhead.com/npc=3770/bleakheart-shadowstalker#screenshots) is using a weird claw.
[Felmusk Rogue](https://www.wowhead.com/npc=3759/felmusk-rogue#screenshots) is dual wielding daggers.
[Felmusk Shadowstalker](https://www.wowhead.com/npc=3763/felmusk-shadowstalker#screenshots) is wielding a spear.
**Expected behaviour**: 
They should not use any weapons. 
Not TBC, but [here's](http://www.youtube.com/watch?v=rFcE2P8E44c&t=130m50s) joana fighting them. 
**Server Revision**: 
2196

**Comment by Wolffenstein** [comment]
Fixed in rev 3400.
