### ISSUE TITLE
[NPC] Hexed Troll

### ISSUE THREAD

**Issue by BlessedByTheSin** [Atlantiss/NetherwingBugtracker#182]
[//]: # (Enclose links to things related to the bug using http://wowhead.com or any other TBC database.)
[//]: # (You can use screenshot ingame to visual the issue.)
[//]: # (Write your tickets according to the format:)
[//]: # ([Quest][Azuremyst Isle] Red Snapper - Very Tasty!)
[//]: # ([NPC] Magistrix Erona)
[//]: # ([Spell][Mage] Fireball)
[//]: # ([Npc][Drop] Ghostclaw Lynx)
[//]: # ([Web] Armory doesnt work)

**Description**: 
Bad mob's pathing/moving behavior.
ID: 3207
**Current behaviour**:
https://imgur.com/fVkQpAx
**Expected behaviour**: 
/shrug
**Server Revision**: 
2028

**Comment by Evolvee** [comment]
please use .npc info next time to tell me entry + id of the mob

thanks

**Comment by Evolvee** [comment]
fixed in next hotfix revision
