### ISSUE TITLE
[Spell][Priest] Mind Flay and Shadow Weaving

### ISSUE THREAD

**Issue by weppas** [Atlantiss/NetherwingBugtracker#1820]
[//]: # (Enclose links to things related to the bug using http://wowhead.com or any other TBC database.)
[//]: # (You can use screenshot ingame to visual the issue.)
[//]: # (Write your tickets according to the format:)
[//]: # ([Quest][Azuremyst Isle] Red Snapper - Very Tasty!)
[//]: # ([NPC] Magistrix Erona)
[//]: # ([Spell][Mage] Fireball)
[//]: # ([Npc][Drop] Ghostclaw Lynx)
[//]: # ([Web] Armory doesnt work)

**Description**: Mind Flay doesn't add a stack of Shadow Weaving as it should be.

**Current behaviour**: https://www.dropbox.com/s/5h2qcte2qm2dlz3/2018-10-23_00-59-35.mp4?dl=0

**Expected behaviour**: I believe Shadow Weaving should either be added per tick of Mind Flay. Or it should add a stack each time you recast Mind Flay.

**Server Revision**: 2196

**Comment by Azalen** [comment]
What better video to proof this than "Learning to Flay".
https://youtu.be/FArCxTrkNVg?t=212

Should add 1 tick per cast, not per tick.

**Comment by weppas** [comment]
Thanks for that video, still something is messed up when you recast mind flay before the first channel hasnt finished.

**Comment by weppas** [comment]
Yeah wasnt 100% sure on which of the interactions was supposed to be correct. But yes if you recast mind flay before the previous cast ends you dont apply a new stack. Going to try it with a no channel macro and see and add another video.

**Comment by weppas** [comment]
Here is a video with a nochanneling macro: https://www.dropbox.com/s/d5yd07gepta8lm2/2018-10-23_12-54-16.mp4?dl=0
I could be completely wrong about Shadow Weaving in that it should add another stack from a recast Mind Flay before it finishes its first channel. I've been trying to find information on it but can't find any significant proof.

**Comment by Wolffenstein** [comment]
Fixed in rev 2203.
