### ISSUE TITLE
[NPC][Dustwallow Marsh] Apprentice Garion

### ISSUE THREAD

**Issue by DeltaLoads** [Atlantiss/NetherwingBugtracker#1821]
[//]: # (Enclose links to things related to the bug using http://wowhead.com or any other TBC database.)
[//]: # (You can use screenshot ingame to visual the issue.)
[//]: # (Write your tickets according to the format:)
[//]: # ([Quest][Azuremyst Isle] Red Snapper - Very Tasty!)
[//]: # ([NPC] Magistrix Erona)
[//]: # ([Spell][Mage] Fireball)
[//]: # ([Npc][Drop] Ghostclaw Lynx)
[//]: # ([Web] Armory doesnt work)

**Description**: 
Apprentice Garion is missing his quest indicator above his head
![wowscrnshot_102318_024600](https://user-images.githubusercontent.com/43690147/47327499-cfbf4c00-d66d-11e8-8674-1130a6c26dbb.jpg)

**Current behaviour**:
Apprentice Garion is missing his quest indicator above his head
**Expected behaviour**: 
He should have gold "!" above him
**Server Revision**: 
2196

**Comment by DeltaLoads** [comment]
![wowscrnshot_102318_024906](https://user-images.githubusercontent.com/43690147/47327603-3b091e00-d66e-11e8-9e8c-d12b6e9f567a.jpg)
Him aswell

**Comment by Shanghi** [comment]
This will be the same as in https://github.com/Atlantiss/NetherwingBugtracker/issues/1068. I just edited the title there so it will be easier to see it's a global thing. They'll all be fixed at the same time.
