### ISSUE TITLE
[spell][priest] Mind soothe resist

### ISSUE THREAD

**Issue by Erodraeda** [Atlantiss/NetherwingBugtracker#1822]
[//]: # (Enclose links to things related to the bug using http://wowhead.com or any other TBC database.)
[//]: # (You can use screenshot ingame to visual the issue.)
[//]: # (Write your tickets according to the format:)
[//]: # ([Quest][Azuremyst Isle] Red Snapper - Very Tasty!)
[//]: # ([NPC] Magistrix Erona)
[//]: # ([Spell][Mage] Fireball)
[//]: # ([Npc][Drop] Ghostclaw Lynx)
[//]: # ([Web] Armory doesnt work)

**Description**: 
When a target resists mind soothe, nothing should happen. Instead of that, the target is being engaged in combat.
**Current behaviour**:
Mind Soothe resists are engaging target in combat
**Expected behaviour**: 
Nothing should happen if resisted.
**Server Revision**:

**Comment by Azalen** [comment]
https://wow.gamepedia.com/Mind_Soothe

> Beware that if the mob resists Mind Soothe you will aggro it and enter combat.

**Comment by Tenoutoften** [comment]
also https://wow.gamepedia.com/index.php?title=Mind_Soothe&oldid=211877 , an older version of the page says it should aggro on resist

**Comment by Erodraeda** [comment]
Ok, so my memory failed me lol
