### ISSUE TITLE
[NPC] Moonglade Warden falls through the world during patrol

### ISSUE THREAD

**Issue by netherwingbta** [Atlantiss/NetherwingBugtracker#1823]
[//]: # (Enclose links to things related to the bug using http://wowhead.com or any other TBC database.)
[//]: # (You can use screenshot ingame to visual the issue.)
[//]: # (Write your tickets according to the format:)
[//]: # ([Quest][Azuremyst Isle] Red Snapper - Very Tasty!)
[//]: # ([NPC] Magistrix Erona)
[//]: # ([Spell][Mage] Fireball)
[//]: # ([Npc][Drop] Ghostclaw Lynx)
[//]: # ([Web] Armory doesnt work)

**Description**: 
[Moonglade Warden](https://www.wowhead.com/npc=11822/moonglade-warden) falls through the world and then eventually floats back up.
**Current behaviour**:
He gets stuck on this pillar and then just falls down through the ground.
He also walks up the side of some of the other pillars during his very long patrol.
![warden](https://user-images.githubusercontent.com/43872263/47334629-d490f980-d687-11e8-932d-004d41ca67bd.jpg)
![warden2](https://user-images.githubusercontent.com/43872263/47334632-d8248080-d687-11e8-8c87-f1df1db6872c.jpg)

**Expected behaviour**: 
Should not walk up the side of pillars nor clip through the ground. 
**Server Revision**: 
2196

**Comment by aresbrutus** [comment]
Fixed in rev `Eris`
