### ISSUE TITLE
[NPC] Blazerunner - immune to stun

### ISSUE THREAD

**Issue by ScottieDOESknow** [Atlantiss/NetherwingBugtracker#1824]
**Description**:  Blazerunner 56 elite elemental Un'Goro Crater

**Current behaviour**: Immune to stuns.  Not sure about fear, root, etc.

**Expected behaviour**:  Should not be immune to stun, fear, or root.

https://www.wowhead.com/quest=3962/its-dangerous-to-go-alone#comments:id=7318

https://www.wowhead.com/quest=3962/its-dangerous-to-go-alone#comments:id=66987

https://www.wowhead.com/npc=9376/blazerunner#comments:id=77433

**Server Revision**: 2200

**Comment by Tenoutoften** [comment]
![5a8a7a0479ad7ce252fba3eea8cce926](https://user-images.githubusercontent.com/34839199/47340103-87b81d80-d69d-11e8-9d49-e10d5cf7cad7.png)
![611e9e929ebcf74112f447d6c5871368](https://user-images.githubusercontent.com/34839199/47340108-8a1a7780-d69d-11e8-976e-77fec1c76b7b.png)
![b37bc8b7086a450618d90ce565565a5c](https://user-images.githubusercontent.com/34839199/47340114-91418580-d69d-11e8-9315-d7a96b3ede07.png)

looks like if you are slow at killing him he should regain his aura, I have never tested that
![3314f54f4854094f04a05c50ee8c3684](https://user-images.githubusercontent.com/34839199/47340145-a5858280-d69d-11e8-9c6b-1e4d02bf38fe.png)
![e6e937cef07fa86ecef40c7d87af1905](https://user-images.githubusercontent.com/34839199/47340146-a5858280-d69d-11e8-8d8a-8d9aad35cb41.png)

**Comment by Evolvee** [comment]
I set the aura re-activation at 30 seconds.

feel free to comment if u think it should be set differently


rev ff15
