### ISSUE TITLE
Blasted Lands Boars and Basilisks spawns

### ISSUE THREAD

**Issue by BezawitNW** [Atlantiss/NetherwingBugtracker#1825]
It is currently very difficult to complete the Blasted Lands buff quests due to Basilisks being so rare. It seems like the Basilisks (Redstone Basilisk and Redstone Crystalhide) share spawn points with Boars (Ashmane Boar and Helboar). While doing these quests, the zone became flooded with Boars and had very few Basilisks. I ended up having to clear all the Boars in the zone multiple times to try to force Basilisks to spawn.

Blasted Lands buff quests I am referring to:

The Basilisk's Bite
Vulture's Vigor
A Boar's Vitality
Snickerfang Jowls
The Decisive Striker

When doing these quests, you need many more Basilisk Brains than you do Blasted Boar Lungs. Perhaps the spawn chance of Boars should be lower (Basilisk higher) to help compensate for this.

**Comment by The14me** [comment]
Shared spawn pool's.Nothing bugged.
Can be closed (tested on rev.3441)
