### ISSUE TITLE
[NPC]Noggle Ficklespragg#15190 has the RP text of [NPC]Anchorite Avuun#17127

### ISSUE THREAD

**Issue by Tenoutoften** [Atlantiss/NetherwingBugtracker#1826]
**Description**: 
[[NPC]Noggle Ficklespragg#15190](https://db.excalibur.ws/?npc=15190) has the rp text of [[NPC]Anchorite Avuun#17127](https://db.excalibur.ws/?npc=17127)

![88797a478db639a2b777da591d20a0ee](https://user-images.githubusercontent.com/34839199/47349315-ab865e00-d6b3-11e8-817c-734841d61788.png)

**Expected behaviour**: 
Not sure what he is suppose to say..

**Server Revision**: 
2196

**Comment by Evolvee** [comment]
rev ff15
