### ISSUE TITLE
Stormwind SI:7 stairs bugged

### ISSUE THREAD

**Issue by mistermeta** [Atlantiss/NetherwingBugtracker#1827]
**Description**: 
The stairs at the entrance to rogue headquarters in Stormwind is not a smooth walking path and it stutters movement or completely halts it. You literally have to jump over the stairs to get inside the building.
**Current behaviour**:
Stairs are stopping you.
**Expected behaviour**: 
Stairs shouldn't stop you.
**Server Revision**:

**Comment by Evolvee** [comment]
client side
