### ISSUE TITLE
Both [NPC][Movement]Twilight Prophet#15308 missing their 2x[NPC]Twilight Avenger#11880 guards

### ISSUE THREAD

**Issue by Tenoutoften** [Atlantiss/NetherwingBugtracker#1829]
**Description**: 
[[NPC]Twilight Prophet#15308](https://www.wowhead.com/npc=15308/twilight-prophet#comments) should have two [[NPC]Twilight Avenger#11880](https://db.excalibur.ws/?npc=11880) following her on her patrol.

http://wowwiki.wikia.com/wiki/Twilight_Prophet

![1a36b55b121e87eba8c11e1903e8b88f](https://user-images.githubusercontent.com/34839199/47355656-3cfccc80-d6c2-11e8-8b79-e4e7ebfd7dc6.png)
![2feb0d4afe3bf88d543d1dfd96272b27](https://user-images.githubusercontent.com/34839199/47355658-3cfccc80-d6c2-11e8-9fe9-a7b965092cae.png)
![8e493ee81a2c1401864b976ef8aaab9c](https://user-images.githubusercontent.com/34839199/47355659-3cfccc80-d6c2-11e8-84e5-b5a9f288f2bf.png)
![104e4c9a59c781093beedf120ed3e54d](https://user-images.githubusercontent.com/34839199/47355660-3cfccc80-d6c2-11e8-8d4e-58716281b516.png)
![413b2b1b0b32cace5392add2fa8a43b8](https://user-images.githubusercontent.com/34839199/47355661-3cfccc80-d6c2-11e8-90a0-a448bdef17d8.png)
![d014368a26f2ae84bfce90c5ce868565](https://user-images.githubusercontent.com/34839199/47355662-3d956300-d6c2-11e8-9d4d-958c69ae3728.png)

Currently patrols alone [NW video]
Keep in mind there is two x [[NPC]Twilight Prophet#15308](https://www.wowhead.com/npc=15308/twilight-prophet#comments), one in the south ID: 1 & one in the North/east ID: 2

**Expected behaviour**: 
Expected to have two  [[NPC]Twilight Avenger#11880](https://db.excalibur.ws/?npc=11880) guards.

**Server Revision**: 
2196

**Comment by aresbrutus** [comment]
Fixed in rev `Eris`
