### ISSUE TITLE
Too fast de-aggro / reset

### ISSUE THREAD

**Issue by ttghnw** [Atlantiss/NetherwingBugtracker#183]
[//]: # (Enclose links to things related to the bug using http://wowhead.com or any other TBC database.)
[//]: # (You can use screenshot ingame to visual the issue.)
[//]: # (Write your tickets according to the format:)
[//]: # ([Quest][Azuremyst Isle] Red Snapper - Very Tasty!)
[//]: # ([NPC] Magistrix Erona)
[//]: # ([Spell][Mage] Fireball)
[//]: # ([Npc][Drop] Ghostclaw Lynx)
[//]: # ([Web] Armory doesnt work)

**Description**: 
Bloodmyst Isle - Wrathscale sorceress
**Current behaviour**:
Skull level mob at the moment for my character - correct aggro distance for the level gap, but the mob de-aggros and resets with me barely running away from it, including as I was slowed by frostbolt
**Expected behaviour**: 
I'd need to run away much more before the mob would reset
**Server Revision**:

**Comment by Kidcudi123** [comment]
I feel like most mobs evade really early?

**Comment by Easyfraggy** [comment]
All mobs seem to evade too quickly atm, if anyone could provide video from retail that would be great.

My personal memory of this is that mobs would evade for 3-5 seconds before going back to their position.

**Comment by SwiftieTBC** [comment]
https://youtu.be/jIbAVivNzSs?t=54s - gives a decent idea of chase length/time if its universal

**Comment by Easyfraggy** [comment]
This issue isn't about leash range/timer Swiftie =) Nice video tho!

**Comment by SwiftieTBC** [comment]
what we trying to find evade timing?

**Comment by Easyfraggy** [comment]
retest and reopen if still a problem. Should be fixed.
