### ISSUE TITLE
[NPC][Feralas] Grimtotem Shaman

### ISSUE THREAD

**Issue by Galawer** [Atlantiss/NetherwingBugtracker#1830]
**Current behaviour**:
[Grimtotem Shaman](https://www.wowhead.com/npc=7727/grimtotem-shaman) uses Fire Nova Totem (ID 11314) with the draenei model.

**Expected behaviour**: 
The totem should be using the horde model.

**Server Revision**: 
2196

**Comment by Evolvee** [comment]
@Wolffenstein there needs to be some core implementation on deciding whether the npc is horde/alliance for totem skins

**Comment by Zarant** [comment]
Grimtotem Earthbinder in dustwallow marsh have the same issue with earthbind totem

**Comment by Cinx787** [comment]
Still an issue as of Server Revision 2647

**Comment by The14me** [comment]
Must be solved with the last Rev  3449
''[Core/Totem]:
- Creatures will now always use Horde version of totems by default''
can be closed.
