### ISSUE TITLE
[NPC]Tortued Druid#12178 use a very weak [Spell]Healing Touch

### ISSUE THREAD

**Issue by Tenoutoften** [Atlantiss/NetherwingBugtracker#1831]
**Description**: 
[[NPC]Tortued Druid#12178](https://db.excalibur.ws/?npc=12178) lvl 55-56 uses an incredibly weak [[Spell]Healing Touch](https://db.excalibur.ws/?search=healing+touch#spells) heals ~350
![55d699b075a80e607064d134b3e50266](https://user-images.githubusercontent.com/34839199/47372441-10f54180-d6ea-11e8-93fa-5a9115b40a2d.png)

Possibly tied with https://github.com/Atlantiss/NetherwingBugtracker/issues/1802

**Expected behaviour**: 
Expected to heal significantly more

**Server Revision**: 
2196

**Comment by Evolvee** [comment]
rev ff15
