### ISSUE TITLE
[NPC]Hive'Ashi Drone#13136 should probably reward regular mob xp rather than 0

### ISSUE THREAD

**Issue by Tenoutoften** [Atlantiss/NetherwingBugtracker#1832]
**Description**: 
[[NPC]Hive'Ashi Drone#13136](https://www.wowhead.com/npc=13136/hiveashi-drone#comments) spawned by [[Spell]Summon Hive'Ashi Drone#21327](https://db.excalibur.ws/?spell=21327) usually after a [[NPC]Tortured Druid#12178](https://db.excalibur.ws/?npc=12178) or [[NPC]Tortured Sentinel#12179](https://db.excalibur.ws/?npc=12179) dies should most likely reward full xp considering it is as difficult as a regular mob. Couldn't find a video though...

[wowhead comments on quest here](https://www.wowhead.com/quest=1125/the-spirits-of-southwind)

**Current behaviour**:
0 xp

**Expected behaviour**: 
Regular mob xp

**Server Revision**: 
2196

**Comment by Evolvee** [comment]
https://github.com/Atlantiss/NetherwingBugtracker/issues/1945
