### ISSUE TITLE
[Quest][Stranglethorn Vale] Up to Snuff

### ISSUE THREAD

**Issue by Kuumi** [Atlantiss/NetherwingBugtracker#1833]
[//]: # (Enclose links to things related to the bug using http://wowhead.com or any other TBC database.)
[//]: # (You can use screenshot ingame to visual the issue.)
[//]: # (Write your tickets according to the format:)
[//]: # ([Quest][Azuremyst Isle] Red Snapper - Very Tasty!)
[//]: # ([NPC] Magistrix Erona)
[//]: # ([Spell][Mage] Fireball)
[//]: # ([Npc][Drop] Ghostclaw Lynx)
[//]: # ([Web] Armory doesnt work)

**Description**: 
Drop rate of snuff feels low. WOWHEAD says 40% and thottbot states 22%. But has felt low compared to other pservers (don't know what would be correct) https://www.wowhead.com/quest=587/up-to-snuff#comments

**Current behaviour**:
Low droprate of Snuff off of all bloodsail pirates and specifically swashbucklers

**Expected behaviour**: 
possibly a higher droprate, still not completely sure.

**Server Revision**:

**Comment by aresbrutus** [comment]
Fixed in rev `Eris`
