### ISSUE TITLE
[NPC] Bloodsail Swabby or Bloodsail Sea Dog resetting midfight 

### ISSUE THREAD

**Issue by Kuumi** [Atlantiss/NetherwingBugtracker#1834]
[//]: # (Enclose links to things related to the bug using http://wowhead.com or any other TBC database.)
[//]: # (You can use screenshot ingame to visual the issue.)
[//]: # (Write your tickets according to the format:)
[//]: # ([Quest][Azuremyst Isle] Red Snapper - Very Tasty!)
[//]: # ([NPC] Magistrix Erona)
[//]: # ([Spell][Mage] Fireball)
[//]: # ([Npc][Drop] Ghostclaw Lynx)
[//]: # ([Web] Armory doesnt work)

**Description**: 
If 2 mobs are pulled at once, one resets halfway through the fight in a certain location
**Current behaviour**:
These mobs are resetting during a fight on the wooden bridge leading up to the bloodsail boats leading to [The Bloodsail Buccaneers] quest. Have no recording proof as my pc is a potato but easily reproducible. 
**Expected behaviour**: 
No mob reset while standing still and fighting.
**Server Revision**:

**Comment by The14me** [comment]
Maybe fixed on last rev.Please retest.

**Comment by Easyfraggy** [comment]
Retest after leashing fix.
