### ISSUE TITLE
Tornado effect caused by Ancient Stone Keeper causes player movement desync

### ISSUE THREAD

**Issue by Shakeandbake** [Atlantiss/NetherwingBugtracker#1837]
[//]: # (Enclose links to things related to the bug using http://wowhead.com or any other TBC database.)
[//]: # (You can use screenshot ingame to visual the issue.)
[//]: # (Write your tickets according to the format:)
[//]: # ([Quest][Azuremyst Isle] Red Snapper - Very Tasty!)
[//]: # ([NPC] Magistrix Erona)
[//]: # ([Spell][Mage] Fireball)
[//]: # ([Npc][Drop] Ghostclaw Lynx)
[//]: # ([Web] Armory doesnt work)

**Description**: 
While fighting the Ancient Stone Keeper in uldaman, players who were caught in the tornado effect (which snared them) caused their character to sometimes fly off into the distance and then slide back to their current position. 
**Current behaviour**:
My guess is that the client is placing the party member where they would have been had they moved in that direction at normal running speed before being rubberbanded back by a server update.
**Expected behaviour**: 
Party members should not be seen to rubberband around while snared from this tornado effect.
**Server Revision**:

**Comment by Easyfraggy** [comment]
If this is only in uldaman I keep it low prio - Please comment if you find same issue in other places.

**Comment by Shakeandbake** [comment]
the desync looked alot like the desync reported for this issue:
https://github.com/Atlantiss/NetherwingBugtracker/issues/1889
