### ISSUE TITLE
[Quest][Hinterlands] Venom Bottles

### ISSUE THREAD

**Issue by Galawer** [Atlantiss/NetherwingBugtracker#1838]
**Description**: 
[Quest](https://www.wowhead.com/quest=2933/venom-bottles)
[Object](https://www.wowhead.com/object=142702/venom-bottle#comments)

Currently you can only start this quest in the Zun'watha camp, but you should also be able to start it from the bottles on the table in Hiri'watha at 31.6 57.7
![image](https://user-images.githubusercontent.com/1574432/47385836-61c96200-d70b-11e8-9d4e-f6e8753ad032.png)

**Server Revision**: 
2196

**Comment by Shanghi** [comment]
This should be fixed in revision 2221. The other bottles there are just decorations on the table so only that one on the left will be usable.
