### ISSUE TITLE
[NPC] Malygen - missing cooking recipes

### ISSUE THREAD

**Issue by ScottieDOESknow** [Atlantiss/NetherwingBugtracker#1839]
**Description**: Malygen <General Goods> vendor in Felwood

http://db.excalibur.ws/?npc=2803

**Current behaviour**: missing 2 cooking recipes (required to level cooking 275+ sans fishing)

Recipe: Charred Bear Kabobs
http://db.excalibur.ws/?item=35564

Recipe: Juicy Bear Burger
http://db.excalibur.ws/?item=35566

**Expected behaviour**:  vendor should sell these recipes (added in 2.4)

https://www.wowhead.com/item=35564/recipe-charred-bear-kabobs
https://www.wowhead.com/item=35566/recipe-juicy-bear-burger

**Server Revision**:  2196

**Comment by ScottieDOESknow** [comment]
I would also like to add, there is a Horde vendor in Felwood that should sell these recipes as well.

http://db.excalibur.ws/?npc=2806

**Comment by aresbrutus** [comment]
These got added in patch 2.4.
