### ISSUE TITLE
Dead Upon Logging In

### ISSUE THREAD

**Issue by Thugli** [Atlantiss/NetherwingBugtracker#1841]
[//]: # (Enclose links to things related to the bug using http://wowhead.com or any other TBC database.)
[//]: # (You can use screenshot ingame to visual the issue.)
[//]: # (Write your tickets according to the format:)
[//]: # ([Quest][Azuremyst Isle] Red Snapper - Very Tasty!)
[//]: # ([NPC] Magistrix Erona)
[//]: # ([Spell][Mage] Fireball)
[//]: # ([Npc][Drop] Ghostclaw Lynx)
[//]: # ([Web] Armory doesnt work)

**Description**: 
Just before I logged out in Durotar, I passed lead to another party member. Upon logging in, I was dead. I logged out manually, where I waited 20 seconds, I did not alt+f4.
**Current behaviour**:
See above
**Expected behaviour**: 
I should not die
**Server Revision**: 
2196

**Comment by Easyfraggy** [comment]
Were you in combat when the logout happened?

**Comment by Thugli** [comment]
> Were you in combat when the logout happened?

I am fairly certain I was not in combat & I have not been able to reproduce this bug.
