### ISSUE TITLE
Drinking while standing

### ISSUE THREAD

**Issue by Thugli** [Atlantiss/NetherwingBugtracker#1842]
[//]: # (Enclose links to things related to the bug using http://wowhead.com or any other TBC database.)
[//]: # (You can use screenshot ingame to visual the issue.)
[//]: # (Write your tickets according to the format:)
[//]: # ([Quest][Azuremyst Isle] Red Snapper - Very Tasty!)
[//]: # ([NPC] Magistrix Erona)
[//]: # ([Spell][Mage] Fireball)
[//]: # ([Npc][Drop] Ghostclaw Lynx)
[//]: # ([Web] Armory doesnt work)

**Description**: 
While I was standing I was able to drink water. My party members confirmed they saw this as well.

**Current behaviour**:
See above.
**Expected behaviour**: 
Drinking should not be possible while standing up.
**Server Revision**: 
2196

**Comment by Tenoutoften** [comment]
Can you reproduce it and make a video?

**Comment by The14me** [comment]
i seen it too,but for some reason cant reproduce.
the Issue was then Shaman use Searing totem and the totem attack..u drink at the same time and do ''attack position''

**Comment by Easyfraggy** [comment]
Need reproduction steps.

**Comment by bloodwindz** [comment]
i eat while standing after every duel

**Comment by Thugli** [comment]
> i eat while standing after every duel

Yeah, now that you mention it, the only times I have noticed this bug are after duels.

**Comment by Easyfraggy** [comment]
Could you test if its after pvp combat in general or just duels?

**Comment by The14me** [comment]
rev.3478 not an issue anymore.
Can be closed.
