### ISSUE TITLE
Unlimited Rough Arrow

### ISSUE THREAD

**Issue by maxturtlesc2** [Atlantiss/NetherwingBugtracker#1844]
[//]: # (Enclose links to things related to the bug using http://wowhead.com or any other TBC database.)
[//]: # (You can use screenshot ingame to visual the issue.)
[//]: # (Write your tickets according to the format:)
[//]: # ([Quest][Azuremyst Isle] Red Snapper - Very Tasty!)
[//]: # ([NPC] Magistrix Erona)
[//]: # ([Spell][Mage] Fireball)
[//]: # ([Npc][Drop] Ghostclaw Lynx)
[//]: # ([Web] Armory doesnt work)

**Description**: 
Rough Arrow doesn't get consumed when used.
**Current behaviour**:

**Expected behaviour**: 
Rough Arrow should get consumed when used.
**Server Revision**:

**Comment by Easyfraggy** [comment]
Didn't we have this before and conclude it was an addon issue?

**Comment by Jezofine** [comment]
Seems to get consumed correctly on 2395.

**Comment by Tenoutoften** [comment]
I tested this https://youtu.be/3isOY7lIUNE
Steady shot does not consume ammo, probably should. Added that in https://github.com/Atlantiss/NetherwingBugtracker/issues/2708
