### ISSUE TITLE
[NPC] Deze Snowbane

### ISSUE THREAD

**Issue by netherwingbta** [Atlantiss/NetherwingBugtracker#1845]
[//]: # (Enclose links to things related to the bug using http://wowhead.com or any other TBC database.)
[//]: # (You can use screenshot ingame to visual the issue.)
[//]: # (Write your tickets according to the format:)
[//]: # ([Quest][Azuremyst Isle] Red Snapper - Very Tasty!)
[//]: # ([NPC] Magistrix Erona)
[//]: # ([Spell][Mage] Fireball)
[//]: # ([Npc][Drop] Ghostclaw Lynx)
[//]: # ([Web] Armory doesnt work)

**Current behaviour**:
[Deze Snowbane](https://www.wowhead.com/npc=15006/deze-snowbane) has incorrect text saying i'm too low level. 
Has "I want to browse your goods." option. It doesn't do anything when clicked though.
![abbattlemaster](https://user-images.githubusercontent.com/43872263/47405172-8f84ca00-d750-11e8-97fe-9cd8da0722ca.jpg)

**Expected behaviour**: 
The NPC should not have this text when the player is high enough level for AB and should not have the vendor option. 
Her being a vendor has to do with the vanilla and prewotlk scourge invasions. 

> Upon completion of the quest N [45] Note from the Front (part of the Scourge Invasion event), Deze Snowbane offered the following items:

**Server Revision**: 
2207

**Comment by Evolvee** [comment]
rev ff15
