### ISSUE TITLE
mirefin murlocs

### ISSUE THREAD

**Issue by fatherfigure2018** [Atlantiss/NetherwingBugtracker#1846]
[//]: # (Enclose links to things related to the bug using http://wowhead.com or any other TBC database.)
[//]: # (You can use screenshot ingame to visual the issue.)
[//]: # (Write your tickets according to the format:)
[//]: # ([Quest][Azuremyst Isle] Red Snapper - Very Tasty!)
[//]: # ([NPC] Magistrix Erona)
[//]: # ([Spell][Mage] Fireball)
[//]: # ([Npc][Drop] Ghostclaw Lynx)
[//]: # ([Web] Armory doesnt work)

**Description**:  mirefin murlocs movespeed is a bit to high compared to Retail tbc even with improve 3/3 blizzard the move a bit to fast

**Current behaviour**:
Moving atleast 10% more tan expected and 1 murloc is in constant evade

**Expected behaviour**: 

less 10% move speed or so in murlocs

**Server Revision**:

**Comment by The14me** [comment]
Can u please bring some proof of that.Thx

**Comment by fatherfigure2018** [comment]
Ofc you need a video about retail tbc and nw to compare? The 2 kind of murlocs and the movespeed of them?

**Comment by Easyfraggy** [comment]
Yes!

**Comment by Tereneckla** [comment]
Looks fine to me.
