### ISSUE TITLE
[Movement][NPC]Twilight Keeper Mayna#15200 should be patrolling back and forth rather than random movements

### ISSUE THREAD

**Issue by Tenoutoften** [Atlantiss/NetherwingBugtracker#1847]
**Description**: 
[[NPC]Twilight Keeper Mayna#15200](https://db.excalibur.ws/?npc=15200) should be patrolling around her camp. Currently just walks a bit around her spawn spot like a regular mob.
![b382e6d76cc50ec273b50d566d665984](https://user-images.githubusercontent.com/34839199/47423581-ac87c000-d785-11e8-9f35-01620535b30a.png)
![4d888934f8bbc2ec889adfb60d657155](https://user-images.githubusercontent.com/34839199/47424282-98dd5900-d787-11e8-97eb-3eae8b439777.png)
![c38005d4922a0ae3131c15ee91511756](https://user-images.githubusercontent.com/34839199/47423582-ad205680-d785-11e8-8585-6ed6eda4e427.png)

https://youtu.be/vkNX8kpsQLU?t=56
https://youtu.be/C5L8iN8LOUE?t=103
https://youtu.be/pV5qGlSKeUI

**Expected behaviour**: 
Expected to patrol back and forth a line around their spawn spots, rather than random movements.

**Server Revision**: 
2207

**Comment by aresbrutus** [comment]
Fixed in rev `Eris`
