### ISSUE TITLE
[Movement][NPC]Twilight Avanger#11880 ID: 36 & 37 standing close to each other in an odd spot without moving

### ISSUE THREAD

**Issue by Tenoutoften** [Atlantiss/NetherwingBugtracker#1848]
**Description**: 
![b2271243100a646613b54e2b5bd8a636](https://user-images.githubusercontent.com/34839199/47423897-90385300-d786-11e8-8595-f906ac8e745a.png)

Stands completely still at this spot

**Expected behaviour**: 
Patrol or move around a bit.

**Server Revision**: 
2207

**Comment by aresbrutus** [comment]
Might have been related to random move not working. Seems to be fine for me.
