### ISSUE TITLE
[spell][warlock] soul link need a recast after new demon is summoned

### ISSUE THREAD

**Issue by duzyizly** [Atlantiss/NetherwingBugtracker#1849]
[//]: # (Enclose links to things related to the bug using http://wowhead.com or any other TBC database.)
[//]: # (You can use screenshot ingame to visual the issue.)
[//]: # (Write your tickets according to the format:)
[//]: # ([Quest][Azuremyst Isle] Red Snapper - Very Tasty!)
[//]: # ([NPC] Magistrix Erona)
[//]: # ([Spell][Mage] Fireball)
[//]: # ([Npc][Drop] Ghostclaw Lynx)
[//]: # ([Web] Armory doesnt work)

**Description**: 
Spell/Talent Soul link https://db.excalibur.ws/?spell=19028 doesn't work as intended with "new" demon.

**Current behaviour**:
Once Your demon pet is dead (or you don't have any) and You summon new one there is no soul link attached to you and the pet.

**Expected behaviour**: 
soul link should cast itself once demon is summoned like here https://www.youtube.com/watch?v=aDGtKZ-xRuo&t=04m05s (You don't need to cast soul link each time You summon a new demon).

**Server Revision**: 
still no idea how to check it.

**Comment by ScottieDOESknow** [comment]
Soul Link is a spell on GCD thus you still need to cast it each time a new demon is summoned. The person in video was most likely using a macro with Fel Domination, Summon X Demon, Soul Link which would explain the quick re-application.

**Comment by The14me** [comment]
can u retest please.

**Comment by duzyizly** [comment]
> Soul Link is a spell on GCD thus you still need to cast it each time a new demon is summoned. The person in video was most likely using a macro with Fel Domination, Summon X Demon, Soul Link which would explain the quick re-application.

hmmm yea this might be true actually since the text of abiility says "stay as long as pet is active". Need more researach.

**Comment by duzyizly** [comment]
This is actually right, you can see at this movie - the guy who's playing a warlock did not even casr soul link (he's clicking with mouseover 1. fel domination, 2. felhunter). If You need more prove I can try to find more movies like this.

Also I did retest - still not working correctly.

**Comment by Easyfraggy** [comment]
This video only proves that it should stay active if you summon a new demon while you already have soul link active with your current.

**Comment by duzyizly** [comment]
> Doesn't prove that soul link should be activated automaticly if you don't have a demon summoned.

Yea but i never said that ; ) or maybe I was misunderstood.

**Comment by duzyizly** [comment]
Same here https://www.youtube.com/watch?v=2CMLa2enhG4&t=31s new demon get buffed by soul link right after it's summoned.

**Comment by ScottieDOESknow** [comment]
>new demon get buffed by soul link right after it's summoned.

That's not what happened at all. They click summon felhunter, then click soul link... can even see tooltips.

**Comment by duzyizly** [comment]
Hmm Yea i see that now my bad.
I'm so confused about that because i rememeber back from retail it used to work like that (at least somewhere in early TBC - not sure about 2.2+ because i had to quit wow back then). So maybe it was a fixed bug or something but can't find any information in patch changes.

**Comment by Tereneckla** [comment]
Working as intended and retail.
