### ISSUE TITLE
[[NPC]Twilight Geolord#11881 should attempt to run away in fear!

### ISSUE THREAD

**Issue by Tenoutoften** [Atlantiss/NetherwingBugtracker#1850]
**Description**: 
[[NPC]Twilight Geolord#11881](https://www.wowhead.com/npc=11881/twilight-geolord#comments) should attempt to run away in fear. Emote can be seen here, Wrath exp: https://youtu.be/pV5qGlSKeUI?t=65

**Current behaviour**:
Never runs away in fear.

**Expected behaviour**: 
should attempt to run away in fear!

**Server Revision**: 
2207

**Comment by Evolvee** [comment]
rev ff15
