### ISSUE TITLE
[Spell][NPC]Twilight Prophet#15308 wrong abilities & wrong damage: Frostbolt & Fire Blast => Blast Wave & Psychic Scream

### ISSUE THREAD

**Issue by Tenoutoften** [Atlantiss/NetherwingBugtracker#1851]
**Description**: 
[[NPC]Twilight Prophet#15308](https://www.wowhead.com/npc=15308/twilight-prophet#comments) 
- Video from vanilla [here](https://youtu.be/KevuaGZMdjY?t=12)

Her Frostbolt in particular is incredibly weak, dealing the damage of a frostbolt owned by a lvl 40 mage
![a677e9c8754761b40c8abf6c19649555](https://user-images.githubusercontent.com/34839199/47428015-49505a80-d792-11e8-807b-d256d7fa1005.png)
![9519b29c5b933e602e6c5a4248e853ab](https://user-images.githubusercontent.com/34839199/47428016-49505a80-d792-11e8-8ee4-29706605e4a8.png)

Chain Lightning is also quite weak, hitting for ~500:
![41279b6200b8efe9a666b49cc5cd5115](https://user-images.githubusercontent.com/34839199/47428152-af3ce200-d792-11e8-89c9-393a84104c57.png)
Video showing [1200 hit here](https://youtu.be/KevuaGZMdjY?t=60)

Frost Nova deals about 150 dmg:
![97c4b1307e1ffdb5023856622bbe6f05](https://user-images.githubusercontent.com/34839199/47428308-2a05fd00-d793-11e8-88e0-e048a8e7e353.png)
Should deal about [450 damage](https://youtu.be/KevuaGZMdjY?t=21)

----------

She uses the same spellIDs on excalibur database as on wowhead:
https://www.wowhead.com/npc=15308/twilight-prophet#abilities
https://db.excalibur.ws/?npc=15308#controlled-abilities

------------

**Current behaviour**:
Frostbolt
Fire Blast
Frost Nova
Chain Lightning

**Expected behaviour**: 
[[Spell]Fira Nova#17366](https://db.excalibur.ws/?spell=17366) -  ([~1000 damage](https://youtu.be/KevuaGZMdjY))
[[Spell]Psychic Scream#22884](https://db.excalibur.ws/?spell=22884) -
[[Spell]Frost Nova#15531](https://db.excalibur.ws/?spell=15531) - ([~450 damage](https://youtu.be/KevuaGZMdjY?t=21))
[[Spell]Chain Lightning#15305](https://db.excalibur.ws/?spell=15305) - ([~1200 damage](https://youtu.be/KevuaGZMdjY?t=60))

**Server Revision**: 
2207

**Comment by Evolvee** [comment]
ff15
