### ISSUE TITLE
[Spell][Shaman] Ghost Wolf in Booty Bay

### ISSUE THREAD

**Issue by Galawer** [Atlantiss/NetherwingBugtracker#1852]
**Current behaviour**:
Travel Form was fixed to not be usable in Booty Bay, but you can still use Ghost Wolf.

**Expected behaviour**: 
Ghost Wolf shouldn't be usable in Booty Bay.

**Server Revision**: 
2207

**Comment by Wolffenstein** [comment]
Fixed in rev 2209.
