### ISSUE TITLE
[Spell] [Druid] Nature's Grace procs

### ISSUE THREAD

**Issue by Onsty** [Atlantiss/NetherwingBugtracker#1853]
[//]: # (Enclose links to things related to the bug using http://wowhead.com or any other TBC database.)
[//]: # (You can use screenshot ingame to visual the issue.)
[//]: # (Write your tickets according to the format:)
[//]: # ([Quest][Azuremyst Isle] Red Snapper - Very Tasty!)
[//]: # ([NPC] Magistrix Erona)
[//]: # ([Spell][Mage] Fireball)
[//]: # ([Npc][Drop] Ghostclaw Lynx)
[//]: # ([Web] Armory doesnt work)

**Description**: 
I reported an issue with Nature's Grace a few days ago,  it's been fixed yesterday. But there is a new problem.

**Current behaviour**:
Nature's Grace now proc on each casts
https://gfycat.com/spanishapprehensiveanophelesmosquito

**Expected behaviour**: 
Should proc only on crit

And, still, now it proc on cast, but delayed, so I'll start casting a new spell (without buff) before it proc on previous crit.
Video clearly shows that it proc instantly after the cast with no delay, and buff applies to the next wrath.
~ 0:36, 3:44 - https://www.youtube.com/watch?v=d1XzHH4yORw
**Server Revision**:

**Comment by Wolffenstein** [comment]
Fixed in rev 2209.
