### ISSUE TITLE
[Pathfinding][The Hinterlands]Shadra'Alor pyramids

### ISSUE THREAD

**Issue by DeltaLoads** [Atlantiss/NetherwingBugtracker#1855]
[//]: # (Enclose links to things related to the bug using http://wowhead.com or any other TBC database.)
[//]: # (You can use screenshot ingame to visual the issue.)
[//]: # (Write your tickets according to the format:)
[//]: # ([Quest][Azuremyst Isle] Red Snapper - Very Tasty!)
[//]: # ([NPC] Magistrix Erona)
[//]: # ([Spell][Mage] Fireball)
[//]: # ([Npc][Drop] Ghostclaw Lynx)
[//]: # ([Web] Armory doesnt work)

**Description**: 
Pathfinding problems for npcs trying to get up the stairs, happens on all of them
https://streamable.com/nz449
**Current behaviour**:
npcs cant get up the stairs of a pyramid
**Expected behaviour**: 
npcs should be able to get up the stairs
**Server Revision**: 
2207

**Comment by Tenoutoften** [comment]
This also happens with the stairs at Jintha'Alor. I just forgot to report about it...

**Comment by Tereneckla** [comment]
Fixed
