### ISSUE TITLE
[Quest][Feralas] Dark Heart

### ISSUE THREAD

**Issue by Galawer** [Atlantiss/NetherwingBugtracker#1856]
**Description**: 
You need to kill Edana Hatetalon for Edana's Dark Heart, to summon her you use [Horn of Hatetalon](https://www.wowhead.com/item=9530/horn-of-hatetalon) which drops from the following mobs:
[Northspring Harpy](https://www.wowhead.com/npc=5362/northspring-harpy)
[Northspring Roguefeather](https://www.wowhead.com/npc=5363/northspring-roguefeather)
[Northspring Slayer](https://www.wowhead.com/npc=5364/northspring-slayer)
[Northspring Windcaller](https://www.wowhead.com/npc=5366/northspring-windcaller)

**Current behaviour**:
The drop rate on [Horn of Hatetalon](https://www.wowhead.com/item=9530/horn-of-hatetalon) is too low.

**Expected behaviour**: 
According to [Wowhead comments](https://www.wowhead.com/item=9530/horn-of-hatetalon#comments), since 2.3 the drop rate is supposed to be 100%.

**Server Revision**: 
2207

**Comment by aresbrutus** [comment]
Fixed in rev `Eris`
