### ISSUE TITLE
[Spell][Priest] Power Word: Shield reapplication

### ISSUE THREAD

**Issue by Erodraeda** [Atlantiss/NetherwingBugtracker#1857]
[//]: # (Enclose links to things related to the bug using http://wowhead.com or any other TBC database.)
[//]: # (You can use screenshot ingame to visual the issue.)
[//]: # (Write your tickets according to the format:)
[//]: # ([Quest][Azuremyst Isle] Red Snapper - Very Tasty!)
[//]: # ([NPC] Magistrix Erona)
[//]: # ([Spell][Mage] Fireball)
[//]: # ([Npc][Drop] Ghostclaw Lynx)
[//]: # ([Web] Armory doesnt work)

**Description**: 
Whenever you apply Power Word: Shield to someone, it leaves the buff (30s duration) and Weakened Soul debuff (15s duration). After Weakened Soul expires, you should be able to reapply PW:S, but an error message "A more powerful spell is already active" is showing, not allowing you to reapply it.
EDIT: After testing, the error only occur if the shield is not damaged. Basically, it's considering same value spells superior for reapplications.
**Current behaviour**:
Reapplication of PW:S is being negated
**Expected behaviour**: 
You should be able to reapply PW:S after Weakened Soul expires, not having to wait for PW:S to expire as well.
**Server Revision**: 2207

**Comment by Jezofine** [comment]
Can reapply if shield is not full, i.e. taken some damage.

**Comment by Wolffenstein** [comment]
It can only happen if the current shield has more absorb than the new one would have. If they're equal, it will reapply the new one as it has longer duration.

**Comment by Erodraeda** [comment]
The issue is still happening, as you can see here https://imgur.com/a/r5K0RPR

**Comment by aresbrutus** [comment]
Re-opening as requested from OP.

**Comment by Easyfraggy** [comment]
What wolf described is true.

Same spellpower apply new one due to longer duration.
More spellpower apply new one due to more powerful shield.
Less spellpower blocked by "more powerful spell". 

Somehow same spellpower is blocked atm.

**Comment by Wolffenstein** [comment]
Fixed in rev 2399.
