### ISSUE TITLE
[NPC] Hive'Regal Slavemaker#11733 doesn't seem to use mind controlling spell.

### ISSUE THREAD

**Issue by Jezofine** [Atlantiss/NetherwingBugtracker#1858]
**Description**: 
[Hive'Regal Slavemaker](https://www.wowhead.com/npc=11733/hiveregal-slavemaker#comments)
2008/03/25 (Patch 2.4.0)
> These guys cast a mind control spell, making you loose control and cast random spells for a few seconds. 

**Current behaviour**:
Didn't use [Poison Mind](https://www.wowhead.com/spell=19469/poison-mind), although I waited for about 15 mins in total.

**Expected behaviour**:
Should use [Poison Mind](https://www.wowhead.com/spell=19469/poison-mind)

**Server Revision**: 2207

**Comment by Tenoutoften** [comment]
I think some NPC don't use mind control unless you are together with someone / a class with a pet. I could be wrong though. If you are alone wouldn't the combat just end since the mob is no longer fighting vs anyone?

**Comment by Evolvee** [comment]
it wont use MC if u are alone
