### ISSUE TITLE
[Core] Companion Movement At Water

### ISSUE THREAD

**Issue by ghost** [Atlantiss/NetherwingBugtracker#1859]
**Description**: Dunno if hunter pets have the same issue.

**Current behaviour**: While swimming at the surface or under water your companion will constantly jump up and down. Tested with [Cat Carrier (Black Tabby)] at STV waters.

**Expected behaviour**: Companions should have a smoother movement at water.

**Server Revision**: 2207

**Comment by Evolvee** [comment]
need gps location where this happens as this doesnt happen in nagrand waters

**Comment by Retinus** [comment]
1) First test outside Grom'gol Base Camp.
Started at
![image](https://user-images.githubusercontent.com/3526114/47614373-a9ebda00-daa7-11e8-8825-ef1f1a28133c.png)
and went straight to Vile Reef area
![image](https://user-images.githubusercontent.com/3526114/47614353-61342100-daa7-11e8-9b5d-b84107ef0437.png)
2) Second test at the waters of Booty Bay
Just swim from the boat area until the ramp where you get inside the town on foot
3) Third test at Wild Shore area
Started at
![image](https://user-images.githubusercontent.com/3526114/47614499-61352080-daa9-11e8-9cda-7aed96680a3e.png)
and went strait to the bloodsail boats
![image](https://user-images.githubusercontent.com/3526114/47614514-a6f1e900-daa9-11e8-96d7-f96a79ac02c1.png)

Companion is jumping up and down or walking at the sea floor

**Comment by Evolvee** [comment]
most likely mmap/liquid problem since it doesnt happen in other places (something similar)

**Comment by Wolffenstein** [comment]
Fixed in rev 3398.
