### ISSUE TITLE
Curse of Recklessness - cannot move

### ISSUE THREAD

**Issue by zapsuu** [Atlantiss/NetherwingBugtracker#1861]
Warlock spell - Curse of Recklessness:
Curses the target with recklessness, increasing melee attack power by 45 but reducing armor by 290 for 2 min. >>>Cursed enemies will not flee and will ignore Fear and Horror effects.<<< Only one Curse per Warlock can be active on any one target.

The ignoring fear is correct. When we fear someone with this curse fear debuff exist on the target, but it don't work.
But if the fear will disappear and the curse still pop, the enemy player cannot move or turn on any side. He can use skills/spells/change forms (druid), but he cannot move. The skill buttons are grey, but they works. 
If the curse down before fear everything is okay.
To unbug the player we have to fear him again. Another CC don't works to repair this bug.

This bug exist only for the players. Mobs and pets works okay.

![wowscrnshot_102418_192648](https://user-images.githubusercontent.com/43937876/47453859-0318ec80-d7ce-11e8-9084-87fa91859fea.jpg)
![wowscrnshot_102418_192651](https://user-images.githubusercontent.com/43937876/47453858-0318ec80-d7ce-11e8-9e62-1305bd28d624.jpg)

**Comment by Easyfraggy** [comment]
Is this confirmed?

**Comment by Brasso** [comment]
This is still bugged. You can't move or use hearthstone after fear end. The issue still persists even after recklessness end.

**Comment by Wolffenstein** [comment]
Fixed in rev 2470.
