### ISSUE TITLE
Pet make combat bug for enemy players

### ISSUE THREAD

**Issue by zapsuu** [Atlantiss/NetherwingBugtracker#1862]
While testing with my friendly warlock I saw that I had a combat bug while duel.
The problem is from the pet, after recast pet, combat bug faded.

The same problem is with hunter pets. Hunter has to relog or dismiss pet.

Pet hasn't to attack us, he can just buff warlock (stamina buff from Imp) or hunter (Spirit Bond) to stuck us in combat bug. There has to be any way between us and enemy's pet and we will stay in CB all time.

![wowscrnshot_102418_193248](https://user-images.githubusercontent.com/43937876/47454683-162cbc00-d7d0-11e8-9549-93c097f97eda.jpg)
![wowscrnshot_102418_193313](https://user-images.githubusercontent.com/43937876/47454684-162cbc00-d7d0-11e8-86a3-49e5f8705e78.jpg)

**Comment by zapsuu** [comment]
I think this is the same problem.

https://github.com/Atlantiss/NetherwingBugtracker/issues/1843

**Comment by Jezofine** [comment]
Maybe connected to #2489?

**Comment by Tenoutoften** [comment]
Is it resolved?
[2349][Core] Threat Fixes - 2018 / 11 / 22

[Core/Threat]:
- Fixed a combat-bug issue caused by certain AoE spells, making the players stuck in combat with their pets

**Comment by Manaci** [comment]
Fixed
