### ISSUE TITLE
Flying player in CC

### ISSUE THREAD

**Issue by zapsuu** [Atlantiss/NetherwingBugtracker#1863]
The problem is with Sap, Secudution (Succubus), Gouge, Stun, Repetance, Freezing Trap.

On one of this CC, the enemy player if he jumped on the CC, he will stay in the air. I didn't notice this bug on Blind/Fear.

![wowscrnshot_102418_193026](https://user-images.githubusercontent.com/43937876/47455042-1d07fe80-d7d1-11e8-9dc4-681c05d13750.jpg)
![wowscrnshot_102418_195046](https://user-images.githubusercontent.com/43937876/47455049-21341c00-d7d1-11e8-85d9-d06cc6e97474.jpg)
![wowscrnshot_102418_195122](https://user-images.githubusercontent.com/43937876/47455057-285b2a00-d7d1-11e8-80d2-3ccd5b688510.jpg)
![wowscrnshot_102418_195237](https://user-images.githubusercontent.com/43937876/47455061-2d1fde00-d7d1-11e8-9b84-f892b0f8b859.jpg)
![wowscrnshot_102418_200805](https://user-images.githubusercontent.com/43937876/47455066-31e49200-d7d1-11e8-8ced-18e3c38d3c3c.jpg)

**Comment by Wolffenstein** [comment]
Fixed in rev 2214.
