### ISSUE TITLE
Warlock pet buffs disappears while duel

### ISSUE THREAD

**Issue by zapsuu** [Atlantiss/NetherwingBugtracker#1864]
Every buff of warlock pets disappears after we start a duel. For example Blood Pact (stamina buff from Imp) or Master Demonologist talent.

![wowscrnshot_102418_211623](https://user-images.githubusercontent.com/43937876/47455624-9c4a0200-d7d2-11e8-955b-9380376a546a.jpg)
![wowscrnshot_102418_211814](https://user-images.githubusercontent.com/43937876/47455626-9c4a0200-d7d2-11e8-811e-f22ef21f131f.jpg)

**Comment by Wolffenstein** [comment]
Fixed in rev 2213.
