### ISSUE TITLE
[Quest][Zul'Farrak]Nekrum's Medallion

### ISSUE THREAD

**Issue by DeltaLoads** [Atlantiss/NetherwingBugtracker#1865]
[//]: # (Enclose links to things related to the bug using http://wowhead.com or any other TBC database.)
[//]: # (You can use screenshot ingame to visual the issue.)
[//]: # (Write your tickets according to the format:)
[//]: # ([Quest][Azuremyst Isle] Red Snapper - Very Tasty!)
[//]: # ([NPC] Magistrix Erona)
[//]: # ([Spell][Mage] Fireball)
[//]: # ([Npc][Drop] Ghostclaw Lynx)
[//]: # ([Web] Armory doesnt work)

**Description**: 
Unable to loot Nekrum Gutchewer even though i have a quest and i did tag him during pyramid event. Quest did work 1 week ago perfectly.
![wowscrnshot_102418_215827](https://user-images.githubusercontent.com/43690147/47459535-abce4880-d7dc-11e8-8d77-90f108e26293.jpg)

**Current behaviour**:
Unable to loot Nekrum Gutchewer
**Expected behaviour**: 
Should be able to loot Nekrum Gutchewer
**Server Revision**: 
2207

**Comment by aresbrutus** [comment]
This issue can arise due to NPC's doing majority of the damage to these trolls, thus the player not getting the actual tag.

**Comment by Mikik3jr** [comment]
The 5 NPCs that fight there dealt the majority of the damage to it, so it prevented you to get the loot. When I was there I could get the medallion.

**Comment by penialito** [comment]
> 
> 
> This issue can arise due to NPC's doing majority of the damage to these trolls, thus the player not getting the actual tag.

that is kinda retarded, how is a healer supposed to do damage?
