### ISSUE TITLE
[SPELL][NPC] Touch of Weakness should also be able to be trained by these 2 trainers.

### ISSUE THREAD

**Issue by aresbrutus** [Atlantiss/NetherwingBugtracker#1866]
http://db.hellfire-tbc.com/?npc=6018
http://db.hellfire-tbc.com/?npc=3706

Both these priest trainers should teach all ranks of Touch of Weakness.

https://web.archive.org/web/20071016182048/http://wowhead.com:80/?spell=2652#taught-by-npc
https://web.archive.org/web/20071029213527/http://www.wowhead.com:80/?npc=6018#teaches-ability:200+1+2
https://web.archive.org/web/20071029213457/http://www.wowhead.com:80/?npc=3706#teaches-ability:200+1+2
http://web.archive.org/web/20071029221838/http://thottbot.com/s2652

Before some patch these npcs also gave out the quest that would reward the player this spell. After the quest got removed they just added it to the trainer.

http://db.hellfire-tbc.com/?npc=6018 seems to be missing rank 1

http://db.hellfire-tbc.com/?npc=3706 seems to be missing all ranks of touch of weakness.

**Comment by Evolvee** [comment]
rev ff15
