### ISSUE TITLE
[NPC] Moonrage Sentry

### ISSUE THREAD

**Issue by netherwingbta** [Atlantiss/NetherwingBugtracker#1867]
[//]: # (Enclose links to things related to the bug using http://wowhead.com or any other TBC database.)
[//]: # (You can use screenshot ingame to visual the issue.)
[//]: # (Write your tickets according to the format:)
[//]: # ([Quest][Azuremyst Isle] Red Snapper - Very Tasty!)
[//]: # ([NPC] Magistrix Erona)
[//]: # ([Spell][Mage] Fireball)
[//]: # ([Npc][Drop] Ghostclaw Lynx)
[//]: # ([Web] Armory doesnt work)

**Description**: 

**Current behaviour**:
[Moonrage Sentry](https://www.wowhead.com/npc=1893/moonrage-sentry) is currently wielding a weapon and shield.
It has the Moonrage Sentry abilities as well as the [Pyrewood Sentry](https://www.wowhead.com/npc=1894/pyrewood-sentry) abilities.
![moonrage](https://user-images.githubusercontent.com/43872263/47461105-509e5500-d7e0-11e8-9763-b80862e4243e.jpg)

**Expected behaviour**: 
[Should not wield weapon and shield when transformed into a worgen](https://www.wowhead.com/npc=1893/moonrage-sentry#screenshots) and should not have human form abilities. 
**Server Revision**: 
2207

**Comment by Evolvee** [comment]
rev ff15

**Comment by Evolvee** [comment]
nope, needs @Wolffenstein to implement core support

**Comment by Tenoutoften** [comment]
![](https://wow.zamimg.com/uploads/screenshots/normal/41722-moonrage-sentry.jpg) from wowhead 2007

**Comment by Evolvee** [comment]
https://github.com/Atlantiss/NetherwingBugtracker/issues/3640
