### ISSUE TITLE
[NPC] Moonrage Watcher

### ISSUE THREAD

**Issue by netherwingbta** [Atlantiss/NetherwingBugtracker#1868]
[//]: # (Enclose links to things related to the bug using http://wowhead.com or any other TBC database.)
[//]: # (You can use screenshot ingame to visual the issue.)
[//]: # (Write your tickets according to the format:)
[//]: # ([Quest][Azuremyst Isle] Red Snapper - Very Tasty!)
[//]: # ([NPC] Magistrix Erona)
[//]: # ([Spell][Mage] Fireball)
[//]: # ([Npc][Drop] Ghostclaw Lynx)
[//]: # ([Web] Armory doesnt work)

**Description**: 

**Current behaviour**:
[Moonrage Watcher](https://www.wowhead.com/npc=1892/moonrage-watcher) is wielding a sword and shield and has the abilities of [Pyrewood Watcher](https://www.wowhead.com/npc=1891/pyrewood-watcher).
**Expected behaviour**: 
[Should not wield weapon](https://www.flickr.com/photos/16449786@N08/4939503600/in/photostream/) and should not have shoot ability.
![unknown](https://user-images.githubusercontent.com/43872263/47463648-197f7200-d7e7-11e8-8dd4-51cae869e522.png)

**Server Revision**: 
2207

**Comment by Evolvee** [comment]
rev ff15

**Comment by Evolvee** [comment]
rev ff15

**Comment by Evolvee** [comment]
nope, needs @Wolffenstein to implement core support

**Comment by Evolvee** [comment]
https://github.com/Atlantiss/NetherwingBugtracker/issues/3640
