### ISSUE TITLE
[NPC] Moonrage Elder

### ISSUE THREAD

**Issue by netherwingbta** [Atlantiss/NetherwingBugtracker#1869]
[//]: # (Enclose links to things related to the bug using http://wowhead.com or any other TBC database.)
[//]: # (You can use screenshot ingame to visual the issue.)
[//]: # (Write your tickets according to the format:)
[//]: # ([Quest][Azuremyst Isle] Red Snapper - Very Tasty!)
[//]: # ([NPC] Magistrix Erona)
[//]: # ([Spell][Mage] Fireball)
[//]: # ([Npc][Drop] Ghostclaw Lynx)
[//]: # ([Web] Armory doesnt work)

**Description**: 

**Current behaviour**:
[Moonrage Elder](https://www.wowhead.com/npc=1896/moonrage-elder) currently has the abilities of both worgen form and [Pyrewood Elder](https://www.wowhead.com/npc=1895/pyrewood-elder).
**Expected behaviour**: 
Should only be able to cast Shadow word: Pain
![unknown](https://user-images.githubusercontent.com/43872263/47463791-8e52ac00-d7e7-11e8-95ef-c2b1e0cff325.png)

**Server Revision**: 
2207

**Comment by Evolvee** [comment]
rev ff15

**Comment by Evolvee** [comment]
nope, needs @Wolffenstein to implement core support

**Comment by Evolvee** [comment]
https://github.com/Atlantiss/NetherwingBugtracker/issues/3640
