### ISSUE TITLE
Ore nodes not spawning

### ISSUE THREAD

**Issue by manslaughter** [Atlantiss/NetherwingBugtracker#187]
**Description**: Haven't seen a single copper ore / tin ore node in all of durotar or half of the barrens.  Maybe I'm just unlucky?

**Current behaviour**: "

**Expected behaviour**: 

**Server Revision**: 2028 patch 203

**Comment by Bleachlol** [comment]
Neither with herbs in Mulgore or Barrens.

**Comment by kelsul** [comment]
herbs/ore are disabled atm afaik

**Comment by The14me** [comment]
herbs/ores's are disabled right now.

**Comment by Evolvee** [comment]
herbs/vein are fully despawned right now, they will be spawned when their system is done
