### ISSUE TITLE
[NPC] Moonrage Tailor

### ISSUE THREAD

**Issue by netherwingbta** [Atlantiss/NetherwingBugtracker#1870]
[//]: # (Enclose links to things related to the bug using http://wowhead.com or any other TBC database.)
[//]: # (You can use screenshot ingame to visual the issue.)
[//]: # (Write your tickets according to the format:)
[//]: # ([Quest][Azuremyst Isle] Red Snapper - Very Tasty!)
[//]: # ([NPC] Magistrix Erona)
[//]: # ([Spell][Mage] Fireball)
[//]: # ([Npc][Drop] Ghostclaw Lynx)
[//]: # ([Web] Armory doesnt work)

**Description**: 

**Current behaviour**:
[Moonrage Tailor](https://www.wowhead.com/npc=3531/moonrage-tailor) has abilities of both worgen form and [Pyrewood Tailor](https://www.wowhead.com/npc=3530/pyrewood-tailor).
**Expected behaviour**: 
Moonrage Tailor should only be able to cast Expose Weakness.

Haven't checked if the human forms all have the abilities of the worgens btw. 
**Server Revision**: 
2207

**Comment by Evolvee** [comment]
rev ff15

**Comment by Evolvee** [comment]
nope, needs @Wolffenstein to implement core support

**Comment by Evolvee** [comment]
https://github.com/Atlantiss/NetherwingBugtracker/issues/3640
