### ISSUE TITLE
[Quest][Feralas]Wandering Shay

### ISSUE THREAD

**Issue by DeltaLoads** [Atlantiss/NetherwingBugtracker#1872]
[//]: # (Enclose links to things related to the bug using http://wowhead.com or any other TBC database.)
[//]: # (You can use screenshot ingame to visual the issue.)
[//]: # (Write your tickets according to the format:)
[//]: # ([Quest][Azuremyst Isle] Red Snapper - Very Tasty!)
[//]: # ([NPC] Magistrix Erona)
[//]: # ([Spell][Mage] Fireball)
[//]: # ([Npc][Drop] Ghostclaw Lynx)
[//]: # ([Web] Armory doesnt work)

**Description**: 
Shay stops following player after she randomly goes to pick a flower, using quest item has no effect (evade)
https://streamable.com/axout
**Current behaviour**:
Using quest item has no effect
**Expected behaviour**: 
Using quest item should make Shay follow player
**Server Revision**: 
2207

**Comment by Azalen** [comment]
Duplicate #1499

**Comment by The14me** [comment]
Duplicate ##1499
