### ISSUE TITLE
[NPC][Un'Goro Crater]Elder Diemetradon

### ISSUE THREAD

**Issue by DeltaLoads** [Atlantiss/NetherwingBugtracker#1873]
[//]: # (Enclose links to things related to the bug using http://wowhead.com or any other TBC database.)
[//]: # (You can use screenshot ingame to visual the issue.)
[//]: # (Write your tickets according to the format:)
[//]: # ([Quest][Azuremyst Isle] Red Snapper - Very Tasty!)
[//]: # ([NPC] Magistrix Erona)
[//]: # ([Spell][Mage] Fireball)
[//]: # ([Npc][Drop] Ghostclaw Lynx)
[//]: # ([Web] Armory doesnt work)

**Description**: 
This guy runs up to you and then just bugs out
![wowscrnshot_102518_020715](https://user-images.githubusercontent.com/43690147/47468310-e6df7480-d7fa-11e8-9519-0872ca11a40a.jpg)

**Current behaviour**:
Just gets to player and then cannot be attacked
**Expected behaviour**: 
Should attack player once he reaches him
**Server Revision**: 
2207

**Comment by DeltaLoads** [comment]
https://streamable.com/z3670
it would appear that he also likes to follow players since he is following me for the past 10 min

**Comment by The14me** [comment]
please do **.npc info**  on the mob and post Entry and ID.

**Comment by DeltaLoads** [comment]
its in screenshot entry:9168 id:35

**Comment by Evolvee** [comment]
cant reproduce it

**Comment by DeltaLoads** [comment]
it appears to be leashing problem. mob stopped at spot once i got out of combat, when i went back this happened
https://streamable.com/aqhi9

**Comment by Easyfraggy** [comment]
What rev is that video from DeltaLoads?

**Comment by DeltaLoads** [comment]
2214

**Comment by Easyfraggy** [comment]
Can you make a video on how to recreate this?

**Comment by DeltaLoads** [comment]
https://streamable.com/anp2c
best video i can get, its random as hell
note: i think totem doesnt have anything to do with it, previous video happened without using any totem, then again i could be wrong

**Comment by Tereneckla** [comment]
Fixed
