### ISSUE TITLE
[Core][Spell][Shaman] Stormstrike+Windfury delay

### ISSUE THREAD

**Issue by Galawer** [Atlantiss/NetherwingBugtracker#1875]
**Description**: 
Related to https://github.com/Atlantiss/NetherwingBugtracker/issues/1853 and https://github.com/Atlantiss/NetherwingBugtracker/issues/1797

**Current behaviour**:
After rev 2209 Windfury procs instantly when triggered by a white hit, but there's still a delay if procced by Stormstrike.
[Video](https://streamable.com/xbcgf)
You can see in the clip that it takes 0.6s for Windfury to proc after Stormstrike, whereas with white hits it happens on the same frame.

**Expected behaviour**: 
Windfury should proc instantly when triggered by Stormstrike, like it does with white hits.

**Server Revision**: 
2214

**Comment by Galawer** [comment]
I've looked into this and found a really good video with EavesDrop shown, so you can track the combat log: https://www.youtube.com/watch?v=YhD4yVauDhA
Going frame by frame here's what I've found:
```
24.760 hit
25.280 wf

29.480 hit
30.480 wf

33.240 hit
33.560 wf

38.079 hit
39.200 wf

41.359 crit
42.039 leader of the pack proc
42.399 wf

44.840 ss
45.600 wf

49.520 hit
50.400 wf

55.320 hit
56.560 wf

01.400 hit
02.080 wf

05.320 ss
05.680 wf

08.719 hit
09.680 wf
```
And so on. You can see that Windfury gets delayed until the next batch, sometimes even 2 batches after the hit, both when triggered by white hits and Stormstrike.

So in fact the issue is the other way around. Stormstrike is working correctly, but instant Windfury from white hits after Rev 2209 is wrong.

**Comment by ircfelix** [comment]
Research done.

**Comment by Tereneckla** [comment]
Is instant, because there is no delay
