### ISSUE TITLE
[Silithus Map Event] The Silithyst Must Flow

### ISSUE THREAD

**Issue by Azalen** [Atlantiss/NetherwingBugtracker#1877]
**Description**: 
http://wowwiki.wikia.com/wiki/The_Silithyst_Must_Flow?oldid=2242456
http://classicdb.ch/?object=181598 (Geysers)
http://classicdb.ch/?object=181597 (Mounds)

**Current behaviour**:
Not possible to receive the Silithyst Buff (spell=29519) from Silithyst Geyser (object=181598) and probably not from Silithyst Mound (object=181597).

**Expected behaviour**: 
![geyser](https://user-images.githubusercontent.com/20336567/47500022-e4fccc00-d861-11e8-8e56-f3499aeef59e.png)
Source: http://classicdb.ch/?object=181597#wh-comments

**Server Revision**: 
[2214]

**Comment by Jezofine** [comment]
#1277

**Comment by Tenoutoften** [comment]
https://github.com/Atlantiss/NetherwingBugtracker/issues/1277
duplicate

**Comment by Azalen** [comment]
Well I wouldnt say its a 100% duplicate since this is concerning the whole event not only the gameobject <.<

**Comment by Easyfraggy** [comment]
Add your information in the other post please if anything is relevant.
