### ISSUE TITLE
[Core]/[NPC] Corpse despawn timer

### ISSUE THREAD

**Issue by xycz** [Atlantiss/NetherwingBugtracker#1880]
**Description**:  
Difficult to say what caused this depending on if it's NPC specific or not, but during our Uldaman run we killed the Ancient Stone Keeper. Everyone passed on the loot and someone changed their mind and wanted the item. Unfortunately the boss corpse despawned with the item inside after just a few seconds and since the player died, there was no way for them to have a chance of looting it.

**Current behaviour**:
Corpse containing rare items despawned within a minute.

**Expected behaviour**: 
Corpses containing higher quality items should remain for a longer duration of time.

**Server Revision**: 2194~

**Comment by Manaci** [comment]
Fixed with loot rework
