### ISSUE TITLE
Gordunni Warlock spawn rate too low

### ISSUE THREAD

**Issue by craigsurbrook** [Atlantiss/NetherwingBugtracker#1884]
[//]: # (Enclose links to things related to the bug using http://wowhead.com or any other TBC database.)
[//]: # (You can use screenshot ingame to visual the issue.)
[//]: # (Write your tickets according to the format:)
[//]: # ([Quest][Azuremyst Isle] Red Snapper - Very Tasty!)
[//]: # ([NPC] Magistrix Erona)
[//]: # ([Spell][Mage] Fireball)
[//]: # ([Npc][Drop] Ghostclaw Lynx)
[//]: # ([Web] Armory doesnt work)

**Description**:
When doing the Feathermoon quest (can't remember the name, but not important) where you have to kill Gordunni Brutes, Shamans, and Warlocks, you have tons and tons of Brutes and Shamans. But there is a problem with the Warlocks. Where a Warlock can spawn is where the "spawn" can be one of several types (like Battlemaster, Shaman, Mage-Lord and Warlock). However, it took hours, with no competition from other players to complete, killing everything in site over and over and over, just to get a "rare" spawn of a warlock. And then again, repeat.

**Current behaviour**:
You can kill the different ogres en-masse, killing them all so that you can get new spawns - and they are usually of Battlemaster, Shaman, and Mage-Lord.

**Expected behaviour**:
The spawns of Warlocks should be higher, not requiring you to kill everything multiple times just to get "one" to show up. Confirmed that this behavior was experienced by other guild members in <The One Percenters> where they had to the same, killing and waiting for respawns, taking hours to complete the quest (just like me).

I can only imagine what this would be like with multiple players in the zone trying to get warlocks.

One last note, I can't remember how this was in retail TBC, but there IS the possibility that Blizzard had it set this way in retail, on purpose, and the grindy aspect of this quest was intended for people to kill and get a level here by grinding. If anyone has information on that, we, of course, want it to be as close to retail as possible, droprates and all (even if they were frustrating, and I do remember that Blizz had some pretty low droprates in retail).

**Server Revision**: 
2214

**Comment by ScottieDOESknow** [comment]
Working as intended. That's how shared spawns work. More players that do the quest = higher RNG turnaround for possible spawns. Just gotta kill and check all the possible locations.

**Comment by netherwingbta** [comment]
There were tons of warlocks if you go a bit further south up the ramp of the massive building area.

**Comment by aresbrutus** [comment]
Yes, this is working as intended. You would have to clear mobs in the camp in the hopes of warlocks to spawn, or check other areas of possible spawn to see if a warlock is up there.
