### ISSUE TITLE
[Spell][Shaman] Grounding Totem and roots

### ISSUE THREAD

**Issue by Galawer** [Atlantiss/NetherwingBugtracker#1885]
**Current behaviour**:
Casting roots on a target protected by [Grounding Totem](http://db.excalibur.ws/?spell=8177) doesn't destroy the totem, because it's immune.
![image](https://user-images.githubusercontent.com/1574432/47516642-459e0000-d886-11e8-8b81-5578938b1030.png)
So while the totem is up you're completely invulnerable to roots.

**Expected behaviour**: 
The totem should get destroyed after redirecting one spell.

**Server Revision**: 
2214

**Comment by Brasso** [comment]
Just tested. Works. Can Close
