### ISSUE TITLE
[NPC]Calandrath#15174, Silithus innerkeeper facing the wrong way

### ISSUE THREAD

**Issue by Tenoutoften** [Atlantiss/NetherwingBugtracker#1887]
**Description**: 
[[NPC]Calandrath#15174](https://www.wowhead.com/npc=15174/calandrath#screenshots) stands with wrong angle, should have face facing outdoors.
https://youtu.be/00uGkMH4FAU?t=33
![ccf9206f6a0c63feac83ea8f506936ab](https://user-images.githubusercontent.com/34839199/47527979-4776bc00-d8a4-11e8-9a6f-70c4bc64e9c9.png)
![ef8714f381ce8cce7035ec54b7eeeebd](https://user-images.githubusercontent.com/34839199/47528020-5c534f80-d8a4-11e8-9a35-e7161c41cbf2.png)

**Expected behaviour**: 
Face towards the outdoors

**Server Revision**: 
2214

**Comment by ScottieDOESknow** [comment]
That's odd. Grinding in Silithus for past few days and she was always facing forward until today.

**Comment by Tenoutoften** [comment]
Yeah I too think she was standing properly a while ago

**Comment by Easyfraggy** [comment]
Seems theres a weird bug with some stationary npcs changing facing/position slightly somehow - dwarf dude in hinterlands and the stormwind guard.

**Comment by Tenoutoften** [comment]
it has returned to correct facing now

**Comment by aresbrutus** [comment]
Working for me.
