### ISSUE TITLE
[Spell] Visual bug when players are stunned by other players

### ISSUE THREAD

**Issue by Thugli** [Atlantiss/NetherwingBugtracker#1889]
[//]: # (Enclose links to things related to the bug using http://wowhead.com or any other TBC database.)
[//]: # (You can use screenshot ingame to visual the issue.)
[//]: # (Write your tickets according to the format:)
[//]: # ([Quest][Azuremyst Isle] Red Snapper - Very Tasty!)
[//]: # ([NPC] Magistrix Erona)
[//]: # ([Spell][Mage] Fireball)
[//]: # ([Npc][Drop] Ghostclaw Lynx)
[//]: # ([Web] Armory doesnt work)

**Description**: 
While in combat with enemy players, the enemy appears to bug/teleport once they are stunned. This happens most of the time while trying to reproduce this bug on a moving/strafing target.

**Current behaviour**:
https://youtu.be/k93J6ijudSk

**Expected behaviour**: 
The target should get stunned where the stun occurs and no visual bug should take place.
**Server Revision**: 
2214

**Comment by Kuumi** [comment]
happens to me too when i pounce as well -bigbrainman

**Comment by Erodraeda** [comment]
Happened with Hammer of Justice as well

**Comment by Thugli** [comment]
Also occurs with fear: 
https://www.youtube.com/watch?v=_lc98rdqGLU
