### ISSUE TITLE
[NPC] Sicky Gazelle

### ISSUE THREAD

**Issue by Bleachlol** [Atlantiss/NetherwingBugtracker#189]
**Description**: 
Sicky Gazelle is not stunned from charge not being killed from AA. 
**Current behaviour**:
When charged, it bugs out, run 5-10 yards and then resets. 
**Expected behaviour**: 
Should be stunned and attack-able after charge.  

Server Revision: 2028

**Comment by Easyfraggy** [comment]
confirmed on 12296 58 probably global issue with these types of critters some reported same issue with a Ram on discord earlier.

**Comment by Zirda** [comment]
I noticed similar behaviour with SW:P and Elwynn Forest Deer critters. 

https://gfycat.com/GraciousNaughtyImago

**Comment by pmachielsen** [comment]
I also noticed that when i DoT the sickly gazelle i dont even see the debuff on the target and i get combat and out-of-combat notice quickly after eachother.

**Comment by wtRCH** [comment]
@pelekon

**Comment by BamboozleNW** [comment]
Tested on multiple, works fine. Close. https://www.youtube.com/watch?v=FWTKoCKd82E
