### ISSUE TITLE
[Spell][Mage] Ice Block not preventing drowning damage

### ISSUE THREAD

**Issue by CCmagro** [Atlantiss/NetherwingBugtracker#1891]
[//]: # (Enclose links to things related to the bug using http://wowhead.com or any other TBC database.)
[//]: # (You can use screenshot ingame to visual the issue.)
[//]: # (Write your tickets according to the format:)
[//]: # ([Quest][Azuremyst Isle] Red Snapper - Very Tasty!)
[//]: # ([NPC] Magistrix Erona)
[//]: # ([Spell][Mage] Fireball)
[//]: # ([Npc][Drop] Ghostclaw Lynx)
[//]: # ([Web] Armory doesnt work)

**Description**: Ice Block not preventing drowning damage.

**Current behaviour**: Ice Block not preventing drowning damage.

**Expected behaviour**: "Ice Block will prevent drowning and fatigue damage, and reset the damage counter (not the bar) to zero. You will still lose breath and become fatigued while iceblocked."
http://wowwiki.wikia.com/wiki/Ice_Block?oldid=430161

**Server Revision**: 2215

**Comment by aresbrutus** [comment]
Addition to this, the paladin bubble spells should prevent drowning + fatigue damage.

http://wowwiki.wikia.com/wiki/Divine_Shield?oldid=1553542
`Divine Shield prevents all damage, including (unlike most other bubbles of other classes) falling damage, and even drowning damage.`

https://youtu.be/b9cg9Wnq2xE?t=183

**Comment by xmesaj2** [comment]
rev 2356
