### ISSUE TITLE
[NPC] Shayis Steelfury

### ISSUE THREAD

**Issue by netherwingbta** [Atlantiss/NetherwingBugtracker#1892]
[//]: # (Enclose links to things related to the bug using http://wowhead.com or any other TBC database.)
[//]: # (You can use screenshot ingame to visual the issue.)
[//]: # (Write your tickets according to the format:)
[//]: # ([Quest][Azuremyst Isle] Red Snapper - Very Tasty!)
[//]: # ([NPC] Magistrix Erona)
[//]: # ([Spell][Mage] Fireball)
[//]: # ([Npc][Drop] Ghostclaw Lynx)
[//]: # ([Web] Armory doesnt work)

**Description**: 

**Current behaviour**:
[Shayis Steelfury](https://www.wowhead.com/npc=7230/shayis-steelfury) has incorrect gossip text and a spyglass option. Seems to be from a WotLK npc.
[Vid of the wotlk npc.](https://www.youtube.com/watch?v=3FLGItxJM_k&t=12s)
Same text and spyglass thing.
https://www.wowhead.com/item=33341/braves-spyglass#created-by-spell
https://github.com/TrinityCore/TrinityCore/issues/20513
![shayis](https://user-images.githubusercontent.com/43872263/47542805-60509300-d8df-11e8-9c6a-548befdc3fbe.jpg)
![shayis2](https://user-images.githubusercontent.com/43872263/47542857-a1e13e00-d8df-11e8-8748-fcffa394b27d.jpg)
**Expected behaviour**: 
Shayis should not have the wotlk npc text and spyglass option.
**Server Revision**: 
2214

**Comment by Evolvee** [comment]
option removed but i need the correct gossip text

**Comment by Evolvee** [comment]
rev ff15
