### ISSUE TITLE
[Spell][Paladin] Judgement of Command

### ISSUE THREAD

**Issue by sifiuocz** [Atlantiss/NetherwingBugtracker#1893]
**Description**: 
[https://youtu.be/8GTPli4G3FU?t=10](url)
In the video i cast judgement while having Seal of Command. The animation of a judgement goes off. The buff "Seal of Command" is consumed, but no damage is inflicted.

**Current behaviour**:

**Expected behaviour**: 

**Server Revision**: 
2214

**Comment by sifiuocz** [comment]
Notice how Combat log says that I cast "Judgement" rather than "Judgement of Command"

**Comment by Easyfraggy** [comment]
https://github.com/Atlantiss/NetherwingBugtracker/issues/1191

**Comment by Easyfraggy** [comment]
Please add the info about "Judgement" in combat log on the proper issue.
