### ISSUE TITLE
[Pet/Pathing] Warlock Felguard intercept issue

### ISSUE THREAD

**Issue by BezawitNW** [Atlantiss/NetherwingBugtracker#1895]
**Description**: Sometimes when you order your Felguard to use Intercept on a mob, intercept is used (the mob becomes stunned) but the Felguard does not actually intercept to the mob. Instead the Felguard manually runs to the mob.

**Current behaviour**: This does not happen all the time and I have not found out the exact conditions where it happens. Occasionally when you order your Felguard to use Intercept, the mob will become stunned from the intercept but the Felguard will not actually intercept to the mob and instead run toward it.

**Expected behaviour**: The Felguard should intercept directly to the mob.

**Comment by Easyfraggy** [comment]
If you can continue to gather info and maybe figure out WHEN it happens that would be very helpful. Ofc if its entirely random theres no way for you to do so!

**Comment by duzyizly** [comment]
same as https://github.com/Atlantiss/NetherwingBugtracker/issues/6933

**Comment by The14me** [comment]
rev.3451 Still not able to reproduce it.
Can be closed.
Please re-open if find more info.

**Comment by BamboozleNW** [comment]
Tested for about an hour last night, could not be reproduced, can be closed.
