### ISSUE TITLE
Revantusk Village Inn

### ISSUE THREAD

**Issue by maxturtlesc2** [Atlantiss/NetherwingBugtracker#1896]
[//]: # (Enclose links to things related to the bug using http://wowhead.com or any other TBC database.)
[//]: # (You can use screenshot ingame to visual the issue.)
[//]: # (Write your tickets according to the format:)
[//]: # ([Quest][Azuremyst Isle] Red Snapper - Very Tasty!)
[//]: # ([NPC] Magistrix Erona)
[//]: # ([Spell][Mage] Fireball)
[//]: # ([Npc][Drop] Ghostclaw Lynx)
[//]: # ([Web] Armory doesnt work)

**Description**: 
Revantusk Village Inn doesn't give rested status.
**Current behaviour**:

**Expected behaviour**: 
Revantusk Village Inn should give rested status.
**Server Revision**:

**Comment by Jezofine** [comment]
It gives rest, you just need to stand near stairs to 2nd floor. Funny area trigger location.

**Comment by Evolvee** [comment]
^^ if u have retail evidence of it not being this case, feel free to comment

**Comment by maxturtlesc2** [comment]
@Evolvee Here it is, sir. https://youtu.be/8lKFNczM-wY?t=23

**Comment by Tereneckla** [comment]
#1896
