### ISSUE TITLE
Princess Moira chain broken?

### ISSUE THREAD

**Issue by samemari** [Atlantiss/NetherwingBugtracker#1897]
**Description**: 
There is the quest chain that starts from http://db.hellfire-tbc.com/?quest=3701 and completes with http://db.hellfire-tbc.com/?quest=4363
**Current behaviour**:
I have both quests in one time:
http://db.hellfire-tbc.com/?quest=4341 and http://db.hellfire-tbc.com/?quest=4363
![wowscrnshot_102618_224215](https://user-images.githubusercontent.com/29822974/47591696-3055ce00-d979-11e8-9186-da3694b34f92.jpg)

**Expected behaviour**: 
Cannot take http://db.hellfire-tbc.com/?quest=4363 from princess in the BRD when prev quest in the chain is active and not completed
**Server Revision**: 
2214

**Comment by ScottieDOESknow** [comment]
Just to be clear, everyone in the group was able to take the quest she offered. The quest should only be available to players who are on part 3: The Fate of the Kingdom (quest 4362). I was the only player in the group that was on the quest to save her afaik.

**Comment by Mikik3jr** [comment]
I duplicated this issue, but I link here just in case:
https://github.com/Atlantiss/NetherwingBugtracker/issues/1901

**Comment by Shanghi** [comment]
Somehow it just had no requirement at all set! It should be fixed in revision 2221 though.
