### ISSUE TITLE
One Venomtail Scorpid cant be attacked/no info

### ISSUE THREAD

**Issue by kelsul** [Atlantiss/NetherwingBugtracker#190]
[//]: # (Enclose links to things related to the bug using http://wowhead.com or any other TBC database.)
[//]: # (You can use screenshot ingame to visual the issue.)
[//]: # (Write your tickets according to the format:)
[//]: # ([Quest][Azuremyst Isle] Red Snapper - Very Tasty!)
[//]: # ([NPC] Magistrix Erona)
[//]: # ([Spell][Mage] Fireball)
[//]: # ([Npc][Drop] Ghostclaw Lynx)
[//]: # ([Web] Armory doesnt work)

**Description**: 
https://streamable.com/229hi
**Current behaviour**:
Cant attack this guy or get a npc info for him, works for others. check vid
**Expected behaviour**: 
He should be kill able 
**Server Revision**:

**Comment by The14me** [comment]
3127 ID:47

**Comment by Easyfraggy** [comment]
Seems to be too many scorpids spawned:
![image](https://user-images.githubusercontent.com/36134067/45928969-c7c79b80-bf4b-11e8-81a7-2ac73720a2a7.png)

**Comment by Easyfraggy** [comment]
https://github.com/Atlantiss/NetherwingBugtracker/issues/220 Linked because it has good screenshots! This issue persists after multiple restarts.

**Comment by Evolvee** [comment]
For some reason there are 2 double spawns... indentical spawnID even.

**Comment by Easyfraggy** [comment]
The unattackable ones are now gone, but some reason there are double spawns of these two scorpids with ID 46 and 47 i believe it was.

**Comment by The14me** [comment]
Working just fine now.

**Comment by Easyfraggy** [comment]
Double spawns of ID 46 and 47 are still there.

**Comment by Tereneckla** [comment]
Fixed
