### ISSUE TITLE
[Zone] [BRD] instance reset with missing bosses

### ISSUE THREAD

**Issue by ScottieDOESknow** [Atlantiss/NetherwingBugtracker#1902]
After clearing 99% of BRD (princess saved) all players (5) exit dungeon. Upon returning, it seem entire dungeon reset (doors closed, trash re-spawned) EXCEPT a few bosses/objects were missing. 

1. Breakable kegs to summon Hurley Blackbreath were missing.
2. Ribbly Screwspigot was missing but his 3 bodyguards were present.
3. Ambassador Flameflash was missing.
4.  Seven Dwarves WERE re-spawned and able to start fight gossip; their door was shut.
5. Lycerium was re-spawned, braziers not lit, door closed BUT Magmus was dead.
6. Emperor Dagran Thaurissan was dead, but princess was ALIVE and HOSTILE.

Few things to note: 

- Group leader did not reset dungeon.
- Group lead was constant, did not change even after returning.
- Tsu can confirm last 3/4 boss dead but trash re-spawn and doors shut.
- Those were the only bosses I checked after returning, could have been more.

**Server Revision**:  2214

**Comment by Godmatik** [comment]
Was fixed several years ago
