### ISSUE TITLE
[Proffesion] Fishing bonuses

### ISSUE THREAD

**Issue by Dusky1** [Atlantiss/NetherwingBugtracker#1904]
**Current behaviour**: Fishing bonus skill from items (for example +5 on Fishing Pole, Hats, boots and other items) and lures is added to your basic skill. Because of that, it slowers down your skilling of fishing, cuz you need to fish more for skillups if you use +Fishing items. Also, you can cheat on getting fishing quests. For example if you have 125 fishing and you need 225 Fishing to take this [quest](https://www.wowhead.com/quest=13826/nat-pagle-angler-extreme), you just use this [lure](https://www.wowhead.com/item=6533/aquadynamic-fish-attractor) and you can pick up the quest.

**Expected behaviour**: Bonus fishing from items and consumables should only affect your chance of succesfull fishing.

**Server Revision**: 2214

**Comment by Tereneckla** [comment]
Fixed
