### ISSUE TITLE
[NPC] Arcane Guardian patrol

### ISSUE THREAD

**Issue by Hidole555** [Atlantiss/NetherwingBugtracker#1905]
[//]: # (Enclose links to things related to the bug using http://wowhead.com or any other TBC database.)
[//]: # (You can use screenshot ingame to visual the issue.)
[//]: # (Write your tickets according to the format:)
[//]: # ([Quest][Azuremyst Isle] Red Snapper - Very Tasty!)
[//]: # ([NPC] Magistrix Erona)
[//]: # ([Spell][Mage] Fireball)
[//]: # ([Npc][Drop] Ghostclaw Lynx)
[//]: # ([Web] Armory doesnt work)

**Description**: In Silvermoon City, Arcane Guardian (Entry: 18103, Id: 3, GUIDLow: 60030) has a patrol issue walking up the Court of the Sun.

**Current behaviour**: When going up the stairs near the fountain in the Court of the Sun, this Arcane Guardian will stop at the top of the stairs, walk back down the stairs, and then go back up the stairs to resume his patrol going towards to the throne room.

**Expected behaviour**: When getting to the top of the stairs next to the fountain in the Court of the Sun, the Arcane Guardian should proceed on his patrol as normal instead of trying to squeeze in some extra cardio.

**Server Revision**: 2214

**Comment by Evolvee** [comment]
maybe core issue @aresbrutus , hold your horses

**Comment by aresbrutus** [comment]
Could be but I still remade the paths just in case. Rev `Eris`
