### ISSUE TITLE
[Quest] Rescue OOX-22/FE!

### ISSUE THREAD

**Issue by nycheia** [Atlantiss/NetherwingBugtracker#1907]
**Description**: 
You seem to be using the 3.2 version of this quest 

**Current behaviour**:
3.2 version https://www.youtube.com/watch?v=GQLEsFetRYc
as indicated by several wowhead comments https://www.wowhead.com/quest=2767/rescue-oox-22-fe#comments

**Expected behaviour**: 
http://wowwiki.wikia.com/wiki/Quest:Rescue_OOX-22/FE!
Its described in the 'Notes' section
**Server Revision**: 
2214

**Comment by Evolvee** [comment]
already reported
