### ISSUE TITLE
[Silvermoon City] Patch 2.4 RP dialogue

### ISSUE THREAD

**Issue by netherwingbta** [Atlantiss/NetherwingBugtracker#1908]
[//]: # (Enclose links to things related to the bug using http://wowhead.com or any other TBC database.)
[//]: # (You can use screenshot ingame to visual the issue.)
[//]: # (Write your tickets according to the format:)
[//]: # ([Quest][Azuremyst Isle] Red Snapper - Very Tasty!)
[//]: # ([NPC] Magistrix Erona)
[//]: # ([Spell][Mage] Fireball)
[//]: # ([Npc][Drop] Ghostclaw Lynx)
[//]: # ([Web] Armory doesnt work)

**Description**: 
A few npcs have dialogue referencing the events of patch 2.4.
**Current behaviour**:
[Initiate Colin](https://www.wowhead.com/npc=18174/initiate-colin) and [Initiate Emeline](https://www.wowhead.com/npc=18175/initiate-emeline) have a conversation about Kael'thas taking M'uru. (even though M'uru is just a few meters away from them in the chamber below.)
![screen shot 2018-10-27 at 2 29 30 pm](https://user-images.githubusercontent.com/43872263/47604187-51103900-d9f6-11e8-8dce-6c4226e5ebe2.png)
![screen shot 2018-10-27 at 2 30 54 pm](https://user-images.githubusercontent.com/43872263/47604188-566d8380-d9f6-11e8-956e-9897809f5341.png)
![screen shot 2018-10-27 at 2 45 57 pm](https://user-images.githubusercontent.com/43872263/47604252-37232600-d9f7-11e8-8fdc-1947a22790b5.png)

[Arcane Guardians](https://www.wowhead.com/npc=18103/arcane-guardian) had their dialogue "fixed" in [2.4. ](https://www.wowhead.com/npc=18103/arcane-guardian#comments:id=267677)
They used to praise the sun king pre 2.4.
![screen shot 2018-10-27 at 2 09 03 pm](https://user-images.githubusercontent.com/43872263/47604291-d6481d80-d9f7-11e8-8022-bb48247ba600.png)
Then in 2.4:
![screen shot 2018-10-27 at 2 19 20 pm](https://user-images.githubusercontent.com/43872263/47604282-c29cb700-d9f7-11e8-8afc-ddadbda8b89e.png)
On netherwing they currently do both.

[Silvermoon City Guardians](https://www.wowhead.com/npc=16222/silvermoon-city-guardian) also self corrects himself with "Sun K-- ah... Silvermoon" when [Champion Vranesh](https://www.wowhead.com/npc=18146/champion-vranesh) does his emotes during his rp patrol. 
![silvermoonsunkingrp](https://user-images.githubusercontent.com/43872263/47604328-730abb00-d9f8-11e8-839d-0bd28035767c.jpg)
https://wow.gamepedia.com/Champion_Vranesh

[Silvermoon Rangers](https://www.wowhead.com/npc=18147/silvermoon-ranger) mention M'uru being taken.
![screen shot 2018-10-27 at 3 08 50 pm](https://user-images.githubusercontent.com/43872263/47604468-90d91f80-d9fa-11e8-8d5c-33f10e6b16a3.png)

Might be more. 

**Expected behaviour**: 
The dialogue should not be in patch 2.4 state. 
**Server Revision**: 
2214

**Comment by Evolvee** [comment]
@aresbrutus u were supposed to do a list of those -.-

**Comment by aresbrutus** [comment]
Thankfully I did, now it is up for you to fix before you forget it! https://github.com/Atlantiss/AtlantissTBCBT/issues/924

**Comment by Evolvee** [comment]
rev 2500
