### ISSUE TITLE
[NPC] Greater Rock Elemental

### ISSUE THREAD

**Issue by SahrFR** [Atlantiss/NetherwingBugtracker#1909]
![wowscrnshot_102718_154810](https://user-images.githubusercontent.com/43706008/47604911-101d2200-da00-11e8-87ea-52cbdb96db6e.jpg)
**Description**: The mob Greater Rock Elemental (Entry 2736; ID 19; GUIDlow 113277) in Badlands seems to be stuck, it stays behind a rock and doesn't move at all (I stayed more than 5 mins to be sure it's really not moving)

**Current behaviour**: The mob doesn't move at all.

**Expected behaviour**: the mob should walk around in the area.

**Server Revision**: 2214

**Comment by SahrFR** [comment]
Here is the same on a lesser rock elemental (stayed a long time to be sure it doesn't move at all).
Server Revision : 2214
npc info : Entry 2735 ; ID 15 ; GUIDlow 107177
![wowscrnshot_102718_191935](https://user-images.githubusercontent.com/43706008/47609666-63649400-da43-11e8-82d1-7964b24b77b1.jpg)

**Comment by aresbrutus** [comment]
Fixed the stuck elemental, the second one is related to some random movement issue, but the npc's do move.
