### ISSUE TITLE
[Spell] [Core] Spell effect cancel on queue

### ISSUE THREAD

**Issue by Zuntrix** [Atlantiss/NetherwingBugtracker#191]
[//]: # (Enclose links to things related to the bug using http://wowhead.com or any other TBC database.)
[//]: # (You can use screenshot ingame to visual the issue.)
[//]: # (Write your tickets according to the format:)
[//]: # ([Quest][Azuremyst Isle] Red Snapper - Very Tasty!)
[//]: # ([NPC] Magistrix Erona)
[//]: # ([Spell][Mage] Fireball)
[//]: # ([Npc][Drop] Ghostclaw Lynx)
[//]: # ([Web] Armory doesnt work)

**Description**: 
If I queue up my auto attack before my spell ends. The visual spell effect won't go off.

**Current behaviour**:

https://i.imgur.com/Lc38kSP.gifv

EDIT: I've been made aware by Tsu who came by in game that the bug seems to only be for the player. He could see my spells even though they didn't show for me.

**Expected behaviour**: 
I assume the effect is going to go off. And then my auto attack animation after that. This might tie into the issue with Rogues auto attacking before backstabbing as the first attack on an enemy. 

**Server Revision**: 
rev 2028

**Comment by Tenoutoften** [comment]
How do you reproduce this? Your gif is gone.
I tried:
* Right click on the mob during the spell: Caused spell to go off normally, but auto attacks not to enable.
* Right click before spell: Auto attack starts, spell cast starts, once spell is finished auto attack continues. w/ visual

**Comment by aresbrutus** [comment]
Going to close this as it either never happened or is fixed by now. DM me to re-open if you got additional info/footage.
