### ISSUE TITLE
[Item] Snowball drop

### ISSUE THREAD

**Issue by samemari** [Atlantiss/NetherwingBugtracker#1911]
**Description**: 
There is an item which attends winter holidays event: http://db.hellfire-tbc.com/?item=17202

**Current behaviour**:
Got drop from Giant Yeti in Alterac
![wowscrnshot_102718_172910](https://user-images.githubusercontent.com/29822974/47605387-63966c80-da0e-11e8-8a37-8139af7bb998.jpg)

**Expected behaviour**: 
Seems Snowballs available only in Winter Holidays event
**Server Revision**: 
2214

**Comment by Shanghi** [comment]
This should be fixed in revision 2333.
