### ISSUE TITLE
Hunter's Disengage not making the character exit combat

### ISSUE THREAD

**Issue by mhdemn** [Atlantiss/NetherwingBugtracker#1913]
[Spell] [Hunter]: Disengage https://tbc-twinhead.twinstar.cz/?spell=14272

**Description**: Hunter's Disengage DOES reduce your aggro amount, but DOES NOT make you exit combat mode.

**Current behaviour**: Reduces threat on target. Doesn't exit combat.

**Expected behaviour**: Reduces threat on target AND exits combat.

**Server Revision**: 2214

**Comment by Easyfraggy** [comment]
This seems unrealisticly OP, being able to leave combat on 5sec cd...

**Comment by ircfelix** [comment]
Does this need further research?

**Comment by aresbrutus** [comment]
closing due to lack of interest.
