### ISSUE TITLE
[Spell][Hunter]Beast Lore doesn't work on beasts with level too low.

### ISSUE THREAD

**Issue by CCmagro** [Atlantiss/NetherwingBugtracker#1914]
[//]: # (Enclose links to things related to the bug using http://wowhead.com or any other TBC database.)
[//]: # (You can use screenshot ingame to visual the issue.)
[//]: # (Write your tickets according to the format:)
[//]: # ([Quest][Azuremyst Isle] Red Snapper - Very Tasty!)
[//]: # ([NPC] Magistrix Erona)
[//]: # ([Spell][Mage] Fireball)
[//]: # ([Npc][Drop] Ghostclaw Lynx)
[//]: # ([Web] Armory doesnt work)

**Description**: Casting Beast Lore on lvl 13 beasts, or less, gives the error "Target is too low level", im lvl 40. I'm not sure if this is a bug, but the maximum level difference seems a bit arbitrary and i couldn't find any source about this spell limitations.

**Expected behaviour**: Work on any level?

**Server Revision**: 2223

**Comment by nuiva** [comment]
Also happens with priest's Mind Control.

**Comment by Wolffenstein** [comment]
Fixed in rev 3400.
