### ISSUE TITLE
[NPC] Jaedenar Adept blinks inside the trees.

### ISSUE THREAD

**Issue by Mikik3jr** [Atlantiss/NetherwingBugtracker#1915]
[//]: # (Enclose links to things related to the bug using http://wowhead.com or any other TBC database.)
[//]: # (You can use screenshot ingame to visual the issue.)
[//]: # (Write your tickets according to the format:)
[//]: # ([Quest][Azuremyst Isle] Red Snapper - Very Tasty!)
[//]: # ([NPC] Magistrix Erona)
[//]: # ([Spell][Mage] Fireball)
[//]: # ([Npc][Drop] Ghostclaw Lynx)
[//]: # ([Web] Armory doesnt work)

**Description**: 
In Fellwood there are Jaedenar Adepts (https://www.wowhead.com/npc=7115/jaedenar-adept) that casts fireballs, fireblasts and blinks.
**Current behaviour**:
They can blink inside the trees.
![wowscrnshot_102718_194209](https://user-images.githubusercontent.com/43505031/47607495-0526b980-da21-11e8-8a7f-7c5b9763c69c.jpg)
**Expected behaviour**: 
The shouldn't
**Server Revision**: 
2214

**Comment by aresbrutus** [comment]
Closing and requesting retest after the update of rev 2430 and 2431.
