### ISSUE TITLE
[Spell][Paladin] Greater Blessing of XY

### ISSUE THREAD

**Issue by Mikik3jr** [Atlantiss/NetherwingBugtracker#1916]
[//]: # (Enclose links to things related to the bug using http://wowhead.com or any other TBC database.)
[//]: # (You can use screenshot ingame to visual the issue.)
[//]: # (Write your tickets according to the format:)
[//]: # ([Quest][Azuremyst Isle] Red Snapper - Very Tasty!)
[//]: # ([NPC] Magistrix Erona)
[//]: # ([Spell][Mage] Fireball)
[//]: # ([Npc][Drop] Ghostclaw Lynx)
[//]: # ([Web] Armory doesnt work)

**Description**: 
Greater paladin buffs are the 30 minute versions of the 10 minute version spells. They required a reagent called Symbold of Kings (https://www.wowhead.com/item=21177/symbol-of-kings) to use it.
**Current behaviour**:
I tried to give it to a lv50 player. She didn't get the buff, beacuse (I suppose) she is too low to receive the buff, but it consumed the reagent.
**Expected behaviour**: 
There should be an error message like "Target level is too low for that" or something like that instead of consuming the reagent, the mana and after that not doing anything.
**Server Revision**: 
2214

**Comment by Easyfraggy** [comment]
Someone please test this with other reagent buffs like PW:F / DS etc.

**Comment by Buggyswires** [comment]
I had a similar issue in Ramparts. Tried to apply Greater Blessing of Salvation to the warlocks in the group (one 62 one 59). The Blessing was only applied to the level 62 warlock, i had to use a 10min Blessing on the other one.

It seems like the level requirement to CAST the Blessing is also applied to the targets

**Comment by Consita** [comment]
server rev 3441:
Paladin Buffs not buffable bc of level and will not remove reagents.
Same with Priest, Mage Buffs
