### ISSUE TITLE
Pet accepting food above its level

### ISSUE THREAD

**Issue by KevinTyrrell** [Atlantiss/NetherwingBugtracker#1917]
**Description**: 
GIF: https://giant.gfycat.com/UltimateHatefulArcticfox.webm

Pets seem to be glad to eat food regardless of level. My level 23 wolf is able to eat food with Required Level 35. This is not correct, as an error should be output such that: "This food is too high level for your pet".

**Current behaviour**:
The pet accepts food regardless of its level requirement. If the pet eats food above his level, he consumes the item but does not gain a 'Feed Pet Effect'.

**Expected behaviour**: 
The pet should only accept food at or below its level requirement. The item being fed to the pet is only consumed if the level requirement is met, then a 'Feed Pet Effect' buff is applied.

**Server Revision**: 
2214

**Comment by KevinTyrrell** [comment]
Note, the food accepted by the pet beyond its level is actually *not consumed*. The animation takes place but the food item remains in the bags. The buff is not applied to the pet. The expected action is that no animation should take place, and an error message should display "that food it too high level for your pet."

**Comment by Manaci** [comment]
Fixed

**Comment by The14me** [comment]
Pet don't eat the food but miss the error message.
Rev 3441

**Comment by Godmatik** [comment]
#8541
