### ISSUE TITLE
Some group members phased out in dungeon

### ISSUE THREAD

**Issue by sum01** [Atlantiss/NetherwingBugtracker#1918]
[//]: # (Enclose links to things related to the bug using http://wowhead.com or any other TBC database.)
[//]: # (You can use screenshot ingame to visual the issue.)
[//]: # (Write your tickets according to the format:)
[//]: # ([Quest][Azuremyst Isle] Red Snapper - Very Tasty!)
[//]: # ([NPC] Magistrix Erona)
[//]: # ([Spell][Mage] Fireball)
[//]: # ([Npc][Drop] Ghostclaw Lynx)
[//]: # ([Web] Armory doesnt work)

**Description**: 
Entered RFD with 5 people, and 2 of them were invisible. The hunter's pet was also a yellow attackable mob, and their hp/mana wasn't changing. Couldn't heal them either.

This was fixed by walking out & back into the dungeon.

Note that their chat & rolls still worked even when invisible.

**Comment by Easyfraggy** [comment]
https://github.com/Atlantiss/NetherwingBugtracker/issues/1791
