### ISSUE TITLE
[Quest] ... and a Batch of Ooze

### ISSUE THREAD

**Issue by Galawer** [Atlantiss/NetherwingBugtracker#1919]
**Description**: 
[... and a Batch of Ooze](https://www.wowhead.com/quest=4294/and-a-batch-of-ooze)
You collect [Un'Goro Slime Sample](https://www.wowhead.com/item=12235/ungoro-slime-sample) from slimes in Un'Goro and use the [Testing for Impurities - Un'Goro Crater](https://www.wowhead.com/quest=4561/testing-for-impurities-ungoro-crater) quest to get [Un'Goro Tested Sample](https://www.wowhead.com/item=15102/ungoro-tested-sample) which can contain [Pure Un'Goro Sample](https://www.wowhead.com/item=12236/pure-ungoro-sample).

**Current behaviour**:
[Pure Un'Goro Sample](https://www.wowhead.com/item=12236/pure-ungoro-sample) also drops from [Firegut Brute](https://www.wowhead.com/npc=7035/firegut-brute) in Burning Steppes.

**Expected behaviour**: 
You should only be able to get [Pure Un'Goro Sample](https://www.wowhead.com/item=12236/pure-ungoro-sample) from [Un'Goro Tested Sample](https://www.wowhead.com/item=15102/ungoro-tested-sample).

**Server Revision**: 
2214

**Comment by Shanghi** [comment]
That's very strange! No more creatures will drop it after revision 2240.
