### ISSUE TITLE
[Object][Deeprun Tram]Invisible trams

### ISSUE THREAD

**Issue by DeltaLoads** [Atlantiss/NetherwingBugtracker#1920]
[//]: # (Enclose links to things related to the bug using http://wowhead.com or any other TBC database.)
[//]: # (You can use screenshot ingame to visual the issue.)
[//]: # (Write your tickets according to the format:)
[//]: # ([Quest][Azuremyst Isle] Red Snapper - Very Tasty!)
[//]: # ([NPC] Magistrix Erona)
[//]: # ([Spell][Mage] Fireball)
[//]: # ([Npc][Drop] Ghostclaw Lynx)
[//]: # ([Web] Armory doesnt work)

**Description**: 
Trams that are at station are invisible for players that enter Deeprun Tram
https://streamable.com/2f9gm
**Current behaviour**:
Trams are invisible while stationary
**Expected behaviour**: 
Trams should be visible
**Server Revision**: 
2214

**Comment by Easyfraggy** [comment]
Need confirmation from 3rd party.

**Comment by Easyfraggy** [comment]
Still need confirmation from 3rd party - also is this not blizzlike? I remember something similar on retail, could be client issue/unfixable.

**Comment by ircfelix** [comment]
Can confirm exactly the same behaviour as shown in the OP.

**Comment by KevinTyrrell** [comment]
Is this the same issues described in [my reddit post from a few weeks ago](https://old.reddit.com/r/wowservers/comments/9lu7w2/private_servers_and_the_deeprun_tram/)?

**Comment by Manaci** [comment]
Fixed

**Comment by KevinTyrrell** [comment]
@Manaci Can you elaborate on how this was fixed?
