### ISSUE TITLE
[Mage][Talent] Ignite

### ISSUE THREAD

**Issue by manslaughter** [Atlantiss/NetherwingBugtracker#1921]
**Description**: Fire mage talent

**Current behaviour**: Applied to enemy as soon as any fire spell crits.

**Expected behaviour**: Spells with a travel time (fireball, pyroblast) should only apply ignite on impact.

**Server Revision**: 2214

**Comment by Evolvee** [comment]
caused by revision 2204

**Comment by Easyfraggy** [comment]
Altho I do think this issue is valid, could we get some retail confirmation e.g a video to show that it should be the case.

**Comment by Wolffenstein** [comment]
Fixed in rev 2205.
