### ISSUE TITLE
[NPC]Crimson/Azure/Earthen/Hoary Templar#15209/15211/15307/125212 missing RP text on summon

### ISSUE THREAD

**Issue by Tenoutoften** [Atlantiss/NetherwingBugtracker#1922]
* [[NPC]Crimson Templar#15209](https://www.wowhead.com/npc=15209/crimson-templar#comments)
* [[NPC]Azure Templar#15211](https://www.wowhead.com/npc=15211/azure-templar#comments)
* [[NPC]Earthen Templar#15307](https://www.wowhead.com/npc=15307/earthen-templar#comments)
* [[NPC]Hoary Templar#15212](https://www.wowhead.com/npc=15212/hoary-templar#comments)

**Current Behavior**:
 says nothing and also spawns out of line of sight https://www.youtube.com/watch?v=9AxJC7epKgs&feature=youtu.be

**Expected behaviour**: 
Looks like they should say
>The Abyssal Council does not tolerate deceit! Feel our wrath, little <Race>!

Source, wrath: https://youtu.be/pV5qGlSKeUI?t=58

--------------------------

[Here](https://youtu.be/pV5qGlSKeUI?t=98) is a duke being summoned, looks like this one has a different text:
>What? Such a small, frail thing beckons me? This will not go unpunished!

--------------

The 40-man boss summoned [here](https://youtu.be/pV5qGlSKeUI?t=156)(yell)
>Your treachery only speeds your doom. This world will fall to darkness!

**Server Revision**: 
2214

**Comment by Evolvee** [comment]
rp fixed in rev yummy

i will rework these stones later
