### ISSUE TITLE
[NPC]Crimson/Azure/Earthen/Hoary Templar#15209/15211/15307/125212 should give 10 rep rather than 2

### ISSUE THREAD

**Issue by Tenoutoften** [Atlantiss/NetherwingBugtracker#1923]
**Description**: 
* [[NPC]Crimson Templar#15209](https://www.wowhead.com/npc=15209/crimson-templar#comments)
* [[NPC]Azure Templar#15211](https://www.wowhead.com/npc=15211/azure-templar#comments)
* [[NPC]Earthen Templar#15307](https://www.wowhead.com/npc=15307/earthen-templar#comments)
* [[NPC]Hoary Templar#15212](https://www.wowhead.com/npc=15212/hoary-templar#comments)

Should all grant 10 reputation on kill, currently grants 2 reputation, source wowhead comment
![935615c05a8918be354fb8d4327bf4f8](https://user-images.githubusercontent.com/34839199/47614357-17473d00-da9f-11e8-8bf3-cc88444d780d.png)

[[NPC]Crimson Templar#15209](https://www.wowhead.com/npc=15209/crimson-templar#comments) may work intentionally already, it is listed as 10 rep in excalibur database but I never fought it...

**Expected behaviour**: 
Expected to give 10 reputation rather than 2

**Server Revision**: 
2214

**Comment by Evolvee** [comment]
it gives me 10

**Comment by Evolvee** [comment]
oh

**Comment by Evolvee** [comment]
https://github.com/Atlantiss/NetherwingBugtracker/issues/1945
