### ISSUE TITLE
[Movement][NPC]Twilight Stonecaller#11882 should "attempts to run away in fear!"

### ISSUE THREAD

**Issue by Tenoutoften** [Atlantiss/NetherwingBugtracker#1924]
**Description**: 
[[NPC]Twilight Stonecaller#11882](https://www.wowhead.com/npc=11882/twilight-stonecaller#screenshots) should "attempts to run away in fear!"

https://youtu.be/g3dvisU_SMM?t=26
https://youtu.be/0Jjbo-t1IeU?t=98

**Current behaviour**:
Doesn't run away in fear.

**Expected behaviour**: 
"attempts to run away in fear!"

**Server Revision**: 
2214

**Comment by Evolvee** [comment]
rev yummy
