### ISSUE TITLE
[Game Mechanic][NPC]Twilight Stonecaller#11882, [NPC]Earth Elemental#329 de-agro while master doesn't

### ISSUE THREAD

**Issue by Tenoutoften** [Atlantiss/NetherwingBugtracker#1925]
**Description**: 
It is possible to pull [[NPC]Twilight Stonecaller#11882](https://www.wowhead.com/npc=11882/twilight-stonecaller#screenshots) in such a fashion that his/her [[NPC]Earth Elemental#329](https://www.wowhead.com/npc=329/earth-elemental#comments) will de-agro because of leash range, and returns to being a neutral pet, while you fight  [[NPC]Twilight Stonecaller#11882](https://www.wowhead.com/npc=11882/twilight-stonecaller#screenshots)

Video [here](https://www.youtube.com/watch?v=DvZ-P8LPczI&feature=youtu.be)

**Expected behaviour**: 
Probably expected to share leash with "master" & fight if you are engaged with the master.

**Server Revision**: 
2214

**Comment by Evolvee** [comment]
should be longer be possible in rev yummy
