### ISSUE TITLE
[NPC]Twilight Stonecaller#11882 summons [NPC]Earth Elemental#329 to often

### ISSUE THREAD

**Issue by Tenoutoften** [Atlantiss/NetherwingBugtracker#1926]
**Description**: 
It seems like [[NPC]Twilight Stonecaller#11882](https://www.wowhead.com/npc=11882/twilight-stonecaller#screenshots) shouldn't always be summoning([[Spell]Summon Earth Elemental#19704](https://db.excalibur.ws/?spell=19704) their [[NPC]Earth Elemental#329](https://www.wowhead.com/npc=329/earth-elemental#comments) when they spawn, looks like it is rare, or they don't do it at all, or it is a group thing only:
![1617fd5e4482c8a3428866c0bbb158c9](https://user-images.githubusercontent.com/34839199/47614757-13b6b480-daa5-11e8-9ea9-26c53ecd4f7b.png)
Three different camps with zero [[NPC]Earth Elemental#329](https://www.wowhead.com/npc=329/earth-elemental#comments)
https://youtu.be/g3dvisU_SMM?t=10
https://youtu.be/g3dvisU_SMM?t=182
https://youtu.be/pV5qGlSKeUI?t=237

Quite later expansion, but here you can see a few summoned:
https://youtu.be/mCGu0J0wJHk?t=121

**Current behaviour**:
Looks to always be summoned.

**Expected behaviour**: 
Expected to be a lot rarer or not be summoned at all after 2.3

**Server Revision**: 
2214

**Comment by Evolvee** [comment]
rev yummy

**Comment by Evolvee** [comment]
added 35% chance per NPC

if it should be lower, comment
