### ISSUE TITLE
[NPC][Quest] Sangrias Stillblade is missing his polearm

### ISSUE THREAD

**Issue by lordsval** [Atlantiss/NetherwingBugtracker#1927]
[//]: # (Enclose links to things related to the bug using http://wowhead.com or any other TBC database.)
[//]: # (You can use screenshot ingame to visual the issue.)
[//]: # (Write your tickets according to the format:)
[//]: # ([Quest][Azuremyst Isle] Red Snapper - Very Tasty!)
[//]: # ([NPC] Magistrix Erona)
[//]: # ([Spell][Mage] Fireball)
[//]: # ([Npc][Drop] Ghostclaw Lynx)
[//]: # ([Web] Armory doesnt work)

**Description**: 
On the Blood Elf Paladin quest "The First Trial", the NPC who attacks you inside the cave, Sangrias Stillblade, attacks you as though he were unarmed. This quest is no longer playable on retail but a screenshot from earlier times show the NPC attacking you with a polearm. This is a very low impact (cosmetic only) bug but I couldn't see it on here so may as well add it.
https://wow.gamepedia.com/File:Sangrias_Stillblade.jpg

Wowhead page for this npc: https://www.wowhead.com/npc=17716/sangrias-stillblade

**Current behaviour**:
Sangrias Stillblade attacks with unarmed (punching)

**Expected behaviour**: 
Sangrias Stillblade attacks with a generic polearm

**Server Revision**: 
Server Revision 2214
(time: 2018-10-28 11:00:00)

**Comment by Evolvee** [comment]
rev yummy
