### ISSUE TITLE
[NPC][Quest] Mirefin Ambusher doesn't give experience.

### ISSUE THREAD

**Issue by Asvaldi** [Atlantiss/NetherwingBugtracker#1928]
**Description**: 
[NPC] Mirefin ambusher (npc=23701) spawned through the script in [Quest] Recover the Cargo! (quest=11140) doesn't give experience.

http://prntscr.com/lbdkej

**Current behaviour**:
Doesn't give XP.

**Expected behaviour**: 
Gives XP.

**Server Revision**:

**Comment by Evolvee** [comment]
https://github.com/Atlantiss/NetherwingBugtracker/issues/1945
