### ISSUE TITLE
[NPC]Crimson/Azure/Earthen/Hoary Templar#15209/15211/15307/125212 should most likely give xp

### ISSUE THREAD

**Issue by Tenoutoften** [Atlantiss/NetherwingBugtracker#1929]
**Description**: 
* [[NPC]Crimson Templar#15209](https://www.wowhead.com/npc=15209/crimson-templar#comments)
* [[NPC]Azure Templar#15211](https://www.wowhead.com/npc=15211/azure-templar#comments)
* [[NPC]Earthen Templar#15307](https://www.wowhead.com/npc=15307/earthen-templar#comments)
* [[NPC]Hoary Templar#15212](https://www.wowhead.com/npc=15212/hoary-templar#comments)

Should all probably grant xp, based on the difficulty of the mob.

**Expected behaviour**: 
Should give xp, doesn't.

**Server Revision**: 
2214

**Comment by Evolvee** [comment]
https://github.com/Atlantiss/NetherwingBugtracker/issues/1945
