### ISSUE TITLE
Creep/NPC death and leaving combat

### ISSUE THREAD

**Issue by Cheesedip** [Atlantiss/NetherwingBugtracker#193]
[//]: # (Enclose links to things related to the bug using http://wowhead.com or any other TBC database.)
[//]: # (You can use screenshot ingame to visual the issue.)
[//]: # (Write your tickets according to the format:)
[//]: # ([Quest][Azuremyst Isle] Red Snapper - Very Tasty!)
[//]: # ([NPC] Magistrix Erona)
[//]: # ([Spell][Mage] Fireball)
[//]: # ([Npc][Drop] Ghostclaw Lynx)
[//]: # ([Web] Armory doesnt work)

**Description**: 
When an enemy npc dies it seems that the death animation is performed with a slight delay. I'm sure its not lag because I have 22ms ping, and others have mentioned this as well. In addition it takes about half a second  to leave combat after the enemy pc dies.

**Current behaviour**:
NPC's don't die immediately when their health gets below zero, in addition the player does not leave combat immediately after NPC-death.

**Expected behaviour**: 
NPC's should die immedaitely when their health gets below zero and the player should leave combat immediately.

**Server Revision**:

**Comment by Cheesedip** [comment]
I just realized this is due to spell-batch, so I guess this can be ignored, but maybe its an idea considering reducing tick-time. Because if you're on the early side of the tick it feels unnecessarily laggy.

**Comment by The14me** [comment]
work fine now.
