### ISSUE TITLE
[Spell][Mage] Blink - Shadowfang Keep

### ISSUE THREAD

**Issue by Ceago** [Atlantiss/NetherwingBugtracker#1930]
**Description**:   It is possible to blink through the stairs leading into the courtyard of SFK and hang around underneath the dungeon.  https://streamable.com/vanr3

**Current behaviour**:  Can blink through if you aim at a certain point.

**Expected behaviour**:   Should blink up the stairs.

**Server Revision**: 2226

**Comment by Ceago** [comment]
So far just SFK and that was the only spot we were able to do it.  We wouldn't have found it if Borgok didn't know this bug existed on other servers and specifically tried it.

**Comment by aresbrutus** [comment]
Closing and requesting retest after the update of rev 2430 and 2431.
