### ISSUE TITLE
[NPC] Ansekhwa teaches Weapon Skills early

### ISSUE THREAD

**Issue by Hidole555** [Atlantiss/NetherwingBugtracker#1931]
[//]: # (Enclose links to things related to the bug using http://wowhead.com or any other TBC database.)
[//]: # (You can use screenshot ingame to visual the issue.)
[//]: # (Write your tickets according to the format:)
[//]: # ([Quest][Azuremyst Isle] Red Snapper - Very Tasty!)
[//]: # ([NPC] Magistrix Erona)
[//]: # ([Spell][Mage] Fireball)
[//]: # ([Npc][Drop] Ghostclaw Lynx)
[//]: # ([Web] Armory doesnt work)

**Description**: Ansekhwa (Entry: 11869, Id: 1, GUIDLow: 20263), the Weapon Master in Thunder Bluff is teaching Weapon Skills to players below level 10.

**Current behaviour**: My level 9 Tauren Warrior (ign: Wolcambak) is able to learn the Guns and Staves skills from him.

**Expected behaviour**: Weapon Skills should not be able to be learned before level 10.

**Server Revision**: 2214

**Comment by Tenoutoften** [comment]
Seems like that is intended:
https://wow.gamepedia.com/index.php?title=Weapon_master&oldid=1048699
