### ISSUE TITLE
[Profession][Misc?] First Aid cancels out the players drinking

### ISSUE THREAD

**Issue by Mewmewww** [Atlantiss/NetherwingBugtracker#1932]
[//]: # (Enclose links to things related to the bug using http://wowhead.com or any other TBC database.)
[//]: # (You can use screenshot ingame to visual the issue.)
[//]: # (Write your tickets according to the format:)
[//]: # ([Quest][Azuremyst Isle] Red Snapper - Very Tasty!)
[//]: # ([NPC] Magistrix Erona)
[//]: # ([Spell][Mage] Fireball)
[//]: # ([Npc][Drop] Ghostclaw Lynx)
[//]: # ([Web] Armory doesnt work)

**Description**: 
Casting first aid [in this case runecloth] cancels the players drinking.
**Current behaviour**:
Casting first aid [in this case runecloth] cancels the players drinking.
**Expected behaviour**: 
shouldnt be cancelling his/her drinking.
**Server Revision**: 
2214

**Comment by xmesaj2** [comment]
#130
