### ISSUE TITLE
Fortitude decreases current health when re-cast with same Rank.

### ISSUE THREAD

**Issue by methodicality** [Atlantiss/NetherwingBugtracker#1934]
https://imgur.com/a/a0u5yZK

**Description**: When casting Fortitude with the same rank of Fortitude already on character, it decreases health as if it wasn't already on said character. In essence, it seems like the player is damaged if the same rank of Fortitude is cast for a second time on the player.

**Current behaviour**: Rank 1 Fortitude grants 30 health, when full health and cast again, it reduces health by 30 instead of keeping it 100%.

**Expected behaviour**: When re-cast on player who has same level of spell, no change in health should occur both in total amount or current amount.

**Server Revision**:  Netherwing

**Comment by Wolffenstein** [comment]
Fixed in rev 2399.

**Comment by Tenoutoften** [comment]
Could probably rename it, looks to be a core issue with rebuffing

[[Spell]Blessing of Kings#20217](https://db.excalibur.ws/?spell=20217)
[[Spell]Greater Blessing of Kings#25898](https://db.excalibur.ws/?spell=25898)
[[Spell]Arcane Intellect(rank 6)#27126](https://db.excalibur.ws/?spell=27126)
