### ISSUE TITLE
[Scholomance] Scholomance Occultist not transforming into Ghost Form

### ISSUE THREAD

**Issue by Azalen** [Atlantiss/NetherwingBugtracker#1936]
**Description**: 
https://en.wikipedia.org/wiki/Scholomance
http://wow-pro.com/dungeon_and_raid_guides/56%E2%80%9361_jame039s_scholomance_guide

http://classicdb.ch/?npc=10472

**Current behaviour**:
Does not transform into Ghost Form.

**Expected behaviour**: 
They should turn into shadow ghosts when at low hitpoints that are immune to all physical attacks. Poisons and other DoTs applied before they turn will continue to tick but no new effects can be applied.

In this phase they use their AoE shadowbolt - spamming it as an instant casts
(Source: http://classicdb.ch/?npc=10472#comments)

Proof: https://youtu.be/vS6ZN-M51xU?t=85

**Server Revision**: 
[2226]

**Comment by Azalen** [comment]
Think those are the mobs they turn into: http://classicdb.ch/?npc=11284

Also this report from Kronos should clear things up a bit: https://vanilla-twinhead.twinstar.cz/?issue=2292

**Comment by Aquaorangez** [comment]
additionally, these mobs seem to have no cooldown on their counterspell ability making it almost impossible to cast against them.

**Comment by Evolvee** [comment]
rev 2827
