### ISSUE TITLE
[Scholomance] Gandling missing RP

### ISSUE THREAD

**Issue by Azalen** [Atlantiss/NetherwingBugtracker#1937]
**Description**: 
http://classicdb.ch/?npc=1853
https://wow.gamepedia.com/Darkmaster_Gandling_(original)

**Current behaviour**:
No RP when all six minibosses are down.

**Expected behaviour**: 
Should yell something indicating he has spawned.

Proof: 
> Once he dies, you will hear Darkmaster Gandling shout. That means he just appeared down the stairs, in the middle of the 6 chambers.
Source: http://wow-pro.com/dungeon_and_raid_guides/56%E2%80%9361_jame039s_scholomance_guide

**Server Revision**: 
[2226]

**Comment by Azalen** [comment]
https://youtu.be/K0hR2pEUw3k?t=291

He yells: "School is in session!"

**Comment by Evolvee** [comment]
shitty cpp cockblocking me, would have to rewrite all the instance logic/bosses
