### ISSUE TITLE
[Scholomance] Jandice Barov not using Clone Ability

### ISSUE THREAD

**Issue by Azalen** [Atlantiss/NetherwingBugtracker#1938]
**Description**: 
https://classicdb.ch/?npc=10503
http://classicdb.ch/?npc=11439

**Current behaviour**:
Does not use clone ability.

**Expected behaviour**: 
Should create lots of clones that attack the party and  making it hard to target her.
Proof: https://wow.gamepedia.com/Jandice_Barov_(original)
> Summon Illusions - Summons 15 illusions to aid the caster in combat and distract the enemy. Illusions last 30 sec.

http://wow-pro.com/dungeon_and_raid_guides/56%E2%80%9361_jame039s_scholomance_guide
> Jandice Barov awaits you at the opposite side of the room, and if you manage to reach her, you did 90% of the job. She isn't very hard, has a special 'copy image' ability, which basically summons a bunch of illusions of Jandice. They are on a 10-15 seconds timer and have 3100 HP. I wouldn't bother killing them. Tab-target through them until you find the real Jandice (the only one which doesn't have "illusion" written in its name) and just keep on attacking her.

**Server Revision**: 
[2226]

**Comment by Evolvee** [comment]
![image](https://user-images.githubusercontent.com/1942409/47622580-f0245600-db06-11e8-933e-d0c3e93d5eee.png)

**Comment by Evolvee** [comment]
they were summoned for me
