### ISSUE TITLE
[Scholomance] Mini Bosses no loot

### ISSUE THREAD

**Issue by Azalen** [Atlantiss/NetherwingBugtracker#1939]
**Description**: 
https://web.archive.org/web/20071026112603/http://wow.allakhazam.com:80/db/mob.html?wmob=10502 (21% blue drop)
https://web.archive.org/web/20071026112628/http://wow.allakhazam.com:80/db/mob.html?wmob=10901 (23% blue drop)
https://web.archive.org/web/20071026112613/http://wow.allakhazam.com:80/db/mob.html?wmob=10505 (24% blue drop)
https://web.archive.org/web/20071028004252/http://wow.allakhazam.com:80/db/mob.html?wmob=10507 (26% blue drop)
https://web.archive.org/web/20071026112639/http://wow.allakhazam.com:80/db/mob.html?wmob=11261 (62% blue drop)
https://web.archive.org/web/20071026112608/http://wow.allakhazam.com:80/db/mob.html?wmob=10504 (72% blue drop)

**Current behaviour**:
None of the six minibosses drop loot. I know this is still possible RNG but seeing that smth similar occured in Sunken Temple I assume they dont have loot at all.

**Expected behaviour**: 
Should drop loot with higher chance for Libram/Totems/BoE t0 as seen in the loot tables.

**Server Revision**: 
[2226]

**Comment by Evolvee** [comment]
rev 2827
