### ISSUE TITLE
[Scholomance] Spectral Tutor Split Ability

### ISSUE THREAD

**Issue by Azalen** [Atlantiss/NetherwingBugtracker#1940]
**Description**: 
https://classicdb.ch/?npc=10498

https://classicdb.ch/?spell=17651
https://classicdb.ch/?spell=17652

https://classicdb.ch/?spell=17653

**Current behaviour**:
Does disappear (supposedly when he uses the split) but no splitted mobs spawn.

**Expected behaviour**: 
Should disappear and split into 5 image projections that heal the Tutor if not killed.

**Server Revision**: 
[2226]

**Comment by Evolvee** [comment]
I dont know from the description what should be fixed. I get that he should become immune for 6 sec and summon 5 dudes. But what about the healing, how that should work?

**Comment by Azalen** [comment]
5x https://classicdb.ch/?npc=11263 spawn for 6 seconds (source: http://wowwiki.wikia.com/wiki/Spectral_Tutor); party has to kill them in time or https://classicdb.ch/?spell=17652 gets used healing the Spectral Tutor and despawning the Spectral Projections.
If party manages to kill the Projections the Tutor reemerges without healing and can be killed.

Sadly im not able to find video footage of this from retail :/

**Comment by Evolvee** [comment]
fixed in next rev
