### ISSUE TITLE
[Scholomance] Linking

### ISSUE THREAD

**Issue by Azalen** [Atlantiss/NetherwingBugtracker#1941]
First room skeletons next to each other should be linked.
![wowscrnshot_102818_185401](https://user-images.githubusercontent.com/20336567/47621482-04615680-daf9-11e8-912f-8b1e0029ea25.jpg)

Room on top of Rattlegore packs of Scholomance Handler (https://classicdb.ch/?npc=11257) should be linked with the surrounding Plagued Hatchlings (https://classicdb.ch/?npc=10678). All packs in the room affected.
![wowscrnshot_102818_192241](https://user-images.githubusercontent.com/20336567/47621491-13e09f80-daf9-11e8-88d5-1f14ca587c01.jpg)

**Server Revision**: 
[2226]

**Comment by aresbrutus** [comment]
Fixed in rev Eris
