### ISSUE TITLE
[Scholomance] Blue Boss loot dropped from trash mob

### ISSUE THREAD

**Issue by Azalen** [Atlantiss/NetherwingBugtracker#1942]
**Description**: 
https://classicdb.ch/?item=14632

**Current behaviour**:
Necropile Leggings dropped from Trash Mob in the Mini-Boss area.

**Expected behaviour**: 
It shouldn't.
Proof: https://web.archive.org/web/20080112071944/http://wow.allakhazam.com:80/db/item.html?witem=14632

**Server Revision**: 
[2226]

**Comment by Evolvee** [comment]
global loot

**Comment by Shanghi** [comment]
This should be fixed in revision 2462.
