### ISSUE TITLE
[Object]Moving corpses

### ISSUE THREAD

**Issue by DeltaLoads** [Atlantiss/NetherwingBugtracker#1944]
[//]: # (Enclose links to things related to the bug using http://wowhead.com or any other TBC database.)
[//]: # (You can use screenshot ingame to visual the issue.)
[//]: # (Write your tickets according to the format:)
[//]: # ([Quest][Azuremyst Isle] Red Snapper - Very Tasty!)
[//]: # ([NPC] Magistrix Erona)
[//]: # ([Spell][Mage] Fireball)
[//]: # ([Npc][Drop] Ghostclaw Lynx)
[//]: # ([Web] Armory doesnt work)

**Description**: 
Using spells (maybe ranged weapons aswell) moves dead target to player
https://streamable.com/oivp7
**Current behaviour**:
Corpse moves toward player
**Expected behaviour**: 
Coprse should stay at same spot where npc dies
**Server Revision**: 
2228

**Comment by Evolvee** [comment]
also casters are moving while casting

and the entire movement is brutally desynced

**Comment by Wolffenstein** [comment]
Fixed in rev 2229.
