### ISSUE TITLE
Incorrect placement of NPC 'Succubus Minion' and incorrect hostility

### ISSUE THREAD

**Issue by AleksanderAAN** [Atlantiss/NetherwingBugtracker#1946]
[//]: # (Enclose links to things related to the bug using http://wowhead.com or any other TBC database.)
[//]: # (You can use screenshot ingame to visual the issue.)
[//]: # (Write your tickets according to the format:)
[//]: # ([Quest][Azuremyst Isle] Red Snapper - Very Tasty!)
[//]: # ([NPC] Magistrix Erona)
[//]: # ([Spell][Mage] Fireball)
[//]: # ([Npc][Drop] Ghostclaw Lynx)
[//]: # ([Web] Armory doesnt work)

**Description**: 
NPC 'Succubus Minion' located in Stonard (Swamp of Sorrows) appears to be unfriendly and standing inside a table
**Current behaviour**:
NPC is 'red' (as a hostile mob would) but non-aggresive
**Expected behaviour**: 
NPC should appear as any other neutral NPC 
Placement of the NPC is linked to 'Cersei Dusksinger', however will incorrectly stand inside/ontop of the table instead of beside 'Cersei Dusksinger'
![wowscrnshot_102818_234748](https://user-images.githubusercontent.com/44557182/47623051-c79f5a80-db0c-11e8-876a-bbaf65a2a29a.jpg)

**Server Revision**:

**Comment by Evolvee** [comment]
https://github.com/Atlantiss/NetherwingBugtracker/issues/1943
