### ISSUE TITLE
Gurubashi Arena

### ISSUE THREAD

**Issue by KevinSvard** [Atlantiss/NetherwingBugtracker#1947]
[//]: # (Enclose links to things related to the bug using http://wowhead.com or any other TBC database.)
[//]: # (You can use screenshot ingame to visual the issue.)
[//]: # (Write your tickets according to the format:)
[//]: # ([Quest][Azuremyst Isle] Red Snapper - Very Tasty!)
[//]: # ([NPC] Magistrix Erona)
[//]: # ([Spell][Mage] Fireball)
[//]: # ([Npc][Drop] Ghostclaw Lynx)
[//]: # ([Web] Armory doesnt work)

**Description**: 
No loot if you simply right-click, you have to shift+right-click. The chest only contains one item. So far I've gotten a pair of green boots, a green shield and 3 Superior Healing Potions at three different times. The chest does not despawn after it has been emptied of the single item.

**Current behaviour**:
See description.

**Expected behaviour**: 
It should also open on a right-click. Everything should be able to be autolooted except for the trinket (since it will bind to you). The chest should contain 50s-2g, sometimes a blue wrist, some green items, the green trinket and sometimes 20-35 potions. All this is taken from memory from TBC. I had two 19 twinks, two 29 twinks and one 49 twink with two Arena Grand Masters each.

**Server Revision**:

**Comment by Easyfraggy** [comment]
https://github.com/Atlantiss/NetherwingBugtracker/issues/642
