### ISSUE TITLE
[Shaman] Shaman weapon enchant procs in Ghost Wolf

### ISSUE THREAD

**Issue by NikiProToss** [Atlantiss/NetherwingBugtracker#1948]
[//]: # (Enclose links to things related to the bug using http://wowhead.com or any other TBC database.)
[//]: # (You can use screenshot ingame to visual the issue.)
[//]: # (Write your tickets according to the format:)
[//]: # ([Quest][Azuremyst Isle] Red Snapper - Very Tasty!)
[//]: # ([NPC] Magistrix Erona)
[//]: # ([Spell][Mage] Fireball)
[//]: # ([Npc][Drop] Ghostclaw Lynx)
[//]: # ([Web] Armory doesnt work)

**Spell**: [Windfury weapon](https://www.wowhead.com/spell=32911/windfury-weapon) and other weapon enchants.

**Description**: The way windfury weapon and other shaman weapon enchant procs work while in ghost wolf form is wrong.

**Current behaviour**: Windfury weapon and other shaman weapon enchants doesn't proc while ghost wolf spell is active.

**Expected behaviour**: Windfury weapon and other shaman weapon enchant procs should work regardless of any other active skill (While winfury weapon enchant is active).

**Server Revision**: 2229

**Comment by Eidous** [comment]
https://www.wowhead.com/spell=2645/ghost-wolf#comments comment chain by UnemMun seems to state otherwise

**Comment by Retinus** [comment]
[Old Druid Forum](http://thedruidsgrove.org/archive/wow/t-8487.html)
[Ghost_Wolf](https://wow.gamepedia.com/Ghost_Wolf)

Both links indicate that weapon buffs' effect are not active (like  [Flametongue Weapon],  [Windfury Weapon], and  [Frostbrand Weapon]) while in ghost wolf form.

**Comment by Easyfraggy** [comment]
Yep this is definitely a bug. Just not super high prio! =)

**Comment by NikiProToss** [comment]
@Easyfraggy  I think people are saying this is not a bug and current behaviour is how things should work. I just didn't do proper research before posting this issue

**Comment by Easyfraggy** [comment]
Oh I think I misread the doesn't in your OP!

They should indeed not proc in ghost wolf! :D
