### ISSUE TITLE
[Item][Spell] Buffs from on-use Jewelcrafting neck pieces is removed upon shapeshift(druid)

### ISSUE THREAD

**Issue by zauru7** [Atlantiss/NetherwingBugtracker#1949]
[//]: # (Enclose links to things related to the bug using http://wowhead.com or any other TBC database.)
[//]: # (You can use screenshot ingame to visual the issue.)
[//]: # (Write your tickets according to the format:)
[//]: # ([Quest][Azuremyst Isle] Red Snapper - Very Tasty!)
[//]: # ([NPC] Magistrix Erona)
[//]: # ([Spell][Mage] Fireball)
[//]: # ([Npc][Drop] Ghostclaw Lynx)
[//]: # ([Web] Armory doesnt work)
**Description**: 

Some jewelcrafting neck pieces have on-use effects that give x stats to entire party. The buff that these items give are removed upon using shapeshift on a druid(aquatic form in the picture but same effect for cat form, travel form etc. Moonkin form oddly enough not affected) Pictured is Heavy Golden Necklace of Battle, but all other items tested show the same behavior.
![aqua](https://user-images.githubusercontent.com/44526051/47645438-4fb74b80-db71-11e8-9707-709fd0b72ade.PNG)

https://www.wowhead.com/item=20831/heavy-golden-necklace-of-battle
https://www.wowhead.com/item=20966/jade-pendant-of-blasting 
https://www.wowhead.com/item=20967/citrine-pendant-of-golden-healing and https://www.wowhead.com/item=20950/pendant-of-the-agate-shield
item buffs all display this behavior. Probably not item related but rather something with shapeshifting
**Current behaviour**:
Shapeshifting into a form causes the buff to be removed

**Expected behaviour**: 
Shapeshifting should not affect the buff at all

**Server Revision**: 
2229

**Comment by zauru7** [comment]
tested with additional items that show the same behavior, bug probably linked to shapeshifting(see edit in OP)

**Comment by zauru7** [comment]
Tested additionally with 
-Eye of the Night https://www.wowhead.com/item=24116/eye-of-the-night
-Embrace of the Dawn https://www.wowhead.com/item=24117/embrace-of-the-dawn
-Chain of the Twillight owl  https://www.wowhead.com/item=24121/chain-of-the-twilight-owl

All show the same result, buff is removed upon shapeshifting. Edited title to more reflect the general problem rather than a single item problem.

**Comment by baade123** [comment]
was about to make report because this happened with pendant of the agate shield

**Comment by Manaci** [comment]
Fixed
