### ISSUE TITLE
[Passive] Inspiring Presence

### ISSUE THREAD

**Issue by Unfairy** [Atlantiss/NetherwingBugtracker#195]
Description: [Passive] Inspiring Presence

Current behaviour: Draenei Passive 'Inspiring Presence' is not showing up as active on myself, not sure about other party members just yet. Not does it show on the character sheet.

Expected behaviour:  The passive should show as active on the buff bar even for self buffing.

Server Revision:

**Comment by Evolvee** [comment]
proof from TBC that it should show on yourself?
