### ISSUE TITLE
[Shaman] "Windfury weapon" procs not identified as a melee attack?

### ISSUE THREAD

**Issue by NikiProToss** [Atlantiss/NetherwingBugtracker#1951]
[//]: # (Enclose links to things related to the bug using http://wowhead.com or any other TBC database.)
[//]: # (You can use screenshot ingame to visual the issue.)
[//]: # (Write your tickets according to the format:)
[//]: # ([Quest][Azuremyst Isle] Red Snapper - Very Tasty!)
[//]: # ([NPC] Magistrix Erona)
[//]: # ([Spell][Mage] Fireball)
[//]: # ([Npc][Drop] Ghostclaw Lynx)
[//]: # ([Web] Armory doesnt work)

**Proof**: [Screenshot](https://imgur.com/a/Xinb4Pp)

**Description**: Windfury weapon procs seems to not be identified as a melee attack

**Current behaviour**: Critical strikes from windfury weapon procs do not trigger Flurry and Shamanistic Focus.

**Expected behaviour**:  Critical strikes from windfury weapon procs should trigger Flurry and Shamanistic Focus.

**Server Revision**: 2229

**Comment by Galawer** [comment]
Windfury procs should proc all melee on-hit effects.
From [wiki](https://wow.gamepedia.com/Windfury_Weapon):

> As of 2.01, Windfury procs can trigger weapon-based procs and enchants—meaning one could potentially have a Crusader proc three times (the normal swing and the 2 Windfury occurrences) or 6 times if one is Dual-Wield Stormstrike spec'd. Windfury procs that crit will also trigger Flurry, but Windfury procs themselves do not consume Flurry.

And [video](https://www.youtube.com/watch?v=YhD4yVauDhA). Hard to spot from buffs because of UI lag, but if you count the procs popping up in the scrolling combat text it does add up. Also, you can see [Siphon Essence](http://db.excalibur.ws/?spell=40291) proccing from Windfury hits.

**Comment by kiraleos** [comment]
This is still an issue. I have only enchanted my off-hand with Windfury:

![alt text](https://i.imgur.com/NQdNrpa.png)

**Comment by QuelSera** [comment]
Windfury crits still do not proc Unleashed Rage, Shamanistic Focus and Flurry.

**Comment by Wolffenstein** [comment]
Fixed
