### ISSUE TITLE
Burning Blade Apprentice Summoning bug

### ISSUE THREAD

**Issue by koochy414** [Atlantiss/NetherwingBugtracker#1952]
[//]: # (Enclose links to things related to the bug using http://wowhead.com or any other TBC database.)
[//]: # (You can use screenshot ingame to visual the issue.)
[//]: # (Write your tickets according to the format:)
[//]: # ([Quest][Azuremyst Isle] Red Snapper - Very Tasty!)
[//]: # ([NPC] Magistrix Erona)
[//]: # ([Spell][Mage] Fireball)
[//]: # ([Npc][Drop] Ghostclaw Lynx)
[//]: # ([Web] Armory doesnt work)

**Description**: 
([NPC] Burning Blade Apprentice
The caster mobs at skull rock in durator resummon a voidwalker when they are reset, resulting in 2 voidwalkers being spawned. Didnt get a chance to recreate this.

**Current behaviour**:
Burning Blade Apprentice resummons a voidwalker while already having one present

**Expected behaviour**: 
should either resummon and replace voidwalker or not cast anything

**Server Revision**:

**Comment by Evolvee** [comment]
rev yummy
