### ISSUE TITLE
Scarlet Cathedral LoS bug

### ISSUE THREAD

**Issue by koochy414** [Atlantiss/NetherwingBugtracker#1953]
[//]: # (Enclose links to things related to the bug using http://wowhead.com or any other TBC database.)
[//]: # (You can use screenshot ingame to visual the issue.)
[//]: # (Write your tickets according to the format:)
[//]: # ([Quest][Azuremyst Isle] Red Snapper - Very Tasty!)
[//]: # ([NPC] Magistrix Erona)
[//]: # ([Spell][Mage] Fireball)
[//]: # ([Npc][Drop] Ghostclaw Lynx)
[//]: # ([Web] Armory doesnt work)

**Description**: 
Weird LoS bug near the doors to the cathedral on the right hand side, equidistant from the fountain and the door (if you are facing the door from the outside). 

**Current behaviour**:
There was a invisible LoS or wall, stopping me from healing.

**Expected behaviour**: 
There shouldn't be any LoS, was completely in the open

**Server Revision**: 
remove the wall?

**Comment by Easyfraggy** [comment]
Provide a screenshot of the area please, much more informative.

**Comment by Tereneckla** [comment]
Fixed
