### ISSUE TITLE
[Hunter] [Pet] Furious Howl - Feed Pet bugged interaction

### ISSUE THREAD

**Issue by mhdemn** [Atlantiss/NetherwingBugtracker#1954]
https://tbc-twinhead.twinstar.cz/?spell=24603

user "ghost" created this issue 15 days ago and it was supposed to be fixed but it isn't on current server revision. https://github.com/Atlantiss/NetherwingBugtracker/issues/1592#issue-369906129

Description: Furious Howl (Wolf-class hunter pet's ability) cancels Feed Pet aura from the wolf.

Current behaviour: Whenever the wolf casts this, it removes Feed Pet's 20 seconds long buff from him. In theory only when the pet attacks or gets attacked the Feed Pet buff gets removed.

Expected behaviour: Wolf pets should be able to cast Furious Howl whenever and not cancel Feed Pet buff.

*It's easily fixable from the player side by using on/off toggling macros along with the Feed Pet button, but if it has easier fixing from the technical side that would be cool.

Server Revision: 2229

**Comment by Easyfraggy** [comment]
Noone had any idea what the report was about because the description was terribly worded. He later closed it himself. No fixing was done to this issue whatsoever because noone described the issue properly untill your post just now. So no it was not fixed.

**Comment by ircfelix** [comment]
Is the research for this report really important? I can't imagine any situation in the game where the Feed Pet buff getting removed from Furious Howl or not makes any difference. So you could just let Furious Howl **not** remove the Feed Pet buff.

**Comment by mhdemn** [comment]
I agree. Besides, I'm going nuts searching for video proof that it worked like that in retail TBC.

Haven't found anything that proves that Howl shouldn't cancel Feed Pet. All I found is [http://classic-wow.wikia.com/wiki/Feed_Pet](url) that says "The "Feed Pet Effect" buff disappears if the pet deals/receives any damage, wasting the feeding", and a bunch of videos.

So far I've only seen video footage that shows that wolf pets actually do not cast Furious Howl (with Furious Howl toggled on) when out of combat.
[https://youtu.be/BsRO1NRDUI4?t=422](url) here you can see a hunter during vanilla retail taming a wolf, then the wolf stays out of combat with Howl toggled on autocast but doesn't cast it.
In [https://youtu.be/Iu4qoFKTlC8?t=580](url) you can see a retail TBC hunter taming a wolf with Howl toggled on and not casting it out of combat. 
For contrast, here's [https://www.youtube.com/watch?v=8rn4mM5nW3o](url) from Netherwing's current server revision (2229).


So I checked every patch note during the TBC xpac looking for something about what cancels and what doesn't cancel Feed Pet buff (assuming classic-wow wiki, what my hunter buddies from vanilla servers say and what I think is true, that only damage/being damaged makes the pet lose it's feed pet buff) and found nothing related to it, only found out that Furious Howl autocast seems to be bugged.

So, reformulating my initial issue:

1st Issue: Furious Howl autocast. I'm inclined to think Furious Howl's autocast when out of combat is a bug.

Current behaviour: Furious Howl is automatically casted when the button is toggled on autocast and the pet is out of combat.

Expected behaviour: Furious Howl should be only casted automatically when in combat AND when toggled on.

2nd issue: **I'm inclined** to think Furious Howl cancels Feed Pet buff when casted. I'll add proof it worked like I think in retail TBC when/if I find it.

Current behaviour: Furious Howl cancels Feed Pet buff when casted.

Expected behaviour: Furious Howl should have no interaction with Feed Pet whatsoever.

Server revision: 2229

**Comment by mhdemn** [comment]
Do you want me to open a new issue for these, open 2 new issues, it's okay if they're written in this one? @Easyfraggy

**Comment by Easyfraggy** [comment]
It's okay if you keep it in here, I do believe that #1 is true, and that is indeed bugged, I remember having to activate howl manually out of combat on my hunter - also it would be annoying weird if wolves would be buffing on off when not in combat in cities etc.

Issue #2 is the one I don't know about. It would be illogical for someone to be able to howl while eating - but lots of things in wow is illogical - so that is in no way proof. Would be nice to get some evidence, but even if you can't it's not a big issue if #1 is fixed.

**Comment by mhdemn** [comment]
Okay, I'll try to find proof in video but it might be hard or impossible. If anyone sees this and thinks of any raw footage of vanilla / tbc hunter gameplay please link it to me and I'll revise it. I already checked the whole Joanna recorded gameplay for his record speedrun and he tames no wolf during the whole thing, and I can't think of anything else but doing random searches, and all I got are those videos I linked earlier where you can't see Howl and Feed Pet happening at the same time anyway. 
Having said that, I find yours is a valid point. Regardless of what it was like in retail and regardless of what you guys do in Netherwing, whether you do as you see fit or as you think it was in retail, I think this is a minor thing. I mean, you can just add a /petautocastoff line to your feed pet macro and a /petautocaston to any of your often-used shots macros and you'll be just fine. So yeah, my point is, if you feel like sticking to the logic here, while I agree it makes sense that if you howl you stop eating, it would also make sense that you can howl between bites, don't you? 
Anyway lol I'll try to find some footage but if I don't find anything (and I'll be testing Outland mostly and I don't think you find many wolves until Blade's Edge Mountains) whatever you decide to do is fine with me and probably everyone, and everyone can adapt to it for sure. Cheers!

**Comment by ircfelix** [comment]
You can search for Lupos, the wolf everyone used for some time back in vanilla. Maybe you're lucky with that search

**Comment by mhdemn** [comment]
I spent another 40 minutes searching for old raid runs from hunter povs, bossfights, didn't do the trick. Lupos was a good shot but I couldn't find any original stuff 'cause youtube lets you sort videos by date but not in an inverse order (-.-)
I also revised like 7 hours of raiding from hunters raiding stuff, the vanilla ones didn't have their Furious Howl turned on, the TBC ones used wind serpents...
I give up. Whatever it is, I'll make sense out of it lol, whether chewing and howling isn't compatible or howling between bites, both work for me.

**Comment by mhdemn** [comment]
Okay here's an update. Tamed a cat with Prowl (Stealth) this time, and when the cat enters stealth it also cancels Feed Pet effect. This one's a bigger deal than the Howl imo, and now I'm inclined to think that a bunch of pets could have this bug. So far I know in 2229 neither Dive nor Dash (Sprint) cancel the Feed Pet buff. Other buffing abilities might be bugged for all I know. Maybe there's a fixable common factor amongst these? 
PS Cats can start eating while in stealth, while out of stealth, and I got confirmation from various vanilla servers that it's like that in there, and entering/exiting stealth doesn't cancel this buff.
PS2 Only happens when entering Prowl state while having Feed Pet active, canceling Prowl state doesn't affect it. So I guess it's the action of casting the ability rather than the aura itself.

**Comment by Easyfraggy** [comment]
Not convinced that this is indeed a bug.

Only first part of the issue (autocast out of combat)

**Comment by mhdemn** [comment]
Since finding proof of it being a bug is gonna be nearly impossible, I'd just like you to please consider the following: (either to take it as an actual bug, a small issue, or a subject to merely discuss to see if there's anything to do about it)

The **Ferocious Howl** thing is pretty much a QoL change. Again, if it happens to be a huge thing when it comes to fixing (I dunno shit about programming, less when it comes to WoW code) then don't worry about it, macros do the trick in here. But I do think it's a minimum impact - QoL thing that would hurt nobody yet everyone would appreciate.
If it's not too impertinent from me, I'd like to suggest to either classify this as a super-low priority thing, and not even an issue but rather a small subject open to debate amongst you admins to decide if you want it this way or that way. I'm fine with either and I'm sure everyone else will.

However, when it comes to **Prowl** I'd say it's a bigger deal because unlike with Howl, there's a few solid reasons you want this on autocast for, at all times, because you want your Cat pet to be stealthed in case you get ganked, or want to deceive an enemy player, or just do not want to be clicking the Prowl button for your pet all day while killing mobs. Yes, you can fix it aswell with the autocaston/off macro lines in your Feed Pet button and another button, but in this case you're actually getting a little trouble whereas in the Howl case there's no trouble at all with the macro fix (since it doesn't matter if Howl is up when out of combat). 
Okay, to reactivate Prowl autocast again after feeding your pet is a little thing to get used to,  but here I'd put my hand in the fire because I'm confident Blizz didn't design it like that on retail. I'm sure I didn't have to toggle my cat's prowl on and off all the time when feeding it back when I was playing TBC back in the day, and my point is it doesn't make sense from a WoW player's pov, since logic can't be applied (cats don't go literally invisible IRL, not while eating, not ever).

Those are my arguments since I've failed to provide proof. I'd just like you guys to consider weighing the QoL factor in when making this decision <3

**Comment by KevinTyrrell** [comment]
I know **exactly** how Prowl autocast worked. If you had prowl on autocast your pet would not go into Prowl when you're idling or walking around. I can prove that without evidence with induction. If the prowl was casted whenever it could be (out of combat) the pet would move at a slower speed and would constantly despawn behind the hunter. It would be completely useless to have it on autocast. Further more, macros exist written in vanilla where they manually /cast Prowl, that's because autocast didn't automatically put them in prowl at all times.


What autocast did for prowl is whenever they would get an attack command (through /petattack button press or aggressive behavior mode) they would enter prowl once and head towards the target.

**Comment by Wolffenstein** [comment]
Fixed in rev 3426.
