### ISSUE TITLE
[Object][Ashenvale]Lumber Pile

### ISSUE THREAD

**Issue by DeltaLoads** [Atlantiss/NetherwingBugtracker#1955]
[//]: # (Enclose links to things related to the bug using http://wowhead.com or any other TBC database.)
[//]: # (You can use screenshot ingame to visual the issue.)
[//]: # (Write your tickets according to the format:)
[//]: # ([Quest][Azuremyst Isle] Red Snapper - Very Tasty!)
[//]: # ([NPC] Magistrix Erona)
[//]: # ([Spell][Mage] Fireball)
[//]: # ([Npc][Drop] Ghostclaw Lynx)
[//]: # ([Web] Armory doesnt work)

**Description**: 
Looting Lumber Pile causes nearby Horde Deforester and Peons to bug out on pathfinding
https://streamable.com/9tv78
https://streamable.com/ncaav
**Current behaviour**:
Horde Deforesters and Peons bug out if you loot Lumber Pile
**Expected behaviour**: 
They should run to player and attack
**Server Revision**: 
2229

**Comment by aresbrutus** [comment]
Not related to object, known issue: https://github.com/Atlantiss/NetherwingBugtracker/issues/1582
