### ISSUE TITLE
Some fears teleport you randomly after it is over

### ISSUE THREAD

**Issue by Mikik3jr** [Atlantiss/NetherwingBugtracker#1956]
[//]: # (Enclose links to things related to the bug using http://wowhead.com or any other TBC database.)
[//]: # (You can use screenshot ingame to visual the issue.)
[//]: # (Write your tickets according to the format:)
[//]: # ([Quest][Azuremyst Isle] Red Snapper - Very Tasty!)
[//]: # ([NPC] Magistrix Erona)
[//]: # ([Spell][Mage] Fireball)
[//]: # ([Npc][Drop] Ghostclaw Lynx)
[//]: # ([Web] Armory doesnt work)

**Description**: 
[Frenzied Pterrodax](https://www.wowhead.com/npc=9167/frenzied-pterrordax) uses [Terrify](https://www.wowhead.com/spell=7399/terrify) on you occasionally.
In this case I was testing Entry: 9167, id:28 GUIDLow 89361
**Current behaviour**:
After the terrify ends it teleports you to a random place around the NPC.
https://www.youtube.com/watch?v=SgXKZbUYPF0&feature=youtu.be
(Sorry for the clicking thingy I haven't set up the recorder)
**Expected behaviour**: 
I should stay where the terrify faded on me.
**Server Revision**: 
2229

**Comment by Easyfraggy** [comment]
LUL xD

**Comment by Jezofine** [comment]
Looks like this is something new, didn't experience this when I was leveling.

**Comment by Tenoutoften** [comment]
Definitely something new... didn't happen to me either

**Comment by Mikik3jr** [comment]
Update: Issue must be global. In Shadow Lab fearing mob doing the same.
https://www.youtube.com/watch?v=N6DYzSc25lw&feature=youtu.be

**Comment by The14me** [comment]
Got fixed if remember right(cant reproduce too).Please recheck and Pm me if still happen.!

**Comment by Jacksn5** [comment]
Still happening, but might generally be connected to Mind Control Incite Chaos from [Blackheart the Inciter](https://db.excalibur.ws/?npc=20637#controlled-abilities) in Shadow Labs - also after the teleport there seems to be a general melee range problem, you can see me spamming Mangle when getting back to the mob in both cases:
[![Post Fear Teleports Rev 2452](http://img.youtube.com/vi/_jlJysFXhOs/0.jpg)](https://www.youtube.com/watch?v=_jlJysFXhOs "Post Fear Teleports Rev 2452")

**Comment by Tereneckla** [comment]
fixed rev 3234
