### ISSUE TITLE
[NPC] Jaedenar Darkweaver

### ISSUE THREAD

**Issue by Mikik3jr** [Atlantiss/NetherwingBugtracker#1958]
[//]: # (Enclose links to things related to the bug using http://wowhead.com or any other TBC database.)
[//]: # (You can use screenshot ingame to visual the issue.)
[//]: # (Write your tickets according to the format:)
[//]: # ([Quest][Azuremyst Isle] Red Snapper - Very Tasty!)
[//]: # ([NPC] Magistrix Erona)
[//]: # ([Spell][Mage] Fireball)
[//]: # ([Npc][Drop] Ghostclaw Lynx)
[//]: # ([Web] Armory doesnt work)

**Description**: 
In Felwood there are dark casters that cast Immolate.
**Current behaviour**:
[Jaedenar Darkweaver](https://www.wowhead.com/npc=7118/jaedenar-darkweaver#abilities) casts [Immolate](https://www.wowhead.com/spell=11962/immolate) during stun.
**Expected behaviour**: 
They shouldn't cast immolate during stun. Also I am not sure if immolate is an instant spell.
**Server Revision**: 
2229

**Comment by Evolvee** [comment]
rev yummy
