### ISSUE TITLE
[Combat][Wand] Target switching while wanding

### ISSUE THREAD

**Issue by Avatarstate** [Atlantiss/NetherwingBugtracker#196]
[//]: # (Enclose links to things related to the bug using http://wowhead.com or any other TBC database.)
[//]: # (You can use screenshot ingame to visual the issue.)
[//]: # (Write your tickets according to the format:)
[//]: # ([Quest][Azuremyst Isle] Red Snapper - Very Tasty!)
[//]: # ([NPC] Magistrix Erona)
[//]: # ([Spell][Mage] Fireball)
[//]: # ([Npc][Drop] Ghostclaw Lynx)
[//]: # ([Web] Armory doesnt work)

**Description**: 
Target switching while wanding causes the attack to stop working
**Current behaviour**:
Switching targets while wanding causes wand animation to continue but not do damage
**Expected behaviour**:
Switching targets while wanding should cause the wand attacks to attack the new target
**Server Revision**:  2028

**Comment by Scylla420** [comment]
yeah noticed this too, really strange because you still can increase your skill with wands when this happens but it deals no damage

**Comment by Wolffenstein** [comment]
Fixed in rev 2046.
