### ISSUE TITLE
I can attack neutral reputation Timbermaw guards with Holy Shock (without "At War" tick)

### ISSUE THREAD

**Issue by Mikik3jr** [Atlantiss/NetherwingBugtracker#1962]
[//]: # (Enclose links to things related to the bug using http://wowhead.com or any other TBC database.)
[//]: # (You can use screenshot ingame to visual the issue.)
[//]: # (Write your tickets according to the format:)
[//]: # ([Quest][Azuremyst Isle] Red Snapper - Very Tasty!)
[//]: # ([NPC] Magistrix Erona)
[//]: # ([Spell][Mage] Fireball)
[//]: # ([Npc][Drop] Ghostclaw Lynx)
[//]: # ([Web] Armory doesnt work)

**Description**: 
I am not at war with Timbermaw Hold and my reputation is neutral with them.
![wowscrnshot_102918_234206](https://user-images.githubusercontent.com/43505031/47684753-427f7880-dbd4-11e8-9ab8-3a6234d5bb4b.jpg)
**Current behaviour**:
![wowscrnshot_102918_234059](https://user-images.githubusercontent.com/43505031/47684739-385d7a00-dbd4-11e8-8eba-362dd3bc4d57.jpg)
And It doesn't even trigger combat.
**Expected behaviour**: 
I shouldn't be able to attack a neutral reputation NPC when I am not at war with them.
**Server Revision**: 
2229

**Comment by Mikik3jr** [comment]
In this case Timbermaw.

**Comment by Easyfraggy** [comment]
I actually remember something weird with Timbermaw rep faction, being able to attack them untill friendly by default. However they should attack back if that is the case and give combat ofc.

**Comment by Tereneckla** [comment]
Can't cast purely offensive spells at neutral not at war on them.
Holy Shock completely fails
![image](https://user-images.githubusercontent.com/50233983/72204559-b1fc2380-3479-11ea-8562-dbaf73792983.png)
