### ISSUE TITLE
[NPC] Dredge Crusher & Dredge Striker - cannot skin

### ISSUE THREAD

**Issue by ScottieDOESknow** [Atlantiss/NetherwingBugtracker#1963]
**Description**: Dredge Crusher & Dredge Strikers (worms) in Silithus

**Current behaviour**: These are labeled as beast but are currently unskinnable

Dredge Crusher
https://gyazo.com/b11ea0689b2587d840ef8dae2d536ef9

Dredge Striker
https://gyazo.com/2a3c114780ecd20148c14c5c501aecc3

**Expected behaviour**: Should be skinnable. Able to be skinned 3 days prior.

**Server Revision**: 2229

**Comment by ScottieDOESknow** [comment]
Skinned a few other mobs in the area, seems like it's only the worms.

**Comment by ScottieDOESknow** [comment]
https://classicdb.ch/?npc=11741#skinning

**Comment by Shanghi** [comment]
I could be wrong, but I think giant worm creatures became skinnable later. If you can find any evidence of anything they should have (it doesn't have to be the full loot table) then it would be fixed though!

For example with the Dredge Crusher, no skinning loot is listed on [Allakhazam](https://web.archive.org/web/20071231150105/http://wow.allakhazam.com:80/db/mob.html?wmob=11741) (it would be mixed with normal loot), [Thottbot](https://web.archive.org/web/20080501151716/http://thottbot.com:80/c11741) (have to view the source to see it all), or [old Wowhead](https://web.archive.org/web/20080403074405/http://www.wowhead.com:80/?npc=11741) even after hundreds of thousands of records. There's plenty of other things that show skinning loot with under 50 recorded kills. Stock databases have them using a skinning loot table that shouldn't exist and is also used by other strange creatures like spiders or birds.

**Comment by ScottieDOESknow** [comment]
skinnable in vanilla...

https://classicdb.ch/?npc=11741#skinning

**Comment by Shanghi** [comment]
classicdb is a private server database though. That rugged leather/rugged hide loot table is the one I was talking about that you won't be able to find on the retail databases.

**Comment by ScottieDOESknow** [comment]
I specifically remember skinning these mobs for quite some time on original servers for sandworm meat (BiS melee food) and rugged leather / hide (BiS skins) 

Please, point me to a database that you would prefer for reference.

**Comment by Shanghi** [comment]
Allakhazam, Thottbot, Wowhead, or any old skinning guides

**Comment by ScottieDOESknow** [comment]
"I was able to skin these mobs fine until today (Oct 29)"

Btw, what changed in the last 3 days that made these mobs not skinnable? Was any proof brought forth for a change or is this just a bug that you are asking proof to change now that it's an issue?

**Comment by ScottieDOESknow** [comment]
https://www.wowhead.com/npc=11741/dredge-crusher#skinning

**Comment by Shanghi** [comment]
Skinning loot was completely stock until a few days ago and it was all changed at once. There's around 1,200 skinnable creatures and the loot table for every one of them was checked using the archived retail databases. I was surprised about the worms because I thought they were skinnable too, but my memory has been corrupted by private servers so I tried to find any proof of any item at all for them but found nothing! It doesn't make sense for them not to show that skinning loot after hundreds of thousands of kills, but plenty of other things will have skinning loot listed with less than 50 kills.

**Comment by Shanghi** [comment]
Old data is needed! TBC Wowhead would be: https://web.archive.org/web/20080403074405/http://www.wowhead.com:80/?npc=11741
Skinning has changed quite a bit so a modern page can't be used

**Comment by ScottieDOESknow** [comment]
"checked using the archived retail databases."

Could you link me the archived databases that were used for these NPC's ?

**Comment by Shanghi** [comment]
It was the 3 listed before.

Wowhead: https://web.archive.org/web/20080403074405/http://www.wowhead.com:80/?npc=11741
Allakhazam: https://web.archive.org/web/20071231150105/http://wow.allakhazam.com:80/db/mob.html?wmob=11741
Thottbot: https://web.archive.org/web/20080501151716/http://thottbot.com:80/c11741
***
They're not easy to manually use though. Here's an example of something showing skinning loot:

Wowhead: https://web.archive.org/web/20080403074405/http://www.wowhead.com:80/?npc=119
In the big "Related" list you can see Ruined Leather Scraps and Light Leather. The get chances of each you would have to right click and view the page source and find this line:
```
new Listview({template: 'item', id: 'skinning', name: 'Skinning', tabs: tabsRelated, parent: 'lkljbjkb574', extraCols: [Listview.extraCols.count, Listview.extraCols.percent], sort:['-percent', 'name'], computeDataFunc: Listview.funcBox.initLootTable, note: sprintf(LANG.lvnote_npcskinning, 24708), _totalCount: 24708, data: [{id:2934,name:'5Ruined Leather Scraps',level:5,source:[2],classs:7,subclass:6,count:14866,stack:[1,1]},{id:2318,name:'5Light Leather',level:10,source:[1,2],classs:7,subclass:6,count:9843,stack:[1,1]}]});
```
so ruined leather scraps were looted 14866 times out of 24708, so about 60%.

Allakhazam: https://web.archive.org/web/20071231150105/http://wow.allakhazam.com:80/db/mob.html?wmob=119
Thottbot: https://web.archive.org/web/20080501151716/http://thottbot.com:80/c119
On these 2 the skinning items are mixed with regular loot, so you would have to add how many times Ruined Leather Scraps and Light Leather was looted to see how many times it was skinned and then use that total to get the chances of each.

**Comment by ScottieDOESknow** [comment]
Thanks for the links and explanation.

**Comment by Tereneckla** [comment]
As Shanghi said, no skinning loot on them on retail tbc databases
