### ISSUE TITLE
Winterspring patrol makes combatbug

### ISSUE THREAD

**Issue by Mikik3jr** [Atlantiss/NetherwingBugtracker#1965]
[//]: # (Enclose links to things related to the bug using http://wowhead.com or any other TBC database.)
[//]: # (You can use screenshot ingame to visual the issue.)
[//]: # (Write your tickets according to the format:)
[//]: # ([Quest][Azuremyst Isle] Red Snapper - Very Tasty!)
[//]: # ([NPC] Magistrix Erona)
[//]: # ([Spell][Mage] Fireball)
[//]: # ([Npc][Drop] Ghostclaw Lynx)
[//]: # ([Web] Armory doesnt work)

**Description**: 
I noticed that there are furbolg patrols on the road in Winterspring.
**Current behaviour**:
They don't attack you:
![wowscrnshot_102918_234737](https://user-images.githubusercontent.com/43505031/47685084-8c1c9300-dbd5-11e8-894c-a95caf1cd9cd.jpg)
You remain in combat if you attack them, then run away:
![wowscrnshot_102918_234806](https://user-images.githubusercontent.com/43505031/47685101-950d6480-dbd5-11e8-9887-a699a39bf8c4.jpg)
You remain in combat even after you kill them (npc info left to right):
![wowscrnshot_102918_235026](https://user-images.githubusercontent.com/43505031/47685122-a5254400-dbd5-11e8-86df-316f974f1307.jpg)

**Expected behaviour**: 
Aggressive patrols should attack me, uppon running away I should not be in combat.
**Server Revision**: 
2229

**Comment by Evolvee** [comment]
they shouldnt be aggresive

that is working as intended

**Comment by Evolvee** [comment]
![image](https://user-images.githubusercontent.com/1942409/47687333-09e59c00-dbe0-11e8-8f3b-07c38c70974a.png)

**Comment by Mikik3jr** [comment]
Sorry then.

But I attacked one of them then ran away. After they went back I was still in combat. I killed them and I was still in combat. After ALT+F4 I didn't die.

**Comment by The14me** [comment]
Work fine now(out of combat)
