### ISSUE TITLE
[Quest] Guardians of the Altar

### ISSUE THREAD

**Issue by Neophrone** [Atlantiss/NetherwingBugtracker#1966]
[//]: # (Enclose links to things related to the bug using http://wowhead.com or any other TBC database.)
[//]: # (You can use screenshot ingame to visual the issue.)
[//]: # (Write your tickets according to the format:)
[//]: # ([Quest][Azuremyst Isle] Red Snapper - Very Tasty!)
[//]: # ([NPC] Magistrix Erona)
[//]: # ([Spell][Mage] Fireball)
[//]: # ([Npc][Drop] Ghostclaw Lynx)
[//]: # ([Web] Armory doesnt work)

**Description**: Escort mob during his way to the end point returned few times to the start of his way, also if u'll not light the lighter during escort mob channeling spell fast, quest can bug, and u have to start quest again. It happened to me, couse I were fighting mob, and didn't light torch for a 15 secs or so.

**Current behaviour**: Wrong pathing of escort quest mob, a chance to stack if u didn't light the torch to fast enough. 

**Expected behaviour**: Escort mob should follow his way to the end of quest, escort mob should channel spell until player will light a torch.

**Server Revision**: 2229.

**Comment by Searcher314** [comment]
Escort seemed Ok, I'm not saying that 100% but idk it seemed fine to me. When I got to the very end at the Altar of Elune I couldn't click on it to activate it, so I wasn't able to complete the quest.

**Comment by DragunovUA** [comment]
broken from October, wtf guys

**Comment by leeviathan** [comment]
This quest is bugged but not how it's described in the initial report anymore. The NPC paths correctly, allows enough time for the lighting of each torch (and tells the player to do so), and attacks mobs appropriately.

However, the last bit of the quest is still broken; when Ranshalla gets to the Altar of Elune and instructs the player to light it while she channels her spell (just like the previous torches), clicking the Altar (which has a gold gear) does nothing. Here's a video of what's supposed to happen when the player clicks the Altar: https://www.youtube.com/watch?v=lemc6SKROJQ

**Comment by Evolvee** [comment]
https://github.com/Atlantiss/NetherwingBugtracker/issues/4299
