### ISSUE TITLE
Pet tame completion animation

### ISSUE THREAD

**Issue by KevinTyrrell** [Atlantiss/NetherwingBugtracker#1968]
[//]: # (Enclose links to things related to the bug using http://wowhead.com or any other TBC database.)
[//]: # (You can use screenshot ingame to visual the issue.)
[//]: # (Write your tickets according to the format:)
[//]: # ([Quest][Azuremyst Isle] Red Snapper - Very Tasty!)
[//]: # ([NPC] Magistrix Erona)
[//]: # ([Spell][Mage] Fireball)
[//]: # ([Npc][Drop] Ghostclaw Lynx)
[//]: # ([Web] Armory doesnt work)

**Description**: 
Pet taming has an incorrect animation/effect/interaction.

**Current behaviour**:
[Twitch Clip](https://clips.twitch.tv/AbstruseSecretiveHabaneroNononoCat)

The tamed mob dies, disappears a few frames later, and a new pet is spawned in.

**Expected behaviour**: 
[Video Evidence](https://youtu.be/YcEqpVfrE7U?list=PLMeJnlp72R7p-X7PgsMFqqjPtcxhF7kB_&t=3193)

The pet does not despawn/die/spawn in but instead 'becomes' passive with a white/blue effect similar to having its loyalty increase.

**Server Revision**: 
2229

**Comment by Manaci** [comment]
Fixed in rev 2389
