### ISSUE TITLE
Deadmines Door LOS

### ISSUE THREAD

**Issue by KevinTyrrell** [Atlantiss/NetherwingBugtracker#1969]
[//]: # (Enclose links to things related to the bug using http://wowhead.com or any other TBC database.)
[//]: # (You can use screenshot ingame to visual the issue.)
[//]: # (Write your tickets according to the format:)
[//]: # ([Quest][Azuremyst Isle] Red Snapper - Very Tasty!)
[//]: # ([NPC] Magistrix Erona)
[//]: # ([Spell][Mage] Fireball)
[//]: # ([Npc][Drop] Ghostclaw Lynx)
[//]: # ([Web] Armory doesnt work)

**Description**: 
Door into the second main room of Deadmines has improper line of sight (this may not be an isolated issue).

**Current behaviour**:
[Twitch Clip](https://clips.twitch.tv/SpoopyNiceMarjoramBudStar)

**Expected behaviour**: 
The open door should not impede line of sight. The pet should also be able to find a path through the open door.

**Server Revision**: 
2229

**Comment by Wolffenstein** [comment]
I can't seem to be able to reproduce it. It must have been some weird sync issue (after a crash perhaps)? It's not causing this error to me at the moment.

**Comment by The14me** [comment]
cant reproduce too. As Wolf say it may be de-sync issue after crash.Please re-test and if happen again PM to re-open.
