### ISSUE TITLE
Deadmines Patrol - Inaccurate Patrol Route?

### ISSUE THREAD

**Issue by KevinTyrrell** [Atlantiss/NetherwingBugtracker#1970]
[//]: # (Enclose links to things related to the bug using http://wowhead.com or any other TBC database.)
[//]: # (You can use screenshot ingame to visual the issue.)
[//]: # (Write your tickets according to the format:)
[//]: # ([Quest][Azuremyst Isle] Red Snapper - Very Tasty!)
[//]: # ([NPC] Magistrix Erona)
[//]: # ([Spell][Mage] Fireball)
[//]: # ([Npc][Drop] Ghostclaw Lynx)
[//]: # ([Web] Armory doesnt work)

**Description**: 
The patrol in deadmines does not walk down into the Goblin Foundry and beyond.

**Current behaviour**:
[Twitch Clip](https://clips.twitch.tv/PiliableFunPicklesJKanStyle)

The patrol (patrols?) spawned when a boss (just one? or multiple?) dies do not patrol beyond the goblin foundry (just THAT patrol, or the other ones too?).

**Expected behaviour**: 
I was not able to find any proof of the patrols in deadmines and where their pathing extends to. I was under the impression that a patrol pack spawns (somewhere near the beginning of the dungeon) every time you kill the Ogre, the Shredder, or the Forgemaster bosses and walks all the way down to the canon. I swear I have been killed by patrols that walk all the way down to the canon area. I've looked through many videos though and none of them go for long enough to show the patrols trailing behind the groups.

**Server Revision**:

**Comment by Easyfraggy** [comment]
This patrol did go all the way down, no idea how / why it was changed?

**Comment by aresbrutus** [comment]
Working just fine for me. Reply here or PM me if you want this to be re-opened.

https://gfycat.com/BrokenGiftedDutchshepherddog
