### ISSUE TITLE
Deadmines - Mr. Smite Inaccurate Animations

### ISSUE THREAD

**Issue by KevinTyrrell** [Atlantiss/NetherwingBugtracker#1971]
[//]: # (Enclose links to things related to the bug using http://wowhead.com or any other TBC database.)
[//]: # (You can use screenshot ingame to visual the issue.)
[//]: # (Write your tickets according to the format:)
[//]: # ([Quest][Azuremyst Isle] Red Snapper - Very Tasty!)
[//]: # ([NPC] Magistrix Erona)
[//]: # ([Spell][Mage] Fireball)
[//]: # ([Npc][Drop] Ghostclaw Lynx)
[//]: # ([Web] Armory doesnt work)

**Description**: 
Mr. Smite in the Deadmines has a few inaccuracies when it comes to his animations.

**Current behaviour**:
[Twitch Clip](https://clips.twitch.tv/BoredWimpyChickpeaRedCoat)

Phase 1: Mr. Smite walks to chest correctly, but turns around and is in attack-stance towards the player character, then turns around again, does not kneel, and changes weapons.
Phase 2: Mr. Smite walks to chest correctly, kneels down at chest, equips [Smite's Hammer] but forgets to remove his dual axes. They are present on his body for the rest of the encounter & death.

**Expected behaviour**: 
[Video Evidence](https://youtu.be/PY7frfcqvvw?t=79)

Phase 1 & 2: Mr. Smite walks to chest, kneels at chest, and changes weapons.

**Server Revision**: 
2229

**Comment by Wolffenstein** [comment]
Fixed in rev 2263.
