### ISSUE TITLE
Pet Evade Bugged In Water

### ISSUE THREAD

**Issue by KevinTyrrell** [Atlantiss/NetherwingBugtracker#1974]
[//]: # (Enclose links to things related to the bug using http://wowhead.com or any other TBC database.)
[//]: # (You can use screenshot ingame to visual the issue.)
[//]: # (Write your tickets according to the format:)
[//]: # ([Quest][Azuremyst Isle] Red Snapper - Very Tasty!)
[//]: # ([NPC] Magistrix Erona)
[//]: # ([Spell][Mage] Fireball)
[//]: # ([Npc][Drop] Ghostclaw Lynx)
[//]: # ([Web] Armory doesnt work)

**Description**: 
[Twitch Clip](https://clips.twitch.tv/CoySlipperyPanTooSpicy)

I had a strange moment when I kited a few enemies into water. The problems begin in [this frame](https://i.imgur.com/qj92Gdq.png) of the video. The mob attempts to reach my pet by swimming downwards into the water, when in fact my pet is at the surface. I commanded my pet to attack the pirate, but he was unable to and didn't move. My pet somehow becomes evade bugged, causing mend pet to evade, and also causing the pirate chasing the pet to get stuck in a loop where I'm able to DPS him to zero without any resistance.

If I figured out a way to reproduce this, it could possibly be abused for exploration purposes. I'm not quite sure why my pet began evading though.

Somehow my pet went back to normal, then had to SWIM DOWN to the bottom, then sprint up the sand incline to reach shore again. It makes me feel like maybe somehow the pet didn't believe it was swimming, as if it was floating in the air (in which case the pet would first touch the ground, then seek the target). Very strange.

**Current behaviour**:
(clip above)

**Expected behaviour**: 
N/A

**Server Revision**:

**Comment by Easyfraggy** [comment]
if you manage to recreate it more than just once in a blue moon ill increase the priority.

**Comment by The14me** [comment]
Was core fixed before a month +- .Cant reproduce it anymore.Please if happen again PM to re-open it.
