### ISSUE TITLE
[NPC][Swamp of Sorrow] Katar

### ISSUE THREAD

**Issue by eryczek1615** [Atlantiss/NetherwingBugtracker#1975]
**Description**: 
[Katar](https://www.wowhead.com/npc=5593/katar)

**Current behaviour**:
He has random movement

**Expected behaviour**: 
He should stand in one place
According to this [Video](https://youtu.be/s14G2JdLh6Y?t=8496)

**Server Revision**: 
2229

**Comment by Tenoutoften** [comment]
Has a picture of him in wrath on wowhead standing in similar positioning:
https://www.wowhead.com/npc=5593/katar#comments

**Comment by aresbrutus** [comment]
Fixed in rev `Eris`
