### ISSUE TITLE
[NPC] Syndicate Highwayman

### ISSUE THREAD

**Issue by Fenvarien1** [Atlantiss/NetherwingBugtracker#1976]
**Description**: 
-Arathi Highlands around Northfold Manor-
NPC Syndicate Highwayman having 2 different types of stealth-buff. Others do not.

**Current behaviour**:
https://imgur.com/a/wcsJq8i
Screenshot of 2 diff types of Syndicate Highwayman. One Highwayman using only their ability 'sneak' the other having the buff 'stealth' as addition to 'sneak'

**Expected behaviour**: 
http://db.hellfire-tbc.com/?npc=2586#abilities
as of his abilities i expect the mob only using 'sneak'

**Server Revision**:

**Comment by Evolvee** [comment]
rev asd
