### ISSUE TITLE
Deserter Lieutenant ignoring CC.

### ISSUE THREAD

**Issue by Haiwuu** [Atlantiss/NetherwingBugtracker#1977]
[NPC] Deserter Lieutenant 23637

**Description**: Deserter Lieutenant will cast shield bash while crowd controlled or beyond its intended range

**Current behaviour**: The NPC casts shield bash while under CC / out of range

**Expected behaviour**:  The NPC should not be able to cast shield bash outside of melee range or while under CC

**Server Revision**: 2229

https://i.imgur.com/82rP1Lb.jpg

**Comment by Evolvee** [comment]
rev asd
