### ISSUE TITLE
[Scarlet Monastery] Scarlet Gallant should run away in fear

### ISSUE THREAD

**Issue by Azalen** [Atlantiss/NetherwingBugtracker#1978]
**Description**: 
Scarlet Gallant (https://classicdb.ch/?npc=4287) isn't running away in fear but should do so.
Proof: https://youtu.be/liWbjzoeQt4?t=22

**Server Revision**: 
[2229]

**Comment by Tenoutoften** [comment]
Yeah it's only a chance

**Comment by Azalen** [comment]
On Netherwing they all run away in fear though, don't they?

**Comment by Evolvee** [comment]
how much % would u say

**Comment by Evolvee** [comment]
setting 50% for now

**Comment by Evolvee** [comment]
rev asd
