### ISSUE TITLE
[Spell] Mark of the Wild cannot be cast on a player with Arcane intellect and/or Frost Armor active.

### ISSUE THREAD

**Issue by Dosdaltherir** [Atlantiss/NetherwingBugtracker#198]
**Description**: 
Mark of the Wild cannot be cast on a player with Arcane Intellect and/or Frost Armor active.
**Current behaviour**: 
Attempting to cast Mark of the Wild on a player with Arcane Intellect and/or Frost Armor active will give off the error message "a more powerful spell is already active".
**Expected behaviour**: 
Mark of the wild should be able to be cast on a player with either and/or both Arcane Intellect and Frost Armor active.
**Server Revision**:
2028

**Comment by Evolvee** [comment]
@Wolffenstein aura stacking

**Comment by Tinnoan** [comment]
it seems it checks for an armor buff, I've tried it on a priest with inner fire on as well and it didn't work there either

**Comment by Wolffenstein** [comment]
Fixed in rev 2067.
