### ISSUE TITLE
[NPC][Quest] Homing Robot OOX-17/TN does not enter combat with enemy NPCs.

### ISSUE THREAD

**Issue by KevinTyrrell** [Atlantiss/NetherwingBugtracker#1985]
[//]: # (Enclose links to things related to the bug using http://wowhead.com or any other TBC database.)
[//]: # (You can use screenshot ingame to visual the issue.)
[//]: # (Write your tickets according to the format:)
[//]: # ([Quest][Azuremyst Isle] Red Snapper - Very Tasty!)
[//]: # ([NPC] Magistrix Erona)
[//]: # ([Spell][Mage] Fireball)
[//]: # ([Npc][Drop] Ghostclaw Lynx)
[//]: # ([Web] Armory doesnt work)

**Description**: '
NPC----
Homing Robot OOX-17/TN
Entry: 7784, Id: 1, GUIDLow: 94325

Quest: Rescue OOX-17/TN!

**Current behaviour**:
[Twitch Clip](https://clips.twitch.tv/BoringDifferentEmuImGlitch)

The robot does not have enemies aggro onto him, does not assist the player, and will walk directly on his path without stopping. He DOES however spawn mobs, though the number of mobs spawned does not seem accurate.

**Expected behaviour**: 
The robot should be hostile to all enemy mobs.

**Server Revision**: 
2229

**Comment by Easyfraggy** [comment]
https://github.com/Atlantiss/NetherwingBugtracker/issues/1114
