### ISSUE TITLE
Hellfire Other factions flight path master shows green !

### ISSUE THREAD

**Issue by Tenoutoften** [Atlantiss/NetherwingBugtracker#1986]
**Description**: 
![746c4260a9f7eb642d74103323b3ec7a](https://user-images.githubusercontent.com/34839199/47748890-23442200-dc8c-11e8-91d9-db17cbe1499e.png)
Other factions flight path master([[NPC]Amish Wildhammer#18931](https://db.excalibur.ws/?npc=18931)) shows green ! Probably shouldn't.

**Expected behaviour**: 
Excepted to not have ! over his head.

**Server Revision**: 
2237

**Comment by Tenoutoften** [comment]
https://github.com/Atlantiss/NetherwingBugtracker/issues/1994

**Comment by Evolvee** [comment]
2238
