### ISSUE TITLE
[NPC] Melgromm Highmountain can attack alliance players despite being a neutral mob

### ISSUE THREAD

**Issue by zauru7** [Atlantiss/NetherwingBugtracker#1987]
[//]: # (Enclose links to things related to the bug using http://wowhead.com or any other TBC database.)
[//]: # (You can use screenshot ingame to visual the issue.)
[//]: # (Write your tickets according to the format:)
[//]: # ([Quest][Azuremyst Isle] Red Snapper - Very Tasty!)
[//]: # ([NPC] Magistrix Erona)
[//]: # ([Spell][Mage] Fireball)
[//]: # ([Npc][Drop] Ghostclaw Lynx)
[//]: # ([Web] Armory doesnt work)

**Description**: 
https://www.wowhead.com/npc=18969/melgromm-highmountain#comments at the stairs at The Stairs of Destiny by the dark portal can attack alliance players with Earth Shock if engaged in combat with same target as him(that's when it triggred for me at least)
![one](https://user-images.githubusercontent.com/44526051/47749674-e8db8480-dc8d-11e8-931c-7b136df14f0e.PNG)
![two](https://user-images.githubusercontent.com/44526051/47749687-eda03880-dc8d-11e8-8a3c-2fd8f826f074.PNG)

**Current behaviour**:
Can attack alliance players
**Expected behaviour**: 
Should not be able to damage players
**Server Revision**: 
2237

**Comment by Evolvee** [comment]
2238 revision
