### ISSUE TITLE
Stonescythe Alpha/Whelp should become unstock after Desperate Defense expires

### ISSUE THREAD

**Issue by Tenoutoften** [Atlantiss/NetherwingBugtracker#1988]
**Description**: 
[[NPC]Stonescythe Alpha](https://db.excalibur.ws/?npc=16929)
[[NPC]Stonescythe Whelp](https://db.excalibur.ws/?npc=16927)
Remain stuck even after their [[Spell]Desperate Defense#33896](https://db.excalibur.ws/?spell=33896) has expired. Should become free to move

**Expected behaviour**: 
Expected to be free to move after [[Spell]Desperate Defense#33896](https://db.excalibur.ws/?spell=33896)  expires

**Server Revision**: 
2237

**Comment by Evolvee** [comment]
2238
