### ISSUE TITLE
Bonechewer Scavenger

### ISSUE THREAD

**Issue by Erodraeda** [Atlantiss/NetherwingBugtracker#1989]
[//]: # (Enclose links to things related to the bug using http://wowhead.com or any other TBC database.)
[//]: # (You can use screenshot ingame to visual the issue.)
[//]: # (Write your tickets according to the format:)
[//]: # ([Quest][Azuremyst Isle] Red Snapper - Very Tasty!)
[//]: # ([NPC] Magistrix Erona)
[//]: # ([Spell][Mage] Fireball)
[//]: # ([Npc][Drop] Ghostclaw Lynx)
[//]: # ([Web] Armory doesnt work)

**Description**: 
The NPC (18952) is using his throw ability from melee range, dealing increased damage because of it.
**Current behaviour**:
Using ranged ability while in melee
**Expected behaviour**: 
Should only autoattack and use melee abilities.
**Server Revision**:

**Comment by Tenoutoften** [comment]
His throw doesn't have a minimum range
https://www.wowhead.com/npc=18952/bonechewer-scavenger#comments
![cd3045f80808c7d4be4a54038b7e2a74](https://user-images.githubusercontent.com/34839199/48513192-7f49a180-e85b-11e8-8d8f-3440b04efb4a.png)
![ce0f271a5c1a90950e4de171bbb30cc4](https://user-images.githubusercontent.com/34839199/48513193-7fe23800-e85b-11e8-81b0-036add62123d.png)

**Comment by Evolvee** [comment]
Seems no longer valid. Please retest/reopen if the issue persists.
