### ISSUE TITLE
Player does not rotate to face the target

### ISSUE THREAD

**Issue by narayagh** [Atlantiss/NetherwingBugtracker#199]
[//]: # (Enclose links to things related to the bug using http://wowhead.com or any other TBC database.)
[//]: # (You can use screenshot ingame to visual the issue.)
[//]: # (Write your tickets according to the format:)
[//]: # ([Quest][Azuremyst Isle] Red Snapper - Very Tasty!)
[//]: # ([NPC] Magistrix Erona)
[//]: # ([Spell][Mage] Fireball)
[//]: # ([Npc][Drop] Ghostclaw Lynx)
[//]: # ([Web] Armory doesnt work)

**Description**: 
If I remember correctly, when the player is not facing the target and starts casting, he should start slowly rotating to face the target. It doesn't work right now.

**Current behaviour**:
Player does not start to rotate. See here: http://sendvid.com/mm8zp10g

**Expected behaviour**: 
Player should start to rotate to face the target.

**Server Revision**:

**Comment by Evolvee** [comment]
thats only for channeled beam spells

**Comment by narayagh** [comment]
Found some hard evidence, how can I reopen the issue and add it?

**Comment by Evolvee** [comment]
comment in here^^

**Comment by narayagh** [comment]
These videos are from my TBC days - hopefully it's clear enough :)

http://sendvid.com/zi5l9t76
http://sendvid.com/16ij1q86
http://sendvid.com/esnr03o3

**Comment by SwiftieTBC** [comment]
This isnt the case. as seen in the video you are holding right click and moving your character. you can tell this as your cursor disappears as it should when holding right click

**Comment by narayagh** [comment]
I might have hold the right button but I did not rotate my character manually, I'm sure of that. Notice how my character slowly, smoothly rotates - this is not done using a key.

**Comment by SwiftieTBC** [comment]
Okay look this is starting to get frustrating so ima post proof of it working correctly on netherwing using right click and then this is getting closed.
https://clips.twitch.tv/WittyHeadstrongMangetoutMcaT
As you can see the player starts to rotate once the right click is removed(cursor appears) matching your retail vids.
this has everything to do with you holding right click and the facing correction is working correctly. this never applied on running at a 90 degree angle and turning you to face the target outside of channeled spells

**Comment by narayagh** [comment]
First of all I don't like your tone.
Second - in the video you linked it looks exactly like it should look. I don't know if something was changed on NW during the last 4 months or not but now it looks fine to me.

I'm closing the issue.
