### ISSUE TITLE
Bonechewer Scavanger

### ISSUE THREAD

**Issue by Mewmewww** [Atlantiss/NetherwingBugtracker#1990]
[//]: # (Enclose links to things related to the bug using http://wowhead.com or any other TBC database.)
[//]: # (You can use screenshot ingame to visual the issue.)
[//]: # (Write your tickets according to the format:)
[//]: # ([Quest][Azuremyst Isle] Red Snapper - Very Tasty!)
[//]: # ([NPC] Magistrix Erona)
[//]: # ([Spell][Mage] Fireball)
[//]: # ([Npc][Drop] Ghostclaw Lynx)
[//]: # ([Web] Armory doesnt work)

**Description**: 
Follows player, evades and doesnt attack. (Many of them evades)
**Current behaviour**:
Follows player, evades and doesnt attack.
**Expected behaviour**: (18952 Entry, Id 18, Guidlow, 59693
Opposite of that.
**Server Revision**: 
2237

**Comment by Easyfraggy** [comment]
We need some way to recreate this problem!

**Comment by The14me** [comment]
Cant reproduce,Please check and if happen again bring some proof or steps how to reproduce and will re-open it.
