### ISSUE TITLE
Bonechewer Scavanger follows and changes follow target

### ISSUE THREAD

**Issue by Dubmandeep** [Atlantiss/NetherwingBugtracker#1992]
**Description**: 

Bonchewer Scavenger followed me after agroing on a slope. Lasted for a few minutes. Could mount up. Then it stopped following me and followed a Mage I helped out, once combat was over for both of us.

**Current behaviour**:
NPC follows you like a pet but you're not in combat. Switches follow target.

**Expected behaviour**: 
Not above.

**Server Revision**:

**Comment by Easyfraggy** [comment]
https://github.com/Atlantiss/NetherwingBugtracker/issues/1990
