### ISSUE TITLE
[Quest] Mission: The Murketh and Shaadraz Gateways

### ISSUE THREAD

**Issue by Needorfeed** [Atlantiss/NetherwingBugtracker#1993]
[//]: # [Quest] Mission: The Murketh and Shaadraz Gateways

**Description**: 
No hit is registered with dropping bombs on either of the portal.

**Current behaviour**:
No hit is registered with dropping bombs on either of the portal.

**Expected behaviour**: 
Should get 1/1, from 2 portals, dropping bombs in flight.

**Server Revision**:

**Comment by Easyfraggy** [comment]
Can someone confirm? Seems most people completed this without a problem.

**Comment by Needorfeed** [comment]
Sophiett and Crasw both have the same problem.

**Comment by Needorfeed** [comment]
Never mind that. It works on the third try.

**Comment by Needorfeed** [comment]
Might have been a internal cooldown

**Comment by Mikik3jr** [comment]
I had to fly 5 times to finish the quest. I got 1 credit, but after the 5th try I could get the othercredit.

**Comment by ezzekielfox** [comment]
I think this is a range issue. Got em both second try when I did it much closer.

**Comment by Xynaps** [comment]
It worked for me the second time, tossed the bomb at roughly the same range. The difference was no active burning animation on the gates.

**Comment by wowthings** [comment]
No credit if I launch the bomb if I'm near the gate, if it's because there's an internal cooldown it will be annoying if there's traffic with the alli and horde flying around trying to get the credit.

**Comment by aresbrutus** [comment]
WAs fixed in rev `2246`
