### ISSUE TITLE
[NPC] Amish  Wildhammer showing FP discovery for Horde characters

### ISSUE THREAD

**Issue by KevinTyrrell** [Atlantiss/NetherwingBugtracker#1994]
[//]: # (Enclose links to things related to the bug using http://wowhead.com or any other TBC database.)
[//]: # (You can use screenshot ingame to visual the issue.)
[//]: # (Write your tickets according to the format:)
[//]: # ([Quest][Azuremyst Isle] Red Snapper - Very Tasty!)
[//]: # ([NPC] Magistrix Erona)
[//]: # ([Spell][Mage] Fireball)
[//]: # ([Npc][Drop] Ghostclaw Lynx)
[//]: # ([Web] Armory doesnt work)

**Description**: 
NPC Info: Entry: 18931, Id: 1, GUIDLow: 28726

**Current behaviour**:
[Screenshot](https://i.imgur.com/MaKJpAk.png)

Amish offers a flight path to horde players (shows on minimap as well). However interacting with him does nothing.

**Expected behaviour**: 
Amish should offer nothing to horde players.

**Server Revision**: 
2237

**Comment by ircfelix** [comment]
confirmed.

**Comment by Easyfraggy** [comment]
https://github.com/Atlantiss/NetherwingBugtracker/issues/1986
