### ISSUE TITLE
Wrathguard

### ISSUE THREAD

**Issue by Erodraeda** [Atlantiss/NetherwingBugtracker#1995]
[//]: # (Enclose links to things related to the bug using http://wowhead.com or any other TBC database.)
[//]: # (You can use screenshot ingame to visual the issue.)
[//]: # (Write your tickets according to the format:)
[//]: # ([Quest][Azuremyst Isle] Red Snapper - Very Tasty!)
[//]: # ([NPC] Magistrix Erona)
[//]: # ([Spell][Mage] Fireball)
[//]: # ([Npc][Drop] Ghostclaw Lynx)
[//]: # ([Web] Armory doesnt work)

**Description**: 
The NPC's ability Flame Wave is ticking too fast, doing more damage than it should.
NPC: 18975
**Current behaviour**:
![screenshot_657](https://user-images.githubusercontent.com/40346279/47752674-e9672180-dc73-11e8-81dc-cf9c3bf2ade3.png)
**Expected behaviour**: 
Shouldn't do damage that often.
**Server Revision**:

**Comment by Easyfraggy** [comment]
It shouldn't chase you, that's the problem. dmg is correct.

**Comment by killablink** [comment]
![image](https://user-images.githubusercontent.com/43510874/47761558-46bc9c00-dc8f-11e8-8bf5-edc12b79d09b.png)

There are a few comments saying that the damage is around 250 per tick, not even close to 688 dmg a tick, I don't think the damage is correct.
