### ISSUE TITLE
[Spell]Hellfire Superiority#32049 should reapply when you ressurect

### ISSUE THREAD

**Issue by Tenoutoften** [Atlantiss/NetherwingBugtracker#1996]
**Description**: 
After my friend died, and I resurrected him in Hellfire it seems like [[Spell]Hellfire Superiority#32049](https://db.excalibur.ws/?spell=32049) doesn't reapply ([[Spell]Hellfire Superiority#32071](https://db.excalibur.ws/?spell=32071) - alliance version)

Picture of me with the buff while my friend doesn't have it
![d20a6b909a5afb12c29bc1b8e7c9c0ac](https://user-images.githubusercontent.com/34839199/47752825-d82f0c80-dc95-11e8-9ab4-a203902ce760.jpg)

**Expected behaviour**: 
Expected to be reapplied when you ressurect

**Server Revision**: 
2237

**Comment by Wolffenstein** [comment]
Fixed in rev 3343.
