### ISSUE TITLE
[npc]Thrallmar Wolf Rider

### ISSUE THREAD

**Issue by ircfelix** [Atlantiss/NetherwingBugtracker#1998]
**Description**: 
Those Wolves ride too fast. It feels utterly wrong.

**Current behaviour**:
Those Wolves ride super fast.

**Expected behaviour**: 
Those Wolves should ride slower.

**Server Revision**: 
2237

**Comment by Evolvee** [comment]
proof? afaik its how it is on retail

**Comment by Cptnlobbe** [comment]
I reacted on this aswell, they should go about half of current speed. No proof :)

**Comment by Kuumi** [comment]
https://www.youtube.com/watch?v=2oZ_LiV9rs0 Fast foward to 1:47:17 and it shows the speed of the wolf riders, its quick but you can compare it to netherwing speed while in game

**Comment by Kuumi** [comment]
Again at 2:05:44 it looks like their speed is at normal 100% mount speed there. Hard to tell from the brief moments the guy catches them on camera

**Comment by ttghnw** [comment]
Some Honor >Hold riders are also too fast

**Comment by Sunlancer** [comment]
In addition to going too fast, the Honor Hold cavalry also stop slightly at every turn

**Comment by ircfelix** [comment]
Kor'kon riders outside of Shadowmoon Village in Shadowmoon Valley also move extremely fast.

**Comment by Tereneckla** [comment]
Fixed
