### ISSUE TITLE
[Quest][Hellfire Peninsula] Mission: The Abyssal Shelf

### ISSUE THREAD

**Issue by Mikik3jr** [Atlantiss/NetherwingBugtracker#1999]
[//]: # (Enclose links to things related to the bug using http://wowhead.com or any other TBC database.)
[//]: # (You can use screenshot ingame to visual the issue.)
[//]: # (Write your tickets according to the format:)
[//]: # ([Quest][Azuremyst Isle] Red Snapper - Very Tasty!)
[//]: # ([NPC] Magistrix Erona)
[//]: # ([Spell][Mage] Fireball)
[//]: # ([Npc][Drop] Ghostclaw Lynx)
[//]: # ([Web] Armory doesnt work)

**Description**: 
[In this quest](https://www.wowhead.com/quest=10163/mission-the-abyssal-shelf#comments) you get a bomb and you have to fly and bomb the enemies down.
**Current behaviour**:
When you throw a bomb, but you get too far away before it lands you don't get the credit for the kills.
**Expected behaviour**: 
I think you should get it. Not sure, but I report this just in case. I haven't read anything like this in comments.
**Server Revision**: 
2237

**Comment by KevinTyrrell** [comment]
Can you provide screenshots / video to show exactly what's happening?

**Comment by KevinTyrrell** [comment]
@Easyfraggy Here is footage (not mine) [from the defunct Corecraft](https://youtu.be/hz4h6nSlhm0?t=262) where the problem appears to be solved. Not sure if this will be of assistance though. I know there source code is open source now though.

**Comment by Mikik3jr** [comment]
https://www.youtube.com/watch?v=kXd4Ep5XqEc&feature=youtu.be

**Comment by Baelek** [comment]
This issue is still ongoing as of rev 3140. You have to practically be ontop of the mobs to get credit.
