### ISSUE TITLE
Cannot revive

### ISSUE THREAD

**Issue by AlteredAli** [Atlantiss/NetherwingBugtracker#20]
[//]: # (Enclose links to things related to the bug using http://wowhead.com or any other TBC database.)
[//]: # (You can use screenshot ingame to visual the issue.)
[//]: # (Write your tickets according to the format:)
[//]: # ([Quest][Azuremyst Isle] Red Snapper - Very Tasty!)
[//]: # ([NPC] Magistrix Erona)
[//]: # ([Spell][Mage] Fireball)
[//]: # ([Npc][Drop] Ghostclaw Lynx)
[//]: # ([Web] Armory doesnt work)

**Description**: 
Test died to mobs, ran to corpse and clicked revive, button pressed down and nothing happened, pressed a few more times and nothing happened.
Ran back to spirit healer and the revive worked.
**Current behaviour**:

**Expected behaviour**: 

**Server Revision**:

**Comment by AlteredAli** [comment]
Update on the revive bug, when i revived at the spirit healer, i found my still "unskelefied" corpse at the location with full model and all.

**Comment by towneh** [comment]
Attempted to ressurrect at my corpse, clicking the button did nothing.

Typed /relog and the ressurect window dissapeared entirely after the loading screen.

I then logged off whilst a ghost and waited 20 seconds until i went back to character select. I then logged back on and re-appeared in the game world alive.

**Comment by wtRCH** [comment]
Fixed
