### ISSUE TITLE
[quest object] particles effect on a wanted poster.

### ISSUE THREAD

**Issue by Dosdaltherir** [Atlantiss/NetherwingBugtracker#200]
![wowscrnshot_092318_161921](https://user-images.githubusercontent.com/43515247/45929093-5688e800-bf4d-11e8-82b9-dfacbb8690c5.jpg)

**Description**: 
The wanted poster in Thelsamar Loch Modan is giving off particle effects glowing.
**Current behaviour**:
Particle effects are glowing in a radius around the wanted poster in Thelsamar Loch Modan.
**Expected behaviour**: 
The wanted poster in Thelsamar Loch Modan should not be giving off particle effect glows. Proof:
https://www.wowhead.com/quest=256/wanted-choksul
**Server Revision**: 
2028

**Comment by Evolvee** [comment]
the screenshot could be taken after the quest was accepted/completed etc...
