### ISSUE TITLE
[NPC/Quest] Boiling blood

### ISSUE THREAD

**Issue by Cptnlobbe** [Atlantiss/NetherwingBugtracker#2000]
Description:
For the quest Boiling blood, you need to boil the blood of some felorcs and some scarabs spawns while doing so.

Current behaviour:
These scarabs gives same exp as a normal mob at lvl 58-60, even tho having 400-500hp.

Expected behaviour:
Give way less exp.

Server Revision:
2237

**Comment by Evolvee** [comment]
rev asd
