### ISSUE TITLE
[Spell] Soul Link

### ISSUE THREAD

**Issue by Malices1** [Atlantiss/NetherwingBugtracker#2001]
[//]: # (Enclose links to things related to the bug using http://wowhead.com or any other TBC database.)
[//]: # (You can use screenshot ingame to visual the issue.)
[//]: # (Write your tickets according to the format:)
[//]: # ([Spell][Warlock] Soul Link)

**Description**: Soul Link disappears when you mount and when you dismount.

**Current behaviour**:
Currently when you Soul Link your pet and then mount you lose your Soul Link.

**Expected behaviour**: 
When you summon your pet and use Soul Link then mount you should still have Soul Link. You shouldn't have to reuse Soul Link everytime you mount and then dismount. https://youtu.be/7k30ZBJ23MQ?t=99

**Server Revision**:

**Comment by Tenoutoften** [comment]
Video of pet reappearing as a warlock dismounts: https://www.youtube.com/watch?v=7k30ZBJ23MQ&feature=youtu.be&t=97
Displaying [[Spell]Soul Link#25228](https://db.excalibur.ws/?spell=25228) instantly applying.
[[Spell]Soul Link#19028](https://db.excalibur.ws/?spell=19028) - the spell you have to apply for it to reappear

**Comment by Tereneckla** [comment]
Fixed
