### ISSUE TITLE
Healing generates threat while mobs are hard CC'ed

### ISSUE THREAD

**Issue by Azalen** [Atlantiss/NetherwingBugtracker#2002]
**Description**:
Effective Healing done adds to the threatlist of a hard CC'ed (poly, fear, etc) mob. We encountered this issue today in Hellfire Ramparts for polymorphed targets.

**Expected behaviour**: 
Effective Healing done should not add to the threatlist of a hard CC'ed mob. Expection: Stuns.
Proof: https://vanilla-twinhead.twinstar.cz/?issue=7652 (read the discussion, lots of different proof)

**Server Revision**: 
[2238]

**Comment by Easyfraggy** [comment]
Just tested with ingame command - can confirm:

![image](https://user-images.githubusercontent.com/36134067/48707819-f0dd7300-ec00-11e8-9fa1-3b6150b73ce9.png)

**Comment by Azalen** [comment]
Please give this HIGH-PRIO tag. It is super annoying and you encounter it basically in every dungeon/raid scenario there is.

**Comment by Wolffenstein** [comment]
Fixed in rev 2348.
