### ISSUE TITLE
 ([Spell][Bleeding Hollow Tormentor] Fear)

### ISSUE THREAD

**Issue by killablink** [Atlantiss/NetherwingBugtracker#2003]
**Description**: I got feared by him and when I used Will of the Forsaken to break it instantly, I teleported maybe 10 yards away from where I was initially feared.

**Current behaviour**: I got feared by him and when I used Will of the Forsaken to break it instantly, I teleported maybe 10 yards away from where I was initially feared. (happened only once after server came back up, not sure how to reproduce)

**Expected behaviour**: Should not teleport after breaking fear

**Server Revision**: 
2238

**Comment by Mewmewww** [comment]
#1956 
Duplicate mechanic wise

**Comment by The14me** [comment]
known(fear issue)
