### ISSUE TITLE
[Core] Objects blocking LoS

### ISSUE THREAD

**Issue by killablink** [Atlantiss/NetherwingBugtracker#2004]
**Description**: 
![screenshot_17](https://user-images.githubusercontent.com/43510874/47758102-f12cc300-dc7f-11e8-9a08-060a28dfc347.png) 

These objects are blocking LoS which feel very odd. (Not only this lamp but others) Also feel alot of broken catapults are breaking LoS when they maybe shouldn't.

**Current behaviour**: Blocking LoS

**Expected behaviour**: Probably shouldn't block LoS

**Server Revision**: 
2238

**Comment by Wolffenstein** [comment]
Need proof
