### ISSUE TITLE
Spell Lock and Devour Magic

### ISSUE THREAD

**Issue by genetheparmesan** [Atlantiss/NetherwingBugtracker#2005]
[//]: # (Enclose links to things related to the bug using http://wowhead.com or any other TBC database.)
[//]: # (You can use screenshot ingame to visual the issue.)
[//]: # (Write your tickets according to the format:)
[//]: # ([Quest][Azuremyst Isle] Red Snapper - Very Tasty!)
[//]: # ([NPC] Magistrix Erona)
[//]: # ([Spell][Mage] Fireball)
[//]: # ([Npc][Drop] Ghostclaw Lynx)
[//]: # ([Web] Armory doesnt work)

**Description**: 
[//]: # ([Spell][Felhunter] Devour Magic)
[//]: # ([Spell][Felhunter] Spell Lock)
**Current behaviour**: not responding to macro "/cast Devour Magic" or the macro "/cast Spell Lock" while other abilities like Seduction and Sacrifice do work.

**Expected behaviour**: 
/cast Devour Magic and /cast Spell Lock would cast the spell at the target 

**Server Revision**:

**Comment by Evolvee** [comment]
try /click PetActionBar1
