### ISSUE TITLE
[Quest] [Zangarmarsh] As The Crow Flies - server crash visual bug

### ISSUE THREAD

**Issue by ScottieDOESknow** [Atlantiss/NetherwingBugtracker#2006]
**Description**: As the Crow Flies - quest 9718

Using the Stormcrow Amulet turns player into a crow that flies above Zangarmrash for quest completion.

**Current behaviour**: 

If server crash, upon relog, player is still flying around but without crow transformation.

https://gyazo.com/aed64d49532cd076013e59d768cfb3fc

**Expected behaviour**: Should maintain crow aesthetic even after server crash.

**Server Revision**: 2237 ?

**Comment by aresbrutus** [comment]
We know it looks bad but since it is due to a server crash stuff like this can happen. As long as it does not make your char stuck or prevent you from continuing on it is just a visual thing. We are aiming for no crashes so stuff like this won't happen. Closing it.
