### ISSUE TITLE
[Spell][Shaman] Lightning Overload

### ISSUE THREAD

**Issue by ezzekielfox** [Atlantiss/NetherwingBugtracker#2007]
Description:
//: # ([Spell][Shaman] Lightning Overload)
//: # ([Spell][Shaman] Chain Lightning)
Current behaviour: Proccing off separate jumps in Chain Lightning, causing each jump a chance to re-proc Lightning Overload.

Expected behaviour: Only the main target of Chain Lightning should have a chance to proc Lightning Overload, it's causing too many jumps on multiple targets.

Server Revision:

**Comment by Wolffenstein** [comment]
Proof? As far as I know that's not true and we specifically made it possible for it to proc more than once.

**Comment by The14me** [comment]
as far i know it work like suppose to be.As Wolf say...please bring some proof about that.

**Comment by Tinnoan** [comment]
According to this post it should have a chance to proc of each hit of chain lightning, though this is from WotLK patch 3.2 I doubt it would change to become that later on.

https://wowhats.wordpress.com/2009/10/27/elemental-chain-lightning/

> Each hit also has a chance to proc Lightning Overload Chain Lightning, which fires a half damage Chain Lightning at the target it’s procced off.

this quote is found in the first paragraph under the "Chain Lightning as AoE" section.

**Comment by Retinus** [comment]
If i m not mistaken in this video Chain Lightning proc Lightning Overload at second target. Not sure though

[Lighting Overload](https://www.youtube.com/watch?v=2Qb2vga-CFw)

**Comment by ezzekielfox** [comment]
> If i m not mistaken in this video Chain Lightning proc Lightning Overload at second target. Not sure though
> 
> [Lighting Overload](https://www.youtube.com/watch?v=2Qb2vga-CFw)

That's from old Lightning Overload, when it had a 5% chance to cast same spell, no damage reduction.

I could be mistaken on my initial post, it just seemed too much when I watch it proc half a dozen times when fighting 3 mobs. I'll try to find proof

**Comment by Brasso** [comment]
https://www.youtube.com/watch?v=HirUj6DQjmU
![image](https://user-images.githubusercontent.com/44345420/50168270-52b9f700-02eb-11e9-86d7-9868eea0d8db.png)


![lo](https://user-images.githubusercontent.com/44345420/50168356-89900d00-02eb-11e9-88c5-422cfce38ffa.png)

![lo2](https://user-images.githubusercontent.com/44345420/50168359-8bf26700-02eb-11e9-9b03-110a293f493b.JPG)

![lo3](https://user-images.githubusercontent.com/44345420/50168365-8dbc2a80-02eb-11e9-86dd-947b2a1f91ef.png)

LO crits should act as normal crits and should proc trinket and clearcasting for example:
![lo3](https://user-images.githubusercontent.com/44345420/50168367-8f85ee00-02eb-11e9-9051-95ef317e14d2.JPG)

**Comment by Wolffenstein** [comment]
I removed the ability of LO to proc from itself, because it led to situations where it would often proc way too often and result in way too high damage. It needs to be researched more thoroughly.

**Comment by Brasso** [comment]
The damage of CL and the proc of LO is reduced correctly. BUT, chain lightning has a chance to proc LO from all 3 hits right now, which means that from 1 CL you can get a total of 12 hits, with 9 LO's. But LO is suppose to be able to proc from LO... you can see where this leads to. I am pretty sure LO is suppose to only be able to proc per CAST of chain lightning, as in 20%, and NOT from all three hits.. but I can't find any sources of this. 3 hits from CL procing 9 LO's, and ALL 9 has a chance to proc, as in 9*3 which is 27 hits, and all of those has a chance to proc again, the chance is really low, but it is ridiculously gamebreaking damage


https://i.imgur.com/5qa01hZ.png

**Comment by Tuwz** [comment]
http://wowwiki.wikia.com/wiki/Lightning_Overload?oldid=1547238
If you go on the Wow wiki dated from 25th of July 2008, so 10 days after patch 2.4.3 hit

![image](https://user-images.githubusercontent.com/45247502/50353291-0a4b4500-0548-11e9-9913-502b2c8d35d7.png)

It states that the spells cast thanks to lightning overload behave completely equal to the base spells, so they should be able to proc clearcast and another spell. In extremely rare situations you can get a lot of procs, but it shouldn't be an issue as they're not causing any threat.

**Comment by Aeded** [comment]
Plenty of misinformation in this report, nice.
1. Lightning overload should never proc from LO (completely out of question and waste of time arguing about)

2. Lightning overload should be able to proc from full resisted casts.
https://web.archive.org/web/20080411063147/http://elitistjerks.com:80/699164-post1481.html
Personaly I didnt manage to get LO proc from full resist, so just mentioning that it should be possible.

Lightning overload should be decided upon succesfull spell cast, not spell hit. Means that chain lightning should not have chance to proc LO from each chain hit, as OP correctly reported.

Even though it is not blizzlike, its nice buff to ele shamans, and adds some extra flavor to gameplay so im not really going to try persuade anyone about it ;)

But in case anyone goes "hmm, but how could you prove it". Its quite simple, watch any post 2.3 patch elemental shaman video and everytime you see lightning overload on chain lightning, it always procs into main target and never into the second or even third target hit by chain lightning. Also the frequency of chain lightning proccing LO in videos is rare to find, shouldnt be that hard if every hit had the chance to proc LO?

**Comment by torrenzGH** [comment]
most convincing footage yet
it's plain to see from the direction of the lightning beam on CL that LO can fire at a different target than the original spell, so it procs on jumps
CL rolls LO on up to three hits but never procs more than once per cast, CL+LO is never observed to create more than 6 hits so LO->LO or multiple LO per CL is nonsense

not sure which part of this behavior is broken but it's still rarely possible to get 9 hits from 1 CL on beta 2526. 
![wowscrnshot_123018_012802](https://user-images.githubusercontent.com/45742182/50543272-a245d000-0bd3-11e9-8c62-3e7a87783467.jpg)

**Comment by Brasso** [comment]
There is very limited footage of elemental shamans in dungeons and killing trash in raids. I have watched a lot of bg footage with chain lightning hitting multiple targets, I've never seen it exceed 6 hits (1 LO).

**Comment by Tereneckla** [comment]
https://www.wowhead.com/forums&topic=125058.1#p1470228
https://www.wowhead.com/forums&topic=25609.1#p244969
https://www.wowhead.com/forums&topic=36496.1#p341896
https://www.wowhead.com/forums&topic=177038.1#p2441538

Lightning Overload proccing Lightning Overload seems to have been removed in Cataclysm.
