### ISSUE TITLE
[NPC][Ramparts] Vazruden resetting when spawned

### ISSUE THREAD

**Issue by mr2tal** [Atlantiss/NetherwingBugtracker#2008]
**Description**: Last boss in hellfire ramparts Vazruden resets everytime he is spawned 

**Current behaviour**: https://clips.twitch.tv/CulturedMoistSpiderPunchTrees
EDIT: resets also on horn usage after landing

**Expected behaviour**:  not despawning

**Server Revision**:

**Comment by Wolffenstein** [comment]
Fixed in rev 2241.
