### ISSUE TITLE
Opposing faction Flight Masterin Hellfire Peninsula

### ISSUE THREAD

**Issue by Spaztick** [Atlantiss/NetherwingBugtracker#2009]
**Description**: 
Opposing faction Flight Master at Stair of Destiny in Hellfire Peninsula shows ! above it's head. Possibly more FMs in other locations do the same.

**Expected behaviour**: 
No !

![icon](https://user-images.githubusercontent.com/29140342/47762423-abc1c300-dc8a-11e8-8d76-fb33a3a9e3ef.png)

**Comment by Wolffenstein** [comment]
Fixed in rev 2241.
