### ISSUE TITLE
[Spell] Batch Delay on shapeshifting.

### ISSUE THREAD

**Issue by Dosdaltherir** [Atlantiss/NetherwingBugtracker#201]
**Description**: 
There's a delay when shifting in and out of bear form.
**Current behaviour**:
Shapeshifting in and out of bear form has the same 400ms delay as every other spell.
**Expected behaviour**: 
I believe that this batch delay should only be active on offensive spells or heals. Spells that only affect the caster, such as paladin auras and druid shapeshifting shouldn't have this delay.
**Server Revision**: 
2028

**Comment by The14me** [comment]
Work fine to me now.Please re-open if still have this problem.
