### ISSUE TITLE
[Quest] [Zangarmarsh] Blackstings Bane quest item not 100%

### ISSUE THREAD

**Issue by ScottieDOESknow** [Atlantiss/NetherwingBugtracker#2010]
**Description**: Blacksting is the objective NPC of quest Blacksting's Bane in Zangarmarsh

**Current behaviour**: Blacksting did not drop stinger for quest completion

https://gyazo.com/a9e7ff39f5376c0a3183ab554f30d3ce

**Expected behaviour**: Blacksting should drop stinger at 100% rate when killed

**Server Revision**: 2238

**Comment by ScottieDOESknow** [comment]
Update: waited 10 minutes for respawn, killed and got quest item.

drop chance should be 100%

**Comment by Shanghi** [comment]
This should be fixed in revision 2240.
