### ISSUE TITLE
[Core] Spellcast leeway against PVE not working

### ISSUE THREAD

**Issue by killablink** [Atlantiss/NetherwingBugtracker#2012]
*Description**: Should be able to cast even if mob walks out of range

**Current behaviour**: Cast doesnt go off

**Expected behaviour**: Cast should still go through even if the mob walks about 5 yards~

**Server Revision**: 2238

**Comment by The14me** [comment]
bring some proof please.

**Comment by killablink** [comment]
Proof of what? That it's not working currently? Because this was already reported a long time ago, got fixed and added, and now it's not working anymore.

**Comment by Easyfraggy** [comment]
https://github.com/Atlantiss/NetherwingBugtracker/issues/121

**Comment by Easyfraggy** [comment]
Yes as with any bug, it will get fixed eventually.

**Comment by narayagh** [comment]
I commented here because the other issue (121) is closed and today you closed this one as well. I was just worried that you might ignore this problem.

**Comment by Easyfraggy** [comment]
121 is open and has been for weeks.

**Comment by narayagh** [comment]
True, my mistake.
