### ISSUE TITLE
Deranged Helboar [NPC] [Spell]

### ISSUE THREAD

**Issue by Neophrone** [Atlantiss/NetherwingBugtracker#2013]
[//]: # (Enclose links to things related to the bug using http://wowhead.com or any other TBC database.)
[//]: # (You can use screenshot ingame to visual the issue.)
[//]: # (Write your tickets according to the format:)
[//]: # ([Quest][Azuremyst Isle] Red Snapper - Very Tasty!)
[//]: # ([NPC] Magistrix Erona)
[//]: # ([Spell][Mage] Fireball)
[//]: # ([Npc][Drop] Ghostclaw Lynx)
[//]: # ([Web] Armory doesnt work)

**Description**: This mobs [Deranged Helboar] have buff[Burning Spikes], that works like druids Thorns, reacting to enemy melee attacks, and dealing damage. But it works wrong, react x3 or even x4 times for every my attack (dealing 25 damage 3 or 4 times to each attack I did), in the end of fight I'm nearly dead, so I have to eat after every mob.
![1](https://user-images.githubusercontent.com/43533040/47762898-1abd0d00-dcc7-11e8-969c-21aa369007a6.jpg)
![2](https://user-images.githubusercontent.com/43533040/47763072-c9f9e400-dcc7-11e8-85e2-fa17ead7949f.jpg)

**Current behaviour**: Reacting x3 or x4 times to every attack I deal.

**Expected behaviour**: Should react one time to every my attack (25 damage to any melee hit).

**Server Revision**: 2238.

**Comment by Wolffenstein** [comment]
Fixed in rev 2241.
