### ISSUE TITLE
[Core] Melee and wand swing timer aren't sharing.

### ISSUE THREAD

**Issue by killablink** [Atlantiss/NetherwingBugtracker#2014]
*Description**: You're able to shoot with your wand and get a melee hit in right after

**Current behaviour**: You're able to shoot with your wand and get a melee hit in right after

**Expected behaviour**: If you shoot with your wand, your melee hit swing timer should reset, shouldn't be able to attack right after

**Server Revision**: 2238

**Comment by towneh** [comment]
If shoot wand is causing the melee swing timer to ready up a melee attack each time then this is definitely not right.

Although not a wand, you can see that during the duel here from vanilla, that's the subsequent melee attacks used after the initial one all are waiting on the swing timer: https://www.youtube.com/watch?v=_zyCfc00KuU

**Comment by Wolffenstein** [comment]
Fixed in rev 3427.
