### ISSUE TITLE
[NPC] Infernals bleeding

### ISSUE THREAD

**Issue by maxturtlesc2** [Atlantiss/NetherwingBugtracker#2015]
[//]: # (Enclose links to things related to the bug using http://wowhead.com or any other TBC database.)
[//]: # (You can use screenshot ingame to visual the issue.)
[//]: # (Write your tickets according to the format:)
[//]: # ([Quest][Azuremyst Isle] Red Snapper - Very Tasty!)
[//]: # ([NPC] Magistrix Erona)
[//]: # ([Spell][Mage] Fireball)
[//]: # ([Npc][Drop] Ghostclaw Lynx)
[//]: # ([Web] Armory doesnt work)

**Description**: 
Infernals can bleed; Rend (Warrior) works on them atm.
**Current behaviour**:

**Expected behaviour**: 
Infernals shouldn't bleed.
**Server Revision**:

**Comment by Tereneckla** [comment]
Fixed
