### ISSUE TITLE
Wrathguard

### ISSUE THREAD

**Issue by genetheparmesan** [Atlantiss/NetherwingBugtracker#2016]
[//]: # (Enclose links to things related to the bug using http://wowhead.com or any other TBC database.)
[//]: # (You can use screenshot ingame to visual the issue.)
[//]: # (Write your tickets according to the format:)
[//]: # ([Quest][Azuremyst Isle] Red Snapper - Very Tasty!)
[//]: # ([NPC] Magistrix Erona)
[//]: # ([Spell][Mage] Fireball)
[//]: # ([Npc][Drop] Ghostclaw Lynx)
[//]: # ([Web] Armory doesnt work)

**Description**: 
[//]: # ([NPC] Wrathguard)
**Current behaviour**: Deals too much damage with Flame Wave. 1 Shots any caster even if theyre moving.

**Expected behaviour**: Probably shouldnt be 100% chance of death if the mob touches you 

**Server Revision**:

**Comment by Wolffenstein** [comment]
Fixed in rev 2241.
