### ISSUE TITLE
[Spell][Rogue] Mutilate

### ISSUE THREAD

**Issue by Seraphomega** [Atlantiss/NetherwingBugtracker#2017]
**Description**: Tooltip says you must be behind the target to use mutilate, but you can use it from the front. This was changed in wotlk

**Current behaviour**: face stab mutilate

**Expected behaviour**: should be only useable from behind
[http://wowwiki.wikia.com/wiki/Mutilate]
"Patch 3.0.2 (14-Oct-2008): Mutilate (Assassination) no longer requires you be behind the target."

**Server Revision**:

**Comment by Wolffenstein** [comment]
Fixed in rev 2241.
