### ISSUE TITLE
Heroic Badge vendor full 2.4.3 gear

### ISSUE THREAD

**Issue by danelmore** [Atlantiss/NetherwingBugtracker#2018]
[//]: # (Enclose links to things related to the bug using http://wowhead.com or any other TBC database.)
[//]: # (You can use screenshot ingame to visual the issue.)
[//]: # (Write your tickets according to the format:)
[//]: # ([Quest][Azuremyst Isle] Red Snapper - Very Tasty!)
[//]: # ([NPC] Magistrix Erona)
[//]: # ([Spell][Mage] Fireball)
[//]: # ([Npc][Drop] Ghostclaw Lynx)
[//]: # ([Web] Armory doesnt work)

**Description**: Heroic badge vendor in Shat has all tbc gear up to 2.4.3 being sold for badges.

**Current behaviour**:

**Expected behaviour**: Should only be the first badge gear available in 2.0

**Server Revision**:

**Comment by Shanghi** [comment]
This should be fixed in revision 2244.
