### ISSUE TITLE
[Quest] The Eyes of Grillok

### ISSUE THREAD

**Issue by killablink** [Atlantiss/NetherwingBugtracker#2019]
*Description**: After absorbing the eye, It seems to be interrupting you every spell cast when it tries to seek an enemy to aggro

**Current behaviour**: Spellcast interrupted every time an eye tries to be summoned. Also get an error message while mounted "can't do this while mounted". Can't turn in the eye at the cauldron if you're mounted.

**Expected behaviour**: The eye that gets summoned shouldn't be interrupting your cast, and you should be able to turn in the eye to the cauldron while mounted.

**Server Revision**: 2238

**Comment by aresbrutus** [comment]
Fixed by Pelekon in rev `2320`
