### ISSUE TITLE
([Spell][Bleeding Hollow Necrolyte] Raise Dead

### ISSUE THREAD

**Issue by killablink** [Atlantiss/NetherwingBugtracker#2020]
*Description**: He is sometimes casting Raise Dead while casting another spell instantly.

**Current behaviour**: Casting Raise dead with no cast, even if he's casting another spell. He even casted an instant Raise Dead while casting a normal raise dead

**Expected behaviour**:  Shouldn't cast instantly.

**Server Revision**: 2238

**Comment by The14me** [comment]
Confirm,wrong spell ID.Suppose to be 34019 +Missing Wolf AI

**Comment by The14me** [comment]
rev 3441. Not an issue anymore.
Can be closed.
