### ISSUE TITLE
Warrior boost doesn't have all spells

### ISSUE THREAD

**Issue by EvanEricWells** [Atlantiss/NetherwingBugtracker#2021]
[//]: # (Enclose links to things related to the bug using http://wowhead.com or any other TBC database.)
[//]: # (You can use screenshot ingame to visual the issue.)
[//]: # (Write your tickets according to the format:)
[//]: # ([Quest][Azuremyst Isle] Red Snapper - Very Tasty!)
[//]: # ([NPC] Magistrix Erona)
[//]: # ([Spell][Mage] Fireball)
[//]: # ([Npc][Drop] Ghostclaw Lynx)
[//]: # ([Web] Armory doesnt work)

**Description**: Title
**Current behaviour**: You only get some spells when you boost
**Expected behaviour**: You should get all spells
**Server Revision**: 2238
Spells I didn't have: Berserker rage, Whirlwind, Pummel, intercept(max rank), Recklessness, revenge, Shield block, disarm, sunder armour(max rank), Shield wall

**Comment by Wolffenstein** [comment]
Fixed in rev 2241.
