### ISSUE TITLE
[Quest] Grillok "Darkeye"

### ISSUE THREAD

**Issue by killablink** [Atlantiss/NetherwingBugtracker#2022]
*Description**: Killed Grillok and didn't receive the quest item (Solo) (mage, maybe pet problem?)

**Current behaviour**: Not dropping the quest item (also taking a really long time to respawn, not sure if normal)

**Expected behaviour**:  Should drop the quest item ( did it again and it dropped correctly, not sure what happened the first time)

**Server Revision**: 2238

**Comment by Shanghi** [comment]
The quest item loot should be fixed in revision 2244.

@aresbrutus I can't remember what you decided to do about respawn times for unique quest people! His ID is 19457.

**Comment by aresbrutus** [comment]
I will check those at a later point. Since Shanghi already fixed the main problem I will close this.
