### ISSUE TITLE
Tagar Spinebreaker odd evade bug.

### ISSUE THREAD

**Issue by BlinkReanimated** [Atlantiss/NetherwingBugtracker#2023]
[//]: # (Enclose links to things related to the bug using http://wowhead.com or any other TBC database.)
[//]: # (You can use screenshot ingame to visual the issue.)
[//]: # (Write your tickets according to the format:)
[//]: # ([Quest][Azuremyst Isle] Red Snapper - Very Tasty!)
[//]: # ([NPC] Magistrix Erona)
[//]: # ([Spell][Mage] Fireball)
[//]: # ([Npc][Drop] Ghostclaw Lynx)
[//]: # ([Web] Armory doesnt work)

**Description**: Tagar Spinebreaker following out of combat

**Current behaviour**: Mob is following me, evades when I attack him. I'm still out of combat. Warrior has tried to charge him, but he still just evades. I can enter and exit combat with him by my side. I relogged to see if it reset him. He slowly walked back to his intended location. When I logged back in I was dead. It started while I was looting a piece of wood/metal and he was returning to his location after chasing a warrior.

**Expected behaviour**: Should just be resetting and going back to his standard pathing.

**Server Revision**: Not sure

**Comment by Wolffenstein** [comment]
Should be fixed
