### ISSUE TITLE
Voidwalkers in hellfire

### ISSUE THREAD

**Issue by Tinnoan** [Atlantiss/NetherwingBugtracker#2024]
**Description**: Rogue Voidwalker (NPC id: 16974) and Uncontrolled Voidwalker (NPC id: 16975) both seem to be using Collapse on death.

[wowhead](https://www.wowhead.com/npc=17014/collapsing-voidwalker#comments) for collapsing voidwalker, comments and abilities both show the collapse ability.

[wowhead](https://www.wowhead.com/npc=16974/rogue-voidwalker#abilities) for rogue voidwalker

[wowhead](https://www.wowhead.com/npc=16975/uncontrolled-voidwalker#abilities) for uncontrolled voidwalker

**Expected behaviour**: Rogue voidwalker and uncontrolled voidwalker shouldn't be using the collapse ability.

Collapse also hit me for 2138 damage, according to comments on the collapsing voidwalker it should be doing 1k-1.5k damage

**Server Revision**: 2238

**Comment by The14me** [comment]
https://github.com/Atlantiss/AtlantissTBCBT/issues/482

**Comment by eryczek1615** [comment]
[Collapsing Voidwalker](https://db.excalibur.ws/?npc=17014#abilities) should also use other abilities for now he uses only Collapse.
[Vacillating Voidcaller](https://db.excalibur.ws/?npc=19527) doesn't use his abilities

**Comment by Easyfraggy** [comment]
![image](https://user-images.githubusercontent.com/36134067/48076273-2471d380-e1e5-11e8-93eb-21f56e1b06ed.png)

![image](https://user-images.githubusercontent.com/36134067/48076278-289df100-e1e5-11e8-9a10-fcf885d7230e.png)

![image](https://user-images.githubusercontent.com/36134067/48076289-2e93d200-e1e5-11e8-8cf2-e755efd70880.png)

![image](https://user-images.githubusercontent.com/36134067/48076310-3784a380-e1e5-11e8-8c6e-9f627091dc55.png)

![image](https://user-images.githubusercontent.com/36134067/48076347-4bc8a080-e1e5-11e8-931e-22b87b64307b.png)

![image](https://user-images.githubusercontent.com/36134067/48076378-5aaf5300-e1e5-11e8-9bfe-74dfa8fe334c.png)

**Comment by Evolvee** [comment]
Seems no longer valid. Please retest/reopen if the issue persists.

(fixed in rev cd)
