### ISSUE TITLE
[Core][Macro] Faerie Fire (Feral) requires the usually redundant (Rank #) to function

### ISSUE THREAD

**Issue by Jacksn5** [Atlantiss/NetherwingBugtracker#2025]
[//]: # (Enclose links to things related to the bug using http://wowhead.com or any other TBC database.)
[//]: # (You can use screenshot ingame to visual the issue.)
[//]: # (Write your tickets according to the format:)
[//]: # ([Quest][Azuremyst Isle] Red Snapper - Very Tasty!)
[//]: # ([NPC] Magistrix Erona)
[//]: # ([Spell][Mage] Fireball)
[//]: # ([Npc][Drop] Ghostclaw Lynx)
[//]: # ([Web] Armory doesnt work)

**Description**: 
[ `/cast Faerie Fire (Feral)`](https://db.excalibur.ws/?spell=27011) is not recognized at all unless the rank is specified like `/cast Faerie Fire (Feral)(Rank 4)`

**Expected behaviour**: 
The /cast function should use the highest available rank of the specified ability by default when not specified, for example a level 70 Mage automatically casts rank 13 simply using `/cast Frostbolt` while for the faster casting rank 1 they would use `/cast Frostbolt(Rank 1)`

**Server Revision**: 
2238

**Comment by Shanghi** [comment]
This is a client problem that the server can't change. For spells that have something in parentheses at the end, you have to put `()` after it to use the highest rank automatically. That's how it was long ago.

Some old 2007/2008 guides:
![image](https://user-images.githubusercontent.com/2672633/47766415-e173a580-dca4-11e8-8c78-6b3f61cf90df.png)
![image](https://user-images.githubusercontent.com/2672633/47766463-2e577c00-dca5-11e8-8e41-298b4ca9353d.png)
