### ISSUE TITLE
[Spell][Rogue] Backstab/Mutilate

### ISSUE THREAD

**Issue by Seraphomega** [Atlantiss/NetherwingBugtracker#2027]
**Description**: Cannot backstab or mutilate an NPC/mob while it is running away with its back turned.

**Current behaviour**:Doesn't work against fleeing mobs that clearly have their backs exposed

**Expected behaviour**:  Should work always from behind 

**Server Revision**:

**Comment by Easyfraggy** [comment]
https://github.com/Atlantiss/NetherwingBugtracker/issues/1565
