### ISSUE TITLE
[NPC] Fel Cannon MKI not leashing

### ISSUE THREAD

**Issue by Jacksn5** [Atlantiss/NetherwingBugtracker#2028]
[//]: # (Enclose links to things related to the bug using http://wowhead.com or any other TBC database.)
[//]: # (You can use screenshot ingame to visual the issue.)
[//]: # (Write your tickets according to the format:)
[//]: # ([Quest][Azuremyst Isle] Red Snapper - Very Tasty!)
[//]: # ([NPC] Magistrix Erona)
[//]: # ([Spell][Mage] Fireball)
[//]: # ([Npc][Drop] Ghostclaw Lynx)
[//]: # ([Web] Armory doesnt work)

**Description**: 
[Fel Cannon MKI](https://db.excalibur.ws/?npc=22461) doesn't evade at all since it's stationary. See video (ignore Simpsons from the other screen :p)
[![Fel Cannon MKI not leashing](http://img.youtube.com/vi/LVioqdfPV5U/0.jpg)](https://www.youtube.com/watch?v=LVioqdfPV5U "Fel Cannon MKI not leashing")

Even hearthing back to Honor Hold, which is halfway across the map, didn't reset them - see 
![wowscrnshot_103118_061940](https://user-images.githubusercontent.com/43507549/47767745-4d6e0200-dcd5-11e8-8c01-3844125cabc8.jpg)

I'm guessing this affects all Fel Cannons, maybe even all stationary NPCs.

**Server Revision**: 
2242

**Comment by Jacksn5** [comment]
Affects [Marauding Crust Burster](https://db.excalibur.ws/?npc=16857) as well, see
![image](https://user-images.githubusercontent.com/43507549/47822478-9620cc00-dd64-11e8-8dee-ad8dd6407c5a.png)

They were able to successfully tunnel forwards at least once, but even after hearthing did they not reset, even 5 minutes later with plenty of time to tunnel out of leash range

**Comment by Easyfraggy** [comment]
Same issue as Crust Burster, we have a fix for it in the works.

**Comment by Easyfraggy** [comment]
Fixed in rev 2245
