### ISSUE TITLE
Hellfire PvP Towers Buff

### ISSUE THREAD

**Issue by Neophrone** [Atlantiss/NetherwingBugtracker#2029]
[//]: # (Enclose links to things related to the bug using http://wowhead.com or any other TBC database.)
[//]: # (You can use screenshot ingame to visual the issue.)
[//]: # (Write your tickets according to the format:)
[//]: # ([Quest][Azuremyst Isle] Red Snapper - Very Tasty!)
[//]: # ([NPC] Magistrix Erona)
[//]: # ([Spell][Mage] Fireball)
[//]: # ([Npc][Drop] Ghostclaw Lynx)
[//]: # ([Web] Armory doesnt work)

**Description**: 5% damage bonus buff disappear after death, and will not apply again after resurection.
![wowscrnshot_103118_062923](https://user-images.githubusercontent.com/43533040/47769583-0f78da00-dce5-11e8-9dc4-362f64efbbba.jpg)

**Current behaviour**: Buff doesn't apply after ress.

**Expected behaviour**: Buff should be on players of faction that got 3 towers everytime they in HFP or in any HFP dungeons/raid. 

**Server Revision**: 2243.

**Comment by Easyfraggy** [comment]
https://github.com/Atlantiss/NetherwingBugtracker/issues/1996
