### ISSUE TITLE
[NPC] Chicken (Refusing to die)

### ISSUE THREAD

**Issue by Thugli** [Atlantiss/NetherwingBugtracker#2031]
[//]: # (Enclose links to things related to the bug using http://wowhead.com or any other TBC database.)
[//]: # (You can use screenshot ingame to visual the issue.)
[//]: # (Write your tickets according to the format:)
[//]: # ([Quest][Azuremyst Isle] Red Snapper - Very Tasty!)
[//]: # ([NPC] Magistrix Erona)
[//]: # ([Spell][Mage] Fireball)
[//]: # ([Npc][Drop] Ghostclaw Lynx)
[//]: # ([Web] Armory doesnt work)

**Description**: 
While attempting to murder a chicken, I was unable to land vampiric touch, as it would ignore my cast and immedietly go out of combat.

![image](https://user-images.githubusercontent.com/37326256/47770356-77afc780-dcb5-11e8-8a90-9d96dd3b7131.png)
**Current behaviour**:
https://clips.twitch.tv/TransparentSarcasticKeyboardOMGScoots

**Expected behaviour**: 
I should be able to slaughter chickens as I please.
**Server Revision**: 
2243

**Comment by Tereneckla** [comment]
Most like same issue as #886
