### ISSUE TITLE
[NPC] Darkcrest Sorceress

### ISSUE THREAD

**Issue by ezzekielfox** [Atlantiss/NetherwingBugtracker#2032]
[//]: # ([NPC] Darkcrest Sorceress)
[//]: # ([Spell] Freezing Circle)

**Description**: Darkcrest Sorceress' cast a slow forming frost spell upon the ground in an area that, when completed, zaps the target for massive frost damage if inside the area.

**Current behaviour**: Darkcrest Sorceress' instantly cast the spell, dealing damage right away before the animation begins.

**Expected behaviour**: The rune on the ground should begin to form, followed by small blocks of ice on opposing sides, moving in a clockwise direction until a circle is formed, before detonating the center in a frost AoE attack, hitting anything inside for massive frost damage.

**Server Revision**:

**Comment by aresbrutus** [comment]
similar https://github.com/Atlantiss/NetherwingBugtracker/issues/2151

**Comment by Mikik3jr** [comment]
Even worse that the 2k+ dmg I got in my face is not even displayed in combat log.

**Comment by Mikik3jr** [comment]
I patiently waited until the spell ends, and it doesn't hit twice.

**Comment by xmesaj2** [comment]
#2361
