### ISSUE TITLE
[NPC] [Zangarmarsh] Umbrafen Eel hovering above water

### ISSUE THREAD

**Issue by ScottieDOESknow** [Atlantiss/NetherwingBugtracker#2033]
**Description**:  Umbrafen Eel @ Umbrafen Lake in Zangarmarsh

**Current behaviour**: If these mobs are pulled to surface of water, they will hover above

https://gyazo.com/46d2f235623060855a2989b1f17e67ef

**Expected behaviour**: Should not hover above water

**Server Revision**:  2242

**Comment by Easyfraggy** [comment]
Pretty sure this is blizzlike.

**Comment by ScottieDOESknow** [comment]
I do recall these mobs partially (half-way) out of the water in this scenario but not above and noticeably hovering.

**Comment by Wolffenstein** [comment]
Blizzlike.
