### ISSUE TITLE
[NPC] [Hellfire Peninsula] Marauding Crust Burster visible / target-able

### ISSUE THREAD

**Issue by ScottieDOESknow** [Atlantiss/NetherwingBugtracker#2034]
**Description**: Marauding Crust Burster (specific ID)

NPC INFO
https://gyazo.com/2a8e4a883c37122b1659bd3bab1b1e68

**Current behaviour**: One specific mob is visible / target-able and missing the 'jumping rocks' animation from being submerged in the ground. Seems like others are fine.

https://gyazo.com/3bfddd87552a06db93a798ea44bd71c9

**Expected behaviour**: Should not be visible, like all others.

**Server Revision**: 2243

**Comment by Easyfraggy** [comment]
Did this happen to anyone else?

**Comment by Tereneckla** [comment]
Fixed
