### ISSUE TITLE
[NPC]Dreghood Brute#16938 display level up animation when changing to [NPC]Fleeing Dreghood Warrrior#19477

### ISSUE THREAD

**Issue by Tenoutoften** [Atlantiss/NetherwingBugtracker#2036]
**Description**: 
[[NPC]Dreghood Brute#16938](https://www.wowhead.com/npc=16938/dreghood-brute#comments) sometimes display level up animation when turning into [[NPC]Fleeing Dreghood Warrrior#19477](https://www.wowhead.com/npc=19477/fleeing-dreghood-warrior) after killing a [[NPC]Illidari Taskmaster#17058](https://www.wowhead.com/npc=17058/illidari-taskmaster)

Video of current behavior [here](https://www.youtube.com/watch?v=r6d7faCfZQI&feature=youtu.be)

**Expected behaviour**: 
Expected to not display level up animation

**Server Revision**: 
2243

**Comment by Easyfraggy** [comment]
Known issue.

**Comment by Tenoutoften** [comment]
Merged into https://github.com/Atlantiss/NetherwingBugtracker/issues/3737
