### ISSUE TITLE
[NPC] Bonechewer Scavenger Positional Desync

### ISSUE THREAD

**Issue by KevinTyrrell** [Atlantiss/NetherwingBugtracker#2039]
[//]: # (Enclose links to things related to the bug using http://wowhead.com or any other TBC database.)
[//]: # (You can use screenshot ingame to visual the issue.)
[//]: # (Write your tickets according to the format:)
[//]: # ([Quest][Azuremyst Isle] Red Snapper - Very Tasty!)
[//]: # ([NPC] Magistrix Erona)
[//]: # ([Spell][Mage] Fireball)
[//]: # ([Npc][Drop] Ghostclaw Lynx)
[//]: # ([Web] Armory doesnt work)

**Description**: 
NPC Info: 18952,, Id: 30, GUIDLow: 71046

After a sap, the mob teleports a large distance, then returns back to his current position. The same happens with another mob nearby. After cheap shot ends, the mob warps to the left of me. I was not lagging while recording this. 
I'm not sure how to reproduce.

**Current behaviour**:
[Twitch Clip](https://clips.twitch.tv/UnsightlyHonestLegYouDontSay)

**Expected behaviour**: 
N/A

**Server Revision**: 
2243

**Comment by Wolffenstein** [comment]
Should be fixed now

**Comment by KevinTyrrell** [comment]
@Wolffenstein What do you think was the cause?
