### ISSUE TITLE
[Escort]Escape from the Catacombs

### ISSUE THREAD

**Issue by Dpthx** [Atlantiss/NetherwingBugtracker#204]
https://www.wowhead.com/quest=9212/escape-from-the-catacombs
https://www.wowhead.com/npc=16295/ranger-lilatha

she's missing assist flag. also doubles down on some of her waypoints at the end.

**Comment by Evolvee** [comment]
she has it, just broken cpp most likely

![image](https://user-images.githubusercontent.com/1942409/45929456-61924700-bf52-11e8-90fa-0b4f8c15f04d.png)

**Comment by Tenoutoften** [comment]
Her assist worked properly when I did it just now. But she does have a slight error in her path at the end
