### ISSUE TITLE
Wrathguards Flamewave

### ISSUE THREAD

**Issue by koochy414** [Atlantiss/NetherwingBugtracker#2041]
[//]: # (Enclose links to things related to the bug using http://wowhead.com or any other TBC database.)
[//]: # (You can use screenshot ingame to visual the issue.)
[//]: # (Write your tickets according to the format:)
[//]: # ([Quest][Azuremyst Isle] Red Snapper - Very Tasty!)
[//]: # ([NPC] Magistrix Erona)
[//]: # ([Spell][Mage] Fireball)
[//]: # ([Npc][Drop] Ghostclaw Lynx)
[//]: # ([Web] Armory doesnt work)

**Description**: 
[NPC] Wrath guards flame wave spell not working as intended, it would instantly cast and put a debuff on us that would tick 5 times in 2 seconds, damage came from a source "no one". 

**Current behaviour**:
Flame wave applying a debuff which ticks 5 times in 2 seconds, for about 750 damage each. 

**Expected behaviour**: 
if i recall correctly, it should cast flamewave in a line ,which does similar damage but you can move out of it, rather than a debuff

**Server Revision**:

**Comment by ircfelix** [comment]
Sauce?

**Comment by towneh** [comment]
This is already fixed by Wolf and awaiting push to live
https://gfycat.com/pl/FalseGlitteringHornbill
