### ISSUE TITLE
[Pathing][Elevator][Pet]

### ISSUE THREAD

**Issue by Fenvarien1** [Atlantiss/NetherwingBugtracker#2042]
**Description**: 
TBC - Zangarmash - Telredor - alliance base ontop of a tree
using the elevator and jump of the elevator. the pet can't follow.

**Current behaviour**:
https://gfycat.com/OptimalCelebratedLeveret

**Expected behaviour**: 
The pet stays behind until there is a path to move or despawns.

**Server Revision**:

**Comment by Peglaa** [comment]
It obviously can't find a path to you so it despawns, caused by you jumping off of it early. A good workaround would prolly be to delay the despawn for a while for these specific situations I suppose. @Wolffenstein

**Comment by Fenvarien1** [comment]
https://github.com/Atlantiss/NetherwingBugtracker/issues/2309 found the same issue in another ticket

**Comment by Fenvarien1** [comment]
tested the exact elevator again and it works. can be closed

**Comment by Tereneckla** [comment]
Fixed
