### ISSUE TITLE
Eye of Kilrogg spawns underneath ground

### ISSUE THREAD

**Issue by Nicemann1089** [Atlantiss/NetherwingBugtracker#2043]
https://drive.google.com/file/d/1TRfnNahnW1PtMOIcgpldzJmzHgJTR9db/view

[//]: # ([Spell][Warlock] Eye of Kilrogg)

**Description**: When casting Eye of Kilrogg, it spawns underneath ground and falls in specific areas.

**Current behaviour**: Eye of Kilrogg spawns underneath ground and falls in specific areas.

**Expected behaviour**: Eye of Kilrogg should stay above the ground and being controllable.

**Comment by Wolffenstein** [comment]
Fixed in rev 2389.
