### ISSUE TITLE
Eye of Kilrogg can attack

### ISSUE THREAD

**Issue by Nicemann1089** [Atlantiss/NetherwingBugtracker#2044]
[//]: # ([Spell][Warlock] Eye of Kilrogg)

**Description**: Eye of Kilrogg can attack/get aggro.

**Current behaviour**: Eye of Kilrogg can attack/get aggro.

**Expected behaviour**: Eye of Kilrogg shouldn't be able to attack/get aggro.

**Comment by ScottieDOESknow** [comment]
This is working as intended. Eye could always get aggro and attack.

https://gyazo.com/54045f97a1fe166998c2f6672d673d75
