### ISSUE TITLE
Logging in dead

### ISSUE THREAD

**Issue by Kuumi** [Atlantiss/NetherwingBugtracker#2045]
[//]: # (Enclose links to things related to the bug using http://wowhead.com or any other TBC database.)
[//]: # (You can use screenshot ingame to visual the issue.)
[//]: # (Write your tickets according to the format:)
[//]: # ([Quest][Azuremyst Isle] Red Snapper - Very Tasty!)
[//]: # ([NPC] Magistrix Erona)
[//]: # ([Spell][Mage] Fireball)
[//]: # ([Npc][Drop] Ghostclaw Lynx)
[//]: # ([Web] Armory doesnt work)

**Description**: 
Upon logging out in an inn and logging back in, I found myself having to run to a corpse that shouldnt have been there. 
![image](https://user-images.githubusercontent.com/44377654/47791551-f9b8e400-dce7-11e8-85eb-3afd2ce2f964.png)

**Current behaviour**:
Dying upon logging overnight.
**Expected behaviour**: 
Staying alive within the confines of the Inn.
**Server Revision**: 
2243

**Comment by Easyfraggy** [comment]
Probably cus you were in combat. Reopen if that wasn't the case.

**Comment by Retinus** [comment]
When i logged out about a week ago i was at the swamp of sorrow inn. Today when i logged back in i saw that my reincarnation was at 60 min cd (shaman char). I think that if i wasn't shaman i would have been dead too.

To my eyes seems like an issue with the preparation of the 2nd beta phase and it wont happen when we go live. If it happens again i ll post here.
