### ISSUE TITLE
NPC, Shattrath

### ISSUE THREAD

**Issue by Erodraeda** [Atlantiss/NetherwingBugtracker#2046]
[//]: # (Enclose links to things related to the bug using http://wowhead.com or any other TBC database.)
[//]: # (You can use screenshot ingame to visual the issue.)
[//]: # (Write your tickets according to the format:)
[//]: # ([Quest][Azuremyst Isle] Red Snapper - Very Tasty!)
[//]: # ([NPC] Magistrix Erona)
[//]: # ([Spell][Mage] Fireball)
[//]: # ([Npc][Drop] Ghostclaw Lynx)
[//]: # ([Web] Armory doesnt work)

**Description**: 
NPC Zahlia, ID 18652 saying it's speech way too often. Seems like 2 times, when she calls her son back and when he gets back.
**Current behaviour**:
saying it's speech 2 times, when she calls her son back and when he gets back.
**Expected behaviour**: 
Should only say in the first time.
**Server Revision**:

**Comment by Manaci** [comment]
Fixed
