### ISSUE TITLE
NPC, Quest, Shattrath

### ISSUE THREAD

**Issue by Erodraeda** [Atlantiss/NetherwingBugtracker#2047]
[//]: # (Enclose links to things related to the bug using http://wowhead.com or any other TBC database.)
[//]: # (You can use screenshot ingame to visual the issue.)
[//]: # (Write your tickets according to the format:)
[//]: # ([Quest][Azuremyst Isle] Red Snapper - Very Tasty!)
[//]: # ([NPC] Magistrix Erona)
[//]: # ([Spell][Mage] Fireball)
[//]: # ([Npc][Drop] Ghostclaw Lynx)
[//]: # ([Web] Armory doesnt work)

**Description**: 
NPC Khadgar's Servant, ID 19685, from quest City of Light, isn't whispering you with the information about the city. His path seems a little bit off, too.
**Current behaviour**:
No whispers are being received from the quest NPC
**Expected behaviour**: 
you should receive several whispers from the NPC, like you can see in this video https://www.youtube.com/watch?v=xDDIk-3HXJk
**Server Revision**:

**Comment by ScottieDOESknow** [comment]
Completed this quest in the first hours of Phase 2 and received  whispers from servant. 
Even had to re-do quest once because server crashed. Whispers both times.

using Prat addon for chat

**Comment by aresbrutus** [comment]
Working just fine.
