### ISSUE TITLE
Serpent sting

### ISSUE THREAD

**Issue by danelmore** [Atlantiss/NetherwingBugtracker#2048]
[//]: # (Enclose links to things related to the bug using http://wowhead.com or any other TBC database.)
[//]: # (You can use screenshot ingame to visual the issue.)
[//]: # (Write your tickets according to the format:)
[//]: # ([Quest][Azuremyst Isle] Red Snapper - Very Tasty!)
[//]: # ([NPC] Magistrix Erona)
[//]: # ([Spell][Mage] Fireball)
[//]: # ([Npc][Drop] Ghostclaw Lynx)
[//]: # ([Web] Armory doesnt work)

**Description**: not able to refresh or cast another serpent sting if yours or another hunters is on the target

**Current behaviour**:not able to refresh or cast another serpent sting if yours or another hunters is on the target

**Expected behaviour**: should be able to refresh before it ending and have yours and another hunters sting active.

**Server Revision**:

**Comment by Wolffenstein** [comment]
Fixed in rev 2245.
