### ISSUE TITLE
Pet trained abilities

### ISSUE THREAD

**Issue by danelmore** [Atlantiss/NetherwingBugtracker#2049]
[//]: # (Enclose links to things related to the bug using http://wowhead.com or any other TBC database.)
[//]: # (You can use screenshot ingame to visual the issue.)
[//]: # (Write your tickets according to the format:)
[//]: # ([Quest][Azuremyst Isle] Red Snapper - Very Tasty!)
[//]: # ([NPC] Magistrix Erona)
[//]: # ([Spell][Mage] Fireball)
[//]: # ([Npc][Drop] Ghostclaw Lynx)
[//]: # ([Web] Armory doesnt work)

**Description**: some pets come with an ability when trained, no there

**Current behaviour**:no special ability when training pets.  ravanger-gore, bird-dive, cat-bite are the ones i've had so far.

**Expected behaviour**: Usually after a few kills with whatever pet they learn that special ability they have.

**Server Revision**:

**Comment by Easyfraggy** [comment]
Don't understand this issue, can someone elaborate?

**Comment by DeltaLoads** [comment]
yes he expect that every pet he tames gets its class specific ability, which it doesnt, this is invalid report
