### ISSUE TITLE
[Object] Chests not despawning after emptying them the first time

### ISSUE THREAD

**Issue by peanutcheese** [Atlantiss/NetherwingBugtracker#205]
[//]: # (Enclose links to things related to the bug using http://wowhead.com or any other TBC database.)
[//]: # (You can use screenshot ingame to visual the issue.)
[//]: # (Write your tickets according to the format:)
[//]: # ([Quest][Azuremyst Isle] Red Snapper - Very Tasty!)
[//]: # ([NPC] Magistrix Erona)
[//]: # ([Spell][Mage] Fireball)
[//]: # ([Npc][Drop] Ghostclaw Lynx)
[//]: # ([Web] Armory doesnt work)

**Description**: 
opening a chest and emptying it does not despawn the chest
**Current behaviour**:
idem ditto as above, note: opening it a 2nd time DOES despawn the chest
**Expected behaviour**: 
if you take all items out of a chest it should despawn
**Server Revision**: 
2028

**Comment by Peglaa** [comment]
Thats weird, this worked fine for me yesterday.

**Comment by totaemoeggerli** [comment]
same thing happened to me
was in a grp, party member out of range, still had to roll for green items, won them imediatly
the chest contained [empty loot] the second time and despawned properly
https://imgur.com/a/o6H371T

**Comment by Peglaa** [comment]
Probably tied to being in a party. I wasn't and it all worked fine.
