### ISSUE TITLE
[NPC] Shattered Hand Mage

### ISSUE THREAD

**Issue by sifiuocz** [Atlantiss/NetherwingBugtracker#2050]
**Description**: 
The damage of This NPC's Fireball spell is too high. It hits for around 1200 damage.

**Current behaviour**:

**Expected behaviour**: 
https://youtu.be/iapfUy-m0wg?t=84
Take a close look at this video filmed in WotLK. After playing the video at 0.25 speed you can see that the Fireball is hitting for around 500.

**Server Revision**: 
-

**Comment by zauru7** [comment]
Weren't they nerfed in wotlk? I specifically remember those guys being very painful during leveling on retail

**Comment by Tenoutoften** [comment]
![4d7d18dd37e07d360341036ffe9d83ad](https://user-images.githubusercontent.com/34839199/47810305-509fd700-dd43-11e8-8904-5f12a678ec85.png)
[[Spell]Fireball#14034](https://www.wowhead.com/spell=14034/fireball)

**Comment by Easyfraggy** [comment]
They have the correct spell.
