### ISSUE TITLE
Hellfire Ramparts. Watchkeeper Gargolmar. [NPC]

### ISSUE THREAD

**Issue by Neophrone** [Atlantiss/NetherwingBugtracker#2051]
[//]: # (Enclose links to things related to the bug using http://wowhead.com or any other TBC database.)
[//]: # (You can use screenshot ingame to visual the issue.)
[//]: # (Write your tickets according to the format:)
[//]: # ([Quest][Azuremyst Isle] Red Snapper - Very Tasty!)
[//]: # ([NPC] Magistrix Erona)
[//]: # ([Spell][Mage] Fireball)
[//]: # ([Npc][Drop] Ghostclaw Lynx)
[//]: # ([Web] Armory doesnt work)

**Description**: If u kill the adds[Hellfire Watchers] of the boss, and then wipe - adds will not respawn. Also one of the boss ability [Retaliation] shouldn't counterattack melee atacks made from behind.

**Current behaviour**: Adds don't respawn after wipe. Ability [Retaliation] counterattack hits made from behind.

**Expected behaviour**: Adds should respawn after wipe. Ability [Retaliation] shouldn't counterattack hits made from behind. 
Proofs: http://wowwiki.wikia.com/wiki/Watchkeeper_Gargolmar.
Retaliation: Instantly counterattack any enemy that strikes you in melee for 15 sec. Melee attacks made from behind cannot be counterattacked.

**Server Revision**: 2244.

**Comment by Easyfraggy** [comment]
Need some proof that the watchers should respawn.

**Comment by Mewmewww** [comment]
The adds aren't summoned, so I don't think it should make sense for them to respawn? I've been looking on some old videos, but no one is wiping!

**Comment by miraco** [comment]
ATM on retail they do respawn when you reset the boss.
proof: https://www.twitch.tv/videos/330150101

**Comment by The14me** [comment]
rev 3451. Still an issue.

**Comment by Wolffenstein** [comment]
Fixed in rev 3454.
