### ISSUE TITLE
Healing nearly dead target still not working properly.

### ISSUE THREAD

**Issue by Mikik3jr** [Atlantiss/NetherwingBugtracker#2052]
[//]: # (Enclose links to things related to the bug using http://wowhead.com or any other TBC database.)
[//]: # (You can use screenshot ingame to visual the issue.)
[//]: # (Write your tickets according to the format:)
[//]: # ([Quest][Azuremyst Isle] Red Snapper - Very Tasty!)
[//]: # ([NPC] Magistrix Erona)
[//]: # ([Spell][Mage] Fireball)
[//]: # ([Npc][Drop] Ghostclaw Lynx)
[//]: # ([Web] Armory doesnt work)

**Description**: 
[Similar issue](https://github.com/Atlantiss/NetherwingBugtracker/issues/1438) was reported before, maybe it is connected.
When the mass PVP happened horde attacked me in hellfire.
**Current behaviour**:
I used lay on hands to save myself. I heard the effect, I saw the heal, I saw the green numbers, I saw the heal in the combat log I still died.
![wowscrnshot_103018_223830](https://user-images.githubusercontent.com/43505031/47805699-3ad8e480-dd38-11e8-9bbd-91f84ba5300f.jpg)
**Expected behaviour**: 
2 possibilities:
1.) If I heal myself I shouldn't die.

2.) If I die from a dmg then I shouldn't be able to use my spells. Having 1hr cd on Lay on Hands because os this not cool.
**Server Revision**: 
2244

**Comment by Tenoutoften** [comment]
https://github.com/Atlantiss/NetherwingBugtracker/issues/398 duplicate? Same class, same ability, both see heal in log
