### ISSUE TITLE
[NPC] Marauding Crust Burster

### ISSUE THREAD

**Issue by Mewmewww** [Atlantiss/NetherwingBugtracker#2054]
[//]: # (Enclose links to things related to the bug using http://wowhead.com or any other TBC database.)
[//]: # (You can use screenshot ingame to visual the issue.)
[//]: # (Write your tickets according to the format:)
[//]: # ([Quest][Azuremyst Isle] Red Snapper - Very Tasty!)
[//]: # ([NPC] Magistrix Erona)
[//]: # ([Spell][Mage] Fireball)
[//]: # ([Npc][Drop] Ghostclaw Lynx)
[//]: # ([Web] Armory doesnt work)

**Description**: 
The yard of how long I have to go before leaving combat is certainly wrong.
**Current behaviour**:
The yard of how long I have to go before leaving combat is certainly wrong.
**Expected behaviour**: 
I should not have to run out of the area where I can't see it anymore, and still be in combat. I think it's due to the fact it doesn't move but uses the burrow ability, and when I'm so far away, it can't use it to catch up to me. https://imgur.com/a/j3sUEMo
**Server Revision**: 
2244

**Comment by Easyfraggy** [comment]
We have a fix for this in the works.

**Comment by Drayo** [comment]
I assume this is due to the leashing being fixed, all stationary mobs cannot leave their leash range (or take forever in the case of these worms) so they won't reset.

They should evade when the distance between them and their target becomes unusually high I guess.

**Comment by Neophrone** [comment]
The same problem with Fel Cannons, it will keep u in combat until u kill it, or meet u'r own death. Also this green nazal goo from pool of agonar will chase u until debuff that they put on u(1 min dot) will expire.

**Comment by Easyfraggy** [comment]
Should be fixed in rev 2245

**Comment by Kidcudi123** [comment]
Fulgorge rare same type bugged
