### ISSUE TITLE
NPC Bleeding Hollow Tormentor

### ISSUE THREAD

**Issue by Erodraeda** [Atlantiss/NetherwingBugtracker#2055]
[//]: # (Enclose links to things related to the bug using http://wowhead.com or any other TBC database.)
[//]: # (You can use screenshot ingame to visual the issue.)
[//]: # (Write your tickets according to the format:)
[//]: # ([Quest][Azuremyst Isle] Red Snapper - Very Tasty!)
[//]: # ([NPC] Magistrix Erona)
[//]: # ([Spell][Mage] Fireball)
[//]: # ([Npc][Drop] Ghostclaw Lynx)
[//]: # ([Web] Armory doesnt work)

**Description**: 
The mob (ID 19424) doesn't summon it's wolf in certain situations
**Current behaviour**:
If I sap the target before pulling, it doens't summon it's wolf when engaged.
**Expected behaviour**: 
Should summon it's wolf regardless of pulling situations
**Server Revision**:

**Comment by maxturtlesc2** [comment]
The same happens with a warrior charge.

**Comment by Wolffenstein** [comment]
Fixed in rev 3427.
