### ISSUE TITLE
[Spell][Priest] Mind control threat issue

### ISSUE THREAD

**Issue by Brasso** [Atlantiss/NetherwingBugtracker#2056]
[//]: # (Enclose links to things related to the bug using http://wowhead.com or any other TBC database.)
[//]: # (You can use screenshot ingame to visual the issue.)
[//]: # (Write your tickets according to the format:)
[//]: # ([Quest][Azuremyst Isle] Red Snapper - Very Tasty!)
[//]: # ([NPC] Magistrix Erona)
[//]: # ([Spell][Mage] Fireball)
[//]: # ([Npc][Drop] Ghostclaw Lynx)
[//]: # ([Web] Armory doesnt work)

**Description**: 
Abilities and attacks from mind controlled units generate no threat.

Failing a mind control generates huge amount of threat on all targets, not only the target that had mind control cast on it.

**Current behaviour**:

https://clips.twitch.tv/ScaryCautiousGrassThunBeast

**Expected behaviour**: 
Threat.
**Server Revision**: 
2244

**Comment by Wolffenstein** [comment]
I don't think I get it. Can you elaborate?

**Comment by Brasso** [comment]
From the clip you can see Tuwz casting mind control on Hellfire sentry. They are immune to mind control so it fails, but when it fails you can see Tuwz getting aggro from both mobs simultaneously despite the tank has generated plenty of threat on both targets.

Mind controlled targets also never pulled aggro from the tank even when doing 2k+ dps when you could spam the abilities, the abilities generate no threat.

**Comment by Wolffenstein** [comment]
I think it's fine now, just checked.
