### ISSUE TITLE
[NPC] Nazan death animation

### ISSUE THREAD

**Issue by Brasso** [Atlantiss/NetherwingBugtracker#2057]
[//]: # (Enclose links to things related to the bug using http://wowhead.com or any other TBC database.)
[//]: # (You can use screenshot ingame to visual the issue.)
[//]: # (Write your tickets according to the format:)
[//]: # ([Quest][Azuremyst Isle] Red Snapper - Very Tasty!)
[//]: # ([NPC] Magistrix Erona)
[//]: # ([Spell][Mage] Fireball)
[//]: # ([Npc][Drop] Ghostclaw Lynx)
[//]: # ([Web] Armory doesnt work)

**Description**: 
When Nazan died he didn't display a death animation but instead instantly flopped dead on the ground.
**Current behaviour**:
https://clips.twitch.tv/RelievedFaintTireTebowing
**Expected behaviour**: 
Death animation.
**Server Revision**: 
2244

**Comment by Tereneckla** [comment]
Fixed
