### ISSUE TITLE
[Pet/Regen] Warlock pets regeneration is extremely low.

### ISSUE THREAD

**Issue by Cptnlobbe** [Atlantiss/NetherwingBugtracker#2058]
Description: Pets should be able to regen. Currently they gain about 50hp/mana a tick on 4500hp pool.

Current behaviour: Warlock pets regen at an abysmal low rate. about 10min from 1-100%.

Expected behaviour: About 10% hp/mana per tick.

**Comment by Cptnlobbe** [comment]
In combat it wont regen at all.

**Comment by Easyfraggy** [comment]
Need some proof that it should be higher. 10% hp seems extremely high.

**Comment by Cptnlobbe** [comment]
its 10% every 5 sec, thats 50% in 50sec. thats not extremly high.

**Comment by Easyfraggy** [comment]
I don't think you understand, you have to provide some proof of what the regen should be. Just saying how it should be won't work.

**Comment by atychiphobia** [comment]
https://youtu.be/XccyLbaij2c?t=381

**Comment by Wolffenstein** [comment]
I think i found the issue, fixed in rev 2982.
