### ISSUE TITLE
Improved Blessing of Might

### ISSUE THREAD

**Issue by Trix115** [Atlantiss/NetherwingBugtracker#206]
The first talent in the ret tree, "Improved Blessing of Might" does not seem to work. With 5/5 points into it the tooltip still reads 35 attack power, which is the baseline amount it gives.

**Comment by Lephidiles** [comment]
In tbc you need to hold the mouse over the spell at the action bar or in spell book. if you hold the mouse over the buff you get you will always see it non improved. same with all spells and is a client limitation as it cant now what talent the person that buffed you had

**Comment by Easyfraggy** [comment]
This is just TBC, tooltip of BoM does not get increased by the talents. 

If you find that the improved BoM extra AP doesnt apply to your character though, do reopen.
