### ISSUE TITLE
[NPC] Netherwing Beta Murloc training other class skills

### ISSUE THREAD

**Issue by ScottieDOESknow** [Atlantiss/NetherwingBugtracker#2060]
**Description**: boosts players; provides gear and training

**Current behaviour**: At level 64, used this NPC to train skills and was trained two skills from other class

arcane blast / steady shot
https://gyazo.com/11ae26435c242845630a0e471543b68c

https://gyazo.com/7ff5516be3a01455b485887c2a506f0f

**Expected behaviour**: NPC should only train skills specific to class

**Server Revision**: 2243 ???

**Comment by ScottieDOESknow** [comment]
I was able to cast arcane blast once on a critter

**Comment by Easyfraggy** [comment]
What class did you get boosted as?

**Comment by ScottieDOESknow** [comment]
I was never boosted. Leveled 1-62 before boost was even available.

**Comment by Easyfraggy** [comment]
But what class are you playing!

**Comment by ScottieDOESknow** [comment]
Playing a rogue. Sorry, I assumed that was obvious from the pictures. :(

**Comment by ircfelix** [comment]
Adding that it does not teach a mage his portals.

**Comment by ircfelix** [comment]
Also the murloc does not teach portals.

**Comment by Wolffenstein** [comment]
Fixed in rev 2275.
