### ISSUE TITLE
[NPC][Hellfire Peninsula] Unfriendly Mag'har

### ISSUE THREAD

**Issue by maxturtlesc2** [Atlantiss/NetherwingBugtracker#2061]
[//]: # (Enclose links to things related to the bug using http://wowhead.com or any other TBC database.)
[//]: # (You can use screenshot ingame to visual the issue.)
[//]: # (Write your tickets according to the format:)
[//]: # ([Quest][Azuremyst Isle] Red Snapper - Very Tasty!)
[//]: # ([NPC] Magistrix Erona)
[//]: # ([Spell][Mage] Fireball)
[//]: # ([Npc][Drop] Ghostclaw Lynx)
[//]: # ([Web] Armory doesnt work)

**Description**: 
Mag'hars does appear friendly (green names) when you first meet them at the unfriendly rep level (orange names).
**Current behaviour**:
Green names when unfriendly.
**Expected behaviour**: 
Names should appear in orange at unfriendly rep.
**Server Revision**:

**Comment by Shanghi** [comment]
Which race and class were you? I'm trying to reproduce it but the colors are working for me.
![image](https://user-images.githubusercontent.com/2672633/47894743-d783ab00-de3a-11e8-80e2-69ba8e85d2c7.png)
![image](https://user-images.githubusercontent.com/2672633/47894751-e8ccb780-de3a-11e8-9741-56d59f54c749.png)
![image](https://user-images.githubusercontent.com/2672633/47894768-f3874c80-de3a-11e8-93b7-4c51184fa2d6.png)

**Comment by maxturtlesc2** [comment]
My bad, it was due to the buff "Guided by the Spirits" from the quest "A Spirit Guide"; makes you friendly as long as you have the buff.
https://www.wowhead.com/spell=29938/guided-by-the-spirits#comments
