### ISSUE TITLE
Shadow Word Pain and likely other debuffs as well.

### ISSUE THREAD

**Issue by AllTheFixins** [Atlantiss/NetherwingBugtracker#2062]
[//]: # (Enclose links to things related to the bug using http://wowhead.com or any other TBC database.)
[//]: # (You can use screenshot ingame to visual the issue.)
[//]: # (Write your tickets according to the format:)
[//]: # ([Quest][Azuremyst Isle] Red Snapper - Very Tasty!)
[//]: # ([NPC] Magistrix Erona)
[//]: # ([Spell][Priest] Shadow Word: Pain)

**Description**: Most likely an issue with any debuffs with different durations.

**Current behaviour**:  If a priest with Improved Shadow Word Pain (+ 6 second duration) in their talents applies their SWP first, an unspecced priest cannot apply his/her own SWP until the initial 6 seconds of priest A's SWP has ticked off. Error message of a more powerful spell is active appears on priest B's screen. Once priest A's SWP isn't higher duration remaining anymore...both debuffs are able to be on the mob simultaneously.

**Expected behaviour**: Priest B should be able to apply SWP regardless of the duration remaining of another priests SWP.

**Server Revision**:

**Comment by Wolffenstein** [comment]
Fixed in rev 2245.
