### ISSUE TITLE
[misc][npc][animation] Strange Dragon Animation

### ISSUE THREAD

**Issue by ircfelix** [Atlantiss/NetherwingBugtracker#2064]
[**Description**: 
If you fly from Stormwind to Burning Steppes, there are some dragons at the south-western edge of The Burning Steppes, occasionally fighting mountaineers.

**Current behaviour**:
When the dragons fly towards the mountaineers, their wings flap extraordinarily fast.

**Expected behaviour**: 
Their wings should not flap that fast, it just looks ridiculous.

**Server Revision**: 
2244

**Comment by Easyfraggy** [comment]
Some video of the issue would be nice.

**Comment by Tereneckla** [comment]
Watched them some time, seems fine.
