### ISSUE TITLE
[Talent][Priest] Surge of Light

### ISSUE THREAD

**Issue by Eidous** [Atlantiss/NetherwingBugtracker#2065]
[//]: # (Enclose links to things related to the bug using http://wowhead.com or any other TBC database.)
[//]: # (You can use screenshot ingame to visual the issue.)
[//]: # (Write your tickets according to the format:)
[//]: # ([Quest][Azuremyst Isle] Red Snapper - Very Tasty!)
[//]: # ([NPC] Magistrix Erona)
[//]: # ([Spell][Mage] Fireball)
[//]: # ([Npc][Drop] Ghostclaw Lynx)
[//]: # ([Web] Armory doesnt work)

**Description**: 
Surge of Light currently gets consumed by normal smite casts, so you never get the benefit of your next smite being instant.

**Current behaviour**:
If you're chaincasting smite, you can queue the next smite before the proc activates, this smite then has a normal cast time while consuming the surge of light buff on completion.

**Expected behaviour**: 
Either the buff should proc on your player faster so that the next smite after the critical smite becomes instant, or a normal cast time smite shouldn't consume the surge of light buff.

**Server Revision**: 
2244

**Comment by Easyfraggy** [comment]
Same as the thing with balance druid few days ago?

**Comment by Erodraeda** [comment]
Can confirm. Pretty annoying bug, tbh

**Comment by Wolffenstein** [comment]
Fixed in rev 2399.
