### ISSUE TITLE
[NPC] Dreadtusk 

### ISSUE THREAD

**Issue by Mewmewww** [Atlantiss/NetherwingBugtracker#2066]
[//]: # (Enclose links to things related to the bug using http://wowhead.com or any other TBC database.)
[//]: # (You can use screenshot ingame to visual the issue.)
[//]: # (Write your tickets according to the format:)
[//]: # ([Quest][Azuremyst Isle] Red Snapper - Very Tasty!)
[//]: # ([NPC] Magistrix Erona)
[//]: # ([Spell][Mage] Fireball)
[//]: # ([Npc][Drop] Ghostclaw Lynx)
[//]: # ([Web] Armory doesnt work)

**Description**: 
As i used the medicin to try and cure the hulking hellboars, it turned into a dreadtusk and stood still, didnt move but only attacked when i went into its melee range.
**Current behaviour**:
As i used the medicin to try and cure the hulking hellboars, it turned into a dreadtusk and stood still, didnt move but only attacked when i went into its melee range.
**Expected behaviour**: 
Should move after u and try to end ur life.
**Server Revision**: 
2244

**Comment by Easyfraggy** [comment]
Proof that he should automaticly agro the player summoning him?

**Comment by Mewmewww** [comment]
> Proof that he should automaticly agro the player summoning him?

Problem wasn't the aggro part, it was the fact that it wouldn't move at all after using the medicin. Assuming if you are a ranged, you would have no problem killing it :p

**Comment by Easyfraggy** [comment]
Ahah I misunderstood. He is rooted. Okay. Easy fix probably.

**Comment by eryczek1615** [comment]
![image](https://user-images.githubusercontent.com/4455568/48219399-b36d2000-e38c-11e8-8015-0354603410f3.png)

There is some Dreadtusks close to the Flacon Watch.
https://imgur.com/zNyMCQ7
https://imgur.com/gtz8gU7
https://imgur.com/yBrl1JD

**Comment by eryczek1615** [comment]
Ok after crash they are Hulking Helboars now.

**Comment by Manaci** [comment]
Fixed
