### ISSUE TITLE
Warriors drop stance on death

### ISSUE THREAD

**Issue by csjansen** [Atlantiss/NetherwingBugtracker#207]
[//]: # (Enclose links to things related to the bug using http://wowhead.com or any other TBC database.)
[//]: # (You can use screenshot ingame to visual the issue.)
[//]: # (Write your tickets according to the format:)
[//]: # ([Quest][Azuremyst Isle] Red Snapper - Very Tasty!)
[//]: # ([NPC] Magistrix Erona)
[//]: # ([Spell][Mage] Fireball)
[//]: # ([Npc][Drop] Ghostclaw Lynx)
[//]: # ([Web] Armory doesnt work)

**Description**: 
Warriors drop stance on death
**Current behaviour**:
When warriors die, they drop their stance which causes their hotbar to swap.
**Expected behaviour**: 
Warriors should keep their stance on death, but be unable to change it until rez.
**Server Revision**:

**Comment by toto6** [comment]
Fixed in Server Revision 2030
