### ISSUE TITLE
[NPC] Rogue Voidwalker and Uncontrolled Voidwalker

### ISSUE THREAD

**Issue by Thorgrimme** [Atlantiss/NetherwingBugtracker#2071]
![wow_2018-11-01_16-46-25](https://user-images.githubusercontent.com/43525297/47862677-f7dd4680-ddf5-11e8-9b84-32963b999a18.jpg)
![wow_2018-11-01_16-47-15](https://user-images.githubusercontent.com/43525297/47862687-fe6bbe00-ddf5-11e8-9a0b-7f10201c4131.jpg)

**Description**: Both mobs collapse on death inflicting roughly 2500 shadow damage, which they shouldnt according to my memory and to this db http://db.hellfire-tbc.com/?npc=16974#abilities.

**Expected behaviour**:  It's only one voidwalker who's suppose to do this in hellfire and it's the collapsing voidwalkers http://db.hellfire-tbc.com/?npc=17014#abilities.

**Server Revision**:

**Comment by Easyfraggy** [comment]
![image](https://user-images.githubusercontent.com/36134067/47868455-8062e380-de04-11e8-96f1-332cd0e3f30e.png)
![image](https://user-images.githubusercontent.com/36134067/47868468-8789f180-de04-11e8-971d-0f2d243ab6f1.png)
![image](https://user-images.githubusercontent.com/36134067/47868483-8e186900-de04-11e8-9ea8-42ebff0b61ad.png)

**Comment by mhdemn** [comment]
would like to add that on top of collapsing voidwalkers being the only ones that collapse, they do not do that on death, but start casting it at a certain health percentage, and it's an interruptible cast, and they can be cc'ed aswell (or killed) to prevent the explosion from happening. Right now they collapse on death regardless of having started their collapse cast, being or not collapsing voidwalkers, being cc'ed when they die, etc.

**Comment by Lampjavel** [comment]
> 
> 
> would like to add that on top of collapsing voidwalkers being the only ones that collapse, they do not do that on death, but start casting it at a certain health percentage, and it's an interruptible cast, and they can be cc'ed aswell (or killed) to prevent the explosion from happening. Right now they collapse on death regardless of having started their collapse cast, being or not collapsing voidwalkers, being cc'ed when they die, etc.

That is intended behavior from retail. Check out the comments [here](https://www.wowhead.com/npc=17014/collapsing-voidwalker#comments) confirming the behavior.

**Comment by mhdemn** [comment]
> > would like to add that on top of collapsing voidwalkers being the only ones that collapse, they do not do that on death, but start casting it at a certain health percentage, and it's an interruptible cast, and they can be cc'ed aswell (or killed) to prevent the explosion from happening. Right now they collapse on death regardless of having started their collapse cast, being or not collapsing voidwalkers, being cc'ed when they die, etc.
> 
> That is intended behavior from retail. Check out the comments [here](https://www.wowhead.com/npc=17014/collapsing-voidwalker#comments) confirming the behavior.

My bad, you're right. I assumed how Ares scripted this was the right way. Good catch btw
Here's a clip showing the damage it does (2k+), in case it's a bit higher than it should be (according to that very wowhead comment). My pet has 2 shadow resistance: https://youtu.be/YTrD5LYzqUc

**Comment by Thorgrimme** [comment]
The collapsing ones does both, starts casting a collapse spell when they get low on hp and collapse once this spell is finished or collapse on death.

**Comment by Daggotur** [comment]
Uncontrolled voidwalkers dont actually attack - they freeze in the animation of casting something and stay that way all time. On the screenshot you can see one hand glowing. 
![wowscrnshot_111218_003616](https://user-images.githubusercontent.com/44930160/48331761-df033b00-e616-11e8-8af8-ca748110b131.jpg)

**Comment by Daggotur** [comment]
Also at this point of time quest item drop rate appears to be 100% although wowhead shows 78% https://www.wowhead.com/npc=16975/uncontrolled-voidwalker#drops
Moreover, after farming them for a while I didnt get a single mote of shadow. Please check their loot table as they used to be the best spot to farm those.

**Comment by Evolvee** [comment]
Fixed the initial report in rev cd, if there is some other issue, report it separately please.

**Comment by Evolvee** [comment]
Also fixed the "hand thingy".
