### ISSUE TITLE
hellfire ramparts- can travelform/ ghostform through the whole instance, can't remember it being like this on retail

### ISSUE THREAD

**Issue by rasin00** [Atlantiss/NetherwingBugtracker#2072]
[//]: # (Enclose links to things related to the bug using http://wowhead.com or any other TBC database.)
[//]: # (You can use screenshot ingame to visual the issue.)
[//]: # (Write your tickets according to the format:)
[//]: # ([Quest][Azuremyst Isle] Red Snapper - Very Tasty!)
[//]: # ([NPC] Magistrix Erona)
[//]: # ([Spell][Mage] Fireball)
[//]: # ([Npc][Drop] Ghostclaw Lynx)
[//]: # ([Web] Armory doesnt work)

**Description**: 

**Current behaviour**:

**Expected behaviour**: 

**Server Revision**:

**Comment by Easyfraggy** [comment]
18:44] Eidous: https://www.youtube.com/watch?v=EB7tOokiD-k this is from wotlk

**Comment by Kuumi** [comment]
if that's the case then you should be able to use a mount since it would technically be 'outdoors'
