### ISSUE TITLE
[NPC] Raging Colossus

### ISSUE THREAD

**Issue by Mewmewww** [Atlantiss/NetherwingBugtracker#2073]
[//]: # (Enclose links to things related to the bug using http://wowhead.com or any other TBC database.)
[//]: # (You can use screenshot ingame to visual the issue.)
[//]: # (Write your tickets according to the format:)
[//]: # ([Quest][Azuremyst Isle] Red Snapper - Very Tasty!)
[//]: # ([NPC] Magistrix Erona)
[//]: # ([Spell][Mage] Fireball)
[//]: # ([Npc][Drop] Ghostclaw Lynx)
[//]: # ([Web] Armory doesnt work)

**Description**: 
Also causing combat bug, even though if its killed.
**Current behaviour**:
Also causing combat bug, even though if its killed.
**Expected behaviour**: 
Shouldn't be in combat after its dead.
**Server Revision**: 
2244

**Comment by Easyfraggy** [comment]
Need more info on this - I get out of combat just fine after killing them.

**Comment by Fenvarien1** [comment]
killed a few with my paladin tank. got 0 problems during the 5/5 kill-quest.

**Comment by Manaci** [comment]
Not an issue anymore
