### ISSUE TITLE
BRD doors close on server crash

### ISSUE THREAD

**Issue by Tenoutoften** [Atlantiss/NetherwingBugtracker#2074]
**Description**: 
[[Object]The Shadowforge Lock#161460](https://db.excalibur.ws/?object=161460)

[[Object]Doodad_BlackRockDoorSingle01#170557](https://db.excalibur.ws/?object=170557)
[[Object]Doodad_BlackRockIronDoor02#170572](https://db.excalibur.ws/?object=170572)

[[Object]Shadowforge Gate#170559](https://db.excalibur.ws/?object=170559)
[[Object]Shadowforge Gate#170560](https://db.excalibur.ws/?object=170560)
[[Object]Supply Room Door#170561](https://db.excalibur.ws/?object=170561)

[[Object]Cell Door#170562](https://db.excalibur.ws/?object=170562)
[[Object]Cell Door#170563](https://db.excalibur.ws/?object=170563)
[[Object]Cell Door#170564](https://db.excalibur.ws/?object=170564)
[[Object]Cell Door#170565](https://db.excalibur.ws/?object=170565)
[[Object]Cell Door#170566](https://db.excalibur.ws/?object=170566)
[[Object]Cell Door#170567](https://db.excalibur.ws/?object=170567)
[[Object]Cell Door#170568](https://db.excalibur.ws/?object=170568)
[[Object]Cell Door#170569](https://db.excalibur.ws/?object=170569)

[[Object]East Garrison Door#170570](https://db.excalibur.ws/?object=170570)
[[Object]Bar Door#170571](https://db.excalibur.ws/?object=170571)

[[Object]Golem Room North#170573](https://db.excalibur.ws/?object=170573)
[[Object]Golem Room South#170574](https://db.excalibur.ws/?object=170574)
[[Object]Thone Room Doors#170575](https://db.excalibur.ws/?object=170575)

[[Object]Doodad_BlackRockDoors01#170556](https://db.excalibur.ws/?object=170556)
[[Object]Doodad_BlackRockDoors02#170576](https://db.excalibur.ws/?object=170576)
[[Object]Doodad_BlackRockDoors03#170577](https://db.excalibur.ws/?object=170577)

[[Object]Relic Coffer Door#174554](https://db.excalibur.ws/?object=174554)
[[Object]Relic Coffer Door#174555](https://db.excalibur.ws/?object=174555)
[[Object]Relic Coffer Door#174556](https://db.excalibur.ws/?object=174556)
[[Object]Relic Coffer Door#174557](https://db.excalibur.ws/?object=174557)
[[Object]Relic Coffer Door#174558](https://db.excalibur.ws/?object=174558)
[[Object]Relic Coffer Door#174559](https://db.excalibur.ws/?object=174559)
[[Object]Relic Coffer Door#174560](https://db.excalibur.ws/?object=174560)
[[Object]Relic Coffer Door#174561](https://db.excalibur.ws/?object=174561)
[[Object]Relic Coffer Door#174562](https://db.excalibur.ws/?object=174562)
[[Object]Relic Coffer Door#174563](https://db.excalibur.ws/?object=174563)
[[Object]Relic Coffer Door#174564](https://db.excalibur.ws/?object=174564)
[[Object]Relic Coffer Door#174566](https://db.excalibur.ws/?object=174566)

[[Object]Dark Coffer#174565](https://db.excalibur.ws/?object=174565)?

**Current behaviour**:
Closes on crash, I am guessing most are closing on crash, I only saw 
[[Object]Shadowforge Gate#170559](https://db.excalibur.ws/?object=170559)
[[Object]Shadowforge Gate#170560](https://db.excalibur.ws/?object=170560)
[[Object]The Shadowforge Lock#161460](https://db.excalibur.ws/?object=161460)

**Expected behaviour**: 
Expected to remain open after crash

**Server Revision**: 
2244

**Comment by Godmatik** [comment]
Closing - all BRD information will be consolidated into one thread
