### ISSUE TITLE
[NPC]ganarg-sapper npc=18827

### ISSUE THREAD

**Issue by wuchermann** [Atlantiss/NetherwingBugtracker#2075]
**Description**: NPC missing Ability https://www.wowhead.com/spell=33895/set-charge

**Comment by Easyfraggy** [comment]
![image](https://user-images.githubusercontent.com/36134067/47869234-b1441800-de06-11e8-9903-0fc6ed14cf42.png)

Don't have it on bestiary - altho there are some flaws in bestiary.

![image](https://user-images.githubusercontent.com/36134067/47869262-d042aa00-de06-11e8-80e9-c585081b07c0.png)

**Comment by Tereneckla** [comment]
Fixed
