### ISSUE TITLE
[Blood Furnace] Shadowmoon Technician: Mines do double damage

### ISSUE THREAD

**Issue by Azalen** [Atlantiss/NetherwingBugtracker#2076]
**Description**: 
http://db.hellfire-tbc.com/?npc=18618
http://db.hellfire-tbc.com/?spell=30846

**Current behaviour**:
Mines trigger the damage twice.
![wowscrnshot_110118_170809](https://user-images.githubusercontent.com/20336567/47864628-63c1ae00-ddfa-11e8-8ead-6ea5047b65d8.jpg)

**Expected behaviour**: 
They should trigger the damage once.

**Server Revision**: 
[2244]

**Comment by Easyfraggy** [comment]
![image](https://user-images.githubusercontent.com/36134067/47869395-2283cb00-de07-11e8-947a-79be57ef7942.png)
Confirmed

**Comment by 25toten** [comment]
I've noticed this as well, looks like it still hasn't be fixed. This is pretty dang annoying.

**Comment by NatsumeLily** [comment]
Bump. A lot of damage for new players in Outlands to deal with, insanely bad for heroics.

**Comment by danbopes** [comment]
Unable to repo (May have been fixed in previous rev):

![](https://i.imgur.com/ds7gsus.png)
