### ISSUE TITLE
[Quest] Natural Remedies.

### ISSUE THREAD

**Issue by Mewmewww** [Atlantiss/NetherwingBugtracker#2077]
[//]: # (Enclose links to things related to the bug using http://wowhead.com or any other TBC database.)
[//]: # (You can use screenshot ingame to visual the issue.)
[//]: # (Write your tickets according to the format:)
[//]: # ([Quest][Azuremyst Isle] Red Snapper - Very Tasty!)
[//]: # ([NPC] Magistrix Erona)
[//]: # ([Spell][Mage] Fireball)
[//]: # ([Npc][Drop] Ghostclaw Lynx)
[//]: # ([Web] Armory doesnt work)

**Description**: 
RP text is a combination of the questline in Terrokar Forest with the mana bomb and the normal quest text with the natural remedies quest.
**Current behaviour**:
RP text is a combination of the questline in Terrokar Forest with the mana bomb and the normal quest text with the natural remedies quest.
**Expected behaviour**: 
Should only have the RP text of natural remedies, taunting us.
**Server Revision**: 
2244

**Comment by Easyfraggy** [comment]
![image](https://user-images.githubusercontent.com/36134067/47869366-0f70fb00-de07-11e8-8b43-aaab5d4c787d.png)

Confirmed

**Comment by aresbrutus** [comment]
https://github.com/Atlantiss/AtlantissTBCBT/issues/3026

**Comment by Manaci** [comment]
Fixed in rev 3134
