### ISSUE TITLE
[NPC][Spell] Arzeth the Merciless's shadowbolt isn't affected by weakening staff

### ISSUE THREAD

**Issue by zauru7** [Atlantiss/NetherwingBugtracker#2081]
[//]: # (Enclose links to things related to the bug using http://wowhead.com or any other TBC database.)
[//]: # (You can use screenshot ingame to visual the issue.)
[//]: # (Write your tickets according to the format:)
[//]: # ([Quest][Azuremyst Isle] Red Snapper - Very Tasty!)
[//]: # ([NPC] Magistrix Erona)
[//]: # ([Spell][Mage] Fireball)
[//]: # ([Npc][Drop] Ghostclaw Lynx)
[//]: # ([Web] Armory doesnt work)

**Description**: 
Doing quest https://www.wowhead.com/quest=10369/arzeths-demise you get a staff to weaken Arzeth to reduce his damage, however his shadowbolt damage is unnaffected and thus still hits for as much as the elite version does. 

**Current behaviour**:
Shadow bolt spell hits for ~1700(notice he is in his "powerless" mode)
![newww](https://user-images.githubusercontent.com/44526051/47867323-7e4b5580-de01-11e8-9266-c202018c480f.PNG)

**Expected behaviour**: 
His shadowbolt should also get reduced damage
![neww2](https://user-images.githubusercontent.com/44526051/47867520-0598c900-de02-11e8-89e9-1715f27661d4.PNG)

**Server Revision**: 
2244

**Comment by Easyfraggy** [comment]
Need confirmation of this, I believe Kutsal tested this? @aresbrutus

**Comment by aresbrutus** [comment]
Correct, the physical damage is reduced but not his shadow bolts.

**Comment by Wolffenstein** [comment]
Fixed in rev 3414.
