### ISSUE TITLE
[Quest] Disrupt Their Reinforcements

### ISSUE THREAD

**Issue by Phibs77** [Atlantiss/NetherwingBugtracker#2083]
[//]: # (Enclose links to things related to the bug using http://wowhead.com or any other TBC database.)
[//]: # (You can use screenshot ingame to visual the issue.)
[//]: # (Write your tickets according to the format:)
[//]: # ([Quest][Azuremyst Isle] Red Snapper - Very Tasty!)
[//]: # ([NPC] Magistrix Erona)
[//]: # ([Spell][Mage] Fireball)
[//]: # ([Npc][Drop] Ghostclaw Lynx)
[//]: # ([Web] Armory doesnt work)

**Description**: Players in party not getting credit for destroying gateways.

**Current behaviour**: Only the player destroying the gateways gets credit for it.

**Expected behaviour**: Players in group should also get credit for destroying gateways.
( https://www.wowhead.com/quest=10208/disrupt-their-reinforcements#comments:id=20739 )

**Server Revision**: 2244

**Comment by ttghnw** [comment]
Low drop rate on demonic stones?

**Comment by ttghnw** [comment]
Seems fixed today :o

**Comment by Wolffenstein** [comment]
Fixed in rev 3425.
