### ISSUE TITLE
[NPC] Boulderfist Mage spell cooldown

### ISSUE THREAD

**Issue by Ahmpy** [Atlantiss/NetherwingBugtracker#2085]
[//]: # (Enclose links to things related to the bug using http://wowhead.com or any other TBC database.)
[//]: # (You can use screenshot ingame to visual the issue.)
[//]: # (Write your tickets according to the format:)
[//]: # ([Quest][Azuremyst Isle] Red Snapper - Very Tasty!)
[//]: # ([NPC] Magistrix Erona)
[//]: # ([Spell][Mage] Fireball)
[//]: # ([Npc][Drop] Ghostclaw Lynx)
[//]: # ([Web] Armory doesnt work)

**Description**: 
In its current state i think these mobs are overtuned, immediately upon engaging these mobs they fire blast the player for ~1700 damage, then will promptly frost bolt and blast again. Most players will have around 5k hp so this makes me think that a mob doing nearly 4k damage in 2 uninterruptable casts (usually around 5-6 seconds between the two instants) is a little off.

**Server Revision**: 
2244

**Comment by Easyfraggy** [comment]
![image](https://user-images.githubusercontent.com/36134067/47869774-1c421e80-de08-11e8-9cc6-13fd9bbea147.png)

Probably needs longer initial on fire blast and longer CD's?

**Comment by Ahmpy** [comment]
Yeah it has the correct spells afaik, I'm just worried that non sustain classes specifically will get trucked by these mobs because even if they kill the mob they will be like 20% hp each mob they kill

**Comment by sifiuocz** [comment]
https://www.wowhead.com/npc=17137/boulderfist-mage#comments

> Just take note, this mob is able to use an instant cast fire spell, similar to that of a mages "Fire Blast". It hits for approximately 1k damage. (Patch 2.0.8)

> Watch out if you get below 2k hp on these...they fire blast for upwards of 1k. (Patch 2.3.2)

**Comment by Sparkaj** [comment]
watched 3 people die to those mobs today.  1 mage links with another and they player takes 3 fireblasts+ bolts...plus the mobs are spawning very close to each other

**Comment by sifiuocz** [comment]
https://i.imgur.com/tV9IKva.jpg
In this picture you can see that the NPC uses it's Fire Blast every 4 seconds. It's definitely too short of a cooldown.

**Comment by Tenoutoften** [comment]
I have found a video of this mob from retail

https://www.youtube.com/watch?v=4WN7b9BGf8U

https://youtu.be/4WN7b9BGf8U?t=54 - Frostbolt hits 450
https://youtu.be/4WN7b9BGf8U?t=54 - Fireblast hits 975
https://youtu.be/4WN7b9BGf8U?t=88 - Frostbolt hits 365
https://youtu.be/4WN7b9BGf8U?t=116 - Frostbolt hits 412
https://youtu.be/4WN7b9BGf8U?t=123 - Frostbolt hits 435
https://youtu.be/4WN7b9BGf8U?t=129 - Fireblast hits 1003

So now you have wowhead comments & video from retail displaying lower damage

**Comment by Tenoutoften** [comment]
I found some """"evidence"""" of 700dmg frostbolts is from MOP-expansion:
https://youtu.be/OluhJc_FGCw?t=78 - 707 frostbolt
https://youtu.be/OluhJc_FGCw?t=81 - 807 frostbolt
https://youtu.be/OluhJc_FGCw?t=123 - 727 frostbolt
https://youtu.be/OluhJc_FGCw?t=125 - 439 fire blast

**Comment by Tenoutoften** [comment]
Damage is fine now in 2304

**Comment by Evolvee** [comment]
Seems no longer valid. Please retest/reopen if the issue persists.
