### ISSUE TITLE
[Quest] By Any Means Necessary

### ISSUE THREAD

**Issue by netherwingbta** [Atlantiss/NetherwingBugtracker#2089]
[//]: # (Enclose links to things related to the bug using http://wowhead.com or any other TBC database.)
[//]: # (You can use screenshot ingame to visual the issue.)
[//]: # (Write your tickets according to the format:)
[//]: # ([Quest][Azuremyst Isle] Red Snapper - Very Tasty!)
[//]: # ([NPC] Magistrix Erona)
[//]: # ([Spell][Mage] Fireball)
[//]: # ([Npc][Drop] Ghostclaw Lynx)
[//]: # ([Web] Armory doesnt work)

**Description**: 
https://www.wowhead.com/quest=9978/by-any-means-necessary
**Current behaviour**:
You're able to click the quest completion option before you fight him.
![wow 2018-11-01 19-29-38-09](https://user-images.githubusercontent.com/43872263/47871871-6da0dc80-de0d-11e8-9437-0654116be6d3.jpg)
Doesn't do anything though when you try to complete it, until you actually beat him though.
![wow 2018-11-01 19-31-14-07](https://user-images.githubusercontent.com/43872263/47871863-67aafb80-de0d-11e8-8047-092b42453858.jpg)

**Expected behaviour**: 
The quest completion screen should be hidden until you beat him close to death. 
https://www.youtube.com/watch?v=CF00bZHv9Tk
**Server Revision**: 
2244

**Comment by DeltaLoads** [comment]
also his body guard shouldn't be immortal
![capture](https://user-images.githubusercontent.com/43690147/47916655-2cf5a180-dea7-11e8-9923-d5db4ae7a124.PNG)

https://streamable.com/ske84

**Comment by Corrozus** [comment]
To add to the above. I tried completing this quest, and while Empoor has the dialogue option to complete the quest I wasn't able to complete it. Trying to do the quest normally just results in him dying.

I've tried the quest 4 times now without luck. I've disabled all addons and cleared my cache. Nothing works.

**Comment by Mikik3jr** [comment]
When I did this quest i beated him up, then the NPC went back to his own patrol, but attacked me again with his 1% HP left, but after 1 attack and 1 frost shock he went back to patrol again.

**Comment by mhdemn** [comment]
Well, for me it just let me kill Empoor (instead of him being unable to drop from 1% and become friendly) as seen on this [video](https://youtu.be/5Yax_Ms5J6U) (sorry I missed the part where I kill him) 
server revision 2253

**Comment by Wolffenstein** [comment]
Fixed in rev 3404.
