### ISSUE TITLE
Leatherworking, Glove Reinforcements.

### ISSUE THREAD

**Issue by Erodraeda** [Atlantiss/NetherwingBugtracker#2090]
[//]: # (Enclose links to things related to the bug using http://wowhead.com or any other TBC database.)
[//]: # (You can use screenshot ingame to visual the issue.)
[//]: # (Write your tickets according to the format:)
[//]: # ([Quest][Azuremyst Isle] Red Snapper - Very Tasty!)
[//]: # ([NPC] Magistrix Erona)
[//]: # ([Spell][Mage] Fireball)
[//]: # ([Npc][Drop] Ghostclaw Lynx)
[//]: # ([Web] Armory doesnt work)

**Description**: 
The Recipe Glove Reinforcements was only added in the patch 2.3.0, not being available before that.
**Current behaviour**:
![screenshot_663](https://user-images.githubusercontent.com/40346279/47872657-f1e36780-dded-11e8-934a-2c01a3a0500a.png)
**Expected behaviour**: 
Should only be available after patch 2.3.0, with mats required being reduced from 18 Heavy Knothide Leather, 14 Primal Earth and 1 Rune Thread to the ones in the screenshot, in 2.4.2.
Font: http://wowwiki.wikia.com/wiki/Glove_Reinforcements
**Server Revision**: 2244

**Comment by aresbrutus** [comment]
Seems we forgot to remove this from the trainer, should be fixed in rev `Triton`
