### ISSUE TITLE
Den Grunt Valley of Trials Levels

### ISSUE THREAD

**Issue by ttghnw** [Atlantiss/NetherwingBugtracker#2092]
[//]: # (Enclose links to things related to the bug using http://wowhead.com or any other TBC database.)
[//]: # (You can use screenshot ingame to visual the issue.)
[//]: # (Write your tickets according to the format:)
[//]: # ([Quest][Azuremyst Isle] Red Snapper - Very Tasty!)
[//]: # ([NPC] Magistrix Erona)
[//]: # ([Spell][Mage] Fireball)
[//]: # ([Npc][Drop] Ghostclaw Lynx)
[//]: # ([Web] Armory doesnt work)

**Description**: **Current behaviour**:
All the grunts have disparate levels like 64, 51, 58, 55, I'm not sure this is blizzlike, I believe starting area npcs are always updated to the proper EP's cap equivalent, being tougher than the average guard etc.

I'm not 100% sure on this so bear with me.

**Expected behaviour**: 

**Server Revision**:

**Comment by Wolffenstein** [comment]
Fixed in rev 3414.
