### ISSUE TITLE
([NPC] Fel Soldier)

### ISSUE THREAD

**Issue by boringdawg** [Atlantiss/NetherwingBugtracker#2093]
**Description**: 
4 Fel Soldiers spawn at Gateway Murketh, however, one of them has a weird pathing issue. The others spawn on the ground below the Gateway, which also seems a bit off.
**Current behaviour**:
https://youtu.be/cgDKF_rMGsI
**Expected behaviour**: 
The mob that bugs out and levitates/falls down over and over should spawn alongside his buddies and walk like they do. And they should probably all spawn on the Gateway, not inside it like they do now.
**Server Revision**: 
2245

**Comment by Tereneckla** [comment]
They still spawn below the gateway floor, but their movement is fine otherwise.

**Comment by Evolvee** [comment]
is this the infernals for stairs of destiny(dark portal) event?

**Comment by Tereneckla** [comment]
Fel Soldiers(18944) for stairs of destiny

**Comment by Evolvee** [comment]
then its wolfs shitto script :lulw:
