### ISSUE TITLE
[Quest] Voidwalkers Gone Wild

### ISSUE THREAD

**Issue by Erodraeda** [Atlantiss/NetherwingBugtracker#2094]
[//]: # (Enclose links to things related to the bug using http://wowhead.com or any other TBC database.)
[//]: # (You can use screenshot ingame to visual the issue.)
[//]: # (Write your tickets according to the format:)
[//]: # ([Quest][Azuremyst Isle] Red Snapper - Very Tasty!)
[//]: # ([NPC] Magistrix Erona)
[//]: # ([Spell][Mage] Fireball)
[//]: # ([Npc][Drop] Ghostclaw Lynx)
[//]: # ([Web] Armory doesnt work)

**Description**: 
In this quest, the beam that buffs the voidwalker is buffing other targets, and going off of the voidwalker, instead of the vortex.
**Current behaviour**:
https://imgur.com/a/rSOrQKo
**Expected behaviour**: 
The beam should go from the Vortex to the voidwalker, buffing him, as you can see in this video https://www.youtube.com/watch?v=-2z8CuWM9lQ
**Server Revision**:

**Comment by Erodraeda** [comment]
Update: Apparently, it only ever targets pets

**Comment by Wolffenstein** [comment]
Different beam, working correctly.
