### ISSUE TITLE
[Rogue] [Talent] Remorseless Attacks talent doesn't work

### ISSUE THREAD

**Issue by NikiProToss** [Atlantiss/NetherwingBugtracker#2095]
[//]: # (Enclose links to things related to the bug using http://wowhead.com or any other TBC database.)
[//]: # (You can use screenshot ingame to visual the issue.)
[//]: # (Write your tickets according to the format:)
[//]: # ([Quest][Azuremyst Isle] Red Snapper - Very Tasty!)
[//]: # ([NPC] Magistrix Erona)
[//]: # ([Spell][Mage] Fireball)
[//]: # ([Npc][Drop] Ghostclaw Lynx)
[//]: # ([Web] Armory doesnt work)

**Description**: Remorseless Attacks talent doesn't work

**Current behaviour**: Remorseless Attacks talent should proc when you kill an NPC or an enemy player that yields experience or honor.

**Expected behaviour**: Remorseless Attacks talent doesn't proc after killing a mob of your level range.

**Server Revision**: 2245

**Comment by NikiProToss** [comment]
For some reason it happened to me but now it's consistently works as intended. I will update this post with a prove if it happens again.

**Comment by Easyfraggy** [comment]
Reopen if you find out how to cause it. Works fine for me.
