### ISSUE TITLE
[Spell][Priest] Shadowform

### ISSUE THREAD

**Issue by Thugli** [Atlantiss/NetherwingBugtracker#2096]
[//]: # (Enclose links to things related to the bug using http://wowhead.com or any other TBC database.)
[//]: # (You can use screenshot ingame to visual the issue.)
[//]: # (Write your tickets according to the format:)
[//]: # ([Quest][Azuremyst Isle] Red Snapper - Very Tasty!)
[//]: # ([NPC] Magistrix Erona)
[//]: # ([Spell][Mage] Fireball)
[//]: # ([Npc][Drop] Ghostclaw Lynx)
[//]: # ([Web] Armory doesnt work)

**Description**: 
Shadowform is greyed out and is unable to be casted, despite having a full mana bar. When pressing shadowform, I receive the following error message: "That spell is not ready yet". There was no obvious trigger for this bug, I only noticed it when a mob aggroed me and I attempted to enter shadowform.
**Current behaviour**:
https://clips.twitch.tv/HandsomeOilySheepBibleThump
**Expected behaviour**: 
As long as the player has enough mana, they should be able to enter shadowform.
**Server Revision**: 
2244

**Comment by Jezofine** [comment]
Got this about 3 times, can't see any trigger. Last time I was mashing dummy in Shattr for about 15 mins and noticed that my Shadowform is not totally dark as usual. I canceled shadowform and it got on permanent cooldown.

**Comment by Evolvee** [comment]
I reported this like 3 years ago. https://github.com/Atlantiss/AtlantissTbcBTOLD/issues/1095

**Comment by Wolffenstein** [comment]
Fixed in rev 2448.
