### ISSUE TITLE
[NPC][Quest] A Burden of Souls

### ISSUE THREAD

**Issue by Erodraeda** [Atlantiss/NetherwingBugtracker#2097]
[//]: # (Enclose links to things related to the bug using http://wowhead.com or any other TBC database.)
[//]: # (You can use screenshot ingame to visual the issue.)
[//]: # (Write your tickets according to the format:)
[//]: # ([Quest][Azuremyst Isle] Red Snapper - Very Tasty!)
[//]: # ([NPC] Magistrix Erona)
[//]: # ([Spell][Mage] Fireball)
[//]: # ([Npc][Drop] Ghostclaw Lynx)
[//]: # ([Web] Armory doesnt work)

**Description**: 
The NPC Shattered Hand Berserker (ID 16878, entry 11) is not giving credit for the quest.
**Current behaviour**:
That NPC is not giving credit for the quest, meanwhile all the others are
**Expected behaviour**: 
All "Shattered Hand" mobs should give credit for this quest.
**Server Revision**:

**Comment by aresbrutus** [comment]
https://github.com/Atlantiss/NetherwingBugtracker/issues/2286

**Comment by Wolffenstein** [comment]
Fixed in rev 2406.

**Comment by skami1** [comment]
[A Burden of Souls] is broken again!
