### ISSUE TITLE
Cross faction murder after a duel

### ISSUE THREAD

**Issue by n12o** [Atlantiss/NetherwingBugtracker#2098]
[//]: # (Enclose links to things related to the bug using http://wowhead.com or any other TBC database.)
[//]: # (You can use screenshot ingame to visual the issue.)
[//]: # (Write your tickets according to the format:)
[//]: # ([Quest][Azuremyst Isle] Red Snapper - Very Tasty!)
[//]: # ([NPC] Magistrix Erona)
[//]: # ([Spell][Mage] Fireball)
[//]: # ([Npc][Drop] Ghostclaw Lynx)
[//]: # ([Web] Armory doesnt work)

**Proof**: [Screenshot](https://imgur.com/a/SC8LJJA)

**Description**: You are able to kill other faction players after a duel.

**Current behaviour**: you are attacking enemy player of ther faction despite duel has ended.

**Expected behaviour**: You shouldn't be able to attack an enemy player after a duel if you were not able to do it before a duel.

**Server Revision**: 2245

**Comment by Easyfraggy** [comment]
You shouldn't be able to duel a player from the other faction xD

**Comment by killablink** [comment]
Well technically you can duel cross-faction if you're in the opposite's faction territory and the other person has pvp toggled off.

**Comment by killablink** [comment]
You could do that on a PVP server, I never played on a PVE server

**Comment by ttghnw** [comment]
Well it is possible with /duel on private servers in any area, usually, don't recall retail

**Comment by Easyfraggy** [comment]
I would love some retail evidence of a cross faction duel, I have never ever heard of this before!

**Comment by killablink** [comment]
"If you're at a faction capital even on a PVP server they are not always flagged for PVP, you can /duel and it will drop the flag.

You can then /ready emote and that lets the enemy faction member know you're ready go rock.

They can then do the same, and start the duel.

Was very very common in Vanilla even on PVP servers."

https://us.battle.net/forums/en/wow/topic/20768286707

WoW Icon 16x16 Patch 1.2.3 (22-Feb-2005): Dueling across factions remains intact in the patch, in consideration of players' desires to duel members of the opposing faction.

It was a thing back in the days

**Comment by Unfairy** [comment]
What? Ofc you can duel people from other factions. Pvp toggled off or on doesnt matter

**Comment by killablink** [comment]
I am pretty sure you can't duel pvp flagged people in their territory as I remember having to wait a while when people messed up and got pvp flagged. Also it wouldn't make sense because if you duel someone pvp flagged you can just kill him right after.

**Comment by Easyfraggy** [comment]
Hmm nice, you learn something new every day I suppose. 👍

**Comment by Unfairy** [comment]
Ye and I remember that I did it in retail.
And people with honor leave people alive after duel even if they can kill you.

**Comment by Unfairy** [comment]
The point is. When you wanna have a fair fight with someone and you both pvp tagged you will end with killing each other. But sometimes people wanna just settle stuff between them, thats what duels for. So we did duels even when we can just pvp to death. Btw same applied to, for example gurubashi arena.
