### ISSUE TITLE
Ressurection bug

### ISSUE THREAD

**Issue by loljeema123** [Atlantiss/NetherwingBugtracker#21]
[//]: # (Enclose links to things related to the bug using http://wowhead.com or any other TBC database.)
[//]: # (You can use screenshot ingame to visual the issue.)
[//]: # (Write your tickets according to the format:)
[//]: # ([Quest][Azuremyst Isle] Red Snapper - Very Tasty!)
[//]: # ([NPC] Magistrix Erona)
[//]: # ([Spell][Mage] Fireball)
[//]: # ([Npc][Drop] Ghostclaw Lynx)
[//]: # ([Web] Armory doesnt work)

**Description**: I died for testing purpose ofc

**Current behaviour**: I Can't ress accept button doesn't happen.

**Expected behaviour**: Suppose to ress when i click accept

**Server Revision**:

**Comment by Dimbleglim** [comment]
This issue is still around.
