### ISSUE TITLE
Paladin Class Quest - Claiming the Light

### ISSUE THREAD

**Issue by ThaWhizz** [Atlantiss/NetherwingBugtracker#210]
[//]: # (Enclose links to things related to the bug using http://wowhead.com or any other TBC database.)
[//]: # (You can use screenshot ingame to visual the issue.)
[//]: # (Write your tickets according to the format:)
[//]: # ([Quest][Azuremyst Isle] Red Snapper - Very Tasty!)
[//]: # ([NPC] Magistrix Erona)
[//]: # ([Spell][Mage] Fireball)
[//]: # ([Npc][Drop] Ghostclaw Lynx)
[//]: # ([Web] Armory doesnt work)

**Description**: 
Blood Elf Paladin quest is bugged. when using the flask on M'uru in Silvermoon City nothing happens and the flask is spent. 
**Current behaviour**:

**Expected behaviour**: 

**Server Revision**:

**Comment by ThaWhizz** [comment]
I apologize if this is a duplicate, but I haven't seen anyone else post about this issue.

**Comment by wtRCH** [comment]
No worries :P
