### ISSUE TITLE
[NPC] - Parched Hydra

### ISSUE THREAD

**Issue by Bleachlol** [Atlantiss/NetherwingBugtracker#2101]
**Description**: 
Parched Hydra does an ability with the name: Heat Wave, but it has no spell animation (can't see the spell being casted). 

Damage is also over tuned: 
By Sware (15,415 – 7·41·83) on 2006/12/11 (Patch 2.0.1): Near and inside the dead mire, they have a ability called heatwave that deals 1300-1400 damage (fire). https://www.wowhead.com/npc=20324/parched-hydra#comments

**Current behaviour**:
Heat wave has no spell animation. 

**Expected behaviour**: 
Should look like this https://www.wowhead.com/spell=35236/heat-wave#screenshots:id=86751

**Server Revision**: 
2244

EDIT: added damage modifier

**Comment by Easyfraggy** [comment]
They are using the correct spell. Damage is correct, they are using it way too often though.

**Comment by Unfairy** [comment]
Hit rating getting reduced by 35%. I hit under this debuff about 1/20 hits. Looks like hit rating reduce is also reduced too much.

**Comment by Unfairy** [comment]
![wowscrnshot_110318_111226](https://user-images.githubusercontent.com/41975070/47949748-fffdc900-df50-11e8-907b-388908c31437.jpg)
3 heat waves statistics. 14 melee, 12 mangle - hit rating 0%
Was tryint to hit only when I was under debuff

**Comment by zauru7** [comment]
can confirm what Unfairy posted, couldn't hit the mob at all(0% hits) when I had the debuff

the hit rating modifier is for sure bugged, not at all 35% reduction as intended(feels closer to 100%)

**Comment by numiee** [comment]
are we getting any updates on this? still to this date bugged...

**Comment by The14me** [comment]
Rev.3451. the animation is still missing.Dmg wise look fine.

**Comment by aeturnum** [comment]
Heat wave still seems to cause a 100% miss chance on Karazhan with rev 3509

**Comment by aeturnum** [comment]
Brief example: https://www.twitch.tv/videos/710803523

**Comment by Wolffenstein** [comment]
Fixed
