### ISSUE TITLE
[Quest]: Arelion's Secret // [NPC]Magister Aledis: bug when losing it's target

### ISSUE THREAD

**Issue by mhdemn** [Atlantiss/NetherwingBugtracker#2102]
https://wotlk-twinhead.twinstar.cz/?quest=10286
https://wotlk-twinhead.twinstar.cz/?npc=20159

**Description**: During Arelion's secret quest, the NPC you gotta fight in order to deliver the quest bugs out big time if you feign death as a hunter.
*He's a friendly NPC patrolling a path, he has a dialogue option if you are on the right quest that makes him hostile, then you fight him until a certain hp threshold that I can't remember and he turns friendly, you can deliver the quest and pick up the following, and then I'm unsure if he despawns or keeps patrolling.

**Current behaviour**: If you feign death while fighting him (after dialoguing with him and before getting him to the health threshold needed to make him friendly) he'll go nuts.
In the video I hit record after bugging him for the first time, luckily (or maybe not so luckily) he fought me so I could reproduce the bug. After that he wouldn't fight me back, he'd just keep walking for a while.
Here I bug him with Feign Death: https://youtu.be/SeNxgYKtKY4
Here he keeps walking and not fighting back: https://youtu.be/yiMYD69zTE0
He despawned shortly after turning around at Zangarmarsh border

**Expected behaviour**: Not sure, I guess when he loses it's target it should be like he managed to kill the player, so he goes back to patrolling as a friendly npc with the dialogue option available for the next player to come.

**Server Revision**: 2244

Edit1: (same revision)
Just confirming it works fine if he doesn't lose his target due to Feign Death. Altho during the fight with him I leave-reenter combat a bunch of times, not sure why. Pet doesn't bug due to this though, so it's okay regardless. After the fight he stands for a minute in complete quest mode, then mounts back up and resumes his patrol - as I think is intended and should be.

**Comment by Retinus** [comment]
Server Revision: 2295

The npc have a ? over his head and you can deliver the quest without the need to fight with him.

From wowhead comments:
He doesn't have a ? over his head, so you have to look at his name. Go up to him and talk to him, and after you talk he'll dismount and attack you. Once you get him to 20% (it's an easy fight), he'll give you the next quest in the chain.

[Source](https://www.wowhead.com/quest=10286/arelions-secret)

**Comment by mhdemn** [comment]
> Server Revision: 2295
> 
> The npc have a ? over his head and you can deliver the quest without the need to fight with him.
> 
> From wowhead comments:
> He doesn't have a ? over his head, so you have to look at his name. Go up to him and talk to him, and after you talk he'll dismount and attack you. Once you get him to 20% (it's an easy fight), he'll give you the next quest in the chain.
> 
> [Source](https://www.wowhead.com/quest=10286/arelions-secret)

Perhaps somebody else just finished it half a minute before, and he was in friendly phase 2 (after combat) still?

**Comment by Retinus** [comment]
Dunno, but if that's the case you can ignore my report. I cba testing this possibility (or any other).

**Comment by eryczek1615** [comment]
When I defeated him and turned back [Aerlion's Secret](https://www.wowhead.com/quest=10286/arelions-secret) I read description of the next quest but after few seconds he returned to patrolling and now I can't take the next [Quest](https://www.wowhead.com/quest=10287/the-mistress-revealed). He doesn't have "!" mark above his head.

![image](https://user-images.githubusercontent.com/4455568/53984929-aaae1000-411a-11e9-9b1c-7330cd8a6fb5.png)

**Comment by The14me** [comment]
Rev.3451 FD and Not able to take the next one bug's look like fixed. Cant reproduce both of them.
can be closed.
