### ISSUE TITLE
[Hellfire Peninsula] Leashing on Blistering Rot/Oozeling

### ISSUE THREAD

**Issue by Kuumi** [Atlantiss/NetherwingBugtracker#2103]
[//]: # (Enclose links to things related to the bug using http://wowhead.com or any other TBC database.)
[//]: # (You can use screenshot ingame to visual the issue.)
[//]: # (Write your tickets according to the format:)
[//]: # ([Quest][Azuremyst Isle] Red Snapper - Very Tasty!)
[//]: # ([NPC] Magistrix Erona)
[//]: # ([Spell][Mage] Fireball)
[//]: # ([Npc][Drop] Ghostclaw Lynx)
[//]: # ([Web] Armory doesnt work)

**Description**: 
In pools of Aggonar when skipping all the mobs to get to Arazzius the Cruel for [Cruel's Intentions] the mobs that were aggro'd do not de-aggro and unleash after a certain distance.
**Current behaviour**:
Blistering Rot and Blistering Oozeling continued to leash despite no damage done to them.
**Expected behaviour**: 
After a certain distance of not being attacked, the mob should reset.
**Server Revision**: 
2244

**Comment by Kuumi** [comment]
Just saw another post about the same thing, sorry!

**Comment by nvyblu** [comment]
This is still ocuring as of 11.8.2018 
<img width="1193" alt="screen shot 2018-11-08 at 12 53 10 pm" src="https://user-images.githubusercontent.com/44880889/48227125-58203b00-e356-11e8-9227-0bd8d9f5e858.png">
<img width="1199" alt="screen shot 2018-11-08 at 12 53 35 pm" src="https://user-images.githubusercontent.com/44880889/48227131-5b1b2b80-e356-11e8-86b6-b3a470ed43cd.png">
<img width="1186" alt="screen shot 2018-11-08 at 12 54 53 pm" src="https://user-images.githubusercontent.com/44880889/48227137-5e161c00-e356-11e8-9a9f-64f243e77f51.png">

**Comment by Easyfraggy** [comment]
this is a duplicate issue - posting your pics here wont help - anyway we are aware and know how to fix but Kutsal and me are limited on time atm so it wont be fixed super fast.
