### ISSUE TITLE
[Hellfire Peninsula][Pools of Aggonar] Random instances of entering and leaving combat

### ISSUE THREAD

**Issue by Kuumi** [Atlantiss/NetherwingBugtracker#2104]
[//]: # (Enclose links to things related to the bug using http://wowhead.com or any other TBC database.)
[//]: # (You can use screenshot ingame to visual the issue.)
[//]: # (Write your tickets according to the format:)
[//]: # ([Quest][Azuremyst Isle] Red Snapper - Very Tasty!)
[//]: # ([NPC] Magistrix Erona)
[//]: # ([Spell][Mage] Fireball)
[//]: # ([Npc][Drop] Ghostclaw Lynx)
[//]: # ([Web] Armory doesnt work)

**Description**: 
When walking around pools of aggonar, my character will enter combat for several seconds and then drop combat
**Current behaviour**:
Entering combat with no NPC around.
**Expected behaviour**: 
Should not enter combat when outside aggro range of mob.
**Server Revision**: 
2244

**Comment by Easyfraggy** [comment]
https://github.com/Atlantiss/NetherwingBugtracker/issues/2040
