### ISSUE TITLE
[Quest] Foot of the Citadel

### ISSUE THREAD

**Issue by mhdemn** [Atlantiss/NetherwingBugtracker#2107]
https://tbc-twinhead.twinstar.cz/?npc=19264
https://tbc-twinhead.twinstar.cz/?npc=22374
https://tbc-twinhead.twinstar.cz/?quest=10876

**Description**: Corpse of Force-Commander Gorax not usable to spawn quest npc.

**Current behaviour**: After killing Gorax we should be able to use the provided quest item on the dead body to spawn the NPC we need the item from to complete the quest. Game doesn't detect the body as seen on the video: https://youtu.be/sRPSiLU7NFI

**Expected behaviour**: We should be able to use [Challenge of the Horde] on Gorax' body to spawn Hand of Kargath, kill it and collect the item.

**Server Revision**: 2244

**Comment by mhdemn** [comment]
Update: tried again today, revision 2244 too. This time it worked flawlessly, seems the bug I found yesterday was a one time thing, maybe. Could use more people commenting here if they found any issue, see if it was a random thing or happens consistently given certain conditions.

**Comment by Corrozus** [comment]
Just attempted this quest. Killed Force-Command Gorax twice. Each time I tried using the Challenge from the Horde banner it said "Requires Force-Command Gorax's body", despite me standing right on top of him

Server Revision: 2272

**Comment by Tahvo2** [comment]
Tried to do the quest today, was not able to plant the flag on Gorax's body.

**Comment by naekobest** [comment]
https://i.gyazo.com/99e7d8d0eb772bdec546e9cf37be7dcb.mp4

**Comment by perkydon** [comment]
Attempted today, the same issue presented itself.

**Comment by Tereneckla** [comment]
Does not work if pet got the killing blow on the Commander.

**Comment by Evolvee** [comment]
fixed in next rev
