### ISSUE TITLE
Leatherworking UI bugged after 300+

### ISSUE THREAD

**Issue by ScottieDOESknow** [Atlantiss/NetherwingBugtracker#2109]
Trained leatherworking in lower city and now my profession window is missing all sub-categories, many spells (old & new) are out of order for their level and/or missing, and the UI will visually bug if I try to click or scroll in main window. Clicking the + button seems to reset the list after it bugs.

clicking
https://gyazo.com/cd50d13bc7f6fcac9348621bbac8f192

scrolling
https://gyazo.com/4e42c8d69efcb21b34039964bab97777

also to note: I recorded the clips with no addons

**Expected behaviour**: should function as normal

**Server Revision**: 2244

**Comment by ScottieDOESknow** [comment]
bugged tooltips for these specific spells

ammo pouch
https://gyazo.com/5dfb72b46071da855c1e197ea63dbace

quiver
https://gyazo.com/7279dbbfdf7a3d603f0e654107b06d12

**Comment by ScottieDOESknow** [comment]
After many tries (clicking on the spell in book) and then getting the error message about old mats (heavy leather) being required, I was able to craft Thick Draenic Pants. 

https://gyazo.com/569b4c081005f51aa712fcb27c678a62

**Comment by wowthings** [comment]
Happens to me too, exactly the same, the list is completely butchered. 
Purged cache, wtf and interface folder and stays the same.

**Comment by wowthings** [comment]
Downloaded the client that NW provides at Discord just to doublecheck. It is still fucked.

**Comment by aresbrutus** [comment]
This might be related to the patch progression where some items are removed from ingame while still being trainable by the profession trainers.

**Comment by ScottieDOESknow** [comment]
The only two items I know that aren't in game yet, are the ammo pouch and quiver. they were added in 2.3 which explains the missing tooltip. Rest of items are overlapping spell in the book with old vanilla items so I assume incorrect item ids.

Currently at 335 LW and I can't even find find the spell to convert TBC scraps in my book anymore. It's just gone now.

https://gyazo.com/fd20f77e47540ea9f3379123719225e8

**Comment by wowthings** [comment]
Use this macro until they fix the issue
/use Leatherworking
/run for i=1,GetNumTradeSkills() do if GetTradeSkillInfo(i)=="**NAMEOFTHESKILL**" then DoTradeSkill(i, GetItemCount("**NAMEOFTHESKILL**")/5) break end end

**Comment by xmesaj2** [comment]
most likely current itemization

**Comment by aresbrutus** [comment]
Fixed in rev `Triton`

Make sure to unlearn and re-learn LW to fix the UI issue.
