### ISSUE TITLE
[Quest][Bloodmyst Isle] Kessel's Elekk 

### ISSUE THREAD

**Issue by Avatarstate** [Atlantiss/NetherwingBugtracker#211]
[//]: # (Enclose links to things related to the bug using http://wowhead.com or any other TBC database.)
[//]: # (You can use screenshot ingame to visual the issue.)
[//]: # (Write your tickets according to the format:)
[//]: # ([Quest][Azuremyst Isle] Red Snapper - Very Tasty!)
[//]: # ([NPC] Magistrix Erona)
[//]: # ([Spell][Mage] Fireball)
[//]: # ([Npc][Drop] Ghostclaw Lynx)
[//]: # ([Web] Armory doesnt work)

**Description**: 
The mount feels like a 60% mount but the tooltip says it should be 100%
**Current behaviour**:
The Kessel's elekk buff and actual spead don't match
**Expected behaviour**: 
Either the mount should be 100% or the tooltip should be 60%, I dont know which is actually correct though. 
**Server Revision**: 
2028

**Comment by Sinyr** [comment]
Seemed weird to me too. The model is that of a 60% mount and it felt that way, but when I checked the tooltip it actually said it's 100%.

**Comment by Evolvee** [comment]
![image](https://user-images.githubusercontent.com/1942409/45949192-5fd08e00-bffb-11e8-8983-621bf7a639e5.png)
it should be 100% mount
