### ISSUE TITLE
[NPC] Umbrafen Witch doctor [Totem] Terror totem

### ISSUE THREAD

**Issue by Mewmewww** [Atlantiss/NetherwingBugtracker#2111]
[//]: # (Enclose links to things related to the bug using http://wowhead.com or any other TBC database.)
[//]: # (You can use screenshot ingame to visual the issue.)
[//]: # (Write your tickets according to the format:)
[//]: # ([Quest][Azuremyst Isle] Red Snapper - Very Tasty!)
[//]: # ([NPC] Magistrix Erona)
[//]: # ([Spell][Mage] Fireball)
[//]: # ([Npc][Drop] Ghostclaw Lynx)
[//]: # ([Web] Armory doesnt work)

**Description**: 
Fear is on a 0.1 second duration, making the ability completely obsolete.
**Current behaviour**:
Fear is on a 0.1 second duration, making the ability completely obsolete.
**Expected behaviour**: 
Should be longer.
**Server Revision**: 
2244

**Comment by The14me** [comment]
https://www.wowhead.com/spell=35197/terror-totem#comments:id=187045
Look fine to me.Please re-test.
