### ISSUE TITLE
[Quest]Mission: The Murketh and Shaadraz Gateways

### ISSUE THREAD

**Issue by DeadManStomping** [Atlantiss/NetherwingBugtracker#2113]
**Description**: Bombing run doesn't work if you go right behind someone

**Current behaviour**: The bombs will drop, but as long as the building is on fire (last about 2-3 minutes) you can't bomb it.

**Expected behaviour**: Either the party should get credit or despite being on fire they should be bombable.

**Server Revision**:

**Comment by Easyfraggy** [comment]
https://github.com/Atlantiss/NetherwingBugtracker/issues/1993
