### ISSUE TITLE
fear rubberbanding

### ISSUE THREAD

**Issue by genetheparmesan** [Atlantiss/NetherwingBugtracker#2116]
[//]: # (Enclose links to things related to the bug using http://wowhead.com or any other TBC database.)
[//]: # (You can use screenshot ingame to visual the issue.)
[//]: # (Write your tickets according to the format:)
[//]: # ([Quest][Azuremyst Isle] Red Snapper - Very Tasty!)
[//]: # ([NPC] Magistrix Erona)
[//]: # ([Spell][Mage] Fireball)
[//]: # ([Npc][Drop] Ghostclaw Lynx)
[//]: # ([Web] Armory doesnt work)

**Description**: 
[//]: # ([Spell][Warlock] Fear)
[//]: # ([Spell][Warlock] Death Coil)
**Current behaviour**:
teleporting players only in pvp. unable to determine location of person feared until the end of fear

**Expected behaviour**: see where they are running around

**Server Revision**:

**Comment by teddys** [comment]
This has somehow returned and is now a current issue once again. Almost impossible for a melee player to attack feared players.
