### ISSUE TITLE
[Core Mechanic][NPC] Raging Colossus

### ISSUE THREAD

**Issue by ezzekielfox** [Atlantiss/NetherwingBugtracker#2117]
[//]: # ([NPC] Raging Colossus)
[//]: # ([Core Mechanic] Melee Range)

**Description**: Raging Colossus has a melee range issue where it thinks it's in range until it shrinks, but doesn't move closer.

**Current behaviour**: Raging Colossus will attack in range, but if it shrinks due to its mechanic whenever it reaches certain health thresholds, it stops being in range, but stands still trying to attack.

**Expected behaviour**: Raging Colossus should adjust location if not in range after it has shrunk.

**Server Revision**:

**Comment by Mikik3jr** [comment]
If you stun the colossus it won't lose its size during stun.

**Comment by Easyfraggy** [comment]
Possibly same issue: https://github.com/Atlantiss/NetherwingBugtracker/issues/2175

**Comment by Tereneckla** [comment]
Fixed
