### ISSUE TITLE
Quest: Chen's empty keg

### ISSUE THREAD

**Issue by Buskmurvel** [Atlantiss/NetherwingBugtracker#212]
[//]: # (Enclose links to things related to the bug using http://wowhead.com or any other TBC database.)
https://www.wowhead.com/quest=819/chens-empty-keg
[//]: # (You can use screenshot ingame to visual the issue.)
[//]: # (Write your tickets according to the format:)
[//]: # ([Quest][Azuremyst Isle] Red Snapper - Very Tasty!)
[//]: # ([NPC] Magistrix Erona)
[//]: # ([Spell][Mage] Fireball)
[//]: # ([Npc][Drop] Ghostclaw Lynx)
[//]: # ([Web] Armory doesnt work)

**Description**: 
The quests start in Barrens, with you picking up a barrel. At either 55, 27 or 45, 65.

**Current behaviour**:
The barrel (or keg) is not there at all.

**Expected behaviour**: 

**Server Revision**:

**Comment by Shanghi** [comment]
There's a lot more places than just those 2. Stock was missing the other spawn points, so that's probably why people got used to just going to those. And just in case, I looted it several times just now to make sure it's really spawning at them.
