### ISSUE TITLE
[Misc] Rakoria spelling mistake

### ISSUE THREAD

**Issue by netherwingbta** [Atlantiss/NetherwingBugtracker#2121]
[//]: # (Enclose links to things related to the bug using http://wowhead.com or any other TBC database.)
[//]: # (You can use screenshot ingame to visual the issue.)
[//]: # (Write your tickets according to the format:)
[//]: # ([Quest][Azuremyst Isle] Red Snapper - Very Tasty!)
[//]: # ([NPC] Magistrix Erona)
[//]: # ([Spell][Mage] Fireball)
[//]: # ([Npc][Drop] Ghostclaw Lynx)
[//]: # ([Web] Armory doesnt work)

**Description**: 
"ot" instead of to
**Current behaviour**:
[Rakoria](https://www.wowhead.com/npc=18385/rakoria) misspelling

![wow 2018-11-02 07-09-57-61](https://user-images.githubusercontent.com/43872263/47897893-de7adf80-de73-11e8-95bf-db6d68a8ff13.jpg)

**Server Revision**: 
2244

**Comment by Sabre142** [comment]
She is also saying holiday stuff that the Christmas goblins should be saying which is weird.

**Comment by The14me** [comment]
rev. 3451 It looks fine now.
https://i.imgur.com/PMDQiH1.png
Can be closed.
