### ISSUE TITLE
[NPC] Warp Stalker, Timber Worg Alpha, Timber Worg double spawn

### ISSUE THREAD

**Issue by netherwingbta** [Atlantiss/NetherwingBugtracker#2122]
[//]: # (Enclose links to things related to the bug using http://wowhead.com or any other TBC database.)
[//]: # (You can use screenshot ingame to visual the issue.)
[//]: # (Write your tickets according to the format:)
[//]: # ([Quest][Azuremyst Isle] Red Snapper - Very Tasty!)
[//]: # ([NPC] Magistrix Erona)
[//]: # ([Spell][Mage] Fireball)
[//]: # ([Npc][Drop] Ghostclaw Lynx)
[//]: # ([Web] Armory doesnt work)

**Description**: 
Just south of Shattrath there are Warp Stalkers and worgs that are double-spawning.
**Current behaviour**:
![wow 2018-11-02 07-56-35-87](https://user-images.githubusercontent.com/43872263/47898704-41ba4100-de77-11e8-817a-43a5bfc1b3e4.jpg)
![wow 2018-11-02 07-56-57-77](https://user-images.githubusercontent.com/43872263/47898724-5565a780-de77-11e8-9e72-70ae58d57838.jpg)
![wow 2018-11-02 08-06-20-37](https://user-images.githubusercontent.com/43872263/47898740-6f9f8580-de77-11e8-986a-29b048771f3d.jpg)
![wow 2018-11-02 08-17-55-24](https://user-images.githubusercontent.com/43872263/47898869-f8b6bc80-de77-11e8-88d7-52e20d939cfa.jpg)
![wow 2018-11-02 08-12-31-91](https://user-images.githubusercontent.com/43872263/47898868-f7858f80-de77-11e8-823f-1f1e34dd469f.jpg)
Cleared the area once to check and they do respawn as double.
May be more.
**Expected behaviour**: 

**Server Revision**: 
2244

**Comment by Easyfraggy** [comment]
These all have same ID, not my mistake afaik?

**Comment by Easyfraggy** [comment]
Attempting hackfixerino in rev biosphere.

Please recheck after you see my file added on changelog it will get a rev number.
