### ISSUE TITLE
[Quest] Missing Friends

### ISSUE THREAD

**Issue by netherwingbta** [Atlantiss/NetherwingBugtracker#2124]
[//]: # (Enclose links to things related to the bug using http://wowhead.com or any other TBC database.)
[//]: # (You can use screenshot ingame to visual the issue.)
[//]: # (Write your tickets according to the format:)
[//]: # ([Quest][Azuremyst Isle] Red Snapper - Very Tasty!)
[//]: # ([NPC] Magistrix Erona)
[//]: # ([Spell][Mage] Fireball)
[//]: # ([Npc][Drop] Ghostclaw Lynx)
[//]: # ([Web] Armory doesnt work)

**Description**: 
[Missing Friends](https://www.wowhead.com/quest=10852/missing-friends) not working. Nothing happens when you open the cages.
**Current behaviour**:
The kids just stands still when you open the cages and you don't get credit for the quest.
![missingfriends](https://user-images.githubusercontent.com/43872263/47900244-83011f80-de7c-11e8-9339-8c770ee130d2.jpg)

**Expected behaviour**: 
The kids are supposed to run away.
https://www.youtube.com/watch?v=3iHpcxqTdcc&t=130
**Server Revision**: 
2244

**Comment by Sparkaj** [comment]
confirmed

**Comment by Easyfraggy** [comment]
https://github.com/Atlantiss/NetherwingBugtracker/issues/2180

**Comment by Evolvee** [comment]
rev XXX
