### ISSUE TITLE
[NPC] Firewing Bloodwarder

### ISSUE THREAD

**Issue by netherwingbta** [Atlantiss/NetherwingBugtracker#2125]
[//]: # (Enclose links to things related to the bug using http://wowhead.com or any other TBC database.)
[//]: # (You can use screenshot ingame to visual the issue.)
[//]: # (Write your tickets according to the format:)
[//]: # ([Quest][Azuremyst Isle] Red Snapper - Very Tasty!)
[//]: # ([NPC] Magistrix Erona)
[//]: # ([Spell][Mage] Fireball)
[//]: # ([Npc][Drop] Ghostclaw Lynx)
[//]: # ([Web] Armory doesnt work)

**Description**: 
[Firewing Bloodwarder's](https://www.wowhead.com/npc=1410/firewing-bloodwarder#abilities) Shadow shock does too much damage and probably has too low of a cooldown.
**Current behaviour**:
Hits for 1248-1400.
![wow 2018-11-02 09-21-46-96](https://user-images.githubusercontent.com/43872263/47905774-30c5fb80-de88-11e8-9164-6a86e62fcffb.jpg)

Don't know about the mana tap ability since i tested on a warrior.

**Expected behaviour**: 
Wowhead comments suggest 700-800
https://www.wowhead.com/npc=1410/firewing-bloodwarder#comments:id=21689
https://www.wowhead.com/npc=1410/firewing-bloodwarder#comments:id=48501
https://www.wowhead.com/npc=1410/firewing-bloodwarder#comments:id=55199:reply=297223
on retail they seemed to be hitting for even less, around 400
https://www.youtube.com/watch?v=UBUj2D2qH0M
**Server Revision**: 
2244

**Comment by Tenoutoften** [comment]
retail values are usually wack, its good for how the mobs behave-ish, emotes, rp, but values are more or less useless unfortunately... But it was definitely dealing too much damage.

rev 2304 dmg
**739**-746-748-762-773-**796**

**Comment by Evolvee** [comment]
Issue seems to be invalid as of now.

Feel free to reopen if the issue persist.
