### ISSUE TITLE
[NPC] Firewing Warlock

### ISSUE THREAD

**Issue by netherwingbta** [Atlantiss/NetherwingBugtracker#2129]
[//]: # (Enclose links to things related to the bug using http://wowhead.com or any other TBC database.)
[//]: # (You can use screenshot ingame to visual the issue.)
[//]: # (Write your tickets according to the format:)
[//]: # ([Quest][Azuremyst Isle] Red Snapper - Very Tasty!)
[//]: # ([NPC] Magistrix Erona)
[//]: # ([Spell][Mage] Fireball)
[//]: # ([Npc][Drop] Ghostclaw Lynx)
[//]: # ([Web] Armory doesnt work)

**Description**: 
[Firewing Warlocks](https://www.wowhead.com/npc=16769/firewing-warlock#abilities) abilities hitting for too much.
**Current behaviour**:
Shadow bolts are hitting for around 900-1000.
Immolate seems to also do too much, couldn't find much.  Ticks were doing 52dmg on the retail footage, compared to 168.
![wow 2018-11-02 09-45-03-39](https://user-images.githubusercontent.com/43872263/47906564-cd3ccd80-de89-11e8-9d84-3387764d7893.jpg)

Wasn't able to test mana tap.
**Expected behaviour**: 
Wowhead comments suggest ~500 dmg for shadowbolt.
https://www.wowhead.com/npc=16769/firewing-warlock#comments:id=42157
Seems to match retail
![warlock](https://user-images.githubusercontent.com/43872263/47906325-4556c380-de89-11e8-88dd-27f8dddfd3b6.jpg)
https://www.youtube.com/watch?v=ol1X4AWCHfM
**Server Revision**: 
2244

**Comment by mhdemn** [comment]
They hit quite a bit yeah, but it matches the general vibe of spell damages in Outland. The melee firewing elves though, those need tweaking. 
Related to these Netherwing Warlocks, they're found in this place Firewing Point channeling some spell into a rune in the ground, facing each other in couples. They're not linked together and I think they should be.

**Comment by Easyfraggy** [comment]
They were definitely not hardlinked on retail.

**Comment by mhdemn** [comment]
Either way, make them all linked or unlinked, some linked and some not is def not blizzlike

**Comment by mhdemn** [comment]
I mean I dont wanna be a pain in the ass, the zone will be okay after the bloodwarders' shock is tuned down, the linking thing doesn't really need to be changed, the zone is like it's meant to be -challenging-. Just posting for perfectionism's sake. It's your decision, if you feel it's ok and Im making fuzz out of nowhere close the issue right away, I don't mean to waste your time.

**Comment by Tereneckla** [comment]
Damage is fixed
