### ISSUE TITLE
[Zangarmash] Pure Water

### ISSUE THREAD

**Issue by maxturtlesc2** [Atlantiss/NetherwingBugtracker#2132]
[//]: # (Enclose links to things related to the bug using http://wowhead.com or any other TBC database.)
[//]: # (You can use screenshot ingame to visual the issue.)
[//]: # (Write your tickets according to the format:)
[//]: # ([Quest][Azuremyst Isle] Red Snapper - Very Tasty!)
[//]: # ([NPC] Magistrix Erona)
[//]: # ([Spell][Mage] Fireball)
[//]: # ([Npc][Drop] Ghostclaw Lynx)
[//]: # ([Web] Armory doesnt work)
<img src="https://i.imgur.com/ULiVQOY.jpg">
**Description**:
https://www.wowhead.com/object=182951/pure-water#contains
http://wowwiki.wikia.com/wiki/Pure_Water
**Current behaviour**:
Pure Water found in Zangarmash.
**Expected behaviour**: 
Pure Water can only be found in Nagrand.
**Server Revision**:

**Comment by aresbrutus** [comment]
Make sure you don't delete those in elemental plateau as they might be shown as being in Zangarmash map. @Evolvee

**Comment by Evolvee** [comment]
rev XXX
