### ISSUE TITLE
[Quest] - Spirit Ally? 

### ISSUE THREAD

**Issue by Bleachlol** [Atlantiss/NetherwingBugtracker#2133]
**Description**: 
You put down a totem on the ground which will spawn the serpent. 

**Current behaviour**:
https://imgur.com/a/J2kkHnP - Only the Serpent is spawning at the moment. 

**Expected behaviour**: 
There should also be a totem that is being placed on the ground. 

https://www.wowhead.com/quest=9847/a-spirit-ally#screenshots:id=64072 
https://www.wowhead.com/quest=9847/a-spirit-ally#videos:id=55318 
**Server Revision**: 
2244

**Comment by Tenoutoften** [comment]
Totem provided by the quest: [[Item]Feralfen Totem#24498](https://www.wowhead.com/item=24498/feralfen-totem) - works
Uses when activated: [[Spell]Place Feralfen Totem#32037](https://db.excalibur.ws/?spell=32037) which "Send Script Event (11413)" suppose this spawns the totem [[NPC]Feralfen Totem#18186](https://db.excalibur.ws/?npc=18186) which can be seen [here on retail](https://youtu.be/Q4arqsSIPvA?t=147), the player hovers over the totem revealing the name.


[[NPC]Feralfen Totem#18186](https://db.excalibur.ws/?npc=18186) spawned by

**Comment by The14me** [comment]
Also u can spawn Infinity numbers of serpent's.

**Comment by Evolvee** [comment]
fixed in next rev
