### ISSUE TITLE
ID 5, [NPC]Fen Strider#18134 has errors in patrol path and goes under ground

### ISSUE THREAD

**Issue by Tenoutoften** [Atlantiss/NetherwingBugtracker#2134]
**Description**: 
ID 5, [[NPC]Fen Strider#18134](https://www.wowhead.com/npc=18134/fen-strider) has errors in patrol path and goes under ground several places, followed by haltered walking animation for a few seconds.
[ID 5, [NPC]Fen Strider#18134 patrol, NW-vid](https://youtu.be/F4QCwhguZ8o)

**Expected behaviour**: 
To walk regularly

**Server Revision**: 
2244

**Comment by Easyfraggy** [comment]
Fixed in rev biosphere
