### ISSUE TITLE
[Quest][Hellfire Penninsula] Avruu's Orb

### ISSUE THREAD

**Issue by zauru7** [Atlantiss/NetherwingBugtracker#2135]
[//]: # (Enclose links to things related to the bug using http://wowhead.com or any other TBC database.)
[//]: # (You can use screenshot ingame to visual the issue.)
[//]: # (Write your tickets according to the format:)
[//]: # ([Quest][Azuremyst Isle] Red Snapper - Very Tasty!)
[//]: # ([NPC] Magistrix Erona)
[//]: # ([Spell][Mage] Fireball)
[//]: # ([Npc][Drop] Ghostclaw Lynx)
[//]: # ([Web] Armory doesnt work)

**Description**: 
During the quest Avruu's Orb(https://www.wowhead.com/quest=9418/avruus-orb) you can not correctly interact with the orb object. It simply says "invalid target" making it impossible to complete the quest.
(relog/reload did not fix the issue)
**Current behaviour**:
You can not get up any options(you simply get invalid target error) https://imgur.com/a/7Jybzut 
**Expected behaviour**: 
You are supposed to get up a gossip option to summon Avruu and complete the quest
**Server Revision**: 
2244

**Comment by killablink** [comment]
I was able to do it and complete it on server rev 2244

**Comment by craigsurbrook** [comment]
Killablink said he could do it (14 hrs ago). However, I just experienced the same exact issue as zauru7. It is exactly as he has described.

**Comment by craigsurbrook** [comment]
Follow up, 15 mins later. I discarded the orb and dropped the quest. Killed Avruu, reaquired the orb and took the quest, and the alter object still says "Invalid object", like as if it's the alter itself that is bugged (perhaps from a previous use).

**Comment by Evolvee** [comment]
I cant reproduce this.

**Comment by craigsurbrook** [comment]
My toon in game is Icehole, alliance Gnome rogue. I have gone back to check the alter and it still says "Invalid Object". So my toon still seems to reflect the problem (I have the quest, it says "complete", and the next step is to click the orb alter to summon and fight Avruu).
Would it help if a GM saw this happen in game? With my account's toon?

**Comment by mhdemn** [comment]
revision 2256 - Seems bug keeps happening now and then, trigger remains unidentified.

Invalid Target (when clicking altar) bug happened 5 hours ago, playing a rogue. However, players Xyxz and Dajnfehr (mage and paladin) interacted with the altar without an issue yesterday.

Don't know what might be the trigger, something stance-related? What class were you playing @zauru7 and @killablink ? All I see in common here is two of the people that couldn't get it to work were rogues. Maybe some passive or aura from the class' talents?

**Comment by killablink** [comment]
I was on a mage

**Comment by zauru7** [comment]
I was playing a feral druid, don't know if class affects this. It's odd that the results differ so much, wonder what the trigger is.

**Comment by mhdemn** [comment]
I see stealthy classes finding trouble with this quest with the little data I got

**Comment by Notmittz** [comment]
Experiencing this problem still, on a druid (balance).  Tried it twice, resetting client, abandoning fully and deleting orb, picking up new one and re-attempting, using stealth, not using stealth, etc.  Still gives 'Invalid Target'

**Comment by zauru7** [comment]
Late addition: I was able to complete the quest despite not being able to use the orb(as video in OP shows). Another player was present who was able to use the orb, and thus both of us could complete the quest. The player who was able to use it was a paladin, I could not use it and I'm a druid. 

It looks to be class related based on the reports here, lots of consistensy with some classes being able to complete it and others not(but it might also just be a correlation). Either way the bug is very much still present and makes the quest impossible to complete for many players

**Comment by koychevd** [comment]
Invalid Target and unable to interact with the orb. Draenei shammy "Tikva". Tried:
relogging
abandoning and retaking
destroying the orb and getting it again

**Comment by ianams** [comment]
Also seeing the invalid target on this object, 60 shaman. 

I had a similar problem with the mudsnout blossoms in Hillsbrad foothills, maybe there's a clue in that.

**Comment by Manaci** [comment]
Fixed

**Comment by sk6868** [comment]
Karazhan server July 26, 2024.  
The bug is still there.

**Comment by Godmatik** [comment]
Are you using 3.3.5 client? 
It does not give me any sort of "invalid target" error

**Comment by Godmatik** [comment]
Even on 3.3.5 client I am not getting any such error.

Close your game, delete cache folder, and disable add-ons @sk6868

**Comment by sk6868** [comment]
I am using the 2.4.3 client

**Comment by sk6868** [comment]
https://github.com/user-attachments/assets/df3dfbc0-3e1b-4630-b6fc-301e9fda78d7

**Comment by sk6868** [comment]
https://github.com/user-attachments/assets/2953e48e-f0c7-43b2-9413-1a0fbbd92df3

cache deleted, all addons were disabled. @Godmatik 
P.S. I don't get any kind of invalid target either.  It simply does not work as in the screen capture.

**Comment by Godmatik** [comment]
Unable to reproduce the issue, and no one else has mentioned it either. Just tested yet again and as I was there I saw someone else just do the quest by talking to the orb. I suspect issue with your client.

**Comment by sk6868** [comment]
Additional information:
my client is from 
https://wowdl.net/client/World-of-Warcraft-2.4.3.8606-enUS
