### ISSUE TITLE
[NPC]Dreghood Drudge#18122 doesn't use [Spell]Shared Bonds#34789

### ISSUE THREAD

**Issue by Tenoutoften** [Atlantiss/NetherwingBugtracker#2136]
**Description**: 
[[NPC]Dreghood Drudge#18122](https://www.wowhead.com/npc=18122/dreghood-drudge#comments) doesn't use their [[Spell]Shared Bonds#34789](https://www.wowhead.com/spell=34789/shared-bonds) spell in order to have [[Spell]Shared Bonds#34788](https://www.wowhead.com/spell=34788/shared-bonds) activated when they fight. 
Picture with it activated from wowhead [here](https://wow.zamimg.com/uploads/screenshots/normal/52890-shared-bonds.jpg)
[Video from retail here](https://youtu.be/DPrw5I7H0RM?t=297)

This is the reason this NPC is almost exclusively found in pairs

**Expected behaviour**: 
Suppose to apply this ability as soon as they are engaged.

**Server Revision**: 
2244

**Comment by Tenoutoften** [comment]
I've seen some of them use the shared bonds now, but they have been lacking the animation

**Comment by fantom8** [comment]
They use shared bonds but the damage is not actually shared in the proper amount. I can bring one of them to half HP and the other one will still be sitting at 100% even though they both have the buff on themselves.

**Comment by KevinTyrrell** [comment]
Shared bonds does not split the damage correctly as @fantom8 commented. Hope this can be fixed.

**Comment by Evolvee** [comment]
fixed
