### ISSUE TITLE
[NPC]Wrekt Slave#18123 doesn't use [Spell]Shared Bonds#34789

### ISSUE THREAD

**Issue by Tenoutoften** [Atlantiss/NetherwingBugtracker#2137]
**Description**: 
[[NPC]Wrekt Slave#18123](https://www.wowhead.com/npc=18123/wrekt-slave) doesn't use their [[Spell]Shared Bonds#34789](https://www.wowhead.com/spell=34789/shared-bonds) spell in order to have [[Spell]Shared Bonds#34788](https://www.wowhead.com/spell=34788/shared-bonds) activated when they fight. 
Picture with it activated from wowhead [here](https://wow.zamimg.com/uploads/screenshots/normal/52890-shared-bonds.jpg)
[Video from retail here](https://youtu.be/DPrw5I7H0RM?t=297)

This is the reason this NPC is almost exclusively found in pairs

**Expected behaviour**: 
Suppose to apply this ability as soon as they are engaged.

**Server Revision**: 
2244

**Comment by Evolvee** [comment]
fixed
