### ISSUE TITLE
"Steady shot" on mage

### ISSUE THREAD

**Issue by justicex123** [Atlantiss/NetherwingBugtracker#2139]
[//]: # (Enclose links to things related to the bug using http://wowhead.com or any other TBC database.)
[//]: # (You can use screenshot ingame to visual the issue.)
[//]: # (Write your tickets according to the format:)
[//]: # ([Quest][Azuremyst Isle] Red Snapper - Very Tasty!)
[//]: # ([NPC] Magistrix Erona)
[//]: # ([Spell][Mage] Fireball)
[//]: # ([Npc][Drop] Ghostclaw Lynx)
[//]: # ([Web] Armory doesnt work)

**Description**: 
Learned "Steady shot" as mage at lvl 62
**Current behaviour**:
![wowscrnshot_110218_130810](https://user-images.githubusercontent.com/44686384/47910717-c2436680-dea4-11e8-99fe-6ea9abac1155.jpg)

**Expected behaviour**: 

**Server Revision**:

**Comment by ttghnw** [comment]
haha =D

**Comment by ircfelix** [comment]
Bug is already known.

**Comment by Easyfraggy** [comment]
This was due to the boost NPC - not a problem in general.
