### ISSUE TITLE
[NPC] Bloodmyst Hatchling

### ISSUE THREAD

**Issue by Avatarstate** [Atlantiss/NetherwingBugtracker#214]
[//]: # (Enclose links to things related to the bug using http://wowhead.com or any other TBC database.)
[//]: # (You can use screenshot ingame to visual the issue.)
[//]: # (Write your tickets according to the format:)
[//]: # ([Quest][Azuremyst Isle] Red Snapper - Very Tasty!)
[//]: # ([NPC] Magistrix Erona)
[//]: # ([Spell][Mage] Fireball)
[//]: # ([Npc][Drop] Ghostclaw Lynx)
[//]: # ([Web] Armory doesnt work)

**Description**: 
Bloodmyst Hatchling doesnt drop loot
**Current behaviour**:
Not dropping loot
**Expected behaviour**:
Should drop loot
**Server Revision**:  2028

**Comment by Evolvee** [comment]
https://github.com/Atlantiss/NetherwingBugtracker/issues/363 duplicate

**Comment by Avatarstate** [comment]
Sorry for the duplicate - I searched and didnt find anything before I posted. :(

**Comment by Evolvee** [comment]
yea its not your fault, the issue posted above is a duplicate but it has a link comment inside it so i choosed that to stay open
