### ISSUE TITLE
[NPC]Darkcrest Slaver#19946 should immediately "calls for a nearby slave to assist him!"

### ISSUE THREAD

**Issue by Tenoutoften** [Atlantiss/NetherwingBugtracker#2140]
**Description**: 
[[NPC]Darkcrest Slaver#19946](https://www.wowhead.com/npc=19946/darkcrest-slaver#comments) should immediately "calls for a nearby slave to assist him!" once engaged, can be seen here:
https://youtu.be/QOgS605h7yU?t=73
![8bf88cc40adf1062fc8a877795769e75](https://user-images.githubusercontent.com/34839199/47910829-4e995d80-de94-11e8-8a0f-597f1fd3feea.png)

**Current behaviour**:
Sometimes uses it on 50%

**Expected behaviour**: 
[[NPC]Darkcrest Slaver#19946](https://www.wowhead.com/npc=19946/darkcrest-slaver#comments) should immediately "calls for a nearby slave to assist him!" once engaged

**Server Revision**: 
2244

**Comment by Mikik3jr** [comment]
I confirm this. Around 50% hp it called for help.

**Comment by Bildo** [comment]
fixed in rev 2413
