### ISSUE TITLE
[NPC] Dreghood Drudge missing spell

### ISSUE THREAD

**Issue by Mikik3jr** [Atlantiss/NetherwingBugtracker#2144]
[//]: # (Enclose links to things related to the bug using http://wowhead.com or any other TBC database.)
[//]: # (You can use screenshot ingame to visual the issue.)
[//]: # (Write your tickets according to the format:)
[//]: # ([Quest][Azuremyst Isle] Red Snapper - Very Tasty!)
[//]: # ([NPC] Magistrix Erona)
[//]: # ([Spell][Mage] Fireball)
[//]: # ([Npc][Drop] Ghostclaw Lynx)
[//]: # ([Web] Armory doesnt work)

**Description**: 
In Zangarmash Dreghood Drudges are in pairs and they have a spell called [Shared Bonds].(https://www.wowhead.com/npc=18122/dreghood-drudge#abilities)
**Current behaviour**:
They don't cast this spell to each other.
**Expected behaviour**: 
They should.
**Server Revision**: 
2244

**Comment by Tenoutoften** [comment]
Already reported: https://github.com/Atlantiss/NetherwingBugtracker/issues/2136

**Comment by Mikik3jr** [comment]
Sorry, when I filtered te search bar didn't find it.
