### ISSUE TITLE
[Quest] [Terokkar Forest] Escaping the Tomb escort = CRASH SERVER?

### ISSUE THREAD

**Issue by ScottieDOESknow** [Atlantiss/NetherwingBugtracker#2146]
**Description**: Escaping the Tomb escort quest in Shadow tomb

**Current behaviour**: After starting this quest within few seconds the server crashes. Replicated 3 times total.

**Expected behaviour**: Should not crash server.

**Server Revision**:  2244

**Comment by wowthings** [comment]
I did that quest without any problems, maybe it was a little coincidence?

**Comment by Sparkaj** [comment]
Happened to me twice as well.  Also happened a couple times when I was near the quest giver, but didn't click him yet, that may have been coincidence though.

**Comment by Bleachlol** [comment]
This quest did not work at all for me, abonded the quest and accepted it twice, nothing happened, https://imgur.com/a/MNvXjkn

Best video of this quest I could find was this one : https://www.wowhead.com/quest=10887/escaping-the-tomb#videos:id=84274

**Comment by Easyfraggy** [comment]
It's been temporarily disabled due to causing crashes @Bleachlol untill wolf can recreate it on local so he can fix it.

**Comment by Thorgrimme** [comment]
Quest npc doesnt assist with hostile npc's, ending up with fighting 2 and quest npc spawning 3 other mobs.

**Comment by Tenoutoften** [comment]
Worked fine when I did it and I witnessed another player do it after me too.
One issue though, I am unable to bless / heal [[NPC]Akuno#22377](https://www.wowhead.com/npc=22377/akuno)(the quest giver)
Can be seen [here](https://www.youtube.com/watch?v=E3qfkXT-tuY&feature=youtu.be)

**Comment by Easyfraggy** [comment]
this has been solved, can you open a new issue on that part Arma?

**Comment by Firroth** [comment]
I don't know if it was just a coincidence or not, but crash happened today for me too, when being near this npc. Can't really know if it's related or just bad luck, cause I didn't test during p2 so I wouldn't know if it's the same issue xD
