### ISSUE TITLE
[Quest] Taken in the night

### ISSUE THREAD

**Issue by netherwingbta** [Atlantiss/NetherwingBugtracker#2150]
[//]: # (Enclose links to things related to the bug using http://wowhead.com or any other TBC database.)
[//]: # (You can use screenshot ingame to visual the issue.)
[//]: # (Write your tickets according to the format:)
[//]: # ([Quest][Azuremyst Isle] Red Snapper - Very Tasty!)
[//]: # ([NPC] Magistrix Erona)
[//]: # ([Spell][Mage] Fireball)
[//]: # ([Npc][Drop] Ghostclaw Lynx)
[//]: # ([Web] Armory doesnt work)

**Description**: 
You get xp from killing the super low hp [netherwing victims](https://www.wowhead.com/npc=22355/netherweb-victim).
**Current behaviour**:
https://www.wowhead.com/quest=10873/taken-in-the-night
![wow 2018-11-02 12-44-01-82](https://user-images.githubusercontent.com/43872263/47913994-47774d00-de9e-11e8-9131-8d80dec0d9c5.jpg)

**Expected behaviour**: 
You should not get xp for killing the web.
https://www.youtube.com/watch?v=U9mYTrSskbg
**Server Revision**: 
2244

**Comment by mhdemn** [comment]
2255
Can't find legit footage besides later xpac retail videos, but it certainly feels like the change of getting the [Sha'tar Warriors](https://tbc-twinhead.twinstar.cz/?npc=22459) inside the [Netherweb Victims](https://www.wowhead.com/npc=22355/netherweb-victim) is very low. I cleared the whole area where these are twice and got 2/6.

Also, as it happens with other quests and situations, pet's killing blows on the victims won't spawn anything out of them.

**Comment by 5f3759** [comment]
Yeah the netherweb victim rate is very very low.
I cleared the entire area 7 times nad got 2/6.

**Comment by Kidcudi123** [comment]
yes very long quest atm and this whole thread should be in the high prio

**Comment by 5f3759** [comment]
The issue with the cocoons seem to be that respawn rate of the warriors inside.
I tried the quest early in the morning and had about a 33% success rate, which is a lot higher then before. I also didn't have any empty cocoons this time.

**Comment by xmesaj2** [comment]
exp fixed by wolf earlier in 2262, respawn 2317
