### ISSUE TITLE
[Quest] Leader of the Bloodscale

### ISSUE THREAD

**Issue by Needorfeed** [Atlantiss/NetherwingBugtracker#2151]
**Description**: 
Seems the freezing circle follows players around, instead of being put down where it is initially cast.

**Current behaviour**:
Freezing circle follows players while being cast, instead of being cast where it is initially cast.
This makes the mob near impossible as is, with frostbolts being cast so often.

**Expected behaviour**: 
Freezing circle should be placed where it is initially cast. (I'm 99% sure)

**Server Revision**:

**Comment by xmesaj2** [comment]
#2361
