### ISSUE TITLE
[NPC] Rajys Fyashe seems to be too difficult

### ISSUE THREAD

**Issue by BezawitNW** [Atlantiss/NetherwingBugtracker#2153]
Rajis Fyashe, an elite Naga in Zangarmarsh, seems to use her abilities (especially Freezing Circle) too often. The damage also happens instantly and hits for ~80% of your health. I believe the damage should not be as high and not happen until the circle finishes placing around you.

If you look at old Wowhead comments, many people say they are easily soloing her:

https://www.wowhead.com/npc=18044/rajis-fyashe#comments

As a Demo Warlock, I have next to no trouble soloing elites / group quests but she absolutely destroys me whenever I attempt her.

**Comment by Easyfraggy** [comment]
https://github.com/Atlantiss/NetherwingBugtracker/issues/2151
