### ISSUE TITLE
[Misc][Minor] Zeppelin announcement to early

### ISSUE THREAD

**Issue by Argonn** [Atlantiss/NetherwingBugtracker#2155]
**Description**: 
When I took the zeppelin from Undercity to Orgrimmar I noticed the announcement being 20seconds before the zeppelin docked the tower.

**Current behaviour**:
The announcement that the zeppelin has arrived comes 19-20seconds to early. And was also missing a departure announcement .. but I can't find proof of that being in 2.4.3 already. (same goes for non capital zeppelins like Gromgol which don't have any at this point)

![image](https://user-images.githubusercontent.com/2676201/47920145-a2666f80-deb1-11e8-8699-e6cb4282b690.png)

**Expected behaviour**: 
The announcement should happen when the zeppelin hits the tower (as seen in the video)
https://youtu.be/JHyz73SWtBk?t=139

**Server Revision**: 
2244

**Comment by Wolffenstein** [comment]
The zeppelins to Grom'Gol have event data specified a waypoint too early in TBC. They updated it in Wotlk but it should be an intended bug for now.
