### ISSUE TITLE
[Hunter][Pet] Pet is being dismissed when (ground) mounted

### ISSUE THREAD

**Issue by Argonn** [Atlantiss/NetherwingBugtracker#2157]
**Description**: 
When you mount a ground mount, your pet will get dismissed.

**Current behaviour**:
When you mount a ground mount, your pet will get dismissed. On lvl 58 i cannot check the fly mount yet.

**Expected behaviour**: 
On ground mounts, your pet should run by your side, on fly mounts your pet should get dismissed.

**Server Revision**: 
2244

**Comment by Wolffenstein** [comment]
All pets (apart from Water Elemental) get dismissed when mounting up in TBC outside of arenas.
