### ISSUE TITLE
[Terrain][Blink]

### ISSUE THREAD

**Issue by killablink** [Atlantiss/NetherwingBugtracker#2158]
**Description**: Can blink through the terrain here. Also mobs are able to pass through the terrain when they shouldn't.

**Current behaviour**: Blinkable through

**Expected behaviour**: working terrain

**Server Revision**: 2244

![wowscrnshot_110218_102328](https://user-images.githubusercontent.com/43510874/47920889-a1b9e300-de89-11e8-8e90-5364899e137c.jpg)
![wowscrnshot_110218_102320](https://user-images.githubusercontent.com/43510874/47920887-9f578900-de89-11e8-9186-463de58a5b7c.jpg)

**Comment by Easyfraggy** [comment]
Likely MMAP problem.

**Comment by aresbrutus** [comment]
Closing and requesting retest after the update of rev 2430 and 2431.
