### ISSUE TITLE
[Quest]: Arelion's Secret

### ISSUE THREAD

**Issue by killablink** [Atlantiss/NetherwingBugtracker#2161]
**Description**: Able to use the scroll on yourself
![wowscrnshot_110218_111025](https://user-images.githubusercontent.com/43510874/47923507-fceed400-de8f-11e8-9174-30b283e6fb29.jpg)

**Current behaviour**: Able to use the scroll on yourself

**Expected behaviour**:  Should only be able to use it on the quest NPC

**Server Revision**: 224

**Comment by Evolvee** [comment]
rev -.-

**Comment by Evolvee** [comment]
rev -.-
