### ISSUE TITLE
[NPC] Bleeding Hallow Necrolyte's Fireball does too much damage

### ISSUE THREAD

**Issue by Fabrikantje** [Atlantiss/NetherwingBugtracker#2162]
**Description**:  Bleeding Hallow Necrolite's Fireball does too much damage. It breaks my Ice Barrier with two hits and my Fire Ward in one hit.

**Current behaviour**: Bleeding Hallow Necrolite's Fireball does too much damage. (600-800 dmg)
http://prntscr.com/ldm0bw
**Expected behaviour**:  Fireball does less damage (364~465 dmg)
http://prntscr.com/ldm0pa

**Server Revision**:  2244

**Comment by Easyfraggy** [comment]
2.3.3 comment probably need some earlier evidence from 2.0.x

**Comment by Fabrikantje** [comment]
Hi, not sure if this helps, but on this page the damage is written on the right side.
[http://db.hellfire-tbc.com/?npc=19422](http://db.hellfire-tbc.com/?npc=19422)

I can't really seem to find any evidence from patch 2.2.0 (when the mob was added).

**Comment by Easyfraggy** [comment]
Private server database - not a source.

**Comment by Tenoutoften** [comment]
Seems good now in rev 2304, I did receive a fireball of 507, lowest being 412, perhaps 10% overtuned atm
![cd3045f80808c7d4be4a54038b7e2a74](https://user-images.githubusercontent.com/34839199/48514944-cb96e080-e85f-11e8-9356-0cde7bdeb61f.png)
![ce0f271a5c1a90950e4de171bbb30cc4](https://user-images.githubusercontent.com/34839199/48514945-cc2f7700-e85f-11e8-87a6-8d307a0093a3.png)

**Comment by Evolvee** [comment]
Issue seems to be invalid as of now.

Feel free to reopen if the issue persist.
