### ISSUE TITLE
[NPC] Some mobs that spawn inside terrain, getting stuck forever

### ISSUE THREAD

**Issue by mhdemn** [Atlantiss/NetherwingBugtracker#2163]
*Sorry if there's a megathread for cases like this, couldn't find it. Btw, there should be a megathread or something to report every mob that spawns stuck in some object, escaping broad-spectrum fixes for this matter

https://tbc-twinhead.twinstar.cz/?npc=20387
![image](https://user-images.githubusercontent.com/25901582/47925272-14dd4c80-debe-11e8-8fc3-e992bb35e952.png)

**Description**: This Young Sporebat in 67.0,69.8 spawns inside this mushroom. There's no collision so I can shoot it but he's unable to exit the terrain he's stuck in so he gets reset.

**Current behaviour**: Spawns stuck in terrain.

**Expected behaviour**: Spawns outside of objects.

**Server Revision**: 2244

**Comment by mhdemn** [comment]
2244:
[Umbraglow Stinger](https://gyazo.com/ee43deee6b2cb2b4accb212118dbee76) at 69.4,67.1

**Comment by Easyfraggy** [comment]
Please use .npc info and supply entry+id in the future.

Fixed in rev biosphere
