### ISSUE TITLE
[NPC][Ability]Blinking a stun+ knockdown effect (Thornfang Ravager, venomspitter, etc)

### ISSUE THREAD

**Issue by killablink** [Atlantiss/NetherwingBugtracker#2165]
**Description**: If you blink their stun, you get stuck in the "knockdown" for way too long

**Current behaviour**: If you blink their stun, you get stuck in the "knockdown" for way too long
https://gfycat.com/PlayfulFailingAmazontreeboa

**Expected behaviour**:  You should be able to move after blinking the stun. Right now blinking the stun has a negative effect, specially since you blink forward, the enemy is behind you and you cant turn for 3 seconds. You should be able to blink and still be moving while having the knockdown effect (its weird looking but its still how it works even in retail)
https://gfycat.com/CourageousAlertAndeancondor

**Server Revision**: 2244

**Comment by killablink** [comment]
To add to this, another thing that shows that knockdowns aren't working properly, if you iceblock while you're knocked down and you wait 3 seconds, even when you go out of it you still can't move because you're still knocked down which doesn't make sense.

**Comment by Wolffenstein** [comment]
Seems blizzlike in TBC/client bug.
