### ISSUE TITLE
Scyers

### ISSUE THREAD

**Issue by Piledriversn** [Atlantiss/NetherwingBugtracker#2166]
![image](https://user-images.githubusercontent.com/43560552/47926839-84047200-deb9-11e8-8a7b-3a2f765d9a7b.png)
![image](https://user-images.githubusercontent.com/43560552/47926892-bdd57880-deb9-11e8-8085-8ea2a0949891.png)

[//]: # (Write your tickets according to the format:)
[//]: # ([Quest][Voren'thal the Seer)
[//]: # ([NPC] Voren'thal the Seer)

**Description**: I chose the Scyers as my Shattrath faction. Even after doing Kagdhar's quest I'm permanently set at war.

**Current behaviour**:I'm permanently at war with the Scyers. I got the reputation from Kagdhar's quest but its at war and can not be changed.

**Expected behaviour**: After doing Kagdhar's quest I get reputation from the faction I chose. Then I should be able to do the Starter quests for that faction.

**Server Revision**:

**Comment by BezawitNW** [comment]
Isnt this due to being Draenei? I believe Draenei start with bonus Aldor rep and "negative" Scryer rep.

On the flip side, Blood Elf start start with bonus Scryer rep and "negative" Aldor rep.

**Comment by Piledriversn** [comment]
Once you do Khagdar's quest to choose which one to do you get minus rep with one and positive with the other. a large amount if i remember right. Like 3k rep. So its enough to do whatever you need to start doing quests with the. Alliance or Horde can do either one.

**Comment by Wolffenstein** [comment]
Fixed in rev 2283.
