### ISSUE TITLE
[Loot][NPC]Tamed Sporebat#18201 shouldn't drop money

### ISSUE THREAD

**Issue by Tenoutoften** [Atlantiss/NetherwingBugtracker#2167]
**Description**: 
[[NPC]Tamed Sporebat#18201](https://www.wowhead.com/npc=18201/tamed-sporebat), summoned by [[Spell]Summon Sporebat#32060](https://www.wowhead.com/spell=32060/summon-sporebat), from [[NPC]Feralfen Hunter#18113](https://www.wowhead.com/npc=18113/feralfen-hunter#abilities), should probably not drop silver/currency. It's a beast pet after all.
https://youtu.be/GLzX02hnIeg?t=99

**Current behaviour**:
Currently drops a few silvers

**Expected behaviour**: 
Not to drop currency

**Server Revision**: 
2244

**Comment by Evolvee** [comment]
rev -.-
