### ISSUE TITLE
[Misc][NPC]Tamed Sporebat#18201 should reward ~1/5 xp of regular mob, currently rewards full xp.

### ISSUE THREAD

**Issue by Tenoutoften** [Atlantiss/NetherwingBugtracker#2168]
**Description**: 
[[NPC]Tamed Sporebat#18201](https://www.wowhead.com/npc=18201/tamed-sporebat), summoned by [[Spell]Summon Sporebat#32060](https://www.wowhead.com/spell=32060/summon-sporebat), from [[NPC]Feralfen Hunter#18113](https://www.wowhead.com/npc=18113/feralfen-hunter#abilities), should only reward 1/5 xp of a regular mob. Amount might be something else though but it is unlikely equal to a mob seeing that it should only have about 900 health and it doesn't give full xp on retail videos.
https://youtu.be/GLzX02hnIeg?t=98

**Current behaviour**:
Gives xp as if it was a regular mob.

**Expected behaviour**: 
Expected to give about a 1/5th xp of a regular mob

**Server Revision**: 
2244

**Comment by Evolvee** [comment]
should be 20% after rev -.-
