### ISSUE TITLE
[Druid] "Stuck" in place after logging in flight form

### ISSUE THREAD

**Issue by Tinnoan** [Atlantiss/NetherwingBugtracker#2169]
**Description**: So I logged out normally while in flight form, and after logging in a while later I got "stuck" when logging in again. What it seems like is that for some reason position isn't updated to the server after this.

I tested it out with Kutsal and did the same thing that I did before and got stuck in the exact same way.

Replication step: Fly while in flight form, log out, wait 5+min (that was how Kutsal and I tested it at least), log back in.

[Video](https://streamable.com/gqnxf)

The video shows me moving around, seeing that npc's do not load beyond the ones that loads when I log in, and me trying to use a spell with cast time which I'm unable to since I'm "in the air".

**Expected behaviour**: Should be able to log in and move about normally.

**Server Revision**: 2244

**Comment by Wolffenstein** [comment]
Fixed in rev 2247.
