### ISSUE TITLE
[Core] Orgrimmar Graveyard respawn location incorrect

### ISSUE THREAD

**Issue by Jacksn5** [Atlantiss/NetherwingBugtracker#217]
**Description**: 
Resurrecting at the Spirit Healer teleports back to the incorrect position again.

**Current behaviour**:
Coords 46.3, 12.8
![wowscrnshot_092318_163716](https://user-images.githubusercontent.com/43507549/45930058-a8843a80-bf5a-11e8-8bef-3d4a8b281bb7.jpg)

**Expected behaviour**: 
Coords 47.3, 17.8
![wowscrnshot_092318_163742](https://user-images.githubusercontent.com/43507549/45930056-a3bf8680-bf5a-11e8-856a-7762b7afc7af.jpg)

**Server Revision**: 
[2028]

**Comment by toto6** [comment]
Fixed in Server Revision 2031
