### ISSUE TITLE
[NPC]Kataru#18080 is not suppose to agro unless attacked if he stares into Terokkar

### ISSUE THREAD

**Issue by Tenoutoften** [Atlantiss/NetherwingBugtracker#2170]
**Description**: 
[[NPC]Kataru#18080]([https://www.wowhead.com/npc=18080/kataru#comments) is not suppose to agro onto players when steering into Terokkar:
![2d0cf158b76840985580530728cd5a1f](https://user-images.githubusercontent.com/34839199/47928496-d6985b00-dec6-11e8-99ee-e5ab93cac156.png)

It might not be limited to him staring, but I couldn't find a proper video, all of those I checked just nuked him.

**Current behaviour**:
Agros like a regular mob

**Expected behaviour**: 
Expected to not agro

**Server Revision**: 
2244

**Comment by Evolvee** [comment]
rev -.-
