### ISSUE TITLE
[Pet Pathing] Underwater in Dustwallow Marsh

### ISSUE THREAD

**Issue by BezawitNW** [Atlantiss/NetherwingBugtracker#2172]
While doing the underwater quests in Dustwallow Marsh, my Voidwalker would not move with me. Instead it would constantly stop + teleport to me over and over. I am not sure if other zones are impacted but Outlands underwater quests seem to have no issue with pet pathing.

**Comment by Wolffenstein** [comment]
Can you post the exact place? A video would be nice

**Comment by BezawitNW** [comment]
Sorry, I opened a duplicate bug for this. Video is on the other one. Anyways here it is:

https://clips.twitch.tv/ElatedShinySlothShadyLulu

**Comment by The14me** [comment]
Cant reproduce anymore(Maybe solved with pet/water fix).
