### ISSUE TITLE
[Zangarmash Mobs] Stop moving after 1 cast

### ISSUE THREAD

**Issue by killablink** [Atlantiss/NetherwingBugtracker#2175]
**Description**:  Mobs like Mire Hydra, Umbraglow Stinger, (probably others,) stop moving after they cast their spell. They restart running at you if you move. If I stand still after their cast, they wont move.

**Current behaviour**: Mobs like Mire Hydra, Umbraglow Stinger, (probably others,) stop moving after they cast their spell. They restart running at you if you move. If I stand still after their cast, they wont move.

**Expected behaviour**:  should move

**Server Revision**: 2244

**Comment by ttghnw** [comment]
@ScottieDOESknow yes I believe it is the same issue.

**Comment by Wolffenstein** [comment]
Fixed in rev 2421.
