### ISSUE TITLE
[Terokkar Forest] [Quest] Escaping the Tomb - server crash

### ISSUE THREAD

**Issue by Kentamentiu** [Atlantiss/NetherwingBugtracker#2176]
**Description**:  When starting the escort quest Escaping the Tomb, the server crashes

**Current behaviour**: As soon as the quest is accepted, the server crash message with the countdown to restart is started.

**Expected behaviour**:  The server shouldn't crash and the escort quest should just happen

**Server Revision**:  2244

**Comment by wowthings** [comment]
There's already one reported  #2146
