### ISSUE TITLE
[Spell] [Hunter] Multi-Shot bugs out sometimes after logging in

### ISSUE THREAD

**Issue by mhdemn** [Atlantiss/NetherwingBugtracker#2179]
*I'm sorry but I couldn't load my screen recording program quick enough to catch this, but this is the 2nd or 3rd time it has happened. I'll update with some footage if I manage to record it.

**Description**: Multi-Shot bugs out sometimes and gives an Invalid Target error message when trying to cast it on hostile targets. It seems it happens after logging in AFTER a server crash/disconnect. Don't know if this would translate into any real issue in a 100% stable server, but perhaps it's worth noting. 

It gets fixed after a short while, don't know if it's time based or how many mobs you kill-based, but after a minute / 1 or 2 mobs it gets fixed and you can use MS again. Maybe using another spell fixes it, I'm not sure.

**Current behaviour**: Multi-Shot gives an Invalid Target error message on attackable targets (and therefore doesn't get fired) sometimes after logging in after a server crash/dc.

**Expected behaviour**: Multi-Shot is usable always as long as your target is attackable and you are in range and have enough mana. Invalid Target error message ONLY when trying to use it on a non-attackable target.

**Server Revision**: 2244

**Comment by Easyfraggy** [comment]
Did you maybe try to check if you were having the common "ALT" bug, where alt button gets stuck on alt tabbing?

You unstuck your keys by simply pressing alt and releasing it.

**Comment by mhdemn** [comment]
It is a common thing, and it happens to me with some keys, but since I do not have alt+C binded to anything at all and pressing C or alt+C does the same thing in my client I know there's something else to this. Again, I'll try to get some footage of it, have my recorder at hand at all times in case it happens again.

**Comment by Easyfraggy** [comment]
It doesn't matter what binds you have, "ALT" bug prevents you from using any attack untill you actively press alt again.

**Comment by mhdemn** [comment]
Yeah, but I mean, shouldn't it then disable every spell in my bars, and not only multi-shot?
It's not a gamebreaking thing, I just picture it might translate to some annoyance when reconnecting after a dc (from the player end) during a BG or a raid, or something like that, but it seems to be really rare and even tho it happened twice to me I didn't quite catch the trigger. Just think it might be a good idea to have it added to the bugtracker in case it happens to more hunters and they search for the bug. Will update when possible.

**Comment by Easyfraggy** [comment]
Well so far I have not heard anyone else with this issue? Can someone please confirm otherwise I think it's client/addon issue. I certainly can't recreate it.

**Comment by mhdemn** [comment]
Gonna close this one, haven't happened again since 1 or 2 revisions after last time it happened.
I'm starting to think it might be the alt key thing, and me coincidentally never trying to press any other button besides multishot before using some ability with a binded alt modifier.
