### ISSUE TITLE
[Spell][NPC] Boar Charge spell=3385 by Elder Mottled Boar npc=3100 does no increased damage

### ISSUE THREAD

**Issue by Jacksn5** [Atlantiss/NetherwingBugtracker#218]
**Description**: 
[Boar Charge](https://db.excalibur.ws/?spell=3385) should deal additional damage which it doesn't, tooltip says 18 for level 8 [Elder Mottled Boar](https://db.excalibur.ws/?npc=3100) (northern Durotar), 21 for level 9.

**Server Revision**: 
2028

**Comment by Tereneckla** [comment]
![image](https://user-images.githubusercontent.com/50233983/71886094-eef3ad80-313b-11ea-92b9-d7f6758afef1.png)

**Comment by Godmatik** [comment]
Closing as https://github.com/Atlantiss/NetherwingBugtracker/issues/8202 has a full list
