### ISSUE TITLE
[Quest] Finding the Survivors

### ISSUE THREAD

**Issue by netherwingbta** [Atlantiss/NetherwingBugtracker#2180]
[//]: # (Enclose links to things related to the bug using http://wowhead.com or any other TBC database.)
[//]: # (You can use screenshot ingame to visual the issue.)
[//]: # (Write your tickets according to the format:)
[//]: # ([Quest][Azuremyst Isle] Red Snapper - Very Tasty!)
[//]: # ([NPC] Magistrix Erona)
[//]: # ([Spell][Mage] Fireball)
[//]: # ([Npc][Drop] Ghostclaw Lynx)
[//]: # ([Web] Armory doesnt work)

**Description**: 
https://www.wowhead.com/quest=9948/finding-the-survivors
No credit given when you open the cages.
**Current behaviour**:
Same issues as https://github.com/Atlantiss/NetherwingBugtracker/issues/2124
Nothing happens when you open the cages,
**Expected behaviour**: 
They should do an emote and  you should get credit.
https://www.youtube.com/watch?v=Z34OKGKUFiU
**Server Revision**: 
2244

**Comment by Easyfraggy** [comment]
https://github.com/Atlantiss/NetherwingBugtracker/issues/2124

**Comment by Evolvee** [comment]
rev XXX

**Comment by Evolvee** [comment]
https://github.com/Atlantiss/NetherwingBugtracker/issues/2329

**Comment by Evolvee** [comment]
rev YYY
