### ISSUE TITLE
[Dungeon] Slave Pens [NPC] Wastewalker slaves and Coilfang Tempest

### ISSUE THREAD

**Issue by Mewmewww** [Atlantiss/NetherwingBugtracker#2182]
[//]: # (Enclose links to things related to the bug using http://wowhead.com or any other TBC database.)
[//]: # (You can use screenshot ingame to visual the issue.)
[//]: # (Write your tickets according to the format:)
[//]: # ([Quest][Azuremyst Isle] Red Snapper - Very Tasty!)
[//]: # ([NPC] Magistrix Erona)
[//]: # ([Spell][Mage] Fireball)
[//]: # ([Npc][Drop] Ghostclaw Lynx)
[//]: # ([Web] Armory doesnt work)

**Description**: 
Incorrect level values (some are even level 71 on normal difficulity) - I think you need to recheck the entire dungeon because there might be some i've missed.
**Current behaviour**:
Incorrect level values (some are even level 71 on normal difficulity) 
**Expected behaviour**: 
Their levels should be much lower.
**Server Revision**: 
2244

**Comment by Evolvee** [comment]
rev dung
