### ISSUE TITLE
[Spell] Reincarnation

### ISSUE THREAD

**Issue by Retinus** [Atlantiss/NetherwingBugtracker#2183]
**Server Revision**: 2244

Yesterday when i logged in (haven't been online for about a week) reincarnation was at 60 min cd (shaman 48 lvl). Stayed online more than an hour and logged out in orgrimar, after using the boost to lvl 58. 

I logged today and reincarnation was again at 60 min cd. Stayed online about an hour and logged out at hellfire inn.

Logged again after 5 hours and reincarnation was again at 60 min cd.

Wasn't in combat with any mob. Maybe related with [#2045](https://github.com/Atlantiss/NetherwingBugtracker/issues/2045)

**Comment by Easyfraggy** [comment]
reincarnation doesn't automaticly revive you, so unless you were dead when logging in and then used reincarnate those issues are not related.

**Comment by Retinus** [comment]
In any case, reincarnation shouldn't be on cool down when you log in after some hours and haven't used it at all. Was working correct and something broke it.

Cant any other shaman check it when he logs in and comment? Either my char is bugged or something isn't working correct.

**Comment by Notmittz** [comment]
Reincarnation isn't working for me either, mine was showing it up but the moment I died it immediately went on a a instant 59 minute CD, as described here, with no option to use ability, just says "release spirit".

I also used the 58 boost and made sure to have an Ank in inventory as well.

**Comment by Brasso** [comment]
I couldn't use it for 4 hours doing heroics. Accept combat ress? cd. Accept soulstone revive? cd. Die? cd. Just log in. cd.

**Comment by Daggotur** [comment]
Same issue, logged in today and died about 20 minutes after login - reincarnation was on CD
![wowscrnshot_112118_222901](https://user-images.githubusercontent.com/44930160/48927718-163add00-ee9e-11e8-8ff0-3606c950918b.jpg)

**Comment by lynxzor** [comment]
I also confirm, even after a server crash and logging in it's on cooldown again.

**Comment by Wolffenstein** [comment]
Fixed in rev 2411.
