### ISSUE TITLE
[Quest] Thick Hydra Scales drop rate

### ISSUE THREAD

**Issue by killablink** [Atlantiss/NetherwingBugtracker#2184]
**Description**: Drop rate is really low, seems to be around 20%, killed maybe 15 Mire Hydras and only got 4

**Current behaviour**: Low drop rate

**Expected behaviour**: Drop rate should be around 100% for a lot of different mobs, look at comments here https://www.wowhead.com/quest=9774/thick-hydra-scales

**Server Revision**: 2244

**Comment by killablink** [comment]
Nvm, apparently these one had low drop rates in 2.0 or something

**Comment by killablink** [comment]
Actually, even in the comments from 2.0 they said the hydras in Dead Mire (Parched Hydra) has a higher drop rate, but even now the drop rate feels way too low.

**Comment by aresbrutus** [comment]
Fixed in rev `Eris`
