### ISSUE TITLE
[Quest] Return to the Abyssal Shelf

### ISSUE THREAD

**Issue by Retinus** [Atlantiss/NetherwingBugtracker#2185]
**Description**: Quest offered from Wing Commander Brack

**Current behaviour**: You can do this quest only once (with no rewards or rep gain)

**Expected behaviour**: This quest should be repeatable (with no rewards or rep gain). [Wowhead Comment](https://www.wowhead.com/quest=10346/return-to-the-abyssal-shelf#comments)

**Server Revision**: 2244

**Comment by Shanghi** [comment]
This should be fixed in revision 2333.
