### ISSUE TITLE
[NPC] Fen strider, 2 patrolling on top of each other

### ISSUE THREAD

**Issue by killablink** [Atlantiss/NetherwingBugtracker#2187]
**Description**: 2 on top of each other

**Current behaviour**: 2 on top of each other

**Expected behaviour**:  should be 1 (ID in the screenshot)
![wowscrnshot_110218_204755](https://user-images.githubusercontent.com/43510874/47946334-b1b0e180-dee0-11e8-8a55-d16f4382dd24.jpg)

**Server Revision**:

**Comment by Easyfraggy** [comment]
Fixed in rev biosphere
