### ISSUE TITLE
[NPC] Servant of Razelikh

### ISSUE THREAD

**Issue by sweetbakery** [Atlantiss/NetherwingBugtracker#2188]
[//]: # (Enclose links to things related to the bug using http://wowhead.com or any other TBC database.)
[//]: # (You can use screenshot ingame to visual the issue.)
[//]: # (Write your tickets according to the format:)
[//]: # ([Quest][Azuremyst Isle] Red Snapper - Very Tasty!)
[//]: # ([NPC] Magistrix Erona)
[//]: # ([Spell][Mage] Fireball)
[//]: # ([Npc][Drop] Ghostclaw Lynx)
[//]: # ([Web] Armory doesnt work)

**Description**: The mob becomes immortal. It enters in "Spirit Shock" effect and then you are not able to kill It.

https://i.imgur.com/4ezVg7r.jpg

https://i.imgur.com/qaa2fZK.jpg

**Current behaviour**: The mob becomes immortal after receiving an effect called "Spirit Shock".

**Expected behaviour**: I am not sure because I don't remember this mob. However I know It should be killable right

**Server Revision**:  Idk what to write here x.x

**Comment by Easyfraggy** [comment]
Issue is very unclear - I don't understand whats wrong nor what it should be. Doesn't seem like the OP knows either? Can someone elaborate?

**Comment by sweetbakery** [comment]
Well, so I'll try to explain again. There's the mob, Servant of Razelikh. In order to kill It, you should strike Stone of Binding while the mob stays in the Spirit Shock state (The mob reaches this state when the hp lows to lethal dmg). However, It seems impossible to do that. What happens next is strange: the mob keeps in the Spirit Shock state for a while and then, the state fades. After this, the mob becomes completely unkillable.

**Comment by sweetbakery** [comment]
So, I researched more and I commited a little mistake. The mob should be unkillable until you get a specific quest that allow you to kill It.

**So I am closing this report.**
