### ISSUE TITLE
[Spell] Unable to use Sunder Armor on an enemy that has Curse of Recklnessness

### ISSUE THREAD

**Issue by manslaughter** [Atlantiss/NetherwingBugtracker#219]
**Description**: Assuming the armor reduction from recklessness > sunder stack and preventing sunder application.

**Current behaviour**:

**Expected behaviour**: 

**Server Revision**: 2028 patch 203

**Comment by Azalen** [comment]
I want to add that the same applies for Faerie Fire (Feral). An interesting sidefact is that the druid is able to apply Faerie Fire if Sunder Armor was applied first.

**Comment by Evolvee** [comment]
@Easyfraggy add it to the list

closing the issue for now as the system will be rewritten entirely
