### ISSUE TITLE
[NPC][Ability] Marsh Dredger - Strangling roots

### ISSUE THREAD

**Issue by killablink** [Atlantiss/NetherwingBugtracker#2190]
**Description**:  Spell doesnt seem interruptable. Is it intended?

**Current behaviour**: Spell doesnt seem interruptable. Is it intended?

**Expected behaviour**: Feels like it should be an interruptable spell but idk

**Server Revision**:  2244

**Comment by Evolvee** [comment]
![image](https://user-images.githubusercontent.com/1942409/47958863-d4bcbd80-dfd4-11e8-9213-6f362eff14f3.png)
intended

**Comment by Kidcudi123** [comment]
Watch out for this 1k dmg root lol
