### ISSUE TITLE
[NPC][Ability] Bloodscale Wavecaller Water Bolt

### ISSUE THREAD

**Issue by killablink** [Atlantiss/NetherwingBugtracker#2191]
**Description**:  Currently uninterruptable.

**Current behaviour**: Currently uninterruptable.

**Expected behaviour**:  Should be interruptable.

**Server Revision**:  2244

**Comment by Evolvee** [comment]
![image](https://user-images.githubusercontent.com/1942409/47958863-d4bcbd80-dfd4-11e8-9213-6f362eff14f3.png)
intended
