### ISSUE TITLE
[NPC] Bloodscale Overseer + Wrekt Slave

### ISSUE THREAD

**Issue by killablink** [Atlantiss/NetherwingBugtracker#2192]
**Description**:  calls for a nearby slavedriver to help him is bugged. Not only the aoe range is way too big, it's able to aggro literally everything around it while it should only be able to pull 1 pack tied to him. (1-2 max wrekt slaves) ( currently able to pull 5-6 at the same time.) 

After killing the overseer, the slaves should disappear, flee
https://www.wowhead.com/npc=20088/bloodscale-overseer#comments
https://www.wowhead.com/npc=18123/wrekt-slave#comments

When you fight a pack of 2 slave drivers, their HP should be linked, share the same hp.
Also, the cooldown of their interrupt right now is way too short. He's able to interrupt my frost tree, and interrupt my fire tree before I even was able to cast frost spells. You can barely cast any spells fighting just 1.

**Current behaviour**: ^

**Expected behaviour**:  Overseer's call for help should call a nearby wrekt slave (1-2) that is close to him, not an aoe pull everything.

Wrekt Slaves should share hp if they're linked together.
Their interrupt CD should be longer.

**Server Revision**:  2244

**Comment by Evolvee** [comment]
range reduced in rev XXX slightly

proper implementation still needs to be done(currently jus call for help if any slave is nearby)

**Comment by Mou-nw** [comment]
The can can even interrupt my nightfall proc'd insta-shadow bolt too! The bolt does not go off and shadow is locked out. Crazy interrupts.

**Comment by Desst** [comment]
this needs a fix

**Comment by Evolvee** [comment]
fixed the interrupt timer in rev 2656

**Comment by KevinTyrrell** [comment]
@Evolvee Revision 2590

[Video](https://www.youtube.com/watch?v=Kq1YDHyyG-M)

Seems like the radius should be reduced by at least half. May need someone on retail to visit Outlands and see the correct radius.
