### ISSUE TITLE
[Rogue] [Talent] Master of Subtlety has no indication

### ISSUE THREAD

**Issue by NikiProToss** [Atlantiss/NetherwingBugtracker#2193]
[//]: # (Enclose links to things related to the bug using http://wowhead.com or any other TBC database.)
[//]: # (You can use screenshot ingame to visual the issue.)
[//]: # (Write your tickets according to the format:)
[//]: # ([Quest][Azuremyst Isle] Red Snapper - Very Tasty!)
[//]: # ([NPC] Magistrix Erona)
[//]: # ([Spell][Mage] Fireball)
[//]: # ([Npc][Drop] Ghostclaw Lynx)
[//]: # ([Web] Armory doesnt work)

**Description**: [Master of Subtlety ](https://imgur.com/a/GHK6IaG)talent has no active or passive indication.

**Server Revision**: 2250

**Comment by Easyfraggy** [comment]
Do you mean you don't get a buff when you leave stealth? Also please provide some proof how it should look like.

**Comment by Easyfraggy** [comment]
Alright I interpret that as this is working correctly? Closing.
