### ISSUE TITLE
[Core Mechanic][Shaman][Spell] Grounding Totem killing user if struck by a spell that causes character to move?

### ISSUE THREAD

**Issue by ezzekielfox** [Atlantiss/NetherwingBugtracker#2195]
[//]: # ([Spell][Shaman] Grounding Totem)

**Description**: Grounding Totem might be killing the Shaman when you try to ground a spell the causes knockback/character movement? Having trouble locking down the issue, but I made a recording to show my problem. Nothing is shown in the combat log to indicate what is happening though.
https://youtu.be/ZJA5FY7w-oA

**Current behaviour**: Spells that cause knockback are instantly killing the Shaman if you try to ground them.

**Expected behaviour**: Grounding Totem should be able to absorb spells and not kill the Shaman, no matter what spell is grounded.

**Server Revision**:

**Comment by Lampjavel** [comment]
Forked Lightning Tether from Boglash also instantly kills with no mention in the combat log.
https://streamable.com/46pup

Entry: 18281

**Comment by mr2tal** [comment]
Shalassi Oracle (18455) also one shots you if you get hit by their knockback

**Comment by Wolffenstein** [comment]
Was fixed a while ago.
