### ISSUE TITLE
[NPC][Combat Bug] Doomsayer Jurim

### ISSUE THREAD

**Issue by Fenvarien1** [Atlantiss/NetherwingBugtracker#2196]
**Description**: 
Terokkar Forest - NPC Doomsayer Jurim http://db.hellfire-tbc.com/?npc=18686
npc id: 18686

i ran pass doomsayer jurim with my 60% mount. he first attacked me and then stuck at one place. i can attack him but he wont follow for some reason.
**Current behaviour**:
https://imgur.com/a/fQWTfCh stuck in Combat for some reason. fears my pet attacks me if i come closer but he don't hunt me down. i can easily kill him from far back.

**Expected behaviour**: 
not stuck

**Server Revision**:

**Comment by Wolffenstein** [comment]
Fixed in rev 3425.
