### ISSUE TITLE
[NPC] Slain Sha'tar Vindicator & Slain Auchenai Warrior

### ISSUE THREAD

**Issue by sifiuocz** [Atlantiss/NetherwingBugtracker#2197]
**Description**: 
These NPCs seem to be stacked on top of each other in couples.
https://i.imgur.com/IOrS1Jc.jpg
https://i.imgur.com/pkDwKdj.jpg

**Current behaviour**:

**Expected behaviour**: 

**Server Revision**: 
2244

**Comment by Evolvee** [comment]
my bad, when i pasted it from sniffs, i didnt account for the fact these NPCs are pooled on retail, meaning a warrior could spawn in place of vindicator and vice versa

rev XXX
