### ISSUE TITLE
[NPC] T'chali the Witch Doctor's position

### ISSUE THREAD

**Issue by netherwingbta** [Atlantiss/NetherwingBugtracker#2198]
[//]: # (Enclose links to things related to the bug using http://wowhead.com or any other TBC database.)
[//]: # (You can use screenshot ingame to visual the issue.)
[//]: # (Write your tickets according to the format:)
[//]: # ([Quest][Azuremyst Isle] Red Snapper - Very Tasty!)
[//]: # ([NPC] Magistrix Erona)
[//]: # ([Spell][Mage] Fireball)
[//]: # ([Npc][Drop] Ghostclaw Lynx)
[//]: # ([Web] Armory doesnt work)

**Description**: 
He is too far up, only his head should be visible, so that it aligns with the skull on the mound.
**Current behaviour**:
![wow 2018-11-03 10-32-56-92](https://user-images.githubusercontent.com/43872263/47950567-5d474980-df54-11e8-9cc1-1dfd6586b986.jpg)

**Expected behaviour**: 
https://www.wowhead.com/npc=21349/tchali-the-witch-doctor#screenshots
![84920-tchali-the-witch-doctor](https://user-images.githubusercontent.com/43872263/47950576-718b4680-df54-11e8-86df-40edc7482fe2.jpg)

**Server Revision**: 
2244

**Comment by aresbrutus** [comment]
I was not able to fix the Z coords as it re positioned above ground so please have a look @Evolvee

**Comment by Evolvee** [comment]
rev cc
