### ISSUE TITLE
The setting to hide cloak and helm does reset after a while 

### ISSUE THREAD

**Issue by Nicemann1089** [Atlantiss/NetherwingBugtracker#2199]
[//]: # (Enclose links to things related to the bug using http://wowhead.com or any other TBC database.)
[//]: # (You can use screenshot ingame to visual the issue.)
[//]: # (Write your tickets according to the format:)
[//]: # ([Quest][Azuremyst Isle] Red Snapper - Very Tasty!)
[//]: # ([NPC] Magistrix Erona)
[//]: # ([Spell][Mage] Fireball)
[//]: # ([Npc][Drop] Ghostclaw Lynx)
[//]: # ([Web] Armory doesnt work)

**Description**: If you uncheck the boxes "Show Cloak" or "Show Helm" in the user interface options, it will hide your cloak or helm in the world just for a period of time. After a while (maybe after relog/restart of own computer) the boxes will be checked again and the cloak or helm will be shown again.

**Current behaviour**: Hiding your cloak or helm is just working for a period of time. The settings will be reset after a while.

**Expected behaviour**: The settings you set should be permanent.

**Server Revision**: 2244

**Comment by Easyfraggy** [comment]
I have had my helm hidden for months without it coming back, are you sure you didn't just set this setting before getting disconnected on a crash?

UI settings only save when you relog.

**Comment by Nicemann1089** [comment]
Yea, I know that relog mechanic with a crash. But actually I thought, it was always a clean logout from my side, before it occured.


________________________________
Von: Easyfraggy <notifications@github.com>
Gesendet: Saturday, November 3, 2018 6:33:15 PM
An: Atlantiss/NetherwingBugtracker
Cc: Nicemann1089; Author
Betreff: Re: [Atlantiss/NetherwingBugtracker] The setting to hide cloak and helm does reset after a while (#2199)


I have had my helm hidden for months without it coming back, are you sure you didn't just set this setting before getting disconnected on a crash?

UI settings only save when you relog.

**Comment by Easyfraggy** [comment]
Need some way of replicating this, I can't get it to happen at all. Tried on multiple chars now.

**Comment by Evolvee** [comment]
this is client side most likely

**Comment by Evolvee** [comment]
pretty easy replication is to uncheck show head, show cloak

then escape, go into interface settings and escape out again

**Comment by Easyfraggy** [comment]
If you escape exit the frame it obv doesn't save it.....

**Comment by Evolvee** [comment]
🤦‍♂️

**Comment by Nicemann1089** [comment]
I just realised it reset after the latest crash with a countdown. Logged in, swoosh cloak and helm displayed again.

**Comment by Easyfraggy** [comment]
So it just resets on crash got it. Issue remains closed. UI only saves on relog.

**Comment by Nicemann1089** [comment]
But the problem is: shouldn't it be saved from the saved variables before the crash? I mean, the settings are set. Why would a crash change it and not only not apply it?

**Comment by Easyfraggy** [comment]
I'm pretty sure that is a client issue we can't fix without making a custom client.

**Comment by kaeonex** [comment]
This issue is likely caused by the cloak/helm settings in ItemRack.
