### ISSUE TITLE
[Spell][Shattrath] Traps work on enemy faction+npc without pvp flag

### ISSUE THREAD

**Issue by Fenvarien1** [Atlantiss/NetherwingBugtracker#2200]
https://github.com/Atlantiss/NetherwingBugtracker/issues/1375 it's another problem - kinda same mechanic problem but this is additional

**Description**: 
https://imgur.com/a/cANQ704
as alliance hunter i am able to use freeze trap or immolation trap on horde enemys + npc without their pvp flag on. look screens. even with pvp flag on they should be immune in shattrath.

**Current behaviour**:
shattrath or save zones(not tested) are not grant you immunity to other factions traps. 

**Expected behaviour**: 
they should be trigger the trap and be immune or don't trigger the trap at all.

**Server Revision**:

**Comment by Evolvee** [comment]
caused by server being in temporary PVE state

should not happen once its switched back to PVP
