### ISSUE TITLE
Blood Furnace Summoner's

### ISSUE THREAD

**Issue by Arnamik12** [Atlantiss/NetherwingBugtracker#2201]
**Description**: 
The [Shadowmoon Summoner](https://www.wowhead.com/npc=17395/shadowmoon-summoner) NPCs in blood furance keep summoning the demons, that give exp, rep and item drops -- so its very easy to farm exp/rep/gold by keeping summoners alive, and using LoS to keep their mana up so they summon instead of fireball.

The felhounds they summon also drop a large number of trash items like fangs and such.

**Server Revision**: 
2244

**Comment by Evolvee** [comment]
should no longer give xp
