### ISSUE TITLE
[Misc] world object potential gold abuse

### ISSUE THREAD

**Issue by efagrgagg** [Atlantiss/NetherwingBugtracker#2202]
[//]: # (Enclose links to things related to the bug using http://wowhead.com or any other TBC database.)
[//]: # (You can use screenshot ingame to visual the issue.)
[//]: # (Write your tickets according to the format:)
[//]: # ([Quest][Azuremyst Isle] Red Snapper - Very Tasty!)
[//]: # ([NPC] Magistrix Erona)
[//]: # ([Spell][Mage] Fireball)
[//]: # ([Npc][Drop] Ghostclaw Lynx)
[//]: # ([Web] Armory doesnt work)

https://imgur.com/a/tRKMNMP

http://vanillawowaddons.com/database/?object=3661

**Description**: the 2 spawn points are very close to each other. crate contains random 3 grey items that can be sold from 20s to over 1g total. when you loot one spawn point the other one immediately spawns. can be abused to farm gold.

**Current behaviour**: looting weapon crate at one tent makes the other near one to instant spawn, then back and forth.

**Expected behaviour**: couldnt find any info on this, probably needs custom fix to prevent abuse.

**Server Revision**: Revision 2244

**Comment by aresbrutus** [comment]
Known issue: https://github.com/Atlantiss/NetherwingBugtracker/issues/222
