### ISSUE TITLE
[Quest][Zangarmarsh] Stinger Venom quest item low drop rate

### ISSUE THREAD

**Issue by Mikik3jr** [Atlantiss/NetherwingBugtracker#2204]
[//]: # (Enclose links to things related to the bug using http://wowhead.com or any other TBC database.)
[//]: # (You can use screenshot ingame to visual the issue.)
[//]: # (Write your tickets according to the format:)
[//]: # ([Quest][Azuremyst Isle] Red Snapper - Very Tasty!)
[//]: # ([NPC] Magistrix Erona)
[//]: # ([Spell][Mage] Fireball)
[//]: # ([Npc][Drop] Ghostclaw Lynx)
[//]: # ([Web] Armory doesnt work)

**Description**: 
[In this quest](https://www.wowhead.com/quest=9830/stinger-venom) you have to kill [Marshlight Bleeders](https://www.wowhead.com/item=24485/marshlight-bleeder-venom#dropped-by) or [Fenglow Stingers](https://www.wowhead.com/npc=20198/fenglow-stinger) for their [venom](https://www.wowhead.com/item=24485/marshlight-bleeder-venom#dropped-by).
**Current behaviour**:
Fenglow Stinger's quest droprate looks fine.
Marshlight Bleeder's droprate seems bad. According to wowhead they should have 22%~ droprate. I've killed 30+ so far and got 0 items. I asked a guildmate how much he has killed so far and he claimed like 10% loot chance. I know we can be unlucky, but I report this anyway just in case.
**Expected behaviour**: 
Marshlight Bleeder's quest item should be higher.
**Server Revision**: 
2244

**Comment by Mikik3jr** [comment]
Acording to wowhead that green thing has 78% drop chance:
![image](https://user-images.githubusercontent.com/43505031/47953277-c5f5ec80-df7b-11e8-9369-384e928fcc73.png)
And I have collected 35 so far. The 2 venom was from Fenglow Stinger.
![image](https://user-images.githubusercontent.com/43505031/47953264-abbc0e80-df7b-11e8-9c1d-09e155c523bc.png)

**Comment by aresbrutus** [comment]
Both of the drop rates seem to be blizzlike.
