### ISSUE TITLE
I Work... For the Horde Quest Bug

### ISSUE THREAD

**Issue by uhhisthistaken** [Atlantiss/NetherwingBugtracker#2205]
I Work... For the Horde!  Quest

Salvaged Metal and Salvaged Wood do not show the correct # of metal or wood that you have in your bag.  Remains 0/8 regardless of how many you pick up and/or are in your bags.

**Comment by Easyfraggy** [comment]
Sounds like UI issue.

**Comment by aresbrutus** [comment]
Also think it is a UI bug as it is working fine for me and many others who have done it during phase 2.
