### ISSUE TITLE
[Core] Totems and PvP rules

### ISSUE THREAD

**Issue by Galawer** [Atlantiss/NetherwingBugtracker#2206]
**Current behaviour**:
Totems deal damage to players of opposing faction even with pvp disabled.
![image](https://user-images.githubusercontent.com/1574432/47953563-b678a280-df7f-11e8-9466-6eeba5fc7a57.png)
Not just a Searing Totem targeting issue, Magma Totem ticks do damage too.
![image](https://user-images.githubusercontent.com/1574432/47953572-df009c80-df7f-11e8-83f7-00ed49e5e913.png)
Also, if they hit a pet it causes the pet to attack you, while still being unattackable by you.
![image](https://user-images.githubusercontent.com/1574432/47953619-6817d380-df80-11e8-90e9-7955bf1a5887.png)

Probably related to https://github.com/Atlantiss/NetherwingBugtracker/issues/2200

**Expected behaviour**: 
Totems should obey pvp settings.

**Server Revision**: 
2244

**Comment by Mikik3jr** [comment]
I don't know how valid this is, since server will be PVP. They put PVE in to prevent griefing.

**Comment by Galawer** [comment]
> I don't know how valid this is, since server will be PVP. They put PVE in to prevent griefing.

You can still disable PvP on a PvP server, in cities or in friendly zones. You could grief players by placing totems in starting zones or near afk players in cities.
I don't know if totems ignore sanctuary rules too, but if so, then you could also kill people in Shattrath.

**Comment by Mikik3jr** [comment]
Yeah, you have a point there.

**Comment by Evolvee** [comment]
caused by server being in temporary PVE state

should not happen once its switched back to PVP
