### ISSUE TITLE
[Dungeon] Underbog

### ISSUE THREAD

**Issue by Mewmewww** [Atlantiss/NetherwingBugtracker#2207]
[//]: # (Enclose links to things related to the bug using http://wowhead.com or any other TBC database.)
[//]: # (You can use screenshot ingame to visual the issue.)
[//]: # (Write your tickets according to the format:)
[//]: # ([Quest][Azuremyst Isle] Red Snapper - Very Tasty!)
[//]: # ([NPC] Magistrix Erona)
[//]: # ([Spell][Mage] Fireball)
[//]: # ([Npc][Drop] Ghostclaw Lynx)
[//]: # ([Web] Armory doesnt work)

**Description** + **Current behaviour**:
Swamplord Musel'ek (Traps aren't reset after wipes, if you mistakenly step on them, him and claw will aggro on you and end your unprepared group)
Black Stalker - used levitate on "Satyr" but instead of making him levitate, he tossed him across the room.
Sanguine hibiscus - drops from either mobs or looted from the ground doesn't respawn over time except the first two. 
**Expected behaviour**: 
Swamplord Musel'eks traps should reset after a wipe.
Blackstalker should make people levitate, not toss them around like a ragdoll.
Sanguine Hibiscus - Over time, they should all respawn
**Server Revision**: 
2244

**Comment by DeltaLoads** [comment]
Also bosses despawn way too fast - Black Stalker despawned in less then 3min even if players have quest for his brains

**Comment by Easyfraggy** [comment]
Need proof that the hibiscus should respawn.

Traps are a part of a global issue it seems. Same as blood furnace mines.

**Comment by aresbrutus** [comment]
Last boss also uses levitate on pets. Don't think this is correct.

**Comment by Mewmewww** [comment]
@Easyfraggy 
https://www.wowhead.com/item=24246/sanguine-hibiscus#comments
Problem is the earliest comment i found was 2.4.3 so changed might have been made. It's also odd because if it wasn't supposed to work like this, why would the very first two Sanguine Hibicus respawn after clearing the entire dungeon? I will try to look further

**Comment by Easyfraggy** [comment]
Please report issues 1 bug at a time.
