### ISSUE TITLE
Tooltip of "Serrated Blades" in rogue's talent tree "Subtlety" malfunction

### ISSUE THREAD

**Issue by Nicemann1089** [Atlantiss/NetherwingBugtracker#2208]
[//]: # (Enclose links to things related to the bug using http://wowhead.com or any other TBC database.)
[//]: # (You can use screenshot ingame to visual the issue.)
[//]: # (Write your tickets according to the format:)
[//]: # ([Quest][Azuremyst Isle] Red Snapper - Very Tasty!)
[//]: # ([NPC] Magistrix Erona)
[//]: # ([Spell][Mage] Fireball)
[//]: # ([Npc][Drop] Ghostclaw Lynx)
[//]: # ([Web] Armory doesnt work)

**Description**: The tooltip of "Serrated Blades" in rogue's talent tree "Subtlety" says "Causes your attacks to ignore **0** of your target's Armor..." for every tier.

**Current behaviour**: Shows always a value of "0".

**Expected behaviour**: Value should be higher.

**Server Revision**: 2244

**Comment by Nicemann1089** [comment]
I just checked it again: Seems to be working sometimes. Now there are shown the values "154", "309" and "464".

**Comment by Easyfraggy** [comment]
possible UI issue?

**Comment by Nicemann1089** [comment]
Could be ofc!


________________________________
Von: Easyfraggy <notifications@github.com>
Gesendet: Saturday, November 3, 2018 8:06:18 PM
An: Atlantiss/NetherwingBugtracker
Cc: Nicemann1089; Author
Betreff: Re: [Atlantiss/NetherwingBugtracker] Tooltip of "Serrated Blades" in rogue's talent tree "Subtlety" malfunction (#2208)


possible UI issue?

**Comment by Easyfraggy** [comment]
Closing for now, please reopen and comment if you get some more info, I can't replicate it.

**Comment by ahlens** [comment]
Hey so I can confirm that it's random. On one rogue I created it shows proper tooltip, on another it shows 0 armor reduction.
