### ISSUE TITLE
[NPC][Quest] Korgaah, Grimnok and Korgaah, I Am For You!

### ISSUE THREAD

**Issue by netherwingbta** [Atlantiss/NetherwingBugtracker#2209]
[//]: # (Enclose links to things related to the bug using http://wowhead.com or any other TBC database.)
[//]: # (You can use screenshot ingame to visual the issue.)
[//]: # (Write your tickets according to the format:)
[//]: # ([Quest][Azuremyst Isle] Red Snapper - Very Tasty!)
[//]: # ([NPC] Magistrix Erona)
[//]: # ([Spell][Mage] Fireball)
[//]: # ([Npc][Drop] Ghostclaw Lynx)
[//]: # ([Web] Armory doesnt work)

**Description**: 
He is not linked to his bodyguards. You're supposed to use the brew to lure him out by himself, but you can just pull him normally. He also reset when he gained the Bloodmaul Intoxication buff. I guess this is a general problem with the brew.
https://www.wowhead.com/npc=20723/korgaah#comments
https://www.wowhead.com/quest=10543/grimnok-and-korgaah-i-am-for-you
**Current behaviour**:
Luring him with the brew works,
![2018-11-03-1632-49 mp4_snapshot_00 22_ 2018 11 03_17 10 45](https://user-images.githubusercontent.com/43872263/47954568-a8308380-df8b-11e8-9d08-485745c9479b.jpg)

 but then he resets when he gets the intoxication buff
![2018-11-03-1632-49 mp4_snapshot_00 35_ 2018 11 03_17 06 12](https://user-images.githubusercontent.com/43872263/47954504-0315ab00-df8b-11e8-934c-1a10c1a2e5bd.jpg)
And again, you can pull him normally since he is not linked.
testing gfycat
https://gfycat.com/MaleFlashyAtlasmoth
**Expected behaviour**: 
Should be linked unless you used the brew to lure him.  Shouldn't reset 
**Server Revision**: 
2244

**Comment by Easyfraggy** [comment]
Some reason the guards don't assist. They should not be hardlinked but rather softlinked.

**Comment by The14me** [comment]
rev.3451. still an issue.

**Comment by Wolffenstein** [comment]
Fixed in rev 3460.
