### ISSUE TITLE
[Spell] Bloodmaul Buzz

### ISSUE THREAD

**Issue by netherwingbta** [Atlantiss/NetherwingBugtracker#2211]
[//]: # (Enclose links to things related to the bug using http://wowhead.com or any other TBC database.)
[//]: # (You can use screenshot ingame to visual the issue.)
[//]: # (Write your tickets according to the format:)
[//]: # ([Quest][Azuremyst Isle] Red Snapper - Very Tasty!)
[//]: # ([NPC] Magistrix Erona)
[//]: # ([Spell][Mage] Fireball)
[//]: # ([Npc][Drop] Ghostclaw Lynx)
[//]: # ([Web] Armory doesnt work)

**Description**: 
Mobs go back to full hp when the buff expires. Also the mobs get the buff just randomly without having anything to do with brew, seems off. Guessing it has something to do with the brewmasters.
https://www.wowhead.com/spell=34932/bloodmaul-buzz#comments:id=380727
**Current behaviour**:
Mobs with this buff
https://www.wowhead.com/spell=37786/bloodmaul-rage

https://gfycat.com/MeagerSeparateAmurratsnake
**Expected behaviour**: 
Should work similarly to last stand.
**Server Revision**: 
2244

**Comment by Tereneckla** [comment]
Fixed

**Comment by The14me** [comment]
We are back in the game with the new patch 2.4 (still bugged). Once the buff fade away=full HP.

**Comment by Wolffenstein** [comment]
Fixed in rev 3359.
