### ISSUE TITLE
[Dungeon] The Slave Pens [NPC] Coilfang Slavehandler [Spell] Missing (nm)

### ISSUE THREAD

**Issue by The14me** [Atlantiss/NetherwingBugtracker#2212]
**Current behaviour**: Missing Hamstring and Head Crack.

**Expected behaviour**: 
https://www.wowhead.com/npc=17959/coilfang-slavehandler
https://www.wowhead.com/spell=9080/hamstring
https://www.wowhead.com/spell=16172/head-crack
https://i.imgur.com/YNVBIiY.png

**Server Revision**:

**Comment by Evolvee** [comment]
https://github.com/Atlantiss/AtlantissTBCBT/issues/1059
https://github.com/Atlantiss/AtlantissTBCBT/issues/575

**Comment by Evolvee** [comment]
its wolfs shit cpp, i told him i would do it in sai and he were like naaaa dawg, its working

few months later... ppl report it on open beta as well 🤦‍♂️

**Comment by Tereneckla** [comment]
Fixed
