### ISSUE TITLE
[Core] Aggressive pets will attack non-hostile players and their pets of the opposing faction

### ISSUE THREAD

**Issue by Saben65** [Atlantiss/NetherwingBugtracker#2213]
**Description**: 
If you set your pet (only tested on a hunter) to aggressive, it will attack non-hostile players. 

**Current behaviour**:
If your pet is set to aggressive and you still can't get your pet to attack, click the aggressive icon again. I tested it by running near the enemy player, I did not test if you could command it to attack at range. This appears to combat bug both players, even when you call off your pet.

**Expected behaviour**: 
Your pet should not be able to attack other players and their pets if they are not hostile.

**Server Revision**: 
Whatever rev it is today.

**Comment by Evolvee** [comment]
caused by PVE setting of the server
server will be set to PVP again soon, so no need to waste time on fixing that
