### ISSUE TITLE
[Pet/Pathing] Strange behavior in Ango'rosh cave (Zangar)

### ISSUE THREAD

**Issue by BezawitNW** [Atlantiss/NetherwingBugtracker#2214]
https://clips.twitch.tv/FitWimpyRingSmoocherZ

Note that I put my pet on passive so I would not risk pulling the mob behind the one I'm attacking. My pet then goes to attack the mob anyway and once the mob is dead, my pet freezes in place + wont move/listen to commands.

**Comment by Easyfraggy** [comment]
As long as we don't know how to recreate this actively, it's gonna be on low prio. 

What did you do too your pet prior to this incident? Treat your Voidwalker right - let him have a few days at the spa every now and then!

**Comment by BezawitNW** [comment]
Noted xD but I do worry about the whole putting my pet on passive and then it going to attack the mob. If that were to happen to a Hunter in a raid it would be no bueno

**Comment by Easyfraggy** [comment]
For sure, but to be able to fix it, we need some way to recreate the bug. Especially odd ones like this!

**Comment by BezawitNW** [comment]
I don't believe I did anything out of the ordinary. The mob was pathing toward me but still too close to the mob behind it. My Voidwalker was channeling Consume SHadows (self-heal) and I put it on passive so it would not run up to the mob and aggro the one behind it. My Voidwalker returned to my side (as normal) and I began to attack the mob from range to burn it down. Upon attacking the mob, my Voidwalker went to assist (as if it were on defensive). I tried toggling between defensive/passive a few times to try to get it to return to my side but it would not (even after the mob was dead). Hope this helps!

**Comment by BezawitNW** [comment]
I think I know what it might be. I just discovered that if I order my Voidwalker to use Torment on a mob (not attack, just order it to use Torment) and then set it to passive, the Voidwalker continues on to the mob instead of returning to my side. I must have ordered it to use Torment and then put it on passive.

So the real issue is when Voidwalker is ordered to use Torment on a mob and then set to passive, it does not return to the Warlock's side like it should. Instead it continues on to the mob to use Torment.

**Comment by Easyfraggy** [comment]
https://github.com/Atlantiss/NetherwingBugtracker/issues/542
