### ISSUE TITLE
[Quest] Wolves Across the Border 

### ISSUE THREAD

**Issue by hirothequester** [Atlantiss/NetherwingBugtracker#2215]
[//]: # (Enclose links to things related to the bug using http://wowhead.com or any other TBC database.)
[//]: # (You can use screenshot ingame to visual the issue.)
[//]: # (Write your tickets according to the format:)
[//]: # ([Quest][Elywnn Forest] Wolves Across the Border)

**Description**: 
The quest "Wolves Across the Border" should require a pre-requisite quest called "A Threat Within" before you are able to obtain the quest.
**Current behaviour**:
The quest can be picked up without the pre-requisite quest
**Expected behaviour**: 
You need to complete the pre-requisite before being able to take the quest.
**Server Revision**: 
Properly chain quests together for a more wholesome experience.

**Comment by Shanghi** [comment]
Proof would be needed for this. The Master Guide book lists it having no prerequisite. Others (like Kobold Camp Cleanup, Brotherhood of Thieves, and Eagan Peltskinner are listed as requiring it so it's probably not a technical error in it.
