### ISSUE TITLE
[NPC][Movement] Feralfan Hunter

### ISSUE THREAD

**Issue by killablink** [Atlantiss/NetherwingBugtracker#2217]
**Description**: If you pull the hunter by 1 shotting his pet (the feralfen spore) and you are out of his autoattack range (36 yards, tested with frostbolt) the hunter will not move to autoattack, and only cast serpent sting on CD

**Current behaviour**: If you pull the hunter by 1 shotting his pet (the feralfen spore) and you are out of his autoattack range (36 yards, tested with frostbolt) the hunter will not move to autoattack, and only cast serpent sting on CD

**Expected behaviour**:  should move

**Server Revision**: 2244

**Comment by Tenoutoften** [comment]
His range should be 40 on [[Spell]Serpent Sting#31975](https://www.wowhead.com/spell=31975/serpent-sting) so you would still be in range... or should be anyway.

**Comment by killablink** [comment]
Yeah, I'm in range for his serpent sting, but not for his auto attack which is 30 yards :P

**Comment by Tenoutoften** [comment]
https://github.com/Atlantiss/NetherwingBugtracker/issues/293
