### ISSUE TITLE
[Quest] The Sharpest Blades

### ISSUE THREAD

**Issue by killablink** [Atlantiss/NetherwingBugtracker#2219]
**Description**:  Low drop rate for the Marshfang Slicer Blade, should be 100%
https://www.wowhead.com/npc=18131/marshfang-slicer#comments

**Current behaviour**: Low drop rate

**Expected behaviour**: 100% drop rate

**Server Revision**:  2244

**Comment by killablink** [comment]
Well considered the posts are 11 years old, and you can see on which patch and have upvotes, it's pretty credible I find that the drop rate were higher than it is currently.

Oh well just leaving it out there

**Comment by Easyfraggy** [comment]
First comment about 100% droprate is from 2.3 as far as I can see.

**Comment by aresbrutus** [comment]
Drop rates correspond to pre-2.3 version.
