### ISSUE TITLE
[Item] Weapon Crates in the Barrens giving higher ilvl items.

### ISSUE THREAD

**Issue by manslaughter** [Atlantiss/NetherwingBugtracker#222]
**Description**: 
Weapon Crates in the barrens (specifically the southsea pirate area) containg weapons with an ilvl higher than the area.

**Current behaviour**:
![image](https://user-images.githubusercontent.com/4078568/45930179-33950e80-bf22-11e8-8056-b96a87a13bb0.png)
(These are level 31 and 30 weapons respectively)

**Expected behaviour**: Weapons in Barrens weapons crates are not such high level.

**Server Revision**: 2028 patch 203

**Comment by Kidcudi123** [comment]
Also the one in Xroads + Ratchet gave wrong loot

**Comment by aresbrutus** [comment]
Confirmed. Dynamic respawn + loot tables have to be relooked at.

**Comment by Shanghi** [comment]
These should be fixed in revision 2438. They shouldn't respawn instantly anymore and the 3 different types of crates should have appropriate level loot for the areas they're in.
