### ISSUE TITLE
[Quest] There Can Be Only One Response - visible infernal triggers

### ISSUE THREAD

**Issue by netherwingbta** [Atlantiss/NetherwingBugtracker#2221]
[//]: # (Enclose links to things related to the bug using http://wowhead.com or any other TBC database.)
[//]: # (You can use screenshot ingame to visual the issue.)
[//]: # (Write your tickets according to the format:)
[//]: # ([Quest][Azuremyst Isle] Red Snapper - Very Tasty!)
[//]: # ([NPC] Magistrix Erona)
[//]: # ([Spell][Mage] Fireball)
[//]: # ([Npc][Drop] Ghostclaw Lynx)
[//]: # ([Web] Armory doesnt work)

**Description**: 
When killing the Razaani to summon the Nexus-Prince you can see the infernal trigger.
**Current behaviour**:
![inf](https://user-images.githubusercontent.com/43872263/47955760-1598e000-df9d-11e8-996d-ea7879a5f4a9.jpg)

https://gfycat.com/FatNauticalBorer
There was no summoning event at the portal either, the Prince just appeared instantly.
**Expected behaviour**: 
Balls of light are supposed to be visible and float up, and then eventually go into the lightning rod thing.
https://www.youtube.com/watch?v=uZ1bVKpBoc4
https://www.wowhead.com/quest=10867/there-can-be-only-one-response
**Server Revision**: 
2244

**Comment by Evolvee** [comment]
rev XXX

**Comment by maxturtlesc2** [comment]
@Evolvee The infernal trigger is not fixed, still appears when killing some Razaani Raider (not all of them though). Moreover there's no glowing orb animation when killing Razaani Nexus Stalker, so I'm not even sure if it currently counts towards the summon of the mob.

**Comment by maxturtlesc2** [comment]
Same thing for Razaani Spell-Thief actually, they don't seem to count towards the summon since there's no glowing animation.

**Comment by Evolvee** [comment]
Core issue - they are still visible as infernal, even to non-gms, until visibility refresh(gm on/off), after that they arent visible anymore. Most likely due to their cpp script.

**Comment by Tereneckla** [comment]
Fixed
