### ISSUE TITLE
[Dungeon] Mana-Tombs [NPC] Ethereal Sorcerer [Spell]   Arcane Fiends

### ISSUE THREAD

**Issue by The14me** [Atlantiss/NetherwingBugtracker#2223]
**Current behaviour**: Atm summon  Arcane Fiends ever when he's ccd.
Make the dung way harder that way.

**Expected behaviour**: Suppose to not do that.
https://www.wowhead.com/npc=18313/ethereal-sorcerer

**Server Revision**:

**Comment by Evolvee** [comment]
rev -.-
