### ISSUE TITLE
[NPC][Combat] Unkor the Ruthless

### ISSUE THREAD

**Issue by sifiuocz** [Atlantiss/NetherwingBugtracker#2224]
**Description**: 
While doing the quest "Don't Kill the Fat One" this NPC turns friendly after getting him low enough as it's supposed. The problem is that the NPC stays in combat with the player after it turns friendly.

**Current behaviour**:

**Expected behaviour**: 
The NPC shouldn't stuck the player in combat. 

**Server Revision**: 
2244

**Comment by Evolvee** [comment]
@Wolffenstein thats issue for SAI scripts that change faction/unit_flags to not be attackable as well... the combat isnt reseted

**Comment by mhdemn** [comment]
Wanna update with [this](https://youtu.be/UzgZ6I2qobk) (2255)

**Comment by Easyfraggy** [comment]
Only turns friendly if you already cleared the 10/10 mobs for your quest afaik.

**Comment by Evolvee** [comment]
3377
