### ISSUE TITLE
[Dungeon] Ramparts - Boss corpse despawn time 

### ISSUE THREAD

**Issue by Avercy** [Atlantiss/NetherwingBugtracker#2226]
**Description**:  Boss's in the ramparts despawn too quickly, sometimes before you can loot the required items

**Current behaviour**: Kill boss, loot for stuff, boss despawns before rest of mobs so you cant loot hand/head etc

**Expected behaviour**: boss corpse should persist for several minutes longer (consistant with other mobs)

**Server Revision**:

**Comment by Easyfraggy** [comment]
Global issue with boss corpses, afaik they shouldnt despawn at all in dungeons unless they are empty (including quest items).

**Comment by Wolffenstein** [comment]
fixed
