### ISSUE TITLE
[Quest] Failed Incursion - You don't meet the requirements for that quest

### ISSUE THREAD

**Issue by BezawitNW** [Atlantiss/NetherwingBugtracker#2227]
When I tried to accept "Failed Incursion" it said "You don't meet the requirements for that quest". Now the quest is not available from the npc (Ysiel Windsinger) and there is not silver question mark. I am level 65- according to the Hellfire database, you need to be 62 to accept it.

http://db.hellfire-tbc.com/?quest=9876

**Comment by zauru7** [comment]
If you've already picked up the "Lost in action" quest you can not accept this one

**Comment by BezawitNW** [comment]
Ah I did- thank you! Closing issue
