### ISSUE TITLE
[Spell][Warlock]Inferno summon is aggressive to player

### ISSUE THREAD

**Issue by Mou-nw** [Atlantiss/NetherwingBugtracker#2229]
**Description**: 
([Spell][Warlock] Inferno) does not do what the tooltip says:

> "Summons a meteor from the Twisting Nether, causing 200 Fire damage and stunning all enemies in the area for 2 sec. An Infernal rises from the crater, under the command of the caster for 5 min. Once control is lost, the infernal must be enslaved to maintain control. Can only be used outdoors."

Also, the current pet must be dismissed manually to cast the spell. 
(Casting the spell mounted dismissed my voidwalker properly).

**Current behaviour**:
1. The Infernal is aggressive to the caster and quickly killed me, immune to enslave attempts.
2. There was no aoe stun on landing.
3. I had to dismiss my current pet manually to cast the spell (mounted worked fine tho)
4. Inferno is immune to enslave
5. At level 70 the Inferno is only level 66

**Expected behaviour**: 
Should be a pet under caster's control.
Should stun the mob's it is cast onto.
Should cause current pet to despawn.
Should be enslavable.
Should match the caster's level.
**Server Revision**:

**Comment by Mou-nw** [comment]
^^

**Comment by BamboozleNW** [comment]
Tested on Kara PTR. Infernal is under casters control, does stun for 2 seconds, causes current pet to despawn, is enslavable, and is matching my current level. Can be closed I believe. https://www.youtube.com/watch?v=5NPVvcVstMk

**Comment by elasdmehico** [comment]
It's still bugged. When you summon infernal its hostile even though it should be controlled for 5 min.

Tried enslaving it, worked fine. I didn't see if it still stunned enemies, but it's hostile when it should be under master's control.

**Comment by Godmatik** [comment]
Inferno was fully fixed a while ago, closing
