### ISSUE TITLE
Druid Quest on Dreadmist Peak

### ISSUE THREAD

**Issue by Tinnoan** [Atlantiss/NetherwingBugtracker#223]
For the quest "The Principal Source" there should be waves of Burning Blade Orcs appearing when trying to fill the sample vial, they don't appear. The haze should also disappear afterwards, which also doesn't happen.

Sarilus Foulborne on the top of Dreadmist Peak is also tagged as Aggressive rather than Neutral like he should be, making it near impossible to do the quest at the intended level (as he's level 25).

**Comment by Jezofine** [comment]
I helped one druid to finish this quest. He said he filled vial while I was kiting Sarilus.

**Comment by Wolffenstein** [comment]
Fixed in rev 3404.
