### ISSUE TITLE
Race Condition with Stealth & Mob Aggro?

### ISSUE THREAD

**Issue by KevinTyrrell** [Atlantiss/NetherwingBugtracker#2230]
[//]: # (Enclose links to things related to the bug using http://wowhead.com or any other TBC database.)
[//]: # (You can use screenshot ingame to visual the issue.)
[//]: # (Write your tickets according to the format:)
[//]: # ([Quest][Azuremyst Isle] Red Snapper - Very Tasty!)
[//]: # ([NPC] Magistrix Erona)
[//]: # ([Spell][Mage] Fireball)
[//]: # ([Npc][Drop] Ghostclaw Lynx)
[//]: # ([Web] Armory doesnt work)

**Description**: 
[Twitch Clip](https://clips.twitch.tv/HappyCogentHawkNomNom)

Mob aggroed me, a few miliseconds later I press stealth, somehow combat was not applied and I stealthed, he de-aggroed.

**Current behaviour**:
Mob aggroed onto me but did not immediately apply combat, allowing me to stealth and cancel combat.

**Expected behaviour**: 
Mob should put me in combat instantly, preventing me from stealthing.

**Server Revision**: 
~2244

**Comment by zauru7** [comment]
same as #295 ?
has to do with spell batching i think

**Comment by KevinTyrrell** [comment]
> same as #295 ?

Yep, that's it.

Duplicate of #295
