### ISSUE TITLE
[NPC][Spell] Bloodscale Enchantress - Arcane Missiles

### ISSUE THREAD

**Issue by killablink** [Atlantiss/NetherwingBugtracker#2232]
**Description**:  She's casting instant cast arcane missiles while it probably be a channeled spell?

**Current behaviour**: Instant arcane missiles, no cast bar

**Expected behaviour**: Probably actually cast? one comment says 170 dmg each second for 5 seconds (2.3 but yeah) https://www.wowhead.com/npc=18088/bloodscale-enchantress#comments

**Server Revision**:  2244

**Comment by Thorgrimme** [comment]
This npc also uses a spell called Freezing Circle, http://db.hellfire-tbc.com/?spell=34787. And u take lots 2-3 k dmg as soon as its casted, believe u should have a few secs to move out of the area becomes it becomes a circle before u take the dmg. As stated in the comment here :https://www.wowhead.com/npc=18088/bloodscale-enchantress#comments

**Comment by Evolvee** [comment]
missiles fixed in rev -.-
