### ISSUE TITLE
[Mage][Spell][Water Elemental's Frost nova

### ISSUE THREAD

**Issue by killablink** [Atlantiss/NetherwingBugtracker#2233]
**Description**:  Able to cast pet's nova slightly out of range

**Current behaviour**: Can cast frost nova even if it shows a red circle that tells you it's out of range
https://gfycat.com/SomberShortGalapagoshawk

**Expected behaviour**:  Visual should be the intended range?

**Server Revision**: 2244

**Comment by knasen88** [comment]
isn't that blizzlike though? I remember blizzard or basically any aoe target thing could be shot slightly out of their targeting reticle would allow
