### ISSUE TITLE
[Quest][Terokkar Forest]Evil Draws Near

### ISSUE THREAD

**Issue by DeltaLoads** [Atlantiss/NetherwingBugtracker#2234]
[//]: # (Enclose links to things related to the bug using http://wowhead.com or any other TBC database.)
[//]: # (You can use screenshot ingame to visual the issue.)
[//]: # (Write your tickets according to the format:)
[//]: # ([Quest][Azuremyst Isle] Red Snapper - Very Tasty!)
[//]: # ([NPC] Magistrix Erona)
[//]: # ([Spell][Mage] Fireball)
[//]: # ([Npc][Drop] Ghostclaw Lynx)
[//]: # ([Web] Armory doesnt work)

**Description**: 
Auchenai Death-Speakers and Auchenai Doomslayers dont drop Doom Skulls (https://www.wowhead.com/item=31812/doom-skull#dropped-by)
**Current behaviour**:
Auchenai Death-Speakers and Auchenai Doomslayers dont drop Doom Skulls
**Expected behaviour**: 
Auchenai Death-Speakers and Auchenai Doomslayers should drop Doom Skulls 
**Server Revision**: 
2244

**Comment by Evolvee** [comment]
rev XXX
