### ISSUE TITLE
[NPC][Movement] Ango'rosh Souleater

### ISSUE THREAD

**Issue by killablink** [Atlantiss/NetherwingBugtracker#2235]
**Description**: Walks as if he's falling

**Current behaviour**: Walks as if he's falling
Entry: 18121, id: 5, GUIDLow: 21938
https://gfycat.com/SnappyHighElk
**Expected behaviour**: Walks normally

**Server Revision**:  2244

**Comment by Easyfraggy** [comment]
Walks normally for me, anyone else see him like this?

**Comment by Tenoutoften** [comment]
I figured this issue out in https://github.com/Atlantiss/NetherwingBugtracker/issues/2492
