### ISSUE TITLE
[NPC][Sunstrider Isle] Treant, Feral Treant, and Elemental mobs are immune to venom shots

### ISSUE THREAD

**Issue by ihazbackup** [Atlantiss/NetherwingBugtracker#2237]
[//]: # (Enclose links to things related to the bug using http://wowhead.com or any other TBC database.)
[//]: # (You can use screenshot ingame to visual the issue.)
[//]: # (Write your tickets according to the format:)
[//]: # ([Quest][Azuremyst Isle] Red Snapper - Very Tasty!)
[//]: # ([NPC] Magistrix Erona)
[//]: # ([Spell][Mage] Fireball)
[//]: # ([Npc][Drop] Ghostclaw Lynx)
[//]: # ([Web] Armory doesnt work)

**Description**: Elemental mobs in blood elf's starting area (Sunstrider Isle) are immune to Venom shot, which is hunter's first dot skill. No idea about other elemental attacks

**Current behaviour**: Every venom shot does not get through Treant, Feral Treants, and elemental mobs up the platform in starting area. "Immune" was shown

**Expected behaviour**: While it may have high resistance, there should be a chance for attacks to go through

**Server Revision**: Didn't see the number, but this incident was found in 03.Nov.2018 at 20:00 GMT+1

**Reproduce**:
- Create a belf hunter
- Level to 3 until u get venom shot.
- Use it on Treant/Feral Treant or the elemental mobs on the platform

**Comment by zauru7** [comment]
Elementals are supposed to be immune to it since it's considered a poison afaik

**Comment by Wolffenstein** [comment]
Elementals are immune to poison.
