### ISSUE TITLE
[NPC] Lieutenant Commander Thalvos

### ISSUE THREAD

**Issue by Brasso** [Atlantiss/NetherwingBugtracker#2238]
[//]: # (Enclose links to things related to the bug using http://wowhead.com or any other TBC database.)
[//]: # (You can use screenshot ingame to visual the issue.)
[//]: # (Write your tickets according to the format:)
[//]: # ([Quest][Azuremyst Isle] Red Snapper - Very Tasty!)
[//]: # ([NPC] Magistrix Erona)
[//]: # ([Spell][Mage] Fireball)
[//]: # ([Npc][Drop] Ghostclaw Lynx)
[//]: # ([Web] Armory doesnt work)

Spawn time is 10 minutes with multiple people waiting, is the time correct and does it have dynamic spawn time?

**Server Revision**: 
2244

**Comment by aresbrutus** [comment]
I will be fixing all of these at a later point.
