### ISSUE TITLE
[Loot][Nagrand]Boulderfist Hunter

### ISSUE THREAD

**Issue by DeltaLoads** [Atlantiss/NetherwingBugtracker#2239]
[//]: # (Enclose links to things related to the bug using http://wowhead.com or any other TBC database.)
[//]: # (You can use screenshot ingame to visual the issue.)
[//]: # (Write your tickets according to the format:)
[//]: # ([Quest][Azuremyst Isle] Red Snapper - Very Tasty!)
[//]: # ([NPC] Magistrix Erona)
[//]: # ([Spell][Mage] Fireball)
[//]: # ([Npc][Drop] Ghostclaw Lynx)
[//]: # ([Web] Armory doesnt work)

**Description**: 
Boulderfist Hunters are missing Obsidian Warbeads (https://www.wowhead.com/item=25433/obsidian-warbeads) in their loot table
**Current behaviour**:
Boulderfist Hunters dont drop Obsidian Warbeads
**Expected behaviour**: 
Boulderfist Hunters should drop Obsidian Warbeads
**Server Revision**: 
2244

**Comment by Shanghi** [comment]
They do have it. I just killed some just in case something strange was happening and got 3 from 6 kills.
![image](https://user-images.githubusercontent.com/2672633/47958281-bf2ca100-df9e-11e8-9be4-c7c3ffc17712.png)
