### ISSUE TITLE
Undercity elevator doors

### ISSUE THREAD

**Issue by corkus1111** [Atlantiss/NetherwingBugtracker#224]
Undercity elevator doors do not open correctly when you get to the bottom. You must wait until the elevator has gone up again for the door at the bottom of the lift to open.

**Comment by deku100** [comment]
It would appear that the bottom door of the left elevator opens when the platform is at the top of the shaft and closes when the platform reaches the bottom.

At the bottom:
![wowscrnshot_092518_003832](https://user-images.githubusercontent.com/43505181/45993571-86bfac00-c05d-11e8-9d51-f66104a3204e.jpg)
Looking in while platform is at the top:
![wowscrnshot_092518_004429](https://user-images.githubusercontent.com/43505181/45993585-8fb07d80-c05d-11e8-8762-03e41e23df95.jpg)

**Comment by Wolffenstein** [comment]
Fixed
