### ISSUE TITLE
[Quest] An improper Burial

### ISSUE THREAD

**Issue by Mewmewww** [Atlantiss/NetherwingBugtracker#2241]
[//]: # (Enclose links to things related to the bug using http://wowhead.com or any other TBC database.)
[//]: # (You can use screenshot ingame to visual the issue.)
[//]: # (Write your tickets according to the format:)
[//]: # ([Quest][Azuremyst Isle] Red Snapper - Very Tasty!)
[//]: # ([NPC] Magistrix Erona)
[//]: # ([Spell][Mage] Fireball)
[//]: # ([Npc][Drop] Ghostclaw Lynx)
[//]: # ([Web] Armory doesnt work)

**Description**: 
Burning corpses (Slain Sha'tar vindicator) and (Slain Auchenai Warrior)
**Current behaviour**:
Everything is counted towards sha'tar vindicators, so if you burn the slain auchenai warriors, you'll still only get credit for Sha'tar vindicator
**Expected behaviour**: 
Slain Auchenai warrior once burned should give me credit for that.
**Server Revision**: 
2244

**Comment by Mewmewww** [comment]
A slight note, this quest is completable but it requires some work

**Comment by Evolvee** [comment]
how did u complete it if they all give only 1 credit? :D

**Comment by Evolvee** [comment]
oh, the credit is correct
its just because there are 2 bodies at 1 spot rn(duplicates)

**Comment by Mikik3jr** [comment]
And for this quest: If I try to use the quest item while I am too far away the error says "You have no target", while I am targeting the corpse.

**Comment by Evolvee** [comment]
PepeHands

**Comment by Mikik3jr** [comment]
Is that a bug, or client issue?

**Comment by Mikik3jr** [comment]
And another thing: 2 corpses were really close to each other. I burned one, but I couldn't burn the other, until the first burned body disappeared. I was torching the burning body, in turn I was targeting the other one.

**Comment by Tenoutoften** [comment]
You don't burn your target, the item itself decided probably depending with range
