### ISSUE TITLE
[Quest] Whispers of the Raven God

### ISSUE THREAD

**Issue by netherwingbta** [Atlantiss/NetherwingBugtracker#2243]
[//]: # (Enclose links to things related to the bug using http://wowhead.com or any other TBC database.)
[//]: # (You can use screenshot ingame to visual the issue.)
[//]: # (Write your tickets according to the format:)
[//]: # ([Quest][Azuremyst Isle] Red Snapper - Very Tasty!)
[//]: # ([NPC] Magistrix Erona)
[//]: # ([Spell][Mage] Fireball)
[//]: # ([Npc][Drop] Ghostclaw Lynx)
[//]: # ([Web] Armory doesnt work)

**Description**: 
Get two buffs instead of one. 
https://www.wowhead.com/quest=10607/whispers-of-the-raven-god
**Current behaviour**:
![wow 2018-11-03 23-04-47-05](https://user-images.githubusercontent.com/43872263/47958616-b8b61d80-dfce-11e8-9a7b-d4bc12ba5d11.jpg)
![2018-11-03-2257-59 mp4_snapshot_15 06_ 2018 11 04_01 11 17](https://user-images.githubusercontent.com/43872263/47958618-c1a6ef00-dfce-11e8-9a8d-0e751e0d5452.jpg)

**Expected behaviour**: 
Maybe one is supposed to be invisible?
https://www.youtube.com/watch?v=0nz-dRGf2wE&t=61
**Server Revision**: 
2244

**Comment by aresbrutus** [comment]
https://github.com/Atlantiss/AtlantissTBCBT/issues/3120

**Comment by mhdemn** [comment]
Wanna update with some more bugs for this [quest](https://db.excalibur.ws/?quest=10607) that exist currently in 2270 along the bug reported in this issue.

Even though the places (where the different "The Xth Prophecy" objects are) complete your quest's objectives (if you have the buff active) when you approach them, these visual and/or annoying bugs are present:

- There are copies of the [object "The First Prophecy"](https://db.excalibur.ws/?object=184950) where the objects for [The Third Prophecy](https://db.excalibur.ws/?object=184968) and [The Fourth Prophecy](https://db.excalibur.ws/?object=184969) should be. 1st and 2nd Prophecies are in the correct place.

![image](https://user-images.githubusercontent.com/25901582/48275586-271f3380-e446-11e8-961f-e49b0911ac6e.png)

![image](https://user-images.githubusercontent.com/25901582/48275594-2a1a2400-e446-11e8-94be-cf15366cee9e.png)

- The [object "The Second Prophecy"](https://db.excalibur.ws/?object=184967) is in the correct spot, however:
  - The area where you get completion for this objective within the quest is way too big. I got it completed when I got onto the platform's upper floor (object is in the floor below), and I was standing on the furthermost section from the object below.
  - It is also spammy as hell, whereas the other 3 locations where the objects are give you the /whisper once, this one will get triggered over and over and fill your chat window.
  - Also, you can interact with this one, whereas the other 3 are not clickable ([as Blizzard designed](https://www.wowhead.com/quest=10607/whispers-of-the-raven-god#comments))

![image](https://user-images.githubusercontent.com/25901582/48276098-787bf280-e447-11e8-9d5a-880129306a7b.png)

![image](https://user-images.githubusercontent.com/25901582/48275947-1cb16980-e447-11e8-8387-28a43bfed1f6.png)


Coords for each object:
Prophecy 1
Prophecy 1
Prophecy 1

**Comment by Frankenberryberry** [comment]
I could not complete this quest. I successfully got the 2nd, 3rd and 4th prophecies but the 1st one wouldn't unlock =(

**Comment by Evolvee** [comment]
fixed in next rev
