### ISSUE TITLE
[Hunter] [Pet]: Pathfinding issues in this spot in HFP + unlinked mobs

### ISSUE THREAD

**Issue by mhdemn** [Atlantiss/NetherwingBugtracker#2244]
https://youtu.be/-CHI9Mim7Fc

**Description**: Went to tame one of these birds and when getting rid of one of them I saw that 1. They're not linked and they probably should be, 2. This terrain bugs the shit out of my pet's pathfinding when seeking my target (but not when following me).

**Current behaviour**: Pet can't find a path to it's target in this spot. Also, these two birds should be linked. 

**Expected behaviour**: Pet should find no issue when chasing down it's target here.

**Server Revision**: 2244

**Comment by Easyfraggy** [comment]
mmaps problem

Same ish area as https://github.com/Atlantiss/NetherwingBugtracker/issues/2158
