### ISSUE TITLE
[Nagrand]Halaa

### ISSUE THREAD

**Issue by DeltaLoads** [Atlantiss/NetherwingBugtracker#2245]
[//]: # (Enclose links to things related to the bug using http://wowhead.com or any other TBC database.)
[//]: # (You can use screenshot ingame to visual the issue.)
[//]: # (Write your tickets according to the format:)
[//]: # ([Quest][Azuremyst Isle] Red Snapper - Very Tasty!)
[//]: # ([NPC] Magistrix Erona)
[//]: # ([Spell][Mage] Fireball)
[//]: # ([Npc][Drop] Ghostclaw Lynx)
[//]: # ([Web] Armory doesnt work)

**Description**: 
Halaa is completly empty and uncapturable, missing wyvern outpost, missing guards and whole capturing event - unless you disabled it for some reason
http://wowwiki.wikia.com/wiki/Halaa
**Server Revision**: 
2244

**Comment by KevinTyrrell** [comment]
![4](https://user-images.githubusercontent.com/12791400/47961159-869ebe80-dfc2-11e8-9359-032a4d3fbf9f.png)

**Comment by Wolffenstein** [comment]
Fixed in rev 2787.
