### ISSUE TITLE
[Warrior][Spell] Charge + Intecept

### ISSUE THREAD

**Issue by killablink** [Atlantiss/NetherwingBugtracker#2247]
**Description**: Being charged or intercepted sometimes doesn't update fast enough, so you get stunned but you don't see the warrior actually charging at you.

**Current behaviour**: Not a fluid charge.
https://gfycat.com/HairyUnhealthyEnglishsetter (2nd intercept)
https://gfycat.com/CarefreeUnsungAdmiralbutterfly (3rd charge)
https://gfycat.com/ElatedDizzyAphid (1st and last charge)
**Expected behaviour**: Should be more fluid

**Server Revision**: 2244

**Comment by Wolffenstein** [comment]
Fixed in rev 2360.
