### ISSUE TITLE
[Spell][Warrior] Spell reflect

### ISSUE THREAD

**Issue by killablink** [Atlantiss/NetherwingBugtracker#2248]
**Description**: Spell reflecting a sheep sheeps the opponent for 50 seconds (Probably the same thing for every other spell that gets reflected)

**Current behaviour**: Spell reflecting a sheep sheeps the opponent for 50 seconds (Probably the same thing for every other spell that gets reflected)

**Expected behaviour**: PVP values should be applied (10 seconds)

**Server Revision**: 2244

**Comment by Easyfraggy** [comment]
Probably a global issue that reflected crowd control spells are not counted as PVP.

**Comment by netherwingbta** [comment]
Spell reflect buff is consumed on first impact. It should last entire duration, allowing for reflection of multiple spells.
You are also currently not able to reflect a spell that is mid-flight. It only works if you activate it before the cast goes off.

**Comment by Easyfraggy** [comment]
No need to research that - reflect is decided on cast success not on hit.

**Comment by ahlens** [comment]
Classic one
https://www.youtube.com/watch?v=Eh2JvonoUlg

**Comment by Easyfraggy** [comment]
> Classic one
> https://www.youtube.com/watch?v=Eh2JvonoUlg

That video is from first version of spell reflect where it would reflect everything during its entire duration. That was later changed to have the buff removed on first hit.

**Comment by ahlens** [comment]
Totally agree. Sorry, it's not 100% correct according to our patch.
