### ISSUE TITLE
[NPC] Marshrock Threshalisk feign death mid fight

### ISSUE THREAD

**Issue by wowthings** [Atlantiss/NetherwingBugtracker#2249]
[//]: # (Enclose links to things related to the bug using http://wowhead.com or any other TBC database.)
[//]: # (You can use screenshot ingame to visual the issue.)
[//]: # (Write your tickets according to the format:)
[//]: # ([Quest][Azuremyst Isle] Red Snapper - Very Tasty!)
[//]: # ([NPC] Magistrix Erona)
[//]: # ([Spell][Mage] Fireball)
[//]: # ([Npc][Drop] Ghostclaw Lynx)
[//]: # ([Web] Armory doesnt work)

**Description**: 
So I was fighting [this npc](https://www.wowhead.com/npc=19706/marshrock-threshalisk) at Zangarmarsh
**Current behaviour**:
and he "dies" mid fight, it happened several times with more of these mobs.
video:
https://streamable.com/bt09u
**Server Revision**: 
2244

**Comment by Wolffenstein** [comment]
He's playing dead, he even emotes when he attacks

**Comment by wowthings** [comment]
Lol fuck, right, didn't see that buff. I was so weirded out by that. I should check the wowhead comments when these things happens.
Sorry!
