### ISSUE TITLE
[Redridge Mountains] Greater Goretusks missing

### ISSUE THREAD

**Issue by PearlzEU** [Atlantiss/NetherwingBugtracker#225]
**Description**: 
Greater Goretusk population barely even exists. Spotted a single one near Bellygrub. All other Goretusk spots on the map, be it around the lake or down south at the Dire Condor/Black Hatchling area do not contain any Greater Goretusks.

**Current behaviour**:
Mobs "Greater Goretusk" barely existing.

**Expected behaviour**: 
Plenty of Goretusks in all the areas surrounding Lakeshire

**Comment by aresbrutus** [comment]
Fixed in one of the upcoming updates.
