### ISSUE TITLE
[NPC] Mogor chain lightning

### ISSUE THREAD

**Issue by Tinnoan** [Atlantiss/NetherwingBugtracker#2250]
**Description**: [Mogor](https://www.wowhead.com/npc=18069/mogor) from the last part of [Ring of Blood](https://www.wowhead.com/quest=9977/the-ring-of-blood-the-final-challenge) chain quest seems to cast chain lightning too often. he's currently casting spells non-stop, this should not be the case.

As can be seen in [this](https://youtu.be/LoB70fUnc_A?t=36) video as soon as the fight starts, he starts casting chain lightning, but then there's a lull until the next one is cast.

**Expected behaviour**: Mogor's chain lightning should have a cooldown before it can be used again.

**Server Revision**: 2244

**Comment by aresbrutus** [comment]
https://github.com/Atlantiss/AtlantissTBCBT/issues/2613

**Comment by Wolffenstein** [comment]
Fixed in rev 2406.

**Comment by Quinden** [comment]
This is active again as of revision 2766 and needs to be re-opened.
