### ISSUE TITLE
[NPC][Spell]Shienor Wing Guard - Shield Bash

### ISSUE THREAD

**Issue by killablink** [Atlantiss/NetherwingBugtracker#2251]
**Description**: Not sure if it's intended but the shield bash duration is really long (7-8 seconds?) while the CD is really short, making it so that if you only had 1 spell tree you are perma locked

**Current behaviour**: Not sure if it's intended but the shield bash duration is really long (7-8 seconds?) while the CD is really short, making it so that if you only had 1 spell tree you are perma locked

**Expected behaviour**:  Not sure but it's worth checking out if it seems normal

**Server Revision**: 2244

**Comment by xmesaj2** [comment]
https://www.wowhead.com/npc=18451 seems it shouldnt lock, just interrupt cast

**Comment by Evolvee** [comment]
rev XXX
