### ISSUE TITLE
Gaining threat while successfully feign-death'ed

### ISSUE THREAD

**Issue by KevinTyrrell** [Atlantiss/NetherwingBugtracker#2252]
[//]: # (Enclose links to things related to the bug using http://wowhead.com or any other TBC database.)
[//]: # (You can use screenshot ingame to visual the issue.)
[//]: # (Write your tickets according to the format:)
[//]: # ([Quest][Azuremyst Isle] Red Snapper - Very Tasty!)
[//]: # ([NPC] Magistrix Erona)
[//]: # ([Spell][Mage] Fireball)
[//]: # ([Npc][Drop] Ghostclaw Lynx)
[//]: # ([Web] Armory doesnt work)

**Description**: 
[Twitch Clip](https://clips.twitch.tv/GentleLaconicLorisPogChamp)

In this clip, you can see I feign deathed two enemy mobs while my pet was fighting a third. My feign death was not resisted, no matter what happens now I should be off the mobs aggro table.

I believe either spirit bond or mend pet put me back onto the aggro table, causing the mobs to chase me even though previously I was considered dead to them.

**Current behaviour**:
Mobs re-aggro onto feign deathed player -- presumably due to Spirit Bond (unconfirmed).

**Expected behaviour**:
Mobs do not re-gain combat with a player who is in a feigned death state. I am not completely sure about this however.

**Server Revision**: 
2253

**Comment by Zarant** [comment]
In my experience this is usually an issue with spirit bond generating aggro, that's usually why I never take spirit bond when leveling on private servers.

**Comment by Easyfraggy** [comment]
This sounds like a duplicate to me something with pets putting you in combat or not.

**Comment by Zarant** [comment]
I don't think that's the case, if you're the last person remaining on a mob's threat list and you have the feign death buff, the mob should reset, regardless if you're in combat or not.
I do remember hunters surviving boss fights with feign death, even post patch 2.3 where feign death don't drop you out of combat during boss fights. 
http://wowwiki.wikia.com/wiki/Wipe_recovery?oldid=1277617

**Comment by KevinTyrrell** [comment]
One thing that is worth mentioning is I do have a mend pet active on my pet while I feign death. If it ends up being true that spirit bond is bugged and gains you threat while feigned then that may mean all helpful spells would do the same.

I think @Zarant is onto something because after I feign death, mend pet + spirit bond are supposedly gaining me threat on all three mobs. On the two mobs that my pet wasn't attacking I would have certainly instantly gained aggro (because he never touched them) immediately but I didn't.

Another possibility but unlikely is for the mobs that were chasing me, my feign death wasn't resisted. But for the mob that was fighting my pet, it did resist. Thus I was still on his threat table and not the other two. My ui at this time didn't display the red error "Resisted" for feign death. However I feel like that's impossible because I've never seen a 'partial resist' in vanilla, where some mobs resist my feign death and others don't.

**Comment by Tereneckla** [comment]
Mend Pet/Spirit Bond generate no threat to a feigned hunter as of rev 3236

**Comment by KenguruSafari** [comment]
Sorry to say, but this still happens.
Feign death causes combat bug for the whole group, as far as I have experienced.
I leveled my hunter while partying with friends, and ever since feign death, healer have had to alt+f4 out of the game to reset aggro closer to 100 times by now.
Now that we do dungeons more often, we experience it more often.
If I overaggro, FD and pet dies, the entire group is in combat.

**Comment by KenguruSafari** [comment]
Sorry to say, but this still happens.
Feign death causes combat bug for the whole group, as far as I have experienced.
I leveled my hunter while partying with friends, and ever since feign death, healer have had to alt+f4 out of the game to reset aggro closer to 100 times by now.
Now that we do dungeons more often, we experience it more often.

**Comment by Tereneckla** [comment]
That is not relevant to this bug. This was the hunter gaining threat through various means while he is in feign death.
