### ISSUE TITLE
[NPC][Spell] Ethereal Arcanist - Arcane missiles?

### ISSUE THREAD

**Issue by killablink** [Atlantiss/NetherwingBugtracker#2253]
**Description**: He is also bugged and using instant arcane missiles, when he probably shouldn't even have the spell (or cast normal arcane missiles instead)
https://www.wowhead.com/npc=21405/ethereal-arcanist#abilities
Also, not sure if intended but from what I can only see from here his "Force blast" ability does normal dmg + 147 but it is currently doing 1200 dmg which is probably overtuned?

**Current behaviour**: ^

**Expected behaviour**: Doesnt cast arcane missiles and probably lower dmg on his force blast

**Server Revision**: 2244

**Comment by Evolvee** [comment]
![image](https://user-images.githubusercontent.com/1942409/47966508-826eb180-e053-11e8-9e86-59016bfc7e6b.png)

Force Blast scales with level

**Comment by Evolvee** [comment]
missiles fixed in rev XXX
