### ISSUE TITLE
[Spell][Mage] Blink (air to ground)(regular too)

### ISSUE THREAD

**Issue by killablink** [Atlantiss/NetherwingBugtracker#2254]
**Description**: So right now there are quite a few problems around with blink that I already reported in the past but heres something different.

Normally when you blink in the air high enough to the point that it doesnt blink you down to the ground, your blink is supposed to replace you in the air so that it resets your fall animation. Right now if you blink high in the air, the animation goes off but nothing happens, it doesnt reset your fall animation.
Also, right now the range to actually blink down to the ground is way too low. Blink always had an abnormal range in the air to blink down to the ground but it's really hard to blink to the ground with this weird range + added delay on blink.

**Current behaviour**:  Nothing happens when you blink in the air.
https://gfycat.com/ValidSpicyKomododragon

Even doesnt blink you down to the ground when you're close
https://gfycat.com/TheseMeaslyAcouchi

Blink is really bugged when you blink while running, you barely get distance at all
https://gfycat.com/TartSilentLice
https://gfycat.com/ElatedDiligentHeron (trying to blink at the same place,once while running, once standing stil)

**Expected behaviour**: Your fall should be reset after blinking if you don't blink directly to the ground. I know in retails its a lot smoother than it was before but you can see in the clip at NW, I'm close to the ground blinking and it doesnt even blink me down to the ground.

Retail clip: https://gfycat.com/ResponsibleReasonableCopperhead
( I also have retail clips from TBC that show you blink down to the ground from really far up if needed)

**Server Revision**: 2244

**Comment by aresbrutus** [comment]
Closing and requesting retest after the update of rev 2430 and 2431.
