### ISSUE TITLE
[NPC]Feralfen Mystic#18114  should keep [Spell]Lightnign Shield#12550 up outside of combat.

### ISSUE THREAD

**Issue by Tenoutoften** [Atlantiss/NetherwingBugtracker#2256]
**Description**: 
[[NPC]Feralfen Mystic#18114](https://www.wowhead.com/npc=18114/feralfen-mystic#abilities) should keep [[Spell]Lightnign Shield#12550](https://www.wowhead.com/spell=12550/lightning-shield) up outside of combat. Can be seen here:
https://youtu.be/Q4arqsSIPvA?t=82

**Current behaviour**:
Doesn't keep it up outside of combat.

**Expected behaviour**: 
Expected to keep it up outside of combat

**Server Revision**: 
2253

**Comment by Evolvee** [comment]
rev XXX
