### ISSUE TITLE
[Misc][NPC]Darkcrest Taskmaster#18086 should "calls for a nearby slave to assist him!"

### ISSUE THREAD

**Issue by Tenoutoften** [Atlantiss/NetherwingBugtracker#2257]
**Description**: 
[[NPC]Darkcrest Taskmaster#18086](https://www.wowhead.com/npc=18086/darkcrest-taskmaster) should "calls for a nearby slave to assist him!"
[here](https://youtu.be/QOgS605h7yU?t=211)

**Current behaviour**:
Doesn't

**Expected behaviour**: 
"calls for a nearby slave to assist him!"

**Server Revision**: 
2253

**Comment by Evolvee** [comment]
rev XXX
