### ISSUE TITLE
[Hunter][Pet] Pet and Mob keep shuffling

### ISSUE THREAD

**Issue by KevinTyrrell** [Atlantiss/NetherwingBugtracker#2259]
[//]: # (Enclose links to things related to the bug using http://wowhead.com or any other TBC database.)
[//]: # (You can use screenshot ingame to visual the issue.)
[//]: # (Write your tickets according to the format:)
[//]: # ([Quest][Azuremyst Isle] Red Snapper - Very Tasty!)
[//]: # ([NPC] Magistrix Erona)
[//]: # ([Spell][Mage] Fireball)
[//]: # ([Npc][Drop] Ghostclaw Lynx)
[//]: # ([Web] Armory doesnt work)

**Description**: 
[Twitch Clip](https://clips.twitch.tv/FurtiveGrossDonkeySquadGoals)

The mob attacked my pet, but was too close, so my pet chose to retreat a bit. This new spacing caused the mob to back up a tiny bit. Then my pet felt he wasn't close enough, so he moved forward. Then the mob backed up, and the cycle repeats itself.

[Here's another example on a different mob, recorded a few minutes later](https://clips.twitch.tv/KathishKathishPassionfruitTwitchRPG)

**Server Revision**: 
2253

**Comment by Easyfraggy** [comment]
Probably happens due to difference in elevation?

**Comment by KevinTyrrell** [comment]
@Easyfraggy [Here's another instance of it happening](https://clips.twitch.tv/MoralGloriousGalagoNotATK). This was also on elevated ground.

**Comment by Manaci** [comment]
Fixed
