### ISSUE TITLE
[Quest][Vanquishing Aquantion]

### ISSUE THREAD

**Issue by galediex** [Atlantiss/NetherwingBugtracker#226]
[//]: # (Enclose links to things related to the bug using http://wowhead.com or any other TBC database.)
[//]: # (You can use screenshot ingame to visual the issue.)
[//]: # (Write your tickets according to the format:)
[//]: # ([Quest][Azuremyst Isle] Red Snapper - Very Tasty!)
[//]: # ([NPC] Magistrix Erona)
[//]: # ([Spell][Mage] Fireball)
[//]: # ([Npc][Drop] Ghostclaw Lynx)
[//]: # ([Web] Armory doesnt work)

**Description**: Aquantion's spells are not interrupt-able.

**Current behaviour**: All of Aquantion's cannot be kicked, gouged, silenced via arcane torrent. 

**Expected behaviour**: All of Aquation's spells should be interrupt-able.

**Server Revision**: 2.4.3 Netherwing Open Beta Server

**Comment by meowmewo** [comment]
https://www.wowhead.com/npc=16292/aquantion#comments

Comments from TBC say hes immune to stuns + interrupts.
