### ISSUE TITLE
[Pet] Defensive Mode attack delay

### ISSUE THREAD

**Issue by KevinTyrrell** [Atlantiss/NetherwingBugtracker#2262]
[//]: # (Enclose links to things related to the bug using http://wowhead.com or any other TBC database.)
[//]: # (You can use screenshot ingame to visual the issue.)
[//]: # (Write your tickets according to the format:)
[//]: # ([Quest][Azuremyst Isle] Red Snapper - Very Tasty!)
[//]: # ([NPC] Magistrix Erona)
[//]: # ([Spell][Mage] Fireball)
[//]: # ([Npc][Drop] Ghostclaw Lynx)
[//]: # ([Web] Armory doesnt work)

**Description**: 
[Twitch Clip](https://clips.twitch.tv/CarefulBlueWolverineOSkomodo)

**Current behaviour**:
After killing a target while on defensive, the pet retreats to the owner as if on passive mode, and after a second or so, selects a new mob that has attacked him or the owner.

**Expected behaviour**: 
After killing a target while on defensive, the pet instantly targets a new mob that has attacked him or the owner.

**Server Revision**: 
2253

**Comment by Godmatik** [comment]
Rev 4014

Unable to reproduce
After first mob dies, pet immediately goes to second mob I am in combat with. Did not wait for me to get melee attacked again or anything like that.
Guess it was fixed at some point.
