### ISSUE TITLE
[NPC][Nagrand]Murkblood Scavenger

### ISSUE THREAD

**Issue by DeltaLoads** [Atlantiss/NetherwingBugtracker#2263]
[//]: # (Enclose links to things related to the bug using http://wowhead.com or any other TBC database.)
[//]: # (You can use screenshot ingame to visual the issue.)
[//]: # (Write your tickets according to the format:)
[//]: # ([Quest][Azuremyst Isle] Red Snapper - Very Tasty!)
[//]: # ([NPC] Magistrix Erona)
[//]: # ([Spell][Mage] Fireball)
[//]: # ([Npc][Drop] Ghostclaw Lynx)
[//]: # ([Web] Armory doesnt work)

**Description**: 
These NPCs award way too much XP, they have about 600hp and award 500xp at lvl 66, very easy to abuse to speed leveling up
**Current behaviour**:
Murkblood Scavangers award normal XP
**Expected behaviour**: 
Murkblood Scavangers should award 10% of current XP
**Server Revision**: 
2253

**Comment by Evolvee** [comment]
rev XXX
