### ISSUE TITLE
[Quest][Nagrand]The Totem of Kar'dash

### ISSUE THREAD

**Issue by DeltaLoads** [Atlantiss/NetherwingBugtracker#2264]
[//]: # (Enclose links to things related to the bug using http://wowhead.com or any other TBC database.)
[//]: # (You can use screenshot ingame to visual the issue.)
[//]: # (Write your tickets according to the format:)
[//]: # ([Quest][Azuremyst Isle] Red Snapper - Very Tasty!)
[//]: # ([NPC] Magistrix Erona)
[//]: # ([Spell][Mage] Fireball)
[//]: # ([Npc][Drop] Ghostclaw Lynx)
[//]: # ([Web] Armory doesnt work)

**Description**: 
Kurenai Captive completely ignores all enemies and doesn't use his abilities while being escorted, also he is offering quest and has gold "!" above him even before you kill the 2 Murkblood Brutes that are guarding him
https://www.wowhead.com/npc=18209/kurenai-captive#comments
**Current behaviour**:
Kurenai Captive offers quest before guards are killed and doesnt use abilities and attacks enemies while escorting
**Expected behaviour**: 
Shouldn't offer quest while guards are alive and should attack enemies while escorting
**Server Revision**: 
2253

**Comment by DeltaLoads** [comment]
also this guy path is totally screwed

**Comment by mhdemn** [comment]
> also this guy path is totally screwed

[^](https://youtu.be/RzqcczPz8E0)

**Comment by aresbrutus** [comment]
https://github.com/Atlantiss/AtlantissTBCBT/issues/3331

**Comment by manslaughter** [comment]
Same issue applies to the Mag'har captive for horde

**Comment by Tenoutoften** [comment]
Merged into https://github.com/Atlantiss/NetherwingBugtracker/issues/3678
