### ISSUE TITLE
[Quest] Mark V is alive!

### ISSUE THREAD

**Issue by netherwingbta** [Atlantiss/NetherwingBugtracker#2265]
[//]: # (Enclose links to things related to the bug using http://wowhead.com or any other TBC database.)
[//]: # (You can use screenshot ingame to visual the issue.)
[//]: # (Write your tickets according to the format:)
[//]: # ([Quest][Azuremyst Isle] Red Snapper - Very Tasty!)
[//]: # ([NPC] Magistrix Erona)
[//]: # ([Spell][Mage] Fireball)
[//]: # ([Npc][Drop] Ghostclaw Lynx)
[//]: # ([Web] Armory doesnt work)

**Description**: 
https://www.wowhead.com/quest=10191/mark-v-is-alive
The escort robot does not assist in attacking anything.
**Current behaviour**:
He just ignores all mobs.
**Expected behaviour**: 
https://www.youtube.com/watch?v=xI_p_NOkEMk
**Server Revision**: 
2244

**Comment by Mikik3jr** [comment]
Ignores even the ones that are hitting it.

**Comment by Matija5** [comment]
Ignores everything he just walks pulls mobs and doesn't give shit

**Comment by rychersky** [comment]
![wowscrnshot_122618_113959](https://user-images.githubusercontent.com/45608488/50454170-fcf4d880-0902-11e9-9fa1-12bfb3296536.jpg)

This is still occurring.

**Comment by Tenoutoften** [comment]
Merged into https://github.com/Atlantiss/NetherwingBugtracker/issues/3678
