### ISSUE TITLE
[Quests][Nagrand]The Ring of Blood

### ISSUE THREAD

**Issue by DeltaLoads** [Atlantiss/NetherwingBugtracker#2266]
[//]: # (Enclose links to things related to the bug using http://wowhead.com or any other TBC database.)
[//]: # (You can use screenshot ingame to visual the issue.)
[//]: # (Write your tickets according to the format:)
[//]: # ([Quest][Azuremyst Isle] Red Snapper - Very Tasty!)
[//]: # ([NPC] Magistrix Erona)
[//]: # ([Spell][Mage] Fireball)
[//]: # ([Npc][Drop] Ghostclaw Lynx)
[//]: # ([Web] Armory doesnt work)

**Description**: 
Quest - The Ring of Blood: The Warmaul Champion
Warmaul Champion (https://www.wowhead.com/npc=18402/warmaul-champion) his attacks are insane, can one shot a tank with mortal strike, not to mention once sunder armor is applied there is no way to keep tank alive even with 2 healers

Quest - The Ring of Blood: The Final Challenge
Mogor (https://www.wowhead.com/npc=18069/mogor) spams Chain Lighting jumps to all party members even if they are behind him and one shots them, also keeps using it and it cant be interrupted so this quest is completly impossible with normal 5 people group

On all of them, players dont get credit for the kill unless they tag and do final blow
**Server Revision**: 
2253

**Comment by Tinnoan** [comment]
1st issue, I've been sifting through some patch 2.x comments on [wowhead](https://www.wowhead.com/quest=9973/the-ring-of-blood-the-warmaul-champion#comments) to give a clue as to what kind of damage he should be doing, and well it varies quite a bit, some saying MS hit for over 5k, some about 4k, so there definitely seems to be some variance there, he's supposed to be the hardest of the bosses in Ring of Blood.

2nd issue #2250 Already posted this issue with video evidence. Except for the jumping on people behind him, that was mentioned in wowhead comments, but didn't have any kind of evidence of if this was actually happening or not currently.

**Comment by Easyfraggy** [comment]
For second issue Chaining can ALWAYS hit behind a mob, this is definitely not a bug question is if the chaining range is too far.

**Comment by DeltaLoads** [comment]
chain lighting was hitting all members even if they were at their max range for heal/ranged attacks

**Comment by Tinnoan** [comment]
chain radius is definitely high, I can attest to that

**Comment by Easyfraggy** [comment]
![image](https://user-images.githubusercontent.com/36134067/48073167-74996780-e1de-11e8-8b84-6dcb8e0b3589.png)

**Comment by mhdemn** [comment]
Wanna add the following issues that happen rn in 2256:
Bosses aren't leashed to the arena (scratch that, that's noted already)
Mogor doesn't respawn at the same time the quest becomes available again when you fail this one.
Warmaul Champion (previous one to Mogor), also it seems a bit clunky since sometimes he will get stuck or something and not initiate his respawn timer in his initial position (Tsu and Legs are aware of this)

**Comment by aresbrutus** [comment]
https://github.com/Atlantiss/AtlantissTBCBT/issues/2613

**Comment by Lecia2134** [comment]
I dont see it here, wanted to mention Rokdar the colossus boss seems to reset aggro everytime he does his aoe stun. Not sure if this is intended. Cant remember from retail.

**Comment by Zadiel** [comment]
Confirming he still hits way too hard; he's hitting me for 6-7k with Mortal Strike in bear form at level 65.

**Comment by Manaci** [comment]
Fixed
