### ISSUE TITLE
[Quest] Shutting Down Manaforge B'naar

### ISSUE THREAD

**Issue by netherwingbta** [Atlantiss/NetherwingBugtracker#2268]
[//]: # (Enclose links to things related to the bug using http://wowhead.com or any other TBC database.)
[//]: # (You can use screenshot ingame to visual the issue.)
[//]: # (Write your tickets according to the format:)
[//]: # ([Quest][Azuremyst Isle] Red Snapper - Very Tasty!)
[//]: # ([NPC] Magistrix Erona)
[//]: # ([Spell][Mage] Fireball)
[//]: # ([Npc][Drop] Ghostclaw Lynx)
[//]: # ([Web] Armory doesnt work)

**Description**: 
https://www.wowhead.com/quest=10329/shutting-down-manaforge-bnaar
https://www.wowhead.com/quest=10299/shutting-down-manaforge-bnaar
It's missing the initial emote in the chat, the 2 minute warning and the 1 minute warning.
Also missing the console window to start the event.
**Current behaviour**:
![wow 2018-11-04 16-23-24-82](https://user-images.githubusercontent.com/43872263/47966218-500f8500-e050-11e8-9f87-36d820dfc8d4.jpg)
Incorrect spawning

**Expected behaviour**: 
![2min](https://user-images.githubusercontent.com/43872263/47966219-530a7580-e050-11e8-84fe-227994d84fa3.png)
https://www.youtube.com/watch?v=LkcvDAt1lU0

The technicians are also supposed to channel to try and stop the shut down and do emotes. 
![technicianduru](https://user-images.githubusercontent.com/43872263/47972057-64777000-e098-11e8-998c-eb492d3c6479.jpg)
https://www.youtube.com/watch?v=buoUgB-6ujQ
![dialogue](https://user-images.githubusercontent.com/43872263/47966639-02494b80-e055-11e8-9261-8f9fa83bea7e.jpg)
**Server Revision**: 
2253

**Comment by Matija5** [comment]
Also if you are in party Only one gets completion

**Comment by maxturtlesc2** [comment]
Just completed this quest, technicians that spawn don't even aggro you and does not even stop the extinction process.
<img src="https://i.imgur.com/sefKq02.jpg">
3 out of 5 technicians didn't even come close to the console, and just stood miles away from it.
<img src="https://i.imgur.com/fR5socB.jpg">

**Comment by Wolffenstein** [comment]
Fixed in rev 3104.
