### ISSUE TITLE
Mobs in laughing skull ruins in nagrand  walking through each other

### ISSUE THREAD

**Issue by rasin00** [Atlantiss/NetherwingBugtracker#2269]
[//]: # (Enclose links to things related to the bug using http://wowhead.com or any other TBC database.)
[//]: # (You can use screenshot ingame to visual the issue.)
[//]: # (Write your tickets according to the format:)
[//]: # ([Quest][Azuremyst Isle] Red Snapper - Very Tasty!)
[//]: # ([NPC] Magistrix Erona)
[//]: # ([Spell][Mage] Fireball)
[//]: # ([Npc][Drop] Ghostclaw Lynx)
[//]: # ([Web] Armory doesnt work)

**Description**: 

**Current behaviour**:

**Expected behaviour**: 

**Server Revision**:

**Comment by Easyfraggy** [comment]
Please type .npc info while targetting the npcs and provide entry+id.

I did find 1 wrong spawn - fixing soon. 17138 ID 14/15.

**Comment by Easyfraggy** [comment]
17138 14/15 fixed in rev biosphere. Please use .npc info next time so I know which mobs to fix.
