### ISSUE TITLE
[Item][Spell] Faintly Glowing Skull item=4945 spell=16375 heals too little

### ISSUE THREAD

**Issue by Jacksn5** [Atlantiss/NetherwingBugtracker#227]
**Description**:
[Faintly Glowing Skull's](https://db.excalibur.ws/?item=4945) [Drain Life](https://db.excalibur.ws/?spell=16375) should deal 75 to 125 damage and heal the same amount, but despite fully dealing 108 damage without killing the NPC or overhealing myself it only healed 26 hp, roughly 25%.

![Faintly Glowing Skull Combat Log](https://i.imgur.com/6PJLrRn.png)

**Server Revision**: 
2028

**Comment by Easyfraggy** [comment]
![image](https://user-images.githubusercontent.com/36134067/45930718-e0dc4680-bf63-11e8-9bbc-89b8d5f9c250.png)

Cannot reproduce
