### ISSUE TITLE
Player Corpses Everywhere

### ISSUE THREAD

**Issue by uhhisthistaken** [Atlantiss/NetherwingBugtracker#2270]
In Hellfire Pennisula 

Both sides of The Path of Glory

Player corpses are visible all over the place with visible name plates.  Looks like I could see every player death since server opened.

**Comment by Wolffenstein** [comment]
Screenshot?

**Comment by uhhisthistaken** [comment]
<a href="http://tinypic.com?ref=2s0yc05" target="_blank"><img src="http://i63.tinypic.com/2s0yc05.jpg" border="0" alt="Image and video hosting by TinyPic"></a>

**Comment by Manaci** [comment]
?????
