### ISSUE TITLE
Charakter turning movement inconsistent

### ISSUE THREAD

**Issue by Nicemann1089** [Atlantiss/NetherwingBugtracker#2271]
[//]: # (Enclose links to things related to the bug using http://wowhead.com or any other TBC database.)
[//]: # (You can use screenshot ingame to visual the issue.)
[//]: # (Write your tickets according to the format:)
[//]: # ([Quest][Azuremyst Isle] Red Snapper - Very Tasty!)
[//]: # ([NPC] Magistrix Erona)
[//]: # ([Spell][Mage] Fireball)
[//]: # ([Npc][Drop] Ghostclaw Lynx)
[//]: # ([Web] Armory doesnt work)

https://drive.google.com/file/d/1wJFwFM92sN74AMXVNQ9PIfo_F-FJCTzV/view

**Description**: The charakter turns sometimes slower to center or even stays with his upper body in the direction until more than 90° turned. 

**Current behaviour**: Legs and upper body are often not aligned.

**Expected behaviour**: The whole charakter should quickly adjust to center with animation.

**Server Revision**: 2253

**Comment by Wolffenstein** [comment]
Client-side issue. We don't control that.

**Comment by Nicemann1089** [comment]
But I only see that on private servers. Do you know how to fix this?

**Comment by Easyfraggy** [comment]
It was like that on retail during tbc also....
