### ISSUE TITLE
[Quest] Help!

### ISSUE THREAD

**Issue by Xeldore** [Atlantiss/NetherwingBugtracker#2273]
[//]: # (Enclose links to things related to the bug using http://wowhead.com or any other TBC database.)
[//]: # (You can use screenshot ingame to visual the issue.)
[//]: # (Write your tickets according to the format:)
[//]: # ([Quest][Azuremyst Isle] Red Snapper - Very Tasty!)
[//]: # ([NPC] Magistrix Erona)
[//]: # ([Spell][Mage] Fireball)
[//]: # ([Npc][Drop] Ghostclaw Lynx)
[//]: # ([Web] Armory doesnt work)

**Description**: Cage is always opened, with corki inside , cant free him with key (nothing happens when you click on cage), cage doesnt reset.

**Current behaviour**:Nothing happens when you click on the cage to open it , I have key. cage doesnt reset

**Expected behaviour**: Cage door should be closed and clicking on it should free Corki.

**Server Revision**: 2253
![wowscrnshot_110418_173632](https://user-images.githubusercontent.com/26502961/47967024-3e7eab00-e059-11e8-86a2-aa3d8dab847c.jpg)

**Comment by Evolvee** [comment]
rev XXX

**Comment by Easyfraggy** [comment]
Also only grants credit to 1 person at a time it seems

**Comment by Evolvee** [comment]
its not even applied on the server yet??

**Comment by Evolvee** [comment]
or report all the quests together
...

there is a problem i cant fix  https://github.com/Atlantiss/NetherwingBugtracker/issues/529 with cages granting credit to 1 person only

**Comment by Mewmewww** [comment]
Just a very slight name bug @Evolvee 
https://imgur.com/a/bW14NPU

**Comment by Evolvee** [comment]
should be better after rev YYY but still requires rewrite after wolf fixes https://github.com/Atlantiss/NetherwingBugtracker/issues/529
