### ISSUE TITLE
[NPC][Spell] Mo'arg Doomsmith, Doomsaw

### ISSUE THREAD

**Issue by netherwingbta** [Atlantiss/NetherwingBugtracker#2274]
[//]: # (Enclose links to things related to the bug using http://wowhead.com or any other TBC database.)
[//]: # (You can use screenshot ingame to visual the issue.)
[//]: # (Write your tickets according to the format:)
[//]: # ([Quest][Azuremyst Isle] Red Snapper - Very Tasty!)
[//]: # ([NPC] Magistrix Erona)
[//]: # ([Spell][Mage] Fireball)
[//]: # ([Npc][Drop] Ghostclaw Lynx)
[//]: # ([Web] Armory doesnt work)

**Description**: 
The ability Doomsaw does nothing, and the infernal is visible. 
https://www.wowhead.com/npc=16944/moarg-doomsmith#abilities
**Current behaviour**:
![wow 2018-11-04 17-44-58-50](https://user-images.githubusercontent.com/43872263/47967035-7dacfc00-e059-11e8-9db8-ee426051da3a.png)

Summon the saw and it does nothing.
**Expected behaviour**: 
Supposed to be a boomerang type attack, the saw flies in the air and eventually hits you.
https://www.youtube.com/watch?v=Mc4_6VNU-AY
**Server Revision**: 
2253

**Comment by Evolvee** [comment]
rev 2911
