### ISSUE TITLE
[NPC] Male / Female Kaliri Hatchling

### ISSUE THREAD

**Issue by Kidcudi123** [Atlantiss/NetherwingBugtracker#2275]
These have absurd amount of HP, is there a beastiary for these?

**Comment by Easyfraggy** [comment]
![image](https://user-images.githubusercontent.com/36134067/47969403-36cdff00-e077-11e8-8237-d363b18b6c61.png)
![image](https://user-images.githubusercontent.com/36134067/47969407-3fbed080-e077-11e8-954a-5ce19356bf59.png)
![image](https://user-images.githubusercontent.com/36134067/47969411-477e7500-e077-11e8-84b8-0aac1eb976cb.png)

**Comment by Easyfraggy** [comment]
![image](https://user-images.githubusercontent.com/36134067/47969936-f5415200-e07e-11e8-86bc-e7bce900bd2f.png)

Male Kaliri do indeed have too much hp, female is correct.

**Comment by Tereneckla** [comment]
Fixed
