### ISSUE TITLE
[Quest] You, Robot

### ISSUE THREAD

**Issue by netherwingbta** [Atlantiss/NetherwingBugtracker#2276]
[//]: # (Enclose links to things related to the bug using http://wowhead.com or any other TBC database.)
[//]: # (You can use screenshot ingame to visual the issue.)
[//]: # (Write your tickets according to the format:)
[//]: # ([Quest][Azuremyst Isle] Red Snapper - Very Tasty!)
[//]: # ([NPC] Magistrix Erona)
[//]: # ([Spell][Mage] Fireball)
[//]: # ([Npc][Drop] Ghostclaw Lynx)
[//]: # ([Web] Armory doesnt work)

**Description**: 
https://www.wowhead.com/quest=10248/you-robot
Quest is completely stock, nothing about it works.
**Current behaviour**:
Pet doesn't work, Negatron just spawns and stands there.
Unable to retry the quest, probably requires a server restart atm. 
**Expected behaviour**: 
Pet should follow you and be usable. Negatron should spawn much further away, run towards you and then do a yell emote.
https://www.youtube.com/watch?v=mWw-3rumZ8I
https://www.youtube.com/watch?v=X4_8Aautsa0
**Server Revision**: 
2253

**Comment by aresbrutus** [comment]
https://github.com/Atlantiss/AtlantissTBCBT/issues/3142

**Comment by jfuglas** [comment]
Still bugged. The minion does not gain aggro

**Comment by Wolffenstein** [comment]
Fixed in rev 3327.
