### ISSUE TITLE
[Quest] [NPC] [Typo] [Extremely low prio issue]: Welcoming the Wolf Spirit

### ISSUE THREAD

**Issue by mhdemn** [Atlantiss/NetherwingBugtracker#2277]
*Sorry in advance, this is pretty grammar bitch-y.

https://tbc-twinhead.twinstar.cz/?quest=10791
https://tbc-twinhead.twinstar.cz/?npc=18384
![image](https://user-images.githubusercontent.com/25901582/47967557-c61ae880-e05e-11e8-9f04-d931a172e256.png)

**Description**: When you use the incense near the candles and the even starts, the NPC starts his speech with a /e that's missing a period (.) symbol. 

**Current behaviour**: Malukaz dons his wolf-fur vestments

**Expected behaviour**: Malukaz dons his wolf-fur vestments.

**Server Revision**: 2253

**Comment by Evolvee** [comment]
rev XXX
