### ISSUE TITLE
[Quest] Shutting Down Manaforge Coruu

### ISSUE THREAD

**Issue by netherwingbta** [Atlantiss/NetherwingBugtracker#2278]
[//]: # (Enclose links to things related to the bug using http://wowhead.com or any other TBC database.)
[//]: # (You can use screenshot ingame to visual the issue.)
[//]: # (Write your tickets according to the format:)
[//]: # ([Quest][Azuremyst Isle] Red Snapper - Very Tasty!)
[//]: # ([NPC] Magistrix Erona)
[//]: # ([Spell][Mage] Fireball)
[//]: # ([Npc][Drop] Ghostclaw Lynx)
[//]: # ([Web] Armory doesnt work)

**Description**: 
https://www.wowhead.com/quest=10330/shutting-down-manaforge-coruu
https://www.wowhead.com/quest=10321/shutting-down-manaforge-coruu
Same as the previous manaforge shutdown, missing the initial emote, 2 min warning and 1 minute warning. Also no dialogue window to start the event, you just right click. Spawned mobs just run to their spot and stack on top of each other, then do nothing.
You can probably just leave the area and not have to fight any of them and get the shut down credit.
Also they are spawning in pairs and in the same spot every time, completely different from retail.
The technicians are also supposed to channel to try and stop the shut down and do emotes. 
![coruu](https://user-images.githubusercontent.com/43872263/47967833-1a739780-e062-11e8-8925-7d220b7c6401.jpg)

**Expected behaviour**: 
![console](https://user-images.githubusercontent.com/43872263/47967741-1135fb00-e061-11e8-8fae-1fe4cfbb357c.jpg)
![channeling](https://user-images.githubusercontent.com/43872263/47967848-51e24400-e062-11e8-8d46-150ee44b861b.jpg)

https://www.youtube.com/watch?v=dFB_Q_WOXvg

**Server Revision**: 
2253

**Comment by aresbrutus** [comment]
https://github.com/Atlantiss/AtlantissTBCBT/issues/3139

**Comment by Matija5** [comment]
Also if you are in party Only one gets completion

**Comment by danbopes** [comment]
In addition to the aforementioned bugs, this quest also bugs out at some point after server restarts, and prevents you from interacting with the console. See #5638 and #4298

**Comment by Wolffenstein** [comment]
Fixed in rev 3104.
