### ISSUE TITLE
[NPC] Starving Helboar aggro range too far

### ISSUE THREAD

**Issue by Ceago** [Atlantiss/NetherwingBugtracker#2279]
**Description**: Starving Helboars aggro at or before the range for charge while other mobs of similar level do not.  https://streamable.com/pab1i  https://streamable.com/67vps
**Current behaviour**:  Will aggro before i can get in range for charge.

**Expected behaviour**:  Just a little less aggro range?

**Server Revision**: 2253

**Comment by Evolvee** [comment]
the NPC has set aggroRange to 28 in DB for some reason

@Easyfraggy @aresbrutus @Wolffenstein is this indended?

**Comment by Kidcudi123** [comment]
https://www.wowhead.com/npc=16879/starving-helboar#comments

**Comment by Evolvee** [comment]
![image](https://user-images.githubusercontent.com/1942409/47970099-23c02c80-e081-11e8-9826-e5e63a2ab861.png)

k lets call it a day

**Comment by Ceago** [comment]
Neat!  I hate it! but glad it's blizzlike.
