### ISSUE TITLE
[NPC] Dust Howler [Questitem] Howling Wind

### ISSUE THREAD

**Issue by Mewmewww** [Atlantiss/NetherwingBugtracker#2280]
[//]: # (Enclose links to things related to the bug using http://wowhead.com or any other TBC database.)
[//]: # (You can use screenshot ingame to visual the issue.)
[//]: # (Write your tickets according to the format:)
[//]: # ([Quest][Azuremyst Isle] Red Snapper - Very Tasty!)
[//]: # ([NPC] Magistrix Erona)
[//]: # ([Spell][Mage] Fireball)
[//]: # ([Npc][Drop] Ghostclaw Lynx)
[//]: # ([Web] Armory doesnt work)

**Description**: 
Howling Wind dropped by Dust Howler
**Current behaviour**:
Howling Wind droprate on Dust Howler should be around 11%, its about 5% atm and its too low.
**Expected behaviour**: 
Should be higher drop rate, still haven't gotten it.
**Server Revision**: 
2253

**Comment by aresbrutus** [comment]
Fixed in rev Eris
