### ISSUE TITLE
[NPC][Spell] Firewing Bloodwarder - Shadow Shock

### ISSUE THREAD

**Issue by killablink** [Atlantiss/NetherwingBugtracker#2281]
**Description**:  Deals 1200 damage

**Current behaviour**: Deals 1200 damage

**Expected behaviour**: According to people posting from patch 2.0, it dealt around 700-800 damage. 
https://www.wowhead.com/npc=1410/firewing-bloodwarder#comments

**Server Revision**:  2253

**Comment by netherwingbta** [comment]
https://github.com/Atlantiss/NetherwingBugtracker/issues/2125
