### ISSUE TITLE
Mind control combat bug

### ISSUE THREAD

**Issue by genesis187** [Atlantiss/NetherwingBugtracker#2282]
[//]: # (Enclose links to things related to the bug using http://wowhead.com or any other TBC database.)
[//]: # (You can use screenshot ingame to visual the issue.)
[//]: # (Write your tickets according to the format:)
[//]: # ([Quest][Azuremyst Isle] Red Snapper - Very Tasty!)
[//]: # ([NPC] Magistrix Erona)
[//]: # ([Spell][Mage] Fireball)
[//]: # ([Npc][Drop] Ghostclaw Lynx)
[//]: # ([Web] Armory doesnt work)

**Description**: 
mind controlling mobs in ramparts causes combat bug

**Current behaviour**:

**Expected behaviour**: 

**Server Revision**:

**Comment by Easyfraggy** [comment]
Can't replicate this - someone please elaborate.

**Comment by The14me** [comment]
Cant reproduce too.Please re-open if happen again or at least give more info(mob id or something)
