### ISSUE TITLE
[Quest] Who Are They?

### ISSUE THREAD

**Issue by mhdemn** [Atlantiss/NetherwingBugtracker#2283]
https://tbc-twinhead.twinstar.cz/?spell=32756
https://tbc-twinhead.twinstar.cz/?spell=38081 (dunno which one is the right buff)

**Description**: So during this quest where you get a disguise and talk to a few NPCs that would be hostile otherwise, if you are a hunter, while the friendly (thanks to the disguise) NPCs ignore you and your pet, the hostile ones that stand guard and can identify you will attack you or your pet, breaking your disguise when hostile action happens. However, hostile action towards the hunter's pet won't effect the hunter itself, resulting in the following behaviour:

**Current behaviour**: https://youtu.be/5KxC8NQaP18 Pet engages on the hostile guard, having no effect on the hunter (until the hunter does take part, removing the disguise).

**Expected behaviour**: Hostile action on the hunter's pet should work like direct action on the hunter itself.

**Server Revision**: 2253

PS: You also get 2 stacks of the disguise buff, thing that has no effect whatsoever in gameplay in any form, but if you wanna polish that detail out, here it is.

**Comment by Godmatik** [comment]
Invalid report.

Per the below - it is intended that you can send hunter pet on the hostile mobs and it does not break your own disguise. So there is no bug here.

![asadsd](https://github.com/user-attachments/assets/a1b5af5d-8741-43c9-9efd-492849fdea6a)
