### ISSUE TITLE
Water elemental doesn't attack polymorphed npc

### ISSUE THREAD

**Issue by Tweez1** [Atlantiss/NetherwingBugtracker#2284]
[//]: # (Enclose links to things related to the bug using http://wowhead.com or any other TBC database.)
[//]: # (You can use screenshot ingame to visual the issue.)
[//]: # (Write your tickets according to the format:)

[//]: # ([Spell][Mage] waterbolt and polymorph)

**Description**: 

**Current behaviour**:
Water elemental's waterbolt ability cannot be used on a polymorphed enemy. The water elemental responds as if the enemy is freindly.

**Expected behaviour**: 
Water bolt should break polymorph.

**Server Revision**:

**Comment by Easyfraggy** [comment]
https://github.com/Atlantiss/NetherwingBugtracker/issues/456
