### ISSUE TITLE
[NPC][Spell] Cabal Abjurist - Arcane Missiles

### ISSUE THREAD

**Issue by killablink** [Atlantiss/NetherwingBugtracker#2285]
**Description**:  He also has an instant 1 arcane missiles spell.

**Current behaviour**: He also has an instant 1 arcane missiles spell.

**Expected behaviour**:  Shouldn't have that.

**Server Revision**: 2253

**Comment by Tenoutoften** [comment]
Doesn't run away from melee after he frost novas but that is likely because he uses just an instant arcane bolt atm 2256

**Comment by xmesaj2** [comment]
fix in rev 2080
