### ISSUE TITLE
[Pet/Pathing] Example of odd pet pathing (applies to anywhere in the world)

### ISSUE THREAD

**Issue by BezawitNW** [Atlantiss/NetherwingBugtracker#2288]
Notice at the very beginning that I pull aggro on the mob with a Shadow Bolt. The mob runs directly toward me. However my pet runs backwards and then toward me (in almost a triangle shape). This seems trivial but this is what I mean when I say "pet pathing is weird on NW". This is not an isolated event and happens just about everywhere I have leveled so far:

https://clips.twitch.tv/SincereKnottyDoveYouDontSay

**Comment by devo6969** [comment]
This is fixed
