### ISSUE TITLE
Warlock's rain of fire damage values incorrect

### ISSUE THREAD

**Issue by Shiek94** [Atlantiss/NetherwingBugtracker#2289]
**Description**: 
Warlock's rain of fire is dealing immense damange, way too much to be the correct values (warlock literally overaggroing with first RoF tick after giving it 20 seconds of aoe tanking in dungeon).

It's very possible that rain of fire ticks for what it should deal in total damage at the moment (group's warlock reported 1,5k ticks on lvl 64, while blizzard ticks for 200 dmg at that level.

**Current behaviour**:
Warlock's spell rain of fire does way too much damage, possibly it's total damage value each tick.

**Expected behaviour**: 
All RoF ticks should add up to the amount 1 tick is doing at the moment.

**Server Revision**: 
2253

**Comment by Wolffenstein** [comment]
Fixed in rev 2313.
