### ISSUE TITLE
[NPC][Bloodmyst Isle] Draenei Cartographer

### ISSUE THREAD

**Issue by Sinyr** [Atlantiss/NetherwingBugtracker#229]
[//]: # (Enclose links to things related to the bug using http://wowhead.com or any other TBC database.)
[//]: # (You can use screenshot ingame to visual the issue.)
[//]: # (Write your tickets according to the format:)
[//]: # ([Quest][Azuremyst Isle] Red Snapper - Very Tasty!)
[//]: # ([NPC] Magistrix Erona)
[//]: # ([Spell][Mage] Fireball)
[//]: # ([Npc][Drop] Ghostclaw Lynx)
[//]: # ([Web] Armory doesnt work)
**Description**:
NPC ID: 17600

**Current behaviour**:
NPCs are in a proper pose, but alive:

![cart](https://user-images.githubusercontent.com/9539181/45930260-3b72a400-bf5e-11e8-862d-21829fa8c288.png)

**Expected behaviour**: 
NPCs should be dead corpses  (gray):
https://www.wowhead.com/quest=9620/the-missing-survey-team#screenshots:id=15269

**Server Revision**: 
2028

**Comment by Evolvee** [comment]
fixed in next hotfix revision
![image](https://user-images.githubusercontent.com/1942409/45930413-5219fa80-bf60-11e8-8dad-6946bc0c0980.png)
