### ISSUE TITLE
[Hunter] [Pet Abilities] Pet's special abilities and Kill Command won't crit

### ISSUE THREAD

**Issue by Corrozus** [Atlantiss/NetherwingBugtracker#2291]
[//]: # (Enclose links to things related to the bug using http://wowhead.com or any other TBC database.)
[//]: # (You can use screenshot ingame to visual the issue.)
[//]: # (Write your tickets according to the format:)
[//]: # ([Quest][Azuremyst Isle] Red Snapper - Very Tasty!)
[//]: # ([NPC] Magistrix Erona)
[//]: # ([Spell][Mage] Fireball)
[//]: # ([Npc][Drop] Ghostclaw Lynx)
[//]: # ([Web] Armory doesnt work)

**Description**: Currently pet abilities and Kill Command aren't able to crit. I've logged half a day's worth of questing with recount and, as evident from below screenshots, Kill Command, Gore and Bite have not yet crit once. I've tried speccing both with and without [Focused Fire](http://db.hellfire-tbc.com/?spell=35030). Outside of recount I also have MSBT and have not once noticed Kill Command or other special pet abilities crit.

https://imgur.com/a/ZEuDvdq Kill Command
https://imgur.com/a/yaE573B Gore
https://imgur.com/a/r4JQ1P4 Bite

**Current behaviour**: Pet abilities and Kill Command aren't able to critically strike.

**Expected behaviour**: Pet abilities and Kill Command should be able to critically strike

**Server Revision**:  2253

**Comment by Wolffenstein** [comment]
Fixed in rev 2273.
