### ISSUE TITLE
Undercity NPC people not always walking on floor level

### ISSUE THREAD

**Issue by Nicemann1089** [Atlantiss/NetherwingBugtracker#2292]
[//]: # (Enclose links to things related to the bug using http://wowhead.com or any other TBC database.)
[//]: # (You can use screenshot ingame to visual the issue.)
[//]: # (Write your tickets according to the format:)
[//]: # ([Quest][Azuremyst Isle] Red Snapper - Very Tasty!)
[//]: # ([NPC] Magistrix Erona)
[//]: # ([Spell][Mage] Fireball)
[//]: # ([Npc][Drop] Ghostclaw Lynx)
[//]: # ([Web] Armory doesnt work)

https://drive.google.com/file/d/1_e1Dgybsn7WdlRU-pKmPDvuK6i9H1rCV/view?usp=drivesdk

**Description**: The wandering npc are going through the floor, when they walk over heightened ground. And sometimes they disappear on the screen, if you walk past them (you can only see it in the very first frame of the video, bc then I immediately started recording and they reappeared. I tried to reproduce it...seems kinda rare.).

**Current behaviour**: Gliding through hightened floor and sometimes disappearing on the screen.

**Expected behaviour**: Obv should walk on the floor and never disappear.

**Server Revision**: 2253

EDIT: Here is the disappearing: https://drive.google.com/file/d/1MaQXCw_umVy47M0bz0sxRYK-7J7CK5dh/view?usp=drivesdk

**Comment by Manaci** [comment]
Fixed
