### ISSUE TITLE
[NPC]Daggerfen Assassin#18116 should "attempts to run away in fear!"

### ISSUE THREAD

**Issue by Tenoutoften** [Atlantiss/NetherwingBugtracker#2293]
**Description**: 
[[NPC]Daggerfen Assassin#18116](https://www.wowhead.com/npc=18116/daggerfen-assassin) should "attempts to run away in fear!"
[source](https://youtu.be/pq7o_dti95w?t=159)

**Current behaviour**:
Doesn't

**Server Revision**: 
2253

**Comment by Evolvee** [comment]
rev YYY
