### ISSUE TITLE
[NPC]Daggerfen Muckdweller#18115 should "attempts to run away in fear!"

### ISSUE THREAD

**Issue by Tenoutoften** [Atlantiss/NetherwingBugtracker#2294]
**Description**: 
[[NPC]Daggerfen Muckdweller#18115](https://www.wowhead.com/npc=18115/daggerfen-muckdweller#objective-of) should "attempts to run away in fear!"
[source](https://youtu.be/pq7o_dti95w?t=159)

**Current behaviour**:
Doesn't

**Server Revision**: 
2253

**Comment by Evolvee** [comment]
rev YYY
