### ISSUE TITLE
[Quest] Bring Me The Egg!

### ISSUE THREAD

**Issue by BezawitNW** [Atlantiss/NetherwingBugtracker#2299]
I successfully picked up the egg and summoned the Windroc Matriarch. For whatever reason, I could not get my VW to aggro her and I died. I used Soulstone to res while the Matriarch flew up into the air. Once I was full hp/mana with minion back out, I engaged her again. However when I attacked her she did not aggro at all. I was able to kill her from 100% to 0 without her ever engaging me.

https://clips.twitch.tv/ShortColdWaffleGivePLZ

**Comment by Mikik3jr** [comment]
I confirm it. I died from the bird, and when I attacked it again it did not give a fuck about me.
![wowscrnshot_110818_142948](https://user-images.githubusercontent.com/43505031/48201678-1fd32980-e363-11e8-814e-74940d4b752a.jpg)
![Uploading WoWScrnShot_110818_143026.jpg…]()

**Comment by xmesaj2** [comment]
fix in rev 2080
