### ISSUE TITLE
Custom channels typing problem 

### ISSUE THREAD

**Issue by wtRCH** [Atlantiss/NetherwingBugtracker#230]
[//]: # (Enclose links to things related to the bug using http://wowhead.com or any other TBC database.)
[//]: # (You can use screenshot ingame to visual the issue.)
[//]: # (Write your tickets according to the format:)
[//]: # ([Quest][Azuremyst Isle] Red Snapper - Very Tasty!)
[//]: # ([NPC] Magistrix Erona)
[//]: # ([Spell][Mage] Fireball)
[//]: # ([Npc][Drop] Ghostclaw Lynx)
[//]: # ([Web] Armory doesnt work)

**Description**: After you join any custom channel fe. world you can't type in it unless you relog.

**Comment by danbopes** [comment]
#596
