### ISSUE TITLE
[NPC][Hellfire Peninsula] Bleeding Hollow Dark Shaman

### ISSUE THREAD

**Issue by eryczek1615** [Atlantiss/NetherwingBugtracker#2301]
**Description**: 
[NPC](https://db.excalibur.ws/?npc=16873#abilities) in Zeth'Gor

**Current behaviour**:
His [Totem](https://db.excalibur.ws/?spell=32062) hits for 700-900hp and his ability [Raise Soul](https://db.excalibur.ws/?spell=34013) doesn't work.

**Expected behaviour**: 
His totem should hit for 396-442 and when he'll use Riase Soul close to the corpse should summon [Hollow Bleeding Soul](https://db.excalibur.ws/?npc=19464) according to description of this ability

**Server Revision**: 
2253

**Comment by Easyfraggy** [comment]
![image](https://user-images.githubusercontent.com/36134067/48672019-c3c18f80-eb30-11e8-828b-33dbe91f1581.png)

![image](https://user-images.githubusercontent.com/36134067/48672030-d3d96f00-eb30-11e8-8cf9-ac5555142327.png)

**Comment by t4bbi** [comment]
Hey Easy,
I'm pretty sure the information on your pictures isn't correct. I did some more research and found some hints on wowhead.com to support my assumption. If you check the wowheads spell data for [Bleeding Hollow Necrolyte](https://www.wowhead.com/npc=19422/bleeding-hollow-necrolyte) you'll find [Raise Dead](https://www.wowhead.com/spell=34019/raise-dead) listed for that NPC. Raise Dead summons [Bleeding Hollow Skeletons](https://www.wowhead.com/npc=19460/bleeding-hollow-skeleton#comments), with its NPC site showing a picture with Necrolyte and Skeleton. Also the [comments](https://www.wowhead.com/npc=19422/bleeding-hollow-necrolyte#comments) from the TBC period to the NPCs and spells confirm these facts.

When checking [Bleeding Hollow Dark Shaman](https://www.wowhead.com/npc=16873/bleeding-hollow-dark-shaman) and his abilities on wowhead it didnt list Raise Dead or Shadowbolt. Again, the [comments](https://www.wowhead.com/npc=16873/bleeding-hollow-dark-shaman) support that NPC behaviour of not casting both of these spells. I also just checked on live servers myself and the shaman is only using melee attacks, his totem as well as bloodlust and lightning shield. 

I was writing dungeon, class and leveling guides for German WoW print media at that time and was really into these details back then. I really think my memory is not failing me here.

Cheers
tabbi

**Comment by Easyfraggy** [comment]
Bestiary isn't always complete it only shows spells they have on AI - so if they have a 1 time use spell or a triggered ability fx enrage at 30% it likely wont show on bestiary - I just posted for additional info.

**Comment by Tereneckla** [comment]
Damage of Shadowbolts and Fire Nova Totem was lowered.
Shamans still do Shadowbolts and a Raise Dead cast (which does nothing)

**Comment by devo6969** [comment]
I find a lot of conflicting information between sources and what I see in-game on retail. I can't find any video from back in the day of someone questing here. On Retail though, they do not cast either Raise Soul nor Shadowbolt but Wowhead says they do 🤷‍♂️ . Only thing I can find from back in the day is the comment.

Retail BFA - https://www.youtube.com/watch?v=2ip0OylCAdw
PTR - https://www.youtube.com/watch?v=48O5AfBtWfo

Both these sources say Dark Shamans have Raise Soul
https://wow.gamepedia.com/Bleeding_Hollow_Dark_Shaman#:~:text=Bleeding%20Hollow%20Dark%20Shaman%20are,be%20found%20in%20Hellfire%20Peninsula.
https://www.wowhead.com/spell=34013/raise-soul

https://www.wowhead.com/npc=16873/bleeding-hollow-dark-shaman#comments
lvl 60~61
Casts Lightning Shield, 3 Charges. 50% of inflicting 120 dmg on hit
Casts Bloodlust +30% attackspeed on self, after 15~20 seconds
attempts to run away in fear! <15% hp

**Comment by Godmatik** [comment]
I watched several classic videos and in none of them did I ever see them try and use a raise soul ability, so I believe this is intended.

Sounds like this was added to their spell list but Blizz never properly implemented them, we have seen this before with other mobs as well.

Closing
