### ISSUE TITLE
Mob instantly aggroes when rogue approaches while stealthed

### ISSUE THREAD

**Issue by Nicemann1089** [Atlantiss/NetherwingBugtracker#2302]
[//]: # (Enclose links to things related to the bug using http://wowhead.com or any other TBC database.)
[//]: # (You can use screenshot ingame to visual the issue.)
[//]: # (Write your tickets according to the format:)
[//]: # ([Quest][Azuremyst Isle] Red Snapper - Very Tasty!)
[//]: # ([NPC] Magistrix Erona)
[//]: # ([Spell][Mage] Fireball)
[//]: # ([Npc][Drop] Ghostclaw Lynx)
[//]: # ([Web] Armory doesnt work)

https://drive.google.com/file/d/1o7WMYhjXApjR4cMtYDy6GjVEG055bewJ/view?usp=drivesdk

https://drive.google.com/file/d/13P76FYHIVC7OF58h3gWGGag6HEZcXd4u/view?usp=drivesdk

**Description**: Mob instantly aggroes when you approach while stealthed, instead of first looking in your direction. I recorded it both with "Master of Deception 0/5" and "Master of Deception 5/5".

**Current behaviour**: Mob instantly aggroes when you approach while stealthed, instead of first looking in your direction.

**Expected behaviour**: Mob should first be curious and look in your direction. You should have a little buffer to know when the enemy is near aggroeing you.

**Server Revision**: 2253

**Comment by Nicemann1089** [comment]
Is it intended that the boars or all animals? don't show this warning feature? it is working for humanoids, I just checked.

**Comment by Peglaa** [comment]
Those boars have a huge aggro radius, similar to wolves so they might also have their stealth detection much bigger. Not sure how bugged this really is tho.

**Comment by AndrewNB41191** [comment]
seems fine in my experience.

**Comment by The14me** [comment]
Rechecked and work perfect now.
