### ISSUE TITLE
[NPC] Chief Engineer Lorthander

### ISSUE THREAD

**Issue by netherwingbta** [Atlantiss/NetherwingBugtracker#2303]
[//]: # (Enclose links to things related to the bug using http://wowhead.com or any other TBC database.)
[//]: # (You can use screenshot ingame to visual the issue.)
[//]: # (Write your tickets according to the format:)
[//]: # ([Quest][Azuremyst Isle] Red Snapper - Very Tasty!)
[//]: # ([NPC] Magistrix Erona)
[//]: # ([Spell][Mage] Fireball)
[//]: # ([Npc][Drop] Ghostclaw Lynx)
[//]: # ([Web] Armory doesnt work)

**Description**: 
Only used Slow and Arcane Unlocking on me, never his Arcane Bolts.
**Expected behaviour**: 
Has listed Arcane bolts as one of his abilities, so he should probably use it. 
https://www.wowhead.com/npc=18697/chief-engineer-lorthander#abilities
**Server Revision**: 
2253

**Comment by Evolvee** [comment]
rev YYY
