### ISSUE TITLE
[Netherstorm] The Violet Tower

### ISSUE THREAD

**Issue by netherwingbta** [Atlantiss/NetherwingBugtracker#2304]
[//]: # (Enclose links to things related to the bug using http://wowhead.com or any other TBC database.)
[//]: # (You can use screenshot ingame to visual the issue.)
[//]: # (Write your tickets according to the format:)
[//]: # ([Quest][Azuremyst Isle] Red Snapper - Very Tasty!)
[//]: # ([NPC] Magistrix Erona)
[//]: # ([Spell][Mage] Fireball)
[//]: # ([Npc][Drop] Ghostclaw Lynx)
[//]: # ([Web] Armory doesnt work)

**Description**: 
In the violet tower you are supposed to get a curse debuff that decreases damage dealt by 50%.
There's also some cool warp field visuals missing from the outside of the tower. Makes it look more like a prison.
**Current behaviour**:
No curse inside the tower.
![wow 2018-11-05 00-46-49-26](https://user-images.githubusercontent.com/43872263/47971725-59badc00-e094-11e8-9218-89ef8c85782b.jpg)
[Ar'kelos](https://www.wowhead.com/npc=19494/arkelos) inside the tower is also supposed to take double damage to even it out (lol)
**Expected behaviour**: 
https://www.wowhead.com/spell=34102/curse-of-the-violet-tower
![curse](https://user-images.githubusercontent.com/43872263/47971651-dbf6d080-e093-11e8-963e-d526cd73e549.jpg)
![prison](https://user-images.githubusercontent.com/43872263/47971718-43ad1b80-e094-11e8-93a1-ead435e4099b.jpg)

**Server Revision**: 
2253

**Comment by Evolvee** [comment]
its only if u are on a certain quest

**Comment by Evolvee** [comment]
https://github.com/Atlantiss/AtlantissTbcBTOLD/issues/551
![image](https://user-images.githubusercontent.com/1942409/47997329-bef5e800-e0fb-11e8-9a02-3ec5ac2abe4b.png)
https://github.com/Atlantiss/AtlantissTBCBT/issues/3138
![image](https://user-images.githubusercontent.com/1942409/47997361-da60f300-e0fb-11e8-8b99-bed148d9a00a.png)

**Comment by Evolvee** [comment]
rev cd
