### ISSUE TITLE
[Quest] Skywing

### ISSUE THREAD

**Issue by killablink** [Atlantiss/NetherwingBugtracker#2305]
**Description**:  After circling the 2nd tower or whatever, he's supposed to fly down to the platform under, but he is currently walking all the way back to the entrance and taking a long detour

**Current behaviour**: ^

**Expected behaviour**:  flies down to the platform

**Server Revision**: 2253

**Comment by ScottieDOESknow** [comment]
Same. Did this quest twice few days ago and was working as intended.

**Comment by killablink** [comment]
Yeah dunno but for me he just walked back to the first tree and walked up to the platform he's supposed to fly down to

**Comment by Easyfraggy** [comment]
Need a way to replicate it reliably if possible.

**Comment by Evolvee** [comment]
works fine for me, need video of this happening(or how to reproduce)

**Comment by mhdemn** [comment]
2256

Don't know how to reproduce the bug tbh, and I didn't expect any bug so I was rather late to click [record](https://youtu.be/WC16BDHfIuk).
This is the hidden chat in that moment, forgot I had the picture toggled on:
![bird escort emote](https://user-images.githubusercontent.com/25901582/48084481-22654000-e1f8-11e8-9771-591ccf8360d5.png)

The rest of the [quest](https://tbc-twinhead.twinstar.cz/?quest=10898) works fine, gets completed, [Skywing](https://tbc-twinhead.twinstar.cz/?npc=22424) morphs into an arakkoa and runs away as expected and all.

I'll hold on to the quest so I can abandon it and record the whole thing again if you guys don't see anything in the video that can give you a hint.

**Comment by aresbrutus** [comment]
Could you redo this and record the full encounter?

**Comment by Evolvee** [comment]
i didnt check the script yet, maybe there is some fault

**Comment by mhdemn** [comment]
Aight will do that asap, just waiting for help in-game

**Comment by mhdemn** [comment]
[Here](https://youtu.be/AZlh_Yed9iY)'s the full walk-through the quest. Bug happens at 02:43. The druid had it completed. 
Still holding on to the quest in case you ask me to run it again.

**Comment by Evolvee** [comment]
thx

**Comment by mhdemn** [comment]
you're very welcome

**Comment by Evolvee** [comment]
rev dsa
