### ISSUE TITLE
[Quest] Shutting Down Manaforge Duro

### ISSUE THREAD

**Issue by netherwingbta** [Atlantiss/NetherwingBugtracker#2306]
[//]: # (Enclose links to things related to the bug using http://wowhead.com or any other TBC database.)
[//]: # (You can use screenshot ingame to visual the issue.)
[//]: # (Write your tickets according to the format:)
[//]: # ([Quest][Azuremyst Isle] Red Snapper - Very Tasty!)
[//]: # ([NPC] Magistrix Erona)
[//]: # ([Spell][Mage] Fireball)
[//]: # ([Npc][Drop] Ghostclaw Lynx)
[//]: # ([Web] Armory doesnt work)

**Description**: 
https://www.wowhead.com/quest=10338/shutting-down-manaforge-duro
https://www.wowhead.com/quest=10322/shutting-down-manaforge-duro
Same as the others, no dialogue window to initiate the event. Missing the emotes in the chat, event starting, and 1 minute warning.
The mobs just run to their spot and don't do anything, no channeling to stop the shutdown.

**Current behaviour**:
You can just hide and get the event done without fighting any of them.
![wow 2018-11-05 00-24-28-52](https://user-images.githubusercontent.com/43872263/47971999-cdaab380-e097-11e8-89e4-1a41dc97e349.jpg)

**Expected behaviour**: 
![duro](https://user-images.githubusercontent.com/43872263/47972075-95f03b80-e098-11e8-8688-ce1979f20154.png)

https://www.youtube.com/watch?v=3LJK317Vrug
https://www.youtube.com/watch?v=95Xq_G0J6HU
**Server Revision**: 
2253

**Comment by Matija5** [comment]
Also if you are in party Only one gets completion

**Comment by Wolffenstein** [comment]
Fixed in rev 3104.
