### ISSUE TITLE
[Quest] Creatures of the Eco-Domes

### ISSUE THREAD

**Issue by netherwingbta** [Atlantiss/NetherwingBugtracker#2307]
[//]: # (Enclose links to things related to the bug using http://wowhead.com or any other TBC database.)
[//]: # (You can use screenshot ingame to visual the issue.)
[//]: # (Write your tickets according to the format:)
[//]: # ([Quest][Azuremyst Isle] Red Snapper - Very Tasty!)
[//]: # ([NPC] Magistrix Erona)
[//]: # ([Spell][Mage] Fireball)
[//]: # ([Npc][Drop] Ghostclaw Lynx)
[//]: # ([Web] Armory doesnt work)

**Description**: 
https://www.wowhead.com/quest=10427/creatures-of-the-eco-domes
When there are bleeds (probably magic dots as well) on the talbuk when you tag them you will get stuck in combat. You don't die if you alt+ f4 though.

**Expected behaviour**: 
Debuffs are supposed to be insta cleared from the talbuk when you use the item to tag them.
https://www.youtube.com/watch?v=49rz1YaKmXc&t=20
**Server Revision**: 
2255

**Comment by aresbrutus** [comment]
https://github.com/Atlantiss/AtlantissTBCBT/issues/3246

**Comment by xmesaj2** [comment]
Got a fix, will close this once I push the changes

**Comment by AxeCell** [comment]
When tagging a low health talbuk while standing close to an already tagged talbuk, you'll hit the sleeping talbuk with the Talbuk Tagger, while the other talbuk remains unaffected. These hits gives credit and counts towards the quest objective. Did this as a hunter with my pet tanking the talbuk.

**Comment by xmesaj2** [comment]
fix in rev 2080
