### ISSUE TITLE
[NPC] Markaru

### ISSUE THREAD

**Issue by netherwingbta** [Atlantiss/NetherwingBugtracker#2308]
[//]: # (Enclose links to things related to the bug using http://wowhead.com or any other TBC database.)
[//]: # (You can use screenshot ingame to visual the issue.)
[//]: # (Write your tickets according to the format:)
[//]: # ([Quest][Azuremyst Isle] Red Snapper - Very Tasty!)
[//]: # ([NPC] Magistrix Erona)
[//]: # ([Spell][Mage] Fireball)
[//]: # ([Npc][Drop] Ghostclaw Lynx)
[//]: # ([Web] Armory doesnt work)

**Description**: 

[Markaru](https://www.wowhead.com/npc=20775/markaru) spams Venom Spit regardless of if you are in melee range or not. Also summons tentacles at a fast rate. 
**Expected behaviour**: 

> Markaru is rooted in place in the middle of the lake. He also has a poison spit attack which he will use if he can't melee you.
> 
> However, the spit only has about a 30 yard range. If you have any ranged attacks which exceed this range (such as a Hunter's Auto Shot,) you can blast him from outside his attack range. Unlike pretty much every other mob I've ever seen (with the exception of Dr. Boom,) he won't evade bug if you do this.
> 
> So if you're lucky enough to be a Hunter, get just inside max range, turn on Auto Shot, and go have a coffee.
https://www.wowhead.com/npc=20775/markaru#comments:id=226788

Hard to really find anything on the tentacles since almost all the footage is of people 1 shotting him. 

https://www.youtube.com/watch?v=UQ9joFQ7uNo&t=15
https://www.youtube.com/watch?v=2TAX3Z4tBmo&t=23
**Server Revision**: 
2255

**Comment by Evolvee** [comment]
there is not rly said it shouldnt cast it if u arent in melee tho :/

**Comment by Evolvee** [comment]
and he is currently stationary, not moving already

**Comment by Evolvee** [comment]
i will close it for now, if u find some evidence of it, feel free to comment
