### ISSUE TITLE
[Pet] Pets struggle to board Zepplins/Boats

### ISSUE THREAD

**Issue by KevinTyrrell** [Atlantiss/NetherwingBugtracker#2309]
[//]: # (Enclose links to things related to the bug using http://wowhead.com or any other TBC database.)
[//]: # (You can use screenshot ingame to visual the issue.)
[//]: # (Write your tickets according to the format:)
[//]: # ([Quest][Azuremyst Isle] Red Snapper - Very Tasty!)
[//]: # ([NPC] Magistrix Erona)
[//]: # ([Spell][Mage] Fireball)
[//]: # ([Npc][Drop] Ghostclaw Lynx)
[//]: # ([Web] Armory doesnt work)

**Description**: 
[Twitch Clip](https://clips.twitch.tv/HomelyExcitedHareOSfrog)

**Current behaviour**:
Pets attempting to board boats/zepplings which are moving (not sure if this is the cause) have strange pathing.

**Expected behaviour**: 
Pets should be able to board boats/zepplings normally.

**Server Revision**: 
2255

**Comment by Fenvarien1** [comment]
Same issue as #2042
