### ISSUE TITLE
[Pet] Pet movement speed while owner is polymorphed is slow

### ISSUE THREAD

**Issue by KevinTyrrell** [Atlantiss/NetherwingBugtracker#2310]
[//]: # (Enclose links to things related to the bug using http://wowhead.com or any other TBC database.)
[//]: # (You can use screenshot ingame to visual the issue.)
[//]: # (Write your tickets according to the format:)
[//]: # ([Quest][Azuremyst Isle] Red Snapper - Very Tasty!)
[//]: # ([NPC] Magistrix Erona)
[//]: # ([Spell][Mage] Fireball)
[//]: # ([Npc][Drop] Ghostclaw Lynx)
[//]: # ([Web] Armory doesnt work)

**Description**: 
[Twitch Clip](https://clips.twitch.tv/GiantBashfulBatBloodTrail)

**Current behaviour**:
When the owner of the pet is polymorphed, the pet's default movement speed(?) or returning movement speed is that of the speed of the sheep'ed master.

**Expected behaviour**: 
The pet's movement should not be hindered by the afflictions of the master.

**Server Revision**: 
2255

**Comment by Wolffenstein** [comment]
Fixed in rev 2263.
