### ISSUE TITLE
[Pet] Pets fall through ground when summoned in Searing Gorge

### ISSUE THREAD

**Issue by KevinTyrrell** [Atlantiss/NetherwingBugtracker#2311]
[//]: # (Enclose links to things related to the bug using http://wowhead.com or any other TBC database.)
[//]: # (You can use screenshot ingame to visual the issue.)
[//]: # (Write your tickets according to the format:)
[//]: # ([Quest][Azuremyst Isle] Red Snapper - Very Tasty!)
[//]: # ([NPC] Magistrix Erona)
[//]: # ([Spell][Mage] Fireball)
[//]: # ([Npc][Drop] Ghostclaw Lynx)
[//]: # ([Web] Armory doesnt work)

**Description**: 
[Twitch Clip](https://clips.twitch.tv/SuperAmazonianDinosaurHeyGirl)

[Another example](https://clips.twitch.tv/FantasticPluckyBatteryAMPEnergyCherry) which happened a few minutes later.

**Current behaviour**:
Sometimes when summoning pets in sections of searing gorge, they appear to spawn accidentally on the lower levels.

**Expected behaviour**: 
Pets should be summoned on the same Z level as the master.

**Server Revision**: 
2255

**Comment by KevinTyrrell** [comment]
Another example of summoning & falling through terrain: https://clips.twitch.tv/SmoothStormyWasabiFloof

Summoning into a tree: #2314

**Comment by mhdemn** [comment]
Happens also in [this spot in front of Karazhan](https://youtu.be/hDwgYaYbzKY) (Deadwind Pass, around 47.0,75.5)

**Comment by KredesX** [comment]
yep! happens all the time, quite annoying.

**Comment by Manaci** [comment]
Fixed
