### ISSUE TITLE
[Core][Spell][Mage] Frostbolt rank 1 vs higher rank (other spells too)

### ISSUE THREAD

**Issue by killablink** [Atlantiss/NetherwingBugtracker#2312]
**Description**:  If you hit a mob with a high rank frostbolt and then try to frostbolt with a rank 1 or lower rank, it will say a more powerful spell is actually active just before the cast ends

**Current behaviour**: If you hit a mob with a high rank frostbolt and then try to frostbolt with a rank 1 or lower rank, it will say a more powerful spell is actually active just before the cast ends

**Expected behaviour**: Should be able to cast frostbolt. This problem happens with fireball too. I imagine any spell that leaves a debuff has this problem.

**Server Revision**: 2253

**Comment by ircfelix** [comment]
Still happening. It's the slow effect and the dot component of both spells.

**Comment by Easyfraggy** [comment]
Theres a dot from frostbolt? 🤔

**Comment by The14me** [comment]
Retested and work perfect now.
