### ISSUE TITLE
[Quest] Shutting Down Manaforge Ara

### ISSUE THREAD

**Issue by netherwingbta** [Atlantiss/NetherwingBugtracker#2313]
[//]: # (Enclose links to things related to the bug using http://wowhead.com or any other TBC database.)
[//]: # (You can use screenshot ingame to visual the issue.)
[//]: # (Write your tickets according to the format:)
[//]: # ([Quest][Azuremyst Isle] Red Snapper - Very Tasty!)
[//]: # ([NPC] Magistrix Erona)
[//]: # ([Spell][Mage] Fireball)
[//]: # ([Npc][Drop] Ghostclaw Lynx)
[//]: # ([Web] Armory doesnt work)

**Description**: 
https://www.wowhead.com/quest=10323/shutting-down-manaforge-ara
https://www.wowhead.com/quest=10365/shutting-down-manaforge-ara
Same as the others, no dialogue window to initiate the event. Missing the emotes in the chat, event starting, and 1 minute warning.
The mobs just run to their spot and don't do anything, no channeling to stop the shutdown.
**Current behaviour**:
https://gfycat.com/HotNegativeBeardedcollie
**Expected behaviour**: 
The technicians are supposed to stop the shut down.
https://www.youtube.com/watch?v=ct7gfJZbLDk
![aratech](https://user-images.githubusercontent.com/43872263/47977406-20946300-e0b8-11e8-93f9-3959a5556331.jpg)
![aracontrol](https://user-images.githubusercontent.com/43872263/47977436-4883c680-e0b8-11e8-93c0-ce43fefbec97.jpg)

**Server Revision**: 
2255

**Comment by Matija5** [comment]
Also if you are in party Only one gets completion

**Comment by Kidcudi123** [comment]
bump

**Comment by Johra92** [comment]
This is still an issue, not getting credit for more than one person in group. Same issue as described above

**Comment by rychersky** [comment]
Still only granting credit for one person at a time.

revision 2749

**Comment by Wolffenstein** [comment]
Fixed in rev 3104.
