### ISSUE TITLE
[Pet] Summoned inside of tree

### ISSUE THREAD

**Issue by KevinTyrrell** [Atlantiss/NetherwingBugtracker#2314]
[//]: # (Enclose links to things related to the bug using http://wowhead.com or any other TBC database.)
[//]: # (You can use screenshot ingame to visual the issue.)
[//]: # (Write your tickets according to the format:)
[//]: # ([Quest][Azuremyst Isle] Red Snapper - Very Tasty!)
[//]: # ([NPC] Magistrix Erona)
[//]: # ([Spell][Mage] Fireball)
[//]: # ([Npc][Drop] Ghostclaw Lynx)
[//]: # ([Web] Armory doesnt work)

**Description**: 
[Twitch Clip](https://clips.twitch.tv/AffluentSuspiciousTigerFunRun)

This may have something to do with #2311 

**Expected behaviour**: 
Pet should summon ontop of the owner if the area next to the hunter would collide with terrain. (need source on this)

**Server Revision**: 
2255

**Comment by Manaci** [comment]
Fixed
