### ISSUE TITLE
[NPC] [Nagrand] Vir'anni Raider - weapon floating after death & sound bug?

### ISSUE THREAD

**Issue by ScottieDOESknow** [Atlantiss/NetherwingBugtracker#2315]
**Description**:  Vir'anni Raider @ Oshu'gun

**Current behaviour**: 

1. when this NPC dies their weapon remains floating in mid air

https://gyazo.com/1fc9bcb6551b577d0765306aac287457

2. they occasionally seem to make a sound of Elekk? I'm unsure whether if this is intended or just an improper sound file attributed to this NPC

**Expected behaviour**: weapon should settle on the ground after death

**Server Revision**: 2255

**Comment by Evolvee** [comment]
rev YYY
