### ISSUE TITLE
[Pet] Pet standing mid-air

### ISSUE THREAD

**Issue by KevinTyrrell** [Atlantiss/NetherwingBugtracker#2316]
[//]: # (Enclose links to things related to the bug using http://wowhead.com or any other TBC database.)
[//]: # (You can use screenshot ingame to visual the issue.)
[//]: # (Write your tickets according to the format:)
[//]: # ([Quest][Azuremyst Isle] Red Snapper - Very Tasty!)
[//]: # ([NPC] Magistrix Erona)
[//]: # ([Spell][Mage] Fireball)
[//]: # ([Npc][Drop] Ghostclaw Lynx)
[//]: # ([Web] Armory doesnt work)

**Description**: 
[Twitch Clip](https://clips.twitch.tv/DarkGentleLemurDogFace)

**Current behaviour**:
Pet stands mid-air while trying to stand next to master.

**Expected behaviour**: 
If the area next to the hunter is not valid, the pet should stand onto of the master

**Server Revision**: 
2255

**Comment by Easyfraggy** [comment]
Flying doggo <3

**Comment by Manaci** [comment]
Fixed
