### ISSUE TITLE
[Quest] Fall From Grace

### ISSUE THREAD

**Issue by KevinTyrrell** [Atlantiss/NetherwingBugtracker#2318]
[//]: # (Enclose links to things related to the bug using http://wowhead.com or any other TBC database.)
[//]: # (You can use screenshot ingame to visual the issue.)
[//]: # (Write your tickets according to the format:)
[//]: # ([Quest][Azuremyst Isle] Red Snapper - Very Tasty!)
[//]: # ([NPC] Magistrix Erona)
[//]: # ([Spell][Mage] Fireball)
[//]: # ([Npc][Drop] Ghostclaw Lynx)
[//]: # ([Web] Armory doesnt work)

**Description**: 
[Twitch Clip](https://clips.twitch.tv/NaiveNeighborlyBasenjiSSSsss)

**Current behaviour**:
The last dialogue option "Tragic..." does not close the dialogue window. Nothing happens when the option is chosen.

**Expected behaviour**: 
The last dialogue option "Tragic..." should close the dialogue window.

**Server Revision**: 
2255

**Comment by Evolvee** [comment]
rev YYY
