### ISSUE TITLE
Stable Master (Possibly client-side)

### ISSUE THREAD

**Issue by KevinTyrrell** [Atlantiss/NetherwingBugtracker#2319]
[//]: # (Enclose links to things related to the bug using http://wowhead.com or any other TBC database.)
[//]: # (You can use screenshot ingame to visual the issue.)
[//]: # (Write your tickets according to the format:)
[//]: # ([Quest][Azuremyst Isle] Red Snapper - Very Tasty!)
[//]: # ([NPC] Magistrix Erona)
[//]: # ([Spell][Mage] Fireball)
[//]: # ([Npc][Drop] Ghostclaw Lynx)
[//]: # ([Web] Armory doesnt work)

**Description**:
[Twitch Clip](https://clips.twitch.tv/WealthyEsteemedCamelRitzMitz)

**Current behaviour**:
If you call / revive a pet after having already had the stable master window open, the stable master will not allow you to stable that pet until you close the window and re-open it again.

**Expected behaviour**: 
The stable master should allow you to stable your pet even when calling it after opening the window.

**Server Revision**: 
2255

**Comment by Wolffenstein** [comment]
Not a bug.
