### ISSUE TITLE
[NPC]Unstable Shroom#20479 has too much health, should have ~300 health.

### ISSUE THREAD

**Issue by Tenoutoften** [Atlantiss/NetherwingBugtracker#2321]
**Description**: 
[[NPC]Unstable Shroom#20479](https://www.wowhead.com/npc=20479/unstable-shroom) has way too much health on [NW](https://www.youtube.com/watch?v=SNSLlzyEAxw&feature=youtu.be) - 8200 health. Should only have about 300 health. Wowhead lists it at [198 health](https://www.wowhead.com/npc=20479/unstable-shroom), excalibur at [296 health](https://db.excalibur.ws/?npc=20479#summoned-by-spell)
![4291ffbb4cf79f34384665abd228e98f](https://user-images.githubusercontent.com/34839199/47988043-70d3eb00-e0e1-11e8-9c85-fa35a55f2431.png)

It is spawned by [[Spell]Unstable Mushroom Primer#35273](https://www.wowhead.com/spell=35273/unstable-mushroom-primer) triggering [[Spell]Summon Unstable Mushroom#35256](https://db.excalibur.ws/?spell=35256)

**Expected behaviour**: 
Expected to have roughly 300 health.

**Server Revision**: 
2253

**Comment by Evolvee** [comment]
rev dsa
