### ISSUE TITLE
[Misc][NPC]Unstable Shroom#20479 should grow into full size, rather than spawn at full size

### ISSUE THREAD

**Issue by Tenoutoften** [Atlantiss/NetherwingBugtracker#2323]
**Description**: 
[[NPC]Unstable Shroom#20479](https://www.wowhead.com/npc=20479/unstable-shroom) should use [[Spell]Grow#31698](https://db.excalibur.ws/?spell=31698) to grow into full size as it launches it's offensive spell [[Spell]Unstable Cloud#35252](https://db.excalibur.ws/?spell=35252). On [NW](https://youtu.be/Y2-nkMHGkYg?t=3) it spawns full size

![6bd03f9cb0ae3b0f705a6b3cd8506a80](https://user-images.githubusercontent.com/34839199/47988190-df18ad80-e0e1-11e8-8bc8-dd16c779e59a.png)

**Expected behaviour**: 
Expected to grow into full size as it's cast is completed

**Server Revision**: 
2253

**Comment by Tenoutoften** [comment]
Used by:
[[NPC]Bog Lord#18127](https://www.wowhead.com/npc=18127/bog-lord)
[[NPC]Fungal Giant#19734](https://www.wowhead.com/npc=19734/fungal-giant)

**Comment by Evolvee** [comment]
i swear it was working pre-beta PepeHands
its my script after all xd

**Comment by Evolvee** [comment]
@Wolffenstein "set scale" sai action doesnt work 😢

**Comment by Tenoutoften** [comment]
:/

**Comment by Evolvee** [comment]
rev DDF
