### ISSUE TITLE
[NPC] [Blade's Edge] Living Grove Defender

### ISSUE THREAD

**Issue by ScottieDOESknow** [Atlantiss/NetherwingBugtracker#2324]
**Description**: Living Grove Defender is an NPC spawned during quest 'Protecting Our Own'

**Current behaviour**: NPC is spawned neutral and attackable (as intended) but when killed, grants XP

https://gyazo.com/80c9786b4f30734ae9b649276650d089

**Expected behaviour**: NPC should not grant XP

https://gyazo.com/0ce178720f2bab0828dc96bb77994567

**Server Revision**: 2255

**Comment by Evolvee** [comment]
rev YYY
