### ISSUE TITLE
[Movement][NPC]Fenclaw Thrasher#18214 ID 2 occasionally stuck in a rock.

### ISSUE THREAD

**Issue by Tenoutoften** [Atlantiss/NetherwingBugtracker#2325]
**Description**: 
[[NPC]Fenclaw Thrasher#18214](https://www.wowhead.com/npc=18214/fenclaw-thrasher), ID 2 occasionally stuck in a rock. It broke loose the second time I pulled it, but evaded on the first time.
https://www.youtube.com/watch?v=4Qlhi8xFWK4&feature=youtu.be

**Expected behaviour**: 
Probably place this one slightly different. 

**Server Revision**: 
2253

**Comment by Easyfraggy** [comment]
Fixed in rev biosphere
