### ISSUE TITLE
[NPC][Drop] Mazzranache

### ISSUE THREAD

**Issue by totaemoeggerli** [Atlantiss/NetherwingBugtracker#2326]
[//]: # (Enclose links to things related to the bug using http://wowhead.com or any other TBC database.)
[//]: # (You can use screenshot ingame to visual the issue.)
[//]: # (Write your tickets according to the format:)
[//]: # ([Quest][Azuremyst Isle] Red Snapper - Very Tasty!)
[//]: # ([NPC] Magistrix Erona)
[//]: # ([Spell][Mage] Fireball)
[//]: # ([Npc][Drop] Ghostclaw Lynx)
[//]: # ([Web] Armory doesnt work)

**Description**: 
[Mazzranache](https://de.wowhead.com/npc=3068/mazzranache) drops [Tender Strider Meat](https://www.wowhead.com/item=33009/tender-strider-meat) although [Kyle's Gone Missing!](https://www.wowhead.com/quest=11129/kyles-gone-missing) has been completed.

**Current behaviour**:
Quest item drops after quest has been completed.

**Expected behaviour**: 
Quest item shouldn't drop after quest has been completed.

**Server Revision**: 2255

**Comment by Evolvee** [comment]
rev YYY
