### ISSUE TITLE
[NPC]Seeping Sludge Globule / Void Waste Globule

### ISSUE THREAD

**Issue by kingzzNW** [Atlantiss/NetherwingBugtracker#2327]
[//]: # (Enclose links to things related to the bug using http://wowhead.com or any other TBC database.)
[//]: # (You can use screenshot ingame to visual the issue.)
[//]: # (Write your tickets according to the format:)
[//]: # ([Quest][Azuremyst Isle] Red Snapper - Very Tasty!)
[//]: # ([NPC] Magistrix Erona)
[//]: # ([Spell][Mage] Fireball)
[//]: # ([Npc][Drop] Ghostclaw Lynx)
[//]: # ([Web] Armory doesnt work)

**Description**: These mobs are part of the Quest [Electro-Shock Goodness!](https://www.wowhead.com/quest=10411/electro-shock-goodness) in Netherstorm. Upon attacking and under the effect of the provided elixir [Navuud's Concoction](https://www.wowhead.com/item=29737/navuuds-concoction) mobs named [Seeping Sludge](https://www.wowhead.com/npc=20501/seeping-sludge) and [Void Waste](https://www.wowhead.com/npc=20778/void-waste) accordingly split into ~10 low HP [Seeping Sludge Globule](https://www.wowhead.com/npc=20806/seeping-sludge-globule) or [Void Waste Globule
](https://www.wowhead.com/npc=20805/void-waste-globule) which however each grant full XP of a regular mob resulting in ~4-5k xp overall.

**Current behaviour**: Mobs grant full XP

**Expected behaviour**: I couldnt find the proper values or if these mobs should grant XP at all, however this seems fairly abusable

**Server Revision**: 2255

**Comment by xmesaj2** [comment]
fix in rev 2080
