### ISSUE TITLE
Lake Vents in Barrens

### ISSUE THREAD

**Issue by Tinnoan** [Atlantiss/NetherwingBugtracker#233]
Lake vents in the barrens don't seem to be giving out any breath.

![lake_vent](https://user-images.githubusercontent.com/25431721/45930393-ecc60980-bf5f-11e8-8a04-3aa577c8daca.png)

**Comment by The14me** [comment]
Confirm for this one.Others work fine to me.

**Comment by Tereneckla** [comment]
Only the one in Lushwater Oasis works.
Stagnant Oasis, Forgotten Pools and Sludge Fen don't work.

**Comment by The14me** [comment]
Still bugged in rev.3441

**Comment by Wolffenstein** [comment]
Fixed in rev 3451.
