### ISSUE TITLE
[NPC][Loot] Diemetradon Empty Loot

### ISSUE THREAD

**Issue by KevinTyrrell** [Atlantiss/NetherwingBugtracker#2330]
[//]: # (Enclose links to things related to the bug using http://wowhead.com or any other TBC database.)
[//]: # (You can use screenshot ingame to visual the issue.)
[//]: # (Write your tickets according to the format:)
[//]: # ([Quest][Azuremyst Isle] Red Snapper - Very Tasty!)
[//]: # ([NPC] Magistrix Erona)
[//]: # ([Spell][Mage] Fireball)
[//]: # ([Npc][Drop] Ghostclaw Lynx)
[//]: # ([Web] Armory doesnt work)

**Description**: 
[Twitch Clip](https://clips.twitch.tv/HilariousPreciousDaikonMingLee)

[Another example nearby](https://clips.twitch.tv/NastyInspiringBearOptimizePrime)

NPC Info: Entry: 9163, Id: 33, GUIDLow: 213319

Shift looted all four items successfully into my bags. However it still appears he is lootable.

**Server Revision**: 
2255

**Comment by Easyfraggy** [comment]
https://github.com/Atlantiss/NetherwingBugtracker/issues/1054
