### ISSUE TITLE
[NPC] Scorpid Hunter Unable To Move

### ISSUE THREAD

**Issue by KevinTyrrell** [Atlantiss/NetherwingBugtracker#2332]
[//]: # (Enclose links to things related to the bug using http://wowhead.com or any other TBC database.)
[//]: # (You can use screenshot ingame to visual the issue.)
[//]: # (Write your tickets according to the format:)
[//]: # ([Quest][Azuremyst Isle] Red Snapper - Very Tasty!)
[//]: # ([NPC] Magistrix Erona)
[//]: # ([Spell][Mage] Fireball)
[//]: # ([Npc][Drop] Ghostclaw Lynx)
[//]: # ([Web] Armory doesnt work)

**Description**: 
[Twitch Clip](https://clips.twitch.tv/ExuberantEnergeticRedpandaPeteZarollTie)

I'm not sure how to reproduce this, but I got a Scorpid to low HP, then sent my pet on other mobs while the low HP Scorpid chased. Surprisingly, he casted his ability like he usually did and then just stopped moving all together. Very strange.

**Server Revision**: 
2255

**Comment by Tereneckla** [comment]
Fixed
