### ISSUE TITLE
[Spell] [NPC] [Blade's Edge] Bloodmaul Buzz - Bloodmaul Ogres (any)

### ISSUE THREAD

**Issue by ScottieDOESknow** [Atlantiss/NetherwingBugtracker#2333]
**Description**: Bloodmaul Ogres cast Bloodmaul Buzz which increases max HP by 20%

**Current behaviour**: NPC will heal to full from this buff after it expires.

**Expected behaviour**: buff should only add 20% max HP (like last stand)

**Server Revision**: 2255

**Comment by The14me** [comment]
https://github.com/Atlantiss/AtlantissTBCBT/issues/909

**Comment by Mewmewww** [comment]
high priority please, its almost impossible for a warrior to kill these before they get to heal unless we can get crits.

**Comment by ScottieDOESknow** [comment]
same issue

https://github.com/Atlantiss/NetherwingBugtracker/issues/2211

**Comment by chinupf** [comment]
Issue is still present, mobs regain full health after buff expires.

**Comment by Tereneckla** [comment]
Duplicate of #2211
