### ISSUE TITLE
[NPC] Infernal Warbringer [Entry: 19261]

### ISSUE THREAD

**Issue by Eidous** [Atlantiss/NetherwingBugtracker#2334]
[//]: # (Enclose links to things related to the bug using http://wowhead.com or any other TBC database.)
[//]: # (You can use screenshot ingame to visual the issue.)
[//]: # (Write your tickets according to the format:)
[//]: # ([Quest][Azuremyst Isle] Red Snapper - Very Tasty!)
[//]: # ([NPC] Magistrix Erona)
[//]: # ([Spell][Mage] Fireball)
[//]: # ([Npc][Drop] Ghostclaw Lynx)
[//]: # ([Web] Armory doesnt work)

**Description**: 
The immolation aura currently ticks multiple time per second, making it impossible for melee characters to fight these mobs

**Current behaviour**:

**Expected behaviour**: 

**Server Revision**: 
2255

**Comment by Eidous** [comment]
it seems to have fixed itself, it's not happening to me anymore either, guess i'll reopen if it happens again

**Comment by The14me** [comment]
It happen again,but not every time.That's why ill reopen.

**Comment by Piledriversn** [comment]
![image](https://user-images.githubusercontent.com/43560552/48053322-5281f400-e1a2-11e8-8aae-6c81df7af801.png)
It seems to happen sometimes and sometimes it doesn't. But if it happens again ill get something better than this screenshot.

**Comment by Evolvee** [comment]
general problem with passive auras procing too often than they are supposed to

@Wolffenstein you fix didnt fix it obviously

**Comment by Dullone** [comment]
I encounter this same bug just now.  After playing around with the Infernal for a little while this bug feels like multiple immolation auras.  Not all infernals have this issue and some seem to have a faster tick than others further, the damage seems to come in clusters of ticks.  So 2-4 ticks every period of time for different infernals, it was difficult to tell for certain as stay in too long resulted in death.

![wowscrnshot_120118_123059](https://user-images.githubusercontent.com/12240493/49331596-62081900-f565-11e8-928f-d0a2b7b36934.jpg)

**Comment by Gniddikon** [comment]
Can confirm, still bugged.

**Comment by Valywave** [comment]
Same bug for me.

![infernalbug](https://user-images.githubusercontent.com/38636491/49721456-85684d80-fc62-11e8-93d5-e7f3b38698ed.png)

**Comment by Wolffenstein** [comment]
Fixed in rev 2422.
