### ISSUE TITLE
[Quest] [Blade's Edge] What Came First, the Drake or the Egg? hp visual bug

### ISSUE THREAD

**Issue by ScottieDOESknow** [Atlantiss/NetherwingBugtracker#2335]
**Description**: after opening nether drake egg, using temporal phase modulator changes npc

**Current behaviour**: Occasionally, when NPC is changed, it will show low HP (only visual)

spawning with 2% HP
https://gyazo.com/60e247f9265c966702a3cf580142c7d7

**Expected behaviour**: NPC should spawn showing max HP 

https://gyazo.com/5b1bca820c4c74dcd5b437246ffc4f91

**Server Revision**:  2255

**Comment by ScottieDOESknow** [comment]
Smaily can confirm NPC had max HP after changed. 
Other group members were having same visual bug as myself.

**Comment by Mewmewww** [comment]
Just a comment on this. It's actually showing the mobs health in percentage (without showing it in percentage) so when it says 100, its 100% hp
