### ISSUE TITLE
[Zone] [Blade's Edge] random swirly floating in air

### ISSUE THREAD

**Issue by ScottieDOESknow** [Atlantiss/NetherwingBugtracker#2336]
**Description**: Blade's Edge Mountains @ 60.0, 71.5 in Singing ridge

**Current behaviour**: swirly floating in mid air. looks like stun animation

https://gyazo.com/81ce5ffd6f4859a1f266971a2a673a33

**Expected behaviour**: seems like it shouldn't be there

**Server Revision**: 2255

**Comment by Evolvee** [comment]
yea its a trigger and idk what its used for

its there even on retail sniffs

**Comment by ScottieDOESknow** [comment]
Looks like there is another swirly a bit north. They seem to line up with the border between Razor's Ridge and Razor Ridge where the color transitions from beige to purple.

**Comment by Evolvee** [comment]
their name is 
![image](https://user-images.githubusercontent.com/1942409/48030298-e75c0180-e150-11e8-8635-5c924941b794.png)

i think it has to do something with some RP event around that area :D

**Comment by Evolvee** [comment]
disabled until we find out what its used for
