### ISSUE TITLE
[Pet] Pet permanently stuck on 'Stay' mode

### ISSUE THREAD

**Issue by KevinTyrrell** [Atlantiss/NetherwingBugtracker#2338]
[//]: # (Enclose links to things related to the bug using http://wowhead.com or any other TBC database.)
[//]: # (You can use screenshot ingame to visual the issue.)
[//]: # (Write your tickets according to the format:)
[//]: # ([Quest][Azuremyst Isle] Red Snapper - Very Tasty!)
[//]: # ([NPC] Magistrix Erona)
[//]: # ([Spell][Mage] Fireball)
[//]: # ([Npc][Drop] Ghostclaw Lynx)
[//]: # ([Web] Armory doesnt work)

**Description**: 
[Twitch Clip](https://clips.twitch.tv/ShinySquareSpiderTriHard)

I set my pet on stay, Then I auto shot a Freezing Trapped target and at the same time I spam 'pet attack'. The pet refuses to attack the freezing trap (blizzlike? not sure) but does when auto shot breaks it. I press 'pet follow' and then immediately do 'pet attack' since follow caused the pet to return to me. 

Somehow doing the above, I put my pet in a bugged state where he believes he is still in 'stay' position, but displays as 'follow'. At that point, he can no longer properly follow me. If I press 'follow mode', he will simply come to my current position but will internally remain on 'stay'.

Here's a follow up clip of what I mean.

[Twitch Clip](https://clips.twitch.tv/IntelligentAmericanKangarooNononoCat)

**Server Revision**: 
2255

**Comment by scarabadookie** [comment]
Appears to be the same issue as [#620](https://github.com/Atlantiss/NetherwingBugtracker/issues/620) @Easyfraggy
