### ISSUE TITLE
[NPC][Spell] Wrathscale Sorceress

### ISSUE THREAD

**Issue by Sinyr** [Atlantiss/NetherwingBugtracker#234]
[//]: # (Enclose links to things related to the bug using http://wowhead.com or any other TBC database.)
[//]: # (You can use screenshot ingame to visual the issue.)
[//]: # (Write your tickets according to the format:)
[//]: # ([Quest][Azuremyst Isle] Red Snapper - Very Tasty!)
[//]: # ([NPC] Magistrix Erona)
[//]: # ([Spell][Mage] Fireball)
[//]: # ([Npc][Drop] Ghostclaw Lynx)
[//]: # ([Web] Armory doesnt work)

**Description**: 
NPC ID: 17336

**Current behaviour**:
Cast bar under nameplate shows up when NPC starts casting Frostbolt, but it's stuck at empty state, and stays visible even after the NPC finishes casting it, until it dies. One time only it disappeared when NPC started running away in fear, but in every other case it stayed there until death. Also, one time it randomly increased to like 5% halfway through the cast and stayed there.

![sorc](https://user-images.githubusercontent.com/9539181/45930365-79bc9300-bf5f-11e8-9a37-91d53d73ab19.png)

Note: This is actually the only monster so far that I've seen that had a cast bar, so it's possible that this is the case with some other monsters and/or spells as well.

**Expected behaviour**: 
Cast bar should fill up and then disappear.

**Server Revision**: 
2028

**Comment by Evolvee** [comment]
this is a client bug (most probably)

https://github.com/ccshiro/cc-buglist/issues/686
https://github.com/ccshiro/cc-buglist/issues/1706
https://github.com/ccshiro/cc-buglist/issues/1098
https://github.com/ccshiro/cc-buglist/issues/1131
