### ISSUE TITLE
[Megathread] Mind Control

### ISSUE THREAD

**Issue by KevinTyrrell** [Atlantiss/NetherwingBugtracker#2340]
[//]: # (Enclose links to things related to the bug using http://wowhead.com or any other TBC database.)
[//]: # (You can use screenshot ingame to visual the issue.)
[//]: # (Write your tickets according to the format:)
[//]: # ([Quest][Azuremyst Isle] Red Snapper - Very Tasty!)
[//]: # ([NPC] Magistrix Erona)
[//]: # ([Spell][Mage] Fireball)
[//]: # ([Npc][Drop] Ghostclaw Lynx)
[//]: # ([Web] Armory doesnt work)

**Description**: 
[Twitch Clip](https://clips.twitch.tv/StormyPopularGarlicPeteZaroll)
[Youtube Video](https://www.youtube.com/watch?v=qsOP8tvsmus&feature=youtu.be)
Mind control teleports target to the caster, teleports them away a frame later. If the mind control breaks on that frame then the player is literally teleported to the caster.

[Twitch Clip](https://clips.twitch.tv/CogentPlayfulCrabBCouch)
When mind control abruptly ends, the caster does a 'failed jump' animation.

[Twitch Clip](https://clips.twitch.tv/NurturingDepressedKeyboardPlanking)
The caster can also be the one who is teleported to the target. I'm not sure how to reproduce each case though.

[Twitch Clip](https://clips.twitch.tv/AmazonianNurturingBubbleteaAMPTropPunch)
Normally a priest cannot mind control a member of the same faction. If the same-faction target is mind controlled, he still cannot mind control the target because "Target is Charmed". This is correct and blizzlike. However if the same-faction priest spams Mind Control right as Mind Control on the target ends, then the priest will mind control a member of his own faction. This likely happens because the incoming Mind Control hits right as 'charmed' is removed from the target but right before the target is turned back into allied (no longer attack-able by same-faction).

[Twitch Clip](https://clips.twitch.tv/AntsyGlutenFreeCroissantTheTarFu)
[Screenshot](https://i.imgur.com/h5uLcn5.jpg)
[Youtube Video](https://www.youtube.com/watch?v=O7kwIb5V-TA&feature=youtu.be)
If a target is mind controlled, and walked through an instance portal, the mind controlled target is still considered 'charmed' and has the debuff on him. Additionally, the caster is still considered to be controlling the target (even though he is not) and thus does not have his action bar and cannot move (shown in screenshot). In one case, when the mind control ended, the target was teleported into the voice and was infinitely moving.

[Twitch Clip](https://clips.twitch.tv/FastDifficultDelicataSuperVinlin)
Mind control completing at the same time as the target vanishes cancels out the vanish and leaves the rogue out of stealth. The rogue should be in stealth after this interaction.

[Twitch Clip](https://clips.twitch.tv/YawningHyperBeanBrainSlug)
Tapping mind control rapidly allows you to recast it without finishing the prior cast.

**Server Revision**: 
2255

**Comment by Kidcudi123** [comment]
When you Mind Control elites in dungeons - you can spam their abilities with no cooldown and kill stuff super fast and easy

**Comment by Easyfraggy** [comment]
https://github.com/Atlantiss/NetherwingBugtracker/issues/787

**Comment by Brasso** [comment]
#2056

**Comment by Wolffenstein** [comment]
Fixed in rev 2262 (outside of Stealth which is intended).
