### ISSUE TITLE
[Misc][NPC]Bogstrok Crusher#20295 should "attempts to run away in fear!"

### ISSUE THREAD

**Issue by Tenoutoften** [Atlantiss/NetherwingBugtracker#2341]
**Description**: 
[[NPC]Bogstrok Crusher#20295](https://www.wowhead.com/npc=20295/bogstrok-crusher#abilities) should "attempts to run away in fear!"

Can be seen [here](https://youtu.be/pd9IJMkwBs0?t=57)

**Current behaviour**:
Doesn't

**Expected behaviour**: 
Should "attempts to run away in fear!"

**Server Revision**: 
2255

**Comment by Evolvee** [comment]
rev YYY
