### ISSUE TITLE
[NPC]Ango'Rosh Shaman#18118's [Spell]Healing Touch#23381 is way too weak

### ISSUE THREAD

**Issue by Tenoutoften** [Atlantiss/NetherwingBugtracker#2342]
**Description**: 
[[NPC]Ango'Rosh Shaman#18118](https://www.wowhead.com/npc=18118/angorosh-shaman#abilities)'s 
[[Spell]Healing Touch#23381](https://www.wowhead.com/spell=23381/healing-touch) is incredibly weak:
![56ab18e1df6814ef085927b0a45fe785](https://user-images.githubusercontent.com/34839199/48012574-9a613680-e122-11e8-8da3-4cb8796197f2.png)

**Expected behaviour**: 
Should probably heal significantly more

**Server Revision**: 
2255

**Comment by Evolvee** [comment]
rev YYY
