### ISSUE TITLE
[Spell] Ritual of Summoning Party Channel Does Not End When Portal Disappears

### ISSUE THREAD

**Issue by KevinTyrrell** [Atlantiss/NetherwingBugtracker#2344]
[//]: # (Enclose links to things related to the bug using http://wowhead.com or any other TBC database.)
[//]: # (You can use screenshot ingame to visual the issue.)
[//]: # (Write your tickets according to the format:)
[//]: # ([Quest][Azuremyst Isle] Red Snapper - Very Tasty!)
[//]: # ([NPC] Magistrix Erona)
[//]: # ([Spell][Mage] Fireball)
[//]: # ([Npc][Drop] Ghostclaw Lynx)
[//]: # ([Web] Armory doesnt work)

**Description**: 
[Twitch Clip](https://clips.twitch.tv/AthleticSmoggyStarOSkomodo)

**Current behaviour**:
The channel of someone clicking on a summoning portal is not canceled when the portal vanishes.

**Expected behaviour**: 
The channel of someone clicking on a summoning portal should be canceled when the portal vanishes.

**Server Revision**: 
2255

**Comment by Manaci** [comment]
Fixed
