### ISSUE TITLE
[Spell] Ritual of Summoning Ends Too Quickly Upon Success

### ISSUE THREAD

**Issue by KevinTyrrell** [Atlantiss/NetherwingBugtracker#2345]
[//]: # (Enclose links to things related to the bug using http://wowhead.com or any other TBC database.)
[//]: # (You can use screenshot ingame to visual the issue.)
[//]: # (Write your tickets according to the format:)
[//]: # ([Quest][Azuremyst Isle] Red Snapper - Very Tasty!)
[//]: # ([NPC] Magistrix Erona)
[//]: # ([Spell][Mage] Fireball)
[//]: # ([Npc][Drop] Ghostclaw Lynx)
[//]: # ([Web] Armory doesnt work)

**Description**: 
Ritual Of Summoning ends nearly instantly upon getting a second channeler.

**Current behaviour**:
[Twitch Clip](https://clips.twitch.tv/SmallInspiringKaleOSfrog)

**Expected behaviour**: 
[Video Evidence](https://youtu.be/KmDcuLjBWC0?t=85)

**Server Revision**: 
2255

**Comment by Easyfraggy** [comment]
This is bugged on every pserver afaik.

**Comment by Golfbyxan** [comment]
It was working on The Rebirth: https://youtu.be/Lmn2yOIV__A?t=114
And you can probably dig out something in the commits: https://github.com/Rebirth-MaNGOS/MaNGOS/commits/master

**Comment by devo6969** [comment]
On Netherwing, they reworked the way Ritual of Summoning is now. You get the 2nd channeler, the portal will disappear and a self cast will come from the warlock, summoning the person.
