### ISSUE TITLE
[Spell] Vanish - Bar Switch Is Delayed

### ISSUE THREAD

**Issue by KevinTyrrell** [Atlantiss/NetherwingBugtracker#2346]
[//]: # (Enclose links to things related to the bug using http://wowhead.com or any other TBC database.)
[//]: # (You can use screenshot ingame to visual the issue.)
[//]: # (Write your tickets according to the format:)
[//]: # ([Quest][Azuremyst Isle] Red Snapper - Very Tasty!)
[//]: # ([NPC] Magistrix Erona)
[//]: # ([Spell][Mage] Fireball)
[//]: # ([Npc][Drop] Ghostclaw Lynx)
[//]: # ([Web] Armory doesnt work)

**Description**: 
[Twitch Clip](https://clips.twitch.tv/AmericanCourageousTubersDxCat)

**Current behaviour**:
There is a noticeable delay between vanishing and the stealth bar being set in place. This delays usage of stealth only abilities like cheap shot after a vanish.

**Expected behaviour**: 
The stealth bar should be activate immediately upon vanishing. I can try to find verification if needed.

**Server Revision**: 
2255

**Comment by Evolvee** [comment]
there is a spell delay thread currently waiting to be properly analyzed and implemented but yea, if u can, more footage of it wouldnt hurt

**Comment by KevinTyrrell** [comment]
@Evolvee Do you mean spell batching?

**Comment by Evolvee** [comment]
i guess thats what kids call it these days

**Comment by killablink** [comment]
I was going to agree with you looking at that clip but I made a rogue myself and vanishing -> cheapshot, my bars switched instantly. Maybe addon issue or lag or something?

**Comment by ScottieDOESknow** [comment]
current bar switching - November 12th
https://gyazo.com/dc51f6b941ad5b9e1022940c192b51a2
