### ISSUE TITLE
[NPC][Hellfire Peninsula] Unyielding Knight

### ISSUE THREAD

**Issue by eryczek1615** [Atlantiss/NetherwingBugtracker#2347]
**Description**: 
[Unyielding Knight](https://www.wowhead.com/npc=16906/unyielding-knight#abilities) is located in Expedition Armory

**Current behaviour**:
They run away in fear.
![image](https://user-images.githubusercontent.com/4455568/48016103-fb8d0800-e12a-11e8-84bc-48534ec513f8.png)

**Expected behaviour**:
They shouldn't run away in fear they should only call for help.
[Video](https://youtu.be/fYTbGbHo14Q?t=41) no one knight ran away in fear.

**Server Revision**: 
2255

**Comment by Evolvee** [comment]
isnt the video a private server?
at <https://youtu.be/fYTbGbHo14Q?t=208> there are multiple q items in loot table, weird

**Comment by Easyfraggy** [comment]
The multiple quest items happened (still happens afaik) after they implemented aoe loot and multiple mobs dropped the q item.

**Comment by bloodwindz** [comment]
i remember them from retail tbc i think they dint run in fear too
 but thats minor lol

**Comment by Evolvee** [comment]
rev YYY
