### ISSUE TITLE
[Quest][Shattrath City]Marks of Sargeras

### ISSUE THREAD

**Issue by DeltaLoads** [Atlantiss/NetherwingBugtracker#2348]
[//]: # (Enclose links to things related to the bug using http://wowhead.com or any other TBC database.)
[//]: # (You can use screenshot ingame to visual the issue.)
[//]: # (Write your tickets according to the format:)
[//]: # ([Quest][Azuremyst Isle] Red Snapper - Very Tasty!)
[//]: # ([NPC] Magistrix Erona)
[//]: # ([Spell][Mage] Fireball)
[//]: # ([Npc][Drop] Ghostclaw Lynx)
[//]: # ([Web] Armory doesnt work)

**Description**: 
Unable to turn in quest even if you have 10 marks in your bag, quest displays as completed in quest log
![wowscrnshot_110518_193024](https://user-images.githubusercontent.com/43690147/48018608-938df000-e131-11e8-9747-7c697e27f4fa.jpg)

**Current behaviour**:
Unable to turn in quest
**Expected behaviour**: 
Should be able to turn in quest if you have required quest items in bag
**Server Revision**: 
2255

**Comment by aresbrutus** [comment]
Seems to be an addon issue? Works just fine for me. Please retry and reply back of how it went here.

https://gfycat.com/DiligentCourageousAmericanpainthorse

**Comment by Easyfraggy** [comment]
No new info. Assuming it was addon issue.
