### ISSUE TITLE
[Item] [NPC]: anachronism in Cenarion Expedition's QM vendored goodies

### ISSUE THREAD

**Issue by mhdemn** [Atlantiss/NetherwingBugtracker#2349]
[Fedryen Swiftspear](https://tbc-twinhead.twinstar.cz/?npc=17904) is the quartermaster for this faction. Amongst the things he sells there are two arrow ammunitions: Scout's Arrows and Warden's Arrows.

Now, from TBC launch until 2.1.0 [Warden's Arrows](https://tbc-twinhead.twinstar.cz/?item=24412) required level 62, as seen in this [article](https://wow.gamepedia.com/Warden%27s_Arrow_(ammunition)).
![image](https://user-images.githubusercontent.com/25901582/48019841-b372e300-e134-11e8-9cdb-d1724c226130.png)

From 2.1.0 and on [Warden's Arrows](https://tbc-twinhead.twinstar.cz/?item=31949) got their required level increased to 68. It seems (according to this database) that instead of modifying the item Blizz added a 68 version to the database and replaced the vendor's one with the new one.

Both versions of this ammo required revered reputation (nothing wrong with NW in that aspect).

This is how it looks on NW:
![image](https://user-images.githubusercontent.com/25901582/48019595-1adc6300-e134-11e8-806a-81f269bc8000.png)

Right now though NW is on content patch 2.0.3, same patch it will have on release so this vendor should have the appropriate arrows. 

**Server Revision**: 2255

**Comment by Shanghi** [comment]
This should be fixed in revision 2333.
