### ISSUE TITLE
[Core][Loot] Partially looted Chests not despawning

### ISSUE THREAD

**Issue by Jacksn5** [Atlantiss/NetherwingBugtracker#235]
**Description**: 
When a chest ist only partially looted, it should despawn 5 minutes after opening (regardless if anything was looted). The Darnassian Bleu I left in this chest about half an hour earlier was still in there. This will likely also be a problem for mining nodes.

![wowscrnshot_092318_165731](https://user-images.githubusercontent.com/43507549/45930600-8bec0080-bf62-11e8-8f77-e62a7090a548.jpg)

**Server Revision**: 
2028

**Comment by Manaci** [comment]
Fixed
