### ISSUE TITLE
{NPC] Boulderfist Hunter [Spell] Spear Throw

### ISSUE THREAD

**Issue by Mewmewww** [Atlantiss/NetherwingBugtracker#2350]
[//]: # (Enclose links to things related to the bug using http://wowhead.com or any other TBC database.)
[//]: # (You can use screenshot ingame to visual the issue.)
[//]: # (Write your tickets according to the format:)
[//]: # ([Quest][Azuremyst Isle] Red Snapper - Very Tasty!)
[//]: # ([NPC] Magistrix Erona)
[//]: # ([Spell][Mage] Fireball)
[//]: # ([Npc][Drop] Ghostclaw Lynx)
[//]: # ([Web] Armory doesnt work)

**Description**: 
Spear Throw is cast in melee

**Current behaviour**:
Spear Throw is cast in melee

**Expected behaviour**: 
Not a melee ability.
**Server Revision**: 
2255

**Comment by Evolvee** [comment]
well.. there is no minimum range on the spell

![image](https://user-images.githubusercontent.com/1942409/48031461-a108a180-e154-11e8-9fe1-96ebe7049ce5.png)

**Comment by Tenoutoften** [comment]
[[NPC]Feralfen Hunter#18113](https://www.wowhead.com/npc=18113/feralfen-hunter#comments) uses [[Spell]Serpent Sting#31975](https://www.wowhead.com/spell=31975/serpent-sting) in melee as well. That spell also has no minimum range and comments on wowhead says the NPC does use it in melee.


[[NPC]Boulderfist Hunter#18352](https://www.wowhead.com/npc=18352/boulderfist-hunter#comments) has a comment saying:
![e0b5c812c67f74569d8fe9892b1d3e05](https://user-images.githubusercontent.com/34839199/48078664-32762300-e1ea-11e8-83aa-c0b980182e77.png)

Wouldn't be surprised if this NPC also uses their ability in melee

**Comment by Evolvee** [comment]
k i will close this until u find some proper evidence they shouldnt cast it
