### ISSUE TITLE
Playerside DC-triggered bug

### ISSUE THREAD

**Issue by mhdemn** [Atlantiss/NetherwingBugtracker#2351]
Not sure if this is something that's fixable or worth reporting, but well.
I got dced just now, after being on land for 20 or 25 minutes since I last landed from a flight, it was my connection's problem and when it came back I logged back in, to find myself [flying](https://youtu.be/8Zmth40l-cc) through terrain up to Zangarmash, then backwards fly to Shattrath, then fly to the last place I landed in a regular flight (this horde city in Terokkar). 

Sorry if this is a rare thing that has to do with the game's structure itself that can't be fixed, I don't really know how to tell.

**Server Revision**: 2255

**Comment by Tenoutoften** [comment]
Known that it is very "creative" if you log off while flying: https://github.com/Atlantiss/NetherwingBugtracker/issues/2317

**Comment by mhdemn** [comment]
Please read before you comment your first thought, thanks

**Comment by Easyfraggy** [comment]
https://github.com/Atlantiss/NetherwingBugtracker/issues/2317
