### ISSUE TITLE
[Quest][Terokkar Forest] Veil Skith: Darkstone of Terokk

### ISSUE THREAD

**Issue by Mikik3jr** [Atlantiss/NetherwingBugtracker#2353]
**Description:**
[In this quest](https://tbc-twinhead.twinstar.cz/?quest=10839) we use  Rod of Purification on a stone.

**Current behaviour:**
When I used the quest item it started to channel it, but I instantly got the credit for it, instead of after finishing the channel. 
![wowscrnshot_110518_211013](https://user-images.githubusercontent.com/43505031/48024214-5846ed80-e140-11e8-8547-81fca284435a.jpg)
The stone was not destroyed after I used the item. (According to this [youtube video](https://www.youtube.com/watch?v=RIT_mxzh4r0) it should be destroyed, but it happened after tbc so idk)

**Expected behaviour:**
I should get credit after I finish channeling
Maybe a destroy animation?

**Server Revision:**
2255

**Comment by aresbrutus** [comment]
https://github.com/Atlantiss/AtlantissTBCBT/issues/1025
