### ISSUE TITLE
[Quest][Hellfire Peninsula] In Case of Emergency...

### ISSUE THREAD

**Issue by eryczek1615** [Atlantiss/NetherwingBugtracker#2354]
**Description**: 
[Quest](https://www.wowhead.com/quest=10161/in-case-of-emergency) we have to collect 30 [Zeppelin Debris](https://www.wowhead.com/item=28116/zeppelin-debris).

**Current behaviour**:
This parts disappear after 5-10 sec

**Expected behaviour**: 
After collected part of zeppelin it should disappear immediately

**Server Revision**: 
2255

**Comment by Shanghi** [comment]
I'm not sure when, but this was fixed.
