### ISSUE TITLE
quest escaping the tomb

### ISSUE THREAD

**Issue by clogau** [Atlantiss/NetherwingBugtracker#2355]
[//]: # (Enclose links to things related to the bug using http://wowhead.com or any other TBC database.)
[//]: # (You can use screenshot ingame to visual the issue.)
[//]: # (Write your tickets according to the format:)
[//]: # ([Quest][Azuremyst Isle] Red Snapper - Very Tasty!)
[//]: # ([NPC] Magistrix Erona)
[//]: # ([Spell][Mage] Fireball)
[//]: # ([Npc][Drop] Ghostclaw Lynx)
[//]: # ([Web] Armory doesnt work)

**Description**: 
quest, terokkar forest, bone wastes "Eescaping the tomb"
**Current behaviour**:
completed the quest with another, they accepted the quest as did I via the pop up request finished the quest  other group member got credit I did not
**Expected behaviour**: 
everyone on the quest in same party should get credit
**Server Revision**:

**Comment by Mikik3jr** [comment]
Revision: 2255

**Comment by Evolvee** [comment]
rev YYY
