### ISSUE TITLE
[Spell][Mage]Polymorph - Leaving combat when sheeping 1 npc

### ISSUE THREAD

**Issue by killablink** [Atlantiss/NetherwingBugtracker#2356]
**Description**: Say I just sheep a random mob and start running away, if I run far away enough from the mob, (specially to the point where the mob disappear from my view [cant target him anymore]), the mob should reset and ofc sheep breaks. Right now I can go super far away, come back and the mob is still sheeped.

**Current behaviour**: ^

**Expected behaviour**:  Mob should reset when I'm too far out of range.

**Server Revision**: 2255

**Comment by The14me** [comment]
rev.3451 it looks fixed now (mob reset and sheep break).
Can be closed.
