### ISSUE TITLE
[Misc][NPC]Warped Peon#18595 should "attempts to run away in fear!"

### ISSUE THREAD

**Issue by Tenoutoften** [Atlantiss/NetherwingBugtracker#2357]
**Description**: 
[[NPC]Warped Peon#18595](https://www.wowhead.com/npc=18595/warped-peon) should "attempts to run away in fear!"
Can be seen [here](https://youtu.be/2VW1P2V-WdI?t=208)
![dd1783a9c5360d42557cab5dacf19c05](https://user-images.githubusercontent.com/34839199/48030368-183c3680-e151-11e8-9e47-6c16910f15d6.png)

**Current behaviour**:
Doesn't

**Expected behaviour**: 
Should "attempts to run away in fear!"

**Server Revision**: 
2255

**Comment by Evolvee** [comment]
rev YYY
