### ISSUE TITLE
[NPC] Voidshrieker mobs gain spell school buff against everything cast against them

### ISSUE THREAD

**Issue by BezawitNW** [Atlantiss/NetherwingBugtracker#2358]
The Voidshrieker mobs in Netherstorm are suppose to gain a buff against whatever school of magic is cast against them first which lowers the damage of that spell school by 75%. However they are currently gaining that buff against every type of magic damage used against them. 

So for example, currently if I open with Immolate, the mob gains a buff that lowers fire damage taken by 75% (correct). And then when I apply a Corruption/Curse of Agony, the mob then also gains a buff that lowers shadow damage taken by 75% (incorrect). The mob should only gain the buff based on the first spell used against it.

https://www.wowhead.com/npc=18870/voidshrieker#comments

**Comment by Evolvee** [comment]
rev YYY
