### ISSUE TITLE
[Pathing] Voidwalker having issues pathing into tents

### ISSUE THREAD

**Issue by Scylla420** [Atlantiss/NetherwingBugtracker#236]
**Description**: 
My voidwalker (Spell 697, NPC 1860) has been having great difficulty pathing into a specific tent in Westfall.  I have not had the opportunity to try this out with other tents.  The mob it's trying to attack is Defias Smuggler (95).
[.GPS info](https://i.imgur.com/449SsbA.png)
**Current behaviour**:
https://streamable.com/z8j53
https://streamable.com/vj6ck
**Expected behaviour**: 
My pet should walk into the tent and begin attacking the enemy without issue.
**Server Revision**: 
2028

**Comment by The14me** [comment]
Related do sleeping NPC script : entry 96 ID 39

**Comment by Tereneckla** [comment]
Fixed
