### ISSUE TITLE
[Quest] On Nethery Wings does not complete

### ISSUE THREAD

**Issue by BezawitNW** [Atlantiss/NetherwingBugtracker#2360]
When doing the quest "On Nethery Wings" when you destroy the Void Conduit, you do not get credit for killing it.

**Comment by Evolvee** [comment]
worked fine for me :( :( :(

**Comment by Easyfraggy** [comment]
Low prio untill replication method is added.

**Comment by Evolvee** [comment]
its probably when more ppl do it and it gives credit only to 1?

**Comment by Thorgrimme** [comment]
Same happened to me, and i wasn't in a grp,

**Comment by Mikik3jr** [comment]
I was not in group, threw that q item 14 times and I didn't finish the quest.
![wowscrnshot_111118_123920](https://user-images.githubusercontent.com/43505031/48312441-d70fb080-e5ae-11e8-8ecd-6b7d630ef996.jpg)

**Comment by Kaini27** [comment]
Failed quest of first try. There is an NPC on top of the building, seems like upon death its not always counts kill, maybe duo to it being out of range on kill coz of the netherwing drake flight path. Also, how different players suppose to do it in a row? Do they will have to wait for a respawn?
https://i.imgur.com/tXjmIM1.jpg

**Comment by Evolvee** [comment]
![image](https://user-images.githubusercontent.com/1942409/48365351-fbe94e00-e6aa-11e8-99eb-fd44877579b8.png)

I just finished it 
![image](https://user-images.githubusercontent.com/1942409/48365368-01469880-e6ab-11e8-9167-76a3bcaf48a9.png)

with 13 stacks left

I will make some slight improvements to it, but it works for me....


Try again after revision "dung".
