### ISSUE TITLE
[NPC][Spell] Bloodscale Enchantress - Freezing Circle

### ISSUE THREAD

**Issue by Kaini27** [Atlantiss/NetherwingBugtracker#2361]
[//]: # (Enclose links to things related to the bug using http://wowhead.com or any other TBC database.)
[//]: # (You can use screenshot ingame to visual the issue.)
[//]: # (Write your tickets according to the format:)
[//]: # ([Quest][Azuremyst Isle] Red Snapper - Very Tasty!)
[//]: # ([NPC] Magistrix Erona)
[//]: # ([Spell][Mage] Fireball)
[//]: # ([Npc][Drop] Ghostclaw Lynx)
[//]: # ([Web] Armory doesnt work)
**Description**: Freezing circle spell on Bloodscale Enchantress in Zangarmarsh is not working properly.

**Current behaviour**:
**1** Freezing circle appears after cast is finished but its casted on Bloodscale Enchantress position instead.
**2** Animation is stuck on first/last phase (frost stones keep spawning in first/last phase position and for form circle).
**3** Freezing debuff and damage applied immediately without waiting animation to finish, could be so, that its finished right away and this bugs out animation aswell.
**Expected behaviour**:
Freezing circle should appear after Bloodscale Enchantress finishes cast on a player (where he was at the start of the cast) and after circle is finished it freezes (roots) player for a long period of time and does high instant damage.

**Server Revision**: 2255

**Comment by Easyfraggy** [comment]
https://github.com/Atlantiss/NetherwingBugtracker/issues/2151

**Comment by xmesaj2** [comment]
fix in rev 2080
