### ISSUE TITLE
[NPC][Blade's Edge Mountains]Unstable Fel-Imp

### ISSUE THREAD

**Issue by DeltaLoads** [Atlantiss/NetherwingBugtracker#2362]
[//]: # (Enclose links to things related to the bug using http://wowhead.com or any other TBC database.)
[//]: # (You can use screenshot ingame to visual the issue.)
[//]: # (Write your tickets according to the format:)
[//]: # ([Quest][Azuremyst Isle] Red Snapper - Very Tasty!)
[//]: # ([NPC] Magistrix Erona)
[//]: # ([Spell][Mage] Fireball)
[//]: # ([Npc][Drop] Ghostclaw Lynx)
[//]: # ([Web] Armory doesnt work)

**Description**: 
During quest Fire At Will! Unstable Fel-Imps award full XP, i remember they awarded much less in retail, but cant find exact number. Since they are one-shot for most classes and they keep spawning this can be abused for easy leveling
**Current behaviour**:
Unstable Fel-Imps award full XP 
**Expected behaviour**: 
Unstable Fel-Imps should award just a fraction of current XP
**Server Revision**: 
2255

**Comment by Evolvee** [comment]
rev YYY
