### ISSUE TITLE
[Spell][Paladin] Divine Illumination

### ISSUE THREAD

**Issue by Mikik3jr** [Atlantiss/NetherwingBugtracker#2363]
[//]: # (Enclose links to things related to the bug using http://wowhead.com or any other TBC database.)
[//]: # (You can use screenshot ingame to visual the issue.)
[//]: # (Write your tickets according to the format:)
[//]: # ([Quest][Azuremyst Isle] Red Snapper - Very Tasty!)
[//]: # ([NPC] Magistrix Erona)
[//]: # ([Spell][Mage] Fireball)
[//]: # ([Npc][Drop] Ghostclaw Lynx)
[//]: # ([Web] Armory doesnt work)

**Description**: 
![image](https://user-images.githubusercontent.com/43505031/48031981-47a17200-e156-11e8-9709-9053b3da5338.png)
If I cast a spell with this buff, but the buff wears off before I finish casting, then the spell costs according to the original spell cost.
**Current behaviour**:
The problem is if the buff wears off and I can't afford the original mana cost I still finish casting it:
https://www.youtube.com/watch?v=JF5InNoDemo&feature=youtu.be
**Expected behaviour**: 
I shouldn't be able to finish the casting of a spell if I can't afford the mana cost.
**Server Revision**: 
2255

**Comment by Wolffenstein** [comment]
Fixed in rev 2301.
