### ISSUE TITLE
[Wand] Quivers not increasing wand speed

### ISSUE THREAD

**Issue by Thugli** [Atlantiss/NetherwingBugtracker#2364]
[//]: # (Enclose links to things related to the bug using http://wowhead.com or any other TBC database.)
[//]: # (You can use screenshot ingame to visual the issue.)
[//]: # (Write your tickets according to the format:)
[//]: # ([Quest][Azuremyst Isle] Red Snapper - Very Tasty!)
[//]: # ([NPC] Magistrix Erona)
[//]: # ([Spell][Mage] Fireball)
[//]: # ([Npc][Drop] Ghostclaw Lynx)
[//]: # ([Web] Armory doesnt work)

**Description**: 
Quivers increase ranged attack speed by 10%, and I am pretty sure that wands are considered a ranged attack. I'm also fairly certain this was how it worked in retail TBC, though I am in the process of looking for proper evidence. 
**Current behaviour**:
Equipping a quiver does not affect wand attack speed.
**Expected behaviour**: 
Equipping a quiver should increase wand attack speed by the amount that is listed in the quiver's tooltip.
**Server Revision**: 
2255

**Comment by Wolffenstein** [comment]
We specifically made it not affect wand speed since that was a bug.
