### ISSUE TITLE
[Spell][Paladin] Seal of Blood

### ISSUE THREAD

**Issue by Kaini27** [Atlantiss/NetherwingBugtracker#2365]
[//]: # (Enclose links to things related to the bug using http://wowhead.com or any other TBC database.)
[//]: # (You can use screenshot ingame to visual the issue.)
[//]: # (Write your tickets according to the format:)
[//]: # ([Quest][Azuremyst Isle] Red Snapper - Very Tasty!)
[//]: # ([NPC] Magistrix Erona)
[//]: # ([Spell][Mage] Fireball)
[//]: # ([Npc][Drop] Ghostclaw Lynx)
[//]: # ([Web] Armory doesnt work)

**Description**:  Reflected damage is too high.

**Current behaviour**: All melee attacks deal additional Holy damage equal to 35% of normal weapon damage, but the Paladin loses health equal to **500**% of the total damage inflicted.

**Expected behaviour**: All melee attacks deal additional Holy damage equal to 35% of normal weapon damage, but the Paladin loses health equal to 10% of the total damage inflicted.

**Server Revision**: 2255

**Comment by Easyfraggy** [comment]
As in missing entirely or just lowered to the proper amount?

**Comment by Kaini27** [comment]
Critical hits dont cause larger reflected damage. Unknow for me if they should do more.

**Comment by Wolffenstein** [comment]
Fixed
