### ISSUE TITLE
Bonus damage of items not showing in charakter spell info/maybe also not working

### ISSUE THREAD

**Issue by Nicemann1089** [Atlantiss/NetherwingBugtracker#2366]
[//]: # (Enclose links to things related to the bug using http://wowhead.com or any other TBC database.)
[//]: # (You can use screenshot ingame to visual the issue.)
[//]: # (Write your tickets according to the format:)
[//]: # ([Quest][Azuremyst Isle] Red Snapper - Very Tasty!)
[//]: # ([NPC] Magistrix Erona)
[//]: # ([Spell][Mage] Fireball)
[//]: # ([Npc][Drop] Ghostclaw Lynx)
[//]: # ([Web] Armory doesnt work)

https://drive.google.com/file/d/1ncxJxIvlcce3OMVc6ZUtZkPss7-sNh0E/view?usp=drivesdk

**Description**: In the video you can see the equipped mace shows 31 bonus healing and 11 bonus damage in the tooltip. But only the bonus healing is shown in the charakter spell info.

**Current behaviour**: Only bonus healing of items seems to apply, not bonus damage. At least it is not displaying it.

**Expected behaviour**: Bonus healing and damage should apply like shown in the tooltip.

**Server Revision**: 2255

**Comment by Nicemann1089** [comment]
aight, wasn't familiar with the 2.0 itemization. thx

**Comment by Tenoutoften** [comment]
No, since those items gave both; https://classicdb.ch/?itemset=212
