### ISSUE TITLE
Burning Legion Gate Key

### ISSUE THREAD

**Issue by Defgha** [Atlantiss/NetherwingBugtracker#2367]
[Quest][Hellfire P] Doorway to the Abyss
[NPC]  Warbringer Arix'Amal
[Npc][Drop] Burning Legion Gate Key

**Description**: 
Didn't drop key on kill

**Current behaviour**:

**Expected behaviour**: 

**Server Revision**:

**Comment by aresbrutus** [comment]
Works fine: https://i.imgur.com/Lr6HtEU.jpg

Tons of people also did this quest and it drops.
