### ISSUE TITLE
[Quest][Misc] Nexus-King Salhadaar

### ISSUE THREAD

**Issue by netherwingbta** [Atlantiss/NetherwingBugtracker#2369]
[//]: # (Enclose links to things related to the bug using http://wowhead.com or any other TBC database.)
[//]: # (You can use screenshot ingame to visual the issue.)
[//]: # (Write your tickets according to the format:)
[//]: # ([Quest][Azuremyst Isle] Red Snapper - Very Tasty!)
[//]: # ([NPC] Magistrix Erona)
[//]: # ([Spell][Mage] Fireball)
[//]: # ([Npc][Drop] Ghostclaw Lynx)
[//]: # ([Web] Armory doesnt work)

**Description**: 
https://www.wowhead.com/quest=10408/nexus-king-salhadaar
https://www.wowhead.com/npc=20454/nexus-king-salhadaar
One of the force field visuals is missing. Disabling all 3 still unlocks him normally though.
**Current behaviour**:
![wow 2018-11-06 05-22-22-07](https://user-images.githubusercontent.com/43872263/48042994-877f4e00-e184-11e8-997b-4e9d87a2ba9b.jpg)

**Expected behaviour**: 
![3](https://user-images.githubusercontent.com/43872263/48043002-91a14c80-e184-11e8-925f-c29fe1e87a59.jpg)

https://www.youtube.com/watch?v=Rs8zH2vtpGY
https://www.youtube.com/watch?v=rWyBXTo9XIc&t=18s

**Server Revision**: 
2256

**Comment by aresbrutus** [comment]
https://github.com/Atlantiss/AtlantissTBCBT/issues/3156

**Comment by Wolffenstein** [comment]
Fixed in rev 3414.
