### ISSUE TITLE
[Spell][Shaman] Stoneclaw Totem

### ISSUE THREAD

**Issue by Eidous** [Atlantiss/NetherwingBugtracker#237]
[//]: # (Enclose links to things related to the bug using http://wowhead.com or any other TBC database.)
[//]: # (You can use screenshot ingame to visual the issue.)
[//]: # (Write your tickets according to the format:)
[//]: # ([Quest][Azuremyst Isle] Red Snapper - Very Tasty!)
[//]: # ([NPC] Magistrix Erona)
[//]: # ([Spell][Mage] Fireball)
[//]: # ([Npc][Drop] Ghostclaw Lynx)
[//]: # ([Web] Armory doesnt work)

**Description**: 
Stoneclaw totems should have a 50% chance to stun melee attackers for 3 seconds. This does not seem to be working at the moment.

**Current behaviour**:
Stoneclaw totems do not proc their stun.

**Expected behaviour**: 
Stoneclaw totems proccing their stun when getting hit in melee

**Server Revision**: 
2028

**Comment by narayagh** [comment]
This seems to be fixed in rev 2072.

**Comment by bj86** [comment]
My experience is that it doesn't even taunt the mob if I have done previous threat to it. I see the "taunt" animation, but the mob keeps attacking me. Also no stun.
