### ISSUE TITLE
[NPC] Razormane Wolf level too high

### ISSUE THREAD

**Issue by totaemoeggerli** [Atlantiss/NetherwingBugtracker#2370]
[//]: # (Enclose links to things related to the bug using http://wowhead.com or any other TBC database.)
[//]: # (You can use screenshot ingame to visual the issue.)
[//]: # (Write your tickets according to the format:)
[//]: # ([Quest][Azuremyst Isle] Red Snapper - Very Tasty!)
[//]: # ([NPC] Magistrix Erona)
[//]: # ([Spell][Mage] Fireball)
[//]: # ([Npc][Drop] Ghostclaw Lynx)
[//]: # ([Web] Armory doesnt work)

**Description**: 
[Razormane Wolf](https://www.wowhead.com/npc=3939/razormane-wolf#comments) is the pet of [Razormane Hunter](https://www.wowhead.com/npc=3265/razormane-hunter#comments).

**Current behaviour**:
Pet is same level as the master (11-12).

**Expected behaviour**:
Pet should be 4 levels below the master (7-8).
The NPCs survived Cata and the wolf is still 4 levels lower, scales from 7-56 the Hunter scales from 10-60.
I didn't find any wowhead comments so here is a wowwiki link. http://wowwiki.wikia.com/wiki/Razormane_Wolf

**Server Revision**: 2256

**Comment by The14me** [comment]
rev.3451 still an issue.

**Comment by Wolffenstein** [comment]
Fixed in rev 3459.
