### ISSUE TITLE
[NPC] Bonechewer Scavanger

### ISSUE THREAD

**Issue by shockave** [Atlantiss/NetherwingBugtracker#2372]
[//]: # (Enclose links to things related to the bug using http://wowhead.com or any other TBC database.)
[//]: # (You can use screenshot ingame to visual the issue.)
[//]: # (Write your tickets according to the format:)
[//]: # ([Quest][Azuremyst Isle] Red Snapper - Very Tasty!)
[//]: # ([NPC] Magistrix Erona)
[//]: # ([Spell][Mage] Fireball)
[//]: # ([Npc][Drop] Ghostclaw Lynx)
[//]: # ([Web] Armory doesnt work)

**Description**: 
Bonechewer Scavanger ran away from me to "throw wrench" when was in melee range then again walked to me and melee'd me like normal
**Current behaviour**:
when NPC is in melee range he walks away to use "throw wrench" once then again walks up to melee you.
**Expected behaviour**: 
He should use "throw wrench" only when he's not in melee and should not run away to use it
**Server Revision**:

**Comment by Easyfraggy** [comment]
Thinkhttps://github.com/Atlantiss/NetherwingBugtracker/issues/1989
