### ISSUE TITLE
[Spell][NPC]Cleave by Roloch

### ISSUE THREAD

**Issue by Fenvarien1** [Atlantiss/NetherwingBugtracker#2374]
Class: Hunter
Pet: Bird

**Description**: 
NPC Name: Roloch(Rare-Elite)
Where: Stranglethorn Vale
NPC ID: 14488
Spell ID: 15496
NPC link: http://db.hellfire-tbc.com/?npc=14488
Spell link: http://db.hellfire-tbc.com/?spell=15496

"Inflicts 110% of normal melee damage to an enemy and its nearest ally."

I tanked the rare elite with my pet and positioned myself on the opposit side of the mob. He hits me on a long range with its cleave. see gif.

**Current behaviour**:
https://gfycat.com/DeepSoggyColt

**Expected behaviour**: 
As of the statement from easy he shouldn't be able to hit me at this range to the target hit by cleave.

**Server Revision**:

**Comment by Easyfraggy** [comment]
The chaining range is way too big should never be this large unless its a gigantic mob like Magtheridon.

These mobs that use this specific cleave are semi-large (ogre size and slightly above/below) the correct chaining range would be about 5yards from the center of target (not combat reach).

**Comment by Fenvarien1** [comment]
Revision 2256

**Comment by The14me** [comment]
Rev.3451 still an issue.

**Comment by Wolffenstein** [comment]
With 2.0 Cleave it's working as intended.
