### ISSUE TITLE
[Objective]a fishpool cut in half

### ISSUE THREAD

**Issue by Fenvarien1** [Atlantiss/NetherwingBugtracker#2375]
**Description**: 
Objective: Firefin Snapper School
Where: Stranglethorn Vale
Coords: 24.8 19.5

**Current behaviour**:
![fishpool](https://i.imgur.com/tggCFHI.jpg)

**Expected behaviour**: 
not cut in half

**Server Revision**:

**Comment by Fenvarien1** [comment]
Revision 2256

**Comment by Manaci** [comment]
Fixed
