### ISSUE TITLE
[Npc][Drop]Steam Pump Overseer;Drain Schematics

### ISSUE THREAD

**Issue by wuchermann** [Atlantiss/NetherwingBugtracker#2376]
Drop rate for drain Schematics may be to low; wowhead comments suggest its a higher drop chance from the Steam Pump Overseer : (https://www.wowhead.com/item=24330/drain-schematics)

**Comment by Tenoutoften** [comment]
I probably killed over 30 of this specific NPC, I definitely think it is too low.

**Comment by aresbrutus** [comment]
Fixed in rev `Eris`
