### ISSUE TITLE
End Of Duel Cheer Doesn't Happen If Channeling

### ISSUE THREAD

**Issue by KevinTyrrell** [Atlantiss/NetherwingBugtracker#2377]
[//]: # (Enclose links to things related to the bug using http://wowhead.com or any other TBC database.)
[//]: # (You can use screenshot ingame to visual the issue.)
[//]: # (Write your tickets according to the format:)
[//]: # ([Quest][Azuremyst Isle] Red Snapper - Very Tasty!)
[//]: # ([NPC] Magistrix Erona)
[//]: # ([Spell][Mage] Fireball)
[//]: # ([Npc][Drop] Ghostclaw Lynx)
[//]: # ([Web] Armory doesnt work)

**Description**: 
[Twitch Clip](https://clips.twitch.tv/JollyProudGoatFailFish)

**Current behaviour**:
While casting, the casters channeling is interrupted (all casting, or just channeling?) but he does not perform the cheer.

**Expected behaviour**: 
A duel winner will cheer when he is victorious in a duel.

**Server Revision**: 
2256

**Comment by Wolffenstein** [comment]
Not a bug/clientside.
