### ISSUE TITLE
[Misc][NPC]Minion of Terokk#22376 should give 10% rather than 100% of regular mob xp

### ISSUE THREAD

**Issue by Tenoutoften** [Atlantiss/NetherwingBugtracker#2378]
**Description**: 
[[NPC]Minion of Terokk#22376](https://www.wowhead.com/npc=22376/minion-of-terokk) should only give ~10% of regular mob xp.
[Video here](https://youtu.be/4OUSOHykCuA?t=7)

These are spawned during [[Quest]The Skettis Offensive#10879](https://www.wowhead.com/quest=10879/the-skettis-offensive)

**Current behaviour**:
Gives full xp

**Expected behaviour**: 
10% of regular mob.

**Server Revision**: 
2256

**Comment by Evolvee** [comment]
rev DDF
