### ISSUE TITLE
[Spell][NPC]Thetis spell Tendon Rip wrong slow value

### ISSUE THREAD

**Issue by Fenvarien1** [Atlantiss/NetherwingBugtracker#2379]
**Description**: 
NPC: Thetis
Where: Stranglethorn Vale
Spell: Tendon Rip
NPC ID: 730
Spell ID: 3604
NPC link: http://db.hellfire-tbc.com/?npc=730
Spell link: http://db.hellfire-tbc.com/?spell=3604

Reduces an enemy's movement speed by 25% for 10 sec.

**Current behaviour**:
gif: https://gfycat.com/BoldSeparateCoyote
![tendon rip debuff](https://i.imgur.com/MocS4TF.jpg)

debuff value seems to be 67%

**Expected behaviour**: 
debuff value should be 25%

**Server Revision**:

**Comment by Mikik3jr** [comment]
Revision: 2256

(If you write ".server info" you can check it)

**Comment by Fenvarien1** [comment]
ok thanks for the hint. will check it soon

**Comment by Tenoutoften** [comment]
This might be a client issue, I can't find any "Tendon Rip" other than the one [[NPC]Tethis#730](https://www.wowhead.com/npc=730/tethis#abilities) uses...
[[Spell]Tendon Rip#3604](https://www.wowhead.com/spell=3604/tendon-rip) from wowhead

There is only one Tendon Rip in Excalibur Database and it is that one.

**Comment by Easyfraggy** [comment]
Well hes also linking pserver database so xD 
![image](https://user-images.githubusercontent.com/36134067/48078072-158d2000-e1e9-11e8-8857-3756c363d4c2.png)
