### ISSUE TITLE
[Item] Noggenfogger Elixir

### ISSUE THREAD

**Issue by KevinTyrrell** [Atlantiss/NetherwingBugtracker#2381]
[//]: # (Enclose links to things related to the bug using http://wowhead.com or any other TBC database.)
[//]: # (You can use screenshot ingame to visual the issue.)
[//]: # (Write your tickets according to the format:)
[//]: # ([Quest][Azuremyst Isle] Red Snapper - Very Tasty!)
[//]: # ([NPC] Magistrix Erona)
[//]: # ([Spell][Mage] Fireball)
[//]: # ([Npc][Drop] Ghostclaw Lynx)
[//]: # ([Web] Armory doesnt work)

**Description**:
Noggenfogger does not impose restrictions with mounting.

**Current behaviour**:
You can mount while under the effects of Noggenfogger Skeleton: [Screenshot](https://i.imgur.com/geiKSDA.jpg)
You can mount while under the effects of Noggenfogger Mini [Screenshot](https://i.imgur.com/a61mUCh.jpg)

**Expected behaviour**: 
You cannot mount while under the effects of Noggenfogger Skeleton
>Patch 5.0.4 (2012-08-28): You can now mount while transformed into a skeleton.

You cannot mount while under the effects of Noggenfogger Mini
>Patch 3.3.0 (2009-12-08): Players shrunk while under the effects of this item will now be able to mount.

[Evidence](https://wow.gamepedia.com/Noggenfogger_Elixir)

**Server Revision**: 
2256

**Comment by Wolffenstein** [comment]
Fixed in rev 2263.
