### ISSUE TITLE
Quest, Timber Worg tails

### ISSUE THREAD

**Issue by clogau** [Atlantiss/NetherwingBugtracker#2382]
[//]: # (Enclose links to things related to the bug using http://wowhead.com or any other TBC database.)
[//]: # (You can use screenshot ingame to visual the issue.)
[//]: # (Write your tickets according to the format:)
[//]: # ([Quest][Azuremyst Isle] Red Snapper - Very Tasty!)
[//]: # ([NPC] Magistrix Erona)
[//]: # ([Spell][Mage] Fireball)
[//]: # ([Npc][Drop] Ghostclaw Lynx)
[//]: # ([Web] Armory doesnt work)

**Description**: 
Unable to complete quest as no quest items are dropping
**Current behaviour**:
Quest requires 12 timber worg tails, I currently have 9, but even killing numerous and numerous wolfs they have not dropped any more, yes I am aware that the drop rate of these are very very low. Also I have noticed that the quest giver has a yellow question mark above his head to indicate that the quest is completed, but am not able to complete. And none of the quest itmems are in my bank
**Expected behaviour**: 
The quest giver should not have a solid yellow question mark over his head until quest items have been aquired
**Server Revision**:

**Comment by Evolvee** [comment]
![image](https://user-images.githubusercontent.com/1942409/48070864-259d0380-e1d9-11e8-8003-22a2bf17c6e4.png)

it drops for me

![image](https://user-images.githubusercontent.com/1942409/48070935-46fdef80-e1d9-11e8-9f6d-236472aec5dc.png)

try to clean cache
