### ISSUE TITLE
[Racial][Human] Diplomacy

### ISSUE THREAD

**Issue by Mikik3jr** [Atlantiss/NetherwingBugtracker#2383]
[//]: # (Enclose links to things related to the bug using http://wowhead.com or any other TBC database.)
[//]: # (You can use screenshot ingame to visual the issue.)
[//]: # (Write your tickets according to the format:)
[//]: # ([Quest][Azuremyst Isle] Red Snapper - Very Tasty!)
[//]: # ([NPC] Magistrix Erona)
[//]: # ([Spell][Mage] Fireball)
[//]: # ([Npc][Drop] Ghostclaw Lynx)
[//]: # ([Web] Armory doesnt work)

**Description**: 
You gain 10% more reputation.

**Current behaviour**:
I finished a [quest ](https://www.wowhead.com/quest=10020/a-cure-for-zahlia) which gives 350 repu to Aldor. I got the 350x1.1 = 385 reputation to Aldor, but I lost 423 repu from Scryers. (350x1.1x1.1)
![wowscrnshot_110618_134914](https://user-images.githubusercontent.com/43505031/48067204-f59d3280-e1cf-11e8-8960-c5c4f80d88fe.jpg)
**Expected behaviour**: 
![image](https://user-images.githubusercontent.com/43505031/48067180-e322f900-e1cf-11e8-881e-5e92ac4cbc4d.png)
I think when you finish that quests for aldor or scryer you lose 10% more from the other side, so the human racial is countered out (so you can't be exalted with both sides), but it seem the racial makes you lose more rep.
**Server Revision**: 
2256

**Comment by Wolffenstein** [comment]
Fixed in rev 2285.

**Comment by Mikik3jr** [comment]
For finishing an Aldor quest I still lose more for Scryers than what I get for Aldor. (Actually I couldn't find if as human I should lose the same amount as I get to the other side, but I comment here just in case)
