### ISSUE TITLE
[NPC] Illidari Taskmaster and their slaves spawn stacked instead of on their spots.

### ISSUE THREAD

**Issue by Easyfraggy** [Atlantiss/NetherwingBugtracker#2385]
**Description**: 

**Current behaviour**:
![image](https://user-images.githubusercontent.com/36134067/48074045-57fe2f00-e1e0-11e8-962b-9106b8eac7c2.png)

If you pull them and reset they go to their correct positions:

![image](https://user-images.githubusercontent.com/36134067/48074064-651b1e00-e1e0-11e8-9fff-1f3aecbbada9.png)

**Expected behaviour**: 
Spawn in their correct positions.

**Server Revision**: 2255

**Comment by Tereneckla** [comment]
Fixed
