### ISSUE TITLE
Fel corrupters in BEM should be patrolling giving buffs to the serpents and raptors not standing in same spot

### ISSUE THREAD

**Issue by rasin00** [Atlantiss/NetherwingBugtracker#2386]
[//]: # (Enclose links to things related to the bug using http://wowhead.com or any other TBC database.)
[//]: # (You can use screenshot ingame to visual the issue.)
[//]: # (Write your tickets according to the format:)
[//]: # ([Quest][Azuremyst Isle] Red Snapper - Very Tasty!)
[//]: # ([NPC] Magistrix Erona)
[//]: # ([Spell][Mage] Fireball)
[//]: # ([Npc][Drop] Ghostclaw Lynx)
[//]: # ([Web] Armory doesnt work)

**Description**: 

**Current behaviour**:

**Expected behaviour**: 

**Server Revision**:

**Comment by Easyfraggy** [comment]
Yes they are just not added yet.

**Comment by The14me** [comment]
Work fine now.(they add the buff).

**Comment by Easyfraggy** [comment]
I dont think we fixed their patrols smaily?

**Comment by The14me** [comment]
Rev 3451. Path and buff are fixed now.
Can be closed.
