### ISSUE TITLE
Feeding pet with high level food does not work

### ISSUE THREAD

**Issue by lasdarf** [Atlantiss/NetherwingBugtracker#2388]
[//]: # (Enclose links to things related to the bug using http://wowhead.com or any other TBC database.)
[//]: # (You can use screenshot ingame to visual the issue.)
[//]: # (Write your tickets according to the format:)
[//]: # ([Quest][Azuremyst Isle] Red Snapper - Very Tasty!)
[//]: # ([NPC] Magistrix Erona)
[//]: # ([Spell][Mage] Fireball)
[//]: # ([Npc][Drop] Ghostclaw Lynx)
[//]: # ([Web] Armory doesnt work)

**Description**: 
When you feed your pet with food, which is above the pets level it is not consumed by the pet. Nevertheless the animation is there and also the sound effect. Additionally no error pops up (e.g. pet level too low). Everything else works as intended: F.e. The Hyena does not want to eat bread and also the correct error message pops up.
I experienced this behaviour when I tried to feed my lvl 50 Hyena with lvl 55 food.

**Current behaviour**:
The animation and sound effects for feeding the pet are working, but the food is not consumed.
**Expected behaviour**: 
I'm unsure here, what is the "correct" way. To my knowledge a pet should be able to eat food also above the pets level. When a pet does not want to eat the food an error message should pop up (food level too low, does not eat bread etc...)
**Server Revision**: 
Tested on 06.11.2018

**Comment by Easyfraggy** [comment]
https://github.com/Atlantiss/NetherwingBugtracker/issues/1917
