### ISSUE TITLE
[Quest][Shadowmoon Valley]The Force of Neltharaku

### ISSUE THREAD

**Issue by DeltaLoads** [Atlantiss/NetherwingBugtracker#2389]
[//]: # (Enclose links to things related to the bug using http://wowhead.com or any other TBC database.)
[//]: # (You can use screenshot ingame to visual the issue.)
[//]: # (Write your tickets according to the format:)
[//]: # ([Quest][Azuremyst Isle] Red Snapper - Very Tasty!)
[//]: # ([NPC] Magistrix Erona)
[//]: # ([Spell][Mage] Fireball)
[//]: # ([Npc][Drop] Ghostclaw Lynx)
[//]: # ([Web] Armory doesnt work)

**Description**: 
Freeing Enslaved Netherwing Drake awards two credits toward quest completion instead of one - you get one credit as soon as you use quest item on them and then another after 10s or so
**Current behaviour**:
Freeing Enslaved Netherwing Drake awards two credits toward quest completion
**Expected behaviour**: 
Should only get 1 credit per drake
**Server Revision**: 
2256

**Comment by xmesaj2** [comment]
fixed in 2316
