### ISSUE TITLE
Group loot threshold not working

### ISSUE THREAD

**Issue by Shakeandbake** [Atlantiss/NetherwingBugtracker#239]
[//]: # (Enclose links to things related to the bug using http://wowhead.com or any other TBC database.)
[//]: # (You can use screenshot ingame to visual the issue.)
[//]: # (Write your tickets according to the format:)
[//]: # ([Quest][Azuremyst Isle] Red Snapper - Very Tasty!)
[//]: # ([NPC] Magistrix Erona)
[//]: # ([Spell][Mage] Fireball)
[//]: # ([Npc][Drop] Ghostclaw Lynx)
[//]: # ([Web] Armory doesnt work)

**Description**: 
Grouped with another player with 'group loot' turned on, and threshold set to uncommon caused white quality items to not be lootable, and claim they are still being rolled on.
**Current behaviour**:

**Expected behaviour**: 

**Server Revision**:

**Comment by wtRCH** [comment]
It is known issue that we are currently working on.

Duplicate
