### ISSUE TITLE
[NPC][Hellfire Peninsula] Void Baron Galaxis

### ISSUE THREAD

**Issue by eryczek1615** [Atlantiss/NetherwingBugtracker#2390]
**Description**: 
[Void Baron Galaxis](https://www.wowhead.com/npc=16939/void-baron-galaxis#abilities)

**Current behaviour**:
He doesn't use [Absorb Life](https://www.wowhead.com/spell=34239/absorb-life)
His [Void Servant](https://www.wowhead.com/npc=19599/void-servant) are hitting for 30-60hp

**Expected behaviour**: 
He should use Absorb Life
Void Servant according to this [Video](https://youtu.be/BH5o47DjjiE?t=81) should attack for 90-120hp and should be <Void Baron Galaxis's Guardian>

**Server Revision**: 
2256

**Comment by Evolvee** [comment]
rev dsa
