### ISSUE TITLE
felsworn gas mask - can't turn the quest in

### ISSUE THREAD

**Issue by rasin00** [Atlantiss/NetherwingBugtracker#2391]
[//]: # (Enclose links to things related to the bug using http://wowhead.com or any other TBC database.)
[//]: # (You can use screenshot ingame to visual the issue.)
[//]: # (Write your tickets according to the format:)
[//]: # ([Quest][Azuremyst Isle] Red Snapper - Very Tasty!)
[//]: # ([NPC] Magistrix Erona)
[//]: # ([Spell][Mage] Fireball)
[//]: # ([Npc][Drop] Ghostclaw Lynx)
[//]: # ([Web] Armory doesnt work)

**Description**: 

**Current behaviour**:

**Expected behaviour**: 

**Server Revision**:

**Comment by Easyfraggy** [comment]
I've seen others do this q, need more information.

**Comment by Tenoutoften** [comment]
Did your mask expire maybe?

**Comment by Tenoutoften** [comment]
I just did this.
Your mask probably either expired or you didn't equip it:
https://www.youtube.com/watch?v=5eS5QYIJelU&feature=youtu.be

**Comment by Tenoutoften** [comment]
Did the entire chain without problems

**Comment by Easyfraggy** [comment]
Seems noone else has this issue - gonna close for now if someone else experiences this I will reopen.
