### ISSUE TITLE
(NPC] Ear-Biter

### ISSUE THREAD

**Issue by Thorgrimme** [Atlantiss/NetherwingBugtracker#2392]
![wow_2018-11-06_18-34-07](https://user-images.githubusercontent.com/43525297/48082386-c6e48380-e1f2-11e8-8493-0be5f74f9d9c.jpg)

**Description**: Has the sound of a male gnome when u talk to him.

**Expected behaviour**: A ogre voice would be more suitable.

**Server Revision**:

**Comment by netherwingbta** [comment]
It's on purpose, the ogre is a reference to Mike Tyson. (bit part of someones ear off) and the goblin next to him is a reference to Don King.
https://www.wowhead.com/npc=18895/ear-biter#sounds

**Comment by Thorgrimme** [comment]
The more u know.

**Comment by Thorgrimme** [comment]
Read comment above.
