### ISSUE TITLE
[Quest] Survey The Land

### ISSUE THREAD

**Issue by Mewmewww** [Atlantiss/NetherwingBugtracker#2393]
[//]: # (Enclose links to things related to the bug using http://wowhead.com or any other TBC database.)
[//]: # (You can use screenshot ingame to visual the issue.)
[//]: # (Write your tickets according to the format:)
[//]: # ([Quest][Azuremyst Isle] Red Snapper - Very Tasty!)
[//]: # ([NPC] Magistrix Erona)
[//]: # ([Spell][Mage] Fireball)
[//]: # ([Npc][Drop] Ghostclaw Lynx)
[//]: # ([Web] Armory doesnt work)

**Description**: 
Nagrand Quest with Altruiss
**Current behaviour**:
After taking the quest, I should be flying with his drake over forge camp, and then when I land, then I should have my survey completed. Right now, you take the quest, then you need to talk to him and once you're finished speaking to him, then he completes your survey and makes you fly.
**Expected behaviour**: 
Flight instantly.
**Server Revision**: 
2256

**Comment by Evolvee** [comment]
proof?

**Comment by Mewmewww** [comment]
https://www.youtube.com/watch?v=cRcrDqt6-0E&t=5s
latest video i can find on youtube. also in questlog it says "
Sit back and enjoy the ride. Speak to Altruis when the survey is complete."'
https://www.wowhead.com/classes#warrior

**Comment by Easyfraggy** [comment]
From my memory you get credit at the end of the flight.

**Comment by mhdemn** [comment]
Yeah, I remember getting credit by finishing Altruis' dialogue after the flight is complete.

About starting the flight I think it started automatically after accepting the quest, but perhaps the dragon had a dialogue button to start it, not sure. Pretty sure you had no way of getting Altruis' dialogue without flying first, that's for sure.

**Comment by Evolvee** [comment]
TBC/Wotlk video would be handy

**Comment by Manaci** [comment]
Fixed
