### ISSUE TITLE
[NPC]Wrekt Seer#17143 should keep [Spell]Lightning Shield#12550 up outside of combat.

### ISSUE THREAD

**Issue by Tenoutoften** [Atlantiss/NetherwingBugtracker#2394]
**Description**: 
[[NPC]Wrekt Seer#17143](https://www.wowhead.com/npc=17143/wrekt-seer#comments) should keep [[Spell]Lightning Shield#12550](https://www.wowhead.com/spell=12550/lightning-shield) up outside of combat. Can be seen [here](https://youtu.be/hJMTEKTaBbA?t=63)

**Current behaviour**:
Doesn't keep it up outside of combat.

**Expected behaviour**: 
Expected to keep it up outside of combat

**Server Revision**: 
2256

**Comment by Evolvee** [comment]
rev DDF
