### ISSUE TITLE
[NPC] Wounded Blood Elf Pilgrim

### ISSUE THREAD

**Issue by Galawer** [Atlantiss/NetherwingBugtracker#2395]
**Description**: 
[Wounded Blood Elf Pilgrim](https://www.wowhead.com/npc=16993/wounded-blood-elf-pilgrim) offering the quest [The Road to Falcon Watch](https://www.wowhead.com/quest=9375/the-road-to-falcon-watch).

**Current behaviour**:
NPC doesn't respawn or doesn't spawn at all. I've waited about half an hour.

**Expected behaviour**: 
Wowhead comments say:

> Has a spawntimer of 1-2 seconds.

**Server Revision**: 
2256

**Comment by aresbrutus** [comment]
Fixed in rev `Eris`

**Comment by knasen88** [comment]
doesn't work 
same error, she gets stuck in town after someone completes it and doesn't respawn
https://i.imgur.com/lfYnOOw.jpg
https://i.imgur.com/AaCjfHR.png

**Comment by fantom8** [comment]
Confirmed knasen88's report.
