### ISSUE TITLE
[Misc][NPC]Firewing Warlock#16769 should "attempts to run away in fear!" at low health.

### ISSUE THREAD

**Issue by Tenoutoften** [Atlantiss/NetherwingBugtracker#2396]
**Description**: 
[[NPC]Firewing Warlock#16769](https://www.wowhead.com/npc=16769/firewing-warlock#comments) should "attempts to run away in fear!" at low health.
Can be seen [here](https://youtu.be/LJ83I78ymPQ?t=368)

**Current behaviour**:
Doesn't

**Server Revision**: 
2256

**Comment by Evolvee** [comment]
rev dsa
