### ISSUE TITLE
[NPC]Infested Root-Walker#22095's [Spell]Regrowth#39000 heals about double intended amount

### ISSUE THREAD

**Issue by Tenoutoften** [Atlantiss/NetherwingBugtracker#2397]
**Description**: 
[[NPC]Infested Root-Walker#22095](https://www.wowhead.com/npc=22095/infested-root-walker#comments)'s [[Spell]Regrowth#39000](https://www.wowhead.com/spell=39000/regrowth) heals too much:
![2594de54901b94854429bf1d4b15d794](https://user-images.githubusercontent.com/34839199/48090211-9ad2fd80-e206-11e8-8309-07cdf2e5f460.png)
![a8bb8d295ab282bb200e3dfce2ba0289](https://user-images.githubusercontent.com/34839199/48090212-9b6b9400-e206-11e8-9909-eadc0cb9f812.png)
![d17c3dbfad64e9cdb0fb0014b1a369ee](https://user-images.githubusercontent.com/34839199/48090216-9d355780-e206-11e8-8b1d-09d8011c5037.png)

A regrowth doing 2600 is higher than the base value of a wrath druid's[[Spell]Regrowth(Rank12)#48443](https://wotlk-twinhead.twinstar.cz/?spell=48443) ~2234-2495

**Current behaviour**:

**Expected behaviour**: 
I'd expect it to heal about the same as a regular [[Spell]Regrowth(Rank 10)#26980](https://db.excalibur.ws/?spell=26980) from a druid, which is learned at 65.
[NPC]Infested Root-Walker#22095](https://www.wowhead.com/npc=22095/infested-root-walker#comments) level range is 64-65 so something along the lines of **~1215-1355 with a 1274 Healing over time.** 

**Server Revision**: 
2256

**Comment by Evolvee** [comment]
npcs dont use abilities of players
