### ISSUE TITLE
[NPC]Feralfen Druid#20270's [Spell]Regrowth#16561 looks too strong

### ISSUE THREAD

**Issue by Tenoutoften** [Atlantiss/NetherwingBugtracker#2398]
**Description**: 
[[NPC]Feralfen Druid#20270](https://www.wowhead.com/npc=20270/feralfen-druid#comments)'s [[Spell]Regrowth#16561](https://www.wowhead.com/spell=16561/regrowth) seems too strong
![2fb9f7cb31a29b45b71e78c229572980](https://user-images.githubusercontent.com/34839199/48091026-ce168c00-e208-11e8-85bf-0a4f21eedabf.png)
![d6af805d2146339d809d398898e9d1e6](https://user-images.githubusercontent.com/34839199/48091027-ce168c00-e208-11e8-8000-3e6b001d8d2b.png)
[[NPC]Feralfen Druid#20270](https://www.wowhead.com/npc=20270/feralfen-druid#comments) is strictly level 62

---

Previously reported the [[Spell]Regrowth#39000](https://www.wowhead.com/spell=39000/regrowth) of  [[NPC]Infested Root-Walker#22095](https://www.wowhead.com/npc=22095/infested-root-walker#comments)  https://github.com/Atlantiss/NetherwingBugtracker/issues/2397

**Expected behaviour**:
This value makes more sense ~1050-1150 with additional 1100 over 21 sec.

**Server Revision**: 
2256

**Comment by Evolvee** [comment]
proof?

the spell ID is the same as on wowhead and in sniffs

**Comment by Tenoutoften** [comment]
I have watched about 4 retail videos now, and the only cast I can find so far is this one: https://youtu.be/4QBOS_FojGo?t=58

You barely see the health change

**Comment by Evolvee** [comment]
all spells use the same formula, it cant scale badly if others dont as well

**Comment by Tenoutoften** [comment]
It seems strange that this guy would say they heal 1-3k, when this mob always heals: 
 ~2500 flat
 +2450 over time(7*350) 
=~5000
![d17c3dbfad64e9cdb0fb0014b1a369ee](https://user-images.githubusercontent.com/34839199/48090216-9d355780-e206-11e8-8b1d-09d8011c5037.png)

**Comment by Evolvee** [comment]
rev cd
