### ISSUE TITLE
[Misc][NPC]Cabal Spell-weaver#21902 should "attempts to run away in fear!"

### ISSUE THREAD

**Issue by Tenoutoften** [Atlantiss/NetherwingBugtracker#2399]
**Description**: 
[[NPC]Cabal Spell-weaver#21902](https://www.wowhead.com/npc=21902/cabal-spell-weaver) should "attempts to run away in fear!"
Can be seen [here](https://youtu.be/UvQKx_3oJr8?t=42)

**Current behaviour**:
Doesn't

**Expected behaviour**: 
Should "attempts to run away in fear!" at low health.

**Server Revision**: 
2256

**Comment by Evolvee** [comment]
rev DDF
