### ISSUE TITLE
Blood elf treants respawn

### ISSUE THREAD

**Issue by AlteredAli** [Atlantiss/NetherwingBugtracker#24]
[//]: # (Enclose links to things related to the bug using http://wowhead.com or any other TBC database.)
[//]: # (You can use screenshot ingame to visual the issue.)
[//]: # (Write your tickets according to the format:)
[//]: # ([Quest][Azuremyst Isle] Red Snapper - Very Tasty!)
[//]: # ([NPC] Magistrix Erona)
[//]: # ([Spell][Mage] Fireball)
[//]: # ([Npc][Drop] Ghostclaw Lynx)
[//]: # ([Web] Armory doesnt work)

**Description**: 
Same thing as grell's in the night elf starting area
**Current behaviour**:

**Expected behaviour**: 

**Server Revision**:

**Comment by aresbrutus** [comment]
Thank you for your report. 

This will be corrected ASAP.
