### ISSUE TITLE
[Pet] Voidwalker - Missing Name

### ISSUE THREAD

**Issue by Scylla420** [Atlantiss/NetherwingBugtracker#240]
**Description**: 
My Voidwalker currently has no nickname and is simply called "Voidwalker".  Summoning a new Voidwalker gives it the name "Unknown" but if I log out and back in then it's back to just "Voidwalker". Other warlocks seem to have a nickname just fine so I'm not sure what happened to mine.
**Current behaviour**:
[Voidwalker](https://cdn.discordapp.com/attachments/372465548950241280/493475787748671500/unknown.png)
[Unknown](https://prnt.sc/kxrs20)
**Expected behaviour**: 
My VW should have a nickname such as "Juk'gak"
**Server Revision**: 
2028

**Comment by The14me** [comment]
Work fine to me.Please re-open if happen again.
