### ISSUE TITLE
2 food buffs possible

### ISSUE THREAD

**Issue by Defgha** [Atlantiss/NetherwingBugtracker#2400]
**Description**: 
You can have 2 active food buffs, I used Dried Fruit Rations and Helboar Bacon, both buffs applied.

**Current behaviour**:
See above

**Expected behaviour**: 
Only 1 food buff active

**Server Revision**:

**Comment by Easyfraggy** [comment]
We are reworking buff stacking, atm some things stack that shouldn't and vice versa.

**Comment by Defgha** [comment]
issue seems to be Druid fruit, not labeled as food buff

**Comment by Manaci** [comment]
Fixed
