### ISSUE TITLE
[Quest] Scratches

### ISSUE THREAD

**Issue by Mewmewww** [Atlantiss/NetherwingBugtracker#2401]
[//]: # (Enclose links to things related to the bug using http://wowhead.com or any other TBC database.)
[//]: # (You can use screenshot ingame to visual the issue.)
[//]: # (Write your tickets according to the format:)
[//]: # ([Quest][Azuremyst Isle] Red Snapper - Very Tasty!)
[//]: # ([NPC] Magistrix Erona)
[//]: # ([Spell][Mage] Fireball)
[//]: # ([Npc][Drop] Ghostclaw Lynx)
[//]: # ([Web] Armory doesnt work)

**Description**: 
Kaliri Totem quest gives credit too fast and Bird doesn't despawn.
**Current behaviour**:
Currently, once you enter Sylvanaar you get credit from the quest. However, you need to let Daranelle to perform some magic spell or some shit to analyse the bird, which doesnt happen. And since this doesn't happen, the bird stays on you permanently.
**Expected behaviour**: 
However, you need to let Daranelle to perform some magic spell or some shit to analyse it (which in turn despawns the bird)
**Server Revision**: 
2256

**Comment by aresbrutus** [comment]
https://github.com/Atlantiss/AtlantissTBCBT/issues/3098

**Comment by Evolvee** [comment]
rev 2500
