### ISSUE TITLE
[Spell] Drunken Haze [NPC] Bloodmaul Brewmaster

### ISSUE THREAD

**Issue by Mewmewww** [Atlantiss/NetherwingBugtracker#2402]
[//]: # (Enclose links to things related to the bug using http://wowhead.com or any other TBC database.)
[//]: # (You can use screenshot ingame to visual the issue.)
[//]: # (Write your tickets according to the format:)
[//]: # ([Quest][Azuremyst Isle] Red Snapper - Very Tasty!)
[//]: # ([NPC] Magistrix Erona)
[//]: # ([Spell][Mage] Fireball)
[//]: # ([Npc][Drop] Ghostclaw Lynx)
[//]: # ([Web] Armory doesnt work)

**Description**: 
Drunken Haze
**Current behaviour**:
Doesn't give off the drunken blurscreen when used. https://www.wowhead.com/spell=37591/drunken-haze#comments
**Expected behaviour**: 
Should be completely smashed as the text says.
**Server Revision**: 
2256

**Comment by ScottieDOESknow** [comment]
Was working for me a couple days ago when questing.
Also working for me as of right now.

https://gyazo.com/35fc7c6bf490f1c7c8f2a986b04a8916

**Comment by ScottieDOESknow** [comment]
working for me previously when questing and currently 

https://gyazo.com/35fc7c6bf490f1c7c8f2a986b04a8916

**Comment by Mewmewww** [comment]
oh, cool to know lol :D
