### ISSUE TITLE
[NPC] Vindicator Haylen

### ISSUE THREAD

**Issue by Kidcudi123** [Atlantiss/NetherwingBugtracker#2403]
![image](https://user-images.githubusercontent.com/33790123/48097938-8d743e00-e21b-11e8-9923-89dee4ba1c86.png)

This questgiver's currently dying to a tree
Somebody save him

Expected Behaviour: Slightly move the mobs away from him

**Comment by aresbrutus** [comment]
Fixed in rev `Vesta`
