### ISSUE TITLE
Ruthless Cunning [Quest] Planting a banner is bugged

### ISSUE THREAD

**Issue by mhdemn** [Atlantiss/NetherwingBugtracker#2404]
**Description**: When you plant a [banner](https://tbc-twinhead.twinstar.cz/?item=25552) during this [quest](https://tbc-twinhead.twinstar.cz/?quest=9927) only the player planting [gets credit](https://youtu.be/W5hmRxnD-kI).

**Current behaviour**: Planting a banner gives credit to the player only.

**Expected behaviour**: Planting a banner gives credit to every player in party. I'm basing myself in this [comment](https://www.wowhead.com/quest=9927/ruthless-cunning) I saw on wowhead from user Paratus:

![image](https://user-images.githubusercontent.com/25901582/48100352-2ce8ff00-e223-11e8-9ed4-2dfbb765981e.png)

**Server Revision**: 2256

**Comment by mhdemn** [comment]
Also:
You can plant the flags on corpses with loot inside, which can result in loss of valuable loot that's being rolled for.

Sometimes the physical flag that appears won't appear.

Sidenote, in retail [bodies don't even disappear](https://www.youtube.com/watch?v=-87p0W9eXqw) as they do once you plant the flag.

**Comment by mhdemn** [comment]
Also, I know I should open a new ticket but in this quest [Body of Evidence](https://tbc-twinhead.twinstar.cz/?quest=9931), even though the event, dialogues and stuff works just fine, first time I did it carbonite said it got completed as soon as the ogres spawned and started their rp walk, but it didn't. I found out it wasn't complete in the NPC though, after abandoning and repicking I could complete it normally when they finish their speech.

**Comment by Wolffenstein** [comment]
Fixed in rev 3469.
