### ISSUE TITLE
[Quest][Hellfire Peninsula] Natural Remedies

### ISSUE THREAD

**Issue by maxturtlesc2** [Atlantiss/NetherwingBugtracker#2405]
[//]: # (Enclose links to things related to the bug using http://wowhead.com or any other TBC database.)
[//]: # (You can use screenshot ingame to visual the issue.)
[//]: # (Write your tickets according to the format:)
[//]: # ([Quest][Azuremyst Isle] Red Snapper - Very Tasty!)
[//]: # ([NPC] Magistrix Erona)
[//]: # ([Spell][Mage] Fireball)
[//]: # ([Npc][Drop] Ghostclaw Lynx)
[//]: # ([Web] Armory doesnt work)

**Description**: 

**Current behaviour**:
Seed of Revitalization (item provided to summon the mob) only works once. If you fail on your first try, you can't summon the mob another time.
**Expected behaviour**: 
Seed of Revitalization should be able to summon as long as the quest is not completed.
**Server Revision**:

**Comment by Tenoutoften** [comment]
Doesn't disappear from [this guy](https://www.youtube.com/watch?v=iGrljCsdOy4) doing the quest, but it is from 2013 dec...

**Comment by maxturtlesc2** [comment]
If I remember correctly the item quest didn't disappear after I used it, but I couldn't make it work again when I tried to use it after failing once: the summoning wasn't starting again. It's like the item had only one charge.

**Comment by Manaci** [comment]
Fixed in rev 3134
