### ISSUE TITLE
[NPC] [Shadowmoon Valley] Envoy Icarius trigger is visible

### ISSUE THREAD

**Issue by ScottieDOESknow** [Atlantiss/NetherwingBugtracker#2406]
**Description**: Envoy Icarius spawns during quest 'To Catch a Thistlehead'

**Current behaviour**: trigger to spawn NPC is visible even when not on the quest (before or after)

trigger
https://gyazo.com/fcba7eaf5248824ced244a659aa55b68

ID
https://gyazo.com/897b1d4d30c530db5e5a8d7dc2c551c6

**Expected behaviour**: trigger should not be visible to anyone

**Server Revision**: 2256

**Comment by aresbrutus** [comment]
https://github.com/Atlantiss/AtlantissTBCBT/issues/4144

**Comment by Bildo** [comment]
fixed in rev 2410
