### ISSUE TITLE
Auchenai ghosts

### ISSUE THREAD

**Issue by craigsurbrook** [Atlantiss/NetherwingBugtracker#2407]
[//]: # (Enclose links to things related to the bug using http://wowhead.com or any other TBC database.)
[//]: # (You can use screenshot ingame to visual the issue.)
[//]: # (Write your tickets according to the format:)
[//]: # ([Quest][Azuremyst Isle] Red Snapper - Very Tasty!)
[//]: # ([NPC] Magistrix Erona)
[//]: # ([Spell][Mage] Fireball)
[//]: # ([Npc][Drop] Ghostclaw Lynx)
[//]: # ([Web] Armory doesnt work)

**Description**: 
The untargetable ghosts that walk near Auchenai are basically stationary, and just walk a bit like reg mobs do around their centroid.
I realize this is quite minor, but seemed to me back in the day to create quite the atmosphere of importance of doing these quests for the Dranei.

**Current behaviour**:
The untargetable ghosts are basically stationary.

**Expected behaviour**: 
In retail, the untargetable ghosts would "stream" (walk) towards the Auchenai arena, and then would despawn as they reached it, and new ones would spawn in and keep walking toward the arena. This gave the impression ingame that that the Dranei spirits were being stolen/not allowed to rest, and that the quests you were doing were "saving" their souls. It left quite an impression on me back in the day, making one feel a sense of urgency - whereas now, with them basically stationary, you don't get that sense at all.

**Server Revision**: 
2256

**Comment by Evolvee** [comment]
Duplicate
