### ISSUE TITLE
[Misc][NPC]Cabal Initiate#21907 should "becomes enraged!"

### ISSUE THREAD

**Issue by Tenoutoften** [Atlantiss/NetherwingBugtracker#2408]
**Description**: 
[[NPC]Cabal Initiate#21907](https://www.wowhead.com/npc=21907/cabal-initiate#comments) should "becomes enraged!" rather than "goes into a frenzy!"
Can be seen [here](https://youtu.be/UvQKx_3oJr8?t=89)
![26782b10571dc2224257333a85ff6bd6](https://user-images.githubusercontent.com/34839199/48121222-a230f000-e274-11e8-9e5a-074511032fd5.png)

**Current behaviour**:
"goes into a frenzy!"

**Expected behaviour**: 
"becomes enraged!"

**Server Revision**: 
2256

**Comment by Tenoutoften** [comment]
It becomes enraged, with enrage spell, it just says it goes into frenzy

**Comment by Evolvee** [comment]
rev DDF
