### ISSUE TITLE
Libram of Saints Departed (item=24386)

### ISSUE THREAD

**Issue by Novat93** [Atlantiss/NetherwingBugtracker#2409]
[//]: # (Enclose links to things related to the bug using http://wowhead.com or any other TBC database.)
[//]: # (You can use screenshot ingame to visual the issue.)
[//]: # (Write your tickets according to the format:)
[//]: # ([Quest][Azuremyst Isle] Red Snapper - Very Tasty!)
[//]: # ([NPC] Magistrix Erona)
[//]: # ([Spell][Mage] Fireball)
[//]: # ([Npc][Drop] Ghostclaw Lynx)
[//]: # ([Web] Armory doesnt work)

**Description**: Having the libram equipped does not seem to heal the paladin when judgement is cast.
item=24386 - Libram of Saints Departed

**Current behaviour**: Casting judgement does not heal the paladin

**Expected behaviour**: Whenever judgement is cast, the paladin should be healed for the amount stated on the item text.

**Server Revision**: 2256

![libram](https://user-images.githubusercontent.com/36829235/48121348-f9cf5b80-e274-11e8-9c2d-b30a472bda9f.PNG)

**Comment by Novat93** [comment]
The issue may affect other librams triggered by judgement as well. For obvious reasons, i have not been able to test any other librams.

**Comment by Easyfraggy** [comment]
If you want to test the other librams poke me on discord on user Easy - Post me names/item ID of the librams you want.

**Comment by paoea** [comment]
this bug is still active

**Comment by Evolvee** [comment]
fixed in rev 2988
