### ISSUE TITLE
[Misc][NPC]Shimmerscale Eel#18750 gives full xp, should give 50-10% xp

### ISSUE THREAD

**Issue by Tenoutoften** [Atlantiss/NetherwingBugtracker#2410]
**Description**: 
[[NPC]Shimmerscale Eel#18750](https://www.wowhead.com/npc=18750/shimmerscale-eel#comments) is currently granting full regular mob xp. It should probably give less, considering it has half the health of a regular mob. On Retail it's giving just 10% of a regular mob, that's a bit low imo, though.
Can be seen killed [here](https://youtu.be/hvysEEOo3A4?t=87)

**Expected behaviour**: 
50% xp or lower.

**Server Revision**: 
2256

**Comment by Evolvee** [comment]
rev DDF
