### ISSUE TITLE
[Misc][NPC]Cabal Abjurist#21660 should "attempts to run away in fear!"

### ISSUE THREAD

**Issue by Tenoutoften** [Atlantiss/NetherwingBugtracker#2411]
**Description**: 
[[NPC]Cabal Abjurist#21660](https://www.wowhead.com/npc=21660/cabal-abjurist#comments) should "attempts to run away in fear!"
Can be seen [here](https://youtu.be/KR1zXROmzx0?t=93) and [here](https://youtu.be/2WurwPD1ui0?t=325)

**Current behaviour**:
Doesn't

**Expected behaviour**: 
Should "attempts to run away in fear!"

**Server Revision**: 
2256

**Comment by Evolvee** [comment]
rev DDF
