### ISSUE TITLE
Seal of the crusader

### ISSUE THREAD

**Issue by Novat93** [Atlantiss/NetherwingBugtracker#2412]
[//]: # (Enclose links to things related to the bug using http://wowhead.com or any other TBC database.)
[//]: # (You can use screenshot ingame to visual the issue.)
[//]: # (Write your tickets according to the format:)
[//]: # ([Quest][Azuremyst Isle] Red Snapper - Very Tasty!)
[//]: # ([NPC] Magistrix Erona)
[//]: # ([Spell][Mage] Fireball)
[//]: # ([Npc][Drop] Ghostclaw Lynx)
[//]: # ([Web] Armory doesnt work)

**Description**: Applying the seal of the crusader seal, does not seem to increase the damage of Crusader Strike, as stated in the official 2.4.2 patch notes.
http://wowwiki.wikia.com/wiki/Patch_2.4.2

''Seal of the Crusader: This ability now increases the damage dealt by Crusader Strike by 40%.''

**Current behaviour**: Regardless of which seal is applied to the paladin. Crusader strike will deal 110% of the damage, as stated on the character stat card.

**Expected behaviour**: Whenever seal of the crusader is applied. The Crusader Strike ability should deal an additional 40% damage, to offset the raw damage per hit lost when applying the seal. So that the Crusader strike ability should deal roughly the same amount of damage, regardless of which seal is applied.

**Server Revision**: 
2256

**Comment by Wolffenstein** [comment]
Fixed in rev 2264.
