### ISSUE TITLE
[Misc][NPC]Succubus Minion#10928 100% regular mob xp rather than 50%

### ISSUE THREAD

**Issue by Tenoutoften** [Atlantiss/NetherwingBugtracker#2413]
**Description**: 
[[NPC]Shadowy Summoner#17088](https://www.wowhead.com/npc=17088/shadowy-summoner#comments), among a lot of other warlock-NPCs use [[Spell]Summon Succubus#8722](https://www.wowhead.com/spell=8722/summon-succubus) to sumnmon [[NPC]Succubus Minion#10928](https://www.wowhead.com/npc=10928/succubus-minion#comments)

I previously reported that this NPC should grant experience, and it has been fixed: https://github.com/Atlantiss/NetherwingBugtracker/issues/1747, however it looks like it should only give 50% xp of a regular mob rather than full xp(current behavior) - This can be seen in the two videos I provided in that report as well:

https://www.youtube.com/watch?v=26kkq0F6n7o&feature=youtu.be&t=325
https://www.youtube.com/watch?v=gusbV3RtP44&feature=youtu.be&t=43
Can also be seen here on this specific NPC: https://youtu.be/s3U-Wvrq5hQ?t=103

**Expected behaviour**: 
50% xp rather than 100% xp of a regular mob

**Server Revision**: 
2256

**Comment by Evolvee** [comment]
rev DDF
