### ISSUE TITLE
[PvP] Flagging through heals

### ISSUE THREAD

**Issue by Tulveli** [Atlantiss/NetherwingBugtracker#2414]
**Description**:  Flagging for PvP via healing doesn't allow for objective capture.

**Current behaviour**:  When I healed a PvP flagged ally I was flagged as well (as intended), however I didn't get any quest credit for capturing the PvP objectives in Hellfire Peninsula.  I also couldn't see the capture bar progress, although my party members said that I was flagged for PvP on their screens.
When I right-clicked my portrait it said PvP was disabled, and after enabling it, I was able to capture the objectives and gain quest credit.

**Expected behaviour**:  Flagging for PvP by healing or buffing should allow for the capture of PvP objectives.

**Server Revision**:

**Comment by Evolvee** [comment]
could be caused by PVE state of realm
