### ISSUE TITLE
[Spell] Taunt

### ISSUE THREAD

**Issue by Mewmewww** [Atlantiss/NetherwingBugtracker#2418]
[//]: # (Enclose links to things related to the bug using http://wowhead.com or any other TBC database.)
[//]: # (You can use screenshot ingame to visual the issue.)
[//]: # (Write your tickets according to the format:)
[//]: # ([Quest][Azuremyst Isle] Red Snapper - Very Tasty!)
[//]: # ([NPC] Magistrix Erona)
[//]: # ([Spell][Mage] Fireball)
[//]: # ([Npc][Drop] Ghostclaw Lynx)
[//]: # ([Web] Armory doesnt work)

**Description**: 
Taunting hunter pets.
**Current behaviour**:
Taunting doesn't force hunter pets to attack the warrior.
**Expected behaviour**: 
Taunting should force hunter pets to attack the warrior
**Server Revision**: 
2256

**Comment by Easyfraggy** [comment]
Can you supply some proof that taunt should work on pets?

**Comment by Mewmewww** [comment]
This is a very common and very highly beneficial mechanic in PvP. 
https://us.battle.net/forums/en/wow/topic/20750274874
https://www.youtube.com/watch?v=64_TAuCJ5y8
https://www.wowhead.com/forums&topic=114316
http://www.arenajunkies.com/topic/159066-taunt-pet-macro/

tell me if you need more

**Comment by bloodwindz** [comment]
https://www.youtube.com/watch?v=g-ZOluGhMoA&t=2s

3.08 in the vid

**Comment by bloodwindz** [comment]
this is  high priority and its a basic and important pvp mechanic

**Comment by femdead** [comment]
still not working

**Comment by Regimant** [comment]
still not working

**Comment by jasonbourne109** [comment]
I came here to report this same bug. All forms of taunt (Druid's Growl, Warrior's Taunt, Paladin's Righteous Defense) should work on Hunter pets. This is extremely important for Warriors and Druids in PvP.

Currently, when taunt is used on a pet, the spell is triggered and the pet is affected by the taunt debuff (correct), but the pet does not change targets (incorrect).

**Comment by Wolffenstein** [comment]
Fixed in rev 3059.
