### ISSUE TITLE
[Auras] [Paladin] Dosent reset upon dying

### ISSUE THREAD

**Issue by Gedlund** [Atlantiss/NetherwingBugtracker#242]
[//]: # (Enclose links to things related to the bug using http://wowhead.com or any other TBC database.)
[//]: # (You can use screenshot ingame to visual the issue.)
[//]: # (Write your tickets according to the format:)
[//]: # ([Quest][Azuremyst Isle] Red Snapper - Very Tasty!)
[//]: # ([NPC] Magistrix Erona)
[//]: # ([Spell][Mage] Fireball)
[//]: # ([Npc][Drop] Ghostclaw Lynx)
[//]: # ([Web] Armory doesnt work)

**Description**: 
Paladins auras are supposed to go back to being inactive once a player dies.

**Current behaviour**:
Paladin auras are still cast and appear as a 0 second buff instead of a always buff icon does also not apply the armor.

**Expected behaviour**: 
Paladins have to recast their auras when reviving as it has been deactivated by dying. 

**Server Revision**:

**Comment by wtRCH** [comment]
Happens not only to the auras but every permanent buff. Happened to me twice and I am not using any buff addon or stuff.

**Comment by Wolffenstein** [comment]
Fixed
