### ISSUE TITLE
[Misc][NPC]Skithian Dreadhawk#18452 shouldn't attempts to flee away in fear!"

### ISSUE THREAD

**Issue by Tenoutoften** [Atlantiss/NetherwingBugtracker#2420]
**Description**: 
[[NPC]Skithian Dreadhawk#18452](https://www.wowhead.com/npc=18452/skithian-dreadhawk) is currently "attempts to flee away in fear!" but shouldn't:

https://youtu.be/3iHpcxqTdcc?t=27
https://youtu.be/3iHpcxqTdcc?t=36
https://youtu.be/3iHpcxqTdcc?t=66
https://youtu.be/3iHpcxqTdcc?t=76
https://youtu.be/3iHpcxqTdcc?t=111
https://youtu.be/3iHpcxqTdcc?t=166
https://youtu.be/MkuEP18Xn8w?t=90
https://youtu.be/MkuEP18Xn8w?t=104
https://youtu.be/MkuEP18Xn8w?t=128
https://youtu.be/MkuEP18Xn8w?t=141
https://youtu.be/MkuEP18Xn8w?t=240

I have watched more videos than these two and never seen it flee or in the text.

**Expected behaviour**: 
Expected to not "attempts to flee away in fear!"

**Server Revision**: 
2256

**Comment by Evolvee** [comment]
rev DDF
