### ISSUE TITLE
[Quest] Getting The Bladespire Tanked.

### ISSUE THREAD

**Issue by Mewmewww** [Atlantiss/NetherwingBugtracker#2425]
[//]: # (Enclose links to things related to the bug using http://wowhead.com or any other TBC database.)
[//]: # (You can use screenshot ingame to visual the issue.)
[//]: # (Write your tickets according to the format:)
[//]: # ([Quest][Azuremyst Isle] Red Snapper - Very Tasty!)
[//]: # ([NPC] Magistrix Erona)
[//]: # ([Spell][Mage] Fireball)
[//]: # ([Npc][Drop] Ghostclaw Lynx)
[//]: # ([Web] Armory doesnt work)

**Description**: 
Making them drunk.
**Current behaviour**:
Currently if you bait them to drink, they'll go to drink but if you engage them while drinking and when they get the debuff that they're intoxicated, they'll reset.
**Expected behaviour**: 
Shouldn't expect to reset.
**Server Revision**: 
2256

**Comment by Tereneckla** [comment]
Fixed
