### ISSUE TITLE
[PVP] hunter's pet attacking with both PvP mode's off

### ISSUE THREAD

**Issue by shockave** [Atlantiss/NetherwingBugtracker#2426]
**Description**: 
Ally's hunter pet attacking horde player with both PvP disabled.
**Current behaviour**:
Hunter's pet attacked me(with PvP disabled) when i walked past it.
https://imgur.com/NbDqTq4
**Expected behaviour**: 
Pet should not aggro when PvP is disabled.
**Server Revision**:

**Comment by Manaci** [comment]
PvP Server?
