### ISSUE TITLE
[NPC] Gorr'Dim [Quest] Gorr'Dim Your Time Has Come

### ISSUE THREAD

**Issue by Mewmewww** [Atlantiss/NetherwingBugtracker#2427]
[//]: # (Enclose links to things related to the bug using http://wowhead.com or any other TBC database.)
[//]: # (You can use screenshot ingame to visual the issue.)
[//]: # (Write your tickets according to the format:)
[//]: # ([Quest][Azuremyst Isle] Red Snapper - Very Tasty!)
[//]: # ([NPC] Magistrix Erona)
[//]: # ([Spell][Mage] Fireball)
[//]: # ([Npc][Drop] Ghostclaw Lynx)
[//]: # ([Web] Armory doesnt work)

**Description**: 
Range pulling
**Current behaviour**:
You actaully don't need alcohol to bait him away from sober guards. Seems like they aren't linked.
**Expected behaviour**: 
Guards should be linked with Gorr'Dim if pulled with traditional means.
**Server Revision**: 
2256

**Comment by Easyfraggy** [comment]
https://github.com/Atlantiss/NetherwingBugtracker/issues/2209
