### ISSUE TITLE
[NPC] Rip-Blade Ravager

### ISSUE THREAD

**Issue by Mewmewww** [Atlantiss/NetherwingBugtracker#2428]
[//]: # (Enclose links to things related to the bug using http://wowhead.com or any other TBC database.)
[//]: # (You can use screenshot ingame to visual the issue.)
[//]: # (Write your tickets according to the format:)
[//]: # ([Quest][Azuremyst Isle] Red Snapper - Very Tasty!)
[//]: # ([NPC] Magistrix Erona)
[//]: # ([Spell][Mage] Fireball)
[//]: # ([Npc][Drop] Ghostclaw Lynx)
[//]: # ([Web] Armory doesnt work)

**Description**: 
In Skald in BeM
**Current behaviour**:
He is currently at the very north of Bem. Should only be near Toshley station. (Entry: 22123, Id: 20)
**Expected behavior
Should only be near Toshley station.
**Server Revision**: 
2256

**Comment by Evolvee** [comment]
fixed in next rev
