### ISSUE TITLE
[Quest] From the Ashes

### ISSUE THREAD

**Issue by Mewmewww** [Atlantiss/NetherwingBugtracker#2429]
[//]: # (Enclose links to things related to the bug using http://wowhead.com or any other TBC database.)
[//]: # (You can use screenshot ingame to visual the issue.)
[//]: # (Write your tickets according to the format:)
[//]: # ([Quest][Azuremyst Isle] Red Snapper - Very Tasty!)
[//]: # ([NPC] Magistrix Erona)
[//]: # ([Spell][Mage] Fireball)
[//]: # ([Npc][Drop] Ghostclaw Lynx)
[//]: # ([Web] Armory doesnt work)

**Description**: 
You plant a seed (gachiGASM) and a forest should appear.
**Current behaviour**:
You plant a seed and only a tree appears.
**Expected behaviour**: 
You plant the seed and a forest should appear. https://www.youtube.com/watch?v=HmmPS5IW84Y
**Server Revision**: 
2256

**Comment by aresbrutus** [comment]
https://github.com/Atlantiss/AtlantissTBCBT/issues/3112

**Comment by leeviathan** [comment]
The quest works as described with the tree growing and all that, but the respawn timer is very long, maybe around 5-10 minutes (rev. 3068)

**Comment by Manaci** [comment]
Fixed
