### ISSUE TITLE
ElvUI "Vendor Grays" not awarding value, but deleting items

### ISSUE THREAD

**Issue by jacerm** [Atlantiss/NetherwingBugtracker#243]
[//]: # (Enclose links to things related to the bug using http://wowhead.com or any other TBC database.)
[//]: # (You can use screenshot ingame to visual the issue.)
[//]: # (Write your tickets according to the format:)
[//]: # ([Quest][Azuremyst Isle] Red Snapper - Very Tasty!)
[//]: # ([NPC] Magistrix Erona)
[//]: # ([Spell][Mage] Fireball)
[//]: # ([Npc][Drop] Ghostclaw Lynx)
[//]: # ([Web] Armory doesnt work)

**Description**: ElvUI interface error

**Current behaviour**: "Vendor Grays" not awarding value, but deleting items

**Expected behaviour**: "Vendor Grays" should award value and delete items

**Server Revision**:

**Comment by Evolvee** [comment]
does this work on some other server?

Its most likely just the addon issue.

**Comment by jacerm** [comment]
Nope. It worked on Gummy and Warmane

**Comment by jacerm** [comment]
Well at least I remember it working. I went and tried on warmane again..it doesn't work there either. Feel free to close this.
