### ISSUE TITLE
[Quest][Shattrath City] What Book? I don't see any book

### ISSUE THREAD

**Issue by Mikik3jr** [Atlantiss/NetherwingBugtracker#2430]
[//]: # (Enclose links to things related to the bug using http://wowhead.com or any other TBC database.)
[//]: # (You can use screenshot ingame to visual the issue.)
[//]: # (Write your tickets according to the format:)
[//]: # ([Quest][Azuremyst Isle] Red Snapper - Very Tasty!)
[//]: # ([NPC] Magistrix Erona)
[//]: # ([Spell][Mage] Fireball)
[//]: # ([Npc][Drop] Ghostclaw Lynx)
[//]: # ([Web] Armory doesnt work)

**Description**: 
There are 3 thugs in shatt that you beat up for information. You talk to "Dirty" Larry and the event starts. If you deal enough dmg to him the event ends and you finish the quest.
https://www.wowhead.com/quest=10231/what-book-i-dont-see-any-book

**Current behaviour**:
After beating them they want back to neutral, but I stayed in combat. Even 5 minutes later I am in combat.
**Expected behaviour**: 
After finishing the event I shouldn't stay in combat,
**Server Revision**: 
2256

**Comment by mhdemn** [comment]
Also one of those quest NPCs that won't get friendly sometimes and die.

**Comment by AxeCell** [comment]
Would like to add that the NPCs will constantly switch between hostile and neutral when you've brought "Dirty" Larry down to the required health percentage until they're back in their original position.

**Comment by Evolvee** [comment]
reworked in 2966
