### ISSUE TITLE
[Quest] Patience and Understanding

### ISSUE THREAD

**Issue by mhdemn** [Atlantiss/NetherwingBugtracker#2431]
**Description**: [Sal'Salabim](https://tbc-twinhead.twinstar.cz/?npc=18584) turns hostile after clicking it's dialogue option, you fight him until a certain hp threshold and he turns friendly and you can complete the [quest](https://tbc-twinhead.twinstar.cz/?quest=10004) by talking to him.

**Current behaviour**: He doesn't always turn friendly (guessing it's like the many other friendly-hostile turning quest npcs), we could kill him without him giving any signal of phasing.

![image](https://user-images.githubusercontent.com/25901582/48141105-70d31700-e2aa-11e8-8ee9-382b81cffc7a.png)

**Expected behaviour**: He turns [friendly and available for quest turn-in at low HP and walks back to his position](https://gyazo.com/a58216138cb67940f10ede6bda0b96ba). Will try to find the exact amount from a reliable source, but would say it's 1hp since it doesn't look like the detail they change from xpac to xpac, specially when they [keep it as elite](https://www.youtube.com/watch?v=Gz5cOxtvQks) (even though he's weaker than a rabbit in retail).

**Server Revision**: 2256

Edit: Yeah, 2nd try he turned friendly at 6%. Didn't do anything different, just facerolled keyboard but he did this time. Also gets you stuck in combat.

**Comment by mhdemn** [comment]
Follow up quest [Crackin' Some Skulls](https://tbc-twinhead.twinstar.cz/?quest=10009), which consists in the same kind of NPCs have the same issues. 

Here's a list of related issues (about quests with buggy friendly-hostile NPCs you gotta beat up to make 'em yield)
#2089 
#2224 
#2102 
#2430

**Comment by Manaci** [comment]
Fixed

**Comment by The14me** [comment]
Its bugged again
For some reason, Sal'salabim don't reset after quest complete so the next player sees the mob already ''tagged'' and cant start the fight.

**Comment by Wolffenstein** [comment]
Fixed in rev 3388.
