### ISSUE TITLE
[NPC][Ashenvale] Ashenvale Outrunner

### ISSUE THREAD

**Issue by totaemoeggerli** [Atlantiss/NetherwingBugtracker#2432]
[//]: # (Enclose links to things related to the bug using http://wowhead.com or any other TBC database.)
[//]: # (You can use screenshot ingame to visual the issue.)
[//]: # (Write your tickets according to the format:)
[//]: # ([Quest][Azuremyst Isle] Red Snapper - Very Tasty!)
[//]: # ([NPC] Magistrix Erona)
[//]: # ([Spell][Mage] Fireball)
[//]: # ([Npc][Drop] Ghostclaw Lynx)
[//]: # ([Web] Armory doesnt work)

**Description**: 
[Ashenvale Outrunner](https://www.wowhead.com/npc=12856/ashenvale-outrunner)

**Current behaviour**:
https://gfycat.com/FinishedFlashyGosling
NPC uses its 2sec stun too often. Didn't find any comment on wowhead but 2sec every 5sec is too often.

**Expected behaviour**:
didn't find any info on how long the CD should be

**Server Revision**: 2256

**Comment by ahlens** [comment]
Many "interruption" spells are used quite often by mobs. I have no evidences how it should work so I haven't reported that. For example there are places where you are literally disarmed during the whole fight.

**Comment by Easyfraggy** [comment]
Report them .npc info and add entry+ID.

**Comment by Evolvee** [comment]
rev DDF
