### ISSUE TITLE
[NPC][Hellfire Peninsula] Gan'arg Servant

### ISSUE THREAD

**Issue by eryczek1615** [Atlantiss/NetherwingBugtracker#2433]
**Description**: 
[Gan'arg Servant](https://www.wowhead.com/npc=16947/ganarg-servant)
![image](https://user-images.githubusercontent.com/4455568/48145924-34a4b400-e2b4-11e8-949a-e3662165019b.png)

**Current behaviour**:
One of them is in line of sight.
https://imgur.com/xoPgFHE
https://imgur.com/6aUf59y
 
**Expected behaviour**: 
Shouldn't be in line of sight.

**Server Revision**: 
2256

**Comment by Easyfraggy** [comment]
This report makes no sense. Please explain differently xD

**Comment by eryczek1615** [comment]
I can attack this NPC only by autoattack when I will try use for example Mangle or other spell " Target not in line of sight" and even this npc stands in one place and he will lose aggro after few second.

**Comment by Easyfraggy** [comment]
Thanks, probably just places inside the object - ill check it out on the weekend.

**Comment by ScottieDOESknow** [comment]
same deal - NPC info
https://gyazo.com/27b932abd61450cc5410399e5b847f5d

**Comment by The14me** [comment]
There is an issue only from this angle
https://imgur.com/a/TRyOOAR
From anywhere else, it works fine.
Rev 3451

**Comment by Wolffenstein** [comment]
Fixed in rev 3460.
