### ISSUE TITLE
[NPC][Hellfire Peninsula] Bonestripper Buzzard

### ISSUE THREAD

**Issue by shockave** [Atlantiss/NetherwingBugtracker#2434]
**Description**: 
Getting stuck in terrain
**Current behaviour**:
when patroling some of them get under textures or stuck in them(bones and hills)
**Expected behaviour**: 
NPC flying over/around textures
**Server Revision**:

**Comment by Easyfraggy** [comment]
Please do .npc info on the bugged mobs so i can locate them.

**Comment by shockave** [comment]
can not recreate it with any of the mobs in the area. Im sorry.

**Comment by Easyfraggy** [comment]
Closing for now, let me know if you find some again and do .npc info.
