### ISSUE TITLE
[Misc] [Quest] Measuring Warp Energies

### ISSUE THREAD

**Issue by Corrozus** [Atlantiss/NetherwingBugtracker#2437]
[//]: # (Enclose links to things related to the bug using http://wowhead.com or any other TBC database.)
[//]: # (You can use screenshot ingame to visual the issue.)
[//]: # (Write your tickets according to the format:)
[//]: # ([Quest][Azuremyst Isle] Red Snapper - Very Tasty!)
[//]: # ([NPC] Magistrix Erona)
[//]: # ([Spell][Mage] Fireball)
[//]: # ([Npc][Drop] Ghostclaw Lynx)
[//]: # ([Web] Armory doesnt work)

**Description**: The quest requires you to use [Warp-Attuned Orb](https://www.wowhead.com/item=29324/warp-attuned-orb) to take measures at the base of 4 different pylons. Currently you can only use the quest item at a very specific spot around the base of the pylons.

Going off an old [comment](https://web.archive.org/web/20070320175449/http://www.wowhead.com:80/?quest=10313) from march 2007, you should be able to use the quest item anywhere near the pylons and get credit.

**Current behaviour**: Only lets you use quest item at a very specific spot to get credit.

**Expected behaviour**: Should be able to use quest item in the general vicinity of the pylons to get credit.

**Server Revision**: 2256

**Comment by Wolffenstein** [comment]
Fixed in rev 3436.
