### ISSUE TITLE
"Hide Cloak" in interface doesnt work

### ISSUE THREAD

**Issue by Buskmurvel** [Atlantiss/NetherwingBugtracker#244]
Even if its checked or unchecked cloak still shows.
Havent tried with helm yet.

**Comment by Buskmurvel** [comment]
Ehm... i didn't look close enough.

The option to the left seems to work, check my image:

https://gyazo.com/5c2ff8b4d27bd1319e5c6fb89ca66f2c

**Comment by toto6** [comment]
Both options work fine for me. Are you sure it is bugged?

**Comment by Peglaa** [comment]
Works fine for me.

**Comment by toto6** [comment]
closing since no response from the author
