### ISSUE TITLE
[NPC] Terrorguards in Oshu'gun stun too frequently

### ISSUE THREAD

**Issue by mhdemn** [Atlantiss/NetherwingBugtracker#2440]
**Description**: [Terrorguards](https://tbc-twinhead.twinstar.cz/?npc=18661) use their spell [War Stomp](https://tbc-twinhead.twinstar.cz/?spell=11876) every 6 or 7 seconds, resulting in a complete drama to deal with. If you do this alone with a melee class it's p much impossible.

**Current behaviour**: [Stuns for 5 seconds every 6-7 seconds](https://youtu.be/agQ2VQBqs1U).

**Expected behaviour**: Stuns for 5 seconds with a reasonable frequence. 

**Server Revision**: 2259

**Comment by Evolvee** [comment]
rev DDF
