### ISSUE TITLE
[NPC] [Netherstorm] Rhonsus - teleporting, won't drop aggro, stuck

### ISSUE THREAD

**Issue by ScottieDOESknow** [Atlantiss/NetherwingBugtracker#2444]
**Description**: Rhonsus is objective of quest 'Master Smith Rhonsus'. When he drops below 100% HP, he yells 'calls for help' and 'makes a dash for the forge'

**Current behaviour**: 

Pulling him behind a the house next to forge made Rhonsus teleport to the forge (inside) then teleport outside. After teleporting outside he is still aggro but cannot move. Will attack if close.

location behind small house before teleport (gps data)
https://gyazo.com/0bdb8d98d33a110426ebc080c1213335

I also vanished at one point and Rhonsus bugged out again, would not drop aggro, can attack if close,  but can't move just as before. I replicated this 2 times.

Rhonsus stuck 1
https://gyazo.com/081f13d7a2e2303cb17d5b3dca29f65f
https://gyazo.com/f7e84650a2fe54a5136e82915f464694

Rhonsus stuck 2
https://gyazo.com/797728e837d3db524340a5cf7aaf1cf8

**Expected behaviour**: Rhonsus should call for help and run toward the forge, inside, aggro mobs, then run out back to player. 

**Server Revision**: 2259

**Comment by ScottieDOESknow** [comment]
Just to add... I did finish the quest (2nd try) so it's not broken. I waited for respawn to further test.

**Comment by Tenoutoften** [comment]
I didn't pull him behind the house, and he didn't teleport for me.

**Comment by Tereneckla** [comment]
Fixed
