### ISSUE TITLE
I just got attacked by two faggot draeni that werent flagged for pvp and neither was I.... so WHAT THE FUCK

### ISSUE THREAD

**Issue by mantusks** [Atlantiss/NetherwingBugtracker#2446]
[//]: # (Enclose links to things related to the bug using http://wowhead.com or any other TBC database.)
[//]: # (You can use screenshot ingame to visual the issue.)
[//]: # (Write your tickets according to the format:)
[//]: # ([Quest][Azuremyst Isle] Red Snapper - Very Tasty!)
[//]: # ([NPC] Magistrix Erona)
[//]: # ([Spell][Mage] Fireball)
[//]: # ([Npc][Drop] Ghostclaw Lynx)
[//]: # ([Web] Armory doesnt work)

**Description**: 

**Current behaviour**:

**Expected behaviour**: 

**Server Revision**:

**Comment by Mewmewww** [comment]
were they using aoe abilties?

**Comment by mantusks** [comment]
um one intro'd on me with dragon breath, idk, I was rez sick so I died after iceblock pretty fast
