### ISSUE TITLE
[NPC] [Hunter] [Pet pathing] Fey Drakes and Bladewing Bloodletters

### ISSUE THREAD

**Issue by mhdemn** [Atlantiss/NetherwingBugtracker#2448]
**Description**: [Fey Drakes](https://tbc-twinhead.twinstar.cz/?npc=20713) and [Bladewing Bloodletters](https://tbc-twinhead.twinstar.cz/?npc=21033) that are part of different quests are flying creatures.

**Current behaviour**: When you send pets against these they will find their path to it if the mob is not in combat. If it's in combat though they lose the ability to find their way to it. They can fight the mob if it's in their range though.

You can see [here](https://youtu.be/64QoUGvSdP4) the different situations, me pulling first, pet pulling first, pet losing aggro and not being able to chase the mob cause the mob is already in combat. Drakes are just the same.

**Expected behaviour**: Normal pet pathing.

**Server Revision**: 2259

**Comment by Easyfraggy** [comment]
Probably related to the mobs being "flying"

**Comment by mhdemn** [comment]
Doesn't happen with [Mature Silkwings](https://tbc-twinhead.twinstar.cz/?npc=21839) or [Silkwings](https://tbc-twinhead.twinstar.cz/?npc=21373) and these are flying too

**Comment by The14me** [comment]
Rev 3451. not an issue anymore.Pet can find the paths with no problem.
