### ISSUE TITLE
[Quest] Zeth'gor must burn

### ISSUE THREAD

**Issue by Mewmewww** [Atlantiss/NetherwingBugtracker#2449]
[//]: # (Enclose links to things related to the bug using http://wowhead.com or any other TBC database.)
[//]: # (You can use screenshot ingame to visual the issue.)
[//]: # (Write your tickets according to the format:)
[//]: # ([Quest][Azuremyst Isle] Red Snapper - Very Tasty!)
[//]: # ([NPC] Magistrix Erona)
[//]: # ([Spell][Mage] Fireball)
[//]: # ([Npc][Drop] Ghostclaw Lynx)
[//]: # ([Web] Armory doesnt work)

**Description**: 
Torches don't drop after wasting the first 5. (courtesy of dangeroso)
**Current behaviour**:
Torches don't drop after wasting the first 5.
**Expected behaviour**: 
Should continuously give torches.
**Server Revision**: 
2259

**Comment by mantusks** [comment]
I couldnt get one to drop after 3

**Comment by teddys** [comment]
the torches randomly stop dropping at some point .. had to abandon and retake only for the torches to stop dropping again when I was 3/4

**Comment by Ceago** [comment]
Confirming still not working.  Seems they just stop dropping.

**Comment by banuhl** [comment]
STILL not working… I wasted more than 1h until I finally retook the quest and after 5 Mobs I had my 4 torches -.-

**Comment by The14me** [comment]
Once u burn 2-3 buildings (before gather the other tourchs they stop dropping.
If u look all of them and then start burning it work just fine.

**Comment by Evolvee** [comment]
fixed in next rev
