### ISSUE TITLE
[Spell][Racial] Berserking doesn't increase in potency on low health.

### ISSUE THREAD

**Issue by Easyfraggy** [Atlantiss/NetherwingBugtracker#2450]
**Current behaviour**:

![image](https://user-images.githubusercontent.com/36134067/48165297-70a43d00-e2e5-11e8-8144-c43b28209b0c.png)

![image](https://user-images.githubusercontent.com/36134067/48165323-7ef25900-e2e5-11e8-819f-d2cddf553613.png)

**Expected behaviour**: 
Should increase in potency based on hp%.

![image](https://user-images.githubusercontent.com/36134067/48165357-97627380-e2e5-11e8-82fa-8b0297426308.png)

**Server Revision**: 2259

**Comment by Wolffenstein** [comment]
Fixed in rev 2265.

**Comment by wtRCH** [comment]
#2512
