### ISSUE TITLE
[Quest][Azuremyst Isle] Totem of Vark

### ISSUE THREAD

**Issue by methodicality** [Atlantiss/NetherwingBugtracker#2451]
https://www.youtube.com/watch?v=WkUpuaOb0Ek - Start at 1:15 to see proper quest mechanics.
https://www.wowhead.com/quest=9542/totem-of-vark - Many posts during TBC stating what should happen.

**Description**: After completing the Totem of Yor quest the totem then gives you the following quest "Totem of Vark". You swim out of the water, onto land, where the furbolg transforms himself and the character into panthers, then guides you to the end location of the quest.

**Current behaviour**: NPC and character do not morph into invisible panther form. The NPC disappears and character is left to run without invisible panther form.

**Expected behaviour**: NPC and character should morph into invisible panther form. NPC should guide player to end-point of quest.

**Comment by Peglaa** [comment]
what? this worked fine, how did it break

**Comment by methodicality** [comment]
No idea, first time I've ever tried it. I should've abandoned and tried again I suppose.

**Comment by Fenvarien1** [comment]
started the quest right now. the npc swims to the strand. gets his furbolg form. then talks to me and just disappered.

**Comment by WhyAintThisFixedYet** [comment]
Quest still does not work. Tried abandoning and retaking. NPC dissapears, likely turning it self into the panther and running off without you and not casting the appropriate ability on the player.

It may be because when it shifts into panther form it no longer see the player and can't target them? I'm not sure.

**Comment by Wolffenstein** [comment]
Fixed in rev 2401.
