### ISSUE TITLE
[Dungeon] Auchenai Crypts bugs

### ISSUE THREAD

**Issue by mhdemn** [Atlantiss/NetherwingBugtracker#2454]
2259

**NORMAL Auchenai Crypts**

Some NPCs with a higher level than they should have.
Unliving Stalkers ([normal](https://tbc-twinhead.twinstar.cz/?npc=18501)) ([heroic](https://tbc-twinhead.twinstar.cz/?npc=20323)) are mostly all heroic versions of the npc inside.

Heroic Stalkers have their [Viper Sting](https://tbc-twinhead.twinstar.cz/?spell=37551) waaay overtuned and drains 3k mana in one tick. Normal version Stalkers cast a normal Viper Sting.

I assume Avatar doesn't drop anything in normal mode.

Rest seems fine, including Hero of the Mag'har questchain. Please use this thread for more detailing / newfound bugs.

**Comment by Easyfraggy** [comment]
Big high prio for Crypts that is still unfixed aswell: https://github.com/Atlantiss/AtlantissTBCBT/issues/799

**Comment by mhdemn** [comment]
2304
Wanna update with another detail I've learned now that I was able to finish the instance:

The [Shadow Labyrinth Key](https://db.excalibur.ws/?item=27991) is currently a drop from [Talon King Ikiss](https://db.excalibur.ws/?npc=18473).

It should be found inside [The Talon King's Coffer](https://db.excalibur.ws/?object=187372), object that spawns in the room when Ikiss dies, and contains a copy of the key for each member of the group; just like The Scarlet Key.

**Comment by Easyfraggy** [comment]
Why do you comment that on Auchenai Crypts issue?

**Comment by mhdemn** [comment]
fuck

**Comment by Evolvee** [comment]
rev dung
