### ISSUE TITLE
[Quest] Stalk the Stalker

### ISSUE THREAD

**Issue by bekonja** [Atlantiss/NetherwingBugtracker#2456]
[//]: # (Enclose links to things related to the bug using http://wowhead.com or any other TBC database.)
[//]: # (You can use screenshot ingame to visual the issue.)
[//]: # (Write your tickets according to the format:)
[//]: # ([Quest][Azuremyst Isle] Red Snapper - Very Tasty!)
[//]: # ([NPC] Magistrix Erona)
[//]: # ([Spell][Mage] Fireball)
[//]: # ([Npc][Drop] Ghostclaw Lynx)
[//]: # ([Web] Armory doesnt work)

**Description**: Cannot pick https://db.excalibur.ws/?quest=9719 from npc. Im lvl63, Sporeggar friendly, hence should be eligible for this quest.
https://tbc-twinhead.twinstar.cz/?quest=9719 - twinstar had silmilar issue with this quest being available only to alliance players. Mabye this is the issue on your server too.

**Current behaviour**: Cannot pick [Stalk the Stalker] quest with all requirements fulfilled.

**Expected behaviour**: 

**Server Revision**: 2261

**Comment by Shanghi** [comment]
This should be fixed in revision 2333. You were right about the alliance thing!
