### ISSUE TITLE
[Quest] The Vengeful Harbinger

### ISSUE THREAD

**Issue by AxeCell** [Atlantiss/NetherwingBugtracker#2457]
**Description**:
I'll post two videos showcasing how the quest is supposed to work:
https://www.youtube.com/watch?v=J4OXliKrVco
https://www.youtube.com/watch?v=AOKItoYC-u0

**Current behaviour**:
The current quest only contains the contruct spawning and the draenei slowly moving towards it. There is no ghosts floating around the room, and the Draenei Tomb Guardian doesn't approach the Vengeful Harbinger once defeated. Once completed you'll recieve the quest objective and you can turn it in to the Draenei Ascendant(which appears to be somewhat off model wise).

**Expected behaviour**: 
As shown in the videos above.

**Server Revision**:

**Comment by aresbrutus** [comment]
https://github.com/Atlantiss/AtlantissTBCBT/issues/574

**Comment by RhadigarTV** [comment]
**Description**: Issue originally presented is still present in game.

**Server Revision**: 3483

**Comment by Godmatik** [comment]
Duplicate
https://github.com/Atlantiss/NetherwingBugtracker/issues/7425
