### ISSUE TITLE
Twilight Marauder Morna

### ISSUE THREAD

**Issue by KevinTyrrell** [Atlantiss/NetherwingBugtracker#2458]
[//]: # (Enclose links to things related to the bug using http://wowhead.com or any other TBC database.)
[//]: # (You can use screenshot ingame to visual the issue.)
[//]: # (Write your tickets according to the format:)
[//]: # ([Quest][Azuremyst Isle] Red Snapper - Very Tasty!)
[//]: # ([NPC] Magistrix Erona)
[//]: # ([Spell][Mage] Fireball)
[//]: # ([Npc][Drop] Ghostclaw Lynx)
[//]: # ([Web] Armory doesnt work)

**Description**: 
[Twitch Clip](https://clips.twitch.tv/SilkyRichBadgerRickroll)

I had a strange interaction with this patrol. 

- Twilight Marauder Morna approached the Cenarion Hold mobs and abruptly stopped. Notice she is facing forward and is mounted, but not moving. That is strange to me because I thought she keeps moving and does not stop.

- She engages combat with one of the Cenarion NPCs The other Cenarion NPCs are not tethered (bug?) and do not engage in combat. Both Morna and a Cenarion NPC dismount immediately. Neither run at each other (bug?). The other twilight marauders tethered to Morna also dismount, become in combat with the Cenarion NPC, but do not run at him (bug?).

- With no animation (bug?), Morna shoots a ranged weapon (bug? should she always shoot ranged or should she go melee?) at the Cenarion NPCs until they are dead.

- Somehow Monra becomes in-combat with the Cenarion NPCs that should be beyond her aggro distance. I don't understand how that's possible.

- Upon Eagle Eye ending, the other twilgiht marauders appear to be meleeing the Cenarion NPC from far away.

- When the last NPC dies, there seems to be some sort of desync where the server believes the Twilight Marauders are in melee range of the Cenarion NPC, because they all spring on my client towards the dead Cenarion NPC 

- Finally, combat ends and Monra mounts, but her marauders do not mount, which seems to be a bug.

Overall this was very strange and it seems like there is a lot wrong with her and the Cenarion group.

@aresbrutus 

**Server Revision**: 
2261

**Comment by aresbrutus** [comment]
Again related to formations I believe https://github.com/Atlantiss/NetherwingBugtracker/issues/826

**Comment by KevinTyrrell** [comment]
> Again related to formations I believe #826

You believe all of that interaction is due to formation related concerns?

**Comment by aresbrutus** [comment]
Maybe not all of them, but fixing formations should give us more info on what is still not working on your list.

**Comment by Godmatik** [comment]
Rev 4017 - no longer an issue

Followed Morna as she did her path, she and her pack now properly dismounts and engages the Cenarion Outriders when she encounters them. When the outriders die, they properly remount and move along their normal path.

The outriders are still bugged with their formation and not patrolling - but there is a separate github report already open about that.
