### ISSUE TITLE
[Quest] The Fel and the Furious

### ISSUE THREAD

**Issue by AxeCell** [Atlantiss/NetherwingBugtracker#2459]
**Description**: 
You'll be tasked to use a device for mind-controlling a fel reaver. You're then meant to use the fel reaver to destroy 60 infernals with one of its abilities. You'll also be fending of adds around the quest area with the other fel reaver abilities. The quets is limited to 5 minutes.

**Current behaviour**:
Attempting to destroy the infernals doesn't work. The missiles of your ability will go off, but nothing happens once they reach the infernals. The fel reaver is also quite weak in terms of fending off the adds surrounding you, but this might not be un-blizzlike.

**Expected behaviour**: 
Using the missiles on the infernals is supposed to destroy them and give you credit.

**Server Revision**:

**Comment by aresbrutus** [comment]
https://github.com/Atlantiss/AtlantissTBCBT/issues/3958

**Comment by Aquaorangez** [comment]
Still bugged. The low damage is also a bug. If you look at [this video](https://www.youtube.com/watch?v=_4YAH4_MEvU) you can see his auto attack should be doing about 8x what they are now. In addition, the fel reaver move "Sonic Boom" doesn't work at all. Uncompletable quest.

**Comment by Evolvee** [comment]
rev 2687
