### ISSUE TITLE
[Quest] Teleport This!

### ISSUE THREAD

**Issue by AxeCell** [Atlantiss/NetherwingBugtracker#2461]
**Description**: 
Nether-Stalker Nauthis wants you to use the Mental Interference Rod on the Mo'arg at Forge Base: Gehenna and use their Detonate Teleporter ability on the three teleporters in the forge camp.

**Current behaviour**:
Using the Mental Intereference Rod on a Cyber-Rage Forgelord and then casting Detonate Teleporter on the teleporter doesn't give quest credit.

**Expected behaviour**: 
Using Detonate Teleporter on a teleporter should give quest credit.

**Server Revision**:

**Comment by Evolvee** [comment]
rev dsa
