### ISSUE TITLE
[Quest] Escape from Coilskar Cistern

### ISSUE THREAD

**Issue by AxeCell** [Atlantiss/NetherwingBugtracker#2463]
**Description**: 
Escort Earthmender Wilda out of Coilskar Cistern and then seek out Earthmender Torlok at the Altar of Damnation, found at the western outskirts of the Hand of Gul'dan.

**Current behaviour**:
Once you reach Earthmender Wilda she'll already be freed from the water bubble the Coilskar Cistern is supposed to keep her in. During the escort you'll be ambushed by 1 enemy at a time and I'm unsure if there are supposed to spawn more. Once you reach the small water elementals they'll float in the air without any visual effects keeping them up. Once done with the small ambush, the water elementals wont follow Wilda and they'll remain stuck in the air. The escort can still be completed.

**Expected behaviour**: 
Earthmender Wilda is supposed to be supressed by the Coilskar Cistern(as shown at this timestamp: https://youtu.be/i_CpElkm5q4?t=114). Once reaching the water elementals, they'll be freed and will proceed to follow Earthmender Wilda until the escort is complete. If they can attack or not remains uncertain to me.

**Server Revision**:

**Comment by aresbrutus** [comment]
https://github.com/Atlantiss/AtlantissTBCBT/issues/3067

**Comment by Evolvee** [comment]
rev qwe
