### ISSUE TITLE
[NPC] Mana Wraith

### ISSUE THREAD

**Issue by AxeCell** [Atlantiss/NetherwingBugtracker#2464]
**Description**: 
Mana wraiths have the ability "Devour Mana". Post is related to this ability.

**Current behaviour**:
After casting Devour Mana, Mana Wraiths has a tendency to self-root themself. Fought them as a hunter where my pet was initially tanking them.

**Expected behaviour**: 
After casting Devour Mana they should reapproach whoever has the highest threat.

**Server Revision**:

**Comment by Tereneckla** [comment]
Fixed
