### ISSUE TITLE
[Hunter] [Traps] Frost Trap Is Unreliable

### ISSUE THREAD

**Issue by KevinTyrrell** [Atlantiss/NetherwingBugtracker#2466]
[//]: # (Enclose links to things related to the bug using http://wowhead.com or any other TBC database.)
[//]: # (You can use screenshot ingame to visual the issue.)
[//]: # (Write your tickets according to the format:)
[//]: # ([Quest][Azuremyst Isle] Red Snapper - Very Tasty!)
[//]: # ([NPC] Magistrix Erona)
[//]: # ([Spell][Mage] Fireball)
[//]: # ([Npc][Drop] Ghostclaw Lynx)
[//]: # ([Web] Armory doesnt work)

**Description**:
[Twitch Clip](https://clips.twitch.tv/BrainyBetterClintFreakinStinkin)

**Current behaviour**:
Sometimes Frost Trap seems to not apply to any or all targets. Shown above, mobs are walking through frost trap while debuffed but continue to move at regular speed.

**Expected behaviour**: 
Mobs should be slowed when entering the frost trap radius, as long as they are not immune to slows.

**Server Revision**: 
2261

**Comment by Manaci** [comment]
Fixed in rev 3214
