### ISSUE TITLE
[Quest] Bladespire Kegger - missing emotes

### ISSUE THREAD

**Issue by mhdemn** [Atlantiss/NetherwingBugtracker#2467]
**Description**: In this [quest](https://tbc-twinhead.twinstar.cz/?quest=10545) you gotta use the given [item](https://tbc-twinhead.twinstar.cz/?item=30353) to place beer mugs that will lure nearby ogres ([shamans](https://tbc-twinhead.twinstar.cz/?npc=19998), [brutes](https://tbc-twinhead.twinstar.cz/?npc=19995), [champions](https://tbc-twinhead.twinstar.cz/?npc=21296) and [cooks](https://tbc-twinhead.twinstar.cz/?npc=20334) all the same) that will drink it.

**Current behaviour**: Sometimes as seen [here](https://youtu.be/92Xpr2FqAmU) the ogres won't do the proper animations or get the debuff, even though you get credit towards completion all the same. Second clip in the video shows a nearby ogre doing the correct emotes.

**Expected behaviour**: All ogres do what the 2nd ogre in the video do.

**Server Revision**: 2261

**Comment by Tereneckla** [comment]
The ogres not standing idle don't do the proper animations.
The one doing chopping: 19995 18
https://www.youtube.com/watch?v=G2IDFtzDYh0
The one sitting: 19995 11
https://www.youtube.com/watch?v=9T8MvLktzP8

And the patrols: 19995 16, 37, 10, 26, 28, 5, 30, 32, 33, 2 and 19998 10, 3, 15
As seen in the video above.

**Comment by Godmatik** [comment]
Duplicate #4635
