### ISSUE TITLE
Missing ~2 mobs in Auchenai Grounds spot.

### ISSUE THREAD

**Issue by Tenoutoften** [Atlantiss/NetherwingBugtracker#2469]
**Description**: 
Id 2, [[NPC]Auchenai Death-speaker#21242](https://www.wowhead.com/npc=21242/auchenai-death-speaker) at 
![55b487504449478dea5bc911a6ae1552](https://user-images.githubusercontent.com/34839199/48200421-6161d580-e35f-11e8-9ca2-5db91b56b651.png)

Is standing too far north.

Looks like a few NPCs is missing in this hall: https://youtu.be/ay40u0SqpqE?t=15

**Expected behaviour**: 
Expected a few more NPCs in this hall, standing spread enough to not link. Looks like 4 NPCs(living) should be in his hall.

**Server Revision**: 
2261

**Comment by Evolvee** [comment]
the 2 npcs are blizzlike-confirmed in sniffs, you can see them in the video afterall


more npcs added @Easyfraggy this area will require sniff-treatment anyway
