### ISSUE TITLE
[NPC][Drop] Riverpaw Gnoll - 117

### ISSUE THREAD

**Issue by Scylla420** [Atlantiss/NetherwingBugtracker#247]
**Description**: 
NPC 117 - Level 11-13 Riverpaw Gnolls can currently drop Mulgore Spice Bread (item 4544), a level 25 food.
**Current behaviour**:
NPC 117 - Level 11-13 Riverpaw Gnolls can currently drop Mulgore Spice Bread (item 4544), a level 25 food.
**Expected behaviour**: 
Level 25 food should drop from higher level mobs.  [Allakhazam drop list can be found here.](https://web.archive.org/web/20080620190533/http://wow.allakhazam.com:80/db/item.html?witem=4544) [And here for the Gnoll.](https://web.archive.org/web/20080106200520/http://wow.allakhazam.com:80/db/mob.html?wmob=117)  Nothing that low is found on wowhead archives either.
**Server Revision**: 
2028

**Comment by aresbrutus** [comment]
Will be fixed in one of the next updates
