### ISSUE TITLE
[[Quest]The Fallen Exarch, wrong size on [NPC]Reanimated Exarch & slightly wrong spawn position

### ISSUE THREAD

**Issue by Tenoutoften** [Atlantiss/NetherwingBugtracker#2470]
**Description**: 
[[Quest]The Fallen Exarch#10915](https://www.wowhead.com/quest=10915/the-fallen-exarch)

[[NPC]Reanimated Exarch#22452](https://www.wowhead.com/npc=22452/reanimated-exarch#comments) looks very small on NW compared to [retail](https://youtu.be/ay40u0SqpqE?t=36)
[NW size here](https://www.youtube.com/watch?v=4JaRHAKLPi4&feature=youtu.be)

He also spawns in the wrong position, he should be further away from the Tomb. He is spawned after you open [[Object]Auchenai Coffin#184999](https://www.wowhead.com/object=184999/auchenai-coffin) at 
![coffin](https://user-images.githubusercontent.com/34839199/48201786-77719500-e363-11e8-832d-81e3cd1881d3.png)

**Expected behaviour**: 
Expected to be larger and spawn further away from the coffin

**Server Revision**: 
2261

**Comment by aresbrutus** [comment]
https://github.com/Atlantiss/AtlantissTBCBT/issues/1054

**Comment by Tereneckla** [comment]
![WoWScrnShot_011320_150302](https://user-images.githubusercontent.com/50233983/72261815-e0af0100-3615-11ea-9882-3e85ebbd80f5.jpg)
