### ISSUE TITLE
[NPC]Shalassi Oracle#18455 [Spell]Shadow Shock#11824 & [Spell]Chain Lightning#12058 deals too much damage

### ISSUE THREAD

**Issue by Tenoutoften** [Atlantiss/NetherwingBugtracker#2471]
**Description**: 
[[NPC]Shalassi Oracle#18455](https://www.wowhead.com/npc=18455/shalassi-oracle#comments) damage looks too high.
![ab89639558aef5f6ab3c566d1f5f7e3f](https://user-images.githubusercontent.com/34839199/48205924-6a59a380-e36d-11e8-985b-ab7f814b0e8c.png)

NW
![cde36d81638b203b84887af49552e1ed](https://user-images.githubusercontent.com/34839199/48205929-6d549400-e36d-11e8-84a9-09355a6f233a.png)
![a3f633cda0835b93c2ea9ae279eaca18](https://user-images.githubusercontent.com/34839199/48205930-6ded2a80-e36d-11e8-9b2d-695f803d5848.png)

https://www.wowhead.com/spell=11824/shock#comments
https://www.wowhead.com/spell=12058/chain-lightning#comments

**Expected behaviour**: 
Should probably deal about 650-800?

**Server Revision**: 
2261

**Comment by Wolffenstein** [comment]
Fixed in rev 2273.
