### ISSUE TITLE
[NPC]Shalassi Oracle#18455, iD:17 miss placed

### ISSUE THREAD

**Issue by Tenoutoften** [Atlantiss/NetherwingBugtracker#2472]
**Description**: 
[[NPC]Shalassi Oracle#18455, iD:17](https://www.wowhead.com/npc=18455/shalassi-oracle#comments)
missplaced:

![033c3759df8752b3bb53d8171e7ed849](https://user-images.githubusercontent.com/34839199/48206249-4ba7dc80-e36e-11e8-9171-de5769b4e97f.png)
![aae8d934fb8af11ec64cf0c3f1e567e7](https://user-images.githubusercontent.com/34839199/48206251-4ba7dc80-e36e-11e8-9967-1b8e77649d8e.png)

**Expected behaviour**: 
Should probably be on the platform.

**Server Revision**: 
2261

**Comment by aresbrutus** [comment]
Fixed in rev `Vesta`
