### ISSUE TITLE
[NPC] Unstable Voidwraith [Spell] Unstable Rift#36463 dealing too much damage

### ISSUE THREAD

**Issue by Corrozus** [Atlantiss/NetherwingBugtracker#2473]
[//]: # (Enclose links to things related to the bug using http://wowhead.com or any other TBC database.)
[//]: # (You can use screenshot ingame to visual the issue.)
[//]: # (Write your tickets according to the format:)
[//]: # ([Quest][Azuremyst Isle] Red Snapper - Very Tasty!)
[//]: # ([NPC] Magistrix Erona)
[//]: # ([Spell][Mage] Fireball)
[//]: # ([Npc][Drop] Ghostclaw Lynx)
[//]: # ([Web] Armory doesnt work)

**Description**: Doing the quest [Recipe for Destruction](http://db.hellfire-tbc.com/?quest=10437) I got killed in 2 seconds by this spell as shown by the screenshot below.

https://imgur.com/a/jlVsW82

A comment from [wowhead](https://www.wowhead.com/npc=18869/unstable-voidwraith#comments) from 2007 suggests it should only be doing 1k every half second. 

The spell also follows you around. It should be pulsing in place, so you can move out of it.

**Current behaviour**: Unstable Rift does too much damage and follows you around.

**Expected behaviour**: Should deal less damage and pulse in place, like any other void zone.

**Server Revision**: 2261

**Comment by Mikik3jr** [comment]
Another thing: When it dies that circle is following you and it looks like the invisible dead body is following and hitting me after I killed it.
![wowscrnshot_111118_121104](https://user-images.githubusercontent.com/43505031/48312174-20f69780-e5ab-11e8-9494-849eb12aa6e4.jpg)

**Comment by xmesaj2** [comment]
fixed in 2316
