### ISSUE TITLE
Enraged Spirits of Fire and Earth - when the totem of spirits is laid and you move forward to next mobs and lay totem again it does lay the totem again it stays in its original place until it expires- not sure if this is intended or not

### ISSUE THREAD

**Issue by rasin00** [Atlantiss/NetherwingBugtracker#2474]
[//]: # (Enclose links to things related to the bug using http://wowhead.com or any other TBC database.)
[//]: # (You can use screenshot ingame to visual the issue.)
[//]: # (Write your tickets according to the format:)
[//]: # ([Quest][Azuremyst Isle] Red Snapper - Very Tasty!)
[//]: # ([NPC] Magistrix Erona)
[//]: # ([Spell][Mage] Fireball)
[//]: # ([Npc][Drop] Ghostclaw Lynx)
[//]: # ([Web] Armory doesnt work)

**Description**: 

**Current behaviour**:

**Expected behaviour**: 

**Server Revision**:

**Comment by Easyfraggy** [comment]
Please describe your issues better - They are almost unreadable and impossible to understand. Use punctuation.

Writing all the inof in the topic is not the way to report. Screenshots are great use win+shift+s and copy pasta directly into github. Or ShareX or similar programs.

**Comment by Matija5** [comment]
It's not shaman thing, With this quest u get Totem of Spirits which u have to put on ground and kill enraged earth and fire spirit near it. But when u move on the other location and you click Totem of Spirits to put on ground he doesn't appear but he refreshes the previous totem u pulled
