### ISSUE TITLE
[NPC]Infested Root-Walker#22095 should heal [NPC]Rotting Forest-Rager#22307 when both are engaged in the same fight

### ISSUE THREAD

**Issue by Tenoutoften** [Atlantiss/NetherwingBugtracker#2475]
**Description**: 
[NW video](https://youtu.be/LkRuyAiX4E4)

[[NPC]Infested Root-Walker#22095](https://www.wowhead.com/npc=22095/infested-root-walker#comments) is using it's [[Spell]Regrowth#39000](https://www.wowhead.com/spell=39000/regrowth) but the heal doesn't seem to be received, not sure where it ends up but [[NPC]Rotting Forest-Rager#22307](https://www.wowhead.com/npc=22307/rotting-forest-rager#comments) doesn't receive any heal. Perhaps immune?

**Expected behaviour**: 
[[NPC]Rotting Forest-Rager#22307](https://www.wowhead.com/npc=22307/rotting-forest-rager#comments) should receive the [[Spell]Regrowth#39000](https://www.wowhead.com/spell=39000/regrowth)-heal from [[NPC]Infested Root-Walker#22095](https://www.wowhead.com/npc=22095/infested-root-walker#comments)

**Server Revision**: 
2266

**Comment by Tereneckla** [comment]
Infested Root-Walkers aren't healing Rotting Forest-Ragers anymore.
Guess this is the fix.

**Comment by Evolvee** [comment]
video unavailable

**Comment by Evolvee** [comment]
@Wolffenstein could be global wolfAI (SPELL_TARGET_AI_DECISION) problem. The 22095 doesnt heal 22307 (it doesnt even inicialize)... tried to change them to the same faction, didnt help.

**Comment by Wolffenstein** [comment]
Fixed in rev 3368.
