### ISSUE TITLE
[quest] Recharging the Batteries - pet interaction

### ISSUE THREAD

**Issue by sifiuocz** [Atlantiss/NetherwingBugtracker#2477]
**Description**: 
The Phase Hunters (https://db.excalibur.ws/?npc=18879) don't emote how they are supposed to when the pet deals the damage that brings the Phase Hunter NPCs below a certain HP threshold that trigger the emote.
Therefore player cannot use the item (Battery Recharging Blaster - https://db.excalibur.ws/?item=28369) on the NPCs and can't get progress on the quest.

**Current behaviour**:

**Expected behaviour**: 

**Server Revision**: 
2266

**Comment by mhdemn** [comment]
Exactly what OP says. Also, even though it's not TBC retail footage, in this [video](https://www.youtube.com/watch?v=hAEsbK11oz8) you can see you should get an Invalid Target error message when trying to use it on the worms above the HP threshold; in my opinion it makes sense it always was like that.

I also recorded it before checking if this was reported so [here](https://www.youtube.com/watch?v=IkGvott34kk) you go, in case it helps.

**Comment by Easyfraggy** [comment]
Might be global problem.

**Comment by Tenoutoften** [comment]
Figured that would add that I can use the item even at 100% - though it wont give me credit.

Sometimes when I use it at low hp, it doesn't change the mob(Even if it's done the emote) Perhaps because I tried earlier?

I have also seen it do level up animation, possibly when the drained phase hunter-mob change happens and it is a level higher?

**Comment by mhdemn** [comment]
Sorry I cant quote and format and stuff, typing from phone.

Think the guy in the vid I linked tries to use the item on worms above the HP threshold and gets Invalid Target Errors. Anyhow I agree on that even in retail TBC it allowed you to use it before it was time it's a small QoL thing.

I didn't find any issue when using the item after the emote that I could relate to trying to use it before, only pet-related. Might have been arisen in a later server rev?

About the level up animation they do: I reckon seeing them do it randomly both in and out of combat. As I was typing the report or recording I kept listening the sound too.

**Comment by HyperXewl** [comment]
What I've experienced: Random level up animation on the Phase Hunter. Just as Original Post describes, the phase hunter will not properly trigger the item's effect if it is the hunter's pet that brings the health below the threshold.

**Comment by Evolvee** [comment]
rev 2932

**Comment by raethkcj** [comment]
This seems to be broken again in rev 3507, possibly related to #7319
