### ISSUE TITLE
[Dungeon] Mana Tombs bugs - Outland-wide spell damage

### ISSUE THREAD

**Issue by mhdemn** [Atlantiss/NetherwingBugtracker#2478]
2266
NORMAL Mana Tombs

Overall scripting is gucci, just some spell damages that seem way overtuned, in a similar way to most of the rest of Outland's casters, gets specially crazy in dungeons like this or other Auchindoun's.

1. [Ethereal Sorcerer](https://db.excalibur.ws/?npc=18313) ([heroic](https://db.excalibur.ws/?npc=20259)). This database lists both versions of this spell in their abilities so I dunno which one normal ones should cast, but they cast either [this](https://db.excalibur.ws/?spell=32349) or [this](https://db.excalibur.ws/?spell=32353) to summon Arcane Fiends.

- Now, [Arcane Fiends](https://db.excalibur.ws/?npc=18429) ([heroic](https://db.excalibur.ws/?npc=20252)) cast [Arcane Explosion](https://db.excalibur.ws/?spell=15253) ([heroic](https://db.excalibur.ws/?spell=33860)) pretty often, which hurts a lot since two are spawned at the same time by the sorcerers.

![image](https://user-images.githubusercontent.com/25901582/48223103-87569c80-e396-11e8-9c5d-09a88cde6af9.png)

Looks overtuned compared to this [comment on wowhead from patch 2.0.6](https://www.wowhead.com/npc=18429/arcane-fiend#comments), at least for the normal version of the dungeon:

![image](https://user-images.githubusercontent.com/25901582/48223252-eae0ca00-e396-11e8-8fa9-2ff96f8e3cff.png)

Looks overtuned even if they were casting the heroic version of the explosion tbh.

2. [Ethereal Darkcasters](https://db.excalibur.ws/?npc=18331) ([heroic](https://db.excalibur.ws/?npc=20256)) have 3 abilities, two of them seem overtuned:

- [Mana Burn](https://db.excalibur.ws/?spell=34930) ([heroic](https://db.excalibur.ws/?spell=34931)) currently has the following issues:
  - I'm pretty sure they're using a [priest version of the spell](https://db.excalibur.ws/?spell=25380) since no bolt is fired, as it should according to the tooltip.
  - According to its tooltip and also priest's mana burn it should inflict damage equal to half the mana burned with the cast:

According to [wowhead comments from then](https://www.wowhead.com/npc=18331/ethereal-darkcaster#comments) they do drain a lot of mana:

![image](https://user-images.githubusercontent.com/25901582/48224275-8b37ee00-e399-11e8-8464-7af67671344a.png)

This is after taking one mana burn at 3300 mana:

![image](https://user-images.githubusercontent.com/25901582/48224146-36947300-e399-11e8-8887-6f98274283d7.png)

So yea, the amount of mana burned checks out, since 2400+ damage means 4800+ mana burned in one hit.

However, these taken damages imply I had double that number drained in mana points, and my pool isn't even that large, and I wasn't full mana in any of these situations:

![image](https://user-images.githubusercontent.com/25901582/48224371-d2be7a00-e399-11e8-87b1-89bcd6d3b1b0.png)

![image](https://user-images.githubusercontent.com/25901582/48224384-df42d280-e399-11e8-9d11-88c400dff4b5.png)

Meaning their Mana Burns calculate the damage somehow else, instead of dealing half the mana drained in damage as they should.

- [Shadow Word: Pain](https://db.excalibur.ws/?spell=34942) (same spell for normal and heroic versions of the mob according to this database) seems to do too much damage aswell. You can see the damage of one tick in the previous picture, here's another:

![image](https://user-images.githubusercontent.com/25901582/48224512-39439800-e39a-11e8-85ea-77b4d9b93972.png)

Ticks for 6 times, making 10,092 total damage. Can't find reliable info on what was the total damage in retail, but again in this comment I think he's saying the spell will do more or less 2400 damage in his full duration:

![image](https://user-images.githubusercontent.com/25901582/48225171-59745680-e39c-11e8-999c-853a750244c6.png)

Pretty high above 2400. [This](https://db.excalibur.ws/?spell=25368) is priest's rank 10 SW:P for comparison (1236 total base damage).

.....................................................................................................................................................................................................................

Will update with reliable sources, noticed mistakes, etc. Please lemme know if I fucked up somewhere.

Wanna also add that overall spell damages are too high almost everywhere in Outland. In Sethekk Halls (#2455) it's pretty crazy with the Lightning thing; here's it's more manageable but still overtuned. In open world there's a ton of caster mobs dealing a lot of damage, and even though this was def a thing in retail TBC I don't think it was, generally speaking, this high everywhere in the xpac content.

**Comment by Wolffenstein** [comment]
Please retest again in rev 2273 and reopen if still bugged.
