### ISSUE TITLE
[NPC] Sethekk Initiate

### ISSUE THREAD

**Issue by Mikik3jr** [Atlantiss/NetherwingBugtracker#2479]
[//]: # (Enclose links to things related to the bug using http://wowhead.com or any other TBC database.)
[//]: # (You can use screenshot ingame to visual the issue.)
[//]: # (Write your tickets according to the format:)
[//]: # ([Quest][Azuremyst Isle] Red Snapper - Very Tasty!)
[//]: # ([NPC] Magistrix Erona)
[//]: # ([Spell][Mage] Fireball)
[//]: # ([Npc][Drop] Ghostclaw Lynx)
[//]: # ([Web] Armory doesnt work)

**Description**: 
This [mob](https://www.wowhead.com/npc=18318/sethekk-initiate#abilities) has a spell reflect ability.
![wowscrnshot_110818_210736](https://user-images.githubusercontent.com/43505031/48225963-ba049300-e39e-11e8-95af-b3cfbd87f48a.jpg)

**Current behaviour**:
According to our shaman he got the dmg from spell reflect. After that I Ice Lance-d the guy, reflected those 3 Ice Lances back. The mob didn't take dmg from those Ice Lances, nor me.

**Expected behaviour**: 
2 possibilities:
- According to wowhead it reflects 1 spell, so the buff should disappear after the reflect.
- If it reflects all spells during that buff, then I should take dmg from reflected spells.

**Server Revision**: 
2266

**Comment by The14me** [comment]
https://www.wowhead.com/spell=33961/spell-reflection
''Magical spells will be reflected''
That looks fine to me.There is nothing for ''only 1 spell reflect''.
Can be closed
Rev .3451
