### ISSUE TITLE
Rogue's Stealth

### ISSUE THREAD

**Issue by Erodraeda** [Atlantiss/NetherwingBugtracker#248]
[//]: # (Enclose links to things related to the bug using http://wowhead.com or any other TBC database.)
[//]: # (You can use screenshot ingame to visual the issue.)
[//]: # (Write your tickets according to the format:)
[//]: # ([Quest][Azuremyst Isle] Red Snapper - Very Tasty!)
[//]: # ([NPC] Magistrix Erona)
[//]: # ([Spell][Mage] Fireball)
[//]: # ([Npc][Drop] Ghostclaw Lynx)
[//]: # ([Web] Armory doesnt work)

**Description**: 
When you are in group with a rogue, you can't see him while stealthed, but you should be able to.
**Current behaviour**:
When you are in group with a rogue, you can't see him while stealthed
**Expected behaviour**: 
You should be able to see your group mates, even if they are stealthed.
**Server Revision**:

**Comment by Easyfraggy** [comment]
fixed in 2110
