### ISSUE TITLE
Old Hillsbrad foothills bugs - Druid most forms take you out of form when leaving a building also cant enter the dungeon after a wipe

### ISSUE THREAD

**Issue by rasin00** [Atlantiss/NetherwingBugtracker#2480]
[//]: # (Enclose links to things related to the bug using http://wowhead.com or any other TBC database.)
[//]: # (You can use screenshot ingame to visual the issue.)
[//]: # (Write your tickets according to the format:)
[//]: # ([Quest][Azuremyst Isle] Red Snapper - Very Tasty!)
[//]: # ([NPC] Magistrix Erona)
[//]: # ([Spell][Mage] Fireball)
[//]: # ([Npc][Drop] Ghostclaw Lynx)
[//]: # ([Web] Armory doesnt work)

**Description**: 

**Current behaviour**:

**Expected behaviour**: 

**Server Revision**:

**Comment by rasin00** [comment]
Also just leaving form would return me to tauren form and some of the mobs in the instance was level 71

**Comment by Wolffenstein** [comment]
Fixed in rev 2293.
