### ISSUE TITLE
[Quest][Shadowmoon Valley] Imbuing the headpiece is bugged wish Shapeshifting.

### ISSUE THREAD

**Issue by Unfairy** [Atlantiss/NetherwingBugtracker#2481]
Equipping Unfinished headpiece giving you buff and yo able to see ghost gul'dans near the main one.
But when you shapeshift into any of form (as druid) you are not able to see the ghosts and just can use the trinket to complete the quest.
Buff on
![wowscrnshot_110918_000156](https://user-images.githubusercontent.com/41975070/48227544-4cab2f00-e3ab-11e8-8063-7437f41bf694.jpg)
Buff off
![wowscrnshot_110918_000200](https://user-images.githubusercontent.com/41975070/48227554-5339a680-e3ab-11e8-8e05-178e31ffb67a.jpg)

**Comment by devo6969** [comment]
https://www.wowhead.com/spell=38438/echoes-of-memory
"Cannot be used while shapeshifted"

You see him with the buff then as his flys it cancels out and force to kill it out of shapeshift .
https://youtu.be/DqSq-jNYlfc
