### ISSUE TITLE
[Spell][Shaman]Earth/Fire Elemental Totem

### ISSUE THREAD

**Issue by DeltaLoads** [Atlantiss/NetherwingBugtracker#2482]
[//]: # (Enclose links to things related to the bug using http://wowhead.com or any other TBC database.)
[//]: # (You can use screenshot ingame to visual the issue.)
[//]: # (Write your tickets according to the format:)
[//]: # ([Quest][Azuremyst Isle] Red Snapper - Very Tasty!)
[//]: # ([NPC] Magistrix Erona)
[//]: # ([Spell][Mage] Fireball)
[//]: # ([Npc][Drop] Ghostclaw Lynx)
[//]: # ([Web] Armory doesnt work)

**Description**: 
Using earth/fire elemental totem has no effect
https://streamable.com/rclue
**Current behaviour**:
Earth/Fire Elementals dont spawn when using totem
**Expected behaviour**: 
Using Earth/Fire Elemental Totem should spawn elementals
**Server Revision**: 
2266

**Comment by Wolffenstein** [comment]
Fixed in rev 2269.
