### ISSUE TITLE
[Stormwind]Invisible wall outside mage tower

### ISSUE THREAD

**Issue by DeltaLoads** [Atlantiss/NetherwingBugtracker#2483]
[//]: # (Enclose links to things related to the bug using http://wowhead.com or any other TBC database.)
[//]: # (You can use screenshot ingame to visual the issue.)
[//]: # (Write your tickets according to the format:)
[//]: # ([Quest][Azuremyst Isle] Red Snapper - Very Tasty!)
[//]: # ([NPC] Magistrix Erona)
[//]: # ([Spell][Mage] Fireball)
[//]: # ([Npc][Drop] Ghostclaw Lynx)
[//]: # ([Web] Armory doesnt work)

**Description**: 
https://streamable.com/n3z82
**Current behaviour**:
Invisible wall outside mage tower
**Expected behaviour**: 
No invisible walls outside of tower
**Server Revision**: 
2266

**Comment by Tenoutoften** [comment]
This is definitely because of the tall mount. Tested today with other mounts & noggenfogger & without mount.
