### ISSUE TITLE
[Dungeon][Sethekk Halls] Missing pack + Birds multiple dots.

### ISSUE THREAD

**Issue by Unfairy** [Atlantiss/NetherwingBugtracker#2484]
Cant say for sure, but there might be missing pack right before last boss.
If no one will be up to check old videos, will do myself later.

Non elite birds putting each - 1 debuff on tank, not sure if its supposed to be like that or suppsoed to be just 1 debuff reaplying every time bird use this ability.
(Cant remember it being the thing in retail).

**Comment by Easyfraggy** [comment]
https://github.com/Atlantiss/AtlantissTBCBT/issues/836

**Comment by Tereneckla** [comment]
Pack is there. Multiple dots is correct.
