### ISSUE TITLE
Quest: Missing Friends

### ISSUE THREAD

**Issue by Novat93** [Atlantiss/NetherwingBugtracker#2487]
[//]: # (Enclose links to things related to the bug using http://wowhead.com or any other TBC database.)
[//]: # (You can use screenshot ingame to visual the issue.)
[//]: # (Write your tickets according to the format:)
[//]: # ([Quest][Azuremyst Isle] Red Snapper - Very Tasty!)
[//]: # ([NPC] Magistrix Erona)
[//]: # ([Spell][Mage] Fireball)
[//]: # ([Npc][Drop] Ghostclaw Lynx)
[//]: # ([Web] Armory doesnt work)

**Description**: 
quest=10852
The amount of freed children credited, does not reflect the amount of kids actually freed from the cages.

**Current behaviour**:
The game sometimes credits the player with freeing an extra child.

**Expected behaviour**: 
The player should be credited with only the children freed.

**Server Revision**: 
2270

![kid](https://user-images.githubusercontent.com/36829235/48241067-9b6dbe80-e3d5-11e8-87ab-97ee9a355861.PNG)
There are 2 children present in the cage

![kid2](https://user-images.githubusercontent.com/36829235/48241073-a58fbd00-e3d5-11e8-8faa-53dc9387e15e.PNG)
The player is credited with freeing 3 children

**Comment by Manaci** [comment]
Fixed
