### ISSUE TITLE
[NPC][Spell] Spell damage of almost all NPCs i met in Outland is overtuned

### ISSUE THREAD

**Issue by bekonja** [Atlantiss/NetherwingBugtracker#2488]
[//]: # (Enclose links to things related to the bug using http://wowhead.com or any other TBC database.)
[//]: # (You can use screenshot ingame to visual the issue.)
[//]: # (Write your tickets according to the format:)
[//]: # ([Quest][Azuremyst Isle] Red Snapper - Very Tasty!)
[//]: # ([NPC] Magistrix Erona)
[//]: # ([Spell][Mage] Fireball)
[//]: # ([Npc][Drop] Ghostclaw Lynx)
[//]: # ([Web] Armory doesnt work)

**Description**: Every spell-casting mob i met on my journey from HFP to Terokkar was difficult due absurdly high damage they deal. Up untill Tomb of Lights and Firewing Point i considered it as some sort of hardcore challange for myself to keep playing, but now im frustrated. Ethereal Aranists deals ~2k damage in 5s arcane missle cast, Firewing Bloodwarders shock me with 1.4k damage every 4 seconds, and im 4k health only. Each of this mob can 1v1 me easily with some unlucky pull or resists on my side. I really wanted to find some original TBC footage to proof that casts that deal 50% of player health is not blizzlike at all, but there is no leveling footage from 2007 on youtube. I just tested it on Warmane and these mobs deal twise as less damage with their abilities.

Edit1: https://www.wowhead.com/npc=1410/firewing-bloodwarder#comments:id=21689 original TBC mob deals twise less damage than it is on your server.

Edit2: https://github.com/Atlantiss/NetherwingBugtracker/issues/2478 https://github.com/Atlantiss/NetherwingBugtracker/issues/2471 looks like dungeon mobs are affected by this overtuning too.

**Current behaviour**: NPCs spell damage in Outland is absurdly high. Some elites can even oneshot you with their spells.

**Expected behaviour**: 

**Server Revision**: 2270

**Comment by Tenoutoften** [comment]
If you are melee class I highly recommend abusing the walls. When I was at the Firewing I was clearing one hut and pulled them in there, hitting the mobs through the wall so they would never cast:p

**Comment by bekonja** [comment]
> If you are melee class I highly recommend abusing the walls. When I was at the Firewing I was clearing one hut and pulled them in there, hitting the mobs through the wall so they would never cast:p

Its cool and all, but how do you LOS mobs whose casts are instans? Or ones with channeling spells? Because they are the ones that i was talking about in initial post.
Anyways mobs shouldnt be hitting with x2 spell damage in a first place. This is the most massive bug iv seen so far.

**Comment by Wolffenstein** [comment]
Fixed in rev 2273.
