### ISSUE TITLE
Hunter pet combat

### ISSUE THREAD

**Issue by Matija5** [Atlantiss/NetherwingBugtracker#2489]
[//]: # (Enclose links to things related to the bug using http://wowhead.com or any other TBC database.)
[//]: # (You can use screenshot ingame to visual the issue.)
[//]: # (Write your tickets according to the format:)
[//]: # ([Quest][Azuremyst Isle] Red Snapper - Very Tasty!)
[//]: # ([NPC] Magistrix Erona)
[//]: # ([Spell][Mage] Fireball)
[//]: # ([Npc][Drop] Ghostclaw Lynx)
[//]: # ([Web] Armory doesnt work)

**Description**: While we were doing slaves pen yesterday one of the party members got stuck in combat but noone in party was in combat, then we called an GM and he said that my pet was holding him in combat even tho i was not in combat.

**Current behaviour**: Pet getting other players stuck in combat

**Expected behaviour**: 

**Server Revision**:

**Comment by Tenoutoften** [comment]
Is this still happening?

**Comment by Tenoutoften** [comment]
I did Slave Pens today with a hunter who had his pet out, we never got stuck in combat

**Comment by aresbrutus** [comment]
I think this has already been fixed, DM me if the issue still persists.
