### ISSUE TITLE
Pathing

### ISSUE THREAD

**Issue by John-Johnston** [Atlantiss/NetherwingBugtracker#249]
Mobs are taking 'shortcuts' even if there is a clear path to the player.  
https://www.youtube.com/watch?v=6oso9qQNf6s

**Comment by Evolvee** [comment]
this is intended retail behaviour

you can still test it on retail even now...

**Comment by Evolvee** [comment]
https://youtu.be/0M3HznqYuzc

**Comment by John-Johnston** [comment]
You're referring to the first scene? It's clearly two cuts.

**Comment by John-Johnston** [comment]
https://youtu.be/z4LxhxnIvlo?t=3m59s

**Comment by Evolvee** [comment]
![image](https://user-images.githubusercontent.com/1942409/46037364-3b160c80-c108-11e8-9564-363233a128ce.png)

:(
