### ISSUE TITLE
[Quest] Skywing

### ISSUE THREAD

**Issue by Needorfeed** [Atlantiss/NetherwingBugtracker#2491]
**Description**: 
Skywing fucks off after doing the final platform, but doesnt give any completion.

**Current behaviour**:
No completion on quest for me nor crasw when finishing the Skywing quest.

**Expected behaviour**: 
Should give us completed, so we can deliver the q.

**Server Revision**: 
2270

**Comment by The14me** [comment]
https://github.com/Atlantiss/NetherwingBugtracker/issues/2305

**Comment by Evolvee** [comment]
works fine for me

**Comment by Needorfeed** [comment]
weird. Both me and crasw got the same problem.
Maby we're just special :(

**Comment by Tenoutoften** [comment]
I just did this quest with 2 players in party and it worked as intended.
