### ISSUE TITLE
[NPC]Boulderfist Mystic#17135 current [Spell]Healing Touch is very weak

### ISSUE THREAD

**Issue by Tenoutoften** [Atlantiss/NetherwingBugtracker#2493]
**Description**: 
[[NPC]Boulderfist Mystic#17135](https://www.wowhead.com/npc=17135/boulderfist-mystic)'s current healing touch is very weak:
![9594ca944279ff25ba1e5503af1b7568](https://user-images.githubusercontent.com/34839199/48258268-fb378a00-e414-11e8-8ede-8223fb762b35.png)

Uses [[Spell]Healing Touch#11431](https://www.wowhead.com/spell=11431/healing-touch) on wowhead.

**Expected behaviour**: 
I'd expect a healing touch at this level from a regular mob to hit about 3000-3500

**Server Revision**: 
2270

**Comment by Evolvee** [comment]
we use the same spell ID

**Comment by Tenoutoften** [comment]
It's seems bizarre if this is correct behavior - if it is it must be a bug on retail itself? It makes no sense thats such a high level mob would heal as it if was level 20

**Comment by Evolvee** [comment]
try to find some vid...

**Comment by Tenoutoften** [comment]
Ill take a look in an hour or something

**Comment by Tenoutoften** [comment]
https://youtu.be/xX8CH40gKhY?t=192
Here you can see it using 
[[Spell]Earth Shock#13281](https://www.wowhead.com/spell=13281/earth-shock) on a non-casting shadow priest. Generally on NW I have never seen mobs use Earth Shock / Counter spell unless you actually cast something.

**Comment by Tenoutoften** [comment]
https://youtu.be/Dz2U57d85os?t=180 finally found it healing, but the guy doesnt target it

**Comment by Evolvee** [comment]
rev cd
