### ISSUE TITLE
[NPC]Tortured Earth Spirit#17156 Should go into Frenzy rather than Enrage, wrong enrage spell, Earth Shock deals too much damage

### ISSUE THREAD

**Issue by Tenoutoften** [Atlantiss/NetherwingBugtracker#2495]
**Description**: 
[[NPC]Tortured Earth Spirit#17156](https://www.wowhead.com/npc=17156/tortured-earth-spirit#abilities) shouldn't "becomes enraged!" but rather "goes into a frenzy!"
Seen [here](https://youtu.be/xlqdiCFB9us?t=45)

Currently uses a very weak [[Spell]Enrage](https://db.excalibur.ws/?search=enrage#spells:0+1) giving just +20 attack damage. Wowhead had this creature with [[Spell]Frenzy#3019](https://www.wowhead.com/spell=3019/frenzy)

![fd5cdb0e567f1fee1184223999ea862d](https://user-images.githubusercontent.com/34839199/48260362-7d2ab180-e41b-11e8-82b1-d797551b714b.png)
![da62439a263f6b8192f46d567143d5ef](https://user-images.githubusercontent.com/34839199/48260470-e90d1a00-e41b-11e8-87ae-3b92cbb702d1.png)

**Expected behaviour**: 
Lower damage earth shock, expected to have Frenzy spell rather than enrage, expected to "goes into frenzy" rather than "becomes enraged!"

**Server Revision**: 
2270

**Comment by Evolvee** [comment]
its the same spell
![image](https://user-images.githubusercontent.com/1942409/48263474-88370f00-e426-11e8-83ae-36af27e7429a.png)

they just renamed it
