### ISSUE TITLE
[Dungeon][NPC]Wastewalker Worker#17964 should "attempts to run away in fear!" & missing RP text yells

### ISSUE THREAD

**Issue by Tenoutoften** [Atlantiss/NetherwingBugtracker#2496]
**Description**: 
[[NPC]Wastewalker Worker#17964](https://www.wowhead.com/npc=17964/wastewalker-worker#comments)

Doesn't "attempts to run away in fear!" seen [here](https://youtu.be/NKXDqy4RHR0?t=67)
Doesn't do yells when freed, seen [here](https://youtu.be/NKXDqy4RHR0?t=73):

>Will the pain ever end?

>The pain is finally over.

>Thank you!

>How can we ever repay you for this?

>We have waited forever for this day to come!

Seen [here](https://youtu.be/NKXDqy4RHR0?t=126)
>Free at least

**Expected behaviour**: 
Should do all the RP parts.

**Server Revision**: 
2270

the shit cpp: 
![image](https://user-images.githubusercontent.com/1942409/80916867-a5b71180-8d5b-11ea-8578-e34dc63c1ac0.png)

**Comment by Evolvee** [comment]
@Wolffenstein its your shit cpp, i told u i would do it in sai and u were like naaaa dawg, its working

few months later... ppl report it on open beta as well 🤦‍♂️

**Comment by Wolffenstein** [comment]
Fixed in rev 3368.
