### ISSUE TITLE
[Misc][NPC]Coilfang Collaborator#17962 shouldn't emote "goes into a frenzy"

### ISSUE THREAD

**Issue by Tenoutoften** [Atlantiss/NetherwingBugtracker#2497]
**Description**: 
[[NPC]Coilfang Collaborator#17962](https://www.wowhead.com/npc=17962/coilfang-collaborator#abilities) shouldn't emote "goes into a frenzy" when using [[Spell]Frenzy#8269](https://www.wowhead.com/spell=8269/frenzy) seen [here](https://youtu.be/NKXDqy4RHR0?t=260)

**Current behaviour**:
![457594ac8b0104bcede6bdd06fe0dd92](https://user-images.githubusercontent.com/34839199/48263420-59209d80-e426-11e8-8967-54153d6fff7a.png)

**Expected behaviour**: 
No emote.

**Server Revision**: 
2270

**Comment by Evolvee** [comment]
rev dsa
