### ISSUE TITLE
Old Hillsbrad Foothills Epoch Hunter literally too angry to die

### ISSUE THREAD

**Issue by Mikik3jr** [Atlantiss/NetherwingBugtracker#2498]
[//]: # (Enclose links to things related to the bug using http://wowhead.com or any other TBC database.)
[//]: # (You can use screenshot ingame to visual the issue.)
[//]: # (Write your tickets according to the format:)
[//]: # ([Quest][Azuremyst Isle] Red Snapper - Very Tasty!)
[//]: # ([NPC] Magistrix Erona)
[//]: # ([Spell][Mage] Fireball)
[//]: # ([Npc][Drop] Ghostclaw Lynx)
[//]: # ([Web] Armory doesnt work)

**Description**: 
OHF(n) run.
**Current behaviour**:
Thrall didn't attack the boss. He was going in/out of combat all the time. We couldn't kill the boss, until we moved it close to Thrall so Thrall could finish the boss off.
https://www.youtube.com/watch?v=6v1WE6hl9WI&feature=youtu.be
**Expected behaviour**: 
Thrall should be in in combat attacking the last boss and boss should die.
**Server Revision**: 
2270

**Comment by Wolffenstein** [comment]
Thrall has to get the finishing blow and he'll fight normally since rev 2273.
