### ISSUE TITLE
Hunter taming pet bugs

### ISSUE THREAD

**Issue by Frankenberryberry** [Atlantiss/NetherwingBugtracker#2499]
**Description**: 
I came across a few flaws and bugs when I did the orc lvl 10 hunter taming quest line. They are written below.

**Current behaviour**:
1) No xp was given for any of the different steps. They should each reward 850xp.
2) After taming a pet I couldn't give them any orders. They wouldn't attack, stay or follow.
3) After a taming a pet I couldn't dismiss them without relogging.

**Expected behaviour**: 
1) xp should be given.
2) You should be able to give these pets orders (even though they aren't permanent pets)
3) You should be able to dismiss them so you can complete the quest line without relogging 3 times.

**Server Revision**:

**Comment by Easyfraggy** [comment]
Please use the search function.

**Comment by Easyfraggy** [comment]
https://github.com/Atlantiss/NetherwingBugtracker/issues/375
