### ISSUE TITLE
Fireplaces

### ISSUE THREAD

**Issue by Lukeroo** [Atlantiss/NetherwingBugtracker#25]
You don't receive any damage when standing on a fireplace. Normally from what I know you always received damage.

**Comment by aresbrutus** [comment]
Can you please post the .gps text, or provide a screenshot with location so we can check the issue?

**Comment by Lukeroo** [comment]
Hello I send a screenshot. Dun Morogh - camp where you take the quest for boars
![zrzut ekranu 2018-09-23 o 09 59 46](https://user-images.githubusercontent.com/43504488/45925538-c5e3e500-bf17-11e8-84ee-7cd1d321f953.png)

**Comment by Sinyr** [comment]
Also in Dun Morogh, the campfire in front of the Frostmane Hold cave entrance

**Comment by The14me** [comment]
Not core issue,just this two need a fix.

**Comment by Shanghi** [comment]
These and about 40 more around the world will now burn you after revision 2438.
