### ISSUE TITLE
[NPC] [AI] Hunter pet and companion pet share same pathing when passive

### ISSUE THREAD

**Issue by peanutcheese** [Atlantiss/NetherwingBugtracker#250]
[//]: # (Enclose links to things related to the bug using http://wowhead.com or any other TBC database.)
[//]: # (You can use screenshot ingame to visual the issue.)
[//]: # (Write your tickets according to the format:)
[//]: # ([Quest][Azuremyst Isle] Red Snapper - Very Tasty!)
[//]: # ([NPC] Magistrix Erona)
[//]: # ([Spell][Mage] Fireball)
[//]: # ([Npc][Drop] Ghostclaw Lynx)
[//]: # ([Web] Armory doesnt work)

**Description**: 
https://gyazo.com/79399700fd3d5b0ac2f52a1ec4057d7e
**Current behaviour**:
the 2 different types of pets are standing on top of eachother
**Expected behaviour**: 
I remember from playing a hunter in actual TBC that this was not a problem, the pets should not be in the exact same spot.
**Server Revision**: 
2028

**Comment by Evolvee** [comment]
it uses the same follow generator currently

**Comment by Tereneckla** [comment]
Fixed
