### ISSUE TITLE
[NPC]Coilfang Soothsayer#17960 should use a channeled [Spell]Arcane Missiles rather than a single [Spell]Arcane bolt-spell

### ISSUE THREAD

**Issue by Tenoutoften** [Atlantiss/NetherwingBugtracker#2500]
**Description**: 
[[NPC]Coilfang Soothsayer#17960](https://www.wowhead.com/npc=17960/coilfang-soothsayer#abilities) should use a channeled 5 bolt [[Spell]Arcane Missiles](https://db.excalibur.ws/?search=arcane+missiles#spells) rather than a one-bolt arcane missiles can be seen [here](https://youtu.be/NKXDqy4RHR0?t=470)

**Expected behaviour**: 
A proper channeled [[Spell]Arcane Missiles](https://db.excalibur.ws/?search=arcane+missiles#spells) spell

**Server Revision**: 
2270

**Comment by Evolvee** [comment]
rev dsa
