### ISSUE TITLE
[Dungeon][NPC]Underbog Mushroom#17990 doesn't grow in size, Doesn't use [Spell]Spore Cloud

### ISSUE THREAD

**Issue by Tenoutoften** [Atlantiss/NetherwingBugtracker#2503]
**Description**: 
During the encounter with [[NPC]Hungarfen#17770](https://www.wowhead.com/npc=17770/hungarfen#abilities:mode=normal)  several mushrooms will spawn:

[[NPC]Underbog Mushroom#17990](https://www.wowhead.com/npc=17990/underbog-mushroom#abilities) doesn't grow in size.
HC version might be affected too: [[NPC]Underbog Mushroom#20189](https://db.excalibur.ws/?npc=20189)

[[Spell]Spore Cloud#31689](https://www.wowhead.com/spell=31689/spore-cloud)
HC [[Spell]Spore Cloud#34168](https://www.wowhead.com/spell=34168/spore-cloud)

Retail video [here](https://youtu.be/t1OKsqd2D-E?t=22)
NW video [here](https://www.youtube.com/watch?v=CpP5Z_Jq-f0&feature=youtu.be)

![92e2ec89bf5535a30ff059fe875df2c7](https://user-images.githubusercontent.com/34839199/48267908-d0a8f980-e433-11e8-8169-38f60702c023.png)
![bcecb6375152884933bec0c7144ea2ee](https://user-images.githubusercontent.com/34839199/48267977-06e67900-e434-11e8-9b89-e462beeab733.png)
![2f63a010ed7a38975377c84ca1b3dc6c](https://user-images.githubusercontent.com/34839199/48268038-309fa000-e434-11e8-8f8b-87bdec50b96a.png)

**Expected behaviour**: 
Expected to grow, should use Spore Cloud
**Server Revision**: 
2270

**Comment by Evolvee** [comment]
![image](https://user-images.githubusercontent.com/1942409/48366008-dd845200-e6ac-11e8-88bd-b22bb2a52d70.png)

**Comment by Easyfraggy** [comment]
This seems to be a new bug - i tested this - and watched stream as late as yesterday where they worked normally.

When you do go to fix this boss don't forget: https://github.com/Atlantiss/AtlantissTBCBT/issues/974

**Comment by Easyfraggy** [comment]
Is this still happening?

**Comment by AxeCell** [comment]
This still happened to me 2 days ago from the time of this comment. They spawn below the boss and they wont grow as they should. They should also instead spawn beneath players at a frequent pace.

**Comment by Easyfraggy** [comment]
They spawn randomly around a distance from him - not under players or atleast if it is under players its a random distance around players - you can see this easily on videos.

**Comment by Mikik3jr** [comment]
Same on heroic, and no cloud. 
![wowscrnshot_013019_135624](https://user-images.githubusercontent.com/43505031/52040353-6fc32600-2537-11e9-869e-bb874365a874.jpg)

**Comment by Manaci** [comment]
They're super slow at growing and takes a while before they start doing their poison cloud stuff still

**Comment by devo6969** [comment]
Retail TBC - https://www.youtube.com/watch?v=gdkoI_muyrw
PTR -  https://www.youtube.com/watch?v=hUiDmairGts

Just appears to be a visual bug of to give the players a visual indicator that the mushroom is going to explode soon, cloud animation works just not the growing mushroom

**Comment by Wolffenstein** [comment]
Fixed in rev 3438.

**Comment by babno** [comment]
@Wolffenstein still happening on karazahn. Not fixed.
