### ISSUE TITLE
Enraged air spirits immune to nature and arcane spells in SMV,  air elementals in nagrand are not immune to arcane spells

### ISSUE THREAD

**Issue by rasin00** [Atlantiss/NetherwingBugtracker#2507]
[//]: # (Enclose links to things related to the bug using http://wowhead.com or any other TBC database.)
[//]: # (You can use screenshot ingame to visual the issue.)
[//]: # (Write your tickets according to the format:)
[//]: # ([Quest][Azuremyst Isle] Red Snapper - Very Tasty!)
[//]: # ([NPC] Magistrix Erona)
[//]: # ([Spell][Mage] Fireball)
[//]: # ([Npc][Drop] Ghostclaw Lynx)
[//]: # ([Web] Armory doesnt work)

**Description**: 

**Current behaviour**:

**Expected behaviour**: 

**Server Revision**:

**Comment by Easyfraggy** [comment]
Please provide info on how it should be. This report is as close to invalid as it gets. You give no info.

**Comment by Mvtsvraev** [comment]
I tried to find info about arcane resist on elementals and can not find anything about this. Elementals on  plateau should not have arcane immune.So for me it remains an open question why Spirits in SMV have it, when air spirits have not arcane resist in vanilla and also on the plateau they also have no resist too.

**Comment by Wolffenstein** [comment]
Blizzlike.
