### ISSUE TITLE
Not getting quest items

### ISSUE THREAD

**Issue by Matija5** [Atlantiss/NetherwingBugtracker#2508]
[//]: # (Enclose links to things related to the bug using http://wowhead.com or any other TBC database.)
[//]: # (You can use screenshot ingame to visual the issue.)
[//]: # (Write your tickets according to the format:)
[//]: # ([Quest][Azuremyst Isle] Red Snapper - Very Tasty!)
[//]: # ([NPC] Magistrix Erona)
[//]: # ([Spell][Mage] Fireball)
[//]: # ([Npc][Drop] Ghostclaw Lynx)
[//]: # ([Web] Armory doesnt work)

**Description**: So I did underbog dungeon 2 times and both times I didn't get quest from him, then I moved on to nagrand and kill atm 138 dust howlers and didn't get quest that they drop but I did get like 10 poweder that they drop and that has lower drop rate. So i think i might be bugged or something 

**Current behaviour**:

**Expected behaviour**: 

**Server Revision**:

**Comment by Easyfraggy** [comment]
Were you in a raid?

**Comment by Matija5** [comment]
I was not, Kutsal said that it was a bugg that there was requirement to get that quest, I don't know if he fixed it tho

**Comment by Manaci** [comment]
Fixed
