### ISSUE TITLE
([Spell][Mage] Conjure water(food too?))

### ISSUE THREAD

**Issue by killablink** [Atlantiss/NetherwingBugtracker#251]
**Description**: Spam casting Conjure Water starts the global cooldown everytime you hit the key

**Current behaviour**: If you spam Conjure Water and press again conjure water like .5 seconds before the first cast goes off, it starts another global cooldown for no reason and you can't chain cast it.

**Expected behaviour**: Spamming a spell while another spell is being casted shouldn't start a GCD

**Server Revision**:  2032

**Comment by killablink** [comment]
Not sure why this is need research

https://gfycat.com/PerfumedBewitchedHapuka

If you spam cast any spell (frostbolt here) you will get another action is in progress and GCD doesn't go off
If you spam conjure, there are no errors and the global cooldown starts again even if you're still casting

**Comment by devo6969** [comment]
I tested this on classic and there is a global if you are spamming the conjured item.
