### ISSUE TITLE
[Quest] Dimensius the All-Devouring

### ISSUE THREAD

**Issue by Mewmewww** [Atlantiss/NetherwingBugtracker#2511]
[//]: # (Enclose links to things related to the bug using http://wowhead.com or any other TBC database.)
[//]: # (You can use screenshot ingame to visual the issue.)
[//]: # (Write your tickets according to the format:)
[//]: # ([Quest][Azuremyst Isle] Red Snapper - Very Tasty!)
[//]: # ([NPC] Magistrix Erona)
[//]: # ([Spell][Mage] Fireball)
[//]: # ([Npc][Drop] Ghostclaw Lynx)
[//]: # ([Web] Armory doesnt work)

**Description**: 
The Etheral helpers are... interesting.
**Current behaviour**:
Ethereal helpers don't help to combat the enemies besides the captain.
**Expected behaviour**: 
Should help, but they don't.
**Server Revision**: 2270

**Comment by Mikik3jr** [comment]
They disappeared to me while we were going to the place.

**Comment by mhdemn** [comment]
I recorded it.
Following NPCs are affected and do what you can see in this [video](https://youtu.be/sj04IKt8qfo) (nothing): [Protectorate Defenders](https://db.excalibur.ws/?npc=20984), [Protectorate Avengers](https://db.excalibur.ws/?npc=21805) and [Protectorate Regenerators](https://db.excalibur.ws/?npc=21783).
[Captain Saeed](https://db.excalibur.ws/?npc=20985) takes the beating alone.

[Dimensius](https://db.excalibur.ws/?npc=19554) is scripted flawlessly and performs as expected though.

**Comment by lynxzor** [comment]
The ads he summoned didn't do anything even when they spawned on me and I moved around until I attacked them, the Voidshrieker did attack my totems though if I placed them then would ignore me.
![wowscrnshot_112518_131727](https://user-images.githubusercontent.com/795881/48979746-1f52c680-f0b7-11e8-80d5-66fe40d0423a.jpg)
![wowscrnshot_112518_132129](https://user-images.githubusercontent.com/795881/48979748-2548a780-f0b7-11e8-92d8-e86cb9df5c4b.jpg)

**Comment by Frankenberryberry** [comment]
This quest is not working. Me and my group tried this event 3 times. When we get to the big room the boss never spawns and the captain despawns along with his soldiers.

**Comment by Johra92** [comment]
Me and my group just tried to do this quest, the NPCs all despawned as we reached the room where the boss should spawn.

**Comment by 5f3759** [comment]
Yeah, same as above. All NPCs despawned and theres no boss.
Important quest for pre-bis items.

**Comment by jarmanfour** [comment]
+1 to this, still broken

**Comment by Drayo** [comment]
+1 This Quest really is an important one :(

**Comment by pbjtime** [comment]
+1 please fix.... captain saeed is no where to be found for 2+ days

**Comment by Manaci** [comment]
Fixed in rev 3198
