### ISSUE TITLE
Berserking does not properly scale with health percentage

### ISSUE THREAD

**Issue by AndrewNB41191** [Atlantiss/NetherwingBugtracker#2512]
([Spell][Racial] Berserking)
**Description**: Berserking does not properly scale with health percentage.

**Current behaviour**: Berserking currently appears to scale from its 30% maximum haste buff to its 10% min from the health values 0%(max value) to 80%(min value) 

**Expected behaviour**: Should scale as explained in this wowpedia page from 2008 https://wow.gamepedia.com/index.php?title=Berserking&oldid=1685283
if current health is below or equal to 40% haste buff is 30% and after that scales linearly to 100% health and a 10% haste buff

**Server Revision**: 
2270

**Comment by mantusks** [comment]
Mantusks approved, I have videos to prove this.

**Comment by wtRCH** [comment]
It was fixed in revision 2265. On what server revision did you test it?

**Comment by AndrewNB41191** [comment]
if the server revisions are instantly applied to the server then i tried it after that.

**Comment by mantusks** [comment]
I just tested it right now, and there is no difference between full hp and 90% hp for berserking. Most of my testing at low health was done last night and it was changing below 10% hp.

**Comment by wtRCH** [comment]
If you don't provide me with server revision in 1-2 hours, I am closing the issue.

https://github.com/Atlantiss/NetherwingBugtracker/issues/2450

**Comment by wtRCH** [comment]
Do .serverinfo ingame.

**Comment by mantusks** [comment]
We are testing from server revision 2270

**Comment by Wolffenstein** [comment]
Fixed in rev 2273.
