### ISSUE TITLE
[NPC] Warp aberration and Sundered Rumbler

### ISSUE THREAD

**Issue by sifiuocz** [Atlantiss/NetherwingBugtracker#2513]
**Description**: 
These two NPCs (https://db.excalibur.ws/?npc=18865, https://db.excalibur.ws/?npc=18881) corpses always disappear before the player is able to loot them. 
This bug might be caused by a quest called "Elemental Power Extraction (https://db.excalibur.ws/?quest=10226) where the player is supposed to use an item on those NPCs and then supposedly their corpses disappear immediately.

**Current behaviour**:

**Expected behaviour**: 

**Server Revision**: 
2270

**Comment by Evolvee** [comment]
![image](https://user-images.githubusercontent.com/1942409/73591029-e0ee3e00-44e9-11ea-8bd8-a53b1970ffc6.png)
shit cpp

**Comment by Evolvee** [comment]
fixed in next rev
