### ISSUE TITLE
[Dungeon] Black Morass mobs evade if pull far away from portal

### ISSUE THREAD

**Issue by Mikik3jr** [Atlantiss/NetherwingBugtracker#2514]
[//]: # (Enclose links to things related to the bug using http://wowhead.com or any other TBC database.)
[//]: # (You can use screenshot ingame to visual the issue.)
[//]: # (Write your tickets according to the format:)
[//]: # ([Quest][Azuremyst Isle] Red Snapper - Very Tasty!)
[//]: # ([NPC] Magistrix Erona)
[//]: # ([Spell][Mage] Fireball)
[//]: # ([Npc][Drop] Ghostclaw Lynx)
[//]: # ([Web] Armory doesnt work)

**Description**: 
BM portals summons a big add, or a boss every 6 wave.

**Current behaviour**:
If you pull away the main summoned mob too far away from the portal it resets and goes back.
On this picture our tank died, but boss reset:
![wowscrnshot_110918_192423](https://user-images.githubusercontent.com/43505031/48283148-f21ddb80-e45b-11e8-938d-1ba5cb4bba87.jpg)

**Expected behaviour**: 
Main mobs/bosses should not evade if pulled away from the portal.

**Server Revision**: 
2270

**Comment by Wolffenstein** [comment]
Proof?

**Comment by Mikik3jr** [comment]
I mean shouldn't enemies follow you inside dungeons until you run out of dungeon/Wipe/Kill them?

**Comment by Mikik3jr** [comment]
I just don't think it should work like that, when mobs follow you inside dungeons forever AND the second boss knock you back with Wing Buffet. It knocked back our tank, then the boss reseted itself on 5% in the middle of the fight.

I have no proof here.

**Comment by Mikik3jr** [comment]
![image](https://user-images.githubusercontent.com/43505031/48285559-41b3d580-e463-11e8-8207-887fd4a1e84f.png)
Found out you are right. I am really sorry.
