### ISSUE TITLE
[Dungeon] Black Morass protals are coming nonstop

### ISSUE THREAD

**Issue by Mikik3jr** [Atlantiss/NetherwingBugtracker#2515]
[//]: # (Enclose links to things related to the bug using http://wowhead.com or any other TBC database.)
[//]: # (You can use screenshot ingame to visual the issue.)
[//]: # (Write your tickets according to the format:)
[//]: # ([Quest][Azuremyst Isle] Red Snapper - Very Tasty!)
[//]: # ([NPC] Magistrix Erona)
[//]: # ([Spell][Mage] Fireball)
[//]: # ([Npc][Drop] Ghostclaw Lynx)
[//]: # ([Web] Armory doesnt work)

**Description**: 
There are 18 waves in the dungeon.

**Current behaviour**:
After killing a boss the next portal appears. There is no stop.

**Expected behaviour**: 
There should be a little break after bosses.

**Server Revision**: 
2270

**Comment by Wolffenstein** [comment]
That's not true. There can be up to 4 portals at once if you're not fast enough.

**Comment by Mikik3jr** [comment]
But then the break time should be there.

**Comment by Wolffenstein** [comment]
Fixed in rev 2273.
