### ISSUE TITLE
[Dungeon] Black Morass adds are op

### ISSUE THREAD

**Issue by Mikik3jr** [Atlantiss/NetherwingBugtracker#2516]
[//]: # (Enclose links to things related to the bug using http://wowhead.com or any other TBC database.)
[//]: # (You can use screenshot ingame to visual the issue.)
[//]: # (Write your tickets according to the format:)
[//]: # ([Quest][Azuremyst Isle] Red Snapper - Very Tasty!)
[//]: # ([NPC] Magistrix Erona)
[//]: # ([Spell][Mage] Fireball)
[//]: # ([Npc][Drop] Ghostclaw Lynx)
[//]: # ([Web] Armory doesnt work)

**Description**: 
https://www.wowhead.com/npc=17892/infinite-chronomancer

**Current behaviour**:
This add's arcane explosion deals 3.6k dmg. It hurts. And there is another one with shadow bolt that deals 3k+ dmg. Sadly I can't find the second one's name.

**Expected behaviour**: 
Caster adds should not deal that much amount of dmg on a normal dungeon.

**Server Revision**: 
2270

**Comment by Mikik3jr** [comment]
![image](https://user-images.githubusercontent.com/43505031/48286637-93119400-e466-11e8-994f-7efbe2498aa0.png)

**Comment by SwiftieTBC** [comment]
https://youtu.be/yF0jylnAxr8?t=85 - proof of AE dealing too much dmg

**Comment by Wolffenstein** [comment]
Fixed in rev 2273.
