### ISSUE TITLE
[NPC] Sa'at

### ISSUE THREAD

**Issue by Mikik3jr** [Atlantiss/NetherwingBugtracker#2517]
[//]: # (Enclose links to things related to the bug using http://wowhead.com or any other TBC database.)
[//]: # (You can use screenshot ingame to visual the issue.)
[//]: # (Write your tickets according to the format:)
[//]: # ([Quest][Azuremyst Isle] Red Snapper - Very Tasty!)
[//]: # ([NPC] Magistrix Erona)
[//]: # ([Spell][Mage] Fireball)
[//]: # ([Npc][Drop] Ghostclaw Lynx)
[//]: # ([Web] Armory doesnt work)

**Description**: 
I finished the BM quest.

**Current behaviour**:
NPC offers the beacon in 2 options. Both of them gives me the beacon.
![wowscrnshot_110918_193131](https://user-images.githubusercontent.com/43505031/48283561-2fcf3400-e45d-11e8-8fa6-eb2de136d552.jpg)

**Expected behaviour**: 
Should be 1 option I think.

**Server Revision**: 
2270

**Comment by Wolffenstein** [comment]
It's actually blizzlike from what I remember.

**Comment by Mikik3jr** [comment]
Then sorry.

**Comment by Tenoutoften** [comment]
I found a video from retail here:
https://youtu.be/QC7JjccOGf8?t=21

**Comment by Wolffenstein** [comment]
Fixed in rev 2273.

**Comment by Godmatik** [comment]
Still occurs, when you talk to Sa'at, both options appear.
