### ISSUE TITLE
[Quest] Divination: Gorefiend's Cloak [NPC] Cleric of Karabor visible without wearing spectrecles

### ISSUE THREAD

**Issue by Corrozus** [Atlantiss/NetherwingBugtracker#2518]
[//]: # (Enclose links to things related to the bug using http://wowhead.com or any other TBC database.)
[//]: # (You can use screenshot ingame to visual the issue.)
[//]: # (Write your tickets according to the format:)
[//]: # ([Quest][Azuremyst Isle] Red Snapper - Very Tasty!)
[//]: # ([NPC] Magistrix Erona)
[//]: # ([Spell][Mage] Fireball)
[//]: # ([Npc][Drop] Ghostclaw Lynx)
[//]: # ([Web] Armory doesnt work)

**Description**: The mobs that drop the cloak for this quest are visible without wearing [the spectrecles](http://db.hellfire-tbc.com/?item=30719), while also being friendly. When you wear the spectrecles they turn hostile. As a hunter I'm also able to feign death and switch headgear to drop aggro off these mobs, as they turn friendly while not wearing the spectrecles.

Top comment from [this thread](https://web.archive.org/web/20070315124027/http://www.wowhead.com:80/?quest=10635) from 2007 indicates that you shouldn't be able to see the mobs unless you wear the spectrecles.

**Current behaviour**: Mobs are visible and friendly while not wearing spectrecles

**Expected behaviour**: Mobs should be invisible while not wearing spectrecles

**Server Revision**: 2272

**Comment by Evolvee** [comment]
@Wolffenstein u were supposed to do that aura fix :/// (discord history)

**Comment by Mikik3jr** [comment]
Funny when you don't wear your spectrecles they are friendly and a female draenei has female dwarf voice when you select them.

**Comment by Manaci** [comment]
Fixed
