### ISSUE TITLE
Duel defeat put you to the air

### ISSUE THREAD

**Issue by Emityx** [Atlantiss/NetherwingBugtracker#252]
**Description**: 

In duel whenever you are defeated you will end up in the air. You need to move a bit to end up back on ground.

**Expected behaviour**: 
You should not end up in the air after you are defeated!

**Server Revision**: 2032

**Comment by wtRCH** [comment]
Did you jump during the end of the duel?

**Comment by Emityx** [comment]
Let some more guys test it and it seems to be working currently. Will re-open if i'll find it to be bugged after all.
