### ISSUE TITLE
[Dungeon] Shadow Labs

### ISSUE THREAD

**Issue by Mewmewww** [Atlantiss/NetherwingBugtracker#2520]
[//]: # (Enclose links to things related to the bug using http://wowhead.com or any other TBC database.)
[//]: # (You can use screenshot ingame to visual the issue.)
[//]: # (Write your tickets according to the format:)
[//]: # ([Quest][Azuremyst Isle] Red Snapper - Very Tasty!)
[//]: # ([NPC] Magistrix Erona)
[//]: # ([Spell][Mage] Fireball)
[//]: # ([Npc][Drop] Ghostclaw Lynx)
[//]: # ([Web] Armory doesnt work)

**Description**: 
Megathread.
**Current behaviour**:
No initial yell from the 1st boss (https://imgur.com/a/eNOB4kY)

2nd boss room, 3 packs, 2 of the packs are linked/chained. Led to almost 8-10 mobs at the same.  (https://imgur.com/a/KuoZ6d1) - All were pulled despite cautiousness

Right before the second boss, there should be invisible rogues (https://imgur.com/a/6fLEbl4) - Left and right side of the tents I believe, and scouting around.

Bubble didn't remove the 2nd boss' mind control (Sophiett is unsure of this interaction)

Missing patrol near 3rd boss - patrolling mobs.
3rd boss, threat removal from everyone (Unsure whether it's a normal or heroic mechanic)
Murmur Event room bugged (Fairy will post something)

**Expected behaviour**: 
See above, 
**Server Revision**: 
2270

**Comment by Unfairy** [comment]
In Addition.
3rd boss room packs missing patroling pack around boss. Here is info (copy past from my old report to other project).
[3rd boss room]
3rd boss room supposed to consist of 3rd boss, tonn of skeletons and 4 similar packs of mobs.
Mobs are linked, moving together and staying in 1 line.
One pack consists of from left to right: Cabal Zealot, Cabal Fanatic, Cabal Clutist and Cabal Zealot.
https://user-images.githubusercontent.com/41975070/43995190-5fd3afc4-9db2-11e8-94da-7feafd9168d1.png
1st pack (Moon) moving from end of the room closer to center of the room (to 2nd pack - Triangle) they are making pauses in 2 points - near the end of the room and near the center and when they are pausing - they are doing /kneel emotion
2nd pack (Triangle) moving from center of the room to the 3rd (stationary pack - Star) they are making pauses in 2 points - near the center of the room and near 3rd pack and kneeling.
3rd pack (Star) not moving and kneeling all the time.
4th pack (Circle) - Circling around the boss and 3rd pack. Making 2 pauses on the stairs and kneeling to the 3rd boss.
Link for the info : https://youtu.be/0MAm_fGg8gg?t=921

[4th boss room]
Door to last room suppsoed to open itself. Animation/event of warlock trying to run away and getting killed by Murmur.
Animation of 2 Cabal Executioners running to middle from sides.
Animations of mobs keep fighting Murmur, dies and new mobs replace them.
Animations of Mobs being knocked down my Murmur.
There is A LOT TO SCRIPT in last room but mainly its some "beauty, animation" stuff.
Here is link you can use to gather info. With set timing for opening door.
https://youtu.be/0MAm_fGg8gg?t=1179

**Comment by Tenoutoften** [comment]
Don't want to be picky but if you want precise quotes, a lot of times you wont get them correctly if you take them of wowwiki and similar pages. Doesn't matter too much for 5 mans, but for raids that will break addons.

**Comment by Easyfraggy** [comment]
Please make 1 issue per bug - It's a mess when 5/7 issues get fixed and the remaining 2 get forgotten.

https://github.com/Atlantiss/AtlantissTBCBT/issues/4067
https://github.com/Atlantiss/AtlantissTBCBT/issues/1735

**Comment by Easyfraggy** [comment]
Closing this please report any issues that might still persist individually.
