### ISSUE TITLE
[NPC][Drop] Bonechewer Evoker/Scavenger/Raider/Mutant

### ISSUE THREAD

**Issue by Gerryco** [Atlantiss/NetherwingBugtracker#2521]
**Description**:  Lvl 57-60 Bonechewer Orcs dropping Tome of Arcane Brilliance II (lvl 70)

**Current behaviour**:    ^

**Expected behaviour**: 
https://www.wowhead.com/npc=19701/bonechewer-evoker#drops:mode=noteworthy:0-18+1
https://www.wowhead.com/npc=16876/bonechewer-mutant#drops:mode=noteworthy:0-18+1
https://www.wowhead.com/npc=16925/bonechewer-raider#drops:mode=noteworthy:0-18+1
https://www.wowhead.com/npc=18952/bonechewer-scavenger#drops:mode=noteworthy:0-18+1

**Server Revision**: Could not find.

**Comment by ircfelix** [comment]
http://wowwiki.wikia.com/wiki/Tome_of_Arcane_Brilliance_2?oldid=1459091

> This tome drops from elites in most high-level Burning Crusade dungeons, such as Tempest Keep, Shattered Halls, parts of Auchindoun, The Steamvault, Caverns of Time, Karazhan and also in heroic dungeons.

**Comment by Shanghi** [comment]
You need to use the old databases for loot, like [Allakhazam](https://web.archive.org/web/20080417161740/http://wow.allakhazam.com:80/db/item.html?witem=22153) (or [Thottbot](https://web.archive.org/web/20080329214103/http://thottbot.com:80/i22153) and [Old Wowhead](https://web.archive.org/web/20080403133838/http://www.wowhead.com:80/?item=22153) but in this case those 2 won't be useful since it's global loot and will limit the creatures shown). I've gathered all the individual creature pages from each database before and there are enough records from low level creatures combined with the wowhead/thottbot/allakhazam comments below to believe the books should be on low level things too (and also not just from instances like wowwiki claims). Weak non-instance things do seem to have a lower chance though.

> "Although it's a low drop, this book droped for me from the ghosts on Master's Cellar near Karazhan, hope others have that luck too."
>
> "This dropped for me while farming motes of fire in elemental plateau"
>
> "dropet of a lvl 61 mob in hellfire peninsula near the portals"
>
> "Dropped from a level 67 Greater Windroc for me"
>
> "Dropped for me from a lvl 62 Terrorfiend at the Pools of Aggonar in Hellfire"
>
> "This dropped for me at the Ruins of Enkaat in Netherstorm."
>
> "looking through the drop list seems like it only drops from instances, but i got one today from darkspine siren"
>
> "I got this today from an [url=http://www.wowhead.com/?npc=19852]Artifact Seeker[/url] in Netherstorm, so it's definately not [i]just [/i] from instances."
>
> "I got this item yesterday from a drop in netherstorm"
>
> "Wowhead only lists the first 200 drop places, the Kvaldir Raider is just not on the list because people have had smaller drop chances from them."
>
> "Dropped off of a regular mob in Hellfire Peninsula not just a dungeon drop."
>
> "It dropped for me in Zangarmash from one of those Fly's just outside cenarion refuge"
>
> "Dropped off a Umbraglow Stinger for me in Zangarmarsh"
>
> "Got this off of a hellboar that attcked me while mounted"
>
> "just got it while farming fire elementals."
>
> "Dropped off a Voidspawn for me today in Nagrand."
>
> "i picked one up in BEM "
>
> "Dropped for me on Hellfire Pensuline from a orc I think"
>
> "Mine dropped off a slime in the pools of aggonar."
>
> "It just dropped from an ogre. just north of Zabrajin village in Zangarmash."
>
> "Dropped for me off some random mob in Terokkar Forest while doing quests."
>
> "dropped randomly from a Unyeilding sorcerer thingy in southern hellfire penn"
>
> "Got one off a spider in the cave going from Zang to Blades Edge"
>
> "Dropped off a Voidwalker in HP"
>
> "dropped of Nexus stalker in Netherstorm"
>
> "Dropped from a standard Orc just outside Hellfire Citadel"
>
> "Not just the elites though. High level mobs in places like netherstorm/shadowmoon drop them aswell."
>
> "one dropped off a infernal"
>
> "I got mine from the birds in Nagrand"
>
> "Got mine off a Teromoth in Terokkar Forest"
>
> "Drop of Birdman in Viel Shalas"
>
> "Pretty neat :) it dropped from the mobs before Karazhan"
>
> "Dropped off an Ango'rosh Sentry in Zangarmarsh"
>
> "Random drop off mob from Bloodmaul Ravine."
>
> "Dropped off a Talbuk in Eco-Dome in Netherstorm."
>
> "dropped off a dreadfang lurker in zangermarsh"
