### ISSUE TITLE
[Spell][Rogue] Rupture & Garrote

### ISSUE THREAD

**Issue by ahlens** [Atlantiss/NetherwingBugtracker#2523]
[//]: # (Enclose links to things related to the bug using http://wowhead.com or any other TBC database.)
[//]: # (You can use screenshot ingame to visual the issue.)
[//]: # (Write your tickets according to the format:)
[//]: # ([Quest][Azuremyst Isle] Red Snapper - Very Tasty!)
[//]: # ([NPC] Magistrix Erona)
[//]: # ([Spell][Mage] Fireball)
[//]: # ([Npc][Drop] Ghostclaw Lynx)
[//]: # ([Web] Armory doesnt work)

**Description**: 
These two spells:
- [Garrote](https://tbc-twinhead.twinstar.cz/?spell=11290)
- [Rupture](https://tbc-twinhead.twinstar.cz/?spell=11274)
cannot be reapplied if the stronger one already affects the target.

**Current behaviour**:
You can use another spell of the same kind only if you are going to cast stronger one (with more combo points). You cannot reapply it even at 5 combo points. This can be an issue more for PvP rather than for PvE I suppose.

However, [Expose Armor](https://tbc-twinhead.twinstar.cz/?spell=11198) seems to work properly.

Here is the link to download a video as my Vimeo limit has been already exceed.
https://filetransfer.io/data-package/dtCQ4LZm

**Expected behaviour**: 
We should be able to use it no matter of already existing debuff version on the enemy.

**Server Revision**: 
2279

**Comment by Easyfraggy** [comment]
Part of buffstacking - being remade entirely.

**Comment by Wolffenstein** [comment]
Fixed in rev 2288.
