### ISSUE TITLE
[Talent][Warrior] Improved Berserker Rage

### ISSUE THREAD

**Issue by ahlens** [Atlantiss/NetherwingBugtracker#2525]
[//]: # (Enclose links to things related to the bug using http://wowhead.com or any other TBC database.)
[//]: # (You can use screenshot ingame to visual the issue.)
[//]: # (Write your tickets according to the format:)
[//]: # ([Quest][Azuremyst Isle] Red Snapper - Very Tasty!)
[//]: # ([NPC] Magistrix Erona)
[//]: # ([Spell][Mage] Fireball)
[//]: # ([Npc][Drop] Ghostclaw Lynx)
[//]: # ([Web] Armory doesnt work)

**Description**: 

- [Berserker Rage](https://tbc-twinhead.twinstar.cz/?spell=18499) + [Improved Berserker Rage](https://tbc-twinhead.twinstar.cz/?spell=20501)

Buff is applied immediately but there is 0.5 - 1.0 sec delay before we get instant rage from talent.

**Current behaviour**: 
Here is a video
https://vimeo.com/user9632932/review/300000814/0c8565efc4

[Bloodrage](https://tbc-twinhead.twinstar.cz/?spell=2687) works fine so I assume it's talent issue.

**Expected behaviour**: 
We should get rage instantly. 

Not a major issue in my opinion as it's not used for PvP. I'm not an expert in PvE so I can't speak for these part.

**Server Revision**: 
2279

**Comment by Wolffenstein** [comment]
Fixed in rev 2288.
