### ISSUE TITLE
[Quest][Netherstorm] Battle-Mage Dathric, Abjurist Belmara, Conjurer Luminrath, Cohlien Frostweaver

### ISSUE THREAD

**Issue by Kaini27** [Atlantiss/NetherwingBugtracker#2526]
[//]: # (Enclose links to things related to the bug using http://wowhead.com or any other TBC database.)
[//]: # (You can use screenshot ingame to visual the issue.)
[//]: # (Write your tickets according to the format:)
[//]: # ([Quest][Azuremyst Isle] Red Snapper - Very Tasty!)
[//]: # ([NPC] Magistrix Erona)
[//]: # ([Spell][Mage] Fireball)
[//]: # ([Npc][Drop] Ghostclaw Lynx)
[//]: # ([Web] Armory doesnt work)

**Description**: Kirin Tor quests from quest starting items at Kirin'var village in Netherstorm dont work.
**Current behaviour**: Quests cannot be completed, rp doest works.

**Expected behaviour**:
 Item name- **Dathric's Blade**           Item id- **29233** Quest name- **Battle-Mage Dathric** Quest id- **10182**
Item name- **Belmara's Tome**         Item id- **29234** Quest name- **Abjurist Belmara** Quest id- **10305**
Item name- **Luminrath's Mantle**    Item id- **29235** Quest name- **Conjurer Luminrath** Quest id- **10306**
Item name- **Cohlien's Cap**           Item  id- **29236** Quest name- **Cohlien Frostweaver** Quest id- **10307**

**Server Revision**: 2279

**Comment by Evolvee** [comment]
Worked fine, must be core issue

**Comment by Thorgrimme** [comment]
Had no issues doing this yesterday.

**Comment by Wolffenstein** [comment]
Fixed in rev 2281.

**Comment by Tenoutoften** [comment]
Cohlien Frostweaver isn't working again

**Comment by Evolvee** [comment]
only him? its a core bug then

**Comment by Evolvee** [comment]
![image](https://user-images.githubusercontent.com/1942409/51426348-ac168e00-1be9-11e9-98a6-bfb81b550b2c.png)

works for me?
