### ISSUE TITLE
Champion Vranesh stuck

### ISSUE THREAD

**Issue by Novat93** [Atlantiss/NetherwingBugtracker#2527]
[//]: # (Enclose links to things related to the bug using http://wowhead.com or any other TBC database.)
[//]: # (You can use screenshot ingame to visual the issue.)
[//]: # (Write your tickets according to the format:)
[//]: # ([Quest][Azuremyst Isle] Red Snapper - Very Tasty!)
[//]: # ([NPC] Magistrix Erona)
[//]: # ([Spell][Mage] Fireball)
[//]: # ([Npc][Drop] Ghostclaw Lynx)
[//]: # ([Web] Armory doesnt work)

**Description**: Champion Vranesh is stuck in a waypoint loop in the Farstrider square, in front of the paladin trainers building.
npc=18146

**Current behaviour**:
Loops on the spot endlessly

**Expected behaviour**: 
Supposed to be patrolling around Silvermoon City

**Server Revision**: 
2279

3 different screenshots, where the NPC is stuck in the same location.

![vranesh1](https://user-images.githubusercontent.com/36829235/48299236-c71ea080-e4ca-11e8-865b-a9924fe554d1.PNG)
![vranesh2](https://user-images.githubusercontent.com/36829235/48299237-ca199100-e4ca-11e8-803d-57b6a795f18c.PNG)
![vranesh3](https://user-images.githubusercontent.com/36829235/48299240-cc7beb00-e4ca-11e8-9b00-7ddbc771cc3c.PNG)

**Comment by Wolffenstein** [comment]
Fixed in rev 2281.
