### ISSUE TITLE
[Movement][NPC]Northwind Cleft 4 missing ogres in the cave

### ISSUE THREAD

**Issue by Tenoutoften** [Atlantiss/NetherwingBugtracker#2529]
**Description**: 
Missing following NPCs in this specific cave room:
[[NPC]Boulderfist Warrior#17136](https://www.wowhead.com/npc=17136/boulderfist-warrior)
[[NPC]Boulderfist Mage#17137](https://www.wowhead.com/npc=17137/boulderfist-mage)
Can be seen [here](https://youtu.be/sHWpYiOhQbk?t=181)

Additionally expect 2 NPCs(It's usually 2) in this portion of the cave:
https://youtu.be/PPCoS0HoPl0?t=242

**Expected behaviour**: 
Expect a few NPCs in these rooms based on retail evidence. 

**Server Revision**: 
2279

**Comment by aresbrutus** [comment]
Fixed in rev `Vesta`
