### ISSUE TITLE
([Spell][Mage] Frost Armor)

### ISSUE THREAD

**Issue by killablink** [Atlantiss/NetherwingBugtracker#253]
**Description**: The application of the debuff currently resets the leash range of mobs (I imagine this is not only to frost armor, but also Ice armor, Molten Armor and everything that applies a debuff or damage a minion after hitting the player

**Current behaviour**: Mob attacks you with frost armor, gets the debuff and resets the leash timer. I was able to kite a mob really far away by letting myself hit every few seconds.

**Expected behaviour**: The debuff application should not reset the leash timer.

**Server Revision**:  2032

**Comment by Wolffenstein** [comment]
Any sources/proof that it should not?

**Comment by killablink** [comment]
It's going to be really hard to find proof of that because who really recorded themselves back in retail running away from a mob while reapplying the frost armor debuff. I can say the same back and ask is there any proof that it should reset the leash range?

To give you background information, I've played mage all my life in tbc and wotlk to the highest level (top 10 and 1 time rank 1 of BG, while also having realm firsts of instances) I know for a fact that frost armor//ice armor should not reset the leash timer, but the one that I was always less certain is I think Molten armor reapplies the leash timer if you have ignite and a mob hits you, molten armor crits and ignites gets into effect. From what I remember, that would also explain why thorns doesn't reset the leash timer (if you had a mob that runs faster than you and hits you while thorns it would never unleash). That would explain why Molten Armor COULD reset the leash timer, in this case it's because it procs ignites when molten armor crits.

**Comment by Wolffenstein** [comment]
You do have a point, I will look into it. Any other spell types I should take into consideration for disabling in this system?

**Comment by killablink** [comment]
I don't have first hands experience on the other classes but I feel stuff like retribution aura and maybe the priest talent that makes you reflect damage with power word shield most likely does not reset leash timer as it was not you directly damaging the mob. Aside from that I can't think of other atm

**Comment by Easyfraggy** [comment]
I don't think any "when hit" procs should reset leash timer at all, that's including thorns, holy shield, frost armors and other effects that cause damage to mobs when they attack the player.

**Comment by Evolvee** [comment]
dude i already reported this X times @Wolffenstein , check forums

btw

![image](https://user-images.githubusercontent.com/1942409/45946627-bdf87380-bff1-11e8-968e-2fd1407ce224.png)

**Comment by Tenoutoften** [comment]
Frost armor is still resetting the leech timer in rev 2395

**Comment by Wolffenstein** [comment]
Fixed in rev 2471.
