### ISSUE TITLE
Wrong range when picking up quest items from the ground

### ISSUE THREAD

**Issue by Nicemann1089** [Atlantiss/NetherwingBugtracker#2530]
[//]: # (Enclose links to things related to the bug using http://wowhead.com or any other TBC database.)
[//]: # (You can use screenshot ingame to visual the issue.)
[//]: # (Write your tickets according to the format:)
[//]: # ([Quest][Azuremyst Isle] Red Snapper - Very Tasty!)
[//]: # ([NPC] Magistrix Erona)
[//]: # ([Spell][Mage] Fireball)
[//]: # ([Npc][Drop] Ghostclaw Lynx)
[//]: # ([Web] Armory doesnt work)

https://drive.google.com/file/d/1ObRyMmSiDo2oIGqWtGAZ3a_AY96ndwV_/view?usp=drivesdk

**Description**: I don't know if this is a bug or if it was like that on retail. Picking up quest items from the ground seems to have a shorter effective range than the mouse symbol shows, when it turns into the golden gearwheel.

**Current behaviour**: Video above will demonstrate it.

**Expected behaviour**: The effective range of picking items up should be in sync with the mouse symbol turning into color.

**Server Revision**: 2279

**Comment by ircfelix** [comment]
This is only a vanilla source, but around 1:30, when the rogue is far away from the rune, but he still can loot it while the mouse symbol is coloured.

https://www.youtube.com/watch?v=1QximOcF5T8

**Comment by ircfelix** [comment]
You can also teleport to naxx and try the range in exactly this Frozen Rune.

**Comment by Tenoutoften** [comment]
https://youtu.be/1QximOcF5T8?t=108

**Comment by devo6969** [comment]
Was trying to research if this ever got hotfix looking up "object interaction" "Looting objects". Couldn't find any :/ Still need a solid answer

Retail BFA - https://www.youtube.com/watch?v=zwhYjbPQGyA
Retail MoP - https://youtu.be/SnnE17dC2H4

**Comment by Godmatik** [comment]
Duplicate
