### ISSUE TITLE
[Quest][Netherstorm] A Lingering Suspicion)

### ISSUE THREAD

**Issue by Thorgrimme** [Atlantiss/NetherwingBugtracker#2532]
[//]: # http://db.hellfire-tbc.com/?quest=10314

[//]: # ([Npc][Drop] http://db.hellfire-tbc.com/?item=29338

**Description**: The drop rate on this quest item is way to low, suppose to be 80 % according to this db, feels like it more like 20-30 %. Killed like 30+ mobs now and got 5 quest items. SO perhaps a bit higher but still off.

**Server Revision**:

**Comment by ircfelix** [comment]
According to https://wowhead.com/quest=10314/ein-hartnäckiger-verdacht#english-comments the drop rate should be rather low instead of super high like 80%.

**Comment by ircfelix** [comment]
https://web.archive.org/web/20080412090027/http://thottbot.com/i29338

Thottbot suggests a ~15.3% drop rate, but if you click on the Kirin'Var Ghost link, it shows a ~27% drop rate (same for all the other mobs).

**Comment by aresbrutus** [comment]
I just checked and the drop rates are correct

**Comment by Thorgrimme** [comment]
Ok those drop rates seems correct, but are we sure that data is for kills with ppl "on the quest" ? As killing 60 mobs in general for completing that quest in general seems like an overkill imo, and i can't recall it being that bad back on retail...

**Comment by ircfelix** [comment]
There is no reason to farm Kirin'Var Ghost since they don't drop motes or anything special. the only valueable thing they drop is nethercloth. So you can guess that they were only killed for the quest and the drop rate of them is correct.

**Comment by aresbrutus** [comment]
Neither 80 or 25% is correct. The actual number is more in between. I think you have just gotten unlucky Thorgrimme. The drop rate is not low enough that people should have issues with it as it is right now.

**Comment by Thorgrimme** [comment]
Fair enough.

**Comment by Spaztick** [comment]
This issue needs to be reopened, my current drop rate is less than 5%. Even being generous and getting the 15% drop rate off thottbot or the 25-80% as the "correct" rate would be nice.
