### ISSUE TITLE
[Quest][Nagrand][Returning the Favor]Item:  [Kil'sorrow Banner]

### ISSUE THREAD

**Issue by Matija5** [Atlantiss/NetherwingBugtracker#2534]
[//]: # (Enclose links to things related to the bug using http://wowhead.com or any other TBC database.)
[//]: # (You can use screenshot ingame to visual the issue.)
[//]: # (Write your tickets according to the format:)
[//]: # ([Quest][Azuremyst Isle] Red Snapper - Very Tasty!)
[//]: # ([NPC] Magistrix Erona)
[//]: # ([Spell][Mage] Fireball)
[//]: # ([Npc][Drop] Ghostclaw Lynx)
[//]: # ([Web] Armory doesnt work)

**Description**: So in quest returning the favor u get Banner which u have to put on ogers u kill, and it says that has 5 sec CD after u use it, but it appers that actuall CD to use it is bigger cuze u still can't use it after thoes 5 sec but u have to wait more time to use it again

**Current behaviour**:

**Expected behaviour**: 

**Server Revision**:

**Comment by ircfelix** [comment]
https://www.wowhead.com/quest=9931/returning-the-favor#comments

Before 2.1 you could spam the banner without any cooldown, according to several comments.

> 
Idk if it was as of 2.1 but since 5/27 the banner has a cool down of like 5 seconds.

**Comment by Tenoutoften** [comment]
I think this is a cooldown problem but rather a banner proximity problem.
I just killed 4 ogres, planted 2 flags shortly after each other, and when I went to plant my 3rd it said "item not ready yet." When the banners faded it could plant one of them

Ill see if I can make a video

**Comment by Tenoutoften** [comment]
https://github.com/Atlantiss/NetherwingBugtracker/issues/3317
Made a more clear bug report of the issue here
