### ISSUE TITLE
[Dungeon] Shadow Labs [NPC] Blackheart the Inciter

### ISSUE THREAD

**Issue by Mewmewww** [Atlantiss/NetherwingBugtracker#2535]
[//]: # (Enclose links to things related to the bug using http://wowhead.com or any other TBC database.)
[//]: # (You can use screenshot ingame to visual the issue.)
[//]: # (Write your tickets according to the format:)
[//]: # ([Quest][Azuremyst Isle] Red Snapper - Very Tasty!)
[//]: # ([NPC] Magistrix Erona)
[//]: # ([Spell][Mage] Fireball)
[//]: # ([Npc][Drop] Ghostclaw Lynx)
[//]: # ([Web] Armory doesnt work)

**Description**: 
No intro dialogue https://imgur.com/a/guoNVI9
**Current behaviour**:
Should be speaking to his crowd.
**Expected behaviour**: 
He's not.
**Server Revision**: 
2279

**Comment by Wolffenstein** [comment]
Don't trust wowwiki with texts.
