### ISSUE TITLE
[Dungeon] Shadow Labs [NPC] Blackheart the Inciter (Pathing Problem)

### ISSUE THREAD

**Issue by Mewmewww** [Atlantiss/NetherwingBugtracker#2536]
[//]: # (Enclose links to things related to the bug using http://wowhead.com or any other TBC database.)
[//]: # (You can use screenshot ingame to visual the issue.)
[//]: # (Write your tickets according to the format:)
[//]: # ([Quest][Azuremyst Isle] Red Snapper - Very Tasty!)
[//]: # ([NPC] Magistrix Erona)
[//]: # ([Spell][Mage] Fireball)
[//]: # ([Npc][Drop] Ghostclaw Lynx)
[//]: # ([Web] Armory doesnt work)

**Description**: 
Buggy pathing, dashes towards the centrum after going to stairs.
**Current behaviour**:
Buggy pathing, dashes towards the centrum after going to stairs. (Recon will send it)
**Expected behaviour**: 
Should not be encountering these pathing problems 
**Server Revision**: 
2279

**Comment by Wolffenstein** [comment]
Fixed in rev 2281.
