### ISSUE TITLE
[NPC] Watcher Leesa'oh

### ISSUE THREAD

**Issue by Galawer** [Atlantiss/NetherwingBugtracker#2537]
**Description**: 
[Watcher Leesa'oh](https://www.wowhead.com/npc=17831/watcher-leesaoh)
Entry: 17831, Id: 1, GUIDLow: 42356

**Current behaviour**:
NPC seems to get stuck, I think after the RP from completing [Stealing Back the Mushrooms](https://www.wowhead.com/quest=9709/stealing-back-the-mushrooms). I found her standing like this, unable to interact with her and turn in quests.
![Imgur](https://i.imgur.com/T1hE76J.jpg)

**Expected behaviour**: 
NPC should reset after RP.

**Server Revision**: 
2279

**Comment by Wolffenstein** [comment]
Fixed in rev 2281.

**Comment by Anduyon** [comment]
Not fixed. Same issue persists on live servers.

**Comment by PuffedxO** [comment]
She is still bugged, atm shes standing at the same spot as in the picture above doing nothing :(

**Comment by zhuk90** [comment]
Not fixed, hello
