### ISSUE TITLE
[Dungeon] Shadow Labs [Encounter] Grandmaster Vorpil

### ISSUE THREAD

**Issue by Mewmewww** [Atlantiss/NetherwingBugtracker#2538]
[//]: # (Enclose links to things related to the bug using http://wowhead.com or any other TBC database.)
[//]: # (You can use screenshot ingame to visual the issue.)
[//]: # (Write your tickets according to the format:)
[//]: # ([Quest][Azuremyst Isle] Red Snapper - Very Tasty!)
[//]: # ([NPC] Magistrix Erona)
[//]: # ([Spell][Mage] Fireball)
[//]: # ([Npc][Drop] Ghostclaw Lynx)
[//]: # ([Web] Armory doesnt work)

**Description**: 
After his teleport -> Rain of Fire phase, all voidwalkers ran away from him.
**Current behaviour**:
Voidwalkers ran away from him instead of trying to merge with him.
**Expected behaviour**: 
Voidwalkers should try to merge with him instead of running away.
**Server Revision**: 
2279

**Comment by ircfelix** [comment]
Correct.
https://www.youtube.com/watch?v=v-Z7XBj-J5k (around 1:15 you can see the expected behaviour)

**Comment by Wolffenstein** [comment]
Fixed
