### ISSUE TITLE
"Tracking" interface minor issue - Food & Drink vendor not showing on minimap

### ISSUE THREAD

**Issue by mhdemn** [Atlantiss/NetherwingBugtracker#2539]
**Description**: [Xerintha Ravenoak](https://db.excalibur.ws/?npc=20916) is a <Food & Drink> vendor in Evergrove, BEM.

**Current behaviour**: doesn't show up on minimap when tracking Food & Drink vendors. She even has the <Food & Drink> tag in her name.

As a note, so far while leveling I found it a common thing for NPCs that sell stuff from various types to sometimes not be tagged as a vendor of X thing but do show up on minimap when tracking Y and Z that they also sell. This NPC though is the first one that only sells X that isn't tagget as an X vendor.

**Expected behaviour**: shows up on minimap when tracking these vendors.

**Server Revision**: 2279

**Comment by Easyfraggy** [comment]
Possibly client issue? I remember having same bug on Felmyst.

**Comment by mhdemn** [comment]
definitely the kind of thing that I'd assume is client-side based. But I can't get it to work anyhow, with or without addons, freshly deleted cache / error folders...

minor issue amongst trivial issues anyway

**Comment by mhdemn** [comment]
Found another bug in the Matrix, this fella [Dealer Digriz](https://db.excalibur.ws/?npc=19534) in Netherstorm is the opposite to the other case, since he gets tracked as a food & drink vendor and he sells none of these.

**Comment by toto6** [comment]
Fixed in Rev 2329.

This is not a client issue. If you encounter the same bug with other "Tracking" on the minimap, please report them.
