### ISSUE TITLE
[Quest][NPC] Counterattack!

### ISSUE THREAD

**Issue by manslaughter** [Atlantiss/NetherwingBugtracker#254]
**Description**: This is a quest given by Rethgar Deathgate in the barrens after you've killed the 3 kolkar leaders.

**Current behaviour**: Both friendly and enemy NPCs will stand stationary if their target dies and will not regenerate health or leash.

**Expected behaviour**: NPCs will leash and evade/regen HP when not in combat.

**Server Revision**: 2032 rev 203

**Comment by wtRCH** [comment]
@Pelekon

**Comment by pelekon** [comment]
fixed in rev 2182
