### ISSUE TITLE
[Dungeon] Shadow Labs Gauntlet [Entrance to Murmur up till Murmur]

### ISSUE THREAD

**Issue by Mewmewww** [Atlantiss/NetherwingBugtracker#2540]
[//]: # (Enclose links to things related to the bug using http://wowhead.com or any other TBC database.)
[//]: # (You can use screenshot ingame to visual the issue.)
[//]: # (Write your tickets according to the format:)
[//]: # ([Quest][Azuremyst Isle] Red Snapper - Very Tasty!)
[//]: # ([NPC] Magistrix Erona)
[//]: # ([Spell][Mage] Fireball)
[//]: # ([Npc][Drop] Ghostclaw Lynx)
[//]: # ([Web] Armory doesnt work)

**Description**: 
Combat bug.
**Current behaviour**:
Combat bug after killing the first pack, fixed after killing second pack.
**Expected behaviour**: 
No combat bug should occur.
**Server Revision**: 
2279

**Comment by Wolffenstein** [comment]
Should be fixed now
