### ISSUE TITLE
[Spell] Intervene, Intercept, Charge

### ISSUE THREAD

**Issue by Mewmewww** [Atlantiss/NetherwingBugtracker#2541]
[//]: # (Enclose links to things related to the bug using http://wowhead.com or any other TBC database.)
[//]: # (You can use screenshot ingame to visual the issue.)
[//]: # (Write your tickets according to the format:)
[//]: # ([Quest][Azuremyst Isle] Red Snapper - Very Tasty!)
[//]: # ([NPC] Magistrix Erona)
[//]: # ([Spell][Mage] Fireball)
[//]: # ([Npc][Drop] Ghostclaw Lynx)
[//]: # ([Web] Armory doesnt work)

**Description**: 
Problems with Intervene, Intercept, Charge
**Current behaviour**:
Charged murmur and I walked back 30 yards away from him. Intercept same problem and sometimes an intervene on a party member causes me to walk back as well. Re-creation/replicating this problem is unknown. I wish I knew what could cause it, but I don't.
**Expected behaviour**: 
Should not walk back randomly. 
**Server Revision**: 
2279

**Comment by Mikik3jr** [comment]
I saw it. It is like you are repositioning yourself.

**Comment by Easyfraggy** [comment]
https://github.com/Atlantiss/NetherwingBugtracker/issues/1165

**Comment by Mewmewww** [comment]
Just adding what caused this here even though wolf knows - group mindcontrol. If you fight as Drain Vs Satyr. Intercepting, charging or intervening anyone will cause you to waddle towards Satyr.

**Comment by Jacksn5** [comment]
Feral Charge is also affected, I wanted to stay at the Zealot but it autowalked back, most likely connected to Mind Control Incite Chaos from [Blackheart the Inciter](https://db.excalibur.ws/?npc=20637#controlled-abilities)
[![Post Charge Auto Walk Rev 2452](http://img.youtube.com/vi/LPkgDeAJpdg/0.jpg)](https://www.youtube.com/watch?v=LPkgDeAJpdg "Post Charge Auto Walk Rev 2452")

**Comment by Wolffenstein** [comment]
Fixed in rev 2457.
