### ISSUE TITLE
[Quest] Kindness

### ISSUE THREAD

**Issue by AxeCell** [Atlantiss/NetherwingBugtracker#2542]
**Description**: 
Mordenai at Netherwing Fields in Shadowmoon Valley wants you to feed 8 Mature Netherwing Drakes.

**Current behaviour**:
Once the Mature Netherwing Drakes have eaten the Carcass, they will "fly" away by doing the netherdrake run animation. Credit for feeding the drakes doesn't apply until 30 seconds after they eat the carcass.

**Expected behaviour**: 
Once they complete their consume animation, the credit should be applied to your quest log. They should also fly back to their original position rather than do the ground running animation.

**Server Revision**:

**Comment by ircfelix** [comment]
https://de.wowhead.com/quest=10804/freundlichkeit#english-comments

> You do not get credit for feeding it until the drake lands, eats the carcass, and says something in draconic

**Comment by Kaini27** [comment]
Revision 2304. feeded drakes keep staying at the ground

**Comment by Firroth** [comment]
Rev 2407, still the same.

![screenshot_3](https://user-images.githubusercontent.com/43505196/49690637-9155f180-fb34-11e8-84a6-d83c89ab5077.png)

**Comment by Godmatik** [comment]
Rev 4014 - works fine now, quest credit given after they done eating the carcass.

Closing.
