### ISSUE TITLE
[Quest] The Cipher of Damnation

### ISSUE THREAD

**Issue by AxeCell** [Atlantiss/NetherwingBugtracker#2543]
**Description**: 
Use the Cipher of Damnation at the Altar of Damnation to summon Cyrukh the Firelord.

Destroy Cyrukh the Firelord and then speak with Earthmender Torlok, also found at the Altar of Damnation.

**Current behaviour**:
After using The Cipher of Damnation, Cyrukh the Firelord will spawn without delay and an animation. The RP event that follows wont happen and you'll have to kill the firelord without the NPCs assisting you.

**Expected behaviour**: 
Expected behaviour displayed in this video:
https://www.youtube.com/watch?v=Gc8FpKDilSI

**Server Revision**:

**Comment by Easyfraggy** [comment]
Strange - this was also bugged on closed beta but not in this way 🤔 The rp did happen.

**Comment by Evolvee** [comment]
rev 2729
