### ISSUE TITLE
[Quest] The Force of Neltharaku

### ISSUE THREAD

**Issue by AxeCell** [Atlantiss/NetherwingBugtracker#2545]
**Description**: 
Neltharaku, flying high above Netherwing Fields in Shadowmoon Valley, wants you to free 5 Enslaved Netherwing Drakes using the Enchanted Nethervine Crystal.

**Current behaviour**:
After freeing an enslaved Netherwing Drake with the Enchanted Nethervine Crystal, the dragon will fly off and die after about 5-10 seconds, giving you 1 additional quest credit, leaving you at 2 total.

**Expected behaviour**: 
After freeing an enslaved Netherwing Drake, the credit should be given once the drake has flied far enough to despawn instead of dying, not when tagged.

**Server Revision**:

**Comment by kwah8787** [comment]
I just did this quest and the "current behavior" you described is no longer happening. What I observed was what you described as "expected behavior".
revision 2756   2/4/19

**Comment by devo6969** [comment]
Can confirm, this is no longer happening, PTR is working fine
PTR - https://www.youtube.com/watch?v=Fes4w8Pjrdo
