### ISSUE TITLE
[NPC] Honor Hold Quartermaster have [Dragonhide robe] on sell.

### ISSUE THREAD

**Issue by Unfairy** [Atlantiss/NetherwingBugtracker#2546]
Honor Hold Quartermaster have [Dragonhide robe] on sell.
Didnt saw any other quartermasters having pvp reputation sets pieces.
![wowscrnshot_111018_183718](https://user-images.githubusercontent.com/41975070/48303193-fc011680-e50f-11e8-800d-785f8cddab3c.jpg)

**Comment by ircfelix** [comment]
https://wowhead.com/item=35360 :
Added in patch 2.4.0.7897

**Comment by aresbrutus** [comment]
Correct item ID = http://db.hellfire-tbc.com/?item=35469

**Comment by aresbrutus** [comment]
Fixed in rev `Castilla`
