### ISSUE TITLE
Latency problems, probably server-sided

### ISSUE THREAD

**Issue by Nicemann1089** [Atlantiss/NetherwingBugtracker#2547]
[//]: # (Enclose links to things related to the bug using http://wowhead.com or any other TBC database.)
[//]: # (You can use screenshot ingame to visual the issue.)
[//]: # (Write your tickets according to the format:)
[//]: # ([Quest][Azuremyst Isle] Red Snapper - Very Tasty!)
[//]: # ([NPC] Magistrix Erona)
[//]: # ([Spell][Mage] Fireball)
[//]: # ([Npc][Drop] Ghostclaw Lynx)
[//]: # ([Web] Armory doesnt work)

https://drive.google.com/file/d/1b83BdZ4N92yEmwHKbH3ZHfOnoD0mO2SQ/view?usp=drivesdk

My connection performance: https://i.imgur.com/y06sXXL.png

**Description**: Since today I face the problem, when casting rapidly consecutive, the latency is jumping from 10 ms to sometimes almost 700 ms between the casts. I am pretty sure it is server-sided. I immediately checked my connection (picture above). FYI I usually had a ping of 10-20 ms on this server.

**Current behaviour**: In the video you can see the red bar of the quartz castbar. Casting feels also very inconsistent.

**Expected behaviour**: 

**Server Revision**: 2281

**Comment by Wolffenstein** [comment]
Should be fixed now
