### ISSUE TITLE
[Talent][Priest] Improved Power Word: Fortitude

### ISSUE THREAD

**Issue by Jarvix1** [Atlantiss/NetherwingBugtracker#2548]
[//]: # (Enclose links to things related to the bug using http://wowhead.com or any other TBC database.)
[//]: # (You can use screenshot ingame to visual the issue.)
[//]: # (Write your tickets according to the format:)
[//]: # ([Quest][Azuremyst Isle] Red Snapper - Very Tasty!)
[//]: # ([NPC] Magistrix Erona)
[//]: # ([Spell][Mage] Fireball)
[//]: # ([Npc][Drop] Ghostclaw Lynx)
[//]: # ([Web] Armory doesnt work)

**Description**: Putting points into Improved Power Word: Fortitude gives the increased effect on the spell description, but not when you actually use it.

**Current behaviour**: Power Word: Fortitude is not receiving the percent increase from the Improved: Power Word Fortitude talent.

**Expected behaviour**: Improved Power Word: Fortitude would give the extra 30% increase to the spell, not just on the tooltip.

**Server Revision**: [2284]
![pwf](https://user-images.githubusercontent.com/33297516/48303776-e9211e80-e4dc-11e8-81c6-3b69b7ab8254.png)

**Comment by Wolffenstein** [comment]
The tooltip displays wrong info (can't control it, clientside issue) but the actual buff/talent works properly.
