### ISSUE TITLE
pandemonius - when he phases out and spell reflects the spells do no damage to the player

### ISSUE THREAD

**Issue by rasin00** [Atlantiss/NetherwingBugtracker#2549]
[//]: # (Enclose links to things related to the bug using http://wowhead.com or any other TBC database.)
[//]: # (You can use screenshot ingame to visual the issue.)
[//]: # (Write your tickets according to the format:)
[//]: # ([Quest][Azuremyst Isle] Red Snapper - Very Tasty!)
[//]: # ([NPC] Magistrix Erona)
[//]: # ([Spell][Mage] Fireball)
[//]: # ([Npc][Drop] Ghostclaw Lynx)
[//]: # ([Web] Armory doesnt work)

**Description**: 

**Current behaviour**:

**Expected behaviour**: 

**Server Revision**:

**Comment by rasin00** [comment]
Also same with spell reflecting mobs in SP they either eat the spell and take damage or they reflect it and player takes no damage

**Comment by Wolffenstein** [comment]
Fixed in rev 2286.
