### ISSUE TITLE
[NPC] Frostmane Headhunter

### ISSUE THREAD

**Issue by Unryzen** [Atlantiss/NetherwingBugtracker#255]
**Description**: 
[Frostmane Headhunters](https://www.wowhead.com/npc=1123/frostmane-headhunter) are ignoring LoS. I don't know if that's the case with every mob with throw ability, but these mobs really throw those spears through trees and hills.

**Current behaviour**:
Currently they are ignoring trees and smaller hills with their throw ability.

**Expected behaviour**: 
Mob throw skill should work like spell casting when it comes to Line of Sight.

**Server Revision**: 
2032

**Comment by Godmatik** [comment]
It was Blizzlike that trees and hills did not provide LoS

**Comment by Easyfraggy** [comment]
Blizzlike, if they shoot through trees and objects like that - Cave walls etc on the other hand please do reopen if that is the case.
