### ISSUE TITLE
[Quest][Netherstorm] When the Cows Come Home

### ISSUE THREAD

**Issue by Kaini27** [Atlantiss/NetherwingBugtracker#2551]
[//]: # (Enclose links to things related to the bug using http://wowhead.com or any other TBC database.)
[//]: # (You can use screenshot ingame to visual the issue.)
[//]: # (Write your tickets according to the format:)
[//]: # ([Quest][Azuremyst Isle] Red Snapper - Very Tasty!)
[//]: # ([NPC] Magistrix Erona)
[//]: # ([Spell][Mage] Fireball)
[//]: # ([Npc][Drop] Ghostclaw Lynx)
[//]: # ([Web] Armory doesnt work)

**Description**: Quest ID 10337 **When the Cows Come Home**

**Current behaviour**: Ignores everything and keeps going.

**Expected behaviour**: Should wait until combat is finished plus a couple of seconds more and stop when combat begins.

**Server Revision**: 2282

**Comment by Ahmpy** [comment]
https://www.youtube.com/watch?v=Vx_Y0CwcQ6U bessy should attack mobs.
