### ISSUE TITLE
Missing [[NPC]Scarlet Disciple#4285 outside of Scarlet Monastery Dungeons

### ISSUE THREAD

**Issue by Tenoutoften** [Atlantiss/NetherwingBugtracker#2552]
**Description**: 
Missing [[NPC]Scarlet Disciple#4285](https://www.wowhead.com/npc=4285/scarlet-disciple) just outside of the dungeon portals, can be seen [here](https://youtu.be/GybA7FS8mXI?t=362)
![9c436594558bcaeee6f23c1322344ab0](https://user-images.githubusercontent.com/34839199/48304037-0a9cfd00-e513-11e8-8d23-82e3372f38e6.png)

**Expected behaviour**: 
Expect a pair to be standing here facing each other and do talking animation.

**Server Revision**: 
2282

**Comment by aresbrutus** [comment]
Fixed in rev `Vesta`
