### ISSUE TITLE
[Quest] A Boaring Time for Grulloc - no real trouble for the player, visual/Roleplayey thing

### ISSUE THREAD

**Issue by mhdemn** [Atlantiss/NetherwingBugtracker#2554]
**Description**: in this [quest](https://db.excalibur.ws/?quest=10721) you use the given [whistle](https://db.excalibur.ws/?item=31350) item to summon this boar that will get Grulloc's aggro and then run away chased by him to keep him busy, as seen in this [retail vid](https://www.youtube.com/watch?v=WNIK82wT-gQ). Not TBC footage, but agrees with quest's description.

**Current behaviour**: [The boar fights him until death](https://youtu.be/ApD5el1Y7MQ).

**Expected behaviour**: Boar gets aggro and runs away with Grulloc on his tail. Unsure about how that ends though, guess boar despawns after a short while and Grulloc returns.

**Server Revision**: 2282

**Comment by ircfelix** [comment]
https://www.wowhead.com/quest=10721/a-boaring-time-for-grulloc

Comments state expected behaviour:

> 

By Ilphin (5,371 –  1·15·26)  on 2007/11/06 (Patch 2.2.3) |   |  
-- | -- | --

>

**Comment by mhdemn** [comment]
> https://www.wowhead.com/quest=10721/a-boaring-time-for-grulloc
> 
> Comments state expected behaviour:
> 
> > 
> 
> By Ilphin (5,371 – 1·15·26) on 2007/11/06 (Patch 2.2.3)	 	 
> >

Thanks! Here's a screenshot of the one he mentions:
![image](https://user-images.githubusercontent.com/25901582/48304668-93209b00-e51d-11e8-8c84-a3eeda23e1cd.png)

**Comment by 5f3759** [comment]
The boar doesn't aggro Grulloc anymore, it just stands there.
You blow the whistle, boar spawns, nothing more happens. To complete this quest you either need to have a pet or a friend to pull Grulloc.

**Comment by danbopes** [comment]
Confirmed: @Evolvee

**Comment by Evolvee** [comment]
fixed
