### ISSUE TITLE
[Dungeon] Botanica [Encounter] First boss

### ISSUE THREAD

**Issue by Mewmewww** [Atlantiss/NetherwingBugtracker#2557]
[//]: # (Enclose links to things related to the bug using http://wowhead.com or any other TBC database.)
[//]: # (You can use screenshot ingame to visual the issue.)
[//]: # (Write your tickets according to the format:)
[//]: # ([Quest][Azuremyst Isle] Red Snapper - Very Tasty!)
[//]: # ([NPC] Magistrix Erona)
[//]: # ([Spell][Mage] Fireball)
[//]: # ([Npc][Drop] Ghostclaw Lynx)
[//]: # ([Web] Armory doesnt work)

**Description**: 
The adds infront of the boss.
**Current behaviour**:
They were linked, so we had to kill them all at the same time. Same problem with SLABS.
**Expected behaviour**: 
Not supposed to be linked. 
**Server Revision**: 
2282

**Comment by Easyfraggy** [comment]
Think this may have bugged because we changed the basic assist state of formations - 

Need to make their assist radius a few yards same in slabs - they are hardlinked correctly (last time I checked).

**Comment by Easyfraggy** [comment]
https://github.com/Atlantiss/AtlantissTBCBT/issues/2102 <- closed linking issue

**Comment by Wolffenstein** [comment]
Fixed in rev 2292.
