### ISSUE TITLE
[Dungeon] Botanica [NPC] Mutate Fleshlasher

### ISSUE THREAD

**Issue by Mewmewww** [Atlantiss/NetherwingBugtracker#2558]
[//]: # (Enclose links to things related to the bug using http://wowhead.com or any other TBC database.)
[//]: # (You can use screenshot ingame to visual the issue.)
[//]: # (Write your tickets according to the format:)
[//]: # ([Quest][Azuremyst Isle] Red Snapper - Very Tasty!)
[//]: # ([NPC] Magistrix Erona)
[//]: # ([Spell][Mage] Fireball)
[//]: # ([Npc][Drop] Ghostclaw Lynx)
[//]: # ([Web] Armory doesnt work)

**Description**: 
Too much rep.
**Current behaviour**:
13 rep pr. kill - too much.
**Expected behaviour**: 
Should only give 2 rep pr. kill
**Server Revision**: 
2282

**Comment by Wolffenstein** [comment]
Fixed in rev 2292.
