### ISSUE TITLE
[Dungeon] Botanica [Spell] Poison Cloud

### ISSUE THREAD

**Issue by Mewmewww** [Atlantiss/NetherwingBugtracker#2559]
[//]: # (Enclose links to things related to the bug using http://wowhead.com or any other TBC database.)
[//]: # (You can use screenshot ingame to visual the issue.)
[//]: # (Write your tickets according to the format:)
[//]: # ([Quest][Azuremyst Isle] Red Snapper - Very Tasty!)
[//]: # ([NPC] Magistrix Erona)
[//]: # ([Spell][Mage] Fireball)
[//]: # ([Npc][Drop] Ghostclaw Lynx)
[//]: # ([Web] Armory doesnt work)

**Description**: 
The poison cloud.
**Current behaviour**:
Poision cloud is very transparent - I believe it should be more visible.
**Expected behaviour**: 
More visibility, almost invisible.
**Server Revision**: 
2282

**Comment by Easyfraggy** [comment]
Need proof it should be more visible.

**Comment by ircfelix** [comment]
U referring to Laj fight? https://www.youtube.com/watch?v=h-mzL1K6jlE 4:40

**Comment by Wolffenstein** [comment]
I don't control that spell effect.
