### ISSUE TITLE
Graveyard for Cave in Valley of Trials

### ISSUE THREAD

**Issue by wtRCH** [Atlantiss/NetherwingBugtracker#256]
[//]: # (Enclose links to things related to the bug using http://wowhead.com or any other TBC database.)
[//]: # (You can use screenshot ingame to visual the issue.)
[//]: # (Write your tickets according to the format:)
[//]: # ([Quest][Azuremyst Isle] Red Snapper - Very Tasty!)
[//]: # ([NPC] Magistrix Erona)
[//]: # ([Spell][Mage] Fireball)
[//]: # ([Npc][Drop] Ghostclaw Lynx)
[//]: # ([Web] Armory doesnt work)

**Description**: If you die inside the cave near the mob that is required to kill for the quest you will be appear in Razor Hill GY which is wrong. You should be appearing at Valley of Trials GY

**Comment by Jezofine** [comment]
>Map: 1 (Kalimdor) Zone: 14 (Durotar) Area: 365 (Burning Blade Coven) 
X: -53.250000, -4323.343750, 66.967499 Orientation: 2.954227 
grid[31,23]cell[14,14] InstanceID: 0 
ZoneX: 44.649529 ZoneY: 52.810871 
GroundZ: 138.973022 FloorZ: 66.967499 Have height data (Map: 1 VMap: 1 Col: 1)

![wowscrnshot_120518_184956](https://user-images.githubusercontent.com/2833746/49517802-d53fc100-f8be-11e8-8c26-98601617fbe4.jpg)
![wowscrnshot_120518_185037](https://user-images.githubusercontent.com/2833746/49517807-d7098480-f8be-11e8-87ce-b5934721a602.jpg)
It happens in a some radius around that spot, least at:
>Map: 1 (Kalimdor) Zone: 14 (Durotar) Area: 365 (Burning Blade Coven) 
X: -26.303268, -4328.331543, 69.659309 Orientation: 0.948647 
grid[31,23]cell[15,14] InstanceID: 0 
ZoneX: 44.743862 ZoneY: 52.046425 
GroundZ: 124.243568 FloorZ: 69.659081 Have height data (Map: 1 VMap: 1 Col: 1)

I also died 2 times in slightly different places near Yarrog Baneshadow, but spawned correctly at Valley of Trials' GY.

**Comment by Wolffenstein** [comment]
Fixed in rev 2470.
