### ISSUE TITLE
[Dungeon] Botanica [Room with Laj]

### ISSUE THREAD

**Issue by Mewmewww** [Atlantiss/NetherwingBugtracker#2560]
[//]: # (Enclose links to things related to the bug using http://wowhead.com or any other TBC database.)
[//]: # (You can use screenshot ingame to visual the issue.)
[//]: # (Write your tickets according to the format:)
[//]: # ([Quest][Azuremyst Isle] Red Snapper - Very Tasty!)
[//]: # ([NPC] Magistrix Erona)
[//]: # ([Spell][Mage] Fireball)
[//]: # ([Npc][Drop] Ghostclaw Lynx)
[//]: # ([Web] Armory doesnt work)

**Description**: 
The NPCs (whatever zombies).
**Current behaviour**:
They're all catergorized as "beasts" - should not have such
**Expected behaviour**: 
Should be non-categorized. 
**Server Revision**: 
2282

**Comment by Wolffenstein** [comment]
ServerToClient: SMSG_QUERY_CREATURE_RESPONSE (0x267D) Length: 109 ConnIdx: 0 Time: 04/19/2016 21:12:49.349 Number: 1382
Entry: 19513
Leader: False
Name: Mutate Fear-Shrieker
Type Flags: DoNotPlayWoundParryAnimation (8)
Creature Type Flags 2: 0
**CreatureType: Beast (1)**

ServerToClient: SMSG_QUERY_CREATURE_RESPONSE (0x267D) Length: 102 ConnIdx: 0 Time: 04/19/2016 21:12:49.349 Number: 1383
Entry: 19865
Leader: False
Name: Mutate Horror
Type Flags: DoNotPlayWoundParryAnimation (8)
Creature Type Flags 2: 0
**CreatureType: Beast (1)**

WoWWiki also confirms they're supposed to be beasts.
