### ISSUE TITLE
[Dungeon] Botanica [Boss] Laj

### ISSUE THREAD

**Issue by Mewmewww** [Atlantiss/NetherwingBugtracker#2561]
[//]: # (Enclose links to things related to the bug using http://wowhead.com or any other TBC database.)
[//]: # (You can use screenshot ingame to visual the issue.)
[//]: # (Write your tickets according to the format:)
[//]: # ([Quest][Azuremyst Isle] Red Snapper - Very Tasty!)
[//]: # ([NPC] Magistrix Erona)
[//]: # ([Spell][Mage] Fireball)
[//]: # ([Npc][Drop] Ghostclaw Lynx)
[//]: # ([Web] Armory doesnt work)

**Description**: 
Laj teleport
**Current behaviour**:
When Laj teleports, he summons two treants, but he needs to stand still on the platform for a couple of seconds instead of attacking immediately. 
**Expected behaviour**: 
He should do a summon animation, and then attack us. https://www.youtube.com/watch?v=xAEPa25JPJs
**Server Revision**: 
2282

**Comment by ircfelix** [comment]
Laj fight 4:40
https://www.youtube.com/watch?v=h-mzL1K6jlE

**Comment by Wolffenstein** [comment]
Fixed in rev 2292.
