### ISSUE TITLE
[Dungeon] Laj Summoned Treants

### ISSUE THREAD

**Issue by Mewmewww** [Atlantiss/NetherwingBugtracker#2562]
[//]: # (Enclose links to things related to the bug using http://wowhead.com or any other TBC database.)
[//]: # (You can use screenshot ingame to visual the issue.)
[//]: # (Write your tickets according to the format:)
[//]: # ([Quest][Azuremyst Isle] Red Snapper - Very Tasty!)
[//]: # ([NPC] Magistrix Erona)
[//]: # ([Spell][Mage] Fireball)
[//]: # ([Npc][Drop] Ghostclaw Lynx)
[//]: # ([Web] Armory doesnt work)

**Description**: 
They're not using their abilities.
**Current behaviour**:
They do not use any abiltiies, they only melee as far as we saw.
**Expected behaviour**: 
Once the treants are spawned, one should use Mind Flay, the other should throw thorns at us. They should stand on their summon platforms for a while, and once done with casting, then they should melee.
https://www.youtube.com/watch?v=xAEPa25JPJs
**Server Revision**: 
2282

**Comment by Wolffenstein** [comment]
Fixed in rev 2292.
