### ISSUE TITLE
Mission: The Abyss Shelf

### ISSUE THREAD

**Issue by Daggotur** [Atlantiss/NetherwingBugtracker#2564]
[//]: #https://www.wowhead.com/quest=10162/mission-the-abyssal-shelf (Enclose links to things related to the bug using http://wowhead.com or any other TBC database.)
[//]: # (You can use screenshot ingame to visual the issue.)
[//]: # (Write your tickets according to the format:)
[//]: # ([Quest][Azuremyst Isle] Red Snapper - Very Tasty!)
[//]: # ([NPC] Magistrix Erona)
[//]: # ([Spell][Mage] Fireball)
[//]: # ([Npc][Drop] Ghostclaw Lynx)
[//]: # ([Web] Armory dosnt work)

**Description**: Bomb throwing quest

**Current behaviour**: Right now when you throw a bomb you immediately kill mobs with it

**Expected behaviour**: Mobs should die when the bomb lands and not when you throw it same is true for the previous quest https://www.wowhead.com/quest=10129/mission-gateways-murketh-and-shaadraz

**Server Revision**:

**Comment by Wolffenstein** [comment]
Fixed in rev 2292.
