### ISSUE TITLE
[Spell][Hunter] Hunter's Mark can't be refreshed

### ISSUE THREAD

**Issue by scarabadookie** [Atlantiss/NetherwingBugtracker#2565]
[//]: # (Enclose links to things related to the bug using http://wowhead.com or any other TBC database.)
[//]: # (You can use screenshot ingame to visual the issue.)
[//]: # (Write your tickets according to the format:)
[//]: # ([Quest][Azuremyst Isle] Red Snapper - Very Tasty!)
[//]: # ([NPC] Magistrix Erona)
[//]: # ([Spell][Mage] Fireball)
[//]: # ([Npc][Drop] Ghostclaw Lynx)
[//]: # ([Web] Armory doesnt work)

**Description**: 
Can't refresh same rank Hunter's Mark on a target.

**Current behaviour**:
Trying to re-cast Hunter's Mark gives "A more powerful spell is already active", at least with 5/5 in the talent Improved Hunter's Mark.
 
**Expected behaviour**: 
Same rank and talent level Hunter's Mark should be refreshable before it wears off.

**Server Revision**: 
2282

**Comment by Wolffenstein** [comment]
Fixed in rev 2297.
