### ISSUE TITLE
[NPC] Protean Nightmare

### ISSUE THREAD

**Issue by AxeCell** [Atlantiss/NetherwingBugtracker#2567]
**Description**: 
The Protean Nightmare patrols in the 2nd Arcatraz room.

**Current behaviour**:
One pack patrols up to the platform and stacks on top of another pack of adds that are stationary. 

**Expected behaviour**: 
The packs should patrol different sections of the room. 
Time Stamp for Reference: https://youtu.be/Al3Qyici4LA?t=63

**Server Revision**: 
2282

**Comment by Wolffenstein** [comment]
Fixed in rev 2292.
