### ISSUE TITLE
[NPC] Entropic Eye

### ISSUE THREAD

**Issue by AxeCell** [Atlantiss/NetherwingBugtracker#2569]
**Description**: 
Entropic Eye enemy located in the 1st boss room of Arcatraz.

**Current behaviour**:
Cleave hits in a 360 degree angle. 
The Entropic Eye does not apply debuffs to the group.

**Expected behaviour**: 
Shouldn't have its cleave reach behind itself?
Should more frequently debuff the group with its breath attack. Should also hex targets.
Time stamp for reference: https://youtu.be/Al3Qyici4LA?t=260 | https://youtu.be/Al3Qyici4LA?t=393

**Server Revision**: 
2282

**Comment by Mikik3jr** [comment]
I saw some disease effect during the fight, but no debuff was applied.
https://www.wowhead.com/npc=20868/entropic-eye#abilities

**Comment by Wolffenstein** [comment]
Fixed in rev 2292.
