### ISSUE TITLE
[Quest] Zereketh the Unbound

### ISSUE THREAD

**Issue by AxeCell** [Atlantiss/NetherwingBugtracker#2571]
**Description**: 
Topic is about the Consumption ability used by Zereketh the Unbound.

**Current behaviour**:
Consumption wont be place in a fixed location, but will instead move around at seemingly random dealing a ton of damage to players. Also does no damage to Pets.
There was also a weird interaction where something only dealt 2 damage during the fight.

**Expected behaviour**: 
Consumption should only be locked to where it initially spawns.

**Server Revision**: 
2282

**Comment by Wolffenstein** [comment]
Fixed in rev 2292.
