### ISSUE TITLE
[NPC] Arcatraz Sentinel

### ISSUE THREAD

**Issue by AxeCell** [Atlantiss/NetherwingBugtracker#2572]
**Description**: 
Topic is about the Arcatraz Sentinel enemy as a whole.

**Current behaviour**:
The health bar displayed as 40/total health instead of 40% of their total health.
When it detonated, it would come back alive(unattackeble) and chase down the hunter. Once the hunter feign death it would properly die.
The lightning from their corpse rarely hits a player, and it will only hit 1 player at maximum.
The Arcatraz Sentinel wont attack unless provoked.
The Arcatraz Sentinel keeps its lightning (de)buff while dead for a very(infinite?) long duration.

**Expected behaviour**: 
Should display 40% health. 
Once dead, it should stay dead.
The lightning from their corpse should hit one target every second: https://youtu.be/Al3Qyici4LA?t=434
The Arcatraz Sentinel should aggro unto players.
The lightning (de)buff should disappear after a shortish time.

**Server Revision**: 
2282

**Comment by Easyfraggy** [comment]
Need proof that it should hit everyone - never heard of this - it just ticks fast, hits 1 person at a time.

The agro reset used to work not sure why it stopped. 
The Lightning debuff should disappear 10-20 seconds after death.

**Comment by Wolffenstein** [comment]
Fixed in rev 2292.

**Comment by Easyfraggy** [comment]
There still seems to be a problem with the pulsing lightning debuff - it shoots at twice the rate it should:

https://gfycat.com/FirmGrotesqueDeermouse

And sometimes it doesn't shoot at all - but seems to happen when multiple players where some are out of range? Does it have some threat mechanic atm? It should just hit closest target in range.

**Comment by AxeCell** [comment]
I would also like to add that they can be slowed. I am not sure if this is intended.

**Comment by Tereneckla** [comment]
fixed as of 3236
