### ISSUE TITLE
[NPC] Negaton Screamer

### ISSUE THREAD

**Issue by AxeCell** [Atlantiss/NetherwingBugtracker#2574]
**Description**: 
Topic is regarding the Negaton Screamer's spell usage.

**Current behaviour**:
Should use its spells more frequently. Group had to deliberately wait a long time without attacking just to see its spells ever being used.

**Expected behaviour**: 
Should frequently cast its abilities.

**Server Revision**: 
2282

**Comment by Wolffenstein** [comment]
Fixed in rev 2292.

**Comment by Easyfraggy** [comment]
These mobs gain immunity from debuffs that don't deal damage - They should only change their "buff" when hit by damaging spell.

**Comment by Evolvee** [comment]
![image](https://user-images.githubusercontent.com/1942409/48982984-a325a680-f0e9-11e8-89fb-6b4890d0425e.png)

**Comment by The14me** [comment]
rev.3451 casting looks fine.
Can be closed.
