### ISSUE TITLE
[NPC]Vir'aani Arcanist#17150 should keep [Spell]Vir'aani Concentration#33839 up outside of combat. [Misc]Shouldn't attempt to run away

### ISSUE THREAD

**Issue by Tenoutoften** [Atlantiss/NetherwingBugtracker#2575]
**Description**: 
[[NPC]Vir'aani Arcanist#17150](https://www.wowhead.com/npc=17150/viraani-arcanist#abilities) should keep [[Spell]Vir'aani Concentration#33839](https://db.excalibur.ws/?spell=33839) up outside of combat.
Can be seen [here](https://youtu.be/Yp9Dn_8up1Y?t=12)

Shouldn't "attempts to run away in fear!" - keep in mind the buff has been removed on later retail: https://www.wowhead.com/spells?notFound=33839 and it not displaying in these 4 first clips.
https://youtu.be/eOC966oGhAM?t=53
https://youtu.be/eOC966oGhAM?t=72
https://youtu.be/eOC966oGhAM?t=111
https://youtu.be/eOC966oGhAM?t=131 

https://youtu.be/Yp9Dn_8up1Y?t=23
https://youtu.be/Yp9Dn_8up1Y?t=58
https://youtu.be/Yp9Dn_8up1Y?t=81
https://youtu.be/Yp9Dn_8up1Y?t=127

**Current behaviour**:
Only uses [[Spell]Vir'aani Concentration#33839](https://db.excalibur.ws/?spell=33839) in combat.
"Attempts to run away in fear!"

**Expected behaviour**: 
Keep [[Spell]Vir'aani Concentration#33839](https://db.excalibur.ws/?spell=33839) on outside of combat.
Shouldn't "attempts to run away in fear!"

**Server Revision**: 
2282

**Comment by Tenoutoften** [comment]
Hold for a little, I think that is a private server video... 
https://youtu.be/ykqDWwbf9zQ?t=27 this mob doesn't have [[Spell]Vir'aani Concentration#33839](https://db.excalibur.ws/?spell=33839) outside of combat

**Comment by Tenoutoften** [comment]
I think this is all just private server stuff...

**Comment by Tenoutoften** [comment]
Nvm, I think this is legit plus I found a third source.. apparently the death knight plays at the Drak'Thul realm realm

**Comment by Wolffenstein** [comment]
Fixed in rev 3404.
