### ISSUE TITLE
[NPC] Eredar Deathbringer

### ISSUE THREAD

**Issue by AxeCell** [Atlantiss/NetherwingBugtracker#2576]
**Description**: 
Topic is related to the cleave and aura ability on the NPC.

**Current behaviour**:
The cleave will hit in a 360 degree angle.
Once you enter the Eredar Deathbringer's aura you'll enter combat with it and it will target you while being unattackble through evades. The NPC will engage once his threat switches to a different target like a healer with heal aggro.

**Expected behaviour**: 
Should the cleave be 180 instead of 360 degree?
The aura shouldn't put you in combat, and if it did, it wouldn't cause the enemy to evade.

**Server Revision**: 
2282

**Comment by Wolffenstein** [comment]
Fixed in rev 2292.
