### ISSUE TITLE
[Quest][Netherstorm]Securing the Shaleskin Shale

### ISSUE THREAD

**Issue by Matija5** [Atlantiss/NetherwingBugtracker#2577]
[//]: # (Enclose links to things related to the bug using http://wowhead.com or any other TBC database.)
[//]: # (You can use screenshot ingame to visual the issue.)
[//]: # (Write your tickets according to the format:)
[//]: # ([Quest][Azuremyst Isle] Red Snapper - Very Tasty!)
[//]: # ([NPC] Magistrix Erona)
[//]: # ([Spell][Mage] Fireball)
[//]: # ([Npc][Drop] Ghostclaw Lynx)
[//]: # ([Web] Armory doesnt work)

**Description**: I think that drop rate of shaleskin shale is lower then it should be, according to wowdb it's supposed to have 36%, wowhead says 50% (but thats probablly not in tbc) and I killed 48 of them and have 4 of them. Dubt that 36% drop rate and that 5 didn't drop from 48 of them. I'm not sure once again just something i noticed

https://www.wowdb.com/items/29464-shaleskin-shale
**Current behaviour**:

**Expected behaviour**: 

**Server Revision**:

**Comment by Wolffenstein** [comment]
I remember them having a shitty drop rate on retail even in WoD

**Comment by Matija5** [comment]
Could be, but I can't be that unlucky, if it's 36% drop rate

**Comment by Wolffenstein** [comment]
Very much possible, yes

**Comment by Matija5** [comment]
yeah I'm most likely, well should i delete or will u close?

**Comment by Wolffenstein** [comment]
Leave it open

**Comment by aresbrutus** [comment]
The drop rates are correct.
