### ISSUE TITLE
[NPC] Sargeron Archer

### ISSUE THREAD

**Issue by AxeCell** [Atlantiss/NetherwingBugtracker#2578]
**Description**:
Topic is related to Sargeon Archer's Scatter Shot ability.

**Current Behaviour**:
Sargeon Archer does not use Scatter Shot.

**Expected Behaviour**:
Sargeron Archer should use Scatter Shot.

**Server Revision**:
2282

**Comment by Tenoutoften** [comment]
[[NPC]Sargeron Archer#20901](https://www.wowhead.com/npc=20901/sargeron-archer#abilities)
[[Spell]Scatter Shot#23601](https://www.wowhead.com/spell=23601/scatter-shot)
![3081a80f4080edddd772f765df714e09](https://user-images.githubusercontent.com/34839199/48307421-967f4b00-e54c-11e8-8f28-ab6183f96d11.png)

**Comment by Easyfraggy** [comment]
![image](https://user-images.githubusercontent.com/36134067/48307476-c24f0080-e54d-11e8-927a-db72263837d2.png)

This SS is from 2.3 🤔

**Comment by AxeCell** [comment]
Makes it more challening and engaging with the rain of fire being able to remove it. :)

**Comment by Wolffenstein** [comment]
Fixed in rev 2292.
