### ISSUE TITLE
[NPC] Vile Fin Minor Oracle

### ISSUE THREAD

**Issue by nycheia** [Atlantiss/NetherwingBugtracker#258]
Nych - Undead Priest

**Description**: 
The murloc will start to flee, but as soon as you melee it, it will stop fleeing instantly and start casting on you again if it has mana. Doesnt seem to do it if it doesnt have mana

**Current behaviour**:
Breaks flee after a single melee swing if it has mana
http://prntscr.com/kxt9ro

**Expected behaviour**: 
Continue to flee for a little bit, and not break flight instantly after 1 melee. 

**Server Revision**: (not sure what to put here)
23-09-2018 21:50 CEST

**Comment by Tereneckla** [comment]
Fixed
