### ISSUE TITLE
[NPC] Harbinger Skyriss

### ISSUE THREAD

**Issue by AxeCell** [Atlantiss/NetherwingBugtracker#2580]
**Description**: 
Topic related to the kill credit provided by Harbinger Skyriss' clones.

**Current behaviour**:
Killing a clone provides identical reputation gain to the boss himself leading to 3 times as much reputation if you kill both clones.

**Expected behaviour**: 
Clones are not supposed to give reputation.

**Server Revision**: 
2282

**Comment by Wolffenstein** [comment]
Fixed in rev 2292.
