### ISSUE TITLE
[NPC][Hellfire Peninsula] Shattered Hand Acolyte

### ISSUE THREAD

**Issue by eryczek1615** [Atlantiss/NetherwingBugtracker#2583]
**Description**: 
[Shattered Hand Acolyte](https://www.wowhead.com/npc=19415/shattered-hand-acolyte#abilities)

**Current behaviour**:
He doesn't use his abilities.

**Expected behaviour**: 
Should use his abilities

**Server Revision**: 
2282

**Comment by Easyfraggy** [comment]
![image](https://user-images.githubusercontent.com/36134067/48307099-2372d600-e546-11e8-9070-cdc4d75ad041.png)

**Comment by Evolvee** [comment]
fixed -.- some retard bound the abilities on "death" events instead of ai initializing
