### ISSUE TITLE
[NPC] This one Mana Wraith spawns in unreachable position - evading bug

### ISSUE THREAD

**Issue by mhdemn** [Atlantiss/NetherwingBugtracker#2585]
Entry: 18864, Id: 11, GUIDLow: 17046

35.1,58.8

![image](https://user-images.githubusercontent.com/25901582/48307599-9e40ee80-e550-11e8-8503-1421d29c8b70.png)

**Server Revision**: 2282

**Comment by Evolvee** [comment]
fixed
