### ISSUE TITLE
Muck Spawn for quest Muck Diving are stationary

### ISSUE THREAD

**Issue by craigsurbrook** [Atlantiss/NetherwingBugtracker#2586]
[//]: # (Enclose links to things related to the bug using http://wowhead.com or any other TBC database.)
[//]: # (You can use screenshot ingame to visual the issue.)
[//]: # (Write your tickets according to the format:)
[//]: # ([Quest][Azuremyst Isle] Red Snapper - Very Tasty!)
[//]: # ([NPC] Magistrix Erona)
[//]: # ([Spell][Mage] Fireball)
[//]: # ([Npc][Drop] Ghostclaw Lynx)
[//]: # ([Web] Armory doesnt work)

**Description**: 
The Muck Spawns are utterly stationary. I realize that this might be an obvious one that was identified in closed beta, but I didn't see any closed or open reports on this in the bug tracker, so I thought I should mention it.

**Current behaviour**:
Muck Spawns don't move.

**Expected behaviour**: 
They move around and pat.

**Server Revision**: 
2282

**Comment by aresbrutus** [comment]
They all have the correct movement type and range. Should be working fine.

**Comment by craigsurbrook** [comment]
If by "working fine" the movement type is "stationary" and the range is 0.
I'm standing in Nagrand looking at 3 mobs just barely in water, and they do not move AT ALL. Ever.
41.6 37.5 are the coords I'm standing at looking at these utterly stationary Muck Spawns.
The others only pat maybe 3yds. I know that this is not what they did in retail.
So, while, in theory, they supposedly have the "correct movement type and range" and "should" be working fine, they aren't.

**Comment by aresbrutus** [comment]
There were 2 Muck spawns with stationary movement, those have been corrected. Ping me on Discord when you are available so we can both check the issue since it looks fine from database.

**Comment by aresbrutus** [comment]
Re-opening for further info

**Comment by Easyfraggy** [comment]
.npc info and typing entry + id in your bug reports helps tremendously!

**Comment by craigsurbrook** [comment]
https://www.youtube.com/watch?v=cidAhmlmB_Q
is from later retail WoW (from 2015) where a Death Knight is doing this quest, and you can see how far the Muck Spawns patrol from their centroid area, and it's pretty far. This looks like what I remember from TBC retail, so I think it represents their proper behavior (and I would posit, it just being my opinion, that they didn't change their behavior in the later expansions).

**Comment by aresbrutus** [comment]
Fixed in rev `Castilla`
