### ISSUE TITLE
[NPC] Talon King Ikiss

### ISSUE THREAD

**Issue by AxeCell** [Atlantiss/NetherwingBugtracker#2587]
**Description**: 
Topic is related to loot table of Talon King Ikiss.

**Current behaviour**:
Talon King Ikiss only drops 1 item alongside the heroic Primal Nether.

**Expected behaviour**: 
Talon King Ikiss should drop 2 items.

**Server Revision**: 
2282

**Comment by Mikik3jr** [comment]
And his poli doesn't break, not even from arcane missles.

**Comment by Easyfraggy** [comment]
Need some proof that it should break.

**Comment by ircfelix** [comment]
https://www.youtube.com/watch?v=W1LGW01ZPsY

In the beginning someone is sheeped and does not get unsheeped from the arcane volley. Around 0:56 the priest is sheeped and does not get unsheeped from taking damage.
At 2:07 you can see him drop a primal nether and at least 2 more items.

**Comment by Easyfraggy** [comment]
also should be 73 rather than 72. 

![image](https://user-images.githubusercontent.com/36134067/48311621-bccfd580-e5a2-11e8-972a-4c9291d56cb9.png)

**Comment by Wolffenstein** [comment]
Fixed in rev 2292.
