### ISSUE TITLE
[NPC][Spell] Conjurer Luminrath - Summon Dancing Sword

### ISSUE THREAD

**Issue by Kaini27** [Atlantiss/NetherwingBugtracker#2588]
[//]: # (Enclose links to things related to the bug using http://wowhead.com or any other TBC database.)
[//]: # (You can use screenshot ingame to visual the issue.)
[//]: # (Write your tickets according to the format:)
[//]: # ([Quest][Azuremyst Isle] Red Snapper - Very Tasty!)
[//]: # ([NPC] Magistrix Erona)
[//]: # ([Spell][Mage] Fireball)
[//]: # ([Npc][Drop] Ghostclaw Lynx)
[//]: # ([Web] Armory doesnt work)

**Description**: Summons 1 Dancing Sword to aid the caster in battle for 30sec.

**Current behaviour**: Summoned Sword is friendly

**Expected behaviour**: Summoned Sword suppose to attack player

**Server Revision**: 2282

**Comment by Evolvee** [comment]
rev vrr
