### ISSUE TITLE
Auto shot and spell queueing mechanics

### ISSUE THREAD

**Issue by Zarant** [Atlantiss/NetherwingBugtracker#259]
During patch 2.3, spell queuing mechanics were added to the game, this change affected most spells in the game, including auto shot.

> Client spell cast requests are now sent to the server even if your player is already casting another spell. This eliminates the need for /stopcasting in macros to compensate for latency. 

Source: http://wowwiki.wikia.com/wiki/Patch_2.3.0

Once the 0.5s Auto Shot cast time starts, it shouldn't be interrupted by other shots, spell casts performed during the Auto Shot wind up time should be queued and handled by the server immediately after the auto shot goes off. Before patch 2.3, specially using fast attack speed weapons or under the effect temporary haste buffs hunters had to compensate for latency by casting steady shot a split second before the auto shot went off. Patch 2.3 added a huge QoL change that completely kicked the latency compensation component out of the DPS rotation.

>In short:
1 - GCD is client only, and starts immediately upon sending the cast to the server
2 - Auto Shot can't be interrupted once the cast starts by other casts
3 - The next cast is "queued up" and began immediatetly after Auto Shot
4 - The server doesn't have any cooldown on Steady Shot. It counts on the client handling that through the GCD

Source: https://web.archive.org/web/20080211131225/http://elitistjerks.com:80/f31/t11420-hunter_beast_mastery_bible/p109/ - see the last post, from January 28th, 2008 (patch 2.3.3)

**Comment by Wolffenstein** [comment]
It should be already working. Did you try it?

**Comment by Zarant** [comment]
it feels like multi-shot is interrupting the auto shot spell cast, i don't have access to higher level characters to test this further

**Comment by Wolffenstein** [comment]
I tested it and it looks fine to me.

**Comment by Easyfraggy** [comment]
seems fixed/non issue?
