### ISSUE TITLE
[NPC] Dreadmaul Ogres (Blasted Lands)

### ISSUE THREAD

**Issue by offcell123** [Atlantiss/NetherwingBugtracker#2590]
[//]: # (Enclose links to things related to the bug using http://wowhead.com or any other TBC database.)
[//]: # (You can use screenshot ingame to visual the issue.)
[//]: # (Write your tickets according to the format:)
[//]: # ([Quest][Azuremyst Isle] Red Snapper - Very Tasty!)
[//]: # ([NPC] Magistrix Erona)
[//]: # ([Spell][Mage] Fireball)
[//]: # ([Npc][Drop] Ghostclaw Lynx)
[//]: # ([Web] Armory doesnt work)

**Description**: 
Dreadmaul Ogres do not seem to be properly animated 
**Current behaviour**:

**Expected behaviour**: 

**Server Revision**:

**Comment by Easyfraggy** [comment]
Need more info. Just saying smth is wrong doesn't tell us anything. What are they doing? And what should they be doing?

If you are talking about specific npc type .npc info ingame and provide entry+id

**Comment by Tenoutoften** [comment]
These look alright to me, perhaps he thought there should be patrols here or something, but this is a dull place...
