### ISSUE TITLE
[NPC] Bleeding Hollow Tormentor - HFP

### ISSUE THREAD

**Issue by offcell123** [Atlantiss/NetherwingBugtracker#2591]
[//]: # (Enclose links to things related to the bug using http://wowhead.com or any other TBC database.)
[//]: # (You can use screenshot ingame to visual the issue.)
[//]: # (Write your tickets according to the format:)
[//]: # ([Quest][Azuremyst Isle] Red Snapper - Very Tasty!)
[//]: # ([NPC] Magistrix Erona)
[//]: # ([Spell][Mage] Fireball)
[//]: # ([Npc][Drop] Ghostclaw Lynx)
[//]: # ([Web] Armory doesnt work)

**Description**: 
Stopped attacking mid fight, also ported back to original starting position after being frost nova'd
**Current behaviour**:

**Expected behaviour**: 

**Server Revision**:

**Comment by Easyfraggy** [comment]
We need a way to recreate or atleast more info .npc info when targetting the mob. Video or screenshots help for example get shareX

**Comment by Tereneckla** [comment]
Dead issue
