### ISSUE TITLE
Dwarf Priest - Character Model disappears in keep hallways (Honor Hold and Zethgor Keep)

### ISSUE THREAD

**Issue by offcell123** [Atlantiss/NetherwingBugtracker#2593]
[//]: # (Enclose links to things related to the bug using http://wowhead.com or any other TBC database.)
[//]: # (You can use screenshot ingame to visual the issue.)
[//]: # (Write your tickets according to the format:)
[//]: # ([Quest][Azuremyst Isle] Red Snapper - Very Tasty!)
[//]: # ([NPC] Magistrix Erona)
[//]: # ([Spell][Mage] Fireball)
[//]: # ([Npc][Drop] Ghostclaw Lynx)
[//]: # ([Web] Armory doesnt work)

**Description**: 
Moving through these keeps the dwarf priest character model would disappear from screen in certain sections then reappear upon exiting that section
**Current behaviour**:

**Expected behaviour**: 
Should not disappear
**Server Revision**:

**Comment by Easyfraggy** [comment]
Client issue. Not possible to be solved afaik.
