### ISSUE TITLE
[NPC] Infernal Warbringer (HFP) aoe aura ticking too often ¬0.1s per tick

### ISSUE THREAD

**Issue by offcell123** [Atlantiss/NetherwingBugtracker#2594]
[//]: # (Enclose links to things related to the bug using http://wowhead.com or any other TBC database.)
[//]: # (You can use screenshot ingame to visual the issue.)
[//]: # (Write your tickets according to the format:)
[//]: # ([Quest][Azuremyst Isle] Red Snapper - Very Tasty!)
[//]: # ([NPC] Magistrix Erona)
[//]: # ([Spell][Mage] Fireball)
[//]: # ([Npc][Drop] Ghostclaw Lynx)
[//]: # ([Web] Armory doesnt work)

**Description**: 
Infernal warbringer aoe damage tick on melee seems to tick far too much. Some mobs are ok others have this problem. Ticks for approx 92 dmg every 0.1 seconds.
**Current behaviour**:

**Expected behaviour**: 

**Server Revision**:

**Comment by Easyfraggy** [comment]
Please use the search function before posting. https://github.com/Atlantiss/NetherwingBugtracker/issues/2334
