### ISSUE TITLE
[Character] Holy Priest Surge of Light - Free smite proc consumed without instant cast

### ISSUE THREAD

**Issue by offcell123** [Atlantiss/NetherwingBugtracker#2595]
[//]: # (Enclose links to things related to the bug using http://wowhead.com or any other TBC database.)
[//]: # (You can use screenshot ingame to visual the issue.)
[//]: # (Write your tickets according to the format:)
[//]: # ([Quest][Azuremyst Isle] Red Snapper - Very Tasty!)
[//]: # ([NPC] Magistrix Erona)
[//]: # ([Spell][Mage] Fireball)
[//]: # ([Npc][Drop] Ghostclaw Lynx)
[//]: # ([Web] Armory doesnt work)

**Description**: 
Holy Priest surge of light not working correctly in some instances, when chain casting and Surge of Light procs it will be consumed but without an instant cast.
**Current behaviour**:

**Expected behaviour**: 

**Server Revision**:

**Comment by Easyfraggy** [comment]
Please search before posting. https://github.com/Atlantiss/NetherwingBugtracker/issues/2065
