### ISSUE TITLE
[Quest] [Blade's Edge] The Hound-Master - not receiving kill credit

### ISSUE THREAD

**Issue by ScottieDOESknow** [Atlantiss/NetherwingBugtracker#2596]
**Description**:

The Hound-Master quest requires Baelmon the Hound-Master killed. Druid provides an Evergrove Wand that summons two giant trees that assist in battle.

**Current behaviour**:

Tried this quest twice using the Evergrove Wand and didn't receive credit for killing Baelmon either try. May have something to do with the trees summoned with Evergrove Wand getting killing blows, etc.

https://gyazo.com/75b33442fe0f8bb19c7ba1852a6cf596

**Expected behaviour**: Should receive credit for kill

**Server Revision**: 2282

**Comment by Easyfraggy** [comment]
https://github.com/Atlantiss/NetherwingBugtracker/issues/2597

**Comment by Novat93** [comment]
Credit was given to me and my Rogue buddy

![killcredit](https://user-images.githubusercontent.com/36829235/48508769-ba45d800-e84f-11e8-9f2e-cf2e8031e536.PNG)

**Comment by ScottieDOESknow** [comment]
Makes sense as well, but how much damage did you both do, compared to the trees?

On first attempt I actually thought my damage output was not enough just as theorized above, but after 2nd attempt this clearly wasn't the case. Level 70 combat spec + food buff + adrenaline rush + blade flurry + attack power trinket + thistle tea = did over 4x more damage than both trees combined.

ONE comment mentioning 'failure to hold aggro' which is rather vague (early TBC 2.0.6)
https://gyazo.com/035bcf27aaa4294b0d7e2deb339a197a

no mention of failures in any of these comments, even those who used the trees (patch 2.0.6 to 2.4.3+)
https://www.wowhead.com/npc=19747/baelmon-the-hound-master#comments

quest completion / trees are "powerful and will do most the damage"
https://gyazo.com/3d2d72ba051cec7fdddde192ef7c6951

My guess: Early on, this quest was bugged in the same manner on live TBC servers, and then fixed.

a) trees are not flagged correctly (pet/party, etc) resulting in failure, due to damage threshold. Similar to when a mob is kited to faction/city guards and they do majority dmg so player loses out on loot and/or XP.

b) trees are not flagged correctly (pet/party, etc) and getting killing blow resulting in failure (same as above)

**Comment by Shanghi** [comment]
I just tested this for someone and:
* it didn't matter if the trees got the killing blow - if I did at least 50% of the damage it worked
* I did 49.9% damage and didn't get credit
* I did 50% damage and got credit
I tried a few times each way and it was always the same.

**Comment by Mikik3jr** [comment]
This is irratitve af, because I didn't deal enough dmg to the elite and didn't get the credit. I tried to do again, but the item had only 1 charge, so I wasn't able to summon the trees again. I dropped the Q, to get it again, so I can use the Q item, but it dropped the q item AND the flare which is required to summon the druid which gives the Q..................

**Comment by Manaci** [comment]
Fixed
