### ISSUE TITLE
[Quest] [Blade's Edge] Fire at Will - south cannon visual bug

### ISSUE THREAD

**Issue by ScottieDOESknow** [Atlantiss/NetherwingBugtracker#2598]
**Description**:  

The quest Fire at Will has player take control of the two fel cannons in Death's Door to destroy portals.

**Current behaviour**:

The southern cannon does not change direction to face towards the portal and/or enemies, but the abilities used to destroy the portal and/or enemies still shoot from the proper side/angle.

clip
https://gyazo.com/1c6a0fbc6a303a38675e1001a1533324

**Expected behaviour**: 

When under control of player, cannon should swivel 360 degrees towards any enemy targeted or face portal (default). 

NOTE: The northern cannon functions as intended.

**Server Revision**:  2282

**Comment by Tereneckla** [comment]
Fixed
