### ISSUE TITLE
[[NPC]Blazzle#28344 should have repair option

### ISSUE THREAD

**Issue by Tenoutoften** [Atlantiss/NetherwingBugtracker#2599]
**Description**: 
[[NPC]Blazzle#28344, ID: 1](https://www.wowhead.com/npc=28344/blazzle#sells) should offer an option to repair. This NPC is located in Netherstorm, Area 52 and holds the title >Blacksmithing Supplies>

**Server Revision**: 
2282

**Comment by Evolvee** [comment]
rev vrr
