### ISSUE TITLE
Full kill credit/loot/xp when your pet kills an enemy without player assistance

### ISSUE THREAD

**Issue by Scylla420** [Atlantiss/NetherwingBugtracker#26]
Hi, any mob killed solely by your pet (Warlock imp in this case, gonna assume it's a global issue,) gives you full xp + loot + kill credit when you should gain nothing if you or someone in your party doesn't participate in the kill.

[NW footage](https://www.youtube.com/watch?v=VlBR9I4OlYA&feature=youtu.be)

[Here's a source](http://wowwiki.wikia.com/wiki/Hunter_pet?oldid=1550252)

"Note: the hunter will not gain loot or experience from a mob the pet kills solo"

Sorry for not finding a better source than wowwiki, although I'm sure everyone knows that this should function this way.

**Comment by Evolvee** [comment]
It should work for hunters already.

**Comment by Wolffenstein** [comment]
Fixed in rev 2020.
