### ISSUE TITLE
Item that regurarly drops: Pitchfork

### ISSUE THREAD

**Issue by Buskmurvel** [Atlantiss/NetherwingBugtracker#260]
I've noticed it drop about 15-20 times from different mobs around lvl 20-25.

https://gyazo.com/2b1df18b3de4ecf5877fbdfd24cd856d

https://gyazo.com/132177e2918f4fc84f628f7ac5a318f6

Seems to be something wrong with the "global loot".

**Comment by Wolffenstein** [comment]
Rather with items the global loot misses.

**Comment by Wolffenstein** [comment]
Fixed in rev 2040.
