### ISSUE TITLE
[Misc][NPC]Shaleskin Flayer#20210 should emote when [Spell]Shaleskin#36576-buff is spent & attempts to run away in fear

### ISSUE THREAD

**Issue by Tenoutoften** [Atlantiss/NetherwingBugtracker#2601]
**Description**: 
[[NPC]Shaleskin Flayer#20210](https://www.wowhead.com/npc=20210/shaleskin-flayer) missing emote
- german - "Der Zauber prallt teilweise an der Haut von Schieferhaultschinder ab."

Think I found an English version here: https://youtu.be/G6fc2FpD-h8?t=13 "Shaleskin Flayer's skin partially deflects the spell."

https://youtu.be/wPClBDqcELw?t=22
https://youtu.be/wPClBDqcELw?t=33

This emote should happen when it's [[Spell]Shaleskin#36576](https://www.wowhead.com/spell=36576/shaleskin) is spent on an incoming magic effect. When a posion is applying /or whatever it is, his buff is spent and the emote is done.

Should also do emote "attempts to run away in fear!" - "Schieferhaultschinder versucht zu fluchten!"
https://youtu.be/wPClBDqcELw?t=23

**Expected behaviour**: 
Expected to do emote when using [[Spell]Shaleskin#36576](https://www.wowhead.com/spell=36576/shaleskin)

**Server Revision**: 
2282

**Comment by Evolvee** [comment]
https://github.com/Atlantiss/AtlantissTBCBT/issues/1308
https://github.com/ccshiro/cc-buglist/issues/2555

**Comment by Evolvee** [comment]
rev vrr

**Comment by Evolvee** [comment]
note that the functionality of the spell is still bugged (the 50% dmg off part on spells)---> needs to be scripted
