### ISSUE TITLE
[Misc][NPC]Spymaster Thalodien#19468missing yellow "?" [Quest]Report to Spymaster Thalodien#11039

### ISSUE THREAD

**Issue by Tenoutoften** [Atlantiss/NetherwingBugtracker#2602]
**Description**: 
[[NPC]Spymaster Thalodien#19468](https://www.wowhead.com/npc=19468/spymaster-thalodien) missing yellow "?" for [[Quest]Report to Spymaster Thalodien#11039](https://www.wowhead.com/quest=11039/report-to-spymaster-thalodien)

![06bc442c03195b2faf3291f92ef8f1bd](https://user-images.githubusercontent.com/34839199/48312058-6e720500-e5a9-11e8-8b1b-4a4cc9e0842b.jpg)

**Expected behaviour**: 
Expect yellow "?"

**Server Revision**: 
2282

**Comment by Evolvee** [comment]
no idea why that happens atm

**Comment by GMThunderan** [comment]
Seems to be fixed: [rev 3228](https://i.imgur.com/iEaa5Od.jpg)

so /close ?
