### ISSUE TITLE
[NPC] Seeping Ooze

### ISSUE THREAD

**Issue by Mikik3jr** [Atlantiss/NetherwingBugtracker#2603]
[//]: # (Enclose links to things related to the bug using http://wowhead.com or any other TBC database.)
[//]: # (You can use screenshot ingame to visual the issue.)
[//]: # (Write your tickets according to the format:)
[//]: # ([Quest][Azuremyst Isle] Red Snapper - Very Tasty!)
[//]: # ([NPC] Magistrix Erona)
[//]: # ([Spell][Mage] Fireball)
[//]: # ([Npc][Drop] Ghostclaw Lynx)
[//]: # ([Web] Armory doesnt work)

**Description**: 
![wowscrnshot_111118_121535](https://user-images.githubusercontent.com/43505031/48312208-89457900-e5ab-11e8-91e6-30cee1a4f678.jpg)

**Current behaviour**:
After casting Seeping Split it creates 2 friendly Seeping Oozes.
![wowscrnshot_111118_121140](https://user-images.githubusercontent.com/43505031/48312217-abd79200-e5ab-11e8-9fcb-78a814e8e9ac.jpg)
**Expected behaviour**: 
I don't think it should spawn friendly targets.
**Server Revision**: 
2282

**Comment by Mikik3jr** [comment]
https://www.wowhead.com/npc=21264/seeping-ooze#comments

**Comment by Easyfraggy** [comment]
Why you heff to be med? They just want to be frens 💘

**Comment by Mikik3jr** [comment]
Even after 10 minutes they are there. I am afraid they are not disappearing.

**Comment by xmesaj2** [comment]
fixed in 2316
