### ISSUE TITLE
[NPC-zone] Combat bug with Tormented Soul

### ISSUE THREAD

**Issue by mhdemn** [Atlantiss/NetherwingBugtracker#2605]
[Tormented Souls](https://db.excalibur.ws/?npc=20512) that are all around the place in this area in NS will get you bugged in combat indefinitely 80% of the times you fight one of them.

Would add video or picture but don't think that would serve any purpose, playing hunter as usual. It's not my pet, FD removes it until a new Soul bugs you again.

**Server Revision**: 2282

**Comment by xmesaj2** [comment]
fixed in 2316
