### ISSUE TITLE
[Misc][NPC]Artifact Seeker#19852, ID: 6,7,9 & 10 missing random movement.

### ISSUE THREAD

**Issue by Tenoutoften** [Atlantiss/NetherwingBugtracker#2606]
**Description**: 
[[NPC]Artifact Seeker#19852, ID: 6,7,9,10](https://www.wowhead.com/npc=19852/artifact-seeker) missing random movement.

Can be seen here:
https://youtu.be/N16mPJ-8RqE?t=22
https://youtu.be/9gRTTL6AfQE?t=28
https://youtu.be/VlqyP2ui5lY?t=39

Currently stands static on NW

**Expected behaviour**: 
Random movement.

**Server Revision**: 
2282

**Comment by Easyfraggy** [comment]
I have not yet started on Netherstorm rewrite! But I will double check these when I do.

**Comment by Tereneckla** [comment]
Number 10 still is static

**Comment by Wolffenstein** [comment]
Fixed in rev 3680.
