### ISSUE TITLE
[Quest][Netherstorm]Bloody Imp-ossible!

### ISSUE THREAD

**Issue by Matija5** [Atlantiss/NetherwingBugtracker#2607]
[//]: # (Enclose links to things related to the bug using http://wowhead.com or any other TBC database.)
[//]: # (You can use screenshot ingame to visual the issue.)
[//]: # (Write your tickets according to the format:)
[//]: # ([Quest][Azuremyst Isle] Red Snapper - Very Tasty!)
[//]: # ([NPC] Magistrix Erona)
[//]: # ([Spell][Mage] Fireball)
[//]: # ([Npc][Drop] Ghostclaw Lynx)
[//]: # ([Web] Armory doesnt work)

**Description**: Imp won't collect blood unless ur extreamly close to warp chaser and attacking it with meele, I as hunter if killed em with ranged imp wouldn't collect blood

**Current behaviour**:

**Expected behaviour**: 

**Server Revision**:

**Comment by Evolvee** [comment]
I will try to increase it, but you will still need to be close to the NPC.

Its even in the quest description:

![image](https://user-images.githubusercontent.com/1942409/48354533-45796f00-e692-11e8-882e-b209f18bb7eb.png)

**Comment by Evolvee** [comment]
rev vrr
