### ISSUE TITLE
[NPC] Naberius [Spell] Consumption dealing too much damage

### ISSUE THREAD

**Issue by Corrozus** [Atlantiss/NetherwingBugtracker#2608]
[//]: # (Enclose links to things related to the bug using http://wowhead.com or any other TBC database.)
[//]: # (You can use screenshot ingame to visual the issue.)
[//]: # (Write your tickets according to the format:)
[//]: # ([Quest][Azuremyst Isle] Red Snapper - Very Tasty!)
[//]: # ([NPC] Magistrix Erona)
[//]: # ([Spell][Mage] Fireball)
[//]: # ([Npc][Drop] Ghostclaw Lynx)
[//]: # ([Web] Armory doesnt work)

**Description**: Same issue as [#2473](https://github.com/Atlantiss/NetherwingBugtracker/issues/2473). Void zone from Naberius dealing an erroneously large amount of damage and it follows you around.

![naberiusvoidfissure](https://user-images.githubusercontent.com/44730894/48313367-af731500-e5bb-11e8-8327-6971ce8c96b0.PNG)

**Current behaviour**: Void zone spell dealing too much damage and follows you around.

**Expected behaviour**: Void zone should only deal 1k/s and remain stationary

**Server Revision**: 2282

**Comment by xmesaj2** [comment]
fixed in 2316
