### ISSUE TITLE
[NPC][Hellfire Peninsula] Shattered Hand Grunt

### ISSUE THREAD

**Issue by eryczek1615** [Atlantiss/NetherwingBugtracker#2610]
**Description**: 
Shattered Hand Grunt

**Current behaviour**:
This grunts are fighting with themselves but one of them have random moevement
https://imgur.com/gKDrz3i

Left grunt
![image](https://user-images.githubusercontent.com/4455568/48314206-77bd9a80-e5c6-11e8-87cd-8b93fb4feeda.png)

Right Grunt
![image](https://user-images.githubusercontent.com/4455568/48314213-8f951e80-e5c6-11e8-953c-826b46a95bc8.png)

**Expected behaviour**: 
Should stand in one place.

**Server Revision**: 
2282

**Comment by Evolvee** [comment]
@Easyfraggy i checked sniffs and it looks correct tho :D

**Comment by Easyfraggy** [comment]
I'm pretty sure I did it after sniffs - I remember also stopping and thinking - Hey this looks weird. Might have to go non blizzlike just for it to not look retarded I guess.

**Comment by Tereneckla** [comment]
Number 6 is the only one that stands still now.

**Comment by Wolffenstein** [comment]
Fixed in rev 3388.
