### ISSUE TITLE
[Spell][hunter]Kill Command

### ISSUE THREAD

**Issue by Matija5** [Atlantiss/NetherwingBugtracker#2611]
[//]: # (Enclose links to things related to the bug using http://wowhead.com or any other TBC database.)
[//]: # (You can use screenshot ingame to visual the issue.)
[//]: # (Write your tickets according to the format:)
[//]: # ([Quest][Azuremyst Isle] Red Snapper - Very Tasty!)
[//]: # ([NPC] Magistrix Erona)
[//]: # ([Spell][Mage] Fireball)
[//]: # ([Npc][Drop] Ghostclaw Lynx)
[//]: # ([Web] Armory doesnt work)

**Description**: You are able to cast kill command while your pet is dead, which i think should not be possible

**Current behaviour**:

**Expected behaviour**: 

**Server Revision**:

**Comment by mhdemn** [comment]
it highlights, but you can't cast it

**Comment by Easyfraggy** [comment]
Seems the OP was false

**Comment by Matija5** [comment]
Well I can cast it and it does deal dmg, just summon ur pet go fight a mob, wait for him to die and then cast Kill command
