### ISSUE TITLE
[Quest] Deathblow to the Legion NPCs don't follow after first fail.

### ISSUE THREAD

**Issue by Mikik3jr** [Atlantiss/NetherwingBugtracker#2613]
[//]: # (Enclose links to things related to the bug using http://wowhead.com or any other TBC database.)
[//]: # (You can use screenshot ingame to visual the issue.)
[//]: # (Write your tickets according to the format:)
[//]: # ([Quest][Azuremyst Isle] Red Snapper - Very Tasty!)
[//]: # ([NPC] Magistrix Erona)
[//]: # ([Spell][Mage] Fireball)
[//]: # ([Npc][Drop] Ghostclaw Lynx)
[//]: # ([Web] Armory doesnt work)

**Description**: 
https://www.wowhead.com/quest=10409/deathblow-to-the-legion
3 NPCs spawn and they help us in battle. First we fight against Kaylaan, then Socretar.

**Current behaviour**:
First it worked well. All 3 NPCs followed us. We wiped on the first time, When we tried again the quest the elite guy followed us, while the other 2 were standing back.
![wowscrnshot_111118_163942](https://user-images.githubusercontent.com/43505031/48315183-4f886880-e5d3-11e8-9d27-6795330f40f2.jpg)
(in the background)
![wowscrnshot_111118_163946](https://user-images.githubusercontent.com/43505031/48315185-51522c00-e5d3-11e8-8659-b9935de60c37.jpg)

**Expected behaviour**: 
NPCs should follow us even after retrying after wipe.

**Server Revision**: 
2282

**Comment by Manaci** [comment]
Fixed
