### ISSUE TITLE
[Quest] Deathblow to the Legion fight against Kaylaan is hard af

### ISSUE THREAD

**Issue by Mikik3jr** [Atlantiss/NetherwingBugtracker#2614]
[//]: # (Enclose links to things related to the bug using http://wowhead.com or any other TBC database.)
[//]: # (You can use screenshot ingame to visual the issue.)
[//]: # (Write your tickets according to the format:)
[//]: # ([Quest][Azuremyst Isle] Red Snapper - Very Tasty!)
[//]: # ([NPC] Magistrix Erona)
[//]: # ([Spell][Mage] Fireball)
[//]: # ([Npc][Drop] Ghostclaw Lynx)
[//]: # ([Web] Armory doesnt work)

**Description**: 
https://www.wowhead.com/quest=10409/deathblow-to-the-legion
3 NPCs spawn and they help us in battle. First we fight against Kaylaan, then Socretar. First we fight against Kaylaan.
**Current behaviour**:

This is a fuking hard fight. We can't even kill the little guy. Hits too hard.
![wowscrnshot_111118_164904](https://user-images.githubusercontent.com/43505031/48315127-a2adeb80-e5d2-11e8-812b-85baaab7e747.jpg)
And does 1 minutes stun AOE, then kills everyone in 1 hit:
![wowscrnshot_111118_164826](https://user-images.githubusercontent.com/43505031/48315134-b35e6180-e5d2-11e8-91fe-e18ddb1370d0.jpg)

**Expected behaviour**: 
According to his comment this should be an ez tank and spank fight)
![image](https://user-images.githubusercontent.com/43505031/48315093-58c50580-e5d2-11e8-943b-c479afa98187.png)
**Server Revision**: 
2282

**Comment by Frankenberryberry** [comment]
the post above doesn't describe the situation with this quest entirely accurately.
The phase 1 NPC will AoE stun your entire party for 1 minute - then proceed to kill all players. The quest is undoable in it's current state.

**Comment by 0vertime** [comment]
We nuked him before he used the 1min stun, he just disappears. This quest is not completable.

**Comment by pelekon** [comment]
should be fixed in rev 2760
