### ISSUE TITLE
[Quest] Deathblow to the Legion I can heal NPCs

### ISSUE THREAD

**Issue by Mikik3jr** [Atlantiss/NetherwingBugtracker#2615]
[//]: # (Enclose links to things related to the bug using http://wowhead.com or any other TBC database.)
[//]: # (You can use screenshot ingame to visual the issue.)
[//]: # (Write your tickets according to the format:)
[//]: # ([Quest][Azuremyst Isle] Red Snapper - Very Tasty!)
[//]: # ([NPC] Magistrix Erona)
[//]: # ([Spell][Mage] Fireball)
[//]: # ([Npc][Drop] Ghostclaw Lynx)
[//]: # ([Web] Armory doesnt work)

**Description**: 
3 NPC summoned to help us in fight in this 5 man quest.
**Current behaviour**:
I can heal the NPCs
**Expected behaviour**: 
According this comment (last row) I should not be able to heal the NPCs:
![image](https://user-images.githubusercontent.com/43505031/48315272-56fc4180-e5d4-11e8-80f5-0928ed9c86ff.png)

**Server Revision**: 
2282

**Comment by pelekon** [comment]
should be fixed in rev 2760
