### ISSUE TITLE
[Quest] Sabotage the Warp-Gate

### ISSUE THREAD

**Issue by mhdemn** [Atlantiss/NetherwingBugtracker#2616]
**Description**: In this [quest](https://db.excalibur.ws/?quest=10310) you gotta escort Drijya while he does some stuff around the nearby camp. He does his thing in 3 different positions, dividing the waves in three clear phases.

- When doing the quest you find the obvious bug, also present in many other escort NPCs: He won't help you fight the mobs.
  - This should work like this [wowhead comment](https://www.wowhead.com/quest=10310/sabotage-the-warp-gate#comments) says:

![image](https://user-images.githubusercontent.com/25901582/48315278-654a5d80-e5d4-11e8-92a3-4b3dabeab2c3.png)

- Also, when doing the quest it seems fishy that the first wave, that consists in a big group of [imps](https://db.excalibur.ws/?npc=20399), is so much more difficult to deal with in comparison to the following two. I'm guessing these imps should have less health than the standard level 68 mob, probably less damage than currently too:

![image](https://user-images.githubusercontent.com/25901582/48315310-d8ec6a80-e5d4-11e8-88f8-c1329d4f6a65.png)
(Same wowhead page)

Sorry, I couldn't find any footage from retail TBC, every video I found is later xpacs and people rampaging through every wave all the same.

**Server Revision**: 2282

**Comment by Tenoutoften** [comment]
I don't know if you completed this quest given it's difficulty but I did it today and when the escort is done Drijya kills himself, strange. Got it complete though

**Comment by Tenoutoften** [comment]
Merged into https://github.com/Atlantiss/NetherwingBugtracker/issues/3678
