### ISSUE TITLE
[NPC] It feels like caster mobs do too little damage now

### ISSUE THREAD

**Issue by BezawitNW** [Atlantiss/NetherwingBugtracker#2618]
Since the change was made to caster mob scaling it feels as though they are doing too little damage. A good example of this is we were in Black Morass and one of the Rift Lords used Pyroblast on a Warlock. The Warlock only lost about 20% of their health from the Pyroblast.

**Comment by Wolffenstein** [comment]
The damage is in line with what was on retail, I promise. It's just not supposed to do a lot on normal...
