### ISSUE TITLE
[Object] Patch of Elemental Water

### ISSUE THREAD

**Issue by Kantrul** [Atlantiss/NetherwingBugtracker#2619]
**Description**: 
According to this website: http://web.archive.org/web/20061222040723/http://www.capsu.org:80/wow/pools_and_wreckage.html#elemental_water
There should be 6 pools of "Patch of Elemental Water" in Azshara (specific locations in website) where you can fish 3 specific items.
**Current behaviour**:
In the current server revision there are no "Patch of Elemental Water" in Azshara.
**Expected behaviour**: 
There should be 6 pools of "Patch of Elemental Water" in Azshara.
**Server Revision**: 
2295

**Comment by Evolvee** [comment]
fixed in next rev
