### ISSUE TITLE
[NPC] Boars in Elwynn Forest

### ISSUE THREAD

**Issue by Needorfeed** [Atlantiss/NetherwingBugtracker#262]
[//]: # ([NPC] Magistrix Erona)

**Description**: 
Level 5-7? Boars outside Goldshire will be 50% chance of bugging out, like they're out of range, even with having your weapon up inside the pig. Wont be able to melee it.

**Current behaviour**:
Melee range behaves as out of range or LoS

**Expected behaviour**: 
Pressing Attack, or any ability, should engage combat with the boar.

**Server Revision**:

**Comment by Easyfraggy** [comment]
Fixed
