### ISSUE TITLE
[Quest]  [Arelion's Journal]

### ISSUE THREAD

**Issue by Retinus** [Atlantiss/NetherwingBugtracker#2620]
[Arelion's Journal] the item for the q drop from blistering oozeling.

The journal should be inside a brown bag hanging in a tree at 40, 37.

[Source](https://www.wowhead.com/quest=9374/arelions-journal)

**Server Revision**: 2295

**Comment by Easyfraggy** [comment]
![image](https://user-images.githubusercontent.com/36134067/48318156-773ff680-e5fc-11e8-9949-d1d288c222f2.png)

Seems to be true.

**Comment by aresbrutus** [comment]
I checked this before, they have a very slight drop chance from the oozes.
