### ISSUE TITLE
[Spell][Mage]Blink - Air to ground + reset fall animation

### ISSUE THREAD

**Issue by killablink** [Atlantiss/NetherwingBugtracker#2621]
**Description**: There was a fix in the changelog that said it should reset fall animation but it still doesn't do it

**Current behaviour**: https://gfycat.com/CalmFaroffGraysquirrel
https://gfycat.com/SillyTotalHadrosaurus

**Expected behaviour**: I should either blink to the ground, or have my fall animation reset.

**Server Revision**: 2295

**Comment by Wolffenstein** [comment]
Fixed in rev 2303.
