### ISSUE TITLE
[Quest][Hellfire Peninsula] The Finest Down minor typo

### ISSUE THREAD

**Issue by scarabadookie** [Atlantiss/NetherwingBugtracker#2623]
[//]: # (Enclose links to things related to the bug using http://wowhead.com or any other TBC database.)
[//]: # (You can use screenshot ingame to visual the issue.)
[//]: # (Write your tickets according to the format:)
[//]: # ([Quest][Azuremyst Isle] Red Snapper - Very Tasty!)
[//]: # ([NPC] Magistrix Erona)
[//]: # ([Spell][Mage] Fireball)
[//]: # ([Npc][Drop] Ghostclaw Lynx)
[//]: # ([Web] Armory doesnt work)

**Description**: 
Mirren Longbeard doesn't want you to mess with his hat, even after giving it to you. The droprate for the feathers of the quest (quest=9420) seems low, but wowhead comments indicate that it should be that way.

**Current behaviour**:
When completed, Mirren Longbeard (NPC 16851) says: You **threat** my hat well now, name. You won't find a finer one anywhere in this world or another.

**Expected behaviour**: 
You treat my hat well now, name. You won't find a finer one anywhere in this world or another.

**Server Revision**: 
2304
![threat](https://user-images.githubusercontent.com/20177923/48318475-ba509880-e601-11e8-8e7f-2ea1bbbd1f1f.png)

**Comment by Evolvee** [comment]
rev vrr
