### ISSUE TITLE
[Spell][Mage]Blink  - air to ground (again)

### ISSUE THREAD

**Issue by killablink** [Atlantiss/NetherwingBugtracker#2626]
**Description**: Even in 2304's fix, it's still not working how it should be and just resets fall animation instead of blinking to the ground. Even if I blink right before hitting the ground, I blink back upwards

**Current behaviour**:
https://gfycat.com/SimplisticTheseArmednylonshrimp
https://gfycat.com/SparsePotableAidi
https://gfycat.com/NimbleKaleidoscopicIndianspinyloach

**Expected behaviour**: Should blink down to the ground. I don't know how blink it set up to work but it feels like it's taking too much time to update my character to where he currently is and blink from where he is? so instead I'm always blinking as if I was still up next to the platforms

**Server Revision**: 2304

**Comment by Tenoutoften** [comment]
I figured, although it doesn't make any difference. That I would provide a video of a player jumping down from some distance and blinking:

https://www.youtube.com/watch?v=eiC7fX07cGE&feature=youtu.be&t=499

Was desperately looking for evidence for something else...

**Comment by Tenoutoften** [comment]
https://youtu.be/0Tr4vjhawQc?t=429
https://youtu.be/0Tr4vjhawQc?t=185

**Comment by aresbrutus** [comment]
Closing and requesting retest after the update of rev 2430 and 2431.
