### ISSUE TITLE
Mobaz NPC in Hellfire Peninsula

### ISSUE THREAD

**Issue by Daggotur** [Atlantiss/NetherwingBugtracker#2628]
https://www.wowhead.com/npc=18979/mobaz
**Description**: MOBAZ - named worm in hellfire peninsula

**Current behaviour**: He casts inhale and currently it does nothing

**Expected behaviour**:  It should pull to him and slow down. http://db.hellfire-tbc.com/?npc=18979 also he has not loot but I couldnt find his loot table anywhere

**Server Revision**:

**Comment by xmesaj2** [comment]
fixed in 2316

**Comment by leeviathan** [comment]
I just fought this mob, dropped a gray item. Not sure if the spell was "Inhale", but the mob casted a spell with a blue beam effect that seemed to do nothing

**Comment by Godmatik** [comment]
Confirmed, no loot table, and didn't use the inhale ability on me
