### ISSUE TITLE
[Quest][Shadowmoon Vally][Enraged Spirits of Fire and Earth][Enraged Spirits of Water][Enraged Spirits of Air][Quest Item] Totem of Spirits

### ISSUE THREAD

**Issue by Matija5** [Atlantiss/NetherwingBugtracker#2629]
[//]: # (Enclose links to things related to the bug using http://wowhead.com or any other TBC database.)
[//]: # (You can use screenshot ingame to visual the issue.)
[//]: # (Write your tickets according to the format:)
[//]: # ([Quest][Azuremyst Isle] Red Snapper - Very Tasty!)
[//]: # ([NPC] Magistrix Erona)
[//]: # ([Spell][Mage] Fireball)
[//]: # ([Npc][Drop] Ghostclaw Lynx)
[//]: # ([Web] Armory doesnt work)

**Description**:  With these quests u get Totem of Spirits which u have to put on ground and kill enraged earth, fire, water and air spirits near it. But when u move on the other location and you click Totem of Spirits to put on ground he doesn't appear but he refreshes the previous totem u put.

**Current behaviour**:

**Expected behaviour**: 

**Server Revision**:

**Comment by Easyfraggy** [comment]
Thanks for a more descriptive issue than - it finally makes sense!

https://github.com/Atlantiss/NetherwingBugtracker/issues/2474

**Comment by Dollywog** [comment]
Can confirm this is still the case, when trying to place a new Spirit of Totems (30 second CD) you have to wait full 2minutes for the previous one to despawn before this will work it seems

**Comment by rychersky** [comment]
This behavior observed and commented on above is still happening (quest item is a 30s cooldown but you must wait 2m for the previous totem to despawn).

**Comment by kwah8787** [comment]
still happening. you have to wait until the totem expires (2 min or so) before you can place the new one even though it is only 30 second cooldown. I think the totem is supposed to behave like normal shaman totems and be able to replace.
revision 2756

**Comment by The14me** [comment]
Rev.3460 still an issue.

**Comment by Drayo** [comment]
This is one annoying issue for sure. It makes these quests a huge pain in the ass.

**Comment by Wolffenstein** [comment]
Fixed in rev 3477.
