### ISSUE TITLE
[Spell] Beast training wrong requirements

### ISSUE THREAD

**Issue by Gniddikon** [Atlantiss/NetherwingBugtracker#263]
**Description**: When I try to teach my pet "Natural Armor (Rank 1)" or "Great Stamina (Rank 1)" it says "Target is too low level" even though my pet has reached level 8. The skills only require pet level 1.

**Current behaviour**: Cannot train my pet with the skills according to its level.

**Expected behaviour**:  Should be able to.

**Server Revision**: 2032

**Comment by The14me** [comment]
https://github.com/Atlantiss/NetherwingBugtracker/issues/505
