### ISSUE TITLE
[NPC] [Ironforge] Ormyr Flinteye <Rogue Trainer> - missing

### ISSUE THREAD

**Issue by ScottieDOESknow** [Atlantiss/NetherwingBugtracker#2630]
**Description**: 

Ormyr Flinteye - Rogue trainer located in The Forlorn Cavern

**Current behaviour**:

NPC is missing
https://gyazo.com/a7a6404295d28e173f26d44c19976f0d

**Expected behaviour**: 

NPC should be in the corner by bookcase
https://gyazo.com/a22c822c536e56d59135ed0e178a2d2c

https://www.wowhead.com/npc=5166/ormyr-flinteye#screenshots:id=450762

**Server Revision**: 2304

**Comment by Evolvee** [comment]
rev vrr
