### ISSUE TITLE
Shadow Lab enterance incorrect RP?

### ISSUE THREAD

**Issue by Mikik3jr** [Atlantiss/NetherwingBugtracker#2631]
[//]: # (Enclose links to things related to the bug using http://wowhead.com or any other TBC database.)
[//]: # (You can use screenshot ingame to visual the issue.)
[//]: # (Write your tickets according to the format:)
[//]: # ([Quest][Azuremyst Isle] Red Snapper - Very Tasty!)
[//]: # ([NPC] Magistrix Erona)
[//]: # ([Spell][Mage] Fireball)
[//]: # ([Npc][Drop] Ghostclaw Lynx)
[//]: # ([Web] Armory doesnt work)

**Description**: 
Front of Shadow Lab we can see a little RP that ninja orcs come out of the dungeon to fight with other NPCs

**Current behaviour**:
They come out of the enterance.

**Expected behaviour**: 
I am not sure about this, but according to this 10yr old video maybe they should be inside of the enterance. I report this jusr in case.
https://vimeo.com/1683810

**Server Revision**: 
2304

**Comment by Tenoutoften** [comment]
https://youtu.be/z0RcjwDWV7c?t=3

**Comment by Easyfraggy** [comment]
Are those RP texts missing Tentou? Otherwise I'm closing this.

**Comment by Tenoutoften** [comment]
I don't know, I haven't bothered moving my character over there

**Comment by Evolvee** [comment]
i scripted that RP

from our research it was supposed to look like it is now on the server, similar evidence is provided above to support that claim

what probably happened in the 1st vid is that these mobs respawned while the combat finished so the defenders re-engaged those orc(they indeed spawn inside)
