### ISSUE TITLE
[Zone] [Terokkar Forest] Auchindown spirit towers - not resetting

### ISSUE THREAD

**Issue by ScottieDOESknow** [Atlantiss/NetherwingBugtracker#2634]
**Description**: 

Capturing all 5 spirit towers enables a zonewide buff 'Blessing of Auchindown' that lasts for 6 hours.

**Current behaviour**:

After 6 hours the tower control is NOT resetting to neutral; they remain controlled by the last faction to hold them and the zonewide buff persists. Towers are still able to swap faction as usual with pvp control.

https://gyazo.com/5b2884d975249134ae2c8235f4d9dc2a

**Expected behaviour**: 

After 6 hours, the zonewide buff should be removed and the 5 towers should be reset to neutral.

**Server Revision**:  2304

**Comment by zauru7** [comment]
had similar bug yesterday, it appeared to work after reset. Don't know if relevant but it was also related to the 6 hour lockout period(perhaps that's what's broken)

https://github.com/Atlantiss/NetherwingBugtracker/issues/2612

**Comment by ScottieDOESknow** [comment]
A server crash / restart will reset world pvp objectives to neutral in HFP, Zangarmarsh, Auchindown.

The spirit towers WERE working correctly just recently. I was online for two resets this past weekend and in both instances capped all five towers right as they went neutral for the 6 hour buff.

**Comment by Manaci** [comment]
Fixed
