### ISSUE TITLE
[NPC] Not moving after being interrupted or after casting an ability

### ISSUE THREAD

**Issue by BezawitNW** [Atlantiss/NetherwingBugtracker#2635]
Not sure if these two clips are related. For the first clip, after I interrupt the Mire Hydra at max range it does not move closer to me. However if I am within 20-25 yards and interrupt, it seems to path toward me correctly:

https://clips.twitch.tv/BashfulBeautifulToothPlanking

Next clip is an Umbraglow Stinger. After it uses Glowing Blood ability on me it remains stationary:

https://clips.twitch.tv/RoughQuaintFriesOMGScoots

**Comment by BezawitNW** [comment]
This seems odd to explain but I think the clips are related. If YOU (player) remain stationary and do not move, the mob also does not move. But if you move your character at all, the mob will resume moving toward you.

**Comment by Easyfraggy** [comment]
https://github.com/Atlantiss/NetherwingBugtracker/issues/2175
