### ISSUE TITLE
[NPC][Hellfire Peninsula] Urga'zz

### ISSUE THREAD

**Issue by Daggotur** [Atlantiss/NetherwingBugtracker#2636]
Quest mob Urga'zz Ability Proximity bomb https://www.wowhead.com/spell=34095/throw-proximity-bomb 
![wowscrnshot_111218_124134](https://user-images.githubusercontent.com/44930160/48368376-2cb08f80-e679-11e8-8e59-403b38a86865.jpg)

**Current behaviour**: Currently he uses the ability several times in a row (see screenshot)

**Expected behaviour**: SHould be 7 sec CD as per wowhead

**Server Revision**:

**Comment by 0vertime** [comment]
https://i.imgur.com/USWv9c9.png

**Comment by The14me** [comment]
Rev.3460 looks fine now.
Can be closed.
