### ISSUE TITLE
[Npc][Spell] Tormented Soul/Kirin'Var Ghost - Soulbind

### ISSUE THREAD

**Issue by Kaini27** [Atlantiss/NetherwingBugtracker#2637]
[//]: # (Enclose links to things related to the bug using http://wowhead.com or any other TBC database.)
[//]: # (You can use screenshot ingame to visual the issue.)
[//]: # (Write your tickets according to the format:)
[//]: # ([Quest][Azuremyst Isle] Red Snapper - Very Tasty!)
[//]: # ([NPC] Magistrix Erona)
[//]: # ([Spell][Mage] Fireball)
[//]: # ([Npc][Drop] Ghostclaw Lynx)
[//]: # ([Web] Armory doesnt work)

**Description**: Tormented Soul wich transforms into Kirin'Var Ghost has spell named Soulbind and its not working correctly

**Current behaviour**: Kirin'Var Ghost applies buff on himself and debuff on the player wich leads to 50% damage done being redirected on a player, but upon dispelling debuff there is still damage being redirected.

**Expected behaviour**: After offensive dispel on Kirin'Var Ghost or defensive on player- damage should stop being reflected. 

**Server Revision**: 2304

**Comment by Tenoutoften** [comment]
It can also cast soulbind while stunned... Probably shouldn't do that.

**Comment by Kaini27** [comment]
True, it can also do it while silenced.

**Comment by Tenoutoften** [comment]
I revisited this place after the 2321 server rev and now they no longer apply the debuff to the player, only to themselves

**Comment by Godmatik** [comment]
Fixed already in rev 3556
