### ISSUE TITLE
Warp Hunter Visual Bug While Phasing

### ISSUE THREAD

**Issue by tepex0** [Atlantiss/NetherwingBugtracker#2638]
Seems to occus when the warp hunters phase and then come into field of view. Doesn't occur when they phase near you

bugged - https://i.imgur.com/ie4FJm4.jpg & https://i.imgur.com/HnsV3QJ.jpg

normal - https://i.imgur.com/A0tD0YF.jpg

server revision 2304

**Comment by Tereneckla** [comment]
Fixed
