### ISSUE TITLE
[Spell][Paladin] Crusader Strike does not refresh all seals.

### ISSUE THREAD

**Issue by Mikik3jr** [Atlantiss/NetherwingBugtracker#2639]
[//]: # (Enclose links to things related to the bug using http://wowhead.com or any other TBC database.)
[//]: # (You can use screenshot ingame to visual the issue.)
[//]: # (Write your tickets according to the format:)
[//]: # ([Quest][Azuremyst Isle] Red Snapper - Very Tasty!)
[//]: # ([NPC] Magistrix Erona)
[//]: # ([Spell][Mage] Fireball)
[//]: # ([Npc][Drop] Ghostclaw Lynx)
[//]: # ([Web] Armory doesnt work)

**Description**: 
![image](https://user-images.githubusercontent.com/43505031/48374133-298ec100-e6c4-11e8-9f0c-54ae7435acfb.png)

**Current behaviour**:
If ONLY my seal (wisdom) is up Crusader Strike (from other paladin) refreshes the my seal on the target, but it can't be seen. The seal cunts down until 0, then stays on 0, cuz the timer visually is not refreshed.

If the other paladin uses their own seal (Crusader this time), then Crusader Strike they don't refresh my seal, only theirs.

**Expected behaviour**: 
Crusader Strike should refresh ALL seals on target.

**Server Revision**: 
2304

**Comment by Kaini27** [comment]
On some circumstances Crusader Strike claims ownership on other paladins seals, losing main seal. Have been spoted on Seal of Light. Most likely related to this bug. Will test it out again when main report will be fixed.

**Comment by Novat93** [comment]
I have experienced Crusader strike improperly applying seals, the paladin did not himself apply. I only experienced this while in a party with a second paladin, where i applied judgement of the crusader and a second paladin applied judgement of wisdom. On occasion, crusader strike replaced my judgement of the crusader with judgement of light.

**Comment by Wolffenstein** [comment]
Fixed in rev 2365.
