### ISSUE TITLE
Pulled mobs stop outside melee range if you walk towards them 

### ISSUE THREAD

**Issue by paoea** [Atlantiss/NetherwingBugtracker#264]
[//]: # (Enclose links to things related to the bug using http://wowhead.com or any other TBC database.)
[//]: # (You can use screenshot ingame to visual the issue.)
[//]: # (Write your tickets according to the format:)
[//]: # ([Quest][Azuremyst Isle] Red Snapper - Very Tasty!)
[//]: # ([NPC] Magistrix Erona)
[//]: # ([Spell][Mage] Fireball)
[//]: # ([Npc][Drop] Ghostclaw Lynx)
[//]: # ([Web] Armory doesnt work)

**Description**: 
Pulled mobs stop outside melee range if you walk towards them 
**Current behaviour**:
If you pull a mob with some ranged ability, they come towards you. If you also walk towards them, they stop little quick outside melee range. 
**Expected behaviour**: 
Mobs should come direct in to melee range, no matter in which direction you move.
**Server Revision**:

**Comment by Evolvee** [comment]
the mob predicts that you are going to reach the mob just in time and at the same time prevents from entering your hitbox and then walking away for it unnecesarily, so he just waits..

**Comment by Easyfraggy** [comment]
fixed from what I can tell
