### ISSUE TITLE
[Quest][Shadowmoon vally] Teron Gorefiend - Lore and Legend

### ISSUE THREAD

**Issue by Matija5** [Atlantiss/NetherwingBugtracker#2640]
[//]: # (Enclose links to things related to the bug using http://wowhead.com or any other TBC database.)
[//]: # (You can use screenshot ingame to visual the issue.)
[//]: # (Write your tickets according to the format:)
[//]: # ([Quest][Azuremyst Isle] Red Snapper - Very Tasty!)
[//]: # ([NPC] Magistrix Erona)
[//]: # ([Spell][Mage] Fireball)
[//]: # ([Npc][Drop] Ghostclaw Lynx)
[//]: # ([Web] Armory doesnt work)

**Description**: There is not Ancient Shadowmoon Spirit near altar so u can't turn in quest, even tho i have Spectrecles on. And also there is teron gorefiend at altar don't know if he is supposed to be there
https://www.wowhead.com/npc=21797/ancient-shadowmoon-spirit
https://imgur.com/a/PvxRuig

**Current behaviour**:

**Expected behaviour**: 

**Server Revision**:

**Comment by Evolvee** [comment]
rev 2684

**Comment by Evolvee** [comment]
its not updated yet

**Comment by kwah8787** [comment]
appears to still be bugged revision 2756
 
Teron Gorefiend still at the altar.... spectacles on and no spirit to turn quest in to after 15 minutes of waiting

just giving an update

**Comment by kwah8787** [comment]
update... a few hours later i got the quest to work normally i dont know what changed
