### ISSUE TITLE
Blood Furnace Tehnicians : Bombs

### ISSUE THREAD

**Issue by Kimro143** [Atlantiss/NetherwingBugtracker#2641]
**Description**:   The tehnicians lay bombs dealing around 1.8k damage when in proximity.

**Current behaviour**: Bombs cannot be disarmed by rogues.

**Expected behaviour**: they should be disarmed with 300 skill.

Source: http://www.blizzardguides.com/burning-crusade/blood_furnace_guide.html

**Comment by Kimro143** [comment]
Extract a passage from http://www.tentonhammer.com/guides/the-blood-furnace-guide
by Byron Mudry on Jan 25, 2007

Shadowmoon Technician –They through bombs that explode for an AOE damage and silence, and place land mines on the ground that explode for 2k damage to everyone around them. The mines can be deactivated by a rogue or you can just move carefully around them.

**Comment by Dirge123** [comment]
The mines are classified as physical damage and cannot be Cloak of Shadows'ed to get rid of them (you take full damage) but you can use Fire Ward & Fire Protection Potions to absorb their damage.

**Comment by NatsumeLily** [comment]
Bump. Gives rogues some great control on mines and lets groups move on instead of waiting for the mines to despawn.

**Comment by danbopes** [comment]
Should be fixed already. Comment below if still bugged.
