### ISSUE TITLE
[NPC][Shadow Labyrinth] Cabal Ritualist

### ISSUE THREAD

**Issue by Easyfraggy** [Atlantiss/NetherwingBugtracker#2642]
**Description**: 

These should seemingly use different weapon/ability combinations than currently:

![image](https://user-images.githubusercontent.com/36134067/48380954-1b4b9f80-e6da-11e8-83d0-442e5167db10.png)

http://wowwiki.wikia.com/wiki/Shadow_Labyrinth

https://gfycat.com/InfantileHonorableKingfisher gif of current:

Red staff for both frost and arcane and the dagger one uses gouge and flame buffet which is wrong according to above info.

**Server Revision**: 2304

**Comment by Drayo** [comment]
Wowpedia also mentions that "Dispel" is only used on Heroic. 

https://wow.gamepedia.com/index.php?title=Cabal_Ritualist&oldid=2796008

Wowwiki is correct about the rest of the spells.

**Comment by Drayo** [comment]
This becomes relevant again for the fresh release.

WowWhead quote: https://www.wowhead.com/npc=18794/cabal-ritualist#comments


> By 5057 (6,434 –  3·10·40)  on 2007/06/28 (Patch 2.1.2) |   |  
> Caster ones can be identified by having a staff. Melee ones will have either 2 daggers or 2 sword.

So in a compact format including Easys wowwiki post:

- Normal white Staff: Frostbolt+Frostnova

- Red glowing Staff: Arcane Missiles+Addle Humanoid +Dispell (HC only, around 10s cd)

- Daggers: High Damage+Gouge

- Sword: Spamming Flame Buffet and casting Fireblast (around 5s cd)

The mobs in the room already seem to have different sets of abilities, the only thing wrong about them is that **they all them seem to gouge**, even casters. Furthermore, the **casters melee way too much**, they should just chain-cast like Aran for example. 

**And of course, the different type of mobs need their correct weapons.**

**Comment by Wolffenstein** [comment]
Fixed in rev 3394.

**Comment by Drayo** [comment]
I just retested this, it works for the most part. (Visuals all working now)

Some, mostly small, issues though:

- The Arcane version with the Red Staff **interrupts** his own "**Addle Humanoid**" channeling with an Arcane Missiles cast every time, and **Arcane Missiles has infinite range and ignores LOS**.

- The version with the Sword (Fire) does not properly spam "Flame Buffet".

- The Dagger versions off-hand swing always hits for exactly 250 damage (92 on normal version), should be around half of the main-hand damage.
