### ISSUE TITLE
[NPC][Nagrand] Southwind Cleft ogre cave 3 stacked ogres

### ISSUE THREAD

**Issue by scarabadookie** [Atlantiss/NetherwingBugtracker#2643]
[//]: # (Enclose links to things related to the bug using http://wowhead.com or any other TBC database.)
[//]: # (You can use screenshot ingame to visual the issue.)
[//]: # (Write your tickets according to the format:)
[//]: # ([Quest][Azuremyst Isle] Red Snapper - Very Tasty!)
[//]: # ([NPC] Magistrix Erona)
[//]: # ([Spell][Mage] Fireball)
[//]: # ([Npc][Drop] Ghostclaw Lynx)
[//]: # ([Web] Armory doesnt work)

**Description**: 
Ogres like being close to eachother sometimes.

**Current behaviour**:
3 ogres are stacked in the center of the cave making it hardmode to clear, especially if all 3 spawn as Boulderfist Mages. The warrior in picture below was walking back and forth 1 yard, on the wall and scenery as well.

**Expected behaviour**: 
Good ogres stay solo or in pairs :feelsgood: 

**Server Revision**: 
2304
![southwind cleft ogres](https://user-images.githubusercontent.com/20177923/48382974-0b38bd80-e6e4-11e8-88cb-f8fab547a972.png)

**Comment by aresbrutus** [comment]
Fixed in rev `Nariman`
