### ISSUE TITLE
[Spell][Druid][Balance] Force of Nature treants are level 70 always

### ISSUE THREAD

**Issue by Kuumi** [Atlantiss/NetherwingBugtracker#2644]
[//]: # (Enclose links to things related to the bug using http://wowhead.com or any other TBC database.)
[//]: # (You can use screenshot ingame to visual the issue.)
[//]: # (Write your tickets according to the format:)
[//]: # ([Quest][Azuremyst Isle] Red Snapper - Very Tasty!)
[//]: # ([NPC] Magistrix Erona)
[//]: # ([Spell][Mage] Fireball)
[//]: # ([Npc][Drop] Ghostclaw Lynx)
[//]: # ([Web] Armory doesnt work)

**Description**: 
Treants are level 70 despite player level not level 70.
**Current behaviour**:
summoned treants by boomie are not player level
**Expected behaviour**: 
Should be player level
**Server Revision**:

**Comment by Easyfraggy** [comment]
https://github.com/Atlantiss/NetherwingBugtracker/issues/2063

**Comment by shakedown12** [comment]
I agree i just experienced that issue today in Un'goro lvl 50 boomkin used trees lvl 70 on me
