### ISSUE TITLE
[Spell] [Druid] Rake

### ISSUE THREAD

**Issue by Brynbb** [Atlantiss/NetherwingBugtracker#2646]
[//]: # (Enclose links to things related to the bug using http://wowhead.com or any other TBC database.)
[//]: # (You can use screenshot ingame to visual the issue.)
[//]: # (Write your tickets according to the format:)
[//]: # ([Quest][Azuremyst Isle] Red Snapper - Very Tasty!)
[//]: # ([NPC] Magistrix Erona)
[//]: # ([Spell][Mage] Fireball)
[//]: # ([Npc][Drop] Ghostclaw Lynx)
[//]: # ([Web] Armory doesnt work)

**Description**:  Rake cannot be reapplied while it is on the target.  Does not appear to be talent related (tested with talents and without talents).

**Current behaviour**: Receiving error message "A more powerful spell is already active" when attempting to reapply Rake before it expires.
![wowscrnshot_111218_194711](https://user-images.githubusercontent.com/18388258/48385354-d3b21d00-e6b3-11e8-9d76-554fc024fa59.jpg)

**Expected behaviour**: Reapplies rake at full duration.

**Server Revision**:

**Comment by ahlens** [comment]
It's a global issue. The same problem appears with others spells as well.

**Comment by Easyfraggy** [comment]
Please name those spells.

**Comment by gurtash** [comment]
Same thing happens when you try to reapply rip

https://www.youtube.com/watch?v=mz23BPV2sGQ

cant even apply a 5point rip over a 4point
server rev: 2370
