### ISSUE TITLE
[NPC][Hellfire Peninsula][Infernal Warbringer] Immolation

### ISSUE THREAD

**Issue by Liquidsoap** [Atlantiss/NetherwingBugtracker#2647]
[//]: # (Enclose links to things related to the bug using http://wowhead.com or any other TBC database.)
[//]: # (You can use screenshot ingame to visual the issue.)
[//]: # (Write your tickets according to the format:)
[//]: # ([Quest][Azuremyst Isle] Red Snapper - Very Tasty!)
[//]: # ([NPC] Magistrix Erona)
[//]: # ([Spell][Mage] Fireball)
[//]: # ([Npc][Drop] Ghostclaw Lynx)
[//]: # ([Web] Armory doesnt work)

**Description**: Infernal Warbringer's Immolation spell in Hellfire Peninsula
https://www.wowhead.com/npc=19261/infernal-warbringer#abilities

**Current behaviour**: Immolation aura was ticking approximately every 0.25seconds. However, I've only seen this behaviour on one of the Infernal Warbringer's at this time. I have interacted with approximately 8-12 Infernal Warbringers.
![hellfire infernal immolation bug](https://user-images.githubusercontent.com/28773914/48386345-7794cc00-e6a6-11e8-88e5-e02d8d3822d8.jpg)

**Expected behaviour**: Immolation should tick once every 3 seconds.

**Server Revision**:

**Comment by Easyfraggy** [comment]
https://github.com/Atlantiss/NetherwingBugtracker/issues/2334
