### ISSUE TITLE
[Spell] Flare + Warp Stalker mob

### ISSUE THREAD

**Issue by mbzz88** [Atlantiss/NetherwingBugtracker#2648]
**Description**:  Hunter Flare does not remove Warp Stalker invisibility

**Current behaviour**: Warp Stalker npc=18464 does not have invisibility spell=32942 removed by flare 
https://youtu.be/kQ7jaK677KI
Not sure if it is invisibility in general that's affected, or this mob specifically

**Expected behaviour**: Flare removes invisibility

**Server Revision**: 2304

**Comment by mbzz88** [comment]
The phase shift/"Phasing Invisibility" is an invisibility spell, not stealth, but flare should remove it
http://wowwiki.wikia.com/wiki/Flare
"Exposes all hidden and invisible enemies within 10 yards of the targeted area for 20 sec."

**Comment by Novat93** [comment]
https://www.wowhead.com/npc=23219/blackwind-warp-chaser#comments

![warp stalker](https://user-images.githubusercontent.com/36829235/48393067-5b2c7a00-e70e-11e8-9aa0-f883111a3cee.PNG)

**Comment by xmesaj2** [comment]
warlock can see invisibility and not stealth, these are 2 different mechanics 
http://db.hellfire-tbc.com/?spell=1543 it has dispel type 5 which is stealth, and dispel type 6 which is invisibility 
https://www.wowhead.com/spell=32943 is invisibility
seems flare should work on it but will check old dbc data later if invis part has been added with another patch and isnt documented, need to compare different dbc but so far https://wow.gamepedia.com/index.php?title=Flare&oldid=734393 which is around patch 2.1 it says only about stealth

**Comment by towneh** [comment]
https://www.wowhead.com/spell=32942/phasing-invisibility#comments:id=285358

**Comment by Manaci** [comment]
Not a bug
