### ISSUE TITLE
Bloodrage warrior can charge.

### ISSUE THREAD

**Issue by jay070** [Atlantiss/NetherwingBugtracker#265]
[//]: # (Enclose links to things related to the bug using http://wowhead.com or any other TBC database.)
[//]: # (You can use screenshot ingame to visual the issue.)
[//]: # (Write your tickets according to the format:)
[//]: # ([Quest][Azuremyst Isle] Red Snapper - Very Tasty!)
[//]: # ([NPC] Magistrix Erona)
[//]: # ([Spell][Mage] Fireball)
[//]: # ([Npc][Drop] Ghostclaw Lynx)
[//]: # ([Web] Armory doesnt work)

**Description**: 
can still charge when i use bloodrage (should not be possible reason: in combat)
**Current behaviour**:

**Expected behaviour**: 

**Server Revision**:

**Comment by Godmatik** [comment]
It put you in combat during Vanilla, but not the case in BC:

The Burning Crusade Patch 2.3.0 (2007-11-13):
Bloodrage should no longer initiate combat, though it will prevent rage decay for the duration.
