### ISSUE TITLE
NPC- Marticar

### ISSUE THREAD

**Issue by Novat93** [Atlantiss/NetherwingBugtracker#2650]
[//]: # (Enclose links to things related to the bug using http://wowhead.com or any other TBC database.)
[//]: # (You can use screenshot ingame to visual the issue.)
[//]: # (Write your tickets according to the format:)
[//]: # ([Quest][Azuremyst Isle] Red Snapper - Very Tasty!)
[//]: # ([NPC] Magistrix Erona)
[//]: # ([Spell][Mage] Fireball)
[//]: # ([Npc][Drop] Ghostclaw Lynx)
[//]: # ([Web] Armory doesnt work)

**Description**: The rare spawn Marticar in the Zangarmash zone has an incorrect patrol path
npc=18680

**Current behaviour**: 
Marticar, in one of it's 3 spawn locations, along the northern part of the zone. Will inevitably patrol into the Orebor Harborage guards, and subsequently die.

**Expected behaviour**: 
The path should turn south along the serpent lake, avoiding the elite NPCs, before continuing west.

**Server Revision**: 
2304

![marticar](https://user-images.githubusercontent.com/36829235/48390995-e4d74a00-e704-11e8-9d81-4ec4e9293b46.PNG)

**Comment by aresbrutus** [comment]
Fixed in rev `Castilla`
