### ISSUE TITLE
[NPC] [Netherstorm] Dealer Senzik - missing gem

### ISSUE THREAD

**Issue by ScottieDOESknow** [Atlantiss/NetherwingBugtracker#2651]
**Description**: 

Dealer Senzik <Gems & Jewelcrafting Supplies> sells limited supply uncommon quality gems

**Current behaviour**:

Missing uncommon purple gem 'Shifting Shadow Draenite' (+3 Agility and +4 Stamina)
All other gems are available in limited supply (1)

**Expected behaviour**: 

NPC should sell this item in limited quantity (1)

thottbot
https://web.archive.org/web/20080915151050/http://thottbot.com:80/i23110

**Server Revision**: 2304

**Comment by aresbrutus** [comment]
Should be fixed in rev `Castilla `Please recheck after it goes live.
