### ISSUE TITLE
[Class] Warlock imp sometimes takes aoe damage while phase shifted

### ISSUE THREAD

**Issue by BezawitNW** [Atlantiss/NetherwingBugtracker#2652]
https://clips.twitch.tv/SecretiveSnappyChowderBleedPurple

I've noticed this a few different times but this is the first clip I've remembered to take of it. Imp is set to passive + stay + phase shifted near Murmur to ensure tank is in range of Blood Pact. A party member receives the debuff and when they blow up, it kills my imp near them despite it being phase shifted.

**Comment by Easyfraggy** [comment]
It appears to die same moment as someone explodes with Murmur's Touch - Might be related to aoe spells? Just like aoe spells also damage neutral players (PvE setting).

**Comment by Wilmya** [comment]
This happens at Mother Shahraz as well. Probably because the damage is coming from a friendly.

**Comment by Tereneckla** [comment]
https://www.youtube.com/watch?v=6dvLGBxe-ro

Imp position
https://youtu.be/6dvLGBxe-ro?t=20

Fatal Attractioned on Imp
https://youtu.be/6dvLGBxe-ro?t=28
Imp stays afterwards, kinda hard to see the Imp, but blood pact stays on and here you see the imp rebuffing fire shield.
https://youtu.be/6dvLGBxe-ro?t=45

**Comment by BamboozleNW** [comment]
No chance, cleared all of T4/T5/T6 content on this server with affliction, never had an imp die on any fight. This has to have been fixed. Can be closed I would imagine.
