### ISSUE TITLE
[Quest][Shadowmoon Vally] Of Thistleheads and Eggs...

### ISSUE THREAD

**Issue by Matija5** [Atlantiss/NetherwingBugtracker#2654]
[//]: # (Enclose links to things related to the bug using http://wowhead.com or any other TBC database.)
[//]: # (You can use screenshot ingame to visual the issue.)
[//]: # (Write your tickets according to the format:)
[//]: # ([Quest][Azuremyst Isle] Red Snapper - Very Tasty!)
[//]: # ([NPC] Magistrix Erona)
[//]: # ([Spell][Mage] Fireball)
[//]: # ([Npc][Drop] Ghostclaw Lynx)
[//]: # ([Web] Armory doesnt work)

**Description**: I looted all of the eggs from camp couple of times and none of them gave me quest item rotten arakkoa egg, idk if it's bugged but i'm pretty sure at least one in camp should give item

**Current behaviour**:

**Expected behaviour**: 

**Server Revision**:

**Comment by Easyfraggy** [comment]
It's extremely low drop rate. Always was a retarded quest.

**Comment by Matija5** [comment]
So basicly there is a change that noone of the eggs in camp give item until right now spawn ?

**Comment by Matija5** [comment]
Finnaly got it, so it's prob not bugged I just wasn't sure when u click on egg and it doesn't give item can it respawn into one that does

**Comment by Evolvee** [comment]
@Shanghi made those gameobjects I believe

**Comment by Shanghi** [comment]
As Easy said, this is just a rude quest and you might get unlucky. When one respawns it can be a good or bad egg. On stock they were all bad eggs except one specific good one.
