### ISSUE TITLE
Noggenfogger should actually work while small in TBC with internet proof.

### ISSUE THREAD

**Issue by craigsurbrook** [Atlantiss/NetherwingBugtracker#2655]
[//]: # (Enclose links to things related to the bug using http://wowhead.com or any other TBC database.)
[//]: # (You can use screenshot ingame to visual the issue.)
[//]: # (Write your tickets according to the format:)
[//]: # ([Quest][Azuremyst Isle] Red Snapper - Very Tasty!)
[//]: # ([NPC] Magistrix Erona)
[//]: # ([Spell][Mage] Fireball)
[//]: # ([Npc][Drop] Ghostclaw Lynx)
[//]: # ([Web] Armory doesnt work)

**Description**: 
The "small" mount using Noggenfogger was removed due to someone showing a post from 3.3.0 (WotLK) where they say they "added" the ability to mount using Noggenfogger.
This is true, however, mounting while small (but not skeleton) was in the game in Vanilla and TBC, and got BROKEN for WotLK. So they "added" the ability back in 3.3.0 to fix this.
In fact, mounting while small should work in TBC and did work in TBC. Scouring the internet for old references (what is still left) states this.
--------------------------------------------------------------------------------------------------
- Wrath-Logo-Small Patch 3.3.0 (08-Dec-2009): Players shrunk while under the effects of this item will now be able to mount.
This was the "fix" for what Wrath broke.
http://wowwiki.wikia.com/wiki/Noggenfogger_Elixir

Here is a post from TBC era about this:

30 | By Travis (505 – 1·4) on 2007/11/08 (Patch 2.2.3)You can still ride a gryphon taxi when "You feel smaller...", best part is that the gryphon also shrinks. Appeared that the smaller gryphon flew lower than typical.18psychosam666 on 2007/11/19 (Patch 2.3.0)This also works for flying mounts. It's adorable to be on a minature Netherdrake! Posting screenshot. | By Travis (505 – 1·4) on 2007/11/08 (Patch 2.2.3) |   |   | 18 | psychosam666 on 2007/11/19 (Patch 2.3.0)This also works for flying mounts. It's adorable to be on a minature Netherdrake! Posting screenshot.
-- | -- | -- | -- | -- | -- | --
By Travis (505 – 1·4) on 2007/11/08 (Patch 2.2.3) |   |  
18 | psychosam666 on 2007/11/19 (Patch 2.3.0)This also works for flying mounts. It's adorable to be on a minature Netherdrake! Posting screenshot.

The link to these posts is here:
https://www.wowhead.com/item=8529/noggenfogger-elixir#comments

Proof that Noggenfogger while small ALWAYS worked in TBC. See the dates and revisions. Which shows that WotLK ADDED this ability back when it was broken in WotLK.
The previous bugtracker poster showed proof that WotLK added it back, but it was misleading because it made it appear as if it was the first time that Noggenfogger was working this way. As these posts show, Noggenfogger always worked while small in TBC.
--------------------------------------------------------------------------------------------------
**Current behaviour**:
You can't mount while small and using Noggenfogger.

**Expected behaviour**: 
You should be able to mount with Noggenfogger while small, but not with skeleton.

**Server Revision**: 
2304

**Comment by craigsurbrook** [comment]
Sorry about the fonts in the post, not "yelling" it was an artifact of cut and pasting stuff from the internet, which came through weird.

**Comment by ircfelix** [comment]
Please try to find more sources. Giving the devs extra work based on one comment for a cosmetic thing is redundant.

**Comment by Mikik3jr** [comment]
![image](https://user-images.githubusercontent.com/43505031/48410709-b591fe80-e73f-11e8-92dd-ef382f0dffd1.png)

**Comment by Mikik3jr** [comment]
And according to patch note: Patch 3.3.0 (08-Dec-2009): Players shrunk while under the effects of this item will now be able to mount.

But here is a video from 09.06.2009 that shows you can mount up:
https://www.youtube.com/watch?v=CJvKo5TBlTQ

**Comment by Mikik3jr** [comment]
[This 10 years old video](https://www.youtube.com/watch?v=TFoYWcLVKy0) shows you at 1:35 that the player is mounting up while under the noggenfogger effect.

**Comment by craigsurbrook** [comment]
There were actually multiple posts from the internet in my original post, tried to copy the text instead of a screen shot like Mikik3jr:
1) By Travis (505 – 1·4) on 2007/11/08 (Patch 2.2.3)You can still ride a gryphon taxi when "You feel smaller...", best part is that the gryphon also shrinks. Appeared that the smaller gryphon flew lower than typical.
2) psychosam666 on 2007/11/19 (Patch 2.3.0)This also works for flying mounts. It's adorable to be on a minature Netherdrake! Posting screenshot.
3) Ashkir on 2009/08/30 (Patch 3.2.0)
For some reason you get an error now that says 'You Can't Do That Yet'.
4) Garon132 on 2010/01/15 (Patch 3.3.0)
Error was resolved in patch 3.3 You can now once again mount while small! ;D

Sorry that some of these didn't come through visibly or easy to read.

Notice the dates and patch of the posts (these match up with the post of a different thread with dates and times from Mikik3jr).

I just wanted to say, also, that I'm the GM of the first open-beta test Alliance guild on NW, and many people in the guild complained and were angry that the Noggenfogger mounting was "removed" because someone erroneously posted that it was only "added" in 3.3.0 during WotLK, where the poster didn't understand that it was a bug in WotLK and the 3.3.0 patch "fixed" it to work as it's supposed to where you can use Noggenfogger and mounts (as I explained in my first post to this thread) - where subsequently a developer removed mounting with Noggenfogger due to this erroneous bugtrack.

Given the shouting in gchat by people who were angry that it was removed, something simple like this is indeed important to the people who play the game (even if it doesn't seem like it's worth the time of a developer). The mounting was removed so easily, I'm sure it's equally as easy for a developer to put it back.

Thank you Mikik3jr for all the input, plus the 10yr old video showing the mounted noggenfogger so that I didn't have to go back and dig that all up myself. If all of this isn't sufficient, please let us know on this thread. I'm sure we could find more if it's required.

**Comment by Wolffenstein** [comment]
Fixed in rev 2339.
