### ISSUE TITLE
[NPC]Apprentice Andrethan#20463 should offer to "I wish to browse your wares." & Repair

### ISSUE THREAD

**Issue by Tenoutoften** [Atlantiss/NetherwingBugtracker#2657]
**Description**: 
[[NPC]Apprentice Andrethan#20463](https://www.wowhead.com/npc=20463/apprentice-andrethan#comments) should offer to "I wish to browse your wares." & Repair
https://youtu.be/6B06pLdHnXw?t=2

![18081709d5478116c6d4872dc95fe6f9](https://user-images.githubusercontent.com/34839199/48414442-0c510580-e74b-11e8-979a-59c5cd40cc10.png)

**Current behaviour**:
Doesn't offer to vendor/repair

**Expected behaviour**: 
 should offer to "I wish to browse your wares." & Repair

**Server Revision**: 
2304

**Comment by Tenoutoften** [comment]
He does offer his vendor items after delivering the quests, still doesn't offer to repair though

**Comment by Evolvee** [comment]
![image](https://user-images.githubusercontent.com/1942409/48501320-4a2e5680-e83d-11e8-84e1-e3fb4396833f.png)
he is fine for me

**Comment by Evolvee** [comment]
hmmm on PTR it doesnt

weird

**Comment by Evolvee** [comment]
rev cd
