### ISSUE TITLE
[NPC]Rhonsus deal 100% of his damage as fire, should be an effect in addition to his regular damage

### ISSUE THREAD

**Issue by Tenoutoften** [Atlantiss/NetherwingBugtracker#2658]
**Description**: 
[[NPC]Rhonsus#20410](https://www.wowhead.com/npc=20410/rhonsus#comments) is currently doing 100% fire damage 
![ce13fcd0d28a299171661d499905686d](https://user-images.githubusercontent.com/34839199/48418781-78853680-e756-11e8-9400-fdd0a4633354.png)

But should only deal 40 fire damage with his regular attack. - maybe something like this: https://db.excalibur.ws/?spell=36635
https://www.wowhead.com/spell=36635/fiery-weapon-proc
![7b36c94ec7858b40387986df942eff3a](https://user-images.githubusercontent.com/34839199/48418772-71f6bf00-e756-11e8-84e3-409f8dc1abe2.png)

I think this glow and damage should only happen after 
![d1749f0dc0d25c03170c7e9d21c008ff](https://user-images.githubusercontent.com/34839199/48419405-29d89c00-e758-11e8-89a3-834223c5d9b5.png)

I dont think he was dual wielding either...

Another report on the guy regarding him teleporting, I didnt witness this though: https://github.com/Atlantiss/NetherwingBugtracker/issues/2444

**Expected behaviour**: 
Expected to deal fire damage after he does his emote, expected to have his weapon visually start glowing at that point

**Server Revision**: 
2304

**Comment by Evolvee** [comment]
changed default dmg to normal

**Comment by Evolvee** [comment]
rev 2500
