### ISSUE TITLE
[Misc/RP Event][[Quest]Building a Perimeter#10240 RP flavour missing

### ISSUE THREAD

**Issue by Tenoutoften** [Atlantiss/NetherwingBugtracker#2659]
**Description**: 
[[Quest]Building a Perimeter#10240](https://www.wowhead.com/quest=10240/building-a-perimeter) missing visuals on completion:

A barrier should be formed around the area
https://youtu.be/XJQ8-gXHAp8?t=84
https://youtu.be/g_X00Det8fk?t=5

Small arcane explosion animations can be seen near the boarder... probably small sized invisible npcs casting it. Its purely visual
https://youtu.be/XI9NJ8RC4ak?t=34

Maybe this is why the Mana Seeker#]() is doing some sort of dampen magic animation?
https://youtu.be/g_X00Det8fk?t=27

Currently the NPC does his arcane explosion and that's about it.

**Expected behaviour**: 
Barrier & Arcane Explosions at the edges of the barrier.

**Server Revision**: 
2304

**Comment by Tenoutoften** [comment]
It can also cast soulbind while stunned...

**Comment by Evolvee** [comment]
fixed in 2318
