### ISSUE TITLE
[Quest] Damning Evidence - quest item missing in some loot tables

### ISSUE THREAD

**Issue by mhdemn** [Atlantiss/NetherwingBugtracker#2660]
**Description**: This [quest](https://db.excalibur.ws/?quest=10432) is about killing demons around the place and getting [these items](https://db.excalibur.ws/?item=29797) with a not too high - not too low droprate, 9-23% according to [wowhead](https://db.excalibur.ws/?item=29797#dropped-by), 15-25% according to [twinhead](https://tbc-twinhead.twinstar.cz/?item=29797#dropped-by) and 20% in [exca](https://www.wowhead.com/item=29797/orders-from-kaelthas#dropped-by).

**Current behaviour**: They are only dropping from [Mo'arg Warp Masters](https://db.excalibur.ws/?npc=20326) (with an acceptable droprate that feels like 20% I guess).

**Expected behaviour**: Should be dropping from [Daughters of Destiny](https://db.excalibur.ws/?npc=18860) (wowhead says 9% dr, exca says 20%, twinhead says 15%) and from [Gan'arg Warp-Tinkers](https://db.excalibur.ws/?npc=20285) (wowhead 21%, exca 20%, twinhead 25%) too.

These databases agree on that both Mo'args and Gan'args should be dropping with a fairly equal droprate.

Searched for footage from TBC times, could find this wowhead comment:

![image](https://user-images.githubusercontent.com/25901582/48425805-d9683b00-e765-11e8-9a35-de065b2e64ee.png)

It speaks of the three different mobs' droprates so they all three should be dropping it.

Maybe I've been extremely unlucky, but I've killed near 15-20 Masters for 5 orders, and double that number in tinkers and got none from the latters.

**Server Revision**: 2304

**Comment by aresbrutus** [comment]
Fixed in rev `Castilla`
