### ISSUE TITLE
Feign Death doesn't stop channeled spells currently being casted on the hunter

### ISSUE THREAD

**Issue by mhdemn** [Atlantiss/NetherwingBugtracker#2663]
Can't log in right now, I think we were at 2304 earlier, but this has been like this at least since I noticed.

When some mob or player casts a spell on you, you can feign death and automatically the caster gets "interrupted" as in they lose their target so cast doesn't continue. This works flawlessly unless the caster is a mob and it resists your feign death, in that case it's like you didn't cast it.

However currently in NW if the spell that's being casted is a channel as mind flay, arcane missiles and such, even a successful feign death won't stop it and they will keep targeting and casting at you. Didn't try with players' channeled casts.

I know channeled casts work a little different but I'm quite sure feign death is able to stop it where LoS-ing the caster, for example, doesn't. Will update with whatever proof or info I can find if there's a need to.

**Comment by Easyfraggy** [comment]
Need evidence from retail of this.

**Comment by mhdemn** [comment]
Well, after spending a while watching horrible 10 year old hunter pvp videos and looking around for any direct mention of this, I gave up on searching evidence for it.
So instead, here's a bunch of arguments and people not saying ever that channels were and exception:

1. This is common knowledge and this is googleable anytime. Feign Death gets you out of combat and wipes all your threat on all targets when you use it unless it gets resisted. So why would channels skip this mechanic? I mean if a hunter makes a pull and wants to FD when tank picks mobs up, or pulls too many and wants to FD and succeeds, why would some mob casting a channel on him keep him as target when he's supposed to wipe all aggro on him and exit combat? Never heard or seen a failed pull not because of a resisted FD but for a channel on the hunter.

2. Can't find anyone anywhere saying "it's a nice spell, gets people attacking you to stop doing so, worst case scenario you gain a couple seconds in PvP when it's a human player who you trying to fool. UNLESS you're getting channeled at, then whoever's the caster the spell doesn't work.

![image](https://user-images.githubusercontent.com/25901582/48548871-6e864380-e8ce-11e8-969c-8d93540970ad.png)

![image](https://user-images.githubusercontent.com/25901582/48548878-71813400-e8ce-11e8-8456-95e4434f43b8.png)

![image](https://user-images.githubusercontent.com/25901582/48548881-73e38e00-e8ce-11e8-9d3d-c0c213c85869.png)

![image](https://user-images.githubusercontent.com/25901582/48548883-7645e800-e8ce-11e8-8c98-e9d47278cb1c.png)

3. This is logical though, if you successfully feign death against some monster, it will stop attacking you. Hell, you can even stand amongst a raid mob pack while feigning death and they will do as you weren't there. Why would a spell, to be precise a channeled one by an exception through which a mob can ignore this mechanic?

**Comment by Easyfraggy** [comment]
Fixed i believe? @Wolffenstein

**Comment by Manaci** [comment]
Fixed in rev 2775
