### ISSUE TITLE
Missing Friends 

### ISSUE THREAD

**Issue by miviv1268** [Atlantiss/NetherwingBugtracker#2664]
[//]: # (Enclose links to things related to the bug using http://wowhead.com or any other TBC database.)
[//]: # (You can use screenshot ingame to visual the issue.)
[//]: # (Write your tickets according to the format:)
[//]: # ([Quest][Azuremyst Isle] Red Snapper - Very Tasty!)
[//]: # ([NPC] Magistrix Erona)
[//]: # ([Spell][Mage] Fireball)
[//]: # ([Npc][Drop] Ghostclaw Lynx)
[//]: # ([Web] Armory doesnt work)

**Description**: 
Can't open or interact with the cage for some reason
**Current behaviour**:
![ezgif com-video-to-gif](https://user-images.githubusercontent.com/43628154/48445794-7d9db200-e765-11e8-9004-a80a21d90bb5.gif)

**Expected behaviour**: 
Too interact with the Cages and Complete the Quest
**Server Revision**:

**Comment by ScottieDOESknow** [comment]
Completed this quest with no issues 12 hours ago.

**Comment by xmesaj2** [comment]
cannot reproduce

**Comment by Easyfraggy** [comment]
Probably ALT bugged.

**Comment by The14me** [comment]
If someone bug out again like that... Exit game+delete cache folder fix the issue.
