### ISSUE TITLE
[Quest]Creatures of the Eco-Dome#10427, Talbuks are on the ground for too long, Talbuk Doe missing emote

### ISSUE THREAD

**Issue by Tenoutoften** [Atlantiss/NetherwingBugtracker#2666]
**Description**: 
[[Quest]Creatures of the Eco-Dome#10427](https://www.wowhead.com/quest=10427/creatures-of-the-eco-domes)

* [[NPC]Talbuk Doe#20610](https://www.wowhead.com/npc=20610/talbuk-doe) should "calls for the aid of a nearby male!" if there is a [[NPC]Talbuk Sire#20777](https://www.wowhead.com/npc=20777/talbuk-sire) nearby, can be seen [here](https://youtu.be/5HXLxHDvtN0?t=28)
![ca282baff2107835612e97564fb2af3d](https://user-images.githubusercontent.com/34839199/48448607-e43fc180-e79f-11e8-837e-d8b90fe475f6.png)

* The [[NPC]Talbuk Doe#20610](https://www.wowhead.com/npc=20610/talbuk-doe) & [[NPC]Talbuk Sire#20777](https://www.wowhead.com/npc=20777/talbuk-sire) remain on the ground for too long after using [[Item]Talbuk Tagger#29817](https://www.wowhead.com/item=29817/talbuk-tagger)=>[[Spell]Tag Subbued Talbuk#35771](https://www.wowhead.com/spell=35771/tag-subbued-talbuk) They should only be on the ground for 20 seconds, then return to normal state:
![4c223abb4314674e38993f859aef5bae](https://user-images.githubusercontent.com/34839199/48448716-2ff26b00-e7a0-11e8-824d-1f04cc114a6c.png)
![55a3077210da03244013c6557d25f0cb](https://user-images.githubusercontent.com/34839199/48448750-4a2c4900-e7a0-11e8-833d-ec94e9dae2c5.png)
![f17d684e871ed101a61bbaca8a67075a](https://user-images.githubusercontent.com/34839199/48448761-52848400-e7a0-11e8-9d9a-522d5c90102d.png)

**Server Revision**: 
2304

**Comment by aresbrutus** [comment]
The RP emote thing: https://github.com/Atlantiss/AtlantissTBCBT/issues/3245

**Comment by Evolvee** [comment]
wolfs shit cpp...

**Comment by lhevraz** [comment]
Still bugged.

**Comment by Wolffenstein** [comment]
Fixed in rev 2777.
