### ISSUE TITLE
Quest - Thunderlord Clan Artifact

### ISSUE THREAD

**Issue by Novat93** [Atlantiss/NetherwingBugtracker#2668]
[//]: # (Enclose links to things related to the bug using http://wowhead.com or any other TBC database.)
[//]: # (You can use screenshot ingame to visual the issue.)
[//]: # (Write your tickets according to the format:)
[//]: # ([Quest][Azuremyst Isle] Red Snapper - Very Tasty!)
[//]: # ([NPC] Magistrix Erona)
[//]: # ([Spell][Mage] Fireball)
[//]: # ([Npc][Drop] Ghostclaw Lynx)
[//]: # ([Web] Armory doesnt work)

**Description**: The item which begins a quest, Thunderlord Clan Artifact seem to be dropping at a very low rate.
item=30431
quest=10524 - The quest it starts

**Current behaviour**:
After killing ogres in a 2 man group for about an hour, the item (30431) has yet to drop.

**Expected behaviour**: 
Due to how many quests are locked behind the player getting the drop, and the fact that Blizzard added a quest which instructs the player to kill 30 ogres. (quest=10503). It stands to reason, that there should be a decent chance the player would get the item within the 30 ogres killed.

**Server Revision**: 
2304

**Comment by aresbrutus** [comment]
Fixed in rev `Castilla`
