### ISSUE TITLE
[NPC]Severed Spirit shouldn't "attempts to run away in fear!"

### ISSUE THREAD

**Issue by Tenoutoften** [Atlantiss/NetherwingBugtracker#2669]
**Description**: 
[[NPC]Severed Spirit#19881](https://www.wowhead.com/npc=19881/severed-spirit#objective-of) shouldn't "attempts to run away in fear!"
Currently does:
![1ad353495897e96b4cfcbe299b3e1c97](https://user-images.githubusercontent.com/34839199/48452279-aa29ec00-e7ae-11e8-832a-bfbb5c8d27fa.png)

Never runs away in fear:
https://youtu.be/PpgUMoAzags?t=7
https://youtu.be/PpgUMoAzags?t=25
https://youtu.be/PpgUMoAzags?t=75
https://youtu.be/PpgUMoAzags?t=81
https://youtu.be/PpgUMoAzags?t=130
https://youtu.be/PpgUMoAzags?t=137
https://youtu.be/PpgUMoAzags?t=155
https://youtu.be/PpgUMoAzags?t=176
https://youtu.be/PpgUMoAzags?t=191
https://youtu.be/PpgUMoAzags?t=213
https://youtu.be/PpgUMoAzags?t=292
https://youtu.be/PpgUMoAzags?t=312

**Expected behaviour**: 
Expected to not run away in fear

**Server Revision**: 
2304

**Comment by Evolvee** [comment]
rev cd
