### ISSUE TITLE
[NPC] Defias Traitor - 467

### ISSUE THREAD

**Issue by Scylla420** [Atlantiss/NetherwingBugtracker#267]
**Description**: 
During the Escort quest The Defias Brotherhood (155), the Defias Traitor (467) does not help us with nearby mobs that we're in combat with.  He will only assist in combat if he's the one that's attacked first.
**Current behaviour**:
[He walks completely past nearby enemies that we're in combat with](https://streamable.com/vnt1j)
**Expected behaviour**: 
[If the defias traitor paths near an enemy that we're attacking, he should help.](https://youtu.be/7eVju9ndvBE?t=3m25s)
**Server Revision**: 
2032

**Comment by Evolvee** [comment]
@Wolffenstein pls https://github.com/Atlantiss/AtlantissTBCBT/issues/2591 - when u do it also convert all sai escorts to that react state :D currently the asist react state cockblocked the script entirely and prevent executing all further

**Comment by Buggyswires** [comment]
https://www.youtube.com/watch?v=4yGTJV9-MEk

**Comment by The14me** [comment]
move to https://github.com/Atlantiss/NetherwingBugtracker/issues/3678
