### ISSUE TITLE
[Npc][Spell] Kil'sorrow Spellbinder - Chains of Ice

### ISSUE THREAD

**Issue by Kaini27** [Atlantiss/NetherwingBugtracker#2670]
[//]: # (Enclose links to things related to the bug using http://wowhead.com or any other TBC database.)
[//]: # (You can use screenshot ingame to visual the issue.)
[//]: # (Write your tickets according to the format:)
[//]: # ([Quest][Azuremyst Isle] Red Snapper - Very Tasty!)
[//]: # ([NPC] Magistrix Erona)
[//]: # ([Spell][Mage] Fireball)
[//]: # ([Npc][Drop] Ghostclaw Lynx)
[//]: # ([Web] Armory doesnt work)

**Description**: Under effect of Chains of Ice player should not only be rooted, but also lose mana.
Npc ID: 17145
Spell ID: 22744
Mana burning aura ID: **22745**

**Current behaviour**: There is sound effect of a mana burn and purple animation of it on a player, but it does not drain any mana. 

**Expected behaviour**: Chains of Ice casted by Kil'sorrow Spellbinder should burn mana every 2 seconds for 10 seconds (5 times) by amount of 350-450 mana points (350 on some sources).

**Server Revision**: 2304

**Comment by xmesaj2** [comment]
fixed in rev 2334
