### ISSUE TITLE
[NPC][Spell] Voidshrieker - Damage Reduction: %magic school name%

### ISSUE THREAD

**Issue by Kaini27** [Atlantiss/NetherwingBugtracker#2671]
[//]: # (Enclose links to things related to the bug using http://wowhead.com or any other TBC database.)
[//]: # (You can use screenshot ingame to visual the issue.)
[//]: # (Write your tickets according to the format:)
[//]: # ([Quest][Azuremyst Isle] Red Snapper - Very Tasty!)
[//]: # ([NPC] Magistrix Erona)
[//]: # ([Spell][Mage] Fireball)
[//]: # ([Npc][Drop] Ghostclaw Lynx)
[//]: # ([Web] Armory doesnt work)

**Description**: The school of magic that NPC goes for and resistance buff are not defined in first combat. If you reset combat just once- it starts working properly

**Current behaviour**: Uses predefined school of magic and does not gains resistance buff. Tested on holy damage.

**Expected behaviour**: behaviour of NPC is correct on 2nd interaction with a player, but it wont happen because player would kill it on first one.

**Server Revision**: 2304

**Comment by ircfelix** [comment]
What?

**Comment by Evolvee** [comment]
rev cd
