### ISSUE TITLE
[NPC] Infernal Warbringer Immolation DoT 

### ISSUE THREAD

**Issue by Merkmode** [Atlantiss/NetherwingBugtracker#2672]
![immolation glitch](https://user-images.githubusercontent.com/44766722/48468133-a6976480-e7b0-11e8-9140-666aa55e8a6d.png)

([Quest][Hellfire Peninsula] The Path of Anguish)
([NPC] Infernal Warbringer)
([Spell] Immolation DoT)

**Description**: Went to approach the mob to kill it for the quest and the DoT it naturally does was doing its ticks like 5 times a second

**Current behaviour**: Mobs doing nearly 500 DPS just from its natural DoT from Immolation

**Expected behaviour**: Should only be doing it once every several seconds

**Server Revision**: 2304

**Comment by Easyfraggy** [comment]
https://github.com/Atlantiss/NetherwingBugtracker/issues/2334
