### ISSUE TITLE
[Spell][Racial] Berserking is still working improperly

### ISSUE THREAD

**Issue by sifiuocz** [Atlantiss/NetherwingBugtracker#2673]
**Description**: 
Berserking a racial ability of all Trolls still doesn't work. When doing my calculations I am going off of Terraism's post in this thread: https://www.wowhead.com/forums&topic=27913

> Berserking: ... this increases your attack speed by 10-30%, depending on your current health. If you have 40% or less, it's the full 30% boost, otherwise it varies relative to your health.

and off of this article on Wowwiki website: http://wowwiki.wikia.com/wiki/Haste. Afaik this is an up-to-date formula used in 2.4.3

> Weapon Speed = weapon base speed / ((1+haste modifier A /100)×(1+haste modifier B /100)× ... × (1+ haste modifier K / 100))

As a proof i am posting a screenshot of my hunter that has 20% attack speed from a talent called "Serpent's swiftness" and 10% more attack speed from my quiver "Medium Quiver"
![wowscrnshot_111418_183252](https://user-images.githubusercontent.com/13140968/48500679-b6a85600-e83b-11e8-8fe8-f827a58b8539.jpg)
![wowscrnshot_111418_183017](https://user-images.githubusercontent.com/13140968/48500684-b90ab000-e83b-11e8-8c5f-d66b5168493f.jpg)

weapon speed = 2.7/((1+20/100)×(1+10/100)) = 2.7/(1.2×1.1) = 2,045

**Current behaviour**:
Berserking increases attack speed by too much.
At 100% health my weapon speed is:
![wowscrnshot_111418_184150](https://user-images.githubusercontent.com/13140968/48501222-04718e00-e83d-11e8-9f07-766b7ab5986c.jpg)
1.65=2,7/(1.1×1,2×x)
x=2.7/(1.65×1.1×.1.2)=1.24
Berserking attack speed yield = 24 %

Below 40% health my weapon speed is:
![wowscrnshot_111418_181447](https://user-images.githubusercontent.com/13140968/48501434-7ea21280-e83d-11e8-8d55-9c400403c429.jpg)
1.12=2.7/(1.1×1.2×x)
x=2.7/(1.12×1.1×1.2)=1.82
Berserking attack speed yield = 82%

**Expected behaviour**: 
As you can see 82% attack speed increase would alter the game balance by quite a lot. Please have another look into this.

**Server Revision**: 
2304

**Comment by sifiuocz** [comment]
Asterisk symbol is used change my text to itallics so i will use × symbol for multiplying

**Comment by Easyfraggy** [comment]
Did you account for quiver?

I get with 2,5 sec cast time 2,27 cast time which is correct at 10% buff.

**Comment by sifiuocz** [comment]
@Easyfraggy Did you read my report?
I say specifically that I use Medium Quiver and account in that in my calculations. This needs a reopen. Also EasyFraggy is talking about casting time while I am talking about weapon speed.

**Comment by Easyfraggy** [comment]
You explain very weirdly by not doing the calculation how it should be but rather what it shows.

For your 100% example it should be 2,7/(1,1*1,2*1,1) = 1,859. That would clearly show that you are getting too much haste from it instead of all these backwards calculations. 

Reopened and Y it does give too much haste. With 2,2 speed no talents no quiver full health I get random numbers:
1,54
1,77
1,55
1,68
While it should be 2,0.

**Comment by Tereneckla** [comment]
https://www.youtube.com/watch?v=8aykvZ69ITE

**Comment by Tereneckla** [comment]
Working 100% correct for spells on PTR now

Melee/Ranged seems to consist of 2 attack speed buffs. One is scaling with your missing hp, one is a random value.
