### ISSUE TITLE
[Music] Kil'sorrow Fortress plays wrong music track

### ISSUE THREAD

**Issue by tepex0** [Atlantiss/NetherwingBugtracker#2674]
**Description**: The music in Kil'sorrow Fortress in southern Nagrand plays the music from STV

**Current behaviour**: Plays STV music

**Expected behaviour**: Plays not-STV STV music, unsure what it should be

**Server Revision**: 2304

**Comment by Easyfraggy** [comment]
Music is client side - we can't control it.
