### ISSUE TITLE
[Item] [Patch 2.1] Relentless Earthstorm Diamond design on vendor

### ISSUE THREAD

**Issue by tepex0** [Atlantiss/NetherwingBugtracker#2675]
**Description**: Design: Relentless Earthstorm Diamond is available from the 
Consortium Quartermaster Paulsta'ats 

**Current behaviour**: The design is available from the vendor

**Expected behaviour**: The design should not be available until patch 2.1
http://wowwiki.wikia.com/wiki/Design:_Relentless_Earthstorm_Diamond

**Server Revision**: 2304

**Comment by aresbrutus** [comment]
This was already on my sheet but must have missed updating it for the database. Thank you for your report, this will be fixed in rev `Castilla`

**Comment by tepex0** [comment]
https://i.imgur.com/0H0Tj8T.jpg
Design is available from the Netherstorm vendor @aresbrutus

**Comment by aresbrutus** [comment]
Seems I forgot to put the changes I made in dev into the file. Should be working after rev `Phoebe` Please recheck.
