### ISSUE TITLE
[NPC] Vir'aani Raider makes elekk noise when crit

### ISSUE THREAD

**Issue by tepex0** [Atlantiss/NetherwingBugtracker#2676]
**Description**: NPC Vir'aani Raider around Oshu'gun in Nagrand makes elekk noise 
https://www.wowhead.com/npc=17149/viraani-raider

**Current behaviour**: Vir'aani raider makes elekk noise when crit

**Expected behaviour**: Vir'aani raider not making elekk noise when crit

**Server Revision**: 2304

**Comment by ScottieDOESknow** [comment]
sound bug dupe

https://github.com/Atlantiss/NetherwingBugtracker/issues/2315

**Comment by Easyfraggy** [comment]
Well evolves fix has been live for a while - so this sound bug seems to still be present regardless?

**Comment by Tereneckla** [comment]
Fixed

**Comment by Godmatik** [comment]
Duplicate
