### ISSUE TITLE
[NPC][Arcatraz] Gargantuan Abyssal

### ISSUE THREAD

**Issue by Easyfraggy** [Atlantiss/NetherwingBugtracker#2677]
**Description**: 
It would be very odd that there are no comments about being able to avoid his meteor ability by stunning him.
https://www.wowhead.com/npc=20898/gargantuan-abyssal#comments

**Current behaviour**:
Currently Stunable.

**Expected behaviour**: 
Shouldn't be stunable.

**Server Revision**: 2304

**Comment by Godmatik** [comment]
Still stunnable

**Comment by Manaci** [comment]
Fixed
