### ISSUE TITLE
[NPC] Grand Warlock Nethekurse (Heroic)

### ISSUE THREAD

**Issue by AxeCell** [Atlantiss/NetherwingBugtracker#2679]
**Description**: 
When dropping low, the boss will channel a spin attack acting as a mini-enrage for you to kill him quickly enough.

**Current behaviour**:
He started casting the spin and canceled it after 2 seconds. The cancellation happened at the same time as one of our party members died.

**Expected behaviour**: 
He should finish his spinning attack.

**Server Revision**: 
2304

**Comment by Liquidsoap** [comment]
This just happened to our group as well. He started channeling his [Dark Spin] and our tank moved away and the boss followed the tank which canceled the [Dark Spin]. The boss should remain in place and channel [Dark Spin] until he dies.

**Comment by Fenvarien1** [comment]
https://youtu.be/VenF3F4qmB4?t=64 here you see him spin at 20% commented

**Comment by Wolffenstein** [comment]
Fixed in rev 2447.
