### ISSUE TITLE
[NPC] Warchief Kargath Bladefist (Heroic)

### ISSUE THREAD

**Issue by AxeCell** [Atlantiss/NetherwingBugtracker#2682]
**Description**: 
Warchief Kargath Bladefist is found within The Shattered Halls, acting as the last boss.

**Current behaviour**:
Dropped 1 item alongside the Primal Nether.

**Expected behaviour**: 
Should drop atleast 2 items alongside the Primal Nether.

**Server Revision**: 
2304

**Comment by aresbrutus** [comment]
https://github.com/Atlantiss/NetherwingBugtracker/issues/3438
