### ISSUE TITLE
[Warlock] [Pet] [Core Mechanic] Dismiss/Recall behaviors

### ISSUE THREAD

**Issue by Shalovski** [Atlantiss/NetherwingBugtracker#2688]
**Description**: A new pet is re-summoned every time the warlock teleports/zones/mounts or uses the command "/run PetAbandon()", causing unintented behaviors.

**Current behavior**: If the Warlock performs an action that temporarily "dismisses" its pet (teleporting/zoning/mounting/run PetAbandon()), the action that will bring it back will re-summon a fresh new pet, thus erasing all of its previous buffs and refreshing all of its cooldowns.

For example, mounting right after using "Intercept" on the Felguard will cause its cooldown to be refreshed when the Warlock dismounts.

Another example, mounting after getting buffs on the pet will remove all of them once the Warlock dismounts.

_TL;DR : Actions that automatically recall Warlocks' pets re-summon new unbuffed pets with cleared ability cooldowns._

**Expected behavior**: Teleporting/zoning/dismounting/run PetAbandon() should bring back the pet to its previous state, and not summon a fresh new one (thus keeping its cooldowns and buffs.)
The current behavior should only happen when summoning a new pet manually, with the exception of re-summoning the same pet type after using the commonly known command "/run PetAbandon()" - which should bring back the same buffed pet back, just as expected when teleporting/zoning/dismounting.

[Source](https://web.archive.org/web/20130811112339/http://elitistjerks.com/f80/t17008-pve_raiding_compendium/) for "/run PetAbandon()" cases : "- Demons about to die can be dismissed and nearly instantly resummoned with Fel Domination. This will conserve their buffs, and bring them back with full health and mana. The command to dismiss a demon is /run PetAbandon(), which can be macro'd and assigned to a button."

_TL;DR : Actions that automatically recall Warlocks' pets should bring back the same **buffed** pet without clearing all of their ability cooldowns._

**Server Revision**: 2304

**Comment by Tereneckla** [comment]
Fixed
