### ISSUE TITLE
'Show Enemy Nameplates' cast bar freezes, does not fill.

### ISSUE THREAD

**Issue by Giantulol** [Atlantiss/NetherwingBugtracker#269]
**Description**: 
'Show Enemy Nameplates' cast bar freezes, does not fill.
Tested this on many mobs, not only Maggot as you can see in the screenshot pasted below.

**Current behaviour**:
The cast bar does not fill as supposed to and freezes after spell is done untill the mob died.

**Expected behaviour**: 
The cast bar should fill.  (yellow orange-ish)

https://i.imgur.com/eOXdZVe.jpg

**Comment by wtRCH** [comment]
It's client side
