### ISSUE TITLE
[NPC] Ravager Hatchling [Tame Beast] - Pet has no Ravage/Bite Ability

### ISSUE THREAD

**Issue by Merkmode** [Atlantiss/NetherwingBugtracker#2690]
**Description**: After taming the Ravager Hatchling as a pet it had no Ravage/Bite Ability

**Current behaviour**: The pet only has Growl and Dash ability

**Expected behaviour**: The pet should have all of its standard abilities when tamed (Dash, Ravage, Bite, Gore etc.)

**Server Revision**:

**Comment by sifiuocz** [comment]
Not every pet you tame has abilities they know right away.
