### ISSUE TITLE
[Spell] Stealth

### ISSUE THREAD

**Issue by ahlens** [Atlantiss/NetherwingBugtracker#2692]
[//]: # (Enclose links to things related to the bug using http://wowhead.com or any other TBC database.)
[//]: # (You can use screenshot ingame to visual the issue.)
[//]: # (Write your tickets according to the format:)
[//]: # ([Quest][Azuremyst Isle] Red Snapper - Very Tasty!)
[//]: # ([NPC] Magistrix Erona)
[//]: # ([Spell][Mage] Fireball)
[//]: # ([Npc][Drop] Ghostclaw Lynx)
[//]: # ([Web] Armory doesnt work)

**Description**: 
I'd like to discuss one mechanic regarding [Stealth ](https://vanilla-twinhead.twinstar.cz/?spell=1784)as on this server I can see it for the first time. Maybe it's working correctly, I'm not sure. Let me know what do you think.

**Current behaviour**:
When we are in [Stealth ](https://vanilla-twinhead.twinstar.cz/?spell=1784)and we are debuffed from for example dot spell, our stealth immediately breaks off regardless taking any kind of damage in moment where debuff is applied.

**Expected behaviour**: 
I was sure [Stealth ](https://vanilla-twinhead.twinstar.cz/?spell=1784)should be cancelled after taking dmg, not when debuff is applied. So giving you the example, Warlock spotted you, targeted you, put a dot on you but you should be still able to for example Cheap Shoot him because you haven't recieved any dmg yet, only debuff was applied.

**Server Revision**: 
2304

**Comment by Evolvee** [comment]
Working correctly
