### ISSUE TITLE
[Object] [STV] Half-Buried Bottle unlootable

### ISSUE THREAD

**Issue by Labteth** [Atlantiss/NetherwingBugtracker#2694]
**Description**: 
The Half-Buried Bottle (item 2560) at 33.8 77.7 is is unlootable even though I can interact with it.  Other bottles appear to be working as intended.

**Current behaviour**:
Interacting with the object gives no loot and the object remains able to be interacted with.

**Expected behaviour**: 
Interacting with the object should contain "Carefully Folded Note" (Item 4098) 25% of the time as well as other junk items.

**Server Revision**:

**Comment by Shanghi** [comment]
This should be fixed in revision 2555. The quest item had a bad restriction that wouldn't let you see/take it if you were below a certain level so any bottles with it could look empty and messed up.
