### ISSUE TITLE
[Quest][Shadowmoon Valley] Demonic Crystal Prisons

### ISSUE THREAD

**Issue by Mikik3jr** [Atlantiss/NetherwingBugtracker#2695]
[//]: # (Enclose links to things related to the bug using http://wowhead.com or any other TBC database.)
[//]: # (You can use screenshot ingame to visual the issue.)
[//]: # (Write your tickets according to the format:)
[//]: # ([Quest][Azuremyst Isle] Red Snapper - Very Tasty!)
[//]: # ([NPC] Magistrix Erona)
[//]: # ([Spell][Mage] Fireball)
[//]: # ([Npc][Drop] Ghostclaw Lynx)
[//]: # ([Web] Armory doesnt work)

**Description**: 
[In this quest](https://www.wowhead.com/quest=10528/demonic-crystal-prisons) you have to kill this [succubus](https://www.wowhead.com/npc=21309/painmistress-gabrissa#comments) to get a [key](https://www.wowhead.com/item=30442/crystalline-key) from her.
**Current behaviour**:
The key doesn't have 100% drop chance.
![wowscrnshot_111518_160702](https://user-images.githubusercontent.com/43505031/48562827-4957fc00-e8f3-11e8-87b6-ceb3f5e8f592.jpg)

**Expected behaviour**: 
Acording to Kutsal and logic (which not always work with Blizzard) it should be 100%. I mean why not? There is only 1 Painmistress Gabrissa in the game that drops this item, so why wouldn't it have 100% drop rate?
**Server Revision**: 
2304

**Comment by aresbrutus** [comment]
Fixed in rev `Castilla`
