### ISSUE TITLE
[NPC] Wrath-Scryer Soccothrates flame shocks too frequently.

### ISSUE THREAD

**Issue by Mikik3jr** [Atlantiss/NetherwingBugtracker#2696]
[//]: # (Enclose links to things related to the bug using http://wowhead.com or any other TBC database.)
[//]: # (You can use screenshot ingame to visual the issue.)
[//]: # (Write your tickets according to the format:)
[//]: # ([Quest][Azuremyst Isle] Red Snapper - Very Tasty!)
[//]: # ([NPC] Magistrix Erona)
[//]: # ([Spell][Mage] Fireball)
[//]: # ([Npc][Drop] Ghostclaw Lynx)
[//]: # ([Web] Armory doesnt work)

**Description**: 
Arcatraz boss. https://www.wowhead.com/npc=20886/wrath-scryer-soccothrates#comments
**Current behaviour**:
Using his flame shock too many times. It can shock 3 players at the same time.
**Expected behaviour**: 
[According to this 11 years old video](https://www.youtube.com/watch?v=-1WdabqfyH8) this boss doesn't shock that frequently.
**Server Revision**: 
2304

**Comment by Mikik3jr** [comment]
(It happened on normal IIRC)

**Comment by Mikik3jr** [comment]
This is happened on HC (WARNING very shocking picture!)
![image](https://user-images.githubusercontent.com/43505031/48860150-60e62780-edc0-11e8-8b7a-7961974f8823.png)

**Comment by Easyfraggy** [comment]
timestamps :(

**Comment by Mikik3jr** [comment]
Sadly I tried to put timestamps on combat log, but couldn't find out how.

However, the Felfire Shock puts a not removeable dot on me, so the dot dmg should be seen there, but I can't see it.

**Comment by Brasso** [comment]
Can confirm. Shock doesn't seem to have a cooldown. Almost unkillable atm.

2356

**Comment by Easyfraggy** [comment]
I think this should be fixed - can someone retest?
