### ISSUE TITLE
[Item] [Patch 2.3] Cenarion War Hippogryph

### ISSUE THREAD

**Issue by tepex0** [Atlantiss/NetherwingBugtracker#2700]
**Description**: Cenarion War Hippogryph is available to buy from the Cenarion quartermaster Fedryen Swiftspear

https://www.wowhead.com/item=33999/cenarion-war-hippogryph#comments

**Current behaviour**: mount is available

**Expected behaviour**: mount not available until patch 2.3

**Server Revision**: 2304

**Comment by zauru7** [comment]
looks to be already fixed in 2319
![2319](https://user-images.githubusercontent.com/44526051/48580301-1a577f80-e91f-11e8-92d3-905681554501.PNG)
