### ISSUE TITLE
[Spell] Misdirection

### ISSUE THREAD

**Issue by Ahmpy** [Atlantiss/NetherwingBugtracker#2702]
[//]: # (Enclose links to things related to the bug using http://wowhead.com or any other TBC database.)
[//]: # (You can use screenshot ingame to visual the issue.)
[//]: # (Write your tickets according to the format:)
[//]: # ([Quest][Azuremyst Isle] Red Snapper - Very Tasty!)
[//]: # ([NPC] Magistrix Erona)
[//]: # ([Spell][Mage] Fireball)
[//]: # ([Npc][Drop] Ghostclaw Lynx)
[//]: # ([Web] Armory doesnt work)

**Description**: Currently misdirection is wonky when there are multiple hunters attempting to use it. Once a player uses MD on a target, that target cannot recieve another MD from a different hunter until the 30s buff wears out.

**Expected behaviour**: Hunters should be able to back-to-back MD targets and even override MD on targets, the spell should not prevent others from using it while it is active on a target.

**Server Revision**:  2321

**Comment by Wolffenstein** [comment]
Fixed in rev 2984.
