### ISSUE TITLE
[Quest] Using Smoke Beacon on Zeth'Gur Must Burn crashes game

### ISSUE THREAD

**Issue by Dollywog** [Atlantiss/NetherwingBugtracker#2703]
[//]: # (Enclose links to things related to the bug using http://wowhead.com or any other TBC database.)
[//]: # (You can use screenshot ingame to visual the issue.)
[//]: # (Write your tickets according to the format:)
[//]: # ([Quest][Azuremyst Isle] Red Snapper - Very Tasty!)
[//]: # ([NPC] Magistrix Erona)
[//]: # ([Spell][Mage] Fireball)
[//]: # ([Npc][Drop] Ghostclaw Lynx)
[//]: # ([Web] Armory doesnt work)

**Description**: When activating the Smoke Beacon quest item on Zeth'Gur Must Burn on the northern tower my client freezes and closes each time

**Expected behaviour**:  Have replicated this three times now, no other issues until this last few hours playing

**Server Revision**:

**Comment by Dollywog** [comment]
Also happened at Southern Tower now, have received credit for the item use though at least

**Comment by Dollywog** [comment]
I am now getting freezes engaging certain mobs also in this area, one of the patrolling Wold Riders near the Foothill Tower

**Comment by Manaci** [comment]
Fixed
