### ISSUE TITLE
Puking from Overpowering Sickness debuff during flight makes interesting mechanic

### ISSUE THREAD

**Issue by Mikik3jr** [Atlantiss/NetherwingBugtracker#2705]
[//]: # (Enclose links to things related to the bug using http://wowhead.com or any other TBC database.)
[//]: # (You can use screenshot ingame to visual the issue.)
[//]: # (Write your tickets according to the format:)
[//]: # ([Quest][Azuremyst Isle] Red Snapper - Very Tasty!)
[//]: # ([NPC] Magistrix Erona)
[//]: # ([Spell][Mage] Fireball)
[//]: # ([Npc][Drop] Ghostclaw Lynx)
[//]: # ([Web] Armory doesnt work)

**Description**: 
In a quest called Of Thistleheads And Eggs you pick up eggs in SMV. If you are unlucky you get a [Rotting Putrescence](https://www.wowhead.com/spell=36810/rotting-putrescence) debuff for 1 minute. In random times you start to vomit (Overpowering Sickness spellname), you are stunned and you lose health during vomiting.

**Current behaviour**:
I used gryph in SVM(Wildhammer Stronghold) to fly to Shatt. During fly I started to puke and it instantly teleported me to Shatt. After this I was kinda sharding/phasing?
Here how it looked like: https://www.youtube.com/watch?v=QJdXLP6-kik&feature=youtu.be
It disappeared after a short time. (I think it was over after I "actually" arrived from the flight)

**Expected behaviour**: 
I don't find anything about this, but it looks so no intentional effect that I don't think it should work like this.

**Server Revision**: 
2321

**Comment by Mikik3jr** [comment]
Wolf secretly putting sharding into TBC confirmed.

**Comment by Tereneckla** [comment]
https://www.youtube.com/watch?v=HzAHZX-RSmw

**Comment by Wolffenstein** [comment]
Fixed in rev 3368.
