### ISSUE TITLE
[Quest][Shadowmoon Valley] To Catch A Thistlehead

### ISSUE THREAD

**Issue by Mikik3jr** [Atlantiss/NetherwingBugtracker#2706]
[//]: # (Enclose links to things related to the bug using http://wowhead.com or any other TBC database.)
[//]: # (You can use screenshot ingame to visual the issue.)
[//]: # (Write your tickets according to the format:)
[//]: # ([Quest][Azuremyst Isle] Red Snapper - Very Tasty!)
[//]: # ([NPC] Magistrix Erona)
[//]: # ([Spell][Mage] Fireball)
[//]: # ([Npc][Drop] Ghostclaw Lynx)
[//]: # ([Web] Armory doesnt work)

**Description**: 
You place a trap so the bodyguard (Blood Lord Zarath) weill leave the target NPC, and you can kill him:
https://www.youtube.com/watch?v=qyiS0FaqjtA

**Current behaviour**:
The target NPC is already standing there and unkillable:
![wowscrnshot_111518_234902](https://user-images.githubusercontent.com/43505031/48587049-05381c00-e932-11e8-9381-8c34460064d7.jpg)

The guard leaves too late. As a holy paladin I slowly killed the quest guy, and even after that the guard was there.
![wowscrnshot_111518_235045](https://user-images.githubusercontent.com/43505031/48587059-0e28ed80-e932-11e8-92f0-82b30a8b0c9c.jpg)

**Expected behaviour**: 
- The guy should not be there without starting the event
- THe guard should leave earlier for RP purposes, and it would be bad if I accidentaly pull him while I kill the quest guy.

**Server Revision**: 
2321

**Comment by ScottieDOESknow** [comment]
Visible trigger. Duplicate.

https://github.com/Atlantiss/NetherwingBugtracker/issues/2406

**Comment by Bildo** [comment]
issue fixed some time ago
