### ISSUE TITLE
The Prophecy Of Akida doesn't work

### ISSUE THREAD

**Issue by csjansen** [Atlantiss/NetherwingBugtracker#271]
[//]: # (Enclose links to things related to the bug using http://wowhead.com or any other TBC database.)
[//]: # (You can use screenshot ingame to visual the issue.)
[//]: # (Write your tickets according to the format:)
[//]: # ([Quest][Azuremyst Isle] Red Snapper - Very Tasty!)
[//]: # ([NPC] Magistrix Erona)
[//]: # ([Spell][Mage] Fireball)
[//]: # ([Npc][Drop] Ghostclaw Lynx)
[//]: # ([Web] Armory doesnt work)

**Description**: 
The Prophecy Of Akida doesn't work
**Current behaviour**:
You do not get credit for freeing Stillpine Captives
**Expected behaviour**: 
You should get credit
**Server Revision**:

**Comment by aresbrutus** [comment]
Can you clear your cache folder and try again? It works for me.

**Comment by xmesaj2** [comment]
I can look at it but check if this solves it

**Comment by csjansen** [comment]
Cleared cache and still doesn't work.

**Comment by csjansen** [comment]
Also, dropped quest and re-acquired.  Stillpine Ancestor says $n instead of name.  Quest still is not providing progress

**Comment by csjansen** [comment]
MaceToFace in game.  Stuck on this quest do to needed it to continue lines.

**Comment by Evolvee** [comment]
@xmesaj2 i probably accidentaly applied a fix to it which bugged 

Basically it changed the target gob sends to npc from closest pc to action invoker

There is a core issue tho - the gob doesnt know the invoker so it sends null as stored target

Just apply the script from earlier DB backup to the gob cage

**Comment by narayagh** [comment]
Additionally: 
![2018-09-24_10-36-10](https://user-images.githubusercontent.com/13250690/45943301-04e06c00-bfe6-11e8-994e-618482a6123d.png)

**Comment by Evolvee** [comment]
fixed in next hotfix rev
