### ISSUE TITLE
[Spell][Hunter] Avoidance

### ISSUE THREAD

**Issue by AxeCell** [Atlantiss/NetherwingBugtracker#2710]
**Description**: 
Reduces the damage your pet takes from area of effect attacks by an additional 25/50%

**Current behaviour**:
The damage reduction does not apply to nearly as many area of effect attacks as it should, especially noticeable in dungeons.

**Expected behaviour**: 
Should reduce the damage done by all area of effect attacks that doesn't split into single target damage.

**Server Revision**: 
2321

**Comment by mhdemn** [comment]
#2452

**Comment by mhdemn** [comment]
Pasting here 'cause I got #2452 a little too crowded and slightly deviated from initial issue.

> 2339 update
> 
> Been observing it in HCs in every boss with aoe mechanics, every cleaving / aoe-spell provided mob. Both normal and elite mobs, bosses and minibosses (as Torung in Shattered Halls) will annihilate any hunter pet in 1-2 hits max.
> 
> A fair amount of these were also those scarce NPCs around heroics that have their damage numbers a tad bit high, but also those whose damage is adecquate and bearable by tanks are hitting pets for the full amount.

**Comment by Zarant** [comment]
I noticed the same thing in shadow labyrinth, Grandmaster Vorpil's rain of fire in normal mode does full damage on pets. Cabal executioner's whirlwind also does full damage on pets in both heroic and normal modes.

**Comment by Manaci** [comment]
Most likely all fixed as said the in the linked bug tracker
