### ISSUE TITLE
[Hunter Pet] Happiness

### ISSUE THREAD

**Issue by AxeCell** [Atlantiss/NetherwingBugtracker#2711]
**Description**: 
Hunter pets gradually loses happiness as time goes on, and will lose a great deal of happiness once killed.

**Current behaviour**:
Once the pet dies and is desummoned, it will lose double or more of the amount of happiness from death once resummoned.

**Expected behaviour**: 
Should only lose happiness from the death itself, and not a big bonus amount from being desummoned while dead.

**Server Revision**: 
2321

**Comment by mhdemn** [comment]
Video of what OP says [here](https://youtu.be/2CPDkWBdwwo)
good find

**Comment by Wolffenstein** [comment]
Fixed in rev 2427.
