### ISSUE TITLE
[NPC] Captured Protectorate Vanguard

### ISSUE THREAD

**Issue by mhdemn** [Atlantiss/NetherwingBugtracker#2713]
**Description**: [This](https://db.excalibur.ws/?npc=20763) is a questgiver NPC that gives you an escort quest. As many other escort NPCs that spawn in the middle of areas filled with enemies, he's not supposed to be attacked by them until a player picks up the quest and he enters "escorted state".

**Current behaviour**: [Gets gangbanged](https://youtu.be/-LCvoiERHqg) as soon as he spawns (I found him getting rekt by those NPCs and I tried to save him, but I sort of failed.

**Expected behaviour**: Surrounding enemies leave him alone until a player picks up the quest. 

**Server Revision**: 2321

**Comment by Evolvee** [comment]
![image](https://user-images.githubusercontent.com/1942409/48629544-30664e00-e9ba-11e8-83e8-63493455bcbb.png)

**Comment by Tenoutoften** [comment]
According to this [retail video](https://www.youtube.com/watch?v=1j0S9AHfDY0) with time stamps there is a small RP event that goes as follows:

* 11:11:11 Ethereum assassin says: Bring out the gladiator!
* 11:12:55 Etherium Gladiator says: Send it out!
* 11:12:55 Etherium Gladiator yells: Time for the pain!
* 11:12:58 Captured Protectorate Vanguard says: For the Protectorate! DIE EHTEREUM FILTH! 

If you help Captured Protectorate Vanguard clearing out the enemies he will tank you:
* 11:13:11 Captured Protectorate Vanguard says: Thanks, Friend. Will you help me get out of here?
