### ISSUE TITLE
[NPC][Spell] Watoosun's Polluted Essence - Acidic Splash

### ISSUE THREAD

**Issue by manslaughter** [Atlantiss/NetherwingBugtracker#2714]
**Description**: Water elemental in the lake south of Sunspring Post in Nagrand.

**Current behaviour**: He casts "Acidic Splash", a poison dot.

**Expected behaviour**: Not sure if he shouldn't have the ability entirely, but currently it is a quickly stacking debuff that does ~330 dmg every 3 seconds per stack for 30 seconds.  This is a crazy amount of damage for a non-elite.
There are no wowhead comments for the NPC that mention poison or acidic splash at all, and considering its deadliness currently, is very convincing that its either the wrong ability or shouldn't be available for it to use.  It also has a scorpion tail for an icon.
https://www.wowhead.com/npc=18145/watoosuns-polluted-essence#comments

**Server Revision**: 2321

**Comment by The14me** [comment]
https://i.imgur.com/D66dbwG.png

**Comment by Easyfraggy** [comment]
Seems it should do melee damage+30 and then 45 per tick per stack?

**Comment by Wolffenstein** [comment]
Fixed in rev 3404.
