### ISSUE TITLE
[Quest] Arconus the Insatiable

### ISSUE THREAD

**Issue by mhdemn** [Atlantiss/NetherwingBugtracker#2716]
**Description**: When you accept the quest you get a [reflection](https://db.excalibur.ws/?npc=20603) of the [NPC](https://db.excalibur.ws/?npc=20552) that gives you the quest to help you do it.

**Current behaviour**: Both the NPC and the reflection won't correctly phase/evolve/whatever as you progress, that means the NPC will keep calling for you even if he's given you the quest already; the reflection will stick with you after completing the quest and saying stuff to do as you head in the wrong direction (as if you weren't completed yet). The scripting is right though, they say their position-triggered speeches and all with accuracy.

**Expected behaviour**: Reflection goes away upon completion. Questgiver doesn't get it's speech line triggered by your position if you're on his quest.

**Server Revision**: 2321

**Comment by Tereneckla** [comment]
https://www.youtube.com/watch?v=CCm8qNA3bms

Like retail.
