### ISSUE TITLE
[NPC] Gor Grimgut

### ISSUE THREAD

**Issue by manslaughter** [Atlantiss/NetherwingBugtracker#2717]
[//]: # (Enclose links to things related to the bug using http://wowhead.com or any other TBC database.)
[//]: # (You can use screenshot ingame to visual the issue.)
[//]: # (Write your tickets according to the format:)
[//]: # ([Quest][Azuremyst Isle] Red Snapper - Very Tasty!)
[//]: # ([NPC] Magistrix Erona)
[//]: # ([Spell][Mage] Fireball)
[//]: # ([Npc][Drop] Ghostclaw Lynx)
[//]: # ([Web] Armory doesnt work)

**Description**: This is a named ogre that spawns when you try to loot The Thunderspike for the quest of the same name in blade's edge mountains (horde).

**Current behaviour**: He spams a debuff that stuns you called Exhaustion.

**Expected behaviour**: Either he uses this on himself as a drawback to his Furious Rage or he doesn't use it at all.
https://wow.gamepedia.com/Gor_Grimgut

**Server Revision**: 2321

**Comment by Wolffenstein** [comment]
Fixed in rev 3428.
