### ISSUE TITLE
[Quest] The Thunderspike

### ISSUE THREAD

**Issue by manslaughter** [Atlantiss/NetherwingBugtracker#2718]
[//]: # (Enclose links to things related to the bug using http://wowhead.com or any other TBC database.)
[//]: # (You can use screenshot ingame to visual the issue.)
[//]: # (Write your tickets according to the format:)
[//]: # ([Quest][Azuremyst Isle] Red Snapper - Very Tasty!)
[//]: # ([NPC] Magistrix Erona)
[//]: # ([Spell][Mage] Fireball)
[//]: # ([Npc][Drop] Ghostclaw Lynx)
[//]: # ([Web] Armory doesnt work)

**Description**: Horde quest in blade's edge.

**Current behaviour**: When you turn in the quest there is some RP but you can't see/'hear' the NPCs talking.

**Expected behaviour**: There is some RP text.
https://www.wowhead.com/quest=10526/the-thunderspike#comments:id=467732

**Server Revision**: 2321

**Comment by Wolffenstein** [comment]
It's because they're whispering. That's intended.
