### ISSUE TITLE
[Quest] Spirit Calling

### ISSUE THREAD

**Issue by manslaughter** [Atlantiss/NetherwingBugtracker#2719]
[//]: # (Enclose links to things related to the bug using http://wowhead.com or any other TBC database.)
[//]: # (You can use screenshot ingame to visual the issue.)
[//]: # (Write your tickets according to the format:)
[//]: # ([Quest][Azuremyst Isle] Red Snapper - Very Tasty!)
[//]: # ([NPC] Magistrix Erona)
[//]: # ([Spell][Mage] Fireball)
[//]: # ([Npc][Drop] Ghostclaw Lynx)
[//]: # ([Web] Armory doesnt work)

**Description**: Horde quest in blade's edge, Mok'nathal Village.

**Current behaviour**: Lesser Nether Drakes drop the quest macguffins at a % chance.

**Expected behaviour**: Only drops the quest macguffin if you are near the totem provided for the quest.  Not sure about drop rate.

**Server Revision**: 2321

**Comment by aresbrutus** [comment]
Fixed in rev Triton
