### ISSUE TITLE
[Pet pathing][Silvermoon City] Collision with target dummy

### ISSUE THREAD

**Issue by Thugli** [Atlantiss/NetherwingBugtracker#272]
**Description**: 
When pets collide with the noninteractive target dummies in Farstrider's Square in Silvermoon City, they bug out.
**Current behaviour**:
https://clips.twitch.tv/SpoopyKnottyTarsierStinkyCheese
**Expected behaviour**: 
pets should walk around these objects, just like any solid object or "wall".
**Server Revision**:

**Comment by Manaci** [comment]
Fixed
