### ISSUE TITLE
[Item] Ethereum Prison Key - Not implemented until 2.1.0, dropping now in 2.0.3

### ISSUE THREAD

**Issue by mhdemn** [Atlantiss/NetherwingBugtracker#2720]
**Description**: These [keys](https://db.excalibur.ws/?item=29460) are a fundamental source of reputation income for the Consortium faction and were introduced in patch 2.1.0 as you can see in [gamepedia](https://wow.gamepedia.com/Ethereum_Prison_Key).

![image](https://user-images.githubusercontent.com/25901582/48595043-70461a80-e953-11e8-9640-5eb1f32da491.png)

They also form part of a [questchain](https://wow.gamepedia.com/Seek_Out_Ameer).

**Current behaviour**: Keys dropping and are functioning, so you can get the [ID tags](https://db.excalibur.ws/?item=31957) from the mobs that you free from the opened prisons; but not turn them in since qchain isn't implemented.

**Expected behaviour**: Keys weren't implemented until 2.1.0; they have to be removed from loot tables.

**Server Revision**: 2321

**Comment by aresbrutus** [comment]
Fixed in rev `Triton`
