### ISSUE TITLE
[NPC][Blade's Edge Mountains] Bladewing Bloodletter

### ISSUE THREAD

**Issue by maxturtlesc2** [Atlantiss/NetherwingBugtracker#2721]
[//]: # (Enclose links to things related to the bug using http://wowhead.com or any other TBC database.)
[//]: # (You can use screenshot ingame to visual the issue.)
[//]: # (Write your tickets according to the format:)
[//]: # ([Quest][Azuremyst Isle] Red Snapper - Very Tasty!)
[//]: # ([NPC] Magistrix Erona)
[//]: # ([Spell][Mage] Fireball)
[//]: # ([Npc][Drop] Ghostclaw Lynx)
[//]: # ([Web] Armory doesnt work)

**Description**: 
Entry: 21033 Id: 25 GUIDLow: 13503
**Current behaviour**:
Weird behaviors (sometimes flies off and then come back on the ground), weird movement speed.
**Expected behaviour**: 
Normal behaviours.
**Server Revision**:

**Comment by Tereneckla** [comment]
Fixed
