### ISSUE TITLE
[Dungeon] Karazhan Chess Event pawns can't attack diagonally

### ISSUE THREAD

**Issue by Mikik3jr** [Atlantiss/NetherwingBugtracker#2722]
[//]: # (Enclose links to things related to the bug using http://wowhead.com or any other TBC database.)
[//]: # (You can use screenshot ingame to visual the issue.)
[//]: # (Write your tickets according to the format:)
[//]: # ([Quest][Azuremyst Isle] Red Snapper - Very Tasty!)
[//]: # ([NPC] Magistrix Erona)
[//]: # ([Spell][Mage] Fireball)
[//]: # ([Npc][Drop] Ghostclaw Lynx)
[//]: # ([Web] Armory doesnt work)

**Description**: 
When we tried Karazhan yesterday I couldn't attack diagonally with the pawns.

**Current behaviour**:
You can't attack diagonally with pawns.

**Expected behaviour**: 
[This video says otherwise](https://youtu.be/Mf9yLAFXMUA?t=190)

**Server Revision**: 
2321

**Comment by Mewmewww** [comment]
I remember being able to do it as far as i remember.

**Comment by Mikik3jr** [comment]
Well I tried it and I couldn't do it. Since we were there for a short time I couldn't research for a video tho check this. I reported this issue just in case.

**Comment by Wolffenstein** [comment]
The timestamp you linked literally shows the grunt not attacking the diagonally placed conjurer though?

**Comment by Wolffenstein** [comment]
It's only possible if you time the facing change with the melee interval time.
