### ISSUE TITLE
[Misc][NPC]Gan'arg Mekgineer#16940 RP channeling lacks visual beam & end target of their beam always light's up regardless of channeling

### ISSUE THREAD

**Issue by Tenoutoften** [Atlantiss/NetherwingBugtracker#2723]
**Description**: 
[[NPC]Gan'arg Mekgineer#16940](https://www.wowhead.com/npc=16949/ganarg-mekgineer)
* Lacking their blue beam into the field.
* The end of where their channeled beam should be lights up regardless if they are channeling or not. Should be turned off when they stop channeling.
* Some of them are missing until Easy / someone else fixes the spawns, only ID 22,23 & 24 there atm

Can be seen [here, retail](https://youtu.be/wvrtr9nOI7U?t=27)

NW:
![5d5c92646657ccbc7b9ac09cae5136ad](https://user-images.githubusercontent.com/34839199/48619210-0ef66980-e99c-11e8-91a2-509b0857b799.png)
![cde443fa70300643ce45d38f4051ca22](https://user-images.githubusercontent.com/34839199/48619111-b9ba5800-e99b-11e8-8c40-11c2d5e07a4e.png)
![82639d267412ffc675c9e7a5a5a2ced1](https://user-images.githubusercontent.com/34839199/48619055-8c6daa00-e99b-11e8-86e2-5c8622e6814a.png)

**Server Revision**: 
2321

**Comment by Evolvee** [comment]
@aresbrutus @Easyfraggy pls remake the area, i will script it afterwards

**Comment by Evolvee** [comment]
rev ggx
