### ISSUE TITLE
[NPC] Tork is in Ogri'la while he got added in 2.1.0

### ISSUE THREAD

**Issue by mhdemn** [Atlantiss/NetherwingBugtracker#2724]
2321

[Tork](https://db.excalibur.ws/?npc=23347)
![image](https://user-images.githubusercontent.com/25901582/48621412-c17dfa80-e9a3-11e8-8b92-1670a4b0dfc3.png)

[Source](https://wow.gamepedia.com/Tork):

![image](https://user-images.githubusercontent.com/25901582/48621459-df4b5f80-e9a3-11e8-9c24-4e6325ca9831.png)

**Comment by Evolvee** [comment]
rev cc
