### ISSUE TITLE
Glancing Blows

### ISSUE THREAD

**Issue by Erodraeda** [Atlantiss/NetherwingBugtracker#2725]
[//]: # (Enclose links to things related to the bug using http://wowhead.com or any other TBC database.)
[//]: # (You can use screenshot ingame to visual the issue.)
[//]: # (Write your tickets according to the format:)
[//]: # ([Quest][Azuremyst Isle] Red Snapper - Very Tasty!)
[//]: # ([NPC] Magistrix Erona)
[//]: # ([Spell][Mage] Fireball)
[//]: # ([Npc][Drop] Ghostclaw Lynx)
[//]: # ([Web] Armory doesnt work)

**Description**: 
Through my leveling experience since Phase 1, I've seen little to no glancing blows at all, which chance should be high up to 2.1. I've tracked the Combat Log, as well as a couple other addons that record glancing blows.
**Current behaviour**:
The chance of Glancing Blows seems to be way lower than it should be.
![screenshot_691](https://user-images.githubusercontent.com/40346279/48626187-6561a900-e998-11e8-896c-7c4f972e3227.png)

**Expected behaviour**: 
Chance for Glancing blows should be ~10% in targets of the same level,
http://wowwiki.wikia.com/wiki/Glancing_blow
**Server Revision**:

**Comment by aresbrutus** [comment]
@Easyfraggy can you have a look at this one?

**Comment by Easyfraggy** [comment]
I'll test it later - it should indeed be:

glancing blow chance = 10 + mob defense - player weapon skill

**Comment by Easyfraggy** [comment]
So after some testing

While we are at combat formulas - boss parry chance should be significantly higher. Atm is around 6%.

vs lvl 70:
![image](https://user-images.githubusercontent.com/36134067/48650412-498cf000-e9f6-11e8-8b22-eaf0661c0106.png)

vs lvl 73:
![image](https://user-images.githubusercontent.com/36134067/48651093-8c9c9280-e9f9-11e8-9935-54d8f2ad5bd8.png)

**Comment by xmesaj2** [comment]
fixed in 2330
