### ISSUE TITLE
Quest items with weird CD linking

### ISSUE THREAD

**Issue by mhdemn** [Atlantiss/NetherwingBugtracker#2726]
**Description**: If you use this [flare gun](https://db.excalibur.ws/?item=31108) while having [Totem of Spirits](https://db.excalibur.ws/?item=30094) during SMV questing, it will put Totem in a 2 min shared CD. Doesn't happen the other way around, and totem has a 30 seconds CD. They belong to completely different questchains.

Happens the other way around when using this [whistle](https://db.excalibur.ws/?item=30462) (the whistle will trigger its 10 second CD on the flare, again, different questchains).

**Server Revision**: 2321

**Comment by Wolffenstein** [comment]
Blizzlike.
