### ISSUE TITLE
[Dustwallow Marsh] Corrosion Prevention

### ISSUE THREAD

**Issue by Labteth** [Atlantiss/NetherwingBugtracker#2727]
**Description**: 
No quest credit given for dissolving any oozes when using the quest item.

**Current behaviour**:
After the channeled spell "Ooze Channel" the targeted ooze is killed, but no credit is given for the quest.

**Expected behaviour**: 
Credit given for each Ooze killed with the quest item

**Server Revision**:

**Comment by Wolffenstein** [comment]
You need to be energized by one of the engine parts.

**Comment by Labteth** [comment]
Tested again.  No quest credit is given for kills even while energized.

**Comment by Frankenberryberry** [comment]
Still not working :(
