### ISSUE TITLE
[Misc] [Fishing] Mr. Pinchy erroneously dropping from rivers in Terokkar

### ISSUE THREAD

**Issue by Corrozus** [Atlantiss/NetherwingBugtracker#2728]
[//]: # (Enclose links to things related to the bug using http://wowhead.com or any other TBC database.)
[//]: # (You can use screenshot ingame to visual the issue.)
[//]: # (Write your tickets according to the format:)
[//]: # ([Quest][Azuremyst Isle] Red Snapper - Very Tasty!)
[//]: # ([NPC] Magistrix Erona)
[//]: # ([Spell][Mage] Fireball)
[//]: # ([Npc][Drop] Ghostclaw Lynx)
[//]: # ([Web] Armory doesnt work)

**Description**: [Mr. Pinchy](http://db.hellfire-tbc.com/?item=27388) is able to be fished from rivers in Terokkar. He's only supposed to drop from Highland Mixed Schools, as as the 3rd comment from the top explains in [this thread](https://web.archive.org/web/20070701110747/http://www.wowhead.com/?item=27445#z0z) from 2007. He's also dropping too frequently. I caught him twice in 30 minutes.

![pinchynw](https://user-images.githubusercontent.com/44730894/48646408-0f692180-e9e9-11e8-8a78-d9d5e7c779c0.PNG)

**Current behaviour**: Mr. Pinchy can be fished from places he's not supposed to be fished from.

**Expected behaviour**: Should only be available from Highland Mixed Schools, in fly-only areas of Terokkar.

**Server Revision**: 2321

**Comment by Shanghi** [comment]
This should be fixed in revision 2333.

**Comment by Kidtoucher** [comment]
it did not get fixed yet, i got Mr Pinchy from near allerian stronghold in terokkar.
