### ISSUE TITLE
[Quest][Blade's Edge Mountains] A Curse Upon Both of Your Clans!

### ISSUE THREAD

**Issue by maxturtlesc2** [Atlantiss/NetherwingBugtracker#2729]
[//]: # (Enclose links to things related to the bug using http://wowhead.com or any other TBC database.)
[//]: # (You can use screenshot ingame to visual the issue.)
[//]: # (Write your tickets according to the format:)
[//]: # ([Quest][Azuremyst Isle] Red Snapper - Very Tasty!)
[//]: # ([NPC] Magistrix Erona)
[//]: # ([Spell][Mage] Fireball)
[//]: # ([Npc][Drop] Ghostclaw Lynx)
[//]: # ([Web] Armory doesnt work)

**Description**: 

**Current behaviour**:
Spirits doesn't spawn when using the quest item "Wicked Strong Fetish" at the bottom of the towers in the Bloodmaul Outpost (but still consume 1 charge).
**Expected behaviour**: 
Spirits should spawn when using the quest item in those locations.
**Server Revision**:

**Comment by Evolvee** [comment]
Can someone provide more information?

**Comment by aresbrutus** [comment]
https://youtu.be/FBdBv1EnPu0?t=296
https://youtu.be/FBdBv1EnPu0?t=143

Seems you use the item, a spirit spawns and killing that spirit gives you the objective that you cursed that building.

**Comment by maxturtlesc2** [comment]
2 examples at the bottom of the two towers in Bloodmaul Outpost: https://youtu.be/8xw0C7SIf7Q?t=19

The quest item can be used at the bottom of the ramp (1st tower) and on the lower part of the ramp as well (2nd tower).

**Comment by Evolvee** [comment]
rev 2492

**Comment by maxturtlesc2** [comment]
This is not fixed, please reopen.

**Comment by Evolvee** [comment]
![image](https://user-images.githubusercontent.com/1942409/61065076-3d312980-a403-11e9-8a53-1556c9690398.png)

???
