### ISSUE TITLE
DB/Creature: Mana Wyrms in Sunstrider Isle not moving

### ISSUE THREAD

**Issue by Teppic1** [Atlantiss/NetherwingBugtracker#273]
**Description**: 

Mana Wryms should all have random movement.

**Current behaviour**:

Some don't move at all. Can be fixed globally so no need for individual spawn ids.

**Comment by Wolffenstein** [comment]
It can't because it's a core issue which I cannot reproduce

**Comment by Teppic1** [comment]
In TC all that is needed is this

```sql
UPDATE `creature` SET `spawndist`=5, `MovementType`=1 WHERE `id` IN (15274) AND `MovementType`=0;
```

Does the core not used the same random movement system?

**Comment by Wolffenstein** [comment]
Nope. But I think the issue is somewhere deeper outside of random movement generator anyway

**Comment by Tereneckla** [comment]
fixed
