### ISSUE TITLE
[Spell][Warrior] Victory Rush does not proc after killing Silkwing Larva

### ISSUE THREAD

**Issue by maxturtlesc2** [Atlantiss/NetherwingBugtracker#2730]
[//]: # (Enclose links to things related to the bug using http://wowhead.com or any other TBC database.)
[//]: # (You can use screenshot ingame to visual the issue.)
[//]: # (Write your tickets according to the format:)
[//]: # ([Quest][Azuremyst Isle] Red Snapper - Very Tasty!)
[//]: # ([NPC] Magistrix Erona)
[//]: # ([Spell][Mage] Fireball)
[//]: # ([Npc][Drop] Ghostclaw Lynx)
[//]: # ([Web] Armory doesnt work)

**Description**: 

**Current behaviour**:
Victory Rush does not proc after killing Silkwing Larva (Blade's Edge Mountains).
**Expected behaviour**: 
Victory Rush should proc after killing those mobs.
**Server Revision**:

**Comment by Easyfraggy** [comment]
It's because they transform into silkwing instead of dying - unsure if they should actually die and give victory rush etc.

**Comment by Wolffenstein** [comment]
Fixed in rev 3428.
