### ISSUE TITLE
[Quest][Blade's Edge Mountains] Trial and Error

### ISSUE THREAD

**Issue by maxturtlesc2** [Atlantiss/NetherwingBugtracker#2731]
[//]: # (Enclose links to things related to the bug using http://wowhead.com or any other TBC database.)
[//]: # (You can use screenshot ingame to visual the issue.)
[//]: # (Write your tickets according to the format:)
[//]: # ([Quest][Azuremyst Isle] Red Snapper - Very Tasty!)
[//]: # ([NPC] Magistrix Erona)
[//]: # ([Spell][Mage] Fireball)
[//]: # ([Npc][Drop] Ghostclaw Lynx)
[//]: # ([Web] Armory doesnt work)

**Description**: 
https://www.youtube.com/watch?v=X8j5a3NkPN0 (yes I know it's not a tbc period video, but it shouldn't be any different from a tbc one).
**Current behaviour**:
Using the fourth wand on an ogre made him follow me, but didn't turn him friendly. He wasn't attacking me but he was still hostile (I could hit him). Using the first wand turned the mob friendly like it should though.
**Expected behaviour**: 
Wand 1 & 4 are supposed to turn ogres friendly for a set amount of time.
**Server Revision**:

**Comment by devo6969** [comment]
This worked fine on the PTR, both 1st and 4th went friendly
