### ISSUE TITLE
[NPC][Blade's Edge Mountains] Lesser Nether Drake

### ISSUE THREAD

**Issue by maxturtlesc2** [Atlantiss/NetherwingBugtracker#2732]
[//]: # (Enclose links to things related to the bug using http://wowhead.com or any other TBC database.)
[//]: # (You can use screenshot ingame to visual the issue.)
[//]: # (Write your tickets according to the format:)
[//]: # ([Quest][Azuremyst Isle] Red Snapper - Very Tasty!)
[//]: # ([NPC] Magistrix Erona)
[//]: # ([Spell][Mage] Fireball)
[//]: # ([Npc][Drop] Ghostclaw Lynx)
[//]: # ([Web] Armory doesnt work)

**Description**: 
<img src="https://i.imgur.com/CeHN78W.jpg">
**Current behaviour**:
Mob bugged out. Does not react. Message "You are too far away!" in melee range.
**Expected behaviour**: 
Normal npc.
**Server Revision**:

**Comment by Tereneckla** [comment]
Fixed
