### ISSUE TITLE
[NPC][Blade's Edge Moutains] Wyrmcult Poacher

### ISSUE THREAD

**Issue by maxturtlesc2** [Atlantiss/NetherwingBugtracker#2733]
[//]: # (Enclose links to things related to the bug using http://wowhead.com or any other TBC database.)
[//]: # (You can use screenshot ingame to visual the issue.)
[//]: # (Write your tickets according to the format:)
[//]: # ([Quest][Azuremyst Isle] Red Snapper - Very Tasty!)
[//]: # ([NPC] Magistrix Erona)
[//]: # ([Spell][Mage] Fireball)
[//]: # ([Npc][Drop] Ghostclaw Lynx)
[//]: # ([Web] Armory doesnt work)

**Description**: 

**Current behaviour**:
The ability "Net" used by Wyrmcult Poacher lasts for 9sec at the moment. I have no proof that it should not last this long, but I highly doubt it should be the case since it makes any double aggro a certain death situation for any melee-only class (moreover there's no diminishing returns on the ability, so you could theoretically be 'netted' continuously). 
**Expected behaviour**: 
There is no wowhead comments that seem to complain about it, so the duration is probably way lower than 9sec (probably 2-3sec).
**Server Revision**:

**Comment by Wolffenstein** [comment]
Not a bug, check 2.1 patch notes.

**Comment by maxturtlesc2** [comment]
@Wolffenstein The only thing I found in patch 2.1 is:
"Net spell duration changed from 10 to 6 seconds."
BUT it's in the 'Dungeons and Raids' category, so it shouldn't apply in the outside world.
