### ISSUE TITLE
[NPC][Stranglethorn Vale] Bloodsail Warlock

### ISSUE THREAD

**Issue by Kidtoucher** [Atlantiss/NetherwingBugtracker#2734]
![wowscrnshot_111718_122920](https://user-images.githubusercontent.com/45120987/48660686-56492c80-ea66-11e8-897b-5415ef5bfe0c.jpg)

xd

Reproduce:
Just engage in combat, kite the Bloodsail Warlock, let it reset to his initial position.

**Description**: 
Bloodsail Warlock will always summon the pet even though it already exists.
**Current behaviour**:
Bloodsail Warlock will always summon the pet even though it already exists.
**Expected behaviour**: 
Bloodsail Warlock should only summon the pet when it doesn´t exist yet.
**Server Revision**:

**Comment by Manaci** [comment]
Fixed
