### ISSUE TITLE
Princess must die!

### ISSUE THREAD

**Issue by Sador22** [Atlantiss/NetherwingBugtracker#2737]
[//]: # (Enclose links to things related to the bug using http://wowhead.com or any other TBC database.)
[//]: # (You can use screenshot ingame to visual the issue.)
[//]: # (Write your tickets according to the format:)
[//]: # ([Quest][Azuremyst Isle] Red Snapper - Very Tasty!)
[//]: # ([NPC] Magistrix Erona)
[//]: # ([Spell][Mage] Fireball)
[//]: # ([Npc][Drop] Ghostclaw Lynx)
[//]: # ([Web] Armory doesnt work)

**description**: 
The princess does not spawn

**current behavior**:
The princess does not spawn

**what it should be**: 
Princess should be there, thus I could kill her

**Comment by wtRCH** [comment]
She does spawn. Try again later.
