### ISSUE TITLE
[Boss] Grandmaster Vorpil

### ISSUE THREAD

**Issue by Mewmewww** [Atlantiss/NetherwingBugtracker#2738]
[//]: # (Enclose links to things related to the bug using http://wowhead.com or any other TBC database.)
[//]: # (You can use screenshot ingame to visual the issue.)
[//]: # (Write your tickets according to the format:)
[//]: # ([Quest][Azuremyst Isle] Red Snapper - Very Tasty!)
[//]: # ([NPC] Magistrix Erona)
[//]: # ([Spell][Mage] Fireball)
[//]: # ([Npc][Drop] Ghostclaw Lynx)
[//]: # ([Web] Armory doesnt work)

**Description**: 
Used rain of fire
**Current behaviour**:
Rain of fire was casted, then he self-interrupted it.
**Expected behaviour**: 
No self-interupt should be occuring. 
**Server Revision**: 
2321

**Comment by Easyfraggy** [comment]
Seems to happen rarely - no idea why.

**Comment by Tereneckla** [comment]
![image](https://user-images.githubusercontent.com/50233983/72366618-e599b080-36fa-11ea-8825-76e7ee0a01c9.png)
https://youtu.be/N99BJl5zYUM
He interrupted Rain of Fire to cast his Shadow Bolt Volley.

**Comment by Godmatik** [comment]
Was fixed at some point
