### ISSUE TITLE
Food buffs stacking incorrectly

### ISSUE THREAD

**Issue by Manaforall1** [Atlantiss/NetherwingBugtracker#2739]
[//]: # (Enclose links to things related to the bug using http://wowhead.com or any other TBC database.)
[//]: # (You can use screenshot ingame to visual the issue.)
[//]: # (Write your tickets according to the format:)
[//]: # ([Quest][Azuremyst Isle] Red Snapper - Very Tasty!)
[//]: # ([NPC] Magistrix Erona)
[//]: # ([Spell][Mage] Fireball)
[//]: # ([Npc][Drop] Ghostclaw Lynx)
[//]: # ([Web] Armory doesnt work)

**Description**: 
Food Buffs are stacking with each other.
https://imgur.com/a/UFI2b8N
**Current behaviour**:
Currently various 10 minute Foodbuffs stack with each other awswell as the 30 minute foodbuffs.
Examples of these are: Dried Fruit Rations and Nightfin Soup.
**Expected behaviour**: 
Only one foodbuff at a time should be active and it should overwrite already exisiting ones on the target
**Server Revision**: 
2321

**Comment by Easyfraggy** [comment]
https://github.com/Atlantiss/NetherwingBugtracker/issues/2400
