### ISSUE TITLE
Morin Cloudstalker pathing

### ISSUE THREAD

**Issue by wtRCH** [Atlantiss/NetherwingBugtracker#274]
[//]: # (Enclose links to things related to the bug using http://wowhead.com or any other TBC database.)
[//]: # (You can use screenshot ingame to visual the issue.)
[//]: # (Write your tickets according to the format:)
[//]: # ([Quest][Azuremyst Isle] Red Snapper - Very Tasty!)
[//]: # ([NPC] Magistrix Erona)
[//]: # ([Spell][Mage] Fireball)
[//]: # ([Npc][Drop] Ghostclaw Lynx)
[//]: # ([Web] Armory doesnt work)

**Description**: Morin Cloudstalker in the Mulgore isn't patroling on the road. Instead he is staying near the road sign.

**Comment by aresbrutus** [comment]
He does path. It is just that he sometimes stops at the roadsigns before moving on.
