### ISSUE TITLE
[Core] CC/Stun Desync

### ISSUE THREAD

**Issue by nullfoxh** [Atlantiss/NetherwingBugtracker#2740]
Gouge and Kidney Shot are causing desync, while Cheap Shot isn't.
https://streamable.com/kpqau

**Comment by Tenoutoften** [comment]
May I present the newest dance move of our hunter... the [**Double Frontal Moonwalk**](https://www.youtube.com/watch?v=P9cYNp0IF94&feature=youtu.be)

**Comment by Wolffenstein** [comment]
Should be fixed now
