### ISSUE TITLE
Duel Flag Position

### ISSUE THREAD

**Issue by nullfoxh** [Atlantiss/NetherwingBugtracker#2741]
**Description**: Duel Flag should be spawned a bit to the side and not directly between players. 

**Current behaviour**: ![wowscrnshot_111718_105318](https://user-images.githubusercontent.com/12772977/48663776-ab546500-ea9d-11e8-880a-305d26acb681.jpg)

**Expected behaviour**: https://youtu.be/5vW_0HyHexM?t=5

**Comment by toto6** [comment]
Fixed in Server Revision 2325
