### ISSUE TITLE
[Core] Spell delay/Batching goes up to 600ms?

### ISSUE THREAD

**Issue by nullfoxh** [Atlantiss/NetherwingBugtracker#2742]
I know Evolve said batching is not correct atm, but still this feels off:
![batching](https://user-images.githubusercontent.com/12772977/48663827-536a2e00-ea9e-11e8-93fc-ee36ef878143.png)

**Comment by nullfoxh** [comment]
https://cdn.discordapp.com/attachments/281202128503046145/516671115234377754/unknown.png

![image](https://user-images.githubusercontent.com/12772977/49032092-683c7500-f1b4-11e8-9d26-f7dbae91a52c.png)

![image](https://user-images.githubusercontent.com/12772977/49032288-d8e39180-f1b4-11e8-9e64-b0ad6a23c608.png)

From today, this happens constantly,

**Comment by nullfoxh** [comment]
As I'm sure you're aware the delay has been lowered, but it is affecting selfbuffs, which it shouldn't. Picture from today:

![unknown](https://user-images.githubusercontent.com/12772977/50045727-c3b99e80-00a0-11e9-9bbb-6c09ee40cc14.png)

**Comment by SuddenDeath** [comment]
Most likely core lag related, similar results on Sunwell(0-150ms) which has no spell batch system at all.
Warmane TBC seem to be around 0-30ms for self buffs.

The batch time seem to have been reduced significantly, yet am still able to encounter 0-500ms delays at times, most likely because of this core lag(possibly caused by HG/Mangos base?).

**Comment by SuddenDeath** [comment]
Temporary fix should be to reduce spell delay to 0-200ms... Seeing as the core delay adds another 0-200ms.
Currently it's:
0-200ms for self buffs
0-600ms for spells on other players

**IF** changed to 0-200ms, would be:
0-200ms for self buffs
0-400ms for spells on other players.

Seems reasonable until main issue is resolved.

**Comment by Manaci** [comment]
Pepehands
