### ISSUE TITLE
[NPC] Anvilrage Warden#8890 only cast Hooked Net

### ISSUE THREAD

**Issue by Kuumi** [Atlantiss/NetherwingBugtracker#2743]
[//]: # (Enclose links to things related to the bug using http://wowhead.com or any other TBC database.)
[//]: # (You can use screenshot ingame to visual the issue.)
[//]: # (Write your tickets according to the format:)
[//]: # ([Quest][Azuremyst Isle] Red Snapper - Very Tasty!)
[//]: # ([NPC] Magistrix Erona)
[//]: # ([Spell][Mage] Fireball)
[//]: # ([Npc][Drop] Ghostclaw Lynx)
[//]: # ([Web] Armory doesnt work)

**Description**: 
When pulled from range, Anvilrage Warden only cast Hooked Net then stop running toward the player.
**Current behaviour**:
Do not continue their path to run and melee the player, stop moving after casting Hooked Net Ability.
**Expected behaviour**: 
Should continue into melee range and attack
**Server Revision**: 
2321

**Comment by Kuumi** [comment]
Seems to occur with Anvilrage Enforcer outside of BRD as well. stop moving once the player is netted

**Comment by Tereneckla** [comment]
Fixed
