### ISSUE TITLE
[NPC][Zangarmarsh] Marsh Dredger

### ISSUE THREAD

**Issue by eryczek1615** [Atlantiss/NetherwingBugtracker#2744]
**Description**: 
[Marsh Dredger](https://www.wowhead.com/npc=18137/marsh-dredger) uses [Strangling Roots](https://www.wowhead.com/spell=35234/strangling-roots)

**Current behaviour**:
His roots hits for 192 hp
![image](https://user-images.githubusercontent.com/4455568/48665657-e01ee700-eab2-11e8-9a36-24358312c270.png)

**Expected behaviour**: 
According to this [Video](https://youtu.be/yOVqDMtVzL0?t=102) roots should hit for 36hp.

**Server Revision**: 
2321

**Comment by Tenoutoften** [comment]
values from spells are off on videos way later on...

**Comment by wtRCH** [comment]
Please provide with video before Cataclysm Shattering.

**Comment by eryczek1615** [comment]
I found only this [Video](https://youtu.be/WFimrUoYQVU?t=1586) but this is from WarmaneTBC and roots doesn't hit for 36 or 192 but for ~120.

**Comment by Easyfraggy** [comment]
pserver vid is also invalid.

**Comment by Manaci** [comment]
Dead issue and no real proof
