### ISSUE TITLE
[NPC][Zangarmarsh] Lord Klaq

### ISSUE THREAD

**Issue by eryczek1615** [Atlantiss/NetherwingBugtracker#2745]
**Description**: 
[Lord Klaq](https://www.wowhead.com/npc=18282/lord-klaq)

**Current behaviour**:
Lord Klaq has 2 Guardians and he gives reputation and has slow respawn as other NPCs https://imgur.com/aPYQs6q 

**Expected behaviour**: 
Lord Klaq should have 3 guardians and shouldn't give reputation for Sporeggar. [Video](https://youtu.be/R7M16xdnGt4?t=73)
He should have random movement [Video](https://youtu.be/yOVqDMtVzL0?t=84)
He should have fast respawn.

![image](https://user-images.githubusercontent.com/4455568/48665261-b3b39c80-eaab-11e8-9e59-6749f7d8e6a9.png)

![image](https://user-images.githubusercontent.com/4455568/48665928-fa0ef880-eab7-11e8-98d1-742a61a525b8.png)

**Server Revision**: 
2321

**Comment by aresbrutus** [comment]
Fixed in rev `Phoebe`
