### ISSUE TITLE
[NPC][Zangarmarsh]Sporelok

### ISSUE THREAD

**Issue by eryczek1615** [Atlantiss/NetherwingBugtracker#2746]
**Description**: 
[Sporelok](https://www.wowhead.com/npc=18912/sporelok#comments)

**Current behaviour**:
Missing some Sporeloks.

**Expected behaviour**: 
Should have random movement
Sholud be more of them:
 - Around Lord Klaq 72.9 94.4 [Video](https://youtu.be/R7M16xdnGt4?t=73)
https://imgur.com/gm7w7JP
 - In this corridor leading us to Lord Klaq 73.6 95.9  and 72.6 96.9 [Video](https://youtu.be/R7M16xdnGt4?t=105)
https://imgur.com/M2BaNuR 
https://imgur.com/rtvyxjf
 - At the entrance to the cave we don't have any sporelok 74.5 93.1 [Video](https://youtu.be/R7M16xdnGt4?t=57)
https://imgur.com/gblk6Nw
 - In front of the cave should be more Sporeloks for example here 74.5 90.0 should be one more. [Video](https://youtu.be/R7M16xdnGt4?t=51)
https://imgur.com/1Ld90Hk
 - 71.0 97.3 Here should be one [Video](https://youtu.be/yOVqDMtVzL0?t=327) [Video](https://youtu.be/yOVqDMtVzL0?t=158)
https://imgur.com/qHuoTcS
 - 72.7 95.2 There should be some sporeloks [Video](https://youtu.be/yOVqDMtVzL0?t=185)
https://imgur.com/w4KmLps

**Server Revision**: 
2321

**Comment by aresbrutus** [comment]
Fixed in rev `Phoebe`
