### ISSUE TITLE
[Hunter] Auto Shot 

### ISSUE THREAD

**Issue by Ahmpy** [Atlantiss/NetherwingBugtracker#2749]
[//]: # (Enclose links to things related to the bug using http://wowhead.com or any other TBC database.)
[//]: # (You can use screenshot ingame to visual the issue.)
[//]: # (Write your tickets according to the format:)
[//]: # ([Quest][Azuremyst Isle] Red Snapper - Very Tasty!)
[//]: # ([NPC] Magistrix Erona)
[//]: # ([Spell][Mage] Fireball)
[//]: # ([Npc][Drop] Ghostclaw Lynx)
[//]: # ([Web] Armory doesnt work)

**Current behaviour**:  
Some issues with hunter shots getting stuck in a queue after interrupting an auto shot.

This bug was fixed a while back and has recently started to happen once more see: https://github.com/Atlantiss/NetherwingBugtracker/issues/61

Firing a spell during the .5s wind up time for auto shot will cause it to be queue'd and fired immediately after the auto shot. The problem occurs when you never fire the auto shot, but happened to queue a spell: it will make it so that you can not cast the spell until either you complete the auto shot or completely deselect targets (untoggle auto shot)

Ex: https://youtu.be/IFEU-GYfb9s

**Expected behaviour**: It seems that spells fired during this auto shot wind up time are being correctly put into the queue; however, they are becoming reliant on the auto shot finishing to fire. Shots that are queue'd should also be able to complete if the auto shot is canceled.

**Server Revision**:  2321

**Comment by Tenoutoften** [comment]
:thinking:
