### ISSUE TITLE
Logout isn't instant in Cities

### ISSUE THREAD

**Issue by Scylla420** [Atlantiss/NetherwingBugtracker#275]
**Description**: 
Logout takes 20 seconds inside of Ironforge
**Current behaviour**:
[pic~](https://prnt.sc/kxu0yb)
**Expected behaviour**: 
Logout should be instant inside any city or inn.
**Server Revision**: 
2032

**Comment by Peglaa** [comment]
Could it be related to toto's fix about removing rested when leaving inns? It worked fine yesterday

**Comment by Wolffenstein** [comment]
Fixed in rev 2036.
