### ISSUE TITLE
[Hunter][Pet][Spell] Dive and Dash

### ISSUE THREAD

**Issue by Ahmpy** [Atlantiss/NetherwingBugtracker#2750]
[//]: # (Enclose links to things related to the bug using http://wowhead.com or any other TBC database.)
[//]: # (You can use screenshot ingame to visual the issue.)
[//]: # (Write your tickets according to the format:)
[//]: # ([Quest][Azuremyst Isle] Red Snapper - Very Tasty!)
[//]: # ([NPC] Magistrix Erona)
[//]: # ([Spell][Mage] Fireball)
[//]: # ([Npc][Drop] Ghostclaw Lynx)
[//]: # ([Web] Armory doesnt work)

**Current behaviour**: Hunter pet spell dash/dive doesn't effect the pet's move speed when returning to player or stay position (Most noticeable in combat).
Ex: https://youtu.be/GaFstVJMgpY

**Expected behaviour**: Pet's speed should always be increased for the duration of the dash/dive spell.

**Server Revision**: 2321

**Comment by Manaci** [comment]
Fixed
