### ISSUE TITLE
[Quest] Dissension Amongst the Ranks

### ISSUE THREAD

**Issue by mhdemn** [Atlantiss/NetherwingBugtracker#2751]
**Description**: For this [quest](https://db.excalibur.ws/?quest=10769) you just wear the given tabard, getting a blood elf morph through a buff, becoming able to get credit for [Crazed Colossi](https://db.excalibur.ws/?npc=19823) kills.

**Current behaviour**: Just like that quest in Netherstorm with the worms (#2477) you gotta use an item on when you get them under a certain hp threshold, these won't give credit if it's your pet who deals the damage that triggers the script. In the worms case, availability to use the item on; in these giants, the kill credit.

Also, and according to wowhead comments, every player in the group gets credit for a kill as long as they have the [belf-transforming buff](https://db.excalibur.ws/?spell=38224) on them thanks to the [tabard](https://db.excalibur.ws/?item=31279); I got credit from the first one when only my partner had the disguise on.

**Expected behaviour**: Doesn't matter who deals the killing blow, players with disguise on should get credit when kill happens.

**Server Revision**: 2321

**Comment by Manaci** [comment]
Fixed
