### ISSUE TITLE
[Dungeon] Mechanar's bugs thread

### ISSUE THREAD

**Issue by mhdemn** [Atlantiss/NetherwingBugtracker#2752]
**Current behaviour**:
- Pulls at the beginning of the dungeon bug the group in combat all the time. Not sure what's the cause, it forces group to zone out and in again for the 3-4 first pulls, if someone doesn't exit combat somehow healing him will result in contagion.
- The "event" thingy at the final bridge before [Pathaleon](https://db.excalibur.ws/?npc=19220) has a starting pull right after you kill the previous boss, the female blood elf whateverthenameis, and then you progress (or not) through the bridge until Pathaleon. 
Doesn't matter much if you move or not, since the mobs that spawn along the bridge target your group right away regardless of how far they're from you when they spawn. This includes Pathaleon.
Currently though, a few of these pulls do not target you and wait for you in position.

**Server Revision**: 2321

**Comment by Mikik3jr** [comment]
The combat bug is caused by a pet. I think you had a warlock or hunter in your party.

**Comment by mhdemn** [comment]
Yeah, we had myself on my hunter. Thanks for adding that, I was pretty clueless

**Comment by mhdemn** [comment]
2339
After some more HC Mechanars ran I wanna add a few updates / new things:

#### Mob-related Issues
- In the same line of unconsistency that you can feel in a lot of Heroics, in this one the "imba" mob -that I feel has its damage a little higher than it should- is [Bloodwarder Slayer](https://db.excalibur.ws/?npc=21524).
  - Looking at his spells and stats, and taking for example a copy I made of my combat log (Sorry I didn't keep a screenshot) where one of these hit my hunter in full mail gear (around 33% phys damage reduction) for 3.2k white damage + 6.4k Solar Strike damage (white was a crit, Solar wasn't) in the same batch, I'm inclined to think he's way too strong: See the math (excalibur DB as source):

1. His average damage is 2589.5 without any reductions applied, a crit would hit for twice that amount, then reduced by a 1/3 we'd be looking at around 3.4k damage --> Correct.

2. Problem is his Solar Strike (and his Mortal Strike too) gets its damage from thrice the weapon's damage and not the character's damage. I have no idea what damage these guys' weapons have, but even if I'm not correct to assume they have some AP too besides their weapon, numbers don't add up, since 3 times their max damage -2849 · 3- reduced by 33% (from armor) result in 5,698.

Maths aside, it stands out that defense capped tanks in heroic dung BiS gear get melted by these. They also **could be using them with a higher frequency than they should**, but I couldn't keep track of this since you don't live long enough to test it / you're forced to burst them in a CC chain.

#### Combat bug
> The combat bug is caused by a pet. I think you had a warlock or hunter in your party.

Did the beginning of Mecha without my pet up or anyone in the group having one, got bugged in combat multiple times all the same.


#### Events
> * The "event" thingy at the final bridge before [Pathaleon](https://db.excalibur.ws/?npc=19220) has a starting pull right after you kill the previous boss, the female blood elf whateverthenameis, and then you progress (or not) through the bridge until Pathaleon.
>   Doesn't matter much if you move or not, since the mobs that spawn along the bridge target your group right away regardless of how far they're from you when they spawn. This includes Pathaleon.
>   Currently though, a few of these pulls do not target you and wait for you in position.

Seems fixed after 2 correctly working gauntlet-bridge events.


#### Boss-related issues
- When [Gatewatcher Iron-Hand](https://db.excalibur.ws/?npc=21526) correctly emotes and players get the warning "swings his hammer menacingly", but he didn't cast [Jackhammer](https://db.excalibur.ws/?spell=39194) after doing so, not in any of the two times he did the warning during fight. He did this mechanic correctly in normal difficulty in the last Mechanar I did in phase 2.

- During [Pathaleon](https://db.excalibur.ws/?npc=21537)'s fight, the [Nether Wraith](https://db.excalibur.ws/?npc=21535)s he summons will **ignore LoS and cast Arcane Missiles** (continue casting, but also start a new cast through the corners between the bridge and Pathaleon's chamber, a terrain players' vision collide with). If an aoe fear is casted, it's almost a guaranteed wipe.

**Comment by Easyfraggy** [comment]
1 bug per issue please!

**Comment by mhdemn** [comment]
oof
will dissect this post in individual bugs after dinner and close it after then

**Comment by mhdemn** [comment]
Posted individual bugs in threads #2939 #2941 #2942 and #2944

Closing this one
