### ISSUE TITLE
[Item] Costume Scraps [Quest] Meeting at the Blackwing Coven

### ISSUE THREAD

**Issue by maxturtlesc2** [Atlantiss/NetherwingBugtracker#2755]
[//]: # (Enclose links to things related to the bug using http://wowhead.com or any other TBC database.)
[//]: # (You can use screenshot ingame to visual the issue.)
[//]: # (Write your tickets according to the format:)
[//]: # ([Quest][Azuremyst Isle] Red Snapper - Very Tasty!)
[//]: # ([NPC] Magistrix Erona)
[//]: # ([Spell][Mage] Fireball)
[//]: # ([Npc][Drop] Ghostclaw Lynx)
[//]: # ([Web] Armory doesnt work)

**Description**: 
https://www.wowhead.com/item=31121/costume-scraps#comments
https://www.wowhead.com/npc=22099/wyrmcult-provisioner#comments
<img src="https://i.imgur.com/JeHMHxy.png">
**Current behaviour**:
Costume Scraps drops before having the quest that allows to loot it. I had the 5 costume scraps necessary for the quest before even having the forementioned quest.
**Expected behaviour**: 
Costume Scraps should drop only after having "Meeting at the Blackwing Coven". Important note: it should drop even after completing the quest, since there is a vendor inside the cave.
<img src="https://i.imgur.com/hZqs9pl.png">
**Server Revision**:

**Comment by Shanghi** [comment]
This should be fixed in revision 2333.
