### ISSUE TITLE
[Item] Blackwhelp Net [NPC] Wyrmcult Blackwhelp

### ISSUE THREAD

**Issue by maxturtlesc2** [Atlantiss/NetherwingBugtracker#2756]
[//]: # (Enclose links to things related to the bug using http://wowhead.com or any other TBC database.)
[//]: # (You can use screenshot ingame to visual the issue.)
[//]: # (Write your tickets according to the format:)
[//]: # ([Quest][Azuremyst Isle] Red Snapper - Very Tasty!)
[//]: # ([NPC] Magistrix Erona)
[//]: # ([Spell][Mage] Fireball)
[//]: # ([Npc][Drop] Ghostclaw Lynx)
[//]: # ([Web] Armory doesnt work)

**Description**: 
https://www.wowhead.com/item=31129/blackwhelp-net
**Current behaviour**:
Missing the net animation.
**Expected behaviour**: 
Net animation.
**Server Revision**:

**Comment by maxturtlesc2** [comment]
Ok I'm gonna add a bit more intel on this. You have 12 charges of "Blackwhelp Net" to capture 10 Wyrmcult Blackwhelp. After I was done with the 10 (thus the quest was completed) I was still able to use the 2 charges left (which is normal). The 2 charges left actually had the proper animation process (I think): a short cast time (~2sec) and the net animation was properly shown. However since the quest was already completed, the Wyrmcult didn't disappear but stayed stuck (and I was stuck in combat). I was able to kill it without any retaliation. So yeah, some bugs here and there. Quest: "Whelps of the Wyrmcult".

**Comment by Manaci** [comment]
Fixed?
