### ISSUE TITLE
[Misc][Blade's Edge Mountains] Graveyards in 2.1 patch

### ISSUE THREAD

**Issue by maxturtlesc2** [Atlantiss/NetherwingBugtracker#2757]
[//]: # (Enclose links to things related to the bug using http://wowhead.com or any other TBC database.)
[//]: # (You can use screenshot ingame to visual the issue.)
[//]: # (Write your tickets according to the format:)
[//]: # ([Quest][Azuremyst Isle] Red Snapper - Very Tasty!)
[//]: # ([NPC] Magistrix Erona)
[//]: # ([Spell][Mage] Fireball)
[//]: # ([Npc][Drop] Ghostclaw Lynx)
[//]: # ([Web] Armory doesnt work)

**Description**: 
<img src="https://i.imgur.com/CWop83q.png">
**Current behaviour**:
Seems like the current state of the server in terms of graveyard spawn point is currently 2.1+, since you spawn at the Grishnath graveyard if you die in Blackwing Coven.
**Expected behaviour**: 
2.0 graveyard spawn points. There should be 2 graveyards less at 2.0 (the Grishnath one and another).
**Server Revision**:

**Comment by Manaci** [comment]
Irrelevant now

**Comment by Manaci** [comment]
Reopened for future usage
