### ISSUE TITLE
[Mechanar] Gatewatcher Iron-Hand +  Gatewatcher Gyro-Kill - Badge of Justice in normal mode

### ISSUE THREAD

**Issue by adrenochrom** [Atlantiss/NetherwingBugtracker#2759]
**Description**:
https://www.wowhead.com/npc=19218/gatewatcher-gyro-kill
https://www.wowhead.com/npc=19710/gatewatcher-iron-hand

**Current behaviour**:
Both mobs dropped a Badge of Justice in Mechanar normal mode.

**Expected behaviour**: 
Badge of Justice should only drop in heroic mode.

**Server Revision**:

**Comment by Evolvee** [comment]
ups, my bad, sorrry

**Comment by Evolvee** [comment]
will be fixed in revision "Phase 3 v2"
