### ISSUE TITLE
[NPC][Silvermoon Farstrider] Sound Missing

### ISSUE THREAD

**Issue by Thugli** [Atlantiss/NetherwingBugtracker#276]
[//]: # (Enclose links to things related to the bug using http://wowhead.com or any other TBC database.)
[//]: # (You can use screenshot ingame to visual the issue.)
[//]: # (Write your tickets according to the format:)
[//]: # ([Quest][Azuremyst Isle] Red Snapper - Very Tasty!)
[//]: # ([NPC] Magistrix Erona)
[//]: # ([Spell][Mage] Fireball)
[//]: # ([Npc][Drop] Ghostclaw Lynx)
[//]: # ([Web] Armory doesnt work)

**Description**: 
This Silvermoon Farstrider, located @ 82,35 in Farstrider Square in Silvermoon is missing audio related to their behaviour. This NPC's behaviour is to constantly melee attack a target dummy. When the npc strikes the target dummy, sometimes you hear a sound and sometimes you do not.

**Current behaviour**:
When this NPC strikes a target dummy, the sound of them striking the dummy doesn't always go off.
https://clips.twitch.tv/CloudyGracefulPterodactylDendiFace

**Expected behaviour**: 
Every time that NPC strikes the target dummy, it should make a sound.

**Server Revision**:

**Comment by BamboozleNW** [comment]
The "uppercut" makes no sound, though I can obviously find no retail information or video on the sound. https://www.youtube.com/watch?v=v4tr3XVMWA4

**Comment by Wolffenstein** [comment]
Blizzlike.
