### ISSUE TITLE
[NPC][Blade's Edge Mountains] Grishna Falconwing

### ISSUE THREAD

**Issue by maxturtlesc2** [Atlantiss/NetherwingBugtracker#2761]
[//]: # (Enclose links to things related to the bug using http://wowhead.com or any other TBC database.)
[//]: # (You can use screenshot ingame to visual the issue.)
[//]: # (Write your tickets according to the format:)
[//]: # ([Quest][Azuremyst Isle] Red Snapper - Very Tasty!)
[//]: # ([NPC] Magistrix Erona)
[//]: # ([Spell][Mage] Fireball)
[//]: # ([Npc][Drop] Ghostclaw Lynx)
[//]: # ([Web] Armory doesnt work)

**Description**: 
https://www.wowhead.com/spell=35109/grishna-kaliri#used-by-npc
**Current behaviour**:
Grishna Falconwing can summon more than one Grishna Raven (some had 2/3 ravens stacked on each other with them).
**Expected behaviour**: 
Grishna Falconwing should be able to summon only one Grishna Raven.
**Server Revision**:

**Comment by Easyfraggy** [comment]
Possibly due to this area being unfinished by me - will attempt to finish BEM as soon as wolf fixes sniffs on dev.

**Comment by Evolvee** [comment]
no its because of scuffed core

**Comment by Tereneckla** [comment]
Fixed
