### ISSUE TITLE
[NPC] [Darkshore] Blackwood Pathfinder not attacking

### ISSUE THREAD

**Issue by nycheia** [Atlantiss/NetherwingBugtracker#2762]
**Description**: 
Blackwood Pathfinder doesnt AA 

**Current behaviour**:
Doesnt auto attack, only casts Faerie Fire

**Expected behaviour**: 
To Auto Attack

**Server Revision**: 
2321

**Comment by Easyfraggy** [comment]
![image](https://user-images.githubusercontent.com/36134067/48672072-83164600-eb31-11e8-9815-2244d1e44f79.png)

**Comment by Easyfraggy** [comment]
Need recreation steps if you make them bug somehow.

**Comment by nycheia** [comment]
You can recreate it by wanding them.
