### ISSUE TITLE
[Spell][Priest] Prayer of Mending ignores LoS

### ISSUE THREAD

**Issue by nullfoxh** [Atlantiss/NetherwingBugtracker#2765]
**Description**: Prayer of Mending procs/bounces back and forward through pillars, walls and all objects that block line of sight. 

**Current behaviour**: https://streamable.com/ycox1

**Expected behaviour**:  Prayer of Mending should not bounce between players if they are not in line of sight, it should only consume 1 charge of the buff and disappear.

**Proof**:
https://youtu.be/NMkgJmSiMc4?t=1m21s
https://youtu.be/6JjgpeS0YDU?t=4m11s
https://www.youtube.com/watch?v=MdXsUkc7ZA0
At 0:13, 12:12 and 15:40

**Comment by xmesaj2** [comment]
rev 2336

**Comment by xmesaj2** [comment]
will leave it open until more details are known if I should revert it
