### ISSUE TITLE
Stucked mobs

### ISSUE THREAD

**Issue by DragunovUA** [Atlantiss/NetherwingBugtracker#2767]
[//]: # (Enclose links to things related to the bug using http://wowhead.com or any other TBC database.)
[//]: # (You can use screenshot ingame to visual the issue.)
[//]: # (Write your tickets according to the format:)
[//]: # ([Quest][Azuremyst Isle] Red Snapper - Very Tasty!)
[//]: # ([NPC] Magistrix Erona)
[//]: # ([Spell][Mage] Fireball)
[//]: # ([Npc][Drop] Ghostclaw Lynx)
[//]: # ([Web] Armory doesnt work)

**Description**: 
mobs attacking corpse
**Current behaviour**:
stuck on corpse
**Expected behaviour**: 
not
**Server Revision**: 
![wowscrnshot_111818_221911](https://user-images.githubusercontent.com/45152251/48678163-25611880-eb88-11e8-9a25-99ba6434b85f.jpg)

**Comment by DragunovUA** [comment]
they didnt aggro on player btw

**Comment by Easyfraggy** [comment]
Ye probably because they are in evade state - hopefully fixed after next update when the critter fix is live.

**Comment by Tereneckla** [comment]
Fixed
