### ISSUE TITLE
PvP kills 

### ISSUE THREAD

**Issue by Whatsthis880** [Atlantiss/NetherwingBugtracker#2768]
**Description**: 
In a BG (maybe elsewhere also), player do not get the honor and kill when they do not damage a player
**Current behaviour**:
See description
**Expected behaviour**: 
Should give the kill if nearby
**Server Revision**:

**Comment by Azalen** [comment]
Still persisting and very annoying!

**Comment by xmesaj2** [comment]
fixed by wolf, rev 2613
