### ISSUE TITLE
[Class][Druid] Both Bear Form and Dire Bear Form appear on bars

### ISSUE THREAD

**Issue by Kuumi** [Atlantiss/NetherwingBugtracker#2769]
[//]: # (Enclose links to things related to the bug using http://wowhead.com or any other TBC database.)
[//]: # (You can use screenshot ingame to visual the issue.)
[//]: # (Write your tickets according to the format:)
[//]: # ([Quest][Azuremyst Isle] Red Snapper - Very Tasty!)
[//]: # ([NPC] Magistrix Erona)
[//]: # ([Spell][Mage] Fireball)
[//]: # ([Npc][Drop] Ghostclaw Lynx)
[//]: # ([Web] Armory doesnt work)

**Description**: 
after achieving dire bear form, bear form should be removed from UI. 
**Current behaviour**:
Both forms of bear form appear on UI 
![image](https://user-images.githubusercontent.com/44377654/48678284-cf1fb580-eb46-11e8-87a7-8b74df51a29d.png)

**Expected behaviour**: 
Only dire bear form should appear
**Server Revision**: 
2333

**Comment by Wolffenstein** [comment]
It's only due to the beta npc. It won't happen on live.
