### ISSUE TITLE
Mob stuck on player

### ISSUE THREAD

**Issue by Thacen** [Atlantiss/NetherwingBugtracker#2771]
Description:
Mob doesnt lose aggro
Current behaviour:
Shadowlord Deathwail 
![image](https://user-images.githubusercontent.com/34222930/48678431-9ce07900-eb83-11e8-99d0-e294f96d9213.png)
even tho i used vanish it still followed me 
Expected behaviour: 
Losing aggro - not following around
Server Revision:

**Comment by ScottieDOESknow** [comment]
If you aggro in the air then he will follow for a bit yet never attack BUT if you aggro him from the ground at the small courtyard where he circles, he will aggro and attack as intended. 

Mob is target of this quest https://www.wowhead.com/quest=10707/the-atamal-terrace

Supposed to kill the 3 summoners, then few mob waves spawn, then Shadowlord Deathwail finally comes down to fight where you kill for the quest item.

https://i.gyazo.com/f9417ab0c226fd548f993dbfdd1256f5.png

**Comment by The14me** [comment]
Cant recreate in rev 3451.
Can be closed i think.
