### ISSUE TITLE
[Core] Players unsaved to raid instance cannot access other player's raid instances

### ISSUE THREAD

**Issue by sifiuocz** [Atlantiss/NetherwingBugtracker#2774]
**Description**: 
We found this bug when running Kara today.

**Current behaviour**:
I couldn't access my raid group's Kara instance ID when i wasn't saved to any instance ID myself. GMs tried to port me in and it didn't work. 

**Expected behaviour**: 
When I am grouped with someone that is saved to an instance and I am not when I enter the particular instance i should be in the same ID that the leader is in.

**Server Revision**: 
2335

**Comment by sifiuocz** [comment]
Unable to reproduce anymore. Can be closed.

**Comment by Zarant** [comment]
I was unable to reproduce that as well.
