### ISSUE TITLE
[Core] [NPC] Boss movement speed slowed when low HP

### ISSUE THREAD

**Issue by ezzekielfox** [Atlantiss/NetherwingBugtracker#2776]
[//]: # ([Core][NPC] Boss mobs)
[//]: # ([NPC] Pandemonius)

**Description**: Boss mobs (or at the very least Pandemonius) slows movement speed when HP is low.

**Current behaviour**: Movement speed is lowered when HP is below 35%

**Expected behaviour**: All Boss mobs should move at full speed at all times

**Server Revision**:

**Comment by Tereneckla** [comment]
Fixed
