### ISSUE TITLE
[NPC][The Mechanar](Heroic)Tempest Forge Destroyer - Pathing

### ISSUE THREAD

**Issue by Liquidsoap** [Atlantiss/NetherwingBugtracker#2777]
![tempest-forget destroyer](https://user-images.githubusercontent.com/28773914/48680071-473caa00-eb4c-11e8-86e0-306ec7ba4fd6.jpg)
[//]: # (Enclose links to things related to the bug using http://wowhead.com or any other TBC database.)
[//]: # (You can use screenshot ingame to visual the issue.)
[//]: # (Write your tickets according to the format:)
[//]: # ([Quest][Azuremyst Isle] Red Snapper - Very Tasty!)
[//]: # ([NPC] Magistrix Erona)
[//]: # ([Spell][Mage] Fireball)
[//]: # ([Npc][Drop] Ghostclaw Lynx)
[//]: # ([Web] Armory doesnt work)

**Description**: There is a [Tempest-Forge Destroyer] whose pathing is incorrect. It is the [Tempest-Forge Destroyer] that paths from the base of the stairs to the base of the elevator near the Cache of the Legion.
https://www.wowhead.com/npc=19735/tempest-forge-destroyer

**Current behaviour**: The [Tempest-Forge Destroyer] only paths a couple yards behind and in front of the two [Sunseeker Astromage]s that are in front of the elevator.

**Expected behaviour**: The [Tempest-Forge Destroyer] shoulder path from the base of the elevator to the near the base of the left stairway.

**Server Revision**: Phase 3 Beta

**Comment by Easyfraggy** [comment]
He is made from sniffs directly from retail afaik - should be correct. Need better evidence that it is wrong - for example a video.

**Comment by Liquidsoap** [comment]
I've found a video from around the Cataclysm time frame. 
At this first timestamp you can see the mob in question patrolling behind the wall of translucent cubes: [https://youtu.be/mgAvgObSjKM?t=57](url)
At this 2nd timestamp he runs past the mob in question: [https://youtu.be/mgAvgObSjKM?t=156](url)

Here is a 2nd video from a newer expansion of the same mob at the following timestamp: [https://youtu.be/Iakl4ExgD-k?t=43](url)

In both cases you can see the mob patrol quite a bit further out away from the Sunseeker Astromages allowing the Tempest-Forge Destroyer to be pulled independently of the Sunseeker Astromages.

**Comment by Easyfraggy** [comment]
I fixed the links in your comment - if you put brackets it wont work properly on ghub.

**Comment by Wolffenstein** [comment]
Fixed in rev 3428.
