### ISSUE TITLE
Ring enchants do not register properly

### ISSUE THREAD

**Issue by Nicemann1089** [Atlantiss/NetherwingBugtracker#2779]
[//]: # (Enclose links to things related to the bug using http://wowhead.com or any other TBC database.)
[//]: # (You can use screenshot ingame to visual the issue.)
[//]: # (Write your tickets according to the format:)
[//]: # ([Quest][Azuremyst Isle] Red Snapper - Very Tasty!)
[//]: # ([NPC] Magistrix Erona)
[//]: # ([Spell][Mage] Fireball)
[//]: # ([Npc][Drop] Ghostclaw Lynx)
[//]: # ([Web] Armory doesnt work)

https://drive.google.com/file/d/1w_RpdrIczXAD0P5zXYh2ldXrRK26gGDc/view?usp=drivesdk

**Description**: When I enchant both of my rings, in this case +heal especially, it just not register the stats correctly, if I unequip and equip again in a specific order. 

**Current behaviour**: As you can see in the video, I first have 1365 +heal. After unequipping and equipping both rings and equipping only one again, the enchanted stats do not add up to the display and it shows 1345 +heal.

**Expected behaviour**: Enchanted items should register +heal (or stats in general) correctly, no matter in which sequence I equip them. obv

**Server Revision**: 2335

**Comment by Nicemann1089** [comment]
The ring enchants do not stack as well. But I do not know if this is a tbc thing.

**Comment by Nicemann1089** [comment]
The two ring enchants do not stack with each other as well.

**Comment by Nicemann1089** [comment]
https://drive.google.com/file/d/1Wm7EPVegG0DQ22POAZikDk9CdlWbGe4U/view?usp=drivesdk

There you can see, that the second ring enchant does not stack.

**Comment by Tenoutoften** [comment]
This is not working with 2407

**Comment by Tenoutoften** [comment]
The best work around you can do for this is to enchant one of the rings with spellpower instead

**Comment by Redpandaw** [comment]
Why healing+healing doesnt stack? is it tbc or server bug? 
Ok, i enchanted another ring with spell power, but after death i have to re equip rings to make enchants work? what is going on?

**Comment by Notmelody** [comment]
Kind of feels cheated to have raised enchanting to get the ring enchants only to find out it doesnt work :/

**Comment by Redpandaw** [comment]
Are you guys going to fix it?))

**Comment by Easyfraggy** [comment]
I don't know when it will get fixed sorry - there are a lot more pressing issues. Probably not top prio for devs atm!

**Comment by Notmelody** [comment]
Driving me up the wall that i have to un-equip and re-equip my ring for the enchants to re-register during raids, and ontop of that the bloody healing enchants still dont stack.

Please can we look into this somewhat soon?

**Comment by H4Xx0R-PC** [comment]
Please fix this :)

**Comment by Jovzin** [comment]
Hello 
Pls fix I ahve the same issue.
Enchanted both rings with +20 to bonus healing  and one enchant is not counting at all to the total bonus healing.
Thank you

**Comment by bekonja** [comment]
1 bug, 7 months. Just leveled enchanting and i feel cheated.

**Comment by Wolffenstein** [comment]
Fixed in rev 3022.

**Comment by bekonja** [comment]
that bug is totally fixed and absolutely not present again on kz server

**Comment by Tereneckla** [comment]
Only healing power is not stacking.

**Comment by Wolffenstein** [comment]
Fixed in rev 3511.
