### ISSUE TITLE
Shattered Hand Warhound (heroic)

### ISSUE THREAD

**Issue by acedo1234** [Atlantiss/NetherwingBugtracker#2781]
[//]: # (Enclose links to things related to the bug using http://wowhead.com or any other TBC database.)
[//]: # (You can use screenshot ingame to visual the issue.)
[//]: # (Write your tickets according to the format:)
[//]: # ([Quest][Azuremyst Isle] Red Snapper - Very Tasty!)
[//]: # ([NPC] Magistrix Erona)
[//]: # ([Spell][Mage] Fireball)
[//]: # ([Npc][Drop] Ghostclaw Lynx)
[//]: # ([Web] Armory doesnt work)

**Description**: Inflicts Physical damage to an enemy every 3 sec. for 15 sec.

**Current behaviour**: No ability is used.

**Expected behaviour**: Should use on its target.

**Server Revision**:

**Comment by Easyfraggy** [comment]
![image](https://user-images.githubusercontent.com/36134067/48681228-877a4780-eba1-11e8-84c2-cb59cfb0cc97.png)

They do seem to use it - but it has no effect.

**Comment by Easyfraggy** [comment]
Seems to work fine for me
