### ISSUE TITLE
[Core][NPC] Mobs do not appear on screen until you get close to them *new*

### ISSUE THREAD

**Issue by Gerryco** [Atlantiss/NetherwingBugtracker#2782]
**Description**: Having trouble questing in Hellfire Peninsula at the moment because enemies do not show on screen, though they are there, until I actually get into aggro range. Friendly npcs are late to appear as well, though they appear at a slightly greater distance.

**Current behaviour**: See above^

**Expected behaviour**: Not this.

**Server Revision**: idk

**Comment by Gerryco** [comment]
Alliance and Horde.

**Comment by Tankitall** [comment]
I second this.
tested in terrokar forest, it seems as if the draw distance for npc's are set to below 30 yards on the horizontal plain. I tested it vertically by using a flying mount and going above the npc and being stationary and could still see the same npc.
![wowscrnshot_111918_010247](https://user-images.githubusercontent.com/44883325/48681029-c3a8aa80-eb97-11e8-9e0d-1eba6817ac12.jpg)
![wowscrnshot_111918_010301](https://user-images.githubusercontent.com/44883325/48681030-c3a8aa80-eb97-11e8-9434-0e7ce7aea205.jpg)
![wowscrnshot_111918_010348](https://user-images.githubusercontent.com/44883325/48681031-c3a8aa80-eb97-11e8-8b4e-d93a1ac3e8ae.jpg)

**Comment by Easyfraggy** [comment]
It's a temporary thing while we fix an underlying issue causing the client crashes in shattrath.
