### ISSUE TITLE
[Item] Grunt's Waterskin

### ISSUE THREAD

**Issue by Gerryco** [Atlantiss/NetherwingBugtracker#2783]
**Description**: Thrallmar Friendly rep reward water not being sold in the proper quantities. Alliance equivalent 'Footman's Waterskin' is.

**Current behaviour**: Grunt's Waterskin is sold individually for 19s.

**Expected behaviour**: Should be sold as a stack of 5 for 19s as is the Alliance equivalent.

**Server Revision**: idk

**Comment by Kiperr** [comment]
```sql 
UPDATE item_template` SET `BuyCount` = 5 WHERE `entry` = 24006; 
```

**Comment by aresbrutus** [comment]
Fixed in rev `Nariman `thanks to Kiper
