### ISSUE TITLE
[NPC] Bonechewer Orcs Make a B-line

### ISSUE THREAD

**Issue by Gerryco** [Atlantiss/NetherwingBugtracker#2784]
**Description**: Noting what has been reported by Kevintyrell and Shockave, this issue affects not only Scavengers, but also Evokers as far as I know, but differently. The Scavengers will randomly run away, but not to do anything. It's like an early "run away in fear" mechanic, but they actually run, not walk. Scavenger running probably has to do with the "Throw Wrench" mechanic listed by Shockave. Evokers also run, but when they are actually at the low health point for running away in fear.

**Current behaviour**: Mobs RUN, sometimes at the wrong time.

**Expected behaviour**: If running away in fear, they should be walking as normal. Scavengers are probably too eager to use the wrench ability; I assume they're supposed to just stand and throw when you get in pre-melee range of them, and then switch to melee when in close quarters- or maybe at the end of the natural "run away in fear" cycle is when they throw the wrenches instead of returning to melee range of the player.

**Server Revision**: Where do I find this?

**Comment by Tenoutoften** [comment]
This [video](https://youtu.be/TzyBVDZsMHk?t=94) displays that they shouldn't "just stand and throw" before you get "pre-melee range of them" as you assume.

It also shows that they wont randomly run away either: [this pull](https://youtu.be/TzyBVDZsMHk?t=172) in particular shows it all:

* They will use throw if they are ranged, and run into melee.
* When they are melee they will not run away until they are low, then they will do the "attempts to run away in fear!"-mechanic

If they are not suppose to run into melee after this mechanic we need evidence for it...
