### ISSUE TITLE
Total client crash when NPC spawns new adds bug

### ISSUE THREAD

**Issue by Dollywog** [Atlantiss/NetherwingBugtracker#2785]
[//]: # (Enclose links to things related to the bug using http://wowhead.com or any other TBC database.)
[//]: # (You can use screenshot ingame to visual the issue.)
[//]: # (Write your tickets according to the format:)
[//]: # ([Quest][Azuremyst Isle] Red Snapper - Very Tasty!)
[//]: # ([NPC] Magistrix Erona)
[//]: # ([Spell][Mage] Fireball)
[//]: # ([Npc][Drop] Ghostclaw Lynx)
[//]: # ([Web] Armory doesnt work)

**Description**:  First noticed when Questing in Hellfire Peninsula, the Wolfriders patrolling when noticing you summon Wolves next to them and attack you with them.  The instant the Wolf is summoned, it's nameplate reads "Unknown" and the client hard-freezes.  Also, when testing Mechanar Heroic- Pathaleon the Calculator summons "Nether Anomaly" which instead also appear as "Unknown" nameplate and initiate the same crash.

**Current behaviour**:  Crashing client on spawning seemingly new adds by an NPC

**Expected behaviour**: Should not freeze client

**Server Revision**:   Not sure if my client is the issue.  I have deleted full WTF folder and tried, same issue.  Deleted Cache, still an issue.  
Tried my Client with a different TBC server realmlist and flew to the adds in Hellfire - worked fine.

**Comment by Easyfraggy** [comment]
Gonna keep it low prio unless we find others with same issue - for now try installing a different fresh client, like we talked about! =)

**Comment by Dollywog** [comment]
Sure, am downloading as we speak, will update you with what happens.  I noticed on Thursday some people in Hellfire were experiencing the same thing with Wolfriders in Zeth'Gur

**Comment by Dollywog** [comment]
Hey guys just to update you, I downloaded a new client.  No problem with raw client alone.  I added my Addons with no WTF folder, issues started again.  I figured it was an Addon doing this.
By slowly deleting them one by one I think it is either a version of Ace/Lightheaded/GearScoreLite  .

**Comment by Easyfraggy** [comment]
Gearscore xD 

Weird that it would cause crash on spawning mobs - good thing you found the issue - closing since problem has been found! Try getting another version of the addon (altho I would not recommend using gearscore addons in tbc).

**Comment by Dollywog** [comment]
Yeh I just downloaded a giant addon pack and it was in there, I hadn't even noticed it before
