### ISSUE TITLE
[Spell][Rogue] Garrote

### ISSUE THREAD

**Issue by femtaur** [Atlantiss/NetherwingBugtracker#2786]
[//]: # (Enclose links to things related to the bug using http://wowhead.com or any other TBC database.)
[//]: # (You can use screenshot ingame to visual the issue.)
[//]: # (Write your tickets according to the format:)
[//]: # ([Quest][Azuremyst Isle] Red Snapper - Very Tasty!)
[//]: # ([NPC] Magistrix Erona)
[//]: # ([Spell][Mage] Fireball)
[//]: # ([Npc][Drop] Ghostclaw Lynx)
[//]: # ([Web] Armory doesnt work)

**Description**: 
garrote does not produce cp
**Current behaviour**:
garrote does not produce cp but does silence and bleed
**Expected behaviour**: 
garrote should produce cp
**Server Revision**: 
2335

**Comment by ScottieDOESknow** [comment]
working as intended for me

https://i.gyazo.com/47a71cc1e489d2e472a852800657e5d1.mp4

**Comment by The14me** [comment]
@femtaur  please add at least pic or Gif of that.

**Comment by femtaur** [comment]
my bad. it happened to all mobs in kara up to moroes
