### ISSUE TITLE
Char model stuck in standing/combat model

### ISSUE THREAD

**Issue by Gibi-gibii** [Atlantiss/NetherwingBugtracker#2787]
[//]: # (Enclose links to things related to the bug using http://wowhead.com or any other TBC database.)
[//]: # (You can use screenshot ingame to visual the issue.)
[//]: # (Write your tickets according to the format:)
[//]: # ([Quest][Azuremyst Isle] Red Snapper - Very Tasty!)
[//]: # ([NPC] Magistrix Erona)
[//]: # ([Spell][Mage] Fireball)
[//]: # ([Npc][Drop] Ghostclaw Lynx)
[//]: # ([Web] Armory doesnt work)

**Description**: 
https://youtu.be/kPU_W1SZMc4
**Current behaviour**: char model is standing in the "attack" model after combat sometimes

**Expected behaviour**: should return to normal standing motion, eating food/drinking should cause model to sit, currently stays in standing/attack model even though food/drink is being consumed.

**Server Revision**:

**Comment by Jacksn5** [comment]
Happened to me too:
[![Eating Standing Up](http://img.youtube.com/vi/7fG2YUEDxlQ/0.jpg)](https://www.youtube.com/watch?v=7fG2YUEDxlQ "Eating Standing Up")
I'm wondering why the attack animation is on without a target.

**Comment by sadfx** [comment]
Still happening

**Comment by DaedalusMachina007** [comment]
This doesn't happen anymore as of Server Revision 3106.  Was probably fixed earlier but not sure when exactly.
