### ISSUE TITLE
[Core][Spell][Rogue] Cheapshot instantly after stealthing - Mob resetting

### ISSUE THREAD

**Issue by killablink** [Atlantiss/NetherwingBugtracker#2788]
**Description**: If you do an opener (cheapshot) right after stealthing, the mob will reset. 
(Also it feels that the bar switching is just SLIGHTLYYYY too slow because if you try to stealth and cheapshot directly, you will do your ability that is not in your stealth bar (hemo for example)

**Current behaviour**: Mob resets
https://gfycat.com/HelpfulBlandLiger

**Expected behaviour**: Stay in combat

**Server Revision**: 2336

**Comment by killablink** [comment]
https://gfycat.com/GenerousInsecureBengaltiger Yes it works on high level mobs too.

https://gfycat.com/AffectionateAcidicCaterpillar Going into stealth takes slightly too much time, trying to stealth + cheapshot as soon as possible isnt reliable because of it

**Comment by Neophrone** [comment]
I have the same issue, works only with neutral mobs.

**Comment by Wolffenstein** [comment]
Should be fixed now
