### ISSUE TITLE
Johnathon Garrett

### ISSUE THREAD

**Issue by Fuckballsgitgud** [Atlantiss/NetherwingBugtracker#2789]
The NPC in Shadowmoon Village is not there. Also Grifttah in Lower City does not sell the Hulu Doll

**Comment by The14me** [comment]
Johnathon Garrett Added in patch 2.3.0.7561
https://www.wowhead.com/npc=25099/jonathan-garrett

Hula Girl Doll Added in patch 2.3.0
https://www.wowhead.com/item=34249/hula-girl-doll

Will be there when this patch hit.
If u do .server info           will see we are at 2.0.3 patch right now.
