### ISSUE TITLE
Quest: Bounty on Murlocs

### ISSUE THREAD

**Issue by paoea** [Atlantiss/NetherwingBugtracker#279]
[//]: # (Enclose links to things related to the bug using http://wowhead.com or any other TBC database.)
[//]: # (You can use screenshot ingame to visual the issue.)
[//]: # (Write your tickets according to the format:)
[//]: # ([Quest][Azuremyst Isle] Red Snapper - Very Tasty!)
[//]: # ([NPC] Magistrix Erona)
[//]: # ([Spell][Mage] Fireball)
[//]: # ([Npc][Drop] Ghostclaw Lynx)
[//]: # ([Web] Armory doesnt work)

**Description**: 
The Quest "Bounty on Murlocs" should be available at level 7. https://tbc-twinhead.twinstar.cz/?quest=46
**Current behaviour**:
The Quest "Bounty on Murlocs" is currently only at level 10 available.
**Expected behaviour**: 
The Quest "Bounty on Murlocs" should be available at level 7. Together with the other Quests you get from Guard Thomas.
**Server Revision**:

**Comment by aresbrutus** [comment]
https://i.imgur.com/0cmjVHe.png

**Comment by Evolvee** [comment]
The quest is already at level 7 in DB. Are you sure you did all previous requirements? E.g. completing quest https://tbc-twinhead.twinstar.cz/?quest=39 ?

**Comment by paoea** [comment]
https://vanillawowdb.com/?quest=46

You are right! On most private servers you can get it right away, when you actually shouldn't

**Comment by Evolvee** [comment]
yep, Pyralis reworked the entire chaining so expect it to be a lot different than u are used to from other privates

**Comment by Tenoutoften** [comment]
Am I missing something?

[[Quest]Bounty on Murlocs#46](https://www.wowhead.com/quest=46/bounty-on-murlocs) shouldn't have any pre-quest, and it's not part of any chain unlike the quests in the "A fishy Peril"-chain(http://web.archive.org/web/20071229050303/http://thottbot.com:80/q40)

http://web.archive.org/web/20080101101533/http://thottbot.com:80/q46 - doesn't claim the quest is part of a chain, a person reporting informs us that to get the quest you just walk up to [[NPC]Guard Thomas#261](https://www.wowhead.com/npc=261/guard-thomas)
![5f1dc20a9854f5c36d0a1f6041b1d9cf](https://user-images.githubusercontent.com/34839199/49643695-ab99ad80-fa16-11e8-8887-60ced41613a0.png)
![09e5be1c995940e31d9dfb8e0971be53](https://user-images.githubusercontent.com/34839199/49643696-ab99ad80-fa16-11e8-8fda-6d80d2c3f807.png)

**Comment by aresbrutus** [comment]
@Shanghi have a look please.
