### ISSUE TITLE
Hellfire Ramparts. Nazan didn't drop Badge of Justice

### ISSUE THREAD

**Issue by Zebhor** [Atlantiss/NetherwingBugtracker#2790]
[//]: # (Enclose links to things related to the bug using http://wowhead.com or any other TBC database.)
[//]: # (You can use screenshot ingame to visual the issue.)
[//]: # (Write your tickets according to the format:)
[//]: # ([Quest][Azuremyst Isle] Red Snapper - Very Tasty!)
[//]: # ([NPC] Magistrix Erona)
[//]: # ([Spell][Mage] Fireball)
[//]: # ([Npc][Drop] Ghostclaw Lynx)
[//]: # ([Web] Armory doesnt work)

**Description**: 
During the fight with Nazan (dragon boss) they didn't drop Badge of Justice. Chest container contain only items.
**Current behaviour**:
HC Boss didn't drop 1 BoJ
**Expected behaviour**: 
HC Boss should drop 1 BoJ
**Server Revision**: 
2337

**Comment by Shanghi** [comment]
That's added in 2.3.

Patch notes about it: "In addition, on Heroic difficulty the chest now contains a Badge of Justice for each player present."

[2.0.12 comment](https://www.wowhead.com/npc=17536/nazan#comments:id=78280): "and btw no Badge in this fight :*("
