### ISSUE TITLE
Auto Attack Switching 

### ISSUE THREAD

**Issue by nycheia** [Atlantiss/NetherwingBugtracker#2795]
**Description**: 
When you switch target you are still in action to attack the target but no melee swings come off, so you are standing doing nothing but skills like Sinister strike can go off but no normal melee swing goes off until you stop attack and start attack your target again.

https://gfycat.com/IllegalAlienatedLeech

**Current behaviour**:
Doesnt resume auto attack when you switch, unless you stop AA and start it again

**Expected behaviour**: 
Should resume it, without having to start it yourself.

**Server Revision**: 
2336

**Comment by Easyfraggy** [comment]
Because it wont recreate for me. 

https://gfycat.com/AdvancedClumsyAmoeba

**Comment by teddys** [comment]
It is recreating .. you just don't understand the issue otherwise you wouldn't be using abilities on the second target immediately after targeting it. Your gif shows exactly what's wrong. The very first time you switch the target, you are not attacking that target at all until you use eviscerate. If you want to recreate it properly, don't use any abilities, because that's what enables the autoattack.

1) attack target A with autoattack
2) switch target to target B and don't use any abilities
3) see that your autoattack is not going off

**Comment by rjorgensen** [comment]
If you slow down the clip you can see the 1st mob dies and for a short period the rogue has no target. The rogue then gains a new target, the 2nd mob when that mob hits him/her.
I did some testing on the dummies with target switching with <tab> or simple left click and i kept attacking and I kept attacking the new target. I also killed a few mobs pulling two at a time killing one mob and then let the other hit me - which should cause me to target that mob BUT not starting my auto attacks.

**The only bug I see is auto attack not activating after using a special on the 2nd mob.** I was not able to recreate that.

**Comment by Easyfraggy** [comment]
teddys I don't think you watched my gif properly - the devastate is long after i already hit the mob with a MH crit - as you should know the client often bugs out with showing the damage number untill you deal another blow. You can see the HP of the mob drop from the crit long before the numbers appear.

https://gfycat.com/SoreParallelFossa

This i dont use any abilities and just tab target.

Still can't recreate this whatsoever.

**Comment by Easyfraggy** [comment]
If you can recreate it then please post some more videos.

**Comment by Fenvarien1** [comment]
@nycheia could you post your macro on SS please. is there an AA check in it?

**Comment by Dusky1** [comment]
You can recreate simmilar situation by trying to attack mob that have just evaded (idk if its a bug):
1. Attack a mob
2. Run away from mob so he evades and returns back to his previous position
3. While mob is running back you need to start attacking him (Sprint or Shadowstep helps)
4. After the mob returns to his position you will stand still with Attack enabled but you wont attack the mob (you can attack only with skills).

**Comment by Fenvarien1** [comment]
but thats not the shown case. thats some evasion bug you describe. you clearly see that he is attacking 2 mobs wihtout running away or do some edgy stuff.

**Comment by Fenvarien1** [comment]
@Jacksn5 you can clearly see you are hitting with your weapon Autoattack on first swing but MISS. maybe it is the same like this? https://github.com/Atlantiss/NetherwingBugtracker/issues/461

**Comment by Jacksn5** [comment]
It just (Rev 2537) happened to me twice on [Warlord Kalithresh](https://db.excalibur.ws/?npc=20633), Steamvault endboss with the Distillers.
I got last hit with Execute everytime, execute spam automatically retargetted boss, but unfortunately no recording but it and I don't know whether the first attack missed.
I'll gladly help figure this out, seems like it might be easier reproduced on either that Warlord in SV or Mennu the Betrayer with his totems in SP.

**Comment by teddys** [comment]
/startattack macro + getting stunned might somehow be affecting this

**Comment by Crusaderz** [comment]
My first auto-attack bug happened in pvp before i started using macro with /startattack

**Comment by Crusaderz** [comment]
Definitely something with auto-targeting due being attacked. Killed warrior and 1.5 seconds later hunter attacked me appearing as my target, sure enough my AA got bugged.

**Comment by Easyfraggy** [comment]
I finally had it happen to me - it only happens when I spam execute right as the mob dies - not able to reproduce reliably (happens 1/100 times I do this).

**Comment by Tankdiehutte** [comment]
Bug still exists. https://www.youtube.com/watch?v=-FcroN-X8zg 
Autohit working normally after mob dies ( or doubleclicking /using shortcut for autoattackspell).


Same behavior triggered when doing the Quest "Rediscovering your Roots" after using the [Razorthorn Flayer Gland]. As long u got the pet ,your Character isnt attacking while Autohiticon has a bright border but isnt blinking red in the middle. In this case while the Player owns the Ravager pet he cant autohit.

https://youtu.be/E8QL4xUG1rY
Link to Questitem you have to use: https://www.wowhead.com/item=34255/razorthorn-flayer-gland#reward-from-q

I dont know if these bugs have sth in common.

**Comment by Easyfraggy** [comment]
Still can't recreate reliably, if someone can figure out what makes it happen maybe wolf can fix it :/

**Comment by The14me** [comment]
Rev 3460. Its fixed.
Can be closed.
