### ISSUE TITLE
[Karazhan][NPC] Moroes combat bug

### ISSUE THREAD

**Issue by towneh** [Atlantiss/NetherwingBugtracker#2796]
**Description**: 
Moroes encounter does not reset correctly after leashing the boss.

**Current behaviour**:
When you attempt to reset the Moroes encounter by running down the stairs, he leashes and runs back to the platform, but then continuously re-engages any one in the raid that's still present inside the instance before leashing once again. This only stops once everyone is dead or has left the instance. Whilst this happens anyone in the raid gets put in combat when he engages, and then combat drops on the leash.

**Expected behaviour**: 
Moroes should leash when he reaches the stairs and then the encounter should reset properly.

**Server Revision**: 
n/a

**Comment by Easyfraggy** [comment]
https://github.com/Atlantiss/NetherwingBugtracker/issues/2566

**Comment by Wolffenstein** [comment]
Fixed in rev 2339.
