### ISSUE TITLE
Curse of Elements bug. [Spell] [Warlock]

### ISSUE THREAD

**Issue by Neophrone** [Atlantiss/NetherwingBugtracker#2799]
[//]: # (Enclose links to things related to the bug using http://wowhead.com or any other TBC database.)
[//]: # (You can use screenshot ingame to visual the issue.)
[//]: # (Write your tickets according to the format:)
[//]: # ([Quest][Azuremyst Isle] Red Snapper - Very Tasty!)
[//]: # ([NPC] Magistrix Erona)
[//]: # ([Spell][Mage] Fireball)
[//]: # ([Npc][Drop] Ghostclaw Lynx)
[//]: # ([Web] Armory doesnt work)
[//]: # (To find server revision type `.server info` command in the game chat.)
 
**Description**: I've tested warlock's spells, DPS, talents. Found this bug.

**Current behaviour**:
 First I thought it's Shadow bolt bug, but than I noticed that problem not with SB, but with all direct damaging spells, that used against target with Curse of Elements applied on it. Sometimes spells dealing to much damage, Idk the reason, but it happens.
First of all lets do some math with SB damage.
SB rank 11 has 3.0 base cast time, so the base bonus damage from SPD should be:
3.0/3.5= 0.8571. With Shadow and Flame talent it should be 0.8571 * 1.2 (+20% bonus) = 1.028.
Also we have Curse of Elements (+10%) and Demonic Sacrifice(+15%).
With my gear, Fel Armor, flask, oil and food I have 1238 Shadow SPD.
So the final damage should be: 
(607(base SB rank 11 damage) + 1238*1.028) * 1.1 * 1.15=2377dmg, without any procs or another buffs/debuffs.
Sometimes it's dealing correct damage:
![wowscrnshot_111918_124800](https://user-images.githubusercontent.com/43533040/48702550-de137000-ebf9-11e8-9e3d-ecaf8c868763.jpg)
Sometimes that damage:
![wowscrnshot_111918_124744](https://user-images.githubusercontent.com/43533040/48702619-013e1f80-ebfa-11e8-9e79-526d58ac4afc.jpg)
And sometimes even that:
![wowscrnshot_111918_124909](https://user-images.githubusercontent.com/43533040/48702641-0f8c3b80-ebfa-11e8-9bb3-0aa16dfe622b.jpg)
This is happening with other spells, for example Searing Pain:
Normal hit:
![wowscrnshot_111918_130113](https://user-images.githubusercontent.com/43533040/48703140-883fc780-ebfb-11e8-8ab4-57993cd95079.jpg)
OP hit lvl 1:
![wowscrnshot_111918_130119](https://user-images.githubusercontent.com/43533040/48703181-9aba0100-ebfb-11e8-9806-d1eaa0880f48.jpg)
OP hit lvl 2:
![wowscrnshot_111918_130044](https://user-images.githubusercontent.com/43533040/48703209-b32a1b80-ebfb-11e8-9098-b66fb4d70a0f.jpg)
The problem with Curse of the Elements it's happening only with this curse applied to the target, without it, spells dealing damage they should deal.

![wowscrnshot_111918_110706](https://user-images.githubusercontent.com/43533040/48712397-56882a00-ec16-11e8-9110-a3c41785ce78.jpg)
And this is self bufed pre-raid warlock. =)
**Expected behaviour**: 
Correct damage of spells with Curse of Elements at the target.
**Server Revision**: 2336.

**Comment by Neophrone** [comment]
I think the reason is that this Curse decreasing target resistances by 88. And it's working like partial resists but vice versa. I mean if target have resistance to shadow school, u'r spells can do less damage (75% of normal damage, 50% of normal damage, 25% of normal damage or full resist). But resistances mechanic works wrong, looks like with curse target has negative resistances and spells dealing +25% or + 50% of it's damage. 
If 2377 is a normal damage, than 2965/2377 = 1.25 (25% bonus damage) and 3543/2377 = 1.5(50% bonus damage).
Yes, this is the reason for sure. The lowest ammount of ressistance is 0, it can't be negative.

**Comment by Neophrone** [comment]
Also I remember discussion about armor, and negative armor. Are u sure armor can be negative? Imo lowest ammount of armor should be 0, likewise resistances.

**Comment by Easyfraggy** [comment]
Something is definitely odd

If we calculate the possible max from below (0 spellpower no gear) it should be 666 dmg.

No CoE
![image](https://user-images.githubusercontent.com/36134067/48714373-e4faac80-ec12-11e8-9979-a53a37fa2cc9.png)

With CoE
![image](https://user-images.githubusercontent.com/36134067/48714357-dd3b0800-ec12-11e8-9630-f64cd9342675.png)

**Comment by Wolffenstein** [comment]
This has been solved.
