### ISSUE TITLE
Totem of Coo related - needs confirmation

### ISSUE THREAD

**Issue by mikefirefly** [Atlantiss/NetherwingBugtracker#280]
[//]: # (Enclose links to things related to the bug using http://wowhead.com or any other TBC database.)
[//]: # (You can use screenshot ingame to visual the issue.)
[//]: # (Write your tickets according to the format:)
[//]: # ([Quest][Azuremyst Isle] Red Snapper - Very Tasty!)
[//]: # ([NPC] Magistrix Erona)
[//]: # ([Spell][Mage] Fireball)
[//]: # ([Npc][Drop] Ghostclaw Lynx)
[//]: # ([Web] Armory doesnt work)

**Description**: 
Bug related to the buff received after completing the Totem of Coo quest.

**Current behaviour**:
Complete Totem of Coo quest, receive "slow fall" buff (called Ghost of something?). Jump down and get into combat - I attacked a Moongraze Buck. When the buff ends, you are disconnected from the server.

**Expected behaviour**: 
No disconnection.

**Server Revision**:

**Comment by radekhr** [comment]
When my buff expired, I didn't get a DC

**Comment by lynxzor** [comment]
2431 No DC when followed op's steps, so close?
