### ISSUE TITLE
Heroic steamvaults - Warlord Kalithresh spellreflect does no damage to spellcaster

### ISSUE THREAD

**Issue by rasin00** [Atlantiss/NetherwingBugtracker#2800]
[//]: # (Enclose links to things related to the bug using http://wowhead.com or any other TBC database.)
[//]: # (You can use screenshot ingame to visual the issue.)
[//]: # (Write your tickets according to the format:)
[//]: # ([Quest][Azuremyst Isle] Red Snapper - Very Tasty!)
[//]: # ([NPC] Magistrix Erona)
[//]: # ([Spell][Mage] Fireball)
[//]: # ([Npc][Drop] Ghostclaw Lynx)
[//]: # ([Web] Armory doesnt work)
[//]: # (To find server revision type `.server info` command in the game chat.)

**Description**: 

**Current behaviour**:

**Expected behaviour**: 

**Server Revision**:

**Comment by rasin00** [comment]
When he casts spellreflect and you cast a spell and it reflects at you it does no damage to the player

**Comment by maxturtlesc2** [comment]
The same happened to me in Slave Pens, most likely a global problem to the spellreflect.

**Comment by Wolffenstein** [comment]
Should be fixed now

**Comment by Spaztick** [comment]
I believe fire spells are still bugged on spell reflect.

**Comment by itsjojotbh** [comment]
Tested this today 26/12, can confirm it is still bugged at least for holy spells/smite
Some proof: https://www.twitch.tv/videos/354361028
Notice how the shadow word: pain and death reflects damage to me, but smite only does it occasionally

**Comment by Tereneckla** [comment]
Fixed
