### ISSUE TITLE
Soul Leech. [Warlock] [Talent]

### ISSUE THREAD

**Issue by Neophrone** [Atlantiss/NetherwingBugtracker#2801]
[//]: # (Enclose links to things related to the bug using http://wowhead.com or any other TBC database.)
[//]: # (You can use screenshot ingame to visual the issue.)
[//]: # (Write your tickets according to the format:)
[//]: # ([Quest][Azuremyst Isle] Red Snapper - Very Tasty!)
[//]: # ([NPC] Magistrix Erona)
[//]: # ([Spell][Mage] Fireball)
[//]: # ([Npc][Drop] Ghostclaw Lynx)
[//]: # ([Web] Armory doesnt work)
[//]: # (To find server revision type `.server info` command in the game chat.)

**Description**: Incorrect formula for Soul Leech healing.

**Current behaviour**:
Soul Leech should heal warlock 20% of damage done on proc, plus bonus from Fel Armor (26% in my case).
Example:
Searing Pain did 777 damage, Soul Leech heal should be:
(777 * 0.2) * 1.26= 196.
![2](https://user-images.githubusercontent.com/43533040/48707113-17061180-ec07-11e8-9bf7-1d1a445e3e6b.jpg)
Another example:
Shadow Bolt did 4376 damage, Soul Leech heal should be:
(4376 * 0.2) * 1.26= 1103.
![4](https://user-images.githubusercontent.com/43533040/48707857-6b11f580-ec09-11e8-81db-d09681bdd601.jpg)

**Expected behaviour**: 
Looks like Soul Leech heal got bonus from bonus healing, but it shouldn't.
Proofs from old wowhead comments:
https://web.archive.org/web/20071028143756/http://www.wowhead.com:80/?spell=30296#comments
" I'm pretty sure Fel Armor adds 20% do this effect!!
Does healing gear add to soul leech as well?
I'v tested this now:
Fel Armor does add to Soul Leech.
Healing gear does not add to Soul Leech."
**Server Revision**: 2336.

**Comment by Tereneckla** [comment]
Fixed
