### ISSUE TITLE
Mechanar Tempest Forge Destroyer charged fist

### ISSUE THREAD

**Issue by craigsurbrook** [Atlantiss/NetherwingBugtracker#2802]
[//]: # (Enclose links to things related to the bug using http://wowhead.com or any other TBC database.)
[//]: # (You can use screenshot ingame to visual the issue.)
[//]: # (Write your tickets according to the format:)
[//]: # ([Quest][Azuremyst Isle] Red Snapper - Very Tasty!)
[//]: # ([NPC] Magistrix Erona)
[//]: # ([Spell][Mage] Fireball)
[//]: # ([Npc][Drop] Ghostclaw Lynx)
[//]: # ([Web] Armory doesnt work)
[//]: # (To find server revision type `.server info` command in the game chat.)

**Description**: 
When this mob does it's charged fist, you can't interrupt it.

**Current behaviour**:
Charged fist is uninterruptible.

**Expected behaviour**: 
You should be able to interrupt it.

Okay, just to be clear, all of us in the group remembered that you can interrupt it. I'm going to posit that we may be wrong.

**Server Revision**: 
2336

**Comment by The14me** [comment]
https://www.wowhead.com/npc=19735/tempest-forge-destroyer#comments:id=57339

**Comment by Mikik3jr** [comment]
I don't know what is your problem, our rogue/shaman could kick/shock it.

**Comment by craigsurbrook** [comment]
Strange, Sophiett, not one of us could.... I don't know why.

**Comment by craigsurbrook** [comment]
oh and I DID forget to say we were on heroic. Sorry about that.

**Comment by Easyfraggy** [comment]
Just tested on HC - works fine.
