### ISSUE TITLE
[NPC] Can Use Opposing Faction Flightmaster - Shadowmoon Valley

### ISSUE THREAD

**Issue by offcell123** [Atlantiss/NetherwingBugtracker#2803]
[//]: # (Enclose links to things related to the bug using http://wowhead.com or any other TBC database.)
[//]: # (You can use screenshot ingame to visual the issue.)
[//]: # (Write your tickets according to the format:)
[//]: # ([Quest][Azuremyst Isle] Red Snapper - Very Tasty!)
[//]: # ([NPC] Magistrix Erona)
[//]: # ([Spell][Mage] Fireball)
[//]: # ([Npc][Drop] Ghostclaw Lynx)
[//]: # ([Web] Armory doesnt work)
[//]: # (To find server revision type `.server info` command in the game chat.)

**Description**: 
As Alliance, in Shadowmoon Valley I can use the horde flightmaster at Sanctum of the Stars and can attack the alliance flightmaster at the Altar of Sha'tar. In fact, I can attack all alliance NPCs.
**Current behaviour**:
Above
**Expected behaviour**: 
The opposite of this.
**Server Revision**:

**Comment by Shanghi** [comment]
Those are reputation towns, not horde/alliance even though they're blood elves and aliens. Sanctum of the Stars is for the Scryers and Altar of Sha'tar is for the Aldor and they'll like or hate you based on your reputation with them.

Were you able to actually attack and do damage? When I try normal attacks nothing happens and when trying a spell it says "Invalid target." They probably need to be changed to not show as attackable if possible, but that's just a guess!

**Comment by Manaci** [comment]
Fixed
