### ISSUE TITLE
[Spell] Mind control

### ISSUE THREAD

**Issue by nycheia** [Atlantiss/NetherwingBugtracker#2804]
https://prnt.sc/lk8h58

**Description**: 
Mind control does not break when its out of range of you, you can basically keep running away with it until the duration runs out. My record was something like 200 yards away.

**Current behaviour**:
Does not break MC when out of range

**Expected behaviour**: 
Break MC when its slightly further away than cast range IIRC

**Server Revision**: 
2336

**Comment by Dirge123** [comment]
During Open Beta Phase 3 this seems to still  occur (I could only do it to lower level mobs) and on top of that it will not keep you in combat during it's duration

https://imgur.com/a/7raRLO1

**Comment by Wolffenstein** [comment]
Fixed in rev 2399.
