### ISSUE TITLE
[NPC] [DROP] Shattered Hand Executioneer

### ISSUE THREAD

**Issue by MrBomBasTiKs** [Atlantiss/NetherwingBugtracker#2805]
**Description**: 
We rolled on a badge of justice.

**Current behaviour**:
The Shattered Hand Executioneer drop the badge of justice as intented but the whole group rolled on it.
![sans titre](https://user-images.githubusercontent.com/38095594/48711966-e032fa00-ec0c-11e8-8a3b-07a9af8e35f1.png)

**Expected behaviour**: 
Everyone in the group should loot a badge of justice from him.

**Server Revision**: 
AtlantissCoreTBC - Server Revision: 2336

**Comment by ircfelix** [comment]
Still happens.

Furthermore, if you want to loot the white loot from this mob and it is not your turn on looting, you get the message "This item is still being rolled on". If it is not your turn to loot an npc, the white and grey loot it wields, should not be displayed and lootable, until the one who's on the loot turn opens the mob's loot window and doesn't loot a thing.

**Comment by Manaci** [comment]
Fixed I believe
