### ISSUE TITLE
[Spell][Paladin] Blessing of freedom

### ISSUE THREAD

**Issue by MrBomBasTiKs** [Atlantiss/NetherwingBugtracker#2806]
**Description**: 
Blessing of freedom should remove every slows.

**Current behaviour**:
Blessing of freedom didn't remove Blast wave on the second boss of SHH.

**Expected behaviour**: 
It should remove it and we should be immune to the slow of the spell during blessing of freedom.

> - Burning Weapon/Blast Wave: When Warbringer O'mrogg's weapon starts burning, he hits for 1k fire damage in melee, then he will cast 2 consecutive Blast Waves (each of them deals around 2.5k-3.2k damage). This also has a debuff to movement speed.

> - The debuffs can be cleansed and dispelled.

Source : http://wowwiki.wikia.com/wiki/Warbringer_O%27mrogg

**Server Revision**: 
AtlantissCoreTBC - Server Revision: 2336

**Comment by teddys** [comment]
I don't think it's the fault of the spell, but rather of the ability. I remember rogue's improved sprint also not removing blast wave from a certain mob in tk on a different server.

**Comment by devo6969** [comment]
https://www.wowhead.com/npc=16809/warbringer-omrogg#comments
"Druids: It is possible to power shift out of the Thunderclap debuff, but not out of the Blast Wave debuff."
Think it works similar to the effect of "Daze" a druid nor a blessing of freedom can get rid of Daze
