### ISSUE TITLE
[NPC] Kylene - Has cooking recipes that should not be available until 2.1.2

### ISSUE THREAD

**Issue by imchaotic** [Atlantiss/NetherwingBugtracker#2807]
[//]: # (Enclose links to things related to the bug using http://wowhead.com or any other TBC database.)
[//]: # (You can use screenshot ingame to visual the issue.)
[//]: # (Write your tickets according to the format:)
[//]: # ([Quest][Azuremyst Isle] Red Snapper - Very Tasty!)
[//]: # ([NPC] Magistrix Erona)
[//]: # ([Spell][Mage] Fireball)
[//]: # ([Npc][Drop] Ghostclaw Lynx)
[//]: # ([Web] Armory doesnt work)
[//]: # (To find server revision type `.server info` command in the game chat.)

**Description**: 
[NPC] Kylene in the Inn in Shatt can train 3 different cooking recipe's. The most powerful of these is "Fisherman's Feast" which is a 2.1.2 recipe.
http://wowwiki.wikia.com/wiki/Patch_2.1.2

**Current behaviour**:
1: Talking to Kylene
2: Click "I hear you are quite the cook"
3: Be provided 3 different recipes to learn

**Expected behaviour**: 
Kylene should not have the option to learn the 3 recipes until patch 2.1.2.

**Server Revision**: 
2338

**Comment by aresbrutus** [comment]
Kylene won't be giving out cooking recipes after rev `Aterpol`

**Comment by Evolvee** [comment]
why am i assigned?

**Comment by Evolvee** [comment]
rev 2468
