### ISSUE TITLE
Stealth dispellable

### ISSUE THREAD

**Issue by mistermeta** [Atlantiss/NetherwingBugtracker#2809]
[//]: # (Enclose links to things related to the bug using http://wowhead.com or any other TBC database.)
[//]: # (You can use screenshot ingame to visual the issue.)
[//]: # (Write your tickets according to the format:)
[//]: # ([Quest][Azuremyst Isle] Red Snapper - Very Tasty!)
[//]: # ([NPC] Magistrix Erona)
[//]: # ([Spell][Mage] Fireball)
[//]: # ([Npc][Drop] Ghostclaw Lynx)
[//]: # ([Web] Armory doesnt work)
[//]: # (To find server revision type `.server info` command in the game chat.)

**Description**: 
Stealth seems to be dispellable in arena by priests' mass dispel skill.
**Current behaviour**:
Stealth being dispelled by priests' mass dispel skill.
**Expected behaviour**: 
Stealth shouldn't be a dispellable mechanic. Mass dispel on a stealthed person should just remove other removable spells and put both parties in combat.
**Server Revision**:

**Comment by wunsen** [comment]
distract is also working the same way as mass dispel, if I use it on another rogue it removes him from stealth
