### ISSUE TITLE
Bloodmyst Hatchlings in the Lost Fold have no loot

### ISSUE THREAD

**Issue by csjansen** [Atlantiss/NetherwingBugtracker#281]
[//]: # (Enclose links to things related to the bug using http://wowhead.com or any other TBC database.)
[//]: # (You can use screenshot ingame to visual the issue.)
[//]: # (Write your tickets according to the format:)
[//]: # ([Quest][Azuremyst Isle] Red Snapper - Very Tasty!)
[//]: # ([NPC] Magistrix Erona)
[//]: # ([Spell][Mage] Fireball)
[//]: # ([Npc][Drop] Ghostclaw Lynx)
[//]: # ([Web] Armory doesnt work)

**Description**: 
Bloodmyst Hatchlings in the Lost Fold have no loot
**Current behaviour**:
Bloodmyst Hatchlings in the Lost Fold have no loot
**Expected behaviour**: 
Bloodmyst Hatchlings in the Lost Fold should have loot
**Server Revision**:

**Comment by Shanghi** [comment]
This should be fixed in revision 2152.
