### ISSUE TITLE
Stealth interaction not allowed

### ISSUE THREAD

**Issue by mistermeta** [Atlantiss/NetherwingBugtracker#2810]
[//]: # (Enclose links to things related to the bug using http://wowhead.com or any other TBC database.)
[//]: # (You can use screenshot ingame to visual the issue.)
[//]: # (Write your tickets according to the format:)
[//]: # ([Quest][Azuremyst Isle] Red Snapper - Very Tasty!)
[//]: # ([NPC] Magistrix Erona)
[//]: # ([Spell][Mage] Fireball)
[//]: # ([Npc][Drop] Ghostclaw Lynx)
[//]: # ([Web] Armory doesnt work)
[//]: # (To find server revision type `.server info` command in the game chat.)

**Description**: 
Picking up things like WSG flags etc. are being prevented unless you manually leave Stealth.
**Current behaviour**:
The game doesn't drop Stealth and let you pick up the object, instead does nothing. The interaction doesn't happen and the player remains in stealth.
**Expected behaviour**: 
The interaction should happen and Stealth should be removed.
**Server Revision**:

**Comment by 4egito** [comment]
@Tereneckla fixed in rev 3245
**[3245][Core] Misc Fixes
[Core/Battleground]:
- Allow players to start capturing flags/objectives while stealthed or invisible (doing so will however remove stealth/invisibility)**
