### ISSUE TITLE
[NPC] Marksman Bova missing

### ISSUE THREAD

**Issue by DragunovUA** [Atlantiss/NetherwingBugtracker#2811]
[//]: # (Enclose links to things related to the bug using http://wowhead.com or any other TBC database.)
[//]: # (You can use screenshot ingame to visual the issue.)
[//]: # (Write your tickets according to the format:)
[//]: # ([Quest][Azuremyst Isle] Red Snapper - Very Tasty!)
[//]: # ([NPC] Magistrix Erona)
[//]: # ([Spell][Mage] Fireball)
[//]: # ([Npc][Drop] Ghostclaw Lynx)
[//]: # ([Web] Armory doesnt work)
[//]: # (To find server revision type `.server info` command in the game chat.)

**Description**: 
Marksman Bova missing in Aldor, but Archer Delvinar is here.

https://www.wowhead.com/npc=25196/archer-delvinar
https://www.wowhead.com/npc=25195/marksman-bova
**Current behaviour**:
:(
**Expected behaviour**: 
bring it back
**Server Revision**:

**Comment by Easyfraggy** [comment]
Likely invalid report - they don't seem to exist in 2.0

**Comment by mhdemn** [comment]
Reckon reading Kutsal fixed Bova some days ago, thought Delvinar too but he's back:
![image](https://user-images.githubusercontent.com/25901582/48798848-d80ab580-ed05-11e8-9e03-75f7d6f170e0.png)

https://wow.gamepedia.com/Archer_Delvinar
![image](https://user-images.githubusercontent.com/25901582/48798868-e5c03b00-ed05-11e8-9a7f-02f09ed4d29a.png)

**Comment by DragunovUA** [comment]
just let them be

**Comment by aresbrutus** [comment]
Archer Delvinar PTE 2.3 fixed in rev `Aterpol`
