### ISSUE TITLE
Shadowmoon valley netherwing mine

### ISSUE THREAD

**Issue by Lyenlash** [Atlantiss/NetherwingBugtracker#2812]
**Description**: 
There are 0 mobs inside the netherwing mine in shadowmoon valley and there is a weird visual bug where my character disappears for no reason.

**Comment by wtRCH** [comment]
Weird visual bug where your character disappears is client side as far as I remember.

**Comment by Shanghi** [comment]
Most things over there are added in patch 2.1 along with more Netherwing quests.
