### ISSUE TITLE
[NPC][Spell] Highest Threat Target Mind Controlled by Coilfang Soothsayer in Slave Pens

### ISSUE THREAD

**Issue by Jacksn5** [Atlantiss/NetherwingBugtracker#2814]
[//]: # (Enclose links to things related to the bug using http://wowhead.com or any other TBC database.)
[//]: # (You can use screenshot ingame to visual the issue.)
[//]: # (Write your tickets according to the format:)
[//]: # ([Quest][Azuremyst Isle] Red Snapper - Very Tasty!)
[//]: # ([NPC] Magistrix Erona)
[//]: # ([Spell][Mage] Fireball)
[//]: # ([Npc][Drop] Ghostclaw Lynx)
[//]: # ([Web] Armory doesnt work)
[//]: # (To find server revision type `.server info` command in the game chat.)

**Description**: 
Despite being highest on threat, our tank was mind controlled by [Coilfang Soothsayer](https://db.excalibur.ws/?npc=17960) using [Domination](https://db.excalibur.ws/?spell=35280) in Slave Pens, which I'm 100% sure is not supposed to happen. You can see him hit all 3 NPCs with Avenger's Shield in the video 25 seconds in.

[![Top Threat MC](http://img.youtube.com/vi/Ldolu9tbfQo/0.jpg)](https://www.youtube.com/watch?v=Ldolu9tbfQo&t=25 "Top Threat MC")

**Server Revision**: 
2338

**Comment by Drayo** [comment]
I'm not sure how relevant this is, but the MC she uses seems to be the same as the one from The Maker on BF and he is actually able to MC the MT.

>  this biggest issue is if ur unlucky and he choses the Main Tank he will go after the healer

> As of last night he MC'd twice. First he MC'd me (the MT) and the mage poly'd me while the hunter pet tanked the mob.
