### ISSUE TITLE
[Core] Automatically "following" Player After Charging Critter

### ISSUE THREAD

**Issue by Jacksn5** [Atlantiss/NetherwingBugtracker#2816]
[//]: # (Enclose links to things related to the bug using http://wowhead.com or any other TBC database.)
[//]: # (You can use screenshot ingame to visual the issue.)
[//]: # (Write your tickets according to the format:)
[//]: # ([Quest][Azuremyst Isle] Red Snapper - Very Tasty!)
[//]: # ([NPC] Magistrix Erona)
[//]: # ([Spell][Mage] Fireball)
[//]: # ([Npc][Drop] Ghostclaw Lynx)
[//]: # ([Web] Armory doesnt work)
[//]: # (To find server revision type `.server info` command in the game chat.)

**Description**: 
Immediately after charging the frog in front of Quagmirran in Slave Pens, my character automatically moved to our tank despite being too far away to follow, note that with that camera angle this type of movement would be impossible just using keys. See video at 1:35 and beyond.
I use this macro:
`/castsequence Charge, Berserker Stance`

[![Auto-Follow Tank](http://img.youtube.com/vi/Ldolu9tbfQo/0.jpg)](https://www.youtube.com/watch?v=Ldolu9tbfQo&t=95 "Auto-Follow Tank")

**Server Revision**: 
2338

**Comment by Easyfraggy** [comment]
Problem is related to having been mind controlled - https://github.com/Atlantiss/NetherwingBugtracker/issues/2541
