### ISSUE TITLE
Ritual of Summoning - Warlock

### ISSUE THREAD

**Issue by Manaforall1** [Atlantiss/NetherwingBugtracker#2818]
[//]: # (Enclose links to things related to the bug using http://wowhead.com or any other TBC database.)
[//]: # (You can use screenshot ingame to visual the issue.)
[//]: # (Write your tickets according to the format:)
[//]: # ([Quest][Azuremyst Isle] Red Snapper - Very Tasty!)
[//]: # ([NPC] Magistrix Erona)
[//]: # ([Spell][Mage] Fireball)
[//]: # ([Npc][Drop] Ghostclaw Lynx)
[//]: # ([Web] Armory doesnt work)
[//]: # (To find server revision type `.server info` command in the game chat.)

**Description**: 
Currently not able to summon people outside of range. 
**Current behaviour**:
Seems like a fixed bug reappeared that makes you unable to summon people outside of range.
https://github.com/Atlantiss/NetherwingBugtracker/issues/892

**Expected behaviour**: 
Should be able to summon anyone from anywhere.
**Server Revision**: 
2338

**Comment by Wolffenstein** [comment]
Was fixed.
