### ISSUE TITLE
Blacksmithing one-handed weapons are not unique

### ISSUE THREAD

**Issue by sifiuocz** [Atlantiss/NetherwingBugtracker#2820]
**Description**: 
None of the blacksmithing weapons are unique as they should be in patch 2.0

**Current behaviour**:
![wowscrnshot_111918_181802](https://user-images.githubusercontent.com/13140968/48723732-b804c480-ec27-11e8-837f-362305ecb9f6.jpg)

**Expected behaviour**: 

**Server Revision**: 
2338

**Comment by sandreid** [comment]
They should be Mainhand-only.

**Comment by Tankitall** [comment]
Dragonstrike has always been one-hand and not MH-only even since 2.0

**Comment by sandreid** [comment]
> Dragonstrike has always been one-hand and not MH-only even since 2.0

Do you have any source for that information?

**Comment by Easyfraggy** [comment]
They should indeed be mainhand only untill 2.4 - it's a known issue.

**Comment by aresbrutus** [comment]
https://github.com/Atlantiss/AtlantissTBCBT/issues/4351

**Comment by aresbrutus** [comment]
Fixed in rev `Aterpol`
