### ISSUE TITLE
Heroic steamvaults - Warlord Kalithresh

### ISSUE THREAD

**Issue by Manaforall1** [Atlantiss/NetherwingBugtracker#2822]
[//]: # (Enclose links to things related to the bug using http://wowhead.com or any other TBC database.)
[//]: # (You can use screenshot ingame to visual the issue.)
[//]: # (Write your tickets according to the format:)
[//]: # ([Quest][Azuremyst Isle] Red Snapper - Very Tasty!)
[//]: # ([NPC] Magistrix Erona)
[//]: # ([Spell][Mage] Fireball)
[//]: # ([Npc][Drop] Ghostclaw Lynx)
[//]: # ([Web] Armory doesnt work)
[//]: # (To find server revision type `.server info` command in the game chat.)

**Description**: 
Too infrequent occouring of the Naga Distiller event. 
**Current behaviour**:
Warlord Kalithresh is not channeling the Naga Disillers often enough.
 Possible tuning issue with him only doing it 2 times over a  1:45m fight.
**Expected behaviour**: 
Him channeling the Naga Disitllers should provide constant pressure on  dps to targetswitch fast so it happening so few times makes the encounter a lot easier.
**Server Revision**: 
2338

**Comment by Easyfraggy** [comment]
Please provide proof of your claims.

**Comment by Mikik3jr** [comment]
[In this video](https://www.youtube.com/watch?v=CcB3nYErYC4) from 3:37-5:00 (1 min 23s long fight) the boss used the Naga Distiller 3 times.

**Comment by tcberk12** [comment]
VIDEO 1: https://www.youtube.com/watch?v=CcB3nYErYC4 (Feb 2007: Patch 2.0 - unsure if heroic or not) 
Pull: 3:36
First tank: 3:47 (11s)
Second tank: 4:20 (33s)
Third Tank: 4:53 (33s)
Death: 5:00

VIDEO 2: https://www.youtube.com/watch?v=3D-uEg4dwsU (Mar 2007: Patch 2.0 - heroic confirmed)

Pull: 0:11
First tank: 0:20 (10s)
Second tank: 0:54 (33s)
Third tank: 1:28 (33s)
Fourth tank: 2:01 (33s)
Fifth tank…: 2:34 (33s)
SIXTH TANK!: 3:01 (27s)

VIDEO 3: https://www.youtube.com/watch?v=CcB3nYErYC4 (Mar 2008: Patch 2.3 - heroic confirmed)

Pull: 4:57
First tank: 5:11 (14s)
Second tank: 5:59 (48s)
Death: 6:27 (28s)


VIDEO 4: https://www.youtube.com/watch?v=3WirTKzw7aA (May 2008: Patch 2.4 - heroic confirmed)

Pull: 4:29
First tank: 4:41 (12s)
Second tank: 5:28 (47s)
Third tank: 6:17 (49s)

**Comment by Wolffenstein** [comment]
Fixed in rev 2354.
