### ISSUE TITLE
[Dungeon][Blood Furnace]Shadowmoon Technician not linked

### ISSUE THREAD

**Issue by feuerkind** [Atlantiss/NetherwingBugtracker#2824]
**Description**: 
Shadowmoon Technician on the first pack after the first Boss (the one standing on the right) is not linked its pack.
**Current behaviour**:
Look at the target marked with skull.
![wowscrnshot_111918_184823](https://user-images.githubusercontent.com/13179578/48726993-4762a580-ec31-11e8-8f5e-cf279604691c.jpg)
**Expected behaviour**: 
https://youtu.be/BCl8S178ul4?t=466
**Server Revision**: 
2338

**Comment by Evolvee** [comment]
rev 2655
