### ISSUE TITLE
Crusader Procrate (Holy Strength)

### ISSUE THREAD

**Issue by Manaforall1** [Atlantiss/NetherwingBugtracker#2825]
[//]: # (Enclose links to things related to the bug using http://wowhead.com or any other TBC database.)
[//]: # (You can use screenshot ingame to visual the issue.)
[//]: # (Write your tickets according to the format:)
[//]: # ([Quest][Azuremyst Isle] Red Snapper - Very Tasty!)
[//]: # ([NPC] Magistrix Erona)
[//]: # ([Spell][Mage] Fireball)
[//]: # ([Npc][Drop] Ghostclaw Lynx)
[//]: # ([Web] Armory doesnt work)
[//]: # (To find server revision type `.server info` command in the game chat.)

**Description**: 
Currently the Crusader enchant proc Holy Strength rate is too high.
**Current behaviour**:
Currently the Crusader enchant procs Holy Strength too often.
Affer 2 days of testing the procrate seems to zero in on around 40% with no or a very low internal cooldown. Fastest it procced after a proc was 4 seconds.
The data is taken from an addon that gathers the data ingame itself from procs during combat only.
https://imgur.com/a/Q3iJcpc
**Expected behaviour**: 
The sources on the procrate i was able to find indicate it beeing significantly lower but there also seem to be contradictions regarding it.
https://www.wowhead.com/spell=20034/crusader#comments
More research is likely needed.
**Server Revision**: 
2338

**Comment by towneh** [comment]
https://www.wowhead.com/forums&topic=6614#p61000

**Comment by Tereneckla** [comment]
Fixed
