### ISSUE TITLE
[Profession][Alchemy] Recipes

### ISSUE THREAD

**Issue by Unfairy** [Atlantiss/NetherwingBugtracker#2826]
You are able to learn the recipes for:
Elixir of Major Fortitude and Elixir of Draenic Wisdom which are not supposed to be in game in 2.0 and atm its breaking alchemy.
https://cdn.discordapp.com/attachments/500361802228432907/514148765339484169/unknown.png
https://cdn.discordapp.com/attachments/500361802228432907/514148801355841546/unknown.png
https://cdn.discordapp.com/attachments/500361802228432907/514148848806002728/unknown.png
and if you try to make them you get the error of "The item is not found"

**Comment by aresbrutus** [comment]
Fixed in rev `Aterpol`

Make sure to re-learn engineering after the server is updated with this rev.
