### ISSUE TITLE
[Zone]Stratholme south enterance

### ISSUE THREAD

**Issue by Dekirayne** [Atlantiss/NetherwingBugtracker#2827]
[//]: # (Enclose links to things related to the bug using http://wowhead.com or any other TBC database.)
[//]: # (You can use screenshot ingame to visual the issue.)
[//]: # (Write your tickets according to the format:)
[//]: # ([Quest][Azuremyst Isle] Red Snapper - Very Tasty!)
[//]: # ([NPC] Magistrix Erona)
[//]: # ([Spell][Mage] Fireball)
[//]: # ([Npc][Drop] Ghostclaw Lynx)
[//]: # ([Web] Armory doesnt work)
[//]: # (To find server revision type `.server info` command in the game chat.)

**Description**: 
The client freezes when i use that enterance
**Current behaviour**:
Client freezes, i can't even see my character unit frame, and if i relog i get teleported to the lvl 1 starting area.
**Expected behaviour**: 
should not do that
**Server Revision**:

**Comment by Manaci** [comment]
Never had this happen on live
