### ISSUE TITLE
[Mana-Tombs] Ethereal Spellbinder

### ISSUE THREAD

**Issue by Azalen** [Atlantiss/NetherwingBugtracker#2828]
**Description**: 
https://www.wowhead.com/npc=18312/ethereal-spellbinder#abilities:mode=heroic
http://db.hellfire-tbc.com/?npc=18312#abilities

**Current behaviour**:
They cast their "Summon Ethereal Wraith" (spell=32316) while being hard CC'ed (in our case polymorph) making some of the packs almost impossible to clear without wiping and reiteration.
We had to stop our run because of this :(

**Expected behaviour**: 
Hard CC'ed mobs shouldn't cast a summon ability.

Proof: 
>Similar to the Ethereal Sorcerers, the Ethereal Spellbinders will summon an Arcane Wraith after a set amount of time that they aren't crowd controlled. Keep them sheeped or seduced at all times when DPS isn't focused on them.
> Source: https://www.wowhead.com/npc=18312/ethereal-spellbinder#comments

**Server Revision**: 
[2338]

**Comment by Evolvee** [comment]
rev xxd

**Comment by Dollywog** [comment]
Hello, why is this closed? Spellbinders still using 2x Ethereals (should be 1x) even when hard CC

**Comment by Evolvee** [comment]
they wont after revision 2362

check .server info at what revision the server is
