### ISSUE TITLE
[Spell][Draenei] Inspiring/Heroic Presence aura not applying

### ISSUE THREAD

**Issue by Spaztick** [Atlantiss/NetherwingBugtracker#2830]
**Description**: 
Draenei racial perk Inspiring/Heroic Presence aura not applying to players.

**Current behaviour**:
No 1% hit either solo, in party, etc.

**Expected behaviour**: 
Aura shown and 1% hit given.

**Comment by Peglaa** [comment]
the aura doesn't show as a buff but it should still work just fine
