### ISSUE TITLE
Escape from Durnholde. [Quest]

### ISSUE THREAD

**Issue by Neophrone** [Atlantiss/NetherwingBugtracker#2831]
[//]: # (Enclose links to things related to the bug using http://wowhead.com or any other TBC database.)
[//]: # (You can use screenshot ingame to visual the issue.)
[//]: # (Write your tickets according to the format:)
[//]: # ([Quest][Azuremyst Isle] Red Snapper - Very Tasty!)
[//]: # ([NPC] Magistrix Erona)
[//]: # ([Spell][Mage] Fireball)
[//]: # ([Npc][Drop] Ghostclaw Lynx)
[//]: # ([Web] Armory doesnt work)
[//]: # (To find server revision type `.server info` command in the game chat.)

**Description**:
 This is a part of quest chain of rescueing Thrall from Durnhold (BM attune quest chain). Every party member should turn in prev quest before one party member can start this one and it will share automaticaly to the rest of party members.

**Current behaviour**:
After turning in prev quest by all party members, our tank took this part of quest chain [Escape from Durnholde] and quest didn't share to the rest party members.
**Expected behaviour**: 
Should automaticaly share between all party members.
**Server Revision**: 2338.

**Comment by pelekon** [comment]
fixed in 2376
