### ISSUE TITLE
Old Hillsbrad Foothils (heroic).

### ISSUE THREAD

**Issue by Neophrone** [Atlantiss/NetherwingBugtracker#2832]
[//]: # (Enclose links to things related to the bug using http://wowhead.com or any other TBC database.)
[//]: # (You can use screenshot ingame to visual the issue.)
[//]: # (Write your tickets according to the format:)
[//]: # ([Quest][Azuremyst Isle] Red Snapper - Very Tasty!)
[//]: # ([NPC] Magistrix Erona)
[//]: # ([Spell][Mage] Fireball)
[//]: # ([Npc][Drop] Ghostclaw Lynx)
[//]: # ([Web] Armory doesnt work)
[//]: # (To find server revision type `.server info` command in the game chat.)

**Description**:
 We tried OHF heroic, and found that some packs of mobs linked together.

**Current behaviour**:
We were standing in the place like shown on screen and pulled two mobs right down of us, during their way to us it wasn't any mobs around pulled pack, but the mobs that were standing near other barrack pulled too, and mobs that were standing inside the closest barrack pulled too.
![wowscrnshot_111918_230111](https://user-images.githubusercontent.com/43533040/48735101-147bda00-ec50-11e8-88fe-5dad0c640ddd.jpg)

**Expected behaviour**: 
This packs shouldn't be linked together. Btw they pulled without any problems on normal mod.
**Server Revision**: 2338.

**Comment by Easyfraggy** [comment]
I think it's due to specific angle - the mobs in front of the barracks are linked with the mobs behind the barracks - please find some video evidence that they should not be linked.

**Comment by mhdemn** [comment]
We just replicated this and pulled a shitload of mobs, just like OP says.

Tried pulling same guys again without killing any of the involved patrols, but from the pit cubicle at the end of the barracks area. We only pulled the pack with the hunter+wolf, which is def linked to these two. The guys inside the barrack shouldn't be linked though, I think. Will try to find footage

**Comment by Fenvarien1** [comment]
https://youtu.be/ChDS5zrS6MQ?t=228 you can see how X-mark(cross) running out of the building. 4 mobs linked. minutes before its shown that they are marking the ones right at the entrance and the 2 inside of the house.

**Comment by Easyfraggy** [comment]
Seems this is just because you guys pull when a patrol is near the mobs behind the backside of the house - no bug here. just need to clear the dog patrols first.
