### ISSUE TITLE
[NPC] Unliving Caretaker's Debilitating Strike reduces ranged/wand damage

### ISSUE THREAD

**Issue by Spaztick** [Atlantiss/NetherwingBugtracker#2834]
**Description**: 
Unliving Caretakers outside of Karazahn use Debilitating Strike, which reduces only melee damage but is also affecting ranged and wand damage.
![untitled-1](https://user-images.githubusercontent.com/29140342/48735366-cc3bc800-ec0d-11e8-9a72-8bc6600fc570.jpg)

**Comment by Godmatik** [comment]
Rev 4018 - no longer an issue, only affects melee damage
Probably fixed with the recent aura revamp
