### ISSUE TITLE
[Npc] Shade of Aran - Blizzard covers entire room.

### ISSUE THREAD

**Issue by 5f3759** [Atlantiss/NetherwingBugtracker#2835]
**Description**:  The blizzard from Shade of Aran keeps growing larger and larger until it covers the room.

**Expected behaviour**:  The blizzard should stay the same size and circle around the room. The middle should always be safe.
Video of intended behavior: https://www.youtube.com/watch?v=l0DB4lzAttw

**Comment by Azalen** [comment]
https://www.youtube.com/watch?v=gcA6y7sxKcA

**Comment by Wolffenstein** [comment]
Please recheck in rev 2339.
