### ISSUE TITLE
[NPC] Skeletal Usher

### ISSUE THREAD

**Issue by Mikik3jr** [Atlantiss/NetherwingBugtracker#2838]
[//]: # (Enclose links to things related to the bug using http://wowhead.com or any other TBC database.)
[//]: # (You can use screenshot ingame to visual the issue.)
[//]: # (Write your tickets according to the format:)
[//]: # ([Quest][Azuremyst Isle] Red Snapper - Very Tasty!)
[//]: # ([NPC] Magistrix Erona)
[//]: # ([Spell][Mage] Fireball)
[//]: # ([Npc][Drop] Ghostclaw Lynx)
[//]: # ([Web] Armory doesnt work)
[//]: # (To find server revision type `.server info` command in the game chat.)

**Description**: 
[Skeletal Ushers](https://www.wowhead.com/npc=16471/skeletal-usher#comments) in Kara prenerf are immune to CC.

**Current behaviour**:
![wowscrnshot_111918_210724](https://user-images.githubusercontent.com/43505031/48740861-607f4c80-ec59-11e8-933f-a386994da76c.jpg)

**Expected behaviour**: 
They should be immune to CC in 2.0
![image](https://user-images.githubusercontent.com/43505031/48740872-6d03a500-ec59-11e8-83f6-538d4ba85c49.png)

**Server Revision**: 
2338

**Comment by Drayo** [comment]
To add to this (I don't know if they have this right now, it's to avoid raids kiting them pre-nerf):

> Skeletal Ushers appear to be able to pull an enemy towards them under certain circumstances - it may be that this can only happen if no one is in melee range. 

It's [THIS](https://www.wowhead.com/spell=29661/magnetic-pull) spell, it should have an **initial cooldown** of around 5 seconds on pull. After that they should **use it if no one is in melee range** to avoid kiting.

**Comment by Evolvee** [comment]
rev xxd
