### ISSUE TITLE
[The Mechanar HC] Pack bugged out after killing rogue.

### ISSUE THREAD

**Issue by maxturtlesc2** [Atlantiss/NetherwingBugtracker#2839]
[//]: # (Enclose links to things related to the bug using http://wowhead.com or any other TBC database.)
[//]: # (You can use screenshot ingame to visual the issue.)
[//]: # (Write your tickets according to the format:)
[//]: # ([Quest][Azuremyst Isle] Red Snapper - Very Tasty!)
[//]: # ([NPC] Magistrix Erona)
[//]: # ([Spell][Mage] Fireball)
[//]: # ([Npc][Drop] Ghostclaw Lynx)
[//]: # ([Web] Armory doesnt work)
[//]: # (To find server revision type `.server info` command in the game chat.)

**Description**: 
<img src="https://i.imgur.com/8ZIa6bR.png">
Rogue went to sapp star, he got caught and died alone. He then released (so he was outside the dungeon) and he was stuck in combat, and the whole mob pack was acting like he was still near, focusing him from time to time. A vanish from the rogue made the star patrol again and dropped the aggro from the rogue.
**Current behaviour**:
Pack bugged after killing a party member. Rogue stuck in combat outside the dungeon.
**Expected behaviour**: 
Pack acting as expected, Sunseeker Engineer patrolling like normal.
**Server Revision**:

**Comment by Easyfraggy** [comment]
Probably happens with instant-release - maybe needs a zone check on combat?

**Comment by maxturtlesc2** [comment]
Another thing: we wiped on the pack right in front of the elevator. When we came back in, one of our member had aggro the pack we just wiped on even though we barely entered the dungeon (so we couldn't possibly aggro it by normal means).

**Comment by maxturtlesc2** [comment]
<img src="https://i.imgur.com/vEZ3fNo.png">
Another bug: I just died from this mf and here I am, dead but not back at the graveyard, unable to move.

**Comment by devo6969** [comment]
Tried to recreate both of these events, was unable to
