### ISSUE TITLE
[PTE]Design: Relentless Earthstorm Diamond PTE should not be available before patch 2.1

### ISSUE THREAD

**Issue by aresbrutus** [Atlantiss/NetherwingBugtracker#2840]
http://db.hellfire-tbc.com/?item=32412

**Comment by sandreid** [comment]
Relentless Earthstorm Diamond was added in patch 2.1.

Source: https://www.wowhead.com/item=32409/relentless-earthstorm-diamond

**Comment by Fowdall** [comment]
The recipe is currently purchasable from the Consortium Quartermaster in Nagrand. It should not appear in the vendor until at least patch 2.1.

**Comment by Neophrone** [comment]
Honestly it was in game pre-2.1. But in 2.1 they reworked this meta gem. Before 2.1 requirement for activation was 3 red gem, not 2x of all 3 color. I'll find proofs later.

**Comment by aresbrutus** [comment]
http://wowwiki.wikia.com/wiki/Relentless_Earthstorm_Diamond?oldid=639863

> This item is part of the 2.1.0 patch.

https://www.wowhead.com/item=32409/relentless-earthstorm-diamond#comments
2.0.12 comments

https://web.archive.org/web/20070206025045/http://wow.allakhazam.com:80/db/mob.html?wmob=20242

**Comment by Easyfraggy** [comment]
from 2.1 patch notes:

"Jewelcrafters can make two new melee oriented meta gems. One is found randomly as a world drop and the other sold by the reputation vendor."

The comments on 2.0.12 are likely from the PTR.

**Comment by ScottieDOESknow** [comment]
gems that were added added in 2.1

https://gyazo.com/b2409dd168b0d6ab7524fbb1e80164d4
