### ISSUE TITLE
[The Steamvaults Heroic] Mekgineer Steamrigger Add Spawns Abnormal

### ISSUE THREAD

**Issue by Merkmode** [Atlantiss/NetherwingBugtracker#2841]
**Description**: On the encounter the boss is spawning adds at an impossible pace to handle.

**Server Revision**:  2338

**Comment by nycheia** [comment]
TBC Retail video evidence:
https://www.youtube.com/watch?v=t98Q2HZb8bE

**Comment by Merkmode** [comment]
That is drastically slower than what we experienced

**Comment by Merkmode** [comment]
We had over 20 adds spawn within 30 seconds of the encounter

**Comment by Easyfraggy** [comment]
that video is from july 2007 need earlier vid.

**Comment by Merkmode** [comment]
^^^

**Comment by xycz** [comment]
not sure if srs, but here is a vid uploaded 9th of mars 2007 (roughly one and a half month after TBC release), likely the oldest documented video of the kill on youtube at least (heroic).

avoid video if you suffer from claustrophobia, shit's a mess,.

https://www.youtube.com/watch?v=OdWQYk6ZK-4

**Comment by Merkmode** [comment]
Yeah definitely still not spawning as many as we had they were coming in groups of 3 or 5 constantly within 30 seconds we had like 10 adds up at a time and that was with focusing all our dmg on them was absolutely impossible to keep up with and considering that we are in full Pre BiS shouldnt be an issue

**Comment by Goron123** [comment]
We found that at each interval - 75% > 50% > 25% - it spawns 6x adds instead of 3x and the 1x add per 7 seconds felt like 1x add every 3 seconds...

Also, the adds spawn at the boss - not in the room... that may be accurate though and other TBC projects may have done it incorrectly.

**Comment by mhdemn** [comment]
Wanna add that after wiping, the 3 initial adds won't respawn, I think they should? -I can't find evidence backing this up directly, but comments and guides suggest it should be the case and consider no scenario where you can get rid of them-

PS At least they didn't respawn after any of our wipes.

**Comment by Drayo** [comment]
I do want to mention here that while we did kill him, the fight is very hard in it's current state, we had a Prot Pally, Mage, Warlock and a Resto Shaman. Even with Bloodlust, full consumes and heroic gear, we had trouble killing this guy. 

It does seems like the adds spawn at an extreme rate, even with perma AOE we did not have one second without at least 2 adds. From my experience, when this boss is overtuned, players will simply start using super lame kiting/LOS strategies, might be better to reevaluate the spawn rate on this.

**Comment by The14me** [comment]
https://www.youtube.com/watch?v=OdWQYk6ZK-4
may need a little reduce reduce of the spawn rate of the add's
From the other hand...  https://www.wowhead.com/npc=17796/mekgineer-steamrigger#comments:id=38783

**Comment by Fenvarien1** [comment]
this comment is on the same patch as the one commented under it: "This fight is easy on Heroic. 
It's the same as the "Normal" fight, but instead of him spawning 3 at a time, he just spawns one every 7 seconds or so? Have your ranged nuke the 1 he spawns, then just get back on the boss. "

we had atleast double the adds if not more than in the video.(and we killed some not feared like they do)

**Comment by Fenvarien1** [comment]
We testet our version today.

### Our Version:

> > - [add spawnrate](https://youtu.be/Tn3LdDE_zJk?t=43) 1 add every 7 seconds
> 
> > - [75% trigger](https://youtu.be/Tn3LdDE_zJk?t=119) 4 add spawn
> > - [50% trigger](https://youtu.be/Tn3LdDE_zJk?t=200) 3 add spawn
> > - [25% trigger](https://youtu.be/Tn3LdDE_zJk?t=282) 3 add spawn
> 
> > - [5 add spawn working](https://youtu.be/Tn3LdDE_zJk?t=426)
> > - [healed up by gnomes and again under 75% - no extra 3-5 spawn(working)](https://youtu.be/Tn3LdDE_zJk?t=167) we did the same for 50% and 25%


### How it should be:

> > > [Screenshot 10.02.2007 - wowwiki Mekgineer Steamrigger](https://web.archive.org/web/20070210020308/http://www.wowwiki.com:80/Mekgineer_Steamrigger)
> > > - Every 25% health at 75%, 50% and 25% health he shouts "Tune 'em up good boys!", three to five Steamrigger Mechanics appear
> > > - On heroic mode, Steamrigger's attacks are identical to normal mode, however, the gnomes that previously only spawned during the "Attack of the Gnomes" phase of the fight will now spawn steadily throughout the encounter, at a rate of around 1 per 30 seconds, in addition to the normal 3-spawn during the "Tune 'em good boys!" phase
> > 
> >- this guide stays the same until [06.06.2007](https://web.archive.org/web/20070606114459/http://www.wowwiki.com:80/Mekgineer_Steamrigger)
> >- on [04.07.2007](https://web.archive.org/web/20070704223555/http://www.wowwiki.com:80/Mekgineer_Steamrigger) it kinda **copy&pasta** the [comment by casey](https://www.wowhead.com/npc=17796/mekgineer-steamrigger#comments:id=43112) from wowhead: 
> >_"Steamrigger is almost identical to normal mode, except that an extra gnome appears every 7 seconds or so"_ - i like the adaptation of **"or so"**
> > 
> 
> > [27.02.2007 wowhead comment  by casey](https://www.wowhead.com/npc=17796/mekgineer-steamrigger#comments:id=43112)
> > "**but instead of him spawning 3 at a time**, he just spawns one every 7 seconds or so"
> > i like to remind here "**instead of spawning 3**"
> 
> the only proof of (3add spawn only + 1 add every 7sec) is the from wowwiki MONTH later where they changed **the original 10.02.2007 version** to the copy&pasta version but with 3 add trigger only...or so
> there is a huge gap between 7sec and 30sec. as of all videos i have seen there are slower spawnrates. maybe not 30seconds but no 7sec spawn either.
> 
> > a Video from **11.07.2007**(reminder:04.07.2007 screenshot of wowwiki guide" changed it to 7sec spawnrate)
> > - [20sec spawnrate](https://youtu.be/t98Q2HZb8bE?t=20) first at 0:22 2nd at 0:42 - if it were 7sec it couldn't spawn round 42
> 
> i didn't found a single proof of 75%/50%/25% 3-5add spawn with 7 seconds add spawnrate combined.

 

it's up to you which version we stick to but our version is in my opinion wrong. please consider the informations and make a adaptation.

**Comment by Manaci** [comment]
Fixed

**Comment by raethkcj** [comment]
NOT fixed rev 3519 @Wolffenstein
