### ISSUE TITLE
Attumen the Huntsman

### ISSUE THREAD

**Issue by justicex123** [Atlantiss/NetherwingBugtracker#2842]
[//]: # (Enclose links to things related to the bug using http://wowhead.com or any other TBC database.)
[//]: # (You can use screenshot ingame to visual the issue.)
[//]: # (Write your tickets according to the format:)
[//]: # ([Quest][Azuremyst Isle] Red Snapper - Very Tasty!)
[//]: # ([NPC] Magistrix Erona)
[//]: # ([Spell][Mage] Fireball)
[//]: # ([Npc][Drop] Ghostclaw Lynx)
[//]: # ([Web] Armory doesnt work)
[//]: # (To find server revision type `.server info` command in the game chat.)

**Description**: 
Attumen the Huntsman respawned in Karazhan
**Current behaviour**:
Attumen the Huntsman respawned after we killed him
![wowscrnshot_112018_024727](https://user-images.githubusercontent.com/44686384/48742138-b3afca00-ec6e-11e8-9b80-9c8b1a71d121.jpg)

**Expected behaviour**: 
He should not respawn when we kill him
**Server Revision**: 
2338

**Comment by Mvtsvraev** [comment]
Actually horseman does not throw in the air when he charges.

**Comment by Wolffenstein** [comment]
Fixed in rev 2339.
