### ISSUE TITLE
[NPC] Attumen the Huntsman

### ISSUE THREAD

**Issue by nycheia** [Atlantiss/NetherwingBugtracker#2843]
**Description**: 
This issue holds multiply bugs, and one that i am unsure of.

Firstly, the spawning of the boss is supposed to appear to the left of the boss. Not on top of the boss. 
Proof: https://youtu.be/bZZW_xyLp9U?t=19
Current attumen: https://clips.twitch.tv/SpicyCarefulOcelotOMGScoots

Second issue, when charging in p3 it is supposed to drop aggro right after charging, and not swing several times at the target it charges.
Proof: https://youtu.be/bZZW_xyLp9U?t=147
Current attumen: https://clips.twitch.tv/DifficultCaringKimchiMikeHogu

Unsure third issue, getting hit by hit cleave in the back (chaining cleave? couldnt find proof for it that its not supposed to work like that, just looked very iffy)
Current attumen: https://clips.twitch.tv/MoldyRelentlessDelicataBibleThump

**Server Revision**: 
2338

**Comment by Manaci** [comment]
Fixed, Fixed, pre-nerf and fixed
