### ISSUE TITLE
[Karazhan] Rain of Fire spell on Human Conjurer cannot be targetted properly

### ISSUE THREAD

**Issue by Fowdall** [Atlantiss/NetherwingBugtracker#2845]
[//]: # (Enclose links to things related to the bug using http://wowhead.com or any other TBC database.)
[//]: # (You can use screenshot ingame to visual the issue.)
[//]: # (Write your tickets according to the format:)
[//]: # ([Quest][Azuremyst Isle] Red Snapper - Very Tasty!)
[//]: # ([NPC] Magistrix Erona)
[//]: # ([Spell][Mage] Fireball)
[//]: # ([Npc][Drop] Ghostclaw Lynx)
[//]: # ([Web] Armory doesnt work)
[//]: # (To find server revision type `.server info` command in the game chat.)

**Description**: The Rain of Fire spell on the Human conjurer is untargetable.

**Current behaviour**: The Rain of Fire spell appears on top of the Human Conjurer upon casting.

**Expected behaviour**: The Rain of Fire spell should be targetable using in a ground-target fashion similar to the Warlock spell

**Server Revision**: 2338

**Comment by Wolffenstein** [comment]
Fixed in rev 2379.
