### ISSUE TITLE
[Karazhan] The Chess Event pieces do not despawn after the event has been completed.

### ISSUE THREAD

**Issue by Fowdall** [Atlantiss/NetherwingBugtracker#2846]
[//]: # (Enclose links to things related to the bug using http://wowhead.com or any other TBC database.)
[//]: # (You can use screenshot ingame to visual the issue.)
[//]: # (Write your tickets according to the format:)
[//]: # ([Quest][Azuremyst Isle] Red Snapper - Very Tasty!)
[//]: # ([NPC] Magistrix Erona)
[//]: # ([Spell][Mage] Fireball)
[//]: # ([Npc][Drop] Ghostclaw Lynx)
[//]: # ([Web] Armory doesnt work)
[//]: # (To find server revision type `.server info` command in the game chat.)

**Description**: The pieces of the chess event do not despawn after defeating Warchief Kargath.

**Current behaviour**: The "pieces of the chess event return to their original positions after completing the Chess Event.

https://clips.twitch.tv/RenownedThankfulDelicataUnSane

**Expected behaviour**: The pieces of the chess event disappear after defeating Warchief Kargath.

**Server Revision**: 2338

**Comment by Easyfraggy** [comment]
You can play vs each other after completing chess (5 v 5) so to speak - don't think this report is valid

You can actually see them respawning slightly in the very last frames of this video before the fadeout:

https://youtu.be/b496Mc9A4U0?t=179
