### ISSUE TITLE
[Auchenai Crypts] Summon while hard CC'ed (potential global issue)

### ISSUE THREAD

**Issue by Azalen** [Atlantiss/NetherwingBugtracker#2847]
**Description**: 
Multiple mobs in the Auchenai Crypt have the same pool of summon abilities:

https://www.wowhead.com/npc=18495/auchenai-vindicator#abilities
https://www.wowhead.com/npc=18493/auchenai-soulpriest#abilities
https://www.wowhead.com/npc=18497/auchenai-monk#abilities

**Current behaviour**:
These summon abilities can get casted while being hard CC'ed (Polymorph for us).

**Expected behaviour**: 
They shouldn't.
Reference: #2828 

**Server Revision**: 
[2338]

**Comment by devo6969** [comment]
This is as intended, If the mob is Cced, it will still summon the undead mob regardless. 

(Retail BFA) https://www.youtube.com/watch?v=SLs1s5HboT0
