### ISSUE TITLE
[NPC][Karazhan] Nightbane

### ISSUE THREAD

**Issue by Brasso** [Atlantiss/NetherwingBugtracker#2848]
[//]: # (Enclose links to things related to the bug using http://wowhead.com or any other TBC database.)
[//]: # (You can use screenshot ingame to visual the issue.)
[//]: # (Write your tickets according to the format:)
[//]: # ([Quest][Azuremyst Isle] Red Snapper - Very Tasty!)
[//]: # ([NPC] Magistrix Erona)
[//]: # ([Spell][Mage] Fireball)
[//]: # ([Npc][Drop] Ghostclaw Lynx)
[//]: # ([Web] Armory doesnt work)
[//]: # (To find server revision type `.server info` command in the game chat.)

**Description**: 
Nightbane in Karazhan runs way too fast.
**Current behaviour**:
https://clips.twitch.tv/RoundTiredIguanaDogFace

**Server Revision**: 
2338

**Comment by Easyfraggy** [comment]
Speed is directly from retail sniffs - however he should indeed have a small grace period when landing and complete his landing animation.

**Comment by Drayo** [comment]
I think his landing was fixed at some point during the beta, at least it is not like in the clip anymore.

Can probably be closed.

**Comment by Manaci** [comment]
Most likely fixed
