### ISSUE TITLE
[Auchenai Crypts] Falter

### ISSUE THREAD

**Issue by Azalen** [Atlantiss/NetherwingBugtracker#2849]
**Description**: 
https://www.wowhead.com/spell=32859/falter

**Current behaviour**:
This spell does not act like an immobilize (root) but like a petrify. I cannot use any skill or turn around while having this debuff.

**Expected behaviour**: 
It should work like a root.

**Server Revision**: 
[2338]

**Comment by Tereneckla** [comment]
Fixed
