### ISSUE TITLE
Silverpine Forest - A Recipe for Death

### ISSUE THREAD

**Issue by Zeref09731** [Atlantiss/NetherwingBugtracker#285]
**Description**: ([Quest][Silverpine Forest] A Recipe for Death) - Low quest item drop rate for Skittering Blood

**Current behavior**: Quest item appears to have ~10% (2/20ish) drop rate based on attempts to kill the necessary NPCs.  This is based on spending approx 1 hr working on quest.
- http://classicdb.ch/?npc=1780
- http://classicdb.ch/?npc=1781
- http://classicdb.ch/?npc=12433

**Expected behavior**:   The quest item Skittering Blood, http://classicdb.ch/?item=3254, should have roughly 80% drop rate, per brief research.

**Other Notes**:  Might just be bad RNG on my part... Please advise if I can gather additional information for the team.  Thank you.

**Comment by aresbrutus** [comment]
Fixed in one of the next updates.
