### ISSUE TITLE
[NPC] Arcatraz (Heroic) Eredar Soul-Eater has no aura

### ISSUE THREAD

**Issue by BezawitNW** [Atlantiss/NetherwingBugtracker#2850]
The Eredar Soul-Eater's in Arcatraz (Heroic) do not have Entropic Aura like they should. The aura should reduces attack and cast speed of the players near them:

https://clips.twitch.tv/PeppySmallAyeayeItsBoshyTime

Documentation on abilities: 

https://www.wowhead.com/npc=20879/eredar-soul-eater#abilities

https://www.wowhead.com/npc=20879/eredar-soul-eater#comments

"Entropic Aura
Time between attacks increased by 25%
Casting Time increased by 25%
Movement Speed increased by 25%"

http://wowwiki.wikia.com/wiki/Eredar_Soul-Eater

https://wow.gamepedia.com/Eredar_Soul-Eater

**Comment by Easyfraggy** [comment]
![image](https://user-images.githubusercontent.com/36134067/48746218-d9d56a00-ec6e-11e8-834e-9b4f5af73502.png)

He doesn't have an aura he puts a debuff aura on you - works fine for me?

**Comment by BezawitNW** [comment]
Hmm that's odd- he never applied the debuff aura to anyone in our group:

https://clips.twitch.tv/PeppySmallAyeayeItsBoshyTime

Did you try in Heroic, Easy?

**Comment by Easyfraggy** [comment]
Confirmed it's missing in HC =)

**Comment by Evolvee** [comment]
rev xxd
