### ISSUE TITLE
Karazhan, Moroes

### ISSUE THREAD

**Issue by Erodraeda** [Atlantiss/NetherwingBugtracker#2851]
[//]: # (Enclose links to things related to the bug using http://wowhead.com or any other TBC database.)
[//]: # (You can use screenshot ingame to visual the issue.)
[//]: # (Write your tickets according to the format:)
[//]: # ([Quest][Azuremyst Isle] Red Snapper - Very Tasty!)
[//]: # ([NPC] Magistrix Erona)
[//]: # ([Spell][Mage] Fireball)
[//]: # ([Npc][Drop] Ghostclaw Lynx)
[//]: # ([Web] Armory doesnt work)
[//]: # (To find server revision type `.server info` command in the game chat.)

**Description**: 
We wiped after killing moroes, but even withtout killing the 4 adds he displayed his loot
**Current behaviour**:
Moroes is displaying his loot before killing the 4 adds
![wowscrnshot_112018_001751](https://user-images.githubusercontent.com/40346279/48747232-c66bd400-ec59-11e8-81c7-098694c3c899.jpg)
**Expected behaviour**: 
Moroes should only display loot after killing the 4 adds he has with him, and him, ofc.
**Server Revision**:

**Comment by Easyfraggy** [comment]
pretty sure this issue is invalid.
