### ISSUE TITLE
[Npc][Karazhan] Flame wreath killing raid instantly when landing on pets that are standing still

### ISSUE THREAD

**Issue by Brasso** [Atlantiss/NetherwingBugtracker#2853]
[//]: # (Enclose links to things related to the bug using http://wowhead.com or any other TBC database.)
[//]: # (You can use screenshot ingame to visual the issue.)
[//]: # (Write your tickets according to the format:)
[//]: # ([Quest][Azuremyst Isle] Red Snapper - Very Tasty!)
[//]: # ([NPC] Magistrix Erona)
[//]: # ([Spell][Mage] Fireball)
[//]: # ([Npc][Drop] Ghostclaw Lynx)
[//]: # ([Web] Armory doesnt work)
[//]: # (To find server revision type `.server info` command in the game chat.)

**Description**: 
When Aran's flame wreath lands on a pet, even it is ordered to stand still it will instantly kill the raid.
**Current behaviour**:
https://clips.twitch.tv/RealDullPanPJSalt

**Server Revision**: 
2338

**Comment by Easyfraggy** [comment]
https://gfycat.com/MetallicSecondhandCapeghostfrog

**Comment by Easyfraggy** [comment]
![image](https://user-images.githubusercontent.com/36134067/48771963-39f5fb80-ecc3-11e8-8378-e6aed24ae224.png)

Pet death has no effect either.

**Comment by Brasso** [comment]
Interesting. Combat log said "Shadhuun killed you." which is the warlocks felguard, there might be a difference between hunter pet and summoned pet. I also fully accept we are trash.

**Comment by Easyfraggy** [comment]
I'll try with warlock pet also!

**Comment by Easyfraggy** [comment]
Just tested with Felguard - no problem either as you can see on gif he only blows up when I tell him to follow me and thus moves.

https://gfycat.com/YawningDefensiveHammerkop

https://gfycat.com/CaringPopularDoe

**Comment by Easyfraggy** [comment]
After trying really hard to bug it - I did manage to do so - but it only happened because I made him reposition the last moments of the cast finishing.

https://gfycat.com/FamiliarBarrenJerboa

**Comment by Easyfraggy** [comment]
I kept trying for a bit and it seems to be when pet repositions right as the cast is finishing. Don't think this is actually a bug just bad gameplay by the pet controller.

**Comment by Shalovski** [comment]
After trying it once (and on purpose) with a Felguard during our raid, pressing PetStay() during the cast of Flame Wreath still caused the raid to explode (combat log showed it was caused by both the Felguard and the Hunter's Pet.)
Either the pet moved or it didn't; the result was the same : pet controller didn't make a mistake and the raid exploded. If the pet moved, then something wrong happened server-side, because PetStay() was pressed long before the cast ended.
The downside is that we only tested that once (we dismissed the pets on the next tries), maybe it does not happen all the time ?

**Comment by Easyfraggy** [comment]
stay command is a bit weird if pet is already attacking something - there are some bug reports open on the tracker already. Don't think this is a flamewreath problem.

**Comment by Easyfraggy** [comment]
https://gfycat.com/BareWellmadeAsianwaterbuffalo

**Comment by Noxvice** [comment]
Just had this occur in a kara run, my pet was just attacking aran normaly without stay pressed. Other hunter had his pet on stay, and his pet blew us up. 

We did got through a few flame wraths and only blew up once.

**Comment by Easyfraggy** [comment]
I honestly don't know what the issue is - only way I can make it happen is if I change pet settings (set stay) (set attack) right before the flame wreath cast ends. Which should make your pet blow up. So I don't see a bug - if you want to test it over and over one day I can make that happen.

**Comment by Noxvice** [comment]
Spend time with Smaily this morning at Aran. Was not able to reproduce it while my pet was still. It did however trigger almost every time my pet moved during Flame Wreath. It would seem that this does workm and that hunters should just remove pets on this fight. 

It's a 12 min enrage timer anyways, dps is not important, meters don't matter. 
Only thing with pets on this fight is that Avoidance is not working, but that is already reported elsewhere. 

 - Nox

**Comment by zauru7** [comment]
![989](https://user-images.githubusercontent.com/44526051/50001862-7e14ad00-ff9e-11e8-8aff-8882447b2016.PNG)
bit late but didn't know about it until now
https://web.archive.org/web/20071215105444/http://forums.wow-europe.com:80/thread.html?topicId=286852358&sid=1
