### ISSUE TITLE
[Item] Mark of Sargares

### ISSUE THREAD

**Issue by AndrewNB41191** [Atlantiss/NetherwingBugtracker#2855]
**Description**: Mark of Sargares appears to have stacked with Marks of Kiljaden when i placed them in my bank, pretty sure im not too high to play and didnt lose them.

**Current behaviour**: Separate items should not stack

**Expected behaviour**: 2 stacks

**Server Revision**: 2338

**Comment by Easyfraggy** [comment]
![image](https://user-images.githubusercontent.com/36134067/48771238-2053b480-ecc1-11e8-8d93-292f049cc5ae.png)
