### ISSUE TITLE
([Spell][Paladin] hammer of justice)

### ISSUE THREAD

**Issue by heydanbrowne** [Atlantiss/NetherwingBugtracker#2856]
[//]: # (Enclose links to things related to the bug using http://wowhead.com or any other TBC database.)
[//]: # (You can use screenshot ingame to visual the issue.)
[//]: # (Write your tickets according to the format:)
[//]: # ([Quest][Azuremyst Isle] Red Snapper - Very Tasty!)
[//]: # ([NPC] Magistrix Erona)
[//]: # ([Spell][Mage] Fireball)
[//]: # ([Npc][Drop] Ghostclaw Lynx)
[//]: # ([Web] Armory doesnt work)
[//]: # (To find server revision type `.server info` command in the game chat.)

**Description**: 
can't dispel hoj

**Current behaviour**:
can't dispel hoj

**Expected behaviour**: 
hoj can be dispelled

**Server Revision**:

**Comment by Godmatik** [comment]
Yes you can dispel it, probably fixed at some point, can be closed
