### ISSUE TITLE
[Item] Bangle of Endless Blessings

### ISSUE THREAD

**Issue by luther112** [Atlantiss/NetherwingBugtracker#2858]
Description: Bangle of Endless Blessings seems to proc from talking to any Gryph master.

Current behaviour: After talking with any neutral or ally Gryph master, "meditation" buff from Bangle of Endless Blessings procs.

Expected behaviour: "Meditation" buff from Bangle of Endless Blessings should only proc from casting spells.

Server Revision: 2340

**Comment by Manaci** [comment]
Fixed
