### ISSUE TITLE
[Spell] Invisibility

### ISSUE THREAD

**Issue by Dekirayne** [Atlantiss/NetherwingBugtracker#2859]
[//]: # (Enclose links to things related to the bug using http://wowhead.com or any other TBC database.)
[//]: # (You can use screenshot ingame to visual the issue.)
[//]: # (Write your tickets according to the format:)
[//]: # ([Quest][Azuremyst Isle] Red Snapper - Very Tasty!)
[//]: # ([NPC] Magistrix Erona)
[//]: # ([Spell][Mage] Fireball)
[//]: # ([Npc][Drop] Ghostclaw Lynx)
[//]: # ([Web] Armory doesnt work)
[//]: # (To find server revision type `.server info` command in the game chat.)

**Description**: 
Invisibility fails from time to time, and mobs can aggro you when invisible
**Current behaviour**:
Use invisibility and when the fading ends nothing happens just "invisibility fades" message, and if it succeeds regular mobs can throw you out of invisibility...
**Expected behaviour**: 
Should go invisible after the fading ends, and mobs shouldn't aggro you out of invisibility unless they have detection.
**Server Revision**: 
http://wowwiki.wikia.com/wiki/Invisibility_(mechanic)

**Comment by Wolffenstein** [comment]
Could you provide a video of that happening?

**Comment by Dekirayne** [comment]
> Could you provide a video of that happening?

I turned my instant replay on, when it happens ill capture it.

**Comment by Dekirayne** [comment]
> Could you provide a video of that happening?

ok i can't recreate it for the life of me, but the first day of instant 70 testing it happened quite a few times in a row actually. Anyways it works well now but idk why. Still the invisibility aggro stays as the issue.

**Comment by Easyfraggy** [comment]
If a projectile is already flying towards you i believe you should be broken out?

It is true that mobs should stop attacking you immediately though.

**Comment by Dekirayne** [comment]
> If a projectile is already flying towards you i believe you should be broken out?
> 
> It is true that mobs should stop attacking you immediately though.

it's not the projectile, on the first day of 70 testing i tried it in shat and it failed. As for the aggro I meant that mobs can't pull you out of the invisibility when it is fully effected, as it says in the mechanics.

**Comment by ircfelix** [comment]
Can confirm that behaviour. I just added some Greater Bogstroks in Slave Pens and used invisibility to get rid of them. I turned invisible, but didn't leave combat. After invis faded, they still followed me and I was still in combat.

**Comment by ircfelix** [comment]
Just happened again. Became invisible, didn't leave combat and got killed by an add.

**Comment by Easyfraggy** [comment]
Still need video of it happening.

**Comment by ircfelix** [comment]
https://i.imgur.com/kqop7Ao.jpg

Here you can see the strange behaviour. Check out the combat log:
1+2: Two times it is being refreshed, which I guess are the first two ticks of the threat reduce. 
3. Then I gain invisibility, which I guess that's the buff that makes you invisible (for simplicity reasons I'll call this "stealth buff" now, even though it is not stealth).
4. Then the threat decrease happens again.
5. The stealth buff fades.
6. The stealth buff applies again.
7. Mob applies Howling Screech to me.
8. The stealth buff fades.
9. I am afflicted by Howling Screech.
10-13. Mob hits me and I die.

During the whole points 4-10, I did not leave the invisibility **animation** at all.

Also check out EavesDrop in the right part of the screenshot. You don't see the --- combat --- before the mob hits me, but only after I died.  

Just try out Invisibility on a naked mage in Shattrath and look at your combat log, it looks utterly weird like this:
https://i.imgur.com/cUcWGmq.jpg

If this is not enough evidence, I'll go make a video for you. Btw, I had no dots or debuffs on me when before I used invisibility.

**Comment by Easyfraggy** [comment]
Need video - combat log doesn't show full picture.

**Comment by killablink** [comment]
Or here, 5 seconds passed and invisibility didn't trigger: https://gfycat.com/ClumsyCreativeGermanpinscher

**Comment by The14me** [comment]
rev.3478 not an issue anymore.
Can be closed.
