### ISSUE TITLE
[Item] Quagmirans eye gets proced by armor

### ISSUE THREAD

**Issue by Dekirayne** [Atlantiss/NetherwingBugtracker#2861]
[//]: # (Enclose links to things related to the bug using http://wowhead.com or any other TBC database.)
[//]: # (You can use screenshot ingame to visual the issue.)
[//]: # (Write your tickets according to the format:)
[//]: # ([Quest][Azuremyst Isle] Red Snapper - Very Tasty!)
[//]: # ([NPC] Magistrix Erona)
[//]: # ([Spell][Mage] Fireball)
[//]: # ([Npc][Drop] Ghostclaw Lynx)
[//]: # ([Web] Armory doesnt work)
[//]: # (To find server revision type `.server info` command in the game chat.)

**Description**: 
Quagmirans eye gets proced from ice armor
**Current behaviour**:
Quagmirans eye gets proced from ice armor
**Expected behaviour**: 
Should only happen from harmful spells
**Server Revision**:

**Comment by Easyfraggy** [comment]
Trinkets proccing from spells should only proc from damaging spells in general.

**Comment by Tereneckla** [comment]
Fixed
