### ISSUE TITLE
[NPC][Boss] Terestian Illhoof strange reset after wipe

### ISSUE THREAD

**Issue by Mikik3jr** [Atlantiss/NetherwingBugtracker#2862]
[//]: # (Enclose links to things related to the bug using http://wowhead.com or any other TBC database.)
[//]: # (You can use screenshot ingame to visual the issue.)
[//]: # (Write your tickets according to the format:)
[//]: # ([Quest][Azuremyst Isle] Red Snapper - Very Tasty!)
[//]: # ([NPC] Magistrix Erona)
[//]: # ([Spell][Mage] Fireball)
[//]: # ([Npc][Drop] Ghostclaw Lynx)
[//]: # ([Web] Armory doesnt work)
[//]: # (To find server revision type `.server info` command in the game chat.)

**Description**: 
We wiped on Illhoof in Karazhan. I had a soulstone on myself, but I died too deep inside. When the last person died the boss started to run back to his position (from outside of the room) and I used this time to rezz myself back and run out, before the boss arrives to his starting point. I got out of the room, but we stuck in a nonstop combat/out of combat cycle until someone died.

**Current behaviour**:
Cringe incoming:
https://www.youtube.com/watch?v=Ak3cUcOJcys&feature=youtu.be

**Expected behaviour**: 
I have no proof how it should look like in this situation, but I haven't found anything in comments that mentions this specific phenomenom.

**Server Revision**: 
2338

**Comment by Drayo** [comment]
We also had this issue today. 

When the boss resets, Kil'rek despawns then Illhoof re-summons Kil'rek who is still in-fight with the players, Illhoof also aggros, but because the players are not in his room he resets over and over.

The issue seems to be be Kil'rek not properly getting out of fight.

**Comment by devo6969** [comment]
This is still happening. If you don't out range Kil'rek he keeps aggroing towards the alive player forcing you to go up the stairs.

PTR Long version (Without Stairs) - https://www.youtube.com/watch?v=8FHn3y2nqRA
PTR Short Version (Without Stairs) - https://www.youtube.com/watch?v=SpyEuoxCfo0
PTR Stairs (Out-ranging Kil'rek) - https://www.youtube.com/watch?v=jpA3FFN6pFk

**Comment by Wolffenstein** [comment]
Fixed in rev 3455.
