### ISSUE TITLE
[NPC] Ethereal Beacon is not visible

### ISSUE THREAD

**Issue by Mikik3jr** [Atlantiss/NetherwingBugtracker#2863]
[//]: # (Enclose links to things related to the bug using http://wowhead.com or any other TBC database.)
[//]: # (You can use screenshot ingame to visual the issue.)
[//]: # (Write your tickets according to the format:)
[//]: # ([Quest][Azuremyst Isle] Red Snapper - Very Tasty!)
[//]: # ([NPC] Magistrix Erona)
[//]: # ([Spell][Mage] Fireball)
[//]: # ([Npc][Drop] Ghostclaw Lynx)
[//]: # ([Web] Armory doesnt work)
[//]: # (To find server revision type `.server info` command in the game chat.)

**Description**: 
In Mana Tombs (in this case HC) the final boss [Nexus-Prince Shaffar](https://www.wowhead.com/npc=18344/nexus-prince-shaffar) has 2 [Ethereal Beacons](https://www.wowhead.com/npc=18431/ethereal-beacon#comments) next to him. In the fight the boss summons more and more Beacons.

**Current behaviour**:
These beacons are invisible and cannot be targeted with cursos, only with TAB. The summoned ones alter are invisible as well.
![wowscrnshot_112018_134248](https://user-images.githubusercontent.com/43505031/48774857-abd24300-eccb-11e8-82fc-f0ae3ecbf18e.jpg)
![wowscrnshot_112018_134257](https://user-images.githubusercontent.com/43505031/48774858-ac6ad980-eccb-11e8-88c2-a7d39c00de21.jpg)

**Expected behaviour**: 
Beacons should be visible with a spark-bubble-thingy skin.

**Server Revision**: 
2238

**Comment by AxeCell** [comment]
Would also like to add that the NPCs aren't casting enough spells to make the fight a challenge.

**Comment by Manaci** [comment]
Fixed
