### ISSUE TITLE
[NPC](PVP - ARENA) Summonable creatures spawning as friendly to same faction

### ISSUE THREAD

**Issue by huntdfl** [Atlantiss/NetherwingBugtracker#2864]
Two separate occasions this happened last night in arena.
1. Versus a UD mage: summons water elemental is spawned but shows green (friendly) and is not attackable.  It still was attacking us and Freeze + Waterbolt still worked correctly. Attempted to pummel it despite it's friendly status but was unable.
2. Versus a UD rogue: Nightseye panther (https://www.wowhead.com/item=24128/figurine-nightseye-panther) was summoned and followed the rogue around but was listed as green/friendly - unsure if this should be listed as red/hostile and should be killable.

**Comment by Evolvee** [comment]
2. is fine

**Comment by Manaci** [comment]
Fixed
