### ISSUE TITLE
[NPC] Talon King Ikiss level

### ISSUE THREAD

**Issue by Kidcudi123** [Atlantiss/NetherwingBugtracker#2865]
current behaviour: lvl 73 and does crushing blows to tank with 500 defense.

Expected: This guy should be lvl 72 and do no crushing blows (crushing blow should probably have its own report)

Source
https://youtu.be/jsp6n_ssyjk
http://wowwiki.wikia.com/wiki/Crushing_blow

**Comment by Easyfraggy** [comment]
Crushing blows happen no matter how much defense you have - it's about 15% from a +3 mob.

**Comment by Easyfraggy** [comment]
Could be that it's a typo on bestiary - need more evidence of level 72.

**Comment by Easyfraggy** [comment]
![image](https://user-images.githubusercontent.com/36134067/48778543-c7424b80-ecd5-11e8-9269-b914c56738cc.png)
Earliest vid I can find seems to say 72 also!

**Comment by Evolvee** [comment]
rev 2827
