### ISSUE TITLE
Priest - Desperate Prayer spell missing 

### ISSUE THREAD

**Issue by Nicemann1089** [Atlantiss/NetherwingBugtracker#2866]
[//]: # (Enclose links to things related to the bug using http://wowhead.com or any other TBC database.)
[//]: # (You can use screenshot ingame to visual the issue.)
[//]: # (Write your tickets according to the format:)
[//]: # ([Quest][Azuremyst Isle] Red Snapper - Very Tasty!)
[//]: # ([NPC] Magistrix Erona)
[//]: # ([Spell][Mage] Fireball)
[//]: # ([Npc][Drop] Ghostclaw Lynx)
[//]: # ([Web] Armory doesnt work)
[//]: # (To find server revision type `.server info` command in the game chat.)

**Description**: Desperate Prayer spell missing 

**Current behaviour**: Desperate Prayer spell missing 

**Expected behaviour**: 

**Server Revision**: 2338

**Comment by aresbrutus** [comment]
I need more info, which race of priest are you? Which trainer did you go to?

**Comment by ahlens** [comment]
As far as I know Human and Dwarf should have it. Yesterday it worked well. 

Did you go to Murloc and click "Teach me everything I should know"?

**Comment by Nicemann1089** [comment]
please close, I am stupid :)
