### ISSUE TITLE
auto attack

### ISSUE THREAD

**Issue by bloodwindz** [Atlantiss/NetherwingBugtracker#2868]
[//]: # (Enclose links to things related to the bug using http://wowhead.com or any other TBC database.)
[//]: # (You can use screenshot ingame to visual the issue.)
[//]: # (Write your tickets according to the format:)
[//]: # ([Quest][Azuremyst Isle] Red Snapper - Very Tasty!)
[//]: # ([NPC] Magistrix Erona)
[//]: # ([Spell][Mage] Fireball)
[//]: # ([Npc][Drop] Ghostclaw Lynx)
[//]: # ([Web] Armory doesnt work)
[//]: # (To find server revision type `.server info` command in the game chat.)

**Description**:  auto attack dont get trigger by offensive damaging melee abilities

**Current behaviour**:as warrior while dueling with 70 rage  i engaged combat for a test and used with my 70 rage (rage pot)  mortal strike but it dint trigger auto attack afterwards

**Expected behaviour**:  abilties like mortal strike (possibly other too?) should trigger auto attack  if they are used with enough rage  or energy

**Server Revision**: 2340

**Comment by Easyfraggy** [comment]
![image](https://user-images.githubusercontent.com/36134067/48782965-99620480-ecdf-11e8-8844-8d723f4495be.png)
