### ISSUE TITLE
Heroic Manatombs - Tavarok

### ISSUE THREAD

**Issue by Manaforall1** [Atlantiss/NetherwingBugtracker#2869]
[//]: # (Enclose links to things related to the bug using http://wowhead.com or any other TBC database.)
[//]: # (You can use screenshot ingame to visual the issue.)
[//]: # (Write your tickets according to the format:)
[//]: # ([Quest][Azuremyst Isle] Red Snapper - Very Tasty!)
[//]: # ([NPC] Magistrix Erona)
[//]: # ([Spell][Mage] Fireball)
[//]: # ([Npc][Drop] Ghostclaw Lynx)
[//]: # ([Web] Armory doesnt work)
[//]: # (To find server revision type `.server info` command in the game chat.)

**Description**: 
Tavarok in Manatombs Heroic does not seem to be using his Arcing Smash ability.
**Current behaviour**:
Currently Tavarok in Manatombs Heroic seem to be missing his Arcing Smash ability.
All hits i got while tanking him were between 1,5k -2.3k.
Arcing Smash should do around 10k-11k dmg in the currently available gear.
Could possibly have dodged/parried it.
https://wow.gamepedia.com/Tavarok
**Expected behaviour**: 
Should be using Arcing Smash every now and then, leading to huge spike dmg on the tank.
**Server Revision**: 
2238

**Comment by Easyfraggy** [comment]
He is indeed not using it - even though he has the ability in wolfAI

![image](https://user-images.githubusercontent.com/36134067/48790664-2f9e2680-ecf0-11e8-9613-eb096c518d8e.png)

![image](https://user-images.githubusercontent.com/36134067/48790696-40e73300-ecf0-11e8-9579-925b2d38438f.png)

**Comment by Tereneckla** [comment]
Fixed
