### ISSUE TITLE
[Line of Sight](Scarlet Initiate,Trisfal Glades)They will start/continue casting fireball even if im out of their line of sight.

### ISSUE THREAD

**Issue by Domo0696** [Atlantiss/NetherwingBugtracker#287]
[//]: # (Enclose links to things related to the bug using http://wowhead.com or any other TBC database.)
[//]: # (You can use screenshot ingame to visual the issue.)
[//]: # (Write your tickets according to the format:)
[//]: # ([Quest][Azuremyst Isle] Red Snapper - Very Tasty!)
[//]: # ([NPC] Magistrix Erona)
[//]: # ([Spell][Mage] Fireball)
[//]: # ([Npc][Drop] Ghostclaw Lynx)
[//]: # ([Web] Armory doesnt work)

**Description**:
Scarlet Initiate will start/continue casting fireball even if im out of their line of sight.

**Current behaviour**:
The mob will continue to damage me even if i hide behind a tree or anything else.
**Expected behaviour**: 

**Server Revision**:

**Comment by Godmatik** [comment]
Trees are not LoS objects, that is blizzlike.
