### ISSUE TITLE
[Mana Tombs][Spell] Mana Leech ability Arcane Explosion does too little damage

### ISSUE THREAD

**Issue by Manaforall1** [Atlantiss/NetherwingBugtracker#2870]
[//]: # (Enclose links to things related to the bug using http://wowhead.com or any other TBC database.)
[//]: # (You can use screenshot ingame to visual the issue.)
[//]: # (Write your tickets according to the format:)
[//]: # ([Quest][Azuremyst Isle] Red Snapper - Very Tasty!)
[//]: # ([NPC] Magistrix Erona)
[//]: # ([Spell][Mage] Fireball)
[//]: # ([Npc][Drop] Ghostclaw Lynx)
[//]: # ([Web] Armory doesnt work)
[//]: # (To find server revision type `.server info` command in the game chat.)

**Description**: 
Mana Leech have issues with their abilities.
**Current behaviour**:
Mana Leach´s ability Arcane Explosion only does 800 dmg upon death.
**Expected behaviour**: 
Mana Leach´s ability Arcane Explosion should do 1200 dmg upon death.
https://www.wowhead.com/npc=19306/mana-leech#comments
**Server Revision**: 
2238

**Comment by Azalen** [comment]
#2828

**Comment by Evolvee** [comment]
rev xxd
