### ISSUE TITLE
Sethekk Halls H! Spell Reflection

### ISSUE THREAD

**Issue by Nixazzar** [Atlantiss/NetherwingBugtracker#2871]
**Description**: 
In Sethekk Halls on heroic difficulty (not tested on normal).
Spell reflection that Sethekk Initiate use is not working, it should reflect damage back to its caster!
**Current behaviour**:
Any spell used gets back to its caster in terms of visual animations but damage is not reflected, also any kind of harmful spell, debuff, dot etc. wont cause damage or "stick" to caster.
**Expected behaviour**: 
https://www.wowhead.com/spell=33961/spell-reflection
"Raise your shield, reflecting the next spell cast on you.  Lasts 6 sec." Spell should work like this, linked from Sethekk Halls initiate.
**Server Revision**: 
2238

**Comment by Wolffenstein** [comment]
It will be fixed in the next update.

**Comment by bloodwindz** [comment]
its the same for PVP it dont reflect spells on pvp
