### ISSUE TITLE
[NPC] [Boss] [Spell] [Karazhan] Shade of Aran - Arcane Missiles

### ISSUE THREAD

**Issue by Drayo** [Atlantiss/NetherwingBugtracker#2873]
[//]: # (Enclose links to things related to the bug using http://wowhead.com or any other TBC database.)
[//]: # (You can use screenshot ingame to visual the issue.)
[//]: # (Write your tickets according to the format:)
[//]: # ([Quest][Azuremyst Isle] Red Snapper - Very Tasty!)
[//]: # ([NPC] Magistrix Erona)
[//]: # ([Spell][Mage] Fireball)
[//]: # ([Npc][Drop] Ghostclaw Lynx)
[//]: # ([Web] Armory doesnt work)
[//]: # (To find server revision type `.server info` command in the game chat.)

**Description**: 

The implementation of Arcane Missiles is slightly wrong.

**Current behaviour**: 

His Arcane Missiles have an initial cast on Netherwing. (He casts "Arcane Missiles" for 1-1.5 seconds and when the cast is finished he starts actually channeling "Arcane Missiles")

**Expected behaviour**: 

His Arcane Missiles should NOT haven an initial cast and he should instantly channel them.

**Sources**:  Any Video that shows a cast bar, one can just look at the model and timing of the first Missile too.

https://youtu.be/3ltTqtrV_qM?t=158

**Server Revision**:  2238

**Comment by Drayo** [comment]
It looks like this issue did not get fixed, he still has an initial cast for Arcane Missiles as of Rev: 2366.

**Comment by Easyfraggy** [comment]
Yep I also said this on discord few days ago - still has initial cast time.

**Comment by Manaci** [comment]
Fixed

**Comment by Drayo** [comment]
This seems to have resurfaced: https://youtu.be/fcbGIgVoEgM

Compared to retail: https://youtu.be/3ltTqtrV_qM?t=158

You can kick Arcane Missiles before he actually channels it, thus preventing him from using any Mana at all.

**Comment by Drayo** [comment]
Also, a second issue with his Arcane Missiles is that the actual channel has a short range. He cancels his cast.

**Initial Cast** (should not exist but correct range) -> **Channel** -> **Cancel** (range too short?)

https://www.youtube.com/watch?v=owaF1fdaN7k - Can be seen 3 times after he casts Arcane Explosion.

**Comment by Wolffenstein** [comment]
Fixed in rev 3484.
