### ISSUE TITLE
[NPC] Coilfang Champion doesn't fear

### ISSUE THREAD

**Issue by Mikik3jr** [Atlantiss/NetherwingBugtracker#2875]
[//]: # (Enclose links to things related to the bug using http://wowhead.com or any other TBC database.)
[//]: # (You can use screenshot ingame to visual the issue.)
[//]: # (Write your tickets according to the format:)
[//]: # ([Quest][Azuremyst Isle] Red Snapper - Very Tasty!)
[//]: # ([NPC] Magistrix Erona)
[//]: # ([Spell][Mage] Fireball)
[//]: # ([Npc][Drop] Ghostclaw Lynx)
[//]: # ([Web] Armory doesnt work)
[//]: # (To find server revision type `.server info` command in the game chat.)

**Description**: 
[Coilfang Champions](https://www.wowhead.com/npc=17957/coilfang-champion#comments) are in Slave Pens mostly in groups.

**Current behaviour**:
We pulled a 5 group at the end which consists of 2 Champions. We killed them last. They haven't used any fear.

**Expected behaviour**: 
Coilfang Champions should fear. At least IF they really supposed to have fear they should have used it at least once.

Sadly this is my shitty proof about it:
![image](https://user-images.githubusercontent.com/43505031/48795761-12705480-ecfe-11e8-8f14-7e2dbc641fa1.png)

**Server Revision**: 
2338

**Comment by Easyfraggy** [comment]
They do use Frightening Shout - about 10-20 seconds in. 

![image](https://user-images.githubusercontent.com/36134067/48799607-e6f26780-ed07-11e8-8e8a-30312032ea39.png)

![image](https://user-images.githubusercontent.com/36134067/48799646-05f0f980-ed08-11e8-8c1d-71f3235855e9.png)

Maybe you just stunned/cc'd them at the right times?

**Comment by Mikik3jr** [comment]
We noticed it 1 time, so in later 5 packs we killed the last 2 champions last. We didn't have much CC.
Pala tank
Pala Heal
Elemental shaman
Warlock
Balance druid

**Comment by Easyfraggy** [comment]
Need recreation steps - they use it fine for me solo.

**Comment by Mikik3jr** [comment]
Only these 2 screenshots I can provide:
![wowscrnshot_112018_192636](https://user-images.githubusercontent.com/43505031/48866384-effc3b00-edd2-11e8-8dde-60efaf3464f2.jpg)
![wowscrnshot_112018_192923](https://user-images.githubusercontent.com/43505031/48866385-f094d180-edd2-11e8-8474-bbf5385a5ef6.jpg)

**Comment by Evolvee** [comment]
timer reduced

if there was some different issue, reopen pls

**Comment by Evolvee** [comment]
rev xxd
