### ISSUE TITLE
[Spell] Demonic Sacrifice

### ISSUE THREAD

**Issue by ghost** [Atlantiss/NetherwingBugtracker#2876]
[//]: # (Enclose links to things related to the bug using http://wowhead.com or any other TBC database.)
[//]: # (You can use screenshot ingame to visual the issue.)
[//]: # (Write your tickets according to the format:)
[//]: # ([Quest][Azuremyst Isle] Red Snapper - Very Tasty!)
[//]: # ([NPC] Magistrix Erona)
[//]: # ([Spell][Mage] Fireball)
[//]: # ([Npc][Drop] Ghostclaw Lynx)
[//]: # ([Web] Armory doesnt work)
[//]: # (To find server revision type `.server info` command in the game chat.)

**Description**: 

Currently playing warlock and noticed as destruction spec that Demonic Sacrifice isn't functioning as it did in retail.

**Current behaviour**:

When being sacrificed, demon just fades out.

**Expected behaviour**: 

When Demonic Sacrifice is cast, the demon should show a dying animation and make the dying sound.

**Server Revision**: 

2340

**Comment by devo6969** [comment]
They have changed this on Netherwing to fit the expected behavior. This is fixed
