### ISSUE TITLE
Dungeon ID save is removed somehow

### ISSUE THREAD

**Issue by Mikik3jr** [Atlantiss/NetherwingBugtracker#2877]
[//]: # (Enclose links to things related to the bug using http://wowhead.com or any other TBC database.)
[//]: # (You can use screenshot ingame to visual the issue.)
[//]: # (Write your tickets according to the format:)
[//]: # ([Quest][Azuremyst Isle] Red Snapper - Very Tasty!)
[//]: # ([NPC] Magistrix Erona)
[//]: # ([Spell][Mage] Fireball)
[//]: # ([Npc][Drop] Ghostclaw Lynx)
[//]: # ([Web] Armory doesnt work)
[//]: # (To find server revision type `.server info` command in the game chat.)

**Description**: 
I finished SP hc, but at the end I remained afk in the dungeon. There was a restart to advance the server revision from 2338 to 2339.

**Current behaviour**:
There was someone else in a party and I left. The 1 minute timer appeared for ghetto HS. I teleported back to shatt (my HS home). I checked then I realized that I am not saved for SP hc. (But still saved to HC mana tombs which I have done already today)

**Expected behaviour**: 
Well I just report this, because you told us to report behaviours like this back in phase1.

**Server Revision**: 
2238->2239

**Comment by Mikik3jr** [comment]
Update:
We killed 2 boss in SP HC and I was not saved.
![wowscrnshot_112618_190154](https://user-images.githubusercontent.com/43505031/49032857-f4976980-f1ad-11e8-9fe0-1426143d6759.jpg)

**Comment by Manaci** [comment]
Fixed
