### ISSUE TITLE
[NPC] [Immunity] [Karazhan] Mana Feeder

### ISSUE THREAD

**Issue by Drayo** [Atlantiss/NetherwingBugtracker#2879]
[//]: # (Enclose links to things related to the bug using http://wowhead.com or any other TBC database.)
[//]: # (You can use screenshot ingame to visual the issue.)
[//]: # (Write your tickets according to the format:)
[//]: # ([Quest][Azuremyst Isle] Red Snapper - Very Tasty!)
[//]: # ([NPC] Magistrix Erona)
[//]: # ([Spell][Mage] Fireball)
[//]: # ([Npc][Drop] Ghostclaw Lynx)
[//]: # ([Web] Armory doesnt work)
[//]: # (To find server revision type `.server info` command in the game chat.)

**Description**: 

[Mana Feeders ](https://www.wowhead.com/npc=16491/mana-feeder#comments) are not immune to fear.

**Current behaviour**:

Mana Feeders can be feared.

**Expected behaviour**: 

Mana Feeders are supposed to be immune to ALL magic damage and effects. They cannot be trapped by hunters for example, so fear or ANY other magical type CC should not work on them. Physical Stuns etc. should work though.

**Server Revision**: 2238

**Comment by Drayo** [comment]
Just noticed that it could have been "Intimidating Shout" not sure if that one counts as a Physical ability.

**Comment by Easyfraggy** [comment]
Warrior shout is also a regular fear effect.

**Comment by Saben65** [comment]
They should also be immune to wands. Currently it seems the damage from wands is not be handled like magic damage, even though it shows up in the logs as doing magic damage.

**Comment by Wolffenstein** [comment]
Fixed in rev 3430.
