### ISSUE TITLE
[Spell][Core Mechanic] Spell leeway is missing on NPCS

### ISSUE THREAD

**Issue by killablink** [Atlantiss/NetherwingBugtracker#288]
**Description**: Someone else posted it but you closed it requiring proof so I'm reposting this. When a target gets slightly out of range, the spell cast should still go off.

**Current behaviour**: NPC target walks 1 yard out of range, spell doesnt go off

**Expected behaviour**: Apply leeway so that even if he runs slighty out of range, the cast goes off:
https://youtu.be/9A78vBofREg?t=293  Scorch cast goes off, you can even clearly see the quartz bar going grey (out of range)

**Server Revision**: 2037

**Comment by knasen88** [comment]
#121

**Comment by wtRCH** [comment]
Duplicate

**Comment by Wolffenstein** [comment]
Fixed in rev 2038.
