### ISSUE TITLE
Karazhan Loot sharing

### ISSUE THREAD

**Issue by justicex123** [Atlantiss/NetherwingBugtracker#2880]
[//]: # (Enclose links to things related to the bug using http://wowhead.com or any other TBC database.)
[//]: # (You can use screenshot ingame to visual the issue.)
[//]: # (Write your tickets according to the format:)
[//]: # ([Quest][Azuremyst Isle] Red Snapper - Very Tasty!)
[//]: # ([NPC] Magistrix Erona)
[//]: # ([Spell][Mage] Fireball)
[//]: # ([Npc][Drop] Ghostclaw Lynx)
[//]: # ([Web] Armory doesnt work)
[//]: # (To find server revision type `.server info` command in the game chat.)

**Description**: 
We killed Opera yesterday and dont loot it, today we took new healer without Kara CD and he looted a item from boss
**Current behaviour**:

**Expected behaviour**: 
u can't loot boss when u haven't been in raid
**Server Revision**: 
2338

**Comment by Manaci** [comment]
Fixed
