### ISSUE TITLE
Can't retrieve corpse in Raid if you leave group

### ISSUE THREAD

**Issue by Gimmedapurps** [Atlantiss/NetherwingBugtracker#2881]
[//]: # (Enclose links to things related to the bug using http://wowhead.com or any other TBC database.)
[//]: # (You can use screenshot ingame to visual the issue.)
[//]: # (Write your tickets according to the format:)
[//]: # ([Quest][Azuremyst Isle] Red Snapper - Very Tasty!)
[//]: # ([NPC] Magistrix Erona)
[//]: # ([Spell][Mage] Fireball)
[//]: # ([Npc][Drop] Ghostclaw Lynx)
[//]: # ([Web] Armory doesnt work)
[//]: # (To find server revision type `.server info` command in the game chat.)

**Description**: Cant revive by retrieving corpse in a Raid Instance if you leave group while corpse running back.

**Current behaviour**: Cant revive by retrieving corpse in a Raid Instance if you leave group while corpse running back.

**Expected behaviour**: Walking into Instance Portal should revive you outside.

**Server Revision**:

**Comment by Brasso** [comment]
Just tested in SSC by leaving raid group before entering, works now. Can close.
