### ISSUE TITLE
Combat bug after party member gets mind controlled

### ISSUE THREAD

**Issue by nycheia** [Atlantiss/NetherwingBugtracker#2885]
**Description**: 
Tank gets mc'd, attacks me and i attack him and i stay in combat afterwards as the only party member

It was not debugged, but i do believe it was related to the MC.

Alt + F4 fixed it however.

Video: https://clips.twitch.tv/ExuberantInterestingLyrebirdSoBayed

**Server Revision**: 
2339

**Comment by Easyfraggy** [comment]
This seems to be related to MC and pets getting stuck in combat with MC targets.
