### ISSUE TITLE
[Item] Savory Deviate Delight buffs don't replace each other.

### ISSUE THREAD

**Issue by Spaztick** [Atlantiss/NetherwingBugtracker#2887]
**Description**: 
Savory Deviate Delight buffs don't replace each other, so you can have Flip Out and Yaaarrrr buffs at the same time.

**Current behaviour**:
Buffs are not removed when eating SDD.

**Expected behaviour**: 
Flip Out/Yaaarrrr is removed and a new buff replaces it.

**Server Revision**: 
2339

**Comment by Easyfraggy** [comment]
This only applies to shapeshifting buffs. You can have all the other noggenfogger effects at the same time.

**Comment by Wolffenstein** [comment]
Fixed in rev 3429.
