### ISSUE TITLE
[Talent][Priest] "Blackout" talent not proc'ing from some spells.

### ISSUE THREAD

**Issue by CCmagro** [Atlantiss/NetherwingBugtracker#2888]
[//]: # (Enclose links to things related to the bug using http://wowhead.com or any other TBC database.)
[//]: # (You can use screenshot ingame to visual the issue.)
[//]: # (Write your tickets according to the format:)
[//]: # ([Quest][Azuremyst Isle] Red Snapper - Very Tasty!)
[//]: # ([NPC] Magistrix Erona)
[//]: # ([Spell][Mage] Fireball)
[//]: # ([Npc][Drop] Ghostclaw Lynx)
[//]: # ([Web] Armory doesnt work)
[//]: # (To find server revision type `.server info` command in the game chat.)

**Description**: Spells Shadow Word: Death and Vampiric Touch are not proc'ing "Blackout" talent.

**Expected behaviour**: They should.

**Server Revision**: 2340

**Comment by Easyfraggy** [comment]
need some proof that what you are saying is:

1. true.
2. proof it should proc it.

**Comment by Azalen** [comment]
https://youtu.be/FArCxTrkNVg?t=181
You see him casting Shadow Word: Pain proccing Blackout.

Shadow Word: Death is a normal shadow damage spell from the shadow tree. There is plenty of footage in the video showing that it procs Blackout. There is no reason it shouldn't from just reading the Talent.

How it should work: Blackout can proc from the initial cast but not from the following damage ticks.
Proof: https://wow.gamepedia.com/index.php?title=Blackout&oldid=1576626

**Comment by Azalen** [comment]
Can confirm the initial report. 

Vampiric Touch does not proc Blackout.

**Comment by CCmagro** [comment]
Thx for video, i couldn't find any other proof. At 22:33 you can see SW:D proccing it.
https://youtu.be/FArCxTrkNVg?t=1350

**Comment by Easyfraggy** [comment]
So now we just need proof that these spells don't actually proc it on NW.

**Comment by CCmagro** [comment]
All i did was casting ~40 times each of these 2 spells. The other shadow dmg spells proc'ed within a "few" casts (less than 15).

**Comment by Easyfraggy** [comment]
It's 10% chance - could still just be bad luck - however no need for more proof it's probably just a missing flag.

**Comment by towneh** [comment]
Some testing for the proc on VT and SWD today. Not currently observed:
https://www.twitch.tv/videos/341175065

**Comment by Wolffenstein** [comment]
Fixed in rev 2399.
