### ISSUE TITLE
No loot from wyverns in Highperch

### ISSUE THREAD

**Issue by Buskmurvel** [Atlantiss/NetherwingBugtracker#289]
So i farmed half a lvl in Highperch in Thousand Needles. Probably around 50-70 mobs killed.
Didnt get loot from a single monster.

**Comment by aresbrutus** [comment]
They are supposed to be really really shit at dropping loot. 

I tested and it does drop loot but a very low drop chance. You can check Joana and see the amount of empty loots here: https://youtu.be/FG8pkhreZjU?t=1105

Please PM me if you disagree and want this to be re-opened.
