### ISSUE TITLE
[Npc][Karazhan] Dreadbeast, Shadowbeast and Phase Hound

### ISSUE THREAD

**Issue by Brasso** [Atlantiss/NetherwingBugtracker#2890]
[//]: # (Enclose links to things related to the bug using http://wowhead.com or any other TBC database.)
[//]: # (You can use screenshot ingame to visual the issue.)
[//]: # (Write your tickets according to the format:)
[//]: # ([Quest][Azuremyst Isle] Red Snapper - Very Tasty!)
[//]: # ([NPC] Magistrix Erona)
[//]: # ([Spell][Mage] Fireball)
[//]: # ([Npc][Drop] Ghostclaw Lynx)
[//]: # ([Web] Armory doesnt work)
[//]: # (To find server revision type `.server info` command in the game chat.)

**Description**: 
Combining report because lazy, sorry. Dreadbeast and Shadowbeast do not use Howl of the Broken Hills https://www.wowhead.com/spell=29304/howl-of-the-broken-hills.

Phase hound phases almost constantly, might need to check the timer.

**Current behaviour**:
https://clips.twitch.tv/TentativeObliqueNarwhalItsBoshyTime

**Server Revision**: 
2338

**Comment by Wolffenstein** [comment]
Fixed in rev 2342.

**Comment by Brasso** [comment]
This is broken again. Phase hounds do not phase at all, and the other two do not cast Howl of the Broken Hills.
