### ISSUE TITLE
[Spell][Priest] Prayer of Mending not working as intended

### ISSUE THREAD

**Issue by Nicemann1089** [Atlantiss/NetherwingBugtracker#2891]
[//]: # (Enclose links to things related to the bug using http://wowhead.com or any other TBC database.)
[//]: # (You can use screenshot ingame to visual the issue.)
[//]: # (Write your tickets according to the format:)
[//]: # ([Quest][Azuremyst Isle] Red Snapper - Very Tasty!)
[//]: # ([NPC] Magistrix Erona)
[//]: # ([Spell][Mage] Fireball)
[//]: # ([Npc][Drop] Ghostclaw Lynx)
[//]: # ([Web] Armory doesnt work)
[//]: # (To find server revision type `.server info` command in the game chat.)

https://drive.google.com/file/d/1h9rbcmi9rNJip-BCf5J5TIaewwgoSo69/view?usp=drivesdk

**Description**: As you can see in the video Prayer of Mending is doing weird things. It was the whole dungeon like that.

**Current behaviour**: Prayer of Mending jumps from the caster several times to targets without coming back and being triggered.

**Expected behaviour**: Prayer of Mending should only have one instance per cooldown and jump from player to player.

**Server Revision**: I uploaded it 6 hours later. I think it should be 2338.

**Comment by Easyfraggy** [comment]
probably an animation only issue.
