### ISSUE TITLE
[NPC] [Spell] [Karazhan] Nightbane - Distracting Ash

### ISSUE THREAD

**Issue by Drayo** [Atlantiss/NetherwingBugtracker#2892]
[//]: # (Enclose links to things related to the bug using http://wowhead.com or any other TBC database.)
[//]: # (You can use screenshot ingame to visual the issue.)
[//]: # (Write your tickets according to the format:)
[//]: # ([Quest][Azuremyst Isle] Red Snapper - Very Tasty!)
[//]: # ([NPC] Magistrix Erona)
[//]: # ([Spell][Mage] Fireball)
[//]: # ([Npc][Drop] Ghostclaw Lynx)
[//]: # ([Web] Armory doesnt work)
[//]: # (To find server revision type `.server info` command in the game chat.)

**Description**: 

Distracting Ash has some issues.

**Current behaviour**:

He CASTS Distracting Ash (1 second cast) while he is on the ground AND while he is in the air, when he finally applies it, he turns to the player it is being cast on. It seems like the Spell reduces hit chance.

**Expected behaviour**: 

- Distracting Ash must be INSTANT. 
~~He should ONLY cast it in his GROUND-PHASE~~
- He should NOT turn and look at his target while applying it.
~~It should reduce Spell-Range instead of Hit-Chance.~~

_- He might be casting it a little bit to frequently, in old videos it seems to happen less often (might be subjective)_

https://www.youtube.com/watch?v=St3nFx5GD88

Now if you watch this video in general you will see that he ONLY casts two things, that is his Breath and his Fear. Distracting Ash is never actually cast, this also makes sense since he never actually turns around in the old videos which implies that is was most likely instant, like any other DoT.

**Server Revision**: 2339

**Comment by Wolffenstein** [comment]
There are 2 different types of Distracting Ash - one cast on the ground, and one cast in the air.

**Comment by Drayo** [comment]
I'm very confident that there should only be one single Spell.

The Spell with the ID: **30280** was used **BEFORE 2.1**.

The Spell with the ID: **30130** was used **AFTER 2.1**.

He never used Distracting Ash in the Air Phase, it is also not mentioned on any wiki or wowhead, Distracting Ash is exclusively attributed to the Ground Phase.

On wowwiki it says:

> Patch 2.1.0 (22-May-2007):  Nightbane was significantly retuned with no official patch note; Rain of Bones no longer follows targets, Smoking Blast damage greatly reduced, **Distracting Ash completely changed**, no longer able to fear during landing, several bugs fixed.

The part about "completely changed" describes the switch FROM **-Spell Range** TO **-Hit Chance**.

**Comment by Wolffenstein** [comment]
Both spell id's exist in 2.0 DBC and I remember seeing a video where he applied the debuff while in the air phase. I will try to find it.

**Comment by Wolffenstein** [comment]
https://www.youtube.com/watch?v=oAywfa6nuK4&feature=youtu.be&t=3m9s - there you go, Distracting Ash in the air phase.

**Comment by Drayo** [comment]
Yeah, it's true, he seems to be using it in both Phases, I never knew.
I can't tell if if he uses both versions of the Spell or just one, at least not from the Last Resort video, it's odd that the wiki mentiones the Spell being reworked if both were present from the start though.

I'll scratch that part from the initial report and just leave the casting time/targeting issue for now then.

**Comment by Wolffenstein** [comment]
Wowwiki is generally a rather poor source when it comes to anything :) It's useful to get some basic information it's quite often wrong when it comes to numerous details.

**Comment by Wolffenstein** [comment]
Fixed in rev 2342.
