### ISSUE TITLE
[NPC] [Spell] [Karazhan] Nightbane - Charred Earth

### ISSUE THREAD

**Issue by Drayo** [Atlantiss/NetherwingBugtracker#2893]
[//]: # (Enclose links to things related to the bug using http://wowhead.com or any other TBC database.)
[//]: # (You can use screenshot ingame to visual the issue.)
[//]: # (Write your tickets according to the format:)
[//]: # ([Quest][Azuremyst Isle] Red Snapper - Very Tasty!)
[//]: # ([NPC] Magistrix Erona)
[//]: # ([Spell][Mage] Fireball)
[//]: # ([Npc][Drop] Ghostclaw Lynx)
[//]: # ([Web] Armory doesnt work)
[//]: # (To find server revision type `.server info` command in the game chat.)

**Description**: 

Charred Earth has some issues.

**Current behaviour**:

He currently CASTS Charred Earth with a 1 second cast time, he LOOKS at the player it is being cast on.

**Expected behaviour**: 

- Charred Earth should NOT have a cast time, it should be instant.
- He should NOT look at the player he casts it on.

**Source**: 

https://www.youtube.com/watch?v=St3nFx5GD88

If you watch this video in general you will see that he only casts two things, his Breath and his Fear.
He never casts Charred Earth, he also never looks away from the tank, this implies that it should be an instant cast.

**Server Revision**:  2339

**Comment by Wolffenstein** [comment]
Fixed in rev 2342.
