### ISSUE TITLE
[NPC] [Hellfire Peninsula] [Jewelcrafting] Tatiana - no dialogue option

### ISSUE THREAD

**Issue by ScottieDOESknow** [Atlantiss/NetherwingBugtracker#2894]
**Description**: 

Tatiana -Master Jewelcrafting Trainer- located inside Honor Hold inn

**Current behaviour**:

Tatiana will not offer dialogue option to train jewelcrafting spells

https://gyazo.com/44f797cffcca3eda5501f611033e7dec

**Expected behaviour**: 

Tatiana should offer dialogue options for training spells and buying items

**Server Revision**: 

2339

**Comment by Fenvarien1** [comment]
Maybe check for the Horde equivalent aswell -> (horde)npc=18751 (ally)npc=18774

**Comment by aresbrutus** [comment]
Fixed in rev `Hygiea`
