### ISSUE TITLE
[NPC][Spell][2.1] Heroic Talon King Ikiss Slow

### ISSUE THREAD

**Issue by tepex0** [Atlantiss/NetherwingBugtracker#2895]
**Description**: On heroic mode, Talon King Ikiss, last boss of Sethekk Halls, casts slow on random targets. He shouldnt until patch 2.1 - http://wowwiki.wikia.com/wiki/Talon_King_Ikiss fourth paragraph under 'Heroic Mode'

"As of 2.1.0, he randomly casts Slow on the party, which lasts for around 10 seconds"

"Talon King Ikiss on Heroic difficulty has been significantly reworked. He now has a point blank area of effect slow spell, increased damage on the Arcane volley , increased damage on the Arcane Explosion, and reduced the frequency on his Polymorph." from patch 2.1 notes

**Current behaviour**: Currently casts slow on random targets

**Expected behaviour**: Shouldnt cast slow before 2.1

**Server Revision**: 2339

**Comment by Wolffenstein** [comment]
Fixed in rev 2342.
