### ISSUE TITLE
[NPC] [Spell] [Karazhan] Nightbane - Smoking Blast

### ISSUE THREAD

**Issue by Drayo** [Atlantiss/NetherwingBugtracker#2897]
[//]: # (Enclose links to things related to the bug using http://wowhead.com or any other TBC database.)
[//]: # (You can use screenshot ingame to visual the issue.)
[//]: # (Write your tickets according to the format:)
[//]: # ([Quest][Azuremyst Isle] Red Snapper - Very Tasty!)
[//]: # ([NPC] Magistrix Erona)
[//]: # ([Spell][Mage] Fireball)
[//]: # ([Npc][Drop] Ghostclaw Lynx)
[//]: # ([Web] Armory doesnt work)
[//]: # (To find server revision type `.server info` command in the game chat.)

**Description**: 

Smoking Blast has some issues.

**Current behaviour**:

He sometimes does not cast smoking blast often enough, **this might be due to him casting Distracting Ash for 1 second during his Air-Phase** ([Issue 2892](https://github.com/Atlantiss/NetherwingBugtracker/issues/2892)).

He sometimes casts only 5-7 Blasts during an entire Air-Phase.

**Expected behaviour**: 

While he is in the Air-Phase, after channeling Rain of Bones, he should cast Smoking Blast approx. once every second for about 15 seconds. (1 second cast time and a minimal delay between casts, makes for around 10-12 Hits like observed in the Sources)

**Source**:

https://youtu.be/St3nFx5GD88?t=317

In this Phase I count 11 Hits, one oddity is that sometimes two Blasts hit two different players at pretty much the same time, I don't know why this happens, it might have been a bug.

https://youtu.be/XdePecG4Ih8?t=120

This one shows around 12 casts and is dated before 2.1, so the amount of hits is not lower before the nerf.

**Server Revision**: 2339

**Comment by Wolffenstein** [comment]
Please recheck after revision 2342.
