### ISSUE TITLE
[NPC] Warbringer O'mrogg (Heroic)

### ISSUE THREAD

**Issue by Liquidsoap** [Atlantiss/NetherwingBugtracker#2898]
[//]: # (Enclose links to things related to the bug using http://wowhead.com or any other TBC database.)
[//]: # (You can use screenshot ingame to visual the issue.)
[//]: # (Write your tickets according to the format:)
[//]: # ([Quest][Azuremyst Isle] Red Snapper - Very Tasty!)
[//]: # ([NPC] Magistrix Erona)
[//]: # ([Spell][Mage] Fireball)
[//]: # ([Npc][Drop] Ghostclaw Lynx)
[//]: # ([Web] Armory doesnt work)
[//]: # (To find server revision type `.server info` command in the game chat.)

**Description**: Issue was seen in [The Shattered Halls] (heroic) while fighting the boss [Warbringer O'mrogg].
https://www.wowhead.com/npc=16809/warbringer-omrogg

**Current behaviour**: At one point during the fight [Warbringer O'mrogg] completely stopped moving, even though he continued to target player characters, and allowed us to kill him without performing any further actions.
We believe it was caused by a mage in the group blinking off the stairs toward the center of the arena (the position where the [Warbringer O'mrogg] is initially standing). We are unsure if any other events could have possibly triggered the issue.

**Expected behaviour**: [Warbringer O'mrogg] should continue chasing player characters.

**Server Revision**: Phase 3

**Comment by Easyfraggy** [comment]
probably https://github.com/Atlantiss/NetherwingBugtracker/issues/2175

**Comment by devo6969** [comment]
Duplicate #3304

**Comment by Wolffenstein** [comment]
Should be fixed.
