### ISSUE TITLE
Boss attacking my dead corpse (cant release)

### ISSUE THREAD

**Issue by Gimmedapurps** [Atlantiss/NetherwingBugtracker#2899]
[//]: # (Enclose links to things related to the bug using http://wowhead.com or any other TBC database.)
[//]: # (You can use screenshot ingame to visual the issue.)
[//]: # (Write your tickets according to the format:)
[//]: # ([Quest][Azuremyst Isle] Red Snapper - Very Tasty!)
[//]: # ([NPC] Magistrix Erona)
[//]: # ([Spell][Mage] Fireball)
[//]: # ([Npc][Drop] Ghostclaw Lynx)
[//]: # ([Web] Armory doesnt work)
[//]: # (To find server revision type `.server info` command in the game chat.)

**Description**: Maiden is attacking my dead corpse nonstop and I cannot release.

**Current behaviour**: Wiped on Maiden, **_server got restarted before I released_**. Much later log back in and shes attacking my corpse and I cannot release.

https://i.gyazo.com/a0e895dc219f1e1a19020ddc93288c2f.mp4

**Expected behaviour**: I should just be able to release.

**Server Revision**:

**Comment by The14me** [comment]
Since SSC issue was fixed, that must be ok too.
Rev 3460.
