### ISSUE TITLE
Water Death

### ISSUE THREAD

**Issue by AlteredAli** [Atlantiss/NetherwingBugtracker#29]
[//]: # (Enclose links to things related to the bug using http://wowhead.com or any other TBC database.)
[//]: # (You can use screenshot ingame to visual the issue.)
[//]: # (Write your tickets according to the format:)
[//]: # ([Quest][Azuremyst Isle] Red Snapper - Very Tasty!)
[//]: # ([NPC] Magistrix Erona)
[//]: # ([Spell][Mage] Fireball)
[//]: # ([Npc][Drop] Ghostclaw Lynx)
[//]: # ([Web] Armory doesnt work)

**Description**: 
![wowscrnshot_092318_064150](https://user-images.githubusercontent.com/43499721/45921582-d1c1ae00-befb-11e8-8d69-f559f1e2bfba.jpg)
I died in the water, and now im stuck like this and cannot move.
**Current behaviour**:

**Expected behaviour**: 

**Server Revision**:

**Comment by AlteredAli** [comment]
Update: I logged and came back fully revived, able to move

**Comment by wtRCH** [comment]
Fixed
