### ISSUE TITLE
[Dungeon]Gruul's Lair, Olm the Summoner's pet wont move when enslaved

### ISSUE THREAD

**Issue by Tenoutoften** [Atlantiss/NetherwingBugtracker#2902]
**Description**: 
[[NPC]Olm the Summoner#18834](https://www.wowhead.com/npc=18834/olm-the-summoner)'s pet [[NPC]Wild Fel Stalker#18847](https://www.wowhead.com/npc=18847/wild-fel-stalker) wouldn't move when enslaved by our warlock. Summoned by [[Spell]Summon Wild Felhunter#33131](https://www.wowhead.com/spell=33131/summon-wild-felhunter#comments)

**Expected behaviour**: 
Shouldn't stuck when enslaved

**Server Revision**: 
2339

**Comment by Easyfraggy** [comment]
Should be solved on next update.
