### ISSUE TITLE
[Dungeon][NPC]Sethekk Guard#18323 shouldn't be immune to stun

### ISSUE THREAD

**Issue by Tenoutoften** [Atlantiss/NetherwingBugtracker#2904]
**Description**: 
[[NPC]Sethekk Guard#18323](https://www.wowhead.com/npc=18323/sethekk-guard#comments)
is currently immune to stun, but shouldn't be:
![4b76e23be6dc5d1406caffe039dba69f](https://user-images.githubusercontent.com/34839199/48848098-6f721600-eda3-11e8-8900-f4711a571e88.png)

**Expected behaviour**: 
Can be seen stunned in heroic version here: https://youtu.be/6dr_ssJ5KWo?t=90 patch 2.1
Shouldn't be immune to stun.

**Server Revision**: 
2339

**Comment by Easyfraggy** [comment]
![image](https://user-images.githubusercontent.com/36134067/48897718-18c01700-ee4b-11e8-8ea6-65461f872eee.png)

I believe the guy in your comment is talking about normal mode.

**Comment by Tenoutoften** [comment]
Maybe he is but they should be stunable in heroic mode: https://youtu.be/6dr_ssJ5KWo?t=90

**Comment by Manaci** [comment]
Not a bug
