### ISSUE TITLE
[Dungeon][NPC]Sethekk Guard#18323 deals ~90% too much damage

### ISSUE THREAD

**Issue by Tenoutoften** [Atlantiss/NetherwingBugtracker#2905]
**Description**: 
Mostly blue geared warrior w/ dev aura https://youtu.be/6dr_ssJ5KWo?t=50

* No demo shout
2283 => 1945(338 blocked) 
2237
1673
1739
1641 => 1303(338 blocked)
1914 => 1606(338 blocked)
2051
2131
1676 => 1338(338 blocked)
1792 => 1454(338 blocked)

Lowest hit 1673
Highest hit 2283

* Receives Lay on Hands, still no demo shout
1726
1534
1376(338 blocked)
1481(338 blocked)
1417
1834
1673
1128(338 blocked)

NW, suspect we used demo shout
![b8eaaebabc99aee74ef41e3592657591](https://user-images.githubusercontent.com/34839199/48849286-50c14e80-eda6-11e8-9731-072299d23a9d.png)
![d77c6c07af8ebdb4e70bdc8edfedf74a](https://user-images.githubusercontent.com/34839199/48849288-50c14e80-eda6-11e8-8c71-e02afe48752f.png)
![3f693ced9a16e81007a401c15ae8b565](https://user-images.githubusercontent.com/34839199/48849289-5159e500-eda6-11e8-9447-245cd095496f.png)
![4e9f5319b9c34664169d905535c51732](https://user-images.githubusercontent.com/34839199/48849290-5159e500-eda6-11e8-874d-60a219153d03.png)

Hugmonster 13 000 armor, prot warrior
Arma 13500 armor, holy paladin

Average hit on us, 3737 damage.

(((3745 + 3729)/2) / ((1673 + 2283)/2)) ~1.89

These are currently hitting roughly 89% harder than retail(Possibly more since we might have had more armor + demo shout)

**Expected behaviour**: 
Less auto attack damage

**Server Revision**: 
2339

**Comment by Evolvee** [comment]
they do intended  melee AA dmg right now
