### ISSUE TITLE
[Racial][Blood Elf] Enchanting skill

### ISSUE THREAD

**Issue by Many12997** [Atlantiss/NetherwingBugtracker#2906]
[//]: # (Enclose links to things related to the bug using http://wowhead.com or any other TBC database.)
[//]: # (You can use screenshot ingame to visual the issue.)
[//]: # (Write your tickets according to the format:)
[//]: # ([Quest][Azuremyst Isle] Red Snapper - Very Tasty!)
[//]: # ([NPC] Magistrix Erona)
[//]: # ([Spell][Mage] Fireball)
[//]: # ([Npc][Drop] Ghostclaw Lynx)
[//]: # ([Web] Armory doesnt work)
[//]: # (To find server revision type `.server info` command in the game chat.)

**Description**: Blood Elf racial Arcane Affinity should give only +10 to enchanting skill,but in game it appears to give +20 to skill cap
**Current behaviour**:
Blood Elf enchanting skill cap is 395,so its 20 more than normal cap 375
**Expected behaviour**: 
Blood elf enchanting skill cap should be 385
![wowscrnshot_112118_142203](https://user-images.githubusercontent.com/45187634/48854265-c4b52400-edb1-11e8-864f-cfcb58b8a1fc.jpg)

**Server Revision**:

**Comment by ircfelix** [comment]
Source?

**Comment by Tenoutoften** [comment]
The tooltip itself from World of Warcraft; [[Spell]Arcane Affinity#28877](https://www.wowhead.com/spell=28877/arcane-affinity#comments)


![5c89a4f215c307ced0bed41d14ce29f9](https://user-images.githubusercontent.com/34839199/48859995-e74e3980-edbf-11e8-8d6f-b9c0bd309b8f.png)
![0cbd3a994a3a21966e4161224541b780](https://user-images.githubusercontent.com/34839199/48859963-d30a3c80-edbf-11e8-839f-a52100315adf.png)

**Comment by Tenoutoften** [comment]
Figured I'd add that when I logged in today I noticed my blood elf only had 375/375 enchanting skill, but upon unlearning and re-learning it, it went back to 395/395

**Comment by lynxzor** [comment]
Learning at the trainer the normal way takes you to level 11 as intended, maybe it's just a bug with learning from the beta NPC?
![image](https://user-images.githubusercontent.com/795881/49175403-6b646c00-f340-11e8-90ce-cd4ba7a40f97.png)

**Comment by Easyfraggy** [comment]
entirely possibly - low prio for sure.

**Comment by Manaci** [comment]
Fixed for sure
