### ISSUE TITLE
[NPC] Arcatraz Sentinel

### ISSUE THREAD

**Issue by Manaforall1** [Atlantiss/NetherwingBugtracker#2907]
[//]: # (Enclose links to things related to the bug using http://wowhead.com or any other TBC database.)
[//]: # (You can use screenshot ingame to visual the issue.)
[//]: # (Write your tickets according to the format:)
[//]: # ([Quest][Azuremyst Isle] Red Snapper - Very Tasty!)
[//]: # ([NPC] Magistrix Erona)
[//]: # ([Spell][Mage] Fireball)
[//]: # ([Npc][Drop] Ghostclaw Lynx)
[//]: # ([Web] Armory doesnt work)
[//]: # (To find server revision type `.server info` command in the game chat.)

**Description**: 
Arcatraz Sentinels do currently not use their Energy Discharge ability correctly.
**Current behaviour**:
Arcatraz Sentinels do currently not use their Energy Discharge ability until after they are dead.
The issue seems to have something to do with players in range, indicated by comment on a prior report on them: https://github.com/Atlantiss/NetherwingBugtracker/issues/2572
On that note, the threat drop was working correctly.
**Expected behaviour**: 
Arcatraz Sentinels should use their Energy Discharge ability from the point they are in range until a couple of seconds after death.
**Server Revision**: 
2339

**Comment by Easyfraggy** [comment]
You link Duplicate thread in your own post?
