### ISSUE TITLE
Big bug report (mostly warrior stuff, mob ai, and general stuff, written by Monkeynews)

### ISSUE THREAD

**Issue by arckoss** [Atlantiss/NetherwingBugtracker#2908]
This is the list of bugs that monkeynews wrote yesterday after playing on the beta (as a warrior obviously). I didn't see him report it, so I'll just put it here:

https://gyazo.com/55a95d401ac8eebbb4a86a2859c88dab

here's the clip: https://mixer.com/Monkeynews?vod=66658728

Hope it helps

**Comment by Tenoutoften** [comment]
@ blood frenzy: https://github.com/Atlantiss/NetherwingBugtracker/issues/1177

@ infernal warbringers: https://github.com/Atlantiss/NetherwingBugtracker/issues/2334

@ Health regen, what should it be, provide evidence?

@ dynamic quest object: I think these are already dynamic, but might not be very high when there arent so many around

@ view distance, it's not going to be this low

@ overpower: https://github.com/Atlantiss/NetherwingBugtracker/issues/588

@ umbrafen witchdoctors, there are few spawns https://www.wowhead.com/npc=20115/umbrafen-witchdoctor

@ Flying mount CC, can confirm entangled roots works, probably shouldn't

@ Darkcrest slaver: https://github.com/Atlantiss/NetherwingBugtracker/issues/2148 & https://github.com/Atlantiss/NetherwingBugtracker/issues/2140

@ Rajah Hagazed, didnt run super fast when I did it, he did use shield wall multiple times none of the wowhead comments say anything about it, and retail videos kill this npc too fast: https://www.wowhead.com/npc=18046/rajah-haghazed#comments

@ freezing circle https://www.wowhead.com/spell=34787/freezing-circle#comments, shouldn't be able to interrupt if barrier is up.
![9f27af2c238ffc01f1280a5204c5679d](https://user-images.githubusercontent.com/34839199/48862063-790c7580-edc5-11e8-9c2d-4224a18d8128.png)

@ Parched Hydra heat way used too often: https://github.com/Atlantiss/NetherwingBugtracker/issues/2101

**Comment by zauru7** [comment]
make 1 bug report per bug, it's impossible to keep track of bug fixes when you've got a dozen bugs in 1 report

**Comment by Evolvee** [comment]
https://www.youtube.com/watch?v=Ba6Ty72eSH8&feature=youtu.be&t=695

**Comment by Evolvee** [comment]
https://www.wowhead.com/forums&topic=111079/how-to-de-mount-someone-as-a-mage
` Also, if you can, frost nova someone on their mount.. they'll either have to eat it or get off and fight.`

**Comment by Easyfraggy** [comment]
So 10/12 are invalid or already reported. Can you repost:
Worg Master wolves keeping in combat:
Marauding crust burster bug
Rajah should only use shield wall once and on low hp in 3 seperate reports
Freezing circle keeping you in combat after mob dies.

16/20 invalid or already reported.

**Comment by Tenoutoften** [comment]
Reported the Rajah SW issue https://github.com/Atlantiss/NetherwingBugtracker/issues/2946 I don't know about the others
