### ISSUE TITLE
[General] Casting is interrupted randomly 

### ISSUE THREAD

**Issue by khaledsraira** [Atlantiss/NetherwingBugtracker#2909]
[//]: # (Enclose links to things related to the bug using http://wowhead.com or any other TBC database.)
[//]: # (You can use screenshot ingame to visual the issue.)
[//]: # (Write your tickets according to the format:)
[//]: # ([Quest][Azuremyst Isle] Red Snapper - Very Tasty!)
[//]: # ([NPC] Magistrix Erona)
[//]: # ([Spell][Mage] Fireball)
[//]: # ([Npc][Drop] Ghostclaw Lynx)
[//]: # ([Web] Armory doesnt work)
[//]: # (To find server revision type `.server info` command in the game chat.)

**Description**: Random interrupts to casting even while standing doing nothing else

**Current behaviour**: Casting can sometimes be randomly interrupted while standing still for no reason. It seems as if the more dense the area is (i.e the more players in the local area), the more frequent the interrupts. Less interruptions going to areas with less players. This includes casting for crafting as well, and is more noticeable while crafting due to the long cast time for crafting certain items. The error "Can't do that while moving" sometimes pops up even though I am not moving. 

**Expected behaviour**: There shouldn't be any interrupts randomly happening.

**Server Revision**:

**Comment by Peglaa** [comment]
Can confirm, happened to me once while I was applying an enchant.

**Comment by sandreid** [comment]
It seems to happen when other players run close to you.

**Comment by knasen88** [comment]
can confirm, seems more frequent among other people, so raiding-wise this would seem particularly bad.

**Comment by mhdemn** [comment]
Joining or leaving a raid or a party will interrupt it too. Noticed it while crafting, even though it feels like overall it gets interrupted less now, and when it happens I just walk forward a step and craft without further issues.

**Comment by raethkcj** [comment]
Happens very often on Amani Lynx packs in ZA.

**Comment by Easyfraggy** [comment]
This issue is outdated and already fixed like a year ago, it turned out to be when someone would mount on a flying mount near you. So the issue with amani lynx is new, can you give more info, preferably a video?

**Comment by raethkcj** [comment]
Created new issue #6936 with video
