### ISSUE TITLE
[spell][core mechanic]Hunter's mark is not being applied to specific mobs in west sanctum.

### ISSUE THREAD

**Issue by queeb3** [Atlantiss/NetherwingBugtracker#291]
**Description**: 
so when I try to apply my hunter's mark to specific enemies like the mana stalkers and mana wraiths near Silvermoon, it uses the mana and says that it was used, but no mark appears nor do they get the debuff.
**Current behavior**:
Hunters mark is not applied even though it is shown as it was.
**Expected behavior**: 
Hunter's mark should show up above the target and give them the specified debuff from said ability.
**Server Revision**:

**Comment by knasen88** [comment]
it's an arcane spell and they're immune to arcane

**Comment by Gniddikon** [comment]
They are immune to hunters mark which is blizzlike and working correctly.
