### ISSUE TITLE
[Hunter] [Spell-Talent] Hunter's Mark - Improved HM from different hunters

### ISSUE THREAD

**Issue by mhdemn** [Atlantiss/NetherwingBugtracker#2910]
rev 2344

Reporting this here since #2339 is a bit too crowded.

Talent [Improved Hunter's Mark](https://db.excalibur.ws/?spell=19425) enhances the hunter's HM so melee attackers' AP is also boosted.

**Current behaviour**:
- Any hunter can overwrite other allied hunters' Hunter's Mark.
  - Furthermore, you can overwrite a talent-enhanced Hunter's Mark with your 0/5 Hunter's Mark. 

**Expected behaviour**:
- A talent-enhanced Hunter's Mark should overwrite a worse version of Hunter's Mark, as in **5/5HM>4/5HM>3/5HM>2/5HM>1/5HM>0/5HM**
  - All the same, a worse or equal version of HM shouldn't be able to overwrite HM -unless it's an equal HM from the hunter that casted the currently active HM-.
- And "a more powerful effect is already active" errors for the situations above.

I believe these comments from WotLK prepatch back up my position, but I will try to find some video proof if needed (_please don't make me :<_)

![image](https://user-images.githubusercontent.com/25901582/48867473-8d0ca300-edd6-11e8-91d4-48f90fa1e481.png)

![image](https://user-images.githubusercontent.com/25901582/48867481-9138c080-edd6-11e8-8af3-bf21c2b24a33.png)

https://www.wowhead.com/forums&topic=42682 / https://www.wowhead.com/forums&topic=49530

**Comment by Godmatik** [comment]
Was fixed
