### ISSUE TITLE
Doom Lord Kazzak Enrage

### ISSUE THREAD

**Issue by itsjojotbh** [Atlantiss/NetherwingBugtracker#2911]
[//]: # (Enclose links to things related to the bug using http://wowhead.com or any other TBC database.)
[//]: # (You can use screenshot ingame to visual the issue.)
[//]: # (Write your tickets according to the format:)
[//]: # ([Quest][Azuremyst Isle] Red Snapper - Very Tasty!)
[//]: # ([NPC] Magistrix Erona)
[//]: # ([Spell][Mage] Fireball)
[//]: # ([Npc][Drop] Ghostclaw Lynx)
[//]: # ([Web] Armory doesnt work)
[//]: # (To find server revision type `.server info` command in the game chat.)

**Description**: 
Doom Lord Kazzak doesn't always spam Shadow Bolt volley at the enrage at low health
**Current behaviour**:
See above
**Expected behaviour**: 
Should chain cast Shadow Bolt Volley until killed or wiping the raid
**Server Revision**:

**Comment by tcberk12** [comment]
https://www.youtube.com/watch?v=jf51zsgl-FA

Looks like the enrage should happen between 50-60 seconds after pull. In the link, the pull is at 1:04 (and the boss mod indicates that enrage is in 50-60 seconds). The first enrage comes 58 seconds later at 2:02

8 seconds later, the enrage ends and you can see the boss mod indicate that the enrage occurs again in another 50-60 minute window

**Comment by Evolvee** [comment]
rev kazzak
