### ISSUE TITLE
[Paladin] [spell] Divine Intervention

### ISSUE THREAD

**Issue by Homiecup** [Atlantiss/NetherwingBugtracker#2912]
**Description**:
https://clips.twitch.tv/PowerfulCrunchyBeeGrammarKing
I use divine intervention but it doesn't kill me, just taking 50% hp and giving the target the divine intervention buff.

**Current behaviour**:
Most of the time it works and kills the user, but in some cases it just deals half the users health but still gives the other target the effect.

**Expected behaviour**: 
The paladin uses divine intervention and kills himself to give a person in group a buff where they are immune to all dmg for 3min but can't do any actions

**Server Revision**: 
2345

**Comment by Erodraeda** [comment]
Do you have the talent Blessed Life, from the holy tree? it might be some interaction with that

**Comment by Homiecup** [comment]
Yeah i have blessed life, sounds like that could very well be the issue.

**Comment by devo6969** [comment]
Tried to even recreate it to make sure, seems fixed
#6177 duplicate
