### ISSUE TITLE
[Quest][Black Morass] The Opening of the Dark Portal

### ISSUE THREAD

**Issue by Brasso** [Atlantiss/NetherwingBugtracker#2914]
[//]: # (Enclose links to things related to the bug using http://wowhead.com or any other TBC database.)
[//]: # (You can use screenshot ingame to visual the issue.)
[//]: # (Write your tickets according to the format:)
[//]: # ([Quest][Azuremyst Isle] Red Snapper - Very Tasty!)
[//]: # ([NPC] Magistrix Erona)
[//]: # ([Spell][Mage] Fireball)
[//]: # ([Npc][Drop] Ghostclaw Lynx)
[//]: # ([Web] Armory doesnt work)
[//]: # (To find server revision type `.server info` command in the game chat.)

**Current behaviour**:
You cannot complete the quest back at the quest giver in heroic difficulty, if you run out and switch to normal mode it works fine.

**Server Revision**: 
2345

**Comment by ScottieDOESknow** [comment]
Can confirm unable to complete quest on heroic difficulty.
https://gyazo.com/4bb95f3caa99d1b43489adfaf5860489
Switched difficulty to normal and NPC offers completion.

**Comment by The14me** [comment]
Reset Dungeon fix the issue...but still, there is an issue.

**Comment by wtRCH** [comment]
Fixed? @danbopes
