### ISSUE TITLE
[Dungeon] Mana-Tombs HC [NPC] Ethereal Crypt Raider {skill} Charge

### ISSUE THREAD

**Issue by Zebhor** [Atlantiss/NetherwingBugtracker#2915]
[//]: # (Enclose links to things related to the bug using http://wowhead.com or any other TBC database.)
[//]: # (You can use screenshot ingame to visual the issue.)
[//]: # (Write your tickets according to the format:)
[//]: # ([Quest][Azuremyst Isle] Red Snapper - Very Tasty!)
[//]: # ([NPC] Magistrix Erona)
[//]: # ([Spell][Mage] Fireball)
[//]: # ([Npc][Drop] Ghostclaw Lynx)
[//]: # ([Web] Armory doesnt work)
[//]: # (To find server revision type `.server info` command in the game chat.)

**Description**: 
Ethereal Crypt Raider used 4 times in less than 0.1 charge against 1 person.
**Current behaviour**:
He use more than 1 charge per person. Healer received 4 hits 2,2k each and instant died by this skill.
<a href="https://imgur.com/ZYH7khz"><img src="https://i.imgur.com/ZYH7khz.jpg" title="source: imgur.com" /></a>
<a href="https://imgur.com/s8fPtZJ"><img src="https://i.imgur.com/s8fPtZJ.jpg" title="source: imgur.com" /></a>
**Expected behaviour**: 
He should use 1 charge then back to tank or person with high aggro then use next charge.
**Server Revision**: 
2345

**Comment by devo6969** [comment]
Tried to recreate this, tried multiple times on different Ethereal Crypt Raiders. Would only cast one charge as intended
