### ISSUE TITLE
[Quest][Tanaris] The Caverns of Time

### ISSUE THREAD

**Issue by Saben65** [Atlantiss/NetherwingBugtracker#2916]
**Description**: 
The Custodian of Time (

**Current behaviour**:

**Expected behaviour**: 

**Server Revision**: 
203

**Comment by The14me** [comment]
Can u add any info about the problem please? if not ill just close the report.ty!

**Comment by The14me** [comment]
https://github.com/Atlantiss/NetherwingBugtracker/issues/2917
