### ISSUE TITLE
[NPC][Karazhan] Terestian Illhoof's Sacrifice

### ISSUE THREAD

**Issue by Brasso** [Atlantiss/NetherwingBugtracker#2918]
[//]: # (Enclose links to things related to the bug using http://wowhead.com or any other TBC database.)
[//]: # (You can use screenshot ingame to visual the issue.)
[//]: # (Write your tickets according to the format:)
[//]: # ([Quest][Azuremyst Isle] Red Snapper - Very Tasty!)
[//]: # ([NPC] Magistrix Erona)
[//]: # ([Spell][Mage] Fireball)
[//]: # ([Npc][Drop] Ghostclaw Lynx)
[//]: # ([Web] Armory doesnt work)
[//]: # (To find server revision type `.server info` command in the game chat.)

**Description**: 
Terestian Illhoof's Sacrifice can sometimes set a player's hp to a very low amount, killing him after the first tick of damage. Only happens sometimes. 
**Current behaviour**:
After first wipe, the Sacrifice worked properly. 
https://clips.twitch.tv/VictoriousRoughRamenDeIlluminati
First Sacrifice worked, second Sacrifice did it.
https://clips.twitch.tv/ShortLongHamburgerPupper

**Server Revision**: 
2338

**Comment by Easyfraggy** [comment]
Issue about same spell: https://github.com/Atlantiss/NetherwingBugtracker/issues/2943

**Comment by Manaci** [comment]
Fixed

**Comment by Manaci** [comment]
Fixed
