### ISSUE TITLE
[Spell] Resurrection Sickness - 15007

### ISSUE THREAD

**Issue by Scylla420** [Atlantiss/NetherwingBugtracker#292]
**Description**: 
Resurrection Sickness' duration should not decrease when you log out.  You should log back in to the same time left on the debuff as when you logged out.
**Current behaviour**:
[Before logout](https://cdn.discordapp.com/attachments/372465548950241280/493541483333287946/unknown.png)
[10 mins later logging back in the debuff is gone.](https://cdn.discordapp.com/attachments/372465548950241280/493543910585532416/unknown.png)
**Expected behaviour**: 
Rez sickness should have had 4 mins and 46 secs remaining when I logged back in.
[Source 1](http://wowwiki.wikia.com/wiki/Resurrection_Sickness?oldid=2294402)
> Unlike other debuffs, this won't get off the character while you are logged out.

[Source 2](https://www.wowhead.com/spell=15007/resurrection-sickness)

> This is possibly one of the more idiotic things Blizz decided on. I can't count how many time I've been force to just sit and do absolutely nothing waiting for this damn thing to go away while I could spend the 10 mins doing anything thing else on another toon.

> This debuff persist through logging out even.
So I've your like me thinking, well let's do something different, like play with an alt, and turn back into your character with ress sickness, you'll be ackwardly surprised, the debuff is still there!
So if you have it, stay logged in on the character with the debuff to get rid of it.

**Server Revision**: 
2037

**Comment by Wolffenstein** [comment]
Fixed in rev 2038.
