### ISSUE TITLE
[Dungeon][The Slave Pens] Hunter can not solo Mennu the Betrayer

### ISSUE THREAD

**Issue by ayrb13** [Atlantiss/NetherwingBugtracker#2920]
**Description**: 
Hunter can solo the first boss in official TBC server.
**Current behaviour**:
When i stand on the step, the mobs can hit me straightly instead of taking a detour
**Expected behaviour**: 
the mobs should take a detour to hit me when i stand on the step
**Server Revision**:

**Comment by wtRCH** [comment]
Example:
https://www.youtube.com/watch?v=i2jTGb0B5_E
(2008)

**Comment by ayrb13** [comment]
3rd boss of SP also can be killed by hunter
Proof:
https://www.youtube.com/watch?v=Ki61EujNcg4
(2008)
