### ISSUE TITLE
Chests are not spawning. 

### ISSUE THREAD

**Issue by Noxvice** [Atlantiss/NetherwingBugtracker#2922]
I have spent 3-4 hours now flying around outland camps and caves looking for chests, just to see if what people were saying on disc was right. So far I have yet to see a single one. 
Been through BEM, Nagrand, Netherstorm and Zanga. I will keep flying, but for now it seems like there are no chests spawning in the open world, or I might be serioursly out of luck. 

Like I said I might be serioursly out of luck, decided to report anyways. 

Not sure what to link, euhm.. The envoirment is working amazing in regards to flying and jumping on things ;)

**Comment by Manaci** [comment]
Intentionally removed
