### ISSUE TITLE
[NPC] Bladespire Enforcer/Ravager/Battlemage

### ISSUE THREAD

**Issue by AxeCell** [Atlantiss/NetherwingBugtracker#2923]
**Description**: 
The Bladespire Enforcers, Ravagers and Battlemages can be found patrolling outside Gruul's Lair.

**Current behaviour**:
Some of the mobs are standing where they should be standing, but others are not patrolling correctly. They simply stack close to or on top of other NPCs.

**Expected behaviour**: 
Some of these mobs should patrol to make the zone more ardeous and immersive.
Here's proof with a Bladespire Enforcer patrolling up a tower: https://youtu.be/IPinkYtXCv8?t=16

**Server Revision**: 
2345

**Comment by Easyfraggy** [comment]
I didn't correct the elite ogres in my remake of BEM - Need wolf to fix sniffs so we can complete the rest of the areas.
