### ISSUE TITLE
[Quest] A Nessecary Distraction

### ISSUE THREAD

**Issue by AxeCell** [Atlantiss/NetherwingBugtracker#2925]
**Description**: 
Exarch Onaala wants you to return to the Ruins of Karabor and find a way to unleash Azaloth on his captors.
Larissa Sunstrike wants you to return to the Ruins of Karabor and find a way to unleash Azaloth on his captors

**Current behaviour**:
The Sunfury Warlocks standing around Azaloth are not channeling any spell, and I once caught them being aggroed to him while he was banished.

**Expected behaviour**: 
Should channel spells unto Azaloth to suppress him. Once released they should again aggro to him.

**Server Revision**: 
2345

**Comment by Easyfraggy** [comment]
This has been bugged and working on/off over the last 6 months.

**Comment by Evolvee** [comment]
https://github.com/Atlantiss/AtlantissTbcBTOLD/issues/644
https://github.com/Atlantiss/AtlantissTBCBT/issues/3071
https://github.com/Atlantiss/AtlantissTbcBTOLD/issues/1818

**Comment by Evolvee** [comment]
rev ggx
