### ISSUE TITLE
Able to melee through obstacles

### ISSUE THREAD

**Issue by Nicemann1089** [Atlantiss/NetherwingBugtracker#2928]
[//]: # (Enclose links to things related to the bug using http://wowhead.com or any other TBC database.)
[//]: # (You can use screenshot ingame to visual the issue.)
[//]: # (Write your tickets according to the format:)
[//]: # ([Quest][Azuremyst Isle] Red Snapper - Very Tasty!)
[//]: # ([NPC] Magistrix Erona)
[//]: # ([Spell][Mage] Fireball)
[//]: # ([Npc][Drop] Ghostclaw Lynx)
[//]: # ([Web] Armory doesnt work)
[//]: # (To find server revision type `.server info` command in the game chat.)

**Description**: Just heard someone talking about being able to melee through pillars in arena at least. He was just whining about it, so I guess he forgot that he is participating in a beta. I do not think he will report that bug, so I will.

**Server Revision**: 2345

**Comment by The14me** [comment]
well ok....but will be good to bring some proof about it.

**Comment by nuiva** [comment]
This is blizzlike, see https://www.youtube.com/watch?v=xjMRzrCOo2w at 0:50.

**Comment by Easyfraggy** [comment]
Only autoattack works through LOS - using skills require LOS.

Blizzlike.
