### ISSUE TITLE
[npc] [pet] enemies with pets and their relation

### ISSUE THREAD

**Issue by knasen88** [Atlantiss/NetherwingBugtracker#293]
[//]: # (Enclose links to things related to the bug using http://wowhead.com or any other TBC database.)
[//]: # (You can use screenshot ingame to visual the issue.)
[//]: # (Write your tickets according to the format:)
[//]: # ([Quest][Azuremyst Isle] Red Snapper - Very Tasty!)
[//]: # ([NPC] Magistrix Erona)
[//]: # ([Spell][Mage] Fireball)
[//]: # ([Npc][Drop] Ghostclaw Lynx)
[//]: # ([Web] Armory doesnt work)

**Description**: 
they're not really linked, you can kill the master as long as you stay out of pullrange of the pet they have.
The pet also does not give XP at all (they should)
**Current behaviour**:
https://streamable.com/ox0jq illustrated here
**Expected behaviour**: 
they should aggro the same target that aggros the owner.
**Server Revision**:

**Comment by Tenoutoften** [comment]
1. fairly certain the xp issue is solved after revisions in phase 2
2. The NPC you attacked seems to be under the effects of https://github.com/Atlantiss/NetherwingBugtracker/issues/192 which has been fixed.

In server rev 2395 it works like this:
* One shotting the master at ~40 yards despawns pet 
* One shotting the pet at ~40 yards kills the pet => Master wont re-summon another one(Waited until corpse despawned and then some)
* If you pull without one shotting they will both react, and both leech at the same time
* The pet is still regaining health slowly, as if it was a regularly owned player pet(Should probably regain much faster)

**Comment by Tenoutoften** [comment]
NPC#3265, ID6 with pet#3939 in barrens which leeches differently. Master will leech significantly earlier, the pet will keep chasing until it is despawned which happens a bit after the master has leecher(But before he reaches his spot)

Once he is back on his spot he will resummon the pet: https://youtu.be/sdXBXoMWoFE

**Comment by Godmatik** [comment]
All of these issues appear fixed
