### ISSUE TITLE
[Priest][Spell] Pain Suppression puts you in combat forever

### ISSUE THREAD

**Issue by Nicemann1089** [Atlantiss/NetherwingBugtracker#2930]
[//]: # (Enclose links to things related to the bug using http://wowhead.com or any other TBC database.)
[//]: # (You can use screenshot ingame to visual the issue.)
[//]: # (Write your tickets according to the format:)
[//]: # ([Quest][Azuremyst Isle] Red Snapper - Very Tasty!)
[//]: # ([NPC] Magistrix Erona)
[//]: # ([Spell][Mage] Fireball)
[//]: # ([Npc][Drop] Ghostclaw Lynx)
[//]: # ([Web] Armory doesnt work)
[//]: # (To find server revision type `.server info` command in the game chat.)

**Description**: A guy wrote in chat, that if you cast Pain Suppression on someone, you are combat locked for the whole time. I again do not think these guys report it, so I do.

**Server Revision**: 2345

**Comment by Easyfraggy** [comment]
Need replication steps and video of it bugging out like this.

**Comment by Wolffenstein** [comment]
Not enough info.
