### ISSUE TITLE
[Item][Enchant] Golden & Runic Spellthread, Nethercobra & Nethercleft Leg Armor

### ISSUE THREAD

**Issue by Saben65** [Atlantiss/NetherwingBugtracker#2932]
**Description**: 
Golden and Runic spellthread were slightly buffed in [Patch 2.1](http://wowwiki.wikia.com/wiki/Patch_2.1.0). Look under "Additional Profession Changes" for golden spellthread and under "Leatherworking" for nethercobra.

**Current behaviour**:
Golden and Runic spellthread are at their post 2.1 levels.
Golden Spellthread: +66 Healing, +20 Stam
Runic Spellthread: +35 Spell Damage, +20 Stam
Nethercleft Leg Armor: +12 Agility, +40 Stam
Nethercobra Leg Armor:  +50 AP, +12 Crit

**Expected behaviour**: 
Pre 2.1 their stats should be
[Golden Spellthread](http://wowwiki.wikia.com/wiki/Golden_Spellthread?oldid=596345): +51 Healing, +18 Stam
[Runic Spellthread](http://wowwiki.wikia.com/wiki/Runic_Spellthread?oldid=596346): +27 Spell Damage, +18 Stam
[Nethercleft Leg Armor](http://wowwiki.wikia.com/wiki/Nethercleft_Leg_Armor?oldid=497277): +12 Agility, +35 Stam
[Nethercobra Leg Armor](http://wowwiki.wikia.com/wiki/Nethercobra_Leg_Armor?oldid=611239): +45 AP, +12 Crit

**Server Revision**: 
2349

**Comment by aresbrutus** [comment]
Sadly the spell effects themselves got changed with the 2.1 patch so unless we go back to an old client there is not much we can do about these items.
