### ISSUE TITLE
[Proffesion]Engineering UI

### ISSUE THREAD

**Issue by DeltaLoads** [Atlantiss/NetherwingBugtracker#2933]
[//]: # (Enclose links to things related to the bug using http://wowhead.com or any other TBC database.)
[//]: # (You can use screenshot ingame to visual the issue.)
[//]: # (Write your tickets according to the format:)
[//]: # ([Quest][Azuremyst Isle] Red Snapper - Very Tasty!)
[//]: # ([NPC] Magistrix Erona)
[//]: # ([Spell][Mage] Fireball)
[//]: # ([Npc][Drop] Ghostclaw Lynx)
[//]: # ([Web] Armory doesnt work)
[//]: # (To find server revision type `.server info` command in the game chat.)

**Description**: 
Engineering UI is bugged when you learn all patterns from trainer, same problem as with Leatherworking, also Magnified Moon Specs(https://www.wowhead.com/item=32480/magnified-moon-specs) can be learned from trainer even if it was added on patch 2.1
![wowscrnshot_112218_201623](https://user-images.githubusercontent.com/43690147/48919536-9a3b9780-ee93-11e8-8873-a1742e09f1a6.jpg)

**Current behaviour**:
Engineering UI is bugged, patterns from later patches can be learned from trainers
**Expected behaviour**: 
Working UI and only 2.0 patterns
**Server Revision**: 
2349

**Comment by aresbrutus** [comment]
Fixed in rev `Aterpol`

Make sure to re-learn engineering after the server is updated with this rev.
