### ISSUE TITLE
Shattered Halls Heroic issue

### ISSUE THREAD

**Issue by justicex123** [Atlantiss/NetherwingBugtracker#2934]
[//]: # (Enclose links to things related to the bug using http://wowhead.com or any other TBC database.)
[//]: # (You can use screenshot ingame to visual the issue.)
[//]: # (Write your tickets according to the format:)
[//]: # ([Quest][Azuremyst Isle] Red Snapper - Very Tasty!)
[//]: # ([NPC] Magistrix Erona)
[//]: # ([Spell][Mage] Fireball)
[//]: # ([Npc][Drop] Ghostclaw Lynx)
[//]: # ([Web] Armory doesnt work)
[//]: # (To find server revision type `.server info` command in the game chat.)

**Description**: 
I lost my timed debuff when I used Ice Block
**Current behaviour**:
https://clips.twitch.tv/ClumsyKathishCaterpillarANELE
**Expected behaviour**: 

**Server Revision**:

**Comment by Easyfraggy** [comment]
Same with bubble - you can still complete the event/quest and if you die and reenter you get the timer back.

**Comment by Mikik3jr** [comment]
[In this video](https://www.youtube.com/watch?v=PvMfIQFPPI8) at 4:40 you can see that the mage (bottom one in party frame) uses ice block, and removes the timer.

**Comment by Easyfraggy** [comment]
So this is actually blizzlike? Actually one of the few retail bugs where I don't really mind if they got fixed but this is EXTREMELY low prio.
