### ISSUE TITLE
[Dungeon][The Slave Pens][NPC][Spell] Coilfang Soothsayer - Domination

### ISSUE THREAD

**Issue by killablink** [Atlantiss/NetherwingBugtracker#2935]
**Description**: Not sure if it's correct or not, but you currently can't undead racial out of the domination. On wowhead comments from 2.0 they only talked about how it's not dispellable but I'm not sure if it's also meant to not be dispellable by WOTF

**Current behaviour**: ^

**Expected behaviour**: Not sure if UD racial should be usable

**Server Revision**: 2349

**Comment by Bleachlol** [comment]
This is what I have found regarding WoTF, although, I have not tested to Mass dispel the mc (should be able to according to comments), but I think the Gms can test rather easy. 

By Allyn (259 – 1·4) on 2007/03/01 (Patch 2.0.8)
**Didn't seem to be any change between normal and heroic, except for upscaled damage. Melee hits for about 2k, knockback for about 1.5k. MC on the tank is still dangerous - and is undispellable, nor can you use Will of the Forsaken to break it - but nothing too major. Not too difficult on the whole.**
(Source: https://www.wowhead.com/npc=17381/the-maker#comments) 


By Minxette (2,704 – 1·3·14) on 2007/04/14 (Patch 2.0.12)
**In heroic can mc multiple times. This cannot be dispelled but can be mass dispelled.**

(Source: https://www.wowhead.com/npc=17381/the-maker#comments)

**Comment by killablink** [comment]
That isn't the same mob

**Comment by Bleachlol** [comment]
Its not the same mob no, but if you look at the ability, you can clearly see that it casts only by 2 mobs, that boss and the coilfang soothslayer. 
Source: https://www.wowhead.com/spell=30923/domination

**Comment by Easyfraggy** [comment]
Same spell will work the same way - only thing you can change between mobs using it is targetting and cooldown afaik.

**Comment by aresbrutus** [comment]
WOTF should not get you out + mass dispell is not dispelling as it should not.
