### ISSUE TITLE
[Mage][Spell] Presence of Mind bugged

### ISSUE THREAD

**Issue by ircfelix** [Atlantiss/NetherwingBugtracker#2936]
**Description**: 
Presence of Mind should make your next non-channeled spell with less than 10s cast time instant.

**Current behaviour**:
Sometimes it doesn't make the next spell instant (still has a cast time) or when using a spell, the presence of mind aura is consumed and nothing happens. Sometimes it works as intended and makes the next spell an instant.

**Expected behaviour**: 
Presence of Mind should make your next non-channeled spell with less than 10s cast time instant.

**Server Revision**: 
2349

**Comment by Easyfraggy** [comment]
Think this was already reported?

**Comment by ircfelix** [comment]
Search showed nothing

**Comment by Easyfraggy** [comment]
Yeah I can't find it either - I just remember reading this exact bug before - maybe deja vu

**Comment by xmesaj2** [comment]
Can you provide example spells that doesn't work with it? Or it does (not) work randomly with the same spell?

**Comment by ircfelix** [comment]
I tried to conjure water with it, which did not work.

**Comment by xmesaj2** [comment]
rev 2356
