### ISSUE TITLE
[Item] Primalstrike Set Bonus

### ISSUE THREAD

**Issue by Saben65** [Atlantiss/NetherwingBugtracker#2937]
**Description**: 
In Patch 2.1 blizzard changed the set bonus of the Primalstrike [Vest](https://www.wowhead.com/item=29525/primalstrike-vest),[ Bracers](https://www.wowhead.com/item=29527/primalstrike-bracers), and [Belt](https://www.wowhead.com/item=29526/primalstrike-belt) to give AP instead of Strength. 

> Leatherworking made Primalstrike set now has an attack power set bonus rather than a strength set bonus.

**Current behaviour**:
Set bonus is currently +40 AP.

**Expected behaviour**: 
Set bonus should be [+20 Strength](https://web.archive.org/web/20070312055629/http://www.thottbot.com:80/i29525).

**Server Revision**: 
2349

**Comment by aresbrutus** [comment]
As much as we would like, we can not change spell bonus of sets like these to pre-2.1 version.
