### ISSUE TITLE
Paladin vengeance seal not working correctly with reckoning proc

### ISSUE THREAD

**Issue by Helmsley** [Atlantiss/NetherwingBugtracker#2938]
[//]: # (Enclose links to things related to the bug using http://wowhead.com or any other TBC database.)
[//]: # (You can use screenshot ingame to visual the issue.)
[//]: # (Write your tickets according to the format:)
[//]: # ([Quest][Azuremyst Isle] Red Snapper - Very Tasty!)
[//]: # ([NPC] Magistrix Erona)
[//]: # ([Spell][Mage] Fireball)
[//]: # ([Npc][Drop] Ghostclaw Lynx)
[//]: # ([Web] Armory doesnt work)
[//]: # (To find server revision type `.server info` command in the game chat.)

**Description**: 
Theres a problem the way reckoning proc is supposed to work with seal of vengeance
**Current behaviour**:
The current behavior when stacking vengeance dot while reckoning is up seems to stack twice on one melee hit when seal of vengeance procs but doesnt do the times 2 vengeance damage on hit.
**Expected behaviour**: 
While hitting a mob with seal of vengeance active and reckoning up one melee hit should stack vengeance twice and give 2 melee swing of vengeance damage on hit on top of the dot. ( When vengeance procs on hit)
**Server Revision**:

**Comment by tcberk12** [comment]
https://www.mmo-champion.com/threads/670068-reckoning-SoC

> Throughout TBC, Reckoning would not proc any seal damage of any kind. This included Seal of Vengeance, Blood and Command.

I think that refutes this claim? Though I'm not sure exactly what OP is attempting to say.

**Comment by Helmsley** [comment]
what i mean is seal of vengenace does 2 type of damage, theres a dot that can stack 5 times and once u stack vengeance 5 times u do vengeance damage on melee attack (when it procs and resets timer) what im saying is that  that vengeance damage isnt working with reckoning like it sould because u do double swings so when u get a vengenace proc when the 5 stacks are up u should get 2 swings worth on vengenace damage on hit (when it procs on hit).... its working fine when im not at full stacks i get 2 stacks on 1 swing  when reckoninig is up when vengeance procs. the same should happen when fully stacked... meaning vengeance should do 2 swings worth on vengeance damage on hit.ty

**Comment by Tereneckla** [comment]
Reckoning works with all other seals (apart from command, but that's intended)
No double Vengeance after 10 minutes of testing of testing on mobs 30 level lower than me.

**Comment by torrenzGH** [comment]
idk if SoV should work with reck or not but the current behavior is a strange inbetween. you can get 2x DoT stack, you can go from 4 stacks to 5 _and_ get 1x instant damage, but you can't ever get 2 instants at 5 stacks.

https://wowwiki.fandom.com/wiki/Patch_2.2.0
>Seal of Vengeance duration increased to 15 seconds. In addition, when Seal of Vengeance strikes a target that already has 5 applications you will cause instant Holy damage. 

confusingly, ingame the stacking DoT is called _holy vengeance_. the new instant holy damage effect was also called _seal of vengeance_, and probably has a separate cooldown right now that stops it from working with reck.

**Comment by Godmatik** [comment]
Rev 4018 - something to watch for with the upcoming weapon procs rework

**Comment by Godmatik** [comment]
Fixed with upcoming proc branch update
