### ISSUE TITLE
[Dungeon] Mechanar - Initial pulls bug you in combat

### ISSUE THREAD

**Issue by mhdemn** [Atlantiss/NetherwingBugtracker#2939]
**Description**: It seems the few packs at the start of The Mechanar always leave the group bugged in combat. The common aspect to these few packs is that they all have a [Sunseeker Netherbinder](https://db.excalibur.ws/?npc=21541) in them, their summoned [Arcane Servant](https://db.excalibur.ws/?npc=21521)s might be responsible.

Some attribute this bug to any pet from party members - I haven't been able to confirm it, after getting bugged all the same after fights with my pet dismissed or dismissing it while bugged in combat.

**Server Revision**: 2339 when noticed, 2349 currently --> I think it's still happening

**Comment by Easyfraggy** [comment]
Can't replicate - related to the pet agro bug?

**Comment by Mikik3jr** [comment]
Yeah I reported that every time at the begining of the mechanar after the robot patroler fight I stuck in combat until the hunter/warlock dismisses their pet.

**Comment by mhdemn** [comment]
> Yeah I reported that every time at the begining of the mechanar after the robot patroler fight I stuck in combat until the hunter/warlock dismisses their pet.

Will try to capture it, but even after I lost the recording I remember clearly dismissing it to exit combat after 2nd pack was killed, but not exiting combat - which confuses me, since dismissing the pet to debug combat after 1st pack worked just a minute ago.

**Comment by Tenoutoften** [comment]
We need a retest
[2349][Core] Threat Fixes - 2018 / 11 / 22
- Fixed a combat-bug issue caused by certain AoE spells, making the players stuck in combat with their pets

**Comment by aresbrutus** [comment]
Think this was fixed, dm me if not.
