### ISSUE TITLE
Unlimited Aggro Range [Frostmane Troll]

### ISSUE THREAD

**Issue by DoctorRaymos** [Atlantiss/NetherwingBugtracker#294]
Not sure if this is for this mob only, or a larger issue.

https://imgur.com/a/wGxyYyQ

Recreation steps : All I did was start aggro in range, walk backwards and continue to let it hit me. As shown in picture, I brought it all the way to the starting area in Coldridge Valley, and a guard came and killed it. Extremely far distance for aggro!

**Comment by Godmatik** [comment]
It's a known issue with Frost Armor

**Comment by wtRCH** [comment]
It's due to mage Frost Amor.
More here: https://github.com/Atlantiss/NetherwingBugtracker/issues/253
