### ISSUE TITLE
[NPC] Bloodwarder Slayers inside HC Mechanar have too much damage

### ISSUE THREAD

**Issue by mhdemn** [Atlantiss/NetherwingBugtracker#2941]
**Description**:  [Bloodwarder Slayer](https://db.excalibur.ws/?npc=21524).
- Looking at his spells and stats, and taking for example a copy I made of my combat log (Sorry I didn't keep a screenshot) where one of these hit my hunter in full mail gear (around 33% phys damage reduction) for 3.2k white damage + 6.4k Solar Strike damage (white was a crit, Solar wasn't) in the same batch, I'm inclined to think he's way too strong: See the math (excalibur DB as source):

  - His average damage is 2589.5 without any reductions applied, a crit would hit for twice that amount, then reduced by a 1/3 we'd be looking at around 3.4k damage --> Correct.

  - Problem is his Solar Strike (and his Mortal Strike too) gets its damage from thrice the weapon's damage and not the character's damage. I have no idea what damage these guys' weapons have, but even if I'm not correct to assume they have some AP too besides their weapon, numbers don't add up, since 3 times their max damage -2849 · 3- reduced by 33% (from armor) result in 5,698.

Maths aside, it stands out that defense capped tanks in heroic dung BiS gear get melted by these. They also **could be using them with a higher frequency than they should**, but I couldn't keep track of this since you don't live long enough to test it / you're forced to burst them in a CC chain.

**Expected behaviour**: I guess their damage after calculations and their weapon damage should be different variables when calculating the damage of their various attacks.

**Server Revision**: 2339 when noticed, reposted in 2349 --> I think they haven't got touched since.

**Comment by Easyfraggy** [comment]
Hes doing 1k dps on 11k armor with 10% parry 10% dodge. Doesn't seem extreme to me - maybe just a bit bursty? His base damage is actually lower than it should be atm.

**Comment by mhdemn** [comment]
I'll make sure to hit record next time I fight these, but I'd def say there is something fishy about them.
Maybe I got a crushing blow or something, dunno what I did with the screenshots I took.

**Comment by Easyfraggy** [comment]
![image](https://user-images.githubusercontent.com/36134067/48923521-8e5dce80-eeaf-11e8-8c2b-f9d4ae3cb2ec.png)

I let him beat me for a while with:

![image](https://user-images.githubusercontent.com/36134067/48923529-9a499080-eeaf-11e8-9834-5cca81d85321.png)

**Comment by mhdemn** [comment]
If you could test it with my armor

![image](https://user-images.githubusercontent.com/25901582/48923550-de3c9580-eeaf-11e8-8189-0e72da5b2bc5.png)

**Comment by Easyfraggy** [comment]
I mean it's a hc - why would it be relevant with your armor? 50% is slightly on the low side for a beginner hc tank.

**Comment by mhdemn** [comment]
I consider my scepticism satisfied

**Comment by Anselm123** [comment]
Seems a bit odd that they have 2 versions of MS and can cast both at near the same second and do 9k burst though

**Comment by Anselm123** [comment]
https://wow.gamepedia.com/Bloodwarder_Slayer says they should only be using the solar strike
