### ISSUE TITLE
[NPC] [Boss] [Karazhan] Illhoof - Sacrifice

### ISSUE THREAD

**Issue by Drayo** [Atlantiss/NetherwingBugtracker#2943]
[//]: # (Enclose links to things related to the bug using http://wowhead.com or any other TBC database.)
[//]: # (You can use screenshot ingame to visual the issue.)
[//]: # (Write your tickets according to the format:)
[//]: # ([Quest][Azuremyst Isle] Red Snapper - Very Tasty!)
[//]: # ([NPC] Magistrix Erona)
[//]: # ([Spell][Mage] Fireball)
[//]: # ([Npc][Drop] Ghostclaw Lynx)
[//]: # ([Web] Armory doesnt work)
[//]: # (To find server revision type `.server info` command in the game chat.)

**Current behaviour**:

Illhoof correctly chains the tank sometimes, but instead of attacking the second aggro target until the chains get killed, he drops threat permanently instead.

**Expected behaviour**: 

Chains should work like the old fear, he should look for the second target on the aggro list until the main target has regained control over his character. Permanently dropping threat makes no sense due to the boss being taunt immune.

**Server Revision**: 2345

**Comment by Easyfraggy** [comment]
As with fear you need to get back on the agrolist - by doing something. Buffing/attacking/healing to get agro back. However this does seem much more severe.

**Comment by Easyfraggy** [comment]
https://github.com/Atlantiss/NetherwingBugtracker/issues/2918 about same spell - could be fixed at the same time.

**Comment by Wolffenstein** [comment]
I didn't code any threat resets to that encounter, so he should reaggro on the main tank unless somebody accumulated more threat in that time.

**Comment by Drayo** [comment]
There might be a possibility that he got overtaken on threat, but it would have been 3 players in a window of about 6 seconds.

https://www.twitch.tv/videos/339002720?t=02h36m41s

This is where I saw it. It might need further investigation.

**Comment by RealZwox** [comment]
I see no bug in your linked Twitch Video. Tank got chained -> Mage Blocked -> next one in the Threatlist is the Priest. And if you watch exactly in 02:37:02 you see that the mage is the First in the Threatlist. A classic overaggro

**Comment by Easyfraggy** [comment]
I don't see any bug in the video either. Mage overagros - Iceblocks - tank is still chained - Illhoof slaps the priest into the ground - tank still chained - illhoof runs for mage (still top agro) - tanks gets freed - slaps mage in the ground and turns to the rogue whoem we can't see how much threat he has - he may very well have overtaken the tank by the time he gets out of chains.

**Comment by Drayo** [comment]
Yes, it's quite possible that he was just overtaken in threat, this can be closed. Should there be any issues it can just be reopened later.
