### ISSUE TITLE
[Boss] Pathaleon the Calculator's wraith adds ignore collision

### ISSUE THREAD

**Issue by mhdemn** [Atlantiss/NetherwingBugtracker#2944]
During [Pathaleon](https://db.excalibur.ws/?npc=21537)'s fight, the [Nether Wraith](https://db.excalibur.ws/?npc=21535)s he summons will **ignore LoS and cast Arcane Missiles** (**start** a new cast through the corners between the bridge and Pathaleon's chamber, a terrain players' vision collide with; and **not only** be able to continue the cast if LoS happens before channel is over).

If an aoe fear is casted, it's almost a guaranteed wipe since party members will be forced to move inside range of Pathaleon's AoE, either to reach the wraiths, to reach your DPSes and heal them, etc

**Server Revision**: noticed in 2339, reposted in 2349 since I haven't read confirmation of this getting fixed

**Comment by Wolffenstein** [comment]
The spell they use has an attribute "SPELL_ATTR2_CAN_TARGET_NOT_IN_LOS", so apparently they should be able to do that (unless you manage to find proof that it should be otherwise). Closing for now.

**Comment by KarlDenXII** [comment]
This boss ignores initial aggro.
