### ISSUE TITLE
[Item] Hallowed Rainment 2-Set Bonus

### ISSUE THREAD

**Issue by Saben65** [Atlantiss/NetherwingBugtracker#2945]
**Description**: 
In [Patch 2.1](http://wowwiki.wikia.com/wiki/Patch_2.1.0) Blizzard changed the 2-set bonus of [Hallowed Rainment](https://www.wowhead.com/transmog-set=874/hallowed-raiment) to give a 30% chance to avoid interruption when casting Binding Heal.

> Hallowed Raiment Set: The Binding Heal set bonus on this set has been changed to 30% chance to resist losing casting time off Binding Heal when taking damage.

**Current behaviour**:
The post 2.1 set bonus is in affect, it is the 30% chance to avoid interruption when casting binding heal.

**Expected behaviour**: 
The 2-set should [reduce the mana cost of binding heal by 5%.](https://web.archive.org/web/20070314062359/http://www.thottbot.com:80/i27775)

**Server Revision**: 
2349

**Comment by Tenoutoften** [comment]
Would have to make a custom spell for this?
https://db.excalibur.ws/?spell=37556 =>https://www.wowhead.com/spell=37556/binding-heal-cost-reduction

Looks like they never changed the name of the aura from the set bonus, they just changed the spell itself

**Comment by Easyfraggy** [comment]
Unsure if this can be fixed if blizzard changed the spell it would show wrong tooltip if we did.

**Comment by aresbrutus** [comment]
As much as we would like, we can not change spell bonus of sets like these to pre-2.1 version.
