### ISSUE TITLE
[NPC]Rajah Haghazed#18046 uses his shield wall too frequently

### ISSUE THREAD

**Issue by Tenoutoften** [Atlantiss/NetherwingBugtracker#2946]
**Description**: 
[[NPC]Rajah Haghazed#18046](https://www.wowhead.com/npc=18046/rajah-haghazed#comments) uses his shield wall too frequently at the moment. Feels like the CD is about 30 sec or so

Suggest 1 min cooldown perhaps?
None of the comments mention him using his shield wall very frequently

**Expected behaviour**: 
1 min CD on shield wall

**Server Revision**: 
2349

**Comment by Wolffenstein** [comment]
Fixed in rev 2353.
