### ISSUE TITLE
[Item] Supple Leather Boots

### ISSUE THREAD

**Issue by Saben65** [Atlantiss/NetherwingBugtracker#2947]
**Description**: 
In [Patch 2.1](http://wowwiki.wikia.com/wiki/Patch_2.1.0), Blizzard nerfed [Supple Leather Boots](https://www.wowhead.com/item=31532/supple-leather-boots). The boots are a reward from the quest [Whispers of the Raven God](https://www.wowhead.com/quest=10607/whispers-of-the-raven-god). Prior to this change, these boots were actually one of the better/best pre-raid boots for feral druids.

**Current behaviour**:
Stats are at their post 2.1 levels.

352 Armor
+22 Strength
+24 Stamina
+11 Agility

**Expected behaviour**: 
Stats should be at their [pre-2.1 level](https://web.archive.org/web/20070516034207/http://thottbot.com:80/i31532).

+352 Armor
+19 Strength
+24 Stamina
+11 Agility
+30 Attack Power

**Server Revision**: 
2349

**Comment by aresbrutus** [comment]
Fixed in rev `Aterpol`
