### ISSUE TITLE
[NPC][Boss][Karazhan][Curator] Aggro-range and hitbox

### ISSUE THREAD

**Issue by sandreid** [Atlantiss/NetherwingBugtracker#2948]
[//]: # (To find server revision type `.server info` command in the game chat.)

**Description**: 
The Curator doesn't appear to be acting as it should, according to retail TBC. His aggro-range as well as his hitbox seem to be too big.

**Current behaviour**:
([NPC]The Curator)'s aggro-range seems to be too big. Something around 50-60 yards. His hitbox is also huge. You can hit him with melee attack up to about 15-25 yards away. 

**Expected behaviour**: 
https://www.youtube.com/watch?v=1p0Z_VF-dkI
Video from retail TBC (Patch 2.1, by the date of the video)

([NPC]The Curator) has a hitbox only slightly larger than his feet here (Roughly 5 years - About 1/3 of the size of NW) and the melee range seems to reflect this range as well. He is also closer to the player when he aggros - About 35-40 yards away.

NPC in question: http://db.excalibur.ws/?npc=15691

**Server Revision**: 2349

**Comment by Easyfraggy** [comment]
His agro range atm is 40 yards.

**Comment by Wolffenstein** [comment]
Fixed in rev 2351.
