### ISSUE TITLE
[NPC] [Spell] Mana Tombs - Nexus Terror's Death Coil is a buff, not a debuff

### ISSUE THREAD

**Issue by Jacksn5** [Atlantiss/NetherwingBugtracker#2949]
[//]: # (Enclose links to things related to the bug using http://wowhead.com or any other TBC database.)
[//]: # (You can use screenshot ingame to visual the issue.)
[//]: # (Write your tickets according to the format:)
[//]: # ([Quest][Azuremyst Isle] Red Snapper - Very Tasty!)
[//]: # ([NPC] Magistrix Erona)
[//]: # ([Spell][Mage] Fireball)
[//]: # ([Npc][Drop] Ghostclaw Lynx)
[//]: # ([Web] Armory doesnt work)
[//]: # (To find server revision type `.server info` command in the game chat.)

**Description**: 
[Nexus Terror](https://db.excalibur.ws/?npc=20265)'s [Death Coil](https://db.excalibur.ws/?spell=38065) is an aura which can be cancelled using /cancelaura Death Coil
See
[![Death Coil Aura 1](http://img.youtube.com/vi/Icb_FaaghZk/0.jpg)](https://www.youtube.com/watch?v=Icb_FaaghZk "Death Coil Aura 1")
and
[![Death Coil Aura 2](http://img.youtube.com/vi/frG_Z2Mnwo0/0.jpg)](https://www.youtube.com/watch?v=frG_Z2Mnwo0 "Death Coil Aura 2")

**Server Revision**: 
2349

**Comment by Easyfraggy** [comment]
https://github.com/Atlantiss/AtlantissTBCBT/issues/4073

**Comment by xmesaj2** [comment]
rev 2356
