### ISSUE TITLE
[Item] The Oathkeeper

### ISSUE THREAD

**Issue by Saben65** [Atlantiss/NetherwingBugtracker#2950]
**Description**: 
[The Oathkeeper](https://www.wowhead.com/item=31299/the-oathkeeper) had its equip bonus changed from +30 spell damage to +26 hit in [Patch 2.4](http://wowwiki.wikia.com/wiki/Patch_2.4.0) (undocumented in offical notes). Patch 2.4 came out March 24, 2008 and the last time it was captured by the wayback machine with SP was [March 21, 2008](https://web.archive.org/web/20080321063353/http://thottbot.com:80/i31299).

[A wowhead comment](https://www.wowhead.com/item=31299/the-oathkeeper#comments:id=241625) mentions this change was on the PTR while patch 2.3.3 was active. The next patch that would have been on the PTR was 2.4.

**Current behaviour**:
The Oathkeeper currently has "Equip: Improves Hit Rating by 26."

**Expected behaviour**: 
The Oathkeeper should instead have "Equip: Increases damage and healing done by magical spells and effects by up to 30." until patch 2.4

**Server Revision**: 
2349

**Comment by aresbrutus** [comment]
Fixed in rev `Aterpol`
