### ISSUE TITLE
Expose Armor stack with Sunder Armor. [Spell]

### ISSUE THREAD

**Issue by Neophrone** [Atlantiss/NetherwingBugtracker#2951]
[//]: # (Enclose links to things related to the bug using http://wowhead.com or any other TBC database.)
[//]: # (You can use screenshot ingame to visual the issue.)
[//]: # (Write your tickets according to the format:)
[//]: # ([Quest][Azuremyst Isle] Red Snapper - Very Tasty!)
[//]: # ([NPC] Magistrix Erona)
[//]: # ([Spell][Mage] Fireball)
[//]: # ([Npc][Drop] Ghostclaw Lynx)
[//]: # ([Web] Armory doesnt work)
[//]: # (To find server revision type `.server info` command in the game chat.)

**Description**:
 Rogue Expose Armor stack with warrior Sunder Armor. 

**Current behaviour**:
 Maybe the reason is that I have Improved Expose Armor in talents, and normal (not improved EA) will not stack. But I'm sure that it stack and armor reduction stack to, couse damage increased heavily.
Screenshot:
![1](https://user-images.githubusercontent.com/43533040/48924209-688bf600-eebe-11e8-8f7d-df93c49bd8a7.jpg)

**Expected behaviour**: 
Expose Armor and Sunder Armor shouldn't stack. Normal Expose armor reduce armor by 2050 points, 5 stacks of Sunder armor reduce armor by 2600. Since EA reduction depends on ammount of combo points and SA on ammount of stacks they can replace each other if applied debuff weaker than that u trying to put on target. I was using 5CP Improved EA (-3075 armor), so in this case warrior's Devastate should not apply SA stacks.
**Server Revision**: 2349.

**Comment by Saben65** [comment]
http://web.archive.org/web/20080528014216/http://elitistjerks.com/f47/t24301-rogue_pve_dps/#Raid-wide_Buffs_and_Boss_Debuffs

> Note that a 5-CP Expose Armor with 2 points in Improved Expose Armor is worth slightly more armor reduction than Sunder Armor (3075 vs. 2600). If your tank is a protection warrior, then Expose Armor will overwrite and prevent the use of Sunder Armor, reducing the warrior's initial threat from Devastating up to a full stack of Sunder Armor, as well as his threat on subsequent Devastates with 5 Sunders. The net effect on his TPS will be a reduction of roughly 100, usually precluding usage of Expose Armor. However, if your tank is not a warrior, then it is a net raid DPS gain for one rogue to switch to a cycle incorporating Improved Expose Armor rather than having a DPS warrior apply Sunder Armor. See the cycle section below for more information on Expose cycles.

**Comment by knasen88** [comment]
does it actually decrease the armor or is the sunder armor debuff just still there to provide the (tank) warrior with his 5 sunder devastate damage? (does more dmg per sunder armor on the target)

**Comment by Neophrone** [comment]
> does it actually decrease the armor or is the sunder armor debuff just still there to provide the (tank) warrior with his 5 sunder devastate damage? (does more dmg per sunder armor on the target)

It's actualy decrease armor. With both debuffs my damage was like I'm hitting mob without armor.

**Comment by Mikik3jr** [comment]
I just comment here, because I see a _guild_ that abuses this with their rogues running improved version of the spell, which was really not used back in the days according to vanilla and 2.3.3 comments.

**Comment by Neophrone** [comment]
Strange, this issue didn't close, but I ran MT few days ago, and my EA didn't stack with SA of our tank.

**Comment by Neophrone** [comment]
Useful to spent points in imp EA if u doing dungeons with Feral druid tank. Imo, but 2 points in imp EA better than spent points to improve u'r poisons.

**Comment by Mikik3jr** [comment]
Not improved Expose armor does not stack with Sunder armor. Just tested it now.
