### ISSUE TITLE
Underbat. Underbog(heroic). Tentacle Lash. [NPC] [Spell]

### ISSUE THREAD

**Issue by Neophrone** [Atlantiss/NetherwingBugtracker#2952]
[//]: # (Enclose links to things related to the bug using http://wowhead.com or any other TBC database.)
[//]: # (You can use screenshot ingame to visual the issue.)
[//]: # (Write your tickets according to the format:)
[//]: # ([Quest][Azuremyst Isle] Red Snapper - Very Tasty!)
[//]: # ([NPC] Magistrix Erona)
[//]: # ([Spell][Mage] Fireball)
[//]: # ([Npc][Drop] Ghostclaw Lynx)
[//]: # ([Web] Armory doesnt work)
[//]: # (To find server revision type `.server info` command in the game chat.)

**Description**:
 Underbat (from Underbog heroic) has an ability [Tentacle Lash] that can only hit targets in melee range that standing behind Underbat, so if u a melee DPS and u'll stand in front of this mob u're in safe.

**Current behaviour**:
[Tentacle Lash] hitting even if u stand in front of mob.
**Expected behaviour**: 
This ability should hit targets behind NPC.
Proofs: https://www.wowhead.com/npc=17724/underbat#comments  First comment.
"Watch out, melee DPS. On heroic these little bastards can hit you with a very strong ability called "Tentacle Lash" if you're behind them."
**Server Revision**: 2349.

**Comment by Mikik3jr** [comment]
Funny I experienced it in the other way:
![wowscrnshot_112218_181550](https://user-images.githubusercontent.com/43505031/48924629-b30b7380-eeba-11e8-97ae-a7a03f01cc6c.jpg)

**Comment by Neophrone** [comment]
I've just noticed u report it right after me. =)

**Comment by Mikik3jr** [comment]
Oh sorry I misunderstood your report. I thought you said that they hit their front target. I should go to sleep.

**Comment by Neophrone** [comment]
Megabit was our tank, so he always fight this mob face to face, and ofc. he shouldn't be affected by this ability. Sophiett screen shows that he got hit.

**Comment by Ceago** [comment]
It's supposed to be like a backstab.  hit's if the mob is behind a player not if the player is behind the mob.  They're still using it when in front though.

**Comment by Neophrone** [comment]
> It's supposed to be like a backstab. hits if the mob is behind a player not if the player is behind the mob. They're still using it when in front though.

No, they should using it exactly if player standing behind this mob. Same mechanic as dragon's tail swipe.

**Comment by Neophrone** [comment]
> It's supposed to be like a backstab. hits if the mob is behind a player not if the player is behind the mob. They're still using it when in front though.

Oh wait, looks like u right. 
"Quite nasty if they are after you. Hit my mage for 12k.

Dont run away from them, they only do it when they face your back"
https://www.wowhead.com/spell=37956/tentacle-lash#comments

**Comment by Mikik3jr** [comment]
https://www.youtube.com/watch?v=CRMNLQtsxig

In this video 2 of them are hitting the tank which means 2 things:
1.) They don't use it on tank
2.) They use it, but then it doesn't deal 5k+ dmg. (I think the first one is the correct)

**Comment by miraco** [comment]
Afaik Pre 2.1 it was also to targets in Front. Just like a cleave.

> 
Creatures will no longer Cleave targets that aren't in front of them. 

http://wowwiki.wikia.com/wiki/Patch_2.1.0

**Comment by Easyfraggy** [comment]
I don't know about this one - I have a very early video where they use it in front. They removed the knockdown effect in some early patch so it is very hard to see by watching a video.

The tooltip can be read many ways - the third option you guys didn't consider is that it is used on tank when any player is behind the mob. If noone is behind it doesn't use it =)

I don't know how exactly it should work because theres no good information on it.

**Comment by Neophrone** [comment]
This one heroic vid, and it's pre-2.1 becouse it posted 26th of March 2007, and 2.1 patch released May 2007.
 https://youtu.be/CRMNLQtsxig?t=33
Watch tank health at the start, where they were fighting 3 Underbats. I didn't notice 5k hits, only normal melee swings (1800-2k dmg). Feral and rogue were fighting this mobs from behind, they didn't get damage at all. This means Tentacle Lash should work like backstab.
Also watch the fight with Underbog Lord at 7:03. The fight that should be realy chalengeable.

**Comment by knasen88** [comment]
https://www.wowhead.com/spell=34171/tentacle-lash
this is hitting from front, and absolutely RAPING anything that tries to tank it

**Comment by devo6969** [comment]
https://www.youtube.com/watch?v=CRMNLQtsxig
https://www.youtube.com/watch?v=OV9P3LQq8FQ

This "Backlash" was on another server but according to these videos from 13 years ago it doesn't seem they are trying to avoid any back attack and they don't take any damage. You can see a feral druid go behind the sporebat and takes zero damage so I'm sure this wasn't a thing in Retail TBC

**Comment by Wolffenstein** [comment]
Fixed in rev 3460.
