### ISSUE TITLE
[NPC] [Underbog] Underbat uses Tentacle Lash on targets front of itself

### ISSUE THREAD

**Issue by Mikik3jr** [Atlantiss/NetherwingBugtracker#2953]
[//]: # (Enclose links to things related to the bug using http://wowhead.com or any other TBC database.)
[//]: # (You can use screenshot ingame to visual the issue.)
[//]: # (Write your tickets according to the format:)
[//]: # ([Quest][Azuremyst Isle] Red Snapper - Very Tasty!)
[//]: # ([NPC] Magistrix Erona)
[//]: # ([Spell][Mage] Fireball)
[//]: # ([Npc][Drop] Ghostclaw Lynx)
[//]: # ([Web] Armory doesnt work)
[//]: # (To find server revision type `.server info` command in the game chat.)

**Description**: 
In Underbog there are [Underbats](https://www.wowhead.com/npc=17724/underbat). They cast [Tentacle Lash](https://www.wowhead.com/spell=34171/tentacle-lash) to targets which are BEHIND the mob.

**Current behaviour**:
As I saw only our tank was hit by this spell. I Intentionally stood behind them, or was watching our melee dps's HP, but they didn't get hurt.
![wowscrnshot_112218_181550](https://user-images.githubusercontent.com/43505031/48924550-adf9f480-eeb9-11e8-8680-ab83308e62e1.jpg)
Once I gained aggro and they killed me really fast
![wowscrnshot_112218_181843](https://user-images.githubusercontent.com/43505031/48924589-13e67c00-eeba-11e8-9615-1c5f0f1a0762.jpg)

**Expected behaviour**: 
They should use the spell on targets which are behind them and NOT front of them.

**Server Revision**: 
2349

**Comment by Mikik3jr** [comment]
Closed cuz wolf said on discord it is working correctly.

**Comment by Drayo** [comment]
I think this should be reopened and reconsidered. 

The fact that they use it on the tank feels really weird, it makes them the most dangerous mobs in the instance by FAR.

They should use it on anyone standing behind them, but not on anyone in front on them.

"Extra damage to an enemy when behind them." the Tooltip is worded oddly, yes,  but on wowhead someone specifically warns the melee DPS to be careful:

> By kingfausto (3,225 –  6·22)  on 2008/01/31 (Patch 2.3.3) 
> Watch out, melee DPS. On heroic these little bastards can hit you with a very strong ability called 
> "Tentacle Lash" IF you're behind them.

No mention of them using it on the tank if ANYONE is behind them, they only use it on players that are actually behind them.

**Comment by KarlDenXII** [comment]
This mob is still bugged and needs to be fixed.
