### ISSUE TITLE
Alchemist stone not working in druid forms 

### ISSUE THREAD

**Issue by Fungiqt** [Atlantiss/NetherwingBugtracker#2957]
**Description**: The Alchemist stone doenst add the 40% Pot effect when your in cat or bear. - https://cdn.discordapp.com/attachments/514505181090545704/515244449639694336/fel_mana_potion_bug.png

**Current behaviour**: ^

**Expected behaviour**: Should add the 40% on top of the mana/health pot

**Server Revision**: 2349

**Comment by devo6969** [comment]
Still an issue on the PTR

**Comment by Wolffenstein** [comment]
Fixed in rev 3472.
