### ISSUE TITLE
[Spell][Hunter] Feign Death doesnt work

### ISSUE THREAD

**Issue by ayrb13** [Atlantiss/NetherwingBugtracker#2958]
**Description**: 
Hunter cast Feign Death skill while pet keep on attacking mobs, hunter can escape from battle status, when pet is dead, hunter turns into battle status, and will be killed by  mobs
**Current behaviour**:
Feign Death does not work when pet is dead
https://youtu.be/lV1g6_af9M0
**Expected behaviour**: 
Hunter will escape from battle status
**Server Revision**: 
2349

**Comment by Brasso** [comment]
Good find. You should change your title to [Spell][Hunter] before admins mark it as invalid. You should also put your example video under Current behavior. Use the command " .server info " in game to find the current server revision and put it in the report.

**Comment by ayrb13** [comment]
> Good find. You should change your title to [Spell][Hunter] before admins mark it as invalid. You should also put your example video under Current behavior. Use the command " .server info " in game to find the current server revision and put it in the report.

thanks

**Comment by Easyfraggy** [comment]
+1 for effort - but please use search function first! https://github.com/Atlantiss/NetherwingBugtracker/issues/429
