### ISSUE TITLE
[Pathing/Clipping] Coldridge Valley

### ISSUE THREAD

**Issue by DoctorRaymos** [Atlantiss/NetherwingBugtracker#296]
Mob falls through map during pathing - https://i.imgur.com/r2kP9OP.jpg
Mob falls through map during pathing - https://i.imgur.com/cMix6YS.jpg
Whatchu doin up there rabbit - https://i.imgur.com/ixUXEK4.jpg
Goofy wolf position - https://i.imgur.com/wFOmhmM.jpg
Another damn goofy wolf - https://i.imgur.com/98cLn7B.jpg
Intersecting mobs that sit there (NSFW, they getting it on) - https://i.imgur.com/FWt6xjN.jpg
Doesn't move - https://i.imgur.com/xrpdsyf.jpg

**Comment by aresbrutus** [comment]
Fixed in one of the next updates.
