### ISSUE TITLE
Shaman Reincarnate not working

### ISSUE THREAD

**Issue by Nixazzar** [Atlantiss/NetherwingBugtracker#2960]
**Description**: When killed, shamans reincanate ability dont proc and shaman is not able to resurrect even tho ability is off CD. Not always, sometimes it just wont proc.

**Current behaviour**: No option for to reincarnate.

**Expected behaviour**: When shaman is killed, if reincarnate is off CD shaman should be always able to reincarnate provided he has reagent ankh with him.

**Server Revision**: dont know. Date 11/23/2018

**Comment by Brasso** [comment]
#2183

**Comment by tcberk12** [comment]
@Nixazzar unrelated to the issue, but in future you can type .server info and the Revision is listed in the resultant text.

**Comment by Easyfraggy** [comment]
need to see this happen - cant replicate.

**Comment by Zebhor** [comment]
Shaman Reincarnation is on CD everytime i log into game.
Server Revision: 2364

**Comment by Easyfraggy** [comment]
Yes that is already reported in a different issue - He says it doesn't proc even when it's not on CD.

**Comment by Wolffenstein** [comment]
This was fixed in rev 2411.
