### ISSUE TITLE
[Dungeon] Blood Furnace - Broggok orc event

### ISSUE THREAD

**Issue by adrenochrom** [Atlantiss/NetherwingBugtracker#2961]
**Description**: 
The timers / triggers of the waves are not well scripted.

**Current behaviour**:
- killed first wave
- had to wait 75 seconds foir 2nd wave
- 3rd wave spawned when 1 mob from 2nd wave was still alive
- 4th wave spawned when 3 mobs of 3rd wave were alive

https://www.twitch.tv/videos/339619865?t=54m24s

**Expected behaviour**: 
- 2nd wave should spawn short after first wave was killed
- 4th wave should spawn when 3rd wave is down

**Server Revision**: 
203

**Comment by mhdemn** [comment]
2349

Pretty much what OP says, last fix messed it up a little 

https://youtu.be/5DMy2Uz3tn8

**Comment by Tereneckla** [comment]
Fixed
