### ISSUE TITLE
[Dungeon] Thrall strips down after polimorfed

### ISSUE THREAD

**Issue by Mikik3jr** [Atlantiss/NetherwingBugtracker#2962]
[//]: # (Enclose links to things related to the bug using http://wowhead.com or any other TBC database.)
[//]: # (You can use screenshot ingame to visual the issue.)
[//]: # (Write your tickets according to the format:)
[//]: # ([Quest][Azuremyst Isle] Red Snapper - Very Tasty!)
[//]: # ([NPC] Magistrix Erona)
[//]: # ([Spell][Mage] Fireball)
[//]: # ([Npc][Drop] Ghostclaw Lynx)
[//]: # ([Web] Armory doesnt work)
[//]: # (To find server revision type `.server info` command in the game chat.)

**Description**: 
Thrall got polimorfed during OHF(hc)  escort.

**Current behaviour**:
Here when we cross the bridge before the 2nd boss:
![image](https://user-images.githubusercontent.com/43505031/48954227-e8f73900-ef48-11e8-9fa0-b8707f82b05c.png)
After poli:
![image](https://user-images.githubusercontent.com/43505031/48954254-04fada80-ef49-11e8-856c-89dd39d855b2.png)

**Expected behaviour**: 
Thrall still should be in his armor

**Server Revision**: 
2349

**Comment by Wolffenstein** [comment]
Fixed in rev 3427.
