### ISSUE TITLE
[NPC][Dungeon] Captain Skarloc

### ISSUE THREAD

**Issue by Mikik3jr** [Atlantiss/NetherwingBugtracker#2963]
[//]: # (Enclose links to things related to the bug using http://wowhead.com or any other TBC database.)
[//]: # (You can use screenshot ingame to visual the issue.)
[//]: # (Write your tickets according to the format:)
[//]: # ([Quest][Azuremyst Isle] Red Snapper - Very Tasty!)
[//]: # ([NPC] Magistrix Erona)
[//]: # ([Spell][Mage] Fireball)
[//]: # ([Npc][Drop] Ghostclaw Lynx)
[//]: # ([Web] Armory doesnt work)
[//]: # (To find server revision type `.server info` command in the game chat.)

**Description**: 
The boss casts consecration under himself.

**Current behaviour**:
[Looks like every second conescration lands to the previous place where he casted it, instead of under the boss. Even when the boss dies he still casts the 2nd one on the previous one.](https://www.youtube.com/watch?v=yVrqc08sTdU&feature=youtu.be)

**Expected behaviour**: 

**Server Revision**: 
2349

**Comment by mythyrylfalcon** [comment]
Consecration should be Heroic only.
"Heroic Only -Consecrate: Players standing on Consecrated ground take 675 Holy damage per second."

https://wow.gamepedia.com/index.php?title=Captain_Skarloc&oldid=1478651

**Comment by devo6969** [comment]
This is an only Heroic mechanic in normal he doesn't cast this on normal but it does appear there is a 2nd cast animation on the previous consecration which to retail TBC this is suppose to happen. Its when he cast his 2nd consecration is when the 1st consecration's animation triggers again.
Retail TBC - https://youtu.be/afbf54etkcY?t=221 (You can see the 2nd animation as he drops his 2nd consecration)
PTR - https://www.youtube.com/watch?v=R2jKXKJx9VY
