### ISSUE TITLE
[Spell][Rogue] Sap

### ISSUE THREAD

**Issue by sifiuocz** [Atlantiss/NetherwingBugtracker#2964]
**Description**: 
This bug is related to Sap and it's interaction on an NPC.

**Current behaviour**:
While an NPC is sapped by the player the players are able to generate threat on the NPC with spells (heals from a healer etc.),

**Expected behaviour**: 
As a CC sap is the players shouldn't be able to generate threat on the sapped NPC.

**Server Revision**: 
2349

**Comment by sifiuocz** [comment]
Its not fixed on 2349

**Comment by Easyfraggy** [comment]
![image](https://user-images.githubusercontent.com/36134067/48961413-86b42d80-ef74-11e8-80b8-e16181d6e674.png)

Confirmed not working on 2349 with sap.

**Comment by Easyfraggy** [comment]
![image](https://user-images.githubusercontent.com/36134067/48961469-22de3480-ef75-11e8-9b26-5192d44189c7.png)

Still bugged for polymorph and other CC's aswell.

**Comment by Wolffenstein** [comment]
Fixed in rev 2366.
