### ISSUE TITLE
[NPC][Quest] The Scarlet Oracle, Demetria

### ISSUE THREAD

**Issue by Novat93** [Atlantiss/NetherwingBugtracker#2966]
[//]: # (Enclose links to things related to the bug using http://wowhead.com or any other TBC database.)
[//]: # (You can use screenshot ingame to visual the issue.)
[//]: # (Write your tickets according to the format:)
[//]: # ([Quest][Azuremyst Isle] Red Snapper - Very Tasty!)
[//]: # ([NPC] Magistrix Erona)
[//]: # ([Spell][Mage] Fireball)
[//]: # ([Npc][Drop] Ghostclaw Lynx)
[//]: # ([Web] Armory doesnt work)
[//]: # (To find server revision type `.server info` command in the game chat.)

**Description**: 
The NPC Demetria (npc=12339) is present in the Eastern plaguelands.

**Current behaviour**:
She is present in the zone, without anyone (presumably) having accepted the quest which spawn her.

**Expected behaviour**: 
The NPC should only spawn once a Horde player has accepted the quest to kill her.
quest=6148

**Server Revision**: 
2349

![demetria spawned](https://user-images.githubusercontent.com/36829235/48958628-b1948680-ef60-11e8-9ffb-b8823b29c145.PNG)

**Comment by Evolvee** [comment]
rev xdd
