### ISSUE TITLE
[Dungeon][Stratholme] 

### ISSUE THREAD

**Issue by Novat93** [Atlantiss/NetherwingBugtracker#2967]
[//]: # (Enclose links to things related to the bug using http://wowhead.com or any other TBC database.)
[//]: # (You can use screenshot ingame to visual the issue.)
[//]: # (Write your tickets according to the format:)
[//]: # ([Quest][Azuremyst Isle] Red Snapper - Very Tasty!)
[//]: # ([NPC] Magistrix Erona)
[//]: # ([Spell][Mage] Fireball)
[//]: # ([Npc][Drop] Ghostclaw Lynx)
[//]: # ([Web] Armory doesnt work)
[//]: # (To find server revision type `.server info` command in the game chat.)

**Description**: The gate houses in the Stratholme dungeon does not correctly close once a player enters them, then spawn a bunch of mobs to attack the player(s).

**Current behaviour**:
The gates stay open, and remain open as the player passes through the gate.

**Expected behaviour**: 
The gates are supposed to close once a player enters. Then some mobs are supposed to spawn, rats i believe, from the crates attacking the players in the gatehouse. Once the mobs have been defeated, the gates are supposed to open.

**Server Revision**: 
2349

Prior to entering the gate house
![strat door](https://user-images.githubusercontent.com/36829235/48958692-22d43980-ef61-11e8-99ec-17eb445abc4e.PNG)

I am able to walk through freely
![strat door 2](https://user-images.githubusercontent.com/36829235/48958684-18b23b00-ef61-11e8-9a59-4b85997b7993.PNG)

**Comment by Evolvee** [comment]
need info  - what gates, what npcs, how many npcs etc.

**Comment by noradora** [comment]
https://youtu.be/opFRb4Y0WzM?t=67
https://www.wowhead.com/npc=10441/plagued-rat

**Comment by Evolvee** [comment]
the video is no longer available LF info

**Comment by Evolvee** [comment]
https://www.youtube.com/watch?v=3yAOdhlXotw&feature=youtu.be&t=324

**Comment by Evolvee** [comment]
fixed in next rev
