### ISSUE TITLE
[NPC][Dungeon] [Stratholme] Magistrate Barthilas

### ISSUE THREAD

**Issue by Novat93** [Atlantiss/NetherwingBugtracker#2968]
[//]: # (Enclose links to things related to the bug using http://wowhead.com or any other TBC database.)
[//]: # (You can use screenshot ingame to visual the issue.)
[//]: # (Write your tickets according to the format:)
[//]: # ([Quest][Azuremyst Isle] Red Snapper - Very Tasty!)
[//]: # ([NPC] Magistrix Erona)
[//]: # ([Spell][Mage] Fireball)
[//]: # ([Npc][Drop] Ghostclaw Lynx)
[//]: # ([Web] Armory doesnt work)
[//]: # (To find server revision type `.server info` command in the game chat.)

**Description**: The boss NPC Magistrate Barthilas does not run further into the dungeon, once a player has opened the Stratholme service gate. Usually known as the backdoor entrance.

**Current behaviour**:
The NPC does not move when the gate is opened

**Expected behaviour**: 
The Boss is supposed to flee further into the entrance, to the gate next to the entrance to Baron Rivendare's courtyard. Whenever a player opens the backdoor entrance. In order to engage the boss at his spawn position, in front of the chapel. The players should be required to enter from the front entrance.

**Server Revision**: 
2349

Prior to opening the door
![barthilas](https://user-images.githubusercontent.com/36829235/48958829-ee14b200-ef61-11e8-8074-743888656d72.PNG)

I am able to open the door and walk up to the boss
![barthilas 2](https://user-images.githubusercontent.com/36829235/48958834-f4a32980-ef61-11e8-86dc-3c5dd9dbaea4.PNG)

Further info:
I was in Stratholme for the purpose of completing the level 60 Blood Elf paladin quest ''True master's of the light'' (quest=9737). The quest seems to be working exactly as it should, as does all the quests leading up to this quest.

**Comment by Evolvee** [comment]
this is already reported somewhere
