### ISSUE TITLE
Pet Bypassing Food Level Requirement

### ISSUE THREAD

**Issue by Thugli** [Atlantiss/NetherwingBugtracker#297]
[//]: # (Enclose links to things related to the bug using http://wowhead.com or any other TBC database.)
[//]: # (You can use screenshot ingame to visual the issue.)
[//]: # (Write your tickets according to the format:)
[//]: # ([Quest][Azuremyst Isle] Red Snapper - Very Tasty!)
[//]: # ([NPC] Magistrix Erona)
[//]: # ([Spell][Mage] Fireball)
[//]: # ([Npc][Drop] Ghostclaw Lynx)
[//]: # ([Web] Armory doesnt work)

**Description**: 
Both my pet and I are level 14 and I was able to feed my pet a mutton chop that requires level 15.
**Current behaviour**:
My level 14 pet was able to eat a piece of meat that requires level 15.
**Expected behaviour**: 
Pet's should be have to meet the level requirements for food.
**Server Revision**:

**Comment by Wolffenstein** [comment]
Relevant info for me: http://www.wow-petopia.com/faq.php?id=diet

**Comment by Wolffenstein** [comment]
Fixed in rev 2039.
