### ISSUE TITLE
[NPC]Raging Fire-Soul#22311 lacking Immolation spell

### ISSUE THREAD

**Issue by Tenoutoften** [Atlantiss/NetherwingBugtracker#2972]
**Description**: 
[[NPC]Raging Fire-Soul#22311](https://www.wowhead.com/npc=22311/raging-fire-soul) lacking Immolation spell which should hit for roughly 108.
https://youtu.be/yBAY9lBPYHk?t=70

NW only does auto attack
![0e7cd503e9608f4a96972fd33fdc147f](https://user-images.githubusercontent.com/34839199/48961168-b8c49000-ef72-11e8-977b-28714b78d526.png)

Not sure how frequent it should be used but here is a video of a warlock farming it:
https://youtu.be/LEK0XPW4X8Q?t=8

Considering this mob hits about 300-400, perhaps the ~150 numbers are immolation hits?

**Expected behaviour**: 
Should have an Immolation spell

**Server Revision**: 
2349

**Comment by xmesaj2** [comment]
rev 2356
