### ISSUE TITLE
[NPC]Storming Wind-Ripper#22310 shouldn't spam [Spell]Lightning Bolt#20295

### ISSUE THREAD

**Issue by Tenoutoften** [Atlantiss/NetherwingBugtracker#2974]
**Description**: 
[[NPC]Storming Wind-Ripper#22310](https://www.wowhead.com/npc=22310/storming-wind-ripper) is currently spamming [[Spell]Lightning Bolt#20295](https://www.wowhead.com/spell=20295/lightning-bolt) but shouldn't: https://youtu.be/LEK0XPW4X8Q?t=144

**Expected behaviour**: 
Expected to occasionally use [[Spell]Lightning Bolt#20295](https://www.wowhead.com/spell=20295/lightning-bolt) rather than spam it

**Server Revision**: 
2349

**Comment by xmesaj2** [comment]
rev 2356
