### ISSUE TITLE
[NPC][Auchenai Crypts] Avatar of the Matyred drops too much loot

### ISSUE THREAD

**Issue by Brasso** [Atlantiss/NetherwingBugtracker#2975]
[//]: # (Enclose links to things related to the bug using http://wowhead.com or any other TBC database.)
[//]: # (You can use screenshot ingame to visual the issue.)
[//]: # (Write your tickets according to the format:)
[//]: # ([Quest][Azuremyst Isle] Red Snapper - Very Tasty!)
[//]: # ([NPC] Magistrix Erona)
[//]: # ([Spell][Mage] Fireball)
[//]: # ([Npc][Drop] Ghostclaw Lynx)
[//]: # ([Web] Armory doesnt work)
[//]: # (To find server revision type `.server info` command in the game chat.)

**Description**: 
The avatar of the last boss in Auchenai Crypts drops too much loot.
**Current behaviour**:
https://imgur.com/a/Iln48DF https://imgur.com/a/vho9yLv

**Server Revision**: 
2349

**Comment by Evolvee** [comment]
rev xxd
