### ISSUE TITLE
The Saga of Terokk. [Quest item]

### ISSUE THREAD

**Issue by Neophrone** [Atlantiss/NetherwingBugtracker#2976]
[//]: # (Enclose links to things related to the bug using http://wowhead.com or any other TBC database.)
[//]: # (You can use screenshot ingame to visual the issue.)
[//]: # (Write your tickets according to the format:)
[//]: # ([Quest][Azuremyst Isle] Red Snapper - Very Tasty!)
[//]: # ([NPC] Magistrix Erona)
[//]: # ([Spell][Mage] Fireball)
[//]: # ([Npc][Drop] Ghostclaw Lynx)
[//]: # ([Web] Armory doesnt work)
[//]: # (To find server revision type `.server info` command in the game chat.)

**Description**:
 The Saga of Terokk is a quest item for quest Terokk's Legacy. Should lies in a center of room in Sethekk Halls where we'll summon Anzu in patch 2.1.

**Current behaviour**:
Maybe book lies where it should on normal mode, but there is no book on heroic mode.
![1](https://user-images.githubusercontent.com/43533040/48963010-7743dd00-ef92-11e8-96fc-8b097519e1e1.jpg)

**Expected behaviour**: 
The Saga of Terokk  should lies in a center of room in Sethekk Halls where we'll summon Anzu.
Proove:
https://www.wowhead.com/object=183050/the-saga-of-terokk#screenshots:id=14270
Look at the date of screen download, it's pre-2.1 patch(released 15th May 2007).
**Server Revision**: 2349.

**Comment by Neophrone** [comment]
Also the book can loot only 1 player, but it should has a short respawn (around 10-15 secs).

**Comment by Evolvee** [comment]
rev xxd
