### ISSUE TITLE
The Black Stalker. Heroic. [NPC] [Dungeon] [Loot]

### ISSUE THREAD

**Issue by Neophrone** [Atlantiss/NetherwingBugtracker#2977]
[//]: # (Enclose links to things related to the bug using http://wowhead.com or any other TBC database.)
[//]: # (You can use screenshot ingame to visual the issue.)
[//]: # (Write your tickets according to the format:)
[//]: # ([Quest][Azuremyst Isle] Red Snapper - Very Tasty!)
[//]: # ([NPC] Magistrix Erona)
[//]: # ([Spell][Mage] Fireball)
[//]: # ([Npc][Drop] Ghostclaw Lynx)
[//]: # ([Web] Armory doesnt work)
[//]: # (To find server revision type `.server info` command in the game chat.)

**Description**:
 Heroic last bosses always should drop 2x blue items, primal nether and badge of justice. They should have a chance to drop epic item and epic gem. Idk all bosses have the same issue, but Black Stalker droped only 1 blue item, badge and primal for us.
Proove:
https://youtu.be/GtFAfZBLsXU?t=174
Vid download date is first of April 2007, so this is pre-2.1 patch (2.1 released 15 May 2007).

**Current behaviour**: 
The Black Stalker(heroic) droped only 1 blue item(gear).
**Expected behaviour**: 
The Black Stalker and the others heroic last bosses should drop 2 blue items(gear).
**Server Revision**: 2349.

**Comment by aresbrutus** [comment]
https://github.com/Atlantiss/NetherwingBugtracker/issues/3438
