### ISSUE TITLE
[Spell][Hunter] Multi-Shot

### ISSUE THREAD

**Issue by Zarant** [Atlantiss/NetherwingBugtracker#2978]
Multi-shot messes up your auto shots, after you finish a cast, your next auto shot will hit one of the 3 multi-shot targets regardless if you are targeting that unit or not. 

I'm gonna provide an example below, pay attention at the 1 minute, 50s mark, after I finish casting multi-shot:
https://youtu.be/s6g9-uUkTyc?t=110

Server Revision:  2349

**Comment by Easyfraggy** [comment]
Video doesn't work

**Comment by Zarant** [comment]
Did some arenas in the past 2 days and I had to macro /stopattack with multi-shot, this bug was making me break ccs all the god damn time.
Here is an example: https://youtu.be/81UDj5Pym1w?t=4918
I multi-shot the rogue and my auto attack goes on the druid.

Do I have to unearth 2007-2008 footage to prove that auto shot should only fire on your current target? I can link days worth of video and you won't see auto shot firing at random people other than your current target.

**Comment by Easyfraggy** [comment]
You closed this because it was fixed or?

**Comment by Zarant** [comment]
Yeah it was fixed a month ago or so
