### ISSUE TITLE
[NPC][Spell] Prince Malchezaar - Enfeeble. Not always correctly reducing HP and healing taken.

### ISSUE THREAD

**Issue by Cherryxo** [Atlantiss/NetherwingBugtracker#2979]
[//]: # (Enclose links to things related to the bug using http://wowhead.com or any other TBC database.)
[//]: # (You can use screenshot ingame to visual the issue.)
[//]: # (Write your tickets according to the format:)
[//]: # ([Quest][Azuremyst Isle] Red Snapper - Very Tasty!)
[//]: # ([NPC] Magistrix Erona)
[//]: # ([Spell][Mage] Fireball)
[//]: # ([Npc][Drop] Ghostclaw Lynx)
[//]: # ([Web] Armory doesnt work)
[//]: # (To find server revision type `.server info` command in the game chat.)

**Description**: 
 [Revision as of 00:17, January 14, 2007](http://wowwiki.wikia.com/wiki/Prince_Malchezaar?oldid=421239) wowwiki describes enfeeble as:
"Perodically Enfeebles 5 random people excluding the tank which reduces their max hit points to 1, healing effect and health regen to 0% for about 7 seconds."

**Current behaviour**:
Occasionally when you receive the enfeeble debuff you are not reduced to 1 hp(1) and can still receive healing(2) as shown in [this twitch clip.](https://clips.twitch.tv/SuspiciousCuriousHerbsSSSsss)

**Expected behaviour**: 
The debuff should reduce you to 1 hp and reduce healing and regen effects by 100%

**Server Revision**: 
2349

**Comment by Manaci** [comment]
Fixed
