### ISSUE TITLE
([Spell][Mage]Polymorph)

### ISSUE THREAD

**Issue by killablink** [Atlantiss/NetherwingBugtracker#298]
**Description**: Using polymorph next to a linked (same faction mob or however you call that) mob isn't aggroing the non sheeped target.

**Current behaviour**: Sheep a humanoid right next to one and the other one doesn't move.

**Expected behaviour**: Sheeping a mob next to another one should aggro the surrounding like a normal spell would. There's a reason why this existed : https://wow.gamepedia.com/Sheep_pull

**Server Revision**: 2037

**Comment by Wolffenstein** [comment]
From what we could gather from our sources the polymorphed mobs do not aggro others until the polymorph ends. The wowpedia page you linked doesn't really specify it so I need a better proof

**Comment by killablink** [comment]
Again, I've played mage all my life in TBC and it's definitely how it's supposed to work. How does that page not specify? It says it's a strategy where the mage uses sheep to pull instead of the tank. Obviously you're not gonna wait 1 minute until the sheep breaks to pull mobs. It was changing somewhere in Cata I believe

https://us.battle.net/forums/en/wow/topic/3123037815

Many crowd control abilities no longer cause creatures to attack players when they are cast. The creature will not attack the player when the crowd control wears off, and nearby creatures will not become hostile to the player either. However, if a visible player gets too close to the target creature, the creature will remember and attack the player when the crowd control effect wears off. The intent is to make it easier for dungeon groups to manage crowd control assignments and pulling packs of hostile NPCs. The abilities affected by this change are: Hibernate, Entangling Roots, Wyvern Sting (will still cause hostility when it begins to deal damage), Freezing Trap, Polymorph, Repentance, Shackle Undead, Blind, Hex, Bind Elemental, Banish, Seduction.

**Comment by Godmatik** [comment]
Yes, Cata changed it so that using CC on mobs won't aggro ones nearby. At least in dungeons, 100%. Not sure about the outside world.

**Comment by Wolffenstein** [comment]
@killablink don't take it personally, I always ask for proof because a lot of the times people's memories are faulty and I don't want to change stuff based on that

**Comment by killablink** [comment]
Sorry, didn't mean to but yeah stuff concerning mages in TBC I am very knowledgeful and my memory isn't plagued by pservers stuff as I haven't played them except at Gummy recently. Here's more proof:

https://us.battle.net/forums/en/wow/topic/1536704896

"Other CCers can prepare CC's without aggroing mobs like rogue saps or hunter traps. Rogues have to be out of combat to sap too, so make sure he gets the sap in before sheep. "

**Comment by Wolffenstein** [comment]
Fixed in rev 2040.
