### ISSUE TITLE
[Dungeon][Sethekk Halls] Infight bug in the start not related to pets

### ISSUE THREAD

**Issue by adrenochrom** [Atlantiss/NetherwingBugtracker#2980]
**Description**: 
In the beginning some ppl get can't get outfight after a pack is dead. This is not related to pets - we didn't had any.
This happened 3-5 times on different packs.
Sometimes we were infight from mass dispel on critter. After we killed that critter we got outfight. But not always.
Rezone gets you out of fight.

**Current behaviour**:
Some playes are not outfight after some packs in the beginning.
https://www.twitch.tv/videos/339982544?t=03h20m28s

**Expected behaviour**: 
You should get outfight after every pack ins dead.

**Server Revision**:

**Comment by Neophrone** [comment]
It's strange, we ran Sethekk Halls yesterday, and we hadn't such problem.

**Comment by Tenoutoften** [comment]
Suggestion: When this happens try to contact a GM and request him to check what you are in combat with, this way you can get a way more precise bug report!

**Comment by Tenoutoften** [comment]
Oh! This might be related to the MC-combat bug!

**Comment by Godmatik** [comment]
Seems fixed
