### ISSUE TITLE
[Dungeon][Ramparts] Vazruden evaded and despawned

### ISSUE THREAD

**Issue by adrenochrom** [Atlantiss/NetherwingBugtracker#2983]
**Description**: 
Vazrued evaded and despawned after we got in combat with him.

**Current behaviour**:
- Vazrued evaded and despawned short after we got in combat with him.
https://www.twitch.tv/videos/340042226?t=52m14s

**Expected behaviour**: 
Vazruden should not evade/despawn when players are alive.

**Server Revision**: 
203

**Comment by The14me** [comment]
Confirm,just happen again.

**Comment by devo6969** [comment]
I tried to recreate the boss from despawning, the only thing i could find is when the boss leaves the ring and runs up the path he will despawn, perhaps running to a out of position healer
https://www.youtube.com/watch?v=RmEP5QdZhxA
