### ISSUE TITLE
[NPC] 22017 Eclipsion Spellbinder Resets Late and Kills Itself

### ISSUE THREAD

**Issue by WarriorTSW** [Atlantiss/NetherwingBugtracker#2984]
[//]: # (Enclose links to things related to the bug using http://wowhead.com or any other TBC database.)
[//]: # (You can use screenshot ingame to visual the issue.)
[//]: # (Write your tickets according to the format:)
[//]: # ([Quest][Azuremyst Isle] Red Snapper - Very Tasty!)
[//]: # ([NPC] Magistrix Erona)
[//]: # ([Spell][Mage] Fireball)
[//]: # ([Npc][Drop] Ghostclaw Lynx)
[//]: # ([Web] Armory doesnt work)
[//]: # (To find server revision type `.server info` command in the game chat.)

**Description**: 
Eclipsion Spellbinder https://www.wowhead.com/npc=22017/eclipsion-spellbinder resets a lot later than Eclipsion Soldiers.
Also when i was killed, the mob also vanished. (see video)
**Current behaviour**:
When pulling mobs including an Eclipsion Spellbinder and running away, everything else will reset but the Eclipsion Spellbinder will continue to chase for approximately thee times the distance as the Eclipsion Soldiers.
Video starts at 02:50
https://youtu.be/no6jxKJl4jE
**Expected behaviour**: 
Same reset behaviour as other mobs.
**Server Revision**: 
2349

**Comment by Tereneckla** [comment]
Fixed
