### ISSUE TITLE
[core] Increased Swing Speed Aura Effects Stacking

### ISSUE THREAD

**Issue by WarriorTSW** [Atlantiss/NetherwingBugtracker#2985]
[//]: # (Enclose links to things related to the bug using http://wowhead.com or any other TBC database.)
[//]: # (You can use screenshot ingame to visual the issue.)
[//]: # (Write your tickets according to the format:)
[//]: # ([Quest][Azuremyst Isle] Red Snapper - Very Tasty!)
[//]: # ([NPC] Magistrix Erona)
[//]: # ([Spell][Mage] Fireball)
[//]: # ([Npc][Drop] Ghostclaw Lynx)
[//]: # ([Web] Armory doesnt work)
[//]: # (To find server revision type `.server info` command in the game chat.)

**Description**: 
Slow effects stacking
**Current behaviour**:
Improved Thunderclap and the debuff from  [Riftmaker] https://www.wowhead.com/item=29182/riftmaker Temporal Rift ID: 35353 stack. I dont think this is limited to Improved Thunderclap and that any slowing effect will add up currently on Beta.
**Expected behaviour**: 
Patch 1.7.0 (13-Sep-2005): Spells and effects that reduce attack speed will no longer stack with each other.

Spells and effects that reduce attack speed will no longer stack with each other. Some spells this change effects include Thunderclap, Frost Armor, the Doomguard's Cripple spell, the Icy Chill enchantment, and Hurricane.

There are a lot including npc abilities.
**Server Revision**: 
2349

**Comment by Evolvee** [comment]
aura stacking is temporarily taken down, as its being rewritten

once its enabled again, all aura stacking issues will be resolved

**Comment by Easyfraggy** [comment]
They might stack visually - lots do like Thunderfury and Thunderclap however the attack speed is only modified by the most powerful effect - I believe this is already working though unless you can prove that it doesn't?

**Comment by Tereneckla** [comment]
![image](https://user-images.githubusercontent.com/50233983/72912599-28cbd300-3d3c-11ea-8773-cb8952a805f2.png)

**Comment by Evolvee** [comment]
test it on player with some player-only spells, its probably just the spell from thunderfury that has different effects to it so it stacks visually

**Comment by Evolvee** [comment]
still?
