### ISSUE TITLE
Heroic Arcatraz Felguard / Stealthed Succubus pull together

### ISSUE THREAD

**Issue by Rocklenry** [Atlantiss/NetherwingBugtracker#2987]
[//]: # (Enclose links to things related to the bug using http://wowhead.com or any other TBC database.)
[//]: # (You can use screenshot ingame to visual the issue.)
[//]: # (Write your tickets according to the format:)
[//]: # ([Quest][Azuremyst Isle] Red Snapper - Very Tasty!)
[//]: # ([NPC] Magistrix Erona)
[//]: # ([Spell][Mage] Fireball)
[//]: # ([Npc][Drop] Ghostclaw Lynx)
[//]: # ([Web] Armory doesnt work)
[//]: # (To find server revision type `.server info` command in the game chat.)

**Description**: 
The Stealthed Succubus and the Felguard first pulls in the room of the 2nd and 3rd Bosses of Heroic Arcatraz pull together no matter the distance between them.  

**Current behaviour**:
Regardless of the position of the Felguard, the stealthed Succubus pulls with him.  We tried and wiped at least 5 times before a GM had to kill the stealthed succubus for us to continue.  We had detect invisible on and could see the stealthed mob's position so we knew when you should be able to pull them separate, but we could never.  

**Expected behaviour**: 
Each of those mobs in there should be able to be pulled separate even though they can link if you aren't careful.  

**Server Revision**: 
2349

**Comment by The14me** [comment]
20881 ID 2 with .20882 ID 2
May not be a valid issue.

**Comment by Easyfraggy** [comment]
https://github.com/Atlantiss/NetherwingBugtracker/issues/2836
