### ISSUE TITLE
[NPC][QUEST] Dark Iron Legacy / Franclorn Forgewright

### ISSUE THREAD

**Issue by duzyizly** [Atlantiss/NetherwingBugtracker#2988]
![wowscrnshot_112418_164119](https://user-images.githubusercontent.com/43931626/48970068-06d7a300-f008-11e8-99d3-e4adbe6a415e.jpg)
[//]: # (Enclose links to things related to the bug using http://wowhead.com or any other TBC database.)
[//]: # (You can use screenshot ingame to visual the issue.)
[//]: # (Write your tickets according to the format:)
[//]: # ([Quest][Azuremyst Isle] Red Snapper - Very Tasty!)
[//]: # ([NPC] Magistrix Erona)
[//]: # ([Spell][Mage] Fireball)
[//]: # ([Npc][Drop] Ghostclaw Lynx)
[//]: # ([Web] Armory doesnt work)
[//]: # (To find server revision type `.server info` command in the game chat.)

**Description**: NPC Franclorn Forgewright is here as "unknown" npc and he doesn't offer an brd quest key aka dark iron legacy. It has been reported before and closed by "fixed in rev" at 5th october 2018 but still not working correctly.

**Current behaviour**: ^

**Expected behaviour**: should be named Franclorn Forgewright and offer a quest.

**Server Revision**: Im 80% sure it's 2356.

**Comment by duzyizly** [comment]
![wowscrnshot_112418_201518](https://user-images.githubusercontent.com/43931626/48972196-ec142700-f025-11e8-9ca5-4e2838c04e37.jpg)
Delated cache and rolled new character - still unknown.

**Comment by Evolvee** [comment]
![image](https://user-images.githubusercontent.com/1942409/48981847-e3315d00-f0da-11e8-87ed-164db463d8d3.png)

**Comment by Evolvee** [comment]
I cant reproduce this.

**Comment by duzyizly** [comment]
Yup, working now.
![wowscrnshot_112618_195204](https://user-images.githubusercontent.com/43931626/49035341-c701ee80-f1b4-11e8-83ca-01077c6e9fb0.jpg)
