### ISSUE TITLE
[Item] Force Reactive Disk

### ISSUE THREAD

**Issue by Tholinx** [Atlantiss/NetherwingBugtracker#2989]
[//]: # (Enclose links to things related to the bug using http://wowhead.com or any other TBC database.)
[//]: # (You can use screenshot ingame to visual the issue.)
[//]: # (Write your tickets according to the format:)
[//]: # ([Quest][Azuremyst Isle] Red Snapper - Very Tasty!)
[//]: # ([NPC] Magistrix Erona)
[//]: # ([Spell][Mage] Fireball)
[//]: # ([Npc][Drop] Ghostclaw Lynx)
[//]: # ([Web] Armory doesnt work)
[//]: # (To find server revision type `.server info` command in the game chat.)

**Description**: 
http://tbc.cavernoftime.com/item=18168
Force Reactive Disk doesn't work at all.

**Current behaviour**:
It should do AOE dmg (approx 25-40 dmg) to all moobs around me when I block. Now even if I block it won't do any dmg at all.
recount: https://i.imgur.com/h7Khw9f.png

**Expected behaviour**: 
"When the shield blocks it releases an **electrical charge that damages all nearby enemies**. This also has a chance of damaging the shield."

**Server Revision**: 
2338

**Comment by Wolffenstein** [comment]
Fixed in rev 3185.
