### ISSUE TITLE
[175708] Crossroads Supply Crate

### ISSUE THREAD

**Issue by wtRCH** [Atlantiss/NetherwingBugtracker#299]
[//]: # (Enclose links to things related to the bug using http://wowhead.com or any other TBC database.)
[//]: # (You can use screenshot ingame to visual the issue.)
[//]: # (Write your tickets according to the format:)
[//]: # ([Quest][Azuremyst Isle] Red Snapper - Very Tasty!)
[//]: # ([NPC] Magistrix Erona)
[//]: # ([Spell][Mage] Fireball)
[//]: # ([Npc][Drop] Ghostclaw Lynx)
[//]: # ([Web] Armory doesnt work)

**Description**: When looting crate at max range it doesn't count to the quest and makes the crate dispawn.

**Comment by xmesaj2** [comment]
cannot reproduce

**Comment by The14me** [comment]
cant reproduce too.Re-open if happen again.
