### ISSUE TITLE
Profession cooldowns

### ISSUE THREAD

**Issue by lynxzor** [Atlantiss/NetherwingBugtracker#2993]
[//]: # (Enclose links to things related to the bug using http://wowhead.com or any other TBC database.)
[//]: # (You can use screenshot ingame to visual the issue.)
[//]: # (Write your tickets according to the format:)
[//]: # ([Quest][Azuremyst Isle] Red Snapper - Very Tasty!)
[//]: # ([NPC] Magistrix Erona)
[//]: # ([Spell][Mage] Fireball)
[//]: # ([Npc][Drop] Ghostclaw Lynx)
[//]: # ([Web] Armory doesnt work)
[//]: # (To find server revision type `.server info` command in the game chat.)

**Description**: Profession cooldowns are on 2.4.3 when they should be 2.0 values

**Current behaviour**: 2.4.3 cd's

**Expected behaviour**: Cd's should be updated on patch cycles

**Server Revision**: 2349

![image](https://user-images.githubusercontent.com/795881/48971882-e1529580-f017-11e8-90b7-4ee60ce27d86.png)

Information based on patch cycles 2.0, 2.1, 2.2, 2.3, 2.4, so I have ignored things like Void Shatter which changed 2.4 to 2.4.2, so the listed changes 2.4.0, 2.4.2, 2.4.3 would all be in the 2.4.0 cycle

Transmutes (Primal might, life etc) shared cd's come under general except for the ones listed specifically.
The rest of the vanilla transmutes I believe stay as 24hr cd's?

_edit image: Earthstorm & Skyfire transmutes should also reduce to 20hrs in 2.4.2 - added_

**Comment by aresbrutus** [comment]
Fixed in rev `Hygiea` Please test it out. You might need to relog for the tooltip to show correct cooldowns.
