### ISSUE TITLE
[Dungeon][NPC]Lieutenant Drake missing RP text / yell or too low range on yell? in OFH

### ISSUE THREAD

**Issue by Tenoutoften** [Atlantiss/NetherwingBugtracker#2994]
**Description**: 
[[NPC]Lieutenant Drake#17848](www.wowhead.com/npc=17848) seems to be missing RP text when the huts are all on fire.

Can be seen here (normal version):
https://youtu.be/euFbwTViw_Q?t=90

Including it happening in HC version too:
https://youtu.be/6lOWgKhAMvU?t=21

>You there, fetch water quickly! Get these flames out before they spread to the rest of the keep! Hurry damn you!

https://db.excalibur.ws/?npc=17848 - N
https://db.excalibur.ws/?npc=20535 - HC

**Current behaviour**:
No such yell in heroic on my recording...

**Expected behaviour**: 
Expected to do RP yell / text as provided

**Server Revision**: 
2349

**Comment by Wolffenstein** [comment]
You could have simply been too far from him, the text is there for sure.

**Comment by Tenoutoften** [comment]
Ill recheck this sometime ~ perhaps the yell range is too low?

**Comment by Evolvee** [comment]
slapped area-wide text in rev xxd
