### ISSUE TITLE
[Misc][Dungeon] OFH missing RP by Captain Edward Hanes & Captain Sanders

### ISSUE THREAD

**Issue by Tenoutoften** [Atlantiss/NetherwingBugtracker#2996]
**Description**:
Throughout the entirety of the Ashbringer RP event there is an additional two NPCs seen drinking with  [Barkeep Kelly](https://www.wowhead.com/npc=20377/barkeep-kelly#comments), they seem to be stuck by the boats close to the harbor - Captain Sanders has half of his legs into the ground.

https://youtu.be/NjcKHm13A5w?t=5

The missing NPCs are  https://www.wowhead.com/npc=20400/captain-edward-hanes#comments & https://www.wowhead.com/npc=20351/captain-sanders both have red shirt & pirate hat

![a60e7c17724168679468221f3fa085ad](https://user-images.githubusercontent.com/34839199/48972664-76ad5400-f02f-11e8-8b7d-e8351024a012.png)
![33c2f87308a6db55cdb6382854d15b19](https://user-images.githubusercontent.com/34839199/48972676-9a709a00-f02f-11e8-8687-9b8c346749e0.png)

**Expected behaviour**: 
Barkeep Kelly should be drinking and talking with two NPCs

**Server Revision**: 
2356

**Comment by Evolvee** [comment]
its working, it just has long repeat cooldown

**Comment by Evolvee** [comment]
1500 seconds to be precise after a player moves close to them in the inn

![image](https://user-images.githubusercontent.com/1942409/48978482-4c4dac00-f0ac-11e8-88f9-a3d1be5845ab.png)
![image](https://user-images.githubusercontent.com/1942409/48978486-5cfe2200-f0ac-11e8-95de-83dccc91d35f.png)
![image](https://user-images.githubusercontent.com/1942409/48978487-638c9980-f0ac-11e8-8653-4ddcda3c64c0.png)

**Comment by Evolvee** [comment]
![image](https://user-images.githubusercontent.com/1942409/48978493-7e5f0e00-f0ac-11e8-814e-c19913ba746c.png)
