### ISSUE TITLE
[Dungeon][Misc] OHF  Thrall too easily dismounts to kill lowbie NPCs

### ISSUE THREAD

**Issue by Tenoutoften** [Atlantiss/NetherwingBugtracker#2998]
**Description**: 
Thrall seems to dismount to kill lowbie NPC bears etc on the private servers I have played on, though on these retail videos he doesn't, perhaps he shouldn't do it? Remove some NPCs / alter path
https://db.excalibur.ws/?npc=17876
https://db.excalibur.ws/?npc=20548

https://youtu.be/euFbwTViw_Q?t=146
https://youtu.be/glZpWn3qmKI?t=412

**Current behaviour**:
Thrall dismounts to kill lowbie beasts on occasion 

**Expected behaviour**: 
Expected to not dismount, perhaps fewer NPCs / different path or a combination of the two

**Server Revision**: 
2349

**Comment by Easyfraggy** [comment]
He did this on retail also but might have too big agro range?

**Comment by Tenoutoften** [comment]
Possibly linked too https://github.com/Atlantiss/NetherwingBugtracker/issues/3420

**Comment by Tenoutoften** [comment]
Might be fixed after

[2443][Core/Creature]:
- Reduced minimum aggro radius - this will reduce the range at which low level mobs will attack much higher level targets

**Comment by duzyizly** [comment]
fixed @Tereneckla close please.
Thrall only leaves his mount once he's "exactly" at lowbie mob.
rev 3371.

**Comment by Tereneckla** [comment]
Not exactly TBC retail, but Thrall walks straight through a bear in this one
https://youtu.be/N6QzpEkS3tU?t=917

**Comment by The14me** [comment]
Not sure if that vid is from retail or not. Even if it's retail they change so many things from back then.
