### ISSUE TITLE
[Core Mechanic]Players on flying mounts in air should be immune to Frost Nova-effects & [Need research]Possibly other CC effects

### ISSUE THREAD

**Issue by Tenoutoften** [Atlantiss/NetherwingBugtracker#2999]
**Description**
This issue still needs research, I don't have video evidence for Stuns, Cyclone & Incapacitating effects - if anyone can provide video evidence of players on flying mounts, in air, from TBC either receiving stuns, incapacitating-effects or cycloned or showing immune feel free to help out.

While on a flying mount, and in air one should be immune to almost all crowd control effects:
* Stun
* Incapacitating effects(Repentance, maim, sap...)
* Fully immobilizing effects(Frost Bite, Frost Nova, Entangle Roots
* Cyclone

---
Currently you can do all of those, though you can't reliably use Death Coil(Not sure how to reproduce this, but done it twice) and Polymorph is immune already:
![cyclone](https://user-images.githubusercontent.com/34839199/48966960-12ac7080-efda-11e8-93d5-9336b5d5c4e6.png)
![frost nova](https://user-images.githubusercontent.com/34839199/48966961-13450700-efda-11e8-9a3d-c2cdcc8ec8d2.png)
![repentance](https://user-images.githubusercontent.com/34839199/48966962-13450700-efda-11e8-8470-af9b35b590da.png)
![roots](https://user-images.githubusercontent.com/34839199/48966963-13450700-efda-11e8-864b-ee3d66698dbe.png)
![stun](https://user-images.githubusercontent.com/34839199/48966964-13450700-efda-11e8-9761-bcde8bc0f00b.png)

Players on flying mounts, in air should be immune to Frost Nova-effects:
----
A frost mage Blizzards a group of enemy players, including one player on a flying mount in air and something shows up as "immune"
https://youtu.be/gl1y10OO-jU?t=151 This is most likely Frostbite, which is confirmed that the mage got here: https://youtu.be/gl1y10OO-jU?t=167

Considering a flying mount in air is immune to Frostbite, it goes to reason that it should also be immune to Frost Nova, Entangle Roots & similar effects. A good enough player would simply Frost Nova if a flying mount flew over him like https://youtu.be/gl1y10OO-jU?t=306

While when the flying mount is on the ground it is vulnerable to Frost Nova-effects: https://www.youtube.com/watch?v=Ba6Ty72eSH8&feature=youtu.be&t=695

----

You could polymorph people off their flying mounts in air during beta/first patch for a brief period of time
----
In the very first patch / Beta it seems like you could polymorph a player flying on a mount, this seem to have been hotfixed very quickly
![beta](https://user-images.githubusercontent.com/34839199/48970690-b106f900-f00f-11e8-9d6d-119301915cd7.png)
![tbc early-beta dismount](https://user-images.githubusercontent.com/34839199/48970693-bb28f780-f00f-11e8-9cfa-fdef2a27e2da.png)
![f7d16df1af889699427e49a00943dd1e](https://user-images.githubusercontent.com/34839199/48973052-423d9600-f037-11e8-8c02-f7c1489b1808.png)

-----
These comments aren't from TBC, but hopefully better than nothing.
There is definitely a difference between flying in the air and being landed on the ground, a flying mount should have the same conditions as a ground mount when landed(That means vulnerable to "everything"):
![difference between flying on ground and flying in air](https://user-images.githubusercontent.com/34839199/48966763-e0017880-efd7-11e8-80db-35c3e5bc9bf9.png)
![abd8ad50a3f2f3bcf62bd5595c408497](https://user-images.githubusercontent.com/34839199/48973065-68633600-f037-11e8-9793-f9838ce913f3.png)
![f759d7ed04e8c96afcf7e27112bab969](https://user-images.githubusercontent.com/34839199/48973069-7022da80-f037-11e8-8531-3e59d58bb06f.png)
![f8f8ed178410b93e2717ec38023cd7c9](https://user-images.githubusercontent.com/34839199/48973072-7e70f680-f037-11e8-9ac8-983ef04a0772.png)
![769416536cc81ede378b04e7cb6cf99e](https://user-images.githubusercontent.com/34839199/48973075-8f216c80-f037-11e8-8ac4-0985a7bbe636.png)

--
Apparently there is one thing that should dismount a player flying with a mount
[[Item]Goblin Rocket Launcher#23836](https://www.wowhead.com/item=23836/goblin-rocket-launcher)
![you can dismount flying](https://user-images.githubusercontent.com/34839199/48970709-d85dc600-f00f-11e8-8b91-fbe378d9b570.png)

Stuns & Incapacitating effects
---
![63b094f7e5a631b19ca476e73c1f68ee](https://user-images.githubusercontent.com/34839199/48973046-2afea880-f037-11e8-936f-7c50c5523c5e.png)
![abd8ad50a3f2f3bcf62bd5595c408497](https://user-images.githubusercontent.com/34839199/48973064-626d5500-f037-11e8-8326-3f55e1e4d283.png)

**Expected behaviour**: 
Players on flying mount in air should be immune to:
* Frost Nova-like effects
* Entangle Roots
* Stuns
* Incapacitating effects

**Server Revision**: 
2349

**Comment by Wolffenstein** [comment]
They are immune to various cc's currently, but not to roots/stuns, and they shouldn't be. I don't see a reason for opening issues about it without evidence, as from what we have found so far proved otherwise.

**Comment by Tenoutoften** [comment]
Players on flying mounts, in air should be immune to Frost Nova-effects:
----
A frost mage Blizzards a group of enemy players, including one player on a flying mount in air and something shows up as "immune"
https://youtu.be/gl1y10OO-jU?t=151 This is most likely Frostbite, which is confirmed that the mage got here: https://youtu.be/gl1y10OO-jU?t=167

Considering a flying mount in air is immune to Frostbite, it goes to reason that it should also be immune to Frost Nova, Entangle Roots & similar effects. A good enough player would simply Frost Nova if a flying mount flew over him like https://youtu.be/gl1y10OO-jU?t=306

While when the flying mount is on the ground it is vulnerable to Frost Nova-effects: https://www.youtube.com/watch?v=Ba6Ty72eSH8&feature=youtu.be&t=695

**Comment by Tenoutoften** [comment]
I have video evidence of frost bite procing on a flying mount in TBC showing immune, how is that not evidence?

**Comment by Tenoutoften** [comment]
Id be interested to review the evidence for flying mounts in air that they should be vulnerable to 
roots/stuns if you have any, then I can stop trying to search for it

**Comment by Wolffenstein** [comment]
Okay, I was wrong about roots. It would be good to have evidence for stuns but I will make the players immune to them too for now. Fixed in rev 2358.

**Comment by Tenoutoften** [comment]
Here is a comment from wrath, 3.2 (Release (US) September 22, 2009) saying players are immune to stuns and incapacitating effects on flying mount in air
![wrath stun](https://user-images.githubusercontent.com/34839199/48973517-51c1dc80-f041-11e8-948a-fbe21f5ac17f.png)

**Comment by Tenoutoften** [comment]
https://wow.gamepedia.com/index.php?title=Flight_Form&oldid=1662260
![rocket launcher](https://user-images.githubusercontent.com/34839199/48974720-2995a600-f060-11e8-887f-5f16c3ed836e.png)

Now why would they be immune to Goblin Rocket Launcher?
![8f4451f423457415275798fd150e2e6f](https://user-images.githubusercontent.com/34839199/48974728-521da000-f060-11e8-8973-0c85f1444e5e.png)
Because it has a stun...

**Comment by knasen88** [comment]
flying mounts are part of cancer that killed wow, wouldn't hurt to limit them a bit tbh. flying = invincibility = bad gameplay

**Comment by torrenzGH** [comment]
default to "not immune" unless evidence from the period is provided, as you have with goblin rocket launcher. wotlk and cata is when the bulk of flying "QoL" began, we shouldnt assume that behavior already existed prior

gamepedia article on sheep had the note about flying mounts being immune as early as 2007 with no changes since apart from pointing out the exception of grounded flying mounts
https://wow.gamepedia.com/index.php?title=Polymorph&oldid=899550

blastwave still working in wrath
https://youtu.be/WeZIyxrRXGo?t=1385
