### ISSUE TITLE
[Spell][Undead] Cannibalize

### ISSUE THREAD

**Issue by Ceago** [Atlantiss/NetherwingBugtracker#3]
Cannibalize is interrupted instantly when cast.  Does not seem to matter what health you are at.  Others mentioning the same issue in general chat.

**Comment by towneh** [comment]
![image](https://user-images.githubusercontent.com/25694892/45921121-59c99880-bea7-11e8-860b-61e383ba6e27.png)

**Comment by Wolffenstein** [comment]
Fixed in rev 2020.
