### ISSUE TITLE
Rogue throwing weapon 

### ISSUE THREAD

**Issue by AlteredAli** [Atlantiss/NetherwingBugtracker#30]
[//]: # (Enclose links to things related to the bug using http://wowhead.com or any other TBC database.)
[//]: # (You can use screenshot ingame to visual the issue.)
[//]: # (Write your tickets according to the format:)
[//]: # ([Quest][Azuremyst Isle] Red Snapper - Very Tasty!)
[//]: # ([NPC] Magistrix Erona)
[//]: # ([Spell][Mage] Fireball)
[//]: # ([Npc][Drop] Ghostclaw Lynx)
[//]: # ([Web] Armory doesnt work)

**Description**: 
Seemingly infinite ammo for thrown weapons
**Current behaviour**:

**Expected behaviour**: 

**Server Revision**:

**Comment by Maginerk** [comment]
seems to be working fine for me 1 throw=1durability lost as expected

**Comment by Wolffenstein** [comment]
No clue what this issue is about.
