### ISSUE TITLE
Escort quest popup$

### ISSUE THREAD

**Issue by Erodraeda** [Atlantiss/NetherwingBugtracker#300]
[//]: # (Enclose links to things related to the bug using http://wowhead.com or any other TBC database.)
[//]: # (You can use screenshot ingame to visual the issue.)
[//]: # (Write your tickets according to the format:)
[//]: # ([Quest][Azuremyst Isle] Red Snapper - Very Tasty!)
[//]: # ([NPC] Magistrix Erona)
[//]: # ([Spell][Mage] Fireball)
[//]: # ([Npc][Drop] Ghostclaw Lynx)
[//]: # ([Web] Armory doesnt work)

**Description**: 
I was in a group with another person, that was in another map. He started an escort quest, in Stonetalon Mountains. I was in Orgrimmar, and my friend were in Ghostlands, both in the group. Even tho we were in different maps, the pop up to accept the quest appeared for both of us.
**Current behaviour**:
Escort quest accept pop-up showing for people on other maps (if on the same group)
**Expected behaviour**: 
Pop-up should only appear if close to the area the quests starts.
**Server Revision**:

**Comment by Wolffenstein** [comment]
Fixed in rev 2040.
