### ISSUE TITLE
[NPC][Karazhan][Spell] Attumen the Huntsman's Berserker Charge Spell

### ISSUE THREAD

**Issue by tepex0** [Atlantiss/NetherwingBugtracker#3001]
**Description**: After merging, Attumen does not cast charge on anyone. We had a warrior using his range weapon from ~10 yards away. Attumen never used his charge during the fight.

http://wowwiki.wikia.com/wiki/Berserker_Charge says he should cast charge with a minimum range of 8 yards.

**Current behaviour**: Does not cast charge on anyone, including people both in melee and far away. 

**Expected behaviour**: Should cast charge on atleast people 8+ yards away, unsure if he should cast charge on people stacked up.

**Server Revision**: 2356

**Comment by Wolffenstein** [comment]
He was casting charge just fine for all previous groups. I would need a video to see what exactly went wrong.

**Comment by Drayo** [comment]
Can be closed, he does charge after merging.

**Comment by devo6969** [comment]
Saw nothing wrong with this on the PTR, casted charged 5 seconds after he merged 🤷
