### ISSUE TITLE
[NPC] Krixel Pinchwhistle is spawned

### ISSUE THREAD

**Issue by lynxzor** [Atlantiss/NetherwingBugtracker#3002]
**Description**: ID: 23396 should be removed until PVP Season 2
**Current behaviour**: Spawned
**Expected behaviour**: Spawn in Season 2
**Server Revision**: 2356
![wowscrnshot_112418_213349](https://user-images.githubusercontent.com/795881/48973271-9777a880-f033-11e8-8885-5a130ab4cfe6.jpg)

**Comment by aresbrutus** [comment]
Fixed in rev `Aterpoll`
