### ISSUE TITLE
[Item] PVP water available

### ISSUE THREAD

**Issue by lynxzor** [Atlantiss/NetherwingBugtracker#3003]
**Description**: Star's Tears (32453) & Star's Lament (32455) are available for purchase when it's a 2.1 item.
**Current behaviour**: Can purchase before 2.1
**Expected behaviour**: Purchase only in 2.1 onwards per the official patch notes
**Server Revision**: 2356
![wowscrnshot_112418_215705](https://user-images.githubusercontent.com/795881/48973304-4320f880-f034-11e8-92d7-2dd58aaaba0c.jpg)

**Comment by aresbrutus** [comment]
Fixed in rev `Aterpol`
