### ISSUE TITLE
[NPC] Prince Malchezaar Low Dmg

### ISSUE THREAD

**Issue by WarriorTSW** [Atlantiss/NetherwingBugtracker#3004]
[//]: # (Enclose links to things related to the bug using http://wowhead.com or any other TBC database.)
[//]: # (You can use screenshot ingame to visual the issue.)
[//]: # (Write your tickets according to the format:)
[//]: # ([Quest][Azuremyst Isle] Red Snapper - Very Tasty!)
[//]: # ([NPC] Magistrix Erona)
[//]: # ([Spell][Mage] Fireball)
[//]: # ([Npc][Drop] Ghostclaw Lynx)
[//]: # ([Web] Armory doesnt work)
[//]: # (To find server revision type `.server info` command in the game chat.)

**Description**: 
Boss its me for under 10 dmg.
**Current behaviour**:
While wiping I ran to the door. Had my back facing the boss and the boss was hitting me for very little.
![image](https://user-images.githubusercontent.com/23043262/48973343-2638f500-f035-11e8-932d-3558bf3effe8.png)

**Expected behaviour**: 
Hitting me like normal regardless of which direction im facing or where in the room i am
**Server Revision**: 
2356

**Comment by Tenoutoften** [comment]
Could this be due to stacking negative attack power debuffs - although if scripted correctly that shouldn't explain this since there is a cap on how much damage reduction such debuffs can grant

**Comment by Easyfraggy** [comment]
It's not due to AP overflow. it's properly capped at 0 - need more information - What phase was this in?

![image](https://user-images.githubusercontent.com/36134067/48979745-7fe60180-f0bf-11e8-895a-448cd71c9481.png)

**Comment by WarriorTSW** [comment]
Heres the video from the stream. 
https://www.twitch.tv/videos/340185074##
02:52:50
I am sitting to try and die faster from crits.

**Comment by Easyfraggy** [comment]
Something goes wrong with AP scaling during transition - 

Transition with no demo shout:

![image](https://user-images.githubusercontent.com/36134067/48980258-e3bff880-f0c6-11e8-8eae-f5299dd09a62.png)

Apply demo after transition:

![image](https://user-images.githubusercontent.com/36134067/48980264-f6d2c880-f0c6-11e8-9da3-84af8297880f.png)


If I transition him with Demo up:

![image](https://user-images.githubusercontent.com/36134067/48980238-af4c3c80-f0c6-11e8-8953-9022ba80f059.png)

Once demo fades 

![image](https://user-images.githubusercontent.com/36134067/48980254-d0149200-f0c6-11e8-8a5b-b7914bdd2858.png)

Reapply demo

![image](https://user-images.githubusercontent.com/36134067/48980268-10741000-f0c7-11e8-8a30-b74775ba5afa.png)

**Comment by gabbat** [comment]
that is absolutely bonkers, but in line with other reports on AP + debuffs. 
I think there is two parts: 
- ap with debuffs in general beeing weird (even tho tbc was exactly like that)
and
- prince p2 dmg beeing absolutely bugged. I am not sure if this only happens when using demo shout or otherwise would happen as well

**Comment by Manaci** [comment]
Fixed
