### ISSUE TITLE
[NPC][Karazhan] Moroes attacking while vanished

### ISSUE THREAD

**Issue by tepex0** [Atlantiss/NetherwingBugtracker#3005]
**Description**: Moroes will vanish to garrote a target, but sometimes his model would stay and keep attacking the tank. Moroes would shimmer as if about to go invis, and would gain the vanish debuff. Someone would still get garroted when this happened.

**Current behaviour**: Will sometimes not fully vanish and keep attacking the tank while garroting a random target.

**Expected behaviour**: Should always go fully invisible and stop attacking the tank while garroting a target.

**Server Revision**: 2356

**Comment by Easyfraggy** [comment]
Probably a byproduct of the bug reported on internal tracker about Moroes in https://github.com/Atlantiss/AtlantissTBCBT/issues/4368

**Comment by Wolffenstein** [comment]
He doesn't attack/garrote while vanished. If he did that, that means he just went out of vanish really quickly (which can happen).
