### ISSUE TITLE
[NPC] Astral Flare summoned by trash has too much HP

### ISSUE THREAD

**Issue by Mikik3jr** [Atlantiss/NetherwingBugtracker#3006]
[//]: # (Enclose links to things related to the bug using http://wowhead.com or any other TBC database.)
[//]: # (You can use screenshot ingame to visual the issue.)
[//]: # (Write your tickets according to the format:)
[//]: # ([Quest][Azuremyst Isle] Red Snapper - Very Tasty!)
[//]: # ([NPC] Magistrix Erona)
[//]: # ([Spell][Mage] Fireball)
[//]: # ([Npc][Drop] Ghostclaw Lynx)
[//]: # ([Web] Armory doesnt work)
[//]: # (To find server revision type `.server info` command in the game chat.)

**Description**: 
This Astral Flare is summoned from Arcane Protectors in Karazhan and NOT FROM CURATOR

**Current behaviour**:
The flares have like 20-25k HP like the ones summoned from Curator

**Expected behaviour**: 
I don't think the flares from trash should be the same as curator.

**Server Revision**: 
2356

**Comment by Wolffenstein** [comment]
Fixed in rev 2358.
