### ISSUE TITLE
[NPC][Karazhan][Spell] Moroes' gouge not being broken by Blessing of Sacrifice

### ISSUE THREAD

**Issue by tepex0** [Atlantiss/NetherwingBugtracker#3007]
**Description**: During the Moroes encounter, he will gouge the main tank and go to second highest on threat. Putting Blessing of Sacrifice on a garroted raid member should allow a Prot pally to self-break gouge and regain threat on Moroes.

http://karamoroes.blogspot.com/2007/10/moroes-fight.html
from october 2007, not the best source but says blessing of sacrifice should break gouge

**Current behaviour**:Gouge does not break from Blessing of Sacrifice self-damage. Tested on both a garroted target and on a second tank taking hits from a Moroes side-mob.

**Expected behaviour**: Moroes' gouge should break when a paladin takes damage from blessing of sacrifice, no matter how the sac'd target takes damage.

**Server Revision**: 2356

**Comment by Easyfraggy** [comment]
Could be global issue with incapacitate effects and BoS?

**Comment by feuerkind** [comment]
@Easyfraggy you said Moroes' Gouge was a stun in database ond Discord. 
According to http://wowwiki.wikia.com/wiki/Patch_2.1.2_(undocumented_changes) it was an incapacitate effect pre 2.1.2. So you should be able to break it with damage, berserker rage ect. in 2.0.
