### ISSUE TITLE
[NPC] Arcane Protector weird hitbox

### ISSUE THREAD

**Issue by Mikik3jr** [Atlantiss/NetherwingBugtracker#3008]
[//]: # (Enclose links to things related to the bug using http://wowhead.com or any other TBC database.)
[//]: # (You can use screenshot ingame to visual the issue.)
[//]: # (Write your tickets according to the format:)
[//]: # ([Quest][Azuremyst Isle] Red Snapper - Very Tasty!)
[//]: # ([NPC] Magistrix Erona)
[//]: # ([Spell][Mage] Fireball)
[//]: # ([Npc][Drop] Ghostclaw Lynx)
[//]: # ([Web] Armory doesnt work)
[//]: # (To find server revision type `.server info` command in the game chat.)

**Description**: 
After curator.

**Current behaviour**:
The hitbox is weird. They have like 15y attack range. The Protector was almost top of the ramp, I was middle on the stairs and I died from a simple attack.
![wowscrnshot_112418_230554](https://user-images.githubusercontent.com/43505031/48973427-4ff71980-f03f-11e8-952a-e625f92f9ef1.jpg)

**Expected behaviour**: 
I think it shouldn't have this big attack range. All evidence is I have is a clip from 2013 (on 0.25 speed)
at 15:02 when he runs past the protectors:
https://www.youtube.com/watch?v=lS6xM0-JF0o

**Server Revision**: 
2356

**Comment by Wolffenstein** [comment]
Fixed in rev 2359.
