### ISSUE TITLE
[NPC] Arcane Protector casts Fist of Stone too frequently

### ISSUE THREAD

**Issue by Mikik3jr** [Atlantiss/NetherwingBugtracker#3009]
[//]: # (Enclose links to things related to the bug using http://wowhead.com or any other TBC database.)
[//]: # (You can use screenshot ingame to visual the issue.)
[//]: # (Write your tickets according to the format:)
[//]: # ([Quest][Azuremyst Isle] Red Snapper - Very Tasty!)
[//]: # ([NPC] Magistrix Erona)
[//]: # ([Spell][Mage] Fireball)
[//]: # ([Npc][Drop] Ghostclaw Lynx)
[//]: # ([Web] Armory doesnt work)
[//]: # (To find server revision type `.server info` command in the game chat.)

**Description**: 
Karazhan after curator.

**Current behaviour**:
They recast 2s after the effect wore off them.

**Expected behaviour**: 
They already deal 8.5k damage (not crush, not crit) into my holy paladin 12k armor, this effetct almost 1 hit kills our 15k hp tank. They have this effect up too many times.

**Server Revision**: 
2356

**Comment by Wolffenstein** [comment]
Fixed in rev 2359.
