### ISSUE TITLE
[Quest][Sunstrider Isle] Solanian's Belongings wrong text description

### ISSUE THREAD

**Issue by leon12345** [Atlantiss/NetherwingBugtracker#301]
[//]: # (Enclose links to things related to the bug using http://wowhead.com or any other TBC database.)
[//]: # (You can use screenshot ingame to visual the issue.)
[//]: # (Write your tickets according to the format:)
[//]: # ([Quest][Azuremyst Isle] Red Snapper - Very Tasty!)
[//]: # ([NPC] Magistrix Erona)
[//]: # ([Spell][Mage] Fireball)
[//]: # ([Npc][Drop] Ghostclaw Lynx)
[//]: # ([Web] Armory doesnt work)

**Description**: 
wrong description in quest log
https://gyazo.com/391b08208c356861bc42fd3be138850d
https://gyazo.com/b2b13c901b5192dcb9dc750a2b389dcf
**Current behaviour**:
it doesnt show item names with the counter
**Expected behaviour**: 
it should show the item names
**Server Revision**: 
2028

**Comment by aresbrutus** [comment]
Please provide us with info WHAT is wrong. I checked the quest text and it seemed fine.

**Comment by Wolffenstein** [comment]
Delete your client cache folder.
