### ISSUE TITLE
[Spell] Skeletal Waiter Brittle Bones does not remove armor

### ISSUE THREAD

**Issue by Mikik3jr** [Atlantiss/NetherwingBugtracker#3010]
[//]: # (Enclose links to things related to the bug using http://wowhead.com or any other TBC database.)
[//]: # (You can use screenshot ingame to visual the issue.)
[//]: # (Write your tickets according to the format:)
[//]: # ([Quest][Azuremyst Isle] Red Snapper - Very Tasty!)
[//]: # ([NPC] Magistrix Erona)
[//]: # ([Spell][Mage] Fireball)
[//]: # ([Npc][Drop] Ghostclaw Lynx)
[//]: # ([Web] Armory doesnt work)
[//]: # (To find server revision type `.server info` command in the game chat.)

**Description**: 
Skeletal Waiters cast it in Karazhan. It reduces your armor to 0
https://www.wowhead.com/spell=32441/brittle-bones

**Current behaviour**:
![image](https://user-images.githubusercontent.com/43505031/48973506-01e31580-f041-11e8-9cff-5ece506a7f68.png)

**Expected behaviour**: 
They should remove armor.

**Server Revision**: 
2356

**Comment by Wolffenstein** [comment]
Fixed in rev 2359.
