### ISSUE TITLE
[Item] PVP Gem costs

### ISSUE THREAD

**Issue by lynxzor** [Atlantiss/NetherwingBugtracker#3011]
**Description**: Gem costs should be:
2.1 patch double nerfed costs:
28125 -> 8100 ->6885 honor
31500 -> 10000 -> 8500 honor
**Current behaviour**: Post 2.1 costs
**Expected behaviour**: 2.0 Gem costs of 28125 & 31500 honor
**Server Revision**: 2356
![wowscrnshot_112418_213650](https://user-images.githubusercontent.com/795881/48973523-04417180-f039-11e8-8527-641181dc0e83.jpg)

Sources
2.1 Offical Patch notes
Pre
http://web.archive.org/web/20070513234643/http://www.thottbot.com:80/i28118
http://web.archive.org/web/20070516231812/http://www.thottbot.com:80/i28362
http://web.archive.org/web/20070517171419/http://www.thottbot.com:80/i28120
http://web.archive.org/web/20070519192303/http://www.thottbot.com:80/i28363
http://web.archive.org/web/20070514075537/http://www.thottbot.com:80/i28123
http://web.archive.org/web/20070515113015/http://thottbot.com:80/i28119
Post
http://web.archive.org/web/20070701180501/http://www.thottbot.com:80/i28118
http://web.archive.org/web/20070708204513/http://www.thottbot.com:80/i28362
http://web.archive.org/web/20070706175847/http://www.thottbot.com:80/i28120
http://web.archive.org/web/20070712010743/http://www.thottbot.com:80/i28363
http://web.archive.org/web/20070707140807/http://www.thottbot.com:80/i28123
http://web.archive.org/web/20070703203706/http://www.thottbot.com:80/i28119

**Comment by Evolvee** [comment]
@aresbrutus these epic gems shouldnt even be there

**Comment by aresbrutus** [comment]
Due to 2.4.3 client limitations the costs have been increased to 22950 cost instead of 31500 and 19125 instead of 28125 in rev `Aterpol`
