### ISSUE TITLE
[Spell] Skeletal Waiter Brizzle Bones on feral druid

### ISSUE THREAD

**Issue by Mikik3jr** [Atlantiss/NetherwingBugtracker#3012]
[//]: # (Enclose links to things related to the bug using http://wowhead.com or any other TBC database.)
[//]: # (You can use screenshot ingame to visual the issue.)
[//]: # (Write your tickets according to the format:)
[//]: # ([Quest][Azuremyst Isle] Red Snapper - Very Tasty!)
[//]: # ([NPC] Magistrix Erona)
[//]: # ([Spell][Mage] Fireball)
[//]: # ([Npc][Drop] Ghostclaw Lynx)
[//]: # ([Web] Armory doesnt work)
[//]: # (To find server revision type `.server info` command in the game chat.)

**Description**: 
When our feral tank druid got this debuff.

**Current behaviour**:
After turning back from skeleton form the druid went into human form, but still was in bear form:
![wowscrnshot_112418_201817](https://user-images.githubusercontent.com/43505031/48973522-64d4ac80-f041-11e8-9fee-77ed327ed835.jpg)
![wowscrnshot_112418_201844](https://user-images.githubusercontent.com/43505031/48973525-67cf9d00-f041-11e8-8aee-d37bad20267b.jpg)

**Expected behaviour**: 
Feral druids should turn back to bear, instead of their original humanoid form in visually.

**Server Revision**: 
2356

**Comment by Tereneckla** [comment]
Fixed
