### ISSUE TITLE
[NPC] Doris Volanthius is spawned

### ISSUE THREAD

**Issue by lynxzor** [Atlantiss/NetherwingBugtracker#3013]
Description: ID: 32385 should be removed until PVP Season 3
Current behaviour: Spawned
Expected behaviour: Spawn in Season 3 and sell correct gear for the season
Server Revision: 2356
![wowscrnshot_112418_230042](https://user-images.githubusercontent.com/795881/48973691-c85cdb00-f03d-11e8-8de3-aa5fafd809ad.jpg)

**Comment by aresbrutus** [comment]
Fixed in rev `Aterpoll`
