### ISSUE TITLE
Karazhan Opera Event "cleared" 

### ISSUE THREAD

**Issue by nycheia** [Atlantiss/NetherwingBugtracker#3015]
**Description**: 
The door was open, the curtains was up, the NPC had the line "Excellent performance" etc. the first time we got to the opera event. 
Time stamped video of it: https://www.twitch.tv/videos/339705929?t=01h16m19s

I dont remember the revision, but this was done at around 21:00 CET last night 23/11

**Comment by Manaci** [comment]
Fixed
