### ISSUE TITLE
[NPC]Scarlet Paladin#1834 lacks [Spell]Holy Light & Seal of Protection

### ISSUE THREAD

**Issue by Tenoutoften** [Atlantiss/NetherwingBugtracker#3016]
**Description**: 
[[NPC]Scarlet Paladin#1834](https://www.wowhead.com/npc=1834/scarlet-paladin#comments) looks to be lacking both Holy Light & Seal of Protection(https://db.excalibur.ws/?spell=17177 / https://www.wowhead.com/spell=17177/seal-of-protection#comments)

Video of NW behavior [here](https://www.youtube.com/watch?v=VRuOmjrcbiM&feature=youtu.be)
![b31a842c60f3266a21031c3afbae6acf](https://user-images.githubusercontent.com/34839199/48974798-08828480-f063-11e8-8cb5-abf00e1534ae.png)

**Current behaviour**:
Doesn't seem to use these abilities

**Expected behaviour**: 
Expected to also use Holy Light & Seal of Protection

**Server Revision**: 
2356

**Comment by Evolvee** [comment]
rev xxd
