### ISSUE TITLE
[NPC] The Maker

### ISSUE THREAD

**Issue by AxeCell** [Atlantiss/NetherwingBugtracker#3017]
**Description**: 
The Maker is the first boss you face in Blood Furnace.

**Current behaviour**:
During the Blood Furnace heroic encounter(and perhaps normal), the boss doesn't knock up the tank which leads to a threat drop.

**Expected behaviour**: 
Should drop all the threat on the tank by knocking him up as shown in this clip: https://youtu.be/VWYuV82PMAk?t=107

**Server Revision**: 
2345

**Comment by Easyfraggy** [comment]
Maybe you got resists? There are extremely few abilities that drop all threat - this is not one of them.

https://gfycat.com/DearCompleteHairstreakbutterfly

**Comment by AxeCell** [comment]
Perhaps it doesn't drop threat completely, but during the fight on **heroic** the only visibly working ability was his Mind-control. I did him twice without ever experiencing his knock-up threat drop(which happens in the WowHobbs video considering he runs to other party members each time Hoobs is knocked up). Might've gotten resisted, or perhaps the frequency is set to too low.
