### ISSUE TITLE
[Spell] Allergies

### ISSUE THREAD

**Issue by AxeCell** [Atlantiss/NetherwingBugtracker#3018]
**Description**: 
This ability is used by Underbog Shambler, who's found in Underbog.

**Current behaviour**:
The ability didn't proc once during its entire duration when applied to me.

**Expected behaviour**: 
I remember it having a decently frequent knockdown effect.

**Server Revision**: 
2345

**Comment by Easyfraggy** [comment]
It currently gets removed on first stun it applies - need evidence of how it should work.

**Comment by SwiftieTBC** [comment]
https://youtu.be/9T1gGO3_eZo?t=422 although more recent patch the way easy described is correct. ill try to look for earlier footage too see if it was changed or if it was always a one hit debuff

**Comment by Tenoutoften** [comment]
![46cedc892e7e178ff16a85cf7b4e604f](https://user-images.githubusercontent.com/34839199/48979689-f9c9bb00-f0be-11e8-812b-f63e59d37e6d.png)

**Comment by AxeCell** [comment]
Upon revisiting Underbog I had the debuff reapplied to me and the effect would expire once I got knocked down the first time.

**Comment by Tereneckla** [comment]
Couldn't find any change to that ability in patch notes.
Works as described by comments / the video.
