### ISSUE TITLE
[NPC] Swamplord Musel'ek

### ISSUE THREAD

**Issue by AxeCell** [Atlantiss/NetherwingBugtracker#3019]
**Description**: 
Topic is related to Swamplord Musel'ek who's found within Underbog.

**Current behaviour**:
Once dead, you don't have to finish off Claw to recieve the loot from the boss.

**Expected behaviour**: 
Not much proof to go by, but is this interaction intended?

**Server Revision**: 
2345

**Comment by Easyfraggy** [comment]
99% sure this is intended and how it on retail. Need evidence to the contrary.

**Comment by Tenoutoften** [comment]
When I did this dungeon the people in it agreed that you shouldn't have to finish off claw as well

**Comment by Easyfraggy** [comment]
![image](https://user-images.githubusercontent.com/36134067/48979402-aeada900-f0ba-11e8-9eeb-8c753bae931d.png)

There are clearly sparkles on the corpse on both videos after Swamplord dies and Claw is still alive and hostile.
