### ISSUE TITLE
[NPC] Warp Splinter

### ISSUE THREAD

**Issue by AxeCell** [Atlantiss/NetherwingBugtracker#3022]
**Description**: 
Topic is related to Warp Splinter and his arcane volley ability in Botanica heroic.

**Current behaviour**:
Arcane Volley either deals too much damage or operates wrongly. It will currently hit everyone within range in a 360 degree radius for 6k damage or so.

**Expected behaviour**: 
Should hit less targets depending on circumstance while also hit for less than 6k. Video examples listed below.

Doesn't hit anyone but the tank: https://youtu.be/0mywgZKveKw?t=523
Hits the resto shaman only and possibly the tank: https://youtu.be/0mywgZKveKw?t=523
Seems to be only hitting the tank in this video: https://www.youtube.com/watch?v=KGFrSMBMXzM
Here it hits everyone, but it deals no damage, although later it's random: https://youtu.be/1IqyxTuxUBU?t=42
Here's possibly the oldest video I could find, but the damage is way lower than the current 6k: https://www.youtube.com/watch?v=T-gbAfL_Ytk

**Server Revision**: 
2345

**Comment by Corrozus** [comment]
His Arcane Volley is dealing correct pre-nerf damage on heroic mode. Quoting a comment from [this thread](https://web.archive.org/web/20070315114326/http://www.wowhead.com:80/?npc=17977#z0z) from wowhead, march 15th 2007.

> He has been considerably buffed for heroic mode.

>1) His arcane aoe now hits everyone. It doesn't matter if you are tanking him against the wall and having him face away from the party. The arcane bolts seem to hit people behind him now.

>2) The damage from the aoe is INSANE now. It was hitting everyone for 5800-6200 damage. I hope you have an extremely decked out healer for this or are packing some serious arcane resist. As it stands now.... healing for this guy is close to impossible.

There's a large difference in damage from normal to heroic. It doesnt get nerfed until [patch 2.1](http://wowwiki.wikia.com/wiki/Patch_2.1.0)

> Warp Splinter's Arcane Volley damage has been reduced on Heroic.

**Comment by zauru7** [comment]
on HC you're pretty much forced to tank him on the bridge where the volley is only 180* arc forward facing

**Comment by Easyfraggy** [comment]
First and second video is the same video =) And it's post 2.1 + nothing to indicate that it is heroic.
3rd video - nothing to indicate that it is heroic.
4th video - nothing to indicate that it is heroic.
5th video - nothing to indicate that it is heroic.

**Comment by zauru7** [comment]
![00](https://user-images.githubusercontent.com/44526051/48979752-91c7a480-f0bf-11e8-970e-c08d3d807159.PNG)
given how contradictory the pre 2.1 comments about this boss is, it was probably quite buggy

**Comment by Wolffenstein** [comment]
Pre-nerf (2.0) Arcane Volley on Heroic mode:

**Effect 0: Id 2 (SPELL_EFFECT_SCHOOL_DAMAGE)
BasePoints = 5550 to 6451 x 0,00**

Don't see anything wrong here.

**Comment by AxeCell** [comment]
I would like to add that we did use totems and pets, so for all I know the mechanic might work the way Zauru7 pointed out. It's mostly just a confusing mechanic.
