### ISSUE TITLE
[NPC] Ethereal Sorcerer

### ISSUE THREAD

**Issue by AxeCell** [Atlantiss/NetherwingBugtracker#3023]
**Description**: 
Topic is related to Ethereal Sorcerer(not to be confused with Ethereal Spellbinders) and his spell interactions in Mana-tombs heroic.

**Current behaviour**:
Once sheeped on pull, the NPC wont summon his elementals after releasing, and he'll also never use his arcane spell(s).

**Expected behaviour**: 
Should summon his elementals upon being freed and frequently use his arcane spell(s).

**Server Revision**: 
2349

**Comment by idsss** [comment]
had the same issue with fear as cc earlier. both sorcerers and spellbinders didn't summon any elementals after (didn't pay much attention to their spells tho). Same after letting them hit our tank for a few mins/bringing them low hp, "tried" wiping too.. :D
also, seemed like one spellbinder summoned his elementals while being hunter trapped, but couldn't reproduce that

**Comment by Tereneckla** [comment]
Fixed
