### ISSUE TITLE
[NPC] Raging Skeleton

### ISSUE THREAD

**Issue by AxeCell** [Atlantiss/NetherwingBugtracker#3024]
**Description**: 
Topic is related to Raging Skeletons found in Auchenai Crypts heroic.

**Current behaviour**:
Their regular movement speed is very slow to the point where any ranged class can easily kite them to death.

**Expected behaviour**: 
The skeletons should be fast enough for a tank to be needed to tank them while they're not self buffing themself with a damage boost/movement slow buff. 
This is the earliest video i could find showcasing their movement: https://youtu.be/ZCR0ZENXxdc?t=235

**Server Revision**: 
2356

**Comment by Easyfraggy** [comment]
They do seem a bit too slow.

**Comment by Evolvee** [comment]
rev xxd
