### ISSUE TITLE
[NPC] Entropic Eye

### ISSUE THREAD

**Issue by AxeCell** [Atlantiss/NetherwingBugtracker#3025]
**Description**: 
Topic is related to Entropic Eye in Arcatraz heroic.

**Current behaviour**:
There are currently no Entropic Eye enemies in Zereketh the Unbound's room.

**Expected behaviour**: 
There should be 2 Entropic Eye enemies in Zereketh the Unbound's room.

**Server Revision**: 
2356

**Comment by Evolvee** [comment]
wtf is this shit @Wolffenstein 
when u teleport there

![image](https://user-images.githubusercontent.com/1942409/48978335-83bb5900-f0aa-11e8-95ea-8ccf3132e0b2.png)

these eyes periodically "fall" through the ground inch by inch and eventually disappear fully xdddd

when the "process" is over, the room is just this:
![image](https://user-images.githubusercontent.com/1942409/48978344-9cc40a00-f0aa-11e8-8b41-25de19e44472.png)

no bosses, no eyes, nothing... nada

**Comment by Evolvee** [comment]
and the npc in question has 
![image](https://user-images.githubusercontent.com/1942409/48978354-b8c7ab80-f0aa-11e8-97c0-0dae762d369c.png)

so it doesnt spawn in hero right now, idk if intended

**Comment by Easyfraggy** [comment]
![image](https://user-images.githubusercontent.com/36134067/48978646-dac32d00-f0ae-11e8-8c50-c5e378491a40.png)

Can't replicate

**Comment by Easyfraggy** [comment]
They are probably just spawned slightly below ground.

**Comment by Brasso** [comment]
Arcatraz was fine when we did it last night. All the mobs were there.

**Comment by Evolvee** [comment]
rev xxd
