### ISSUE TITLE
[NPC] Unbound Devastator

### ISSUE THREAD

**Issue by AxeCell** [Atlantiss/NetherwingBugtracker#3027]
**Description**: 
Topic is related to the first Unbound Devastator encountered in the duo boss room in Arcatraz heroic.

**Current behaviour**:
He's currently "patrolling" in a 5 yard circle close to a nearby stealthed Succubus. You can't pull him without attracting said succubus.

**Expected behaviour**: 
Unbound Devastator is supposed to patrol on the far left side so he can be pulled separately from the invisible succubus.

**Server Revision**: 
2356

**Comment by sifiuocz** [comment]
https://github.com/Atlantiss/NetherwingBugtracker/issues/2836
