### ISSUE TITLE
[NPC][Underbog] Windcaller Claw attack animation stuck after npc turns friendly

### ISSUE THREAD

**Issue by Easyfraggy** [Atlantiss/NetherwingBugtracker#3029]
**Description**: 

**Current behaviour**:
On Swamplord fight:
17826 
after beating Claw to submission you get stuck in attack animation. He also does ding animation when turning friendly.
![image](https://user-images.githubusercontent.com/36134067/48979500-039def00-f0bc-11e8-90c7-754418db788d.png)

**Expected behaviour**: 
Stops attack animation.

**Server Revision**: 2356

**Comment by devo6969** [comment]
Could not recreate on the PTR. Seems fixed
