### ISSUE TITLE
Guild log

### ISSUE THREAD

**Issue by DarthNekr0s** [Atlantiss/NetherwingBugtracker#303]
**Description**:  shows up blank even after having it open for a long time waiting to see if itll show

**Current behaviour**: nothing in guild log

**Expected behaviour**:  yesterday was working, everything was showing up as usual

**Server Revision**: 
![untitled](https://user-images.githubusercontent.com/16113944/45934673-e4fc7880-bfe4-11e8-98fb-684ca5bc9564.png)

**Comment by yihu0259** [comment]
Still have the same bug on my guild. Nothing on the log

**Comment by frenkzenith** [comment]
Same in my guild

**Comment by frenkzenith** [comment]
I have the same bug in my guild

**Comment by Tereneckla** [comment]
fixed
