### ISSUE TITLE
[Spell][Warlock] Conflagrate

### ISSUE THREAD

**Issue by PolarCookie** [Atlantiss/NetherwingBugtracker#3031]
**Description**: 
http://db.hellfire-tbc.com/?spell=30912
`Ignites a target that is already afflicted by your Immolate, dealing 579 to 722 Fire damage and consuming the Immolate spell.`

**Current behaviour**:
If a fellow warlock applies Immolate to a target, you can freely use Conflagrate and it will not consume the Immolate. Conflagrate will consume your own Immolate.

**Expected behaviour**: 
Conflagrate should only activate on your own Immolate.

**Server Revision**: 
2356

**Comment by Wolffenstein** [comment]
Fixed in rev 3429.
