### ISSUE TITLE
[Quest] [Shadowmoon Valley] To Catch a Thistlehead - Envoy Icarius does not despawn if not killed

### ISSUE THREAD

**Issue by Grookshank** [Atlantiss/NetherwingBugtracker#3033]
![grafik](https://user-images.githubusercontent.com/9802675/48981638-7fa63000-f0d8-11e8-834f-97d7841250ee.png)

**Description**: 
Envoy Icarius spawns during the quest To Catch a Thistlehead. If he is not killed during the quest, he just stays there inactive, unattackable.

**Current behaviour**:
See above.

**Expected behaviour**: 
He should despawn after xxx minutes.

**Server Revision**: 
Beta 25.11.2018

**Comment by Bildo** [comment]
fixed in rev 2410
