### ISSUE TITLE
UBRS door won't open with the required key

### ISSUE THREAD

**Issue by Esploye** [Atlantiss/NetherwingBugtracker#3034]
[//]: # (Enclose links to things related to the bug using http://wowhead.com or any other TBC database.)
[//]: # (You can use screenshot ingame to visual the issue.)
[//]: # (Write your tickets according to the format:)
[//]: # ([Quest][Azuremyst Isle] Red Snapper - Very Tasty!)
[//]: # ([NPC] Magistrix Erona)
[//]: # ([Spell][Mage] Fireball)
[//]: # ([Npc][Drop] Ghostclaw Lynx)
[//]: # ([Web] Armory doesnt work)
[//]: # (To find server revision type `.server info` command in the game chat.)

**Description**: When you approach the door to UBRS the door says it requires the item "Seal of Ascension" but when you right click on the door it won't open even though i have the ring.

**Current behaviour**: Door won't open with key

**Expected behaviour**: Door should open with key

**Server Revision**: 2356

**Comment by Easyfraggy** [comment]
UBRS is closed on purpose like all other lvl 60 raids.
