### ISSUE TITLE
Priest's spell Levitate animation wrong

### ISSUE THREAD

**Issue by Nicemann1089** [Atlantiss/NetherwingBugtracker#3035]
[//]: # (Enclose links to things related to the bug using http://wowhead.com or any other TBC database.)
[//]: # (You can use screenshot ingame to visual the issue.)
[//]: # (Write your tickets according to the format:)
[//]: # ([Quest][Azuremyst Isle] Red Snapper - Very Tasty!)
[//]: # ([NPC] Magistrix Erona)
[//]: # ([Spell][Mage] Fireball)
[//]: # ([Npc][Drop] Ghostclaw Lynx)
[//]: # ([Web] Armory doesnt work)
[//]: # (To find server revision type `.server info` command in the game chat.)

https://drive.google.com/file/d/1Z9TyyxsjS2ODFFpCW87glczjtABbqAsG/view?usp=drivesdk

**Current behaviour**: The character is only levitating in the correct animation when not moving. When moving it is just a usual running animation a few feet above the ground.

**Expected behaviour**: While the levitate buff is up, the animation should always be "levitating".

**Server Revision**: 2361

**Comment by Easyfraggy** [comment]
Please provide retail proof.

**Comment by Nicemann1089** [comment]
it is blizzlike, after what I just saw in videos. please close, thx
