### ISSUE TITLE
[Spell][Priest] Mind Flay

### ISSUE THREAD

**Issue by Gooback** [Atlantiss/NetherwingBugtracker#3036]
**Description**:
On many types of mobs Mind Flay will start to cast but immediately fail. I't will cost mana and not do any dmg.

**Comment by Easyfraggy** [comment]
Please provide more info.
Type .npc info when targetting one of these mobs in question and if you can provide SS/video.

**Comment by towneh** [comment]
https://i.imgur.com/ERX42G1.gifv

I've managed to replicate this issue. It doesn't seem to be linked to spell resist, as there is no resist message in the combat log, I have tried this with both uncapped and capped hit rating (76 with talents).

Issue appears to be that the casting animation goes off with no spell being cast as you can see in the gif.

**Comment by Easyfraggy** [comment]
seems to be when you restart mind flay cast right after cancelling previous one with micro movement - not at all the same.

**Comment by Easyfraggy** [comment]
Oh - was the OP trying to mind flay critters?

**Comment by Jezofine** [comment]
I was smashing dummy for about 10 mins and for Mind Flay started to get interrupted instantly. After waiting couple seconds everything was ok again. Happened to me once or twice. Could not find anything suspicious in log cause of spam in Shattr.

**Comment by Tereneckla** [comment]
#4018
