### ISSUE TITLE
[NPC] Shattered Hand Champion (Heroic)

### ISSUE THREAD

**Issue by AxeCell** [Atlantiss/NetherwingBugtracker#3037]
**Description**: 
Topic is related to the Shattered Hand Champion NPCs found in Shattered Halls heroic(normal?)

**Current behaviour**:
Can apply many forms of CC on them.

**Expected behaviour**: 
Should be immune to all forms of CC as demonstrated in these provided links:
Wowhead: https://cdn.discordapp.com/attachments/510512635352055818/516320042762371085/unknown.png
Wowwiki: https://cdn.discordapp.com/attachments/510512635352055818/516319977280634891/unknown.png

**Server Revision**: 
2304

**Comment by Evolvee** [comment]
rev xxd
