### ISSUE TITLE
[Spell][Hunter pet][NPC] I cant learn any pet skills on pet trainer

### ISSUE THREAD

**Issue by DragunovUA** [Atlantiss/NetherwingBugtracker#3038]
[//]: # (Enclose links to things related to the bug using http://wowhead.com or any other TBC database.)
[//]: # (You can use screenshot ingame to visual the issue.)
[//]: # (Write your tickets according to the format:)
[//]: # ([Quest][Azuremyst Isle] Red Snapper - Very Tasty!)
[//]: # ([NPC] Magistrix Erona)
[//]: # ([Spell][Mage] Fireball)
[//]: # ([Npc][Drop] Ghostclaw Lynx)
[//]: # ([Web] Armory doesnt work)
[//]: # (To find server revision type `.server info` command in the game chat.)

**Description**: 
I cant learn any pet skills on pet trainer
**Current behaviour**:
http://i.piccy.info/i9/2821e364075db0690457ce492dc35637/1543175764/371095/1284727/WoWScrnShot_112518_214933.jpg
**Expected behaviour**: 
pls fix
**Server Revision**:

**Comment by Easyfraggy** [comment]
You need pet loyalty and pet training points to learn skills. Not all pets you tame have skills by default.

Can some experienced tbc hunter clarify this?

**Comment by DragunovUA** [comment]
i have points and loyalty, npc haven't options to learn passive skills like stamina etc.

**Comment by Easyfraggy** [comment]
No problem - glad you found the issue on your end!
