### ISSUE TITLE
Crafting second Dragonmaw = cannot carry more of these items

### ISSUE THREAD

**Issue by ttghnw** [Atlantiss/NetherwingBugtracker#3039]
**Description**: **Current behaviour**:
Doesn't let me craft although I have seen it working for others previously, so it is a new bug.
While having Dragonmaw it lets you craft a drakefist hammer but then doesn't let you upgrade to dragonmaw, also if u try to dual wield Dragonmaw and Drakefist it doesn't let you aswell.

**Expected behaviour**: 
Should be able
**Server Revision**:

**Comment by ttghnw** [comment]
After clearing cache it switched to "main-hand" so this might be the patch. However I've seen another player with the axe who had the same issue. Sorry if invalid for build at release but I could swear I've seen double blacksmith weps around.

**Comment by Tenoutoften** [comment]
You wont be able to have two of them on release

**Comment by Shanghi** [comment]
It was just changed to its older unique version today (along with a lot of other items), so that's why you saw people with 2 before.
