### ISSUE TITLE
Mission: Possible but not probable

### ISSUE THREAD

**Issue by Erodraeda** [Atlantiss/NetherwingBugtracker#304]
[//]: # (Enclose links to things related to the bug using http://wowhead.com or any other TBC database.)
[//]: # (You can use screenshot ingame to visual the issue.)
[//]: # (Write your tickets according to the format:)
[//]: # ([Quest][Azuremyst Isle] Red Snapper - Very Tasty!)
[//]: # ([NPC] Magistrix Erona)
[//]: # ([Spell][Mage] Fireball)
[//]: # ([Npc][Drop] Ghostclaw Lynx)
[//]: # ([Web] Armory doesnt work)

**Description**: 
There's this rogue quest, where you have special things to do. You have a whistle (Fizzule's Whistle) which you use, and then /salute at the target (7233, Taskmaster Fizzule) so it becomes friendly, it isn't working. Also, when you Ambush the Mutated Venture Co. Drones (7310) they die instantly, as intended, but it doesn't give credit for the quest.
**Current behaviour**:
Fizzule's Whistle + /salute isn't making the target friendly and no credit is being given by ambushing the Mutated Venture Co. Drones.
**Expected behaviour**: 
Fizzule's Whistle should make Taskmaster Fizzule friendly after a /salute and Mutated Venture Co. Drones should give credit for the quest when ambushed.
**Server Revision**:

**Comment by Evolvee** [comment]
you need to salute twice

**Comment by Evolvee** [comment]
You need to fire 2 flares and then /salute, not just one.

**Comment by Evolvee** [comment]
http://www.wowhead.com/quest=2458/deep-cover#comments:id=32265
"Once you shoot the flares, walk up to him and use the "/salute" emote on him"

http://www.wowhead.com/npc=7233/taskmaster-fizzule#comments:id=588220
"once you fire 2 flares (provided by the questgiver) and /salute him he'll turn friendly"

**Comment by Evolvee** [comment]
Mutated Venture Co. Drones (7310) fixed in next revision
