### ISSUE TITLE
[Spell][Paladin] Turn Evil

### ISSUE THREAD

**Issue by Homiecup** [Atlantiss/NetherwingBugtracker#3040]
**Description**: 
Turn Evil doesn't fear demons even though its a spell added in 2.4.0 but it should should always be able to fear undead and demons in TBC from when it was added.
http://wowwiki.wikia.com/wiki/Turn_Evil
https://wow.gamepedia.com/Turn_Evil

**Current behaviour**:
Turn evil currently can only fear undead targets.

**Expected behaviour**: 
Turn Evil should be able to fear undead and demons.

**Server Revision**: 
2361

**Comment by Tenoutoften** [comment]
I've been able to fear demons with it

**Comment by Homiecup** [comment]
Yeah you had right on that i was looking at turn undead.
