### ISSUE TITLE
[Raid][SSC][Hydross] Adds activate too quickly

### ISSUE THREAD

**Issue by killablink** [Atlantiss/NetherwingBugtracker#3041]
**Description**: When the boss transitions, the adds that spawn should slowly spawn for 2 seconds before moving at all.

**Current behaviour**: They instantly aggro and attack

**Expected behaviour**: They shouldn't be moving for 2~ seconds. https://youtu.be/L7ltio-Xgrw?t=114
https://youtu.be/Pqu49qc3LKI?t=79
**Server Revision**:

**Comment by killablink** [comment]
Also something important to note, if I remember correctly currently they spawn at the exact time the boss transitions, but you can see in the video that the boss transitions, and then the adds spawn 1~ second later, and then they get activated

**Comment by Wolffenstein** [comment]
Fixed in rev 2366.
