### ISSUE TITLE
[Raid][SSC][Lurker] Adds not moving to platforms properly

### ISSUE THREAD

**Issue by killablink** [Atlantiss/NetherwingBugtracker#3043]
**Description**: The adds should move to their designed place before aggoring

**Current behaviour**: They aggro right in the water and sit there

**Expected behaviour**: They should walk all the way to their position on the platform, and then aggro

**Server Revision**:

**Comment by Wolffenstein** [comment]
Thanks

**Comment by Wolffenstein** [comment]
Fixed in rev 2366.
