### ISSUE TITLE
[Mage][Spell] frost nova and pet freeze

### ISSUE THREAD

**Issue by somnu** [Atlantiss/NetherwingBugtracker#3044]
[//]: # (Enclose links to things related to the bug using http://wowhead.com or any other TBC database.)
[//]: # (You can use screenshot ingame to visual the issue.)
[//]: # (Write your tickets according to the format:)
[//]: # ([Quest][Azuremyst Isle] Red Snapper - Very Tasty!)
[//]: # ([NPC] Magistrix Erona)
[//]: # ([Spell][Mage] Fireball)
[//]: # ([Npc][Drop] Ghostclaw Lynx)
[//]: # ([Web] Armory doesnt work)
[//]: # (To find server revision type `.server info` command in the game chat.)

**Description**: 
Both Frost Nova and Water Elemental's Freeze root effect doesn't always land. The spell does damage, but the root effect doesn't apply. There is no resist message generated in combat log, just Frost Nova hits X for Y damage.

**Current behaviour**:
Both Frost Nova and Water Elemental's Freeze root effect doesn't always land. The spell does damage, but the root effect doesn't apply. There is no resist message generated in combat log, just Frost Nova hits X for Y damage.

**Expected behaviour**: 
If frost nova or pet freeze lands (does damage), they should also root the targets in place.
**Server Revision**: 
2361

**Comment by Evolvee** [comment]
thats not true, there are talents that increase chance to resist root/snare and so on, the dmg goes through but the root components doesnt
https://youtu.be/kYeBkX6bC1k?t=6

**Comment by somnu** [comment]
Do you have any proof for this?

**Comment by Evolvee** [comment]
yea i believe so, this was fixed like 2.5 years ago so, i dont remember what it was... feel free to disprove it

**Comment by somnu** [comment]
Ok I have one more question, how is mage pet 'chance to hit' calculated? Does it inherit the mage's hit chance from gear? It feels like pet nova resists a lot.

**Comment by Evolvee** [comment]
it doesnt inherit hit until wotlk afaik
