### ISSUE TITLE
[Spell][Warlock][Raid][SSC] Nether Protection on Leotheras the Blind Demon form.

### ISSUE THREAD

**Issue by Cptnlobbe** [Atlantiss/NetherwingBugtracker#3046]
**Description**: 
Nether protection proccing on Leotheras demon form attacks.
**Current behaviour**:
Does not proc on attacks. Might need further testing, I only got a total of maybe 10-12 hits over all tries, that wasn't fully resisted.
**Expected behaviour**: 
Should proc.

**Server Revision**: 
2361

**Comment by Easyfraggy** [comment]
This is contested - need more evidence.

**Comment by killablink** [comment]
![image](https://user-images.githubusercontent.com/43510874/49164441-210dcb80-f2fd-11e8-89b2-f8cbbdd9f32c.png)

**Comment by Easyfraggy** [comment]
Seems like an early enough blue post to confirm that this issue is invalid.
