### ISSUE TITLE
([Quest][Blade's Edge Mountains] ...and a Time for Action) does not work properly!

### ISSUE THREAD

**Issue by pmachielsen** [Atlantiss/NetherwingBugtracker#3047]
[//]: # (Enclose links to things related to the bug using http://wowhead.com or any other TBC database.)
[//]: # (You can use screenshot ingame to visual the issue.)
[//]: # (Write your tickets according to the format:)
 # ([Quest][Blade's Edge Mountains] ...and a Time for Action)
[//]: # ([NPC] Magistrix Erona)
[//]: # ([Spell][Mage] Fireball)
[//]: # ([Npc][Drop] Ghostclaw Lynx)
[//]: # ([Web] Armory doesnt work)
[//]: # (To find server revision type `.server info` command in the game chat.)

**Description**: 
Quest ...and a Time for Action does not get any trigger when you slay a Wyrmcult hewer in Ruuan Weald or  the tunnel pas the bridge
**Current behaviour**:
no trigger of the 10 kills you need to get to finish quest
**Expected behaviour**: 
at every kill make quest progression
**Server Revision**:

**Comment by pmachielsen** [comment]
for some reason 10 m later when i returned in the tunnel for another quest killing the Wyrmcult Hewers started to count all of the sudden
only thing that changed is that i delivered the [Quest]Wyrmskull Watcher in between  so iam baffled by this

**Comment by pmachielsen** [comment]
went back to Ruaan Weald area to check if killing some there also started counting and it did
i seripously killed atleast 5 at Ruaan Weald and 5 in Tunnel before making this bug report something i did in between unbroke it )delivering that other quest or something else)

**Comment by Easyfraggy** [comment]
Can someone translate?

**Comment by Tenoutoften** [comment]
He is saying he picked up [[Quest]...and a time for action#10713](https://www.wowhead.com/quest=10713/and-a-time-for-action)

and he didn't get quest credit for killing [[NPC]Wyrmcult Hewer#21810](https://www.wowhead.com/npc=21810/wyrmcult-hewer) but later on he did(At the place over the bridge)

I suspect he killed the incorrect [[NPC]Wyrmcult Poacher#21809](https://www.wowhead.com/npc=21809/wyrmcult-poacher)

https://www.youtube.com/watch?v=W4nZraQqOIo&feature=youtu.be

**Comment by The14me** [comment]
Working just fine.
