### ISSUE TITLE
[Raid][SSC][NPC] Underbog Colossus - Acid geyser

### ISSUE THREAD

**Issue by scarabadookie** [Atlantiss/NetherwingBugtracker#3048]
[//]: # (Enclose links to things related to the bug using http://wowhead.com or any other TBC database.)
[//]: # (You can use screenshot ingame to visual the issue.)
[//]: # (Write your tickets according to the format:)
[//]: # ([Quest][Azuremyst Isle] Red Snapper - Very Tasty!)
[//]: # ([NPC] Magistrix Erona)
[//]: # ([Spell][Mage] Fireball)
[//]: # ([Npc][Drop] Ghostclaw Lynx)
[//]: # ([Web] Armory doesnt work)
[//]: # (To find server revision type `.server info` command in the game chat.)

**Description**: 
Acid geyser ability only targets the tank

**Current behaviour**:
4/4 times the geyser targeted the tank with highest threat

**Expected behaviour**: 
It should target a random raid member see [https://www.wowhead.com/npc=21251/underbog-colossus#comments](url)

**Server Revision**: 
2361

**Comment by Wolffenstein** [comment]
Fixed in rev 2366.
