### ISSUE TITLE
[Raid][SSC][NPC] Coilfang Frenzy - Doesn't reset aggro

### ISSUE THREAD

**Issue by scarabadookie** [Atlantiss/NetherwingBugtracker#3049]
[//]: # (Enclose links to things related to the bug using http://wowhead.com or any other TBC database.)
[//]: # (You can use screenshot ingame to visual the issue.)
[//]: # (Write your tickets according to the format:)
[//]: # ([Quest][Azuremyst Isle] Red Snapper - Very Tasty!)
[//]: # ([NPC] Magistrix Erona)
[//]: # ([Spell][Mage] Fireball)
[//]: # ([Npc][Drop] Ghostclaw Lynx)
[//]: # ([Web] Armory doesnt work)
[//]: # (To find server revision type `.server info` command in the game chat.)

**Description**: 
If someone falls in the water in SSC the fish won't give up.

**Current behaviour**:
Coilfang frenzies do not drop aggro when there's no player in reach, locking raid/members in combat. They also "swim" a few yards above the water on the pipes that lead into the water.

**Expected behaviour**: 
Coilfang frenzies should stay in the water and drop aggro when there's no target available.

**Server Revision**: 
2361

**Comment by Easyfraggy** [comment]
https://gfycat.com/MessyAnxiousItaliangreyhound

**Comment by Wolffenstein** [comment]
Fixed in rev 2711.
