### ISSUE TITLE
[Quest][Ghostlands] Culinary Crunch

### ISSUE THREAD

**Issue by Thugli** [Atlantiss/NetherwingBugtracker#305]
**Description**: 
The drop rate on crunchy spider legs seems extremely low.

**Current behaviour**:
I've killed around 30 or so spindleweb lurkers (Possibly more) and only received 2 crunchy spider legs.

**Expected behaviour**: 
Drop rate for crunchy spider leg should be increased

**Server Revision**:

**Comment by Wolffenstein** [comment]
Fixed in rev 2046.
