### ISSUE TITLE
[Raid][SSC] Fathom-Lord Karathress encounter summoned totems are able to move. 

### ISSUE THREAD

**Issue by Joaxx** [Atlantiss/NetherwingBugtracker#3050]
[//]: # (Enclose links to things related to the bug using http://wowhead.com or any other TBC database.)
[//]: # (You can use screenshot ingame to visual the issue.)
[//]: # (Write your tickets according to the format:)
[//]: # ([Quest][Azuremyst Isle] Red Snapper - Very Tasty!)
[//]: # ([NPC] Magistrix Erona)
[//]: # ([Spell][Mage] Fireball)
[//]: # ([Npc][Drop] Ghostclaw Lynx)
[//]: # ([Web] Armory doesnt work)
[//]: # (To find server revision type `.server info` command in the game chat.)

**Description**: The totems casted by Fathom-Guard Tidalvess on the Fathom-Lord Karathress encounter are able to move and chase people. 

**Current behaviour**: The totems have an aggro table and will chase after people who attack them. https://clips.twitch.tv/AlertLachrymoseDragonfruitJebaited

**Expected behaviour**: Totems should remain stationary and should not be able to target and attack players. 

**Server Revision**: 2361

**Comment by Wolffenstein** [comment]
Fixed in rev 2366.

**Comment by ircfelix** [comment]
Requesting reopen.

I did not see any totem following people yesterday, but the totems cast by Fathom-Guard Tidalvess are
a) stacked directly inside Fathom-Guard Tidalvess, which makes targeting them a mess
b) moving with Fathom-Guard Tidalvess, if he moves.
