### ISSUE TITLE
[Raid][SSC][NPC] Greyheart Tidecaller - Water elemental totem summon cast time

### ISSUE THREAD

**Issue by scarabadookie** [Atlantiss/NetherwingBugtracker#3051]
[//]: # (Enclose links to things related to the bug using http://wowhead.com or any other TBC database.)
[//]: # (You can use screenshot ingame to visual the issue.)
[//]: # (Write your tickets according to the format:)
[//]: # ([Quest][Azuremyst Isle] Red Snapper - Very Tasty!)
[//]: # ([NPC] Magistrix Erona)
[//]: # ([Spell][Mage] Fireball)
[//]: # ([Npc][Drop] Ghostclaw Lynx)
[//]: # ([Web] Armory doesnt work)
[//]: # (To find server revision type `.server info` command in the game chat.)

**Description**: 

**Current behaviour**:
The instant the tidecaller puts out its totem, it summons an elemental.

**Expected behaviour**: 
The totem should be out for a short period of time before it summons an elemental, to allow for quick dps to destroy it before it can summon an elemental.

**Server Revision**: 
2361

**Comment by Easyfraggy** [comment]
Need some retail source on how long this timer should be.

**Comment by Brasso** [comment]
The water elemental hits for over 12k frost damage on tanks every swing, not sure if this is correct, feels absurd.

**Comment by killablink** [comment]
https://youtu.be/0ZRFZKPMBWo?t=1383
https://youtu.be/0ZRFZKPMBWo?t=1476
seems to be around 4~ seconds after the totem is dropped (2008 clip)

**Comment by killablink** [comment]
Just tried on actual retail and the first one gets summoned from 2-4 seconds after totem is dropped

**Comment by Wolffenstein** [comment]
Fixed in rev 2366.
