### ISSUE TITLE
[Raid][SSC][NPC] Coilfang Serpentguard - spell reflect stacks are not consumed

### ISSUE THREAD

**Issue by scarabadookie** [Atlantiss/NetherwingBugtracker#3052]
[//]: # (Enclose links to things related to the bug using http://wowhead.com or any other TBC database.)
[//]: # (You can use screenshot ingame to visual the issue.)
[//]: # (Write your tickets according to the format:)
[//]: # ([Quest][Azuremyst Isle] Red Snapper - Very Tasty!)
[//]: # ([NPC] Magistrix Erona)
[//]: # ([Spell][Mage] Fireball)
[//]: # ([Npc][Drop] Ghostclaw Lynx)
[//]: # ([Web] Armory doesnt work)
[//]: # (To find server revision type `.server info` command in the game chat.)

**Description**: 

**Current behaviour**:
The spell reflect buff has 4 stacks and does not lose stacks when hit, it stays up until it expires.

**Expected behaviour**: 
One stack should be consumed every time a spell is reflected.

**Server Revision**: 
2361

**Comment by Wolffenstein** [comment]
Fixed in rev 2366.
