### ISSUE TITLE
Addon "Gladdy" not working properly

### ISSUE THREAD

**Issue by Nicemann1089** [Atlantiss/NetherwingBugtracker#3054]
[//]: # (Enclose links to things related to the bug using http://wowhead.com or any other TBC database.)
[//]: # (You can use screenshot ingame to visual the issue.)
[//]: # (Write your tickets according to the format:)
[//]: # ([Quest][Azuremyst Isle] Red Snapper - Very Tasty!)
[//]: # ([NPC] Magistrix Erona)
[//]: # ([Spell][Mage] Fireball)
[//]: # ([Npc][Drop] Ghostclaw Lynx)
[//]: # ([Web] Armory doesnt work)
[//]: # (To find server revision type `.server info` command in the game chat.)

**Description**: The latest version of Schaka's famous arena frames addon for 2.4.3 is not working properly. https://github.com/Schaka/gladdy

**Current behaviour**: The arena frames are not updating health and mana information. They display the class of the enemy but nothing more.

Evolve told me to report that. He said it could be server-side.

**Server Revision**: 2361

**Comment by Evolvee** [comment]
Probably the % HP system @Wolffenstein
