### ISSUE TITLE
Hit rating not shown in character pane

### ISSUE THREAD

**Issue by Nicemann1089** [Atlantiss/NetherwingBugtracker#3056]
[//]: # (Enclose links to things related to the bug using http://wowhead.com or any other TBC database.)
[//]: # (You can use screenshot ingame to visual the issue.)
[//]: # (Write your tickets according to the format:)
[//]: # ([Quest][Azuremyst Isle] Red Snapper - Very Tasty!)
[//]: # ([NPC] Magistrix Erona)
[//]: # ([Spell][Mage] Fireball)
[//]: # ([Npc][Drop] Ghostclaw Lynx)
[//]: # ([Web] Armory doesnt work)
[//]: # (To find server revision type `.server info` command in the game chat.)

https://drive.google.com/file/d/1waMr4aKrhBXY1BdnhH-gkqWtUtE8IvZB/view?usp=drivesdk

**Current behaviour**: Hit rating is not shown in the character pane. I put hit gems on my gear and it still says "0" hit rating.

**Server Revision**: 2361

**Comment by Easyfraggy** [comment]
Oh he was trying to get spell hit?

**Comment by Nicemann1089** [comment]
aight, I should stop smoking dope when testing such shit
