### ISSUE TITLE
[Raid][SSC][NPC] Leotheras the Blind INNER DEMONS

### ISSUE THREAD

**Issue by Brasso** [Atlantiss/NetherwingBugtracker#3057]
[//]: # (Enclose links to things related to the bug using http://wowhead.com or any other TBC database.)
[//]: # (You can use screenshot ingame to visual the issue.)
[//]: # (Write your tickets according to the format:)
[//]: # ([Quest][Azuremyst Isle] Red Snapper - Very Tasty!)
[//]: # ([NPC] Magistrix Erona)
[//]: # ([Spell][Mage] Fireball)
[//]: # ([Npc][Drop] Ghostclaw Lynx)
[//]: # ([Web] Armory doesnt work)
[//]: # (To find server revision type `.server info` command in the game chat.)

**Current behaviour**:
The damage of the inner demons is way too low, their melee does about 250 damage on a warlock. Never got hit by shadow bolt, damage is unknown, but might as well check it also. 
The demon's shadow bolt is also redirected by nearby grounding totem from other players.
https://clips.twitch.tv/HelpfulFlirtyLocustStinkyCheese

The inner demons are really easy to kill as healer even without spell damage on gear, either the health is 7k (postnerf), instead of 10-11k (prenerf), or the spell damage bonus might too high. https://clips.twitch.tv/BoldAmusedLousePermaSmug (resto shaman near center of the screen)

> https://www.wowhead.com/npc=21215/leotheras-the-blind#comments
> (Aurelius on 2007/05/26 (Patch 2.1.0 )
> In the latest patch (2.1.0) they nerfed the HP of his adds and the HP of Leotheras himself. They have also reduced the amount of HP for inner demons from roughly 10,000 HP to 7,000 HP. Free loot 
> FTW!)

The timer for inner demon's shadow bolt is too long, allowing casters to completely negate the mechanic, also making it really easy for healers. This has the opposite effect for tanks, making them unable to reflect enough shadow bolts to kill their demons.

~~Leotheras whirlwind does not have a stacking effect if you get hit multiple times, it just refreshes the debuff and the dot timer.~~

**Server Revision**: 
2361

**Comment by aresbrutus** [comment]
Thank you for the report, we will be also adding it to our internal list. About the stacking of whirlwind: https://youtu.be/8SWVNk-KfUI?t=198

**Comment by Easyfraggy** [comment]
Please only 1 issue/spell per post!

Their health is copied from the player. Not a set value in 2.0 version.

Leotheras whirlwind should NOT stack. This is some pserver info... 
https://youtu.be/8SWVNk-KfUI?t=198

**Comment by Brasso** [comment]
Thanks you for the correction, some gummy custom stuff then fogging my memory. So that's why the demons are so easy to kill as healer but absurdly hard as tank.

**Comment by Dollywog** [comment]
How are tanks meant to be able to kill the demons when they only melee'ing for about 100 on tanks.  Both our tanks failed the kill 3/3 times.

**Comment by Brasso** [comment]
Found another issue. Demons are healed by chain heal. The mobs are considered a friendly target when another player without inner demons target them, that might be the issue.
https://clips.twitch.tv/AwkwardMuddyClipsdadOptimizePrime

**Comment by Wolffenstein** [comment]
Fixed in rev 2706.
