### ISSUE TITLE
[Spell][Hunter] Kill Command

### ISSUE THREAD

**Issue by Zarant** [Atlantiss/NetherwingBugtracker#3058]
Despite the spell being off the GCD, you cannot macro other spells with Kill Command.
Once you hit the macro, kill command will go off and the next spell will return "Another action is in progress". On top of that, upon using a kill command+steady shot macro sometimes lock down your auto shot, I couldn't reproduce this part consistently but I'm suspecting that happens whenever you press the macro when the auto shot is about to go off.

Kill command just like other similar spells (e.g. Icy Veins or Fel Domination) allow you to cast 2 spells at the same time as long as the first spell on your macro is off the GCD.

The clip below show the behavior I just described, notice the first time I press the macro my auto shot gets all messed up and all subsequent button presses don't ever manage to cast both steady shot and kill command at the same time.

https://clips.twitch.tv/RelatedInexpensivePlumagePanicBasket

Server Revision: 2361

**Comment by Wolffenstein** [comment]
Please retest after revision 2366.

**Comment by Zarant** [comment]
I tested it again in revision 2451 and it's not working properly.

**Comment by Zarant** [comment]
Working as intended (revision 2756)
