### ISSUE TITLE
[Raid][SSC][NPC] Greyheart Nether-Mage Blink Ability

### ISSUE THREAD

**Issue by Brasso** [Atlantiss/NetherwingBugtracker#3059]
[//]: # (Enclose links to things related to the bug using http://wowhead.com or any other TBC database.)
[//]: # (You can use screenshot ingame to visual the issue.)
[//]: # (Write your tickets according to the format:)
[//]: # ([Quest][Azuremyst Isle] Red Snapper - Very Tasty!)
[//]: # ([NPC] Magistrix Erona)
[//]: # ([Spell][Mage] Fireball)
[//]: # ([Npc][Drop] Ghostclaw Lynx)
[//]: # ([Web] Armory doesnt work)
[//]: # (To find server revision type `.server info` command in the game chat.)

**Description**: 
The Nether-Mage teleports players instead of himself.
**Current behaviour**:
https://clips.twitch.tv/SolidPleasantSharkDatSheffy (on the left, resto shaman)
**Expected behaviour**: 
The mage should teleport himself.
**Server Revision**: 
2361

**Comment by Wolffenstein** [comment]
Fixed in rev 2366.

**Comment by Drayo** [comment]
resurfaced

**Comment by Drayo** [comment]
After re-testing, they indeed still teleport the player in front of them instead of themselves to the players position.

This makes tanking them much easier than it should be.

**Comment by Wolffenstein** [comment]
Fixed in rev 3449.
