### ISSUE TITLE
[Raid][SSC] Coilfang Priestess 

### ISSUE THREAD

**Issue by Dollywog** [Atlantiss/NetherwingBugtracker#3061]
[//]: # (Enclose links to things related to the bug using http://wowhead.com or any other TBC database.)
[//]: # (You can use screenshot ingame to visual the issue.)
[//]: # (Write your tickets according to the format:)
[//]: # ([Quest][Azuremyst Isle] Red Snapper - Very Tasty!)
[//]: # ([NPC] Magistrix Erona)
[//]: # ([Spell][Mage] Fireball)
[//]: # ([Npc][Drop] Ghostclaw Lynx)
[//]: # ([Web] Armory doesnt work)
[//]: # (To find server revision type `.server info` command in the game chat.)

**Description**: These mobs currently when CC breaks or when pulled can spam their Holy Fire / Holy Smite ability sometimes three spells in one global.  

**Current behaviour**:  Can one shot tank in one global with poor luck

**Expected behaviour**: Should have internal CD on abilities and not cast them within globals of each other.

**Comment by Wolffenstein** [comment]
Fixed in rev 2366.
