### ISSUE TITLE
[NPC] Teromoth [Spell] Pacifying Dust

### ISSUE THREAD

**Issue by Tholinx** [Atlantiss/NetherwingBugtracker#3063]
[//]: # (Enclose links to things related to the bug using http://wowhead.com or any other TBC database.)
[//]: # (You can use screenshot ingame to visual the issue.)
[//]: # (Write your tickets according to the format:)
[//]: # ([Quest][Azuremyst Isle] Red Snapper - Very Tasty!)
[//]: # ([NPC] Magistrix Erona)
[//]: # ([Spell][Mage] Fireball)
[//]: # ([Npc][Drop] Ghostclaw Lynx)
[//]: # ([Web] Armory doesnt work)
[//]: # (To find server revision type `.server info` command in the game chat.)

**Description**: 
Pacifying Dust - Unable to attack 

**Current behaviour**:
I can normally cast and attack

**Expected behaviour**: 
I shouldn't be able to cast or attack

**Server Revision**: 
2361

**Comment by Tenoutoften** [comment]
Shouldn't be able to attack, looks like you should be able to cast spells
![a4cd52028070e48e2c8efe96ecd4ace5](https://user-images.githubusercontent.com/34839199/49008827-23421f80-f16f-11e8-9a3d-9965a947e2ab.png)

**Comment by Tenoutoften** [comment]
Just tested, it works as the comment says. Unable to attack, able to cast spells, working as intended.
