### ISSUE TITLE
[Spell][Paladin] Seal/Judgement of Blood Reflected Damage Too High When Damage is Increased

### ISSUE THREAD

**Issue by Jacksn5** [Atlantiss/NetherwingBugtracker#3064]
[//]: # (Enclose links to things related to the bug using http://wowhead.com or any other TBC database.)
[//]: # (You can use screenshot ingame to visual the issue.)
[//]: # (Write your tickets according to the format:)
[//]: # ([Quest][Azuremyst Isle] Red Snapper - Very Tasty!)
[//]: # ([NPC] Magistrix Erona)
[//]: # ([Spell][Mage] Fireball)
[//]: # ([Npc][Drop] Ghostclaw Lynx)
[//]: # ([Web] Armory doesnt work)
[//]: # (To find server revision type `.server info` command in the game chat.)

**Description**: 
During [Mechano-Lord Capacitus](https://db.excalibur.ws/?npc=21533)'s [Polarity Shift](https://db.excalibur.ws/?spell=39096) in Mechanar Heroic seems to multiply [Seal of Blood](https://db.excalibur.ws/?spell=31892)'s reflected damage as well, see

[![Mech Mechano Lord Capacitus Seal of Blood](http://img.youtube.com/vi/d7N-Bjyco6Q/0.jpg)](https://www.youtube.com/watch?v=d7N-Bjyco6Q "Mech Mechano Lord Capacitus Seal of Blood")

4074 Damage dealt, 6966 reflected.

**Server Revision**: 
~2348, 22.11. afternoon

**Comment by Wolffenstein** [comment]
Fixed in rev 2366.
