### ISSUE TITLE
[Item] BoE World Epics with Post 2.1 Stats

### ISSUE THREAD

**Issue by Saben65** [Atlantiss/NetherwingBugtracker#3067]
The following BoE world epics should have their ilvls reduced to 95 and the following stat reductions pre-2.1. Some are more significant than others (Leggings of Beast Mastery).

Item: [Chestguard of the Exile](https://web.archive.org/web/20070312203506/http://www.thottbot.com:80/i31320), 
-60 armor, -1 crit rating pre-2.1.
[Wowhead Comment post-2.1](https://www.wowhead.com/item=31320/chestguard-of-exile#comments:id=95765)

Item: [Lifegiving Cloak](https://web.archive.org/web/20070312120039/http://www.thottbot.com:80/i31329)
-5 armor, -1 Intellect. 

Item: [Will of Edward the Odd](https://web.archive.org/web/20070421004320/http://www.thottbot.com:80/i31340)
-8 armor, -1 crit. 

Item: [Kamaei's Cerulean Skirt](https://web.archive.org/web/20070428022925/http://www.thottbot.com:80/i31343)
-1 armor, -1 spirit. 

Item: [The Night Watchman](https://web.archive.org/web/20070514031931/http://www.thottbot.com:80/i31333)
-10 armor, -2 Stam

Item: [Lightning Crown](https://web.archive.org/web/20070515071745/http://www.thottbot.com:80/i31330)
-27 armor, -1 crit

Item: [Leggings of Beast Mastery](https://web.archive.org/web/20070513160157/http://www.thottbot.com:80/i31328)
-28 armor, -30 agility, -45 stamina
Equip: -140 armor and -17 stam for pet (Looks like they updated the spell instead of replacing it, so probably can't be fixed)
[Wowhead Comment](https://www.wowhead.com/item=31328/leggings-of-beast-mastery#comments:id=87430) post 2.1.

Item: [Pants of Living Growth](https://web.archive.org/web/20070514110335/http://thottbot.com:80/i31335)
-10 Armor, -1 Intellect

Item: [Chestguard of Exile](https://web.archive.org/web/20070312203506/http://www.thottbot.com:80/i31320)
-60 armor, -1 crit

Item: [Charlotte's Ivy](https://web.archive.org/web/20070317200749/http://www.thottbot.com:80/i31338)
-1 spirit

Item: [Choker of Repentance](https://web.archive.org/web/20070515064940/http://www.thottbot.com:80/i31321)
-1 strength

Item: [Band of Impenetrable Defenses](https://web.archive.org/web/20070409234705/http://www.thottbot.com:80/i31319)
-1 defense

Item: [Lola's Eve](https://web.archive.org/web/20070419094933/http://www.thottbot.com:80/i31339)
-2 stam

Item: [Truestrike Ring](https://web.archive.org/web/20070510125743/http://www.thottbot.com:80/i31326)
-1 agility

Most the weapons look to be in their pre-nerf state already. There are still some minor fixes to be done though

Item: [The Ancient Scepter of Sue-Min](https://web.archive.org/web/20070315163953/http://www.thottbot.com:80/i31342)
-1 Intel

Item: [The Hammer of Destiny](https://web.archive.org/web/20070314191817/http://www.thottbot.com:80/i31322)
Should be 295-444 damage instead of 304-457, -33 intel

Item: [Staff of Natural Fury](https://web.archive.org/web/20070312203601/http://www.thottbot.com:80/i31334)
133-257 damage instead of 133-261, -5 str, -1 stam, Equip: 525 AP instead of 712

**Comment by aresbrutus** [comment]
Fixed in rev `Phoebe`

Please check them after clearing your cache.
