### ISSUE TITLE
[Item] Deathwing Brood Cloak

### ISSUE THREAD

**Issue by Saben65** [Atlantiss/NetherwingBugtracker#3068]
**Description**: 
Added in Patch 2.1 with Ogri'la dailies, [Deathwing Brood Cloak](https://www.wowhead.com/item=31942/deathwing-brood-cloak) was a cloak that could be crafted with scales from the 4 dragons in the BEM and 35 apexis crystals.

**Current behaviour**:
The cloak is currently BoE.

**Expected behaviour**: 
The cloak should be BoP until [Patch 2.4](http://wowwiki.wikia.com/wiki/Patch_2.4.0).
> [Deathwing Brood Cloak]: These cloaks are now bound on equip instead of bound on pickup.

[Wowhead comment from 2.1](https://www.wowhead.com/item=31942/deathwing-brood-cloak#comments:id=88833)
> They are all BOP, and you have no control over which one you will get when you combine the 4 dragon scales. Could get lucky, could get something completely useless. In case it is useless to you, you can exchange it for an Apexis Crystal at Sky Commander Keller (http://www.wowhead.com/?npc=23334).

[Pre 2.4](https://web.archive.org/web/20080218213443/http://thottbot.com:80/i31942)
[Post 2.4](https://web.archive.org/web/20080327140640/http://thottbot.com:80/i31942)

**Server Revision**: 
2364

**Comment by aresbrutus** [comment]
Fixed in rev `Phoebe`
