### ISSUE TITLE
SSC trash gangrape

### ISSUE THREAD

**Issue by Mikik3jr** [Atlantiss/NetherwingBugtracker#3069]
[//]: # (Enclose links to things related to the bug using http://wowhead.com or any other TBC database.)
[//]: # (You can use screenshot ingame to visual the issue.)
[//]: # (Write your tickets according to the format:)
[//]: # ([Quest][Azuremyst Isle] Red Snapper - Very Tasty!)
[//]: # ([NPC] Magistrix Erona)
[//]: # ([Spell][Mage] Fireball)
[//]: # ([Npc][Drop] Ghostclaw Lynx)
[//]: # ([Web] Armory doesnt work)
[//]: # (To find server revision type `.server info` command in the game chat.)

**Description**: 
In SSC we pulled a pack of trash, I died and they were hitting my dead body.

**Current behaviour**:
![wowscrnshot_112518_214204](https://user-images.githubusercontent.com/43505031/49033812-76889200-f1b0-11e8-877e-e4e0f1b742e5.jpg)
![wowscrnshot_112518_214209](https://user-images.githubusercontent.com/43505031/49033814-77212880-f1b0-11e8-9657-1d32d62013b0.jpg)
![wowscrnshot_112518_214226](https://user-images.githubusercontent.com/43505031/49033815-77b9bf00-f1b0-11e8-998e-9a22117a6328.jpg)
I tried to release but it didn't work. Only alt+f4 solved this issue.
![wowscrnshot_112518_214239](https://user-images.githubusercontent.com/43505031/49033817-78525580-f1b0-11e8-8409-86c54a845b87.jpg)
![image](https://user-images.githubusercontent.com/43505031/49033829-83a58100-f1b0-11e8-89a1-a2d0bb744c82.png)

**Expected behaviour**: 
Sadly I don't know how it happened. Maybe on the picture it can be seen on which part of SSC we were in and which trash we pulled.

And funny thing that I had SS up on me, but It didn't even offer me the option to revive myself.
**Server Revision**: 
2363

**Comment by Easyfraggy** [comment]
Seems to be an issue with soulstone.
