### ISSUE TITLE
[Quest][Zangarmarsh] Now That We're Still Friends...

### ISSUE THREAD

**Issue by Saben65** [Atlantiss/NetherwingBugtracker#3070]
**Description**: 
After completing [Now That We're Friends...](https://www.wowhead.com/quest=9726/now-that-were-friends) you unlock a similar, repeatable quest, [Now That We're Still Friends...](https://www.wowhead.com/quest=9727/now-that-were-still-friends).

**Current behaviour**:
The repeatable version of the quest, [Now That We're Still Friends...](https://www.wowhead.com/quest=9727/now-that-were-still-friends), only requires you to kill 12 [Bloodscale Slavedrivers](https://www.wowhead.com/npc=18089/bloodscale-slavedriver) and 6 [Blood Scale Enchantresses](https://www.wowhead.com/npc=18088/bloodscale-enchantress).

**Expected behaviour**: 
The quest was changed in [Patch 2.4](http://wowwiki.wikia.com/wiki/Patch_2.4.0_(undocumented_changes)) to only require 6 [Blood Scale Enchantresses](https://www.wowhead.com/npc=18088/bloodscale-enchantress). Prior to that, you needed to kill 12 of both, just like the normal quest [Now That We're Friends...](https://www.wowhead.com/quest=9726/now-that-were-friends)

**Server Revision**: 
2364

**Comment by Kiperr** [comment]
``sql
UPDATE `quest_template` SET `ReqCreatureOrGOCount2` = 12 WHERE `entry` = 9727; 
```

**Comment by aresbrutus** [comment]
Fixed in rev Nariman thanks to `Kiper`
