### ISSUE TITLE
[Paladin][Spell]Blessing of Sanctuary & Greater Blessing of Sanctuary deal different damage & scales with spell damage

### ISSUE THREAD

**Issue by Tenoutoften** [Atlantiss/NetherwingBugtracker#3071]
**Description & Current Behavior**: 

The damage caused component of [[Spell]BoSa/GBoSa](https://db.excalibur.ws/?search=blessing+of+sanctuary) 
---
Current behavior seen [here](https://youtu.be/4wnAeO-zipA)
BoSa & GBoSa got different scaling when it comes to their damage
[[Spell]Blessing of Sanctuary#27169](https://db.excalibur.ws/?spell=27168)
[[Spell]Greater Blessing of Sanctuary#27169](https://db.excalibur.ws/?spell=27169)

GBoSa dealt 97 damage with 409 spell damage
BoSa dealt 187 damage with 409 spell damage

Text on the buff
---
![4c5e92a1507b8855ca4a7dcfa77ad112](https://user-images.githubusercontent.com/34839199/49032033-e0526d00-f1ab-11e8-93d2-98f15f40ebac.png)
![160f5bdb9ee46d1861c62c451e0367a1](https://user-images.githubusercontent.com/34839199/49032034-e0526d00-f1ab-11e8-8f28-95d86e575ad6.png)
---

Video evidence
---
On the [kronos bug tracker](https://vanilla-twinhead.twinstar.cz/?issue=2774) there is one video with a paladin using BoSa together with Sanctity Aura in Strat Living, can be seen [here](https://youtu.be/84OwHLAuQzc?t=56), showing 35 damage dealt.
The same paladin does the Baron fight without Sanctity Aura showing 35 damage [here](https://youtu.be/84OwHLAuQzc?t=114)

**Seems to me Sanctity Aura shouldn't increase the holy damage done by BoSa/GBoSa.**

---

Hobbos made lots of [videos](https://www.youtube.com/user/wowhobbs/videos?view=0&sort=da&flow=grid), some while he leveled, some at max level, doing big pulls with BoSa/GBoSa:

* Hobbos is seen with [[Spell]Greater Blessing of Sanctuary(rank 1)#25899](https://db.excalibur.ws/?spell=25899), it deals 35 damage flat, [here](https://youtu.be/EN7KfJ7ZKXc?t=154)
 * [Another video](https://youtu.be/6e19e9vg0Fs?t=88), this time Ulduman and again you see 35 damage.
* [Shadowfang Keep](https://youtu.be/-JREuvxyviQ?t=138)
* Hobbos has reached level 70, using [[Spell]Greater Blessing of Sanctuary(Rank 2)#27169](https://db.excalibur.ws/?spell=27169) and it's dealing 46 damage, can be seen [here](https://youtu.be/72c8YUNusEo?t=195)

You can also see that Hobbos got spell damage gear, he is wearing [Spaulders of the Righteous](https://db.excalibur.ws/?item=27739) which got +15 damage and healing. With the standard coefficient of instant spells, 42.85% his [[Spell]BoSa/GBoSa](https://db.excalibur.ws/?search=blessing+of+sanctuary) should always deal 53 damage if it was scaling with spell damage.

* Hobbos in Karazhan, fighting Moroes [here](https://youtu.be/nHosnYn_4QM?t=130),  you see 46 damage being dealt. This is the flat amount of [[Spell][GBoSa(Rank 2)#27169](https://db.excalibur.ws/?spell=27169)

---

Not using BoSa, strange because if it scales with spell power this is a lot of threat?
https://www.youtube.com/watch?v=yv1UwMJdH0U

---

Patch notes from http://wowwiki.wikia.com/wiki/Blessing_of_Sanctuary:
---
* Patch 1.6.0 (12-Jul-2005): New Sparkle animation added.
* Patch 1.9.0 (03-Jan-2006): [Greater Blessing of Sanctuary] added.
*  Patch 3.0.2 (14-Oct-2008): Reduced to 1 rank, now reduces all damage taken by 3% and generates rage, mana or runic power when a parry/dodge/block occurs.
            Old, 5 ranks. Last rank text was "Places a Blessing on the friendly target, reducing damage dealt from all sources by up to 80 for 10 min. In addition, when the target blocks a melee attack the attacker will take 46 Holy damage."

---

Figured I'd post some comments from "Blessing of Sanctuary - required?" from [wowhead](https://www.wowhead.com/forums&topic=20313)
>I have a friend, who is a Pally tank, and he NEVER uses Blessing of Sanctuary.

>2) Sanctuary (reduces a bit of dmg and helps with aggro on multi-mobs)

>In raiding, if you can only get 1 blessing choose BoK over Sanctuary. The extra stam(health)/agi(armor/dodge)/int(mana)/strength(BV & DPS) will help you and your raid more than the minor damage mitigation and threat generation of Sanctuary.

---

>[Holy damage dealt from this bless isn’t influenced by +spell damage bonus on items.](http://paladin-guide.blogspot.com/2005/12/blessings.html) - 2005, Dec 20th

---

**Expected behaviour**: 
Shouldn't scale with spell damage, and should deal the same damage.

**Server Revision**: 
2364

**Comment by Mango-Ray** [comment]
Found a source supporting this;
http://web.archive.org/web/20080404225422/http://thottbot.com:80/s27168
![](https://i.gyazo.com/d722610e66fd5e6a507cebfea940f46f.png)

While it is not affected by spell power, it is affected by global modifiers, such as Sanctuary Aura, One-Handed Specialization..etc..

**Comment by Tenoutoften** [comment]
Nice, that explains why it was dealing a bit higher damage sometimes...

**Comment by Tenoutoften** [comment]
Resolved
