### ISSUE TITLE
[Paladin][Spell]Greater/Blessing of Sanctuary Damage Reduction formula seems off & Reducing damage to 0 causes mobs to have 100% miss chance

### ISSUE THREAD

**Issue by Tenoutoften** [Atlantiss/NetherwingBugtracker#3072]
**Description**: 
![4c5e92a1507b8855ca4a7dcfa77ad112](https://user-images.githubusercontent.com/34839199/49032033-e0526d00-f1ab-11e8-93d2-98f15f40ebac.png)
![160f5bdb9ee46d1861c62c451e0367a1](https://user-images.githubusercontent.com/34839199/49032034-e0526d00-f1ab-11e8-8f28-95d86e575ad6.png)

Current NW behavior:
When [[Spell]BoSa/GBoSa](https://db.excalibur.ws/?search=blessing+of+sanctuary) reduces the damage of mobs to 0 it causes them to miss 100% of their attacks, can be seen [here](https://www.youtube.com/watch?v=TSSaLe0TwZ8&feature=youtu.be) - I'd expect them to still hit you but the damage to be 1.

I went and tested on a big higher level mobs in WPL
Without [[Spell]BoSa/GBoSa](https://db.excalibur.ws/?search=blessing+of+sanctuary)
![110af4f9aa3a9a1a1639db5fcd5d6698](https://user-images.githubusercontent.com/34839199/49034953-ae450900-f1b3-11e8-95a6-65d3b8ab37b8.png)

With [[Spell]BoSa/GBoSa](https://db.excalibur.ws/?search=blessing+of+sanctuary)
![f5eb3b1ae72852849c37fd3c5d068efb](https://user-images.githubusercontent.com/34839199/49034955-aedd9f80-f1b3-11e8-82e7-066ec8b74953.png)

My damage reduction through armor:
![d00ef2d37006e56aa7f9cc0fe108a752](https://user-images.githubusercontent.com/34839199/49035009-d6346c80-f1b3-11e8-82bf-eb9a8a25967d.png)

Shouldn't this mob be hitting me for less? These images show I am getting roughly 20 damage reduction though I should have 46.5, this mob should be hitting me for 1? I am not sure whether to use my reduction vs 70 or vs lvl 50 either way I am making a mistake or something isn't working.

(100 - 53.5) * 80(damage reduction) = 46.5

Comments from [wowhead](https://www.wowhead.com/forums&topic=20313) on the subject
>If you are getting hit for 1000 dmg is 32 less damage really that big a deal? 

>Say you have a 60% dmg reduction through armor, this means BoSa only reduces physical dmg taken by 32 dmg, which basically equals 32 block value (if you are uncrushable). 

Patch notes from http://wowwiki.wikia.com/wiki/Blessing_of_Sanctuary:
---
* Patch 1.6.0 (12-Jul-2005): New Sparkle animation added.
* Patch 1.9.0 (03-Jan-2006): [Greater Blessing of Sanctuary] added.
*  Patch 3.0.2 (14-Oct-2008): Reduced to 1 rank, now reduces all damage taken by 3% and generates rage, mana or runic power when a parry/dodge/block occurs.
            Old, 5 ranks. Last rank text was "Places a Blessing on the friendly target, reducing damage dealt from all sources by up to 80 for 10 min. In addition, when the target blocks a melee attack the attacker will take 46 Holy damage."

---

**Expected behaviour**: 
Physical damage reduction based on armor reduction.
The lowest you can reduce the damage to is 1, mobs shouldn't get 100% chance to miss you.

**Server Revision**: 
2364

**Comment by Tenoutoften** [comment]
This should maybe scale with spell power after all:
https://www.youtube.com/watch?v=L_1kNPpo0gg
While tanking Archimonde on occasion something is hitting him for 70

**Comment by Anselm123** [comment]
Are you factoring in the fact that sanctuary scales up to 80 and not flat 80 and also the fact that flat reduction works before armor? so if it's 1000 auto attack it takes 80 off and then does the armor reduction meaning that it's damage reduction you see if less the more armor you have. If you have 0 armor it will do 80 on a boss auto but if you have say 50% reduction it will only take off 40.

(1000-80)*0.5=460
vs
(1000*0.5) -80=420

**Comment by Tenoutoften** [comment]
@Anselm123 Pretty sure I did that on the WPL spider that you see.

(100 - 53.5) * 80(damage reduction) = 46.5 

53.5 being the reduction.

**Comment by Tereneckla** [comment]
Fixed
