### ISSUE TITLE
[Items] Leatherworking Drums

### ISSUE THREAD

**Issue by joovah** [Atlantiss/NetherwingBugtracker#3073]
**Description**: Leatherworking drums (War/Battle/Restoration/Speed) got buffed in Patch 2.3 with an increased range (5-10 to 40) and the removal of the cast time (1s) plus other minor buff (usable in any druid form/peculiar changes to Panic one)

Proof:
-https://www.engadget.com/2007/10/11/big-surprises-in-patch-2-3-on-the-ptr/
"Blizzard hopes to change that now by increasing the radius of all but the Panic drums past their current 5-10 yards and removed the 1 sec casting time from all but the Panic Drums. The Panic drums only received a slight increase in radius and a slight reduction in casting time."

-http://wowwiki.wikia.com/wiki/Patch_2.3.0
 "-Greatly increased the radius of the [Drums of Battle], [Drums of Restoration], [Drums of Speed], and [Drums of War].
-Increased the range at which you can gain leatherworking skill from crafting drums.
-Removed the casting time from the Drums of Battle, Drums of Restoration, Drums of Speed, and Drums of War.
-Slightly increased the radius of [Drums of Panic].
-Reduced the casting time of Drums of Panic and added a global cooldown equal to the casting time.
-Drums can now be used while shapeshifted. " (was usable only in tree of life or moonkin before)

-https://www.wowhead.com/item=29528/drums-of-war#comments
you can find multiple comments like:
"The range on these is so low as to make them nearly useless. I couldn't measure it exactly but it's less than 15 yards, may be as short as melee range. The cast time is not short, either. Overall not a very useful item."
"10 Yard range with a 1 second cast time"
"These, like all the other drums except Drums of Panic, are getting buffed with an increased radius of effect and an instant cast time in patch 2.3."

**Current behaviour**: LW drums behave as their post 2.3 version (instant cast and 40yd range for Battle/War/Speed/Restoration)

**Expected behaviour**: Drums should be in their "weaker" (pre 2.3) state.

**Comment by gryendal** [comment]
Confirmed

**Comment by joovah** [comment]
Idk BS weapon will be unique so...

**Comment by killablink** [comment]
![image](https://user-images.githubusercontent.com/43510874/49062234-51f8de00-f1e1-11e8-8596-dfa91334baed.png)

Mechanics =/= item stats

**Comment by joovah** [comment]
???
BS changes: you cut 1 item from dual wielders
Lw changes: you basically cut drums (noone used them before ZA)

You could even just remove drums until we reach za to me, it's the same thing as any other item that was added in later patches since they got changes drammtically to basically count as a new item.

Il 27 nov 2018 07:11, killablink <notifications@github.com> ha scritto:

[image]<https://user-images.githubusercontent.com/43510874/49062234-51f8de00-f1e1-11e8-8596-dfa91334baed.png>

Mechanics =/= item stats

**Comment by Evolvee** [comment]
I will look into it, hold your horses.

Please link me all drums.

**Comment by joovah** [comment]
big one:
Drums of Battle http://db.hellfire-tbc.com/?item=29529

others:
Drums of Speed http://db.hellfire-tbc.com/?item=29530
Drums of Restoration http://db.hellfire-tbc.com/?item=29531
Drums of War http://db.hellfire-tbc.com/?item=29528

Drums of Panic http://db.hellfire-tbc.com/?item=29532

**Comment by Evolvee** [comment]
fixed in rev skrr
