### ISSUE TITLE
[Spell][Priest] Mind Flay

### ISSUE THREAD

**Issue by Thugli** [Atlantiss/NetherwingBugtracker#3074]
[//]: # (Enclose links to things related to the bug using http://wowhead.com or any other TBC database.)
[//]: # (You can use screenshot ingame to visual the issue.)
[//]: # (Write your tickets according to the format:)
[//]: # ([Quest][Azuremyst Isle] Red Snapper - Very Tasty!)
[//]: # ([NPC] Magistrix Erona)
[//]: # ([Spell][Mage] Fireball)
[//]: # ([Npc][Drop] Ghostclaw Lynx)
[//]: # ([Web] Armory doesnt work)
[//]: # (To find server revision type `.server info` command in the game chat.)

**Description**: 
While attacking a target dummy, rank 7 mindflay (Max Rank) was doing exactly 445 damage per tick, every time despite the tooltip saying the 3-second channel does  579-582 overall. As can be seen in the attached screenshot, 36 mind flay ticks were counted. Shadow word pain was used prior to testing mindflay so I could properly test all mindflay ticks with misery & 5 stacks of shadow vulnerability.  The tooltip implies there is a range of damage, whereas mind flay ticks constantly do the same damage assuming the target has the same debuffs & the player does not gain any auras that increase spell damage.

![image](https://user-images.githubusercontent.com/37326256/49039791-c9515200-f18e-11e8-86f1-22449fb6d8ad.png)

**Current behaviour**:

**Expected behaviour**: 
Mind Flay ticks should slightly vary and not be completely static all the time.
**Server Revision**: 
2364

**Comment by Easyfraggy** [comment]
![image](https://user-images.githubusercontent.com/36134067/49041875-ba869180-f1c6-11e8-9b23-fe0ec8013ab4.png)

Try clearing your cache?
