### ISSUE TITLE
[Item] Veteran's Scaled Pieces

### ISSUE THREAD

**Issue by Saben65** [Atlantiss/NetherwingBugtracker#3075]
**Description**: 
Veteran's scaled pieces were itemized quite differently pre [Patch 2.2](http://wowwiki.wikia.com/wiki/Patch_2.2.0) and 2.4 for the bracers.

> Veteran’s Scaled Belt: Stats have been adjusted to correct budget.
Veteran’s Scaled Greaves: Stats have been adjusted to correct budget.

**Current behaviour**:
Post 2.2 levels
[Veteran's Scaled Belt](https://web.archive.org/web/20080327015805/http://thottbot.com:80/i32794)
[Veteran's Scaled Greaves](https://web.archive.org/web/20080327015805/http://thottbot.com:80/i32794)

Post 2.4 levels
[Veteran's Scaled Bracers](https://web.archive.org/web/20080928031054/http://thottbot.com:80/i32819)

**Expected behaviour**: 
Pre-2.2 Levels
[Veteran's Scaled Belt](https://web.archive.org/web/20070830070740/http://www.thottbot.com:80/i32806)
[Veteran's Scaled Greaves](https://web.archive.org/web/20070630230634/http://www.thottbot.com:80/i32794)

Pre-2.4 Levels
[Veteran's Scaled Bracers](https://web.archive.org/web/20080319085432/http://thottbot.com:80/i32819)

**Server Revision**: 
2364

**Comment by aresbrutus** [comment]
Fixed in rev `Phoebe`
