### ISSUE TITLE
Enrage not instantly generating rage with resto talent Intensity

### ISSUE THREAD

**Issue by Cygmus** [Atlantiss/NetherwingBugtracker#3076]
[//]: # (Enclose links to things related to the bug using http://wowhead.com or any other TBC database.)
[//]: # (You can use screenshot ingame to visual the issue.)
[//]: # (Write your tickets according to the format:)
[//]: # ([Quest][Azuremyst Isle] Red Snapper - Very Tasty!)
[//]: # ([NPC] Magistrix Erona)
[//]: # ([Spell][Mage] Fireball)
[//]: # ([Npc][Drop] Ghostclaw Lynx)
[//]: # ([Web] Armory doesnt work)
[//]: # (To find server revision type `.server info` command in the game chat.)

**Description**: The druid ability Enrage is generating the "instant" rage from the talent Intensity with a slight delay instead of immediately on key press.

**Current behavior**: The base spell is correct, 20 rage is generated over 10 seconds but the instant rage is generated just before the first tick. (approximately 200ms before?) There is also no combat log entry for the 4/7/10 rage but I am unsure if there is suppose to be one.

**Expected behavior**: The 4/7/10 rage from the talent should be generated instantly.

**Server Revision**: 2364

**Comment by Easyfraggy** [comment]
Need proof that this should be exempt from batching.

**Comment by Cygmus** [comment]
I though batching only applied to abilities cast on other units?

**Comment by Easyfraggy** [comment]
Evidence from Mvtsvraev is pretty damn solid.
