### ISSUE TITLE
[Quest][Nagrand] Ring of Blood: The Final Challenge

### ISSUE THREAD

**Issue by itsjojotbh** [Atlantiss/NetherwingBugtracker#3077]
[//]: # (Enclose links to things related to the bug using http://wowhead.com or any other TBC database.)
[//]: # (You can use screenshot ingame to visual the issue.)
[//]: # (Write your tickets according to the format:)
[//]: # ([Quest][Azuremyst Isle] Red Snapper - Very Tasty!)
[//]: # ([NPC] Magistrix Erona)
[//]: # ([Spell][Mage] Fireball)
[//]: # ([Npc][Drop] Ghostclaw Lynx)
[//]: # ([Web] Armory doesnt work)
[//]: # (To find server revision type `.server info` command in the game chat.)

**Description**: 
The RP text upon defeating the final quest mob Mogor is not existing
**Current behaviour**:
Mogor yells on aggro the first time and again after he resurrects, but Gurgthock doesn't yell anything when Mogor is defeated
**Expected behaviour**: 
Gurgthock is supposed to yell "{Player/pet who got the killing blow} has defeated the hero of the Warmaul, Mogor! All hail {Player/pet who got the killing blow}!
Evidence here: [https://www.wowhead.com/npc=18069/mogor#comments:id=316896](url)
[https://imgur.com/a/zxRk61r](url) as evidence here he doesn't yell anything between Mogor ressing and me completing the quest

**Server Revision**: 
2364

**Comment by Tereneckla** [comment]
Fixed
