### ISSUE TITLE
The Defias Brotherhood Escort

### ISSUE THREAD

**Issue by Echoxias** [Atlantiss/NetherwingBugtracker#308]
**Description**: 
Along with the escort not attacking mobs that are pulled by the player, I failed the quest during a server crash and the quest is no longer in my quest log to be abandoned or able to be accepted at the quest giver.  Player name in game is Nero
**Current behaviour**:
Escort attacks enemies only that it aggros. When quest is failed it disappears from the quest log and is no longer able to be re-accepted at the quest giver.
**Expected behaviour**:
Escort assists with enemies that it pulls along with enemies the player pulls within in it's aggro range. If the quest is failed it is considered failed in the quest log and should be able to be re-accepted at the quest giver.
**Server Revision**:

**Comment by Scylla420** [comment]
just for reference, the first half of the report (npc not assisting players) was also reported [here](https://github.com/Atlantiss/NetherwingBugtracker/issues/267)

**Comment by Navedonar** [comment]
.

**Comment by The14me** [comment]
rev.3441 u can fail/abound the q and take it again with no problem.
Can be closed.
