### ISSUE TITLE
Engineering Materials Cannot Be Obtained

### ISSUE THREAD

**Issue by Mou-nw** [Atlantiss/NetherwingBugtracker#3080]
**Description**: 
Cannot obtain Fused Wiring 
AND Inlaid Mithril Cylinder and Goblin Rocket Fuel also an issue

**Current behaviour**:

### 1. Fused Wiring
Target Dummies should leave behind a lootable corpse the has a chance to contain fused wiring. At the moment there is no corpse to loot on despawn.

Viggz Shinesparked in Shatt sells the schematic for Fused Wiring but only in a later patch (2.4?). No schematic for this in the Beta

Recipes I cannot make due to this:
- Gnomish Cloaking Device
- Mechanical Dragonling

### 2. Goblin Rocket Fuel
I haven't seen Volatile Rum for sale at a beta materials vendor (might be mistaken, but I have looked). 
Do I have to make a toon just for Alchemy_ and then farm the rum??? Just for 4x rocket fuel...

Recipes I cannot make due to this:
- Mithril Mechanical Dragonling
- Arcanite Mechanical Dragonling (uses Mithril Mechanical Dragonling as a mat)

### 3. Inlaid Mithril Cylinder
Would be nice to have at the vendor.  Same as above, would have to make a BS toon just to make 5x of this.

Recipes I cannot make due to this:
- Gnomish Death Ray
- Gnomish Battle Chicken
- Mithril Mechanical Dragonling
- Arcanite Mechanical Dragonling (uses Mithril Mechanical Dragonling as a mat)

### 4. Where is the schematic for Rocket Boots Xtreme Lite?
Are the cloth boots added in a later patch?

**Expected behaviour**: 
1. Fused Wiring
Should be obtainable from target dummy
_Perhaps add the mat to a vendor during beta?_

2. Rocket Fuel and 3. Inlaid Cylinder
_Add material to beta vendor?_

4. Rocket Boots
_Wheee!_

**Server Revision**: 
2364

**Comment by Saben65** [comment]
The cloth rocket boots were added in [Patch 2.4](http://wowwiki.wikia.com/wiki/Patch_2.4.0).

> A new recipe has been added for [Rocket Boots Xtreme Lite], a cloth version of the [Rocket Boots Xtreme]. This pattern drops from Combat 15 Mechano-Lord Capacitus.

**Comment by Dusky1** [comment]
Schematic: Fused Wiring should be sold by Xizzer Fizzbolt in Everlook (limited supply).

Its also not possible to create Goblin Jumper Cables XL due to lack of this recipe.

**Comment by ibogdandx** [comment]
Bump. This should drop yes. You need fused wiring for Repair bots aswell ( Raiding )...

**Comment by Manaci** [comment]
Most of the stuff is fixed or was a beta issue only, target dummies not having loot is reported alone here #3936
