### ISSUE TITLE
[Paladin][Spell] Seal of blood not always proccing

### ISSUE THREAD

**Issue by Novat93** [Atlantiss/NetherwingBugtracker#3081]
[//]: # (Enclose links to things related to the bug using http://wowhead.com or any other TBC database.)
[//]: # (You can use screenshot ingame to visual the issue.)
[//]: # (Write your tickets according to the format:)
[//]: # ([Quest][Azuremyst Isle] Red Snapper - Very Tasty!)
[//]: # ([NPC] Magistrix Erona)
[//]: # ([Spell][Mage] Fireball)
[//]: # ([Npc][Drop] Ghostclaw Lynx)
[//]: # ([Web] Armory doesnt work)
[//]: # (To find server revision type `.server info` command in the game chat.)

**Description**: 
Through testing, hitting the test dummies in Shattrath. I have come across an oddity, where on rare occasions, seal of blood will not proc.

**Current behaviour**:
Seal of blood, will on rare occasions, not proc despite the seal being applied to the paladin.

**Expected behaviour**: 
Seal of blood should have a 100% proc chance, provided the paladin actually hits the target. 
I.e the attack is a hit, crit or a glancing blow and NOT a dodge, parry or a miss.

**Server Revision**: 
2364

As can be seen in the picture bellow. The amount of melee hits exceed the amount of seal of blood procs by 2, instead of the expected 1 dropped proc due to the dummy dodging an attack.
![seal of blood case 2](https://user-images.githubusercontent.com/36829235/49059282-6c927d80-f208-11e8-858a-61208e71780d.PNG)

A second attempt, using a much faster weapon and more expertise.
![seal of blood case 4](https://user-images.githubusercontent.com/36829235/49059391-00fce000-f209-11e8-8eb5-d55cd1770e94.PNG)

The attack hitting for 191 points of physical damage does not trigger the seal.
![seal of blood case 3](https://user-images.githubusercontent.com/36829235/49059403-0bb77500-f209-11e8-86cd-608497300b98.PNG)

**Comment by Mikik3jr** [comment]
Is this the same issue?
https://github.com/Atlantiss/NetherwingBugtracker/issues/208

**Comment by Novat93** [comment]
Seems i made an error when i posted the error report late last night. The second screenshot does not actually show the bug, and seal of blood damage was actually done.

Editing it out.

**Comment by Tereneckla** [comment]
Fixed
