### ISSUE TITLE
[NPC][Spell] Wrath-Scryer Soccothrates

### ISSUE THREAD

**Issue by Chickengrease** [Atlantiss/NetherwingBugtracker#3082]
[//]: # (Enclose links to things related to the bug using http://wowhead.com or any other TBC database.)
[//]: # (You can use screenshot ingame to visual the issue.)
[//]: # (Write your tickets according to the format:)
[//]: # ([Quest][Azuremyst Isle] Red Snapper - Very Tasty!)
[//]: # ([NPC] Magistrix Erona)
[//]: # ([Spell][Mage] Fireball)
[//]: # ([Npc][Drop] Ghostclaw Lynx)
[//]: # ([Web] Armory doesnt work)
[//]: # (To find server revision type `.server info` command in the game chat.)

**Description**: 

Ask Kutsal for more info. He threatened me into making this report. 

**Current behaviour**:

http://db.hellfire-tbc.com/?npc=20886#abilities

His fire spells do physical based damage on NW.

**Expected behaviour**: 

Some evidence that the spells should belong to the fire school. 

https://web.archive.org/web/20111208013201/https://www.wowhead.com/npc=20886/wrath-scryer-soccothrates#abilities

https://web.archive.org/web/20111208013201/https://www.wowhead.com/npc=20886/wrath-scryer-soccothrates#comments:id=25186

"Make sure your tank doesn't stand in the fire if he gets a charge (since the "charge" is basically stationary). Run a fire resistance aura if you have a Pally. Spread the group out."

"Fire resistance totems do help mitigate the damage taking from his immolation spell."

http://www.tentonhammer.com/guides/the-arcatraz-guide-0f279fab-2bc2-46c1-a93f-5c557c8853a1

"The fight is basically a full out DPS fight to down him before his flame damage kills everyone. Fire resist on the melee players that need to be in his immolation aura is extremely helpful, but not necessary if players are good at stepping out and bandaging before they get to bad."

Also videos on Youtube show many groups running a fire resistance totem. 

**Server Revision**:

**Comment by aresbrutus** [comment]
https://youtu.be/fGxe6d_w6b4?t=207

You can actually read fire damage in the combat log her about the fel immolation which is also physical atm. So we can assume the physical damage should be changed to fire damage yes.

**Comment by Evolvee** [comment]
![image](https://user-images.githubusercontent.com/1942409/52178006-17a35280-27c9-11e9-8555-850d1a54fc07.png)

**Comment by Evolvee** [comment]
![image](https://user-images.githubusercontent.com/1942409/52178032-78328f80-27c9-11e9-88be-c9ccf7246895.png)
![image](https://user-images.githubusercontent.com/1942409/52178033-7d8fda00-27c9-11e9-88b1-9775547bf00b.png)

works fine for me?
