### ISSUE TITLE
[Instance] Black Moras event auto restart.

### ISSUE THREAD

**Issue by Cherryxo** [Atlantiss/NetherwingBugtracker#3083]
[//]: # (Enclose links to things related to the bug using http://wowhead.com or any other TBC database.)
[//]: # (You can use screenshot ingame to visual the issue.)
[//]: # (Write your tickets according to the format:)
[//]: # ([Quest][Azuremyst Isle] Red Snapper - Very Tasty!)
[//]: # ([NPC] Magistrix Erona)
[//]: # ([Spell][Mage] Fireball)
[//]: # ([Npc][Drop] Ghostclaw Lynx)
[//]: # ([Web] Armory doesnt work)
[//]: # (To find server revision type `.server info` command in the game chat.)

**Description**: 
In black moras you are supposed to defend medivh untill he can open the black portal(?). You do this by killing different mobs spawning from portals, if you do not aggro mobs that spawn from a portal, they will walk towards medivh and start depleting his shield. When the shield reaches 0% medivh dies and the event ends.

I realise the vod linked later is long so if you have any questions then please ask and I shall try to answer them.

**Current behaviour**:
If you let Medivh's shield deplete then he will die and all mobs will despawn, however, it seems as if the event automatically restarts instantly. Portals start spawning even tho Medivh is dead and mobs will start doing work on a shield that do not exist. You do not get any indication that the event is going (shield %, portal number) other than portals spawning. 

[Here is a vod from the run where this occured.](https://www.twitch.tv/videos/341321189?t=4h52m30s) Between linked time and about 5h 20m we are standing around trying to figure out what the hell is going on.

**Expected behaviour**: 
When medivh dies the event should end and you should have to wait untill medivh respawns before you can start it again.

**Server Revision**: 
2364

**Comment by Wolffenstein** [comment]
Fixed in rev 2366.
