### ISSUE TITLE
[Dungeon]Botanica[NPC]Bloodwarder Protector [Spell]=35399 Spell Reflection stacks not being consumed

### ISSUE THREAD

**Issue by Corrozus** [Atlantiss/NetherwingBugtracker#3084]
[//]: # (Enclose links to things related to the bug using http://wowhead.com or any other TBC database.)
[//]: # (You can use screenshot ingame to visual the issue.)
[//]: # (Write your tickets according to the format:)
[//]: # ([Quest][Azuremyst Isle] Red Snapper - Very Tasty!)
[//]: # ([NPC] Magistrix Erona)
[//]: # ([Spell][Mage] Fireball)
[//]: # ([Npc][Drop] Ghostclaw Lynx)
[//]: # ([Web] Armory doesnt work)
[//]: # (To find server revision type `.server info` command in the game chat.)

**Description**: Akin to issue #2486  and #3052 

**Current behaviour**: Reflected hostile spells do not consume a stack of Spell Reflection

**Expected behaviour**: Reflected Spells should consume a stack

**Server Revision**:  2364

**Comment by Wolffenstein** [comment]
Fixed in rev 2366.
