### ISSUE TITLE
[Item]Set Oblivion Raiment

### ISSUE THREAD

**Issue by ircfelix** [Atlantiss/NetherwingBugtracker#3085]
**Description**: 
The Warlock D3 set Oblivion Raiment should give a 45 mp5 bonus when equipping two parts of it. 

**Current behaviour**:
Without the 2 part set bonus of the set, I have 65 mp5 while casting.
When equip 2 parts for the bonus, my Mana goes up to 67 mp5 while casting.

**Expected behaviour**: 
Equipping 2 parts of the set should give 45 mp5 on top of the 2 mp5 I get.

**Server Revision**: 
2364

**Comment by Tenoutoften** [comment]
It's 45 mp5 to your pet

**Comment by ircfelix** [comment]
oh my! sorry! pls close this!
