### ISSUE TITLE
[Karazhan][Boss] Moroes: Divine Shield of the adds can't be removed with mass dispell

### ISSUE THREAD

**Issue by ircfelix** [Atlantiss/NetherwingBugtracker#3089]
**Description**: 
See title. Some of moroes' adds use divine shield during the encounter.

**Current behaviour**:
See title.

**Expected behaviour**: 
Divine shield and other effects that grant immunity should be dispellable by a priest's mass dispell

**Server Revision**:

**Comment by Easyfraggy** [comment]
Need proof from retail.

**Comment by ircfelix** [comment]
http://wowwiki.wikia.com/wiki/Moroes?oldid=1048446

Search for mass dispell.
And i think it was a thing back then.

**Comment by Wolffenstein** [comment]
Fixed in rev 3427.
