### ISSUE TITLE
Unseen mobs around Jitters and Stalvan in Duskwood

### ISSUE THREAD

**Issue by wtRCH** [Atlantiss/NetherwingBugtracker#309]
[//]: # (Enclose links to things related to the bug using http://wowhead.com or any other TBC database.)
[//]: # (You can use screenshot ingame to visual the issue.)
[//]: # (Write your tickets according to the format:)
[//]: # ([Quest][Azuremyst Isle] Red Snapper - Very Tasty!)
[//]: # ([NPC] Magistrix Erona)
[//]: # ([Spell][Mage] Fireball)
[//]: # ([Npc][Drop] Ghostclaw Lynx)
[//]: # ([Web] Armory doesnt work)

**Description**: In Duskwood, near Stalvan and Jitters they are mobs on level 51 called Unseen (you can't see it without GM mode) who oneshots players around.

**Comment by Evolvee** [comment]
https://github.com/Atlantiss/NetherwingBugtracker/issues/402
