### ISSUE TITLE
[Core Mechanic][Spell]Intimidating shout should have a chance to resist

### ISSUE THREAD

**Issue by Tenoutoften** [Atlantiss/NetherwingBugtracker#3090]
**Description**: 
This is likely a core issue, Intimidating Shout should have a chance to resist even though it is tagged as a physical school according to the patch notes of 1.10 linked below. I tested on [[NPC]Scarlet Defender#4298](https://www.wowhead.com/npc=4298/scarlet-defender),  [[Spell]Intimidating Shout#20511](https://db.excalibur.ws/?spell=20511). As a 70 I keep getting feared though I resist almost everything else from the other mobs. 

This mob was mentioned in another bug report:
----
https://github.com/Atlantiss/NetherwingBugtracker/issues/1610
>NPC] Scarlet Defender- Intimidating Shout [20511]
https://web.archive.org/web/20080620084025/http://wow.allakhazam.com:80/db/mob.html?wmob=4298

Current behaviour:
They doesn't seem to use [Spell] Intimidating Shout [20511]. Waited like for 1min+ nothing. Brought them down to less than 20% hp still nothing. So my assumption is they don't have it.

Expected behaviour:
They should use [Spell] Intimidating Shout [20511] every 30-40s.

Server Revision:
2177
----

**http://wowwiki.wikia.com/wiki/Patch_1.10.0**
Patch 1.10.0 (28-Mar-2006): The cowering in fear effect will no longer be applied **when the target resists this shout**. In addition, this shout will now affect a maximum of 5 targets.

**Expected behaviour**: 
Expected to have a high chance to resist an intimidating shout from a low level mob.

**Server Revision**: 
2364

**Comment by killablink** [comment]
Worth checking if warrior fear has a chance to resist too, I'd test it but trying with 3 min CD would take too long

**Comment by Tenoutoften** [comment]
What do you mean check?
The patch notes reveal it should resist. I don't get why this is tagged with need research... What am I missing? @wtRCH

**Comment by Tenoutoften** [comment]
I can prob test it

**Comment by Tenoutoften** [comment]
I made 3 warriors and used the ability 20 times in dual, zero resists.

**Comment by Tenoutoften** [comment]
A warrior friend of mine tells me he has never gotten his intimidating shout resisted

**Comment by Wolffenstein** [comment]
Fixed in rev 2395.
