### ISSUE TITLE
[Raid][SSC] Fathom Guard Sharkiss "Hurl Trident" ability 

### ISSUE THREAD

**Issue by Dollywog** [Atlantiss/NetherwingBugtracker#3091]
[//]: # (Enclose links to things related to the bug using http://wowhead.com or any other TBC database.)
[//]: # (You can use screenshot ingame to visual the issue.)
[//]: # (Write your tickets according to the format:)
[//]: # ([Quest][Azuremyst Isle] Red Snapper - Very Tasty!)
[//]: # ([NPC] Magistrix Erona)
[//]: # ([Spell][Mage] Fireball)
[//]: # ([Npc][Drop] Ghostclaw Lynx)
[//]: # ([Web] Armory doesnt work)
[//]: # (To find server revision type `.server info` command in the game chat.)

**Description**: When this Fathom Guard uses his Throw Spear ability, he runs towards the players he is targetting with it before throwing a spear and going back to the tank.

**Current behaviour**:  Switches targets, runs away from tank at high speed, uses ability (can also see Leeching Throw cast time) + gets in range before completing animation, then runs back to tank.    This is not over-aggroing as you can see in clip he uses this on healers and other raid members on the other Fathom Guard groups.

**Expected behaviour**:  Fathom Guard should remain still , face the player he is using Spear Throw on and throw it in approx 1.5 seconds with no range limit.   He should still change targets as he is doing but remain still.   This greatly improves tanking ability on the boss (due to limited melee range and fast moving boss)

**Server Revision**:  Possibly fixed by removing range cap on the Spear Throw so Fathom Guard doesn't have to run to ~20 yards range of each target.  I can see on some DB that it has 30 yard range, in which case maybe it should only target players within 30 yards originally so he doesn't have to move around?

https://clips.twitch.tv/PlacidFairGarageYouWHY

Trying to find old videos of expected behaviour, watching this in 0.5 speed is hard to make out throwing animation but you can see Fathom Guard stays still as he is killed unless the tank moves to dodge Whirlwind
https://www.youtube.com/watch?v=pub88sW4Jxs&feature=youtu.be&t=88

**Comment by Brasso** [comment]
https://youtu.be/siCBD90IJ7k?t=121

**Comment by Wolffenstein** [comment]
Fixed in rev 2706.
