### ISSUE TITLE
[Spell][Druid] Cyclone letting through last tick of lifebloom

### ISSUE THREAD

**Issue by Picajzla** [Atlantiss/NetherwingBugtracker#3092]
**Description**: If lifebloom is cast on target before it gets cycloned,the last tick of lifebloom will heal the target through cyclone.

**Current behaviour**:   https://youtu.be/x-HLm3JjH2w

**Expected behaviour**:  Cyclone should block all healing on the target.

**Server Revision**:

**Comment by wtRCH** [comment]
@Evolvee please comment on this.

**Comment by Evolvee** [comment]
bug

**Comment by Wolffenstein** [comment]
Fixed in rev 2442.
