### ISSUE TITLE
[Dungeon] [NPC] Durnholde Warden

### ISSUE THREAD

**Issue by Dollywog** [Atlantiss/NetherwingBugtracker#3093]
[//]: # (Enclose links to things related to the bug using http://wowhead.com or any other TBC database.)
[//]: # (You can use screenshot ingame to visual the issue.)
[//]: # (Write your tickets according to the format:)
[//]: # ([Quest][Azuremyst Isle] Red Snapper - Very Tasty!)
[//]: # ([NPC] Magistrix Erona)
[//]: # ([Spell][Mage] Fireball)
[//]: # ([Npc][Drop] Ghostclaw Lynx)
[//]: # ([Web] Armory doesnt work)
[//]: # (To find server revision type `.server info` command in the game chat.)

**Description**: Durnholde Warden (Heroic) [may also be on Normal mode] can cast it's Dispel Magic ability whilst in hard CC

**Current behaviour**:  Whilst in a full Fear and Entangling Roots, the Warden dispelled its own Roots and its own Fear whilst it was still under the Fear effect.

**Expected behaviour**:  Should not be able to cast it's abilities whilst under hard CC (see also Ethereal Spellbinder in Mana Tombs Heroic which can do this)

**Comment by aresbrutus** [comment]
I just tested it out and works fine for me: https://gfycat.com/UnfortunateAgileArizonaalligatorlizard

Any footage of it happening to you?

**Comment by aresbrutus** [comment]
I would require some video footage as it was fine for me.

**Comment by Easyfraggy** [comment]
Is it possible that the damage from entangling roots broke the fear and he then dispelled himself?

**Comment by Evolvee** [comment]
reopen if happens again
