### ISSUE TITLE
Scourgebane Draught and Infusion aren't stacking with flasks/elixirs

### ISSUE THREAD

**Issue by Anselm123** [Atlantiss/NetherwingBugtracker#3094]
https://www.wowhead.com/item=22779/scourgebane-draught#comments

https://www.wowhead.com/item=22778/scourgebane-infusion#comments

**Description**: 

Scourgebane Draught and infusion consumables gotten from the ghostlands are suppose to stack with Flasks and elixirs 

**Current behaviour**:

Don't stack with flasks and elixirs

**Expected behaviour**: 

Suppose to be able to stack and aren't guardian/battle effects

**Server Revision**:

**Comment by duzyizly** [comment]
still a thing as rev 3392 ptr.
![WoWScrnShot_062020_124000](https://user-images.githubusercontent.com/43931626/85199889-2d98b100-b2f3-11ea-91ab-468c91d9b728.jpg)

**Comment by Wolffenstein** [comment]
Fixed in rev 3393.
