### ISSUE TITLE
[Talent][Shaman] Elemental devastation

### ISSUE THREAD

**Issue by Shakill0Neal** [Atlantiss/NetherwingBugtracker#3097]
**Description**: Trigger "Elemental devastation" talent elemental shaman

**Current behaviour**: Talent works on totem "searing totem" while on others "magma-fire nova totem" don't working. 
https://classic.wowhead.com/spell=29180/elemental-devastation

**Expected behaviour**: Talent proc on all fire totem

**Server Revision**:

**Comment by Easyfraggy** [comment]
Need evidence that this talent should proc from totems.

**Comment by teddys** [comment]
Kitanue on 2007/05/18 (Patch 2.0.12)

I was curious about this as well and tested it. Unfortunately, Elemental Devastation does NOT proc off flametongue nor frostbrand weapons :(

doesn't even proc from imbues so why would it proc from totems

**Comment by Shakill0Neal** [comment]
indeed i don't understand. It could also be that works on flamentongue and frostband, that's how it goes on smoldeforge server but i'm not sure it's right. However on totems it should be right the proc since that's how it is on wowhead.

**Comment by Brasso** [comment]
Elemental Devastation procing from anything else than direct spell crits such as shocks, LB or CL is some private server stuff. It is currently procing from searing totem, which is a bug and should be fixed.

![ed2](https://user-images.githubusercontent.com/44345420/50162768-65c6ca00-02df-11e9-856f-8d5b8dad3512.png)
![ed3](https://user-images.githubusercontent.com/44345420/50162772-67908d80-02df-11e9-9381-77e2c6672301.png)
![ed4](https://user-images.githubusercontent.com/44345420/50162776-68c1ba80-02df-11e9-9ba2-5fb5e9d78495.png)
![ed5](https://user-images.githubusercontent.com/44345420/50162780-69f2e780-02df-11e9-99dd-03ae2da219c6.png)

**Comment by torrenzGH** [comment]
Related to #393

> The damage portion of this totem's [Attack] spell is incorrectly triggered by the shaman instead of the totem. It adds aggro to the you instead of the totem, in the combat log it shows you doing the damage, and it even procs lightning shield onto you.
> 
> ![image](https://user-images.githubusercontent.com/1574432/46149954-bfcd6b80-c26b-11e8-94de-ae1243a5b12e.png)

I also experienced this behavior by getting Eye of Magtheridon proc from a searing totem resist.

**Comment by Tereneckla** [comment]
#6531 is the issue, not Elemental Devastation
