### ISSUE TITLE
Regular mobs getting the "ding" effect around them when spawning.

### ISSUE THREAD

**Issue by Adrian1235a** [Atlantiss/NetherwingBugtracker#31]
As the title says, the mobs get the level up effect when they spawn. Small detail thing but I just wanted to report it anyway.

**Comment by Sinyr** [comment]
Can confirm. On other servers it usually happened if a monster spawned at a higher level than the last time you saw it, but on here it also happened when a level 1 Volatile Mutation spawned.

**Comment by bumbaloe** [comment]
Occurred with lv. 6 Ravaged Corpse in Tirisfal Glades.

**Comment by Wolffenstein** [comment]
Please retest after revision 2275.
