### ISSUE TITLE
Dead corpse on the air

### ISSUE THREAD

**Issue by Erodraeda** [Atlantiss/NetherwingBugtracker#310]
[//]: # (Enclose links to things related to the bug using http://wowhead.com or any other TBC database.)
[//]: # (You can use screenshot ingame to visual the issue.)
[//]: # (Write your tickets according to the format:)
[//]: # ([Quest][Azuremyst Isle] Red Snapper - Very Tasty!)
[//]: # ([NPC] Magistrix Erona)
[//]: # ([Spell][Mage] Fireball)
[//]: # ([Npc][Drop] Ghostclaw Lynx)
[//]: # ([Web] Armory doesnt work)

**Description**: 
Jumped from the Zepellin and died from falling damage
**Current behaviour**:
My corpse stood in mid air, just like shown in the print screen
![screenshot_486](https://user-images.githubusercontent.com/40346279/45935628-8e128700-bf83-11e8-8e3d-a3615ac5df3b.png)
**Expected behaviour**: 
My corpse should be in the ground
**Server Revision**:

**Comment by Wolffenstein** [comment]
Fixed
