### ISSUE TITLE
[Item]Destructive Skyfire Diamond#25890 should require 5 red gems in 2.0(Changes in 2.1)

### ISSUE THREAD

**Issue by Tenoutoften** [Atlantiss/NetherwingBugtracker#3100]
**Description**: 
[[Item]Insightful Earthstorm Diamond#25901](https://www.wowhead.com/item=25901/insightful-earthstorm-diamond#comments) is suppose to require 5 red gems. Figured if we are changing drums we might as well change the meta gems: https://github.com/Atlantiss/NetherwingBugtracker/issues/3073

![f60844c9588f84ff30f662f7af7b350e](https://user-images.githubusercontent.com/34839199/49161085-6f848f80-f328-11e8-8e67-2e987b517fbd.png)
![b35e2b58227dc3147d17d2faee3996af](https://user-images.githubusercontent.com/34839199/49161542-5b8d5d80-f329-11e8-887e-e80d8da72c6a.png)
![091123ffe96477ddab667ae1602cd27e](https://user-images.githubusercontent.com/34839199/49162073-6dbbcb80-f32a-11e8-89ce-3074bf6fce7a.png)

https://web.archive.org/web/20070227063621/http://www.wowhead.com:80/?item=25890

**Current behaviour**:
Requires 2 gems of each color.

**Expected behaviour**: 
Expected to require 5 red gems.

**Server Revision**: 
2364

**Comment by Easyfraggy** [comment]
Patch it changed?
