### ISSUE TITLE
[Item]Powerful Earthstorm Diamond#25896 should require 5 blue gems (Changes in 2.1)

### ISSUE THREAD

**Issue by Tenoutoften** [Atlantiss/NetherwingBugtracker#3102]
**Description**: 
https://www.wowhead.com/item=25896/powerful-earthstorm-diamond#comments
https://web.archive.org/web/20070305164511/http://www.wowhead.com:80/?item=25896
![ad71a821e486c25c487decb68d48c7fe](https://user-images.githubusercontent.com/34839199/49163194-d146f880-f32c-11e8-8216-ff7cfcdc0ba2.png)

**Current behaviour**:
Requires 3 blue gems.

**Expected behaviour**: 
Require 5 blue gems.

**Server Revision**: 
2364

**Comment by Easyfraggy** [comment]
Patch it changed?
