### ISSUE TITLE
[Item]Tenacious Earthstorm Diamond#25898 should require 5 of each gem color instead of just 5 blue(Changes in 2.1)

### ISSUE THREAD

**Issue by Tenoutoften** [Atlantiss/NetherwingBugtracker#3103]
**Description**: 
https://www.wowhead.com/item=25898/tenacious-earthstorm-diamond#comments
https://web.archive.org/web/20070305103508/http://www.wowhead.com:80/?item=25898

**Current behaviour**:
Requires 5 blue

**Expected behaviour**: 
Require 5 red, yellow, blue

**Server Revision**: 
2364

**Comment by Easyfraggy** [comment]
Patch it changed?
