### ISSUE TITLE
[Item]Bracing Earthstorm Diamond#25897 should require more yellow than blue & more red then blue rather more red than blue(Changes in 2.3.2)

### ISSUE THREAD

**Issue by Tenoutoften** [Atlantiss/NetherwingBugtracker#3104]
**Description**: 
https://www.wowhead.com/item=25897/bracing-earthstorm-diamond
https://web.archive.org/web/20070307081443/http://www.wowhead.com:80/?item=25897

**Current behaviour**:
Requires more red than blue gems.

**Expected behaviour**: 
Should require more yellow than blue gems & more red than blue gems

**Server Revision**: 
2364

**Comment by Easyfraggy** [comment]
Which patch was this changed?
