### ISSUE TITLE
"Dissension Amongst the Ranks..." quest not giving credit for last kill

### ISSUE THREAD

**Issue by Lariari** [Atlantiss/NetherwingBugtracker#3106]
Killed 3 mobs without getting credit, killed the 4th one and got it to complete.

https://www.youtube.com/watch?v=jRpUbAj-3aM

**Comment by AxeCell** [comment]
It's probably related to the killing blow. My theory is that the warlock got the final blow without the costume on, and the costume is required to recieve the proper credit.

**Comment by Manaci** [comment]
Fixed
