### ISSUE TITLE
[Item]Shattrath Leggings#30257 should have 22 Feral Combat Skill Rating rather than expertise(Changes in 2.3)

### ISSUE THREAD

**Issue by Tenoutoften** [Atlantiss/NetherwingBugtracker#3107]
**Description**: 
https://www.wowhead.com/item=30257/shattrath-leggings
https://web.archive.org/web/20070317193923/http://www.wowhead.com:80/?item=30257

Should have 22 feral combat skill rating rather than expertise until 2.3

**Current behaviour**:
Got expertise

**Expected behaviour**: 
Should have 22 feral combat skill rating rather than expertise until 2.3

**Server Revision**: 
2364

**Comment by Easyfraggy** [comment]
We wont be changing expertise.
