### ISSUE TITLE
[Item]Clefthoof Hide Leggings#31544 should have Feral combat skill rating 18 rather than expertise(Changes in 2.3)

### ISSUE THREAD

**Issue by Tenoutoften** [Atlantiss/NetherwingBugtracker#3108]
**Description**: 
https://www.wowhead.com/item=31544/clefthoof-hide-leggings
https://web.archive.org/web/20070515061637/http://www.wowhead.com:80/?item=31544

Should have feral combat skill rating 18 rather than expertise rating 18.

**Current behaviour**:
18 expertise rating

**Expected behaviour**: 
18 Feral Combat Skill Rating rather than expertise

**Server Revision**: 
2364

**Comment by Easyfraggy** [comment]
We wont be changing expertise.
