### ISSUE TITLE
[Item]Flesh Handlers Gauntlets#30341 should have feral combat skill rating rather than expertise (Changes in 2.3)

### ISSUE THREAD

**Issue by Tenoutoften** [Atlantiss/NetherwingBugtracker#3109]
**Description**: 
https://www.wowhead.com/item=30341/flesh-handlers-gauntlets#comments
https://web.archive.org/web/20070228225359/http://www.wowhead.com:80/?item=30341
Should have 18 feral combat skill rating rather than 18 expertise rating

**Current behaviour**:
18 expertise rating

**Expected behaviour**: 
Should have 18 feral combat skill rating rather than 18 expertise rating

**Server Revision**: 
2364

**Comment by Easyfraggy** [comment]
We wont be changing expertise.
