### ISSUE TITLE
Wrong Lynx in Ghostlands

### ISSUE THREAD

**Issue by deku100** [Atlantiss/NetherwingBugtracker#311]
[//]: # (Enclose links to things related to the bug using http://wowhead.com or any other TBC database.)
[//]: # (You can use screenshot ingame to visual the issue.)
[//]: # (Write your tickets according to the format:)
[//]: # ([Quest][Azuremyst Isle] Red Snapper - Very Tasty!)
[//]: # ([NPC] Magistrix Erona)
[//]: # ([Spell][Mage] Fireball)
[//]: # ([Npc][Drop] Ghostclaw Lynx)
[//]: # ([Web] Armory doesnt work)

**Description**: Wrong Lynx in Ghostlands

**Current behaviour**: Low level lynx from Eversong Woods spawned in Ghostlands, west of the Sanctum of the Moon.
![wowscrnshot_092318_215844](https://user-images.githubusercontent.com/43505181/45935833-86e87a80-bf7d-11e8-9d76-24e653ccb1e5.jpg)

**Expected behaviour**: Elder Springpaw doesn't spawn in this location.

**Server Revision**:

**Comment by aresbrutus** [comment]
Will be fixed in one of the next updates.
