### ISSUE TITLE
[Item]Thoriumweave Cloak#28256 should have 318 armor rather than 390 (Changes in 2.1)

### ISSUE THREAD

**Issue by Tenoutoften** [Atlantiss/NetherwingBugtracker#3111]
**Description**: 
http://web.archive.org/web/20070314062712/http://www.thottbot.com:80/i28256
https://www.wowhead.com/item=28256/thoriumweave-cloak&bonus=4101

http://wowwiki.wikia.com/wiki/Patch_2.1.0
Armor: All Burning Crusade items that spent part of their budget on increased armor have been re-evaluated. Some gained additional armor, while others gained other additional bonuses.

**Current behaviour**:
390 armor

**Expected behaviour**: 
318 armor

**Server Revision**: 
2364

**Comment by aresbrutus** [comment]
Fixed in rev `Phoebe`
