### ISSUE TITLE
[Item]Manimal's Cinch#30942 should have 284 armor rather than 348 armor(Changes in 2.1)

### ISSUE THREAD

**Issue by Tenoutoften** [Atlantiss/NetherwingBugtracker#3112]
**Description**: 
http://wowwiki.wikia.com/wiki/Patch_2.1.0
>Armor: **All Burning Crusade items** that spent part of their budget on increased armor have been re-evaluated. Some gained additional armor, while others gained other additional bonuses.

http://web.archive.org/web/20070518215136/http://www.thottbot.com:80/i30942
Manimal's Cinch#30942 has it's oldest version set at 348 armor, however the date is 2007, may 18th which means 3 days post 2.1. Therefor we **know** that this item had lower armor or lower stats(Most likely lower armor) based on https://github.com/Atlantiss/NetherwingBugtracker/issues/3111 I'd propose a new value of 348 * 0.815 ((318/390=~0.815)) = 284

You may want to just nerf stats instead(Something based on https://github.com/Atlantiss/NetherwingBugtracker/issues/3114 ?), this was just an easier way to get a good estimate

**Current behaviour**:
348 Armor

**Expected behaviour**: 
284 Armor

**Server Revision**: 
2364

**Comment by aresbrutus** [comment]
http://web.archive.org/web/20070312203303/http://www.thottbot.com:80/i30942

We got the correct stats already.
