### ISSUE TITLE
[Item]A'dal's Signet of Defense should have 299 armor rather than 367(Changes in 2.1)

### ISSUE THREAD

**Issue by Tenoutoften** [Atlantiss/NetherwingBugtracker#3113]
**Description**: 
https://www.wowhead.com/item=28792/adals-signet-of-defense is a reward from the magtheridon head-quest.

2007, june 2nd thottbot(Oldest of the archives I use) got this item listed at 367 armor(This is also current NW value)

http://wowwiki.wikia.com/wiki/Patch_2.1.0
>Armor: All Burning Crusade items that spent part of their budget on increased armor have been re-evaluated. Some gained additional armor, while others gained other additional bonuses.

Ill apply the same forumla here as I did in https://github.com/Atlantiss/NetherwingBugtracker/issues/3112

367 * 0.815 = 299

**Current behaviour**:
367 armor

**Expected behaviour**: 
299 armor

**Server Revision**: 
2364

**Comment by aresbrutus** [comment]
Head got added in 2.1, it is not available before.
