### ISSUE TITLE
[Item]Verdant Gloves#30943 should have 23 strength instead of 26 strength(Changes in 2.1)

### ISSUE THREAD

**Issue by Tenoutoften** [Atlantiss/NetherwingBugtracker#3114]
**Description**: 
Verdant Gloves#30943 should have provided stats for 2.0
http://web.archive.org/web/20070407075954/http://www.thottbot.com:80/i30943

**Current behaviour**:
Verdant Gloves#30943 currently got 26 strength instead of 23strength

**Expected behaviour**: 
26 strength instead of 23strength

**Server Revision**: 
2364

**Comment by aresbrutus** [comment]
Fixed in rev `Phoebe`
