### ISSUE TITLE
[Item]Mystical Skyfire Diamond 2.0

### ISSUE THREAD

**Issue by killablink** [Atlantiss/NetherwingBugtracker#3115]
**Description**: https://web.archive.org/web/20070227063520/http://www.wowhead.com:80/?item=25893

**Current behaviour**: Currently giving haste rating

**Expected behaviour**: Should be instant cast if we go 2.0. On patch 2.1 the proc chance increased to 5% and halves cast time
**Server Revision**:

**Comment by killablink** [comment]
Also, the buff duration is 10 seconds instead of 6 seconds

**Comment by killablink** [comment]
Also, there is no internal cooldown for the gem on patch 2.0

**Comment by Manaci** [comment]
Irrelevant now

**Comment by Manaci** [comment]
Reopened for future usage

**Comment by Godmatik** [comment]
Not using 2.0 stats/procs for items any longer - closing
