### ISSUE TITLE
[Item]Lieutenant's Signet of Lordaeron#28211 should have 110 armor rather than 143(Changes in 2.1)

### ISSUE THREAD

**Issue by Tenoutoften** [Atlantiss/NetherwingBugtracker#3116]
**Description**: 
http://web.archive.org/web/20070410210230/http://www.thottbot.com:80/i28211
[Item]Lieutenant's Signet of Lordaeron#28211 should have 110 armor rather than 143(Changes in 2.1)

**Current behaviour**:
143 armor

**Expected behaviour**: 
110 armor

**Server Revision**: 
2364

**Comment by aresbrutus** [comment]
Fixed in rev `Phoebe`
