### ISSUE TITLE
[item]Syrannis' Mystic Sheen#28301 should have 198 armor rather than 234(Changes in 2.1)

### ISSUE THREAD

**Issue by Tenoutoften** [Atlantiss/NetherwingBugtracker#3117]
**Description**: 
http://web.archive.org/web/20070318140517/http://www.thottbot.com:80/i28301
Should have 198 armor, currently got 234 armor

**Current behaviour**:
234 armor

**Expected behaviour**: 
198 armor

**Server Revision**: 
2364

**Comment by aresbrutus** [comment]
Fixed in rev `Phoebe`
