### ISSUE TITLE
Master Loot

### ISSUE THREAD

**Issue by Arnamik12** [Atlantiss/NetherwingBugtracker#3118]
**Description**: 
Master looting has some issues
**Current behaviour**:
Master loot when enabled completely ignored the threshold and makes all items that drop Master looted, even grey trash drops.
**Expected behaviour**: 
Should work like other loot rules, like group loot- applies the looting rule to the threshold and above, but round robin on the items below threshold 
**Server Revision**: 
2364

**Comment by Easyfraggy** [comment]
You say it has - some - issues - what are the other ones?

**Comment by Argonn** [comment]
This is really annoying, I now have to have twice the bag space to raid as ML.
Besides that, the ML is not able to set the threshold if he's not the raid master.

**Comment by Godmatik** [comment]
Must have been fixed at some point, just tested and threshold works just fine with master looter.

Closing.
