### ISSUE TITLE
Oasis Snapjaw

### ISSUE THREAD

**Issue by Erodraeda** [Atlantiss/NetherwingBugtracker#312]
[//]: # (Enclose links to things related to the bug using http://wowhead.com or any other TBC database.)
[//]: # (You can use screenshot ingame to visual the issue.)
[//]: # (Write your tickets according to the format:)
[//]: # ([Quest][Azuremyst Isle] Red Snapper - Very Tasty!)
[//]: # ([NPC] Magistrix Erona)
[//]: # ([Spell][Mage] Fireball)
[//]: # ([Npc][Drop] Ghostclaw Lynx)
[//]: # ([Web] Armory doesnt work)

**Description**: 
Oasis Snapjaws, ID 3461. Their loot table isn't disappearing after looting, leaving an empty slot, preventing from skinning.
![screenshot_487](https://user-images.githubusercontent.com/40346279/45936116-3d059180-bf89-11e8-9c47-abcf8f03f3d4.png)
Edit: Actually happening with different mobs in The Barrens.
**Current behaviour**:
Loot table isn't disappearing
**Expected behaviour**: 
Should disappear after you loot it
**Server Revision**:

**Comment by Easyfraggy** [comment]
Possibly related to you being in a party causing quest item to block the loot window somehow.

**Comment by Evolvee** [comment]
Its most likely because there is a loot for some other party member.

**Comment by The14me** [comment]
Killed like 100,never happen to me.Please re-open if happen again.
