### ISSUE TITLE
The Great Moongraze Hunt part 1 and part 2.

### ISSUE THREAD

**Issue by Frankenberryberry** [Atlantiss/NetherwingBugtracker#3120]
[//]: # (https://www.wowhead.com/quest=9454/the-great-moongraze-hunt and followup https://www.wowhead.com/quest=10324/the-great-moongraze-hunt)
[//]: # ([Quest][Azuremyst Isle] The Great Moongraze Hunt)

**Description**: 

**Current behaviour**:
In both quests there is a bit of RP text where you can ask Acteon (the questgiver) "Acteon, where is the best area to hunt for moongraze stags?" OR "Acteon, where is the best area to hunt for moongraze bucks?" (in the followup quest). When playing a hunter he doesn't give you an answer but instead shows you the hunter trainer list of spells and skills. I have only tested this as a hunter. It might be different with a different non-hunter class.

**Expected behaviour**: 
Sadly I don't know the correct behavior but I assume he is going to answer you question with some RP-text.

**Server Revision**:

**Comment by Tenoutoften** [comment]
I can add that this was in on Felmyst so they probably had some evidence for it, I'll come back if I discover something

**Comment by Godmatik** [comment]
Rev 4015 - no longer an issue.
When asking him where the Moongraze are as a hunter, he properly gives the RP text response.

![nbnbbvn](https://github.com/user-attachments/assets/c255b985-9188-41d6-8c62-226e38e96753)
