### ISSUE TITLE
[Item]The Nexus Key#29988 from Kael'Thas should have 0 spelldamage in 2.0(Changes in 2.1)

### ISSUE THREAD

**Issue by Tenoutoften** [Atlantiss/NetherwingBugtracker#3121]
**Description**: 
I personally think this isn't a fair change since most/all other items from Kael'thas can't be found in 2.0 state.
http://web.archive.org/web/20070513093427/http://www.thottbot.com:80/i29988

**Current behaviour**:
Nw stats:
76 stam
52 int
51 spell crit rating
236 spell damage

**Expected behaviour**: 
66 stam
46 int
42 spell crit

**Server Revision**: 
2364

**Comment by ircfelix** [comment]
Does it really make sense fixing this? I mean guilds will go SSC and then TK, and as soon as both is cleared, t6 should open.

**Comment by Easyfraggy** [comment]
I don't think that t6 will open the same day someone beats the two - we would like to give the chance for other guilds that are progressing these fights to beat it prenerf before updating the items to 2.1. Vashj/TK also have the vials implemented atm so it takes a certain amount of weeks before you can attune a full raid. (also undecided how vials will be handled in the end).

**Comment by Tenoutoften** [comment]
Kael'thas loot has been decided to be 2.1 since several items lack their 2.0 information and NW wont do custom nerfs on these
