### ISSUE TITLE
[Hunter][Pets][Karazhan] Pet movement on Nightbane

### ISSUE THREAD

**Issue by sifiuocz** [Atlantiss/NetherwingBugtracker#3123]
**Description**: 
This bug report is about pets during the nightbane encounter.

**Current behaviour**:
Hunter pets go in front of Nightbane instead of at his back very often. This may be due to his large hitbox.

**Expected behaviour**: 
Every Smouldering Breath my pet dies and I cant do anything about it since the pet always goes in front of the boss.

**Server Revision**: 
2364

**Comment by Noxvice** [comment]
This is not just a kara issue, also happends in HC and other places where a mob is moved around after combat is started. 

Seems like the initial attack order will make pet go behind mob, but after it has entered combat it will not move behind the mob by itself if said mob is moved.

**Comment by Easyfraggy** [comment]
Need evidence that pets should continually move behind their target after being sent the first time.

**Comment by sifiuocz** [comment]
https://youtu.be/0bZi5KWON38?t=70
In this video you can see pets' behaviour. They move to those Shadowsword Berserkers and position themselves in a semicircle behind the mobs wherever it is the closest to the hunters. You can see the pets reposition themselves instantaneously at 1:25 so they are in the semicircle behind the mob.

This doesn't happen on the server. Pets move instantaneously at the back of the mobs (exactly 180 degrees from the point the mob is facing).

On Nightbane the pet positioning is messed up. They position themselves in front of the boss instead of at the back.

**Comment by networm555** [comment]
https://github.com/Atlantiss/NetherwingBugtracker/issues/3763. Can confirm. Should be fixed with high-prio. Gamebreaking for hunters.

**Comment by Noxvice** [comment]
http://wowwiki.wikia.com/wiki/Patch_2.3.0

I know it's wow Wikia, but under the general thing:
Pets will try to get behind their targets when engaging in melee combat.

**Comment by tjukoela** [comment]
bump

**Comment by Manaci** [comment]
Fixed
