### ISSUE TITLE
[Spell] - Aspect of the wild spams combat log

### ISSUE THREAD

**Issue by Bleachlol** [Atlantiss/NetherwingBugtracker#3124]
**Description**: 
Was taming a few pets for my hunter and noticed how aspect of the wild spams combat log. 
**Current behaviour**:
When clicked and I have the aspect on me, max rank and rank 2 of the aspect spams my combat log, rank 1 is fine tho. 
Combat log: https://imgur.com/a/DjuR0Vk

**Expected behaviour**: 
When activated, the buff should only **<Name> gains aspect of the wild** once. and not spam combat, like rank 1 of aspect of the wild 
**Server Revision**: 
2364

**Comment by Manaci** [comment]
Fixed
