### ISSUE TITLE
[NPC] [Script] [Karazhan] Nightbanes Threat-Reset (Ground -> Air)

### ISSUE THREAD

**Issue by Drayo** [Atlantiss/NetherwingBugtracker#3125]
[//]: # (Enclose links to things related to the bug using http://wowhead.com or any other TBC database.)
[//]: # (You can use screenshot ingame to visual the issue.)
[//]: # (Write your tickets according to the format:)
[//]: # ([Quest][Azuremyst Isle] Red Snapper - Very Tasty!)
[//]: # ([NPC] Magistrix Erona)
[//]: # ([Spell][Mage] Fireball)
[//]: # ([Npc][Drop] Ghostclaw Lynx)
[//]: # ([Web] Armory doesnt work)
[//]: # (To find server revision type `.server info` command in the game chat.)

**Description**: 

I think Nightbane has issues with his aggro resets.

**Current behaviour**:

Nightbane currently cast Smoking Blast only on the main Tank, making this fight easier than it should be.

**Expected behaviour**: 

He should cast it on the player with the highest threat. This seems to be working, however, **it looks like he does not properly reset his aggro table when he transitions into the air phase**, thus casting it on the tank every time.

One time our tank died and he went for a mage until he also died (about 5 blasts) this also indicates that he does not reset threat properly because the mage did not touch him at all during the air-phase.

**Server Revision**:  2366

**Comment by Drayo** [comment]
On our last kill he only used Smoking Blast on the tank once again. No MD was used during air phase and healers did not get hit a single time, even though they should be the prime target due to healing threat.

One thing I'd like to add though, it seems like he is consistently not in LoS while flying making it nearly impossible to redirect his aggro during the flight phase and thus "tank" him. If Smoking Blast is cast on other players aside from the MT again, this should be addressed because he would be insanely annoying and awkward if you can't control his aggro during flight phase due to not being able to hit him.

**Comment by Drayo** [comment]
- This is still an issue on Karazhan. Smoking Blast is always cast on the tank, and there are LOS issues while Nightbane is in the Air.

https://www.youtube.com/watch?v=mPSXJcIRZ18

This video shows Nightbane casting Smoking Blast almost exclusively on the healers. You can also see the Warlock cast Drain Life and Shadow Bolts at Nightbane during his flight Phase.

**This bug makes the fight significantly easier than it should be.**

**Comment by Wolffenstein** [comment]
Fixed in rev 3834.
