### ISSUE TITLE
[GOBJECT] Extra mailbox in Undercity

### ISSUE THREAD

**Issue by ttghnw** [Atlantiss/NetherwingBugtracker#3126]
**Description**: 
An extra mailbox is near the auctioneers in UC

**Expected behaviour**: 
Should only be the one on the upper tier near the bank and inn
![wowscrnshot_112918_041301](https://user-images.githubusercontent.com/43508698/49198941-7d203080-f38d-11e8-90fa-66c4ad977e02.jpg)
.
**Server Revision**:

**Comment by ahlens** [comment]
Leave it! I hate running to those mailboxes :P

**Comment by Evolvee** [comment]
Do we know this for sure or are we basing it on prior private server experience only?

**Comment by Evolvee** [comment]
https://wow.gamepedia.com/Undercity_points_of_interest

**Comment by Shanghi** [comment]
These shouldn't exist. That map is from later after they added about 9999999999 mailboxes everywhere. The way they were placed is also unacceptable!
![image](https://user-images.githubusercontent.com/2672633/49240922-6650fc80-f3d4-11e8-8d28-0a7bd32463b0.png)

https://www.youtube.com/watch?v=zmWyUfdgUoc#t=23s
One would have been visible at:
![image](https://user-images.githubusercontent.com/2672633/49240364-00b04080-f3d3-11e8-8771-3df15589d731.png)

Object: 177044
IDs to remove: 2, 3, 4, 5

**Comment by ttghnw** [comment]
Yup the AH - Mailbox routine up-down quite "autistically rememberable" <3

**Comment by Evolvee** [comment]
rev 2468
