### ISSUE TITLE
[Raid] [Karazhan] Lord Crispin Ference on Moroes

### ISSUE THREAD

**Issue by Dollywog** [Atlantiss/NetherwingBugtracker#3127]
[//]: # (Enclose links to things related to the bug using http://wowhead.com or any other TBC database.)
[//]: # (You can use screenshot ingame to visual the issue.)
[//]: # (Write your tickets according to the format:)
[//]: # ([Quest][Azuremyst Isle] Red Snapper - Very Tasty!)
[//]: # ([NPC] Magistrix Erona)
[//]: # ([Spell][Mage] Fireball)
[//]: # ([Npc][Drop] Ghostclaw Lynx)
[//]: # ([Web] Armory doesnt work)
[//]: # (To find server revision type `.server info` command in the game chat.)

**Description**:  This add when reaching around 35% health spams his Shield Wall ability seemingly endlessly.  

**Current behaviour**:   When getting to low health, this add on the fight could be heard and seen constantly spamming his Shield Wall animation & sound effect.  It appeared as though if this was the case he would constantly have 75% damage reduction and you could not wait out the duration.

**Expected behaviour**:  NPC should just use ability once while low HP and it should have a max duration, or if no max duration, at least not spam the ability.

**Comment by zauru7** [comment]
Saw this yesterday as well, don't have any screenshot but you could hear the sound of him spamming his shield wall

**Comment by Bleachlol** [comment]
You can see here: https://www.youtube.com/watch?v=PXpjYHkW4gc&t=58s that the mob has Shield Wall when Hobbs is targeting the mob. I'd ***ASSUME*** that the mob casted Shield Wall at 20%. 
1:03 you can see that shield walls falls of the mob until he dies.

**Comment by Wolffenstein** [comment]
Fixed in rev 3427.
