### ISSUE TITLE
[Raid] [Boss] [Karazhan] Moroes Damage

### ISSUE THREAD

**Issue by Dollywog** [Atlantiss/NetherwingBugtracker#3128]
[//]: # (Enclose links to things related to the bug using http://wowhead.com or any other TBC database.)
[//]: # (You can use screenshot ingame to visual the issue.)
[//]: # (Write your tickets according to the format:)
[//]: # ([Quest][Azuremyst Isle] Red Snapper - Very Tasty!)
[//]: # ([NPC] Magistrix Erona)
[//]: # ([Spell][Mage] Fireball)
[//]: # ([Npc][Drop] Ghostclaw Lynx)
[//]: # ([Web] Armory doesnt work)
[//]: # (To find server revision type `.server info` command in the game chat.)

**Description**: Moroes melee damage seems slightly overtuned, was landing 7000-9000 crushing hits on 20000 armor [65% reduction] feral druid in full Season 1.  When he had the Blessing of Might this could go as high as 11000.

**Current behaviour**:  Impression that melee damage may be overtuned.  Also,  I think Moroes is bleed immune but shouldn't be.

**Expected behaviour**:  https://youtu.be/rKS0m34rn00?t=84
Have been looking into this further, these protection warriors in 2006 get crushed twice as they run away from Moroes with their backs to him and eat 2 crushings for 3600/4500 ; Demo Shout not on boss. 
 I know warriors receive +16% damage reduction vs druid , but you can clearly see the MT handles him hitting around 700-1800 on plate blues (Still end up wiping though).

https://youtu.be/wJUB_9j4pH0?t=132
This time from a feral perspective, not great quality and a lot of text on the screen but at this moment you can see the feral gets Gouge aggro and eats a melee swing for ~10% HP.  The protection warrior MT you can see his damage numbers on the Target-of-Target frame range from around 600-1800 again.  When Moroes enrages this appears to increase to around 30% of MT HP on full hit but difficult to confirm.

https://www.ironsongtribe.com/Thread-Karazhan-Boss-Encounters
Note in Moroes section they estimate 1600-2500 on plate. 
Also note final line, Moroes himself is not immune to bleeds.

**Server Revision**:  Will be doing some tests later with a protection warrior when I have the time, but initial impression is damage too high / can be tested by GM characters in plate blues.

**Comment by Easyfraggy** [comment]
There is no data readily available on the prenerf raids/dungeons that you will find on any videos - simply noone recorded early enough. Almost all of kara - SSC and TK was nerfed within the first week of the instance existing on retail.

Moroes is working as intended.

**Comment by Dollywog** [comment]
Where do you get the Values from if you can't find the evidence anywhere?

**Comment by Easyfraggy** [comment]
I didn't say we can't find the data anywhere - I said that you as regular guy using google and youtube can't find it.

We have sniffs and tons of old now deleted posts/comments/videos and general data from the very early days of TBC. A lot of the CC research was also shared with us.

**Comment by Joaxx** [comment]
I think the community would be interested in seeing some of that research, please share it as it will almost certainly aid in finding further evidence.

**Comment by Easyfraggy** [comment]
We are not going to be releasing any of our research because we don't want to be helping our rivals. Maybe some time in the future when all is said and done.

If you think something is overtuned please do report it so we can check it out - I did check Moroes after this post.
