### ISSUE TITLE
The Cursed Crew

### ISSUE THREAD

**Issue by Frankenberryberry** [Atlantiss/NetherwingBugtracker#3131]
**Description**: 
NPC's and pet's can't leave the ship so quest becomes impossible.

**Current behaviour**:
https://imgur.com/a/SQOXjKa

The exit from the ship I highlighted is bugged. Currently NPC's can't get out of the ship which means they just bug out if you pull them.

**Expected behaviour**: 
NPC's should be able to leave the ship so we can complete the quest. Sorry I could not find a video of this from before 2008 =(

**Server Revision**:

**Comment by Evolvee** [comment]
bad mmaps around the ships

**Comment by Manaci** [comment]
Fixed I would assume
