### ISSUE TITLE
[NPC][Auchenai Crypts] Unliving Cleric, Unliving Sorcerer

### ISSUE THREAD

**Issue by Dusky1** [Atlantiss/NetherwingBugtracker#3132]
**Description**:This guys are summoned by Auchenai Vindicators in Auchenai Crypts. I was doin Heroic mode.

**Current behaviour**: They cast (Unliving Cleric) Heal and (Unliving Sorcerer) Fireball abilities that cannot be interrupted (Kick im my case, but i guess other interrupts also doesnt work).

**Expected behaviour**: Should be possible to interrupt those spells.

**Server Revision**: 
2370

**Comment by Easyfraggy** [comment]
Got some proof of this?

**Comment by Easyfraggy** [comment]
Need some timestamps - but yeah seems like you are right.

**Comment by Dusky1** [comment]
https://www.youtube.com/watch?v=F_5q8pbVIT4#t=1m51s you can look at this one. Its normal but on NW now you cant interrupt even in Normal mode. Hero shouldnt be different since they were CC able in Hero mode.

**Comment by Evolvee** [comment]
rev 2468
