### ISSUE TITLE
Seal of Vengeance crits do not grant Vengeance stacks

### ISSUE THREAD

**Issue by Felynda** [Atlantiss/NetherwingBugtracker#3133]
**Description**: 
When using Seal of Vengeance I attack dummy. When it crits it doesn't give a proc of vengeance (Ret pala talent). U are supposed to get a stack when you crit (read talent description)
**Current behaviour**:
When Seal of Vengeance crits it doesn't give a proc of vengeance (Ret pala talent)
**Expected behaviour**: 
When you crit you get a stack.

ty for reading

**Comment by Tereneckla** [comment]
Fixed
