### ISSUE TITLE
[Item]Gladiator's Refuge set#685/709/720 should have 4-bonus spell#23218 instead of #46834 (Changes in 2.4)

### ISSUE THREAD

**Issue by Tenoutoften** [Atlantiss/NetherwingBugtracker#3135]
**Description**: 
These sets:
* [Gladiator's Refuge, set#685](https://www.wowhead.com/item-set=685/gladiators-refuge)
* [Merciless Gladiator's Refuge, set#709](https://www.wowhead.com/item-set=709/merciless-gladiators-refuge)
* [Vengeful gladiator's Refuge, set#720](https://www.wowhead.com/item-set=720/vengeful-gladiators-refuge)

Should use [[Spell]Shapeshift Movement Speed#23218](https://www.wowhead.com/spell=23218/shapeshift-movement-speed) as 4-set bonus rather than [[Spell]Restoration Regrowth Bonus#46834](https://www.wowhead.com/spell=46834/restoration-regrowth-bonus)

In other words, the same 4-set bonus as the feral set,[Gladiator's Sanctuary, set#584](https://www.wowhead.com/item-set=584/gladiators-sanctuary)

----
List of Patch dates can be found **[here](http://wowwiki.wikia.com/wiki/Patches/2.x)**

**[Patch 2.4.0](http://wowwiki.wikia.com/wiki/Patch_2.4.0)**
>Druid Restoration PvP Sets: The bonus movement speed for Bear, Cat, and Travel Form has been removed and replaced with a new bonus to Regrowth.

[[Spell]Shapeshift Movement Speed#23218](https://www.wowhead.com/spell=23218/shapeshift-movement-speed) last seen on: 2008 february 25th
http://web.archive.org/web/20080225064225/http://thottbot.com:80/i31377

First report of regrowth bonus: 2008 march 27th
http://web.archive.org/web/20080327154333/http://thottbot.com:80/i31377

----

**Current behaviour**:
These sets currently utilize the 2.4 patch set bonus [[Spell]Restoration Regrowth Bonus#46834](https://www.wowhead.com/spell=46834/restoration-regrowth-bonus)

**Expected behaviour**: 
Expect set#[685](https://www.wowhead.com/item-set=685/gladiators-refuge)/[709](https://www.wowhead.com/item-set=709/merciless-gladiators-refuge)/[720](https://www.wowhead.com/item-set=720/vengeful-gladiators-refuge) to use [[Spell]Shapeshift Movement Speed#23218](https://www.wowhead.com/spell=23218/shapeshift-movement-speed) until [Patch 2.4.0](http://wowwiki.wikia.com/wiki/Patch_2.4.0)

**Server Revision**: 
2370

**Comment by aresbrutus** [comment]
Not possible due to client limitation.

**Comment by Tenoutoften** [comment]
This is possible because the spell is in the game. What isn't possible is changing the text itself to display the different spellID being used, for that you would need an addon.
