### ISSUE TITLE
[Spell][Warrior] Whirlwind - hitting more than 4 targets

### ISSUE THREAD

**Issue by idsss** [Atlantiss/NetherwingBugtracker#3138]
**Description**:
![wowscrnshot_112918_205226](https://user-images.githubusercontent.com/43757915/49248506-29a7f400-f41a-11e8-8e60-072140a60b0a.jpg)

**Current behaviour**: [Whirlwind](https://www.wowhead.com/spell=1680/whirlwind) can hit more than 4 targets

**Expected behaviour**: should only hit 4
![wowscrnshot_112918_210403](https://user-images.githubusercontent.com/43757915/49248632-7ee40580-f41a-11e8-9229-b0c7b5b5fd9d.jpg)

**Server Revision**: 2370

**Comment by Easyfraggy** [comment]
Confirmed!

**Comment by Wolffenstein** [comment]
Fixed in rev 2379.

**Comment by Bleachlol** [comment]
Seems like this was fixed, in the regards of a 2H, found this today: https://imgur.com/a/7rksnny where it seems like the main hand or off hand (using duel wield) is still hitting more than 4 targets with Whirlwind.
