### ISSUE TITLE
[Item]Gladiator's Wildhide set#585/716/722 should have 4-bonus spell#23218 instead of #46832 (Changes in 2.4)

### ISSUE THREAD

**Issue by Tenoutoften** [Atlantiss/NetherwingBugtracker#3139]
**Description**: 
These sets:
* [Gladiator's Wildhide, set#585](https://www.wowhead.com/item-set=585/gladiators-wildhide)
* [Merciless Gladiator's Wildhide, set#716](https://www.wowhead.com/item-set=716/merciless-gladiators-wildhide)
* [Vengeful gladiator's Wildhide, set#722](https://www.wowhead.com/item-set=722/vengeful-gladiators-wildhide)

Should use [[Spell]Shapeshift Movement Speed#23218](https://www.wowhead.com/spell=23218/shapeshift-movement-speed) as 4-set bonus rather than [[Spell]Moonkin Starfire Bonus#46832](https://db.excalibur.ws/?spell=46832)

In other words, the same 4-set bonus as the feral set,[Gladiator's Sanctuary, set#584](https://www.wowhead.com/item-set=584/gladiators-sanctuary)

----

List of Patch dates can be found **[here](http://wowwiki.wikia.com/wiki/Patches/2.x)**

**[Patch 2.4.0](http://wowwiki.wikia.com/wiki/Patch_2.4.0)**
>Druid Balance PvP Sets: The bonus movement speed for Bear, Cat, and Travel Form has been removed and replaced with a new bonus to Wrath and Starfire.

[[Spell]Shapeshift Movement Speed#23218](https://www.wowhead.com/spell=23218/shapeshift-movement-speed) last seen on: 2008 March 17th
http://web.archive.org/web/20080317085722/http://thottbot.com:80/i32056

[[Spell]Moonkin Starfire Bonus#46832](https://db.excalibur.ws/?spell=46832)
 first seen on:: 2008 april 17th
http://web.archive.org/web/20080417124649/http://thottbot.com:80/i32056

----

**Current behaviour**:
These sets currently utilize the 2.4 patch set bonus [[Spell]Moonkin Starfire Bonus#46832](https://db.excalibur.ws/?spell=46832)

**Expected behaviour**: 
Expect set#[585](https://www.wowhead.com/item-set=585/gladiators-wildhide)/[716](https://www.wowhead.com/item-set=716/merciless-gladiators-wildhide)/[722](https://www.wowhead.com/item-set=722/vengeful-gladiators-wildhide) to use [[Spell]Shapeshift Movement Speed#23218](https://www.wowhead.com/spell=23218/shapeshift-movement-speed) until [Patch 2.4.0](http://wowwiki.wikia.com/wiki/Patch_2.4.0)

**Server Revision**: 
2370

**Comment by aresbrutus** [comment]
Not possible due to client limitation.

**Comment by Tenoutoften** [comment]
This is possible because the spell is in the game. What isn't possible is changing the text itself to display the different spellID being used, for that you would need an addon.
