### ISSUE TITLE
[pet][Warlock] Phase shift.

### ISSUE THREAD

**Issue by Cptnlobbe** [Atlantiss/NetherwingBugtracker#3140]
**Description**: 
During phase shift the Imp is unable to be attacked by any damage,
**Current behaviour**:
Gets attacked from ground/chain damage.
**Expected behaviour**: 
Immortal.
**Server Revision**:

**Comment by Easyfraggy** [comment]
maybe same issue as the aoe hitting non pvp targets?

**Comment by Wolffenstein** [comment]
Fixed in rev 3078.
