### ISSUE TITLE
[Item]Lightfathom Scepter#30108 is currently in 2.1 state, provided values for 2.0

### ISSUE THREAD

**Issue by Tenoutoften** [Atlantiss/NetherwingBugtracker#3141]
**Description**: 
NW 2.1:
![a4ae92fe76f06c16d1e6a3ede26f3135](https://user-images.githubusercontent.com/34839199/49256962-ff156580-f430-11e8-8bdb-df16eba3841b.png)

2.0
![2150bf095355de623bdbca9cdf609181](https://user-images.githubusercontent.com/34839199/49258763-eb6cfd80-f436-11e8-8f1e-ae9f6eaa7905.png)
https://web.archive.org/web/20070519083345/http://wow.allakhazam.com:80/db/item.html?witem=30108

**Expected behaviour**: 
Use allakhazam values, 2.0

**Server Revision**: 
2370

**Comment by aresbrutus** [comment]
Fixed in rev `Phoebe`

**Comment by Tenoutoften** [comment]
This item receives an additional update in patch 2.2
https://web.archive.org/web/20071001225940/http://wow.allakhazam.com:80/db/item.html?witem=30108
![03a4e1bbc65141260d96803855b5450c](https://user-images.githubusercontent.com/34839199/49346439-c8d72080-f692-11e8-9a37-526f4ffb46f0.png)
