### ISSUE TITLE
[Spell][Warlock] Ritual of Summoning

### ISSUE THREAD

**Issue by itsjojotbh** [Atlantiss/NetherwingBugtracker#3142]
[//]: # (Enclose links to things related to the bug using http://wowhead.com or any other TBC database.)
[//]: # (You can use screenshot ingame to visual the issue.)
[//]: # (Write your tickets according to the format:)
[//]: # ([Quest][Azuremyst Isle] Red Snapper - Very Tasty!)
[//]: # ([NPC] Magistrix Erona)
[//]: # ([Spell][Mage] Fireball)
[//]: # ([Npc][Drop] Ghostclaw Lynx)
[//]: # ([Web] Armory doesnt work)
[//]: # (To find server revision type `.server info` command in the game chat.)

**Description**: 
Ritual of Summoning is not working according to its 2.0 state
**Current behaviour**:
Players who are not in the same instance as the summoning Warlock can be summoned into the instance
**Expected behaviour**: 
You should only be able to summon other players who are in the same instance as the Warlock while summoning inside an instance i.e. not able to summon into instances. This functionality was introduced in patch 2.4.0.
Evidence: [http://wowwiki.wikia.com/wiki/Ritual_of_Summoning#Patch_changes](url)
Patch 2.4.0 (25-Mar-2008): Ritual of Summoning can be used to summon players into instances if they meet the instance requirements.
**Server Revision**: 
2370

**Comment by Easyfraggy** [comment]
Not sure if we want to change this - spells and mechanics are 2.4.3

**Comment by Wolffenstein** [comment]
Will not be changed as Easy stated.
