### ISSUE TITLE
[Dungeon][Mechanar] Jagged Blue / Red Crystal showing on loot for everyone in the party

### ISSUE THREAD

**Issue by feuerkind** [Atlantiss/NetherwingBugtracker#3145]
**Description**: 
Both Jagged Blue Crystal and Jagged Red Crystal from the 2 Minibosses at the start can be seen by group members who weren't assigned that drop showing a "That item is still being rolled for." error.
**Current behaviour**:
It has nothing to do with the green item dropping there, had the same issue on the first one without green drop, just didn't get to Screenshot before it got looted.
![wowscrnshot_112918_040705](https://user-images.githubusercontent.com/13179578/49259171-8f0add80-f438-11e8-92d4-3d5b1f433189.jpg)
**Expected behaviour**: (NEEDS RESEARCH)
Only the person who can actually loot the Crystal should be able to see it on the corpse.
**Server Revision**: 
2364 (?)

**Comment by Tenoutoften** [comment]
This is a global thing you can see the loot other people in the party got the right to loot, without being able to loot it yourself

**Comment by feuerkind** [comment]
https://www.twitch.tv/bukkage/clip/PlacidImportantChickenHoneyBadger?filter=clips&range=7d&sort=time
probably related
