### ISSUE TITLE
[Item] Serpent Spine Longbow currently in 2.1 state, provided values for 2.0

### ISSUE THREAD

**Issue by jackedgamer** [Atlantiss/NetherwingBugtracker#3146]
https://gyazo.com/37458689887ff050e0b8a74c45de60e8 - 2.1 stats
https://gyazo.com/214f7f50744d162d66eca963f17710c5 - 2.0 stats

2.0 bow did not have crit on.

**Comment by jackedgamer** [comment]
> Are you claiming thottbot stats are incorrect? If your stats are correct this would be a nice buff to hunters

exactly

**Comment by Tenoutoften** [comment]
Could you post the exact link to the website displaying these stats?

**Comment by aresbrutus** [comment]
I need a source for this, for now it looks like how it should be on NW.

**Comment by Saben65** [comment]
[wowwiki May 8, 2007](http://wowwiki.wikia.com/wiki/Serpent_Spine_Longbow?oldid=629855)
[wowwiki May 18, 2007](http://wowwiki.wikia.com/wiki/Serpent_Spine_Longbow?oldid=649395)

Not sure what exactly happened between those 10 days or where they got the numbers. But the one from May 8 also has crit on it.

[Wowhead comment](https://www.wowhead.com/item=30105/serpent-spine-longbow#comments:id=79231) from 2.0.12 (May 7, 2007) though

> Nice Bow with a good speed and impact damage. Personally, I would love to see something similar w/ +Agi/Int +Hit, +RAP **instead of just AP**.
>
>It Would make it more clear that its a hunter Bow. But in its current state it can be used, and applied to anyone that can use bows. Granted, as im leveling my Rogue Alt. I'd probably pick up the Steelhawk for him solely due to the fact of hit Rating on it.
>
>None the Less, nice bow

**Comment by Manaci** [comment]
Irrelevant now
