### ISSUE TITLE
[Raid][Karazhan] Spectral Performer's Spotlight

### ISSUE THREAD

**Issue by feuerkind** [Atlantiss/NetherwingBugtracker#3147]
[//]: # (Enclose links to things related to the bug using http://wowhead.com or any other TBC database.)
[//]: # (You can use screenshot ingame to visual the issue.)
[//]: # (Write your tickets according to the format:)
[//]: # ([Quest][Azuremyst Isle] Red Snapper - Very Tasty!)
[//]: # ([NPC] Magistrix Erona)
[//]: # ([Spell][Mage] Fireball)
[//]: # ([Npc][Drop] Ghostclaw Lynx)
[//]: # ([Web] Armory doesnt work)
[//]: # (To find server revision type `.server info` command in the game chat.)

**Description**: 
These trashmobs before opera do an area buff called "Spotlight" that increases damage done on anyone in it. This buff currently only affects NPCs while it should also work on players.
**Current behaviour**:
![wowscrnshot_112418_231201](https://user-images.githubusercontent.com/13179578/49259468-c62dbe80-f439-11e8-828a-d7c47026ddaf.jpg)
**Expected behaviour**: 
"A spotlight shines down near them that increases the damage output of anyone in it. Pull the monsters out of the spotlight, and stand in it yourself."
https://www.wowhead.com/npc=16473/spectral-performer#comments
**Server Revision**: 
whatever it was on 24/11/2018

**Comment by Evolvee** [comment]
It should not affect players on 2.0 afaik.

**Comment by Easyfraggy** [comment]
I think wolf was the one saying that it doesn't buff players in 2.0 from the 2.0 spell dbc.

**Comment by towneh** [comment]
Only trustworthy comments I can find on this is from http://www.tentonhammer.com/guides/karazhan-guide-opera-halls-opera-event which states: "...they use Spotlight to increase the damage done by anyone in the light by 20%..." which is dated during the 2.1 patch. I'm unable to find *any* comments regarding official or unofficial patch notes to say that the behaviour of this spell (32214) has changed.

This comment on https://www.wowhead.com/npc=16473/spectral-performer#comments:id=122786 explains:
"A spotlight shines down near them that increases the damage output of anyone in it. Pull the monsters out of the spotlight, and stand in it yourself." again this is during 2.1.3.

In absence of any information regarding the fact that spotlight was changed, can we now argue the case for *not* making it behave as 2.1, what evidence do we have that says it *shouldn't* provide a beneficial debuff to players as well?

**Comment by RealZwox** [comment]
By Sylvanes (2,143 – 14·30) on 2007/03/21 (Patch 2.0.10) |   |  
-- | -- | --


Seem to Sleep the 2nd highest aggro (Dispellable Magic), **also believe _you_ get a buff after it is dispelled called Spotlight that increases damage done by 20% lasts roughly 15 seconds.** When they die they do around 3k - 4k fire damage AoE.

**Comment by aresbrutus** [comment]
2.1 was when major nerfs happened, so we would require 2.0.x comments. Keep in mind that 2.0.12 might also be during PTR so comments might be talking about that.

**Comment by Wolffenstein** [comment]
Fixed in rev 2374.
