### ISSUE TITLE
Warp Splinter Arcane Volley

### ISSUE THREAD

**Issue by despairr1** [Atlantiss/NetherwingBugtracker#3148]
[//]: # (Enclose links to things related to the bug using http://wowhead.com or any other TBC database.)
[//]: # (You can use screenshot ingame to visual the issue.)
[//]: # (Write your tickets according to the format:)
[//]: # ([Quest][Azuremyst Isle] Red Snapper - Very Tasty!)
[//]: # ([NPC] Magistrix Erona)
[//]: # ([Spell][Mage] Fireball)
[//]: # ([Npc][Drop] Ghostclaw Lynx)
[//]: # ([Web] Armory doesnt work)
[//]: # (To find server revision type `.server info` command in the game chat.)

**Description**: 
Arcane Volley aoe
**Current behaviour**:
Hitting targets all around the room
**Expected behaviour**: 
Only targets facing in front of the boss pre 2.1 
**Server Revision**: 
2370

**Comment by zauru7** [comment]
that only applies if you tank him on the bridge, did you do that?

**Comment by Tenoutoften** [comment]
https://github.com/Atlantiss/NetherwingBugtracker/issues/3022

**Comment by The14me** [comment]
Work just fine
