### ISSUE TITLE
[Raid][Gruul's Lair] Gruul's Shatter interaction with immunites

### ISSUE THREAD

**Issue by feuerkind** [Atlantiss/NetherwingBugtracker#3149]
**Description**: 
Shatter seems to go through immunities (should it in 2.0?) and possibly act like another player for extra shatter damage on nearby players (speculation).
**Current behaviour**:
You cannot see very well if at all. (sorry, we should've prepared recording better!)
In group 5 the mage takes damage while using Iceblock and the Moonkin who is somewhat close to him gets one-shot while using Barkskin. (both characters in crafted gear, so low-ish HP)
Both of them are in the top left corner (check minimap).
https://www.twitch.tv/videos/340190059?t=31m07s
**Expected behaviour**:  (NEEDS RESEARCH)
Found one guide from 2.0 not mentioning immunities at all:
https://www.ownedcore.com/forums/world-of-warcraft/world-of-warcraft-guides/13202-gruul-dragonkiller-strategy-guide.html
And a guide from 2.2 saying that they only remove the active movement slow:
https://forum.twguild.org/index.php?topic=3463.0
**Server Revision**: 
whatever it was 24/11/2018

**Comment by feuerkind** [comment]
https://youtu.be/v8uD8DnlRWI?t=104
Misanthrope swears up and down that this is 2.0. At least you can see a mage not taking damage from Iceblock.

**Comment by feuerkind** [comment]
Might very well just be a reupload.

At this part he uses IB with druid tank close to himself damaging him by 13.4k while still not taking damage himself. If we believe the 2.0 guide that says that damage caps at 9k the theory of iceblock hurting people close might be true.
Mage isn't super close to the druid and there doesn't seem to be anyone else nearby.

https://youtu.be/v8uD8DnlRWI?t=311

**Comment by Saben65** [comment]
I believe this issue is more than a Shatter issue. It seems Ice Block does not negate environment damage at all.

I was able to recreate this by ice blocking by a cooking fire that does damage, and ice blocking. I still took damage. Additionally, earlier today I died to Blaze during Nazan in Heroic Ramparts, even though I was quite sure I had Ice Block on prior to Blaze landing on me. At the time I thought I must have just been mistaken, or accidentally canceled ice block early, but it seems more likely now that it is bugged.

**Comment by ircfelix** [comment]
At the end of this thread there's a link (you may contribute to) with old tbc videos:
https://forum.atlantiss.eu/netherwing/topic/126-quick-how-to-search-and-find-sources-for-bug-reports/

Just search for dungeons or raids and you will most likely find something.

**Comment by zauru7** [comment]
![45324](https://user-images.githubusercontent.com/44526051/49339506-12901e80-f633-11e8-8352-ba2d259dbb03.PNG)
it was hotfixed as a bug in tbc about 1 month after release, shatter damage is not supposed to be avoidable through immunities

**Comment by Easyfraggy** [comment]
So this is working correctly atm?

**Comment by feuerkind** [comment]
I guess we can accept that hotfix to be the intended 2.0 state, so shatter going through immunity is correct.

Still leaves us with the question if immunities increase the damage taken by people nearby (and if that is the case whether they should).

**Comment by Saben65** [comment]
https://www.youtube.com/watch?v=v8uD8DnlRWI&t=5m15s

If you check the combat log in the bottom right, while the mage iceblocks he does shatter damage to people around him.

At  https://www.youtube.com/watch?v=v8uD8DnlRWI&t=6m20s, you can see Naturen, another mage, does damage to Kerp. Naturen is in Iceblock.

Also, Iceblock appears to cause Stoned to miss which would then not apply the shatter damage to the mage (I am assuming the the bug fix was to make it so stoned can't miss).

Another one: https://www.youtube.com/watch?v=v8uD8DnlRWI&t=1m45s

**Comment by Easyfraggy** [comment]
I believe this is already working correctly?

**Comment by Manaci** [comment]
Irrelevant now
