### ISSUE TITLE
[Spell][Faerie Fire] Not Preventing Stealth

### ISSUE THREAD

**Issue by Thugli** [Atlantiss/NetherwingBugtracker#315]
**Description**: 
According to a guild member who is a rogue, faerie fire did not prevent him from stealthing.

**Current behaviour**:
Faerie fire does not prevent rogue stealth (possibly druid stealth as well).

**Expected behaviour**: 
Faerie fire should prevent any form of stealth as long as it is active.

**Server Revision**:

**Comment by Mvtsvraev** [comment]
Confirmed had same issue with Shadowmeld.

**Comment by Wolffenstein** [comment]
Fixed in rev 2147.
