### ISSUE TITLE
[Tooltip][Item] Drums of Battle usable while shapeshifted

### ISSUE THREAD

**Issue by tepex0** [Atlantiss/NetherwingBugtracker#3150]
**Description**: Drums of Battle states it is usable while shapeshifted,  but after they got changed to 2.0 version in revision 2367, it is no longer possible to use them while shapeshifted, except in tree form.

https://i.imgur.com/dHSlC6I.jpg - Trying to use Drums of Battle in bear, cat, and tree form
Bear & cat fail, tree can cast drums.

**Current behaviour**:Drums of Battle tooltip says it is usable while shapeshifted.

**Expected behaviour**: Tooltip should not state that drums are usable while shapeshifted.

**Server Revision**: 2370

**Comment by Evolvee** [comment]
http://wowwiki.wikia.com/wiki/Drums?oldid=583293
![image](https://user-images.githubusercontent.com/1942409/49302243-dfc91780-f4c6-11e8-96a2-24f3aa473193.png)
