### ISSUE TITLE
Druid - Lunar guidance and dreamstate are not giving any bonus stats on the character sheet

### ISSUE THREAD

**Issue by Anselm123** [Atlantiss/NetherwingBugtracker#3152]
![image](https://user-images.githubusercontent.com/36844570/49298612-2a926180-f4be-11e8-9d22-7b3a4b59539a.png)

![image](https://user-images.githubusercontent.com/36844570/49298630-35e58d00-f4be-11e8-8f77-224d0e314702.png)

![image](https://user-images.githubusercontent.com/36844570/49298756-6e856680-f4be-11e8-9e10-de8158abdaaf.png)

![image](https://user-images.githubusercontent.com/36844570/49298770-75ac7480-f4be-11e8-87cd-92c5eeedeedf.png)

**Description**:  Lunar guidance and dreamstate talents aren't  currently showing as giving any healing or spell damage or mp5 on the character sheet as they should.

**Current behaviour**: If i equip an item with int my healing, spell damage and mp5 are not increasing

**Expected behaviour**: These stats should increase

**Server Revision**:

**Comment by Anselm123** [comment]
Ok so I just buffed myself with motw and an int flask and I gained spell damage, healing and mp5

![image](https://user-images.githubusercontent.com/36844570/49299862-08e6a980-f4c1-11e8-916e-159a549d0b15.png)


seems to be working with buffs but not gear

**Comment by Dusky1** [comment]
Pendant of the Violet Eye doesnt have +40 intellect in 2.0 itemization. You can see it on your "Base Stats" table that nothing have changed. Delete your cache pls ;)

**Comment by Anselm123** [comment]
Ah ok that explains it then I just tried with adding an int enchant to a new weapon. Thanks for sorting the confusion :)
