### ISSUE TITLE
[Druid][Spell] Tree of life's bonus healing aura

### ISSUE THREAD

**Issue by Onsty** [Atlantiss/NetherwingBugtracker#3153]
[//]: # (Enclose links to things related to the bug using http://wowhead.com or any other TBC database.)
[//]: # (You can use screenshot ingame to visual the issue.)
[//]: # (Write your tickets according to the format:)
[//]: # ([Quest][Azuremyst Isle] Red Snapper - Very Tasty!)
[//]: # ([NPC] Magistrix Erona)
[//]: # ([Spell][Mage] Fireball)
[//]: # ([Npc][Drop] Ghostclaw Lynx)
[//]: # ([Web] Armory doesnt work)
[//]: # (To find server revision type `.server info` command in the game chat.)

**Description**: 
Tree of life aura increases healing received by 25% of the tree of life's total spirit.

**Current behaviour**:
+Spirit buffs that are received while in tree of life form do not increase healing done.

1st screen: I have 463 spirit without any buffs, which is equivalent to 214 lifebloom ticks.
<a href="https://gyazo.com/5606b73cbb38ec935e28ce304d6feff7"><img src="https://i.gyazo.com/5606b73cbb38ec935e28ce304d6feff7.png" alt="Image from Gyazo" width="472"/></a>

2nd screen: used Scroll of spirit(+30) and botanika trinket(+130), 647 total spirit, and it is still 214 lifebloom ticks.
<a href="https://gyazo.com/2ff7a877167f36e5653fce85d9cfc75d"><img src="https://i.gyazo.com/2ff7a877167f36e5653fce85d9cfc75d.png" alt="Image from Gyazo" width="489.6"/></a>

The other side of this bug that you can use trinket or any other +spirit buffs (or even full spirit gear) while in normal form, then shapeshifting into the tree form and get bonus healing that will continue to work even when the buffs disappear (or gear swithed), until you reshapeshifted.

It seems like the bonus healing (amounting to 25% of the total spirit) is calculatied ones you shapeshifting into the tree of life form, and is not recalculated when you receive any +spirit buff\proc while in form.

**Expected behaviour**: 
Spirit buffs that are received while in tree of life form should increase healing done.

**Server Revision**: 
2370

**Comment by Tereneckla** [comment]
It is working the same way as every buff/hot/dot/debuff.

They snapshot your current stats at the time of application.
