### ISSUE TITLE
[Item] Scroll of Intellect V 

### ISSUE THREAD

**Issue by stinkblaster** [Atlantiss/NetherwingBugtracker#3155]
[//]: # (Enclose links to things related to the bug using http://wowhead.com or any other TBC database.)
[//]: # (You can use screenshot ingame to visual the issue.)
[//]: # (Write your tickets according to the format:)
[//]: # ([Quest][Azuremyst Isle] Red Snapper - Very Tasty!)
[//]: # ([NPC] Magistrix Erona)
[//]: # ([Spell][Mage] Fireball)
[//]: # ([Npc][Drop] Ghostclaw Lynx)
[//]: # ([Web] Armory doesnt work)
[//]: # (To find server revision type `.server info` command in the game chat.)

**Description**: 
Says "That Item is still being rolled for" when it is not something that can be rolled for.
https://www.twitch.tv/bukkage/clip/PlacidImportantChickenHoneyBadger?filter=clips&range=7d&sort=time
**Current behaviour**:
Can't loot item, says still being rolled for.
**Expected behaviour**: 
Should be lootable
**Server Revision**: 
2370

**Comment by feuerkind** [comment]
#3145 probably related
