### ISSUE TITLE
[NPC] ID 22204 Fear Fiend doesn't use his ability

### ISSUE THREAD

**Issue by zauru7** [Atlantiss/NetherwingBugtracker#3157]
[//]: # (Enclose links to things related to the bug using http://wowhead.com or any other TBC database.)
[//]: # (You can use screenshot ingame to visual the issue.)
[//]: # (Write your tickets according to the format:)
[//]: # ([Quest][Azuremyst Isle] Red Snapper - Very Tasty!)
[//]: # ([NPC] Magistrix Erona)
[//]: # ([Spell][Mage] Fireball)
[//]: # ([Npc][Drop] Ghostclaw Lynx)
[//]: # ([Web] Armory doesnt work)
[//]: # (To find server revision type `.server info` command in the game chat.)

**Description**: 
Fear Fiend ID 22204 in BEM is supposed to have a frontal cone fire damage ability called "Fel Flames". This ability is supposed to be conserved when they're enslaved. 
**Current behaviour**:
They're not using the ability when facing them and it's not conserved(probably because it's not there in the first place) when you enslave them
![wowscrnshot_120118_000945](https://user-images.githubusercontent.com/44526051/49319650-1ff7bc80-f4fe-11e8-95f8-d1db697bac08.jpg)

**Expected behaviour**: 
They should use the spell and it should be usable when enslaved. 
**Server Revision**: 
2370

**Comment by The14me** [comment]
Confirm! Spell id : 36248

**Comment by Evolvee** [comment]
fixed in next rev

**Comment by The14me** [comment]
ID is right,but the spell dmg is way off.
