### ISSUE TITLE
[Aura Stacking] Low rank spell being canceled after cast time elapsed if aura from same higher rank spell is already applied on target.

### ISSUE THREAD

**Issue by fvb1** [Atlantiss/NetherwingBugtracker#3159]
[//]: # (Enclose links to things related to the bug using http://wowhead.com or any other TBC database.)
[//]: # (You can use screenshot ingame to visual the issue.)
[//]: # (Write your tickets according to the format:)
[//]: # ([Quest][Azuremyst Isle] Red Snapper - Very Tasty!)
[//]: # ([NPC] Magistrix Erona)
[//]: # ([Spell][Mage] Fireball)
[//]: # ([Npc][Drop] Ghostclaw Lynx)
[//]: # ([Web] Armory doesnt work)
[//]: # (To find server revision type `.server info` command in the game chat.)

**Description**: 
Low rank spell being canceled after cast time elapsed if aura from this spell with higher rank is applied on target already.
**Current behaviour**:
Responds with error text: "A more powerfull spell is already active" and cancels spell cast.
Example: Cannot overwrite frostbolt last rank snare effect by frostbolt rank 1.
With npc:
https://youtu.be/xwKXidt-Psg
With player. At 31 second on following video:
https://youtu.be/Wjfs87vXUAY?t=27

**Expected behaviour**: 
Not sure about overwriting auras, but it shouldn't cancel spell cast at least.
Sources: Any TBC retail mage PvP movie(sorry for not providing any).
**Server Revision**: 
2371(I hope it's right)

**Comment by The14me** [comment]
https://github.com/Atlantiss/NetherwingBugtracker/issues/2312
