### ISSUE TITLE
Bloodfury Ripper

### ISSUE THREAD

**Issue by Young991** [Atlantiss/NetherwingBugtracker#316]
([Quest][Stonetalon Mountains] Bloodfury Bloodline)
 ([NPC] Bloodfury Ripper)
([Npc][Drop] Bloodfury Ripper's Remains)

**Description**: 
Loot Bugged
**Current behaviour**:
Does not drop the remains
**Expected behaviour**: 
Drops the remains on kill
**Server Revision**:

**Comment by aresbrutus** [comment]
Corrected in one of the next updates.
