### ISSUE TITLE
[Karazhan] Arcane Watchman(Arcane Explosion cast range)

### ISSUE THREAD

**Issue by Fenvarien1** [Atlantiss/NetherwingBugtracker#3160]
**Description**: 
Arcane Watchman - the Robots before The Curator - after Theater
https://wow.gamepedia.com/Arcane_Watchman
http://db.hellfire-tbc.com/?spell=29768
Spellname: Overload(the AOE debuff aka ArcaneExplosion for the raid)
Spell-ID: 29768

**Current behaviour**:
The Mob runs towards the Raid to cast his Spell which should be max range castable. Feels like he only got a 25y castrange right now.
That's even a bigger problem because it sets range DPS higher in threat due to the closer range and they pull higher threat than the tank.

**Expected behaviour**: 
having a 40y range -not moving at all

**Server Revision**: 
2370

**Comment by Tereneckla** [comment]
Fixed
