### ISSUE TITLE
[Warrior] [Talent] [2h and one hand Weapon Specialization]

### ISSUE THREAD

**Issue by Owsikchaosue** [Atlantiss/NetherwingBugtracker#3161]
[//]: # (Enclose links to things related to the bug using http://wowhead.com or any other TBC database.)
[//]: # (You can use screenshot ingame to visual the issue.)
[//]: # (Write your tickets according to the format:)
[//]: # ([Quest][Azuremyst Isle] Red Snapper - Very Tasty!)
[//]: # ([NPC] Magistrix Erona)
[//]: # ([Spell][Mage] Fireball)
[//]: # ([Npc][Drop] Ghostclaw Lynx)
[//]: # ([Web] Armory doesnt work)
[//]: # (To find server revision type `.server info` command in the game chat.)

**Description**:

**Current behaviour**: talents works like aura increases all dmg one hand two hand and ranged

**Expected behaviour**:  [Two-Handed Weapon Specialization] works only on 2h
 [One-Handed Weapon Specialization] works only on 1h

**Server Revision**:

**Comment by Mikik3jr** [comment]
I reported a same issue with paladins:
https://github.com/Atlantiss/NetherwingBugtracker/issues/1441
