### ISSUE TITLE
[Talent][Rogue] Ruthlessness on range (not Deadly Throw)

### ISSUE THREAD

**Issue by Phibs77** [Atlantiss/NetherwingBugtracker#3162]
[//]: # (Enclose links to things related to the bug using http://wowhead.com or any other TBC database.)
[//]: # (You can use screenshot ingame to visual the issue.)
[//]: # (Write your tickets according to the format:)
[//]: # ([Quest][Azuremyst Isle] Red Snapper - Very Tasty!)
[//]: # ([NPC] Magistrix Erona)
[//]: # ([Spell][Mage] Fireball)
[//]: # ([Npc][Drop] Ghostclaw Lynx)
[//]: # ([Web] Armory doesnt work)
[//]: # (To find server revision type `.server info` command in the game chat.)

**Description**: 
I'm not 100% how Ruthlessness is supposed to work and the research attempts were rather confusing, so i'm opening a ticket here with the possibility to either add "Needs research" or "Invalid" to it if someone knows how it's supposed to work.

When i tested Ruthlessness in combination with Slice and Dice, i sometimes gained combopoints when using Slice and Dice in melee range. So far, everything good (well, expect #1645, also added my tests there).
When i moved out of melee range i never gained any combopoints. Ruthlessness was changed from "finishing moves" to "melee finishing moves" in patch 2.3 i think. But since we are using 2.4.3 talents and it still procs Ruthlessness in melee range, i'm confused if Slice and Dice is only considered a "melee finishing move" when used in melee range or if it should/could proc Ruthlessness when used out of melee range. The patchnotes only say that it shouldn't proc on Deadly Throw anymore.

**Current behaviour**:
Ruthlessness only procs combopoints when in melee range.

**Expected behaviour**: 
Proc on Slice and Dice out of melee range? Maybe someone else knows. As i said, not 100% sure how it's supposed to work blizzlike. But i rather make an invalid report than let a possible bug stay in the game. :)

**Server Revision**: 
2370

**Comment by Peglaa** [comment]
Wowhead comments indicate that it did proc but in wotlk, I also cannot find any substantial proof for tbc altho I see little changes regarding that and also why would they change it late tbc just to change it again in wotlk. It should most likely proc no matter the range but I'm not sure if we can find some real proof...

**Comment by Wolffenstein** [comment]
It has 5yd max range.
