### ISSUE TITLE
[NPC][Silvermoon City] Sirigna'no ruins my immersion

### ISSUE THREAD

**Issue by Brasso** [Atlantiss/NetherwingBugtracker#3163]
[//]: # (Enclose links to things related to the bug using http://wowhead.com or any other TBC database.)
[//]: # (You can use screenshot ingame to visual the issue.)
[//]: # (Write your tickets according to the format:)
[//]: # ([Quest][Azuremyst Isle] Red Snapper - Very Tasty!)
[//]: # ([NPC] Magistrix Erona)
[//]: # ([Spell][Mage] Fireball)
[//]: # ([Npc][Drop] Ghostclaw Lynx)
[//]: # ([Web] Armory doesnt work)
[//]: # (To find server revision type `.server info` command in the game chat.)

**Description**: 
She paths through a chair, even when I'm sitting in it. Please fix immediately or I unsub.

https://imgur.com/a/eIavzRF. Location in album.

**Server Revision**: 
2370

**Comment by Evolvee** [comment]
fixed in next rev
