### ISSUE TITLE
([Spell][Mage] Blizzard)

### ISSUE THREAD

**Issue by somnu** [Atlantiss/NetherwingBugtracker#3164]
**Description**: 
Game objects that are not considered line of sight blockers (i.e: trees) block line of sight for Blizzard spell.

**Current behaviour**:
Sign posts and trees and other game objects that don't block LoS for spells like frostbolt DO block LOS for blizzard.

**Expected behaviour**: 
Blizzard should castable behind trees just like all other spells. I think this isn't limited to blizzard as I asked a priest friend and he said mass dispel acts the same way. So it might be for all AOE targetable spells.
**Server Revision**: 
2370

**Comment by killablink** [comment]
There was that bug on Gummy too, I think it's a client side bug, not sure if we can get it fixed

**Comment by Wolffenstein** [comment]
Fixed in rev 2392.
