### ISSUE TITLE
[Steamvault] One mob not following on pull of pack and aggroing patrol.

### ISSUE THREAD

**Issue by Unfairy** [Atlantiss/NetherwingBugtracker#3165]
![wowscrnshot_120118_181751](https://user-images.githubusercontent.com/41975070/49330589-78c86300-f599-11e8-8a5c-1cd88a85b0ed.jpg)
Moon marked mob not going anywhere on pull and thus aggroing patrol.
Mob supposed to aggro on pull and follow the target.

**Comment by Easyfraggy** [comment]
it does agro - but can't find path in that area - we also encountered this on closed beta. (same mob and pack)

**Comment by bloodwindz** [comment]
he can find the path from the rigth side of the pillar but not from the left

**Comment by Tenoutoften** [comment]
possibly related to what I just posted
https://github.com/Atlantiss/NetherwingBugtracker/issues/3171

**Comment by rychersky** [comment]
This is still occurring and quite aggravating when it causes wipes.

**Comment by Realnairoby** [comment]
28.08.2020. Still bugged. best tbc experience ive ever had. Thanks for nothing. Awesome job

**Comment by Tereneckla** [comment]
![image](https://user-images.githubusercontent.com/50233983/91708746-0c213480-eb82-11ea-8cf6-a89c78d252dc.png)

**Comment by Wolffenstein** [comment]
Fixed in rev 3737.
