### ISSUE TITLE
[Steam Vaults] Warlord Kalitresh's door not closing up on engaging the fight.

### ISSUE THREAD

**Issue by Unfairy** [Atlantiss/NetherwingBugtracker#3166]
Warlord Kalitresh's door not closing up on engaging the fight.
![wowscrnshot_120118_193023](https://user-images.githubusercontent.com/41975070/49330621-ba590e00-f599-11e8-9fdc-787e26e9138b.jpg)

**Comment by devo6969** [comment]
Yea, the door is suppose to be closed.
https://youtu.be/q2SGNawC7kw?t=94

**Comment by Wolffenstein** [comment]
Fixed in rev 3452.
