### ISSUE TITLE
Assisting with summoning through summoning stone should req channeling for ~5s rather than instant

### ISSUE THREAD

**Issue by Tenoutoften** [Atlantiss/NetherwingBugtracker#3167]
**Description**: 
Assisting someone with summoning through the summoning stone on NW displays no animation and instantly complete while it should have a channeling animation for roughly 5 seconds.

The channeled cast should be hidden on the assistants screen, just like with regular summoning: https://youtu.be/kbfjINV3qCY?t=46 

[Retail](https://youtu.be/u0HlBnfsSMU?t=114)
[NW](https://www.youtube.com/watch?v=KUIBiTRGqEQ&feature=youtu.be)

**Expected behaviour**: 
Expected to be a 5 seconds channel with spell effect

**Server Revision**: 
2370

**Comment by Wolffenstein** [comment]
Pretty sure it just depends on when the required number of people click it.

**Comment by Tenoutoften** [comment]
What do you mean? With summoning stone only 1 is required

**Comment by BamboozleNW** [comment]
#2345
