### ISSUE TITLE
[Coilfang Reservoir] Mortog Steamhead 2.0 / 2.1

### ISSUE THREAD

**Issue by Unfairy** [Atlantiss/NetherwingBugtracker#3168]
Mortog Steamhead not supposed to be there (or at least selling stuff and repairing gear) untill 2.1
![buggy](https://user-images.githubusercontent.com/41975070/49330701-e759f080-f59a-11e8-848c-1a79fe299558.jpeg)

**Comment by Tenoutoften** [comment]
https://wow.gamepedia.com/Mortog_Steamhead
Patch 2.0.3 (2007-01-09): Added. 
Patch 2.1.0 (2007-05-22):
* Mortog Steamhead standing outside of the Coilfang dungeons will repair armor and weapons as well as sell various items to those exalted with the Cenarion Expedition.
* Mortog will now trade players Cenarion healing and mana salves for Coilfang Armaments. These potions only work inside the Coilfang dungeon and raid zones.

**Comment by Unfairy** [comment]
No, only thing he is doing for people in 2.0 is just talk to them. Exalted mentioned here not as in 2.0 he is trading it only to those who's exalted but just as requirements.
Untill 2.1 its just NPC that talks to you.

**Comment by Manaci** [comment]
Irrelevant now

**Comment by Evolvee** [comment]
We will still need to fix this for future.
