### ISSUE TITLE
[Steam Vaults] Warlord Kalitresh not casting Impale.

### ISSUE THREAD

**Issue by Unfairy** [Atlantiss/NetherwingBugtracker#3169]
Warlord Kalitresh not casting Impale.
Impale Counted 0 for whole fight.
http://db.hellfire-tbc.com/?npc=17798#abilities
https://www.wowhead.com/npc=17798/warlord-kalithresh#comments
![buggy2](https://user-images.githubusercontent.com/41975070/49330737-70712780-f59b-11e8-870c-ed2f1fac01b8.jpeg)

**Comment by Jacksn5** [comment]
Can confirm, he didn't cast it once in our very long 1 DPS fight.

![image](https://user-images.githubusercontent.com/43507549/50548198-e32bfc00-0c48-11e9-969d-270e6af0c080.png)

**Comment by Easyfraggy** [comment]
It was working during closed beta - not sure what made it not work anymore?

**Comment by devo6969** [comment]
Still bugged, zero impales 
PTR - https://www.youtube.com/watch?v=i__6-PTvD4A

Retail TBC - https://www.youtube.com/watch?v=q2SGNawC7kw

**Comment by Wolffenstein** [comment]
Fixed in rev 3452.
