### ISSUE TITLE
I have arena points without doing arena or even pvping at all.

### ISSUE THREAD

**Issue by Ceago** [Atlantiss/NetherwingBugtracker#3170]
**Description**:   I have 24 arena points without any pvp activity.  Character name Ceagoe.

**Current behaviour**:  Have arena points.

**Expected behaviour**:  Should not have arena points.

**Server Revision**: 2370

**Comment by Phibs77** [comment]
Same. I have 13 Arena Points without ever entering any arena or even team.

**Comment by Tereneckla** [comment]
Fixed
