### ISSUE TITLE
[Warrior] Spell Reflection -Freezing Trap

### ISSUE THREAD

**Issue by bloodwindz** [Atlantiss/NetherwingBugtracker#3173]
[//]: # (Enclose links to things related to the bug using http://wowhead.com or any other TBC database.)
[//]: # (You can use screenshot ingame to visual the issue.)
[//]: # (Write your tickets according to the format:)
[//]: # ([Quest][Azuremyst Isle] Red Snapper - Very Tasty!)
[//]: # ([NPC] Magistrix Erona)
[//]: # ([Spell][Mage] Fireball)
[//]: # ([Npc][Drop] Ghostclaw Lynx)
[//]: # ([Web] Armory doesnt work)
[//]: # (To find server revision type `.server info` command in the game chat.)

**Description**: spell reflection frost trap

**Current behaviour**:it work correctly and eats the frost trap but a visual bug apears like something got frozen when its not

**Expected behaviour**:  the nothing will apear on screen if  a warr spell reflect a frost trap like this video
https://www.youtube.com/watch?v=0M3HznqYuzc&t=415s
trap can be also reflected even after scattered shot as shown

**Server Revision**: 2372

**Comment by teddys** [comment]
he's reflecting a freezing trap
frost trap can't be reflected

**Comment by bloodwindz** [comment]
yeah

**Comment by The14me** [comment]
rev.3478 still an issue.

**Comment by Wolffenstein** [comment]
Fixed in rev 3533.
