### ISSUE TITLE
[Quest][Azuremyst Isle] Vindicator Aldar

### ISSUE THREAD

**Issue by xycz** [Atlantiss/NetherwingBugtracker#3174]
[//]: # (Enclose links to things related to the bug using http://wowhead.com or any other TBC database.)
[//]: # (You can use screenshot ingame to visual the issue.)
[//]: # (Write your tickets according to the format:)
[//]: # ([Quest][Azuremyst Isle] Red Snapper - Very Tasty!)
[//]: # ([NPC] Magistrix Erona)
[//]: # ([Spell][Mage] Fireball)
[//]: # ([Npc][Drop] Ghostclaw Lynx)
[//]: # ([Web] Armory doesnt work)
[//]: # (To find server revision type `.server info` command in the game chat.)

**Description**: 
Quest is available too early.

**Current behaviour**:
The quest 'Vindicator Aldar' is available before finishing 'Healing the Lake'.

**Expected behaviour**: 
The quest 'Vindicator Aldar' should be locked until the player has completed 'Healing the Lake'.

**Server Revision**: 
2370

**Reference**:
https://db.excalibur.ws/?quest=10304

**Comment by Shanghi** [comment]
That's true, but it's already set that way and I can't figure out how to reproduce the problem! Did it offer you 2 quests at once, or did it just skip Healing the Lake after What Must Be Done...?

**Comment by xycz** [comment]
I will have to create a new character to be sure exactly what order I got the quests in, but I am certain that I completed 'Healing the Lake' after 'Inoculation' which as I understand it, should not be possible.

**Comment by Shanghi** [comment]
Oh! Vindicator Aldar is just an optional breadcrumb quest that leads to Inoculation. You can do Inoculation before that, but then you won't be able to do Vindicator Aldar later. This is according to the official strategy guide and a note near to bottom of <http://wowwiki.wikia.com/wiki/Quest:Inoculation>:
> The quest [4] Vindicator Aldar is not required to receive this quest. However, once you have this quest you can no longer receive [4] Vindicator Aldar, so to get a little extra experience it is recommended to complete the [3] Healing the Lake quest chain and [4] Vindicator Aldar before this quest.
