### ISSUE TITLE
[NPC] Cave LoS potential bug

### ISSUE THREAD

**Issue by sefamurat** [Atlantiss/NetherwingBugtracker#3175]
[//]: # (Enclose links to things related to the bug using http://wowhead.com or any other TBC database.)
[//]: # (You can use screenshot ingame to visual the issue.)
[//]: # (Write your tickets according to the format:)
[//]: # ([Quest][Azuremyst Isle] Red Snapper - Very Tasty!)
[//]: # ([NPC] Magistrix Erona)
[//]: # ([Spell][Mage] Fireball)
[//]: # ([Npc][Drop] Ghostclaw Lynx)
[//]: # ([Web] Armory doesnt work)
[//]: # (To find server revision type `.server info` command in the game chat.)

**Description**: Mob LoS issue

**Current behaviour**: Kobold doesn't notice me in cave standing right near me when another mob far away does

**Expected behaviour**: It should notice me at least at the same time the other mob does

**Server Revision**: 2370

Video: https://gyazo.com/561bb4e9d869f85d8b83ab9b4e0e4815

**Comment by Wolffenstein** [comment]
It's not a LoS issue, the AI is just optimized in a way that mobs look for targets in certain intervals. As you saw later he aggroed just fine when assisting the other mob. If you moved a little he would start attacking as well.
