### ISSUE TITLE
[Karazhan] Attempting to enter instance while dead and raid is in combat with a boss ports you to Shattrath.

### ISSUE THREAD

**Issue by manslaughter** [Atlantiss/NetherwingBugtracker#3179]
**Description**: See title.

**Current behaviour**: You are ported to Shattrath as a ghost.

**Expected behaviour**: You are prevented from zoning in but don't get ported naywhere.

**Server Revision**: 2374

**Comment by Wolffenstein** [comment]
Fixed in rev 2378.
