### ISSUE TITLE
Amani Berserker#15643 wrong Enrage spell

### ISSUE THREAD

**Issue by Tenoutoften** [Atlantiss/NetherwingBugtracker#318]
**Description**: 

_Amani Berserker_, NPC#15643(https://db.excalibur.ws/?npc=15643) uses wrong enrage spell and thus deals way more damage than it should. It should be using _Enrage_, spell#8599(https://db.excalibur.ws/?spell=8599). 

**Current behaviour**:

_Amani Berserker#15643_ uses incorrect Enrage spell and thus significantly different damage output. Recieved 88 Crit followed by 94 Crit(https://i.gyazo.com/7b18e96408a263b5d65d3e94530af8b0.png) with _420 armor / 25.15% physical damage reduction_ at level 10.

**Expected behaviour**: 

_Amani Berserker#15643_ should use _Enrage#8599_

**Server Revision**: 

2040

**Comment by Evolvee** [comment]
fixed in next hotfix revision
