### ISSUE TITLE
[Item] Annihilator proc rate

### ISSUE THREAD

**Issue by Galawer** [Atlantiss/NetherwingBugtracker#3180]
**Description**: 
[[Annihilator]](http://db.excalibur.ws/?item=12798) - [[Armor Shatter]](http://db.excalibur.ws/?spell=16928)

**Current behaviour**:
Proc rate is way too low, from what I've tested it seems to be 5%. Even when dual wielding with Flurry and double Mongoose I cannot reliably keep the debuff up by myself, sometimes I can be swinging for up to 3 minutes without a single proc.

**Expected behaviour**: 
The only sources I could find on what the proc rate should be are [a Wowhead comment](https://www.wowhead.com/item=12798/annihilator#comments:id=279758):

> In testing with Seal of the Crusader it procc'ed every 5 to 8 swings and i was easily able to get it stacked to 3 and keep it there.

and [a website](https://xpoff.com/threads/weapon-proc-rates.60492/) that lists a bunch of Vanilla items. According to it the proc rate on Annihilator should be 15%. That does line up with the Wowhead comment, a proc every 5 to 8 hits is just about 15%, that's also what the proc rate was on other servers I've played on.

**Server Revision**: 
2374

**Comment by Wolffenstein** [comment]
Fixed in rev 2383.
