### ISSUE TITLE
[Hunter] Talent: Entrapment (Survival) 

### ISSUE THREAD

**Issue by Tim130** [Atlantiss/NetherwingBugtracker#3181]
[//]: # (Enclose links to things related to the bug using http://wowhead.com or any other TBC database.)
[//]: # (You can use screenshot ingame to visual the issue.)
[//]: # (Write your tickets according to the format:)
[//]: # ([Quest][Azuremyst Isle] Red Snapper - Very Tasty!)
[//]: # ([NPC] Magistrix Erona)
[//]: # ([Spell][Mage] Fireball)
[//]: # ([Npc][Drop] Ghostclaw Lynx)
[//]: # ([Web] Armory doesnt work)
[//]: # (To find server revision type `.server info` command in the game chat.)

**Description**: 
The Survival-Talent "Entrapment" doesn´t work correctly.

**Current behaviour**:
Only works for the first "Pulse" of Explosive Trap.

**Expected behaviour**: 
The talent should work for each "Pulse" of:
- Immolation Trap
- Frost Trap
- Explosive Trap
- Snake Trap
with a 25% chance of 4 s immobilization.

**Server Revision**: 
Talent-Tooltip
https://wow.gamepedia.com/Entrapment

**Comment by Tim130** [comment]
Server Revision 2377

**Comment by Tereneckla** [comment]
Snake Trap is left as not being able to proc entrapment at all.
The other traps are fixed.
