### ISSUE TITLE
[NPC] [Spell] [Karazhan] Skeletal Waiter - Brittle Bones

### ISSUE THREAD

**Issue by Drayo** [Atlantiss/NetherwingBugtracker#3184]
[//]: # (Enclose links to things related to the bug using http://wowhead.com or any other TBC database.)
[//]: # (You can use screenshot ingame to visual the issue.)
[//]: # (Write your tickets according to the format:)
[//]: # ([Quest][Azuremyst Isle] Red Snapper - Very Tasty!)
[//]: # ([NPC] Magistrix Erona)
[//]: # ([Spell][Mage] Fireball)
[//]: # ([Npc][Drop] Ghostclaw Lynx)
[//]: # ([Web] Armory doesnt work)
[//]: # (To find server revision type `.server info` command in the game chat.)

**Description**: 

Brittle Bones does not work correctly from what I can tell.

**Current behaviour**:

Right now, when you get the debuff, you turn into a Skeleton for the entire duration, this is not correct.

**Expected behaviour**: 

This mob **should give you a debuff lasting 90 seconds, called "[Brittle Bones](https://tbc-twinhead.twinstar.cz/?spell=32441)"** that says:  > You feel...different. 
**You get this debuff and for now nothing happens.** Then when you have this debuff, from time to time you should get transformed into a skeleton and lose all armor. This will be a **second debuff, called "[Rattled](https://tbc-twinhead.twinstar.cz/?spell=32437)" lasting about 10 seconds** saying:  > No armor.

This transformation comes and goes while you have the debuff. That means you are a skeleton for 10 seconds and then back to normal, after like 20 seconds you are a skeleton without armor again.
Sometimes you only get transformed once for the entire duration of the debuff and sometimes you are transformed 2-3 times, it should be a bit random.

Debuff that the Mob should apply(already working): https://tbc-twinhead.twinstar.cz/?spell=32441
Debuff that you should get a few times during those 90 seconds: https://tbc-twinhead.twinstar.cz/?spell=32437

Last time that debuff was checked, no passive spell existed to actually trigger the "Rattled" debuff (like getting hit triggering it), thus it was put on a timer with a random +- element, but I guess that stuff is better left to you guys.

As for sources, the Spell Brittle Bones already mentions "periodically" and on [this ](https://wow.gamepedia.com/Skeletal_Waiter)wiki page it is also mentioned.

Do mind though that the Brittle Bones Spell was modified here https://github.com/Atlantiss/NetherwingBugtracker/issues/3010 and should be reverted.

**Server Revision**: 2371

**Comment by Wolffenstein** [comment]
Fixed in rev 2381.
