### ISSUE TITLE
[NPC] [Boss] [Karazhan] The Big Bad Wolf - Run Speed

### ISSUE THREAD

**Issue by Drayo** [Atlantiss/NetherwingBugtracker#3185]
[//]: # (Enclose links to things related to the bug using http://wowhead.com or any other TBC database.)
[//]: # (You can use screenshot ingame to visual the issue.)
[//]: # (Write your tickets according to the format:)
[//]: # ([Quest][Azuremyst Isle] Red Snapper - Very Tasty!)
[//]: # ([NPC] Magistrix Erona)
[//]: # ([Spell][Mage] Fireball)
[//]: # ([Npc][Drop] Ghostclaw Lynx)
[//]: # ([Web] Armory doesnt work)
[//]: # (To find server revision type `.server info` command in the game chat.)

**Description**: 

His run speed seems to be a bit low.

**Current behaviour**:

He could be outrun even without the debuffs speed increase. He also never switches to his worgen sprint animation which he does in a lot of videos from time to time.

**Expected behaviour**: 

I know his speed was probably taken from a sniff, but if you watch some videos it seems that players actually did have some trouble outrunning him, even though their path does not seem stupid or anything like that. 

He seems to be only slightly slower than the player with the debuff, implying that he should be about as fast as a normal player maybe very slightly faster. Then, the ones chased get a small increase by the debuff to outrun him.

Some source material:

https://youtu.be/tstm93TkCG0?t=183

https://youtu.be/A2x202ulSG0?t=126
https://youtu.be/SvW5g_I_-X8?t=74
See how the melees chasing him can barely keep up on a straight in these two?

**Server Revision**: 2377

**Comment by bloodwindz** [comment]
he was faster a bit and we needed to hug run  in to wall to slow him down in retail

**Comment by Tenoutoften** [comment]
People might not have used minor speed too

**Comment by Drayo** [comment]
Closing this since his speed was taken from sniffs.
