### ISSUE TITLE
Lootable items stay after picking them up

### ISSUE THREAD

**Issue by acedo1234** [Atlantiss/NetherwingBugtracker#3186]
[//]: # (Enclose links to things related to the bug using http://wowhead.com or any other TBC database.)
[//]: # (You can use screenshot ingame to visual the issue.)
[//]: # (Write your tickets according to the format:)
[//]: # ([Quest][Azuremyst Isle] Red Snapper - Very Tasty!)
[//]: # ([NPC] Magistrix Erona)
[//]: # ([Spell][Mage] Fireball)
[//]: # ([Npc][Drop] Ghostclaw Lynx)
[//]: # ([Web] Armory doesnt work)
[//]: # (To find server revision type `.server info` command in the game chat.)

**Description**: Items stay in the world when looted for a bit longer than they should.

**Current behaviour**: Battered Chests for instance stay even with no loot in them and having inventory space, the same also was found from me when I picked up Wood Logs in the "a Bundle of Trouble" quest, but they disappeared after abut 30 seconds.

**Expected behaviour**:  After looting they should disappear immediately.

**Server Revision**: 2377

**Comment by wtRCH** [comment]
Known issue.
