### ISSUE TITLE
Defias Thug Movement Speed

### ISSUE THREAD

**Issue by acedo1234** [Atlantiss/NetherwingBugtracker#3187]
[//]: # (Enclose links to things related to the bug using http://wowhead.com or any other TBC database.)
[//]: # (You can use screenshot ingame to visual the issue.)
[//]: # (Write your tickets according to the format:)
[//]: # ([Quest][Azuremyst Isle] Red Snapper - Very Tasty!)
[//]: # ([NPC] Magistrix Erona)
[//]: # ([Spell][Mage] Fireball)
[//]: # ([Npc][Drop] Ghostclaw Lynx)
[//]: # ([Web] Armory doesnt work)
[//]: # (To find server revision type `.server info` command in the game chat.)

**Description**: Defias Thugs in the starting zone run REALLY slow after you when they get low.

**Current behaviour**: Get low, walk as if slowed.

**Expected behaviour**: Im spitballing as I cant find any of them getting low in videos but them just infinitely walking at you when they get low does not seem right, I believe they should just have normal speed.

**Server Revision**: 2377

**Comment by acedo1234** [comment]
Seems Prowlers and Young forest bears do this too. Possible all mobs do this?

**Comment by wtRCH** [comment]
This is blizzlike.

**Comment by acedo1234** [comment]
These monsters don't run in fear though. Most animals don't run in fear, the starting zone defias themselves don't run in fear (many other ones do but not these ones) https://youtu.be/aWyxdOzIVJU?t=64 here is a guy slowly killing the mobs in 2008 but they don't run in fear.

Not to mention if they run in fear they are supposed to turn tail and flee, not keep attacking while being slowed. The entire lethality of the murlocs in elwynn by the logging camp is from their ability to run away in fear and pull more murlocs, they don't do that here, instead they run slowly\ TOWARDS you when low.

I've tested up to a dozen different mobs (Many in high level TBC zones) and they ALL move slow when low. Many of them beasts, now keep in mind very FEW beasts actually run away in fear. This is a glaring issue to allow people to kite anything forever as long as its low and it will be noticeable on day 1. 

When every (i assume its every mob as I haven't came across one that hasn't done this yet) does this it is going to be embarrassing. Here is a clip I took of just 1 mob doing it, you can even melee it without being hit once you get the hang of it (I didn't do this in the clip but it is possible to attack unharmed) https://youtu.be/t-_Ct3mD8gU
