### ISSUE TITLE
[Dungeon] Botanica [NPC] Commander Sarannis

### ISSUE THREAD

**Issue by stevemcdjr** [Atlantiss/NetherwingBugtracker#3189]
**Description**: 
In Normal Botanica, the first boss Commander Sarannis is level 73 instead of 72 like she's supposed to be. See screenshot below.

**Current behaviour**:
Commander Sarannis is level 73. 

**Expected behaviour**: 
Commander Sarannis is level 72.

**Server Revision**: 
2382

![wowscrnshot_120118_220048](https://user-images.githubusercontent.com/31624800/49335249-c81d8c00-f5b7-11e8-9277-033ed9e30a7a.jpg)

**Comment by Wolffenstein** [comment]
Proof that she should be 72?

**Comment by killablink** [comment]
https://www.youtube.com/watch?v=7B_ehT9uHB0

Level 72 in that video

**Comment by Evolvee** [comment]
rev 2538
