### ISSUE TITLE
[Pet] Disappears while swimming

### ISSUE THREAD

**Issue by Scylla420** [Atlantiss/NetherwingBugtracker#319]
**Description**: 
While I was swimming from Thelsamar to the other side of The Loch, my voidwalker bugged out and disappeared from view completely.  It's still listed as an active pet, and while I can use the spell health funnel, it's channeled into my body visually, doesn't heal my pet, and doesn't drain any health from me.  An issue with pet pathing in water for the most part.
**Current behaviour**:
[You can see the pet vanish 40 secs in](https://streamable.com/omjrd)
[Health Funnel test](https://streamable.com/89yn8)
**Expected behaviour**: 
Pet should path along the water with no issue, should swim along with me, and not disappear like this.
**Server Revision**: 
2040

**Comment by Wolffenstein** [comment]
Fixed in rev 2074.
