### ISSUE TITLE
[Spell][Hunter] Serpent Sting

### ISSUE THREAD

**Issue by kubawww7** [Atlantiss/NetherwingBugtracker#3191]
**Description**:
 Hunter can't refresh his Serpent sting

**Current behaviour**:
Improved Serpent sting by talent can't be refreshed befor it end. Shows message that: A more powerfull spell is allready active.

**Expected behaviour**:
 Improved Serpent sting by talent should be refreshed before the end.

**Comment by tcberk12** [comment]
this has been fixed in an update since reported
