### ISSUE TITLE
[Shaman] windfury crits do not proc special effects

### ISSUE THREAD

**Issue by pesky89** [Atlantiss/NetherwingBugtracker#3193]
**Description**: winfury critical strikes do not proc special effects like flurry, shamanistic focus etc

**Current behaviour**: winfury critical strikes do not proc special effects like flurry, shamanistic focus etc

**Expected behavior**: windfury crits shoul trigger special effects like melee attacks do, even if it’s yellow damage

**Server Revision**: 2377

**Comment by Zarant** [comment]
After patch 2.2, extra attacks from sword spec couldn't proc any kind of effect, I'm not 100% sure if the same thing applies for windfury as well.

**Comment by pesky89** [comment]
Hello  
post from 2007: https://blue.mmo-champion.com/topic/18050-tbc-enhancement-shaman-faq/  : The two extra attacks can proc flurry, unleashed rage, and shamanistic rage. They do not consume flurry charges, and don't glance.  
post from 2007: https://www.wowhead.com/forums&topic=1209 : Windfury procs, though yellow in damage, WILL activate flurry).  
post from 2008: https://www.wowhead.com/forums&topic=7393 : WF means more hits which means more chances to crit procing both flurry and shamanistic focus.

**Comment by rjorgensen** [comment]
Windfury would activate Flurry back in vanilla. [https://youtu.be/ja1j7xWpB3w?t=56](url) (unbreakable).
If you look closely at 56 seconds you can he lands 3 attacks - a normal for ~440 and 2 critical strikes for ~1.2K. Windfury adds AP to the attacks. I assume the non critical strike is a normal swing and the two critical strikes are windfury attacks. When you slow the video down, you can see he gains flurry.
![wf proc](https://user-images.githubusercontent.com/45169919/49369746-7299ca00-f6f2-11e8-87b3-4becb788b0ef.png)
Print from some testing on dummies on NW beta. Here you can see WF procs do not activate flurry.

**Comment by Galawer** [comment]
Duplicate: https://github.com/Atlantiss/NetherwingBugtracker/issues/1951
