### ISSUE TITLE
[Nagrand] Pure Water

### ISSUE THREAD

**Issue by Tzunamii** [Atlantiss/NetherwingBugtracker#3194]
**Description**:  Pure water

**Current behaviour**: Pure water and Bluefish school stacking on eachother

**Expected behaviour**:  Can only be 1 School of fish at a time.

**Server Revision**: 
2321

**Comment by The14me** [comment]
any gps on the location or at least screenshot of the place please?

**Comment by Manaci** [comment]
Fixed
