### ISSUE TITLE
[spell][warrior] Sunder Armor stacks get reset once a second warrior uses sunder armor

### ISSUE THREAD

**Issue by sifiuocz** [Atlantiss/NetherwingBugtracker#3195]
**Description**: 
Sunder Armor stacks get reset to 1 once other warrior uses devastate (both tanks were using r3 in the testing), but once there is 5 stacks already it gets refreshed instead of it being reset.

**Current behaviour**:

**Expected behaviour**: 

**Server Revision**: 
2382

**Comment by Easyfraggy** [comment]
Possibly visual issue - can you share a video of this?

**Comment by Tenoutoften** [comment]
I tested this with two warriors using devastate r3 and didn't get Sunder Armor reset

**Comment by Easyfraggy** [comment]
That is just how tbc is afaik Tenoutoften - I always had problems with seeing SA duration from other players in raids - same for any debuff really - Thunder Clap - Demo Shout etc.

Seems this issue is no longer valid?
