### ISSUE TITLE
[Item] Nightfall proc chance

### ISSUE THREAD

**Issue by Galawer** [Atlantiss/NetherwingBugtracker#3196]
**Description**: 
[[Nightfall]](https://www.wowhead.com/item=19169/nightfall) - [[Spell Vulnerability]](https://www.wowhead.com/spell=23605/spell-vulnerability)

**Current behaviour**:
Proc chance is way too high against lvl 70 targets.

**Expected behaviour**: 
From 2.4.2 patch notes:
> [Nightfall] now has a chance to fail on targets over level 60

According to [Wowhead comments](https://www.wowhead.com/item=19169/nightfall#comments:id=280101) and [a post on Elitist Jerks](https://web.archive.org/web/20081109083512/http://elitistjerks.com/f31/t17089-paladin_protection_you/p55/#post727564) the proc rate was changed to ~0.1% to make the axe unusable in non-vanilla content:
>Against random mobs in Netherstorm lvl 68-70: 30mins 372 tracked hits, zero procs...
Against random mobs in Winterspring lvl 58-59: Spent maybe 10mins just to make sure it was still working, procced at the usual rate of around 15% (121 hits, 10procs in this particular testing)
Back to Netherstorm: Another hour and 712 swings on the logs I'm about to come here and report that it must be broken entirely, and something very disappointing happens... it procs, once on a lvl 68 Basilisk. Sadly it actually proccing shows it's not broken, but that the proc rate is >.1% by my results. (1084 hits, 1 proc)

For comparison, after 1011 hits on the lvl 70 target dummy, I got 94 procs.

**Server Revision**: 
2382

**Comment by Anselm123** [comment]
Isn't it 2.0 though so it should have a higher proc?

**Comment by Galawer** [comment]
> Isn't it 2.0 though so it should have a higher proc?
