### ISSUE TITLE
[Quest] Trial of the Naaru: Maghteridon

### ISSUE THREAD

**Issue by Dynastyy** [Atlantiss/NetherwingBugtracker#3197]
[//]: # (Enclose links to things related to the bug using http://wowhead.com or any other TBC database.)
[//]: # (You can use screenshot ingame to visual the issue.)
[//]: # (Write your tickets according to the format:)
[//]: # ([Quest][Azuremyst Isle] Red Snapper - Very Tasty!)
[//]: # ([NPC] Magistrix Erona)
[//]: # ([Spell][Mage] Fireball)
[//]: # ([Npc][Drop] Ghostclaw Lynx)
[//]: # ([Web] Armory doesnt work)
[//]: # (To find server revision type `.server info` command in the game chat.)

**Description**: 
(http://wowwiki.wikia.com/wiki/Quest:Trial_of_the_Naaru:_Magtheridon) 

**Current behaviour**:
After the completion of this quest we didn't get awared of "The Tempest Key" http://wowwiki.wikia.com/wiki/The_Tempest_Key . Also it showed me that we would have been awarded with the Title "Champion of the Naaru" which should be the case in 2.3 not in 2.0. 

**Expected behaviour**: 
After turning in the quest you should get the ring and the key.

**Comment by aresbrutus** [comment]
https://github.com/Atlantiss/AtlantissTBCBT/issues

**Comment by Shanghi** [comment]
The fix for this was just sent to be applied to the server, but it might not be on the public realm until The Eye is open since part of the change was to make entering require that key.
