### ISSUE TITLE
[NPC] Mobs running in fear at low hp stays permanently slowed

### ISSUE THREAD

**Issue by sefamurat** [Atlantiss/NetherwingBugtracker#3198]
**Description**: Mobs running in fear at low hp stays permanently slowed

**Current behaviour**: Mobs that trigger a "run away in fear" mechanic will stay slowed down after their fear ends and they return to attacking. (Currently only tested on some gnolls and defias mobs)

**Expected behaviour**: Mobs should retain their normal speed after their fear is over. (Although I could not find a proof for this, it's vividly how i remember it worked in retail. I might be wrong or confused)

**Server Revision**: 2382

**Comment by Tenoutoften** [comment]
You have to find evidence

**Comment by Zarant** [comment]
I believe that is working as intended, mobs are supposed to run slower if they are below ~15% hp

**Comment by Evolvee** [comment]
unless the mob heal itself to gain health, it will remain slowed by default regardless the flee
