### ISSUE TITLE
[NPC] Defias Footpad

### ISSUE THREAD

**Issue by Many12997** [Atlantiss/NetherwingBugtracker#3199]
http://db.hellfire-tbc.com/?npc=481#drop
http://wowwiki.wikia.com/wiki/Spawn
**Description**: 
NPC's named Defias Footpad at The Jansen Stead in westfall are respawning way faster than they should
**Current behaviour**:
Defias Footpad respawns after around  1 minute  
**Expected behaviour**: 
Most normal mobs respawn timer should be set on 5 minutes
**Server Revision**: 
2382

**Comment by Easyfraggy** [comment]
There are very few of these mobs - might be so fast due to dynamic respawns because you wipe out all of them?

**Comment by Many12997** [comment]
Im not sure how dynamic respawn works,but it appeared this way only on this specific mobs in whole westfall,so i cant tell for sure.
But I can tell for sure,that it didnt happend with gnolls,even tho i wiped out in few moments few camps with help of my friend.

**Comment by Easyfraggy** [comment]
There is only 1 group of these mobs - several groups of gnolls - dynamic respawns makes sure that there are always mobs of a specific type alive - which means if there is more than 1 area and you only clear one they wont respawn faster. However if there is only 1 area and you clear that they will respawn very fast. Maybe these mobs shouldn't have dynamic respawn - unless they are part of some quest?

**Comment by Many12997** [comment]
They can be part of quest for defias bandamas in westfall,but players usually do it on people's militia chain

**Comment by Easyfraggy** [comment]
Yeah I mean if they are only for bandanas they should not be dynamic.

**Comment by Dekirayne** [comment]
i am alone in there killing them and they respawn before i manage to kill another mob

**Comment by Manaci** [comment]
Fixed
