### ISSUE TITLE
warrior charging through floor

### ISSUE THREAD

**Issue by leahnie956** [Atlantiss/NetherwingBugtracker#32]
[//]: # (Enclose links to things related to the bug using http://wowhead.com or any other TBC database.)
[//]: # (You can use screenshot ingame to visual the issue.)
[//]: # (Write your tickets according to the format:)
[//]: # ([Quest][Azuremyst Isle] Red Snapper - Very Tasty!)
[//]: # ([NPC] Magistrix Erona)
[//]: # ([Spell][Mage] Fireball)
[//]: # ([Npc][Drop] Ghostclaw Lynx)
[//]: # ([Web] Armory doesnt work)

**Description**: 

**Current behaviour**:

**Expected behaviour**: 

**Server Revision**:

**Comment by DoctorRaymos** [comment]
Maybe give a location where this happened so it can be recreated, report is way too vague

**Comment by wtRCH** [comment]
Invalid for now. Waiting for more info

**Comment by wtRCH** [comment]
Invalid
