### ISSUE TITLE
[Spell] Unable to cast Drain Soul (1120) on critters.

### ISSUE THREAD

**Issue by Scylla420** [Atlantiss/NetherwingBugtracker#320]
**Description**: 
Attempting to use Drain Soul (1120) on a Squirrel (1412) bugs the spell out to where it channels for about .2 seconds before cancelling and dropping combat with the critter.
**Current behaviour**:
https://streamable.com/vf7oz
**Expected behaviour**: 
Drain Soul should channel as normal, killing the critter.
**Server Revision**: 
2040

**Comment by Easyfraggy** [comment]
Can you attack the critter with other spells? There is a bug atm with critters resetting/evading instantly.

**Comment by Scylla420** [comment]
> Can you attack the critter with other spells? There is a bug atm with critters resetting/evading instantly.

yeah you're right, seems like no spells work @Easyfraggy

**Comment by Easyfraggy** [comment]
Okay, this is a different issue tied to the bugged critters then!
