### ISSUE TITLE
[Quest][BEM] Gorgrom the Dragon-Eater

### ISSUE THREAD

**Issue by Geigerkind** [Atlantiss/NetherwingBugtracker#3201]
**Description**: You need to place totems on the corpse of a mob.

**Current behaviour**:
Works like a charm, but you can use multiple quest items on the same npc.

**Expected behaviour**: Dont know what happens specifically, but using it multiple times on the same mob is clearly not correct

**Server Revision**: 2382

**Comment by Kiperr** [comment]
https://www.youtube.com/watch?time_continue=143&v=pC3aTpDhFz0 so whats the bug?

**Comment by Geigerkind** [comment]
I see, I didnt think Blizzard would make such a pointless quest of placing 3 totems on the very same corpse. Thanks for finding that video.
