### ISSUE TITLE
[Quest][Object] Chen's Empty Keg

### ISSUE THREAD

**Issue by naekobest** [Atlantiss/NetherwingBugtracker#3202]
**Description**: 
The Kegs do not spawn at any of the given/known points. I checked those several times over a span of 30min. ([9 possible spawn locations](https://vanilla-twinhead.twinstar.cz/?object=3238))
57.2, 9.0
55.8, 20.
55.7, 27.3
54.7, 37.2
56.5, 43.7
45.0, 62.6
41.8, 38.8
37.9, 16.2
43.9, 12.1

Taken from various guides (like zygor, joana) it seems like they are fixed spawn points since both of the guides mention 1 particular spawn point (55.7, 27.3)

[Old Github issue](https://github.com/Atlantiss/NetherwingBugtracker/issues/212)

I checked with Katsul if they are in the world at all and it seems like that they are not visible/not spawning?!

**Current behaviour**:
Do not spawn or are not visible at all 9 spawn locations.

**Expected behaviour**: 
Keg is supposed to spawn at following locations:
57.2, 9.0
55.8, 20.
55.7, 27.3
54.7, 37.2
56.5, 43.7
45.0, 62.6
41.8, 38.8
37.9, 16.2
43.9, 12.1

**Server Revision**: 
2282

**Comment by Shanghi** [comment]
Oh, I understand now! Some proof will be needed though. I couldn't find much after going through hundreds of comments and searching for guides that talk about it. The evidence I've found isn't very strong for either case, but I still think it's leaning towards being pooled so far.

Evidence for being pooled:
![image](https://user-images.githubusercontent.com/2672633/49346609-f4daad80-f662-11e8-851e-5a27e11f0b0e.png)
![image](https://user-images.githubusercontent.com/2672633/49346668-c3161680-f663-11e8-8fcb-7bd684fe828e.png)

Evidence for being in all places:
![image](https://user-images.githubusercontent.com/2672633/49346636-57cc4480-f663-11e8-8e95-0401479896a4.png)

**Comment by aresbrutus** [comment]
Maybe the minimal amount spawned at a time could be higher? Like 3/9 at all times? Bottle in STV works the same for example + it starts a quest so it doesn't have to be too rare. 

But the choice is up to you ofcourse. But I also believe it should be pooled and not fixed spawns.

**Comment by Shanghi** [comment]
Yes, I was thinking about that after seeing the first comment and it would make sense, especially for such a big zone! I'll do that if no better proof is found soon.

**Comment by Shanghi** [comment]
The minimum that are spawned at once will be raised in revision 2438 since that's how some similar objects work, but if anyone has proof about this specific object working differently then just reopen this and it will be changed!
