### ISSUE TITLE
[NPC] Chrono lord Deja Heroic

### ISSUE THREAD

**Issue by Anselm123** [Atlantiss/NetherwingBugtracker#3203]
http://wowwiki.wikia.com/wiki/Chrono_Lord_Deja

https://www.wowhead.com/npc=17879/chrono-lord-deja#comments

![image](https://user-images.githubusercontent.com/36844570/49344454-9d930800-f677-11e8-8a90-1477ba8caec4.png)

**Description**:  A bit wonky compared to what he should have

**Current behaviour**: 
level 73
doesn't pull you in
Randomly drops aggro and focuses on someone 

**Expected behaviour**:  I was under the impression that 5 man bosses were 72 iirc
Is meant to have a magnetic pull ability or arcane blast
No mention anywhere of a threat wipe/focus ability

**Server Revision**:

**Comment by killablink** [comment]
Boss is 72
https://www.youtube.com/watch?v=lYLdDZrD3DU
https://youtu.be/lYLdDZrD3DU?t=103

It's the second time I see a report about bosses being 73 instead of 72, are other bosses like this or is it something about 2.0 having an extra level or something?

**Comment by Anselm123** [comment]
No it wasn't over aggro, don't have any proof of that unfortunately but it was almost like he just ignored the aggro table and ran after whoever. When he dropped from me I was still top on omen

**Comment by Easyfraggy** [comment]
> http://www.blizzardguides.com/burning-crusade/black_morass.html
> from march 2007 patch 20.10

What is it in this guide you want us to read?

**Comment by Drayo** [comment]
As for the Magnetic pull: https://www.wowhead.com/npc=17879/chrono-lord-deja#comments

> Heroic Ability: Chrono Lord Deja will perform a "Yank" (a-la-heroic blood furnace's last boss, or the teleport party spell of Grandmaster Vorpil (shadow labs)) to the whole party, dragging them in shortly before he does an arcane explosion-type spell. This is easily avoidable by immediately running out, and keeping max range.

while wowpedia says:

>  Attraction — Chrono Lord Deja pulls in all players within 50 yards. 

This video shows the Magnetic Pull: https://youtu.be/qbgnxUxHz7o?t=212

**Comment by Evolvee** [comment]
level corrected in rev 2827

**Comment by KarlDenXII** [comment]
This boss is still bugged, needs to be fixed.

**Comment by Easyfraggy** [comment]
How is it bugged? Just saying its bugged doesn't help us.

**Comment by devo6969** [comment]
I don't see any bugs on this boss. Probably fixed
