### ISSUE TITLE
[Raid][Boss] Corpse despawns quickly after all loot is distributed

### ISSUE THREAD

**Issue by manslaughter** [Atlantiss/NetherwingBugtracker#3204]
[//]: # (Enclose links to things related to the bug using http://wowhead.com or any other TBC database.)
[//]: # (You can use screenshot ingame to visual the issue.)
[//]: # (Write your tickets according to the format:)
[//]: # ([Quest][Azuremyst Isle] Red Snapper - Very Tasty!)
[//]: # ([NPC] Magistrix Erona)
[//]: # ([Spell][Mage] Fireball)
[//]: # ([Npc][Drop] Ghostclaw Lynx)
[//]: # ([Web] Armory doesnt work)
[//]: # (To find server revision type `.server info` command in the game chat.)

**Description**: This is pedantic but when a boss dies we like to line up for a screenshot with the corpse.

**Current behaviour**: As soon as all loot is distributed, you have a very short time until the corpse despawns.

**Expected behaviour**: Corpse should persist for at least a few minutes.

**Server Revision**: 2382

**Comment by Wolffenstein** [comment]
Any specific boss you encountered it on?

**Comment by manslaughter** [comment]
This was Prince in Karazhan.

**Comment by devo6969** [comment]
Seems fixed couldn't recreate
