### ISSUE TITLE
[NPC] Lady Vashj

### ISSUE THREAD

**Issue by Ensipidx** [Atlantiss/NetherwingBugtracker#3205]
**Description**: Toxic Spore Cloud from sporebats in phase 3 tick rate is too slow.

**Current behaviour**: Seemingly ticking at once every 3 seconds.

https://clips.twitch.tv/SquarePlumpSquirrelRedCoat Shaman only getting hit by the initial tick that goes out upon landing, tick rate too slow that he doesn't take any more damage.

**Expected behaviour**: Toxic Spore Clouds should tick every 1 second and include the initial tick on landing.

https://youtu.be/Udlfkvaq1F8?t=733 Melee stack gets rooted and rogue takes 3 ticks of poison before he vanishes out.

**Server Revision**: 2382

**Comment by Wolffenstein** [comment]
Fixed in rev 2385
