### ISSUE TITLE
[NPC] Lady Vashj

### ISSUE THREAD

**Issue by Ensipidx** [Atlantiss/NetherwingBugtracker#3206]
**Description**: Static Charge should still exist in phase 3.

**Current behaviour**: It was just changed to not happen in phase 3.

**Expected behaviour**: It exists while shes active.

https://youtu.be/Udlfkvaq1F8?t=693

Rogue PoV has both timers showing that static charge is going out and also at the timestamp she turns around and does a lightning spell cast animation (show its not just a bugged boss mod tracking)

**Server Revision**: 2382

**Comment by Wolffenstein** [comment]
Sorry, the changelog was incorrect. I meant to type Forked Lightning. Static Charge will still be casted in Phase 3.
