### ISSUE TITLE
[Item]Lightfathom Scepter#30108 missing patch 2.2 update

### ISSUE THREAD

**Issue by Tenoutoften** [Atlantiss/NetherwingBugtracker#3208]
**Expected behavior:**
This item receives an additional update in patch 2.2
https://web.archive.org/web/20071001225940/http://wow.allakhazam.com:80/db/item.html?witem=30108
![03a4e1bbc65141260d96803855b5450c](https://user-images.githubusercontent.com/34839199/49346439-c8d72080-f692-11e8-9a37-526f4ffb46f0.png)

**Comment by Tenoutoften** [comment]
@aresbrutus

**Comment by aresbrutus** [comment]
Fixed in rev `Nariman`
