### ISSUE TITLE
[World Boss] [Doomwalker]

### ISSUE THREAD

**Issue by Drayo** [Atlantiss/NetherwingBugtracker#3209]
[//]: # (Enclose links to things related to the bug using http://wowhead.com or any other TBC database.)
[//]: # (You can use screenshot ingame to visual the issue.)
[//]: # (Write your tickets according to the format:)
[//]: # ([Quest][Azuremyst Isle] Red Snapper - Very Tasty!)
[//]: # ([NPC] Magistrix Erona)
[//]: # ([Spell][Mage] Fireball)
[//]: # ([Npc][Drop] Ghostclaw Lynx)
[//]: # ([Web] Armory doesnt work)
[//]: # (To find server revision type `.server info` command in the game chat.)

Summary:

- When he is alive, all mobs within his patrol area should die and possibly not respawn until he is killed.

- **Doomwalker should have 2.3 Million HP.**

- **His melee damage should be around 15k -18k.**

- His items should be BoP.

- He should drop less than 500G.

- [Earthquake](https://www.wowhead.com/spell=32686/earthquake), 1 minute cooldown, 8000 physical damage over 4 ticks (2000 each), NOT reduced by armor. Each damage tick comes with a resistible knockdown, debuff of the knockdown must be hidden.

- [Speed Buff](https://www.wowhead.com/spell=32636/overrun), 40 seconds cooldown, triggers [Overrun](https://www.wowhead.com/spell=32637/overrun). Overrun does 1000-1500 damage and knocks players far back, completely resets threat. He targets random players aside from the tank.

- [Chain Lightning](https://www.wowhead.com/spell=28167/chain-lightning) is working properly, it should not target the tank.

- [Crush Armor](https://www.wowhead.com/spell=33661/crush-armor) debuff should last 60s and reduce armor by 10% per stack, it should stack up to 10 times.

- Enrage at 20% increasing his physical damage by 100%, pre-nerf it should include the damage of Earthquake and Overrun.

- He should cast Earthquake from time to time while patrolling.

**Expected behaviour in more detail**: 

- **Doomwalker should have 2.3 Million HP**

- **His melee damage should be around 15k -18k**

Wowhead mentions 15k on the tank while enraged, tanks have over 50% damage mitigation so it was most likely higher than 30k unmitigated while enraged, wowwiki says 6-8k on a Tank which puts in somewhere between 15 and 18k for normal un-enraged attacks.

- He should drop around 500G (or less in 2.0 since 2.4 increased his gold drop(same for Kazzak), players in wrath and later loot 500g in videos)

- His items should be BoP until 2.4, just like Kazzaks.

- His [Earthquake](https://www.wowhead.com/spell=32686/earthquake) should have a cooldown of 1 minute.

- Earthquake should do 2,000 physical damage every 2 seconds (total 8,000 physical damage) **and must not be reduced by armor.** (Other stuff like Shadowform and Defensive Stance should reduce it)

**Earthquake should have a chance to trigger a knockdown on every one of those four damage ticks. 
This is how I guess it should work from watching some videos. In videos players get knocked down 0,1,2 or 3 times (I did not see 4), it seems random, very high level players in later expansions soloing him do not seem to get knocked down at all, or just once on each quake. Either the knockdown is resistible or it does not trigger with 100% certainty on every tick, the high level player thing seems to point to the latter. The Knockdown is something like [this](https://www.wowhead.com/spell=22592/knockdown#used-by-npc), but I cannot find anything associated with his quake spell. This debuff must be invisible.**

**One more thing, wowwiki tactics mention the knockdown being avoidable by having a shield, I assume a priest shield, that would mean it only knocks you down if you actually take the damage. Players on flying mounts should get the damage but no knockdown.**

- His [Overrun](https://www.wowhead.com/spell=32637/overrun) should be triggered by his [Speed buff](https://www.wowhead.com/spell=32636/overrun) and have a cooldown of 40 seconds.

Overrun should do some physical damage, knock players back increase his movement speed by 100% for 5s and reset his aggro table. Aside from the movement speed, it seems to work well, it was very hard to see if he got increased speed on our test. It seems he should target a random ranged player.

- His [Chain Lightning](https://www.wowhead.com/spell=28167/chain-lightning) should have a cooldown of around 5-10 seconds.  I saw him casting Chain Lightning in a video at 50s , 1m, 1m20s, 1m33s 1m46s. It seems to work well on NW.

Small mention: Some players believe Chain Lightning should be able to kill the entire raid at once if everybody stands too close, but the Spell seems to have a target limit on wowhead, additionally, the fact that it doubles the damage on each jump would lead to some VERY UNREASONABLE numbers when it reaches 20+ players (at 30 jumps we are in the trillions and that would be dumb as fuck). Bottom line, the target limit is correct as it is right now.

- [Crush Armor](https://www.wowhead.com/spell=33661/crush-armor) should have a low cooldown of around 5-10 seconds (that, or it has a chance on hit, I saw him apply it in <10 second intervals and also >20 seconds in between casts)

**WoWhead description says "Reduces the target's armor by 10% for 1 min. Stacks up to 10 times."** 
The Spell  on NW only stacks up to 5 (even on the actual wowhead spell) but it must have gotten changed at some point, in the video below you can see someone get 9 Stacks, implying it should stack up to 10. In the video you only see a duration of 30s, wowhead says 1 minute but I cannot find any proof for that.

- Enrage is used at 20% and increases all of his physical damage by 100%.

**Before a hotfix on 17.02.2007 it also increased the damage of his physical abilities (Earthquake and Overrun), after that it only doubled his melee damage. This meant you had to wait for a quake before you push him under 20%, then you had one minute to kill him or he would use an earthquake for 16k damage and kill the raid.**
I think this is a very important part of his "pre-nerf" state because it forces players do kill him properly, On most servers guilds can cheese him with 10 man groups in the middle of the night, makes him very boring tbh, with his enrage affecting quake, low dps raids cannot kill him that easily.

**Early in TBC he was patrolling Shadowmoon Valley, using his quake from time to time, killing everything around him (RP fluff). I cannot find his old path anywhere, maybe someone else can find it though.**
Later in TBC he just patrols at BT and uses his Earthquake from time to time. When he is alive, all mobs within his patrol area should die and possibly not respawn until he is killed.

His RP yell lines are:
Aggro:
* Do not proceed. You will be eliminated.
Earthquake:
* Tectonic disruption commencing.
* Magnitude set. Release.
Overrun:
* Trajectory locked.
* Engage maximum speed.
Slaying:
* Threat level zero. (This might be on reset, wowhead comment and wiki say different things)
* Directive accomplished.
* Target exterminated.
Death:
* System failure in five... f-o-u-r...

Sources:

Mentions 2 300 000k Health approximation
https://www.wowhead.com/npc=17711/doomwalker#comments
Video Shows 2.25m but eh
https://youtu.be/MVi-V1c9uZk?t=178

21227 dmg hit, crushing I assume, roughly 15k assuming 10% reduction from armor
https://www.youtube.com/watch?v=iZ5v4VSLXRs

German but mentions 5-6k on 16-17k armor tank (points to 15k again)
Also mentions a 21k crit which (assuming cloth gear) means 15k hits
http://wowdata.buffed.de/npc/Verdammniswandler-17711#comments

"(11-15K normal hits on plate, and that's before any Crush Armors)"
assuming at least 50% damage reduction this means 30k+ hits during enrage
https://www.wowhead.com/npc=17711/doomwalker#comments

Crush Armor at 9x and no knockdown on players over lvl 70
https://www.youtube.com/watch?v=MMgdY4FB-aM 

Old reupload, random knockdowns can be seen here (sometimes 3 sometime 0)
https://www.youtube.com/watch?v=egxseYhpXmw

If you need any fruther proof or info I can have a look around. @Evolvee @Easyfraggy

**Server Revision**: 2378

**Comment by Easyfraggy** [comment]
To add to this - he used overrun on the tank currently - should not use it on anyone in melee range - random ranged target.

**Comment by Evolvee** [comment]
did u retest it after latest fix?

**Comment by Evolvee** [comment]
did anyone try him?

**Comment by Drayo** [comment]
**Remaining issues:**

- Crush Armor stacks up to 5, it should stack up to 10.

- Overrun might have the wrong charge. (In videos the target of it gets a MASSIVE knockback while everyone in the path of DW just gets a minor knockback.
(https://www.wowhead.com/spell=32637/overrun)

- Earthquake damage should not be reduced by armor and is missing it's knockdown.(https://www.wowhead.com/spell=32686/earthquake)

- The Knockdown should be a spell like this (https://www.wowhead.com/spell=22592/knockdown#used-by-npc) but no debuff should show. 
_("Effect #2 | Persistent Area Aura: Periodically trigger spell Interval: 2 seconds" part of the Earthquake spell)_

- Earthquake and Overrun damage should double while enraged (sub 20%). (Careful with HP when this is implemented)

- His death Aura does not work, you don't die when you get near him when you have the debuff (application of that one works).

**Comment by Evolvee** [comment]
@Wolffenstein ^^ spell core issues

**Comment by Jseay1313** [comment]
you can currently LOS doomwalkers earthquake and it should always stun unless shielded

**Comment by Evolvee** [comment]
if there are any issues left, comment pls

**Comment by Tenoutoften** [comment]
Unless you guys are doing a custom timer on his respawn, his respawn looks to be 2 days, with 3 days window, Netherwing has set the downtime to be at least 7 days.

This comment stats 58 hours, that would mean it's 2 days until the window opens again if we are to judge this based on all previous knowledge of world boss respawns.
https://www.mmo-champion.com/threads/1123445-Doomwalker-s-spawn-time-Anyone-know
![](https://i.gyazo.com/154eae32e35eae37b81b9d453de586f0.png)

If you search around you can find many people saying 2-4 or 2-5, 3-5 etc. so I think it makes sense that it's 2 days before a window of 3 days open.

**Comment by Evolvee** [comment]
wolf has some research on it, its not a static timer, its random
