### ISSUE TITLE
([NPC] Warlock Pets) 

### ISSUE THREAD

**Issue by yokothan** [Atlantiss/NetherwingBugtracker#321]
[//]: # (Enclose links to things related to the bug using http://wowhead.com or any other TBC database.)
[//]: # (You can use screenshot ingame to visual the issue.)
[//]: # (Write your tickets according to the format:)
[//]: # ([Quest][Azuremyst Isle] Red Snapper - Very Tasty!)
[//]: # ([NPC] Magistrix Erona)
[//]: # ([Spell][Mage] Fireball)
[//]: # ([Npc][Drop] Ghostclaw Lynx)
[//]: # ([Web] Armory doesnt work)

**Description**: pet is attacking while in defensive mode. When you haven't attacked the target yet, as in hostile action targeting.  

**Current behaviour**:

**Expected behaviour**: 

**Server Revision**:

**Comment by wtRCH** [comment]
Probably the same issue is happening for the hunter.

**Comment by Tereneckla** [comment]
#384 is a better report
