### ISSUE TITLE
[Quest] Allegiance to the Aldor

### ISSUE THREAD

**Issue by Shiifa** [Atlantiss/NetherwingBugtracker#3210]
[//]: # (Enclose links to things related to the bug using http://wowhead.com or any other TBC database.)
[//]: # (You can use screenshot ingame to visual the issue.)
[//]: # (Write your tickets according to the format:)
[//]: # ([Quest][Azuremyst Isle] Red Snapper - Very Tasty!)
[//]: # ([NPC] Magistrix Erona)
[//]: # ([Spell][Mage] Fireball)
[//]: # ([Npc][Drop] Ghostclaw Lynx)
[//]: # ([Web] Armory doesnt work)
[//]: # (To find server revision type `.server info` command in the game chat.)

**Description**: The follow-up quest to "City of Light" in Shattrath, "Allegiance to the Aldor," does not give the correct reputation rewards.

**Current behaviour**: After selecting the Aldor as your ally, you inexplicably gain the expected reputation gain with the Scryers and the expected reputation drop with the Aldor.
![allegiance_to_the_aldor](https://user-images.githubusercontent.com/45551268/49354640-b354fd00-f678-11e8-9a95-c03a2696b9e5.png)

**Expected behaviour**:  The reverse reputation allotment should happen instead: https://www.wowhead.com/quest=10551/allegiance-to-the-aldor

**Comment by Wolffenstein** [comment]
That might be due to the beta settings maxing out your reputations.

**Comment by Shanghi** [comment]
Like he said, it's just a beta thing because you started with Scryers being exalted, so Aldor despises you. You did get Aldor reputation, but the measly 3500 from the quest didn't help very much. A GM or most Testers on discord could change it for you if you want.
