### ISSUE TITLE
Devotion Aura removes Scroll of Protection V.

### ISSUE THREAD

**Issue by maidros** [Atlantiss/NetherwingBugtracker#3211]
**Description**: 
Devotion Aura removes Scroll of Protection V.

**Current behaviour**:
I read ticket #3095 regarding this issue and understand that Scroll of Protection V was changed so that it doesn't erase Devotion Aura - however now, applying Devotion Aura removes Scroll of Protection V, yet you can still reapply Scroll of Protection again immediately after this.

**Expected behaviour**: 
If both are supposed to stack, as the discussion in #3095 indicates, then reapplying Devotion Aura should not remove Scroll of Protection V as it currently does.

**Comment by maidros** [comment]
no, it's not a duplicate.

the other thread was addressing how scroll removes devo. after that issue was closed, this issue still persists - devo removes scroll.

it's a bug that is happening on the beta right now.

**Comment by Easyfraggy** [comment]
![image](https://user-images.githubusercontent.com/36134067/49362797-0a41ed00-f6e0-11e8-8412-dbc38ad1c0a3.png)

And its not closed - it's still open...

**Comment by maidros** [comment]
ah, i missed the end, the new behavior is addressed in that ticket. my bad.
