### ISSUE TITLE
[item] Netherwave Net

### ISSUE THREAD

**Issue by Zebhor** [Atlantiss/NetherwingBugtracker#3213]
[//]: # (Enclose links to things related to the bug using http://wowhead.com or any other TBC database.)
[//]: # (You can use screenshot ingame to visual the issue.)
[//]: # (Write your tickets according to the format:)
[//]: # ([Quest][Azuremyst Isle] Red Snapper - Very Tasty!)
[//]: # ([NPC] Magistrix Erona)
[//]: # ([Spell][Mage] Fireball)
[//]: # ([Npc][Drop] Ghostclaw Lynx)
[//]: # ([Web] Armory doesnt work)
[//]: # (To find server revision type `.server info` command in the game chat.)

**Description**: 
Netherwave Net stacks

**Current behaviour**:
Netherwave Net stack at 20

**Expected behaviour**: 
Netherwave Net should stack at 10

https://www.wowhead.com/item=24268/netherweave-net#comments:id=215189
Stacksize changed it 2.3.2, it's now 20 instead of 10.

**Server Revision**: 
2382

**Comment by wtRCH** [comment]
@aresbrutus

**Comment by Manaci** [comment]
Irrelevant now

**Comment by Evolvee** [comment]
this will need to be fixed for future
