### ISSUE TITLE
Tailoring specialization(s)

### ISSUE THREAD

**Issue by ircfelix** [Atlantiss/NetherwingBugtracker#3215]
**Description**: 
In TBC tailoring you can learn one of three specializations.

**Current behaviour**:
When you unlearn tailoring after learning a specialization, you still have the specialization in your spell book. This allows you to tailor your specialization set first (e.g. spellfire set), unlearn tailoring and still use the specialization set afterwards. I did not try yet if you can also learn a second specialization by relearning tailoring again.

**Expected behaviour**: 
If you unlearn tailoring, your specialization should also be removed.

**Server Revision**:

**Comment by Consita** [comment]
server rev: 3482
unlearning tailoring also removes the spec.

can be closed
