### ISSUE TITLE
[Spell][Hunter] Kill Command bug

### ISSUE THREAD

**Issue by sweetbakery** [Atlantiss/NetherwingBugtracker#3216]
[//]: # (Enclose links to things related to the bug using http://wowhead.com or any other TBC database.)
[//]: # (You can use screenshot ingame to visual the issue.)
[//]: # (Write your tickets according to the format:)
[//]: # ([Quest][Azuremyst Isle] Red Snapper - Very Tasty!)
[//]: # ([NPC] Magistrix Erona)
[//]: # ([Spell][Mage] Fireball)
[//]: # ([Npc][Drop] Ghostclaw Lynx)
[//]: # ([Web] Armory doesnt work)
[//]: # (To find server revision type `.server info` command in the game chat.)

**Description**: Kill Command is not dealing damage when the pet is set to passive mode.

**Current behaviour**: Kill Command is not doing damage If pet is set to passive mode.

**Expected behaviour**: Kill Command should always do damage, It doesn't matter the pet condition.

**Server Revision**: 2382.

**Comment by sweetbakery** [comment]
Update: the problem is ever worse.

Actually, there are more problems related to Kill Command.

**If the pet is set to passive mode, dead or out of range, Kill Command is triggered however It doesn't damage the enemy target.**

I tested It just now!

**Comment by sweetbakery** [comment]
Update 2: Kill Command is absolutely bugged.

**I tested more situations after I realized the problems mentioned in the first update. Even in Aggresive Mode, _sometimes_ when I use Kill Command, It doesn't damage the target! Even in Combat state. The spell is triggered, the sound effect played, however no damages lands the target.** 

My advice is to rewrite all the spell.

**Comment by Easyfraggy** [comment]
Please use the search function before posting. https://github.com/Atlantiss/NetherwingBugtracker/issues/2709
