### ISSUE TITLE
[Dungeon][NPC][Drop] Lieutenant Drake wrong drops on HC

### ISSUE THREAD

**Issue by Many12997** [Atlantiss/NetherwingBugtracker#3217]
[//]: # (Enclose links to things related to the bug using http://wowhead.com or any other TBC database.)
[//]: # (You can use screenshot ingame to visual the issue.)
[//]: # (Write your tickets according to the format:)
[//]: # ([Quest][Azuremyst Isle] Red Snapper - Very Tasty!)
[//]: # ([NPC] Magistrix Erona)
[//]: # ([Spell][Mage] Fireball)
[//]: # ([Npc][Drop] Ghostclaw Lynx)
[//]: # ([Web] Armory doesnt work)
[//]: # (To find server revision type `.server info` command in the game chat.)

**Description**: 
[NPC] Lieutenant Drake seems to drop items from NORMAL difficulty on HEROIC mode
![wowscrnshot_120318_163610](https://user-images.githubusercontent.com/45187634/49387699-c9b79300-f722-11e8-810d-a79c59efbd23.jpg)

Here also screens with drops from other bosses as proof that it was on HEROIC mode
![wowscrnshot_120318_164651](https://user-images.githubusercontent.com/45187634/49387759-f5d31400-f722-11e8-9390-79fea1bd83ce.jpg)

![wowscrnshot_120318_165853](https://user-images.githubusercontent.com/45187634/49387773-008da900-f723-11e8-896a-16a10e070490.jpg)

Lieutenant Drake loot table 
NORMAL: https://tbc-twinhead.twinstar.cz/?npc=17848
HEROIC: https://tbc-twinhead.twinstar.cz/?npc=20535
**Current behaviour**:
Lieutenant Drake drops normal mode items on heroic
**Expected behaviour**: 
Lieutenant Drake should drop heroic mode rewards on heroic mode
**Server Revision**: 
2328

**Comment by Shanghi** [comment]
This should be fixed after revision 2525.
