### ISSUE TITLE
[Misc][Quest]Alien Egg#4821 turn in RP seems broken/missing

### ISSUE THREAD

**Issue by Tenoutoften** [Atlantiss/NetherwingBugtracker#3219]
**Description/Current behaviour**: 
[[Quest]Alien Egg#4821](https://www.wowhead.com/quest=4821/alien-egg) has broken RP on turn in.
When I turned it in the dog critter died(Might have been a coincidence) and a red serpent spawned and immediately despawned.

**Expected behaviour**: 
https://youtu.be/0YZufzs6aw0?t=199 

**Server Revision**: 
2382

**Comment by Evolvee** [comment]
The event works fine for me, the only thing i need to add is the egg at the beggining.

**Comment by Evolvee** [comment]
fixed in next rev
