### ISSUE TITLE
[Core Mechanic] Time between killing blow and death of mob

### ISSUE THREAD

**Issue by killablink** [Atlantiss/NetherwingBugtracker#322]
**Description**: Right now because of spell batch(?) or however the server is, it takes way too long for the server to update from killing blow --> death animation

**Current behaviour**: After dealing a killing blow with a spell, you see the damage, then around .4 seconds until the mob actually dies
https://gfycat.com/IncredibleDrearyComet

**Expected behaviour**: The time between that should be a lot shorter
https://youtu.be/YdurLnYW9Yo?t=28
https://youtu.be/0SPfKwiU_n4?t=41
https://youtu.be/nZ4QqxKvdSA?t=33

**Server Revision**: 2040

**Comment by wtRCH** [comment]
It's intended, working properly.

**Comment by Searcher314** [comment]
> It's intended, working properly.

Is this for real? I was about to report this as well. It absolutely isn't how things "worked" during TBC. There are so many bugs mob AI and combat in general it's honestly overwhelming to start sitting down and reporting them all. Then I see a response like this and it makes me want to give up before I've even started.

**Comment by killablink** [comment]
Can I know how it is intended and working properly? If it's supposed to be "blizzlike" why is it not nearly the same as the ones in these videos?

Compare this from the server from any of the clip I linked:
https://gfycat.com/IncredibleDrearyComet

If it's intended to be working badly then yes sure it's working as intended but don't go on and close a ticket like that

**Comment by Godmatik** [comment]
> It's intended, working properly.

I noticed this slight 'delay' between final blow and death animation as well, and I don't recall it at all from TBC, can you look into it again?

**Comment by tcberk12** [comment]
@Searcher314 please report your bugs related to mob AI and combat.

**Comment by Evolvee** [comment]
https://github.com/Wolffenstein/NetherwingSecretBugtracker/issues/6

**Comment by paoea** [comment]
With a Voidwalker it's really weird to see that the mob is still standing but the Voidwalker is already walking back to me

**Comment by Wolffenstein** [comment]
Fixed in rev 2067.
