### ISSUE TITLE
[Spell][Hunter] Feed Pet

### ISSUE THREAD

**Issue by sweetbakery** [Atlantiss/NetherwingBugtracker#3220]
[//]: # (Enclose links to things related to the bug using http://wowhead.com or any other TBC database.)
[//]: # (You can use screenshot ingame to visual the issue.)
[//]: # (Write your tickets according to the format:)
[//]: # ([Quest][Azuremyst Isle] Red Snapper - Very Tasty!)
[//]: # ([NPC] Magistrix Erona)
[//]: # ([Spell][Mage] Fireball)
[//]: # ([Npc][Drop] Ghostclaw Lynx)
[//]: # ([Web] Armory doesnt work)
[//]: # (To find server revision type `.server info` command in the game chat.)

**Description**: Feed Pet should feed my pet with food If It has lower (but not too many) or equal level, increasing loyalty and giving Training Points.

**Current behaviour**:  If I give a food that holds higher level than my pet and try to use Feed Pet on this item, the spell is triggered and nothing happens. (Loyalty is not increased, Training Points not given and so on).

The problem is: the spell should not be triggered and an error message should appear!

**Expected behaviour**: If I give a food that holds higher level than my pet and try to use Feed Pet on this item, an error message should appear and the spell should not be triggered.

**Server Revision**: 2382

PS: It's a confirmed bug that I tested today. My pet is level 64 and I gave him level 70 and 75 foods.

**Comment by Easyfraggy** [comment]
https://github.com/Atlantiss/NetherwingBugtracker/issues/1917
