### ISSUE TITLE
[Misc][Quest]Testing the Tonic#9434 missing RP animations when turned in & NPC doesn't transform fast enough back to original form

### ISSUE THREAD

**Issue by Tenoutoften** [Atlantiss/NetherwingBugtracker#3221]
**Description**: 
NW's RP when turning in [[Quest]Testing the Tonic#9434](https://www.wowhead.com/quest=9434/testing-the-tonic) lacks
* Drinking animation
* Stun animation after transformation
* Takes too long before the NPC transforms back again(When it transforms back it should still be under stun animation)

[NW](https://www.youtube.com/watch?v=R_aDQm_-nh8&feature=youtu.be)
[Retail]https://youtu.be/Y9uZQ7e8SVM?t=45

**Current behaviour**:
Lacks animations

**Expected behaviour**: 
Expect provided animations

**Server Revision**: 
2382

**Comment by Kiperr** [comment]
Corrected version send to Kutasal

**Comment by aresbrutus** [comment]
Fixed in rev `Nariman `thanks to Kiper.
