### ISSUE TITLE
[Spell][Hunter] Multi shot

### ISSUE THREAD

**Issue by Sylldran** [Atlantiss/NetherwingBugtracker#3222]
**Description**:  Multi shot outranges the 41 yards maximum. 

**Current behaviour**:    Tested on the dummies in Shattrath, standing  at 41 yards from the closest one, in a direct line of a row of target dummies. Sending a Multi Shot targeting the closest dummy, at 41yd, the 2 other missiles strike the 2 next dummies in the line, which are at a distance, greater than 41yd.

**Expected behaviour**:  Should not hit any targets out of range. 

![wowscrnshot_120318_184402](https://user-images.githubusercontent.com/45574077/49396882-dcda5b00-f742-11e8-9956-6ddce54750e5.jpg)

**Server Revision**:

**Comment by Easyfraggy** [comment]
proof?

**Comment by nullfoxh** [comment]
I believe he means proof that it shouldn't hit the two dummies out of range.

**Comment by Jezofine** [comment]
Does [Vanilla video](https://youtu.be/QQ2A0SVGt6Q?t=121) count? Hunter kites boss in a large semicircle in range of his abilities. I think dwarves and elementals down the stairs could be slightly out of range, but they are not affected by multi-shots. Specifically at 2:05 (first link) and [2:25](https://youtu.be/QQ2A0SVGt6Q?t=143).
Delete if it's not enough proof.

**Comment by Wolffenstein** [comment]
Fixed in rev 2428.
