### ISSUE TITLE
[NPC][Dungeon] Bonechewer Ravener

### ISSUE THREAD

**Issue by Many12997** [Atlantiss/NetherwingBugtracker#3223]
[//]: # (Enclose links to things related to the bug using http://wowhead.com or any other TBC database.)
[//]: # (You can use screenshot ingame to visual the issue.)
[//]: # (Write your tickets according to the format:)
[//]: # ([Quest][Azuremyst Isle] Red Snapper - Very Tasty!)
[//]: # ([NPC] Magistrix Erona)
[//]: # ([Spell][Mage] Fireball)
[//]: # ([Npc][Drop] Ghostclaw Lynx)
[//]: # ([Web] Armory doesnt work)
[//]: # (To find server revision type `.server info` command in the game chat.)

**Description**: 
https://www.wowhead.com/npc=17264/bonechewer-ravener#drops:mode=heroic
NPC's inside Hellfire Ramparts dungeon named Bonechewer Ravener's have way to high damage on hit.
Not always,but some of them were able to oneshoot our paladin tank with 14k hp and t4 full set.
I inspected his items and i believe he was def cap (i doubt it's relevant here anyway).
Also I've noticed that Curse of Weakness somehow bring down these absurdal damage values back to normal (3k dmg on main hand melee and 2k-2.5k on off hand melee).
Unfortunetly due to combat log bug(or is it?) we were unable to catch it on screen.
**Current behaviour**:
Some of Bonechewer Ravener's hits for 8k with both main hand and off hand melee attacks,crits up to 15k-16k dmg
**Expected behaviour**: 
Bonechewer Ravener's Should hit with melee attack for ~3k dmg with main hand and ~2k-2.5k dmg with off hand
Proof: https://www.wowhead.com/npc=17264/bonechewer-ravener#comments
(top comment)
**Server Revision**: 
2382

**Comment by Easyfraggy** [comment]
![image](https://user-images.githubusercontent.com/36134067/49407533-3483c100-f759-11e8-99b2-5eb92650652b.png)

Hits for correct damage on blue geared tank.
