### ISSUE TITLE
[Spell][Warlock] Eye of Kilrogg "ding" effect on summon

### ISSUE THREAD

**Issue by feuerkind** [Atlantiss/NetherwingBugtracker#3225]
**Description**: 
Eye of Kilrogg gets a leveling up animation when summoned.
**Current behaviour**:
![lx5vcwbsrh](https://user-images.githubusercontent.com/13179578/49406164-1025e580-f755-11e8-893d-57cacdbcd09f.gif)
**Expected behaviour**: 
https://youtu.be/Pdn-IaYXfFc?t=30
**Server Revision**: 
2382

**Comment by Wolffenstein** [comment]
Fixed in rev 2389.
