### ISSUE TITLE
[NPC][Dungeon] Slave Pens heroic stuck in combat after being mind controlled

### ISSUE THREAD

**Issue by tepex0** [Atlantiss/NetherwingBugtracker#3226]
**Description**: If you are mind controlled during slave pens heroic you can get stuck in combat after all mobs are dead

**Current behaviour**:Some party members stay in combat after the mobs are dead after being mind controlled in slave pens heroic - https://youtu.be/PWpebojIhMA?t=1264

**Expected behaviour**: Should drop combat after all enemies are dead

**Server Revision**: 2382

**Comment by Tenoutoften** [comment]
[2423][Core] Units should no longer stay in combat with mind control targets after the effect ended
retest?

**Comment by Godmatik** [comment]
Already fixed
