### ISSUE TITLE
[Dungeon][Steam Vaults] Coilfang Engineer entering fight late

### ISSUE THREAD

**Issue by feuerkind** [Atlantiss/NetherwingBugtracker#3228]
**Description**: 
It takes the Coilfang Engineer about 20 seconds to join the fight from behind the pillar. Possibly he is getting stuck on something on the way. Could not see.
**Current behaviour**:
https://youtu.be/ibhmzCeWtS8?t=742
**Expected behaviour**: 
Starting to run towards the group immediately.
**Server Revision**: 
2382

**Comment by Easyfraggy** [comment]
https://github.com/Atlantiss/NetherwingBugtracker/issues/3165
