### ISSUE TITLE
[NPC][Dungeon]Heroic Underbog Underbat patrol gets stuck

### ISSUE THREAD

**Issue by tepex0** [Atlantiss/NetherwingBugtracker#3229]
**Description**: One of the three Underbats that patrols on the spiral ramp before the first boss in heroic Underbog did not move after we aggroed the patrol.

**Current behaviour**:At 10:20 you can see the patrol of 3 Underbats aggro, and at 10:40 you can see one of the Underbats sitting on the ramp not moving. It was targeting Lexxa who was barely standing in the water, not swimming.

https://youtu.be/0MZmRcF1gvg?t=640

**Expected behaviour**: Shouldn't afk on the ramp

**Server Revision**: 2382

**Comment by Easyfraggy** [comment]
possibly bad mmaps near the water?

**Comment by feuerkind** [comment]
I'm pretty sure it is stuck between those mushrooms. All mobs throughout the dungeon seem to have difficulties with going past / through those but at least they don't usually get stuck.

**Comment by devo6969** [comment]
I tried recreating the events of the priest getting Healing aggro and bugging out the mob but was unable to. However after doing testing for 15 mins I was able to manage getting one Sporebat stuck for only a few seconds and then it would auto reset.
https://www.youtube.com/watch?v=WOqeI_Isfrk
