### ISSUE TITLE
[Quest][Ghostlands] Escape from the Catacombs

### ISSUE THREAD

**Issue by Thugli** [Atlantiss/NetherwingBugtracker#323]
[//]: # (Enclose links to things related to the bug using http://wowhead.com or any other TBC database.)
[//]: # (You can use screenshot ingame to visual the issue.)
[//]: # (Write your tickets according to the format:)
[//]: # ([Quest][Azuremyst Isle] Red Snapper - Very Tasty!)
[//]: # ([NPC] Magistrix Erona)
[//]: # ([Spell][Mage] Fireball)
[//]: # ([Npc][Drop] Ghostclaw Lynx)
[//]: # ([Web] Armory doesnt work)

**Description**: 
For the first half of the escort, Ranger Lilatha wasn't helping me fight off mobs and kept walking past me fighting them. Only once I got out of the cave she started engaging in combat and helping me fight the mobs. 

**Current behaviour**:
NPC doesn't help kill mobs for part of the escort, and continued walking while I was killing these mobs. I was aggroing and killing mobs that the npc was about to pat into, it's possible this bug only occurs when the player gains initial aggro, though I am not too sure.

**Expected behaviour**: 
The npc should assist the player fight off enemies and not simply walk off

**Revision**:

**Comment by Perturabo** [comment]
While it is supremely annoying, this is how it used to work on retail. You always had to let them aggro the mobs before attacking them.

**Comment by deku100** [comment]
Also during the last "troll ambush," the Oracle didn't bother attacking either of us.
![wowscrnshot_092518_002751](https://user-images.githubusercontent.com/43505181/45992974-735f1180-c05a-11e8-85cc-f9644aeeb024.jpg)

**Comment by tcberk12** [comment]
> While it is supremely annoying, this is how it used to work on retail. You always had to let them aggro the mobs before attacking them.

I don't think this is true. 

https://www.youtube.com/watch?v=7eVju9ndvBE

Watch from 2:20 on, the player engages several defias first, but the Defias Traitor engages still.

**Comment by aresbrutus** [comment]
https://github.com/Atlantiss/NetherwingBugtracker/issues/3678
