### ISSUE TITLE
[Dungeon][The Underbog]The Black Stalker random targets for Chain Lightning

### ISSUE THREAD

**Issue by feuerkind** [Atlantiss/NetherwingBugtracker#3230]
**Description**: 
She is currently targetting a random player from the group and running towards them while casting Chain Lightning.
This Ability is only supposed to target the tank.
**Current behaviour**:
https://youtu.be/0MZmRcF1gvg?t=3070
**Expected behaviour**: 
https://www.youtube.com/watch?v=8yvnlI8MX-Y
https://www.youtube.com/watch?v=GtFAfZBLsXU
In both videos she exclusively targets the person with aggro. Additionally there is this wowhead comment for confirmation:
![wowheadstalker](https://user-images.githubusercontent.com/13179578/49409144-90e9df00-f75f-11e8-9ec0-c31a2d5330e4.png)
**Server Revision**: 
2382

**Comment by Easyfraggy** [comment]
its a weird new bug - some recent core change made this happen - same thing for Karathress Spear throw.

**Comment by EGSilver** [comment]
Straight from the companion guide - 

Chain lightning; Spell affects up to 5 targets, and deals successively great Nature damage to each affected target. Chain lightning deals about 1800-2200 Nature damage to the first target. Heroic; deals about 2800-3200 Nature damage to the first target on Heroic mode.

The first target being the one with the most aggro.

**Comment by devo6969** [comment]
Can Confirm, its still bugged and it only targets the main tank (Thank you Bamb)

Multiple PoV of Retail TBC
https://www.youtube.com/watch?v=pZpbYLtoCs8
https://www.youtube.com/watch?v=sBUqf59Im4Y
https://www.youtube.com/watch?v=ZUtu9hcSxXQ

**Comment by Wolffenstein** [comment]
Fixed in rev 3443.
