### ISSUE TITLE
[Loot] Murloc Scout dropping green item of equal req level

### ISSUE THREAD

**Issue by sefamurat** [Atlantiss/NetherwingBugtracker#3231]
**Description**:  Murloc Scout mob in Redridge Mountains dropping an item of it's own level.

**Current behaviour**: 19 Level Murloc Scout (https://classic.wowhead.com/npc=578/murloc-scout#drops:mode=noteworthy:100-3-2-18+1) dropped 24 ilvl, 19 req lvl green weapon Decapitating Sword of the Bear (https://classic.wowhead.com/item=3740/decapitating-sword). It was located in murloc camp south of Alther's Mill in Redridge Mountains.

**Expected behaviour**: Ordinary NPC's shouldn't be able to drop items with req. level equal to their own creature level, only lower.

**Server Revision**: 2382

**Comment by The14me** [comment]
rev.3460 Not an issue.
Can be closed.
