### ISSUE TITLE
[NPC] Missing spawn for Great Goretusk

### ISSUE THREAD

**Issue by sefamurat** [Atlantiss/NetherwingBugtracker#3232]
**Description**: Great Goretusk at Redridge Mountains are missing most of their spawns

**Current behaviour**: Great Goretusks (https://classicdb.ch/?npc=547) are only spawning near the graveyard west of Lakeshire.

**Expected behaviour**: They should spawn in other places such as entrance to Burning Steppes and southwest of Lake Everstill

**Server Revision**: 2382

**Comment by Easyfraggy** [comment]
Need better source than classicdb - we don't use private server information for this.

**Comment by sefamurat** [comment]
I tried thottbot archives but the map location jpg was broken, and classic wowhead doesn't have map locations for this npc. I don't know any other reliable databases.

**Comment by wtRCH** [comment]
Videos of passage from Redrige to Burning Steppes. There must be one

**Comment by sefamurat** [comment]
I guess one could pick up the quest and check the mob locations on questhelper addon? I believe questhelper was based on retail data.

**Comment by The14me** [comment]
https://i.imgur.com/4OjXqCq.png Confirm!

**Comment by sefamurat** [comment]
The14me, may i ask what source you used for that map?

**Comment by wtRCH** [comment]
> The14me, may i ask what source you used for that map?

This is our private research. We won't share it.

**Comment by The14me** [comment]
Personal collection of information gathered  through the years.

**Comment by aresbrutus** [comment]
Fixed in rev `Nariman`

**Comment by sefamurat** [comment]
The spawns at westfall are still missing
