### ISSUE TITLE
[Spell][Talent]Fireballs DoT/Empowered Fireball Talent

### ISSUE THREAD

**Issue by ta55el** [Atlantiss/NetherwingBugtracker#3233]
Empowered Fireball talent now scales also Fireball DoT with spell power damage but shouldn't.

**Comment by Tenoutoften** [comment]
Not sure if this helps

[[Spell]Fireball(Rank 13)#27070](https://db.excalibur.ws/?spell=27070) seen ticking for 
 23 [here](https://youtu.be/Y9j4et87GCE?t=102)
He is briefly revealing his talents [here](https://youtu.be/Y9j4et87GCE?t=57), 5/5 [[Spell]Empowered Fireball#31660](https://db.excalibur.ws/?spell=31660)

![c7299f73a4cdb1ea548a5cf2a1277a1b](https://user-images.githubusercontent.com/34839199/49442948-4bfb9200-f7cb-11e8-9ce6-e400d93f5dfd.png)

**Comment by ta55el** [comment]
Fireball DoT without this talent work properly. If we put talents in Empowered Fireball this DoT start scale with spell dmg. I search some video from these days.

**Comment by ta55el** [comment]
https://www.youtube.com/watch?v=S7ak4c2Hgnw
https://www.youtube.com/channel/UC8pGvDXL-CuX--pArPfItXA
It was guild raided on retail

**Comment by Tenoutoften** [comment]
[NW, Fireball DoT w/ 5/5 Empowered Fireball](https://www.youtube.com/watch?v=7LIWL3D-bNg&feature=youtu.be) - ticks for 73 with 1166 fire spell damage

**Comment by ta55el** [comment]
This bug was also on CC server https://github.com/ccshiro/cc-buglist/issues/1848

**Comment by Godmatik** [comment]
Rev 4018 - no longer an issue
Proper spell coefficients were all recently imported from classic - verified that Fireball DOT no longer scales from Empowered Fireball talent
