### ISSUE TITLE
[Quest] The Rethban Gauntlet

### ISSUE THREAD

**Issue by sefamurat** [Atlantiss/NetherwingBugtracker#3237]
**Description**: The Rethban Gauntlet not working properly

**Current behaviour**: After accepting quest, you can die / release spirit and still complete the quest.

**Expected behaviour**: Dying and releasing spirit should make the quest [Failed]. This is stated explicitly in the quest description.

**Server Revision**: 2382

**Comment by Easyfraggy** [comment]
https://github.com/Atlantiss/NetherwingBugtracker/issues/925
