### ISSUE TITLE
[Quest][Terokkar Forest] Escaping from the Tomb - Akuno 

### ISSUE THREAD

**Issue by Firroth** [Atlantiss/NetherwingBugtracker#3238]
**Current behaviour**:
NPC [Akuno ](https://www.wowhead.com/npc=22377/akuno) doesn't assist you in battle if mob will aggro on you, also he doesn't seem to use his spells. He is simply meele'ing mob to death.

**Expected behaviour**: 
He should help player at all times when in combat, and he should use his spell [Chain Lightning ](https://www.wowhead.com/spell=39945/chain-lightning)

Proof: https://www.youtube.com/watch?v=afDQa0UzOp0

**Server Revision**: 
2382

**Comment by Tenoutoften** [comment]
I suppose this is more of a NPC missing spell report rather than a quest report
[NPC]Akuno#22377 missing [Spell]Chain Lightning#39945

**Comment by Evolvee** [comment]
asist is bugged for all escorts, has to be fixed globally

spells added

**Comment by Evolvee** [comment]
rev 2500
