### ISSUE TITLE
[Misc][NPC]Thomas Miller#3518 missing RP text "Fresh bread for sale!"

### ISSUE THREAD

**Issue by Tenoutoften** [Atlantiss/NetherwingBugtracker#3239]
**Description**: 
[[NPC]Thomas Miller#3518](https://www.wowhead.com/npc=3518/thomas-miller#comments) patrolling around in The Trade District in Stormwind doesn't do his RP text "Fresh bread for sale!"
seen [here](https://youtu.be/VX9dTpZFKNQ?t=136)
![d4b6aed9640472284e31e0f8cc6bd58e](https://user-images.githubusercontent.com/34839199/49470745-327a3a80-f80b-11e8-8d7e-817cfe319292.png)

**Current behaviour**:
He does patrol within The Trade District but it looks odd at times, pauses at a few points, at one point he will go back and forth(After he has passed the cheese shop). He pauses at a guard before the ramp to the flight master without turning towards him and hangs there for a few seconds without any dialog.

**Expected behaviour**: 
Expected to do RP text and for his patrol to be more purpose full perhaps

**Server Revision**: 
2382

**Comment by Evolvee** [comment]
fixed
