### ISSUE TITLE
[NPC]Mikhail

### ISSUE THREAD

**Issue by wtRCH** [Atlantiss/NetherwingBugtracker#324]
[//]: # (Enclose links to things related to the bug using http://wowhead.com or any other TBC database.)
[//]: # (You can use screenshot ingame to visual the issue.)
[//]: # (Write your tickets according to the format:)
[//]: # ([Quest][Azuremyst Isle] Red Snapper - Very Tasty!)
[//]: # ([NPC] Magistrix Erona)
[//]: # ([Spell][Mage] Fireball)
[//]: # ([Npc][Drop] Ghostclaw Lynx)
[//]: # ([Web] Armory doesnt work)

**Description**: NPC named Mikhail in Wetlands doesn't offer the quest again when you abandon it. And when you complete the quest you can't turn it in to him.

**Comment by wtRCH** [comment]
![image](https://user-images.githubusercontent.com/11255782/45937254-c4b9c300-bfbe-11e8-8386-4541e5919ded.png)

**Comment by Evolvee** [comment]
what quest

**Comment by Evolvee** [comment]
if you mean tapoke, you need to defeat tapoke, i slightly tweaked the script

should be fine after next hotfix rev
