### ISSUE TITLE
Shattered halls Heroic. FIRST BOSS BUG

### ISSUE THREAD

**Issue by thebigbull** [Atlantiss/NetherwingBugtracker#3240]
**Description**: Bug in first boss encounter

**Current behaviour**: At 25% of his HP boss is not doing the ability Dark spin.
**Expected behaviour**:  When Grand Warlock Nethekurse reaches 25% remaining health, he spins wildly, inflicting Physical damage to all players within 0 yards and hurling bolts of dark magic that inflict Shadow damage.

**Server Revision**:

**Comment by thebigbull** [comment]
Please take a look at this

**Comment by feuerkind** [comment]
#2679

**Comment by wtRCH** [comment]
> #2679

Duplicate
