### ISSUE TITLE
Pet wont attack CC'ed targets while in passive stance.

### ISSUE THREAD

**Issue by dalabu** [Atlantiss/NetherwingBugtracker#3241]
**Description**: If pet is in passive stance it doesn't attack target if target is CC'ed.

**Current behaviour**: As shown on the video.
https://streamable.com/7751x

**Expected behaviour**: Pet should at command attack target even if CC'ed.

**Server Revision**:

**Comment by Easyfraggy** [comment]
https://github.com/Atlantiss/NetherwingBugtracker/issues/456
