### ISSUE TITLE
indoors mounting bug

### ISSUE THREAD

**Issue by sweetbakery** [Atlantiss/NetherwingBugtracker#3243]
[//]: # (Enclose links to things related to the bug using http://wowhead.com or any other TBC database.)
[//]: # (You can use screenshot ingame to visual the issue.)
[//]: # (Write your tickets according to the format:)
[//]: # ([Quest][Azuremyst Isle] Red Snapper - Very Tasty!)
[//]: # ([NPC] Magistrix Erona)
[//]: # ([Spell][Mage] Fireball)
[//]: # ([Npc][Drop] Ghostclaw Lynx)
[//]: # ([Web] Armory doesnt work)
[//]: # (To find server revision type `.server info` command in the game chat.)

**Description**: I can stay mounted indoors.

**Current behaviour**: Indoors are not removing mounting up effect.

**Expected behaviour**: When I get inside somewhere, I should be dismounted instantly just like retail.

**Server Revision**: 2382

**Screenshots**:
My character is at Ship indoors mounted! :0 https://i.imgur.com/wl0oLtR.jpg
After this, I went outside and I was not able to mount again: https://i.imgur.com/cDZcvK3.jpg

There's a video showing how It should work: https://youtu.be/zcMZ6BOTCTs?t=236 (it's not from retail I tried my best to find It).

**Comment by Easyfraggy** [comment]
Would need retail proof for this specific location - dismounting when inside in general works fine it would be specific to that very location.
