### ISSUE TITLE
Pet breaks CC while in aggressive stance.

### ISSUE THREAD

**Issue by dalabu** [Atlantiss/NetherwingBugtracker#3244]
**Description**: While pet is in aggressive stance it doesn't stop auto attacking when target is CC'ed.

**Current behaviour**:As shown on video.
https://streamable.com/1df9e

**Expected behaviour**: Pet needs to stop auto attacking as soon as target gets CC'ed even if pet is aggressive stanced.

**Server Revision**:

**Comment by Manaci** [comment]
Fixed
