### ISSUE TITLE
[NPC]Doom Lord Kazzak#18728 has way too small hit box

### ISSUE THREAD

**Issue by Tenoutoften** [Atlantiss/NetherwingBugtracker#3245]
**Description**: 
[[NPC]Doom Lord Kazzak#18728](https://www.wowhead.com/npc=18728/doom-lord-kazzak#comments) has significantly too small hit box 

**Current behaviour**:
[NW hit box](https://www.youtube.com/watch?v=spcmPoT1hao&feature=youtu.be)

**Expected behaviour**: 
[Retail hit box](https://youtu.be/jf51zsgl-FA?t=116)

**Server Revision**: 
2382

**Comment by towneh** [comment]
https://youtu.be/bWPlxOIxC4w better example of radius size size as he's pulled further down the ramp. Melee POV to show melee hotbox distance.
