### ISSUE TITLE
Primal Mooncloth Set Material Cost

### ISSUE THREAD

**Issue by ByronRageQuit** [Atlantiss/NetherwingBugtracker#3247]
**Description**: Primal Mooncloth patterns are missing their 2.0 cost. 

**Current behaviour**: Items are using their 2.1 and later cost. (At 2.1 the cost of these items was greatly reduced) In some cases changed (less cloth required more primals required)

Note: I used the date May 1, 2007 as a reference date as that was 2 weeks before 2.1 launch

Primal Mooncloth Robe: 
http://wowwiki.wikia.com/wiki/Primal_Mooncloth_Robe?oldid=1260024
http://wowwiki.wikia.com/wiki/Primal_Mooncloth_Robe?oldid=626051

Primal Mooncloth Shoulders:
http://wowwiki.wikia.com/wiki/Primal_Mooncloth_Shoulders?oldid=617272

Primal Mooncloth Belt:
http://wowwiki.wikia.com/wiki/Primal_Mooncloth_Belt?oldid=617271

**Expected behaviour**: The cost of mats for these items should change until 2.1 patch

**Server Revision**: 2382

**Comment by aresbrutus** [comment]
Shiro explained best: https://github.com/ccshiro/cc-buglist/issues/2103#issuecomment-186312863
