### ISSUE TITLE
Uvuros "Safespotable"

### ISSUE THREAD

**Issue by ttghnw** [Atlantiss/NetherwingBugtracker#3248]
**Description**: **Current behaviour**:
The elite core hound will not go to melee allowing a ranged caster to simply dps him to death with no evade and not even getting feared at least from the position I was on.
![wowscrnshot_120518_031532](https://user-images.githubusercontent.com/43508698/49487914-691c7900-f83c-11e8-93c5-2b946e9d42f0.jpg)
![wowscrnshot_120518_031535](https://user-images.githubusercontent.com/43508698/49487915-69b50f80-f83c-11e8-9e51-122cfa8ee551.jpg)
![wowscrnshot_120518_031548](https://user-images.githubusercontent.com/43508698/49487916-69b50f80-f83c-11e8-9ac3-c466b464256b.jpg)
![wowscrnshot_120518_031602](https://user-images.githubusercontent.com/43508698/49487917-69b50f80-f83c-11e8-92ba-c2da99b68bf4.jpg)
![wowscrnshot_120518_031611](https://user-images.githubusercontent.com/43508698/49487918-69b50f80-f83c-11e8-8254-c56840746b7e.jpg)
![wowscrnshot_120518_031618](https://user-images.githubusercontent.com/43508698/49487919-69b50f80-f83c-11e8-84e9-52ca9a452d12.jpg)

**Comment by Easyfraggy** [comment]
It's not uvurus specific just a result of #2175
