### ISSUE TITLE
[Item] Night Blade

### ISSUE THREAD

**Issue by george-GPT** [Atlantiss/NetherwingBugtracker#3249]
[//]: # (Enclose links to things related to the bug using http://wowhead.com or any other TBC database.)
[//]: # (You can use screenshot ingame to visual the issue.)
[//]: # (Write your tickets according to the format:)
[//]: # ([Quest][Azuremyst Isle] Red Snapper - Very Tasty!)
[//]: # ([NPC] Magistrix Erona)
[//]: # ([Spell][Mage] Fireball)
[//]: # ([Npc][Drop] Ghostclaw Lynx)
[//]: # ([Web] Armory doesnt work)
[//]: # (To find server revision type `.server info` command in the game chat.)

**Description**: 

Item Name | Current PPM | Additional Notes
-- | -- | --
The Night Blade | 1.6 | Armor pen from proc needs further testing in a controlled environment https://imgur.com/a/jfW1Pt2 Proc may be much lower then it should be: _"According to the german forums the pro crate got lowered from 21% to 6,5% (Patch 2.0.12)"_ https://tbc-twinhead.twinstar.cz/?item=31331

**Current behaviour**:

**Expected behaviour**: 
It appears that the proc rate may be lower then what is blizzlike. Further research is needed.
**Server Revision**: 
2382

**Comment by Peglaa** [comment]
Comments do indeed say that it would proc very often on 2.0 but it got nerfed at 2.1... could be a nice buff for 2.0 rogues to make the proc rate bigger as it was on 2.0.

**Comment by Manaci** [comment]
Irrelevant now

**Comment by Manaci** [comment]
Reopened for future usage

**Comment by knasen88** [comment]
make it happen 👍

**Comment by Godmatik** [comment]
2.0 states for items no longer used - closing
