### ISSUE TITLE
Hunter pet, Growl and Gore abilities

### ISSUE THREAD

**Issue by wtRCH** [Atlantiss/NetherwingBugtracker#325]
[//]: # (Enclose links to things related to the bug using http://wowhead.com or any other TBC database.)
[//]: # (You can use screenshot ingame to visual the issue.)
[//]: # (Write your tickets according to the format:)
[//]: # ([Quest][Azuremyst Isle] Red Snapper - Very Tasty!)
[//]: # ([NPC] Magistrix Erona)
[//]: # ([Spell][Mage] Fireball)
[//]: # ([Npc][Drop] Ghostclaw Lynx)
[//]: # ([Web] Armory doesnt work)

**Description**: Sadly, I can't say much about it but it's what the player told me so far:
![image](https://user-images.githubusercontent.com/11255782/45937217-6c82c100-bfbe-11e8-93da-956f72cec797.png)
![image](https://user-images.githubusercontent.com/11255782/45937232-80c6be00-bfbe-11e8-857e-0e9e718c8b86.png)

**Comment by mbzz88** [comment]
Possibly pet focus is regenerating at the wrong rate, should be 24 focus every 4 seconds
https://web.archive.org/web/20070716083118/http://bigredkitty.blogspot.com:80/2007/05/focus-system.html
Growl definitely should cost 15 focus though

**Comment by Easyfraggy** [comment]
Need proof that pet abilities should have a priority list.

**Comment by Eidous** [comment]
https://www.wowhead.com/forums&topic=6714

**Comment by Easyfraggy** [comment]
No proof added in a whole month. Closing..
