### ISSUE TITLE
[Paladin][Spell] Judgement of the crusader and Sanctity aura math errors

### ISSUE THREAD

**Issue by Novat93** [Atlantiss/NetherwingBugtracker#3250]
[//]: # (Enclose links to things related to the bug using http://wowhead.com or any other TBC database.)
[//]: # (You can use screenshot ingame to visual the issue.)
[//]: # (Write your tickets according to the format:)
[//]: # ([Quest][Azuremyst Isle] Red Snapper - Very Tasty!)
[//]: # ([NPC] Magistrix Erona)
[//]: # ([Spell][Mage] Fireball)
[//]: # ([Npc][Drop] Ghostclaw Lynx)
[//]: # ([Web] Armory doesnt work)
[//]: # (To find server revision type `.server info` command in the game chat.)

**Description**: Holy damage added from the paladins own gear, and increased holy damage taken by the targeted mob via judgement of the crusader. Seem to add up to different values. Sanctity aura also seem to incorrectly add bonus damage.

**Current behaviour**:
Testing the following 5 scenarios, using rank 6 consecration (max rank).
219 spell damage on gear = 92 damage
0 spell damage on gear, 219 spell damage from judgement of the crusader = 91 damage

Using sanctity aura - +10% holy damage +2% all damage

219 spell damage on gear = 103 (92 * 1.12 = 103.04)
0 spell damage on gear, 219 spell damage from judgement of the crusader = 99 (91 *1.12 = 101.92)

**Expected behaviour**: 
1. The system should calculate spell damage equally. Be it spell damage on the characters gear, or bonus spell damage received on the target mob.

2. Sanctity aura should properly add 12% bonus damage total to holy abilities. It only appears to add just shy of 9% to spell damage granted by judgement of Crusader.

**Server Revision**: 
2395

Note:
To reach exactly 219 spell damage, for reproduction purposes. You can equip the two items bellow:

Gavel of Unearthed Secrets (30832) + 40 spell damage enchant
Tidefury Gauntlets (27510)

**Comment by Tenoutoften** [comment]
What other talent points did you have other than Sanctity Aura 2/3?

**Comment by Novat93** [comment]
Crusade, which i just discovered provided (incorrectly) a damage bonus on the mechanical dummies in shattrath. Testing revealed the damage bonus did not apply on other mechanical units, so i will not be filing an individual bug report. As the mechs in Shattrath will not be part of the live launch.

Testing on actual mobs outside shattrath (beast) without crusade talent.

Test 2:
**The new tested values appear identical, and they may be, or they are simply rounded to the same number**
219 spell damage on gear = 89 damage
0 spell damage on gear, 219 spell damage from judgement of the crusader = 89 damage

Using sanctity aura - +10% holy damage +2% all damage

**The bonus granted by sanctity aura does not properly grant both values the same bonus**
219 spell damage on gear = 98
0 spell damage on gear, 219 spell damage from judgement of the crusader = 96

**Comment by Novat93** [comment]
Test 3:
361 spell damage on paladin
Judgement of the crusader + Libram of zeal = 266 bonus damage
= 627 bonus damage total
Consecration rank 6 (max)

Sanctity aura base rank = 10% holy damage
148 damage per tick

Sanctity aura base + 1 point improved = 10% holy damage +1% all damage
150 damage per tick

Sanctity aura base + 2 points improved = 10% holy damage +2% all damage
151 damage per tick

Improved sanctity aura seem to be working as it should. First point adding 2 damage, second point adding only 1 damage is most certainly caused by rounding the numbers.

**Comment by ta55el** [comment]
Talents, buffs and debuffs stacking multiple damage so it will be like that (1,1*1,02)=1,122

**Comment by Godmatik** [comment]
Fully tested and verified the numbers to be correct, s/o to Zoo for testing.

Closing

![pallynumbers](https://github.com/user-attachments/assets/c843d5d8-9c8e-4b22-a2a0-78ed976029b6)
