### ISSUE TITLE
[Quest][Shadowmoon Valley] Besieged

### ISSUE THREAD

**Issue by Firroth** [Atlantiss/NetherwingBugtracker#3252]
Quest [Besieged](https://www.wowhead.com/quest=10595/besieged)

**Current behaviour**:
Guards do too much dmg too infernals, and low dmg dealing classes can have a problem completing this quest cause of it. Since they are immune to fire spells, I needed to use Frostbolt even though I started attacking infernal when he had 90% hp and he took 3 hits from my frostbolt, I didn't get credit. Similar case everytime, unless I started attacking when infernal "just spawned" on landing, only then I stood a chance in gear t4 lvl 70 xD, so it can be far worse I imagine on lvling players with lesser dmg.

**Expected behaviour**: 
Guards should deal either lesser dmg to them, or player should get credit even if guards dealt more damage than them.

**Server Revision**: 
2395

**Comment by Bildo** [comment]
fixed in rev 2410
