### ISSUE TITLE
[NPC] Springpaw Stalker

### ISSUE THREAD

**Issue by Erodraeda** [Atlantiss/NetherwingBugtracker#3254]
[//]: # (Enclose links to things related to the bug using http://wowhead.com or any other TBC database.)
[//]: # (You can use screenshot ingame to visual the issue.)
[//]: # (Write your tickets according to the format:)
[//]: # ([Quest][Azuremyst Isle] Red Snapper - Very Tasty!)
[//]: # ([NPC] Magistrix Erona)
[//]: # ([Spell][Mage] Fireball)
[//]: # ([Npc][Drop] Ghostclaw Lynx)
[//]: # ([Web] Armory doesnt work)
[//]: # (To find server revision type `.server info` command in the game chat.)

**Description**: 
Some of these mobs are attacking without going out of stealth, and do not appear to you until you move (still being in stealth)
**Current behaviour**:
The mob (Entry 15651, ID 61) does damage without leaving stealth.
**Expected behaviour**: 
Should leave stealth after the first hit
**Server Revision**: 2395

**Comment by Erodraeda** [comment]
https://imgur.com/a/SRvuELC
Finally reproduced it to record.

**Comment by Tereneckla** [comment]
Fixed
