### ISSUE TITLE
[Zone] Shadowmoon Valley - Bad positioning of NPC's

### ISSUE THREAD

**Issue by Firroth** [Atlantiss/NetherwingBugtracker#3255]
**Current behaviour**:

![screenshot_4](https://user-images.githubusercontent.com/43505196/49527451-3c0aad80-f8b2-11e8-9faf-80e65d57521f.png)

They both overlap each other and don't even move or anything, watched their behaviour for 2min.

**Expected behaviour**: 

They shouldn't overlap each other, and pretty possible 1 of them should be in other place.

**Server Revision**: 
2395

**Comment by Tenoutoften** [comment]
I think some parts of Netherstorm & Shadowmoon Valley is waiting for sniffs to be done before they are fixed

**Comment by Kiperr** [comment]
they should have pathing

**Comment by Kiperr** [comment]
Fix send to Kutasal

**Comment by aresbrutus** [comment]
Fixed in rev `Nariman `thanks to Kiper. Please recheck after fix is pushed.
