### ISSUE TITLE
[Zone] Shadowmoon Valley - Shadow Council Warlocks missing visual effect

### ISSUE THREAD

**Issue by Firroth** [Atlantiss/NetherwingBugtracker#3256]
**Current behaviour**:
Most of them work fine, and cast green beam at the object, with some of them being exceptions for some reason.

![screenshot_5](https://user-images.githubusercontent.com/43505196/49528446-4037ca80-f8b4-11e8-83e3-2c3452a6ec4b.png)

**Expected behaviour**: 
All of them should be casting this visual green beam on the pillars near each they stand.

**Server Revision**: 
2395

**Comment by devo6969** [comment]
Still happens on the PTR. Seems if you are to kill one, and not the whole pack. When that one you killed respawns it stops the animation for the one's that were left alive.

**Comment by Godmatik** [comment]
Rev 4018 - checked on PTR and this no longer occurs
Killed one and it did not interrupt the animation for the others after respawn. Also killed all 4 in one tower and same result, they all doing their animations properly upon respawn
