### ISSUE TITLE
[Quest] Thwart the Dark Conclave

### ISSUE THREAD

**Issue by Firroth** [Atlantiss/NetherwingBugtracker#3258]
**Current behaviour**:
You can use item without clearing the place out of mobs who perform the ritual.

![screenshot_5](https://user-images.githubusercontent.com/43505196/49529983-82164000-f8b7-11e8-9782-04d8134adb38.png)

**Expected behaviour**: 
You should only be able to use the item when "ritual place" is clear of mobs who are performing it. (ones who cast purple beam)

![screenshot_3](https://user-images.githubusercontent.com/43505196/49530272-3617cb00-f8b8-11e8-83b0-f12732312ed3.png)

https://www.youtube.com/watch?v=f485qK2RgqY

**Server Revision**: 
2395

**Comment by aresbrutus** [comment]
Fixed in rev `Nariman `thanks to Kiper fix.

**Comment by Bemrok** [comment]
Quest is broking again - you can't use the staff, doesn't matter the position or if you have killed the mobs or not as shown in screenshot
![wowscrnshot_021119_195458](https://user-images.githubusercontent.com/47538033/52586580-27a9da80-2e38-11e9-91ea-ee1f4f298530.jpg)
