### ISSUE TITLE
[Object][Ghostlands] Stairs are buggy

### ISSUE THREAD

**Issue by Thugli** [Atlantiss/NetherwingBugtracker#326]
[//]: # (Enclose links to things related to the bug using http://wowhead.com or any other TBC database.)
[//]: # (You can use screenshot ingame to visual the issue.)
[//]: # (Write your tickets according to the format:)
[//]: # ([Quest][Azuremyst Isle] Red Snapper - Very Tasty!)
[//]: # ([NPC] Magistrix Erona)
[//]: # ([Spell][Mage] Fireball)
[//]: # ([Npc][Drop] Ghostclaw Lynx)
[//]: # ([Web] Armory doesnt work)

**Description**: 
Staircase in Farstrider Enclave - Ghostlands gets buggy when walking over it.

**Current behaviour**:
The bugged behaviour of walking up these stairs, as well as coordinates, can be seen here:
https://clips.twitch.tv/DaintyStrongCougarShadyLulu

**Expected behaviour**: 
Walking up the stairs should be smooth with no resistance

**Server Revision**:

**Comment by wtRCH** [comment]
This bug happens when you take a slightly different approach on them

**Comment by Easyfraggy** [comment]
Isn't this entirely client side?

**Comment by Evolvee** [comment]
clientside
