### ISSUE TITLE
[Misc]Unable to set at war with [Faction]The Aldor#932

### ISSUE THREAD

**Issue by Tenoutoften** [Atlantiss/NetherwingBugtracker#3260]
**Description**: 
Should be optional to set at war with [[Faction]The Aldor#932](https://www.wowhead.com/faction=932/the-aldor) seen [here](https://www.youtube.com/watch?v=ZzBmlTaeoFo) and [here](https://youtu.be/T-5eXxSE8W0?t=9)

Unable to check at war:
![0ff79b1a178ed85e20e574cdf5203ac2](https://user-images.githubusercontent.com/34839199/49540104-7e8eb300-f8cf-11e8-9e55-351130bcc2b9.png)
![d5c3b4c0a2d7d32476e670ff41b40909](https://user-images.githubusercontent.com/34839199/49540105-7e8eb300-f8cf-11e8-9cd0-bb12fc1da472.png)
I also checked with the character I did 1-70 with.

Previously it looked like someone got stuck permanently at war with [[Faction]The Scryers#934](https://www.wowhead.com/faction=934/the-scryers): https://github.com/Atlantiss/NetherwingBugtracker/issues/2166

**Current behaviour**:
Unable to set at war with [[Faction]The Aldor#932](https://www.wowhead.com/faction=932/the-aldor)

**Expected behaviour**: 
Should be able to set at war with [[Faction]The Aldor#932](https://www.wowhead.com/faction=932/the-aldor)

**Server Revision**: 
2395

**Comment by nullfoxh** [comment]
Have you done this quest https://www.wowhead.com/quest=10211/city-of-light ? Someone on discord mentioned you needed to do it first, not confirmed though.

**Comment by Tenoutoften** [comment]
One of my characters has done it

**Comment by Godmatik** [comment]
Will not be changed - this has the possibility to be very disruptive
