### ISSUE TITLE
[NPC] Mobs don't aggro after they respawn

### ISSUE THREAD

**Issue by somnu** [Atlantiss/NetherwingBugtracker#3262]
**Description**: 
Mobs never aggro the player if they respawn on top of him and the player makes no moves.

**Current behaviour**:
Currently mobs never aggro the player if they respawn on top of him and the player makes no moves.

![wowscrnshot_120518_221349](https://user-images.githubusercontent.com/10576515/49541514-a1bf5f80-f8db-11e8-8806-8c206a0a6a00.jpg)

**Expected behaviour**: 
All mobs should have a "grace period" of about 2-3 seconds after they respawn where they don't aggro immediately after which they should aggro any player that has been camping the spot.

**Server Revision**: 
2395

**Comment by lynxzor** [comment]
Related: https://github.com/Atlantiss/NetherwingBugtracker/issues/2511#issuecomment-441441112

**Comment by Wolffenstein** [comment]
Fixed in rev 2518.
