### ISSUE TITLE
[Misc][NPC]Shattrath City lacking a few Refugee NPCs(#19155/19120/19162/20876)

### ISSUE THREAD

**Issue by Tenoutoften** [Atlantiss/NetherwingBugtracker#3265]
**Description**: 
There is lacking a few Refugee NPCs in Lower City next to the horde battlemasters, specifically:
* [[NPC]Sporeling Refugee#19155](https://www.wowhead.com/npc=19155/sporeling-refugee)
* [[NPC]Broken Refugee#19120](https://www.wowhead.com/npc=19120/broken-refugee)
* [[NPC]Lost one Refugee#19162](https://www.wowhead.com/npc=19162/lost-one-refugee)
* [[NPC]Human Refugee#20876](https://db.excalibur.ws/?npc=20876)

Map 530(Outland)
Zone: 3703 (Shattrath City)
Area: 3899 (Lower City)

Can be seen [here](https://youtu.be/LgXTlZ_Iilk?t=241)
[here](https://youtu.be/LgXTlZ_Iilk?t=265)
[here](https://youtu.be/LgXTlZ_Iilk?t=301) - next to the forges on the left in the video.

The refugee NPCs in Lower City sometimes patrol a bit(some of them alone) and they will do talking animation while doing so.

**Current behaviour**:
Looks like there should be more NPCs by the "kitchen" especially.

**Expected behaviour**: 
Expect a few more NPCs

**Server Revision**: 
2395

**Comment by rjorgensen** [comment]
They all seem to be added in 2.2.

**Comment by Tenoutoften** [comment]
What makes you say that?

Published on Jan 21, 2007

[Patch 2.0.5](http://wowwiki.wikia.com/wiki/Patches/2.x) - 14 January 2007

**Comment by aresbrutus** [comment]
Fixed in rev `Nariman`
