### ISSUE TITLE
[Priest]  Focus Casting (Buff gained from Martyrdom talent)

### ISSUE THREAD

**Issue by Thugli** [Atlantiss/NetherwingBugtracker#3266]
[//]: # (Enclose links to things related to the bug using http://wowhead.com or any other TBC database.)
[//]: # (You can use screenshot ingame to visual the issue.)
[//]: # (Write your tickets according to the format:)
[//]: # ([Quest][Azuremyst Isle] Red Snapper - Very Tasty!)
[//]: # ([NPC] Magistrix Erona)
[//]: # ([Spell][Mage] Fireball)
[//]: # ([Npc][Drop] Ghostclaw Lynx)
[//]: # ([Web] Armory doesnt work)
[//]: # (To find server revision type `.server info` command in the game chat.)

**Description**: 
The focus casting buff occasionally procs from non-critical strikes.
**Current behaviour**:
https://clips.twitch.tv/ShortMoldyOstrichBabyRage
**Expected behaviour**: 
The focus casting buff should only be triggered by critical strikes.
**Server Revision**: 
2395

**Comment by Easyfraggy** [comment]
I believe this is due to resilience and it is actually correct behavior - when resilience negates the crit? I have some weird memory of that.

@Evolvee

**Comment by Evolvee** [comment]
Resilience
