### ISSUE TITLE
[Arena] Clipping on walls/game objects 

### ISSUE THREAD

**Issue by Thugli** [Atlantiss/NetherwingBugtracker#3267]
[//]: # (Enclose links to things related to the bug using http://wowhead.com or any other TBC database.)
[//]: # (You can use screenshot ingame to visual the issue.)
[//]: # (Write your tickets according to the format:)
[//]: # ([Quest][Azuremyst Isle] Red Snapper - Very Tasty!)
[//]: # ([NPC] Magistrix Erona)
[//]: # ([Spell][Mage] Fireball)
[//]: # ([Npc][Drop] Ghostclaw Lynx)
[//]: # ([Web] Armory doesnt work)
[//]: # (To find server revision type `.server info` command in the game chat.)

**Description**: 
Several instances of clipping on walls & game objects on various arena maps.
**Current behaviour**:
Corner of pillar in Blade's Edge Arena (May be blizzlike):
https://clips.twitch.tv/WiseSteamyMangoSeemsGood

Pillars in Blade's Edge Arena:
https://clips.twitch.tv/WittyNaiveApeTF2John
https://clips.twitch.tv/ScrumptiousFunFishFreakinStinkin

Tomb in the middle of Ruins of Lorderon:
https://clips.twitch.tv/SpotlessAdventurousKimchiDerp
https://clips.twitch.tv/PatientEphemeralCobraFrankerZ

Spikes surrounding the pillars in Nagrand arena: 
https://clips.twitch.tv/BillowingKitschyEndiveFailFish

**Expected behaviour**: 
Players should not clip when running into these game objects.
**Server Revision**: 
2395

**Comment by Wolffenstein** [comment]
How many times do I have to say that the server does not control raw player movement
