### ISSUE TITLE
[Spell][Mage] Able to spam Arcane Missiles (GCD bug) + Facing target bug while turning

### ISSUE THREAD

**Issue by killablink** [Atlantiss/NetherwingBugtracker#3268]
**Description**: Able to spam AM and drain my own mana

**Current behaviour**: https://gfycat.com/DelightfulTanBream

**Expected behaviour**: GCD should happen

**Server Revision**: 2395

**Comment by Easyfraggy** [comment]
This happens when recasting AM while already channeling one. Doesn't happen with Mind Flay and Drain Life for me - but very easy to recreate with AM.

**Comment by killablink** [comment]
https://gfycat.com/YoungUnsteadyHumpbackwhale

Sometimes not able to cast AM while you're rotating and face the target, still get target not in front of you error.

**Comment by Easyfraggy** [comment]
I think thats actually a seperate issue - "keyboard turning doesn't update your facing untill you let it go".

https://gfycat.com/DevotedFoolhardyCorydorascatfish

**Comment by Tereneckla** [comment]
Spam is fixed

**Comment by Evolvee** [comment]
so whats wrong with it now?

**Comment by Tereneckla** [comment]
What easy described. Arcane missiles (well all channeling spells) don't check if you are still facing your target during channeling.

**Comment by Evolvee** [comment]
they shouldnt, once you manage to cast it, you can rotate with your character however you want

**Comment by Evolvee** [comment]
or?

**Comment by Tereneckla** [comment]
If it's correct that you can rotate your character however you want after start of channeling then everything is working fine.

**Comment by Evolvee** [comment]
k, unless someone provides evidence -- closed
