### ISSUE TITLE
[Class] Warlock [Pet] [Misc] Summoning Underground

### ISSUE THREAD

**Issue by tcberk12** [Atlantiss/NetherwingBugtracker#327]
There is an issue with summoning a pet/minion on land that is directly above underground passages. 

I was summoning my imp atop the Fargodeep mine in Elywnn. When the imp spawned, however, it spawned in the tunnel passageways directly below me and was quickly killed off by kobolds.

The summoned pet/minion should spawn on the same level of ground as the player summoning.

In the below screenshot you can see my position above the mine, as well as my recently summoned imp taking damage (in the combat log) inside the mine as a result of him being spawned below me. Rip Belpit.

<img width="1440" alt="screen shot 2018-09-23 at 9 10 52 pm" src="https://user-images.githubusercontent.com/43530009/45937467-32410180-bf75-11e8-9232-939eacccdf6b.png">

**Comment by devo6969** [comment]
https://www.youtube.com/watch?v=MUpyQwTtZyI

It happens on the "peak" of the Mountain perhaps a hole in the terrain.

**Comment by Tereneckla** [comment]
![image](https://user-images.githubusercontent.com/50233983/86518139-316a1e80-be2f-11ea-8ab8-9de09363c674.png)

**Comment by Wolffenstein** [comment]
Fixed in rev 3439.
