### ISSUE TITLE
Mob: Entry: 3098, Id: 33 - Mottled Boar

### ISSUE THREAD

**Issue by MacaWilly** [Atlantiss/NetherwingBugtracker#3270]
Entry: 3098, Id: 33

Mottled Boar, in the Valley of Trials 43.8, 72.5 spawns half into the ground, looks to be a visual bug as you still can attack from range

**Comment by wtRCH** [comment]
@aresbrutus

**Comment by aresbrutus** [comment]
Fixed in rev `Nariman`
