### ISSUE TITLE
[Core Mechanc][NPC]Humanoids under flee mechanic should start of running, then walk back when mechanic has ended. Mechanic not lasting long enough

### ISSUE THREAD

**Issue by Tenoutoften** [Atlantiss/NetherwingBugtracker#3273]
**Description**: 
When humanoid mobs capable of "attempts to run away in fear" has their mechanic triggered they should run at full speed:

Retail evidence:
---
Found video evidence [here](https://youtu.be/EN7KfJ7ZKXc?t=164) Notice the mob that **runs** behind his back, Hobbos turns around, and confirms this mob is running at full speed.

Mob runs away, then after a while it slow down again, notice it is still under the flee mechanic [here](https://youtu.be/EN7KfJ7ZKXc?t=189)

Retail flee mechanic looks to last ~10-15 seconds. Perhaps easier to notice [here](https://youtu.be/EN7KfJ7ZKXc?t=390)

NW behavior:
---
Seen [here](https://youtu.be/ERPyEue34TQ?t=23)
Walks away in fear, when the flee mechanic is complete it charges back. Pretty much the reverse of retail
evidence provided.

NW flee mechanic lasts ~6 seconds.

**Expected behaviour**: 
Humanoid mobs are expected to run when the flee mechanic triggers, and eventually slow down. 

**Server Revision**: 
2395

**Comment by Tenoutoften** [comment]
Figured I'd post this since someone else posted it, another humanoid, this time outside of SM running away rather than limping away
https://youtu.be/zssuKMWa-vg?t=2442

**Comment by Godmatik** [comment]
Closing this one out - more detailed information from classic found here:
https://github.com/Atlantiss/NetherwingBugtracker/issues/7145
