### ISSUE TITLE
[Hunter] Ranged speed weapon

### ISSUE THREAD

**Issue by ta55el** [Atlantiss/NetherwingBugtracker#3274]
**Description**: 
Ranged weapon speed can be stack endlessly by switching weapons with diffrend attack speed and then quivers and ammo pouch.
https://imgur.com/a/6SaMk2c

**Server Revision**: 2395

I'll record a video for a while how i do it.
https://youtu.be/TWV6vslpAmA

It can be done also in second way increasing weapon speed.
https://youtu.be/ApqAPxOva4Q

**Comment by Wolffenstein** [comment]
Fixed in rev 2399.

**Comment by atychiphobia** [comment]
https://youtu.be/XccyLbaij2c?t=381
