### ISSUE TITLE
[Item] Flame Cap

### ISSUE THREAD

**Issue by ta55el** [Atlantiss/NetherwingBugtracker#3275]
**Description**: 
Flame Cap should deal dmg also on ranged attacks.
http://wowwiki.wikia.com/wiki/Flame_Cap?oldid=1468485

**Current Behaviour:**
https://www.youtube.com/watch?v=sheIVQ64JaQ&feature=youtu.be

**Server Revision**: 2395

**Comment by Tenoutoften** [comment]
http://web.archive.org/web/20070410132021/http://www.thottbot.com:80/i22788
confirmed

**Comment by Wolffenstein** [comment]
Fixed in rev 2436.
