### ISSUE TITLE
[Talent][Mage]Arcane Instability

### ISSUE THREAD

**Issue by ircfelix** [Atlantiss/NetherwingBugtracker#3277]
**Description**: 
I am not sure if this talent works as it should, maybe it is just a display bug and is already working. Maybe not.

**Current behaviour**:
When you spec into this talent, you see the 1/2/3% critical strike chance increase as advertised by the talent. According to the source http://wowwiki.wikia.com/wiki/Arcane_Instability?oldid=1432059, that is correct.
However, if I spec into this talent, I don't see a spell damage increase, neither for the spell damage in my character window, nor for the base damage of my spells. . My test character has 551 spell damage when I spec into 1/2/3 points of this talent. Compared to the Piercing Ice talent, which seems to increase the base damage of frost spells by 2/4/6%, Arcane Instability does nothing besides the critical strike bonus.

**Expected behaviour**: 
According to http://wowwiki.wikia.com/wiki/Arcane_Instability?oldid=1432059, the talent should increase the spell damage (of all schools) on from gear and stats by 1/2/3% and my character should display 556/562/567 spell damage in the character window.

**Server Revision**: 
2395

**Comment by killablink** [comment]
No talents
![image](https://user-images.githubusercontent.com/43510874/49603681-f1447080-f959-11e8-847c-5a9b57c2dc8b.png)

With Arcane stability
![image](https://user-images.githubusercontent.com/43510874/49603699-fe615f80-f959-11e8-8292-f4793f35d28e.png)

**Comment by ircfelix** [comment]
> 
> 
> No talents
> ![image](https://user-images.githubusercontent.com/43510874/49603681-f1447080-f959-11e8-847c-5a9b57c2dc8b.png)
> 
> With Arcane stability
> ![image](https://user-images.githubusercontent.com/43510874/49603699-fe615f80-f959-11e8-8292-f4793f35d28e.png)
> 
> I think it only increases your dmg and not your spell power on your tab itself

Then it's a display bug. The Piercing Ice talent shows the base damage increase for frost spells, this talent doesn't.

**Comment by killablink** [comment]
What do you mean display bug? I also don't understand what you mean for piercing ice, it doesn't update your character tab.

Some talents don't change tooltips and others, same way how you talent for permafrost, if you mouse over your frostbolt it will say slows for 50%, but the debuff the enemy receives, the tooltip only shows 40% (even though it is 50%)

**Comment by ircfelix** [comment]
If I take 3 points in Piercing Ice and go to the spell book, I see the updated base damage of e.g. frost bolt (636 instead of 600). However, if I take 3 points in Arcane Instability, none of my spell's tooltips is updated.

That's why I didn't know if it works or not, but you proved that it works, so this issue can also be closed.

**Comment by ircfelix** [comment]
It's still not certain if it should be:
- spell damage and healing from gear and effects increase (e.g. instead of 100 spell damage in character window, it's 103),
- flat total damage increase to all spell schools (e.g. if your spell hits a mob for 100, it should hit for 103),
- or a flat base damage increase to all spells (e.g. if a spell's base damage is 100-200, the spell's base damage should be 103-206)

My source states it's spell damage and healing.

@Tenoutoften  I don't fully get what you want to say with your source.

**Comment by Tereneckla** [comment]
It's the second, and it does that.
