### ISSUE TITLE
[NPC] Garr Salthoof facing the wrong direction

### ISSUE THREAD

**Issue by towneh** [Atlantiss/NetherwingBugtracker#3278]
**Description**: 
NPC facing the wrong direction and slightly too far forward in the door frame.

**Current behaviour**:
![image](https://user-images.githubusercontent.com/25694892/49603501-5c566d00-f983-11e8-825f-782dcc88b977.png)

**Expected behaviour**: 
https://youtu.be/zssuKMWa-vg?t=2431
![image](https://user-images.githubusercontent.com/25694892/49603535-71cb9700-f983-11e8-8aa2-d6a5af2aa313.png)

**Server Revision**: 
2395

**Comment by Tenoutoften** [comment]
He posted the video https://www.youtube.com/watch?v=zssuKMWa-vg&feature=youtu.be&t=2431

**Comment by aresbrutus** [comment]
Fixed in rev `Nariman`
