### ISSUE TITLE
[Spell][Frostbolt] (All spells with debuffs most likely)

### ISSUE THREAD

**Issue by killablink** [Atlantiss/NetherwingBugtracker#3279]
**Description**: [2396][Core] Fixed an issue which prevented certain spells from being casted due to lower spell rank even if they had non-aura applying effects (e.g. Frostbolt)"

https://gfycat.com/SillyYawningEasternglasslizard

**Current behaviour**: We can now cast lower rank frost bolt even after a higher rank frostbolt, the problem now is that the lower rank frostbolt is replacing the debuff of the higher rank, which it shouldn't. Same thing with fireball, the rank 1 replaces the higher rank debuff and does 1 dmg ticks.
https://gfycat.com/SillyYawningEasternglasslizard

**Expected behaviour**: Doesn't reapply a lower duration (or lesser dmg dealing debuff)

**Server Revision**: 2401

**Comment by Evolvee** [comment]
it works just fine
