### ISSUE TITLE
[Core Mechanic][Druid][Paladin][Mage][Spell]Lose Mana & Health on class spells-buffs upon rebuff

### ISSUE THREAD

**Issue by Tenoutoften** [Atlantiss/NetherwingBugtracker#3280]
**Description**: 
Based on https://github.com/Atlantiss/NetherwingBugtracker/issues/1934 a few additional buffs eating resources they shouldn't upon rebuff

**Blessing of Kings**
* [[Spell]Blessing of Kings#20217](https://db.excalibur.ws/?spell=20217)
* [[Spell]Greater Blessing of Kings#25898](https://db.excalibur.ws/?spell=25898)

**Arcane Intellect**
* [[Spell]Arcane Intellect(rank 1)#1459](https://db.excalibur.ws/?spell=1459)
* [[Spell]Arcane Intellect(rank 2)#1460](https://db.excalibur.ws/?spell=1460)
* [[Spell]Arcane Intellect(rank 3)#1461](https://db.excalibur.ws/?spell=1461)
* [[Spell]Arcane Intellect(rank 4)#10156](https://db.excalibur.ws/?spell=10156)
* [[Spell]Arcane Intellect(rank 5)#10157](https://db.excalibur.ws/?spell=10157)
* [[Spell]Arcane Intellect(rank 6)#27126](https://db.excalibur.ws/?spell=27126)

**Mark of the Wild - Health update works, mana doesn't**
* [[Spell]Mark of the Wild(Rank 2)#5232](https://db.excalibur.ws/?spell=5232)
* [[Spell]Mark of the Wild(Rank 3)#6756](https://db.excalibur.ws/?spell=6756)
* [[Spell]Mark of the Wild(Rank 4)#5234](https://db.excalibur.ws/?spell=5234)
* [[Spell]Mark of the Wild(Rank 5)#8907](https://db.excalibur.ws/?spell=8907)
* [[Spell]Mark of the Wild(Rank 6)#9884](https://db.excalibur.ws/?spell=9884)
* [[Spell]Mark of the Wild(Rank 7)#9885](https://db.excalibur.ws/?spell=9885)
* [[Spell]Mark of the Wild(Rank 8)#26990](https://db.excalibur.ws/?spell=26990)

Works correctly
[[Spell]Arcane Brilliance(Rank 1 & 2)#23028/27127](https://db.excalibur.ws/?search=arcane+brilliance#spells)

**Current behaviour**:
Lose current health/Mana on rebuff on specific buffs

**Expected behaviour**: 
Expected to only lose the cost of the buff, if rebuffed with the same rank / improvements

**Server Revision**: 
2401

**Comment by Godmatik** [comment]
Was fixed a few years ago - closing
