### ISSUE TITLE
[Priest][Mind Control] Threat issue

### ISSUE THREAD

**Issue by killablink** [Atlantiss/NetherwingBugtracker#3282]
**Description**: I'm attacking a mob and a priest mind controls me and gets all the aggro on him even though he wasn't in combat with the mob. Even after taunting the mob still goes after him after the taunt

**Current behaviour**: I'm attacking a mob and a priest mind controls me and gets all the aggro on him even though he wasn't in combat with the mob. Even after taunting the mob still goes after him after the taunt
https://gfycat.com/AshamedInferiorAmericanratsnake

**Expected behaviour**: Probably shouldn't get aggro and I should still get hit by the mob

**Server Revision**: 2401

**Comment by Brasso** [comment]
Related? #2056

**Comment by Wolffenstein** [comment]
The caster receives a ton of threat after the mind control fades. That is intended.

**Comment by killablink** [comment]
Sorry can I have proof of how kind control generate mass threat on mobs not being mind controlled?
All I find online is how you generate a lot of threat to the mob you finished mind controlling, not the mobs around it.(how it's supposed to be, if he mind controlled the wolf and I couldn't get aggro it would be different but he mind controlled me when he wasn't even in combat with the wolf. And you said it generates threat when mind control fades but the priest grabbed the aggro from a mob he didn't even attack nor mind control. The mob should be still attacking me.

Genuinely curious to see what proof you have because I really believe that this isn't normal.

**Comment by Wolffenstein** [comment]
Sorry I misunderstood. This issue will be fixed in rev 2404.
