### ISSUE TITLE
[Priest][Mind Control] PVP Trinket  

### ISSUE THREAD

**Issue by killablink** [Atlantiss/NetherwingBugtracker#3283]
**Description**: Unable to use PVP Trinket when you get mind controlled (can use will of forsaken to break it though)

**Current behaviour**: https://gfycat.com/AshamedInferiorAmericanratsnake 
(You can see I wasn't able to trinket (I was also stunned but I tried to trinket the stun itself and I was able) the mind control) (Also tested against just mind control and couldn't)

**Expected behaviour**:  Should be able to trinket MC

**Server Revision**: 2401

**Comment by Wolffenstein** [comment]
Fixed in rev 2403.
