### ISSUE TITLE
They're Alive! Maybe..

### ISSUE THREAD

**Issue by WhyAintThisFixedYet** [Atlantiss/NetherwingBugtracker#3285]
[//]: # (Enclose links to things related to the bug using http://wowhead.com or any other TBC database.)
[//]: # (You can use screenshot ingame to visual the issue.)
[//]: # (Write your tickets according to the format:)
[//]: # ([Quest][Azuremyst Isle] Red Snapper - Very Tasty!)
[//]: # ([NPC] Magistrix Erona)
[//]: # ([Spell][Mage] Fireball)
[//]: # ([Npc][Drop] Ghostclaw Lynx)
[//]: # ([Web] Armory doesnt work)
[//]: # (To find server revision type `.server info` command in the game chat.)

**Description**: They're Alive! Maybe.. is a quest on Bloodmyst Isle where you have to kill Webbed Creatures to release researchers. There is a chance for hostile mobs to be webbed so you may end up spawning a creature that will be hostile.

**Current behaviour**: Nazzivus Summoners spawned from Webbed Creatures or not hostile nor attackable. They are red in game, but wont attack players.

**Expected behaviour**: Creatures should attack players once free'd and players should be able to kill them. 

**Server Revision**: 2401

**Comment by wtRCH** [comment]
@aresbrutus

**Comment by Tenoutoften** [comment]
In addition:
* You don't get shared quest credit for freeing [[NPC]Expedition Researcher#17681](https://www.wowhead.com/npc=17681/expedition-researcher).
* [[NPC]Expedition Researcher#17681](https://www.wowhead.com/npc=17681/expedition-researcher) freed far up the mountain seem to clip through the ground when they run away. [Here](https://www.youtube.com/watch?v=0lIE_43bBFY&feature=youtu.be) is one that has already went through the ground
