### ISSUE TITLE
[Stealth] Mobs see me trough Stealth.

### ISSUE THREAD

**Issue by Giantulol** [Atlantiss/NetherwingBugtracker#3287]
**Description**: 
Mobs in heroic difficulty at CoT Ohf in this case; I noticed this problem and tested it afterwards. 
I went stealth, sended my party members into a group of random elite mobs and let them die. I was at a distance the mobs should never be able to see me at in stealth, never the less they still came for me.

https://i.imgur.com/iw1tTh7.jpg

**Server Revision**: 
2402

**Comment by Tenoutoften** [comment]
[[NPC]Durnholde Sentry#17819](https://www.wowhead.com/npc=17819/durnholde-sentry#comments) is usually accompanied with [[NPC]Durnholde Tracking Hound#17840](https://www.wowhead.com/npc=17840/durnholde-tracking-hound). Were there any dogs nearby?

**Comment by Giantulol** [comment]
We already cleared the patrol with the dog so no, btw this also occurs if you vanish before all your party members died. You seem chained to them. If I remember correctly; when you vanish when you are the last player alive it works fine.

**Comment by towneh** [comment]
Is this related? https://youtu.be/WjVDKxZt1V0

**Comment by Giantulol** [comment]
I noticed that bug in the first beta phase, but that is fixed I think.

**Comment by Godmatik** [comment]
Unable to reproduce.
Likely fixed at some point and this was never closed.
