### ISSUE TITLE
[Item] Blade of Twisted Visions

### ISSUE THREAD

**Issue by Saben65** [Atlantiss/NetherwingBugtracker#3288]
**Description**: 
[Blade of Twisted Visions](https://www.wowhead.com/item=33467/blade-of-twisted-visions#comments:id=234422) was buffed in 2.4.

**Current behaviour**:
[Weapon is in its post 2.4 stats.](https://web.archive.org/web/20081014020936/http://thottbot.com:80/i33467)

**Expected behaviour**: 
[Weapon should be in pre-2.4 stats.
](https://web.archive.org/web/20071116025350/http://thottbot.com:80/i33467)

This should be right, but I only ran it against a DB, don't have a server up to test on.
```SQL
# pre 2.4
UPDATE Item_template SET SellPrice=131461,ItemLevel=132,stat_type1=5,stat_value1=22,stat_type2=30,stat_value2=29,stat_type3=0,stat_value3=0,spellid_1=44075 WHERE entry=33467; -- Blade of Twisted Visions

# post 2.4
UPDATE item_template SET SellPrice=136956,ItemLevel=138,stat_type1=7,stat_value1=33,stat_type2=5,stat_value2=21,stat_type3=30,stat_value3=21,spellid_1=42814 WHERE entry=33467; -- Blade of Twisted Visions
```

**Server Revision**: 
2402

**Comment by wtRCH** [comment]
@aresbrutus

**Comment by aresbrutus** [comment]
Fixed in rev `Nariman`
