### ISSUE TITLE
[Azuremyst Isle][NPC]#17110 incorrectly gates [Q]#9454 behind [Q]#9452->[Q]#9453

### ISSUE THREAD

**Issue by Tenoutoften** [Atlantiss/NetherwingBugtracker#3289]
**Description**: 
[[Quest]The Great Moongraze Hunt#9454](https://www.wowhead.com/quest=9454/the-great-moongraze-hunt), given by [[NPC]Acteon#17110](https://www.wowhead.com/npc=17110/acteon), is incorrectly gated by [[Quest]Red Snapper - Very Tasty!#9452](https://www.wowhead.com/quest=9452/red-snapper-very-tasty) => [[Quest]Find Acteon!#9453](https://www.wowhead.com/quest=9453/find-acteon) 

----

[[NPC]Acteon#17110](https://www.wowhead.com/npc=17110/acteon) seen offering no quest while [[Quest]Red Snapper - Very Tasty!#9452](https://www.wowhead.com/quest=9452/red-snapper-very-tasty) is in the log. 
![1](https://user-images.githubusercontent.com/34839199/49626799-a8cd9700-f9db-11e8-9510-c7fb3b8c4a11.png)

---

Returning to [[NPC]Acteon#17110](https://www.wowhead.com/npc=17110/acteon) after completing [[Quest]Red Snapper - Very Tasty!#9452](https://www.wowhead.com/quest=9452/red-snapper-very-tasty) => [[Quest]Find Acteon!#9453](https://www.wowhead.com/quest=9453/find-acteon) 
![3](https://user-images.githubusercontent.com/34839199/49626841-e7fbe800-f9db-11e8-838c-26cb311386e7.png)

---

Upon completion of [[Quest]Find Acteon!#9453](https://www.wowhead.com/quest=9453/find-acteon), [[NPC]Acteon#17110](https://www.wowhead.com/npc=17110/acteon) offers [[Quest]The Great Moongraze Hunt#9454](https://www.wowhead.com/quest=9454/the-great-moongraze-hunt)
![4](https://user-images.githubusercontent.com/34839199/49626866-0530b680-f9dc-11e8-92a8-ec37bf2056e1.png)

---

http://web.archive.org/web/20070705193930/http://www.thottbot.com:80/q9454
![5](https://user-images.githubusercontent.com/34839199/49626887-25f90c00-f9dc-11e8-89b7-b64e1e709f4e.png)

---

**Expected behaviour**: 
[[NPC]Acteon#17110](https://www.wowhead.com/npc=17110/acteon) should offer [[Quest]The Great Moongraze Hunt#9454](https://www.wowhead.com/quest=9454/the-great-moongraze-hunt) without having done the [[Quest]Red Snapper - Very Tasty!#9452](https://www.wowhead.com/quest=9452/red-snapper-very-tasty) => [[Quest]Find Acteon!#9453](https://www.wowhead.com/quest=9453/find-acteon)-chain

**Server Revision**: 
2402

**Comment by Shanghi** [comment]
This should be fixed in revision 2438. I feel ashamed for missing it before!
