### ISSUE TITLE
Swimming in mid-air after connected flight path

### ISSUE THREAD

**Issue by Erodraeda** [Atlantiss/NetherwingBugtracker#329]
[//]: # (Enclose links to things related to the bug using http://wowhead.com or any other TBC database.)
[//]: # (You can use screenshot ingame to visual the issue.)
[//]: # (Write your tickets according to the format:)
[//]: # ([Quest][Azuremyst Isle] Red Snapper - Very Tasty!)
[//]: # ([NPC] Magistrix Erona)
[//]: # ([Spell][Mage] Fireball)
[//]: # ([Npc][Drop] Ghostclaw Lynx)
[//]: # ([Web] Armory doesnt work)

**Description**: 
I got a flight path from stonetalon mountains to orgrimmar. after doing the connection in xroads, my character started swimming in mid air, instead of getting a mount again.
![screenshot_488](https://user-images.githubusercontent.com/40346279/45937787-fff5cb00-bf99-11e8-9879-98ed6599b964.png)

**Current behaviour**:
Swimming mid air
**Expected behaviour**: 
Mount up again
**Server Revision**:

**Comment by Wolffenstein** [comment]
Fixed in rev 2049.
