### ISSUE TITLE
[Bloodmyst Isle][Q]#9561 is incorrectly awarding 0xp, should give 1150xp

### ISSUE THREAD

**Issue by Tenoutoften** [Atlantiss/NetherwingBugtracker#3291]
**Description**: 
[[Quest]Nolkai's Words#9561](https://www.wowhead.com/quest=9561/nolkais-words) is turned in at [[Object]Mound of Dirt#181758](https://www.wowhead.com/object=181758/mound-of-dirt) and currently awards 0xp, should reward up to 1150xp.

---

Showing screenshot displaying no "Experienced Gained" in chat
![1](https://user-images.githubusercontent.com/34839199/49627402-f26bb100-f9de-11e8-89c0-5e82b82a06fc.png)

And a screenshot that this should show up, though this was confirmed to not give xp, and not just incorrectly not display it.
![2](https://user-images.githubusercontent.com/34839199/49627403-f26bb100-f9de-11e8-96e5-77fe98987c1b.png)

---

http://web.archive.org/web/20071214050302/http://thottbot.com:80/q9561
![31552637c093ee530e6bb324631552f9](https://user-images.githubusercontent.com/34839199/49627395-e54ec200-f9de-11e8-8e95-5fdf74a2e987.png)

**Current behaviour**:
0 xp on turn in

**Expected behaviour**: 
[[Quest]Nolkai's Words#9561](https://www.wowhead.com/quest=9561/nolkais-words) should reward 1150 xp based upon old thottbot.

**Server Revision**: 
2402

**Comment by Bildo** [comment]
fixed in rev 2410
