### ISSUE TITLE
[Azuremyst Isle][Misc, RP]NPC#18810 slightly incorrect RP text & lack crafting animation

### ISSUE THREAD

**Issue by Tenoutoften** [Atlantiss/NetherwingBugtracker#3292]
**Description**: 
* [[NPC]Otonambusi#18810](https://www.wowhead.com/npc=18810/otonambusi#comments)'s does slightly incorrect text on NW:
![4d5a18f71d1a497450ad711b1c76a9f4](https://user-images.githubusercontent.com/34839199/49628543-fbf81780-f9e4-11e8-8d25-f82b2bec4ec6.png)

* Should be saying "How can you have any pudding if you don't eat your fish?" seen [here on retail](https://www.youtube.com/watch?v=dUvfCHZJ-JI)

* [[NPC]Otonambusi#18810](https://www.wowhead.com/npc=18810/otonambusi#comments) is also seen [on retail](https://www.youtube.com/watch?v=dUvfCHZJ-JI) doing crafting animation, which makes sense since he is preparing fish.

Picture from [wowhead](https://www.wowhead.com/npc=18810/otonambusi#screenshots:id=112001) posted 2008, December 17th
![112001-otonambusi](https://user-images.githubusercontent.com/34839199/49628711-226a8280-f9e6-11e8-984d-c02175ba3dad.jpg)

---

Wowhead comments
![6beb6ab219a05d5c83f8e22ed982e68b](https://user-images.githubusercontent.com/34839199/49628548-01556200-f9e5-11e8-9a79-39a0331978e4.png)

---

**Current behaviour**:
* No crafting animation
* Incorrect text: "If you don't eat your fish, you can't have any pudding!"

**Expected behaviour**: 
- [ ] Crafting animation, except when doing his text
- [x] Correct text: "How can you have any pudding if you don't eat your fish?"

**Server Revision**: 
2402

**Comment by aresbrutus** [comment]
He actually says both the lines: https://i.imgur.com/COwzvxJ.png

**Comment by Tenoutoften** [comment]
Aha, my bad then

**Comment by Wolffenstein** [comment]
His model (and other similar Broken ones) do not support EMOTE_STATE_USESTANDING_NOSHEATHE emote animation until wotlk.
