### ISSUE TITLE
[Azuremyst Isle]NPC#17587 deals too much damage, should assist players, sometimes incorrectly offers Q#9612

### ISSUE THREAD

**Issue by Tenoutoften** [Atlantiss/NetherwingBugtracker#3293]
**Description**: 
* [[NPC]Draenei Youngling#17587](https://www.wowhead.com/npc=17587/draenei-youngling#comments) is suppose to be rescued by players, and upon receiving [[Spell]Gift of the Naaru#28880](https://www.wowhead.com/spell=28880/gift-of-the-naaru) do RP text-thanks and offer [[Quest]A Hearty Thanks!#9612](https://www.wowhead.com/quest=9612/a-hearty-thanks)

* Additionally note that aggroing a hostile mob and dragging it to [[NPC]Draenei Youngling#17587](https://www.wowhead.com/npc=17587/draenei-youngling#comments) should activate the NPC.

* Quest can be seen acquired [here, retail](https://youtu.be/d076BETWphk?t=30) - Published on Jun 20, 2007

---

Wowhead comments:
![2afc3e9c790dd36bbe3af0a5199302b5](https://user-images.githubusercontent.com/34839199/49635327-a4b37080-f9ff-11e8-8e66-6db7f6969e63.png)
![005f03ca89c7a3733ead8ccdb2ff3f9f](https://user-images.githubusercontent.com/34839199/49635329-a54c0700-f9ff-11e8-9676-4e41b7236b27.png)
![bc527d3d1b9182d44dfd54321770bec3](https://user-images.githubusercontent.com/34839199/49635330-a5e49d80-f9ff-11e8-9ffc-bdfe8fdad97e.png)

---

**Current behaviour**:
* [[NPC]Draenei Youngling#17587](https://www.wowhead.com/npc=17587/draenei-youngling#comments) incorrectly deals far too high damage, sometimes one hitting the mobs aggroing onto him. Can be seen [here, NW](https://www.youtube.com/watch?v=QYq3rRnA-Zc&feature=youtu.be)
* Incorrectly offers [[Quest]A Hearty Thanks!#9612](https://www.wowhead.com/quest=9612/a-hearty-thanks) when receiving [[Spell]Gift of the Naaru#28880](https://www.wowhead.com/spell=28880/gift-of-the-naaru) regardless if he has recently been in a fight or not. Can be seen [here, NW](https://www.youtube.com/watch?v=wV-K740TPq0&feature=youtu.be)
* Does not assist players with hostile mobs on them. Can be seen [here, NW](https://www.youtube.com/watch?v=MImJy-S6xhY&feature=youtu.be)

**Expected behaviour**: 
- [ ] Should deal significantly lower damage, but high enough that he will successfully kill the mob alone. He has a shield and 1 hander so should be rather tanky mob.(See [comment](https://www.wowhead.com/quest=9612/a-hearty-thanks#comments:id=46506) & [Video](https://youtu.be/d076BETWphk?t=30), takes damage and his health isn't noticeably dropping)
- [ ] Should assist players who has hostile mobs on them.([See comment](https://www.wowhead.com/quest=9612/a-hearty-thanks#comments:id=216347))
- [ ] Should only offer quest after receiving [[Spell]Gift of the Naaru#28880](https://www.wowhead.com/spell=28880/gift-of-the-naaru) after taking damage.

**Server Revision**: 
2402

**Comment by aresbrutus** [comment]
https://github.com/Atlantiss/AtlantissTBCBT/issues/102
