### ISSUE TITLE
[NPC][Spell][Rogue] Stealthing whilst getting in combat

### ISSUE THREAD

**Issue by towneh** [Atlantiss/NetherwingBugtracker#3296]
**Description**: 
I am able to cast stealth at the same time as getting in combat with an NPC.

**Current behaviour**:
https://youtu.be/WjVDKxZt1V0

**Expected behaviour**: 
I should either get in combat preventing me from Stealthing, or I should remain stealthed and the NPC not notice me. If I approach the NPC whilst in stealth to begin with, I do not get aggro.

**Server Revision**: 
2395

**Comment by Evolvee** [comment]
I dont see why it wouldnt be able to work as it is now? Stealth doesnt prevent you from getting aggro.
I dont know how it is for NPC, but if u stealth near player that casts somethng on you, he wont stop the cast if he still sees you in stealth too.

**Comment by nullfoxh** [comment]
While true what you're saying Evolve, being "aggroed" by players doesn't put you in combat.

This is simply a guess but it sort of feels like the stealth effect is applied with a delay and thus the mob can aggro you. Or the combat flag is set with a delay and allows you to stealth still, but I'm leaning toward the first option.

**Comment by nullfoxh** [comment]
To add, in the video the mob is facing away while aggroing a stealthed player, who wasn't aggroed while unstealthed from the same range. It's weird.

**Comment by towneh** [comment]
Footage of me being stealthed against the same NPC:
https://www.youtube.com/watch?v=OkF2EBL9Ih8
So this cannot just be him seeing through stealth normally.

**Comment by nullfoxh** [comment]
I'd say this video would support my theory of the stealth applying with a delay, either on the player, or just "in the eyes of the mob."

**Comment by Wolffenstein** [comment]
The NPC can still detect you even when you cast Stealth

**Comment by Fenvarien1** [comment]
https://gfycat.com/RecklessRapidFruitbat here you see another problem which should not be happening. 
you see the orc cast firebolt on you while i am in stealth and he stops again and again but repeats to cast it. then i walk away to lure him into another orc. both now try to cast firebolt but cancel it and repeat it.

**Comment by towneh** [comment]
Further to Fen's update, I have now tested by stealthing prior to purposefully getting aggro on the NPC by contacting them, and they are unable to cast a spell on me:
https://www.youtube.com/watch?v=edMKZLVqP38

**Comment by nullfoxh** [comment]
In response to Wolf: Compare aggro range from Towneh's first video: https://youtu.be/WjVDKxZt1V0 to the one where he is purposefully aggroing in the second video: https://www.youtube.com/watch?v=edMKZLVqP38

**Comment by towneh** [comment]
OK I'm going to post my bug video https://www.youtube.com/watch?v=edMKZLVqP38 as a separate issue so that it can be worked on with a bit more focus and not get confused with the aggro/combat issue here.

**Comment by killablink** [comment]
I feel like it was possible on retail too due to batching and how stealth takes a really short time to actually go through

**Comment by paoea** [comment]
I also noticed it and it feels weird. 

Does this message have to come up 3 times? 

![capture](https://user-images.githubusercontent.com/43524197/49689467-00761a80-fb22-11e8-904f-8eef1e49bf58.PNG)

**Comment by Godmatik** [comment]
Unable to reproduce - fixed at some point I am guessing
