### ISSUE TITLE
[Spell]Mind Controlling players affected by stuns enables the priest to move them around regardless

### ISSUE THREAD

**Issue by Tenoutoften** [Atlantiss/NetherwingBugtracker#3297]
**Description**: 
* If a player gets stunned by a mob, and then gets [[Spell]Mind Control(Rank 3)#10912](https://db.excalibur.ws/?spell=10912) by a priest, the priest will be able to move the player around - despite the player being stunned. Can be seen [here](https://www.youtube.com/watch?v=z3SolmG-7rI&feature=youtu.be)

**Expected behaviour**: 
Shouldn't be able to move CCed players, even if they are [[Spell]Mind Control(Rank 3)#10912](https://db.excalibur.ws/?spell=10912)

**Server Revision**: 
2402

**Comment by Wolffenstein** [comment]
Fixed in rev 2403.
