### ISSUE TITLE
[Core Mechanic]Unlimited leash without dealing dmg if someone else hits it, granted you keep agro

### ISSUE THREAD

**Issue by Tenoutoften** [Atlantiss/NetherwingBugtracker#3298]
**Description**: 
Mobs will keep attacking you even if you run hundreds of yards away, despite not dealing damage to the mob yourself under the condition that someone else keeps hitting it.
[Example](https://www.youtube.com/watch?v=Fpc9nXbF_8I)

This could be used for griefing other players.

For clarity, it has nothing to do with [[Spell]Mind Control#10912](https://db.excalibur.ws/?spell=10912), I reproduced it without it.

**Expected behaviour**: 
I'll admit I don't know for a 100% fact exactly how this should work, but I'd assume the mob will de-aggro and instead go for the player hitting it.

**Server Revision**: 
2402

**Comment by Wolffenstein** [comment]
That's intended and I see no reason why it shouldn't work like that.

**Comment by Tenoutoften** [comment]
Alright, sorry for wasting your time with this one, I should've researched it better myself. I'll do some research anyway for my own sake:)

---

http://wow.allakhazam.com/wiki/combat_%28WoW%29
**Escaping Combat**
>Note that if someone else pulls aggro from you or you continue to attack it, the traveling distance to leash the mob will reset.

>A few classes have alternate means of escaping combat. Best known among these is the hunter's Feign Death, which causes the hunter to flop on the ground and play dead. It is possible that the hunter's pet will remain in combat when this happens. Rogues also have an ability called Vanish that immediately puts them into a stealth state and makes their opponents lose track of them and run off. At much later levels, a Mage can also cast Invisibility to fade out of battle. **All of these abilities will produce the same results as leashing if there is nobody else with hate against the target.**

http://wow.allakhazam.com/wiki/Leash_%28WoW%29 - This page last modified 2009-06-15 16:01:32
>All non-instance mobs have the potential to "leash" when you try to run too far. When a player moves too far from where the combat began, the mob will run very quickly back to where they were beforehand and evade all attacks until they return. It is possible to go a long distance with a target -- Kiting is more difficult in WoW, but can still be done to targets that you are able to keep prodding as you move. **However, if you go long enough without adding additional aggro to the target, it will leash.**
