### ISSUE TITLE
[NPC][Spell][Stealth][Prowl] Caster NPC unable to finish spell cast whilst stealthed

### ISSUE THREAD

**Issue by towneh** [Atlantiss/NetherwingBugtracker#3299]
**Description**: 
Bonechewer Evoker (possibly more caster npcs) is unable to succesfully complete his spell cast whilst I am stealth ed and have purposefully gotten aggro.

**Current behaviour**:
https://www.youtube.com/watch?v=edMKZLVqP38

**Expected behaviour**: 
NPC should be able to attack me with a spell.

**Server Revision**: 
2402

**Comment by towneh** [comment]
Confirmed that this also happens with other NPCS. Tested with Firewing Warlocks in Terokkar:-

https://www.youtube.com/watch?v=koMxbhzkK58

**Comment by towneh** [comment]
Please mark as high priority.

**Comment by towneh** [comment]
Confirmed this also happens with Druids whilst Prowling in Cat form.

**Comment by Wolffenstein** [comment]
Fixed in rev 2403.
