### ISSUE TITLE
Skinning not working on mobs without drops

### ISSUE THREAD

**Issue by Niylah** [Atlantiss/NetherwingBugtracker#33]
[//]: # (Enclose links to things related to the bug using http://wowhead.com or any other TBC database.)
[//]: # (You can use screenshot ingame to visual the issue.)
[//]: # (Write your tickets according to the format:)
[//]: # ([Quest][Azuremyst Isle] Red Snapper - Very Tasty!)
[//]: # ([NPC] Magistrix Erona)
[//]: # ([Spell][Mage] Fireball)
[//]: # ([Npc][Drop] Ghostclaw Lynx)
[//]: # ([Web] Armory doesnt work)

**Description**: 
Skinning not working on mobs without drops

Prairie Wolf - Mulgore
Nightsabers - Teldrassil
Adult Plainstrider - Mulgore

Starving Ghostclaw - Ghostlands
Mistbat - Ghostlands
Tiger? - Eversong

**Current behaviour**:

**Expected behaviour**: 

**Server Revision**:

**Comment by Wolffenstein** [comment]
Could you write what mob exactly did you test it on?

**Comment by wowthings** [comment]
Happened to me with the Nightsabers at Teldrassil.
![wowscrnshot_092218_225345](https://user-images.githubusercontent.com/43504905/45921719-2d1f7c00-bebb-11e8-91a9-5546532bd160.jpg)

**Comment by Niylah** [comment]
Prairie Wolf in Mulgore

**Comment by MVerschoor** [comment]
The following mobs have the same issue. 
In Ghostlands, the tiger (Starving Ghostclaw?) and mistbat.
In Eversong, the Tiger. 
Don't remember the exact names.

**Comment by Wolffenstein** [comment]
Fixed in rev 2020.
