### ISSUE TITLE
([Spell][NPC+Shaman]Lightning Shield)

### ISSUE THREAD

**Issue by killablink** [Atlantiss/NetherwingBugtracker#330]
**Description**: Lightning shield is currently giving spell pushback.

**Current behaviour**: If you cast a spell that has travel time say fireball, cast another one while the first one is traveling and deals damage to a mob with lightning shield, the lightning shield damage is giving spell pushback to your next spell

**Expected behaviour**: Lightning shield shouldn't give spell pushback. I can't test it right now since I'm not high level enough but maybe this behavior is reproduced with molten armor and other spells that trigger damage when hit. Tried searching for proof for that but there aren't really any info and tried to search for elemental shaman pvp videos but couldn't find a good clip yet. If you guys have proof that it should give spell pushback I'd like to see it please!

**Server Revision**: 2040

**Comment by Zuntrix** [comment]
Here is video proof
https://imgur.com/XJLyD8M 

Revision 2060

**Comment by killablink** [comment]
This really needs fixing for release because a lot of low leveling zones have shamans or trolls with lightning shield and it completely destroys casters right now

**Comment by killablink** [comment]
Closing because should be fixed in 2486
