### ISSUE TITLE
[NPC ][Dungeon] Heroic Talon King Ikiss

### ISSUE THREAD

**Issue by Dirge123** [Atlantiss/NetherwingBugtracker#3300]
Combat starts as soon as anyone engages the boss and when the boss casts his immunity you can exit combat and sit and drink (if you haven't hit the boss or done any action to provoke combat)

Both of those instances are incorrect.
https://www.youtube.com/watch?v=O7dFFjfktCc

**Comment by devo6969** [comment]
This is fixed, couldn't recreate
