### ISSUE TITLE
[Dungeon] [Shattered Halls] Warbringer O'mrogg

### ISSUE THREAD

**Issue by Kinson72** [Atlantiss/NetherwingBugtracker#3304]
On a Warbringer O'mrogg attempt in Shattered Halls today, an aggro reset/drop didn't seem right to a few in our group.  I was the last dps alive and my target of target and omen showed me as the boss' primary target.  The boss was positioned on the stairs of the arena and was stationary with me targeted for a good 5 seconds.  I may have missed a cast bar or mechanic that would cause this but it may be something to look out for.  Edit: Ive watched a few videos about it and see he turns red when he aoe fears then casts.  I do remember looking at the boss as this was happening and he was red, but it seemed longer than the combo in what I've watched.  Revision 2402

**Comment by Drayo** [comment]
Can confirm this, sometimes he just stands around and looks at people, it feels a bit odd.

I did find a video where he does something similar on retail though, might be part of his fixate ability. Not sure how he works exactly, it does not seems like a straight up threat wipe. He might be doing it for too long on NW.

https://youtu.be/tsyBghAsxJY?t=72

Shortly after 1.12.

**Comment by Camarila** [comment]
Can Confirm his anger mode seems to be longer than perhaps it should be?
Can't find a source of how long it should be exactly though..
Server revision: 2749

**Comment by devo6969** [comment]
I tried recreating "he just stands around and looks at people" when the boss enrages and maybe its due to the pathing of the stairs,  I saw nothing when you would tank in him the middle.
PTR - https://youtu.be/wy1xhsc_LBo?t=32
