### ISSUE TITLE
[NPC] Karazhan Phantom Valet

### ISSUE THREAD

**Issue by ta55el** [Atlantiss/NetherwingBugtracker#3305]
**Current behaviour**: Hits too hard. 9-10k on tank

**Expected behaviour**: 
http://wowwiki.wikia.com/wiki/Phantom_Valet?oldid=1209312
He should hits for 10k on cloth.

**Server Revision**:  2402

**Comment by ta55el** [comment]
He hits harder now than most of the bosses in TBC xD

**Comment by Drayo** [comment]
Invalid considering the CC value adjustments. Can probably be closed.
