### ISSUE TITLE
[Core][Combat][Priest][Mind Control] 

### ISSUE THREAD

**Issue by killablink** [Atlantiss/NetherwingBugtracker#3306]
**Description**: Lots of bugs regardings mind control + combat so here we go:

https://gfycat.com/TautFixedFurseal
Bug 1:First if you hit more than once a target that is mind controlled, you will forever stuck in combat as you see 30 seconds in ish.
Bug 2: At 0:48 seconds I defeat the druid and get out of combat, but my swords are still out, as if I was still in combat. As soon as I target the priest, my auto attacks goes off and attack him.
Bug 3: After attacking the priest when I was "out of combat" from the druid, I get stuck in combat forever.

https://gfycat.com/DirtyRecentAnura
Bug 4: It eventually led to this bug due to me still having my sword out, I was able to attack the same faction.
You can also see that after killing the druid, I get out of combat but my swords at still out and directly try to attack the priest after only clicking him when it shouldn't be the case.

How to reproduce bug 4: Duel same faction, have it mind controlled and kill him while stuck in combat. Then priest mind controls again and then I can auto attack him to death after it breaks.

**Current behaviour**:

**Expected behaviour**: 

**Server Revision**:

**Comment by Godmatik** [comment]
Getting stuck in combat from MC was fixed a long time ago - closing
