### ISSUE TITLE
[Spell][Priest] Mind Vision (Resist on friendly players)

### ISSUE THREAD

**Issue by Thugli** [Atlantiss/NetherwingBugtracker#3308]
[//]: # (Enclose links to things related to the bug using http://wowhead.com or any other TBC database.)
[//]: # (You can use screenshot ingame to visual the issue.)
[//]: # (Write your tickets according to the format:)
[//]: # ([Quest][Azuremyst Isle] Red Snapper - Very Tasty!)
[//]: # ([NPC] Magistrix Erona)
[//]: # ([Spell][Mage] Fireball)
[//]: # ([Npc][Drop] Ghostclaw Lynx)
[//]: # ([Web] Armory doesnt work)
[//]: # (To find server revision type `.server info` command in the game chat.)

**Description**: 
Mind vision occasionally resists on friendly targets.
**Current behaviour**:
https://clips.twitch.tv/HyperDeadWrenResidentSleeper
**Expected behaviour**: 
Mind vision should not be able to resist a friendly target.

**Server Revision**: 
2407

**Comment by devo6969** [comment]
Since Mind Vision can be casted on unfriendly players I think the spell is intended to resist regardless friendly/unfriendly. Can't find any information supporting this behavior.

**Comment by Wolffenstein** [comment]
Fixed in rev 3465.
