### ISSUE TITLE
[NPC][Ghostclaw Lynx] Taking too long to reset

### ISSUE THREAD

**Issue by Thugli** [Atlantiss/NetherwingBugtracker#331]
[//]: # (Enclose links to things related to the bug using http://wowhead.com or any other TBC database.)
[//]: # (You can use screenshot ingame to visual the issue.)
[//]: # (Write your tickets according to the format:)
[//]: # ([Quest][Azuremyst Isle] Red Snapper - Very Tasty!)
[//]: # ([NPC] Magistrix Erona)
[//]: # ([Spell][Mage] Fireball)
[//]: # ([Npc][Drop] Ghostclaw Lynx)
[//]: # ([Web] Armory doesnt work)

**Description**: 
At approximetly 69, 37 in Ghostlands, two ghostclaw lynx kept chasing my pet and I for a really long time.
**Current behaviour**:
Video of bugged behaviour can be seen here:
https://clips.twitch.tv/BoldNurturingDoveJKanStyle
**Expected behaviour**: 
These mobs should reset sooner.
**Server Revision**:

**Comment by Godmatik** [comment]
Known issue.

#169
