### ISSUE TITLE
[Shattrath] Safe Zone incorrect, can attack inside Shatt

### ISSUE THREAD

**Issue by killablink** [Atlantiss/NetherwingBugtracker#3310]
**Description**:  https://gfycat.com/OldfashionedSaltyGermanpinscher A part inside the tunnel isn't actually safe, can attack other faction

**Current behaviour**:

**Expected behaviour**: Should be safe all the way.

**Server Revision**: 2407

**Comment by killablink** [comment]
Not sure what needs research for this

**Comment by devo6969** [comment]
This is still a thing on Retail BFA. It is intended. Will go from Sanctuary, half way through the tunnle I go into contested territory then near the end back you sanctuary.  

Retail BFA - https://www.youtube.com/watch?v=7U82u96KMTs
