### ISSUE TITLE
[NPC][Dungeon] Heroic Talon King Ikiss pre 2.1

### ISSUE THREAD

**Issue by Fenvarien1** [Atlantiss/NetherwingBugtracker#3312]
**Description**: 
NPC: Talon King Ikiss
http://db.hellfire-tbc.com/?npc=18473

Wrong Level+
Sheep isn't working as intended+
Arcane Explosion don't kills you pre 2.1
Arcane Volley dmg isn't 2000dmg+ pre 2.1

i played myself as paladin tank

level report: https://github.com/Atlantiss/NetherwingBugtracker/issues/2865

**Current behaviour**:
**First of the level research**:
Date(19.06.2007)Patch(2.1.2) https://youtu.be/O7dFFjfktCc?t=32 Level 72
![72-1](https://user-images.githubusercontent.com/44606340/49683727-caa54780-fac9-11e8-9a4a-ce02c5dc2852.jpg)
Date(15.08.2007)Patch(2.1.3) https://youtu.be/jsp6n_ssyjk?t=267 Level 72
![72-2](https://user-images.githubusercontent.com/44606340/49683755-253ea380-faca-11e8-8075-9e4ac723a823.jpg)
https://www.youtube.com/watch?v=aw2V_wlfbAY - better quality - after Patch 2.1

but i couldn't find any level change on Talon King Ikiss during my research.

**Sheep heal**:
_Heal is missing. can't actually proof it right now because i didn't record the fight. but i am sure it didn't healed me._

_Sheep Heal proof_:
https://youtu.be/U6VaJLmltMU?t=64 (NHC fight)
https://youtu.be/W1LGW01ZPsY?t=75 (HC Fight) - MT got CC with sheep by Talon Ikiss and heals 30% within seconds while the Healer PoV is casting ShadowWord Pain(at that point the tank got sheeped) and Mindblast(during that cast he got healed)
https://youtu.be/W1LGW01ZPsY?t=52 (HC Fight) Healer PoV got sheeped and healed up wihtout a HOT.

**Sheep Break**:
i could not break my sheep with my Sacrifice-Spell(transfer dmg to me). this i am 100% sure it didn't. - there i need research help - but tbh thats common sheep break mechanic. maybe i am wrong.

**EDIT: found proof it didn't break from damage taken.**

**Arcane Explosion after Teleport+Arcane Volley**:
http://eu.battle.net/wow/de/game/patch-notes/2-1-0 (GERMAN LANGUAGE) - Official Website
translated:
_Talon King Ikiss on Heroic difficulty has been significantly reworked. He now has a point blank area of effect slow spell, increased damage on the Arcane volley , increased damage on the Arcane Explosion, and reduced the frequency on his Polymorph_. 

_Current: Arcane Explosion kills you and the Arcane Volley deals 1500-3200 damage_
(from my logs)(proof it later when i am back home or run sethekk again - depends on recount logs available or not)

https://youtu.be/W1LGW01ZPsY?t=96
**The Healer PoV got sheeped during teleport. He got hit by both within 2seconds**
![damage](https://user-images.githubusercontent.com/44606340/49684198-c4ff3000-fad0-11e8-9b84-fa017e03c5ba.jpg)
Explosion-dmg: 2565(2565 resisted) 5130damage
Volley: 1352(451 resisted) 1803damage

Volley damage during the complete PoV:
1. 1314(438R) - 1752
2. 1255(418R) - 1673
3. 655(1304R) - 1959
4. 872(872R) - 1744
5. 832(832R) - 1664
6. 441(1321R) - 1762
7. 1251(417R) - 1668
8. 1352(451R) - 1803
9. 1322(467R) - 1789
10. 1293(431R) - 1724
-Boss Dead- average damage: 1751,8; 1664-1959range

That's not accurate but we can tell it does not exceed 2000k damage in total. it barely reaches the 1800damage and the video is a proof for the official patchnotes nerfed Talon Ikiss pre 2.1

**Server Revision**: 
2405

**Comment by Manaci** [comment]
Irrelevant now/Fixed
