### ISSUE TITLE
[NPC][Dungeon][Sethekk Halls] Missing Pack

### ISSUE THREAD

**Issue by Fenvarien1** [Atlantiss/NetherwingBugtracker#3313]
**Description**: 
5 man Pack missing infront of Talon King Ikiss - NHC+HC

ANOTHER TICKET: https://github.com/Atlantiss/NetherwingBugtracker/issues/2484

**Current behaviour**:
-missing at all-

**Expected behaviour**: 
5 man pack
Date(26.07.2007)https://youtu.be/H_yzBuSdtwE?t=29 Tank PoV - he is looking towards Talon King Ikiss and you can clearly see a Bird patrol from the pack and other infront of Talon King Ikiss.
Date(16.08.2007)https://youtu.be/XSSuOTj8Ozo?t=119 Tank PoV - same. you can see the pack even better.
![unbenannt](https://user-images.githubusercontent.com/44606340/49684690-9b95d280-fad7-11e8-8212-4414d289828b.jpg)

Date(12.04.2008)https://youtu.be/jUxPMFyyk2s?t=19 here you see it perfectly.
![unbenannt](https://user-images.githubusercontent.com/44606340/49684768-85d4dd00-fad8-11e8-90a5-087afc36991c.jpg)
Left to right:
1. Sethekk Talon Lord http://db.hellfire-tbc.com/?npc=20701#abilities
2. Sethekk Prophet http://db.hellfire-tbc.com/?npc=20695#abilities
3. Sethekk Shaman http://db.hellfire-tbc.com/?npc=20699#abilities
4. Time-Lost Shadowmage http://db.hellfire-tbc.com/?npc=20698#abilities
5. Avian Warhawk http://db.hellfire-tbc.com/?npc=21990#abilities

Date(22.02.2007)Patch(pre 2.1- one month after release) NON HEROIC proof - best view https://youtu.be/ig1F_dk5R5s?t=226
The bird got a patrol script form left to right.
![1](https://user-images.githubusercontent.com/44606340/49685018-7c4d7400-fadc-11e8-844d-28c7768d22f7.jpg)

better view on positioning.
![2](https://user-images.githubusercontent.com/44606340/49685031-b0c13000-fadc-11e8-90da-1e1e1d1acccb.jpg)

**Server Revision**: 
2405

**Comment by aresbrutus** [comment]
https://i.imgur.com/DDPxslm.jpg

**Comment by aresbrutus** [comment]
Fixed in rev `Nariman`
