### ISSUE TITLE
[Talent][Hunter] Improved Revive Pet

### ISSUE THREAD

**Issue by ta55el** [Atlantiss/NetherwingBugtracker#3314]
**Current behaviour**: With talent sspell "Revive Pet" cost 1623 mana but we cant cast this spell when ur mana is less than cost of the original spell. Mana consume is good.

**Server Revision**: 2402

**Comment by Tenoutoften** [comment]
I don't understand completely, could you please explain some more?

I made a Draenei Hunter, which at level 70 got:
4458 Health
4273 Mana

Cost of Revive Pet = 2706 Mana
Cost of 1/2 imp Revive Pet = 2164 Mana (2706 Mana * 0.8 (20% Reduction))
Cost of 2/2 imp Revive Pet = 1623 Mana (2706 Mana * 0.6 (40% Reduction))

**Comment by Wolffenstein** [comment]
It really is bugged, but will be fixed in rev 2409.
