### ISSUE TITLE
[Quest] A Fair Trade

### ISSUE THREAD

**Issue by lynxzor** [Atlantiss/NetherwingBugtracker#3315]
**Description**: Offers completion text right away instead of the quest objective text

![wowscrnshot_120818_160115](https://user-images.githubusercontent.com/795881/49687963-eed14a80-fb02-11e8-8586-92ba54737cf4.jpg)

**Current behaviour**: Offers quest completion text before the objective text

**Expected behaviour**: Give the quest objective text first
https://wow.gamepedia.com/A_Fair_Trade_(Orgrimmar)
**Server Revision**: 2407

**Comment by Bildo** [comment]
fixed in rev 2410
