### ISSUE TITLE
[Spell][Warrior] charge/intercept is wrong

### ISSUE THREAD

**Issue by antikiller69** [Atlantiss/NetherwingBugtracker#3316]
[//]: # (Enclose links to things related to the bug using http://wowhead.com or any other TBC database.)
[//]: # (You can use screenshot ingame to visual the issue.)
[//]: # (Write your tickets according to the format:)
[//]: # ([Quest][Azuremyst Isle] Red Snapper - Very Tasty!)
[//]: # ([NPC] Magistrix Erona)
[//]: # ([Spell][Mage] Fireball)
[//]: # ([Npc][Drop] Ghostclaw Lynx)
[//]: # ([Web] Armory doesnt work)
[//]: # (To find server revision type `.server info` command in the game chat.)

**Description**:  charge/intercept

**Current behaviour**:
charge/intercept stun starts instantly instead when landing on target therefore u lose stun before u reach target
**Expected behaviour**: 
charge/intercept stun should start when u land on target instead wasting seconds on travelling time
https://youtu.be/VZk1NJXHUqk?t=141
**Server Revision**:

**Comment by Wolffenstein** [comment]
https://www.youtube.com/watch?v=p5ZX2s-7bVY&feature=youtu.be
https://youtu.be/XeCiG5eJyfE?t=40s

**Comment by Tenoutoften** [comment]
Looks like the stun starts about midway through the charge on the retail videos but they happen almost instantly on NW videos

[Swift video](https://www.youtube.com/watch?v=VZk1NJXHUqk&feature=youtu.be&t=141)
* Charge stun happen 5.5 "night elf steps" into it.

**Comment by towneh** [comment]
The best example I have of mid-air charge against a mounted moving target, and how the stun is applied and where my character ends up at the player: https://youtu.be/oin8NQXGY0s?t=130

**Comment by antikiller69** [comment]
oh i tho this was closed ald? well good to see it might be bugged atm

**Comment by Easyfraggy** [comment]
It should just apply stun with spell delay like any other debuff in the game. So 0-400ms.

**Comment by towneh** [comment]
So what about the mechanic of following moving targets during the charge, popular vanilla servers also do not do this.

**Comment by Evolvee** [comment]
@Wolffenstein just look into my spell delay research and ctrl + f "intercept"

this thread is pointless

**Comment by antikiller69** [comment]
so any news if issue has been fixed?

**Comment by Godmatik** [comment]
Spell delay was turned disabled years ago, so this thread is now pointless.

Closing.
