### ISSUE TITLE
[Quest]#9931 proximity bug of [Object]#182354 prevents usage of Qitem#25555=>Spell#32314

### ISSUE THREAD

**Issue by Tenoutoften** [Atlantiss/NetherwingBugtracker#3317]
**Description**: 
* In [[Quest]Returning the Favor#9931](https://www.wowhead.com/quest=9931/returning-the-favor) the objective is to kill [[NPC]Warmaul Shaman#18064](https://www.wowhead.com/npc=18064/warmaul-shaman) & [[NPC]Warmaul Reaver#17138](https://www.wowhead.com/npc=17138/warmaul-reaver) and use your provided quest item, [[Item]Kil'sorrow Banner#25555](https://www.wowhead.com/item=25555/kilsorrow-banner) which will plant a [[Object]Kil'sorrow Banner#182354](https://db.excalibur.ws/?object=182354) through the usage of [[Spell]Plant Kil'sorrow Banner#32314](https://www.wowhead.com/spell=32314/plant-kilsorrow-banner)

* The issue is when the corpses of NPC are too close together, planting a [[Object]Kil'sorrow Banner#182354](https://db.excalibur.ws/?object=182354) becomes impossible with misleading error message "Item is not ready yet."(https://github.com/Atlantiss/NetherwingBugtracker/issues/2534).

* Note that this doesn't exactly seem to be the proximity between the [[Object]Kil'sorrow Banner#182354](https://db.excalibur.ws/?object=182354), but something to do with your characters distance towards the [[Object]Kil'sorrow Banner#182354](https://db.excalibur.ws/?object=182354) notice how in the [video](https://youtu.be/mndR0Hq3ETU?t=19) I can't use the [[Spell]Plant Kil'sorrow Banner#32314](https://www.wowhead.com/spell=32314/plant-kilsorrow-banner) at first, but as I walk further away from the [[Object]Kil'sorrow Banner#182354](https://db.excalibur.ws/?object=182354) I get to use [[Item]Kil'sorrow Banner#25555](https://www.wowhead.com/item=25555/kilsorrow-banner) => [[Spell]Plant Kil'sorrow Banner#32314](https://www.wowhead.com/spell=32314/plant-kilsorrow-banner) just fine.

* You can't plant a banner on [[NPC]Zorbo the Advisor#18413](https://www.wowhead.com/npc=18413/zorbo-the-advisor) due to error message "You can't do that yet". I'd assume you should be able to as he is indirectly described as the leader of [[NPC]Warmaul Shaman#18064](https://www.wowhead.com/npc=18064/warmaul-shaman) & [[NPC]Warmaul Reaver#17138](https://www.wowhead.com/npc=17138/warmaul-reaver) in [[Quest]Wanted: Zorbo the Advisor#9939](https://www.wowhead.com/quest=9939/wanted-zorbo-the-advisor)
>"Zorbo the Advisor, wanted for numerous planned attacks on Garadar. Along with his reavers and shaman, Zorbo has slain countless orcs. Consider Zorbo as armed, dangerous, and merciless.

>Zorbo makes his home in the Laughing Skull Ruins in the northern mountains of Nagrand."

**Current behaviour**:
Killing a group of Ogres in a pile will prevent players from using provided quest item

**Expected behaviour**: 
Expected to be able to place banners regardless of how close the banners are.
[Retail video](https://youtu.be/KcXbapzVTs8?t=159) from later expansion

**Server Revision**: 
2407

**Comment by Tenoutoften** [comment]
affects https://www.wowhead.com/quest=9666/declaration-of-power too

**Comment by Wolffenstein** [comment]
Fixed in rev 3370.
