### ISSUE TITLE
[Spell] Seed of corruption

### ISSUE THREAD

**Issue by Tzunamii** [Atlantiss/NetherwingBugtracker#3319]
**Description**:  Before Patch 2.0.7 Seed of corruption could proc of each other so if u had 10 seeds up and 1 seed detonated all 10 seeds detonated at after the first bringing a hugh AoE Burst.

**Current behaviour**: Every seed got it's own timer and doesn't react to one another

**Expected behaviour**:   [Seed of Corruption] cannot proc off of its own damage. It used to go off when another seed exploded. Now it doesn't react to other seeds. Shadowfury and rain of fire work to proc them though. [BEFORE PATCH 2.0.7] after this is fixed.

https://wow.gamepedia.com/Patch_2.0.7_(undocumented_changes)

**Server Revision**: 2407

**Comment by aresbrutus** [comment]
Class spells and talents are 2.4.3.
