### ISSUE TITLE
[Spell] Crusader Strikee

### ISSUE THREAD

**Issue by Tzunamii** [Atlantiss/NetherwingBugtracker#3320]
**Description**:  https://wow.gamepedia.com/Patch_2.0.3_(undocumented_changes)

**Current behaviour**: it is a 6sec cooldown after 2.0.3 it should be 10sec

**Expected behaviour**:  10sec CD as of patch 2.0.3

**Server Revision**: 2407

**Comment by sweetbakery** [comment]
The Burning Crusade Patch 2.3.0 (2007-11-13): Cooldown reduced from 10 to 6 seconds. 

Your report is invalid cuz post past 2.3 this change was reverted.

**Comment by Tzunamii** [comment]
yes but the current patch on the server is at 2.0.3 so it is valid

**Comment by aresbrutus** [comment]
Class spells and talents are 2.4.3.
