### ISSUE TITLE
[Spell] Silencing Shot

### ISSUE THREAD

**Issue by Tzunamii** [Atlantiss/NetherwingBugtracker#3321]
**Description**:  Silencing Shot should be 75% of weapon damage, but it is 50% this was changed in patch 2.0.6

**Current behaviour**: 50% damage of weapon damage

**Expected behaviour**:  should be 75% until patch 2.0.6 then changed to 50%

**Server Revision**: 2407

**Comment by aresbrutus** [comment]
Class spells and talents are 2.4.3.
