### ISSUE TITLE
[Spell] Counter spell

### ISSUE THREAD

**Issue by Tzunamii** [Atlantiss/NetherwingBugtracker#3322]
**Description**: Counter spell should trigger the GCD  before patch 2.0.6
https://wow.gamepedia.com/Patch_2.0.6

**Current behaviour**: Does not Trigger the GCD

**Expected behaviour**: Should trigger GCD

**Server Revision**: 2407

**Comment by aresbrutus** [comment]
Class spells and talents are 2.4.3.
