### ISSUE TITLE
[Spell] Dire Bear Form ( Bear Form )

### ISSUE THREAD

**Issue by Tzunamii** [Atlantiss/NetherwingBugtracker#3325]
**Description**: Dire bear form should crant 25% stamina and give 450% armor until patch 2.0.10
Can't test Bear form but i guess same thing is here.
https://wow.gamepedia.com/Patch_2.0.10

**Current behaviour**: Grants 25% stamina and 400% armor 
**Expected behaviour**:  Grant 25% Health and 450% armor

**Server Revision**: 2407

**Comment by aresbrutus** [comment]
Class spells and talents are 2.4.3.
