### ISSUE TITLE
[Talent] Savage Fury

### ISSUE THREAD

**Issue by Tzunamii** [Atlantiss/NetherwingBugtracker#3326]
**Description**: Before patch 2.0.10 Talent Savage fury should also grant bonus damage to some of Bear forms Damage abilitys
https://wow.gamepedia.com/Patch_2.0.10

**Current behaviour**: No Bonus damage

**Expected behaviour**: 10/20% Increased damage on Maul, Swipe, Mangle

**Server Revision**: 2407

**Comment by aresbrutus** [comment]
Class spells and talents are 2.4.3.
