### ISSUE TITLE
Mind controlled target teleports to their target after it is over

### ISSUE THREAD

**Issue by Mikik3jr** [Atlantiss/NetherwingBugtracker#3327]
[//]: # (Enclose links to things related to the bug using http://wowhead.com or any other TBC database.)
[//]: # (You can use screenshot ingame to visual the issue.)
[//]: # (Write your tickets according to the format:)
[//]: # ([Quest][Azuremyst Isle] Red Snapper - Very Tasty!)
[//]: # ([NPC] Magistrix Erona)
[//]: # ([Spell][Mage] Fireball)
[//]: # ([Npc][Drop] Ghostclaw Lynx)
[//]: # ([Web] Armory doesnt work)
[//]: # (To find server revision type `.server info` command in the game chat.)

**Description**: 
In Karazhan a Spectral Retainer mind controlled our tank. OFC we wiped and I ran away and reset the trash. On my way running away the tank was still mind controled.

**Current behaviour**:
After MC was over the tank instantly teleported to me.
https://www.youtube.com/watch?v=9XKaPCYOnY4&feature=youtu.be

**Expected behaviour**: 
This shouldn't happen.

**Server Revision**: 
2407

**Comment by Brasso** [comment]
This happens at Lady Vash'j aswell. Copy paste from persuasion thread that got closed.

https://clips.twitch.tv/MildRelatedClamJonCarnage Paladin teleports at around 11s.

https://clips.twitch.tv/AmazonianBlightedHerbsNomNom Tank gets teleported to platform at the end.

**Comment by Godmatik** [comment]
Fixed a while ago
