### ISSUE TITLE
[Talent] Predatory Instincts

### ISSUE THREAD

**Issue by Tzunamii** [Atlantiss/NetherwingBugtracker#3328]
**Description**:  Should have increased crit on the talents before patch 2.0.10 but instead uses newer patch crit fix.
https://wow.gamepedia.com/Patch_2.0.10

**Current behaviour**:2/4/6/8/10% Crit bonus per point spent 

**Expected behaviour**: 3/6/9/12/15% Crit bonus per point spent

**Server Revision**: 2407

**Comment by Mikik3jr** [comment]
Spells and Talents are 2.4.3, check Discord information text channel.

**Comment by aresbrutus** [comment]
Class spells and talents are 2.4.3.
