### ISSUE TITLE
[Talent] Improved Leader of the Pack

### ISSUE THREAD

**Issue by Tzunamii** [Atlantiss/NetherwingBugtracker#3329]
**Description**:  Improved Leader of the Pack Should be able to Crit heal before patch 2.0.10
https://wow.gamepedia.com/Patch_2.0.10

**Current behaviour**: Does not Crit heal

**Expected behaviour**: Should be able to crit heal

**Server Revision**: 2407

**Comment by Mikik3jr** [comment]
Spells and Talents are 2.4.3, check Discord information text channel.
