### ISSUE TITLE
([Quest]) "The Prophecy of Akida" somewhat broken

### ISSUE THREAD

**Issue by Rebelyna** [Atlantiss/NetherwingBugtracker#333]
[//]: # ([Quest][Azuremyst Isle] Prophecy of Akida)
[//]: # ([NPC] Stillpine Captive)

**Description**:
Accepted the quest last night, got 1 key and freed 1 captive, so my quest counter is at 1/8 freed. Then went to bed. Now, I am not getting progress for the quest after I freed several Stillpine Captives, still at 1/8. Also when the captives mention you there is a bug in the text when they try to talk to you with your name, it says something like: "Thank you, %n!"

**Current behaviour**:
Not receiving quest progress when freeing captives, while it worked last night before I went to bed.
Also the NPC says: "Thank you, %n!"

**Expected behaviour**: 
Receiving quest progress when freeing captives.
The NPCs should be able to speak to you with your name. :)

**Server Revision**: 
rev 2040 I guess?

**Comment by Easyfraggy** [comment]
Duplicate https://github.com/Atlantiss/NetherwingBugtracker/issues/271
