### ISSUE TITLE
If mind controlled target is killed then runs back and joins the fight that person stays in combat

### ISSUE THREAD

**Issue by Mikik3jr** [Atlantiss/NetherwingBugtracker#3330]
[//]: # (Enclose links to things related to the bug using http://wowhead.com or any other TBC database.)
[//]: # (You can use screenshot ingame to visual the issue.)
[//]: # (Write your tickets according to the format:)
[//]: # ([Quest][Azuremyst Isle] Red Snapper - Very Tasty!)
[//]: # ([NPC] Magistrix Erona)
[//]: # ([Spell][Mage] Fireball)
[//]: # ([Npc][Drop] Ghostclaw Lynx)
[//]: # ([Web] Armory doesnt work)
[//]: # (To find server revision type `.server info` command in the game chat.)

**Description**: 
In Karazhan Spectral Retainers mind controll. First our Shaman (Name: Moya) was mind controlled so we killed her. After that our priest (Name: Medcu) was controlled so we killed him.

**Current behaviour**:
-> Moya released, then ran back and joined in our fight again.
-> Medcu used Soulstone and joined back in our fight again.
-> Both of them remained in combat after the fight.
https://www.youtube.com/watch?v=sMJV7M2i6U0&feature=youtu.be

**Expected behaviour**: 
IMO this shouldn't happen.

**Server Revision**: 
2407

**Comment by killablink** [comment]
#3306  , if you attack a mind controlled target, you just get stuck in combat

**Comment by Godmatik** [comment]
Fixed a long time ago
