### ISSUE TITLE
[Talent] Moonkin Form

### ISSUE THREAD

**Issue by Tzunamii** [Atlantiss/NetherwingBugtracker#3331]
**Description**: Should only have 360% armor instead of 400% before patch 2.0.10
https://wow.gamepedia.com/Patch_2.0.10

**Current behaviour**: Gives 400% armor

**Expected behaviour**: Give 350% armor

**Server Revision**: 2407

**Comment by Mikik3jr** [comment]
Spells and Talents are 2.4.3, check Discord information text channel.

**Comment by aresbrutus** [comment]
Class spells and talents are 2.4.3.
