### ISSUE TITLE
[Spell] [Warlock] Health Funnel

### ISSUE THREAD

**Issue by RealZwox** [Atlantiss/NetherwingBugtracker#3332]
Health Funnel is not working correkt when the Warlock is low health.

Current:

https://youtu.be/R3Paoe5zWZY
and
https://youtu.be/ClDFAJ57Ack

The Warlock should die and not get rezzed like a Hunter.

**Comment by BamboozleNW** [comment]
Tested on Kara PTR. I died, did not res, seems to be working now. https://www.youtube.com/watch?v=PnkyBpe9TMQ
