### ISSUE TITLE
GM leveled 70 pet auto attacking for 10-80

### ISSUE THREAD

**Issue by Gattious** [Atlantiss/NetherwingBugtracker#3333]
**Description**:  Pet is white hitting for 10-80... Mostly 30-50, without cobra reflexes.

**Current behaviour**:  Pet is white hitting for avg of 30-50 with these stats https://gyazo.com/988d518c2c09448f195e37c223c6e555
No cobra reflexes.

**Expected behaviour**: 
 Not to hit like a wet noodle.
**Server Revision**:

**Comment by Tenoutoften** [comment]
Likely because of https://github.com/Atlantiss/NetherwingBugtracker/issues/3404. Pets don't update stats atm unless they are dismisses/resummoned or relog

**Comment by Tenoutoften** [comment]
I tested this with a Gm leveled pet myself, with and without talents, with and without gear and it for roughyl 100.

**Comment by Manaci** [comment]
Fixed
