### ISSUE TITLE
[Visual Bug] "Refer-a-Friend" instead of "rested" XP.

### ISSUE THREAD

**Issue by Gniddikon** [Atlantiss/NetherwingBugtracker#3334]
**Description**: The combat log says (+ xx Refer-A-Friend bonus) instead of rested bonus

**Current behaviour**: says Refer-A-Friend

**Expected behaviour**: Should say rested. It also should **not** say "(+ 0 xp) if there is no rested status.

**Server Revision**: 2407

Screenshot: https://imgur.com/a/vZfM7yq

**Comment by Valywave** [comment]
Same Issue, exept I had no rested exp/bar.

Screenshot of the same problem: [https://imgur.com/a/3MF2clA](url)

**Comment by Tenoutoften** [comment]
This can happen to mobs and map exploring. Not sure why

**Comment by wtRCH** [comment]
Did you clean your Cache? We don't and we won't have any Refer-a-Friend program on TBC.

**Comment by Tenoutoften** [comment]
This is with clean Cache

**Comment by Wolffenstein** [comment]
Fixed in rev 2416.
