### ISSUE TITLE
Improved Righteous Fury paladin talents not working?

### ISSUE THREAD

**Issue by jarkasna** [Atlantiss/NetherwingBugtracker#3336]
Regular Righteous Fury increases threat from holy damage by 60%. The improved talents 3/3 increases this by another 50% for a total of 90% increased threat from holy damage, but when you mouse over the buff it still says 60%. I can't confirm if the extra threat is not working or if this is only a spelling mistake. 

Thanks.

**Comment by towneh** [comment]
This is due to talents not affecting the tooltip/buff description, although they actually are, this is a restriction of the client and can only be fixed with add-ons.

**Comment by Wolffenstein** [comment]
What towneh said. Tooltips don't display talent changes.
