### ISSUE TITLE
[Q]Crackin' some Skulls#10009 NPC#18588&18586 should have 30s respawn timer

### ISSUE THREAD

**Issue by Tenoutoften** [Atlantiss/NetherwingBugtracker#3337]
**Description**: 
[[NPC]Floon#18588](https://www.wowhead.com/npc=18588/floon) & [[NPC]Coosh'coosh#18586](https://www.wowhead.com/npc=18586/cooshcoosh#drops) killed in [[Quest]Carckin' some skulls#10009](https://www.wowhead.com/quest=10009/crackin-some-skulls) should have just 30 second respawn timer:
![7e90098c421ee876a827946ef322db9a](https://user-images.githubusercontent.com/34839199/49695407-e4628f80-fb9a-11e8-840a-dc6e860033e6.png)

**Current behaviour**:
Currently have a much longer respawn timer.

**Expected behaviour**: 
30 Seconds respawn timer.

**Server Revision**: 
2407

**Comment by aresbrutus** [comment]
Due to an expected huge population, the respawn time has been adjusted to that.
