### ISSUE TITLE
[Misc][NPC]Mother Kashur#18687 facing the wrong way

### ISSUE THREAD

**Issue by Tenoutoften** [Atlantiss/NetherwingBugtracker#3338]
**Description**: 
It would seem that [[NPC]Mother Kashur#18687](https://www.wowhead.com/npc=18687/mother-kashur#screenshots) should be facing the bonfire, can be seen [here](https://youtu.be/55ugZSqPs7w?t=277) & on [wowhead screenshots](https://www.wowhead.com/npc=18687/mother-kashur#screenshots) from 2007

**Current behaviour**:
Faces the road.

**Expected behaviour**: 
Should face the bonfire.

**Server Revision**: 
2407

**Comment by aresbrutus** [comment]
Fixed in rev `Nariman`
