### ISSUE TITLE
[NPC]Agitated Orc Spirit#18043 doesn't agro by proximity

### ISSUE THREAD

**Issue by Tenoutoften** [Atlantiss/NetherwingBugtracker#3339]
**Description**: 
* [[NPC]Agitated Orc Spirit#18043](https://www.wowhead.com/npc=18043/agitated-orc-spirit#comments) don't have any agro radius despite them being hostile mobs, described as agitated, seen aggroed by proximity [here](https://youtu.be/_qQRm3iSQxw?t=12)

* They probably wouldn't have been "Good for farming" if they didn't automatically agro by proximity.
![d1399f67366afc83b0500e564e71b55d](https://user-images.githubusercontent.com/34839199/49695945-981b4d80-fba2-11e8-84af-3121c69d0703.png)

* If you attack one and drag it over another it will pull however

**Current behaviour**:
No agro radius, can be seen [here](https://youtu.be/l_7Jb3XrMSQ)

**Expected behaviour**: 
Should be aggressive

**Server Revision**: 
2407

**Comment by yesthisisnick** [comment]
Still an issue.  Additionally, these mobs can't be opened with a stun (pounce at least on my druid).  If I do try to open with pounce nothing seems to happen and it breaks my auto attacks.

As an aside, their patrol is sending them through/on top of their surroundings, can be seen below.

Revision: 2771
![wowscrnshot_020719_174728](https://user-images.githubusercontent.com/46409107/52450507-eac0a980-2b00-11e9-99cd-e0aab81f130b.jpg)

**Comment by Manaci** [comment]
Fixed
