### ISSUE TITLE
[Spell][Shadowpine Hexxer][Hex]

### ISSUE THREAD

**Issue by Thugli** [Atlantiss/NetherwingBugtracker#334]
[//]: # (Enclose links to things related to the bug using http://wowhead.com or any other TBC database.)
[//]: # (You can use screenshot ingame to visual the issue.)
[//]: # (Write your tickets according to the format:)
[//]: # ([Quest][Azuremyst Isle] Red Snapper - Very Tasty!)
[//]: # ([NPC] Magistrix Erona)
[//]: # ([Spell][Mage] Fireball)
[//]: # ([Npc][Drop] Ghostclaw Lynx)
[//]: # ([Web] Armory doesnt work)

**Description**: 
Significant delay with the npc's hex. It may have been some form of server lag though or something on my end.
**Current behaviour**:
When this npc casted hex on me, hex was significantly delayed and I was unable to cast any abilities for several seconds before I got hexed.
A video of the bugged behaviour can be seen here:
https://clips.twitch.tv/BelovedArborealShrimpGivePLZ
**Expected behaviour**: 
The hex should go off right away without delay.
**Server Revision**:

**Comment by The14me** [comment]
Work perfect now.
Rev:2083

**Comment by Easyfraggy** [comment]
Reopen if it isn't fixed.
