### ISSUE TITLE
[Quest][Quest Item] Raising Spirits

### ISSUE THREAD

**Issue by naekobest** [Atlantiss/NetherwingBugtracker#3340]
**Description**: 
[Quest objective](https://classicdb.ch/?quest=672) is to gather 10x [Highland Raptor Eyes](https://classicdb.ch/?item=4512)
Drop % is wayyyyy to low

**Current behaviour**:
Dropchance is around 30% 
[Proof 1](https://i.gyazo.com/dcc684741101f4a6446d4320ae509999.png)
[Proof 2](https://i.gyazo.com/a863253efae90412c1e29b24a3bd5799.png)

**Expected behaviour**: 
Dropchance is exactly 80%
[Vanilla Database](https://classicdb.ch/?npc=2559)
[TBC Database](https://tbc-twinhead.twinstar.cz/?npc=2559)

**Server Revision**: 
2407

**Comment by wtRCH** [comment]
Databases of other private server aren't good proof of item chance drop. Please rather use thottbot archive.

**Comment by wtRCH** [comment]
I will reopen the issue if there will be proof from reliable source.
