### ISSUE TITLE
[RP Event][NPC]Ancient Orc Ancestor#18688 don't move towards Oshu'Gun

### ISSUE THREAD

**Issue by Tenoutoften** [Atlantiss/NetherwingBugtracker#3341]
**Description**: 
The [[NPC]Ancient Orc Ancestor#18688](https://www.wowhead.com/npc=18688/ancient-orc-ancestor) event in Nagrand seems to lacking somewhat: They are currently doing their texts but standing still. Should be moving towards Oshu'gun. I also don't see any of them in groups. I'd imagine this has been reported on your other trackers so might not be necessary to add much.

https://youtu.be/DRjQ3PDgj1k?t=24

Entrance
---
![entrance](https://user-images.githubusercontent.com/34839199/49696330-e7647c80-fba8-11e8-9855-2057c6dff9a2.png)
![entrance2](https://user-images.githubusercontent.com/34839199/49696367-5c37b680-fba9-11e8-91fa-4252c3cda1d4.png)

Moving in group:
----
![b13de9d30601bf8f786af3c4e6ea30a7](https://user-images.githubusercontent.com/34839199/49696298-8472e580-fba8-11e8-9216-c1c43084ffe4.png)
![group](https://user-images.githubusercontent.com/34839199/49696343-137ffd80-fba9-11e8-8223-4c252624d129.png)
![275038-ancient-orc-ancestor](https://user-images.githubusercontent.com/34839199/49696300-85a41280-fba8-11e8-8ceb-2cad3311341a.jpg)

'Pictures of singular orcs walking:
---
![287427-what-the-soul-sees](https://user-images.githubusercontent.com/34839199/49696335-fba87980-fba8-11e8-8585-35a72b60ac5c.jpg)
![287428-what-the-soul-sees](https://user-images.githubusercontent.com/34839199/49696336-fba87980-fba8-11e8-8e1d-d7072c51ca6f.jpg)
![80583-ancient-orc-ancestor](https://user-images.githubusercontent.com/34839199/49696337-fc411000-fba8-11e8-9eed-b18ca4230cc0.jpg)

**Current behaviour**:
Standing still doing their texts

**Expected behaviour**: 

**Server Revision**: 
2407

**Comment by Evolvee** [comment]
fixed in last rev
