### ISSUE TITLE
[Core Mechanic]NPCs should get DR when using several stuns in fast succession vs players

### ISSUE THREAD

**Issue by Tenoutoften** [Atlantiss/NetherwingBugtracker#3344]
**Description**: 

Based on evidence provided in https://github.com/Atlantiss/NetherwingBugtracker/issues/3151
I think it is likely that regular mobs with stuns(And potentially other CC-effects) should be affected by Diminishing Returns when used against players:

> Video evidence from relevants patch displaying Diminishing Returns:
> ----
> > https://www.youtube.com/watch?v=gIl-5Z7rYFY&feature=youtu.be&t=189 - 
> Published on May 8, 2008 / Potentially [Patch 2.4.1](http://wowwiki.wikia.com/wiki/Patch_2.4.1)
> 
> [[NPC]Shattered Hand Champion#17671](https://www.wowhead.com/npc=17671/shattered-hand-champion)
> * 1st [[Spell]Concussion Blow#32588](https://www.wowhead.com/spell=32588/concussion-blow) received [here](https://youtu.be/gIl-5Z7rYFY?t=197) lasts 5 seconds(03:18 - 03:23)
> * 2nd[[Spell]Concussion Blow#32588](https://www.wowhead.com/spell=32588/concussion-blow) received [here](https://youtu.be/gIl-5Z7rYFY?t=207) lasts 2.5 seconds(03:27 - 03:29) 
> 
> 
> >https://youtu.be/3Kb1yntN9GA?t=2 
> Published on Jul 25, 2010¨
> 
> [[NPC]Shattered Hand Champion#17671](https://www.wowhead.com/npc=17671/shattered-hand-champion)
> * 1st [[Spell]Concussion Blow#32588](https://www.wowhead.com/spell=32588/concussion-blow) received [here](https://youtu.be/3Kb1yntN9GA?t=2) lasts 5 seconds(00:02 - 00:07)
> * 2nd [[Spell]Concussion Blow#32588](https://www.wowhead.com/spell=32588/concussion-blow) received [here](https://youtu.be/3Kb1yntN9GA?t=14) - lasts 2.5 seconds(00:14 - 00:16)
> 
> * 1st [[Spell]Cheap Shot](https://db.excalibur.ws/?search=cheap+shot) from [[NPC]Shattered Hand Assassin#17695](https://www.wowhead.com/npc=17695/shattered-hand-assassin) received [here](https://youtu.be/3Kb1yntN9GA?t=236) lasts 4 seconds(03:57 - 04:01)
> * 2nd [[Spell]Concussion Blow#32588](https://www.wowhead.com/spell=32588/concussion-blow) received [here](https://youtu.be/3Kb1yntN9GA?t=250) lasts 2.5 seconds(04:11 - 04:13)
>  
> -----
> 
> Based on the information extracted from above videos it is evident that the mobs use the standard formula for diminsihing returns:
> http://wowwiki.wikia.com/wiki/Diminishing_returns?oldid=1663771
> **From the official [patch 1.4.0 release notes](http://wowwiki.wikia.com/wiki/Patch_1.4.0):**
> * On the second use of the same category of spell (e.g. slowing), that spell's duration is reduced by 50%.
> * On the third use, the duration is reduced by 75%.
> * On the fourth attempt, the target becomes immune to the spell.
> * Spells must be used on the same target within 15 seconds of the *end* of the duration in order to be diminished. In other words, if a target hasn't had a slowing spell active on them for more than 15 seconds, the next slowing spell will have full effect.
> 
> 
> Players vs NPCs
> ---
> **Diminishing Returns in PvE**
> * Many types of crowd control also suffer from diminishing returns versus NPCs. Diminishing returns do not count per player but per creature; every creature has its own diminishing return for each group of CC and all players in your party / raid will be affected by that diminishing return.
> 
> ----
> 
> Patch notes on DRs & stuns:
> ---
> [Patch 1.4.0](http://wowwiki.wikia.com/wiki/Patch_1.4.0) - These diminishing return is regarding PvP
> [Patch 1.9.0](http://wowwiki.wikia.com/wiki/Patch_1.9.0) - These are under Class Related Changes, doesn't say specifically PvP.
> * Improved Starfire - The stun effect's duration no longer diminishes or is diminished by controlled stun abilities and spells (e.g. Cheap Shot, Hammer of Justice, Charge etc.).
> * Improved Concussive Shot - The stun effect's duration no longer diminishes or is diminished by controlled stun abilities and spells (e.g. Cheap Shot, Hammer of Justice, Charge etc.).
> * Impact - The stun effect's duration no longer diminishes or is diminished by controlled stun abilities and spells (e.g. Cheap Shot, Hammer of Justice, Charge etc.).
> * Seal of Justice - Mana cost slightly increased. The stun effect's duration no longer diminishes or is diminished by controlled stun abilities and spells (e.g. Cheap Shot, Hammer of Justice, Charge etc...).
> * Blackout - The stun effect's duration no longer diminishes or is diminished by controlled stun abilities and spells (e.g. Cheap Shot, Hammer of Justice, Charge etc...).
> * Mace Specialization - The stun effect's duration no longer diminishes or is diminished by controlled stun abilities 
> * Pyroclasm - The stun effect's duration no longer diminishes or is diminished by controlled stun abilities and spells (e.g. Cheap Shot, Hammer of Justice, Charge etc...).
> * Mace Specialization - The stun effect's duration no longer diminishes or is diminished by controlled stun abilities and spells (e.g. Cheap Shot, Hammer of Justice, Charge etc...).
> * Improved Revenge - The stun effect's duration no longer diminishes or is diminished by controlled stun abilities and spells (e.g. Cheap Shot, Hammer of Justice, Charge etc...).
> 
> ---
> 
> This potentially a global Core Mechanic rather than being specific to Shattered Halls. If it is a global issue, it would make sense that mobs should have stun CDs of 15 seconds or more.
> ---

**Current behaviour**:
Creatures using stuns vs players suffer no DR, even if multiple are used within a very short time.

**Expected behaviour**: 
Creatures using stuns within normal DR timing against players should have their stun times diminished.

**Server Revision**: 
2407

**Comment by Evolvee** [comment]
They do but I guess certain NPC spells are not treated by the DR-cathegory mechanic.

**Comment by Drayo** [comment]
- A lot of NPC abilities are affected by DR on NW. (Example mob from the OP https://i.imgur.com/sGXjarm.png)

- If any are not behaving as they should be reported.

The mechanic mentioned in this topic is implemented and this issue can be closed.
