### ISSUE TITLE
[Crash issue] [Quest] Tree's Company

### ISSUE THREAD

**Issue by Gniddikon** [Atlantiss/NetherwingBugtracker#3345]
**Description**: In Azuremyst Isle, approximately at coordinates 18, 84, it is currently possible to trigger the event more than once at a time, if two people use the "tree disguise kit" to turn into a tree, causing a server crash.

**Current behaviour**: Quest event can be started at the same time

**Expected behaviour**: Should only be able to do it once at the same time, not causing several NPCs to spawn and consequently crashing the server.

**Server Revision**: 2407

**Comment by Gniddikon** [comment]
Just now, the server also crashed with just one person doing the quest. It crashed right when the event completed.

**Comment by Kimro143** [comment]
I just want to add... if you turn into a tree right on top of flag, is no crash, all goes well... crash happend only if u are far, like 2 feets or more from it.

**Comment by Tenoutoften** [comment]
Didn't crash when I did it [video](https://www.youtube.com/watch?v=qQBFOgrQaiM&feature=youtu.be)

**Comment by Peglaa** [comment]
Someone just did it again and server didn't crash.. he was pretty far away from the flag as well

**Comment by Wolffenstein** [comment]
Fixed in rev 2479.
