### ISSUE TITLE
[Dungeon] [Tempest Keep Heroics]

### ISSUE THREAD

**Issue by Dirge123** [Atlantiss/NetherwingBugtracker#3349]
**Description**: 
You don't get locked after killing the first couple of bosses in Arcatraz Heroic and Botanica Heroic

**Current behaviour**:
https://imgur.com/a/YnwR5Fe
**Expected behaviour**: 
You are supposed to be locked after killing a boss
**Server Revision**: # Server Revision 2407

**Comment by Dirge123** [comment]
(Might just be visual)

**Comment by towneh** [comment]
https://forum.twguild.org/index.php?topic=4535.0

"You become saved to a raid instance if you participate on killing a boss inside that raid, or if you join a raid which has killed a boss and zone into the instance. You remain saved to that raid instance until it is scheduled to reset."

**Comment by Manaci** [comment]
Fixed
