### ISSUE TITLE
[NPC][Dungeon] Botanica trash NPC lacks visual of channelling spell

### ISSUE THREAD

**Issue by Dirge123** [Atlantiss/NetherwingBugtracker#3350]
[//]: # (Enclose links to things related to the bug using http://wowhead.com or any other TBC database.)
[//]: # (You can use screenshot ingame to visual the issue.)
[//]: # (Write your tickets according to the format:)
[//]: # ([Quest][Azuremyst Isle] Red Snapper - Very Tasty!)
[//]: # ([NPC] Magistrix Erona)
[//]: # ([Spell][Mage] Fireball)
[//]: # ([Npc][Drop] Ghostclaw Lynx)
[//]: # ([Web] Armory doesnt work)
[//]: # (To find server revision type `.server info` command in the game chat.)

**Description**: 
Sunseeker Channeller lacking visuals of spells
**Current behaviour**:
https://imgur.com/64kFlr6
**Expected behaviour**: 

**Server Revision**: 2407

**Comment by Tenoutoften** [comment]
https://youtu.be/qT-w30Iwl9s?t=178
