### ISSUE TITLE
 [Spell][Priest] Mass Dispel cancels friendly players' eating and drinking auras

### ISSUE THREAD

**Issue by Thugli** [Atlantiss/NetherwingBugtracker#3351]
[//]: # (Enclose links to things related to the bug using http://wowhead.com or any other TBC database.)
[//]: # (You can use screenshot ingame to visual the issue.)
[//]: # (Write your tickets according to the format:)
[//]: # ([Quest][Azuremyst Isle] Red Snapper - Very Tasty!)
[//]: # ([NPC] Magistrix Erona)
[//]: # ([Spell][Mage] Fireball)
[//]: # ([Npc][Drop] Ghostclaw Lynx)
[//]: # ([Web] Armory doesnt work)
[//]: # (To find server revision type `.server info` command in the game chat.)

**Description**: 
Mass dispel can cancel any friendly player's eating or drinking aura.
**Current behaviour**:

**Expected behaviour**: 
Mass dispell should not be able to remove positive buffs from friendly players.
**Server Revision**: 
2407

**Comment by Wolffenstein** [comment]
Fixed in rev 2415.
