### ISSUE TITLE
[Hunter][Visual Bug] Switching aspects after attacking hides the model for your mainhand and bow.

### ISSUE THREAD

**Issue by Nawoz** [Atlantiss/NetherwingBugtracker#3352]
Basically if you are attacking something then switch aspects and immediately untarget the enemy so your next attack doesn't go off then your models for mainhand and bow are invisible only showing your offhand.

**Comment by Nawoz** [comment]
Also appears to happen after eating.

**Comment by Nawoz** [comment]
Weapons appear to other players apparently.

**Comment by Zarant** [comment]
This feels like a client side issue, I'm not sure anything can be done server side to stop that from happening.
