### ISSUE TITLE
[Spell][Hunter] Reapplying Serpent Sting

### ISSUE THREAD

**Issue by hunterclassy** [Atlantiss/NetherwingBugtracker#3353]
**Description**:
Can't reapply Serpent Sting while Serpent Sting is still on Target.

**Current behaviour**:
Get error message "A more powerful spell is already active"

My video here: https://youtu.be/OmVDAJaQaQ4

**Expected behaviour**:
Should reapply Serpent Sting while Serpent Sting is still on Target.

**Comment by Tenoutoften** [comment]
Looks like this has already been reported: https://github.com/Atlantiss/NetherwingBugtracker/issues/3191

**Comment by wtRCH** [comment]
Duplicate of #3191
