### ISSUE TITLE
[Spell][Hunter] Feign Death Resist too often

### ISSUE THREAD

**Issue by hunterclassy** [Atlantiss/NetherwingBugtracker#3354]
**Description**:
I downloaded Netherwing beta client and deleted Cache folder before tests.

(Proof: Retail Hunters running through Heroic with Elite Mobs lvl 70-71 no resist) 
https://www.youtube.com/watch?v=i2jTGb0B5_E
https://www.youtube.com/watch?v=AMhMcysXNjw

**Current behaviour**:
Feign Death gets way too often resisted even by low level gray Mob/Mobs like lvl 50+ and much much more resisted by green Level 61-67, yellow 68-69 Mob/Mobs.

My video here: https://youtu.be/2gHLOxtUf1U

**Expected behaviour**:
Should not get resisted that often, only once in a while. The chance of resist is only higher if the Mob level is higher than your current level.

**Comment by hunterclassy** [comment]
wtRCH 

Why did you label it as low-prio-issues? Class mechanics and bugs should be high priority since you need Class spells through leveling and further all the time. 

meanwhile you put simple visual bugs like swimming with mount which has no affect on swim speed on high priority? #1186

**Comment by hunterclassy** [comment]
Wasn't counting every time I used, felt like 5-6 out of 9-10 mobs resisted from lvl 61-69. Felt pretty high tho. Sorry don't have blizzard resist chance % table, I'm just a Hunter player of years of long-time retail experience from mid-end of vanilla through whole tbc and wotlk content

**Comment by hunterclassy** [comment]
> 
> 
> wtRCH added this to To do in low-prio-issues via **automation** 12 hours ago
> It will likely be moved up. I think resistance chance also has something to do with your proximity to the mobs(Higher chance for resist if you are closer)

not really, i remember well running through dungeons low level dungeons to heroic 70's and having several mobs on my back then feign death and was saved on retail back then, as i said even lvl 50+ resist more than it should, felt too high. Thanks for you comment tho

**Comment by Firroth** [comment]
![screenshot_3](https://user-images.githubusercontent.com/43505196/49758770-1b7e9100-fcc0-11e8-853d-09bedd210f16.png)
![screenshot_4](https://user-images.githubusercontent.com/43505196/49758771-1b7e9100-fcc0-11e8-94fa-3a053648b5a5.png)

I went and tested it in terokkar forest on lvl 63-64 mobs, pulled them in packs of 3-4 each time (on 20 attempts, 0 resists).

Next I went to Shadowmoon Valley on mobs lvl 67-69 (here also 20 attempts, but here results were worse. On 20 attempts 4 resists.

Tested it on 128 hit rating.

**Comment by Wolffenstein** [comment]
Hit rating is irrelevant, I made the resist chance based only upon the table values you linked.

**Comment by Firroth** [comment]
Yep, I guessed so it's irrevelant, since talents have 4% to nully 4% from the table on targets of the same lvl. Just mentioned it, since wasn't 100% sure it isn't related.

**Comment by Drayo** [comment]
Why the fuck would there be a difference? Also, they just stated hit rating is irrelevant, so gear makes no difference either.

> Nonethenless should not resist that often

Who says that?



Anyway I googled a bit and I did find a post from 2009 (WotLK) that says hit affects FD, sadly that does not mean it's that way in TBC. Or that the poster actually had a clue for that matter, since hit cap against lvl 70 would be 6% and not 4% if I remember correctly.

But if any future hunter wants to go ahead and find some evidence that Hit should actually affect FD, you might have chance.

https://wowwhimsy.wordpress.com/2009/06/01/hunter-bag-of-tricks-no-3-feign-death/

> Feign death cannot be resisted by players, but it can be resisted by mobs.  A mob of your own level has a 4% chance of resisting your feign death.  A mob 3 levels higher has a 17% chance of resisting, and a mob 6 level higher has a 50% chance of resisting.  This chance to resist can be reduced by hit rating.  If you are hit capped against a mob, it should not resist your feign death.   Just another reason to make sure you are hit capped when you go raiding.

**Comment by hunterclassy** [comment]
i meant it makes a difference on this beta, not on original. I noticed if here if you run directly into mob and feign death the chance of resist is lower but if you hit them a few times or they hit you the resist is higher.

**Comment by Wolffenstein** [comment]
The resist chance does not depend on you hitting the mob in any way. It's constant based on what I wrote earlier.

**Comment by hunterclassy** [comment]
> 
> 
> The resist chance does not depend on you hitting the mob in any way. It's constant based on what I wrote earlier.

been running now through vanilla low level dungeons and even there feign death gets resisted up too many times, went also in normal slave pens and underbog, same thing. Definitely not working correctly. Also watch my other bug issue report on feign death about combat bug not resetting and pet combat bug, which have been marked as duplicate by one of your mods.

**Comment by Zarant** [comment]
Providing a source from 2006: 
http://web.archive.org/web/20061230092631/http://www.thottbot.com:80/?sp=5384

> From experience, it appears that anything nearby gets a chance to resist, and anything far away does not.
> 
> For example, I have seen FD resisted when used out of combat - because there were a number of mobs nearby.  Conversely, I have never seen FD fail, no matter how many mobs are angry at the hunter, if all the mobs are far away (raid pulling).

**Comment by Zarant** [comment]
Extensive research have been done before about this subject here: https://github.com/lh-server/core/pull/175

To sum up, feign death follows the spell hit formula, and should take into account how close the hunter is to the target, it's not clear exactly how the range calculation is done, but there are multiple sources indicating that after a certain distance, the resist calculation should not be taken into account.

**Comment by Zarant** [comment]
Another important thing, when feign death resists, the death animation doesn't play out:
https://youtu.be/xcDoCP9U3mg?t=242
https://youtu.be/cbIO_3KCANY?t=433

**Comment by Wolffenstein** [comment]
Fixed in rev 2437.
