### ISSUE TITLE
[Spell][Hunter] Feign Death Pet Combat Bug

### ISSUE THREAD

**Issue by hunterclassy** [Atlantiss/NetherwingBugtracker#3355]
**Description**:
Feign Death not working correctly.

**Current behaviour**:
My Pet is on passive. Only I start combat with Mob > Mob puts me AND Pet into combat half second later Pet is out of combat again and Mob attacks me and I am the only one in combat. Then I use Feign Death and go out of combat and then Mob starts to attack my noncombat Pet (the Mob used that half second combat at start to bug the combat with my Pet)

My video here: https://youtu.be/ZR3iq7VGTD8

**Expected behaviour**:
My Pet is on passive. I start combat with Mob only > Mob puts ONLY me into combat and attacks me. I use Feign Death and go out of combat > Mob must reset.

**Comment by wtRCH** [comment]
Already known issue. Duplicate.
