### ISSUE TITLE
[Spell][Hunter] Feign Death Combat Bug

### ISSUE THREAD

**Issue by hunterclassy** [Atlantiss/NetherwingBugtracker#3356]
**Description**:
Feign Death not working correctly

**Current behaviour**:
Me and Pet are in combat. Mob attacks my Pet. While both me and Pet are in combat > I use Feign Death and go out of combat and do nothing. Pet dies and mob starts running towards me and attacking me while I was out of combat and puts me into combat again.

My video here: https://youtu.be/67Gc3DCaqqw

**Expected behaviour**:
Me and Pet are in combat. Mob attacks my Pet. While both me and Pet are in combat > I use Feign Death and go out of combat and do nothing. Pet dies and mob must reset.

**Comment by wtRCH** [comment]
Duplicate. Already known issue.
