### ISSUE TITLE
[Talent][Hunter] Improved Revive Pet Talent 40% Mana reduction

### ISSUE THREAD

**Issue by hunterclassy** [Atlantiss/NetherwingBugtracker#3357]
**Description**:
Improved Revive Pet 2/2 should reduce Mana Cost of Revive Pet by 40%.

**Current behaviour**:
Does not reduce mana cost by 40%, only shows the reduced number on Spell icon tooltip.

My video here: https://youtu.be/afIDTHN-xYg

**Expected behaviour**:
Should reduce mana cost by 40%.

**Comment by towneh** [comment]
Please check the current several version with '.server info" command and compare with wolf's statement here: https://github.com/Atlantiss/NetherwingBugtracker/issues/3314#issuecomment-445476274

**Comment by Wolffenstein** [comment]
It will be fixed in rev 2409.
