### ISSUE TITLE
[Item][Engineering] Deathray Does not Work

### ISSUE THREAD

**Issue by PiaCarrot** [Atlantiss/NetherwingBugtracker#3359]
[//]: # (Enclose links to things related to the bug using http://wowhead.com or any other TBC database.)
[//]: # (You can use screenshot ingame to visual the issue.)
[//]: # (Write your tickets according to the format:)
[//]: # ([Quest][Azuremyst Isle] Red Snapper - Very Tasty!)
[//]: # ([NPC] Magistrix Erona)
[//]: # ([Spell][Mage] Fireball)
[//]: # ([Npc][Drop] Ghostclaw Lynx)
[//]: # ([Web] Armory doesnt work)
[//]: # (To find server revision type `.server info` command in the game chat.)

**Description**: Gnomish Death Ray does not work. I can not use it on enemy faction or mobs of any level.

**Current behaviour**: Using it in range simply says, Invalid Target.

**Expected behaviour**: It should work on any mob or target of the enemy faction. It can also crit still in earlier patches, cannot say for later ones, this is based off wowhead comments and screenshots.

**Server Revision**: 2407

**Comment by Wolffenstein** [comment]
Fixed in rev 2532.
