### ISSUE TITLE
[Quest][Darkshore] A Lost Master/Quest item "Enchanted Moonstalker Cloak"

### ISSUE THREAD

**Issue by mbzz88** [Atlantiss/NetherwingBugtracker#336]
https://www.wowhead.com/quest=993/a-lost-master https://www.wowhead.com/item=5387/enchanted-moonstalker-cloak
Not entirely sure if this is a bug or not, but when using this item, it turns the player invisible as normal, however pets are not.
If your pet gets aggro from mobs and dies, those mobs (now invisble to the player) will aggro onto the player and attack you out of invisibility.
I don't remember if the invisibility is meant to be applied to your pet, or it's auto dismissed, or perhaps nothing at all, it's been a long time since I've done this quest.
The rest of the quest works correctly.

**Comment by aresbrutus** [comment]
The invis only should apply on the caster(you), so the pet should indeed be dismissed by the hunter manually.
