### ISSUE TITLE
[Item]Weapons do not apply flat spell damage to hits

### ISSUE THREAD

**Issue by torrenzGH** [Atlantiss/NetherwingBugtracker#3360]
[//]: # (Enclose links to things related to the bug using http://wowhead.com or any other TBC database.)
[//]: # (You can use screenshot ingame to visual the issue.)
[//]: # (Write your tickets according to the format:)
[//]: # ([Quest][Azuremyst Isle] Red Snapper - Very Tasty!)
[//]: # ([NPC] Magistrix Erona)
[//]: # ([Spell][Mage] Fireball)
[//]: # ([Npc][Drop] Ghostclaw Lynx)
[//]: # ([Web] Armory doesnt work)
[//]: # (To find server revision type `.server info` command in the game chat.)

**Description**: 
Weapons with flat spell damage added to their attacks are incorrectly dealing only their physical damage. 
Likely affects all weapons of this type. Tested on:
7682/torturing-poker **(see reproduction video)**
3194/black-malice
1482/shadowfang
1318/night-reaver
7730/cobalt-crusher

**Current behaviour**:
No spell damage is dealt.

**Expected behaviour**: 
Affected weapons should deal composite physical+spell damage, and spell damage should be dealt through a paladin's blessing of protection, causing spellcast delay and removing the regen powerup from battlegrounds.

**Source: https://www.wowhead.com/item=1482/shadowfang#comments:id=227292**
![source1](https://user-images.githubusercontent.com/45742182/49744137-74d4c900-fc9c-11e8-8a0a-94856ed2d53a.jpg)
**Partial reproduction on beta: https://youtu.be/uD0Q9JKoB9k**
Torturing poker dealing no fire damage, with and without BoP.

See also:
https://classic.wowhead.com/spell=1022/blessing-of-protection
https://classic.wowhead.com/item=7682/torturing-poker#comments

**Server Revision**: 
2407

**Comment by Wolffenstein** [comment]
Fixed in rev 2414.
