### ISSUE TITLE
Dragonmaw + Blackout Truncheon procs

### ISSUE THREAD

**Issue by Neophrone** [Atlantiss/NetherwingBugtracker#3361]
[//]: # (Enclose links to things related to the bug using http://wowhead.com or any other TBC database.)
[//]: # (You can use screenshot ingame to visual the issue.)
[//]: # (Write your tickets according to the format:)
[//]: # ([Quest][Azuremyst Isle] Red Snapper - Very Tasty!)
[//]: # ([NPC] Magistrix Erona)
[//]: # ([Spell][Mage] Fireball)
[//]: # ([Npc][Drop] Ghostclaw Lynx)
[//]: # ([Web] Armory doesnt work)
[//]: # (To find server revision type `.server info` command in the game chat.)

**Description**:
 Both maces have similar chance on hit procs:
http://wowwiki.wikia.com/wiki/Blackout_Truncheon (132 haste) proc buff name - Blinding Speed.
![7](https://user-images.githubusercontent.com/43533040/49757381-f3456100-fcc4-11e8-8ec9-da5d36cfc754.jpg)
http://wowwiki.wikia.com/wiki/Dragonmaw_(mace) (212 haste) proc buff name - Haste.
![8](https://user-images.githubusercontent.com/43533040/49757421-0d7f3f00-fcc5-11e8-9b88-4309a5deaaa1.jpg)
This buffs even have the same icons.

**Current behaviour**:
This buffs rewriting each other, but they shouldn't.
![9](https://user-images.githubusercontent.com/43533040/49759106-6a7cf400-fcc9-11e8-8744-c9fb561372f5.jpg)
Probably the problem is that they have the same buff icon (I remember similar bug on another private server when enh shaman's 4 pieces t6 proc didn't stack with shaman's Ashtongue trinket proc - both procs had the same icon).
**Expected behaviour**: 
They should stack:
https://www.wowhead.com/item=27901/blackout-truncheon&bonus=4091#comments
"The haste effects do stack as i use both this as an off hand and the drakefist hammer as a main hand."
**Server Revision**: 2407.

**Comment by Neophrone** [comment]
Due to upcoming fresh server this bug become relevant again.
Up!

**Comment by Wolffenstein** [comment]
Fixed in rev 3391.
