### ISSUE TITLE
Dragonmaw pre-2.1 state.

### ISSUE THREAD

**Issue by Neophrone** [Atlantiss/NetherwingBugtracker#3362]
[//]: # (Enclose links to things related to the bug using http://wowhead.com or any other TBC database.)
[//]: # (You can use screenshot ingame to visual the issue.)
[//]: # (Write your tickets according to the format:)
[//]: # ([Quest][Azuremyst Isle] Red Snapper - Very Tasty!)
[//]: # ([NPC] Magistrix Erona)
[//]: # ([Spell][Mage] Fireball)
[//]: # ([Npc][Drop] Ghostclaw Lynx)
[//]: # ([Web] Armory doesnt work)
[//]: # (To find server revision type `.server info` command in the game chat.)

**Description**: 
Just found wayback machine wowhead archive before 2.1 patch released.
https://web.archive.org/web/20070223012617/http://www.wowhead.com:80/?item=28438
**Current behaviour**:
Haste proc should be 200, not 212. Also notice the materials u need to craft it (Drakefist Hammer x1, Primal Might x2, Primal Nether x12(!!!))
**Expected behaviour**: 
Haste proc should be 200, u need 12 Primal Nether to craft instead 8 (that changed after 2.1 patch).
**Server Revision**: 2407.

**Comment by Tenoutoften** [comment]
Materials required can be changed, but the haste proc is a spell and would require a hack fix or client fix

[[Spell]Copy of Haste#40267](https://db.excalibur.ws/?spell=40267) has 200 haste for 10 seconds but I don't know if it is used by anything else...
