### ISSUE TITLE
[NPC] [Double Spawn] Enraged Air Spirit

### ISSUE THREAD

**Issue by Drayo** [Atlantiss/NetherwingBugtracker#3365]
[//]: # (Enclose links to things related to the bug using http://wowhead.com or any other TBC database.)
[//]: # (You can use screenshot ingame to visual the issue.)
[//]: # (Write your tickets according to the format:)
[//]: # ([Quest][Azuremyst Isle] Red Snapper - Very Tasty!)
[//]: # ([NPC] Magistrix Erona)
[//]: # ([Spell][Mage] Fireball)
[//]: # ([Npc][Drop] Ghostclaw Lynx)
[//]: # ([Web] Armory doesnt work)
[//]: # (To find server revision type `.server info` command in the game chat.)

**Description**: 

There are two Spirits on top of each other.

**Current behaviour**:

Either there is one too many spawned or they need proper positions.

https://i.imgur.com/IfVxqRY.jpg

**Expected behaviour**: 

Should not be bunched up.

Entry 21060 
ID: 25 & 26
GUIDLow: 43475 & 43476

**Server Revision**: 2407

**Comment by Tenoutoften** [comment]
It's possible that one is lacking a patrol route

**Comment by Evolvee** [comment]
![image](https://user-images.githubusercontent.com/1942409/58897791-733f0780-86f9-11e9-8ab5-1a2ce4fcfc5a.png)

this is from sniffs

there ARE supposed to be 2 elementals on "top of each other". its blizzlike

**Comment by Evolvee** [comment]
the only problem is they are supposed to be random moving around, that is fixed in rev 2986

**Comment by Drayo** [comment]
Okay, I hope this works and is not too over-complicated. I'm not sure if there are more Spawn Points than mobs spawned on NW and they get randomized like herbs, but I have never seen them in any other spots so I assume it is not so.

I made some quick comparisons between Retail and NW (from PTR). Tn retail they are more spread out and have the random movement you mentioned, also at least two of them patrol.

Hidden Ledge Spot Retail: https://www.twitch.tv/videos/434447584
Retail has 7 spawns on this ledge.
Hidden Ledge Spot NW: https://www.twitch.tv/videos/434447885
NW has 3 spawns on this ledge.

Main Area Retail: https://www.twitch.tv/videos/434450808
Retail has 26 Spawns all over the Main Area.
Main Area NW: https://www.twitch.tv/videos/434451972
NW has 20 Spawns all over the Main Area.

Overall there seem to be 10 Mobs missing on NW, and the Spawn Points seem to be more spread out on Retail, especially the ones on the road are missing.

If you want/need anything else, my subscription runs out in about one week. ;P

**Comment by Drayo** [comment]
I will re-make this issue with a correct title and without clutter.
My recordings are old and don't work anymore, I need to remake these too.
