### ISSUE TITLE
Weaponsmith pre-2.1 state.

### ISSUE THREAD

**Issue by Neophrone** [Atlantiss/NetherwingBugtracker#3366]
[//]: # (Enclose links to things related to the bug using http://wowhead.com or any other TBC database.)
[//]: # (You can use screenshot ingame to visual the issue.)
[//]: # (Write your tickets according to the format:)
[//]: # ([Quest][Azuremyst Isle] Red Snapper - Very Tasty!)
[//]: # ([NPC] Magistrix Erona)
[//]: # ([Spell][Mage] Fireball)
[//]: # ([Npc][Drop] Ghostclaw Lynx)
[//]: # ([Web] Armory doesnt work)
[//]: # (To find server revision type `.server info` command in the game chat.)

**Description**: 
I really don't want to open 18 issues to each weapon u can craft with weaponsmith, so I decide to open one issue for all of them, since they all have the same pre-2.1 problems.
**Current behaviour**:

1)
As I posted here: https://github.com/Atlantiss/NetherwingBugtracker/issues/3363 https://github.com/Atlantiss/NetherwingBugtracker/issues/3362
every second form and third form of all weaponsmith weapons:
1h maces:
- [ ] [Dragonmaw]
- [ ] [Dragonstrike]

2h maces:
- [ ] [Deep Thunder]
- [ ] [Stormherald]

1h swords:
- [ ] [Blazeguard]
- [ ] [Blazefury]

2h swords:
- [ ] [Lionheart Champion]
- [ ] [Lionheart Executioner]

1h axes:
 - [ ] [Black Planar Edge] 
- [ ]  [Wicked Edge of the Planes]

2h axes:
- [ ] [Mooncleaver] 
- [ ] [Bloodmoon]

 need 12 Primal Nether instead of 8 to create second form. And need 20 Nether Vortex instead of 5 to create third form.
Another links that proves my words: 
https://web.archive.org/web/20070417015434/http://www.wowhead.com:80/?item=28435#0
https://web.archive.org/web/20070505113107/http://www.wowhead.com:80/?item=28441#z0z

2)
I've already posted about ammount of haste, that 1h maces should proc: 
- [ ] (https://github.com/Atlantiss/NetherwingBugtracker/issues/3363 https://github.com/Atlantiss/NetherwingBugtracker/issues/3362 https://github.com/Atlantiss/NetherwingBugtracker/issues/3364)
- [ ] [Deep Thunder] should has 346 - 520 Damage (113.9 DPS) instead of 348-523 (114.6 DPS).
https://web.archive.org/web/20070505113107/http://www.wowhead.com:80/?item=28441#z0z

3)
The last pre-2.1 difference - item lvl of all weaponsmith weapons:
pre-2.1: First form - ilvl 100, second form - ilvl 115, third form - ilvl 130.
after 2.1: 107 - 123 - 136.
https://web.archive.org/web/20070420060410/http://www.wowhead.com:80/?search=lionheart
Anyway it's not important.

**Server Revision**: 2407.

**Comment by wtRCH** [comment]
Please do something like this before all Weapons you want to report on: ```- [ ]``` This will make small checkbox for anyone who fix it to check and let others know that this was done already.

**Comment by Neophrone** [comment]
Edited issue text. I hope it's more comfortable to work with it now.

**Comment by Tenoutoften** [comment]
recommend adding 
https://github.com/Atlantiss/NetherwingBugtracker/issues/3364
https://github.com/Atlantiss/NetherwingBugtracker/issues/3363
https://github.com/Atlantiss/NetherwingBugtracker/issues/3362
here and close the singular ones. 

I think #3364 can just be closed and not reported here, if they do change the spell which I highly doubt they will already see it on the others

**Comment by Neophrone** [comment]
> Materials required can be changed, but the haste proc is a spell and would require a hack fix, my understanding, or client change(Client change wont happen)
> 
> [[Spell]Copy of Haste#40267](https://db.excalibur.ws/?spell=40267) has 200 haste for 10 seconds, right amount and duration, but I don't know if it is used by anything else...
> 
> These maces are currently using [[Spell]Haste#21165](https://db.excalibur.ws/?spell=21165)

12 haste difference not a big deal(but since we're aiming 2.0 itemization I thought I did have to report it), but materials is a big deal, since this craftable weapons is a best weapons u can get before 2.1 patch.
Also as we found out here: https://github.com/Atlantiss/NetherwingBugtracker/issues/3371, in 2.0.x patches Nether Vortex only usable for this weapons.
 So 20 Nether Vortex's is a right price for BiS weapons considering that noone except weaponsmithers will need them.

**Comment by feuerkind** [comment]
Can we address this before launch plaease @aresbrutus ?
Is this similar to #3247 or would just increasing the numbers work.

**Comment by aresbrutus** [comment]
Same answer as at https://github.com/ccshiro/cc-buglist/issues/2103#issuecomment-186312863
