### ISSUE TITLE
[NPC] [Raid] [Magtheridon's Lair] Burning Abyssal

### ISSUE THREAD

**Issue by Drayo** [Atlantiss/NetherwingBugtracker#3367]
[//]: # (Enclose links to things related to the bug using http://wowhead.com or any other TBC database.)
[//]: # (You can use screenshot ingame to visual the issue.)
[//]: # (Write your tickets according to the format:)
[//]: # ([Quest][Azuremyst Isle] Red Snapper - Very Tasty!)
[//]: # ([NPC] Magistrix Erona)
[//]: # ([Spell][Mage] Fireball)
[//]: # ([Npc][Drop] Ghostclaw Lynx)
[//]: # ([Web] Armory doesnt work)
[//]: # (To find server revision type `.server info` command in the game chat.)

**Description:**

Small visual issue with the summoned Infernals.

**Current behaviour**:

They simply despawn after x seconds.

**Expected behaviour**: 

These mobs should die and crumble, then the corpse should despawn after ~10 seconds.

**Source:**

Can be seen throughout this video: https://youtu.be/A5Ma8G8ZScc?t=5m11s

Specifically at 5 Minutes 15 Seconds.

**Server Revision**: 2407

**Comment by Easyfraggy** [comment]
Is this issue still present?

**Comment by Drayo** [comment]
yep

**Comment by Wolffenstein** [comment]
Fixed in rev 3407.
