### ISSUE TITLE
[Underbog][Swamplord Musel'ek] Aimed shot when someone is in melee range.

### ISSUE THREAD

**Issue by Giantulol** [Atlantiss/NetherwingBugtracker#3368]
Swamplord Musel'ek should use aimed shot only when nobody is in melee range.

Here he does it on the tank who is right in front of him. This makes him nearly unkillable with certain group setups. 

![image](https://user-images.githubusercontent.com/43524545/49766723-699e8f00-fcd6-11e8-916e-52611dfb2789.png) I know this is after the nerf, but I am almost certain its supposed to be like that before the nerf as well.

**Comment by Wolffenstein** [comment]
Fixed in rev 2420.

**Comment by Kuska101** [comment]
Looks like he still do it:
https://clips.twitch.tv/PleasantImportantBillRitzMitz

**Comment by deim69** [comment]
Still doing it, makes it impossible to complete UB normal mode as he just oneshots tank, unless you are level 70.
https://imgur.com/a/pTixAI3
10k shot on warrior tank.

**Comment by devo6969** [comment]
Seems fixed, tried to recreate it, he wouldn't Aim shot if i was in melee range.
