### ISSUE TITLE
Ravening Apparition has no auto attack animation

### ISSUE THREAD

**Issue by gunnermaniac** [Atlantiss/NetherwingBugtracker#337]
[//]: # (Enclose links to things related to the bug using http://wowhead.com or any other TBC database.)
[//]: # (You can use screenshot ingame to visual the issue.)
[//]: # (Write your tickets according to the format:)
[//]: # ([Quest][Azuremyst Isle] Red Snapper - Very Tasty!)
[//]: # ([NPC] Magistrix Erona)
[//]: # ([Spell][Mage] Fireball)
[//]: # ([Npc][Drop] Ghostclaw Lynx)
[//]: # ([Web] Armory doesnt work)

**Description**: Ravening Apparition has no auto attack animation. The Vengeful Apparitions in the same area have the expected animation.

**Current behaviour**: Ravening Apparition has no auto attack animation. 

**Expected behaviour**:  Ravening Apparition has the same attack animation as other mobs of this type.

**Server Revision**:

**Comment by The14me** [comment]
Confirm.Happen only in water.On the land have the animation

**Comment by devo6969** [comment]
Still happening on the PTR

**Comment by Godmatik** [comment]
Animations are client-side
