### ISSUE TITLE
Primal Nether pre-2.1 difference.

### ISSUE THREAD

**Issue by Neophrone** [Atlantiss/NetherwingBugtracker#3370]
[//]: # (Enclose links to things related to the bug using http://wowhead.com or any other TBC database.)
[//]: # (You can use screenshot ingame to visual the issue.)
[//]: # (Write your tickets according to the format:)
[//]: # ([Quest][Azuremyst Isle] Red Snapper - Very Tasty!)
[//]: # ([NPC] Magistrix Erona)
[//]: # ([Spell][Mage] Fireball)
[//]: # ([Npc][Drop] Ghostclaw Lynx)
[//]: # ([Web] Armory doesnt work)
[//]: # (To find server revision type `.server info` command in the game chat.)

**Description**: 

1)

Full list of profession's recipes where u need Primal Nether.
https://web.archive.org/web/20070416072140/http://www.wowhead.com:80/?item=23572#z0z
Most recipes have a difference between pre-2.1 and post-2.1 versions.
Some of them harder to craft before 2.1 (like weaponsmith weapons where u need 12 Primal Nether instead of 8).
 Some of them easier to craft like [Hand of Eternity] - healing mace.
Pre-2.1 mats: 4x [Hardened Adamantite Bar] 10x [Eternium Bar] 8x [Primal Might] 2x [Primal Nether]
https://web.archive.org/web/20070408110444/http://www.wowhead.com:80/?item=23556#00z
Post-2.1 mats:
![1](https://user-images.githubusercontent.com/43533040/49769585-6e207300-fce9-11e8-95b2-c593bfe16f10.jpg)

2)

I found information, that pre-2.1 Primal Nether had a chance (about 5%) to drop from last bosses of normal (non-heroic) dungeons.
"Bosses known to drop Primal Nethers on NON-Heroic instances (as of Patch 2.0.8) Keep in mind for Non-Heroic instances the drop rate is close to 5%"

"HELLFIRE CITADEL
- [ ] Warchief Kargath Bladefist - The Shattered Halls

TEMPEST KEEP
- [ ] Pathaleon the Calculator ---- The Mechanar
- [ ] Harbinger Skyriss ------------ The Arcatraz
- [ ] Warp Splinter ----------------- The Botanica

COILFANG RESERVOIR
- [ ] Warlord Kalithresh ------------The Steamvault

CAVERNS OF TIME
- [ ] Aeonus ----------------------- The Black Morass

AUCHINDOUN
- [ ] Murmur ------------------------- Shadow Labyrinth
- [ ] Talon King Ikiss --------------- Sethekk Halls"

Proves:
https://web.archive.org/web/20070408192042/http://www.wowhead.com:80/?item=23572#M0z (comments).
https://web.archive.org/web/20070407203614/http://www.wowhead.com:80/?npc=19220#00Rzc (Primal Nether in drop list of Mechanar last boss on a normal mode).

**Server Revision**: 2407.

**Comment by Tenoutoften** [comment]
> I found information, that pre-2.1 Primal Nether had a chance (about 5%) to drop from last bosses of normal (non-heroic) dungeons.
> "Bosses known to drop Primal Nethers on NON-Heroic instances (as of Patch 2.0.8) Keep in mind for Non-Heroic instances the drop rate is close to 5%"
Is this bugged?

**Comment by Neophrone** [comment]
> > I found information, that pre-2.1 Primal Nether had a chance (about 5%) to drop from last bosses of normal (non-heroic) dungeons.
> > "Bosses known to drop Primal Nethers on NON-Heroic instances (as of Patch 2.0.8) Keep in mind for Non-Heroic instances the drop rate is close to 5%"
> 
> Is this bugged?

I think it's not. Drop was removed after 2.1. At least comments don't say anything about a bug.

**Comment by Manaci** [comment]
Irrelevant now
