### ISSUE TITLE
Nether Vortex pre-2.1 difference.

### ISSUE THREAD

**Issue by Neophrone** [Atlantiss/NetherwingBugtracker#3371]
[//]: # (Enclose links to things related to the bug using http://wowhead.com or any other TBC database.)
[//]: # (You can use screenshot ingame to visual the issue.)
[//]: # (Write your tickets according to the format:)
[//]: # ([Quest][Azuremyst Isle] Red Snapper - Very Tasty!)
[//]: # ([NPC] Magistrix Erona)
[//]: # ([Spell][Mage] Fireball)
[//]: # ([Npc][Drop] Ghostclaw Lynx)
[//]: # ([Web] Armory doesnt work)
[//]: # (To find server revision type `.server info` command in the game chat.)

**Description**: 
Since I reported issue about third forms of BS craftable weapons, that require 20x Nether Vortex there is a full list of pre-2.1 recipes where u need Nether Vortex.
https://web.archive.org/web/20070418104209/http://www.wowhead.com:80/?item=30183#1
Tailoring/Leatherworking t5 crafting belts need 5(instead of 2) Nether Vortex to craft, but less ammount of the other mats.

**Server Revision**: 2407.

**Comment by Zarant** [comment]
I'm pretty sure the recipes are only supposed to drop post patch 2.1, probably the spells were in the game client before that.

You can keep making thottbot searches for all these items, you will find out that there are no records of those recipes dropping before patch 2.1:
http://web.archive.org/web/20070610175250/http://www.thottbot.com:80/i30280
http://web.archive.org/web/20070527100548/http://www.thottbot.com:80/i30281
http://web.archive.org/web/20070705055115/http://www.thottbot.com:80/i30322

Even if you take any singular item, there are no entries or comments predating may 15, 2007 (patch 2.1).

For instance the first entry into the database dates back to may 31st:
http://web.archive.org/web/20070531093818/http://www.thottbot.com:80/i30040

**Comment by Neophrone** [comment]
Probably u right, but still BS's weapons need 20 of Vortexes to craft.

**Comment by Tenoutoften** [comment]
Should close based upon https://github.com/Atlantiss/NetherwingBugtracker/issues/3366#issuecomment-450550188  referensing https://github.com/ccshiro/cc-buglist/issues/2103#issuecomment-186312863

>We're unable to change the mats requirements client-side. If we change the required mats server-side you need both the mats the client displays (so it lets you press the Enchant button) and the mats the server requires. That is too iffy an experience for us to change this.

**Comment by Manaci** [comment]
Irrelevant now
