### ISSUE TITLE
[NPC] Shimmerwing Moth

### ISSUE THREAD

**Issue by maxturtlesc2** [Atlantiss/NetherwingBugtracker#3372]
[//]: # (Enclose links to things related to the bug using http://wowhead.com or any other TBC database.)
[//]: # (You can use screenshot ingame to visual the issue.)
[//]: # (Write your tickets according to the format:)
[//]: # ([Quest][Azuremyst Isle] Red Snapper - Very Tasty!)
[//]: # ([NPC] Magistrix Erona)
[//]: # ([Spell][Mage] Fireball)
[//]: # ([Npc][Drop] Ghostclaw Lynx)
[//]: # ([Web] Armory doesnt work)
[//]: # (To find server revision type `.server info` command in the game chat.)

**Description**: 
https://youtu.be/OEucKbNYaXc?t=60
Not a TBC vid, but it should not be any different.
**Current behaviour**:
Shimmerwing Moth have an abnormal high movement speed out of combat.
**Expected behaviour**: 
Slower movement speed out of combat.
**Server Revision**:

**Comment by devo6969** [comment]
Don't see an issue, speed seems to be fine on the PTR.

PTR - https://www.youtube.com/watch?v=Gl2BUc18lBU
