### ISSUE TITLE
[Azuremyst Isle][Q]Search Stillpine Hold#9565

### ISSUE THREAD

**Issue by Tenoutoften** [Atlantiss/NetherwingBugtracker#3373]
**Description**: 
* [[Object]Blood Crystal#181748](https://www.wowhead.com/object=181748/blood-crystal) is by default protected by 2 x [[NPC]Crazed Wildkin#17189](https://www.wowhead.com/npc=17189/crazed-wildkin) bit it doesn't look like it should.

* Retail video from later expansion [here](https://youtu.be/MfXeLd1Xsyc?t=179) and [here](https://youtu.be/k2V5omyFO7Y?t=57)

* To reach this object is the objective of [[Quest]Search Stillpine Hold#9565](https://www.wowhead.com/quest=9565/search-stillpine-hold) turning the quest in will spawn 2 x [[NPC]Crazed Wildkin#17189](https://www.wowhead.com/npc=17189/crazed-wildkin) however, seems excessive that you are suppose to fight 4 x  [[NPC]Crazed Wildkin#17189](https://www.wowhead.com/npc=17189/crazed-wildkin) here.
 
**Current behaviour**:
* [[Object]Blood Crystal#181748](https://www.wowhead.com/object=181748/blood-crystal) is by default protected by ) bit it doesn't look like it should.

**Expected behaviour**: 
Expected to not be guarded

**Server Revision**: 
2407

**Comment by Wolffenstein** [comment]
Fixed in rev 2422.
