### ISSUE TITLE
[Bloodmyst Isle][Quest]Declaration of Power too#9666 doesn't share Declaration of Power Objective while in group

### ISSUE THREAD

**Issue by Tenoutoften** [Atlantiss/NetherwingBugtracker#3374]
**Description**: 
[[Quest]Declaration of Power too#9666](https://www.wowhead.com/quest=9666/declaration-of-power)
Doesn't share its "Declaration of Power" objective while in group.

Provided item: [[Item]Draenei Banner#24084](https://www.wowhead.com/item=24084/draenei-banner)
To be used on corpse of [[NPC]Lord Xiz#17701](https://www.wowhead.com/npc=17701/lord-xiz)
[[Spell]Place Draenei Banner#30988](https://www.wowhead.com/spell=30988/place-draenei-banner)
[[Object]Draenei Banner#181917](https://db.excalibur.ws/?object=181917)

You are also unable to place an additional banner on the corpse due to the same mechanic happening here https://github.com/Atlantiss/NetherwingBugtracker/issues/3317

**Current behaviour**:
Doesn't share Objective while in group, but the corpse is currently despawning slower than the banner so you can place it a second time

**Expected behaviour**: 
Expected to share objective while in group.

**Server Revision**: 
2407

**Comment by Wolffenstein** [comment]
It shouldn't be shared, but multiple players will be able to use the banner on the corpse to get their credit after rev 3469.
