### ISSUE TITLE
[Paladin] [Spell] Seal of Vengeance judgement with no stacks

### ISSUE THREAD

**Issue by Anselm123** [Atlantiss/NetherwingBugtracker#3375]
![image](https://user-images.githubusercontent.com/36844570/49792165-53beb780-fd32-11e8-8c5a-fc2e03e9669f.png)

![image](https://user-images.githubusercontent.com/36844570/49792274-9d0f0700-fd32-11e8-81c5-37344c15cba3.png)

**Description**:  Judgement of vengeance without any stacks heals

**Current behaviour**: When casting Judgement of Vengeance on a target without any stacks of Holy vengeance on the target it heals the target for 1hp

**Expected behaviour**:  Is meant to do 0 damage since you have no stacks

**Server Revision**:

**Comment by devo6969** [comment]
Still happens, can't find any information of this happening on retail. All sources talk about "5 stacks" and never zero. I think its safe to say if there is no stacks, its suppose to do "only" zero damage not heal the target for one.

**Comment by Wolffenstein** [comment]
Fixed in rev 3465.
