### ISSUE TITLE
NPC Aggro/Leash Issue

### ISSUE THREAD

**Issue by maxturtlesc2** [Atlantiss/NetherwingBugtracker#3376]
[//]: # (Enclose links to things related to the bug using http://wowhead.com or any other TBC database.)
[//]: # (You can use screenshot ingame to visual the issue.)
[//]: # (Write your tickets according to the format:)
[//]: # ([Quest][Azuremyst Isle] Red Snapper - Very Tasty!)
[//]: # ([NPC] Magistrix Erona)
[//]: # ([Spell][Mage] Fireball)
[//]: # ([Npc][Drop] Ghostclaw Lynx)
[//]: # ([Web] Armory doesnt work)
[//]: # (To find server revision type `.server info` command in the game chat.)

**Description**: 
https://imgur.com/a/RTFUNUi
I ran away from this NPC and this happened (it lasted around 20s i'd say). I'm not sure about what the exact cause is, my guess is a bug involving a combat situation, since this NPC is fighting Nether Beasts (Manaforge Duro).

**Expected behaviour**: 
Proper leash reset.
**Server Revision**:

**Comment by Wolffenstein** [comment]
Should be fixed in rev 2538.
