### ISSUE TITLE
[Bloodmyst Isle][Paladin][Quest]Redemption#9600 Doesn't give XP / Might lack RP

### ISSUE THREAD

**Issue by Tenoutoften** [Atlantiss/NetherwingBugtracker#3377]
**Description**: 
* [[Quest]Redemption#9600](https://www.wowhead.com/quest=9600/redemption) currently rewards 0 xp.
![b1029ec14da19f4ce3b04ad8f51c00d1](https://user-images.githubusercontent.com/34839199/49794628-4c9aa800-fd38-11e8-91ea-4bb0fd048916.png)

* According to [old thottbot](http://web.archive.org/web/20071121105402/http://thottbot.com:80/q9600) it should give 900 xp.

---

* Additionally I think it is slightly off that there is almost nothing happening here: You ressurect [[NPC]Young Furbolg Shaman#17542](https://www.wowhead.com/npc=17542/young-furbolg-shaman#comments) with [[Item]Symbol of Life#6866](https://www.wowhead.com/item=6866/symbol-of-life) => [[Spell]Symbol of Life#8593](https://www.wowhead.com/spell=8593/symbol-of-life).

* [[NPC]Young Furbolg Shaman#17542](https://www.wowhead.com/npc=17542/young-furbolg-shaman#comments) stands up for a few seconds, doesn't turn towards player or says anything, then he dies again. I couldn't find a video of this quest and comments don't say a whole lot, it would be natural for the NPC to turn towards the player and thank him/her then run away and despawn...

**Current behaviour**:
* 0 xp
* [[NPC]Young Furbolg Shaman#17542](https://www.wowhead.com/npc=17542/young-furbolg-shaman#comments) doesn't thank player

**Expected behaviour**: 
* 900 xp
* Maybe [[NPC]Young Furbolg Shaman#17542](https://www.wowhead.com/npc=17542/young-furbolg-shaman#comments) should thank the player.

**Server Revision**: 
2407

**Comment by pelekon** [comment]
fixed xp reward if u find any proof about this "maybe emote" then create new report and send me link on discord
