### ISSUE TITLE
[Item] lesser healing potion -Heal too low

### ISSUE THREAD

**Issue by The14me** [Atlantiss/NetherwingBugtracker#338]
**Current behaviour**: Atm heal for 77

**Expected behaviour**: 
 Suppose to be 140 to 180.
https://www.wowhead.com/item=858/lesser-healing-potion

**Server Revision**:

**Comment by illiji** [comment]
![wowscrnshot_092418_004753](https://user-images.githubusercontent.com/43508759/45938929-87443e00-bf9c-11e8-92fb-24b51c1bca63.jpg)
![wowscrnshot_092418_005022](https://user-images.githubusercontent.com/43508759/45938930-8b705b80-bf9c-11e8-9d42-3ea35b98b279.jpg)

**Comment by xmesaj2** [comment]
if you miss more health, potion still heals for the same amount or more? asking because can be just combat log not showing overheal

**Comment by SwiftieTBC** [comment]
Tested and seems to be working correctly now
