### ISSUE TITLE
[Hunter] Paperdoll Crit Chance

### ISSUE THREAD

**Issue by gwxse8w** [Atlantiss/NetherwingBugtracker#3382]
**Description**: 
The displayed crit chance in the paperdoll is wrong.

**Current behaviour**:
Create a new hunter and check peperdoll's crit chance.
A naked hunter troll has 153 agility. Wearing a white bow crit chance should be:
153/40 + 1 = 4.825
Right now the displayed value is 3.29

The same happens if you take the talent Letal Shots
153/40 + 1 + 5 = 9.825
Right now the displayed value is 8.29

In both cases 1.535% crit is missing.
Another proof about this is the mouseover tooltip on Agility.
With 153 agility (naked troll) it says "Increase Critical Hit chance by 2.29%"

**Expected behaviour**: 
Every agility point should grant 0.025% crit.
Mouseover tooltip on Agility (naked troll, 153 agility) should say:
"Increase Critical Hit chance by 3.825%"
That 1.535% crit shouldn't be missing.

**Server Revision**:

**Comment by ta55el** [comment]
Hunters start with -1,53% crit chance at 70 lvl.

**Comment by Neophrone** [comment]
Did u up u'r bow skill?

**Comment by gwxse8w** [comment]
> 
> 
> Did u up u'r bow skill?

For the sake of it, I did.
Created a new Blood Elf (insta70) and levelled up Bow Skill to 350 without using "Teach everything I should know" from the NPC. Yes, I went to an hunter trainer to learn my skills as well.

Same thing. Level70 Blood Elf has 153 agility and the tooltip still talks about 2.29% crit.

**Comment by Zarant** [comment]
It's working as intended, hunters are supposed to have -1.53% base crit.

Following source from vanilla wow:
http://wowwiki.wikia.com/wiki/Critical_strike?oldid=349108

And also you can check out the calculations from Cheeky's spreadsheet from TBC: 
https://web.archive.org/web/20080302191443/http://elitistjerks.com:80/f31/t9816-hunter_spreadsheets_--_development/
