### ISSUE TITLE
Missing sound from mobs detecting stealth

### ISSUE THREAD

**Issue by Talimar** [Atlantiss/NetherwingBugtracker#3383]
[//]: # (Enclose links to things related to the bug using http://wowhead.com or any other TBC database.)
[//]: # (You can use screenshot ingame to visual the issue.)
[//]: # (Write your tickets according to the format:)
[//]: # ([Quest][Azuremyst Isle] Red Snapper - Very Tasty!)
[//]: # ([NPC] Magistrix Erona)
[//]: # ([Spell][Mage] Fireball)
[//]: # ([Npc][Drop] Ghostclaw Lynx)
[//]: # ([Web] Armory doesnt work)
[//]: # (To find server revision type `.server info` command in the game chat.)

**Description**: 
Sounds are missing from mob behavior.

**Current behaviour**:
Mobs turn towards you,silently, if you get near in their field of view while stealthed.

**Expected behaviour**: 
Same as the above except they're supposed to grunt or make a noise. I tested with both humanoids and beast.

For the record, this is not when they break player stealth, only when they detect something nearby.

**Server Revision**: 
2407

**Comment by Wolffenstein** [comment]
Are you sure you don't have sound effects turned off?

**Comment by Tenoutoften** [comment]
Works fine https://www.youtube.com/watch?v=SI5-N7Ux0-k&feature=youtu.be
If your sound wasn't low it might have been your camera being very far away I think that could affect it

**Comment by Talimar** [comment]
I just tried again with camera zoomed in and sound at max. Still no noise.
I can record a clip tomorrow.

**Comment by Talimar** [comment]
https://www.youtube.com/watch?v=hjjdqJt-t_g

**Comment by Wolffenstein** [comment]
Not every mob has a sound for it. The client doesn't have it for the mobs you've shown for example. I just checked wolves in Elwynn and it works fine on them.
