### ISSUE TITLE
[Hunter][Pet] Pursuit speed

### ISSUE THREAD

**Issue by gwxse8w** [Atlantiss/NetherwingBugtracker#3384]
**Description**: 
Pet pursuit speed is wrong.
Currently pet in pursuit of a mob runs at at 100% move speed if the hunter didn't take Bestial Swiftness.

**Current behaviour**:
Pursuit speed (without any talent modifying it) is 100%.

**Expected behaviour**: 
Pursuit speed (without any talent modifying it) should be 115%.
Pursuit speed + Bestial Swiftness should be 149.5% (Bestial Swiftness bonus is multiplicative).

Other "spells" affecting pursuit speed (all multiplicative) are:
Aspect of the Pack
Pathfinding
Dash
Dive
Charge

Bestial Swiftness, Pack and Pathfinding Should stack together.

Dash/Dive (and Charge?) will override all the others.

**Comment by Tenoutoften** [comment]
Source?

**Comment by Godmatik** [comment]
Rev 4014 - tested and it works fine, pursuit speed is faster than 100%. Must have been fixed at some point.
