### ISSUE TITLE
[NPC] [Boss] [Spell] [Karazhan] Shade of Aran - Blizzard

### ISSUE THREAD

**Issue by Kaini27** [Atlantiss/NetherwingBugtracker#3386]
[//]: # (Enclose links to things related to the bug using http://wowhead.com or any other TBC database.)
[//]: # (You can use screenshot ingame to visual the issue.)
[//]: # (Write your tickets according to the format:)
[//]: # ([Quest][Azuremyst Isle] Red Snapper - Very Tasty!)
[//]: # ([NPC] Magistrix Erona)
[//]: # ([Spell][Mage] Fireball)
[//]: # ([Npc][Drop] Ghostclaw Lynx)
[//]: # ([Web] Armory doesnt work)
[//]: # (To find server revision type `.server info` command in the game chat.)

**Description**: There seems to be safespots from blizzard on edges of the room between bookshelfs in the corners. They do not work 100% of the times, but still happening.

**Current behaviour**: Currenlty sometimes player is able to avoid blizzard damage by standing in a corners between shelfs, it could be the result of LoS and timing on damage ticks.

**Expected behaviour**: There should be no safezone from Blizzard damage besides inner ring and opposite side from blizzard.

**Server Revision**: Currenlty **2407** (dec 11), occured 2 days ago

**Comment by Drayo** [comment]
Pretty sure this is invalid like my report about the door safespot, no one is using this anyway so it might as well just be closed.

**Comment by devo6969** [comment]
Tried to recreate this, the only thing i could find is that it doesn't refresh the "slow effect" of blizzard but continues to take damage from it regardless. No safe spot in corners.
PTR -https://www.youtube.com/watch?v=q1cS9vgLZBw
