### ISSUE TITLE
[Warlock] [Talent] Master Summoner

### ISSUE THREAD

**Issue by Valywave** [Atlantiss/NetherwingBugtracker#3388]
**Description**: I should be able to summon a fel guard for the reduced mana cost of the Master Summoner talent, but currently I can't. (see screenshot)

**Current behaviour**:

![mastersummonerbug](https://user-images.githubusercontent.com/38636491/49846062-c038c580-fdc9-11e8-88d3-ff12550b3225.png)

**Expected behaviour**: 

[http://wowwiki.wikia.com/wiki/Master_Summoner](url)

**Server Revision**: **2407**

**Comment by Wolffenstein** [comment]
It will be fixed in rev 2409.
