### ISSUE TITLE
[Warlock] [Talent] Mana Feed not working with Drain Mana Rank 1&2

### ISSUE THREAD

**Issue by Valywave** [Atlantiss/NetherwingBugtracker#3389]
**Description**: **Mana Feed** **Rank 1 and Rank 2** do not grant Mana to my pet when I use **Drain Mana**.

**Current behaviour**:

**Mana Feed** Rank 1 and Rank 2 do not grant Mana to my pet when I use **Drain Mana**. Rank 3 however does. This was mentioned in another form in #1933 ,but I noticed it is only not working on Rank 1 & 2. _Life Tap however does work with all 3 ranks._

**Expected behaviour**: 

My pet should get 33% of the mana I drain with Drain Mana on Rank 1 and 66% on Rank 2.

http://wowwiki.wikia.com/wiki/Mana_Feed

**Server Revision**: **2407**

**Comment by Wolffenstein** [comment]
From what I've seen in core (or perhaps from what I haven't seen) I'm not convinced even rank 3 works.

**Comment by Wolffenstein** [comment]
Fixed in rev 2426.
