### ISSUE TITLE
Pet dissapeared while doing quest in Thousand Needles

### ISSUE THREAD

**Issue by Buskmurvel** [Atlantiss/NetherwingBugtracker#339]
I was doing the quest "A dip in the Moonwell", in Thousand Needles, coords: 17,27.
https://tbc-twinhead.twinstar.cz/?quest=9433
https://www.youtube.com/watch?v=loAIeZbYC8s (its at 00.50) in the vid.

When i controlled the robot my pet just dissapeared. I can't use "Call pet", revive or see him at a stable master.
I can assure you he was well fed and with high happiness, since i've had him for some time now.

Seems like when i transformed into a robot the pet just wierded out.

**Comment by Easyfraggy** [comment]
When you need to report location it's best to use .gps command ingame and take a screenshot of the info you get in chat window.

Other useful commands:
.server info
.npc info

**Comment by Wolffenstein** [comment]
Fixed in rev 2075.
