### ISSUE TITLE
[Pet][Quest][Hunter]

### ISSUE THREAD

**Issue by MacaWilly** [Atlantiss/NetherwingBugtracker#3391]
During the level 10 quest for your hunter training you have to tame 3 pet's, all 3 of them showed the same issue where the tamed pet would stand next to the corpse after killing it and not auto-follow you. 

Instead you need to click follow, every time you kill a mob.

**Comment by Tenoutoften** [comment]
Related:

Hunter Pet Quest XP doesn't give xp:
https://github.com/Atlantiss/NetherwingBugtracker/issues/69

https://github.com/Atlantiss/NetherwingBugtracker/issues/375
* Combat portion of this issue is probably resolved

**Comment by pelekon** [comment]
fixed in rev 2432
