### ISSUE TITLE
[Bloodmyst Isle]Freeing NPC#17681 for Q#9670 doesn't share credit & specific spots makes NPC#17681 go through ground

### ISSUE THREAD

**Issue by Tenoutoften** [Atlantiss/NetherwingBugtracker#3393]
**Description**: 
[[Quest]They're Alive! Maybe...#9670](https://www.wowhead.com/quest=9670/theyre-alive-maybe)
* You don't get shared quest credit for freeing [[NPC]Expedition Researcher#17681](https://www.wowhead.com/npc=17681/expedition-researcher).
* [[NPC]Expedition Researcher#17681](https://www.wowhead.com/npc=17681/expedition-researcher) freed far up the mountain seem to clip through the ground when they run away. [Here](https://www.youtube.com/watch?v=0lIE_43bBFY&feature=youtu.be) is one that has already went through the ground.

* [[NPC]Expedition Researcher#17681](https://www.wowhead.com/npc=17681/expedition-researcher) is freed from [[NPC]Webbed Creature#17680](https://www.wowhead.com/npc=17680/webbed-creature) who has two abilities: [[Spell]Free Webbed Creature#31009](https://www.wowhead.com/spell=31009/free-webbed-creature) & [[Spell]Free Webbed Creature#30950](https://www.wowhead.com/spell=30950/free-webbed-creature)

* Another issue tied with this quest: https://github.com/Atlantiss/NetherwingBugtracker/issues/3285 about [[NPC]Nazzivus Summoner#17524](https://www.wowhead.com/npc=17524/nazzivus-summoner)

**Expected behaviour**: 
Expected to not go through the ground.
Shared quest credit for freeing creatures

**Server Revision**: 
2407

**Comment by temperrr** [comment]
The quest progression is still not shared and untargetable nazzivus summoner and hellcaller
