### ISSUE TITLE
[Spell][Mage] Blink working

### ISSUE THREAD

**Issue by hunterclassy** [Atlantiss/NetherwingBugtracker#3394]
*UPDATE*: Working now

**Comment by Tenoutoften** [comment]
Other [[Spell]Blink#1953](https://www.wowhead.com/spell=1953/blink) reports on terrain
https://github.com/Atlantiss/NetherwingBugtracker/issues/2158
https://github.com/Atlantiss/NetherwingBugtracker/issues/1915
https://github.com/Atlantiss/NetherwingBugtracker/issues/1930

Specific about Air to Ground:
https://github.com/Atlantiss/NetherwingBugtracker/issues/2254
https://github.com/Atlantiss/NetherwingBugtracker/issues/2626

**Comment by aresbrutus** [comment]
Requesting `.gps` coordinates of ALL the spots you are doing testing with. This so that Wolf does not run around looking for locations + to compare with your footage once he does fixes. Even if you mention it breaks in every steep spot or w/e, we still want to see `.gps` locations and footage ofcourse.

**Comment by aresbrutus** [comment]
https://github.com/Atlantiss/NetherwingBugtracker/issues/3098
https://github.com/Atlantiss/NetherwingBugtracker/issues/2626
https://github.com/Atlantiss/NetherwingBugtracker/issues/2254
https://github.com/Atlantiss/NetherwingBugtracker/issues/2158
https://github.com/Atlantiss/NetherwingBugtracker/issues/1930

**Comment by Fenvarien1** [comment]
https://gfycat.com/AthleticIllustriousGossamerwingedbutterfly
mage blinks 2 diff directions but end up at diff distance.
X: 1864.620117, -4259.601074, 37.158035 Map Kalimdor Area Ogrimmar

**Comment by The14me** [comment]
https://github.com/Atlantiss/AtlantissTBCBT/issues/4420 ''Noone'' issue's .

**Comment by Brasso** [comment]
https://imgur.com/a/zVXyELU
![image](https://user-images.githubusercontent.com/44345420/49865629-c6e52e00-fe05-11e8-9b86-81601b57cc63.png)

So blink is not working in most places, but I've found that it works pretty well outside of Ironforge for some reason.

![image](https://user-images.githubusercontent.com/44345420/49865929-8c2fc580-fe06-11e8-8105-cadb089343a6.png)
https://imgur.com/a/vuQJ3xQ

**Comment by hunterclassy** [comment]
The GPS spots of my video clip, as i said it happens almost everywhere:

Map: 1 (Kalimdor) Zone: 1637 (Orgrimmar) Area: 1637 (Orgrimmar)
X: 1662.598267, -4389.298828, 23.421450 Orientation: 4.890691
grid[35,23]cell[1,12] InstanceID: 0
 ZoneX: 50.527271 ZoneY: 65.348312
GroundZ: 23.437500 FloorZ: 23.421347 Have height data (Map: 1 VMap: 1 Col: 1)


Map: 530 (Outland) Zone: 3519 (Terokkar Forest) Area: 3519 (Terokkar Forest)
X: -2069.457031, 4819.286621, 0.481356 Orientation: 2.127409
grid[28,41]cell[1,0] InstanceID: 0
 ZoneX: 41.926785 ZoneY: 29.707140
GroundZ: 0.480162 FloorZ: 0.480162 Have height data (Map: 1 VMap: 1 Col: 1)


Map: 530 (Outland) Zone: 3483 (Hellfire Peninsula) Area: 3483 (Hellfire Peninsula)
X: -22.982639, 2796.963379, 62.853287 Orientation: 1.131502
grid[31,37]cell[15,3] InstanceID: 0
 ZoneX: 53.104378 ZoneY: 43.680077
GroundZ: 62.852558 FloorZ: 62.852558 Have height data (Map: 1 VMap: 1 Col: 1)


Map: 530 (Outland) Zone: 3523 (Netherstorm) Area: 3726 (Manaforge B'naar)
X: 3024.171631, 4254.903809, 161.450546 Orientation: 1.178624
grid[37,39]cell[10,15] InstanceID: 0
 ZoneX: 22.034605 ZoneY: 65.437080
GroundZ: 161.447968 FloorZ: 161.447968 Have height data (Map: 1 VMap: 1 Col: 1)


Map: 530 (Outland) Zone: 3522 (Blade's Edge Mountains) Area: 3776 (Bloodmaul Outpost)
X: 1538.206299, 6430.833496, -1.390225 Orientation: 1.155051
grid[34,44]cell[14,0] InstanceID: 0
 ZoneX: 44.516121 ZoneY: 79.358345
GroundZ: -1.391419 FloorZ: -1.391419 Have height data (Map: 1 VMap: 1 Col: 1)

**Comment by Brasso** [comment]
Update after rev 2430

Blinking up slopes and down slopes works much better than before. https://gfycat.com/NeedyOrganicFairybluebird
https://gfycat.com/CompassionateFreeArmyworm

Steeper slopes do not work.
https://gfycat.com/HappyUniqueArawana
Same in ironforge from the pit.

**Comment by Fenvarien1** [comment]
https://gfycat.com/AthleticIllustriousGossamerwingedbutterfly https://gfycat.com/SentimentalPortlyGalapagoshawk progress :FeelsLoveMan:
