### ISSUE TITLE
[Misc] Fear and Aggro interactions aren't Blizz-like

### ISSUE THREAD

**Issue by Helelel** [Atlantiss/NetherwingBugtracker#3396]
Description: Fear and aggro interactions aren't working as per either 2.4.3 nor 2.0.1 rulesets. 2.3 saw Fear Ward changed so as to have a 3 minute cooldown and a 3 minute uptime, instead of a 30 second cooldown with a 10 minute uptime. To compensate for this change, the way fear mechanics and aggro swapping worked was changed. Prior to 2.3, if the current aggro target of a given NPC was feared, the NPC would change targets to the next highest target on its aggro threshold. To prevent this, raids used Fear Ward or Tremor Totems. After 2.3, if the current aggro target of a given NPC was feared, the NPC would continue to chase and attack the current target, even through fear.

Current Behavior: The server is using 2.4.3 skills (including the nerfed Fear Ward with a 3 minute cooldown and 3 minute uptime), as well as pre 2.3 fear mechanics (NPCs drop aggro on their current target if it enters a fear state). This is a huge nerf to Druid and Paladin tanks, who have no way to properly deal with fear mechanics, and makes them incapable of properly tanking fights like Archimonde, Nightbane, etc., unlike retail.

Expected Behavior: If the server is going by the 2.4.3 mechanical ruleset, NPCs should not temporarily drop aggro on their current target after it is feared (Nightbane, Archimonde, etc.). If the server is going by the 2.0.1 ruleset, Fear Ward should have a 30 second cooldown and a 10 minute uptime.

Evidence: http://wowwiki.wikia.com/wiki/Patch_2.3.0

Ctrl-F to the word "fear" and you will see evidence of both claims. Here is the text directly from the patch notes:

On Fear Ward: "Fear Ward is now available to all priests at level 20. Duration reduced to 3 minutes, cooldown increased to 3 minutes."

On Fear Mechanics: "Creature AI has been changed to no longer prioritize attacking unfeared targets over feared targets."

**Comment by Tenoutoften** [comment]
[Retail video evidence 2.3](https://www.youtube.com/watch?v=ZfTV61jJyQY&feature=youtu.be&t=36)
Tank gets feared and keeps the pack on him

**Comment by Helelel** [comment]
> [Retail video evidence 2.3](https://www.youtube.com/watch?v=ZfTV61jJyQY&feature=youtu.be&t=36) - Published on Mar 20, 2008
> Tank gets feared and keeps the pack on him

Thank you very much for this video evidence, it was hard to find when I looked myself. In this video, you can see the tank being feared by the Coilfang Siren @ 0:37 and maintaining full aggro.

**Comment by Easyfraggy** [comment]
This is all intentional. PvE content is 2.0 state while spells/talents 2.4.3.

**Comment by Helelel** [comment]
> This is all intentional. PvE content is 2.0 state while spells/talents 2.4.3.

This is a hard nerf to Druid and Paladin tanks and not Blizz-like.
