### ISSUE TITLE
[spell][class] Downranking of the buffs and Greater buffs

### ISSUE THREAD

**Issue by Kaini27** [Atlantiss/NetherwingBugtracker#3397]
**Description**: Downranking issues possibly on all classes, a little complicated issue to describe.

**Current behaviour**:
 "A more powerful spell is allready active" is not occurring when player casts rank 1 buff on the target with max rank of the greater buff like Prayer of Fortitutde or Greater Blessing of Wisdom for example.

Currenly its possible to cast rank one Touch of Weakness and Inner fire even if max rank is already active.

Greater Buffs that require reagents are are disappearing when player who did buffs gets kicked or leaves by himself. This does not occur if person who gets buff leaves by himself or gets kicked.

Max rank of the greater(possibly lesser as well) buff casted on party/raid does not downranks for players who are lower levels.

**Expected behaviour**: 
Any similar spells should not be replaced with lower status effect.
Greater Buffs should not disappear under any circumstances.
Greater or lesser buff of a max rank casted on a lower level player should adjust accordingly to targets level if its possible for targets level to even have that buff.

**Requesting** investigation on downranking of Circle of Healing since that spell even though being active spell behaves as a buff and downranks to targets level accordingly. Possible due to having most HPS in game if not overhealing and having max targets healed. Cannot accomplish testing myself due to instant 70.

**Server Revision**: 2431

**Comment by killablink** [comment]
Probably similar core problem with #3279  with smaller rank debuffs replacing higher ranks too

**Comment by Godmatik** [comment]
Fixed a long time ago.
Downranked buffs no longer replace higher rank ones.
