### ISSUE TITLE
ghost walking

### ISSUE THREAD

**Issue by RishikeshRamjith** [Atlantiss/NetherwingBugtracker#34]
[//]: # (Enclose links to things related to the bug using http://wowhead.com or any other TBC database.)
[//]: # (You can use screenshot ingame to visual the issue.)
[//]: # (Write your tickets according to the format:)
[//]: # ([Quest][Azuremyst Isle] Red Snapper - Very Tasty!)
[//]: # ([NPC] Magistrix Erona)
[//]: # ([Spell][Mage] Fireball)
[//]: # ([Npc][Drop] Ghostclaw Lynx)
[//]: # ([Web] Armory doesnt work)

**Description**: 
can't walk as a ghost, character model lies on the floor, have to relog to fix
**Current behaviour**:

**Expected behaviour**: 

**Server Revision**:

**Comment by wtRCH** [comment]
Known issue, we are working on it
