### ISSUE TITLE
24 hour leveling bug compliation

### ISSUE THREAD

**Issue by myah123** [Atlantiss/NetherwingBugtracker#340]
**Description**: 
Sorry I don't have enough time to get details about each bug and list it in the template in 10+ posts, hopefully thats ok and you can look into these, just going to list a compilation I've found leveling so far and try to be as specific as possible:

~~- Hunter autoshot delayed by spells such as mend pet, first aid, and raptor strike, adds time on the autoshot timer and I don't believe it should, no evidence though but I think it should be looked at~~
~~- Pertaining to the above I notice serpent sting/arcane shot/concussive shot sometimes linked to autoattack so for example concussive shot wont fire until stop moving character and autoshot, should be able to use instant cast abilities while moving independent of autoshot~~
- Growl should have priority over other autocast spells on petbar, (growl vs gore = use growl if not on cd)
- sometimes ressing pet and feeding it right away makes it dissapear and have to relog to reset
- pet refuses to attack an freezing trapped mob when I command it to if its on passive (might be on defensive and aggressive as well, should attack if told though)
- pet refuses to attack mobs out of stealth, would order to attack on fen creepers and it would wait until they are out of stealth
- underwater pet/mob pathing near boats north of auberdine messed up
- pet/mob pathing for boats north of menethil harbor messed up 
- ~~Instadied near jitters and stalvan, tsu said he put in a ticket for unseen mobs that kill you being there when they are obviously not supposed to be~~
- bonewarders near nekrosh in menethil bone armor has infinite absorption
- drop rate for young crocolisk skin for menethil quest seemed a bit too low
- the missing diplomat question bugs out at slimpoke event in menethil (mikhael does not give/accept quests until killed and respawned after starting the chain to kill slimpoke outside inn), tsu said he reported this one
- cooking supplies woman in dolanaar was uninteractable at server launch, might have been fixed (she sells spices and flour)
- character model dissapeared twice in small spaces (once in building in darnassus north side going up to morrowgrain guy, second time in dun algaz tunnel going from wetlands to loch modan
- minor spelling mistake on forlorn spirit emote when doing stalvan quest, one at moonbrook called me $n and the one in stormwind called me $r

Overall server looks really good and not too many major bugs. I will say however the optimization seems to need work. I understand it might be because of the spell batching and it seems like a great idea but it seems to be making the gameplay very clunky for a hunter at least. It feels like everything is underwater or like you are playing with 300-500ms or something, I've been playing from US on private servers for the past two years and its always been manageable, whether its the server/host or batching there is a noticeable delay on all combat. I'm for spell batching, but not at the cost of noticeable optimization loss and fluidity of gameplay/combat, I feel like this is the biggest issue ive seen that needs to be worked on during beta.

**Comment by toto6** [comment]
please, make ONE report with ONLY ONE bug !

**Comment by toto6** [comment]
and dont forget to fill the required sections when making a report that are the following:

**Description**: 

**Current behaviour**:

**Expected behaviour**: 

**Server Revision**:

**Comment by toto6** [comment]
try to see it in the developer way, if we jump in  to fix quickly some bugs, we will never consider such report...

**Comment by myah123** [comment]
Again as stated I don't have an hour to do all that right now, I should be sleeping took 20 to make an account here and report all of it for you here, if you want to rewrite it all be my guest

**Comment by toto6** [comment]
nop, that's fine, this report will just stay like this, and probably nobody will fix it :D that's on you

**Comment by Easyfraggy** [comment]
I've put strikethrough over the two bugs that are already reported! 

Dev time is the bottleneck for release so anything we can do to help make their life easier!

Please do report them individually when you get time! Some like the character disappearing might need some more info - I cannot reproduce it in those places atleast.

GJ Testing!

**Comment by Thugli** [comment]
I would have to agree that at times, playing as a hunter can feel a little clunky. The only times it has actually had any meaningful effect on gameplay was when I was killing elites in ghostlands, and having abilities going off a little late and at varying delays(At least it seemed like varying delays) made it a little harder to kite.  I get around 130 ms here, but the responsiveness sometimes feels slower than it has on other servers where I get similar ms. Though it could be batching, I'm not entirely sure. 

That being said, several things were scripted well with hunter pets, such as pet pathing, movement, and overall pet responsiveness. Pet movement and pathing feels like I'm playing a modern version of wow (I don't remember much of the tbc days, so I can't compare it to that) in the sense that is very smooth and very rarely bugs out, despite my constant efforts of testing pet behaviour and attempting to find bugs.

I'm not very concerned about any bugs related to hunters so far, as it seems like the team is doing a solid job fixing bugs, and as mentioned this could just be spell batching that I am not used to.

**Comment by Easyfraggy** [comment]
Most of the issues related to clunkiness should be related to https://github.com/Atlantiss/NetherwingBugtracker/issues/135

**Comment by Easyfraggy** [comment]
> Growl should have priority over other autocast spells on petbar, (growl vs gore = use growl if not on cd)

Need proof of this.

Retest all of this and make seperate issues for each of these please, this report wont be useful anymore.
