### ISSUE TITLE
[NPC][Shattered Halls] Shattered Hand Assassin not immediately visible after breaking its stealth

### ISSUE THREAD

**Issue by Jacksn5** [Atlantiss/NetherwingBugtracker#3400]
[//]: # (Enclose links to things related to the bug using http://wowhead.com or any other TBC database.)
[//]: # (You can use screenshot ingame to visual the issue.)
[//]: # (Write your tickets according to the format:)
[//]: # ([Quest][Azuremyst Isle] Red Snapper - Very Tasty!)
[//]: # ([NPC] Magistrix Erona)
[//]: # ([Spell][Mage] Fireball)
[//]: # ([Npc][Drop] Ghostclaw Lynx)
[//]: # ([Web] Armory doesnt work)
[//]: # (To find server revision type `.server info` command in the game chat.)

**Description**: 
This Shattered Hand Assassin (heroic id 20580, normal 17695, stealth spell id 30991?) was not visible to me after breaking its stealth opening with cheap shot, until I used Demoralizing Shout. You can however see the Mage start casting Fireball before it's even visible to me, and according to the rest of my party it happened to them on the occasional other Assassins, unfortunately they don't have recordings.

[![Shattered Hand Assassin not immediately visible after breaking its stealth](http://img.youtube.com/vi/RO5sByAjm-s/0.jpg)](https://www.youtube.com/watch?v=RO5sByAjm-s "Shattered Hand Assassin not immediately visible after breaking its stealth")

Happened on November 27th.

**Comment by Tenoutoften** [comment]
That's about server rev 2367? We're on 2431 and with 2407->2431 I think something happened with stealthed NPCs.

[[NPC]Troll Roof Stalker#23090](https://www.wowhead.com/npc=23090/troll-roof-stalker) are now not using stealth, can be seen [here](https://www.youtube.com/watch?v=aW-AzCiegL8&feature=youtu.be)

**Comment by Jacksn5** [comment]
This seems to be a general issue with stealth, still happening on rev 2645

**Comment by BamboozleNW** [comment]
https://www.youtube.com/watch?v=9uQTMzg8dxE Can be closed, Works fine in Rev 3478.
