### ISSUE TITLE
 [Spell][Paladin] Consecration (Spell Coefficient)

### ISSUE THREAD

**Issue by Mango-Ray** [Atlantiss/NetherwingBugtracker#3402]
### **Description**: 
Consecration's coefficient currently has a fluctuating range that is dependent on how much bonus spell power you have, ranging somewhere between 0.9 to 1, but it should always be 1. 

![](https://i.gyazo.com/89b58a90d841fd328e8337206aee3f69.png)
I recorded values and filled out a chart showing how adding spell power doesn't give a coefficient of 1. I picked spell power values that were divisible by 8 to omit the possibility of any rounding affecting the end equation of the coefficient. This was done without any talents spent, on a single testing dummy to avoid any influencing factors. 

### **Proof of Coefficient value**: 

- http://web.archive.org/web/20080325141058/http://thottbot.com:80/s27173
Below in the comments, you can see a positive comment clearly stating some coefficients for some of the spell ranks.
![](https://i.gyazo.com/80d273063985367b44efcda61257f727.png)
There is no official mention of this on the 2.3 patch notes, but it was a patch where paladins got revamped dramatically.

- http://wowwiki.wikia.com/wiki/Consecration?direction=next&oldid=1317138 
WoWWiki further reinforces the credibly of the above comment by having change logs dated back to this era, and clearly shows the values for all ranks. I have not tested the lower ranks to see if they were off.
 ![](https://i.gyazo.com/16c11d44cfcb3c23df68b8a4191b85af.png)
The webpage also mistakenly says the coefficient is 95.24% on the same page, but its merely the value prior to 2.3 and unfortunately was never deleted upon the update of new information. This is made apparent if you look at older entries of the webpage.

Server Revision: 2431

**Comment by Wolffenstein** [comment]
Please retest in rev 2832.

**Comment by Mormansk** [comment]
Tested in 2851 and I think the coefficient is even lower now.
Casting rank 6 consecration with 273 spell power does a total of 768 damage, when it should be 512+273 = 785.

**Comment by Evolvee** [comment]
@Manaci @Tereneckla retest pls

**Comment by Tereneckla** [comment]
400 Spellpower, 888 damage instead of 912

**Comment by Wolffenstein** [comment]
Fixed in rev 3368.
