### ISSUE TITLE
[BM]Hunter Talent Bestial Discipline only working after relog

### ISSUE THREAD

**Issue by Fenvarien1** [Atlantiss/NetherwingBugtracker#3404]
**Description**: 
http://db.hellfire-tbc.com/?spell=19592
Spellname: Bestial Discipline 
Beastmaster Spec - Tier 5 Talent

**Current behaviour**:
https://gfycat.com/UnacceptableAnotherHalcyon
If you login with BM everything is fine but after reseting your talents there is a problem.
After reset the pet regen energy is halfed as intended but if you put back in the talents points it is still 24energy/4seconds(the regen without talent)
You can fix it by relog. After relog your talent points in Bestial Discipline(Tier5) work.

Tested it with the MM Talent "Go for the Throat"(Tier3). It works after reset your talents without relog.

**Expected behaviour**: 
The points put into the talent work instant.

**Server Revision**: 
2431

**Comment by eri1997** [comment]
All pet related talents that change or affect pet stats still require a resummon to update after putting points into the talents.

**Comment by Godmatik** [comment]
Rev 4016 - still an issue
Dismissing and recalling the pet also fixes the problem.
But adding in talent points that apply a benefit to your pet should do so without need to relog or resummon the pet

**Comment by Godmatik** [comment]
Fixed now, talents applied to pets properly without needing to relog or resummon
