### ISSUE TITLE
[Quest] Westfall - Captain Sander's Treasure Map

### ISSUE THREAD

**Issue by Dekirayne** [Atlantiss/NetherwingBugtracker#3406]
**Description**: 
Captain Sander's Treasure Map has atrrociously low drop chance, i have been grinding murlocs for an hour and no drop of the map.
**Current behaviour**:
Map doesnt drop at all
**Expected behaviour**: 
Map should have a 10% drop chance.
**Server Revision**:

**Comment by wtRCH** [comment]
What's your proof of that?

**Comment by Dekirayne** [comment]
> What's your proof of that?

wowhead %drops https://www.wowhead.com/item=1357/captain-sanders-treasure-map

**Comment by Dekirayne** [comment]
ok now it dropped took me almost 2h

**Comment by Tenoutoften** [comment]
http://web.archive.org/web/20071107191624/http://thottbot.com:80/i1357
[](https://i.gyazo.com/d97497de2ec75864f8e5b9ff7a4cffd1.png)

**Comment by Dekirayne** [comment]
fair enough :D issue closed then.
