### ISSUE TITLE
[Pets] Npcs - westfal murlocs with pets can stack their pets

### ISSUE THREAD

**Issue by Dekirayne** [Atlantiss/NetherwingBugtracker#3407]
**Description**: 
when murloc  with a pet kills me his pets started to multiply for some reason.
**Current behaviour**:
![sfdsdfssdf](https://user-images.githubusercontent.com/12075744/49952555-6edd2300-fefc-11e8-9fa0-9bdd29378db7.png)

On this screenshot you can see multiple healthbars of crrawler pets of the same murloc. he just instantly kills me now with so many pets.
**Expected behaviour**: 

**Server Revision**:

**Comment by Drayo** [comment]
- Cannot reproduce this. https://i.imgur.com/SbMbTlX.png

Can probably be closed.
