### ISSUE TITLE
Infernal Warbringer Immolation aura. Inconsistent

### ISSUE THREAD

**Issue by Cptnlobbe** [Atlantiss/NetherwingBugtracker#3411]
**Description**: 
Only a few of the infernals (one that I've tested) got correct behaviour on immolation aura.
**Current behaviour**:
![immoaura](https://user-images.githubusercontent.com/44623649/49960177-eb2d3180-ff0f-11e8-87f7-04e44ab9b764.jpg)

**Expected behaviour**: 

**Server Revision**: 
2431

**Comment by Gniddikon** [comment]
According to #2334 it should've been fixed in a recent revision, however as of revision 2431 it is still bugged.

**Comment by Wolffenstein** [comment]
Fixed in rev 2435.
