### ISSUE TITLE
[NPC][Netherstorm] Eye of Culuthas [Spell] Focused Bursts

### ISSUE THREAD

**Issue by maxturtlesc2** [Atlantiss/NetherwingBugtracker#3412]
[//]: # (Enclose links to things related to the bug using http://wowhead.com or any other TBC database.)
[//]: # (You can use screenshot ingame to visual the issue.)
[//]: # (Write your tickets according to the format:)
[//]: # ([Quest][Azuremyst Isle] Red Snapper - Very Tasty!)
[//]: # ([NPC] Magistrix Erona)
[//]: # ([Spell][Mage] Fireball)
[//]: # ([Npc][Drop] Ghostclaw Lynx)
[//]: # ([Web] Armory doesnt work)
[//]: # (To find server revision type `.server info` command in the game chat.)

**Description**: 
https://www.wowhead.com/npc=20394/eye-of-culuthas#comments
**Current behaviour**:
Eye of Culuthas does not channel the spell "Focused Bursts" all the way. Hence, the following comment can't even be verified to be working or not.
<img src="https://i.imgur.com/1UT4KLl.png">
**Expected behaviour**: 
Eye of Culuthas should channel Focused Bursts all the way.
**Server Revision**:

**Comment by devo6969** [comment]
The issue seems to be when its incombat with an mob, it will stop its cast, by itself it works completely fine.

**Comment by Wolffenstein** [comment]
Fixed in rev 3680.
