### ISSUE TITLE
[Raid][NPC][Lady Vash'j] Toxic Sporebat poison

### ISSUE THREAD

**Issue by Brasso** [Atlantiss/NetherwingBugtracker#3413]
[//]: # (Enclose links to things related to the bug using http://wowhead.com or any other TBC database.)
[//]: # (You can use screenshot ingame to visual the issue.)
[//]: # (Write your tickets according to the format:)
[//]: # ([Quest][Azuremyst Isle] Red Snapper - Very Tasty!)
[//]: # ([NPC] Magistrix Erona)
[//]: # ([Spell][Mage] Fireball)
[//]: # ([Npc][Drop] Ghostclaw Lynx)
[//]: # ([Web] Armory doesnt work)
[//]: # (To find server revision type `.server info` command in the game chat.)

**Current behaviour**:
The poison from Toxic Sporebat is ticking before the visual of the toxic pool has spawned
https://clips.twitch.tv/BelovedConfidentSardineDancingBanana
**Expected behaviour**: 
The damage should start ticking when the pool can be seen by the player.
**Server Revision**: 
2431

**Comment by Easyfraggy** [comment]
Need proof of this from retail.

**Comment by Imbaslap** [comment]
https://www.youtube.com/watch?v=SYypbzs9d44 12:14-12:17
first tick happens when the green goop pile appears. not before.

**Comment by Easyfraggy** [comment]
First tick happens long before the patch spawns on your link Imbaslap:

![image](https://user-images.githubusercontent.com/36134067/49970634-466d1d00-ff2c-11e8-9afd-553801870c5c.png)
