### ISSUE TITLE
[Raid][NPC][Lady Vash'j] Water Elementals

### ISSUE THREAD

**Issue by Brasso** [Atlantiss/NetherwingBugtracker#3414]
[//]: # (Enclose links to things related to the bug using http://wowhead.com or any other TBC database.)
[//]: # (You can use screenshot ingame to visual the issue.)
[//]: # (Write your tickets according to the format:)
[//]: # ([Quest][Azuremyst Isle] Red Snapper - Very Tasty!)
[//]: # ([NPC] Magistrix Erona)
[//]: # ([Spell][Mage] Fireball)
[//]: # ([Npc][Drop] Ghostclaw Lynx)
[//]: # ([Web] Armory doesnt work)
[//]: # (To find server revision type `.server info` command in the game chat.)

**Current behaviour**:
Elementals are not immune to nature damage. 
https://clips.twitch.tv/SpoopySaltyConsolePunchTrees
**Expected behaviour**: 
https://cdn.discordapp.com/attachments/434094788380196867/522884228912906250/vashj_immunes.png
**Server Revision**: 
2431

**Comment by Imbaslap** [comment]
https://www.youtube.com/watch?v=SYypbzs9d44 source video.

**Comment by Drayo** [comment]
Only the Enchanted Elementals are missing the immunity as far as I could tell.

**Comment by Wolffenstein** [comment]
Fixed in rev 2434.
