### ISSUE TITLE
[Dungeon] Sethekk Guard

### ISSUE THREAD

**Issue by Fenvarien1** [Atlantiss/NetherwingBugtracker#3419]
**Description**: 
http://wowwiki.wikia.com/wiki/Sethekk_Halls
- Immune to Crowd Control in Heroic Mode, can be kited, stunned or damage from 2 guards can be healed through. Cannot be Mind Controlled in Heroic Mode.
http://wowwiki.wikia.com/wiki/Sethekk_Guard
- Immune to Crowd Control in Heroic
http://db.hellfire-tbc.com/?npc=20692
ign: Sethekk Guard(lvl 70-71)

**Current behaviour**:
Immune to CC and stuns.

**Expected behaviour**: 
https://youtu.be/6dr_ssJ5KWo?t=91
atleast stunable(concussion blow from the warrior tank used in the video) after one mob died or stunable without condition.

**Server Revision**: 
2431

**Comment by Neophrone** [comment]
https://www.wowhead.com/npc=18323/sethekk-guard#comments
Immune to any kind of CC. But stunable and disarmable.
"Toggol on 2007/05/15 (Patch 2.0.12)

They are immune to charm also. However, they can be stunned and disarmed."
