### ISSUE TITLE
[NPC][Luzran]

### ISSUE THREAD

**Issue by Thugli** [Atlantiss/NetherwingBugtracker#342]
[//]: # (Enclose links to things related to the bug using http://wowhead.com or any other TBC database.)
[//]: # (You can use screenshot ingame to visual the issue.)
[//]: # (Write your tickets according to the format:)
[//]: # ([Quest][Azuremyst Isle] Red Snapper - Very Tasty!)
[//]: # ([NPC] Magistrix Erona)
[//]: # ([Spell][Mage] Fireball)
[//]: # ([Npc][Drop] Ghostclaw Lynx)
[//]: # ([Web] Armory doesnt work)

**Description**: 
Luzran, an npc in Ghostlands was bugged as he was patting. A video of this can be seen below:
https://clips.twitch.tv/ArtisticThirstyBubbleteaCopyThis

**Current behaviour**:
Luzran bugged out during his pathing as he was teleporting in the air and back on the ground constantly as he walked.

**Expected behaviour**: 
Luzran should walk normally.

**Server Revision**:

**Comment by Easyfraggy** [comment]
@aresbrutus same issue as The other abo had.

**Comment by Evolvee** [comment]
fixed in next hotfix rev

@Easyfraggy what abom?
