### ISSUE TITLE
[Core]Aggro radius towards low level mobs too large

### ISSUE THREAD

**Issue by Tenoutoften** [Atlantiss/NetherwingBugtracker#3420]
**Description**: 
*Notice how close people on retail, even at level 60 in Gnomeregan have to run towards mobs before they agro. The player will often strike the mobs with a melee hit before he pulls the mob by proximity:
https://youtu.be/UXO9TyU2P9Q?t=37

* Now compare on NW, this time a level 70 character: https://www.youtube.com/watch?v=edNDMpgnitM&feature=youtu.be

**Current behaviour**:
To large aggro radius towards low level mobs

**Expected behaviour**: 
Smaller aggro radius towards low level mobs

**Server Revision**: 
2431

**Comment by Tenoutoften** [comment]
Video of a 70 hunter going through normal ramparts in patch 2.4
https://www.youtube.com/watch?v=1FbckUocuE4

**Comment by Wolffenstein** [comment]
Should be better in rev 2443.
