### ISSUE TITLE
[NPC] Deathstalker Adamant

### ISSUE THREAD

**Issue by Mentat33** [Atlantiss/NetherwingBugtracker#3423]
[//]: # (Enclose links to things related to the bug using http://wowhead.com or any other TBC database.)
[//]: # (You can use screenshot ingame to visual the issue.)
[//]: # (Write your tickets according to the format:)
[//]: # ([Quest][Azuremyst Isle] Red Snapper - Very Tasty!)
[//]: # ([NPC] Magistrix Erona)
[//]: # ([Spell][Mage] Fireball)
[//]: # ([Npc][Drop] Ghostclaw Lynx)
[//]: # ([Web] Armory doesnt work)
[//]: # (To find server revision type `.server info` command in the game chat.)

**Description**: 
Deathstalker Adamant (Entry: 3849, Id: 1, GUIDLow: 296503) does not attack Alliance when attacked. 

**Current behaviour**:
Deathstalker Adamant (Entry: 3849, Id: 1, GUIDLow: 296503) does not attack Alliance when attacked. 

**Expected behaviour**: 
Should melee alliance players when aggrod.

**Server Revision**: 
2431

**Comment by Manaci** [comment]
Only happens of you range attack him outside of his cell, kinda non-issue.
