### ISSUE TITLE
[Item] Grime-Encrusted Object

### ISSUE THREAD

**Issue by Mentat33** [Atlantiss/NetherwingBugtracker#3426]
[//]: # (Enclose links to things related to the bug using http://wowhead.com or any other TBC database.)
[//]: # (You can use screenshot ingame to visual the issue.)
[//]: # (Write your tickets according to the format:)
[//]: # ([Quest][Azuremyst Isle] Red Snapper - Very Tasty!)
[//]: # ([NPC] Magistrix Erona)
[//]: # ([Spell][Mage] Fireball)
[//]: # ([Npc][Drop] Ghostclaw Lynx)
[//]: # ([Web] Armory doesnt work)
[//]: # (To find server revision type `.server info` command in the game chat.)

**Description**: 
This item seems to have pretty darn close to a 90-95% drop chance off of mobs in Gnomeregan

**Current behaviour**:
Very very high drop chance

**Expected behaviour**: 
Drop Chance should be FAR lower
https://web.archive.org/web/20071012095409/http://thottbot.com:80/i9308 

**Server Revision**: 
2431

**Comment by Tenoutoften** [comment]
Can confirm, I killed some mobs there today

**Comment by aresbrutus** [comment]
Fixed in rev `Nariman`
