### ISSUE TITLE
[Dungeon][OHF][Spell][NPC] MC on Durnholde Rifleman causes server crash

### ISSUE THREAD

**Issue by idsss** [Atlantiss/NetherwingBugtracker#3427]
![wowscrnshot_121418_183523](https://user-images.githubusercontent.com/43757915/50021282-e1bbcc00-ffd8-11e8-9833-f19a062a4fbd.jpg)

MC'ing that guy crashed the server (maybe other mobs in there too)

rev 2431

edit: mc on durnholde mages crashes it too (rev 2483)

**Comment by Thugli** [comment]
What unit frame addon is this

**Comment by idsss** [comment]
ufi backport thugli

**Comment by Evolvee** [comment]
doesnt happen for me
