### ISSUE TITLE
[Spell] [Warlock] Howling Terror on whelps from Black Morass portal

### ISSUE THREAD

**Issue by Kinson72** [Atlantiss/NetherwingBugtracker#3429]
[//]: # (Enclose links to things related to the bug using http://wowhead.com or any other TBC database.)
[//]: # (You can use screenshot ingame to visual the issue.)
[//]: # (Write your tickets according to the format:)
[//]: # ([Quest][Azuremyst Isle] Red Snapper - Very Tasty!)
[//]: # ([NPC] Magistrix Erona)
[//]: # ([Spell][Mage] Fireball)
[//]: # ([Npc][Drop] Ghostclaw Lynx)
[//]: # ([Web] Armory doesnt work)
[//]: # (To find server revision type `.server info` command in the game chat.)
Yesterday I used Howl of Terror on a set of 3 whelps that come out of Black Morass portals.  The whelps showed the fear icon, but it had no effect and they immediately came to me and melee'd.  I am not sure if this is spell-related or mob-related, but figured it was reportable.

**Comment by Tenoutoften** [comment]
Anything else happened? Did the whelps have any other effects on them?

**Comment by Kinson72** [comment]
I am not quite sure. We had a bunch of mobs on us from the portal and I aoe fear'd the whelps as soon as they came.  They immediately switched to and killed me with fear icons.  I did not check any of their buffs and this was the only time i saw it.  I have not tried to recreate.

**Comment by devo6969** [comment]
This is fixed, Overlapped the 2 abilities Howl of Terror/Physic Scream after the video, saw no bugs. 
https://www.youtube.com/watch?v=3Q_Ok9ubGcY
