### ISSUE TITLE
[NPC] [Escort] Demolitionist Legoso is a friend to all living things

### ISSUE THREAD

**Issue by knugen1234** [Atlantiss/NetherwingBugtracker#343]
[//]: # (Enclose links to things related to the bug using http://wowhead.com or any other TBC database.)
[//]: # (You can use screenshot ingame to visual the issue.)
[//]: # (Write your tickets according to the format:)
[//]: # ([Quest][Azuremyst Isle] Red Snapper - Very Tasty!)
[//]: # ([NPC] Magistrix Erona)
[//]: # ([Spell][Mage] Fireball)
[//]: # ([Npc][Drop] Ghostclaw Lynx)
[//]: # ([Web] Armory doesnt work)

**Description**: 
During the quest 'Ending Their World' you must escort Demolitionist Legoso to the Vector Coil. However Legoso won't attack any creatures unless they attack him first, some of the creatures isn't event hostile towards him which means that even though they might attack you he will just ignore them and continue running towards the Vector Coil while you stand there trying to keep up. Since the Blood Elf in the area are hostile towards him and will attack him it kinda works out but does means that he can usually pull 1-3 extra mobs before "ignoring" his current pathing

I also noticed that sometimes he will just stand around doing nothing whilst a ranged Blood Elf is shooting at him.
 **Current behaviour**:
Doesnt seem to be hostile to any creature **except when attacked**.
**Expected behaviour**: 
Should actively engage in combat with / agro creatures that are hostile to him **and the player**
**Server Revision**: 
2029-2032 (forgot to check which revision, this was yesterday)

**Comment by wtRCH** [comment]
This thing seems to happen to every Escort quest NPC.

**Comment by Tenoutoften** [comment]
Maybe he isn't suppose to be defensive mode towards the player/player's party taking the quest?
[wowhead comment](https://www.wowhead.com/quest=9759/ending-their-world#comments)
![](https://i.gyazo.com/dc131751f58557951d78b982053e645f.png)

**Comment by Tenoutoften** [comment]
I did this quest today and it doesn't have this issue. If I engaged a mob he would help me

**Comment by Tenoutoften** [comment]
Merged into https://github.com/Atlantiss/NetherwingBugtracker/issues/3678 but we need to know how to reproduce
