### ISSUE TITLE
Enchant Ring Healing Power not functioning correctly

### ISSUE THREAD

**Issue by mantacore** [Atlantiss/NetherwingBugtracker#3430]
Description:  Enchant Ring:  Healing Power not effective on second ring

Current behaviour: If both rings are enchanted with Healing Power and rings placed in the slots only one of +20 healing power is updated in stats

Expected behaviour: Both of the enchants healing should be added to the current Bonus Healing stat.

Server Revision: 2431

**Comment by Neophrone** [comment]
Both enchants will add bonus healing. But there is another bug:
if u'll equip 2 rings with +20 healing enchants and after that u'll take off one of the ring - +20 healing bonus from enchant of this ring will stay, but if u'll equip this ring again and take off it again this bug will dissapear.

**Comment by Tenoutoften** [comment]
https://github.com/Atlantiss/NetherwingBugtracker/issues/2779
