### ISSUE TITLE
[EN][Loot] Snow Leopard

### ISSUE THREAD

**Issue by tsuone** [Atlantiss/NetherwingBugtracker#3433]
[//]: # (Enclose links to things related to the bug using http://wowhead.com or any other TBC database.)
[//]: # (You can use screenshot ingame to visual the issue.)
[//]: # (Write your tickets according to the format:)
[//]: # ([Quest][Azuremyst Isle] Red Snapper - Very Tasty!)
[//]: # ([NPC] Magistrix Erona)
[//]: # ([Spell][Mage] Fireball)
[//]: # ([Npc][Drop] Ghostclaw Lynx)
[//]: # ([Web] Armory doesnt work)
[//]: # (To find server revision type `.server info` command in the game chat.)

**Description**: Snow Leopard loot table is wrong.

**Current behaviour**: Snow Leopard in Dun Morogh drops Peacebloom.

**Expected behaviour**: Snow Leopard (if global, beasts) shouldn't drop herbs like Peacebloom.

**Server Revision**: 2431

**Comment by Tenoutoften** [comment]
Would be good if someone with access to the database can check.

* Murlocs, Nagas, Owlkin and Worgens also drop cloth https://github.com/Atlantiss/NetherwingBugtracker/issues/372

In addition there is likely a lot of small issues like this, but should probably make a larger issue regarding these random ones?:
* [[NPC]Vale Moth#16520](http://web.archive.org/web/20071227085445/http://thottbot.com:80/c16520#A::A) has way too low drop chance on Broken Antenna / Torn Moth Wing. [NW behavior](https://www.youtube.com/watch?v=-Jxinwe4zmo&feature=youtu.be), I killed about 20 with zero drops apart from a set of pants.

**Comment by tsuone** [comment]
@Tereneckla @Manaci

**Comment by Tereneckla** [comment]
Fixed
