### ISSUE TITLE
[Core] Snapshotting doesn’t work at all

### ISSUE THREAD

**Issue by Helelel** [Atlantiss/NetherwingBugtracker#3435]
Description: DoTs should retain the SP/AP values of the player when first applied. Using an AP adjusted spell like Rend or Lacerate, or using an SP adjusted spell like Curse of Agony or Seal of Vengeance after a on use SP trinket should increase the coefficient of the spell by the adjusted rate for the entire duration of the spell, for example. They currently do not.

Current behaviour: DoTs do seem to be temporarily affected by flat percentage damage increases, but are not affected by temporary AP/SP changes at all. I did not test this on HoTs, but this may be the case for them, as well.

Expected behaviour: DoT abilities with AP/SP scaling that fall off should be affected by temporary changes to AP/SP based on the AP/SP value of the character when casted. Stacking DoTs that do not naturally fall off, like Lacerate and Seal of Vengeance, should carry the AP/SP value of the character on application on a stack by stack basis throughout the length that they remain active/refreshed.

**Comment by Evolvee** [comment]
no
hots/dots do dmg based on spell dmg u had on the first application
