### ISSUE TITLE
[Core]Blade Flurry/Sweeing Strikes shouldn't hit critters

### ISSUE THREAD

**Issue by Tenoutoften** [Atlantiss/NetherwingBugtracker#3436]
**Description**: 
From [Patch 2.4.2](http://wowwiki.wikia.com/wiki/Patch_2.4.2)
* Fixed an issue where chain damage spells were chaining to critters.

* Ability: [[Spell]Blade Flurry#13877](https://www.wowhead.com/spell=13877/blade-flurry): This ability can no longer hit critters as its secondary targets and will now use a proper range calculation for all secondary targets.

Currently [chains onto critters on NW](https://www.youtube.com/watch?v=54ixr4LeXJY&feature=youtu.be) but shouldn't.

* [[Spell]Sweeping Strikes#12328](https://db.excalibur.ws/?spell=12328): This ability can no longer hit critters as its secondary targets and will now use a proper range calculation for all secondary targets.

Currently [chains onto critters NW](https://www.youtube.com/watch?v=aHLlfJ7Kb3M&feature=youtu.be) but shouldn't.

Not sure if this change should affect [[Spell]Chain Lightning#25442](https://db.excalibur.ws/?spell=25442)

**Expected behaviour**: 
Expected to ignore Critters.

**Server Revision**: 
2431

**Comment by Wolffenstein** [comment]
Fixed in rev 2439.
