### ISSUE TITLE
[Spell] Serious bug with how spells are considered cast

### ISSUE THREAD

**Issue by parlaking** [Atlantiss/NetherwingBugtracker#3439]
[//]: # (Enclose links to things related to the bug using http://wowhead.com or any other TBC database.)
[//]: # (You can use screenshot ingame to visual the issue.)
[//]: # (Write your tickets according to the format:)
[//]: # ([Quest][Azuremyst Isle] Red Snapper - Very Tasty!)
[//]: # ([NPC] Magistrix Erona)
[//]: # ([Spell][Mage] Fireball)
[//]: # ([Npc][Drop] Ghostclaw Lynx)
[//]: # ([Web] Armory doesnt work)
[//]: # (To find server revision type `.server info` command in the game chat.)

**Description**: 

There are side effects of the delay it takes for a spell to be considered cast. I don't know if it's the spellbatching or not, because I don't recall this happening a few weeks ago and I was told there have been no recent changes to spell batching. But I could have just not noticed it a few weeks ago, because 19 days ago someone made a report about 600ms spell batch delay. https://github.com/Atlantiss/NetherwingBugtracker/issues/2742

**Current behaviour**:

Certain spell procs that rely on casts being considered 'cast' aren't behaving properly.
The easiest example of this is with a druid with the balance tree talent Nature's Grace. I will outline the steps to reproduce the problem below. Is very easy to reproduce and happens 100% of the time.

**Expected behaviour**: 

**Steps to reproduce the problem:**

1. Make a druid, get the talent Nature's Grace
2. Spam starfire onto target dummy as fast as you can
3. After you crit, keep spamming it. You'll notice that your next cast does not consume nature's grace.
4. Do the same thing except wait ~500-700ms (the weird spell delay) after each starfire cast ends before casting the next starfire. You will notice that your next starfire will be properly consumed.

So there's a disconnect between the spell cast delay system and what it considers to be a cast if it's cast before or after the delay system. Especially considering that half of the Nature's Grace proc works immediately (the -0.5 second cast time part), while the other half (the internal 'look for completion of cast' part) is improperly interacting with the cast delay system.

**Server Revision**:

**Comment by Onsty** [comment]
I tried to reproduce that and that's what I noticed: it seems like nature's grace buff occurs twice, first time when a spell that will crit has finished being cast (as it should be), and then after the damage is dealt to the target natures grace effect is refreshed.(as it shouldn't be).

It clearly seen that after spell finished being cast timer on buff starts counting down, but then refreshed back to 15s at the moment when damage is dealt to the target.

<a href="https://gyazo.com/7286fa57cb05510b19dc8d418e1696f6"><img src="https://i.gyazo.com/7286fa57cb05510b19dc8d418e1696f6.gif" alt="Image from Gyazo" width="632.5"/></a>

In this case if u spam spell button as fast as u can, when crit ocurs first natures grace effect consumed by next cast, then "projectile" reaches the target, effect refreshed and applied to the second cast. 
(I can record it if needed)
So after one critical hit your next 2 (non critical) casts get -0.5s of cast time. What can be considered as some kind of dps abuse )

**Comment by Onsty** [comment]
Here is the video.

https://gfycat.com/olddimpledbunting

After first critical cast, next 2 (non critical) get -0,5s

**Comment by SwiftieTBC** [comment]
To clarify this doesnt seem like an issue to do with spell delay moreso an issue with natures grace proccing when the projectile leaves and will crit (blizzlike) and when the crit hits the target (bug)

**Comment by Jseay1313** [comment]
Swiftie seems spot on, natures grace itself here works flawlessly with wrath and spell interchanging which is a rarity on private servers, it correctly procs on the cast but as mentioned seems to proc again when the crit hits the target

**Comment by Onsty** [comment]
@Wolffenstein 
This one fucked up again somehow. Nature's Grace proc twice, on cast and on hit. Prolly affect other on cast procs too, didn't check tho. Just 2 weeks ago it wasn't a case

![56de461c50b9c3e0fad12ee2a501fd61](https://user-images.githubusercontent.com/44346265/212474650-922e4277-3402-44c5-99fc-a48e08aab09b.gif)
