### ISSUE TITLE
Fully resist Arcane Devourer's Devour Mana, still drained mana

### ISSUE THREAD

**Issue by gunnermaniac** [Atlantiss/NetherwingBugtracker#344]
[//]: # (Enclose links to things related to the bug using http://wowhead.com or any other TBC database.)
[//]: # (You can use screenshot ingame to visual the issue.)
[//]: # (Write your tickets according to the format:)
[//]: # ([Quest][Azuremyst Isle] Red Snapper - Very Tasty!)
[//]: # ([NPC] Magistrix Erona)
[//]: # ([Spell][Mage] Fireball)
[//]: # ([Npc][Drop] Ghostclaw Lynx)
[//]: # ([Web] Armory doesnt work)

https://i.imgur.com/4SrUcht.jpg

**Description**: Fully resisted Arcane Devourer Devour Mana, but still lost mana. 

**Current behaviour**: Losing mana even through full resist

**Expected behaviour**: No mana lost on full resist

**Server Revision**:

**Comment by Tereneckla** [comment]
Fixed
