### ISSUE TITLE
[Raid][SSC][Elevator boss] Game crashes if you die on elevator

### ISSUE THREAD

**Issue by Brasso** [Atlantiss/NetherwingBugtracker#3440]
[//]: # (Enclose links to things related to the bug using http://wowhead.com or any other TBC database.)
[//]: # (You can use screenshot ingame to visual the issue.)
[//]: # (Write your tickets according to the format:)
[//]: # ([Quest][Azuremyst Isle] Red Snapper - Very Tasty!)
[//]: # ([NPC] Magistrix Erona)
[//]: # ([Spell][Mage] Fireball)
[//]: # ([Npc][Drop] Ghostclaw Lynx)
[//]: # ([Web] Armory doesnt work)
[//]: # (To find server revision type `.server info` command in the game chat.)

If  you miss the lift in SSC and die on the transport the game crashes, Wowerror with the message "Failed to dereference transport!"

**Server Revision**: 
2431

**Comment by Wolffenstein** [comment]
It doesn't crash for me. Can you record it?

**Comment by Brasso** [comment]
The game crashes when I click release spirit, consistently.

**Comment by Brasso** [comment]
Confirmed with another player. Suicide on elevator, release spirit leads to crash.

**Comment by Brasso** [comment]
Same issue on the second elevator.

**Comment by Brasso** [comment]
Confirmed with GM Rion. Doesn't happen if you GM teleport into the raid, you need to be in a raid group.

**Comment by Easyfraggy** [comment]
Is this still happening?

**Comment by devo6969** [comment]
Tried to recreate on the PTR, was unable to.

**Comment by Tereneckla** [comment]
Think elevator crashes are a mac client problem

**Comment by Godmatik** [comment]
Mac client is no longer supported, closing
