### ISSUE TITLE
[Dungeon][NPC] H Sethekk Halls - Sethekk Ravenguards add on 1st Boss

### ISSUE THREAD

**Issue by idsss** [Atlantiss/NetherwingBugtracker#3441]
**Description**: 
![wowscrnshot_121518_174314](https://user-images.githubusercontent.com/43757915/50045480-f5783880-0093-11e9-828c-039b877af7a4.jpg)

**Current behaviour**: Had the 2 Ravenguards (and on our 1st try the non elite bird pack aswell) behind 1st Boss in Sethekk hc join the fight when he summoned his elementals

**Expected behaviour**: 
guess that shouldn't happen
**Server Revision**: 2431

**Comment by Tenoutoften** [comment]
At what point during the fight, do you think they pulled instantly?

**Comment by idsss** [comment]
think it was about when he spawned the 2nd wave of adds

**Comment by Tenoutoften** [comment]
Have you figure out what triggers it specifically...

**Comment by idsss** [comment]
just tried it again didnt happen this time, close this i guess

**Comment by Easyfraggy** [comment]
Theres definitely something happening where you pull adds on this fight - I think it's related to the small elemental adds - this also happened to us on beta when we did it - but we could not replicate it.

**Comment by devo6969** [comment]
Having a hard time replicating this :/ Killed the mob 50 times in various places, couldn't get the ravenlords to pull
