### ISSUE TITLE
[Core] Movement Stutter

### ISSUE THREAD

**Issue by nullfoxh** [Atlantiss/NetherwingBugtracker#3442]
Weird movement stutter. Especially noticeable in the first 5 seconds of this video where the character will microstutter and blink:

https://streamable.com/mxu5u

**Comment by SuddenDeath** [comment]
Definitely noticeable at times, not as fluid as for example Warmane: https://youtu.be/vBn_W8ppQOw?t=45s

**Comment by The14me** [comment]
Need more info.Like how it happen,how to reproduce,both ppl seen it etc.?

**Comment by SuddenDeath** [comment]
@The14me lol, watch someone running around near you closely, and you'll see the stutter.

**Comment by Drayo** [comment]
The streamable link is dead.

Sure, super smooth movement would be nice, but generally I feel like the current movement seems fine. 

There are some stutters here and there but to be honest, it's much worse on classic for example, so NW does not seem bad at all.
