### ISSUE TITLE
[Battleground] Crashing during a BG bug

### ISSUE THREAD

**Issue by killablink** [Atlantiss/NetherwingBugtracker#3443]
**Description**: If you crash during a bg, you get teleported to your hearthstone but the game still thinks you're in a BG
https://gfycat.com/HonestRegularAmericantoad

**Current behaviour**: If you crash during a bg, you get teleported to your hearthstone but the game still thinks you're in a BG

**Expected behaviour**: I don't exactly remember when they changed it but I think there was a small amount of time you had so you could relog and still be in the BG. Either ways you shouldn't still be considered in the BG if you're not in the BG lol.

**Server Revision**:  2431

**Comment by Evolvee** [comment]
@Wolffenstein probably emtecs /who fix

**Comment by Godmatik** [comment]
Tested with a couple crashes on PTR server, unable to reproduce. Have also not heard of this issue happening in the past year on Netherwing.

Potentially fixed at some point. Will reopen if I hear of it happening again.
