### ISSUE TITLE
[Item][Oil of Immolation] Affected by spell damage 

### ISSUE THREAD

**Issue by naekobest** [Atlantiss/NetherwingBugtracker#3444]
**Description**: 
You can stack fire spell damage to increase the damage of Oil of Immolation

**Current behaviour**:
You can stack as much spell damage (preferable fire) to increas the damge of Oil of Immolation.

[Fel Armor](https://i.gyazo.com/b7e9d522f225a36bf301808f785795e0.mp4)
[Fel Armor + Imp Sacrifice](https://i.gyazo.com/c51c1f82d75477ecfed515139e87a20d.mp4)
[Full Buffed + Trinket](https://i.gyazo.com/36e097f5159e20eda80220e3775edc53.mp4)

**Expected behaviour**: 
Oil of Immolation should NOT get affected by spell damage bonuses as of Patch 1.6.1
http://wowwiki.wikia.com/wiki/Oil_of_Immolation

**Server Revision**: 
2431

**Comment by Wolffenstein** [comment]
Fixed in rev 2509.
