### ISSUE TITLE
[Dungeon][Blood Furnace][Boss]The Maker - Domination Spell on Warriors

### ISSUE THREAD

**Issue by Hotmotion** [Atlantiss/NetherwingBugtracker#3445]
[//]: # (Enclose links to things related to the bug using http://wowhead.com or any other TBC database.)
[//]: # (You can use screenshot ingame to visual the issue.)
[//]: # (Write your tickets according to the format:)
[//]: # ([Quest][Azuremyst Isle] Red Snapper - Very Tasty!)
[//]: # ([NPC] Magistrix Erona)
[//]: # ([Spell][Mage] Fireball)
[//]: # ([Npc][Drop] Ghostclaw Lynx)
[//]: # ([Web] Armory doesnt work)
[//]: # (To find server revision type `.server info` command in the game chat.)

**Description**: 
After getting mind controlled by domination spell, boss died and charge got broken. After that every time i used my charge/intercept my character would normally rush to the target but afterwards it would slowly walk back to the position from where i used it, and i couldn't control my character until he got back to the starting position. "Helpful tip" GM Narilrave came and we tested few things and he said i still had aura on me so he killed me and revived me and bug was gone and charge was working properly again.
**Current behaviour**:
After using charge character would walk back to the position where charge was used from.
**Expected behaviour**: 
It should not walk back to the position from where it was used from.
**Server Revision**: 2431

**Comment by Wolffenstein** [comment]
Duplicate, it was already reported before.
