### ISSUE TITLE
[Spell] Seed of Corruption visual effects.

### ISSUE THREAD

**Issue by Neophrone** [Atlantiss/NetherwingBugtracker#3447]
[//]: # (Enclose links to things related to the bug using http://wowhead.com or any other TBC database.)
[//]: # (You can use screenshot ingame to visual the issue.)
[//]: # (Write your tickets according to the format:)
[//]: # ([Quest][Azuremyst Isle] Red Snapper - Very Tasty!)
[//]: # ([NPC] Magistrix Erona)
[//]: # ([Spell][Mage] Fireball)
[//]: # ([Npc][Drop] Ghostclaw Lynx)
[//]: # ([Web] Armory doesnt work)
[//]: # (To find server revision type `.server info` command in the game chat.)

**Description**: 
Mechanically spell works as it should works, but visually it's not. When u use it on target u see purple glowing around the target, but also it should do impressive explosion(visualy) when it's trigger.
How it visually works on Netherwing:
![soc](https://user-images.githubusercontent.com/43533040/50048193-56246700-00ce-11e9-9efd-eba0f4c98d1d.gif)
How it should work:
https://youtu.be/P4WLDck4ZHw?t=41
**Current behaviour**:
Lack of visual effects on spell triggering.
**Expected behaviour**: 
A huge explosion on spell triggering.
**Server Revision**: 2431.

**Comment by Neophrone** [comment]
Also there is a lack of sound effect as well. Next video demonstrate sound effect (and visual effect too):
https://youtu.be/ILAydhZm_-k

**Comment by Wolffenstein** [comment]
Fixed in rev 2446.
