### ISSUE TITLE
[Scarlet Monastery Cath] Scarlet Command Mograin and Inquisitor Whitemane

### ISSUE THREAD

**Issue by Yunnichan** [Atlantiss/NetherwingBugtracker#3448]
[//]: # (Enclose links to things related to the bug using http://wowhead.com or any other TBC database.)
[//]: # (You can use screenshot ingame to visual the issue.)
[//]: # (Write your tickets according to the format:)
[//]: # ([Quest][Azuremyst Isle] Red Snapper - Very Tasty!)
[//]: # ([NPC] Magistrix Erona)
[//]: # ([Spell][Mage] Fireball)
[//]: # ([Npc][Drop] Ghostclaw Lynx)
[//]: # ([Web] Armory doesnt work)
[//]: # (To find server revision type `.server info` command in the game chat.)

**Description**: 
#NPC High Inquisitor Whitemane did not resurrect #NPC Commander Mograine after she put me (a hunter) and my pet into a deep sleep.

**Current behaviour**:
After I was awoken from the deep sleep spell that Whitemane had cast, me and my pet were able to attack Whitemane until she had 1% health left and then she would noy die and was then not attackable.

**Expected behaviour**: 
I believe she is supposed to ressurrect Commander Mograine after the player kills him the first time and then gets High Inquisitor Whitemane to 1% health, where she will resurrect him and heal herself (not sure if she is supposed to heal herself after rezzing him)

**Server Revision**:

**Comment by Godmatik** [comment]
Rev 4014
Unable to reproduce as a hunter
Was successfully put to sleep everytime and Whitemane resurrected with no issues.
Even tried with Beastial Wrath up, same result.
Probably fixed at some point.
