### ISSUE TITLE
[Core][Paladin] Healing Threat Modifier

### ISSUE THREAD

**Issue by Mango-Ray** [Atlantiss/NetherwingBugtracker#3449]
### **Description**: 
Healing threat done from a paladin should be affected by a x0.25 modifier instead of the current x0.5 that Netherwing is currently using. Paladins have a passive x0.5 modifier to healing threat that is multiplied by the global x0.5 threat reduction that exists for all classes when healing.

This is an important fix as many tanks wont pick up paladin healers for 5 mans, as they do too much threat in comparison to other healers.

### **Proof of Claim**: 

- Omen 2.4.3, downloaded from wowace.com, clearly gives paladins a 0.25 threat modifier on healing. This was done with zero buffs or talents.
![](https://i.gyazo.com/4eabddfafe73f9a296da8ce993e394cb.png)

- http://wowwiki.wikia.com/wiki/Threat?direction=next&oldid=1277765
WoWWiki snapshot from june 20, 2008 that further supports this claim.
![](https://i.gyazo.com/f1d71b59cc527d07fa03081513fbb0d6.png)

Notes: google " paladin healing threat "0.25" "and you will get many more sources if you find it necessary.

Server Revision: 2431

**Comment by Kidcudi123** [comment]
Have you tested this with other healers if they all have it wrong?

**Comment by Mango-Ray** [comment]
@Kidcudi123 only with priest and paladin. Every other healer should have a x0.5 multiplier and almost all  private servers have this correct by default. Paladins are unique in this regard for some reason, but they desperately need it being as they don't have threat reduction talents, whereas every other healer class does.

**Comment by Wolffenstein** [comment]
Fixed in rev 2449.
