### ISSUE TITLE
[Quest][Dun Morogh] Frostmane Hold (fully explore radius)

### ISSUE THREAD

**Issue by killablink** [Atlantiss/NetherwingBugtracker#3450]
**Description**: The fully explore radius of this quest seems wrong. I could walk all the way in the middle and I would not get the objective complete until I walked into this exact spot: 

![wowscrnshot_121618_011309](https://user-images.githubusercontent.com/43510874/50050729-8f120b00-00d1-11e9-9722-554fdf8357e5.jpg)

Did it 2 other times on a 70. 

One time I killed the last troll deep inside the hold and it completed the fully explore objective at the same time. (The objective to fully explore should be separated, it seems right now you can't fully explore until you kill 5 trolls)
https://gfycat.com/AbsoluteSandyBrocketdeer

To prove it, the 2nd time I killed 5 trolls and I went to the same place I "fully" explored the hold in the last clip but it still wouldn't complete it. So I went to the spot in the first pic and got the credit to fully explore.
https://gfycat.com/BestExcellentAfricanpiedkingfisher

**Expected behaviour**:  The objective should complete wherever you're deep inside the hold and not just at towards that random point while having 5 trolls killed.

**Server Revision**:  2431

**Comment by Evolvee** [comment]
all 3 areatriggers that are in that cave are already involved, there are no others
