### ISSUE TITLE
[Combat log] I think? Raid cooldown addons not working correctly

### ISSUE THREAD

**Issue by WarriorTSW** [Atlantiss/NetherwingBugtracker#3452]
[//]: # (Enclose links to things related to the bug using http://wowhead.com or any other TBC database.)
[//]: # (You can use screenshot ingame to visual the issue.)
[//]: # (Write your tickets according to the format:)
[//]: # ([Quest][Azuremyst Isle] Red Snapper - Very Tasty!)
[//]: # ([NPC] Magistrix Erona)
[//]: # ([Spell][Mage] Fireball)
[//]: # ([Npc][Drop] Ghostclaw Lynx)
[//]: # ([Web] Armory doesnt work)
[//]: # (To find server revision type `.server info` command in the game chat.)

**Description**: 
Having tested multiple raid cooldown addons, I cant seem to get any of them working correctly.
Ora2
RAT
CombatLogCleaner doesnt seem to help
Addons are for correct version for the server and are confirmed working elsewhere.

**Current behaviour**:
When I expect to see a shaman blood lust for example ready to be used. The addons show nothing. This is the case when all other addons are turned off. It does appear that the addons do scan the spec of the player correctly. No addon errors occur. 

**Expected behaviour**: 
Addons being able to track player cooldowns

**Server Revision**: 
2431

**Comment by gwxse8w** [comment]
Just tested it.
If both players are using oRA2, for sure you get the Druid's Combat Res bar/cd.
I then tested with Shaman's Bloodlust and that's not tracked indeed. Couldn't test Anhk.

**Comment by Godmatik** [comment]
Probably fixed a long time ago, able to track it just fine. 

Can be closed
