### ISSUE TITLE
Sarkoth

### ISSUE THREAD

**Issue by Drackath** [Atlantiss/NetherwingBugtracker#3453]
Just a minor issue that doesn't affect leveling but sarckoth is a liitle bit off track.

 

https://user-images.githubusercontent.com/31246378/50053296-311a0d80-013b-11e9-9ed0-141f67c64085.png

**Comment by Wolffenstein** [comment]
Proof?

**Comment by Tenoutoften** [comment]
Wowhead screenshot from april 2008
![](https://wow.zamimg.com/uploads/screenshots/normal/79633-sarkoth.jpg)
