### ISSUE TITLE
Peons in valley of Trials

### ISSUE THREAD

**Issue by Drackath** [Atlantiss/NetherwingBugtracker#3454]
Another minor issue that doesn't affect gameplay but the peons are supposed to chop the tree no the lumber pile. Seen this on many private servers before and hoped you can fix it.

(https://user-images.githubusercontent.com/31246378/50053380-eb5e4480-013c-11e9-89d2-21902c7de0ce.png)

**Comment by Wolffenstein** [comment]
That is incorrect. Please don't cite other private servers as source.
