### ISSUE TITLE
[Terokkar Forest]Warp Stalker

### ISSUE THREAD

**Issue by Fenvarien1** [Atlantiss/NetherwingBugtracker#3455]
**Description**: 
http://db.hellfire-tbc.com/?npc=18464
Warp Stalker 63-64
Terokkar Forest

**Current behaviour**:
if they port behind you they stop autoattacking but casting their slow from time to time. he starts attacking after you move.
only happens if he don't need to move towards you after teleport.

**Expected behaviour**: 
attack me even without me reposition

**Server Revision**: 
2447

**Comment by Brasso** [comment]
https://www.youtube.com/watch?v=w_Zc0n0tbPs With bonus clip after.

**Comment by Wolffenstein** [comment]
Fixed in rev 2470.
