### ISSUE TITLE
[Spell][Paladin] Divine Intervention target sometimes loses the buff

### ISSUE THREAD

**Issue by Mikik3jr** [Atlantiss/NetherwingBugtracker#3456]
[//]: # (Enclose links to things related to the bug using http://wowhead.com or any other TBC database.)
[//]: # (You can use screenshot ingame to visual the issue.)
[//]: # (Write your tickets according to the format:)
[//]: # ([Quest][Azuremyst Isle] Red Snapper - Very Tasty!)
[//]: # ([NPC] Magistrix Erona)
[//]: # ([Spell][Mage] Fireball)
[//]: # ([Npc][Drop] Ghostclaw Lynx)
[//]: # ([Web] Armory doesnt work)
[//]: # (To find server revision type `.server info` command in the game chat.)

**Description**: 
It happened twice in Karazhan. Once when we accidentally pulled 3 ushers I used DI on our shaman, I died, but somehow the DI instantly removed from the shaman. Sadly I don't have pics about that.

Next one when we pulled trash after curator, I DI-d our tank paladin, but he didn't stop moving at all.

**Current behaviour**:
Here are the pictures that I used DI on our tank paladin, he had the buff for like 0.3s. He claimed he didn't remove the buff.
![image](https://user-images.githubusercontent.com/43505031/50057069-ba463a00-0165-11e9-88c6-7dbeb10a43a5.png)
![image](https://user-images.githubusercontent.com/43505031/50057061-a69ad380-0165-11e9-9107-ba9e70c86a74.png)

When we wiped on Netherspite, our Tank paladin used DI on me and it worked. I tried to remove it by moving, jumping, bubble, wingz, potion drinking, none of them removed it.

**Expected behaviour**: 
DI should stay until not cancelled/for 3 minutes.

**Server Revision**: 
2447

**Comment by Drayo** [comment]
Throughout T4/5 and 6 I have never really seen DI fail. And we wiped a lot. ;)

Might have been an early beta issue or the tank might have had some cancelaura macro. I believe if it happened after beta some pally would have mentioned it.

Can probably be closed.
