### ISSUE TITLE
[NPC] [Boss] [Karazhan] Illhoofs Chains (Visual Issue)

### ISSUE THREAD

**Issue by Drayo** [Atlantiss/NetherwingBugtracker#3457]
[//]: # (Enclose links to things related to the bug using http://wowhead.com or any other TBC database.)
[//]: # (You can use screenshot ingame to visual the issue.)
[//]: # (Write your tickets according to the format:)
[//]: # ([Quest][Azuremyst Isle] Red Snapper - Very Tasty!)
[//]: # ([NPC] Magistrix Erona)
[//]: # ([Spell][Mage] Fireball)
[//]: # ([Npc][Drop] Ghostclaw Lynx)
[//]: # ([Web] Armory doesnt work)
[//]: # (To find server revision type `.server info` command in the game chat.)

**Current behaviour**:

When a player uses Ice Block/Bubble to get out of the chains, **they do not despawn**.

**Expected behaviour**: 

When a player uses Ice Block/Bubble to get out of the chains, **they should despawn**.

**Source:** 

https://youtu.be/CI49jQMdaf0?t=146

https://youtu.be/JsSgkjO59gE?t=47

**Server Revision**: 2445

**Comment by Thugli** [comment]
I noticed this as well, here is a video of this taken from the beta in a Kara run 3 days ago: https://vimeo.com/306707330

**Comment by devo6969** [comment]
This is still happening on the PTR. Chains don't despawn once using an immunity. Should despawn.
Retail TBC (Pally bubble) - https://youtu.be/Pm7ITxo_r7c?t=34
Retail TBC (Mage block) - https://youtu.be/Pm7ITxo_r7c?t=203
PTR - https://www.youtube.com/watch?v=8SoibdkdXAk

**Comment by Wolffenstein** [comment]
Fixed in rev 3473.
