### ISSUE TITLE
[NPC][Dungeon][SHH][Spell] Grand Warlock Nethekurse - Void Zones

### ISSUE THREAD

**Issue by idsss** [Atlantiss/NetherwingBugtracker#3458]
**Current behaviour**: Grand Warlock Nethekurse (SHH) summons voids zones which currently deal no damage

**Expected behaviour**: should do 1000 dmg/sec on norm and 3500 dmg/sec on heroic

![unbenannt2](https://user-images.githubusercontent.com/43757915/50057512-a4d40e80-016b-11e9-823e-2ccb686b0661.jpg)

![unbenannt](https://user-images.githubusercontent.com/43757915/50057466-24ada900-016b-11e9-978d-3fc3a172cd7b.jpg)

[Wowhead](https://web.archive.org/web/20110927133656/http://www.wowhead.com:80/npc=16807/grand-warlock-nethekurse#comments)
[Wiki](http://wowwiki.wikia.com/wiki/Grand_Warlock_Nethekurse)
[Thottbot](https://web.archive.org/web/20130112222520/http://www.thottbot.com/npc=16807)
**Server Revision**: 2447

**Comment by Jseay1313** [comment]
+ still does not work 2462

**Comment by idsss** [comment]
rev 2468
