### ISSUE TITLE
Zul Marrosh Incorrect Name

### ISSUE THREAD

**Issue by theloa** [Atlantiss/NetherwingBugtracker#346]
[//]: # (Enclose links to things related to the bug using http://wowhead.com or any other TBC database.)
[//]: # (You can use screenshot ingame to visual the issue.)
[//]: # (Write your tickets according to the format:)
[//]: # ([Quest][Azuremyst Isle] Red Snapper - Very Tasty!)
[//]: # ([NPC] Magistrix Erona)
[//]: # ([Spell][Mage] Fireball)
[//]: # ([Npc][Drop] Ghostclaw Lynx)
[//]: # ([Web] Armory doesnt work)

**Description**: 
The mob Zul Marrosh has the incorrect name "Unknown".
**Current behaviour**:
Only an issue with the mob. Related quest text and item name ("Zul'Marosh's Head") are correct.
**Expected behaviour**: 
Should be named "Zul'Marrosh".
**Server Revision**:

**Comment by Evolvee** [comment]
![image](https://user-images.githubusercontent.com/1942409/45942444-ab2a7280-bfe2-11e8-97b8-20b9c6bd9333.png)

i see him just fine, try to clear cache and restart client
