### ISSUE TITLE
Libram of Souls Redeemed (item id:28592)

### ISSUE THREAD

**Issue by taurenrogue** [Atlantiss/NetherwingBugtracker#3460]
**Description**: 
Libram of Souls Redeemed (item id:28592) doesn't work for either holy or flash of light.

**Current behaviour**:
Does nothing.

**Expected behaviour**: 
Should give BH to HL/FoL

**Server Revision**: 
2451

**Comment by Tenoutoften** [comment]
This libram would give +96 bonus healing(+108 if you have improved HL & FH in holy tree) to flash & holy light even without the blessing:

https://www.wowhead.com/item=28592/libram-of-souls-redeemed#comments:id=68367

Though I don't recommend reintroducing bugs as was done in https://github.com/Atlantiss/NetherwingBugtracker/issues/2556.

**Comment by H4Xx0R-PC** [comment]
+1, please fix this
