### ISSUE TITLE
[item]Serpent-coil braid on use effect does not stack with other trinkets all the time

### ISSUE THREAD

**Issue by ircfelix** [Atlantiss/NetherwingBugtracker#3462]
**Description**: 
According to Elitistjerks comments, this item's spell damage increasing effect stacks together with on-use trinkets like Icon of the Silver Crescent.

**Current behaviour**:
Most of the time both trinkets can be activated together, but sometimes it simply does not work.
I use a macro like this to stack the two trinkets (Icon is slot 14):
> /use 14
/use mana emerald

**Expected behaviour**: 
They should always work together.

**Server Revision**: 
2451

**Comment by ircfelix** [comment]
video of the bug occurring
https://streamable.com/d1w7d

**Comment by tcberk12** [comment]
You have to activate Icon of the Silver Crescent (or whatever your other trinket is first). Using a mana gem before the other trinket is starting a 15 second internal CD on your other trinkets.

https://www.youtube.com/watch?v=pseDc_jri70&feature=youtu.be&t=23

^ shows a mage using Icon first, then mana gem, to properly stack the trinkets.

See https://github.com/netherspite/cc-buglist/issues/1040 - elitistjerks also cited on this report.

**Comment by tcberk12** [comment]
Tested it on NW: In line with my comment above, they stack if you use the other trinket first. If you use a mana gem first, your trinket wont be able to be used for 15 seconds (the duration of Serpent Coil Braids buff).

This is working as intended.

**Comment by ircfelix** [comment]
Requesting reopen.
In m macro, /use 14 (on use trinket) comes before /use mana emerald. There is even /cast icy veins between them and the bug still sometimes occurred. Maybe it has something to do with how spells are processed.

**Comment by tcberk12** [comment]
I tried it 5 times when leading with the mana gem: 100% failure rate on stacking.

I tried it 5 times when leading with the crescent: 100% success rate on stacking.

I'll keep trying to and post here again if it ever works out of line.

**Comment by killablink** [comment]
Was gonna report it but seems it was already done but yeah, as reported, using a Mana Gem while having Serpent-coil Braid shouldn't put your other trinket on CD (Icon in this case)

**Comment by ircfelix** [comment]
@Easyfraggy this trinket's effect still puts on use trinket on CD.

**Comment by Easyfraggy** [comment]
Not sure thats even server side. Wolf would have to pitch in.

**Comment by ircfelix** [comment]
Currently the fix to this problem is to use your trinket before the mana gem. Maybe, this way we can avoid the extra work of fixing this cooldown problem.

**Comment by Godmatik** [comment]
Rev 4017 - no longer an issue
Using mana gem first to proc Serpent-Coil Braid does not cause other trinkets to go on cooldown
