### ISSUE TITLE
[SSC][Ability][Graphic] Leeching throw 

### ISSUE THREAD

**Issue by Novat93** [Atlantiss/NetherwingBugtracker#3463]
[//]: # (Enclose links to things related to the bug using http://wowhead.com or any other TBC database.)
[//]: # (You can use screenshot ingame to visual the issue.)
[//]: # (Write your tickets according to the format:)
[//]: # ([Quest][Azuremyst Isle] Red Snapper - Very Tasty!)
[//]: # ([NPC] Magistrix Erona)
[//]: # ([Spell][Mage] Fireball)
[//]: # ([Npc][Drop] Ghostclaw Lynx)
[//]: # ([Web] Armory doesnt work)
[//]: # (To find server revision type `.server info` command in the game chat.)

**Description**: 
The ability Leeching throw currently has no graphic
Ability = 29436

**Current behaviour**:
The projectile appears as a white and blue checkered cube

**Expected behaviour**: 
Presumably, the correct graphic would be an arrow or a spear.

**Server Revision**: 
2451

Additional info: These boxes would be instantly familiar to anyone playing on a certain other server 🐷 

![bug1](https://user-images.githubusercontent.com/36829235/50059625-ac0a1500-0189-11e9-9510-3c2f10bd6cb6.PNG)

![bug2](https://user-images.githubusercontent.com/36829235/50059626-b0cec900-0189-11e9-9b6a-951f1ba4c1c9.PNG)

**Comment by WarriorTSW** [comment]
Not just Graphical. He also runs towards the target. 
https://youtu.be/EL8Ki16gsRE

**Comment by Brasso** [comment]
@WarriorTSW #3091

**Comment by SwiftieTBC** [comment]
https://youtu.be/4RrNvx66yok?t=141 is what the object should look like

**Comment by The14me** [comment]
Rev.3472 still an issue.

**Comment by Wolffenstein** [comment]
Looks fine to me.
