### ISSUE TITLE
Spitfire Totem can be interrupted with Concussion Blow

### ISSUE THREAD

**Issue by WarriorTSW** [Atlantiss/NetherwingBugtracker#3464]
[//]: # (Enclose links to things related to the bug using http://wowhead.com or any other TBC database.)
[//]: # (You can use screenshot ingame to visual the issue.)
[//]: # (Write your tickets according to the format:)
[//]: # ([Quest][Azuremyst Isle] Red Snapper - Very Tasty!)
[//]: # ([NPC] Magistrix Erona)
[//]: # ([Spell][Mage] Fireball)
[//]: # ([Npc][Drop] Ghostclaw Lynx)
[//]: # ([Web] Armory doesnt work)
[//]: # (To find server revision type `.server info` command in the game chat.)

**Description**: 
https://youtu.be/ollwscLemYs
Concussion Blow is interrupting Spitfire Totem's Cast
**Current behaviour**:

**Expected behaviour**: 
Cant be interrupted by anything
**Server Revision**: 
2451

**Comment by ircfelix** [comment]
The totems of the first shaman (the male draenei) moved when the shaman moved and were all stacked in one spot.

**Comment by WarriorTSW** [comment]
still can be interrupted by stun. Tested just now with intercept stun and concussion blow

**Comment by Manaci** [comment]
Fixed
