### ISSUE TITLE
[NPC] Deathforged Infernal - visible trigger [bad flag]

### ISSUE THREAD

**Issue by Firroth** [Atlantiss/NetherwingBugtracker#3467]
**Current behaviour**:
Normal player can see "trigger", -> bad flag set.

![screenshot_3](https://user-images.githubusercontent.com/43505196/50062882-cbb13580-01a9-11e9-8ed7-4ea447226918.png)

**Expected behaviour**: 
Shouldn't be visible by players, only by GM's I guess.

**Server Revision**: 
2151

**Comment by Tereneckla** [comment]
Duplicate of #2736
