### ISSUE TITLE
[NPC] Warchief Kargath Bladefist (Heroic)

### ISSUE THREAD

**Issue by ircfelix** [Atlantiss/NetherwingBugtracker#3468]
**Description**: 
Screenshot:
https://i.imgur.com/V2UkhsR.jpg

**Current behaviour**:
You can skip the 2nd boss, O'mrogg, in SHH heroic and directly go for Kargath Bladefist, the 2nd boss O'mrogg does aggro, but not run towards Warchief Kargath Bladefist (see chat window in screen shot). This can be abused to save some time during the TK heroic pre quest.

**Expected behaviour**: 
When engaging Warchief Kargath Bladefist, the 2nd boss O'mrogg should not only add, but also run towards the Warchief Kargath Bladefist position and engage the group.

**Server Revision**: 
2451

**Comment by Manaci** [comment]
Fixed
