### ISSUE TITLE
[Raid] [SSC] [Fathom-Guard Sharkkis]

### ISSUE THREAD

**Issue by Gedlund** [Atlantiss/NetherwingBugtracker#3469]
[//]: # (Enclose links to things related to the bug using http://wowhead.com or any other TBC database.)
[//]: # (You can use screenshot ingame to visual the issue.)
[//]: # (Write your tickets according to the format:)
[//]: # ([Quest][Azuremyst Isle] Red Snapper - Very Tasty!)
[//]: # ([NPC] Magistrix Erona)
[//]: # ([Spell][Mage] Fireball)
[//]: # ([Npc][Drop] Ghostclaw Lynx)
[//]: # ([Web] Armory doesnt work)
[//]: # (To find server revision type `.server info` command in the game chat.)

**Description**: 
Fathom-Guard Sharkkis (FGS) ability "Hurl Trident" makes FGS move toward a target before throwing his trident at them, making him run back and forth between said target and the tank. 

**Current behaviour**:
FGS runs back and forth trying to find a target for his Hurl Trident ability, im uncertain if this also is happening to his multi-shot or leeching mana ability.

**Expected behaviour**: 
FGS stands still but can find targets to attack anyway. 

https://www.youtube.com/watch?v=pub88sW4Jxs (FGS stands still until dead).

**Server Revision**:

**Comment by Brasso** [comment]
#3091 #3463 Duplicate

**Comment by The14me** [comment]
Duplicate
