### ISSUE TITLE
[Spell][Hunter] Concussive Shot 

### ISSUE THREAD

**Issue by Thugli** [Atlantiss/NetherwingBugtracker#347]
[//]: # (Enclose links to things related to the bug using http://wowhead.com or any other TBC database.)
[//]: # (You can use screenshot ingame to visual the issue.)
[//]: # (Write your tickets according to the format:)
[//]: # ([Quest][Azuremyst Isle] Red Snapper - Very Tasty!)
[//]: # ([NPC] Magistrix Erona)
[//]: # ([Spell][Mage] Fireball)
[//]: # ([Npc][Drop] Ghostclaw Lynx)
[//]: # ([Web] Armory doesnt work)

**Description**: 
Concussive shot occasionally won't go off, when this happens it doesn't go on cooldown, and I don't get any error message. I will be in the proper range to use it but nothing happens. I know there are other reports of issues regarding concussive shot, but I don't think any of them talk about the ability not even going off. With the other reported bug, it was actually going off and the target was receiving the debuff but the slow effect was not working. With the issue I am describing when I spam concussive shot nothing happens.

**Edit:** Though it has happened a few times in the past 2 hours. It happened twice on Luzran, the elite quest mob in ghostlands. Not sure if that was just chance, or related at all to that mob.

**Current behaviour**:
Sometimes concussive shot doesn't go off and nothing happens when I try to use it.

**Expected behaviour**: 
As long as I am in proper range, have enough mana etc... concussive shot should properly go off on the target.

**Server Revision**:

**Comment by Easyfraggy** [comment]
This happens when you move as it queues autoshot before concussive/sting etc, causing it to wait with firing untill you stand still to fire auto attack. Reopen if that isn't the case. Duplicate https://github.com/Atlantiss/NetherwingBugtracker/issues/135
