### ISSUE TITLE
[RAID] [SSC] [Fathom-Guard Tidalvess /  Fathom-Lord Karathress]

### ISSUE THREAD

**Issue by Gedlund** [Atlantiss/NetherwingBugtracker#3470]
[//]: # (Enclose links to things related to the bug using http://wowhead.com or any other TBC database.)
[//]: # (You can use screenshot ingame to visual the issue.)
[//]: # (Write your tickets according to the format:)
[//]: # ([Quest][Azuremyst Isle] Red Snapper - Very Tasty!)
[//]: # ([NPC] Magistrix Erona)
[//]: # ([Spell][Mage] Fireball)
[//]: # ([Npc][Drop] Ghostclaw Lynx)
[//]: # ([Web] Armory doesnt work)
[//]: # (To find server revision type `.server info` command in the game chat.)

**Description**: 
The three totems Spitfire Totem , Poison Cleansing Totem and Earthbind Totem sometimes move their position after being spawned. 

**Current behaviour**:
Spitfire Totem, Poison Cleansing Totem and Earthbind Totem from either Tidvaless or FLK sometimes move or change position when attacking a player.

**Expected behaviour**: 
Totems dont move. 

**Server Revision**:

**Comment by Brasso** [comment]
- Totems summoned by Fathom-Guard Tidalvess will no longer be able to move or attack and will now properly inherit totem behaviour - was fixed in 2366. This is still an issue?

**Comment by Tenoutoften** [comment]
This is not limited to these specific totems/NPC. https://www.youtube.com/watch?v=YRvnVrEF0Es&feature=youtu.be

**Comment by Wolffenstein** [comment]
Fixed in rev 2507.
