### ISSUE TITLE
[RAID] [SSC] [Spitfire Totem]

### ISSUE THREAD

**Issue by Gedlund** [Atlantiss/NetherwingBugtracker#3471]
[//]: # (Enclose links to things related to the bug using http://wowhead.com or any other TBC database.)
[//]: # (You can use screenshot ingame to visual the issue.)
[//]: # (Write your tickets according to the format:)
[//]: # ([Quest][Azuremyst Isle] Red Snapper - Very Tasty!)
[//]: # ([NPC] Magistrix Erona)
[//]: # ([Spell][Mage] Fireball)
[//]: # ([Npc][Drop] Ghostclaw Lynx)
[//]: # ([Web] Armory doesnt work)
[//]: # (To find server revision type `.server info` command in the game chat.)

**Description**: 
Spitfire totem is immune to priests mind-flay ability (maybe it has something to do with mind-flay applying a slow-effect)

**Current behaviour**:
Priests can't use their mind flay ability on Spitfire totems due to immunity.

**Expected behaviour**: 
Only the slow is "Removed" but mind-flay can still be used to damage the totem.

**Server Revision**:

**Comment by Doppelmoral** [comment]
Can you do more testing on that ? There's a popular tbc bug on private servers that make the spell resist as whole if the slow aspect of the spell was resisted.

Example: Hunters with https://classic.wowhead.com/spell=24283/surefooted talented got basically a 15% resist chance against mage's frostbolt in PvP. There should be two rolls, on for the spell to do dmg and for the spell to apply slow/snare/root etc.

**Comment by Easyfraggy** [comment]
I think this might be a general issue with channeled spells? I have little to no experience from retail with using channeled spells on totems though - need some proof of this.

**Comment by Wolffenstein** [comment]
Fixed in rev 3079.
