### ISSUE TITLE
[Spell][Hunter]Feign Death doesn't break on eating/drinking

### ISSUE THREAD

**Issue by Feelingbadinc** [Atlantiss/NetherwingBugtracker#3475]
[//]: # (Enclose links to things related to the bug using http://wowhead.com or any other TBC database.)
[//]: # (You can use screenshot ingame to visual the issue.)
[//]: # (Write your tickets according to the format:)
[//]: # ([Quest][Azuremyst Isle] Red Snapper - Very Tasty!)
[//]: # ([NPC] Magistrix Erona)
[//]: # ([Spell][Mage] Fireball)
[//]: # ([Npc][Drop] Ghostclaw Lynx)
[//]: # ([Web] Armory doesnt work)
[//]: # (To find server revision type `.server info` command in the game chat.)

**Description**: If you Feigh Death and start eating or drinking, Feign Death doesn't break

**Current behaviour**: Feign Death doesn't break while eating/drinking (example image: used Mage food)
![screenshot_265](https://user-images.githubusercontent.com/45940730/50088778-44dd7680-0204-11e9-8b6d-edec9eecec68.png)

**Expected behaviour**: Feign Death should break once you start eating/drinking

**Server Revision**: 2452

**Comment by Tenoutoften** [comment]
Another issue related to eating & drinking, effects are removed when Entangling Roots expire from mobs : https://github.com/Atlantiss/NetherwingBugtracker/issues/843

**Comment by Tereneckla** [comment]
fixed as of rev 3236
