### ISSUE TITLE
[Spell][Mage] Blizzard/coc/frostbolt slows overlap

### ISSUE THREAD

**Issue by rikhx** [Atlantiss/NetherwingBugtracker#3476]
[//]: # (Enclose links to things related to the bug using http://wowhead.com or any other TBC database.)
[//]: # (You can use screenshot ingame to visual the issue.)
[//]: # (Write your tickets according to the format:)
[//]: # ([Quest][Azuremyst Isle] Red Snapper - Very Tasty!)
[//]: # ([NPC] Magistrix Erona)
[//]: # ([Spell][Mage] Fireball)
[//]: # ([Npc][Drop] Ghostclaw Lynx)
[//]: # ([Web] Armory doesnt work)
[//]: # (To find server revision type `.server info` command in the game chat.)

**Description**: Blizzard/CoC/Frostbolt should never be able to be applied to a target at the same time.

**Current behaviour**: Right now you can apply blizzard/coc/frostbolt and all 3 slows will stay as debuffs on the target, the strongest slow does not overwrite and remove the lesser slows.

Works like this atm https://imgur.com/a/4dcaLfb

**Expected behaviour**: The strongest slow should overwrite any existing slow aka a cone of cold should overwrite and remove the frostbolt slow, and the other way around frostbolt slow should not be applied to a target that is slowed by cone of cold already. 

Keep in mind the Ice armor debuff should never get removed by a stronger slow since it's an -atkspeed debuff aswell, so it should coexist with the strongest slow.

Proof: https://youtu.be/-J55f0puu9A?t=295 - https://youtu.be/-J55f0puu9A?t=248 - https://youtu.be/-J55f0puu9A?t=996 (Ice armor dealio)

**Server Revision**: 2451

**Comment by Brasso** [comment]
https://www.youtube.com/watch?v=O-W7hCw-Prg 

The strongest slow takes precedence which is good. But being able to chain weaker slow effects on top to permanently slow the target has pretty bad implications for pvp and should be fixed.

**Comment by Tereneckla** [comment]
Fixed
