### ISSUE TITLE
[NPC] Surveyor Candress npcid=16522

### ISSUE THREAD

**Issue by Dract** [Atlantiss/NetherwingBugtracker#3478]
**Description**: 
Surveyor Candress casts her fireball much too frequently making it quite impractical to solo her.

**Current behaviour**:
Will spam fireballs for 28-30 damage untill she is oom.

**Expected behaviour**: 
Will cast fireballs a little less frequently.  According to this wowhead comment from https://www.wowhead.com/quest=9311/blood-elf-spy she is very easy to solo.

By Conure (762 –  2·9)  on 2007/04/04 (Patch 2.0.12) |   |  
Surveyor Candress is very easy to kill/solo and is found at the top of the blood elf encampment at Shadow Ridge. When you engage with her, one other Blood Elf Scout (http://www.wowhead.com/?npc=16521) will attack you as well. I suggest putting Gift of the Naaru on you just to negate the slight chance that you would die.

**Server Revision**:

**Comment by Evolvee** [comment]
need evidence that she should not cast it frequently

**Comment by Tereneckla** [comment]
Oldest video I could find.
https://youtu.be/-CqiRz4i-lo?t=544

**Comment by Evolvee** [comment]
earth shock

**Comment by Tereneckla** [comment]
Earth Shock in wotlk does not interrupt anymore.
They gave it an attack speed slow and introduced wind shear for interrupts
