### ISSUE TITLE
[NPC][The Arcatraz (H)] Wrath-Scryer Soccothrates aggro resets inconsistently

### ISSUE THREAD

**Issue by letterix** [Atlantiss/NetherwingBugtracker#3479]
[//]: # (Enclose links to things related to the bug using http://wowhead.com or any other TBC database.)
[//]: # (You can use screenshot ingame to visual the issue.)
[//]: # (Write your tickets according to the format:)
[//]: # ([Quest][Azuremyst Isle] Red Snapper - Very Tasty!)
[//]: # ([NPC] Magistrix Erona)
[//]: # ([Spell][Mage] Fireball)
[//]: # ([Npc][Drop] Ghostclaw Lynx)
[//]: # ([Web] Armory doesnt work)
[//]: # (To find server revision type `.server info` command in the game chat.)

**Description**: 
When Wrath-Scryer Soccothrates charges, he should aggro reset (which he does) but at randomly he locks onto players, whether they have done anything at all. We saw players who had stood still for bout 30 seconds get targeted, pets that hadn't attacked for the last few minutes etc.

**Current behaviour**:
Acts as if the aggro reset can be resisted by players and their pets

**Expected behaviour**: 
Should always aggro reset and start with a fresh aggro table after each charge
[Retail video](https://www.youtube.com/watch?v=c9svgCKd6NM)

**Server Revision**: 
2452

**Comment by Wolffenstein** [comment]
Fixed in rev 2454.
