### ISSUE TITLE
Darkwraith#15657 wrong Enrage spell 

### ISSUE THREAD

**Issue by Tenoutoften** [Atlantiss/NetherwingBugtracker#348]
**Description**: 

_Darkwraith_(NPC#15657, https://db.excalibur.ws/?npc=15657) uses wrong enrage spell

**Current behaviour**:

_Darkwraith_(NPC#15657, https://db.excalibur.ws/?npc=15657) uses wrong enrage spell giving +30% attack speed & +9 attack damage. Should be using _Enrage#8599_ (https://db.excalibur.ws/?npc=15657#abilities)

https://i.gyazo.com/f85f95456d3b20b6fd1429c74535c775.png

**Expected behaviour**: 

_Darkwraith#15657_ should use _Enrage#8599_.
https://i.gyazo.com/15476d966a7950721d5008f72e200888.png

**Server Revision**: 

2040

**Comment by Evolvee** [comment]
it currently uses 8599 enrage, its just scaling

![image](https://user-images.githubusercontent.com/1942409/45942348-52f37080-bfe2-11e8-93d5-ba9a7708fec8.png)
(check BasePoints)
