### ISSUE TITLE
Teldrassil - Dynamic Respawn Game Objects/NPC's

### ISSUE THREAD

**Issue by SwiftieTBC** [Atlantiss/NetherwingBugtracker#3480]
The re spawn rate on these items seems to long for a starter zone
Game object -152094 - Hyacinth Mushroom
Game object -152095 - Moonpetal Lily
Game object - 4608 - Timberling Sprout

NPC's for the quest Ferocitas the Dream Eater - Q ID 2459
Only the main NPC Ferocitas the Dream Eater (ID 7234) has increase respawn, the mystics (ID 7235) are also part of the q and don't dynamically re-spawn.

**Comment by Wolffenstein** [comment]
@aresbrutus

**Comment by aresbrutus** [comment]
All of those are in the dynamic spawn system. Perhaps objects should have a higher refill rate however.
