### ISSUE TITLE
[NPC] Fel Overseer in Shadow Labyrinth should not keep hitting the tank after he is feared.

### ISSUE THREAD

**Issue by 5f3759** [Atlantiss/NetherwingBugtracker#3481]
**Current behaviour**: The Fel Overseer keeps hitting the tank even when he's feared. Smaily can confirm.

**Expected behaviour**: The Fel Overseer should behave as if the main target was gouged or similar and switch to the highest non-feared target.
https://www.youtube.com/watch?v=d7rzDpVEgRM&t=210

**Server Revision**: 2452

**Comment by Evolvee** [comment]
his targets gets stunned, not feared

**Comment by letterix** [comment]
@Evolvee Should still go for the second highest threat player.

Check this [comment](https://www.wowhead.com/npc=18796/fel-overseer#comments:id=83733) on wowhead from 2007

"
HEROIC
Ignoring the massive damage they can do, you can simply have one of your ranged DPS be the second highest in threat and kite him until the fear wears off the tank (I did this as a mage, blink helps but you can probably manage without it).

I'm not sure if the same applies to regular SL.
"

**Comment by 5f3759** [comment]
@Evolvee Check the video, the mob changes target to someone that is not feared.

**Comment by Tenoutoften** [comment]
https://www.wowhead.com/npc=18796/fel-overseer#comments:id=66691
![](https://i.gyazo.com/bc46e813ec411a6d6d79fcfc427852a7.png)

**Comment by The14me** [comment]
rev.3472 ''While I was soloing Slabs I noticed these guys don't seem to fear when you are by yourself'' is still bugged. If u are solo u get feared.

**Comment by Wolffenstein** [comment]
Fixed in rev 3477.
