### ISSUE TITLE
[Shadowlabs HC]Intervene and Charge bug

### ISSUE THREAD

**Issue by Fenvarien1** [Atlantiss/NetherwingBugtracker#3483]
**Description**: 
- During the 2nd boss my intervene started to bug and one charge on 3rd boss.
- On our way to the first boss and the complete grind towards the 2nd i got 0 problems with intervene.

### **Current behaviour**:
i cast intervene on a party member and run away like i got a deathcoil from a WL(random direction 20y) after i reached my party member. started to happen during the 2nd Boss.

> during 2nd boss fight:
> - [intervene on zeeya](https://clips.twitch.tv/AbstruseExquisiteLaptop4Head) running towards the stairs after reaching zeeya
> - [intervene on hunter](https://clips.twitch.tv/SweetTrappedButterChocolateRain) running randomly away after reaching the hunter

> trash:
> - [intervene on zeeya](https://clips.twitch.tv/CorrectRamshackleKoupreyEagleEye) running away randomly after reaching zeeya
> - [intervene on hunter](https://clips.twitch.tv/StrangeBitterCrab4Head) running away randomly after reaching the hunter
> - [intervene TEST on zeeya](https://clips.twitch.tv/ComfortableDignifiedRuffPanicBasket) it worked without problems even adding the skeletons? maybe he got no threat from target? _the port-lookalike movement is due to a jump right after intervene._

> 3rd Boss:
> - [charge on boss](https://clips.twitch.tv/ExuberantUgliestBarracudaCoolStoryBro) running randomly away after reaching the Boss

**Server Revision**: 
2452

**Comment by Wolffenstein** [comment]
Fixed in rev 2457.
