### ISSUE TITLE
Seed of Corruption visual effects v. 2.0.

### ISSUE THREAD

**Issue by Neophrone** [Atlantiss/NetherwingBugtracker#3484]
[//]: # (Enclose links to things related to the bug using http://wowhead.com or any other TBC database.)
[//]: # (You can use screenshot ingame to visual the issue.)
[//]: # (Write your tickets according to the format:)
[//]: # ([Quest][Azuremyst Isle] Red Snapper - Very Tasty!)
[//]: # ([NPC] Magistrix Erona)
[//]: # ([Spell][Mage] Fireball)
[//]: # ([Npc][Drop] Ghostclaw Lynx)
[//]: # ([Web] Armory doesnt work)
[//]: # (To find server revision type `.server info` command in the game chat.)

**Description**: 
After fixing this issue: https://github.com/Atlantiss/NetherwingBugtracker/issues/3447 visual explosion now explode around the warlock instead of target u casted Seed of Corruption on.
**Current behaviour**:
Visual explosion appear on warlock.
**Expected behaviour**: 
Visual explosion should explode on target u casted Seed of Corruption on.
**Server Revision**: 2457.

**Comment by Wolffenstein** [comment]
Oops, sorry. Will be fixed in rev 2459.
