### ISSUE TITLE
[Dungeon] Shadow Labs - Missing Soul Devices

### ISSUE THREAD

**Issue by towneh** [Atlantiss/NetherwingBugtracker#3485]
**Description**: 
Missing Soul Devices, interactable (with quest) or non interactable objects should be present in the instance.

**Current behaviour**:
Not there

**Expected behaviour**: 
![image](https://user-images.githubusercontent.com/25694892/50114838-86d6de80-023d-11e9-922c-a176bb3504da.png)
https://www.youtube.com/watch?v=0e1ImLdGyJg
http://wowwiki.wikia.com/wiki/Quest:The_Soul_Devices?oldid=782109
Soul devices should be found within the tents of blackheart the inciter's room, in front of grandmaster vorpil and within the tents leading up to murmur.

**Server Revision**: 
2457

**Comment by Evolvee** [comment]
werent u on hero?

**Comment by towneh** [comment]
Yes this was on heroic, you can see evidence of them being present in Murmur's room here on this video in heroic mode:
https://youtu.be/kH64WTxytQ8?t=355

**Comment by towneh** [comment]
Also https://www.youtube.com/watch?v=1zn538fRQ98 shows two of these before Vorpil

**Comment by towneh** [comment]
Further retail video of entire solo run through to assist with placement of soul devices https://www.youtube.com/watch?v=LujKi3oJAq0

**Comment by Shanghi** [comment]
This should be fixed in revision 2462.
