### ISSUE TITLE
[Dungeon][NPC] Shadow Labs - Missing Skeleton Spawns

### ISSUE THREAD

**Issue by towneh** [Atlantiss/NetherwingBugtracker#3487]
**Description**: 
Missing non elite skeleton spawns from bones

**Current behaviour**:
https://clips.twitch.tv/CrowdedSilkyMallardCclamChamp

**Expected behaviour**: 
Single skeleton should spawn from skeleton on floor

**Server Revision**: 
2457

**Comment by Tereneckla** [comment]
Fixed

**Comment by Easyfraggy** [comment]
Just to clarify - they were always there just they are pooled spawns so not all of them are up in every dungeon. It's random which ones are spawned. The big white skeleton on the video is just a random doodad - not one of the skellies playing dead - they look different.

So this report was invalid.
