### ISSUE TITLE
[Dungeon][NPC] Shadow Labs - Weird NPC Pathing Before Vorpil

### ISSUE THREAD

**Issue by towneh** [Atlantiss/NetherwingBugtracker#3488]
**Description**: 
Pulling NPCs back to LoS position, the melee mobs were unable to reach the tank until he moved in to the room.
Additionally the last pack in the room isn't walking around Vorpil in a circle around the boss, they are just standing still in the top right corner.

**Current behaviour**:
https://clips.twitch.tv/GleamingNaivePancakeHeyGirl - NPC pathing to tank
https://clips.twitch.tv/MoldySuaveStarJonCarnage - Npc pack not walking around Vorpil

**Expected behaviour**: 
Melee mobs should be able to path to the tank
NPC Pack should be walking around Vorpil

**Server Revision**: 
2457

**Comment by towneh** [comment]
Please see https://youtu.be/LujKi3oJAq0?t=460 for evidence of correct placement of trash packs, you can see the pathing pack behind Vorpil as the player approaches the boss.

**Comment by Tereneckla** [comment]
Fixed
