### ISSUE TITLE
[Dungeon][NPC] Shadow Labs - Grandmaster Vorpil Abilities

### ISSUE THREAD

**Issue by towneh** [Atlantiss/NetherwingBugtracker#3489]
**Description**: 
* Vorpil doesn't cast rain of fire during the encounter
* Banished players are correctly immune from teleport but appear to receive full aggro from Vorpil, even whilst banished. This bug appears to prevent Vorpil from casting RoF.
* Voidwalkers do not leave a blue spell effect on the ground from where they spawn

**Current behaviour**:
https://www.twitch.tv/videos/350475563?t=23m32s

**Expected behaviour**: 
* Vorpil should follow up teleport with a rain of fire aoe
* Druid is banished whilst teleport occurs in example video here https://youtu.be/v-Z7XBj-J5k?t=76 and vorpil never switches target from the warrior tank, Vorpil should ignore the banished target and cast RoF correctly.
* Voidwalkers should leave a blue spell animation on the spawn location
https://www.youtube.com/watch?v=1zn538fRQ98

**Server Revision**: 
2457

**Comment by Anselm123** [comment]
he teleported for us, can't remember if he did ROF though

**Comment by Peglaa** [comment]
Yup, he teleported for my group and he used ROF.

**Comment by Phibs77** [comment]
https://www.twitch.tv/videos/350421077?t=00h55m50s
Worked fine for us.

**Comment by lynxzor** [comment]
> https://www.twitch.tv/videos/350421077?t=00h55m50s
> Worked fine for us, except spawn animations.

Same, cast both fine.

**Comment by Drayo** [comment]
Well, he linked a clip of their run where is obviously did not work, lol.

Banish seems to be a good suspect here, it also seems like the teleport resets threat but not for the banished player.

https://www.youtube.com/watch?v=gTtQzX5qFXQ 

In this video there seems to be no threat reset.

**Comment by towneh** [comment]
Yep sorry I missed that, so we can confirm there is a teleport, but banish seems to be a bit funky with the aggro handling and he was attacking me even whilst I was still banished :D

**Comment by Fenvarien1** [comment]
was with @Peglaa and the teleport worked and RoF - i guess we were teleported twice the complete 2min fight https://www.twitch.tv/videos/350421077?t=55m43s

**Comment by Fenvarien1** [comment]
@towneh @Wolffenstein you can reproduce the bug by banish a target close to the teleport(like towneh video) and the boss is focusing the banish after teleport. he starts moving instead of casting.

**Comment by towneh** [comment]
Updated original post with correct experience of mechanics and provided further video research to banish/teleport behaviour

**Comment by Tereneckla** [comment]
Fixed
