### ISSUE TITLE
Enraged Wraith#17086 uses wrong Enrage spell

### ISSUE THREAD

**Issue by Tenoutoften** [Atlantiss/NetherwingBugtracker#349]
**Description**: 

Enraged Wraith#17086(https://db.excalibur.ws/?npc=17086) uses wrong enrage spell giving 10 physical damage & 30% attack speed, should use Enrage#8599(https://db.excalibur.ws/?npc=17086#abilities) giving 1 physical damage & 30% attack speed.

**Current behaviour**:

Enraged Wraith#17086 uses wrong enrage spell giving 10 physical damage & 30% attack speed.
https://i.gyazo.com/e339950e6b4034e64aa416458473c236.png

**Expected behaviour**: 

Enraged Wraith#17086 should use Enrage#8599(https://db.excalibur.ws/?npc=17086#abilities)
https://i.gyazo.com/15476d966a7950721d5008f72e200888.png

**Server Revision**: 

2040

**Comment by Evolvee** [comment]
it currently uses 8599

the spell damage bonus is scaling based on a level of the NPC
