### ISSUE TITLE
[Dungeon][Warrior][Spell] Shadow Labs - Warrior Charge/Intercept Pathing Bug

### ISSUE THREAD

**Issue by towneh** [Atlantiss/NetherwingBugtracker#3490]
**Description**: 
Attempting to Charge or Intercept NPCs in the instance after Inciter and up to Murmur creatures a strange issue where the warrior rushes towards the target and then walks away

**Current behaviour**:
https://clips.twitch.tv/BraveBadCrabFailFish

**Expected behaviour**: 
Warrior should charge/intercept normally 

**Server Revision**: 
2457

**Comment by Wolffenstein** [comment]
Rev 2457
