### ISSUE TITLE
[Dungeon][NPC] Shadow Labs - Murmur's Touch not working as expected

### ISSUE THREAD

**Issue by towneh** [Atlantiss/NetherwingBugtracker#3491]
**Description**: 
Murmur's Touch should knock a player up in to the air

**Current behaviour**:
The player receives the debuff but does not take the knock up effect
https://www.twitch.tv/videos/350475563?t=37m11s

**Expected behaviour**: 
https://youtu.be/vUxnL93ZDpw?t=37 Tank gets knocked up in to the air

**Server Revision**: 
2457

**Comment by rjorgensen** [comment]
Thundering Storm — Check range too big. Check referred video for comparing.
Murmur's Touch - No knock up when the timer runs out.
Incorrect timers on both Murmur's Touch and Sonic Boom (they are not cast frequently enough)

Video Reference: https://www.youtube.com/watch?v=G3pVbyU_jLo 

Side note the linked video is on normal xD (not your fault, I guess clickbait was even a thing 11 years ago)

**Comment by devo6969** [comment]
Can confirm there is no knock up and appears the 1st/2nd Murmur's Touch doesn't like to drag people in.
Retail TBC - https://www.youtube.com/watch?v=wCiab-vk8tg
PTR Murmur H - https://www.youtube.com/watch?v=vo2HQ6WKGjE
https://wow.gamepedia.com/Murmur
Murmur's Touch
"The ranged classes will be primarily concerned with Murmur's Touch. Everyone needs to watch for this debuff and run away from his teammates to avoid damaging and silencing them. Spells such as Divine Shield will prevent damage from occurring to the person with the debuff, but the AoE effect still occurs. A common tactic to avoid the fall damage that results from being launched in the air is for the player with this debuff to run into the tent situated in the area."

**Comment by Godmatik** [comment]
Still bugged, should knock you in the air, but it does not.

**Comment by Wolffenstein** [comment]
Fixed in rev 3556.
