### ISSUE TITLE
[Dungeon][Chests] Shadow Labs - Missing Chests from Blackheart's Room

### ISSUE THREAD

**Issue by towneh** [Atlantiss/NetherwingBugtracker#3492]
**Description**: 
Missing chests from the tents in Blackheart the Inciter's trash area.

**Current behaviour**:
https://www.twitch.tv/videos/350475563?t=09m04s and onward

**Expected behaviour**: 
https://www.youtube.com/watch?v=K-t1TlwsRqI

**Server Revision**: 
2457

**Comment by Manaci** [comment]
Intentionally removed
