### ISSUE TITLE
[Combat] Crowd Controlled targets keep player in combat until target has left the agro radius

### ISSUE THREAD

**Issue by Jseay1313** [Atlantiss/NetherwingBugtracker#3493]
**Description**: NPCs remain in combat with you when crowd controlled until the mob reaches the specific range to drop combat, assuming only the 1 player is engaged the mob should disengage and the player should leave combat after a specific distance

**Current behaviour**: Sheep a mob and run away, the player is locked in combat until polymorph fades on the NPC and then it runs the required distance without being attacked and leashes, leaving players locked in combat for 50+ seconds despite being hundreds of yards away.

**Expected behaviour**: At a certain distance from the player, the NPC should reset while rooted, feared, sheeped, trapped, sapped.

https://www.youtube.com/watch?v=zYJcX8IyKx4&feature=youtu.be

**Server Revision**: 2459

**Comment by Jseay1313** [comment]
Didn't see that, just wanted to add/note that it also works for other crowd controls like freezing trap/root etc.

**Comment by The14me** [comment]
rev. 3472 not an issue anymore since https://github.com/Atlantiss/NetherwingBugtracker/issues/2356get fixed.
Can be closed.
