### ISSUE TITLE
[Quest] The Codex of Blood - Shadow Labs

### ISSUE THREAD

**Issue by lynxzor** [Atlantiss/NetherwingBugtracker#3494]
**Description**: No codex to be found to complete quest

**Current behaviour**: No spawn
![wowscrnshot_121718_222637](https://user-images.githubusercontent.com/795881/50119702-6d3c9380-024b-11e9-90b8-b0e59ab9f10f.jpg)

**Expected behaviour**: 
![image](https://user-images.githubusercontent.com/795881/50119680-5dbd4a80-024b-11e9-9cd5-05c3385a202f.png)

**Server Revision**: 2457

**Comment by towneh** [comment]
You can see the book in https://www.youtube.com/watch?v=1zn538fRQ98

**Comment by Shanghi** [comment]
This should be fixed in revision 2462.
