### ISSUE TITLE
[Dungeon] [Shadow Labs] Murmur

### ISSUE THREAD

**Issue by Kinson72** [Atlantiss/NetherwingBugtracker#3495]
I was running this on my warlock and during the 2nd half of the fight with murmur, I had aggro and maintained it until he was dead.  I was about 15-20 yards from his con circle and I don't believe he used any type of penalty ability because of range.

**Comment by Drayo** [comment]
Second half? Murmur does not have different phases though? It sounds like he simply did nothing after you pulled aggro?

Anyway, Murmur should work like Lurker, he should only consider threat in melee range.
He will hit the entity with the highest threat that he can reach, it can be a Player (Tank or Melee) or a Shadowfiend for example, it does not matter. 
Ranged DPS should not be able to pull aggro on this fight, he should only attack them according to the threat list if they go into melee.

This means he should only cast [Resonance](https://www.wowhead.com/spell=33657/resonance) when no one is in melee range, but as soon as ANYONE is in melee range he should simply hit that target.

**Comment by Kinson72** [comment]
He starts with like 30% right?  I mean around 20% he had me targeted until dead.  I don't think he switched to anyone else, but we had the tank and I believe a rogue in melee range.

**Comment by Kinson72** [comment]
Also, there was damage to other people at this time.  I am not sure if it was all just coincidental aoe.

**Comment by Tereneckla** [comment]
Fixed
