### ISSUE TITLE
[Quest][Shadowmoon Valley] Besieged

### ISSUE THREAD

**Issue by Ceago** [Atlantiss/NetherwingBugtracker#3496]
**Description**:   Shadowmoon scouts will not attack nearby infernal attackers if the player starts attacking them first.

**Current behaviour**: https://streamable.com/jrdi1  Scouts do not attack.

**Expected behaviour**:  Scouts should assist player even if the player attacks first.

**Server Revision**: 2457

**Comment by Tereneckla** [comment]
https://youtu.be/Rt4dWI7nyFo?t=8
They should be attacking the infernal the second it spawns
Same issue with the Wildhammer Defenders (21736) at alliance base

**Comment by The14me** [comment]
rev.3472.still an issue.If u pull the infernal first, scouts don't attack it.

**Comment by Wolffenstein** [comment]
Fixed in rev 3675.
