### ISSUE TITLE
[Dungeon] [Shadow Labs] patrol not moving at Grandmaster Vorpil

### ISSUE THREAD

**Issue by Dadeerh** [Atlantiss/NetherwingBugtracker#3497]
[//]: # (Enclose links to things related to the bug using http://wowhead.com or any other TBC database.)
[//]: # (You can use screenshot ingame to visual the issue.)
[//]: # (Write your tickets according to the format:)
[//]: # ([Quest][Azuremyst Isle] Red Snapper - Very Tasty!)
[//]: # ([NPC] Magistrix Erona)
[//]: # ([Spell][Mage] Fireball)
[//]: # ([Npc][Drop] Ghostclaw Lynx)
[//]: # ([Web] Armory doesnt work)
[//]: # (To find server revision type `.server info` command in the game chat.)

**Description**: 
There is a patrol moving around the boss

**Current behaviour**:
They are standing still to the right

**Expected behaviour**: 
They should walk around (see picture)
![billede](https://user-images.githubusercontent.com/21084363/50126289-8efa4280-026c-11e9-81c5-20e26e69d4db.png)

**Server Revision**: 
2457

**Comment by towneh** [comment]
Yep same as https://github.com/Atlantiss/NetherwingBugtracker/issues/3488

**Comment by The14me** [comment]
Need some retail proof if possible.

**Comment by Drayo** [comment]
**https://youtu.be/3zAyyNW_ULk?t=288** 

They walk around the boss counter clockwise and kneel where they are standing on NW right now and in 3 other positions, they should be rather easy to see/guess from the two videos I posted.

**Comment by Tereneckla** [comment]
Fixed
