### ISSUE TITLE
[Dungeon] [Shadow Labs] Grandmaster Vorpil instant death of some players after teleport

### ISSUE THREAD

**Issue by Dadeerh** [Atlantiss/NetherwingBugtracker#3498]
[//]: # (Enclose links to things related to the bug using http://wowhead.com or any other TBC database.)
[//]: # (You can use screenshot ingame to visual the issue.)
[//]: # (Write your tickets according to the format:)
[//]: # ([Quest][Azuremyst Isle] Red Snapper - Very Tasty!)
[//]: # ([NPC] Magistrix Erona)
[//]: # ([Spell][Mage] Fireball)
[//]: # ([Npc][Drop] Ghostclaw Lynx)
[//]: # ([Web] Armory doesnt work)
[//]: # (To find server revision type `.server info` command in the game chat.)

**Description**: 
When he did the teleport, 3 of us just died. Combat log showed 3 times rain of fire (which shouldn't have killed the tank at least), even though we only stood there for a millisecond before dying. It worked as intended the second time, it was only that one time it happened..
![billede](https://user-images.githubusercontent.com/21084363/50126778-9b7f9a80-026e-11e9-8046-1877ff5fca3c.png)

**Current behaviour**:

**Expected behaviour**: 

**Server Revision**: 
2357

**Comment by Tereneckla** [comment]
Fixed
