### ISSUE TITLE
[Event][Stranglethorn Vale] Gurubashi Arena has stopped working

### ISSUE THREAD

**Issue by Brasso** [Atlantiss/NetherwingBugtracker#3499]
[//]: # (Enclose links to things related to the bug using http://wowhead.com or any other TBC database.)
[//]: # (You can use screenshot ingame to visual the issue.)
[//]: # (Write your tickets according to the format:)
[//]: # ([Quest][Azuremyst Isle] Red Snapper - Very Tasty!)
[//]: # ([NPC] Magistrix Erona)
[//]: # ([Spell][Mage] Fireball)
[//]: # ([Npc][Drop] Ghostclaw Lynx)
[//]: # ([Web] Armory doesnt work)
[//]: # (To find server revision type `.server info` command in the game chat.)

**Current behaviour**:
The event isn't triggering anymore. Time in bottom right corner.

![wowscrnshot_121818_030031](https://user-images.githubusercontent.com/44345420/50127518-b56eac80-0271-11e9-853a-6e32761cc62b.jpg)

![wowscrnshot_121818_030455](https://user-images.githubusercontent.com/44345420/50127532-cc150380-0271-11e9-9ddb-2bf8af52b7f4.jpg)

**Expected behaviour**: 
Event should trigger every 3 hours.
**Server Revision**: 
2457

**Comment by Tereneckla** [comment]
Old report, it works now
