### ISSUE TITLE
[NPC Pathing][Silvermoon City]

### ISSUE THREAD

**Issue by Thugli** [Atlantiss/NetherwingBugtracker#350]
[//]: # (Enclose links to things related to the bug using http://wowhead.com or any other TBC database.)
[//]: # (You can use screenshot ingame to visual the issue.)
[//]: # (Write your tickets according to the format:)
[//]: # ([Quest][Azuremyst Isle] Red Snapper - Very Tasty!)
[//]: # ([NPC] Magistrix Erona)
[//]: # ([Spell][Mage] Fireball)
[//]: # ([Npc][Drop] Ghostclaw Lynx)
[//]: # ([Web] Armory doesnt work)

**Description**: 
A group of npc's seem to occasionally stop very briefly before moving again while patting north through the royal exchange in Silvermoon City. Before they got to the roundabout between farstrider's square and the royale exchange they stopped for a little while (Which is probably working as intended) and then they continued up the stairs where the same issue occurred.

**Current behaviour**:
A video of the bugged behaviour can be seen here:
https://clips.twitch.tv/SquareFilthyWalletHassanChop

**Expected behaviour**: 

This group of npc's should walk fluidly without these very brief stutters.

**Server Revision**:

**Comment by Evolvee** [comment]
removed wp delay since no response from @Wolffenstein in rev `xdd`

**Comment by Evolvee** [comment]
just scuffed formation movement

**Comment by Evolvee** [comment]
removed wp delay since no response from @Wolffenstein in rev `xdd`

**Comment by Wolffenstein** [comment]
Delay is intentional, I removed the patch.

**Comment by Evolvee** [comment]
even at the very beggining? seems useless since there is no event or anyting
