### ISSUE TITLE
Mage Talent Arcane Concentration and AoE spells

### ISSUE THREAD

**Issue by Lacheezy** [Atlantiss/NetherwingBugtracker#3500]
**Description**:  The proc chance of Arcane Concentration on AoE spells seems abnormally low,q like it only procs on the first instance of channeled AoE spells.  I casted blizzard spell hitting 4 target dummies with each tick and only received 5 procs of Arcane Concentration all of which only happened on the first instance of damage for the spell.  Tested for about 15 mintues.  (This could be related to many other bugs...the frozen shadoweave set bonus heals you for 2% of frost damage done but will only heal you on the first tick of blizzard and not any subsequent ticks.  Made gear to test as most of the time multiple mechanics like this do not work with all ticks of blizzard just the first one.)

**Current behaviour**: Arcane concentration 10% in the tooltip seems higher than actual rate of generation.  Also, the buff does not seem to proc on any instance of damage after the first tick in the channel.

**Expected behaviour**:  Arcane concentration should proc on each INSTANCE of damage in the channel for example Blizzard has 8 ticks, so 8 chances to get a clearcast...not just 1 chance on the first instance of damage.  

**Server Revision**: 2457

**Comment by killablink** [comment]
No it's only on spell cast. It's working fine.

**Comment by Lacheezy** [comment]
If this were the case, then wouldn't arcane missiles NOT generate clear casting procs on damage after the spellcast? It can and does give procs on any instance of damage.  Tested that to make sure.

**Comment by killablink** [comment]
Yes, that is currently bugged. AM should proc clearcast only on cast, not by missile.

**Comment by Lacheezy** [comment]
I don't have any proof yet of what I'm remembering.  Still looking for a video that I remember corecraft finding and showing everyone about it in their fixes a few years back ...I'm curious if you have any documentation stating otherwise.

**Comment by killablink** [comment]
http://wowwiki.wikia.com/wiki/Arcane_Concentration?direction=next&oldid=1018562

"Unlike "on spell hit" effects, Arcane Concentration cannot proc off each hit of an Arcane Missiles' bolt, but only off the initial hit of AM itself."

If it actually worked, AM would be the most cost-efficient spell, I looked up many videos of people spamming AM and it only ever procs right after casting (before a missile even deals dmg)

**Comment by ircfelix** [comment]
As you've already figured out, CC should only proc on the start of a channeling cast. More specific for AM here: https://github.com/Atlantiss/NetherwingBugtracker/issues/1801

**Comment by ircfelix** [comment]
20 of 234 of my Arcane Explosions on 1 target triggered clearcasting, which is a ~8,54% proc rate.
13 of 152 of my Arcane Explosions on 4 targets triggered clearcasting, which is a ~8,55% proc rate.

I guess the sample size for testing was too low to produce 8,5% instead of 10% proc rate as a result.

**Comment by Drayo** [comment]
> Clearcasting and Area of Effect-spells:
> Each time a spell deals damage it should have one chance to proc regardless of the amount of targets affected.

Source:
Faxxmonkey video episode 2, original upload to warcraftmovies june 2006.
https://www.youtube.com/watch?v=3O_pNDc73MM
13:35 - 14:13 ::::::: He attacks 93 mobs during the scourge event.
Stacks them up and uses Frost Nova, Arcane Explosions, Flamestrike and Cone of Cold.

Amount of Casts: 12
Amount of targets per Cast: 93
Clearcast Procs: 1

If it was on each hit he would proc Clearcasting on nearly every cast.
In the video his chance to proc clearcasting is clearly lower and about ~10% on each spell-cast.

**Comment by ircfelix** [comment]
please close

**Comment by arcwizard** [comment]
""Unlike "on spell hit" effects, Arcane Concentration cannot proc off each hit of an Arcane Missiles' bolt, but only off the initial hit of AM itself." 
Then how can you comment on the record from patch changes 3.0.8? ( Patch 3.0.8 (2009-01-20): This spell now only has one chance to trigger Arcane Concentration. http://wowwiki.wikia.com/wiki/Patch_3.0.8).  It turns out that before the introduction of this patch did clearсasting become activated 1 time per cast, and Blizzard added a change to the game, as a result of which he began to activate 1 time per cast? Either I don't understand something, or it seems like nonsense.

**Comment by ircfelix** [comment]
> > killablink: Unlike "on spell hit" effects, Arcane Concentration cannot proc off each hit of an Arcane Missiles' bolt, but only off the initial hit of AM itself.
> 
> Then how can you comment on the record from patch changes 3.0.8? ( Patch 3.0.8 (2009-01-20): This spell now only has one chance to trigger Arcane Concentration. http://wowwiki.wikia.com/wiki/Patch_3.0.8). It turns out that before the introduction of this patch did clearсasting become activated 1 time per cast (if rely on your info, since judging by the descriptions of the patches, on the period 2.4.3 to 3.0.8 there were no other changes in mechanics affecting the cause of its triggering), and Blizzard added a change to the game, as a result of which he began to trigger 1 time per cast? Either I don't understand something, or it sounds like "we decided to change the wheel, making it round".

The one proc chance per spell mechanic was already present in vanilla. Check the kronos bugtracker for proof.

**Comment by Dynastyy** [comment]
I didnt state it should procc from every DoT Tick. I just said it will procc from the first INITIAL tick of the DoT if you read it correctly.

**Comment by arcwizard** [comment]
>  Check the kronos bugtracker for proof.

If u about report #7619. First of all, in these videos I don't saw **how many talents have invested in arcane concentration**. Secondly, even if we consider the whole chain of arcane missiles as 1 spell, then even at that, on video clearcasting was triggered less often than it should with a 10% chance (for example, in the last video from the beginning to 6:24 I counted about 41 spell casts, and 0 clearcasting triggers).

**Comment by TomaszPop** [comment]
I remeber few years ago on Ravenholdt (WoW TBC gloval server) i was lvling a mage, and i almost did every dungeon with no drinking at all... just spaming Blizzard > Blizzard > Blizzard... (buff activated like every single blizz spell) 100% dungeon dmg = blizzard. This is first time when i see this kind of problem.

I did 726 direct hits from blizzard during Sockade dungeon - buff wasnt activeted even once.

![WoWScrnShot_041219_164838](https://user-images.githubusercontent.com/36456873/56046128-de480f80-5d42-11e9-902a-396f89688edb.jpg)


![WoWScrnShot_041219_152446](https://user-images.githubusercontent.com/36456873/56046230-151e2580-5d43-11e9-95f6-7995efa97581.jpg)

**Comment by ircfelix** [comment]
> 
> 
> I remeber few years ago on Ravenholdt (WoW TBC gloval server) i was lvling a mage, (and yes it was TBC expansion). Each time i did a dungeon i did it with no drinking at all... just spaming Blizzard > Blizzard > Blizzard... (buff activated like every single blizz spell) 100% dungeon dmg = blizzard. I remeber that clearly. This is first time when i see this kind of problem.
> 
> Buff should have chance to activated "AFTER ANY DAMAGE SPELL HITS A TARGET"
> 
> I did 726 direct hits from blizzard during Stockade dungeon - buff wasnt activeted even once.
> 
> ![WoWScrnShot_041219_164838](https://user-images.githubusercontent.com/36456873/56046128-de480f80-5d42-11e9-902a-396f89688edb.jpg)
> 
> ![WoWScrnShot_041219_152446](https://user-images.githubusercontent.com/36456873/56046230-151e2580-5d43-11e9-95f6-7995efa97581.jpg)


You convinced me that you're smart enough to show us valid research for your claim. There is a thread pinned on the Netherwing General Forums if you need advice on how to research.

Thank you in advance!

**Comment by Tereneckla** [comment]
https://youtu.be/3WOlDCBcjKc?t=489
![image](https://user-images.githubusercontent.com/50233983/86513860-ebe92980-be0d-11ea-880f-339c0d9dae6e.png)
https://youtu.be/PPtWoXVOKI4
Also 5/5 and no permanent clearcasting
