### ISSUE TITLE
First Aid trainer missing Rank 1

### ISSUE THREAD

**Issue by Xtigg** [Atlantiss/NetherwingBugtracker#3501]
[//]: # (Enclose links to things related to the bug using http://wowhead.com or any other TBC database.)
[//]: # (You can use screenshot ingame to visual the issue.)
[//]: # (Write your tickets according to the format:)
[//]: # ([Quest][Azuremyst Isle] Red Snapper - Very Tasty!)
[//]: # ([NPC] Magistrix Erona)
[//]: # ([Spell][Mage] Fireball)
[//]: # ([Npc][Drop] Ghostclaw Lynx)
[//]: # ([Web] Armory doesnt work)
[//]: # (To find server revision type `.server info` command in the game chat.)

**Description**: ([NPC] Thamner Pol) does not train Apprentice First Aid 

**Current behaviour**: Rank 1 is not listed

**Expected behaviour**: Rank 1 should be available 

**Server Revision**:

**Comment by Xtigg** [comment]
This was found yesterday with a level 7 mage from phase one. Attached SS shows First Aid not found under general tab in spell book, the other SS shows Rank 1 not listed with already known checked.  


I would need a fresh level 1 to properly test.




![wowscrnshot_121818_115918](https://user-images.githubusercontent.com/16626061/50173406-fc35c400-02bc-11e9-94c8-6e2cfcdd8443.jpg)
![wowscrnshot_121818_115852](https://user-images.githubusercontent.com/16626061/50173414-03f56880-02bd-11e9-8b11-081501968479.jpg)

**Comment by Shanghi** [comment]
But on that picture, Available isn't checked!

**Comment by Xtigg** [comment]
Well that's an important detail missed. Good eye, Shanghi!

**Comment by Shanghi** [comment]
The mystery has been solved then! Thamner Pol probably shouldn't be drinking while teaching first aid though.
