### ISSUE TITLE
[Item]Blade of Eternal Darkness

### ISSUE THREAD

**Issue by ircfelix** [Atlantiss/NetherwingBugtracker#3502]
**Description**: 
According to https://www.youtube.com/watch?v=N-kA-GrYWHA, this item's effect should proc on instant aoe spells like Arcane Explosion, Cone of Cold or Frost Nova (you can see the blue numbers from mana regeneration when the mage goes into melee, e.g. at 3:26), which indicates that the estimated 10% proc rate **per target** (https://www.wowhead.com/item=17780/blade-of-eternal-darkness#comments) on this item.

According to the wowhead comment and the video (linked above), it should only proc from direct damage spells.
> "this blade's affect can only be actived with a direct damage spell not damage over time or channeling one" 

**Current behaviour**:
If it procs, on direct (aoe) spells, it definately has no 10% proc rate.

**Expected behaviour**: 
This item should have a 10% proc rate **per target** on everything that is not a channeled aoe spell or an aoe spell with a cast time.

**Server Revision**: 
2457

**Comment by Jseay1313** [comment]
+ this item is still pretty useful in tbc solely because it procs on each individual target

**Comment by Kaziczek** [comment]
Revision 2718
After testing with Arcane explosion show proc rate of 2.5%, but never proced 2 or more times from single AE never mind how many targets i got.

I'll update after testing proc rate with single target spells and arcane missiles, there is possibility that it proc on cast, and not on hit.

**Comment by ircfelix** [comment]
Bump.

**Comment by Wolffenstein** [comment]
It does have 10% proc chance, but also 30s icd.

**Comment by ircfelix** [comment]
In the video (3:47) linked in the initial post you can see the mage getting multiple mana restore procs from the blade from two spells cast a global apart from each other. One time from arcane explosion and one time from frost nova. So I guess your 30s icd is wrong. Also it should proc on multiple targets 10% chance per target.

**Comment by Kaziczek** [comment]
While i know that comments are not best for proving bugs, there is a lot of them on wowhead:

By Moshimoshi (2,202 – 2·17) on 2007/12/14 (Patch 2.3.0) | 
This blade has got NO internal cooldown at all, so IF you find yourself very low on mana and have the ability to use an AOE spell then you can get many times your mana back from downranking and switching to this blade in your main hand.

(Yes, as a lvl 70 char, have this myself and I used it with very great success on morogrim tidewalker on the murlocs when I was running low. I'm a mage and had only a resto shammy in my group so I had to do the most with what I had.)

By Aditi (335 – 5) on 2008/06/18 (Patch 2.4.1)
--
When casting Arcane Missiles with this item equipped, each tick has a separate chance to trigger the proc
AoE with Arcane Explosion: each target damaged by the spell has a separate chance to trigger the proc on them. if multiple targets have the proc trigger on them in a single AE cast, you get 100 mana back per target it damaged.
10% proc rate confirmed
