### ISSUE TITLE
[Dungeon][NPC] Shadow Labs - Grandmaster Vorpil missing yell+soundfile at start

### ISSUE THREAD

**Issue by Fenvarien1** [Atlantiss/NetherwingBugtracker#3503]
**Description**: 
Shadowlabs - Grandmaster Vorpil
npc id=18732

**Current behaviour**:
only uses the [opening yell+soundfile on pull](https://www.twitch.tv/videos/350475563?t=23m28s)
missing the "call for help"-yell

[kill yell+soundfile working](https://www.twitch.tv/videos/350475563?t=24m45s)

### **Expected behaviour**: 
> [opening+additional call](https://youtu.be/1zn538fRQ98?t=3)
> at 8,5sec emote happen
> at 12,5sec first spawn
>
>4seconds before the first spawn which is the exact length of the soundfile

> - Yell: Come to my aid! Heed your master now!
> - Soundfile: https://www.wowhead.com/sound=10523/a-auch-vorpil-help01
> - Sound Name: A_AUCH_Vorpil_Help01
> - Sound-ID: 10523

**Server Revision**: 
2457

**Comment by Wolffenstein** [comment]
Fixed in rev 2461.
