### ISSUE TITLE
[Core][Item][Spell] Libram/idol/totem swapping during a spell cast

### ISSUE THREAD

**Issue by Anselm123** [Atlantiss/NetherwingBugtracker#3504]
http://wowwiki.wikia.com/wiki/Patch_2.4.3

https://www.wowinterface.com/downloads/info8295-HolyLibrams.html

**Description**:  Patch 2.4.3 changed the ability to change a weapon slot during a spell cast. Prior to this you were able to swap a libram during the cast time of a spell while piggybacking on the GCD caused from the spell cast like you can from instant cast spells.

**Current behaviour**: You get the error message "you can't do that right now"

**Expected behaviour**: Since this is patch 2.0 you should be able to swap librams during the gcd of the spell being cast to improve paladin/shaman/druid spell usage.

**Server Revision**:

**Comment by killablink** [comment]
And it doesn't matter, they're using 2.4.3 mechanics not 2.0

**Comment by The14me** [comment]
we use 2.4.3 mechanics.
