### ISSUE TITLE
[NPC] Rocktusk Farm, multiple Venomtail Scorpids spawned too closely together

### ISSUE THREAD

**Issue by MacaWilly** [Atlantiss/NetherwingBugtracker#3506]
![image](https://user-images.githubusercontent.com/45656934/50151890-14422d80-0327-11e9-895b-19ee34293f71.png)

**Comment by The14me** [comment]
It looks good to me, but if something will be changed...entry 3127 ID 46 and  47 can be removed.
rev.3472.

**Comment by Wolffenstein** [comment]
Fixed in rev 3476.
