### ISSUE TITLE
Ruul the Darkener NPC - ID=21315 Cipher of Damnation - Borak's Charge

### ISSUE THREAD

**Issue by Styggex** [Atlantiss/NetherwingBugtracker#3508]
[//]: # (https://www.wowhead.com/quest=10578/the-cipher-of-damnation-boraks-charge.)
[//]: # (http://puu.sh/CjB7e/2d532518fc.jpg)
[//]: # (Write your tickets according to the format:)
[//]: # ([Quest][Shadowmoon Valley] The Cipher of Damnation - Borak's Charge)
[//]: # ([NPC] Ruul the Darkener)

**Description**: Currently Ruul the Darkener spawns right above Akama's prison, he is standing still there for atleast 30 seconds then he despawns, nowhere to be found. I tried camping the road leading into Dragonmaw Fortress and after a while he appeared, and once he reached the gate he immediately despawns. All of the RP and dialogues are also missing, from what I've been trying to see and figure out

**Current behaviour**: He spawns in the right location, but the route seems to be either missing or only "half-done". He later appears in end of the route, right before Dragonmaw Fortress where he just sits upon his dragon and the dragon does not stop before the gate, where 2 netherwing dragons should appear with rider and there's supposed to be an RP event where he delivers the fragment.

**Expected behaviour**: He is supposed to spawn right above Akama's Prison, then immediately starts flying according to the route, once he is close to Dragonmaw Fortress, two dragonmaw riders atop their netherwing dragons should appear right behind the gate, and there should be an RP event when that happens.

**Server Revision**:

**Comment by Styggex** [comment]
The only video I can find is this, you can see that Ruul has stopped and is about to have a dialogue/RP event with either the riders on the netherwing dragons or something else in front of them. I tried this quest in retail and it was the same as on this server, but I feel that Ruul is not working properly, even on retail. Might be wrong but; https://youtu.be/iv7aTr0uTkE?t=7

**Comment by Godmatik** [comment]
The patrol path seems just fine to me - probably fixed at some point.
