### ISSUE TITLE
[Item][Spell]Shadowmend set bonus with multiple hits

### ISSUE THREAD

**Issue by torrenzGH** [Atlantiss/NetherwingBugtracker#3509]
[//]: # (Enclose links to things related to the bug using http://wowhead.com or any other TBC database.)
[//]: # (You can use screenshot ingame to visual the issue.)
[//]: # (Write your tickets according to the format:)
[//]: # ([Quest][Azuremyst Isle] Red Snapper - Very Tasty!)
[//]: # ([NPC] Magistrix Erona)
[//]: # ([Spell][Mage] Fireball)
[//]: # ([Npc][Drop] Ghostclaw Lynx)
[//]: # ([Web] Armory doesnt work)
[//]: # (To find server revision type `.server info` command in the game chat.)

**Description**: 
items: https://www.wowhead.com/item-set=553/shadows-embrace
spell: https://www.wowhead.com/spell=39373/shadowmend

I only tried mage spells so couldn't reproduce effect on dots and stuff like drain life. Possibly related to #3500, where the "1x per cast, aoe/channeling disregarded" mechanic is also applied (correctly).

**Current behaviour**:
The 2% heal from shadow/frost damage dealt occurs for only one instance of damage per cast, even if more hits are generated by means of AoE, DoT or channelled spell. The heal should use the caster's crit chance but doesn't seem to crit at all. Maybe related to it being counted as "periodic" healing? 
- Blizzard on 3 dummies, one heal received, 2% of original hit to one target.
![log2](https://user-images.githubusercontent.com/45742182/50164625-7e38e380-02e3-11e9-967e-014279c52c34.jpg)
- Frost nova on 3 dummies, one hit is resisted, resulting in no healing at all.
![log1](https://user-images.githubusercontent.com/45742182/50164905-1df67180-02e4-11e9-96d2-81c4abe04ec1.jpg)
- 100+ frostbolts, no crit heals. ~10% spell crit.
![crits1](https://user-images.githubusercontent.com/45742182/50166755-f7d2d080-02e7-11e9-959f-b1ae147988d3.jpg)

**Expected behaviour**: 
Shadowmend should heal you for 2% of damage on each instance of damage dealt and use your spellcrit chance.
Comments from wowhead pages above.
![cap1](https://user-images.githubusercontent.com/45742182/50165448-4e8adb00-02e5-11e9-962c-e8b5b4c64215.jpg)
![cap2](https://user-images.githubusercontent.com/45742182/50167873-687aec80-02ea-11e9-9e67-e44aabaada27.jpg)
![crits2](https://user-images.githubusercontent.com/45742182/50167640-e5f22d00-02e9-11e9-9648-19807daad1a3.jpg)
**Server Revision**: 
2457

**Comment by Tereneckla** [comment]
Fixed
