### ISSUE TITLE
Mobs incombat positioning abuse. [Rogue] [Druid] [NPC]

### ISSUE THREAD

**Issue by Neophrone** [Atlantiss/NetherwingBugtracker#351]
[//]: # (Enclose links to things related to the bug using http://wowhead.com or any other TBC database.)
[//]: # (You can use screenshot ingame to visual the issue.)
[//]: # (Write your tickets according to the format:)
[//]: # ([Quest][Azuremyst Isle] Red Snapper - Very Tasty!)
[//]: # ([NPC] Magistrix Erona)
[//]: # ([Spell][Mage] Fireball)
[//]: # ([Npc][Drop] Ghostclaw Lynx)
[//]: # ([Web] Armory doesnt work)

**Description**: When you fighting mobs you can abuse mobs mechanic when they changing position to be in front of you (player). So I can use backstab staying in front of mob actualy. More in video.
![position abuse](https://user-images.githubusercontent.com/43533040/45944059-6954f880-bff1-11e8-9015-3a4a3510ef5a.gif)

**Current behaviour**: Server mechanic abuse.

**Expected behaviour**: -----.

**Server Revision**:

**Comment by Wolffenstein** [comment]
Fixed in rev 2046.
