### ISSUE TITLE
[Hunter][Spell] Eagle Eye

### ISSUE THREAD

**Issue by Zarant** [Atlantiss/NetherwingBugtracker#3510]
Eagle eye behaves in a weird manner whenever I start chaining it to some far away location, sometimes objects/NPCs don't load properly, sometimes they do. sometimes my camera goes back to my character, the spell behavior is totally inconsistent. 

Here is the current behavior: https://youtu.be/NKsSYohmKms

And here is the expected behavior: 

> By Brighid (30,737 –  6·25·210)  on 2007/08/23 (Patch 2.1.3) 
> 
> The Shaman spell "Far Sight" works the same way as Eagle Eye does, and gives the same visual effect. In PvP, the foe has no way of knowing whether it is a Shaman or Hunter watching them.
> 
> Also, despite what soultwister says, you can indeed "chain cast" Eagle Eye, but not without a macro. Normally, if you cast Eagle Eye and try to recast it, it instead cancels it. But if you make the following simple macro, it will work:
> /cast !Eagle Eye
> It's the "!" that does it. Instead of toggling the spell, it forces it to recast it. This work with Aspects, too. Anyway, try it. Cast Eagle Eye on something, maybe a mountain at a zone's edge, and then hit the button for this macro and click somewhere that normally is out of sight - your vision changes to that spot. It still does seem have a range limit, but it allows you to see areas that were previously impossible to see (or are simply really far away).
> 
> It's amazing what very strange things Blizzard hides just out of view. I'd imagine that one could use this trick to get a peek at places like Hyjal. It also makes it quite easy to look at the opposing faction's spawn before a BG starts to get an idea of what you're up against.
> 
> Have some fun with it!

Source: https://www.wowhead.com/spell=6197/eagle-eye#comments

Server Revision: 2457

**Comment by Talthos** [comment]
This is bugged as of 2020 now. Video evidence showing the retail functionality from 2007 TBC-era located (mute the music, if desired):

https://www.youtube.com/watch?v=db3sYKRf_AQ&t=1m43s

**Comment by Wolffenstein** [comment]
Fixed in rev 3378.
