### ISSUE TITLE
[Item]Mark of Defiance

### ISSUE THREAD

**Issue by torrenzGH** [Atlantiss/NetherwingBugtracker#3511]
[//]: # (Enclose links to things related to the bug using http://wowhead.com or any other TBC database.)
[//]: # (You can use screenshot ingame to visual the issue.)
[//]: # (Write your tickets according to the format:)
[//]: # ([Quest][Azuremyst Isle] Red Snapper - Very Tasty!)
[//]: # ([NPC] Magistrix Erona)
[//]: # ([Spell][Mage] Fireball)
[//]: # ([Npc][Drop] Ghostclaw Lynx)
[//]: # ([Web] Armory doesnt work)
[//]: # (To find server revision type `.server info` command in the game chat.)

**Description**: 
alliance: https://www.wowhead.com/item=27922/mark-of-defiance
horde: https://www.wowhead.com/item=27924/mark-of-defiance

**Current behaviour**:
Tested on ally side. The ~15 sec internal cooldown and amount restored behave correctly. I also received procs off molten armor as discussed in #3234. However, using arcane missiles to channel 5 hits, I only ever received the proc on the first instance of damage from the spell. This behavior was changed in 2.2.

**Expected behaviour**: 
I leave it to the discretion of staff whether this belongs in "2.0" or not.
![mark of defiance](https://user-images.githubusercontent.com/45742182/50171098-d0810100-02f1-11e9-9b58-0c7294d5e75c.jpg)

**Server Revision**: 
2457

**Comment by ircfelix** [comment]
Did you also check the proc rate? It seems kinda low.

**Comment by Godmatik** [comment]
It was decided long ago that trinkets will be in their 2.4.3 state - closing
