### ISSUE TITLE
[Spell][Rogue] Remorseless Attacks

### ISSUE THREAD

**Issue by tendub** [Atlantiss/NetherwingBugtracker#3512]
[//]: # (Enclose links to things related to the bug using http://wowhead.com or any other TBC database.)
[//]: # (You can use screenshot ingame to visual the issue.)
[//]: # (Write your tickets according to the format:)
[//]: # ([Quest][Azuremyst Isle] Red Snapper - Very Tasty!)
[//]: # ([NPC] Magistrix Erona)
[//]: # ([Spell][Mage] Fireball)
[//]: # ([Npc][Drop] Ghostclaw Lynx)
[//]: # ([Web] Armory doesnt work)
[//]: # (To find server revision type `.server info` command in the game chat.)

**Description**: 

Rogue talent (first tier assassination tree) remorseless attacks is not providing crit bonus for hemorrhage
 
**Current behaviour**:

Remorseless Attacks buff is consumed upon using hemo but is not granting crit bonus. Tested with GM Smaily in Thousand Needles on lvl 40 rogue, got no hemo crits, but sinister strike was critting properly. Could be astronomically terrible luck, but Felmyst had the same issue so I don't think so. Only tested for hemo and sinister strike, not the other attacks.

**Expected behaviour**: 

Upon using hemo with Remorseless Attacks buff the attack should have +40% chance to crit

**Server Revision**: 

2457

**Comment by Wolffenstein** [comment]
Hemorrhage is in the list of spells affected by it. It should be working properly just like Sinister Strike.

**Comment by Wolffenstein** [comment]
It really should be working. I will reopen if someone else reports this as an issue as well.
