### ISSUE TITLE
[Spell][Mage]Ice Barrier and wards scaling

### ISSUE THREAD

**Issue by torrenzGH** [Atlantiss/NetherwingBugtracker#3513]
[//]: # (Enclose links to things related to the bug using http://wowhead.com or any other TBC database.)
[//]: # (You can use screenshot ingame to visual the issue.)
[//]: # (Write your tickets according to the format:)
[//]: # ([Quest][Azuremyst Isle] Red Snapper - Very Tasty!)
[//]: # ([NPC] Magistrix Erona)
[//]: # ([Spell][Mage] Fireball)
[//]: # ([Npc][Drop] Ghostclaw Lynx)
[//]: # ([Web] Armory doesnt work)
[//]: # (To find server revision type `.server info` command in the game chat.)

**Description**: 
I only tested ice barrier. I assume fire ward and frost ward are affected as they were changed in the same patch.

**Current behaviour**:
Ice Barrier tooltip currently lists the correct new base value of 1075 at rank 6 introduced in 2.3. The same patch buffed spellpower scaling from 10% to 30%. The absorb value I got with 755 spellpower is 1178, so only around 10% scaling is applied.
![wowscrnshot_121818_201239](https://user-images.githubusercontent.com/45742182/50177471-5dcc5180-0302-11e9-85b1-b63bba6cd058.jpg)

**Expected behaviour**: 
https://web.archive.org/web/20080304051324/http://elitistjerks.com:80/f31/t16979-mage_tc_after_2_3_a/
from 2.3 notes:
 Fire Ward and Frost Ward now gain additional benefit from spell damage bonuses. Base absorb values of ranks 5 and 6 have been reduced.
Ice Barrier now gains additional benefit from spell damage bonuses. Base absorb values of ranks 5 and 6 have been reduced. (Rank 6: Old: 1175 + 10% | New: 1075 + 30%)
**Server Revision**: 
2457

**Comment by Evolvee** [comment]
could u also check priests PW:shield? should be 60 or 80 from bonus healing(before counting talents inside it), im not 100% sure now

**Comment by torrenzGH** [comment]
rank 12 pw:s with no talents shows as 1265 base
1385 absorbed with 402 spellpower so 30%
![1](https://user-images.githubusercontent.com/45742182/50182802-9541fa80-0310-11e9-98f9-8d20949d85ab.jpg)
http://wowwiki.wikia.com/wiki/Power_Word:_Shield
it was increased to 20% early on and increased again in 2.3 but the final value isnt specified here

seems shadow ward, frost/fire, ice barrier and pw:s were all modified in this patch so definitely worth checking out

**Comment by Wolffenstein** [comment]
PW:S is currently 30% from BSH

**Comment by Wolffenstein** [comment]
Fixed in rev 2461.
