### ISSUE TITLE
Omer's Revenge - Dynamic Respawn

### ISSUE THREAD

**Issue by SwiftieTBC** [Atlantiss/NetherwingBugtracker#3514]
Doesn't seem the NPC for this quest are dynamically re spawning
Ormer's Revenge - Quest ID 295
Mottled Scytheclaw - Creature ID 1022
Mottled Razormaw - Creature ID 1023

**Comment by Wolffenstein** [comment]
Please tag @aresbrutus in all of these

**Comment by aresbrutus** [comment]
These got fixed.
