### ISSUE TITLE
[Spell] Incite Chaos, caster behaviour

### ISSUE THREAD

**Issue by AxeCell** [Atlantiss/NetherwingBugtracker#3516]
**Description**: 
Topic is related to Incite Chaos' behaviour with spell casting.

**Current behaviour**:
Sometimes when a caster channels up a spell they will self interrupt repeatedly instead of finishing the cast.

**Expected behaviour**: 
Casters should be able to finish their spell casts when mind-controlled by Incite Chaos.

**Server Revision**: 
2457

**Comment by Tereneckla** [comment]
Only the castbar disappears

**Comment by Godmatik** [comment]
Rev 4017 - unable to reproduce
After Incite Chaos is cast, everything works normally, even if mid-cast with a spell.
