### ISSUE TITLE
[NPC][Shattered Halls] Shattered Hand Assassin incorrect AI

### ISSUE THREAD

**Issue by Jseay1313** [Atlantiss/NetherwingBugtracker#3519]
**Description**: Shattered Hand Assassins currently prioritizing their abilities/targets incorrectly

http://wowwiki.wikia.com/wiki/Shattered_Halls 
Stealthed in the hallways before Warbringer O'mrogg and to Warchief Kargath Bladefist. Uses Sap on first player to aggro them. Use any method of detection. If unavailable simply keep your distance while the tank scouts ahead and the assassin will immediately break its own sap. 

**Current behaviour**: The assassin saps, and then instantly cheap shots the same target and breaks the sap with auto attacks despite the group being engaged or within range

**Expected behaviour**: The assassin should sap a target and then behave as if the target is disoriented and cheap shot + engage on another target.

**Server Revision**: 2462

**Comment by The14me** [comment]
Need some retail proof.

**Comment by TheRealZaroua** [comment]
Assassins should also only be using Sap on players who are out of combat. However they'll currently cast Sap on players that already are in combat.

**Comment by devo6969** [comment]
Can't find any information or videos of Sap in combat but this is an NPC ability not like Rogue's Sap. _Perhaps_ like Blast wave on Warbringer O'mrogg has a slow movement effect and you cant Freedom it off where as Blast wave on a mage you can freedom. They are different is my point. According to sources though, it is suppose to sap a target and then cheapshot another target. Whether its in-combat, out-of-combat, or both I couldn't say for-sure.

PTR - Only rogue pull - https://www.youtube.com/watch?v=1-hlzQoTyog 
PTR - Aggroed then pulled with rogue - https://www.youtube.com/watch?v=4mjlAj2sr6g

https://wowwiki.fandom.com/wiki/Shattered_Halls
"Uses Sap on first player to aggro them."

https://www.wowhead.com/npc=17695/shattered-hand-assassin#abilities
" They usually take out a random member of the party through sap, then procede to cheapshot another, and attacking."

**Comment by BamboozleNW** [comment]
https://www.youtube.com/watch?v=HXT8NH-nvFI     
3:04 Shaman gets sapped, then the warrior gets cheap shotted. 3:26 shaman gets sapped, then cheap shotted. 4:28 shaman just gets cheap shotted(resist?) 4:45 spriest gets sapped, then cheap shot on the shaman. 5:15 warrior sap, shaman cheap shot. "Expected behaviour: The assassin should sap a target and then behave as if the target is disoriented and cheap shot + engage on another target." I would say confirmed, seems like saps the closest target and cheap shots another, regardless of combat.

**Comment by devo6969** [comment]
On that video Bamb, i think they shaman got sapped, then cheap shotted because @ 3:26 because aggro from mana spring. at 4:28 they unstealthed him, hence the instant cheap shot. Good video
