### ISSUE TITLE
[Spell] Magic Grounding (Akkiris Lightning-Waker)

### ISSUE THREAD

**Issue by AxeCell** [Atlantiss/NetherwingBugtracker#3521]
**Description**: 
Topic is related to the Magic Grounding spell of Akkiris Lightning-Waker found within Arcatraz(heroic).

**Current behaviour**:
During the fight with the mini-boss I never noticed him buffing himself with this spesific buff. Someone would have to double-check if this is actually the case.

**Expected behaviour**: 
He should buff himself with Magic Grounding which reduces the magic damage he takes by 50%.

**Server Revision**: 
2345

**Comment by AxeCell** [comment]
Here's the ability page on Wowhead: https://www.wowhead.com/npc=20908/akkiris-lightning-waker#abilities:mode=normal
Here's a video showcasing the shaman's flame shock ticks/fire elemental fire nova dealing reduced damage once his buff kicks in: https://youtu.be/NBqaJ7nPdWQ?t=303

**Comment by Wolffenstein** [comment]
Fixed in rev 3389.
