### ISSUE TITLE
[NPC] Harbinger Skyriss post 2

### ISSUE THREAD

**Issue by AxeCell** [Atlantiss/NetherwingBugtracker#3524]
**Description**: 
Topic is related to Haringer Skyriss' clones.

**Current behaviour**:
Once killing the first clone of Harbinger Skyriss in heroic we got the "You are now saved to this instance" message. 2nd clone also had the same health as the boss himself.

**Expected behaviour**: 
The first interaction shouldn't happen, and the clone should have reduced health instead of what the boss himself starts with.

**Server Revision**: 
2345

**Comment by The14me** [comment]
Need retail proof.

**Comment by AxeCell** [comment]
Here's proof that the 2nd clone should have a much lower health pool: https://youtu.be/XKGHdJNFHeE?t=212

**Comment by Tereneckla** [comment]
That guy never changed target, but the clones have a lot lower hp than the boss.
