### ISSUE TITLE
[Spell] Curse of Mending

### ISSUE THREAD

**Issue by Bleachlol** [Atlantiss/NetherwingBugtracker#353]
**Description**: 
Hit the enemy, did animation never healed 
**Current behaviour**:
Evaded the spell on mob and sometimes doesn't heal on hit, does the animation though. 
https://imgur.com/a/16sn97K 
**Expected behaviour**: 
Curse of mending should have a 20% chance to heal the enemy on hit. 
**Server Revision**: 
2040

**Comment by Evolvee** [comment]
npc entry?

**Comment by Evolvee** [comment]
broken spell, NPC script is fine

**Comment by The14me** [comment]
Confirm,work only with mele attack atm. rev:2083
