### ISSUE TITLE
[NPC](Loot) The Black Stalker

### ISSUE THREAD

**Issue by AxeCell** [Atlantiss/NetherwingBugtracker#3530]
**Description**: 
Topic is related to the loot table of The Black Stalker in heroic.

**Current behaviour**:
The Black Stalker only dropped a Primal Nether and an epic gem.

**Expected behaviour**: 
Should drop atleast two blue gear items.

**Server Revision**: 
2457

**Comment by aresbrutus** [comment]
Should be fixed in rev `2466`
