### ISSUE TITLE
Spelling error in "Free From the Hold" quest

### ISSUE THREAD

**Issue by Mavock** [Atlantiss/NetherwingBugtracker#3532]
[//]: # (Enclose links to things related to the bug using http://wowhead.com or any other TBC database.)
[//]: # (You can use screenshot ingame to visual the issue.)
[//]: # (Write your tickets according to the format:)
[//]: # ([Quest][Azuremyst Isle] Red Snapper - Very Tasty!)
[//]: # ([NPC] Magistrix Erona)
[//]: # ([Spell][Mage] Fireball)
[//]: # ([Npc][Drop] Ghostclaw Lynx)
[//]: # ([Web] Armory doesnt work)
[//]: # (To find server revision type `.server info` command in the game chat.)

**Description**: 
Typo found in Gilthares Firebough's speech during the escort quest "Free from the Hold".

**Current behaviour**:
Dialogue: Looks like the Southsea Freeboters are heavily entrenched on the coast.
**Expected behaviour**: 
Dialogue: Looks like the Southsea Freebooters are heavily entrenched on the coast. 
**Server Revision**: 

![image](https://user-images.githubusercontent.com/39953678/50188983-db548980-0323-11e9-90e1-5769790f2291.png)

**Comment by Evolvee** [comment]
rev 2500
