### ISSUE TITLE
[Spell][Hunter] Feign Death foesn't work in combat.

### ISSUE THREAD

**Issue by transphenomenal** [Atlantiss/NetherwingBugtracker#3533]
[//]: # (Enclose links to things related to the bug using http://wowhead.com or any other TBC database.)
[//]: # (You can use screenshot ingame to visual the issue.)
[//]: # (Write your tickets according to the format:)
[//]: # ([Quest][Azuremyst Isle] Red Snapper - Very Tasty!)
[//]: # ([NPC] Magistrix Erona)
[//]: # ([Spell][Mage] Fireball)
[//]: # ([Npc][Drop] Ghostclaw Lynx)
[//]: # ([Web] Armory doesnt work)
[//]: # (To find server revision type `.server info` command in the game chat.)

**Description**: 
[Spell][Hunter] Feign Death does not work if it could be resisted in combat.

**Current behaviour**:
Feign Death does not work while in combat and there's a chance it could be resisted. The Feign Death buff is given, yet you stay standing and things still attack you. I tried it against the dummies and low level mobs. I also tried it 5 times against a level 67 mobs, and if it was within 15 yards or so, Feign Death never worked. But it worked when it was 25 or so yards away. There was no "Spell was resisted" notification in the combat log. 
I am using a female Blood Elf.

**Expected behaviour**: 
Feign Death should make you fall down "dead" and mobs will stop attack you. If it's resisted, then the Feign Death buff should not appear and the spell should immediately start its 30 second cool down.

**Server Revision**:

**Comment by Wolffenstein** [comment]
The spell was resisted, currently the only issue is the aura stays on you when that happens.

**Comment by gwxse8w** [comment]
I don't think Feign Death is supposed to send a combatlog message.

In fact, at least pre-2.3, the only way to check for a FD resist was through mid-screen-error-messages.

Extract from the addon `FeignResistBell` with toc 20200:
```if (event == 'UI_ERROR_MESSAGE') and (arg1 == ERR_FEIGN_DEATH_RESISTED) then```
That's how the addon check for it, aka, not from the combatlog messages.

**Comment by Wolffenstein** [comment]
Fixed in rev 2465.
