### ISSUE TITLE
[NPC] Naturalist Bite

### ISSUE THREAD

**Issue by gwxse8w** [Atlantiss/NetherwingBugtracker#3534]
**Description**: 
Once Naturalist Bite is released from his cage (and after you kill the three mobs, that should probably be four) he will grant you a Nature Resist (110 NR) and Stats (5%) buff, called Mark of Bite.
If you then wipe on Quagmirran Naturalist Bite should despawn/die (does he add to the boss fight and die? Not sure) or shouldn't grant you Mark of Bite no more.

Aka, you shouldn't be able to acquire Mark of Bite twice, unless you reset the instance.

**Current behaviour**:
When you wipe on Quagmirran you can take another Mark of Bite.

**Expected behaviour**: 
You should be able to get Mark of Bite just once per instance reset.

**Comment by Wolffenstein** [comment]
Proof?

**Comment by The14me** [comment]
Need retail proof.

**Comment by Tenoutoften** [comment]
There is a very strange spell I found... [[Spell]Quagmirran hits Naturalist Bite#32560](https://www.wowhead.com/spell=32560/quagmirran-hits-naturalist-bite)

**Comment by Tereneckla** [comment]
Couldn't find anything on him despawning.
All other druids stay to let other players complete the quest.
