### ISSUE TITLE
[Loot] Motes of Shadow not dropping from all demons

### ISSUE THREAD

**Issue by bigripper** [Atlantiss/NetherwingBugtracker#3535]
**Description**: In retail, Motes of Shadow dropped from nearly all demons.

**Current behaviour**: Motes only drop off void walker demons in HFP and Nagrand.

**Expected behaviour**:  Nearly every demon in Outland should have a chance to drop motes. I know this was changed after 2.1, but since we are 2.0, I feel like this should be implemented.

Proof:

archive from 2007 wowhead.com

https://web.archive.org/web/20071018173327/http://wowhead.com:80/?item=22577

You can see all the mobs that drop them and some of the comments talk about the drops too.

**Server Revision**:

**Comment by Saben65** [comment]
Reported previously: https://github.com/Atlantiss/NetherwingBugtracker/issues/3348

**Comment by The14me** [comment]
Duplicate
