### ISSUE TITLE
[Dungeon][The Arcatraz] Final boss scenario did not reset

### ISSUE THREAD

**Issue by Medry** [Atlantiss/NetherwingBugtracker#3536]
[//]: # (Enclose links to things related to the bug using http://wowhead.com or any other TBC database.)
[//]: # (You can use screenshot ingame to visual the issue.)
[//]: # (Write your tickets according to the format:)
[//]: # ([Quest][Azuremyst Isle] Red Snapper - Very Tasty!)
[//]: # ([NPC] Magistrix Erona)
[//]: # ([Spell][Mage] Fireball)
[//]: # ([Npc][Drop] Ghostclaw Lynx)
[//]: # ([Web] Armory doesnt work)
[//]: # (To find server revision type `.server info` command in the game chat.)

**Description**: 
Explanation and videos of exactly what happened since it's probably had to reproduce.

While wiping on the final boss, we managed to break the scenario so that it was not resetting, and the mini-bosses would stay spawned.
I will post two videos from a party members stream where the bug may have started.
First Video: https://www.youtube.com/watch?v=77nQtCTaRPI&feature=youtu.be
We wipe on the second mini boss, our warlock runs out of the room to avoid death. The mini-boss chases him and then turns around to reset to his spawn position when the warlock exits the room. Millhouse chases and then turns around, and engages the mini-boss. The mini boss then teleported the warlock on top of him, and he dies. The mini-boss finishes off millhouse before resetting, but the visual bubble around the Warden does not disappear
Second Video: https://www.youtube.com/watch?v=_9BEKmcRG0k&feature=youtu.be
Due to us believing it was bugged, due to the bubble visual, our rogue runs into the room and starts the fight to test, while 3 of us stand outside the room, out of combat and watch. The fight starts successfully and the rogue uses vanish, but dies when the mini-boss that spawns auto-aggro's to him because he is inside the room. This starts the scenario refusing to reset. The rest of the group, still out of combat, begins rezzing up the two dead players, however the script for the fight appears to still be running, because after some time passes the second mini-boss is released from his prison and auto-aggro's onto our healer who is trying to rez our currently afk rogue. We all exit the room again, and the mini-boss resets to his spawn position below the cell. Then after some time the third mini-boss spawns, and Millhouse who has been standing in the middle of the room starts attacking him. Millhouse ice blocks, and the mini-boss runs to us, we exit the room again, causing him to run back into the room and kill Millhouse. Once Millhouse dies, he resets to his spawn position and stands there. 
At this point i contacted a GM on the discord who tried to help us, and advised me to make this bug report as he was unable to repair the fight.
**Current behaviour**:
Fight did not reset when players in combat died. 
During our first wipe, the warlock who exited the room was teleported back in and killed before the fight reset, but in video two where we all stood outside the room as only the rogue got in combat, it became bugged. Have a feeling us being out of combat and standing outside the room caused the event to not reset.

**Expected behaviour**: 
A wipe on the mini-bosses should cause the entire event to reset. 

**Server Revision**:

**Comment by Jalapan** [comment]
still broken! if you wipe you need a GM to reset last boss.

**Comment by devo6969** [comment]
I think what is happening when you aggro the first mob it treated like you are still there -Alive- and over time Millhouse spawns and goes to the middle and doesn't aggro the 2nd or 1st mob. Now though, as long as you don't aggro the 2nd mob the encounter will reset but of course this takes time and the visual bubble is still there so "visual bug". It took a lot of effort to recreate this and the likely hood of someone doing it again in its current state is very unlikely. The only way for the bug to happen is to legit aggro all three mobs and die now.
First Video - Reset happens early- https://www.youtube.com/watch?v=fUjNRfmWzpI
Second Video - Resets off third mini-boss- https://www.youtube.com/watch?v=xsWBOK1qgLI
Third Video  - Recreating the bug - https://www.youtube.com/watch?v=Z-6woSxdoCM

**Comment by Godmatik** [comment]
Duplicate
