### ISSUE TITLE
[Quest][Netherstorm]Creatures of the Eco-Domes

### ISSUE THREAD

**Issue by bigripper** [Atlantiss/NetherwingBugtracker#3538]
**Description**:  The talbuks stay permanently in their tagged state. 

**Current behaviour**:The talbuks stay permanently in their tagged state. 

**Expected behaviour**: The should not stay in the state for more than 30 seconds. The state that they are in now requires a server reset to make them attack-able again. I wait for more than 10 minutes just to test and they are still just laying on the ground. The "sleep" visual goes away after about 30 seconds.

**Server Revision**: 
![talbuk](https://user-images.githubusercontent.com/45222160/50201900-39c83a80-0319-11e9-9f8e-af6f2a3f5396.PNG)
![talbuk](https://user-images.githubusercontent.com/45222160/50201922-51072800-0319-11e9-9e2d-45ebbbfcbe9e.PNG)

**Comment by Tenoutoften** [comment]
https://github.com/Atlantiss/NetherwingBugtracker/issues/2666 already reported
