### ISSUE TITLE
[Quest][Durotar] Therzok

### ISSUE THREAD

**Issue by Rosos** [Atlantiss/NetherwingBugtracker#3539]
[//]: # (Enclose links to things related to the bug using http://wowhead.com or any other TBC database.)
[//]: # (You can use screenshot ingame to visual the issue.)
[//]: # (Write your tickets according to the format:)
[//]: # ([Quest][Azuremyst Isle] Red Snapper - Very Tasty!)
[//]: # ([NPC] Magistrix Erona)
[//]: # ([Spell][Mage] Fireball)
[//]: # ([Npc][Drop] Ghostclaw Lynx)
[//]: # ([Web] Armory doesnt work)
[//]: # (To find server revision type `.server info` command in the game chat.)

**Description**: 
Class quest for rogues (troll/orc) is greyed out at lvl 10, when it should be available.
**Current behaviour**:
Can't accept the quest because its greyed at lvl 10.
**Expected behaviour**: 
Should be acceptable at lvl 10.
**Server Revision**:

**Comment by Tenoutoften** [comment]
You couldn't get the quest from [[NPC]Kaplak#3170](http://web.archive.org/web/20071114184321/http://thottbot.com:80/c3170)? 
http://web.archive.org/web/20071120091354/http://thottbot.com:80/q1859

**Comment by Rosos** [comment]
Ye thats the issue, the quest is there but not available for me as lvl 10.

**Comment by Shanghi** [comment]
Is your character a troll? That's an optional orc-only quest that's usually not set right on private servers. The grayed out one you see may be a different level 16 quest on him.

Some comments from wowhead/thottbot/allakhazam:
> [Wowhead:7] [Aapo87] [2008/02/24] [2.3.3]
> I wasnt able to get this quest as a troll either, however you can go to the cleft of shadows and get the next quest from that Ther-whats his face guy without compelting this quest.
> 
> [Wowhead:0] [keart56] [2009/11/02] [3.2.2a]
> hello guys i have porblem i will not get the rogue quets from my  rogue trainer in razor hill is thta normal or? i am level 10 troll rogue
> 
> [Wowhead:0] [Jaybles2100] [2010/07/18] [3.3.5a]
> I can confirm this: At the moment (patch 3.3.5) Troll rogues can't get this quest at level 10 they can however get the next one in the quest line from [url=http://www.wowhead.com/npc=6446]Therzok[/url] in Orgrimmar.
> 
> [Wowhead:1] [Shadowspawn] [2009/12/13] [3.3.0]
> It seems to be Orc only.  This is strengthened by the fact that he states the race in his quest log ("Was told to keep an eye out for an orc by your description") as opposed to the <race> tag.
> 
> [Thottbot:0] [KurrelgyreGM] [2005/12/05] [1.8.4]
> How the heck do I get this?
> I'm a level 12 troll rogue now, and STILL cannot get this quest! Is there a race restriction? Or a prereq quest?
> 
> [Thottbot:0] [RepulsionParadigm>] [2005/12/05] [1.8.4]
> <Blank>
> If you can't get the quest from Kaplak, go directly to Therzok in Org. That's how I got mine (level 10 troll rogue).
> 
> [Thottbot:0] [cheeeko] [2005/12/05] [1.8.4]
> <Blank>
> yeah, just talk to Therzok in cleft of shadows. i'm a troll and i got the quest at lvl 11
> 
> [Thottbot:0] [Thauglor] [2006/10/30] [1.12.2]
> Quest eligibility.
> This quest is strange. You MUST be an orc rogue to get it. Trolls rogues are not eligible, and I wonder why. I haven't find any troll rogue trainer in Durotar, except in Orgrimmar. So, trolls seems to have to speak directly to Therzok.
> 
> [Thottbot:1] [LinkD] [2007/07/22] [2.1.3]
> im a level 10 troll rogue
> and i cannot get the quest from the rogue trainer in durotar, so if your a troll rogue, go straight to the second step in the quest
> 
> [Allakhazam:1] [Talamil] [2005/04/28] [1.4.0]
> not given
> This quest is not given to me (lvl 10 troll rogue)
> 
> [Allakhazam:1] [Yassassin] [2005/07/19] [1.6.0]
> Troll rogues
> My troll didn't get this either.
> Just go speak with Therzok and you can still get the quest.
> You get a great dagger at the end. Don't skip this quest.

It's also been marked as Orc-only on [Wowhead since Cataclysm](https://web.archive.org/web/20100701004427/http://www.wowhead.com:80/quest=1859) (but nothing before that unfortunately).

**Comment by Rosos** [comment]
Oh i am a troll, that makes sense then. I wasnt aware it was only for orcs !

**Comment by Shanghi** [comment]
It's going to cause a lot of confusion now that people are used to doing it as trolls!
