### ISSUE TITLE
[Zone - Ghostlands/Zul Aman] zul'aman raid portal not giving messages 

### ISSUE THREAD

**Issue by DarthNekr0s** [Atlantiss/NetherwingBugtracker#354]
**Description**: while in a raid group, trying to enter Zul Aman portal doesnt give any error messages, you just run at an invisible wall

**Current behaviour**: ^ description

**Expected behaviour**:  should have a message saying Zul Aman is not available

**Server Revision**: 
![wowscrnshot_092418_192443](https://user-images.githubusercontent.com/16113944/45945195-09317700-c030-11e8-9fc2-7047b4cc53d2.jpg)

**Comment by Manaci** [comment]
Not needed anymore
