### ISSUE TITLE
[Loot] Mob wealth

### ISSUE THREAD

**Issue by Dekirayne** [Atlantiss/NetherwingBugtracker#3540]
**Description**: 
All mobs in the game seem to have increased wealth/money drop (silver/gold)
**Current behaviour**:
I have tested numerous mobs, and there is no way in hell that they drop this much money.
Even ogres in Deadwind pass drop like 19silver if i remember correctly im lazy to go check out.
**Expected behaviour**: 
I'm not sure how much each mob should drop, but from this screenshot i think these mobs in WPL should drop max 2 silver
![image](https://user-images.githubusercontent.com/12075744/50220953-01197700-0394-11e9-89d8-f1e36714c5db.png)

**Server Revision**:

**Comment by Drayo** [comment]
https://www.youtube.com/watch?v=o76X1TSA9_U

1-5 Silver seems to be the correct range for these, at least it was back in vanilla.

Maybe increased Money drops form Outlands affect vanilla mobs too?

**Comment by Evolvee** [comment]
gold drop was increased compared to stock servers - it was researched from retail videos, especially joana

**Comment by Evolvee** [comment]
We overhauled the entire gold loot income from the whole world...

reopen if u find evidence

**Comment by Dekirayne** [comment]
ok I admit my mistake, years of private servers seem to have blurred my memory of retail vanilla/tbc.
nice to see how you guys do the databases, love it.
