### ISSUE TITLE
[Dungeon][NPC] Shadow Labs - Blackheart the Inciter MC_Spell_List(tbc research)

### ISSUE THREAD

**Issue by Fenvarien1** [Atlantiss/NetherwingBugtracker#3542]
### LIST OF SPELL USED DURING MIND CONTROL
_The number behind the spells counts the usage. **The list only contains proven spells**_

<details>
    <summary>Shaman</summary>

- Chainlightning 4
- Lightning Shield 2
- Nature's Swiftness
- Water Shield 4
- Rockbiter Weapon
- Flameshock
- Frostshock
- Lesser Healing Wave 2
- Lightning Bolt

</details>

<details>
    <summary>Druid</summary>

- Starfire 4
- Wrath 5
- Maul
- Hurricane
- Feral Charge

</details>

<details>
    <summary>Paladin</summary>

-  Holy Light
-  Avenging Wrath
-  Consecration 4
-  Avenger's Shield 2
-  Holy Shield
-  Flash Heal

</details>

<details>
    <summary>Rogue</summary>

- Kick
- Throw
- Cloak of Shadows
- Evasion
- Blind
- Gouge

</details>

<details>
    <summary>Priest</summary>

- Fade 4
- Psychic Scream 2
- Innerfire
- Holy Fire 5
- Smite 3
- Holy Nova 4
- Inner Focus
- Shadow Word: Death 4
- Mind Blast
- Devouring Plague
- Mass Dispell

</details>

<details>
    <summary>Mage</summary>

- Cone of Cold 2
- Blizzard 4
- Molten Armor 2
- Flamestrike
- Firebolt 4
- Arcane Blast 2
- Ice Armor
- Frost Nova 2
- Ice Lance 2
- Scorch
- Arcane Explosion
- Blastwave
- Pyroblast
- Ice Barrier
- Dragon's Breath

</details>

<details>
    <summary>Warlock</summary>

- Howl of Terror 3
- Incinerate 3
- Searing Pain 2
- Curse of Agony
- Seed of Corruption
- Rain of Fire

</details>

<details>
    <summary>Warrior</summary>

- Concussion Blow
- Shoot(range weapon)
- Sweeping Strikes 2
- Commanding Shout
- Whirlwind
- Thunder Clap
- Cleave
- Rend 3
- Demoralizing Shout
- Spell Reflection
- Battle Shout
- Last Stand
- Shield Block

</details>

<details>
    <summary>Hunter</summary>

- Frost Trap 4
- Volley 4
- Rapid Fire 3
- Multishot 3
- Hunter's Mark 2
- Aspect of the Hawk 3
- Aspect of the Monkey
- Aspect of the Wild
- Scatter Shot
- Pet Mending
- Explosive Trap 2
- Serpent Sting
- Freezing Trap
- Viper Sting

</details>

<details>
    <summary>Racials</summary>

- Priest(UD/BE): Touch of Weakness
- Orc Racial: Blood Fury
- Tauren Racial: Stomp
- Human Racial: Perception

</details>

### **Videos:**
<details>
    <summary>11.02.2007 - Video 1 Shaman POV</summary>
https://www.youtube.com/watch?v=vX95Z5nqI0c

https://youtu.be/vX95Z5nqI0c?t=43 Incite Chaos 1

Shaman:
Chainlightning
Lightning Shield
Nature's Swiftness
Lesser Healing Wave

Druid:
Starfire

Mage:
Cone of Cold

https://youtu.be/vX95Z5nqI0c?t=113 Incite Chaos 2

Warrior:
Shoot(range weapon)

Shaman:
Chainlightning
Lightning Bolt
Water Shield

Druid:
Wrath
Starfire

https://youtu.be/vX95Z5nqI0c?t=174 Incite Chaos 3

Shaman:
Chainlightning
Rockbiter Weapon
</details>
<details>
    <summary>17.05.2007 - Video 2 Hunter POV</summary>
https://www.youtube.com/watch?v=kTQefSWeFHY

https://youtu.be/kTQefSWeFHY?t=28 1

Hunter:
Freezing Trap
Volley
Rapid Fire

Shaman:
Flameshock
Chainlightning

Priest:
Devouring Plague

https://youtu.be/kTQefSWeFHY?t=97 2 

Orc Racial: Blood Fury

Priest:
Devouring Plague

Hunter:
Volley
Multishot

https://youtu.be/kTQefSWeFHY?t=168 3

Orc Racial: Blood Fury

Shaman:
Frostshock
Water Shield
Lightning Shield

Hunter:
Hunter's Mark
Aspect of the Monkey

https://youtu.be/kTQefSWeFHY?t=234 4

Hunter:
Rapid Fire
Aspekt of the Hawk
Pet Mending
Shaman:
Watershield
</details>
<details>
    <summary>25.04.2007 - Video 3 Hunter POV</summary>
https://www.youtube.com/watch?v=XeZLEYiCEzE

https://youtu.be/XeZLEYiCEzE?t=34 1

Hunter:
Multishot
Rapid Fire
Aspekt of the Hawk
Scatter Shot
Flame Trap
Freezing Trap
Aspect of the Wild

Priest:
Fade

Mage:
Blizzard

Druid:
Swipe

https://youtu.be/XeZLEYiCEzE?t=104 2

Hunter:
Freezing Trap
Volley
Serpent Sting

Mage:
Molten Armor
Flamestrike
Firebolt

https://youtu.be/XeZLEYiCEzE?t=162 3

Hunter:
Freezing Trap
Aspekt of the Hawk
Hunter's Mark

Priest:
Psychic Scream

Mage:
Arcane Blast

</details>
<details>
    <summary>24.03.2007 - Video 4 Priest POV</summary>
https://www.youtube.com/watch?v=4M6g6mHBXFM

https://youtu.be/4M6g6mHBXFM?t=16 1

Priest:
Innerfire
Holy Fire
Smite
Holy Nova
Inner Focus

Druid:
Starfire
Wrath
Hurricane

Mage:
Arcane Blast

https://youtu.be/4M6g6mHBXFM?t=43 2

Priest:
Smite
Holy Fire
Fade
Shadow Word: Death

Mage:
Blizzard

Warlock:
Incinerate

https://youtu.be/4M6g6mHBXFM?t=76 3

Priest:
Holy Nova
Shadow Word:Death
Holy Fire
Touch of Weakness
Mind Blast

Druid:
Starfire

https://youtu.be/4M6g6mHBXFM?t=107 4

Priest:
Fade
Holy Nova
Shadow Word:Death

Warrior:
Concussion Blow

Mage:
Firebolt

https://youtu.be/4M6g6mHBXFM?t=139 5

Priest:
Holy Nova
Shadow Word:Death
Holy Fire
Fade
Smite

</details>
<details>
    <summary>10.08.2007 - Video 5 Mage POV</summary>
https://www.youtube.com/watch?v=bUQ02Qmt5ik

https://youtu.be/bUQ02Qmt5ik?t=37 1

Mage:
Icearmor
Frost Nova
Ice Lance
Cone of Cold
Blizzard

Druid:
Feral Charge

https://youtu.be/bUQ02Qmt5ik?t=106 2

Mage:
Scorch
Firebolt

Warlock:
Howl of Terror
</details>
<details>
    <summary>18.05.2008 - Video 6 Warrior POV</summary>
https://www.youtube.com/watch?v=H1CSuikb1Cs

https://youtu.be/H1CSuikb1Cs?t=27 1

Priest:
Holy Fire

https://youtu.be/H1CSuikb1Cs?t=88 2

Tauren Racial Stomp

Warrior:
Sweeping Strikes
Commanding Shout

Priest:
Psychic Scream

https://youtu.be/H1CSuikb1Cs?t=162 3

Warrior:
Whirlwind

Mage:
Arcane Explosion
Blastwave
Dragon's Breath

https://youtu.be/H1CSuikb1Cs?t=229 4

Mage:
Molten Armor
Firebolt
Blizzard

Warrior:
Sweeping Strikes
Cleave
</details>
<details>
    <summary>23.08.2007 - Video 7 Warlock POV</summary>
https://www.youtube.com/watch?v=BWlWoz4heTg

https://youtu.be/BWlWoz4heTg?t=23 1

Warlock:
Incinerate
Searing Pain
Curse of Agony
Seed of Corruption

Druid:
Wrath

Paladin:
Holy Light
Avenging Wrath
Consecration

https://youtu.be/BWlWoz4heTg?t=98 2

Warlock:
Searing Pain
Howl of Terror
Rain of Fire

Druid:
Wrath

Paladin:
Consecration

Mage:
Frost Nova

https://youtu.be/BWlWoz4heTg?t=155 3

Warlock:
Incinerate
Incinerate
Howl of Terror

Mage:
Arcane Blast
Ice Lance

Paladin:
Consecration

Warrior:
Thunderclap

Druid:
Wrath

</details>
<details>
    <summary>09.10.2007 - Video 8 Mage POV</summary>
https://www.youtube.com/watch?v=SY2AUIYf15E

https://youtu.be/SY2AUIYf15E?t=25 1

Mage:
Pyroblast

Hunter:
Viper Sting
</details>
<details>
    <summary>08.07.2007 - Video 9 Paladin Tank POV</summary>
https://www.youtube.com/watch?v=PsHk3m0cbgU

https://youtu.be/PsHk3m0cbgU?t=33 1

Paladin Tank:
Avenger's Shield
Holy Shield

Warrior:
Rend

Priest:
Mass Dispell

https://youtu.be/PsHk3m0cbgU?t=65 2

Paladin:
Flash Heal
Consecration
Avenger's Shield

Priest:
Shadow Word: Death

Rogue:
Kick
</details>
<details>
    <summary>08.04.2007 + 29.10.2006 - Video Compilation</summary>
https://youtu.be/Mp9ptDNOT5A?t=39

Mage POV

Rogue:
Throw

Warrior:
Demo Shout

Mage:
Ice Barrier

https://www.youtube.com/watch?v=N4WrHPZhJO0

Warrior POV

Human Racial Perception

Warrior:
Rend
Demo Shout
Spell Reflection
Battle Shout
Shield Block
Last Stand

Hunter:
Explosive Trap
Multishot
Volley
Freezing Trap
Frost Trap
</details>

**Comment by The14me** [comment]
https://github.com/Atlantiss/AtlantissTBCBT/issues/2972

**Comment by Tenoutoften** [comment]
Since this issue is related to his MC ability Id like to point out two aspects I think are strange:
- Pets don't get MC but continue hacking away at the boss.
- If you Line of Sight your party members you don't do anything

**Comment by The14me** [comment]
The Duplicate issue was fixed a long time ago, but worth a check.
