### ISSUE TITLE
[Core][Spell] Damage from stealth not visible

### ISSUE THREAD

**Issue by Dusky1** [Atlantiss/NetherwingBugtracker#3543]
**Current behaviour**: When rogue attacks you from stealth, you dont see how much dmg you take (there is no info on your portrait, scrolling battle text and combat log). I mean only the first hit - for example Ambush, Eviscerate etc. directly from stealth.

**Expected behaviour**: You should see how much dmg u take on your portrait, scrolling battle text and combat log.

**Server Revision**: 
2462

**Comment by sadfx** [comment]
I actually observed this with mobs too, but it wasn't just the first attack.. some stealthed cat in Eversong hit me 5-6 times without destealthing and no attack was registered in the combat log.

**Comment by Evolvee** [comment]
delayed visibility system causes this

**Comment by The14me** [comment]
Rev.3472. Not an issue anymore.
Can be closed.
