### ISSUE TITLE
[core][spell] shoot wand on focus

### ISSUE THREAD

**Issue by Kaini27** [Atlantiss/NetherwingBugtracker#3544]
**Description**: Shooting wand on focus target has multiple bugs. Most likely connected with issue #2220

**Current behaviour**: 
1) Having friendly unit targeted in target and enemy unit as focus will lead to "interrupted" message at the end of the cast.
2) Having enemy unit in both target and focus will lead to casting "shoot" on target despite specifically casting it on focus. If manualy interrupted by /stopcasting many times and very fast- it can get through and start shooting on focus.
3) Not having anything in target and enemy unit as focus will lead to "shoot" being caster properly on focus target for first time, but upon switching focus target it will continue to shoot on first target no matter if you stoped casting, cleared focus completely before setting new one or switched it many times. To force it being casted on proper focus target player needs to acquire new target and clear it or do the stopcasting trick that was described before.

**Expected behaviour**: Shooting wand on focus should simply shoot wand on focus despite of target status.

**Server Revision**: 2462

**Comment by Doppelmoral** [comment]
Same as #3562, didn't see your report when I made mine but suppose same problem.

**Comment by towneh** [comment]
http://wowwiki.wikia.com/wiki/Multiboxing_macros?oldid=1307926 has a macro for wanding your focus target for multiboxing:
/assist focus 
/cast [harm] shoot; 
It seems like you cannot wand the focus target directly, but you have to assist it to bring it up as your actual target first.

**Comment by towneh** [comment]
Should work the same way as hunter auto shot in regards to focus and mouseover targetting

**Comment by The14me** [comment]
Rev.3472 not an issue anymore.
Can be closed.
