### ISSUE TITLE
[Quest][Blackrock Menace]

### ISSUE THREAD

**Issue by Ensipidx** [Atlantiss/NetherwingBugtracker#3546]
**Description**: Only certain orcs in Redridge drop the axes for Blackrock Menance.

**Current behaviour**: Only blackrock mobs around 19-21 (outrunners/grunts) seemingly drop the Battleworn Axes for Blackrock Menance. 

**Expected behaviour**: Blackrock Champions at the very least, but likely all orcs, should drop the Battleworn Axe.

https://www.wowhead.com/quest=20/blackrock-menace#comments:id=298488:reply=337613
https://www.wowhead.com/quest=20/blackrock-menace#comments:id=304479

Both speak of Blackrock Champions dropping the axes, but it is likely the old elites (in the ruined castle at Stonewatch) should drop them as well.

Since this quest is a preq to the Stonewatch elites most people would have the quest done before killing the mobs there, so I think old drop % data on thottbot it skewed as people killing them no longer have the ability to see the axe as loot (similar reasoning with Champions and mobs up in the north cave).

**Server Revision**: 2462

**Comment by Tenoutoften** [comment]
http://web.archive.org/web/20080915191512/http://thottbot.com:80/i3014
![](https://i.gyazo.com/87f942008038799c8ca96555e97de845.png)
Earlier versions on thottbot gives percentages down to ~1.5% which is obviously wrong.

**Comment by Shanghi** [comment]
This and all other similar cases should be fixed in revision 2481.
