### ISSUE TITLE
[Item]Eye of Magtheridon does not work

### ISSUE THREAD

**Issue by ircfelix** [Atlantiss/NetherwingBugtracker#3547]
**Description**: 
According to it's tooltip and https://de.wowhead.com/item=28789, this trinket should proc from full resists. Just for clarification, this item should **not** proc from partial resists.

**Current behaviour**:
Eye of Magtheridon does not proc from full resists.

**Expected behaviour**: 
Eye of Magtheridon should proc from full resists.

**Server Revision**: 
2462

**Comment by BezawitNW** [comment]
Trinket seems to be working for me.

**Comment by ircfelix** [comment]
Maybe since the latest patch?

**Comment by Manaci** [comment]
Fixed
