### ISSUE TITLE
[Item] Set Crystalforge Raiment

### ISSUE THREAD

**Issue by H4Xx0R-PC** [Atlantiss/NetherwingBugtracker#3551]
[//]: # (Enclose links to things related to the bug using http://wowhead.com or any other TBC database.)
[//]: # (You can use screenshot ingame to visual the issue.)
[//]: # (Write your tickets according to the format:)
[//]: # ([Quest][Azuremyst Isle] Red Snapper - Very Tasty!)
[//]: # ([NPC] Magistrix Erona)
[//]: # ([Spell][Mage] Fireball)
[//]: # ([Npc][Drop] Ghostclaw Lynx)
[//]: # ([Web] Armory doesnt work)
[//]: # (To find server revision type `.server info` command in the game chat.)

**Description**: 
The set bonuses are incorrect. According to http://web.archive.org/web/20071011010054/http://elitistjerks.com:80/f31/t15513-paladin_healing_efficiency/ http://web.archive.org/web/20070510051509/http://thottbot.com:80/i30138 and https://web.archive.org/web/20070506035707/http://wow.allakhazam.com:80/db/item.html?witem=30138 the bonuses are supposed to be (2): Increases the armor granted by your Devotion Aura ability by 350. and (4): Reduces the casting time of your Holy Light spell by 0.25.2 sec.
**Current behaviour**:
The current set bonuses are:
(2) : Each time you cast a Judgment, your party members gain 50 mana.
(4): Your critical heals from Flash of Light and Holy Light reduce the cast time of your next Holy Light or Flash of Light spell by 0.50 sec for 10 sec. This effect cannot occur more than once per minute.
**Expected behaviour**: 
The set bonuses are supposed to be:
(2): Increases the armor granted by your Devotion Aura ability by 350.
(4): Reduces the casting time of your Holy Light spell by 0.25.2 sec.
**Server Revision**: 
2462

**Comment by Tenoutoften** [comment]
What does "...by 0.25.2 sec." mean?
On thottbot 10th of may 2007 this bonus is simply
"Reduces the cast time of your Holy Light by 0.2 sec"

---

Anyway, notice how the spellID for Judgement/Devotion Aura is #37188
The updated/old holy light is #37189

This means this change can't be done without client change right? So it wont be done

**Comment by Manaci** [comment]
Irrelevant now
