### ISSUE TITLE
Hit rating gems

### ISSUE THREAD

**Issue by skebre** [Atlantiss/NetherwingBugtracker#3552]
[//]: # (Enclose links to things related to the bug using http://wowhead.com or any other TBC database.)
[//]: # (You can use screenshot ingame to visual the issue.)
[//]: # (Write your tickets according to the format:)
[//]: # ([Quest][Azuremyst Isle] Red Snapper - Very Tasty!)
[//]: # ([NPC] Magistrix Erona)
[//]: # ([Spell][Mage] Fireball)
[//]: # ([Npc][Drop] Ghostclaw Lynx)
[//]: # ([Web] Armory doesnt work)
[//]: # (To find server revision type `.server info` command in the game chat.)

**Description**: 
Gemming items with yellow hit rating gems seems to not give me hit rating.
**Current behaviour**:
Enchants with hit rating, and gear with hit rating work fine for me. But gems with hit rating even though inserted in to gear and equiped do not give any hit rating at all.
**Expected behaviour**: 
They should add hit rating to my character.
**Server Revision**:

**Comment by killablink** [comment]
Hit rating gems are for melee hit rating and not spell hit

**Comment by skebre** [comment]
Haha, whoah that makes me look stupid. I wanted to log the beta and help out, but looks like my wrath experience doesn't matter that much here x)
