### ISSUE TITLE
[NPC] Toad critters in Teldrassil give a small amount of XP.

### ISSUE THREAD

**Issue by Gniddikon** [Atlantiss/NetherwingBugtracker#3553]
**Description**:  The level 1 critter toads in Teldrassil give 8 XP to my level 2 druid.

**Current behaviour**: The level 1 critter toads in Teldrassil give 8 XP to my level 2 druid.

**Expected behaviour**: Critters should not yield XP.

**Server Revision**: 2462

I want to add that it's apparently **only** the toads, other critters in the starting area do not yield XP.

**Comment by Wolffenstein** [comment]
Fixed in rev 2472.
