### ISSUE TITLE
[NPC] Reach of Risen Stalker/Zombies Seems Off

### ISSUE THREAD

**Issue by OMEGALULW** [Atlantiss/NetherwingBugtracker#3554]
https://i.imgur.com/e5aSrhP.png
![image](https://user-images.githubusercontent.com/21988932/50310386-21cff280-04a2-11e9-9c22-95241c6a2368.png)

![image](https://user-images.githubusercontent.com/21988932/50310371-18468a80-04a2-11e9-9085-fac7f8771489.png)

**Description**: Mob attacks from very far away

**Current behaviour**: Attacks from farther away than all other mobs I've run into

**Expected behaviour**: not that :D 

**Server Revision**: 2462

**Comment by Manaci** [comment]
Fixed
