### ISSUE TITLE
[Engineering]Goblin Land Mine damage

### ISSUE THREAD

**Issue by Fenvarien1** [Atlantiss/NetherwingBugtracker#3555]
**Description**: 
https://www.wowhead.com/item=4395/goblin-land-mine

Goblin Land Mine dealing more damage than the tooltip.

**Current behaviour**:
 It is damage on two mobs not like Blood Furnace double procc.
![unbenannt](https://user-images.githubusercontent.com/44606340/50314562-8e9db980-04af-11e9-91da-2249231e5b24.jpg)
Enemy: http://db.hellfire-tbc.com/?npc=16973
Name: Bonestripper Vulture
Level: 61-62
**Expected behaviour**: 
![unbenannt](https://user-images.githubusercontent.com/44606340/50314676-0ec41f00-04b0-11e9-89a4-33f84122cc10.jpg)

**Server Revision**: 
2462

**Comment by torrenzGH** [comment]
seems to be in this state still in rev 2745
![wowscrnshot_013119_000300](https://user-images.githubusercontent.com/45742182/52129245-55707180-2637-11e9-8bb4-8beb97a0d83a.jpg)

**Comment by The14me** [comment]
rev.3472 Not an issue anymore.
https://i.imgur.com/Wwaumcg.png
Can be closed.
