### ISSUE TITLE
[Hunter][Spell] Flare & spell delay

### ISSUE THREAD

**Issue by Zarant** [Atlantiss/NetherwingBugtracker#3557]
The flare debuff doesn't seem to behave the same way it did back on retail, in regards to delayed debuff application. I feel like it's significantly more difficult to sprint or shadowstep into a flare, It might be a latency issue on my end, but it's worth sharing the research anyway.

Source:
First of all I'm gonna link this clip from retail TBC: https://youtu.be/hS82JzE6F0I?t=486
On this clip you can see a druid sprinting inside a hunter's flare. You have to break it down frame by frame to understand all the nuances, keeping in mind that this video was recorded at 30 fps, so each frame lasts 0.333 seconds.

Once the druid runs into the flare, he manages to cast pounce, the animation goes off and nothing happens. 9 frames later (~0.300 seconds) he loses the stealth buff and get put in combat. 14 frames later (~0.467 seconds), he is affected by the flare debuff and the hunter is affected by the pounce debuff.

On this same video: https://youtu.be/hS82JzE6F0I?t=414
The druid gets revealed by flare and it takes about ~20 frames to reveal him (~0.667 seconds)

As you can see, It takes at least 2 batches of 400ms to get affected by the flare debuff. Maybe the game checks if you're inside every 400ms and then you get the debuff on the next batch.

**Comment by Evolvee** [comment]
yes, either wolf fixed it badly again or the spell delay is fucked up(which it is) and causing this problem

**Comment by Peglaa** [comment]
I don't think the flare fix is live yet so wait till it's updated then retest.
