### ISSUE TITLE
[Dungeons][General] The hourly instance lock is reset by relogging

### ISSUE THREAD

**Issue by itsjojotbh** [Atlantiss/NetherwingBugtracker#3558]
[//]: # (Enclose links to things related to the bug using http://wowhead.com or any other TBC database.)
[//]: # (You can use screenshot ingame to visual the issue.)
[//]: # (Write your tickets according to the format:)
[//]: # ([Quest][Azuremyst Isle] Red Snapper - Very Tasty!)
[//]: # ([NPC] Magistrix Erona)
[//]: # ([Spell][Mage] Fireball)
[//]: # ([Npc][Drop] Ghostclaw Lynx)
[//]: # ([Web] Armory doesnt work)
[//]: # (To find server revision type `.server info` command in the game chat.)

**Description**: 
Like the title says, the hourly limit of 5 instances will reset by relogging your character.
**Current behaviour**:
After resetting an instance 5 times and being locked out from entering an instance, you can simply relog to reset it.
Some evidence: https://imgur.com/a/oY4T6vQ second picture is taken 1m30s after the first one where the instance is locked, and after a relog I could enter back into the dungeon
**Expected behaviour**: 
The instance lock is supposed to last for 1 hour from the first instance opened.
**Server Revision**: 
2462

**Comment by Wolffenstein** [comment]
Fixed in rev 2576.
