### ISSUE TITLE
Player sitting / standing and casting

### ISSUE THREAD

**Issue by mikefirefly** [Atlantiss/NetherwingBugtracker#356]
[//]: # (Enclose links to things related to the bug using http://wowhead.com or any other TBC database.)
[//]: # (You can use screenshot ingame to visual the issue.)
[//]: # (Write your tickets according to the format:)
[//]: # ([Quest][Azuremyst Isle] Red Snapper - Very Tasty!)
[//]: # ([NPC] Magistrix Erona)
[//]: # ([Spell][Mage] Fireball)
[//]: # ([Npc][Drop] Ghostclaw Lynx)
[//]: # ([Web] Armory doesnt work)

**Description**: 
Player sit / stand and casting.

**Current behaviour**:
Sit, cast hearthstone. Player doesn't stand up and when the cast is finished, he appears in the destination still sitting.

**Expected behaviour**: 
Not sure how it was on retail but AFAIR the player should appear standing up in the destination at least.

**Server Revision**:

**Comment by SwiftieTBC** [comment]
2 quotes from WowWiki
"Sitting while in combat immediately stops auto-attacks, but not spell-casting."
"As of Patch 2.3, if you are seated and try to use abilities that require you to be standing, you will stand up and use them. This can be disabled with: /console autoStand 0"

Examples in modern retail 
https://www.reddit.com/r/wow/comments/4y6lpw/casting_hearthstone_while_sitting_makes_your/

Quote from wowhead
"By Nekroradai (2,602 –  2·26)  on 2007/08/25 (Patch 2.1.3) 
You can also sit or sleep and use your hearthstone at the same time."

I agree that at the end of the cast the animation should be played and the player arrives standing though

**Comment by AugustDay** [comment]
Couple notes to add to this issue. You can sit down, drink, cast hearthstone, and not only will you not stand up, but the drinking will continue unabated. I've attached a cropped screenshot of this in action: 
![cropped](https://user-images.githubusercontent.com/4572133/46188789-16ed3380-c2a0-11e8-9fce-29051432f2ff.jpg)
As you can see, my character is halfway through drinking and casting Hearthstone at the same time. Should casting Hearth interrupt drinking?

**Comment by Wolffenstein** [comment]
SPELL_ATTR0_CASTABLE_WHILE_SITTING
