### ISSUE TITLE
[Class][Hunter][Spell] Revive Pet works when you do not have an active pet

### ISSUE THREAD

**Issue by towneh** [Atlantiss/NetherwingBugtracker#3560]
**Description**: 
You are able to successfully cast Revive Pet and incur mana loss when you do not have an active pet. In my case I attempted this after my pet ran away, but it also works when your pet is stabled.

**Current behaviour**:
Revive Pet works without an active pet.

**Expected behaviour**: 
http://wowwiki.wikia.com/wiki/Revive_Pet?oldid=1423686
"Limitations
Pet must have died"

You should receive the error message "You do not have a pet"

**Server Revision**:

**Comment by Tenoutoften** [comment]
If you have your pet dismissed you can resummon it by Revive pet, even though your pet is still alive

**Comment by Tenoutoften** [comment]
https://github.com/Atlantiss/NetherwingBugtracker/issues/1167

**Comment by Neophrone** [comment]
Still exists in-game. Karazhan PTR.

**Comment by Wolffenstein** [comment]
Fixed in rev 3424.
