### ISSUE TITLE
[Hunter][Spell] Frost trap & slow stacking mechanics

### ISSUE THREAD

**Issue by Zarant** [Atlantiss/NetherwingBugtracker#3561]
Frost trap debuff should follow the same slow stacking rules applied to most slow effects in the game.

Source: 
https://youtu.be/4jbSgaPROH0?t=217 - Mage gets hit by wing clip and run into a frost trap, wing clip gets overwritten by the frost trap debuff. Both slows are 60% slows.

https://youtu.be/0iuR6CwL9rc?t=23 - You can see both concussive shot and frost trap being applied at the same time. Although concussive shot is a 50% slow, it's also a hybrid spell, since the daze component affects steady shot damage.

https://youtu.be/0iuR6CwL9rc?t=12 - Both wing clip and frost trap are active on the same target, however, wing clip has a longer duration.

Server revision: 2462

**Comment by Evolvee** [comment]
aura stacking is disabled right now

**Comment by Manaci** [comment]
Fixed in rev 3214
