### ISSUE TITLE
[Spell][Macro]Mouseover & Shoot

### ISSUE THREAD

**Issue by Doppelmoral** [Atlantiss/NetherwingBugtracker#3562]
[//]: # (Enclose links to things related to the bug using http://wowhead.com or any other TBC database.)
[//]: # (You can use screenshot ingame to visual the issue.)
[//]: # (Write your tickets according to the format:)
[//]: # ([Quest][Azuremyst Isle] Red Snapper - Very Tasty!)
[//]: # ([NPC] Magistrix Erona)
[//]: # ([Spell][Mage] Fireball)
[//]: # ([Npc][Drop] Ghostclaw Lynx)
[//]: # ([Web] Armory doesnt work)
[//]: # (To find server revision type `.server info` command in the game chat.)

**Description**: 
mouseover macros are not working as intended with shoot (wand)
**Current behaviour**:
https://streamable.com/3iupf
I can wand a target A via mouseover, but when attempting to wand target B, C etc. the attack will either go on the first attacked target OR not go off at all ("interrupted")
Note how in the video at ~0:58 after Immolating all dummies and mouseover wand them successfully, I target the friendly player character and again am unable to mouseover-shoot while still able to mouseover-immo
**Expected behaviour**: 
As long as a mouseover target exists that meets the conditions, no matter what I attacked previously or am currently targetting, it should shoot. Btw I also tried different macros, behaviour is the same. http://www.arenajunkies.com/topic/165876-wand-macro/
**Server Revision**: 2462

Macros I've tested with multiple spells and Shoot:
1) /cast [target=mouseover,exists,harm] Shoot; [target=target,exists,harm] Shoot
2) /cast [target=mouseover, exists, harm] Shoot
   /cast [target=target, exists, harm] Shoot

**Comment by The14me** [comment]
Rev.3472 not an issue anymore. Fixed with wand/auto-attack target rework.
Can be closed.
