### ISSUE TITLE
[NPC] Forsaken Raider

### ISSUE THREAD

**Issue by Ahmpy** [Atlantiss/NetherwingBugtracker#3563]
[//]: # (Enclose links to things related to the bug using http://wowhead.com or any other TBC database.)
[//]: # (You can use screenshot ingame to visual the issue.)
[//]: # (Write your tickets according to the format:)
[//]: # ([Quest][Azuremyst Isle] Red Snapper - Very Tasty!)
[//]: # ([NPC] Magistrix Erona)
[//]: # ([Spell][Mage] Fireball)
[//]: # ([Npc][Drop] Ghostclaw Lynx)
[//]: # ([Web] Armory doesnt work)
[//]: # (To find server revision type `.server info` command in the game chat.)

**Description**: Spamming vanish ability when chasing player and are untargetable until they reset at which point they seem to act normally

https://www.youtube.com/watch?v=xN9Lnr_Vv7A

**Server Revision**: 2462

**Comment by Drayo** [comment]
Issue is still present. 

After resetting them once they seem to work fine.

**Comment by The14me** [comment]
It may be related to a bigger problem with mobs acting strangely after restart/crash before first pull.

**Comment by Wolffenstein** [comment]
Fixed in rev 3475.
