### ISSUE TITLE
[NPC] Gan'arg Analyzer

### ISSUE THREAD

**Issue by RealZwox** [Atlantiss/NetherwingBugtracker#3564]
Current:
On the south Apexis Monument at  27.4/68.6 is one Gan'arg Analyzer missing
On Both 27.4 / 68.6 and 31.8 / 63.8 is the mob placement wrong.

Expected behaviour:

One Gan'arg Analyzer should stay on each Apexis Relic and 2 Gan'arg Analyzer should stay on the Platform of the Apexis Monument

https://youtu.be/d7_SSrx559w?t=25

The Gan'arg Analyzer on the Apexis Relic should sometimes look like he is working on that Apexis Relic good to see at https://youtu.be/d7_SSrx559w?t=52

rev 2462

**Comment by RealZwox** [comment]
Can be closed cause this NPC'S should not be there pre 2.1

**Comment by wtRCH** [comment]
@aresbrutus

**Comment by aresbrutus** [comment]
Fixed in rev `Nariman`
