### ISSUE TITLE
[Spell][Warrior] Whirlwind

### ISSUE THREAD

**Issue by trueodra** [Atlantiss/NetherwingBugtracker#3565]
[//]: # (Enclose links to things related to the bug using http://wowhead.com or any other TBC database.)
[//]: # (You can use screenshot ingame to visual the issue.)
[//]: # (Write your tickets according to the format:)
[//]: # ([Quest][Azuremyst Isle] Red Snapper - Very Tasty!)
[//]: # ([NPC] Magistrix Erona)
[//]: # ([Spell][Mage] Fireball)
[//]: # ([Npc][Drop] Ghostclaw Lynx)
[//]: # ([Web] Armory doesnt work)
[//]: # (To find server revision type `.server info` command in the game chat.)

**Description**: 
Whirlwind spell critical strikes.

**Current behaviour**:
Whirlwind http://db.deathside.ru/?spell=1680 crits sometimes don't add Deep Wounds http://db.deathside.ru/?spell=12867 + Blood Frenzy http://db.deathside.ru/?spell=29859 effects on target which got crit.
https://www.youtube.com/watch?v=PWdma9aSPf8  0:12

**Expected behaviour**: 
Whirlwind crits should add Deep Wounds+Blood Frenzy always.
Proof: https://www.youtube.com/watch?v=3rbd02jJXy8  5:29

**Server Revision**: 
2462

**Comment by Brasso** [comment]
Critting an NPC or player behind you doesn't give you on crit effects, such as flurry or deep wounds. Repeatable.

**Comment by Evolvee** [comment]
dont test mechanics on dummies pls

**Comment by trueodra** [comment]
https://youtu.be/0NNf-w6y2_4
it does not work with mobs too

**Comment by Tereneckla** [comment]
Fixed
