### ISSUE TITLE
[Talent][Warrior] Flurry

### ISSUE THREAD

**Issue by trueodra** [Atlantiss/NetherwingBugtracker#3566]
[//]: # (Enclose links to things related to the bug using http://wowhead.com or any other TBC database.)
[//]: # (You can use screenshot ingame to visual the issue.)
[//]: # (Write your tickets according to the format:)
[//]: # ([Quest][Azuremyst Isle] Red Snapper - Very Tasty!)
[//]: # ([NPC] Magistrix Erona)
[//]: # ([Spell][Mage] Fireball)
[//]: # ([Npc][Drop] Ghostclaw Lynx)
[//]: # ([Web] Armory doesnt work)
[//]: # (To find server revision type `.server info` command in the game chat.)

**Description**: 
Whirldwind critical strikes and Flurry.

**Current behaviour**:
Whirlwind http://db.deathside.ru/?spell=1680 crits don't add Flurry http://db.deathside.ru/?spell=16284 (or http://db.deathside.ru/?spell=12974) to player.
https://www.youtube.com/watch?v=PWdma9aSPf8

**Expected behaviour**: 
Every whirlwind crit should add Flurry effect.
Proof: https://www.youtube.com/watch?v=3rbd02jJXy8&t=349s  7:39

**Server Revision**: 
2462

**Comment by Brasso** [comment]
You gain flurry buff after critting correctly? I think you are confusing what is happening in that retail video. The flurry you see there is the enemy warrior's own flurry, he is fighting another warrior.

**Comment by trueodra** [comment]
it does not work with mobs too
https://youtu.be/0NNf-w6y2_4

**Comment by Saben65** [comment]
Perhaps related: https://github.com/Atlantiss/NetherwingBugtracker/issues/3477

**Comment by Tereneckla** [comment]
Fixed
