### ISSUE TITLE
[Dungeon][Blackrock Depths] Arena boss does not automatically engage player

### ISSUE THREAD

**Issue by Jseay1313** [Atlantiss/NetherwingBugtracker#3569]
**Current behaviour**:The Arena boss is currently not running into the room when spawned and engaging the player

**Expected behaviour**: The Arena boss should run into the ring of law and automatically engage the group in the room

**Server Revision**: 2478

**Comment by Brasso** [comment]
Proof?

**Comment by Jseay1313** [comment]
Are you asking for proof as in you want proof of him not engaging me or you want proof that he should engage me instead of sitting in the tunnel doing nothing, it's not even running out into the arena agro aside.

**Comment by Jseay1313** [comment]
https://youtu.be/w965TeVu56w?t=224 there you go either way
https://youtu.be/x2wGkRziPOA?t=72
https://www.youtube.com/watch?v=Ui_nZY_sBUk

**Comment by Brasso** [comment]
I missed the part where you said he didn't run in to the room at all, obviously that's a bug. What I meant is if he should auto aggro the group in the room without them engaging him.

**Comment by Tereneckla** [comment]
Fixed
