### ISSUE TITLE
Invading Rotlimb Cannibal Clustered

### ISSUE THREAD

**Issue by ttghnw** [Atlantiss/NetherwingBugtracker#357]
[//]: # (Enclose links to things related to the bug using http://wowhead.com or any other TBC database.)
[//]: # (You can use screenshot ingame to visual the issue.)
[//]: # (Write your tickets according to the format:)
[//]: # ([Quest][Azuremyst Isle] Red Snapper - Very Tasty!)
[//]: # ([NPC] Magistrix Erona)
[//]: # ([Spell][Mage] Fireball)
[//]: # ([Npc][Drop] Ghostclaw Lynx)
[//]: # ([Web] Armory doesnt work)

**Description**: and **Current behaviour**:
The rotlimb cannibal packs that are scripted to attack fairbreeze village are crumped/clustered upon each other to the inexperienced eye it would be enough to seem like 3 mobs instead of 9.
**Expected behaviour**: 
The mobs shouldn't occupy the same position but have a natural spread
![wowscrnshot_092418_110622](https://user-images.githubusercontent.com/43508698/45946887-2cd1ce80-bfea-11e8-8224-b7b67d5bf3fe.jpg)
![wowscrnshot_092418_110624](https://user-images.githubusercontent.com/43508698/45946888-2cd1ce80-bfea-11e8-837b-0e8d901b7416.jpg)
![wowscrnshot_092418_110626](https://user-images.githubusercontent.com/43508698/45946890-2d6a6500-bfea-11e8-8df1-97fac70e5722.jpg)

**Server Revision**:

**Comment by huntdfl** [comment]
Just ran into this pack, they roamed from North east of fairbreeze village and were running through the ground/walking up+over trees that were in their pathing.

**Comment by aresbrutus** [comment]
https://i.imgur.com/qbrtMDF.jpg

Works fine for me. Probably related to the invasion script.

**Comment by Wolffenstein** [comment]
Fixed in rev 3139.
