### ISSUE TITLE
[NPC] Blade's Edge Mountains - Post 2.1 NPC'S

### ISSUE THREAD

**Issue by RealZwox** [Atlantiss/NetherwingBugtracker#3572]
The follow NPC'S needs to be removed:
https://wow.gamepedia.com/Gan%27arg_Analyzer / https://www.wowhead.com/npc=23385/simon-unit
https://wow.gamepedia.com/Wrath_Hound / https://www.wowhead.com/npc=20557/wrath-hound
https://wow.gamepedia.com/Furnace_Guard / https://www.wowhead.com/npc=22291/furnace-guard

**Comment by RealZwox** [comment]
https://web.archive.org/web/20070510064913/http://wow.allakhazam.com:80/dyn/mobs/zone114.html
https://web.archive.org/web/20070623022524/http://wow.allakhazam.com:80/dyn/mobs/zone114.html

this are 2 snapshots of the npc list in blade edge's. The first 10.05.2007 and the second one 26.06.2007. Patch 2.1 got released at 15.05.2007.
There is no "Legion Flak Cannon" on the first snapshot but on the second after the release of 2.1 its there.

**Comment by wtRCH** [comment]
@aresbrutus

**Comment by aresbrutus** [comment]
Fixed in rev `Nariman`
