### ISSUE TITLE
[Raid][Karazhan][Spell] Shade of Aran's Flame Wreath triggers on minions such as Shadowfiend

### ISSUE THREAD

**Issue by Diseal** [Atlantiss/NetherwingBugtracker#3573]
_**Edit:** This may be a no-op. @Drayo linked patch notes for 2.1.0 that says this was fixed then, so to maintain pre-nerf Karazhan, it makes sense that it wouldn't be fixed yet._

**Description**: 
Flame Wreath is triggering when a pet moves through it

**Current behaviour**:
Flame Wreath is triggering when a pet moves through it

**Expected behaviour**: 
Flame Wreath should not trigger 
https://wow.gamepedia.com/Shade_of_Aran

> The following do not trigger the effect:
> 
> Spell casting
> Moving around inside the rings
> Moving around outside the rings
> Turning resulting from a spell cast (such as  [Mind Flay],  [Steady Shot] or  [Whirlwind])
> Immunity/removal effects such as  [Divine Shield] or  [Cloak of Shadows] (these did initially trigger the effect)
> Pets
> Companions

**Server Revision**: 
2478? (copied from another ticket 2 hours ago)

**Proof**:
Note "X's Minion's Explosion"
![first](https://i.imgur.com/j6raEuR.jpg)
![second](https://i.imgur.com/4Lm4I9D.jpg)

**Comment by Drayo** [comment]
https://wow.gamepedia.com/Patch_2.1.0

> Shade of Aran's Flame Wreath should completely ignore pets, summons, guardians and mind-controlled NPCs.

I don't like it much either, just feels clunky and frustrating, but I guess it part of pre-nerf Aran?

**Comment by Brasso** [comment]
#2853 Might be interesting to read.

**Comment by Diseal** [comment]
Ah, good catch @Drayo 

never mind!

**Comment by Wolffenstein** [comment]
It is intended.
