### ISSUE TITLE
[NPC]Shienor Sorcerer doesn't have Power of Kran'aish

### ISSUE THREAD

**Issue by Tuwz** [Atlantiss/NetherwingBugtracker#3574]
**Description**: Shienor Sorcerer doesn't have his abilities scripted.

**Current behaviour**: Shienor Sorcerer  (npc=18450) doesn't have his abilities, especially Power of Kran'aish.
![image](https://user-images.githubusercontent.com/45247502/50367669-2075f700-0582-11e9-984a-cc58e50d546e.png)

**Expected behaviour**: You should be able to Mind Control him and use it on yourself and all allies nearby according to the earliest comment found on Wowhead.
![image](https://user-images.githubusercontent.com/45247502/50367691-384d7b00-0582-11e9-96f4-9fa1c36f0982.png)
https://www.wowhead.com/npc=18450/shienor-sorcerer#comments

**Server Revision**: 2462

**Comment by The14me** [comment]
Rev.3472 still an issue.
https://www.wowhead.com/spell=32924/power-of-kranaish#comments:id=94120
Spell ID 32924 that missing from MC tab.

**Comment by Wolffenstein** [comment]
Fixed in rev 3475.
