### ISSUE TITLE
[Spells] Spellcast leeway for players isn't working

### ISSUE THREAD

**Issue by somnu** [Atlantiss/NetherwingBugtracker#3575]
**Description**: 
I know this issue has been opened in the past, but all I could find are closed reports,  so I am reopening it.

**Current behaviour**:
If you begin casting a spell at a target that is standing at max range, the target can make your spell say "out of range" by simply walking 1 yard away from you.

**Expected behaviour**: 
There should be a leeway of a couple of yards before the spellcast returns an "out of range" error message.

**Server Revision**: 
2462

**Comment by killablink** [comment]
#121
