### ISSUE TITLE
Mobs not evading when they should.

### ISSUE THREAD

**Issue by Bravehurt** [Atlantiss/NetherwingBugtracker#3576]
[//]: # (Enclose links to things related to the bug using http://wowhead.com or any other TBC database.)
[//]: # (You can use screenshot ingame to visual the issue.)
[//]: # (Write your tickets according to the format:)
[//]: # ([Quest][Azuremyst Isle] Red Snapper - Very Tasty!)
[//]: # ([NPC] Magistrix Erona)
[//]: # ([Spell][Mage] Fireball)
[//]: # ([Npc][Drop] Ghostclaw Lynx)
[//]: # ([Web] Armory doesnt work)
[//]: # (To find server revision type `.server info` command in the game chat.)

**Description**: When a player is unreachable to the mobs, he should be in an idle state with perma evasion, but he's still attackable
![wowscrnshot_122118_201150](https://user-images.githubusercontent.com/46060170/50369056-bea39600-055d-11e9-8b92-4eea72ca06df.jpg)

**Current behaviour**: Can damage mobs when they are in the idle "no pathing" state

**Expected behaviour**: Mobs evade everyspell/attack/aoe when in the "no pathing" idle state

**Server Revision**:

**Comment by Wolffenstein** [comment]
They do evade when they cannot find the path. If they didn't that means they were able to create one (albeit quite wrong). Could you manage to record how you did that?

**Comment by Bravehurt** [comment]
Sorry for the piss poor quality, downloaded free software on the go
https://streamable.com/itwps

**Comment by Brasso** [comment]
That is some piss poor quality indeed. If you have an nvidia gpu you have shadowplay already installed with Geforce experience, alt + z by default. :)

**Comment by leeviathan** [comment]
I can confirm this is happening. I was able to kill a fel reaver by standing out of reach and it didn't evade. I don't know how to reproduce it, it seems kind of random; like it'll start to evade and then go back to being damageable if you move around a bit (or maybe moving around has nothing to do with it)

**Comment by Wolffenstein** [comment]
Fixed in rev 3198.
