### ISSUE TITLE
Randomly leaving channel

### ISSUE THREAD

**Issue by SweN1997** [Atlantiss/NetherwingBugtracker#358]
Leveling up to 2 made me auto-leave the looking for group channel . 
https://imgur.com/a/ZCO6ViR

**Comment by Sinyr** [comment]
I've noticed those random "joined LFG channel" messages once per hour or 2. Happened at the exact same moment to my leveling buddy as well. We weren't doing anything specific, just killing mobs and stuff.

**Comment by Manaci** [comment]
Fixed
