### ISSUE TITLE
Warlock Succubus pet

### ISSUE THREAD

**Issue by h03m03** [Atlantiss/NetherwingBugtracker#3580]
[//]: # (Enclose links to things related to the bug using http://wowhead.com or any other TBC database.)
[//]: # (You can use screenshot ingame to visual the issue.)
[//]: # (Write your tickets according to the format:)
[//]: # ([Quest][Azuremyst Isle] Red Snapper - Very Tasty!)
[//]: # ([NPC] Magistrix Erona)
[//]: # ([Spell][Mage] Fireball)
[//]: # ([Npc][Drop] Ghostclaw Lynx)
[//]: # ([Web] Armory doesnt work)
[//]: # (To find server revision type `.server info` command in the game chat.)

**Description**: 
Using Succubus Charm ability when succubus invisibility spell toggled on makes her bug out and shift in and out of invis without actually casting the Charm spell. Have to disable her invis to be able to use Charm.
**Current behaviour**:
Cast charm with succubus pet but doesn't cast it unless u toggle of the auto-cast of invisibility.
**Expected behaviour**: 
Leaving her invis when you use her Charm without having to de-toggle her invis.
**Server Revision**: 
latest.

**Comment by Tereneckla** [comment]
Fixed
