### ISSUE TITLE
[Shaman] Windfury OH crits do not proc special effects (MH does proc)

### ISSUE THREAD

**Issue by pesky89** [Atlantiss/NetherwingBugtracker#3582]
**Description**: 
There are currently two opened issues regarding WF crits not proccing special effects:  

- https://github.com/Atlantiss/NetherwingBugtracker/issues/3193  [Shaman] windfury crits do not proc special effects
- https://github.com/Atlantiss/NetherwingBugtracker/issues/1951  [Shaman] "Windfury weapon" procs not identified as a melee attack?

but seems to be **partially fixed**.  

**Current behaviour**:  
Windfury offhand critical hits do not proc special effects, while mainhand critical hits proc them.
MH:  
![mainhand](https://user-images.githubusercontent.com/26849796/50371991-81c3b780-05ce-11e9-9202-629e591a0a66.png)  
OH:  
![offhand](https://user-images.githubusercontent.com/26849796/50371992-81c3b780-05ce-11e9-8eba-8b66368716af.png)  

**Expected behaviour**:  
Both windfury critical hits should proc special effects
**Server Revision**:

**Comment by Brasso** [comment]
Paraphrasing Evolve "Don't test class mechanics on dummies". Test on real mobs to confirm this.

**Comment by pesky89** [comment]
Tested on mobs from Terokkar Forest and the issue is confirmed. WF OH crits didnt proc special effects

**Comment by pesky89** [comment]
@wtRCH hi! Do you need additional logs? Cause the status should be Confirmed. Thank you!

**Comment by Orphid** [comment]
Having the same issue, wondering if there's any progress on this issue. WF in OH is quite a dps loss at the moment as it steals your windfury procs but doesn't give you the benefits.

**Comment by kiraleos** [comment]
This still is bugged. I tested it today and is quite easy to reproduce. 
I'm using windfury only on my OH: 

![alt text](https://i.imgur.com/NQdNrpa.png)

**Comment by Wolffenstein** [comment]
Fixed
