### ISSUE TITLE
[Professions]Unlearn this profession cause visual bug

### ISSUE THREAD

**Issue by Fenvarien1** [Atlantiss/NetherwingBugtracker#3583]
**Description**: 
Unlearn this profession cause visual bug for the trainers. 

**Current behaviour**:
After pressing the Unlearn button the patterns get flagged as green(skill achieved) instead of red(missing skill).

**But you are not able to learn them either way.**

If you close the trainer menu and talk to him again the bug is gone.
[WebM link to gfycat.com](https://gfycat.com/SpiffyComfortableHydatidtapeworm)
- Blacksmith
- Alchemy
- Mining

3/3 tested profressions now got the same bug. i assume it is a general bug and don't test the rest.

**Expected behaviour**: 
The trainer menu remains red if you don't have the skill.

**Server Revision**: 
2483

**Comment by The14me** [comment]
rev.3472. Still an issue.

**Comment by Wolffenstein** [comment]
Fixed in rev 3475.
