### ISSUE TITLE
[NPC][Azuremyst Isle] Slight typo for Totem of Vark RP

### ISSUE THREAD

**Issue by Peglaa** [Atlantiss/NetherwingBugtracker#3584]
[//]: # (Enclose links to things related to the bug using http://wowhead.com or any other TBC database.)
[//]: # (You can use screenshot ingame to visual the issue.)
[//]: # (Write your tickets according to the format:)
[//]: # ([Quest][Azuremyst Isle] Red Snapper - Very Tasty!)
[//]: # ([NPC] Magistrix Erona)
[//]: # ([Spell][Mage] Fireball)
[//]: # ([Npc][Drop] Ghostclaw Lynx)
[//]: # ([Web] Armory doesnt work)
[//]: # (To find server revision type `.server info` command in the game chat.)

**Description**: 
When you accept the quest 9544 an NPC spawns(17410) and says some text. It has a typo where it fails to show the players name.

![image](https://user-images.githubusercontent.com/15163719/50373662-9b6efa00-05e2-11e9-83a0-5a01382b0b41.png)

**Current behaviour**:

**Expected behaviour**: 

**Server Revision**: 2483

**Comment by Evolvee** [comment]
fixed
