### ISSUE TITLE
[item][spell] Thunderfury applies cyclone to all targets, not just the main one

### ISSUE THREAD

**Issue by Evolvee** [Atlantiss/NetherwingBugtracker#3585]
![image](https://user-images.githubusercontent.com/1942409/50373684-d8d38780-05e2-11e9-9165-9d1c179412f2.png)

this was properly working before rev 2483

**Comment by Tholinx** [comment]
https://github.com/Atlantiss/NetherwingBugtracker/issues/2989

Can u check also this, please?

**Comment by The14me** [comment]
rev.3472 still an issue.

**Comment by Wolffenstein** [comment]
Works fine...
