### ISSUE TITLE
[NPC] Sunfury mobs not spawning- Manaforge Duro

### ISSUE THREAD

**Issue by mbzz88** [Atlantiss/NetherwingBugtracker#3587]
**Description**: Sunfury Bowman (npc=20207) & Conjurer (npc=20139) around Manaforge Duro are missing from the game

**Current behaviour**: No mobs

**Expected behaviour**: Mobs spawn

**Server Revision**: 2483

**Comment by RealZwox** [comment]
The Zone gets reworked soon.

**Comment by Manaci** [comment]
Fixed
