### ISSUE TITLE
[Object] primitive chest messages

### ISSUE THREAD

**Issue by DarthNekr0s** [Atlantiss/NetherwingBugtracker#359]
**Description**: while being out of range to interact with this item, it gives a message saying "item is locked" while it shouldn't say anything until the player gets closer

**Current behaviour**: gives an error message from far away

**Expected behaviour**:  not being interactable/showing message until youre within range of chest

**Server Revision**: 2040

![wowscrnshot_092418_201624](https://user-images.githubusercontent.com/16113944/45947374-55cc8080-c037-11e8-9b48-209d07289af1.jpg)

**Comment by wtRCH** [comment]
@pelekon

**Comment by Tereneckla** [comment]
Fixed
