### ISSUE TITLE
[Quest][Tirisfal Glades] Fields of Grief!

### ISSUE THREAD

**Issue by Orehna** [Atlantiss/NetherwingBugtracker#3591]
**Description**: 

There are no pumpkins to gather. I waited for 10 minutes and no pumkin spawned + there was only one other person in the area who wasn't doing the quest.

**Current behaviour**:

No pumpkins spawn

**Expected behaviour**: 

Pumpkins spawn

**Comment by Orehna** [comment]
apparently this is tied to some know dynamic respawn issues so I'll just close this

**Comment by wtRCH** [comment]
Opening, for now.

**Comment by Evolvee** [comment]
@Shanghi fixed?

**Comment by Shanghi** [comment]
I have no idea! The whole world will be messed up if it's not though

**Comment by Manaci** [comment]
Fixed
