### ISSUE TITLE
[NPC] Murkblood Spearman

### ISSUE THREAD

**Issue by AxeCell** [Atlantiss/NetherwingBugtracker#3592]
**Description**: 
Topic is related to the Murkblood Spearman NPC found within Underbog Heroic and its regular spear throw "ability".

**Current behaviour**:
The Murkblood Spearman will miss a large portion of his spear throws. I don't know the exact percentage, but it felt like he was missing half of his throws if not more.

**Expected behaviour**: 
Should have somewhat identical hit chance to regular attacks.

**Server Revision**: 
2457

**Comment by Tereneckla** [comment]
Fixed
