### ISSUE TITLE
[Arcatraz]missing packs at '1st Boss'-room

### ISSUE THREAD

**Issue by Fenvarien1** [Atlantiss/NetherwingBugtracker#3594]
**Description**: 
missing 2 packs of:
![unbenannt3](https://user-images.githubusercontent.com/44606340/50378680-2e864f00-0638-11e9-8439-f6ffe9f1a9f5.jpg)
1xhttp://db.hellfire-tbc.com/?npc=21608
2xhttp://db.hellfire-tbc.com/?npc=21607

### **Current behaviour**:

![unbenannt](https://user-images.githubusercontent.com/44606340/50378687-51186800-0638-11e9-9e56-358fb639e125.jpg)
![unbenannt2](https://user-images.githubusercontent.com/44606340/50378689-52e22b80-0638-11e9-89c7-d605820f9679.jpg)

### **Expected behaviour**: 

![unbenannt4](https://user-images.githubusercontent.com/44606340/50378702-a2c0f280-0638-11e9-85f4-070c51cb71bc.jpg)

Video: https://www.youtube.com/watch?v=sLBaPuQIsPU&feature=youtu.be&t=92

>**1 PACK movement**:
> ![unbenannt5](https://user-images.githubusercontent.com/44606340/50378746-4a3e2500-0639-11e9-9fab-70f2b563468c.jpg)
> patrol movement live: https://youtu.be/sLBaPuQIsPU?t=84
> _patrol movement slowmo_: https://gfycat.com/SardonicFewElk
> moves back:https://youtu.be/sLBaPuQIsPU?t=97
> _moves back slowmo_: https://gfycat.com/LoneFirstKoodoo
> 
> he stays for ~5-6sec after he moved.

> 2 PACK movement:
> ![2ndmob](https://user-images.githubusercontent.com/44606340/50378869-0ef12580-063c-11e9-8f20-088be8d3224b.jpg)
> https://youtu.be/sLBaPuQIsPU?t=94
> between 1:33-1:37
> Slowmo: https://gfycat.com/MellowIllDromedary
> 
> stays for 5-6sec after he moved.

**Server Revision**: 
2483

**Comment by devo6969** [comment]
I assume they are talking bout the ones you mention because they arnt there on retail or any other video after 2.1
https://wowwiki.fandom.com/wiki/Patch_2.1.0
There are fewer Protean Nightmares roaming the halls.
