### ISSUE TITLE
[Arcatraz]Missing corpses

### ISSUE THREAD

**Issue by Fenvarien1** [Atlantiss/NetherwingBugtracker#3595]
**Current behaviour**:
![unbenannt](https://user-images.githubusercontent.com/44606340/50378996-77410680-063e-11e9-866e-88598396a1ff.jpg)

**Expected behaviour**: 
![corpses](https://user-images.githubusercontent.com/44606340/50379003-b40cfd80-063e-11e9-9b5f-3f1200262f14.jpg)

**Server Revision**: 
2483

**Comment by devo6969** [comment]
They made a lot of changes to Arcatraz from 2.1 on. This video is from 2.0. Can't find any patch notes when they removed them though :/

**Comment by Tereneckla** [comment]
#3594
