### ISSUE TITLE
[NightElf Hunter] Auto Shot Usable while Shadowmeld.

### ISSUE THREAD

**Issue by S2Sin** [Atlantiss/NetherwingBugtracker#36]
**Description**: Auto Shot does not cancel Shadowmeld.

**Current behaviour**: You can use Auto Shot while in Shadowmeld. You will stay in Shadowmeld, and mobs will not attack you while you are attacking them with Auto Shot. 

**Expected behaviour**: Using any ability (including Auto Shot) while in Shadowmeld should cancel and remove Shadowmeld.

**Server Revision**: 2.4.3

**Comment by xmesaj2** [comment]
fixed in 2089
