### ISSUE TITLE
Perascamin (be riding trainer with repair)

### ISSUE THREAD

**Issue by ttghnw** [Atlantiss/NetherwingBugtracker#360]
[//]: # (Enclose links to things related to the bug using http://wowhead.com or any other TBC database.)
[//]: # (You can use screenshot ingame to visual the issue.)
[//]: # (Write your tickets according to the format:)
[//]: # ([Quest][Azuremyst Isle] Red Snapper - Very Tasty!)
[//]: # ([NPC] Magistrix Erona)
[//]: # ([Spell][Mage] Fireball)
[//]: # ([Npc][Drop] Ghostclaw Lynx)
[//]: # ([Web] Armory doesnt work)

**Current behaviour**:
I'm not so 
![wowscrnshot_092418_112624](https://user-images.githubusercontent.com/43508698/45947606-d3b76a00-bfec-11e8-93c3-7d4a26d38944.jpg)
sure if the riding trainer should be a repair npc.
**Expected behaviour**: 
A typical trainer mouseover should appear instead of the anvil and repair interface, I believe.
**Server Revision**:

**Comment by ttghnw** [comment]
Correction: No interface , just anvil incon

**Comment by ttghnw** [comment]
Note The mouse is not captured on the ss unfortunately

**Comment by Evolvee** [comment]
fixed in next hotfix rev
