### ISSUE TITLE
[Talent][Shaman] Elemental Focus

### ISSUE THREAD

**Issue by Aeded** [Atlantiss/NetherwingBugtracker#3601]
**Description**: 
Clearcasting buff consumtion is timed wrong for 2/2 stack

**Current behaviour**:
When you have 2/2 stacks of clearcasting, after you cast next spell, clearcasting is consumed when spell hits, rather than after immidiately after spell is succesfuly casted.
However, if you have 1/2 stack of clearcasting, it works as it should. (Clearcasting consomed right after cast)

**Expected behaviour**: 
Clearcasting should be consumed right after succesful spell cast, no matter how many stacks you have.

**Server Revision**: 2485

**Comment by Aeded** [comment]
this is what I tried to describe
https://youtu.be/fd2Wflvs5xw?t=47
if you have two stacks, it is being consumed on spell hit. If you have only one stack it is being consumed on spell cast. (In both cases it should be consumed on spell cast

**Comment by Aeded** [comment]
https://youtu.be/_u0a6TUljyU?t=99
had 2 stacks, right after he finished cast it consumed one stack. (not after the LB hit target, as it is on NW atm) so fix it, ty alot

**Comment by Tereneckla** [comment]
Visual bug only. Clearcasting got removed with both spellcasts still in the air.
https://youtu.be/Cnn2-pmTr_c

**Comment by Godmatik** [comment]
Fixed in upcoming spell proc rework branch
