### ISSUE TITLE
[Spell] [Shaman] Fire/Earth elemental totem

### ISSUE THREAD

**Issue by Aeded** [Atlantiss/NetherwingBugtracker#3602]
**Description**: 
Nothing works

**Current behaviour**:
1. Both fire and earth can go miles away from their totem
![wowscrnshot_122318_104902](https://user-images.githubusercontent.com/45561230/50382605-d4bb6e80-06a3-11e9-996d-01b540b06572.jpg)

2. Both fire and earth start running towards mobs on which you start casting (you dont even need to finish the cast)
3. Both fire and earth dont despawn their totem if the elemental itself is killed
4. Both fire and Earth dont gain party wide buffs and auras

**Expected behaviour**: 
1. Both elementals are supposed to leash back to their totem, if they are lured beyond 50yd radius
https://youtu.be/lOHOp-s6__g?t=678
Elemental keeps going back and forth because the target is at edge of 50yd radius

2. Both elementals should attack the mobs that attack the shaman, they should also focus the target that shaman is attacking.
To be fair, I never really figure out the algorithm how they choose targets

    https://youtu.be/9uzvlvDzEs0?t=260
    Elemental stops attacking guard and attacks shamans target

    youtu.be/lOHOp-s6__g?t=5m14s
    Elemental swaps to paladin after warrior charges, because its nearest target

3. If elemental dies, totem should despawn
https://youtu.be/9uzvlvDzEs0?t=398
elemental died, totem despawned (you dont see any totem when he turns camera around)

4. Both elementals should gain party wide buffs and auras (shamans totems/heroism)
**Server Revision**: 2485

**Comment by Tereneckla** [comment]
The should not get buffs though

**Comment by The14me** [comment]
Rev.3472
1)Not happen anymore
2)Not happen anymore
3)if totem die=they die too
4)Not an issue.
Can be closed.
