### ISSUE TITLE
[Spell][Shaman] Fire elemental totem

### ISSUE THREAD

**Issue by Aeded** [Atlantiss/NetherwingBugtracker#3603]
**Description**: 
doesnt work well

**Current behaviour**:
1. Has no mana&has very low HP
2. Fire shield aura is visible
3. Doesnt cast often

**Expected behaviour**: 
1.  eu.battle.net/wow/en/game/patch-notes/2-1-0

"Fire Elemental Totem: This pet will now come into the game with full health and mana, including that gained from a percentage of its master’s stamina and intellect. It will also now properly get increased stamina from a percentage of its master’s stamina."
https://youtu.be/9FNSYxBrLpI?t=198
![okqb](https://user-images.githubusercontent.com/45561230/50382790-9aec6700-06a7-11e9-8d21-476544f9b7f9.png)

Should have between 5-6k mana.

2. Fire shield aura is supposed to have hidden flag

3. Fire elemental should cast like crazy
https://youtu.be/9FNSYxBrLpI?t=237

I have plenty of other vids capturing fire elementals, so if someone is interested I can link them.
**Server Revision**: 2485

**Comment by The14me** [comment]
Rev.3472
Have HP, but no mana. He Gains % HP from player Stam.
Fire shield aura is visible
Still don't cast Often.

**Comment by Godmatik** [comment]
Closing - there is more complete information here:
https://github.com/Atlantiss/NetherwingBugtracker/issues/7798
