### ISSUE TITLE
[Spell][Shaman] Earth elemental Totem

### ISSUE THREAD

**Issue by Aeded** [Atlantiss/NetherwingBugtracker#3604]
**Description**: 
doesnt work well

**Current behaviour**:
1. Has low HP (gets killed by one mob 7 levels lower)
2. Deals very low dmg ( 44 dmg per melee hit)
3. Is immune to nature based heals
4. Has his own armor buff visible

**Expected behaviour**: 
1. Should have much higher HP (scales with shaman stamina) Should be around 8-10k
2. Should deal around 230 dmg on 0 armor
https://youtu.be/6jSasbXRTvo
Here it deals 263 crit on 50% armor reduction
https://youtu.be/9uzvlvDzEs0?t=5m40s

3. Should be immune to harmful nature spells, but not helpfull nature spells
4. His armor buff should have hidden flag

**Server Revision**: 2485

**Comment by jasonbourne109** [comment]
To add to this, the Greater Earth Elemental that spawns from the Earth Elemental Totem is level 66, even when the caster is level 70. The Earth Elemental Totem itself is level 70. I'm assuming that the Greater Earth Elemental has the stats of a level 66 and is not scaling with gear, which is causing the issue.

Also: the Greater Earth Elemental is immune to nature-based heals. That should not be the case.

**Comment by Wolffenstein** [comment]
Fixed in rev 3173.
