### ISSUE TITLE
[Talent][Mage] Frostbite

### ISSUE THREAD

**Issue by Aeded** [Atlantiss/NetherwingBugtracker#3605]
**Description**: 
Frostbite debuff is not getting replaced by frost nova or pet nova

**Current behaviour**:
![wowscrnshot_122318_121305](https://user-images.githubusercontent.com/45561230/50383063-e1909000-06ac-11e9-88bc-5cab4a51d9b5.jpg)
Frostbite debuff is not getting replaced by frost nova or pet nova

**Expected behaviour**: 
https://youtu.be/evY1Q9KdXfM?t=1m49s
https://youtu.be/dxQvIEVPOO8?t=2m38s
Rogue gets frostbite proc, and its replaced by frost nova from mage

**Server Revision**: 2485

**Comment by Evolvee** [comment]
all aura stacking is disabled right now ^^
