### ISSUE TITLE
[Spell][Mage] Summon Water Elemental

### ISSUE THREAD

**Issue by Aeded** [Atlantiss/NetherwingBugtracker#3606]
**Description**: 
Water elemental scaling is completely off
![wowscrnshot_122318_122057](https://user-images.githubusercontent.com/45561230/50383372-96797b80-06b2-11e9-8a44-73f218760eff.jpg)

**Current behaviour**:
1. Health and mana of water elemental are too high
2. Water bolt and freeze mana cost are too high
3. Probably general issue, but if water elemental is slowed and mage is not, he follows the mage at same speed, completely ignoring his movement slow.

**Expected behaviour**: 
1. Elemental's base mana before scaling should be 2240 (fact), and its health should be around 2300 (aproxximate)
Both pet intellect and stamina should be 30% of players intelect and stamina. In addition, pet should gain 7.5 health per point of stamina and 5 mana per point of intellect.

https://youtu.be/P0ou5D_v3uY?t=8m5s
Mage has around 370 intelect and his pet has 2985 mana.

https://youtu.be/fja5OBiCClU?t=11m50s
Mage has around 439 intelect and his pet has 3038 mana.

In late tbc, water elemental should have around 3.7k health and 3k mana. (Watch any mage vid)

http://www.arenajunkies.com/topic/11639-pet-scaling/#entry86310
"water elemental only has around 3700 hp"

2. Waterbolt should cost 10% of base mana =224 mana. Freeze should cost 14% of base mana=314 mana

3. Pet should not ignore slow effect when on follow

btw: water bolt should do (Player bonus frost dmg)*0,4*(2,5/3,5)+(waterbolt base dmg).
and freeze should not scale with gear at all, but I think those two things are fine
**Server Revision**: 2485

**Comment by Evolvee** [comment]
scaling was done based on https://github.com/ccshiro/cc-buglist/issues/2052

**Comment by Aeded** [comment]
?? Well not that I read it, but from the picture Barroth linked, you can see that water ele had 3.5k HP and 3k mana. On screenshot I linked you can clearly see that both HP and mana are already much higher on almost naked character?
![image](https://user-images.githubusercontent.com/45561230/50385679-888b2100-06d9-11e9-9240-3ba8f4b208e4.png)

**Comment by 4egito** [comment]
![image](https://user-images.githubusercontent.com/52432938/87225346-e1420d80-c394-11ea-80de-325bff79ece2.png)
[Source](https://vanilla-wow.fandom.com/wiki/Summon_Water_Elemental#:~:text=Summon%20Water%20Elemental%20is%20a,minions%20or%20the%20Hunter's%20pets.)
From the post above^ calculations based on "cchiro/cc-buglist" will be
**Pet HP = Round(2126 + 7.5*Math.floor(428 * 0.3)) = Round(2126 + (7.5*128)) = 3086 hp
Pet Mana = Math.floor(2375 + 4.95*Math.floor(324 * 0.3)) = Math.floor(2375 + (4.95*97)) = 2855 mana**

**Comment by 4egito** [comment]
Meanwhile in PTR naked mage got more stats than expected
![WoWScrnShot_071120_162949](https://user-images.githubusercontent.com/52432938/87225638-3bdc6900-c397-11ea-8b24-ee26752c3678.jpg)

**Comment by 4egito** [comment]
https://www.youtube.com/watch?v=5cHuRPtnZwU&feature=youtu.be&t=125 Video is recorded on EU-Outland PvP and EU-Cho'gall PvP which means RETAIL. Look at the mage stats 10500 flat hp then look at the pet 3769hp/3097mp

**Comment by Godmatik** [comment]
Was fixed back in 2021, duplicate thread that wasn't closed
