### ISSUE TITLE
[Spell] [Shaman] Fire totems dont put shaman in combat

### ISSUE THREAD

**Issue by Aeded** [Atlantiss/NetherwingBugtracker#3607]
**Current behaviour**:
Fire totems dont put shaman in combat
**Expected behaviour**: 
they should
**Server Revision**: 2485

**Comment by Evolvee** [comment]
dont test things like this in shattrath please, its sanctuary area

![image](https://user-images.githubusercontent.com/1942409/50519712-7683f680-0abc-11e9-8417-12cb0be26f80.png)

it works properly
