### ISSUE TITLE
[Spell][Shaman] Earthbind totem puts players in combat

### ISSUE THREAD

**Issue by Aeded** [Atlantiss/NetherwingBugtracker#3608]
**Description**: 
Earthbind totem puts enemy players in combat
**Expected behaviour**: 
earthbind should not cause combat
**Server Revision**: 2485

**Comment by Evolvee** [comment]
probably caused by DB rework from yday - wasnt bugged previously

**Comment by zmthc93** [comment]
proof that its not meant to put players in combat? long time shaman 1 trick and i'm fairly sure its meant to but could be wrong/ thinking of different expansion

**Comment by Evolvee** [comment]
it shouldnt 100%
