### ISSUE TITLE
[Item] Eye of Gruul

### ISSUE THREAD

**Issue by itsonlysmellz** [Atlantiss/NetherwingBugtracker#3609]
[//]: # (Enclose links to things related to the bug using http://wowhead.com or any other TBC database.)
[//]: # (You can use screenshot ingame to visual the issue.)
[//]: # (Write your tickets according to the format:)
[//]: # ([Quest][Azuremyst Isle] Red Snapper - Very Tasty!)
[//]: # ([NPC] Magistrix Erona)
[//]: # ([Spell][Mage] Fireball)
[//]: # ([Npc][Drop] Ghostclaw Lynx)
[//]: # ([Web] Armory doesnt work)
[//]: # (To find server revision type `.server info` command in the game chat.)

**Description**: Eye of Gruul does not have the correct 2.0 stats

**Current behaviour**:
Equip: Each healing spell you cast has a 2% chance to make your next heal cast within 15 sec cost 450 less mana.
This is just the 2.1 version but without the 44 +healing.

**Expected behaviour**: 
The correct 2.0 version reads:
Equip: When your mana drops below 20%, your next heal cast within 15 sec costs 600 less mana. There is a 1 minute cooldown on this effect.
http://web.archive.org/web/20070510125154/http://www.thottbot.com:80/i28823

**Server Revision**: 2485

**Comment by Tenoutoften** [comment]
It uses the correct spellID, but the spellID's effect was changed.

**Comment by Manaci** [comment]
Irrelevant now
