### ISSUE TITLE
[Quest][Wetlands] Young Crocolisk Skins droprate

### ISSUE THREAD

**Issue by PearlzEU** [Atlantiss/NetherwingBugtracker#361]
**Description**: 
The drop rate of the young crocolisk skins seems painfully low. I cleared the marshes north and south of the road twice in a circle ending up with 2/4 skins. It took me about 30 crocs to complete the quest. Obviously bad RNG can never be ruled out 100%, but it might be worth looking into the drop rate since it felt unusually low to me.

**Current behaviour**:
Drop rate of quest item "Young Crocolisk Skin" unusually low.

**Expected behaviour**: 
Drop rate varies between 40-80% according to various databases.

**Comment by SwiftieTBC** [comment]
https://web.archive.org/web/20071104194359/http://thottbot.com:80/i3397
https://web.archive.org/web/20071013094854/http://wow.allakhazam.com:80/db/item.html?witem=3397
Multiple comments on thottbot show people killing ~30ish to get it 

Comments on this section of allakhazam also reinforce the low droprate
https://web.archive.org/web/20080324200251/http://wow.allakhazam.com:80/db/quest.html?wquest=484

**Comment by aresbrutus** [comment]
I just checked the DB and the drop rate corresponds to the retail data.
