### ISSUE TITLE
[Spell] [Mage] Spellsteal

### ISSUE THREAD

**Issue by Aeded** [Atlantiss/NetherwingBugtracker#3610]
**Description**:
Spellstolen buffs dont keep their original power.

**Current behaviour**:
When mage spellsteals magic buffs that are affected by spell power of caster/talents, then spellstolen version on mage doesnt keep the spell power of original caster, but instead is replaced by spell power of mage.
(HoTs, Absorb Shields, etc...)
If you spell steal 800bh lifebloom with naked mage, spell stolen lifebloom heals for 39 per tick. Which is equal to lifebloom casted naked druid. (bh=bonus heal)

Also if you steal Gift of the Naaru, it heals for very wierd amount (91heal/tick). It is possibly the amount you get healed for at lvl 1 gift of naaru.

**Expected behaviour**: 
Spellstolen buffs should keep spellpower from original caster. (Including talents/idols/spell power)
**Server Revision**: 2485

**Comment by killablink** [comment]
Yep, should keep the original values. Spellstealing lifebloom was always a good way for a mage to keep himself up in arenas if there was no healer.

Though I'm not sure of something, you say it's being replaced by the spell power of the mage but lifebloom is ticking as if there is 0 bonus heal? A mage has bonus healing from his gear too

**Comment by torrenzGH** [comment]
any sources?
the increase from talents to e.g. mark of the wild and lifebloom should be retained but spellpower is a different thing
https://www.warcraftmovies.com/movieview.php?id=36326
here spellpower is definitely overwritten by the mage's and i can't find any patch notes about such behavior being changed

how much is "a weird amount"? gift of the naaru is just shit, it will never tick more than 200-300 even on geared healers

**Comment by killablink** [comment]
The spell that was stolen should be affected by the mage's spellpower ( which is equal to the mages healing power). The same way in that video how fire shield received 100% of the mage's spellpower, lifebloom would receive the bonus healing of the mage's spellpower.

**Comment by Kaziczek** [comment]
After few test so far it looks like more complicated problem, maybe even full rework may be needed.
Healing spells  from druid keep ranks but use Mage BH to calculate ticks
Mark and Gift both gives only armor component,

Mobs:
Shattered Halls
Shattered acolytes "Resist Shadow" gives only 2 shadow resist instead of 105

Shadow Labirynth:
Acolyte Renew ticks only for 60

Nether storm:
Sunfury________  Fiery Intelect gives like 10 spellpower instead of 110

I will try to update post whenever i find new ones

**Comment by Godmatik** [comment]
Rev 4017 - no longer an issue, likely fixed with new spell aura branch.
Spellstolen buffs properly retain the bonus damage/healing of the person you stole them from
