### ISSUE TITLE
[Spell][Shaman] Lightning shield

### ISSUE THREAD

**Issue by Aeded** [Atlantiss/NetherwingBugtracker#3612]
**Description**: 
lightning shield has wrong spell coeff
**Current behaviour**:
Lightning shield has 100% spell coeff
**Expected behaviour**: 
Lightning shield should have 80% spell coeff

https://imgur.com/a/VXCashA
https://www.youtube.com/watch?v=j00v_yW8NuQ&feature=youtu.be&t=3m47s

Shield deals 520 damage, then 547 with 101 spell damage totem.
Thats is around 80% benefit from spell power in total instead of current 100%.

**Server Revision**: 2485

**Comment by Wolffenstein** [comment]
Fixed in rev 2489.
