### ISSUE TITLE
[Spell] [Warlock] Soul stone

### ISSUE THREAD

**Issue by Aeded** [Atlantiss/NetherwingBugtracker#3613]
**Description**: 
Soulstone persist on target when they leave group.
**Current behaviour**:
Soulstone persist on target when they leave group.
**Expected behaviour**: 
The Burning Crusade Patch 2.1.0 (2007-05-22): Soulstones can no longer be used on targets not in your party or raid. In addition, the soulstone buff will now be removed if the target or caster leaves the party or raid.
**Server Revision**: 2485

**Comment by Tereneckla** [comment]
Fixed
