### ISSUE TITLE
[Spell][Priest] Shadow word: Death

### ISSUE THREAD

**Issue by Aeded** [Atlantiss/NetherwingBugtracker#3614]
**Description**: 
backfire dmg is not being reduced/increased by buffs/debuffs on priest
**Current behaviour**:
Backfire dmg is not being reduced by spells like Pain Supression
![wowscrnshot_122318_151753](https://user-images.githubusercontent.com/45561230/50384514-047b6e00-06c6-11e9-9f75-a511ef8fa4bf.jpg)

**Expected behaviour**: 
Backfire dmg should be reduced/increased by buffs/debuff that hande dmg taken (Pain supression/curse of elements)
**Server Revision**: 2485

**Comment by Aeded** [comment]
![image](https://user-images.githubusercontent.com/45561230/50387737-0c5a0300-0704-11e9-9035-f16730ec4a8a.png)
https://youtu.be/QyTyNaiEJKs?t=147
Here is swd backfire either partialy resisted, or the dmg is reduced by Spell warding talent. But probably partial resist. Either way it proves my point

**Comment by Wolffenstein** [comment]
I don't know if it worked when this report was made, but it certainly works now.
