### ISSUE TITLE
[Spell][Priest] Power Infusion

### ISSUE THREAD

**Issue by Aeded** [Atlantiss/NetherwingBugtracker#3615]
**Description**: 
Overwrites icy veins and heroism

**Current behaviour**:
Overwrites icy veins and heroism
**Expected behaviour**: 
http://us.battle.net/wow/en/game/patch-notes/2-4-0

"Power Infusion: Infuses the target with power, increasing their spell haste by 20% and reducing the mana cost of all spells by 20%. Lasts for 15 seconds.This will not stack with other haste effects, such as Heroism, Bloodlust, or Icy Veins." 

It is not supposed to overwrite the buffs, but only make the haste portion of the buffs not stack.  Both effect can exist at same time, you just gain +20% haste from one and -20% mana cost of spels from other
**Server Revision**: 2485

**Comment by Evolvee** [comment]
will be working when aura stacking system is applied after being rewritten(in progress) .. same as all other stacking issues
