### ISSUE TITLE
[Spell][Shaman] Lightning shield/watershield

### ISSUE THREAD

**Issue by Aeded** [Atlantiss/NetherwingBugtracker#3617]
**Description**: 
1. Water/lightning shield triggers only on demaging attack
2. Spell reflected spells react wierd with lightning shield

**Current behaviour**:
1. Water/lightning shield triggers only on demaging attack (tested clone, and piercing howl-none of them consumed shield charge)
2. Spell reflected spells consume one charge of lightning shield, but noone gets demaged. Sometimes it doesnt even consume one charge. Water Shield works fine.

**Expected behaviour**: 
1. Every single attack that is made agaist shaman should trigger water/lightning shields. Ofcourse there are some exceptions like mark from hunters/rogue sap/mind vision etc. (and some pve encounter debuffs are exception too-but who cares)
some proofs:
http://eu.battle.net/wow/en/game/patch-notes/2-1-0
"Water Shield: When a Shaman with this spell active is afflicted with Cyclone, the charge burned will now grant mana."

https://youtu.be/4bd7o2SBe18?t=35s
when cyclone hits, last charge is consumed and dru is dmged for 500

https://youtu.be/RBKOMclpmFs?t=57s
One charge was consumed when mage casted poly (no dmg cuz he had ice barrier)

https://youtu.be/RBKOMclpmFs?t=3m20s
One charge consumed when lock casted corruption and got hit for 402

https://youtu.be/FlnUhUqVTKE?t=2m19s
One charge consumed sham is affected by warrior fear and hes hitted for 500 dmg

https://youtu.be/RTuy2wSodfA?t=30s
viper sting triggered shield and hitted hunter for 508

https://youtu.be/JFrsPsU6AA8?t=55s
Prist fear trigered shield and hit for 494 dmg

2) With the lightning shield and spell reflect issue, the shaman should take the hit by the lightning shield (In theory)

**Server Revision**: 2485

**Comment by Wolffenstein** [comment]
Everything apart from the reflect issue fixed in rev 2490.

**Comment by Erodraeda** [comment]
It's also proccing off of Distract, Sap...

**Comment by The14me** [comment]
Rev.3472 Distract/sap issue does not appear anymore.
Can be closed.
