### ISSUE TITLE
[NPC] Lost Soul

### ISSUE THREAD

**Issue by Cpandrej** [Atlantiss/NetherwingBugtracker#3618]
[//]: # (Enclose links to things related to the bug using http://wowhead.com or any other TBC database.)
[//]: # (You can use screenshot ingame to visual the issue.)
[//]: # (Write your tickets according to the format:)
[//]: # ([Quest][Azuremyst Isle] Red Snapper - Very Tasty!)
![wow_2018-12-23_17-03-11](https://user-images.githubusercontent.com/46089397/50385410-7ad39c80-06d5-11e9-8b6e-f7debddf5b61.jpg)

[//]: # ([NPC] Lost Soul)

**Description**: 
It seems that there are two Lost souls instead of One
**Current behaviour**:
Two lost souls instead of one lost soul
**Expected behaviour**: 
One Lost soul
**Server Revision**: 
Server Revision: 2485

**Comment by The14me** [comment]
May be related to last DB change.

**Comment by The14me** [comment]
rev.3472 not an issue anymore.
