### ISSUE TITLE
[Spell][Warlock] Seed of corruption

### ISSUE THREAD

**Issue by Aeded** [Atlantiss/NetherwingBugtracker#3619]
**Description**: 
Does not detonate from its own dot demage if warlock has low spell dmg.

**Current behaviour**:
Does not detonate from its own dot demage if warlock has low spell dmg. So if the previous dot ticks dont add up to 1044 dmg taken before the last tick is supposed to happen, it will just disappear with last tick of the dot without explosion

**Expected behaviour**: 
Explosion is supposed to happen after the full duration of dot even for 0 bonus spell dmg seed of corruption
**Server Revision**: 2485

**Comment by Neophrone** [comment]
Spell tooltip says: when the target takes 1044 total damage or dies - the seed will inflict....
It doesn't say any words about expired spell (dot). 
Bring proves if I'm wrong.

**Comment by kacmed** [comment]
Also there is another issue with seed of corruption ... after exploding only surrounding targets should get damage, target on which seed exploded itself should not take damage 

When the target takes 1044 total damage or dies, the seed will inflict 1110 to 1290 Shadow damage to ->all other enemies<- within 15 yards of the target

**Comment by devo6969** [comment]
This is all fixed, tested it with another mob nearby as well, the SoC doesn't inflict its exploding damage to the effected target.
https://www.youtube.com/watch?v=WAv0vniF3kk
