### ISSUE TITLE
Weapon Skills and Defense increases too fast

### ISSUE THREAD

**Issue by Azalen** [Atlantiss/NetherwingBugtracker#362]
**Description**: 
Weapon Skills and Defense increases too fast. I get level up to 17 and after 5 incoming hits and 5 outgoing hits I have full Sword Skill and Defense again. (both +5)

**Expected behaviour**: 
It should increase but obviously not instantaniously. I think this is a new issue because it wasn't that way yesterday

**Server Revision**: 
[2040]

**Comment by Azalen** [comment]
Okay, I wasn't able to reproduce this on level 18 or 19, maybe it was a rare case of RNG. Still felt super weird.

**Comment by Azalen** [comment]
Yes it's grey mobs. Not sure about defense yet because I have skilled extra defense as a warrior. Probably best you do a testsample on your own. But GREY mobs are the source!

**Comment by Easyfraggy** [comment]
Just to clarify, grey mobs should give skillups, but you are saying the rate at which you get them on grey mobs is too high atm?

**Comment by 5f3759** [comment]
I noticed something similar on critters. I got weapon skillup on 100% of hits on critters.

**Comment by asatorrr** [comment]
I just tested this at level 14. Level 8 mobs, which are grey, would only give me weapon skill level ups somewhat sporadically. However, level 7 was almost every single hit (I estimate >90%).

Also, the skill leveling from fighting mobs that do give experience seems to be pretty low. I mean roughly one skill level per kill just feels bad.

**Comment by Azalen** [comment]
Okay I have another update regarding the Defense gain:

Defense increases as well from grey mobs with every incoming hit but only up to the level treshhold. I don't get any points beyong 110 even though it should be possible. 

I'd really like to have a look at your defense/weapon skill formula now and try to fix it after trying out so much different scenarios

http://www.bilder-upload.eu/upload/8d93bf-1537862806.jpg

**Comment by Easyfraggy** [comment]
> Okay I have another update regarding the Defense gain:
> 
> Defense increases as well from grey mobs with every incoming hit but only up to the level treshhold. I don't get any points beyong 110 even though it should be possible.
> 
> I'd really like to have a look at your defense/weapon skill formula now and try to fix it after trying out so much different scenarios
> 
> http://www.bilder-upload.eu/upload/8d93bf-1537862806.jpg

https://github.com/Atlantiss/NetherwingBugtracker/issues/178

**Comment by Dosdaltherir** [comment]
For me it seems to only work on critters.
