### ISSUE TITLE
[Spell][Prist] Mind Vision

### ISSUE THREAD

**Issue by Aeded** [Atlantiss/NetherwingBugtracker#3620]
**Description**: 
Mind vision interupts drinking/eating on your target
**Current behaviour**:
Mind vision interupts drinking/eating on your target
**Expected behaviour**: 
Patch 2.4.0 (2008-03-25): Mind Vision can no longer be used in Arena. **It also doesn't interrupt drinking/eating.**
**Server Revision**: 2485

**Comment by Wolffenstein** [comment]
On the target or the caster?

**Comment by Aeded** [comment]
On target obviously, tested on friendly units and on enemies and mind vision interupts them both from eating/drinking

**Comment by Wolffenstein** [comment]
Fixed in rev 2488.
