### ISSUE TITLE
Died just outside razor hill at the razormane grounds and my ghost spawned at north durotar near org instead of razor hill.

### ISSUE THREAD

**Issue by Ominouss** [Atlantiss/NetherwingBugtracker#3621]
[//]: # (Enclose links to things related to the bug using http://wowhead.com or any other TBC database.)
[//]: # (You can use screenshot ingame to visual the issue.)
[//]: # (Write your tickets according to the format:)
[//]: # ([Quest][Azuremyst Isle] Red Snapper - Very Tasty!)
[//]: # ([NPC] Magistrix Erona)
[//]: # ([Spell][Mage] Fireball)
[//]: # ([Npc][Drop] Ghostclaw Lynx)
[//]: # ([Web] Armory doesnt work)
[//]: # (To find server revision type `.server info` command in the game chat.)

**Description**: 
Died just outside razor hill at the razormane grounds and my ghost spawned at north durotar near org insteat of razor hill.
**Current behaviour**:
Died just outside razor hill at the razormane grounds and my ghost spawned at north durotar near org insteat of razor hill.
**Expected behaviour**: 
Shouldn't ghost spawn at nearest graveyard in razor hill?
**Server Revision**:

**Comment by The14me** [comment]
need .gps at the place.

**Comment by Brasso** [comment]
![wowscrnshot_122418_113908](https://user-images.githubusercontent.com/44345420/50397449-b5d6de00-0770-11e9-951f-46a6d33ff5b0.jpg)

**Comment by aresbrutus** [comment]
Need .gps at where you DIED please.

**Comment by Brasso** [comment]
Gravestone not enough? :pepesad:

**Comment by Ominouss** [comment]
![razor hill graveyard death bug](https://user-images.githubusercontent.com/45925657/50542266-557bde00-0b6e-11e9-9238-ce9470a04564.png)

tested again and the .gps at where I died = 46, 48 and now it put me @ sen'jin village graveyard instead of razor hill graveyard.

**Comment by The14me** [comment]
Rev.3472
https://i.imgur.com/0fWtZSi.jpg is fixed
When u die around Tiragarder Keep its normal to be spawned at Sen'jin.
Can be closed.
