### ISSUE TITLE
Mechanar Patrol Timer (First Room)

### ISSUE THREAD

**Issue by acedo1234** [Atlantiss/NetherwingBugtracker#3623]
[//]: # (Enclose links to things related to the bug using http://wowhead.com or any other TBC database.)
[//]: # (You can use screenshot ingame to visual the issue.)
[//]: # (Write your tickets according to the format:)
[//]: # ([Quest][Azuremyst Isle] Red Snapper - Very Tasty!)
[//]: # ([NPC] Magistrix Erona)
[//]: # ([Spell][Mage] Fireball)
[//]: # ([Npc][Drop] Ghostclaw Lynx)
[//]: # ([Web] Armory doesnt work)
[//]: # (To find server revision type `.server info` command in the game chat.)

**Description**: The first room containing the Tempest-Forge Patroller's.

**Current behaviour**: They currently stay for far too long. They currently stay still for about 1 whole minute, which is fairly annoying if someone has to afk for a second during their patrol, or didn't get all the buffs out in time.

**Expected behaviour**: If you watch the video I linked from 2007 the mob on the left finishes his patrol at around 0:06 seconds and resumes his patrol around the 00:27-00:32 mark. And at 1:20 he only stays for about 10 seconds. 

**Server Revision**: 2485

https://www.youtube.com/watch?v=gMaDUFgxbgk

**Comment by aresbrutus** [comment]
Fixed in rev `Nariman`
