### ISSUE TITLE
[NPC] [Karazhan] Prince Malchezaar - Infernals

### ISSUE THREAD

**Issue by Drayo** [Atlantiss/NetherwingBugtracker#3624]
[//]: # (Enclose links to things related to the bug using http://wowhead.com or any other TBC database.)
[//]: # (You can use screenshot ingame to visual the issue.)
[//]: # (Write your tickets according to the format:)
[//]: # ([Quest][Azuremyst Isle] Red Snapper - Very Tasty!)
[//]: # ([NPC] Magistrix Erona)
[//]: # ([Spell][Mage] Fireball)
[//]: # ([Npc][Drop] Ghostclaw Lynx)
[//]: # ([Web] Armory doesnt work)
[//]: # (To find server revision type `.server info` command in the game chat.)

**Current behaviour**:

The Infernals channel their Hellfire AOE instantly upon landing.

**Expected behaviour**: 

They should wait for approx. 3-4 seconds after landing before using their Hellfire AOE

**Source:**

https://youtu.be/Dh1I0E4CsAY?t=35

https://youtu.be/ux_W4yDf-rU?t=183

**Server Revision**:  2485

**Comment by Wolffenstein** [comment]
Fixed in rev 2653.
