### ISSUE TITLE
[Spell][Core Mechanic] Chain effect spells

### ISSUE THREAD

**Issue by Aeded** [Atlantiss/NetherwingBugtracker#3625]
**Current behaviour**:
1. Chain spells are able to bounce behind 180 cone of the caster (tested multishot, chain lightning)
2. Chain spells require player to have LoS with every target otherwise they wont chain (tested multishot, chain lightning, sweeping strikes, cleave)

**Expected behaviour**: 
1. Chain spells like Avengers shield, chain lightning, multi shot should not be able to hit behind 180 cone of caster (with an exception to chain heal, sweeping strikes and cleave spells)
https://youtu.be/4okg6BmVoGM?t=15s

2. Chain spells should not require player to have LoS with every target
https://youtu.be/m8nOaNMHZIQ?t=5m31s
**Server Revision**: 2485

**Comment by Kuska101** [comment]
We tested the 2nd part of this report, well, i can confirm this. Not much to add but i have a clip of the current behavior on NW, maybe it can help. Definetly looks weird and in some cases will be really annoying due to inability to heal people behind the corners, when you try to los some of the boss mechanics https://clips.twitch.tv/BigDelightfulOysterChefFrank

**Comment by Easyfraggy** [comment]
Need proof of issue 1

Issue 2 is broken indeed.

**Comment by Aeded** [comment]
??? https://youtu.be/4okg6BmVoGM?t=15s
Chain lightning hits the tank, doesnt chain because every party member is behind 180 front cone
how is that not a proof

**Comment by Aeded** [comment]
https://youtu.be/lOHOp-s6__g?t=11m16s
calm down with your "need research" labels already

**Comment by Easyfraggy** [comment]
I think wolf can check some flags on Spell DBC for this - it's kind of inconclusive - might be different mechanics depending on specific spell - the video with the bear on sethekk is inconclusive - could simply be out of chaining range.

**Comment by Godmatik** [comment]
Rev 4018 - unable to reproduce, chain spells are not able to bounce 180 degrees.
Probably fixed at some point
