### ISSUE TITLE
[Spell][Priest] Shadow word: death

### ISSUE THREAD

**Issue by Aeded** [Atlantiss/NetherwingBugtracker#3626]
**Description**: 
Backfire dmg is 0 if swd was fully absorbed by shield.
![image](https://user-images.githubusercontent.com/45561230/50387684-00ba0c80-0703-11e9-9104-957e5579aaf0.png)

**Current behaviour**:
Backfire dmg is 0 if swd was fully absorbed by shield.

**Expected behaviour**: 
Priest should take the dmg that was absorbed by shield.
**Server Revision**: 2485

**Comment by Aeded** [comment]
Something tells me that you made the backfire dmg always equal to dmg dealt, which is sadly not correct

**Comment by Easyfraggy** [comment]
Need some retail proof that this is true.

**Comment by Aeded** [comment]
https://youtu.be/TYawfgVBSEc?t=1160
You can even read the combat log there

**Comment by Wolffenstein** [comment]
Fixed in rev 2494.
