### ISSUE TITLE
[Spell][Warlock] Hellfire

### ISSUE THREAD

**Issue by Aeded** [Atlantiss/NetherwingBugtracker#3627]
**Description**: 
Hellfire causes pushback on cast/channeled for enemies.

**Current behaviour**:
Hellfire causes pushback on cast/channeled for enemies.

**Expected behaviour**: 
http://wowwiki.wikia.com/wiki/Patch_2.3.0
Hellfire: This spell will no longer cause enemy spells to increase casting time or reduce channel time. It will also no longer prevent flag captures in Battlegrounds.
**Server Revision**: 2485

**Comment by Wolffenstein** [comment]
Fixed in rev 2497.
