### ISSUE TITLE
[Pet][Mechanic] pet on follow is unsnareable

### ISSUE THREAD

**Issue by Aeded** [Atlantiss/NetherwingBugtracker#3628]
**Description**: 
I wouldnt be suprised if it was reported already, but I didnt find myself on bugtracker. So sry if its duplicate

**Current behaviour**:
https://youtu.be/01mgte8BNjs
Pet starts to move at correct speed once you send him attack.

**Expected behaviour**: 
self explanatory
**Server Revision**: 2485

**Comment by Wolffenstein** [comment]
Fixed in rev 2496.
