### ISSUE TITLE
Bloodmyst Hatchling mob - no loot

### ISSUE THREAD

**Issue by mikefirefly** [Atlantiss/NetherwingBugtracker#363]
[//]: # (Enclose links to things related to the bug using http://wowhead.com or any other TBC database.)
[//]: # (You can use screenshot ingame to visual the issue.)
[//]: # (Write your tickets according to the format:)
[//]: # ([Quest][Azuremyst Isle] Red Snapper - Very Tasty!)
[//]: # ([NPC] Magistrix Erona)
[//]: # ([Spell][Mage] Fireball)
[//]: # ([Npc][Drop] Ghostclaw Lynx)
[//]: # ([Web] Armory doesnt work)

**Description**: 
Bloodmyst Hatchling loot.

**Current behaviour**:
Bloodmyst Hatchlings drop no loot whatsoever.

**Expected behaviour**: 
According to wowhead, Bloodmyst Hatchlings should drop loot.

**Server Revision**:

**Comment by SwiftieTBC** [comment]
https://web.archive.org/web/20071105003344/http://wow.allakhazam.com:80/db/mob.html?wmob=17525
Shows the 3 common drops the rest is generic stuff for their level

**Comment by Evolvee** [comment]
https://github.com/Atlantiss/NetherwingBugtracker/issues/214

**Comment by Sothanwow** [comment]
I would like to add while for the most part nothing dropped from these guys at around 11-12 kills a single green item dropped.

**Comment by wtRCH** [comment]
@pelekon

**Comment by Tereneckla** [comment]
Fixed
