### ISSUE TITLE
[Spell](Netherspite) Nether Portal - Dominance

### ISSUE THREAD

**Issue by AxeCell** [Atlantiss/NetherwingBugtracker#3633]
**Description**: 
Topic is related to the Blue Beam "Dominance" buff applied to players during the Netherspite encounter.

**Current behaviour**:
The Dominance buff will not increase the damage you take from Netherspite's "Nether Burn" ability. I am unsure if if it even increases the damage you take from void zones.

**Expected behaviour**: 
The Dominance buff should not be "tankable" by only 1 player. The aura will be unhealable once any dps goes above 30 or so stacks. Dominance should also increase the damage you recieve from void zones.

**Server Revision**: 
2485

**Comment by Kuska101** [comment]
Theres some little proff of that from our run. Attention on my raid healthbars - my HP (Leon) and another shaman "Shabiji" staying in blue beam for quite a while, whole phase actually. Yet we recieve absolutely the same damage from Netherspite aura, which can be seen on my raidframes.
https://clips.twitch.tv/SincereTenderLobsterBIRB

Not sure if we should proof that the blue beam should increase incoming damage from spells, but i guess developers are aware of that.

**Comment by Drayo** [comment]
https://youtu.be/KQhL3jJo7t4?t=213

Source that it should both be doing increased damage to the player with blue stacks. (Void and Burn)

**Comment by Wolffenstein** [comment]
Fixed in rev 2493.
