### ISSUE TITLE
Blinking right before entering any instance portal will warp you to nether 

### ISSUE THREAD

**Issue by tempgithubgod** [Atlantiss/NetherwingBugtracker#3634]
[//]: # (Enclose links to things related to the bug using http://wowhead.com or any other TBC database.)
[//]: # (You can use screenshot ingame to visual the issue.)
[//]: # (Write your tickets according to the format:)
[//]: # ([Quest][Azuremyst Isle] Red Snapper - Very Tasty!)
[//]: # ([NPC] Magistrix Erona)
[//]: # ([Spell][Mage] Fireball)
[//]: # ([Npc][Drop] Ghostclaw Lynx)
[//]: # ([Web] Armory doesnt work)
[//]: # (To find server revision type `.server info` command in the game chat.)

**Description**: 
If you blink as you jump into any instance the SPLIT SECOND before entering the instance, you will blink into nowhere and fall through the ground and die. Happens at ALL instance entrances, both Outland and Kalimdor.

sidenote: If done in hellfire ramparts, you will infinitely die and respawn in this nether zone and be stuck forever until a GM assists you. Does not happen at any other instance I've found.

#2079 this might be related! But this one they're blinking out of the dungeon rather than in

**Current behaviour**:
Blink right before entering instance warps you through ground.
**Expected behaviour**: 
Blinking right before entering any instance should not warp you through the ground.
**Server Revision**: 
2485 Hash: 025c7360cba0

**Comment by killablink** [comment]
https://gfycat.com/RepulsiveCluelessFinch

Confirmed

**Comment by Wolffenstein** [comment]
Fixed in rev 2511.
