### ISSUE TITLE
[NPC][Mechanics]Mob melee attack range leeway still active while slowed

### ISSUE THREAD

**Issue by Fenvarien1** [Atlantiss/NetherwingBugtracker#3635]
**Description**: 
Melee range for mobs is higher than it should be while slowed.

Definition:

> If you and your target is running, the game client will give you a +2.5 yard leeway range, same goes for your target, basically the range indicator for your melee abilities will be white when you're within 7.5 yards of the target(point to point)

> *Leeway mechanic will immediately stop if you or your target becomes slowed to more than -29% of normal run speed(-30% is when your character will switch animation to walking instead of running). Note that it has to be more than -29% of normal running speed, meaning if you or your enemy is on a 100% and become slowed, but the slow doesn't slow down enough to go below -29% normal run speed, then mechanic will still work. Example: Warlock with Curse of Exhaustion talented to grant 30% slow, you cast it on a rogue that has 8% run speed boots enchant. Then leeway mechanic will still work.

https://www.reddit.com/r/lightshope/comments/8yh841/melee_leeway_mechanic/

**Current behaviour**:
Mob is able to hit melee within 5.1-8yards and i can't return a hit because my range is 5yards less.(slowed)
https://gfycat.com/AgileScarceHumpbackwhale

I run into 5yards less and i am able to attack.
https://gfycat.com/AmpleBronzeAmbushbug

running around the target within 5-8y without movement back and forth.
https://gfycat.com/BraveWarmBluemorphobutterfly

**Expected behaviour**: 
You are able to trade even at 5yards or less **because of the slow**. Which was working 2weeks ago. There i leveled a warrior to 10 and used the harmstring kite mechanics.

**Server Revision**: 
2485

> melee leeway bonus was changed on 11.12.2018 Rev 2421

thanks to @Easyfraggy who helped me

**Comment by The14me** [comment]
May be related to new core/DB change.

**Comment by phillipnavarro** [comment]
Please upgrade the priority of this bug. This currently makes leveling a warrior much harder as they are unable to hamstring kite.

**Comment by pnavuf** [comment]
Please upgrade the priority of this bug if possible. This bug currently makes it very difficult to level warrior as it makes hamstring kiting impossible. If left in for launch, it would give players an extremely poor impression of the server.

**Comment by The14me** [comment]
Rev.3472 not an issue anymore.
Can be closed.
