### ISSUE TITLE
Elevators fall damage

### ISSUE THREAD

**Issue by Fenvarien1** [Atlantiss/NetherwingBugtracker#3638]
**Current behaviour**:
Telredor[Zangarmarsh]
https://gfycat.com/GleamingJoyousCanary (ded)
https://gfycat.com/FarflungTenderBurro (ded)
https://gfycat.com/PointedGrippingDwarfrabbit (jumping dmg)

> Thunder Bluff[Mulgore]
> https://gfycat.com/BlankBrownBlackwidowspider - falling down 4,7k dmg(90%hp)
> https://gfycat.com/QuerulousKindIriomotecat - jump of the elevator 5y close to the ground 4,5k dmg(~85%hp)
> 
> Freewind Post[Thousand Needles]
> https://gfycat.com/YawningWaryBrownbutterfly (jumping dmg)
> https://gfycat.com/VigorousJadedEuropeanpolecat (ded)
> 
> The Great Lift[Barrens/Thousand Needles]
> https://gfycat.com/IdioticPlaintiveAfricanporcupine (ded-100%hp)
> 
> These are Horde killing bugs - so don't need to be fixed soon : )

**Server Revision**: 
2497

**Comment by Wolffenstein** [comment]
Fixed in rev 2512.
