### ISSUE TITLE
[Loot] Greater Fleshripper (16-17) dropping Blindweed

### ISSUE THREAD

**Issue by Azalen** [Atlantiss/NetherwingBugtracker#364]
**Current behaviour**:
Greater Fleshripper (https://classicdb.ch/?npc=154) dropping Blindweed with 100% chance. 

**Expected behaviour**: 
It shouldnt. 
Proof: 
https://wayback.archive.org/web/20060415033130/http://wow.allakhazam.com:80/db/item.html?witem=8839
**Server Revision**: 
[2040]

**Comment by Azalen** [comment]
Entry ID = 1109

**Comment by SwiftieTBC** [comment]
https://web.archive.org/web/20071107021939/http://wow.allakhazam.com:80/db/mob.html?wmob=154
https://web.archive.org/web/20070702215112/http://www.thottbot.com:80/c154

Doesnt show any record of any blindweed dropping on either thottbot or Allakhazam records

**Comment by wtRCH** [comment]
@pelekon

**Comment by Tereneckla** [comment]
Fixed
