### ISSUE TITLE
Pyrewood - list of core issues

### ISSUE THREAD

**Issue by Evolvee** [Atlantiss/NetherwingBugtracker#3640]
List of issues that need to be fixed before fixing reports listed below:
https://github.com/Atlantiss/AtlantissTBCBT/issues/4346
https://github.com/Atlantiss/AtlantissTBCBT/issues/4345

---------------------

Issues to fix:
https://github.com/Atlantiss/NetherwingBugtracker/issues/1870
https://github.com/Atlantiss/NetherwingBugtracker/issues/1869
https://github.com/Atlantiss/NetherwingBugtracker/issues/1868
https://github.com/Atlantiss/NetherwingBugtracker/issues/1867
And all other NPCs involved in pyrewood village.

SQL is already waiting:
![image](https://user-images.githubusercontent.com/1942409/50402028-6fdf4180-0793-11e9-94af-39f8d6db13d4.png)

**Comment by The14me** [comment]
Since the above issue's was fixed...that suppose to be fixed too.
Can be closed.
Rev.3472
