### ISSUE TITLE
[Spell][Warrior] Sweeping strikes

### ISSUE THREAD

**Issue by Aeded** [Atlantiss/NetherwingBugtracker#3641]
**Description**: 
Dmg caused by SS is calculatet incorectly. Mentioned aswell here down in comments that make no sense #1604 

**Current behaviour**:
Dmg caused by SS is using only main target armor, but twice. (technicaly 3 times, because dmg before second reduction is also wrong)
If you have warrior that deals 1k on 0% reduction and have him attack player A that has 50% armor reduction. And player B with 0% armor reduction is standing next to player A. It will go like this:
Player A gets hit by 500 physical, and player B gets hit by 250 physical (instead of 1k). Because instead of using the armor of player B, your current implementation uses armor of player A to calculate dmg on player B.
https://youtu.be/8sO1GDI3ijc?t=11
As you can see, it doesnt matter if druid is in bear form or not.

https://youtu.be/tpLg1qrpNY0?t=12
And here shaman(50% armor) takes full hits as if he had 0 armor, because main target has no armor.

**Expected behaviour**: 
Dmg caused by SS should be calculated "as if the warrior was hitting the secondary target" which means that SS dmg should not depend on armor of main target at all, and dmg recieved by both target should by calculated from their own armor.
**Server Revision**: 2497

**Comment by Easyfraggy** [comment]
Please use search function next time - this is a duplicate - but since you have more information here im closing the old one instead.

https://github.com/Atlantiss/NetherwingBugtracker/issues/1604

**Comment by Wolffenstein** [comment]
Fixed in rev 2503.
