### ISSUE TITLE
[Spell][Shaman] Totem of the Astral Winds

### ISSUE THREAD

**Issue by hitbutton** [Atlantiss/NetherwingBugtracker#3642]
Description: 
The Totem relic 'Totem of the Astral Winds' does not appear to be working.
https://www.wowhead.com/item=27815/totem-of-the-astral-winds
spell=34244
(No longer exists on Wowhead)

Current behaviour:
When equipped, the relic should add 80AP to the bonus attack power granted to the shaman's Windfury Weapon attacks. Currently it appears not to affect windfury damage at all.

I did a number of 10 minute tests with a static amount of AP (no Unleashed Rage talent) and only a single weapon (either main hand or offhand) enchanted with Windfury Weapon.

The expected damage increase should have been ~14 for both mainhand and offhand
(given 2.7/2,6 weapon speeds, 40% increase from Elemental Weapons talent, 10% increase from Weapon Mastery talent, and ~39.5% armor reduction on the target)

The observed minimum and maximum damage done by Windfury Attack in the tests was identical regardless of whether the totem was equipped.

Expected behaviour: 
When equipped, Totem of the Astral Winds should add 80AP to the bonus attack power granted to the shaman's Windfury Weapon attacks.

Server Revision: 2497

**Comment by Wolffenstein** [comment]
Fixed in rev 2502.
