### ISSUE TITLE
[Class][Warrior] Blood Craze

### ISSUE THREAD

**Issue by bloodwindz** [Atlantiss/NetherwingBugtracker#3643]
[//]: # (Enclose links to things related to the bug using http://wowhead.com or any other TBC database.)
[//]: # (You can use screenshot ingame to visual the issue.)
[//]: # (Write your tickets according to the format:)
[//]: # ([Quest][Azuremyst Isle] Red Snapper - Very Tasty!)
[//]: # ([NPC] Magistrix Erona)
[//]: # ([Spell][Mage] Fireball)
[//]: # ([Npc][Drop] Ghostclaw Lynx)
[//]: # ([Web] Armory doesnt work)
[//]: # (To find server revision type `.server info` command in the game chat.)

**Description**: blood craze dont work

**Current behaviour**: when warrior suffer a critical hit  the blood craze dont proc

**Expected behaviour**: it should proc 100%

**Server Revision**: 2498

**Comment by Evolvee** [comment]
how did u test it?

**Comment by bloodwindz** [comment]
yes

**Comment by Evolvee** [comment]
i mean, what is the way u tested it? did u sit to proc the crit?

**Comment by Evolvee** [comment]
it works
