### ISSUE TITLE
[Class][Rogue] Master of sublety

### ISSUE THREAD

**Issue by bloodwindz** [Atlantiss/NetherwingBugtracker#3644]
[//]: # (Enclose links to things related to the bug using http://wowhead.com or any other TBC database.)
[//]: # (You can use screenshot ingame to visual the issue.)
[//]: # (Write your tickets according to the format:)
[//]: # ([Quest][Azuremyst Isle] Red Snapper - Very Tasty!)
[//]: # ([NPC] Magistrix Erona)
[//]: # ([Spell][Mage] Fireball)
[//]: # ([Npc][Drop] Ghostclaw Lynx)
[//]: # ([Web] Armory doesnt work)
[//]: # (To find server revision type `.server info` command in the game chat.)

**Description**: buff dont apear

**Current behaviour**:buff dont show up in stealth and dont give the 10%  damage buff for 6 sec before and after stealth breaks  

**Expected behaviour**: when  in stealth it should apear like a non flashing buff like stealth buff is and boost your opener damage by 10%  and after stealth break the buff it should flash like its about to get expired  for 6 seconds and with the 10% damage boost to any attack

**Server Revision**: 2498

**Comment by torrenzGH** [comment]
https://www.wowhead.com/spell=31223/master-of-subtlety#comments
judging by this it never had a buff icon until wrath
from my trial the damage buff behaved correctly if attacking from normal stealth, but if you accessed stealth through vanish you do not get the buff. 2497

**Comment by Wolffenstein** [comment]
It's working correctly.

**Comment by tbc123** [comment]
https://www.youtube.com/watch?v=41B5jbysegM its a bug btw

**Comment by wtRCH** [comment]
@Wolffenstein Revert.

**Comment by The14me** [comment]
Rev.3472 not an issue anymore.
Can be closed.
