### ISSUE TITLE
[Class][Rogue][Talent]  Imp kidney shot 

### ISSUE THREAD

**Issue by bloodwindz** [Atlantiss/NetherwingBugtracker#3645]
[//]: # (Enclose links to things related to the bug using http://wowhead.com or any other TBC database.)
[//]: # (You can use screenshot ingame to visual the issue.)
[//]: # (Write your tickets according to the format:)
[//]: # ([Quest][Azuremyst Isle] Red Snapper - Very Tasty!)
[//]: # ([NPC] Magistrix Erona)
[//]: # ([Spell][Mage] Fireball)
[//]: # ([Npc][Drop] Ghostclaw Lynx)
[//]: # ([Web] Armory doesnt work)
[//]: # (To find server revision type `.server info` command in the game chat.)

**Description**: it dosent work

**Current behaviour**:when talented kidney shot applied it dosent  apply the 9% damage from all sources means player any damage   other classes any melee or spell damage

**Expected behaviour**: it should be shown a second debuff near the kidney shot buff on the target for the duration of kidney shot and apply damage any type from player and any other source (other player or whatever)

**Server Revision**: 2498

**Comment by Wolffenstein** [comment]
![image](https://user-images.githubusercontent.com/1576644/50451023-b9659300-0931-11e9-9fab-5a08d62536ba.png)

Works just fine. I don't know why you expect any debuff to be there. There is none in TBC.
