### ISSUE TITLE
[Spell][Druid] Frenzied regeneration

### ISSUE THREAD

**Issue by Aeded** [Atlantiss/NetherwingBugtracker#3647]
**Description**: 
Healing ticks are unable to crit (tested 4x full duration with 25% crit chance. Its 3 min cd so..)
**Current behaviour**:
Healing ticks are unable to crit
**Expected behaviour**: 
Should be able to crit with 1.5x amount of normal tick, with the crit chance from your melee crit.
https://youtu.be/Ub4ckrWEY-E?t=883
![image](https://user-images.githubusercontent.com/45561230/50407915-6bda1080-07e1-11e9-9a05-85ad0d555355.png)

**Server Revision**: 2497

**Comment by Aeded** [comment]
Frenzied regeneration is physical spell, even heals as type physical. You would need some insane source that physical abylity should be influenced by spell crit.
pls stop toutching my reports and go practise some math like 160*1,2=192 🤔

**Comment by Easyfraggy** [comment]
You take things way to personally.

The burden of proof is on you - you want this changed - it would be the only healing spell in game that scales with physical crit.

**Comment by Wolffenstein** [comment]
It has a physical spell school indeed, but its DamageClass = 0 (SPELL_DAMAGE_CLASS_NONE), which means it's using magic crit chance. Need proof it should use physical indeed.

**Comment by Tereneckla** [comment]
dead issue
