### ISSUE TITLE
[Hunter][Spell] Trap trigger radius

### ISSUE THREAD

**Issue by Zarant** [Atlantiss/NetherwingBugtracker#3649]
Trap trigger radius seems to be slightly smaller to what is supposed to be, when you compare it to retail footage. To make the comparison easier, I took this screenshot where I'm barely outside the trap radius: https://i.imgur.com/qhEZR6I.jpg

All the clips I'm gonna link now are recorded with 30 fps, so each spell batch takes around 12 frames to complete. 

https://youtu.be/9z2m9f8Z9P4?t=491 - On this clip, if you pause at the exact same frame the rogue gets the frost trap debuff and rewind 13 frames, you can see that's exactly when the frost trap animation start to play out, so the trap triggered and then ~400ms later the rogue gets affected by the trap debuff. Here you can see that the trap activation range is quite big.

Now to understand the next 2 clips you have to consider the 2 second long trap arming time:
> Traps can be set while in combat, but require a 2 second arming time.

Source: http://wowwiki.wikia.com/wiki/Patch_2.0.1

https://www.youtube.com/watch?v=LrZ_qgp917c&feature=youtu.be&t=393 - Hunter lay down a trap and 74 frames (2.467s) after laying the trap, the paladin gets affected by the trap debuff, considering the delayed debuff application, if you rewind 12 frames you can see where the paladin was when the trap triggered. The paladin came from behind, the hunter was between his trap and the paladin, considering that the hunter got stunned and the trap was directly in front of the hunter

https://www.youtube.com/watch?v=hS82JzE6F0I&feature=youtu.be&t=509 - Very similar situation, the hunter is rooted in place, and then the druid position himself in a way that the hunter is standing between the druid and the trap, if you rewind 12 frames you can see the druid position when he triggers the trap.

I tried to dig through patch notes and blue posts but the only thing I found about this subject was a hotfix applied during the WoD period, that implied that the trap radius was 5 yards at some point:

> Hotfix (2015-01-08): "Freezing Trap now has a trigger radius of 3 yards (down from 5 yards)." 

Source: https://wow.gamepedia.com/Freezing_Trap

I also found a testimony from the arena junkies forums, written a week after patch 3.2:

> trap radius is like 2yards, melee range is like 5y
> didnt test it thais patch but always before it was like that:
> hunter staying on top of trap -> melee class at max melee range hiting hunter and not getting traped
> moreover hunter takes step back -> melee still hiting him through trap

Source: http://www.arenajunkies.com/topic/93057-freezing-trap-trigger-range/

According to this person, melee should be able to hit the hunter from max range if the hunter is on top of the trap, but if you compare to the retail footage I just linked, you can have an idea that the trap trigger radius is very close to 5 yards. My guess here is that the trap activation radius is 5 yards, but since the player's hitbox is much bigger than the trap hitbox you can still get hit by melee attacks without triggering the trap if you are standing right on top of it.

**Comment by Wolffenstein** [comment]
Should be better after rev 2950.

**Comment by x-x-x-x-x-x-x-x-x-x-x-x** [comment]
Trigger radius is still too low. Melee can easily hit the hunter and not get trapped, while the hunter is standing on the trap. This should not be possible and was confirmed on Classic. Radius should be melee range + character size(target). @Wolffenstein
