### ISSUE TITLE
[Quest][The Barrens] Apothecary Zamah

### ISSUE THREAD

**Issue by totaemoeggerli** [Atlantiss/NetherwingBugtracker#365]
**Description**:
The quest starts at Apothecary Helbrim in Crossroads. You have to deliver [Rendered Spores] within 45 Minutes to Apothecary Zamah in Thunder Bluff. The timer ran out and the quest failed. I did not abandoned the quest or delete the quest item (100% sure about this). 
I realized that the quest disappeared from my quest log and the quest item from my bag after the server crash this morning. I can't tell if it disappeared this morning or yesterday already. However, I can't pick up the quest at the NPC again.

**Current behaviour**:
Quest disappeared from quest log and quest item from the bag probably after a server crash.

**Expected behaviour**: 
Quest should remain in the quest log even after it fails. And players should be able to abandone and pick it up again.

**Server Revision**:

**Comment by Wolffenstein** [comment]
Fixed in rev 2138.
