### ISSUE TITLE
air force guard post 

### ISSUE THREAD

**Issue by bloodwindz** [Atlantiss/NetherwingBugtracker#3650]
[//]: # (Enclose links to things related to the bug using http://wowhead.com or any other TBC database.)
[//]: # (You can use screenshot ingame to visual the issue.)
[//]: # (Write your tickets according to the format:)
[//]: # ([Quest][Azuremyst Isle] Red Snapper - Very Tasty!)
[//]: # ([NPC] Magistrix Erona)
[//]: # ([Spell][Mage] Fireball)
[//]: # ([Npc][Drop] Ghostclaw Lynx)
[//]: # ([Web] Armory doesnt work)
[//]: # (To find server revision type `.server info` command in the game chat.)

**Description**: the air force guard post   dont trigger the flying units in any city 

**Current behaviour**:if you go to any city it as hostile (mean horde or whatever) in outlands it dosent trigger air defence units or (depends on where it is if its lets say honor hold its the griphon mounts units)

**Expected behaviour**:  if any flying  hostile player come close to a faction by flying it should trigger air defence  that is unique of the spesific  outland city   for sporegar bats and what ever for  honor hold griphons etc https://images-ext-1.discordapp.net/external/EQlP2d1_TroLzHKLQbBZMi9L0CMOm8MN4NRknLqBkyw/https/cdn.discordapp.com/attachments/525897461055750144/526931759632482304/unknown.png?width=1117&height=674

https://media.discordapp.net/attachments/525897461055750144/526918665933815809/unknown.png

**Server Revision**: 2498

**Comment by Tereneckla** [comment]
Fixed
