### ISSUE TITLE
[NPC] Shadowmoon Soulstealer, Shadowlord Deathwail

### ISSUE THREAD

**Issue by Onsty** [Atlantiss/NetherwingBugtracker#3655]
[//]: # (Enclose links to things related to the bug using http://wowhead.com or any other TBC database.)
[//]: # (You can use screenshot ingame to visual the issue.)
[//]: # (Write your tickets according to the format:)
[//]: # ([Quest][Azuremyst Isle] Red Snapper - Very Tasty!)
[//]: # ([NPC] Magistrix Erona)
[//]: # ([Spell][Mage] Fireball)
[//]: # ([Npc][Drop] Ghostclaw Lynx)
[//]: # ([Web] Armory doesnt work)
[//]: # (To find server revision type `.server info` command in the game chat.)

**Description**: 
Shadowmoon Soulstealer <a href="https://gyazo.com/15b3a78d3018e6b827ecdc100c29d7be"><img src="https://i.gyazo.com/15b3a78d3018e6b827ecdc100c29d7be.png" alt="Image from Gyazo" width="152.8"/></a>
and Shadowlord Deathwail  <a href="https://gyazo.com/aef7244c5119df4bbb6c6145b6dfe382"><img src="https://i.gyazo.com/aef7244c5119df4bbb6c6145b6dfe382.png" alt="Image from Gyazo" width="142.4"/></a>
in this area in SMV
<a href="https://gyazo.com/affbfb99518bb3ab2c09e69055ccb276"><img src="https://i.gyazo.com/affbfb99518bb3ab2c09e69055ccb276.png" alt="Image from Gyazo" width="545.6"/></a>

These mobs are needed for the Black Temple attunement quest [The Ata'mal Terrace](https://www.wowhead.com/quest=10707/the-atamal-terrace)
So i dunno how they should act before BT release

**Current behaviour**:
Shadowmoon Soulstealer are bring you in combat and does not attack you
<a href="https://gyazo.com/9034ce276eeb9b77b3c2ec3d0eb14849"><img src="https://i.gyazo.com/9034ce276eeb9b77b3c2ec3d0eb14849.jpg" alt="Image from Gyazo" width="900.8"/></a>

Shadowlord Deathwail doesn't have combat resetting distance. He Just chasing you and keeping in combat
<a href="https://gyazo.com/73af94a536dcf284d16d5fcc755d15bd"><img src="https://i.gyazo.com/73af94a536dcf284d16d5fcc755d15bd.jpg" alt="Image from Gyazo" width="1005.6"/></a>
**Expected behaviour**: 

**Server Revision**:

**Comment by Evolvee** [comment]
i fixed this some time ago
