### ISSUE TITLE
Pathaleon MC

### ISSUE THREAD

**Issue by networm555** [Atlantiss/NetherwingBugtracker#3656]
Lost control over my character after mindcontrol ended. It responds on some commands but then AI intervenes and starts its own thing like running to someone. Happened to every player he mindcontrolled.

**Comment by ircfelix** [comment]
Quality gold level report.

**Comment by networm555** [comment]
Not a paid job to sit here and format. Say ty i even bother to do this, so your retarded sarcastic ass can play something different than sunwell. Dont like it? Create your own with same issue. This will help. Your imbicile comments not helping at all.

**Comment by ircfelix** [comment]
The better bug reports are written, the faster they will be fixed.

**Comment by Mikik3jr** [comment]
I think you are a class that can charge (warrior, druid in bear), aren't you @networm555? Did this "AI intervene" happened after you charged?

**Comment by Godmatik** [comment]
Was fixed a while ago
