### ISSUE TITLE
[NPC](heroic) Auchenai Monk

### ISSUE THREAD

**Issue by AxeCell** [Atlantiss/NetherwingBugtracker#3657]
**Description**: 
Topic is related to the Auchenai Monk enemy found within Auchenai Crypts heroic and its damage values. Said damage test was done on a protection paladin with 14 000 armor(57% damage reduction), every protective talents alongside Righteous Fury active and heavy focus on spell damage pieces.

**Current behaviour**:
The Auchenai Monk hit me for 680-950 white damage.

**Expected behaviour**: 
As of this moment, this enemy doesn't pose any threat even alongside its signature whirlwind ability. I was unable to find any videos nor information in regards to its initial 2.0.1 damage values, but as the most melee heavy NPC in this heroic they deal way less damage than one would expect.

**Server Revision**: 
2457

**Comment by Fenvarien1** [comment]
same problem as here: https://github.com/Atlantiss/NetherwingBugtracker/issues/3658

it's impossible to fix something based on feelings.

**Comment by Easyfraggy** [comment]
bestiary only has normal mode values: 
![image](https://user-images.githubusercontent.com/36134067/50454940-0013b700-094b-11e9-9a6a-b403c677575a.png)

**Comment by devo6969** [comment]
Retail TBC, I believe this is normal. The monk hits a naked rogue 3 times. Once with (701) auto+ (751) WF proc, then auto 798

(Shows level 65 mob on tooltip) Retail TBC - https://youtu.be/TUjDZ5IMveQ?t=34
(Monk hits) Retail TBC - https://youtu.be/TUjDZ5IMveQ?t=83
