### ISSUE TITLE
[Dungeon](Shadow Labyrinth)(Heroic) Damage Values

### ISSUE THREAD

**Issue by AxeCell** [Atlantiss/NetherwingBugtracker#3658]
**Description**: 
Topic will be related to the damage many of the NPCs within Shadow Labyrinth Heroic does, and how it either is or feels undertuned. These damage tests were done on a protection paladin with 14 000 armor(57% damage reduction), every protective talents alongside Righteous Fury active and heavy focus on spell damage pieces. I also made sure to show my back to a lot of these enemies to prevent blocks.
I can't personally hunt for the correct values on each NPC, so help on undocumented NPCs in the comments would be appreciated.
Finding video evidence on this heroic was hard due to the nature of it being a level 70 normal dungeon.

**Current behaviour**:
Cabal Acolyte - 440-600 white damage
Tortured Skeleton - 120-155 white damage
Cabal Zealot - 400-600(normal), 650-770(transformed)
Grandmaster Vorpil - 550-650 white damage, Void Traveler shadow nova 1175, Shadowbolt Volley 1k

**Expected behaviour**: 
Cabal Acolyte: Their damage feels a bit on the low side. Especially when compared to the staff wielding Cabal Ritualists hitting for 1150-1220 damage.

Tortured Skeleton: These are normal enemies found between the 2nd and 3rd boss. I mostly noted these down because it was easily possible to tank 2 packs on my warlock while I was channeling hellfire.

Cabal Zealot: This enemy stood the most out of anything found within the dungeon. Their damage is extremely low, and doesn't change much once transformed. Here's a comment from 2.0.12 talking about how dangerous they're supposed to be: https://www.wowhead.com/npc=18638/cabal-zealot#comments:id=62956

Grandmaster Vorpil: His white damage was heavily underwhelming for a heroic boss. According to Wowhead his shadowbolt volley damage is authentic, but according to this comment the Void Traveler's Shadow Nova should deal about double of what it's currently doing: https://www.wowhead.com/npc=18732/grandmaster-vorpil#comments:id=20000

**Server Revision**: 
2438

**Comment by bloodwindz** [comment]
+ 1

**Comment by Fenvarien1** [comment]
It's hard to fix something without proper research.
Do you have any proof of the 2.0 values instead of  "they dealt alot of damage" or "it feels like".

> The dogs do massive melee damage. The effect must be removed or the mob must be killed instantly.

They can't adapt the damage to something more "heavy" hitting based on such comments.

The Shadownova and Volley of Vorpil are correct. Same as the spawnrate of adds. The Shadowdamage is increased by every voidwalker reaching the boss by 120.
Shadowvolley: https://youtu.be/gTtQzX5qFXQ?t=81 (825)
Shadownova: https://youtu.be/gTtQzX5qFXQ?t=89 (590+654resist=1244)
Melee: https://youtu.be/gTtQzX5qFXQ?t=7 (820dmg with low gear)
Melee: https://youtu.be/gTtQzX5qFXQ?t=23 (633 and a seconds with 543, 3rd with 694)

so we are on point with damage values for the Vorpil Boss.

I would suggest to do more research on the other trash mobs. they could be undertuned.

**Comment by AxeCell** [comment]
For reference I commented about the Fel Overseer dealing too low damage back in phase 2 of the beta. The NPC was thereafter adjusted by the main developer without me providing any proof at the time. It was simply obvious the NPC was too weak compared to how much the Malicious Instructor was hitting.

In regards to your statement about me attempting it in pre-raid blues or greens, I was in fact one of the only ones running dungeons/heroics in phase 2 of the beta on alliance side, and we did get around to test heroics such as Shadow Labyrinth and others in the process. I was informed by testers and the like to note down damage values that seemed off, even if I couldn't ultimately provide proof.

Me mentioning Grandmaster Vorpil was plainly due to the comments added by the party members I did the heroic with. This will be a common occurance on fights like this(on live release) where the NPC doesn't even come close to the general expectations players have of said encounter. (This comes from heightened expectations of the legendary "Hard TBC heroics" stigma, and recent experiences on boosted private servers).

Atleast you participated in the discussion which is needed for reports like this that have very limited amount of proof available to them. There will also be situations where the people leading the project has to decide for themself if they want to keep encounters "blizzlike" for the sake of purity, or adjust it to make the encounters more true to their stigma/up to the challenge of similar content.

**Comment by Kuska101** [comment]
I wanted to report something like that, for example about Grandmaster Vorpil as well, like look at this (https://clips.twitch.tv/StrongRelentlessFoxSSSsss) - i pulled aggro on him and he barely hit me, his damage is laughable. His aoe damage is laughable as well. Well, yea, we are soo overgeared and nuked him, and nuking is key for this particular fight. But looking at the comments on wowhead + this video from Fenvarien, it seems to be correct. This encounter is really, very easy, even with weak gear people will be able to pull this ~3k dps from grp with BL and CD's in 15-30 sec nuke him and avoid his main mechanic with TP+ROF+some ocasional explosions from voids.

As for thrash mobs (like Zealots) - i always mention something like that here and there, for example in Arc there was a mob that i could tank as ele shaman for 10 sec, and it was a rogue-like mob with fast powerful attacks, such npcs should just destroy casters in seconds in heroics without any chance to survive, but, well, they dont. Fenvarien asked for a proper research - i tried to find any relevant Slabs run video where trash is included from retail and couldnt find any. Other private server databases are not a credible source of info either. So what do we do in such cases? I have some reports alike prepared, but have no clue how to prove it.

**Comment by cah4ec182** [comment]
Guys, for the correct values on each NPC use this database: https://db.excalibur.ws/

Example: 
1) **Cabal Acolyte** (Heroic): Level: 70; Classification: Elite; React: A H; Faction: Monster; Health: 25,151; Mana: 9,465; Worth: 18 36; Damage: 2,668 - 3,068; Attack Speed: 2000 ms; Damage School: Physical; Armor: 5474; Experience Multiplier: 1;
https://db.excalibur.ws/?npc=20638, here u can see abilities too.

2)**Cabal Zealot** (Heroic): Ability - Shape of the Beast: Time between attacks decreased by 100%. Attack Power increased by 750. Cannot Cast Spells.

Enjoy!

**Comment by Evolvee** [comment]
damage overhauled, try again please
