### ISSUE TITLE
[NPC] Neltharaku

### ISSUE THREAD

**Issue by rychersky** [Atlantiss/NetherwingBugtracker#3659]
**Description**:
![wowscrnshot_122618_005436](https://user-images.githubusercontent.com/45608488/50437994-4f091000-08a9-11e9-8dc2-3028ed7923a6.jpg)

**Current behaviour**: Not sure what triggers it but Neltharaku will stop patrolling in a clockwise circle and idle in the air.

**Expected behaviour**: Patrol in a circle.

**Server Revision**: Server Revision: 2497 [Branch: master, Hash: 9f3d799dee42]

**Comment by Evolvee** [comment]
someone clicked on him

**Comment by rychersky** [comment]
I should clarify: he stops moving entirely, even when no player is interacting with him. I got his first quest and then went and did subsequent quests only to come back and find him in the same spot every time in the idle-flying animation.

**Comment by fantom8** [comment]
Still happening on live servers. You can go check the NPC out in SMV right now, he's stationary at the back of the fortress.

He was patrolling before I talked with him (for the first quest - the one where you have to exhaust the dialog options) but afterwards for the last 15+ minutes he's been in the same spot each time I returned after doing the next step in the chain.

I waited around for a few minutes in front of him and no new players showed up to interact with him but he still didn't start patrolling again.

https://i.imgur.com/lD8k77N.png

**Comment by The14me** [comment]
Rev.3472 still an issue. Stop for no reason.

**Comment by Godmatik** [comment]
Rev 4022

Still an issue, noticed it on Kara server.

**Comment by Godmatik** [comment]
Potentially fixed with upcoming movement rework
