### ISSUE TITLE
[Quest][Azuremyst Isle] Chieftain Oomooroo

### ISSUE THREAD

**Issue by Eidous** [Atlantiss/NetherwingBugtracker#366]
[//]: # (Enclose links to things related to the bug using http://wowhead.com or any other TBC database.)
[//]: # (You can use screenshot ingame to visual the issue.)
[//]: # (Write your tickets according to the format:)
[//]: # ([Quest][Azuremyst Isle] Red Snapper - Very Tasty!)
[//]: # ([NPC] Magistrix Erona)
[//]: # ([Spell][Mage] Fireball)
[//]: # ([Npc][Drop] Ghostclaw Lynx)
[//]: # ([Web] Armory doesnt work)

**Description**: 
The Stillpine raiders that spawn after you hand in the quest "Chieftain Oomooroo" are not hostile to the crazed wildkin inside of Stillpine hold, so they just run past them.

**Current behaviour**:
The Stillpine raiders run past the crazed wildkin to their endpoint (and probably despawn, but I couldn't run past the wildkin myself to verify)

**Expected behaviour**: 
The Stillpine raiders run into the cave and die mercilessly by the wildkin's hand

**Server Revision**: 
2040

**Comment by Evolvee** [comment]
fixed in next hotfix revision
