### ISSUE TITLE
[NPC] Vhel'kur

### ISSUE THREAD

**Issue by Kuska101** [Atlantiss/NetherwingBugtracker#3660]
**Current behaviour**:
1. Do not patrool the island and simply stands still on his respawn spot
2. Have wrong animation while fighting, he have "landed" dragon animation instead of flying version while he is currently in mid-air, which is looking weird and wrong

Both issues can be seen in this clip - footage from Netherwing
https://clips.twitch.tv/ImpossibleSecretiveSangSquadGoals

Edit: i've checked again my vod of this npc, well, looks like he WAS patrooling before i wiped on him first time, but then stopped. 
**Expected behaviour**: 
1. Should patrool around the netherwing lodge
2. Should have correct flying animation if there is no land behind him.

Correct behavior of both issues can be seen in this vid from retail: https://youtu.be/pseiw4cVPA8?t=43

**Server Revision**: 
2497

**Comment by The14me** [comment]
rev.3472 he just stays.After die/respawn he start the path again.Worth a check.

**Comment by Godmatik** [comment]
Fixed at some point?

He is flying around just fine for me and I watched for a while, never got stuck, and have not heard of this issue on Netherwing server.
