### ISSUE TITLE
[Item] Insightful Earthstorm Diamond

### ISSUE THREAD

**Issue by Aeded** [Atlantiss/NetherwingBugtracker#3662]
**Description**: 
![image](https://user-images.githubusercontent.com/45561230/50443349-4b09dc00-0903-11e9-9930-145673ed0d97.png)
Proc from gem "Mana Restore" procs after spell hit, not after spell cast
**Current behaviour**:
Proc from gem "Mana Restore" procs after spell hit, not after spell cast
**Expected behaviour**: 
Proc should be after succesful spell cast. (as the description says btw)
**Server Revision**: 2497

**Comment by Tenoutoften** [comment]
On [Wowhead](https://www.wowhead.com/spell=27521/chance-to-restore-mana-on-spellcast)
![](https://i.gyazo.com/ecfea444f00b9661cbf7d2212110d3e5.png)

On [Excalibur](https://db.excalibur.ws/?spell=27521/chance-to-restore-mana-on-spellcast)
![](https://i.gyazo.com/c1df8c6929792dc7c572f3d4b042a07e.png)

Judging by the text it's evident that the proc should happen after the cast, a cast isn't successful before it has landed. Comment on wowhead stats the text is inaccurate in 2.3 in regards to proc rate, it gets increased from 2% to 5%

**Comment by ircfelix** [comment]
According to the info by @sandreid , this report needs no more research @Wolffenstein .

> 
> 
> On [Wowhead](https://www.wowhead.com/spell=27521/chance-to-restore-mana-on-spellcast)
> ![](https://camo.githubusercontent.com/e166a887cc90bee2e5064c143156306c4c738563/68747470733a2f2f692e6779617a6f2e636f6d2f65636665613434346630306239363631636266376432323132313130643365352e706e67)
> 
> On [Excalibur](https://db.excalibur.ws/?spell=27521/chance-to-restore-mana-on-spellcast)
> ![](https://camo.githubusercontent.com/efaf79ae6ad0e768148d8a70f0d9e38837279b19/68747470733a2f2f692e6779617a6f2e636f6d2f63316466386336393239373932646337633537326633643462303432613037652e706e67)
> 
> Judging by the text it's evident that the proc should happen after the cast, a cast isn't successful before it has landed.

Check **comments** on wowhead for the 300 mana value.

**Comment by Aeded** [comment]
Its definetly not supposed to proc from water shield or auras, procing from these kind of spells was fixed in later patches. It is supposed to proc from Totemic recall, but you have to recieve mana for destroyed totem because its not supposed to proc if you cast totemic recall without any totems.
And in general, tooltips are very misleading so dont put any value on them. But this is not the case, its actualy supposed to proc on spell cast.

**Comment by Xynaps** [comment]
@Aeded I can't seem to find any support for your claim of a fix, at least not in official patch notes. There are no references to this item in the patch notes anywhere from what I could see. The only change it had, that has some source, was a stealth buff in 2.3.0 from 2 % -> 5 % proc chance and that source is the datamining of wowhead at the time. It's of course possible that a fix was done but a source to back up the claim would be nice.  

I also attempted to make it proc with paladin seals, both the buff and the procs generated, which according to the wowhead comments should work, but I got no proc. It could have been just a bad luck but I doubt it.

**Comment by lajhar** [comment]
Please check the current proc chance.

As of 2.3 chance should be 5% instead of 2%.
Not a big sample, but I got 24 proc off 1000 spellcasts which seem to be far closer to 2% rather than 5%. It could be bad luck tho.

Also, the original report is also legit. Wowhead comments indicate that it procs on every type of spellcasts, can even proc on itself (0.05*0.05 = 0.0025 chance)

Server revision: 3139

**Comment by Wolffenstein** [comment]
Fixed in rev 3194.
