### ISSUE TITLE
[Talent][Shaman] Elemental Focus

### ISSUE THREAD

**Issue by Aeded** [Atlantiss/NetherwingBugtracker#3663]
**Description**: 
Clearcasting proc from this talent gets consumed by spells that are mana free, because of Elemental Mastery spell. (Tested also mana free procs from overloads and they dont consume clearcasting)
**Current behaviour**:
Clearcasting proc from this talent gets consumed by spells that are mana free, because of Elemental Mastery spell.
**Expected behaviour**: 
Mana free spells should not consume buffs that reduce mana cost of spells.
**Server Revision**: 2497

**Comment by Kuska101** [comment]
This one is really doubtful, cant see any reason why casts with Elemental focus should not consume Clearcasting proccs.
Just look at talent descriptions:
Elemental Mastery:
When activated, this spell gives your next Fire, Frost, or Nature damage spell a 100% critical strike chance and reduces the mana cost by 100%.
>...and reduces the mana cost by 100%.

Elemental Focus:
After landing a critical strike with a Fire, Frost or Nature damage spell you enter a Clearcasting state. The Clearcasting state reduces the mana cost of your next 2 damage spells by 40%.
>...reduces the mana cost of your next 2 damage spells by 40%.

How does it contradict each other? After short googling could not find anything that confirms your suggestion. For example here: https://github.com/cmangos/issues/issues/1739 (cmangos github) people suggest completely the opposite to be correct. And logically, current behaviour seems correct to me.

**Comment by Aeded** [comment]
🤔 links wotlk bug report, that describes some comletely different bug because elemental mastery was completely reworked in wotlk...
Mana free spells dont consume buffs that reduce mana cost of spells. That should be general rule for everything (eg overload doesnt consume clearcasting, which already works, etc etc)

If you dont believe me, there are cases mentioned in patchnotes that clearly say "Mana free spells dont consume buffs that reduce mana cost"
There is for example patchnote about Surge of light not consuming Inner focus.

So pls crawl below rock and dont comment on my reports with useless wall of text

**Comment by Kuska101** [comment]
Lmao that's a proper attitue. Allright, keep spamming with senseless reports without any proof, gl.

**Comment by Easyfraggy** [comment]
As with all your other reports (almost) need proof.

**Comment by Aeded** [comment]
Well I honestly didnt expect that you need proof for every "common behaviour" that vast majority of player base is familiar with.
https://youtu.be/_u0a6TUljyU?t=92
But ye here you go, now give me back 1 hr of my life that I wasted just to prove you and some other double digit IQ monkey wrong.

Now please be so kind and remove "need resereach" from #3664 ty alot.

**Comment by Easyfraggy** [comment]
Please stop with the attitude - it won't get you anything. Nice to have some proof for this - good find.

**Comment by Aeded** [comment]
I wont look for proof to the #3664 because noone ever had elemental mastery and shamanistic focus specced. It is general behaviour, like I said like 4 times already.
It is same case, just different scenario, because instead of clearcasting its slightly different buff from other talent.
Not even going to argue about it... If you dont want to believe it, it is your personal problem not mine.

**Comment by Tereneckla** [comment]
rev 3170
