### ISSUE TITLE
[Talent][Shaman] Shamanistic Focus

### ISSUE THREAD

**Issue by Aeded** [Atlantiss/NetherwingBugtracker#3664]
Description:
"Focused" proc from this talent gets consumed by shocks that are mana free, because of Elemental Mastery spell.
Current behaviour:
"Focused" proc from this talent gets consumed by shocks that are mana free, because of Elemental Mastery spell.
Expected behaviour:
Mana free spells should not consume buffs that reduce mana cost of spells.
Server Revision: 2497

**Comment by Easyfraggy** [comment]
Need proof

**Comment by Wolffenstein** [comment]
Fixed in rev 3592.
