### ISSUE TITLE
[Spell][Shaman] Totem of Wrath

### ISSUE THREAD

**Issue by Aeded** [Atlantiss/NetherwingBugtracker#3667]
**Description**: 
Multiple instances of totem doesnt stack
**Current behaviour**:
Multiple instances of totem doesnt stack
**Expected behaviour**: 
![image](https://user-images.githubusercontent.com/45561230/50446278-a2fd0e80-0914-11e9-806c-4f9481bcbca0.png)
https://youtu.be/xAuysLCO4Sg?t=58
Totem of Wrath should stack.
**Server Revision**: 2497

**Comment by Easyfraggy** [comment]
Merely a visual issue - they don't stack for real.

**Comment by Kuska101** [comment]
Cmon Easyfraggy, they do stack, there are plenty of evidence of that, despite this looking weird. This is the reason why 5ele mboxing was so popular back then. 
Read this thread for example, or any other first links in google.
https://www.dual-boxing.com/threads/11259-Totem-of-Wrath-stacking/page2

But you have to do something with this dude attitude, for this one as well https://github.com/Atlantiss/NetherwingBugtracker/issues/3663 the boy require some rest from wow testing.

**Comment by Wolffenstein** [comment]
Fixed in rev 2505.
