### ISSUE TITLE
[NPC] Haferet - Walking on top of the crates in the Trader's Tier leatherworking shop

### ISSUE THREAD

**Issue by Hidole555** [Atlantiss/NetherwingBugtracker#3668]
[//]: # (Enclose links to things related to the bug using http://wowhead.com or any other TBC database.)
[//]: # (You can use screenshot ingame to visual the issue.)
[//]: # (Write your tickets according to the format:)
[//]: # ([Quest][Azuremyst Isle] Red Snapper - Very Tasty!)
[//]: # ([NPC] Magistrix Erona)
[//]: # ([Spell][Mage] Fireball)
[//]: # ([Npc][Drop] Ghostclaw Lynx)
[//]: # ([Web] Armory doesnt work)
[//]: # (To find server revision type `.server info` command in the game chat.)

**Description**: 
Haferet (ID: 1, GUIDLow: 27209) the leatherworking supplies vendor in the Trader's Tier in the Exodar has a short route that causes her to walk on top of the crates of the store.
**Current behaviour**:
She walks around in a short, roughly circular path that causes her to stand on top of the crates in her store.
![image](https://user-images.githubusercontent.com/44522751/50446379-b5f6eb00-08e2-11e9-91ab-6e30c172ae82.png)

**Expected behaviour**: 
I do not know if she is stationary or not on retail but I am certain that she does not walk on top of the crates in her store.
**Server Revision**: 
2497

**Comment by Evolvee** [comment]
rev 2504
