### ISSUE TITLE
[NPC] Kolkar Marauder

### ISSUE THREAD

**Issue by totaemoeggerli** [Atlantiss/NetherwingBugtracker#367]
[//]: # (Enclose links to things related to the bug using http://wowhead.com or any other TBC database.)
[//]: # (You can use screenshot ingame to visual the issue.)
[//]: # (Write your tickets according to the format:)
[//]: # ([Quest][Azuremyst Isle] Red Snapper - Very Tasty!)
[//]: # ([NPC] Magistrix Erona)
[//]: # ([Spell][Mage] Fireball)
[//]: # ([Npc][Drop] Ghostclaw Lynx)
[//]: # ([Web] Armory doesnt work)

**Description**:
Kolkar Maurauder takes a strange path through the Stagnant Oasis. This mob escorts the Rare Elite Rocklance. There are two mobs of the same name, only one took a strange path.

**Current behaviour**:
https://gfycat.com/WholeShabbyGyrfalcon
The single mob in the pond wasn't in combat with anyone before it charged me.

**Expected behaviour**: 
The mob should stay at the side of the Rare Elite just like the other mob.

**Comment by aresbrutus** [comment]
Was working fine with me. The issue is probably trying to reconnect with the leader of the path.
