### ISSUE TITLE
[Quest][Dustwallow Marsh]  Corrosion Prevention

### ISSUE THREAD

**Issue by Rosos** [Atlantiss/NetherwingBugtracker#3670]
[//]: # (Enclose links to things related to the bug using http://wowhead.com or any other TBC database.)
[//]: # (You can use screenshot ingame to visual the issue.)
[//]: # (Write your tickets according to the format:)
[//]: # ([Quest][Azuremyst Isle] Red Snapper - Very Tasty!)
[//]: # ([NPC] Magistrix Erona)
[//]: # ([Spell][Mage] Fireball)
[//]: # ([Npc][Drop] Ghostclaw Lynx)
[//]: # ([Web] Armory doesnt work)
[//]: # (To find server revision type `.server info` command in the game chat.)

**Description**: 
While having the buff from the blue rays and using the dissolver on the ooz it gets dissolved but you get no progress on the quest.
**Current behaviour**:
Get no progress when dissolving the oozes
**Expected behaviour**: 
Should get 1/x progress per dissolved ooz
**Server Revision**:

**Comment by Evolvee** [comment]
https://github.com/Atlantiss/AtlantissTBCBT/issues/2661

**Comment by Evolvee** [comment]
![image](https://user-images.githubusercontent.com/1942409/50450094-e3b45200-092b-11e9-926e-169f08b2e897.png)
is not being given at the end of the channel 😡

**Comment by bekonja** [comment]
Still not working on v2555. Quest is incompletable.
