### ISSUE TITLE
[Spell][Shaman] Earth elemental sometimes puts you in combat in Shattrath

### ISSUE THREAD

**Issue by Brasso** [Atlantiss/NetherwingBugtracker#3671]
[//]: # (Enclose links to things related to the bug using http://wowhead.com or any other TBC database.)
[//]: # (You can use screenshot ingame to visual the issue.)
[//]: # (Write your tickets according to the format:)
[//]: # ([Quest][Azuremyst Isle] Red Snapper - Very Tasty!)
[//]: # ([NPC] Magistrix Erona)
[//]: # ([Spell][Mage] Fireball)
[//]: # ([Npc][Drop] Ghostclaw Lynx)
[//]: # ([Web] Armory doesnt work)
[//]: # (To find server revision type `.server info` command in the game chat.)

**Description**: 
Earth elemental sometimes puts you in combat in Shattrath which can cause guards to attack players of the opposite faction.
**Current behaviour**:
https://youtu.be/QwlQjxmrNn8

**Server Revision**: 
2497

**Comment by The14me** [comment]
rev.3472 not an issue anymore.
Can be closed.
