### ISSUE TITLE
[Talent][Rogue] Dirty deeds

### ISSUE THREAD

**Issue by Aeded** [Atlantiss/NetherwingBugtracker#3672]
**Description**: 
Doesnt increase dmg of  all abylities if target is below 35% hp (tested rupture+garrote=doesnt increase)
But when I tested eviscerate it did increase the dmg properly
**Current behaviour**:
Doesnt increase dmg of all abylities if target is below 35% hp
![image](https://user-images.githubusercontent.com/45561230/50449186-eca22500-0925-11e9-9f06-1c4c2ca30eb2.png)
![image](https://user-images.githubusercontent.com/45561230/50449205-0d6a7a80-0926-11e9-9b2a-ad131355fbd4.png)
Dmg is always 155 for garrote and 188 for rupture at any % of target hp

**Expected behaviour**: 
All abylities that deal dmg are supposed to do +20% more dmg agaist <35% hp target. (Anything but auto attacks) This dmg is supposed to stack with other dmg buffs like shadowstep or improved kydney shot etc... Only thing that this does not stack with is mangle (for garrote+rupture) from feral druid. If there is <35% hp target that has mangle debuff, only stronger effect (mangle=30% dmg on bleeds) takes effect
**Server Revision**: 2497

**Comment by Evolvee** [comment]
![image](https://user-images.githubusercontent.com/1942409/50450061-afd92c80-092b-11e9-8fa7-bfbe7b9bbdec.png)

![image](https://user-images.githubusercontent.com/1942409/50450066-b667a400-092b-11e9-81c0-8525bb136e09.png)

**Comment by Wolffenstein** [comment]
Fixed in rev 2504.
