### ISSUE TITLE
[Spell][Paladin] Blessing of Protection

### ISSUE THREAD

**Issue by Aeded** [Atlantiss/NetherwingBugtracker#3674]
**Description**: 
Paladin can use BoP while being CCd himself (by type physical cc) on other party members (tested with physical stun)

**Current behaviour**:
Paladin can use BoP while being CCd himself (by type physical cc) on other party members, even while stunned

**Expected behaviour**: 
You can approach this two ways:
1) Early tbc behaviour
"Patch 2.2.0: Blessing of Protection: This spell can no longer be cast on others when stunned. It can only be cast on self under those circumstances."
Which means you would just have to exclude physical stuns, and have BoP useable for most other physical CC like war fear/blind/scatter.

OR

2) Late tbc behaviour
http://www.arenajunkies.com/topic/26587-paladin-blind/#entry221646
"You **used to be able** to BoP others out of _(while having yourself)_ physical fear / blind as well. "
"you can still BoP others out of blind/intim shout as long as you have control of your character. "

Where you most likely, judging by the topic discussion above, were not able to use BoP on others while ccd at all.

**Server Revision**: 2497

**Comment by Aeded** [comment]
Im aware of that lol... but since _someone_ could consider late tbc comments somehow unreliable, I listed another option that they can choose from, so atleast the BoP is not useable while stunned.

**Comment by Evolvee** [comment]
I reported this back in 2016 and it was not clear what is stun and what isnt.(from the mechanical point of view) 
![image](https://user-images.githubusercontent.com/1942409/50455720-415a9580-0950-11e9-98ba-824951ba7f34.png)

this is on Sap as well for example ^^
![image](https://user-images.githubusercontent.com/1942409/50455731-4cadc100-0950-11e9-8dd2-3d82982a9916.png)

I guess I will just post everything from the old forum topic I made 3 years ago and let you try to deal with it 🤣 : 

https://github.com/ccshiro/cc-buglist/issues/1114
![image](https://user-images.githubusercontent.com/1942409/50455782-93032000-0950-11e9-826b-351410b002ef.png)

![image](https://user-images.githubusercontent.com/1942409/50455787-9bf3f180-0950-11e9-88d5-2d7f49acc552.png)
https://www.warmane.com/bugtracker/report/45087
![image](https://user-images.githubusercontent.com/1942409/50455810-b62dcf80-0950-11e9-8284-ec1f2c872296.png)
![image](https://user-images.githubusercontent.com/1942409/50455817-c0e86480-0950-11e9-8219-16b411b17217.png)
https://www.reddit.com/r/wowservers/comments/6c8zf5/how_many_people_will_there_be_on_warmane_tbc/dhsx3z0/
![image](https://user-images.githubusercontent.com/1942409/50455834-dc536f80-0950-11e9-999c-6d01544a70ca.png)

https://www.warmane.com/bugtracker/report/49737
![image](https://user-images.githubusercontent.com/1942409/50455836-e2e1e700-0950-11e9-9e0c-eebecf7cf593.png)


https://www.youtube.com/watch?v=htETzla0pio#t=15m31s

**Comment by Aeded** [comment]
🤔 Cool, but what exactly is the question here? First of all, are we going to completely ignore the post from AJ, which suggest that in late TBC you were not able to bop others while CCd yourself? There was probably some reason why in the end warmane chose to go with this solution over making BoP as it was in early tbc.

Or are we going for the early tbc BoP?
If yes then do you need me to specify which debuffs are considered as physical stun? Cause answer to that is very simple and can be found in your own post.

**Comment by Aeded** [comment]
### 2.4.3 BoP
 _(assuming from AJ post)_

**1)** You are **able** to use BoP on **yourself** while being CCd by **any** abylity that has school Physical. 
**2)** You are **unable** to use BoP on **others** if you do not have control of your character.
_I incline more to this option, because this is what warmane had done._

### 2.2.0 BoP
 _(assuming from the gathered info through years, posted together above by evolve)_

**1)** You are **able** use BoP on **yourself** while being CCd by **any** abylity that has school Physical.
**2)** You are **able** to use BoP on **others**, if you are under control of following physical abylities;

- **Druid:**
Maim

- **Hunter:**
Scatter Shot

- **Rogue:** 
Gouge
Blind
Sap

- **Warrior:**
Intimidating Shout

     _Hint; It is helpful to view it from point of Diminishing Returns. In other words it has to be school 
     Physical, and have DR different from Stun (controled, proc, stormherald)._ 

**3)** You are **unable** to use BoP on **others**, if you are under effect of any **physical stun** that falls into DR category of _**Stun**_ , _**Stun Proc**_ or **Stormherald** _(Disclaimer: Only helpful point view on the issue, dont take that literaly)_

- **Druid:**
Bash

- **Hunter:**
Improved Concussive Shot
Intimidation

- **Rogue:**
Cheap Shot
Kydney Shot
Mace Specialization Proc

- **Warlock:**
Intercept

- **Warrior:**
Concussion Blow
Intercept
Mace Specialization Proc
Charge
Improved Revenge Proc

     _btw: Even though Impact and Seal of Justice proc could appear to someone as physical, they are in 
             fact school Fire and Holy, just undispelable. BoP doesnt work on them at all, thats why they are 
             not on the list_

- **Tauren:**
Warstomp

- **Items:**

- _TBC:_
Brutal Earthstorm Diamond Proc
Deep Thunder, Stormherald Proc


- _Classic:_
Linken's Boomerang Stun Proc
The Unstoppable Force Proc
(Hammer of the Titans, Bludgeon of the Grinning Dog, The Chief's Enforcer, The Judge's Gavel) Proc
Hurd Smasher Proc

     _btw: Engineering bombs have school Fire and BoP doesnt work on them at all, thats why they are not 
              on the list_

This list should contain all PvP relevant stuns and stun procs that make you **unable** to use BoP on others. 
But of course there are other abylities which are being used in PvE encounters that should be on the list aswell. List would be very long If I were to include them all. But again, if they have **school physical** and **mechanic stun** then they would be on the list aswell.

Like I already said, I incline for the way easier 2.4.3 behaviour that is supported by AJ topic. And worth to mention that it is what warmane had done. Warmane has unironicaly one of the most knownledgable and experienced people around wow emu, so one can safely assume that there was a good reason behind their decision about BoP.

**Comment by Wolffenstein** [comment]
Fixed in rev 3368.
