### ISSUE TITLE
[Spell][Priest] Prayer of mending LoS

### ISSUE THREAD

**Issue by Aeded** [Atlantiss/NetherwingBugtracker#3676]
**Description:** Prayer of Mending ignores LoS.

**Current behaviour:** Prayer of Mending ignores LoS.

**Expected behaviour:** Prayer of Mending should not bounce if players are not in line of sight, it should only consume 1 charge of the buff and disappear.

Proof:
https://youtu.be/MdXsUkc7ZA0?t=11
https://youtu.be/MdXsUkc7ZA0?t=728
https://youtu.be/NMkgJmSiMc4?t=80
https://youtu.be/6JjgpeS0YDU?t=250
https://youtu.be/6JjgpeS0YDU?t=642
https://youtu.be/NMkgJmSiMc4?t=517
https://youtu.be/6JjgpeS0YDU?t=619  (watch the enemy team PoM)
https://youtu.be/MdXsUkc7ZA0?t=185

inb4 _someone_ is going to close the issue, becuse they play priest. #2765 Link one single clip where it actualy ignores textures and **clearly** bounces through them.

**Server Revision:** 2497

**Comment by Wolffenstein** [comment]
Fixed in rev 2508.
