### ISSUE TITLE
[NPC Movement] scout stronghand

### ISSUE THREAD

**Issue by DarthNekr0s** [Atlantiss/NetherwingBugtracker#368]
**Description**:  i couldnt get a video of this while he was doing it but orgrimmar npc Scout Stronghand was clipping into the ground as he walked in the grey stone tunnel entrance part of org. movement was normal when he exited onto normal ground though.

**Current behaviour**: npc clips into ground from about his calfs

**Expected behaviour**:  to walk normally on the ground surface

**Server Revision**: 2040

**Comment by The14me** [comment]
https://www.wowhead.com/npc=14375

**Comment by Evolvee** [comment]
reworked the waypoint patrol in next hotfix rev
