### ISSUE TITLE
[Core][Spell][Arcane Missiles] More powerful spell is already active.

### ISSUE THREAD

**Issue by killablink** [Atlantiss/NetherwingBugtracker#3680]
**Description**: If you cast a high rank AM, and try to interrupt it by casting another AM but of lower rank, it doesn't allow you and says a more powerful spell is already active.

**Current behaviour**: If you cast a high rank AM, and try to interrupt it by casting another AM but of lower rank, it doesn't allow you and says a more powerful spell is already active.

**Expected behaviour**: Should be able to interrupt your own cast with a different rank of the spell.

**Server Revision**: 2497

**Comment by Wolffenstein** [comment]
Fixed in rev 2511.
