### ISSUE TITLE
[Dungeon] Old Hillsbrad Foothills - strange behaviour of the pack infront of the castle

### ISSUE THREAD

**Issue by adrenochrom** [Atlantiss/NetherwingBugtracker#3682]
**Description**: 
The Pack infront of the castle can't decied if infight or outfight.
https://clips.twitch.tv/BlitheExpensiveVampireThisIsSparta
full: https://www.twitch.tv/videos/354854472?t=00h38m25s

**Current behaviour**:
- infight / outfight every 2 seconds

**Expected behaviour**: 
- pack wasn't pulled so it should be just standing there

**Server Revision**: 
2497

**Comment by Easyfraggy** [comment]
It's the stoneskin totem pulling them and somehow they reset instead of attacking the group.

**Comment by Manaci** [comment]
Dead issue
