### ISSUE TITLE
[Quest][Feralas] Screecher Spirits

### ISSUE THREAD

**Issue by Rosos** [Atlantiss/NetherwingBugtracker#3683]
[//]: # (Enclose links to things related to the bug using http://wowhead.com or any other TBC database.)
[//]: # (You can use screenshot ingame to visual the issue.)
[//]: # (Write your tickets according to the format:)
[//]: # ([Quest][Azuremyst Isle] Red Snapper - Very Tasty!)
[//]: # ([NPC] Magistrix Erona)
[//]: # ([Spell][Mage] Fireball)
[//]: # ([Npc][Drop] Ghostclaw Lynx)
[//]: # ([Web] Armory doesnt work)
[//]: # (To find server revision type `.server info` command in the game chat.)

**Description**: 
Should be able to kill the Vale Screechers in Feralas and then use the Yeh'kinya's Bramble (item provided) to summon the spirit of the screecher and then talk to spirit and get the essence ( item needed for quest).
**Current behaviour**:
Nothing happens when you killed the screecher and using the Yeh'kinya's bramble on it. Just start of animation and instant cancel.
**Expected behaviour**: 
Should do a channel and when done a spirit should appear and interactable to give you the essence.
**Server Revision**:

**Comment by maxturtlesc2** [comment]
Aren't you supposed to use the item when the mob is still alive?

**Comment by Rosos** [comment]
"Take this bramble wand and go to Feralas. Find and defeat vale screechers in southern and central Feralas, then wave my bramble over their fallen bodies. This will coax their spirit to reveal itself. Touch the spirit and collect its essence."

**Comment by Tenoutoften** [comment]
Something has broken the interaction with using items with dead bodies recently.... This quest use to work

**Comment by totaemoeggerli** [comment]
same with "testing the vessel" in hinterlands/feralas

**Comment by aresbrutus** [comment]
@Evolvee important quest in chain quest breaking.

**Comment by Evolvee** [comment]
Its a core issue, nothing I can do about it, with all spells(quest items) that should be used on dead bodies: https://github.com/Atlantiss/NetherwingBugtracker/issues/3803

**Comment by RealZwox** [comment]
Im not 100% sure if this npc is dead aswell 
https://classicdb.ch/?quest=2561
But this quest seems to work.

**Comment by Mikik3jr** [comment]
Now it works again, but I can take more credits if I click really fast multiple times on the spirit.

**Comment by Evolvee** [comment]
reworked in rev 2655
