### ISSUE TITLE
[UI] Friends List not showing player status

### ISSUE THREAD

**Issue by Hidole555** [Atlantiss/NetherwingBugtracker#3684]
[//]: # (Enclose links to things related to the bug using http://wowhead.com or any other TBC database.)
[//]: # (You can use screenshot ingame to visual the issue.)
[//]: # (Write your tickets according to the format:)
[//]: # ([Quest][Azuremyst Isle] Red Snapper - Very Tasty!)
[//]: # ([NPC] Magistrix Erona)
[//]: # ([Spell][Mage] Fireball)
[//]: # ([Npc][Drop] Ghostclaw Lynx)
[//]: # ([Web] Armory doesnt work)
[//]: # (To find server revision type `.server info` command in the game chat.)

**Description**: 
Adding a player initially causes them to be added to the Friends List as a "Level 0 Unknown". If either the player that added or the player that was added to friends logs out and logs back in, the Friends List will not detect the Online presence of the added player and will remain in an Offline state as well as being described only as "Unknown".
**Current behaviour**:
The details of online friends are not being detected and they do not appear as online when logging in.
![image](https://user-images.githubusercontent.com/44522751/50486354-a30a1680-09c7-11e9-8d12-a0733a564c81.png)

**Expected behaviour**: 
The friends list should indicate when a friend is online as well as their level and class.
**Server Revision**: 
2497

**Comment by RandomGuyFromDiscordServer** [comment]
If you add someone. then close friends list and open it again, it will show him as offline.

**Comment by Wolffenstein** [comment]
It works fine for me, do you have any addons that could affect it?

Please record the whole process, maybe I'm doing something wrong.

**Comment by RandomGuyFromDiscordServer** [comment]
Disabled all the addons, still says unknown and offline.

**Comment by RandomGuyFromDiscordServer** [comment]
@Wolffenstein https://youtu.be/Irlnjpe9O4Y

**Comment by Kidtoucher** [comment]
the online bug still persists. it happened to a few players at least.

**Comment by Wolffenstein** [comment]
Fixed in rev 2559.
