### ISSUE TITLE
[NPC][Durotar] Den Grunt on top bonfire in Valley of Trials

### ISSUE THREAD

**Issue by Brasso** [Atlantiss/NetherwingBugtracker#3687]
[//]: # (Enclose links to things related to the bug using http://wowhead.com or any other TBC database.)
[//]: # (You can use screenshot ingame to visual the issue.)
[//]: # (Write your tickets according to the format:)
[//]: # ([Quest][Azuremyst Isle] Red Snapper - Very Tasty!)
[//]: # ([NPC] Magistrix Erona)
[//]: # ([Spell][Mage] Fireball)
[//]: # ([Npc][Drop] Ghostclaw Lynx)
[//]: # ([Web] Armory doesnt work)
[//]: # (To find server revision type `.server info` command in the game chat.)

**Description**: 
Title.
![wowscrnshot_122818_000714](https://user-images.githubusercontent.com/44345420/50497351-02ebd600-0a37-11e9-9fff-42a015c7ea36.jpg)

**Server Revision**: 
2515

**Comment by Brasso** [comment]
Seems to be fine now. I think you're right Swiftie, unless Kutsal fixed it.

**Comment by aresbrutus** [comment]
GM thing, working fine otherwise.
