### ISSUE TITLE
[Hunter][Spell] Can't queue any spells in a macro

### ISSUE THREAD

**Issue by Zarant** [Atlantiss/NetherwingBugtracker#3688]
It's not possible to queue any spell if you have this spell bound to a macro starting with /cast !Auto Shot
Whenever you do that, it triggers a GCD and the spell doesn't go off.

Server revision: 2515

**Comment by gwxse8w** [comment]
macros like:
```/cast !Auto Shot
/cast Steady Shot```

and:
```/cast !Auto Shot
/castsequence reset=2.73 Steady Shot, Arcane Shot, Steady Shot, Steady Shot```

don't work correctly.

**Comment by Wolffenstein** [comment]
Please recheck in revision 2537.

**Comment by Zarant** [comment]
It's working as intended now.
