### ISSUE TITLE
Cant put any kinda of gems in Shoulderpads of the Stranger

### ISSUE THREAD

**Issue by yoloteddy** [Atlantiss/NetherwingBugtracker#3689]
I cant use gems in that item.

**Comment by RandomGuyFromDiscordServer** [comment]
Because it doesn't have gem socket at 2.0.3 
https://web.archive.org/web/20070501204542/http://www.thottbot.com:80/i30055

**Comment by aresbrutus** [comment]
Delete your cache folder.
