### ISSUE TITLE
[Quest][Azuremyst Isle][Galaen's Fate]

### ISSUE THREAD

**Issue by jay070** [Atlantiss/NetherwingBugtracker#369]
[//]: # (Enclose links to things related to the bug using http://wowhead.com or any other TBC database.)
[//]: # (You can use screenshot ingame to visual the issue.)
[//]: # (Write your tickets according to the format:)
[//]: # ([Quest][Azuremyst Isle] Red Snapper - Very Tasty!)
[//]: # ([NPC] Magistrix Erona)
[//]: # ([Spell][Mage] Fireball)
[//]: # ([Npc][Drop] Ghostclaw Lynx)
[//]: # ([Web] Armory doesnt work)

**Description**: 
after 1hour farming sunhawk reclaimer, still no drop of the Galaen's Amulet.
killed the camp 2 x now.
**Current behaviour**:

**Expected behaviour**: 

**Server Revision**:

**Comment by The14me** [comment]
https://www.wowhead.com/quest=9579/galaens-fate
https://www.wowhead.com/item=23873/galaens-amulet

**Comment by jay070** [comment]
the Amulet dropt now, so it seems i'm extreme unlucky on drop chances.

**Comment by Firroth** [comment]
I dropped it after 10-15min. with another person. Drop is low yea, but quest works fine.
