### ISSUE TITLE
Under City Fatal Fall Damageg

### ISSUE THREAD

**Issue by WarriorTSW** [Atlantiss/NetherwingBugtracker#3691]
[//]: # (Enclose links to things related to the bug using http://wowhead.com or any other TBC database.)
[//]: # (You can use screenshot ingame to visual the issue.)
[//]: # (Write your tickets according to the format:)
[//]: # ([Quest][Azuremyst Isle] Red Snapper - Very Tasty!)
[//]: # ([NPC] Magistrix Erona)
[//]: # ([Spell][Mage] Fireball)
[//]: # ([Npc][Drop] Ghostclaw Lynx)
[//]: # ([Web] Armory doesnt work)
[//]: # (To find server revision type `.server info` command in the game chat.)

**Description**: 
Dying from fall damage that shouldnt kill while in Under City
**Current behaviour**:
https://youtu.be/XKxFJRmnMxQ
**Expected behaviour**: 
Much smaller amount of dmg
**Server Revision**: 
2515

**Comment by WarriorTSW** [comment]
Just died in the same area. This time falling into water

**Comment by Peglaa** [comment]
Can you try some other places? Or is this strictly tied to UC? I know wolf made some height changes recently mybe that broke it?

**Comment by RandomGuyFromDiscordServer** [comment]
I tried it and i only take 800 fall damage..

**Comment by Wolffenstein** [comment]
I didnt change anything with height.

**Comment by wtRCH** [comment]
Might it be tied with elevator?

**Comment by Hidole555** [comment]
You might be on to something wtRCH. It may very well be the elevator. I was able to recreate the bug just now on two characters. I went up the elevator, stepped out, stepped back in, rode the elevator back down, and then performed the same maneuver seen in the above video. My character a Blood Elf Paladin with the Black War Wolf. I also had 3/3 Pursuit of Justice. When my character landed he died instantly.
My second character was a Tauren warrior. This time when I rode the elevator up, I did not step out and back in. I rode the elevator back down and did the same jump from the video which resulted in a dead cow.

**Comment by Hidole555** [comment]
@Wolffenstein here you go mate
https://youtu.be/DRIIwGdjCNo

It took me a few tries to recreate it, I was almost ready to assume it was stealth-fixed somehow.

**Comment by Hidole555** [comment]
New comment because I got curious and went looking to see if other areas have a similar problem.
Here is footage of the elevator at Telredor I took a couple minutes ago showcasing a similar glitch: https://youtu.be/oXPhayDW7Sc

**Comment by Brasso** [comment]
Perhaps player position isn't updated during the elevator ride? Looks like it still has the height position at the top of the elevator therefore you take maximum falling damage.

**Comment by Wolffenstein** [comment]
Should be fixed after revision 2523.
