### ISSUE TITLE
[Item][set]Tirisfal Regalia 4/5 set bonus not working on channeled crits of Arcane missiles

### ISSUE THREAD

**Issue by ircfelix** [Atlantiss/NetherwingBugtracker#3697]
**Description**: 
According to the tooltip, the 4/5 set bonus of the "Tirisfal Regalia" should grant you 70 spell damage on a spell crit.

**Current behaviour**:
If you crit with Arcane Missiles, you will not get the buff from the 4/5 set bonus on every crit of AM.

**Expected behaviour**: 
If you crit with Arcane Missiles, you should get the buff from the 4/5 set bonus on every crit of AM.

**Server Revision**: 
2515

**Comment by Wolffenstein** [comment]
Should be fixed.
