### ISSUE TITLE
[Spell][Shaman] Earth Shield is 2.4.0 state

### ISSUE THREAD

**Issue by Doom1337** [Atlantiss/NetherwingBugtracker#3698]
**Description**: 
Earth Shield is not like it should be in a pre-2.4.0 State. While this is a miniscule thing, merely a QoL change PvE wise. Blizzard did it to lower the cost of re-applying earth shield due dispels and what-not (was a pvp focused change because dispels removes the entirety of earth shield instead of charges up until wotlk)

**Current behaviour**:
Currently Earth Shield costs **450 mana, 6 charges.** Talented Tidal Focus 5/5 Brings it down to 427

**Expected behaviour**: 
Earth Shield should cost **900 mana, 10 charges.** (not talented Tidal Focus)

[wowwiki](http://wowwiki.wikia.com/wiki/Earth_Shield)
" Patch 2.4.0 (25-Mar-2008): Number of charges reduced from 10 to 6. Mana cost reduced by 50%."

**Server Revision**: 
2515

**Comment by killablink** [comment]
Spells are using 2.4.3 mechanics, which means that it is correct currently.

**Comment by Doom1337** [comment]
> Spells are using 2.4.3 mechanics, which means that it is correct currently.

Then my bad if that's the case!
