### ISSUE TITLE
[NPC] Scarlet Convert & Scarlet Initiate Spawn Texture Bug

### ISSUE THREAD

**Issue by towneh** [Atlantiss/NetherwingBugtracker#37]
**Description**: 
When the Scarlet Convert & Scarlet Initiate spawns in Deathknell, they appear briefly as a texture-less model, which immediately disappears before the correct NPC with pathing behaviour then takes its place.

**Expected behaviour**: 
NPC appears without this texture-less ghost effect beforehand.

**Comment by Wolffenstein** [comment]
Fixed in rev 2020.
