### ISSUE TITLE
Baron Longshore WANTED quest south of ratchet

### ISSUE THREAD

**Issue by illiji** [Atlantiss/NetherwingBugtracker#370]
[//]: # ([Quest][The Barrens] WANTED: Baron Longshore)
[//]: # ([NPC] Baron Longshore)

**Description**:  NPC for quest doesn't spawn

**Current behaviour**: mob doesn't spawn

**Expected behaviour**: mob spawns at 1 of a few camps on the coast south of ratchet

**Server Revision**:

**Comment by Evolvee** [comment]
he has 4 possible spawn points, did you check all of them?

**Comment by DarthNekr0s** [comment]
killed him just now at 64,47

**Comment by Evolvee** [comment]
ok, closing then
