### ISSUE TITLE
[Spell][Shaman] Lightning Overload trigger Chain lightning cooldown

### ISSUE THREAD

**Issue by Kuska101** [Atlantiss/NetherwingBugtracker#3700]
**Description**: 
Lightning overload proc trigger refresh of Chain lightning cd back to 6 sec

**Current behaviour**:
Lightning overload proc trigger refresh of Chain lightning cd back to 6 sec
vid: https://streamable.com/j1xzb (spellbars, you can see how CL cd trigger again short after on Overload proc)

**Expected behaviour**: 
Lightning overload should not affect cooldown of Chain lightning in any way

**Server Revision**: 
2515

**Comment by Wolffenstein** [comment]
Proof? Even if I disable the serverside cooldown application, it will still be visually bugged because the procced Lightning Overload spell has the same cooldown category as Chain Lightning (which causes the client to apply cooldown visually).

**Comment by Tereneckla** [comment]
Fixed
