### ISSUE TITLE
[Core][PvP] Combat not dropping after being attacked by hunter/chased by pet

### ISSUE THREAD

**Issue by Jacksn5** [Atlantiss/NetherwingBugtracker#3702]
[//]: # (Enclose links to things related to the bug using http://wowhead.com or any other TBC database.)
[//]: # (You can use screenshot ingame to visual the issue.)
[//]: # (Write your tickets according to the format:)
[//]: # ([Quest][Azuremyst Isle] Red Snapper - Very Tasty!)
[//]: # ([NPC] Magistrix Erona)
[//]: # ([Spell][Mage] Fireball)
[//]: # ([Npc][Drop] Ghostclaw Lynx)
[//]: # ([Web] Armory doesnt work)
[//]: # (To find server revision type `.server info` command in the game chat.)

**Description**:
Combat should've faded around 0:07, doesn't drop till 0:55
[![Combat Lasting Too Long](http://img.youtube.com/vi/UEJ2p79WH9g/0.jpg)](https://www.youtube.com/watch?v=UEJ2p79WH9g "Combat Lasting Too Long")

**Comment by The14me** [comment]
Rev.3472 not an issue anymore.
Can be closed.
