### ISSUE TITLE
[Core][Flight path] Flying too slowly + bunch of issues

### ISSUE THREAD

**Issue by killablink** [Atlantiss/NetherwingBugtracker#3703]
**Description**: Flying speed on a flight path randomly goes super slow:
https://gfycat.com/EquatorialLiquidAmericancrow

After reaching the point, I blinked and got teleported here:
https://gfycat.com/TeemingCaringGnatcatcher

I could cast but at the same time couldn't cast anything on my mount. The game was thinking I was still on a flight path. I would blink and it doesn't actually move me anywhere. Also couldn't talk to the flight master or anyone. Had to log off

**Expected behaviour**: Normal flightpath behavior

**Server Revision**:

**Comment by Emtec** [comment]
Fixed.
