### ISSUE TITLE
[MOB][Fenissa the Assassin

### ISSUE THREAD

**Issue by killablink** [Atlantiss/NetherwingBugtracker#3704]
**Description**: Attacks you but is still in stealth, can kill you without ever appearing, and she doesn't appear as doing dmg in your combat log

**Current behaviour**: Attacks you but is still in stealth, can kill you without ever appearing, and she doesn't appear as doing dmg in your combat log

**Expected behaviour**: Should leave stealth after attacking

**Server Revision**:

**Comment by Evolvee** [comment]
rev 2538
