### ISSUE TITLE
[Misc] Flying mounts loose the ability to fly after knockback

### ISSUE THREAD

**Issue by Geigerkind** [Atlantiss/NetherwingBugtracker#3705]
**Current behaviour**:
Knockbacks remove the flying effect of a flying mount.

**Expected behaviour**: 
That should not happen.

**Server Revision**: 2522

**Reproduction steps**: 
Go to Netherstorm: Ruins of Farahlon and fly near one of these Hound of Culuthas.

**Comment by Mewmewww** [comment]
I know wowwiki isn't the best site for citations, however: https://imgur.com/a/ynrmQ12

**Comment by Kaini27** [comment]
I remember getting knockback from Halaa guards in nagrand disabled flying on mine drake back in the days on retail.

**Comment by RealZwox** [comment]
https://www.youtube.com/watch?v=pWlBr_fT6bI

I found this. And Typhoon is a knockback if i remember correctly.

**Comment by RealZwox** [comment]
https://www.youtube.com/watch?v=d50EFzc0_Uc

you can even do it with items that morphs people in something else.
Some GM should test if that is working correctly.

**Comment by killablink** [comment]
Typhoon is a wotlk spell and the morph was before immunity was given to flying mounts. You could sheep people out of the flying mounts but people complained so there was immunity given after.

**Comment by RealZwox** [comment]
https://www.youtube.com/watch?v=pWlBr_fT6bI

The Typhoon was pre Wotlk spell prob a pre and last patch of tbc.

**Comment by knasen88** [comment]
knockback did dismount before some wotlk patch, this is invalid
https://wow.gamepedia.com/Patch_3.3.0

> Knockbacks  no longer dismount players. If on a flying mount, you will be knocked back a short distance before being able to resume flying.

**Comment by Mikik3jr** [comment]
A mob called Hound of Culuthas knocked me away while I was flying, then my fly mount lost the ability to fly and behaved like a normal 60% ground mount.

**Comment by femdead** [comment]
how is this `needs research` lmao

**Comment by Rixh1** [comment]
Can confirm this behavior, it might be supposed to dismount you, but make your 280% gryphon a 100% ground mount? Think not.

**Comment by someotherplayer** [comment]
https://www.youtube.com/watch?v=MYqzp6zRdiY

Can confirm. I guess "need research" is for deciding if they should dismount you or not.

**Comment by The14me** [comment]
Rev.3472 not an issue anymore. At knockdown, it dismounts u now.
Can be closed.
