### ISSUE TITLE
[Item][Set] Trisifal Reglia 4 Set Bonus doesnt stack with Serpent Coil Braid

### ISSUE THREAD

**Issue by Dynastyy** [Atlantiss/NetherwingBugtracker#3706]
[//]: # (Enclose links to things related to the bug using http://wowhead.com or any other TBC database.)
[//]: # (You can use screenshot ingame to visual the issue.)
[//]: # (Write your tickets according to the format:)
[//]: # ([Quest][Azuremyst Isle] Red Snapper - Very Tasty!)
[//]: # ([NPC] Magistrix Erona)
[//]: # ([Spell][Mage] Fireball)
[//]: # ([Npc][Drop] Ghostclaw Lynx)
[//]: # ([Web] Armory doesnt work)
[//]: # (To find server revision type `.server info` command in the game chat.)

**Description**: 
Trisifal Reglia 4 Set Bonus doesnt stack with Serpent Coil Braid

**Current behaviour**:
When you use Mana Gem (which triggers the on use effect of Serpen Coil Braid) it overwrites the T5 Mage 4 Set procc. While the Serpent Coil Braid buff is active you cant gain, the 4 Set bonus procc.

**Expected behaviour**: 
4 Set bonus and Serpent Coil Braid should stack

**Server Revision**: 
2522

**Comment by Tereneckla** [comment]
Fixed
