### ISSUE TITLE
[Dungeon][NPC] Shirrak the Dead Watcher [Spell] Carnivorous Bite

### ISSUE THREAD

**Issue by Anduyon** [Atlantiss/NetherwingBugtracker#3708]
**Description**: 
The Boss is using his Carnivorous Bite spell way too often. Tested on heroic.
**Current behaviour**:
https://www.twitch.tv/videos/340133416?t=01h36m20s
I do not have a recording of the run we did today but his behaviour is roughly the same to what is seen in this video. Sometimes you will even get 2 stacks one after the other, even when you have been pulled to him as a ranged character.
**Expected behaviour**: 
Carnivorous Bite: Melee range bleed debuff that is applied on all nearby players roughly every ten seconds. This can stack if you stay in melee range, dealing considerable damage. He seems to always trigger it right after using "Attract Magic" (so that everyone getting pulled in will get it before being able to move away). 
https://www.youtube.com/watch?v=rPPpZz6cCMU
An example of the fight from the tanks pov can be found here.
**Server Revision**:

**Comment by Easyfraggy** [comment]
Can confirm - this has been bugged for a long time - I think theres another report on this issue - or I have one on the other tracker still open not sure.

**Comment by devo6969** [comment]
Still bugged, seems that he is casting it one after another, one point its 3 times in a row . In the youtube video that Anduyon posted seemed odd that the dot removed itself with 4 seconds left with no pally in the group (prob a blizz bug)

PTR - https://www.youtube.com/watch?v=9cyAcUwyZZo

**Comment by Wolffenstein** [comment]
Fixed in rev 3443.
