### ISSUE TITLE
[Profession] Ragesteel patterns

### ISSUE THREAD

**Issue by rychersky** [Atlantiss/NetherwingBugtracker#3709]
[//]: # (Enclose links to things related to the bug using http://wowhead.com or any other TBC database.)
[//]: # (You can use screenshot ingame to visual the issue.)
[//]: # (Write your tickets according to the format:)
[//]: # ([Quest][Azuremyst Isle] Red Snapper - Very Tasty!)
[//]: # ([NPC] Magistrix Erona)
[//]: # ([Spell][Mage] Fireball)
[//]: # ([Npc][Drop] Ghostclaw Lynx)
[//]: # ([Web] Armory doesnt work)
[//]: # (To find server revision type `.server info` command in the game chat.)

**Description**: Ragesteel Blacksmithing patterns became available in Patch 2.2.

![image](https://user-images.githubusercontent.com/45608488/50541203-d1b9f580-0b5d-11e9-9ef3-9aaaa17e4eba.png)

**Current behaviour**: On the PTR they are listed on the Blacksmithing Patterns vendor.

**Expected behaviour**: These patterns should not be available until Patch 2.2. 
https://www.wowhead.com/item=33174/plans-ragesteel-shoulders
http://wowwiki.wikia.com/wiki/Ragesteel_Shoulders

(Respective Wowhead and Wowwiki pages for the actual Burning Rage set doesn't indicate what patch they were released).

**Server Revision**: 2522

**Comment by Shanghi** [comment]
Only the shoulders were added in 2.2 and it's already set that way. Those other 3 were always there and there's old 2.0 comments about them on each one like:
![image](https://user-images.githubusercontent.com/2672633/50545010-4a0fcd80-0bd5-11e9-9060-1378732e7de8.png)
![image](https://user-images.githubusercontent.com/2672633/50545013-52680880-0bd5-11e9-9183-e31837cf678e.png)
![image](https://user-images.githubusercontent.com/2672633/50545025-893e1e80-0bd5-11e9-91eb-e12a71878bab.png)
