### ISSUE TITLE
Rogue pickpocket quest item 

### ISSUE THREAD

**Issue by Ershank** [Atlantiss/NetherwingBugtracker#3710]
**Description**: 
As a new lvl 70 char, tried to complete the rogue poison quest in westfall by pickpocketing the key from the guardsmen in the southeast tower. I saw the key, I pickpocketed the key, but the key did not show up in my inventory. On subsequent attempts after NPC was reset, I was not able to pickpocket the key because I 'can only have 1 of these items' (but did not have it in inventory)

**Current behaviour**:
Can not loot quest item from mob using pickpocket

**Expected behaviour**: 
Pick pocketed item shows up in inventory

**Comment by Wolffenstein** [comment]
Have you checked your keyring?

**Comment by Ershank** [comment]
Ahh sorry I did not. That's probably it. Thanks for the reply
