### ISSUE TITLE
Spirit of Redemption movable

### ISSUE THREAD

**Issue by nycheia** [Atlantiss/NetherwingBugtracker#3711]
**Current behaviour**:
https://clips.twitch.tv/ZanyPunchyDiamondHumbleLife
You can move when in Spirit of Redemption form.

**Expected behaviour**: 
You shouldn't be able to move.

**Server Revision**: 
2522

**Comment by Tenoutoften** [comment]
I just tested this by dying normally and couldn't so something must trigger for this to happen, surely?

**Comment by nycheia** [comment]
> I just tested this by dying normally and couldn't so something must trigger for this to happen, surely?

Yeah i tested it regularly as well, couldn't move either. But something else triggers the movable stuff i guess, i just dont know what.

**Comment by Tenoutoften** [comment]
Does the guy in the clip have any idea?

**Comment by nycheia** [comment]
> Does the guy in the clip have any idea? Unless that's you of course...

I'll ask him, i was just watching stream.

**Comment by Drayo** [comment]
On other Servers it happened when Priests were killed by a spell that moves them (big knockback or lurker spout for example) sometimes it also happened when they were jumping around and died mid-air.

**Comment by Wolffenstein** [comment]
I have no idea how to reproduce it.

**Comment by Brasso** [comment]
It's hard to see but it looks like the priest jumps the instant he is killed. https://www.youtube.com/watch?v=BeBbqTCKJEM&feature=youtu.be

**Comment by nycheia** [comment]
I cant reproduce it either, no matter how i jump when i die, nor wether if i jump off objects or on to objects.

**Comment by Brasso** [comment]
Looks like he dies to immolate, maybe a combination of dot damage and jumping?

**Comment by AxeCell** [comment]
This is a common occurance on other private servers. It happens if the priest either gets knocked in the air and dies, or if they manually jump while dying.

**Comment by Wolffenstein** [comment]
I can't reproduce it with either.

**Comment by Manaci** [comment]
Fixed
