### ISSUE TITLE
Can't mount after HC / using portal from mage

### ISSUE THREAD

**Issue by Tholinx** [Atlantiss/NetherwingBugtracker#3712]
[//]: # (Enclose links to things related to the bug using http://wowhead.com or any other TBC database.)
[//]: # (You can use screenshot ingame to visual the issue.)
[//]: # (Write your tickets according to the format:)
[//]: # ([Quest][Azuremyst Isle] Red Snapper - Very Tasty!)
[//]: # ([NPC] Magistrix Erona)
[//]: # ([Spell][Mage] Fireball)
[//]: # ([Npc][Drop] Ghostclaw Lynx)
[//]: # ([Web] Armory doesnt work)
[//]: # (To find server revision type `.server info` command in the game chat.)

**Description**: 
When I want to use mount it shows "You can't do that yet"
https://i.imgur.com/BbZfXi6.png

**Current behaviour**:
We did SV after that I've used portal from mage to SC. And now I can't mount.

**Expected behaviour**: 
I should be able to mount xD

**Server Revision**:  
2522

**Comment by Tholinx** [comment]
Now it work fine after like 5-10minutes, but it's annoying.

**Comment by Wolffenstein** [comment]
Can't reproduce

**Comment by Tholinx** [comment]
I will record it next time, it happened even to one guy in previous group.

**Comment by Tholinx** [comment]
Happened again today after ramparts, I left group, then server restarted (update) then I used HS and again i can't mount.

**Comment by Tereneckla** [comment]
dead issue
