### ISSUE TITLE
[Item] Fel Reaver's Piston

### ISSUE THREAD

**Issue by Saben65** [Atlantiss/NetherwingBugtracker#3713]
**Description**: 
[Fel Reaver's Piston](https://web.archive.org/web/20070408043254/http://www.thottbot.com:80/i30619) is supposed to heal for a total of 500 over 12 seconds. 

**Current behaviour**:
Currently the proc [Regeneration](https://web.archive.org/web/20071113175553/http://thottbot.com:80/s38324) heals 500 per tick, for a total of **2000 hp**.

> Gelyn gains Regeneration. 
Gelyn's Flash of Light heals Gelyn for 1427. 
**Gelyn gains 500 health from Gelyn's Regeneration. 
Gelyn gains 500 health from Gelyn's Regeneration. 
Gelyn gains 500 health from Gelyn's Regeneration.
Gelyn gains 500 health from Gelyn's Regeneration.** 
Regeneration fades from Gelyn.

**Expected behaviour**: 
[Regeneration](https://web.archive.org/web/20071113175553/http://thottbot.com:80/s38324) should heal 4 times, once every three seconds for 125 each.

**Server Revision**: 
2526

**Comment by xmesaj2** [comment]
![image](https://user-images.githubusercontent.com/550384/50572690-97eb2800-0dc5-11e9-8a90-e1b0a26fc07e.png)
works fine

**Comment by Saben65** [comment]
I disagree. After further testing, the issue is that it is currently scaling exceptionally well with bonus healing. At 1700 bonus healing, it is ticking for 467, with 5/5 Holy guidance that goes up to a cap of 500 per tick.

![image](https://user-images.githubusercontent.com/1936487/50573819-b12dad80-0da0-11e9-9df7-cf846497f1e1.png)
First proc is with 1700+ bonus healing, 5/5 Holy Guidance.
Second proc is naked, just with 5/5 Holy Guidance.

[Comment from 2.2.3](https://www.wowhead.com/item=30619/fel-reavers-piston#comments:id=157726:reply=18437) stating it was healing for a total of 500.
[Comment from 2.4.2](https://www.wowhead.com/item=30619/fel-reavers-piston#comments:id=290822:reply=47260) Identifying talents increasing the healing tick, but not bonus healing.

The spell should benefit from +healing talents like it currently does; however, it should not benefit from Bonus Healing, or it should benefit very poorly, like fractions of a percent if we are to [believe this comment](https://www.wowhead.com/item=30619/fel-reavers-piston#comments:id=254079).

**Comment by aresbrutus** [comment]
The issue is that you didn't make it clear that bonus healing and/or talents are involved in your original post. Re-opening this.

**Comment by xmesaj2** [comment]
rev 2556
