### ISSUE TITLE
Warlock Imp pet cannot attack NPC walking away because does the pet does not close the gap enough before casting

### ISSUE THREAD

**Issue by Ominouss** [Atlantiss/NetherwingBugtracker#3714]
https://gfycat.com/UnawareWhoppingBongo

**Description**: 
Warlock Imp pet cannot attack NPC walking away because does the pet does not close the gap enough before casting
**Current behaviour**:
Warlock Imp pet cannot attack NPC walking away because does the pet does not close the gap enough before casting
**Expected behaviour**: 
Warlock Imp pet should be able to attack NPC walking away because the pet does close the gap enough before casting. Maybe this happens to me because of 150-180ish latency?

**Server Revision**: 
[02:50] AtlantissCoreTBC - Server Revision: 2526 [Branch: master, Hash: c2eb59825556] 
[02:50] Online players: 126 (max: 129) 
[02:50] Active connections: 129 (max: 132) Queued connections: 0 (max: 0) 
[02:50] Server uptime: 44 Minute(s) 22 Second(s). 
[02:50] Current time: 2018-12-29_23-51-27 
[02:50] Content Patch: 203.

**Comment by The14me** [comment]
''On a side note, it’s equally eye-rolling when you’re chasing a mob or player in open-world and the imp tries to cast firebolt, realises that half-way through the cast, the target is out of range, skips happily a few paces forward, tries to cast again, and gets stuck in this eternal cycle''
https://us.forums.blizzard.com/en/wow/t/my-poor-imp/236628
Blizzlike.
Rev.3472.
Can be closed.
