### ISSUE TITLE
[item] Rift stalker Gauntlets

### ISSUE THREAD

**Issue by sifiuocz** [Atlantiss/NetherwingBugtracker#3715]
*Description**: 
This item gives wrong stats

**Current behaviour**:
The critical strike chance on the item is melee only.

**Expected behaviour**: 
The critical strike chance on the item should be overall critical chance.
see:
https://web.archive.org/web/20070208103037/http://www.wowhead.com:80/?item=30140

**Server Revision**: 
2526

**Comment by Easyfraggy** [comment]
General critical strike is only physical (gun/bow/xbow/melee) in tbc. Spell Crit is for spells only.

**Comment by Easyfraggy** [comment]
Nvm checked ingame this does seem wierd indeed:

![image](https://user-images.githubusercontent.com/36134067/50552463-1647ad00-0c94-11e9-9073-b5a338c5a50c.png)

**Comment by Manaci** [comment]
This is correct, should be normal critical strike rating as seen in [archives](https://web.archive.org/web/20070225173144/http://wow.allakhazam.com/db/itemset.html?setid=652)

**Comment by Manaci** [comment]
Fixed
