### ISSUE TITLE
[Dungeon] Ethereal Spellbinder their summons (Ethereal Wraith) OP.

### ISSUE THREAD

**Issue by Giantulol** [Atlantiss/NetherwingBugtracker#3717]
**Description**: 
The summoned mob Etereal Wraith goes melee when interrupted/silenced, he then hits way to hard.
https://i.gyazo.com/fd8689a1cc5f2c47990d70c072e7ddd2.png
He also appears to summon while CC (fear in our case). Does not seem blizzlike.
**Current behaviour**:
They hit for 4k.
**Expected behaviour**: 
They should hit much less, no proof.
**Server Revision**: 
2526

**Comment by devo6969** [comment]
Currently hits for 4k each still whether or not if its a bug, probably not. Tried to find info on this add and could not find anything.

**Comment by Wolffenstein** [comment]
Fixed in rev 3460.
