### ISSUE TITLE
[Spell] Holy Shock doing nothing when cast on an enemy player in a sanctuary

### ISSUE THREAD

**Issue by Sayinos** [Atlantiss/NetherwingBugtracker#3718]
[//]: # (Enclose links to things related to the bug using http://wowhead.com or any other TBC database.)
[//]: # (You can use screenshot ingame to visual the issue.)
[//]: # (Write your tickets according to the format:)
[//]: # ([Quest][Azuremyst Isle] Red Snapper - Very Tasty!)
[//]: # ([NPC] Magistrix Erona)
[//]: # ([Spell][Mage] Fireball)
[//]: # ([Npc][Drop] Ghostclaw Lynx)
[//]: # ([Web] Armory doesnt work)
[//]: # (To find server revision type `.server info` command in the game chat.)

**Description**: Holy Shock simply goes on cooldown when "cast" on somebody of the opposite faction in Shatt

**Current behaviour**: Holy Shock goes on cooldown, not damaging the enemy (obviously) OR healing the Paladin

**Expected behaviour**: Holy Shock should heal the Paladin if auto self-cast is enabled, otherwise it should not go on cooldown at all.

**Server Revision**:

**Comment by fazhenghan** [comment]
Confirmed.

**Comment by Wolffenstein** [comment]
Fixed in rev 2533.
