### ISSUE TITLE
[Item] Can't add gems to sockets on certain items

### ISSUE THREAD

**Issue by bioguy741** [Atlantiss/NetherwingBugtracker#3719]
[//]: # (Enclose links to things related to the bug using http://wowhead.com or any other TBC database.)
[//]: # (You can use screenshot ingame to visual the issue.)
[//]: # (Write your tickets according to the format:)
[//]: # ([Quest][Azuremyst Isle] Red Snapper - Very Tasty!)
[//]: # ([NPC] Magistrix Erona)
[//]: # ([Spell][Mage] Fireball)
[//]: # ([Npc][Drop] Ghostclaw Lynx)
[//]: # ([Web] Armory doesnt work)
[//]: # (To find server revision type `.server info` command in the game chat.)

**Description**: 
Specific items won't accept any gems.
**Current behaviour**:
The items Leggings of Tirisfal and Cord of Screaming Terrors will not take any gems in their sockets. When the Socket Gems button is pressed, the prongs do not enclose the gem, and the gem is not consumed from inventory. The sound of the button, however, is played. All gems attempted in these items will not socket, and other items currently worn are able to be socketed. 
http://tbc.cavernoftime.com/item=30207
http://tbc.cavernoftime.com/item=30064

**Expected behaviour**: 

By clicking Socket Gems, the gems should be consumed from inventory and remain in the desired sockets.
**Server Revision**: 
2526

**Comment by Drayo** [comment]
Delete Cache

**Comment by fazhenghan** [comment]
Does that legging have Socket in 2.0? If you have a cache from other server is might show wrong stats in Netherwing cus Netherwing is 2.0 item other servers are 2.4.3.

**Comment by bioguy741** [comment]
Yep, that's the problem. Fixed now.
