### ISSUE TITLE
[Item] Tsunami Talisman

### ISSUE THREAD

**Issue by rychersky** [Atlantiss/NetherwingBugtracker#3720]
[//]: # (Enclose links to things related to the bug using http://wowhead.com or any other TBC database.)
[//]: # (You can use screenshot ingame to visual the issue.)
[//]: # (Write your tickets according to the format:)
[//]: # ([Quest][Azuremyst Isle] Red Snapper - Very Tasty!)
[//]: # ([NPC] Magistrix Erona)
[//]: # ([Spell][Mage] Fireball)
[//]: # ([Npc][Drop] Ghostclaw Lynx)
[//]: # ([Web] Armory doesnt work)
[//]: # (To find server revision type `.server info` command in the game chat.)

**Description**: Tsunami Talisman's 2.0 itemization has a proc that heals for 270-330 health.

I'm having trouble finding any info on Wowhead, Wowpedia/Wiki, or any other source that has the original stats. The best I can do is this spreadsheet from Felmyst (on the Arms/Fury warrior tab, Trinkets listings, additional info column):

https://docs.google.com/spreadsheets/d/1MCHrHkLSsCgF2D5CRitVP7sZA9KNgYbpF05nNn6YTDM/edit#gid=1240053535 

And a comment from user koaschten on the item on Wowhead:

https://www.wowhead.com/item=30627/tsunami-talisman#comments

as of PTR Patch Release of May 8th, this trinket got its stats changed to:
Improves hit rating by 10.
Improves critical strike rating by 38.
Chance on critical hit to increase your attack power by 340 for 10 secs.

kinda hourglass ver. 2.0

**Current behaviour**: On the PTR, it has the 2.1+ itemization of a 10% chance to proc on critical hit for 340 AP for 10 seconds.

**Expected behaviour**: 2.0 itemization should have it have a 10% chance to proc on critical hit for 270-330 health.

**Server Revision**: 2531

**Comment by Saben65** [comment]
The proc should be [Crit Proc Heal](https://www.wowhead.com/spell=38350/crit-proc-heal).

It is using it's post 2.1 spell [Fury of the Crashing Waves](https://www.wowhead.com/spell=42083/fury-of-the-crashing-waves).

[Pre 2.1 stats](https://web.archive.org/web/20070514031843/http://www.thottbot.com:80/i30627)
[Post 2.1 stats](https://web.archive.org/web/20070703052656/http://www.thottbot.com:80/i30627)

**Comment by Brasso** [comment]
![ddfge](https://user-images.githubusercontent.com/44345420/50544045-222a6500-0be9-11e9-9481-6490e246f5a2.png)

I'm seeing the correct version. Did you clear your cache?

**Comment by rychersky** [comment]
Clearing out my cache fixed this. Thanks!
