### ISSUE TITLE
[NPC] Quagmirran H Slave Pens

### ISSUE THREAD

**Issue by activate0** [Atlantiss/NetherwingBugtracker#3721]
**Description**: Quagmirran, last boss in Slave Pens, should patrol but currently does not. 

**Current behaviour**: Quagmirran currently stands idle in front of the pool behind him.

**Expected behaviour**: Quagmirran should patrol in and out of the pool. https://www.youtube.com/watch?v=HstGgpPjmqo first 20 seconds

**Server Revision**: 2531

**Comment by Drayo** [comment]
Might have been a GM that triggered the Event? At least the last few times this issue occurred it was someone going ahead.

**Comment by Wolffenstein** [comment]
He moves there when a certain areatrigger is reached (a GM might have activated it by accident).
