### ISSUE TITLE
[Spell][Warrior] Charge/Intercept fall damage

### ISSUE THREAD

**Issue by rychersky** [Atlantiss/NetherwingBugtracker#3722]
[//]: # (Enclose links to things related to the bug using http://wowhead.com or any other TBC database.)
[//]: # (You can use screenshot ingame to visual the issue.)
[//]: # (Write your tickets according to the format:)
[//]: # ([Quest][Azuremyst Isle] Red Snapper - Very Tasty!)
[//]: # ([NPC] Magistrix Erona)
[//]: # ([Spell][Mage] Fireball)
[//]: # ([Npc][Drop] Ghostclaw Lynx)
[//]: # ([Web] Armory doesnt work)
[//]: # (To find server revision type `.server info` command in the game chat.)

**Description**: Jumping from a height that would cause fall damage and then using Charge/Intercept on an NPC mid-air.

Beginning on the cliff:
![wowscrnshot_122918_203912](https://user-images.githubusercontent.com/45608488/50544173-664a4500-0baa-11e9-97c2-1e199e3b4303.jpg)

Mid-air:
![wowscrnshot_122918_203914](https://user-images.githubusercontent.com/45608488/50544174-664a4500-0baa-11e9-82b8-6c88c1f4cefc.jpg)

Intercepted to target, no fall damage incurred yet (combat log):
![wowscrnshot_122918_203916](https://user-images.githubusercontent.com/45608488/50544175-66e2db80-0baa-11e9-9ea7-705021844a9c.jpg)

Terrezfury falls and loses 3096 health:
![wowscrnshot_122918_203917](https://user-images.githubusercontent.com/45608488/50544176-66e2db80-0baa-11e9-8bf3-f266a5e2777d.jpg)

**Current behaviour**: You still take fall damage.

**Expected behaviour**: You should charge to the target and incur zero fall damage.

**Server Revision**: 2531

**Comment by Wolffenstein** [comment]
Fixed in rev 2536.
