### ISSUE TITLE
Botanica - Missing Buff/Animation - Nethervine Inciter/Reaper

### ISSUE THREAD

**Issue by acedo1234** [Atlantiss/NetherwingBugtracker#3724]
**Description**: The two packs just before Thorngrin the Tender do not gain the visual spell "Sunseeker Blessing" nor do they actually get the buff at all from the Sunseeker Channeler. 

**Current behaviour**: Does not get the very important buff that makes them deadly.

**Expected behaviour**: Every so often the Sunseeker Channeler will do her thing and give the buff to her respective group by stopping her animation, walking to the middle and then casting the buff, these Channelers do not do it at the same time and will rotate their buffs at different times. The video evidence will explain. 

**Server Revision**: 2531

https://youtu.be/iZ2hSgi5K_w?t=78 At 1:18 you can see the demon with the buff, and one side with the visual/buff but the other does not have it.

https://youtu.be/qT-w30Iwl9s?t=219 some more evidence of them getting the visual buff. 

https://youtu.be/U3oNb3mjQ4w?t=333 more footage, this one shows how the packs rotate the buff/visual at different times. One side has it, the other side doesn't, then it flips.

**Comment by Brasso** [comment]
Still broken. Bumping the thread.

**Comment by Evolvee** [comment]
rev 2914
