### ISSUE TITLE
Prairie Stalker Pathing

### ISSUE THREAD

**Issue by WarriorTSW** [Atlantiss/NetherwingBugtracker#3725]
[//]: # (Enclose links to things related to the bug using http://wowhead.com or any other TBC database.)
[//]: # (You can use screenshot ingame to visual the issue.)
[//]: # (Write your tickets according to the format:)
[//]: # ([Quest][Azuremyst Isle] Red Snapper - Very Tasty!)
[//]: # ([NPC] Magistrix Erona)
[//]: # ([Spell][Mage] Fireball)
[//]: # ([Npc][Drop] Ghostclaw Lynx)
[//]: # ([Web] Armory doesnt work)
[//]: # (To find server revision type `.server info` command in the game chat.)

**Description**: 
Mobs not deciding to reset
**Current behaviour**:
Once I ran far away - I had x2 Prairie Stalkers running after me. They didnt know if they should reset to continue chasing. Might be a los issue?
https://www.youtube.com/watch?v=1rsnBlMO0lk
**Expected behaviour**: 
Running back like normal once I run a certain distance away
**Server Revision**: 
Idk sorry. Yesterday 29/12/18 16:39 realm time

**Comment by Dollywog** [comment]
I 100% expected that YouTube to link to a Morogrim video

**Comment by Fenvarien1** [comment]
https://youtu.be/1rsnBlMO0lk?t=39 same issue

**Comment by aresbrutus** [comment]
It seems to be related to the wolves trying to attack the critter and the person in aggro.

**Comment by maxturtlesc2** [comment]
Same issue as #3376

**Comment by Wolffenstein** [comment]
Can't reproduce. I know it happens sometimes but without a good reproduction rate i wont be able to find the culprit.

**Comment by Wolffenstein** [comment]
Should be fixed in rev 2538.
