### ISSUE TITLE
Tauren Hit Box Potential 

### ISSUE THREAD

**Issue by WarriorTSW** [Atlantiss/NetherwingBugtracker#3726]
[//]: # (Enclose links to things related to the bug using http://wowhead.com or any other TBC database.)
[//]: # (You can use screenshot ingame to visual the issue.)
[//]: # (Write your tickets according to the format:)
[//]: # ([Quest][Azuremyst Isle] Red Snapper - Very Tasty!)
[//]: # ([NPC] Magistrix Erona)
[//]: # ([Spell][Mage] Fireball)
[//]: # ([Npc][Drop] Ghostclaw Lynx)
[//]: # ([Web] Armory doesnt work)
[//]: # (To find server revision type `.server info` command in the game chat.)

**Description**: 
Mobs being able to melee while Tauren cant
**Current behaviour**:
After kiting a mob, I noticed I was out of range to melee. However the mob I was trying to melee was able to melee me. Also while kiting mobs I often noticed the enemy npcs are easily connecting their melee hits and it was harder for me to land me melee hits (as in for me to get close enough for my swing to trigger)
https://www.youtube.com/watch?v=8psVvqmvYXw
**Expected behaviour**: 
If they can melee me, I can melee them. And vice versa. 
**Server Revision**: 
idk sorry. 29/12/18 14:19 Realm Time

**Comment by Jacksn5** [comment]
I'm pretty sure that's blizzlike and not related to Tauren hit box, while kiting you can't reliably melee NPCs like you would if you were standing.

**Comment by Easyfraggy** [comment]
This actually seems like https://github.com/Atlantiss/NetherwingBugtracker/issues/2795 to me and not the issue you describe.

**Comment by torrenzGH** [comment]
nice fov fix

**Comment by The14me** [comment]
Since the other issue was resolved, that must be closed too. There is no problem with male range attacks anymore.
Rev 3472.
