### ISSUE TITLE
Phantom Auto Attacks

### ISSUE THREAD

**Issue by PolarCookie** [Atlantiss/NetherwingBugtracker#3728]
**Description**: 
I won a duel against a guy, then this happened to me.
He was standing about 10-20 yards away when it happened.
![wowscrnshot_123018_190426](https://user-images.githubusercontent.com/1158801/50549951-d9b18c80-0c66-11e9-8f79-748965f946d7.jpg)

**Server Revision**: 
2538

**Comment by The14me** [comment]
2k rev's after that issue and none report anything like that. Its supposed to be fixed.
Can be closed.Rev 3472.
