### ISSUE TITLE
Northshire Defias Pathfinding 

### ISSUE THREAD

**Issue by lomsac** [Atlantiss/NetherwingBugtracker#3729]
[//]: # (Enclose links to things related to the bug using http://wowhead.com or any other TBC database.)
[//]: # (You can use screenshot ingame to visual the issue.)
[//]: # (Write your tickets according to the format:)
[//]: # ([Quest][Azuremyst Isle] Red Snapper - Very Tasty!)
[//]: # ([NPC] Magistrix Erona)
[//]: # ([Spell][Mage] Fireball)
[//]: # ([Npc][Drop] Ghostclaw Lynx)
[//]: # ([Web] Armory doesnt work)
[//]: # (To find server revision type `.server info` command in the game chat.)

**Description**: 
The Defias Thugs are running over the fences
**Current behaviour**:
-//-
**Expected behaviour**: 
They should be running around them

**Comment by Evolvee** [comment]
no
