### ISSUE TITLE
Undercity Chat Swapping

### ISSUE THREAD

**Issue by nycheia** [Atlantiss/NetherwingBugtracker#373]
http://prntscr.com/ky3ekx

**Description**: 
Standing absolutely in undercity, changes channel constantly. So far has happened 4 times in 10 minutes. I have not tested it in other big cities yet.

**Current behaviour**:
Swaps channels between Tirisfal General+Local Defense chats to Undercity General, Trade and LocalDefense chats.

**Expected behaviour**: 
Shouldnt swap these by not zoning, im standing absolutely still in undercity next to the enchanting trainers
**Server Revision**: 
15:33 CEST 24-09-2018

EDIT: It also seems to change the lightning

**Comment by Evolvee** [comment]
https://github.com/Atlantiss/AtlantissTBCBT/issues/3657

**Comment by nycheia** [comment]
> [Atlantiss/AtlantissTBCBT#3657](https://github.com/Atlantiss/AtlantissTBCBT/issues/3657)

the issue you are referring to is private

**Comment by Easyfraggy** [comment]
> the issue you are referring to is private

We sometimes link to our old internal tracker with same issue as you guys report to give developers some more information about the bug when they try to fix it.

**Comment by Tereneckla** [comment]
Fixed
