### ISSUE TITLE
[NPC] [RP] Stormwind - wrong pronoun in dialogue

### ISSUE THREAD

**Issue by H2714** [Atlantiss/NetherwingBugtracker#3730]
[//]: # (Enclose links to things related to the bug using http://wowhead.com or any other TBC database.)
[//]: # (You can use screenshot ingame to visual the issue.)
[//]: # (Write your tickets according to the format:)
[//]: # ([Quest][Azuremyst Isle] Red Snapper - Very Tasty!)
[//]: # ([NPC] Magistrix Erona)
[//]: # ([Spell][Mage] Fireball)
[//]: # ([Npc][Drop] Ghostclaw Lynx)
[//]: # ([Web] Armory doesnt work)
[//]: # (To find server revision type `.server info` command in the game chat.)

**Description**: 
NPC [Justine Demalier](https://www.wowhead.com/npc=12481/justine-demalier#comments) uses the wrong pronoun for female characters.

**Current behaviour**: 
"That one, Malagan. I know **him**. Dependable, brave and trustworthy. [name] is **his** name.".

**Expected behaviour**: 
"That one, Malagan. I know **her**. Dependable, brave and trustworthy. [name] is **her** name."

**Server Revision**: 
2538

**Comment by Evolvee** [comment]
fixed
