### ISSUE TITLE
[NPC] Outland Armor Quartermaster

### ISSUE THREAD

**Issue by eedijs** [Atlantiss/NetherwingBugtracker#3732]
[NPC] Lieutenant Rachel Vaccar

**Description**: Cannot interact with vendor in Champions' Hall, Stormwind

**Current behaviour**: Cannot interact with vendor to buy items

**Expected behaviour**: Should be a working vendor to buy items

**Server Revision**: 2538

**Comment by aresbrutus** [comment]
She has never been a vendor in TBC.
