### ISSUE TITLE
[Dynamic Respawn] The Ruins of Ordil'Arana - Ashenvale

### ISSUE THREAD

**Issue by killablink** [Atlantiss/NetherwingBugtracker#3735]
**Description**: ![wowscrnshot_123018_171822](https://user-images.githubusercontent.com/43510874/50552390-2c3b7a80-0c60-11e9-8fdf-705020d9b6f7.jpg)

I think some mobs are not on the dynamic respawn here? We cleared everything and nothing but this single mob that I target would respawn faster than the others.

**Expected behaviour**: Should probably respawn quicker to at least have 1 up at all times from what I believe it works? (No other places to find these mobs)

**Server Revision**:

**Comment by Easyfraggy** [comment]
Are these mobs part of a quest?

**Comment by killablink** [comment]
Yes, don't remember the name of the quest though. You have to get a gem from them or something like that.
