### ISSUE TITLE
[Mob][Spell][Mana burn] Felslayer in Ashenvale

### ISSUE THREAD

**Issue by killablink** [Atlantiss/NetherwingBugtracker#3736]
**Description**: The felslayer in Ashenvale spams instant manaburns on low cd (2-3 seconds). Probably 

**Current behaviour**: The felslayer in Ashenvale spams instant manaburns on low cd (2-3 seconds). 

**Expected behaviour**:  Probably shouldn't be instant cast and probably higher CD?.

**Server Revision**: 2538

**Comment by Tenoutoften** [comment]
It's possible that it uses the wrong mana burn spell I encountered a similar issue with a mob in Feralas https://github.com/Atlantiss/NetherwingBugtracker/issues?q=is%3Aissue+mana+burn+is%3Aclosed

On wowhead [[NPC]Felslayer#3774](https://www.wowhead.com/npc=3774/felslayer#abilities) uses
[[Spell]Mana Burn#13321](https://www.wowhead.com/spell=13321/mana-burn) which has a 3 second cast time.

**Comment by Evolvee** [comment]
adjusted
