### ISSUE TITLE
auto shot bug again

### ISSUE THREAD

**Issue by Ahmpy** [Atlantiss/NetherwingBugtracker#3738]
[//]: # (Enclose links to things related to the bug using http://wowhead.com or any other TBC database.)
[//]: # (You can use screenshot ingame to visual the issue.)
[//]: # (Write your tickets according to the format:)
[//]: # ([Quest][Azuremyst Isle] Red Snapper - Very Tasty!)
[//]: # ([NPC] Magistrix Erona)
[//]: # ([Spell][Mage] Fireball)
[//]: # ([Npc][Drop] Ghostclaw Lynx)
[//]: # ([Web] Armory doesnt work)
[//]: # (To find server revision type `.server info` command in the game chat.)

**Current behaviour**: (couldnt find old issue-this was fixed before some recent changes broke it again)
 https://youtu.be/Hl5wu8B8RPY 
instant casts are queued to fire while hunter starts .5s wind up for auto shot. If hunter interrupts said wind up before it fires the shot will also not fire, but the gcd will end up still being consumed. 
**Expected behaviour**: 
Instant cast hunter shots should not delay or be delayed by auto shot.
**Server Revision**: 
2546

**Comment by Frankenberryberry** [comment]
I can confirm this. Also I would like to add that if this can not be fixed before release I would suggest reversing the changes made since they overall made things worse =(

**Comment by Styggex** [comment]
I can confirm this as well.

**Comment by Zarant** [comment]
Tested this at revision 3430. This bug still persists.

As of patch 2.4, only steady shot and multi-shot should be queued after an auto shot.

Research provided has been listed on issue #2339

**Comment by Wolffenstein** [comment]
Can you provide a video?

**Comment by Zarant** [comment]
https://youtu.be/5e7P2Aq_hEo

It's not very clear but if you pay close attention, arcane shot and multi-shot are getting queued and only casting after auto shot goes out.

The same happens with serpent sting, viper sting and scorpid sting as well, basically all hunter shots except aimed shot are getting queued and are only firing after your auto shot goes out.
As of patch 2.4, steady shot should be the only spell queued after an auto shot.

**Comment by raethkcj** [comment]
Here (https://streamable.com/ak1d4y) is a short clip from https://youtu.be/4jbSgaPROH0?t=178

The hunter shoots an auto, then waits and presses Arcane Shot with almost exactly 0.5s left on his Auto Shot timer. However, the Arcane Shot doesn't hit the target until *after* the next Auto Shot.

This suggests that instant shots *should* fire a GCD instantly, but be queued until Auto Shot goes off.

**Comment by Godmatik** [comment]
Was fixed last year
