### ISSUE TITLE
[Shattrath City] Horde Portals dont work

### ISSUE THREAD

**Issue by quapuzi** [Atlantiss/NetherwingBugtracker#3739]
**Description**:  Shattrath City Horde Portals dont work (as Warrior)

**Current behaviour**:
If you click on any of the portals, you get the error message: Not enough Mana
**Expected behaviour**: 
You get portet to the chosen City
**Server Revision**: 
2546

**Comment by RandomGuyFromDiscordServer** [comment]
Works fine for me too (Orc warrior).

**Comment by Wolffenstein** [comment]
Fixed in rev 2547.
