### ISSUE TITLE
[UI] Combatlog / damage meters not working

### ISSUE THREAD

**Issue by towneh** [Atlantiss/NetherwingBugtracker#374]
**Current behaviour**:
Nothing appears in the combat log window by default. This was also a problem on other TBC server projects.

**Expected behaviour**: 
You need to run the following macro in order to fix the issue:
/run local f = CreateFrame("frame",nil, UIParent); f:SetScript("OnUpdate", CombatLogClearEntries);
Combat log entries then appear in the combatlog frames

**Server Revision**: 
2040

**Comment by Evolvee** [comment]
yep its a scuffed client

happened on retail too
