### ISSUE TITLE
Campfires do not do ticking fire damage when standing too close.

### ISSUE THREAD

**Issue by Medry** [Atlantiss/NetherwingBugtracker#3740]
[//]: # (Enclose links to things related to the bug using http://wowhead.com or any other TBC database.)
[//]: # (You can use screenshot ingame to visual the issue.)
[//]: # (Write your tickets according to the format:)
[//]: # ([Quest][Azuremyst Isle] Red Snapper - Very Tasty!)
[//]: # ([NPC] Magistrix Erona)
[//]: # ([Spell][Mage] Fireball)
[//]: # ([Npc][Drop] Ghostclaw Lynx)
[//]: # ([Web] Armory doesnt work)
[//]: # (To find server revision type `.server info` command in the game chat.)

**Description**: 
No Fire damage from campfires and some other fires when standing too close

Nice little feature to have working, i remember getting broken out of stealth by campfires at the most inconvenient times.

**Current behaviour**:
Campfires in-game and the Basic Campfire summoned by the player with the cooking skill do not deal any ticking fire damage when players walk too close to them
Have also noticed inconsistent behavior with Bonfires in lower city. The larges ones do no ticking damage, but the smaller ones do. Other fires around the world could have the same issue.

**Expected behaviour**: 
Campfires should deal a tiny fire tick to the player when they stand too close. 
As noted on https://wow.gamepedia.com/Cooking_Fire_(ability)
"Patch 3.0.8 (2009-01-20): No longer requires  [Simple Wood]. Also, no longer causes fire damage when players stand too close. "

**Server Revision**: 
2546

**Comment by Tenoutoften** [comment]
You have to write which one specifically because it looks like a lot of them are fixed already: https://github.com/Atlantiss/NetherwingBugtracker/issues/25

**Comment by The14me** [comment]
.gps at the place with that campfire.They work fine to me.

**Comment by devo6969** [comment]
Only one in shattrath I couldn't get triggered was at 73.88, 51.29
