### ISSUE TITLE
Priest T5 - Avatar Raiment 2p set bonus not working

### ISSUE THREAD

**Issue by Iskra12** [Atlantiss/NetherwingBugtracker#3741]
**Description**: 2p set bonus description: "If your Greater Heal brings the target to full health, you gain 100 mana".
**Current behaviour**: Using Greater Heal don't give any mana. 
**Expected behaviour**: Should give 100 mana if Greter Heal bring target to full health.

**Server Revision**: 2546

**Comment by Wolffenstein** [comment]
Works now.
