### ISSUE TITLE
[Zangarmarsh] Twinspire Graveyard cannot be captured

### ISSUE THREAD

**Issue by weirdbiz** [Atlantiss/NetherwingBugtracker#3742]
[//]: # (Enclose links to things related to the bug using http://wowhead.com or any other TBC database.)
[//]: # (You can use screenshot ingame to visual the issue.)
[//]: # (Write your tickets according to the format:)
[//]: # ([Quest][Azuremyst Isle] Red Snapper - Very Tasty!)
[//]: # ([NPC] Magistrix Erona)
[//]: # ([Spell][Mage] Fireball)
[//]: # ([Npc][Drop] Ghostclaw Lynx)
[//]: # ([Web] Armory doesnt work)
[//]: # (To find server revision type `.server info` command in the game chat.)

**Description**: 
Twinspire Graveyard capturing does not work properly.
**Current behaviour**:
After capturing both beacons, Zangarmarsh banner at Twinspire Graveyard is usable, but says 'not enough mana'. Also Alliance Field Scout does not pass the flag to player and not marked on the map.
**Expected behaviour**: 
From https://www.wowhead.com/spell=33779/twin-spire-blessing#comments:
"You capture both towers, and then your Field Scout (shown on the map as a flag) can be spoken to. You go up to the Field Scout and ask for a battle standard (you must be unmounted)
Then you run to the Graveyard and place the banner. You only have 5 minutes to get to standard to the graveyard, so be quick. Once you do that, you control the graveyard and get the Twin Spire Blessing."

After that graveyard is captured, it should become owned by faction and appropriate buff should appear on faction characters in this zone.

NB: "must be unmounted requirement" seems to be removed, according to the comment from the link above:
"well if it works for something... since the patch 2.4.2 iu can use any mount havin' the flag"

**Server Revision**: 
2546

**Comment by Wolffenstein** [comment]
Fixed in rev 2547.

**Comment by Wolffenstein** [comment]
Fixed in rev 3328.
