### ISSUE TITLE
# [Escort Quest] [Netherstorm] [When the Cows Come Home] +[Mark V is Alive!]

### ISSUE THREAD

**Issue by Mev2020** [Atlantiss/NetherwingBugtracker#3744]
**Description**: 
Escort quest in Netherstorm "Mark V is Alive!" not working properly ( the npc does not attack any mobs on his way) same problem with escort quest "When the Cows Come Home". Plz fix it.

**Current behaviour**:

-When the Cows Come Home:
https://youtu.be/d1BlKj9BoOc

-Mark V is Alive:
https://youtu.be/cdxyoWDnfAY

---------------------------

**Expected behaviour**: 
-Mark V is Alive!:
https://youtu.be/psENspXb58w?t=41

-When the Cows Come Home:
https://youtu.be/IRvjFHWOlZ4?t=48

This is my 2 report, sorry if I did not follow the rules of publication.

**Comment by Drayo** [comment]
https://github.com/Atlantiss/NetherwingBugtracker/issues/3678

**Comment by Tenoutoften** [comment]
Merged into https://github.com/Atlantiss/NetherwingBugtracker/issues/3678
