### ISSUE TITLE
[Quest][Quest Item] Dartol's Rod of Transformation

### ISSUE THREAD

**Issue by Anonyxx** [Atlantiss/NetherwingBugtracker#3745]
**Description**: 
This is a critical bug as it permanently affects your character and will require intervention from a GM to fix. This relates to a level 25-30 quest (Raene's Cleansing) and so is very important to fix before launch as this is a common quest that a lot of players complete.

**Current behaviour**:

Currently, using Dartol's Rod of Transformation locks your character out of casting any spells. Even out of furbolg form, the error persists.. The error message shown is "Not enough mana" when I have more than enough. Even spells that don't cost any mana i.e. Gift of the Naaru cannot be cast and the error message persists.

Even upon Alt-F4, logout, reloadui the error persists. My character can no longer cast any spells at all after using this item.

**Expected behaviour**: 

After leaving furbolg form, the player should be able to cast any and all spells on the normal basis of gameplay.

**Server Revision**: 
2546

**Comment by Wolffenstein** [comment]
Fixed in rev 2547.
