### ISSUE TITLE
 ([Quest][Netherstorm] -  Ar'kelos the Guardian

### ISSUE THREAD

**Issue by Mev2020** [Atlantiss/NetherwingBugtracker#3746]
**Expected behaviour**: 
 https://www.wowhead.com/quest=10176/arkelos-the-guardian
**Description**: 
 Quest "Ar'kelos the guardian" does not work, after killing Ar'kelos. quest not complete.

 **Current behaviour**:
![1](https://user-images.githubusercontent.com/46243754/50560588-146d0080-0d0b-11e9-99ff-be95e0f95b79.jpg)
![2](https://user-images.githubusercontent.com/46243754/50560590-1636c400-0d0b-11e9-85f5-8a4db91f0a30.jpg)

**Comment by Drayo** [comment]
Just to make sure, you were not in a Raid, right? You UI shows "Group 1" at your player frame but I'm not sure if that's always the case.

**Comment by The14me** [comment]
Need retest

**Comment by The14me** [comment]
Rev.3472. Work just fine.
Can be closed.Maybe was a Raid/UI issue.
