### ISSUE TITLE
Battle Rez in Kara

### ISSUE THREAD

**Issue by Neccos** [Atlantiss/NetherwingBugtracker#3747]
[//]: # ([Spell][Druid] Battle Rez)

**Description**: Battle rez in kara was sometimes causing players to rez outside the instance rather inside during the encounter. This happened once at maiden in kara. 

**Current behaviour**: Sometimes rezzing players outside the instance.

**Expected behaviour**: Always rez inside the instance.

**Server Revision**:

**Comment by Drayo** [comment]
Did they already release or were they still in the Instance when they were resurrected? Knowing this might help them find the cause.

**Comment by Neccos** [comment]
they had already released, thanks for your question

**Comment by Tholinx** [comment]
Well if they released and raid was in combat its normal that they ress outside, atleast I remember it like that.

**Comment by Firroth** [comment]
During boss encounter:
If he released spirit, then got combat ress -> it should ress him outside.
If he was in body, then got combat ress -> it should revive him inside.

Never saw it act as both "inside", except on some private servers.

**Comment by devo6969** [comment]
On retail you arnt allowed to release yourself during the encounter probably because people would release, brez wouldn't work and/or you wouldn't get loot because you are not there.

Retail BFA - https://www.youtube.com/watch?v=VQiqVAJ9dEQ
