### ISSUE TITLE
Raveners in ramparts

### ISSUE THREAD

**Issue by Neccos** [Atlantiss/NetherwingBugtracker#3748]
**Description**: If you wouldn't mind taking a loot at the damage values or attack speed on raveners in ramparts. They seem to be doing much more damage that I recall. I know that they always did a lot of damage but this seems to be more than expected. Would consistently kill a pre raid prot paladin tank in 4-5 simultaneous hits in less than a second. Was healing tank in t5 and tank would sometimes die before a 1.5 second heal could be cast, often times pre casting it. 

**Current behaviour**: A lot of damage.

**Expected behaviour**: A lot of damage, but not current amounts of damage. 

**Server Revision**:

**Comment by The14me** [comment]
Need retail proof.
