### ISSUE TITLE
Kara hallway to maiden dropping combat during fights.

### ISSUE THREAD

**Issue by Neccos** [Atlantiss/NetherwingBugtracker#3749]
**Description**: Combat would occasionally be dropped when the only mobs left were being CC'd with shackle. This allowed one of our priests to rez people when they died on the pulls.

**Current behaviour**: Dropping combat when combat should not be dropped.

**Expected behaviour**: Staying in combat while mobs are cc'd.

**Server Revision**:

**Comment by Godmatik** [comment]
Duplicate
