### ISSUE TITLE
Totem of Wrath

### ISSUE THREAD

**Issue by Neccos** [Atlantiss/NetherwingBugtracker#3750]
[//]: # ([Spell][Shaman] Totem of Wrath)

**Description**: Currently totem of wrath is stacking. I have seen other posts that say they should not stack. However there is evidence of totem of wrath stacking from this post from 2008. https://www.dual-boxing.com/threads/11259-Totem-of-Wrath-stacking
I honestly dont remember totem of wrath ever stacking in tbc sorry if this has been addressed before but it could be something to look into whether or not this totem really should stack or not. 

**Current behaviour**: Stacks.

**Expected behaviour**: Don't specifically know, needs to be researched I think whether or not this totem should really stack. 

**Server Revision**:

**Comment by Brasso** [comment]
Totem of wrath stacking is correct for tbc.
