### ISSUE TITLE
Netherblade set pieces.

### ISSUE THREAD

**Issue by Neophrone** [Atlantiss/NetherwingBugtracker#3751]
[//]: # (Enclose links to things related to the bug using http://wowhead.com or any other TBC database.)
[//]: # (You can use screenshot ingame to visual the issue.)
[//]: # (Write your tickets according to the format:)
[//]: # ([Quest][Azuremyst Isle] Red Snapper - Very Tasty!)
[//]: # ([NPC] Magistrix Erona)
[//]: # ([Spell][Mage] Fireball)
[//]: # ([Npc][Drop] Ghostclaw Lynx)
[//]: # ([Web] Armory doesnt work)
[//]: # (To find server revision type `.server info` command in the game chat.)

**Description**: 
I saw that Wolfy made corection for Netherblade Chestpiece, and I found that helm and gloves have wrong stats too.
**Current behaviour**:
Current Netherblade Facemask and Netherblade Shoulders stats:
![1](https://user-images.githubusercontent.com/43533040/50562129-1db19980-0d1a-11e9-80bb-613fa19ed5c5.jpg)
![2](https://user-images.githubusercontent.com/43533040/50562130-1db19980-0d1a-11e9-8028-7b2082549286.jpg)

**Expected behaviour**: 
Netherblade Facemask and Netherblade Shoulders stats according to 4th of March 2007 wowhead data (pre-2.1):
![3](https://user-images.githubusercontent.com/43533040/50562186-8e58b600-0d1a-11e9-9a8a-19b07f4ba4da.jpg)
![4](https://user-images.githubusercontent.com/43533040/50562187-8e58b600-0d1a-11e9-8807-b1ba83c697a7.jpg)

Source:
https://web.archive.org/web/20070304132353/http://www.wowhead.com:80/?item=29044
https://web.archive.org/web/20070304132649/http://www.wowhead.com:80/?item=29047
**Server Revision**: 2547.

**Comment by Ensipidx** [comment]
Netherblade Shoulders are probably correct (https://web.archive.org/web/20070410111401/http://www.thottbot.com:80/i29047). Top comment refers to it having 10 dodge rating in its comparison (https://www.wowhead.com/item=29047/netherblade-shoulderpads#comments:id=55038).

Netherblade Mask probably needs to be changed. https://www.wowhead.com/item=29044/netherblade-facemask#comments:id=46336:reply=290289 References a loss of 3 stam, 4 ap, gain 23 agi, and losing crit/hit rating.

**Comment by Godmatik** [comment]
2.0 item stats no longer used - closing
