### ISSUE TITLE
Rested XP in enemy main city

### ISSUE THREAD

**Issue by 161134050** [Atlantiss/NetherwingBugtracker#3752]
[//]: # (Enclose links to things related to the bug using http://wowhead.com or any other TBC database.)
[//]: # (You can use screenshot ingame to visual the issue.)
[//]: # (Write your tickets according to the format:)
[//]: # ([Quest][Azuremyst Isle] Red Snapper - Very Tasty!)
[//]: # ([NPC] Magistrix Erona)
[//]: # ([Spell][Mage] Fireball)
[//]: # ([Npc][Drop] Ghostclaw Lynx)
[//]: # ([Web] Armory doesnt work)
[//]: # (To find server revision type `.server info` command in the game chat.)

**Description**: 
Currently, you are considered at rest when within an enemy main city (and generate xp and can log off instnatly)

**Current behaviour**:
Currently, you are considered at rest when within an enemy main city (and generate xp and can log off instnatly)

**Expected behaviour**: 
You do not get rested xp within an enemy city

**Server Revision**: 
Server Revision: 2547

**Comment by 161134050** [comment]
Thanks

**Comment by xmesaj2** [comment]
rev 2562
