### ISSUE TITLE
[Dungeon][NPC][Botanica] Warp splinter

### ISSUE THREAD

**Issue by Zarant** [Atlantiss/NetherwingBugtracker#3753]
Arcane volley is not supposed to hit pets,

Source:
https://www.youtube.com/watch?v=UHpc21RZURE at the 27 second mark, normal mode
https://www.youtube.com/watch?v=L7pWoLhj3DE at the 43 second mark, heroic mode

Pay extra attention on the pet frames, pets take damage from stomp but not arcane volley

Server revision: 2547

**Comment by Tenoutoften** [comment]
This boss is known to change through the patches and both your videos are from very late into the expansion 2.3/2.4... Not saying it should hit pets

**Comment by Tereneckla** [comment]
There have been no changes to Warp Splinter mechanically in the patch notes.

**Comment by Wolffenstein** [comment]
Fixed in rev 3388.
