### ISSUE TITLE
Hunter's Mark on Voodoo Trolls on Echo Isles

### ISSUE THREAD

**Issue by Styggex** [Atlantiss/NetherwingBugtracker#3754]
[//]: # (https://www.wowhead.com/quest=826/zalazane.)
[//]: # (You can use screenshot ingame to visual the issue.)
[//]: # (Write your tickets according to the format:)
[//]: # ([Quest][Zalazane])
[//]: # ([NPC] Voodoo Troll)
[//]: # ([Spell][Mage] Fireball)
[//]: # ([Npc][Drop] Ghostclaw Lynx)
[//]: # ([Web] Armory doesnt work)
[//]: # (To find server revision type `.server info` command in the game chat.)

**Description**: Hunter's Mark puts you in combat when you use it on a Voodoo Troll and their AI simply stop, they dont do anything

**Current behaviour**: You put up Hunter's Mark on a Voodoo Troll and they target you and puts you in combat, their AI also simply gets canceled.

**Expected behaviour**: You're supposed to not end up in combat when you use Hunter's Mark on a Voodoo Troll

**Server Revision**: 2547

**Comment by Zarant** [comment]
It has something to do with lightning shield and similar effects, please notice that Hunter's mark is not supposed to get enemies in combat but is supposed to stop other players from drinking

> So a while back they implemented a change that made any DoT that lands on you make you stand up and stop drinking when you are OOC and Drinking (or sitting in general). I was very anti this buff because it benefits warlocks the most who don't need anymore buffs in 2s and 3s.
> 
> Anyways I was messing around and Hunter's Mark (Rank 1-4) also does this effect, from 100yd range. Has situational uses seeing as it doesn't work through LoS, but it has 0 travel time and most players will assume combat if you're coming at them and they auto-stand up.

http://www.arenajunkies.com/topic/10029-tip-for-hunters/

**Comment by Tokretsim** [comment]
Same happens in duel with player shaman.
![wowscrnshot_011619_103413](https://user-images.githubusercontent.com/38424067/51233582-40c78480-197b-11e9-89ca-a96942832530.jpg)

**Comment by Zarant** [comment]
Issue seems fixed, cannot reproduce it.
