### ISSUE TITLE
No fish caught in Terokar

### ISSUE THREAD

**Issue by artemicon** [Atlantiss/NetherwingBugtracker#3755]
[//]: # (Enclose links to things related to the bug using http://wowhead.com or any other TBC database.)
[//]: # (You can use screenshot ingame to visual the issue.)
[//]: # (Write your tickets according to the format:)
[//]: # ([Quest][Azuremyst Isle] Red Snapper - Very Tasty!)
[//]: # ([NPC] Magistrix Erona)
[//]: # ([Spell][Mage] Fireball)
[//]: # ([Npc][Drop] Ghostclaw Lynx)
[//]: # ([Web] Armory doesnt work)
[//]: # (To find server revision type `.server info` command in the game chat.)

**Description**: 
No fish caught in Terokar.

**Current behaviour**:
When casting in Terokar with 480 skill I am unable to catch any fish.  Please note I am only counting fishing attempts that would otherwise actually land a fish.  I am not counting "Fish got away messages", although sometimes I do get that message.  This implies that I am actually landing a fish due to not getting the Fish got away message but when I click no fish is looted.

Tested at Lake Silmyr, and Lake Jorune.

I also tested fishing in a few areas of Nagrand and Zangarmarsh and those areas appear to be functioning correctly.  Did not extensively test fish tables.

**Expected behaviour**: 
Should be catching fish in those locations.

**Server Revision**: 
Atlantiss.eu 
AtlantissCoreTBC - Server Revision: 2548 [Branch: master, Hash: cf1ec2720327] 
Online players: 37 (max: 37) 
Active connections: 44 (max: 45) Queued connections: 0 (max: 0) 
Server uptime: 1 Minute(s) 50 Second(s). 
Current time: 2018-12-31_18-46-19 
Content Patch: 203

**Comment by wtRCH** [comment]
@Shanghi

**Comment by Tereneckla** [comment]
fixed
