### ISSUE TITLE
[Misc] The two left-most Practice Lockboxes at Alther's Mill in Redridge Mountains do not respawn after being opened.

### ISSUE THREAD

**Issue by Novendar** [Atlantiss/NetherwingBugtracker#3756]
**Description**: 
The two left-most Practice Lockboxes in Alter's Mill, Redridge Mountains, either do not respawn or take much longer than they should to respawn after opening with "Pick Lock"

*Steps to Reproduce*
1- Enter the Server after a fresh reboot with a Rogue that has the Lock Pick skill.
2- Travel to Redridge Mountains.
3- Travel to Alther's Mill.
4- Lock Pick the left-most Practice Lockbox.
5- Lock Pick the second left-most Practice Lockbox.
6- Observe the result.

**Current behaviour**:
The Practice Lockboxes do not respawn.

**Expected behaviour**: 
The Practice Lockboxes respawn after 10 seconds.

**Server Revision**: 
2548 Branch: master, Hash: cf1ec2720327

![lockboxes_no_respawn_althers_mill](https://user-images.githubusercontent.com/45017294/50565482-4bd4b080-0cfd-11e9-8286-56275e5eab9e.png)

**Comment by Shanghi** [comment]
This should be fixed in revision 2554.

**Comment by Novendar** [comment]
Fix confirmed in Revision 2555.
