### ISSUE TITLE
Random High amounts of exp

### ISSUE THREAD

**Issue by Hardfelt** [Atlantiss/NetherwingBugtracker#3757]
[//]: # (Enclose links to things related to the bug using http://wowhead.com or any other TBC database.)
[//]: # (You can use screenshot ingame to visual the issue.)
[//]: # (Write your tickets according to the format:)
[//]: # ([Quest][Azuremyst Isle] Red Snapper - Very Tasty!)
[//]: # ([NPC] Magistrix Erona)
[//]: # ([Spell][Mage] Fireball)
[//]: # ([Npc][Drop] Ghostclaw Lynx)
[//]: # ([Web] Armory doesnt work)
[//]: # (To find server revision type `.server info` command in the game chat.)

**Description**: 
Exp values off for mobs while leveling. Noticed it after recent restart. Mobs should be giving 70-80 exp at lvl 7, but some give upwards to 260 exp. https://clips.twitch.tv/CrispyPrettiestBananaDancingBanana A clip of one example
**Current behaviour**:
Random influx of exp
**Expected behaviour**: 
set rate of exp based on your lvl and lvl of mob
**Server Revision**:

**Comment by SwiftieTBC** [comment]
This is fixed and can be closed
