### ISSUE TITLE
[Core][Polymorph] Combat bug

### ISSUE THREAD

**Issue by killablink** [Atlantiss/NetherwingBugtracker#3759]
**Description**: If you pull a pack of 2 mobs, sheep one of the 2 targets, kill the other, you will leave combat even though the other mob is still sheeped.

**Current behaviour**: If you pull a pack of 2 mobs, sheep one of the 2 targets, kill the other, you will leave combat even though the other mob is still sheeped.

**Expected behaviour**: Should stay in combat.

**Server Revision**: 2550

**Comment by wtRCH** [comment]
This might also happen to Hunters probably.

**Comment by Wolffenstein** [comment]
Can't reproduce on local. If it still happens, please make a video.
