### ISSUE TITLE
[Misc] The lockbox atop Kraven's Tower does not grant more than 1 Lockpicking skill up.

### ISSUE THREAD

**Issue by Novendar** [Atlantiss/NetherwingBugtracker#3761]
**Description**: 
Lockpicking the lockbox for the Rogue's Poison quest atop Kraven's Tower only grants 1 Lockpicking skill up. The Character's Lockpicking skill was at 73 and the lockbox was orange. Several attempts were made after gaining the initial skill up to no avail.

*Steps to Reproduce*
1- Create a Rogue.
2- Obtain and increase the Lockpicking skill to between 70 and 75.
3- Begin the quest 'Klaven's Tower' (QuestID: 2359).
4- Travel to Kraven's Tower in Westfall.
5- Ascend the Tower to the to floor.
6- Lockpick the lockbox/chest but DO NOT loot it.
7- Observe how a skill up is obtained.
8- Keep lockpicking and opening the lockbox but DO NOT loot it.
9- Observe the results.

**Current behaviour**:
No Lockpicking points are gained beyond the first, even when the lockbox is "orange".

**Expected behaviour**: 
The lockbox gives Lockpicking skill ups up to ~175 skill.

**Additional Note**
The lockbox is no longer interact-able after being looted, but I can't remember if it was like that in Retail.

**Server Revision**: 
Revision: 2550 Branch: master, Hash: f78ec14f864c

![kravens_tower_lockbox](https://user-images.githubusercontent.com/45017294/50570057-cecf2880-0d48-11e9-94cb-71cc128838a4.png)

**Comment by Drayo** [comment]
Oh I was just adding some proof. I'm not doubting your report.

You could of course test if it works like it should (even after looting it) aside from the missing skill points.

**Comment by Novendar** [comment]
Alright, thanks for the assist! :)

**Comment by Novendar** [comment]
Tested the lockbox (Duskwood Chest as it's actually named) like Drayo suggested in his quotes and it seems to be working as intended. 

Closing the issue.
