### ISSUE TITLE
[NPC]Moonstalker Runt#2070 incorrectly shares level with [NPC]Moonstalker Matriarch#2071

### ISSUE THREAD

**Issue by Tenoutoften** [Atlantiss/NetherwingBugtracker#3762]
**Description**: 
This issue is identical to one that I reported in Ghostland which has been solved.
https://github.com/Atlantiss/NetherwingBugtracker/issues/737

[[NPC]Moonstalker Matriarch#2071](https://www.wowhead.com/npc=2071/moonstalker-matriarch) has [[NPC]Moonstalker Runt#2070](https://www.wowhead.com/npc=2070/moonstalker-runt) as pet, summoned by [[Spell]Summon Moonstalker Runt#8594](https://www.wowhead.com/spell=8594/summon-moonstalker-runt). The summoned pet should be 3 levels below his master, but currently has the same level.

Indicated by wowhead comment from [[Quest]A lost master#986](https://www.wowhead.com/quest=986/a-lost-master)
![](https://i.gyazo.com/9d327292ccd33ca442e8cb64e90a7049.png)

**Expected behaviour**: 
[[NPC]Moonstalker Runt#2070](https://www.wowhead.com/npc=2070/moonstalker-runt) owned by [[NPC]Moonstalker Matriarch#2071](https://www.wowhead.com/npc=2071/moonstalker-matriarch) should be 3 levels below it's master.

**Server Revision**: 
2550

**Comment by wtRCH** [comment]
@aresbrutus

**Comment by Wolffenstein** [comment]
Fixed in rev 3386.
