### ISSUE TITLE
[Hunter][Pets] Pet AI behaviour

### ISSUE THREAD

**Issue by networm555** [Atlantiss/NetherwingBugtracker#3763]
Pet trying to hit target in the face. If pet  doesent have aggro he should always hit target from the back. 
Tested on dummy humanoid and random wolves in terrokkar. If you played tank did you ever saw pet standing near you when you tank ? Ofc not. They always positioning themselves with melees somewhere.

**Comment by networm555** [comment]
Found this on a bugtracker  https://github.com/Atlantiss/NetherwingBugtracker/issues/3123. Can confirm.

**Comment by tjukoela** [comment]
bump

**Comment by The14me** [comment]
Rev.3472 Not an issue anymore.
Can be closed.
