### ISSUE TITLE
Spell power not being applied from healing gear

### ISSUE THREAD

**Issue by Neccos** [Atlantiss/NetherwingBugtracker#3765]
**Description**: Spell damage not being calculated from healing gear. Some pieces of gear are giving spell damagebut not the full amount while others are giving no spell damage

**Current behaviour**: Not correctly giving spell damage from healing gear. 
https://imgur.com/a/f3ecoMA

![wowscrnshot_010119_072948](https://user-images.githubusercontent.com/46281980/50573372-38c2ee80-0d98-11e9-8ff4-e9630f111fde.jpg)
![wowscrnshot_010119_073325](https://user-images.githubusercontent.com/46281980/50573373-3a8cb200-0d98-11e9-9291-7c8c26fe4e61.jpg)

here are two screenshots of my gear and my bonus spell damage. The SSC mace alone has +148 spell damage on it and 443 healing while in my character screen i only have 81 spell damage. Second screenshot included to show that this is not just a visual bug as my moonfire is hitting for 370-400 with a base damage of the spell being 335-393. 

**Expected behaviour**: Should have spell damage equal to the amount of spell damage listed on gear.

**Server Revision**:

**Comment by Brasso** [comment]
Healing gear does not have spell damage on it before patch 2.3.

**Comment by Neccos** [comment]
@Brasso can i get a link please

**Comment by Brasso** [comment]
https://github.com/nullfoxh/NWTooltipFix
