### ISSUE TITLE
[NPC] [Boss] [Karazhan] Shade of Aran - reset HP after raid member died

### ISSUE THREAD

**Issue by AWIDIUS** [Atlantiss/NetherwingBugtracker#3767]
https://clips.twitch.tv/ConfidentAdorableWhaleKappaPride 
Dont know if this boss behaviour is blizzlike, but after raid member died, Aran reseted his HP.

**Comment by networm555** [comment]
thats fun 🥇  leave it like this. 
ps: ye thats a bug.

**Comment by wtRCH** [comment]
@Wolffenstein

**Comment by Tenoutoften** [comment]
Have to figure out what caused it specifically... it certainly doesn't happen every time anyone dies?

**Comment by AWIDIUS** [comment]
Well ... To be honest I was just looking on someone's stream. So I dont know

**Comment by Wolffenstein** [comment]
It should be fixed in rev 2555.
