### ISSUE TITLE
[World objects] [Stormwind] Meat in the Moonwell

### ISSUE THREAD

**Issue by H2714** [Atlantiss/NetherwingBugtracker#3768]
[//]: # (Enclose links to things related to the bug using http://wowhead.com or any other TBC database.)
[//]: # (You can use screenshot ingame to visual the issue.)
[//]: # (Write your tickets according to the format:)
[//]: # ([Quest][Azuremyst Isle] Red Snapper - Very Tasty!)
[//]: # ([NPC] Magistrix Erona)
[//]: # ([Spell][Mage] Fireball)
[//]: # ([Npc][Drop] Ghostclaw Lynx)
[//]: # ([Web] Armory doesnt work)
[//]: # (To find server revision type `.server info` command in the game chat.)

**Description**: 
There is meat in and around the Moonwell in Stormwind. When hovering with the mouse on the offending objects it says "Moonwell".

**Current behaviour**:
![image](https://user-images.githubusercontent.com/46264740/50574558-f4ad0980-0dea-11e9-8b1e-77500a82678e.png)
![image](https://user-images.githubusercontent.com/46264740/50574584-62f1cc00-0deb-11e9-9aa1-d982c0c1c674.png)

**Expected behaviour**: 
No meat in the druid sanctuary.

**Server Revision**: 
2550

**Comment by Shanghi** [comment]
Typical alliance. Their mess should be cleaned up after revision 2554.
