### ISSUE TITLE
[Quest] Give Gerard a Drink

### ISSUE THREAD

**Issue by Anonyxx** [Atlantiss/NetherwingBugtracker#3769]
[//]: # (Enclose links to things related to the bug using http://wowhead.com or any other TBC database.)
[//]: # (You can use screenshot ingame to visual the issue.)
[//]: # (Write your tickets according to the format:)
[//]: # ([Quest][Azuremyst Isle] Red Snapper - Very Tasty!)
[//]: # ([NPC] Magistrix Erona)
[//]: # ([Spell][Mage] Fireball)
[//]: # ([Npc][Drop] Ghostclaw Lynx)
[//]: # ([Web] Armory doesnt work)
[//]: # (To find server revision type `.server info` command in the game chat.)

**Description**: 

In 2.0, the quest Give Gerard a Drink should reward 1 reputation with Stormwind. This was changed in a later TBC patch to award 0 rep, but in earlier versions of TBC (2.0.1) this quest should award 1 reputation with Stormwind. Since we are on 2.0, then this quest should be changed too. 

I remember doing this quest early on in TBC on retail as it was well known to give a small bit of rep with Stormwind.

**Current behaviour**:

Does not reward rep upon completion.

**Expected behaviour**: 

Should award 1 rep for each server turn in.

**Server Revision**: 
2550

**Comment by wtRCH** [comment]
Azeroth world is post 2.3
