### ISSUE TITLE
Scroll of Protection replacing Devotion Aura

### ISSUE THREAD

**Issue by ttghnw** [Atlantiss/NetherwingBugtracker#377]
[//]: # (Enclose links to things related to the bug using http://wowhead.com or any other TBC database.)
[//]: # (You can use screenshot ingame to visual the issue.)
[//]: # (Write your tickets according to the format:)
[//]: # ([Quest][Azuremyst Isle] Red Snapper - Very Tasty!)
[//]: # ([NPC] Magistrix Erona)
[//]: # ([Spell][Mage] Fireball)
[//]: # ([Npc][Drop] Ghostclaw Lynx)
[//]: # ([Web] Armory doesnt work)

**Description**: 

**Current behaviour**:
Scroll of Protection replacing Devotion Aura
**Expected behaviour**: 
Should not
**Server Revision**:

**Comment by wtRCH** [comment]
Buff stacking issue

**Comment by Wolffenstein** [comment]
Fixed in rev 2048.
