### ISSUE TITLE
[Warlock][Enslave Demon][Wrath fiend]

### ISSUE THREAD

**Issue by tutuma499** [Atlantiss/NetherwingBugtracker#3770]
The Wrath Fiend (Forge camp: Wrath in blade's edge mountain) is doing crazy damage when he is enslaved.

https://streamable.com/yvszg
https://streamable.com/aivmv

https://i.imgur.com/3Kgs2lE.jpg

**Comment by tutuma499** [comment]
It seems like most Enslaved demons abilities don't use cooldown when they are on auto cast and When they aren't the damage scale with spell power.

**Comment by Evolvee** [comment]
rev 2655
