### ISSUE TITLE
[Warrior][Spell] Spell reflection

### ISSUE THREAD

**Issue by bloodwindz** [Atlantiss/NetherwingBugtracker#3771]
[//]: # (Enclose links to things related to the bug using http://wowhead.com or any other TBC database.)
[//]: # (You can use screenshot ingame to visual the issue.)
[//]: # (Write your tickets according to the format:)
[//]: # ([Quest][Azuremyst Isle] Red Snapper - Very Tasty!)
[//]: # ([NPC] Magistrix Erona)
[//]: # ([Spell][Mage] Fireball)
[//]: # ([Npc][Drop] Ghostclaw Lynx)
[//]: # ([Web] Armory doesnt work)
[//]: # (To find server revision type `.server info` command in the game chat.)

**Description**: spell reflection on judgment

**Current behaviour**: judgment of paladin is not get spell reflected when spell reflection of a warrior  is active  but warr get the damage normaly

**Expected behaviour**: it should get spell reflected

**Server Revision**: 2550

**Comment by Evolvee** [comment]
proof?

I dont think it should be reflected. its not considered "magical" effect. They dont destroy grounding totem as well.

**Comment by killablink** [comment]
I also believe you can't reflect judgement. It's the same thing as hammer of wrath

**Comment by Evolvee** [comment]
https://us.battle.net/forums/en/wow/topic/7592200251
https://www.wowhead.com/forums&topic=107792.1
https://github.com/ccshiro/cc-buglist/issues/2328
