### ISSUE TITLE
[Spell][Warlock] Dark pact

### ISSUE THREAD

**Issue by Shinizaa** [Atlantiss/NetherwingBugtracker#3772]
Description:

The ability Dark Pact from the the Warlock's Affliction Tree is not working.

Current behaviour:

Using Dark Pact correctly drains the mana from the pet, but does not return it to the caster. The combat log shows the correct ammount of mana that shoud be gained, but in reality nothing happens.

Expected behaviour:

Dark Pact drains the mana from the pet and transfers it to the Warlock.

**Comment by Brasso** [comment]
Already reported #3395
