### ISSUE TITLE
Auto Attack gets you stuck in combat after Duel (Visual)

### ISSUE THREAD

**Issue by Kidtoucher** [Atlantiss/NetherwingBugtracker#3773]
**Description**: 
When dueling and doing the final Attack with Auto Attack, the combat status and animation keep you in combat. However, you can still drink which makes it a _visual_ bug.
 
**Current behaviour**:
When dueling and doing the final Attack with Auto Attack, the combat status and animation keep you in combat. However, you can still drink which makes it a _visual_ bug.

**Expected behaviour**: 
Shouldn´t be stuck in combat after a duel ends.

![](https://image.prntscr.com/image/tqintOkvTVekvieEE-sN6A.png)

**Comment by killablink** [comment]
#3306 bug 2 and 4

**Comment by Wolffenstein** [comment]
Please retest after revision 2563.
