### ISSUE TITLE
[Arena] Stealth Orb while in stealth

### ISSUE THREAD

**Issue by wtRCH** [Atlantiss/NetherwingBugtracker#3775]
[//]: # (Enclose links to things related to the bug using http://wowhead.com or any other TBC database.)
[//]: # (You can use screenshot ingame to visual the issue.)
[//]: # (Write your tickets according to the format:)
[//]: # ([Quest][Azuremyst Isle] Red Snapper - Very Tasty!)
[//]: # ([NPC] Magistrix Erona)
[//]: # ([Spell][Mage] Fireball)
[//]: # ([Npc][Drop] Ghostclaw Lynx)
[//]: # ([Web] Armory doesnt work)
[//]: # (To find server revision type `.server info` command in the game chat.)

**Description**: Picking orb in stealth

**Current behaviour**: Picking orb while in stealth doesn't remove stealth/prowl (invisiblity too?) from you.

**Expected behaviour**: Picking orb in arena while in stealth should remove stealth/prowl (invisiblity too?) from you.

**Server Revision**:

**Comment by alextmofo** [comment]
https://youtu.be/ItiaES2ch7A?t=170 proof of how it should work, you can see its a debuff that has a DoT

**Comment by killablink** [comment]
That's two different things. I forgot based on which patch we're using but I believe we're using the gem that gives you increased dmg instead of a DoT.

For what OP said, yes picking up the gem should bring you out of stealth.

**Comment by alextmofo** [comment]
"n patch 2.4 this will increase all damage taken by 5% and only last 15 seconds instead of putting a DoT on you and lasting 21 seconds as it did before." https://www.wowhead.com/spell=34709/shadow-sight#comments

**Comment by Wolffenstein** [comment]
Fixed in rev 2555.
