### ISSUE TITLE
[Warlock][Enslave Demon][Jadefire mobs]

### ISSUE THREAD

**Issue by tutuma499** [Atlantiss/NetherwingBugtracker#3777]
I found several bugs on the jadefire mobs in felwood (Jadefire run camp)

Jadefire Hellcaller is doing crazy damage when he is enslaved i'm not even sure they are supposed to have fireball while enslaved.
https://streamable.com/i9riv

Jadefire Trickster
i'm fairly sure they're not supposed to have "Cause insanity" spell while enslaved
https://streamable.com/7zyai

Jadefire Rogue : No cooldown on Gouge

**Comment by wtRCH** [comment]
@Evolvee @Wolffenstein Heavy abuse.

**Comment by Drayo** [comment]
Oh boy.

**Comment by networm555** [comment]
Before allissues are  fixed i recommend disabling enslave at all. Pretty sure alot of demons have similar issue when enslaved and this takes time to fix. And you dont have a time.
For example some warlocks at ares abused this shit for month especially in pvp.

**Comment by Wolffenstein** [comment]
Yeah but are you sure it's not because his dmg scales with your level (70)?

**Comment by Brasso** [comment]
Does not scale with level. https://youtu.be/S5u6JScHNxY Works as level 55 aswell.

**Comment by tutuma499** [comment]
It seems like most Enslaved demons abilities don't use cooldown when they are on auto cast and When they aren't the spell damage scale with spell power.

**Comment by Evolvee** [comment]
spell removed
