### ISSUE TITLE
[Enchant] Steel Weapon Chain

### ISSUE THREAD

**Issue by PembrokePB** [Atlantiss/NetherwingBugtracker#3778]
[//]: # (Enclose links to things related to the bug using http://wowhead.com or any other TBC database.)
[//]: # (You can use screenshot ingame to visual the issue.)
[//]: # (Write your tickets according to the format:)
[//]: # ([Quest][Azuremyst Isle] Red Snapper - Very Tasty!)
[//]: # ([NPC] Magistrix Erona)
[//]: # ([Spell][Mage] Fireball)
[//]: # ([Npc][Drop] Ghostclaw Lynx)
[//]: # ([Web] Armory doesnt work)
[//]: # (To find server revision type `.server info` command in the game chat.)

**Description**: 
Steel Weapon chain provided full immunity to disarms until 2.3 currently it does not do this and only provides 50%.
**Current behaviour**:
Currently provides only 50% immunity
**Expected behaviour**: 
should provide full immunity until patch 2.3
**Server Revision**:

**Comment by wtRCH** [comment]
@aresbrutus

**Comment by PembrokePB** [comment]
I personally think its something to note out especially leveling and a good way for gold for blacksmiths at early levels

**Comment by Wolffenstein** [comment]
It will remain the same.

**Comment by wcraycroft** [comment]
If that is the case, then the adamantite weapon chain should be added prior to 2.3. Since it was added at the same time as the 50% nerf, there was never a point in TBC where 50% reduced duration was the highest in the game.
