### ISSUE TITLE
Betrayal from Within

### ISSUE THREAD

**Issue by Hardfelt** [Atlantiss/NetherwingBugtracker#3779]
[//]: # (Enclose links to things related to the bug using http://wowhead.com or any other TBC database.)
[//]: # (You can use screenshot ingame to visual the issue.)
[//]: # (Write your tickets according to the format:)
[//]: # ([Quest][Azuremyst Isle] Red Snapper - Very Tasty!)
[//]: # ([NPC] Magistrix Erona)
[//]: # ([Spell][Mage] Fireball)
[//]: # ([Npc][Drop] Ghostclaw Lynx)
[//]: # ([Web] Armory doesnt work)
[//]: # (To find server revision type `.server info` command in the game chat.)

**Description**: 
![wowscrnshot_010219_001242](https://user-images.githubusercontent.com/46285613/50581067-ef1fe580-0e23-11e9-8e26-a5a50092a223.jpg)
Quest dialogue is bugged, no way to turn in. Screen shot pretty much describes it.
**Current behaviour**:

**Expected behaviour**: 

**Server Revision**:

**Comment by wtRCH** [comment]
Please turn all of your addons and try again.

**Comment by wtRCH** [comment]
![image](https://user-images.githubusercontent.com/11255782/50581323-fe6d5600-0e58-11e9-8b93-c558a23cae9a.png)
Closing
