### ISSUE TITLE
[NPC] Myst Leecher - missing spell

### ISSUE THREAD

**Issue by Firroth** [Atlantiss/NetherwingBugtracker#378]
[NPC] Myst Leecher https://www.wowdb.com/npcs/17523-myst-leecher

**Current behaviour**:
Doesn't use spell leech poison https://www.wowdb.com/spells/31288-leech-poison

**Expected behaviour**: 
Uses spell https://www.wowdb.com/spells/31288-leech-poison

**Server Revision**: 
2040

**Comment by The14me** [comment]
Have the spell in rev 2083.
