### ISSUE TITLE
[Quest] [Undead Starting Area] The Damned - no shared loot

### ISSUE THREAD

**Issue by LostInLyrics** [Atlantiss/NetherwingBugtracker#3780]
**HIGH PRIORITY**

**Description**: 
We just did the Quest "The Damned" in the Undead Starting Area Deathknell (first big loot quest in the area) and only one person was able to loot the quest item per mob. If group looting isn't enabled on one of the first quests, it wouldnt make the server look too good.

**Expected behaviour**: 
With group looting, both players should be able to loot the quest item dropped by these mobs.

**Server Revision**: 
2555

**Comment by Wolffenstein** [comment]
It works fine for me...

**Comment by LostInLyrics** [comment]
We cleared our cache, tried again on new chars and it worked.

Was a problem on our side then, sorry. You guys can close this issue.
