### ISSUE TITLE
world breaker proc and other weapons 

### ISSUE THREAD

**Issue by fastfu** [Atlantiss/NetherwingBugtracker#3782]
i tried world breaker and it displayed proc on combat text but didnt affect stats or be shown as buff in corner and im quite sure it doesnt even work at all

**Comment by bloodwindz** [comment]
it does work fine and its prety good the buff icon migt be bugged the crit chance removed after you crit once i get 69%crit with it and its sound like thunderclap when it procs

**Comment by fastfu** [comment]
it might just be me but it definitley doesnt work at all
