### ISSUE TITLE
[Warlock][Enslave Demon][Nagrand Mobs]

### ISSUE THREAD

**Issue by tutuma499** [Atlantiss/NetherwingBugtracker#3783]
Felguard Legionnaire : No cooldown on "Cutdown" spell
https://streamable.com/wnrri

Mo'arg Engineer : No cooldown on "Puncture" and "Thorium Drill" spell
https://streamable.com/t8i7v

Terrorguard :  No cooldown on "War stomp" spell
https://streamable.com/74ubk

**Comment by wtRCH** [comment]
@Wolffenstein

**Comment by tutuma499** [comment]
It seems like most Enslaved demons abilities don't use cooldown when they are on auto cast and When they aren't the spell damage scale with spell power.

**Comment by Wolffenstein** [comment]
Fixed in rev 2580.
