### ISSUE TITLE
game crashes while dead and ghost teleports to hearthstone location

### ISSUE THREAD

**Issue by Ominouss** [Atlantiss/NetherwingBugtracker#3784]
[//]: # (Enclose links to things related to the bug using http://wowhead.com or any other TBC database.)
[//]: # (You can use screenshot ingame to visual the issue.)
[//]: # (Write your tickets according to the format:)
[//]: # ([Quest][Azuremyst Isle] Red Snapper - Very Tasty!)
[//]: # ([NPC] Magistrix Erona)
[//]: # ([Spell][Mage] Fireball)
[//]: # ([Npc][Drop] Ghostclaw Lynx)
[//]: # ([Web] Armory doesnt work)
[//]: # (To find server revision type `.server info` command in the game chat.)

**Description**: 
game crashes while dead and ghost teleports to hearthstone location
**Current behaviour**:
game crashes while dead and ghost teleports to hearthstone location
**Expected behaviour**: 
game crashes while dead and ghost stays where it is
**Server Revision**:

**Comment by Tenoutoften** [comment]
Going to need a bit more background information on that I'd assume...

**Comment by The14me** [comment]
If u find the specific place to reproduce that, please let me know.Never seen that happen to me or anyone else since release.
