### ISSUE TITLE
DragonStrike

### ISSUE THREAD

**Issue by Djenery** [Atlantiss/NetherwingBugtracker#3785]
**Description**: 
DragonStrike has incorrect hand. In game it has main-hand but correct is one-hand. 
**Current behaviour**:
https://pastenow.ru/128918c2032d480132fee449b394249d
but 
every tbc database says that it has one-hand:
http://db.hellfire-tbc.com/?item=28439
https://tbc-twinhead.twinstar.cz/?item=28439#created-by
https://db.darkwizard.pl/?item=28439

**Comment by aresbrutus** [comment]
We use 2.0 itemization, please clear your cache folder and restart your client.

**Comment by tcberk12** [comment]
This is an invalid report. It was changed to main-hand in patch 2.4

**Comment by aresbrutus** [comment]
https://web.archive.org/web/20070512153640/http://www.wowhead.com:80/?item=28439
