### ISSUE TITLE
[Rogue][Spell] Vanish + Combat

### ISSUE THREAD

**Issue by killablink** [Atlantiss/NetherwingBugtracker#3786]
**Description**: https://gfycat.com/EagerConcreteCrossbill The rogue vanishes my kidney shot and is supposed to be out of combat but isn't so I wasn't able to sap him after vanishing myself. This is pretty important interaction in rogue vs rogue as to how you should be able to reliably sap the other rogue if you both just vanished an ability.

**Expected behaviour**:  Shouldn't be in combat after vanishing an ability.

**Server Revision**: 2555

**Comment by Wolffenstein** [comment]
Are you sure it's the kidney shot that prolonged combat on him?

**Comment by killablink** [comment]
Nothing else hit him except kidney shot when he vanished. What I think happened is he vanished, lost combat but the kidney came at same time so he got in combat. I don't know how all the interaction with batching and stuff should work though

**Comment by Wolffenstein** [comment]
Please retest in rev 2564.
