### ISSUE TITLE
[Dungeon][Chests] Slave Pens - Missing Chest in 2nd room before boss

### ISSUE THREAD

**Issue by dominion-pvp** [Atlantiss/NetherwingBugtracker#3787]
[//]: # (Enclose links to things related to the bug using http://wowhead.com or any other TBC database.)
[//]: # (You can use screenshot ingame to visual the issue.)
[//]: # (Write your tickets according to the format:)
[//]: # ([Quest][Azuremyst Isle] Red Snapper - Very Tasty!)
[//]: # ([NPC] Magistrix Erona)
[//]: # ([Spell][Mage] Fireball)
[//]: # ([Npc][Drop] Ghostclaw Lynx)
[//]: # ([Web] Armory doesnt work)
[//]: # (To find server revision type `.server info` command in the game chat.)

**Description**: 
Missing Chest near all the crab people in the 2nd room before you enter the room with the boss.

**Current behaviour**:
Chest is not currently in dungeon (both heroic and normal)
![image](https://user-images.githubusercontent.com/46330764/50614318-31cdd600-0e95-11e9-8944-fcd11c14e86e.png)

**Expected behaviour**: 
Here is a video linked from 2007 and a screen shot showing the chest is in the dungeon
![image](https://user-images.githubusercontent.com/46330764/50614389-73f71780-0e95-11e9-84b0-1549f5187a98.png)
https://www.youtube.com/watch?v=HK2Et7RL1ak
**Server Revision**:

**Comment by Manaci** [comment]
Removed cause too easy to farm
