### ISSUE TITLE
[Dungeon][Chests] Mechanar - Missing both chests near Gatewatcher Iron-hand

### ISSUE THREAD

**Issue by dominion-pvp** [Atlantiss/NetherwingBugtracker#3789]
[//]: # (Enclose links to things related to the bug using http://wowhead.com or any other TBC database.)
[//]: # (You can use screenshot ingame to visual the issue.)
[//]: # (Write your tickets according to the format:)
[//]: # ([Quest][Azuremyst Isle] Red Snapper - Very Tasty!)
[//]: # ([NPC] Magistrix Erona)
[//]: # ([Spell][Mage] Fireball)
[//]: # ([Npc][Drop] Ghostclaw Lynx)
[//]: # ([Web] Armory doesnt work)
[//]: # (To find server revision type `.server info` command in the game chat.)

**Description**: 
Missing the chests near Gatewatcher Iron-hand in Mechanar (N) and (H)
**Current behaviour**:
Chests do not spawn in Mechanar
Chest 1
![image](https://user-images.githubusercontent.com/46330764/50614633-668e5d00-0e96-11e9-9e64-f7076db20063.png)
Chest 2
![image](https://user-images.githubusercontent.com/46330764/50614728-a8b79e80-0e96-11e9-841a-b49053f81dc3.png)

**Expected behaviour**: 
Chest 1
![image](https://user-images.githubusercontent.com/46330764/50614621-537b8d00-0e96-11e9-9fbf-23442d601a79.png)

Chest 2
![image](https://user-images.githubusercontent.com/46330764/50614702-976e9200-0e96-11e9-97e2-a42ed77ac8fe.png)

**Server Revision**:

**Comment by Manaci** [comment]
Intentional removal
