### ISSUE TITLE
[Quest][Moonglade] Trial of the Lake - Aquatic form druid quest 

### ISSUE THREAD

**Issue by wowthings** [Atlantiss/NetherwingBugtracker#379]
[//]: # (Enclose links to things related to the bug using http://wowhead.com or any other TBC database.)
[//]: # (You can use screenshot ingame to visual the issue.)
[//]: # (Write your tickets according to the format:)
[//]: # ([Quest][Azuremyst Isle] Red Snapper - Very Tasty!)
[//]: # ([NPC] Magistrix Erona)
[//]: # ([Spell][Mage] Fireball)
[//]: # ([Npc][Drop] Ghostclaw Lynx)
[//]: # ([Web] Armory doesnt work)

**Description**: 
There should be a pickup object in Moonglade for this [this quest](https://www.wowhead.com/quest=28/trial-of-the-lake) at the bottom of the lake Elune'ara on a random position. Explored the entire lake for 20 minutes and no luck.
**Current behaviour**:
Pickup object not spawning.

**Comment by wowthings** [comment]
Update: 
Went back and it spawned in front of me after swimming around for a bit. Maybe the time of the spawn is fucked? It's doable anyways.

**Comment by totaemoeggerli** [comment]
found it at 54 47 and a new one spawned at 54 50 moments later
there are 3 or more red circles spread in the lake and the vase spawns in one of them

**Comment by Easyfraggy** [comment]
So this issue is invalid?

**Comment by wowthings** [comment]
Yep, guess I had a severe case of bad luck the first time I went there. Wop
