### ISSUE TITLE
[Rogue][Spell] Blind a vanish interaction.

### ISSUE THREAD

**Issue by killablink** [Atlantiss/NetherwingBugtracker#3793]
Description: Using blind on a rogue when he already went and vanished should pop him out of stealth and be blinded in this case. At the very least break out of stealth (that's when you blind the rogue exactly at the same time as vanish, if you blind slightly after he vanished like the clip he should be out of stealth and blinded) I played many arena games where I blinded the rogue in that exact same pattern, slightly after he vanished but every time he was still in stealth and not blinded.
https://gfycat.com/EasySpitefulAxolotl

Current behaviour:

Expected behaviour: https://www.youtube.com/watch?v=xF4Rx1sQYQU&feature=youtu.be&t=91
Target should break out of stealth and be blinded

Server Revision: 2555

**Comment by wtRCH** [comment]
@Evolvee

**Comment by Evolvee** [comment]
Vanish should work like this:
1) if u cast or autoattack into vanish fadeout time period(vanish visible), vanish and stealth should cancel and u should be affected by the cast
2) if u cast before the fade out time, vanish and stealth should cancel but you shouldnt be affected by the cast
3) if its a a projectile cast and you vanish mid air, both stealth and vanish are preserved and the cast is negated

**Comment by killablink** [comment]
Pretty much what Evolve said
