### ISSUE TITLE
[spell][Orc Racial] Can't use spell.

### ISSUE THREAD

**Issue by Stxks** [Atlantiss/NetherwingBugtracker#3794]
[//]: # (Enclose links to things related to the bug using http://wowhead.com or any other TBC database.)
[//]: # (You can use screenshot ingame to visual the issue.)
[//]: # (Write your tickets according to the format:)
[//]: # ([Quest][Azuremyst Isle] Red Snapper - Very Tasty!)
[//]: # ([NPC] Magistrix Erona)
[//]: # ([Spell][Mage] Fireball)
[//]: # ([Npc][Drop] Ghostclaw Lynx)
[//]: # ([Web] Armory doesnt work)
[//]: # (To find server revision type `.server info` command in the game chat.)

**Description**: 
When I try to use the Orc Racial nothing happens. Tried with Elvui that has key press on down both turned on and disabled. Also tried with 0 Addons enabled 100% blizzard Ui after relogging. Not in combat and not on cooldown. Has been working fine today.
**Current behaviour**:
Ability highlights on Action Bar but does not use. ![wowscrnshot_010219_184701](https://user-images.githubusercontent.com/46333276/50619538-56d73e80-0ebf-11e9-954f-72cee79609f1.jpg)
**Expected behaviour**: 
Ability to be used granting buff and Ability to go on cooldown.
**Server Revision**: 
2555

**Comment by Brasso** [comment]
Issue on your end. Try disabling addons.

**Comment by Stxks** [comment]
i did try those and still didnt work, On rev 2566 now and its working idk
