### ISSUE TITLE
[Master]Last two server updates caused slight rollback

### ISSUE THREAD

**Issue by Tenoutoften** [Atlantiss/NetherwingBugtracker#3795]
**Description/Current behaviour**: 
The last two server updates caused a slight rollback in terms of positioning & loot.
These server updates were around 00:00 - 03:00 ~

**Expected behaviour**: 

**Server Revision**: 
2550

**Comment by sweetbakery** [comment]
This is not exactly a bug I think. The server does a backup and then It restarts. If you perform any action during the server backup and the restart, this action will be undone.

**Comment by wtRCH** [comment]
Not a bug
