### ISSUE TITLE
reset ID glitch

### ISSUE THREAD

**Issue by gaypala** [Atlantiss/NetherwingBugtracker#3798]
so first of all i wanted 2 know hc reset timer cycle.I did 1hc 3days ago and 1 hc more than 1day ago/when i did last 1 it had 1day 3h timer reset liek with 1st one.i was waiting them 2  reset and loged in after 5am today.But my ids did not reset i had new 24hours reset timer.

**Comment by ircfelix** [comment]
What?

**Comment by gaypala** [comment]
ID list did not reset exept of this i got 24hours timer.......

**Comment by gaypala** [comment]
first of all i was wonder why i had more than 24hours reset timer for heroic.

**Comment by gaypala** [comment]
![wowscrnshot_010319_161622](https://user-images.githubusercontent.com/46336832/50669523-b5431080-0fd6-11e9-8149-7bf184d18153.jpg)
![wowscrnshot_010319_161709](https://user-images.githubusercontent.com/46336832/50669532-c429c300-0fd6-11e9-9a5a-4c99c8319937.jpg)
![wowscrnshot_010419_040904](https://user-images.githubusercontent.com/46336832/50669540-cbe96780-0fd6-11e9-97d1-caf247819ee8.jpg)
![wowscrnshot_010419_040909](https://user-images.githubusercontent.com/46336832/50669557-d9065680-0fd6-11e9-9bc5-7f87ccfc9e58.jpg)

**Comment by wtRCH** [comment]
@aresbrutus

**Comment by Manaci** [comment]
Fixed
