### ISSUE TITLE
Ghost spawn bug

### ISSUE THREAD

**Issue by Dekirayne** [Atlantiss/NetherwingBugtracker#38]
[//]: # (Enclose links to things related to the bug using http://wowhead.com or any other TBC database.)
[//]: # (You can use screenshot ingame to visual the issue.)
[//]: # (Write your tickets according to the format:)
[//]: # ([Quest][Azuremyst Isle] Red Snapper - Very Tasty!)
[//]: # ([NPC] Magistrix Erona)
[//]: # ([Spell][Mage] Fireball)
[//]: # ([Npc][Drop] Ghostclaw Lynx)
[//]: # ([Web] Armory doesnt work)

**Description**: 
On Death "Release spirit" spawned my ghost instantly to the corpse
**Current behaviour**:

**Expected behaviour**: 
Should spawn ghost at spirit healer
**Server Revision**:

**Comment by wtRCH** [comment]
Fixed
