### ISSUE TITLE
Fences and NPCs pathing around it

### ISSUE THREAD

**Issue by nycheia** [Atlantiss/NetherwingBugtracker#380]
http://prntscr.com/ky4nqw

**Description**: 
Mobs running above fences (tested with three different mobs, Wandering Spirit, Bleeding Horror and Vampiric Bat)

**Current behaviour**:
The mobs run above the fence.

**Expected behaviour**: 
Its supposed to run around, except if its a 'low' fence iirc.

**Server Revision**: 
16:50 CEST 24-09-2018

**Comment by wtRCH** [comment]
Blizzlike
