### ISSUE TITLE
[Shaman][Spell] Ghost Wolf 

### ISSUE THREAD

**Issue by bloodwindz** [Atlantiss/NetherwingBugtracker#3800]
[//]: # (Enclose links to things related to the bug using http://wowhead.com or any other TBC database.)
[//]: # (You can use screenshot ingame to visual the issue.)
[//]: # (Write your tickets according to the format:)
[//]: # ([Quest][Azuremyst Isle] Red Snapper - Very Tasty!)
[//]: # ([NPC] Magistrix Erona)
[//]: # ([Spell][Mage] Fireball)
[//]: # ([Npc][Drop] Ghostclaw Lynx)
[//]: # ([Web] Armory doesnt work)
[//]: # (To find server revision type `.server info` command in the game chat.)

**Description**: kill the caster

**Current behaviour**:when talented or untalented ghost wolf is casted  the shaman will die instantly

**Expected behaviour**:--

**Server Revision**: 2566

**Comment by wtRCH** [comment]
Can you explain that a bit more?

**Comment by Brasso** [comment]
Works fine for me.

**Comment by aresbrutus** [comment]
This is probably due to an item and not actually the ghost wolf spell: https://github.com/Atlantiss/NetherwingBugtracker/issues/3802

**Comment by Wolffenstein** [comment]
Fixed in rev 2569.
