### ISSUE TITLE
[Core]Leash Range of slowed mobs is off

### ISSUE THREAD

**Issue by ircfelix** [Atlantiss/NetherwingBugtracker#3801]
**Description**: 
A few days ago I have been running a SHH heroic. While aoeing, I saw I pulled aggro from some mobs. In order to prevent a painful death, I used cone of cold to slow the mob following me (see EavesDrop in the right corner of the screen). The mob who hit me was the mob next to the priest resurrecting me. As you can see from the screenshots in https://imgur.com/a/j38nd6x, the leash range of the mob is absurdly high. I have also experienced this during some aoe grind tries, that I had to get so far away from mobs that my spells did not hit all mobs any more, in order to prevent being hit by mobs.

**Current behaviour**:
Leash range of mobs while moving seems to be too high.

**Expected behaviour**: 
Leash range of mobs while moving should be lower.

**Server Revision**:

**Comment by Wolffenstein** [comment]
Fixed in rev 2569.

**Comment by ircfelix** [comment]
<3
