### ISSUE TITLE
[Item] Star-Strider Boots - kills me

### ISSUE THREAD

**Issue by Tim130** [Atlantiss/NetherwingBugtracker#3802]
[//]: # (Enclose links to things related to the bug using http://wowhead.com or any other TBC database.)
[//]: # (You can use screenshot ingame to visual the issue.)
[//]: # (Write your tickets according to the format:)
[//]: # ([Quest][Azuremyst Isle] Red Snapper - Very Tasty!)
[//]: # ([NPC] Magistrix Erona)
[//]: # ([Spell][Mage] Fireball)
[//]: # ([Npc][Drop] Ghostclaw Lynx)
[//]: # ([Web] Armory doesnt work)
[//]: # (To find server revision type `.server info` command in the game chat.)

**Description**: 
The dressing of "Star-Strider Boots" kills me instantly. Combat Log only says "...died.", no damage.

**Current behaviour**:

**Expected behaviour**: 

**Server Revision**: 
Server Revision: 2566
Content Patch 203

**Comment by gaypala** [comment]
lul

**Comment by Brasso** [comment]
Can confirm the boots kill you instantly.

**Comment by Evolvee** [comment]
top kek

**Comment by Wolffenstein** [comment]
Fixed in rev 2569.
