### ISSUE TITLE
[Hunter][spell] Instant shots

### ISSUE THREAD

**Issue by QWERTYQWERTYQWERTYX** [Atlantiss/NetherwingBugtracker#3804]
**Description**: 
 Sometimes hunter cannot use instant shots (even scatter) until an automatic shot occurs. This is a very important bug, hunters cant pvp and kite mobs.

**Current behaviour**:
https://streamable.com/ds3s0

**Expected behaviour**: 
should work as it should

**Server Revision**: 
2567

**Comment by Wolffenstein** [comment]
Fixed in rev 2569.
