### ISSUE TITLE
Sent on random flightpath to the veiled sea while standing on scryers tier 

### ISSUE THREAD

**Issue by rasin00** [Atlantiss/NetherwingBugtracker#3805]
[//]: # (Enclose links to things related to the bug using http://wowhead.com or any other TBC database.)
[//]: # (You can use screenshot ingame to visual the issue.)
[//]: # (Write your tickets according to the format:)
[//]: # ([Quest][Azuremyst Isle] Red Snapper - Very Tasty!)
[//]: # ([NPC] Magistrix Erona)
[//]: # ([Spell][Mage] Fireball)
[//]: # ([Npc][Drop] Ghostclaw Lynx)
[//]: # ([Web] Armory doesnt work)
[//]: # (To find server revision type `.server info` command in the game chat.)

**Description**: 

**Current behaviour**:

**Expected behaviour**: 

**Server Revision**:

**Comment by rasin00** [comment]
Was just standing still after i used my hs and sent to the veiled sea, flying through the earth and just kept dying over and over, nailrave helped me out but earlier on i was on flight to dustwallow and could not dismount unless i mounted my kodo or started to HS

**Comment by Wolffenstein** [comment]
Fixed in rev 2569.
