### ISSUE TITLE
[Quest] [The Barrens] Meats to Orgrimmar #6365

### ISSUE THREAD

**Issue by mantacore** [Atlantiss/NetherwingBugtracker#3806]
The quest 'Meats to Orgrimmar' is not available from Zargh in the Crossroads.  There are no pre requisites for this quest except being level 10.

This quest is key for Taurens as a fast way to get the flight point in Orgrimmar

![image](https://user-images.githubusercontent.com/6078611/50653748-7c794c00-0f82-11e9-966f-ba3e41bd58f5.png)

**Comment by Epsynus** [comment]
According to the old thottbot comments imported here: https://classic.wowhead.com/quest=6365/meats-to-orgrimmar

While it appears that *some* Tauren's were able to get the quest. it is supposed to be for Orcs and Trolls only.

While Tauren have: A Bundle of Hides instead.

Same information is present: http://wowwiki.wikia.com/wiki/Quest:Meats_to_Orgrimmar

**Comment by mantacore** [comment]
Hmm that does seem a bit odd to get a quest for a flight point that you would already have.  But guess it is was it is..
