### ISSUE TITLE
([Spell][Paladin] Spiritual Attunement)

### ISSUE THREAD

**Issue by Neccos** [Atlantiss/NetherwingBugtracker#3807]
**Description**: Spiritual Attunement is not giving mana when the heal being used on the paladin bring the paladin from x% to 100% full health. It works as intended as long as the paladin is not brough up to maximum health. Example: Paladin is at 50% health, heal crits him and brings him to 100% health, paladin does not gain mana.

**Current behaviour**: Works fine unless the heal is bringing paladin to maximum health.

**Expected behaviour**: The paladin would gain mana equal to the amount of health healed despite if the heal heals them to full.

**Server Revision**:

**Comment by staplerx300** [comment]
still bugged btw, makes dungeons horrible

**Comment by Nonamesleftffs** [comment]
https://youtu.be/YSQuG-IqUJ4

Made a video to show just how bad the issue is - It's returning around 3% of healing received rather than 10%. This is effectively making Protection Paladins not viable.

**Comment by totaemoeggerli** [comment]
please fix this issue as fast as possible

**Comment by Nonamesleftffs** [comment]
Still not fixed. I am posting about it on discord virtually every day and devs just take the piss..

**Comment by Wolffenstein** [comment]
Fixed in rev 2741.

**Comment by Arnamik12** [comment]
This is broken again like before the fix :(
