### ISSUE TITLE
[Item][Engineering] Gnomish Battle Chicken

### ISSUE THREAD

**Issue by Xynaps** [Atlantiss/NetherwingBugtracker#3808]
**Description**:  The guardian spawned by the [Gnomish Battle Chicken](https://www.wowhead.com/item=10725/gnomish-battle-chicken) has incorrect level.

**Current behaviour**:  The guardian spawned is a level 1 npc. And it does not attack neutral targets.

**Expected behaviour**:  Depends on which patch it is tuned for. 

Pre 2.4: Should be scaling with engineering level and 30 minute cooldown.
2.4 - 2.4.2: Set to level 55, does not scale with engineering level, 20 minute cooldown.
2.4.3: Scales with engineering level again.

Should also attack neutral targets attacked by the player.

[Link that references patch changes](https://wowwiki.wikia.com/wiki/Gnomish_Battle_Chicken). 

**Server Revision**:  2570

**Comment by Unrelented** [comment]
Could we get a fix on this? Server claims to be an experience like no other with authenticity it doesn't seem like something that should be pushed aside. 
I opened a note about this and was told to leave something on Discord? 
I spent like 10G on the mats for this just to be disappointed & unable to troll people with it on the level I deserve. One problem overlooked is another negative perception gone untouched lets make this the only place true level 70 players wish to be. Thank you~

**Comment by Refuge001** [comment]
Honestly, this needs to be fixed.

**Comment by Refuge001** [comment]
Opened January 03, what in the world is going on here.

**Comment by Evolvee** [comment]
https://github.com/Atlantiss/NetherwingBugtracker/issues/6265
https://github.com/Atlantiss/NetherwingBugtracker/issues/5347
