### ISSUE TITLE
[Quest][Westfall] The Defias Brotherhood (the Defias Traitor escort)

### ISSUE THREAD

**Issue by Shalovski** [Atlantiss/NetherwingBugtracker#381]
**Description**: 
After the NPC died and the escort failed (the server also crashed right after it happened), the quest disappeared from the quest log while making it unable to be picked again or to be abandoned it in the quest log.

**Current behaviour**:
If someone in the party starts the quest, a message popup says that the player is already on the quest. But when those other players check their quest log after they started it, it does not show that the player is on the quest.

**Expected behaviour**: 
The quest should not disappear from the quest log.
The quest is probably still active with "(failed)" status, while player is unable to abandon it since it does not show in the quest log.

**Server Revision**:

**Comment by wtRCH** [comment]
Refered to https://github.com/Atlantiss/NetherwingBugtracker/issues/267 , https://github.com/Atlantiss/NetherwingBugtracker/issues/308 ,

**Comment by Wolffenstein** [comment]
Fixed in rev 2138.
