### ISSUE TITLE
[Rogue] Stealth is too slow, weird interaction when using throw

### ISSUE THREAD

**Issue by killablink** [Atlantiss/NetherwingBugtracker#3810]
**Description**: I was able to use throw on my rogue to hit a rogue out of stealth when he was stealthed way before I started my throw animation.

https://gfycat.com/AmazingAptKillerwhale

**Current behaviour**:

**Expected behaviour**: This should never happen. 

**Server Revision**: 2570

**Comment by Wolffenstein** [comment]
Fixed in rev 2573.
