### ISSUE TITLE
When using flight master you should only land on your last stop

### ISSUE THREAD

**Issue by karabitaz** [Atlantiss/NetherwingBugtracker#3812]
**Description**:  if you for example fly from ogri to tb, you land in crossroads and lift off again, but on retail if you fly above crossroads and don't land there to continue your flight.

**Current behaviour**: You land and lift of again

**Expected behaviour**: Don't land in middle of the way. in this video you can see someone flying from IF to STV, and when flies above sw, he doesn't land, but just flies over. https://youtu.be/fmDi3ydg-A8?t=156

**Server Revision**: 2574

**Comment by Brasso** [comment]
Think it looks correct on NW right now. https://www.youtube.com/watch?v=0vp47RfziXQ

**Comment by karabitaz** [comment]
i just checked again and in fact it does, i remember flying to loch modan from sw, and gryphon landed in searing gorge. will check that flight path specifically.
