### ISSUE TITLE
[Item][Engineering] Cluster Launcher or Large Rocket Cluster

### ISSUE THREAD

**Issue by Tottori97** [Atlantiss/NetherwingBugtracker#3814]
https://www.wowhead.com/item=21570/cluster-launcher

**Description**: Cluster Launcher does not respond to any of the Large Red/Blue/Green Rocket Clusters thrown into it, might also be an issue with the rockets and not the Cluster Launcher itself. When you click the rockets they get thrown into a random direction into the ground, and produce no firework effect. 

**Current behaviour**: Rockets fly off into a random direction, fall on the ground, and produce no effect.

**Expected behaviour**: Rockets should drop into the Cluster Launcher and fire off, producing a firework effect.

**Server Revision**: 2574

**Comment by Godmatik** [comment]
Fixed earlier this year - closing.
