### ISSUE TITLE
[Spell][Force of Nature] Treants do not engage dueling target until player engages

### ISSUE THREAD

**Issue by Jseay1313** [Atlantiss/NetherwingBugtracker#3818]
**Description**: Treants do not engage the target you are dueling until you engage them, despite potentially being summoned directly ontop of the hostile player

**Current behaviour**: Treants do not engage target dueling until engaged

**Expected behaviour**:  Treants should engage hostile player based on range to target and not whether the player engages or not

**Server Revision**: 2585

**Comment by The14me** [comment]
rev 3460. still an issue.

**Comment by Wolffenstein** [comment]
Fixed in rev 3471.
