### ISSUE TITLE
Gladiator's Felweave/Dreadweave Handguards/Gauntlets

### ISSUE THREAD

**Issue by prease** [Atlantiss/NetherwingBugtracker#3819]
[//]: # (Enclose links to things related to the bug using http://wowhead.com or any other TBC database.)
[//]: # (You can use screenshot ingame to visual the issue.)
[//]: # (Write your tickets according to the format:)
[//]: # ([Quest][Azuremyst Isle] Red Snapper - Very Tasty!)
[//]: # ([NPC] Magistrix Erona)
[//]: # ([Spell][Mage] Fireball)
[//]: # ([Npc][Drop] Ghostclaw Lynx)
[//]: # ([Web] Armory doesnt work)
[//]: # (To find server revision type `.server info` command in the game chat.)

**Description**: Equip effect not working as intended

**Current behaviour**: No chance to avoid interruption

**Expected behaviour**: 50% Chance to avoid interruption on damage

**Server Revision**:

**Comment by BamboozleNW** [comment]
Looking into this now.

**Comment by Tereneckla** [comment]
Getting an around 50% chance to avoid interruption.
