### ISSUE TITLE
Blink delay 

### ISSUE THREAD

**Issue by superstar333** [Atlantiss/NetherwingBugtracker#382]
**Description**: 
"Blink" doesnt work like it should
**Current behaviour**:
Theres a delay between the actual spell and the animation
**Expected behaviour**: 
Blink should work instantly without that delay

**Comment by Evolvee** [comment]
10:33
11:03
etc.
https://youtu.be/MFjMHepHFpY

**Comment by Evolvee** [comment]
https://youtu.be/Mh_cLN66zHA
1:58
sorry the above video is copyright striked
