### ISSUE TITLE
[Misc] Chat channels are broken right now

### ISSUE THREAD

**Issue by Brasso** [Atlantiss/NetherwingBugtracker#3822]
[//]: # (Enclose links to things related to the bug using http://wowhead.com or any other TBC database.)
[//]: # (You can use screenshot ingame to visual the issue.)
[//]: # (Write your tickets according to the format:)
[//]: # ([Quest][Azuremyst Isle] Red Snapper - Very Tasty!)
[//]: # ([NPC] Magistrix Erona)
[//]: # ([Spell][Mage] Fireball)
[//]: # ([Npc][Drop] Ghostclaw Lynx)
[//]: # ([Web] Armory doesnt work)
[//]: # (To find server revision type `.server info` command in the game chat.)

**Description**
Chat channels such as general or trade chat does not work in cities and world. You can type in them but players can't see what you're typing. Tried in Shattrath, Terrokar forest and Thunderbluff.

**Server Revision**: 
2585

**Comment by gaypala** [comment]
very nice........

**Comment by Wolffenstein** [comment]
Fixed in rev 2589.
