### ISSUE TITLE
Slice and Dice removes Stealth

### ISSUE THREAD

**Issue by Dusky1** [Atlantiss/NetherwingBugtracker#3824]
If you cast Slice and Dice into Stealth very fast, your stealth is removed.

You need to do it very fast. spam macro:

/cast Slice and Dice
/cast !Stealth

**Comment by Evolvee** [comment]
it should remove stealth

**Comment by Dusky1** [comment]
yeah but if you cast SND while in stealth. Now u cast SND out of stealth and if you stealth fast enough it will remove your stealth cuz the SND is delayed

**Comment by Kantrul** [comment]
POG

**Comment by Evolvee** [comment]
🤦‍♂️

**Comment by Evolvee** [comment]
@wtRCH ?

**Comment by devo6969** [comment]
I tried using the macro but you can't even stealth till out of combat and your combo points are gone. If you apply SND, then stealth once out of combat (with SND still up) it doesn't break stealth -As intended-
