### ISSUE TITLE
[Spell][Warlock] Devour Magic

### ISSUE THREAD

**Issue by nallac** [Atlantiss/NetherwingBugtracker#3826]
[//]: # (Enclose links to things related to the bug using http://wowhead.com or any other TBC database.)
[//]: # (You can use screenshot ingame to visual the issue.)
[//]: # (Write your tickets according to the format:)
[//]: # ([Quest][Azuremyst Isle] Red Snapper - Very Tasty!)
[//]: # ([NPC] Magistrix Erona)
[//]: # ([Spell][Mage] Fireball)
[//]: # ([Npc][Drop] Ghostclaw Lynx)
[//]: # ([Web] Armory doesnt work)
[//]: # (To find server revision type `.server info` command in the game chat.)

**Description**: 
A Warlock's Felhunter pet is able to dispel enemy debuffs in Shattrath, a neutral zone, using Devour Magic.

**Current behaviour**:
A Warlock's Felhunter pet is able to dispel enemy debuffs in Shattrath, a neutral zone, using Devour Magic.

**Expected behaviour**: 
A Warlock's Felhunter pet should not be able to dispel enemy debuffs in Shattrath, a neutral zone, using Devour Magic.

**Server Revision**: 
2585

**Proof**
https://gfycat.com/CautiousAnnualGallowaycow

**Comment by The14me** [comment]
Fixed in rev [2588]
