### ISSUE TITLE
[item] Oil of immolation - Weird cooldown bug

### ISSUE THREAD

**Issue by Anselm123** [Atlantiss/NetherwingBugtracker#3827]
**Description**: Weird bug with oil of immolation not being able to be used when a potion is on cooldown

**Current behaviour**: When you have a potion on cooldown it is not able to be used, however it doesn't have a cooldown affected by potions nor potions affecting the cooldown of the oil.

You get the message "You cannot drink anymore yet"

http://wowwiki.wikia.com/wiki/Oil_of_Immolation

**Expected behaviour**: Should be able to be used during a potion cooldown.

**Comment by Anselm123** [comment]
Still happening btw

**Comment by Manaci** [comment]
Fixed
