### ISSUE TITLE
Hellfire Ramparts - invisible wall isn't working

### ISSUE THREAD

**Issue by Tholinx** [Atlantiss/NetherwingBugtracker#3828]
[//]: # (Enclose links to things related to the bug using http://wowhead.com or any other TBC database.)
[//]: # (You can use screenshot ingame to visual the issue.)
[//]: # (Write your tickets according to the format:)
[//]: # ([Quest][Azuremyst Isle] Red Snapper - Very Tasty!)
[//]: # ([NPC] Magistrix Erona)
[//]: # ([Spell][Mage] Fireball)
[//]: # ([Npc][Drop] Ghostclaw Lynx)
[//]: # ([Web] Armory doesnt work)
[//]: # (To find server revision type `.server info` command in the game chat.)

**Description**:  I can jump down from ramparts. https://www.youtube.com/watch?v=SWy2CKL2pt8

**Current behaviour**: I can jump down from ramparts.

**Expected behaviour**: I should not be able to jump down.

**Server Revision**:  2590

**Comment by Brasso** [comment]
Reported earlier here #2011 . No invisible wall is blizzlike, but you should be transported out of the instance, that is bugged.

**Comment by The14me** [comment]
Duplicate #2011
