### ISSUE TITLE
[Spell] [NPC] Summon Imp, Summon Voidwalker...

### ISSUE THREAD

**Issue by BlessedByTheSin** [Atlantiss/NetherwingBugtracker#383]
[//]: # (Enclose links to things related to the bug using http://wowhead.com or any other TBC database.)
[//]: # (You can use screenshot ingame to visual the issue.)
[//]: # (Write your tickets according to the format:)
[//]: # ([Quest][Azuremyst Isle] Red Snapper - Very Tasty!)
[//]: # ([NPC] Magistrix Erona)
[//]: # ([Spell][Mage] Fireball)
[//]: # ([Npc][Drop] Ghostclaw Lynx)
[//]: # ([Web] Armory doesnt work)

**Description**: 
Really weird behavior of AI (pets) upon casting certain spells.
Tested only with: **Life Tap** and **Demon Skin**
**Entry: 416, SpawnId - (Entry: 416, Id: 0), GUIDLow: 542**
**Entry: 1860, SpawnId - (Entry: 1860, Id: 0), GUIDLow: 576**

**Current behaviour**:
https://imgur.com/a/Mix2Oea
https://imgur.com/a/L1Wh91S

**Expected behaviour**: 
/shrug

**Server Revision**: 
2040

**Comment by Arnamik12** [comment]
yeah i noticed this as well, its like they are trying to defend you since you take damage from life tap so they target who damaged you, yourself :)
