### ISSUE TITLE
Grey/white item roll error (Major bug, we cant gear up)

### ISSUE THREAD

**Issue by frenkzenith** [Atlantiss/NetherwingBugtracker#3831]
You cant loot grey/white item when in group because of this message

![wowscrnshot_010419_173104](https://user-images.githubusercontent.com/46387122/50714787-27077280-1048-11e9-9ec5-f9bd98f8ab76.jpg)

**Comment by frenkzenith** [comment]
This happen alot

**Comment by Tixlenra** [comment]
Yeah I've noticed this a lot too, I think it's because that's not your loot, it's a member of your parties, you can just see it when you shouldn't be able to. Correct me if I'm wrong though, because I'm no dev.

**Comment by Drayo** [comment]
@Tixlenra you are correct, it's working fine but you should not be able to see the loot if you are not eligible.

**Comment by The14me** [comment]
It's fixed with laters loot rework.
Rev 3460.
