### ISSUE TITLE
Young Wolf Infinite Leash

### ISSUE THREAD

**Issue by Nesmie** [Atlantiss/NetherwingBugtracker#3834]
[//]: # (Enclose links to things related to the bug using http://wowhead.com or any other TBC database.)
[//]: # (You can use screenshot ingame to visual the issue.)
[//]: # (Write your tickets according to the format:)
[//]: # ([Quest][Azuremyst Isle] Red Snapper - Very Tasty!)
[//]: # ([NPC] Magistrix Erona)
[//]: # ([Spell][Mage] Fireball)
[//]: # ([Npc][Drop] Ghostclaw Lynx)
[//]: # ([Web] Armory doesnt work)
[//]: # (To find server revision type `.server info` command in the game chat.)

**Description**: Young Wolf in northshire had infinite leash. I Had smited him, but someone else had tagged it first due to latency/high population and I decided not to waste mana killing it so I just ran away but it never stopped chasing me. 

**Current behaviour**: Followed me from the "o" in northshire, all the way past the river. 

**Expected behaviour**: It would leash back to its spawn area much earlier. 

**Server Revision**:

**Comment by The14me** [comment]
Any Wolf there or ?

**Comment by Manaci** [comment]
Fixed
