### ISSUE TITLE
[Spell][Rogue][Backstab] able to 'front-stab' enemies

### ISSUE THREAD

**Issue by Tixlenra** [Atlantiss/NetherwingBugtracker#3836]
[//]: # (Enclose links to things related to the bug using http://wowhead.com or any other TBC database.)
[//]: # (You can use screenshot ingame to visual the issue.)
[//]: # (Write your tickets according to the format:)
[//]: # ([Quest][Azuremyst Isle] Red Snapper - Very Tasty!)
[//]: # ([NPC] Magistrix Erona)
[//]: # ([Spell][Mage] Fireball)
[//]: # ([Npc][Drop] Ghostclaw Lynx)
[//]: # ([Web] Armory doesnt work)
[//]: # (To find server revision type `.server info` command in the game chat.)

**Description**: Able to 'front-stab' enemies with backstab.

**Current behaviour**: Can front-stab

**Expected behaviour**:  Shouldn't be able to backstab when you have aggro.

**Server Revision**:

**Comment by RealZwox** [comment]
Same for Shred for Druids

**Comment by nikolay510** [comment]
You can do it on every other private server except warmane (because of internal 500ms spell delay). It's latency issue, you can't fix it. Higher ping - easier frontstabs.

**Comment by The14me** [comment]
rev.3460 cant reproduce it.
