### ISSUE TITLE
[NPC] Springpaw Stalker 'stealth walks'

### ISSUE THREAD

**Issue by Tixlenra** [Atlantiss/NetherwingBugtracker#3837]
[//]: # (Enclose links to things related to the bug using http://wowhead.com or any other TBC database.)
[//]: # (You can use screenshot ingame to visual the issue.)
[//]: # (Write your tickets according to the format:)
[//]: # ([Quest][Azuremyst Isle] Red Snapper - Very Tasty!)
[//]: # ([NPC] Magistrix Erona)
[//]: # ([Spell][Mage] Fireball)
[//]: # ([Npc][Drop] Ghostclaw Lynx)
[//]: # ([Web] Armory doesnt work)
[//]: # (To find server revision type `.server info` command in the game chat.)

**Description**: Springpaw Stalker 'stealth walks'

**Current behaviour**: Springpaw Stalker 'stealth walks'

**Expected behaviour**: Should run normally when they exit stealth.

**Server Revision**:

**Comment by Evolvee** [comment]
should be fixed in next revision, if not reopen pls
