### ISSUE TITLE
[Shaman][Spell] Lightning shield does not have internal CD

### ISSUE THREAD

**Issue by pesky89** [Atlantiss/NetherwingBugtracker#3840]
**Description**:  
Shaman's spell does not have internal cooldown. it damages enemy on every hit.  
**Current behaviour**:  
Shaman's spell does not have internal cooldown. it damages enemy on every hit.  
**Expected behaviour**:  
It should have an internal cooldown of 3s
**Server Revision**:  
2594

**Comment by Evolvee** [comment]
should be already fixed, retest pls
