### ISSUE TITLE
Guild ranks change name into guild name after server restart/crash

### ISSUE THREAD

**Issue by dmrljes** [Atlantiss/NetherwingBugtracker#3843]
After every crash or restar of the server, guild ranks change into the guild name, for example rank SOCIAL changes name in GUILD. Photo: 
![image](https://user-images.githubusercontent.com/23341857/50723141-f2dc9200-10d9-11e9-88a4-df34a4a65f60.png)

**Comment by Tholinx** [comment]
My whole guild disappeared after crash earlier today around 2 AM ... my silvers are gone also

**Comment by Chickengrease** [comment]
Our rank names also default to guild name. Never seen this type of bug before lul.

**Comment by RealZwox** [comment]
Can confirm after every crash rank names get resetet.

**Comment by Neophrone** [comment]
Btw do u know the meaning of u'r guild name? 😁

**Comment by dmrljes** [comment]
It's not Russian related, it's not dick.

**Comment by Zsorrov** [comment]
Confirmed. Happens in my guild as well.

**Comment by yihu0259** [comment]
Confirmed, the same issue in my guild. The ranking name is the same as the guild name.

**Comment by RobGFour** [comment]
Confirmed. happens every time

**Comment by RobGFour** [comment]
Not fixed...after last crash they reverted back to guild names

**Comment by yihu0259** [comment]
> Fixed in rev 2611. You will need to rename them again.

The issue is still there after restarting the server, ranking name the same as the guild name and blank guild log
