### ISSUE TITLE
If you're in a party and you log out and back in, you can't see party members

### ISSUE THREAD

**Issue by Tixlenra** [Atlantiss/NetherwingBugtracker#3844]
[//]: # (Enclose links to things related to the bug using http://wowhead.com or any other TBC database.)
[//]: # (You can use screenshot ingame to visual the issue.)
[//]: # (Write your tickets according to the format:)
[//]: # ([Quest][Azuremyst Isle] Red Snapper - Very Tasty!)
[//]: # ([NPC] Magistrix Erona)
[//]: # ([Spell][Mage] Fireball)
[//]: # ([Npc][Drop] Ghostclaw Lynx)
[//]: # ([Web] Armory doesnt work)
[//]: # (To find server revision type `.server info` command in the game chat.)

**Description**: If you're in a party and you log out and back in, you can't see party members. I had to get my friend to disband the group because I was still technically in it, but on my screen I wasn't.

**Current behaviour**: If you're in a party and you log out and back in, you can't see party members but they can see you

**Expected behaviour**: Should be able to see party members.

**Server Revision**:

**Comment by Suzaru** [comment]
This is extremly annoying and potentially dangerous.

We were in Deadmines, with me being the Groupleader. I had a disconnect and when i came back online, i wasn't in the party anymore, at least for me. My mates still saw me in the party, and with me being leader (albeit I'm not in the party anymore, at least for me) we couldn't do nothing anymore and had to reset :(.

**Comment by Shnoofeen** [comment]
This happens on changing zones occasionally also. 

But I can confirm 100% that if you log out or DC while in party the party will no longer display for you, although you are still in a party & can see party chat but are unable to chat as it errors with 'You are not in a party'

**Comment by The14me** [comment]
SInce other issue is fixed, that must be ok too.
