### ISSUE TITLE
[NPC] [Gamon] non dynamic respawn 

### ISSUE THREAD

**Issue by AndrewNB41191** [Atlantiss/NetherwingBugtracker#3845]
[//]: # (Enclose links to things related to the bug using http://wowhead.com or any other TBC database.)
[//]: # (You can use screenshot ingame to visual the issue.)
[//]: # (Write your tickets according to the format:)
[//]: # ([Quest][Azuremyst Isle] Red Snapper - Very Tasty!)
[//]: # ([NPC] Magistrix Erona)
[//]: # ([Spell][Mage] Fireball)
[//]: # ([Npc][Drop] Ghostclaw Lynx)
[//]: # ([Web] Armory doesnt work)
[//]: # (To find server revision type `.server info` command in the game chat.)

**Description**: respawn takes forever, atypical to every other spawn

**Current behaviour**: non dynamic respawn on gamon in orgimar for rogue quest 

**Expected behaviour**: dynamic respawn

**Server Revision**: 2594

**Comment by Evolvee** [comment]
gamon is single npc, how could it be dynamic?

**Comment by AndrewNB41191** [comment]
i guess i dont. i thought dynamic respawns were mobs that respawned more frequently based on server pop. he seemed to have a very long respawn, but if thats normal/intended disregard.

**Comment by Evolvee** [comment]
no its based on availability, server pop has nothing to do with dynamic respawn

it respawns the same if there are 1 or 5k ppl online if both of them kill the same amount of mobs in the same time

**Comment by Evolvee** [comment]
it just requires lower respawn timer then, but u cant make dynamic from 1 npc

**Comment by xmesaj2** [comment]
leave gamon alone 😢

**Comment by AndrewNB41191** [comment]
cool, thanks for explaining!
