### ISSUE TITLE
Blocked Hamstring doesn't apply slow

### ISSUE THREAD

**Issue by femdead** [Atlantiss/NetherwingBugtracker#3847]
it should still apply a debuff even if damage is reduced to 0

**Comment by Tenoutoften** [comment]
Proof?

**Comment by Evolvee** [comment]
x doubt

**Comment by torrenzGH** [comment]
block stops ms, poisons, crits, wf etc
hamstring would be a very weird exception

**Comment by weirdbiz** [comment]
https://www.wowhead.com/spell=1715/hamstring#comments

According to comments subtree, in 2.4.3 this ability was blockable completely.

**Comment by Evolvee** [comment]
if u find proof, reopen it

**Comment by femdead** [comment]
interesting, other servers all had it wrong i guess
