### ISSUE TITLE
Duping content of Nolkai's Box

### ISSUE THREAD

**Issue by knugen1234** [Atlantiss/NetherwingBugtracker#3849]
[//]: # (Enclose links to things related to the bug using http://wowhead.com or any other TBC database.)
[//]: # (You can use screenshot ingame to visual the issue.)
[//]: # (Write your tickets according to the format:)
[//]: # ([Quest][Azuremyst Isle] Red Snapper - Very Tasty!)
[//]: # ([NPC] Magistrix Erona)
[//]: # ([Spell][Mage] Fireball)
[//]: # ([Npc][Drop] Ghostclaw Lynx)
[//]: # ([Web] Armory doesnt work)
[//]: # (To find server revision type `.server info` command in the game chat.)

**Description**:
Nolkai's Box is a quest reward from the quest 'Nolkai's Words', its a container and will give you some silver, a green off-hand item, a 8-slot bag and some gray trash item.
When i did this quest earlier i only looted the silver and the 8-slot bag and kept the other two items inside the box to reserve bag-space. At some point (probably during a server reset/crash?) it seems like the content of this container/quest reward was reset and i could loot the silver and the same 8-slot bag again.

**Current behaviour**:
Content of Nolkai's Box seems to reset (if you keep it and don't loot all the items from the container) during server crashes/resets (not really sure).

**Expected behaviour**: 
The container should not 'reset' but remain with whatever items you have not yet looted from it

**Server Revision**: 2594

**Comment by Manaci** [comment]
Dead issue
