### ISSUE TITLE
[NPC]Shadowpine Hexxer (16346)/[Spell]Dispel Magic (17201)

### ISSUE THREAD

**Issue by Kentamentiu** [Atlantiss/NetherwingBugtracker#385]
[//]: # (Enclose links to things related to the bug using http://wowhead.com or any other TBC database.)
[//]: # (You can use screenshot ingame to visual the issue.)
[//]: # (Write your tickets according to the format:)
[//]: # ([Quest][Azuremyst Isle] Red Snapper - Very Tasty!)
[//]: # ([NPC] Magistrix Erona)
[//]: # ([Spell][Mage] Fireball)
[//]: # ([Npc][Drop] Ghostclaw Lynx)
[//]: # ([Web] Armory doesnt work)

**Description**: 
When you root Shadowpine Hexxer with Frost Nova he tries to dispel that with Dispel Magic. If there is another debuf already on the mob, like frostbolt snare, it dispells the earlier applied debuff and he remains rooted.

**Current behaviour**:
Mob fails to dispell his root

**Expected behaviour**: 
He frees himself and continues the fight

**Server Revision**: 
2040

**Comment by Easyfraggy** [comment]
There's no such thing as a dispel order, it is entirely random. If you have proof otherwise, reopen.

**Comment by Evolvee** [comment]
dispel is RNG based, there is no such thing as dispel order right now

if you have a proof of it though, i would be more than grateful if you could provide it ^^

**Comment by Evolvee** [comment]
lets keep it open for some time easy, i will close it if there wont be any new info
