### ISSUE TITLE
You cant send message of this type until you reach level 10 (Spam bug)

### ISSUE THREAD

**Issue by frenkzenith** [Atlantiss/NetherwingBugtracker#3850]
I get this message even when im just walking doing nothing in the chat.

I get this message when killing a mobs.

It seem it come from addons but still need to be fix, was not doing that on other TBC server.

![wowscrnshot_010519_103605](https://user-images.githubusercontent.com/46387122/50726081-ece4b200-10d5-11e9-808c-3257f1304b7d.jpg)

**Comment by Shanghi** [comment]
To whoever can fix this: you need to allow all types of addon messages without a level restriction

**Comment by Evolvee** [comment]
addon related

**Comment by Manaci** [comment]
Fixed
