### ISSUE TITLE
Quest cant turn in after completion

### ISSUE THREAD

**Issue by rangobob** [Atlantiss/NetherwingBugtracker#3851]
[//]: # (Enclose links to things related to the bug using http://wowhead.com or any other TBC database.)
[//]: # (You can use screenshot ingame to visual the issue.)
[//]: # (Write your tickets according to the format:)
[//]: # ([Quest][Azuremyst Isle] Red Snapper - Very Tasty!)
[//]: # ([NPC] Magistrix Erona)
[//]: # ([Spell][Mage] Fireball)
[//]: # ([Npc][Drop] Ghostclaw Lynx)
[//]: # ([Web] Armory doesnt work)
[//]: # (To find server revision type `.server info` command in the game chat.)

**Description**: 
Completed Paladin Horde Quest "The First Trial"
**Current behaviour**:
Can not turn in quest at Quest NPC Knight-Lord Bloodvalor
**Expected behaviour**: 
Being able to turn in quest.
**Server Revision**: 2594

**Comment by Evolvee** [comment]
Which was the 1st NPC you picked it at?
