### ISSUE TITLE
[Quest][Coldridge Valley] The Troll's Cave

### ISSUE THREAD

**Issue by Polybolos** [Atlantiss/NetherwingBugtracker#3853]
[//]: # (Enclose links to things related to the bug using http://wowhead.com or any other TBC database.)
[//]: # (You can use screenshot ingame to visual the issue.)
[//]: # (Write your tickets according to the format:)
[//]: # ([Quest][Azuremyst Isle] Red Snapper - Very Tasty!)
[//]: # ([NPC] Magistrix Erona)
[//]: # ([Spell][Mage] Fireball)
[//]: # ([Npc][Drop] Ghostclaw Lynx)
[//]: # ([Web] Armory doesnt work)
[//]: # (To find server revision type `.server info` command in the game chat.)

**Description**: 
Quest The Troll's Cave doesn't give reputation with Ironforge. (checked on dwarf character)
**Current behaviour**:
Only gives +250 reputation with Gnomeregan exiles.
**Expected behaviour**: 
Should give +250 reputation both with Ironforge and Gnomeregan exiles.
proof: http://web.archive.org/web/20080207081420/http://thottbot.com:80/q182
**Server Revision**: 
2594

**Comment by wtRCH** [comment]
@Shanghi

**Comment by Shanghi** [comment]
This should be fixed now.
