### ISSUE TITLE
[NPC] [Respawn] Kolkar (Barrens)

### ISSUE THREAD

**Issue by naekobest** [Atlantiss/NetherwingBugtracker#3854]
We would basically just need higher respawns. All areas are still heavy contested and its impossible to find Kolkars. Same with the named questmobs

**Comment by wtRCH** [comment]
Kolkars and Raptors are spreaded in the whole zone. That's why they don't respawn so fast. If they aren't in the dynamic respawn already they will be added. Otherwise we won't do anything about it.

@aresbrutus
