### ISSUE TITLE
[Quest][Coldridge Valley] The Stolen Journal

### ISSUE THREAD

**Issue by Polybolos** [Atlantiss/NetherwingBugtracker#3855]
[//]: # (Enclose links to things related to the bug using http://wowhead.com or any other TBC database.)
[//]: # (You can use screenshot ingame to visual the issue.)
[//]: # (Write your tickets according to the format:)
[//]: # ([Quest][Azuremyst Isle] Red Snapper - Very Tasty!)
[//]: # ([NPC] Magistrix Erona)
[//]: # ([Spell][Mage] Fireball)
[//]: # ([Npc][Drop] Ghostclaw Lynx)
[//]: # ([Web] Armory doesnt work)
[//]: # (To find server revision type `.server info` command in the game chat.)

**Description**: 
Quest The Stolen Journal doesn't give reputation with Ironforge. (checked on dwarf character)
**Current behaviour**:
Only gives +500 reputation with Gnomeregan exiles.
**Expected behaviour**: 
Should give +500 reputation with Gnomeregan exiles and +250 with Ironforge
proof: http://wowwiki.wikia.com/wiki/Quest:The_Stolen_Journal?oldid=819993
(august 2007 version of page)
**Server Revision**: 
2594

**Comment by wtRCH** [comment]
@Shanghi

**Comment by Shanghi** [comment]
This should be fixed now.
