### ISSUE TITLE
[Core] Weapon skill up 100% by killing critters

### ISSUE THREAD

**Issue by pesky89** [Atlantiss/NetherwingBugtracker#3856]
[//]: # (Enclose links to things related to the bug using http://wowhead.com or any other TBC database.)
[//]: # (You can use screenshot ingame to visual the issue.)
[//]: # (Write your tickets according to the format:)
[//]: # ([Quest][Azuremyst Isle] Red Snapper - Very Tasty!)
[//]: # ([NPC] Magistrix Erona)
[//]: # ([Spell][Mage] Fireball)
[//]: # ([Npc][Drop] Ghostclaw Lynx)
[//]: # ([Web] Armory doesnt work)
[//]: # (To find server revision type `.server info` command in the game chat.)

**Description**: 
Weapon skill is 100% level up chance when you kill critters  
**Current behaviour**:
Weapon skill is 100% level up chance when you kill critters. this can be abused to level up weapon.  
I killed gazzelas in the Barrens.
**Expected behaviour**: 
Weapon skill should not level up 100% chance by killing critters.   
**Server Revision**:

**Comment by wtRCH** [comment]
I confirm that, but I don't know if it should be like that or not.

**Comment by pesky89** [comment]
i mean, in this situation, it's better to farm critters than mobs to level up, since for critters 1 swing = 1 level up

**Comment by Zarant** [comment]
I'm having the opposite impression, low level mobs never give weapon skill consistently, even green level mobs, leveling from 1 to 200+ is a pain in the butt because if the mob is just a few levels below you will rarely get a skill point.

**Comment by Argonn** [comment]
Not just critter, works on any neutral (yellow) creature. (boars outside of Orgrimmar give 100% skillup)

**Comment by Tereneckla** [comment]
#362
