### ISSUE TITLE
[Quest] [Coldridge Valley] Quests and reputation with Alliance capitals

### ISSUE THREAD

**Issue by Polybolos** [Atlantiss/NetherwingBugtracker#3857]
[//]: # (Enclose links to things related to the bug using http://wowhead.com or any other TBC database.)
[//]: # (You can use screenshot ingame to visual the issue.)
[//]: # (Write your tickets according to the format:)
[//]: # ([Quest][Azuremyst Isle] Red Snapper - Very Tasty!)
[//]: # ([NPC] Magistrix Erona)
[//]: # ([Spell][Mage] Fireball)
[//]: # ([Npc][Drop] Ghostclaw Lynx)
[//]: # ([Web] Armory doesnt work)
[//]: # (To find server revision type `.server info` command in the game chat.)

**Description**: 
Quests that give reputation with one Capital also give 1/4 of that reputation with all other faction capitals. That works as intended.
But most quests in Coldridge Valley give repu with 2 Alliance factions: with Ironforge and Gnomeregan exiles. These quests did not add 1/4 of that reputation to other Alliance capitals.

To clarify there are 2 examples:
1: Priest's quest "Hallowed Rune" gave me +75 Ironforge repu, that resulted in following reputation changes:
Darnassus: +18
Exodar: +18
Gnomeregan exiles: +18
Ironforge: +75
Stormwind: +18

2: "Scalding Mornbrew Delivery" quest gave me +75 Ironforge and +75 Gnomeregan exiles reputation. What i got:
Darnassus: +**0**
Exodar: +**0**
Gnomeregan exiles: +75
Ironforge: +75
Stormwind: +**0**

Currently I checked only Coldridge quests. But that may be more global problem affecting all quests that give repu with more than one capital, not sure about that.

**Current behaviour**:
Quests which give reputation with 2 races do not add 1/4 of that reputation to other Alliance capitals. (Checked Coldridge Valley only)
**Expected behaviour**: 
They should add 1/4 of that reputation value to other Alliance capitals. Just like all other quests do.
**Server Revision**: 
2594

**Comment by Godmatik** [comment]
Fixed a few months ago - closing
