### ISSUE TITLE
Constant Server Disconnect

### ISSUE THREAD

**Issue by AngryBrickedVITA** [Atlantiss/NetherwingBugtracker#3859]
Keep disconnecting every 1-3 minutes after logging in the problem is when I am disconnecting it doesnt kick me out back to the login screen it just gets stuck in disconnecting phase and does not DC me, I have tried rebooting my router, flushing my DNS and using a different Network Adapter, all with the same end result. I did notice that using the play.netherwing.eu REALMLIST was abit more stable in terms of the disconnection frequency, causing it to occur at a lesser rate but the issue still persisted. I ve deleted cache after each DC aswell, with no change to the issue. I am forced to close the client and reopen another when this occurs and it is very frustrating a fix or help towards a fix would be most appreciated.

**Comment by Manaci** [comment]
Fixed
