### ISSUE TITLE
[NPC][Spell][Bloodmyst Isle] Bristlelimb Shaman

### ISSUE THREAD

**Issue by Eidous** [Atlantiss/NetherwingBugtracker#386]
[//]: # (Enclose links to things related to the bug using http://wowhead.com or any other TBC database.)
[//]: # (You can use screenshot ingame to visual the issue.)
[//]: # (Write your tickets according to the format:)
[//]: # ([Quest][Azuremyst Isle] Red Snapper - Very Tasty!)
[//]: # ([NPC] Magistrix Erona)
[//]: # ([Spell][Mage] Fireball)
[//]: # ([Npc][Drop] Ghostclaw Lynx)
[//]: # ([Web] Armory doesnt work)

**Description**: 
The searing totem dropped by the Bristlelimb Shaman doesn't do anything.

**Current behaviour**:
The searing totem doesn't cast any spells.

**Expected behaviour**: 
The searing totem should hit a close target every x seconds for some fire damage.

**Server Revision**: 
2040

**Comment by The14me** [comment]
https://github.com/Atlantiss/AtlantissTBCBT/issues/4193

**Comment by Bildo** [comment]
fixed in rev 2413
