### ISSUE TITLE
[Quest][Bloodmyst Isle] Saving Princess Stillpine

### ISSUE THREAD

**Issue by weirdbiz** [Atlantiss/NetherwingBugtracker#3860]
[//]: # (Enclose links to things related to the bug using http://wowhead.com or any other TBC database.)
[//]: # (You can use screenshot ingame to visual the issue.)
[//]: # (Write your tickets according to the format:)
[//]: # ([Quest][Azuremyst Isle] Red Snapper - Very Tasty!)
[//]: # ([NPC] Magistrix Erona)
[//]: # ([Spell][Mage] Fireball)
[//]: # ([Npc][Drop] Ghostclaw Lynx)
[//]: # ([Web] Armory doesnt work)
[//]: # (To find server revision type `.server info` command in the game chat.)

**Description**: 
This quest should be acquired in location where NPC Princess Stillpine is in cage: 68.2, 81.2
But under specific events can be acquired in other locations, where NPC appears.
**Current behaviour**:
Currently, this quest can be acquired from same NPC located in Blood Watch (54,56) under specific circumstances: some other player did specific event from other quest, probably, which triggered multiple NPCs to appear there, among which was Princess Stillpine, which gave me this quest.
**Expected behaviour**: 
Quest can be acquired only in location where NPC Princess Stillpine is in cage: 68.2, 81.2.
https://www.wowhead.com/quest=9667/saving-princess-stillpine
**Server Revision**: 
2594

**Comment by wtRCH** [comment]
@Evolvee

**Comment by Evolvee** [comment]
its wolfs fault 🤣 his quest script... im not touching it

**Comment by Tereneckla** [comment]
You can take the quest from the Princess spawned by the "Ending Their World" event. (Id 2)
Should only be available from the caged one (Id 1)

**Comment by Wolffenstein** [comment]
Fixed in rev 3469.
