### ISSUE TITLE
[Quest][Bloodmyst Isle] Catch and Release

### ISSUE THREAD

**Issue by Brasso** [Atlantiss/NetherwingBugtracker#3861]
[//]: # (Enclose links to things related to the bug using http://wowhead.com or any other TBC database.)
[//]: # (You can use screenshot ingame to visual the issue.)
[//]: # (Write your tickets according to the format:)
[//]: # ([Quest][Azuremyst Isle] Red Snapper - Very Tasty!)
[//]: # ([NPC] Magistrix Erona)
[//]: # ([Spell][Mage] Fireball)
[//]: # ([Npc][Drop] Ghostclaw Lynx)
[//]: # ([Web] Armory doesnt work)
[//]: # (To find server revision type `.server info` command in the game chat.)

**Description**: 
If you are multiple people in a group and tag a scout, you get more than 1 tag, e.g 3/6 for 1 tag if you are 3 people in the group.

**Expected behaviour**: 
Should only reward one, but still shared within the group.
**Server Revision**: 
2594

**Comment by Tereneckla** [comment]
Killing them also gives an addition quest credit.

**Comment by Wolffenstein** [comment]
Fixed in rev 3378.
