### ISSUE TITLE
Ranged Weapon Skill up

### ISSUE THREAD

**Issue by Erodraeda** [Atlantiss/NetherwingBugtracker#3863]
[//]: # (Enclose links to things related to the bug using http://wowhead.com or any other TBC database.)
[//]: # (You can use screenshot ingame to visual the issue.)
[//]: # (Write your tickets according to the format:)
[//]: # ([Quest][Azuremyst Isle] Red Snapper - Very Tasty!)
[//]: # ([NPC] Magistrix Erona)
[//]: # ([Spell][Mage] Fireball)
[//]: # ([Npc][Drop] Ghostclaw Lynx)
[//]: # ([Web] Armory doesnt work)
[//]: # (To find server revision type `.server info` command in the game chat.)

**Description**: 
I'm leveling, got a bow, skill level at 1, but I'm getting doubled skill ups.
**Current behaviour**:
I'm currently getting 2 skill ups - one when I shoot, another when the target is hit.
**Expected behaviour**: 
Should only get one skill up per shot, when the shot is shot (lol)
**Server Revision**: 2594

**Comment by killablink** [comment]
Same thing with wands

**Comment by Brasso** [comment]
There are definitely multiple issues with weapon skill ups right now. If you shoot an enemy with a range weapon, then run into melee range and hit the mob with a melee weapon you expect a melee weapon skill up, but instead you get ranged weapon skill up.

https://www.twitch.tv/videos/360040951

**Comment by sadfx** [comment]
[https://i.imgur.com/bcabdNC.png]

this has timestamps showing the bug :28 crossbow skill-up on melee miss

**Comment by Drayo** [comment]
I tried Wands/Bows (even one with an on hit effect) and Thrown Weapons. I never get more than one skillup. 

Waving in and out of melee always grants the skillup for the expected weaponskill too.

Can probably be closed.
