### ISSUE TITLE
[Core] Fall Damage / Flightpath

### ISSUE THREAD

**Issue by Kidtoucher** [Atlantiss/NetherwingBugtracker#3865]
**Description**: 
I was flying from Auberdine to Rutheran Village and the server DCd. When i logged in it dropped me off, but I died due to fall damage

**Current behaviour**:
I was flying from Auberdine to Rutheran Village and the server DCd. When i logged in it dropped me off, but I died due to fall damage

**Expected behaviour**: 
Should not die

![safejes](https://user-images.githubusercontent.com/45120987/50729502-62cf3480-113b-11e9-8234-14e8e73aece8.png)

**Comment by The14me** [comment]
It was fixed with latest update about fly mounts.
