### ISSUE TITLE
[Mining]Cooper vein

### ISSUE THREAD

**Issue by Matija5** [Atlantiss/NetherwingBugtracker#3867]
[//]: # (Enclose links to things related to the bug using http://wowhead.com or any other TBC database.)
[//]: # (You can use screenshot ingame to visual the issue.)
[//]: # (Write your tickets according to the format:)
[//]: # ([Quest][Azuremyst Isle] Red Snapper - Very Tasty!)
[//]: # ([NPC] Magistrix Erona)
[//]: # ([Spell][Mage] Fireball)
[//]: # ([Npc][Drop] Ghostclaw Lynx)
[//]: # ([Web] Armory doesnt work)
[//]: # (To find server revision type `.server info` command in the game chat.)

**Description**:  Some of the veins are spawned at the same spot and when u mine then you are able to do it couple of times. For instance I ran into cooper vein in dun morogh that always spawns with extra two veins at same spot so u can mine it 3 times.

**Current behaviour**:
Edit: https://www.youtube.com/watch?v=w9b4vUxFKbw&feature=youtu.be

I recorded so you can understand it better
**Expected behaviour**: 

**Server Revision**:

**Comment by Shanghi** [comment]
Do you mean 3 hits in all or 9 hits?
If you mean 3, then that's how it is on TBC where you have to mine it a few times to get everything.
If you mean 9, then that's a terrible problem!

**Comment by Matija5** [comment]
No there are seperate cooper vein but at exact same place

**Comment by dmrljes** [comment]
You can mine one ore several times, it isn't like other expansion where you can mine ore only once.

**Comment by kemotix** [comment]
It's perfectly fine. That's how mining should work in TBC.

**Comment by Shanghi** [comment]
I just saw the video and they're right. That's just how it is on TBC. It's better to be safe than sorry though so thank you for showing the video that makes it clear!
