### ISSUE TITLE
[Mining] Scam copper veins in Ghostlands

### ISSUE THREAD

**Issue by mooviestar** [Atlantiss/NetherwingBugtracker#3869]
[//]: # (Enclose links to things related to the bug using http://wowhead.com or any other TBC database.)
[//]: # (You can use screenshot ingame to visual the issue.)
[//]: # (Write your tickets according to the format:)
[//]: # ([Quest][Azuremyst Isle] Red Snapper - Very Tasty!)
[//]: # ([NPC] Magistrix Erona)
[//]: # ([Spell][Mage] Fireball)
[//]: # ([Npc][Drop] Ghostclaw Lynx)
[//]: # ([Web] Armory doesnt work)
[//]: # (To find server revision type `.server info` command in the game chat.)

**Description**: 
There is a cave in ghostlands at 27,51 where copper veins cannot be mined
**Current behaviour**:
I ran into this cave expecting to mine copper, several attempts at mining the copper yielded nothing, i was instead ambushed by respawns 
**Expected behaviour**: 
Mining copper veins should result in looted copper
**Server Revision**: 
Give me copper when i mine it

**Comment by monsterguy** [comment]
The nodes seem to be working incorrectly because of the quest - https://www.wowhead.com/quest=9207/underlight-ore-samples

**Comment by Utilbart** [comment]
The exact same thing is probably happening in felwood with herb/mining nodes. They become ghost nodes due to the extra quest items they can drop, preventing the objects from despawning/respawning correctly.

**Comment by Manaci** [comment]
Fixed
