### ISSUE TITLE
Discolored Worg Hearts

### ISSUE THREAD

**Issue by AlteredAli** [Atlantiss/NetherwingBugtracker#387]
[//]: # (Enclose links to things related to the bug using http://wowhead.com or any other TBC database.)
[//]: # (You can use screenshot ingame to visual the issue.)
[//]: # (Write your tickets according to the format:)
[//]: # ([Quest][Azuremyst Isle] Red Snapper - Very Tasty!)
[//]: # ([NPC] Magistrix Erona)
[//]: # ([Spell][Mage] Fireball)
[//]: # ([Npc][Drop] Ghostclaw Lynx)
[//]: # ([Web] Armory doesnt work)

**Description**: 
discolored worg hearts are dropping from Prairie Wolf Alpha's in Mulgore, where they should only be dropping from wolves in silverpine/tirisfal glades.
**Current behaviour**:

**Expected behaviour**: 

**Server Revision**: 
2040

**Comment by aresbrutus** [comment]
https://i.imgur.com/Lge9XPA.jpg 

Confirmed.

Should only be entries:
```
1766
1765
1923
12431
```

https://i.imgur.com/vpttQoc.png

**Comment by Buggyswires** [comment]
They also drop from the wolves in Westfall

**Comment by Arnamik12** [comment]
and the prowlers(118) in elwynn

**Comment by Mentat33** [comment]
And Timber (rare spawn) in Dun Morogh
![timber](https://user-images.githubusercontent.com/43624877/46260628-60af6700-c4b6-11e8-9d40-e86c5e86cf70.png)

**Comment by Shanghi** [comment]
This should be fixed in revision 2152.
