### ISSUE TITLE
[warlock] improved corruption bugged instant cast

### ISSUE THREAD

**Issue by tehelelol** [Atlantiss/NetherwingBugtracker#3870]
[//]: # (Enclose links to things related to the bug using http://wowhead.com or any other TBC database.)
[//]: # (You can use screenshot ingame to visual the issue.)
[//]: # (Write your tickets according to the format:)
[//]: # ([Quest][Azuremyst Isle] Red Snapper - Very Tasty!)
[//]: # ([NPC] Magistrix Erona)
[//]: # ([Spell][Mage] Fireball)
[//]: # ([Npc][Drop] Ghostclaw Lynx)
[//]: # ([Web] Armory doesnt work)
[//]: # (To find server revision type `.server info` command in the game chat.)

**Description**: 
improved corruption bugged instant cast
**Current behaviour**:
need to stand still to cast corruption with 5/5 imp. corruption
**Expected behaviour**: 
5/5 corruption makes it instant cast and should be applyable while moving or jumping
**Server Revision**:

**Comment by Drayo** [comment]
Did it resolve itself for you? Because I can cast it while running just fine now.

**Comment by wtRCH** [comment]
@tehelelol ?

**Comment by wtRCH** [comment]
No response - resolved.
