### ISSUE TITLE
[Movement] Can't swim straight down

### ISSUE THREAD

**Issue by yesthisisnick** [Atlantiss/NetherwingBugtracker#3871]
[//]: # (Enclose links to things related to the bug using http://wowhead.com or any other TBC database.)
[//]: # (You can use screenshot ingame to visual the issue.)
[//]: # (Write your tickets according to the format:)
[//]: # ([Quest][Azuremyst Isle] Red Snapper - Very Tasty!)
[//]: # ([NPC] Magistrix Erona)
[//]: # ([Spell][Mage] Fireball)
[//]: # ([Npc][Drop] Ghostclaw Lynx)
[//]: # ([Web] Armory doesnt work)
[//]: # (To find server revision type `.server info` command in the game chat.)

**Description**: 
When trying to swim straight down with "x" (default key), my toon will begin dropping but shortly after reset to where I started
**Current behaviour**:
See description
**Expected behaviour**: 
Swim straight down
**Server Revision**:

**Comment by Manaci** [comment]
Fixed
