### ISSUE TITLE
[Quest] They're Alive! Maybe...

### ISSUE THREAD

**Issue by Brasso** [Atlantiss/NetherwingBugtracker#3872]
[//]: # (Enclose links to things related to the bug using http://wowhead.com or any other TBC database.)
[//]: # (You can use screenshot ingame to visual the issue.)
[//]: # (Write your tickets according to the format:)
[//]: # ([Quest][Azuremyst Isle] Red Snapper - Very Tasty!)
[//]: # ([NPC] Magistrix Erona)
[//]: # ([Spell][Mage] Fireball)
[//]: # ([Npc][Drop] Ghostclaw Lynx)
[//]: # ([Web] Armory doesnt work)
[//]: # (To find server revision type `.server info` command in the game chat.)

Quest objective is not shared in group.

Rev
2596.

**Comment by wtRCH** [comment]
Fix your issue template. What do you exactly mean? Issue will stay closed untill you edit it @Brasso
