### ISSUE TITLE
[Mail system] Returning mail from alts/banks causes them to disappear

### ISSUE THREAD

**Issue by scarabadookie** [Atlantiss/NetherwingBugtracker#3873]
[//]: # (Enclose links to things related to the bug using http://wowhead.com or any other TBC database.)
[//]: # (You can use screenshot ingame to visual the issue.)
[//]: # (Write your tickets according to the format:)
[//]: # ([Quest][Azuremyst Isle] Red Snapper - Very Tasty!)
[//]: # ([NPC] Magistrix Erona)
[//]: # ([Spell][Mage] Fireball)
[//]: # ([Npc][Drop] Ghostclaw Lynx)
[//]: # ([Web] Armory doesnt work)
[//]: # (To find server revision type `.server info` command in the game chat.)

**Description**: 
Using a level 1 bank alt to store some items while leveling, and returning the mails to the main character once they're needed.

**Current behaviour**:
Returned multiple mails with items a few hours ago, none have arrived, tried again recently and that mail also hasn't arrived. Sending items in a new mail from the same alt to the main works and is instant.

**Expected behaviour**: 
Mail returned with the "Return" button should arrive properly.

**Server Revision**: 
2596

**Comment by scarabadookie** [comment]
Can't edit for some reason, but just adding that both characters are on the same account for clarity.

**Comment by Lithits** [comment]
Have the same issue. Character name Litheals, mail returned from Litbank.

**Comment by Gniddikon** [comment]
This needs to be a high priority issue asap.

**Comment by torrenzGH** [comment]
Stromboli, sent mail to oathbank, returned, got nothing

**Comment by xmesaj2** [comment]
rev 2601, please retest once it goes live

**Comment by wowthings** [comment]
That would explain why I had a returned item from the AH and didn't appear on the bag when I checked later.

**Comment by xmesaj2** [comment]
I will need more specifics, because its all looking fine from my tests. What kind of mails does it happen with? Returning mails with attached items from chars on the same account? Returning to a different account characters? Anything to do with mentioned AH? What items were included?

**Comment by mbzz88** [comment]
Still broken revision 2604.
Returning mail from my bank alt (Jazbank) to my main (Jazara) resulted in the mail simply disappearing.
Both characters are on the same account.
All returned mail had multiple items, mostly Light, Medium and Heavy Leather.
Some mail was returned correctly, that mail contained 2x stacks of Silk Cloth and 2x Cooking recipes, and the other 2x BoE weapons, a 6slot bag and a cooking recipe.
This possibly only happens with certain trade goods?

**Comment by d4rksite** [comment]
Having the same issue, already lost 2 mails.
Wenn sending to my Level 1 Alt and returning it never arrives. If I take the items out and create a new eMail it works properly.
The issue seems solved, but is now back again.

**Comment by Dirge123** [comment]
This is still an issue.
I lost over 100 bolts of Runecloth and about 50g :(

**Comment by thesmasher** [comment]
I lost about 300 herbs. Might want to disable the return button, or you could change it to the delete button. Since that is what it does. This is a basic game function that is broken in a terrible way. This is a major issue.

**Comment by zpectral** [comment]
Same bug for me as well.

**Comment by xmesaj2** [comment]
The update goes live at the time of this comment so let me know if it still happens after that. Revision 2645+

**Comment by AndrewNB41191** [comment]
I havent experienced this bug, but now mail from AH (purchased item on buyout) is dissapearing, despite relogs and waiting 2+hrs.

**Comment by AndrewNB41191** [comment]
update: the more recent four items that i bought appeared, but upon "looting the mail" the items never appeared in my bag.

**Comment by xmesaj2** [comment]
Auction House items should appear after relogging, this is going to be fixed once rev 2657 goes live, they will appear instantly. Can you give me more information what kind of items did you loot from mailbox that didn't appear in bags?

**Comment by AndrewNB41191** [comment]
Iron Bars, they appeared in my bags eventually, not sure what it was about. if no one else has experianced it would have been addon related.

**Comment by Tereneckla** [comment]
rev 3058
