### ISSUE TITLE
[Quest] Underlight Ore Samples

### ISSUE THREAD

**Issue by bluemike61** [Atlantiss/NetherwingBugtracker#3874]
[//]: # (Enclose links to things related to the bug using http://wowhead.com or any other TBC database.)
[//]: # (You can use screenshot ingame to visual the issue.)
[//]: # (Write your tickets according to the format:)
[//]: # ([Quest][Azuremyst Isle] Red Snapper - Very Tasty!)
[//]: # ([NPC] Magistrix Erona)
[//]: # ([Spell][Mage] Fireball)
[//]: # ([Npc][Drop] Ghostclaw Lynx)
[//]: # ([Web] Armory doesnt work)
[//]: # (To find server revision type `.server info` command in the game chat.)

**Description**: For this quest you have to kill blackpaw gnolls for underlight ore samples.

**Current behaviour**: The underlight ore samples aren't shared amongst party members despite it being a quest drop.

**Expected behaviour**: The underlight ore sample should drop for the whole party.

**Server Revision**: 2596

**Comment by Shanghi** [comment]
This one was purposefully not set as group loot because it also comes from an object, and objects with group loot items act strangely out in the open world where multiple groups can interact with it.
