### ISSUE TITLE
Gordo NPC, in Tirisfall Glades.

### ISSUE THREAD

**Issue by ArzonNetherwing** [Atlantiss/NetherwingBugtracker#3875]
[//]: # (Enclose links to things related to the bug using http://wowhead.com or any other TBC database.)
[//]: # (You can use screenshot ingame to visual the issue.)
[//]: # (Write your tickets according to the format:)
[//]: # ([Quest][Azuremyst Isle] Red Snapper - Very Tasty!)
[//]: # ([NPC] Magistrix Erona)
[//]: # ([Spell][Mage] Fireball)
[//]: # ([Npc][Drop] Ghostclaw Lynx)
[//]: # ([Web] Armory doesnt work)
[//]: # (To find server revision type `.server info` command in the game chat.)

**Description**: Gordo NPC, in Tirisfall Glades.

**Current behaviour**: While patrolling the path, he occasionally walks through the floor and falls through it.

**Expected behaviour**:  

**Server Revision**:

**Comment by The14me** [comment]
Rev.3460 not an issue anymore.
