### ISSUE TITLE
The Maclure Vineyards Dynamic Respawn is low

### ISSUE THREAD

**Issue by ghost** [Atlantiss/NetherwingBugtracker#3876]
The boar are not dynamic respawn enabled, there quest loot is not shared with the group (everybody is ungrouping when they realize that)

Chunk of boar meat is not a quest item officialy but it should have a exeption

It take me 1 hour to finish it

**Comment by wtRCH** [comment]
It shouldn't have an exception. Boar should be added to the dynamic respawn tho.

**Comment by wtRCH** [comment]
@aresbrutus

**Comment by The14me** [comment]
May need a check.
