### ISSUE TITLE
Death after Unstuck

### ISSUE THREAD

**Issue by cah4ec182** [Atlantiss/NetherwingBugtracker#3877]
**Description**: More recently, unstuck has caused the death of a character. tested 3 times in a row, 3 times death.

**Current behaviour**: Kill character.

**Expected behaviour**: Dont kill character.

**Server Revision**:

**Comment by Wolffenstein** [comment]
Unstuck kills you if your hearthstone is on cooldown, to actually let you unstuck yourself...
