### ISSUE TITLE
[Quest][Mulgore] Kyle's Gone Missing!

### ISSUE THREAD

**Issue by caradas** [Atlantiss/NetherwingBugtracker#3878]
[//]: # (Enclose links to things related to the bug using http://wowhead.com or any other TBC database.)
[//]: # (You can use screenshot ingame to visual the issue.)
[//]: # (Write your tickets according to the format:)
[//]: # ([Quest][Azuremyst Isle] Red Snapper - Very Tasty!)
[//]: # ([NPC] Magistrix Erona)
[//]: # ([Spell][Mage] Fireball)
[//]: # ([Npc][Drop] Ghostclaw Lynx)
[//]: # ([Web] Armory doesnt work)
[//]: # (To find server revision type `.server info` command in the game chat.)

**Description**: 
Unique quest item drops multiple times.
**Current behaviour**:
The quest item "Tender Strider Meat" is marked unique and drops even if its already in the inventory
**Expected behaviour**: 
Unique quest items should only drop when not in inventory. (As far as i remember you could trigger a multiple unique drop when you have more as one mob lootable and a chance of a unique quest items but never get a unique quest item displayed to loot if you already have one)
**Server Revision**: 
2596

**Comment by wtRCH** [comment]
This might be due to shared quest items in party. Did this happen to you while in party or alone?

**Comment by Evolvee** [comment]
fixed in next rev
