### ISSUE TITLE
Shalandis Isle - Wrong music track

### ISSUE THREAD

**Issue by ttghnw** [Atlantiss/NetherwingBugtracker#388]
[//]: # (Enclose links to things related to the bug using http://wowhead.com or any other TBC database.)
[//]: # (You can use screenshot ingame to visual the issue.)
[//]: # (Write your tickets according to the format:)
[//]: # ([Quest][Azuremyst Isle] Red Snapper - Very Tasty!)
[//]: # ([NPC] Magistrix Erona)
[//]: # ([Spell][Mage] Fireball)
[//]: # ([Npc][Drop] Ghostclaw Lynx)
[//]: # ([Web] Armory doesnt work)

**Description**: **Current behaviour**:**Expected behaviour**: 
In Shalandis Isle, the track "Isle of Shalandis" should play (temple of the moon) not one of the eversong ones

**Server Revision**:

**Comment by tcberk12** [comment]
I was there on the beta and heard the correct custom music playing. 

This is the soundtrack: https://www.youtube.com/watch?v=-WdZIEtLGQo

**Comment by Wolffenstein** [comment]
It's controlled client-side. I can't change it in any way.
