### ISSUE TITLE
Mob leashes are heavily extended by totems

### ISSUE THREAD

**Issue by skittles56** [Atlantiss/NetherwingBugtracker#3880]
**Current behaviour**: When I put down an earthbind or stoneclaw totem, mob leashes are heavily extended (they can chase me from the town in bloodmyst all the way to the core where the blood elf pyromancers are). This also tends to affect other mobs even when I get rid of them before pulling another. This especially happens when I aggro more than one mob. 

For example, I aggroed a naga at the Wrathscale Lair and it followed me all the way south to Bristlebend Enclave after putting a stoneclaw totem down and an earthbind totem after when they caught up to me. This could end up for some crazy kiting behavior.

**Expected behaviour**: Mob leashes shouldn't be extended by totems and they definitely shouldn't follow you throughout half of the town

**Server Revision**: 2596

**Comment by staplerx300** [comment]
can confirm, it makes shamans unplayable

**Comment by Wolffenstein** [comment]
Fixed in rev 2666.
