### ISSUE TITLE
[Warlock][Pet] Warlock Demons resets their name after each crash.

### ISSUE THREAD

**Issue by DaddyDedoge** [Atlantiss/NetherwingBugtracker#3881]
[//]: # (Enclose links to things related to the bug using http://wowhead.com or any other TBC database.)
[//]: # (You can use screenshot ingame to visual the issue.)
[//]: # (Write your tickets according to the format:)
[//]: # ([Quest][Azuremyst Isle] Red Snapper - Very Tasty!)
[//]: # ([NPC] Magistrix Erona)
[//]: # ([Spell][Mage] Fireball)
[//]: # ([Npc][Drop] Ghostclaw Lynx)
[//]: # ([Web] Armory doesnt work)
[//]: # (To find server revision type `.server info` command in the game chat.)

**Description**: 
1: Warlock pet changed name to default "voidwalker" after crash

2: Also imp /petattack causes imp to go melee
**Current behaviour**:
1: Not giving me the custom warlock pet name

2: imp goes melee on /petattack
**Expected behaviour**: 
1: Pet is supposed to have unique name, started out as Kraknar

2: imp should start casting
**Server Revision**: 
2597

**Comment by DaddyDedoge** [comment]
Fireball was active, what I am saying is that "/petattack" and "shift+t" is behaving differently.

**Comment by H2714** [comment]
That's weird, "/petattack" and "shift+t" works just fine for me.  
Having a misbehaving imp and an impersonal voidwalker sounds bad, I hope you get it fixed. Good luck!

**Comment by DaddyDedoge** [comment]
voidwalker name is still "Voidwalker"

**Comment by The14me** [comment]
rev .3460 Void have unique name too.
Can be closed.
