### ISSUE TITLE
Warlock Soul Shards Issue

### ISSUE THREAD

**Issue by arsalanrkhan** [Atlantiss/NetherwingBugtracker#3882]
Description: Soul Stones gathered do not directly go to the soul bag.

Current behaviour: My Soul Shards do not directly go to the soul bag. Instead, they go to the first available slot in any bag.

Expected behaviour: The Soul Shards should go to the first available slot of the Soul Bag, if the soul bag is present and has enough space.

Server Revision: 2598

**Comment by Neophrone** [comment]
Do u use any warlock addons? Necrosis for example has an option to select a bag where u'r soul shards will be placed even if u have soul bag and selected bag is a common bag.

**Comment by Drayo** [comment]
I also don't have this issue, might be an addon.

**Comment by arsalanrkhan** [comment]
I dont have any warlock addons yet. Also I just realized that I can even place any other item in the soul bag. It just acts like a common bag.

**Comment by wtRCH** [comment]
What soul bag do you have? @arsalanrkhan

**Comment by Snowie493** [comment]
Using the soulbag you get from succubus quest. Only soulshards go automatic in it and no other items can be placed there.
Might need more research on this one before fixing something that is working?

**Comment by duzyizly** [comment]
this is addon related (fortexorcist or necrosis) or some old (fixed) core issue.

![WoWScrnShot_062320_235104](https://user-images.githubusercontent.com/43931626/85468369-aaa27f80-b5ac-11ea-9f29-a65860729335.jpg)
![WoWScrnShot_062320_235206](https://user-images.githubusercontent.com/43931626/85468375-abd3ac80-b5ac-11ea-9ea1-4168e9b1697c.jpg)
