### ISSUE TITLE
[core][spell][warrior] Intimidating shout should probably affect units behind the caster as well

### ISSUE THREAD

**Issue by Evolvee** [Atlantiss/NetherwingBugtracker#3883]
https://www.youtube.com/watch?v=3z2nV3pRDS0&feature=youtu.be&t=77

Currently affects only units in front of caster(the 2ndary fear).

**Comment by Evolvee** [comment]
^^ We are talking about the 2ndary fear effect. Not primary on main target.

**Comment by teddys** [comment]
https://youtu.be/VNgGCGl0_S0?t=349

**Comment by Easyfraggy** [comment]
Primary target has to be in front. It is a seperate effect - it also has longer range than the aoe part of the fear. This issue is invalid.
