### ISSUE TITLE
Voidwalker low threat with optimal talents for tanking.

### ISSUE THREAD

**Issue by bautazor** [Atlantiss/NetherwingBugtracker#3884]
[//]: # (Enclose links to things related to the bug using http://wowhead.com or any other TBC database.)
[//]: # (You can use screenshot ingame to visual the issue.)
[//]: # (Write your tickets according to the format:)
[//]: # ([Quest][Azuremyst Isle] Red Snapper - Very Tasty!)
[//]: # ([NPC] Magistrix Erona)
[//]: # ([Spell][Mage] Fireball)
[//]: # ([Npc][Drop] Ghostclaw Lynx)
[//]: # ([Web] Armory doesnt work)
[//]: # (To find server revision type `.server info` command in the game chat.)

**Description**: Voidwalker losing threat on single-target even with 3/3 improved voidwalker and 2/2 improved drain soul. I've noticed it can hold aggro if it facepulls. Then i can suddenly put full dots and spam shadowbolts without overtaking. I'm not sure if this is a bug related to who engages first (some private servers have this bug) or if the threat levels are just off. Level 24 warlock, rank 2 torment on auto-cast.

**Current behaviour**: My voidwalker loses aggro very easily on one target with only dots + some wanding

**Expected behaviour**: The voidwalker should be able to hold aggro on one target when I have full dots and wanding, given that I've put talent points to make it optimal for it to do so. Especially seeing as my character is far from twinked out.

**Server Revision**:

**Comment by Kristoferhh** [comment]
I've noticed a threat problem on my hunter as well. From what I can see, my pet uses taunt once in the beginning of the fight then never again.

**Comment by Snowie493** [comment]
I have not specced that and my voidwalker keeps aggro just fine with fulldots + wanding. Even a rogue in party cant steal aggro from it.

**Comment by knasen88** [comment]
Is it oom? His growl manacost is far higher than his regen

**Comment by leeviathan** [comment]
My felguard can't keep aggro well at all, it seems a lot worse than the voidwalker. Curse of Agony + Corruption + Drain Life (untalented, ~6 seconds into fight) will pull any mob. No wanding or other attacks of any kind, taunt on cooldown. Level 60. I have talented reduction to affliction threat too.
