### ISSUE TITLE
[Quest] Test of Lore 

### ISSUE THREAD

**Issue by Anduyon** [Atlantiss/NetherwingBugtracker#3885]
[//]: # (Enclose links to things related to the bug using http://wowhead.com or any other TBC database.)
[//]: # (You can use screenshot ingame to visual the issue.)
[//]: # (Write your tickets according to the format:)
[//]: # ([Quest][Azuremyst Isle] Red Snapper - Very Tasty!)
[//]: # ([NPC] Magistrix Erona)
[//]: # ([Spell][Mage] Fireball)
[//]: # ([Npc][Drop] Ghostclaw Lynx)
[//]: # ([Web] Armory doesnt work)
[//]: # (To find server revision type `.server info` command in the game chat.)

**Description**: 
Legacy of the Aspects cannot be looted.
**Current behaviour**:
The Book in Dor'danil is empty when looted.
**Expected behaviour**: 
It should contain the book [Legacy of the Aspects] for the quest Test of Lore.
**Server Revision**:

**Comment by Asparagoose** [comment]
This is likely related to the empty gameobjects bug, they weren't resetting properly after a recent fix and it's reported to have been fixed now.

**Comment by wtRCH** [comment]
@Anduyon Is it still happening after revision 2603? You can check revision typing .server info on the chat in game.

**Comment by Manaci** [comment]
Fixed
