### ISSUE TITLE
[Hunter] Sometimes targetting a 2nd mob while pet is attacking the first mob still attacks the mob the pet is on

### ISSUE THREAD

**Issue by Nawoz** [Atlantiss/NetherwingBugtracker#3887]
Basically there are times i try to tag a 2nd monster while my pet is already on one. While targeting the 2nd monster I still attack the 1st mob my pet is on regardless of how many times I retarget the 2nd mob. My pet is a ravager specimen from azuremyst if that helps any.

Let me clarify I am trying to shoot the 2nd mob with an arrow and leave my pet on the first mob, not change my pet's target.

Thanks.

**Comment by wtRCH** [comment]
@Wolffenstein Wand and Pet autoattack are back again.

**Comment by Zarant** [comment]
Issues #844 and #2978 are probably related to this one.

**Comment by Godmatik** [comment]
Must have been fixed a long time ago, closing
