### ISSUE TITLE
[Quest][Elwynn Forest] Legend of Stalwan ghost focuses someone else

### ISSUE THREAD

**Issue by Mikik3jr** [Atlantiss/NetherwingBugtracker#3888]
[//]: # (Enclose links to things related to the bug using http://wowhead.com or any other TBC database.)
[//]: # (You can use screenshot ingame to visual the issue.)
[//]: # (Write your tickets according to the format:)
[//]: # ([Quest][Azuremyst Isle] Red Snapper - Very Tasty!)
[//]: # ([NPC] Magistrix Erona)
[//]: # ([Spell][Mage] Fireball)
[//]: # ([Npc][Drop] Ghostclaw Lynx)
[//]: # ([Web] Armory doesnt work)
[//]: # (To find server revision type `.server info` command in the game chat.)

**Description**: 
In this quest I was asked to open a chest in the upper level of the inn (in goldshire) and it summoned a ghost.

**Current behaviour**:
The ghost attacked a lv10 rogue who was like 2 rooms away instead of me.
![wowscrnshot_010619_184407](https://user-images.githubusercontent.com/43505031/50739611-5c949300-11e3-11e9-9ea1-41d25b2eb57e.jpg)
I tried to save her, but the ghost polimorphed me and switched back to the rogue. >.>
![wowscrnshot_010619_184414](https://user-images.githubusercontent.com/43505031/50739620-6fa76300-11e3-11e9-9906-9e5a665ea1b0.jpg)

**Expected behaviour**: 
I think it should attack me.

**Server Revision**: 
Content patch: 203

**Comment by Godmatik** [comment]
Forlorn spirit should not spawn at Goldshire Inn for this quest in the chain.

I tested it and it currently does not spawn, so I am guessing this was properly removed at some point.

Closing
