### ISSUE TITLE
Bandaging somebody else while eating, cancells the food.

### ISSUE THREAD

**Issue by Ficue** [Atlantiss/NetherwingBugtracker#3889]
**Description**: I tried to bandage a guy while he was eating food and the bandage cancelled his food, he immediately stood up and cancelled the food timer. He had to eat again.

**Current behaviour**: Eating cancelled while being bandaged.

**Expected behaviour**: Someone else should be able to keep eating while being bandaged.

**Server Revision**:

**Comment by Tenoutoften** [comment]
Known issue https://github.com/Atlantiss/NetherwingBugtracker/issues/130
