### ISSUE TITLE
[Item] Group rolling for an item issue

### ISSUE THREAD

**Issue by Brasso** [Atlantiss/NetherwingBugtracker#3891]
[//]: # (Enclose links to things related to the bug using http://wowhead.com or any other TBC database.)
[//]: # (You can use screenshot ingame to visual the issue.)
[//]: # (Write your tickets according to the format:)
[//]: # ([Quest][Azuremyst Isle] Red Snapper - Very Tasty!)
[//]: # ([NPC] Magistrix Erona)
[//]: # ([Spell][Mage] Fireball)
[//]: # ([Npc][Drop] Ghostclaw Lynx)
[//]: # ([Web] Armory doesnt work)
[//]: # (To find server revision type `.server info` command in the game chat.)

**Current behaviour**
When rolling for an item in a group and the person that wins the item has a full inventory, the item is free to loot for the rest of the group.

![image](https://user-images.githubusercontent.com/44345420/50741945-bb1e3900-1204-11e9-8d02-14744cc93f10.png)
Weppas looted the item.

**Expected behaviour**: 
The item should still belong to the person that won.
**Server Revision**: 
2599

**Comment by wtRCH** [comment]
@Wolffenstein

**Comment by dominion-pvp** [comment]
This issue is in every pserver afaik. I think even in retail if you had full bags and won loot, it still went up for grabs.

**Comment by Manaci** [comment]
Fixed with loot rework
