### ISSUE TITLE
summoning meeting stone and warlock spell

### ISSUE THREAD

**Issue by DaddyDedoge** [Atlantiss/NetherwingBugtracker#3895]
[//]: # (Enclose links to things related to the bug using http://wowhead.com or any other TBC database.)
[//]: # (You can use screenshot ingame to visual the issue.)
[//]: # (Write your tickets according to the format:)
[//]: # ([Quest][Azuremyst Isle] Red Snapper - Very Tasty!)
[//]: # ([NPC] Magistrix Erona)
[//]: # ([Spell][Mage] Fireball)
[//]: # ([Npc][Drop] Ghostclaw Lynx)
[//]: # ([Web] Armory doesnt work)
[//]: # (To find server revision type `.server info` command in the game chat.)

**Description**: 
Summoning party members not working 
**Current behaviour**:
says "you have no target" when trying to summon with both meeting stone and warlock summoning spell
**Expected behaviour**: 
its expected to summon people
**Server Revision**: 
2603

**Comment by DaddyDedoge** [comment]
warlock summon can also summon people from outside of dungeon to inside a dungeon, not sure if this is intended or not

**Comment by DaddyDedoge** [comment]
Summoning problem seems to occur when trying to summon someone from one continent to another.
Not sure if intended or not

**Comment by Netherwingreporter** [comment]
> Summoning problem seems to occur when trying to summon someone from one continent to another.
> Not sure if intended or not

I just reported the same issue here https://github.com/Atlantiss/NetherwingBugtracker/issues/3896.

These can be merged if its easier.
