### ISSUE TITLE
[Spell] Dungeon Meeting Stone Summon Across Continents

### ISSUE THREAD

**Issue by Netherwingreporter** [Atlantiss/NetherwingBugtracker#3896]
[//]: # (Enclose links to things related to the bug using http://wowhead.com or any other TBC database.)
[//]: # (You can use screenshot ingame to visual the issue.)
[//]: # (Write your tickets according to the format:)
[//]: # ([Quest][Azuremyst Isle] Red Snapper - Very Tasty!)
[//]: # ([NPC] Magistrix Erona)
[//]: # ([Spell][Mage] Fireball)
[//]: # ([Npc][Drop] Ghostclaw Lynx)
[//]: # ([Web] Armory doesnt work)
[//]: # (To find server revision type `.server info` command in the game chat.)

**Description**: You're unable to summon people across continents through dungeon meeting stones. We tested this a few times with someone taking the boat back and forth between the continents. 

Here's a picture of the bug in question. Note my location and the player we're trying to summons location. Also the error message at the top of the screen.

![wowscrnshot_010619_233530](https://user-images.githubusercontent.com/46065757/50755135-f7559780-120c-11e9-851e-691f076e705a.jpg)

**Current behaviour**: Show's "No Target" error message and doesn't summon.

**Expected behaviour**: You should be able to summone regardless of where the other person is at in the world.

**Server Revision**:

**Comment by wtRCH** [comment]
Reverted latest changes. You should be able to summon across servers.

**Comment by Demite** [comment]
This still doesn't work is the present way to summon only within said continent the way its going to stay? when attempting to summon someone on another continent it says you have no target.
