### ISSUE TITLE
[Spell][Hunter][Pets] Auto-cast spell priority

### ISSUE THREAD

**Issue by Kristoferhh** [Atlantiss/NetherwingBugtracker#3897]
**Description**: The spell prioritization on the auto-cast spells isn't working as intended.

**Current behaviour**: My pet, a cat, spams Claw all the time even though Growl (which has lower focus cost as well) is infront of it in priority.

**Expected behaviour**: It should use Growl if it's off cooldown, then Bite if it's off cooldown and Growl is on cooldown, then Claw if both Growl and Bite are on cooldown, since Growl is in spell slot nr. 1, Bite is in nr. 2 and Claw is in nr. 3

**Server Revision**: 2603

**Comment by Zarant** [comment]
I don't think this is a bug, unless if it was an undocumented change that happened somewhere between vanilla and patch 2.4.3

It's been confirmed that this particular issue was the intended behavior in patch 1.12:
https://docs.google.com/spreadsheets/d/1rQRdHw8LgmiPEVc8ST-cwdD1kKkBwhwlK1f0eO45voU/edit#gid=992486865

According to the research done on the classic hunter discord, pets are supposed to use spells randomly with no particular priority.
