### ISSUE TITLE
Infinite Spawn of minions

### ISSUE THREAD

**Issue by Realnairoby** [Atlantiss/NetherwingBugtracker#3898]
[//]: # (Enclose links to things related to the bug using http://wowhead.com or any other TBC database.)
[//]: # (You can use screenshot ingame to visual the issue.)
[//]: # (Write your tickets according to the format:)
[//]: # ([Quest][Azuremyst Isle] Red Snapper - Very Tasty!)
[//]: # ([NPC] Magistrix Erona)
[//]: # ([Spell][Mage] Fireball)
[//]: # ([Npc][Drop] Ghostclaw Lynx)
[//]: # ([Web] Armory doesnt work)
[//]: # (To find server revision type `.server info` command in the game chat.)

**Description**: 
NPCs with adds, such as pets or npcs that spawn adds are acting incorrect. E.g. Shadowpine Catlord in Ghostlands.
Some more researches were done here: https://github.com/ccshiro/cc-buglist/issues/1058
**Current behaviour**:
If you kill the main NPC and you will die due to the add the npc will respawn and spawn a new add as well. Means after the respawn he will have 2 adds. This is an infinite cycle. Killing the main npc again and dying due to the 2 adds --> He will respawn with an add and got 3 adds now. 
Same for NPCs that spawn adds to help them fight. If you kill the main NPC and die to the add he will respawn and still got the add. 

**Expected behaviour**: 
The add should despawn if you die after killing the main npc. It shouldnt stack up infinitely. 
 
**Server Revision**: 
2603

**Comment by duzyizly** [comment]
not a thing anymore, pet npc dissapears once you kill "main NPC" and die to pet.

![WoWScrnShot_062020_124631](https://user-images.githubusercontent.com/43931626/85200043-743adb00-b2f4-11ea-9270-34d3f36b3b77.jpg)
