### ISSUE TITLE
[Instance][NPC] Disappearing Willix the Importer

### ISSUE THREAD

**Issue by towneh** [Atlantiss/NetherwingBugtracker#3899]
**Description**: 
Once you have successfully completed the escort mission for Willix in RFK he offers you the chance to complete the quest and obtain your reward near the entrance to the instance.

**Current behaviour**:
As soon as the ? appears to complete the quest he disappears after a couple of seconds, and you cannot finish the quest until you reset the instance and speak to him back at his tent.

**Expected behaviour**: 
Willix should hang around for a bit longer before disappearing.

**Server Revision**: 
n/a

**Comment by Manaci** [comment]
Fixed
