### ISSUE TITLE
[NPC] Stonetusk Boar (Elwynn)

### ISSUE THREAD

**Issue by Dubmandeep** [Atlantiss/NetherwingBugtracker#39]
**Description**: 

- Drops Crag Boar Rib
- Low drop rate of boar meat
- Unable to attack Boars right next to Goldshire

**Expected behaviour**: 

- Should not drop Crag Boar Rib
- Should drop boar meat at a higher rater
- http://db.excalibur.ws/?npc=113

**Comment by Wolffenstein** [comment]
The loot should be correct according to our sources. The database you're linking is another private server.

**Comment by aresbrutus** [comment]
Point 1 confirmed: https://i.imgur.com/bLvdN86.png

**Comment by aresbrutus** [comment]
Point 3 should be fixed from 2094. Only point 1 and 2 left.

**Comment by Shanghi** [comment]
The rest should be fixed in revision 2152.
