### ISSUE TITLE
(Buff][Interaction)

### ISSUE THREAD

**Issue by Narec** [Atlantiss/NetherwingBugtracker#390]
Just ran Wailing Caverns and noticed a few things.

Mark of the Wild is unable to be cast on me when I have Demon Skin up. The NPC inside WC could still buff me, however. The same issue occurs for Fire Shield from my Imp, and Thorns.

Also I'm told you are already aware, but ritual of summoning does not work.

Thanks!

**Comment by wowthings** [comment]
It happens too with frost armor and devotion aura. #198

**Comment by Wolffenstein** [comment]
Fixed in rev 2067.
