### ISSUE TITLE
[Item] Cracked Power Core doesn't apply Spell Power to attacks

### ISSUE THREAD

**Issue by sinorius** [Atlantiss/NetherwingBugtracker#3902]
https://www.wowhead.com/item=23334/cracked-power-core

**Description**: 
Cracked power core doesn't apply SP to spells.

**Current behaviour**: 
Spells have the same power after consuming the core as they have before it.

**Expected behaviour**: 
Spells should hit with additional power after consuming the core

**Server Revision**: 
2603

![screenshot from 2019-01-07 15-51-38](https://user-images.githubusercontent.com/6484378/50775102-945c1300-1295-11e9-833d-6ea761a45dda.png)
![screenshot from 2019-01-07 15-51-45](https://user-images.githubusercontent.com/6484378/50775103-945c1300-1295-11e9-8456-4b290418dcb9.png)
![screenshot from 2019-01-07 15-51-57](https://user-images.githubusercontent.com/6484378/50775104-945c1300-1295-11e9-9a14-824460e0bde0.png)
![screenshot from 2019-01-07 15-52-19](https://user-images.githubusercontent.com/6484378/50775105-945c1300-1295-11e9-906e-6f1ae61ef141.png)

**Comment by sinorius** [comment]
I also noticed that the https://www.wowhead.com/spell=29109/arcane-residue spell wasn't giving the SP addition as well so maybe it's somehow connected?

**Comment by Tereneckla** [comment]
Fixed
