### ISSUE TITLE
[NPC] [Ehco Isles] Vodoo Troll

### ISSUE THREAD

**Issue by epsota** [Atlantiss/NetherwingBugtracker#3903]
[//]: # (Enclose links to things related to the bug using http://wowhead.com or any other TBC database.)
[//]: # (You can use screenshot ingame to visual the issue.)
[//]: # (Write your tickets according to the format:)
[//]: # ([Quest][Azuremyst Isle] Red Snapper - Very Tasty!)
[//]: # ([NPC] Magistrix Erona)
[//]: # ([Spell][Mage] Fireball)
[//]: # ([Npc][Drop] Ghostclaw Lynx)
[//]: # ([Web] Armory doesnt work)
[//]: # (To find server revision type `.server info` command in the game chat.)

**Description**: Trolls do not attack or move when attacked from range.

**Current behaviour**: Troll stands still and only casts healing wave when HP is low.

**Expected behaviour**:  Troll should attack and move towards target.

**Server Revision**: 2603

**Comment by The14me** [comment]
Cant reproduce.Please add some proof.

**Comment by The14me** [comment]
Rev.3482 not an issue anymore.
Can be closed.
