### ISSUE TITLE
Lava insta death in Ghostlands

### ISSUE THREAD

**Issue by mooviestar** [Atlantiss/NetherwingBugtracker#3904]
[//]: # (Enclose links to things related to the bug using http://wowhead.com or any other TBC database.)
[//]: # (You can use screenshot ingame to visual the issue.)
[//]: # (Write your tickets according to the format:)
[//]: # ([Quest][Azuremyst Isle] Red Snapper - Very Tasty!)
[//]: # ([NPC] Magistrix Erona)
[//]: # ([Spell][Mage] Fireball)
[//]: # ([Npc][Drop] Ghostclaw Lynx)
[//]: # ([Web] Armory doesnt work)
[//]: # (To find server revision type `.server info` command in the game chat.)
https://imgur.com/a/PFHrS5D
**Description**: 
I was in Deatholme in ghostlands in some of the green goo. I'm not sure if its meant to kill you but i instantly died after a few seconds of being in it
**Current behaviour**:
Died in the green goo took all my hp 
**Expected behaviour**: 
Maybe i shouldn't die in the green goo
**Server Revision**: 
Help

**Comment by Manaci** [comment]
Confirmed, green goo pools in the ziggurats do max lava dmg and 1 shots lowbies under 700ish HP

**Comment by Wolffenstein** [comment]
Fixed in rev 3366.
