### ISSUE TITLE
[Quest][Ironforge] Essential Artificals quest item can be looted by multiple people at the same time

### ISSUE THREAD

**Issue by Mikik3jr** [Atlantiss/NetherwingBugtracker#3906]
[//]: # (Enclose links to things related to the bug using http://wowhead.com or any other TBC database.)
[//]: # (You can use screenshot ingame to visual the issue.)
[//]: # (Write your tickets according to the format:)
[//]: # ([Quest][Azuremyst Isle] Red Snapper - Very Tasty!)
[//]: # ([NPC] Magistrix Erona)
[//]: # ([Spell][Mage] Fireball)
[//]: # ([Npc][Drop] Ghostclaw Lynx)
[//]: # ([Web] Armory doesnt work)
[//]: # (To find server revision type `.server info` command in the game chat.)

**Description**: 
In this quest there are machines on the ground that we have to loot (12). 

**Current behaviour**:
We found out if we try to loot it at the same time everyone can get it. It is not that easy to pull out, but we managed to do that multiple times. [We made a video about it for testing porpuses ofc](https://www.youtube.com/watch?v=DuZwjMDfs9s&feature=youtu.be)

**Expected behaviour**: 
- I don't know if it is blizzlike or not, so I don't know if it should happen
- As we pick it up it spawns back again (only if multiple people loot it at the same time) (is it releated to your new respawn system?)

**Server Revision**: 
Content patch: 203

**Comment by dominion-pvp** [comment]
Its shared loot in party duh.

**Comment by Mikik3jr** [comment]
Not really, cuz as you can see on the video that the last time only 1 guy got it instead all of us. It disappears as someone loot it.

**Comment by Sejadis** [comment]
afaik shared party loot does not apply to lootable objects, only mobs

**Comment by BamboozleNW** [comment]
Devo and myself tested this tonight, on the Kara PTR. This no longer works, multiple mobs, perfect timing, never worked once. Can be closed.
