### ISSUE TITLE
Can strafe jump kite indefinitely without taking damage

### ISSUE THREAD

**Issue by Notmittz** [Atlantiss/NetherwingBugtracker#391]
**Description**: 
If you strafe jump sideways, away from the mob, you can continue to hit them without them being able to hit you back.  I have been able to pull this off, fairly consistently, against many different mobs in the belf starter zones as well as the barrens so far.

https://youtu.be/N2H8VbHGhRs
(Video is unlisted and can only be accessed via this direct link)

**Current behaviour**:
Server is giving a lot of leeway to players when kiting sideways, allowing for the hitting of NPCs but the hit leeway isn't high enough for the mobs to keep up with.  Or the mob is trying to move in the players predicted direction during the camera turn, so that they can't keep up?  I'm not sure how it's being handled server side.

**Expected behaviour**: 
Mob should be able to keep up with players and continue to strike them even when doing this wonky maneuver.

**Comment by Jezofine** [comment]
#3176
