### ISSUE TITLE
Shaman Ligtning Shield NO INTERNAL CD

### ISSUE THREAD

**Issue by am3shan** [Atlantiss/NetherwingBugtracker#3910]
**Description**: Lightning shield seem to have no internal cd on trigger

**Current behaviour**:
shield damage triggers on every hit
**Expected behaviour**: 
shield should trigger only every few seconds as stated in the description
**Server Revision**: 
2603

screenshot of duel with a rogue 
https://imgur.com/a/ncU49S4

**Comment by Brasso** [comment]
#3840 Use search function to avoid making duplicate reports.

**Comment by Evolvee** [comment]
should be already fixed, retest pls

**Comment by wtRCH** [comment]
Working.
