### ISSUE TITLE
[PvP] Freezes in WPvP and in PvP in general.

### ISSUE THREAD

**Issue by Unfairy** [Atlantiss/NetherwingBugtracker#3911]
Typical for private servers bugs, I thought not happening here.
Sometimes, not every time, when engaged in PvP freezes happening for 2-5 seconds which making pvp frustrating and annoying.

Hope anyone can confirm or prove that so it will be looked for possible solution.

**Comment by Evolvee** [comment]
Can confirm 2 freezes outside of PVP (in arathi highlands) when running through the southern cave to prince nazjak.

Wasnt happening prior to launch.

**Comment by torrenzGH** [comment]
has happened to me several times mostly in wpvp
also observed allies lagging and walking in spot for several seconds when attacking em, will get footage from now

**Comment by Jseay1313** [comment]
happened frequently in SFK, ashenvale, and other places, common like OP mentioned on private servers and annoying.

**Comment by whissper** [comment]
on Archangel (old Feenix TBC realm) we dealt with this problem by reducing view distance to minimal value (in graphic settings on client)

**Comment by whissper** [comment]
hope we are able to make a links from other repositories...
Same issue was discussed:
https://github.com/FeenixServerProject/Archangel_2.4.3_Bugtracker/issues/2172
https://github.com/FeenixServerProject/Archangel_2.4.3_Bugtracker/issues/508

**Comment by Evolvee** [comment]
its not client issue

NW was freeze-less for the past 3 years on highest view distance for me, this is a new one.

**Comment by rychersky** [comment]
Also confirm. I will have random freezes while out in the world questing that last 10-45 seconds (one time causing the client to close out entirely). I have not disabled all add-ons to see if it still occurs but from what I can tell reading around, this doesn't seem to be add-on related.

**Comment by Unfairy** [comment]
So.
Weeks passed. 
I can only say that from my experience it's related to only having/appearing ANY OTHER THAN YOURS character on your screen.
It happened to me outside pvp also, in BEM when I was questing. 
Was doing it alone - no freezes. Party joined me - we all started getting freezes when get close to eachother.
Sometimes I see people get freeze when you just passing them by. Crossed my way with some troll in nagrand, both on mounts, but second later saw him got freeze.
(character start running animation in 1 spot).
Only can judge that it's related only to seeing other character appear / move on your screen.

**Comment by Unfairy** [comment]
Also to add.
Never happened in dungeon. 
Only in open world.
Need to check BGs and Arenas.

**Comment by rychersky** [comment]
This is occurring to me and others during 5-man instances.

**Comment by Godmatik** [comment]
Must have been fixed a long time ago, no comments about this issue in past year on Netherwing, and I have also never experienced such freezes as described.

Closing.
