### ISSUE TITLE
[Hunter][Pets] Pet randomly stays or stops moving when on follow

### ISSUE THREAD

**Issue by mooviestar** [Atlantiss/NetherwingBugtracker#3912]
[//]: # (Enclose links to things related to the bug using http://wowhead.com or any other TBC database.)
[//]: # (You can use screenshot ingame to visual the issue.)
[//]: # (Write your tickets according to the format:)
[//]: # ([Quest][Azuremyst Isle] Red Snapper - Very Tasty!)
[//]: # ([NPC] Magistrix Erona)
[//]: # ([Spell][Mage] Fireball)
[//]: # ([Npc][Drop] Ghostclaw Lynx)
[//]: # ([Web] Armory doesnt work)
[//]: # (To find server revision type `.server info` command in the game chat.)

**Description**: 
Walking anywhere with my pet on follow it will pause movement, i'll have to then tell it to follow again
**Current behaviour**:
Pet stops following when following
**Expected behaviour**: 
Pet should follow 
**Server Revision**: 
Should not stop moving

**Comment by Zarant** [comment]
Seems fixed, I cannot reproduce that.
