### ISSUE TITLE
Mind Blast Twice

### ISSUE THREAD

**Issue by jakeoff** [Atlantiss/NetherwingBugtracker#3914]
[//]: # (Enclose links to things related to the bug using http://wowhead.com or any other TBC database.)
[//]: # (You can use screenshot ingame to visual the issue.)
[//]: # (Write your tickets according to the format:)
[//]: # ([Quest][Azuremyst Isle] Red Snapper - Very Tasty!)
[//]: # ([NPC] Magistrix Erona)
[//]: # ([Spell][Mage] Fireball)
[//]: # ([Npc][Drop] Ghostclaw Lynx)
[//]: # ([Web] Armory doesnt work)
[//]: # (To find server revision type `.server info` command in the game chat.)

**Description**: Mind Blast is able to be casted back-to-back (twice) if queued properly.

**Current behaviour**: Mind Blast can be casted twice (acting as if there are 2 charges) if the 2nd cast is queued up properly after the first.

**Expected behaviour**: Mind Blast should be put on a cooldown after the 1st use and therefore not able to be used back-to-back.

**Server Revision**:

**Comment by bekonja** [comment]
I can easily reproduce same bug as a tauren simply spamming War Stomp. It consistantly echoes twise.

**Comment by jakeoff** [comment]
> What does it mean "queued up properly"? Can you record it?

It also works if you just spam it. Can easily replicate it by casting Mind Blast and just spamming the button as you're casting the first, it will result in two Mind Blasts casts.
