### ISSUE TITLE
[Core][Dungeon] Muyoh event in Wailing Caverns crashes server

### ISSUE THREAD

**Issue by Kristoferhh** [Atlantiss/NetherwingBugtracker#3917]
**Description**: When doing the last boss event in Wailing Caverns, the server crashes a high number of times.

**Current behaviour**: The event causes the server to crash for whatever reason before Muyoh even gets into the room to start the wave event

**Expected behaviour**: The server should not crash

**Server Revision**: 2603

**Comment by nullfoxh** [comment]
Crashed for us on first wave today

**Comment by Evolvee** [comment]
coincidence probably
