### ISSUE TITLE
Small druid bug

### ISSUE THREAD

**Issue by Stripeink** [Atlantiss/NetherwingBugtracker#3918]
So i am playing a nightelf druid and i have put points into increasing my mark of the wild. now on the buff it says i should be getting 74 armor but on the buff its saying i only have 65 armor.

not a major issue just dont know if its working properly

**Comment by devo6969** [comment]
This is still in classic and always has been a thing for years. Like tenoutoften said, it will update on your tooltip but not "visually" show the amount on the buff. 
Refer to #4004
