### ISSUE TITLE
[Dungeon][BFD] Twilight Lord Kelris adds are bugged

### ISSUE THREAD

**Issue by Kristoferhh** [Atlantiss/NetherwingBugtracker#3919]
**Description**: The adds (water elementals at least) that you spawn after defeating Twilight Lord Kelris are bugged

**Current behaviour**: Four of them spawn, which completely decimate the party with aoe frostbolts

**Expected behaviour**: Only two of them are supposed to spawn. Still decent amount of damage, but half of what's currently going on.

**Server Revision**: 2603

**Comment by Jovzin** [comment]
No it should be like that.  4 has to sapwn.  You have to take cover and separate them

**Comment by The14me** [comment]
Work just fine.

**Comment by femdead** [comment]
It's supposed to be 2 water eles, 4 turtles, 6 lobsters and 8 non-elite crabs (12 maybe? a swarm anyway)
right now it's 4 of each mob type
