### ISSUE TITLE
[NPC]Silithid Swarmer (3252)

### ISSUE THREAD

**Issue by Kentamentiu** [Atlantiss/NetherwingBugtracker#392]
[//]: # (Enclose links to things related to the bug using http://wowhead.com or any other TBC database.)
[//]: # (You can use screenshot ingame to visual the issue.)
[//]: # (Write your tickets according to the format:)
[//]: # ([Quest][Azuremyst Isle] Red Snapper - Very Tasty!)
[//]: # ([NPC] Magistrix Erona)
[//]: # ([Spell][Mage] Fireball)
[//]: # ([Npc][Drop] Ghostclaw Lynx)
[//]: # ([Web] Armory doesnt work)

**Description**: 
Silithid Swarmer sometimes instantly respawns when you kill them, continuing in combat

**Current behaviour**:
Respawn upon kill.

**Expected behaviour**: 
Just die and stay dead.

**Server Revision**: 
2040

**Comment by wtRCH** [comment]
@pelekon

**Comment by The14me** [comment]
Cant reproduce.Please re-open if happen again.
