### ISSUE TITLE
[Quest]Q#7735 Pristine Yeti Hide should give 2200xp, currently gives 0xp

### ISSUE THREAD

**Issue by Tenoutoften** [Atlantiss/NetherwingBugtracker#3920]
**Description**: 
http://web.archive.org/web/20080917071049/http://thottbot.com:80/q7735
Pristine Yeti Hide Q#7735 should give 2200 Xp currently gives 0xp.

![](https://i.gyazo.com/a5bd8f2e39aaee222c92f1ac9876dc75.png)
**Expected behaviour**: 
2200xp

**Server Revision**: 
2603

**Comment by Evolvee** [comment]
https://www.wowhead.com/quest=7735/pristine-yeti-hide#comments:id=567337
https://www.wowhead.com/quest=7735/pristine-yeti-hide#comments:id=157316
https://www.wowhead.com/quest=7735/pristine-yeti-hide#comments:id=293423
https://www.wowhead.com/quest=7735/pristine-yeti-hide#comments:id=261212
https://www.wowhead.com/quest=7735/pristine-yeti-hide#comments:id=74150
https://www.wowhead.com/quest=7735/pristine-yeti-hide#comments:id=148869
https://www.wowhead.com/quest=7735/pristine-yeti-hide#comments:id=35651
https://www.wowhead.com/quest=7735/pristine-yeti-hide#comments:id=117257
https://www.wowhead.com/quest=7735/pristine-yeti-hide#comments:id=45954
https://www.wowhead.com/quest=7735/pristine-yeti-hide#comments:id=127733

isnt supposed to give any XP
