### ISSUE TITLE
Shaman ankh not placed on cooldown. 

### ISSUE THREAD

**Issue by wedemhaha** [Atlantiss/NetherwingBugtracker#3922]
[//]: # (Enclose links to things related to the bug using http://wowhead.com or any other TBC database.)
[//]: # (You can use screenshot ingame to visual the issue.)
[//]: # (Write your tickets according to the format:)
[//]: # ([Quest][Azuremyst Isle] Red Snapper - Very Tasty!)
[//]: # ([NPC] Magistrix Erona)
[//]: # ([Spell][Mage] Fireball)
[//]: # ([Npc][Drop] Ghostclaw Lynx)
[//]: # ([Web] Armory doesnt work)
[//]: # (To find server revision type `.server info` command in the game chat.)

**Description**: 
Shaman Ankh has no cooldown.
**Current behaviour**:
Shaman ankh is currently not placed on cooldown on first use, and you can subsequently spam rez yourself as long as you have reagents. 
**Expected behaviour**: 
Ankh is placed on cooldown and a reagent consumed on use after death. 
**Server Revision**:

**Comment by wedemhaha** [comment]
https://clips.twitch.tv/SoftWimpyManateeSeemsGood

**Comment by Evolvee** [comment]
should be already fixed, retest pls
