### ISSUE TITLE
Souvenirs of Death

### ISSUE THREAD

**Issue by tbc123** [Atlantiss/NetherwingBugtracker#3923]
Deathguard Samsa of Tarren Mill wants 30 Hillsbrad Human Skulls.
Relevant Locations
This NPC or object can be found in Alterac Mountains.
Description
I hear you were enlisted by Darthalia to wage war on the humans of Hillsbrad. So jealous I am. . .

While you're off having all the fun -- slaying humans, pillaging the town, terrorizing innocent people -- I am stuck standing guard here in Tarren Mill.

Perhaps you'll take pity on an old Deathguard like myself? You see I am collecting human skulls. And you will be fighting humans for quite some time. Over the course of your long battle, bring me 30 skulls and I will make it worth your while.
Reward
You will receive:
Skull Ring
Progress
So the lucky <name> returns? How many humans have you slaughtered today? Hundreds I do hope!

Have you any skulls for me?
Completion
Precious skulls! So beautiful! I owe you as promised, <name>!
Gains
Upon completion of this quest you will gain:
2600 exp (at level 20) 0gold/15siver/60 at max level
350 reputation with Undercity

drop on this quest loot so low

**Comment by The14me** [comment]
Its blizzlike. Drop rate is 30 to 50% depend of the NPC.
