### ISSUE TITLE
Melee Auto Attack bug when attacking reseting npc

### ISSUE THREAD

**Issue by powerlol** [Atlantiss/NetherwingBugtracker#3924]
[//]: # (Enclose links to things related to the bug using http://wowhead.com or any other TBC database.)
[//]: # (You can use screenshot ingame to visual the issue.)
[//]: # (Write your tickets according to the format:)
[//]: # ([Quest][Azuremyst Isle] Red Snapper - Very Tasty!)
[//]: # ([NPC] Magistrix Erona)
[//]: # ([Spell][Mage] Fireball)
[//]: # ([Npc][Drop] Ghostclaw Lynx)
[//]: # ([Web] Armory doesnt work)
[//]: # (To find server revision type `.server info` command in the game chat.)

**Description**: 
When u charge/melee attack a NPC that's reseting (i.e. running back to his position) you won't be able to auto attack him if he aggros you back on his position. You'll have to leave combat to be able to hit him back. 
**Current behaviour**:
Auto attack won't trigger till you get out of combat
**Expected behaviour**: 
Auto attack/charge should evade till he gets in position and then you'll be able to hit him with auto attack 
**Server Revision**: Live

**Comment by The14me** [comment]
Rev.3482 still an issue.

**Comment by Godmatik** [comment]
Duplicate - already an issue open about evading mobs and being unable to attack
