### ISSUE TITLE
Gnomeregan bosses not dropping loot

### ISSUE THREAD

**Issue by Hellzmatter** [Atlantiss/NetherwingBugtracker#3925]
[//]: # (Enclose links to things related to the bug using http://wowhead.com or any other TBC database.)
[//]: # (You can use screenshot ingame to visual the issue.)
[//]: # (Write your tickets according to the format:)
[//]: # ([Quest][Azuremyst Isle] Red Snapper - Very Tasty!)
[//]: # ([NPC] Magistrix Erona)
[//]: # ([Spell][Mage] Fireball)
[//]: # ([Npc][Drop] Ghostclaw Lynx)
[//]: # ([Web] Armory doesnt work)
[//]: # (To find server revision type `.server info` command in the game chat.)

**Description**: 
Gnomeregan bosses not dropping loot
**Current behaviour**:
Cleared the first 2 bosses in Gnomeregan (The troll boss and slime boss) and neither dropped any loot.
**Expected behaviour**: 
Drop at least 1 blue item from bosses.
**Server Revision**:

**Comment by Evolvee** [comment]
need info
which bosses - and their id

**Comment by Evolvee** [comment]
cant reproduce
