### ISSUE TITLE
[Spell][Hunter][Pet]Furious Howl

### ISSUE THREAD

**Issue by Kristoferhh** [Atlantiss/NetherwingBugtracker#3926]
**Description**: The Furious Howl ability for Wolf hunter pets is bugged.

**Current behaviour**: If it's set to auto-cast, it will auto-cast even if out of combat which cancels the feed pet effect. Which means when you want to feed your pet you have to take it off auto-cast, feed it, wait for it to be done feeding, then turn it back on.

**Expected behaviour**: Furious Howl should only auto-cast, if set so, during combat.

**Server Revision**: 2603

**Comment by theisk** [comment]
Don't think this is fixed yet? 
It'd be a BIG QoL fix for upcomming fresh with all the new hunters lvl'ing in groups with wolves

**Comment by Wolffenstein** [comment]
Fixed in rev 3426.
