### ISSUE TITLE
[Spell] Able to multicast spells with macros

### ISSUE THREAD

**Issue by Medry** [Atlantiss/NetherwingBugtracker#3928]
[//]: # (Enclose links to things related to the bug using http://wowhead.com or any other TBC database.)
[//]: # (You can use screenshot ingame to visual the issue.)
[//]: # (Write your tickets according to the format:)
[//]: # ([Quest][Azuremyst Isle] Red Snapper - Very Tasty!)
[//]: # ([NPC] Magistrix Erona)
[//]: # ([Spell][Mage] Fireball)
[//]: # ([Npc][Drop] Ghostclaw Lynx)
[//]: # ([Web] Armory doesnt work)
[//]: # (To find server revision type `.server info` command in the game chat.)

**Description**: 
Make a macro and /cast the same spells (only specific ones work) on several lines, and you can multicast the spell when you press the macro. Such as bloodrage, and getting max rage in 1 gcd. 
Added video of it from youtube. https://youtu.be/gV8W6UKj9mI
**Current behaviour**:
Press the macro and get max rage, lose a ton of health. if i click twice quickly i can nearly kill myself. Spells multi casting inside a macro
**Expected behavior**: 
Should cast the spell once
**Server Revision**: 
2606

**Comment by Realnairoby** [comment]
Its the same for potions.

**Comment by RealZwox** [comment]
Im pretty sure thats cause the Que spells and delayed Spells

**Comment by Marow** [comment]
And so much people abused that and are already near 60.... nice -.- hope they get banned!

**Comment by RealZwox** [comment]
i could not do it anymore with bloodrage. Cant test the other stuff

**Comment by Evolvee** [comment]
k

**Comment by gabbat** [comment]
I (sometimes) can spamcast mindvision, ooming within 1second, depending on how fast I press the button. seems to be back
