### ISSUE TITLE
[Warlock][Pet:Voidwalker Spell Rank Issue]

### ISSUE THREAD

**Issue by louboo1** [Atlantiss/NetherwingBugtracker#3929]
[//]: # (Enclose links to things related to the bug using http://wowhead.com or any other TBC database.)
[//]: # (You can use screenshot ingame to visual the issue.)
[//]: # (Write your tickets according to the format:)
[//]: # ([Quest][Azuremyst Isle] Red Snapper - Very Tasty!)
[//]: # ([NPC] Magistrix Erona)
[//]: # ([Spell][Mage] Fireball)
[//]: # ([Npc][Drop] Ghostclaw Lynx)
[//]: # ([Web] Armory doesnt work)
[//]: # (To find server revision type `.server info` command in the game chat.)

**Description**: 
I purchased the Grimoire of Torment (Rank 2)  from NPC: Spackle Thornberry  at 'The Slaughtered Lamb' for my Voidwalker. After using the grimoire, I checked if it updated on my pet's skill bar. Torment was still at Rank 1. I checked the Spellbook page>Demon, Torment is still Rank 1 and did not upgrade to Rank 2. 

**Current behaviour**:

**Expected behaviour**: 
For pet spells to get updated in spellbook & spellbar, and to run as supposed to. 
**Server Revision**:

**Comment by Drayo** [comment]
https://github.com/Atlantiss/NetherwingBugtracker/issues/3884

These are probably related.

**Comment by devo6969** [comment]
This is fixed
