### ISSUE TITLE
[Spell]Searing Totem 

### ISSUE THREAD

**Issue by Bleachlol** [Atlantiss/NetherwingBugtracker#393]
**Description**: 
Seen a few times where the totem would kill random critters
**Current behaviour**:
Searing totem shooting random critters
**Expected behaviour**: 
Not kill critters
**Server Revision**: 
2040

Edit: Spelling

**Comment by Retinus** [comment]
Adding some more things / server rev 2050

According to [https://wow.gamepedia.com/Searing_Totem](url) searing totem will ignore neutral targets, unless you engage them first. Right now it attacks newtral mobs and critters.

Also according to [https://wow.gamepedia.com/Earthbind_Totem](url) earthbind totem will aggro neutral mobs within range. Its working correct.

**Comment by Retinus** [comment]
server rev 2060

One strange thing about searing totem aggro

1.You are out of combat
2.Place searing totem
3.Totem attacks a hostile mob
4.You enter combat
5.Mob attacks you and ignores totem

Mob should first attack the totem and then you.

**Comment by narayagh** [comment]
Searing Totem attacks/aggros neutrals after killing its current target - rev 2072

**Comment by Galawer** [comment]
The damage portion of this totem is incorrectly triggered by the shaman instead of the totem. It adds aggro to the you instead of the totem, in the combat log it shows you doing the damage, and it even procs lightning shield onto you.

![image](https://user-images.githubusercontent.com/1574432/46149954-bfcd6b80-c26b-11e8-94de-ae1243a5b12e.png)

**Comment by cathabv** [comment]
Confirmed still aggroing neutral targets e.g bunnies, striders etc even if you did not aggro the target

**Comment by The14me** [comment]
rev 3441. still attack anything alive around him.

**Comment by Wolffenstein** [comment]
Fixed in rev 3443.
