### ISSUE TITLE
mines mass spawning

### ISSUE THREAD

**Issue by evanijr** [Atlantiss/NetherwingBugtracker#3933]
[//]: # (Enclose links to things related to the bug using http://wowhead.com or any other TBC database.)
[//]: # (You can use screenshot ingame to visual the issue.)
[//]: # (Write your tickets according to the format:)
[//]: # ([Quest][Azuremyst Isle] Red Snapper - Very Tasty!)
[//]: # ([NPC] Magistrix Erona)
[//]: # ([Spell][Mage] Fireball)
[//]: # ([Npc][Drop] Ghostclaw Lynx)
[//]: # ([Web] Armory doesnt work)
[//]: # (To find server revision type `.server info` command in the game chat.)

**Description**: 
mines in Tirisfal Glade are everywhere
**Current behaviour**:
Way too many mines spawning in the zone copper tin and silver, unsure about other zones but this is insane the amount i am finding.
**Expected behaviour**: 
Mines should be a little rarer
**Server Revision**: 
2603

**Comment by Evolvee** [comment]
known https://github.com/Atlantiss/AtlantissTBCBT/issues/4431

**Comment by Evolvee** [comment]
the fix is already applied/on its way but i will just leave this topic open for now until its confirmed done
