### ISSUE TITLE
Mob Speed

### ISSUE THREAD

**Issue by Jseay1313** [Atlantiss/NetherwingBugtracker#3935]
**Current behaviour**: Many (most) mobs run too fast, many mobs keep up with travel form/dash or run faster than both

**Expected behaviour**: Common sense

**Server Revision**: 2606

**Comment by Evolvee** [comment]
which mobs? most mobs have 1.14 run speed

**Comment by Jseay1313** [comment]
pretty much every non raptor beast, many humanoids, ogres, go take a nice trip through STV in travel form and get back to me with your findings, maybe take a nice little look at daze and tauren agro radius while youre at it. 

https://www.youtube.com/watch?v=x1-UbZP9r7E&feature=youtu.be
