### ISSUE TITLE
Can't sell some items in AH with full charges

### ISSUE THREAD

**Issue by Rebeli83** [Atlantiss/NetherwingBugtracker#3937]
[//]: # (Enclose links to things related to the bug using http://wowhead.com or any other TBC database.)
[//]: # (You can use screenshot ingame to visual the issue.)
[//]: # (Write your tickets according to the format:)
[//]: # ([Quest][Azuremyst Isle] Red Snapper - Very Tasty!)
[//]: # ([NPC] Magistrix Erona)
[//]: # ([Spell][Mage] Fireball)
[//]: # ([Npc][Drop] Ghostclaw Lynx)
[//]: # ([Web] Armory doesnt work)
[//]: # (To find server revision type `.server info` command in the game chat.)

**Description**: 
At least Amulet of the Moon can't be sold in AH even with full charges.
**Current behaviour**:
Can't sell Amulet of the moon with full charges. 
https://imgur.com/a/QejcUfI
**Expected behaviour**: 
Should be able to sell items with full charges.
**Server Revision**:

**Comment by Tundra28** [comment]
[item] Heavy Golden Necklace of Battle is another case that cant be sold on full charge! probably some others. i'll keep this post update as soon as i found more bugs.

You can trade the pendant with anyone btw, just auction House

**Comment by cloudeca** [comment]
It appears to be only items that are learned from recipes. The ones learned from the trainer can be sold. I noticed that when you look at the information from a JC recipe for an item of that sort it's shown that it has only 1 charge but when you craft it it has 10 charges.

**Comment by temperrr** [comment]
Sadly this is still an issue. What makes it worse is that the value of the item is 1c, so it's worthless to sell aswell! (should be around the 16s mark!)

**Comment by GMThunderan** [comment]
It's true, tested it on PTR as well.

**Comment by Wolffenstein** [comment]
Fixed in rev 3361.
