### ISSUE TITLE
[Core] Stealthed units disappearing permanently

### ISSUE THREAD

**Issue by Zarant** [Atlantiss/NetherwingBugtracker#3939]
I can't reproduce it constantly, but sometimes stealthed units permanently disappear once they get close to you, as evidenced by the clip below:
https://www.twitch.tv/videos/360725365

I manage to detect the mob, and then at melee range the mob disappears, I'm still in combat and if you look closely to my health bar, I'm still taking damage but no combat log entries are being generated.
Maybe it has something to do with the fact that player stealth detection is much worse when the mob comes from behind, I don't know.

**Comment by Zarant** [comment]
Need research? Have you even checked the vod I linked? You guys even bother going through the reports? This likely have little to do with rogues or druids its mostly a NPC issue.

**Comment by deathkneel** [comment]
It also happened to me a few times. I was taking damage and I couldn't see any mobs around or select any with tab. Once I ran far enough away I could see the mob running back to his position and using stealth.

**Comment by The14me** [comment]
Rev.3482  Not an issue anymore. Must be fixed with stealth rework.
