### ISSUE TITLE
[Quest][Teldrassil] Iverron´s Antidote

### ISSUE THREAD

**Issue by toki90** [Atlantiss/NetherwingBugtracker#394]
**Description**: 
Looting of quest items working incorrectly.

**Current behaviour**:
After collecting all items (Moonpetal Lily, Hyacinth Mushroom) required for the quest, the items are still "sparkling" and you can loot them, though nothing appears in the lootbox if you do. (https://imgur.com/URlrnfR)

**Expected behaviour**: 
Shouldnt "sparkle" anymore, you shouldnt be able to right click it once you got all of the required item.

**Server Revision**:

**Comment by Navedonar** [comment]
.

**Comment by Tereneckla** [comment]
Fixed
