### ISSUE TITLE
[Spell][Shaman] Lightning shield oneshot

### ISSUE THREAD

**Issue by karliva** [Atlantiss/NetherwingBugtracker#3940]
[//]: # (Enclose links to things related to the bug using http://wowhead.com or any other TBC database.)
[//]: # (You can use screenshot ingame to visual the issue.)
[//]: # (Write your tickets according to the format:)
[//]: # ([Quest][Azuremyst Isle] Red Snapper - Very Tasty!)
[//]: # ([NPC] Magistrix Erona)
[//]: # ([Spell][Mage] Fireball)
[//]: # ([Npc][Drop] Ghostclaw Lynx)
[//]: # ([Web] Armory doesnt work)
[//]: # (To find server revision type `.server info` command in the game chat.)

**Description**: 
Lightning shield proccs unlimited amount of times with no internal cd on Mr. Smite in The Deadmines
**Current behaviour**:
On Mr. Smites AoE stun, Lightning Shield hits Mr. Smite infinite times untill he instantly dies.
**Expected behaviour**: 
Only 3 stacks, and internal CD
**Server Revision**: 

Clip of this happening:
https://www.twitch.tv/videos/360495254?t=550s

**Comment by Evolvee** [comment]
should be fixed already, retest pls

**Comment by Evolvee** [comment]
should be fixed already, retest pls

**Comment by karliva** [comment]
This seemed fixed when i did a DM run today
