### ISSUE TITLE
[core] [spell] Channeled spells vs double cast of instant into queue

### ISSUE THREAD

**Issue by Evolvee** [Atlantiss/NetherwingBugtracker#3941]
pretty sure already reported somewhere but cant find it

reproduction:

cast blizzard, spam ice lance, it gets triggered twice
on warlock, all channeling spells make your dark pact proc twice

**Comment by roflsaus** [comment]
This also works on Bloodrage for Warriors. You can spam it to be used several times, giving you full rage each cooldown.

**Comment by RealZwox** [comment]
https://github.com/Atlantiss/NetherwingBugtracker/issues/3928

**Comment by Dimmaro** [comment]
Issue works with consumables as well. You can make a macro to use multiple potions at once before cooldown is applied

**Comment by Evolvee** [comment]
cant reproduce the potion macro

**Comment by Evolvee** [comment]
blizzard/channeling works fine for me, so im closing this

**Comment by Evolvee** [comment]
nvm

**Comment by Jseay1313** [comment]
double casted a few moonfires today, did not channel a spell prior or anything

**Comment by Zadiel** [comment]
I don't know if this is the same issue or a different one, but this happens rarely with energy-based abilities too if you have the energy for 2 of them at once. I've seen rake, claw, and shred all double-use in one global, giving me 2 combo points and taking twice the energy.

**Comment by Jseay1313** [comment]
can still double mangle and double ice lance

**Comment by wowthings** [comment]
Still an issue, casted 2 moonfires

**Comment by Evolvee** [comment]
what did u cast prior to it
