### ISSUE TITLE
[Talent][Warrior] Improved Charge

### ISSUE THREAD

**Issue by tau94** [Atlantiss/NetherwingBugtracker#3942]
[//]: # (Enclose links to things related to the bug using http://wowhead.com or any other TBC database.)
[//]: # (You can use screenshot ingame to visual the issue.)
[//]: # (Write your tickets according to the format:)
[//]: # ([Quest][Azuremyst Isle] Red Snapper - Very Tasty!)
[//]: # ([NPC] Magistrix Erona)
[//]: # ([Spell][Mage] Fireball)
[//]: # ([Npc][Drop] Ghostclaw Lynx)
[//]: # ([Web] Armory doesnt work)
[//]: # (To find server revision type `.server info` command in the game chat.)

**Description**: 
Should increase amount of rage gained Charge ability.
2/2 Should generate 6 more rage. And 1/2 should generate 3 more rage.

I still only receive 15 Rage when using the Charge Ability, i expect 21 Rage with 2/2 talent.

**Current behaviour**:
Does not increase rage generated from Charge.

**Expected behaviour**: 
Should generate additional 6 rage.

**Server Revision**: 
2603

**Comment by liek0r** [comment]
Talent is working normally in rev 2605.
