### ISSUE TITLE
[Core][Spell][Warrior] Overpower not usable instantly after proc.

### ISSUE THREAD

**Issue by antikiller69** [Atlantiss/NetherwingBugtracker#3943]
[//]: # (Enclose links to things related to the bug using http://wowhead.com or any other TBC database.)
[//]: # (You can use screenshot ingame to visual the issue.)
[//]: # (Write your tickets according to the format:)
[//]: # ([Quest][Azuremyst Isle] Red Snapper - Very Tasty!)
[//]: # ([NPC] Magistrix Erona)
[//]: # ([Spell][Mage] Fireball)
[//]: # ([Npc][Drop] Ghostclaw Lynx)
[//]: # ([Web] Armory doesnt work)
[//]: # (To find server revision type `.server info` command in the game chat.)

**Description**: overpower

**Current behaviour**: overpower does not proc instantly when enemy dodges, it is tied into spellbatching which it should not be, all reactive skills should be able to use instantly instead waiting for spellbatching and its not lag
**Expected behaviour**: should proc instantly

**Server Revision**:

**Comment by wtRCH** [comment]
@Evolvee

**Comment by teddys** [comment]
https://youtu.be/VNgGCGl0_S0?t=347
Watch his bar when he gets a dodge ... overpower is usable immediately

**Comment by Easyfraggy** [comment]
your timestamp is wrong teddys: https://youtu.be/VNgGCGl0_S0?t=355

However you are correct it should not be delayed for sure.

**Comment by tsuone** [comment]
Bump.

**Comment by Godmatik** [comment]
Need to retest and reverify.
And if it is still bugged, need to see how it feels after upcoming weapon proc rework branch.

**Comment by Godmatik** [comment]
Rev 4018 - can't reproduce
I am able to use the same instant I get a dodge.
