### ISSUE TITLE
warrior intimidating shout

### ISSUE THREAD

**Issue by antikiller69** [Atlantiss/NetherwingBugtracker#3944]
[//]: # (Enclose links to things related to the bug using http://wowhead.com or any other TBC database.)
[//]: # (You can use screenshot ingame to visual the issue.)
[//]: # (Write your tickets according to the format:)
[//]: # ([Quest][Azuremyst Isle] Red Snapper - Very Tasty!)
[//]: # ([NPC] Magistrix Erona)
[//]: # ([Spell][Mage] Fireball)
[//]: # ([Npc][Drop] Ghostclaw Lynx)
[//]: # ([Web] Armory doesnt work)
[//]: # (To find server revision type `.server info` command in the game chat.)

**Description**: intimidating shout

**Current behaviour**:requires u to face the opponent, should be able to use it without seeing the enemy

**Expected behaviour**: should be able to use without facing the enemy

**Server Revision**:

**Comment by killablink** [comment]
No you need to face the enemy to use intimidating shout.

**Comment by wtRCH** [comment]
You need to face the enemy to use Intimidating Shout stun but other 5 enemies around you should flee (even behind you). It was reported earlier.
