### ISSUE TITLE
[NPC] Innkeeper Delaniel not selling goods

### ISSUE THREAD

**Issue by Martin322** [Atlantiss/NetherwingBugtracker#3945]
[//]: # (Enclose links to things related to the bug using http://wowhead.com or any other TBC database.)
[//]: # (You can use screenshot ingame to visual the issue.)
[//]: # (Write your tickets according to the format:)
[//]: # ([Quest][Azuremyst Isle] Red Snapper - Very Tasty!)
[//]: # ([NPC] Magistrix Erona)
[//]: # ([Spell][Mage] Fireball)
[//]: # ([Npc][Drop] Ghostclaw Lynx)
[//]: # ([Web] Armory doesnt work)
[//]: # (To find server revision type `.server info` command in the game chat.)

**Description**: Innkeeper Delaniel an NPC located in Eversong Woods in Falconwing Square inn is not selling food and drinks.

**Current behaviour**: She is not selling food and drinks.

**Expected behaviour**: She should sell food and drinks.

**Server Revision**: 

[https://www.wowhead.com/npc=15433/innkeeper-delaniel](url)

**Comment by Shanghi** [comment]
She begins selling things in patch 2.3.

**Comment by Martin322** [comment]
Thank you for the explanation, next time I will research more before posting.
