### ISSUE TITLE
2 vendors missing in night elf starting area, leather armour vendor and general goods vendor.

### ISSUE THREAD

**Issue by MMo-Reject** [Atlantiss/NetherwingBugtracker#3948]
[//]: # (Enclose links to things related to the bug using http://wowhead.com or any other TBC database.)
[//]: # (You can use screenshot ingame to visual the issue.)
[//]: # (Write your tickets according to the format:)
[//]: # ([Quest][Azuremyst Isle] Red Snapper - Very Tasty!)
[//]: # ([NPC] Magistrix Erona)
[//]: # ([Spell][Mage] Fireball)
[//]: # ([Npc][Drop] Ghostclaw Lynx)
[//]: # ([Web] Armory doesnt work)
[//]: # (To find server revision type `.server info` command in the game chat.)

**Description**: 

**Current behaviour**:

**Expected behaviour**: 

**Server Revision**:

**Comment by Evolvee** [comment]
any links? wowhead? names of those npcs?

**Comment by Manaci** [comment]
Leather armor merchant is there, can't find any info on a general goods vendor there though
