### ISSUE TITLE
Client freeze causing death and spawn at flight master

### ISSUE THREAD

**Issue by heffokrg** [Atlantiss/NetherwingBugtracker#3949]
Random occurrence causing client to freeze. If you force shut down the client you'll spawn at the flight master you last used and you'll be dead. If you were in a party you've also left it. Happened to me twice in 10-15 hours of play.

**Comment by wtRCH** [comment]
Were you in combat? @heffokrg

**Comment by heffokrg** [comment]
Yes. I was in combat both times. It happened to me once yesterday as well but this time I tried waiting it out and it worked fine. What I noticed however when the client does freeze there's always a Rogue in combat on my screen as well. No clue if it's related.
