### ISSUE TITLE
The Vile Reef

### ISSUE THREAD

**Issue by AWIDIUS** [Atlantiss/NetherwingBugtracker#3950]
Hello, in Stranglethorn Valley in Vile Reef location I've got Fatigue, which is more likely to have out of continent, its quite near to the land, just next to Murloc nest in such a Valley in there. And the Murlocs in there have badly set evade mechanism, where mobs in certain situations doesnt count that they can swim, meaning that if Im just "standing" on the textures of ruins of the underwater city and I pull 1 mob right next to me on the ground (diagonaly 10yd), its more likely to evade in 2 secs bcs it couldnt find path up to me.

**Comment by Tenoutoften** [comment]
I believe this is an mmap issue & we would need evidence on fatigue zones...

**Comment by AWIDIUS** [comment]
https://imgur.com/a/2f1iuBD Its really close to the land ... This would happen if you'd just swim from Grom'gol base camp to the island where elementals are

**Comment by wtRCH** [comment]
Blizzlike. Look how the water changes.
