### ISSUE TITLE
[NPC] Marsh Inkspewer

### ISSUE THREAD

**Issue by bekonja** [Atlantiss/NetherwingBugtracker#3951]
[//]: # (Enclose links to things related to the bug using http://wowhead.com or any other TBC database.)
[//]: # (You can use screenshot ingame to visual the issue.)
[//]: # (Write your tickets according to the format:)
[//]: # ([Quest][Azuremyst Isle] Red Snapper - Very Tasty!)
[//]: # ([NPC] Magistrix Erona)
[//]: # ([Spell][Mage] Fireball)
[//]: # ([Npc][Drop] Ghostclaw Lynx)
[//]: # ([Web] Armory doesnt work)
[//]: # (To find server revision type `.server info` command in the game chat.)

**Description**: 
https://db.excalibur.ws/?quest=1426

https://db.excalibur.ws/?npc=750
https://db.excalibur.ws/?npc=751
https://db.excalibur.ws/?npc=747
https://db.excalibur.ws/?npc=752

**Current behaviour**: No murlocs other than Marsh Inkspewers spawn in Swamp of Sorrows. That makes Threat From the Sea quest imposible to complete.

**Expected behaviour**:  Either make all spawns sharable - any type of murloc can spawn on any murloc spot, or set fixed spawn points like on other pservers.

**Server Revision**: 2603

**Comment by Tenoutoften** [comment]
Duplicate, known issue: https://github.com/Atlantiss/NetherwingBugtracker/issues/1433
