### ISSUE TITLE
[Elwynn Forest][NPC] Wolf type

### ISSUE THREAD

**Issue by iwcham1979** [Atlantiss/NetherwingBugtracker#3953]
While doing the Quest "Protect the Frontier" in Elwyn forest, I notice that ALL the wolves are "Prowlers" where they should be very few of them...

**Comment by wtRCH** [comment]
@aresbrutus

**Comment by The14me** [comment]
According to this map its not an issue
https://classic.wowhead.com/npc=118/prowler
Rev.3482 can be closed.

**Comment by Tereneckla** [comment]
That's not really a proof.
But
https://youtu.be/QAqweoOsakM
https://youtu.be/XSSNXOKn8ow

lots of Prowlers
