### ISSUE TITLE
[Quest] Chen's Empty Keg - Doesn't give EXP

### ISSUE THREAD

**Issue by nullfoxh** [Atlantiss/NetherwingBugtracker#3954]
https://vanilla-twinhead.twinstar.cz/?quest=822

Gave me no EXP.

Was gonna post screenshots but server crashed before I could take them.

**Comment by Evolvee** [comment]
its not supposed to give any xp
https://www.wowhead.com/quest=822/chens-empty-keg#comments:id=303018
https://www.wowhead.com/quest=822/chens-empty-keg#comments:id=188012
https://www.wowhead.com/quest=822/chens-empty-keg#comments:id=217228

**Comment by nullfoxh** [comment]
My bad!
