### ISSUE TITLE
Summon bug

### ISSUE THREAD

**Issue by tbc123** [Atlantiss/NetherwingBugtracker#3955]
cheak the summon wlock and stone his broken can't summon from kalimdor on estern kingdoms

**Comment by Nixazzar** [comment]
yes, agreed, had same issuses, came here to post, and saw this post! Summons dont work on sum stones, say's "no target" for people trying to summon.

**Comment by nullfoxh** [comment]
@Nixazzar Summoning stone at WC worked fine earlier today for my group at least.

**Comment by Saladin710** [comment]
Just to add, tried to use Stone at SFK. Worked for folks who were on this continent from Vanilla, but would not summon our 2 party members that were in Ghostlands. GL is on the same continent, but is part of the new exp. Said "Invalid Target". Also would not summon with a lock portal

**Comment by jhuerta13** [comment]
Ghostlands is located on Eastern Kingdom by looking at the map, but they are actually located on Outland just as Isle of Quel'Danas and Azuremist Isles are, therefore it is safe to say that these places are located in a different "continent" from kalimdor/EK.

Evidence:
https://youtu.be/9rFE8HzIijY

In a SM run we weren't able to summon party members that were in kalimdor places by using either summ stone or wlock summ, showing the same "no target" message, but as soon as they got into the zeppelin and arrive EK we could get them summoned.

**Comment by Extrabeefy** [comment]
Having same issue with client saying No Target when attempting to summon someone to DM who is on Kalimdor.

**Comment by Manaci** [comment]
Fixed
