### ISSUE TITLE
[Zangarmarsh][Quest]As the Crow Flies#9718 doesn't give quest credit

### ISSUE THREAD

**Issue by Tenoutoften** [Atlantiss/NetherwingBugtracker#3956]
**Description/Current behaviour**: 
[[Quest]As the Crow Flies#9718](https://www.wowhead.com/quest=9718/as-the-crow-flies) doesn't give quest credit on landing.

It is very important that this quest works, without completion [[item]Drain Schematics#24330](https://www.wowhead.com/item=24330/drain-schematics) wont be able to drop for players.

[[Quest]Drain Schematics#9731](https://www.wowhead.com/quest=9731/drain-schematics) opens a [Chain of 4 quests](https://db.excalibur.ws/?quest=9724) in total 6 quests are blocked because of this.

![](https://i.gyazo.com/23f66f00f8dee9f1ca91ed76e7bf24b1.png)

**Server Revision**: 
2603

**Comment by Evolvee** [comment]
https://github.com/Atlantiss/NetherwingBugtracker/issues/4019#issuecomment-453277201

**Comment by Tenoutoften** [comment]
Resolved!
