### ISSUE TITLE
WC Disciple of Naralex wouldn't move after serpent summoning circle 

### ISSUE THREAD

**Issue by KatCross** [Atlantiss/NetherwingBugtracker#3959]
[//]: # (Enclose links to things related to the bug using http://wowhead.com or any other TBC database.)
[//]: # (You can use screenshot ingame to visual the issue.)
[//]: # (Write your tickets according to the format:)
[//]: # ([Quest][Azuremyst Isle] Red Snapper - Very Tasty!)
[//]: # ([NPC] Magistrix Erona)
[//]: # ([Spell][Mage] Fireball)
[//]: # ([Npc][Drop] Ghostclaw Lynx)
[//]: # ([Web] Armory doesnt work)
[//]: # (To find server revision type `.server info` command in the game chat.)

**Description**: After escorting the Disciple of Naralex to the first summoning circle where he cleanses the caverns of the spirits, the disciple took a few steps towards the bridge, started helping us fight the raptor on the bridge, and then quit responding after we killed the raptor. We then tried aggro-ing other mobs to him and then dragging him to the chamber where Naralex is sleeping, but he still did nothing. 

**Current behaviour**: Freezes after getting in combat once summoning circle is cleansed

**Expected behaviour**: guides you to Naralex's chamber and then starts the final rp even/boss encounter.

**Server Revision**:

**Comment by Godmatik** [comment]
Rev 4016 - Unable to reproduce
Tried twice using the exact steps outlined above, the disciple never got stuck.
