### ISSUE TITLE
[NPC] Razormane Seer (3458)

### ISSUE THREAD

**Issue by Kentamentiu** [Atlantiss/NetherwingBugtracker#396]
[//]: # (Enclose links to things related to the bug using http://wowhead.com or any other TBC database.)
[//]: # (You can use screenshot ingame to visual the issue.)
[//]: # (Write your tickets according to the format:)
[//]: # ([Quest][Azuremyst Isle] Red Snapper - Very Tasty!)
[//]: # ([NPC] Magistrix Erona)
[//]: # ([Spell][Mage] Fireball)
[//]: # ([Npc][Drop] Ghostclaw Lynx)
[//]: # ([Web] Armory doesnt work)

**Description**: 
He replaces Healing Ward instantly with searing totem

**Current behaviour**:
When his hp drops low enough, he casts Healing Ward. The very next moment, he always replaces it by casting Searing Totem

**Expected behaviour**: 
Leave Healing Ward up to assist the mob in combat

**Server Revision**: 
2040

**Comment by Easyfraggy** [comment]
Should probably be able to have multiple totems up at the same time.

**Comment by The14me** [comment]
Still issue in 3441. Additional from time to time use Alli version of Searing totem.

**Comment by Wolffenstein** [comment]
Those totems share the same totem slot. Blizzlike.
