### ISSUE TITLE
[Quest] Protect Kanati Greycloud ID:4966 

### ISSUE THREAD

**Issue by Kristoferhh** [Atlantiss/NetherwingBugtracker#3960]
**Description**: The "Protect Kanati Greycloud quest is not working as intended

**Current behaviour**: As soon as you accept the quest, it gets instantly completed and you can turn it in without any adds spawning.

**Expected behaviour**: According to the quest, adds are supposed to spawn and you need to protect the quest giver. And in the text quest when turning it in he thanks you for protecting him.

**Server Revision**: 2604

**Comment by Ceago** [comment]
As of server rev 2605 this is still not working.

**Comment by Evolvee** [comment]
rev 2719

**Comment by linxz1** [comment]
Request reopen. As soon as someone fails/completes he enters a state where another cant turn in or accept a quest.

**Comment by Evolvee** [comment]
rev 2827
