### ISSUE TITLE
[Core] Different location after logout -> login

### ISSUE THREAD

**Issue by pesky89** [Atlantiss/NetherwingBugtracker#3961]
**Description**: 
I logged out in Rachet, where my inn was, and at the next login, i was in Booty Bay.  
Another guy said in chat he logged out in Orgirmmar, but was in UC at his next login.

**Current behaviour**:
I logged out in Rachet, where my inn was, and at the next login, i was in Booty Bay.  
Another guy said in chat he logged out in Orgirmmar, but was in UC at his next login.

**Expected behaviour**: 
Should retain the logout position.  
**Server Revision**: 
2604

**Comment by wtRCH** [comment]
Player saving issue @Wolffenstein

**Comment by pesky89** [comment]
proof : https://clips.twitch.tv/FrailMagnificentQuailANELE

**Comment by Anselm123** [comment]
I've had this a few times today. Always seem to appear in a flight path when it happens and die to fall damage

**Comment by Tereneckla** [comment]
Fixed
