### ISSUE TITLE
Moving camera with rmb + sitting to eat/drink

### ISSUE THREAD

**Issue by blinkkurwa** [Atlantiss/NetherwingBugtracker#3962]
[//]: # (Enclose links to things related to the bug using http://wowhead.com or any other TBC database.)
[//]: # (You can use screenshot ingame to visual the issue.)
[//]: # (Write your tickets according to the format:)
[//]: # ([Quest][Azuremyst Isle] Red Snapper - Very Tasty!)
[//]: # ([NPC] Magistrix Erona)
[//]: # ([Spell][Mage] Fireball)
[//]: # ([Npc][Drop] Ghostclaw Lynx)
[//]: # ([Web] Armory doesnt work)
[//]: # (To find server revision type `.server info` command in the game chat.)

**Description**: 
Moving camera with pressed right mouse button + using food or drinks simply wastes it for nothing. It doesn't matter if it made your character to slide on his ass or if you used it when your camera was right in the center of the direction your character was looking.
Somewhat annoying because if you don't constantly check your buffs, you might notice it pretty late that you wasn't drinking/eating anything whole this time, which can lead to a premature change of surrounding scenery.

https://youtu.be/u4H7xFwqCXk

**Server Revision**: 2604

**Comment by nullfoxh** [comment]
Moving mouse while holding RMB turns your character, shouldn't that break the eating or am I not understanding this correctly?

**Comment by kemotix** [comment]
Use LMB to move camera. RMB is for character.

**Comment by blinkkurwa** [comment]
>Moving mouse while holding RMB turns your character, shouldn't that break the eating or am I not understanding this correctly?

No, it didn't on retail: https://youtu.be/QyTyNaiEJKs?t=788 13:09, 16:31, 
nor this is the cause there: https://youtu.be/hEv3WAVSQjc

Worth mentioning also that, as you can see on Hydra's movie, the character stops adjusting his position as soon as he sits on the ground, while here you keep sliding until your character will be facing towards the direction your camera was aimed at the moment when you began to drink/eat.

**Comment by Manaci** [comment]
Fixed
