### ISSUE TITLE
[Ashenvale][NPC] Foulweald Furblogs

### ISSUE THREAD

**Issue by iYi** [Atlantiss/NetherwingBugtracker#3963]
NPC's Foulweald Warrior Shaman etc
Behavior: Mobs apply Disease while sapped on stealthed target, sap fade and the mob reset his combat state
Expected behavior: not applying the diseases while sapped at all / reset combat

**Comment by wtRCH** [comment]
Please use proper title next time.

**Comment by Tereneckla** [comment]
https://classic.wowhead.com/spell=6823/corrupted-intellect-passive
https://classic.wowhead.com/spell=6818/corrupted-intellect

It's an aura that pulses periodically to apply the disease.

I don't see why it should be different.
