### ISSUE TITLE
[Ashenvale][Q] Vorsha the Lasher

### ISSUE THREAD

**Issue by tsu-1** [Atlantiss/NetherwingBugtracker#3964]
[//]: # (Enclose links to things related to the bug using http://wowhead.com or any other TBC database.)
[//]: # (You can use screenshot ingame to visual the issue.)
[//]: # (Write your tickets according to the format:)
[//]: # ([Quest][Azuremyst Isle] Red Snapper - Very Tasty!)
[//]: # ([NPC] Magistrix Erona)
[//]: # ([Spell][Mage] Fireball)
[//]: # ([Npc][Drop] Ghostclaw Lynx)
[//]: # ([Web] Armory doesnt work)
[//]: # (To find server revision type `.server info` command in the game chat.)

**Description**: Muglash incorrectly following his path and falling through.

**Current behaviour**: When Muglash reach the water, he should swim up top rather than on the bottom of the sea (maps related). Also, there is a small place near the brazier where he falls through the floor (luckily comes up).

**Expected behaviour**: Muglash should swim on the water surface not underneeth and shouldn't fall under textures in one spot.

**Server Revision**: 2604

**Comment by tsuone** [comment]
Bump

**Comment by The14me** [comment]
Rev.3482 still an issue (At least swimming on the bottom)

**Comment by Godmatik** [comment]
Rev 4015 no longer an issue - the pathing was just fine, and did not fall through when reaching the island either.

Probably fixed when Wolf did his pathing core fixes last year
