### ISSUE TITLE
Delay before combat drops when NPC resets

### ISSUE THREAD

**Issue by femdead** [Atlantiss/NetherwingBugtracker#3965]
Current behaviour: 
Run from a mob, it eventually drops aggro, delay of about 5 seconds, then you are out of combat

Expected behavour:
Mob de-aggo and combat drop happen at the same time

**Comment by Drayo** [comment]
For me it's always between 0.5 and 2 seconds, never anything close to 5 seconds. Seems normal to me.

Can probably be closed.
