### ISSUE TITLE
[Shaman] Mana totem should not aggro

### ISSUE THREAD

**Issue by pesky89** [Atlantiss/NetherwingBugtracker#3967]
**Description**: 
If i body pull a mob and i have mana totem down, the mob will distroy the mana totem.  
Even when i attack the mob with low damage, mana totem is still distoryed by mob.  

**Current behaviour**:
If i body pull a mob and i have mana totem down, the mob will distroy the mana totem.  
Even when i attack the mob with low damage, mana totem is still distoryed by mob.  

**Expected behaviour**: 
Mana totem should not give aggro, even when i body pull with character.  

ps: is was working the other days  

**Server Revision**: 
2604

**Comment by Geigerkind** [comment]
Does not happen to me recently anymore
