### ISSUE TITLE
[Outlands][Loot]Humanoid  NPCs below lvl 64 have way to low Netherweave & Runecloth drop chance

### ISSUE THREAD

**Issue by Tenoutoften** [Atlantiss/NetherwingBugtracker#3968]
**Description**: 
Mobs below and including level 64(Zangarmarsh, Hellfire Peninsula, Terokkar Forest)
Two of our players have gone through these zones and together gotten just about 1 stack of netherweave cloth.

http://web.archive.org/web/20080326225047/http://thottbot.com:80/c18952

[[Item]Netherweave Cloth#21877](https://www.wowhead.com/item=21877/netherweave-cloth)
[[Item]Runecloth#14047](https://www.wowhead.com/item=14047/runecloth)

![](https://i.gyazo.com/4da73192ab032e9a00a4a92dcd279c54.png)

**Current behaviour**:
Very low drop chance 0-2%?

**Expected behaviour**: 
~32%

**Server Revision**: 
2603

**Comment by Tereneckla** [comment]
Fixed
