### ISSUE TITLE
[Proffesions] First aid sometimes gives 0 hp

### ISSUE THREAD

**Issue by pesky89** [Atlantiss/NetherwingBugtracker#3969]
**Description**: 
I noticed that sometimes first aid gives 0 hp on last tick
**Current behaviour**:
I noticed that sometimes first aid gives 0 hp on last tick. Happened several times. Could not find a way to reproduce  
![image](https://user-images.githubusercontent.com/26849796/50887805-d0f64e80-13fc-11e9-8723-d6ba2fcd0862.png)

PS: i was not full hp.

**Expected behaviour**: 
Should not give 0 hp
**Server Revision**: 
2604

**Comment by teddys** [comment]
has to do with spell batching I guess .. happens only on the last tick

**Comment by Mikik3jr** [comment]
![image](https://user-images.githubusercontent.com/43505031/51425974-ff85dd80-1be3-11e9-968d-6ba90670cf28.png)

**Comment by AWIDIUS** [comment]
![](https://i.imgur.com/Y3GaAli.jpg)

**Comment by Kantrul** [comment]
Still happening. pls fix

**Comment by Godmatik** [comment]
Must have been fixed, closing
