### ISSUE TITLE
No update on health bar on healing other

### ISSUE THREAD

**Issue by ttghnw** [Atlantiss/NetherwingBugtracker#397]
[//]: # (Enclose links to things related to the bug using http://wowhead.com or any other TBC database.)
[//]: # (You can use screenshot ingame to visual the issue.)
[//]: # (Write your tickets according to the format:)
[//]: # ([Quest][Azuremyst Isle] Red Snapper - Very Tasty!)
[//]: # ([NPC] Magistrix Erona)
[//]: # ([Spell][Mage] Fireball)
[//]: # ([Npc][Drop] Ghostclaw Lynx)
[//]: # ([Web] Armory doesnt work)

**Description**: 

**Current behaviour**:
Healing the player displays on combat log, player gets healed but the health bar does not reflect the actual healing.
**Expected behaviour**: 
Should do so. This happened on various situations.

![wowscrnshot_092418_174220](https://user-images.githubusercontent.com/43508698/45965833-7558ae80-c021-11e8-8043-c1d7e100cc27.jpg)
![wowscrnshot_092418_174221](https://user-images.githubusercontent.com/43508698/45965834-7558ae80-c021-11e8-96d3-4490aea315f0.jpg)
![wowscrnshot_092418_174228](https://user-images.githubusercontent.com/43508698/45965835-7558ae80-c021-11e8-8343-508efd0c0f19.jpg)
![wowscrnshot_092418_174233](https://user-images.githubusercontent.com/43508698/45965836-7558ae80-c021-11e8-9298-dfd128f70908.jpg)
![wowscrnshot_092418_174323](https://user-images.githubusercontent.com/43508698/45965837-7558ae80-c021-11e8-8d2b-14ab09527a41.jpg)

**Server Revision**:

**Comment by wtRCH** [comment]
@Wolffenstein

**Comment by Sinyr** [comment]
This could be related to the issue I was having about party HP. At around that level her max HP is somewhere around 250-300, so this is probably 100/X instead of 100% (My issue: #175 )

**Comment by Wolffenstein** [comment]
Fixed in rev 2211.
