### ISSUE TITLE
Seal of Righteousness aura sometimes fails to apply the effects.

### ISSUE THREAD

**Issue by svepi123** [Atlantiss/NetherwingBugtracker#3970]
**Description**: 
Seal of Righteousness sometimes fail to deal dmg while the 30sec aura is in effect.

**Current behaviour**:
Fails to deal damage sometimes not deal damage (1 hit might fail, the others might register the dmg) while aura is up, fixing it requires recasting the Seal BUT sometime is requires more than once to fix it.

**Expected behaviour**: 
Upon casting it should guarantee a small portion of Holy Damage based on your weapon's speed + seal Rank. 

**Server Revision**: 
2604

**Comment by Anselm123** [comment]
Can confirm still an issue and happens with judgement sometimes. Auto/spell lands no damage. No resist or miss it just doesn't happen

**Comment by Wolffenstein** [comment]
Fixed in rev 2743.
