### ISSUE TITLE
[NPC][PATHING] Fozruk & Ads

### ISSUE THREAD

**Issue by Snowie493** [Atlantiss/NetherwingBugtracker#3974]
**Description**: 
![image](https://user-images.githubusercontent.com/1365540/50891194-0b132080-13fc-11e9-8110-69ac16ae2803.png)

**Current behaviour**:
See image above, Pathing is below ground.

**Expected behaviour**: 

**Server Revision**: 
2604 (date: 9/1-2019)

**Comment by The14me** [comment]
Rev.3482 Not an issue anymore.
