### ISSUE TITLE
[TOTEM][AGGRO][Spell][Shaman]

### ISSUE THREAD

**Issue by syphex97** [Atlantiss/NetherwingBugtracker#3975]
[//]: # (Enclose links to things related to the bug using http://wowhead.com or any other TBC database.)
[//]: # (You can use screenshot ingame to visual the issue.)
[//]: # (Write your tickets according to the format:)
[//]: # ([Quest][Azuremyst Isle] Red Snapper - Very Tasty!)
[//]: # ([NPC] Magistrix Erona)
[//]: # ([Spell][Mage] Fireball)
[//]: # ([Npc][Drop] Ghostclaw Lynx)
[//]: # ([Web] Armory doesnt work)
[//]: # (To find server revision type `.server info` command in the game chat.)

**Description**: 
Mobs randomly destroy totems when they shouldn't, Totems randomly Aggro mobs as well, as in attacking anything that is attack able. If you heal yourself you automatically get aggro from anyone and anything. 

I.E, Stone claw totem Does not aggro the npc if you have done any damage to them, this includes ur Searing Totem. If you heal yourself while the Stoneclaw totem has aggro you take the aggro from the mobs.

Stoneclaw totem does not stun the enemy either on hit with a 50% chance. tested this on a low level mob and out of 5 totems it did not stun a single time.

**Current behaviour**:
Aggro is non functional and totem randomly aggro/attack mobs that you havent aggroed or is neutral.
StoneClaw Totem does not stun nor aggro any mobs that has taken damage, Any healing you apply to yourself or party member overtakens the aggro.

Healing yourself when a Party Member has aggro overtakes their aggro and gives you aggro.

Mobs Randomly Destroy  totems that has been put out and does not, face, aggro or even use their attack speed to damage the totem.

This happens to every single totem as well,  the mobs randomly destroy it.

**Expected behaviour**: 
Totems should only attack mobs that are Hostile as if a pet were in defensive mode. And Should NEVER attack a neutral target unless you do.

Stoneclaw Totem Should have a 50% chance to stun the target on hit and taunt any enemy within a range of 8 yards. Totem should also have the ability to taunt an enemy no matter the amount of damage or aggro they have taken from a normal target.

Healing yourself or anyone outside of the target who has aggro should not overlap or have you take any threat the target that has aggro. 

Mobs should not randomly engage Totems unless they are the first ones in range of the hostile mob.

However in the middle of fights they walk up and destroy the totem or if you place the totem down.
This happens to all totems, however some are more obvious than others, in this case, Mana Totem, Searing Totem, Healing Totem & EarthBind Totem, And the mobs completely Ignore stoneclaw totem unless it is the first to taunt an undamaged enemy or are the first to throw a effect at the npc.

**Server Revision**:

**Comment by pesky89** [comment]
totem aggro fixed

**Comment by The14me** [comment]
Stun/taunt issue is fixed too. (aggro neutral mob's is not true for this totem). Rev 3441.
Can be closed.
