### ISSUE TITLE
Bug: Logged out somewhere in wilderness, logged in at flight master.

### ISSUE THREAD

**Issue by IGNPoint** [Atlantiss/NetherwingBugtracker#3977]
Not sure if this is known already,, a GM told me to report it.

https://gfycat.com/CalculatingPolishedFluke

The char in the GIF is not me, but essentially same thing happened to me in Hillsbrad. I got a green head, decided to log out and back in to save char incase of crash. Spawned at Flight master. I was at the time of log out near Dwarfs in the South easy.

**Comment by Greytt** [comment]
I have logged out at zeppeling serveral times and it puts me back at orgrimmar flight master. Rev 2604

**Comment by narayagh** [comment]
Logged out in Darnassus in front of the bank, logged in **dead** in Rut'theran Village.

**Comment by The14me** [comment]
Duplicate
