### ISSUE TITLE
Rogue Distract - Lightning sheild.

### ISSUE THREAD

**Issue by Greytt** [Atlantiss/NetherwingBugtracker#3978]
[//]: # (Enclose links to things related to the bug using http://wowhead.com or any other TBC database.)
[//]: # (You can use screenshot ingame to visual the issue.)
[//]: # (Write your tickets according to the format:)
[//]: # ([Quest][Azuremyst Isle] Red Snapper - Very Tasty!)
[//]: # ([NPC] Magistrix Erona)
[//]: # ([Spell][Mage] Fireball)
[//]: # ([Npc][Drop] Ghostclaw Lynx)
[//]: # ([Web] Armory doesnt work)
[//]: # (To find server revision type `.server info` command in the game chat.)

**Description**: 

**Current behaviour**: [Spell][Rogue] Distract trigger [Spell][Shaman] Lightning Shield.

**Expected behaviour**:  To not do that.

**Server Revision**: 2604

**Comment by nullfoxh** [comment]
Also proccs off Sap, breaking rogues stealth ofc.

**Comment by Wolffenstein** [comment]
Fixed in rev 2658.
