### ISSUE TITLE
[NPC][Spell] Dalaran Shield Guar

### ISSUE THREAD

**Issue by tsuone** [Atlantiss/NetherwingBugtracker#3979]
[//]: # (Enclose links to things related to the bug using http://wowhead.com or any other TBC database.)
[//]: # (You can use screenshot ingame to visual the issue.)
[//]: # (Write your tickets according to the format:)
[//]: # ([Quest][Azuremyst Isle] Red Snapper - Very Tasty!)
[//]: # ([NPC] Magistrix Erona)
[//]: # ([Spell][Mage] Fireball)
[//]: # ([Npc][Drop] Ghostclaw Lynx)
[//]: # ([Web] Armory doesnt work)
[//]: # (To find server revision type `.server info` command in the game chat.)

**Description**: Dalaran Shield Guard spell Violent Shield Effect not working correctly.

**Current behaviour**: Violent Shield Effect doesn't do it on hit melee damage to attackers.

**Expected behaviour**: Violent Shield Effect should strike attacker with 85 damage hit.

**Server Revision**: 2604

**Comment by tsuone** [comment]
Bump

**Comment by Wolffenstein** [comment]
![obraz](https://user-images.githubusercontent.com/1576644/80870366-519e2580-8ca6-11ea-81f7-1ac716177f9f.png)

Works fine.
