### ISSUE TITLE
Lag/Batch?

### ISSUE THREAD

**Issue by ttghnw** [Atlantiss/NetherwingBugtracker#398]
[//]: # (Enclose links to things related to the bug using http://wowhead.com or any other TBC database.)
[//]: # (You can use screenshot ingame to visual the issue.)
[//]: # (Write your tickets according to the format:)
[//]: # ([Quest][Azuremyst Isle] Red Snapper - Very Tasty!)
[//]: # ([NPC] Magistrix Erona)
[//]: # ([Spell][Mage] Fireball)
[//]: # ([Npc][Drop] Ghostclaw Lynx)
[//]: # ([Web] Armory doesnt work)

**Description**: 
![wowscrnshot_092418_174937](https://user-images.githubusercontent.com/43508698/45966150-3c6d0980-c022-11e8-8e65-2cef5dbd4339.jpg)

**Current behaviour**:
Healed by LoH - dead anyway
**Expected behaviour**: 
I don't really know but will post so you guys can check if this is WAIntended - please see combat log below
![wowscrnshot_092418_174937](https://user-images.githubusercontent.com/43508698/45966188-527aca00-c022-11e8-9d7f-7c392a2f4b38.jpg)

**Server Revision**:

**Comment by wtRCH** [comment]
@Wolffenstein

**Comment by The14me** [comment]
cant reproduce.Please re-open if happen again.
