### ISSUE TITLE
Rough Bronze Shoulders cannot  be disenchanted.

### ISSUE THREAD

**Issue by Lithits** [Atlantiss/NetherwingBugtracker#3980]
http://db.hellfire-tbc.com/?item=3480#disenchanting
Here it says that it can be disenchanted. It is a green item, so yeah.
But right now I can't disenchanted them.

**Comment by Tenoutoften** [comment]
Working as intended! In patch 2.0 these shoulders are **not* green quality. Please clear your cache.
http://web.archive.org/web/20071123113445/http://thottbot.com:80/i3480
![](https://i.gyazo.com/617f31bbe0705ec40a5001aadaf07836.png)


Go into your wow folder and delete Cache
![](https://i.gyazo.com/e0f918c368830b49ab9f8a09403f4220.png)

**Comment by The14me** [comment]
What ''Tenoutoften'' say.
