### ISSUE TITLE
[QUEST] tiara of the deep

### ISSUE THREAD

**Issue by Dekirayne** [Atlantiss/NetherwingBugtracker#3981]
**Description**: 
tiara of the deep quest mob didn't drop quest loot
**Current behaviour**:
when you kill Hydromancer Velratha she drops nothing
**Expected behaviour**: 
she should drop tiara of the deep
**Server Revision**:

**Comment by Jalapan** [comment]
dropped for me. maybe check drop %? should be 100 if player has quest Tiara of the deep

**Comment by maxturtlesc2** [comment]
It didn't drop anything for my group either, the mob should drop Second Mosh'aru Tablet and Tiara of the Deep.

**Comment by Easyfraggy** [comment]
she dropped both quest items for me.

**Comment by Godmatik** [comment]
Didn't drop for us either

**Comment by Tereneckla** [comment]
Weegli Blastfuse likely did more than 50% of the damage
