### ISSUE TITLE
Execute not doing anything sometimes

### ISSUE THREAD

**Issue by femdead** [Atlantiss/NetherwingBugtracker#3982]
Hard to tell but, occasionally when you use execute, it won't have any effect (no rage cost, animation, noise, no dodge/miss, no damage, no nothing) besides putting you on GCD

**Comment by eunuck1** [comment]
Can confirm this, this is pretty major in terms of warrior dps. It also seems to be pretty consistent when you are really close to a target

**Comment by liek0r** [comment]
Yes, can confirm. Annoying.

**Comment by teddys** [comment]
2647 revision
still happening

**Comment by liek0r** [comment]
rev 2660, execute not working at all anymore

https://streamable.com/wkbtg

**Comment by liek0r** [comment]
@Wolffenstein please reopen

**Comment by liek0r** [comment]
This is still happening. rev 2691

@Wolffenstein reopen please.
