### ISSUE TITLE
[Core] Faction queue not working

### ISSUE THREAD

**Issue by pesky89** [Atlantiss/NetherwingBugtracker#3983]
**Description**: 
i noticed that faction queue is not working. There are more than 55%H and the queue is not implemented  
**Current behaviour**:
i noticed that faction queue is not working. There are more than 55%H and the queue is not implemented.  
Check this example: 3275 total players and 1875 horde players. This means 57.3% horde players.  
![image](https://user-images.githubusercontent.com/26849796/50906748-737af580-142e-11e9-999f-95b7fd6629fc.png)

**Expected behaviour**: 
Faction Queue should be popped at 55% horde players.  
**Server Revision**: 
2604

**Comment by wtRCH** [comment]
It's disabled.
