### ISSUE TITLE
Healing aggro bugged

### ISSUE THREAD

**Issue by Jalapan** [Atlantiss/NetherwingBugtracker#3984]
[//]: # (Enclose links to things related to the bug using http://wowhead.com or any other TBC database.)
[//]: # (You can use screenshot ingame to visual the issue.)
[//]: # (Write your tickets according to the format:)
[//]: # ([Quest][Azuremyst Isle] Red Snapper - Very Tasty!)
[//]: # ([NPC] Magistrix Erona)
[//]: # ([Spell][Mage] Fireball)
[//]: # ([Npc][Drop] Ghostclaw Lynx)
[//]: # ([Web] Armory doesnt work)
[//]: # (To find server revision type `.server info` command in the game chat.)

**Description**: 
Healing aggro is not working as it should, it is tweaked to high
**Current behaviour**:
when a player uses a healing spell or a potion or a healthstone they generate alot of aggro, more then they should
**Expected behaviour**: 
Should not give as much aggro as it does now, very easily reproducable if engage a mob and fight for awhile then a party member uses a heal or a pot you will see the healing aggro and its abnormaly high.

**Server Revision**:

**Comment by ircfelix** [comment]
Source?

**Comment by Jseay1313** [comment]
I've seen this with eating and drinking and power word shield thus far as well. Have had instances where the tank pulls with BE racial or ranged and the player eating/drinking takes agro, also mobs sitting on consecrate agroing a priest just for PW:S

**Comment by fantom8** [comment]
I have also experienced this on a Warlock. I have pulled off my pet when Omen says I'm still below it in threat, let alone at 110% or 130% that should be required.

Happens with abilities that heal. Easy to verify this yourselves simply by healing with Omen active.

**Comment by Jalapan** [comment]
I agree!
You dont have a pic of the omen threst so devs can fix it?😄

**Comment by Drayo** [comment]
I tested Potions and Healthstone. They generate **exactly** the expected amount of threat and properly split among multiple mobs.

Can be closed.
