### ISSUE TITLE
Paladin Illumination talent - should offer 100% mana return. currently wrong value (patch 2.1+)

### ISSUE THREAD

**Issue by Jalapan** [Atlantiss/NetherwingBugtracker#3985]
[//]: # (Enclose links to things related to the bug using http://wowhead.com or any other TBC database.)
[//]: # (You can use screenshot ingame to visual the issue.)
[//]: # (Write your tickets according to the format:)
[//]: # ([Quest][Azuremyst Isle] Red Snapper - Very Tasty!)
[//]: # ([NPC] Magistrix Erona)
[//]: # ([Spell][Mage] Fireball)
[//]: # ([Npc][Drop] Ghostclaw Lynx)
[//]: # ([Web] Armory doesnt work)
[//]: # (To find server revision type `.server info` command in the game chat.)

Before Patch 2.1, the Illumination talent offered a 100% mana return. However, it was nerfed to 60% and thus changed the stat priority for Paladins in some people's opinions. Some remain adamant that even despite the nerf, stacking spell crit is better for longetivity because even without the 100% mana return it is more efficient than a constant mana per 5 second (MP5) bonus. Others argue that since it does not return the full mana cost you will burn through your mana much more quickly using Holy Light and thus MP5 is the best way to overcome this nerf.

Since we play patch 2.0 shouldnt this be changed?

**Comment by ircfelix** [comment]
Talents are 2.4.3 on netherwing, since they are client-based and hard to change.

**Comment by Evolvee** [comment]
player spells and talent mechanics are 2.4.3

if there is any problem with it still, feel free to reopen
