### ISSUE TITLE
Quest: Gauging the Resonant Frequency bugged

### ISSUE THREAD

**Issue by Jalapan** [Atlantiss/NetherwingBugtracker#3986]
[//]: # (Enclose links to things related to the bug using http://wowhead.com or any other TBC database.)
[//]: # (You can use screenshot ingame to visual the issue.)
[//]: # (Write your tickets according to the format:)
[//]: # ([Quest][Azuremyst Isle] Red Snapper - Very Tasty!)
[//]: # ([NPC] Magistrix Erona)
[//]: # ([Spell][Mage] Fireball)
[//]: # ([Npc][Drop] Ghostclaw Lynx)
[//]: # ([Web] Armory doesnt work)
[//]: # (To find server revision type `.server info` command in the game chat.)

Quest: Gauging the Resonant Frequency bugged pillars not working as they should, you should place them as a star and get complete.

**Comment by The14me** [comment]
Need some proof.

**Comment by The14me** [comment]
Rev.3482 still no proof or any more info about that issue.
Please close, if someone finds more info or complain about that can make another report.

**Comment by Tereneckla** [comment]
https://www.wowhead.com/quest=10594/gauging-the-resonant-frequency#screenshots

Any shape is fine as long as it has five beams in the middle (so most of the time you make a pentagon)
