### ISSUE TITLE
[Npc][Drop] Item Disappeared when trying to create inventory space to loot.

### ISSUE THREAD

**Issue by iB-Krypt** [Atlantiss/NetherwingBugtracker#3987]
[//]: # (Enclose links to things related to the bug using http://wowhead.com or any other TBC database.)
[//]: # (You can use screenshot ingame to visual the issue.)
https://imgur.com/a/Mc2Z24j
[//]: # (Write your tickets according to the format:)
[//]: # ([Quest][Azuremyst Isle] Red Snapper - Very Tasty!)
[//]: # ([NPC] Magistrix Erona)
[//]: # ([Spell][Mage] Fireball)
[//]: # ([Npc][Drop] Ghostclaw Lynx)
[//]: # ([Web] Armory doesnt work)
[//]: # (To find server revision type `.server info` command in the game chat.)

**Description**: 
I didn't have bag space for my item the first time i tried looting so i went to my bags and made space, as you can see. And when i went to loot it again the Boss just disappeared. Taking my item and no one was able to recover it.
**Current behaviour**:
Dungeon Boss corpses disappearing before all items are able to be looted.
**Expected behaviour**: 
Dungeon Boss corpses remaining until items are completely looted.
**Server Revision**: 
2604, but this happened a few nights ago.

**Comment by devo6969** [comment]
Tried to recreate, was unable to. Seems fixed

**Comment by BamboozleNW** [comment]
+ @devo6969 was there, seemed fine.
