### ISSUE TITLE
Incorrect number of characters on the server after deleting one of them

### ISSUE THREAD

**Issue by Chert-Nik** [Atlantiss/NetherwingBugtracker#3988]
[//]: # (Enclose links to things related to the bug using http://wowhead.com or any other TBC database.)
[//]: # (You can use screenshot ingame to visual the issue.)
[//]: # (Write your tickets according to the format:)
[//]: # ([Quest][Azuremyst Isle] Red Snapper - Very Tasty!)
[//]: # ([NPC] Magistrix Erona)
[//]: # ([Spell][Mage] Fireball)
[//]: # ([Npc][Drop] Ghostclaw Lynx)
[//]: # ([Web] Armory doesnt work)
[//]: # (To find server revision type `.server info` command in the game chat.)

**Description**: 
Created 3 characters, deleted one of them. Number of characters on realm selection menu is incorrect.
On the attached image you can see two characters in the background and the displayed number 3 in the server selection line.
<img width="1280" alt="screenshot_3" src="https://user-images.githubusercontent.com/22856631/50927976-61b74380-146a-11e9-9a91-82b29ef589b7.png">

**Current behaviour**:
On realms selection menu still shows 3 characters on the server.
**Expected behaviour**: 
Should show 2 characters on server.
**Server Revision**: 
2604 Branch: Master, Hash: 5baeb79b036f

**Comment by The14me** [comment]
Rev.3482 not an issue anymore.
