### ISSUE TITLE
[NPC] Gordunni Shaman [Quest][Feralas] they aren't anywhere but are needed for quest

### ISSUE THREAD

**Issue by efagrgagg** [Atlantiss/NetherwingBugtracker#3989]
[//]: # (Enclose links to things related to the bug using http://wowhead.com or any other TBC database.)
[//]: # (You can use screenshot ingame to visual the issue.)
[//]: # (Write your tickets according to the format:)
[//]: # ([Quest][Azuremyst Isle] Red Snapper - Very Tasty!)
[//]: # ([NPC] Magistrix Erona)
[//]: # ([Spell][Mage] Fireball)
[//]: # ([Npc][Drop] Ghostclaw Lynx)
[//]: # ([Web] Armory doesnt work)
[//]: # (To find server revision type `.server info` command in the game chat.)

**Description**:  ok so quest is https://www.wowhead.com/quest=2980/the-ogres-of-feralas and theres no Gordunni Shamans existing at all... on spots where those mobs should be theyre replaced by Battlemasters or Mage-Lords. quest requires 10 shaman kills, but i repeat they just dont exist anywhere.

**Current behaviour**: Gordunni Shaman dont exist

**Expected behaviour**: they should be somewhere

**Server Revision**: 2604

**Comment by efagrgagg** [comment]
update there are shamans but insanely scarce compared to 10 needed for kill quest. pretty sure mage-lords should be shamans and vice versa theres abundance of them.

**Comment by duzyizly** [comment]
respawn time of all ogres here = 10 min (ptr rev3390)
spawn is randomized.
