### ISSUE TITLE
[Quest] Perfect Yeti Hide

### ISSUE THREAD

**Issue by efagrgagg** [Atlantiss/NetherwingBugtracker#3992]
[//]: # (Enclose links to things related to the bug using http://wowhead.com or any other TBC database.)
[//]: # (You can use screenshot ingame to visual the issue.)
[//]: # (Write your tickets according to the format:)
[//]: # ([Quest][Azuremyst Isle] Red Snapper - Very Tasty!)
[//]: # ([NPC] Magistrix Erona)
[//]: # ([Spell][Mage] Fireball)
[//]: # ([Npc][Drop] Ghostclaw Lynx)
[//]: # ([Web] Armory doesnt work)
[//]: # (To find server revision type `.server info` command in the game chat.)

**Description**: https://www.wowhead.com/quest=7738/perfect-yeti-hide Doesn't grant any xp upon completion/turning in.

**Current behaviour**:

**Expected behaviour**: 

**Server Revision**: 2604

**Comment by Evolvee** [comment]
it was already reported  https://github.com/Atlantiss/NetherwingBugtracker/issues/3920#issuecomment-452546106
