### ISSUE TITLE
[Spell][Warrior] Slam goes through when warrior is disarmed

### ISSUE THREAD

**Issue by Brasso** [Atlantiss/NetherwingBugtracker#3995]
[//]: # (Enclose links to things related to the bug using http://wowhead.com or any other TBC database.)
[//]: # (You can use screenshot ingame to visual the issue.)
[//]: # (Write your tickets according to the format:)
[//]: # ([Quest][Azuremyst Isle] Red Snapper - Very Tasty!)
[//]: # ([NPC] Magistrix Erona)
[//]: # ([Spell][Mage] Fireball)
[//]: # ([Npc][Drop] Ghostclaw Lynx)
[//]: # ([Web] Armory doesnt work)
[//]: # (To find server revision type `.server info` command in the game chat.)

**Description**: 
If the warrior gets disarmed mid slam channel the slam still goes off. I have no proof that it shouldn't, but slam requires melee weapon equipped so it would make sense.

**Expected behaviour**: 
Slam gets interrupted.
**Server Revision**: 
2604

**Comment by tsuone** [comment]
> Does the slam do damage as if you were unarmed or does it do full weapon damage currently when disarmed?

Unarmed damage when disarmed.

**Comment by Godmatik** [comment]
Rev 4018 - no longer an issue
Slam cancels itself mid-cast if you are disarmed
