### ISSUE TITLE
Rested earn rate no consistent

### ISSUE THREAD

**Issue by DarkGHLB** [Atlantiss/NetherwingBugtracker#3996]
[//]: # (Enclose links to things related to the bug using http://wowhead.com or any other TBC database.)
[//]: # (You can use screenshot ingame to visual the issue.)
[//]: # (Write your tickets according to the format:)
[//]: # ([Quest][Azuremyst Isle] Red Snapper - Very Tasty!)
[//]: # ([NPC] Magistrix Erona)
[//]: # ([Spell][Mage] Fireball)
[//]: # ([Npc][Drop] Ghostclaw Lynx)
[//]: # ([Web] Armory doesnt work)
[//]: # (To find server revision type `.server info` command in the game chat.)

**Description**: Between talking with friends, rested earn rate seems to be vastly different amongst players.

**Current behaviour**:

**Expected behaviour**: 

**Server Revision**:

**Comment by Brasso** [comment]
Cannot reproduce. Did some log out in an inn and other didn't? Just have everyone log out in an inn and see if you have 2 bars after 8 hours etc.

**Comment by The14me** [comment]
Need some proof,or at least to know whats the different.
