### ISSUE TITLE
Crit while sitting does not activate talents

### ISSUE THREAD

**Issue by DarkGHLB** [Atlantiss/NetherwingBugtracker#3997]
[//]: # (Enclose links to things related to the bug using http://wowhead.com or any other TBC database.)
[//]: # (You can use screenshot ingame to visual the issue.)
[//]: # (Write your tickets according to the format:)
[//]: # ([Quest][Azuremyst Isle] Red Snapper - Very Tasty!)
[//]: # ([NPC] Magistrix Erona)
[//]: # ([Spell][Mage] Fireball)
[//]: # ([Npc][Drop] Ghostclaw Lynx)
[//]: # ([Web] Armory doesnt work)
[//]: # (To find server revision type `.server info` command in the game chat.)

**Description**: Being hit/crit while sitting does not activate talents

**Current behaviour**: Blood craze/enrage will not activate if hit by a mob while sitting

**Expected behaviour**: Blood craze/enrage activate upon being crit.

**Server Revision**:

**Comment by Brasso** [comment]
#1871 Working as intended
