### ISSUE TITLE
gnomer elevator

### ISSUE THREAD

**Issue by DarkGHLB** [Atlantiss/NetherwingBugtracker#3998]
[//]: # (Enclose links to things related to the bug using http://wowhead.com or any other TBC database.)
[//]: # (You can use screenshot ingame to visual the issue.)
[//]: # (Write your tickets according to the format:)
[//]: # ([Quest][Azuremyst Isle] Red Snapper - Very Tasty!)
[//]: # ([NPC] Magistrix Erona)
[//]: # ([Spell][Mage] Fireball)
[//]: # ([Npc][Drop] Ghostclaw Lynx)
[//]: # ([Web] Armory doesnt work)
[//]: # (To find server revision type `.server info` command in the game chat.)

**Description**: Went down the elevator at gnomeregan (outside instance), and walked off. 5 feet later I died. 4 of my party members died after walking off the elevator as well.

**Current behaviour**: Fall damage from elevator.

**Expected behaviour**: No fall damage from walking off elevator.

**Server Revision**:

**Comment by Wolffenstein** [comment]
Fixed after next restart.

**Comment by kelsealae** [comment]
Me and my group ran gnomeregan yesturday, and went on the elevator, and a critical error popped up the same time the server crashed. Unfortunately, I didn't get a screenshot.
