### ISSUE TITLE
[Minor] LFG channel on new character

### ISSUE THREAD

**Issue by DoctorRaymos** [Atlantiss/NetherwingBugtracker#40]
Hey, very minor bug or unintended behavior. When creating and starting new character, you are automatically placed in the LFG channel, which prompts this error - https://imgur.com/a/NS9u6ZY

Not sure what intended behavior for LFG channel is, but I definitely don't recall getting any errors similar to this on character creation.

**Comment by Emtec** [comment]
Fixed
