### ISSUE TITLE
[Blood Furnace] Broggok just leaves his cell and follows a player

### ISSUE THREAD

**Issue by killablink** [Atlantiss/NetherwingBugtracker#4002]
**Description**: https://gfycat.com/TerribleNearGnatcatcher

**Current behaviour**: https://gfycat.com/TerribleNearGnatcatcher

**Expected behaviour**: Doesn't leave his cell.

**Server Revision**: latest

**Comment by Wolffenstein** [comment]
Fixed in rev 2645.
