### ISSUE TITLE
[Spell][Priest] Improved Power Word: Fortitude on Rank 2 PWF Is not Working

### ISSUE THREAD

**Issue by PiaCarrot** [Atlantiss/NetherwingBugtracker#4004]
**Description**: The tooltip says Rank 2 PW:F should increase stamina by 10, but on;y increases by 8. I have 2/2 Improved talent for PW:F

**Current behaviour**: Buffs stam by 8

**Expected behaviour**: Should buff stam by 10, according to tooltip

**Server Revision**: 203

**Comment by Tenoutoften** [comment]
It updates correctly on action bars, but the buff icon text itself will always say the default value, that's how it is.

**Comment by devo6969** [comment]
This is still in classic and always has been a thing for years. Like tenoutoften said, it will update on your tooltip but not "visually" show the amount on the buff.
https://www.wowhead.com/forums&topic=148342
"it's a common bug that happens with all buffs that actually get modified by talents. If you have the "Improved Power Word: Fortitude" talent, it will show up in your spellbook, but not on your buff bar. It's been like that for years..."
"Its intended not to reveal information about your character such as talent build in PvP situations"
