### ISSUE TITLE
Corrupted Sabers (Felwood)

### ISSUE THREAD

**Issue by Bzmode** [Atlantiss/NetherwingBugtracker#4005]
[//]: # (Enclose links to things related to the bug using http://wowhead.com or any other TBC database.)
[//]: # (You can use screenshot ingame to visual the issue.)
[//]: # (Write your tickets according to the format:)
[//]: # ([Quest][Azuremyst Isle] Red Snapper - Very Tasty!)
[//]: # ([NPC] Magistrix Erona)
[//]: # ([Spell][Mage] Fireball)
[//]: # ([Npc][Drop] Ghostclaw Lynx)
[//]: # ([Web] Armory doesnt work)
[//]: # (To find server revision type `.server info` command in the game chat.)

**Description**: 

**Current behaviour**: Can't turn the cat into the quest giver.

**Expected behaviour**: Quest should complete when returned to the quest giver in its corrupted state

**Server Revision**:

**Comment by Evolvee** [comment]
You need to click on the cat, there is a gossip option.

If it doesnt work, reopen.

**Comment by DeerDance56** [comment]
Gossip does not open. Quest cannot be completed.

**Comment by Evolvee** [comment]
Core issue then

**Comment by rangobob** [comment]
Still not fixed.

**Comment by Ashfall7x** [comment]
Still bugged.

**Comment by Evolvee** [comment]
Core problem -  the summoned NPC isnt recognized as a creature by the server
![image](https://user-images.githubusercontent.com/1942409/51614175-688f8d00-1f25-11e9-92f9-95158c111edf.png)

**Comment by Evolvee** [comment]
Its a spells fault:

15647

![image](https://user-images.githubusercontent.com/1942409/51614306-a987a180-1f25-11e9-8809-f7395e2a07d2.png)

**Comment by Evolvee** [comment]
When summoned via script, the NPC works just fine.

When summoned via spell(quest item), the NPC is bugged.

**Comment by Fuzedknight** [comment]
Can confirm still broken.

**Comment by elenmerbau** [comment]
Doesn't work for me as well.

**Comment by CryingEnder** [comment]
Still doesn't work

**Comment by Wolffenstein** [comment]
Fixed in rev 2777.
