### ISSUE TITLE
[NPC] Silithid Invader 

### ISSUE THREAD

**Issue by syphex97** [Atlantiss/NetherwingBugtracker#4006]
[//]: # (Enclose links to things related to the bug using http://wowhead.com or any other TBC database.)
[//]: # (You can use screenshot ingame to visual the issue.)
[//]: # (Write your tickets according to the format:)
[//]: # ([Quest][Azuremyst Isle] Red Snapper - Very Tasty!)
[//]: # ([NPC] Magistrix Erona)
[//]: # ([Spell][Mage] Fireball)
[//]: # ([Npc][Drop] Ghostclaw Lynx)
[//]: # ([Web] Armory doesnt work)
[//]: # (To find server revision type `.server info` command in the game chat.)

**Description**: 
There is right now only 1 of these mobs that spawn and thats about it, Killing the Silithid Hive Drones is supposed to spawn invaders but that doesnt work.
**Current behaviour**:
Killing Silithid Hive Drones do not spawn Silithid Invaders

**Expected behaviour**: 
Upon killing a Silithid hive drone a Invader is supposed to spawn in its place

**Server Revision**: 

https://i.imgur.com/6Cz8Jgd.png

https://i.imgur.com/ShsPtZu.png

**Comment by Tenoutoften** [comment]
Are you inside the cave? Both of your pictures are from outside of the cave. This NPC will only spawn on the inside of the cave https://github.com/Atlantiss/NetherwingBugtracker/issues/121

**Comment by Shanghi** [comment]
He's right about them only spawning in the cave though (and at the entrance). The drones outside share a spawn with a different type. Were you killing the drones inside? This worked before.
![image](https://user-images.githubusercontent.com/2672633/50955692-cc2aac80-1487-11e9-8a76-b4ec0b6843b7.png)
![image](https://user-images.githubusercontent.com/2672633/50955781-fbd9b480-1487-11e9-93bd-71a009d2393f.png)
![image](https://user-images.githubusercontent.com/2672633/50955827-14e26580-1488-11e9-8890-6c461273c5a7.png)
![image](https://user-images.githubusercontent.com/2672633/50955960-773b6600-1488-11e9-8c1f-37064eed2839.png)

**Comment by syphex97** [comment]
> He's right about them only spawning in the cave though (and at the entrance). The drones outside share a spawn with a different type. Were you killing the drones inside? This worked before.



I did not once state that they didnt, it was just assumed they did because he thought it looked like i was outside the cave. - Already made sure to check everything so i didnt make a invalid issue.
![ghjkhkhj](https://user-images.githubusercontent.com/20000240/50971672-e8a90200-14e4-11e9-974f-bdae37a1ba97.PNG)

**Comment by Manaci** [comment]
Fixed
