### ISSUE TITLE
[Quest] The Color of Blood: Red Woolen Bandanas are not shared on group loot.

### ISSUE THREAD

**Issue by ritterpa** [Atlantiss/NetherwingBugtracker#4007]
[//]: # (Enclose links to things related to the bug using http://wowhead.com or any other TBC database.)
[//]: # (You can use screenshot ingame to visual the issue.)
[//]: # (Write your tickets according to the format:)
[//]: # ([Quest][Azuremyst Isle] Red Snapper - Very Tasty!)
[//]: # ([NPC] Magistrix Erona)
[//]: # ([Spell][Mage] Fireball)
[//]: # ([Npc][Drop] Ghostclaw Lynx)
[//]: # ([Web] Armory doesnt work)
[//]: # (To find server revision type `.server info` command in the game chat.)

**Description**: 
The quest items for the Stockades quest "The Color of Blood" - Red Wool Bandanas - are not lootable by all party members - each one is only lootable one time by one player.
**Current behaviour**:

**Expected behaviour**: 
All party members should be able to loot each Red Wool Bandana that drops for the quest.
**Server Revision**:

**Comment by Tereneckla** [comment]
mass report #7176
