### ISSUE TITLE
[Core] Casting stopped when mob goes out of range.

### ISSUE THREAD

**Issue by teodinmw** [Atlantiss/NetherwingBugtracker#4009]
[//]: # (Enclose links to things related to the bug using http://wowhead.com or any other TBC database.)
[//]: # (You can use screenshot ingame to visual the issue.)
[//]: # (Write your tickets according to the format:)
[//]: # ([Quest][Azuremyst Isle] Red Snapper - Very Tasty!)
[//]: # ([NPC] Magistrix Erona)
[//]: # ([Spell][Mage] Fireball)
[//]: # ([Npc][Drop] Ghostclaw Lynx)
[//]: # ([Web] Armory doesnt work)
[//]: # (To find server revision type `.server info` command in the game chat.)

**Description**: 

**Current behaviour**:
Casting stops the instant the mob goes out of range of the spell that you are casting on them.
**Expected behaviour**: 
There is a grace period of range where casting will continue even if the mob goes out of range of the spell to a maximum distance before stopping the cast.
**Server Revision**:

**Comment by HyperXewl** [comment]
I'm seeing the same issue

**Comment by Tenoutoften** [comment]
Known issue https://github.com/Atlantiss/NetherwingBugtracker/issues/121

**Comment by Mewmewww** [comment]
Spell leeway could've been temporarily reverted since there have been appearing a weird collection of issues since the launch.

**Comment by The14me** [comment]
Duplicate #121
