### ISSUE TITLE
[NPC]Silithid Swarmer 4196

### ISSUE THREAD

**Issue by Bleachlol** [Atlantiss/NetherwingBugtracker#401]
**Description**: 
Creatures pet, easy killable and abuseable, gives xp Creature ID: 4196 
**Current behaviour**:
Gives xp when killed https://imgur.com/a/ThwzpiY 
**Expected behaviour**: 
Should not give xp
**Server Revision**: 
2040

**Comment by Evolvee** [comment]
fixed in next rev
