### ISSUE TITLE
[Core Mechanic][Hunter] Pet attacks from range and front

### ISSUE THREAD

**Issue by Wookiefister** [Atlantiss/NetherwingBugtracker#4010]
[//]: # (Enclose links to things related to the bug using http://wowhead.com or any other TBC database.)
[//]: # (You can use screenshot ingame to visual the issue.)
[//]: # (Write your tickets according to the format:)
[//]: # ([Quest][Azuremyst Isle] Red Snapper - Very Tasty!)
[//]: # ([NPC] Magistrix Erona)
[//]: # ([Spell][Mage] Fireball)
[//]: # ([Npc][Drop] Ghostclaw Lynx)
[//]: # ([Web] Armory doesnt work)
[//]: # (To find server revision type `.server info` command in the game chat.)

**Description**: [Core Mechanic][Hunter] Pet attacks from range and front

**Current behaviour**: Multiple times I have witnessed my pet attack from a very long range out of melee, and also from the front of the mob. Here is a screenshot https://imgur.com/a/T9RUv7j I confirmed with the other members of my party that this appeared on their screens as well, so it is not visual or clientside. This is game breaking in pvp for obvious reasons if your pet can attack from a huge range, but also is a significant reduction in dps if your pet attacks from the from the front rather from behind in a dungeon (especially if you are BM at 70) this is should be fixed with high priority. 

**Expected behaviour**:  The pet should be able to attack only from melee range and should also go behind the mob if not the current target of the mob. 

**Server Revision**: This happened last at 8:45 PST as seen in the screenshot

**Comment by Manaci** [comment]
Fixed
