### ISSUE TITLE
[Professions] fishing bobber disappearing

### ISSUE THREAD

**Issue by Kidtoucher** [Atlantiss/NetherwingBugtracker#4013]
**Description**: 
the bobber is sometimes disappearing, making it impossible to click it and loot any fish.

**Current behaviour**:
the bobber is sometimes disappearing, making it impossible to click it and loot any fish.

**Expected behaviour**: 
the bobber should never disappear in the middle of the fishing cast.

**Comment by Erodraeda** [comment]
Happening to my friend as well.

**Comment by sefamurat** [comment]
Can confirm that this still exists. Happens every 5-10 casts. Very discouraging on top of the fact that fishing is really an arse to level.

**Comment by Nythius** [comment]
This is still happening. Usually happens a few seconds after the fish bobber moves due to catching a fish.

**Comment by xrayEU** [comment]
Happens for me as well.

**Comment by Tereneckla** [comment]
Fixed, bobber only disappears if you sleep when a fish bites
