### ISSUE TITLE
[Custom Shared Loot] Troll Temper

### ISSUE THREAD

**Issue by Azalen** [Atlantiss/NetherwingBugtracker#4014]
**Current behaviour**:
https://vanilla-twinhead.twinstar.cz/?item=9523 not in share quest loot table

**Server Revision**: 
[2608]

**Comment by Snowie493** [comment]
Confirming that it is indeed not shared between the grp.

**Comment by Sabre142** [comment]
Same with https://db.excalibur.ws/?item=17756 Shadowshard Fragment apparently.

**Comment by Tereneckla** [comment]
Fixed
