### ISSUE TITLE
Warlock pets passive ability not working

### ISSUE THREAD

**Issue by Jalapan** [Atlantiss/NetherwingBugtracker#4015]
[//]: # (Enclose links to things related to the bug using http://wowhead.com or any other TBC database.)
[//]: # (You can use screenshot ingame to visual the issue.)
[//]: # (Write your tickets according to the format:)
[//]: # ([Quest][Azuremyst Isle] Red Snapper - Very Tasty!)
[//]: # ([NPC] Magistrix Erona)
[//]: # ([Spell][Mage] Fireball)
[//]: # ([Npc][Drop] Ghostclaw Lynx)
[//]: # ([Web] Armory doesnt work)
[//]: # (To find server revision type `.server info` command in the game chat.)

**Description**: 
Warlock pets passive is not doing anything, broken
**Current behaviour**:
Warlock pets passive is not doing anything
**Expected behaviour**: 
If player is attacked, pet should attack that mob
**Server Revision**:

**Comment by ozhanbinici** [comment]
the expected behaviour is defensive, not passive.

**Comment by Tereneckla** [comment]
Fixed
