### ISSUE TITLE
[Core] Disconnecting mid flight puts you back at the start of the flight

### ISSUE THREAD

**Issue by Zarant** [Atlantiss/NetherwingBugtracker#4016]
Whenever you take a taxi from point A to point B, and you disconnect at the middle of the flight path, your position is reset, making you go through the whole flight again, last night I got stuck for over half an hour in a flight between theramore and auberdine because of constant server lag and DCs.

The server should store the player's position so they can continue the flight from where they got disconnected, not start the whole flight all over again.

> About your flights, if it's a multi-stop flight that you've taken, press Alt+F4 before the next stop, then relaunch WoW, log back in, you'll continue your flight and stop at the first flightmaster, instead of going the whole way. 

http://wow.allakhazam.com/forum.html?forum=21&mid=116983447196137233#3

Somewhat related to #3188

Server Revision: 2604

**Comment by Tenoutoften** [comment]
I haven't figured out this mechanic completely...
But I have noticed some players get ported back to where they previously landed from a flight path

**Comment by DragunovUA** [comment]
still bugged af

**Comment by Zarant** [comment]
As of revision 3443, it's working as intended, if you log out and log back in, the server will remember your last position, however, i'm not sure if that's still the case if the server crashes.
