### ISSUE TITLE
[Core] Pets/totems from same faction players show as hostile, but can´t be attacked. (visual)

### ISSUE THREAD

**Issue by Kidtoucher** [Atlantiss/NetherwingBugtracker#4017]
**Description**: 
Pets/totems from same faction players show as hostile, but can´t be attacked. (visual)

**Current behaviour**:
Pets/totems from same faction players show as hostile, but can´t be attacked. (visual)

**Expected behaviour**: 
Shouldn´t display the attack symbol when hovering over the pet.

**Comment by torrenzGH** [comment]
this is typical pserver stuff and not super high impact but would be nice to fix anyways
won't be as noticeable when view range is increased

**Comment by wtRCH** [comment]
View distance related. Invalid.
