### ISSUE TITLE
Mind Flay Channeling

### ISSUE THREAD

**Issue by jakeoff** [Atlantiss/NetherwingBugtracker#4018]
[//]: # (Enclose links to things related to the bug using http://wowhead.com or any other TBC database.)
[//]: # (You can use screenshot ingame to visual the issue.)
[//]: # (Write your tickets according to the format:)
[//]: # ([Quest][Azuremyst Isle] Red Snapper - Very Tasty!)
[//]: # ([NPC] Magistrix Erona)
[//]: # ([Spell][Mage] Fireball)
[//]: # ([Npc][Drop] Ghostclaw Lynx)
[//]: # ([Web] Armory doesnt work)
[//]: # (To find server revision type `.server info` command in the game chat.)

**Description**: Mind Flay will sometimes (very rarely) appear to cancel it's channel (cast bar disappears), but the Mind Flay slow/damage portion will still affect the target for the full 3 second duration. During this time you may also move around, and the spell will still be affecting your target. You can also keep refreshing Mind Flay during this time to extend this 'buggy' state. A similar recent issue was present on a different project, but here, I've experienced it in differing scenarios and more frequently during periods of server instability (but also when not lagging). I cannot figure out why it happens and therefore cannot reliably reproduce it, but I do have screenshots if it is of any help.

**Current behaviour**: Mind Flay will sometimes (very rarely) appear to cancel it's channel (cast bar disappears), but the Mind Flay slow/damage portion will still affect the target for the full 3 second duration. During this time you may also move around, and the spell will still be affecting your target.

**Expected behaviour**: Mind Flay's cast bar channel should not disappear and you should not be able to move around (and refresh this state) during the cast.

**Server Revision**:

**Comment by jakeoff** [comment]
This is also happening with other channeled spells such as: Drain Soul, Drain Life, Drain Mana, etc.

**Comment by Gedlund** [comment]
Jakeoff ? ur here ? I remember u from feenix i think ? (Immortal sunrise guy )

**Comment by Desst** [comment]
can confirm this
I think it's related to spell queueing

**Comment by Desst** [comment]
this needs to be fixed ASAP. Can be abused in Pvp

**Comment by towneh** [comment]
Related to my previous comments during beta? https://github.com/Atlantiss/NetherwingBugtracker/issues/3036#issuecomment-441838101

**Comment by Camarila** [comment]
I should also like to add that if there is a reflect on an enemy, mind flay will apply slow to self (as a reflect) but no damage. Very strange.
How it should work (I think): It should be usable with the reflect up doing damage directly to the enemy.
How to reproduce: Attack an enemy with spell reflect (like the mageslayers in netherstorm) and cast mind flay and see it reflects to self.

**Comment by Tereneckla** [comment]
https://www.youtube.com/watch?v=qWJBKvQenEU
At 0:14 I manage to get the bug and move with mind flay ticking.
At 0:44 I can produce a longer chain of it and spam mind flay in the not showing global cooldown.

A channel bugged like this cannot be interrupted in any way.


To reproduce you start a new channel exactly at the end (or maybe slightly before) of your last channel.

I suppose the package that says you are casting something gets lost.

**Comment by Rayuuken** [comment]
Apparently is there any information about this spell Mind Flay beeing fixed. In my case when im using MF it also does have its cast bart to sometimes disappear.

When does this happen? Usually when i try to CLIP the 2nd tick of the spell whenever mb goes off or i have to refresh sw:p / VT usually to be very much min/maxing the dps output that i can potentially pull off.

I know that shps were never kings of the dps. But if you were good you could be performing pretty well. I hate to be handicapped on my own when the one and only spell that i can spam the dps with is bugged like this.

Any memo of this spell beeing as one of the major game breaking problems and needing a fix asap or something? Atm kind of pointless putting any kind of effort to be doing best dps u can. I can simply refresh dots use mb / sw:d at typical raid boss rotation and dont cast a single mf.

Cause when this happens i think its a resist and after losing two gcds i find out that its not a resist but this god damn bug with MF still beeing cast even though the cast bar disappeared

**Comment by SdentBurri** [comment]
I've found the specific position in the RPLLLogs Dump that might get you some informations for it hopefully. It was at 20:51:02.054 as I clipped MF at ROS BT and got the behaviour. I tried to color it as good as possible. Please see the colored table:
https://user-images.githubusercontent.com/26461040/73608474-aeb10f00-45c3-11ea-9f1a-b0034e002942.png
If needed i can send you the full dump directly (not public).
I feel like it might also be connected to the suspect long delay time between Invalidity of UnitChannelInfo/[channeling] to get to false when GetSpellCooldown/UnitChannelInfo endTimeMs plus ping is already exceeded and no spell is cast - but you start a new cast in exactly that moment. But im still trying hard to get useful informations on it in the last few days.

**Comment by Kersoph** [comment]
(In consultation with evolve) I can reproduce it with carefully timing the new MF right in the gap where the old MF is done but Channeling is somehow still true for some ms. (client side). So around by 2-3x the indicated delay e.g. Quartz. Of course I don't know if that is really the issue behind it.
The thing is that you can also move, jump and even start to cast a new spell while MF still ticks. And it seems that interrupts and spellpushback have no effect on the bugged MF (so it still ticks normally).
And by refreshing it in time you can extend the bugged state.

Video on PTR: https://www.dropbox.com/s/ays67j8uz46cmgm/World%20Of%20Warcraft_2_MF.mp46037-15998.mkv?dl=0 (download for better quality)
Log: https://www.dropbox.com/s/tut534pjhf2pwa9/WoWCombatLog.txt?dl=0
Other log on PTR with the same behaviour (not in video): [WoWCombatLog.txt](https://github.com/Atlantiss/NetherwingBugtracker/files/4155878/WoWCombatLog.txt)

**Comment by Kersoph** [comment]
Anything I can do / try out?

**Comment by Wolffenstein** [comment]
Fixed in rev 3362.
