### ISSUE TITLE
[Quest][Blade's Edge Mountains]Vision Guide

### ISSUE THREAD

**Issue by Squarz** [Atlantiss/NetherwingBugtracker#4019]
[//]: # (Enclose links to things related to the bug using http://wowhead.com or any other TBC database.)
[//]: # (You can use screenshot ingame to visual the issue.)
[//]: # (Write your tickets according to the format:)
[//]: # ([Quest][Azuremyst Isle] Red Snapper - Very Tasty!)
[//]: # ([NPC] Magistrix Erona)
[//]: # ([Spell][Mage] Fireball)
[//]: # ([Npc][Drop] Ghostclaw Lynx)
[//]: # ([Web] Armory doesnt work)
[//]: # (To find server revision type `.server info` command in the game chat.)

**Current behaviour**:
Fails to teleport the player back to Thunderlord Stronghold and no quest credit is given:
https://streamable.com/b5nns
**Expected behaviour**: 
The player should be returned to Thunderlord Stronghold and quest credit should be given.
**Server Revision**: 
2604

**Comment by Evolvee** [comment]
taxi scripts are currently disabled afaik due to researching the crashes https://github.com/Atlantiss/NetherwingBugtracker/issues/3956

**Comment by Evolvee** [comment]
should be resolved
