### ISSUE TITLE
Unseen enemy in Duskwood

### ISSUE THREAD

**Issue by ThriceFilter** [Atlantiss/NetherwingBugtracker#402]
[//]: # (Enclose links to things related to the bug using http://wowhead.com or any other TBC database.)
[//]: # (You can use screenshot ingame to visual the issue.)
[//]: # (Write your tickets according to the format:)
[//]: # ([Quest][Azuremyst Isle] Red Snapper - Very Tasty!)
[//]: # ([NPC] Magistrix Erona)
[//]: # ([Spell][Mage] Fireball)
[//]: # ([Npc][Drop] Ghostclaw Lynx)
[//]: # ([Web] Armory doesnt work)

**Description**: 
Something keeps killing me in duskwood whenever i try to loot this chest, it is immune to all damage and is listed as unseen. Also every chest i have found in duskwood is empty youtube vid below explains
**Current behaviour**:
https://youtu.be/D9dLNQlqo6g

**Expected behaviour**: 

**Server Revision**:

**Comment by wowthings** [comment]
Same as this #309

**Comment by Evolvee** [comment]
https://github.com/Atlantiss/NetherwingBugtracker/issues/309

**Comment by Evolvee** [comment]
Unseen NPCs wont attack you now, unless you aoe them. http://wowwiki.wikia.com/wiki/Unseen
