### ISSUE TITLE
Friend notification when online gets spammed

### ISSUE THREAD

**Issue by Jalapan** [Atlantiss/NetherwingBugtracker#4020]
[//]: # (Enclose links to things related to the bug using http://wowhead.com or any other TBC database.)
[//]: # (You can use screenshot ingame to visual the issue.)
[//]: # (Write your tickets according to the format:)
[//]: # ([Quest][Azuremyst Isle] Red Snapper - Very Tasty!)
[//]: # ([NPC] Magistrix Erona)
[//]: # ([Spell][Mage] Fireball)
[//]: # ([Npc][Drop] Ghostclaw Lynx)
[//]: # ([Web] Armory doesnt work)
[//]: # (To find server revision type `.server info` command in the game chat.)

**Description**: 
When a friend connects to game you get a notice, since a few hours ago the message is spammed severals times
**Current behaviour**:
message is spammed severals times
**Expected behaviour**: 
should only give one notification
**Server Revision**:

**Comment by The14me** [comment]
Addon issue maybe?

**Comment by teddys** [comment]
This does not happen for me

**Comment by Tereneckla** [comment]
Happens if friend also in your guild
