### ISSUE TITLE
[Spell][Priest] Abolish Disease

### ISSUE THREAD

**Issue by Desst** [Atlantiss/NetherwingBugtracker#4022]
**Current behaviour**:
Abolish disease and Abolish poison sometimes do not dispel subsequent diseases/poisons (like they have dispell protection).

**Expected behaviour**:
Abolish disease should remove a disease on initial cast and every 5 seconds for 20 seconds

**Server Revision**:
2604

**Comment by Tereneckla** [comment]
Fixed
