### ISSUE TITLE
[Talent][Hunter] Serpent's Swiftness

### ISSUE THREAD

**Issue by Sogarez** [Atlantiss/NetherwingBugtracker#4023]
**Description**: 
Wrong weapon speed with 5/5 Serpent's Swiftness talent (http://db.hellfire-tbc.com/?spell=34470)

**Current behaviour**:
With "Sniper Rifle of the Owl" (http://db.hellfire-tbc.com/?item=3430) weapon (original speed 3.0) and without any Ammo pouch the actual speed with 5/5 talent is 2.5

**Expected behaviour**: 
Must be 3.0 - 0.6 = 2.4 

**Server Revision**: 
2604

**Comment by Zarant** [comment]
Working as intended, 3.0/1.2 = 2.5

**Comment by Manaci** [comment]
Fixed
