### ISSUE TITLE
Warlock cant summon players on other continents

### ISSUE THREAD

**Issue by Jalapan** [Atlantiss/NetherwingBugtracker#4024]
[//]: # (Enclose links to things related to the bug using http://wowhead.com or any other TBC database.)
[//]: # (You can use screenshot ingame to visual the issue.)
[//]: # (Write your tickets according to the format:)
[//]: # ([Quest][Azuremyst Isle] Red Snapper - Very Tasty!)
[//]: # ([NPC] Magistrix Erona)
[//]: # ([Spell][Mage] Fireball)
[//]: # ([Npc][Drop] Ghostclaw Lynx)
[//]: # ([Web] Armory doesnt work)
[//]: # (To find server revision type `.server info` command in the game chat.)

**Description**: 
Cant summon players that are not on the same continent as you
**Current behaviour**:
says no target when the player in question is on another continent
**Expected behaviour**: 
you should be able to summon anyone from any continent/zone regardless
**Server Revision**:

**Comment by Snowie493** [comment]
this worked this morning, havnt tried since then.

**Comment by Desst** [comment]
meeting stones also broken

**Comment by Tenoutoften** [comment]
Already reported https://github.com/Atlantiss/NetherwingBugtracker/issues/3955

**Comment by The14me** [comment]
Duplicate #3955
