### ISSUE TITLE
Warlock surface swimming with pet leads to pet getting dismissed

### ISSUE THREAD

**Issue by Azalen** [Atlantiss/NetherwingBugtracker#4025]
**Current behaviour**:
When you swim on the surface with pet (void in my case) it stays at the same position and warps forward from time to time to stay in range of the warlock. Always at some point (maybe 10 seconds = 3 warps) it will get dismissed and you have to recast it.

If you swim below the surface this bug does not occur and the pet will swim right next to you.

**Expected behaviour**: 
No warping, same effect for surface swimming than underwater swimming.

**Server Revision**: 
[2608]

**Comment by devo6969** [comment]
This is fixed. most I could recreate this is when i would Fly up in the air and land in the water and swim on the surface, but it would just teleport to me not despawn. Tried with all warlock pets
