### ISSUE TITLE
Root running out breaks FA/eating (only sometimes)

### ISSUE THREAD

**Issue by teddys** [Atlantiss/NetherwingBugtracker#4026]
**Description**: this net for example https://db.excalibur.ws/?npc=4093#abilities

**Current behaviour**: when eating/first aiding while under the effect of this net, by the time the net debuff runs out, your eating/first aid is interrupted

**Expected behaviour**: should not be interrupted

**Server Revision**: 2604

Did not encounter it before, but it's probably the same for all root/immobilize effects

**Comment by Godmatik** [comment]
Fixed already
