### ISSUE TITLE
Captain Sanders Treasure

### ISSUE THREAD

**Issue by Cephas13** [Atlantiss/NetherwingBugtracker#4027]
[//]: # (Enclose links to things related to the bug using http://wowhead.com or any other TBC database.)
[//]: # (You can use screenshot ingame to visual the issue.)
[//]: # (Write your tickets according to the format:)
[//]: # ([Quest][Azuremyst Isle] Red Snapper - Very Tasty!)
[//]: # ([NPC] Magistrix Erona)
[//]: # ([Spell][Mage] Fireball)
[//]: # ([Npc][Drop] Ghostclaw Lynx)
[//]: # ([Web] Armory doesnt work)
[//]: # (To find server revision type `.server info` command in the game chat.)

**Description**: I turned in the final quest for Captain Sanders Treasure and only received one of the items because my bags had one slot open.

**Current behaviour**: The quest completed even though my bags were full.

**Expected behaviour**: The game shouldn't have allowed the quest to complete if I was not able to fit quest rewards into my bags.

**Server Revision**:

**Comment by xmesaj2** [comment]
fixed in 2609
