### ISSUE TITLE
[NPC] Talbuk Stag Skinning Table

### ISSUE THREAD

**Issue by Ensipidx** [Atlantiss/NetherwingBugtracker#4029]
**Description**: Talbuk Stags skin for way too much leather.

**Current behaviour**: Talbuks Stag skin for upwards of 4 full knothide leather (not always scraps like most non 70 mobs)

![image](https://user-images.githubusercontent.com/28462188/51007108-443eb400-1514-11e9-962e-f82704710060.png)

**Expected behaviour**: Should skin for scraps like every other similar level mob (once in a while a full knothide)

**Server Revision**: Current (203)

**Comment by Ensipidx** [comment]
Talbuk Thorngrazer aswell

**Comment by Shanghi** [comment]
All of the cases like this should hopefully be fixed now, but I'm too weak to be able to check/confirm so will keep it open until someone can.

**Comment by Manaci** [comment]
Fixed
