### ISSUE TITLE
[Quest] The Skettis Offensive

### ISSUE THREAD

**Issue by BezawitNW** [Atlantiss/NetherwingBugtracker#4031]
The Skettis Offensive quest cannot be completed. When you kill all the invading birds / elite you get credit for everything but "Attack thawarted".

**Comment by BezawitNW** [comment]
Does seem to be working now. Hitting for 2300 on leather- not sure if that is normal or not.

**Comment by Fenvarien1** [comment]
![unbenannt](https://user-images.githubusercontent.com/44606340/51186134-28069280-18d9-11e9-9379-a86927127d4f.jpg)
isn't working today

**Comment by RealZwox** [comment]
The dmg of the of the Avatar is way to overtuned. Got hit for 2k on Plate and he is a nonelite.
Also you can spawn multiable times. Just accept the kill the minions and wait for the big one. Abadon the quest and repeat. I saw a level 61 hunter got oneshoted. Was quite funny to watch.

**Comment by FIXTHISFASTERRR** [comment]
ye this is bugged as hell hits for 2k

**Comment by Evolvee** [comment]
rev 2699

**Comment by Evolvee** [comment]
The damage is not overtuned. Check wowhead comments.

**Comment by Evolvee** [comment]
Because I know ur lazy and wont even try, this is a screenshot from wowhead:
![image](https://user-images.githubusercontent.com/1942409/51750329-0fa12f80-20b2-11e9-8ae7-37c25c7acc84.png)
