### ISSUE TITLE
[Core] Mob speed is too fast.

### ISSUE THREAD

**Issue by teodinmw** [Atlantiss/NetherwingBugtracker#4032]
[//]: # (Enclose links to things related to the bug using http://wowhead.com or any other TBC database.)
[//]: # (You can use screenshot ingame to visual the issue.)
[//]: # (Write your tickets according to the format:)
[//]: # ([Quest][Azuremyst Isle] Red Snapper - Very Tasty!)
[//]: # ([NPC] Magistrix Erona)
[//]: # ([Spell][Mage] Fireball)
[//]: # ([Npc][Drop] Ghostclaw Lynx)
[//]: # ([Web] Armory doesnt work)
[//]: # (To find server revision type `.server info` command in the game chat.)

**Description**: 
Mob speed is too high across the board. Mobs that are incredibly noticeably fast include: gnolls, defias, wastewanders.
**Current behaviour**:
Mobs run with the speed of 10,000 Usain Bolts.
**Expected behaviour**: 
Mobs should run with the speed of maybe 0.75 Usain Bolts.
**Server Revision**:

**Comment by The14me** [comment]
Duplicate https://github.com/Atlantiss/NetherwingBugtracker/issues/3935
