### ISSUE TITLE
[Quest] Torgos!

### ISSUE THREAD

**Issue by BezawitNW** [Atlantiss/NetherwingBugtracker#4033]
After placing the carcass of Trachela on the ground to summon Torgos, Torgos does not spawn.

**Comment by BezawitNW** [comment]
Still doesn't seem to work consistently. Friend and I just tried. When we reached  the monument there was already a Torgos spawned, which someone else must have failed. We killed that one (and got credit). I used my carcass to try spawning another. After ~3 minutes of waiting another Torgos never appeared.

**Comment by Balanarr** [comment]
Not sure if the item is actually also supposed to spawn him, or only make him to descend if he's spawned. I know for sure that he spawns and flies around that camp at an un-pullable range without using the item.
Hopefully I'll remember to try it on official and see if using the carcass when he's not spawned does actually also spawn him.

**Comment by Manaci** [comment]
Fixed
