### ISSUE TITLE
[Item][Shaman]Ravager proc interactions

### ISSUE THREAD

**Issue by torrenzGH** [Atlantiss/NetherwingBugtracker#4034]
[//]: # (Enclose links to things related to the bug using http://wowhead.com or any other TBC database.)
[//]: # (You can use screenshot ingame to visual the issue.)
[//]: # (Write your tickets according to the format:)
[//]: # ([Quest][Azuremyst Isle] Red Snapper - Very Tasty!)
[//]: # ([NPC] Magistrix Erona)
[//]: # ([Spell][Mage] Fireball)
[//]: # ([Npc][Drop] Ghostclaw Lynx)
[//]: # ([Web] Armory doesnt work)
[//]: # (To find server revision type `.server info` command in the game chat.)

**Description**: 
**outdated, will add current findings in comments**
**Current behaviour**:
whirlwind attacks only activate frostbrand and rockbiter.

**Expected behaviour**: 
should proc flametongue and windfury aswell.

https://www.wowhead.com/item=7717/ravager#comments:id=62038
https://www.reddit.com/r/KronosWoW/comments/8jx1pf/windfury_internal_cooldown_or_not/dz6ce5p/

**Server Revision**: 
2604

**Comment by torrenzGH** [comment]
just observed it proccing wf, gonna close until i try it out some more

**Comment by torrenzGH** [comment]
Been swinging it around all day and have a better understanding now

Tooltip incorrectly states whirlwind does normal damage +300, should be +5. Value observed is consistent with +5
Flametongue and Frostbrand can both proc from whirlwind
![ravager1](https://user-images.githubusercontent.com/45742182/51022842-a1bf1900-1585-11e9-9627-fbe5b44d57a4.jpg)
**Windfury attack does not proc from whirlwind.**
My rockbiter is too low rank to test satisfyingly, might come back to this
rev 2604

**Comment by wtRCH** [comment]
Value was fixed already.

**Comment by torrenzGH** [comment]
@wtRCH small followup, you can autoattack during the whirlwind effect which I've seen some sources say shouldn't be possible https://forum.elysium-project.org/topic/31798-shaman-and-ravager/
this is why I thought the whirlwind was proccing wf when it doesnt

also some vanilla footage of whirlwind hits proccing windfury
https://www.youtube.com/watch?v=mtPs9BUhRAk

**Comment by Hatson22** [comment]
Auto-attacking during the whirlwind effect is not right at all.

**Comment by Tankdiehutte** [comment]
Yep and procrate ist too low here. Made a report for that procrate with links: https://github.com/Atlantiss/NetherwingBugtracker/issues/6525

**Comment by Evolvee** [comment]
https://github.com/Atlantiss/NetherwingBugtracker/issues/6525
