### ISSUE TITLE
Dropping Combat

### ISSUE THREAD

**Issue by jakeoff** [Atlantiss/NetherwingBugtracker#4037]
[//]: # (Enclose links to things related to the bug using http://wowhead.com or any other TBC database.)
[//]: # (You can use screenshot ingame to visual the issue.)
[//]: # (Write your tickets according to the format:)
[//]: # ([Quest][Azuremyst Isle] Red Snapper - Very Tasty!)
[//]: # ([NPC] Magistrix Erona)
[//]: # ([Spell][Mage] Fireball)
[//]: # ([Npc][Drop] Ghostclaw Lynx)
[//]: # ([Web] Armory doesnt work)
[//]: # (To find server revision type `.server info` command in the game chat.)

**Description**: Currently as a Shadow Priest, I am able to dot a target and then shortly after (2-3 seconds) I drop combat and am able to eat/drink/mount etc. if a party member has aggro on the mob(s) I have dotted. If I use any other abilities (Mind Flay/Mind Blast etc. I remain in combat). Have not tested if this is an issue with warlock dots as well.

**Current behaviour**: Currently as a Shadow Priest, I am able to dot a target and then shortly after (2-3 seconds) I drop combat and am able to eat/drink/mount etc. if a party member has aggro on the mob(s) I have dotted. If I use any other abilities (Mind Flay/Mind Blast etc. I remain in combat). Have not tested if this is an issue with warlock dots as well.

**Expected behaviour**: I should remain in combat after using DoT abilities on the target.

**Server Revision**:

**Comment by wtRCH** [comment]
@Evolvee

**Comment by Godmatik** [comment]
Fixed a long time ago
