### ISSUE TITLE
[NPC] Bloodscalp Witch Doctor

### ISSUE THREAD

**Issue by RealZwox** [Atlantiss/NetherwingBugtracker#4041]
Both Totems the Mob places are not disappearing instant after death. They are still up for like 15 sec.

They should despawn instant after death of the Mob.

**Server Revision**: 2306

**Comment by duzyizly** [comment]
they do, probably fixed with long time ago.

![WoWScrnShot_061920_211947](https://user-images.githubusercontent.com/43931626/85173065-aad01180-b272-11ea-97ec-239a42aefe2b.jpg)
