### ISSUE TITLE
Horde: Quest: Brutal Armor

### ISSUE THREAD

**Issue by Pankysek** [Atlantiss/NetherwingBugtracker#4044]
[//]: # (Enclose links to things related to the bug using http://wowhead.com or any other TBC database.)
[//]: # (You can use screenshot ingame to visual the issue.)
[//]: # (Write your tickets according to the format:)
[//]: # ([Quest][Azuremyst Isle] Red Snapper - Very Tasty!)
[//]: # ([NPC] Magistrix Erona)
[//]: # ([Spell][Mage] Fireball)
[//]: # ([Npc][Drop] Ghostclaw Lynx)
[//]: # ([Web] Armory doesnt work)
[//]: # (To find server revision type `.server info` command in the game chat.)

**Quest**: Brutal Armor https://classicdb.ch/?quest=1838

**NPC**: Thun'grim Firegaze

**Description**: 
Brutal Armor is a Level 20 Horde Quest for Warriors, wherein you need to gather various materials (10 Iron Bars, 10 Powdered Azurite, 15 Smoky Iron Ingots, and 1 Vial of Phlogiston). Once you have gathered all of these materials, you return to the quest giver (Thun'grim Firegaze) who should then accept the items and let you proceed onto the next quest.

**Current behaviour**:
What happens instead is that his floating question mark stays greyed out, even if you have all the materials.

**Expected behaviour**: 
You should be able to hand in all materials with no issue and proceed with the next quest.

**Screen**:  http://prntscr.com/m5z55i
http://prntscr.com/m5z5he

**Comment by Pankysek** [comment]
when I took all the things out of my backpack and returned them the quest was fixed

**Comment by teddys** [comment]
It worked just fine for me.

**Comment by Nimarioos** [comment]
bugged for me, helped gm

**Comment by duzyizly** [comment]
> when I took all the things out of my backpack and returned them the quest was fixed

another one @Tereneckla
