### ISSUE TITLE
[Item][loot]Ethereum Prison Keys shouldn't drop in 2.0, added 2.1

### ISSUE THREAD

**Issue by Tenoutoften** [Atlantiss/NetherwingBugtracker#4046]
**Description**: 
Ethereum Prison Keys are currently dropping but shouldn't, previously reported here.
https://github.com/Atlantiss/NetherwingBugtracker/issues/2720

**Current behaviour**:

**Expected behaviour**: 
[[Item]Ethereum Prison Key#29460](https://db.excalibur.ws/?item=29460#objective-of) shouldn't drop until 2.1. This will reduce the amount of normal dungeons people have to do before heroics significantly

**Server Revision**: 
2604

**Comment by Zarant** [comment]
In order for the Ethereum keys to drop, you need to complete this quest first:
https://www.wowhead.com/quest=10970/a-mission-of-mercy
This particular quest got added to the game in patch 2.1

**Comment by Drayo** [comment]
@aresbrutus This is a big one, would be nice if this was fixed asap.

**Comment by Tixlenra** [comment]
Aye, this needs to be high priority.

**Comment by Evolvee** [comment]
the item shouldnt exist anymore

**Comment by Evolvee** [comment]
this means its deleted from anywhere in the world, even players inventory/banks etc.
