### ISSUE TITLE
[Core][Pet] Pet follow speed mimicking the master's speed

### ISSUE THREAD

**Issue by Zarant** [Atlantiss/NetherwingBugtracker#4047]
Pets on this server will always set their speed to their master's speed regardless of the situation. This is a huge issue in pvp.

Take this video from retail tbc for an example:
https://youtu.be/4jbSgaPROH0?t=128 - Hunter is hamstrung, sends his pet on the mage and then calls it back, you can see the pet running back at normal speed while the hunter is slowed.

Now how it works on netherwing:
https://www.twitch.tv/videos/360748087 - notice that the follow speed is reduced however the pursuit speed remain unchanged.

Might be related to issue #2310

**Comment by Zarant** [comment]
As of revision 3430, this issue has appeared again:

https://youtu.be/nY9nFET0Sto

**Comment by Wolffenstein** [comment]
It's getting fixed in rev 3437.
