### ISSUE TITLE
[Core]Stuck in combat because of view distance and lag

### ISSUE THREAD

**Issue by killablink** [Atlantiss/NetherwingBugtracker#4048]
**Description**: If you run past mobs too quickly and aggro them and they chase you and they disappear out of the view distance you just get stuck in combat until you die or you go back and aggro them again

**Current behaviour**:

**Expected behaviour**: 

**Server Revision**:

**Comment by am3shan** [comment]
can conform...mobs waiting at the edge of the zone. once they are in view again they aggro even after several minutes
