### ISSUE TITLE
Flight Path Bug

### ISSUE THREAD

**Issue by Thugli** [Atlantiss/NetherwingBugtracker#405]
[//]: # (Enclose links to things related to the bug using http://wowhead.com or any other TBC database.)
[//]: # (You can use screenshot ingame to visual the issue.)
[//]: # (Write your tickets according to the format:)
[//]: # ([Quest][Azuremyst Isle] Red Snapper - Very Tasty!)
[//]: # ([NPC] Magistrix Erona)
[//]: # ([Spell][Mage] Fireball)
[//]: # ([Npc][Drop] Ghostclaw Lynx)
[//]: # ([Web] Armory doesnt work)

**Description**: 
While flying from Sun Rock Retreat (Stonetalon) to Ratchet, my character got dismounted from the gryphon mid flight and continued flying without the gryphon after passing through the crossroads. 
**Current behaviour**:
A video of this behaviour can be seen here: 
https://clips.twitch.tv/SweetSarcasticAlpacaOptimizePrime

**Expected behaviour**: 
While flying, players should stay on the gryphon at all times.
**Server Revision**:

**Comment by Azalen** [comment]
Ye can confirm, the dismount happens as soon as you past the first inbetween gryphonmaster.

**Comment by Wolffenstein** [comment]
Fixed in rev 2049.
