### ISSUE TITLE
[Core] Disconnect on lifts

### ISSUE THREAD

**Issue by maxturtlesc2** [Atlantiss/NetherwingBugtracker#4050]
[//]: # (Enclose links to things related to the bug using http://wowhead.com or any other TBC database.)
[//]: # (You can use screenshot ingame to visual the issue.)
[//]: # (Write your tickets according to the format:)
[//]: # ([Quest][Azuremyst Isle] Red Snapper - Very Tasty!)
[//]: # ([NPC] Magistrix Erona)
[//]: # ([Spell][Mage] Fireball)
[//]: # ([Npc][Drop] Ghostclaw Lynx)
[//]: # ([Web] Armory doesnt work)
[//]: # (To find server revision type `.server info` command in the game chat.)

**Description**: 
I was disconnected on a Thunderbluff lift and reconnected in the air (almost died from the fall) since the lift was at the bottom of its course. I could not find retail evidence of characters actually reconnecting properly on the lift, so I am not sure if that's an actual bug or not, but did this post just in case.
**Current behaviour**:
If you disconnect/get disconnected on a lift, you will reconnect at the exact z position the server recorded your disconnection.
**Expected behaviour**: 
Reconnection on the lift, at the correct z lift position?
**Server Revision**:

**Comment by wtRCH** [comment]
@Wolffenstein

**Comment by maxturtlesc2** [comment]
So I guess that's either not a bug, or devs can't do anything about it?
