### ISSUE TITLE
[Quest] You, Robot

### ISSUE THREAD

**Issue by Ensipidx** [Atlantiss/NetherwingBugtracker#4056]
**Description**: Quest not complete able, Negatron chases player and pet can never pull threat.

**Current behaviour**: Negatron chases the player and never drops threat on them, pet does 0 threat even with auto attacks, and even when negatron dies it does give quest completion (tried hitting doing damage, and getting the last hit both don't work)

Even using ankh after dying to Negatron makes him retarget the player and never drop target onto the pet.

**Expected behaviour**: Pet should be fighting, should be complete able.

**Server Revision**: 203

**Comment by Ceago** [comment]
Even if soloed with a prot paladin it is still not completeable as if the robot does more damage than the player you do not get credit.

**Comment by Uriskall** [comment]
still an issue in server revision 2857, not able to complete, even if you do manage to kill without the pet being able to take aggro.

**Comment by jfuglas** [comment]
Still bugged. The minion does not gain aggro

**Comment by Cosmic-Lattee** [comment]
Stilled bugged, managed to kill it through kiting and still didn't get completion.

**Comment by sdaasdsgsdg** [comment]
Now can summon Negatron twice. After second summon you can't take the quest again. If Negatron will be slain you can take quest again. Then quest bugged forever.

After you take quest Negatron spawn and run to quest giver. In a few minutes spawn Scrap Reaver and immidiately attack Negatron without control from player. If player dont use control 2x Negatron slain them. If a player attack Negatron they run for him till player died. Sometimes he run to Area 52 and kill guards.

**Comment by czarecoo** [comment]
still does not work rev 2922

**Comment by Wolffenstein** [comment]
Fixed in rev 3327.
