### ISSUE TITLE
Channeled spells sometimes cannot be cast

### ISSUE THREAD

**Issue by fantom8** [Atlantiss/NetherwingBugtracker#4057]
**Description**: 
Channeled spells such as drain life/consume shadows (voidwalker) sometimes fail on cast but still consume mana.

**Current behaviour**:
Sporadically when you press a channeled Warlock spell (possibly other classes too) it will fail with the error message "interrupted." Mana is still consumed and if you repeatedly press the button this behavior will repeat.

This happens even when not on the global cooldown and after not pressing any other button or moving for several seconds (during a successful channel of the spell). So it is **not** the same as #4018

The only way to fix it is to perform some other actions then return to the channeled spell. Otherwise you can sit there and spam out your whole mana bar and get nothing.

**Expected behaviour**: 
When the ability is used it should start channeling and shouldn't double charge the caster's mana or cancel the channel without any effect.

**Comment by Jalapan** [comment]
confirmed bugged.

**Comment by killablink** [comment]
Happens with blizzard too

**Comment by Tereneckla** [comment]
#4018
