### ISSUE TITLE
Disconnects every 1-10 seconds for persistent time

### ISSUE THREAD

**Issue by lesbattersby** [Atlantiss/NetherwingBugtracker#4059]
[//]: # (Enclose links to things related to the bug using http://wowhead.com or any other TBC database.)
[//]: # (You can use screenshot ingame to visual the issue.)
[//]: # (Write your tickets according to the format:)
[//]: # ([Quest][Azuremyst Isle] Red Snapper - Very Tasty!)
[//]: # ([NPC] Magistrix Erona)
[//]: # ([Spell][Mage] Fireball)
[//]: # ([Npc][Drop] Ghostclaw Lynx)
[//]: # ([Web] Armory doesnt work)
[//]: # (To find server revision type `.server info` command in the game chat.)

**Description**: I disconnect between 1 and 10 seconds after logging into my character.

**Current behaviour**:

I'm getting random disconnects every 5 seconds or so on my character. I'm certain it isn't my internet connection, and I tried running with no addons so it isn't anything i'm doing in that sense. i also restarted client multiple times.
I was questing in the crypt in raven hill cemetery (the crypt in the north east corner of cemetery) and was stood roughly underneath the arch on the first turn to the left hand side, and i got an instant dc. i relogged and moved forwards maybe 2 steps and another dc. same story again and again, i assumed it was my net being patchy or maybe i was in a slightly buggy area so i just brute forced it and relogged again and again, moving in 5 sec windows until i was well clear of the area. i got until the road to the south when it still persisted, so i went to disc to ask for advice. someone said that if you get a gm to tp you it can fix it so i tried hearthing to darkshire, but still the problem persisted so i contacted Smaily. he tried something at first although im not sure what it was, but this didnt seem to work either so i just logged and gave it half an hour to see if the problem went away. after 30 mins i relogged and still the same issue, so i got Smaily to tp me to another zone (to stormwind) to see if this solved the problem but it did not, so now i cant play as i still get disconnected after anywhere between 1 and 10 seconds of logging into my character. Smaily told me to post this here and also post to Pegla directly so here i am.

**Expected behaviour**: 

**Server Revision**:

**Comment by wtRCH** [comment]
Did it happen on this only character or all of your characters? @lesbattersby
