### ISSUE TITLE
[Quest] [NPC] The Zhevra 

### ISSUE THREAD

**Issue by BlessedByTheSin** [Atlantiss/NetherwingBugtracker#406]
[//]: # (Enclose links to things related to the bug using http://wowhead.com or any other TBC database.)
[//]: # (You can use screenshot ingame to visual the issue.)
[//]: # (Write your tickets according to the format:)
[//]: # ([Quest][Azuremyst Isle] Red Snapper - Very Tasty!)
[//]: # ([NPC] Magistrix Erona)
[//]: # ([Spell][Mage] Fireball)
[//]: # ([Npc][Drop] Ghostclaw Lynx)
[//]: # ([Web] Armory doesnt work)

**Description**: 
**NPC**:  [Zhevra Runner](https://classicdb.ch/?npc=3242) has a low chance to drop a quest item **[Zhevra Hooves](https://classicdb.ch/?item=5086)**
**Entry: 3242, SpawnId - (Entry: 3242, Id: 71), GUIDLow: 6877**
**Current behaviour**:
-//-
**Expected behaviour**: 
-//-
**Server Revision**: 
2040

**Comment by Jezofine** [comment]
There's thottbot link to [Zhevra hooves](http://web.archive.org/web/20100818204030/http://thottbot.com:80/i5086)

**Comment by 5f3759** [comment]
In a party of 2, we killed 30-40 zhevra's without a single drop.

**Comment by Jezofine** [comment]
Forgot to say that I got all hooves from 18 zhevra runners (maybe less, I don't know how many zhevras I killed before accepting quest).

**Comment by aresbrutus** [comment]
They should indeed have a low drop rate but I adjusted them a little bit in one of then ext updates.
