### ISSUE TITLE
ress sickness

### ISSUE THREAD

**Issue by maggimar123** [Atlantiss/NetherwingBugtracker#4060]
[//]: # (Enclose links to things related to the bug using http://wowhead.com or any other TBC database.)
[//]: # (You can use screenshot ingame to visual the issue.)
[//]: # (Write your tickets according to the format:)
[//]: # ([Quest][Azuremyst Isle] Red Snapper - Very Tasty!)
[//]: # ([NPC] Magistrix Erona)
[//]: # ([Spell][Mage] Fireball)
[//]: # ([Npc][Drop] Ghostclaw Lynx)
[//]: # ([Web] Armory doesnt work)
[//]: # (To find server revision type `.server info` command in the game chat.)

**Description**: 
({Spell})[Global]  res sickness 
**Current behaviour**:
Dosent tick while being offline
**Expected behaviour**: 
should run out even if offline
**Server Revision**:

**Comment by Drayo** [comment]
http://wowwiki.wikia.com/wiki/Resurrection_Sickness

> Unlike other debuffs, this won't get off the character while you are logged out.
