### ISSUE TITLE
[NPC]Windroc Matriach#19055 from [Quest] Bring me the egg!

### ISSUE THREAD

**Issue by Tenoutoften** [Atlantiss/NetherwingBugtracker#4062]
**Description**: 
[[NPC]Windroc Matriach#19055](https://www.wowhead.com/npc=19055/windroc-matriarch) doesn't seem to have a despawn timer. Suggest  ~30-60 sec despawn timer. Perhaps add a max amount of entries up at the same time?

**Current behaviour**:
Stays up for very long, maybe until server restarts unless killed.

**Expected behaviour**: 
Expected to despawn within a reasonable amount of time to prevent stacking. 

**Server Revision**: 
2604

**Comment by wtRCH** [comment]
Notice that this happens to all summoned via script/spell NPCs when in combat too.

**Comment by Evolvee** [comment]
rev 2655
