### ISSUE TITLE
[NPC][Horde] Victor Ward (Undercity) - Apprentice Tailor

### ISSUE THREAD

**Issue by drewk8** [Atlantiss/NetherwingBugtracker#4063]
**Description**: 
Erroneous listing of know tailoring recipes.

**Current behavior**:
When checking this NPC to learn new tailoring recipes, when filtering for already know, it only lists two recipes (Brown Linen Pants + Simple Linen Pants, both having incorrect icons). 

**Expected behavior**: 
Should list know recipes, with correct icons.

**Server Revision**: 
2604

**Comment by drewk8** [comment]
Same issue with NPC "Snang" in Ogrimmar, Apprentice Tailor. I suspect there are others fitting this description, at least with tailors, if not with other profession trainers.

Server Revision:
2682

**Comment by Godmatik** [comment]
Technically confirmed - in Wrath these NPCs lost their ability to train recipes up to 75 but in TBC should still have them. But since the tailoring trainer itself in major cities all teach patterns until 300, it's irrelevant and not worth changing.
