### ISSUE TITLE
[NPC][Silverpine Forest] Sickly Refugee

### ISSUE THREAD

**Issue by maxturtlesc2** [Atlantiss/NetherwingBugtracker#4064]
[//]: # (Enclose links to things related to the bug using http://wowhead.com or any other TBC database.)
[//]: # (You can use screenshot ingame to visual the issue.)
[//]: # (Write your tickets according to the format:)
[//]: # ([Quest][Azuremyst Isle] Red Snapper - Very Tasty!)
[//]: # ([NPC] Magistrix Erona)
[//]: # ([Spell][Mage] Fireball)
[//]: # ([Npc][Drop] Ghostclaw Lynx)
[//]: # ([Web] Armory doesnt work)
[//]: # (To find server revision type `.server info` command in the game chat.)

**Description**: 
https://imgur.com/JKkPZqk
**Current behaviour**:
Sickly Refugee can use their abilities even when cc'd.
**Expected behaviour**: 
Sickly Refugee can't use their abilities while cc'd.
**Server Revision**:

**Comment by Evolvee** [comment]
what retard marked it with core

oh 
![image](https://user-images.githubusercontent.com/1942409/73592281-c40d3700-44f8-11ea-9f36-df2f0660d90b.png)

that explains it

-----

fixed in next rev
