### ISSUE TITLE
([Quest][Eversong Woods] Unexpected Results)

### ISSUE THREAD

**Issue by Znakharka** [Atlantiss/NetherwingBugtracker#4065]
[//]: # (Enclose links to things related to the bug using http://wowhead.com or any other TBC database.)
[//]: # (You can use screenshot ingame to visual the issue.)
[//]: # (Write your tickets according to the format:)
[//]: # ([Quest][Eversong Woods] Unexpected Results)
[//]: # ([NPC] Magistrix Erona)
[//]: # ([Spell][Mage] Fireball)
[//]: # ([Npc][Drop] Ghostclaw Lynx)
[//]: # ([Web] Armory doesnt work)
[//]: # (To find server revision type `.server info` command in the game chat.)

**Description**: 
Mobs coming all together instead of waves.
**Current behaviour**:

**Expected behaviour**: 

**Server Revision**:

**Comment by wtRCH** [comment]
Please provide more info. @Znakharka

**Comment by Kiperr** [comment]
https://youtu.be/dgupKoO6hRA she spawns 4 mobs together, there is no waves in this quest.
