### ISSUE TITLE
Mining

### ISSUE THREAD

**Issue by antikiller69** [Atlantiss/NetherwingBugtracker#4066]
[//]: # (Enclose links to things related to the bug using http://wowhead.com or any other TBC database.)
[//]: # (You can use screenshot ingame to visual the issue.)
[//]: # (Write your tickets according to the format:)
[//]: # ([Quest][Azuremyst Isle] Red Snapper - Very Tasty!)
[//]: # ([NPC] Magistrix Erona)
[//]: # ([Spell][Mage] Fireball)
[//]: # ([Npc][Drop] Ghostclaw Lynx)
[//]: # ([Web] Armory doesnt work)
[//]: # (To find server revision type `.server info` command in the game chat.)

**Description**: no vein spawns atm, very few

**Current behaviour**: no vein spawns
**Expected behaviour**: should have more vein spawns

**Server Revision**:

**Comment by wtRCH** [comment]
@Shanghi

**Comment by Tereneckla** [comment]
rev 3205
