### ISSUE TITLE
Logging off with combat bug kills you

### ISSUE THREAD

**Issue by Tixlenra** [Atlantiss/NetherwingBugtracker#4068]
[//]: # (Enclose links to things related to the bug using http://wowhead.com or any other TBC database.)
[//]: # (You can use screenshot ingame to visual the issue.)
[//]: # (Write your tickets according to the format:)
[//]: # ([Quest][Azuremyst Isle] Red Snapper - Very Tasty!)
[//]: # ([NPC] Magistrix Erona)
[//]: # ([Spell][Mage] Fireball)
[//]: # ([Npc][Drop] Ghostclaw Lynx)
[//]: # ([Web] Armory doesnt work)
[//]: # (To find server revision type `.server info` command in the game chat.)

**Description**: Logging off with combat bug kills you

**Current behaviour**: Logging off with combat bug kills you, even when there's no NPC's around.

**Expected behaviour**: Shouldn't get combat bug in the first place, but when you do, you shouldn't die because of it. 

**Server Revision**:

**Comment by Yasur7** [comment]
Yeah, many people experience that. Here's my pretty similar story:

I logged of at 17:00 server time at Badlands (I have been there 1st time, didn't unlock FP). When I logged back I saw myself dead at Arathi Highlands o.O Wasn't in any combat for sure.
