### ISSUE TITLE
[quest][hillsbrad] souvenirs of death. Human skulls can be pickpocketed

### ISSUE THREAD

**Issue by Zmol** [Atlantiss/NetherwingBugtracker#4069]
Skulls are pickpocketable.
Almost 100% success of pickpocketing their skulls

**Comment by wtRCH** [comment]
!? So they should be or not? Provide more info @Zmol

**Comment by Zmol** [comment]
I should not be able to pickpocket their skulls obviously :)

**Comment by Tixlenra** [comment]
Found this yesterday, very odd bug!

**Comment by Drayo** [comment]
Can no longer be pick pocketed. WoWhead just had an error.

Can be closed.
