### ISSUE TITLE
[Event][RP] Dark Portal Event horns

### ISSUE THREAD

**Issue by tcberk12** [Atlantiss/NetherwingBugtracker#407]
**Description**: 
I was able to witness the Dark Portal Event with Evolve

**Current behaviour**:
Currently, a series of horns plays at the beginning of the event, followed by a quote from Kazzak. Then, waves of demons spawn from the portal and attack the Alliance/Horde guards stationed aat the portal 

**Expected behaviour**: 
Horns should play at the beginning of every wave of demons, per Evolve.

**Server Revision**:

**Comment by Evolvee** [comment]
*per every cycle
cycle = all waves defeated

fixed
