### ISSUE TITLE
Graveyard Zone Bug (Auberdine)

### ISSUE THREAD

**Issue by TimWester** [Atlantiss/NetherwingBugtracker#4071]
[//]: # (Enclose links to things related to the bug using http://wowhead.com or any other TBC database.)
[//]: # (You can use screenshot ingame to visual the issue.)
[//]: # (Write your tickets according to the format:)
[//]: # ([Quest][Azuremyst Isle] Red Snapper - Very Tasty!)
[//]: # ([NPC] Magistrix Erona)
[//]: # ([Spell][Mage] Fireball)
[//]: # ([Npc][Drop] Ghostclaw Lynx)
[//]: # ([Web] Armory doesnt work)
[//]: # (To find server revision type `.server info` command in the game chat.)

**Description**: 

Spawning at wrong graveyard if you die in [Zone][Darkshore] Auberdine as horde,
you spawn at [Zone][Ashenvale] Splintertree Post's Graveyard.

**Current behaviour**:
Spawn as ghost in [Zone][Ashenvale] Splintertree Post's Graveyard.

**Expected behaviour**: 
Spawn as ghost in [Zone][Darkshore] North of Auberdine.

**Server Revision**:

**Comment by Upperfoot** [comment]
I can vouch for this being a problem too

This guide here made in 2009 details how it worked on retail

https://deathraygames.com/articles/walkthroughs/wow-horde-owl/

**Comment by Tereneckla** [comment]
fixed rev 3198
