### ISSUE TITLE
[NPC]Boulderfist mage#17137 shouldn't run away in fear

### ISSUE THREAD

**Issue by Tenoutoften** [Atlantiss/NetherwingBugtracker#4072]
**Description**: 
[[NPC]Boulderfist mage#17137](https://db.excalibur.ws/?npc=17137) shouldn't run away in fear(Ogres generally don't)
https://youtu.be/4WN7b9BGf8U?t=120

**Current behaviour**:
[[NPC]Boulderfist mage#17137](https://db.excalibur.ws/?npc=17137) runs away in fear.

**Expected behaviour**: 
Expected to not run away in fear

**Server Revision**: 
2604

**Comment by Evolvee** [comment]
rev 2655
