### ISSUE TITLE
[Core][Shaman] Totem not despawning

### ISSUE THREAD

**Issue by am3shan** [Atlantiss/NetherwingBugtracker#4073]
**Description**: shaman totems are not despawning after duration has run out

**Current behaviour**:
multiple totems up at the same time (only visual, not attacking)
**Expected behaviour**: 
totem destoyed after duration is 0s
**Server Revision**: 
2604

https://i.imgur.com/AmOXn60.jpg

**Comment by pesky89** [comment]
can be closed
