### ISSUE TITLE
[Quest][Darkshore]'Terenthis' NPC in doesn't turn in quest

### ISSUE THREAD

**Issue by Cyromatter** [Atlantiss/NetherwingBugtracker#4074]
[//]: # (Enclose links to things related to the bug using http://wowhead.com or any other TBC database.)
[//]: # (You can use screenshot ingame to visual the issue.)
[//]: # (Write your tickets according to the format:)
[//]: # ([Quest][Azuremyst Isle] Red Snapper - Very Tasty!)
[//]: # ([NPC] Magistrix Erona)
[//]: # ([Spell][Mage] Fireball)
[//]: # ([Npc][Drop] Ghostclaw Lynx)
[//]: # ([Web] Armory doesnt work)
[//]: # (To find server revision type `.server info` command in the game chat.)

**Description**: 
The NPC is a questgiver.
**Current behaviour**:
Upon completion of the quest the NPC cannot be spoken to
**Expected behaviour**: 
Should be able to spoken to and turn in quest. Other players, upon asked, are reporting the same issue.
**Server Revision**: 
2604

**Comment by Kiperr** [comment]
Did she had bugged RP after some quest? Like talking one sentence over and over ??

**Comment by Evolvee** [comment]
seems working now, reopen if it happens again

**Comment by The14me** [comment]
After u complete the quest and the RP start....another player cant  interact with the npc again.

**Comment by Evolvee** [comment]
what quest

**Comment by Evolvee** [comment]
ok i see , fixed in next rev

**Comment by Evolvee** [comment]
no wait -.- its fine... tell me what quest or record it

**Comment by Evolvee** [comment]
Its 4 months and noone responded with the quest name so.. closing
