### ISSUE TITLE
Junkboxes, Arnak Grimtotem

### ISSUE THREAD

**Issue by Erodraeda** [Atlantiss/NetherwingBugtracker#4076]
[//]: # (Enclose links to things related to the bug using http://wowhead.com or any other TBC database.)
[//]: # (You can use screenshot ingame to visual the issue.)
[//]: # (Write your tickets according to the format:)
[//]: # ([Quest][Azuremyst Isle] Red Snapper - Very Tasty!)
[//]: # ([NPC] Magistrix Erona)
[//]: # ([Spell][Mage] Fireball)
[//]: # ([Npc][Drop] Ghostclaw Lynx)
[//]: # ([Web] Armory doesnt work)
[//]: # (To find server revision type `.server info` command in the game chat.)

**Description**: 
Was questing in 1k Needles, and Arnak Grimtotem gave me a Battered Junkbox everytime I pick pocketed him (like 4 times). One of those junkboxes, when I opened, had a Warsong Report item, from a quest in Ashenvale(lol)
**Current behaviour**:
That mob has higher than usual chance to give a junkbox, and the junkboxes are giving items that should not be given.
**Expected behaviour**: 

**Server Revision**:

**Comment by Evolvee** [comment]
dont see it in its loot table
@Shanghi 
```
SELECT *
FROM item_loot_template WHERE entry = 16882
```

FeelsWeirdMan

**Comment by Shanghi** [comment]
I already fixed it but was just waiting to see if it was actually applied to the live realm before saying anything! I forgot to assign myself.
The rate of the junkbox is normal and getting it 4 times was just luck.

**Comment by Evolvee** [comment]
k
