### ISSUE TITLE
[Hunter] [Pet] Pets keep breaking freezing targets 

### ISSUE THREAD

**Issue by fishworld** [Atlantiss/NetherwingBugtracker#4077]
**Current behaviour**:

When you put a freezing trap on a target that is being attacked by the pet and the target is successfully freezed, the pet ignores the trap and just keep on attacking.

**Expected behaviour**: 

The pet should stop attack on targets that's being freezed, until you command them otherwise. This was working before but is now bugged.

**Comment by Falathrin** [comment]
This is still an issue.

**Comment by Manaci** [comment]
Fixed
