### ISSUE TITLE
[Uldaman][NPC] Galgan Firehammer boss has vanilla level value

### ISSUE THREAD

**Issue by Desst** [Atlantiss/NetherwingBugtracker#4080]
**Current behaviour**:
Galgan FIrehammer is level 45 which is vanilla value
**Expected behaviour**: 
should be level 40

**Server Revision**: 
2604

**Comment by Navedonar** [comment]
https://wow.gamepedia.com/Galgann_Firehammer 
 Patch 2.3.0 (2007-11-13): Level reduced from 45 to 40.

**Comment by Wolffenstein** [comment]
Fixed in rev 3389.
