### ISSUE TITLE
[Spell][Mage] Applying/removing Arcane Intellect yields unexpected changes in Spell Power when under SP buff

### ISSUE THREAD

**Issue by sinorius** [Atlantiss/NetherwingBugtracker#4082]
**Description**: When the player is under the influence of Manawraith (https://www.wowhead.com/npc=15648/manawraith#abilities) Arcane Residue (https://www.wowhead.com/spell=29109/arcane-residue) applying and then removing Arcane Intellect increases the Spell Power even more (20 SP from the buff + additional 20 SP after removing Arcane Intellect). Links to two videos showcasing the bug: 
https://www.twitch.tv/videos/362784233
https://www.twitch.tv/videos/362783922

** Steps to reproduce **: 

1. Start  reproducing without having Arcane Intellect on mage.
2. Kill Manawraith so you'll gain Arcane Residue and + 20 SP.
3. Apply Arcane Intellect.
4. You now have + 40 SP.
5. Remove Arcane Intellect - nothing changes - still +40 SP.
6. Wait for Arcane Residue to wear off (2 min).
7. Bonus SP is reduced to +20.
8. Apply Arcane Intellect -- unexpected +20 SP get removed.

Additionally, just as I wrote here: https://github.com/Atlantiss/NetherwingBugtracker/issues/3902#issuecomment-452017436, the SP does not increase the spell damage by the amount it should.

**Current behaviour**:
Weird things happen with SP after applying and removing Arcane Intellect.

**Expected behaviour**: 
Applying and removing Arcane Intellect should not change SP in any way.

**Server Revision**: 
2604

**Comment by Tereneckla** [comment]
Fixed
