### ISSUE TITLE
Voidwalker spell suffering does nothing

### ISSUE THREAD

**Issue by Jalapan** [Atlantiss/NetherwingBugtracker#4085]
[//]: # (Enclose links to things related to the bug using http://wowhead.com or any other TBC database.)
[//]: # (You can use screenshot ingame to visual the issue.)
[//]: # (Write your tickets according to the format:)
[//]: # ([Quest][Azuremyst Isle] Red Snapper - Very Tasty!)
[//]: # ([NPC] Magistrix Erona)
[//]: # ([Spell][Mage] Fireball)
[//]: # ([Npc][Drop] Ghostclaw Lynx)
[//]: # ([Web] Armory doesnt work)
[//]: # (To find server revision type `.server info` command in the game chat.)

**Description**: 
Voidwalker spell suffering does nothing when used
**Current behaviour**:
Voidwalker spell suffering does nothing
**Expected behaviour**: 
Taunts the target and increases the threat the Voidwalker generates against it for 5 seconds.
**Server Revision**:

**Comment by loveremoval** [comment]
Havent had problems with this
