### ISSUE TITLE
[Druid] Shapeshifted Crit Chance

### ISSUE THREAD

**Issue by Umyron** [Atlantiss/NetherwingBugtracker#4086]
Playing as a druid and when I shift to bear form, my crit chance is displayed as my exact weapon skill crit chance in both my character screen melee stats and tooltip for the "attack" spell in the spellbook.

**Current behaviour**:
If I level my current weapon skill, my shape-shifted crit chance goes up with it.

**Expected behaviour**: 
From what I've understood, it is not supposed to function this way in tbc; shapeshifted crit chance should be independent of weapon skill.

I do suspect that my crit chance is in fact different and its an issue with it not displaying the right calculations in my character screen and spellbook.

**Comment by Realnairoby** [comment]
Sources: 

> You dont have to level up your weapon skills actively as a feral druid. When you shift into cat or bear form, your "feral" weapon skill is automatically set to 5*your level (what it would be if you were maxxed in a particular weapon skill). (https://www.wowhead.com/forums&topic=3440)

> nope. feral attacks are based off you having max weapon skill for your level, regardless of what skill you possess with the weapon equipped.  (https://www.mmo-champion.com/threads/667765-Weapon-skill)

> As a Druid, when you are in a Cat, Bear or Dire Bear form, you automatically have the full 5 Weapon skill per level. (https://www.engadget.com/2008/01/29/shifting-perspectives-hit-rating-expertise-and-defense-skill-f/)

> Your "paw skill" is automatically maxed out when you ding. Your mace, staff, polearm, or whatever else skill has no impact on your Feral damage output at all, it only affects your damage while meleeing in caster form. (https://gamefaqs.gamespot.com/boards/534914-world-of-warcraft/56419045)

**Comment by tojothethief** [comment]
How this isn't fixed on Netherwing of all places baffles me. Even Sunwell fixed it

**Comment by devo6969** [comment]
This isnt an issue on the PTR
PTR - https://www.youtube.com/watch?v=edUJcdeRenA
