### ISSUE TITLE
Sharpening Stone Decreases Offhand Damage

### ISSUE THREAD

**Issue by 25toten** [Atlantiss/NetherwingBugtracker#4087]
[//]: # (Enclose links to things related to the bug using http://wowhead.com or any other TBC database.)
[//]: # (You can use screenshot ingame to visual the issue.)
[//]: # (Write your tickets according to the format:)
[//]: # ([Quest][Azuremyst Isle] Red Snapper - Very Tasty!)
[//]: # ([NPC] Magistrix Erona)
[//]: # ([Spell][Mage] Fireball)
[//]: # ([Npc][Drop] Ghostclaw Lynx)
[//]: # ([Web] Armory doesnt work)
[//]: # (To find server revision type `.server info` command in the game chat.)

**Description**: 
Applying sharpening stones slightly decreases the white damage on your offhand.This was tested on a warrior. Cannot confirm if it works on other classes like this. I wonder if offhand mastery is interfering with the item in some weird formula.

http://db.hellfire-tbc.com/?item=2871

Does this with rough, coarse, heavy and solid sharpening stones. I presume this occurs on all stones that add + damage.

**Current behaviour**:
+x damage works, but it subsequently decreases the white damage. 
**Expected behaviour**: 
**Server Revision**:

**Comment by Manaci** [comment]
It's because of the Warrior talent Dual Wield Specialization fucking something up with sharpening stone damage it seems.

**Comment by Godmatik** [comment]
Rev 4017 - working as intended, fixed at some point I guess,

Specced into Dual Wield Specialization and used an Adamantite Sharpening Stone on my off-hand only and did swings with it - then the same number of swings with no sharpening stone on and compared - the weapon with the stone did roughly 12 damage more on average when comparing normal attacks only. My sample size was only 30 non-crit swings each but looks good to me.
