### ISSUE TITLE
Tauren hitbox? too big

### ISSUE THREAD

**Issue by femdead** [Atlantiss/NetherwingBugtracker#4088]
Tauren hitbox is way too big or gives too much leeway, mobs are hitting/dazing from very far away when attempting to kite, even when the mob is slowed and therefore shouldn't get melee leeway.

**Comment by wtRCH** [comment]
Blizzlike.

**Comment by femdead** [comment]
@wtRCH if it's blizzlike your attack range would also be bigger but it's not; mobs are able to hit tauren from a range where the tauren can't attack back while moving

**Comment by Eckarte** [comment]
> @wtRCH if it's blizzlike your attack range would also be bigger but it's not; mobs are able to hit tauren from a range where the tauren can't attack back while moving

This. If it's Blizzlike you should let the Tauren hit as well. As it stands, you'll just end up with "out of range" messages.

**Comment by networm555** [comment]
I think its time to make Tauren classic-like. Large reach and hitbox. Just create a cow on the classic and make some adjustments. Because something feels way off.
