### ISSUE TITLE
Eating and drink aborted when entering combat

### ISSUE THREAD

**Issue by Jalapan** [Atlantiss/NetherwingBugtracker#4089]
[//]: # (Enclose links to things related to the bug using http://wowhead.com or any other TBC database.)
[//]: # (You can use screenshot ingame to visual the issue.)
[//]: # (Write your tickets according to the format:)
[//]: # ([Quest][Azuremyst Isle] Red Snapper - Very Tasty!)
[//]: # ([NPC] Magistrix Erona)
[//]: # ([Spell][Mage] Fireball)
[//]: # ([Npc][Drop] Ghostclaw Lynx)
[//]: # ([Web] Armory doesnt work)
[//]: # (To find server revision type `.server info` command in the game chat.)

**Description**: 
Eating and drink is aborted when entering combat
**Current behaviour**:
Eating and drink aborted when entering combat
**Expected behaviour**: 
eating and drinking should only be interrupted when hit
**Server Revision**:

**Comment by Manaci** [comment]
Fixed
