### ISSUE TITLE
[Core][pets] Pets doesn't despawn when you take a flight

### ISSUE THREAD

**Issue by eunuck1** [Atlantiss/NetherwingBugtracker#4090]
[//]: # (Enclose links to things related to the bug using http://wowhead.com or any other TBC database.)
[//]: # (You can use screenshot ingame to visual the issue.)
[//]: # (Write your tickets according to the format:)
[//]: # ([Quest][Azuremyst Isle] Red Snapper - Very Tasty!)
[//]: # ([NPC] Magistrix Erona)
[//]: # ([Spell][Mage] Fireball)
[//]: # ([Npc][Drop] Ghostclaw Lynx)
[//]: # ([Web] Armory doesnt work)
[//]: # (To find server revision type `.server info` command in the game chat.)

**Description**:  Currently pets doesn't despawn when pet classes take FP, so it quickly overruns it. I do not know if it is some issues with the class using pets when it lands, maybe someone else could update this.

**Current behaviour**: Pets doesn't despawn when you take a flight path

**Expected behaviour**: They should despawn when you take a flight path and appear again when you land

**Server Revision**: 2605
![bug13](https://user-images.githubusercontent.com/46464510/51078556-0fb72d80-16b7-11e9-9d78-71605d1cf40c.png)

**Comment by Utilbart** [comment]
The same thing happens whenever you already have a pet and spawn another (for example, you got a voidwalker and spawn an imp, the voidwalker does not despawn. You can even have the same entity in the game (for example 2x a voidwalker) with the same name (one controlled, the other one not despawned and stuck in the position where the new one was spawned).

**Comment by Manaci** [comment]
Fixed
