### ISSUE TITLE
[Quest] The Essence of Enmity

### ISSUE THREAD

**Issue by tbc123** [Atlantiss/NetherwingBugtracker#4091]
didnt work i use quest item after slain dragon nothing heppends quest item not working

**Comment by wtRCH** [comment]
Please provide with more details @tbc123 such as what should happen. Please follow template given when making new issue.

**Comment by tbc123** [comment]
https://www.youtube.com/watch?v=MU5FAC9E4LQ

**Comment by tbc123** [comment]
https://www.youtube.com/watch?v=MU5FAC9E4LQ but this i need use quest item on 45% hp

**Comment by teddys** [comment]
You are supposed to use the totem on a corpse, but currently that is not possible(says invalid target).

**Comment by Balanarr** [comment]
Was able to use it on the dragonkin while they were alive :/

**Comment by Manaci** [comment]
Dead/Fixed issue
