### ISSUE TITLE
mobs healing to full when vindication procs 

### ISSUE THREAD

**Issue by saulpaladin** [Atlantiss/NetherwingBugtracker#4092]
[//]: # (Enclose links to things related to the bug using http://wowhead.com or any other TBC database.)
[//]: # (You can use screenshot ingame to visual the issue.)
[//]: # (Write your tickets according to the format:)
[//]: # ([Quest][Azuremyst Isle] Red Snapper - Very Tasty!)
[//]: # ([NPC] Magistrix Erona)
[//]: # ([Spell][Mage] Fireball)
[//]: # ([Npc][Drop] Ghostclaw Lynx)
[//]: # ([Web] Armory doesnt work)
[//]: # (To find server revision type `.server info` command in the game chat.)

**Description**: 
sometimes when a mob is low vindication (ret pally talent) procs will heal them to full. I'm not entirely sure if its vindication but ive noticed this happening as it procs at times.

**Comment by Drayo** [comment]
https://github.com/Atlantiss/NetherwingBugtracker/issues/1808

**Comment by Wolffenstein** [comment]
Fixed in rev 2618.
