### ISSUE TITLE
[Spell][Hunter] Auto Shot not working when switching targets

### ISSUE THREAD

**Issue by augestir** [Atlantiss/NetherwingBugtracker#4093]
[//]: # (Enclose links to things related to the bug using http://wowhead.com or any other TBC database.)
[//]: # (You can use screenshot ingame to visual the issue.)
[//]: # (Write your tickets according to the format:)
[//]: # ([Quest][Azuremyst Isle] Red Snapper - Very Tasty!)
[//]: # ([NPC] Magistrix Erona)
[//]: # ([Spell][Mage] Fireball)
[//]: # ([Npc][Drop] Ghostclaw Lynx)
[//]: # ([Web] Armory doesnt work)
[//]: # (To find server revision type `.server info` command in the game chat.)

**Description**: When you tab target or switch targets by clicking, auto shot to interrupt itself several times (sometimes as long as 5+ seconds) before beginning to auto shot again.

**Current behaviour**: Auto shot not continuing when switching targets and interrupting itself for a prolonged period.

**Expected behaviour**: Auto shot should continue to fire when switching targets

**Server Revision**:

**Comment by wtRCH** [comment]
Already known issue, that's for wands too.
