### ISSUE TITLE
[Talents] ????? Missing a talent point on level up

### ISSUE THREAD

**Issue by Neccos** [Atlantiss/NetherwingBugtracker#4094]
missing a talent point on level up. dinged from a quest inside mara and then did not recieve a talent point. currently level 50 with only being able to spend 40 talent points. 

**Current behaviour**:

**Expected behaviour**: Should have 41 talent points to spend at lvl 50.

**Server Revision**:

**Comment by aresbrutus** [comment]
Can you please tell us your characters name?

**Comment by Manaci** [comment]
Dead issue
