### ISSUE TITLE
[NPC]Conjurer Luminrath#1954's Dancing swords hit way too hard(~x5)

### ISSUE THREAD

**Issue by Tenoutoften** [Atlantiss/NetherwingBugtracker#4095]
**Description**: 
[[NPC]Dancing Swords#21093](https://www.wowhead.com/npc=21093/dancing-sword#comments) is hitting significantly harder than it is suppose to (~1200-1500).

Spawned by [[NPC]Conjurer Luminrath#19544](https://www.wowhead.com/npc=19544/conjurer-luminrath#abilities) using [[Spell]Summon Dancing Sword#36110](https://www.wowhead.com/spell=36110/summon-dancing-sword)

**Current behaviour**:
Hitting fast for ~1200-1500.

**Expected behaviour**: 
Expect ~200-400

**Server Revision**: 
2605

**Comment by wtRCH** [comment]
Can you provide with some proof of that?

**Comment by bekonja** [comment]
Can confirm, swords hit like a trucks.
What type of proof you need? Noone mentioned sword damage on wowhead since 2007. Do you think people wouldnt notice for 10 years that some casual mob in leveling zone hits you like dungeon elite. Lack of proof is proof by itself, nerf it.

**Comment by efagrgagg** [comment]
https://imgur.com/Yl7xlmV smashing me for 1150 no universe where its supposed to do this damage put any random number in that doesn't 3shot us ty

**Comment by Skitter92** [comment]
![luminrath1](https://user-images.githubusercontent.com/46928262/51539310-47da1100-1e19-11e9-9fda-f25c86f4d016.png)
![luminrath2](https://user-images.githubusercontent.com/46928262/51539311-47da1100-1e19-11e9-91e4-188225b1a0a9.png)

For what is supposed to be a 1 person mob, that's pretty ridiculous.

**Comment by rychersky** [comment]
Dancing Sword's melee swing hits Terrez for 1064 Physical. 

There's no way that this is intended.

**Comment by lildarlin** [comment]
Can confirm it.
<img width="338" alt="screen shot 2019-02-02 at 12 32 29" src="https://user-images.githubusercontent.com/36848576/52163739-b014d680-26e6-11e9-9215-8bef12fb8438.png">

**Comment by Baelek** [comment]
This issue is still ongoing:
[05:35:55] Dancing Sword's melee swing hits Baelek for 1349 Physical. 
[05:35:56] Dancing Sword's melee swing hits Baelek for 1369 Physical. 
[05:35:58] Dancing Sword's attack was dodged by Baelek. 
[05:35:59] Dancing Sword's melee swing hits Baelek for 2112 Physical. (Critical) 
[05:36:01] Dancing Sword's melee swing hits Baelek for 1414 Physical. 

Taking over 6k damage in the span of 5 seconds is severely overtuned and needs to be reduced to a more reasonable number.

**Comment by hbjose** [comment]
It isnt solved :( U wont find a source about the dmg of the cast.

**Comment by UijoYojimbob** [comment]
![WoWScrnShot_111619_202446](https://user-images.githubusercontent.com/57849826/69001579-3afa4280-08af-11ea-984a-10a9878632ba.jpg)

Can confirm, this still hits VERY hard because it is an elite mob upon summoning. I suggest just making it a normal mob.

**Comment by Puppetmast0r** [comment]
Oh thank god it's not just me then.
My mage killed him without a problem half a year ago so I couldn't figure out what I was doing differently on my new shadow priest.
I basically get killed within 3 swings.
