### ISSUE TITLE
[Quest] [Bloodmyst Isle] Ending Their World

### ISSUE THREAD

**Issue by EatTidePods** [Atlantiss/NetherwingBugtracker#4096]
**Description**: 
https://tbc-twinhead.twinstar.cz/?quest=9759#comments

**Current behaviour**:
I did not get credit for the escort completion, except my party members did. In fact I got a ''failed'' at the end.

**Expected behaviour**: 
All party members get completion on the end of the escort quest.

**Server Revision**: 
[Megathread][Quest] Issues with Escort Quests(React state, Faction, Interaction, Buff reset, Pathing) #3678

**Comment by devo6969** [comment]
Did you accept the quest and share to others? Did you die and release before the RP event was over? Did you run out of range of the RP event? Need more explanation please :D.

**Comment by nonameform** [comment]
There is another issue associated with this quest.

Whenever Demolitionist Legoso addresses player character by name during the escort, there is $n instead of the name. I believe it should be %n to work correctly.

**Comment by Godmatik** [comment]
Fixed per #6336 

Closing
