### ISSUE TITLE
[Netherstorm][Misc][Quest][NPC]#10182/10305/10306/10307 should turn neutral to players completing their quests

### ISSUE THREAD

**Issue by Tenoutoften** [Atlantiss/NetherwingBugtracker#4097]
**Description**: 
These NPC should become neutral to the player upon completing their quests.

* [[NPC]Battle-Mage Dathric#19543](https://www.wowhead.com/npc=19543/battle-mage-dathric) - [Quest#10182](https://www.wowhead.com/quest=10182/battle-mage-dathric)
* [[NPC]Abjurist Belmara#19546](https://www.wowhead.com/npc=19546/abjurist-belmara) - [Quest#10305](https://www.wowhead.com/quest=10305/abjurist-belmara)
* [[NPC]Conjurer Luminrath#19544](https://www.wowhead.com/npc=19544/conjurer-luminrath) - [Quest#10306](https://www.wowhead.com/quest=10306/conjurer-luminrath)
* [[NPC]Cohlien Frostweave#19545](https://www.wowhead.com/npc=19545/cohlien-frostweaver) - [Quest#10307](https://www.wowhead.com/quest=10307/cohlien-frostweaver)

![](https://i.gyazo.com/91944f3e01c8339a4c739d2829152513.png)

**Current behaviour**:
Remain hostile.

**Expected behaviour**: 
Expected to become neutral to the player after completing their quests

**Server Revision**: 
2604

**Comment by Evolvee** [comment]
looking for the spell_area id
