### ISSUE TITLE
[Quest]Show them Gnome Mercy! Infernal trigger from flesh mobs & Not sharing party loot on Prince Object

### ISSUE THREAD

**Issue by Tenoutoften** [Atlantiss/NetherwingBugtracker#4098]
**Description**: 
After killing [[NPC]Nexus-Prince Razaan#21057](https://www.wowhead.com/npc=21057/nexus-prince-razaan) for [[Quest]Show them Gnome Mercy!#10675](https://www.wowhead.com/quest=10675/show-them-gnome-mercy) this spawns [[Object]Collection of Souls#185033](https://www.wowhead.com/object=185033/collection-of-souls) all party members should be able to loot the box before it disappears.

https://github.com/Atlantiss/NetherwingBugtracker/issues/2423

In addition, killing the flesh mobs would display an infernal trigger rather than the yellow glow(which does work for the other humanoid NPCs)
![](https://i.gyazo.com/2f1b6dd769a00f89d9ce8ddb6d5e38fe.png)

**Current behaviour**:
Once a party member loots the object it floats away.
Infernal triggers from the neutral mobs.

**Expected behaviour**: 
All party members on quest should be able to loot it
No infernal triggers.

**Server Revision**: 
2604

**Comment by The14me** [comment]
That must be fixed with laters loot Rework.
Rev.3482.

**Comment by Tereneckla** [comment]
Current: Box despawns after 1 person loots it.
Expected: Multiple people should be able to loot it, until it despawns based on its timer

https://www.wowhead.com/quest=10675/show-them-gnome-mercy#comments:id=118260
https://www.wowhead.com/quest=10675/show-them-gnome-mercy#comments:id=152628

**Comment by Godmatik** [comment]
Rev 4018 - no longer an issue - the box does not despawn after 1 person loots it.
