### ISSUE TITLE
[Quest][Game Object]Corki cages remain open until crash/restart

### ISSUE THREAD

**Issue by Tenoutoften** [Atlantiss/NetherwingBugtracker#4099]
**Description**: 
This report is valid to these Corki cages. When someone opens it it will not shut until server crash/restart
https://github.com/Atlantiss/NetherwingBugtracker/issues/2528

https://db.excalibur.ws/?object=182350
https://db.excalibur.ws/?object=182521

**Current behaviour**:
Doesn't close until restart/crash

**Expected behaviour**: 
Expected to close within a reasonable amount of time ~30-60s

**Server Revision**: 
2605

**Comment by Tenoutoften** [comment]
First one seems to work correctly

**Comment by Evolvee** [comment]
rev 2655
