### ISSUE TITLE
High level mobs 

### ISSUE THREAD

**Issue by AlteredAli** [Atlantiss/NetherwingBugtracker#41]
[//]: # (Enclose links to things related to the bug using http://wowhead.com or any other TBC database.)
[//]: # (You can use screenshot ingame to visual the issue.)
[//]: # (Write your tickets according to the format:)
[//]: # ([Quest][Azuremyst Isle] Red Snapper - Very Tasty!)
[//]: # ([NPC] Magistrix Erona)
[//]: # ([Spell][Mage] Fireball)
[//]: # ([Npc][Drop] Ghostclaw Lynx)
[//]: # ([Web] Armory doesnt work)

**Description**: 
The grub show's its level even though it should be a skull
![wowscrnshot_092318_070242](https://user-images.githubusercontent.com/43499721/45921737-ce7bf180-befe-11e8-9cd9-461d5fd6e8cc.jpg)
![wowscrnshot_092318_070243](https://user-images.githubusercontent.com/43499721/45921738-d0de4b80-befe-11e8-99fe-6036f5b09110.jpg)

**Current behaviour**:

**Expected behaviour**: 

**Server Revision**:

**Comment by Drayo** [comment]
Pretty sure neutral mobs cannot be level ?? unless they are a boss. So this is working as indented.
