### ISSUE TITLE
[Hunter] 2 Hand Weapon Visual Bug

### ISSUE THREAD

**Issue by LushenWOP** [Atlantiss/NetherwingBugtracker#4100]
Hey Team!
Im a Hunter at the lvl 16. I have the following problem: My 2 hand weapon, which is normally displayed on my back, always bends away. So I don't see it on my back. Normally it is on my back. If I pull them out with the "Z" key, I'll see them again. If I then attack it again with my bow, it is gone.

Best Regards,
Lushen

**Comment by wtRCH** [comment]
Show some images, screenshots and what weapon do you use. Both melee and ranged.

**Comment by wtRCH** [comment]
Show some images, screenshots and what weapon do you use. Both melee and ranged. @LushenWOP

**Comment by LushenWOP** [comment]
http://prntscr.com/m6fkr2

There you see. Its not caused by the Quiver on the back while using the bow. (Because on the image I didnt used the bow).

Im using a 2 Hand Axe & a Bow.

**Comment by LushenWOP** [comment]
"Axe of Orgrimmar" & "Heavy Shortbow"

**Comment by Manaci** [comment]
Fixed
