### ISSUE TITLE
Using items that share healthstone CD prevent casting Lesser Heal

### ISSUE THREAD

**Issue by Desparto** [Atlantiss/NetherwingBugtracker#4101]
[//]: # (Enclose links to things related to the bug using http://wowhead.com or any other TBC database.)
[//]: # (You can use screenshot ingame to visual the issue.)
[//]: # (Write your tickets according to the format:)
[//]: # ([Quest][Azuremyst Isle] Red Snapper - Very Tasty!)
[//]: # ([NPC] Magistrix Erona)
[//]: # ([Spell][Mage] Fireball)
[//]: # ([Npc][Drop] Ghostclaw Lynx)
[//]: # ([Web] Armory doesnt work)
[//]: # (To find server revision type `.server info` command in the game chat.)

**Description**: 
I have used two items that share cooldown with healthstones (crystalized mana residue and cracked power core). While the 2 minute cooldown on these items is in place, I am unable to cast Lesser Heal. I have not tested this with other heals as I am still low level, but am concerned that this will mean using a healthstone will prevent the caster casting heals for 2 mins afterwards.
**Current behaviour**:
Cannot cast heals for 2 mins after using an item which shares the healthstone cooldown (error message says "spell is not ready yet"
**Expected behaviour**: 
Should be able to cast heals as expected.
**Server Revision**: 
2605

**Comment by Tereneckla** [comment]
Fixed
