### ISSUE TITLE
[Quest]Whispers of the Raven God, Third Prohecy doesn't give credit

### ISSUE THREAD

**Issue by Tenoutoften** [Atlantiss/NetherwingBugtracker#4102]
**Description**: 
https://github.com/Atlantiss/NetherwingBugtracker/issues/2243
The Third Prophecy doesn't trigger after one of our players got credit no one else did afterwards.

**Current behaviour**:
Doesn't give credit

**Expected behaviour**: 
Expected to get credit granted you have the buff

**Server Revision**: 
2605

**Comment by Anduyon** [comment]
Can confirm.

**Comment by totaemoeggerli** [comment]
I got 1 2 and 3. 3 of the 4 objects say first when you hover over them.

**Comment by Wolffenstein** [comment]
Fixed in rev 2631.
