### ISSUE TITLE
[Quest] "WANTED: Baron Longshore" Respawntimer broken

### ISSUE THREAD

**Issue by LushenWOP** [Atlantiss/NetherwingBugtracker#4103]
Hey fellas,
I'm just questing and have determined that a respawntimer is broken.
At the Quest "WANTED: Baron Longshore" from "Gazlowe" you have to kill
"Baron Longshore" and get his head. Im camping here at his spawnpoint for around 45 minutes (with a full group) and he isnt spawning since 45mins. (We saw him right before we came here from another group so he is not bugged in general) just the respawntimer is broke.

Best Regards,
Lushen

**Comment by Brasso** [comment]
![image](https://user-images.githubusercontent.com/44345420/51080475-da253b00-16dc-11e9-9c9e-65ddd3c8d8fa.png)

**Comment by LushenWOP** [comment]
We were a group camping all spots

**Comment by LushenWOP** [comment]
Maybe some1 wasnt at this point. Thanks!
