### ISSUE TITLE
[WoW Error] Game Crashing After Server Became Stable

### ISSUE THREAD

**Issue by jasonbourne109** [Atlantiss/NetherwingBugtracker#4104]
My game client is crashing with no warning. Not sure what triggers this either. Below is a copy of the error report (character name omitted - I can send in a private message if necessary) that shows up and asks me if I want to send this information to Blizzard.

This could be a problem on my end. I'm coming here because this started happening after the server became more stable as of today/yesterday.

--
WoWBuild: 18606
Realm: Netherwing [37.187.251.149:8095]
Local Zone: Undercity
Local Player: [omitted], 0000000000006788, (1480.64,182.357,-61.5033)
Add Ons: AtlasLoot QuestHelper Recount 

=========================================================
Assertion Failed!

 App:         /Applications/World of Warcraft TBC/World of Warcraft.app
 File:        /Volumes/F2/usrbuild/xb/build/WoW_8606patch2.4.3/WoW/Source/Mac/../ObjectMgrClient/ObjectMgrClient.cpp
 Line:        2025
 Error Code:  0x85100086
 Time:        2019-01-12 20.38.56 EST

 Assertion:   Illegal client GUID dereference at /Volumes/F2/usrbuild/xb/build/WoW_8606patch2.4.3/WoW/Source/Mac/../Object/ObjectClient/Movement_C.cpp:73! Provided GUID 0xF1100050AF001DDB

---------------------------------------------------------
Thread 0 (0x303) (Current)
  0 0x0004393a <unknown>
  1 0x00043f38 <unknown>
  2 0x000512e8 <unknown>
  3 0x000049c5 <unknown>
  4 0x000050f8 <unknown>
  5 0x0009aaf7 <unknown>
  6 0x0038b8de <unknown>
  7 0x0031e06f <unknown>
  8 0x0008ded3 <unknown>
  9 0x000946ad <unknown>
 10 0x00251fb7 <unknown>
 11 0x0025203f <unknown>
 12 0x000a00f2 <unknown>
 13 0x000a0b7e <unknown>
 14 0x000a1def <unknown>
 15 0x000a31b6 <unknown>
 16 0x003a33f6 <unknown>
 17 0x003a4972 <unknown>
 18 0x005dd68e <unknown>
 19 0x0017c905 <unknown>
 20 0x0000b5ea <unknown>
 21 0x002bb224 <unknown>
 22 0x002c05f7 <unknown>
 23 0x002c0882 <unknown>
 24 0x00011f05 <unknown>
 25 0x000036f9 <unknown>
 26 0x92f3bbca _InvokeEventHandlerUPP(OpaqueEventHandlerCallRef*, OpaqueEventRef*, void*, long (*)(OpaqueEventHandlerCallRef*, OpaqueEventRef*, void*)) + 26
 27 0x92ed507c DispatchEventToHandlers(EventTargetRec*, OpaqueEventRef*, HandlerCallRec*) + 2027
 28 0x92ed41da SendEventToEventTargetInternal(OpaqueEventRef*, OpaqueEventTargetRef*, HandlerCallRec*) + 376
 29 0x92ed4056 _SendEventToEventTargetWithOptions + 40
 30 0x92eef0a1 ToolboxEventDispatcherHandler(OpaqueEventHandlerCallRef*, OpaqueEventRef*, void*) + 1306
 31 0x92ed54fb DispatchEventToHandlers(EventTargetRec*, OpaqueEventRef*, HandlerCallRec*) + 3178
 32 0x92ed41da SendEventToEventTargetInternal(OpaqueEventRef*, OpaqueEventTargetRef*, HandlerCallRec*) + 376
 33 0x92eef62d _SendEventToEventTarget + 33
 34 0x9306fef5 _ToolboxEventDispatcher + 82
 35 0x9306fdbb _RunApplicationEventLoop + 192
 36 0x0000382a <unknown>
 37 0x000024fe <unknown>
 38 0x00002425 <unknown>
 39 0x00000001 <unknown>

Thread 1 (0x1d03)
  0 0xa7b6fabe ___workq_kernreturn + 10
  1 0xa7c1f9a1 __pthread_wqthread + 422
  2 0xa7c1f782 _start_wqthread + 34
  3 0xffffff00 <unknown>

Thread 2 (0x6103)
  0 0xa7b6e2fe _mach_wait_until + 10
  1 0xa7af4b0e _nanosleep + 322
  2 0xa7af4993 _usleep + 54
  3 0x0004e178 <unknown>
  4 0x00044a61 <unknown>
  5 0xa7c205e8 __pthread_body + 137
  6 0xa7c237d7 __pthread_start + 82
  7 0xa7c1f7a6 _thread_start + 34
  8 0x00000000 <unknown>

Thread 3 (0xa003)
  0 0xa7b8d54a ___sem_wait_nocancel + 10
  1 0x00044a61 <unknown>
  2 0xa7c205e8 __pthread_body + 137
  3 0xa7c237d7 __pthread_start + 82
  4 0xa7c1f7a6 _thread_start + 34
  5 0x00000000 <unknown>

Thread 4 (0x6203)
  0 0xa7b8d54a ___sem_wait_nocancel + 10
  1 0x00044a61 <unknown>
  2 0xa7c205e8 __pthread_body + 137
  3 0xa7c237d7 __pthread_start + 82
  4 0xa7c1f7a6 _thread_start + 34
  5 0x00000000 <unknown>

Thread 5 (0x9f03)
  0 0xa7b8d54a ___sem_wait_nocancel + 10
  1 0x00044a61 <unknown>
  2 0xa7c205e8 __pthread_body + 137
  3 0xa7c237d7 __pthread_start + 82
  4 0xa7c1f7a6 _thread_start + 34
  5 0x00000000 <unknown>

Thread 6 (0x6603)
  0 0xa7b6fabe ___workq_kernreturn + 10
  1 0xa7c1f9a1 __pthread_wqthread + 422
  2 0xa7c1f782 _start_wqthread + 34
  3 0x001e4008 <unknown>

Thread 7 (0x6c2b)
  0 0xa7b6e1a2 _mach_msg_trap + 10
  1 0xa7b6e6f3 _mach_msg + 47
  2 0x99ef2c68 _glcDebugListener + 416
  3 0xa7c205e8 __pthread_body + 137
  4 0xa7c237d7 __pthread_start + 82
  5 0xa7c1f7a6 _thread_start + 34
  6 0x00000000 <unknown>

Thread 8 (0x8703)
  0 0x9b21e09c Security::CssmClient::DbImpl::deactivate() + 0
  1 0x9b14d01c Security::CssmClient::SSDbImpl::~SSDbImpl() + 26
  2 0x9b0fb71d Security::RefPointer<Security::CssmClient::ObjectImpl>::release() + 63
  3 0x9b1fe929 Security::RefPointer<Security::CssmClient::ObjectImpl>::~RefPointer() + 19
  4 0x9b2b9354 Security::KeychainCore::KeychainImpl::~KeychainImpl() + 274
  5 0x9b14cfad Security::KeychainCore::KeychainImpl::~KeychainImpl() + 15
  6 0x9b0fb804 Security::CFClass::refCountForType(long, void const*) + 126
  7 0x939e7793 __CFRelease + 511
  8 0x9b305b0f invocation function for block in Security::KeychainCore::StorageManager::tickleKeychain(Security::KeychainCore::KeychainImpl*) + 26
  9 0xa79dfa78 __dispatch_call_block_and_release + 15
 10 0xa79dfabb __dispatch_client_callout + 58
 11 0xa79ef3f0 __dispatch_root_queue_drain + 636
 12 0xa79efa86 __dispatch_worker_thread2 + 98
 13 0xa7c1fa16 __pthread_wqthread + 539
 14 0xa7c1f782 _start_wqthread + 34
 15 0x54485244 <unknown>

Thread 9 (0x8107)
  0 0xa7b6e1a2 _mach_msg_trap + 10
  1 0xa7b6e6f3 _mach_msg + 47
  2 0xa7b86382 _mach_msg_server + 313
  3 0x0002c638 <unknown>
  4 0xa7c205e8 __pthread_body + 137
  5 0xa7c237d7 __pthread_start + 82
  6 0xa7c1f7a6 _thread_start + 34
  7 0x00000000 <unknown>

Thread 10 (0x8003)
  0 0xa7b6e2fe _mach_wait_until + 10
  1 0xa7af4b0e _nanosleep + 322
  2 0xa7af4993 _usleep + 54
  3 0x00014e91 <unknown>
  4 0x000d78b7 <unknown>
  5 0x0010ca43 <unknown>
  6 0x0010cc30 <unknown>
  7 0x952986c1 -[NSThread main] + 39
  8 0x95298570 ___NSThread__start__ + 1242
  9 0xa7c205e8 __pthread_body + 137
 10 0xa7c237d7 __pthread_start + 82
 11 0xa7c1f7a6 _thread_start + 34
 12 0x00000000 <unknown>

Thread 11 (0x7e03)
  0 0xa7b717b2 ___psynch_cvwait + 10
  1 0xa7c23b30 __pthread_cond_wait + 751
  2 0xa7c215cd _pthread_cond_wait + 25
  3 0x0028af73 <unknown>
  4 0x0006df0c <unknown>
  5 0x0010ca43 <unknown>
  6 0x0010cc30 <unknown>
  7 0x952986c1 -[NSThread main] + 39
  8 0x95298570 ___NSThread__start__ + 1242
  9 0xa7c205e8 __pthread_body + 137
 10 0xa7c237d7 __pthread_start + 82
 11 0xa7c1f7a6 _thread_start + 34
 12 0x00000000 <unknown>

Thread 12 (0xc21b)
  0 0xa7b6e1a2 _mach_msg_trap + 10
  1 0xa7b6e6f3 _mach_msg + 47
  2 0x934e9a82 HALB_MachPort::SendMessageWithReply(unsigned int, unsigned int, unsigned long, unsigned long, mach_msg_header_t*, bool, unsigned int) + 126
  3 0x934c1c3b HALB_MachPort::SendSimpleMessageWithSimpleReply(unsigned int, unsigned int, int, int&, bool, unsigned int) + 49
  4 0x934bebcb HALC_ProxyIOContext::IOWorkLoop() + 1589
  5 0x934be342 HALC_ProxyIOContext::IOThreadEntry(void*) + 236
  6 0x934f26d0 invocation function for block in HALC_ProxyIOContext::HALC_ProxyIOContext(unsigned long, unsigned int) + 20
  7 0x934bdfcf HALB_IOThread::Entry(void*) + 71
  8 0xa7c205e8 __pthread_body + 137
  9 0xa7c237d7 __pthread_start + 82
 10 0xa7c1f7a6 _thread_start + 34
 11 0x00000000 <unknown>

Thread 13 (0x13803)
  0 0xa7b6e2fe _mach_wait_until + 10
  1 0x949b5075 _MPDelayUntil + 22
  2 0x0068f807 <unknown>
  3 0x006b52a9 <unknown>
  4 0xa7c205e8 __pthread_body + 137
  5 0xa7c237d7 __pthread_start + 82
  6 0xa7c1f7a6 _thread_start + 34
  7 0x00000000 <unknown>

Thread 14 (0x13607)
  0 0xa7b6e2fe _mach_wait_until + 10
  1 0x949b5075 _MPDelayUntil + 22
  2 0x0068f807 <unknown>
  3 0x006b52a9 <unknown>
  4 0xa7c205e8 __pthread_body + 137
  5 0xa7c237d7 __pthread_start + 82
  6 0xa7c1f7a6 _thread_start + 34
  7 0x00000000 <unknown>

Thread 15 (0x13503)
  0 0xa7b717b2 ___psynch_cvwait + 10
  1 0xa7c23b30 __pthread_cond_wait + 751
  2 0xa7c231da _pthread_cond_timedwait + 27
  3 0x0028ae6d <unknown>
  4 0x002ab8f8 <unknown>
  5 0x002aba42 <unknown>
  6 0x0010ca43 <unknown>
  7 0x0010cc30 <unknown>
  8 0x952986c1 -[NSThread main] + 39
  9 0x95298570 ___NSThread__start__ + 1242
 10 0xa7c205e8 __pthread_body + 137
 11 0xa7c237d7 __pthread_start + 82
 12 0xa7c1f7a6 _thread_start + 34
 13 0x00000000 <unknown>

Thread 16 (0x13403)
  0 0xa7b73406 ___select_nocancel + 10
  1 0xa7b7137d _select + 78
  2 0x002aae38 <unknown>
  3 0x002abdf6 <unknown>
  4 0x0010ca43 <unknown>
  5 0x0010cc30 <unknown>
  6 0x952986c1 -[NSThread main] + 39
  7 0x95298570 ___NSThread__start__ + 1242
  8 0xa7c205e8 __pthread_body + 137
  9 0xa7c237d7 __pthread_start + 82
 10 0xa7c1f7a6 _thread_start + 34
 11 0x00000000 <unknown>

Thread 17 (0x12d0b)
  0 0xa7b6e1a2 _mach_msg_trap + 10
  1 0xa7b6e6f3 _mach_msg + 47
  2 0x938eaaa9 ___CFRunLoopServiceMachPort + 289
  3 0x938ea16a ___CFRunLoopRun + 3196
  4 0x938e91f1 _CFRunLoopRunSpecific + 584
  5 0x939021ef _CFRunLoopRunInMode + 82
  6 0x92b62c6f -[__CoreSchedulingSetRunnable runForever] + 654
  7 0x92b62860 +[__CoreSchedulingSetRunnable _run:] + 129
  8 0x952986c1 -[NSThread main] + 39
  9 0x95298570 ___NSThread__start__ + 1242
 10 0xa7c205e8 __pthread_body + 137
 11 0xa7c237d7 __pthread_start + 82
 12 0xa7c1f7a6 _thread_start + 34
 13 0x00000000 <unknown>

Thread 18 (0xcf17)
  0 0xa7b8d54a ___sem_wait_nocancel + 10
  1 0x006b5275 <unknown>
  2 0xa7c205e8 __pthread_body + 137
  3 0xa7c237d7 __pthread_start + 82
  4 0xa7c1f7a6 _thread_start + 34
  5 0x00000000 <unknown>

Thread 19 (0x1270f)
  0 0xa7b71126 _pread$NOCANCEL$UNIX2003 + 10
  1 0x0004d187 <unknown>
  2 0x0004d2dc <unknown>
  3 0x00035464 <unknown>
  4 0x00034800 <unknown>
  5 0x0079d85a <unknown>
  6 0x0079dc21 <unknown>
  7 0x0004edd4 <unknown>
  8 0x0004d92a <unknown>
  9 0x0004d648 <unknown>
 10 0x00045a3a <unknown>
 11 0x000330dc <unknown>
 12 0x000507d7 <unknown>
 13 0x000643a2 <unknown>
 14 0x003a4e05 <unknown>
 15 0x006d5ddd <unknown>
 16 0x006af69e <unknown>
 17 0x006b036d <unknown>
 18 0x006b03b9 <unknown>
 19 0x006b5297 <unknown>
 20 0xa7c205e8 __pthread_body + 137
 21 0xa7c237d7 __pthread_start + 82
 22 0xa7c1f7a6 _thread_start + 34
 23 0x00000000 <unknown>

Thread 20 (0x10c6f)
  0 0xa7b717b2 ___psynch_cvwait + 10
  1 0xa7c23b30 __pthread_cond_wait + 751
  2 0xa7c231da _pthread_cond_timedwait + 27
  3 0x0028ae6d <unknown>
  4 0x00512f76 <unknown>
  5 0x0010ca43 <unknown>
  6 0x0010cc30 <unknown>
  7 0x952986c1 -[NSThread main] + 39
  8 0x95298570 ___NSThread__start__ + 1242
  9 0xa7c205e8 __pthread_body + 137
 10 0xa7c237d7 __pthread_start + 82
 11 0xa7c1f7a6 _thread_start + 34
 12 0x00000000 <unknown>

Thread 21 (0x759b)
  0 0xa7b6e2fe _mach_wait_until + 10
  1 0x949b5075 _MPDelayUntil + 22
  2 0x0068f807 <unknown>
  3 0x006b52a9 <unknown>
  4 0xa7c205e8 __pthread_body + 137
  5 0xa7c237d7 __pthread_start + 82
  6 0xa7c1f7a6 _thread_start + 34
  7 0x00000000 <unknown>

Thread 22 (0x6e0f)
  0 0xa7b8d54a ___sem_wait_nocancel + 10
  1 0x00044a61 <unknown>
  2 0xa7c205e8 __pthread_body + 137
  3 0xa7c237d7 __pthread_start + 82
  4 0xa7c1f7a6 _thread_start + 34
  5 0x00000000 <unknown>

Thread 23 (0x12507)
  0 0xa7b8d54a ___sem_wait_nocancel + 10
  1 0x00044a61 <unknown>
  2 0xa7c205e8 __pthread_body + 137
  3 0xa7c237d7 __pthread_start + 82
  4 0xa7c1f7a6 _thread_start + 34
  5 0x00000000 <unknown>

Thread 24 (0x12317)
  0 0xa7b8d54a ___sem_wait_nocancel + 10
  1 0x00044a61 <unknown>
  2 0xa7c205e8 __pthread_body + 137
  3 0xa7c237d7 __pthread_start + 82
  4 0xa7c1f7a6 _thread_start + 34
  5 0x00000000 <unknown>

Thread 25 (0x1082b)
  0 0xa7b6fabe ___workq_kernreturn + 10
  1 0xa7c1f9a1 __pthread_wqthread + 422
  2 0xa7c1f782 _start_wqthread + 34
  3 0xa7be7145 _tiny_malloc_should_clear + 14

Thread 26 (0xd347)
  0 0x00000000 <unknown>

=========================================================

**Comment by Drayo** [comment]
Disable Add-ons and delete the Cache Folder, see if that helps.

**Comment by 0vertime** [comment]
Where did you logout? Might need GM to teleport you.

**Comment by Furies1** [comment]
I'm having the same issue around most sorts of teleports. It doesn't happen everytime tho.

Boats, elevators, Tram from SW to IF are are things that make me DC very often. Have to login with Wine to move character away from the zone and then i can log back in with MAC client.

**Comment by nazarik** [comment]
Could you please prioritise this? Other places of crashes are Thousand Needles elevs closer to Tanaris and suspect Shattrath city Scryers elevator

**Comment by Easyfraggy** [comment]
Try lowering your terrain distance untill someone can look at this.

**Comment by nazarik** [comment]
Alliance Zangarmarsh Telredor's elevator yet another crash

**Comment by ottenby** [comment]
was this ever solved?
