### ISSUE TITLE
[Quest][Undercity]The Prodigal Lich Returns

### ISSUE THREAD

**Issue by Marangwe** [Atlantiss/NetherwingBugtracker#4105]
[//]: # https://www.wowhead.com/quest=411/the-prodigal-lich-returns
[//]: # https://i.imgur.com/vm40Tc9.jpg
[//]: # (Write your tickets according to the format:)
[//]: # ([Quest][Undercity] The Prodigal Lich Returns)
[//]: # ([NPC] Bethor Iceshard)

[//]: # 2605

**Description**: 
Bethor summons the visage of Gunthor. 

**Current behaviour**:
 Lots of players are doing this quest and the visage isn't despawning.  Causes a loss of FPS when in the area. 

**Expected behaviour**: 
Visage of Gunthor should depsawn
**Server Revision**:

**Comment by Tereneckla** [comment]
Fixed
