### ISSUE TITLE
[EPL] Of Forgotten Memories

### ISSUE THREAD

**Issue by Azalen** [Atlantiss/NetherwingBugtracker#4107]
**Description**: 
http://classicdb.ch/?quest=5781

**Current behaviour**:
Gameobject "Loose Dirt Mound" (object=177240) is not spawned.

**Expected behaviour**: 
Should be spawned to start the linked event.

**Server Revision**: 
[2605]

**Comment by Evolvee** [comment]
rev 2655

**Comment by rychersky** [comment]
![image](https://user-images.githubusercontent.com/45608488/51623201-6ad9f300-1ef5-11e9-9855-4ad8252ff156.png)

I've been here for 15 minutes and have yet to see the pile of dirt spawn.

**Comment by Evolvee** [comment]
rev 2699
