### ISSUE TITLE
[Quest][Hillsbrad] WANTED: Baron Vardus

### ISSUE THREAD

**Issue by mooviestar** [Atlantiss/NetherwingBugtracker#4108]
[//]: # (Enclose links to things related to the bug using http://wowhead.com or any other TBC database.)
[//]: # (You can use screenshot ingame to visual the issue.)
[//]: # (Write your tickets according to the format:)
[//]: # ([Quest][Azuremyst Isle] Red Snapper - Very Tasty!)
[//]: # ([NPC] Magistrix Erona)
[//]: # ([Spell][Mage] Fireball)
[//]: # ([Npc][Drop] Ghostclaw Lynx)
[//]: # ([Web] Armory doesnt work)
[//]: # (To find server revision type `.server info` command in the game chat.)

**Description**: 
http://db.darkwizard.pl/?quest=566
https://db.excalibur.ws/?quest=566
This quest is unavailable to me as a level 21, it should be able to obtain at level 19 or below for the 19 twink quest reward.
**Current behaviour**:
Unavailable at low level
**Expected behaviour**: 
Should be able to obtain below 19
**Server Revision**: 
Obtain at 17-19 for twink reward

**Comment by nullfoxh** [comment]
https://www.wowhead.com/quest=566/deprecated-wanted-baron-vardus

![image](https://user-images.githubusercontent.com/12772977/51092438-e6260100-179f-11e9-8316-d425b6c2589f.png)

**Comment by Shanghi** [comment]
The level is already 17. You need to do WANTED: Syndicate Personnel first though.

**Comment by duzyizly** [comment]
![as](https://user-images.githubusercontent.com/43931626/85467233-3ddab580-b5ab-11ea-8ddb-cf9c19344128.jpg)
