### ISSUE TITLE
[Item] Soul Shard

### ISSUE THREAD

**Issue by BlessedByTheSin** [Atlantiss/NetherwingBugtracker#411]
[//]: # (Enclose links to things related to the bug using http://wowhead.com or any other TBC database.)
[//]: # (You can use screenshot ingame to visual the issue.)
[//]: # (Write your tickets according to the format:)
[//]: # ([Quest][Azuremyst Isle] Red Snapper - Very Tasty!)
[//]: # ([NPC] Magistrix Erona)
[//]: # ([Spell][Mage] Fireball)
[//]: # ([Npc][Drop] Ghostclaw Lynx)
[//]: # ([Web] Armory doesnt work)

**Description**: 
[Soul Shard](https://classicdb.ch/?item=6265) randomly appearing in my inventory just by walking, not doing anything. (rarely happens)
**Current behaviour**:
=//=
**Expected behaviour**: 
=//=
**Server Revision**: 
2040

**Comment by Easyfraggy** [comment]
Are you running out of range of your voidwalker/pup/succu?

**Comment by BlessedByTheSin** [comment]
> Are you running out of range of your voidwalker/pup/succu?

Could be. Tho, I am not sure.

**Comment by Easyfraggy** [comment]
In TBC when you run out of range of your demon your soulshard is returned to you.
