### ISSUE TITLE
 [Spell][Rogue] Pickpocket

### ISSUE THREAD

**Issue by REDBUN** [Atlantiss/NetherwingBugtracker#4110]
[//]: # (Enclose links to things related to the bug using http://wowhead.com or any other TBC database.)
[//]: # (You can use screenshot ingame to visual the issue.)
[//]: # (Write your tickets according to the format:)
[//]: # ([Quest][Azuremyst Isle] Red Snapper - Very Tasty!)
[//]: # ([NPC] Magistrix Erona)
[//]: # ([Spell][Mage] Fireball)
[//]: # ([Npc][Drop] Ghostclaw Lynx)
[//]: # ([Web] Armory doesnt work)
[//]: # (To find server revision type `.server info` command in the game chat.)

**Description**: Pickpocket not working as it should.

**Current behaviour**: Cast Pickpocket, then don't loot anything, cast Pickpocket again, Error reads "This mob has already had it's pockets picked"

**Expected behaviour**: Cast Pickpocket, don't loot anything, cast pickpocket again - Able to loot just like the first cast.
When a mob's pockets have ZERO loot, error message "This mob has already had it's pockets picked" should then come up. Mobs have about a 5-10 minute pocket loot respawn time in which the error message will cease, and pickpocket function will once again work as normal.

**Server Revision**: 
![image](https://user-images.githubusercontent.com/46639726/51081435-5ad34e00-1754-11e9-8ac6-6d1a36cd2950.png)

**Comment by wtRCH** [comment]
@aresbrutus @Shanghi

**Comment by Manaci** [comment]
Fixed with loot rework
