### ISSUE TITLE
[NPC][Badlands] Martek the Exalted

### ISSUE THREAD

**Issue by Kuumi** [Atlantiss/NetherwingBugtracker#4112]
[//]: # (Enclose links to things related to the bug using http://wowhead.com or any other TBC database.)
[//]: # (You can use screenshot ingame to visual the issue.)
[//]: # (Write your tickets according to the format:)
[//]: # ([Quest][Azuremyst Isle] Red Snapper - Very Tasty!)
[//]: # ([NPC] Magistrix Erona)
[//]: # ([Spell][Mage] Fireball)
[//]: # ([Npc][Drop] Ghostclaw Lynx)
[//]: # ([Web] Armory doesnt work)
[//]: # (To find server revision type `.server info` command in the game chat.)

**Description**: 
Martek the exalted is stuck doing RP

**Current behaviour**:
![image](https://user-images.githubusercontent.com/44377654/51081508-961f3f80-16b6-11e9-9e29-46829d039e0c.png)

**Expected behaviour**: 
For me to be able to talk to him and turn in my quest
**Server Revision**: 
2605

**Comment by Evolvee** [comment]
works now
