### ISSUE TITLE
Quest "A Hunter's Boast" crashing game

### ISSUE THREAD

**Issue by vitaminclutch** [Atlantiss/NetherwingBugtracker#4113]
[//]: # (Enclose links to things related to the bug using http://wowhead.com or any other TBC database.)
[//]: # (You can use screenshot ingame to visual the issue.)
[//]: # (Write your tickets according to the format:)
[//]: # ([Quest][Azuremyst Isle] Red Snapper - Very Tasty!)
[//]: # ([NPC] Magistrix Erona)
[//]: # ([Spell][Mage] Fireball)
[//]: # ([Npc][Drop] Ghostclaw Lynx)
[//]: # ([Web] Armory doesnt work)
[//]: # (To find server revision type `.server info` command in the game chat.)

**Description**: 
The quest "A Hunter's Boast" crashed my game and I had to wait until the timer ran out on the quest to continue playing
**Current behaviour**:
Game crashed while quest was accepted
**Expected behaviour**: 
Not to crash
**Server Revision**: 

The bug is fixable by waiting out the 15min for the quest timer and then playing as normal

**Comment by Peglaa** [comment]
Disable your quest helper addon. It's bugged for these quests. That's what causing you to crash.
