### ISSUE TITLE
[Core][objects] Looting same gameobject several times with several people

### ISSUE THREAD

**Issue by eunuck1** [Atlantiss/NetherwingBugtracker#4115]
# https://db.excalibur.ws/?item=19071
# https://clips.twitch.tv/SpoopySteamyLionKevinTurtle
[//]: # (Write your tickets according to the format:)
[//]: # ([Quest][Azuremyst Isle] Red Snapper - Very Tasty!)
[//]: # ([NPC] Magistrix Erona)
[//]: # ([Spell][Mage] Fireball)
[//]: # ([Npc][Drop] Ghostclaw Lynx)
[//]: # ([Web] Armory doesnt work)
[//]: # (To find server revision type `.server info` command in the game chat.)

**Description**: So it seems you can loot gameobjects multiple times if you time it right. Dont know how if it works on all of them but atleast the tainted vessels in jintha'alor.

**Current behaviour**: You can loot same object several times over and over with multiple party members if you time it.

**Expected behaviour**: Should onyl be one that can loot it and should dissapear after its looted

**Server Revision**:

**Comment by Manaci** [comment]
Fixed
