### ISSUE TITLE
Camera Bug in SW

### ISSUE THREAD

**Issue by Uriskall** [Atlantiss/NetherwingBugtracker#4117]
**Description**: 
When looking downward at the bridges in Stormwind there appears to be a bug that allows you to see through Stormwind. The bug only occurs (from what I've encountered) when zooming further out on the camera and looking downward towards the ground while on the [bridge.](https://vimeo.com/user64349541/review/311028028/ea68980c27)

**Server Revision**: 
2605

**Comment by wtRCH** [comment]
That's client side.
