### ISSUE TITLE
Martek the Exiled stuck in RP, unable to turn in/accept quests

### ISSUE THREAD

**Issue by staplerx300** [Atlantiss/NetherwingBugtracker#4118]
[//]: # (Enclose links to things related to the bug using http://wowhead.com or any other TBC database.)
[//]: # (You can use screenshot ingame to visual the issue.)
[//]: # (Write your tickets according to the format:)
[//]: # ([Quest][Azuremyst Isle] Red Snapper - Very Tasty!)
[//]: # ([NPC] Magistrix Erona)
[//]: # ([Spell][Mage] Fireball)
[//]: # ([Npc][Drop] Ghostclaw Lynx)
[//]: # ([Web] Armory doesnt work)
[//]: # (To find server revision type `.server info` command in the game chat.)

**Description**:  Martek keeps pacing back and forth and you can't right click on him. Stuck endlessly in roleplay.
https://i.imgur.com/oahm5V7.jpg
https://i.imgur.com/MXo8sIr.png

**Current behaviour**: Stuck in roleplay, uninteractable.

**Expected behaviour**: Not stuck in roleplay, interactable and able to turn in/accept quests with him.

**Server Revision**: 
2605

**Comment by wtRCH** [comment]
Duplicate.
