### ISSUE TITLE
[NPC][Quest] The Forlorn Spirit for The Legend of Stalvan spawns on the wrong floor in Lion Pride's Inn.

### ISSUE THREAD

**Issue by Novendar** [Atlantiss/NetherwingBugtracker#4119]
**Description**: 
The Forlorn Spirit for the quest 'The Legend of Stalvan' that spawns after opening the chest in Lion Pride's Inn spawns on the wrong floor, causing it to aggro low level players and slaughtering them.

*Steps to Reproduce*
1- Start the Quest 'The Legend of Stalvan' (Quest ID 66)
2- Progress to the step requiring to visit  Lion Pride's Inn (Quest ID 69)
3- Talk to the Inn Keeper
4- Proceed to the second floor and open the chest
**Current behaviour**:
The Forlorn Spirit spawns on the ground floor and aggros random low level players.

**Expected behaviour**: 
The Forlorn Spirit spawns where the chest is and aggros on the player that opened it.

**Server Revision**: 
Revision 2605 [Branch: master, Hash: a6ed8401898b]

**Comment by sadfx** [comment]
I just had it spawn on the 2nd floor and once it polymorphed me it went for a player on the first floor. Mob is neutral and should only engage the player that opened it, not turn pseudohostile and attack anyone.

**Comment by The14me** [comment]
Rev.3482 Not an issue anymore since nothing spawns.
https://classic.wowhead.com/quest=70/the-legend-of-stalvan#comments:id=43610
Can be closed.
