### ISSUE TITLE
[Class]Mage - Permafrost 2/3, possibly other ranks

### ISSUE THREAD

**Issue by Kentamentiu** [Atlantiss/NetherwingBugtracker#412]
[//]: # (Enclose links to things related to the bug using http://wowhead.com or any other TBC database.)
[//]: # (You can use screenshot ingame to visual the issue.)
[//]: # (Write your tickets according to the format:)
[//]: # ([Quest][Azuremyst Isle] Red Snapper - Very Tasty!)
[//]: # ([NPC] Magistrix Erona)
[//]: # ([Spell][Mage] Fireball)
[//]: # ([Npc][Drop] Ghostclaw Lynx)
[//]: # ([Web] Armory doesnt work)

**Description**: 
Frostbolt slows the mob by 40%. Permafrost 2/3 should add 7% to that. The Frostbolt tooltip reflects that to say 47%, but the Frostbolt debuff remains at 40%

**Current behaviour**:
Permafrost has no effect. Mobs remain slowed as if it was not active and the debuff reflects that.

**Expected behaviour**: 
7% increased slow.

**Server Revision**: 
2040

**Comment by Kentamentiu** [comment]
100% sure I only checked the tooltip after noticing the slow was not being applied.

**Comment by Godmatik** [comment]
Buff/Debuffs will not show adjusted values from talent points, this is Blizzlike for TBC.

**Comment by Easyfraggy** [comment]
Need proof of the talent not working tooltips dont change in tbc.
