### ISSUE TITLE
[Loot][NPC]Scorch Imp#21021 doesn't drop [Item]Mote of Shadows#22577, should drop at 33% rate

### ISSUE THREAD

**Issue by Tenoutoften** [Atlantiss/NetherwingBugtracker#4120]
**Description**: 
[[NPC]Scorch Imp#21021](http://web.archive.org/web/20070522115609/http://www.thottbot.com:80/c21021) currently doesn't drop [[Item]Mote of Shadows#22577](https://www.wowhead.com/item=22577/mote-of-shadow)

![](https://i.gyazo.com/b523abe0ddb0341c8a4b97772cfede8f.png)

On [Thottbot Archive](http://web.archive.org/web/20070522115609/http://www.thottbot.com:80/c21021) it is listed with 33% drop chance with 6759 registered kills at 2007.05.22(Patch 2.1.0)

---

**[[Item]Mote of Shadows#22577](https://www.wowhead.com/item=22577/mote-of-shadow) are dropped by void beings in Outland.**

As of Patch 2.1 the following has changed regarding [[Item]Mote of Shadows#22577](https://www.wowhead.com/item=22577/mote-of-shadow) drops:

- Enraged Fel Sparks now properly drop Motes of Fire instead of Motes of Shadow.
- Motes of Shadow now primarily drop from void creatures and have been removed from nearly all demons

- http://wowwiki.wikia.com/wiki/Mote_of_Shadow

**Current behaviour**:
Doesn't drop [[Item]Mote of Shadows#22577](https://www.wowhead.com/item=22577/mote-of-shadow)

**Expected behaviour**: 
33% chance for [[Item]Mote of Shadows#22577](https://www.wowhead.com/item=22577/mote-of-shadow) from [[NPC]Scorch Imp#21021](http://web.archive.org/web/20070522115609/http://www.thottbot.com:80/c21021)

**Server Revision**: 
2605

**Comment by wtRCH** [comment]
@aresbrutus
