### ISSUE TITLE
Wand Shoot getting cancelled when swapping targets.

### ISSUE THREAD

**Issue by foutweny** [Atlantiss/NetherwingBugtracker#4123]
**Description**: 
Problem with wands "Shoot" behaviour.

**Current behaviour**:
"Shoot" with wand CANCELS when switching targets while channeling it.

**Expected behaviour**: 
Swapping targets while channeling wand "Shoot" should start attacking the new target.

**Server Revision**:

**Comment by pesky89** [comment]
check this option:  
![image](https://user-images.githubusercontent.com/26849796/51083731-65c3b980-1727-11e9-8057-de9b38dd435f.png)

**Comment by wtRCH** [comment]
Duplicate.
