### ISSUE TITLE
[NPC] Babagaya Shadowcleft

### ISSUE THREAD

**Issue by gefthi** [Atlantiss/NetherwingBugtracker#4125]
[//]: # (Enclose links to things related to the bug using http://wowhead.com or any other TBC database.)
[//]: # (You can use screenshot ingame to visual the issue.)
[//]: # (Write your tickets according to the format:)
[//]: # ([Quest][Azuremyst Isle] Red Snapper - Very Tasty!)
[//]: # ([NPC] Magistrix Erona)
[//]: # ([Spell][Mage] Fireball)
[//]: # ([Npc][Drop] Ghostclaw Lynx)
[//]: # ([Web] Armory doesnt work)
[//]: # (To find server revision type `.server info` command in the game chat.)

**Description**: 
The neutral warlock trainer Babagaya Shadowcleft does not provide Drain Life Rank 4 at level 38 as the capital cities trainers.
**Current behaviour**:

**Expected behaviour**: 
Having the Drain Life Rank 4 spell available at level 38. It only has the next rank.
**Server Revision**:

**Comment by wtRCH** [comment]
@aresbrutus

**Comment by duzyizly** [comment]
hard to find any info about that but she is actually missing lvl 4d rain life on tbcdb https://tbcdb.com/?npc=23534#teaches-ability:50+1+2

she has it on any wotlk database (npc was added in tbc).

![aaa](https://user-images.githubusercontent.com/43931626/85175803-92fb8c00-b278-11ea-8083-a660fc451fc3.jpg)

**Comment by Wolffenstein** [comment]
Fixed in rev 3397.
