### ISSUE TITLE
Totems having too much aggro

### ISSUE THREAD

**Issue by staplerx300** [Atlantiss/NetherwingBugtracker#4126]
[//]: # (Enclose links to things related to the bug using http://wowhead.com or any other TBC database.)
[//]: # (You can use screenshot ingame to visual the issue.)
[//]: # (Write your tickets according to the format:)
[//]: # ([Quest][Azuremyst Isle] Red Snapper - Very Tasty!)
[//]: # ([NPC] Magistrix Erona)
[//]: # ([Spell][Mage] Fireball)
[//]: # ([Npc][Drop] Ghostclaw Lynx)
[//]: # ([Web] Armory doesnt work)
[//]: # (To find server revision type `.server info` command in the game chat.)

**Description**: 
Totems (specifically mana and healing totems) in dungeons and even solo are doing enough aggro that mobs are attacking them, seems to be way way more than usual.

**Current behaviour**:
Mobs attacking totems with seemingly little aggro.

**Expected behaviour**: 
Mobs only attacking totems if no players have aggro yet, and similar.

**Server Revision**: 
2605

**Comment by wtRCH** [comment]
Duplicate.
