### ISSUE TITLE
Honorable Killl only being counted if enemy dies to direct damage

### ISSUE THREAD

**Issue by Thugli** [Atlantiss/NetherwingBugtracker#4128]
[//]: # (Enclose links to things related to the bug using http://wowhead.com or any other TBC database.)
[//]: # (You can use screenshot ingame to visual the issue.)
[//]: # (Write your tickets according to the format:)
[//]: # ([Quest][Azuremyst Isle] Red Snapper - Very Tasty!)
[//]: # ([NPC] Magistrix Erona)
[//]: # ([Spell][Mage] Fireball)
[//]: # ([Npc][Drop] Ghostclaw Lynx)
[//]: # ([Web] Armory doesnt work)
[//]: # (To find server revision type `.server info` command in the game chat.)

**Description**: 
Currently, honorable kills are not being awarded if an enemy player dies to non-direct damage. 
**Current behaviour**:

**Expected behaviour**: 
Honorable kills should always be counted when a player kills a member of the opposing faction (Under normal settings, IE no honorless target debuff).
**Server Revision**: 
2605

**Comment by Thugli** [comment]
It also appears that HKs are not shared between party/raid. Party/raid members must do damage to an enemy player for the HK to properly be counted.

**Comment by Wolffenstein** [comment]
Fixed in rev 2614.
