### ISSUE TITLE
Deeprun Rat Roundup Despawn to long or not happening

### ISSUE THREAD

**Issue by Kegbeard** [Atlantiss/NetherwingBugtracker#4129]
**Description**: [Quest][Ironforge Deeprun Tram] [Deeprun Rat Roundup](https://www.wowhead.com/quest=6661/deeprun-rat-roundup) when a player starts quest and entrances rats then leaves rats without finishing quest, leaves ran in a state that does not allow respawn.

**Current behaviour**: Entranced rats do not despawn (or within 15 minutes) and cause new rats not to respawn

**Expected behaviour**:  Entranced rats should despawn 5-10 minutes, new rats should spawn

**Server Revision**:  Ensure entranced rats despawn after an appropriate amount of time has passed and ensure new rats are respawning.

**Comment by danbopes** [comment]
Confirmed: All the rats stay as "Enthralled Deeprun Rat", and do not properly despawn/revert back to "Deeprun Rat" for others to continue to quest.

**Comment by The14me** [comment]
Rev.3482 still an issue, rats did not reset after u leave the zone.

**Comment by ASRoux** [comment]
This is still an issue, can't complete the quest

**Comment by Godmatik** [comment]
Was fixed last year on Rev 3915

Closing
