### ISSUE TITLE
Typos!

### ISSUE THREAD

**Issue by Mewmewww** [Atlantiss/NetherwingBugtracker#413]
[//]: # (Enclose links to things related to the bug using http://wowhead.com or any other TBC database.)
[//]: # (You can use screenshot ingame to visual the issue.)
[//]: # (Write your tickets according to the format:)
[//]: # ([Quest][Azuremyst Isle] Red Snapper - Very Tasty!)
[//]: # ([NPC] Magistrix Erona)
[//]: # ([Spell][Mage] Fireball)
[//]: # ([Npc][Drop] Ghostclaw Lynx)
[//]: # ([Web] Armory doesnt work)

**Description**: Grammar! https://imgur.com/a/qJfY2IW

**Current behaviour**: Current is a typo: https://imgur.com/a/qJfY2IW

**Expected behaviour**: In the traditional English language points out that, if the following word starts with/sounds like a vowel, the article must start with "an" ;( https://imgur.com/a/qJfY2IW

**Server Revision**: Current revision is 2040

**Comment by Evolvee** [comment]
its a blizzlike typo btw ;)

**Comment by Evolvee** [comment]
![image](https://user-images.githubusercontent.com/1942409/45974367-6f72c580-c041-11e8-848c-90cef6eb3bce.png)

from official retail source

**Comment by Evolvee** [comment]
will be fixed in next hotfix rev.
