### ISSUE TITLE
The Gordunni Scroll is not lootable.

### ISSUE THREAD

**Issue by Rebeli83** [Atlantiss/NetherwingBugtracker#4130]
[//]: # (Enclose links to things related to the bug using http://wowhead.com or any other TBC database.)
[//]: # (You can use screenshot ingame to visual the issue.)
[//]: # (Write your tickets according to the format:)
[//]: # ([Quest][Azuremyst Isle] Red Snapper - Very Tasty!)
[//]: # ([NPC] Magistrix Erona)
[//]: # ([Spell][Mage] Fireball)
[//]: # ([Npc][Drop] Ghostclaw Lynx)
[//]: # ([Web] Armory doesnt work)
[//]: # (To find server revision type `.server info` command in the game chat.)

**Description**: 
The Gordunni Scroll isn't lootable in feralas.
**Current behaviour**:
The Gordunni Scroll is "empty"
**Expected behaviour**: 
Should be able to pick-up the quest.
**Server Revision**: 2605

**Comment by wtRCH** [comment]
Please wait some time before picking it up. Maybe item inside object didn't refill. @Rebeli83

**Comment by taurenrogue** [comment]
server revision 2676 cant loot in any of the spots found on database

**Comment by whispersz** [comment]
I can confirm this. I only found out of 3 spots and I was not able to loot it. Neither 3 other people.

**Comment by Tereneckla** [comment]
Fixed
