### ISSUE TITLE
Contagion of Rot

### ISSUE THREAD

**Issue by AWIDIUS** [Atlantiss/NetherwingBugtracker#4131]
https://imgur.com/a/pit2twp Mob has tendency to put his debuff all over again on me even when I have it already and Im not dispelling it

**Comment by AWIDIUS** [comment]
Maybe the first mob overwrites debuff of second mob and it counts as a dispell, therefore second mob reacts with debuff again

**Comment by The14me** [comment]
Rev.3482 not an issue anymore.
