### ISSUE TITLE
UD female getting stucked in stairs

### ISSUE THREAD

**Issue by calylith** [Atlantiss/NetherwingBugtracker#4132]
[//]: # (Enclose links to things related to the bug using http://wowhead.com or any other TBC database.)
[//]: # (You can use screenshot ingame to visual the issue.)
[//]: # (Write your tickets according to the format:)
[//]: # ([Quest][Azuremyst Isle] Red Snapper - Very Tasty!)
[//]: # ([NPC] Magistrix Erona)
[//]: # ([Spell][Mage] Fireball)
[//]: # ([Npc][Drop] Ghostclaw Lynx)
[//]: # ([Web] Armory doesnt work)
[//]: # (To find server revision type `.server info` command in the game chat.)

**Description**: 
Playing Undead female and feels the hitbox of the char is wrong. 
**Current behaviour**:
Getting stucked in all different stairs in Ghostlands
**Expected behaviour**: 
Run up stairs without getting blocked in air.
**Server Revision**:

**Comment by wtRCH** [comment]
That's client side.
