### ISSUE TITLE
[Quest][Hillsbrad] WANTED: Baron Vardus (no spawn)

### ISSUE THREAD

**Issue by Bromidious** [Atlantiss/NetherwingBugtracker#4133]
**Description:**
https://vanilla-twinhead.twinstar.cz/?npc=2306
https://vanilla-twinhead.twinstar.cz/?quest=566

**Current behaviour**:
Common issue being reported among users about Baron not being available. GM was not able to find mob either.

**Expected behaviour**: 
Baron Vardus should be spawning in one of 5 locations.

**Server Revision**: 
Spawn Baron Vardus randomly in one of 5 locations. Camps along north mountain side curving towards west shore of Alterac and possibly one location in the Strahnsbrad inn.

**Comment by wtRCH** [comment]
@aresbrutus

**Comment by Bromidious** [comment]
Was this fixed?

**Comment by aresbrutus** [comment]
https://github.com/Atlantiss/NetherwingBugtracker/issues/4569
