### ISSUE TITLE
[NPC]Murkblood putrifier#18202's [Spell]Tainted Chain Lightning#32132 reduces 100% intellect instead of 15%

### ISSUE THREAD

**Issue by Tenoutoften** [Atlantiss/NetherwingBugtracker#4134]
**Description**: 
[[NPC]Murkblood putrifier#18202](https://db.excalibur.ws/?npc=18202#abilities)'s [[Spell]Tainted Chain Lightning#32132](https://db.excalibur.ws/?spell=32132) reduces too much intellect

![](https://media.discordapp.net/attachments/375840002405564416/533961209238519818/0int.png?width=1248&height=702)

![](https://i.gyazo.com/2476eba4b732743ecc3933d209c9a1b5.png)

**Current behaviour**:
Reduces intellect by way too much

**Expected behaviour**: 
15% reduced intellect

**Server Revision**: 
2605

**Comment by Ninehills42** [comment]
Confirmed. Still not fixed.
