### ISSUE TITLE
NPC - Pathfinder spawns

### ISSUE THREAD

**Issue by lynxzor** [Atlantiss/NetherwingBugtracker#4135]
![image](https://user-images.githubusercontent.com/795881/51084687-29438e00-1726-11e9-95e7-593810d33d34.png)

**Description**: Multiple mobs on spawn point

**Current behaviour**: Multiple mobs on spawn point

**Expected behaviour**: One

**Server Revision**:

**Comment by aresbrutus** [comment]
https://i.imgur.com/tfZxstJ.jpg

Related to this quest: https://db.excalibur.ws/?quest=1535


The mobs need to despawn after a while.

**Comment by Tereneckla** [comment]
Fixed
