### ISSUE TITLE
Zangarmarsh World Pvp Buff does not apply after both beacons are captured

### ISSUE THREAD

**Issue by Jerzze** [Atlantiss/NetherwingBugtracker#4136]
[//]: # (Enclose links to things related to the bug using http://wowhead.com or any other TBC database.)
[//]: # (You can use screenshot ingame to visual the issue.)
[//]: # (Write your tickets according to the format:)
[//]: # ([Quest][Azuremyst Isle] Red Snapper - Very Tasty!)
[//]: # ([NPC] Magistrix Erona)
[//]: # ([Spell][Mage] Fireball)
[//]: # ([Npc][Drop] Ghostclaw Lynx)
[//]: # ([Web] Armory doesnt work)
[//]: # (To find server revision type `.server info` command in the game chat.)

**Description**: 

**Current behaviour**:

**Expected behaviour**: 

**Server Revision**:

**Comment by wtRCH** [comment]
Fill out template @Jerzze

**Comment by Wolffenstein** [comment]
Fixed in rev 3328.
