### ISSUE TITLE
[Maraudon] Pariah's Instruction. Gems and Amulet not shared loot.

### ISSUE THREAD

**Issue by Unfairy** [Atlantiss/NetherwingBugtracker#4137]
Gems and Amulet supposed to be shared loot both outside and inside dungeon.

Right now you can loot it as a party ONLY if you loot the gems and amulet SAME time.
1 amulet and 5 gems, not being able to loot it normal as shared making this quest especially annoying.

**Comment by wtRCH** [comment]
@aresbrutus

**Comment by Godmatik** [comment]
Rev 4018 - no longer an issue - the quest objects all are shared with party just fine
