### ISSUE TITLE
[Quest] The Fel and the Furious

### ISSUE THREAD

**Issue by Anduyon** [Atlantiss/NetherwingBugtracker#4139]
NOTE: Copied this for visibility. Can be deleted as a duplicate. Just wanted to get attention to the issue since the old report is from November. The Situation remains the same on the live server.

Description:
You'll be tasked to use a device for mind-controlling a fel reaver. You're then meant to use the fel reaver to destroy 60 infernals with one of its abilities. You'll also be fending of adds around the quest area with the other fel reaver abilities. The quets is limited to 5 minutes.

Current behaviour:
Attempting to destroy the infernals doesn't work. The missiles of your ability will go off, but nothing happens once they reach the infernals. The fel reaver is also quite weak in terms of fending off the adds surrounding you, but this might not be un-blizzlike.

Expected behaviour:
Using the missiles on the infernals is supposed to destroy them and give you credit.

Server Revision: 2605

**Comment by Johra92** [comment]
I tried doing this quest yesterday, did not work at the time. Good on you for the bug report!

**Comment by aresbrutus** [comment]
https://github.com/Atlantiss/AtlantissTBCBT/issues/3958

**Comment by Evolvee** [comment]
rev 2687
