### ISSUE TITLE
[Quest]Elixir of Pain (501)

### ISSUE THREAD

**Issue by Kentamentiu** [Atlantiss/NetherwingBugtracker#414]
[//]: # (Enclose links to things related to the bug using http://wowhead.com or any other TBC database.)
[//]: # (You can use screenshot ingame to visual the issue.)
[//]: # (Write your tickets according to the format:)
[//]: # ([Quest][Azuremyst Isle] Red Snapper - Very Tasty!)
[//]: # ([NPC] Magistrix Erona)
[//]: # ([Spell][Mage] Fireball)
[//]: # ([Npc][Drop] Ghostclaw Lynx)
[//]: # ([Web] Armory doesnt work)

**Description**: 
Collect 20 Mountain Lion Blood (3496) from Mountain Lions 
**Current behaviour**:
Very low droprate.

**Expected behaviour**: 
This should be 100% droprate (as reported on Thottbot)

**Server Revision**: 
2040

**Comment by aresbrutus** [comment]
Will be fixed in one of the next updates.
