### ISSUE TITLE
{Desolace} [NPC for quest} Khan Dez'hepah  not spawning after 2 hours of waiting

### ISSUE THREAD

**Issue by Jovzin** [Atlantiss/NetherwingBugtracker#4140]
Description:
Quest : https://www.wowhead.com/quest=1365/khan-dezhepah
NPC: https://www.wowhead.com/npc=5600/khan-dezhepah

Is not sapwning at all after 2 hours of killing everything in the cammp.   

Current behaviour:
Wasn't able to spawn the NPC. Killed mobs in the area for +60-120min. Khan Dez'hepah didn't spawn.

Expected behaviour:
    He should spawn in one of the two big tents. Can be either one.

**Comment by wtRCH** [comment]
@aresbrutus

**Comment by aresbrutus** [comment]
Same issue: https://github.com/Atlantiss/NetherwingBugtracker/issues/4133

**Comment by dmrljes** [comment]
Issue still not resolved

**Comment by rwtjr0** [comment]
Seems to spawn one time after crash or restart of server. Then does not respawn. Please fix!

**Comment by MrOrgmo** [comment]
+1 , still an issue

**Comment by Tsekeflime** [comment]
Issue still not resolved

**Comment by aresbrutus** [comment]
https://github.com/Atlantiss/NetherwingBugtracker/issues/4569

**Comment by whispersz** [comment]
This NPC still not spawning. I've been farming in fron of those 2 tents for 50 minutes and no spawn

**Comment by nightwica** [comment]
This is still not working as intended as ow today, only spawning after a crash

**Comment by nightwica** [comment]
Something weird is up with this quest. I thought the people were right about "he only spawns after a server restart or crash", that kind of made sense. Only that it isn't true. We had a DC, I asked on General if someone killed him and sb said yes they just did. But anyway I tried my luck, went to the area only to find a guy killing him in the northernmost tent, luckily enough he invited me to the group just on time.
Went back another time for the following quest where we grouped with a guy who also needed him, I showed him where he spawned for me and we killed him. That is already the 3rd time in a row after a single crash.
But then, still on the follow-up quest, we partied up with some guys again, led them to "his" tent but we also checked the others, and he was nowhere to be found for 20-30 minutes. We wiped the camp and killed his add, too. But only his add kept spawning, atleast 2 or 3 times, all the time without him, so something might be still up with this quest.

**Comment by thestranger064** [comment]
hello! as of today 05/02 -2019 its still not working properly.

steps: killed battle lords at every location, and nothing
killed windchasers and maulers , just incase
camped both big tents

and nothing. sadly this one of those quest that everyone knows about, but nothing is done about it.

**Comment by Evolvee** [comment]
fixed in rev 2971
