### ISSUE TITLE
[Core Mechanic] Rested XP Cap Should Be Higher

### ISSUE THREAD

**Issue by Shrizz** [Atlantiss/NetherwingBugtracker#4141]
**Description**: 

Rested XP for levels 1-57 should be accumulating at 5% of a level per 4 hours of real time logged off up to a cap of 300% of the current level, a total of 60 bubbles gained over the course of 240 hours (10 days). The rate of accumulation seems to be working as intended; however, the cap seems to be fixed at the original 150% of a level ceiling, instead of 300%.

When I logged on my level 7 warlock, whom I hadn't touched in a little over 5 days, I noticed that his rested XP was at exactly 1.5 times his current level XP requirement: 6750 rested for level 7 to 8, which requires 4500 xp normally. It should have been a little bit higher.

**Current behaviour**:

The rested XP ceiling is only 150% of the current level instead of 300%, as per the custom changes Netherwing said they implemented for rested XP (double rest XP generation AND cap).

**Expected behaviour**: 

The rested XP ceiling should be 300% of the current level (60 bubbles) instead of 150%.

**Server Revision**: 

2610

**Comment by staplerx300** [comment]
still bugged

**Comment by Drengsta** [comment]
Same here. I have 2 alts. One of them I haven't touched since launch day that I got out of newbie zone and into the inn (lvl 5). He only has 150% rested xp.

**Comment by Egozy** [comment]
Confirmed, was out for 5 days and and I have the 150% (checked the actual xp gained while playing, not relying on an addon/xp-bar text)

**Comment by fantom8** [comment]
Confirmed still bugged, my rogue has been capped at exactly 150% rested for days now: https://i.imgur.com/ZuKSjKh.png

**Comment by Gniddikon** [comment]
This seems to be fixed? My hunter is at 210% rested right now.
