### ISSUE TITLE
Shaman totem dmg not showing as pet damage on dps meters

### ISSUE THREAD

**Issue by Korstoo** [Atlantiss/NetherwingBugtracker#4144]
**Description**: So the issue I'm facing is that for some reason other players doesn't tend to see my totem damage on their meters. However I'm able to see totems as pet damage in my own meters without any problem. Just as nobody else is able to see them, I'm getting declined from groups as the only damage source comes from my abilities + melee no totems included. Currently using recount addon as most of us are.

**Current behaviour**: The same.

**Expected behaviour**: Other people could see my totem damage as pet damage --> increase my overall damage shown.

**Server Revision**: 2605

**Comment by towneh** [comment]
Isn't this an issue with Recount and pet/totem ownership being counted towards your damage? At least the same problem with totems no appearing for other players with sync enabled also occurs on Warmane.

**Comment by ShadyWins** [comment]
Have you tried testing with other DMG meters such as Skada?

**Comment by The14me** [comment]
Magma totem Show
Fire Nova show.
Searing show.
Make sure u click on Pet box to not Merge and u gonna be fine.
https://i.imgur.com/ydlrs21.png
Rev.3482.
Can be closed.

**Comment by Tereneckla** [comment]
https://authors.curseforge.com/forums/world-of-warcraft/official-addon-threads/general-addons/218762-recount?comment=2194

Issue with recount itself
