### ISSUE TITLE
Fire-Hardened Mail Warrior Quest

### ISSUE THREAD

**Issue by Heckas** [Atlantiss/NetherwingBugtracker#4145]
[//]: # (Enclose links to things related to the bug using http://wowhead.com or any other TBC database.)
[//]: # (You can use screenshot ingame to visual the issue.)
[//]: # (Write your tickets according to the format:)
[//]: # ([Quest][Azuremyst Isle] Red Snapper - Very Tasty!)
[//]: # ([NPC] Magistrix Erona)
[//]: # ([Spell][Mage] Fireball)
[//]: # ([Npc][Drop] Ghostclaw Lynx)
[//]: # ([Web] Armory doesnt work)
[//]: # (To find server revision type `.server info` command in the game chat.)

**Description**: 
I just finished farming the materials for the Fire-Hardened Mail Warrior Quest, I had everything in my bags and my quest log read completed, but I could not turn it in. I tried abandoning and re picking up the quest but that deleted everything I just farmed for the quest. Any way to help? Netherwing Server, Character name: Stannis

**Current behaviour**:
Would not let me turn in Fire-Hardened Mail quest, abandoned to re-pick and turn in, all quest items were deleted.
**Expected behaviour**: 
Expected a simple quest turn in, which would open some more warrior armor quests
**Server Revision**:

**Comment by wtRCH** [comment]
Same goes for Horde Burtal Armor.

**Comment by Jacksn5** [comment]
https://github.com/Atlantiss/NetherwingBugtracker/issues/4054#issuecomment-453768619
> 
> I deleted 1 item and reobtained it and it allowed it to be turned in

this didn't work for me

**Comment by Evolvee** [comment]
![image](https://user-images.githubusercontent.com/1942409/51427540-7083c000-1bf9-11e9-94c5-e653bb2afb67.png)
works fine for me

**Comment by Evolvee** [comment]
did u have full inventory?

or did u put some items into guild bank?

any addons?

**Comment by Apawlogies** [comment]
http://prntscr.com/nn2ckk - Player had his quest items deleted upon trying to hand in the quest. - Needs investigation.

**Comment by Evolvee** [comment]
well if u abandon a quest, it deletes all quest items associated with it its core feature, nothing to do with this perticular quest

**Comment by The14me** [comment]
Delete items when Abandon quest is normal.
about the issue when u have the items but can't turn the quest think that was fixed.
