### ISSUE TITLE
Warrior - Overpower not instantly available on a Dodge

### ISSUE THREAD

**Issue by Tylerpls** [Atlantiss/NetherwingBugtracker#4146]
[//]: # (Enclose links to things related to the bug using http://wowhead.com or any other TBC database.)
[//]: # (You can use screenshot ingame to visual the issue.)
[//]: # (Write your tickets according to the format:)
[//]: # ([Quest][Azuremyst Isle] Red Snapper - Very Tasty!)
[//]: # ([NPC] Magistrix Erona)
[//]: # ([Spell][Mage] Fireball)
[//]: # ([Npc][Drop] Ghostclaw Lynx)
[//]: # ([Web] Armory doesnt work)
[//]: # (To find server revision type `.server info` command in the game chat.)

**Description**:  Dodge should make a overpower instant, 

**Current behaviour**: Delay on overpower proc.

**Expected behaviour**: Instant overpower after a dodge.

**Server Revision**:

**Comment by wtRCH** [comment]
Duplicate.
