### ISSUE TITLE
[NPC][Spell] Pesterhide Snarler Intimidating Growl

### ISSUE THREAD

**Issue by Ceago** [Atlantiss/NetherwingBugtracker#4147]
**Description**:  Pesterhide Snarler's intimidating growl causes players to run in fear too fast.   https://streamable.com/mpac2

**Current behaviour**:  Fast running in fear, occasionally will run very far.  

**Expected behaviour**:  Should run at normal speed.

**Server Revision**: 2605

**Comment by Drayo** [comment]
By Vonara (9,914 – 2·19·64) on 2010/06/03 (Patch 3.3.3)

> His adds have an ability called Intimidating Growl that will send you RUNNING. You get around a 100% movement increase and you run around feared. It's a bit different from most fears, but you'll have to witness it to really see why.
