### ISSUE TITLE
Call upon a pet does not show a dead pet frame

### ISSUE THREAD

**Issue by Quaade93** [Atlantiss/NetherwingBugtracker#4148]
**Description**: 
When your pet is dead and you press call pet, it should come up a frame under playerframe showing your pet, that its dead. This causes some major problem regarding macros and pets.

**Current behaviour**:
When you use call pet and the pet is dead, no petframe appear.

**Expected behaviour**: 
When your pet is dead and you press call pet, it should come up a fram under playerframe showing your pet, that its dead.

**Server Revision**: 2605

**Comment by The14me** [comment]
Rev.3482 not an issue anymore.
Can be closed.
