### ISSUE TITLE
While questing in STV, i got teleported back to Ratchet after a relog

### ISSUE THREAD

**Issue by KredesX** [Atlantiss/NetherwingBugtracker#4149]
[//]: # (Enclose links to things related to the bug using http://wowhead.com or any other TBC database.)
[//]: # (You can use screenshot ingame to visual the issue.)
[//]: # (Write your tickets according to the format:)
[//]: # ([Quest][Azuremyst Isle] Red Snapper - Very Tasty!)
[//]: # ([NPC] Magistrix Erona)
[//]: # ([Spell][Mage] Fireball)
[//]: # ([Npc][Drop] Ghostclaw Lynx)
[//]: # ([Web] Armory doesnt work)
[//]: # (To find server revision type `.server info` command in the game chat.)

**Description**: Weird teleport happened after i relogged. Was doing Skullsplitter Tusk in STV, relogged to check an addon and when i logged back in, i was teleported to Ratchet. 

**Current behaviour**: ?

**Expected behaviour**: ? 

**Server Revision**: 2605

**Comment by wtRCH** [comment]
This is due to saving player.
