### ISSUE TITLE
[Spell][Hunter] Talent Endurance Training does not increase pet's HP

### ISSUE THREAD

**Issue by Gniddikon** [Atlantiss/NetherwingBugtracker#415]
**Description**: The talent "Endurance Training" does not increase my pet's HP, but only my own HP.

**Current behaviour**: see above

**Expected behaviour**: Should increase the pet's HP by 2% per talent point.

**Server Revision**: 2040

**Comment by Gniddikon** [comment]
Still has no effect whatsoever on the pet.

**Comment by The14me** [comment]
yea,will be fixed before release for sure.

**Comment by Manaci** [comment]
Fixed
