### ISSUE TITLE
Taunting Hunter Pet into Freezing Trap doesn't work

### ISSUE THREAD

**Issue by femdead** [Atlantiss/NetherwingBugtracker#4150]
Expected Behaviour:
Taunt debuff forces the pet to break trap

Current behaviour: 
Pet does not attack you while trapped

**Comment by Tereneckla** [comment]
https://forum.buffed.de/topic/28048-jaeger-gegen-krieger-im-pvp/?p=341557
https://www.elitepvpers.com/forum/world-warcraft/133187-druid-warri-vs-druid-hunter-taktiken.html#post1094108

Old German forum posts that it should work.
But only idiot hunters do not have pet in passive

**Comment by Wolffenstein** [comment]
Fixed in rev 3383.
