### ISSUE TITLE
[NPC] Witherbark Witch Doctor uses Draenei Totems

### ISSUE THREAD

**Issue by towneh** [Atlantiss/NetherwingBugtracker#4151]
**Description**: 
Witherbark Witch Doctor uses wrong totems. NPCs at Witherbark Village in Arathi Highlands.

**Current behaviour**:
![image](https://user-images.githubusercontent.com/25694892/51089369-dd173e80-1763-11e9-8bb6-2ae0ad5d94b4.png)
Magma Totem II that is dropped uses the Draenei texture.

**Expected behaviour**: 
Should use the correct NPC ward/totem textures.

**Server Revision**: 
2605

**Comment by wtRCH** [comment]
@aresbrutus @Shanghi

**Comment by The14me** [comment]
Rev.3482 Not an issue anymore.
Can be closed.
