### ISSUE TITLE
Mob in step off "mode" parrying my hits.

### ISSUE THREAD

**Issue by AWIDIUS** [Atlantiss/NetherwingBugtracker#4152]
You implemented feature that was on retail, that if player is too close to the mob, mob just steps off a little further by turning to player backwards, going few yards forward and then turn back to face player. In this case mob's parry should be diminished to 0%. https://imgur.com/a/cPMipgT Mobs yet still parrying

**Comment by Drayo** [comment]
No, it is just a visual effect, you should also not be able to backstab the mob for example. (which you can't atm)

If it was like that everyone you just fuck around with every mob....
