### ISSUE TITLE
Target too close

### ISSUE THREAD

**Issue by DarkGHLB** [Atlantiss/NetherwingBugtracker#4153]
[//]: # (Enclose links to things related to the bug using http://wowhead.com or any other TBC database.)
[//]: # (You can use screenshot ingame to visual the issue.)
[//]: # (Write your tickets according to the format:)
[//]: # ([Quest][Azuremyst Isle] Red Snapper - Very Tasty!)
[//]: # ([NPC] Magistrix Erona)
[//]: # ([Spell][Mage] Fireball)
[//]: # ([Npc][Drop] Ghostclaw Lynx)
[//]: # ([Web] Armory doesnt work)
[//]: # (To find server revision type `.server info` command in the game chat.)

**Description**: Target too close issue causing melee attacks not to go off (seems to typically just be auto attacks and not spell abilities)

**Current behaviour**: Target too close and auto attacks will not swing.

**Expected behaviour**: Cannot be too close to auto attack.

**Server Revision**:

**Comment by Manaci** [comment]
Surely fixed
