### ISSUE TITLE
Abolish Poison

### ISSUE THREAD

**Issue by gurtash** [Atlantiss/NetherwingBugtracker#4154]
**Description**: 
Abolish Poison not working correctly

**Current behaviour**:
Abolish Poison only removes poisons on application & every 2 seconds out of combat
https://youtu.be/syDFIcCXH2w

**Expected behaviour**: 
Abolish Poison should remove poisons on applications & every 2 seconds regardless of combat
**Server Revision**: 
server rev 2605

**Comment by Lycalo** [comment]
still not working properly

**Comment by ttghnw** [comment]
still broken

**Comment by Realnairoby** [comment]
Any news on this? One of the most important fixes for druids in PvP. @wtRCH

**Comment by ttghnw** [comment]
This is unacceptable. Still broken, we are a joke for rogues at the moment.

**Comment by Easyfraggy** [comment]
Fixed priority for you. Not that it helps much. Should be easy fix - ill ask wolf about it.

**Comment by pelekon** [comment]
checked on local with rev 2786 and it works, closing
