### ISSUE TITLE
Seal of Justice judgement not limiting movement speed of other players

### ISSUE THREAD

**Issue by staplerx300** [Atlantiss/NetherwingBugtracker#4155]
[//]: # (Enclose links to things related to the bug using http://wowhead.com or any other TBC database.)
[//]: # (You can use screenshot ingame to visual the issue.)
[//]: # (Write your tickets according to the format:)
[//]: # ([Quest][Azuremyst Isle] Red Snapper - Very Tasty!)
[//]: # ([NPC] Magistrix Erona)
[//]: # ([Spell][Mage] Fireball)
[//]: # ([Npc][Drop] Ghostclaw Lynx)
[//]: # ([Web] Armory doesnt work)
[//]: # (To find server revision type `.server info` command in the game chat.)

**Description**: 
Seal of Justice when judged limits movement speed of other players to 100%.

**Current behaviour**:
Has no effect on opposing players. Only retains the anti-fleeing mechanic against NPC mobs.

**Expected behaviour**: 
Limits movement speed of opposing players to 100%.

**Server Revision**: 
2605

**Comment by Wolffenstein** [comment]
Works fine for me. Will reopen if others can confirm and provide footage.
