### ISSUE TITLE
Ferocity (feral)

### ISSUE THREAD

**Issue by ttghnw** [Atlantiss/NetherwingBugtracker#4156]
[//]: # (Enclose links to things related to the bug using http://wowhead.com or any other TBC database.)
[//]: # (You can use screenshot ingame to visual the issue.)
[//]: # (Write your tickets according to the format:)
[//]: # ([Quest][Azuremyst Isle] Red Snapper - Very Tasty!)
[//]: # ([NPC] Magistrix Erona)
[//]: # ([Spell][Mage] Fireball)
[//]: # ([Npc][Drop] Ghostclaw Lynx)
[//]: # ([Web] Armory doesnt work)
[//]: # (To find server revision type `.server info` command in the game chat.)

**Description**: 
The named talent after respec is not working, confirmed on tooltip and on actual energy and rage consumption
![wowscrnshot_011319_205748](https://user-images.githubusercontent.com/43508698/51090598-fa550880-1775-11e9-86d0-4031aa7c9b0a.jpg)
, this comes and goes it seems and it's not uniformly observable with all players at the same time apparently.
**Current behaviour**:

**Expected behaviour**: 

**Server Revision**:

**Comment by wtRCH** [comment]
Tooltip might not reflect talent changes. Please check on your character unit frame if it works. @ttghnw
