### ISSUE TITLE
BG system + not ending empty games

### ISSUE THREAD

**Issue by floridalady** [Atlantiss/NetherwingBugtracker#4157]
BG system creating non equal games . unless ppl of 1 side are dodging their bg pop there shouldnt be games 10vs 1 or 2 . i dont think 8 ppl of 1 side did dodge their bg pop up . means if u have 2vs2 or 2vs3 both side needs joiners otherwise the system shouldnt let more ppl in . also i had a  bg 5 alliance vs 0 horde which didnt end . it should if theres not enuff ppl on the other side a timer ends the game. cuant tell me this system is correct tbc bg system.

**Comment by Manaci** [comment]
Not a bug
