### ISSUE TITLE
Defensive Stance - Warrior

### ISSUE THREAD

**Issue by EGSilver** [Atlantiss/NetherwingBugtracker#4158]
**Description**: 
Warriors are able to train defensive stance straight from the trainer.
There was a class quest that you needed to do before you where granted the Defensive stance ability.

Previously, Defensive Stance was granted to the warrior via one of a number of equivalent warrior class quests as listed below. With the changes in Patch 4.0.1, these quests no longer need to be completed, and they were removed in patch 4.0.3a.

EDIT; Source: https://wow.gamepedia.com/Defensive_Stance

**Server Revision**: 
2605

**Comment by Manaci** [comment]
Fixed
