### ISSUE TITLE
[Darkshore] Beached Sea Turtle Quests

### ISSUE THREAD

**Issue by Azalen** [Atlantiss/NetherwingBugtracker#416]
**Description**: 
In Darkshore there are five Beached Sea Turtle gameobjects that each start a different quest with a different level requirement:
https://classicdb.ch/?search=Beached+Sea+Turtle#quests

**Current behaviour**:
The low level quests (questlog shows 14 and 15) are in the south where the high level ones (19 and 19) should be. You can judge the appropriate level by the mobs surrounding the gameobject. In the south you have 19-20 mobs around it. 
This is important because each of the quest rewards different amount of EXP and ofc because it looks super weird to pick up a red quest surrounded by green mobs (colors refer to level of the mobs).

**Expected behaviour**: 
Netherwing is using the same wrong quest assignments than classicDB and Nostalrius. Im linking the 
game objects now and the quest id it should relate to:

South of Auberdine:
https://classicdb.ch/?object=176191 -> (level 19-20) quest ID = 4731
https://classicdb.ch/?object=176198 -> (level 19-20) quest ID = 4732

https://classicdb.ch/?object=176190 -> (level 12-13) quest ID = 4722

North of Auberdine:
https://classicdb.ch/?object=176196 -> (level 13-14) quest ID = 4727
https://classicdb.ch/?object=176197 -> (level 13-14) quest ID = 4725

Obviously I have no proof for this but it should be common sense that quests for level 20 that reward more exp should be related to the gameobject that is surrounded by mobs of level 20 and not by mobs of level 13. This error is in the DB for ages.

**Server Revision**: 
[2041]

**Comment by Shanghi** [comment]
This should be fixed in revision 2121. There were some comments verifying them too, and now they're all by the mobs that make sense for their levels. The beached sea creatures were all mixed up too.
