### ISSUE TITLE
Winterfall Ambushers not dropping combat

### ISSUE THREAD

**Issue by Drengsta** [Atlantiss/NetherwingBugtracker#4160]
[//]: # (Enclose links to things related to the bug using http://wowhead.com or any other TBC database.)
[//]: # (You can use screenshot ingame to visual the issue.)
[//]: # (Write your tickets according to the format:)
[//]: # ([Quest][Azuremyst Isle] Red Snapper - Very Tasty!)
[//]: # ([NPC] Magistrix Erona)
[//]: # ([Spell][Mage] Fireball)
[//]: # ([Npc][Drop] Ghostclaw Lynx)
[//]: # ([Web] Armory doesnt work)
[//]: # (To find server revision type `.server info` command in the game chat.)

**Description**: Winterfall Ambushers are not dropping aggro and running all the way to Everlook

**Current behaviour**:Winterfall Ambushers are not dropping aggro and running all the way to Everlook

**Expected behaviour**: They should drop aggro and make it so you can mount when you are halfway across the zone.

**Server Revision**:

**Comment by devo6969** [comment]
This seems fixed on the PTR, They don't chase anymore.
