### ISSUE TITLE
[Ashenvale] Splintertree Post - Rested

### ISSUE THREAD

**Issue by wtRCH** [Atlantiss/NetherwingBugtracker#4161]
[//]: # (Enclose links to things related to the bug using http://wowhead.com or any other TBC database.)
[//]: # (You can use screenshot ingame to visual the issue.)
[//]: # (Write your tickets according to the format:)
[//]: # ([Quest][Azuremyst Isle] Red Snapper - Very Tasty!)
[//]: # ([NPC] Magistrix Erona)
[//]: # ([Spell][Mage] Fireball)
[//]: # ([Npc][Drop] Ghostclaw Lynx)
[//]: # ([Web] Armory doesnt work)
[//]: # (To find server revision type `.server info` command in the game chat.)

**Description**:  Rested Experience in Splintertree Post tavern.

**Current behaviour**: When you enter Splintertree Post tavern you instantly gain 2 rested experience bars.

**Expected behaviour**: When you enter Splintertree Post travern you shouldn't get rested experience bar instantly but only start to generate it slowly.

**Server Revision**: 
2605

**Comment by Tereneckla** [comment]
Fixed
