### ISSUE TITLE
[Spell] Throw

### ISSUE THREAD

**Issue by REDBUN** [Atlantiss/NetherwingBugtracker#4163]
[//]: # (Enclose links to things related to the bug using http://wowhead.com or any other TBC database.)
[//]: # (You can use screenshot ingame to visual the issue.)
[//]: # (Write your tickets according to the format:)
[//]: # ([Quest][Azuremyst Isle] Red Snapper - Very Tasty!)
[//]: # ([NPC] Magistrix Erona)
[//]: # ([Spell][Mage] Fireball)
[//]: # ([Npc][Drop] Ghostclaw Lynx)
[//]: # ([Web] Armory doesnt work)
[//]: # (To find server revision type `.server info` command in the game chat.)

**Description**: Throw gives two skill points per use.

**Current behaviour**: Cast throw, gain a skill point on cast, and a second later gain another skill point on hit.
https://youtu.be/Tuw3R7Bh3bo

**Expected behaviour**: Throw should only gain a skill point on cast, not on hit.

**Server Revision**:

**Comment by wtRCH** [comment]
@Wolffenstein

**Comment by Tereneckla** [comment]
#3863
