### ISSUE TITLE
[NPC][Core] No DR on NPC immobilize spells, like nets!

### ISSUE THREAD

**Issue by Peglaa** [Atlantiss/NetherwingBugtracker#4166]
[//]: # (Enclose links to things related to the bug using http://wowhead.com or any other TBC database.)
[//]: # (You can use screenshot ingame to visual the issue.)
[//]: # (Write your tickets according to the format:)
[//]: # ([Quest][Azuremyst Isle] Red Snapper - Very Tasty!)
[//]: # ([NPC] Magistrix Erona)
[//]: # ([Spell][Mage] Fireball)
[//]: # ([Npc][Drop] Ghostclaw Lynx)
[//]: # ([Web] Armory doesnt work)
[//]: # (To find server revision type `.server info` command in the game chat.)

**Description**: 
NPCs that use immobilize spells, namely the nets, have no DR for those spells and they can chain root you forever. e.g. Bluegill Raider(1418)

**Current behaviour**:

**Expected behaviour**: 

**Server Revision**: 2605

**Comment by Wolffenstein** [comment]
Rev 2621.
