### ISSUE TITLE
[Item]Rough Bronze Cuirass#2866 should be white quality instead of green until last patch

### ISSUE THREAD

**Issue by Tenoutoften** [Atlantiss/NetherwingBugtracker#4167]
**Description**: 
[[Item]Rough Bronze Cuirass#2866](http://web.archive.org/web/20071201114147/http://thottbot.com:80/i2866) Incorrectly grants stats, correctly states that you can't disenchant. Item should be white quality in this patch until the last patch
![](https://i.gyazo.com/25c9bddbb272903690a40fab011e4182.png)
![](https://i.gyazo.com/1a032661c2c1052d4b955fd26f0cbfdc.png)

**Current behaviour**:
* Gives stats, green quality

**Expected behaviour**: 
* White quality, no stats

**Server Revision**: 
2605

**Comment by wtRCH** [comment]
@aresbrutus
