### ISSUE TITLE
[Movement][NPC]Thief Catcher Delve#14363 error in path(Flies through the ground)

### ISSUE THREAD

**Issue by Tenoutoften** [Atlantiss/NetherwingBugtracker#4168]
**Description**: 
[[NPC]Thief Catcher Delve#14363](https://db.excalibur.ws/?npc=14363) has a slight error in his patrol path causing him to do fall animation while his legs go through the flour while in the Ironforge bank.
Can be seen [here](https://youtu.be/ezTDnczdWyY)

**Expected behaviour**: 
Should be walking

**Server Revision**: 
2606

**Comment by wtRCH** [comment]
@Shanghi
