### ISSUE TITLE
Red Leather Bandanas

### ISSUE THREAD

**Issue by qetsohukare** [Atlantiss/NetherwingBugtracker#417]
**Drop Chance is low**: 

**The bandanas drop chance seems to be very low for this quest**:

**since its a quest that has a drop of 15 bandanas it is expected that the drop chance is near 100%**:

**Comment by paoea** [comment]
After finishing the first deafias quest, I got 10. Does feel right

**Comment by qetsohukare** [comment]
the 1 defias quest needs 30 defias to die so i dont think its fair, but still if its the way it should work i wont complain :) just thought to report it

**Comment by aresbrutus** [comment]
Will be fixed in one of the upcoming updates.
