### ISSUE TITLE
"item is still being rolled for" loot bug with full bags!

### ISSUE THREAD

**Issue by Nixazzar** [Atlantiss/NetherwingBugtracker#4173]
**Description**: 
In any dungeon, or normal world party when u roll on item, need or greed, doesnt matter, and you win that roll if your bags are full u wont recive item to bags, as thats how its supposed to work. However when you delete something from your bags, and try to loot that same item again, you will get message "that item is still being rolled for" and you wont be able to loot it, but anyone else from your party will be, no matter what they rolled, greed, need, or haven't rolled at all.

This has happened to me twice in dungeons my mistake, as my bags got full, so i tried to test it once more to see if it is really the case, and deliberately made my bags full, rolled need for specific item, while others greeded, and i still wasnt able to pick it up, but party was. So in my opinion thats a major bug, not that problematic on low levels, but once outland dungeons and raids start rolling then it will become major problem because it opens doors to Ninjaing and potentially loosing valuable items.

**Current behaviour**:
If your bags are full, and u win roll on and item, you wont be able to pick it up afterwards when u clear bag space as you will get message "that item is still being rolled for" but other people who did not win that roll will be able to take it no problem.

**Expected behaviour**: 
When u win roll on an item, if you dont have bag space, you will be able to pick it up once your bags have free slots, but others wont be able to take your item.

**Server Revision**: 
2605

**Comment by Nixazzar** [comment]
![wowscrnshot_011419_045531](https://user-images.githubusercontent.com/45208041/51098452-b50ef600-17ca-11e9-90eb-0e2c5e09b6d0.jpg)

**Comment by VoidLock92** [comment]
I get this issue in party even for normal loot like cloth or greys.  It will show me it is lootable but then when I try to loot it says this item is still being rolled on. But it is not something you roll on.

**Comment by leeviathan** [comment]
From my observation it seems like **cloth** loot is out-of-sync with group loot, so if it's your turn to loot a corpse you can loot everything except for the cloth loot (i.e. Wool Cloth), which can then be looted by another group member.

**Comment by devo6969** [comment]
similar issue to #3987 duplicate?

**Comment by Tereneckla** [comment]
Fixed
