### ISSUE TITLE
[Spell][Druid] Force Of Nature

### ISSUE THREAD

**Issue by Vapedx0** [Atlantiss/NetherwingBugtracker#4174]
[//]: # (Enclose links to things related to the bug using http://wowhead.com or any other TBC database.)
[//]: # (You can use screenshot ingame to visual the issue.)
[//]: # (Write your tickets according to the format:)
[//]: # ([Quest][Azuremyst Isle] Red Snapper - Very Tasty!)
[//]: # ([NPC] Magistrix Erona)
[//]: # ([Spell][Mage] Fireball)
[//]: # ([Npc][Drop] Ghostclaw Lynx)
[//]: # ([Web] Armory doesnt work)
[//]: # (To find server revision type `.server info` command in the game chat.)

**Description**: Treants when summoned with multiple enemies around, will kill one unit, and the run back to the druid on passive (even if druid is still in combat with multiple mobs). Sometimes when using a Damaging Spell (non damaging spells like Faerie Fire will cause treants to remain follow passive on druid) the treats will go over in attack mode, and sometimes they will, and sometimes they will just follow the unit but not attack them

**Current behaviour**: Treants will sometimes attack mob if you use a damaging spell on an enemy, but will not attack if you use non-damaging spells or heal others that are also in combat. Here are two clips i was able to get in a dungeon
https://clips.twitch.tv/FairUnsightlyPorpoiseOSkomodo  (treants go passive after first kill, and then when at the mini troll boss, i moonfire to get the treants to aggro onto boss, they hit once, then stay follow on the miniboss till they despawn)

https://clips.twitch.tv/TriangularAffluentOcelotFrankerZ (Treants aggro like normal, but once target dies passive back to druid, i tested faerie fire to see if that'll aggro but it didn't, nor did my heals to my group, only damaging spells seem to be a "fix" around it.

**Expected behaviour**: Treants should fight anything the druid is fighting, and when aggrod on to a mob, should be able to attack them as well

**Server Revision**:

**Comment by Godmatik** [comment]
Unable to reproduce, perhaps fixed at some point.

Treants properly go to the other targets on their own after the first one is dead, no action needed by me.
