### ISSUE TITLE
Screecher Spirits Quest

### ISSUE THREAD

**Issue by Bakster15** [Atlantiss/NetherwingBugtracker#4176]
[//]: # (Enclose links to things related to the bug using http://wowhead.com or any other TBC database.)
[//]: # (You can use screenshot ingame to visual the issue.)
[//]: # (Write your tickets according to the format:)
[//]: # ([Quest][Azuremyst Isle] Red Snapper - Very Tasty!)
[//]: # ([NPC] Magistrix Erona)
[//]: # ([Spell][Mage] Fireball)
[//]: # ([Npc][Drop] Ghostclaw Lynx)
[//]: # ([Web] Armory doesnt work)
[//]: # (To find server revision type `.server info` command in the game chat.)

**Description**: 
You can't use the quest item  [Yeh'kinya's Bramble] on the Screecher mobs. Whether they are dead, alive, full hp or low hp. 
**Current behaviour**:

**Expected behaviour**: 

**Server Revision**: 
2605

**Comment by Brasso** [comment]
Fixed in next server update. Server isn't updated yet.
