### ISSUE TITLE
Group loot bugged? (In dungeons)

### ISSUE THREAD

**Issue by Mikik3jr** [Atlantiss/NetherwingBugtracker#4179]
[//]: # (Enclose links to things related to the bug using http://wowhead.com or any other TBC database.)
[//]: # (You can use screenshot ingame to visual the issue.)
[//]: # (Write your tickets according to the format:)
[//]: # ([Quest][Azuremyst Isle] Red Snapper - Very Tasty!)
[//]: # ([NPC] Magistrix Erona)
[//]: # ([Spell][Mage] Fireball)
[//]: # ([Npc][Drop] Ghostclaw Lynx)
[//]: # ([Web] Armory doesnt work)
[//]: # (To find server revision type `.server info` command in the game chat.)

**Description**: 
We were using Group Loot in Zul'Farrak.

**Current behaviour**:
After rolling nothing happens, and the loot disappears.
https://www.youtube.com/watch?v=2H4QrAkTUxw&feature=youtu.be
**Expected behaviour**: 

**Server Revision**:

**Comment by staplerx300** [comment]
this happened to me as well i rolled need on an item in ZF and my need roll never went through, so i didn't get the item

also troll temper isn't shared loot in ZF as well

i.imgur.com/nRS5Lyk.jpg

still waiting on my amulet...

**Comment by Manaci** [comment]
Fixed with loot rework
