### ISSUE TITLE
flight form

### ISSUE THREAD

**Issue by gurtash** [Atlantiss/NetherwingBugtracker#4183]
**Description**: 
flight form bug
**Current behaviour**:
you cannot loot herbs while flying in flight form
**Expected behaviour**: 
you should be able to loot herbs while flying
**Server Revision**: 
server rev 2605

**Comment by gurtash** [comment]
https://www.youtube.com/watch?v=Wr0EUdfOiBc 
proof

**Comment by BezawitNW** [comment]
I've been able to herb in flight form yesterday + today.

**Comment by gurtash** [comment]
bug is that you cannot loot while flying not while in flight form still cannot loot while flying server rev 2635

**Comment by Shadowkill22** [comment]
Could somebody please check it ? I know it is quite advantages againt others but still blizzlike.

**Comment by Tereneckla** [comment]
Fixed since
