### ISSUE TITLE
[Loot][Winterspring] Ice Thistle Yeti Patriach and Matriarch loot table

### ISSUE THREAD

**Issue by Brasso** [Atlantiss/NetherwingBugtracker#4184]
[//]: # (Enclose links to things related to the bug using http://wowhead.com or any other TBC database.)
[//]: # (You can use screenshot ingame to visual the issue.)
[//]: # (Write your tickets according to the format:)
[//]: # ([Quest][Azuremyst Isle] Red Snapper - Very Tasty!)
[//]: # ([NPC] Magistrix Erona)
[//]: # ([Spell][Mage] Fireball)
[//]: # ([Npc][Drop] Ghostclaw Lynx)
[//]: # ([Web] Armory doesnt work)
[//]: # (To find server revision type `.server info` command in the game chat.)

**Description**: 
Might be an issue with the loot tables of these mobs. Cleared the cave twice and got 2 blues and 3 greens. We could have also just been lucky. Could check it just in case.

**Server Revision**: 
2605

**Comment by Shanghi** [comment]
If they were druid idols and paladin things then it was some rude stock loot that needed to be removed from a lot of things. If they were weapons/armor, then you got very lucky! Either way, the much higher chance on idols/paladin things should be fixed now.

**Comment by Brasso** [comment]
They were indeed idols! Thanks.
