### ISSUE TITLE
Bugged patrol in Badlands.

### ISSUE THREAD

**Issue by Mikik3jr** [Atlantiss/NetherwingBugtracker#4185]
[//]: # (Enclose links to things related to the bug using http://wowhead.com or any other TBC database.)
[//]: # (You can use screenshot ingame to visual the issue.)
[//]: # (Write your tickets according to the format:)
[//]: # ([Quest][Azuremyst Isle] Red Snapper - Very Tasty!)
[//]: # ([NPC] Magistrix Erona)
[//]: # ([Spell][Mage] Fireball)
[//]: # ([Npc][Drop] Ghostclaw Lynx)
[//]: # ([Web] Armory doesnt work)
[//]: # (To find server revision type `.server info` command in the game chat.)

**Description**: 
There is an ogregroup that patrols in badlands.

**Current behaviour**:
https://www.youtube.com/watch?v=VuybTMlD5tM&feature=youtu.be
![image](https://user-images.githubusercontent.com/43505031/51122182-96841b80-1819-11e9-9adf-7e2d36782126.png)

**Comment by duzyizly** [comment]
https://github.com/Atlantiss/NetherwingBugtracker/issues/6850

**Comment by Wolffenstein** [comment]
Fixed in rev 3344.
