### ISSUE TITLE
[Spell][Shaman] Blood Fury + Lightning Shield

### ISSUE THREAD

**Issue by Galawer** [Atlantiss/NetherwingBugtracker#4189]
**Description**: 
[[Blood Fury]](http://db.hellfire-tbc.com/?spell=33697) [[Lightning Shield]](http://db.hellfire-tbc.com/?spell=324
)

**Current behaviour**:
Using Blood Fury consumes a stack of your Lightning Shield.

**Expected behaviour**: 
It shouldn't.

**Server Revision**: 
2605

**Comment by The14me** [comment]
Rev.3482 not an issue anymore.
Can be closed.
