### ISSUE TITLE
[Quest] Alas, Andorhal

### ISSUE THREAD

**Issue by Searcher314** [Atlantiss/NetherwingBugtracker#4192]
I put a group of 6 players together to do the Alas, Andorhal" quest in WPL. When we killed Araj his grown spawn did appear correctly but only 1 player was able to loot it and get the quest item.
Instead it should have stayed and allowed each player to loot the quest item as long as they were on the quest, it doesn't matter if they are in group or not. This is how it has worked since I did the quest in vanilla.
So hopefully that can get fixed, it really isn't worth killing the mob 1 time for each group member.

Game object: https://classicdb.ch/?object=177241
Game item: https://classicdb.ch/?item=17114
Quest ID (Alliance): https://classicdb.ch/?quest=211

**Comment by Brasso** [comment]
Worked fine for us. All three players could loot the item before it despawned.

**Comment by Drayo** [comment]
A "Group" of 6 players?

Might be that Group Loot does not work properly for Raids.

**Comment by Searcher314** [comment]
> Worked fine for us. All three players could loot the item before it despawned.

Not sure when you tried this, I reported it to a GM over discord but he asked that I put in an official report today, so that's what I'm doing. Regardless it didn't work for us.

**Comment by Searcher314** [comment]
> A "Group" of 6 players?
> 
> Might be that Group Loot does not work properly for Raids.

We weren't in a raid group. We had a group of 5 and a 6th asked if we had room. I told him to come tag along because he should be able to loot the quest object out of group. So he was out of group. The 1 player that did loot the item was in our group, our group had the tag on the mob.

**Comment by Azalen** [comment]
Worked for my group two days ago.

**Comment by ShadyWins** [comment]
There is still issues with this Q.

I've today killed Alas Andorhal 4 times on my Tauren Shaman - not once have i Been able to loot the Q-object, while everyone Else in my group was able to. I get the message "invalid target" when right clicking the urn. 
I tried disabling All addons, abandon q and redo, and i did it 4th time with a Tauren druid who had samme issue. This Leads me to believe this issue is related to Taurens only

Anyhow its still not working as intended...

**Comment by langtang** [comment]
i hate to bump old posts but this is an issue im still having on alliance side

**Comment by leeviathan** [comment]
just wanted to add to the list concurring. The quest item is only available to the first looter. However I did this quest about a month ago with a different character and both party members were able to loot it. Not sure what has changed or what was different.

**Comment by Easyfraggy** [comment]
Is it possible you can supply some more information? Like which faction/race you were when unable to loot it aswell as wether you were in a raid or normal party?

If we can't reproduce this reliably its hard to fix.

**Comment by Manaci** [comment]
Fixed
