### ISSUE TITLE
[Auction House/AH Addons] AUX/Auctioneer can't scan more than 100 pages of auctions.

### ISSUE THREAD

**Issue by Lebaowski** [Atlantiss/NetherwingBugtracker#4195]
[//]: # (Enclose links to things related to the bug using http://wowhead.com or any other TBC database.)
[//]: # (You can use screenshot ingame to visual the issue.)
[//]: # (Write your tickets according to the format:)
[//]: # ([Quest][Azuremyst Isle] Red Snapper - Very Tasty!)
[//]: # ([NPC] Magistrix Erona)
[//]: # ([Spell][Mage] Fireball)
[//]: # ([Npc][Drop] Ghostclaw Lynx)
[//]: # ([Web] Armory doesnt work)
[//]: # (To find server revision type `.server info` command in the game chat.)

**Description**: When scanning the AH with AUX or Auctioneer it scans a maximum of 100 pages, so exactly 5000 auctions every time I scan it. If I scan every category individually it comes out to 312 pages, or 15000+ auctions with over 100 pages in the 'Trade Goods' category alone. A lot of players rely on scanning the auction house and putting item values in tooltips in order to decide what to vendor and what to keep for auctions to save time and gold, but only scanning 1/3 of active auctions makes this hard. These addons work on other servers, and will scan all pages even if there are over 100.

**Current behaviour**: Can't scan more than 100 pages on the AH using AH addons even though there are over 300 pages worth of auctions, the addon only picks up the first 100 pages. It can be worked around by scanning each category individually.

**Expected behaviour**: The addons should pick up all pages and show the total amount of expected pages while scanning, and scan every item on the auction house including the ones added during the scan.

**Server Revision**: 2605

AUX:
![wowscrnshot_011419_230834](https://user-images.githubusercontent.com/9139546/51145129-4924a000-1853-11e9-9059-d2437390d22c.jpg)

Auctioneer:
![wowscrnshot_011419_230915](https://user-images.githubusercontent.com/9139546/51145140-4de95400-1853-11e9-9ed4-c2238cfe6c9c.jpg)

**Comment by AsgerCode** [comment]
Just confirmed this issue.

**Comment by Manaci** [comment]
Addon meme
