### ISSUE TITLE
Attacks Made Just Before Sweeping Strikes Expires Don't Benefit From It

### ISSUE THREAD

**Issue by femdead** [Atlantiss/NetherwingBugtracker#4196]
The window is already short enough at 10 seconds, right now it's effectively ~9 seconds on NW

**Comment by Jalapan** [comment]
https://github.com/Atlantiss/NetherwingBugtracker/issues/4476

**Comment by Godmatik** [comment]
Unable to reproduce, probably fixed at some point, or it was related to spell delay (which was removed long ago)
