### ISSUE TITLE
Aspect of the Cheetah bug

### ISSUE THREAD

**Issue by Nachopie123** [Atlantiss/NetherwingBugtracker#4197]
[//]: # ([Spell][Hunter] Aspect of the Cheetah)
[//]: # ([Spell][Hunter] Hunter's Mark)

**Description**: 
Aspect of the cheetah will trigger daze from non-damaging abilities.

**Current behaviour**:
You are able to get dazed from being dispelled by a priest, and you can also daze yourself if you use hunter's mark on a shaman (which also shouldn't trigger lightning shield btw)

**Expected behaviour**: 
Aspect of the cheetah should only trigger daze from damaging abilities: i.e. casted spells with damage (frostbolt), instant spells such as arcane shot, melee / range white-hits, and melee / range abilities (mortal strike, hamstring etc) but never trigger from dots or non-damaging spells.

**Server Revision**: 
2605 [Branch: master, Hash: a6ed8401898b]

**Comment by Manaci** [comment]
Fixed
