### ISSUE TITLE
Mobs gaining full health

### ISSUE THREAD

**Issue by rangobob** [Atlantiss/NetherwingBugtracker#4199]
[//]: # (Enclose links to things related to the bug using http://wowhead.com or any other TBC database.)
[//]: # (You can use screenshot ingame to visual the issue.)
[//]: # (Write your tickets according to the format:)
[//]: # ([Quest][Azuremyst Isle] Red Snapper - Very Tasty!)
[//]: # ([NPC] Magistrix Erona)
[//]: # ([Spell][Mage] Fireball)
[//]: # ([Npc][Drop] Ghostclaw Lynx)
[//]: # ([Web] Armory doesnt work)
[//]: # (To find server revision type `.server info` command in the game chat.)

**Description**: 
All mobs i have encountered have been possible to reach full health just as they try to flee or so, i think it's connected to them fleeing, not 100 % sure.
**Current behaviour**:
They gain 100% health instantly
**Expected behaviour**: 
Not do that. (it's any mob) even mobs with no possible cast (thus im not just lagging and not seeing a cast)
**Server Revision**: 
2605

**Comment by nullfoxh** [comment]
Are you a paladin? Vindication was bugging and healing mobs. It's fixed but server wasn't updated yet

**Comment by Wolffenstein** [comment]
Fixed in rev 2618.
