### ISSUE TITLE
Warlock imp chases enemy in melee range when oom 

### ISSUE THREAD

**Issue by Scylla420** [Atlantiss/NetherwingBugtracker#42]
Warlocks imp (summoned through spell 688, npc 416) currently runs after its target in melee range while oom when it should stay by your side and wait for mana to regen before casting more firebolts.  

[NW footage, 25 secs in.](https://youtu.be/OhO5gESYUd0?t=23s)

Discussion of the same issue on TC github (note that I am not talking about auto attacking, that part is working correctly.)

https://github.com/TrinityCore/TrinityCore/issues/301
"Problems: When it runs OOM it will still run up in melee range"
"Expected Result: Imp should stay by your side, and wait for mana to regen, then continue casting Firebolts."

https://github.com/TrinityCore/TrinityCore/issues/15600
"imp should always stay at cast range even on oom."

Note that all these sources are from wrath and do not come with any conclusive evidence for the way imp AI should function.  IF anyone has other sources please post!

**Comment by Evolvee** [comment]
We did research on water elemental, which should be pretty much the same and it DID run to melee range...(it doesnt attack, it just positions to better distance in order to cast its fireball/waterball more easily after regaining mana for it)

**Comment by SwiftieTBC** [comment]
https://youtu.be/2i_IMIS-h2s?t=2m36s shows an imp going oom and maintaining distance not autoing,
https://youtu.be/2llnWFRVPt0?t=3m49s same again re-positions to be able to cast but no meele .
Sadly this is wotlk but ill try to find tbc footage

**Comment by Brasso** [comment]
Can also only find footage from Wrath but I don't think it has changed. https://www.youtube.com/watch?v=lwxA9IETNqY&feature=youtu.be&t=159

From 2008, of course imps don't melee, but I think it implies that it also doesn't follow people when oom.

![impmelee](https://user-images.githubusercontent.com/44345420/50173017-a67e0d80-02f6-11e9-97b2-49ab96d1a127.png)

**Comment by The14me** [comment]
''Water Elementals (Frost Mage pet) and Imps (Warlock minion) do not have an auto-attack. Instead they will cast spells as long as the auto-cast for their respective abilities is active —Waterbolt for Elementals, Firebolt for Imps.''
https://us.battle.net/support/en/article/12726
Can be closed.
