### ISSUE TITLE
[Item] Magic Dust has a Cast Time

### ISSUE THREAD

**Issue by sadfx** [Atlantiss/NetherwingBugtracker#4201]
**Description**: Magic Dust Cast Time

**Current behaviour**: Magic Dust has a cast time

**Expected behaviour**: Should be instant cast (https://www.youtube.com/watch?v=qAAERKlq9ZQ&feature=youtu.be&t=38)

**Server Revision**: 2625

**Comment by Evolvee** [comment]
thats a vanilla video
