### ISSUE TITLE
[Quest] Raene's Cleansing

### ISSUE THREAD

**Issue by Saben65** [Atlantiss/NetherwingBugtracker#4202]
**Description**: 
[Raene's Cleansing pt. 5](http://wowwiki.wikia.com/wiki/Quest:Raene%27s_Cleansing_(5))

I have had multiple people tell me they did this quest with success previously; however, after killing rotten slimes for an hour and not having the chest appear, ontop of having multiple people I met over the course of that hour also give up, I am pretty sure this quest was broken at some point.

The quest in

**Current behaviour**:
Currently the slimes do not seem to drop a chest when they die.

**Expected behaviour**: 
[Rotting Slimes](https://classic.wowhead.com/npc=3928/rotting-slime) should occasionally drop a chest that contains the [Iron Pommel](https://classic.wowhead.com/item=5519/iron-pommel). 

**Server Revision**: 
2625

**Comment by balazskvr** [comment]
I had the same issue, no chest spawned.

**Comment by Saben65** [comment]
Not sure if something changed. I was in the area for another quest today, and I got it after killing 4 slimes.
