### ISSUE TITLE
(147) at login

### ISSUE THREAD

**Issue by Westifilms** [Atlantiss/NetherwingBugtracker#4203]
Morning
i log in and before i get to character selection i get (147)
it then makes me login again and the cycle continues.
Effectivly i cant get past it to play.
Please help
Im on a mac.
Cheers
Shock

**Comment by fjaros** [comment]
Issue happens because game server's SMSG_AUTH_RESPONSE doesn't return any data payload when authenticating with the auth server as a Mac client. Only returns packet length + opcode.

**Comment by Desst** [comment]
Confirmed. This should be Hotfixed

**Comment by BAndysc** [comment]
Fixed in rev 2639
