### ISSUE TITLE
An Ambitious Plan Quest not workign

### ISSUE THREAD

**Issue by Drengsta** [Atlantiss/NetherwingBugtracker#4205]
[//]: # (Enclose links to things related to the bug using http://wowhead.com or any other TBC database.)
[//]: # (You can use screenshot ingame to visual the issue.)
[//]: # (Write your tickets according to the format:)
[//]: # ([Quest][Azuremyst Isle] Red Snapper - Very Tasty!)
[//]: # ([NPC] Magistrix Erona)
[//]: # ([Spell][Mage] Fireball)
[//]: # ([Npc][Drop] Ghostclaw Lynx)
[//]: # ([Web] Armory doesnt work)
[//]: # (To find server revision type `.server info` command in the game chat.)

**Description**: Alliance quest " An Ambitious Plan" is not working.

**Current behaviour**:Upon using the quest item on a wounded uncontrolled voidwalker, it does not drop or create the quest item on the ground to loot.

**Expected behaviour**: Upon using the crystal, a red crystal should appear on the ground to loot for quest completion.
Link to how it should work: https://www.youtube.com/watch?v=rLBenfubi7w

**Server Revision**:

**Comment by Evolvee** [comment]
![image](https://user-images.githubusercontent.com/1942409/51428065-bd6a9500-1bff-11e9-9163-ab256a608a70.png)

works fine for me
