### ISSUE TITLE
log out issue

### ISSUE THREAD

**Issue by quacked123** [Atlantiss/NetherwingBugtracker#4209]
[//]: # (Enclose links to things related to the bug using http://wowhead.com or any other TBC database.)
[//]: # (You can use screenshot ingame to visual the issue.)
[//]: # (Write your tickets according to the format:)
[//]: # ([Quest][Azuremyst Isle] Red Snapper - Very Tasty!)
[//]: # ([NPC] Magistrix Erona)
[//]: # ([Spell][Mage] Fireball)
[//]: # ([Npc][Drop] Ghostclaw Lynx)
[//]: # ([Web] Armory doesnt work)
[//]: # (To find server revision type `.server info` command in the game chat.)

**Description**: 
logging out teleport issue
**Current behaviour**:
logging out teleports you to random locations when logging in
**Expected behaviour**: 
should log you out where u are
**Server Revision**:

**Comment by Desst** [comment]
Can confirm. This is old though and very annoying

**Comment by Jhep1903** [comment]
Can confirm as well. I logged out at BB inn and logged back in 1 min later and was at FP in Ratchet
