### ISSUE TITLE
Big Sparkles

### ISSUE THREAD

**Issue by Tinnoan** [Atlantiss/NetherwingBugtracker#421]
The sparkles for the dirt mounds for the quest "New Life" in The Charred Vale in Stonetalon Mountains are very big, 3-4 times the height of my tauren.

![big sparkles](https://user-images.githubusercontent.com/25431721/45978813-7acbee00-c04d-11e8-8a91-3e261836096d.png)

**Comment by Evolvee** [comment]
any retail video confirming this issue?

**Comment by Easyfraggy** [comment]
https://github.com/Atlantiss/NetherwingBugtracker/issues/597

**Comment by Evolvee** [comment]
guess we are closing this too then, if u find some retail evidence/proof, reopen pls
