### ISSUE TITLE
[Quest]Broodling Essence

### ISSUE THREAD

**Issue by powerlol** [Atlantiss/NetherwingBugtracker#4210]
[//]: # (Enclose links to things related to the bug using http://wowhead.com or any other TBC database.)
[//]: # (You can use screenshot ingame to visual the issue.)
[//]: # (Write your tickets according to the format:)
[//]: # ([Quest][Azuremyst Isle] Red Snapper - Very Tasty!)
[//]: # ([NPC] Magistrix Erona)
[//]: # ([Spell][Mage] Fireball)
[//]: # ([Npc][Drop] Ghostclaw Lynx)
[//]: # ([Web] Armory doesnt work)
[//]: # (To find server revision type `.server info` command in the game chat.)

**Description**: 
After using Draco-Incarcinatrix https://www.wowhead.com/item=12284/draco-incarcinatrix-900 on the broodling (dragonskin) it doesn't pop the crystal that will loot the "Broodling Essence"
**Current behaviour**:
Doesn't drop any cristal on the body
**Expected behaviour**: 
Should drop a crystal on his body so we're able to loot the broodling essence
**Server Revision**: 
live

**Comment by Manaci** [comment]
Fixed
