### ISSUE TITLE
Zul'Farrak RP locking out a boss/Goblin not opening gates

### ISSUE THREAD

**Issue by staplerx300** [Atlantiss/NetherwingBugtracker#4212]
[//]: # (Enclose links to things related to the bug using http://wowhead.com or any other TBC database.)
[//]: # (You can use screenshot ingame to visual the issue.)
[//]: # (Write your tickets according to the format:)
[//]: # ([Quest][Azuremyst Isle] Red Snapper - Very Tasty!)
[//]: # ([NPC] Magistrix Erona)
[//]: # ([Spell][Mage] Fireball)
[//]: # ([Npc][Drop] Ghostclaw Lynx)
[//]: # ([Web] Armory doesnt work)
[//]: # (To find server revision type `.server info` command in the game chat.)

**Description**: 

**Current behaviour**:
The gobbo is supposed to open the gates.

**Expected behaviour**: 
He doesn't, it's bugged and he does the RP but the gates don't open and then he goes off on his own to fight trolls.

**Server Revision**: 
2625

**Comment by Wolffenstein** [comment]
Fixed in rev 2626.
