### ISSUE TITLE
[Quest] The Smallest Creatures

### ISSUE THREAD

**Issue by naekobest** [Atlantiss/NetherwingBugtracker#4215]
https://github.com/Atlantiss/NetherwingBugtracker/issues/2246

Its been open since 4th nov. and its a big chain. kinda sad that its still not fixed

**Comment by waterloorick** [comment]
Update?

**Comment by aresbrutus** [comment]
https://github.com/Atlantiss/NetherwingBugtracker/issues/2246

Duplicate
