### ISSUE TITLE
[Quest] 10629 "Shizz Work" Incompletable/Doesn't work, Poo after killing Hellboars/Hound dismermbering doesn't appear

### ISSUE THREAD

**Issue by Pu3Ho** [Atlantiss/NetherwingBugtracker#4216]
[//]: # (Enclose links to things related to the bug using http://wowhead.com or any other TBC database.)
[//]: # (You can use screenshot ingame to visual the issue.)
[//]: # (Write your tickets according to the format:)
[//]: # ([Quest][Azuremyst Isle] Red Snapper - Very Tasty!)
[//]: # ([NPC] Magistrix Erona)
[//]: # ([Spell][Mage] Fireball)
[//]: # ([Npc][Drop] Ghostclaw Lynx)
[//]: # ([Web] Armory doesnt work)
[//]: # (To find server revision type `.server info` command in the game chat.)

**Description**: 
Impossible to do the quest.
**Current behaviour**:
Poo after killing Hellboars/Hound dismermbering corpse doesn't appear
**Expected behaviour**: 
It should appear.
**Server Revision**: 
2625

**Comment by Domceru** [comment]
Possibly related to https://github.com/Atlantiss/NetherwingBugtracker/issues/4202?

**Comment by Manaci** [comment]
Fixed
