### ISSUE TITLE
[Quest][The Hinterlands] A Gesture of Goodwill

### ISSUE THREAD

**Issue by Mikik3jr** [Atlantiss/NetherwingBugtracker#4217]
[//]: # (Enclose links to things related to the bug using http://wowhead.com or any other TBC database.)
[//]: # (You can use screenshot ingame to visual the issue.)
[//]: # (Write your tickets according to the format:)
[//]: # ([Quest][Azuremyst Isle] Red Snapper - Very Tasty!)
[//]: # ([NPC] Magistrix Erona)
[//]: # ([Spell][Mage] Fireball)
[//]: # ([Npc][Drop] Ghostclaw Lynx)
[//]: # ([Web] Armory doesnt work)
[//]: # (To find server revision type `.server info` command in the game chat.)

**Description**: 
[In this quest I have to kill a troll and his pet in a cave.](https://www.wowhead.com/quest=9470/a-gesture-of-goodwill)

**Current behaviour**:
I found the guy outside of the cave.
![wowscrnshot_011519_110333](https://user-images.githubusercontent.com/43505031/51173326-815cca80-18b5-11e9-9f58-596eaad841d6.jpg)

**Expected behaviour**: 
Should spawn inside the cave, not outside.
![image](https://user-images.githubusercontent.com/43505031/51173393-a18c8980-18b5-11e9-8479-608ea4d92ed0.png)

**Comment by Gniddikon** [comment]
This guy is still falsely spawning a bit outside the cave instead of inside.

**Comment by Exorcista** [comment]
Today it spawned fareish away from the cave almost behind it. Really easy to miss it.

**Comment by Tereneckla** [comment]
Fixed
