### ISSUE TITLE
[Spell] [Rogue] Preparation

### ISSUE THREAD

**Issue by iYi** [Atlantiss/NetherwingBugtracker#4219]
when pop preparation causes screen freeze for 1~ sec feels like i pause the game, tried without addons this bug appear still, also tried on different servers, this problem doesnt appear there just on Netherwing. its very annoying and possible game breaking in arenas please investigate it

**Comment by killablink** [comment]
same bug as #4178

**Comment by RandomGuyFromDiscordServer** [comment]
Close this one too then if the other one was fixed.
