### ISSUE TITLE
[Dungeon - Shadow Lab][Misc][NPC]Cabal Ritualist#18794  should attempt to run away in fear!

### ISSUE THREAD

**Issue by Tenoutoften** [Atlantiss/NetherwingBugtracker#4220]
**Description**: 
[[NPC]Cabal Ritualist#18794](https://www.wowhead.com/npc=18794/cabal-ritualist#comments) should attempt to run away in fear!
Video evidence [here](https://youtu.be/tnqVA72v4lo?t=31)

**Current behaviour**:
Doesn't run away in fear.

**Expected behaviour**: 
Should run away in fear.

**Server Revision**: 
2625

**Comment by Evolvee** [comment]
2863

**Comment by Evolvee** [comment]
![image](https://user-images.githubusercontent.com/1942409/53681135-396af900-3ce5-11e9-80be-aae6a2f7ac6f.png)

**Comment by Wolffenstein** [comment]
Fixed in rev 3387.
