### ISSUE TITLE
[NPC]Somnus moves with hyper speed

### ISSUE THREAD

**Issue by ircfelix** [Atlantiss/NetherwingBugtracker#4221]
**Description**: 
The npc Somnus runs very fast, roughly as fast as a charging warrior and there is no way to avoid dying to him once you've aggroed him while questing.

**Current behaviour**:
The npc Somnus runs very fast, roughly as fast as a charging warrior.

**Expected behaviour**: 
It is very unlikely that he should move so fast, so please fix his movement speed to normal.
https://de.wowhead.com/npc=12900/somnus#english-comments

> I found Somnus to be easily kiteable, at least from a Mage PoV.

> Might just be me, but he seems to move slower than the others.
> Von veno3 (12,573 –  2·9·88)  am 2008.07.30 (Patch 2.4.3)

**Server Revision**: 
2625

**Comment by Evolvee** [comment]
fixed in next rev
