### ISSUE TITLE
Quest Raene's Cleansing cant be completed

### ISSUE THREAD

**Issue by Relot** [Atlantiss/NetherwingBugtracker#4222]
**Description**: 
quest Raene's Cleansing http://db.hellfire-tbc.com/?quest=1027 can not be completed because the quest item does not fall out of the chest that should appear after the death of the mobs
**Current behaviour**:
after killing mobs, only loot remains
**Expected behaviour**: 
after killing mobs, must leave the chest as an object
**Server Revision**:

**Comment by Manaci** [comment]
Fixed
