### ISSUE TITLE
[Quest] Whispers of the Raven God

### ISSUE THREAD

**Issue by naekobest** [Atlantiss/NetherwingBugtracker#4223]
https://i.gyazo.com/d6fc0017362a0c7720049c0287ce1477.mp4
**Current behaviour**:
Does not trigger the quest event

**Expected behaviour**: 
should trigger and complete the quest 

**Server Revision**: 
2625

gg another quest bugged

**Comment by Wolffenstein** [comment]
Fixed in rev 2631.
