### ISSUE TITLE
[Item]  Orb of the Grishna

### ISSUE THREAD

**Issue by naekobest** [Atlantiss/NetherwingBugtracker#4224]
**Description**: 
Item which starts a quest

**Current behaviour**:
does not drop after 100 kills ( 0% )

**Expected behaviour**: 
should drop at least x after 100 kills ( 3 - 11% )

**Server Revision**: 
2625

**Comment by Wolffenstein** [comment]
![image](https://user-images.githubusercontent.com/1576644/51180292-5cbe1e00-18c8-11e9-8db3-f92285994379.png)

Has 15% chance to drop and did just fine for me after killing like ~10 mobs.
