### ISSUE TITLE
[NPC] Wyrmcult Zealot

### ISSUE THREAD

**Issue by naekobest** [Atlantiss/NetherwingBugtracker#4226]
**Description**: 
Is a mage, can cast spells

**Current behaviour**:
is a mage, can cast spells - has no mana
https://i.gyazo.com/thumb/1000/ebe376b7c30aa8b680c9040b139bbb61-jpg.jpg

**Expected behaviour**: 
is a mage, can cast spell, should have mana

**Server Revision**: 
2625

gg another bug

**Comment by Wolffenstein** [comment]
That isn't a bug, ask Blizzard why they made it this way.
