### ISSUE TITLE
[Quest][Item] Whelps of Wyrmcult

### ISSUE THREAD

**Issue by naekobest** [Atlantiss/NetherwingBugtracker#4227]
The net stopped working for me after 6 whelps
https://i.gyazo.com/2c961d70b4362f861df493d92059bdd4.mp4

revision
2625

**Comment by Wolffenstein** [comment]
It says "no charges" right there on the item.

**Comment by Dimbleglim** [comment]
I have the same issue with 12 charges. It isn't capturing any whelps no matter at what health level they are.

**Comment by Easyfraggy** [comment]
Are you trying to capture the correct whelps? Need SS of the mobs and item.

**Comment by Tereneckla** [comment]
https://youtu.be/B50g_Wuh9os

The item uses up 1 charge on start of the cast and 1 charge on end.

**Comment by BeastUnknown** [comment]
same problem for me, no charges 8/10, tried again 7/10 no charges. using multiple charges on a single whelp cast

**Comment by Wolffenstein** [comment]
Fixed in rev 3503.
