### ISSUE TITLE
[Pet][Water Elemental] Water elemental isn't chain casting his waterbolts.

### ISSUE THREAD

**Issue by killablink** [Atlantiss/NetherwingBugtracker#4229]
**Description**: Water Elemental is losing a lot of dps as he is currently not chain casting his water bolts. After casting one, he takes about 1 second before restarting to cast.

**Current behaviour**:Water Elemental is losing a lot of dps as he is currently not chain casting his water bolts. After casting one, he takes about 1 second before restarting to cast.

**Expected behaviour**: Chain casts.

**Server Revision**: Latest

**Comment by killablink** [comment]
https://gfycat.com/SmoggyDetailedFantail

Look at the top left pet frame, he casts waterbolt, finishes, waits 2 seconds before casting. Frost mages are losing a lot of dps because of this bug,

**Comment by killablink** [comment]
Water elemental is currently waiting till his water bolt reaches his target before it starts casting the next one, while it should just keep spam casting. Here's a clip from S2 TBC and how it acts currently (you can see on the top left my water elemental cast time in the pet frame)

https://gfycat.com/ImpossibleGreedyBlacklab
When the target is currently at melee range of the pet, he actually "chain casts" but even there it's slightly slower than retail

**Comment by Easyfraggy** [comment]
Should be resolved next update (according to changelog) please revise if that's not the case.
