### ISSUE TITLE
Great Goretusk

### ISSUE THREAD

**Issue by Mewmewww** [Atlantiss/NetherwingBugtracker#423]
[//]: # (Enclose links to things related to the bug using http://wowhead.com or any other TBC database.)
[//]: # (You can use screenshot ingame to visual the issue.)
[//]: # (Write your tickets according to the format:)
[//]: # ([Quest][Azuremyst Isle] Red Snapper - Very Tasty!)
[//]: # ([NPC] Magistrix Erona)
[//]: # ([Spell][Mage] Fireball)
[//]: # ([Npc][Drop] Ghostclaw Lynx)
[//]: # ([Web] Armory doesnt work)

**Description**: Lack of Great Goretusk spawns in Redridge mountains

**Current behaviour**: Literally only found 1 near bellygrub in redridge mountains. should be more according to questhelper + zygor.

**Expected behaviour**: Needs to be many more...

**Server Revision**: 2040

**Comment by aresbrutus** [comment]
Fixed in one of the next updates.
