### ISSUE TITLE
[Pet] Attack doesn't tag the Mob for you

### ISSUE THREAD

**Issue by zonk2** [Atlantiss/NetherwingBugtracker#4230]
**Description**: If your pet attacks a target first, it is not your tag. It has to be tag'd by yourself (or another one when he is like 'stealing' it)

**Current behaviour**: Pet attacks target -> still tag'able/red for everyone else

**Expected behaviour**: Your own Pet attacks target -> it should be your tag / grey for everyone else

**Server Revision**: Latest

**Comment by Wookiefister** [comment]
Yep just logged on to post this same bug very annoying

**Comment by Fuzedknight** [comment]
Can confirm it's bugged

**Comment by Tenoutoften** [comment]
This is a hunter bug, it looks to work fine for warlocks

**Comment by Easyfraggy** [comment]
Was about to say - this worked fine on my warlock the entire time.

**Comment by Wolffenstein** [comment]
Fixed in rev 2861.
