### ISSUE TITLE
No diminishing returns on npc sleep

### ISSUE THREAD

**Issue by Wookiefister** [Atlantiss/NetherwingBugtracker#4231]
[//]: # (Enclose links to things related to the bug using http://wowhead.com or any other TBC database.)
[//]: # (You can use screenshot ingame to visual the issue.)
[//]: # (Write your tickets according to the format:)
[//]: # ([Quest][Azuremyst Isle] Red Snapper - Very Tasty!)
[//]: # ([NPC] Magistrix Erona)
[//]: # ([Spell][Mage] Fireball)
[//]: # ([Npc][Drop] Ghostclaw Lynx)
[//]: # ([Web] Armory doesnt work)
[//]: # (To find server revision type `.server info` command in the game chat.)

**Description**: Was noticing no DRs on sleeps from the shadowforge chanters today at 6:53 AM PST 

**Current behaviour**: slept almost constantly by chanters for 8 secs each

**Expected behaviour**: diminishing returns on the sleep

**Server Revision**: 2633

**Comment by The14me** [comment]
Rev.3482 still an issue.

**Comment by Godmatik** [comment]
Rev 4016 - no longer an issue - the sleep from this mob properly gets DRed.
Probably fixed with new aura branch
