### ISSUE TITLE
Alliance Reputation doesnt increase Reputation with Alliance factions

### ISSUE THREAD

**Issue by Padatoo** [Atlantiss/NetherwingBugtracker#4232]
[//]: # (Enclose links to things related to the bug using http://wowhead.com or any other TBC database.)
[//]: # (You can use screenshot ingame to visual the issue.)
[//]: # (Write your tickets according to the format:)
[//]: # ([Quest][Azuremyst Isle] Red Snapper - Very Tasty!)
[//]: # ([NPC] Magistrix Erona)
[//]: # ([Spell][Mage] Fireball)
[//]: # ([Npc][Drop] Ghostclaw Lynx)
[//]: # ([Web] Armory doesnt work)
[//]: # (To find server revision type `.server info` command in the game chat.)

**Description**: 
Received 350 Reputation with Alliance from this quest "Return to Milton" 
https://vanilla-twinhead.twinstar.cz/?quest=542
and had 0 reputation increase with Alliance factions.
**Current behaviour**:
0 increase to all Alliance reputations
**Expected behaviour**: 
X increase to all Alliance reputations
**Server Revision**: 
2633

**Comment by Manaci** [comment]
I found out that "Alliance" and "Horde" Reputation is its own faction, so you can find it by going /run SetWatchedFactionIndex(1) (number should be akin to the top faction (This also counting just the "Alliance" and "Horde" faction subsections to show their invisible Reputation)
