### ISSUE TITLE
Flute of the ancients, cant res

### ISSUE THREAD

**Issue by Madnomadin** [Atlantiss/NetherwingBugtracker#4233]
[//]: # (Enclose links to things related to the bug using http://wowhead.com or any other TBC database.)
https://www.wowhead.com/item=11445/flute-of-the-ancients
[//]: # (You can use screenshot ingame to visual the issue.)
[//]: # (Write your tickets according to the format:)

**Description**: 
Cant summon the tree again if the escort is failed and abandoned
**Current behaviour**:

**Expected behaviour**: 
Should be able to summon the tree again.
**Server Revision**:

**Comment by The14me** [comment]
Rev.3482 Not an issue anymore. Flute still stays on abound quest and can resume the tree.
Can be closed.
