### ISSUE TITLE
[NPC][Felwood] Warpwood Shredder has "windfury" procs

### ISSUE THREAD

**Issue by Desst** [Atlantiss/NetherwingBugtracker#4234]
**Description**: 
This bug is pretty common among private servers. I'm sure there are other mobs with this issue
**Current behaviour**:
Every third or fourth attack Warpwood Shredder (normal melee swing) has a "windfury-like" proc causing him to attack 3 times at once

**Expected behaviour**: 
Mobs should attack you with normal melee swings once at a time

**Server Revision**:  2635

**Comment by 0vertime** [comment]
It has Thrash ability.
