### ISSUE TITLE
Green Hills of Stranglethorn 

### ISSUE THREAD

**Issue by sefamurat** [Atlantiss/NetherwingBugtracker#4235]
**Description**: Green Hills of Stranglethorn 

**Current behaviour**: Abandoning the quest "Green Hills of Stranglethorn" will destroy the completed chapters in your inventory, destroyed chapters can not be restored. This makes the quest impossible to complete.

**Expected behaviour**: Destroyed chapters should be restored by talking to Barnil Stonepot. Source: https://wow.gamepedia.com/The_Green_Hills_of_Stranglethorn_(old)

**Server Revision**: 2635

**Comment by Chritty** [comment]
This cannot be completed if you abandon the quest after completing a chapter. I asked a GM to exchange my pages for the chapter after I discovered this (Already turned it in once and still purchased the pages again) and they refused. Thus, the quest is broken until this is fixed. Either let the quest be repeatable with no XP gain or restore the chapter by talking to the NPC. GM Sillence was very unhelpful; only told me to do it again which is not even possible

**Comment by Wolffenstein** [comment]
Fixed in rev 3164.
