### ISSUE TITLE
 [Spell] [Hunter] Multishot queue

### ISSUE THREAD

**Issue by QWERTYQWERTYQWERTYX** [Atlantiss/NetherwingBugtracker#4236]
**Description**: 
 Sometimes hunter cant use multishot until an automatic shot occurs, or stop working altogether. Please fix this as you did it there https://github.com/Atlantiss/NetherwingBugtracker/issues/3804
**Expected behaviour**: 
should work as it should

**Server Revision**: 
2635

**Comment by The14me** [comment]
Must be fixed with the latest Hunter rework.
