### ISSUE TITLE
Enemy player pets show at 10% health

### ISSUE THREAD

**Issue by 0vertime** [Atlantiss/NetherwingBugtracker#4237]
**Description**: 
On few occassions I've noticed enemy player pet's being 10% and tried attacking them but their full health. Very misleading in pvp. Not just my client since my guildies have noted it as well.

https://i.imgur.com/mu67R2x.png

**Current behaviour**:
Pet's show low health.

**Expected behaviour**: 
Pet's should show their actual health.

**Server Revision**: 
2635

**Comment by killablink** [comment]
Happens to me too, or sometimes it looks like it has 0% hp

**Comment by Wolffenstein** [comment]
Fixed in rev 2641.
