### ISSUE TITLE
[Quest]Wanted: Baron Longshore

### ISSUE THREAD

**Issue by Demite** [Atlantiss/NetherwingBugtracker#4238]
Baron takes like 30 minutes to respawn with 200 people trying to do the quest.

**Comment by nullfoxh** [comment]
He has multiple spawns, usually ends up being on top of the hill where nobody will be looking. Seemed to spawn just fine for me days ago

**Comment by Demite** [comment]
Just spent an hour there with only two spawns and like 5 groups competing for it. He spawned in the same place both times. Just really crappy situation. I think the spawn needs to be reduced in timer atleast until the bulk of the players process through the zone.

**Comment by Wolffenstein** [comment]
It's working fine, he has like 4 spawn places.
