### ISSUE TITLE
 ([Quest][Azuremyst Isle] Show Gnomercy

### ISSUE THREAD

**Issue by Sothanwow** [Atlantiss/NetherwingBugtracker#424]
**Description**: 
 Minor issue In the quest Show Gnomercy  [Show Gnomercy](https://www.wowhead.com/quest=9537/show-gnomercy)   when the npc [engineer spark overgrind ](https://www.wowhead.com/npc=17243/engineer-spark-overgrind#abilities) turns aggressive and the player attacks him you are pvp flagged. 
Aside from that everything works he rps as he should and turns aggressive
*Current behaviour**:
turns player pvp flagged
**Expected behaviour**: 
shouldn't turn player on quest pvp flagged when attacked.
**Server Revision**: 
2040

**Comment by xmesaj2** [comment]
fix in rev 2054, needs testing
