### ISSUE TITLE
[Core][Pet] targeting enemy players pet makes it attack (abusable)

### ISSUE THREAD

**Issue by am3shan** [Atlantiss/NetherwingBugtracker#4240]
**Description**: 
hitting attack target key or right click on enemy pet, will automaticly make it attack you, regardless of range or pet stance
its easily abusable in neutral cities to make the guards kill a pet & its master, while leaving the abuser harmless
**Current behaviour**:
pet aggroes player who right click's it even in def stance
**Expected behaviour**: 
pet should turn hostile only when directed or if it had been hit...based on stance
**Server Revision**: 
2635

**Comment by The14me** [comment]
Rev.3482 still an issue. If u right click on the player the pet stay, but if u right click on the pet--->attack you.

**Comment by Wolffenstein** [comment]
Fixed in rev 3520.
