### ISSUE TITLE
[Hunter] Auto Shot bug when switching target

### ISSUE THREAD

**Issue by Th00p** [Atlantiss/NetherwingBugtracker#4241]
[//]: # (Enclose links to things related to the bug using http://wowhead.com or any other TBC database.)
[//]: # (You can use screenshot ingame to visual the issue.)
[//]: # (Write your tickets according to the format:)
[//]: # ([Quest][Azuremyst Isle] Red Snapper - Very Tasty!)
[//]: # ([NPC] Magistrix Erona)
[//]: # ([Spell][Mage] Fireball)
[//]: # ([Npc][Drop] Ghostclaw Lynx)
[//]: # ([Web] Armory doesnt work)
[//]: # (To find server revision type `.server info` command in the game chat.)

**Description**: Auto Shot doesn't shoot if you switch from one target to another while Auto Shot is activated.

**Current behaviour**: When Auto shooting a target and then switching to another target using tab or clicking the Auto Shot will get stuck in a loop and not shoot until you reset the Auto Shot by tapping Auto Shot twice.

**Expected behaviour**: Auto Shot should continue shooting even if you change target.

**Server Revision**: 2638

**Update**: Seems to only happen after a playing for a while.

**Comment by Realnairoby** [comment]
Have you checked your interface options that continueing auto-attack after target change is enabled?

**Comment by Th00p** [comment]
Yep the interface option Stop Auto Attack is disabled.

**Comment by guirssane** [comment]
Can confirm, it happened to me a lot in dungeon

**Comment by KredesX** [comment]
Please fix this. Like imagine this in pvp, its not god damn annoying!

**Comment by duzyizly** [comment]
this is how it looks like  : )
https://clips.twitch.tv/GloriousZealousPeachANELE

**Comment by Wolffenstein** [comment]
Fixed in rev 3422.
