### ISSUE TITLE
Group Loot in Outlands

### ISSUE THREAD

**Issue by Dract** [Atlantiss/NetherwingBugtracker#4244]
**Description**: 
Group looting quest items in outlands seems to be bugged currently, I understand that quest items aren't shared in Outland but it appears they are available for anyone to loot meaning that If you are ranged grouped with a meele you wont be getting any quest items

**Current behaviour**:
In Outland, Quest Items can always be looted by anyone who loots the corpse.

**Expected behaviour**: 
In Outland, Quest items are shared evenly amongst group members in a round robin style.

**Server Revision**: 
2635

**Comment by towneh** [comment]
Needs some research/evidence of this mechanic working as described.

**Comment by Manaci** [comment]
Not a bug
