### ISSUE TITLE
Quest - 9136 - Savage Fronds

### ISSUE THREAD

**Issue by Chulain** [Atlantiss/NetherwingBugtracker#4246]
[//]: # (https://classicdb.ch/?quest=9136.)
[//]: # ([Quest][Eastern Plaguelands] Savage Fronds)
[//]: # ([NPC] Rayne)

**Current behaviour**:
[Quest isn't available](https://classicdb.ch/?quest=9136)
**Expected behaviour**: 
This quest should be available if your rep with the argent dawn is at friendly or higher
**Server Revision**: 
2635

**Comment by Chulain** [comment]
same with:
https://classicdb.ch/?quest=9124
https://classicdb.ch/?quest=9126
https://classicdb.ch/?quest=9131

**Comment by Shanghi** [comment]
These and a bunch of others there were enabled again sometime in the last few days. A long time ago they were disabled along with Naxx quests since the raid is closed for now, but they're safe and possible to do so there's really no use in hiding them!
