### ISSUE TITLE
[Quest][An Earnest Proposition] Non-existant

### ISSUE THREAD

**Issue by Cutiepand** [Atlantiss/NetherwingBugtracker#4247]
https://vanilla-twinhead.twinstar.cz/?quest=8917

# [Quest][An Earnest Proposition]
# [NPC] Mokvar
# 

**Description**: 
The quest chain is unavailable.

**Current behaviour**:
Not able to pick up quest.

**Expected behaviour**: 
Quest that is able to be picked up at level 58.

![image](https://user-images.githubusercontent.com/46035147/51219857-1a7df680-1933-11e9-9601-d978fc10e3fb.png)

**Comment by wtRCH** [comment]
@aresbrutus

**Comment by Evolvee** [comment]
@Shanghi

**Comment by Shanghi** [comment]
There's always a chance! I re-enabled some Light's Hope Chapel ones for the next server update but those were mostly simple ones where you turn in items. I'll ask the person that disabled them if those first 17 or 18 would be ok the next time I see him, but they may be in a disgusting non-working state that would only give false hope to people starting the chain.

**Comment by Cutiepand** [comment]
![image](https://user-images.githubusercontent.com/46035147/54256982-169ad900-455e-11e9-87a3-ba31e931f166.png)
Oof
The quest Mok'var (and other T0.5 NPCS) should give is the one of the title of this thread. "An Earnest Proposition".

Right now we're at step 2 of the chain with the first step unable of being picked up.

Thanks for the hard work.

**Comment by Manaci** [comment]
Fixed
