### ISSUE TITLE
mob still grey after initial tagger dies

### ISSUE THREAD

**Issue by Chulain** [Atlantiss/NetherwingBugtracker#4248]
**Description**: 
mob still grey after initial tagger dies
**Current behaviour**:
if initial tagger dies, the mob remains grey thus no loot/exp
**Expected behaviour**: 
https://www.youtube.com/watch?v=of6kiLqJtHY&feature=youtu.be&t=18
the horde dies -> alliance hunter kills zhevra that was tagged by the horde-> can be looted
**Server Revision**: 
2635

**Comment by The14me** [comment]
https://i.imgur.com/HixS8eM.png
Look like it was just a bug back then...so nothing to be fixed.
Can be closed.
