### ISSUE TITLE
[Dungeon] Old hillsbrad foothills - Mobs spawning at the wrong level

### ISSUE THREAD

**Issue by Johra92** [Atlantiss/NetherwingBugtracker#4249]
[//]: # (Enclose links to things related to the bug using http://wowhead.com or any other TBC database.)
[//]: # (You can use screenshot ingame to visual the issue.)
[//]: # (Write your tickets according to the format:)
[//]: # ([Quest][Azuremyst Isle] Red Snapper - Very Tasty!)
[//]: # ([NPC] Magistrix Erona)
[//]: # ([Spell][Mage] Fireball)
[//]: # ([Npc][Drop] Ghostclaw Lynx)
[//]: # ([Web] Armory doesnt work)
[//]: # (To find server revision type `.server info` command in the game chat.)

**Description**: 
 Several packs of mobs that spawn during the Thrall escort are level 71
**Current behaviour**:
It seems like several packs that spawn throughout the dungeon run is spawned at heroic level rather than the normal level. Not all of them do, but several packs were spawning at level 71. 
**Expected behaviour**: 
They are supposed to be level 66-67 when spawning in the normal version of the dungeon. 
**Server Revision**: 
2635

**Comment by wtRCH** [comment]
@Wolffenstein

**Comment by wtRCH** [comment]
@aresbrutus

**Comment by Evolvee** [comment]
This is a core problem - Thralls script summons wrong NPC entry.

In stables and in church.

![image](https://user-images.githubusercontent.com/1942409/51427858-b3936280-1bfc-11e9-8dbf-f2847e21d77b.png)

**Comment by Godmatik** [comment]
Confirmed, still happens.

**Comment by Wolffenstein** [comment]
Fixed in rev 3104.
