### ISSUE TITLE
[Chat] Shift-Leftclick Query

### ISSUE THREAD

**Issue by Phibs77** [Atlantiss/NetherwingBugtracker#425]
[//]: # (Enclose links to things related to the bug using http://wowhead.com or any other TBC database.)
[//]: # (You can use screenshot ingame to visual the issue.)
[//]: # (Write your tickets according to the format:)
[//]: # ([Quest][Azuremyst Isle] Red Snapper - Very Tasty!)
[//]: # ([NPC] Magistrix Erona)
[//]: # ([Spell][Mage] Fireball)
[//]: # ([Npc][Drop] Ghostclaw Lynx)
[//]: # ([Web] Armory doesnt work)

**Description**: 
When shift-leftclicking on a name in chat multiple times, you get a new query every few seconds.
**Current behaviour**:
"Queued" queries every few seconds.
**Expected behaviour**: 
Only one query should be shown.
**Server Revision**: 
2040

**Comment by Easyfraggy** [comment]
I only get 1 query if i shift click multiple times on the person quickly in a row. 

Do you mean that you shouldnt be able to shift click the same persons name more than once at all? Right now you can only shift click once per 5 seconds or so.

Addon issue?

**Comment by Phibs77** [comment]
I can test it without addons.
Currently, when i spam shift-leftclick on a name in chat 10x, i get the info about level, guild etc 10x, one every few seconds.

**Comment by Phibs77** [comment]
Addon issue confirmed, thought it might be because of the server.
