### ISSUE TITLE
[Dungeon] Old hillsbrad foothills - Mobs spawning too rapidly during the end boss event

### ISSUE THREAD

**Issue by Johra92** [Atlantiss/NetherwingBugtracker#4250]
[//]: # (Enclose links to things related to the bug using http://wowhead.com or any other TBC database.)
[//]: # (You can use screenshot ingame to visual the issue.)
[//]: # (Write your tickets according to the format:)
[//]: # ([Quest][Azuremyst Isle] Red Snapper - Very Tasty!)
[//]: # ([NPC] Magistrix Erona)
[//]: # ([Spell][Mage] Fireball)
[//]: # ([Npc][Drop] Ghostclaw Lynx)
[//]: # ([Web] Armory doesnt work)
[//]: # (To find server revision type `.server info` command in the game chat.)

**Description**: 
At the last boss several packs of black dragons spawn. Each pack spawns one after another correctly from what I saw, but they  spawn very fast after one pack dies. Making the fight much harder than it's supposed to be. I don't have any concrete proof of this, I don't know if there's a proper way of showing that the spawn timer is supposed to be different. But I am quite sure that you would find it to be very fast as well if you have a look at it. 
**Current behaviour**:
After one pack dies during the last boss fight the upcoming one spawns within one second after that. 
**Expected behaviour**: 
Giving about a 3-5 second window between each mob pack, where the dragons would spawn before becoming agressive and start engaging the group. 
**Server Revision**: 
2635

**Comment by Jalapan** [comment]
Agreed. the timer between wave spawns should be 3-5 seconds.

**Comment by wtRCH** [comment]
@aresbrutus

**Comment by devo6969** [comment]
Takes 3 seconds for 2nd wave to spawn, and 1 seconds for the last wave. I see this as invalid. PTR acts quiet similar

PTR - https://www.youtube.com/watch?v=VBxjPuoco24
Retail TBC - (Play as .75 speed) https://youtu.be/XYaerv01FFU?t=52
