### ISSUE TITLE
[Spell][Warrior] Sweeping strikes

### ISSUE THREAD

**Issue by teddys** [Atlantiss/NetherwingBugtracker#4253]
**Current behaviour**: The killing blow you land (can be autoattack/ability) is not affected by sweeping strikes.

**Expected behaviour**:  All of the attacks you make are affected by sweeping strikes.

**Server Revision**: 2635

**Comment by liek0r** [comment]
Interesting. I haven't noticed that. But at least execute killing blows are not affected by sweeping strikes. 

See https://github.com/Atlantiss/NetherwingBugtracker/issues/894

**Comment by teddys** [comment]
Just noticed that it happens only sometimes ... right now slam killing blow was correctly affected by sweeping strikes. Maybe it has something to do with spell batching?

**Comment by femdead** [comment]
also occurs on any attack made in the last ~second of sweeping strikes duration

**Comment by Godmatik** [comment]
Duplicate of #8521 
Gonna close this one out
