### ISSUE TITLE
[NPC] Spell range

### ISSUE THREAD

**Issue by syphex97** [Atlantiss/NetherwingBugtracker#4254]
[//]: # (Enclose links to things related to the bug using http://wowhead.com or any other TBC database.)
[//]: # (You can use screenshot ingame to visual the issue.)
[//]: # (Write your tickets according to the format:)
[//]: # ([Quest][Azuremyst Isle] Red Snapper - Very Tasty!)
[//]: # ([NPC] Magistrix Erona)
[//]: # ([Spell][Mage] Fireball)
[//]: # ([Npc][Drop] Ghostclaw Lynx)
[//]: # ([Web] Armory doesnt work)
[//]: # (To find server revision type `.server info` command in the game chat.)

**Description**: 
Apprently lately i've noticed mobs when they are channeling a spell their range is either too long or they can cast the spell no matter how far away you when they started channeling it, i cannot test how far away i can due to being limited to my movement speed But im for sure that mobs have a longer range than they did a few days ago.

This video might not be the best preview of what im hinting of, but it should give you a good idea of what i mean and can be tested with increased movement speed by a staff member.

https://youtu.be/Ce7XXY3TVYU

**Current behaviour**:

**Expected behaviour**: 

**Server Revision**: 
2635

**Comment by Fuzedknight** [comment]
Does this also apply to player pets like the water elemental? I've had some strange experiences with the water ele shooting from very far distances.

**Comment by syphex97** [comment]
> Does this also apply to player pets like the water elemental? I've had some strange experiences with the water ele shooting from very far distances.

Should because its a problem that effects npc's, try to get a mage to test it out in a duel
