### ISSUE TITLE
[Spell][Hunter] Auto Shot Fixed

### ISSUE THREAD

**Issue by Tokretsim** [Atlantiss/NetherwingBugtracker#4256]
[//]: # (Enclose links to things related to the bug using http://wowhead.com or any other TBC database.)
[//]: # (You can use screenshot ingame to visual the issue.)
[//]: # (Write your tickets according to the format:)
[//]: # ([Quest][Azuremyst Isle] Red Snapper - Very Tasty!)
[//]: # ([NPC] Magistrix Erona)
[//]: # ([Spell][Mage] Fireball)
[//]: # ([Npc][Drop] Ghostclaw Lynx)
[//]: # ([Web] Armory doesnt work)
[//]: # (To find server revision type `.server info` command in the game chat.)

**Description**: 
Auto shot continues even if hunter runs out of range.
**Current behaviour**:
If Auto shot is on and hunter runs out of range, Auto shot doesn't turns off. Happens versus players
![wowscrnshot_011619_103429](https://user-images.githubusercontent.com/38424067/51234039-a9fbc780-197c-11e9-9b11-76c0cb1f30da.jpg)
and mobs
![wowscrnshot_011619_103546](https://user-images.githubusercontent.com/38424067/51234075-bf70f180-197c-11e9-98a7-4ddcd15feffa.jpg)
**Expected behaviour**: 
When hunter runs out of range, Auto shot must stop.
**Server revision**
2635

**Comment by The14me** [comment]
Rev.3482 not an issue anymore.
Can be closed.
