### ISSUE TITLE
[Skinning][Loot] Un'Goro Crater beasts cannot be skinned

### ISSUE THREAD

**Issue by pesky89** [Atlantiss/NetherwingBugtracker#4257]
**Description**: 
Un'Goro Crater beasts cannot be skinned after being looted. Instead of being skinnable, the mouse cursor is still in "loot mode", but looting again does not do anything.
**Current behaviour**:
Un'Goro Crater beasts cannot be skinned after being looted. Instead of being skinnable, the mouse cursor is still in "loot mode", but looting again does not do anything. Sometimes it opens the loot window with "empty loot icon", sometimes it does nothing. I think the game treats the mob as still having loot, thus cannot be skinned.
**Expected behaviour**: 
Un'Goro Crater beasts should be skinnable after their loot has been collected.
**Server Revision**: 
checked 01.15.2019 22:00 server time

**Comment by killablink** [comment]
It's most likely because of the start quest item that seems to keep dropping even if you started/finished the quest

**Comment by wtRCH** [comment]
@aresbrutus @Shanghi

**Comment by kwah8787** [comment]
can confirm that i have not received the A Mangled Journal (this item begins a quest) yet and it is still giving me the bug. Even on beasts that have nothing to do with any quests i have still give the bug.

revision 2825

**Comment by The14me** [comment]
Rev. 3460 not an issue anymore.
Can be closed.
