### ISSUE TITLE
[Spell][Warlock] Soul Siphon

### ISSUE THREAD

**Issue by Dramacydal** [Atlantiss/NetherwingBugtracker#4259]
[//]: # (Enclose links to things related to the bug using http://wowhead.com or any other TBC database.)
[//]: # (You can use screenshot ingame to visual the issue.)
[//]: # (Write your tickets according to the format:)
[//]: # ([Quest][Azuremyst Isle] Red Snapper - Very Tasty!)
[//]: # ([NPC] Magistrix Erona)
[//]: # ([Spell][Mage] Fireball)
[//]: # ([Npc][Drop] Ghostclaw Lynx)
[//]: # ([Web] Armory doesnt work)
[//]: # (To find server revision type `.server info` command in the game chat.)
Soul Siphon (Rank 1) http://db.hellfire-tbc.com/?spell=17804
Soul Siphon (Rank 2)  http://db.hellfire-tbc.com/?spell=17805
**Description**: 
Increases the amount drained by your Drain Life spell by an additional 2-4% for each Affliction effect on the target, up to a maximum of 24-60% additional effect.
**Current behaviour**:
Does not increase amount drained depending on amount afflictions spells applied on target
**Expected behaviour**: 
Must increase amount drained depending on amount afflictions spells applied on target
**Server Revision**: 
???

**Comment by Jalapan** [comment]
@Wolffenstein

**Comment by Wolffenstein** [comment]
It's working fine for me. Perhaps it's not loading your talent properly? What are your nicknames so I can check?

**Comment by Jalapan** [comment]
update, seems to only affect only some people and for me it was solved by a GM resetting my passive skills.

**Comment by Tereneckla** [comment]
Fixed
