### ISSUE TITLE
[NPC] Laughing Sister 4054 not giving XP

### ISSUE THREAD

**Issue by maronics** [Atlantiss/NetherwingBugtracker#426]
Laughing Sister 4054 in Ashenvale does not give XP for killing them. Cenarion Protector 3797 with same faction, same spot, same job according to wowpedia do give XP. They're both faction of Darnassus and maybe some PvP guard interaction or something? But one of them should be wrong I guess, as they're seemingly fullfilling the same role.

**Server Revision**: 2040

**Comment by Jezofine** [comment]
Not giving XP on 2060 too.

**Comment by totaemoeggerli** [comment]
Duplicate https://github.com/Atlantiss/NetherwingBugtracker/issues/704

**Comment by Easyfraggy** [comment]
https://github.com/Atlantiss/NetherwingBugtracker/issues/704#issuecomment-425627575 additional info on Ordanus also not giving xp

**Comment by Tenoutoften** [comment]
Possibly fixed with 2266?

**Comment by wtRCH** [comment]
@pelekon

**Comment by duzyizly** [comment]
tested with lvl 20, 25, 30. Gives no XP - mandatory leveling/fresh NPC (becasue of sacred flame quest).
![WoWScrnShot_061920_202459](https://user-images.githubusercontent.com/43931626/85168781-24fc9800-b26b-11ea-82cd-1cb3fecf55e8.jpg)
![WoWScrnShot_061920_202524](https://user-images.githubusercontent.com/43931626/85168785-262dc500-b26b-11ea-95c7-0a910ea7db39.jpg)
![WoWScrnShot_061920_202548](https://user-images.githubusercontent.com/43931626/85168788-26c65b80-b26b-11ea-9306-bf889f52f413.jpg)

**Comment by Wolffenstein** [comment]
Fixed in rev 3392.
