### ISSUE TITLE
[SPELL][PRIEST]Touch of weakness - blackout

### ISSUE THREAD

**Issue by lfx-h** [Atlantiss/NetherwingBugtracker#4262]
**Description**: 
Touch of weakness interaction with the blackout talent.

**Current behaviour**: 
Touch weakness seems to not proc the blackout talent. 

**Expected behaviour**: 
https://www.wowhead.com/forums&topic=34684&p=3950316
According to this thread and a couple people I've asked, touch of weakness should have the chance to proc blackout.

**Server Revision**: 
2635

**Comment by Desst** [comment]
It definitely used to proc in revision 2605 for sure

**Comment by shaxey** [comment]
I only have 1 point in blackout, but I spent a couple hours farming mobs for a mount and I didn't see it proc once. Could be insanely unlucky but doubt it. Worth checking out I'd say.

**Comment by Za262** [comment]
I have 5 points in Blackout and Touch of Weakness is procing the stun. It was working just fine last night and has been all week.

**Comment by shaxey** [comment]
False alarm, it works

**Comment by The14me** [comment]
Since it works ^ ---> Can be closed.
