### ISSUE TITLE
[Spell][Warlock] Eye of Kilrogg

### ISSUE THREAD

**Issue by elasdmehico** [Atlantiss/NetherwingBugtracker#4263]
[//]: # (Enclose links to things related to the bug using http://wowhead.com or any other TBC database.)
[//]: # (You can use screenshot ingame to visual the issue.)
[//]: # (Write your tickets according to the format:)
[//]: # ([Quest][Azuremyst Isle] Red Snapper - Very Tasty!)
[//]: # ([NPC] Magistrix Erona)
[//]: # ([Spell][Mage] Fireball)
[//]: # ([Npc][Drop] Ghostclaw Lynx)
[//]: # ([Web] Armory doesnt work)
[//]: # (To find server revision type `.server info` command in the game chat.)

**Description**: Summons an Eye of Kilrogg and binds your vision to it. The eye is stealthed and moves quickly but is very fragile.

**Current behaviour**: Can't cast this spell while already controlling a demon pet.

**Expected behaviour**: Should be able to cast this while you have a pet out. Also upon cancelling eye of kilrogg your pet should be teleported on top of your character.

**Server Revision**: 2635

Proof 1:
Video of warlock having succubus out and casting eye of kilrogg. If you continue watching a few seconds after the link provided you'll see he's in a party with a night elf and a human paladin. This confirms the succubus belongs to the warlock.

https://youtu.be/Pdn-IaYXfFc?t=29

Proof 2:
Comment from patch 2.4.0 saying "Casing Eye of Kilrogg will replace your current pet, causing it to temporarily despawn. How is this useful? When you cancel the effect your pet appears on top of you. This is very helpful in certain instances where you have to jump off of something and don't want your pet to path around and aggro everything nearby - set it on stay, go where you need to be, summon an Eye, and then cancel it. Your pet will teleport to you."

https://www.wowhead.com/spell=126/eye-of-kilrogg#comments

Proof 3:
Comment from patch 3.1.0 (wotlk) confirming it hasn't been changed since then...
"This is the Eye of Getting Your Pet Unstuck.
Summon and release it in a guaranteed-to-remain-stuck situation like the leap from the pipe leading to Gluth, and your pet will appear next to you again. Faster than resummoning the pet itself."

https://www.wowhead.com/spell=126/eye-of-kilrogg#comments

Steps to reproduce:
1. Summon any pet
2. Cast eye of kilrog
3. Notice the error message

**Comment by leeviathan** [comment]
Still not working

**Comment by duzyizly** [comment]
still not working as rev 3367 : (

**Comment by Wolffenstein** [comment]
Fixed in rev 3387.
