### ISSUE TITLE
[Item] Heavy Armor Kit

### ISSUE THREAD

**Issue by KevinSvard** [Atlantiss/NetherwingBugtracker#4264]
**Description**: 
Use: Permanently increase the armor value of an item worn on the chest, legs, hands or feet by 24. Only usable on items level 15 and above.

**Current behaviour**:
When trying to enchant another playing through the trade window with Heavy Armor Kit you get the error message: "Item is already enchanted".

**Expected behaviour**: 
If item level is 15 or above, it should get enchanted like an regular enchant and applied when both parties select Trade.

**Server Revision**:

**Comment by The14me** [comment]
Rev.3483 Not an issue anymore.
Can be closed.
