### ISSUE TITLE
Schematic: Accurate Scope missing from vendors

### ISSUE THREAD

**Issue by mirosvk1** [Atlantiss/NetherwingBugtracker#4265]
[//]: # (Enclose links to things related to the bug using http://wowhead.com or any other TBC database.)
[//]: # (You can use screenshot ingame to visual the issue.)
[//]: # (Write your tickets according to the format:)
[//]: # ([Quest][Azuremyst Isle] Red Snapper - Very Tasty!)
[//]: # ()
[//]: # ([Spell][Mage] Fireball)
[//]: # ([Npc][Drop] Ghostclaw Lynx)
[//]: # ([Web] Armory doesnt work)
[//]: # (To find server revision type `.server info` command in the game chat.)

**Description**: 
Schematic: Accurate Scope(http://db.hellfire-tbc.com/?item=13310 ) missing from only 2 vendors that should have it. And that is Mazk Snipeshot <Engineering Supplies> in Boty Bay (http://db.hellfire-tbc.com/?npc=2685) and Super-Seller 680 in Desolace (http://db.hellfire-tbc.com/?npc=12246)

Gnomish Engeneering cannot be complete bcs of this issue.
**Current behaviour**:

**Expected behaviour**: 

**Server Revision**:

**Comment by wtRCH** [comment]
@aresbrutus

**Comment by Shanghi** [comment]
It was just sold out. You're not supposed to be able to see a 0 quantity item like you can on other private servers.
