### ISSUE TITLE
Karazhan chess event

### ISSUE THREAD

**Issue by wedemhaha** [Atlantiss/NetherwingBugtracker#4267]
[//]: # (Enclose links to things related to the bug using http://wowhead.com or any other TBC database.)
[//]: # (You can use screenshot ingame to visual the issue.)
[//]: # (Write your tickets according to the format:)
[//]: # ([Quest][Azuremyst Isle] Red Snapper - Very Tasty!)
[//]: # ([NPC] Magistrix Erona)
[//]: # ([Spell][Mage] Fireball)
[//]: # ([Npc][Drop] Ghostclaw Lynx)
[//]: # ([Web] Armory doesnt work)
[//]: # (To find server revision type `.server info` command in the game chat.)

**Description**: 
Currently when you get to the chess event in Kara neither Horde or Alliance can start the event. When you talk to the king the event simply will not start. 
**Current behaviour**:
When either faction talks to their respective "King" they are placed inside the piece and teleported to the door, but the event does not start and you need to relog in order to remove yourself from the chess piece. 
**Expected behaviour**: 
When a player enters their respective king piece the event should begin. 
**Server Revision**:

**Comment by wtRCH** [comment]
@Wolffenstein

**Comment by Wolffenstein** [comment]
Fixed in rev 2640.
