### ISSUE TITLE
[EN][Server][Login-Issue] Instant "Disconnected from Server" 

### ISSUE THREAD

**Issue by Steverus1** [Atlantiss/NetherwingBugtracker#4268]
**Description:** On the Client Login Screen: After Login you get instant message "Disconnected from Server", although Server is online and working and your login data is correct. (Using Windows 10)

you lose a lot of players everyday because of this serious issue.

https://forum.atlantiss.eu/netherwing/topic/473-cant-log-in/
https://forum.atlantiss.eu/netherwing/topic/496-unable-to-log-in-to-account/
https://forum.atlantiss.eu/netherwing/topic/454-cant-log-in/
https://forum.atlantiss.eu/netherwing/topic/480-cant-log-instant-dc/
https://forum.atlantiss.eu/netherwing/topic/388-disconnected-from-server/
https://forum.atlantiss.eu/netherwing/topic/530-i-cant-logg-in-after-the-last-crash-disconnected-from-server-every-time-i-try-to-logg-in/

- Login Data is 100% correct
- No 2fa
- Login on Website is working flawless
- Deleted Cache, WTF, Logs
- Tried VPN 
- Tried multiple DNS Servers (Router Configuration)
- Game Master confirmed that my account is not banned
- Tried another Client
- Restarted Computer / Used another machine
- changed Password

nothing helped!

**Current behaviour:** After typting in username, password and click "Log in" I get instantly the message "Disconnected from Server". Same behaviour as If I'd input the wrong login, but the login is 100% correct.

**Expected behaviour:** Connection to Server

**Proof:** I tried to log in with a different account and there it works flawless. 

**Steps to reproduce the problem:**

2. Contact me on Discord and I'll give you my Account Name (Phonix#3038)

**Revision:** 2635

**Comment by Sabre142** [comment]
Try set realmlist play.atlantiss.eu

**Comment by Drayo** [comment]
Are you using a non-english client?

**Comment by Evolvee** [comment]
its hopefully fixed, waiting for update i guess
