### ISSUE TITLE
[quest][hillsbrad] Elixir of Suffering

### ISSUE THREAD

**Issue by knasen88** [Atlantiss/NetherwingBugtracker#427]
[//]: # (Enclose links to things related to the bug using http://wowhead.com or any other TBC database.)
[//]: # (You can use screenshot ingame to visual the issue.)
[//]: # (Write your tickets according to the format:)
[//]: # ([Quest][Azuremyst Isle] Red Snapper - Very Tasty!)
[//]: # ([NPC] Magistrix Erona)
[//]: # ([Spell][Mage] Fireball)
[//]: # ([Npc][Drop] Ghostclaw Lynx)
[//]: # ([Web] Armory doesnt work)

**Description**: 
Very low droprate, will definetely be a huge bottleneck on release. 
**Current behaviour**:

**Expected behaviour**: 

**Server Revision**:

**Comment by aresbrutus** [comment]
Fixed in one of the next updates.

**Comment by aresbrutus** [comment]
The quest is how it should be.
