### ISSUE TITLE
BFD summoning boss water elementals deal too much damage

### ISSUE THREAD

**Issue by ghost** [Atlantiss/NetherwingBugtracker#4270]
In BFD there is a room with four candles where a few groups of mobs come in intervals - the group of water elementals seem to do way too much damage, or at least completely out of proportion with the other groups

**Comment by Tenoutoften** [comment]
Been similar reports on too much damage with no source info https://github.com/Atlantiss/NetherwingBugtracker/issues/3919

**Comment by devo6969** [comment]
Classic - https://youtu.be/rGRJFjPea4A?t=1951 (They seem to do a decent amount of damage) no number values though

**Comment by Tereneckla** [comment]
That is the damage they currently deal
