### ISSUE TITLE
[core][pet][combat][hunter][warlock]  Pets  cause combat bug in zulfarrak. have to dismiss which make my class unplayable.

### ISSUE THREAD

**Issue by networm555** [Atlantiss/NetherwingBugtracker#4271]
have to dismiss which make my class unplayable.

**Comment by Tenoutoften** [comment]
https://github.com/Atlantiss/NetherwingBugtracker/issues/4271
https://github.com/Atlantiss/NetherwingBugtracker/issues/2885

**Comment by The14me** [comment]
Since the other issue gets closed, and there is no info about this one. Must be fixed.

**Comment by Godmatik** [comment]
Occurs from mind control, but was fixed a long time ago.

Closing.
