### ISSUE TITLE
[Quest][Escort][Searing Gorge] Suntara Stones Part 1

### ISSUE THREAD

**Issue by KredesX** [Atlantiss/NetherwingBugtracker#4272]
[//]: # (Enclose links to things related to the bug using http://wowhead.com or any other TBC database.)
[//]: # (You can use screenshot ingame to visual the issue.)
[//]: # (Write your tickets according to the format:)
[//]: # ([Quest][Azuremyst Isle] Red Snapper - Very Tasty!)
[//]: # ([NPC] Magistrix Erona)
[//]: # ([Spell][Mage] Fireball)
[//]: # ([Npc][Drop] Ghostclaw Lynx)
[//]: # ([Web] Armory doesnt work)
[//]: # (To find server revision type `.server info` command in the game chat.)

**Description**: I started this escort quest by mistake, and didnt wanna do it right away. The NPC just wandered off. Later on i wanted to do the quest but NPC has not yet respawned, i waited like 20-30 mins and still no respawn. Quest might have bugged out because i started it without actually doing it.

**Current behaviour**: Doesn't respawn if not completed.

**Expected behaviour**: Should respawn after a while, even when not being completed.

**Server Revision**: 2635

**Comment by KredesX** [comment]
There seems to be a really long respawn timer? but is working.

**Comment by leeviathan** [comment]
I just ran into Dorius standing near the tunnel to Loch Modan. I believe he's stuck. I've checked the quarry a couple times today and it has been empty. I'm guessing something went wrong and instead of de-spawning after he dies at the end of the escort, instead he remained alive and broke the quest. Just a guess though.

**Comment by leeviathan** [comment]
I just checked this morning and he's still standing near the tunnel to Loch Modan
