### ISSUE TITLE
 [spell][hunter] Bug with aspect of the pack

### ISSUE THREAD

**Issue by Lillaeth** [Atlantiss/NetherwingBugtracker#4273]
[//]: # (Enclose links to things related to the bug using http://wowhead.com or any other TBC database.)
[//]: # (You can use screenshot ingame to visual the issue.)
[//]: # (Write your tickets according to the format:)
[//]: # ([Quest][Azuremyst Isle] Red Snapper - Very Tasty!)
[//]: # ([NPC] Magistrix Erona)
[//]: # ([Spell][Mage] Fireball)
[//]: # ([Npc][Drop] Ghostclaw Lynx)
[//]: # ([Web] Armory doesnt work)
[//]: # (To find server revision type `.server info` command in the game chat.)

**Description**: 
Lvl 40 hunter tried to give my lvl 16 priest a aspect of the pack for speed. It did not work.
![wowscrnshot_011619_152519](https://user-images.githubusercontent.com/46752270/51255460-9748b900-19a3-11e9-9949-c7c464dc8155.jpg)

**Current behaviour**:
Not giving aspect to low lvl char
**Expected behaviour**: 
Should give aspect to all
**Server Revision**:

**Comment by The14me** [comment]
https://classic.wowhead.com/spell=13159/aspect-of-the-pack#comments:id=2788238
Look like its not a bug
If I'm level 50 and use that Aspect in the party, other player/s must be level 30 to be able to benefit from it.
Rev.3483.
