### ISSUE TITLE
[Karazhan][Boss] Strawman in opera event

### ISSUE THREAD

**Issue by Brasso** [Atlantiss/NetherwingBugtracker#4278]
[//]: # (Enclose links to things related to the bug using http://wowhead.com or any other TBC database.)
[//]: # (You can use screenshot ingame to visual the issue.)
[//]: # (Write your tickets according to the format:)
[//]: # ([Quest][Azuremyst Isle] Red Snapper - Very Tasty!)
[//]: # ([NPC] Magistrix Erona)
[//]: # ([Spell][Mage] Fireball)
[//]: # ([Npc][Drop] Ghostclaw Lynx)
[//]: # ([Web] Armory doesnt work)
[//]: # (To find server revision type `.server info` command in the game chat.)

**Description**: 
Currently Strawman is only disoriented once by fire spells, after the disorient ends you can no longer disorient him again.
**Current behaviour**:
https://www.twitch.tv/videos/364594150?t=36m24s

**Server Revision**: 
2635

**Comment by wtRCH** [comment]
@Wolffenstein

**Comment by Tereneckla** [comment]
Fixed since then
