### ISSUE TITLE
[Spell] Shoot

### ISSUE THREAD

**Issue by Mackiavelly** [Atlantiss/NetherwingBugtracker#4279]
Description: 
If start attacking any mob with a wand, and then take to target any other mob at any distance, the character will continue to use the shoot at a new target even if the mob is very, very far

screen to gif:
https://fs12.fex.net/show/636054490022/1123608657/4db539e8/qwe.gif?1600w,0

P.S.
Unfortunately, the spell panel is not visible on the skin, but I think it’s obvious that, the mob I took on the target is very far beyond the limits of all my spells, even with warlock talents, while the wand has a rarius 30 yd

**Comment by sifiuocz** [comment]
The Auto shot and shoot are affected by the spell leeway most likely but it should not be. Once the player goes too far away from the target (cca 70 yards) the shooting cancels and "the too far away" client side error message pops up.

**Comment by Mackiavelly** [comment]
u see gif?

**Comment by wtRCH** [comment]
Duplicate.
