### ISSUE TITLE
[quest][hillsbrad] Elixir of Agony

### ISSUE THREAD

**Issue by knasen88** [Atlantiss/NetherwingBugtracker#428]
[//]: # (Enclose links to things related to the bug using http://wowhead.com or any other TBC database.)
[//]: # (You can use screenshot ingame to visual the issue.)
[//]: # (Write your tickets according to the format:)
[//]: # ([Quest][Azuremyst Isle] Red Snapper - Very Tasty!)
[//]: # ([NPC] Magistrix Erona)
[//]: # ([Spell][Mage] Fireball)
[//]: # ([Npc][Drop] Ghostclaw Lynx)
[//]: # ([Web] Armory doesnt work)

**Description**: 
LOW droprate, bottleneck guaranteed

**Current behaviour**:

**Expected behaviour**: 

**Server Revision**:

**Comment by knasen88** [comment]
I actually meant to type elixir of pain but if the other elixir quests is anything to go by it probably needs some checkup (Naga and murloc part i would assume)

**Comment by aresbrutus** [comment]
#414

Should be fixed already. PM Kutsal if this is not the case so I can re-open this.
