### ISSUE TITLE
[World] [Ghost can't waterwalk] 

### ISSUE THREAD

**Issue by Johra92** [Atlantiss/NetherwingBugtracker#4280]
[//]: # (Enclose links to things related to the bug using http://wowhead.com or any other TBC database.)
[//]: # (You can use screenshot ingame to visual the issue.)
[//]: # (Write your tickets according to the format:)
[//]: # ([Quest][Azuremyst Isle] Red Snapper - Very Tasty!)
[//]: # ([NPC] Magistrix Erona)
[//]: # ([Spell][Mage] Fireball)
[//]: # ([Npc][Drop] Ghostclaw Lynx)
[//]: # ([Web] Armory doesnt work)
[//]: # (To find server revision type `.server info` command in the game chat.)

**Description**: 
When you are dead you can't walk on water as a ghost.
**Current behaviour**:
When you are dead you can't walk on water as a ghost.
**Expected behaviour**: 
You would be able to walk on water when you are a ghost
**Server Revision**: 
2635

**Comment by Wolffenstein** [comment]
It's working fine for me... 

What race/class are you playing? Can anyone else confirm this?

**Comment by Johra92** [comment]
we died as a group, doing steamvaults. No one in the group could waterwalk as a ghost. I am playing human paladin :)

**Comment by Shanghi** [comment]
You probably figured it out from the last post but it happens if you die in any instance.

**Comment by killablink** [comment]
Confirmed, couldn't walk on water as a ghost when dying in karazhan

**Comment by Manaci** [comment]
Fixed
