### ISSUE TITLE
Bunch of Helboar spawns missing in Blasted Lands

### ISSUE THREAD

**Issue by 0vertime** [Atlantiss/NetherwingBugtracker#4281]
**Description**: 
https://classicdb.ch/?npc=5993

Edit: Might be shared spawn with Felbeast & Redstone Crystalhide.

**Current behaviour**:
Currently only 2 of the northern ones are spawning, 5 of the western ones are not spawning.

**Expected behaviour**: 
More spawns.

**Server Revision**: 
2635

**Comment by Shanghi** [comment]
You're right about them being shared spawns

**Comment by GMThunderan** [comment]
[Helboars](https://classic.wowhead.com/npc=5993) spawns in Blasted Lands missing. Making the quest [Warrior Kinship](https://classic.wowhead.com/quest=8423/warrior-kinship) a pain in the ass.
