### ISSUE TITLE
Quest: [H] JOB OPPORTUNITY: Culling the Competition

### ISSUE THREAD

**Issue by rangobob** [Atlantiss/NetherwingBugtracker#4282]
[//]: # (Enclose links to things related to the bug using http://wowhead.com or any other TBC database.)
[//]: # (You can use screenshot ingame to visual the issue.)
[//]: # (Write your tickets according to the format:)
[//]: # ([Quest][Azuremyst Isle] Red Snapper - Very Tasty!)
[//]: # ([NPC] Magistrix Erona)
[//]: # ([Spell][Mage] Fireball)
[//]: # ([Npc][Drop] Ghostclaw Lynx)
[//]: # ([Web] Armory doesnt work)
[//]: # (To find server revision type `.server info` command in the game chat.)

**Description**: 
Kill Dark Iron Lookout and loot his spyglass
**Current behaviour**:
no spyglass drops,
**Expected behaviour**: 
a spyglass drops
**Server Revision**:

**Comment by Shanghi** [comment]
I just checked and it's there. It's a low chance.
![image](https://user-images.githubusercontent.com/2672633/51267609-1f22c900-198c-11e9-9b54-23f42153be1b.png)

**Comment by rangobob** [comment]
Yes
Thats my bad. just found out.

**Comment by Shanghi** [comment]
That's ok since it's better to be safe than sorry!
