### ISSUE TITLE
looting in party/raid

### ISSUE THREAD

**Issue by antikiller69** [Atlantiss/NetherwingBugtracker#4284]
[//]: # (Enclose links to things related to the bug using http://wowhead.com or any other TBC database.)
[//]: # (You can use screenshot ingame to visual the issue.)
[//]: # (Write your tickets according to the format:)
[//]: # ([Quest][Azuremyst Isle] Red Snapper - Very Tasty!)
[//]: # ([NPC] Magistrix Erona)
[//]: # ([Spell][Mage] Fireball)
[//]: # ([Npc][Drop] Ghostclaw Lynx)
[//]: # ([Web] Armory doesnt work)
[//]: # (To find server revision type `.server info` command in the game chat.)

**Description**: looting in party/raid

**Current behaviour**:currently if correct person does not loot the body the game wont generate rolling window for green/blue/epic items, 5 man party, 4 ppl loot mob but its not their mob, fifth person loots say 30s later and then u get roll window appear since that mob had an item u could roll on

**Expected behaviour**: roll window should trigger instantly doesnt matter if the body u loot is urs or not

**Server Revision**:

**Comment by Manaci** [comment]
Fixed with loot rework
