### ISSUE TITLE
shadowmeld not breaking instantly

### ISSUE THREAD

**Issue by antikiller69** [Atlantiss/NetherwingBugtracker#4285]
[//]: # (Enclose links to things related to the bug using http://wowhead.com or any other TBC database.)
[//]: # (You can use screenshot ingame to visual the issue.)
[//]: # (Write your tickets according to the format:)
[//]: # ([Quest][Azuremyst Isle] Red Snapper - Very Tasty!)
[//]: # ([NPC] Magistrix Erona)
[//]: # ([Spell][Mage] Fireball)
[//]: # ([Npc][Drop] Ghostclaw Lynx)
[//]: # ([Web] Armory doesnt work)
[//]: # (To find server revision type `.server info` command in the game chat.)

**Description**: night elf racial shadowmeld makes person stealth

**Current behaviour**:popping NE out from shadowmeld with aoe spell such as demoralizing shout should remove shadowmeld instantly, however i think it is tied into spellbatching (this might be the case for any stealth stuff)

**Expected behaviour**: any aoe if not resisted should instantly remove stealth/shadowmeld instead being tied into spellbatching

**Server Revision**:

**Comment by The14me** [comment]
Rev.3483 not an issue anymore.
