### ISSUE TITLE
Tarren Mill Inn - gives instant rested experience

### ISSUE THREAD

**Issue by dmrljes** [Atlantiss/NetherwingBugtracker#4286]
**Description**: As soon as you enter the the Tarren Mill Inn, you get instant 1 bar rested experience. 

**Server Revision**: 2635

**Comment by nullfoxh** [comment]
Related: https://github.com/Atlantiss/NetherwingBugtracker/issues/4161

**Comment by Jalapan** [comment]
Same issue in ratchet inn, possibly more inns aswell

**Comment by The14me** [comment]
Rev.3483 not an issue anymore.
