### ISSUE TITLE
[Un'goro] Many mobs cant be looted and/or skinned

### ISSUE THREAD

**Issue by KredesX** [Atlantiss/NetherwingBugtracker#4287]
[//]: # (Enclose links to things related to the bug using http://wowhead.com or any other TBC database.)
[//]: # (You can use screenshot ingame to visual the issue.)
[//]: # (Write your tickets according to the format:)
[//]: # ([Quest][Azuremyst Isle] Red Snapper - Very Tasty!)
[//]: # ([NPC] Magistrix Erona)
[//]: # ([Spell][Mage] Fireball)
[//]: # ([Npc][Drop] Ghostclaw Lynx)
[//]: # ([Web] Armory doesnt work)
[//]: # (To find server revision type `.server info` command in the game chat.)

**Description**: Many mobs shows like they have loot or is ready to be skinned, but neither can they be looted or skinned. Noticed Mainly on Gorillas. 

**Current behaviour**: 

**Expected behaviour**: 

**Server Revision**: 2635

**Comment by Wolffenstein** [comment]
Fixed in rev 2644.
