### ISSUE TITLE
[Dungeon] [Shadow Labyrinth] Combat bug

### ISSUE THREAD

**Issue by Johra92** [Atlantiss/NetherwingBugtracker#4289]
[//]: # (Enclose links to things related to the bug using http://wowhead.com or any other TBC database.)
[//]: # (You can use screenshot ingame to visual the issue.)
[//]: # (Write your tickets according to the format:)
[//]: # ([Quest][Azuremyst Isle] Red Snapper - Very Tasty!)
[//]: # ([NPC] Magistrix Erona)
[//]: # ([Spell][Mage] Fireball)
[//]: # ([Npc][Drop] Ghostclaw Lynx)
[//]: # ([Web] Armory doesnt work)
[//]: # (To find server revision type `.server info` command in the game chat.)

**Description**: 
After we pull and kill each pack in the big room before the second boss in, more specifically the 4 packs in front of the corridor (that u start with) we get stuck in combat. And have to run of the dungeon and back in to be able to continue the run.
**Current behaviour**:
After we pull and kill each pack in the big room before the second boss in, more specifically the 4 packs in front of the corridor (that u start with) we get stuck in combat. 
**Expected behaviour**: 
Combat drops after mobs are dead.
**Server Revision**: 
2635

**Comment by Johra92** [comment]
Edit, after killing the second boss we're also stuck in combat. Although it seems like some party members arent in combat while others (including myself) still are.

**Comment by Tenoutoften** [comment]
Did you have a party member with a pet?

**Comment by Tenoutoften** [comment]
https://github.com/Atlantiss/NetherwingBugtracker/issues/4271

**Comment by Johra92** [comment]
Yes I think that must be it, I was playing the healer and I was mostly stuck in combat. We had several classes with pets!

**Comment by Fuzedknight** [comment]
During that run we had 2 hunters and a warlock. So 3 pets and that is a very strange bug.

**Comment by Tenoutoften** [comment]
I believe this bug has been reintroduced fixing the crashes
[2349][Core] Threat Fixes

[Core/Threat]:
- Fixed a combat-bug issue caused by certain AoE spells, making the players stuck in combat with their pets

**Comment by Godmatik** [comment]
Have not heard of this happening on Netherwing this past year and have not experienced it myself - being a hunter with a pet. Guess it was fixed.

Closing.
