### ISSUE TITLE
[Core Mechanic][Warrior]Whirlwind dodges doesn't trigger Overpower

### ISSUE THREAD

**Issue by antikiller69** [Atlantiss/NetherwingBugtracker#4290]
[//]: # (Enclose links to things related to the bug using http://wowhead.com or any other TBC database.)
[//]: # (You can use screenshot ingame to visual the issue.)
[//]: # (Write your tickets according to the format:)
[//]: # ([Quest][Azuremyst Isle] Red Snapper - Very Tasty!)
[//]: # ([NPC] Magistrix Erona)
[//]: # ([Spell][Mage] Fireball)
[//]: # ([Npc][Drop] Ghostclaw Lynx)
[//]: # ([Web] Armory doesnt work)
[//]: # (To find server revision type `.server info` command in the game chat.)

**Description**: whirlwind strikes nearby 4 foes

**Current behaviour**: strikes 4 mobs but if mobs dodge u cant use overpower proc on them

**Expected behaviour**: should be able to use overpower proc on mobs that dodge whirlwind strike

**Server Revision**:

**Comment by Tenoutoften** [comment]
I'd suggest to rename this to [Core Mechanic][Warrior]Whirlwind dodges doesn't trigger Overpower
https://github.com/Atlantiss/NetherwingBugtracker/issues/3943

**Comment by teddys** [comment]
why is this invalid?

**Comment by Easyfraggy** [comment]
IDK why it was marked invalid - it is only half true though - it does trigger overpower but only against the target that dodges - need proof if it should be different.

**Comment by Valmere** [comment]
easyfraggy's right, been that way as long as I can remember

but here's a google result anyway from 2007 http://www.arenajunkies.com/topic/1176-dodge-and-no-overpower/

**Comment by Easyfraggy** [comment]
I mean it is already working like that on NW afaik - maybe why it was closed. In any case would need proof that it should work differently.

**Comment by teddys** [comment]
> I mean it is already working like that on NW afaik - maybe why it was closed. In any case would need proof that it should work differently.

you have proof in the link above your post 
"Nope its not whirlwind I see the dodge pop up over my targets head. You can even whirlwind and see someone else dodge switch targets and overpower them. "

right now this is not the case ... you switch to the target that dodged whirlwind and you can't overpower them

**Comment by Easyfraggy** [comment]
Are you sure? Cus I did it several times while leveling - Theres a bug with whirlwind offhand attacks that make them not trigger overpower at all - maybe that's what you are experiencing?

**Comment by Hellhound1408** [comment]
Bug is inconsistent. Sometimes overpower procs. Sometimes it doesn't. Same issue with Deep Wounds Talent and Whirwind. Sometimes it procs Deep Wounds on crit when using WW, sometimes it doesn't.

**Comment by tsu-1** [comment]
Same happens on Classic TBC: https://clips.twitch.tv/JoyousEnticingHornetAMPEnergyCherry-B70irVLUH6xd02kY

**Comment by Godmatik** [comment]
Rev 4020
Overpower is only usable on target that dodges from whirlwind, that is working as intended
I also double checked and verified that off-hand whirlwind dodges are properly proccing overpower
