### ISSUE TITLE
[Honor][PvP] Players will get honor points from NPC's / Mobs killing enemy players.

### ISSUE THREAD

**Issue by KredesX** [Atlantiss/NetherwingBugtracker#4292]
[//]: # (Enclose links to things related to the bug using http://wowhead.com or any other TBC database.)
[//]: # (You can use screenshot ingame to visual the issue.)
[//]: # (Write your tickets according to the format:)
[//]: # ([Quest][Azuremyst Isle] Red Snapper - Very Tasty!)
[//]: # ([NPC] Magistrix Erona)
[//]: # ([Spell][Mage] Fireball)
[//]: # ([Npc][Drop] Ghostclaw Lynx)
[//]: # ([Web] Armory doesnt work)
[//]: # (To find server revision type `.server info` command in the game chat.)

**Description**: Title. Players get honor points when they are near a player getting killed by a NPC, without assisting the NPC.

**Current behaviour**: 

**Expected behaviour**: 

**Server Revision**: 2635

**Comment by Wolffenstein** [comment]
This should be fixed now.
