### ISSUE TITLE
[Dungeon] [Shadow Labyrinth] Not getting spirit shards every run

### ISSUE THREAD

**Issue by Johra92** [Atlantiss/NetherwingBugtracker#4293]
[//]: # (Enclose links to things related to the bug using http://wowhead.com or any other TBC database.)
[//]: # (You can use screenshot ingame to visual the issue.)
[//]: # (Write your tickets according to the format:)
[//]: # ([Quest][Azuremyst Isle] Red Snapper - Very Tasty!)
[//]: # ([NPC] Magistrix Erona)
[//]: # ([Spell][Mage] Fireball)
[//]: # ([Npc][Drop] Ghostclaw Lynx)
[//]: # ([Web] Armory doesnt work)
[//]: # (To find server revision type `.server info` command in the game chat.)

**Description**: 
We got spirit shards the first run, we ran outside (still had towers in Alliance control) and went back in for a second run. Did not get spirit shards from the boss the second time. 
**Current behaviour**:
We got spirit shards the first run, we ran outside (still had towers in Alliance control) and went back in for a second run. Did not get spirit shards from the boss the second time. 
**Expected behaviour**: 
Getting spirit shards from each boss while controling towers.
**Server Revision**: 
2635

**Comment by Zarant** [comment]
Whenever you die and release spirit, you lose the tower buff and it doesn't get reapplied when you zone back into the instance.

**Comment by MAY-THE-ETERNAL-SUN-SHINE-UPON-YOU** [comment]
More descriptive and easy to find issue at #5366

**Comment by Manaci** [comment]
^what he said
