### ISSUE TITLE
[Quest] Liquid Stone

### ISSUE THREAD

**Issue by rychersky** [Atlantiss/NetherwingBugtracker#4294]
[//]: # (Enclose links to things related to the bug using http://wowhead.com or any other TBC database.)
[//]: # (You can use screenshot ingame to visual the issue.)
[//]: # (Write your tickets according to the format:)
[//]: # ([Quest][Azuremyst Isle] Red Snapper - Very Tasty!)
[//]: # ([NPC] Magistrix Erona)
[//]: # ([Spell][Mage] Fireball)
[//]: # ([Npc][Drop] Ghostclaw Lynx)
[//]: # ([Web] Armory doesnt work)
[//]: # (To find server revision type `.server info` command in the game chat.)

This quest should be available from Lucien Tosselwrench after turning in "Coolant Heads Prevail" and "Gyro... What?" to Lotwil Veriatus. I am on a level 45 character and tried relogging but was not able to speak to Lucien.

**Comment by Sabre142** [comment]
You need to finish the other gnome's quests.

**Comment by rychersky** [comment]
The very first sentence indicates that I have done so. Thanks for reading.

**Comment by Sabre142** [comment]
You need to do the study of rock chain.

**Comment by Evolvee** [comment]
@Shanghi educate them 🤣

**Comment by Manaci** [comment]
Do other quests
