### ISSUE TITLE
can't rez if the person released while in a dungeon

### ISSUE THREAD

**Issue by staplerx300** [Atlantiss/NetherwingBugtracker#4295]
[//]: # (Enclose links to things related to the bug using http://wowhead.com or any other TBC database.)
[//]: # (You can use screenshot ingame to visual the issue.)
[//]: # (Write your tickets according to the format:)
[//]: # ([Quest][Azuremyst Isle] Red Snapper - Very Tasty!)
[//]: # ([NPC] Magistrix Erona)
[//]: # ([Spell][Mage] Fireball)
[//]: # ([Npc][Drop] Ghostclaw Lynx)
[//]: # ([Web] Armory doesnt work)
[//]: # (To find server revision type `.server info` command in the game chat.)

**Description**: 
if a person releases after a wipe it's impossible to rez them

**Current behaviour**:
^
**Expected behaviour**: 
you should be able to rez them
**Server Revision**: 
2645

**Comment by ibogdandx** [comment]
Yes this doesnt work and it is very annoying to deal with. From today if the person that died released you are not able to ressurect them , you ressurect them but nothing happens they dont get it....

**Comment by Mikik3jr** [comment]
The UI even shows that they are rezzed, but nothing appears.

**Comment by Tenoutoften** [comment]
https://github.com/Atlantiss/NetherwingBugtracker/issues/4473
https://github.com/Atlantiss/NetherwingBugtracker/issues/4354

**Comment by Manaci** [comment]
Fixed in rev 2737
