### ISSUE TITLE
Website Display Netherwing Realm Info 

### ISSUE THREAD

**Issue by grand-lotus-iroh** [Atlantiss/NetherwingBugtracker#4296]
Can you please update website and add Website Realm Info for Netherwing? This is the box that would be cool to have duplicated for Netherwing. More or less, just make the .server info command display on website.

![image](https://user-images.githubusercontent.com/1291364/51290701-7cda0400-19d2-11e9-8d94-2f6a0ccbab60.png)

There should be another box that has the TBC server info too.

**Comment by Wolffenstein** [comment]
We know.
