### ISSUE TITLE
Quest: Shutting down Manaforge Coruu

### ISSUE THREAD

**Issue by Rooik** [Atlantiss/NetherwingBugtracker#4298]
It does not work. Nothing happens and its stuck for 10 minutes.

**Comment by Nudelzwolf** [comment]
Can confirm, broken.

**Comment by Rooik** [comment]
This is still bugged

**Comment by Cofie** [comment]
Still not working. Cant click the Console tu shut it down

**Comment by duderous** [comment]
Can't interact with console for this quest, crystal dropped but can't use it.

**Comment by mywebpage-rocks** [comment]
Can confirm, you can loot the item but it's impossible to click on the console. There are enemy NPCs channeling rays to the console, even if you kill them you still cannot click on the console to begin shutting the manaforge down. It blocks quite important chain in Outland

**Comment by mywebpage-rocks** [comment]
Managed to complete the quest after restart today, not sure if person after me also was able to. 

However elves were not trying to stop the shutting down process. You could possibly just stand there still and quest would be completed anyway.

**Comment by Wolffenstein** [comment]
Fixed in rev 3104.
