### ISSUE TITLE
Quest: [Guardians of the Altar]

### ISSUE THREAD

**Issue by Ebeebe123** [Atlantiss/NetherwingBugtracker#4299]
[Guardians of the Altar] After finishing escort you should be able click altar of elune to complete quest, meanwhile while altar has cogwheel icon after clicking it nothing is happening which makes the quest unable to complete.

**Comment by Evolvee** [comment]
![image](https://user-images.githubusercontent.com/1942409/51427494-e20f3e80-1bf8-11e9-92ec-3d35b865f56b.png)

**Comment by Warlockdaddy** [comment]
I came here to add that the quest is still broken with the same issue, you can't click on the altar even though it has a cogwheel icon.

**Comment by HyperXewl** [comment]
same issue

**Comment by Jalapan** [comment]
still broken, altar unclickable in the end.

https://gyazo.com/aa216934698dce08eb9eefb2626c9cc4

**Comment by Tenoutoften** [comment]
https://github.com/Atlantiss/NetherwingBugtracker/issues/1966 close this one too then

**Comment by HyperXewl** [comment]
this is not fixed, still does nothing when you click the altar

**Comment by Falathrin** [comment]
Still broken

**Comment by ttghnw** [comment]
still broken

**Comment by DragunovUA** [comment]
wtf u guys doing? can u fix it?

**Comment by Jalapan** [comment]
@Wolffenstein

**Comment by balazskvr** [comment]
Still not working, can't click on the altar.

**Comment by Zelden848** [comment]
Still broken

**Comment by hesusinc** [comment]
And still not working

**Comment by kwah8787** [comment]
still broken
revision 2825

**Comment by Gasparunho** [comment]
Still broken as of today 23/03/2019

**Comment by leeviathan** [comment]
still broken rev 2967

**Comment by Evolvee** [comment]
https://github.com/Atlantiss/NetherwingBugtracker/issues/1966

https://github.com/Atlantiss/NetherwingBugtracker/issues/5744

https://github.com/Atlantiss/NetherwingBugtracker/issues/5245

**Comment by Evolvee** [comment]
Todo: the gameobject at the end needs to reset (either loot state change or despawn/respawn or flag 16 removal)...

**Comment by Wolffenstein** [comment]
Fixed in rev 3207.
