### ISSUE TITLE
.save doesn´t work

### ISSUE THREAD

**Issue by Beirut93** [Atlantiss/NetherwingBugtracker#43]
**Description**: 
.save doesn´t work. huge problem on private servers. needs to be adressed ASAP
**Current behaviour**:
.save doesn´t work. huge problem on private servers. needs to be adressed ASAP
**Expected behaviour**: 
.save needs to work otherwise i won´t play here and a lot of my friends will not play either
**Server Revision**:

**Comment by Evolvee** [comment]
everyone is saved automatically if a crash occur, you dont need to save manually yourself
