### ISSUE TITLE
[Quest] Underbelly Scales - 122

### ISSUE THREAD

**Issue by Scylla420** [Atlantiss/NetherwingBugtracker#430]
**Description**: 
The drop rate of Underbelly Whelp Scale (1221) off the npc Black Dragon Whelp (441) felt way too high.
**Current behaviour**:
I received all 6 scales in just 7 kills, deleted them and did it again to double check and got 6 scales in 8 kills.
**Expected behaviour**: 
Drop rate should probably be lower.  No higher than 50% at least judging by various comments post patch 2.3

[wowhead comments](https://www.wowhead.com/quest=122/underbelly-scales)
>I found the drop rate to be totally erratic. When my mage did this quest it took over forty of the them to get the six. A couple of days later I ran my druid through and he got 6 out of 7.I also ran a hunter through and from what I can recall he did at least 20 plus. [2008/01/29 (Patch 2.3.3)]

>I had a horrible drop rate. When I got one in six I felt lucky. Did nearly half a level just getting six scales. [2008/01/26 (Patch 2.3.3)]

>i got mine along the lakeridge highway with about 50% drop rate [2008/06/01 (Patch 2.4.2)}

[Allakhazam comments](https://web.archive.org/web/20080510052810/http://wow.allakhazam.com:80/db/quest.html?wquest=122)

>41 kills 6 scales.. 2 greens [Aug 21st 2007]

>I did this quest very easily as a level 17 rogue. I got a scale about every four drangons I killed. [Aug 26th 2006 9:32pm}

Note that the various allakhazam comments are all from prior to patch 2.3. Wouldn't be surprised if it got buffed a bit but regardless it felt way too high of a drop rate.

**Server Revision**: 
2040

**Comment by aresbrutus** [comment]
Will be fixed in one of the next updates.
