### ISSUE TITLE
[Spell][Warlock](Firestones) don't disapear after logged out for 15min+

### ISSUE THREAD

**Issue by vitor210** [Atlantiss/NetherwingBugtracker#4300]
Tooltip of "Create Firestone" states that the created item disappears after being logged out for more than 15min, just like Healthstones or Soulstones and yet firestones don't disappear. One other difference is that Firestones say who made it (like if it was a crafted item from any profession) like you see here:

https://i.imgur.com/e71QybZ.jpg

But stuff like soulstones or healthstones don't!

https://i.imgur.com/EV5cGTF.jpg

**Comment by Saben65** [comment]
Related: https://github.com/Atlantiss/NetherwingBugtracker/issues/2088

**Comment by devo6969** [comment]
Still an issue, tested in the 2088

**Comment by Godmatik** [comment]
Duplicate
https://github.com/Atlantiss/NetherwingBugtracker/issues/2088
