### ISSUE TITLE
Kil'Sorrow Fortress has terrain issues

### ISSUE THREAD

**Issue by fantom8** [Atlantiss/NetherwingBugtracker#4301]
I'm pretty sure there are mobs or patrols spawning under the ground in Kil'Sorrow Fortress in Nagrand. Either that or the mobs are incorrectly linked with others that are very far away from themselves.

It was hard to pinpoint exactly what the issue is because I couldn't stop, but it's basically a death trap for appropriately leveled characters. Single pulls quickly turn into 5, 6, 7 mobs at a time. And not all from normal patrols. Mobs that should stay still suddenly aggro from well out of range when fighting other mobs in the fortress.

The entrance level is particularly bad about this.

**Comment by The14me** [comment]
The ''issue'' is that most of the mobs blend with the tent's + a lot of paths. So when u pull and think that are 2 mobs...end up with 5.
