### ISSUE TITLE
NPC: Vendor Item missing

### ISSUE THREAD

**Issue by Hellzmatter** [Atlantiss/NetherwingBugtracker#4302]
[//]: # (Enclose links to things related to the bug using http://wowhead.com or any other TBC database.)
[//]: # (You can use screenshot ingame to visual the issue.)
[//]: # (Write your tickets according to the format:)
[//]: # ([Quest][Azuremyst Isle] Red Snapper - Very Tasty!)
[//]: # ([NPC] Magistrix Erona)
[//]: # ([Spell][Mage] Fireball)
[//]: # ([Npc][Drop] Ghostclaw Lynx)
[//]: # ([Web] Armory doesnt work)
[//]: # (To find server revision type `.server info` command in the game chat.)

**Description**: 
Darnassus General Goods vendor Mythrin'dir not selling the recipe "Enchant Shield - Greater Stamina "
**Current behaviour**:
Enchant Shield - Greater Stamina  recipe missing 
**Expected behaviour**: 
Enchant Shield - Greater Staminashould be available for purchase from this vendor
**Server Revision**:

**Comment by Shanghi** [comment]
That's just a world drop. Did you mean Enchant Shield - Greater Stamina? If so, then it's there already but just sold out. It's common to see sold out things as grayed out items on private servers, but you're not supposed to see them at all.

**Comment by Hellzmatter** [comment]
> That's just a world drop. Did you mean Enchant Shield - Greater Stamina? If so, then it's there already but just sold out. It's common to see sold out things as grayed out items on private servers, but you're not supposed to see them at all.

Ahh yes, that's what I meant my bad. 
Oh, I figured it was a bug since the item wasn't even on the list. Thought it would just show as (0) in stock. Thanks!

**Comment by Shanghi** [comment]
I have access to it and saw it. It doesn't have an extremely long restock time, but others probably want it too!

**Comment by Hellzmatter** [comment]
> I have access to it and saw it. It doesn't have an extremely long restock time, but others probably want it too!

Ah okay that's good to hear! Must just be my bad luck then. Thank you :D
