### ISSUE TITLE
[Talent][Rogue] Improved Sprint doesn't remove impairings

### ISSUE THREAD

**Issue by dmrljes** [Atlantiss/NetherwingBugtracker#4304]
I got 2/2 on Improved Sprint and whenever I use the sprint, it never removes impairings.

**Comment by Wolffenstein** [comment]
Which movement impairing effect exactly did you test it on?

**Comment by dmrljes** [comment]
Not sure of the names of impairings, but I will test it and see their names later, but mobs were in Shimmering flats, Thousand Needless (basilisks) and Stranglethorn Vale(panthers).

**Comment by Manaci** [comment]
Dead issue
