### ISSUE TITLE
Guild tabard not showing on login screen

### ISSUE THREAD

**Issue by alextmofo** [Atlantiss/NetherwingBugtracker#4306]
**Description**: Guild tabard not showing on login screen

**Expected behaviour**: It should show

**Comment by shanold** [comment]
![wowscrnshot_022219_154738](https://user-images.githubusercontent.com/47759324/53270267-41111900-36b9-11e9-9074-50ffc868fdb4.jpg)
Guild tabard shows as a blank white one on the character select screen.

Server revision : 2825

**Comment by teddys** [comment]
feelsbadman

**Comment by Tereneckla** [comment]
Fixed
