### ISSUE TITLE
Cannot ressurect if you died in a dungeon and group disbanded

### ISSUE THREAD

**Issue by ibogdandx** [Atlantiss/NetherwingBugtracker#4307]
**Description**: 
You cannot ressurect if you died in a dungeon and group disbanded. You need to take Spirit Healer ressurect cause if you enter the dungeon portal nothing happens. Happened twice today.

**Current behaviour**:

**Expected behaviour**: 
If you run into the dungeon you should ressurect !
**Server Revision**:

**Comment by Wolffenstein** [comment]
Fixed in rev 2654.
