### ISSUE TITLE
[NPC] Blackrock Depths Magmus - Flame Statues.

### ISSUE THREAD

**Issue by Mysstt** [Atlantiss/NetherwingBugtracker#4308]
[//]: # (Enclose links to things related to the bug using http://wowhead.com or any other TBC database.)
[//]: # (You can use screenshot ingame to visual the issue.)
[//]: # (Write your tickets according to the format:)
[//]: # ([Quest][Azuremyst Isle] Red Snapper - Very Tasty!)
[//]: # ([NPC] Magistrix Erona)
[//]: # ([Spell][Mage] Fireball)
[//]: # ([Npc][Drop] Ghostclaw Lynx)
[//]: # ([Web] Armory doesnt work)
[//]: # (To find server revision type `.server info` command in the game chat.)

**Description**: Flame Statues lock you in combat after killing Magmus in Blackrock Depths (BRD).

**Current behaviour**: After killing Magmus, 2nd last boss in BRD, the flames from the statues are not extinguished and keep you locked in combat.

**Expected behaviour**: When Magmus dies, the flame statues should cease, and not lock you into combat.

**Server Revision**: 2646

**Comment by Evolvee** [comment]
any proof they should stop spewing fire? its scripted intentionally to let them spew it after magmus is dead

**Comment by Haipethdev** [comment]
Sorry for the duplicate, missed this with my search some how.  Surely combat should drop regardless of the statues continuing to spew?

**Comment by danbopes** [comment]
@Evolvee Regardless if they should continue spewing or not: Combat should drop after getting out of range. Even 100 yards away, these guys still try to target, keeping players in combat.

**Comment by danbopes** [comment]
Statues:
![](https://i.imgur.com/dqA9PYH.png)

**Comment by Evolvee** [comment]
fixed in rev 3121
