### ISSUE TITLE
[NPC][AI] Unyielding Footman

### ISSUE THREAD

**Issue by syphex97** [Atlantiss/NetherwingBugtracker#4309]
[//]: # (Enclose links to things related to the bug using http://wowhead.com or any other TBC database.)
[//]: # (You can use screenshot ingame to visual the issue.)
[//]: # (Write your tickets according to the format:)
[//]: # ([Quest][Azuremyst Isle] Red Snapper - Very Tasty!)
[//]: # ([NPC] Magistrix Erona)
[//]: # ([Spell][Mage] Fireball)
[//]: # ([Npc][Drop] Ghostclaw Lynx)
[//]: # ([Web] Armory doesnt work)
[//]: # (To find server revision type `.server info` command in the game chat.)

**Description**: 
The Npc apparently uses shield bash on a caster that is standing right next to the npc if you cast.

He doesnt turn around or puts his global attacks on cooldown but instead just interrupts and continue as if he was just attacking the target with aggro.

See video for results.

https://www.youtube.com/watch?v=_8Y7gEx2PM4

**Server Revision**: 
2646

**Comment by Wolffenstein** [comment]
That is intended.
