### ISSUE TITLE
[quest][eversong woods] Agression

### ISSUE THREAD

**Issue by knasen88** [Atlantiss/NetherwingBugtracker#431]
[//]: # (Enclose links to things related to the bug using http://wowhead.com or any other TBC database.)
[//]: # (You can use screenshot ingame to visual the issue.)
[//]: # (Write your tickets according to the format:)
[//]: # ([Quest][Azuremyst Isle] Red Snapper - Very Tasty!)
[//]: # ([NPC] Magistrix Erona)
[//]: # ([Spell][Mage] Fireball)
[//]: # ([Npc][Drop] Ghostclaw Lynx)
[//]: # ([Web] Armory doesnt work)

**Description**: 
I remember this being the only chokepoint of the belf 1-6 area (mainly too few Feral tenders spawning)
**Current behaviour**:

**Expected behaviour**: 

**Server Revision**:

**Comment by aresbrutus** [comment]
You are correct. They were missing from the dynamic respawn system but they hae been added now, thanks for reporting.
