### ISSUE TITLE
[Dungeon] Dire Maul North has far to few mobs in the courtyard

### ISSUE THREAD

**Issue by Derpyous** [Atlantiss/NetherwingBugtracker#4311]
**Description**: 
The courtyard in Dire Maul North has way to few mobs in it. For example, there's supposed to be 27 dogs in the courtyard. Currently there's 7.

**Current behaviour**:
There's only 7 dogs where there should be 27.
https://gyazo.com/3c04a9c3b7ec1d23b62dd693b3abd0c1
https://gyazo.com/f42a5f638b72b233fc1e0d7dd875d19e

**Expected behaviour**: 
There's supposed to be 27 dogs in the courtyard. The instance haven't changed ever.

https://www.youtube.com/watch?v=jDtssm6vAdE - TBC 
https://www.youtube.com/watch?v=-BzgCKdB1ag - Vanilla

**Server Revision**: 
2649

**Comment by Tenoutoften** [comment]
https://github.com/Atlantiss/NetherwingBugtracker/issues/1234

**Comment by Evolvee** [comment]
rev 2716
