### ISSUE TITLE
[Spell][Mage][Invisibility] Invisibility doesn't make you leave combat.

### ISSUE THREAD

**Issue by killablink** [Atlantiss/NetherwingBugtracker#4314]
**Description**: If you use invis while mobs are chasing you, some mobs will still stay in combat with you and hit you through invis while they can't even see you.

**Current behaviour**: If you use invis while mobs are chasing you, some mobs will still stay in combat with you and hit you through invis while they can't even see you.

**Expected behaviour**: Mobs that can't see invis shouldn't be able to hit you out of invis

**Server Revision**: 2646

**Comment by Wolffenstein** [comment]
Please retest in rev 2651.
