### ISSUE TITLE
maraudon combat bug, also breathing visual bug outside instance

### ISSUE THREAD

**Issue by staplerx300** [Atlantiss/NetherwingBugtracker#4317]
[//]: # (Enclose links to things related to the bug using http://wowhead.com or any other TBC database.)
[//]: # (You can use screenshot ingame to visual the issue.)
[//]: # (Write your tickets according to the format:)
[//]: # ([Quest][Azuremyst Isle] Red Snapper - Very Tasty!)
[//]: # ([NPC] Magistrix Erona)
[//]: # ([Spell][Mage] Fireball)
[//]: # ([Npc][Drop] Ghostclaw Lynx)
[//]: # ([Web] Armory doesnt work)
[//]: # (To find server revision type `.server info` command in the game chat.)

**Description**: 

**Current behaviour**:
the fumes from orange side mara near noxxion puts you in combat, and then you can't get out of it unless you alt-f4

also outside the instance where you fill the cerulean vile for one of the quests when you go into the pool you get a visual that your breath is running out even if you return to dry land

**Expected behaviour**: 
neither of those should happen
**Server Revision**: 
cant get in because no grace period for log out, put in queue, so dunno

**Comment by Godmatik** [comment]
Rev 4016 - Unable to reproduce either issue.
Breath bar returns to normal when getting on dry land
The fumes "Spore Cloud" do not even put you in combat in the first place.
