### ISSUE TITLE
[Quest]Rescue OOX-22/FE!  Ending to early

### ISSUE THREAD

**Issue by Jalapan** [Atlantiss/NetherwingBugtracker#4318]
[//]: # (Enclose links to things related to the bug using http://wowhead.com or any other TBC database.)
[//]: # (You can use screenshot ingame to visual the issue.)
[//]: # (Write your tickets according to the format:)
[//]: # ([Quest][Azuremyst Isle] Red Snapper - Very Tasty!)
[//]: # ([NPC] Magistrix Erona)
[//]: # ([Spell][Mage] Fireball)
[//]: # ([Npc][Drop] Ghostclaw Lynx)
[//]: # ([Web] Armory doesnt work)
[//]: # (To find server revision type `.server info` command in the game chat.)

**Description**: 
Escort OOX-22/FE ending/completes prematurly on road just outside yeti cave
**Current behaviour**:
You get completed before reaching intended destination
**Expected behaviour**: 
QUEST SHOULD BE COMPLETED DOWN AT THE COAST AND NOT JUST OUTSIDE YETI CAVE
**Server Revision**:

**Comment by Sabre142** [comment]
Source?

**Comment by staplerx300** [comment]
at the moment you have to let the chicken aggro everything first

if you do that you get credit, if not then sometimes not

**Comment by Jalapan** [comment]
Source : https://www.wowhead.com/quest=2767/rescue-oox-22-fe#comments


Also did the quest yesterday. Can confirm quest get completed just outside yeti cave by the road. Multiple people reported it in the chat aswell

**Comment by Tenoutoften** [comment]
Known issue, it's scripted for a later version... low priority https://github.com/Atlantiss/NetherwingBugtracker/issues/3678
