### ISSUE TITLE
Judgement of Wisdom 

### ISSUE THREAD

**Issue by Canedrac** [Atlantiss/NetherwingBugtracker#4319]
[//]: # (Enclose links to things related to the bug using http://wowhead.com or any other TBC database.)
[//]: # (You can use screenshot ingame to visual the issue.)
[//]: # (Write your tickets according to the format:)
[//]: # ([Quest][Azuremyst Isle] Red Snapper - Very Tasty!)
[//]: # ([NPC] Magistrix Erona)
[//]: # ([Spell][Mage] Fireball)
[//]: # ([Npc][Drop] Ghostclaw Lynx)
[//]: # ([Web] Armory doesnt work)
[//]: # (To find server revision type `.server info` command in the game chat.)

**Description**: 
Judgement of Wisdom does not proc to return mana back to attacker.
**Current behaviour**:
Apply Judgement of Wisdom, over 70 attacks not one proc received for mana. 
**Expected behaviour**: 
Judgement of Wisdom to have similar interactions as Judgement of Light
**Server Revision**:

**Comment by Tenoutoften** [comment]
? It works
![](https://i.gyazo.com/e246ba84f9f51b80dd572299a402f73e.png)

**Comment by Canedrac** [comment]
have you tried with lower rank of it?

**Comment by Tenoutoften** [comment]
No only max rank

**Comment by shanold** [comment]
my max rank is rank 1 and i'm having the same issue it doesn't proc
