### ISSUE TITLE
[Quest Reward][Durotar, Sen'jin Village] Minshina's Skull 

### ISSUE THREAD

**Issue by twobite** [Atlantiss/NetherwingBugtracker#432]
Description: The quest reward has improper life steal values

https://classicdb.ch/?item=4945 the item in question

Current Behavior: When used it did damage within its proper values but did not steal the correct amount of life, here is a picture of my combat log when it happened. You can see it did 91 damage but only stole 7 life from the target

https://i.imgur.com/7qHsAZs.jpg

Expected behaviour: This may be a bit of an anecdotal statement but everytime I've used this on private servers and retail included it would give you the same amount of life leeched as the damage that it did, so I should have got 91 life instead of 7.

Server Revision: Make the life steal value a 1:1 with the damage.

**Comment by Easyfraggy** [comment]
https://github.com/Atlantiss/NetherwingBugtracker/issues/227

Can you share some more info on how this happened?

What mobs were you fighting and how much HP were you missing (aprox) etc.

**Comment by twobite** [comment]
https://i.imgur.com/QPpPasu.jpg

You can see the mob I was fighting in my combat log, here's the whole screenshot showing I was low HP while fighting the mob.

**Comment by twobite** [comment]
Only thing I can think of, which in this case can't be true because the mob had 50 hp, is that for some reason the item will not give 1:1 leech if the mob is low hp. So say the mob had 7 hp left and you use the item, it'll do the overkill damage but wont have 91 life to leech so it will just give you what it has left.

But again, I can't see this being possible in my situation as the mob had well over 7 hp when this occured, can't really put anything else on that other than my word. I wasn't recording when this happened unfortunately

**Comment by Easyfraggy** [comment]
Thanks twobite, I'll try to recreate it if I can.

**Comment by Easyfraggy** [comment]
Still can't recreate this issue. Need recreation steps.

**Comment by wtRCH** [comment]
Works ok. but there isn't 100% bonus spell damage coefficient on the item. With 840 bonus spell damage this item only stole 278 life from the enemy.


> By Diivil on 05/09/2007 (Patch 2.0.12)
> Best thing on this item is that it takes full bonus from spell dmg gear. So if you haven't done to quest and want a trump card for a fight you really want to win, go get it. Just remember that this is 1 time use only so don't waste it :]

**Comment by wtRCH** [comment]
@pelekon
