### ISSUE TITLE
[Spell][Priest] Shadow Word: Death and Vampiric Touch/Embrace interaction

### ISSUE THREAD

**Issue by impersonal66** [Atlantiss/NetherwingBugtracker#4320]
**Description**: 
Shadow Word: Death and Vampiric Touch/Embrace interation when SW:P kills the target
**Current behaviour**:
SW:P damage doesn't regen mana/health from VT/VE when it kills the target. However it regens mana/health when it doesn't kill the target (i.e. goes with backfire). 
Some proofs from combat log, that it doesn't regen anything upon killing the target.
![vp1](https://user-images.githubusercontent.com/46806189/51374248-63a19680-1b3d-11e9-83e4-e3816126dbb2.jpg)
![vp2](https://user-images.githubusercontent.com/46806189/51374253-68664a80-1b3d-11e9-8d25-ab69328e44ea.jpg)
![vp3](https://user-images.githubusercontent.com/46806189/51374254-6bf9d180-1b3d-11e9-80da-658e747f056c.jpg)
**Expected behaviour**: 
SW:P damage must regen mana/health from VT/VE always.
**Server Revision**: 
2647

**Comment by Godmatik** [comment]
Must have been fixed at some point.

If SW:D kills an enemy, it restores health/mana for me just fine with VT and VE.

Closing.
