### ISSUE TITLE
Slow Fall cannot be cast on others

### ISSUE THREAD

**Issue by Nicemann1089** [Atlantiss/NetherwingBugtracker#4322]
[//]: # (Enclose links to things related to the bug using http://wowhead.com or any other TBC database.)
[//]: # (You can use screenshot ingame to visual the issue.)
[//]: # (Write your tickets according to the format:)
[//]: # ([Quest][Azuremyst Isle] Red Snapper - Very Tasty!)
[//]: # ([NPC] Magistrix Erona)
[//]: # ([Spell][Mage] Fireball)
[//]: # ([Npc][Drop] Ghostclaw Lynx)
[//]: # ([Web] Armory doesnt work)
[//]: # (To find server revision type `.server info` command in the game chat.)

**Description**: 

**Current behaviour**: Slow Fall cannot be cast on others.

**Expected behaviour**: Slow Fall should be castable on others.

**Server Revision**: 2647

**Comment by Shanghi** [comment]
That happens in WotLK. From the 3.0.8 patch notes:
> -  Slow Fall is now castable on others.
