### ISSUE TITLE
Eyes of the Beast: Broken [VISUALS]

### ISSUE THREAD

**Issue by Hyesunee** [Atlantiss/NetherwingBugtracker#4324]
**Description**: 
Eyes of the Beast is currently close to useless!

**Current behaviour**:
'Stay' doesn't work during Eyes of the Beast, and 'Fall Damage' hurts your character when you jump down with 'Eyes of the Beast' and then cancel the effect.

**Expected behaviour**: 
You SHOULD BE able to put your pet on STAY during Eyes of the Beast, and your character OFCOURSE shouldn't take falling damage when you jump with your pet, I'll visualize it for you of how stupid the ability currently is.

**Server Revision**: 
2647.

PROOF / VISUAL:
https://gyazo.com/c3a5763ef6371b26335a178a3f4b6555
https://gyazo.com/ae324a4c168963af9bc0eea9b037c87f 

Lots of 'minor' pet bugs around, more to be reported probably, sadly I wasn't around at Beta, little things like these truely separate great hunters from mediocre hunters in endgame content so I hope they get fixed, thanks for reading (also some actual Hunter bugs to be reported soon).

**Comment by The14me** [comment]
Rev.3483 Fall dmg is fixed, but ''stay'' is still bugged. At the moment u remove  Eyes of the Beast the pet bar from Stay change to Follow.

**Comment by Godmatik** [comment]
Tested stay when using eyes of the beast, and it is working.

Closing.
