### ISSUE TITLE
[NPC] Deathforge tinkerer

### ISSUE THREAD

**Issue by Dekirayne** [Atlantiss/NetherwingBugtracker#4325]
**Description**: 
Deathforge tinkerers have too much dmg
**Current behaviour**:
Should they hit me for 1.5k dmg each hit
**Expected behaviour**: 
Should not be that hard i guess
**Server Revision**: 
![image](https://user-images.githubusercontent.com/12075744/51398325-9f3f5f00-1b43-11e9-96cd-f1c0cabc4d84.png)

**Comment by zauru7** [comment]
So what's the correct damage @Dekirayne ?

**Comment by Dekirayne** [comment]
> So what's the correct damage @Dekirayne ?

i don't know but every hit 1500 from normal mob doesn't seem right.

**Comment by Evolvee** [comment]
![image](https://user-images.githubusercontent.com/1942409/51427071-6232a580-1bf3-11e9-9e31-a237ebb2dcc6.png)

they do normal dmg to me

**Comment by Evolvee** [comment]
werent you affected by some debuff?
