### ISSUE TITLE
[Hunter][Spell] Kill command crits don't trigger on crit effects

### ISSUE THREAD

**Issue by Zarant** [Atlantiss/NetherwingBugtracker#4327]
Description: Kill command crits don't trigger on crit effects

Current behaviour: Kill command crits don't proc frenzy and ferocious inspiration

Expected behaviour: Kill command crits should proc frenzy and ferocious inspiration

Source: https://web.archive.org/web/20081004051530/http://elitistjerks.com:80/f31/t9816-hunter_spreadsheets_--_development/

Taken directily from Cheeky's spreadsheet from retail tbc, you can look at the frenzy uptime calculations, it takes kill command into account, which means that kill command crits should proc on crit effects from your pet like frenzy and ferocious inspiration.

Server Revision: Revision: 2647

**Comment by DragunovUA** [comment]
up

**Comment by DragunovUA** [comment]
up

**Comment by Godmatik** [comment]
![qqwqzzz](https://github.com/user-attachments/assets/7cde431d-92f5-49cb-9e0d-0affc159443c)

Works just fine ...
