### ISSUE TITLE
[quest][hillsbrad] souvenirs of death. too high lvl required

### ISSUE THREAD

**Issue by knasen88** [Atlantiss/NetherwingBugtracker#433]
[//]: # (Enclose links to things related to the bug using http://wowhead.com or any other TBC database.)
[//]: # (You can use screenshot ingame to visual the issue.)
[//]: # (Write your tickets according to the format:)
[//]: # ([Quest][Azuremyst Isle] Red Snapper - Very Tasty!)
[//]: # ([NPC] Magistrix Erona)
[//]: # ([Spell][Mage] Fireball)
[//]: # ([Npc][Drop] Ghostclaw Lynx)
[//]: # ([Web] Armory doesnt work)

**Description**: 
Should be able to take it at lvl 20. 
**Current behaviour**:
 able to take when i achieved 24
**Expected behaviour**: 
https://i.imgur.com/LI92cyA.png
**Server Revision**:

**Comment by Wolffenstein** [comment]
It's already available at level 20, but you need to complete Battle of Hillsbrad before you can take it.
