### ISSUE TITLE
[Quest][Karazhan] The Master's Terrace

### ISSUE THREAD

**Issue by Ensipidx** [Atlantiss/NetherwingBugtracker#4330]
**Description**: Quest doesn't work. Blocking the ability to summon nightbane behind this quest. Very important for T4+ onwards.

**Current behaviour**: Medivh is summoned and does some RP but doesn't complete the quest objective.

**Expected behaviour**: Quest should be complete able.

**Server Revision**: 2647

**Comment by killablink** [comment]
+, has to be fixed ASAP

**Comment by Tenoutoften** [comment]
I added this to my other issue about quests in critical condition a few days ago
https://github.com/Atlantiss/NetherwingBugtracker/issues/4207

**Comment by Wolffenstein** [comment]
The stock rp script is complete garbage (and most likely crashes the server) so I disabled it for now. I will script it later but to let you progress, using the item will grant you (and nearby party members) quest credit after revision 2660.

**Comment by Evolvee** [comment]
rev 2714
