### ISSUE TITLE
[Crashlike - Priority][Item] Items disappearing from guild bank/bank/inventory 

### ISSUE THREAD

**Issue by Haipethdev** [Atlantiss/NetherwingBugtracker#4331]
[//]: # (Enclose links to things related to the bug using http://wowhead.com or any other TBC database.)
[//]: # (You can use screenshot ingame to visual the issue.)
[//]: # (Write your tickets according to the format:)
[//]: # ([Quest][Azuremyst Isle] Red Snapper - Very Tasty!)
[//]: # ([NPC] Magistrix Erona)
[//]: # ([Spell][Mage] Fireball)
[//]: # ([Npc][Drop] Ghostclaw Lynx)
[//]: # ([Web] Armory doesnt work)
[//]: # (To find server revision type `.server info` command in the game chat.)

**Description**: 

Tailoring cooldown cloths (Primal Mooncloth, Shadowcloth, Spellcloth) disappearing on two seperate occasions after server crashes.  6 Mooncloth and 8 shadowcloth after the first crash.  9 Spell cloth after the 2nd.

Currently observed within a guild bank, 2nd tab, in which 6 Mooncloth and 8 Shadowcloth went missing with only 7 people (GM and officer rank) having permissions to remove items from tab 2.  Upon being requested to lock down the guild bank permissions and leave everything untouched, 9 spellcloth that were left in the guild bank for that purpose also disappeared upon a server crash during yesterday night.  

Only myself had permissions to remove the 9 spellcloth from <Memory> guild bank tab 2 the evening they disappeared, upon GM request.  Other expensive items in the guild bank, such as primal mights, are unaffected.

Notes:

- Cooldown crafted item related?
- Unlike the mights in the same guild bank tab, cloths were stacked from different crafters and deposited by 3 separate players independently to the guild bank.  Issue with items from different crafters stacking?
- Broken guild permissions similar to guild rank names being broken after crashes?  Allowing members who should not have permission, withdrawing items?
- Guild bank log completely wiped, presumably also because of the crash.
- Is this related to rollbacks also seen during server crashes?

**Current behaviour**:

**Expected behaviour**: 

**Server Revision**: 2647 unless this has updated since yesterday evening.

**Comment by Haipethdev** [comment]
It is worth reiterating that this isn't a simple last-second-before crash rollback problem.  There were several several hours between the first and second incident in which the guild bank was completely closed down and nothing went in or out.  I honestly suspect it isn't just a problem with the guild bank, but rather the stacking of items from different characters/sources.

**Comment by Haipethdev** [comment]
Removed what valuable items were left from tab 2 in case they also disappear.

**Comment by Wolffenstein** [comment]
We intend to rewrite the whole guild system sometime soon, but until then those items seem to be at risk in the guild bank.

**Comment by Tenoutoften** [comment]
We've lost items worth around 3000g due to this

**Comment by Wolffenstein** [comment]
Duplicate.
