### ISSUE TITLE
[Quest] The Eyes of Grillok

### ISSUE THREAD

**Issue by RealZwox** [Atlantiss/NetherwingBugtracker#4332]
Sometimes the Eye Buff fades rnd from you when you leave Zethgor. Happen to me the first time and a mate needed 4 trys.

**Expected behaviour**: 

Should not rnd fade from the Player

**Server Revision**: 
2647

**Comment by Godmatik** [comment]
Confirmed - it happens whenever you get into combat with the eye debuff. Only way to avoid losing it is to not get into combat when heading back to the cauldron.

**Comment by duzyizly** [comment]
Done this quest with 3 characters around rev 3367. I did not lost a buff a single time. Probably fixed long time ago.
