### ISSUE TITLE
[Dungeon] [Steamvaults] Mobs gets stuck and can't be pulled

### ISSUE THREAD

**Issue by Johra92** [Atlantiss/NetherwingBugtracker#4333]
[//]: # (Enclose links to things related to the bug using http://wowhead.com or any other TBC database.)
[//]: # (You can use screenshot ingame to visual the issue.)
[//]: # (Write your tickets according to the format:)
[//]: # ([Quest][Azuremyst Isle] Red Snapper - Very Tasty!)
[//]: # ([NPC] Magistrix Erona)
[//]: # ([Spell][Mage] Fireball)
[//]: # ([Npc][Drop] Ghostclaw Lynx)
[//]: # ([Web] Armory doesnt work)
[//]: # (To find server revision type `.server info` command in the game chat.)

**Description**: 
The issue is that one of the mobs in the pack outside the entrance of the big door, leading up the room inbetween second and third boss, has a mob getting stuck when being pulled. It's  the coilfang engineer, that sits behind the pillar without going with the rest of the pack. Leading him to chain pull other mobs that patrol the area, making the encounter much harder than it is supposed to be. I'm uploading a screenshot, where I am looking straight at the pillar, where the mob pack in question stands (on the opposite side of where I am currently standing. 
![skarmklipp 2019-01-19 01 31 12](https://user-images.githubusercontent.com/45569791/51419338-f2d49b80-1b89-11e9-8139-d40857209103.png)

**Current behaviour**:
he issue is that one of the mobs in the pack outside the entrance of the big door, leading up the room inbetween second and third boss, has a mob getting stuck when being pulled. It's  the coilfang engineer, that sits behind the pillar without going with the rest of the pack. Leading him to chain pull other mobs that patrol the area, making the encounter much harder than it is supposed to be.
**Expected behaviour**: 
All the mobs in the pack comes when u pull them. 
**Server Revision**: 
2647

**Comment by Godmatik** [comment]
Already fixed, can close
