### ISSUE TITLE
bugged hitbox on fleeing mobs with low hp

### ISSUE THREAD

**Issue by numiee** [Atlantiss/NetherwingBugtracker#4336]
[//]: # (Enclose links to things related to the bug using http://wowhead.com or any other TBC database.)
[//]: # (You can use screenshot ingame to visual the issue.)
[//]: # (Write your tickets according to the format:)
[//]: # ([Quest][Azuremyst Isle] Red Snapper - Very Tasty!)
[//]: # ([NPC] Magistrix Erona)
[//]: # ([Spell][Mage] Fireball)
[//]: # ([Npc][Drop] Ghostclaw Lynx)
[//]: # ([Web] Armory doesnt work)
[//]: # (To find server revision type `.server info` command in the game chat.)

**Description**: 
hitbox bug when mobs flee away with low hp, the model turns around but the hitbox does not.

**Current behaviour**:
when mobs flee with low hp, the model turns around but the hitbox does not, for example when you try backstabbing the mob, you have to be infront of the fleeing target instead of behind.

**Expected behaviour**: 
The hitbox should follow with the model.

**Server Revision**: 
2647

**Comment by numiee** [comment]
Are we getting any updates on this issue?

**Comment by The14me** [comment]
Rev.3483 still an issue.

**Comment by Easyfraggy** [comment]
Can confirm

**Comment by Massie323** [comment]
Rev.3730 still an issue, impossible to backstab fleeing mobs due to still facing the player while running away.

https://user-images.githubusercontent.com/57675820/229777460-c6bfd3a7-f1d1-4c2a-b07e-94b5de60e39a.mp4

**Comment by Godmatik** [comment]
Duplicate https://github.com/Atlantiss/NetherwingBugtracker/issues/1565
