### ISSUE TITLE
[NPC] Deathclaw (17661)

### ISSUE THREAD

**Issue by Sinyr** [Atlantiss/NetherwingBugtracker#434]
[//]: # (Enclose links to things related to the bug using http://wowhead.com or any other TBC database.)
[//]: # (You can use screenshot ingame to visual the issue.)
[//]: # (Write your tickets according to the format:)
[//]: # ([Quest][Azuremyst Isle] Red Snapper - Very Tasty!)
[//]: # ([NPC] Magistrix Erona)
[//]: # ([Spell][Mage] Fireball)
[//]: # ([Npc][Drop] Ghostclaw Lynx)
[//]: # ([Web] Armory doesnt work)

**Description**: 
Wrong mouseover tooltip.

**Current behaviour**:
Mouseover tooltip on Deathclaw (17661) says he's Skinnable while he's alive. I don't even have skinning.

![screenshot_1](https://user-images.githubusercontent.com/9539181/45982005-4eb56a80-c057-11e8-81ae-8aee76c40c45.png)

**Expected behaviour**: 
Tooltip shouldn't say "Skinnable" when monsters are alive

**Server Revision**: 
2040

**Comment by Wolffenstein** [comment]
Fixed in rev 2047.
