### ISSUE TITLE
Demon trainer in Silvermoon City does not sell Torment Rank 1 for voidwalker

### ISSUE THREAD

**Issue by Cheesedip** [Atlantiss/NetherwingBugtracker#4344]
[//]: # (Enclose links to things related to the bug using http://wowhead.com or any other TBC database.)
[//]: # (You can use screenshot ingame to visual the issue.)
[//]: # (Write your tickets according to the format:)
[//]: # ([Quest][Azuremyst Isle] Red Snapper - Very Tasty!)
[//]: # ([NPC] Magistrix Erona)
[//]: # ([Spell][Mage] Fireball)
[//]: # ([Npc][Drop] Ghostclaw Lynx)
[//]: # ([Web] Armory doesnt work)
[//]: # (To find server revision type `.server info` command in the game chat.)

**Description**: 
See title
**Current behaviour**:
Doesnt sell rank 1, does sell all other ranks
**Expected behaviour**: 
Demon trainer should sell rank 1 Torment for voidwalker
**Server Revision**:

**Comment by Evolvee** [comment]
such book doesnt exist
