### ISSUE TITLE
[NPC][Spell] Silithid Pox damage increase too high

### ISSUE THREAD

**Issue by Dadeerh** [Atlantiss/NetherwingBugtracker#4346]
[//]: # (Enclose links to things related to the bug using http://wowhead.com or any other TBC database.)
[//]: # (You can use screenshot ingame to visual the issue.)
[//]: # (Write your tickets according to the format:)
[//]: # ([Quest][Azuremyst Isle] Red Snapper - Very Tasty!)
[//]: # ([NPC] Magistrix Erona)
[//]: # ([Spell][Mage] Fireball)
[//]: # ([Npc][Drop] Ghostclaw Lynx)
[//]: # ([Web] Armory doesnt work)
[//]: # (To find server revision type `.server info` command in the game chat.)

**Description**: 
In south Ungoro the silithid aliens cast a disease called Silithid Pox that increases physical damage taken. This percentage is way too high as to what it should be.
It is cast by:
Gorishi Reaver,Gorishi Stinger,Gorishi Tunneler,Gorishi Wasp,Gorishi Worker  according to https://classic.wowhead.com/spell=8137/silithid-pox
Silithid Invader according to https://vanilla-twinhead.twinstar.cz/?spell=8137

**Current behaviour**:
Silithid Pox is 42% increased physical damage for 30 minutes
![billede](https://user-images.githubusercontent.com/21084363/51425404-17596380-1bdc-11e9-8877-0e42dcdbc17c.png)

**Expected behaviour**: 
Silithid Pox should be 10% increased physical damage for 30 minutes. 

https://vanilla-twinhead.twinstar.cz/?spell=8137
https://classic.wowhead.com/spell=8137/silithid-pox

**Server Revision**: 
Server Revision: 2647 [Branch: master, Hash: 809bd9c405af]

**Comment by Evolvee** [comment]
it scales with level 
![image](https://user-images.githubusercontent.com/1942409/51426987-20edc600-1bf2-11e9-95e3-62f349d0074d.png)
