### ISSUE TITLE
[Quest] [Netherstorm] Creatures of the Eco-Domes

### ISSUE THREAD

**Issue by Johra92** [Atlantiss/NetherwingBugtracker#4348]
[//]: # (Enclose links to things related to the bug using http://wowhead.com or any other TBC database.)
[//]: # (You can use screenshot ingame to visual the issue.)
[//]: # (Write your tickets according to the format:)
[//]: # ([Quest][Azuremyst Isle] Red Snapper - Very Tasty!)
[//]: # ([NPC] Magistrix Erona)
[//]: # ([Spell][Mage] Fireball)
[//]: # ([Npc][Drop] Ghostclaw Lynx)
[//]: # ([Web] Armory doesnt work)
[//]: # (To find server revision type `.server info` command in the game chat.)

**Description**: 
After someone does this quest, by using the item and tagging the Talkbuks, they will stay tagged and can't be done by anyone else. 
**Current behaviour**:
After someone does this quest, by using the item and tagging the Talkbuks, they will stay tagged and can't be done by anyone else. 
**Expected behaviour**: 
They would reset, respawn, allowing other people to do the quest. 
**Server Revision**: 
2647

**Comment by Tenoutoften** [comment]
Already reported here: https://github.com/Atlantiss/NetherwingBugtracker/issues/2666

**Comment by AWIDIUS** [comment]
Still not working

**Comment by Manaci** [comment]
Fixed
