### ISSUE TITLE
[Spell][Hunter] Bestial Wrath

### ISSUE THREAD

**Issue by Shinigamie** [Atlantiss/NetherwingBugtracker#4349]
//]: # ([Spell][Hunter] Bestial Wrath
Sry for english, but after i activate Bestial Wrath my pet do at the first times more dmg but after
my pet crits the dmg reduce and do only normal hits. I try it mutch times after every crit the dmg reduce to normal.  

PLS Help :D

**Comment by The14me** [comment]
Rev.3483 not an issue anymore. With Bestial Wrath, after crit, the dmg is still +50% as tooltip says.
