### ISSUE TITLE
[Instance] Reset instance while corpse running back does not revive your character once entered

### ISSUE THREAD

**Issue by Rxrlol** [Atlantiss/NetherwingBugtracker#4350]
**Description**: 
I died inside an instance (LBRS) and reset the instance while corpse running back.
Once I entered the instance to retrieve my corpse I was still dead and unable to revive my corpse and had to run back to spirit ress

**Current behaviour**:
Resetting an instance while running back inside does not revive your character.

**Expected behaviour**: 
You should be able to enter the instance alive when a dungeon has been reset while corpse running back inside.

**Server Revision**: 
2647

**Comment by Wolffenstein** [comment]
It will be fixed after next update.
