### ISSUE TITLE
Gnome casting animation

### ISSUE THREAD

**Issue by Bakster15** [Atlantiss/NetherwingBugtracker#4353]
[//]: # (Enclose links to things related to the bug using http://wowhead.com or any other TBC database.)
[//]: # (You can use screenshot ingame to visual the issue.)
[//]: # (Write your tickets according to the format:)
[//]: # ([Quest][Azuremyst Isle] Red Snapper - Very Tasty!)
[//]: # ([NPC] Magistrix Erona)
[//]: # ([Spell][Mage] Fireball)
[//]: # ([Npc][Drop] Ghostclaw Lynx)
[//]: # ([Web] Armory doesnt work)
[//]: # (To find server revision type `.server info` command in the game chat.)

**Description**: 
When you cast Fireball/Frostbolt as a male gnome the projectile fires from Wrong(left) hand some times.
He throws out his right hand and the fireball/frostbolt exits from his left hand.
![gnome wrong hand casting](https://user-images.githubusercontent.com/45540647/51426969-dff5b180-1bf1-11e9-93d6-d099449d4479.png)

**Current behaviour**:
75% of the time the spell projectiles exit correctly from the right. But some times they somehow exit from the left hand, that's behind the gnomes back.
**Expected behaviour**: 
All frostbolts/fireballs projectiles should exit from the same side every time. (The right side)
![mage correct animation](https://user-images.githubusercontent.com/45540647/51429005-6cac6980-1c0a-11e9-891d-e42673a69c2c.jpg)
**Server Revision**: 
2647

**Comment by Zarant** [comment]
This feels like a client side issue.
