### ISSUE TITLE
Can't get ressed if released spirit

### ISSUE THREAD

**Issue by Erodraeda** [Atlantiss/NetherwingBugtracker#4354]
[//]: # (Enclose links to things related to the bug using http://wowhead.com or any other TBC database.)
[//]: # (You can use screenshot ingame to visual the issue.)
[//]: # (Write your tickets according to the format:)
[//]: # ([Quest][Azuremyst Isle] Red Snapper - Very Tasty!)
[//]: # ([NPC] Magistrix Erona)
[//]: # ([Spell][Mage] Fireball)
[//]: # ([Npc][Drop] Ghostclaw Lynx)
[//]: # ([Web] Armory doesnt work)
[//]: # (To find server revision type `.server info` command in the game chat.)

**Description**: 
While doing Sunken Temple, our tank died, but we finished the pack. He had released the spirit, thinking we would wipe. Our healer ressed him, but he didn't receive it. We tried many times, relogging etc. It happened again (on the other way around) later on.
**Current behaviour**:
If you release spirit, you can't be ressed from inside the instance.
**Expected behaviour**: 
You should be able to receive resses, even if you had released your spirit.
**Server Revision**: 2647

**Comment by MrOrgmo** [comment]
+1 happened to us in RFD as well

**Comment by Manaci** [comment]
Fixed in rev 2737
