### ISSUE TITLE
Rage generation

### ISSUE THREAD

**Issue by femdead** [Atlantiss/NetherwingBugtracker#4357]
Hello, when your attack is dodged/parried by a mob, you gain no rage! And you should gain rage allowing you to use abilities. This bug makes strings of dodge/parry on a 2h warrior even more crippling than they already should be. This has already been reported but it's annoying as heck, seriously

**Comment by Wolffenstein** [comment]
Recheck after revision 2649.

**Comment by battleleet2** [comment]
Recheck - not working.
