### ISSUE TITLE
[Quest][NPC] Shay Leafrunner

### ISSUE THREAD

**Issue by rychersky** [Atlantiss/NetherwingBugtracker#4358]
[//]: # (Enclose links to things related to the bug using http://wowhead.com or any other TBC database.)
[//]: # (You can use screenshot ingame to visual the issue.)
[//]: # (Write your tickets according to the format:)
[//]: # ([Quest][Azuremyst Isle] Red Snapper - Very Tasty!)
[//]: # ([NPC] Magistrix Erona)
[//]: # ([Spell][Mage] Fireball)
[//]: # ([Npc][Drop] Ghostclaw Lynx)
[//]: # ([Web] Armory doesnt work)
[//]: # (To find server revision type `.server info` command in the game chat.)

**Description**: I've been standing at her spawn point for about 30 minutes waiting for her to respawn (I'm assuming someone recently did the escort) and have yet to see her. A guildie saw me standing here on the map and messaged me saying he watched an entire TV espisode of a show waiting and she never spawned.

![image](https://user-images.githubusercontent.com/45608488/51429808-ce031700-1bcf-11e9-90d8-3f0c401a30c3.png)

**Server Revision**: 2647

**Comment by wtRCH** [comment]
@aresbrutus

**Comment by Evolvee** [comment]
7774

she doesnt respawn for some reason even though she has 30 sec spawntimesecs @Wolffenstein

**Comment by aresbrutus** [comment]
https://github.com/Atlantiss/NetherwingBugtracker/issues/4569
