### ISSUE TITLE
[Quest][QID 2358][Horns of Nez'ra] is Missing???

### ISSUE THREAD

**Issue by OMEGALULW** [Atlantiss/NetherwingBugtracker#4359]
**Description**: https://wow.gamepedia.com/Horns_of_Nez%27ra_(quest)

**Current behaviour**: No quest available 

**Expected behaviour**: Quest should be available?? xd 

**Server Revision**: 2647

**Comment by wtRCH** [comment]
@aresbrutus

**Comment by The14me** [comment]
https://classic.wowhead.com/quest=2358/horns-of-nezra#comments:id=3153278
The issue can be closed.

**Comment by Tereneckla** [comment]
Only was in the beta version
