### ISSUE TITLE
[Quest] Turning Point

### ISSUE THREAD

**Issue by naekobest** [Atlantiss/NetherwingBugtracker#4360]
"Voren'thal's Presence" Item does not work on the mob

https://i.gyazo.com/89ae28a07ffa393d9199c2832dbc551b.mp4

Also:
Aldor event bugged too
https://i.gyazo.com/030d3e79a85103fcc91ec8a9369b5e39.mp4

**Comment by Exorcista** [comment]
Npcs that start the Event for any faction takes way longer than 40min to respawn and someone be able to do the quest. Is not logic at all.

**Comment by The14me** [comment]
That quest is Rip on NW and Kara atm.(Teleport work, but nothing more.)
Rev.3460
