### ISSUE TITLE
[Quest][Desolace] Kodo Roundup tamed Kodo follows indefinitely

### ISSUE THREAD

**Issue by MrOrgmo** [Atlantiss/NetherwingBugtracker#4361]
**Description**: 
Quest "Kodo Roundup" in Desolace requires you to use an item to tame Kodos and bring them to a Goblin. While tamed, these Kodos follow you one at a time until delivery.

**Current behaviour**:

The final Kodo continues to follow the character (seemingly indefinitely)

![wowscrnshot_011919_195326](https://user-images.githubusercontent.com/13544889/51431642-f6b4fc00-1c23-11e9-90d4-574cf783cbe8.jpg)

**Expected behaviour**: 

The final kodo disappears once handed in

**Server Revision**: 
20:00 GMT 19/10/2019

**Comment by maxturtlesc2** [comment]
There's another bug: if you have the Kodo Kombobulator debuff on you, you can talk to a Tamed Kodo from another person doing the quest at the same time to get credit of 1 Kodo towards the completion of the quest. You should only get credit when you talk to the kodo you tamed instead.

**Comment by MrOrgmo** [comment]
Saw a Tamed Kodo following someone around in Orgrimmar yesterday. Still unresolved then :wink:

**Comment by Smjames95** [comment]
This issue _might_ not be restricted to just the final Kodo. I just saw 5 Tamed Kodos stacked on the Innkeeper at Shadowprey Village.
![Kodo Glitch](https://user-images.githubusercontent.com/49467093/55850045-cf821280-5b20-11e9-9ed0-816916020260.png)

**Comment by Manaci** [comment]
Fixed
