### ISSUE TITLE
Mind Flay Not Casting

### ISSUE THREAD

**Issue by Thugli** [Atlantiss/NetherwingBugtracker#4362]
[//]: # (Enclose links to things related to the bug using http://wowhead.com or any other TBC database.)
[//]: # (You can use screenshot ingame to visual the issue.)
[//]: # (Write your tickets according to the format:)
[//]: # ([Quest][Azuremyst Isle] Red Snapper - Very Tasty!)
[//]: # ([NPC] Magistrix Erona)
[//]: # ([Spell][Mage] Fireball)
[//]: # ([Npc][Drop] Ghostclaw Lynx)
[//]: # ([Web] Armory doesnt work)
[//]: # (To find server revision type `.server info` command in the game chat.)

**Description**: 
Occasionally mind flay will not cast; the mana will be used and the animation will go off for a split second but the ability won't actually properly go off, resulting in lost mana. It seems to happen in batches, in the sense that once this issue is prevalent, as long as you are standing still it will persist. It's possible it is related to using mindflay at the same time as you strafe but I otherwise have no idea what could be causing it. 

I use the following macro for mind flay, which may or may not contribute to this bug:
/cast [nochanneling]Mind Flay
This macro will not allow me to cancel and recast mind flay if I am currently channeling mind flay.

**Current behaviour**:
![image](https://user-images.githubusercontent.com/37326256/51431912-9317d800-1bfd-11e9-8969-bea3f37da87a.png)

**Expected behaviour**: 

**Server Revision**: 
2647

**Comment by Jalapan** [comment]
same with all channeling spells, warlock Drain life/soul for example

**Comment by Jalapan** [comment]
related https://github.com/Atlantiss/NetherwingBugtracker/issues/4406

**Comment by Jalapan** [comment]
https://github.com/Atlantiss/NetherwingBugtracker/issues/4057

**Comment by Tereneckla** [comment]
#4018
