### ISSUE TITLE
Zangarmarsh PvP Event bugs

### ISSUE THREAD

**Issue by Medry** [Atlantiss/NetherwingBugtracker#4363]
[//]: # (Enclose links to things related to the bug using http://wowhead.com or any other TBC database.)
[//]: # (You can use screenshot ingame to visual the issue.)
[//]: # (Write your tickets according to the format:)
[//]: # ([Quest][Azuremyst Isle] Red Snapper - Very Tasty!)
[//]: # ([NPC] Magistrix Erona)
[//]: # ([Spell][Mage] Fireball)
[//]: # ([Npc][Drop] Ghostclaw Lynx)
[//]: # ([Web] Armory doesnt work)
[//]: # (To find server revision type `.server info` command in the game chat.)

**Description**: 
After capturing both towers, the center has both a capturable neutral flag and an alliance flag. Upon visiting the Field Scout, he has no dialogue to give the player the flag.

**Current behaviour**:
Upon visiting the Field Scout, he has no dialogue to give the player the flag.
**Expected behaviour**: 
He should have dialogue to take his flag so you can bring it to a GY 
https://youtu.be/yt0YBk8RP18?t=163
"When both towers are under your faction's control, the Field Scout of your respective faction will hand out a Battle Standard, which can then be placed in the graveyard (Blizzard calls this the "Central Tower"), capturing it for your faction."

**Server Revision**: 
2647

**Comment by Cinx787** [comment]
Still an issues as of Rev: 2749

**Comment by DragunovUA** [comment]
pls can u add option to capture it plssss

**Comment by Wolffenstein** [comment]
Fixed in rev 3328.
