### ISSUE TITLE
bonus damage

### ISSUE THREAD

**Issue by sandfury** [Atlantiss/NetherwingBugtracker#4364]
[//]: # (Enclose links to things related to the bug using http://wowhead.com or any other TBC database.)
[//]: # (You can use screenshot ingame to visual the issue.)
[//]: # (Write your tickets according to the format:)
[//]: # ([Quest][Azuremyst Isle] Red Snapper - Very Tasty!)
[//]: # ([NPC] Magistrix Erona)
[//]: # ([Spell][Mage] Fireball)
[//]: # ([Npc][Drop] Ghostclaw Lynx)
[//]: # ([Web] Armory doesnt work)
[//]: # (To find server revision type `.server info` command in the game chat.)

**Description**: 

Preserver's Cudgel not adding bonus damage when it should.

I'm not sure if this has something to do with 2.0 itemization though. Sorry for the bad title, I accidentally clicked and now I don't know how to edit.

![wowscrnshot_012019_010308](https://user-images.githubusercontent.com/11744594/51433640-9cca2b80-1c4f-11e9-8758-858459b1166d.jpg)
![wowscrnshot_012019_010310](https://user-images.githubusercontent.com/11744594/51433661-22e67200-1c50-11e9-8512-c61cc7ba6a85.jpg)

**Current behaviour**:

**Expected behaviour**: 

**Server Revision**:

**Comment by Brasso** [comment]
In 2.0 healing gear doesn't give bonus spell damage. Download tooltip fix by Null https://github.com/nullfoxh/NWTooltipFix to see correct tooltips.
