### ISSUE TITLE
[Spell][Mage] Combustion

### ISSUE THREAD

**Issue by Tottori97** [Atlantiss/NetherwingBugtracker#4365]
**Description**: Combustion bugged out somehow while in a dungeon. It got up to 100% crit chance and didn't fall off no matter how many spell crits I got, until I died. I tried to reproduce the bug again but to no avail. I thought it bugged out due to my AoE spells Flamestrike and Blast Wave, but I wasn't able to reproduce it again.

**Current behaviour**: One-time? bug out where the crit didn't fall off.

**Expected behaviour**: Consumed upon any 3 fire spell crits.
![wowscrnshot_012019_010815](https://user-images.githubusercontent.com/46360896/51434220-0e0fdb80-1c5c-11e9-8514-951f8d78ea5d.jpg)
![wowscrnshot_012019_010847](https://user-images.githubusercontent.com/46360896/51434221-0ea87200-1c5c-11e9-9055-0e68eed9153d.jpg)
**Server Revision**: 2647

**Comment by Wolffenstein** [comment]
Fixed in rev 2874.
