### ISSUE TITLE
Kobold patrol pathing in air in Arathi

### ISSUE THREAD

**Issue by Zuntrix** [Atlantiss/NetherwingBugtracker#4367]
[//]: # (Enclose links to things related to the bug using http://wowhead.com or any other TBC database.)
[//]: # (You can use screenshot ingame to visual the issue.)
[//]: # (Write your tickets according to the format:)
[//]: # ([Quest][Azuremyst Isle] Red Snapper - Very Tasty!)
[//]: # ([NPC] Magistrix Erona)
[//]: # ([Spell][Mage] Fireball)
[//]: # ([Npc][Drop] Ghostclaw Lynx)
[//]: # ([Web] Armory doesnt work)
[//]: # (To find server revision type `.server info` command in the game chat.)

**Description**: 
Kobold patrol in Arathi Highlands are walking in the air.

**Current behaviour**:
Walking in the air

https://imgur.com/QP2Fyw9

**Expected behaviour**: 
Walking on the ground :3

**Server Revision**: 
2647

**Comment by The14me** [comment]
Rev 3460. They look fine now.
