### ISSUE TITLE
[Quest][NPC] Private Thorsen won't end quest

### ISSUE THREAD

**Issue by Silun** [Atlantiss/NetherwingBugtracker#4368]
Private Thorsen in STV won't end the Quest "Supplies to Private Thorsen", neither on his patrol nor when he's just standing in the camp. He will however end the quest after being killed and spawned again. After turning in the quest, the follow up will show as an exclamation mark over his head, but he will not actually offer the quest.

https://imgur.com/a/sgz2sLZ

**Comment by Jaypy** [comment]
same issue.

**Comment by The14me** [comment]
Right now rev.3460 u can complete the quest with no problem at any moment.
Can be closed.
