### ISSUE TITLE
Undead starting area- scarlets

### ISSUE THREAD

**Issue by yokothan** [Atlantiss/NetherwingBugtracker#437]
[//]: # (Enclose links to things related to the bug using http://wowhead.com or any other TBC database.)
[//]: # (You can use screenshot ingame to visual the issue.)
[//]: # (Write your tickets according to the format:)
[//]: # ([Quest][Azuremyst Isle] Red Snapper - Very Tasty!)
[//]: # ([NPC] Magistrix Erona)
[//]: # ([Spell][Mage] Fireball)
[//]: # ([Npc][Drop] Ghostclaw Lynx)
[//]: # ([Web] Armory doesnt work)

**Description**: 
Scarlet initiate's don't have and LOS and also don't follow you when trying to kite. instead the immediately lose aggro. 
**Current behaviour**:

**Expected behaviour**: 

**Server Revision**:

**Comment by Easyfraggy** [comment]
Not having LOS is not a bug.

The resetting is a bug.

**Comment by Wolffenstein** [comment]
Seems fine to me. If you think it's still bugged, please record a video and reopen.
