### ISSUE TITLE
[Spell][Warrior] Sweeping Strikes & [Spell][Warrior] Whirlwind aren't working correctly

### ISSUE THREAD

**Issue by Boherus** [Atlantiss/NetherwingBugtracker#4370]
[//]: # (Enclose links to things related to the bug using http://wowhead.com or any other TBC database.)
[//]: # (You can use screenshot ingame to visual the issue.)
[//]: # (Write your tickets according to the format:)
[//]: # ([Quest][Azuremyst Isle] Red Snapper - Very Tasty!)
[//]: # ([NPC] Magistrix Erona)
[//]: # ([Spell][Mage] Fireball)
[//]: # ([Npc][Drop] Ghostclaw Lynx)
[//]: # ([Web] Armory doesnt work)
[//]: # (To find server revision type `.server info` command in the game chat.)

**Description**: [Spell][Warrior] Sweeping Strikes and [Spell][Warrior] Whirlwind aren't working correctly together.
**Current behaviour**: [Spell][Warrior] Whirlwind hitting 4 mobs while [Spell][Warrior] Sweeping Strikes is on only procs Sweeping Strikes once. It's always 1 proc, it doesn't care how many targets were hit by Whirlwind.

**Expected behaviour**: It should proc Sweeping Strikes for each hit of Whirlwind. So 2 hits of Whirlwind should be 2 hits of Sweepings Strikes.

**Server Revision**: 2647

**Comment by Boherus** [comment]
why this is low prio? We’re missing out on tons of damage on any 2+ target aoe

5 hits on 4 target AoE instead of 8 is a pretty good sized chunk of missing damage.

**Comment by Bravehurt** [comment]
https://youtu.be/bWYyXMgmeFU

Clearly showing how it should work.

**Comment by Boherus** [comment]
> after more research, found an old wowhead thread amongst others, that pointed out only 1 whirlwind hit will be proc off SS.
> 
> > /cast sweeping strikes
> > /cast victory rush
> > /cast cleave
> > My grinding macro, with it I can kill 4 mobs faster than they can say "Not in the face!"
> 
> > 2: things about SS tho.
> > 1: WW will only produce 1 extra attack
> > 2: execute will only do about a normal swing worth of damage if the other target is 20%+ HP
> 
> https://www.wowhead.com/forums&topic=33796
> https://hilbert.wordpress.com/sweeping-strikes-guide/
> 
> This is just a reminder to people to do some actual research before opening an issue blindly. It simply waste everyone's time that could be used to fix other issues

How do you explain 9 yellow numbers coming up the second he uses Whirlwind+SS in this video? (A video you linked before the edits) https://www.youtube.com/watch?v=bWYyXMgmeFU

In that video you can clearly see right before he activates cleave he uses only whirlwind+sweeping strikes and 9 yellow numbers appear with 1 of them being parried/dodged. Theres no possible way for that many Yellow numbers to be on the screen with just WW/SS if that combo only generated 1 additional attack. It's pretty simple how it works. If Whirlwind deals damage to a target it will trigger sweeping strikes on another target, it's ONE trigger for ONE hit. It's not using the dual wield extra dmg hit it's combining that for the sweeping strikes.

**Comment by Boherus** [comment]
Yeah actually bravehurt is right i didn't go into much depth looking it up. I just figured other servers had gotten it right. It currently works correctly.

**Comment by Jalapan** [comment]
https://github.com/Atlantiss/NetherwingBugtracker/issues/4476
