### ISSUE TITLE
[Spell][Rogue] Riposte

### ISSUE THREAD

**Issue by Gromi** [Atlantiss/NetherwingBugtracker#4371]
[//]: # (Enclose links to things related to the bug using http://wowhead.com or any other TBC database.)
[//]: # (You can use screenshot ingame to visual the issue.)
[//]: # (Write your tickets according to the format:)
[//]: # ([Quest][Azuremyst Isle] Red Snapper - Very Tasty!)
[//]: # ([NPC] Magistrix Erona)
[//]: # ([Spell][Mage] Fireball)
[//]: # ([Npc][Drop] Ghostclaw Lynx)
[//]: # ([Web] Armory doesnt work)
[//]: # (To find server revision type `.server info` command in the game chat.)

**Description**: 
The disarm effect duration from riposte is not correct

**Current behaviour**:
The mob are disarmed for 1 to 6 sec, its random.

**Expected behaviour**: 
The target should be disarmed for 6 sec.

**Server Revision**: 
2647

**Comment by AWIDIUS** [comment]
Maybe DR are applied to mobs aswell.

**Comment by wtRCH** [comment]
@Evolvee

**Comment by Gromi** [comment]
If its dr related it means that dr is applied to all the mobs sharing the same name. I just did a 1 sec first disarm on a mob.

**Comment by nullfoxh** [comment]
Yeah can confirm, it's randomly lasting way less than it should.

**Comment by Wolffenstein** [comment]
Can't reproduce.
