### ISSUE TITLE
Old Hillsbrad (Heroic) [drop]

### ISSUE THREAD

**Issue by knasen88** [Atlantiss/NetherwingBugtracker#4372]
[//]: # (Enclose links to things related to the bug using http://wowhead.com or any other TBC database.)
[//]: # (You can use screenshot ingame to visual the issue.)
[//]: # (Write your tickets according to the format:)
[//]: # ([Quest][Azuremyst Isle] Red Snapper - Very Tasty!)
[//]: # ([NPC] Magistrix Erona)
[//]: # ([Spell][Mage] Fireball)
[//]: # ([Npc][Drop] Ghostclaw Lynx)
[//]: # ([Web] Armory doesnt work)
[//]: # (To find server revision type `.server info` command in the game chat.)

**Description**: 
Not a single drop except boss drops and silver from mobs, in 70 dungeons in general the loottable for greens are very slim but in here there's absolutely zero drops
**Current behaviour**:
^
**Expected behaviour**: 
if anything, heroics should yield more items?
**Server Revision**: 
2647

**Comment by Tenoutoften** [comment]
https://github.com/Atlantiss/NetherwingBugtracker/issues/3438

**Comment by wtRCH** [comment]
@Wolffenstein

**Comment by Evolvee** [comment]
should work after rev 2751
