### ISSUE TITLE
The Mailbox in Shadowmoon Village Doesn't Work

### ISSUE THREAD

**Issue by fantom8** [Atlantiss/NetherwingBugtracker#4373]
**Description**: 
When attempting to send a mail (in my case an alt) using the mailbox next to Researcher Tiorus it will fail. The "send" button goes grey but the mail just hangs and doesn't send.

**Current behaviour**:
You can't send mails using the mailbox in SMV

**Expected behaviour**: 
You should be able to send mails using the mailbox in SMV

**Server Revision**: 
2647

**Comment by wtRCH** [comment]
@Shanghi
