### ISSUE TITLE
[Quest] Samophlange

### ISSUE THREAD

**Issue by chusli** [Atlantiss/NetherwingBugtracker#4375]
[//]: # (Enclose links to things related to the bug using http://wowhead.com or any other TBC database.)
[//]: # (You can use screenshot ingame to visual the issue.)
[//]: # (Write your tickets according to the format:)
[//]: # ([Quest][Azuremyst Isle] Red Snapper - Very Tasty!)
[//]: # ([NPC] Magistrix Erona)
[//]: # ([Spell][Mage] Fireball)
[//]: # ([Npc][Drop] Ghostclaw Lynx)
[//]: # ([Web] Armory doesnt work)
[//]: # (To find server revision type `.server info` command in the game chat.)

**Description**: 
Samophlange Quest in The Barrens is not working
**Current behaviour**:
You can "speak" with the console but the quest does not progress.
**Expected behaviour**: 
The quest should progress after talking to the console
**Server Revision**: 
No idea, happened yesterday 19.1.2019

**Comment by wtRCH** [comment]
It worked for me earlier.

**Comment by Tereneckla** [comment]
Worked multiple times
