### ISSUE TITLE
[Profession][Engineering] Fell Iron Shells

### ISSUE THREAD

**Issue by Eidous** [Atlantiss/NetherwingBugtracker#4376]
[//]: # (Enclose links to things related to the bug using http://wowhead.com or any other TBC database.)
[//]: # (You can use screenshot ingame to visual the issue.)
[//]: # (Write your tickets according to the format:)
[//]: # ([Quest][Azuremyst Isle] Red Snapper - Very Tasty!)
[//]: # ([NPC] Magistrix Erona)
[//]: # ([Spell][Mage] Fireball)
[//]: # ([Npc][Drop] Ghostclaw Lynx)
[//]: # ([Web] Armory doesnt work)
[//]: # (To find server revision type `.server info` command in the game chat.)

**Description**: 
Crafting Fell Iron Shells give you double the amount of shells that you should be getting (400 instead of 200)

**Current behaviour**:
When crafting Fell Iron Shells you obtain 400 shells per craft.

**Expected behaviour**: 
When crafting Fell Iron Shells you should obtain 200 shells per craft.

**Server Revision**: 
2647

**Comment by wtRCH** [comment]
@aresbrutus

**Comment by The14me** [comment]
Rev.3460 still an issue.

**Comment by Wolffenstein** [comment]
Fixed in rev 3469.
