### ISSUE TITLE
[Quest] The Giant Guardian [NPC]

### ISSUE THREAD

**Issue by The14me** [Atlantiss/NetherwingBugtracker#4378]
**Current behaviour**:Shay Leafrunner dont spawn (ID: 7774)

**Expected behaviour**: Its suppose to spawn.
https://www.wowhead.com/quest=2844/the-giant-guardian

**Server Revision**:

**Comment by Jalapan** [comment]
tried the quest today, npc is not spawning.

**Comment by Jalapan** [comment]
Related to https://github.com/Atlantiss/NetherwingBugtracker/issues/4358

**Comment by Ofecks** [comment]
Went to her spot, waited 5 minutes or so thinking someone had just done her escort, but she didn't spawn.  After I had looked up this issue in the bugtracker, and was working on what the next step in my guide was, she spawned!  The follow-up quest, [49] Wandering Shay, was scripted perfectly and I was able to complete it.  So the quest is working as far as I can tell.

**Comment by Gemuesesueppe** [comment]
Agreed, still doesnt spawn.

**Comment by Tryptamine1** [comment]
As of the 2nd of March, Shay Leafrunner is still not spawning.

**Comment by leeviathan** [comment]
Someone yesterday mentioned that they waited 20 minutes and she eventually spawned. I think they waited right at her spawn location.

**Comment by The14me** [comment]
she bug out [again ](https://imgur.com/a/4Ub4tk6)

**Comment by Evolvee** [comment]
need a way to reproduce this

**Comment by The14me** [comment]
Way to reproduce
1)Make Alli
2)Add quest  2844
3) Teleport to 7774
4)Turn the quest and take the next on. Take the bell from the chest. Walk around with her...kill some npc's etc. Once u see ''Shay Leafrunner Begins to warder off.'' DONT use the bell. Just log out/alt F4 or w/e.
6)She gonna run all over the place till the server restart/crash.

**Comment by The14me** [comment]
Rev.3460 still an issue.

**Comment by Wolffenstein** [comment]
Fixed in rev 3472.
