### ISSUE TITLE
[Spell] Freezing Circle

### ISSUE THREAD

**Issue by RealZwox** [Atlantiss/NetherwingBugtracker#4379]
The hitbox of [Freezing Circle](https://www.wowhead.com/spell=34787/freezing-circle) is way to high.
![image](https://user-images.githubusercontent.com/12686136/51439747-164d3280-1cbf-11e9-9a93-eb9396c666b8.png)

**Server Revision**: 
2647

**Comment by Jseay1313** [comment]
it's way too big, should be just in the circle of ice

**Comment by femdead** [comment]
https://cdn.discordapp.com/attachments/455120632871387156/537653643931942913/unknown.png yeah it's massive lol

**Comment by Tereneckla** [comment]
![WoWScrnShot_010420_143539](https://user-images.githubusercontent.com/50233983/71766364-9cc64880-2eff-11ea-9612-bdf987e60117.jpg)
Fixed
