### ISSUE TITLE
[World] Zeppelin origin and destination swapped visually

### ISSUE THREAD

**Issue by imroroyo** [Atlantiss/NetherwingBugtracker#4380]
[//]: # (Enclose links to things related to the bug using http://wowhead.com or any other TBC database.)
[//]: # (You can use screenshot ingame to visual the issue.)
[//]: # (Write your tickets according to the format:)
[//]: # ([Quest][Azuremyst Isle] Red Snapper - Very Tasty!)
[//]: # ([NPC] Magistrix Erona)
[//]: # ([Spell][Mage] Fireball)
[//]: # ([Npc][Drop] Ghostclaw Lynx)
[//]: # ([Web] Armory doesnt work)
[//]: # (To find server revision type `.server info` command in the game chat.)

**Description**: 
The behaviour seems to be present for all zeppelins and boats. Where during the loading screen while going between two locations, the origin and destination have been swapped visually.

**Current behaviour**:
If for example going from Orgrimmar to Undercity, while on the loading screen between the world, it will draw the destination as origin, and vice versa. In the example above it will show Undercity as the circle, and Orgrimmar as the cross, and also draw the actual 'way' from UC to OG.

**Expected behaviour**: 
It should obviously be visually showing the correct direction in which the zeppelin or boat is headed.

**Server Revision**:
2647

**Comment by imroroyo** [comment]
I know I have seen this before, but lately I haven't seen it when going between different locations.

**Comment by The14me** [comment]
Rev.3460 looks like fixed now.
Can be closed.
