### ISSUE TITLE
[NPC] Summoned npc aggro 

### ISSUE THREAD

**Issue by syphex97** [Atlantiss/NetherwingBugtracker#4381]
[//]: # (Enclose links to things related to the bug using http://wowhead.com or any other TBC database.)
[//]: # (You can use screenshot ingame to visual the issue.)
[//]: # (Write your tickets according to the format:)
[//]: # ([Quest][Azuremyst Isle] Red Snapper - Very Tasty!)
[//]: # ([NPC] Magistrix Erona)
[//]: # ([Spell][Mage] Fireball)
[//]: # ([Npc][Drop] Ghostclaw Lynx)
[//]: # ([Web] Armory doesnt work)
[//]: # (To find server revision type `.server info` command in the game chat.)

**Description**: 
The Succubus Minions in Terokkar Forest at Grangol'Var Village for some reason aggro on you without their master and then even tho their master has ran out of aggro range when they chase you a well the Succubus minions just keep on chasing you.

**Current behaviour**:
Currently chases you and attacks you without your master or chases you much further away from their master ( did not test how far as i had to kill them or they would have killed me)
**Expected behaviour**: 
Should aggro with their Master & as well stop chasing you once you get outside of x range to return to their master

**Server Revision**: 
2647

**Comment by The14me** [comment]
rev 3460 Not an issue anymore, or at least I can't reproduce it.
Can be closed.
