### ISSUE TITLE
[Talent][Shaman] Eye of the Storm

### ISSUE THREAD

**Issue by FIXTHISFASTERRR** [Atlantiss/NetherwingBugtracker#4384]
[//]: # (Enclose links to things related to the bug using http://wowhead.com or any other TBC database.)
[//]: # (You can use screenshot ingame to visual the issue.)
[//]: # (Write your tickets according to the format:)
[//]: # ([Quest][Azuremyst Isle] Red Snapper - Very Tasty!)
[//]: # ([NPC] Magistrix Erona)
[//]: # ([Spell][Mage] Fireball)
[//]: # ([Npc][Drop] Ghostclaw Lynx)
[//]: # ([Web] Armory doesnt work)
[//]: # (To find server revision type `.server info` command in the game chat.)

**Description**: 
Eye of the Storm talent should procc of all crits including /sit  crits
**Current behaviour**:
It doesn't proc via /sit on netherwing (making it hard to play ele shaman vs any mob/hunter pet
**Expected behaviour**: 
Eye of the Storm talent should proc if u get crit by /sit which is 100% crit chance proof (https://wow.gamepedia.com/Patch_2.3.0)  [Eye of the Storm]: This talent can now trigger while the Shaman is sitting.
**Server Revision**:

**Comment by FIXTHISFASTERRR** [comment]
Pls fix this soon, if its not hard to implement, cause now u cant properly pvp with ele or level without this neat mechanic, tnx

**Comment by Brasso** [comment]
Are you sure about this? Wowwiki patch notes are often wrong or misleading. #1871 /sit should not work for warrior talents.

**Comment by FIXTHISFASTERRR** [comment]
pretty sure, go find a video of shaman drinking/sitting and when he gets crit talent will proc, if u think patch notes are wrong, what do u want me to do lol go back in time to prove it

**Comment by Brasso** [comment]
No, I want you to find a video from tbc where this is used.

**Comment by FIXTHISFASTERRR** [comment]
Its nearly impossible to  find a video of it tho, most videos are bunch of clickers showing off oneshot edits with elemental mastery, and rest are resto shamans arena, which dont have this talent...

2.0.1
Fixed an issue where spells that proc while a player was standing would not proc if they were sitting or lying down.

2.2.0
Paladin / Priest / Mage abilities proc while sitting.

2.3.0
Druid Natural protection / Warrior Blood Craze and Enrage now trigger when sitting.
-------------------------------------------------------------------------------------------------------

The 1 shotting of Kazzak was not from /sit. It was from dueling over and over and getting crits normally. 

The patch notes of 2.0.1 clearly state it is an "issue" that is fixed. Later they specifically state in patch notes different abilities that were allowed to proc while sitting. A few abilities and classes had this added multiple times in the patch notes, meaning that with certain patches they dropped, the /sit to crit function stopped working and they would readd it once again to those spells/abilities. 

It's categorized as an "issue" from Blizzard if it doesn't proc a spell. As different patches broke the ability to proc on-crit abilities, it is possible that the TBC pre-patch broke this, and had to be fixed as it did multiple times throughout TBC.

i guess someone could argue devs didnt intend crit to work like that, but then its under clever use of game mechanics, plus its nothing game breaking anyway, shamans are terrible at arena/pvp this just helps like 5%

**Comment by Brasso** [comment]
Unless you can find a video of this, or warriors using /sit to trigger enrage effects in late tbc I'm afraid this will not be changed. Devs have already stated that patch notes, especially the ones you're using, from wowwiki can be horribly inaccurate.

**Comment by FIXTHISFASTERRR** [comment]
so all 3 separate patch notes are wrong, and magically the dev's word is right... ok i guess w/e

**Comment by Brasso** [comment]
You are using the same source for all three patch notes which is invalid according to the devs. You need find a separate source as I said.

**Comment by FIXTHISFASTERRR** [comment]
they allow things like batching and other shit that was present in tbc like this talent /sit, and removed later, i guess they do whatever suits their classes

**Comment by FIXTHISFASTERRR** [comment]
>finds evidence
>"We dont like your evidence"
>find some evidence instead of crying

**Comment by Easyfraggy** [comment]
Then probably his Shamanistic Focus shouldn't proc from /sit crits which is an oversight.
