### ISSUE TITLE
[core] Waypoints(patrols) tend to randomly repeat self causing one time loop and then continue normally

### ISSUE THREAD

**Issue by Evolvee** [Atlantiss/NetherwingBugtracker#4385]
Affects both waypoints started through script and regular patrols.

The NPC goes back to previous waypoint instead of next one and then continue to the original WP and then to the next one..

So it goes like this

WP 1--WP2 --WP1--WP2--WP3

Should be like this:

WP1-WP2-WP3-WP4

**Comment by Evolvee** [comment]
happened here: npc 17704
![image](https://user-images.githubusercontent.com/1942409/70377006-723c9c00-190f-11ea-9379-0af67923b870.png)
between 15 and 16

**Comment by Godmatik** [comment]
Confirmed for NPC 17704 between 15 and 16, but I am not aware of any other examples.

**Comment by Godmatik** [comment]
Repeating WPs like this fixed with movement rework
