### ISSUE TITLE
blue bird ashenvale

### ISSUE THREAD

**Issue by jeraiko** [Atlantiss/NetherwingBugtracker#4387]
[//]: # (Enclose links to things related to the bug using http://wowhead.com or any other TBC database.)
[//]: # (You can use screenshot ingame to visual the issue.)
[//]: # (Write your tickets according to the format:)
[//]: # ([Quest][Azuremyst Isle] Red Snapper - Very Tasty!)
[//]: # ([NPC] Magistrix Erona)
[//]: # ([Spell][Mage] Fireball)
[//]: # ([Npc][Drop] Ghostclaw Lynx)
[//]: # ([Web] Armory doesnt work)
[//]: # (To find server revision type `.server info` command in the game chat.)

**Description**:  Blue bird lvl 31 who drops a quest normally.

**Current behaviour**:  He aint dropping the quest killed him 3 times in a row..

**Expected behaviour**:  Needs to drop q item for ashenvale hunt quest.

**Server Revision**:

**Comment by wtRCH** [comment]
@aresbrutus

**Comment by Evolvee** [comment]
what is blue bird? xd

**Comment by Manaci** [comment]
You need to do the starter quest to enable those
