### ISSUE TITLE
Autoshot target swap.

### ISSUE THREAD

**Issue by Wixyz** [Atlantiss/NetherwingBugtracker#4388]
**Description**: Hunter autoshot glitches out when swapping targets. You can avoid it by untargetting your current target before targetting your next target.

**Current behaviour**: Shottimer resets back to 0. You can test this out by right clicking between target dummies. With a 3.0 weapon you will never shoot when swapping targets once every 2 sec.

https://www.youtube.com/watch?v=q9sQhAQKEXk&feature=youtu.be
Video I made in an attempt to demonstrate.

**Expected behaviour**: Shottimer doesn't reset when swapping targets. If autoshot is not cooling down a shot will go off as soon as you've casted autoshot for 0.5 seconds.

**Server Revision**: 2019-01-20

**Comment by The14me** [comment]
Rev.3460 Not an issue anymore.
Can be closed.
