### ISSUE TITLE
[Spell] DoT spells are delayed

### ISSUE THREAD

**Issue by Brasso** [Atlantiss/NetherwingBugtracker#4389]
[//]: # (Enclose links to things related to the bug using http://wowhead.com or any other TBC database.)
[//]: # (You can use screenshot ingame to visual the issue.)
[//]: # (Write your tickets according to the format:)
[//]: # ([Quest][Azuremyst Isle] Red Snapper - Very Tasty!)
[//]: # ([NPC] Magistrix Erona)
[//]: # ([Spell][Mage] Fireball)
[//]: # ([Npc][Drop] Ghostclaw Lynx)
[//]: # ([Web] Armory doesnt work)
[//]: # (To find server revision type `.server info` command in the game chat.)

**Description**: 
Currently spell delay and spell batching is turned off and there is no "delay" on casted/channeled spells damaging or healing. However, there is a significantly noticeable delay on DoT spells making especially DoT classes such as affliction warlock feel like you're playing with a high ping.

**Current behaviour**:
DoT spells have varying delay on them when applying, sometimes very large.

**Expected behaviour**: 
Since spell batching and delay is turned off, dots should apply instantly.

**Server Revision**: 
2660

**Comment by Wolffenstein** [comment]
It is not turned off, it is turned on and the delay is intended.

**Comment by Brasso** [comment]
The delay feels **much** longer for dots and hots than casted spells and heals though.
