### ISSUE TITLE
[Spell] Frightening Shout

### ISSUE THREAD

**Issue by ghost** [Atlantiss/NetherwingBugtracker#439]
[//]: # (Enclose links to things related to the bug using http://wowhead.com or any other TBC database.)
[//]: # (You can use screenshot ingame to visual the issue.)
[//]: # (Write your tickets according to the format:)
[//]: # ([Quest][Azuremyst Isle] Red Snapper - Very Tasty!)
[//]: # ([NPC] Magistrix Erona)
[//]: # ([Spell][Mage] Fireball)
[//]: # ([Npc][Drop] Ghostclaw Lynx)
[//]: # ([Web] Armory doesnt work)

**Description**: 
[Spell] Frightening Shout ‎– http://db.hellfire-tbc.com/?spell=19134 & https://db.excalibur.ws/?spell=19134
**Current behaviour**:
Cannot be dispelled by 'Will of the Forsaken' as seen in this clip https://clips.twitch.tv/BraveAgileWolverineTBTacoLeft.
**Expected behaviour**: 
Should be dispelled since the tooltip says it's a fear.
**Server Revision**: 
2040

**Comment by Tereneckla** [comment]
Fixed
