### ISSUE TITLE
[Spell][Warlock][Pet] Torment rank 7 lower threat values than rank 6

### ISSUE THREAD

**Issue by TheRealZaroua** [Atlantiss/NetherwingBugtracker#4390]
[//]: # (Enclose links to things related to the bug using http://wowhead.com or any other TBC database.)
[//]: # (You can use screenshot ingame to visual the issue.)
[//]: # (Write your tickets according to the format:)
[//]: # ([Quest][Azuremyst Isle] Red Snapper - Very Tasty!)
[//]: # ([NPC] Magistrix Erona)
[//]: # ([Spell][Mage] Fireball)
[//]: # ([Npc][Drop] Ghostclaw Lynx)
[//]: # ([Web] Armory doesnt work)
[//]: # (To find server revision type `.server info` command in the game chat.)

**Description**: Rank 6 I could Immolate > Curse of Agony > Siphon Life > Unstable Affliction > Corruption and the Voidwalker would hold aggro until all the dots ran out. At rank 7, Curse of Agony > Siphon Life > Unstable Affliction > Corruption and the pet will lose aggro within 10 or 15 seconds.
https://db.excalibur.ws/?spell=27270
https://db.excalibur.ws/?spell=11775

**Current behaviour**: Voidwalker's Torment does less threat with the rank 7 upgrade than with rank 6.

**Expected behaviour**: Voidwalker's Torment rank 7 should do somewhat more threat than rank 6.

**Server Revision**: 2660

**Comment by Wolffenstein** [comment]
It does a lot more threat...
