### ISSUE TITLE
[Spell][Warlock][Pet] Spell Lock doesn't incur school lockout

### ISSUE THREAD

**Issue by TheRealZaroua** [Atlantiss/NetherwingBugtracker#4392]
[//]: # (Enclose links to things related to the bug using http://wowhead.com or any other TBC database.)
[//]: # (You can use screenshot ingame to visual the issue.)
[//]: # (Write your tickets according to the format:)
[//]: # ([Quest][Azuremyst Isle] Red Snapper - Very Tasty!)
[//]: # ([NPC] Magistrix Erona)
[//]: # ([Spell][Mage] Fireball)
[//]: # ([Npc][Drop] Ghostclaw Lynx)
[//]: # ([Web] Armory doesnt work)
[//]: # (To find server revision type `.server info` command in the game chat.)

**Description**: Fel Hunter's Spell Lock spell doesn't lock out a spell's given school when successfully interrupting. Only the silence effect is applied. Spell Lock a shadow spell, once the silence wears off the caster will be able to cast shadow spells again before the expected 6 seconds lockout.
https://db.excalibur.ws/?spell=19647

**Current behaviour**: Spell Lock doesn't cause school lockout.

**Expected behaviour**: Spell Lock should cause school lockout when interrupting a spell for 6 seconds.

**Server Revision**: 2660

**Comment by Wolffenstein** [comment]
Did you test it on players or on a specific mob?

**Comment by TheRealZaroua** [comment]
Both.

**Comment by Wolffenstein** [comment]
Works fine.
