### ISSUE TITLE
Teron Gorefiend, I am quest bugged

### ISSUE THREAD

**Issue by Jerzze** [Atlantiss/NetherwingBugtracker#4393]
[//]: # (Enclose links to things related to the bug using http://wowhead.com or any other TBC database.)
[//]: # (You can use screenshot ingame to visual the issue.)
[//]: # (Write your tickets according to the format:)
[//]: # ([Quest][Azuremyst Isle] Red Snapper - Very Tasty!)
[//]: # ([NPC] Magistrix Erona)
[//]: # ([Spell][Mage] Fireball)
[//]: # ([Npc][Drop] Ghostclaw Lynx)
[//]: # ([Web] Armory doesnt work)
[//]: # (To find server revision type `.server info` command in the game chat.)

**Description**: 

**Current behaviour**: when you take control of Teron, nothing happens until you release teron, then teron becomes an enemy and the quest target spawns as a friend.

**Expected behaviour**: the dranei should spawn and you should be able to attack him as teron

**Server Revision**:

**Comment by Evolvee** [comment]
rev 2684
