### ISSUE TITLE
[item][magical ledger]

### ISSUE THREAD

**Issue by teddys** [Atlantiss/NetherwingBugtracker#4394]
**Current behaviour**: Nothing happens after right clicking https://vanilla-twinhead.twinstar.cz/?item=20949

**Expected behaviour**:  You should be able to accept the quest

**Server Revision**: 2660

**Comment by Evolvee** [comment]
its because it requires quest 8555 to be completed first and the quest is fully disabled because it leads to vanilla raids i guess

@Shanghi @aresbrutus

**Comment by duzyizly** [comment]
it's part of AQ opening quest.

![WoWScrnShot_062320_230204](https://user-images.githubusercontent.com/43931626/85462731-0c132000-b5a6-11ea-9fa6-9785c7bbefb9.jpg)

![WoWScrnShot_062320_225432](https://user-images.githubusercontent.com/43931626/85462727-0b7a8980-b5a6-11ea-9b30-cf4fada55f28.jpg)
