### ISSUE TITLE
Combat Bug

### ISSUE THREAD

**Issue by AWIDIUS** [Atlantiss/NetherwingBugtracker#4395]
When I drag Illidari Taskmaster too far away from spot he spawns by constant damage being dealt to him, his prisoners (Dreghood Geomancers and Dreghood Brute) go back to spot where they spawns. Problems starts when I kill Taskmaster. https://imgur.com/a/G8saUTn .Often happens that I get into combat after Taskmaster die and that combat drops after 2 sec, after additional 1 sec combat is refreshed from nowhere and then like 10 times all over again. Maybe if Taskmaster is dragged and killed too far away, his prisoners wont get freed and thats probably the cause of these combat refreshes.

**Comment by AWIDIUS** [comment]
Can admit that this bug happens with Taskmaster with Geomancers slaves when you just trying to leave combat by just running out and these geomancers have you in target (out of view distance) while Taskmaster left that combat. When I come closer to Geomancers (on view range of them) Taskmaster just get combat with me and run on me.

**Comment by Godmatik** [comment]
Related to https://github.com/Atlantiss/NetherwingBugtracker/issues/2260

Closing this one
