### ISSUE TITLE
[NPC]Bijou Hostile

### ISSUE THREAD

**Issue by towneh** [Atlantiss/NetherwingBugtracker#4396]
**Description**: 
Finding Bijou for Horde quest Operative Bijou (questid 4981) she is hostile to you and attacks when attacked.

**Current behaviour**:
Bijou is unable to be interacted with in order to complete the quest hand in.

![image](https://user-images.githubusercontent.com/25694892/51444647-39450a00-1cf2-11e9-9529-c92708980135.png)

**Expected behaviour**: 
Bijou should provide quest dialogue:-

I won't lie to you, <race>. I needed the money! Kibler pays very, very well - much better than the K.E.F. ever could.

But don't doubt my loyalties! Why do you think I'm down here? To get that crazy goblin some exotic animal eggs or something equally inane? No, only someone truly daft would come to Blackrock Spire to collect pets. Yep, I don't reckon too many people like that exist in this world.

<Bijou laughs.>

The last thing we need are those kinds of people breeding.

**Server Revision**: 
2660

**Comment by wtRCH** [comment]
@aresbrutus

**Comment by Evolvee** [comment]
rev 2719
