### ISSUE TITLE
Get kicked from guild after every logout/crash

### ISSUE THREAD

**Issue by Shinizaa** [Atlantiss/NetherwingBugtracker#4397]
**Description**: Whenever I log out of the game or the server crashes I get kicked from my guild.

**Current behaviour**: Whenever I log out of the game or the server crashes I get kicked from my guild.

**Expected behaviour**:  Able to log out without getting removed from guild.

**Server Revision**: rev 2660

**Comment by HaydenBruinsma** [comment]
Hi, this is happening to me also. When I logout or crash, or dc or whatever, I get "removed" from my guild and am "guildless" however, I can still see guild chat but am unable to talk. To others, I am still in the guild and they can remove me however I can also be invited to another guild and can see both guilds /g. I am able to talk in the new guild until I log out etc then the issue happens again when I log back in.

**Comment by Shnoofeen** [comment]
There is an issue that I am currently facing with the guild that I have. I have had two players experience this now, it is quite similar but not exact the same but could very well be related. 

There is a player who has been trying to leave my guild for last couple days. He joined another guild and every time he logs out it puts him back in our guild. However, you can't see him on the rooster, but the note appears of him coming online. He cant see the guild under social, he can't speak but can see our guild chat (all ranks are open to speak/listen) and has the name of our guild under his name.  He quits the guild  and then he can see the chat of the guild he decided to join, but then once he logs out it puts him back into my guild. However, you can't actually see him in the guild rooster. 

Now this also happened to my partner (both of the players were invited to the guild and didn't sign the initial charter). She had logged out but and came back on later and the guild social pane was blank, under her name was blank but she was able to see all the guild chat but unable to speak in the guild, and she did show up inside the guild rooster. I was able to remove her from the guild and re-invite her and it seems to have been stable for her thus far. 

There are only 11 players in this guild. Another thing that I noticed is when checking the /ginfo it displays the guild as being created 42-94-0 and originally it was actually 0-0-0 

So what is wrong with guilds and why are these issues happening? I've had people say to me have you got over 500 people, so there is some form of issue there?? Why I am having this problem with 11 players and 9 accounts... 

and I really wouldn't like to hear of a 'disband your guild' to fix, the issue needs to be addressed and resolved. If it happens once without being fixed it will certainly happen again. 
![money guild creation](https://user-images.githubusercontent.com/46903596/51494065-52f85700-1daf-11e9-9898-b682166d2273.jpg)
![swiftkiller](https://user-images.githubusercontent.com/46903596/51494067-52f85700-1daf-11e9-9299-6595c41f45e9.jpg)

**Comment by thiccmike** [comment]
Description: Whenever I log out of the game or the server crashes I get kicked from my guild.

Current behaviour: Whenever I log out of the game or the server crashes I get kicked from my guild.

Expected behaviour: Able to log out without getting removed from guild.

I can second the top two comments. Exactly what's happening to me ^^^

**Comment by Shnoofeen** [comment]
So update;

this one said guy that was trying to leave the guild has now came back into it. We can see him in rooster and he chats through our guild, but now somehow he can see people from this other guild coming online and also sees all of that other guilds chat..

**Comment by Skabbkatt** [comment]
I have the same issue. At first i was also bounced back into my old guild. But it has stopped doing that now for some reason. Still cant stay in new guild after relog. I can't see roster, but my guildies sais im there and chat is visible. I am however unable to type in guild chat. We have tried kicking me and inviting me again. But nothing works.

**Comment by Shnoofeen** [comment]
More information relating to guild;

I've noticed that when I make changes to the guild (promote, demote, edit settings) after some time these settings are also reverting themselves back to what they were originally.

**Comment by Bromidious** [comment]
same

**Comment by joltox** [comment]
Am having the same issue, log out and back in and am guildless but can still see guild chat.

**Comment by danbopes** [comment]
Please reopen/comment and tag me if you're still experiencing this issue. We rewrote a good chunk of the guild code, so this issue should be resolved.
