### ISSUE TITLE
[Notification Bug] False notification of quest being shared

### ISSUE THREAD

**Issue by Thugli** [Atlantiss/NetherwingBugtracker#440]
[//]: # (Enclose links to things related to the bug using http://wowhead.com or any other TBC database.)
[//]: # (You can use screenshot ingame to visual the issue.)
[//]: # (Write your tickets according to the format:)
[//]: # ([Quest][Azuremyst Isle] Red Snapper - Very Tasty!)
[//]: # ([NPC] Magistrix Erona)
[//]: # ([Spell][Mage] Fireball)
[//]: # ([Npc][Drop] Ghostclaw Lynx)
[//]: # ([Web] Armory doesnt work)

**Description**: 
I received a notification that a player that I was not grouped with accepted my quest. I had grouped with this player an hour ago, but even then I did not share any quests. I messaged said player, and he did not accept a quest when the notification appeared, so it is unclear what triggered the message on my screen.
![untitled](https://user-images.githubusercontent.com/37326256/45983472-c0c38a80-c02a-11e8-848b-ae4bd209477c.png)

**Current behaviour**:
Bugged notification of sharing a quest with a player 
**Expected behaviour**: 
This message should not appear unless a quest is actually shared and accepted with a member of someone's party or raid.
**Server Revision**:

**Comment by Wolffenstein** [comment]
There are quests that get shared immediately with the party once you accept them.

**Comment by Thugli** [comment]
I suppose that's entirely possible, although I was still receiving the notification over an hour after grouping with this individual (He had been actively playing the game, and I had asked him about it, so there is no possibility that he had the quest window open that entire time). While the message probably was accurate, it was still a very delayed message, somewhat similar to #306

**Comment by Wolffenstein** [comment]
Fixed in rev 3410.
