### ISSUE TITLE
Missing Talent Point On Level up.

### ISSUE THREAD

**Issue by BUSTYMILF** [Atlantiss/NetherwingBugtracker#4400]
[//]: # (Enclose links to things related to the bug using http://wowhead.com or any other TBC database.)
[//]: # (You can use screenshot ingame to visual the issue.)
[//]: # (Write your tickets according to the format:)
[//]: # ([Quest][Azuremyst Isle] Red Snapper - Very Tasty!)
[//]: # ([NPC] Magistrix Erona)
[//]: # ([Spell][Mage] Fireball)
[//]: # ([Npc][Drop] Ghostclaw Lynx)
[//]: # ([Web] Armory doesnt work)
[//]: # (To find server revision type `.server info` command in the game chat.)

**Description**: leveled up and didnt get talent point

**Current behaviour**: lvl 45 with 35 points

**Expected behaviour**:  lvl 45 with 36 points

**Server Revision**:

**Comment by ttghnw** [comment]
fixes after relog
