### ISSUE TITLE
[Healing Wave][Shaman] Healing Way Talent overwrites from different shamans

### ISSUE THREAD

**Issue by Ensipidx** [Atlantiss/NetherwingBugtracker#4401]
**Description**: Healing way talent is bugged.

**Current behaviour**: Healing wave that apply healing way overwrite each other from different shamans so multiple shamans keep resetting the healing way stack down to 1 stack.

**Expected behaviour**: They should just reset the timer without resetting the stacks or multiple shamans healing one tank literally screw over each other.

**Server Revision**: 2660

**Comment by Ensipidx** [comment]
Very important to fix, makes shamans doing -10%~ less healing on tanks with healing wave than they should.

**Comment by Drayo** [comment]
https://github.com/Atlantiss/NetherwingBugtracker/issues/3428

**Comment by Wolffenstein** [comment]
Fixed in rev 2664.
