### ISSUE TITLE
[Raid][Gruul] Gruul is doing hateful strike from any distance (ranged)

### ISSUE THREAD

**Issue by killablink** [Atlantiss/NetherwingBugtracker#4402]
**Description**: Gruul can hit people from 30 yards away with hatefuls.

**Current behaviour**: Gruul can hit people from 30 yards away with hatefuls.

**Expected behaviour**:  Should only hateful melee. Please fix quickly.

**Server Revision**: 2663

**Comment by Wolffenstein** [comment]
Rev 2665.
