### ISSUE TITLE
[Spell][Warrior] Sweeping Strikes & [Spell][Warrior] Execute aren't working like on retail

### ISSUE THREAD

**Issue by shmi11** [Atlantiss/NetherwingBugtracker#4404]
[//]: # (Enclose links to things related to the bug using http://wowhead.com or any other TBC database.)
[//]: # (You can use screenshot ingame to visual the issue.)
[//]: # (Write your tickets according to the format:)
[//]: # ([Quest][Azuremyst Isle] Red Snapper - Very Tasty!)
[//]: # ([NPC] Magistrix Erona)
[//]: # ([Spell][Mage] Fireball)
[//]: # ([Npc][Drop] Ghostclaw Lynx)
[//]: # ([Web] Armory doesnt work)
[//]: # (To find server revision type `.server info` command in the game chat.)

**Description**: 
Sweeping strikes combined with execute is not dealing damage the way it is supposed to do.
**Current behaviour**:
Sweeping strikes with execute deals no damage to the second target if it has more than 20% health.
**Expected behaviour**: 
Sweeping strikes with execute should deal normal melee swing damage to the second target if its health is above 20%.
**Source**:
Look at Patch change of 1.11.0
http://wowwiki.wikia.com/wiki/Sweeping_Strikes
**Server Revision**:

**Comment by FIXTHISFASTERRR** [comment]
bro patch notes are wrong, bring proof bro, stop crying

**Comment by shmi11** [comment]
stop crying? what's up with the insult

**Comment by FIXTHISFASTERRR** [comment]
idk its popular here to comment about how patchnotes are wrong and to stop crying and provide real proof, if i didnt say it the 2 amerifags would anyway

**Comment by shmi11** [comment]
Well I found a bug, I am lvl 68 warrior and I thought the devs should know as no one has mentioned it. Sweeping strikes is so important for warriors to kill multiple targets, and it is painful to waste a global on execute when it does no bounce damage. Better off cleaving mobs down.

**Comment by FIXTHISFASTERRR** [comment]
u have to find a tbc video of exactly your same race class lvl, exact zone spot hitting exact mob, with exact same framerates and latency ( to make  sure the proof is real and not fake like patchnotes) where sweeping strike behaves as u say, -Brasso  - Tedys

**Comment by shmi11** [comment]
What about common sense? sweeping strikes should jump any damaging melee attack like it says on the tooltip, why must execute do 0 bounce damage if the other target is above 20%? Blizzard nerfed execute jumping with sweeping strikes to do normal melee swing damage instead of execute damage.

Well as long as they fix the sweeping strikes + whirlwind I guess it's at least something...

**Comment by wtRCH** [comment]
It was already reported and confirmed that if Execute under Sweeping Strikes effect is used on the target below 20% and naerby target is above 20% of the health, it will get normal melee swing instead of execute.

Duplicate.
