### ISSUE TITLE
Mind Flay Latency Issue

### ISSUE THREAD

**Issue by jakeoff** [Atlantiss/NetherwingBugtracker#4406]
[//]: # (Enclose links to things related to the bug using http://wowhead.com or any other TBC database.)
[//]: # (You can use screenshot ingame to visual the issue.)
[//]: # (Write your tickets according to the format:)
[//]: # ([Quest][Azuremyst Isle] Red Snapper - Very Tasty!)
[//]: # ([NPC] Magistrix Erona)
[//]: # ([Spell][Mage] Fireball)
[//]: # ([Npc][Drop] Ghostclaw Lynx)
[//]: # ([Web] Armory doesnt work)
[//]: # (To find server revision type `.server info` command in the game chat.)

**Description**: Mind flay will sometimes overwrite the original cast with a higher latency re-cast, resulting in a Mind Flay cast with artificial latency (this bug happens when not lagging as well), although the latency added on to the channel is real and affects the timing of the ticks if you track them via the cast bar. This bug only recently started happening with one of the recent updates earlier today. This is not an issue with the addon itself, as this was not happening until today.

**Current behaviour**: https://gyazo.com/8c92ae01ade10fd3d4bddd2898e18088 - Notice how as soon as I cast the first time, the latency is ~100 and then a millisecond later it spikes and resets the channel.

**Expected behaviour**: Mind Flay channel should not reset itself with higher latency.

**Server Revision**:

**Comment by Godmatik** [comment]
Fixed a long time ago with the channeled spells fix
