### ISSUE TITLE
[npc][stealth] Stealthed mobs way too high stealth levels

### ISSUE THREAD

**Issue by knasen88** [Atlantiss/NetherwingBugtracker#441]
[//]: # (Enclose links to things related to the bug using http://wowhead.com or any other TBC database.)
[//]: # (You can use screenshot ingame to visual the issue.)
[//]: # (Write your tickets according to the format:)
[//]: # ([Quest][Azuremyst Isle] Red Snapper - Very Tasty!)
[//]: # ([NPC] Magistrix Erona)
[//]: # ([Spell][Mage] Fireball)
[//]: # ([Npc][Drop] Ghostclaw Lynx)
[//]: # ([Web] Armory doesnt work)

**Description**: 

**Current behaviour**:
seems to be physically impossible to actually see a stealthed mob before it autoattacks you and it fades.
**Expected behaviour**: 
https://youtu.be/t9-p76s-G5k?t=8466
I vividly remember retail as being able to see stealthed mobs (even as non hunter) and their aggro range is also A LOT lower then regular mobs.
Track hidden gives +30 stealth detection (equal to 6 levels higher)

MORE PROOF
https://youtu.be/8lKFNczM-wY?list=PL49Ga_-r7iKkxrbckm9CkUhWzxqrOnw-n&t=1352
does not have track hidden activated, still sees them clearly AND they don't even aggro him while riding very close to them
**Server Revision**:

**Comment by totaemoeggerli** [comment]
I've encountered this problem with the shadow panther in swamp of sorrow https://www.wowhead.com/npc=768/shadow-panther
https://gfycat.com/SimpleSaneDutchshepherddog
**Server Revision:** 2124

**Comment by maxturtlesc2** [comment]
Problem still exists, most stealthed mobs can't be targeted at all.

**Comment by duzyizly** [comment]
fixed along with latest fixes?

**Comment by Tereneckla** [comment]
![image](https://user-images.githubusercontent.com/50233983/85199282-a1848a80-b2ee-11ea-86d1-d0d236f583ab.png)
6 yards to see the panther.

Detection range still is too low.
Had a level+2 mob just as https://youtu.be/t9-p76s-G5k?t=8466.
In the video it seems to be around 10-12 yards the panther gets targeted (enters hunter deadzone halfway to the panther)

**Comment by Wolffenstein** [comment]
Should be increased in rev 3395.
