### ISSUE TITLE
Dungeons kicking party members after crash and resetting instance.

### ISSUE THREAD

**Issue by Waddy333** [Atlantiss/NetherwingBugtracker#4410]
**Description**: 
Dungeons kicking party members out after disconnect and resetting instance.

**Current behaviour**:
During a server crash/restart upon login some party members will be kicked from the party and will be in an instance of their own with only their own unit frame at the top left whilst also being at the beginning of the fresh instance with all mobs back alive. For other party members the members with the issue stated previously will appear to be present visually by the unit frames at the top left in their party and will need to be kicked and re-invited to the party in order to rejoin the correct instance.

Some cases include all party members being reset to their own individual fresh instance at the beginning of the dungeon with no way to return to the original instance, resulting in all progress being lost. (While maintaining all items gained).

**Expected behaviour**: 
Server disconnects/crashes, log back in to the same party and same dungeon in same place with all progress maintained.

**Server Revision**: 
2666

**Comment by Bravehurt** [comment]
Can confirm and it's really annoying. This should be fix ASAP considering dungeons are the biggest thing that is affected by this. Don't want to make a group which takes 30 min + the time players get there, finish their stuff and then halfway get a crash, resulting in half the group leaving. Every SM as been a nightmare so far, worst reset I got so far was 2 packs away from Doan. Great server but these little bug adds up and starts impact on gameplay. I think we can all understand crashes happens, but this is the first server ive encounter this problem with, and I can say it's by far one of the worst. I feel bad for people doing dungeons like Arcatras and get the dungeon reset right in front of harbinger, id loose my shit.

**Comment by elenmerbau** [comment]
Still happening :<

**Comment by Godmatik** [comment]
Instance ID is being fully revamped, this (and other related issues) will be fixed when released this Monday.
