### ISSUE TITLE
Health funnel kills and revives players repeatedly when used at low hp

### ISSUE THREAD

**Issue by genetheparmesan** [Atlantiss/NetherwingBugtracker#4412]
[//]: # ([Spell][Warlock] Health Funnel)

**Description**:
If a warlock uses health funnel on their pet while low on health, it will kill the warlock and then his natural health regen will continue causing him to come back to life and then die again as health funnel is still channeling, repeats continuously until health funnel channel ends.

**Current behaviour**:
If a warlock uses health funnel on their pet while low on health, it will kill the warlock and then his natural health regen will continue causing him to come back to life and then die again as health funnel is still channeling, repeats continuously until health funnel channel ends.
**Expected behaviour**: 
Health funnel either fizzles or does not drop the player below 1 HP
**Server Revision**:

**Comment by Wolffenstein** [comment]
Fixed in rev 2671.
