### ISSUE TITLE
[Karazhan][NPC]Arcane Watchman#16485 runs towards the target it applies Overlord onto

### ISSUE THREAD

**Issue by Tenoutoften** [Atlantiss/NetherwingBugtracker#4413]
**Description/Current behaviour**: 
[[NPC]Arcane Watchman#16485](https://www.wowhead.com/npc=16485/arcane-watchman) runs towards the target it applies [[Spell]Overload#29768](https://www.wowhead.com/spell=29768/overload) onto for a brief moment before returning to the boss.

**Expected behaviour**: 
Expected to apply the debuff without running towards it, unless the target is further than 40 yards away - in which case it might have a check to cast on anyone else within range(Not sure)

**Server Revision**: 
2666

**Comment by Drayo** [comment]
https://github.com/Atlantiss/NetherwingBugtracker/issues/3160

**Comment by wtRCH** [comment]
@Wolffenstein

**Comment by Tereneckla** [comment]
Fixed
