### ISSUE TITLE
[Spell][Mage] Invisibility

### ISSUE THREAD

**Issue by killablink** [Atlantiss/NetherwingBugtracker#4414]
**Description**: Since the last Invisibility fix, you are now able to see people while invis, and it seems people are able to see you while invis.

https://gfycat.com/FamousConsiderateKestrel
The warlock didn't have detect invisibility yet he was able to see me.

**Current behaviour**:

**Expected behaviour**: Shouldn't be able to see non invis people and peeople shouldn't be able to see me without detect invis
**Server Revision**:  2666

**Comment by Wolffenstein** [comment]
Fixed in rev 2672.

**Comment by killablink** [comment]
#4869 Broke again
