### ISSUE TITLE
turning point/ deathblow to the legion

### ISSUE THREAD

**Issue by knasen88** [Atlantiss/NetherwingBugtracker#4417]
[//]: # (Enclose links to things related to the bug using http://wowhead.com or any other TBC database.)
[//]: # (You can use screenshot ingame to visual the issue.)
[//]: # (Write your tickets according to the format:)
[//]: # ([Quest][Azuremyst Isle] Red Snapper - Very Tasty!)
[//]: # ([NPC] Magistrix Erona)
[//]: # ([Spell][Mage] Fireball)
[//]: # ([Npc][Drop] Ghostclaw Lynx)
[//]: # ([Web] Armory doesnt work)
[//]: # (To find server revision type `.server info` command in the game chat.)

**Description**: 
this is the most ridiculous retarded version ive seen of this quest, its completely 100% undoable and when you finally manage to kill the  40man raidboss, socrathar bugs out and doesn't engage
OMEGA shit quest. don't try this one til you see it in changelog
quest id 10507

**Current behaviour**:

**Expected behaviour**: 

**Server Revision**:

**Comment by Tenoutoften** [comment]
Already reported. We managed to complete it, but it was difficult.
https://github.com/Atlantiss/NetherwingBugtracker/issues/4207

**Comment by knasen88** [comment]
our group "killed" the MC'ed draenai, he walks to socrates then the ""script"" bugs out and socrates just stands there.

**Comment by ttghnw** [comment]
B R O K E N

**Comment by Exorcista** [comment]
Broken again. NPC that starts event NEVER spawned for our grp in a timelapse of 1hr yes. 1 hr wasted. And yet this issue is abandoned??

**Comment by Easyfraggy** [comment]
You are posting in duplicate thread thats why it's closed go to the real one #4207
