### ISSUE TITLE
[NPC][22016 Eclypsion Soldier/22017 Spellbinder] Spawns are missing and spawn rate is slower.

### ISSUE THREAD

**Issue by tutuma499** [Atlantiss/NetherwingBugtracker#4418]
Description:
Some Eclipsion Spellbinder and soldiers spawns are missing (https://i.imgur.com/H3aTrI7.jpg) and the remaining eclipsion mobs spawn rate are slower since the server restart to fix execute ability.
12 min apart screenshots (https://i.imgur.com/1t956aA.jpg and https://i.imgur.com/QrBFjg6.jpg)

Expected behaviour:
The missing mobs can be seen in this video https://youtu.be/uvwO-6dpRpg?t=120

**Comment by tutuma499** [comment]
fixed after [2675] server restart

**Comment by tutuma499** [comment]
problem came after the [2676] server crash which happened few minutes after the update

**Comment by tutuma499** [comment]
It seems like if the Eclypsion mobs are dead when a server crash occur they won't respawn until the server restart.

**Comment by The14me** [comment]
Server rev.3460 it work fine.Mobs respawn in 10 min after kill without restar/crash.
Can be closed.
