### ISSUE TITLE
limited vendor recipes was a misstake

### ISSUE THREAD

**Issue by knasen88** [Atlantiss/NetherwingBugtracker#4419]
[//]: # (Enclose links to things related to the bug using http://wowhead.com or any other TBC database.)
[//]: # (You can use screenshot ingame to visual the issue.)
[//]: # (Write your tickets according to the format:)
[//]: # ([Quest][Azuremyst Isle] Red Snapper - Very Tasty!)
[//]: # ([NPC] Magistrix Erona)
[//]: # ([Spell][Mage] Fireball)
[//]: # ([Npc][Drop] Ghostclaw Lynx)
[//]: # ([Web] Armory doesnt work)
[//]: # (To find server revision type `.server info` command in the game chat.)

**Description**: 
https://i.imgur.com/QsevgfS.png
i think picture speaks for itself, the only thing you promote by having this retarded oversight left by blizzard on dead server tier respawns are that people will do anything to get them and the absolute NEED people have for them makes more oppurtunist cunts camp the recipes to sell on AH. It's already put in motion where they roll in with pre-made macros to buy the correct item spamming the vendor at the interval they're restocked. You won't get this item unless you buy it on auction house. Is this something that's "blizzlike"?

at LEAST make them fucking dynamic respawn.

**Server Revision**: 
2738

**Comment by ircfelix** [comment]
How is that bugged? Your report is a comlaint, but no bug report.

However, to support your argument, what would make sense, would be to increase the respawn timer, since original TBC realms were designed for ~2k players, but wie habe 5-6k players. Thus it would make sense to increase the respawn time.

Regardless of what the Netherwing staff will do, I recommend you to check out the Arcanoweave set, which is a viable alternative to the Imbued Netherweave robe.

**Comment by Jalapan** [comment]
To increase its spawnrate with 2x seems reasonable due to how high pop this server has. Same goes with every limited recepie

**Comment by Desst** [comment]
having problems with runed arcanite rod recipe form moonglade... I saw some level 1 chars near the vendor, just saying

**Comment by Drayo** [comment]
Additionally, back in the day the casual pop was way higher, not this many players immediately went for this stuff. They also did not "race" for the endgame content this much so even 3x respawns would most likely not be entirely adequate if one wants to recreate it as it was back then.

**Comment by Evolvee** [comment]
bugtracker is a place for bugs only, post suggestions on forum or discord

if u find some level 1/etc. camping players near limited vendor report them and we will ban them
