### ISSUE TITLE
Quest, Ashenvale, Stonetalon Standstill

### ISSUE THREAD

**Issue by Erodraeda** [Atlantiss/NetherwingBugtracker#442]
[//]: # (Enclose links to things related to the bug using http://wowhead.com or any other TBC database.)
[//]: # (You can use screenshot ingame to visual the issue.)
[//]: # (Write your tickets according to the format:)
[//]: # ([Quest][Azuremyst Isle] Red Snapper - Very Tasty!)
[//]: # ([NPC] Magistrix Erona)
[//]: # ([Spell][Mage] Fireball)
[//]: # ([Npc][Drop] Ghostclaw Lynx)
[//]: # ([Web] Armory doesnt work)

**Description**: 
In the quest, you are supposed to scout a place (just walk on a gazebo on the little island). The scout part is only getting credit when you finish the kill part of the quest.
**Current behaviour**:
https://clips.twitch.tv/GrossConcernedHamsterBigBrother
**Expected behaviour**: 
Get credit for it when you walk on the gazebo, not completing the kill part of the quest.
**Server Revision**:

**Comment by Evolvee** [comment]
it works for me:

![image](https://user-images.githubusercontent.com/1942409/46027668-b36fd400-c0ee-11e8-84b4-3f2317c35356.png)


if i dont step into the gazebo, im not getting full quest complete credit


when i step inside, i get it:
![image](https://user-images.githubusercontent.com/1942409/46027697-c7b3d100-c0ee-11e8-905a-cc7ea65d19d6.png)

**Comment by manslaughter** [comment]
If you enter the gazebo, then get your kills, you will get completion of the scouting objective as soon as you get your last kill.

**Comment by Retinus** [comment]
server rev 2094

Same issue with [#875](https://github.com/Atlantiss/NetherwingBugtracker/issues/875)

**Comment by duzyizly** [comment]
Works for me, rev 3390 ptr.

**Comment by Tereneckla** [comment]
You misunderstood the problem.
![image](https://user-images.githubusercontent.com/50233983/85148279-3d12ee00-b250-11ea-8302-4af6904bffb2.png)
In the gazebo, quest credit for scouting the gazebo not given (according to quest log)

https://youtu.be/JVCQiMIqJa0?t=219
Gets it the moment he walks into the gazebo, without having killed 12 elementals.

**Comment by duzyizly** [comment]
Oh.. Well then, there's two more quests with similar conditions, that works exaclty the same as Stonetalon Standstill at this moment (tested yesterday so probably rev 3390).
https://tbcdb.com/?quest=6421
https://tbcdb.com/?quest=5156

**Comment by Wolffenstein** [comment]
Fixed in rev 3391.
