### ISSUE TITLE
Redoubt Paladin Protection Tree Talent

### ISSUE THREAD

**Issue by SalemSailor** [Atlantiss/NetherwingBugtracker#4420]
The Redoubt talent in the first row of protection for paladins only lasts 5 seconds instead of the 10 seconds it should last when it procs.

**Comment by Tenoutoften** [comment]
"lasts 10 sec or 5 blocks" maybe you blocked 5 attacks and it expired?

**Comment by Wolffenstein** [comment]
Invalid.
