### ISSUE TITLE
Black Morass Aeonus

### ISSUE THREAD

**Issue by Bzmode** [Atlantiss/NetherwingBugtracker#4422]
**Current behaviour**: 
1. Aeonus stops breaking the shield if you hunter's mark him
2. Aeonus' stun has DR

**Expected behaviour**: 
The stun should not have DR
https://www.youtube.com/watch?v=ESLBWXB3LYs
you can see the stun last the same length each time

**Comment by Wolffenstein** [comment]
Fixed in rev 3104.
