### ISSUE TITLE
Healing someone elses warlock pet stuck in combat

### ISSUE THREAD

**Issue by Sublux9** [Atlantiss/NetherwingBugtracker#4423]
[//]: # (Enclose links to things related to the bug using http://wowhead.com or any other TBC database.)
[//]: # (You can use screenshot ingame to visual the issue.)
[//]: # (Write your tickets according to the format:)
[//]: # ([Quest][Azuremyst Isle] Red Snapper - Very Tasty!)
[//]: # ([NPC] Magistrix Erona)
[//]: # ([Spell][Mage] Fireball)
[//]: # ([Npc][Drop] Ghostclaw Lynx)
[//]: # ([Web] Armory doesnt work)
[//]: # (To find server revision type `.server info` command in the game chat.)

**Description**:  While playing a priest leveling with a warlock, if i heal or bubble the warlocks pet - i am stuck in combat permanently, and it happens to others who group and then heal the pet as well, it doesn't matter if the warlocks pet is still in combat.

**Current behaviour**: it locks you in combat regardless of if you are or not, because you healed a warlock pet while it was in combat, the only way to get out of combat, is if the warlock dismisses his pet - this goes away, but that is quite inconvenient.

**Expected behaviour**: To not have to dismiss and resummon a warlock pet, because it sticks his ally in combat because they have healed the warlock pet, during combat.

**Server Revision**:  just getting this bug to not happen any more (:

**Comment by Wolffenstein** [comment]
Fixed in rev 2772.
