### ISSUE TITLE
Heavy Clefthoof Set is missing a LARGE amount of armor!

### ISSUE THREAD

**Issue by MurlNW** [Atlantiss/NetherwingBugtracker#4426]
**Description**: 
Heavy Clefthoof Set has far less armor rating than it is supposed to.
**Current behaviour**:
Currently the chest has 290 armor rating and 52 stamina with 28 defense rating.
**Expected behaviour**: 
http://db.hellfire-tbc.com/?item=25689  -- Shows chest with 500 armor, 45 stamina, and 24 defense.
**Server Revision**:

**Comment by Evolvee** [comment]
2.0 itemization
