### ISSUE TITLE
Heroic dungeons not resetting 

### ISSUE THREAD

**Issue by gurtash** [Atlantiss/NetherwingBugtracker#4427]
**Description**: 
heroics dungeons are the same lockout as the previous day not allowing people to clear them again
**Current behaviour**:
heroic dungeons are not resetting 
https://i.imgur.com/Unxjbw4.png
**Expected behaviour**: 
heroic dungeons should reset daily
**Server Revision**: 
2666

**Comment by Tenoutoften** [comment]
Confirm, didn't play in Gurtash groups but we also experienced this

**Comment by Tereneckla** [comment]
rev 3236 Heroics reset at 9am ST
