### ISSUE TITLE
Rogue: auto-attack bug

### ISSUE THREAD

**Issue by agraff16** [Atlantiss/NetherwingBugtracker#4429]
It only happens very rarely. this could be because i don't fight multiple adds very often? Seems like it happens when switching targets.

I can send a better video if this isn't good enough, pm me on discord "outee"

**Description**: Auto-attack does not work sometimes

**Server Revision**: 
netherwing

[intro4.zip](https://github.com/Atlantiss/NetherwingBugtracker/files/2780214/intro4.zip)

**Comment by agraff16** [comment]
[intro5.zip](https://github.com/Atlantiss/NetherwingBugtracker/files/2780397/intro5.zip)
happened again

**Comment by Easyfraggy** [comment]
https://github.com/Atlantiss/NetherwingBugtracker/issues/2795
