### ISSUE TITLE
[quest][hillsbrad] souvenirs of death

### ISSUE THREAD

**Issue by knasen88** [Atlantiss/NetherwingBugtracker#443]
[//]: # (Enclose links to things related to the bug using http://wowhead.com or any other TBC database.)
[//]: # (You can use screenshot ingame to visual the issue.)
[//]: # (Write your tickets according to the format:)
[//]: # ([Quest][Azuremyst Isle] Red Snapper - Very Tasty!)
[//]: # ([NPC] Magistrix Erona)
[//]: # ([Spell][Mage] Fireball)
[//]: # ([Npc][Drop] Ghostclaw Lynx)
[//]: # ([Web] Armory doesnt work)

**Description**: 
skulls have exceedingly low droprate
**Current behaviour**:
ive completed 2 battle for hillsbrad quests and some grind (30+ mobs) and gotten 3 skulls
**Expected behaviour**: 
wowhead comment between 25-50%
Keeping it at current rate is possible i guess, if you also fix the proper minimum level for the quest i suppose. (so you get some durnholde skulls)
**Server Revision**:

**Comment by aresbrutus** [comment]
They are already set to 30% in the database right now. Maybe you have gotten VERY unlucky?
