### ISSUE TITLE
[Dungeon] Old Hillsbrad (normal) - Some packs are level 70-71

### ISSUE THREAD

**Issue by Desst** [Atlantiss/NetherwingBugtracker#4430]
**Description**: 
There are mobs 70 and 71 lvl in front of the castle and during the thrall event in tarren mill. 

**Expected behaviour**: 
Levels should be somewhat 67 in normal

**Server Revision**: 
2666

**Comment by wtRCH** [comment]
@Wolffenstein

**Comment by Tereneckla** [comment]
It's the lookouts only, so #3577
