### ISSUE TITLE
no rage generation while sitting

### ISSUE THREAD

**Issue by antikiller69** [Atlantiss/NetherwingBugtracker#4432]
[//]: # (Enclose links to things related to the bug using http://wowhead.com or any other TBC database.)
[//]: # (You can use screenshot ingame to visual the issue.)
[//]: # (Write your tickets according to the format:)
[//]: # ([Quest][Azuremyst Isle] Red Snapper - Very Tasty!)
[//]: # ([NPC] Magistrix Erona)
[//]: # ([Spell][Mage] Fireball)
[//]: # ([Npc][Drop] Ghostclaw Lynx)
[//]: # ([Web] Armory doesnt work)
[//]: # (To find server revision type `.server info` command in the game chat.)

**Description**: u should get rage when u sit since u receive crit strike, druids mostly use this as tanking
(also blood craze and enrage do not proc from sitting down) atm u get zero rage from sitting down and getting critted, it does not register it

**Current behaviour**: does not give rage

**Expected behaviour**: should give rage

**Server Revision**:

**Comment by femdead** [comment]
blizzlike
