### ISSUE TITLE
Enemy HP not being displayed as a %

### ISSUE THREAD

**Issue by Ituh** [Atlantiss/NetherwingBugtracker#4433]
Enemy HP should be displayed as a % value and not as an integer.

How it works:
Currently enemy HP is displayed as an exact value. This was working correctly since launch but broke recently.
https://imgur.com/a/qXcJS6Q

How it should work:
Enemy HP should be displayed as a % of their total health.

Source (you should point out proofs of your report, please give us some source):
Many people believe this was changed in patch 2.3 http://wowwiki.wikia.com/wiki/Patch_2.3.0
however, the change in patch 2.3 only applies to friendly units, not enemies.
"There are now options for displaying health and mana values on your health/mana bars for you/your party/your target and to display that information either as percentages or as numbers."

If you look at https://wow.gamepedia.com/Patch_3.0.2_(undocumented_changes)
"Health values appear on targets; mobs, boss, NPC, or player (regardless of group or faction)." It is clear that "regardless of group or faction" means that in patch 3.0.2 they changed this to be an integer. This is a change that only went into effect during WotLK, not TBC.

Video proof: https://www.youtube.com/watch?v=QyTyNaiEJKs&feature=youtu.be&t=8m15s
You can see the priest targeting an enemy and his health is displayed as a %, then he switches to a friendly target and their health is displayed as an integer.

**Comment by FIXTHISFASTERRR** [comment]
one of the bugs that are better than not bugged lol

**Comment by Wolffenstein** [comment]
I only disabled this for players because there were issues with incorrect display. It's enabled for mobs and pets of other players.

**Comment by Ituh** [comment]
Only temporary I hope :)?

**Comment by Shnoofeen** [comment]
As far as I was aware from patch 2.4.3 all faction based enemies will show their health plates with exact values, and all enemy mobs will display their health plates as percentages.

From what I've seen from my own client, it is functioning as I remember it did. 

Showing source videos may not be valid, as there are interface options to force all plates to display percentage values. 

and you kind of disproved what you're saying with this note;

There are now options for displaying health and mana values on your health/mana bars for you/your party/your target and to display that information either as percentages or as numbers.

"YOUR TARGET" being the key words there.

**Comment by Ituh** [comment]
Read the 3.0.2 patch notes
"Regardless of faction" being the key word there. It's extremely clear that the intended behavior I'd only to show friendly party members HP as exact values.
In the video they have that interface option enabled, you can watch them change target to an enemy player and their HP is no longer displayed as a value.

Try reading the proof before saying it's wrong.

**Comment by Shnoofeen** [comment]
Why would I read 3.0.2 notes when the client is 2.4.3 ? 

I simply stated from what patch note they had put in it was kind of dis-providing what they said in the first place "for you/your party/your target". 

The server is running based off client 2.4.3, so anything applied after 2.3  to 2.4.3 would be TRUE on this server. 

and as I stated previously, this appears to me to be working the way that it originally worked on the TBC client in 2007!

**Comment by Ituh** [comment]
Because in 3.0.2 they changed it so that you can see enemy's exact HP regardless of faction. That means that in 2.3 and 2.4.3 you could NOT see enemy hp even with the interface option enabled. It only showed friendly targets exact hp in 2.4.3.

Seeing enemy hp as a value was never applied in tbc, that's the whole point of looking at the 3.0.2 noted because that function was introduced in 3.0.2. And like you said this is 2.4.3 so we should not see enemy hp.

It's clear from the proof that "your target" only applies to friendly targets. Do you really think vague wording in patch notes is better proof than actual gameplay from TBC? Wolf even mentioned above they only changed it for players because of issues with the display. Look at the proof unless you can't admit you're wrong.

**Comment by Shnoofeen** [comment]
![owned](https://user-images.githubusercontent.com/46903596/51678594-b0b9b880-1fd4-11e9-978b-bac9e2333821.jpg)


There is your fact, there is your proof screenshot taken from TBC era. 

Does that look like a friendly target to you? 

Now put your toys back in your pram!

**Comment by Shnoofeen** [comment]
![proofs](https://user-images.githubusercontent.com/46903596/51678804-33427800-1fd5-11e9-9d60-412ab539ee86.jpg)

and just before you say it was from some private server.

**Comment by Shnoofeen** [comment]
![heal then dead](https://user-images.githubusercontent.com/46903596/51679101-e7dc9980-1fd5-11e9-8993-8970fd0fd669.JPG)

and this just to show that my interface is clean of addons before you try pulling that one.

**Comment by Ituh** [comment]
In your first screenshot it shows %hp and exact value, that's an addon. It doesn't even fit in the blizzard default unit frame lol. See how in your 2nd screenshot you only see the exact value?

Your interface is obviously not clear of addons, look in the lower left of picture 1 you have a dps addon lmao

**Comment by Shnoofeen** [comment]
That is how it was displayed on the client. Please show me YOUR screenshot which proves otherwise. 

My UI is free on addons, it uses ONLY quartz and minimap. Two addons which add ZERO functionality to display plates. Others are atlas loot and wim, but I suppose you're going to tell me those contribute to it now. Oh yeah and RECOUNT, yes this displays health text.....

The second screenshot ONLY shows my OWN nameplate, which shows value text. Also which I just used as a reference so you could see I am not using any addons such as bartender, peralxframes, lvu (lua) whatever it is, all of this which add functionality to the plate bars. That was the purpose of that, to show my interface was clean of addons, which it is because my interface is default blizzard UI. 

Why exactly are you that up your butt about this? There are many addons available that do this for you anyway, so honestly I don't get what your fuss is about? 

I wont bother replying anymore, I have added enough information and relevance to back it up. At this point it just feels like you're directing your anger at the first person that doesn't share your opinion about it.

**Comment by nullfoxh** [comment]
@Shnoofeen Lmao, even the health font is different on your screenshot. There's no need to debate this either as everyone knows it's not supposed to display exact values.

**Comment by Ituh** [comment]
There's no anger here, you are showing no actual proof, meanwhile I've given you video proof, and even proof down to the very patch notes these changes were made in. I will explain again for you.

In 2.3 blizzard added the interface option to display exact HP values to friendly targets, group members, etc. It was poorly worded but this did not include enemies. In 3.0.2 they added this function to enemies and it is pretty explicit in the patch notes ("regardless of faction") which you refuse to read for some reason.

In your first screenshot, the font is different on your  target (enemy) and it doesn't even fit the frame correctly. Now compare that to your party members health in your second screenshot. It displays as an exact value because you have that option selected but it's only for friendly targets.

See how it is the same font, fits the bar, and shows ONLY the exact value? There is no interface option to show both %hp and exact value hp in tbc. You can boot up your client right now to see this. You are 100% using an addon to display enemy hp in your first screenshot even if you dont realize it.

What you are showing in your screenshots doesn't prove anything and directly contradicts what you are claiming. There's no need to argue about something you don't understand, the proof is in the OP if you want to understand

**Comment by wtRCH** [comment]
Invalid.
