### ISSUE TITLE
WF still only provides one extra attack

### ISSUE THREAD

**Issue by karliva** [Atlantiss/NetherwingBugtracker#4434]
[//]: # (Enclose links to things related to the bug using http://wowhead.com or any other TBC database.)
[//]: # (You can use screenshot ingame to visual the issue.)
[//]: # (Write your tickets according to the format:)
[//]: # ([Quest][Azuremyst Isle] Red Snapper - Very Tasty!)
[//]: # ([NPC] Magistrix Erona)
[//]: # ([Spell][Mage] Fireball)
[//]: # ([Npc][Drop] Ghostclaw Lynx)
[//]: # ([Web] Armory doesnt work)
[//]: # (To find server revision type `.server info` command in the game chat.)

**Description**: 
Windfury weapon only hitting once
**Current behaviour**:
Windfury weapon only hitting once pr 21/01/2019 21:51 servertime
**Expected behaviour**: 
Windfury Weapon hitting twice

**Server Revision**:

**Comment by Wolffenstein** [comment]
Not live yet.

**Comment by karliva** [comment]
thx
