### ISSUE TITLE
Everytime I log off or disconnect my character disappears from the guild.

### ISSUE THREAD

**Issue by Bloke12** [Atlantiss/NetherwingBugtracker#4435]
[//]: # (Enclose links to things related to the bug using http://wowhead.com or any other TBC database.)
[//]: # (You can use screenshot ingame to visual the issue.)
[//]: # (Write your tickets according to the format:)
[//]: # ([Quest][Azuremyst Isle] Red Snapper - Very Tasty!)
[//]: # ([NPC] Magistrix Erona)
[//]: # ([Spell][Mage] Fireball)
[//]: # ([Npc][Drop] Ghostclaw Lynx)
[//]: # ([Web] Armory doesnt work)
[//]: # (To find server revision type `.server info` command in the game chat.)

**Description**: Everytime I log off or disconnect my character disappears from the guild.

**Current behaviour**: Everytime I log off or disconnect my character disappears from the guild.

**Expected behaviour**: Player should never leave guild unless they leave guild manually or are kicked.

**Server Revision**:

**Comment by PeeCat** [comment]
This is happening to me, except when I log it kicks me from my guild and puts me in a old guild i quit previously. Send help.

**Comment by Sawin** [comment]
the same thing happens to me

**Comment by Jhn3712** [comment]
The same happends to me still aswell, dont think yesterdays "fix" seemed to fix anything.

**Comment by Bromidious** [comment]
same
