### ISSUE TITLE
Tab targetting disables auto-attack

### ISSUE THREAD

**Issue by Bloke12** [Atlantiss/NetherwingBugtracker#4436]
[//]: # (Enclose links to things related to the bug using http://wowhead.com or any other TBC database.)
[//]: # (You can use screenshot ingame to visual the issue.)
[//]: # (Write your tickets according to the format:)
[//]: # ([Quest][Azuremyst Isle] Red Snapper - Very Tasty!)
[//]: # ([NPC] Magistrix Erona)
[//]: # ([Spell][Mage] Fireball)
[//]: # ([Npc][Drop] Ghostclaw Lynx)
[//]: # ([Web] Armory doesnt work)
[//]: # (To find server revision type `.server info` command in the game chat.)

**Description**: When tab targetting to a new mob, melee auto-attacks stops and does not restart until you unselect a mob with 'Esc' and reselect with 'Right Click'. The character remains in the 'auto-attack' stance misleading the player they are auto-attacking

**Current behaviour**: When tab targetting to a new mob, melee auto-attacks stops and does not restart until you unselect a mob with 'Esc' and reselect with 'Right Click'. The character remains in the 'auto-attack' stance misleading the player they are auto-attacking.

**Expected behaviour**: 

**Server Revision**:

**Comment by agraff16** [comment]
[intro4.zip](https://github.com/Atlantiss/NetherwingBugtracker/files/2780701/intro4.zip)

**Comment by Zarant** [comment]
Tab targeting is busted, might be somewhat related to #4241

**Comment by nullfoxh** [comment]
Related with/duplicate of:
https://github.com/Atlantiss/NetherwingBugtracker/issues/4429
https://github.com/Atlantiss/NetherwingBugtracker/issues/4436
https://github.com/Atlantiss/NetherwingBugtracker/issues/4241
https://github.com/Atlantiss/NetherwingBugtracker/issues/4211
https://github.com/Atlantiss/NetherwingBugtracker/issues/2795

**Comment by Easyfraggy** [comment]
Duplicate as described above.
