### ISSUE TITLE
Parched Hydra Heat Wave

### ISSUE THREAD

**Issue by femdead** [Atlantiss/NetherwingBugtracker#4437]
The Debuff States -35% chance to hit, but testing it it seems like -100% or close to. Unable to land a single hit even when i deliberately take the debuff and spam abilities

**Comment by Ebeebe123** [comment]
Can confirm after getting this debuff while doing that quest i was unable to hit at all

**Comment by numiee** [comment]
are we getting any updates on this? still to this date bugged...

**Comment by Aipa01** [comment]
Also can confirm. Still says 35% but is actually 100%

**Comment by Wolffenstein** [comment]
Fixed in rev 3194.
