### ISSUE TITLE
Not showing SP for Prot Paladin low levels

### ISSUE THREAD

**Issue by QueefCatcher** [Atlantiss/NetherwingBugtracker#4440]
![wowscrnshot_012119_160824](https://user-images.githubusercontent.com/46909490/51504659-f12bf300-1d96-11e9-8293-6e43d8496080.jpg)
![wowscrnshot_012119_160826](https://user-images.githubusercontent.com/46909490/51504661-f38e4d00-1d96-11e9-96d2-2456a921496d.jpg)

[//]: # (Enclose links to things related to the bug using http://wowhead.com or any other TBC database.)
[//]: # (You can use screenshot ingame to visual the issue.)
[//]: # (Write your tickets according to the format:)
[//]: # ([Quest][Azuremyst Isle] Red Snapper - Very Tasty!)
[//]: # ([NPC] Magistrix Erona)
[//]: # ([Spell][Mage] Fireball)
[//]: # ([Npc][Drop] Ghostclaw Lynx)
[//]: # ([Web] Armory doesnt work)
[//]: # (To find server revision type `.server info` command in the game chat.)

**Description**: 
Lower level Prot pally. Have two items totally +17 SP, but the SP is not showing on character pane
**Current behaviour**:

**Expected behaviour**: 

**Server Revision**:

**Comment by killablink** [comment]
There is no bonus dmg on healing items until patch 2.3 I believe. You have to use an addon to see the actual real stats.
