### ISSUE TITLE
[NPC] [PvP] [Quest] Attacking NPC Engineer "Spark" Overgrind flags player

### ISSUE THREAD

**Issue by Spaztick** [Atlantiss/NetherwingBugtracker#4443]
**Description**: 
[NPC] [PvP] [Quest] Attacking NPC Engineer "Spark" Overgrind for the quest Show Gnomercy flags player for PvP.

**Current behaviour**:
thing

**Expected behaviour**: 
should not thing

**Server Revision**: 
2676

![flag](https://user-images.githubusercontent.com/29140342/51514032-a086bb00-1dd3-11e9-8dbd-87490565f4d4.jpg)

**Comment by Tereneckla** [comment]
Fixed
