### ISSUE TITLE
Crafting recipes - Not restocking on vendors

### ISSUE THREAD

**Issue by Draklian** [Atlantiss/NetherwingBugtracker#4444]
http://wowwiki.wikia.com/wiki/Limited_quantity_recipes

I didnt go through the entire list, but I am referencing specifically the LW recipe "Pattern: Heavy Knothide Leather" 

This is definitely not restocking correctly. I checked it after a server crash (I was standing at the vendor when the server crashed and logged in right away and no one else was there before or after the crash) as well as after an actual restart and never saw it. I've spent several hours stalking this npc "Cro Threadstrong," Please **verify** this is working correctly.

**Comment by Ravyd** [comment]
> That is already happening.

I'm well aware. This was common practice on felmyst. Here's a screenshot

![corruption](https://user-images.githubusercontent.com/29013305/51508763-ec296c80-1db3-11e9-9f16-1b5d9c07066a.jpg)

**Comment by Wolffenstein** [comment]
It is working and no, the recipes don't restock after crash/restart.

**Comment by Draklian** [comment]
I am curious as to what your source is for the restock time on these. I am currently sitting at hte vendor for over 1.5 hours and its not there.
