### ISSUE TITLE
[Spell][Paladin] Greater Blessing of Sanctuary Rank 1 not available at lvl 60

### ISSUE THREAD

**Issue by Barry031** [Atlantiss/NetherwingBugtracker#4445]
[//]: # (Enclose links to things related to the bug using http://wowhead.com or any other TBC database.)
[//]: # (You can use screenshot ingame to visual the issue.)
[//]: # (Write your tickets according to the format:)
[//]: # ([Quest][Azuremyst Isle] Red Snapper - Very Tasty!)
[//]: # ([NPC] Magistrix Erona)
[//]: # ([Spell][Mage] Fireball)
[//]: # ([Npc][Drop] Ghostclaw Lynx)
[//]: # ([Web] Armory doesnt work)
[//]: # (To find server revision type `.server info` command in the game chat.)

**Description**: 
Greater Blessing of Sanctuary can not be learned at lvl 60

**Current behaviour**:
It says at the trainer i cant learn GBoS R1 cause it requires BoS R4 AND BoS R5.
![gbosr4](https://user-images.githubusercontent.com/24766765/51509953-50235380-1dfb-11e9-85d5-206644a4dff8.png)
![bosr4](https://user-images.githubusercontent.com/24766765/51509937-40a40a80-1dfb-11e9-9e0a-46b63f29c1f6.png)

**Expected behaviour**: 
GBoS R1 should be available if you have learned BoS R4 and are lvl 60. It should not require BoS R4 and BoS R5. 
BoS R5 you get at lvl 70 and are equal to GBoS R2.

**Server Revision**: 
2676

**Comment by Drayo** [comment]
This one is a bit weird. I'm using the same Trainer as OP.

![image](https://user-images.githubusercontent.com/23145811/88245818-d2aefc80-cc98-11ea-947f-bd348af7bf9a.png)
The Tooltip is fine for me, it requires Rank 4 which is correct.

![image](https://user-images.githubusercontent.com/23145811/88245859-f8d49c80-cc98-11ea-83e6-8b5ac2f87891.png)
I am level 60, and thus cannot learn Rank 5, which is also correct.

![image](https://user-images.githubusercontent.com/23145811/88245885-130e7a80-cc99-11ea-8a00-5695f211dc8a.png)
**But when I learn GBoS Rank 1 it also teaches me BoS Rank 5 which is a level 70 Spell.**

I could not find any mention of this anywhere. It also kind makes no sense.

Rev: 3483

**Comment by Godmatik** [comment]
It was fixed/resolved already, can close
