### ISSUE TITLE
Quest Item's Drop Rates are much lower than should be.

### ISSUE THREAD

**Issue by SalemSailor** [Atlantiss/NetherwingBugtracker#4449]
In the starting zone Draenei and Dwarf + Gnomes any quests where you pick up items for quests are way lower than I have encountered in the past on my main. Took me over 25 kills to get 6 manes for The Great Moongraze Hunt and over 50 to get 8 Wendigo Manes in The Grizzled Den. Making this report as I level (6 as of now).

**Comment by WillowWisp** [comment]
can confirm. zenn's bidding takes **literally forever** to complete even though only need 3x 0/3 items

**Comment by wtRCH** [comment]
@Shanghi
