### ISSUE TITLE
[Quest] Torek's Assault

### ISSUE THREAD

**Issue by manslaughter** [Atlantiss/NetherwingBugtracker#445]
**Description**: This is a quest for horde in south central Ashenvale.

**Current behaviour**: When Torek and his alllies reach the end of the silvering outpost, Duriel Moonfire and her allies appear, but quest completion is given immediately.

**Expected behaviour**: Quest is not completed until after Duriel Moonfire and her allies are defeated.

**Server Revision**: 2040

**Comment by xmesaj2** [comment]
fix in rev 2054
