### ISSUE TITLE
[Spell][Shaman] Grounding Totem

### ISSUE THREAD

**Issue by Perfecthandz** [Atlantiss/NetherwingBugtracker#4450]
**Description**: Grounding totem is destroyed upon redirecting ANY harmful spell.

**Current behaviour**: Spells like polymorph, counterspell, corruption, fear, etc. will destroy the totem after being swallowed up by the mechanic.

**Expected behaviour**: Only direct damaging spells should destroy the totem. Debuffs, displels, CC and other spells which do not have a direct instant damage mechanic should be taken down by the totem, maximum of one per 10 seconds. Totem should stay alive and waiting for a chance to absorb another spell, until either the timer runs out or a damaging spell is absorbed.

The Burning Crusade Patch 2.3.0 (2007-11-13): This totem is now immediately destroyed upon the first spell it redirects, rather than redirecting a spell every 10 seconds. 

Make of this patch note what you will.

**Comment by killablink** [comment]
Polymorph should destroy grounding totem. We are using 2.4.3 mechanics

**Comment by Shnoofeen** [comment]
Yeah sounds to me like it's functioning correctly.

**Comment by lynxzor** [comment]
#faq 
![image](https://user-images.githubusercontent.com/795881/51559309-7be51e80-1e79-11e9-9453-1bd33d3cfd0c.png)
