### ISSUE TITLE
[Profession] [Skinning] Loot Disappears if Inv is Full

### ISSUE THREAD

**Issue by OMEGALULW** [Atlantiss/NetherwingBugtracker#4451]
**Description**: Full inventory breaks skinning

**Current behaviour**: If your inventory is full when you skin a mob, closing the loot window prevents you from looting the leather

**Expected behaviour**: Leather is available to be looted afterwards if your inventory was full

**Server Revision**: 2676

Update: Only appears to be happening if you didn't kill the mob yourself

**Comment by The14me** [comment]
Rev.3460 Not an issue anymore.
Can be closed.
