### ISSUE TITLE
[Quest] [Stranglethorn Fever]

### ISSUE THREAD

**Issue by SSupra** [Atlantiss/NetherwingBugtracker#4452]
[//]: # (Enclose links to things related to the bug using http://wowhead.com or any other TBC database.)
[//]: # (You can use screenshot ingame to visual the issue.)
[//]: # (Write your tickets according to the format:)
[//]: # ([Quest][Azuremyst Isle] Red Snapper - Very Tasty!)
[//]: # ([NPC] Magistrix Erona)
[//]: # ([Spell][Mage] Fireball)
[//]: # ([Npc][Drop] Ghostclaw Lynx)
[//]: # ([Web] Armory doesnt work)
[//]: # (To find server revision type `.server info` command in the game chat.)

**Description**: Can not interract with Witch Doctor Unbagwa

**Current behaviour**:

**Expected behaviour**: 

**Server Revision**:

**Comment by DarthNekr0s** [comment]
revision 2719
witch doctor unbagwa should have a blue question mark allowing you to interact with him, giving him the quest item (gorilla fang) and summoning the waves of gorillas that lead to mokk the savage spawning (quest mob)
currently he is not able to be interacted with therefore you can't complete the quest

![wowscrnshot_012919_141706](https://user-images.githubusercontent.com/16113944/51883878-a3377080-23d0-11e9-8cf2-68c4d8e80842.jpg)

**Comment by zhuk90** [comment]
still bugged and no one cares

**Comment by Evolvee** [comment]
hopefully fixed in rev 2721
