### ISSUE TITLE
[Shaman] [Spell] Unleashed Rage

### ISSUE THREAD

**Issue by s2nratio** [Atlantiss/NetherwingBugtracker#4455]
[//]: # (Enclose links to things related to the bug using http://wowhead.com or any other TBC database.)
[//]: # (You can use screenshot ingame to visual the issue.)
[//]: # (Write your tickets according to the format:)
[//]: # ([Quest][Azuremyst Isle] Red Snapper - Very Tasty!)
[//]: # ([NPC] Magistrix Erona)
[//]: # ([Spell][Mage] Fireball)
[//]: # ([Npc][Drop] Ghostclaw Lynx)
[//]: # ([Web] Armory doesnt work)
[//]: # (To find server revision type `.server info` command in the game chat.)

**Description**: Lower Unleashed 

**Current behaviour**: Lower talented ranks of Unleashed Rage prevent maxed out ranks to overwrite. We tested it (because on some servers different ranks of unleashed rage stack) and the first one to trigger blocks the other trigger to overwrite with the higher value. 1st Shaman crits with 8% Unleashed Rage, the buff lasts for 10 secs. In this timeframe the crits of the other Shaman do not trigger his 10% Unleashed Rage, it can only happen when the buff from the first shaman ran out. 
Essentially if you have a shamn with enough crit and the crude spec of 1/5 unleashed rage it could ALWAYS block the talented 10% unleashed rage to happen. 

**Expected behaviour**: if you have two enhancement shaman in a group, one with 4/5 Unleashed Rage and one with 5/5 Unleashed Rage, the higher buff should overwrite the lesser one. 

**Server Revision**: 2676

**Comment by Godmatik** [comment]
Fixed in new aura branch update being released to live soon
