### ISSUE TITLE
[Item] Libram of Truth - Not applying the armor.

### ISSUE THREAD

**Issue by Mysstt** [Atlantiss/NetherwingBugtracker#4457]
[//]: # (Enclose links to things related to the bug using http://wowhead.com or any other TBC database.)
[//]: # (You can use screenshot ingame to visual the issue.)
[//]: # (Write your tickets according to the format:)
[//]: # ([Quest][Azuremyst Isle] Red Snapper - Very Tasty!)
[//]: # ([NPC] Magistrix Erona)
[//]: # ([Spell][Mage] Fireball)
[//]: # ([Npc][Drop] Ghostclaw Lynx)
[//]: # ([Web] Armory doesnt work)
[//]: # (To find server revision type `.server info` command in the game chat.)

**Description**: [Item] Libram of Truth is not applying the 110 armor to players.

**Current behaviour**: When equipped, Devotion aura (on the bar) has the added 110 armor, whilst the tooltip and the Character armor listed under Defenses does not.

**Expected behaviour**: The charter tab should show the increased armor value, and the increased armor value should actually apply to the Paladin and their whole party. (Unsure about the tooltips showing increases to aura's and other buffs).

**Server Revision**: 2676

**Comment by Tenoutoften** [comment]
Another libram also not working: https://github.com/Atlantiss/NetherwingBugtracker/issues/3460
This one is from Karazhan

**Comment by Tenoutoften** [comment]
https://github.com/Atlantiss/NetherwingBugtracker/issues/2409

**Comment by devo6969** [comment]
This works on the PTR. Tried with other players as well, works fine. (Have to reapply Devo aura once equiping libram to see the value increase)
(Without it on 1100 armor) https://i.imgur.com/BxQZZg4.jpg
(With it 1210 armor) https://i.imgur.com/cMr2fPW.jpg
