### ISSUE TITLE
[Megathread]Raid/Instance and daily reset time

### ISSUE THREAD

**Issue by Jalapan** [Atlantiss/NetherwingBugtracker#4458]
[//]: # (Enclose links to things related to the bug using http://wowhead.com or any other TBC database.)
[//]: # (You can use screenshot ingame to visual the issue.)
[//]: # (Write your tickets according to the format:)
[//]: # ([Quest][Azuremyst Isle] Red Snapper - Very Tasty!)
[//]: # ([NPC] Magistrix Erona)
[//]: # ([Spell][Mage] Fireball)
[//]: # ([Npc][Drop] Ghostclaw Lynx)
[//]: # ([Web] Armory doesnt work)
[//]: # (To find server revision type `.server info` command in the game chat.)

**Description**: 
Currently the raid and instance reset's are bugged, i know developers are aware so im creating this bug report so people can see it and adding all relevent information so devs can get it fixed with timers and such
**Current behaviour**:
Currently the raid and instance reset's are bugged, sometimes reset, sometimes never reset and so on.
**Expected behaviour**: 
Raid resets should be Wednesday  9AM CET 

Since Patch 1.9.0, instances are reset according to a fixed calendar. This was decided by Blizzard to be fairest to most and replaces the previous system of resetting raid instances based on the absence from the instance of the raid members. 

Raids:
Weekly resets on US realms occur at 8 AM Pacific Time, every Tuesday.
Weekly resets on EU realms occur at 9 AM Central European Time, every Wednesday

Daily Quests/Dugenons/Heroics

Unlike weekly resets, daily resets happen every morning so that the servers can reset everything that is of lower magnitude (quests, dungeons, NPCs), as opposed to for instance raids, which require weekly resets.

Daily resets on US realms occur at 8 AM Pacific Time.
Daily resets on EU realms occur at 9 AM Central European Time.

Sources:

https://www.wowhead.com/lockouts-and-resets-in-world-of-warcraft

http://wowreset.com/

**Comment by NFZmexizz** [comment]
Low level instance manual reset also aint work. We had to reparty to make it happen

**Comment by Tereneckla** [comment]
rev 3236 Heroics reset at 9am ST
Raids Tuesdays 9am ST
