### ISSUE TITLE
Guild Bank - Guild master unable to withraw money

### ISSUE THREAD

**Issue by MUTEant44** [Atlantiss/NetherwingBugtracker#4460]
[//]: # (Enclose links to things related to the bug using http://wowhead.com or any other TBC database.)
[//]: # (You can use screenshot ingame to visual the issue.)
[//]: # (Write your tickets according to the format:)
[//]: # ([Quest][Azuremyst Isle] Red Snapper - Very Tasty!)
[//]: # ([NPC] Magistrix Erona)
[//]: # ([Spell][Mage] Fireball)
[//]: # ([Npc][Drop] Ghostclaw Lynx)
[//]: # ([Web] Armory doesnt work)
[//]: # (To find server revision type `.server info` command in the game chat.)

**Description**: 
Using a guild master character I'm unable to withdraw money from Guild Bank.

**Current behaviour**:
A Guild Master char is unable to withdraw money from gBank (withdraw button grayed out) despite amount available saying "unlimited" .Neither is able to use it for repairs. Lower ranks with proper permissions can still withdraw money/repair.
Screenshots below are taken with:
- a GM char (withdraw inactive, possible to buy a tab) and
- an officer char with permissions for guild bank set (no tabs to see, can withdraw money);

**Expected behaviour**: 
Guild Master character should have  guild bank access without restriction by default.

**Server Revision**: 
2678

![wowscrnshot_012219_133129](https://user-images.githubusercontent.com/43656285/51536089-b6839280-1e4a-11e9-8160-493b6bc8be60.jpg)
![wowscrnshot_012219_133408](https://user-images.githubusercontent.com/43656285/51536088-b5eafc00-1e4a-11e9-8615-3195e53373ea.jpg)

**Comment by Tereneckla** [comment]
Fixed
