### ISSUE TITLE
cant purchase guild-bank slot

### ISSUE THREAD

**Issue by ZaMiZ** [Atlantiss/NetherwingBugtracker#4461]
**Description**: cant buy a guild bank slot

**Current behaviour**: https://gyazo.com/9069fef93e919856f4414cda65682b00

**Expected behaviour**: should be able to buy a guild bank slot

**Comment by MUTEant44** [comment]
Do you have enough money in your bags? Seems you can't use gbank money to buy a tab just like in my report where I described inability to withdraw gbank money. Your withdraw button is grayed out just like mine...

**Comment by ZaMiZ** [comment]
ye noticed, weird thing im the glead lol

**Comment by MUTEant44** [comment]
So am I :D Yet I can still access the money as an officer with permissions...

**Comment by ZaMiZ** [comment]
ye solved !   you need to have the money in your own bag but there is still the problem "guild leader cant withdraw money"

**Comment by Tereneckla** [comment]
Fixed
