### ISSUE TITLE
[Dungeon][Combat] Arcatraz(normal)

### ISSUE THREAD

**Issue by AxeCell** [Atlantiss/NetherwingBugtracker#4464]
**Description**: 
Topic is related to a combat bug in Arcatraz normal.

**Current behaviour**:
Once the party got into/past the eredar room we would often get stuck in combat even if a GM reset it. We cleared all the trash in the double boss room and after defeating Wrath-Scryer Soccothrates we were again stuck in combat. There was a singular pet present sometimes, but the warlock was dead by the end of the boss fight.

**Expected behaviour**: 
No combat when not engaged with enemies.

**Server Revision**: 
2678

**Comment by Jalapan** [comment]
As a warlock myself i can say thst my pet has some strange combat bug, wont solve untill i dismiss the pet manually

**Comment by Fuzedknight** [comment]
This is directly related to the Robots, they are the cause of the combat bug. I have discovered that if you let the robots finish their suicide cast you won't combat bug but if you kill them you will combat bug.

**Comment by Evolvee** [comment]
does this still happen?

**Comment by Manaci** [comment]
Fixed
