### ISSUE TITLE
HFR fel iron chest not giving roll option to dead people who havent yet released

### ISSUE THREAD

**Issue by Kibir34** [Atlantiss/NetherwingBugtracker#4465]
[Dungeon][Loot]

**Description**: 
Loot from fel iron chest in HFR didn't give people who died but not yet released an option to roll
**Current behaviour**:
Dead people who haven't released cant roll loot from fel iron chest
**Expected behaviour**: 
Dead people who haven't released should be able to roll loot from fel iron chest
**Server Revision**: 
2678

**Comment by Godmatik** [comment]
Resolved at some point I'm guessing - unable to reproduce - dead players can roll on stuff from the chest just fine
