### ISSUE TITLE
[Spell][Hunter][Pet] Warp

### ISSUE THREAD

**Issue by Eidous** [Atlantiss/NetherwingBugtracker#4466]
[//]: # (Enclose links to things related to the bug using http://wowhead.com or any other TBC database.)
[//]: # (You can use screenshot ingame to visual the issue.)
[//]: # (Write your tickets according to the format:)
[//]: # ([Quest][Azuremyst Isle] Red Snapper - Very Tasty!)
[//]: # ([NPC] Magistrix Erona)
[//]: # ([Spell][Mage] Fireball)
[//]: # ([Npc][Drop] Ghostclaw Lynx)
[//]: # ([Web] Armory doesnt work)
[//]: # (To find server revision type `.server info` command in the game chat.)

**Description**: 
The spell Warp learned by the warp stalker family doesn't teleport the pet to the enemy target.

**Current behaviour**:
When your pet uses Warp, he correctly gains the "50% dodge against the next attack" buff, however he does not get teleported to his target.

**Expected behaviour**: 
Pet should get the warp buff, and get teleported to the enemy target

**Server Revision**: 
2678

**Comment by Argonn** [comment]
Well it works, but only on NEUTRAL mobs (yellow named)

**Comment by Kerfelox** [comment]
Still not working properly :(
Please fix this, they are cute!

**Comment by Scarlene** [comment]
Still an issue, only works on neutral mobs, please, fix this! Thank you.

**Comment by Kirishiki** [comment]
Yep waited so long to tame one of these and slightly dissapointed when this doesnt work D:   fix please

**Comment by Kirishiki** [comment]
Still doesnt work, fix please so i can continue with my warpy into adventures !

**Comment by Wolffenstein** [comment]
Fixed in rev 3368.
