### ISSUE TITLE
[NPC][Arcatraz] Unchained Doombringer is CC'able

### ISSUE THREAD

**Issue by Brasso** [Atlantiss/NetherwingBugtracker#4467]
[//]: # (Enclose links to things related to the bug using http://wowhead.com or any other TBC database.)
[//]: # (You can use screenshot ingame to visual the issue.)
[//]: # (Write your tickets according to the format:)
[//]: # ([Quest][Azuremyst Isle] Red Snapper - Very Tasty!)
[//]: # ([NPC] Magistrix Erona)
[//]: # ([Spell][Mage] Fireball)
[//]: # ([Npc][Drop] Ghostclaw Lynx)
[//]: # ([Web] Armory doesnt work)
[//]: # (To find server revision type `.server info` command in the game chat.)

**Current behaviour**:
You are able to use CC on these mobs such as fear and stuns.
**Expected behaviour**: 
Should be CC immune.
**Server Revision**: 
2678

**Comment by Brasso** [comment]
#2677 Related, you can interrupt his meteor with shocks and spell lock. They are also CCable.

**Comment by Manaci** [comment]
Fixed
