### ISSUE TITLE
The Smallest Creatures

### ISSUE THREAD

**Issue by Styggex** [Atlantiss/NetherwingBugtracker#4468]
[//]: # (Enclose links to things related to the bug using http://wowhead.com or any other TBC database.)
[//]: # (You can use screenshot ingame to visual the issue.)
[//]: # (Write your tickets according to the format:)
[//]: # ([Quest][Azuremyst Isle] Red Snapper - Very Tasty!)
[//]: # ([NPC] Magistrix Erona)
[//]: # ([Spell][Mage] Fireball)
[//]: # ([Npc][Drop] Ghostclaw Lynx)
[//]: # ([Web] Armory doesnt work)
[//]: # (To find server revision type `.server info` command in the game chat.)

**Description**: As of now, you can only poison 1 barrel out of 3.

**Current behaviour**:2 barrels are not working, specifically the Green spot Grog and Ripe Moonshine

**Expected behaviour**: You're supposed to be able to poison all 3 barrels whilst controlling the marmot

**Server Revision**: 2678

**Comment by aresbrutus** [comment]
https://github.com/Atlantiss/NetherwingBugtracker/issues/2246

Duplicate
