### ISSUE TITLE
Blood Elf Bandit missing abilities.

### ISSUE THREAD

**Issue by Sothanwow** [Atlantiss/NetherwingBugtracker#447]
**Description**: 
I have killed the npc `[Blood elf Bandit](https://www.wowhead.com/npc=17591/blood-elf-bandit#abilities)` twice now and while he is stealthed he doesn't seem to use his sinister strike or backstab Some sites I was looking at also listed heroic strike but I am unsure on that one as he is supposed to have sinister strike and it seems redundant

Another problem I noticed with him is his health and damage is much to low for a level 7. He was hitting me for around 4 damage the first time I faced him at level 9. 
He also only seemed to have 103 or so health. live lists his health as 295 which isn't right either for tbc I think it would be some where in between there though around other level 7s in the area like the bucks have around 137 - 156 health.

**Current behaviour**:
Is only stealthed doesn't use his abilities and is to weak.

**Expected behaviour**: 
Should used all listed abilities
Sinister Strike
spell=14873
Shadowstalker Stealth
spell=5916
Backstab 
spell=7159
Behaviour runs away.
**Server Revision**:

**Comment by Peglaa** [comment]
Old wowhead lists him at 100 HP 
http://web.archive.org/web/20070408075723/http://www.wowhead.com:80/?npc=17591#z0z

**Comment by aresbrutus** [comment]
He already has the abilities you listed + the stats are also correct if you look at bestiary.

https://i.imgur.com/IpYae2I.png
https://i.imgur.com/RveGc24.png
https://i.imgur.com/AYl1mYA.png
