### ISSUE TITLE
Paladin Illumination - Not Refunding any mana

### ISSUE THREAD

**Issue by Finvy** [Atlantiss/NetherwingBugtracker#4471]
See video below.  Combat log indicates 60% mana refund on heal crit, however mana bar is not adjusted accordingly.  

https://www.youtube.com/watch?v=gtRq-tm7dtw

Any assistance with this would be greatly appreciated.

**Comment by Tenoutoften** [comment]
I think this work, but not when you start from 100% mana. Somewhat similar to a more crucial paladin bug, Spiritual Attunement doesn't generate mana when a paladin is healed to 100% health https://github.com/Atlantiss/NetherwingBugtracker/issues/3807

**Comment by Finvy** [comment]
Confirmed this only seems to be an issue when at full health or mana.  Closing ticket.

**Comment by Tenoutoften** [comment]
I still think it is a bug, it's just less of a bug than you originally thought

**Comment by Tenoutoften** [comment]
I experienced the same issue with https://github.com/Atlantiss/NetherwingBugtracker/issues/4165
