### ISSUE TITLE
[Quest] [Zangarmarsh] Now That We're Still Friends... 

### ISSUE THREAD

**Issue by KredesX** [Atlantiss/NetherwingBugtracker#4472]
[//]: # (Enclose links to things related to the bug using http://wowhead.com or any other TBC database.)
[//]: # (You can use screenshot ingame to visual the issue.)
[//]: # (Write your tickets according to the format:)
[//]: # ([Quest][Azuremyst Isle] Red Snapper - Very Tasty!)
[//]: # ([NPC] Magistrix Erona)
[//]: # ([Spell][Mage] Fireball)
[//]: # ([Npc][Drop] Ghostclaw Lynx)
[//]: # ([Web] Armory doesnt work)
[//]: # (To find server revision type `.server info` command in the game chat.)

**Description**: The nagas you gotta kill in this quest does insane amount of damage, primarily the casters, not sure if this is intended. Also the aggro range seems bugged too, you often end up pulling 4-5 mobs when pulling one. 

**Current behaviour**: Aggro range too high, also damage feels too high on the caster mobs.

**Expected behaviour**: 

**Server Revision**: 2678

**Comment by banallwowbots** [comment]
The casters have a freeze spell that will do great amount of damage, if you are standing in it. This is intended.
