### ISSUE TITLE
Can't be ressed inside dungeon

### ISSUE THREAD

**Issue by Ebeebe123** [Atlantiss/NetherwingBugtracker#4473]
Current behaviour:
Couldn't get ressed both by paladin and priest in Underbog dungeon before i released or after that 
Expected behaviour: 
you should be able to get ressed

**Comment by Tenoutoften** [comment]
https://github.com/Atlantiss/NetherwingBugtracker/issues/4354
https://github.com/Atlantiss/NetherwingBugtracker/issues/4295
