### ISSUE TITLE
[Quest] Escort Fail Despite NPC Alive 

### ISSUE THREAD

**Issue by sadfx** [Atlantiss/NetherwingBugtracker#4474]
**Description**: Escort quest failing despite the NPC not dying/despawning with players nearby

**Current behaviour**: I accepted the quest, two party members accepted it as well. Quest failed for me when I ran off a very short distance to grab some nodes. NPC never despawned as two players were next to him at all times. Quest failed for me but didn't fail for anyone else.

**Expected behaviour**: Escort quest shouldn't fail FOR ANYONE if a single player currently on the quest is in the immediate vicinity of the NPC

**Server Revision**: 2678

**Comment by Evolvee** [comment]
what escort quest?
