### ISSUE TITLE
[Spell][Priest] Power Word: Shield issue

### ISSUE THREAD

**Issue by case8** [Atlantiss/NetherwingBugtracker#4475]
[//]: # (Enclose links to things related to the bug using http://wowhead.com or any other TBC database.)
[//]: # (You can use screenshot ingame to visual the issue.)
[//]: # (Write your tickets according to the format:)
[//]: # ([Quest][Azuremyst Isle] Red Snapper - Very Tasty!)
[//]: # ([NPC] Magistrix Erona)
[//]: # ([Spell][Mage] Fireball)
[//]: # ([Npc][Drop] Ghostclaw Lynx)
[//]: # ([Web] Armory doesnt work)
[//]: # (To find server revision type `.server info` command in the game chat.)

**Description**: 
Power Word: Shield should stop certain actions from being interrupted when hit by a mob.

**Current behaviour**:
When mining or picking up a quest item (and probably other gathering actions) with Power Word: Shield, the action is interrupted if struck by a mob.

**Expected behaviour**: 
When the shield fully absorbs the attack, the action should continue uninterrupted.

**Server Revision**: 
2680 (I think)

**Comment by NFZmexizz** [comment]
it worked fine even yesterday didint checked it today yet

**Comment by case8** [comment]
@NFZ well it’s definitely still not working for me.

**Comment by elasdmehico** [comment]
Pretty sure priest shield isn't supposed to make you immune to interrupts while mining lol can you back this up

**Comment by case8** [comment]
@elasdmehico Doesn’t sound like you’ve even played a priest. 

It’s quite simple. PW:S prevents spell pushback. “Herb gathering” etc are spells. On retail, PW:S prevented pushback when using “gathering” spells.

**Comment by elasdmehico** [comment]
Pretty sure priest shield isn't supposed to make you immune to interrupts while mining nodes. I asked if you could back it up and instead you continue not backing it up. All I'm saying is I'm pretty sure what you're saying is wrong and unless you can back it up I will stand by what I said lol

**Comment by case8** [comment]
You keep saying you're "pretty sure" even though you've obviously never played priest, otherwise you would know this. I've explained it perfectly, it's the simple mechanics of the game. Therefore it's obvious you're just trolling so I won't bother engaging with you any further.

**Comment by Tereneckla** [comment]
Fixed
