### ISSUE TITLE
sweeping strike

### ISSUE THREAD

**Issue by antikiller69** [Atlantiss/NetherwingBugtracker#4476]
[//]: # (Enclose links to things related to the bug using http://wowhead.com or any other TBC database.)
[//]: # (You can use screenshot ingame to visual the issue.)
[//]: # (Write your tickets according to the format:)
[//]: # ([Quest][Azuremyst Isle] Red Snapper - Very Tasty!)
[//]: # ([NPC] Magistrix Erona)
[//]: # ([Spell][Mage] Fireball)
[//]: # ([Npc][Drop] Ghostclaw Lynx)
[//]: # ([Web] Armory doesnt work)
[//]: # (To find server revision type `.server info` command in the game chat.)

**Description**: sweeping strike doesnt do instantly dmg to nearby enemies, tied into spellbatching which it should not be

**Current behaviour**: does not deal dmg instantly

**Expected behaviour**: should do dmg instantly

**Server Revision**:

**Comment by Easyfraggy** [comment]
Post some proof of your claim.

**Comment by Godmatik** [comment]
Spellbatching no longer exists, and not enough information.

Closing.
