### ISSUE TITLE
[Warlock][Talent] Pyroclasm doesn't work

### ISSUE THREAD

**Issue by Jsnapsta** [Atlantiss/NetherwingBugtracker#4477]
**Description**: 
Ran through wailing caverns to help my lower level friend catch up with me and my paladin friend, used rain of fire for most of the instance, and didn't see a single stun off of pyroclasm talent occur.  At the time I was level 31, had 1 point in pyroclasm, and used rain of fire(rank 1).  Hit level 32 and put the second point into pyroclasm, then decided to further investigate by killing mobs in thousand needles for about an hour with rain of fire(rank 1) and hellfire(rank 1).  I couldn't get the stun from pyroclasm to go off once.
**Current behaviour**:
Seems like the talent pyroclasm does not have a chance to stun when using rain of fire or hellfire(not high enough level to test if it works with soul fire)
**Expected behaviour**: 
According to the wow wiki patch changes for pyroclasm with its talent description in game, it should give a 13%/26% chance to stun when rain of fire, hellfire, or soul fire spells damage the target that does not diminish by controlled stuns such as cheap shot, hammer of justice, or charge.
https://wow.gamepedia.com/Pyroclasm_(warlock_talent)
Added links to the talent in a database
Rank 1 (1 Point): https://db.excalibur.ws/?spell=18096
Rank 2 (2 Points): https://db.excalibur.ws/?spell=18073
**Server Revision**: 
2678 (according to .server info)

**Comment by Jsnapsta** [comment]
https://www.youtube.com/watch?v=iocgjL5hSkE

Here's a video I uploaded on me trying to get it to work with the combat log open on the bottom left. Had around 30 damage tics of rain of fire/hellfire and didn't get a single stun.

**Comment by ivanlink** [comment]
Yes I agree, the talent doesn't work, never seen a stun.

**Comment by Wolffenstein** [comment]
Works now.

**Comment by NoMoreGoodNames** [comment]
Its broken again , doesnt stun
