### ISSUE TITLE
[Druid] Auto Attack bug in cat form when in stealth form

### ISSUE THREAD

**Issue by spetan** [Atlantiss/NetherwingBugtracker#4478]
As title suggest There is a Auto Attack bug that occurs only when you are in Cat Form and stealthing trying to use the ability Shred.

Basically the way you can produce this bug is while you are in stealth and you are trying to move behind the target to use the ability Shred at the same time as you are mashing the button the shred ability is assigned you there is a chance it might happen. I dont know IF this scenario can happen while you are fighting players. There was a case earlier as of today where i fought a Druid trying to get my shred ability in to him while we both were in stealth. I ended up killing him just normally but there was a lvl 30 mob that i could not auto attack after and ended up dying to it because of that.

Video that shows(Please skip to 1:29 otherwise you will see terrible PvP skills :^): https://www.youtube.com/watch?v=kzZvxRTaIU8&feature=youtu.be

Here's another example through video to explain this: https://www.youtube.com/watch?v=RqM5cp_NsLA&feature=youtu.be

In this video you can see that this specific mob is easy to produce it on due to the fact that it just evaded my attack while it was finished with its rotation. Whenever something evades that is a monster in that specific way you will reproduce this bug. But that doesnt happen with every mob though. Its just to show you that the bug exists in another way basically.

**Comment by spetan** [comment]
Correction: It doesnt only count for Shred ability. Also counts for Pounce and most likely also for Ravage. Any of these abilities seems to be able to trigger this bug as long as youre in stealth, obviously.

**Comment by Godmatik** [comment]
Was fixed, closing
