### ISSUE TITLE
Blood Elf Paladin Class Quest - Claiming the Light Bugged

### ISSUE THREAD

**Issue by ThaWhizz** [Atlantiss/NetherwingBugtracker#448]
[//]: # (Enclose links to things related to the bug using http://wowhead.com or any other TBC database.)
[//]: # (You can use screenshot ingame to visual the issue.)
[//]: # (Write your tickets according to the format:)
[//]: # ([Quest][Azuremyst Isle] Red Snapper - Very Tasty!)
[//]: # ([NPC] Magistrix Erona)
[//]: # ([Spell][Mage] Fireball)
[//]: # ([Npc][Drop] Ghostclaw Lynx)
[//]: # ([Web] Armory doesnt work)

**Description**: 
This is a Blood Elf Paladin class quest in Silvermoon City. 
[2018-09-24 18-42-10.zip](https://github.com/Atlantiss/NetherwingBugtracker/files/2413282/2018-09-24.18-42-10.zip)

**Current behaviour**:
When using the quest vial on the target M'uru the quest does not complete. (see attachment)
**Expected behaviour**: 
Quest should be marked as complete once the quest item is used on target M'uru.
**Server Revision**:

**Comment by wtRCH** [comment]
Refered to https://github.com/Atlantiss/NetherwingBugtracker/issues/141

**Comment by Wolffenstein** [comment]
Fixed in rev 2046.
