### ISSUE TITLE
[69] Creatures of the Eco-Domes

### ISSUE THREAD

**Issue by Skitter92** [Atlantiss/NetherwingBugtracker#4480]
[//]: # (Enclose links to things related to the bug using http://wowhead.com or any other TBC database.)
[//]: # (You can use screenshot ingame to visual the issue.)
[//]: # (Write your tickets according to the format:)
[//]: # ([Quest][Azuremyst Isle] Red Snapper - Very Tasty!)
[//]: # ([NPC] Magistrix Erona)
[//]: # ([Spell][Mage] Fireball)
[//]: # ([Npc][Drop] Ghostclaw Lynx)
[//]: # ([Web] Armory doesnt work)
[//]: # (To find server revision type `.server info` command in the game chat.)

**Description**: Talbuks are not returning to normal (full hp) status after being tagged. As a result, cannot complete the quest.

**Current behaviour**: Talbuks lying on ground at 20% or less hp.

**Expected behaviour**: Talbuks at full hp so that quest can be completed.

**Server Revision**:

**Comment by Tenoutoften** [comment]
Already reported here: https://github.com/Atlantiss/NetherwingBugtracker/issues/2666
