### ISSUE TITLE
[Quest] Trial of the Naaru: Mercy

### ISSUE THREAD

**Issue by Squarz** [Atlantiss/NetherwingBugtracker#4481]
[//]: # (Enclose links to things related to the bug using http://wowhead.com or any other TBC database.)
[//]: # (You can use screenshot ingame to visual the issue.)
[//]: # (Write your tickets according to the format:)
[//]: # ([Quest][Azuremyst Isle] Red Snapper - Very Tasty!)
[//]: # ([NPC] Magistrix Erona)
[//]: # ([Spell][Mage] Fireball)
[//]: # ([Npc][Drop] Ghostclaw Lynx)
[//]: # ([Web] Armory doesnt work)
[//]: # (To find server revision type `.server info` command in the game chat.)

**Description**: 
Only one Unused Axe of the Executioner is lootable even with five party members on the quest

**Current behaviour**:
Shattered Hand Executioner is only dropping a single Unused Axe of the Executioner

**Expected behaviour**: 
Shattered Hand Executioner should drop an Unused Axe of the Executioner for each party member on the quest

**Server Revision**: 
2678

**Comment by Azalen** [comment]
Proof: https://youtu.be/UzQEPwf8eyY?t=166
See in chat, 2x long white text which represents the unused Axe.
Still buggy.

**Comment by Evolvee** [comment]
should be fixed already
