### ISSUE TITLE
[NPC][Shattered Halls] Shattered Hand Assassin not using Cheap Shot

### ISSUE THREAD

**Issue by Brasso** [Atlantiss/NetherwingBugtracker#4482]
[//]: # (Enclose links to things related to the bug using http://wowhead.com or any other TBC database.)
[//]: # (You can use screenshot ingame to visual the issue.)
[//]: # (Write your tickets according to the format:)
[//]: # ([Quest][Azuremyst Isle] Red Snapper - Very Tasty!)
[//]: # ([NPC] Magistrix Erona)
[//]: # ([Spell][Mage] Fireball)
[//]: # ([Npc][Drop] Ghostclaw Lynx)
[//]: # ([Web] Armory doesnt work)
[//]: # (To find server revision type `.server info` command in the game chat.)

**Current behaviour**:
Shattered Hand Assassin does not use Cheap Shot.

**Expected behaviour**: 
Should use Cheap Shot.

**Server Revision**: 
2678

**Comment by devo6969** [comment]
(They do use Cheap Shot)
refer to #3519
