### ISSUE TITLE
Arikara quest does not summon

### ISSUE THREAD

**Issue by Alaryus** [Atlantiss/NetherwingBugtracker#4483]
[//]: # ([Quest][Thousand Needles] Arikara)

**Supposed to light the Sacred Fire of Life with Incendia Powder to summon Arikara**: 

**Nothing happens when I use the the Incendia Powder on the Sacred Fire of Life**:

**Arikara should be summoned when I do this**: 

**Server Revision: 2678**:

**Comment by Balanarr** [comment]
This worked fine for me about a week ago

**Comment by NFZmexizz** [comment]
Not worked for me last week, i used the quest item on the fireplace , item was usuable but no effect after use

**Comment by duzyizly** [comment]
worked for me like 2 weeks ago so it's something new.

**Comment by Dewsch** [comment]
GM had to come give manual quest credit after we tried to work with him for 20+ minutes to get the quest to work.  We tried relogging, dropping party, using the item from our inventory from max range, on top of it, etc etc.  Nothing ended up working.

**Comment by EGSilver** [comment]
I summoned arikara yesterday. Went back 15 minutes later and it was bugged. Some hunter tamed the beast which resulted in the quest being bugged.

**Comment by Evolvee** [comment]
rev 2690
