### ISSUE TITLE
Screen freezes during rogue abilities

### ISSUE THREAD

**Issue by skittles56** [Atlantiss/NetherwingBugtracker#4484]
**Description**: Not sure which ability it is, but it's related to stuns, stealth or prep being used. I once engaged a rogue and right after he came out of stealth with a cheap shot, I froze for 30 seconds and crashed. Second time I met the guy, both of us froze for 15 seconds. Third time was with my rogue friend in hellfire and it was right after a cheap shot. I've only fought with a few rogues, so I haven't had much of a chance to trigger this issue.

**Current behaviour**: Screen rarely, but often enough, freezes after an ability from rogues are used, friend and enemy alike. 

**Expected behaviour**: Should not be any freezes.

**Server Revision**: 2678

**Comment by networm555** [comment]
Same for hunter. Hapenned about 30 times during pvp encouters with different classes. 100% sure ability queue involved.

**Comment by The14me** [comment]
Think that was fixed a long time ago since none complain about it.
