### ISSUE TITLE
Aldor Rep backtrack? i did some quests after the Allegiance to the Aldor, now im unfriendly again.

### ISSUE THREAD

**Issue by Isiniac** [Atlantiss/NetherwingBugtracker#4485]
[//]: # (Enclose links to things related to the bug using http://wowhead.com or any other TBC database.)
[//]: # (You can use screenshot ingame to visual the issue.)
[//]: # (Write your tickets according to the format:)
[//]: # ([Quest][Azuremyst Isle] Red Snapper - Very Tasty!)
[//]: # ([NPC] Magistrix Erona)
[//]: # ([Spell][Mage] Fireball)
[//]: # ([Npc][Drop] Ghostclaw Lynx)
[//]: # ([Web] Armory doesnt work)
[//]: # (To find server revision type `.server info` command in the game chat.)

**Description**: 

**Current behaviour**:

**Expected behaviour**: 

**Server Revision**:

**Comment by liek0r** [comment]
Some quests clearly state that when completing them you lose Aldor or Scryer rep. You sure you didn't complete one of these?

For example [this quest](http://db.hellfire-tbc.com/?quest=10204)

>Magistrix Larynna wants you to go to Manaforge B'naar and obtain a Bloodgem Shard from a Sunfury Magister. Use this shard near the larger Bloodgem crystals and return to her at Area 52.
>**Completing quests for the Scryers will cause your Aldor reputation level to decrease.**

**Comment by Isiniac** [comment]
im and idiot, its also bin 10 years :) thanks. as i was 2825/3000 so 1 other quests did the jobb.
