### ISSUE TITLE
Starving fungal giant

### ISSUE THREAD

**Issue by AWIDIUS** [Atlantiss/NetherwingBugtracker#4486]
Seems like mob is allowed to climb some kind of corrupted mushrooms https://imgur.com/a/uUfMkou . Maybe pathing problem or smth.

**Comment by The14me** [comment]
Rev.3483 still an issue. Entry 18125 ID 21

**Comment by Godmatik** [comment]
Rev 4018 - no longer an issue and it does not climb the mushroom, likely resolved with last year's pathing updates
