### ISSUE TITLE
[Quest] Full Triangle

### ISSUE THREAD

**Issue by AxeCell** [Atlantiss/NetherwingBugtracker#4488]
**Description**: 
Topic is related to the delivery part of the quest "Full Triangle" found in Netherstorm.

**Current behaviour**:
Once the fight between Ambassador Solannas and Nexus-Prince Haramad ends, the Nexus-Prince will remain idle in the building while his image will take about 3 minutes to appear again. The Nexus-Prince himself never disappears.

**Expected behaviour**: 
Once Ambassador Solannas becomes aggressive, Nexus-Prince Haramad will emerge from his teleporter and assist the player with the NPCs. Once the fight is done he'll return back into the teleporter and his image will reappear.

**Server Revision**: 
2678

**Comment by Evolvee** [comment]
works fine for me

**Comment by Evolvee** [comment]
need reproduction steps

**Comment by Evolvee** [comment]
i just saw 2 ppl do it on live realm and it was fine

**Comment by naikunaikunaiku** [comment]
http://prntscr.com/mbmoui 

experienced the bug 2 times now in our group

first time we engaged the ambassodar second time we didnt fight

**Comment by kwah8787** [comment]
happened to me just now. so when i come in the room nexus prince real and nexus prince image are both up. i turn in full triangle to the image. the fight breaks out and finishes normally as far as i could tell. the nexus prince remained up but the image was gone.. for about 5 minutes then he came back. the prince has remained up the entire time.

**Comment by Evolvee** [comment]
yea but u came to already bugged situation... i need to know how to reproduce this bugged situation

**Comment by Shinizaa** [comment]
When you turn it in wait for the RP to end and let the ambassador attack the nexus prince. The Nexus Prince will run out of his teleporter and after finishing on the mob it just doesn't reset.
That's how it happens. It happened to me last night aswell.

**Comment by Evolvee** [comment]
hmmmm

**Comment by Evolvee** [comment]
oh its a core issue affecting  one components of how its scripted

**Comment by Sherbaderb** [comment]
Currently having the same issue.

I think the issue is I killed the ambassador before Nexus-Prince could attack/touch the mobs. So he failed to reset. 

Saw it working fine about 2 hours ago.

Image respawned after 5~ minutes of waiting.

**Comment by Evolvee** [comment]
i guess its working now?
