### ISSUE TITLE
Escorts in Ghostlands

### ISSUE THREAD

**Issue by Creepermunch** [Atlantiss/NetherwingBugtracker#449]
[//]: # (Enclose links to things related to the bug using http://wowhead.com or any other TBC database.)
[//]: # (You can use screenshot ingame to visual the issue.)
[//]: # (Write your tickets according to the format:)
[//]: # ([Quest][Azuremyst Isle] Red Snapper - Very Tasty!)
[//]: # ([NPC] Magistrix Erona)
[//]: # ([Spell][Mage] Fireball)
[//]: # ([Npc][Drop] Ghostclaw Lynx)
[//]: # ([Web] Armory doesnt work)

**Description**: NPC's have depression, they dont attack your mobs or mobs aggroed on them they just die

**Current behaviour**:
Mobs walk from point A to point B without stopping or attacking/defending
**Expected behaviour**: 
Attacking and defending when mobs are aggroed on the player or NPC in question
**Server Revision**:

**Comment by wtRCH** [comment]
It happens to all the escort NPCs tho.

**Comment by Wolffenstein** [comment]
Fixed in rev 2047.
