### ISSUE TITLE
[Spell][Warlock] Shadowburn & Drain Soul

### ISSUE THREAD

**Issue by elasdmehico** [Atlantiss/NetherwingBugtracker#4494]
[//]: # (Enclose links to things related to the bug using http://wowhead.com or any other TBC database.)
[//]: # (You can use screenshot ingame to visual the issue.)
[//]: # (Write your tickets according to the format:)
[//]: # ([Quest][Azuremyst Isle] Red Snapper - Very Tasty!)
[//]: # ([NPC] Magistrix Erona)
[//]: # ([Spell][Mage] Fireball)
[//]: # ([Npc][Drop] Ghostclaw Lynx)
[//]: # ([Web] Armory doesnt work)
[//]: # (To find server revision type `.server info` command in the game chat.)

**Description**:
Shadowburn: Instantly blasts the target for x to y Shadow damage. If the target dies within 5 sec of Shadowburn, and yields experience or honor, the caster gains a Soul Shard

Drain Soul: Drains the soul of the target, causing x Shadow damage over 15 sec. If the target dies while being drained, and yields experience or honor, the caster gains a Soul Shard. Soul Shards are required for other spells.

**Current behaviour**: Casting shadowburn and drain soul on a target only grants you one soul shard.

**Expected behaviour**: Casting shadowburn and drain soul should grant you two shards.

**Server Revision**: 2682

Steps to reproduce:
1. Bring any player or mob that rewards experience or honor to low enough hp for a shadowburn and shadow bolt to kill the target.
2. Move far away from target
2. Cast shadowbolt -> shadowburn -> drain soul

To do this you need to stay far away, cast shadow bolt then immediately cast shadowburn and drain soul. If the target dies you'll be granted one shard, but you should be getting two, right?

**Comment by Balanarr** [comment]
You should NOT be getting 2.

As of Patch 1.11.0 (2006-06-20): If you cast Drain Soul while this aura is on the victim, you will no longer receive two soul shards upon the victim's death.
