### ISSUE TITLE
bugged Heavy Golden Necklace of Battle on Auction 

### ISSUE THREAD

**Issue by mmaasstteerr** [Atlantiss/NetherwingBugtracker#4496]
[//]: # (Enclose links to things related to the bug using http://wowhead.com or any other TBC database.)
[//]: # (You can use screenshot ingame to visual the issue.)
[//]: # (Write your tickets according to the format:)
[//]: # ([Quest][Azuremyst Isle] Red Snapper - Very Tasty!)
[//]: # ([NPC] Magistrix Erona)
[//]: # ([Spell][Mage] Fireball)
[//]: # ([Npc][Drop] Ghostclaw Lynx)
[//]: # ([Web] Armory doesnt work)
[//]: # (To find server revision type `.server info` command in the game chat.)

**Description**: 
![image](https://user-images.githubusercontent.com/31092539/51620474-bfe82a00-1f32-11e9-9dbf-4d1b785f30a1.png)
When trading unused Heavy Golden Necklace of Battle game said that charges were used already

**Current behaviour**:
Cannot put on auction unused Heavy Golden Necklace of Battle 
**Expected behaviour**: 
Be able to put on auction unused Heavy Golden Necklace of Battle 

**Server Revision**: 
asda

**Comment by Wolffenstein** [comment]
Fixed in rev 3361.
