### ISSUE TITLE
[Rogue] [Mega High Priority] CastSpellByName("Pick Lock") doesn't work

### ISSUE THREAD

**Issue by sadfx** [Atlantiss/NetherwingBugtracker#4498]
**Current behaviour**: CastSpellByName("Pick Lock") is protected.

**Expected behaviour**: Activates Pick Lock - CastSpellByName ("name"[, onSelf])  /WoW API/ PROTECTED\n  Cast the specified spell by display name. As of patch 2.0, this function has been restricted to Blizzard signed UI mods. Note: You can still use this function to open Craft windows and activate Lock Picking.

**Server Revision**: 2682

**Comment by Wolffenstein** [comment]
We can't change that, it's clientside.
