### ISSUE TITLE
Noggerfogger Elixir

### ISSUE THREAD

**Issue by miri283** [Atlantiss/NetherwingBugtracker#4499]
[//]: # (Enclose links to things related to the bug using http://wowhead.com or any other TBC database.)
[//]: # (You can use screenshot ingame to visual the issue.)
[//]: # (Write your tickets according to the format:)
[//]: # ([Quest][Azuremyst Isle] Red Snapper - Very Tasty!)
[//]: # ([NPC] Magistrix Erona)
[//]: # ([Spell][Mage] Fireball)
[//]: # ([Npc][Drop] Ghostclaw Lynx)
[//]: # ([Web] Armory doesnt work)
[//]: # (To find server revision type `.server info` command in the game chat.)

**Description**: 
When i use Noggerfogger Elixir and it make me skeleton, i cant mount up. Im Orc, but Undead race hasn't got this problem.

**Comment by killablink** [comment]
You can't mount up while being a skeleton using the elixir

**Comment by Evolvee** [comment]
is this a bug?

need evidence/proof etc.

**Comment by killablink** [comment]
It's not a bug, there was already a report about noggenfogger
