### ISSUE TITLE
[NPC] Nyoma in Dolanaar is non-interactive

### ISSUE THREAD

**Issue by Vempz** [Atlantiss/NetherwingBugtracker#45]
[//]: # (Enclose links to things related to the bug using http://wowhead.com or any other TBC database.)
[//]: # (You can use screenshot ingame to visual the issue.)
[//]: # (Write your tickets according to the format:)
[//]: # ([Quest][Azuremyst Isle] Red Snapper - Very Tasty!)
[//]: # ([NPC] Magistrix Erona)
[//]: # ([Spell][Mage] Fireball)
[//]: # ([Npc][Drop] Ghostclaw Lynx)
[//]: # ([Web] Armory doesnt work)

**Description**: 

1. go to Dolanaar in Teldrassil
2. go to the cooking trainer
3. target Nyoma and try to interact with her
4. current behaviour is visible

**Current behaviour**:

-  Nyoma (Entry: 4265, Id: 1) is non-interactive
- screenshot: https://imgur.com/a/reRgHql

**Expected behaviour**: 
- Nyoma should be interactive

**Server Revision**: 
rev: 2019

**Comment by Wolffenstein** [comment]
Fixed in rev 2020.
