### ISSUE TITLE
[Player] No default stance on warrior creation gives an empty bar

### ISSUE THREAD

**Issue by Teppic1** [Atlantiss/NetherwingBugtracker#450]
**Description**: 

When creating a new warrior no stance is active and so the action bar is totally empty with no indication of what to do. Clicking the stance adds the abilities.

**Expected behaviour**: 

I'm not sure if this was correct or not in retail, but it seems weird.

**Server Revision**: 

203

**Comment by Teppic1** [comment]
Confirmed as a bug here by Scylla: https://youtu.be/ivx6-1Q_IEM?t=5m30s

**Comment by Wolffenstein** [comment]
Fixed in rev 2046.
