### ISSUE TITLE
A Crew Under Fire not able to hand in

### ISSUE THREAD

**Issue by baygon84** [Atlantiss/NetherwingBugtracker#4500]
[//]: # ([Quest][A Crew Under Fire)
[//]: # ([NPC] Captain Vanessa Beltis)

**Description**: 
A Crew Under Fire Quest not able to be turned in after complete
**Current behaviour**:
Full fight sequence appears to be fine.   At end of last wave Captain Vanessa Beltis appears to remain in combat with debuffs on her - no ? appears to hand in
**Expected behaviour**: 
She should return to the group and offer hand in
**Server Revision**: 
2682

**Comment by Manaci** [comment]
Fixed
