### ISSUE TITLE
[NPC] Tangled Horror

### ISSUE THREAD

**Issue by Haiwuu** [Atlantiss/NetherwingBugtracker#4502]
**Description**: NPC Tangled Horror 766 has an unhealthy obsession with casting rejuvenation.

**Current behaviour**: the NPC will try to cast it repeatedly even after being purged/interrupted
The NPC will sit there casting rejuvenation over and over again, not defending itself.

**Expected behaviour**: NPC should take a break after being interrupted casting the spell and resume combat.

**Server Revision**: 2682

**Comment by Evolvee** [comment]
rev 2685
