### ISSUE TITLE
[NPC] [Human Commoner] out of season

### ISSUE THREAD

**Issue by H2714** [Atlantiss/NetherwingBugtracker#4503]
[//]: # (Enclose links to things related to the bug using http://wowhead.com or any other TBC database.)
[//]: # (You can use screenshot ingame to visual the issue.)
[//]: # (Write your tickets according to the format:)
[//]: # ([Quest][Azuremyst Isle] Red Snapper - Very Tasty!)
[//]: # ([NPC] Magistrix Erona)
[//]: # ([Spell][Mage] Fireball)
[//]: # ([Npc][Drop] Ghostclaw Lynx)
[//]: # ([Web] Armory doesnt work)
[//]: # (To find server revision type `.server info` command in the game chat.)

**Description**: 
Two [Human Commoners](https://www.wowhead.com/npc=18927/human-commoner#comments) with halloween masks in SW trade district.

**Current behaviour**:
![wowscrnshot_012319_194124](https://user-images.githubusercontent.com/46264740/51630955-ac958880-1f4b-11e9-8d15-7762710898a9.jpg)

**Expected behaviour**: 
> These NPCs are often dressed for the season and show up mainly during holiday events.
/Wowhead comments

**Server Revision**: 
2682

**Comment by Evolvee** [comment]
rev 2685
