### ISSUE TITLE
[NPC][Shattered Halls] Shattered Hand Assassin gives +2 rep

### ISSUE THREAD

**Issue by knasen88** [Atlantiss/NetherwingBugtracker#4504]
[//]: # (Enclose links to things related to the bug using http://wowhead.com or any other TBC database.)
[//]: # (You can use screenshot ingame to visual the issue.)
[//]: # (Write your tickets according to the format:)
[//]: # ([Quest][Azuremyst Isle] Red Snapper - Very Tasty!)
[//]: # ([NPC] Magistrix Erona)
[//]: # ([Spell][Mage] Fireball)
[//]: # ([Npc][Drop] Ghostclaw Lynx)
[//]: # ([Web] Armory doesnt work)
[//]: # (To find server revision type `.server info` command in the game chat.)

**Description**: 
title p much, gives 2 rep per kill, every other elite gives 12
**Current behaviour**:
--- https://streamable.com/nbwks
**Expected behaviour**: 
12 rep?
**Server Revision**:

**Comment by Evolvee** [comment]
![image](https://user-images.githubusercontent.com/1942409/51633305-a7d3d300-1f51-11e9-8f3f-7304b5c3727c.png)

**Comment by Evolvee** [comment]
do some research before posting please
