### ISSUE TITLE
Party Disband Bug

### ISSUE THREAD

**Issue by Easters** [Atlantiss/NetherwingBugtracker#4505]
**Description**: Hi! I have noticed a party bug

**Current behaviour**: the party disbands when someone (in the party) goes offline. It will say that the member is still in the party but if they try to invite me again it will say that I am in party when I am actually not. 

**Expected behaviour**:  The party shouldn't disband if someone goes offline, and even if it does disband, it should disappear from the other person's screen.

**Comment by Suzaru** [comment]
Related to serval bug reports:

https://github.com/Atlantiss/NetherwingBugtracker/issues/4636
https://github.com/Atlantiss/NetherwingBugtracker/issues/4410
https://github.com/Atlantiss/NetherwingBugtracker/issues/3844

It's extremly annoying and destroyed a few dungeons for us. :(
