### ISSUE TITLE
Mob comes from the sky

### ISSUE THREAD

**Issue by AWIDIUS** [Atlantiss/NetherwingBugtracker#4506]
https://imgur.com/a/rruYePy . Marauder incoming from the tree, obliquely to the ground. When I pull him, he is followed by additional 1 Marauder and 1 Messenger. Bug in pathing probably.

**Comment by AWIDIUS** [comment]
Next spawn, it spawns correct right in front of fortress, dont know what may have caused that bug.

**Comment by The14me** [comment]
Rev.3483 must be some moment pathing issue. Can recreate it.
