### ISSUE TITLE
[Quest] Power in Uldaman Obisidian Sentinel debuff is bugged.

### ISSUE THREAD

**Issue by Xaero252** [Atlantiss/NetherwingBugtracker#4507]
[//]: # (Enclose links to things related to the bug using http://wowhead.com or any other TBC database.)
[//]: # (You can use screenshot ingame to visual the issue.)
[//]: # (Write your tickets according to the format:)
[//]: # ([Quest][Azuremyst Isle] Red Snapper - Very Tasty!)
[//]: # ([NPC] Magistrix Erona)
[//]: # ([Spell][Mage] Fireball)
[//]: # ([Npc][Drop] Ghostclaw Lynx)
[//]: # ([Web] Armory doesnt work)
[//]: # (To find server revision type `.server info` command in the game chat.)

**Description**: 
The mob "Obsidian Sentinel" inside the back door to Uldaman has a debuff that appears when he "shatters" at different stages of HP. This debuff makes it possible to solo this npc.

**Current behaviour**:
The debuff correctly applies when he hits the required HP, and stays on him when you leave the instance - but as soon as you engage him in combat the debuff drops.

**Expected behaviour**: 
On live retail (verifiable via https://www.wowhead.com/npc=7023/obsidian-sentinel#comments)
This debuff did not reset, making the mob soloable.

**Server Revision**: 
2682

**Comment by Godmatik** [comment]
Rev 4017 - no longer an issue
The stacks properly remain on the mob even after it resets and you re-engage him.
