### ISSUE TITLE
Combat issue again.

### ISSUE THREAD

**Issue by AWIDIUS** [Atlantiss/NetherwingBugtracker#4509]
https://www.youtube.com/watch?v=-11ChAmA1IA We've killed Lisaile Fireweaver, I run out of building and then it started. Combat starts, combat drops, again and again. You can see on video for better assessment.

**Comment by Tenoutoften** [comment]
Possibly the formations of orcs that patrol on their mounts that is currently really buggy? Could be underground?

**Comment by The14me** [comment]
Rev.3483 not an issue anymore.
