### ISSUE TITLE
Paladin's quest Claiming the light

### ISSUE THREAD

**Issue by Ketriasha** [Atlantiss/NetherwingBugtracker#451]
**Description**: 
The q where we get shimmering vessel and we should fulfill it with naaru essence

**Current behaviour**:
After using item q it just dissapears with communicate that it doesnt exist
**Expected behaviour**: 
should get fulfilled vessel with naaru light
**Server Revision**:

**Comment by wtRCH** [comment]
Refered to https://github.com/Atlantiss/NetherwingBugtracker/issues/141

**Comment by Wolffenstein** [comment]
Fixed in rev 2046.
