### ISSUE TITLE
[Item]Formula: Large Prismatic Shard#22565 added in 2.0 not in game

### ISSUE THREAD

**Issue by Tenoutoften** [Atlantiss/NetherwingBugtracker#4514]
**Description**: 
I've seen several items added in 2.0.12 be in the game, yet this item is added later on the timeline. Perhaps this should be added?

http://web.archive.org/web/20070314184916/http://www.thottbot.com:80/i22565
According to the archive this was in game in march, with 3 comments & 1 comment on [Wowhead 2.0.12](https://www.wowhead.com/item=22565/formula-large-prismatic-shard#comments:id=51221)

**Current behaviour**:
Not in the game.

**Expected behaviour**: 
Was in the game in 2.0.12

**Server Revision**: 
2682

**Comment by Shanghi** [comment]
It's already there but just sold out. The timeline one is for Small Prismatic Shard taught by a trainer later.

**Comment by Tenoutoften** [comment]
Alright thanks, someone told me otherwise, closing

**Comment by Shanghi** [comment]
They probably didn't realize items are hidden completely when out of stock instead of grayed out like it normally is on private servers. That still causes a lot of confusion!
