### ISSUE TITLE
Khorium Vein scarcity

### ISSUE THREAD

**Issue by TheRealZaroua** [Atlantiss/NetherwingBugtracker#4515]
[//]: # (Enclose links to things related to the bug using http://wowhead.com or any other TBC database.)
[//]: # (You can use screenshot ingame to visual the issue.)
[//]: # (Write your tickets according to the format:)
[//]: # ([Quest][Azuremyst Isle] Red Snapper - Very Tasty!)
[//]: # ([NPC] Magistrix Erona)
[//]: # ([Spell][Mage] Fireball)
[//]: # ([Npc][Drop] Ghostclaw Lynx)
[//]: # ([Web] Armory doesnt work)
[//]: # (To find server revision type `.server info` command in the game chat.)

**Description**: There's a bug with Khorium Veins not being rare spawns in place of Fel Iron and Adamantite deposites. I spent the last 2½ days mining and found no Khorium Veins at all, which extremely unlikely. The low supply of khorium related trade goods on the AH and their prices also indicate that this isn't just bad luck on my part. 
https://db.excalibur.ws/?object=181557

**Current behaviour**: Khorium Veins do not count as rare spawns of Fel Iron or Adamantite Deposits.

**Expected behaviour**: Fel Iron Deposits and Adamantite Deposits that are completely mined out should sometimes respawn as Khorium Veins,

**Server Revision**: 2682

**Comment by The14me** [comment]
Worth a check if its pulled or not.

**Comment by Godmatik** [comment]
No evidence really, and have not heard any complaints about it this past year on Netherwing.

Closing.
