### ISSUE TITLE
[Item][Thunder Bluff] Hatred of the Centaur (A readable banner upon right clicking, located in the Elder Rise, hut with the druid trainers )

### ISSUE THREAD

**Issue by ndnd123** [Atlantiss/NetherwingBugtracker#4516]
[//]: # (Enclose links to things related to the bug using http://wowhead.com or any other TBC database.)
[//]: # (You can use screenshot ingame to visual the issue.)
[//]: # (Write your tickets according to the format:)
[//]: # ([Quest][Azuremyst Isle] Red Snapper - Very Tasty!)
[//]: # ([NPC] Magistrix Erona)
[//]: # ([Spell][Mage] Fireball)
[//]: # ([Npc][Drop] Ghostclaw Lynx)
[//]: # ([Web] Armory doesnt work)
[//]: # (To find server revision type `.server info` command in the game chat.)

**Description**: 
Hatred of the Centaur (A readable banner upon right clicking, located in the Elder Rise, hut with the druid trainers ) gives the issue "ITEM PAGE MISSING" upon right clicking.
**Current behaviour**:
gives the issue "ITEM PAGE MISSING" upon right clicking.
**Expected behaviour**: 
Shows something to read.
**Server Revision**:

**Comment by Evolvee** [comment]
rev 2688
