### ISSUE TITLE
[NPC][Botanica] High Botanist Freywinn

### ISSUE THREAD

**Issue by Brasso** [Atlantiss/NetherwingBugtracker#4518]
[//]: # (Enclose links to things related to the bug using http://wowhead.com or any other TBC database.)
[//]: # (You can use screenshot ingame to visual the issue.)
[//]: # (Write your tickets according to the format:)
[//]: # ([Quest][Azuremyst Isle] Red Snapper - Very Tasty!)
[//]: # ([NPC] Magistrix Erona)
[//]: # ([Spell][Mage] Fireball)
[//]: # ([Npc][Drop] Ghostclaw Lynx)
[//]: # ([Web] Armory doesnt work)
[//]: # (To find server revision type `.server info` command in the game chat.)

**Current behaviour**:
The tranquility does nothing to the spawned adds.
**Expected behaviour**: 
Tranquility should heal the adds.

**Server Revision**: 
2682

**Comment by Drayo** [comment]
Can confirm, the summoned adds do not get healed despite having the buff on them.

His heal works fine on himself though.

**Comment by Wolffenstein** [comment]
Fixed in rev 3452.
