### ISSUE TITLE
Windcaller Claw credit

### ISSUE THREAD

**Issue by ttghnw** [Atlantiss/NetherwingBugtracker#4519]
[//]: # (Enclose links to things related to the bug using http://wowhead.com or any other TBC database.)
[//]: # (You can use screenshot ingame to visual the issue.)
[//]: # (Write your tickets according to the format:)
[//]: # ([Quest][Azuremyst Isle] Red Snapper - Very Tasty!)
[//]: # ([NPC] Magistrix Erona)
[//]: # ([Spell][Mage] Fireball)
[//]: # ([Npc][Drop] Ghostclaw Lynx)
[//]: # ([Web] Armory doesnt work)
[//]: # (To find server revision type `.server info` command in the game chat.)

**Description**: 

**Current behaviour**:
If he is discovered and you are dead mid fight - no credit and no credit on talking to him

**Comment by 0vertime** [comment]
Yep, got no credit when he turned friendly as I was dead.

**Comment by Demianl** [comment]
Bumping for Evolve who requested me to report this. No credit if you during the fight, but group finishes the boss fight.

**Comment by DragunovUA** [comment]
fix when?
