### ISSUE TITLE
DB/Creature: Kobold Labourers should be hostile

### ISSUE THREAD

**Issue by Teppic1** [Atlantiss/NetherwingBugtracker#452]
**Description**: 

Kobold Labourers (id 80) in Echo Ridge Mine in Northshire don't attack.

**Expected behaviour**: 

They should be hostile. I've seen them marked with a civilian flag in other databases for some reason which makes them not attack, despite being a hostile faction.

**Server Revision**: 

203

**Comment by Teppic1** [comment]
Confirmed here by Scylla: https://youtu.be/ivx6-1Q_IEM?t=5m30s

**Comment by Wolffenstein** [comment]
Fixed in rev 2047.
