### ISSUE TITLE
The Fel and the Furious quest in Shadowmoon Valley

### ISSUE THREAD

**Issue by Styggex** [Atlantiss/NetherwingBugtracker#4521]
[//]: # (Enclose links to things related to the bug using http://wowhead.com or any other TBC database.)
[//]: # (You can use screenshot ingame to visual the issue.)
[//]: # (Write your tickets according to the format:)
[//]: # ([Quest][Azuremyst Isle] Red Snapper - Very Tasty!)
[//]: # ([NPC] Magistrix Erona)
[//]: # ([Spell][Mage] Fireball)
[//]: # ([Npc][Drop] Ghostclaw Lynx)
[//]: # ([Web] Armory doesnt work)
[//]: # (To find server revision type `.server info` command in the game chat.)

**Description**: You can't kill the infernals whilst controlling the Fel Reaver.

**Current behaviour**:You can't kill the infernals whilst controlling the Fel Reaver.

**Expected behaviour**: The infernals are supposed to be killable by the Fel Reaver you're controlling

**Server Revision**: 2682

**Comment by Evolvee** [comment]
rev 2687
