### ISSUE TITLE
Spacebar underwater jumps instead of swimming up.

### ISSUE THREAD

**Issue by Easters** [Atlantiss/NetherwingBugtracker#4523]
**Description**: When underwater using the spacebar jumps rather than swimming towards the surface.

**Current behaviour**: Spacebar jumps underwater.

**Expected behaviour**: Spacebar should swim towards the surface of the water.

**Server Revision**:

**Comment by Easters** [comment]
wait it should be like that?


> #1790 Nope.

**Comment by Brasso** [comment]
> Peglaa commented on 22 Oct 2018
> 
> This is client side. This cant be fixed. It's how it was in retail TBC. Proper swimming while holding space was introduced in WotLK.
