### ISSUE TITLE
My guild completely disappeared

### ISSUE THREAD

**Issue by Todarac** [Atlantiss/NetherwingBugtracker#4524]
[//]: # (Enclose links to things related to the bug using http://wowhead.com or any other TBC database.)
[//]: # (You can use screenshot ingame to visual the issue.)
[//]: # (Write your tickets according to the format:)
[//]: # ([Quest][Azuremyst Isle] Red Snapper - Very Tasty!)
[//]: # ([NPC] Magistrix Erona)
[//]: # ([Spell][Mage] Fireball)
[//]: # ([Npc][Drop] Ghostclaw Lynx)
[//]: # ([Web] Armory doesnt work)
[//]: # (To find server revision type `.server info` command in the game chat.)

**Description**: 
Around January 19th, around 9pm UTC-6 (almost exactly 48 hours ago), I formed an alliance guild called "Spamalot". It was just a couple of friends and myself. We made silly ranks and got the guild the way we wanted it.

Around the next day, January 20th, the guild was completely missing from everyone who joined. The "Guild" tab is greyed out, and none of us are in any guild. As far as we know, there was not a rollback to before we made the guild, because multiple of us had leveled up since making the guild.

Is this a common problem? can I get my guild back instead of getting 10 signatures again?

**Current behaviour**:

Guild completely disappeared with no warning. It is still this way.

**Expected behaviour**: 

A guild should continue to exist a day after you make it.

IGN: Todarac

**Server Revision**: 
2682

**Comment by Fuzedknight** [comment]
Others are having this issue including myself, every single time I log on I am ejected from my guild yet on their end I am still in the guild. They have to manually kick me and reinvite me for me to be "back in" the guild on my end.

**Comment by Todarac** [comment]
Every single person in my guild got kicked, so the guild no longer exists for us

**Comment by joltox** [comment]
I am having the same issue, every time i log out and back in I can not see guild chat, the channel is greyed out. But i can see others guild chat!

**Comment by Todarac** [comment]
Ive given up on getting a GM to give it back. They are not responded to my ingame tickets or to this. I'm just getting the 10 signatures again.

10/10 great server
