### ISSUE TITLE
[NPC][Botanica] Thorngrin the Tender hellfire

### ISSUE THREAD

**Issue by Brasso** [Atlantiss/NetherwingBugtracker#4529]
[//]: # (Enclose links to things related to the bug using http://wowhead.com or any other TBC database.)
[//]: # (You can use screenshot ingame to visual the issue.)
[//]: # (Write your tickets according to the format:)
[//]: # ([Quest][Azuremyst Isle] Red Snapper - Very Tasty!)
[//]: # ([NPC] Magistrix Erona)
[//]: # ([Spell][Mage] Fireball)
[//]: # ([Npc][Drop] Ghostclaw Lynx)
[//]: # ([Web] Armory doesnt work)
[//]: # (To find server revision type `.server info` command in the game chat.)

**Current behaviour**:
The area that deals damage of his hellfire is currently much smaller than the animation. 

**Expected behaviour**: 
Should deal damage on the entire affected area. https://youtu.be/h-mzL1K6jlE?t=256

**Server Revision**: 
2682

**Comment by devo6969** [comment]
This is what its like currently on the PTR. I don't know if its intended though. I tried to go on retail to see but... i wouldn't take any damage so hard to tell.
https://www.youtube.com/watch?v=lt1l-oewmHY

**Comment by Godmatik** [comment]
Watched a few classic videos, seems like the range currently is fine and matches what I see.

Not a bug.
