### ISSUE TITLE
Childrens Week quests

### ISSUE THREAD

**Issue by LoGReeper** [Atlantiss/NetherwingBugtracker#453]
**Description**: Childrens Week first 3 quests auto completing without going to the destinations.

**Current behaviour**: When you accept each of the first 3 quests, it auto completes without you taking the child to the destinations : https://i.imgur.com/LZMYXHd.png

**Expected behaviour**:  Take your child to each destination and use the whistle to summon your child to hand in.

**Server Revision**:

**Comment by wtRCH** [comment]
Duplicate of https://github.com/Atlantiss/NetherwingBugtracker/issues/146
