### ISSUE TITLE
Teron Gorefiend, I am...

### ISSUE THREAD

**Issue by MurlNW** [Atlantiss/NetherwingBugtracker#4530]
quest still functioning the way the previous bug tickets reported

**Description**: 

**Current behaviour**:

**Expected behaviour**: 

**Server Revision**:

**Comment by Tenoutoften** [comment]
And that's because the server hasn't been updated yet!
Server is still on 2682 which you can check with writing ".server info" in-game.
This quest is fixed in 2684
