### ISSUE TITLE
[Nagrand] Alliance inn not working

### ISSUE THREAD

**Issue by djgorra** [Atlantiss/NetherwingBugtracker#4531]
**Description**: The inn in Telaar, Nagrand does not appear to be giving rested XP or allowing the player to log out instantly as inns usually do.

**Server Revision**: 2682
![untitled](https://user-images.githubusercontent.com/24322889/51657197-ccd83e00-1f71-11e9-86d0-ccd3392fb04b.png)

**Comment by Wolffenstein** [comment]
Fixed in rev 3198.
