### ISSUE TITLE
[Quest] [Mail] Messenger Hermesius' quest item sent in the mail (A Letter from the Admiral)

### ISSUE THREAD

**Issue by Spaztick** [Atlantiss/NetherwingBugtracker#4532]
**Description**: 
Messenger Hermesius' quest item sent in the mail (A Letter from the Admiral) has two copies of it in the mail attachments

**Expected behaviour**: 
Should be just 1.

**Server Revision**: 
2682

**Comment by Evolvee** [comment]
https://github.com/Atlantiss/NetherwingBugtracker/issues/5821
