### ISSUE TITLE
[Spell][Fear] Undertuned

### ISSUE THREAD

**Issue by Ravyd** [Atlantiss/NetherwingBugtracker#4534]
Fear is extremely undertuned, and breaks on gray and green mobs without reason completely randomly. The spell never reaches full duration whether dotted, undotted, attacked, unattacked, etc. **The spell is unreliable, that's the best way I can describe it.** 

In general, fear should almost never break unless the mob is nuked (even then, it should not autobreak), or hit very hard. Generally, even with a full set of warlock dots on the target (corruption, CoA, immolate, UA, and Siphone Life) fear should last its entire duration. It is _extremely_ rare for fear to break with just a normal dot rotation up, or for no reason whatsoever. 

Immolate's initial damage has been known to break fear but this, again, happens only rarely. 

The spell in its current form almost isn't worth using. It's extremely annoying and distracts from gameplay. It is a form of CC, though a very touchy one to use. It's the equivalent of sheep just randomly breaking for no reason; it's gamebreaking for the class. PVE/PVP encounters that could normally easily be handled turn into a nightmare when just CCing one mob with fear becomes a full-time job. 

I find myself actually recasting fear if I need to keep a mob feared the second the first one lands because I expect a fear break. 

Proper behavior for fear is that the mob should be **_expected to stay feared_**, not break. Fear breaking is a rare occurrence and should be treated as an exception, not an expectation, and should only happen if the mob is nuked (shadowbolt, frostbolt, a 2h melee attack, or immolate initial damage occasionally) or if you are extremely unlucky with a pulse. DoTs should generally _never_ break fear.

Video:

In this video, we can see that not one fear reaches a full duration, on a mob that possess no special shadow resistance or fear resistance, and is green to the player

[https://clips.twitch.tv/HorribleModernClipsmomWOOP](url)

Again, we see repeated breaking and no full duration fear against a green mob

[https://clips.twitch.tv/ResilientRamshackleTardigradeWholeWheat?tt_medium=clips_api&tt_content=url](url)

Another example 

[https://clips.twitch.tv/FilthyExquisiteKuduFunRun?tt_medium=clips_api&tt_content=url](url)

And another example

[https://clips.twitch.tv/AltruisticDifficultWolfANELE?tt_medium=clips_api&tt_content=url](url)

None of these even remotely resemble proper fear mechanic behavior.

Server Revision 2682

**Comment by Tenoutoften** [comment]
You have to document how rare it should break

**Comment by Ravyd** [comment]
> You have to document how rare it should break

How could you possibly do that. It's all subjective. There's far too many thing going on with fear (pulses, resistances, mob levels, damage, type of damage) to tell you with 100% certainty exactly what it should be.

I can pull up TBC videos but there's going to be an extremely high amount of "chance" to say anything with 100% confidence.

Just look at the videos I linked. If you can look me in the eye and tell me with a straight face that's proper mechanic behavior, as someone who's played since vanilla I'm just going to laugh in your face

**Comment by Ravyd** [comment]
He's a video by a TBC warlock showing fear not even breaking after immolates, let alone normal dot rotation.

[https://www.youtube.com/watch?v=W9ID8a_6a28](url)

In the preface for this video, he's saying he's sick of all the nerf fear posts. So this tells me that TBC fear was very strong. Basically, when we're to the point where it almost never breaks, that's the proper tuning.

Go ahead and watch my clips again. That was probably close to 20 fears on green mobs, not a single fear reached full duration without immolate being cast on a single feared target, nor a shadowbolt. At most, the target had corruption and CoA up simultaniously. For our purposes, that should be basiclaly the equivalent of not being dotted at all.

As I said earlier, fear should not break with a warlock's ENTIRE dot rotation up, which means immolate, corruption, UA, curse of agony, AND siphon life. At the same time.

**Comment by Ravyd** [comment]
From comments in the above video:

> Rathelas
> 11 years ago
> For a DOTlock fear is King, but for a destrolock Fear is close to moot. Of course there is the benefit of the short cast interrupt and the enemy going away from you﻿

Exactly. Unless you are dropping direct damage spells (immolate, shadowbolt) fear should not break 90% of the time. Meaning dots, for all intents and purposes, should hardly ever be a factor in fear breaking

**Comment by Drayo** [comment]
Just from reading this it seems like higher damage by a single spell should have a higher chance to break fear.

Numbers are just examples.

Meaning damage under 100 should only have a small chance to break it (5%), damage between 100 and 200 have a higher chance (15%) and over 300 (30%), over 400 (60%) and so on.

What the numbers should actually be, is up to debate though, it's hard to get it right.

I don't know how it works atm, but another way to do it would be to not take single ticks into account but damage taken in the last 5 seconds in relation to the mobs HP. Here we have the problem that big damage spells should break fear pretty consistently, but depending on the mob HP it might nor do that in this case.

Just some thoughts on the matter. I too have noticed fear being nearly useless while leveling, dots were alright but it never lasted more that ~5 seconds even without big damage, ever. Any big spell would break fear for sure and from what I remember, that did not happen on retail with such consistency.

**Comment by Ravyd** [comment]
> Just from reading this it seems like higher damage by a single spell should have a higher chance to break fear.
> 
> Numbers are just examples. What the numbers should actually be, is up to debate though, it's hard to get it right.
> 
> Meaning damage under 100 should only have a small chance to break it (5%), damage between 100 and 200 have a higher chance (15%) and over 300 (30%), over 400 (60%) and so on.
> 
> This is difficult because you can't do it with raw numbers, it has to scale, that's where it gets a bit awkward to implement on single ticks.
> 
> I don't know how it works atm, but another way to do it would be to not take single ticks into account but damage taken in the last 5 seconds in relation to the mobs HP. Here we have the problem that big damage spells should break fear pretty consistently, but depending on the mob HP it might nor do that in this case.
> 
> Just some thoughts on the matter. I too have noticed fear being nearly useless while leveling, dots were alright but it never lasted more that ~5 seconds even without big damage, ever. Any big spell would break fear for sure and from what I remember, that did not happen on retail with such consistency.

Yes that is exactly right. Direct damage spells, IE frostbolt, fireball, shadowbolt, immolate, etc. have a high chance of breaking fear, but they do not always. Periodic damage spells have litttle to no chance to break fears. Additionally, there is a pulse that ticks every second or so that gives a chance for the fear to fail. 

As you said, fears never reach full duration which is absolutely 100% wrong. Fears should almost always reach full duration, them breaking is the exception not the expectation. 

If a fear fails, you should be surprised (unless you chuck a shadowbolt at it). In this current build, I do not expect a fear to finish under any circumstances. Hell. I don't expect a mob being feared without taking any damage at all to reach full duration. That is 100% unarguably wrong. 

I think it's the pulse that's the issue here. But since this mechanic is so complicated, it's hard to say for sure.

In my videos, I would expect that fear behavior from an orange or red mob. That would be completely understandable. But all mobs I fought were green to me, and you see almost the exact same behavior with gray mobs.

**Comment by Ravyd** [comment]
> Just to mention, I deleted it because on reading it again the solutions make no sense, it's hard to find a cause when you don't know how it's implemented.
> 
> Unfortunately a "fix" is kinda unlikely, just from experience over the last few months, they want proof for this stuff, which is absolutely understandable in most cases, but these kind of issues are so subjective that proving anything is nearly impossible.
> 
> You can watch 50 videos and come up with numbers, but since you don't even know how it works behind the scenes those numbers could be completely useless, so why even bother doing it without having any initial information.
> 
> So here is the best thing one can do for now:
> 
> **Fear is useless on this server, experimental changes would be welcome.**

My thoughts exactly. Or make it unbreakable and dial it back from there. From the small amount of information I have to go off of for tbc the general consensus is that fear is very strong in that expansion, and unless you're doing heavy, heavy damage it should not break. This is nowhere near what we're seeing on this server.

And yes, very good point in regards to numbers. There's no such thing as proper fear numbers. You can watch 100 videos and get 1000 data points, but at the end of the day you have absolutely no idea what broke the fear. Was is mob resistance? Was it damage? was it a pulse? Nobody knows.

And even if you were somehow able to figure out what broke it, that's only 1000 data points. The results of which are nowhere near a large enough sample to mould an entire server to those numbers.

Fear is very strong. If you get feared, expect to stay feared for the spells full duration. That's basically what I would call "working as intended" based on my retail TBC experience, other TBC pserver experience, vanilla experience, TBC videos, and general period-accurate TBC testimony.

**Comment by itsjojotbh** [comment]
https://wow.gamepedia.com/Heartbeat_resist

https://wow.gamepedia.com/index.php?title=Fear_effect&oldid=1550231
Patch 2.1.0 (2007-05-22): "Chance to break crowd control from damage: The increased chance for a spell to break from taking a critical strike has been removed. Instead, all targets over level 60 have a slightly larger chance to break out of crowd-controlling effects when they take damage." 

I believe fear has a damage threshold, which if reached will instantly break the fear effect, in addition to having a chance to break each time the target takes damage. With this in mind, fear breaking early is not a strange occurence. I think the chance to break per point of damage taken might be too high, causing it to break more often than it should.

I'm quite certain the fear mechanic works exactly the same in patch 8.1 as patch 2.4.3 regarding breaking on damage, maybe tweeting a developer and ask about it could provide some insight?

**Comment by Ravyd** [comment]
> https://wow.gamepedia.com/Heartbeat_resist
> 
> I believe this is what you're referring to as "pulses", the game periodically checking for resistance. Maybe you could try using curse of elements on the feared target to reduce the shadow resistance of the target, which in turn would reduce the chance for heartbeat resists and fear breaking early.
> 
> https://wow.gamepedia.com/index.php?title=Fear_effect&oldid=1550231
> Patch 2.1.0 (2007-05-22): "Chance to break crowd control from damage: The increased chance for a spell to break from taking a critical strike has been removed. Instead, all targets over level 60 have a slightly larger chance to break out of crowd-controlling effects when they take damage."
> 
> I believe fear has a damage threshold, which if reached will instantly break the fear effect, in addition to having a chance to break each time the target takes damage. With this in mind, fear breaking early is not a strange occurence. I think the chance to break per point of damage taken might be too high, causing it to break more often than it should.
> 
> I'm quite certain the fear mechanic works exactly the same in patch 8.1 as patch 2.4.3 regarding breaking on damage, maybe tweeting a developer and ask about it could provide some insight?
> 
> Edit: formatting and punctuation

Yes, by pulses I mean heartbeat resists. 

Regarding your comment about curse of elements, are you implying I do that in the normal course of gameplay or as a testing point? I'm level 32, I don't even have curse of elements yet. If you're implying that a warlock needs to have CoE up on a target in order to expect a full-length fear, that is absolutely ridiculous. Curses are a cornerstone of warlocks, and since only one can be applied at a time, the idea of gimping an entire toolkit of useful mechanics so that you can use a _basic mechanic_ is hilarious.

In my videos, the mobs I were fighting were ~5 levels lower than I was, so any heartbeat mechanics should have been minimal or non-existant. 

There is no "damage cap" with fear. And even if there was, at no point in my video would I have met that at any point. None of these hypothetical arguments are relevant to the proof I have clearly presented in the OP.

I will say again, if you viewed those clips and can stand there with a straight face and tell me that fear is working as intended then my only response is "lol"

**Comment by Ravyd** [comment]
> Fear is supposed to break from damage and the threshold is also supposed to increase based on the Warlock's spell damage (more spell dmg = more dmg needed to potentially break Fear). One thing to keep in mind is that all through retail vanilla and TBC, Fear was a hell of a buggy spell, and that it'll be nigh impossible to perfectly replicate how buggy the spell was on a private server. Your best bet is to go for an approximation of what it was, while keeping in mind that Shadow Resist, Hit%, DoT dmg, and direct dmg are all factors in Fear breaking early.

Do you have any sources? I'm curious to learn as much as possible regarding the behind-the-scenes mechanics of fear.

As far as I know there are a few mechanics involved with fear:

1. Shadow resistance
2. Spell hit (passive resistance)
3. Periodic damage
4. Burst damage
 a. school of burst damage?
5. Heartbeat resistance

As you can see, this is one of the most, if not the most complicated mechanic in the game

**Comment by itsjojotbh** [comment]
> There is no "damage cap" with fear. And even if there was, at no point in my video would I have met that at any point. None of these hypothetical arguments are relevant to the proof I have clearly presented in the OP.

Yes, a damage cap exists on Fear effects, this is well known. Patch notes from 3.1 states the damage threshold was reduced
Wrath of the Lich King Patch 3.1.0 (2009-04-14): The damage threshold for  [Fear], Psychic Scream,  [Hex],  [Intimidating Shout], and  [Turn Evil] to break early has been significantly reduced.
(https://wow.gamepedia.com/Psychic_Scream#Patches_and_hotfixes)

Nothing in patch notes will state the threshold was **added**, hence I can draw the conclusion it has always existed.

**Comment by Ravyd** [comment]
> > There is no "damage cap" with fear. And even if there was, at no point in my video would I have met that at any point. None of these hypothetical arguments are relevant to the proof I have clearly presented in the OP.
> 
> Yes, a damage cap exists on Fear effects, this is well known. Patch notes from 3.1 states the damage threshold was reduced
> Wrath of the Lich King Patch 3.1.0 (2009-04-14): The damage threshold for [Fear], Psychic Scream, [Hex], [Intimidating Shout], and [Turn Evil] to break early has been significantly reduced.
> (https://wow.gamepedia.com/Psychic_Scream#Patches_and_hotfixes)
> 
> Nothing in patch notes will state the threshold was **added**, hence I can draw the conclusion it has always existed.

In any case, the point is irrelevant to the proof in the OP

**Comment by Jalapan** [comment]
Warlock here, i have also noticed that fear is almost useless, often first dot tick will break my fear

**Comment by Wolffenstein** [comment]
Should break less easily after revision 2700. Will require further testing and possibly adjustments.

**Comment by Ravyd** [comment]
> Should break less easily after revision 2700. Will require further testing and possibly adjustments.

Thank you Wolf

**Comment by Ravyd** [comment]
Though I would urge you to keep this open until it is actually resolved until then it is an ongoing issue.

My $0.02

**Comment by Ravyd** [comment]
> > Should break less easily after revision 2700. Will require further testing and possibly adjustments.
> 
> thx @Wolffenstein its much better, but it still feels undertuned, the dmg threshhold should be atleast 25% higher

I also agree with this, which is why I don't think the issue should be closed. As of now I don't know if I need to make another post or if he's still following this issue
