### ISSUE TITLE
[Quest] Kodo roundup

### ISSUE THREAD

**Issue by deathkneel** [Atlantiss/NetherwingBugtracker#4535]
[//]: # (Enclose links to things related to the bug using http://wowhead.com or any other TBC database.)
[//]: # (You can use screenshot ingame to visual the issue.)
[//]: # (Write your tickets according to the format:)
[//]: # ([Quest][Azuremyst Isle] Red Snapper - Very Tasty!)
[//]: # ([NPC] Magistrix Erona)
[//]: # ([Spell][Mage] Fireball)
[//]: # ([Npc][Drop] Ghostclaw Lynx)
[//]: # ([Web] Armory doesnt work)
[//]: # (To find server revision type `.server info` command in the game chat.)

**Description**: 
Attack a kodo and then use the Kodo Kombobulator on it.

**Current behaviour**:
The kodo doesn't follow you.

**Expected behaviour**: 
The kodo should follow you once you tamed it even you attacked it before.

**Server Revision**: 
2682

**Comment by Manaci** [comment]
Fixed
