### ISSUE TITLE
[Quest] Elixir of Agony

### ISSUE THREAD

**Issue by Ravyd** [Atlantiss/NetherwingBugtracker#4536]
Current Behavior:

I am unable to pick up the mushrooms for this quest, even after relogging, and dropping the quest and repicking it.

Proper behavior:

The mushrooms should be lootable. 

Video:

[https://clips.twitch.tv/MotionlessBitterDonkeyTwitchRaid](url)

Server Revision: 2682

**Comment by Evolvee** [comment]
workrs fine for me, disable your addons

**Comment by Ravyd** [comment]
Why would addons have any effect on looting a mushroom lol.

I'm level 31 so obviously I haven't had this issue prior

**Comment by wtRCH** [comment]
Worked for me too.
