### ISSUE TITLE
[NPC] [The Barrens] Wooly Kodo

### ISSUE THREAD

**Issue by inscaped** [Atlantiss/NetherwingBugtracker#4538]
**Description**: 
Looks like Wooly Kodo is too heavy for this land. Diving into the texture.
**Current behaviour**:
Weird walking path (Wooly Kodo and others besides him)
**Expected behaviour**: 
Should walk in a pack around mountains and hills.
**Server Revision**: 
2682

![wowscrnshot_012319_162116](https://user-images.githubusercontent.com/30598442/51677907-21200400-1fec-11e9-9b1b-eb51c57e9a8f.jpg)
![wowscrnshot_012319_162205](https://user-images.githubusercontent.com/30598442/51677909-21b89a80-1fec-11e9-9e54-3fbea7dcb1aa.jpg)
![wowscrnshot_012319_162134](https://user-images.githubusercontent.com/30598442/51677911-21b89a80-1fec-11e9-9acc-e39bee0abb6a.jpg)

**Comment by The14me** [comment]
Rev.3483 not an issue anymore.
