### ISSUE TITLE
[NPC][Movement] Grimscale Seer - Leashing Leads to Floating on Nearby Torch

### ISSUE THREAD

**Issue by ghost** [Atlantiss/NetherwingBugtracker#454]
**Description**: There is one particular murloc that does not seem to path from the spawn position. When pulled toward the nearby hill and aggro drops where it leashes back to this position, it no longer remains level on the ground and instead is standing on top of a torch near to the spawn point. Depending on the route one takes to reproduce this, you can see there is an issue where the murloc also, instead of running around the torch, seemingly jumps on top of it and back down.

**Current behaviour**: Grimscale Seer sees nearby torch as a non-illegal path and upon leash back, remains on top of it until killed/reset or pulled to leash from a separate direction.

**Expected behaviour**: The NPC should navigate around the torch and remain level to the ground.

**Server Revision**: 2045

```
AtlantissCoreTBC - rev: 2045 
Online players: 69 (max: 69) 
Active connections: 72 (max: 74) Queued connections: 0 (max: 0) 
Server uptime: 17 Minute(s) 44 Second(s). 
Current time: 2018-09-25 02:15:37 
Content Patch: 203. 
You are outdoors 
Map: 530 (Outland) Zone: 3430 (Eversong Woods) Area: 3911 (Tranquil Shore) 
X: 9090.219727, -5855.770020, 0.258759 Orientation: 3.127720 
grid[49,21]cell[0,0] InstanceID: 0 
 ZoneX: 27.782133 ZoneY: 59.434921 
GroundZ: 0.260835 FloorZ: 0.260835 Have height data (Map: 1 VMap: 1 Col: 1) 
------------------------ 
Entry: 15950, SpawnId - (Entry: 15950, Id: 2), GUIDLow: 11047
```

**Comment by Tereneckla** [comment]
![WoWScrnShot_010720_124925](https://user-images.githubusercontent.com/50233983/71893504-2d916400-314c-11ea-90c2-38df4e322e9c.jpg)
Walked with him to the hill on the other side of the torches and reset him. (Around 28, 58)

**Comment by Godmatik** [comment]
Rev 4016 - can not reproduce, no longer an issue.
Likely fixed when Wolf updated pathing last year.
