### ISSUE TITLE
[Spell] Blessing of Auchindoun

### ISSUE THREAD

**Issue by Sabre142** [Atlantiss/NetherwingBugtracker#4540]
**Description**: 
If a faction captures and controls the five Spirit Towers in the Bone Wastes of Terokkar Forest, every player in that zone of that faction will be buffed with the Blessing of Auchindoun. In addition to the experience and damage boost, it allows buffed players to obtain Spirit Shards from the all of the bosses in the Auchindoun instances.

**Current behaviour**:
The player does not receive the buff when they zone into an auchindoun instance in ghost form. They will have to zone out and in again to get it.

**Expected behaviour**: 
The player should be able to get it even if after zoning in after a death.

**Server Revision**: 
2682

**Comment by Zarant** [comment]
#4293
