### ISSUE TITLE
[AI][NPC][FACTION]

### ISSUE THREAD

**Issue by syphex97** [Atlantiss/NetherwingBugtracker#4543]
[//]: # (Enclose links to things related to the bug using http://wowhead.com or any other TBC database.)
[//]: # (You can use screenshot ingame to visual the issue.)
[//]: # (Write your tickets according to the format:)
[//]: # ([Quest][Azuremyst Isle] Red Snapper - Very Tasty!)
[//]: # ([NPC] Magistrix Erona)
[//]: # ([Spell][Mage] Fireball)
[//]: # ([Npc][Drop] Ghostclaw Lynx)
[//]: # ([Web] Armory doesnt work)
[//]: # (To find server revision type `.server info` command in the game chat.)

**Description**: 
Guards in Area 52 do not attack players who engage in pvp, they only turn hostile but doesnt do anything.

**Current behaviour**:
Turns hostile when another player pvp, but does not engage the player 

**Expected behaviour**: 
Should engage the player who pvp in the zone.

**Server Revision**: 
2682

**Comment by The14me** [comment]
rev.3460 they kill me like a bug.
Can be closed.
