### ISSUE TITLE
[Spell][Paladin] Seal of the crusader

### ISSUE THREAD

**Issue by unlucky313** [Atlantiss/NetherwingBugtracker#4545]
[//]: # (Enclose links to things related to the bug using http://wowhead.com or any other TBC database.)
[//]: # (You can use screenshot ingame to visual the issue.)
[//]: # (Write your tickets according to the format:)
[//]: # ([Quest][Azuremyst Isle] Red Snapper - Very Tasty!)
[//]: # ([NPC] Magistrix Erona)
[//]: # ([Spell][Mage] Fireball)
[//]: # ([Npc][Drop] Ghostclaw Lynx)
[//]: # ([Web] Armory doesnt work)
[//]: # (To find server revision type `.server info` command in the game chat.)

**Description**: 
Seal of the Crusader is supposed at Rank 1 to increase holy damage taken by target after casting judgement by up to 23. Currently, without it I do 14 holy damage and with it 17, every auto. meaning, it's not a random number, but just sustained increase of +3 holy damage.
**Current behaviour**:
Inaccurately buffing holy damage. Sustained +3 holy damage instead of randomed up to +23.
![seal](https://user-images.githubusercontent.com/47005701/51695470-6bf94600-2003-11e9-9778-7edef3bdf32f.png)

**Expected behaviour**: 
To increase damage according to the tooltip. On rank 1, varying up to +23.
**Server Revision**: 
2682
![se2al](https://user-images.githubusercontent.com/47005701/51695507-84696080-2003-11e9-8ca5-f6a009f3875e.png)

**Comment by Silbotronic** [comment]
"Increases damage by up to 23" doesn't mean a random number between 1 and 23, it means it gives you 23 extra spell damage, which is then affected by the coefficient of the individual spell.
