### ISSUE TITLE
Elemental Overload procs trigger Elemental Mastery critical strike

### ISSUE THREAD

**Issue by napalmez** [Atlantiss/NetherwingBugtracker#4547]
[//]: # (Enclose links to things related to the bug using http://wowhead.com or any other TBC database.)
[//]: # (You can use screenshot ingame to visual the issue.)
[//]: # (Write your tickets according to the format:)
[//]: # ([Quest][Azuremyst Isle] Red Snapper - Very Tasty!)
[//]: # ([NPC] Magistrix Erona)
[//]: # ([Spell][Mage] Fireball)
[//]: # ([Npc][Drop] Ghostclaw Lynx)
[//]: # ([Web] Armory doesnt work)
[//]: # (To find server revision type `.server info` command in the game chat.)

**Description**: 
Elemental Mastery (Elemental Shaman talent tree) triggers a critical strike from spell casts, such as Chain Lightning, Shock spells, Lightning bolt etc.
Lightning Overload (Elemental Shaman talent tree) talent gives a 4-20% chance to cast a second similar spell that costs no mana and deals half damage.

The problem with these two is, when you cast a spell, and turn on Elemental Mastery after the first cast, to cast another 100% crit spell, IF the first cast triggers Lightning Overload, it produces another cast of a smaller spell and that smaller proc triggers the Elemental Mastery 100% critical strike. You not only lose the cooldown, but the damage you wanted to do with the big second spell.

Asked a GM today about it, seems to him that this is indeed not how it is intended to work, as you cannot plan for such an occasion. 

Also, Lightning overload procs do not trigger clearcasting for shamans, so I think it should not trigger Elemental Mastery.

**Current behaviour**:
Lightning overload procs trigger Elemental Mastery 100% critical strike and uses up the cooldown.
**Expected behaviour**: 
Lightning overload procs should not trigger elemental mastery's effect.
**Server Revision**:

**Comment by Macumbafeh** [comment]
Up ! This bug is insane for us ! i would report it, but it's already reported !

**Comment by jasonbourne109** [comment]
Can confirm that this bug is still happening as of 2.1.

**Comment by Macumbafeh** [comment]
Not fixed already.

**Comment by ccueto36** [comment]
October 22 and still not fixed. I recently turned elemental spec after reaching 60 and noticed right away that Lighting Overload was triggering the Elemental Mastery ability, this is definitely not blizzlike and it literally ruins the Elemental Mastery ability unless it's used at the very beginning of the fight, before casting any spell.

**Comment by Wolffenstein** [comment]
Fixed in rev 3170.
