### ISSUE TITLE
Haleha in Winterspring

### ISSUE THREAD

**Issue by Edberg1001** [Atlantiss/NetherwingBugtracker#4549]
[//]: # (Enclose links to things related to the bug using http://wowhead.com or any other TBC database.)
[//]: # (You can use screenshot ingame to visual the issue.)
[//]: # (Write your tickets according to the format:)
[//]: # ([Quest][Azuremyst Isle] Red Snapper - Very Tasty!)
[//]: # ([NPC] Magistrix Erona)
[//]: # ([Spell][Mage] Fireball)
[//]: # ([Npc][Drop] Ghostclaw Lynx)
[//]: # ([Web] Armory doesnt work)
[//]: # (To find server revision type `.server info` command in the game chat.)

**Description**: 
Haleha in Winterspring. She gives the amulet for Onyxia attunement without finishing the questchain.
The teleport next to Haleha does not work (It should teleport you to the cave underneth her).
**Current behaviour**:
Haleha in Winterspring. She gives the amulet for Onyxia attunement without finishing the questchain.
The teleport next to Haleha does not work (It should teleport you to the cave underneth her).
**Expected behaviour**: 
Haleha in Winterspring. She gives the amulet for Onyxia attunement without finishing the questchain.
The teleport next to Haleha does not work (It should teleport you to the cave underneth her).
**Server Revision**:

**Comment by The14me** [comment]
Rev.3460 she doesn't give the amulet anymore and the teleport work.
Can be closed.
