### ISSUE TITLE
[Spell][Warrior] Rend

### ISSUE THREAD

**Issue by bukowywowwe** [Atlantiss/NetherwingBugtracker#455]
[spell=772]

**Description**: When clicking Rend spell it takes a good 1-1.5 seconds for it to effect the target. Seem to remember that being an instant cast/effect unto the target after initial sound effect.

**Current behaviour**: Click rend, and it takes 1.5 seconds to effect target

**Expected behaviour**: Click rend and the sound effect starts as the effect hits the target, should be instant.

**Server Revision**:

**Comment by knasen88** [comment]
you mean the time before it ticks or application of debuff?

**Comment by netherwingbta** [comment]
Currently unable to reapply rend on a target before the old debuff has ran out.
![wow 2018-11-01 03-30-22-60](https://user-images.githubusercontent.com/43872263/47829265-c8432580-dd86-11e8-84be-baccf749abb7.png)

Revision 2244

**Comment by Brasso** [comment]
Unable to reproduce, works fine. https://i.imgur.com/f9ttpNJ.gifv
