### ISSUE TITLE
Scholomance incorrect mob immunities

### ISSUE THREAD

**Issue by Jseay1313** [Atlantiss/NetherwingBugtracker#4551]
**Current behaviour**: Demon mobs, and Risen Constructs in this zone are immune to spells, only the mini skeleton mobs prior to Jandice Barov should be spell immune.

https://wowwiki.fandom.com/wiki/Risen_Construct These things near rattlegore are 100% not immune to spells but are here for some reason.

**Expected behaviour**:  Not spell immune

**Server Revision**: 2691

**Comment by Evolvee** [comment]
rev 2827

**Comment by Lockanloads** [comment]
Its still bugged now

**Comment by Evolvee** [comment]
![image](https://user-images.githubusercontent.com/1942409/53305154-20de8700-387e-11e9-89ef-dd93e4dc3220.png)
![image](https://user-images.githubusercontent.com/1942409/53305155-2340e100-387e-11e9-9eba-41ab2725bf21.png)
