### ISSUE TITLE
[Spell][Warlock][Pet] Seduction not casting

### ISSUE THREAD

**Issue by TheRealZaroua** [Atlantiss/NetherwingBugtracker#4552]
[//]: # (Enclose links to things related to the bug using http://wowhead.com or any other TBC database.)
[//]: # (You can use screenshot ingame to visual the issue.)
[//]: # (Write your tickets according to the format:)
[//]: # ([Quest][Azuremyst Isle] Red Snapper - Very Tasty!)
[//]: # ([NPC] Magistrix Erona)
[//]: # ([Spell][Mage] Fireball)
[//]: # ([Npc][Drop] Ghostclaw Lynx)
[//]: # ([Web] Armory doesnt work)
[//]: # (To find server revision type `.server info` command in the game chat.)

**Description**: Succubus skill Seduction doesn't cast at all. Either through macro, clicking the spell bar, or clicking from the spell book. It worked flawlessly a few builds ago.
https://db.excalibur.ws/?spell=6358

**Current behaviour**: Try to cast Seduction, Succubus does nothing.

**Expected behaviour**: Try to cast Seduction, Succubus casts Seduction.

**Server Revision**: 2691

**Comment by Azalen** [comment]
This is true for some - but not all mobs. You can easy confirm this issue in Shadow Labyrinth on the trash packs right before Murmur. Even though all mobs there are humanoids you can only seduce the Spellcaster and the Summoner - but not the warrior (the mobs in warrior t3).

**Comment by Desst** [comment]
a ran dungeons in outland while levelling and can confirm that some mobs are immune to CC (in normal) which should not be in some dungeons

**Comment by BamboozleNW** [comment]
Kara PTR, This is bugged. Tested on multiple humanoids, some she will try to seduce, some she will not. Here is H Slabs as an example. https://www.youtube.com/watch?v=SLAxElA17f8

**Comment by Wolffenstein** [comment]
Fixed in rev 3451.
