### ISSUE TITLE
[Quest] Against the Legion

### ISSUE THREAD

**Issue by toporc26** [Atlantiss/NetherwingBugtracker#4553]
[//]: # (Enclose links to things related to the bug using http://wowhead.com or any other TBC database.)
[//]: # (You can use screenshot ingame to visual the issue.)
[//]: # (Write your tickets according to the format:)
[//]: # ([Quest][Azuremyst Isle] Red Snapper - Very Tasty!)
[//]: # ([NPC] Magistrix Erona)
[//]: # ([Spell][Mage] Fireball)
[//]: # ([Npc][Drop] Ghostclaw Lynx)
[//]: # ([Web] Armory doesnt work)
[//]: # (To find server revision type `.server info` command in the game chat.)

**Description**: 
In quest "Against the Legion" the Wrath Priestess mob will not drop Freshly Drawn Blood which is required to summon Avatar of Sathal
**Current behaviour**:
Wrath Priestess does not drop Freshly Drawn Blood required to summon  Avatar of Sathal

**Expected behaviour**: 
Wrath Priestess should drop Freshly Drawn Blood 100% of the time

**Server Revision**: 
2691

**Comment by Tenoutoften** [comment]
It does drop, just not 100%. I did this quest just a few days ago

**Comment by Tenoutoften** [comment]
[Wowhead comment](https://www.wowhead.com/quest=10641/against-the-legion#comments:id=283759)
![](https://i.gyazo.com/a7188e82ff1f87640b1c8c9f7ecc338a.png)

**Comment by toporc26** [comment]
@Tenoutoften is correct, dropped after a few more kills. closing.
