### ISSUE TITLE
Goblin Mortar and The Mortar: Reloaded

### ISSUE THREAD

**Issue by garbage3588** [Atlantiss/NetherwingBugtracker#4559]
Current behaviour: You can't learn the Goblin Mortar and The Mortar: Reloaded recipes from the goblin engineering trainers.

Expected behaviour: You should be able to learn the Goblin Mortar and The Mortar: Reloaded recipes from the goblin engineering trainers.

Steps to reproduce the problem:

Be a goblin engineer
go see a goblin engineering trainer and try to find The mortar recipes.
Notice that there are no such recipes available to learn.
http://wowwiki.wikia.com/wiki/Goblin_Mortar
http://wowwiki.wikia.com/wiki/The_Mortar:_Reloaded

**Comment by Godmatik** [comment]
Resolved last year in rev 3764
