### ISSUE TITLE
Pets wont attack cc'd target

### ISSUE THREAD

**Issue by mbzz88** [Atlantiss/NetherwingBugtracker#456]
**Description**: Hunter pet will not attack mobs frozen in traps. Sending pet to attack will cause them to move to attack then return to the player immediately. Spam clicking/pressing pet attack fast enough will cause the pet to get close enough and then start attacking trapped mob.

**Current behaviour**: https://youtu.be/qzPN60Qrid8

**Expected behaviour**: Pet attacks as normal when ordered.

**Server Revision**:

**Comment by knasen88** [comment]
try using a different pet mode, agressive or defensive and reproduce, vaguely remember on vanilla servers that passive pets won't break cc even if ordered to.

**Comment by Notmittz** [comment]
Wanted to add to this, just in case it wasn't reported or known, changing pet modes doesn't fix this.  A pet in either Passive or Defensive will refuse to attack a CC target, even if told to do so.  However, it will break the CC target when set to aggressive and ordered to attack

**Comment by mbzz88** [comment]
Just to add a bit more to this, the same issue occurs when trying to send pet to attack "Sunfury Conjurer" npc=20139, while they are channeling the crystal (unsure of the channeled spell name, but the one that gives them "Bloodcrystal Surge" spell=35778". Does not matter if pet is passive,defensive or aggressive.
![wowscrnshot_122218_135617](https://user-images.githubusercontent.com/43509267/50368822-936a8680-05f1-11e9-834f-b0c2e6eeca9b.jpg)

**Comment by dalabu** [comment]
Just to add that the same thing happens with Wyvern sting and Scatter shot not just freezing trap.

**Comment by Manaci** [comment]
Fixed
