### ISSUE TITLE
[Netherstorm][Quest][NPC]Veraku#18544 doesn't despawn/very long despawn timer after being summoned

### ISSUE THREAD

**Issue by Tenoutoften** [Atlantiss/NetherwingBugtracker#4560]
**Description**: 
[[NPC]Veraku#18544](https://db.excalibur.ws/?npc=18544) summoned by [[Spell]Challenge Veraku#34895](https://db.excalibur.ws/?spell=34895) from [[Item]Challenge of the Blue Flight#10274](https://db.excalibur.ws/?item=29101) has a too long despawn timer, resulting in build up if people summon and leave. Objective of [[Quest]Securing the Celestial Ridge#10274](https://db.excalibur.ws/?quest=10274)

**Expected behaviour**: 
Expected to have a reasonable despawn timer, 30-60sec

**Server Revision**: 
2691

**Comment by Evolvee** [comment]
rev 2878
