### ISSUE TITLE
Curse of Recklessness

### ISSUE THREAD

**Issue by genetheparmesan** [Atlantiss/NetherwingBugtracker#4562]
[//]: # ([Spell][Warlock] [Curse of Recklessness)

**Description**: 
curse of recklessness not working properly
**Current behaviour**:
mobs with curse of recklessness on will still run away with fear when they get low on health
**Expected behaviour**: 
mobs will not run away and will instead keep fighting
**Server Revision**:

**Comment by genetheparmesan** [comment]
https://youtu.be/7NVPnMJJYK4

When a mob already running in fear is effected by curse of recklessness they should stop running. This is not currently the case. Mobs running in fear will keep running even if CoR is on them. If a mob has CoR on before they start running  then the ability will work properly. In regards to proper fear effects the spell is working properly in that a feared mob will stop running when inflicted by CoR and a mob with CoR will not run when fear is cast on them.

**Comment by Wolffenstein** [comment]
Fixed in rev 2779.
