### ISSUE TITLE
[NPC][Badlands] Martek the exile stuck in RP

### ISSUE THREAD

**Issue by DarthNekr0s** [Atlantiss/NetherwingBugtracker#4563]
**Description**:  martek the exiled is stuck in RP. checked bugtracker already for this issue and found it had been fixed  #4112  but now he seems to still be doing it. can't interact with him or accept quests etc.

**Current behaviour**: 
![image](https://user-images.githubusercontent.com/16113944/51731767-b80dbe80-20c7-11e9-9013-c4011dc0f8a5.png)

**Expected behaviour**: 

**Server Revision**:  2691

**Comment by Evolvee** [comment]
https://github.com/Atlantiss/NetherwingBugtracker/issues/4385 maybe related

**Comment by craigsurbrook** [comment]
12:39 PST time on 2/23/2019
This is still happening, just counted about 100 of these in a row in rapid succession and cannot turn in the quest "Martek the Exiled" (horde side).
This is incredibly annoying.

**Comment by Evolvee** [comment]
ok i will rewrite it

**Comment by Evolvee** [comment]
rev 2830
