### ISSUE TITLE
[Exodar][NPC]Kudrii#16742, enchanting trainer doesn't sell any recipes

### ISSUE THREAD

**Issue by Tenoutoften** [Atlantiss/NetherwingBugtracker#4564]
**Description/Current behaviour**: 
[[NPC]Kudrii#16742](https://web.archive.org/web/20071113235226/http://thottbot.com/c16742) currently doesn't offer to sell any recipes. Figured I'd add this since it seems that [[Item]Formula: Large Prismatic Shard#22565](https://db.excalibur.ws/?item=22565) is out of stock all the time! 
![](https://i.gyazo.com/37cdfce31bbc9e3ca3ddf1fe5fbf7b9c.png)

Additionally she is suppose to patrol with Egomis taking a break. Currently has a very awkward stock position directly infront of Egomis, but not facing Egomis.
https://www.wowhead.com/npc=16742/kudrii#screenshots - here is a screenshot of her on the way back to the enchanting house.
https://wow.freierbund.de/map_and_guide/244805/Kudrii-Bilder.html - picture of Kudrii by the table nearby

**Expected behaviour**: 
[[NPC]Kudrii#16742](https://web.archive.org/web/20071113235226/http://thottbot.com/c16742) should be selling various recipes according to thottbot archive:

![](https://i.gyazo.com/d30eadedd0babd070dc7d9d31c433683.png)
https://web.archive.org/web/20070314184916/http://www.thottbot.com:80/i22565
![](https://i.gyazo.com/62c482f9214d3fcce927d405d318ca44.png)

**Server Revision**: 
2691

**Comment by Evolvee** [comment]
rev 2878
