### ISSUE TITLE
[Boomkin][Treants]

### ISSUE THREAD

**Issue by FIXTHISFASTERRR** [Atlantiss/NetherwingBugtracker#4567]
[//]: # (Enclose links to things related to the bug using http://wowhead.com or any other TBC database.)
[//]: # (You can use screenshot ingame to visual the issue.)
[//]: # (Write your tickets according to the format:)
[//]: # ([Quest][Azuremyst Isle] Red Snapper - Very Tasty!)
[//]: # ([NPC] Magistrix Erona)
[//]: # ([Spell][Mage] Fireball)
[//]: # ([Npc][Drop] Ghostclaw Lynx)
[//]: # ([Web] Armory doesnt work)
[//]: # (To find server revision type `.server info` command in the game chat.)

**Description**: 
They are level 70 instead of same level as the druid GG
**Current behaviour**:

**Expected behaviour**: 

**Server Revision**:

**Comment by Evolvee** [comment]
rev 2712
