### ISSUE TITLE
Certain NPC's not spawning

### ISSUE THREAD

**Issue by aresbrutus** [Atlantiss/NetherwingBugtracker#4569]
- [ ] [Shay Leafrunner](https://db.excalibur.ws/?npc=7774)
- [x] [Khan Dez'hepah](https://db.excalibur.ws/?npc=5600)
- [ ] [Baron Vardus](https://db.excalibur.ws/?npc=2306)
- [ ] [Dalinda Malem](https://db.excalibur.ws/?npc=5644)
- [ ] [Kalaran Windblade](https://db.excalibur.ws/?npc=8479)
- [ ] [Witch Doctor Mai'jin](https://db.excalibur.ws/?npc=17235)
- [ ] [Tcha'kaz](https://db.excalibur.ws/?npc=17236)
- [ ] [Skywing](https://db.excalibur.ws/?npc=22424)
- [ ] [Tapoke "Slim" Jahn](https://db.excalibur.ws/?npc=4962)

They only spawn once after a server restart and not anymore, or bug out and stop spawning.

**Comment by aresbrutus** [comment]
https://github.com/Atlantiss/NetherwingBugtracker/issues/4358

**Comment by aresbrutus** [comment]
https://github.com/Atlantiss/NetherwingBugtracker/issues/4133

**Comment by aresbrutus** [comment]
https://github.com/Atlantiss/NetherwingBugtracker/issues/4108

**Comment by aresbrutus** [comment]
https://github.com/Atlantiss/NetherwingBugtracker/issues/4140

**Comment by narayagh** [comment]
Possibly add "Stinky" Ignatz to the list.

**Comment by Evolvee** [comment]
https://github.com/Atlantiss/NetherwingBugtracker/issues/4111

**Comment by Evolvee** [comment]
+ Mogor

**Comment by maxturtlesc2** [comment]
Shay Leafrunner standing in the middle of the shimmering flats for some reason.
![ixvw8qg8wl](https://user-images.githubusercontent.com/43255334/52969341-508a1c80-33b0-11e9-82e6-fa8d9935e1d3.jpg)

**Comment by Baelek** [comment]
Requesting for this to be opened again, @Evolvee 

Shay is still not spawning.

**Comment by Evolvee** [comment]
it is some other issue but ok -.-

**Comment by Evolvee** [comment]
https://github.com/Atlantiss/NetherwingBugtracker/issues/5106

**Comment by phantom1004** [comment]
Might need to add Ringo to this list, Creature ID 9999

**Comment by danbopes** [comment]
Still having issues with Khan. After server restart he's always up, but then bugs out and does not spawn again. 40 minutes+ camping his 2 spawn locations in a group, and still no spawn.

**Comment by thebluefish** [comment]
I'm also seeing issues with Khan. Spent two hours between me and a bud, killing everything around him (trying to force a spawn), and nada.

**Comment by Godmatik** [comment]
Torek (NPC questgiver) in Ashenvale also was not spawning, waited 30 minutes for him.

**Comment by thestranger064** [comment]
hello! as of today 05/02 -2019 its still not working properly.

steps: killed battle lords at every location, and nothing
killed windchasers and maulers , just incase
camped both big tents

and nothing. sadly this one of those quest that everyone knows about, but nothing is done about it.
