### ISSUE TITLE
[NPC] Antlered Courser - Rushing Charge

### ISSUE THREAD

**Issue by manslaughter** [Atlantiss/NetherwingBugtracker#457]
[//]: # (Enclose links to things related to the bug using http://wowhead.com or any other TBC database.)
[//]: # (You can use screenshot ingame to visual the issue.)
[//]: # (Write your tickets according to the format:)
[//]: # ([Quest][Azuremyst Isle] Red Snapper - Very Tasty!)
[//]: # ([NPC] Magistrix Erona)
[//]: # ([Spell][Mage] Fireball)
[//]: # ([Npc][Drop] Ghostclaw Lynx)
[//]: # ([Web] Armory doesnt work)

**Description**: These are beasts along the main trail up Stonetalon Mountains.

**Current behaviour**: They gain a buff, Rushing Charge, which increases their next attack's damage.  But they gain it every time it is off cooldown(?), even when their target is in melee range.

**Expected behaviour**: Only gain the buff if their target is not in melee range.

**Server Revision**: 2045

**Comment by Easyfraggy** [comment]
This goes for all types of Rushing Charge abilities.

**Comment by Easyfraggy** [comment]
https://github.com/Atlantiss/NetherwingBugtracker/issues/863

**Comment by Evolvee** [comment]
I had a video where westfall boar used it in combat in melee range as well... so would need some proof/evidence for this

im just gonna delay the usage of this one for now
rev xdd
