### ISSUE TITLE
Recipe: Undermine Clam Chowder missing from Vendor

### ISSUE THREAD

**Issue by frenkzenith** [Atlantiss/NetherwingBugtracker#4571]
Jabbey <General Goods> in Tanaris should sell Recipe: Undermine Clam Chowder

Current behaviour:
not selling it

Expected behaviour: 
Should sell it, because all web database say so and the addon '' Ackis Recipe List '' from back in the day say so too.

https://classicdb.ch/?item=16767#sold-by
https://tbc-twinhead.twinstar.cz/?item=16767

![wowscrnshot_012519_083306](https://user-images.githubusercontent.com/46387122/51749201-bd91e700-207c-11e9-95e7-4d065c50dc1b.jpg)

**Comment by Shanghi** [comment]
It's there but just sold out. Sold out items aren't supposed to be visible at all, but private servers usually don't fix that so that can cause some confusion now.
