### ISSUE TITLE
[NPC] [Exodar] Draenei Commoner - out of season

### ISSUE THREAD

**Issue by H2714** [Atlantiss/NetherwingBugtracker#4574]
**Description**: 
I found 6 Brewfest-teamed [Draenei Commoners ](https://www.wowhead.com/npc=19171/draenei-commoner)  in Exodar.

**Current behaviour**:
![wowscrnshot_012519_153955](https://user-images.githubusercontent.com/46264740/51752574-1df24a00-20b8-11e9-90a2-04a3b4b7882f.jpg)

**Expected behaviour**: 
To not be so festive outside of holiday.

**Server Revision**: 
2697

**Comment by Evolvee** [comment]
rev 2713
