### ISSUE TITLE
Last tick of bandage sometimes heals for 0

### ISSUE THREAD

**Issue by ghost** [Atlantiss/NetherwingBugtracker#4577]
[//]: # (Enclose links to things related to the bug using http://wowhead.com or any other TBC database.)
[//]: # (You can use screenshot ingame to visual the issue.)
[//]: # (Write your tickets according to the format:)
[//]: # ([Quest][Azuremyst Isle] Red Snapper - Very Tasty!)
[//]: # ([NPC] Magistrix Erona)
[//]: # ([Spell][Mage] Fireball)
[//]: # ([Npc][Drop] Ghostclaw Lynx)
[//]: # ([Web] Armory doesnt work)
[//]: # (To find server revision type `.server info` command in the game chat.)

**Description**: Last tick of first aid sometimes heals for 0

**Current behaviour**: Last tick of first aid sometimes heals for 0. The heal goes off but last tick reads +0 in combat log.

**Expected behaviour**: All ticks should work,

**Server Revision**: 2697

**Comment by Godmatik** [comment]
Fixed a long time ago.
