### ISSUE TITLE
[Quest] Familiar Fungi

### ISSUE THREAD

**Issue by rychersky** [Atlantiss/NetherwingBugtracker#4578]
[//]: # (Enclose links to things related to the bug using http://wowhead.com or any other TBC database.)
[//]: # (You can use screenshot ingame to visual the issue.)
[//]: # (Write your tickets according to the format:)
[//]: # ([Quest][Azuremyst Isle] Red Snapper - Very Tasty!)
[//]: # ([NPC] Magistrix Erona)
[//]: # ([Spell][Mage] Fireball)
[//]: # ([Npc][Drop] Ghostclaw Lynx)
[//]: # ([Web] Armory doesnt work)
[//]: # (To find server revision type `.server info` command in the game chat.)

**Description**: Drop rate on the Mushroom Samples is unusually low. I and another player have together killed about 80 Ango'rosh ogres and have only had 2 drop. 

For reference, the drop rate is around 50% on retail servers: https://www.wowhead.com/item=24238/mushroom-sample#dropped-by

**Server Revision**: 2697

**Comment by Drayo** [comment]
Can confirm, takes an absurd amount of kills to complete.

**Comment by Evolvee** [comment]
you must be rly unlucky or be killing wrong types of ogres

its 30-60% based on ogre type currently
