### ISSUE TITLE
[Item] Jump-a-tron 4000 Key

### ISSUE THREAD

**Issue by AWIDIUS** [Atlantiss/NetherwingBugtracker#4579]
I wanted to complete quest, but it didn't allow me to do so with full inventory. The reward is a key, that should come in Keyring. But until I freed 1 inventory space I wasn't able to complete that quest. https://imgur.com/a/zePz5ov . After I deleted Primordial essence (second column from the right, bottom row) it allowed me to complete it even tho Key gone into keyring https://imgur.com/a/WGKGIIV . Keys from quests, should go to keyring slot as normal and quests rewarding keys should be completed regardless on bag space.

**Comment by Manaci** [comment]
Fixed
