### ISSUE TITLE
[NPC][Movement] Wretched Hooligan(s) & Wretched Thug(s) / Sunsail Anchorage Map Movement

### ISSUE THREAD

**Issue by EsWoW** [Atlantiss/NetherwingBugtracker#458]
**Description**: Presently, the right side of the ramp/platform at the bottom of the rotunda allows NPCs to find a path where there shouldn't be one. The left side, as demonstrated, does not have the same issue.

**Current behaviour**: NPCs are moving up and down the platform level in ways they shouldn't. See https://www.youtube.com/watch?v=rpQnci2WV4Y for a demonstration.

**Expected behaviour**: NPCs should run down the side of the ramp as it presently does, as demonstrated, on the opposite side.

**Server Revision**: 2045

```
AtlantissCoreTBC - rev: 2045 
Online players: 73 (max: 75) 
Active connections: 77 (max: 81) Queued connections: 0 (max: 0) 
Server uptime: 1 Hour(s) 15 Minute(s) 27 Second(s). 
Current time: 2018-09-25 03:13:20 
Content Patch: 203. 
You are outdoors 
Map: 530 (Outland) Zone: 3430 (Eversong Woods) Area: 3461 (Sunsail Anchorage) 
X: 8726.895508, -6117.585449, 20.147739 Orientation: 3.654788 
grid[48,20]cell[5,8] InstanceID: 0 
 ZoneX: 33.098183 ZoneY: 70.500633 
GroundZ: 49.132812 FloorZ: 20.148155 Have height data (Map: 1 VMap: 1 Col: 1) 
------------------------ 
Entry: 16162, SpawnId - (Entry: 16162, Id: 8), GUIDLow: 45754 
```

**Comment by EsWoW** [comment]
Just for clarification, it seems the title for Wretched Thug doesn't match the NPC ID I linked for Wretched Hooligan, but **all** NPCs in this area are affected by this, so it shouldn't matter too much.

**Comment by Wolffenstein** [comment]
Any retail proof? Mobs generally can climb inclines like that.

**Comment by EsWoW** [comment]
My apologies. I just confirmed that this is normal behavior on BfA retail. For full transparency, here is a clip from retail toady. https://www.youtube.com/watch?v=eYmcUmeXwLc

Apologies once again. Seems this may be closed.
