### ISSUE TITLE
+10 haste to gloves

### ISSUE THREAD

**Issue by Aedituus** [Atlantiss/NetherwingBugtracker#4580]
[//]: # (Enclose links to things related to the bug using http://wowhead.com or any other TBC database.)
[//]: # (You can use screenshot ingame to visual the issue.)
[//]: # (Write your tickets according to the format:)
[//]: # ([Quest][Azuremyst Isle] Red Snapper - Very Tasty!)
[//]: # ([NPC] Magistrix Erona)
[//]: # ([Spell][Mage] Fireball)
[//]: # ([Npc][Drop] Ghostclaw Lynx)
[//]: # ([Web] Armory doesnt work)
[//]: # (To find server revision type `.server info` command in the game chat.)

**Description**: +10 haste to glove enchant

**Current behaviour**:Does not affect player or spells

**Expected behaviour**: adds 10 haste rating to character's spells

**Server Revision**:

**Comment by Balanarr** [comment]
I see that you mention spells. If the enchant you mention is Minor Haste then that one did NOT affect spells in TBC. For casters it only affects wand speed. It's only for melee,bow/gun/thrown

**Comment by Evolvee** [comment]
need more description/link to the item/ if u still believe its bugged
