### ISSUE TITLE
Wand spell damage reduced by physical damage reduction effect

### ISSUE THREAD

**Issue by Paybac123** [Atlantiss/NetherwingBugtracker#4582]
[//]: # (Enclose links to things related to the bug using http://wowhead.com or any other TBC database.)
[//]: # (You can use screenshot ingame to visual the issue.)
[//]: # (Write your tickets according to the format:)
[//]: # ([Quest][Azuremyst Isle] Red Snapper - Very Tasty!)
[//]: # ([NPC] Magistrix Erona)
[//]: # ([Spell][Mage] Fireball)
[//]: # ([Npc][Drop] Ghostclaw Lynx)
[//]: # ([Web] Armory doesnt work)
[//]: # (To find server revision type `.server info` command in the game chat.)

**Description**: 
SO i found it really weird that poison which reduces physical damage dealt reduces damage of wand damage, I think its bug and it should be repaired, there asre screenshots
https://imgur.com/a/OLIA0Z5
**Current behaviour**:
Physical Damage reduction effects reduce wand damage
**Expected behaviour**: 
It shouldnt lower wand damage, if it is a case you should check also if spell power increased wand damage as i think that wand damage is coded as physical damage and it is not buffed with spell power.
**Server Revision**:

**Comment by Tereneckla** [comment]
Put in bigger topic
