### ISSUE TITLE
Mind Control bug

### ISSUE THREAD

**Issue by Paybac123** [Atlantiss/NetherwingBugtracker#4584]
[//]: # (Enclose links to things related to the bug using http://wowhead.com or any other TBC database.)
[//]: # (You can use screenshot ingame to visual the issue.)
[//]: # (Write your tickets according to the format:)
[//]: # ([Quest][Azuremyst Isle] Red Snapper - Very Tasty!)
[//]: # ([NPC] Magistrix Erona)
[//]: # ([Spell][Mage] Fireball)
[//]: # ([Npc][Drop] Ghostclaw Lynx)
[//]: # ([Web] Armory doesnt work)
[//]: # (To find server revision type `.server info` command in the game chat.)

**Description**: 
Mind control spell is broken with casting any spell from mind controled target
**Current behaviour**:
MC breats faster cast
**Expected behaviour**: 
It should be casted and Mind Control shouldnt break
**Server Revision**:

**Comment by devo6969** [comment]
https://wow.gamepedia.com/Mind_Control#:~:text=Mind%20Control%20(or%20MC)%2C,use%20it%20against%20other%20enemies.
 Patch 1.1.0 (2004-11-07):
"Increased the chance of breaking early."
"When MCing targets to their deaths, you can break the channel once they are over the edge, although be careful not to break it too soon"

**Comment by Godmatik** [comment]
Duplicate
https://github.com/Atlantiss/NetherwingBugtracker/issues/5089
