### ISSUE TITLE
Devotion aura Paladin

### ISSUE THREAD

**Issue by TotalBarracuda** [Atlantiss/NetherwingBugtracker#4585]
[//]: # (Enclose links to things related to the bug using http://wowhead.com or any other TBC database.)
[//]: # (You can use screenshot ingame to visual the issue.)
[//]: # (Write your tickets according to the format:)
[//]: # ([Quest][Azuremyst Isle] Red Snapper - Very Tasty!)
[//]: # ([NPC] Magistrix Erona)
[//]: # ([Spell][Mage] Fireball)
[//]: # ([Npc][Drop] Ghostclaw Lynx)
[//]: # ([Web] Armory doesnt work)
[//]: # (To find server revision type `.server info` command in the game chat.)

**Description**: 

**Current behaviour**:

**Expected behaviour**: 

**Server Revision**:

**Comment by TotalBarracuda** [comment]
Improved Devotion Aura talent doesn't work at all for me.

**Comment by Tenoutoften** [comment]
Any additional details? Screenshot of aura off and armor from character panel then improved aura on and recheck character panel?

**Comment by wtRCH** [comment]
Provide more info about bug, please @TotalBarracuda

**Comment by Tenoutoften** [comment]
Works as intended
![](https://i.gyazo.com/87b8ef9e360e6b11a219c25131873f63.png)
![](https://i.gyazo.com/5b9e95fe7eaa8fae8a3e8b9f1c9ead37.png)
+1205 armor

**Comment by TotalBarracuda** [comment]
The Talent that's supposed to make Devotion aura stronger doesnt work.

**Comment by Tereneckla** [comment]
Devotion Aura and the talent work
