### ISSUE TITLE
[Quest][Desolace] Stealing Supplies

### ISSUE THREAD

**Issue by maxturtlesc2** [Atlantiss/NetherwingBugtracker#4586]
[//]: # (Enclose links to things related to the bug using http://wowhead.com or any other TBC database.)
[//]: # (You can use screenshot ingame to visual the issue.)
[//]: # (Write your tickets according to the format:)
[//]: # ([Quest][Azuremyst Isle] Red Snapper - Very Tasty!)
[//]: # ([NPC] Magistrix Erona)
[//]: # ([Spell][Mage] Fireball)
[//]: # ([Npc][Drop] Ghostclaw Lynx)
[//]: # ([Web] Armory doesnt work)
[//]: # (To find server revision type `.server info` command in the game chat.)

**Description**: 
https://www.wowhead.com/quest=1370/stealing-supplies
**Current behaviour**:
A lot of missing spawn points for Crudely Dried Meat.
**Expected behaviour**: 
Correct amount of spawn points.
**Server Revision**:

**Comment by Evolvee** [comment]
rev 2713
