### ISSUE TITLE
[Top Priority] [Rogue] [Spell] Pick Pocket Resist in PvP

### ISSUE THREAD

**Issue by sadfx** [Atlantiss/NetherwingBugtracker#4589]
**Current behaviour**: Use of Pick Pocket opener macros in PvP can generate resists which breaks stealth

**Expected behaviour**: Pick Pocket is unusable in PvP and should therefore never go off vs players..

**Server Revision**: 2697

**Comment by Wolffenstein** [comment]
Fixed in rev 2704.
