### ISSUE TITLE
DB/Creature: Goldshire - Innkeeper Farley in Lion's Pride Inn missing RP/text

### ISSUE THREAD

**Issue by Teppic1** [Atlantiss/NetherwingBugtracker#459]
**Description**: 

Innkeeper Farley (295) should welcome the player and speak a line of text at intervals.

**Current behaviour**:

He does nothing.

**Expected behaviour**: 

This issue was fixed in TC and all the necessary details can be found here:

https://github.com/TrinityCore/TrinityCore/commit/87948f41fa319f5271038fddffac78e335d69a94

**Server Revision**: 

2045

**Comment by Teppic1** [comment]
This worked the next time I went in. I'll check again after a while.

**Comment by tcberk12** [comment]
I think this is working. 

I would note that after idling in the inn for awhile, moving again would trigger the same RP. Not sure how you could ever filter idle players out from triggering the RP, though.

**Comment by aresbrutus** [comment]
This works. If you think it is broken, PM me on discord so I can re-open.
