### ISSUE TITLE
[Quest] Malin's Request QID 697 Broken

### ISSUE THREAD

**Issue by OMEGALULW** [Atlantiss/NetherwingBugtracker#4590]
**Current behaviour**: Players can't turn in Malin's Request to Skuerto 

**Expected behaviour**: Quest should lead to Worth Its Weight in Gold but that quest wasn't available either after abandoning Malin's Request.

**Server Revision**: 2697

related to https://github.com/Atlantiss/NetherwingBugtracker/issues/757 ??

Update: Maybe I already grabbed Worth Its Weight in Gold since it required no pre-quest and that's what actually prevented me from turning in Malin's Request.. Either way, it's broken since it should be a pre-quest xd

**Comment by randomuser69** [comment]
This bug is still in game: 

![WoWScrnShot_061219_211128](https://user-images.githubusercontent.com/51173000/59815449-99ae9680-92e6-11e9-8838-f2b3a77ad180.jpg)

**Comment by Tereneckla** [comment]
Fixed
