### ISSUE TITLE
Magtheridon 

### ISSUE THREAD

**Issue by Dpthx** [Atlantiss/NetherwingBugtracker#4591]
[//]: # (Enclose links to things related to the bug using http://wowhead.com or any other TBC database.)
[//]: # (You can use screenshot ingame to visual the issue.)
[//]: # (Write your tickets according to the format:)
[//]: # ([Quest][Azuremyst Isle] Red Snapper - Very Tasty!)
[//]: # ([NPC] Magistrix Erona)
[//]: # ([Spell][Mage] Fireball)
[//]: # ([Npc][Drop] Ghostclaw Lynx)
[//]: # ([Web] Armory doesnt work)
[//]: # (To find server revision type `.server info` command in the game chat.)

**Description**: Magtheridon should be rooted whilst he's performing Earthquake. 

**Current behaviour**: He's meeleing people around. 

**Expected behaviour**: Should be rooted and not attacking anyone, just performing his Earthquake animation, which is just him jumping on the spot.

https://www.youtube.com/watch?v=A5Ma8G8ZScc

**Server Revision**:

**Comment by Wolffenstein** [comment]
Fixed in rev 2705.
