### ISSUE TITLE
[Core][Buffs] Buffs disappearing when party member leaves party

### ISSUE THREAD

**Issue by killablink** [Atlantiss/NetherwingBugtracker#4592]
**Description**: If a party member buffs you and he leaves the party, the buff disappears.

**Current behaviour**: If a party member buffs you and he leaves the party, the buff disappears.

**Expected behaviour**: The buff should stay on.

**Server Revision**: 2697

**Comment by Wolffenstein** [comment]
Any buff or which ones specifically?

**Comment by killablink** [comment]
Pretty sure it's every buff, Arma left raid group during Gruul's lair and everyone lost their wisdom blessing. When I was doing dungeons when we reformed the groups they would all lose Arcane Brilliance, etc.

**Comment by Wolffenstein** [comment]
It probably affects party buffs only then

**Comment by Wolffenstein** [comment]
"Greater Blessing of Kings only applies while you are in the group with the paladin who cast it. If you leave the party or raid, this blessing will be removed."

Seems to be working correctly as those buffs are classified as group buffs.
