### ISSUE TITLE
[Mail] Enchanted items lose enchant

### ISSUE THREAD

**Issue by DoctorRaymos** [Atlantiss/NetherwingBugtracker#4593]
Player Softclouds#6211 is reporting that when mailing enchanted items using two separate accounts, upon receiving them they have dropped their enchantments. This took place over 2-3 days. Character that sent mail- Softclouds
Character that received mail- Lightshy

**Comment by DoctorRaymos** [comment]
Comment from player : I'd like to add that some of the items I've picked up from the mailbox today has had their enchants applied, just not visible while the item was in the mailbox. I am quite certain those items I picked up before were items that had enchants on them that indeed disappeared - for I was determined to enchant every green/blue piece with good, yet affordable enchants. Can't guarantee no human error, however. Hopefully the remaining items will prove enchanted. Looting them over the course of leveling up to appropriate levels.

**Comment by Tereneckla** [comment]
visual bug in mailbox
