### ISSUE TITLE
[NPC] Talon King Ikiss

### ISSUE THREAD

**Issue by Aquaorangez** [Atlantiss/NetherwingBugtracker#4595]
[//]: # (Enclose links to things related to the bug using http://wowhead.com or any other TBC database.)
[//]: # (You can use screenshot ingame to visual the issue.)
[//]: # (Write your tickets according to the format:)
[//]: # ([Quest][Azuremyst Isle] Red Snapper - Very Tasty!)
[//]: # ([NPC] Magistrix Erona)
[//]: # ([Spell][Mage] Fireball)
[//]: # ([Npc][Drop] Ghostclaw Lynx)
[//]: # ([Web] Armory doesnt work)
[//]: # (To find server revision type `.server info` command in the game chat.)

**Description**:   Arcane Volley has too long a range (Greater than 40 yards)

**Expected behaviour**:  According to wowhead comments from 2.0.3 (the very first comment on wowhead for Talon King Ikiss) states that arcane volley has 40 yards range and that it can be avoided by hunters at max range. I couldn't avoid it by being farther than 40 yards.

**Server Revision**:

**Comment by wtRCH** [comment]
@Wolffenstein

**Comment by Wolffenstein** [comment]
I dont trust these comments, not enough proof
