### ISSUE TITLE
Hunter's Mark does not correctly grant vision of a stealthed target

### ISSUE THREAD

**Issue by Tehterokkar** [Atlantiss/NetherwingBugtracker#4596]
[//]: # (Enclose links to things related to the bug using http://wowhead.com or any other TBC database.)
[//]: # (You can use screenshot ingame to visual the issue.)
[//]: # (Write your tickets according to the format:)
[//]: # ([Quest][Azuremyst Isle] Red Snapper - Very Tasty!)
[//]: # ([NPC] Magistrix Erona)
[//]: # ([Spell][Mage] Fireball)
[//]: # ([Npc][Drop] Ghostclaw Lynx)
[//]: # ([Web] Armory doesnt work)
[//]: # (To find server revision type `.server info` command in the game chat.)

**Description**: 
Hunter's Mark is supposed to grant the Hunter vision of a mob or player(Rogues/Ferals!) wherever they are if in Stealth. When a Rogue marked with HM goes into Stealth, HM is somehow dispelled, same thing with Vanish.

**Current behaviour**:
If Hunter's Mark is applied to a Rogue or Feral Druid before combat and they go into stealth, the hunter has no vision of the target and Hunter's Mark debuff is not present on target whenever they come out of stealth.

**Expected behaviour**: 
Hunter's Mark should not disappear upon target entering Stealth and should grant the Hunter vision of the target regardless of distance(up-to character rendering distance) and persist through combat, stealth, Shadowmeld and Vanish. Hunter's Mark should NOT disappear from target if target exits combat mode or enters stealth, only a real magic dispel or Cloak of Shadows should remove it.

See Vanilla video of Rogue using Vanish right after Hunter's Mark is applied: https://youtu.be/GsNaGLGMoIs?t=445

**Server Revision**:

**Comment by Zarant** [comment]
You linked a video from pre patch 1.6, i'm pretty sure in 2.4.3 vanish is supposed to remove hunter's mark. Stealth on the other hand, should not remove hunter's mark.

**Comment by Tehterokkar** [comment]
Vanish does not remove debuffs, it never has.

**Comment by Nitrana** [comment]
> 
> 
> Vanish does not remove debuffs, it never has.

That is not correct. It was changed in patch 1.12.0. "Vanish now removes effects that allow the caster to always remain aware of their target (currently Hunter's Mark and Mind Vision)". Source: https://wowwiki.fandom.com/wiki/Patch_1.12.0

When a Rogue or Druid enters Stealth/Prowl the Hunter's Mark debuff should be retained is correct. But also keep in mind that aside from Vanish, a Rogue can use Cloak of Shadows to remove the debuff.

**Comment by Manaci** [comment]
Fixed
