### ISSUE TITLE
Loot issues (Scarlet Monestary)

### ISSUE THREAD

**Issue by MonsterDooty** [Atlantiss/NetherwingBugtracker#4598]
**Description**: 
Upon finishing final boss during Cathedral script (where priestess comes out to res boss) Once finished.  The loot that was dropped by the priestess was only available for 3/5 people to roll it.
**Current behaviour**:
Loot rolls skip certain players leading to unfair chances at specific BoP items.  A tank won cloth head piece as the mage/priest could not roll against him
**Expected behaviour**: 
Upon killing a mob/boss that offers loot of value, a roll sequence commence and there is a fair dice roll amongst the players to see who wins said item.
**Server Revision**: 
Current patch: 203

P.S  That whole SM run ( graveyard/lib/cath)  I was only able to loot roughly 7 mobs total across all instances.  The loot priority was not round robin rather first come first serve.  All I got was the shared gold per mob.

**Comment by MonsterDooty** [comment]
I'd like to add some additional info as it may pertain to the issue.  I had a internet crash lib that caused the phantom issue where I "existed" within the party, but I was in my own instance.  They had to kick me and reinvite me.  Afterwards, the whole loot priority and round robin function was completely broken.

**Comment by Godmatik** [comment]
Unable to reproduce and never heard of this issue from anyone this past year on Netherwing.

Possibly fixed at some point.
