### ISSUE TITLE
[Quest][Netherstorm] Dimensius the All-Devouring (Dimensius doesn't spawn)

### ISSUE THREAD

**Issue by Mikik3jr** [Atlantiss/NetherwingBugtracker#4599]
[//]: # (Enclose links to things related to the bug using http://wowhead.com or any other TBC database.)
[//]: # (You can use screenshot ingame to visual the issue.)
[//]: # (Write your tickets according to the format:)
[//]: # ([Quest][Azuremyst Isle] Red Snapper - Very Tasty!)
[//]: # ([NPC] Magistrix Erona)
[//]: # ([Spell][Mage] Fireball)
[//]: # ([Npc][Drop] Ghostclaw Lynx)
[//]: # ([Web] Armory doesnt work)
[//]: # (To find server revision type `.server info` command in the game chat.)

**Description**: 
In this quest first we talk to the captain and get a team of consortium guys to bead down a big big voidwalker.

**Current behaviour**:
Dimensius does not spawn, and the helper NPCs run middle of the room and they just disappear.

**Expected behaviour**: 
After going inside the building Dimensius should be there and should be attackable. In this state the quest is impossible to do and it gives Preraid BiS items for multiple classes.

**Server Revision**: 
2706

**Comment by Drayo** [comment]
Had the same issue just now, some players have the quest completed though, they said it only works once after a crash. It would be very nice if you could fix this since the gear from it is part of the pre-BIS Gear.

**Comment by Tenoutoften** [comment]
https://github.com/Atlantiss/NetherwingBugtracker/issues/4207
https://github.com/Atlantiss/NetherwingBugtracker/issues/2511

**Comment by wtRCH** [comment]
@aresbrutus

**Comment by Mikik3jr** [comment]
I took the quest when the army was there, but I still got the message that the captain is away fighting. Maybe this info helps to find the problem:

![image](https://user-images.githubusercontent.com/43505031/51792757-57a97a80-21b6-11e9-9873-4c278b87b8f6.png)

**Comment by liek0r** [comment]
Still broken.

**Comment by ttghnw** [comment]
B R O K EN

**Comment by Dotamasta** [comment]
Still broken, doesnt spawn

**Comment by squexence** [comment]
Yesterday the NPC "Captain Saeed" didnt spawn at all and his army was there. Today the spot is empty and no army or npc in sight.

**Comment by TSRSoka** [comment]
Still bugged, Captain won't spawn.

**Comment by Jalapan** [comment]
@Wolffenstein this is an important quest with BiS quest rewards for pre-raiding

**Comment by Azhtyhx** [comment]
Actually, Captain Saeed respawns, only in the wrong location. I just ran by him in Zangarmarsh, surrounded by his army friends.
![wowscrnshot_030719_093537](https://user-images.githubusercontent.com/29478064/53954525-be378780-40d6-11e9-94c3-45fbc986d1d4.jpg)

**Comment by Drayo** [comment]
This is gold.

**Comment by ttghnw** [comment]
omegalul

**Comment by Suzaru** [comment]
Didn't found the captain, not in netherstorm, neither in Zangarmarsh :(

**Comment by darknessangelo** [comment]
Still bugged. Cant talk to Captain to start the event.

**Comment by zhuk90** [comment]
still broken

**Comment by Mangotronic** [comment]
Hello! Quest still broken.

Saeed is spawned but when talked to him, only responds with "Greetings, $name" and nothing happens. Dimensius doesn't spawn either. 

Really want that pre-BIS :(

**Comment by Wolffenstein** [comment]
Fixed in rev 3198.
