### ISSUE TITLE
Death bug 2.0

### ISSUE THREAD

**Issue by AlteredAli** [Atlantiss/NetherwingBugtracker#46]
[//]: # (Enclose links to things related to the bug using http://wowhead.com or any other TBC database.)
[//]: # (You can use screenshot ingame to visual the issue.)
[//]: # (Write your tickets according to the format:)
[//]: # ([Quest][Azuremyst Isle] Red Snapper - Very Tasty!)
[//]: # ([NPC] Magistrix Erona)
[//]: # ([Spell][Mage] Fireball)
[//]: # ([Npc][Drop] Ghostclaw Lynx)
[//]: # ([Web] Armory doesnt work)

**Description**: 
Died to "Cursed Mages" arcane bolt, spawned at spirithealer as usual then teleported to my corpse as ghost.
**Current behaviour**:

**Expected behaviour**: 

**Server Revision**:

**Comment by AlteredAli** [comment]
Update: tried dying to the same mob the same way another 4 times, all unsuccessful

**Comment by Easyfraggy** [comment]
Could you try to recreate after the res bug update?

**Comment by wtRCH** [comment]
Fixed
