### ISSUE TITLE
Factionqueue after DC/alt+F4

### ISSUE THREAD

**Issue by idsss** [Atlantiss/NetherwingBugtracker#4601]
**Description**: supposedly, theres a 5 minute grace period for the queue after a crash. Well, seems like currently u can get placed in queue after u either disconnect or close your client

**Current behaviour**: queue after dc or closing client

**Expected behaviour**: shouldnt get queued instantly after a crash or w/e

**Server Revision**: 2712

**Comment by The14me** [comment]
System get reworked.
Can be closed.

**Comment by Wolffenstein** [comment]
no it did not

**Comment by Godmatik** [comment]
I'm assuming faction queue is never happening again, so going to close this out
