### ISSUE TITLE
[Quest Daily] Fishing Old man Barlo

### ISSUE THREAD

**Issue by Dekirayne** [Atlantiss/NetherwingBugtracker#4602]
**Description**: 
The NPC Old man Barlo is missing that gives daily fishing quest
**Current behaviour**:
NPC missing
**Expected behaviour**: 
The NPC was added in patch 2.0.3

https://wow.gamepedia.com/Old_Man_Barlo
**Server Revision**:

**Comment by lynxzor** [comment]
Actually these were added in [2.4.0](https://www.wowhead.com/patchnotes=2.4.0)
