### ISSUE TITLE
No ammo consumed on missing

### ISSUE THREAD

**Issue by Ninehills42** [Atlantiss/NetherwingBugtracker#4603]
[//]: # (Enclose links to things related to the bug using http://wowhead.com or any other TBC database.)
[//]: # (You can use screenshot ingame to visual the issue.)
[//]: # (Write your tickets according to the format:)
[//]: # ([Quest][Azuremyst Isle] Red Snapper - Very Tasty!)
[//]: # ([NPC] Magistrix Erona)
[//]: # ([Spell][Mage] Fireball)
[//]: # ([Npc][Drop] Ghostclaw Lynx)
[//]: # ([Web] Armory doesnt work)
[//]: # (To find server revision type `.server info` command in the game chat.)

**Description**: 
No ammo is consumed on missing a shot
**Current behaviour**:
When a shot is missed (for example due to low level Bow/Guns skill, no ammo is consumed
**Expected behaviour**: 
Ammo should be consumed, even on miss
**Server Revision**: 
![miss](https://user-images.githubusercontent.com/47057882/51787712-776c7e80-2175-11e9-8994-367c00ec6d9a.png)

**Comment by Tehterokkar** [comment]
I've noticed that at least Serpent Sting does not consume ammo either. Might be some other abilities too but haven't paid attention.(Only noticed this because I had less than 50 arrows left and +10 mobs to kill, so I dotted them with SrS and started meleeing :P)
