### ISSUE TITLE
Triangulation Point One Marker is incorrect

### ISSUE THREAD

**Issue by fantom8** [Atlantiss/NetherwingBugtracker#4604]
**Description**: 
The quest completion marker for this quest is incorrectly placed.

**Current behaviour**:
https://i.imgur.com/WwdZfW7.jpg

You can see that the red arrows are stuck visible. The quest item does make you face the exact location of the red arrow in the screen shot. However when you stand on top of the arrow the quest does not complete. You must move to where the character in the linked image is standing before you get quest completion credit.

**Expected behaviour**: 
The red arrow/triangulation device facing point should line up with the location the player needs to stand at to complete the quest.

**Server Revision**:  2712

**Comment by Evolvee** [comment]
rev 2830
