### ISSUE TITLE
[Spell][Paladin] Sanctity and Resistance auras visual bug.

### ISSUE THREAD

**Issue by Hapsterchap** [Atlantiss/NetherwingBugtracker#4605]
**Description**: I currently get a visual bug when I toggle on Sanctity Aura. On the beta I received this also with Sanctity and the elemental resistance auras (sorry for taking so long to report it!)

**Current behaviour**: https://i.imgur.com/gylqwjt.jpg - sanctity aura
https://i.imgur.com/lp4egQv.jpg - this is frost res aura
(all four auras basically have the same bugged animation)

**Expected behaviour**: No big buggy extended square for the ability.

**Server Revision**: 2712

**Comment by Godmatik** [comment]
Unable to reproduce - if it did exist I am guessing it is clientside anyway
