### ISSUE TITLE
[Spell] Casting stuck after push back

### ISSUE THREAD

**Issue by imroroyo** [Atlantiss/NetherwingBugtracker#4607]
[//]: # (Enclose links to things related to the bug using http://wowhead.com or any other TBC database.)
[//]: # (You can use screenshot ingame to visual the issue.)
[//]: # (Write your tickets according to the format:)
[//]: # ([Quest][Azuremyst Isle] Red Snapper - Very Tasty!)
[//]: # ([NPC] Magistrix Erona)
[//]: # ([Spell][Mage] Fireball)
[//]: # ([Npc][Drop] Ghostclaw Lynx)
[//]: # ([Web] Armory doesnt work)
[//]: # (To find server revision type `.server info` command in the game chat.)

**Description**: 
I was attacked by two players, and I tried to cast Fear (warlock) on one of them. But they were both melee and pushed back my cast time immediately after I started casting. The cast somehow seemed to get stuck at 0, where I was trying to cast the spell, but the bar wouldn't increase. I had to interrupt the cast and start another.

**Current behaviour**:
Casting a spell and getting pushed back immediately might cause the cast to get stuck.

**Expected behaviour**: 
It obviously should be casting anyway while they are not hitting.

**Server Revision**: 
2712

**Comment by Zarant** [comment]
It seems fixed, can't reproduce this issue.
