### ISSUE TITLE
[NPC] Critters

### ISSUE THREAD

**Issue by mbzz88** [Atlantiss/NetherwingBugtracker#461]
**Description**: If you melee a critter, and it misses/is dodged etc. you cannot continue to auto attack the critter, only spells and auto shoot will work.

**Current behaviour**: Player will stand in attack animation doing nothing. Will stay in attack animation until relogging. https://youtu.be/fnxk2tm2-Sc

**Expected behaviour**:  Auto attack should continue to attack.

**Comment by Easyfraggy** [comment]
Possibly related to https://github.com/Atlantiss/NetherwingBugtracker/issues/189

**Comment by Evolvee** [comment]
https://github.com/Atlantiss/AtlantissTbcBTOLD/issues/110

**Comment by Tereneckla** [comment]
Fixed
