### ISSUE TITLE
[Quest] Cho'war the Pillager (Alliance)

### ISSUE THREAD

**Issue by 0vertime** [Atlantiss/NetherwingBugtracker#4610]
**Description**: 
During the end of quest after receiving the key from Cho'war, you must free Corki.

**Current behaviour**:
As you free him with party around you, they don't get credit as well and they have to wait for respawn.

**Expected behaviour**: 
Everyone should get credit nearby for freeing him. 

**Server Revision**: 
2712

Might be same issue with the earlier quests in this chain.
quest=9955 Cho'war the Pillager
quest=9924 Corki's Gone Missing Again!
quest=9923 HELP!

**Comment by Evolvee** [comment]
should be fixed already
