### ISSUE TITLE
[Quest] Forge Camp: Annihilated

### ISSUE THREAD

**Issue by 0vertime** [Atlantiss/NetherwingBugtracker#4611]
**Description**: 
You must use the key obtained from the demons to shoot the cannon.

**Current behaviour**:
Using the cannon does not give party wide credit. Everyone has to do it individually.

**Expected behaviour**: 
Using the cannon should give party wide credit.

**Server Revision**: 
2712

quest=10011

**Comment by Evolvee** [comment]
rev 2830
