### ISSUE TITLE
[Spell][Warrior] Whirlwind

### ISSUE THREAD

**Issue by battleleet2** [Atlantiss/NetherwingBugtracker#4612]
**Description**: 
Whirlwind parried by an enemy SHOULD refund 80% of rage spent

**Current behaviour**:
Whirlwind parried by an enemy doesn't refund 80% of rage spent

**Expected behaviour**: 
Refunding 80% of rage spent

**Server Revision**: 
2712

**Comment by Easyfraggy** [comment]
This report is likely invalid as whirlwind hits several mobs and can be used without any mobs in range - would need solid evidence for this.
