### ISSUE TITLE
[Rogue] [Spell] Preparation 

### ISSUE THREAD

**Issue by ValveHatesDotA** [Atlantiss/NetherwingBugtracker#4616]
**Current behaviour**: Prep didn't reset Sprint (https://i.imgur.com/OFk2ceN.png) This happened following me doing a quest that teleports me from Theramore to Stormwind, it has never behaved like this before

**Expected behaviour**:  Prep resets Sprint

**Server Revision**: 2712

#3581 related 

Edit:  It's not just once, without logging out I tried it again and it didn't reset the CD

**Comment by Easyfraggy** [comment]
Need more information. Is it just sprint or more spells?

**Comment by Godmatik** [comment]
Unable to reproduce - was probably fixed a long time ago.
