### ISSUE TITLE
[NPC][Loot] #18983 Blackfang Tarantula - Spider in Black Morass has no loot table. (Heroic only now)

### ISSUE THREAD

**Issue by herodope** [Atlantiss/NetherwingBugtracker#4618]
**Description**: All of the spiders in Black Morass(18983 - Blackfang Tarantula) have no loot table. They should have a chance to drop Netherweb Spider Silk(21881).

**Current behaviour**: They have no loot. I did two full solo clears of the spiders on Normal and one on Heroic and nothing ever dropped. Not to mention countless normal runs with group and never seen someone loot a spider.

**Expected behaviour**:  They should have a chance to drop Netherweb Spider Silk(21881). If you check Wowhead there are many old comments from 2.0->2.4 patch that discuss the droprate,

https://www.wowhead.com/item=21881/netherweb-spider-silk#comments

 but honestly I am unsure of the exact 'blizzlike' drop% rate. Currently the spiders drop nothing, so step1 would be adding the loot in the first place.

**Server Revision**:  2712

**Comment by Tenoutoften** [comment]
I have seen them drop stuff on this server many times, cleared all spiders in the dungeon a few times. It's very possible that their drop table is too low however, for example they "never" drop greens but comments mention that they drop 1 green every 15th kill. 

Thottbott archive gives these spiders a 50% chance for Netherweb Spider Silk

**Comment by Tenoutoften** [comment]
http://web.archive.org/web/20080525102229/http://thottbot.com:80/c18983
![](https://i.gyazo.com/332a9d86cb5b36b89d846904aabcf9e6.png)

**Comment by Tenoutoften** [comment]
Additionally other stuff needs to be increased... several primals have way to low drop chance I have reported this already and nothing is being done for the time being

https://github.com/Atlantiss/NetherwingBugtracker/issues/4120

**Comment by Manaci** [comment]
Still doesn't drop anything in Heroic, prob cause stock has no items for [it](https://db.excalibur.ws/?npc=22162)
