### ISSUE TITLE
[Spell][Shaman] Elemental Mastery sometimes trigger a casting delay

### ISSUE THREAD

**Issue by sandreid** [Atlantiss/NetherwingBugtracker#4619]
**Description**: 
Elemental Mastery (http://db.excalibur.ws/?spell=16166) is currently bugged. It Sometimes triggers a delay that is roughly 1-2 secs. It feels like the GCD, but the GCD doesn't activated. This happens about 50% of the time.

**Current behaviour**:
Elemental Mastery (http://db.excalibur.ws/?spell=16166) sometimes triggers a delay before you can cast your next spell when activating it, and other times, it doesn't do this.

**Expected behaviour**: 
Elemental Mastery shouldn't trigger any delay until after the buff is lost (As in, after the next spell has been cast).

**Server Revision**: 
2712

Video examples of it having the delay and not:
https://www.youtube.com/watch?v=dlb-f-L9bms

1st EM = Weird delay
2nd EM = Working as intended
3rd EM = Weird delay
4th EM = Working as intended

**Comment by sandreid** [comment]
It isn't the trinkets triggering this cooldown, by the way. I pop them before every time, when casting a Lightning Bolt, prior to the EM+CL combo.

**Comment by sandreid** [comment]
This is still a problem.

**Comment by Tereneckla** [comment]
rev 3236 does not happen anymore
