### ISSUE TITLE
[NPC] Lord Xiz missing weapon

### ISSUE THREAD

**Issue by Sothanwow** [Atlantiss/NetherwingBugtracker#462]
**Description**: 
Currently Lord Xiz is hitting with his fists when he should have the weapon shown in this [here](https://imgur.com/a/ZWwDCKX)
Link to mob and screenshots of it.
https://www.wowhead.com/npc=17701/lord-xiz#screenshots

**Current behaviour**:
Lord Xiz punches
**Expected behaviour**: 
Should hit with sword 
**Server Revision**: 
2045

**Comment by Wolffenstein** [comment]
Fixed in rev 2047.
