### ISSUE TITLE
Maiden of Virtue Trash engaged from adjacent room during fight. 

### ISSUE THREAD

**Issue by Hakaler** [Atlantiss/NetherwingBugtracker#4620]
**Description**: 
During a maiden of virtue pull two night maidens were aggroed from the room directly to the left of her room and down the hallway. 

As this has been a recurring issue in dungeons, such as shadow labyrinth perhaps this is a similar issue,  
**Current behaviour**:
Current Behavior is expected of the boss minus the adds. 
**Expected behaviour**: 
Pulling bosses should not aggro mobs that cannot be aggroed otherwise. 
**Server Revision**: 
2712

**Comment by The14me** [comment]
Rev.3460 cant reproduces it and since there is no other case like that, it looks like misspell the path.
Can be closed.
