### ISSUE TITLE
[Item][Spell] Jungle Remedy doesn't remove Serpent Sting

### ISSUE THREAD

**Issue by OMEGALULW** [Atlantiss/NetherwingBugtracker#4621]
**Current behaviour**:  Jungle Remedy doesn't remove Serpent Sting

**Expected behaviour**:  Jungle Remedy removes poisons

**Server Revision**: 2712

**Comment by The14me** [comment]
It works just fine with rank 5 as suppose to be. Next ranks are higher level and won't work.
https://classic.wowhead.com/item=2633/jungle-remedy#comments:id=2631600
Can be closed.
