### ISSUE TITLE
Gurubashi Arena Event Desync??

### ISSUE THREAD

**Issue by ValveHatesDotA** [Atlantiss/NetherwingBugtracker#4625]
**Current behaviour**: Event is at 2/5/8/11 ST

**Expected behaviour**:  Supposed to be 3/6/9/12  ST 

**Server Revision**: 2712

**Comment by The14me** [comment]
Worth a recheck.

**Comment by Tereneckla** [comment]
Servertime is changing with Summer/Winter time, but events don't adapt to that.
