### ISSUE TITLE
[Boss][Spell][Karazhan](Shade of Aran) Flame Wreath

### ISSUE THREAD

**Issue by AxeCell** [Atlantiss/NetherwingBugtracker#4626]
**Description**: 
Topic is related to the behaviour of the Flame Wreath ability used by Shade of Aran found within Karazhan.

**Current behaviour**:
Flame Wreath will based on certain conditions trigger even if nobody moved.
At this timestamp he sent Pym flying, even if he was mid shadow bolt cast. Aran will also reset due to his target being high up in the air: https://youtu.be/NCfr0Dmds2Y?t=19443

Here's timestamps showcasing Flame Wreath triggering at the end of its duration:

https://youtu.be/NCfr0Dmds2Y?t=19845 | https://youtu.be/NCfr0Dmds2Y?t=20573 | https://youtu.be/NCfr0Dmds2Y?t=20638 | https://youtu.be/NCfr0Dmds2Y?t=21210 | https://youtu.be/NCfr0Dmds2Y?t=23831

Cause might be linked to either camera movement, or members positioning in relation to the Flame Wreath circles.

**Expected behaviour**: 
Flame Wreath should never trigger if nobody in the raid party is moving during the effect.

**Server Revision**: 
2712

**Comment by nullfoxh** [comment]
This might seem like a long shot, but could it be related to this?
I constantly run in to the issue where my character keeps turning after having finished a right-mouse-button turn, just like in this reports videos: https://github.com/Atlantiss/NetherwingBugtracker/issues/3962

**Comment by Frankenberryberry** [comment]
We had a lot of problems with the mechanic as well. What finally did the trick for us was to stay a bit away from each other. Stacking seemed to blow us up.

**Comment by knasen88** [comment]
gigaScuffed smileyface https://clips.twitch.tv/RespectfulSpicyEagleWOOP
not an inch was moved that try

**Comment by Easyfraggy** [comment]
As I said above it seems to be application and removal that sometimes just causes it to blow up.

**Comment by DragunovUA** [comment]
so anyone work on fix this?

**Comment by 5f3759** [comment]
This bug is very critical. Guilds basically just have to pray to rngesus to get past this.
If it's any clue, it only happened to our range players, melee seemed fine.

**Comment by sandreid** [comment]
Seems to only happen to casters: Mages and Priests, primarily. Also possibly Paladins.

**Comment by Drayo** [comment]
For us it did not happen at all on the first ID, but last weekend we chain wiped to this shit.

No matter what we did, someone would randomly blow up right when the debuff was about to fade, sometimes casters, sometimes the tank standing at the edge of the room not even touching his peripherals. Also, Aran would even reset because a player was too high in the air.

It cost us more than two hours to get past this Boss. Please look into this.

**Comment by mnnny** [comment]
When I did Karazhan yesterday, flame wreath triggered to an almost 100% at the end of the duration every time, it seems to be completely random who triggers it, melee or ranged, mana users or non-mana users, based on like 20 attempts yesterday. He also reset his HP a couple of times when FW triggered. We also got new elemental adds at around 10%, FW seemed to trigger that as well, clip below on that as well. Whatever it is, FW seems to make this boss just break.

https://www.twitch.tv/mnnyy/clip/TenderSwissJuiceAsianGlow
https://clips.twitch.tv/InexpensiveRockyCheetahWOOP

**Comment by Easyfraggy** [comment]
It's very hard to fix something that happens randomly - we need to figure out what is really causing the flame wreath to blow up - There was an extention of the grace period done today - lets see if its fixed by that on next update.

**Comment by Wolffenstein** [comment]
Fixed in rev 2768.

**Comment by 5f3759** [comment]
Still not fixed in 2770.
Both our kara groups experiencing the same issue. No movement at all, not even casting or turning and still triggers it.

**Comment by Djmaxcrime** [comment]
yep its even more broken then before it used to proc from stacking now no idea whats procing it but with out fail it will now proc once per fight.

**Comment by Picajzla** [comment]
https://www.twitch.tv/videos/376144972 2:38:30-3:15:00  Here are some tries fron 6/2 after the update. Flame wreath is still very much an issue

**Comment by 5f3759** [comment]
https://www.twitch.tv/videos/376144972?t=02h40m18s
From picajzla's video above.
The warrior explodes without moving, clear as day.

**Comment by knasen88** [comment]
PLEASE FIX, STILL BROKEN
