### ISSUE TITLE
[Core][World Map] Unable to Discover Feathermoon Stronghold

### ISSUE THREAD

**Issue by Alumian** [Atlantiss/NetherwingBugtracker#4629]
[//]: # (Enclose links to things related to the bug using http://wowhead.com or any other TBC database.)
[//]: # (You can use screenshot ingame to visual the issue.)
[//]: # (Write your tickets according to the format:)
[//]: # ([Quest][Azuremyst Isle] Red Snapper - Very Tasty!)
[//]: # ([NPC] Magistrix Erona)
[//]: # ([Spell][Mage] Fireball)
[//]: # ([Npc][Drop] Ghostclaw Lynx)
[//]: # ([Web] Armory doesnt work)
[//]: # (To find server revision type `.server info` command in the game chat.)

**Description**: Upon entering/roaming around the Feathermoon Stronghold in Feralas, it does not become discovered on the map.

**Current behaviour**: Upon entering/roaming around the Feathermoon Stronghold in Feralas, it does not become discovered on the map.

![Map showing undiscovered Feathermoon Stronghold](https://i.imgur.com/jnJOCwQ.png)

**Expected behaviour**: The stronghold should explore upon entering the proximity of the area.

**Server Revision**: 2712

**Comment by The14me** [comment]
Rev.3460 not an issue anymore. It may be addon or cache back then.
Can be closed.
