### ISSUE TITLE
[Spell][Hunter] Humanoid tracking - Deepmoss Eggs tracking icon

### ISSUE THREAD

**Issue by mbzz88** [Atlantiss/NetherwingBugtracker#463]
**Description**: When using Track Humanoids, "Deepmoss Eggs" show up on tracking as "Deepmoss Eggs hackfixerino" https://www.wowhead.com/object=19541/deepmoss-eggs

**Current behaviour**: lol hackfixerino ![wowscrnshot_092518_140137](https://user-images.githubusercontent.com/43509267/45988637-ff5d5180-c0cb-11e8-9af2-d7c78517120d.jpg)

**Expected behaviour**: Deepmoss Eggs should be untrackable with Track Humanoids

**Comment by Evolvee** [comment]
@Wolffenstein u need to exclude triggers from "find" spells

**Comment by xmesaj2** [comment]
fix in rev 2054

**Comment by xmesaj2** [comment]
globally fixed in rev 2081
