### ISSUE TITLE
[Core] Weapon Skill Rate vs Grey Mobs

### ISSUE THREAD

**Issue by OMEGALULW** [Atlantiss/NetherwingBugtracker#4631]
**Current behaviour**: Fighting a grey mob resulted in this https://i.imgur.com/G7sMsGu.png 

Player lvl 46 mob lvl 35 (Shadowforge Tunneler Badlands)

**Expected behaviour**:  You shouldn't gain fucktonnes of skill points in a few seconds

**Server Revision**: 3712

**Comment by Azalen** [comment]
#362
