### ISSUE TITLE
Scholomance Summoners Summoning Skeletons Downstairs

### ISSUE THREAD

**Issue by Ashfall7x** [Atlantiss/NetherwingBugtracker#4632]
**Description**: Summoners in Scholomance are bugged.

**Current behaviour**: They summon Skeletons downstairs, which then pull the entire dungeon and wipe everyone.

**Expected behaviour**: They should summon it correctly on their floor level.

**Comment by Ashfall7x** [comment]
> By chance did you have someone in your party using an AOE? I do remember quite well that if a warlock used seed of corruption, it would hit the summoners from downstairs too in retail.
> 
> (...I was said warlock that wiped the party a few times before we discovered that)

I've ran it twice, neither of these runs had a single warlock. I've observed it in order to understand the bug using my bubble to run out. 

Summoners do summon skeletons to downstairs, not on all terrain types though, I think some of them lack some sort of an invisible wall that glitches the spawn.

**Comment by Evolvee** [comment]
rev 2827
