### ISSUE TITLE
[Instances] Normal Instances undergo forced resets at the heroic reset time.

### ISSUE THREAD

**Issue by tcberk12** [Atlantiss/NetherwingBugtracker#4633]
**Description**: 

Normal instances are currently being reset at the heroic reset time. This is a restriction that does not need to be in place for Normal dungeons and can lead to frustrating outcomes for unsuspecting groups.

**Current behaviour**:

Currently, Normal instances are force reset at the heroic reset time (09:00 Server Time). This boots the entire group out of the instance and, of course, resets the instance. 

**Expected behaviour**: 

 The daily reset of the instance is in place for heroic dungeons that are meant to be run once per day, and should not be in play for normal dungeons. The only instance reset mechanic that should be in play with normal dungeons is that you can reset, at maximum, 5 times per hour.

This statement on a 2009 post by Engadget makes it seem rather clear Normal dungeons are not subject to being reset at the daily reset time: https://www.engadget.com/2009/07/15/wow-rookie-the-inner-workings-of-instances/

>Because heroics offer such high-quality loot, heroics are on a special lockout timer and can only be run once a day per character. Heroics cannot be hard reset by group leaders. The timers are reset automatically every day at 11 a.m. server time on U.S. servers and 8 a.m. server time on European servers. If you are inside a heroic instance when it resets, you'll be teleported to the nearest graveyard.

**Server Revision**: 
 2712

Edit: to further clarify, i'm not saying normal dungeons are "saving" players and only allowing 1 run per day. You can still spam normal dungeons. It is just that they are being unnecessarily reset by the server at the heroic/raid reset time, which is incorrect.

**Comment by tcberk12** [comment]
Bump

**Comment by DragunovUA** [comment]
blizzlike lol
who and why did that

**Comment by Wolffenstein** [comment]
Fixed in rev 2788.
