### ISSUE TITLE
[Quest] Power Stones

### ISSUE THREAD

**Issue by elenmerbau** [Atlantiss/NetherwingBugtracker#4634]
[//]: # (Enclose links to things related to the bug using http://wowhead.com or any other TBC database.)
[//]: # (You can use screenshot ingame to visual the issue.)
[//]: # (Write your tickets according to the format:)
[//]: # ([Quest][Azuremyst Isle] Red Snapper - Very Tasty!)
[//]: # ([NPC] Magistrix Erona)
[//]: # ([Spell][Mage] Fireball)
[//]: # ([Npc][Drop] Ghostclaw Lynx)
[//]: # ([Web] Armory doesnt work)
[//]: # (To find server revision type `.server info` command in the game chat.)

**Description**: 
Quest Power Stones is bugged. We were able to get it, got all the quest items, but can't turn in. I decided to abandon it and can't even get it now. Looks like the quest npc, Rigglefuzz, is stuck.
**Current behaviour**:
^
**Expected behaviour**: 
It should let us turn in the quest! >:c
**Server Revision**: 
2712

**Comment by Many12997** [comment]
I believe it's NPC itself that's bugged,I can't turn in quest for buzzard wings :(
https://classic.wowhead.com/npc=2817/rigglefuzz#comments

**Comment by Manaci** [comment]
Fixed
