### ISSUE TITLE
Client crashes while in party. Character shows as no longer in the party even if it is.

### ISSUE THREAD

**Issue by jorgehog** [Atlantiss/NetherwingBugtracker#4636]
[//]: # (Enclose links to things related to the bug using http://wowhead.com or any other TBC database.)
[//]: # (You can use screenshot ingame to visual the issue.)
[//]: # (Write your tickets according to the format:)
[//]: # ([Quest][Azuremyst Isle] Red Snapper - Very Tasty!)
[//]: # ([NPC] Magistrix Erona)
[//]: # ([Spell][Mage] Fireball)
[//]: # ([Npc][Drop] Ghostclaw Lynx)
[//]: # ([Web] Armory doesnt work)
[//]: # (To find server revision type `.server info` command in the game chat.)

**Description**: up to 2-3 times a day when I'm grouping I the game client crashes instantly and I get logged out. It happened today around ~9:30 for my character Joar. When I logged back in I was no longer in the group according to my screen, but according to others I was still in it. The same happened yesterday twice, but then it happened to another rogue in my party at the exact same time. That's when I wrote the initial ticket. It can't be a coincidence if it happens to two people in the party at the exact same time.

Sometimes after such a crash I've logged in dead even if there was no threats around and I was gone only around 10 sec.

This _only_ happens when I'm in a party.

**Current behaviour**: Sudden crash (game closes). Logging in showing as not in the party anymore even if other party members see me as still in it.

**Expected behaviour**: Not crashing. Still being shown as in party when logging in.

**Server Revision**: 2712

**Comment by jorgehog** [comment]
Could be related to these issues:
https://github.com/Atlantiss/NetherwingBugtracker/issues/4410
https://github.com/Atlantiss/NetherwingBugtracker/issues/3949

I also notice a comment in 3949 saying there is a rogue in the picture. When I think back this could have been the case for all my crashes as well. Either a rogue or a cat druid in stealth. But I am not 100% on this, but I cannot remember a single crash without a stealthed party member.

**Comment by Wolffenstein** [comment]
This issue has been resolved.
