### ISSUE TITLE
LFG/LFM tool

### ISSUE THREAD

**Issue by elenmerbau** [Atlantiss/NetherwingBugtracker#4637]
[//]: # (Enclose links to things related to the bug using http://wowhead.com or any other TBC database.)
[//]: # (You can use screenshot ingame to visual the issue.)
[//]: # (Write your tickets according to the format:)
[//]: # ([Quest][Azuremyst Isle] Red Snapper - Very Tasty!)
[//]: # ([NPC] Magistrix Erona)
[//]: # ([Spell][Mage] Fireball)
[//]: # ([Npc][Drop] Ghostclaw Lynx)
[//]: # ([Web] Armory doesnt work)
[//]: # (To find server revision type `.server info` command in the game chat.)

Hello there! The way LFG/LFM tool works was bothering me from the beginning. My problem is that it has specific level range and won't let you queue or search for people for dungeons if you don't fit in it. It makes sense when you're too small for it and I have no problem with it at all. But it won't let you in if you're "too high". I am level 45 atm and I got all the quests for Uldaman, but I can't use the tool anymore. 
Can you guys somehow solve this problem? For example, remove levelblock for high level players. Or just move it a little, so people that came "late" will be able to queue and use the tool.
I know that I can use /world channel instead, but what's the point of LFG tool then!

**Comment by Balanarr** [comment]
That is how the LFG tool always worked. The point is that if you don't fit in, you shouldn't be there.

**Comment by Tereneckla** [comment]
As Balanarr said
