### ISSUE TITLE
[Spell] Bloodmaul Buzz

### ISSUE THREAD

**Issue by femdead** [Atlantiss/NetherwingBugtracker#4639]
Sometimes heals the Bloodmaul Mauler to full hp. Not part of the spell

**Comment by Eidous** [comment]
as an extra piece of info, i'm 99% this occurs when the spell effect runs out

**Comment by femdead** [comment]
After finishing killing 10 of them, one of which full-healed twice in a row, it seems like it's the bloodmaul buzz running out and being instantly refreshed every 20 seconds which sets them to full hp - which happens to coincide with them enraging

**Comment by Tenoutoften** [comment]
I saw this too but never got around to reporting it

**Comment by rychersky** [comment]
Just had a Bloodmaul Mauler heal from 15% to full upon applying Bloodmaul Buzz to itself.

**Comment by mhawkins30** [comment]
Can confirm this is still occurring as of server revision 2825.

**Comment by Tenoutoften** [comment]
https://github.com/Atlantiss/NetherwingBugtracker/issues/2211
https://github.com/Atlantiss/NetherwingBugtracker/issues/2333

**Comment by Tereneckla** [comment]
Duplicate of #2211
