### ISSUE TITLE
[NPC Bristlelimb Shaman using wrong totem.

### ISSUE THREAD

**Issue by Sothanwow** [Atlantiss/NetherwingBugtracker#464]
**Description**: 
Some of the Bristlelimb Shamans are using the Drenai totem model and others are using the one they should be. These two pictures are both from the server. [Here](https://imgur.com/a/mJmOJdS)
It only seems like the shamans around Princess Silverpine are casting the Drenai version of the totem while the ones up the hill are using the other correct version.

npc https://www.wowhead.com/npc=17320/bristlelimb-shaman

**Current behaviour**:
Totem Has the Drenai totem
**Expected behaviour**: 
Totem should not be Drenai version.
**Server Revision**: 
2045

**Comment by The14me** [comment]
https://github.com/Atlantiss/AtlantissTBCBT/issues/4193

**Comment by xmesaj2** [comment]
fixed in 2139
