### ISSUE TITLE
[Spell][Hunter]Beast Lore

### ISSUE THREAD

**Issue by Eidous** [Atlantiss/NetherwingBugtracker#4640]
[//]: # (Enclose links to things related to the bug using http://wowhead.com or any other TBC database.)
[//]: # (You can use screenshot ingame to visual the issue.)
[//]: # (Write your tickets according to the format:)
[//]: # ([Quest][Azuremyst Isle] Red Snapper - Very Tasty!)
[//]: # ([NPC] Magistrix Erona)
[//]: # ([Spell][Mage] Fireball)
[//]: # ([Npc][Drop] Ghostclaw Lynx)
[//]: # ([Web] Armory doesnt work)
[//]: # (To find server revision type `.server info` command in the game chat.)

**Description**: 
Beast lore doesn't show hp in absolute values

**Current behaviour**:
Beast lore shows hp as percentage

**Expected behaviour**: 
Beast lore should show hp as absolute value

**Server Revision**: 
2712

**Comment by Wolffenstein** [comment]
Fixed in rev 2861.
