### ISSUE TITLE
[Web] first aid skill does not update after paying for

### ISSUE THREAD

**Issue by turandot11** [Atlantiss/NetherwingBugtracker#4641]
[//]: # (Enclose links to things related to the bug using http://wowhead.com or any other TBC database.) i have no clue what does it mean
[//]: # (You can use screenshot ingame to visual the issue.)
![image](https://user-images.githubusercontent.com/47083322/51802912-bd305200-221c-11e9-8508-13bc30fdde5e.png)

[//]: # (Write your tickets according to the format:)
[//]: # ([Quest][Azuremyst Isle] Red Snapper - Very Tasty!)
[//]: # ([NPC] Magistrix Erona)
[//]: # ([Spell][Mage] Fireball)
[//]: # ([Npc][Drop] Ghostclaw Lynx)
[//]: # ([Web] Armory doesnt work)
[//]: # (To find server revision type `.server info` command in the game chat.)

**Description**: the first aid skill does not update after being paid for. I still have 150/150 for first aid, got the new recipe for next level bandages, but while making them the skill remains the same. Aid trainer has nothing to offer.

**Current behaviour**:

**Expected behaviour**: 

**Server Revision**:

**Comment by turandot11** [comment]
thank you.but perhaps this is the case for the later versions, not Burning Crusade?...i went to this castle (Stromgarde Keep) - it is swarming with lvl 35 and up mobs, no SW station or trainers there. Nad being level 29, i am obviously cannot easely go thru the mobs

**Comment by Peglaa** [comment]
You do not need to go thru any mobs actually, when you enter stromgarde keep just turn right on the first intersection and then another right along the wall, you will see friendly guards around, keep following it until you cross a bridge and the NPC that sells the book should be on your right, next to a well I think.

**Comment by turandot11** [comment]
thanks!after being killed by ?? lvl horde in the Arathi Highlands for few times in the orw, i gave up and bought the book in AH.

**Comment by The14me** [comment]
150+ FA is from a book as Pegla say 
Can be closed.
