### ISSUE TITLE
[Quest][Feralas]The Ogres of Feralas - respawn time for ogres is broken

### ISSUE THREAD

**Issue by Maelareth** [Atlantiss/NetherwingBugtracker#4644]
** Description **
The ogres for The Ogres of Feralas are respawning too slow, quest is good as impossible to complete.

** Current Behaviour **
The ogres for The Ogres of Feralas are respawning too slow, quest is good as impossible to complete.

**Expected behaviour**: 
The mobs need to have a dynamic spawn rate added to them

**Server Revision**: 
2712

**Comment by DKXAM** [comment]
Its not just this, the chance for warlocks to spawn is too low, spend half an hour grinding all mobs there and saw 2 of them. It is impossible to complete at the moment.

**Comment by maxturtlesc2** [comment]
Confirm this. Went to most of the possible spawn points for warlocks and shamans, didn't see any. Even if they are pooled with other ogres, it shouldn't be this bad.

**Comment by Easyfraggy** [comment]
Spawn time was fine - the problem is that the warlocks and shamans seem to spawn way too rarely.

**Comment by Tereneckla** [comment]
duplicate #3989
