### ISSUE TITLE
Sending many mails to a single alt results in too many unique recipients error

### ISSUE THREAD

**Issue by grimetone** [Atlantiss/NetherwingBugtracker#4646]
[//]: # (Enclose links to things related to the bug using http://wowhead.com or any other TBC database.)
[//]: # (You can use screenshot ingame to visual the issue.)
[//]: # (Write your tickets according to the format:)
[//]: # ([Quest][Azuremyst Isle] Red Snapper - Very Tasty!)
[//]: # ([NPC] Magistrix Erona)
[//]: # ([Spell][Mage] Fireball)
[//]: # ([Npc][Drop] Ghostclaw Lynx)
[//]: # ([Web] Armory doesnt work)
[//]: # (To find server revision type `.server info` command in the game chat.)

**Description**: 
Sending ingame mails to a single alt account eventually results in being unable to send mails, telling the user that the number of unique recipients have been exceeded

**Current behaviour**:
User is unable to send emails, being told that he has exceeded the number of unique recipients, despite only sending mail to a single alt character

**Expected behaviour**: 
User should be able to send as many mails as he wishes to a single alt character or if this is inteded the error message of too many unique recipients should be revised.

**Server Revision**:

**Comment by sadfx** [comment]
Is your alt's mailbox full?

**Comment by grimetone** [comment]
I'm quite sure it wasn't, but it's a slim possibility.

**Comment by Tereneckla** [comment]
rev 3058
