### ISSUE TITLE
Badge of Justice cant be looted

### ISSUE THREAD

**Issue by Fekapinainas** [Atlantiss/NetherwingBugtracker#4647]
I was in a group with my guildmates, we killed the first boss in HC MT, noone died, I was in the instance during the whole fight, but when I went to the boss to loot my badge, the game said: You dont haver permission to loot that corpse. We put it to FFA but didnt helped.
I relogged and the corpse looks looted now, the cursor didnt interact on it.

**Comment by Manaci** [comment]
Fixed with loot rework
