### ISSUE TITLE
[Spell][Mage Portals]

### ISSUE THREAD

**Issue by Bakster15** [Atlantiss/NetherwingBugtracker#4648]
[//]: # (Enclose links to things related to the bug using http://wowhead.com or any other TBC database.)
[//]: # (You can use screenshot ingame to visual the issue.)
[//]: # (Write your tickets according to the format:)
[//]: # ([Quest][Azuremyst Isle] Red Snapper - Very Tasty!)
[//]: # ([NPC] Magistrix Erona)
[//]: # ([Spell][Mage] Fireball)
[//]: # ([Npc][Drop] Ghostclaw Lynx)
[//]: # ([Web] Armory doesnt work)
[//]: # (To find server revision type `.server info` command in the game chat.)

**Description**: 
Any party member is unable to use your portal if you're not in the same zone as them. So if I take the portal before my party members they're unable to click it.
**Current behaviour**:
The mage needs to be the last person to use his portal for everyone to get trough.
**Expected behaviour**: 
All members should be able to use the portal for the 1 minute duration. No matter where the portal creator(mage) is.
**Server Revision**: 
2712

**Comment by killablink** [comment]
Funnily it worked back in beta but it stopped working somewhere during launch
