### ISSUE TITLE
[item][schematic] Adamantite Shell Machine and Adamantite Arrow Maker are not in game

### ISSUE THREAD

**Issue by Sogarez** [Atlantiss/NetherwingBugtracker#4649]
**Description**: 
Schematic for adamantite shell machine
https://wowwiki.fandom.com/wiki/Schematic:_Adamantite_Shell_Machine
and adamantite arrow maker
https://wowwiki.fandom.com/wiki/Schematic:_Adamantite_Arrow_Maker
cannot be obtained in game. 

For sure it appeared far before 2.1.0, because according to this official patch notes
http://wowwiki.wikia.com/wiki/Patch_2.1.0
adamantite shells already was in game and was slightly changed in 2.1.0 patch

**Current behaviour**:
no schematics of shell machine at vendor
killed 300 sunfury archers and no drop of arrow maker

**Expected behaviour**: 
they must be in game

**Server Revision**: 
2712

**Comment by Balanarr** [comment]
As per wowhead.
Adamantite Shell Machine was added in patch 2.1.0 - https://www.wowhead.com/item=23815/ruined-schematic

and

Adamantite Arrow Maker was added in patch 2.3.0 - https://www.wowhead.com/item=33804/ruined-schematic

both are renamed to ruined schematic but itemid remains

**Comment by Balanarr** [comment]
Adamantite Arrow Maker was added in 2.3, see the comments. https://www.wowhead.com/item=33804/ruined-schematic#comments
Adamantite Shell Machine was also converted in 2.3 https://www.wowhead.com/item=23815/ruined-schematic#comments
And prior to 2.3 was only creating Adamantite shells

**Comment by Sogarez** [comment]
Yes, there was trainable recipe to craft adamantite shells as engineer (1 stack per craft) - on wowhead you can see comments, dated with patch 2.0.x about it like

"This may seem like an excellent way to make money as an Engineer, but be warned, the materials are expensive and there ARE better bullets to be had."

**Comment by Manaci** [comment]
Irrelevant now
