### ISSUE TITLE
[Quest] Bloodfury Bloodline

### ISSUE THREAD

**Issue by manslaughter** [Atlantiss/NetherwingBugtracker#465]
**Description**: This quest requires you to kill the Bloodfury Ripper and loot its remains as the quest objective.

**Current behaviour**: The Bloodfury Ripper does not drop the remains.

**Expected behaviour**: Bloodfury Ripper drops remains 100%.

**Server Revision**: 2045

**Comment by manslaughter** [comment]
duplicate

**Comment by wtRCH** [comment]
Duplicate of https://github.com/Atlantiss/NetherwingBugtracker/issues/316
