### ISSUE TITLE
Battleground Party

### ISSUE THREAD

**Issue by jakeoff** [Atlantiss/NetherwingBugtracker#4650]
[//]: # (Enclose links to things related to the bug using http://wowhead.com or any other TBC database.)
[//]: # (You can use screenshot ingame to visual the issue.)
[//]: # (Write your tickets according to the format:)
[//]: # ([Quest][Azuremyst Isle] Red Snapper - Very Tasty!)
[//]: # ([NPC] Magistrix Erona)
[//]: # ([Spell][Mage] Fireball)
[//]: # ([Npc][Drop] Ghostclaw Lynx)
[//]: # ([Web] Armory doesnt work)
[//]: # (To find server revision type `.server info` command in the game chat.)

**Description**: Accepting a group invite while in a Battleground will kick you from the BG group. This is not a visual problem either, as you cannot use certain party-specific abilities on teammates.

**Current behaviour**: Accepting a group invite while in a Battleground will kick you from the BG group.

**Expected behaviour**: Accepting a group invite while in a Battleground should not kick you from the BG group. You should remain in the BG group while also being in the other party outside of the instance.

**Server Revision**:

**Comment by yutsuku** [comment]
You're also unable to see and use battleground chat, people around will not see you at all when in stealth (applies to rogues/druids and night elves)
