### ISSUE TITLE
[Spell] Cheap Shot doesn't put you in combat

### ISSUE THREAD

**Issue by Tixlenra** [Atlantiss/NetherwingBugtracker#4652]
[//]: # (Enclose links to things related to the bug using http://wowhead.com or any other TBC database.)
[//]: # (You can use screenshot ingame to visual the issue.)
[//]: # (Write your tickets according to the format:)
[//]: # ([Quest][Azuremyst Isle] Red Snapper - Very Tasty!)
[//]: # ([NPC] Magistrix Erona)
[//]: # ([Spell][Mage] Fireball)
[//]: # ([Npc][Drop] Ghostclaw Lynx)
[//]: # ([Web] Armory doesnt work)
[//]: # (To find server revision type `.server info` command in the game chat.)

**Description**:  [Spell] Cheap Shot doesn't put you in combat

**Current behaviour**: [Spell] Cheap Shot doesn't put you in combat, if you have a friend attack a mob, stealth, only cast cheap shot without auto attacking, you'll be able to restealth.

**Expected behaviour**:  should enter combat when casting cheap shot on enemy NPC/enemy player

**Server Revision**: 2712

**Comment by knasen88** [comment]
Every single non damage spell tend to have this *feature*,

**Comment by The14me** [comment]
rev.3460 it put u in combat as other stun/cc ability's (charge/Hammer or justice)
Can be closed.
