### ISSUE TITLE
[NPC][Botanica] Warp Splinter Arcane Volley

### ISSUE THREAD

**Issue by Brasso** [Atlantiss/NetherwingBugtracker#4653]
[//]: # (Enclose links to things related to the bug using http://wowhead.com or any other TBC database.)
[//]: # (You can use screenshot ingame to visual the issue.)
[//]: # (Write your tickets according to the format:)
[//]: # ([Quest][Azuremyst Isle] Red Snapper - Very Tasty!)
[//]: # ([NPC] Magistrix Erona)
[//]: # ([Spell][Mage] Fireball)
[//]: # ([Npc][Drop] Ghostclaw Lynx)
[//]: # ([Web] Armory doesnt work)
[//]: # (To find server revision type `.server info` command in the game chat.)

**Description**: 
This spell is not functioning correctly at the moment. The damage is correct for 2.0, but the mechanic of the spell is not. It should count friendly entities in the room minus 4 according to this wowhead comment and not be direction dependent.

![image](https://user-images.githubusercontent.com/44345420/51805150-4fab1280-226a-11e9-8a2c-e26a81681c0a.png)

**Current behaviour**:
Arcane Volley currently hits everything in the room regardless of how many there are. Removing pets and totems does nothing.
**Expected behaviour**: 
Being only 5 in the group and removing any potential pets or totems should limit the Arcane Volley to 1 bolt, making the mechanic manageable on heroic.
**Server Revision**: 
2712

**Comment by Tenoutoften** [comment]
https://github.com/Atlantiss/NetherwingBugtracker/issues/2821#issuecomment-440281103
>Need jan-march vid - dec is too late. Current value is from 2.0 spell DB - so unlikely it's wrong.

Your comment is from april so I don't think leadership will change anything, it's too late in 2.0 for them.

https://github.com/Atlantiss/NetherwingBugtracker/issues/3753
https://github.com/Atlantiss/NetherwingBugtracker/issues/3148
https://github.com/Atlantiss/NetherwingBugtracker/issues/3022
https://github.com/Atlantiss/NetherwingBugtracker/issues/2821

**Comment by Brasso** [comment]
Here's a video from Feb 4th https://www.youtube.com/watch?v=KGFrSMBMXzM Notice the hunter has his pet dismissed for the fight. Arcane volley only hits the tank.

Video from Feb 22, https://www.youtube.com/watch?v=T-gbAfL_Ytk Warlock and and hunter have their pets out, and there are 2 more arcane volleys hitting the group.

**Comment by Azalen** [comment]
@Evolvee 
Endboss is unkillable if you don't bring the perfect setup (heroism + 3 ranged dps). This can't be correct - even in patch 2.0

**Comment by Evolvee** [comment]
easy is not leadership

**Comment by Tereneckla** [comment]
https://www.youtube.com/watch?v=L7pWoLhj3DE
Here we see a total group size of 6 (5 players+1 pet)
Arcane Volley hits 2-3 targets each time.

**Comment by Wolffenstein** [comment]
Fixed in rev 3363.
