### ISSUE TITLE
Towers in Eastern Plaguelands don't spawn spectral gryphons. 

### ISSUE THREAD

**Issue by Uriskall** [Atlantiss/NetherwingBugtracker#4654]
[Pictures of the tower without a spectral flight path:](https://imgur.com/a/7jxyuOc) 
After taking all four towers in Eastern Plaguelands, it appears that only the Plaguewood tower has the spectral gryphon master.
**Current behaviour**:
Out of all four towers only the Plaguewood Tower has the Spectral Gryphon Master.
**Expected behaviour**: 
All four towers should have Spectral Gryphon Masters.
**Server Revision**: 
2712

**Comment by Azalen** [comment]
Pretty sure this is invalid.

For reference #1767 and https://wowwiki.fandom.com/wiki/A_Game_of_Towers

There is no mention of all four towers having spectral gryphon masters.
