### ISSUE TITLE
[NPC][Drop] Swamp Gas (engineering)

### ISSUE THREAD

**Issue by lildarlin** [Atlantiss/NetherwingBugtracker#4655]
[//]: # (Enclose links to things related to the bug using http://wowhead.com or any other TBC database.)
[//]: # (You can use screenshot ingame to visual the issue.)
[//]: # (Write your tickets according to the format:)
[//]: # ([Quest][Azuremyst Isle] Red Snapper - Very Tasty!)
[//]: # ([NPC] Magistrix Erona)
[//]: # ([Spell][Mage] Fireball)
[//]: # ([Npc][Drop] Ghostclaw Lynx)
[//]: # ([Web] Armory doesnt work)
[//]: # (To find server revision type `.server info` command in the game chat.)

**Description**: 
There is a problem with Swamp Gas drop in Zangarmarsh. Either random or wrong drop when using engineering item Zapthrottle Mote Extractor.
**Current behaviour**:
Drops Mote of LIFE when using Zapthrottle Mote Extractor
**Expected behaviour**: 
Drops Mote of WATER when using Zapthrottle Mote Extractor
**Server Revision**:

**Comment by nuiva** [comment]
https://wowwiki.fandom.com/wiki/Swamp_Gas

> Patch 2.3.0 (13-Nov-2007): Gas clouds in Zangarmarsh now produce [Motes of Water] instead of [Motes of Life].

Considering we're in 2.0 or something, it might be intended.

**Comment by lildarlin** [comment]
Indeed, should have made some research first. I did not know about this. Anyway, progressive patch are always confusing regarding what is and what is not progressive.

**Comment by The14me** [comment]
Worth a check for future patches.

**Comment by Xithus** [comment]
Game is showing patch 2.4.3 now so this swamp gas should be giving motes of water now instead of life.

https://wowwiki.fandom.com/wiki/Gas_cloud

**Comment by Godmatik** [comment]
We are on 2.1 and not 2.4.3, type .info while in-game

If we were on 2.4.3, then Sunwell would be released.
