### ISSUE TITLE
[Quest][Nagrand] Shattering the veil quest mobs don't spawn if target is stunned

### ISSUE THREAD

**Issue by Mikik3jr** [Atlantiss/NetherwingBugtracker#4656]
[//]: # (Enclose links to things related to the bug using http://wowhead.com or any other TBC database.)
[//]: # (You can use screenshot ingame to visual the issue.)
[//]: # (Write your tickets according to the format:)
[//]: # ([Quest][Azuremyst Isle] Red Snapper - Very Tasty!)
[//]: # ([NPC] Magistrix Erona)
[//]: # ([Spell][Mage] Fireball)
[//]: # ([Npc][Drop] Ghostclaw Lynx)
[//]: # ([Web] Armory doesnt work)
[//]: # (To find server revision type `.server info` command in the game chat.)

**Description**: 
In this quest you get a quest item and you use it to shatter earth elementals into smaller parts and kill them for credit.

**Current behaviour**:
If the elementals are under stun, nothing spawns out of them.

**Expected behaviour**: 
They should I think? I report this, because maybe it is core releated issue.

**Server Revision**: 
2712

**Comment by The14me** [comment]
By the look at [this](https://www.wowhead.com/npc=18181/minion-of-gurok#comments:id=29624) , it may be intended with all CCs.
