### ISSUE TITLE
[NPC] Eye of The Storm Emissary clips through a bridge

### ISSUE THREAD

**Issue by Mikik3jr** [Atlantiss/NetherwingBugtracker#4658]
[//]: # (Enclose links to things related to the bug using http://wowhead.com or any other TBC database.)
[//]: # (You can use screenshot ingame to visual the issue.)
[//]: # (Write your tickets according to the format:)
[//]: # ([Quest][Azuremyst Isle] Red Snapper - Very Tasty!)
[//]: # ([NPC] Magistrix Erona)
[//]: # ([Spell][Mage] Fireball)
[//]: # ([Npc][Drop] Ghostclaw Lynx)
[//]: # ([Web] Armory doesnt work)
[//]: # (To find server revision type `.server info` command in the game chat.)

**Description**: 
These NPCs are walking around in Stormwind City

**Current behaviour**:
[When they go from The Mage Quarter to The Trade District through a bridge one of the Emissary is moving like she is falling and clips through the bridge.](https://www.youtube.com/watch?v=5Mwtzgif6wM&feature=youtu.be)

**Expected behaviour**: 
Well this shouldn't happen.

**Server Revision**: 
2712

**Comment by The14me** [comment]
rev.3460 still an issue.

**Comment by Wolffenstein** [comment]
Fixed in rev 3477.
