### ISSUE TITLE
Thunder clap on Pygmy tide crawler

### ISSUE THREAD

**Issue by miyago1** [Atlantiss/NetherwingBugtracker#4659]
[//]: # (Enclose links to things related to the bug using http://wowhead.com or any other TBC database.)
[//]: # (You can use screenshot ingame to visual the issue.)
[//]: # (Write your tickets according to the format:)
[//]: # ([Quest][Azuremyst Isle] Red Snapper - Very Tasty!)
[//]: # ([NPC] Magistrix Erona)
[//]: # ([Spell][Mage] Fireball)
[//]: # ([Npc][Drop] Ghostclaw Lynx)
[//]: # ([Web] Armory doesnt work)
[//]: # (To find server revision type `.server info` command in the game chat.)

**Description**: 
[Quest][Darkshore] Buzzbox 411
**Current behaviour**:
Using thunder clap on [NPC] Pygmy tide crawler deals no damage if the NPC isnt agroed.

**Expected behaviour**: 

**Server Revision**:

**Comment by miyago1** [comment]
Looks like it isnt unique to Pygmy tide crawler, even the highborne in Ameth'Aran darkshore display same behavour. Thunder clap deals no damage to mobs not previously damaged or something like that

**Comment by Mikik3jr** [comment]
Same issue with paladin spell
https://github.com/Atlantiss/NetherwingBugtracker/issues/1757

**Comment by duzyizly** [comment]
i belive this get fixed again a few revisions ago.
