### ISSUE TITLE
[Spell][Hunter] Eyes of the Beast

### ISSUE THREAD

**Issue by mbzz88** [Atlantiss/NetherwingBugtracker#466]
**Description**:  When using Eyes of the Beast to move your pet far away, the pet does not despawn until the player moves close to where the pet was.

**Current behaviour**: Unable to control/summon pet after Eyes of the Beast is cancelled, until player moves back in range, then pet despawns. https://youtu.be/BQGNHleLmv8

**Expected behaviour**: Pet should despawn immediately if range is far enough

**Comment by Wolffenstein** [comment]
Fixed in rev 2047.
