### ISSUE TITLE
[Warrior] Auto-attack sometimes stop working in pvp

### ISSUE THREAD

**Issue by Crusaderz** [Atlantiss/NetherwingBugtracker#4660]
Experienced it on battlegrounds and world pvp. I have hamstring macro with /startattack and sometimes AA stop working completly. During AA shutdown i can apply hamstring (it's mean i'm in range and this alone should initiate auto-attacks) and enemy can auto-attack me. When i die and respawn everything working again.

**Comment by Crusaderz** [comment]
https://github.com/Atlantiss/NetherwingBugtracker/issues/4323

**Comment by Crusaderz** [comment]
Also auto-attack **often** does not work in pvp while both me and my target slowed (enemy is running away) and there is like 2-3 yards distance between us.

**Comment by Easyfraggy** [comment]
Duplicate.

**Comment by Easyfraggy** [comment]
https://github.com/Atlantiss/NetherwingBugtracker/issues/2795
