### ISSUE TITLE
[Spell] Vanish makes it so if you walk into a freezing trap you stay stealthed

### ISSUE THREAD

**Issue by Tixlenra** [Atlantiss/NetherwingBugtracker#4661]
[//]: # (Enclose links to things related to the bug using http://wowhead.com or any other TBC database.)
[//]: # (You can use screenshot ingame to visual the issue.)
[//]: # (Write your tickets according to the format:)
[//]: # ([Quest][Azuremyst Isle] Red Snapper - Very Tasty!)
[//]: # ([NPC] Magistrix Erona)
[//]: # ([Spell][Mage] Fireball)
[//]: # ([Npc][Drop] Ghostclaw Lynx)
[//]: # ([Web] Armory doesnt work)
[//]: # (To find server revision type `.server info` command in the game chat.)

**Description**: [Spell] Vanish makes it so if you walk into a freezing trap, you stay stealthed, even though you're trapped

**Current behaviour**: [Spell] Vanish makes it so if you walk into a freezing trap, you stay stealthed, even though you're trapped

**Expected behaviour**: should take you out of stealth/vanish when you're trapped

**Server Revision**: 2712

**Comment by Zarant** [comment]
That's blizzlike https://youtu.be/9z2m9f8Z9P4?t=168

**Comment by Manaci** [comment]
Not a bug
