### ISSUE TITLE
Delayed Health Update does not work properly?

### ISSUE THREAD

**Issue by Mikik3jr** [Atlantiss/NetherwingBugtracker#4662]
[//]: # (Enclose links to things related to the bug using http://wowhead.com or any other TBC database.)
[//]: # (You can use screenshot ingame to visual the issue.)
[//]: # (Write your tickets according to the format:)
[//]: # ([Quest][Azuremyst Isle] Red Snapper - Very Tasty!)
[//]: # ([NPC] Magistrix Erona)
[//]: # ([Spell][Mage] Fireball)
[//]: # ([Npc][Drop] Ghostclaw Lynx)
[//]: # ([Web] Armory doesnt work)
[//]: # (To find server revision type `.server info` command in the game chat.)

**Description**: 
I experienced when I heal someone they still die.

**Current behaviour**:
It happened multiple times in beta (ask Drain) that I healed someone, my heal went off it showed the big juicy green numbers, but the target still died (happened twice in mechanar when Drain was tanking). Some days ago I was ganked and I used my Lay on Hands on myself, it went on CD, but I didn't heal myself. Is it because of the Delayed HP updates?
![image](https://user-images.githubusercontent.com/43505031/51807276-47ac9c00-2285-11e9-815f-84e12e8d19f0.png)

**Expected behaviour**: 
https://www.youtube.com/watch?v=r7CSJqQOypc&feature=youtu.be&t=132
In this video you showed us how it works, so I am guessing the case is similar. I am not the expert of these mechanics, but I report this anyway just in case I am right.

**Server Revision**: 
2712

**Comment by Corpses** [comment]
Bump, this is still bugged.

**Comment by Godmatik** [comment]
Maybe this was a thing during spell batching/spell delay, which is now disabled.

Never once experienced this, nor heard of anyone coming across this issue during the past year of Netherwing.

Closing for now.
