### ISSUE TITLE
[Quest]  [Rescue OOX-09/HL!] Fail Out Of Nowhere

### ISSUE THREAD

**Issue by OMEGALULW** [Atlantiss/NetherwingBugtracker#4668]
**Current behaviour**: Following the chicken while stealthed made the chicken despawn halfway through the escort. 

**Expected behaviour**: Escort shouldn't fail simply because you're stealthed, Feralas one didn't. 

**Server Revision**:  2712

**Comment by sadfx** [comment]
> Were you in group when you started it and got removed/left? That can also cause the quest to fail.

No. I included all relevant information.

**Comment by duzyizly** [comment]
this was probably the reason https://github.com/Atlantiss/NetherwingBugtracker/issues/6121

**Comment by Wolffenstein** [comment]
Fixed in rev 3387.
