### ISSUE TITLE
Fishing cast and loot window

### ISSUE THREAD

**Issue by wtRCH** [Atlantiss/NetherwingBugtracker#467]
[//]: # (Enclose links to things related to the bug using http://wowhead.com or any other TBC database.)
[//]: # (You can use screenshot ingame to visual the issue.)
[//]: # (Write your tickets according to the format:)
[//]: # ([Quest][Azuremyst Isle] Red Snapper - Very Tasty!)
[//]: # ([NPC] Magistrix Erona)
[//]: # ([Spell][Mage] Fireball)
[//]: # ([Npc][Drop] Ghostclaw Lynx)
[//]: # ([Web] Armory doesnt work)

**Description**: 
![image](https://user-images.githubusercontent.com/11255782/45989941-03fb1900-c07e-11e8-8d35-c21075418871.png)

**Comment by Wolffenstein** [comment]
Depends on the error message. You might just not have the skill needed to fish in that place. Need more info.
