### ISSUE TITLE
[Talent] Anticipation

### ISSUE THREAD

**Issue by femdead** [Atlantiss/NetherwingBugtracker#4670]
https://cdn.discordapp.com/attachments/455120632871387156/539279013756272644/unknown.png
Defence skill doesn't actually train past the base maximum for your current level

**Comment by Barry031** [comment]
https://github.com/Atlantiss/NetherwingBugtracker/issues/178

**Comment by Anselm123** [comment]
Can we get some light or help with this? This is a major bug that is gurting tanks a lot.

**Comment by Wolffenstein** [comment]
Fixed in rev 2739.
