### ISSUE TITLE
[Quest/Spawning]

### ISSUE THREAD

**Issue by ErothT** [Atlantiss/NetherwingBugtracker#4671]
The Highland Fleshstalker respawn rate in Arathi Highlands is either ridiculously longer than from before the current revision (2718) or something might be broken. There are almost none of them respawning anywhere.

**Comment by ErothT** [comment]
As of this moment the Ogres nearby also do not spawn at the same rate. This might not be an isolated spawning problem.

**Comment by Tereneckla** [comment]
rev 3236
Decent respawn rate
There even is instant respawn if none are remaining
