### ISSUE TITLE
Warlock Soul link and incoming damage Floating CT

### ISSUE THREAD

**Issue by Pankuticket** [Atlantiss/NetherwingBugtracker#4672]
[//]: # (Enclose links to things related to the bug using http://wowhead.com or any other TBC database.)
[//]: # (You can use screenshot ingame to visual the issue.)
[//]: # (Write your tickets according to the format:)
[//]: # ([Quest][Azuremyst Isle] Red Snapper - Very Tasty!)
[//]: # ([NPC] Magistrix Erona)
[//]: # ([Spell][Mage] Fireball)
[//]: # ([Npc][Drop] Ghostclaw Lynx)
[//]: # ([Web] Armory doesnt work)
[//]: # (To find server revision type `.server info` command in the game chat.)

**Description**: Incoming damage Floating Combat Text not displaying while Soul Link is active

**Current behaviour**: While active incoming damage text is disabled

**Expected behaviour**: While active incoming damage should display

**Server Revision**: 2718

**Comment by Ramzei** [comment]
I see the damage when Soul Link is active, it's in brackets. I'm using MSBT.

**Comment by Balanarr** [comment]
Using SCT and also seeing the part absorbed by soul link

**Comment by devo6969** [comment]
Elvui shows this as well. Took my addons off and used the standard UI and it wouldn't show the amount Soul Link would absorb but instead the "full hit".

**Comment by Tereneckla** [comment]
Addon issue, visible in the standard blizzard SCT and 2 addons I have lying around
