### ISSUE TITLE
[Item] Formula: Enchant Shield - Major Stamina restock timer

### ISSUE THREAD

**Issue by liek0r** [Atlantiss/NetherwingBugtracker#4673]
[//]: # (Enclose links to things related to the bug using http://wowhead.com or any other TBC database.)
[//]: # (You can use screenshot ingame to visual the issue.)
[//]: # (Write your tickets according to the format:)
[//]: # ([Quest][Azuremyst Isle] Red Snapper - Very Tasty!)
[//]: # ([NPC] Magistrix Erona)
[//]: # ([Spell][Mage] Fireball)
[//]: # ([Npc][Drop] Ghostclaw Lynx)
[//]: # ([Web] Armory doesnt work)
[//]: # (To find server revision type `.server info` command in the game chat.)

**Description**: 
On the grounds that `Pattern: Heavy Knothide Leather` restock timer got reduced based on a single [comment from Thottbot](https://web.archive.org/web/20071028143620/http://www.thottbot.com:80/i25720) I hope that we could do the same for the rest of the important profession patterns that have limited supply.

Now I don't have any comment evidence from 2007-2008 but at least later it was faster according to this [comment on Wowhead](https://www.wowhead.com/item=28282/formula-enchant-shield-major-stamina#comments:id=1812016)

It's just ridiculous to try to level up enchanting when the guy is camped like this all the time:
![image](https://user-images.githubusercontent.com/45569234/51833164-66e80f80-22ff-11e9-98d1-9f3e71f537b8.png)

**Comment by Ramzei** [comment]
Also Enchant Shield - Greater stamina sold by Daniel Bartlett in Undercity seems to have a long respawn time.

**Comment by ripwarlock** [comment]
Also Formula: Runed Eternium Rod

**Comment by Tereneckla** [comment]
Comments are from Mists of Pandaria
