### ISSUE TITLE
Triage quest is bugged.

### ISSUE THREAD

**Issue by mi5h4** [Atlantiss/NetherwingBugtracker#4674]
[//]: # (Enclose links to things related to the bug using http://wowhead.com or any other TBC database.)
[//]: # (You can use screenshot ingame to visual the issue.)
[//]: # (Write your tickets according to the format:)
[//]: # ([Quest][Azuremyst Isle] Red Snapper - Very Tasty!)
[//]: # ([NPC] Magistrix Erona)
[//]: # ([Spell][Mage] Fireball)
[//]: # ([Npc][Drop] Ghostclaw Lynx)
[//]: # ([Web] Armory doesnt work)
[//]: # (To find server revision type `.server info` command in the game chat.)

**Description**: 
I got a problem.
I got now max first aid skill at 225. I met all trainers of first aid in Ironforge and Theramore. They have no "recipe" first aid 225+ for me.
Only recipeces of Magewave+ bandages. I think i have no quest Alliance Trauma by the bug. 
Please help me learn skill and rise up my first aid.
Thanks.
**Current behaviour**:
Max First Aid skill is 225
**Expected behaviour**: 
Max first aid skill expected 375
**Server Revision**:

**Comment by Tenoutoften** [comment]
Well, what level did you try to pick it up?

**Comment by mi5h4** [comment]
35 or 36+

**Comment by mi5h4** [comment]
Now i try do it at 43 an there is now quest. i am now sure, may be i do it later before 35 lvl. Can we rollback this quest for me?

**Comment by mi5h4** [comment]
No help for me? i dont want to levelup new warrior.

**Comment by sadfx** [comment]
Quest was working just fine the other day. Go to Theramore at Lvl 35+ with 225/225 FA.. Complete Triage .. Ez

**Comment by Manaci** [comment]
Not bugged
