### ISSUE TITLE
[Core][Mail] Can't send myself mail from bank char, "You have reached the in-game cap of unique mail recipients"

### ISSUE THREAD

**Issue by Jacksn5** [Atlantiss/NetherwingBugtracker#4675]
[//]: # (Enclose links to things related to the bug using http://wowhead.com or any other TBC database.)
[//]: # (You can use screenshot ingame to visual the issue.)
[//]: # (Write your tickets according to the format:)
[//]: # ([Quest][Azuremyst Isle] Red Snapper - Very Tasty!)
[//]: # ([NPC] Magistrix Erona)
[//]: # ([Spell][Mage] Fireball)
[//]: # ([Npc][Drop] Ghostclaw Lynx)
[//]: # ([Web] Armory doesnt work)
[//]: # (To find server revision type `.server info` command in the game chat.)

**Description**: My main is the only char my bank char has ever sent mail to, yet I get the error "You have reached the in-game cap of unique mail recipients" when trying to mail it things now.

I have bought tons of things off the AH, which would generate mail for others, might that be the cause?

**Server Revision**: 
2718

**Comment by MrOrgmo** [comment]
I've seen others saying that this message also displays when the recipient's mailbox is full. Try opening your main's mail and then sending the rest over.

**Comment by Ravyd** [comment]
> **Description**: My main is the only char my bank char has ever sent mail to, yet I get the error "You have reached the in-game cap of unique mail recipients" when trying to mail it things now.
> 
> I have bought tons of things off the AH, which would generate mail for others, might that be the cause?
> 
> **Server Revision**:
> 2718

typically this arises when that character's mailbox is full

**Comment by Tereneckla** [comment]
rev 3058
