### ISSUE TITLE
Level Requirement Going Going Guano

### ISSUE THREAD

**Issue by Piledriversn** [Atlantiss/NetherwingBugtracker#468]
Master Apothecary Faranell- Going Going Gauno.  
Before the Storm (Patch 2.0.1)
After this patch the Mobs and Bosses changed levels and now for Going Going Guano has a level 30 requirement and it should be around level 26 for the dungeon Razorfen Kraul.

**Comment by Shanghi** [comment]
This should be fixed in revision 2121.
