### ISSUE TITLE
ROGUE [finished cast on stealth target AND gouged-blink]

### ISSUE THREAD

**Issue by Requiemit** [Atlantiss/NetherwingBugtracker#4682]
https://www.youtube.com/watch?v=6kMzBozCSTM&feature=youtu.be

https://www.youtube.com/watch?v=q4YEOiiVQPs&feature=youtu.be

**Comment by bajkorv** [comment]
looks like he blinks right before the gouge to me

**Comment by sadfx** [comment]
Happens with stuns as well (cancels Blink, mage is stunned, Blink on CD)

**Comment by The14me** [comment]
rev.3472 not an issue anymore.Tested with Lightning bolt 
Can be closed.
