### ISSUE TITLE
[Warrior][Spell] Intercept stops short vs moving targets

### ISSUE THREAD

**Issue by Tsaav** [Atlantiss/NetherwingBugtracker#4683]
[//]: # (Enclose links to things related to the bug using http://wowhead.com or any other TBC database.)
[//]: # (You can use screenshot ingame to visual the issue.)
[//]: # (Write your tickets according to the format:)
[//]: # ([Quest][Azuremyst Isle] Red Snapper - Very Tasty!)
[//]: # ([NPC] Magistrix Erona)
[//]: # ([Spell][Mage] Fireball)
[//]: # ([Npc][Drop] Ghostclaw Lynx)
[//]: # ([Web] Armory doesnt work)
[//]: # (To find server revision type `.server info` command in the game chat.)

**Description**:  While casting Intercept on moving players, a lot of times your character will stop short, never reaching the destination

**Current behaviour**: Against moving targets, Intercept does not go the full distance a lot of times.

**Expected behaviour**: Intercept should put you at the target's location when the spell was cast

**Server Revision**:  2718

For some examples: 
https://gfycat.com/HarshQuickHairstreakbutterfly

https://gfycat.com/CreepyInfantileAllensbigearedbat

**Comment by femdead** [comment]
lol owned

**Comment by battleleet2** [comment]
Cataclysm Patch 4.3.0 (2011-11-29): Charge (and related abilities) should now correctly path to a target even if the target moves during the Charge. This change should decrease the likelihood of the warrior Charging to a different location than the target. 

What you describe is a known issue, unfortunately that's how it was in the burning crusade and wrath aswell.

https://www.youtube.com/watch?v=UWeB-regDi0

**Comment by Crusaderz** [comment]
Who cares what bugs retail had back then? Are you insisting that we should implement all of them?

**Comment by Crusaderz** [comment]
LOL. Okey. Blizzard broke vanish in vanilla and couldn't fix it's for like 4 expansions, so let's add random chance for vanish to fail, since it's blizzlike:
https://recked.wordpress.com/2009/10/26/wow-rogue-vanish-fix-errrr-has-vanished/
