### ISSUE TITLE
[Quest] Gnome Improvement

### ISSUE THREAD

**Issue by Javinyx** [Atlantiss/NetherwingBugtracker#4684]
[//]: # (Enclose links to things related to the bug using http://wowhead.com or any other TBC database.)
[//]: # (You can use screenshot ingame to visual the issue.)
[//]: # (Write your tickets according to the format:)
[//]: # ([Quest][Azuremyst Isle] Red Snapper - Very Tasty!)
[//]: # ([NPC] Magistrix Erona)
[//]: # ([Spell][Mage] Fireball)
[//]: # ([Npc][Drop] Ghostclaw Lynx)
[//]: # ([Web] Armory doesnt work)
[//]: # (To find server revision type `.server info` command in the game chat.)

**Description**: 
Hand in a Silver Bar, Moss Agate and Brilliant Gold Ring along with 30 silver for Talvash's Gold Ring.

**Current behaviour**:
When you have all items, you can't hand in quest.

**Expected behaviour**: 
You're supposed to be able to complete quest with items and money in inventory.

**Server Revision**: 
2718

**Comment by czarecoo** [comment]
I had similar issue on Quest:Soothing Turtle Bisque (Horde). Dropping quest and taking it again fixed the problem for me.

**Comment by Javinyx** [comment]
> I had similar issue on Quest:Soothing Turtle Bisque (Horde). Dropping quest and taking it again fixed the problem for me.

That seems to fix it, thank you!

**Comment by The14me** [comment]
That was an issue with most of the quests that need to ''collect'' something. Think it was fixed but can't be sure (no way to reproduce it )
