### ISSUE TITLE
[Shaman] High threat with low to moderate damage

### ISSUE THREAD

**Issue by Leesinga** [Atlantiss/NetherwingBugtracker#4685]
**Description**:  

**Current behaviour**: Elemental and enhacement shamans are generating too much threat, does not match the DPS. The talent spirit weapons seems to not be reducing threat by 30% either. I am pulling agro with only auto attacks mid fight, while we have other classes doing 200-300 more dps with manageable threat.

**Expected behaviour**: Shamans should not cause more agro than other DPS classes, esp. with the talent Spirit Weapons.

**Server Revision**: 2718

**Comment by Tenoutoften** [comment]
Can you show this to be true with threat addons like omen rather than relying on feelings?

**Comment by Nonamesleftffs** [comment]
That's just how ele and enhancement shamans are in tbc, they're one of the heaviest threat classes in WoW history... You kinda need to just start attacking later, or stop attacking if you're about to overaggro.

Welcome to tbc dps shamans! :)

**Comment by ShadyWins** [comment]
Not a bug. I'm playing shaman in outlands now, and they're just like they are supposed to be.
Get used to beg paladins for Salvation and/or use totem to decrease threat regen.. =)

**Comment by The14me** [comment]
Without any proof and details, it's just subjective. All depend of the playstyle, team comp, skill, etc.
