### ISSUE TITLE
Redoubt proccing without a shield being worn, triggering block animation regardless

### ISSUE THREAD

**Issue by staplerx300** [Atlantiss/NetherwingBugtracker#4686]
[//]: # (Enclose links to things related to the bug using http://wowhead.com or any other TBC database.)
[//]: # (You can use screenshot ingame to visual the issue.)
[//]: # (Write your tickets according to the format:)
[//]: # ([Quest][Azuremyst Isle] Red Snapper - Very Tasty!)
[//]: # ([NPC] Magistrix Erona)
[//]: # ([Spell][Mage] Fireball)
[//]: # ([Npc][Drop] Ghostclaw Lynx)
[//]: # ([Web] Armory doesnt work)
[//]: # (To find server revision type `.server info` command in the game chat.)

**Description**: 
Character goes through blocking animation even though I'm using a 2 handed weapon, which results in a very awkward and stupid looking animation where the arm is brought up to block with no shield on.

**Current behaviour**:
https://i.imgur.com/t7wGYcQ.jpg

**Expected behaviour**: 
Not sure, either cause redoubt to not proc unless a shield is worn, or just don't do the blocking animation?

**Server Revision**:

**Comment by Mizers** [comment]
I don't think this is a bug. Redoubt doesn't require a shield to proc. 
https://www.youtube.com/watch?v=VTf8gQhejfE&ab_channel=wangnewton
Also in this video which takes place in retail vanilla you can see him doing the block animation while wielding The Unstoppable Force at 1:41

**Comment by The14me** [comment]
Not a bug as the vid above show it.
