### ISSUE TITLE
[Quest] The Traitor's Destruction

### ISSUE THREAD

**Issue by veekk** [Atlantiss/NetherwingBugtracker#4688]
Quest item [Dar'Khan's Head] still exist after quest competition
<img width="112" alt="image" src="https://user-images.githubusercontent.com/12899687/51879604-d819d800-237c-11e9-95b7-41fe5d8ae9ab.png">
https://www.wowhead.com/quest=9167/the-traitors-destruction

**Comment by Tereneckla** [comment]
fixed
