### ISSUE TITLE
UI glitch makes it look like item has been duped when interacting with gbank

### ISSUE THREAD

**Issue by SteveReiter** [Atlantiss/NetherwingBugtracker#4689]
[//]: # (Enclose links to things related to the bug using http://wowhead.com or any other TBC database.)
[//]: # (You can use screenshot ingame to visual the issue.)
[//]: # (Write your tickets according to the format:)
[//]: # ([Quest][Azuremyst Isle] Red Snapper - Very Tasty!)
[//]: # ([NPC] Magistrix Erona)
[//]: # ([Spell][Mage] Fireball)
[//]: # ([Npc][Drop] Ghostclaw Lynx)
[//]: # ([Web] Armory doesnt work)
[//]: # (To find server revision type `.server info` command in the game chat.)

Edit: Looks like item is not actually duplicated, but it does create a 'fake' item in your inventory that can't be removed until you get rid of the original item.

**Description**: 
As a guild officer I can duplicate items by putting them in the guild back and immediately logging out. When I log back in the item is still in my inventory.

I noticed this by taking a 10 slot bag out of guild bank and replacing it with my old 8 slot bag. I then dropped 2 items into the 10 slot bag and they both disappeared. When I relogged the 10 slot bag was gone but I still have the 8 slot bag on me AND it's in the gbank.

After a few minutes the 10 slot bag and two items I had put in it appeared in my mail.

I still have the duped 8 slot bag, not sure if it will disappear after someone uses it...

**Current behaviour**:
Putting items in the gbank and relogging dupes them (at least for me, guild member tried and it didn't work). I have mostly default UI, only 2 addons that add info to item tooltips.

**Expected behaviour**: 
Items don't get duped in gbank.

**Server Revision**: 
2719

**Comment by SteveReiter** [comment]
Looks like the 'dupe' item can't be vendored or traded or put in my personal bank or the gbank. When I try the icon just greys out. Can't get it out of my inventory until I vendored the original 8 slot bag, then it disappeared after a relog.

**Comment by Manaci** [comment]
Fixed
