### ISSUE TITLE
[Quest][Ghostlands] Forgotten Rituals

### ISSUE THREAD

**Issue by Kaminya** [Atlantiss/NetherwingBugtracker#469]
**Description**: When looting [item] Wavefront Medallion from [gobject] Glistening Mud, the gobject doesn't despawn after single looting. It remains if you loot it again quickly.

**Current behaviour**: [gobject] Glistening Mud doesn't depsawn after a single use.

**Expected behaviour**: [gobject] Glistening Mud should despawn after single use. (immediately)

**Server Revision**: 2045

**Comment by davismj** [comment]
still bugged

**Comment by Tereneckla** [comment]
Fixed
