### ISSUE TITLE
[Quest] Elixir mastery

### ISSUE THREAD

**Issue by Zylvlol** [Atlantiss/NetherwingBugtracker#4695]
**Description**: 
Elixir master quest
**Current behaviour**:
If you have some of the pots in bank once you accept the quest you wont be aviable to complete it without having to abandon the quest and re-do the 10 essences from BM.
**Expected behaviour**: 
Wouldn't matter where you have the items along they are in the bag when you plan to complete the quest.
**Server Revision**: 
2719

**Comment by duzyizly** [comment]
This is working as indended. Sometimes you just need to put elixirs into bank / repick (common wow glitch).
Done this as rev 3377 ptr.
