### ISSUE TITLE
[Profession][Blacksmithing] 'Thunder' Recipe Price not in line with other Weapons learned at 350 Skill

### ISSUE THREAD

**Issue by Optilasgar** [Atlantiss/NetherwingBugtracker#4696]
**Visual Proof of the Problem**:
https://youtu.be/hsyqQv-hzp0

**Description**: 
All of the Weaponsmith Specialization Epic Tier 1 Weapon Recipes learnable at 350 Skill cost 9 Gold to learn with the exception of 'Thunder', the Tier 1 2h Mace, which costs 45g, in line with the 375 Skill Tier 2 & 3 Recipes.

**Current behaviour**:
'Thunder' learnable at 350 Blacksmithing Skill costs 45g to learn

**Expected behaviour**: 
'Thunder' learnable at 350 Blacksmithing Skill should cost 9g, in line with the 5 other Epics weapons learned at that skill level.

**Server Revision**: 
2719 (Hash:c9ae16e84375)

**Comment by teddys** [comment]
bump
https://github.com/Atlantiss/NetherwingBugtracker/issues/4779
