### ISSUE TITLE
Sold item, waiting mail deleted gold

### ISSUE THREAD

**Issue by Hellspawnl** [Atlantiss/NetherwingBugtracker#4697]
**Description**: 
I sold Fel Armament on the Auction house (char name Hellspawnl, Horde). I got the confirmation mail that an item had been sold believe it was 5-7 items. I took out some of the gold but also had mail of the gold waiting after sold item. I deleted those  mails too as I though it was mails where I already collected the gold. Turns out I deleted the mail and  therefore didn't receive the gold. I was told it's no problem I will get he gold and that I would have got a question (Do you want to delete this gold) no such check box came up.
**Current behaviour**:
You can delete gold of sold items for AH without understanding you deleting gold
**Expected behaviour**: 
Should not be possible to delete gold that from items sold of AH during the notification period of time when an item been sold to the gold has been received.
**Server Revision**:

**Comment by Tereneckla** [comment]
rev 3058
