### ISSUE TITLE
Lifetime kills

### ISSUE THREAD

**Issue by Khrondil** [Atlantiss/NetherwingBugtracker#4698]
[//]: # (Enclose links to things related to the bug using http://wowhead.com or any other TBC database.)
[//]: # (You can use screenshot ingame to visual the issue.)
[//]: # (Write your tickets according to the format:)
[//]: # ([Quest][Azuremyst Isle] Red Snapper - Very Tasty!)
[//]: # ([NPC] Magistrix Erona)
[//]: # ([Spell][Mage] Fireball)
[//]: # ([Npc][Drop] Ghostclaw Lynx)
[//]: # ([Web] Armory doesnt work)
[//]: # (To find server revision type `.server info` command in the game chat.)

**Description**: 
Few days ago I was levelling with my girlfriend in Ashenvale and while we were doing that, off course we met some hordes. We killed few of them and in that day we had 14 kills with a total of 40 (lifetime). After a quest or two, when I check again my Honor points I see that instead of 40, now I have 39 kills. And I didn't figure out how's that possible. Same thing happened on my girlfriend's char.
**Current behaviour**:

**Expected behaviour**: 

**Server Revision**:

**Comment by Desst** [comment]
you just payed honor tax

**Comment by Manaci** [comment]
Dead issue
