### ISSUE TITLE
[Spell][Paladin] Divine Shield does not protect from Overload spell in Karazhan

### ISSUE THREAD

**Issue by Mikik3jr** [Atlantiss/NetherwingBugtracker#4699]
[//]: # (Enclose links to things related to the bug using http://wowhead.com or any other TBC database.)
[//]: # (You can use screenshot ingame to visual the issue.)
[//]: # (Write your tickets according to the format:)
[//]: # ([Quest][Azuremyst Isle] Red Snapper - Very Tasty!)
[//]: # ([NPC] Magistrix Erona)
[//]: # ([Spell][Mage] Fireball)
[//]: # ([Npc][Drop] Ghostclaw Lynx)
[//]: # ([Web] Armory doesnt work)
[//]: # (To find server revision type `.server info` command in the game chat.)

**Description**: 
Overload is a debuff on you that deals AOE arcane dmg on you and the dmg increases for every explosion

**Current behaviour**:
![wowscrnshot_012919_001509](https://user-images.githubusercontent.com/43505031/51907327-bc3b2400-23c6-11e9-986a-ec761c8e1567.jpg)

**Expected behaviour**: 
I think I should be able to negate the dmg.

**Server Revision**: 
2719

**Comment by Wolffenstein** [comment]
Nope.
