### ISSUE TITLE
[NPC] Stonetusk Boar

### ISSUE THREAD

**Issue by Mikik3jr** [Atlantiss/NetherwingBugtracker#47]
[//]: # (Enclose links to things related to the bug using http://wowhead.com or any other TBC database.)
[//]: # (You can use screenshot ingame to visual the issue.)
[//]: # (Write your tickets according to the format:)
[//]: # ([Quest][Azuremyst Isle] Red Snapper - Very Tasty!)
[//]: # ([NPC] Magistrix Erona)
[//]: # ([Spell][Mage] Fireball)
[//]: # ([Npc][Drop] Ghostclaw Lynx)
[//]: # ([Web] Armory doesnt work)

**Description**: 
Close to goldshire some Stonetusk Boars can't be attacked.
**Current behaviour**:
Close to goldshire some Stonetusk Boars can't be attacked. When I try to use paladin judgements it says interrupted and I instantly stop attacking when I try to attack them.
![wowscrnshot_092218_230737](https://user-images.githubusercontent.com/43505031/45921830-7e306f80-bebd-11e8-9d26-3938ed54185f.jpg)

**Expected behaviour**: 
I should be able to kill those boars
**Server Revision**:

**Comment by wtRCH** [comment]
Duplicate of https://github.com/Atlantiss/NetherwingBugtracker/issues/39
