### ISSUE TITLE
[NPC][Drop] Keli'dan the Breaker Blood Furnance Heroic

### ISSUE THREAD

**Issue by totaemoeggerli** [Atlantiss/NetherwingBugtracker#4700]
[//]: # (Enclose links to things related to the bug using http://wowhead.com or any other TBC database.)
[//]: # (You can use screenshot ingame to visual the issue.)
[//]: # (Write your tickets according to the format:)
[//]: # ([Quest][Azuremyst Isle] Red Snapper - Very Tasty!)
[//]: # ([NPC] Magistrix Erona)
[//]: # ([Spell][Mage] Fireball)
[//]: # ([Npc][Drop] Ghostclaw Lynx)
[//]: # ([Web] Armory doesnt work)
[//]: # (To find server revision type `.server info` command in the game chat.)

**Description**: 
[Keli'dan the Breaker](https://www.wowhead.com/npc=17377/kelidan-the-breaker)  Blood Furnance Heroic

**Current behaviour**:
Endboss drops 1 blue item only.

**Expected behaviour**: 
Endboss should drop 2 blue items just like every other endboss does.

**Server Revision**: 2719

**Comment by Zarant** [comment]
Drop tables from final bosses in heroic mode are super inconsistent right now, i've seen bosses dropping 2 blue items, some bosses dropping only 1 blue item and i've seen bosses dropping nothing but a primal nether

**Comment by Drayo** [comment]
This is kinda urgent because it's not like players can just put in more time to make up for it on HC.

Also only getting one Item is super demoralizing, so in time people will just start to avoid those dungeons.

**Comment by Wolffenstein** [comment]
Can I get a list of all bosses with incorrect drop counts? It would make it a lot easier.

**Comment by totaemoeggerli** [comment]
here is another issue with other bosses listed: https://github.com/Atlantiss/NetherwingBugtracker/issues/3438
Keli'dan is not on that list, probably because no one else does BF on HC

**Comment by Drayo** [comment]
Was fixed ages ago, can be closed.
