### ISSUE TITLE
[Quest][Mage] Items of Power

### ISSUE THREAD

**Issue by maxturtlesc2** [Atlantiss/NetherwingBugtracker#4701]
[//]: # (Enclose links to things related to the bug using http://wowhead.com or any other TBC database.)
[//]: # (You can use screenshot ingame to visual the issue.)
[//]: # (Write your tickets according to the format:)
[//]: # ([Quest][Azuremyst Isle] Red Snapper - Very Tasty!)
[//]: # ([NPC] Magistrix Erona)
[//]: # ([Spell][Mage] Fireball)
[//]: # ([Npc][Drop] Ghostclaw Lynx)
[//]: # ([Web] Armory doesnt work)
[//]: # (To find server revision type `.server info` command in the game chat.)

**Description**: 
"Get a bolt charged bramble. To get one of those, gather 10 witherbark totem sticks from the witherbark trolls of the arathi highlands. Bring the sticks to the circle of outer binding [...] Place the sticks on the center stone in the circle and wait for lightning to strike it. When it does, the bolt charged bramble will be formed."
**Current behaviour**:
After getting the 10 sticks I went to the circle of outer binding, I clicked on the 10 sticks in my inventory, which made it disappear. I never got the bolt charged bramble like it should.
**Expected behaviour**: 
You should be able to obtain the bolt charged bramble.
**Server Revision**:

**Comment by bimbear** [comment]
After using these items game object should appear above the stone, u should be able to loot quest item.
Worked for me not so long ago.

**Comment by maxturtlesc2** [comment]
I tried a 2nd time and it worked this time. 1st time there wasn't even a cast bar that appeared. Really weird.

**Comment by devo6969** [comment]
Could not recreate on the PTR. Seems fixed
