### ISSUE TITLE
[Engineering][Trinket] Gnomish Battle Chicken Only has 26 Hp.

### ISSUE THREAD

**Issue by Ethugx** [Atlantiss/NetherwingBugtracker#4702]
https://cdn.discordapp.com/attachments/395776706780332032/539824496132096000/WoWScrnShot_012919_143355.jpg

**Description**: 
Gnomish Battle Chicken Only has 26 Hp.
**Current behaviour**:
Hyper Low hp
**Expected behaviour**: 
Correct Value Hp
**Server Revision**
2719

**Comment by Ashfall7x** [comment]
Not only this. It does not attack, let alone giving the buff.

**Comment by Ethugx** [comment]
It aoe taunts, I've gotten Squark for my party (the 5% melee haste buff), he fights also just has so low hp he dies first hit. My 200 engi mechanical dragonling has 1.2k hp or so.

**Comment by Ethugx** [comment]
Well i think he fights i've never seen a hit go off since he dies so quick, appears to work tho.

**Comment by Ethugx** [comment]
Also deathray is too consistent, always 100-125 ticks and 500 hits. tried alot and its never different.

**Comment by Unrelented** [comment]
Can we get a bump on Engineering? <3

**Comment by Evolvee** [comment]
https://github.com/Atlantiss/NetherwingBugtracker/issues/6265
