### ISSUE TITLE
[Boss][Spell][Karazhan](Shade of Aran) Broken, in so many ways

### ISSUE THREAD

**Issue by Anonyxx** [Atlantiss/NetherwingBugtracker#4704]
[//]: # (Enclose links to things related to the bug using http://wowhead.com or any other TBC database.)
[//]: # (You can use screenshot ingame to visual the issue.)
[//]: # (Write your tickets according to the format:)
[//]: # ([Quest][Azuremyst Isle] Red Snapper - Very Tasty!)
[//]: # ([NPC] Magistrix Erona)
[//]: # ([Spell][Mage] Fireball)
[//]: # ([Npc][Drop] Ghostclaw Lynx)
[//]: # ([Web] Armory doesnt work)
[//]: # (To find server revision type `.server info` command in the game chat.)

**Description**: 

The Shade of Aran fight in Karazhan is very very broken and needs to be fixed as an urgent priority. It is a mandatory boss and blocks passage into upper Karazhan.

Currently there are several core mechanical bugs with this boss:

1) Dragon's breath should not be immediately cast after any of
i) Blizzard
ii) Arcane Explosion
iii) Flame Wreath

Currently it is possible to get Arcane Explosion and then right after a Dragon's Breath. This means the timer of Dragon's breath is incorrectly scripted. 

This is how it should look like:
https://www.youtube.com/watch?v=IGBRabo179o

Note how Dragon's Breath is not used in a 10s window of either of the three spells listed above.

2) Flame Wreath is plain and simply broken. It triggers even when there is no movement in the raid. I won't go into detail about what this looks like because there is another thread on this here:

[[Boss][Spell][Karazhan](Shade of Aran) Flame Wreath](https://github.com/Atlantiss/NetherwingBugtracker/issues/4626)

Pets should not cause Flame Wreath, but even when all pets are dismissed in a raid, Flame Wreath still procs. Combat logs show damage from "No-one"

Here's an example of what a raid that doesn't move and doesn't use pets look like:

https://www.youtube.com/watch?v=S4-HbwAIMVc

Triggers randomly for absolutely no good reason.

3) Arcane missiles do not tick correctly. Currently, he does not cast the first initial set of missiles on his target.

4) Elementals should attack the nearest targets to them and should not share an aggro table either with eachother or with Aran. Currently when they spawn, they usually all one shot a healer or dps, depending on who does a high aggro ability in the window of time right after they spawn. Again, this is clearly visible in this video:

https://www.youtube.com/watch?v=IGBRabo179o

5) Aran sometimes spawns multiple sets of elementals. He should spawn 4 elementals at 40% and not spawn any more elementals after that. Currently, he regularly spawns multiple sets of elementals at intervals from 0% to 40%.

**Current behaviour**:

Shade of Aran is a messy and broken fight that needs to be an urgent priority of the developers. 

**Expected behaviour**: 

1) Dragon's Breath should not be used right after or before Blizzard, Arcane Explosion and/or Flame Wreath.

2) Flame Wreath should only trigger when someone crosses the flame threshold - not randomly as is happening now. 

3) The first set of Arcane Missiles should tick on cast.

4) Elementals should target the person closest to them and not instantly all aggro on the same target.

5) Only one set of elementals should be spawned per fight.

**Server Revision**: 
2719

**Comment by Easyfraggy** [comment]
Only report 1 spell / Issue at a time please

Flame wreath is already reported here: https://github.com/Atlantiss/NetherwingBugtracker/issues/4704
Dragon's breath is not tied to any of the abilities you talk about it's tied to Flame Wreath only. All timers are random intervals. 

Would need a video or something to show dragons breath going off after arcane explosion cus this worked fine during beta - it always went off before a new special - e.g. Blizzard/Arcane Explosion/Flame Wreath. The danger in lowering the timer is that it would go off while flame wreath is still up possibly causing people to explode. Also should be reported as a seperate issue.

Arcane Missiles should be reported in a seperate issue.

Elementals have normal threat tables so whats happening is most likely that your healer lands a heal right as they spawn. It's a good idea for healers to not stand in the middle of the room when they do - as their frost bolt obeys LOS and have a max range. Doesn't sound like a bug to me - they have regular threat tables. In fact in the video you link - the 3 visible elementals all target the same shaman that just casted a heal on their first water bolt (one gets banished before ending cast).

**Comment by Drayo** [comment]
> Nobody moves over the flame wreath; its the shaman player who ankhs and moves that causes the flame wreath but in this case, the shaman did not move over the flame wreath and therefore flame wreath should not have been triggered. Also see 24:29 to 25:04 - nobody moves apart from the elementals and yet flame wreath is triggered. Hostile pets should not cause flame wreath!

Flame Wreath triggers on ANY movement, not only the crossing of the visual ring. This is 2.0 and EVERYTHING moving triggers Flame Wreath, even pets. At 24:29 to 25:04, did the warlock have Nether Protection? If you become immune to fire Spells you might trigger Flame Wreath.

> A second set of elementals is spawned after the first set - this should also not happen. This happens multiple times throughout the video I just linked. 25:00 to 25:10 shows a perfect example of this. Clearly the Netherwing cooldown on Elementals is too short.

There is no Cooldown on the Elementals, it happens once per fight on 40%.

What happened here is that Aran reset for a millisecond and thus summoned new adds because he was under 40% HP, this is a bug that has been reported here https://github.com/Atlantiss/NetherwingBugtracker/issues/3767, it was supposed to be fixed, seems to have resurfaced.

It happens when a player gets knocked up super high in the air due to exploding, might be tied to the Boss leash, but idk.


https://www.youtube.com/watch?v=gcA6y7sxKcA and everything will be okay. ;P

**Comment by Anonyxx** [comment]
> Flame Wreath triggers on ANY movement, not only the crossing of the visual ring. This is 2.0 and EVERYTHING moving triggers Flame Wreath, even pets. At 24:29 to 25:04, did the warlock have Nether Protection? If you become immune to fire Spells you might trigger Flame Wreath.

This is incorrect. This is a comment from WoWhead on patch 2.0.7. As you can see, it specifically mentions crossing of the ring as the trigger for flame wreath.

_"This spell targets people in the raid and casts a circle around them. The area in the cicle has a debuff that if someone losses or gains this debuff it will kill your raid or bring all health very very low. So, Paladins, your Divine Sheild [sic] will make you immune to the debuff. so if you see him start to cast it and your sheild is up, CLICK IT OFF, and if your in the circle do not pop your bubble."_

It is only losing or gaining the debuff that causes flame wreath to trigger. I.e. if you are outside flame wreath, you can move so long as you do not cross the flame threshold. Flame wreath should also trigger instantly on the threshold being crossed - not at the end of the duration of the debuff as is happening currently.

I understand that pets can and should trigger flame wreath - but not hostile pets (i.e. Aran's own elementals!).

**Comment by Drayo** [comment]
> I understand that pets can and should trigger flame wreath - but not hostile pets (i.e. Aran's own elementals!).

If this is happening it would certainly explain why for some groups the explosion triggers seemingly randomly.

> This is incorrect. This is a comment from WoWhead on patch 2.0.7. As you can see, it specifically mentions crossing of the ring as the trigger for flame wreath.

Yeah that's true, if it currently works on any movement it would be incorrect then.
In general, flame wreath is very frustrating atm, kinda the wrong thing to spend time on when it comes to pre-nerf abilities imo  (regarding pets especially).

**Comment by Easyfraggy** [comment]
Please move to the correct post - spreading the information about flame wreath in several posts is bad.

https://github.com/Atlantiss/NetherwingBugtracker/issues/4626

As I show in one of my gifs - moving around inside flame wreath works perfectly fine on NW.

The issue is again - Flame wreath sometimes blows up without reason on application/removal(timeout).
