### ISSUE TITLE
[Item] items disappearing from player inventory

### ISSUE THREAD

**Issue by Vergos** [Atlantiss/NetherwingBugtracker#4705]
Accross last few days I had problems with items "disappearing" temporary from my (player) inventory:
1) on 26/01 - missing https://www.wowhead.com/item=2901/mining-pick - noticed via mining dialog;
bought second one, on 27/01 found out I have 2 in inventory

2) on 27/01 - missing https://www.wowhead.com/item=20815/jewelers-kit - noticed via crafting dialog;
bought second one, on 27/01 evening found out I have 2 in inventory

3) on 28/01 - missing https://www.wowhead.com/item=5176/fire-totem - raised a ticket in-game, on 29/01 logged on and have all totems available.

In-game nick: Vergos

EDIT:
29/01 - seems to be connected with crashes
1) was missing stack of https://www.wowhead.com/item=13928/grilled-squid
2) crash (circa 23:00), squids are back, missing mining pick again
3) crash (circa 23:10), mininng pick is back, missing https://www.wowhead.com/item=5177/water-totem

**Expected behaviour**: items not disappearing? :)

**Server Revision**: 2719

**Comment by Manaci** [comment]
Rollback shenanigans
