### ISSUE TITLE
Ignore Doesn't Work

### ISSUE THREAD

**Issue by femdead** [Atlantiss/NetherwingBugtracker#4706]
Still able to get whispers from spammers after they are placed on ignore list
![image](https://user-images.githubusercontent.com/29705985/51933034-57002680-23f8-11e9-9d33-4c9fbaa740a0.png)

marked as fixed in #4049 but it isn't

**Comment by rychersky** [comment]
Still isn't working.

**Comment by devo6969** [comment]
Seems fine, figured it might of had something to do with the icons but no dice
