### ISSUE TITLE
[Netherstorm] [Quest] Battle-Mage Dathric

### ISSUE THREAD

**Issue by Shinizaa** [Atlantiss/NetherwingBugtracker#4707]
**Current behaviour**: When you use Dathric's Blade near the weapon rack he spawns in the door but does not walk towards the weapon rack and does complete.

**Expected behaviour**: He is supposed to rp and walk towards weapon rack and it should complete the quest.

**Server Revision**: 2719

I tried doing this quest twice but it does not complete

**Comment by tcberk12** [comment]
Worked fine for me

**Comment by Mewmewww** [comment]
Worked fine for me as well.

**Comment by Evolvee** [comment]
reopen, if it still doesnt work
