### ISSUE TITLE
Paladin talent 3/3 Sanctified Seals, still able to dispel it

### ISSUE THREAD

**Issue by TobiasCodeNull** [Atlantiss/NetherwingBugtracker#4708]
**Description**: Was fighting a shaman and used seal of wisdom. With 3/3 Sanctified Seals talent is should be 100% dispell-proof. 

**Current behaviour**: The shaman was able to purge the seal. Causing me to loose more mana.

**Expected behaviour**: The shaman wouldn't be able to dispell it cause of the talent.

**Server Revision**: 2719 Hash c9ae16e84375

**Comment by Wolffenstein** [comment]
Shouldn't happen anymore as of rev 2735.
