### ISSUE TITLE
Formula: Enchant Shield - Intellect from Aged Dalaran Wizard in Old Hillsbrad Foothills

### ISSUE THREAD

**Issue by fantom8** [Atlantiss/NetherwingBugtracker#4709]
**Description**: 
The vendor inside Old Hillsbrad Foothills has broken and you can't open his merchant frame to buy the enchant pattern.

**Current behaviour**:
When you right click on the NPC nothing happens. This is the case on both normal and heroic mode.

**Expected behaviour**: 
The NPC should open a merchant frame which allows you to buy the Enchant Shield - Intellect formula. This should be available on both normal and heroic modes as per comments:

https://www.wowhead.com/npc=18664/aged-dalaran-wizard#comments

https://www.wowhead.com/item=22539/formula-enchant-shield-intellect#comments

https://www.wowhead.com/spell=27945/intellect#comments

>defektunge on 2007/02/04 (Patch 2.0.6)
>Sold by a vendor in Southshore in Old Hillsbrad, yes. You don't need to actually fight anything or do anything to access the vendor, so it's very soloable at any level, assuming you can get into CoT.

You can't do heroics before 70 so it's evident that you're supposed to be able to buy it on normal mode.

**Server Revision**: 
2719

**Comment by liek0r** [comment]
I have been able to buy the pattern. Are you horde?

**Comment by drchristie** [comment]
worked fine for me in heroic on alliance

**Comment by distilled890** [comment]
tried to buy pattern in heroic and normal, when you talk to him nothing happens

**Comment by Manaci** [comment]
Fixed
