### ISSUE TITLE
[NPC=15274] Mana Wyrm wanders underground

### ISSUE THREAD

**Issue by Terefinz** [Atlantiss/NetherwingBugtracker#471]
**Description**: Mana wyrm ([NPC=15274]) in Sunstrider Isle wander under the ground as they path around. I noticed this occur in the coords 37.9 X and 22.6 Y in Sunstrider Isle.

**Current behaviour**: ^

**Expected behaviour**: Should not go underground when pathing around

**Server Revision**:  2045

![wowscrnshot_092418_211407](https://user-images.githubusercontent.com/43561224/45991132-b7451d00-c040-11e8-911b-3c8fe1ca3391.jpg)

**Comment by aresbrutus** [comment]
Thank you for your report. For further issues that are npc related, please use the command .npc info while having the creature selected before making a screenshot. That way we know exactly which mob has the issue.

**Comment by Terefinz** [comment]
Hi, after playing a little more I noticed this happens in general with all the mobs in sunstrider isle (Mana Wyrms and Lynxes alike), particularly when pulling them up any staircase when standing on top. As they run up any staircase (like the one pictured in the screenshot) they always clip through the floor.

**Comment by Terefinz** [comment]
Here is a video of multiple examples of this happening. Is this client side?

https://streamable.com/9n68q

**Comment by Tereneckla** [comment]
Fixed
