### ISSUE TITLE
[Quest] A Little Help From My Friends

### ISSUE THREAD

**Issue by OMEGALULW** [Atlantiss/NetherwingBugtracker#4711]
**Current behaviour**: Brought Ringo to the camp but nothing happened, then I was killed and he disappeared preventing me from completing the quest.

**Expected behaviour**: Quest should get completed when you complete it duh

**Server Revision**: 2719

UPDATE: The bug does most likely have to do with me having to abandon the quest and re-take it since I was ganked while doing it. There must be an issue with these timed escorts where you can't complete it until the timer from when you first accepted it runs out (even though you're given a new timer when you start it over). Ignore the idiots saying that it works 100% just because it worked for them. It worked for me the 3rd time I did it as well.

**Comment by battleleet2** [comment]
Works 100% fine.

You probably got killed before going into "chat-space" with npc.

**Comment by sadfx** [comment]
> Works 100% fine.
> 
> You probably got killed before going into "chat-space" with npc.

No it doesn't., I was literally right next to the NPC. I died after running around the NPC for like 1-2 min. Stop saying that it works 100% fine when it clearly didn't for me.

**Comment by Balanarr** [comment]
Also worked perfectly fine for me. Got him near the npc in the camp and it completed without any problems. Maybe he fainted right before you got him to the completing spot?

**Comment by sadfx** [comment]
> Also worked perfectly fine for me. Got him near the npc in the camp and it completed without any problems. Maybe he fainted right before you got him to the completing spot?

No. I went to the NPC and nothing happened and I even waited for him to faint so I could wake him up again to see if that would work but that didn't work either. The quest was broken.

**Comment by drchristie** [comment]
works fine. not a bug. you didnt bring him close enough to his girlfriend.  pvp on a pvp server etc

**Comment by sadfx** [comment]
> works fine. not a bug. you didnt bring him close enough to his girlfriend. pvp on a pvp server etc

No, it was a bug but I think I know what it is.

**Comment by Manaci** [comment]
Dead issue
