### ISSUE TITLE
[NPC] Fel Corruptor and Felsworn Daggermaw

### ISSUE THREAD

**Issue by rychersky** [Atlantiss/NetherwingBugtracker#4712]
**Current behaviour**: Fel Corruptors are standing still in one position (for each spawn point). Felsworn Daggermaws are buffing themselves (and refreshing instantly as soon as it falls off) with Mad Seduced while standing at their spawn points.

**Expected behaviour**: Fel Corruptors patrol around the area and buff individual Felsworn Daggermaws (and I believe Felsworn Scalewings).

**Server Revision**: 2719

**Comment by sleepdaddy** [comment]
Confirmed. Still an issue.

**Comment by devo6969** [comment]
This seems fixed.
