### ISSUE TITLE
View Distance

### ISSUE THREAD

**Issue by tpi0** [Atlantiss/NetherwingBugtracker#4713]
[//]: # (Enclose links to things related to the bug using http://wowhead.com or any other TBC database.)
[//]: # (You can use screenshot ingame to visual the issue.)
[//]: # (Write your tickets according to the format:)
[//]: # ([Quest][Azuremyst Isle] Red Snapper - Very Tasty!)
[//]: # ([NPC] Magistrix Erona)
[//]: # ([Spell][Mage] Fireball)
[//]: # ([Npc][Drop] Ghostclaw Lynx)
[//]: # ([Web] Armory doesnt work)
[//]: # (To find server revision type `.server info` command in the game chat.)

**Description**: 
Ninburi and myself play in the same room however she can see further than I can.  She is consistently seeing enemies before I can.  My computer has max all settings for video
**Current behaviour**:
see above
**Expected behaviour**: 
I would expect to see enemies at the same distance Ninburi can
**Server Revision**: 
2719

**Comment by Tenoutoften** [comment]
Are you equally zoomed out from the characters you play?

**Comment by tpi0** [comment]
Yeah we both are set for max zoom at 50.  What I found weird was last night
once we made it to hellfire I generally could see the fel reaver before her
but all normal sized mobs she sees first

**Comment by drchristie** [comment]
kind of vague and not really a bug since theres probably something on your end
