### ISSUE TITLE
[Item] [Vanilla] Ace of Beasts

### ISSUE THREAD

**Issue by Drayo** [Atlantiss/NetherwingBugtracker#4714]
[//]: # (Enclose links to things related to the bug using http://wowhead.com or any other TBC database.)
[//]: # (You can use screenshot ingame to visual the issue.)
[//]: # (Write your tickets according to the format:)
[//]: # ([Quest][Azuremyst Isle] Red Snapper - Very Tasty!)
[//]: # ([NPC] Magistrix Erona)
[//]: # ([Spell][Mage] Fireball)
[//]: # ([Npc][Drop] Ghostclaw Lynx)
[//]: # ([Web] Armory doesnt work)
[//]: # (To find server revision type `.server info` command in the game chat.)

**Description**:  

This Items Drops from The Beast in Upper Blackrock Spire. UBRS seems to be locked however.
While I completely understand locking old "raids" and possibly other old world content, I think in this case (and maybe a few others) it really has a massive impact on gameplay.

[Darkmoon Card: Blue Dragon] is one of the Priests Core Items in early TBC, not being able to complete the Deck is very annoying.

It was said that this would be fixed prior to release, either by making UBRS accessible or by making the Card drop somewhere else.

**Someone further down proposed to let it drop from Halcyon in LBRS, this would still require some effort from the players and no real additional work since LBRS is already open.** Additionally, If someone would put any effort in scripting UBRS, it would mostly be wasted because players would simply do stealth runs anyway.

**Server Revision**:  2723

**Comment by towneh** [comment]
Confirming that current state of UBRS is that possessing Seal of Ascension does not influence the ability to interact with the door in the black rock spire instance.

**Comment by Camarila** [comment]
I'd rather lvl 70 raids and dungeons be working with no problems, than the devs spending a month to code BlackRock so you could get your 1 item.

**Comment by Drayo** [comment]
Why the fuck would they script the entire dungeon? Just make it do-able/not crash the server ... no one goes in there for the "experience".

I also suggested that they could just let it drop of some random other mob, ANYWHERE really. 

> A month to code backrock.

Fuck you are retarded...

**Comment by towneh** [comment]
Perhaps give it the same drop rate chance to drop from Halycon in LBRS. There's still a level of effort involved to reach him and it's in keeping with the theme.

**Comment by drchristie** [comment]
>bug report

whats the bug? 

Farm LBRS key to get into UBRS. farm beast for ace. And no its not a early game item for priests, its mid t5-t6 BIS for spirit healers, priest+druid. please see EJ archives on the values w/ int-based spirit regen and changes from 2.0 and 2.4.3 in rdruid lifebloom thread

stuff like this is why gummy just locked it all

**Comment by Drayo** [comment]
> whats the bug?
> Farm LBRS key to get into UBRS.  farm beast for ace.

Go do it and see what happens, if you don't want/need to, stop spewing crap. If you can't be bothered to read, keep your useless input for yourself.

> And no its not a early game item for priests, its mid t5-t6 BIS for spirit healers, priest+druid.

You don't farm this stuff when you are in the middle of T5, you do it now, so you actually have it when you need it. No one gives a shit about T4, so in about 2-3 Weeks is will be relevant.

This isn't gummys, so who the fuck cares what happened on his server?

**Comment by Picajzla** [comment]
bump. Nothing  said about this still. I also don't expect UBRS to be scripted, i don't care if it's open or not either. Whoever wants to experience vanilla content can go to any of the vanilla servers,which are plenty and are well scripted aswell. But alternative for getting ace of beasts has to exist. As Towneh recommended, giving Halycon the same droprate on the item as Beast had is an option, or  make it a world drop like all the other parts.  Just imagine the backlash if dragonspine trophy didn't drop on gruul or Illidan didn't drop skull of gul'dan :D

**Comment by MiekZer** [comment]
El famoso 3years development

**Comment by Kaini27** [comment]
bump

**Comment by ibogdandx** [comment]
I mean... Can the devs consider this github post ? The trinket is literally godlike for healers . No one expects ubrs to be scripted properly but at least give us a chance to obtain this. If this TBC server was a progressive one  from Vanilla everyone would have it. 
Or just make it drop somewhere else... make it a random drop from a TBC dungeon idk but make it accesible to players in one way or another.

**Comment by Shakawkawkaw** [comment]
@wolfenstein I feel like this should be adressed, it's not that big of a deal to make the door openable, but it feels clumsy to not have access to the item, as its supposed to be. 
LBRS is open too and it is literally the same zone.

**Comment by Metatron80** [comment]
bump

make it possible to get our BiS trinket!

**Comment by YhwachPogchampiomn** [comment]
Atleast Put the Beast somewhere in LBRS as compensation you sick fucks

**Comment by Easyfraggy** [comment]
https://gfycat.com/singlekindheartedhippopotamus seems fine to me?

**Comment by Realnairoby** [comment]
any news?

**Comment by Valmere** [comment]
![image](https://user-images.githubusercontent.com/2462756/53683989-a70f2900-3cd5-11e9-92e7-876800bb0e24.png)
UBRS rework in progress, hold on to your butts

**Comment by Shakawkawkaw** [comment]
instead of a screenshot you _could_ have posted the link here.

thanks for sharing, you tried

**Comment by towneh** [comment]
He took a screenshot because that "link" is concerning a Dire Maul fix and has nothing to do with UBRS. Please can you cease with the one-upmanship on Github.

**Comment by Drayo** [comment]
This can be closed, yay. Thanks @Evolvee
