### ISSUE TITLE
Healing Aggro on Multiple Mobs

### ISSUE THREAD

**Issue by femdead** [Atlantiss/NetherwingBugtracker#4715]
Doesn't seem like it's getting split between mobs, aoe tanking 15+ skeleton mobs with demo shout and one heal pulls 

Expected behaviour: Healing aggro evenly split between all mobs, instead of full aggro assigned to every mob

**Comment by Tenoutoften** [comment]
This is an issue with demo shout and not healing agro. Demo shout is causing zero threat on this server.

**Comment by Drayo** [comment]
Just tested this:

- Healing aggro get properly split among targets.

- Demo/Battle Shout cause 44 and 55 threat respectively.

Everything works as it should, can be closed.
