### ISSUE TITLE
Rep. Aldor-Scryers

### ISSUE THREAD

**Issue by Diebythegun1** [Atlantiss/NetherwingBugtracker#4716]
я взял репутацию с Алдорами, и выполнил какой то квест в нижнем Городе, после этого у меня репутация с Aldor - Scryers Враждебное. Что делать ?
 I have Aldor and Scryers bad reputation, i complite 1 q Lower City and it happened. What now ?

**Comment by Diebythegun1** [comment]
Nick Barabulka

**Comment by powerlol** [comment]
https://www.wowhead.com/forums&topic=18526#p161160

complete one of those quest to gain reputation for one and lower the reputation for the other. 
Isn't a bug just low IQ

**Comment by Diebythegun1** [comment]
I have already completed a quest to choose a faction. After that, I did some kind of quest in the lower City and I was added a reputation for the opposite faction and lowered from the one that I was already

**Comment by powerlol** [comment]
Click on the link I provided and read comments; there are 2 NPC names which provide you quests to complete (repeatable) and by farming and bringing back mats to them you'll be able to gain reputation for the one you want.

**Comment by Diebythegun1** [comment]
I'll go try. thanks for the help

**Comment by Manaci** [comment]
Not a bug
