### ISSUE TITLE
[Quest][Alchemy] Master of Elixirs

### ISSUE THREAD

**Issue by Blorbish** [Atlantiss/NetherwingBugtracker#4717]
[//]: # (Enclose links to things related to the bug using http://wowhead.com or any other TBC database.)
[//]: # (You can use screenshot ingame to visual the issue.)
[//]: # (Write your tickets according to the format:)
[//]: # ([Quest][Azuremyst Isle] Red Snapper - Very Tasty!)
[//]: # ([NPC] Magistrix Erona)
[//]: # ([Spell][Mage] Fireball)
[//]: # ([Npc][Drop] Ghostclaw Lynx)
[//]: # ([Web] Armory doesnt work)
[//]: # (To find server revision type `.server info` command in the game chat.)

**Description**: 
After have been Transmutation Master I wanted to swap to Elixir Master, I payed my 150g to remove it which seem to have worked. I went to Honor Hold to grab the Master of Elixirs quest, picked it up and it told me to go to Shattrath and talk to Lorokeem. I turned in the quest and when I was about to receive the follow-up quest (to gather elixirs and essence from BM) it told me I wasn't eligible for the follow-up quest and he won't give me the next part of the quest.

_Might be a problem changing alchemy specialization and not just this quest._

**Current behaviour**:
Lorokeem won't give me the second part of Master of Elixirs quest.

**Expected behaviour**: 
Lorokeem should be able to teach me Elixir Master (according to other players).

**Server Revision**: 
2719

**Comment by Drayo** [comment]
Not 100% how it is in 2.0, but normally just can just unlearn it at the guy you learned it from for 150G and then talk to the specialization master of your choice and learn the new one for free.

There should not be a quest you have to do. But like I said, 2.0 could be different.

**Comment by Blorbish** [comment]
Could be, but either way he won't give me anything at all.

**Comment by Blorbish** [comment]
Isn't Lorokeem the elixir specialist though?

**Comment by Blorbish** [comment]
I think the bug might have been by after dropping the quest going to pick-up the elixir master quest and turning it in seems to have given me back my transmutation master. I went and spent 150g more to unlearn it again and that seems to have fixed it, could now grab Elixir Master at Lorokeem.
