### ISSUE TITLE
[Quest] Kim'jael Indeed! Box Bug

### ISSUE THREAD

**Issue by OMEGALULW** [Atlantiss/NetherwingBugtracker#4719]
**Current behaviour**: Kim'jael's Equipment boxes can be empty without despawning (they do despawn if you loot it but you can find ones that are already empty)

**Expected behaviour**: Boxes shouldn't ever be empty when opened

**Server Revision**: 2719

Theory: Perhaps the box contains an item you already have and thus can't see? It shouldn't be like that.

**Comment by duzyizly** [comment]
done the quest with 6 boxes open. None of them was empty.
ptr 3404

![WoWScrnShot_062320_225432](https://user-images.githubusercontent.com/43931626/85461315-86db3b80-b5a4-11ea-8fd2-2d2a8b0fab17.jpg)
