### ISSUE TITLE
Kolkar Pack Runner & Packhound don't aggro together

### ISSUE THREAD

**Issue by Notmittz** [Atlantiss/NetherwingBugtracker#472]
**Description**: 
When you attack Kolkar Pack Runner, there pet Kolkar Packhound, does not attack as well.  When you attack Kolkar Packhound, the centaur doesn't attack as well.  They do not aggro together, but separately.

**Current behaviour**:
They are acting like two separate mobs that stand near each other instead of a hunter and pet. 

**Expected behaviour**: 
They are supposed to act like a hunter and pet, if you aggro one you aggro both.

**Comment by eryczek1615** [comment]
Kolkar Pack Runner - https://www.wowhead.com/npc=3274
Kolkar Packhound - https://www.wowhead.com/npc=4316
They should also patrolling together

**Comment by Evolvee** [comment]
fixed in rev 2498
