### ISSUE TITLE
[dungeon] [loot] [heroic] Dungeon End bosses on heroic does not have guaranteed 2 drops.

### ISSUE THREAD

**Issue by knasen88** [Atlantiss/NetherwingBugtracker#4720]
[//]: # (Enclose links to things related to the bug using http://wowhead.com or any other TBC database.)
[//]: # (You can use screenshot ingame to visual the issue.)
[//]: # (Write your tickets according to the format:)
[//]: # ([Quest][Azuremyst Isle] Red Snapper - Very Tasty!)
[//]: # ([NPC] Magistrix Erona)
[//]: # ([Spell][Mage] Fireball)
[//]: # ([Npc][Drop] Ghostclaw Lynx)
[//]: # ([Web] Armory doesnt work)
[//]: # (To find server revision type `.server info` command in the game chat.)

**Description**: 
Except for the following bosses I ASSUME all the non-fixed suffer the same issue: The 2 item drops are not guaranteed.
I assume it's supposed to work like 2 drops assured, 1 can be epic or simply 2 blues
**Current behaviour**:
completely RNG aside from the already fixed bosses(can drop zero items)
https://media.discordapp.net/attachments/400290777932103682/540220769104560135/unknown.png
all except:
Murmur
Epoch Hunter
The Black Stalker
Warlord Kallithresh
Kargath Bladefist
Pathalon the Calculator
**Expected behaviour**: 
2 guaranteed drops, 
**Server Revision**: 
2719

**Comment by Tenoutoften** [comment]
https://github.com/Atlantiss/NetherwingBugtracker/issues/3438

**Comment by knasen88** [comment]
they seemed to miss that and only fix the ones you mentioned, this is for all other bosses

**Comment by Tenoutoften** [comment]
Yeah, that's what I told them back then, they just didn't listen

**Comment by Imbaslap** [comment]
last boss in OHF doesnt drop any items.

**Comment by Wolffenstein** [comment]
Fixed in rev 2751.

**Comment by knasen88** [comment]
@Shanksalot it's not been pushed to live yet, 2 more revisions to go. currently at 2749
