### ISSUE TITLE
[Quest] Muigin and Larion Drop Rate

### ISSUE THREAD

**Issue by OMEGALULW** [Atlantiss/NetherwingBugtracker#4721]
**Current behaviour**: 50+ kills only 6 petals, does for sure seem off to me. Some other quests have had this issue where they shouldn't be quite be 100% but they're instead around 10-20%

I think the difference in drop rate between the different types of lashers might be off.

**Expected behaviour**: Definitely not supposed to be this rare

**Server Revision**: 2719

**Comment by devo6969** [comment]
The drop rate says 30% on WoWhead classic but there is a lot of comment stating this is wrong from Classic and Vanilla/TBC. This is suppose to be an awful quest.

https://classic.wowhead.com/item=11316/bloodpetal#comments
"I have spent over 4 hours on the bloodpetal quest over 3 days and the drop rate is more like 10%. After 4 hours only 9 out of 15 collected. I am actually finding this to be a problem with all the quests in Un'goro where the drop rates are crazy low so a simple collect x takes multiple days to complete."

https://classic.wowhead.com/quest=4141/muigin-and-larion#comments
"Tedious with a capital "T"! I slugged away at this quest off-and-on for over a week. The only critters that I found much success with were the Bloodpetal Lashers. They had about a 25% drop rate and that was the best I could find. "

"25% is a little high. I've killed 45 now and I only have six. In addition, whenever you tangle with one, you get poison'ed for 30 seconds. Enter this quest chain with a lot of patience."
