### ISSUE TITLE
[Critical][Guild][Bank][Item][Inventory] More item disappearing issue, this time with intact log and not connected to crash

### ISSUE THREAD

**Issue by Haipethdev** [Atlantiss/NetherwingBugtracker#4722]
[//]: # (Enclose links to things related to the bug using http://wowhead.com or any other TBC database.)
[//]: # (You can use screenshot ingame to visual the issue.)
[//]: # (Write your tickets according to the format:)
[//]: # ([Quest][Azuremyst Isle] Red Snapper - Very Tasty!)
[//]: # ([NPC] Magistrix Erona)
[//]: # ([Spell][Mage] Fireball)
[//]: # ([Npc][Drop] Ghostclaw Lynx)
[//]: # ([Web] Armory doesnt work)
[//]: # (To find server revision type `.server info` command in the game chat.)

**Description**: 

20 Primal Water and 20 Primal Mana missing from <Memory> guild bank.  I (Tyba) withdrew them and they are not in my inventory after I relogged.  Not sure if they were in my inventory before relogging (to a bank alt and back) but definitely not there now.  They are also not back in the gbank.  I assume there is a synchronizing issue across threads.

https://imgur.com/a/4LQWNEr

**Current behaviour**:

Items missing from gbank after withdrawing and perhaps relogging.

**Expected behaviour**: 

**Server Revision**: 

2719

**Comment by Haipethdev** [comment]
To reiterate, this was not before or during a server crash like last time.

**Comment by Haipethdev** [comment]
They were also in position 1 and 2 (from top left to top right) in gbank tab 2

**Comment by Haipethdev** [comment]
They are back in the gbank after the crash

**Comment by Tenoutoften** [comment]
... So basically this report is "I got roll backed" or did a GM help out and grant the items back?

**Comment by Haipethdev** [comment]
No, a rollback would have placed the primals back in the gbank and is previously associated with a crash.  The primals disappeared before any crash.  I removed them from the bank, relogged, and they were gone completely.  It may have been the case they never reached my inventory or that they disappeared after a relog.

Once the server crashed, the primals returned to the gbank.  While my personal issue was "solved", this is still potentially a problem for the devs to fix for other people, guilds, and their banks so I have tried to give as much information for reproduction that I could.

**Comment by Haipethdev** [comment]
And no, GMs did not return anything as far as I know.  It simply returned upon crashing.

**Comment by Haipethdev** [comment]
This happened again.  Surely this is a critical bug?

**Comment by Tenoutoften** [comment]
Yeah, it is.

**Comment by Wolffenstein** [comment]
Duplicate.
