### ISSUE TITLE
[NPC] Bonechewer Ravener Threat

### ISSUE THREAD

**Issue by totaemoeggerli** [Atlantiss/NetherwingBugtracker#4723]
[//]: # (Enclose links to things related to the bug using http://wowhead.com or any other TBC database.)
[//]: # (You can use screenshot ingame to visual the issue.)
[//]: # (Write your tickets according to the format:)
[//]: # ([Quest][Azuremyst Isle] Red Snapper - Very Tasty!)
[//]: # ([NPC] Magistrix Erona)
[//]: # ([Spell][Mage] Fireball)
[//]: # ([Npc][Drop] Ghostclaw Lynx)
[//]: # ([Web] Armory doesnt work)
[//]: # (To find server revision type `.server info` command in the game chat.)

**Description**: 
[Bonechewer Ravaner](https://www.wowhead.com/npc=17264/bonechewer-ravener#comments)

**Current behaviour**:
This NPC doesn't seem to follow conventional threat rules. It does high dmg and uses Kidney Shot wich makes fights pretty messy and hard to pin down what is happening. The threat drop after Kidney Shot works as it should. However, it seems as if there are random threat drops appearing.
Here is a clip of a (bad) encounter: https://gfycat.com/AngelicRegularGuanaco
The analysis of the events is based on the addon Diamond Theart Meter which you can see on the right side of the action bars.

- 8sec - Kidney Shot - goes after Healer

- 23sec  - swiches target to Warlock(warlock 1k threat, tank 7k threat)

- 28sec - swiches target to Hunter (hunter 7k threat, tank 10k threat)

**Expected behaviour**: 
The mob should follow normal threat rules.

**Server Revision**: 2719

**Comment by Wolffenstein** [comment]
Their kidney shot causes a threat reset and that's intended.
