### ISSUE TITLE
WSG PVP Faction Que

### ISSUE THREAD

**Issue by Juicey17** [Atlantiss/NetherwingBugtracker#4725]
Every 70 WSG is always 3 ally vs 10 horde, letting horde in without a que is allowing them to farm honor and marks over and over again giving them an upper hand in pvp gear. When arena comes out the horde will already have an advantage over ally due to them having more honor points to purchase gear etc. PLEASE fix this.

**Comment by killablink** [comment]
Agreed, there is no point in q'ing BGs as an alliance because horde just swarms the BGs. Also due to the fact that there is no 45/55 queue. And also putting custom changes to make it so you can turn single marks for honor would be great.

**Comment by sandreid** [comment]
How is this a bug?

**Comment by gunzbngbng** [comment]
PvP is going to need tweaks.  Perhaps PvP gear shouldn't take marks to buy.

**Comment by sandreid** [comment]
That's still not a bug, ladies and gentlemen. If you want custom changes, take the discussion to the forums. This isn't the place. This is for reporting bugs only.

https://forum.atlantiss.eu/netherwing/forum/14-player-versus-player/

**Comment by tsuone** [comment]
Invalid.
