### ISSUE TITLE
[item][world drop] Eternium Runed Blade Recipe

### ISSUE THREAD

**Issue by knasen88** [Atlantiss/NetherwingBugtracker#4727]
[//]: # (Enclose links to things related to the bug using http://wowhead.com or any other TBC database.)
[//]: # (You can use screenshot ingame to visual the issue.)
[//]: # (Write your tickets according to the format:)
[//]: # ([Quest][Azuremyst Isle] Red Snapper - Very Tasty!)
[//]: # ([NPC] Magistrix Erona)
[//]: # ([Spell][Mage] Fireball)
[//]: # ([Npc][Drop] Ghostclaw Lynx)
[//]: # ([Web] Armory doesnt work)
[//]: # (To find server revision type `.server info` command in the game chat.)

**Description**: 
I have been looking for a crafter with this recipe for several days and have found nothing, not a single person has mentioned they have, nor have i ever seen anyone trying to sell it. It is supposed to be a world drop recipe so that none has dropped so far it's either abysmally low drop rate, teebus tier or simply not added to the loottable? I would assume this recipe would fetch a lot of reasons to flaunt your profession for the purpose of making gold so not like people have a reason for hiding they have it.

**Current behaviour**:
is it even added to the loot table?
**Expected behaviour**: 
https://www.wowhead.com/item=23635/plans-eternium-runed-blade#comments
"dropped from nagrand ogre, blades edge drake"
world drop recipe
**Server Revision**: 
2719

**Comment by killablink** [comment]
I believe someone was selling it as alliance

**Comment by knasen88** [comment]
alright, can confirm it actually exists now, hordeside has a crafter. Katt for anyone interested
not sure about the rarity or what mobs can drop it but w/e
