### ISSUE TITLE
[NPC][Loot] Defias Messenger

### ISSUE THREAD

**Issue by kohahahu** [Atlantiss/NetherwingBugtracker#4729]
https://vanillawowdb.com/?npc=550
https://vanilla-twinhead.twinstar.cz/?npc=550

He should drop https://vanilla-twinhead.twinstar.cz/?item=1381, and drop rate should be 100%.

I killed him 5 times with and without party and he didnt drop nothing besides common objects.

He should drop ;A Mysterious Messege;

Server Revision: 2719

**Comment by towneh** [comment]
Only if you have this quest active "http://db.hellfire-tbc.com/?quest=142"

**Comment by kohahahu** [comment]
srry for that
