### ISSUE TITLE
[Hunter Pet] Randomly despawned

### ISSUE THREAD

**Issue by Thugli** [Atlantiss/NetherwingBugtracker#473]
[//]: # (Enclose links to things related to the bug using http://wowhead.com or any other TBC database.)
[//]: # (You can use screenshot ingame to visual the issue.)
[//]: # (Write your tickets according to the format:)
[//]: # ([Quest][Azuremyst Isle] Red Snapper - Very Tasty!)
[//]: # ([NPC] Magistrix Erona)
[//]: # ([Spell][Mage] Fireball)
[//]: # ([Npc][Drop] Ghostclaw Lynx)
[//]: # ([Web] Armory doesnt work)

**Description**: 
My pet despawned as we were both swimming in Cragpool Lake in Stonetalon. I was unable to call or revive my pet and was getting the error message that I already have a summoned pet. After about 5 minutes the game finally registered that my pet had despawned and I was able to call my pet.

**Current behaviour**:
https://clips.twitch.tv/FaithfulReliableButterKappaClaus

**Expected behaviour**: 
Pet should not randomly despawn

**Server Revision**: 
Rev: 2045

**Comment by wtRCH** [comment]
Might be the same with Warlock pets.

**Comment by Easyfraggy** [comment]
Duplicate https://github.com/Atlantiss/NetherwingBugtracker/issues/319
