### ISSUE TITLE
Spell dmg as Healer

### ISSUE THREAD

**Issue by Hidehugo** [Atlantiss/NetherwingBugtracker#4731]
**Description**: Not implemented 1/3 of healing power as bonus spell damage which makes healing items far less attractive than they should be and giving a huge disadvantage to healers farming mobs or dealing damage

**Current behaviour**: Only healing item enhancements such as enchants and spellthreads increase the spelldamage of the player. Healing items which have the description "increases your healing by x and damage by 1/3*x" only increase the healing, not the dmg

**Expected behaviour**: Increase of spell damage by the amount in the description of the items

**Server Revision**:

**Comment by Kaziczek** [comment]
its not bug, its intented implementation, this will change in later patches.

**Comment by Balanarr** [comment]
Indeed. That was added in patch 2.3

**Comment by Hidehugo** [comment]
Ty for answering so quickly, my bad
