### ISSUE TITLE
[Spell][Warrior] Deep Wounds

### ISSUE THREAD

**Issue by bajkorv** [Atlantiss/NetherwingBugtracker#4732]
[//]: # (Enclose links to things related to the bug using http://wowhead.com or any other TBC database.)
[//]: # (You can use screenshot ingame to visual the issue.)
[//]: # (Write your tickets according to the format:)
[//]: # ([Quest][Azuremyst Isle] Red Snapper - Very Tasty!)
[//]: # ([NPC] Magistrix Erona)
[//]: # ([Spell][Mage] Fireball)
[//]: # ([Npc][Drop] Ghostclaw Lynx)
[//]: # ([Web] Armory doesnt work)
[//]: # (To find server revision type `.server info` command in the game chat.)

**Description**: Deep wounds should make warriors critical strikes cause the opponent to bleed, causing 60% of average melee damage over 12 sec.

**Current behaviour**: Does not procc of all warrior critical attacks which it should. Currently it doesnt procc off Whirlwind, Hamstring or Pummel that I've found

**Expected behaviour**: Should be procced of all warrior critical melee abilities and attacks.

**Server Revision**: 2719

**Comment by Dusky1** [comment]
Deep Wounds also kills opponents after duel. It should be removed after duel, but it if the last hit by warrior in a duel is crit, its not removed.

**Comment by Crusaderz** [comment]
It does proc from hamstring.

**Comment by bajkorv** [comment]
actually you are right, now it proccs of hamstring, it didnt at the time of the bug report though, will do more testing

**Comment by Easyfraggy** [comment]
Same as Whirlwind sometimes doesn't proc Flurry (possibly related to whirlwind offhand hits?

**Comment by bajkorv** [comment]
Ive now noticed that sometimes when someone dodge ur whirlwind when its not ur current target, u cannot overpower that target. Same thing with deep wounds on occasions where whirlwind crits a target thats not ur current target and hits multiple targets - doesnt always happen, its usually when it hits/dodges on 3 or 4 targets, not as usual when its only 2.
