### ISSUE TITLE
Bugged character -meeseging, mailing etc

### ISSUE THREAD

**Issue by hesusinc** [Atlantiss/NetherwingBugtracker#4733]
Messeges /w /p /s etc and mail sending didn't work. I can see what I wrote, but other persons can't.
Char name - Tailisha

**Server Revision**: 
2719

**Comment by Pan43** [comment]
I have the same problem, it's frustrating when you can't respond to other players, or write them anything

**Comment by hesusinc** [comment]
DEVs, can you delete and restore character? Maybe this can solve problem. Or check that this char still have 10lvl block

**Comment by The14me** [comment]
Must be related to the Spam system/fixed.
