### ISSUE TITLE
Formula: Runed Eternium Rod: restock time 

### ISSUE THREAD

**Issue by distilled890** [Atlantiss/NetherwingBugtracker#4734]
**Description**: Madame Ruby current supply of the formula: Runed Eternium Rod is bugged. Takes too much time to respawn

**Current behaviour**: It takes several hours (6-12 hrs) for the item to reappear again to be bought

**Expected behaviour**: The respawn should take way less (1-2 hrs)

**Server Revision**: 2719

**Comment by distilled890** [comment]
Couldn't find ANY comment at all on wowhead talking about respawn issues, but on retail noone bought recipes/formula to sell for over x100 their price, here it happens and there is noone happy about it, except the ones that hoard onto em and sell for crazy prices

**Comment by knasen88** [comment]
@drchristie find proof they indeed are 12h respawn thats fucking stock mangoos maybe they wouldn't :)

**Comment by Wolffenstein** [comment]
I will fix all recipes like that, just need a list.

**Comment by gaypala** [comment]
thanks man

**Comment by gaypala** [comment]
https://www.wowhead.com/item=22563/formula-superior-wizard-oil
https://www.wowhead.com/item=22565/formula-large-prismatic-shard
https://www.wowhead.com/item=28282/formula-enchant-shield-major-stamina
https://www.wowhead.com/item=22562/formula-superior-mana-oil
https://www.wowhead.com/item=25849/formula-runed-eternium-rod
https://www.wowhead.com/item=25848/formula-runed-adamantite-rod

**Comment by Wolffenstein** [comment]
Fixed in rev 2735.

**Comment by jcm3** [comment]
https://www.wowhead.com/item=22907/recipe-super-mana-potion

**Comment by knasen88** [comment]
^the above vendor sells more recipes aswelll
