### ISSUE TITLE
[Spell][Warrior] Execute

### ISSUE THREAD

**Issue by battleleet2** [Atlantiss/NetherwingBugtracker#4735]
[//]: # (Enclose links to things related to the bug using http://wowhead.com or any other TBC database.)
[//]: # (You can use screenshot ingame to visual the issue.)
[//]: # (Write your tickets according to the format:)
[//]: # ([Quest][Azuremyst Isle] Red Snapper - Very Tasty!)
[//]: # ([NPC] Magistrix Erona)
[//]: # ([Spell][Mage] Fireball)
[//]: # ([Npc][Drop] Ghostclaw Lynx)
[//]: # ([Web] Armory doesnt work)
[//]: # (To find server revision type `.server info` command in the game chat.)

**Description**: 
15 Rage
Attempt to finish off a wounded foe, causing [X + AP * 0.2] damage and converting each extra point of rage into Y additional damage (up to a maximum cost of 30 rage). Only usable on enemies that have less than 20% health.

**Current behaviour**:
Execute in some scenarios isn't doing anything:
it's not dodged, parried, blocked, missed - takes out rage without dealing any damage and without any description in combat log: video provided:
https://youtu.be/tkXb1H6SdSg

**Expected behaviour**: 

**Server Revision**: 
2719

**Comment by arifashaari** [comment]
same bug as sunwell's wotlk realm

**Comment by Crusaderz** [comment]
I've never seen my execute gets parried, dodged or missed, but i've seen my overpower became aviable right after my execute "did nothing", so i think server does not tell client that execute fails because of parry, dodge or miss. Its the only rational explanation.

**Comment by knasen88** [comment]
Try reaching out to Kain of Gamer district, his old 7x server did not have this issue afaik (also trinity core)

**Comment by Crusaderz** [comment]
@Wolffenstein 
Server still doesn't send client notification when execute missed\parried\dodged .
Should we open new bug report or you can re-open this one?

**Comment by battleleet2** [comment]
Confirming, heard parry sound - nothing on screen, no info in combat log, minor bug really, but still here.

**Comment by Hellhound1408** [comment]
To this date 16th Feb 2019 it is still happening. Execute dumpes rage, but no damage and no message in the Combatlog.

**Comment by Easyfraggy** [comment]
Need video showing the rage dump - On my warrior it just doesn't show "Parry/Dodge/Miss" message when it happens - only consumes 20% of the base rage cost like it should. This is merely a visual issue to me.

**Comment by Wolffenstein** [comment]
Please retest in rev 2804.

**Comment by Crusaderz** [comment]
@Wolffenstein rev 2809 still not working
