### ISSUE TITLE
[Spell] Can be master of more than one alchemy specialization

### ISSUE THREAD

**Issue by Sabre142** [Atlantiss/NetherwingBugtracker#4736]
**Description**: 
Regarding Alchemy specializations, you can only choose one and pay to change it later.

**Current behaviour**:
Can be Transmutation and Potion master at the same time. Probably can be Elixir mastery too to have all three.

**Expected behaviour**:
You should only be allowed to have one mastery in your spellbook at once.

**Server Revision**: 
2719

**Comment by Brasso** [comment]
You sure it's just not a visual issue? Have you gotten procs with two specs? Also relearning alchemy was not in the game in 2.0 this was missed by the team.

**Comment by lynxzor** [comment]
Profession switching was intended to be in from the start afaik

**Comment by lynxzor** [comment]
You're right, though as I said they intended to have it at release @aresbrutus

**Comment by The14me** [comment]
By look at the date, that ''issue'' is due later patch added.
