### ISSUE TITLE
proffesion engineering 

### ISSUE THREAD

**Issue by enjente** [Atlantiss/NetherwingBugtracker#4737]
[//]: # (Enclose links to things related to the bug using http://wowhead.com or any other TBC database.)
[//]: # (You can use screenshot ingame to visual the issue.)
[//]: # (Write your tickets according to the format:)
[//]: # ([Quest][Azuremyst Isle] Red Snapper - Very Tasty!)
[//]: # ([NPC] Magistrix Erona)
[//]: # ([Spell][Mage] Fireball)
[//]: # ([Npc][Drop] Ghostclaw Lynx)
[//]: # ([Web] Armory doesnt work)
[//]: # (To find server revision type `.server info` command in the game chat.)

**Description**: cannot unlearn goblin engineering

**Current behaviour**:paying 10g for unlearn gobling engineering and nothing happens

**Expected behaviour**: should pay 150g and unlearn goblin engineering and be able to learn gnomish engineering

**Server Revision**:

**Comment by devo6969** [comment]
The 150g wasn't a thing till wotlk 3.2. In Classic/TBC you had to unlearn your entire Engineering, reach 200 and then go to the book and you could re-choose specializations. Book: " Soothsaying for Dummies"
 
https://wowwiki.fandom.com/wiki/Patch_3.2.0
Gnomish Engineers and Goblin Engineers can now switch profession specializations for a fee. (150g)

WOTLK - https://www.youtube.com/watch?v=9ffNV2ZRI7M (150g fee)
Classic + TBC - https://www.youtube.com/watch?v=7Iv_iSatN1w (Unlearning Eng)
