### ISSUE TITLE
Quest - Atamal Terrace

### ISSUE THREAD

**Issue by keaarori** [Atlantiss/NetherwingBugtracker#4739]
*Description**: 

**Current behaviour**: Shadowmoon Soulsteelers do not attack, just stand still after killing them no boss or any other progress happens (Almost like script is not triggering), can not pick up Heart either.

**Expected behaviour**: 

**Server Revision**: 
2719

**Comment by Desst** [comment]
haven't been able to complete this quests for more than a week now

**Comment by Imbaslap** [comment]
this event is not really scripted.

Source: 
https://www.youtube.com/watch?v=HoeSAheA36M (TBC retail)
https://www.youtube.com/watch?v=BEAe7_DGNkQ (Retail)
