### ISSUE TITLE
Sunscale Scytheclaw gets 3 attacks

### ISSUE THREAD

**Issue by asatorrr** [Atlantiss/NetherwingBugtracker#474]
[//]: # (Enclose links to things related to the bug using http://wowhead.com or any other TBC database.)
[//]: # (You can use screenshot ingame to visual the issue.)
[//]: # (Write your tickets according to the format:)
[//]: # ([Quest][Azuremyst Isle] Red Snapper - Very Tasty!)
[//]: # ([NPC] Magistrix Erona)
[//]: # ([Spell][Mage] Fireball)
[//]: # ([Npc][Drop] Ghostclaw Lynx)
[//]: # ([Web] Armory doesnt work)

**Description**: Sunscale scytheclaws are triggering 3 attacks per attack animation. I'm a level 15 shaman fighting level 16 scytheclaws and barely survive. Noticed every attack animation I'm getting hit 3 times all at once.

**Current behaviour**:

**Expected behaviour**: 

**Server Revision**: 2045

**Comment by Wolffenstein** [comment]
Thrash?

**Comment by Evolvee** [comment]
slightly reduced thrash chance
