### ISSUE TITLE
[Spell][Warrior] Anticipation

### ISSUE THREAD

**Issue by Avodat** [Atlantiss/NetherwingBugtracker#4740]
**Description**: The protection talent "Anticipation" isn't working.

**Current behaviour**: 
5/5 Anticipation will increase cap of your Defense skill by 20, but you can't level it to max. So level 70 Warrior will have 350/370 defense skill and it wont go past that, making the talent useless.

**Expected behaviour**: 
Your defense cap should increase, as it does. But you should be able to skill up the Defense skill to 370/370 (cap at level 70).

**Server Revision**: 
2719

**Comment by Wolffenstein** [comment]
It will be fixed in rev 2739.
