### ISSUE TITLE
[Warrior] Overpower proc lasts less than 5 seconds

### ISSUE THREAD

**Issue by Crusaderz** [Atlantiss/NetherwingBugtracker#4741]
When my white attack dodged and i don't have 5 rage for OP it deactivates before my weapon (3.8 attack speed) hits again.

tbc warrior: https://youtu.be/3oWUk0F3mmE
His attack dodged @ 6:05 and OP deactivates @ 6:10

**Comment by Wolffenstein** [comment]
And how long is it supposed to last?

**Comment by Crusaderz** [comment]
@Wolffenstein 
5 seconds, according to video evidence.

**Comment by Wolffenstein** [comment]
Fixed in rev 2745.
