### ISSUE TITLE
Pet dissappearing when you dismount close to objects.

### ISSUE THREAD

**Issue by dalabu** [Atlantiss/NetherwingBugtracker#4744]
**Description**: Pet dissappearing when you dismount close to objects

**Current behaviour**: As shown in the video.
https://streamable.com/u2cdi

**Expected behaviour**: Pet should appear next to you and not dissappear into objects, this will have big impact in arena.

**Server Revision**: 2745

**Comment by Wolffenstein** [comment]
Fixed in rev 2746.
