### ISSUE TITLE
[Spell][Hunter] Multishot

### ISSUE THREAD

**Issue by Eidous** [Atlantiss/NetherwingBugtracker#4745]
[//]: # (Enclose links to things related to the bug using http://wowhead.com or any other TBC database.)
[//]: # (You can use screenshot ingame to visual the issue.)
[//]: # (Write your tickets according to the format:)
[//]: # ([Quest][Azuremyst Isle] Red Snapper - Very Tasty!)
[//]: # ([NPC] Magistrix Erona)
[//]: # ([Spell][Mage] Fireball)
[//]: # ([Npc][Drop] Ghostclaw Lynx)
[//]: # ([Web] Armory doesnt work)
[//]: # (To find server revision type `.server info` command in the game chat.)

**Description**: 
When starting a fight by casting multishot, your character will autoshot first.

**Current behaviour**:
If you open combat with a multishot, your character first fires off an autoshot, effectively giving your multishot a 1s cast time

**Expected behaviour**: 
Starting combat with multishot should make your character fire a multishot immediately.

**Server Revision**: 
2745

**Comment by Wolffenstein** [comment]
It will no longer be delayed by an additional 500ms from rev 2747.
