### ISSUE TITLE
Watcher Leesa'oh stuck.

### ISSUE THREAD

**Issue by PuffedxO** [Atlantiss/NetherwingBugtracker#4747]
[//]: # (Enclose links to things related to the bug using http://wowhead.com or any other TBC database.)
[//]: # (You can use screenshot ingame to visual the issue.)
[//]: # (Write your tickets according to the format:)
[//]: # ([Quest][Azuremyst Isle] Red Snapper - Very Tasty!)
[//]: # ([NPC] Magistrix Erona)
[//]: # ([Spell][Mage] Fireball)
[//]: # ([Npc][Drop] Ghostclaw Lynx)
[//]: # ([Web] Armory doesnt work)
[//]: # (To find server revision type `.server info` command in the game chat.)

**Description**: 
[Watcher Leesa'oh ](http://db.hellfire-tbc.com/?npc=17831) is stuck

**Current behaviour**:
She Just stands there doing nothing

**Expected behaviour**: 
NPC should reset.

**Server Revision**: 
2745

**Comment by Cosmic-Lattee** [comment]
Can confirm that she is stuck just standing there still.

**Comment by devo6969** [comment]
I assume the report is meaning when you turn in (Quest ID 9709) Stealing Back the Mushrooms. She does her RP walk and spawns a mushroom, you see a boglord attack it and then RP walks back to her spot. From what I can see the NPC isnt stuck. Resetted my quests and grabbed "(Quest ID 9697) Watcher Leesa'oh and was able to pick up quests. Fixed most likely.
