### ISSUE TITLE
Spider in a Tree (Ghostlands)

### ISSUE THREAD

**Issue by deku100** [Atlantiss/NetherwingBugtracker#475]
[//]: # (Enclose links to things related to the bug using http://wowhead.com or any other TBC database.)
[//]: # (You can use screenshot ingame to visual the issue.)
[//]: # (Write your tickets according to the format:)
[//]: # ([Quest][Azuremyst Isle] Red Snapper - Very Tasty!)
[//]: # ([NPC] Magistrix Erona)
[//]: # ([Spell][Mage] Fireball)
[//]: # ([Npc][Drop] Ghostclaw Lynx)
[//]: # ([Web] Armory doesnt work)

**Description**: Spider in a Tree

**Current behaviour**: Found a spider spawned on the side of tree in the Ghostlands on the way to Windrunner Village. 
![wowscrnshot_092418_232740](https://user-images.githubusercontent.com/43505181/45992098-f893f780-c055-11e8-92b7-e0ed215b9ba4.jpg)

**Expected behaviour**:  Spiders don't spawn in trees.

**Server Revision**:

**Comment by wtRCH** [comment]
It's Blizzlike
