### ISSUE TITLE
[Item] Dragon's Call 

### ISSUE THREAD

**Issue by InsertLink** [Atlantiss/NetherwingBugtracker#4751]
[//]: # (Enclose links to things related to the bug using http://wowhead.com or any other TBC database.)
[//]: # (You can use screenshot ingame to visual the issue.)
[//]: # (Write your tickets according to the format:)
[//]: # ([Quest][Azuremyst Isle] Red Snapper - Very Tasty!)
[//]: # ([NPC] Magistrix Erona)
[//]: # ([Spell][Mage] Fireball)
[//]: # ([Npc][Drop] Ghostclaw Lynx)
[//]: # ([Web] Armory doesnt work)
[//]: # (To find server revision type `.server info` command in the game chat.)

**Description**: Dragon's Call summons a whelp to aid you in battle but the whelp doesn't do anything apart from following the owner around.

**Current behaviour**:Summoned Whelp doesn't do anything in combat.

**Expected behaviour**:Summoned Whelp attacks whoever is nearest to his summoner.

**Server Revision**:2747

**Comment by pbjtime** [comment]
Confirming this behavior happens to me aswell; adding on that it appears when the whelp is hit by an aoe spell OR runs off and attacks a different target that you arnt attacking it properly casts acid spit. Seems that the whelp isnt properly starting to attack which is fixed when they are attacked back.

**Comment by markito123** [comment]
I also have this bug issue. At this moment i got the the 1 hand sword Dragon's Call. Please Update on this issue. Coz its my first epic item in this server :(

**Comment by The14me** [comment]
Rev 3483 they work just fine/attack and cast. Tested on Dummy.
