### ISSUE TITLE
Warmaul Ogre Banner can be planted in other player's corpses. 

### ISSUE THREAD

**Issue by Dovvah** [Atlantiss/NetherwingBugtracker#4752]
**Description**: 
([Quest][Nagrand] Ruthless Cunning) ( 9927 ) 
**Current behaviour**:
Warmaul Ogre Banner ( item=25552 ) can be planted in corpses killed by other players including enemies. 
**Expected behaviour**: 
You should only be able to plant the banner in your corpses. 
**Server Revision**: 
2747

**Comment by Tenoutoften** [comment]
Are you sure?
