### ISSUE TITLE
Quest [Control] won't work

### ISSUE THREAD

**Issue by DialMat** [Atlantiss/NetherwingBugtracker#4754]
https://www.wowhead.com/quest=9595/control
LV10 class quest for mages in the Draenei starting area won't work. The guy who you are supposed to kill just won't appear.

**Comment by ttghnw** [comment]
I tested during beta and it was working you need to kill **a lot** of murlocs.

**Comment by DialMat** [comment]
we were in a group of two and killed something between 30 and 40. i guess ill go back on another killing spree then! thanks.
