### ISSUE TITLE
[Hunter][Spell] Auto shot doesn't always fire on your current target

### ISSUE THREAD

**Issue by Zarant** [Atlantiss/NetherwingBugtracker#4755]
Sometimes when using tab to switch targets or after using multi-shot, your auto shot will fire on your previous target instead of your current one

Current behavior: https://www.youtube.com/watch?v=81UDj5Pym1w&feature=youtu.be&t=4918

Expected behavior:  Auto Shot should always hit your current target

Server Revision:  2747

**Comment by MelEnt** [comment]
Confirm

**Comment by DragunovUA** [comment]
same 4 me, feels bad when u broke your freeze target cos of this stupid bug

**Comment by Wolffenstein** [comment]
Fixed in rev 2858.
