### ISSUE TITLE
Character Stats are completely broken

### ISSUE THREAD

**Issue by femdead** [Atlantiss/NetherwingBugtracker#4756]
Anticipation broken again(still), 350/350 defence at level 70 with 5/5 anticipation
Character sheet showing 0% parry 
Not gaining 5% crit from cruelty
0% block even with shield block, can't get a single revenge proc in a dungeon

What the hell happened in this update jesus christ

**Comment by femdead** [comment]
Not the same as previous issue where you couldn't train defence past your base level cap, where you were stuck at 350/370 (or w/e for your level), it's simply 350/350

**Comment by Wolffenstein** [comment]
relog

**Comment by femdead** [comment]
ok i relogged and i got group bugged when i was leader, epic
