### ISSUE TITLE
[Quest][Shadowmoon Valley] Teron Gorefiend I am...

### ISSUE THREAD

**Issue by Mikik3jr** [Atlantiss/NetherwingBugtracker#4757]
[//]: # (Enclose links to things related to the bug using http://wowhead.com or any other TBC database.)
[//]: # (You can use screenshot ingame to visual the issue.)
[//]: # (Write your tickets according to the format:)
[//]: # ([Quest][Azuremyst Isle] Red Snapper - Very Tasty!)
[//]: # ([NPC] Magistrix Erona)
[//]: # ([Spell][Mage] Fireball)
[//]: # ([Npc][Drop] Ghostclaw Lynx)
[//]: # ([Web] Armory doesnt work)
[//]: # (To find server revision type `.server info` command in the game chat.)

**Description**: 
In this Q you are "possesed" by a pet, then you fight against an elite with new spells.

**Current behaviour**:
The life stealing ability which restores HP does not restore HP to the pet, but your character making the elite idk why attacking the character instead of the pet. With this the pet gets outDPSed from that constant lightning that attacks it and can't kill the elite. Sometimes I even lost the controll and both of them were hitting me....

Sometimes the event is stuck and the lightning attacks are coming even during RP, so you are at liek 50% hp when it starts. 
![image](https://user-images.githubusercontent.com/43505031/52146010-dbee7880-2662-11e9-80a8-0b78b3464867.png)

**Expected behaviour**: 
- The lighning thingies should not attack the quest giver before I take the quest, nor should I take dmg during RP after I get the quest
- The heal ability should heal the pet, not the character, and character should not get aggroed by the elite.

**Server Revision**: 
2749

**Comment by Mikik3jr** [comment]
For those who want to finish this quest, just put down the death of decay, cuz that is your primary damage, and spam absorb on yourself.

**Comment by Tereneckla** [comment]
Fixed
