### ISSUE TITLE
[Spell] Rupture consuming combo points when it doesn't land

### ISSUE THREAD

**Issue by Tixlenra** [Atlantiss/NetherwingBugtracker#4758]
[//]: # (Enclose links to things related to the bug using http://wowhead.com or any other TBC database.)
[//]: # (You can use screenshot ingame to visual the issue.)
[//]: # (Write your tickets according to the format:)
[//]: # ([Quest][Azuremyst Isle] Red Snapper - Very Tasty!)
[//]: # ([NPC] Magistrix Erona)
[//]: # ([Spell][Mage] Fireball)
[//]: # ([Npc][Drop] Ghostclaw Lynx)
[//]: # ([Web] Armory doesnt work)
[//]: # (To find server revision type `.server info` command in the game chat.)

**Description**: [Spell] Rupture consuming combo points when it doesn't land

**Current behaviour**:[Spell] Rupture consuming combo points when it doesn't land

**Expected behaviour**: shouldn't consume combo points unless it lands

**Server Revision**: 2749

didnt notice this before 01-02-19

**Comment by Tixlenra** [comment]
this also counts for eviscerate now too

**Comment by Wolffenstein** [comment]
Fixed in rev 2750.
