### ISSUE TITLE
Auto-shot carries on through steady aim cast

### ISSUE THREAD

**Issue by Tixlenra** [Atlantiss/NetherwingBugtracker#4759]
[//]: # (Enclose links to things related to the bug using http://wowhead.com or any other TBC database.)
[//]: # (You can use screenshot ingame to visual the issue.)
[//]: # (Write your tickets according to the format:)
[//]: # ([Quest][Azuremyst Isle] Red Snapper - Very Tasty!)
[//]: # ([NPC] Magistrix Erona)
[//]: # ([Spell][Mage] Fireball)
[//]: # ([Npc][Drop] Ghostclaw Lynx)
[//]: # ([Web] Armory doesnt work)
[//]: # (To find server revision type `.server info` command in the game chat.)

**Description**: Auto-shot carries on through steady aim cast

**Current behaviour**: Auto-shot carries on through steady aim cast

**Expected behaviour**: shouldn't

**Server Revision**: 2749

**Comment by Easyfraggy** [comment]
https://github.com/Atlantiss/NetherwingBugtracker/issues/5043 I know this one is earlier but almost no information here compared.
