### ISSUE TITLE
Debuff Timers not displaying properly (Deatholme Acolytes, Ghostlands)

### ISSUE THREAD

**Issue by deku100** [Atlantiss/NetherwingBugtracker#476]
[//]: # (Enclose links to things related to the bug using http://wowhead.com or any other TBC database.)
[//]: # (You can use screenshot ingame to visual the issue.)
[//]: # (Write your tickets according to the format:)
[//]: # ([Quest][Azuremyst Isle] Red Snapper - Very Tasty!)
[//]: # ([NPC] Magistrix Erona)
[//]: # ([Spell][Mage] Fireball)
[//]: # ([Npc][Drop] Ghostclaw Lynx)
[//]: # ([Web] Armory doesnt work)

**Description**: Debuff Timers not displaying properly

**Current behaviour**: Fought two Deatholme Acolytes in Ghostlands simultaneously, and both used Shadow Word: Pain on me. However, one of the two debuff timers showed "0 sec" for the duration of the debuff. I still took damage for both SW:Ps.

Initial encounter:
![wowscrnshot_092418_234738](https://user-images.githubusercontent.com/43505181/45992160-401a8380-c056-11e8-9a40-36994f80164a.jpg)
Time Elapsed:
![wowscrnshot_092418_234741](https://user-images.githubusercontent.com/43505181/45992168-4d377280-c056-11e8-8502-93cd7e27db97.jpg)
And again in another encounter:
![wowscrnshot_092418_234904](https://user-images.githubusercontent.com/43505181/45992176-57597100-c056-11e8-9a43-d83568710bf6.jpg)

**Expected behaviour**: Debuff timers should countdown properly for each debuff, including multiple instances of the same debuff.

**Server Revision**:

**Comment by deku100** [comment]
Also "Ghost" has a continuous "0 sec" debuff timer as well.
![wowscrnshot_092518_001826](https://user-images.githubusercontent.com/43505181/45992947-4ca0db00-c05a-11e8-8b92-0fe105e6bcf0.jpg)

**Comment by Sinyr** [comment]
Regarding double debuffs, it happened to me too with Veridian Broodling's Poison Bolt. When I got hit by 2 of them, one stayed at 0s instead of expiring and still dealt damage. Using Purify removed the 0s one first.

**Comment by Easyfraggy** [comment]
https://github.com/Atlantiss/NetherwingBugtracker/issues/85 try again after 2055.
