### ISSUE TITLE
[Druid]  Loss of all Comobo Points if Finishing Move gets dodged / parried

### ISSUE THREAD

**Issue by d4rksite** [Atlantiss/NetherwingBugtracker#4760]
[//]: # (Enclose links to things related to the bug using http://wowhead.com or any other TBC database.)
[//]: # (You can use screenshot ingame to visual the issue.)
[//]: # (Write your tickets according to the format:)
[//]: # ([Quest][Azuremyst Isle] Red Snapper - Very Tasty!)
[//]: # ([NPC] Magistrix Erona)
[//]: # ([Spell][Mage] Fireball)
[//]: # ([Npc][Drop] Ghostclaw Lynx)
[//]: # ([Web] Armory doesnt work)
[//]: # (To find server revision type `.server info` command in the game chat.)

**Description**: 
Loss of all comobo points on the target with druid when the finishing move gets dodged / parry (not sure about miss).

**Current behaviour**:
When I use my finishing move on a target and it gets dodged / parried (missed) all comobo points are consumed.

**Expected behaviour**: 
Comobo Points should stay on target if the finishing move gets dodged / parried / missed, just the energy should be lost. This was the behaviour prior to the latest patch

**Server Revision**: 
2749

**Comment by xMooby** [comment]
#4758 Appearing to be affecting all combo point abilities, not class specific after latest update.

**Comment by AndrewNB41191** [comment]
Affects rogues

**Comment by Wolffenstein** [comment]
Fixed in rev 2750.
