### ISSUE TITLE
[OHF Heroic] Epoch Hunter (Endboss) has no loot

### ISSUE THREAD

**Issue by Azalen** [Atlantiss/NetherwingBugtracker#4762]
**Description**: 
https://www.wow-freakz.com/npc_finder.php?npc=20531&name=epoch-hunter-heroic

**Expected behaviour**: 
Endboss should drop 2 blue items just like every other endboss does.

**Server Revision**:

**Comment by Tenoutoften** [comment]
Already reported:
https://github.com/Atlantiss/NetherwingBugtracker/issues/4720
This was also reported in the Beta by me to check:
https://github.com/Atlantiss/NetherwingBugtracker/issues/3438

**Comment by Azalen** [comment]
Ye I know but one is only a comment and one is closed. Since this is a pretty big bug that is very easy to fix I wanted to make new report.

**Comment by Effi28** [comment]
Since the chest there is part of the BiS for Destruciton Warlocks until t6, a fix would be nice.

**Comment by Wolffenstein** [comment]
Fixed in rev 2751.
