### ISSUE TITLE
[NPC][Swamp of Sorrows] Moustrous Crawler

### ISSUE THREAD

**Issue by maxturtlesc2** [Atlantiss/NetherwingBugtracker#4765]
[//]: # (Enclose links to things related to the bug using http://wowhead.com or any other TBC database.)
[//]: # (You can use screenshot ingame to visual the issue.)
[//]: # (Write your tickets according to the format:)
[//]: # ([Quest][Azuremyst Isle] Red Snapper - Very Tasty!)
[//]: # ([NPC] Magistrix Erona)
[//]: # ([Spell][Mage] Fireball)
[//]: # ([Npc][Drop] Ghostclaw Lynx)
[//]: # ([Web] Armory doesnt work)
[//]: # (To find server revision type `.server info` command in the game chat.)

**Description**: 
https://imgur.com/a/zMVY7Oi
**Current behaviour**:
When killed, the dead body goes down at the bottom of the water. If the mob was killed too far up from the bottom, you can't loot it.
**Expected behaviour**: 
When killed, the dead body should stay still in the water, allowing normal loot corpse.
**Server Revision**:

**Comment by The14me** [comment]
Rev.3483 not an issue anymore.
