### ISSUE TITLE
Explosive Sheep (ENGINEERING)

### ISSUE THREAD

**Issue by MelEnt** [Atlantiss/NetherwingBugtracker#4767]
[//]: # (Enclose links to things related to the bug using http://wowhead.com or any other TBC database.)
[//]: # (You can use screenshot ingame to visual the issue.)
[//]: # (Write your tickets according to the format:)
[//]: # ([Quest][Azuremyst Isle] Red Snapper - Very Tasty!)
[//]: # ([NPC] Magistrix Erona)
[//]: # ([Spell][Mage] Fireball)
[//]: # ([Npc][Drop] Ghostclaw Lynx)
[//]: # ([Web] Armory doesnt work)
[//]: # (To find server revision type `.server info` command in the game chat.)

**Description**: 
Explosive Sheep is bugged.

**Current behaviour**:
Upon using: 
* spawns Sheep
* Sheep disappears
* Creates permanent cooldown for every explosive item

**Expected behaviour**: 
https://www.youtube.com/watch?v=_7vYZQIIGrw

**Server Revision**: 
2749

**Comment by Nuy** [comment]
Can confirm it's bugged.

**Comment by Godmatik** [comment]
fixed - can close
