### ISSUE TITLE
Fire from Nazan in Hellfire Ramparts kills through Divine Shield

### ISSUE THREAD

**Issue by bubbluzz** [Atlantiss/NetherwingBugtracker#4768]
[//]: # (Enclose links to things related to the bug using http://wowhead.com or any other TBC database.)
[//]: # (You can use screenshot ingame to visual the issue.)
[//]: # (Write your tickets according to the format:)
[//]: # ([Quest][Azuremyst Isle] Red Snapper - Very Tasty!)
[//]: # ([NPC] Magistrix Erona)
[//]: # ([Spell][Mage] Fireball)
[//]: # ([Npc][Drop] Ghostclaw Lynx)
[//]: # ([Web] Armory doesnt work)
[//]: # (To find server revision type `.server info` command in the game chat.)

**Description**: The fire from Nazan in Hellfire Ramparts deals damage through divine shield

**Current behaviour**: fire damage through divine shield

**Expected behaviour**: divine shield immune to fire damage

**Server Revision**: 2749
![divine shield bug](https://user-images.githubusercontent.com/47263179/52157985-060c5e80-2694-11e9-8b43-846442e6dc7f.PNG)
![divineshieldbugged](https://user-images.githubusercontent.com/47263179/52157989-09074f00-2694-11e9-96e3-7863e7253cba.PNG)

**Comment by MAY-THE-ETERNAL-SUN-SHINE-UPON-YOU** [comment]
Confirmed still happens.
