### ISSUE TITLE
Finishers Consuming All Combo Points When Missed, Dodged or Parried

### ISSUE THREAD

**Issue by jasonbourne109** [Atlantiss/NetherwingBugtracker#4769]
After today's updates, finishing abilities on my Feral Druid will consume all combo points even when they miss or they are dodged/parried. This was not how finishers functioned before today's updates and definitely not how they worked on Blizzard servers.

Let me know if you would like to see anything else as proof that this is a bug.

**Comment by jasonbourne109** [comment]
Also happens when mobs are immune to the attack. i.e. If I use Rip on a mob that is immune to bleeds, then all combo points disappear.

**Comment by Wolffenstein** [comment]
Fixed in rev 2750.
