### ISSUE TITLE
[UI][Quest] The Tower of Althalaxx quest tracker does not always update with progress

### ISSUE THREAD

**Issue by Vempz** [Atlantiss/NetherwingBugtracker#477]
[//]: # (Enclose links to things related to the bug using http://wowhead.com or any other TBC database.)
[//]: # (You can use screenshot ingame to visual the issue.)
[//]: # (Write your tickets according to the format:)
[//]: # ([Quest][Azuremyst Isle] Red Snapper - Very Tasty!)
[//]: # ([NPC] Magistrix Erona)
[//]: # ([Spell][Mage] Fireball)
[//]: # ([Npc][Drop] Ghostclaw Lynx)
[//]: # ([Web] Armory doesnt work)

**Description**: 

1. go to Darkshore and complete the series of quests leading up to [The Tower of Althalaxx](http://db.hellfire-tbc.com/?quest=966)
2. accept and track the quest
3. kill quest mobs and pick up [Worn Parchment](http://db.hellfire-tbc.com/?item=5348)
4. current behaviour is visible: https://imgur.com/a/On2DLjI

**Current behaviour**:

- quest tracker does not always update with quest progress

**Expected behaviour**: 

- quest tracker should always update with quest progress

**Server Revision**: 
rev: 2045

**Comment by Firroth** [comment]
It's like that for almost every quest which requires more than 1 item, it's a visual bug of some sort.

**Comment by Tereneckla** [comment]
Fixed
