### ISSUE TITLE
Money disappeared from Guild bank after deposit

### ISSUE THREAD

**Issue by ClearedObject** [Atlantiss/NetherwingBugtracker#4770]
[//]: # (Enclose links to things related to the bug using http://wowhead.com or any other TBC database.)
[//]: # (You can use screenshot ingame to visual the issue.)
[//]: # (Write your tickets according to the format:)
[//]: # ([Quest][Azuremyst Isle] Red Snapper - Very Tasty!)
[//]: # ([NPC] Magistrix Erona)
[//]: # ([Spell][Mage] Fireball)
[//]: # ([Npc][Drop] Ghostclaw Lynx)
[//]: # ([Web] Armory doesnt work)
[//]: # (To find server revision type `.server info` command in the game chat.)
I made a deposit of 20 silver at first to make sure it worked, sure enough later that evening the deposit was there. The next day however I logged in and it was gone, no log of it being taken out but I assumed the guild master had taken it out. So as I was trying to help fund our first guild tab I deposited some gold into the bank, after seeing it gone I wrote our guild master, he did not touch it. After this I knew it had an issue going in, so I checked my gold... I didn't have it there either. TLDR: Put some money in the guild bank, didn't show up there and went out of my inventory. 
Thanks for your time
**Description**: 

**Current behaviour**:

**Expected behaviour**: 

**Server Revision**: 2749

**Comment by Wolffenstein** [comment]
Duplicate.
