### ISSUE TITLE
Shadow Labs Ambassador Hellmaw bugged (Banish mode)

### ISSUE THREAD

**Issue by garrettz459** [Atlantiss/NetherwingBugtracker#4771]
[//]: # (Enclose links to things related to the bug using http://wowhead.com or any other TBC database.)
[//]: # (You can use screenshot ingame to visual the issue.)
[
![image](https://user-images.githubusercontent.com/18148419/52159368-76ee4f00-2671-11e9-8ad3-930c94509981.png)
](url)
[//]: # (Write your tickets according to the format:)
[//]: # ([Quest][Azuremyst Isle] Red Snapper - Very Tasty!)
[//]: # ([NPC] Magistrix Erona)
[//]: # ([Spell][Mage] Fireball)
[//]: # ([Npc][Drop] Ghostclaw Lynx)
[//]: # ([Web] Armory doesnt work)
[//]: # (To find server revision type `.server info` command in the game chat.)

**Description**: We wiped on the first boss in normal Shadow Labs and then we attempt him again on second try but he was bugged unable to attack he was immune since has banish buff on him which it shouldn't be the case. 

**Current behaviour**: trashed is cleared and still has banish buff on Hellmaw 1st boss in Shadow labs

**Expected behaviour**: Banish removed after cleared trash in the room

**Server Revision**: 2749

**Comment by devo6969** [comment]
Could not recreate on the PTR. Fixed
