### ISSUE TITLE
[quest][smv] the cipher of damnation

### ISSUE THREAD

**Issue by teddys** [Atlantiss/NetherwingBugtracker#4772]
**Current behaviour**: http://db.hellfire-tbc.com/?quest=10588
after using the quest item, nothing happens

**Expected behaviour**: 
after using the quest item, the quest mob spawns
**Server Revision**: 2749

**Comment by Evolvee** [comment]
guldan was stuck in phase 2 for unknown reason, the event is working

we need to find out what made him to get stucked.

the event works like this:

1) guldan sets phase 2 (in this phase cyrukh cant be summoned again)
2) RP event plays out
3) player click on oronok to help with cyrukh
4) rp event plays out
5) cyrukh fights oronok
6) when cyrukh is killed oronok plays another RP
7) when this RP is finished, guldan sets to phase 1 where you can summon cyrukh again

now, someone had to either somehow delete oronok/make him stuck somewhere or there might be some issue with evade if noone helps oronok to fight cyrukh in phase 6) 

idk, and i cant fix until we find out

**Comment by Drayo** [comment]
Not really sure, but can Oronok die in the fight? Maybe that is what caused it?

**Comment by Evolvee** [comment]
he cannot currently as i didnt have any information on what should happen if he dies

if he died on NW, the event wouldnt be able to be completed and no cyrukh could be summoned ever until next restart

i added a timer that will make sure both npcs will despawn if there is noone attacking cyrukh for some time
