### ISSUE TITLE
[Talent][Paladin] Ardent defender

### ISSUE THREAD

**Issue by TincuAdrian** [Atlantiss/NetherwingBugtracker#4773]
**Current behaviour**:doesn`t work(proc)

**Expected behaviour**: should proc bellow 35% hp

**Comment by Tenoutoften** [comment]
This doesn't work? Do you have proof? It's insane if it doesn't...

**Comment by TincuAdrian** [comment]
[https://imgur.com/a/Obd7oZ3](url)

**Comment by TincuAdrian** [comment]
> This doesn't work? Do you have proof? It's insane if it doesn't... I wont be able to test this myself right now since I am holy

https://imgur.com/a/Obd7oZ3

**Comment by TincuAdrian** [comment]
ok i tested it out and it works but i doesn`t have a visual representation.

**Comment by Anselm123** [comment]
It never had a visual representation

**Comment by devo6969** [comment]
Seems to work fine on the PTR.
PTR - https://www.youtube.com/watch?v=G5dF9VOr_I0
