### ISSUE TITLE
[NPC] [Spell] Voidshrieker

### ISSUE THREAD

**Issue by AWIDIUS** [Atlantiss/NetherwingBugtracker#4774]
After Voidshrieker got hit by Seal of Blood (Holy) he activates 75% Holy damage reduction, but indeed I was able to damage him with Holy spells with no damage reduction. 
![image](https://user-images.githubusercontent.com/45521546/52162390-aa61c580-26d3-11e9-84af-2001f066c871.png)

**Comment by Tenoutoften** [comment]
Also affects a similar mob in Hellfire that I reported in phase 1/2
https://github.com/Atlantiss/NetherwingBugtracker/issues/2105

**Comment by Tereneckla** [comment]
Due to their nature of using the phys hit-table they seem to be treated as physical damage for this

**Comment by Godmatik** [comment]
Duplicate #3079
