### ISSUE TITLE
warlock pet disappears if unmount in combat

### ISSUE THREAD

**Issue by gefthi** [Atlantiss/NetherwingBugtracker#4775]
[//]: # (Enclose links to things related to the bug using http://wowhead.com or any other TBC database.)
[//]: # (You can use screenshot ingame to visual the issue.)
[//]: # (Write your tickets according to the format:)
[//]: # ([Quest][Azuremyst Isle] Red Snapper - Very Tasty!)
[//]: # ([NPC] Magistrix Erona)
[//]: # ([Spell][Mage] Fireball)
[//]: # ([Npc][Drop] Ghostclaw Lynx)
[//]: # ([Web] Armory doesnt work)
[//]: # (To find server revision type `.server info` command in the game chat.)

**Description**: 
If I unmount while I am in combat or initiate combat while I am mounted, the pet does not spawn
**Current behaviour**:
If I unmount while I am in combat or initiate combat while I am mounted, the pet does not spawn
**Expected behaviour**: 
The pet should appear when I amount either in combat or not
**Server Revision**:

**Comment by Easyfraggy** [comment]
From leveling 1-49 this does not happen to me ever.

**Comment by Tereneckla** [comment]
Fixed
