### ISSUE TITLE
[Spell][Warlock][Pet] Felhunter Tainted Blood not stacking

### ISSUE THREAD

**Issue by Jalapan** [Atlantiss/NetherwingBugtracker#4778]
[//]: # (Enclose links to things related to the bug using http://wowhead.com or any other TBC database.)
[//]: # (You can use screenshot ingame to visual the issue.)
[//]: # (Write your tickets according to the format:)
[//]: # ([Quest][Azuremyst Isle] Red Snapper - Very Tasty!)
[//]: # ([NPC] Magistrix Erona)
[//]: # ([Spell][Mage] Fireball)
[//]: # ([Npc][Drop] Ghostclaw Lynx)
[//]: # ([Web] Armory doesnt work)
[//]: # (To find server revision type `.server info` command in the game chat.)

**Description**: 
[Spell][Warlock][Pet] Felhunter Tainted Blood not stacking
**Current behaviour**:
[Spell][Warlock][Pet] Felhunter Tainted Blood not stacking
**Expected behaviour**: 
Should stack to 5x
**Server Revision**:

**Comment by Tereneckla** [comment]
Fixed

**Comment by kemotix** [comment]
Tainted Blood is somehow broken again.
Checked few minutes ago, not stacking at all in duel.
