### ISSUE TITLE
Thunder Learn cost

### ISSUE THREAD

**Issue by AWIDIUS** [Atlantiss/NetherwingBugtracker#4779]
Thunder learn costs 47g 50s. It should cost 9g 50s as other 350 recipes.
![image](https://user-images.githubusercontent.com/45521546/52164942-e27bff00-26f9-11e9-98c1-da393a6e2c08.png)
![image](https://user-images.githubusercontent.com/45521546/52164948-0ccdbc80-26fa-11e9-8cc5-68a05b4cdb80.png)

**Comment by Tenoutoften** [comment]
It should cost 9.5g? 
As far as I can tell it should be completely free:
[Wowhead comment, patch 2.0.6](https://www.wowhead.com/item=28440/thunder#comments:id=30937)
![](https://i.gyazo.com/5ee6633768ebc443b0a344653f4d05c9.png)

**Comment by AWIDIUS** [comment]
Well, maybe because we are on 2.0.3. patch :)

**Comment by AWIDIUS** [comment]
Even after that. 

By Sedis (103 – 1) on 2008/03/24 (Patch 2.3.3) |   |  
-- | -- | --

**Comment by teddys** [comment]
bump

**Comment by The14me** [comment]
bump

**Comment by Wolffenstein** [comment]
Fixed in rev 3484.
