### ISSUE TITLE
[Object][Chest] No loot

### ISSUE THREAD

**Issue by Thugli** [Atlantiss/NetherwingBugtracker#478]
[//]: # (Enclose links to things related to the bug using http://wowhead.com or any other TBC database.)
[//]: # (You can use screenshot ingame to visual the issue.)
[//]: # (Write your tickets according to the format:)
[//]: # ([Quest][Azuremyst Isle] Red Snapper - Very Tasty!)
[//]: # ([NPC] Magistrix Erona)
[//]: # ([Spell][Mage] Fireball)
[//]: # ([Npc][Drop] Ghostclaw Lynx)
[//]: # ([Web] Armory doesnt work)

**Description**: 
My group member and I have come across 2 chests (One in the barrens, and one in Stonetalon around 33,68 that had zero loot when opened. Upon opening the chests they instantly despawned. 

**Current behaviour**:
Occasionally chests out in the world seem to carry no loot and despawn once opened.

**Expected behaviour**: 
I'm not entirely sure if this is an issue with chest despawning or respawning, but chests should only be visible and lootable if they contain loot. 

**Server Revision**: 
rev: 2045

**Comment by bimbear** [comment]
Possible effect of #205

**Comment by samemari** [comment]
Confirm, tried twice chest at  Wetlands 13.5 41.4

Empty and disappears after opening, same thing with chest in Ashnevale in Greenpaw Village

**Comment by Sinyr** [comment]
Tried the chests at these 2 locations in Wetlands 2 times each (different days). Me and my buddy were the only players in the zone so they couldn't possibly be looted before hand, even so they should've despawned.
![screenshot_7](https://user-images.githubusercontent.com/9539181/46246207-3304e800-c3fa-11e8-8183-afc32ceb6ad4.png)
![screenshot_8](https://user-images.githubusercontent.com/9539181/46246208-3304e800-c3fa-11e8-8864-e8bbe7e2022a.png)

**Comment by Buggyswires** [comment]
Same with the chests in Brightwood Grove and The Darkened bank (Duskwood)

**Comment by Sinyr** [comment]
2 more empty chests in Ashenvale
![screenshot_11](https://user-images.githubusercontent.com/9539181/46256994-d9142900-c4b2-11e8-8594-cb58cb6be807.png)
![screenshot_12](https://user-images.githubusercontent.com/9539181/46256995-d9142900-c4b2-11e8-876b-d84810f4e3c2.png)

**Comment by Leksa88** [comment]
Can any1 confirm this happening to any other than Solid Chests? (Or a case of aSolid Chest actually working as expected)

**Comment by Sinyr** [comment]
There are some Solid Chests that work. But the problem is also that when you loot all the items from the chests sometimes it stays spawned but completely empty and doesn't despawn ever. This happens every time when in a party, but I think it can also happen when you're alone but I'm not sure.

**Comment by Dosdaltherir** [comment]
This issue persists. I've opened 2 chests today that were empty.

**Comment by Manaci** [comment]
Fixed
