### ISSUE TITLE
[MOBS] [INVALID RESPAWN]

### ISSUE THREAD

**Issue by Gedlund** [Atlantiss/NetherwingBugtracker#4780]
[//]: # (Enclose links to things related to the bug using http://wowhead.com or any other TBC database.)
[//]: # (You can use screenshot ingame to visual the issue.)
[//]: # (Write your tickets according to the format:)
[//]: # ([Quest][Azuremyst Isle] Red Snapper - Very Tasty!)
[//]: # ([NPC] Magistrix Erona)
[//]: # ([Spell][Mage] Fireball)
[//]: # ([Npc][Drop] Ghostclaw Lynx)
[//]: # ([Web] Armory doesnt work)
[//]: # (To find server revision type `.server info` command in the game chat.)

**Description**: 
Demon hunter supplicants and Demon hunter Initiates are currently not respawning as intended, nor is there enough of the mobs respawning even after waiting 30~~60 minutes.

**Current behaviour**:
This is what the respawn looks like after waiting 30-60 minutes.
![wowscrnshot_020219_151359](https://user-images.githubusercontent.com/32538827/52165170-7f8c6700-26fd-11e9-8dbf-e46669b662b7.jpg)

**Expected behaviour**: 
There is supposed to be a lot of mobs respawning in about 8-10 minutes time. 

References: 
https://www.youtube.com/watch?v=TN0B5Q5Nsgs
https://wow.zamimg.com/uploads/screenshots/normal/71623-demon-hunter-supplicant.jpg
https://wow.zamimg.com/uploads/screenshots/normal/715957-patio-de-armas-de-karabor.jpg

**Server Revision**:

**Comment by totaemoeggerli** [comment]
This issue is outdated. This is not what is happening currently on the server.

> Wolfenstein01/02/2019
> [2740][DB] Reduced respawn rate of Demon Hunter Supplicants

The issue has been created at a time when the respawn rate was changed to stop paladins from "abusing" it. However, the Demon Hunter Supplicants are respawning normally now (5min). The Demon Hunters Initiate aren't (7-8min).
