### ISSUE TITLE
Stats on items

### ISSUE THREAD

**Issue by xeall** [Atlantiss/NetherwingBugtracker#4781]
[//]: # (Enclose links to things related to the bug using http://wowhead.com or any other TBC database.)
[//]: # (You can use screenshot ingame to visual the issue.)
[//]: # (Write your tickets according to the format:)
[//]: # ([Quest][Azuremyst Isle] Red Snapper - Very Tasty!)
[//]: # ([NPC] Magistrix Erona)
[//]: # ([Spell][Mage] Fireball)
[//]: # ([Npc][Drop] Ghostclaw Lynx)
[//]: # ([Web] Armory doesnt work)
[//]: # (To find server revision type `.server info` command in the game chat.)

**Description**: 
Stats on certain items dont give the correct value. Here is a video of it https://www.twitch.tv/videos/373952164
**Current behaviour**:
Example ill show is the rings. Healing is 1558 when it should be 1578
**Expected behaviour**: 
it should not reset on every death or any related mechanic
**Server Revision**:

**Comment by Tenoutoften** [comment]
This has previously been reported in P2 https://github.com/Atlantiss/NetherwingBugtracker/issues/2779
I'd suggest to rename this issue to Enchant Ring - Healing stats reset on death or somethign similar rather than this vague stats on items which doesn't say anything specific about the issue

**Comment by Easyfraggy** [comment]
https://github.com/Atlantiss/NetherwingBugtracker/issues/2779
