### ISSUE TITLE
[NPC] Maiden of Virtue first Repentence didn't work

### ISSUE THREAD

**Issue by Mikik3jr** [Atlantiss/NetherwingBugtracker#4783]
[//]: # (Enclose links to things related to the bug using http://wowhead.com or any other TBC database.)
[//]: # (You can use screenshot ingame to visual the issue.)
[//]: # (Write your tickets according to the format:)
[//]: # ([Quest][Azuremyst Isle] Red Snapper - Very Tasty!)
[//]: # ([NPC] Magistrix Erona)
[//]: # ([Spell][Mage] Fireball)
[//]: # ([Npc][Drop] Ghostclaw Lynx)
[//]: # ([Web] Armory doesnt work)
[//]: # (To find server revision type `.server info` command in the game chat.)

**Description**: 
Maiden from time to time casts Repentence (in random interwalls). 

**Current behaviour**:
At the first cast I heard her line what she says at repentence, but nothing happened. The second one landed at 40%~ HP. Maybe Maiden used another spell at the same time and it interrupted the repentence:
![image](https://user-images.githubusercontent.com/43505031/52168856-ba0ef780-272f-11e9-9855-d45399469e03.png)
![image](https://user-images.githubusercontent.com/43505031/52168905-62bd5700-2730-11e9-991f-cb116c49f760.png)

**Expected behaviour**: 
It should go off anyway?

**Server Revision**: 
2749

**Comment by devo6969** [comment]
Tried to recreate on the PTR. Was not able to, seems fixed, everytime she did her dialogue should would cast Repentence.
