### ISSUE TITLE
[Dungeon] [Stratholme] Combat bug

### ISSUE THREAD

**Issue by Johra92** [Atlantiss/NetherwingBugtracker#4784]
[//]: # (Enclose links to things related to the bug using http://wowhead.com or any other TBC database.)
[//]: # (You can use screenshot ingame to visual the issue.)
[//]: # (Write your tickets according to the format:)
[//]: # ([Quest][Azuremyst Isle] Red Snapper - Very Tasty!)
[//]: # ([NPC] Magistrix Erona)
[//]: # ([Spell][Mage] Fireball)
[//]: # ([Npc][Drop] Ghostclaw Lynx)
[//]: # ([Web] Armory doesnt work)
[//]: # (To find server revision type `.server info` command in the game chat.)

**Description**: 
I get stuck in combat when hitting ghosts in the dungeon with aoe (the neutral ghosts that walk around the dungeon). They  seem to heal passively, and dont attack u when being hit by aoe, but they do put in combat until you zone out of the dungeon. 
**Current behaviour**:
I get stuck in combat when hitting ghosts in the dungeon with aoe (the neutral ghosts that walk around the dungeon) Picture below of an example of the type of mob Im talking about; 
![image](https://user-images.githubusercontent.com/45569791/52169759-fa757200-273d-11e9-9250-823dc7c2f945.png)

**Expected behaviour**: 
When ghosts or any other mob are hit by your aoe dmg they aggro on to you and fight you until either of you die, and after it releases u from combat. 
**Server Revision**: 
2749

**Comment by Johra92** [comment]
When u do /dance on them the combat drops! Learned from a guildmate :D

**Comment by Johra92** [comment]
okey, either that was a one time wonder... or its not actually working : / I cant reproduce the /dance to drop combat... Im back to square one.

**Comment by Unfairy** [comment]
Confirm. Combat bug in undead part and probably in live triggering by agroe-ing Invisible Shades. Killing them not making you leave combat, Fix please.

**Comment by Xaero252** [comment]
Confirming, any time you enter combat with Eye of Naxxramas (the shade NPCs) you will be permanently combat bugged until either dying or closing the game.
After closing the game you will be dead at the graveyard and have to walk back.

**Comment by Tenoutoften** [comment]
That is incorrect @Xaero252 
You will only remain in combat if you let the Eye of Naxxramas complete it's summon spell because it summons bats below the ground(I think). Killing it before it summons will allow you to escape this bug.

**Comment by Godmatik** [comment]
Got fixed when Wolf revamped the dungeon last year.

Closing
