### ISSUE TITLE
druid quest - toxic test 

### ISSUE THREAD

**Issue by bearlygood** [Atlantiss/NetherwingBugtracker#4785]
[//]: # (Enclose links to things related to the bug using http://wowhead.com or any other TBC database.)
[//]: # (You can use screenshot ingame to visual the issue.)
[//]: # (Write your tickets according to the format:)
[//]: # ([Quest][Azuremyst Isle] Red Snapper - Very Tasty!)
[//]: # ([NPC] Magistrix Erona)
[//]: # ([Spell][Mage] Fireball)
[//]: # ([Npc][Drop] Ghostclaw Lynx)
[//]: # ([Web] Armory doesnt work)
[//]: # (To find server revision type `.server info` command in the game chat.)

**Description**: The Druid quest - "Toxic Test" is not working as devilsaurs in un'goro are not spawning at all.

**Current behaviour**: impossible to finish the quest as there are no devilsaurs at all on the map.

**Expected behaviour**: being able to find devilsaurs on the map.

**Server Revision**:

**Comment by eryczek1615** [comment]
I did this q but found only King Mosh.

**Comment by leeviathan** [comment]
There are still no devilsaurs in Ungoro other than king mosh

**Comment by duzyizly** [comment]
they exist on ptr 3404 but stacking ; (
not sure about live version

![WoWScrnShot_062320_224723](https://user-images.githubusercontent.com/43931626/85460480-9312c900-b5a3-11ea-9f5a-d8fe757036f5.jpg)
![WoWScrnShot_062320_224737](https://user-images.githubusercontent.com/43931626/85460487-9443f600-b5a3-11ea-85b9-e4d4ec0a7f40.jpg)

**Comment by Wolffenstein** [comment]
Fixed in rev 3405.
