### ISSUE TITLE
[SPELL] Shields (Ice barrier)

### ISSUE THREAD

**Issue by Mewmewww** [Atlantiss/NetherwingBugtracker#4787]
[//]: # (Enclose links to things related to the bug using http://wowhead.com or any other TBC database.)
[//]: # (You can use screenshot ingame to visual the issue.)
[//]: # (Write your tickets according to the format:)
[//]: # ([Quest][Azuremyst Isle] Red Snapper - Very Tasty!)
[//]: # ([NPC] Magistrix Erona)
[//]: # ([Spell][Mage] Fireball)
[//]: # ([Npc][Drop] Ghostclaw Lynx)
[//]: # ([Web] Armory doesnt work)
[//]: # (To find server revision type `.server info` command in the game chat.)

**Description**: 
Shields such as Ice barrier or Power Word: Shield causes threat.  https://www.wowhead.com/spell=11426/ice-barrier#comments
**Current behaviour**:
Shields such as Ice barrier or Power Word: Shield causes threat.  https://www.wowhead.com/spell=11426/ice-barrier#comments
**Expected behaviour**: 
Should not be causing threat: https://www.wowhead.com/spell=11426/ice-barrier#comments
**Server Revision**: 
2149

**Comment by Tenoutoften** [comment]
Doesn't have those attributes on TBC database
https://db.excalibur.ws/?spell=11426

I think it might be better if you provide omen evidence instead of Spell info from Battle for Azeroth...

**Comment by Godmatik** [comment]
All my research from classic indicates that popping both ice barrier and power:word shield properly generates threat in TBC.

Not a bug.
