### ISSUE TITLE
The Tome of Valor

### ISSUE THREAD

**Issue by AeoxNW** [Atlantiss/NetherwingBugtracker#4788]
[//]: # (Enclose links to things related to the bug using http://wowhead.com or any other TBC database.)
[//]: # (You can use screenshot ingame to visual the issue.)
[//]: # (Write your tickets according to the format:)
[//]: # ([Quest][Azuremyst Isle] Red Snapper - Very Tasty!)
[//]: # ([NPC] Magistrix Erona)
[//]: # ([Spell][Mage] Fireball)
[//]: # ([Npc][Drop] Ghostclaw Lynx)
[//]: # ([Web] Armory doesnt work)
[//]: # (To find server revision type `.server info` command in the game chat.)

**Description**:  On the Westfall phase of the Tome of Valor paladin quest Daphne Stilwell should patrol the farm and orchard and give the next breadcrumb quest.

**Current behaviour**: Daphne does not spawn.

**Expected behaviour**: Daphne should spawn and defend the farm from defias.

**Server Revision**:  2749

**Comment by Fuzedknight** [comment]
She is instantly spawning and despawning every 50 seconds around her farm.

**Comment by Tereneckla** [comment]
707 <---
