### ISSUE TITLE
[Quest][The Barrens]Wanted poster incorrect

### ISSUE THREAD

**Issue by mbzz88** [Atlantiss/NetherwingBugtracker#479]
**Description**: The WANTED poster for the quest WANTED: Baron Longshore https://vanilla-twinhead.twinstar.cz/?quest=895 has the loots sparkles animation instead of a yellow exclamation point.

**Current behaviour**: ![wowscrnshot_092518_163508](https://user-images.githubusercontent.com/43509267/45993146-6c2f1680-c0e1-11e8-97ca-f07f2f872b6e.jpg)

**Expected behaviour**:  Yellow exclamation point (or nothing, I don't remember when wanted poster ! were added)

**Comment by Kidcudi123** [comment]
That sounds retail

**Comment by Shanghi** [comment]
You're too high of a level so the exclamation mark isn't shown anymore. It will stop after level 20. It's possible that there's a problem with how it decides when to stop showing it (<https://github.com/Atlantiss/NetherwingBugtracker/issues/1068>). That needs more research though and it's a global thing so if it's changed then this one will be changed too, so I'll close this one.
