### ISSUE TITLE
Freezing trap, target resist it but there is no text over target.

### ISSUE THREAD

**Issue by dalabu** [Atlantiss/NetherwingBugtracker#4790]
**Description**:  When target resists freezing trap, there is no "RESIST" text over target.

**Current behaviour**:  https://streamable.com/onhjn

**Expected behaviour**: When target does resist the trap there should be "RESIST" text over target.

**Server Revision**:  2749

**Comment by knasen88** [comment]
blizzard ingame sct is a bit wonky, what did the combat log say?

**Comment by Zarant** [comment]
Combat log doesn't show anything when traps resist
