### ISSUE TITLE
[SMV] Sunfury Warlock - too many spawns

### ISSUE THREAD

**Issue by Azalen** [Atlantiss/NetherwingBugtracker#4792]
**Description**: 
http://tbc.cavernoftime.com/npc=21503

**Current behaviour**:
10 spawns on the same position.
![wowscrnshot_020319_005916](https://user-images.githubusercontent.com/20336567/52170680-19c8cb00-274f-11e9-9c20-fd00537de4f4.jpg)

Issue most likely related to the event regarding this item: https://www.wowhead.com/item=30811/scroll-of-demonic-unbanishing

**Expected behaviour**: 
1 spawn at the same position

**Server Revision**: 
[2749]

**Comment by Tenoutoften** [comment]
https://github.com/Atlantiss/NetherwingBugtracker/issues/4206

**Comment by AWIDIUS** [comment]
![image](https://user-images.githubusercontent.com/45521546/52174043-b068ac80-278e-11e9-90c2-f4d4358e0c20.png)

**Comment by ScottieDOESknow** [comment]
3 weeks later and this quest still spawning duplicate NPC

![image](https://user-images.githubusercontent.com/43949261/52509581-b6afbc00-2bc6-11e9-9ab1-58a854d2e0df.png)

Any idea on a fix? This is a required prequest for the Aldor/Scryer long questline.

![image](https://user-images.githubusercontent.com/43949261/52509884-db586380-2bc7-11e9-85ba-855aaf31fffe.png)

**Comment by pelekon** [comment]
fixed in rev 2781
