### ISSUE TITLE
Weapon Skills - Fist Weapons - Not increasing unarmed skill

### ISSUE THREAD

**Issue by Zerowbe** [Atlantiss/NetherwingBugtracker#4795]
**Description**: 
Notice, I saw the closed issue #4782 however, I am experiencing this bug. The unarmed weapon skill is not increasing when I am using a fist weapon. 
**Current behaviour**:
When using fist weapons, unarmed skill level does not increase. 
**Expected behaviour**: 
Unarmed skill should increase when hitting a mob with a fist weapon equipped.
**Server Revision**: 
2749  Hash:54ae327r5363

**Comment by Wolffenstein** [comment]
The fix is not live yet.
