### ISSUE TITLE
Lifebloom Last tick bug

### ISSUE THREAD

**Issue by wapomani** [Atlantiss/NetherwingBugtracker#4796]
[//]: # (Enclose links to things related to the bug using http://wowhead.com or any other TBC database.)
[//]: # (You can use screenshot ingame to visual the issue.)
[//]: # (Write your tickets according to the format:)
[//]: # ([Quest][Azuremyst Isle] Red Snapper - Very Tasty!)
[//]: # ([NPC] Magistrix Erona)
[//]: # ([Spell][Mage] Fireball)
[//]: # ([Npc][Drop] Ghostclaw Lynx)
[//]: # ([Web] Armory doesnt work)
[//]: # (To find server revision type `.server info` command in the game chat.)

**Description**:  Druid lifebloom is supposed to stack 3 times the final tick also stacks and get amplified

**Current behaviour**: it does not increase healing even if you have 3 stacks on the final bloom and only works on the hot

**Expected behaviour**:  the final blooms should be increased in the same amount as the hot

**Server Revision**:

**Comment by Dusky1** [comment]
No ? The final bloom should allways be the same.

**Comment by Crusaderz** [comment]
@wapomani watch any TBC druid video, last bloom is always the same, regardless stack amounts

**Comment by Tenoutoften** [comment]
Invalid

**Comment by devo6969** [comment]
They made that change in WOTLK when the increase of stacks would increase the final heal

https://wowwiki.fandom.com/wiki/Lifebloom#:~:text=Lifebloom%20is%20a%20druid%20heal,and%20immediately%20heal%20the%20target.
Patch 2.1.0 (22-May-2007): Each additional application of this spell will now include the full bonus from effects which increase healing. The final heal, however, is still unaffected by stacking multiple applications of this spell.

 Patch 3.1.0 (14-Apr-2009): Mana cost of all ranks doubled. When Lifebloom blooms or is dispelled, it now refunds half the base mana cost of the spell per application of Lifebloom, and the heal effect is multiplied by the number of applications. Corrected some bugs with the new blooming functionality and dispels.
