### ISSUE TITLE
[NPC] Typo in Willix the Importer's speech

### ISSUE THREAD

**Issue by Spaztick** [Atlantiss/NetherwingBugtracker#4797]
**Description**: 
Typo in Willix the Importer's speech has a typo.
**Current behaviour**:
Ennemy
**Expected behaviour**: 
Should be spelled Enemy.
**Server Revision**: 
2749

![typo](https://user-images.githubusercontent.com/29140342/52174759-328cad00-275e-11e9-8efb-e36faf88fb14.png)

**Comment by Evolvee** [comment]
rev 2769
