### ISSUE TITLE
[Spell][Warlock] Inferno

### ISSUE THREAD

**Issue by kuroda72** [Atlantiss/NetherwingBugtracker#4798]
**Description**: 
The spell Inferno, for Warlocks, quest acquired at level 50 summons an Infernal that is outside of player control, and consistently from level to level, comes out at level 66.

**Current behaviour**:
Summons hostile infernal outside of player control, level 66 regardless of player level.

**Expected behaviour**: 
Infernal summoned should be player level, and under warlock control for 5 minutes without resistance chance associated with Enslave Demon spell, until duration expires, where it should be enslavable by said spell.

**Server Revision**: 
2749

**Comment by Dimbleglim** [comment]
I have the exact same issue. The infernal is immune to enslave demon as well.

**Comment by Noephix** [comment]
Issue still present - lvl 66 infernal, immune to enslavement.

**Comment by Teakane** [comment]
Can confirm this is still present as of current date, exactly in the state described in the OP

**Comment by Luny12345** [comment]
The stun also affects allies when it should only affect enemies.

**Comment by tetsugoro** [comment]
Can confirm that this still behaves exactly as OP describes

**Comment by kramnoitseuq** [comment]
@Wolffenstein @Evolvee BUMP

**Comment by kramnoitseuq** [comment]
@Wolffenstein

**Comment by donatello4k** [comment]
Hello @Wolffenstein Can you please fix this? Huge 1 hour cooldown currently 100% unavailable for warlocks. Infernal should be level 70, under warlock's control for 5 minute without breaking. Should also be enslaveable when the 5 minutes run out.

**Comment by Wolffenstein** [comment]
Fixed in rev 3078.
