### ISSUE TITLE
[NPC][Mosshoof Courser] This mob doesn't exist in Azshara...

### ISSUE THREAD

**Issue by fishworld** [Atlantiss/NetherwingBugtracker#4799]
**Current behaviour**:

I cant find these anywhere in Azshara. You need them for the lvl 50 hunter quest.

**Expected behaviour**: 

They should exist just like any other mob in Azshara. 

**Server Revision**:

**Comment by fishworld** [comment]
Edit: I've found one in the entire zone after searching for hours

**Comment by Evolvee** [comment]
pooled with thunderhead skystormed
