### ISSUE TITLE
[Quest

### ISSUE THREAD

**Issue by deku100** [Atlantiss/NetherwingBugtracker#480]
[//]: # (Enclose links to things related to the bug using http://wowhead.com or any other TBC database.)
[//]: # (You can use screenshot ingame to visual the issue.)
[//]: # (Write your tickets according to the format:)
[//]: # ([Quest][Azuremyst Isle] Red Snapper - Very Tasty!)
[//]: # ([NPC] Magistrix Erona)
[//]: # ([Spell][Mage] Fireball)
[//]: # ([Npc][Drop] Ghostclaw Lynx)
[//]: # ([Web] Armory doesnt work)

**Description**: [Quest] Journey to Undercity

**Current behaviour**: After turning in quest, the emote the occurs after the turn in does not properly display Sylvannas as the subject (see chat log).
![wowscrnshot_092518_004203](https://user-images.githubusercontent.com/43505181/45993448-0bf69100-c05d-11e8-8716-a41a36c62ed5.jpg)

**Expected behaviour**:  Sylvannas kneels and picks up the amulet.

**Server Revision**:

**Comment by The14me** [comment]
You sure isnt a addon issue?

**Comment by aresbrutus** [comment]
Confirmed. 

https://github.com/Atlantiss/AtlantissTBCBT/issues/451

**Comment by Kiperr** [comment]
` UPDATE `script_texts` SET `content_default` = '%s kneels down and pick up the amulet.' WHERE `entry` = -1000358; `

**Comment by Evolvee** [comment]
rev xdd
