### ISSUE TITLE
[Quest][Azshara] Kim'jael Indeed!

### ISSUE THREAD

**Issue by fishworld** [Atlantiss/NetherwingBugtracker#4800]
https://vanilla-twinhead.twinstar.cz/?quest=3601

**Current behaviour**:

When you try to loot some boxes that are empty they don't respawn. Only 3-4 boxes of a total of ~10 have loot in them and respawn. 

**Expected behaviour**: 

Even if a box is empty they should disappear and respawn eventually. 

**Server Revision**:

**Comment by danbopes** [comment]
Dupe of #4719
