### ISSUE TITLE
Switching Alchemy Specialization Not Working As Intended

### ISSUE THREAD

**Issue by DevlinNW** [Atlantiss/NetherwingBugtracker#4801]
**Description**: 
I learned Potion Mastery (quest: http://db.hellfire-tbc.com/?quest=10897) by completing the quest about 10-12 days ago, and immediately unlearned it from the Potion Master in Zangarmarsh for a fee of 150g. I then traveled to Stormspire to speak with the Transmutation Master there, and learned Transmutation Mastery free of charge and without completing the Transmutation Mastery quest. This was confirmed by a yellow text along the lines of "You have learned Transmutation Mastery." and I didn't think more of the matter.
After doing transmutes, with no lucky x2, x3 or x4, for a week or so, I was getting suspicious and tried looking in my spellbook. I saw that it still said Potion Master there.

Here are 2 screenshots that show the problem in more detail:
https://cdn.discordapp.com/attachments/538400921072435211/539837783364206625/unknown.png
https://cdn.discordapp.com/attachments/538400921072435211/539837889547075586/unknown.png
As you can see, I have the option to unlearn Transmutation Mastery, even though I am still a Potion Master. 

**Current behaviour**:
Am still a Potion Master

**Expected behaviour**: 
After paying the fee to unlearn Potion Mastery and subsequently learning Transmutation Mastery, I ought to have Transmutation Mastery in my spellbook and not Potion Mastery.

**Server Revision**: 
2749

**Comment by naekobest** [comment]
Can confirm with multiple times. Talked to diff. trans. masters who also got the same issue. 

Please get onto this asap, somewhat major tbh.

**Comment by Sixoo** [comment]
Confirmed too, stuck with potion mastery.
Lost 150G in the process too, GM does not restore gold, in any case.
Need a fix ( and the gold back please lol)

**Comment by Tereneckla** [comment]
Fixed
