### ISSUE TITLE
Cant send items via mail

### ISSUE THREAD

**Issue by HHElle** [Atlantiss/NetherwingBugtracker#4802]
[//]: # (Enclose links to things related to the bug using http://wowhead.com or any other TBC database.)
[//]: # (You can use screenshot ingame to visual the issue.)
[//]: # (Write your tickets according to the format:)
[//]: # ([Quest][Azuremyst Isle] Red Snapper - Very Tasty!)
[//]: # ([NPC] Magistrix Erona)
[//]: # ([Spell][Mage] Fireball)
[//]: # ([Npc][Drop] Ghostclaw Lynx)
[//]: # ([Web] Armory doesnt work)
[//]: # (To find server revision type `.server info` command in the game chat.)

**Description**: 

**Current behaviour**:

**Expected behaviour**: 

**Server Revision**:

**Comment by HHElle** [comment]
HI! I cant send items to my alt toon via mail. The items stay in my inventory but they get the postal fee :(

**Comment by WarriorTSW** [comment]
/rl to reload ui. works as a fix for me every time.

**Comment by HHElle** [comment]
Doesnt working. I tried more times, just loose money. After relog, after total relog, doesnt working. Anc cant send anything to anyone. Not for my alt, not for my friends alt... just waste money :(

**Comment by HHElle** [comment]
okay, my postal addon was the bad. I disabled and now I can mail.

**Comment by lyons7486** [comment]
Can comfirm that postal is somehow stealing money, if you send any money it takes it as well and the postal cost.
