### ISSUE TITLE
[Spell][Hunter] Enemy trap is not visible when placed right in front of you

### ISSUE THREAD

**Issue by Crusaderz** [Atlantiss/NetherwingBugtracker#4803]
Trap placed by enemy hunter when you near him is invisible. 

Should be visible:
https://youtu.be/cKuQ-CSBFRY?t=82
https://youtu.be/Ok3hD-_Zuno?t=477
https://youtu.be/Ok3hD-_Zuno?t=726
https://youtu.be/UfLdDK5ZEn4?t=120
https://youtu.be/NRHY2VMb5lw?t=53
https://youtu.be/aQaDj1K2Irg?t=246
https://youtu.be/av045DrYxqg?t=160
https://youtu.be/AZdd9gmrOAY?t=139
https://youtu.be/AZdd9gmrOAY?t=215
https://youtu.be/uyg24LUc9cQ?t=226
https://youtu.be/msGVmXKFanM?t=109

**Comment by The14me** [comment]
Rev.3483 its more than visible now.
