### ISSUE TITLE
[NPC] Astral Flare has no model

### ISSUE THREAD

**Issue by Mikik3jr** [Atlantiss/NetherwingBugtracker#4804]
[//]: # (Enclose links to things related to the bug using http://wowhead.com or any other TBC database.)
[//]: # (You can use screenshot ingame to visual the issue.)
[//]: # (Write your tickets according to the format:)
[//]: # ([Quest][Azuremyst Isle] Red Snapper - Very Tasty!)
[//]: # ([NPC] Magistrix Erona)
[//]: # ([Spell][Mage] Fireball)
[//]: # ([Npc][Drop] Ghostclaw Lynx)
[//]: # ([Web] Armory doesnt work)
[//]: # (To find server revision type `.server info` command in the game chat.)

**Description**: 
In Karazhan Curator spawns Astral Flares.

**Current behaviour**:
They don't have any model. Only visible with nameplates.

**Expected behaviour**: 
I think they should be visible? I went through from patch 2.0.1 to 2,4,3 and the [patch notes](https://wow.gamepedia.com/Patch_2.0.1) did not say anything about the Astral Flares, while in [this video ](https://www.youtube.com/watch?v=BFqwYviIF34) it clearly can be seen that flares have that sparking model. So if they are not supposed to have model, then the video wouldn't show them, or if they gained model after a patch then it should be included in the patch notes.

**Server Revision**: 
2749

**Comment by Tenoutoften** [comment]
There are lots of changes not included in the patch notes

Anyway I found it interesting to see how much less damage this boss is doing compared to NW. Perhaps it has something to do with how frequency they do the shocks?

The NW version of [[NPC]Arcatraz Sentinel#21586](https://db.excalibur.ws/?npc=21586) spams energy discharge to the point where I have to chain holy light our tank until it's dead, and I am out gearing this dungeon by quite a lot.
