### ISSUE TITLE
[NPC][Ability][Dungeon] Coilfang Enchantress (Lightning Cloud)

### ISSUE THREAD

**Issue by AxeCell** [Atlantiss/NetherwingBugtracker#4805]
**Description**: 
Topic is related to the Lightning Cloud ability of the Coilfang Enchantress NPC found within Slave Pens heroic.

**Current behaviour**:
The Lightning Cloud ability does about 350 damage each tick. It feels extremely underwhelming to say the least and in return it doesn't pose any threat. Comparing this to any other aoe ability found in any other heroic makes the damage feel out of place.

**Expected behaviour**: 
I didn't find any sources on the 2.0 blizzlike values, but I thought the damage was low enough to warrant a report.

**Server Revision**: 
2749

**Comment by Evolvee** [comment]
spell ids are correct

**Comment by devo6969** [comment]
Found some videos but i always see people standing it, can't make out numbers though... see some "273,443" but can't tell if its from Lighting Cloud or not. 
Retail TBC - https://youtu.be/NtoUX3-SmVo?t=203

**Comment by The14me** [comment]
As Evolvee says....not an issue.
https://www.wowhead.com/spell=32193/lightning-cloud
spell ID and dmg tooltip is correct according to Wowhead.
