### ISSUE TITLE
Purchased weapon off AH and didn't receive it (NOT mail bug)

### ISSUE THREAD

**Issue by ChoppedWell** [Atlantiss/NetherwingBugtracker#4807]
[//]: # (Enclose links to things related to the bug using http://wowhead.com or any other TBC database.)
[//]: # (You can use screenshot ingame to visual the issue.)
[//]: # (Write your tickets according to the format:)
[//]: # ([Quest][Azuremyst Isle] Red Snapper - Very Tasty!)
[//]: # ([NPC] Magistrix Erona)
[//]: # ([Spell][Mage] Fireball)
[//]: # ([Npc][Drop] Ghostclaw Lynx)
[//]: # ([Web] Armory doesnt work)
[//]: # (To find server revision type `.server info` command in the game chat.)

**Description**: 
Purchased a weapon off the AH and didnt receive it. even logged out for mail bug possibility
**Current behaviour**:
Busted
**Expected behaviour**: 
Busted
**Server Revision**: 
Busted

**Comment by Tereneckla** [comment]
rev 3058
