### ISSUE TITLE
Dying from duel (Same Faction)

### ISSUE THREAD

**Issue by Thugli** [Atlantiss/NetherwingBugtracker#481]
[//]: # (Enclose links to things related to the bug using http://wowhead.com or any other TBC database.)
[//]: # (You can use screenshot ingame to visual the issue.)
[//]: # (Write your tickets according to the format:)
[//]: # ([Quest][Azuremyst Isle] Red Snapper - Very Tasty!)
[//]: # ([NPC] Magistrix Erona)
[//]: # ([Spell][Mage] Fireball)
[//]: # ([Npc][Drop] Ghostclaw Lynx)
[//]: # ([Web] Armory doesnt work)

**Description**: 
While dueling a member of the same faction, I died as I lost the duel.

**Current behaviour**:
Video can be seen here:
https://clips.twitch.tv/SquareZanySquirrelChocolateRain

![untitled](https://user-images.githubusercontent.com/37326256/45993366-a4404600-c05c-11e8-8b38-449940c90b83.png)

**Expected behaviour**: 
Players should not die from duels.

**Server Revision**:
Rev: 2045

**Comment by The14me** [comment]
Wa fixed long time a go.Please re-open if still happen.
