### ISSUE TITLE
Don't Kill the Fat One

### ISSUE THREAD

**Issue by Fuzedknight** [Atlantiss/NetherwingBugtracker#4811]
**Description**: The quest involved beating on an ogre until he turns green and you can talk to him.

**Current behaviour**: Unkor is not turning green and is instead fighting until dying, I tried this twice with the same result making the quest and it's large chain impossible to complete. https://puu.sh/CGJSy/d357e17990.png

**Expected behaviour**: Unkor should turn green at low health allowing you to talk to him.

**Server Revision**: 2756

**Comment by Fuzedknight** [comment]
Update: Apparently he will only turn green once you have killed all 10 of the required ogres. I don't know if this is intended or not.

**Comment by Tenoutoften** [comment]
Invalid, please close
https://www.wowhead.com/quest=9889/dont-kill-the-fat-one#comments:id=15121:reply=36684
