### ISSUE TITLE
[Raid][SSC][NPC] Leotheras the Blind Text/Encounter issues.

### ISSUE THREAD

**Issue by Imbaslap** [Atlantiss/NetherwingBugtracker#4812]
[//]: # (Enclose links to things related to the bug using http://wowhead.com or any other TBC database.)
[//]: # (You can use screenshot ingame to visual the issue.)
[//]: # (Write your tickets according to the format:)
[//]: # ([Quest][Azuremyst Isle] Red Snapper - Very Tasty!)
[//]: # ([NPC] Magistrix Erona)
[//]: # ([Spell][Mage] Fireball)
[//]: # ([Npc][Drop] Ghostclaw Lynx)
[//]: # ([Web] Armory doesnt work)
[//]: # (To find server revision type `.server info` command in the game chat.)

**Description**: 
Compilation of issues that do not sync up with DBM addon and missing certain RP events/texts during the fight.
**Current behaviour**:
1) Does not Emote text during transition from human form to Demon form.
2) during the low HP split where both human and demon form come out, Leo kneels for 1 second then attacks a player. it takes about 10 seconds before the Demon form appears and begins engaging the raid.
**Expected behaviour**: 
1) when transitioning from human form to demon form, Leo should Emote-  Leotheras the Blind yells: Be gone, trifling elf.  I am in control now! 
2) during the low HP split, the demon is supposed to spawn as soon as Leo finish's kneeling/emote text.

**Server Revision**: 
Sources: 
https://www.youtube.com/watch?v=HnDQi2RCkSE
https://youtu.be/8SWVNk-KfUI?t=449

**Comment by Wolffenstein** [comment]
Fixed in rev 2763.
