### ISSUE TITLE
[NPC] Berthold should not have the teleport gossip option to Shade of Aran's room until 2.0.7

### ISSUE THREAD

**Issue by Mikik3jr** [Atlantiss/NetherwingBugtracker#4813]
[//]: # (Enclose links to things related to the bug using http://wowhead.com or any other TBC database.)
[//]: # (You can use screenshot ingame to visual the issue.)
[//]: # (Write your tickets according to the format:)
[//]: # ([Quest][Azuremyst Isle] Red Snapper - Very Tasty!)
[//]: # ([NPC] Magistrix Erona)
[//]: # ([Spell][Mage] Fireball)
[//]: # ([Npc][Drop] Ghostclaw Lynx)
[//]: # ([Web] Armory doesnt work)
[//]: # (To find server revision type `.server info` command in the game chat.)

**Description**: 
If you kill Shade of Aran a gossip option appear for Berthold which teleports you to Shade of Aran's room.

**Current behaviour**:
It is in the game.

**Expected behaviour**: 
This should not be here, because the server is in 2.0.3, and this option comes in in 2.0.7.
["Berthold the Doorman will now have a gossip option to teleport players to the Shade of Aran's room. This gossip option only becomes available when players have defeated the Shade of Aran."](https://wow.gamepedia.com/Patch_2.0.7)

**Server Revision**: 
2756

**Comment by Brasso** [comment]
I believe we are in 2.0.x not specifically 2.0.3.

**Comment by Mikik3jr** [comment]
We are in 2.0.3

![image](https://user-images.githubusercontent.com/43505031/52183379-99b26c00-2807-11e9-85f8-3edce23fc3be.png)

**Comment by Jseay1313** [comment]
what a rat

**Comment by naekobest** [comment]
what a rat

**Comment by Brasso** [comment]
Well, itemization is 2.0.x and they have taken some liberty with alchemy respec which was introduced in 2.1, they also never introduced 2.0 5 socket meta gems. Unnecessary change.

**Comment by Mikik3jr** [comment]
Read again: PvE and World Content is 2.0.3. If you can respec alchemy, than that should be reported as well.

**Comment by efagrgagg** [comment]
ok but first patch they will do to server is 2.1 and teleport was added before that

**Comment by naekobest** [comment]
There is nothing to report about the alchemy respec since it’s what they did intentionally. 

This legit is an unnecessary change which dumbs down the whole run in kara. 

You should rather focus on important things rather than what you are seeing in someone’s stream. 

“But muh blizzlike server:(((“

**Comment by Wolffenstein** [comment]
Not going to be changed.

**Comment by Mikik3jr** [comment]
@naekobest Arcane Watchers respawn timer is on 30min, and that is 2.0.3 value. It was increased in 2.0.8, but I think you don't have problem with this. I thought since we really stick for the 2.0.3 values, then I report this too.
