### ISSUE TITLE
[Raid][SSC][Object] Strange pool Not behaving accurately.

### ISSUE THREAD

**Issue by Imbaslap** [Atlantiss/NetherwingBugtracker#4814]
[//]: # (Enclose links to things related to the bug using http://wowhead.com or any other TBC database.)
[//]: # (You can use screenshot ingame to visual the issue.)
[//]: # (Write your tickets according to the format:)
[//]: # ([Quest][Azuremyst Isle] Red Snapper - Very Tasty!)
[//]: # ([NPC] Magistrix Erona)
[//]: # ([Spell][Mage] Fireball)
[//]: # ([Npc][Drop] Ghostclaw Lynx)
[//]: # ([Web] Armory doesnt work)
[//]: # (To find server revision type `.server info` command in the game chat.)

**Description**: 
The Strange Pool only takes 1 cast to fish up The lurker below and the strange pool respawns after the Lurker below is killed on a soft reset of the instance. 
**Current behaviour**:
The Strange Pool only takes 1 cast to fish up The lurker below and the strange pool respawns after the Lurker below is killed on a soft reset of the instance. 
**Expected behaviour**: 
1) The Strange pool should not respawn after the Lurker Below is killed.
2) it should take about 1-60 casts to fish up the Lurker below with 250+ fishing skill. the fisher should also receive loot when fishing in the Strange Pool. (greater sagefish etc) 
**Server Revision**: 
Sources:
https://www.wowhead.com/npc=21217/the-lurker-below#comments
https://www.wowhead.com/object=184845/strange-pool

**Comment by Wolffenstein** [comment]
Fixed in rev 2763.

**Comment by Frankenberryberry** [comment]
This is not in any way fixed. It takes waaaaaaaaay to long.
I raided in TBC and we never had more than 2-3 people fishing and it never took more than 2 minutes or so to catch him.
So far it has taken us 12 minutes on this try to catch him. The chance of him spawning is way to low.
