### ISSUE TITLE
Mana Tombs HC - Tavarok

### ISSUE THREAD

**Issue by femdead** [Atlantiss/NetherwingBugtracker#4816]
Boss corpse despawns within 1-2 minutes of killing him, should not despawn faster than normal mobs (missed out on mining him after figuring out which party members were miners)

Also doesn't seem to use his Arcing Smash which makes the fight trivial

**Comment by Tenoutoften** [comment]
He definitely uses his Arcing Smash

**Comment by devo6969** [comment]
15 mins with loot on him, didn't despawn. Looted him, waited another 13 mins, still didn't despawn. Seems fine
