### ISSUE TITLE
[NPC][Hunter] Stable Master deleting pets

### ISSUE THREAD

**Issue by ZhengSim** [Atlantiss/NetherwingBugtracker#4817]
[//]: # (Enclose links to things related to the bug using http://wowhead.com or any other TBC database.)
[//]: # (You can use screenshot ingame to visual the issue.)
[//]: # (Write your tickets according to the format:)
[//]: # ([Quest][Azuremyst Isle] Red Snapper - Very Tasty!)
[//]: # ([NPC] Magistrix Erona)
[//]: # ([Spell][Mage] Fireball)
[//]: # ([Npc][Drop] Ghostclaw Lynx)
[//]: # ([Web] Armory doesnt work)
[//]: # (To find server revision type `.server info` command in the game chat.)

**Description**: As described in ( https://github.com/Atlantiss/NetherwingBugtracker/issues/1187 ) stable masters don't show your current pet if they're dismissed or you're on a mount. If you then drag one of the stabled pets into your empty current pet tab, it will duplicate the stabled one and overwrite your actual current pet, deleting it in the process. This bug is reproducible. Video proof: https://streamable.com/dz11l

**Current behaviour**: It doesn't show your current pet if it's dismissed or on a mount, will delete pet if you put out another from from stable.

**Expected behaviour**: Obviously shouldn't be possible to lose pets this way.

**Server Revision**: 2756

**Comment by Falathrin** [comment]
Just happened to me. It's really frustrating.

**Comment by Zarant** [comment]
Issue seems partially fixed, still occurs when you manually dismiss your pet and relog:

https://youtu.be/pDl2bhUET8w

**Comment by elenmerbau** [comment]
Ples fix, I'm too scared of getting a 3rd pet now

**Comment by Wolffenstein** [comment]
Fixed in rev 3521.
