### ISSUE TITLE
[Silvermoon City] Random emote

### ISSUE THREAD

**Issue by deku100** [Atlantiss/NetherwingBugtracker#482]
[//]: # (Enclose links to things related to the bug using http://wowhead.com or any other TBC database.)
[//]: # (You can use screenshot ingame to visual the issue.)
[//]: # (Write your tickets according to the format:)
[//]: # ([Quest][Azuremyst Isle] Red Snapper - Very Tasty!)
[//]: # ([NPC] Magistrix Erona)
[//]: # ([Spell][Mage] Fireball)
[//]: # ([Npc][Drop] Ghostclaw Lynx)
[//]: # ([Web] Armory doesnt work)

**Description**: Random emotes in Silvermoon City

**Current behaviour**: Whenever I walk past these guards in Silvermoon, my character makes the /no emote (not reflected in chat log).
![wowscrnshot_092518_004622](https://user-images.githubusercontent.com/43505181/45993487-419b7a00-c05d-11e8-811e-1ee9af544702.jpg)

**Expected behaviour**: Character isn't supposed to emote anything.

**Server Revision**:

**Comment by Wolffenstein** [comment]
I don't see anything that could cause that. Are you sure it's not any addon of yours?

**Comment by Pennywise4569** [comment]
So it's not his character. I tested it out on my male blood elf with all addons disabled. When you walk past the guards there, and sometimes in the chamber with the racial leaders, you will hear a BE female no emote. Can't find the source.

**Comment by Hidole555** [comment]
I know what this is! It's Elrodan who is repeatedly polymorphing Aurosalia in a nearby room. Occasionally she will do a /no emote in between polymorphs. The problem is that instead of tying the sound to her location (or not playing the sound at all), the /no sound acts almost as if you had done a /script PlaySoundFile command and just plays the sound right on top of you.

**Comment by Evolvee** [comment]
![image](https://user-images.githubusercontent.com/1942409/47603846-b6adf680-d9f1-11e8-8611-565b0902dc35.png)

yea @Hidole555 good point!


rev ff15
