### ISSUE TITLE
@wolfenstien fix bgs

### ISSUE THREAD

**Issue by PembrokePB** [Atlantiss/NetherwingBugtracker#4820]
[//]: # (Enclose links to things related to the bug using http://wowhead.com or any other TBC database.)
[//]: # (You can use screenshot ingame to visual the issue.)
[//]: # (Write your tickets according to the format:)
[//]: # ([Quest][Azuremyst Isle] Red Snapper - Very Tasty!)
[//]: # ([NPC] Magistrix Erona)
[//]: # ([Spell][Mage] Fireball)
[//]: # ([Npc][Drop] Ghostclaw Lynx)
[//]: # ([Web] Armory doesnt work)
[//]: # (To find server revision type `.server info` command in the game chat.)

**Description**: 
bgs are broken
**Current behaviour**:
queue system is broken any amount can join on one side
**Expected behaviour**: 
it should work
**Server Revision**:

**Comment by maxturtlesc2** [comment]
Queue system works only for lvl 20+, so if there are many low level horde players connected (compared to alliance) the ratio will be more than 55/45 on the server overall, but for level 20+ players it is still following the 55/45 ratio rule for queue.

**Comment by Unfairy** [comment]
Maxturtle.
He is taking about battleground joining system. 
As it is now: as long as battleground is opened, any amount of players can join no matter the amount of players of opposite faction.
Making possible games like 4 VS 10.
Its supposed to be queued ±1.
4 VS 5. 5 VS 4. 5 VS 5.
"extra" players staying in queue untill players from opposite faction join battleground.
