### ISSUE TITLE
Lambent Blood does not keep you from stealthing

### ISSUE THREAD

**Issue by Unjun357** [Atlantiss/NetherwingBugtracker#4821]
[//]: # (Enclose links to things related to the bug using http://wowhead.com or any other TBC database.)
[//]: # (You can use screenshot ingame to visual the issue.)
[//]: # (Write your tickets according to the format:)
[//]: # ([Quest][Azuremyst Isle] Red Snapper - Very Tasty!)
[//]: # ([NPC] Magistrix Erona)
[//]: # ([Spell][Mage] Fireball)
[//]: # ([Npc][Drop] Ghostclaw Lynx)
[//]: # ([Web] Armory doesnt work)
[//]: # (To find server revision type `.server info` command in the game chat.)

**Description**: Lambent Blood Applied debuff by Bogflare Needler in Zangramarsh. 

**Current behaviour**:Applies debuff but can still stealth

**Expected behaviour**: Stealth should not be allowed

**Server Revision**: Revision 2756

**Comment by Tenoutoften** [comment]
[[Spell]Lambent Blood#35328](https://db.excalibur.ws/?spell=35328) used by [[NPC]Bogflare Needler#20197](https://db.excalibur.ws/?npc=20197)
![](https://i.gyazo.com/244b4013ba82876a1a1a78d417a0f961.png)

**Comment by tcberk12** [comment]
<img width="769" alt="Screen Shot 2019-03-16 at 11 11 24 AM" src="https://user-images.githubusercontent.com/43530009/54479742-6c30e900-47dd-11e9-9c7f-28826da9ec0e.png">

**Comment by ScottieDOESknow** [comment]
20 September 2019

https://i.gyazo.com/5d7fc52b110610ecb968c0beeb2e659e.mp4

Revision 3132

**Comment by Wolffenstein** [comment]
Fixed in rev 3138.
