### ISSUE TITLE
[Auction House][Mail System] Sale Pending Mail isn't Automatically Deleted

### ISSUE THREAD

**Issue by OMEGALULW** [Atlantiss/NetherwingBugtracker#4823]
**Current behaviour**: Sale Pending mail lingers in the mailbox after money has been sent to the player

**Expected behaviour**: "As stated above, initially you should receive an in-game mail from the Auction House, instead of the payment for the sold item. After an hour you should receive mail containing the coin from the sale, and the previous mail, the “Sale Pending” notice, should automatically delete itself. " (https://blue.mmo-champion.com/topic/39282-auction-house-sale-pending-notice/)

**Server Revision**: 2756

**Comment by sadfx** [comment]
> from my experience it auto-deletes properly if you never check your mail until the money arrives

No because last night I opened the mailbox and I had both the sale pending mail and the gold, and I had never seen the sale pending mail before. If it works like that sometimes for some, OK, but it shouldn't matter whether you open it or not.
