### ISSUE TITLE
[Quest][Shadowmoon valley] Harbingers of Shadowmoon

### ISSUE THREAD

**Issue by kwah8787** [Atlantiss/NetherwingBugtracker#4824]
[//]: # (Enclose links to things related to the bug using http://wowhead.com or any other TBC database.)
[//]: # (You can use screenshot ingame to visual the issue.)
[//]: # (Write your tickets according to the format:)
[//]: # ([Quest][Azuremyst Isle] Red Snapper - Very Tasty!)
[//]: # ([NPC] Magistrix Erona)
[//]: # ([Spell][Mage] Fireball)
[//]: # ([Npc][Drop] Ghostclaw Lynx)
[//]: # ([Web] Armory doesnt work)
[//]: # (To find server revision type `.server info` command in the game chat.)

**Description**: 
Shadowmoon Harbingers buggy
**Current behaviour**:
When I stealth and cheap shot the harbingers it's like they immediately reset. I don't get the combo points and they don't get stunned. Also immediately following my auto attacks don't work, but my abilities do. I started playing around a bit and also they reset right when you go out of melee range sometimes. All kinds of buggy.

fraps upload of the cheap shot bug + auto attack bug https://youtu.be/5KIyZUEjQgA

**Expected behaviour**: 

**Server Revision**: 
2756

**Comment by Tenoutoften** [comment]
Can confirm they are resetting too easily

**Comment by Swamper888888** [comment]
Would like to add something, I know something about the issue. Aggro will not go onto my hunter pet, it seems that the NPC can't fight with anyone without the goggles and if you lose combat it will become friendly then neutral again or something similar

**Comment by The14me** [comment]
Rev.3483 not an issue anymore.
Cheap shot/hunter pet etc work just fine without reset or anything strange.
