### ISSUE TITLE
[NPC][Boss][Karazhan][The Curator] Astral Flare doesn't proc Water Shield

### ISSUE THREAD

**Issue by sandreid** [Atlantiss/NetherwingBugtracker#4825]
Description:
The Astral Flares summoned by the Curator doesn't proc Water Shield. 

Current behaviour:
Astral Flares doesn't proc Water Shield. 

Expected behaviour:
Water Shield should proc from all spells as well as ranged and melee attacks. 

"When a spell, melee or ranged attack hits the caster, X mana is restored to the caster."
Source: http://db.excalibur.ws/?spell=33736

Server Revision:
2756

**Comment by Godmatik** [comment]
Rev 4014 - fixed at some point, Astral Flare is properly proccing water shield.

Closing.
