### ISSUE TITLE
[Dungeon] Party member couldn't get back in after death

### ISSUE THREAD

**Issue by Yutiarien** [Atlantiss/NetherwingBugtracker#4827]
[//]: # (Enclose links to things related to the bug using http://wowhead.com or any other TBC database.)
[//]: # (You can use screenshot ingame to visual the issue.)
[//]: # (Write your tickets according to the format:)
[//]: # ([Quest][Azuremyst Isle] Red Snapper - Very Tasty!)
[//]: # ([NPC] Magistrix Erona)
[//]: # ([Spell][Mage] Fireball)
[//]: # ([Npc][Drop] Ghostclaw Lynx)
[//]: # ([Web] Armory doesnt work)
[//]: # (To find server revision type `.server info` command in the game chat.)

**Description**: After a party member died and went back through the dungeon entrance he wasn't in the same instance as me. We couldn't see each other. All the mobs, that we killed, were alive for him but for me they were still dead.

**Current behaviour**: Death of a party member can bring him to a different version of the dungeon

**Expected behaviour**: Party member comes back alive in the same instance

**Server Revision**: 2756

**Comment by The14me** [comment]
Was related to Different ID after player dies. Not sure if that was fixed.
