### ISSUE TITLE
Avatar of the Martyred dident drop anything

### ISSUE THREAD

**Issue by Nesttun** [Atlantiss/NetherwingBugtracker#4828]
**Description**:  We wiped on Avatar of the Martyred after killing Exarch Maladaar in Auchenai Crypts normal mode.
 We ran back and  he then stood exactly where he killed the last person in the party, dident go back to the center or "reset" in any way..
when we started the fight again evrything seemd normal, he used his spells and it dident seem buggy at all, but when he died he dident drop any loot.

**Expected behaviour**:  drop loot, reset to where he should,

**Comment by towneh** [comment]
"The Avatar doesn't drop anything on normal."
https://www.wowhead.com/npc=18478/avatar-of-the-martyred#comments:id=59653

**Comment by devo6969** [comment]
Confirm this report is invalid, he isnt suppose to drop anything on normal, only on heroic
