### ISSUE TITLE
[Kara] Unable to loot boss item

### ISSUE THREAD

**Issue by CharlesH1994** [Atlantiss/NetherwingBugtracker#4829]
**Description**: 
Last night my guild killed Big Bad Wolf in Kara, we had Big bad wolf's paw and Ribbon of Sacrifice we were able to loot the paw but unable to loot the Ribbon we just kept getting the prompt "This item is still being rolled for" even 30-45 minutes after moving on. 
**Current behaviour**:
I am unsure if any other raids have had this issue.
**Expected behaviour**: 
It is expected you're able to get the available loot off of the bosses corpse.
**Server Revision**: 
2756

**Comment by WarriorTSW** [comment]
When I get this issue setting loot to free for all and having whoever you want to have the item loot it works for me.

**Comment by The14me** [comment]
That issue was fixed a long time ago.
