### ISSUE TITLE
Pre-Naxxramas Dungeon Boss

### ISSUE THREAD

**Issue by Piledriversn** [Atlantiss/NetherwingBugtracker#483]
I ran Scarlet Monestary graveyard, finished it and Scorn was there. He is a pre-Naxx only boss. 

https://wow.gamepedia.com/Scourge_Invasion
The link above shows its for the Scourage Invasion only

**Comment by Jezofine** [comment]
Killed him today also, funny guy.

**Comment by Evolvee** [comment]
ok, deleted the entire template from DB, if this doesnt help, nothing will xd

rev xdd
