### ISSUE TITLE
[Quest] Zuluhed the Whacked

### ISSUE THREAD

**Issue by kwah8787** [Atlantiss/NetherwingBugtracker#4831]
[//]: # (Enclose links to things related to the bug using http://wowhead.com or any other TBC database.)
[//]: # (You can use screenshot ingame to visual the issue.)
[//]: # (Write your tickets according to the format:)
[//]: # ([Quest][Azuremyst Isle] Red Snapper - Very Tasty!)
[//]: # ([NPC] Magistrix Erona)
[//]: # ([Spell][Mage] Fireball)
[//]: # ([Npc][Drop] Ghostclaw Lynx)
[//]: # ([Web] Armory doesnt work)
[//]: # (To find server revision type `.server info` command in the game chat.)

**Description**: 
Corpse poof very fast
**Current behaviour**:
We killed Zuluhed the Whacked and only 3/5 of our members were able to loot the key before he poofed, yet we all got credit for the kill itself. It seemed like his corpse poofed as it was hitting the ground, like 2 seconds after the kill.
**Expected behaviour**: 
Corpse should hang around long enough to loot. Probably like normal corpses around 5 minutes?
**Server Revision**: 
2756

**Comment by The14me** [comment]
There is a problem with the Key drop rate too.

**Comment by supzfly** [comment]
This problem occured for our party yesterday. Zuluhed despawned before a single one of us could loot. We killed him, finished off one of the demons that had spawned and by the time we were done the corpse had despawned. This was all in the space of ~1 minute. Very frustrating.
