### ISSUE TITLE
[Quest][NPC]Ogre Head on A Stick = Party spawned NPCs don't depsawn

### ISSUE THREAD

**Issue by Tenoutoften** [Atlantiss/NetherwingBugtracker#4832]
**Description**: 
Ends up looking like this after a few completes.
https://db.excalibur.ws/?quest=3825
![](https://i.gyazo.com/633299831bae93c324d68b1f590175e2.png)

**Expected behaviour**: 
Expected to have a despawn timer

**Server Revision**: 
2756

**Comment by Evolvee** [comment]
rev 2878
