### ISSUE TITLE
[NPC] Lil Timmy <Boy with kittens> 

### ISSUE THREAD

**Issue by OMEGALULW** [Atlantiss/NetherwingBugtracker#4833]
**Current behaviour**: Can't talk to him. It could be that he's out of stock but he still appears to be a vendor (https://i.imgur.com/SdoWrYg.png)

He also doesn't appear to get back on his designated route for several minutes after I talked to him (moved after 5 or so minutes)

**Expected behaviour**:  (Speculation) Should either have an empty vendor window OR not be interactable (the former is probably correct?)
**Server Revision**:  2756

**Comment by The14me** [comment]
Rev.3483 after u talk to him he goes back to normal designated route in around 3-5 min.
Even if he's out of stock,u still have the visual cursor about him and that's normal.
https://classic.wowhead.com/npc=8666/lil-timmy#comments:id=2908357
''that with two people stopping him to attempt a purchase (too late of course).''
