### ISSUE TITLE
[Core] [NPC] Critters Granting Weapon Skill 100%

### ISSUE THREAD

**Issue by Freyii** [Atlantiss/NetherwingBugtracker#4834]
**Description**: 
Critters grant weapon skill 100% of the time on non-crit hits.

**Current behaviour**: 
Critters grant weapon skill 100% of the time up to your current cap. Tested on 1h and 2h swords plus unarmed skill.

**Expected behaviour**: 
Critters should almost never grant weapon skill ups, let alone with a nearly 100% success rate. Only fails on crit OR when critters can take multiple hits from low damage swings.

**Server Revision**:

**Comment by Desst** [comment]
poor critters

**Comment by Tereneckla** [comment]
#362
