### ISSUE TITLE
[NPC] Deadmines - Mr Smite and his guards

### ISSUE THREAD

**Issue by Teppic1** [Atlantiss/NetherwingBugtracker#4835]
**Description**: 

Mr Smite's guards at the bottom of the bridge should be stealthed. When they aggro they should always pull Mr Smite.

**Current behaviour**:

Mr Smite's guards aren't stealthed. You can aggro the guards and kill them without aggroing Mr Smite. With no guards on top the fight is trivial.

**Server Revision**: 

2749

**Comment by randomuser69** [comment]
Teppic is right, the two mobs at the bottom of the bridge should be stealthed and aggroing them should pull Mr. Smite.

See this footage from wow classic beta: https://youtu.be/aiQF6aAM8nU?t=11124

Currently on NW, these two mobs are not stealthed and can be pulled without aggroing Mr. Smite 

@Evolvee 
@wtRCH

**Comment by Wolffenstein** [comment]
Fixed in rev 3082.
