### ISSUE TITLE
[Core][Guild Bank] Money deposited to Guild Bank has disappeared after server restart

### ISSUE THREAD

**Issue by MateuszKuzniewski** [Atlantiss/NetherwingBugtracker#4837]
**Description**: 
Money deposited to the Guild Bank (20g) has disappeared after one of the server restarts yesterday 
(03 Feb 19). Money log doesn't show any movement. Money has been deposited somewhat before the restart. Can't see the money in the bag either.

**Server Revision**: 
2756

**Comment by Wolffenstein** [comment]
Duplicate.
