### ISSUE TITLE
[Raid][SSC][NPC] Leotheras the Blind Whirlwind Damage bug.

### ISSUE THREAD

**Issue by Imbaslap** [Atlantiss/NetherwingBugtracker#4838]
[//]: # (Enclose links to things related to the bug using http://wowhead.com or any other TBC database.)
[//]: # (You can use screenshot ingame to visual the issue.)
[//]: # (Write your tickets according to the format:)
[//]: # ([Quest][Azuremyst Isle] Red Snapper - Very Tasty!)
[//]: # ([NPC] Magistrix Erona)
[//]: # ([Spell][Mage] Fireball)
[//]: # ([Npc][Drop] Ghostclaw Lynx)
[//]: # ([Web] Armory doesnt work)
[//]: # (To find server revision type `.server info` command in the game chat.)

**Description**: 
during the Leotheras the Blind encounter in SSC raid, spell=37641 bleed effect used by the boss is currently being affected by the player's armor value.
**Current behaviour**:
during the Leotheras the Blind encounter in SSC raid, spell=37641 bleed effect used by the boss is currently being affected by the player's armor value.
**Expected behaviour**: 
The Bleed effect from spell=37641 Whirlwind should not be affected by armor. this makes the encounter very under tuned currently on Netherwing.
**Server Revision**: 
https://youtu.be/8SWVNk-KfUI?t=194 - Method kill video showing 2500 bleed ticks on the warlock tank after taking damage from the whirlwind spell. the damage of the whirlwind attack is affected by armor, but the bleed effect is not.

**Comment by Wolffenstein** [comment]
Fixed in rev 2761.
