### ISSUE TITLE
[Raid][SSC][NPC] Leotheras the Blind not casting demon form.

### ISSUE THREAD

**Issue by Gedlund** [Atlantiss/NetherwingBugtracker#4839]
[//]: # (Enclose links to things related to the bug using http://wowhead.com or any other TBC database.)
[//]: # (You can use screenshot ingame to visual the issue.)
[//]: # (Write your tickets according to the format:)
[//]: # ([Quest][Azuremyst Isle] Red Snapper - Very Tasty!)
[//]: # ([NPC] Magistrix Erona)
[//]: # ([Spell][Mage] Fireball)
[//]: # ([Npc][Drop] Ghostclaw Lynx)
[//]: # ([Web] Armory doesnt work)
[//]: # (To find server revision type `.server info` command in the game chat.)

**Description**: 
Leotheras dosen't cast his demon form simply keeps casting whirlwind over and over and over and over again.

**Current behaviour**:
https://www.twitch.tv/videos/375165101?t=02h28m16s

**Expected behaviour**: 
Every 2-3rd whirlwind should result in a demon phase.
**Server Revision**:

**Comment by Wolffenstein** [comment]
Fixed in rev 2761.
