### ISSUE TITLE
Claiming the Light, QuestID#9684 minor error in text.

### ISSUE THREAD

**Issue by Tenoutoften** [Atlantiss/NetherwingBugtracker#484]
**Description**: 

Quest Claiming the Light#9684 (https://db.excalibur.ws/?quest=9684), lacks a space between "life." and "There" and lacks a space between "gift?" and "They" (https://i.gyazo.com/69158face90ccd530fba4790ec5e39f6.png). I deleted my cache and it's still there. 

The text will also be updated later on(When M'uru is in Sunwell) but that's irrelevant now:
https://www.wowhead.com/quest=9684/claiming-the-light

**Current behaviour**:

No space between "life." and "There", and no space between "gift?" and "They".

**Expected behaviour**: 

Expected to have a space between "life." and "There" & "gift?" and "They".

**Server Revision**: 

2048

**Comment by Evolvee** [comment]
@Wolfenstein you didnt use the SQL I gave you for it?

**Comment by Evolvee** [comment]
fixed in next rev
