### ISSUE TITLE
[quest][BEM]Showdown

### ISSUE THREAD

**Issue by duzyizly** [Atlantiss/NetherwingBugtracker#4840]
[//]: # (Enclose links to things related to the bug using http://wowhead.com or any other TBC database.)
[//]: # (You can use screenshot ingame to visual the issue.)
[//]: # (Write your tickets according to the format:)
[//]: # ([Quest][Azuremyst Isle] Red Snapper - Very Tasty!)
[//]: # ([NPC] Magistrix Erona)
[//]: # ([Spell][Mage] Fireball)
[//]: # ([Npc][Drop] Ghostclaw Lynx)
[//]: # ([Web] Armory doesnt work)
[//]: # (To find server revision type `.server info` command in the game chat.)

**Description**: Quest Showdown is not working.

**Current behaviour**: Nothing is happening when you use the horn next to the altar.

**Expected behaviour**:  Event should start once you use rexxar's battle horn.

**Server Revision**: 2756

I know there was some discussion like "-it's working" "-no it's not" "-yes it does lol"... but yeah why does it work for some ppl and it's not working for the others? Magic!

**Comment by Desst** [comment]
I rememeber quest from Hellfire peninsula (Foot of the citadel). A lot of people complained in chat it wasn't working and it didn't work for me and my group but later that day i managed to complete it with another group. That was strange af

**Comment by duzyizly** [comment]
btw, Just done the quest BUT the question is - why it wasn't working yesterday?

**Comment by Falathrin** [comment]
The NPC is supposed to transform into a dragon btw, he's not supposed to stay in human form.

**Comment by jasondilltx** [comment]
this quest is still bugged as of 15 October 2019

**Comment by devo6969** [comment]
This quest seems to be working fine on the PTR and he does transform into a dragon, its % base it appears (turned into a dragon 27%)
PTR - https://www.youtube.com/watch?v=kyGX4pLiL3s

**Comment by duzyizly** [comment]
The quest event You show in this video was working overall from the beggining of Netherwing server.
BUT
Sometimes - and this used to be reported on world chat over and over (I rememeber this from january/february 2019 - so leveling people) the quest event was not starting. Probably, becasue:
1. one of players failed the event (or left the event area)
2. two different players started the quest at the same time
Also, the quest was working perfectly after a server crash, so people were waiting for craft to start it :)

**Comment by duzyizly** [comment]
this is happening again rev 3497 karazhan
