### ISSUE TITLE
[Core] Movement stutter/rubberbanding

### ISSUE THREAD

**Issue by Zarant** [Atlantiss/NetherwingBugtracker#4841]
Since last weekend server update, other players are constantly stuttering and rubberbanding. 

By testing with some other guildies we found out that latency compounds the issue, the more lag you have, the worse the movement desync is. Maybe it has something to do with the movement changes made in revision 2755.

Server revision: 2756

**Comment by DragunovUA** [comment]
i noticed it too, but i thought its only on my side, looks like not only

**Comment by Balanarr** [comment]
Indeed, for the past day movement seems to be very clunky.

Also feared players (in pvp at least) are running actually running in different directions than shown for other players (not sure if this always happens or only sometimes)

**Comment by Cinx787** [comment]
Its honestly pretty bad to watch.

**Comment by Wolffenstein** [comment]
Fixed
