### ISSUE TITLE
[Auction House] Purchase Not Delivered

### ISSUE THREAD

**Issue by TxSmash** [Atlantiss/NetherwingBugtracker#4843]
[//]: # (Enclose links to things related to the bug using http://wowhead.com or any other TBC database.)
[//]: # (You can use screenshot ingame to visual the issue.)
[//]: # (Write your tickets according to the format:)
[//]: # ([Quest][Azuremyst Isle] Red Snapper - Very Tasty!)
[//]: # ([NPC] Magistrix Erona)
[//]: # ([Spell][Mage] Fireball)
[//]: # ([Npc][Drop] Ghostclaw Lynx)
[//]: # ([Web] Armory doesnt work)
[//]: # (To find server revision type `.server info` command in the game chat.)

**Description**: 

**Current behaviour**:

**Expected behaviour**: 

**Server Revision**:

**Comment by TxSmash** [comment]
Purchased Lesser Magic Wand around 2:37am server time.  Mail icon appeared on map checked Mailbox but item did not appear.
Please verify purchase and deliver item.

**Comment by alostic** [comment]
I've had this same issue since about 17 hours ago but if you relog it will appear in your mailbox.

**Comment by Tenoutoften** [comment]
Mail updates ~ once a minute, if you recently checked your mail, it might need another update. you can force update it with relogging.

**Comment by Easyfraggy** [comment]
As Tenoutoften said mail updates every 60 seconds - relog to force update.
