### ISSUE TITLE
[Quest][Tanaris] The Mithril Kid

### ISSUE THREAD

**Issue by Moncer** [Atlantiss/NetherwingBugtracker#4846]
**Description**: don't work for me. i have 2 Heavy Mithril Breastplate and 1 Ornate Mithril Gloves in my bags but quest don't complete.

**Expected behaviour**: 
Quest must give up, since all the ingredients are collected
**Server Revision**: 
2756

**Comment by duzyizly** [comment]
put 'em into bank, relog, pick up, turn in.
