### ISSUE TITLE
container slot disappeared

### ISSUE THREAD

**Issue by Rix0s** [Atlantiss/NetherwingBugtracker#4848]
[//]: # (Enclose links to things related to the bug using http://wowhead.com or any other TBC database.)
[//]: # (You can use screenshot ingame to visual the issue.)
[//]: # (Write your tickets according to the format:)
[//]: # ([Quest][Azuremyst Isle] Red Snapper - Very Tasty!)
[//]: # ([NPC] Magistrix Erona)
[//]: # ([Spell][Mage] Fireball)
[//]: # ([Npc][Drop] Ghostclaw Lynx)
[//]: # ([Web] Armory doesnt work)
[//]: # (To find server revision type `.server info` command in the game chat.)

**Description**: A bag in one of my container slot just disappeared and had some items i was gonna equip when my level allowed

**Current behaviour**:

**Expected behaviour**: 

**Server Revision**:

**Comment by Manaci** [comment]
Dead issue
