### ISSUE TITLE
[Dungeon][Heroic] Hellfire Ramparts -  Nazzan does not drop a badge and neither does chest

### ISSUE THREAD

**Issue by Desst** [Atlantiss/NetherwingBugtracker#4849]
**Current behaviour**:
title
Also in Auchenai crypts heroic - Avatar does not dorp a badge but that might be right behavior
**Expected behaviour**: 
2 badges from hellfire ramprats does not seem right. I don't actually remember early patches like 2.0.3 but it was 4 badges per run for sure
**Server Revision**: 2756

**Comment by Easyfraggy** [comment]
I believe this was discussed before - he doesn't drop a badge untill a certain patch - correct me if I'm wrong.

**Comment by Brasso** [comment]
#2790 Badge was added in patch 2.3.
