### ISSUE TITLE
[Patching/Clipping] Dun Morogh

### ISSUE THREAD

**Issue by DoctorRaymos** [Atlantiss/NetherwingBugtracker#485]
doesnt move - https://i.imgur.com/7Pj6TOR.jpg
died in funny position (not sure what can be done about this) - https://i.imgur.com/Z7cAQ2s.jpg
pathing below map - https://i.imgur.com/b7s7mm5.jpg
standing in air - https://i.imgur.com/ymM611h.jpg
pathing under map - https://i.imgur.com/MX004xQ.jpg
pathing under map - https://i.imgur.com/pA3sYyU.jpg

**Comment by aresbrutus** [comment]
Fixed in one of the upcoming updates.
