### ISSUE TITLE
[NPC][Boss][Karazhan][Prince Malchezaar] SW: Pain

### ISSUE THREAD

**Issue by Drayo** [Atlantiss/NetherwingBugtracker#4851]
[//]: # (Enclose links to things related to the bug using http://wowhead.com or any other TBC database.)
[//]: # (You can use screenshot ingame to visual the issue.)
[//]: # (Write your tickets according to the format:)
[//]: # ([Quest][Azuremyst Isle] Red Snapper - Very Tasty!)
[//]: # ([NPC] Magistrix Erona)
[//]: # ([Spell][Mage] Fireball)
[//]: # ([Npc][Drop] Ghostclaw Lynx)
[//]: # ([Web] Armory doesnt work)
[//]: # (To find server revision type `.server info` command in the game chat.)

**Current behaviour**: Prince Malchezaar uses his Shadow Word: Pain on the Tank in P1 and P3

**Expected behaviour**: Prince Malchezaar should use his Shadow Word: Pain on random targets in Phase 3.

https://wowwiki.fandom.com/wiki/Prince_Malchezaar

> Shadow Word Pain (Phases One and Three)
> Periodically casts Shadow Word: Pain on his primary target for Phase One, and on a random target for
> Phase Three. Can be dispelled. Cannot be reflected. Causes 1500 damage per tick. 

**Server Revision**:  2756

**Comment by Wolffenstein** [comment]
Fixed in rev 2764.
