### ISSUE TITLE
[NPC][Boss][Karazhan][Netherspite] Green Beam

### ISSUE THREAD

**Issue by Drayo** [Atlantiss/NetherwingBugtracker#4852]
[//]: # (Enclose links to things related to the bug using http://wowhead.com or any other TBC database.)
[//]: # (You can use screenshot ingame to visual the issue.)
[//]: # (Write your tickets according to the format:)
[//]: # ([Quest][Azuremyst Isle] Red Snapper - Very Tasty!)
[//]: # ([NPC] Magistrix Erona)
[//]: # ([Spell][Mage] Fireball)
[//]: # ([Npc][Drop] Ghostclaw Lynx)
[//]: # ([Web] Armory doesnt work)
[//]: # (To find server revision type `.server info` command in the game chat.)

**Current behaviour**: The Green Beam does not restore your mana to the current maximum with each tick.
+From [Anonyxx](/Anonyxx): It does not increase healing done.

**Expected behaviour**: The Green Beam should restore all your mana, whenever it lowers you maximum mana, just like the red beam does with health.
+From [Anonyxx](/Anonyxx): It should increase healing done.

https://wow.gamepedia.com/Netherspite

> **Green Beam**
> Hits Player: 
> Maximum mana reduced by 200. Stacks up until your total mana pool reaches 0. Druids in Bear/Cat Form will have their hidden mana bars affected as well. Rage and Energy maxima are unaffected.
> **Healing done is increased by 5% per tick.**
> **Similar to the red beam, mana is restored to the new maximum with each tick.**

**Server Revision**: 2763

**Comment by Anonyxx** [comment]
It also does not increasing healing done, as it should do.

**Comment by air-deutsch** [comment]
Another Bug with Green Beam: When I tank the Green beam as Druid in Cat Form and the buff expires it doesn't restore the original amount of max mana but the additional mana is available forever.

**Comment by Wolffenstein** [comment]
Fixed in rev 2826.
