### ISSUE TITLE
[NPC][Pathing][Karazhan] Fleshbeasts

### ISSUE THREAD

**Issue by Drayo** [Atlantiss/NetherwingBugtracker#4853]
[//]: # (Enclose links to things related to the bug using http://wowhead.com or any other TBC database.)
[//]: # (You can use screenshot ingame to visual the issue.)
[//]: # (Write your tickets according to the format:)
[//]: # ([Quest][Azuremyst Isle] Red Snapper - Very Tasty!)
[//]: # ([NPC] Magistrix Erona)
[//]: # ([Spell][Mage] Fireball)
[//]: # ([Npc][Drop] Ghostclaw Lynx)
[//]: # ([Web] Armory doesnt work)
[//]: # (To find server revision type `.server info` command in the game chat.)

**Current behaviour**: When you pull any of the Fleshbeasts into the Chess Room, they sometimes get stuck on the ramp and just look at the raid. After a while they reset and suddenly engage again.

**Expected behaviour**: They should not get stuck on the ramp.

**Server Revision**:  2763

**Comment by towneh** [comment]
Just to add to this, as perhaps this could be used to track generic pathing issues within Karazhan, if you attempt to kite the Night Mistress NPCs from the corridors leading up towards the Maiden of Virtue down to the stables near the front entrance, then the NPC will become stuck/evade on the main front-entrance staircase when attempting to path back to their original location towards the rest of the raid. The NPC is able to re-engage with the raid once the raid moves back to the top of the same staircase.

**Comment by devo6969** [comment]
Still happens on the PTR. If you let the Fleshbeasts come near the ramp then jump, they still get stucked. I got one to come because i jumped too soon but normally they both get stuck.
PTR - https://www.youtube.com/watch?v=tEYJEmq1n1s

**Comment by Godmatik** [comment]
Rev 4016 - no longer an issue
Likely fixed with the pathing updates done last year
