### ISSUE TITLE
[NPC][Gruul's Lair]  Wild Fel Stalkers

### ISSUE THREAD

**Issue by Drayo** [Atlantiss/NetherwingBugtracker#4854]
[//]: # (Enclose links to things related to the bug using http://wowhead.com or any other TBC database.)
[//]: # (You can use screenshot ingame to visual the issue.)
[//]: # (Write your tickets according to the format:)
[//]: # ([Quest][Azuremyst Isle] Red Snapper - Very Tasty!)
[//]: # ([NPC] Magistrix Erona)
[//]: # ([Spell][Mage] Fireball)
[//]: # ([Npc][Drop] Ghostclaw Lynx)
[//]: # ([Web] Armory doesnt work)
[//]: # (To find server revision type `.server info` command in the game chat.)

**Current behaviour**: When a Warlock enslaves these, the enslave breaks after ~2 seconds every time.

**Expected behaviour**: The enslave should not break this easily and more importantly this consistently, most tactic sites/wikis promote taking him with his own summoned adds, this seems impossible right now.

_EDIT: UgaUga Tanking him with his own minions is impossible, killing the Boss is not the impossible thing. UgaUga_

**Server Revision**: 2763

**Comment by PembrokePB** [comment]
banish it then, its not impossible if a majority of guikds have cleared it already

**Comment by Drayo** [comment]
No worries, I added an explanation in Ape language so even primates like you get it.

**Comment by Drayo** [comment]
I just re-tested and the enslave does not seem to break early anymore.
