### ISSUE TITLE
Ancestral ground orcs

### ISSUE THREAD

**Issue by Hjorghensverg** [Atlantiss/NetherwingBugtracker#4855]
[//]: # (Enclose links to things related to the bug using http://wowhead.com or any other TBC database.)
[//]: # (You can use screenshot ingame to visual the issue.)
[//]: # (Write your tickets according to the format:)
[//]: # ([Quest][Azuremyst Isle] Red Snapper - Very Tasty!)
[//]: # ([NPC] Magistrix Erona)
[//]: # ([Spell][Mage] Fireball)
[//]: # ([Npc][Drop] Ghostclaw Lynx)
[//]: # ([Web] Armory doesnt work)
[//]: # (To find server revision type `.server info` command in the game chat.)

**Description**: The ancestral orcs in nagrand not being "red"

**Current behaviour**: The orcs at the ancestral burial grounds do not pull when you run through them or if you shoot at them (they evade). Also they break their leash if you do melee them and walk away a few yards

**Expected behaviour**: Not this

**Server Revision**:

**Comment by towneh** [comment]
This behavior can be mitigated by first engaging the target with a melee attack, then you are free to deal with them as you would a normal mob. However, if you use ranged attacks/spells/body aggro without doing this, they will evade almost immediately back to their original position.

**Comment by Tereneckla** [comment]
Fixed
