### ISSUE TITLE
[Spell][Druid] Moonfire

### ISSUE THREAD

**Issue by drchristie** [Atlantiss/NetherwingBugtracker#4856]
[//]: # (Enclose links to things related to the bug using http://wowhead.com or any other TBC database.)
[//]: # (You can use screenshot ingame to visual the issue.)
[//]: # (Write your tickets according to the format:)
[//]: # ([Quest][Azuremyst Isle] Red Snapper - Very Tasty!)
[//]: # ([NPC] Magistrix Erona)
[//]: # ([Spell][Mage] Fireball)
[//]: # ([Npc][Drop] Ghostclaw Lynx)
[//]: # ([Web] Armory doesnt work)
[//]: # (To find server revision type `.server info` command in the game chat.)

**Description**: 

Boomkin has a few issues to report, some which had tickets fixed on beta are broken again here. I will do my best to submit them well-formatted separately. To start off, lets talk about moonfire:

references: 
http://wow.allakhazam.com/wiki/spell_coefficient_(wow) (1.5s cast/instant) (42.86% coefficient nonhybrid)
https://wowwiki.fandom.com/wiki/Spell_power  (1.5s cast/instant) (42.86% coefficient)
https://wowwiki.fandom.com/wiki/Spell_power_coefficient?oldid=1492745 (MoonfireDD 15% MoonfireDoT 52%) Revision as of 13:40, July 4, 2008

**Current behaviour**:

( Moonfire sucks in current revision. take it off your bars. ). It hits for about 450-500 noncrit nonpartialresist unbuffed at 888 base spell dmg.  

**Expected behaviour**: 

in pre-bis gear, moonfire on gummy was hitting for 1050 normal 2100ish crits unbuffed 2500-2600 raid buffed and here its hitting for ~500 normal 1k crits (at 888 unbuffed spellpower). The TLDR based on EJ/archived forum posts for moonkin dps is generally wrath/moonfire for max dps, starfire/insect swarm for efficiency. high end gear in raids best is starfire spam, but mid-range should be starfire+moonfire w/ the spellcloth mid-tier gear lvl

random expectations w/ link:
https://www.youtube.com/watch?v=HHa5POhtTBk heres a vanilla max rank moonfire critting 700 in 400 sp 

https://www.twitch.tv/sprinklzlol/clip/DaintyTenderBananaKappaWealth?filter=clips&range=all&sort=time
1030 regular moonfire

https://clips.twitch.tv/PlainWimpyShingleGOWSkull
905 regulars, 980 crit through ice barrier

https://www.youtube.com/watch?v=lbj66oSFjg8
bigger regulars, worse gear but w/ higher crit

science-y expectations:
w/ the third reference: Tooltip states 305-358 base damage. 15% of spell power (+150 at 1k spell power) = 455-508 base damage. 
10% dmg from improved moonfire talent 2/2, 10% from moonfury 5/5 talent, assuming multiplicative: expecting ~550-605. not sure what made it so much higher on other tbc servers unless they straight up used the 42% instant cast coefficient on it or something (bias of people to over-report shit that hurts em and under-report shit that helps em?). 

Correct me if I'm wrong but the talents should apply after the spell power coefficient, it feels as the talents are adding the 110% + 110% dmg prior to the spell power or something

however, using the allakazam link, also revised for 2008:  we can see: 
 

> This category includes damage and healing spells with both a direct portion as well as an "Over-Time" portion. The standard formula for these spells is as follows:
>      Over-Time portion: ([Duration] / 15) / (([Duration] / 15) + ([Cast Time] / 3.5)) = [Over-Time portion]
>      Direct portion: 1 - [Over-Time portion] = [Direct portion]
> The duration and cast time limitations are then applied:
>       Over-Time portion: ([Duration] / 15) * [Over-Time portion] = [Over-Time coefficient]
>       Direct portion: ([Cast Time / 3.5) * [Direct portion] = [Direct coefficient]

note self: ill do the math later
edit: did the math, coefficients come out to about 52% and 15% assuming casttime=1.5s so all 3 proofs are validated

**Server Revision**: 

ill update when i get home, but feb 5, 2019

**Comment by drchristie** [comment]
12/15 = 0.8

0.8 / + 1.5/3.5(.423) = ~ .65 [over-time portion], so direct portion = .35
1.5/3.5 *.35 = direct coefficient =

**Comment by Brasso** [comment]
I'll add some retail footage for reference.

https://www.youtube.com/watch?v=4aLA85c4t8Y Hits for 500-600. Doesn't have the high spell damage because he's tanking, no dps flasks either.

https://www.youtube.com/watch?v=sSGkeKeDQgs 1400-1550 crits, about 800 hits on average in Black Temple, fully raid buffed.

https://www.youtube.com/watch?v=Jlly0oOBObM Around 1200 crits, 600 hits, self buffed.

Hard to tell what kind of gear they're using because boomkin, maybe you can estimate from their hp/mana.

**Comment by drchristie** [comment]
Furthermore, exclusive interview with #1 experienced boomkin on gummy:

BotanistToday at 1:20 PM
MF costs too much mana to do dogshit dmg
all the proof u need

**Comment by Jseay1313** [comment]
Moonfire is definitely hitting too low, I'm not even sure the DOT damage coefficient is correct it's critting for sub 1200 fully flasked and raid buffed with 1040 sp. I don't know what the coefficient should be but like botanist said man its shit for the mana cost and it is (was) supposed to be part of the rotation I.e t5 4 piece bonus

**Comment by Godmatik** [comment]
Either this was fixed at some point, or Gummy had it wrong (more likely).

I compared extensively to classic logs, and moonfire is scaling just as it should.

**Comment by Godmatik** [comment]
Gummy just had it wrong (surprise surprise)

I compared extensively to classic logs.

"in pre-bis gear, moonfire on gummy was hitting for 1050 normal 2100ish crits unbuffed 2500-2600 raid buffed "

Not even sunwell geared/fully buffed boomkin are hitting for close to that much according to the logs I have checked,
