### ISSUE TITLE
[Area] [Elwynn Forest] Echo Ridge Mine - Mobs too stacked

### ISSUE THREAD

**Issue by KredesX** [Atlantiss/NetherwingBugtracker#4858]
[//]: # (Enclose links to things related to the bug using http://wowhead.com or any other TBC database.)
[//]: # (You can use screenshot ingame to visual the issue.)
[//]: # (Write your tickets according to the format:)
[//]: # ([Quest][Azuremyst Isle] Red Snapper - Very Tasty!)
[//]: # ([NPC] Magistrix Erona)
[//]: # ([Spell][Mage] Fireball)
[//]: # ([Npc][Drop] Ghostclaw Lynx)
[//]: # ([Web] Armory doesnt work)
[//]: # (To find server revision type `.server info` command in the game chat.)

**Description**: Mobs too stacked in the mine, its almost impossible to solo while doing the quest [Skirmish at Echo Ridge]

**Current behaviour**: Too many mobs stacked.

**Expected behaviour**: Less mobs should be stacked, also aggro range too high. 

**Server Revision**: 2765

**Comment by Easyfraggy** [comment]
Mines in wow are often very aids - but Kutsal will take a look - if you have any proof like video or screenshots from the area from retail would be very helpful.

**Comment by devo6969** [comment]
There is exact same amount of mobs in the mine on classic as there is on the PTR in the mines
