### ISSUE TITLE
Problems with guildbank, Deposit and Withdraw gold

### ISSUE THREAD

**Issue by Hyldig09** [Atlantiss/NetherwingBugtracker#4859]
[//]: # (Enclose links to things related to the bug using http://wowhead.com or any other TBC database.)
[//]: # (You can use screenshot ingame to visual the issue.)
[//]: # (Write your tickets according to the format:)
[//]: # ([Quest][Azuremyst Isle] Red Snapper - Very Tasty!)
[//]: # ([NPC] Magistrix Erona)
[//]: # ([Spell][Mage] Fireball)
[//]: # ([Npc][Drop] Ghostclaw Lynx)
[//]: # ([Web] Armory doesnt work)
[//]: # (To find server revision type `.server info` command in the game chat.)

**Description**: 

**Current behaviour**:

**Expected behaviour**: 

**Server Revision**:

**Comment by Hyldig09** [comment]
Hello. I've tried to deposit some gold in the guild bank and everytime i do so they disappear. I lose them in my bag, and can se that i've deposit them in the bank. But when I login the day after the gold is gone, and the log says nothing about withdrawing or anything, so it's not like anybody has taken the gold away from the bank. They just disappear...

**Comment by Tenoutoften** [comment]
Leadership is aware that guildbanks deleted reagents & gold. There is no refund policy so don't use guild banks unless you are fine with losing the stuff you put in there

**Comment by Hyldig09** [comment]
Will it be fixed soon? or will we never be able to use the guild bank?

**Comment by Wolffenstein** [comment]
Duplicate.
