### ISSUE TITLE
[Quest][Eversong Woods] Deactivating the spire

### ISSUE THREAD

**Issue by Pennywise4569** [Atlantiss/NetherwingBugtracker#486]
[//]: # (Enclose links to things related to the bug using http://wowhead.com or any other TBC database.)
[//]: # (You can use screenshot ingame to visual the issue.)
[//]: # (Write your tickets according to the format:)
[//]: # ([Quest][Azuremyst Isle] Red Snapper - Very Tasty!)
[//]: # ([NPC] Magistrix Erona)
[//]: # ([Spell][Mage] Fireball)
[//]: # ([Npc][Drop] Ghostclaw Lynx)
[//]: # ([Web] Armory doesnt work)

**Description**: Dying up on the spire makes your body inaccessible. According to comments from 2.4.3 on Wowhead, walking towards the Orb of Translocation @ 69,52 that sends you up to the spire should teleport your spirit there.

**Current behaviour**: Walking towards the orb of translocation does not teleport your spirit up

**Expected behaviour**: Walking towards the orb should teleport your spirit up.

**Server Revision**:

**Comment by Evolvee** [comment]
fixed in next revision
