### ISSUE TITLE
Server crash breaks event in Shattered Halls Heroic

### ISSUE THREAD

**Issue by Mikik3jr** [Atlantiss/NetherwingBugtracker#4862]
[//]: # (Enclose links to things related to the bug using http://wowhead.com or any other TBC database.)
[//]: # (You can use screenshot ingame to visual the issue.)
[//]: # (Write your tickets according to the format:)
[//]: # ([Quest][Azuremyst Isle] Red Snapper - Very Tasty!)
[//]: # ([NPC] Magistrix Erona)
[//]: # ([Spell][Mage] Fireball)
[//]: # ([Npc][Drop] Ghostclaw Lynx)
[//]: # ([Web] Armory doesnt work)
[//]: # (To find server revision type `.server info` command in the game chat.)

**Description**: 
We have just finished the running-archer event after the first boss in Shattered Halls heroic, but the server crashed.

**Current behaviour**:
After the DC we lost out timer debuff for the execution, and there were no executioner at the end of the dungeon, so the quests:
- Trial of the Naaru: Mercy
- Imprisoned in the Citadel
could not be completed.

**Expected behaviour**: 
After server crash we should be able to continue the events. It suck more, because we can do HC runs once/day and that dungeon is aids.

**Server Revision**: 
2765

**Comment by Godmatik** [comment]
Rev 4014 still an issue

**Comment by Godmatik** [comment]
Wolf fixed this in rev 4015
