### ISSUE TITLE
[NPC] Gusting Vortex, Breath of Wind droprate

### ISSUE THREAD

**Issue by someotherplayer** [Atlantiss/NetherwingBugtracker#4864]
The NPCs "Gusting Vortex" in Tanaris should drop Breath of Wind at a relatively high rate.
I have been killing them for 1.5h now and they haven't been dropping anything at all.

http://db.hellfire-tbc.com/?npc=8667

**Comment by Tenoutoften** [comment]
![](https://i.gyazo.com/938a11f816ea78f9d1c6ff84306b552b.png)

**Comment by Tenoutoften** [comment]
http://web.archive.org/web/20071012041205/http://thottbot.com:80/c8667

**Comment by Easyfraggy** [comment]
I think theres a prerequisite quest - I don't remember which one - but one of the quests at Elemental Plateau is required to complete before this drops afaik.

**Comment by jhuerta13** [comment]
Can confirm this bug however this is not limited to just Gusting Vortex NPC, but also those found on Desolace. Two days ago I was killing a lot of them to get mats required for Elemental LW items and not a single one dropped a thing not even gray junk. I'm sure their loot tables are messed up.


Tested NPCs not dropping anything at all:
Whirlwind Stormwalker @ Desolace (Orange/Brownish skin)
Blue Air Elemental @ Desolace (Bluish skin)
Gusting Vortex @ Tanaris


Footage @ Tanaris:
https://youtu.be/vOAboMw6MdQ

**Comment by someotherplayer** [comment]
> 
> 
> I think theres a prerequisite quest - I don't remember which one - but one of the quests at Elemental Throne is required to complete before this drops afaik.

Thats not correct.
I killed a few the other day again and 1 breath dropped. The other had no loot at all.
It might just be the droprate that is crazy low.

**Comment by Easyfraggy** [comment]
Oh nevermind my comment i confused this item with the Nagrand quest.

**Comment by The14me** [comment]
Rev 3460. There is something wrong with the loot table. Killed 10 and only 1 drop anything.

**Comment by Wolffenstein** [comment]
Fixed in rev 3471.
