### ISSUE TITLE
[NPC] Marauding Crust Burster

### ISSUE THREAD

**Issue by InsertLink** [Atlantiss/NetherwingBugtracker#4865]
[//]: # (Enclose links to things related to the bug using http://wowhead.com or any other TBC database.)
[//]: # (You can use screenshot ingame to visual the issue.)
[//]: # (Write your tickets according to the format:)
[//]: # ([Quest][Azuremyst Isle] Red Snapper - Very Tasty!)
[//]: # ([NPC] Magistrix Erona)
[//]: # ([Spell][Mage] Fireball)
[//]: # ([Npc][Drop] Ghostclaw Lynx)
[//]: # ([Web] Armory doesnt work)
[//]: # (To find server revision type `.server info` command in the game chat.)

**Description**: Marauding Crust Burster's drops rate of the quest item [Eroder Leather Case] is way lower that it's meant to be.

**Current behaviour**:After killing over 50 of them the item with a 7% drop rate wouldn't drop.

**Expected behaviour**: The item should be obtainable after killing less than 30 mobs in most cases due to it's intended drop rate.

**Server Revision**:

**Comment by Baelek** [comment]
The RNG gods just aren't in your favor. I received mine in just a handful of kills. Others were lucky, or not as lucky too per https://www.wowhead.com/item=23338/eroded-leather-case#comments

**Comment by Evolvee** [comment]
rev 2830
