### ISSUE TITLE
[Quest] Reward for lvl 64 quest gives items way too low ilvl

### ISSUE THREAD

**Issue by pohlow** [Atlantiss/NetherwingBugtracker#4866]
[//]: # (Enclose links to things related to the bug using http://wowhead.com or any other TBC database.)
[//]: # (You can use screenshot ingame to visual the issue.)
[//]: # (Write your tickets according to the format:)
[//]: # ([Quest][Azuremyst Isle] Red Snapper - Very Tasty!)
[//]: # ([NPC] Magistrix Erona)
[//]: # ([Spell][Mage] Fireball)
[//]: # ([Npc][Drop] Ghostclaw Lynx)
[//]: # ([Web] Armory doesnt work)
[//]: # (To find server revision type `.server info` command in the game chat.)

**Description**: 
What Happens in Terokkar Stays in Terokkar
**Current behaviour**:
gives ilvl 80 equipment, which is way too low for this quest level
**Expected behaviour**: 
Should be about ilvl 95-105
**Server Revision**:

**Comment by Tenoutoften** [comment]
Pretty sure this is a client side thing, looks accurate
https://db.excalibur.ws/?quest=10008

**Comment by wtRCH** [comment]
@aresbrutus
