### ISSUE TITLE
[Quest][Warrior] The Affray 

### ISSUE THREAD

**Issue by darkinone** [Atlantiss/NetherwingBugtracker#4867]
[//]: # (Enclose links to things related to the bug using http://wowhead.com or any other TBC database.)
[//]: # (You can use screenshot ingame to visual the issue.)
[//]: # (Write your tickets according to the format:)
[//]: # ([Quest][Azuremyst Isle] Red Snapper - Very Tasty!)
[//]: # ([NPC] Magistrix Erona)
[//]: # ([Spell][Mage] Fireball)
[//]: # ([Npc][Drop] Ghostclaw Lynx)
[//]: # ([Web] Armory doesnt work)
[//]: # (To find server revision type `.server info` command in the game chat.)

**Description**: 
When i take the quest my game instantly freezed and i can no longer do anything. Closing and opening it doesnt help me. Only when timer is over and quest failed, its unfreezes
**Current behaviour**:

**Expected behaviour**: 

**Server Revision**:

**Comment by Drayo** [comment]
You need to disable the Quest Helper Addon. It bugs out on timed quests.
