### ISSUE TITLE
Multi-Shot

### ISSUE THREAD

**Issue by MelEnt** [Atlantiss/NetherwingBugtracker#4868]
[//]: # (Enclose links to things related to the bug using http://wowhead.com or any other TBC database.)
[//]: # (You can use screenshot ingame to visual the issue.)
[//]: # (Write your tickets according to the format:)
[//]: # ([Quest][Azuremyst Isle] Red Snapper - Very Tasty!)
[//]: # ([NPC] Magistrix Erona)
[//]: # ([Spell][Mage] Fireball)
[//]: # ([Npc][Drop] Ghostclaw Lynx)
[//]: # ([Web] Armory doesnt work)
[//]: # (To find server revision type `.server info` command in the game chat.)

**Description**: 
MultiShot should attack 2 additional targets nearest to your primary target

**Current behaviour**:
MultiShot hits targets that are engaged to you but not in close proximity to your primary target
How to reproduce this issue:
1. Engage more than 1 target
2. Aggro one of the targets (so one is in melee range and other is in ranged range and attacking your pet for instance)
3. Freeze Trap the melee range
4.  MultiShot
5. Watch how the frozen target gets hit even tho there's a vast range difference between them

This issue occurs because MultiShot doesn't use the correct proximity check. 
**It shouldn't hit targets that are close to you, but rather to your primary target**

**Expected behaviour**: 
MultiShot shouldn't hit targets that are far apart

**Server Revision**: 
2765

**Comment by Fuzedknight** [comment]
I've also had some strange interactions with multi shot like it flying out of my back if I have a trapped target behind me.

**Comment by The14me** [comment]
rev. 3460 not an issue anymore.
Can be closed.
