### ISSUE TITLE
[Quest][Bloodmyst Isle] Signs of the Legion Large Area wide spawn issue.

### ISSUE THREAD

**Issue by Sothanwow** [Atlantiss/NetherwingBugtracker#487]
**Description**: 
So I'm not sure if my descriptions or correct as this is a fairly large spanning problem dealing with this quest. I will try to break down the issues. So Nazzivus summoners spawn all around Nazzivian like so in these [Images](https://imgur.com/a/hKbgOrG) If you walk around Nazzivian you will see these  summoners all over here.
They shouldn't be any around here at all at least spawned like this I think they should mostly be replaced with Nazzivus Felsworn or one of the other satyr variation. But I noticed there were not many Nazzivus Felsworn in the area. 

Which leads into the next issue which I am not sure should be a separate issue Nazzivus summoners should be used only with summoning [Tzerak](https://www.wowhead.com/npc=17528/tzerak) Which has a little rp event where they stand in a circle and summon Tzerak a rp happens and he Hellfires killing them. This only happens when they summon him. http://wowwiki.wikia.com/wiki/Nazzivus_Summoner here is a small post explaining what they do. 

This is a video of the kill side of the quest but having a harder time finding the rp even where he is summoned and then kills the summoners.But it should happen when ever he spawns and he should despawn a little while after he spawns and it should repeat after a certain amount of time. The video https://www.youtube.com/watch?v=1kNUHLUEf1c
It is from a later expansion but that should be close to how the npcs are laid out for the kill side of the quest. I am sure there are better sources then what I found. 

From Research this spell is used in part of killing the satyrs
spell=30656 
This spell has some relation to him despawning 
spell=32555

I was not able to see the spell in the database that the summoners use but I know the effect is a Mindflay type of beam. There seem to be a assortment of those type of effects. 

You can see the beam in this picture here https://www.wowhead.com/npc=17524/nazzivus-summoner
I would like to add he does do part of the rp he yells
**Current behaviour**:
Nazzivus Summoners spawning all over the place 
Tzerak summoning rp event doesn't happen.He just spawns in like any other mob in front of the alter.

**Expected behaviour**: 
Summoners should only be spawned when summoning Tzerak 
Tzerak summoning rp even should happen which doesn't 
**Server Revision**: 
2048

**Comment by Peglaa** [comment]
Tzerak summoning event is already working. Not sure about the spawns tho. Mybe Wolf can use some sniff data. I dont have access to it anymore so cant confirm easily.

**Comment by Evolvee** [comment]
its true there are no hardspawned summoners in sniffs

removed in upcoming revision
