### ISSUE TITLE
[Druid][Bear] Issues with rage and swipe.

### ISSUE THREAD

**Issue by jhuerta13** [Atlantiss/NetherwingBugtracker#4870]
**Description**: 

_ISSUE 1: Full rage cost on special abilities when they get dodged/parried/missed_
Druids on bear form are losing complete rage cost of a special ability whenever they are being missed, dodged, parried. This is a big issue for bear tanking since it cuts down the number of abilities you can use to build agro, increasing rage downtime causing agro loss.

Seems like this was reported by warriors, but it does indeed affect druids aswell.
https://github.com/Atlantiss/NetherwingBugtracker/issues/3957

_ISSUE 2: Dodged/parried white attacks not generating rage_
White auto attacks that get dodged or parried aren't generating any rage as they suppose to do, this was also reported on the warriors side but also affects druids.

https://github.com/Atlantiss/NetherwingBugtracker/issues/3846

_ISSUE 3_
Swipe area of effect seems reduced and conditioned to only hit mobs near current target. If you have three mobs in front of the bear and choose to use swipe on one of the side mobs, the mob located on the opposite side will not get hit. In order to hit all three mobs a bear has to arrange them closely together and use the middle mob as main target to spam swipe. This makes multimob tanking more difficult since only the two mobs next to current target get hit leading to agro loss on other mobs.

**Expected behaviour**: 
_ISSUE 1_
Special abilities should consume 20% of the spell's rage cost, and 80% of the spell cost should be refunded whenever they are being missed, dodged or parried.

_ISSUE 2_
Dodged or parried attacks should generate a similar amount of rage as if they would uncritically hit the target.

_ISSUE 3_
Two random mobs in front of the druid should get affected by swipe regardless of their position in relation to current target.

**Ingame Proof**:
_ISSUE 1_
https://youtu.be/9IU4-_-xXPI
@ 17s shows maul being missed and rage dropping from 16 to 6, confirming that full rage cost was considered on that miss.

_ISSUE 2_
https://youtu.be/aiSzI3inMXc
@ 4s a white autoattack gets dodge and no rage is generated from it.

https://youtu.be/YxbYkIIcays
@ 1m04s a white autoattack gets parried and no rage is generated from it. 

_ISSUE 3_
https://youtu.be/YxbYkIIcays
@ 8s and 11s both of these swipes only affect the main target which is the right mob, then the bear arrange them closely together and @ 14s swipe hits two out of three mobs while still having right mob as main target, then @ 16s main target is switched for the middle mob and all three mobs get affected by swipe. Then at 42s the middle mob dies and next swipe only hits the main target until the druid rearrange them closely together again. 

_All of these issues make druid tanking feel so broken mainly due to the rage starvation. Add the first two issues to the fact that Primal Fury (+5 rage on crits, more importantly +15 rage on tripple swipe crits) is also bugged, then one can realize how cripple this makes a druid tank in the current state._

Reference:
https://github.com/Atlantiss/NetherwingBugtracker/issues/3938  - Reported 29 days ago.

**Server Revision**: 
AtlantissCoreTBC - Server Revision: 2765 [Branch: master, Hash: e7f655bdb48f] 
2019-02-06

**Comment by Realnairoby** [comment]
Ye makes it complete hardmode for a feral to tank a simple normal dungeon. This should be on top-prio and be fixed asap

**Comment by DomitrekIndustries** [comment]
I would LOVE to see these fixed asap. Feral tanking is unBEARable right now

**Comment by ErothT** [comment]
I personally don't play a class with rage, but I have some sources for what rage generation was in the transition to 2.0 for level 70.

https://wowwiki.fandom.com/wiki/Rage?oldid=328639

**Comment by towneh** [comment]
https://web.archive.org/web/20080207225442/http://forums.wow-europe.com/thread.html?topicId=83678537&pageNo=1&sid=1

@ErothT the above URL is the archive page for the source that you're after.

**Comment by Wolffenstein** [comment]
Need retail proof for Issue 3 - its listed as a chain spell in client files.

Rest fixed in rev 2804.
