### ISSUE TITLE
Mokvar

### ISSUE THREAD

**Issue by Nadie19** [Atlantiss/NetherwingBugtracker#4872]
[//]: # (Enclose links to things related to the bug using http://wowhead.com or any other TBC database.)
[//]: # (You can use screenshot ingame to visual the issue.)
[//]: # (Write your tickets according to the format:)
[//]: # ([Quest][Azuremyst Isle] Red Snapper - Very Tasty!)
[//]: # ([NPC] Magistrix Erona)
[//]: # ([Spell][Mage] Fireball)
[//]: # ([Npc][Drop] Ghostclaw Lynx)
[//]: # ([Web] Armory doesnt work)
[//]: # (To find server revision type `.server info` command in the game chat.)
**Description**: 
 NPS https://www.wowhead.com/npc=16012/
**Current behaviour**:
Does not give a starting quest for classes,
**Expected behaviour**: 
Must give quest is a chain of quests on set d2
https://ru.wowhead.com/transmog-set=640/darkmantle-armor
**Server Revision**: 
2765
![wowscrnshot_020619_102250](https://user-images.githubusercontent.com/46890519/52326698-9cc17e00-29fa-11e9-8244-3ce8f5560797.jpg)

**Comment by wtRCH** [comment]
@Nadie19 Don't send messages to Kutsal regarding bugs, please. Thank q for the report.

**Comment by Manaci** [comment]
Fixed
