### ISSUE TITLE
[Druid][Core mechanic] Cat Form dodge chance

### ISSUE THREAD

**Issue by SlapZech** [Atlantiss/NetherwingBugtracker#4874]
Description: Dodge chance in druid's Cat Form is significantly lower then that stated by the character information screen. With 21.29% dodge chance I was only able to dodge about 5.8% of melee attacks, according to recount-gathered data.

Current behaviour: Druid's cat form dodge chance is calculated wrong.

Expected behaviour: Dodge chance should be higher.

Server Revision: 2765

**Comment by devo6969** [comment]
Did a 15 min segment. This report seems invalid.
https://i.imgur.com/YeC3T8Y.jpg
