### ISSUE TITLE
[Quest] Master of Potions: unable to turn in

### ISSUE THREAD

**Issue by Anselm123** [Atlantiss/NetherwingBugtracker#4877]
**Description**: I have all the items for the quest master of potions yet I cannot turn it in. I tried all the "fixes" people in discord suggest but none work. These are: deleting cache, relogging, trading the mats to a friend logging off and getting them back, disabling all addons and trying to hand it in. 

Nothing works.

**Current behaviour**: Have the book and all 3 types of potions I need in my bags, cannot turn it in.

**Expected behaviour**: be able to hand in the quest.

**Server Revision**: 2765

**Comment by Anselm123** [comment]
Ok you can close this I managed to make it work by doing everything together with disabling addons, restarting client, deleting cache AND trading the mats

**Comment by Brasso** [comment]
You can close it yourself you know. :)

**Comment by duzyizly** [comment]
putting potions to bank
rellogin'
taking 'em back
helps
:)

related https://github.com/Atlantiss/NetherwingBugtracker/issues/4846
