### ISSUE TITLE
Sunken Temple: Hakkar adds spawn too fast at the beginning of the encounter

### ISSUE THREAD

**Issue by cathabv** [Atlantiss/NetherwingBugtracker#4879]
**Description**: Hakkar adds dont spawn like they should

**Current behaviour**: All of the different mobs spawn at the start, incl non elite mobs, dragonkin and elite serpent

**Expected behaviour**: They should spawn gradually, first some non elites, then the dragonkin and elite serpent mobs in waves

**Comment by Gemuesesueppe** [comment]
Important, we wiped a couple of times and wasted hours, then gave up.

**Comment by Tereneckla** [comment]
Fixed
