### ISSUE TITLE
Bugged loot

### ISSUE THREAD

**Issue by therealqtpi** [Atlantiss/NetherwingBugtracker#4881]
Hi my group had the item The Green Tower drop, we all rolled on it but no one looted it and it wasn't on the body anymore, i'm the only one who rolled need so i'd have it if anything but it's just no where to be found, attached you'll see members rolling on the item when it dropped and then nobody getting it. Thank you so much for your time in the matter

![proof 1](https://user-images.githubusercontent.com/47369468/52365743-2a5e9700-2a16-11e9-9194-5e95d822e92b.png)
![proof 2](https://user-images.githubusercontent.com/47369468/52365744-2a5e9700-2a16-11e9-9737-b979eedad9cc.png)
![proof 3](https://user-images.githubusercontent.com/47369468/52365745-2a5e9700-2a16-11e9-85c2-522f38f6afcb.png)
![proof 4](https://user-images.githubusercontent.com/47369468/52365746-2a5e9700-2a16-11e9-847e-970ef51fb703.png)
![proof 5](https://user-images.githubusercontent.com/47369468/52365747-2af72d80-2a16-11e9-9700-2d77b8c351a1.png)
![proof 6](https://user-images.githubusercontent.com/47369468/52365748-2af72d80-2a16-11e9-8021-93b0847dff0b.png)

**Comment by Manaci** [comment]
Fixed with loot rework
