### ISSUE TITLE
[Quest] [Wailing Caverns] Deviate Hides not available for Alliance

### ISSUE THREAD

**Issue by Polybolos** [Atlantiss/NetherwingBugtracker#4882]
[//]: # (Enclose links to things related to the bug using http://wowhead.com or any other TBC database.)
[//]: # (You can use screenshot ingame to visual the issue.)
[//]: # (Write your tickets according to the format:)
[//]: # ([Quest][Azuremyst Isle] Red Snapper - Very Tasty!)
[//]: # ([NPC] Magistrix Erona)
[//]: # ([Spell][Mage] Fireball)
[//]: # ([Npc][Drop] Ghostclaw Lynx)
[//]: # ([Web] Armory doesnt work)
[//]: # (To find server revision type `.server info` command in the game chat.)

**Description**: 
[Quest] Deviate Hides unavailable on Alliance.

**Current behaviour**:
Was unable to pick the quest. According to wowhead there are no prerequesites for it.

**Expected behaviour**: 
Should be available for both factions.
Proof: https://www.wowhead.com/quest=1486/deviate-hides

**Server Revision**: 
2765

**Comment by Vyriam** [comment]
This quest is still not obtainable by Alliance faction members, although it should be...
Patch 2.2.0

Server Revision : 3119
