### ISSUE TITLE
Druid and Warrior shouts not giving threat

### ISSUE THREAD

**Issue by staplerx300** [Atlantiss/NetherwingBugtracker#4884]
[//]: # (Enclose links to things related to the bug using http://wowhead.com or any other TBC database.)
[//]: # (You can use screenshot ingame to visual the issue.)
[//]: # (Write your tickets according to the format:)
[//]: # ([Quest][Azuremyst Isle] Red Snapper - Very Tasty!)
[//]: # ([NPC] Magistrix Erona)
[//]: # ([Spell][Mage] Fireball)
[//]: # ([Npc][Drop] Ghostclaw Lynx)
[//]: # ([Web] Armory doesnt work)
[//]: # (To find server revision type `.server info` command in the game chat.)

**Description**: 
Demo shout and Battle Shout aren't giving correct amounts of threat, it appears to be 0 or almost 0

**Current behaviour**:

**Expected behaviour**: 
It should be giving a static amount of threat for demo shout and the druid demo shout, and battle shout should be scaling with the amount of party members receiving the buff

**Server Revision**:

**Comment by Zarant** [comment]
Most private servers I played, battle shout is treated as a healing spell, in the sense that all the threat generated is divided evenly among all targets nearby, that's worth investigating.

**Comment by femdead** [comment]
yes it should be

**Comment by Wolffenstein** [comment]
Fixed in rev 2777.

**Comment by femdead** [comment]
was rev 2777 supposed to be today because still broken

**Comment by Easyfraggy** [comment]
> Most private servers I played, battle shout is treated as a healing spell, in the sense that all the threat generated is divided evenly among all targets nearby, that's worth investigating.

It is true that it should be dicided - but healing spells are not divided untill wotlk.
