### ISSUE TITLE
Skullflame Shield - incorrect spell damage scaling

### ISSUE THREAD

**Issue by scruffer** [Atlantiss/NetherwingBugtracker#4886]
**Description**: Skullflame Shield has a history of full, 100% spell damage ratio scaling on its life drain at least into mid-way WOTLK and I can find no information describing when it actually lost its coefficient scaling. This shield is very useful for protection paladins, and since we cannot access Molten Core to create Force Reactive Disk, this is our next best alternative - please fix this item for us!

**Current behaviour**:
"Equip: When struck in combat has a 3% chance of stealing 35 life from target enemy."
Skullflame Shield on Netherwing only has about ~38% spell damage scaling on its lifedrain. This value is only correct for the flamestrike effect on the fire explosion.

**Expected behaviour**: Skullflame Shield's 3% life-steal should scale with 100% of your equipped spell damage value.
Added in 1.11 Classic/Vanilla Warcraft, this item had full scaling for the entire span of TBC
There are many posts detailing the math behind this shield and their results from using it, this particular example is from a player posting from the year 2008 during the 2.4.3 patch.
https://puu.sh/CQmEt/3b4764b358.png
https://www.wowhead.com/item=1168/skullflame-shield#comments

**Server Revision**: 2825

**Comment by Wolffenstein** [comment]
Fixed in rev 2831.
