### ISSUE TITLE
[Raid][Karazhan][NPC] Maiden of Virtue Yell emotes incorrect.

### ISSUE THREAD

**Issue by Imbaslap** [Atlantiss/NetherwingBugtracker#4887]
[//]: # (Enclose links to things related to the bug using http://wowhead.com or any other TBC database.)
[//]: # (You can use screenshot ingame to visual the issue.)
[//]: # (Write your tickets according to the format:)
[//]: # ([Quest][Azuremyst Isle] Red Snapper - Very Tasty!)
[//]: # ([NPC] Magistrix Erona)
[//]: # ([Spell][Mage] Fireball)
[//]: # ([Npc][Drop] Ghostclaw Lynx)
[//]: # ([Web] Armory doesnt work)
[//]: # (To find server revision type `.server info` command in the game chat.)

**Description**: 
Currently on Netherwing, Maiden of Virtue has incorrect Yell emotes for her abilities being used. causing an issue with DBM not working correctly for timers.
**Current behaviour**:
Whenever Maiden of Virtue casts Holy Fire, she emotes "Your impurity must be cleansed.". whenever she casts repentance, she emotes "Cast out your corrupt thoughts."
**Expected behaviour**: 
Maiden of Virtue is supposed to emote "Your impurity must be cleansed." or "Cast out your corrupt thoughts." when she casts Repentance only, NOT when she casts Holy Fire. she should not Emote anything during holy fire casts. 
**Server Revision**: 
Source: TBC Maiden: 
https://www.youtube.com/watch?v=UmyDNcTpI2I
https://www.youtube.com/watch?v=Dwh1nU17gJM

**Comment by Evolvee** [comment]
fixed?
