### ISSUE TITLE
[Core][Flying Mount] Currently able to get sapped in the air in flying mount.

### ISSUE THREAD

**Issue by killablink** [Atlantiss/NetherwingBugtracker#4889]
**Description**: You can get sapped in the air

**Current behaviour**: You can get sapped in the air

**Expected behaviour**:  Shouldn't be able. #2999

**Server Revision**: 2770

**Comment by killablink** [comment]
Cyclone too

**Comment by Wolffenstein** [comment]
Fixed in rev 2776.

**Comment by knasen88** [comment]
?? flying =! invincibility
all stunning a flying mount is 100% possible
