### ISSUE TITLE
Mana Shifter#16310 uses wrong rank of Arcane Explosion.

### ISSUE THREAD

**Issue by Tenoutoften** [Atlantiss/NetherwingBugtracker#489]
**Description**: 
Mana Shifter#16310(https://db.excalibur.ws/?npc=16310#abilities) currently uses an Arcane Explosion dealing ~25-28 arcane damage(https://i.gyazo.com/ad8e588bf14bd132d1b2bae697863237.png), costing ~70 mana. According to excalibur database(https://db.excalibur.ws/?spell=29106) it should be using  Arcane Explosion#29106 costing 120 mana dealing 55 to 60 arcane damage(https://i.gyazo.com/12b03ba1e83f472939357720ca001c70.png).

The database also claims the creature should have 199 mana while it got 200 mana currently.

**Current behaviour**:
Manashifter#16310 possibly using a too low rank of Arcane Explosion.

**Expected behaviour**: 
Expect Manashifter#16310 to use Arcane Explosion#29106

**Server Revision**: 
2048

**Comment by Evolvee** [comment]
it already uses the same spell ID that you reported:
![image](https://user-images.githubusercontent.com/1942409/46018030-3a19b680-c0d9-11e8-87f0-449296d2bfba.png)


the spell is scaling so it doesnt do the "tooltip" damage

**Comment by Tenoutoften** [comment]
My bad, I figured since it was dealing the same as it's regular attack it would potentially be wrong. Is there anyway for me to spellID casted as a regular tester?

**Comment by Evolvee** [comment]
nope
