### ISSUE TITLE
Warlock Imp Dissappears

### ISSUE THREAD

**Issue by V3n1m** [Atlantiss/NetherwingBugtracker#4891]
**Description**:  Warlock Imp Pet will not be resummoned after dismounting a flying mount.

**Current behaviour**: It's totaly random, sometimes it works, sometimes not

**Expected behaviour**: Pets should appear after dismounting

**Server Revision**:

**Comment by The14me** [comment]
Must be fixed in rev. 3450
[Core/Unit]:
- Unit::Dismount will now properly remove all mount auras
