### ISSUE TITLE
[Rogue] Distract and Sap triggering guards

### ISSUE THREAD

**Issue by someotherplayer** [Atlantiss/NetherwingBugtracker#4895]
**Current behaviour**:
The rogues spells Sap and Distract are considered offensive spells and trigger neutral guards.

**Expected behaviour**: 
Using these spells on an enemy player should not make neutral guards agressive.

**Server Revision**: 
2770

**Comment by ScottieDOESknow** [comment]
working as intended


![image](https://user-images.githubusercontent.com/43949261/52487399-8eef3280-2b8b-11e9-8039-4c07811559b7.png)
