### ISSUE TITLE
Battleground stuck in graveyard, can't ressurect

### ISSUE THREAD

**Issue by Mikik3jr** [Atlantiss/NetherwingBugtracker#4897]
[//]: # (Enclose links to things related to the bug using http://wowhead.com or any other TBC database.)
[//]: # (You can use screenshot ingame to visual the issue.)
[//]: # (Write your tickets according to the format:)
[//]: # ([Quest][Azuremyst Isle] Red Snapper - Very Tasty!)
[//]: # ([NPC] Magistrix Erona)
[//]: # ([Spell][Mage] Fireball)
[//]: # ([Npc][Drop] Ghostclaw Lynx)
[//]: # ([Web] Armory doesnt work)
[//]: # (To find server revision type `.server info` command in the game chat.)

**Description**: 
When you die in a BG you are teleported to a graveyard and an NPC ressurecter is there that ressurects every 30s.

**Current behaviour**:
If you die the following is randomly (when they remove the insignia?) happening:
- Your soul CAN'T move at all, you are stuck there.
- If you cancel the ress from the NPC you CAN'T talk to that NPC again, you can't be ressed manually, because your body disappears.
2nd point sucks more, because it can happen, that when you die, the ressurected NPC revives everyone exactly that time, so you have to cancel the ressurect to start the timer again, BUT with this bug, you can't do it. You can only leave, to give your place to someone else.
![image](https://user-images.githubusercontent.com/43505031/52429588-9e776880-2b04-11e9-8c3e-85dcf2cdecd8.png)

**Expected behaviour**: 
I should be able to talk to the NPC autoresser in the graveyards in battlegrounds.

**Server Revision**: 
2770

**Comment by Mikik3jr** [comment]
Maybe it is connected that they remove my insignia or what.

**Comment by Zarant** [comment]
Sometimes I get ported to the graveyard and my character's ghost is lying down, unable to move. It's seemingly random, sometimes I get stuck on the graveyard sometimes I don't.

**Comment by Godmatik** [comment]
Fixed a long time ago.
