### ISSUE TITLE
[Item][Nagrand] Oshu'gun Crystal Powder Sample

### ISSUE THREAD

**Issue by yesthisisnick** [Atlantiss/NetherwingBugtracker#4898]
[//]: # (Enclose links to things related to the bug using http://wowhead.com or any other TBC database.)
[//]: # (You can use screenshot ingame to visual the issue.)
[//]: # (Write your tickets according to the format:)
[//]: # ([Quest][Azuremyst Isle] Red Snapper - Very Tasty!)
[//]: # ([NPC] Magistrix Erona)
[//]: # ([Spell][Mage] Fireball)
[//]: # ([Npc][Drop] Ghostclaw Lynx)
[//]: # ([Web] Armory doesnt work)
[//]: # (To find server revision type `.server info` command in the game chat.)

**Description**: 
I have collected both the Horde version and Alliance version of the powder samples as a Horde player
**Current behaviour**:
Horde players can collect Alliance designated powder samples 
**Expected behaviour**: 
Each faction can only collect their respected factions powder samples
**Server Revision**: 
2770
![hordepowder](https://user-images.githubusercontent.com/46409107/52431625-37d75800-2ace-11e9-9b1f-99eeef31578d.PNG)
![alliancepowder](https://user-images.githubusercontent.com/46409107/52431631-3b6adf00-2ace-11e9-8d53-fdf38f074e6a.PNG)

**Comment by Zeref09731** [comment]
I was able to reproduce this issue as well.  Unexpected item only dropped off of voidspawns near Oshu'gun based on brief testing.

![oshu gun_powder](https://user-images.githubusercontent.com/43506920/53772175-71c03200-3eb3-11e9-9875-4fc9dfaed130.jpg)

**Comment by Manaci** [comment]
Fixed
