### ISSUE TITLE
[Quest][Zone:Netherstorm] Dimensius the All-Devourer: Captain doesn't spawn.

### ISSUE THREAD

**Issue by jorgehog** [Atlantiss/NetherwingBugtracker#4899]
**Description**: 
Dimensius quest line. Around 18:30 a ally rogue started the captain off but didn't follow him (he was solo). A few min after that the ethereals back at the camp (that are supposed to follow him) despawned. Now 30 min later captain and his army is still missing.
**Current behaviour**:
Captain doesn't respawn (30m waited).

**Expected behaviour**: 
Captain respawns if attempt is failed.

**Server Revision**: 
2770

**Comment by jorgehog** [comment]
Did the quest today after the server crash around 6:30. The captain was up and everything worked flawlessly. Seems like there is a potential way of getting into an unrecoverable bugged state.

**Comment by Easyfraggy** [comment]
https://github.com/Atlantiss/NetherwingBugtracker/issues/4599

**Comment by Macumbafeh** [comment]
Tons of person waiting for his spawn.... he never spawn... can you do something pls?
