### ISSUE TITLE
[Quest] Help Tavara

### ISSUE THREAD

**Issue by Camarila** [Atlantiss/NetherwingBugtracker#49]
[//]: # (Enclose links to things related to the bug using http://wowhead.com or any other TBC database.)
[//]: # (You can use screenshot ingame to visual the issue.)
[//]: # (Write your tickets according to the format:)
[//]: # ([Quest][Azuremyst Isle] Red Snapper - Very Tasty!)
[//]: # ([NPC] Magistrix Erona)
[//]: # ([Spell][Mage] Fireball)
[//]: # ([Npc][Drop] Ghostclaw Lynx)
[//]: # ([Web] Armory doesnt work)

**Description**:  Quest 'Help Tavara' doesn't work. W

**Current behaviour**:  When healed with either lesser healer or or Gift of the Naaru the draenei passive or shielded it doesn't do any change to the quest.  Only works after server crash, when everything resets.

**Expected behaviour**: Should get healed and the quest completed, I assume?

**Server Revision**:

**Comment by Evolvee** [comment]
will be fixed in next hotfix rev

**Comment by Godmatik** [comment]
Still broken

**Comment by Wolffenstein** [comment]
I just completed it on Karazhan multiple times, works fine.

**Comment by Godmatik** [comment]
When I tried it yesterday, Tavara was already at 100% health, and my healing didn't trigger any quest completion, will check again later today to see if it is still the case.
