### ISSUE TITLE
Goldmist Village missing several patrols

### ISSUE THREAD

**Issue by Tenoutoften** [Atlantiss/NetherwingBugtracker#490]
**Description & Current behaviour**:
Goldmist Village is very lifeless looking at the moment with zero patroling mobs, at least I sat around for quite a while and saw no patrols. This is a level 10-13 place and should definitely have a few patrols.

From later expansion retail you can see that this place has a few patrols.
https://youtu.be/nUUUJ7GnnIk?t=108
https://youtu.be/1eatw4dOQyU?t=97
https://youtu.be/oLA18zP1paw?t=74

**Expected behaviour**: 
I'd expect based on how similar places are in WoW that this village should have a few patrols as seen in the videos I provided - granted that these are from later expansions, but I highly doubt Blizzard added these patrols way later on.

**Server Revision**: 
2048

**Comment by aresbrutus** [comment]
Will be fixed in one of the upcoming updates.
