### ISSUE TITLE
[Dungeon][NPC] Lieutenant Drake Exploding Shot

### ISSUE THREAD

**Issue by rychersky** [Atlantiss/NetherwingBugtracker#4900]
[//]: # (Enclose links to things related to the bug using http://wowhead.com or any other TBC database.)
[//]: # (You can use screenshot ingame to visual the issue.)
[//]: # (Write your tickets according to the format:)
[//]: # ([Quest][Azuremyst Isle] Red Snapper - Very Tasty!)
[//]: # ([NPC] Magistrix Erona)
[//]: # ([Spell][Mage] Fireball)
[//]: # ([Npc][Drop] Ghostclaw Lynx)
[//]: # ([Web] Armory doesnt work)
[//]: # (To find server revision type `.server info` command in the game chat.)

**Description**: This ability is meant to be used if the tank is at ranged after his Whirlwind cast finishes (similar to Murmur's ability if the tank doesn't run back in quick enough). As it is now, he will use it when the tank is standing in melee range when he finishes Whirlwind.

**Server Revision**: 2770

**Comment by Wolffenstein** [comment]
Fixed in rev 2777.
