### ISSUE TITLE
Guild disappeared

### ISSUE THREAD

**Issue by Beutelteufel1** [Atlantiss/NetherwingBugtracker#4901]
**Description**: 
Complete Guild seems to have disappeared (name: Herrenjedeck). At least me (guildmaster) and my friend cannot see the guild anymore, dont know about other members who were only in it because they signed the charter for us. 
Is there a way to get it back?

**Comment by The14me** [comment]
Suppose to be fixed with the Guild rework that happens before...like half of the year?
