### ISSUE TITLE
Noraani in Telredor doesn't show up on minimap

### ISSUE THREAD

**Issue by Joxur** [Atlantiss/NetherwingBugtracker#4902]
[//]: # (Enclose links to things related to the bug using http://wowhead.com or any other TBC database.)
[//]: # (You can use screenshot ingame to visual the issue.)
[//]: # (Write your tickets according to the format:)
[//]: # ([Quest][Azuremyst Isle] Red Snapper - Very Tasty!)
[//]: # ([NPC] Magistrix Erona)
[//]: # ([Spell][Mage] Fireball)
[//]: # ([Npc][Drop] Ghostclaw Lynx)
[//]: # ([Web] Armory doesnt work)
[//]: # (To find server revision type `.server info` command in the game chat.)

**Description**:  When selecting the "Reagent" filter from the mini-map, Noraani in Telredor does not show up on the minimap

**Current behaviour**: She doesn't show up as a gold dot on the mini-map.

**Expected behaviour**:  She should show up as a gold dot on the mini-map with the reagent filter selected.

**Server Revision**:  2770

**Comment by Evolvee** [comment]
rev 2800
