### ISSUE TITLE
[Quest] Natural Remedies (Hellfire Peninsula): Pathaleon's Image Using Wrong Text

### ISSUE THREAD

**Issue by glubglub1337** [Atlantiss/NetherwingBugtracker#4903]
**Description**: In Hellfire Peninsula on the quest Natural Remedies you use an item near the giant red crystal in the western end of the zone. This causes an image of Pathaleon the Calculator to appear and his image does a bit of dialogue before summoning a colossus and vanishing. Currently he uses the wrong dialogue during this event, and instead uses his dialogue from Firewing Point in another zone.

**Current behaviour**: Pathaleon the Calculator uses his dialogue from Terokkar Forest, when he should be using dialogue from Hellfire Penninsula.

**Expected behaviour**: He should say, "And just what do you think you are doing? You dare to interfere with the master's experiment?" "Do you like what we've done here? Perhaps we will drop these crystals from the sky all over Outland. " "I grow bored with you attempts to heal the land and quell the energies summoning and driving the colossi mad. Goliathon, King of the Colossi, Prince Kael'thas and I demand that you defend the crystal! " "We will meet again soon. "

See this for all his dialogue: https://wowwiki.fandom.com/wiki/Pathaleon_the_Calculator%27s_Image

**Comment by Evolvee** [comment]
rev 2793
