### ISSUE TITLE
Mail sent to another character is not recieved nor being returned to sender.

### ISSUE THREAD

**Issue by shefHauwanga** [Atlantiss/NetherwingBugtracker#4904]
**Description**: Mail messages with items are not reaching recipients. The items are not returned to their sender and the postal cost is not refunded. 
**Current behavior**: When attempting to send one message with multiple items to another character as well as a second message with a single item and some currency the messages disappear. Neither message were received, the postal cost has been removed and the items have not been returned to the sender.
**Expected behaviour**: The items should be in the recipient's mailbox or they should be returned to the sender mailbox and the postal cost should be refunded.
**Server Revision**: 2771

**Comment by Tereneckla** [comment]
rev 3058
