### ISSUE TITLE
[API] SetRaidSubgroup() and SwapRaidSubgroup()

### ISSUE THREAD

**Issue by hitbutton** [Atlantiss/NetherwingBugtracker#4906]
**Description**: The API functions SetRaidSubgroup() and SwapRaidSubgroup() are not currently working correctly, causing issues for the Blizzard interface and AddOns.

**Current behaviour**: SwapRaidSubgroup() does not appear to function at all. This causes the Blizzard raid window to bug out when you drag a raid member from one group on top of a raid member in another group, and the group members are not swapped.

SetRaidSubgroup() is PROTECTED during combat, preventing it from being called by non-Blizzard AddOns. I can find no evidence for this API function being protected at any point during TBC. This prevents players from being able to work around the issues caused by SwapRaidSubgroup() not functioning.

**Expected behaviour**: SwapRaidSubgroup() should be a PROTECTED function which takes the raid index of two raid members as arguments and swaps their raid subgroups.
https://wowwiki.fandom.com/wiki/API_SwapRaidSubgroup?oldid=1399153

SetRaidSubgroup() should not be PROTECTED during combat.
https://wowwiki.fandom.com/wiki/API_SetRaidSubgroup?oldid=1020137

**Server Revision**: 
2771

**Comment by Zarant** [comment]
I might be wrong here, but Isn't that a client side issue?

**Comment by hitbutton** [comment]
SwapRaidSubgroup() being entirely nonfunctional and preventing the Blizzard interface from working correctly is not a client side issue.

It's possible that SetRaidSubgroup() being protected is enforced by the client, which would invalidate that part of the issue. However it seems odd to me that it would be subject to that limitation, which is not mentioned in API documentation from the time.

**Comment by Tenoutoften** [comment]
This is definitely quite frustrating but I think this report is just going to be lost in this huge pile of reports

**Comment by Picajzla** [comment]
It did get lost :D
