### ISSUE TITLE
[NPC] [Zangermarsh] [Feralfen Serpent Stalker Not Despawning]

### ISSUE THREAD

**Issue by glubglub1337** [Atlantiss/NetherwingBugtracker#4907]
**Description**: Feralfen Serpent Stalker NPC is spawning new copies, but none are despawning. There are now over a half dozen Feralfen Serpant Stalkers in Feralfen Village on the steps to of the structure to the south, coords 43.6, 66.4

**Current behaviour**: Feralfen serpent stalkers keep spawning, none are despawning

**Expected behaviour**:  These mobs should despawn after a period of time

https://imgur.com/a/wqDpvAW

**Comment by The14me** [comment]
Rev.3460 Not an issue anymore. Totem and the Serpent despawn in a 30 sec.
