### ISSUE TITLE
[NPC] Void Terror Skinning

### ISSUE THREAD

**Issue by transphenomenal** [Atlantiss/NetherwingBugtracker#4908]
[//]: # (Enclose links to things related to the bug using http://wowhead.com or any other TBC database.)
[//]: # (You can use screenshot ingame to visual the issue.)
[//]: # (Write your tickets according to the format:)
[//]: # ([Quest][Azuremyst Isle] Red Snapper - Very Tasty!)
[//]: # ([NPC] Magistrix Erona)
[//]: # ([Spell][Mage] Fireball)
[//]: # ([Npc][Drop] Ghostclaw Lynx)
[//]: # ([Web] Armory doesnt work)
[//]: # (To find server revision type `.server info` command in the game chat.)

**Description**: 
The Void Terrors at Death's Door in Blades Edge Mountains are unskinnable.

**Current behaviour**:
The Void Terrors do not give the option to skin them.

**Expected behaviour**: 
A message under their Tooltip that indicate they can be skinned, as well as the capacity of being skinned.

**Server Revision**: 
2771

**Comment by lynxzor** [comment]
Actually not skinnable until patch [2.2](https://wow.gamepedia.com/Patch_2.2.0)

**Comment by Manaci** [comment]
Irrelevant now

**Comment by Evolvee** [comment]
will need to be fixed for future

**Comment by Evolvee** [comment]
fixed in next rev
