### ISSUE TITLE
[NPC] [The Underbog] Windcaller Claw

### ISSUE THREAD

**Issue by iCammy** [Atlantiss/NetherwingBugtracker#4909]
**Description**: The Boss/Quest NPC "Claw" in the dungeon "The Underbog" has become invulnerable to incoming damage, making passage through the area as well as defeating the boss impossible.

**Current behaviour**: "Claw" will join battle alongside the other boss NPC Swamplord Musel'ek as normal, but once defeated, if the party fails to defeat Musel'ek and must reattempt the fight, "Claw" will no longer take damage, and thus be unable to be tanked or controlled, upon fight end he will stay where he was last positioned in a hostile state.

**Expected behaviour**: "Claw" should simply be engaged as previously for the fight's reattempt, taking damage at the standard rate, and become friendly once defeated just as the first attempt, resuming position near Musel'ek once leaving combat due to failing to defeat the boss.

**Server Revision**:  2771

**Comment by The14me** [comment]
Since the related issue get fixed, that must be ok too.
