### ISSUE TITLE
[Item] Scroll of Protection

### ISSUE THREAD

**Issue by Pennywise4569** [Atlantiss/NetherwingBugtracker#491]
[//]: # (Enclose links to things related to the bug using http://wowhead.com or any other TBC database.)
[//]: # (You can use screenshot ingame to visual the issue.)
[//]: # (Write your tickets according to the format:)
[//]: # ([Quest][Azuremyst Isle] Red Snapper - Very Tasty!)
[//]: # ([NPC] Magistrix Erona)
[//]: # ([Spell][Mage] Fireball)
[//]: # ([Npc][Drop] Ghostclaw Lynx)
[//]: # ([Web] Armory doesnt work)

**Description**: Scroll of Protection will cast, and remove a Paladin's Devotion Aura, even if it is a weaker version of the spell.

**Current behaviour**: Using a Scroll of Protection as a paladin with Devotion Aura turns off your aura and overrides it.

**Expected behaviour**: Typically "A more powerful spell is active" will appear in these circumstances.

**Server Revision**:

**Comment by Wolffenstein** [comment]
Fixed in rev 2055.
