### ISSUE TITLE
[talent] 1 handed weapon speceliaztion only increases auto attack white damage (prot paladin)

### ISSUE THREAD

**Issue by totalscrubking** [Atlantiss/NetherwingBugtracker#4910]
**Description**: [talent] prot paladin talent 1 handed weapon specelization does not increase all damage done and only his white attacks

**Current behaviour**: the talent description states that all damage the paladin does is boosted by 5%. i know weapon spec on prot and ret seems to be buggy on servers so i saved my talent points and dumped them all into one handed spec all at once. none of the paladins damage such as seal of righeouss, judge, cons, or other abilities/effects that increased by this talent with a 1 handed equiped.

**Expected behaviour**: this talent should should increase all damage by the prot paladin by 5%, not just auto attacks. 

thanks developers.

**Server Revision**: 2771

**Comment by totalscrubking** [comment]
further proof other then the spells tool tip: 

https://www.engadget.com/2008/01/22/build-shop-paladin-0-46-15/

**Comment by Tenoutoften** [comment]
Pretty important to get this fixed

**Comment by Tenoutoften** [comment]
We had a prot paladin test this and it worked for him

**Comment by totalscrubking** [comment]
that is very strange as i was sure i gained not even 1 more damage were added on those abilities for me. ill respec and try again
