### ISSUE TITLE
Wrong materials needed for Super Healing Potion in Alchemy

### ISSUE THREAD

**Issue by Mikik3jr** [Atlantiss/NetherwingBugtracker#4912]
[//]: # (Enclose links to things related to the bug using http://wowhead.com or any other TBC database.)
[//]: # (You can use screenshot ingame to visual the issue.)
[//]: # (Write your tickets according to the format:)
[//]: # ([Quest][Azuremyst Isle] Red Snapper - Very Tasty!)
[//]: # ([NPC] Magistrix Erona)
[//]: # ([Spell][Mage] Fireball)
[//]: # ([Npc][Drop] Ghostclaw Lynx)
[//]: # ([Web] Armory doesnt work)
[//]: # (To find server revision type `.server info` command in the game chat.)

**Description**: 
In Alchemy you can make Super Healing Potion.

**Current behaviour**:
The materials are now:
- 2 Netherbloom
- 1 Felweed
- 1 Imbued Vial

**Expected behaviour**: 
You should need:
- 2 Dreaming Glory
- 1 Felweed
- 1 Imbued Vial

[According to 2.1 patch notes: "Super Healing Potions now require 2 Netherbloom instead of 2 Dreaming Glory to create.."](https://wowwiki.fandom.com/wiki/Patch_2.1.0)
**Server Revision**: 
2771

**Comment by Tenoutoften** [comment]
Should close based upon https://github.com/Atlantiss/NetherwingBugtracker/issues/3366#issuecomment-450550188  referensing https://github.com/ccshiro/cc-buglist/issues/2103#issuecomment-186312863

>We're unable to change the mats requirements client-side. If we change the required mats server-side you need both the mats the client displays (so it lets you press the Enchant button) and the mats the server requires. That is too iffy an experience for us to change this.
