### ISSUE TITLE
[Quest] The battle for Arathi Basin! not working

### ISSUE THREAD

**Issue by rikhx** [Atlantiss/NetherwingBugtracker#4916]
[//]: # (Enclose links to things related to the bug using http://wowhead.com or any other TBC database.)
[//]: # (You can use screenshot ingame to visual the issue.)
[//]: # (Write your tickets according to the format:)
[//]: # ([Quest][Azuremyst Isle] Red Snapper - Very Tasty!)
[//]: # ([NPC] Magistrix Erona)
[//]: # ([Spell][Mage] Fireball)
[//]: # ([Npc][Drop] Ghostclaw Lynx)
[//]: # ([Web] Armory doesnt work)
[//]: # (To find server revision type `.server info` command in the game chat.)

**Description**: The horde AB quest for the tabard is not working

**Current behaviour**: Doesnt register when you cap a base

**Expected behaviour**: Should register when you cap a base

**Server Revision**: 2771

**Comment by Tereneckla** [comment]
fixed rev 3166
