### ISSUE TITLE
[Dungeon][Heroic] Shadow Labs - Murmur dropped Belt of Depravity

### ISSUE THREAD

**Issue by Desst** [Atlantiss/NetherwingBugtracker#4917]
**Description**: 
title

**Expected behaviour**:  Belt of depravity should drop from last boss in Arcatraz heroic

**Server Revision**: 2771

**Comment by Brasso** [comment]
![image](https://user-images.githubusercontent.com/44345420/52510209-5dae4b00-2bfb-11e9-92ca-7e04fd48d5bd.png)

We are in patch 2.0.

**Comment by Jalapan** [comment]
i dont understand? its correct, its suppose to drop for murmur in patch 2.0 and when patch 2.1 comes its from harbinger skyriss.
