### ISSUE TITLE
Names not auto-completing properly from friends list.

### ISSUE THREAD

**Issue by BorisTehBlade** [Atlantiss/NetherwingBugtracker#4918]
[//]: # (Enclose links to things related to the bug using http://wowhead.com or any other TBC database.)
[//]: # (You can use screenshot ingame to visual the issue.)
[//]: # (Write your tickets according to the format:)
[//]: # ([Quest][Azuremyst Isle] Red Snapper - Very Tasty!)
[//]: # ([NPC] Magistrix Erona)
[//]: # ([Spell][Mage] Fireball)
[//]: # ([Npc][Drop] Ghostclaw Lynx)
[//]: # ([Web] Armory doesnt work)
[//]: # (To find server revision type `.server info` command in the game chat.)

**Description**: Names do not auto-complete properly from the friends list.

**Current behaviour**: When trying to send mail to someone in my friends list (who is not in my guild), the name will not auto-complete until after I open my friends list in game. Once I open the friends list it works properly. The issue does not extend to names of people in my guild.

**Expected behaviour**: Names on your friends list should always auto-complete in the mail system.

**Server Revision**: 2771 [Branch: battlegrounds, Hash:a162f79fb853]

**Comment by devo6969** [comment]
Doesn't seem to be an issue currently on the PTR. 
https://www.youtube.com/watch?v=dSRCqgOxkGQ
