### ISSUE TITLE
Hunter Pet Does Not Cancel Attack Upon Target CC

### ISSUE THREAD

**Issue by MelEnt** [Atlantiss/NetherwingBugtracker#4919]
[//]: # (Enclose links to things related to the bug using http://wowhead.com or any other TBC database.)
[//]: # (You can use screenshot ingame to visual the issue.)
[//]: # (Write your tickets according to the format:)
[//]: # ([Quest][Azuremyst Isle] Red Snapper - Very Tasty!)
[//]: # ([NPC] Magistrix Erona)
[//]: # ([Spell][Mage] Fireball)
[//]: # ([Npc][Drop] Ghostclaw Lynx)
[//]: # ([Web] Armory doesnt work)
[//]: # (To find server revision type `.server info` command in the game chat.)

**Description**: 
Hunter Pet does not cancel attacking a target that has been frozen solid by Freezing Trap
**Current behaviour**:
Hunter Pet does not cancel attacking a target that has been frozen solid by Freezing Trap

**Expected behaviour**: 
Hunter Pet should cancel attacking and either 1. prioritise walk back to owner regardless of mode or 2. attack the next target (if there is and if pet is on defensive/aggro mode).
**Server Revision**: 
2771

EDIT: clarification

**Comment by dalabu** [comment]
As show in the video : https://streamable.com/u9g2d
Please fix before 13th :)

**Comment by NatsumeLily** [comment]
Bump.
