### ISSUE TITLE
Reinforced Fel Iron Chest (Hellfire Ramparts)

### ISSUE THREAD

**Issue by Johnkeyz** [Atlantiss/NetherwingBugtracker#4920]
[//]: # (Enclose links to things related to the bug using http://wowhead.com or any other TBC database.)
[//]: # (You can use screenshot ingame to visual the issue.)
[//]: # (Write your tickets according to the format:)
[//]: # ([Quest][Azuremyst Isle] Red Snapper - Very Tasty!)
[//]: # ([NPC] Magistrix Erona)
[//]: # ([Spell][Mage] Fireball)
[//]: # ([Npc][Drop] Ghostclaw Lynx)
[//]: # ([Web] Armory doesnt work)
[//]: # (To find server revision type `.server info` command in the game chat.)

**Description**: 
So 3/5 died against vazruden, me and the hunter lived... NO ONE released spirit, and i looted chest. But apparently only me and hunter was able to roll on the items in the chest... So our shaman missed both a healer ring and mail healer / caster legs. Unsure if i have filled this out correctly, if i haven't i apologize.

**Current behaviour**:
If people are dead but haven't released spirit, and chest is looted, they can't roll on it.

**Expected behaviour**: 
Pretty sure you can roll on items, if you don't release spirit, and always have been able to.

**Server Revision**: 
Netherwing server

**Comment by Godmatik** [comment]
Unable to reproduce
All dead characters were able to roll on items once chest was looted with no issue
