### ISSUE TITLE
[Hunter][Spell] Hunter's Mark

### ISSUE THREAD

**Issue by Zarant** [Atlantiss/NetherwingBugtracker#4921]
**Description**:  Casting Hunter's Mark should cancel eating/drinking buffs on its target.

**Current behaviour**: Sometimes the first application of Hunter's Mark stop other players from drinking but casting it a second time does nothing.

**Expected behaviour**:  Casting Hunter's Mark on other players while they are eating/drinking should stop them from eating or drinking.

Source: 

> So a while back they implemented a change that made any DoT that lands on you make you stand up and stop drinking when you are OOC and Drinking (or sitting in general). I was very anti this buff because it benefits warlocks the most who don't need anymore buffs in 2s and 3s.
> 
> Anyways I was messing around and Hunter's Mark (Rank 1-4) also does this effect, from 100yd range. Has situational uses seeing as it doesn't work through LoS, but it has 0 travel time and most players will assume combat if you're coming at them and they auto-stand up.

http://web.archive.org/web/20181217184015/http://www.arenajunkies.com/topic/10029-tip-for-hunters/

It also leads to believe based on this source that any debuff application should have the same effect.

**Server Revision**:  2771

**Comment by Tenoutoften** [comment]
It's questionable if this mechanic was keept in the game for much further.
Reading your "evidence/link" a priest mentions it works the same on Mind Vision, however just a few posts later another posts reads:
>Mindvision got fixed. 

Makes it questionable if Hunter's Mark canceling effect wasn't fixed... This is posted from February 2008 and there are many months until the final patch

**Comment by Zarant** [comment]
Patch 2.3.3 released January 22nd, 2008.
Patch 2.4 released March 25th, 2008.

The post I linked is from February 12th, after that you have testimonies from 2 different people confirming that same hunter's mark behavior.
Then you have a post from february 21st from the same person that created the forum post in the first place, saying that mind vision doesn't cancel drinking. The OP don't mention anything about hunter's mark, and he was the one that spend time testing it in the first place.

The evidence there is pretty solid, since you have multiple people confirming the same behavior. If you search the AJ hunter forums from the 2.4 era you won't find anyone crying about that alleged nerf.

**Comment by Zarant** [comment]
If you read carefully the whole link I posted you can see that in the same content patch, hunter's mark cancelled drinking and mind vision didn't.
I'll resume the whole conversation:
12 February 2008 - User Seriously create the topic I just quoted above, stating that Hunter's mark interrupt players from drinking.
15 February 2008 - User Stoneskin conducts his own tests corroborating what the OP just said, on top of that he points out that only the first application of hunter's mark have a line of sight check, refreshing the debuff interrupt players from drinking and can be done even out of line of sight.
16 February 2008 - User Sciurus points out that mind vision stop people from drinking
21 February 2008 - User Seriously (OP) then replies "Mindvision got fixed."

You can clearly see that in patch 2.3.3 mind vision did not interrupt players from drinking but Hunter's Mark did.

**Comment by Tenoutoften** [comment]
The comments suggests that for patch 2.3.3 Hunter's mark and Mind Vision would interrupt players drinking.
Comments also suggest that Mind Vision was fixed. The thread itself is just a few comments spanning less than 10 days. I don't see any reason to speculate in that OP would return to correct it if it got changed...

This is a pretty significant mechanic so it would be nice to have 2.4.3 video evidence rather than relying on this thread from 2.3.3

**Comment by Zarant** [comment]
Player A makes a claim - Hunter`s mark should interrupt players from drinking.
Player B conducts his own testing and confirms what A said.
Player C makes another different claim - Mind vision should have the same effect
Player A then tests Player C`s claim and report it back, turned out that Player C was wrong, this mind vision behavior was patched out of the game by patch 2.3.3.

You see a bunch of people describing how the game used to work back in the day, the only thing that is consistent here is the Hunter's Mark behavior.

Mind vision used to interrupt players from drinking, that wasn't the case in patch 2.3.3, since player A tested player C's claim. It's very unlikely that blizzard decided to hotfix that in the 9 day window the thread was created.

And I agree, that`s a pretty significant mechanic indeed but you`re trying to flip the proof of burden here based on your own conjectures, since there is no source pointing to the contrary.

**Comment by Tenoutoften** [comment]
I'd like to see video evidence of this from a 2.4.3 patch
We got some comments that it worked in patch 2.3.3.

I don't have any burden of proof, not making any claim

**Comment by Zarant** [comment]
You're making the claim that the described behavior was patched out of the game in 2.4, despite having no proof.

**Comment by Tenoutoften** [comment]
No I am not making that claim...
I am simply stating you don't have evidence from patch 2.4.3. Sorry for the misunderstandings you are having

>This is a pretty significant mechanic so it would be nice to have 2.4.3 video evidence rather than relying on this thread from 2.3.3

Does not equal to "This doesn't work in patch 2.4.3" Can you find any place where I stated this?

**Comment by Zarant** [comment]
This source is strong enough, since you have 2 independent player observations pointing to the same conclusion.

I'll try to dig for video evidence, but the usage of this mechanic is very situational, mostly useful on very long arena games and it's pretty unlikely that I'll find anything.

**Comment by killablink** [comment]
Hunter's mark doesn't interrupt drinking

**Comment by Tenoutoften** [comment]
Cherez was by many considered to be the best hunter during TBC and held a rating of 2402 in 2v2 with 109W - 5L

[Paladin/Warrior](https://youtu.be/VhCI3DDvGGU?t=69) - Hunter's Mark not used
[Druid/Warrior](https://youtu.be/VhCI3DDvGGU?t=234) - Hunter's Mark not used
[Priest/Rogue](https://youtu.be/VhCI3DDvGGU?t=418) - Hunter's Mark not used
[Druid/Rogue](https://youtu.be/VhCI3DDvGGU?t=592) - Hunter's Mark not used
[Priest/Warlock](https://youtu.be/VhCI3DDvGGU?t=692) - Hunter's Mark not used
[Druid/Warrior#2](https://youtu.be/VhCI3DDvGGU?t=891) - Hunter's Mark not used
[Mage/Warlock](https://youtu.be/VhCI3DDvGGU?t=1021) - Hunter's mark not used

Went through another [~20min video](https://www.youtube.com/watch?v=m_cVI65BHn0) and I can't see any Hunter's Mark either.

**Comment by Zarant** [comment]
Both videos you linked were from S3 (patch 2.3.x), so did the source I linked, which doesn't prove anything. Like I said, the usage of this trick is very situational, it's mostly useful in long drawn out arena games, it's only used when your pet is dead and no one would include their epic 15 minute fight against a warlock/druid team in their pvp video.

**Comment by The14me** [comment]
Since spell/talents suppose to work as 2.4.3 state, i don't see the issue here.

**Comment by Zarant** [comment]
Well, I guess this is a question of opinion at this point. I found very strong evidence that this mechanic was in the game in season 3, there is no strong sources anywhere saying that this mechanic got removed from the game later.

**Comment by tsuone** [comment]
https://web.archive.org/web/20081010220639/http://www.arenajunkies.com/strategy/2v2/Dru_Htr_2/

**Comment by Wolffenstein** [comment]
Fixed in rev 3545.
