### ISSUE TITLE
Can't take chain quest "The missing diplomat" after abandoning it due to a bug

### ISSUE THREAD

**Issue by ForgottenoneNW** [Atlantiss/NetherwingBugtracker#4922]
[//]: # (Enclose links to things related to the bug using http://wowhead.com or any other TBC database.)
[//]: # (You can use screenshot ingame to visual the issue.)
[//]: # (Write your tickets according to the format:)
[//]: # ([Quest][Azuremyst Isle] Red Snapper - Very Tasty!)
[//]: # ([NPC] Magistrix Erona)
[//]: # ([Spell][Mage] Fireball)
[//]: # ([Npc][Drop] Ghostclaw Lynx)
[//]: # ([Web] Armory doesnt work)
[//]: # (To find server revision type `.server info` command in the game chat.)

**Description**: 
Chain quest "The missing diplomat" given by Archmage Tervosh, where you are supposed to find private Hendel, was working perfectly fine. After a server restart for a fix Hendel was not hostile anymore and the quest couldn't be completed. Tried to abandon it and re take the quest but Archamage Tervosh doesn't give it anymore, nor any of the NPCs of the previous "The missing diplomat".

**Current behaviour**: Can't take quest after abandoning it

**Expected behaviour**: Should be able to take it

**Server Revision**:  2771

**Comment by Tereneckla** [comment]
The quest that makes Hendel hostile is given by Hendel. Fixed
