### ISSUE TITLE
Ancient Equine Spirit quest

### ISSUE THREAD

**Issue by LaDeude** [Atlantiss/NetherwingBugtracker#4923]
[//]: # (Enclose links to things related to the bug using http://wowhead.com or any other TBC database.)
[//]: # (You can use screenshot ingame to visual the issue.)
[//]: # (Write your tickets according to the format:)
[//]: # ([Quest][Azuremyst Isle] Red Snapper - Very Tasty!)
[//]: # ([NPC] Magistrix Erona)
[//]: # ([Spell][Mage] Fireball)
[//]: # ([Npc][Drop] Ghostclaw Lynx)
[//]: # ([Web] Armory doesnt work)
[//]: # (To find server revision type `.server info` command in the game chat.)

**Description**: Ancient Equine Spirit quest

**Current behaviour**:

Hello;

My arcanite barding for the paladin epic quest disappeared by the time I took the Ancient Equine Spirit quest.

Thinking of having it in my bag, I got the food for the horse.

Then direction west and west at the time of making the quest I noticed that I miss the Barding Arcanite.

To recover the Barding arcanite I abandoned the quest Ancient Equine Spirit and take it back.

Now I have the Barding Arcanite but I can not make the quest for food ...

**Expected behaviour**: if we quit the quest we must be able to redo the quest to have food

**Server Revision**: 2771

**Comment by LaDeude** [comment]
![image](https://user-images.githubusercontent.com/47465325/52512650-4aed4380-2c06-11e9-8baa-891a56a5049c.png)

**Comment by LaDeude** [comment]
I have just tried again, abandoning the quest and resuming it.

Impossible to have the quest

**Comment by pelekon** [comment]
Nothing bugged here, when you reward Collection of Goods it opens 2 quests: Grimand's Finest Work and Ancient Equine Spirit, both of those quest operate on same quest item, so when you take Ancient Equine Spirit and then reward Grimand's Finest Work then Arcanite Barding gets consumed as item required to complete quest, so you have to retake Ancient Equine Spirit to get item again(as it is provided by it). Looking at various sites it's blizzlike as it is.
