### ISSUE TITLE
[Gameobject] [Item] Upper Blackrock Spire door

### ISSUE THREAD

**Issue by regent3** [Atlantiss/NetherwingBugtracker#4926]
Seal of Ascension https://classicdb.ch/?item=12344

**Description**: 
Seal of Ascension dont open door in dungeon Blackrock Spire

**Server Revision**: 
2771

**Comment by Evolvee** [comment]
ubrs is closed

**Comment by YhwachPogchampiomn** [comment]
Let us in you imbecile
