### ISSUE TITLE
[Bug] 3v3 Arena team dissapeared

### ISSUE THREAD

**Issue by Klvn123** [Atlantiss/NetherwingBugtracker#4927]
**Description**:  3v3 arena team flat out dissapeared out of nowhere, 120g gone. 
Arena team name: Washed up

**Server Revision**: 2771

**Comment by Wolffenstein** [comment]
It's still there, it's a visual issue on the current battlegrounds branch, will be fixed soon

**Comment by Wolffenstein** [comment]
Will be resolved after next server update.
