### ISSUE TITLE
Sizable Amount of Money in the Guild Bank went poof

### ISSUE THREAD

**Issue by Metuskaln** [Atlantiss/NetherwingBugtracker#4928]
[//]: # (Enclose links to things related to the bug using http://wowhead.com or any other TBC database.)
[//]: # (You can use screenshot ingame to visual the issue.)
[//]: # (Write your tickets according to the format:)
[//]: # ([Quest][Azuremyst Isle] Red Snapper - Very Tasty!)
[//]: # ([NPC] Magistrix Erona)
[//]: # ([Spell][Mage] Fireball)
[//]: # ([Npc][Drop] Ghostclaw Lynx)
[//]: # ([Web] Armory doesnt work)
[//]: # (To find server revision type `.server info` command in the game chat.)

**Description**: 
I had a guy join my guild about a month back. His name was Lactocracy. The name of my guild is <the empire> Anyway, he was an excellent guild member and we got along great, but he got tired of grinding out levels so he told me that he was going to quit the game. Despite my protest, he was serious about it and I couldn't convince him to stick around. He deposited 500 gold into the guild bank on Feb 7 as a gift for making his time in the guild enjoyable.
**Current behaviour**:
On Feb 8, the money in the guild bank went poof. Its as if the guild bank was rolled back and reset.
**Expected behaviour**: 
It doesn't even register in the money log.
**Server Revision**:

**Comment by Metuskaln** [comment]
The name of my guild is the empire.

**Comment by Tenoutoften** [comment]
Sad to hear that, unfortunately the policy of the leadership is to never refund resources lost in this way. This is also a well known issue reported several times so it can be safely closed as duplicate.

**Comment by Wolffenstein** [comment]
Duplicate.
