### ISSUE TITLE
[Interface] duplicate senders on mail icon

### ISSUE THREAD

**Issue by d3aths** [Atlantiss/NetherwingBugtracker#493]
**Description**:  when hovering over the mail icon, sender appears more than once

**Current behaviour**:  horde auction house mail appearing twice

**Expected behaviour**:  should just come up once no matter how many messages you have from them

**Server Revision**:  2050

![wowscrnshot_092518_180517](https://user-images.githubusercontent.com/16113944/46001132-e5346b00-c0ed-11e8-825c-7b9a8df1f69e.jpg)

**Comment by Tereneckla** [comment]
Fixed
