### ISSUE TITLE
WSG battleground resurrection

### ISSUE THREAD

**Issue by Enzopoz** [Atlantiss/NetherwingBugtracker#4932]
You can resurrect at any point in the map (Im not sure if this applys to any other BG), you don't need to stand in the graveyard near the Spirit Healer, canceling ress also doesn't work since you get resurrected anyways

EDIT: Tested it in Arathi Basin as well, bugged there too

**Comment by Enzopoz** [comment]
Just tested it in AB, same bug

**Comment by killablink** [comment]
I also believe that when you lose the point (a point gets contested) you don't get teleported to another GY right now

**Comment by killablink** [comment]
Also, I know this isn't exactly the issue for it but, currently special powerups aren't respawning (or respawning too slowly) The speed boots in tunnel in WSG hasn't ever respawned for me

**Comment by Wolffenstein** [comment]
Fixed in rev 2787.
