### ISSUE TITLE
[Quest][Western Plaguelands] Mission Accomplished!

### ISSUE THREAD

**Issue by SimsenFriborg** [Atlantiss/NetherwingBugtracker#4933]
[//]: # (Enclose links to things related to the bug using http://wowhead.com or any other TBC database.)
[//]: # (You can use screenshot ingame to visual the issue.)
[//]: # (Write your tickets according to the format:)
[//]: # ([Quest][Azuremyst Isle] Red Snapper - Very Tasty!)
[//]: # ([NPC] Magistrix Erona)
[//]: # ([Spell][Mage] Fireball)
[//]: # ([Npc][Drop] Ghostclaw Lynx)
[//]: # ([Web] Armory doesnt work)
[//]: # (To find server revision type `.server info` command in the game chat.)

**Description**: 
The quest gives 1000 reputation with alliance, which also is shown in the chat, but the reputaition does not count - it does not actually give you reputation

**Current behaviour**:
Does not give reputation
**Expected behaviour**: 
Should give reputation

**Server Revision**:

**Comment by Manaci** [comment]
Answered this in another similar issue [here](https://github.com/Atlantiss/NetherwingBugtracker/issues/4232#issuecomment-461149576).
