### ISSUE TITLE
Blood Furnance Technician bombs trigger twice.

### ISSUE THREAD

**Issue by Mikik3jr** [Atlantiss/NetherwingBugtracker#4934]
[//]: # (Enclose links to things related to the bug using http://wowhead.com or any other TBC database.)
[//]: # (You can use screenshot ingame to visual the issue.)
[//]: # (Write your tickets according to the format:)
[//]: # ([Quest][Azuremyst Isle] Red Snapper - Very Tasty!)
[//]: # ([NPC] Magistrix Erona)
[//]: # ([Spell][Mage] Fireball)
[//]: # ([Npc][Drop] Ghostclaw Lynx)
[//]: # ([Web] Armory doesnt work)
[//]: # (To find server revision type `.server info` command in the game chat.)

**Description**: 
In Blood Furnance [Technicians](https://www.wowhead.com/npc=17414/shadowmoon-technician) put down mines.

**Current behaviour**:
When we step on them almost like 80% of the time it triggers twice.

**Expected behaviour**: 
It should trigger once.

**Server Revision**: 
2771

**Comment by DragunovUA** [comment]
that's why im dying in BF lol

**Comment by Azalen** [comment]
#2076

**Comment by DragunovUA** [comment]
opened this Issue on 1 Nov 2018 

fun server

**Comment by Evolvee** [comment]
duplicate
