### ISSUE TITLE
[Hunter] [Skill] Feign Death does not break drain life.

### ISSUE THREAD

**Issue by gunzbngbng** [Atlantiss/NetherwingBugtracker#4935]
[//]: # (Enclose links to things related to the bug using http://wowhead.com or any other TBC database.)
[//]: # (You can use screenshot ingame to visual the issue.)
[//]: # (Write your tickets according to the format:)
[//]: # ([Quest][Azuremyst Isle] Red Snapper - Very Tasty!)
[//]: # ([NPC] Magistrix Erona)
[//]: # ([Spell][Mage] Fireball)
[//]: # ([Npc][Drop] Ghostclaw Lynx)
[//]: # ([Web] Armory doesnt work)
[//]: # (To find server revision type `.server info` command in the game chat.)

**Description**: Feign Death is intended to break casts, channels, and targeting.

**Current behaviour**: Feign Death does not break Drain Life.

**Expected behaviour**: Drain Life should end when Feign Death is used.

https://youtu.be/FAz6E6W4T-I?t=778

**Server Revision**: 2771

**Comment by Wolffenstein** [comment]
Fixed in rev 2775.
