### ISSUE TITLE
Underlight Mines missing patrols

### ISSUE THREAD

**Issue by Tenoutoften** [Atlantiss/NetherwingBugtracker#494]
**Description & Current behaviour**:
In the cave there is a Blackpaw Shaman#16337 standing rather still that should be patrolling the cave as seen in https://youtu.be/ljEYjuP27No?t=114

There is also another  Blackpaw Shaman that is suppose to wander the camps patrolling missing.
https://youtu.be/Z1Pq4QhdW4M?t=104

**Expected behaviour**: 
I expect a Blackpaw Shaman#16337 to be patroling the cave. I also expect a few other patrols in the camps outside

**Server Revision**: 
2050

**Comment by aresbrutus** [comment]
Will be fixed in one of the upcoming updates.
