### ISSUE TITLE
[NPC] Moroes should not be Bleed immune

### ISSUE THREAD

**Issue by Mikik3jr** [Atlantiss/NetherwingBugtracker#4941]
[//]: # (Enclose links to things related to the bug using http://wowhead.com or any other TBC database.)
[//]: # (You can use screenshot ingame to visual the issue.)
[//]: # (Write your tickets according to the format:)
[//]: # ([Quest][Azuremyst Isle] Red Snapper - Very Tasty!)
[//]: # ([NPC] Magistrix Erona)
[//]: # ([Spell][Mage] Fireball)
[//]: # ([Npc][Drop] Ghostclaw Lynx)
[//]: # ([Web] Armory doesnt work)
[//]: # (To find server revision type `.server info` command in the game chat.)

**Description**: 
An example of bleed:
![image](https://user-images.githubusercontent.com/43505031/52532575-e2968300-2d27-11e9-8aa8-1e23361a6c89.png)

**Current behaviour**:
Moroes is immune to this bleed type of ability.

**Expected behaviour**: 
As you can see on this [video](https://www.youtube.com/watch?v=8UUmvbKJGxw) (from 2007 february) you should be able to apply the bleed.
![image](https://user-images.githubusercontent.com/43505031/52532584-fa6e0700-2d27-11e9-8cce-1cc9a3ccc55e.png)

This is a huge deal for druid tanks, since this spell is like sunder armor for warriors, it generates a tons of threat.

I checked patch notes before this video was made and I couldn't find anything that Moroes lost it's bleed immunity between the prenerf state and the upload date of the video (which may be was uploaded days later after it was recorded)

EDIT 2:
[Additional video](https://www.youtube.com/watch?v=2DRqj1JFPpc&feature=youtu.be&t=260) and it is from 2007.01.26 according to the [web.archive](https://web.archive.org/web/20070209141744/http://www.lrguild.org/forum/viewforum.php?id=48)
In this video it can be seen that Moroes is not even bleed immune at all (Rogue garrote and the combopoint bleed spell both works on Moroes)
**Server Revision**: 
2776

**Comment by Neophrone** [comment]
Not so important for DPS classes, but if your group has a feral tank u'll wipe thousand times because feral can't manage he's threat without it. 
Up.

**Comment by DragunovUA** [comment]
just fix it wolf

**Comment by FuzzNFA** [comment]
Issue reported during beta testing.
Talked about with testers/game masters in discord.
Got dismissed even after posting video of it.

Let's see how much proof is needed to get something as simple as this fixed.

**Comment by Wolffenstein** [comment]
Fixed in rev 2777.
