### ISSUE TITLE
[spell] [warrior] Demoralizing Shout 

### ISSUE THREAD

**Issue by femdead** [Atlantiss/NetherwingBugtracker#4942]
It currently does 0 threat. It should do 56 per target hit (before modifiers)
source: https://www.ownedcore.com/forums/world-of-warcraft/world-of-warcraft-guides/137123-guide-what-you-need-know-protection-warriors.html
plenty of research on base threat on warrior abilities ie. kenco's research in vanilla, numbers were well known

**Comment by Tenoutoften** [comment]
Same with battle shout

**Comment by Tereneckla** [comment]
Fixed rev 2777
