### ISSUE TITLE
[Spell][Mage]Arcane Missiles - distance breaks channeling

### ISSUE THREAD

**Issue by H2714** [Atlantiss/NetherwingBugtracker#4943]
[//]: # (Enclose links to things related to the bug using http://wowhead.com or any other TBC database.)
[//]: # (You can use screenshot ingame to visual the issue.)
[//]: # (Write your tickets according to the format:)
[//]: # ([Quest][Azuremyst Isle] Red Snapper - Very Tasty!)
[//]: # ([NPC] Magistrix Erona)
[//]: # ([Spell][Mage] Fireball)
[//]: # ([Npc][Drop] Ghostclaw Lynx)
[//]: # ([Web] Armory doesnt work)
[//]: # (To find server revision type `.server info` command in the game chat.)

**Description**: 
Arcane Missiles channeling breaks too easily. 
I tested another channeled spell (Darin Life) and it works just fine.

**Current behaviour**:
If the target moves just slightly out of range the spell will be interrupted (even before the first missile is out!) resulting in wasted mana but no GCD.

**Expected behaviour**: 
There should be some flexibility distance wise.
 
**Server Revision**: 
2776

**Comment by killablink** [comment]
That's because spell leeway isn't completely implemented. But yes there should be some leeway with channeling spells when the target gets out of range like this 
https://youtu.be/kk2yfdLOISI?t=35

**Comment by knasen88** [comment]
#121  thats get's fixed and then is broken every other patch is what needs fixing

**Comment by Easyfraggy** [comment]
Leeway is working fine and my channels don't break untill player is well over 50 yards away.

Leeway for spells is implemented and works perfectly fine - it might just be slightly too short of a leeway - seems to be only a few yards 2-3.

**Comment by knasen88** [comment]
it's like it's hardcoded for each individual spell since every other spell seem to be broken

**Comment by BidingMyTime** [comment]
AM is still broken with _0_ leeway on channel distance above 30yds.
While 50yds is WAY too big (sounds like warlock drains ned fixing the other way around, lol), it should have something similar to the leeway other mage spells have before their cast gets cancelled (when cast was initiated at max range with the target moving away).

**Comment by The14me** [comment]
Rev. 3460 still an issue.

**Comment by Godmatik** [comment]
Duplicate, closing this one
