### ISSUE TITLE
Underbog Heroic

### ISSUE THREAD

**Issue by FIXTHISFASTERRR** [Atlantiss/NetherwingBugtracker#4944]
[//]: # (Enclose links to things related to the bug using http://wowhead.com or any other TBC database.)
[//]: # (You can use screenshot ingame to visual the issue.)
[//]: # (Write your tickets according to the format:)
[//]: # ([Quest][Azuremyst Isle] Red Snapper - Very Tasty!)
[//]: # ([NPC] Magistrix Erona)
[//]: # ([Spell][Mage] Fireball)
[//]: # ([Npc][Drop] Ghostclaw Lynx)
[//]: # ([Web] Armory doesnt work)
[//]: # (To find server revision type `.server info` command in the game chat.)

**Description**: 
Been running underbog HC early server time every day, and getting the same 3 items always dropping between eachother 2 blue items never any epic, and before some update there used to be epic drops frequently, nice fkin stealth nerf after everyone got epics, now i run it 10 after update 0 epics, did fkin 40 runs of UB hc never seen epic legs
**Current behaviour**:

**Expected behaviour**: 

**Server Revision**:

**Comment by DragunovUA** [comment]
cute server

**Comment by Evolvee** [comment]
noone touched loot tables of underbog
