### ISSUE TITLE
Auction house not sorting listings correctly

### ISSUE THREAD

**Issue by kingusjordanus** [Atlantiss/NetherwingBugtracker#4946]
[//]: # (Enclose links to things related to the bug using http://wowhead.com or any other TBC database.)
[//]: # (You can use screenshot ingame to visual the issue.)
[//]: # (Write your tickets according to the format:)
[//]: # ([Quest][Azuremyst Isle] Red Snapper - Very Tasty!)
[//]: # ([NPC] Magistrix Erona)
[//]: # ([Spell][Mage] Fireball)
[//]: # ([Npc][Drop] Ghostclaw Lynx)
[//]: # ([Web] Armory doesnt work)
[//]: # (To find server revision type `.server info` command in the game chat.)

**Description**:The auction house is not sorting auctions correctly.

**Current behaviour**:
Auctions are normally sorted ascending by price by default.  It is somewhat working correctly, but it seems as if there are 2-3 separate collections of each item.  Page 1 is ascending as it should be, but then page 2 is doing the same thing, but with different listings at similar price points.  The best way I can describe it is that each page of an item listed is treated as its own auction house.  So for copper ore, there are 3 pages, and each page starts at around 3 silver and goes up to around a couple of gold depending on quantity, but when you go to the next page, instead of starting off where page 1 ended, it starts over at couple of silver again.  

I have tried using different categories to sort the auctions and logging out and back in and the problem persists no matter what I try.  I have been able to duplicate the issue with any item that has more than one page of listings on the auction house.  These listings are not being grouped together in any obvious way.  Each page has different "time remaining" values, buyout prices, and quantities as is commonly found when it is working correctly.

![page1](https://user-images.githubusercontent.com/47504589/52537894-6e60dd00-2d31-11e9-8cbb-90590dcb4029.JPG)
![page2](https://user-images.githubusercontent.com/47504589/52537895-6e60dd00-2d31-11e9-9250-3f59c15da3b3.JPG)
![page3](https://user-images.githubusercontent.com/47504589/52537896-6e60dd00-2d31-11e9-9b4b-28cdd8da0ff6.JPG)

**Expected behaviour**:  Auction house listings are sorted price ascending by default from page 1 till the last listing.  Listings can be sorted using the toolbars at the top of the "Browse Auctions" window.

**Server Revision**: unknown server revision, Bug reported 12:35pm CST USA, Feb. 10th, 2019.

**Comment by Balanarr** [comment]
As far as I can remember that is how the AH searching worked in BC.
It was changed in later expansions as everyone was using AH addons anyway.

**Comment by Heyyjulian** [comment]
No, Balanarr, this is not correct.  You could literally go to any other private server (Northdale, etc.) and list one item on their AH (try undercutting something from the first page) to see that the way the Netherwing's AH lists its items is incorrect, its almost arbitrary.  There should be one sequential list across all pages per item.  Not a fresh list sorted low to high on each page.  This is broken and rather game breaking to be honest as it makes it effectively impossible to undercut another listing properly.  It also makes it extremely difficult to maintain control of a section of the market (I.e: bags, Primals, etc.)

**Comment by The14me** [comment]
Suppose to be fixed with the latest AH rework.
