### ISSUE TITLE
[Quest] Tabards of the Illidari

### ISSUE THREAD

**Issue by rychersky** [Atlantiss/NetherwingBugtracker#4947]
[//]: # (Enclose links to things related to the bug using http://wowhead.com or any other TBC database.)
[//]: # (You can use screenshot ingame to visual the issue.)
[//]: # (Write your tickets according to the format:)
[//]: # ([Quest][Azuremyst Isle] Red Snapper - Very Tasty!)
[//]: # ([NPC] Magistrix Erona)
[//]: # ([Spell][Mage] Fireball)
[//]: # ([Npc][Drop] Ghostclaw Lynx)
[//]: # ([Web] Armory doesnt work)
[//]: # (To find server revision type `.server info` command in the game chat.)

**Description**: The Illidari Tabard quest items should be a 100% drop rate.

https://www.wowhead.com/quest=10768/tabards-of-the-illidari#comments

They currently are not.

**Server Revision**: 2776

**Comment by Manaci** [comment]
I think they do now
