### ISSUE TITLE
[Raid][SSC][Lady Vashj] Incorrect Tainted Elemental Spawn Timers.

### ISSUE THREAD

**Issue by Imbaslap** [Atlantiss/NetherwingBugtracker#4948]
[//]: # (Enclose links to things related to the bug using http://wowhead.com or any other TBC database.)
[//]: # (You can use screenshot ingame to visual the issue.)
[//]: # (Write your tickets according to the format:)
[//]: # ([Quest][Azuremyst Isle] Red Snapper - Very Tasty!)
[//]: # ([NPC] Magistrix Erona)
[//]: # ([Spell][Mage] Fireball)
[//]: # ([Npc][Drop] Ghostclaw Lynx)
[//]: # ([Web] Armory doesnt work)
[//]: # (To find server revision type `.server info` command in the game chat.)

**Description**: 
Currently on Netherwing, the Tainted Elementals spawn at very random and erratic times.
**Current behaviour**:
during the encounter of Lady Vashj, guilds would be experiencing tainted elementals spawning between 50-90seconds each time at very random occurances, causing a very elongated phase 2 that isn't intended.
**Expected behaviour**: 
Tainted Elementals should spawn at 55 second intervals. first tainted spawns 55s after vashj enters phase 2, and the following tainted elementals spawn 55s after the previous tainted dies by a player or despawns.

looking through the old DBM and Bigwigs LUA files of patch 2.0.12 they have the following:
**DBM:**
`elseif event == "CHAT_MSG_MONSTER_YELL" and arg1 then
		if string.find(arg1, DBM_VASHJ_YELL_PHASE2) then
			phase = 2;
			self:Announce(DBM_VASHJ_WARN_PHASE2, 1);
			self:StartStatusBarTimer(62, "Strider", "Interface\\Icons\\INV_Misc_Fish_13");
			self:StartStatusBarTimer(52, "Tainted Elemental", "Interface\\Icons\\Spell_Nature_ElementalShields");`
and for **Bigwigs:**
`local elemDies = UNITDIESOTHER:format(L["Tainted Elemental"])
function mod:CHAT_MSG_COMBAT_HOSTILE_DEATH(msg)
    if msg == elemDies then
        if self.db.profile.elemental then
            self:Bar(L["elemental_bar"], 60, "Spell_Nature_ElementalShields")
            delayedElementalMessage = self:DelayedMessage(55, L["elemental_soon_message"], "Important")
        end
    else`

the Bigwigs version matches the version used in the Method world 2nd kill video:
https://youtu.be/AuWJ9z62RT8?t=244 you can see the bigwigs timer count from 60s down. it also has the first tainted spawn with 5s remaining on the timer.
the timer then begins to restart once the tainted is killed. 
https://youtu.be/AuWJ9z62RT8?t=365 timer around 2-4s left on tainted and u see a poison bolt lobbing across the center stage, since it takes a few seconds to cast a poison bolt, it matches up with the timer for bigwigs from the first tainted spawn.

in DBM it has this string for when to start the next tainted elemental timer:
`elseif msg == "ElementDies" then
		self:StartStatusBarTimer(55, "Tainted Elemental", "Interface\\Icons\\Spell_Nature_ElementalShields");
		self:ScheduleSelf(53, "Spawn", "Elemental");
		self:ScheduleMethod(50, "SendSync", "ElementDies");
		self:ScheduleSelf(45, "SpawnSoonWarn", "Elemental");`

**Server Revision**: 
Sources: https://wow.curseforge.com/projects/big-wigs/files/119669 - Patch 2.0.12 bigwigs used.
https://www.youtube.com/watch?v=AuWJ9z62RT8 Method world 2nd kill video.

**Comment by Easyfraggy** [comment]
While the timer is definitely not what bigwigs has listed as seen clearly on the video - first elemental spawns 5 seconds before the timer and later they spawn between 50-60 seconds interval every time - 50-90 does seem like too much of an interval.

**Comment by Wolffenstein** [comment]
Fixed in rev 2785.
