### ISSUE TITLE
Darkened Spirits not attacking anything if first pulled by a Searing Totem

### ISSUE THREAD

**Issue by staplerx300** [Atlantiss/NetherwingBugtracker#4949]
[//]: # (Enclose links to things related to the bug using http://wowhead.com or any other TBC database.)
[//]: # (You can use screenshot ingame to visual the issue.)
[//]: # (Write your tickets according to the format:)
[//]: # ([Quest][Azuremyst Isle] Red Snapper - Very Tasty!)
[//]: # ([NPC] Magistrix Erona)
[//]: # ([Spell][Mage] Fireball)
[//]: # ([Npc][Drop] Ghostclaw Lynx)
[//]: # ([Web] Armory doesnt work)
[//]: # (To find server revision type `.server info` command in the game chat.)

**Description**: 
https://tbc-twinhead.twinstar.cz/?quest=10168

If you aggro these mobs in Nagrand after using the mirror item on them to make them a red mob, using a Searing Totem to get the first hit,  the mob will first attack the totem and then just sit there and not attack anything making the quest a joke to complete. You can kill it without taking any damage. 

**Current behaviour**:
If aggroed by a totem instead of a player, once it kills the totem the mob ceases to attack anything. 

**Expected behaviour**: 
It should attack you once it kills the totem like normal. 

**Server Revision**:

**Comment by staplerx300** [comment]
Also one more thing, if after attacking the mob while it's immobile not doing anything, you target a different mob then it starts attacking people normally. 

Very strange behavior.

**Comment by The14me** [comment]
Work fine for me.Rev 3441
