### ISSUE TITLE
[NPC] Blackheart Hellcaller 3771

### ISSUE THREAD

**Issue by Bleachlol** [Atlantiss/NetherwingBugtracker#495]
**Description**: 
Voidwalker minion doesn't depsawn when Blackheart Hellcaller is killed, goes back to the position when kited away. When a new Blackheart Hellcaller spawns, a new voidwalker minion spawns. https://imgur.com/a/gBh97FU When I pulled both minions and the Hellcaller, then one of the voidwalkers minions never reset. https://imgur.com/a/zSRl9ve 

Blackheart Hellcaller: 3771
Voidminion: 8996
Imp: 12922

**Current behaviour**:
Pet follows you, if hellcaller dies, it will reset and go back to position, won't despawn untill killed. 
**Expected behaviour**: 
Voidwalker or imp should despawn after x amount of minutes or despawn when its master is killed. 
**Server Revision**: 
2050

**Comment by Kiperr** [comment]
```sql 
SET @ENTRY := 3771;
INSERT INTO smart_scripts (entry, script_source_type, id, link, event_type, event_phase_mask, event_chance, event_flags, event_param1, event_param2, event_param3, event_param4, event_param5, event_param6, event_param7, event_param8, event_cooldown_min, event_cooldown_max, action_type, action_param1, action_param2, action_param3, action_param4, action_param5, action_param6, action_param7, action_param8, source_type, source_param1, source_param2, source_param3, source_condition_id, target_type, target_param1, target_param2, target_param3, target_condition_id, target_x, target_y, target_z, target_o, comment) VALUES
(@ENTRY, 0, 3, 0, 6, 0, 100, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 41, 1000, 0, 0, 0, 0, 0, 0, 0, 36, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, "On death - All summons: Despawn in 1 seconds // ");
```

**Comment by Evolvee** [comment]
^^ thats ugly af hackfix, wolf should look at this from core-side since similar spells cant be used all over the world

**Comment by Evolvee** [comment]
its actually caused by the spell not being in wolfAI anyway

**Comment by Evolvee** [comment]
rev Xd
