### ISSUE TITLE
[NPC] Shade of Aran Flame Wreath can be interrupted

### ISSUE THREAD

**Issue by Mikik3jr** [Atlantiss/NetherwingBugtracker#4950]
[//]: # (Enclose links to things related to the bug using http://wowhead.com or any other TBC database.)
[//]: # (You can use screenshot ingame to visual the issue.)
[//]: # (Write your tickets according to the format:)
[//]: # ([Quest][Azuremyst Isle] Red Snapper - Very Tasty!)
[//]: # ([NPC] Magistrix Erona)
[//]: # ([Spell][Mage] Fireball)
[//]: # ([Npc][Drop] Ghostclaw Lynx)
[//]: # ([Web] Armory doesnt work)
[//]: # (To find server revision type `.server info` command in the game chat.)

**Description**: 
Title

**Current behaviour**:
If you use warrior charge (from berserker stance forgot the name lol) you can interrupt the flame wreath

**Expected behaviour**: 
Should not be interruptable

**Server Revision**: 
2776

**Comment by Wolffenstein** [comment]
Fixed in rev 2782.
