### ISSUE TITLE
[Quest] Thwart the Dark Conclave

### ISSUE THREAD

**Issue by rychersky** [Atlantiss/NetherwingBugtracker#4951]
[//]: # (Enclose links to things related to the bug using http://wowhead.com or any other TBC database.)
[//]: # (You can use screenshot ingame to visual the issue.)
[//]: # (Write your tickets according to the format:)
[//]: # ([Quest][Azuremyst Isle] Red Snapper - Very Tasty!)
[//]: # ([NPC] Magistrix Erona)
[//]: # ([Spell][Mage] Fireball)
[//]: # ([Npc][Drop] Ghostclaw Lynx)
[//]: # ([Web] Armory doesnt work)
[//]: # (To find server revision type `.server info` command in the game chat.)

**Description**: The respawn time on the 4 guards and the C'thuun looking mob in the water seems way, way too long (or indefinite). I've been waiting for about 25 minutes now and haven't seen any of it respawn.

![wowscrnshot_021019_145502](https://user-images.githubusercontent.com/45608488/52540221-6bbbb300-2d44-11e9-9df3-db249cf9ca68.jpg)

**Server Revision**: 2776

**Comment by teddys** [comment]
confirming

**Comment by Bemrok** [comment]
Quest seem to only work once after server restart - server just crashed - one person could do it - now you just get the message "requires unguarded summoning site" when using the staff.
Mobs are respawning pretty quickly so that seems to be fixed.
![wowscrnshot_021119_195458](https://user-images.githubusercontent.com/47538033/52586353-976b9580-2e37-11e9-93e6-c9abc66629d3.jpg)

**Comment by Suzaru** [comment]
Yep, thats still the case. Can't complete it.

**Comment by Jalapan** [comment]
@Wolffenstein

**Comment by wtRCH** [comment]
@Suzaru @rychersky @Jalapan @Bemrok @teddys Still happening?

**Comment by rychersky** [comment]
![image](https://user-images.githubusercontent.com/45608488/59119299-aeb31f00-890f-11e9-9f7a-7308963717c0.png)

![image](https://user-images.githubusercontent.com/45608488/59119352-d73b1900-890f-11e9-8c45-1b273ab1dc2a.png)

Everything respawned 5-10 minutes later:

![image](https://user-images.githubusercontent.com/45608488/59119683-9ee80a80-8910-11e9-9351-6e56cbca6fb6.png)

So, I'd say everything is working 100% now for this quest.

**Comment by leeviathan** [comment]
Doesn't work for me. Killed all the mobs around the area but it just gives the "requires unguarded summoning area" message.

**Comment by The14me** [comment]
It worked fine for me, but since its rare to reproduce, please re-open if happen again.
Rev.3460

**Comment by knasen88** [comment]
not spawning as of today 6/8

**Comment by knasen88** [comment]
seems to be working now?

**Comment by Godmatik** [comment]
Can't reproduce, seems to have been fixed.
