### ISSUE TITLE
[core] Cloak of Shadows immune effect

### ISSUE THREAD

**Issue by Dusky1** [Atlantiss/NetherwingBugtracker#4952]
The mechanic shown in the following video is no longer working on Netherwing.

https://www.youtube.com/watch?v=5XBimiJ1BM0&t=57
**Server Revision**: 2776

**Comment by Wolffenstein** [comment]
Can you record the test for me?

**Comment by Dusky1** [comment]
right now cannot reproduce it, maybe it was ping related but I end up a few times today in fear/coil/hoj with CoS on me

**Comment by Evolvee** [comment]
well its still only 90%

**Comment by Dusky1** [comment]
I feel like it happens alot. Btw i tought the effect if different from Cloak of Shadows, since it allways shows IMMUNE, not resist?
![wowscrnshot_021119_111821](https://user-images.githubusercontent.com/17127512/52559231-0ffd3280-2df5-11e9-93e2-c2dd9cd416c7.jpg)

**Comment by Evolvee** [comment]
spell delay is complete shit rn so, i dont think it works anyway

**Comment by The14me** [comment]
Rev.3483 still an issue.
