### ISSUE TITLE
regeneration, sprint and berserk not respawning in bg

### ISSUE THREAD

**Issue by tehelelol** [Atlantiss/NetherwingBugtracker#4953]
[//]: # (Enclose links to things related to the bug using http://wowhead.com or any other TBC database.)
[//]: # (You can use screenshot ingame to visual the issue.)
[//]: # (Write your tickets according to the format:)
[//]: # ([Quest][Azuremyst Isle] Red Snapper - Very Tasty!)
[//]: # ([NPC] Magistrix Erona)
[//]: # ([Spell][Mage] Fireball)
[//]: # ([Npc][Drop] Ghostclaw Lynx)
[//]: # ([Web] Armory doesnt work)
[//]: # (To find server revision type `.server info` command in the game chat.)

**Description**: 
regeneration, sprint and berserk not respawning in bg
**Current behaviour**:
regeneration, sprint and berserk not respawning in bg, only available once bg starts
**Expected behaviour**: 
should respawn on a timer
**Server Revision**:

**Comment by Wolffenstein** [comment]
Fixed in rev 2787.
