### ISSUE TITLE
spell resistance broken / overtuned in PvP

### ISSUE THREAD

**Issue by tehelelol** [Atlantiss/NetherwingBugtracker#4954]
[//]: # (Enclose links to things related to the bug using http://wowhead.com or any other TBC database.)
[//]: # (You can use screenshot ingame to visual the issue.)
[//]: # (Write your tickets according to the format:)
[//]: # ([Quest][Azuremyst Isle] Red Snapper - Very Tasty!)
[//]: # ([NPC] Magistrix Erona)
[//]: # ([Spell][Mage] Fireball)
[//]: # ([Npc][Drop] Ghostclaw Lynx)
[//]: # ([Web] Armory doesnt work)
[//]: # (To find server revision type `.server info` command in the game chat.)

**Description**: 
spell resistance broken / overtuned in PvP
**Current behaviour**:
even with 5,2% hit (way over pvp hit cap) and 30 spell penetration I am getting a lot of resist on even unbuffed players. Not even talking motw (which my spell pen negates or shadow prot..)+
Regular spells feel like 1/4 resist sometimes, tons of deathcoil resists.
Spell Lock (wl counter) getting resisted like 80% of the time.
It just feels that the chance to resist is way to high even with spell penetration.
I tested this by using 0 penetration to 30 (motw is 25) and it didn't make any difference.
Spell penetration or resistance is bugged.
**Expected behaviour**: 
sadly I can't "prove" that it is wrong, or what kind of evidence you need?
**Server Revision**:

**Comment by Evolvee** [comment]
spell lock is resisted because pet doesnt inherit hit rating from player, pets hit is 0

u dont count resist talents probably

spell penetration does nothing towards flat resists from talents etc.

**Comment by Evolvee** [comment]
![image](https://user-images.githubusercontent.com/1942409/52542791-b02a6b80-2da3-11e9-9bce-4cce42c611fa.png)
we need to show us how its bugged.. numbers etc.

"it resists a lot" is not evidence
