### ISSUE TITLE
[Spell][Paladin] Consecration - Interrupts Enemy Channeled Spells

### ISSUE THREAD

**Issue by Ceago** [Atlantiss/NetherwingBugtracker#4955]
**Description**:  Paladin consecration interrupts enemies channeled spells.  Works on every mob I've tried it on so far.

**Current behaviour**: Interrupts enemy spell cast.  Please see attached video. https://streamable.com/6fekh

**Expected behaviour**:  Should not interrupt.

**Server Revision**: 2776

**Comment by Tenoutoften** [comment]
Consecration also has additional issues:
Fluctuating spell damage: https://github.com/Atlantiss/NetherwingBugtracker/issues/3402
Doesn't agro mobs: https://github.com/Atlantiss/NetherwingBugtracker/issues/1757

The second bug triggers additional combat bugs: https://github.com/Atlantiss/NetherwingBugtracker/issues/4784

**Comment by Wolffenstein** [comment]
Fixed in rev 2832.
