### ISSUE TITLE
Stranglethorn Fishing Extravaganza event fishpools are not respawning

### ISSUE THREAD

**Issue by Mikik3jr** [Atlantiss/NetherwingBugtracker#4956]
[//]: # (Enclose links to things related to the bug using http://wowhead.com or any other TBC database.)
[//]: # (You can use screenshot ingame to visual the issue.)
[//]: # (Write your tickets according to the format:)
[//]: # ([Quest][Azuremyst Isle] Red Snapper - Very Tasty!)
[//]: # ([NPC] Magistrix Erona)
[//]: # ([Spell][Mage] Fireball)
[//]: # ([Npc][Drop] Ghostclaw Lynx)
[//]: # ([Web] Armory doesnt work)
[//]: # (To find server revision type `.server info` command in the game chat.)

**Description**: 
Every week on Saturday between 1pm-5pm the Stranglethorn Fishing Extravaganza is happening. It means lot of pools spawn at the shores of STV and you have to fish like 40 Speckled Tastyfish and deliver those to an NPC in Booty Bay to win the event.

**Current behaviour**:
The pools don't spawn back at all. I started to fish on the top and I went down until the lv40 purple raptors. That is where I met with another player whom was fishing as well (they started from Booty Bay and were going up on the map), so I turned back and went back to the top again, butI havent found any pools spawning back. Actually I "found" them, but in a really interesting way:
- I mouseovered on the sea and I saw in the tooltip that there is a school of tastyfish there, but there was no that typical "schoolfishmodel" to show it. They were kinda invisible if I can say that
- I tried to fish on that area, but every time I caught something nothing happened. No error message, no failure that the fish got away, no loot table, nothing.
The screenshoot can't show where my cursor was, so I drew a red circle there. The tooltip says that I am mouseovering on the pool, but that can't be seen:
![image](https://user-images.githubusercontent.com/43505031/52542787-a7399a00-2da3-11e9-9b80-cdb2eed156a8.png)

As I see the issue is that it tries to respawn, but it can't, and it stays in that state.
**Expected behaviour**: 
I haven't researched it, but I think the pools should spawn back. I know that blizzard logic can be ducked, but if I think about the possibility that more players are racing to be the first to deliver the 40 fishes, but none of them can do it if ALL the pools are out, then I think it should not be like that.

**Server Revision**: 
2776

**Comment by Tereneckla** [comment]
closed, see #960
