### ISSUE TITLE
[Gruul's Lair][Spell] Gruul the Dragonkiller - Reverberation

### ISSUE THREAD

**Issue by Firroth** [Atlantiss/NetherwingBugtracker#4957]
[NPC] [Gruul the Dragonkiller](https://www.wowhead.com/npc=19044/gruul-the-dragonkiller)
[Spell] Reverberation (silence) [36297]

**Current behaviour**:
He uses it WAAAAAAAAAY to rare, in around 5-6min fight he used it once, or twice which nulls the difficulty of this boss to almost zero. Since tanks death occur mostly with good timed silence on raid.

**Expected behaviour**: 
He should be using Spell Reverberation [36297], every 45s up to 1min. As seen from this video of pre-nerf Gruul.
https://www.youtube.com/watch?v=J2MwoJffk00

**Server Revision**: 
2776

I have no idea why hasn't this been reported earlier. Going for easy kills? Since now Gruul is a joke.

**Comment by Wolffenstein** [comment]
I don't think it's that bad but I'll reduce it a bit in rev 2782.
