### ISSUE TITLE
Some 5-Man bosses have the incorrect level

### ISSUE THREAD

**Issue by fantom8** [Atlantiss/NetherwingBugtracker#4959]
**Description**: Bosses in Black Morass normal and possibly other instances are not the correct level.

**Current behaviour**:
Bosses such as Temporus are level 73 not level 72.

**Expected behaviour**: 
All 5 man bosses should be +2 over the level of their instance. BM is a level 70 instance. This is important not just for tanks but for all casters that aren't supposed to need 16% hit in 5 man instances.

https://wowwiki.fandom.com/wiki/Temporus
https://wowwiki.fandom.com/wiki/Chrono_Lord_Deja
https://wowwiki.fandom.com/wiki/Aeonus

Please check all instances besides BM as well, Shouldn't take long to look at boss NPC entries, and I saw at least one other open ticket about this issue for a different instance.

**Server Revision**: 2776

**Comment by Tenoutoften** [comment]
Was reported on beta too
https://github.com/Atlantiss/NetherwingBugtracker/issues/3203

**Comment by Zarant** [comment]
heroics probably need a thorough review at the moment, I did botanica heroic a couple days ago and some bosses were level 72 and some bosses were level 73

**Comment by Evolvee** [comment]
rev 2827
