### ISSUE TITLE
The Dead Scar missing Phantomsmal Watcher#16311 patrols

### ISSUE THREAD

**Issue by Tenoutoften** [Atlantiss/NetherwingBugtracker#496]
**Description**: 
Phantomsmal Watcher's#16311(https://db.excalibur.ws/?npc=16311) are currently standing still doing nothing. Should be patrolling according to https://i.gyazo.com/e1b7a109db1d9b00a3b6df9e4a068cfb.png (wowhead comment; https://www.wowhead.com/quest=9155/down-the-dead-scar) . The comment is from a significantly later patch 5.4.1 but is seems strange if this entire region is suppose to have zero patrolling. 

https://youtu.be/mNAVsP0sh14?t=100 showing a patrol of Phantomsmal Watcher#16311
https://youtu.be/mNAVsP0sh14?t=137 another one
https://youtu.be/pe9fvCC5KbQ?t=66 another one plus you can see the mob isn't at it's spawn position it would've been at if it wasn't patrolling.

**Current behaviour**:
Nothing is patrolling.

**Expected behaviour**: 
I expect mobs to be patrolling as indicated by wowhead comment & videos from retail.

**Server Revision**: 
2050

**Comment by aresbrutus** [comment]
Will be fixed in one of the upcoming updates.
