### ISSUE TITLE
[talent][rogue]cold blood getting removed on misses

### ISSUE THREAD

**Issue by RoldErrant** [Atlantiss/NetherwingBugtracker#4960]
**Description**: 
 Cold blood buff getting removed if special attack or finisher missed/dodged/parried.
Should stay active until attack lands.

**Resource**:
https://wowwiki.fandom.com/wiki/Patch_2.3.0

"Cold Blood: Fixed an issue where this buff was sometimes getting removed when an attack missed."

**Current behaviour**:
 Cold blood buff getting removed if special attack or finisher missed/dodged/parried.

**Expected behaviour**: 
Cold blood buff should stay active until attack lands.

**Server Revision**:

**Comment by The14me** [comment]
Rev.3460 still an issue.

**Comment by Wolffenstein** [comment]
Fixed in rev 3536.
