### ISSUE TITLE
[Karazhan]Prince Malchezaar using wrong abilities

### ISSUE THREAD

**Issue by Jalapan** [Atlantiss/NetherwingBugtracker#4961]
[//]: # (Enclose links to things related to the bug using http://wowhead.com or any other TBC database.)
[//]: # (You can use screenshot ingame to visual the issue.)
[//]: # (Write your tickets according to the format:)
[//]: # ([Quest][Azuremyst Isle] Red Snapper - Very Tasty!)
[//]: # ([NPC] Magistrix Erona)
[//]: # ([Spell][Mage] Fireball)
[//]: # ([Npc][Drop] Ghostclaw Lynx)
[//]: # ([Web] Armory doesnt work)
[//]: # (To find server revision type `.server info` command in the game chat.)

**Description**: 
Prince seems to do parrys from behind wich shouldnt be possible, also the ability that killed this melee player was "cleave" , prince should not have a cleave ability and if you look in the gif slowly you will see that prince turns and kills the rogue, even tho the rogue is not over tank in threat.
I belive that this is a parry, and prince should not be able to parry from behind, and he should not turn and hit someone else that is lower then tank in threat.
https://gyazo.com/8a5959228e430b9222419f5176d1aaae
**Current behaviour**:
Prince seems to do parrys from behind wich shouldnt be possible, also the ability that killed this melee player was "cleave" , prince should not have a cleave ability and if you look in the gif slowly you will see that prince turns and kills the rogue, even tho the rogue is not over tank in threat.
I belive that this is a parry, and prince should not be able to parry from behind, and he should not turn and hit someone else that is lower then tank in threat.
https://gyazo.com/8a5959228e430b9222419f5176d1aaae
**Expected behaviour**: 
Melee should be safe to hit him prince from behind without him parrying, prince shouldnt have an ability called "cleave" and he should never target anyone except the tank.
**Server Revision**: 

https://wow.gamepedia.com/Prince_Malchezaar

https://wowwiki.fandom.com/wiki/Prince_Malchezaar

**Comment by Jalapan** [comment]
@Wolffenstein high prio please?

**Comment by Brasso** [comment]
I mean, even using your own sources you can find out that he is suppose to use cleave in the earlier versions. https://wowwiki.fandom.com/wiki/Prince_Malchezaar?oldid=497403

![image](https://user-images.githubusercontent.com/44345420/52558382-82b8de80-2df2-11e9-8bfb-445dcdef2052.png)

**Comment by Jalapan** [comment]
Then if you look at the video how can a melee dps get killed from a cleave from behind? it dosent make sense, and if you slowmo the video u see that prince turnseven tho the dps is under the tank in dps

**Comment by Brasso** [comment]
Cleave abilities chain in tbc, some people call it 360 cleave. Your tank is probably too close to the boss and not at max melee range, chaining the cleave from the tank to your rogue, or it chains from the tank -> 
pet -> rogue.

**Comment by Easyfraggy** [comment]
Need some evidence that he is parrying from behind. He never did that for me.

Cleaves are chain cleaves in patch 2.0 so if your melee or tank are badly placed you can indeed get cleaved behind the boss.
