### ISSUE TITLE
Shiv sometimes not doing anything

### ISSUE THREAD

**Issue by Dusky1** [Atlantiss/NetherwingBugtracker#4962]
As the title says, sometimes when I use Shiv, the poison is not applied and i cant see what happened.
(no dmg text, no resist text or whatsoever)
may be related : https://github.com/Atlantiss/NetherwingBugtracker/issues/3982

**Comment by Greytt** [comment]
This happens for me as well. When Shiv is on maximum hit range it does not even try to apply the poison. I don't get a resist or anything in my log. It just doesn't apply.
I am using Mik Scrolling Combat Text and I can see that shiv hits (icon + damage is shown) but there is no signs for poison and it's not on anyone.

**Comment by Easyfraggy** [comment]
Could it be same visual issue as execute where parry/dodge/miss doesn't show visually?

**Comment by Greytt** [comment]
> Could it be same visual issue as execute where parry/dodge/miss doesn't show visually?

It isn't applied and I can use it 4-5 times with the same thing happening. It def needs to be looked into.

**Comment by maxfactor1** [comment]
Adding to this comment, same behaviour observed.

This is game-breaking in pvp. Shiv is an essential tool for pvp rogues.

**Comment by Mercymurv** [comment]
Huge, huge problem. Rogue class is broken until further notice. My shivs not going off, just doing 100 dmg multiple times in a row (especially if target is slightly ahead of you), has been pretty rough. I thought it might be resists, but resists wouldn't happen so much or so particularly on far targets

**Comment by Mercymurv** [comment]
If you need video evidence I'll compile a video showing shiv not working many times, multiple times straight, especially on targets who are running. When they stop and I get right up in their face, shiv has a higher probability of working. 
This really breaks arena when you are trying to shiv wolves and cheetahs around pillars and you hear shiv go off, but no affect, again and again in a row, just your whole energy gets depleted for a few hundred damage from your offhand.

**Comment by Mercymurv** [comment]
https://youtu.be/Odsksg63fYI

Here's a video demonstrating 29 Shivs on a druid, 15 of which did not work. Is this a priority fix?

**Comment by Wolffenstein** [comment]
Fixed in rev 2898. If still bugged - make a new ticket.
