### ISSUE TITLE
[Spell][Warrior] Piercing howl vs stealth/vanish

### ISSUE THREAD

**Issue by teddys** [Atlantiss/NetherwingBugtracker#4966]
**Current behaviour**: Using piercing howl ( http://db.hellfire-tbc.com/?spell=38256 ) does not break rogue/druid's stealth/vanish

**Expected behaviour**:  Using piercing howl (same as demoralizing shout) breaks rogue/druid's stealth/vanish

**Server Revision**:  2776

**Comment by Easyfraggy** [comment]
Can confirm - this was common practice to break rogues out of stealth.

**Comment by teddys** [comment]
Using devour magic on a stealthed target also doesn't break stealth. I'd assume other things such as spellsteal/purge/dispel magic are the same.

**Comment by teddys** [comment]
bump

**Comment by teddys** [comment]
bump

**Comment by Wolffenstein** [comment]
Can't reproduce: https://gfycat.com/pl/harmfulablegazelle.

**Comment by Wolffenstein** [comment]
Dispels fixed in rev 2842. Need confirmation for Piercing Howl.

**Comment by teddys** [comment]
> Can't reproduce: https://gfycat.com/pl/harmfulablegazelle. Dispels are bugged indeed though.

confirmed fixed for both

**Comment by Cptnlobbe** [comment]
Devour magic is bugged again.. does not bring the target out of stealth.

**Comment by teddys** [comment]
Same as piercing howl :S

**Comment by teddys** [comment]
https://github.com/Atlantiss/NetherwingBugtracker/issues/5431

**Comment by Wolffenstein** [comment]
Fixed in rev 2906.

**Comment by santuzzo** [comment]
still broken
