### ISSUE TITLE
[Spell] Ancestral Fortitude doesn't proc from chainheal bounce

### ISSUE THREAD

**Issue by Pinju1** [Atlantiss/NetherwingBugtracker#4967]
**Description**: 
Ancestral Fortitude doesn't proc from Chain heal bounce crits

**Current behaviour**:
Ancestral Fortitude (https://tbc-twinhead.twinstar.cz/?spell=16237) doesn't proc from Chain heal (https://tbc-twinhead.twinstar.cz/?spell=1064) bounce crits (If chain heal casted on X and bounced to Y and Y target heal crit, Y target doesnt get ancestral fortitude)
**Expected behaviour**: 
Ancestral Fortitude should proc on all targets that got a crit

**Server Revision**: 2776

**Comment by devo6969** [comment]
This is fixed on the PTR.
PTR - https://www.youtube.com/watch?v=Swt1keA-Zfk
