### ISSUE TITLE
[QUEST/ITEM] Mission: Possible But Not Probable (Rogue Class Quest)

### ISSUE THREAD

**Issue by dupedful** [Atlantiss/NetherwingBugtracker#4969]
https://www.wowhead.com/item=8066/fizzules-whistle

I accidentally aborted the quest and wanted to take it again. Since I had already used up my charges for the light pistol, I wanted to use Fizzule's Whistle instead. (Which you get as a replacement for the light pistol if you have failed) But unfortunately it doesn't work. I can't accept the quest or anything. So I'm stuck.

I urge you to fix this quest / item as soon as possible. Otherwise, I and others have problems with later dungeons and raids and makes the game itself only more complicated without the poisonous.

**Comment by dupedful** [comment]
Edit: Taskmaster Fizzule's is hostile for rogues, except you use the flare gun (2x and salute) or after the flair guns charges are used Fizzule's Whistle. Both items should change his faction from hostile to friendly. Flare gun does, Fizulle's whistle does not. That's the problem. So if you used all charges of Flare gun, cancel the quest or fail, you should be able to try again with Fizzule's Whistle.

**Comment by dupedful** [comment]
Any chance of getting this fixed asap? I'm still not able to finish the rogue quest line for my poisons. That's a huge disadvantage for me in terms of leveling and dealing decent dps.

**Comment by Evolvee** [comment]
rev 2793

**Comment by Hemphiz** [comment]
Target him and Salute again. If it doesn't work get abit closer. After accepting the quest the whistle never seemed to work but saluting him works well
