### ISSUE TITLE
[Spell] Curse of the Blackheart

### ISSUE THREAD

**Issue by Bleachlol** [Atlantiss/NetherwingBugtracker#497]
**Description**: 
Looks like the spell was casted on the NPC itself and got stunned, Blackheart NPCs in Ashenvael for the quest: https://www.wowhead.com/quest=6441/satyr-horns
Spell ID: 41170 (from wowhead)
**Current behaviour**:
NPC casts the curse on itself. 
**Expected behaviour**: 
Should ALWAYS cast the curse on itself
**Server Revision**: 
2040

**Comment by Evolvee** [comment]
hopefully resolved in next revision

**Comment by Easyfraggy** [comment]
> **Description**:
> Looks like the spell was casted on the NPC itself and got stunned, Blackheart NPCs in Ashenvael for the quest: https://www.wowhead.com/quest=6441/satyr-horns
> Spell ID: 41170 (from wowhead)
> **Current behaviour**:
> NPC casts the curse on itself.
> **Expected behaviour**:
> Should ALWAYS cast the curse on itself
> **Server Revision**:
> 2040

Like what you write here is that it works correctly, could you please edit the OP to reflect the correct issue.

**Comment by Evolvee** [comment]
https://github.com/Atlantiss/NetherwingBugtracker/issues/1029

**Comment by Godmatik** [comment]
Was fixed - close
