### ISSUE TITLE
[core] Kill Credit isnt granted when PET last hits

### ISSUE THREAD

**Issue by perkydon** [Atlantiss/NetherwingBugtracker#4970]
[QUEST][HELLFIRE PENINSULA] A Burden of Souls.

**Description**: The quest is working well, apart from if you have a pet. 

**Current behaviour**: If you have a pet and the pet gets the killing blow, you do not get credit for the kills.

**Expected behaviour**: Your pet's killing blow should count as your own killing blow. Thus, giving you credit for the kill.

**Server Revision**: 2783.

**Comment by Evolvee** [comment]
did u damage the npc or did the pet kill the npc entirely?

also, this would be global core issue, not a quest issue

**Comment by Fuzedknight** [comment]
As I remember this didn't apply to normal kill quests but special events. For example pre rewrite of Ring of Blood, if your pet got the last hit absolutely nobody would get credit. This doesn't apply to simple kill x/10 quests.

**Comment by perkydon** [comment]
> did u damage the npc or did the pet kill the npc entirely?
> 
> also, this would be global core issue, not a quest issue

I did damage the NPC yes, but it was just the pet that got the killing blow. It isn't all quests, I'm finding every now and then on specific quests.

**Comment by Evolvee** [comment]
yea i get it

before i rewritten nagrand arena event, it was based on pure kill.. so someone could steal your boss and do it themselves, now it stores group of players that picked the quest

**Comment by Tereneckla** [comment]
Fixed
