### ISSUE TITLE
Hunter trap aggro

### ISSUE THREAD

**Issue by Lecia2134** [Atlantiss/NetherwingBugtracker#4971]
Aggro as the target is trapped seems to be WAY off. After trap breaks it aggros to healer, but thats not the exact issue, its the amount of damage that needs to be done in order to pull it back to you. they seem to almost be permanently attacking the healer. I have to hit it for a good 5-10% for it to come back to me. Not exactly sure if it should in fact aggro to healer. It seems logical as they can build some aggro through heals but it seems to be way too much. For example, sheep is much more manageable to pull off of heals. If it breaks it takes maybe 1 or 2 hits if that to get it off the target (healer).

**Comment by femdead** [comment]
CC targets should freeze their aggro table when CC'd so that's more of the issue if that isn't happening on this server

**Comment by Lecia2134** [comment]
Video proof that it is as Femdead said: https://youtu.be/i3Q1-qiViR8 chain trapping from original tbc. Never once aggros to healer.

**Comment by Lecia2134** [comment]
Further confirmed that NW was going for blizzlike with this but maybe it didnt pan out. Druid tank tried to taunt while it was trapped and it did nothing, did not work. If that doesnt work and cause aggro then why should heals while said target Is trapped?

**Comment by Zarant** [comment]
Crowd controlled mobs shouldn't build up any healing aggro.

Research about this topic has been done in the past here: https://vanilla-twinhead.twinstar.cz/?issue=7652

**Comment by Wolffenstein** [comment]
Fixed in rev 2786.
