### ISSUE TITLE
AH Issue

### ISSUE THREAD

**Issue by Hegdaddy** [Atlantiss/NetherwingBugtracker#4973]
Hi, I submitted a ticket to a GM but was told to post here instead.

I sold a Black Lotus on AH. I received the mail in game to say it had been purchased; however, no follow up mail was received with the actual gold in it. This was over 48 hours ago. Can you please review and transfer me the lost gold or atleast refund the item back. In game name is Hegdaddy (horde).

Cheers

**Comment by Tereneckla** [comment]
rev 3058
