### ISSUE TITLE
Shaman totem threat issue

### ISSUE THREAD

**Issue by cathabv** [Atlantiss/NetherwingBugtracker#4977]
**Description**: The shaman totems have more threat and a higher threat range then they should have. Several times now I've seen the totem aggro mobs, even if the totem is behind me, the mob will go straight for the totem instead of me. This is the case with mana and heal totem which should generate some amount of threat, but its also the case with say grounding totem which should not happen. Also seen in dungeon, if tremor totem is located behind me and tank fail to pick up a mob, the mob will go for the tremor totem.

**Current behaviour**: Shaman totems have higher threat range than the player, even totems which shouldnt generate any amount of threat. 

**Expected behaviour**: Mana, heal and fire totems should generate some amount of threat, they should however not have higher aggro range than the player. Totems such as grounding, tremor, wrath and windfury ++ should not generate any threat.

**Comment by The14me** [comment]
Rev.3483 not an issue anymore.
