### ISSUE TITLE
[Spell][Warlock] Life Tap generates threat , cancels mana regen and does not benefit from spelldmg

### ISSUE THREAD

**Issue by Jalapan** [Atlantiss/NetherwingBugtracker#4978]
[//]: # (Enclose links to things related to the bug using http://wowhead.com or any other TBC database.)
[//]: # (You can use screenshot ingame to visual the issue.)
[//]: # (Write your tickets according to the format:)
[//]: # ([Quest][Azuremyst Isle] Red Snapper - Very Tasty!)
[//]: # ([NPC] Magistrix Erona)
[//]: # ([Spell][Mage] Fireball)
[//]: # ([Npc][Drop] Ghostclaw Lynx)
[//]: # ([Web] Armory doesnt work)
[//]: # (To find server revision type `.server info` command in the game chat.)

**Description**: 
Life tap cause threat wich it should not do.
Life tap should get bonus from spelldmg from rank 3 and above.
It should also not interrupt mana regen.
**Current behaviour**:
Causes threat, dosent seem to get bonus from spelldmg and seems to interrupt mana regen.
**Expected behaviour**: 
Should bebefit from spelldmg from rank 3 and above
Should not cancel mana regen
Should not cause threat
**Server Revision**: 
2785

https://wow.gamepedia.com/Life_Tap

 Patch 1.12.0 (2006-08-22): This spell now benefits from effects which increase your spell damage. At rank 3 and above, the base amount of health lost and mana gained will increase by 80% of your bonus spell damage effects. Talents and items can further modify those values. Rank 1 and 2 receive reduced effect. 
Patch 0.12 (2004-10-11): No longer interrupts mana regeneration. 
Patch 0.8 (2004-07-07): No longer causes threat.

**Comment by Tenoutoften** [comment]
Just making sure, but you accounted for severely diminishing returns on spell damage for low level spells, right?

**Comment by Jalapan** [comment]
i dont understand your question, but the spelldmg benefits are not untill rank 3 and over (lvl 26 minumum) at this point you rarely have over 30spelldmg. so its not relevant.

**Comment by Balanarr** [comment]
A few hours ago it seemed to be benefitting from + spell damage.
I'm level 66 so I most likely have the last rank available .. rank 6 (420 hp into 420 mana). At around +500 spell damage I'm pretty sure my SCT was showing around 800 mana gained. Also without the exact info it does seem like I'm getting more mana than the 420 base since 420 mana pretty much means 1-2 spell casts which is not true.

Proof: http://oi68.tinypic.com/aak6pt.jpg

**Comment by Jalapan** [comment]
You still gain threat and mana regen is interrupted?

**Comment by Easyfraggy** [comment]
How do you know that it generates threat?

**Comment by Balanarr** [comment]
> 
> 
> You still gain threat and mana regen is interrupted?

Also checked the mana regen out of combat and is not affected in any way

**Comment by Jalapan** [comment]
use omen threat meter, set pet to auto attack only and press life tap.

**Comment by Easyfraggy** [comment]
Omen doesn't reflect server threat - theres no option for addons to see what threat the server has in TBC. 

Omen is estimate and is not a way to tell wether something gives threat or not.

I've shown you server threat after several lifetaps being 0 above.
