### ISSUE TITLE
[Spell][Priest] Smite - resisted a lot

### ISSUE THREAD

**Issue by H2714** [Atlantiss/NetherwingBugtracker#4979]
[//]: # (Enclose links to things related to the bug using http://wowhead.com or any other TBC database.)
[//]: # (You can use screenshot ingame to visual the issue.)
[//]: # (Write your tickets according to the format:)
[//]: # ([Quest][Azuremyst Isle] Red Snapper - Very Tasty!)
[//]: # ([NPC] Magistrix Erona)
[//]: # ([Spell][Mage] Fireball)
[//]: # ([Npc][Drop] Ghostclaw Lynx)
[//]: # ([Web] Armory doesnt work)
[//]: # (To find server revision type `.server info` command in the game chat.)

**Description**: 
Several NPCs around my own level have been able to fully resisted my [Smite](https://vanilla-wow.fandom.com/wiki/Smite).

**Current behaviour**:
Over 10% of my Smites get resisted (6 of 40ish).
![wowscrnshot_021219_192621](https://user-images.githubusercontent.com/46264740/52658921-8769b980-2efc-11e9-82d6-108a539b55fd.jpg)

**Expected behaviour**: 
Holy spells should (maybe) have a 1% chance at being resisted and a bit more of the if the target is 5+ more levels.

According to [Wowpedia](https://vanilla-wow.fandom.com/wiki/Holy_resistance) (pre 3.0 article) no one can resist holy spells. 

[Wow Wiki](https://vanilla-wow.fandom.com/wiki/Holy_resistance) (vanilla) notes that NPCs of a higher level then the player my do so. (This is not the case here)

Holy resistance was discussed in a previous [issue](https://github.com/Atlantiss/NetherwingBugtracker/issues/1190), which concluded that there is a 1% chance of resist on every spell. (I hope I'm not that unlucky)

**Server Revision**: 
2785

**Comment by H2714** [comment]
I continued to count my Smites and I have found that beasts seems to resist them a lot more than humanoids. 
This could of course a coincidence, I have not tested it enough to say it with any kind of certainty. Just thought it might be worth mentioning.

**Comment by Easyfraggy** [comment]
Whats the level difference between you and the mobs you are fighting?

**Comment by H2714** [comment]
They are 1-2 levels above me.
Where did you get those numbers?

**Comment by towneh** [comment]
It's worth noting that the 1% resist chance is versus players in those linked articles. PvE should be requiring the same spell hit amounts as any other spell versus npcs of differing levels as per Easy's above comment.

**Comment by Easyfraggy** [comment]
https://wow.gamepedia.com/index.php?title=Spell_hit&oldid=1303478 is probably the best source for spell hit - since it's directly confirmed by blizzard CM's.

**Comment by H2714** [comment]
Well that explains that. Thank you for the link, I had no idea spells were suppose to fail/be resisted that much based solely on level. 
This will make leveling as holy a bit trickier than I thought, the holy tree has no talent for spell hit! >.<
Case closed.
