### ISSUE TITLE
[Ashenvale][Q] Vorsha the Lasher Typo

### ISSUE THREAD

**Issue by johndwalker** [Atlantiss/NetherwingBugtracker#4980]
[//]: # (Enclose links to things related to the bug using http://wowhead.com or any other TBC database.)
[//]: # (You can use screenshot ingame to visual the issue.)
[//]: # (Write your tickets according to the format:)
[//]: # ([Quest][Azuremyst Isle] Red Snapper - Very Tasty!)
[//]: # ([NPC] Magistrix Erona)
[//]: # ([Spell][Mage] Fireball)
[//]: # ([Npc][Drop] Ghostclaw Lynx)
[//]: # ([Web] Armory doesnt work)
[//]: # (To find server revision type `.server info` command in the game chat.)

**Description**: 

Muglash says, "This will be a ***though*** fight, <name>. Follow me closely.

Screenshot: https://imgur.com/a/PTKPCBc

**Expected behaviour**: 

"though" should be "tough"

**Comment by danbopes** [comment]
Fixed rev 3118
