### ISSUE TITLE
[NPC] Arcatraz Sentinel ability + video proof

### ISSUE THREAD

**Issue by FuzzNFA** [Atlantiss/NetherwingBugtracker#4981]
NPC: Arcatraz Sentinel
Spell: I don't know its name, the only ability this mob has

**Description**: 
I am not sure if he should even use the lightning attack before death, but he seems to be using 4 lightning attacks at the same time as seen in the video
Link with the evidence: https://clips.twitch.tv/DeafPowerfulMuleTTours
**Current behaviour**:
Fires off mutliple abilities at once killing people in a second or two if they are not tank, in normal Arca
**Expected behaviour**: 
Casting non or just one lightning, depending on the patch.
**Server Revision**: 
2785

**Comment by Easyfraggy** [comment]
I also discovered this bug on closed beta but was unable to reproduce reliably - not sure what causes it.

**Comment by FuzzNFA** [comment]
We joked in the group that this looks like the windfury hits by Arcane dudes in Kara lib after Curator or like quadruple explosions on death by Spectral Performers before Kara or like double mine explosions in Blood Furnace. Stuff procs just too much on this server, be it on death effect, this effect or double strike aura. I am willing to bet the same underlining issue affects all these bugs.

Thanks for the labeling. We're going to keep filming all that we do to report video evidence as much as possible.

**Comment by FuzzNFA** [comment]
Happened again.

**Comment by Drayo** [comment]
I can confirm this issue, I personally ONLY experience this on the first Sentinel after the second and third Boss.

**Comment by MAY-THE-ETERNAL-SUN-SHINE-UPON-YOU** [comment]
Confirmed still happens, seemingly at random.

Here's a video where our group pulls 2 sentinels in a row, the first one works normally, the second one is bugged.
https://youtu.be/2uQmYCA4FRA
At 0:10 the first sentinel is pulled, normal damage.
At 1:01 the second sentinel is pulled, goes full Emperor-Palpatine-UNLIMITED-POWER.jpg shocking people 5 times a second like Mike Pence was giving me gay conversion therapy.

**Comment by Tereneckla** [comment]
fixed
