### ISSUE TITLE
Paladin spells still broken.

### ISSUE THREAD

**Issue by Shibester** [Atlantiss/NetherwingBugtracker#4982]
Currently I'm noticing 2 major issues:
1.  [Crusader Strike] doesnt apply Seal's damage/procs at all. 
2.  [Sanctified Seals] Can still be dispelled/purged.

Expected Behavior: 1 should be applying damage of seals, which it currently isn't doing. 2 should not be dispelled at all, but it still able to be dispelled.

Server revision: 2785

**Comment by zanthed1** [comment]
Crusader strike should not apply damaging seal effects. https://github.com/FeenixServerProject/Archangel_2.4.3_Bugtracker/issues/3482

**Comment by Easyfraggy** [comment]
1 issue per report only.

1. is invalid.
