### ISSUE TITLE
Improved expose armor

### ISSUE THREAD

**Issue by Furysammy** [Atlantiss/NetherwingBugtracker#4983]
[//]: # (Enclose links to things related to the bug using http://wowhead.com or any other TBC database.)
[//]: # (You can use screenshot ingame to visual the issue.)
[//]: # (Write your tickets according to the format:)
[//]: # ([Quest][Azuremyst Isle] Red Snapper - Very Tasty!)
[//]: # ([NPC] Magistrix Erona)
[//]: # ([Spell][Mage] Fireball)
[//]: # ([Npc][Drop] Ghostclaw Lynx)
[//]: # ([Web] Armory doesnt work)
[//]: # (To find server revision type `.server info` command in the game chat.)

**Description**: Devestate overides improved expose armor

**Current behaviour**:Devestate removes improved armor debuff

**Expected behaviour**: Devestate shoude not apply sunder armor if expose armor is higher armor reduction.
https://wowwiki.fandom.com/wiki/Improved_Expose_Armor

**Server Revision**: 2785

**Comment by gvozdeni** [comment]
Is this being worked on?

**Comment by Tereneckla** [comment]
Fixed
