### ISSUE TITLE
[NPC] Enraged Air Spirit

### ISSUE THREAD

**Issue by HukNetherwing** [Atlantiss/NetherwingBugtracker#4984]
[//]: # (Enclose links to things related to the bug using http://wowhead.com or any other TBC database.)
[//]: # (You can use screenshot ingame to visual the issue.)
[//]: # (Write your tickets according to the format:)
[//]: # ([Quest][Azuremyst Isle] Red Snapper - Very Tasty!)
[//]: # ([NPC] Magistrix Erona)
[//]: # ([Spell][Mage] Fireball)
[//]: # ([Npc][Drop] Ghostclaw Lynx)
[//]: # ([Web] Armory doesnt work)
[//]: # (To find server revision type `.server info` command in the game chat.)

**Description**: 
Enraged Air Spirits should spawn behind Dragonmaw Fortress in SMV around 67,69 where the netherskates are but they do not seem to spawn here.

**Current behaviour**:
Enraged Air Spirits should spawn behind Dragonmaw Fortress in SMV around 67,69 where the netherskates are but they do not seem to spawn here.

**Expected behaviour**: 
They should spawn near the netherskates behind Dragonmaw Fortress in SMV.
https://www.wowhead.com/npc=21060/enraged-air-spirit#comments
**Server Revision**: 
2785

**Comment by HukNetherwing** [comment]
Also, I haven't 100% confirmed but it seems like there's too few spawns behind altar of shadows.  I've been there a few times and could only find 1-2 max and no corpses.

**Comment by The14me** [comment]
Rev.3460 https://imgur.com/a/yvsX6dh
Not an issue anymore, Air spirit's are there.
