### ISSUE TITLE
[Hunter] [Skill] Multi-Shot often causes Auto Shot to shoot the wrong target.

### ISSUE THREAD

**Issue by gunzbngbng** [Atlantiss/NetherwingBugtracker#4985]
[//]: # (Enclose links to things related to the bug using http://wowhead.com or any other TBC database.)
[//]: # (You can use screenshot ingame to visual the issue.)
[//]: # (Write your tickets according to the format:)
[//]: # ([Quest][Azuremyst Isle] Red Snapper - Very Tasty!)
[//]: # ([NPC] Magistrix Erona)
[//]: # ([Spell][Mage] Fireball)
[//]: # ([Npc][Drop] Ghostclaw Lynx)
[//]: # ([Web] Armory doesnt work)
[//]: # (To find server revision type `.server info` command in the game chat.)

**Description**: When Multi-Shot hits multiple targets, Auto Shot will often begin shooting something different than your target.

**Current behaviour**: When Multi-Shot hits multiple targets, Auto Shot will often begin shooting something different than your target.

**Expected behaviour**: Auto Shot should always shoot your target.  Period.

**Server Revision**: 2785

**Comment by The14me** [comment]
Rev 3460 not an issue anymore.
Can be closed.
