### ISSUE TITLE
 [Spell][Mage] Ritual of Refreshment

### ISSUE THREAD

**Issue by ircfelix** [Atlantiss/NetherwingBugtracker#4986]
**Description**: 
Sometimes when summoning the table, the required two other people click the portal, but no table appears. Happens like 1 out of 10 times.

**Current behaviour**:
Sometimes when summoning the table, the required two other people click the portal, but no table appears. Happens like 1 out of 10 times.

**Expected behaviour**: 
There should always spawn a table if two people click the portal.

**Server Revision**: 
2785

**Comment by Tenoutoften** [comment]
This spell has additional issues:
- You can spam click it to remove it, even if you have 4 stacks in your inventory
- The object spawns on the mage position instead of the portal

**Comment by knasen88** [comment]
it's also possible to bug it out where no table spawns and a cooldown is placed. Prob with ppl clicking then canceling/moving

**Comment by Lenni-s** [comment]
"Ritual of Refreshment" is not consuming arcane powder x2
Is it some intended feature of this server? or can this bug be added to this ticket as well?

**Comment by Godmatik** [comment]
All of these bugs listed here were fixed a long time ago.

Closing.
