### ISSUE TITLE
[Spell][Mage] Spellsteal not always stealing the buff (only dispelling)

### ISSUE THREAD

**Issue by killablink** [Atlantiss/NetherwingBugtracker#4988]

**Comment by ircfelix** [comment]
Can confirm this

**Comment by killablink** [comment]
There are also some buffs that you can't spellsteal at all like a shaman's elemental mastery, combustion, etc. If you can dispel it with a purge or a priest dispel, you should be able to dispel it with a spellsteal, even if it does nothing for the mage.

**Comment by killablink** [comment]
This can be useful: https://wow.gamepedia.com/index.php?title=List_of_magic_effects&direction=next&oldid=1665262
