### ISSUE TITLE
[Objects] Herb nodes not spawning.

### ISSUE THREAD

**Issue by Lotsix03** [Atlantiss/NetherwingBugtracker#4990]
[//]: # (Enclose links to things related to the bug using http://wowhead.com or any other TBC database.)
[//]: # (You can use screenshot ingame to visual the issue.)
[//]: # (Write your tickets according to the format:)
[//]: # ([Quest][Azuremyst Isle] Red Snapper - Very Tasty!)
[//]: # ([NPC] Magistrix Erona)
[//]: # ([Spell][Mage] Fireball)
[//]: # ([Npc][Drop] Ghostclaw Lynx)
[//]: # ([Web] Armory doesnt work)
[//]: # (To find server revision type `.server info` command in the game chat.)

**Description**: Herb nodes seem to have very long respawn times or are just not spawning at all.  At least in the few zones I've run through.  That being barrens, silverpine forest, stranglethorn vale, ashenvale, tanaris.  Perhaps all nodes?  When I timed it, it took me 8 minutes to find another herb in barrens after finding one.  Seems a bit off.

**Current behaviour**:

**Expected behaviour**: 

**Server Revision**:

**Comment by Lotsix03** [comment]
EDIT:  Just did a 45 minute farming run around southern silverpine forest.  Not one briarthorn spawn.  Not a single one.  That whole side of the zone should be almost all briarthorn.  And this is reflected on the auction house.  There's barely any briarthorn on there.

**Comment by Lotsix03** [comment]
EDIT #2:  So after the 3 server restarts, spawn rates seemed to be ok for a bit but then fell back into the same problem as before.  I'm currently at liferoot, spent an hour in wetlands and picked a whopping 18 herbs.  It doesn't seem to matter what herb it is, they all aren't spawning within reason.

**Comment by Lotsix03** [comment]
So just a few minutes ago while pathetically farming goldthorn in arathi highlands, ALL the herb nodes (at least marked by gatherer) had herbs spawned at them for about 5ish minutes.  Seems there's some tweaking going.  Now, of course that's not tenable for the health of the game but my hope is you guys don't just revert it to the pitiful levels that we have previous.

**Comment by Shanksalot** [comment]
Yea did 3 runs around mulgore and only got 2 peacebloom. a few ours later i get to herb 55 and doing circuits around crossroads and only finding 1-2 per 30 mins. something is seriously wrong

**Comment by ndnd123** [comment]
Can confirm i just did several laps around Hinterlands at 12-13 server time, no respawns.

**Comment by fruvel** [comment]
this is true but not only in hinterlands, ALL vanilla herbs have problem with spawn, today i went from rebel camp to booty bay i find only one kingsblood, 0 goldthorn 0 whisker's 

what numer of herbs on map must be, but from respawn to respawn, i dont know what number of herbs must be in duskwood or stranglethorn, i quess that herbs have their optional number in specific zone

vanilla herbs goldthorn  - https://vanilla-twinhead.twinstar.cz/?object=2046
bruiseweed https://vanilla-twinhead.twinstar.cz/?object=1622 or any other herb have low respawn and i quess that on map where must be 20 herbs or 40 displayed is 10 or 5 herbs that is a very annoying me and other players- hard to skill alchemy, herbalism and for 4500 ppl on the server if in one zone will be like 300, where 100 have herbalism... so tell me what now ?

**Comment by Tereneckla** [comment]
rev 3205
