### ISSUE TITLE
Gnomish to Goblin engineering

### ISSUE THREAD

**Issue by Jau167** [Atlantiss/NetherwingBugtracker#4991]
[//]: # (Enclose links to things related to the bug using http://wowhead.com or any other TBC database.)
[//]: # (You can use screenshot ingame to visual the issue.)
[//]: # (Write your tickets according to the format:)
[//]: # ([Quest][Azuremyst Isle] Red Snapper - Very Tasty!)
[//]: # ([NPC] Magistrix Erona)
[//]: # ([Spell][Mage] Fireball)
[//]: # ([Npc][Drop] Ghostclaw Lynx)
[//]: # ([Web] Armory doesnt work)
[//]: # (To find server revision type `.server info` command in the game chat.)

**Description**: 
Gnomish to Goblin engineering
**Current behaviour**:
Book in Tanaris let me unlearn Gnomish engineering and learn Goblin engineering for 150 gold, but goblin engineering trainer doesnt sell me any schematics.
Book is working but specialition change is not. New trainer doesnt recognize u as Goblin/Gnomish after change.
**Expected behaviour**: 
After Change you should be able to learn schematics for specialition u changed to.
**Server Revision**: 
2788

**Comment by Easyfraggy** [comment]
Please retest this in rev 2797 (next server update).
