### ISSUE TITLE
[Quest] Corrupted Sabers

### ISSUE THREAD

**Issue by veekk** [Atlantiss/NetherwingBugtracker#4993]
**Description**:  Still not work

**Current behaviour**: Even after returning saber back nothing happens

**Expected behaviour**: Quest must be done after that

**Server Revision**: 2788

**Comment by Tenoutoften** [comment]
Did you talk with the cat?

**Comment by veekk** [comment]
yes

**Comment by fantom8** [comment]
Worked for me no problem on server revision 2851. It was bugged for me on launch but worked after the fix a little while ago.
