### ISSUE TITLE
[Arena]Lacking cosmetic flags & header stating players remaining & gold/green team

### ISSUE THREAD

**Issue by Tenoutoften** [Atlantiss/NetherwingBugtracker#4995]
**Description**: 
Lacking cosmetic flags & header stating players remaining & gold/green team
https://youtu.be/dkP2pzAo-lA?t=26

Spells for Green & Gold team found in the database:

https://db.excalibur.ws/?spell=32724
https://db.excalibur.ws/?spell=35774
https://db.excalibur.ws/?spell=32725
https://db.excalibur.ws/?spell=35775

There are spells for Team A and Team B as well, but not sure what those are for:
https://db.excalibur.ws/?spell=44683
https://db.excalibur.ws/?spell=44684

**Current behaviour**:
No header & no flags

**Expected behaviour**: 
Expect green & gold flags and a header

**Server Revision**: 
2788

**Comment by Wolffenstein** [comment]
Fixed in rev 2790.
