### ISSUE TITLE
[Arena Bugs] 

### ISSUE THREAD

**Issue by killablink** [Atlantiss/NetherwingBugtracker#4996]
**Description**: Gems aren't spawning.
Buffs under 30seconds get dispelled at the start of the game.

**Current behaviour**:

**Expected behaviour**: Gems should spawn. Buffs under 30 seconds shouldn't be dispelled at the start of the game

**Server Revision**: 2788

**Comment by Wolffenstein** [comment]
Can I get a source on those 30 second thing?

**Comment by killablink** [comment]
https://youtu.be/dkP2pzAo-lA?t=17
starts game with regrowth

**Comment by Wolffenstein** [comment]
Fixed in rev 2789.
