### ISSUE TITLE
[Quest] Rotting Hearts

### ISSUE THREAD

**Issue by Aphroditus-Netherwing** [Atlantiss/NetherwingBugtracker#4998]
**Description**:  Collect rotting hearts from Rissen hungers or stalkers 

**Current behaviour**: Items are currently dropping for only one person in the group.

**Expected behaviour**: Items from these mobs should be shared with the group as they are only drops and can not be found in game objects, Loot mode was using Group Loot.
[image showing only one person can loot](https://i.imgur.com/f7f6h92.jpg)

**Server Revision**: 
2788

**Comment by Amaraen** [comment]
This item is not a quest item and is tradeable, it would be inappropriate to duplicate it.
