### ISSUE TITLE
[Quest] Spinal Dust

### ISSUE THREAD

**Issue by Aphroditus-Netherwing** [Atlantiss/NetherwingBugtracker#4999]
**Description**: Collect 10 Spinal dust from Dreadbone Sentinel, Deathcage Sorcerer, Dreadbone Skeleton or Deathcage Scryer

**Current behaviour**: Items are currently dropping from the mobs but are not being shared when in a group

**Expected behaviour**: Items should be shared with the whole group when in a party [Image showing no shared loot on the items](https://i.imgur.com/f7f6h92.jpg)

**Link to quest**: [Spinal Dust (wowhead)](https://www.wowhead.com/quest=9218)

**Server Revision**: 
2788

**Comment by knasen88** [comment]
they're not actual quest items, you can trade them etc. it's prob cos it's a repeatable that gives a elixir
