### ISSUE TITLE
Combat

### ISSUE THREAD

**Issue by notsofamous** [Atlantiss/NetherwingBugtracker#5]
[//]: # (Enclose links to things related to the bug using http://wowhead.com or any other TBC database.)
[//]: # (You can use screenshot ingame to visual the issue.)
[//]: # (Write your tickets according to the format:)
[//]: # ([Quest][Azuremyst Isle] Red Snapper - Very Tasty!)
[//]: # ([NPC] Magistrix Erona)
[//]: # ([Spell][Mage] Fireball)
[//]: # ([Npc][Drop] Ghostclaw Lynx)
[//]: # ([Web] Armory doesnt work)

**Description**: 

**Current behaviour**:
If you're close to someone who's in combat, you also get into combat. Regardless if you're in party or not. The mob will attack you if the person who was fighting it dies.
https://i.gyazo.com/566bfb2ce6862ab7c01191eb565fc8f5.mp4

**Expected behaviour**: 
You should only get into combat if that person is in your party.
**Server Revision**:

**Comment by Phibs77** [comment]
Can confirm.

**Comment by Wolffenstein** [comment]
Weird, I thought I fixed this. Will take a look.

**Comment by John-Johnston** [comment]
Another bug is you stay in combat after a mob leashed: https://www.youtube.com/watch?v=2SYFO4qcL1E

**Comment by Evolvee** [comment]
http://tbc.internal.atlantiss.eu/showthread.php?tid=1543&highlight=combat

**Comment by John-Johnston** [comment]
Dropped combat after another player killed the mob that leashed

**Comment by galediex** [comment]
I can confirm this bug as well. You should only be placed in combat if your in a party with a player who engages a mob, also even if in a party you should only be placed in combat when in view of the mob if your far away when a party member engages the mob you are not placed in combat.

**Comment by wtRCH** [comment]
Fixed in rev. 2021
