### ISSUE TITLE
Another death bug

### ISSUE THREAD

**Issue by AlteredAli** [Atlantiss/NetherwingBugtracker#50]
[//]: # (Enclose links to things related to the bug using http://wowhead.com or any other TBC database.)
[//]: # (You can use screenshot ingame to visual the issue.)
[//]: # (Write your tickets according to the format:)
[//]: # ([Quest][Azuremyst Isle] Red Snapper - Very Tasty!)
[//]: # ([NPC] Magistrix Erona)
[//]: # ([Spell][Mage] Fireball)
[//]: # ([Npc][Drop] Ghostclaw Lynx)
[//]: # ([Web] Armory doesnt work)

**Description**: 
died to "Cursed Mage", released spirit and found myself stuck in the dead animation, unable to move while as a ghost.
![wowscrnshot_092318_072029](https://user-images.githubusercontent.com/43499721/45921859-5bc04580-bf01-11e8-809a-cc11f77944fc.jpg)

**Current behaviour**:

**Expected behaviour**: 

**Server Revision**:

**Comment by wtRCH** [comment]
We are known of that and currently working on fix that.
