### ISSUE TITLE
[NPC] Dragonmaw Bonewarder

### ISSUE THREAD

**Issue by mbzz88** [Atlantiss/NetherwingBugtracker#500]
**Description**: Spell cast by mob (Dragonmaw Bonewarder) called "Bone Shield" does far too much damage and absorbs too much.
http://db.hellfire-tbc.com/?npc=1057

**Current behaviour**: Damage shield component does 100 damage per hit, and absorbs an unknown amount. This is a level 23 mob, and I am unable to kill it, or even do any damage to it, as a 26 hunter
This mob also casts Curse of the Eye https://www.wowhead.com/spell=3360/curse-of-the-eye, which I think is only meant to be used by the undead pirates in the west of The Wetlands.

**Expected behaviour**: Significantly less damage and absorb.

**Comment by The14me** [comment]
https://github.com/Atlantiss/AtlantissTBCBT/issues/1945

**Comment by xmesaj2** [comment]
fix in rev 2054
