### ISSUE TITLE
Buff/Debuff replacing mechanic.

### ISSUE THREAD

**Issue by liderer** [Atlantiss/NetherwingBugtracker#5000]
There fully not working mechanics for replacing buffs and debuffs (snares /healing reduce effects etc  I was hoping that although it would work here ....  

How its should work : only the strongest debuff should be active .  
The same bug like others progect. 
https://github.com/SunwellWoW/Sunwell-TBC-Bugtracker/issues/385  

1) 
https://imgur.com/TvEyrBW  orc rasical - not remove wound poisons . 

proof : https://youtu.be/HC8_H1AiSHs?t=22m58s 

(Blood fury) removes 5x Wound Poison and makes him immune to gaining wound poison stacks for its duration.  

2) https://imgur.com/hi07Qoc  -all snares stack  

https://youtu.be/QyTyNaiEJKs?t=57
he taken damage of cone of cold , but slow debuff fully ignore ( he have 70 crippling) 

https://youtu.be/AyFZEjIEq_Y?t=155  fbolt  - no debuff 

https://youtu.be/iqqrO0iX11c?t=32   fbolt  - no debuff 

https://youtu.be/43Y...Y9-0OYINA?t=33  fbolt  - no debuff 

https://youtu.be/-41Dgo6auCA?t=418 piercing howl to fshock 

https://youtu.be/-41Dgo6auCA?t=715 fshock to hamstring 

https://youtu.be/-41Dgo6auCA?t=871 

https://youtu.be/3z2nV3pRDS0?t=354 piercing howl to hamstring .

**Comment by Evolvee** [comment]
known
