### ISSUE TITLE
autoattack sometimes bugs out due to /startattack

### ISSUE THREAD

**Issue by teddys** [Atlantiss/NetherwingBugtracker#5001]
**Description**:  /startattack macroed together with regular abilities somehow sometimes bugs out autoattacking(it stops until you detarget and target again) ... it may seem like it's not a big deal, but in pvp it's a huge deal.

I've seen a report about it here, but didn't manage to find it with the search function

**Current behaviour**:

**Expected behaviour**: 

**Server Revision**: 2791

**Comment by Easyfraggy** [comment]
https://github.com/Atlantiss/NetherwingBugtracker/issues/2795

Please add the thing about /startattack macros might be the missing link that explains why some players get it and I haven't had it after 20days+ played - also why do you want a macro like that all abilities except stuff like blind /startattack automaticly anyway?

**Comment by Dusky1** [comment]
you simple bind it to most used abilities to start attacking when u dont have enough rage/energy to use that skill but you dont wanna waste a swing or two until you actually can use that skill
