### ISSUE TITLE
Hunter talent and troll racial

### ISSUE THREAD

**Issue by AndHabb** [Atlantiss/NetherwingBugtracker#5002]
[//]: # ([Talent][Hunter][BM] Endurance Training)
[//]: # ([Spell][Troll] Regeneration)

**Description**: Endurance Training doesn't function as described.

**Current behaviour**: Increases only player health.

**Expected behaviour**: Increases both player and pet health.

=-=-=-=-=-=

**Description**: The troll racial "Regeneration" doesn't function at all.

**Current behaviour**: Does nothing.

**Expected behaviour**: Allows 10% of HP regeneration during combat.

**Comment by Easyfraggy** [comment]
Can someone confirm this?

**Comment by Skotia1** [comment]
![Endurance](https://user-images.githubusercontent.com/52295559/85369895-33c6a180-b52e-11ea-962b-8c4dfd57d107.jpg)

Confirm the first one.

**Comment by Tereneckla** [comment]
Troll Racial works,
The talent Endurance Training needs a relogg to be applied.
