### ISSUE TITLE
[Hunter][Spell] You can continue auto attacking in the middle of a Steady Shot cast or while channeling Volley

### ISSUE THREAD

**Issue by Kristoferhh** [Atlantiss/NetherwingBugtracker#5003]
**Description**: At least both Steady Shot and Volley are broken.

**Current behaviour**: Right now you continue auto attacking while casting Steady Shot and you can start auto attacking again while in the middle of channeling Volley

**Expected behaviour**: You should not be able to auto attack in the middle of these casts, just like you can't attack in the middle of casting Aimed Shot

**Server Revision**: 2791

**Comment by Easyfraggy** [comment]
https://github.com/Atlantiss/NetherwingBugtracker/issues/4791
