### ISSUE TITLE
Fel lotus drop chance

### ISSUE THREAD

**Issue by cathabv** [Atlantiss/NetherwingBugtracker#5004]
**Description**: I've been leveling herbalism and had my herb skill maxed since lvl 62-63. I have yet not looted a single Fel Lotus, which makes me belive the chance is too low on the server. In total I've herbed: 
156 Felweed
99 Dreaming Glory
61 Netherbloom
35 Terocone
35 Ragveil
23 Ancient Lichen
4 Mana Thistle
2 Nightmare Vine

Seeing as outlands herbs should have a 1-3% Fel Lotus drop chance, I belive the chance is too low. It can also be seen on AH where there is hardly any.

**Comment by Easyfraggy** [comment]
Your datasample is way too small if chance is 1-3% you need to do 5k+ herbs to get any reliable information however hopefully a dev can look into it on dev realm for you since gathering that much data on live realm would be rediculous.

**Comment by cathabv** [comment]
It was not intended as a reliable source, just letting you know why I believe what I do. Would be toally empty claim if I made a report saying I feel like drop chance is too low based on... "I just think so" ^^ So theres the numbers why I think its low :)

**Comment by Mikik3jr** [comment]
I can say that I've made more than 100 super manapots, 60-70 elixirs so far, I am over 500-600~ herbloots and I got only 1 Fel Lotus so far.

**Comment by Brasso** [comment]
The drop rate of Fel lotus from Felweed is about 0.9-1%, 1.1% from Dreaming glory, and 1.8% from Netherbloom (should be the highest drop rate of Fel lotus) in 2.0. I've lost count at how much I've gathered but I have gotten 29 Fel lotus so far, the drop rate feel pretty accurate.

Felweed
https://web.archive.org/web/20070525012340/http://thottbot.com/o181270
https://web.archive.org/web/20070227195519/http://www.wowhead.com/?object=181270

Netherbloom
https://web.archive.org/web/20070517225423/http://www.thottbot.com/o181279
https://web.archive.org/web/20070321075550/http://www.wowhead.com:80/?object=181279

Dreaming glory
https://web.archive.org/web/20070810024131/http://www.thottbot.com/o181271

**Comment by ircfelix** [comment]
I am also constantly getting Fel Lotuses. By constantly I don't mean a huge amount, but one lotus from time to time.

**Comment by Onsty** [comment]
It's all about your luck, guys. Getting 1-3 lotus each day, spending about 1-1.5h to farm herbs.

**Comment by Easyfraggy** [comment]
Seems like there are lots of people who think this issue is invalid - I'll close unless we get some solid evidence to the contrary - the rates atm on the server side reflect what has been mentioned from the webarchives above.
