### ISSUE TITLE
Arzeth's Demise

### ISSUE THREAD

**Issue by kemotix** [Atlantiss/NetherwingBugtracker#5005]
[//]: # (Enclose links to things related to the bug using http://wowhead.com or any other TBC database.)
[//]: # (You can use screenshot ingame to visual the issue.)
[//]: # (Write your tickets according to the format:)
[//]: # ([Quest][Azuremyst Isle] Red Snapper - Very Tasty!)
[//]: # ([NPC] Magistrix Erona)
[//]: # ([Spell][Mage] Fireball)
[//]: # ([Npc][Drop] Ghostclaw Lynx)
[//]: # ([Web] Armory doesnt work)
[//]: # (To find server revision type `.server info` command in the game chat.)

**Description**: 
 [NPC] Arzeth the Merciless can resist spell casted by quest item Staff of the Dreghood Elders.
**Current behaviour**:
After resist, [NPC] Arzeth the Merciless is still elite and attacks player.
**Expected behaviour**: 
Spell casted by Staff of the Dreghood Elders shouldn't be resistable.
**Server Revision**: 
2791

**Comment by The14me** [comment]
Rev.3460 cant reproduce it.
