### ISSUE TITLE
[Profession][Alchemy] Masterys dont work?!

### ISSUE THREAD

**Issue by naekobest** [Atlantiss/NetherwingBugtracker#5006]
**Description**: 
A few minutes ago i happily transmuted air -> fire with a proc of 3x

Then i went to unlearn transmute mastery and wanted to learn potion mastery. But then the following happend:
https://i.gyazo.com/thumb/1000/d4871ee2ffe6b271832d6aeefe2a4643-jpg.jpg

As you can see in chat, i have unlearned the transmute mastery. Then i went to the potion mastery guy and wanted to learn obv. potion mastery but here again i can only unlearn it?

Do i now have the potion mastery ability or no? 

**Server Revision**: 
2791

**Comment by naekobest** [comment]
Just tested some more.

Funny enough, you can double (atleast) learn alchemy masterys. Apparently i had transmute/potion all the time. Im not sure if i can learn elixier also

**Comment by ircfelix** [comment]
Same issue was already present at ptr for tailoring.

**Comment by Easyfraggy** [comment]
Please retest this after next server update (2797).
