### ISSUE TITLE
[Druid] Ferocious Bite (possibly other finishers too) not retaining combo points on dodge (or parry)

### ISSUE THREAD

**Issue by Luminnar** [Atlantiss/NetherwingBugtracker#5007]
**Description**: losing all combo points if ferocious bite is dodged (possibly even if parried, but i didn't test it yet)

**Current behaviour**: losing all combo points and energy if ferocious bite is dodged

**Expected behaviour**: should retain combo points and use only the necessary amount of energy

**Server Revision**:

**Comment by Wolffenstein** [comment]
Please retest in rev 2804.
