### ISSUE TITLE
[Quest][Eastern Plaguelands] Redemption doesn't have a dialog option

### ISSUE THREAD

**Issue by PatElder** [Atlantiss/NetherwingBugtracker#5008]
[//]: # (Enclose links to things related to the bug using http://wowhead.com or any other TBC database.)
https://vanilla-twinhead.twinstar.cz/?quest=5742

**Description**: 
After delivering the 3 quests for Tirion he should tell his story.

**Current behaviour**:
Inactive

**Expected behaviour**: 
Tells his story probably through a dialogue option.

**Server Revision**: 
2791

**Comment by knasen88** [comment]
Did you /sit before?

**Comment by PatElder** [comment]
Yes, he said sit and hear my tale so I did and nothing happened, I didn't
get dialogue.

**Comment by Evolvee** [comment]
![image](https://user-images.githubusercontent.com/1942409/52819042-9d1be200-30a8-11e9-8431-c441cdbe111f.png)

**Comment by Evolvee** [comment]
you need to sit
