### ISSUE TITLE
Engineering specialization change

### ISSUE THREAD

**Issue by Szilard91** [Atlantiss/NetherwingBugtracker#5009]
**Description**: I had 345 Gnomish engineering, I wanted to change to Goblin, so I unlearnt it and started to level again. After 225+ skill point I cant learn either spec, because I can't do again the quest. After I saw there is an NPC in Tanaris where I can unlearn Gnome Spec for 150gold, I did it, but still cant redo the prequest what open the Goblin Engineering start quests.

**Current behaviour**: I can not choose Engineering specialization

**Expected behaviour**: Able to do Gobling Engineering quest line (Goblin Engineering -> The Pledge of Secrecy -> Show Your Work

**Server Revision**:

**Comment by Easyfraggy** [comment]
Theres a way to swap from Gnomish to Goblin without unlearning Engineering in entirety (the npc you found later).

When you unlearn Engineering it should also automaticly remove your specialization - this is bugged from what you are saying above. 

Wasn't swapping specializations fixed recently?

**Comment by Wolffenstein** [comment]
Fixed in rev 2933.
