### ISSUE TITLE
[Spell][Paladin] Blessing of Wisdom

### ISSUE THREAD

**Issue by Mikik3jr** [Atlantiss/NetherwingBugtracker#501]
[//]: # (Enclose links to things related to the bug using http://wowhead.com or any other TBC database.)
[//]: # (You can use screenshot ingame to visual the issue.)
[//]: # (Write your tickets according to the format:)
[//]: # ([Quest][Azuremyst Isle] Red Snapper - Very Tasty!)
[//]: # ([NPC] Magistrix Erona)
[//]: # ([Spell][Mage] Fireball)
[//]: # ([Npc][Drop] Ghostclaw Lynx)
[//]: # ([Web] Armory doesnt work)

**Description**: 
Draenei priest Symbol of Hope overwrites Blessing of Wisdom.
**Current behaviour**:
There is a racial priest spell called Symbol of Hope that is up 15s and gives mana back, but it overwrites Blessing of Wisdom. It says "A more powerful spell is already active". Of course Symbol of Hope gives more mana regeneration than wisdom.
![wowscrnshot_092418_195214](https://user-images.githubusercontent.com/43505031/46005158-f3b26080-c0b4-11e8-8c10-874e0d87df38.jpg)

**Expected behaviour**: 
Well I haven't played it on retail, but I really don't think that a 15s buff should overwrite a 10 minute buff. Imagine in raid that you refresh your 30min buffs every 5 minutes.
**Server Revision**: 
2050

**Comment by Wolffenstein** [comment]
Fixed in rev 2067.
