### ISSUE TITLE
[Spell][Rogue] Stealth - enemy casts finish 

### ISSUE THREAD

**Issue by justhelpingxd** [Atlantiss/NetherwingBugtracker#5010]
https://www.twitch.tv/videos/380411571

When out of combat if an enemy casts anything (clone/sheep/smite etc.) and a rogue stealths while the cast still hasn't completed, the cast will continue and knock rogues out of stealth.  This has been attempted with and without members in a party. 

Also, auto attack bug after killing a target where if in stealth will break as it auto attacks even if a target isn't targeted. 
https://gyazo.com/fd56029c4f39b7df23a119f0dd0d83ec

**Comment by Easyfraggy** [comment]
Are you sure that the priest casting on you doesn't have vision of you in stealth?

**Comment by justhelpingxd** [comment]
He did not see me in stealth.  I did the mechanic multiple times to show that it was a bug.

**Comment by Easyfraggy** [comment]
Fair enough it just looked like he might be close enough to see you in stealth on the video.

**Comment by someotherplayer** [comment]
Can confirm. I had the same thing with a druid casting starfire lately.
Went into stealth when a druids starfire was at around 50-70% of its cast time. It still hit me.
The combat log clearly stated "You gain stealth" (no faerie fire ;) )
