### ISSUE TITLE
[Spell][Resist] This is yet another report about spells being resisted. *Updated

### ISSUE THREAD

**Issue by MatrixMKD** [Atlantiss/NetherwingBugtracker#5011]
It happens too damn often. I am "capped" with 3% hit and also 80 spell penetration (feels useless - waste of gems).

I feel like spell penetration is broken and u guys need to look into it. - I heard something went wrong with the last "update" but who knows.

Classes with shadow resistance, such as paladins/priests, even druids with their res. buff. can resist up to 3/4 or 4/5 spells in a row. Undeads resist an awful amount too with just +10 from racial, etc.
It should never be the case unless they got extremely lucky with "1% always miss" which i highly doubt they did.
Other ppl experienced it too who can relate to me, I love this server so i care a lot and u guys are doing amazing job so i want it all to be "perfect" or close to it.

My question is does spell penetration even work or is something wrong with spell hit? I'd place my bets on the former. 
I noticed how u fixed the "Reflect spell" ability by warriors/bosses,etc. to reflect everything, not just dots and to receive damage from direct spells as well. 
I believe in u and i know u can make SERVER GR8 AGAIN. :) I have faith... 

Thx in advance!

**Comment by Easyfraggy** [comment]
Bug compilations and multiple bug posts will all be closed - leaving open to give you the chance to edit it to only reflect 1 bug. 

Multiple bugs in 1 thread always get overlooked and forgotten.

**Comment by MatrixMKD** [comment]
might be fixed by now... i been testing it the last few days, seems much better! U guys are totally amazing and quick. <3 much love
