### ISSUE TITLE
[Spell][Warrior] Intercept

### ISSUE THREAD

**Issue by hammcsuds** [Atlantiss/NetherwingBugtracker#5012]
[//]: # (Enclose links to things related to the bug using http://wowhead.com or any other TBC database.)
[//]: # (You can use screenshot ingame to visual the issue.)
[//]: # (Write your tickets according to the format:)
[//]: # ([Quest][Azuremyst Isle] Red Snapper - Very Tasty!)
[//]: # ([NPC] Magistrix Erona)
[//]: # ([Spell][Mage] Fireball)
[//]: # ([Npc][Drop] Ghostclaw Lynx)
[//]: # ([Web] Armory doesnt work)
[//]: # (To find server revision type `.server info` command in the game chat.)

**Description**: 
Intercept is sharing a Diminishing Returns timer with Charge

**Current behavior**: 
Charge into an Intercept inside a "DR" window results in a 1.5s Intercept stun

**Expected behavior**: 
Intercept has a controlled stun category while Charge does not

**Server Revision**: 
https://wowwiki.fandom.com/wiki/Diminishing_returns

Since patch 1.9 Mace procs are also independent stuns (untest for this issue)
https://vanilla-wow.fandom.com/wiki/Patch_1.9.0

**Comment by Crusaderz** [comment]
Source link is not TBC related. Intercept stun shared DR with charge in TBC.
You can see that intercept stun does not lasts 3 seconds when used after charge:
https://youtu.be/ysH5NC0aPeQ?t=26
https://youtu.be/VZk1NJXHUqk?t=233
https://youtu.be/9c9sfRfc2_Q?t=277
https://youtu.be/PbHQFJI3Erk?t=62
