### ISSUE TITLE
[Steamvault] Hydromancer Thespia - Lightning Cloud Heroic mode.

### ISSUE THREAD

**Issue by Firroth** [Atlantiss/NetherwingBugtracker#5014]
[NPC] https://wowwiki.fandom.com/wiki/Hydromancer_Thespia

**Current behaviour**:
On heroic mode she uses only 1 Lightning Cloud, when it should be 1 for normal mode, 2 for heroic mode. 

**Expected behaviour**: 
On heroic mode she should be using 2 Lightning Clouds, instead of 1.

![screenshot_4](https://user-images.githubusercontent.com/43505196/52826858-cf3a3d80-30c2-11e9-8232-21e13ed4840d.png)

![screenshot_5](https://user-images.githubusercontent.com/43505196/52826926-04df2680-30c3-11e9-94da-3b95c6b639e9.png)

**Server Revision**: 
2791

**Comment by Easyfraggy** [comment]
This is invalid - it's just bad wording - already discussed on closed beta. There are videos from 2.0.3-2.0.6 where its 1 cloud at a time.

**Comment by Firroth** [comment]
@Easyfraggy 
Ok, then tell me this:
How do you know your video is made on HEROIC mode? Title doesn't say it's heroic, nothing in the description as well, loot wasn't shown -> where they loot BoJ's f.e

This video was propably made on NORMAL mode, since everything in it suggests as much. If you want to convince me otherwise show me better proof.

**Comment by Easyfraggy** [comment]
Well if shes supposed to cast it more frequently that's a totally different issue. She should spawn them with about 30-50% overlap so if duration is 12 seconds every 6-9 seconds.

You see the problem with "5 lightning clouds" if she spawned 2 at a time right?

**Comment by usernametaken01** [comment]
> Well if shes supposed to cast it more frequently that's a totally different issue. She should spawn them with about 30-50% overlap so if duration is 12 seconds every 6-9 seconds.
> 
> You see the problem with "5 lightning clouds" if she spawned 2 at a time right?

You nerfed her clouds after u tested it in closed beta, mabe wolf overnerfed it?

**Comment by Easyfraggy** [comment]
> > Well if shes supposed to cast it more frequently that's a totally different issue. She should spawn them with about 30-50% overlap so if duration is 12 seconds every 6-9 seconds.
> > You see the problem with "5 lightning clouds" if she spawned 2 at a time right?
> 
> You nerfed her clouds after u tested it in closed beta, mabe wolf overnerfed it?

We only nerfed it in the sense that we made her spawn 1 cloud at a time instead of 2. The frequency wasn't changed. But yeah maybe frequency is too low - idk im still leveling.
