### ISSUE TITLE
Minor bug with Cuergo's Gold landmark

### ISSUE THREAD

**Issue by Mizers** [Atlantiss/NetherwingBugtracker#5015]
[//]: # (Enclose links to things related to the bug using http://wowhead.com or any other TBC database.)
[//]: # (You can use screenshot ingame to visual the issue.)
[//]: # (Write your tickets according to the format:)
[//]: # ([Quest][Azuremyst Isle] Red Snapper - Very Tasty!)
[//]: # ([NPC] Magistrix Erona)
[//]: # ([Spell][Mage] Fireball)
[//]: # ([Npc][Drop] Ghostclaw Lynx)
[//]: # ([Web] Armory doesnt work)
[//]: # (To find server revision type `.server info` command in the game chat.)

**Description**: Quest Cuergo's Gold in Land's End Beach

**Current behaviour**: You can see a stack of rabbits on each side of the treasure chest where the mobs spawn from when you interact with the landmark. I remember reading that Blizzard likes to use invisible rabbits for events so I'm guessing these are those rabbits, but for some reason they're visible. https://imgur.com/a/GpIU1s4 here's a couple of screenshots of what it looks like. As title suggests this is a minor bug, the quest itself functions as normal. I've read a bug report from when the quest wasn't working and apparently this was fully rewritten, so I'm guessing the rabbits are from that.

**Expected behaviour**: Rabbits shouldn't be visible.

**Server Revision**: 2791

**Comment by Evolvee** [comment]
rev 2798
