### ISSUE TITLE
GCD Issue Upon Swapping Targets

### ISSUE THREAD

**Issue by MelEnt** [Atlantiss/NetherwingBugtracker#5016]
[//]: # (Enclose links to things related to the bug using http://wowhead.com or any other TBC database.)
[//]: # (You can use screenshot ingame to visual the issue.)
[//]: # (Write your tickets according to the format:)
[//]: # ([Quest][Azuremyst Isle] Red Snapper - Very Tasty!)
[//]: # ([NPC] Magistrix Erona)
[//]: # ([Spell][Mage] Fireball)
[//]: # ([Npc][Drop] Ghostclaw Lynx)
[//]: # ([Web] Armory doesnt work)
[//]: # (To find server revision type `.server info` command in the game chat.)

**Description**: 
Global cooldown clears its visual spinner upon changing target

**Current behaviour**:
Global cooldown clears its visual spinner upon changing target

**Expected behaviour**: 
GCD should just continue to tick even if you swap targets. Also a similar bug happening when you swap targets during a cast, e.g., 1. cast frostbolt or any other spell with cast time, 2. swap targets mid cast 3. watch how cast bar disappears
**Server Revision**: 
2791

**Comment by Easyfraggy** [comment]
Afaik gcd is client side - correct me if im wrong @Evolvee

**Comment by Evolvee** [comment]
?

**Comment by MelEnt** [comment]
?

Inviato da iPhone

Il giorno 15 feb 2019, alle ore 23:48, Evolve <notifications@github.com<mailto:notifications@github.com>> ha scritto:


?
