### ISSUE TITLE
[PVP] The Daily Bonus count gets reset on server restart

### ISSUE THREAD

**Issue by transphenomenal** [Atlantiss/NetherwingBugtracker#5019]
[//]: # (Enclose links to things related to the bug using http://wowhead.com or any other TBC database.)
[//]: # (You can use screenshot ingame to visual the issue.)
[//]: # (Write your tickets according to the format:)
[//]: # ([Quest][Azuremyst Isle] Red Snapper - Very Tasty!)
[//]: # ([NPC] Magistrix Erona)
[//]: # ([Spell][Mage] Fireball)
[//]: # ([Npc][Drop] Ghostclaw Lynx)
[//]: # ([Web] Armory doesnt work)
[//]: # (To find server revision type `.server info` command in the game chat.)

**Description**: 
The number of wins in battlegrounds and arena shown by .char pvp gets reset after a server crash.
(The count may have reset in the 1 hour between my checking .char pvp and the server crash in that time was a coincidence)

**Current behaviour**:
When using .char pvp after a server crash, you will have 0 played arena games and 0 played battlegrounds. The Daily Bonus Claimed is set to "no". This will possibly let us accumulate more honor/arena points than normal or wipe away your current progress for that day.

**Expected behaviour**: 
The number of wins/loses should be saved between server crashes/restarts.

**Server Revision**: 
2796

**Comment by Wolffenstein** [comment]
It only resets at the same time as daily quests.
