### ISSUE TITLE
Karazhan Trash Loot [Database Issue]

### ISSUE THREAD

**Issue by Anonyxx** [Atlantiss/NetherwingBugtracker#5020]
[//]: # (Enclose links to things related to the bug using http://wowhead.com or any other TBC database.)
[//]: # (You can use screenshot ingame to visual the issue.)
[//]: # (Write your tickets according to the format:)
[//]: # ([Quest][Azuremyst Isle] Red Snapper - Very Tasty!)
[//]: # ([NPC] Magistrix Erona)
[//]: # ([Spell][Mage] Fireball)
[//]: # ([Npc][Drop] Ghostclaw Lynx)
[//]: # ([Web] Armory doesnt work)
[//]: # (To find server revision type `.server info` command in the game chat.)

**Description**: 

Currently, only one trash item (Belt of the tracker) is dropping as kara trash loot. No other kara trash drops have dropped, despite the fact that they should be in the game.

**Current behaviour**:

Invalid loot tables on all Kara mobs for all the karazhan trash epic drops (apart from belt of the tracker).

**Expected behaviour**: 

All trash epics should have a chance to drop.

**Server Revision**: 
2796

**Comment by towneh** [comment]
Confirming that I have seen only Belt of the Tracker drop from trash mobs in Karazhan raids so far.

Taking a closer look by inspecting profiles from members of the more progressive raiding guilds on Netherwing that are on legacyplayers.com I haven't been able to find Ritssyn's Lost Pendant present, nor shown as a drop on any raids logged from Netherwing realm.

**Comment by Za262** [comment]
Can confirm, 3 weeks of Kara and have seen 7 Belt of the Tracker and no other trash drops so far. 3 raid groups in guild have had the same thing, no other drops, but the belt.

**Comment by Drayo** [comment]
We also only got the Belt a few times with 3 Groups running every week, no other Items (aside from patterns) are dropping.

**Comment by ircfelix** [comment]
In SSC we only had vortexes and plate healing boots. Maybe this is related.

**Comment by killablink** [comment]
You also have to think about which items are drop in 2.0. In SSC, there aren't many trash drop epics aside from those boots and a melee dps neck.

**Comment by towneh** [comment]
These things were dropping in TBC beta...

**Comment by killablink** [comment]
Actually looking quickly through it, it seems that these trash loot (for ssc anyways) shouldn't even be in the game because they're from 2.1
https://www.wowhead.com/item=30027/boots-of-courage-unending

Would explain why only two items are dropping from ssc, probably didn't remove all of them correctly

**Comment by Drayo** [comment]
https://www.wowhead.com/item=30027/boots-of-courage-unending

Is (Patch 2.0.8) though. 

All items should be ingame aside from SSC patterns as far as I know.

**Comment by Evolvee** [comment]
this is an issue for karazhan, if u have issue with SSC make a new report

**Comment by Tenoutoften** [comment]
Wowhead's "Added in patch" is very unreliable, can find all these items in archive prior to 2.1

**Comment by Anonyxx** [comment]
SSC items were in patch 2.0. They were famously so, because Nihilum complained to Blizzard about the terrible stats the trash loot had (worse than heroic gear). This led them to completely rethink stats and itemisation for tier 6 (and some t5 items) and they hired the guy who made the post.
