### ISSUE TITLE
[Spell][Warrior] Demoralizing Shout makes [NPC] Tempest-Forge Destroyer way too weak.

### ISSUE THREAD

**Issue by Mikik3jr** [Atlantiss/NetherwingBugtracker#5021]
[//]: # (Enclose links to things related to the bug using http://wowhead.com or any other TBC database.)
[//]: # (You can use screenshot ingame to visual the issue.)
[//]: # (Write your tickets according to the format:)
[//]: # ([Quest][Azuremyst Isle] Red Snapper - Very Tasty!)
[//]: # ([NPC] Magistrix Erona)
[//]: # ([Spell][Mage] Fireball)
[//]: # ([Npc][Drop] Ghostclaw Lynx)
[//]: # ([Web] Armory doesnt work)
[//]: # (To find server revision type `.server info` command in the game chat.)

**Description**: 
We applied the shout on Tempest-Forge Destroyer in Mechanar HC.
![image](https://user-images.githubusercontent.com/43505031/52864879-76f35200-313b-11e9-8962-5730751a3b87.png)

**Current behaviour**:
After you apply the shout instead of 2 trucks it hits wet noodles:
![image](https://user-images.githubusercontent.com/43505031/52864917-9be7c500-313b-11e9-9806-a795fbc7ad7e.png)
(This is my armor)
![image](https://user-images.githubusercontent.com/43505031/52865069-f1bc6d00-313b-11e9-950e-14c0573a158f.png)
We had a fury warrior and that warrior could survive 6+ hits without getting any heal. I only experienced this weakness only from this NPC in Mechanar.

**Expected behaviour**: 
I don't think that -300ap makes a truckhitting npc this weak, while everything else stays almost as strong as they were before shout.

**Server Revision**: 
2796

**Comment by Tenoutoften** [comment]
With fully speced demo shout you can expect a ~30% damage reduction

**Comment by Mikik3jr** [comment]
Still from 5k dmg (into our full prebis some kara itemed warrior tank)--> fury warrior 1.4k~ dmg, with only -300ap is impressive, and we are talking about a heroic run. No other mobs in the dungeon suffer this level of weakness from this shout, only this one.

**Comment by Tenoutoften** [comment]
Yeah it definitely looks wrong
