### ISSUE TITLE
Most crucial issues in Alterac valley right now that needs fix ASAP

### ISSUE THREAD

**Issue by usernametaken01** [Atlantiss/NetherwingBugtracker#5023]
**Drek' Tar is missing his wolfs:**
[Duros](https://www.wowhead.com/npc=12122/duros#comments) Should be on Drek'Thar left.
[Drakan](https://www.wowhead.com/npc=12121/drakan) Should be on Drek'Thars right.

** If killed they should always respawn if Drek'Thar is reset.**

**This is the spell they should have:**
https://wotlk-twinhead.twinstar.cz/?npc=12121#abilities

**How the wolfs should be positioned when the tower guards are up:**
https://www.youtube.com/watch?v=JnTwmyp2Rq8&feature=youtu.be&t=132

**How the wolfs should be positioned When all the tower guards are down:**
https://youtu.be/apdkAvbiIxg?t=7

**The position of the NPCs in Drek'tars/vanndars room are so bad. This is how they should stand:**
https://youtu.be/JnTwmyp2Rq8?t=133 - Drek' tar's room
https://www.youtube.com/watch?v=ciUZpaxnwDI - Vanndar's room

**Currently you can pull out the marshals one by one very abusive... they should reset like this on both horde and alliance:**
https://www.youtube.com/watch?v=JnTwmyp2Rq8&feature=youtu.be&t=132

**There are no Bowmans in AV (wtf?!) The towers and bunkers got the wrong NPC's**
Horde currently got https://www.wowhead.com/npc=12053/frostwolf-guardian
Alliance currently got  https://www.wowhead.com/npc=12050/stormpike-defender

**These are the correct ones:** (make sure they are stationary they dont move seen [here](https://youtu.be/mNWIHR5GMh0?t=138)
https://www.wowhead.com/npc=13359/frostwolf-bowman - For Horde
https://www.wowhead.com/npc=13358/stormpike-bowman - For Alliance

**The shoot they should have is this one and evolve had proper dmg on em during close beta so ask him what values he used(but for TBC link is for the vanilla version TBC part of twinhead is broken for me):**
https://vanilla-twinhead.twinstar.cz/?spell=22121

**The NPC's at graveyard flags are wrong:**
Currently:
https://www.wowhead.com/npc=13326/seasoned-defender
https://www.wowhead.com/npc=13328/seasoned-guardian

Should be:
https://www.wowhead.com/npc=12050/stormpike-defender - For alliance
https://www.wowhead.com/npc=12053/frostwolf-guardian - For horde

**When flags are being contested the NPC's guarding that flag if its a graveyard or tower/bunker they should stay there until the flag have turned to the opposite faction.**

**You dont get dismounted when you enter towers**

**All 4 bosses and marshals are missing abilitys and are hitting like low as fuck even with all tower buffs. marshals hit for max 2k on cloth-.- should 1 shot people really all npcs needs a overall % increase in dmg**

Alliance marshals missing abilitys:
https://vanilla-twinhead.twinstar.cz/?npc=14765#abilities (This is the vanilla version need to find the horde version of the same spells)

Hordes Marshals missing abilitys:
https://vanilla-twinhead.twinstar.cz/?npc=14777#abilities (This is the vanilla version need to find the horde version of the same spells)

Captain Galvangar:
https://wow.gamepedia.com/index.php?title=Captain_Galvangar&oldid=1335444

Captain Balinda Stonehearth:
https://wow.gamepedia.com/index.php?title=Captain_Balinda_Stonehearth&oldid=1481070

Drek'Thar:
https://wow.gamepedia.com/index.php?title=Drek%27Thar&oldid=1227998

Vanndar Stormpike:
https://wow.gamepedia.com/index.php?title=Vanndar_Stormpike&oldid=1481072

**Comment by Manaci** [comment]
These issues really have to be looked at already. Espcecially the missing loot when removing enemy player insignias. You can only loot silver from the, no https://db.excalibur.ws/?item=17326, https://db.excalibur.ws/?item=17327, https://db.excalibur.ws/?item=17306, https://db.excalibur.ws/?item=17328, all the class specific drops like https://db.excalibur.ws/?item=18206 etc from them or from drops from npcs. Right now you can't do anything other than zerg or defend with your numbers as none of this is working and most of the quest handin NPCs are missing to such a high degree that well, it'll take ages to gather it all and I'd like for it to actually be worked upon and not ignored as this one has been. 

I know there's been plenty of other stuff to work on so far but at least have a developer re-bump stuff like this to show that you're still working on it.

**Comment by Godmatik** [comment]
Closing - will consolidate all outstanding AV issues into one thread now.
