### ISSUE TITLE
Combat Animation Bug

### ISSUE THREAD

**Issue by floridalady** [Atlantiss/NetherwingBugtracker#5024]
like 90% after fighting in pvp im stuck in combat animation. thats not just annoyin in a visual way it also : dismounts u when u click ur self / eating sometimes stop cause u keep standing / if u click on a enemie u instantly start attackin ( bug effects rogue very hard ). log out , kill another npc or go into a dungon ( range kill on critters dont help ) u dont get rid of it until u do that.

ps : unable to hit check next post.

**Comment by Easyfraggy** [comment]
Only 1 bug per issue please - all compilations and multiple bug posts will be closed - gonna leave this open so you can edit it to reflect 1 or the other bug.
