### ISSUE TITLE
[Spell][Rogue] disarm trap 

### ISSUE THREAD

**Issue by AndrewNB41191** [Atlantiss/NetherwingBugtracker#5026]
[//]: # (Enclose links to things related to the bug using http://wowhead.com or any other TBC database.)
[//]: # (You can use screenshot ingame to visual the issue.)
[//]: # (Write your tickets according to the format:)
[//]: # ([Quest][Azuremyst Isle] Red Snapper - Very Tasty!)
[//]: # ([NPC] Magistrix Erona)
[//]: # ([Spell][Mage] Fireball)
[//]: # ([Npc][Drop] Ghostclaw Lynx)
[//]: # ([Web] Armory doesnt work)
[//]: # (To find server revision type `.server info` command in the game chat.)

**Description**: Unsure if this is a bug. I am able to disarm my own factions traps not in duel or arena. All the whiny hunters are calling me a bug abuser for disarming their traps so they cant steal my ele air tags.

**Current behaviour**: disarming same factions traps

**Expected behaviour**:  who knows.

**Server Revision**:

**Comment by AndrewNB41191** [comment]
have heard mixed reports in world chat from "retail rogues"

**Comment by SlizeTBC** [comment]
Patch 1.5.0 (patch date:2005-06-07): It should no longer be possible to disarm traps created by friendly players.

**Comment by The14me** [comment]
Rev. 3460 not an issue anymore.
