### ISSUE TITLE
Abolish Poison

### ISSUE THREAD

**Issue by ttghnw** [Atlantiss/NetherwingBugtracker#5027]
**Description**: 
The druid ability is still not properly removing a rogue's blind with the over-time effect.
Should remove poison with each tick.

The resolution reported on ticket #4154  did not fix this.
**Expected behaviour**:

**Comment by dinsfireyo** [comment]
FOOL blind is a physical debuff what a noooob u cant see the red border around ur debuff or what

**Comment by Zadiel** [comment]
No reason to be rude about it. 

He is correct, though, in that Blind is a physical debuff and not a poison.

**Comment by Easyfraggy** [comment]
Blind is not a poison effect.

**Comment by ttghnw** [comment]
@dinsfireyo Fool? It only became non-poison in patch 2.3.0 and we are at what patch??
Ah well pick and choose patching.

**Comment by ttghnw** [comment]
@Easyfraggy we are not at the above mentioned patch.

**Comment by Easyfraggy** [comment]
PvP mechanics are all 2.4.3 only PvE is 2.0 state.

**Comment by Zadiel** [comment]
This server is on patch 2.4.3 with earlier patch (2.0 I believe?) items. Please do your research before commenting again.
