### ISSUE TITLE
[Spell] Alchemy [Transmute: Primal Might]

### ISSUE THREAD

**Issue by toucem** [Atlantiss/NetherwingBugtracker#5028]
[//]: # ([Spell] Alchemy [Transmute: Primal Might]
**Description**: I made a Arcanite Bar transmute then wanted to do Primal Might transmute but game told me can't do it but I had no cooldown when was trying to make it cause arcanite transmute and primal might does not share cds and actually I did once first Primal might and then arcanite bar it was okay.

**Current behaviour**: Shares Cd with arcanite bar transmute but you can't see cd on primal might after use that also can do primal might then arcanite but not the other way around.

**Expected behaviour**: Does not share same cd with Arcanite Bar transmute

**Comment by Easyfraggy** [comment]
Can someone confirm/deny this?

**Comment by Brasso** [comment]
Can confirm.

**Comment by WarriorTSW** [comment]
Sounds like a cache issue to me. A reload would likely fix. Deletion of cache would almost certainly fix it.

**Comment by towneh** [comment]
One of my guild members just warned us this morning that using transmute arcanite bar has now incurred a cooldown on ALL his transmutes.

**Comment by Aphroditus-Netherwing** [comment]
all transmutes share the same 23 hr cooldown, barring the meta gem stones, which are 48. Those were changed in 2.1 however to 23 hrs as well.

**Comment by Aphroditus-Netherwing** [comment]
Further confirmation of the CD very first comment
https://www.wowhead.com/spell=17187/transmute-arcanite#comments

**Comment by MikeStinse** [comment]
just gave my primal might a 24hr cd making arcanite after server update, hadnt have that happen before for me

**Comment by Tereneckla** [comment]
Fixed
