### ISSUE TITLE
Pet training bug

### ISSUE THREAD

**Issue by Klvn123** [Atlantiss/NetherwingBugtracker#5029]
Pet keep losing his abilities, this time its resistances.

**Comment by Klvn123** [comment]
https://imgur.com/a/oKcM7R5

**Comment by Easyfraggy** [comment]
Probably need a lot more info.

**Comment by Klvn123** [comment]
Hard to pin point when it happens, pet just loses its trained abilities or in this case only trained resistances. It wasnt visual, because he definetely didnt resist anything at all at curator

**Comment by Zarant** [comment]
It usually happens when you enter/leave an instance or when you switch continents, it doesn't happen 100% of the time though. 
Whenever I corpse run to a instance I have to check if my pet lost his passive abilities. Relogging usually fixes it, but sometimes you have to run back to the hunter trainer and retrain all skills again.

**Comment by DragunovUA** [comment]
Natural Armor working fine, looks like only resistances problem
#3ybtw

**Comment by Zarant** [comment]
Managed to reproduce it 100% of the time on the PTR, pet loses all his passive skills when both you and your pet are dead while zoning into a different map.

https://www.youtube.com/watch?v=0LszPeqHo5k

**Comment by george765** [comment]
it happened for me (also) after ressing dead pet 100% every time during 4 hour raid. loses all resist, cobra reflexes. i guess all skills trained from trainer are temporarily lost. after dismiss>call pet, skills are back

**Comment by Zarant** [comment]
As of revision 3442 this issue still persists, whenever you zone into an instance or switch continents while your pet is dead, your pet loses all passive abilities.
