### ISSUE TITLE
the blank character cant be removed from the guild

### ISSUE THREAD

**Issue by yihu0259** [Atlantiss/NetherwingBugtracker#5031]
[//]: # (Enclose links to things related to the bug using http://wowhead.com or any other TBC database.)
[//]: # (You can use screenshot ingame to visual the issue.)
[//]: # (Write your tickets according to the format:)
[//]: # ([Quest][Azuremyst Isle] Red Snapper - Very Tasty!)
[//]: # ([NPC] Magistrix Erona)
[//]: # ([Spell][Mage] Fireball)
[//]: # ([Npc][Drop] Ghostclaw Lynx)
[//]: # ([Web] Armory doesnt work)
[//]: # (To find server revision type `.server info` command in the game chat.)

**Description**: 
those deleted  characters now shown as a blank in the guild cannot be removed from the guild, the system message is "You must specify a target: /<command> <target's name>:

**Current behaviour**:
the blank character cant be removed from the guild.
this is the screenshot as shown below, sry for cant insert the picture directly.
[https://imgur.com/FUyTvus](url)
[https://imgur.com/P1Moa2J](url)

**Expected behaviour**: 

**Server Revision**: 
2799

**Comment by The14me** [comment]
Suppose to be fixed with the latest Guild rework.
rev 3460
