### ISSUE TITLE
Multi Shot hitting target behind me (breaks Freezing Trap)

### ISSUE THREAD

**Issue by Falathrin** [Atlantiss/NetherwingBugtracker#5032]
[//]: # (Enclose links to things related to the bug using http://wowhead.com or any other TBC database.)
[//]: # (You can use screenshot ingame to visual the issue.)
[//]: # (Write your tickets according to the format:)
[//]: # ([Quest][Azuremyst Isle] Red Snapper - Very Tasty!)
[//]: # ([NPC] Magistrix Erona)
[//]: # ([Spell][Mage] Fireball)
[//]: # ([Npc][Drop] Ghostclaw Lynx)
[//]: # ([Web] Armory doesnt work)
[//]: # (To find server revision type `.server info` command in the game chat.)

**Description**: 
As title suggets, if you have a frozen target behind u and u multi shot, that frozen target will get hit. It should only hit targets infront of you, or on your side, not behind you.
**Current behaviour**:

**Expected behaviour**: 

**Server Revision**:

**Comment by Wolffenstein** [comment]
Fixed in rev 2802.
