### ISSUE TITLE
Arena Drinking/eating broken

### ISSUE THREAD

**Issue by Bzmode** [Atlantiss/NetherwingBugtracker#5034]
how it works: Drinking can tick instantly when you drink in arena.

how it should work: It should take 5 seconds just to start the first tick in arena. so 5 seconds just to start ticking(no mana/life after 5 but after it gets a full tick off after the 5 second delay)

**Comment by Easyfraggy** [comment]
Even in open world I never had eating/drinking tick instantly - Would like some more info.

**Comment by Godmatik** [comment]
Must've been fixed at some point, or perhaps never was a bug.
There is 100% for sure no instant tick in arena.

Can close
