### ISSUE TITLE
[NPC] Prospector Remtravel

### ISSUE THREAD

**Issue by Avatarstate** [Atlantiss/NetherwingBugtracker#504]
[//]: # (Enclose links to things related to the bug using http://wowhead.com or any other TBC database.)
[//]: # (You can use screenshot ingame to visual the issue.)
[//]: # (Write your tickets according to the format:)
[//]: # ([Quest][Azuremyst Isle] Red Snapper - Very Tasty!)
[//]: # ([NPC] Magistrix Erona)
[//]: # ([Spell][Mage] Fireball)
[//]: # ([Npc][Drop] Ghostclaw Lynx)
[//]: # ([Web] Armory doesnt work)

**Description**: 
Prospector Remtravel [2917] in Darkshore only attacks nearby enemies when they directly aggro onto HIM, if a mob aggros onto YOU in range of him, he will ignore that mob entirely.
**Current behaviour**:
Does not attack nearby enemies unless he directly gets initial aggro.
**Expected behaviour**: 
Should attack enemies regardless of who initially aggros the mob
**Server Revision**: 
2050

**Comment by Evolvee** [comment]
https://github.com/Atlantiss/NetherwingBugtracker/issues/267#issuecomment-423945600

**Comment by Tenoutoften** [comment]
Making sure it is easier to find this report:
This issue is about [[NPC]Prospector Remtravel#2917](https://db.excalibur.ws/?npc=2917) and happens during the escort [[Quest]The Absent Minded Prospector#731](https://db.excalibur.ws/?quest=731)

**Comment by The14me** [comment]
moved to https://github.com/Atlantiss/NetherwingBugtracker/issues/3678
