### ISSUE TITLE
Drek's HP is resetting randomly INSIDE his room. (AV)

### ISSUE THREAD

**Issue by Wearetestingstuff** [Atlantiss/NetherwingBugtracker#5040]
**Description**: Drek is randomly resetting HP while he is being tanked INSIDE his room. This has happened now multiple times. Unfortunately no one in the raid was streaming who were on discord with us and we do not have video of the behavior. 

**Current behaviour**: Randomly resetting while INSIDE his room. Not while walking out, but INSIDE his room actively being tanked. This is a drek only issue, we have never seen it happen to Vann. 

**Expected behaviour**: Only reset his hp when he runs outside of his hut.

**Comment by Godmatik** [comment]
Closing - will consolidate all outstanding AV issues into one thread now.
