### ISSUE TITLE
Auchenai Crypts Heroic invisible wall prevents me going further after mid dungeon join

### ISSUE THREAD

**Issue by Mikik3jr** [Atlantiss/NetherwingBugtracker#5042]
[//]: # (Enclose links to things related to the bug using http://wowhead.com or any other TBC database.)
[//]: # (You can use screenshot ingame to visual the issue.)
[//]: # (Write your tickets according to the format:)
[//]: # ([Quest][Azuremyst Isle] Red Snapper - Very Tasty!)
[//]: # ([NPC] Magistrix Erona)
[//]: # ([Spell][Mage] Fireball)
[//]: # ([Npc][Drop] Ghostclaw Lynx)
[//]: # ([Web] Armory doesnt work)
[//]: # (To find server revision type `.server info` command in the game chat.)

**Description**: 
There was a group that killed the first boss in AC HC, but the healer left after that. I came in to heal.

**Current behaviour**:
[When I entered to the dungeon everyone ran forward, but I couldn't, because there was an invisible wall in front of me that prevented me going further.](https://www.youtube.com/watch?v=dm5YbF4oyIg&feature=youtu.be)

**Expected behaviour**: 
Well this should not happen.

**Server Revision**: 
2799

**Comment by Easyfraggy** [comment]
Did you try clearing cache?

Seems like a fantasticly weird bug.

**Comment by teddys** [comment]
same thing happened to me in sethekk halls normal at the beinning (like a week ago)

**Comment by Tereneckla** [comment]
Cannot recreate
