### ISSUE TITLE
[NPC] Demon Hunter Initiate

### ISSUE THREAD

**Issue by totaemoeggerli** [Atlantiss/NetherwingBugtracker#5044]
[//]: # (Enclose links to things related to the bug using http://wowhead.com or any other TBC database.)
[//]: # (You can use screenshot ingame to visual the issue.)
[//]: # (Write your tickets according to the format:)
[//]: # ([Quest][Azuremyst Isle] Red Snapper - Very Tasty!)
[//]: # ([NPC] Magistrix Erona)
[//]: # ([Spell][Mage] Fireball)
[//]: # ([Npc][Drop] Ghostclaw Lynx)
[//]: # ([Web] Armory doesnt work)
[//]: # (To find server revision type `.server info` command in the game chat.)

**Description**: 
[Demon Hunter Initiate](https://www.wowhead.com/npc=21180/demon-hunter-initiate) at Ruins of Karabor

**Current behaviour**:
Demon Hunter Initiate respawn time is 8-9 minutes.
Demon Hunter Supplicants respawn time is 5 minutes.

**Expected behaviour**: 
Demon Hunter Initiate respawn time should be 5 minutes
Can not find evidence that they should have a different respawn time then the other mobs in the area.

**Server Revision**: 2799

**Comment by Easyfraggy** [comment]
https://github.com/Atlantiss/NetherwingBugtracker/issues/4780 This guy says 30-60 minutes - so what is it? 8-9 or 30-60 =)
