### ISSUE TITLE
[Item][Engineering] Gnomish Battle Chicken Doesn't work

### ISSUE THREAD

**Issue by MrJiraiya1** [Atlantiss/NetherwingBugtracker#5045]
[//]: # (Enclose links to things related to the bug using http://wowhead.com or any other TBC database.)
[//]: # (You can use screenshot ingame to visual the issue.)
[//]: # (Write your tickets according to the format:)
[//]: # ([Quest][Azuremyst Isle] Red Snapper - Very Tasty!)
[//]: # ([NPC] Magistrix Erona)
[//]: # ([Spell][Mage] Fireball)
[//]: # ([Npc][Drop] Ghostclaw Lynx)
[//]: # ([Web] Armory doesnt work)
[//]: # (To find server revision type `.server info` command in the game chat.)

**Description**: 
Gnomish Battle Chicken doesn't have "use" option
**Current behaviour**:
![wowscrnshot_021619_172353](https://user-images.githubusercontent.com/47691141/52899931-bf7d3f00-3211-11e9-83e2-149f90dde2c3.jpg)

**Expected behaviour**: 
https://www.wowhead.com/item=10725
**Server Revision**: 
2799

**Comment by Easyfraggy** [comment]
Before going further with this try clearing your cache and trying again.

**Comment by MrJiraiya1** [comment]
Thats worked, Thanks
