### ISSUE TITLE
Cannot re-acquire Argent Dawn Commission trinket from NPC after deleting it. 

### ISSUE THREAD

**Issue by maidros** [Atlantiss/NetherwingBugtracker#5046]
**Description**: 
Cannot re-acquire Argent Dawn Commission trinket from NPC after deleting it. 

**Current behaviour**:
If you delete your Argent Dawn Commission trinket from your bags and then return to the appropriate NPC to acquire a new one, the repeatable quest to get a new one is not offered. 

**Expected behaviour**: 
Any of three NPCs should offer a repeatable quest that allows a person who deleted their Argent Dawn Commission to re-acquire it as often as needed. 

Argent Dawn Commission: 
Item 12846: https://vanillawowdb.com/?item=12846 
 
Three repeatable quests allow players to re-acquire the trinket as often as a player desires: 
Quest 5401: https://vanillawowdb.com/?quest=5401 
NPC 10840: https://vanillawowdb.com/?npc=10840 

Quest 5405: https://vanillawowdb.com/?quest=5405 
NPC 10857: https://vanillawowdb.com/?npc=10857 

Quest 5503: https://vanillawowdb.com/?quest=5503 
NPC 10839: https://vanillawowdb.com/?npc=10839 
 
Proof that this is the intended functionality (aside from retail and all private servers working this way): 
https://wow.gamepedia.com/Argent_Dawn_Commission 
https://github.com/dalaranwow/dalaran-wow/issues/3214 
https://github.com/TrinityCore/TrinityCore/issues/10998 
 
**Server Revision**: 
AtlantissCoreTBC - Server Revision: 2799 [Branch: master, Hash: b8c6feb0c4b2]

**Comment by joceanlab** [comment]
you can re get it from an NPC at lights hope.

**Comment by maidros** [comment]
Thank you for the advice. That is a good work-around. I thought that wasn't until patch 3.1.3 however it worked. I'll leave this bug report up, however, for the developers to correct the three repeatable quests on the NPCs in Western Plaguelands. Cheers.

**Comment by Tenoutoften** [comment]
Should also reward xp the first time you complete the quest:
https://github.com/Atlantiss/NetherwingBugtracker/issues/1725

**Comment by Evolvee** [comment]
so what is the tldr?
there are 3 npcs but only 1 of them enables you to get lost item back?

**Comment by maidros** [comment]
The TL;DR is that while all three offer the **initial** quest to obtain the trinket, **none** of those three offer the repeatable no-xp quest to re-obtain the trinket if you have deleted it. 

The NPC that joceanlab mentioned is not in my list of three NPCs that should offer the "blue question mark" repeatable quest.

**Comment by Tenoutoften** [comment]
And the initial quest rewards no xp

**Comment by Picajzla** [comment]
alternative is to do the stratholme quest where you collect flesh fragments. That gives you a follow up that gives you the trinket that also makes you able to collect scourgestones. Might help someone

**Comment by Evolvee** [comment]
Tbf, I dont see any "proof" from the links you posted, if anything, the TC report confirms our current behavior --> non repeatable quests with possibility to get the item at Miranda
