### ISSUE TITLE
People blinking/rubberbanding in pvp and instances

### ISSUE THREAD

**Issue by FIXTHISFASTERRR** [Atlantiss/NetherwingBugtracker#5047]
[//]: # (Enclose links to things related to the bug using http://wowhead.com or any other TBC database.)
[//]: # (You can use screenshot ingame to visual the issue.)
[//]: # (Write your tickets according to the format:)
[//]: # ([Quest][Azuremyst Isle] Red Snapper - Very Tasty!)
[//]: # ([NPC] Magistrix Erona)
[//]: # ([Spell][Mage] Fireball)
[//]: # ([Npc][Drop] Ghostclaw Lynx)
[//]: # ([Web] Armory doesnt work)
[//]: # (To find server revision type `.server info` command in the game chat.)

**Description**: 
Last week i noticed this getting worse or appearing, ppl start to blink in bgs and movement is not clear
**Current behaviour**:

**Expected behaviour**: 

**Server Revision**:

**Comment by Wolffenstein** [comment]
Duplicate https://github.com/Atlantiss/NetherwingBugtracker/issues/5036.
