### ISSUE TITLE
Visual bug with pet skills.

### ISSUE THREAD

**Issue by dalabu** [Atlantiss/NetherwingBugtracker#5048]
**Description**: Pet bar doesnt show all the skills.

**Current behaviour**: https://imgur.com/a/Yb4YP80
Pet skil bar doesnt show all the skills. Bite missing in screenshot.

**Expected behaviour**: All skills should be visible.

**Server Revision**: 2799

**Comment by Easyfraggy** [comment]
You can drag pet skills onto the pet bar - this looks like an addon / UI issue.
