### ISSUE TITLE
[Shaman] Totems are destroyed by AoE effects

### ISSUE THREAD

**Issue by Brasso** [Atlantiss/NetherwingBugtracker#5049]
[//]: # (Enclose links to things related to the bug using http://wowhead.com or any other TBC database.)
[//]: # (You can use screenshot ingame to visual the issue.)
[//]: # (Write your tickets according to the format:)
[//]: # ([Quest][Azuremyst Isle] Red Snapper - Very Tasty!)
[//]: # ([NPC] Magistrix Erona)
[//]: # ([Spell][Mage] Fireball)
[//]: # ([Npc][Drop] Ghostclaw Lynx)
[//]: # ([Web] Armory doesnt work)
[//]: # (To find server revision type `.server info` command in the game chat.)

**Description**: 
Totems should only be destroyed by direct damage and not AoE spells.
**Current behaviour**:
Currently destroyed by AoE spells, such as warrior whirlwind or cleave, also destroyed by NPC cleave spells.
**Expected behaviour**: 
Immune to AoE and cleave attacks, must be specifically attacked to be destroyed
**Server Revision**: 
2799.

**Comment by Wolffenstein** [comment]
I'd assume it's only Cleave spells and not AoEs?

**Comment by Brasso** [comment]
Haven't noticed them get destroyed spells like rain of fire or blizzard. But whirlwind definitely destroys them in pvp.

**Comment by Easyfraggy** [comment]
You should be able to edit the title.

**Comment by Brasso** [comment]
Yes. But isn't whirlwind considered AoE? Maybe it's only physical spells.

**Comment by Wolffenstein** [comment]
Fixed in rev 2802.
