### ISSUE TITLE
([Spell][Hunter pet] Beast Training) - Pet skills

### ISSUE THREAD

**Issue by Lukeroo** [Atlantiss/NetherwingBugtracker#505]
**Description**: 
I can't teach my pet skills example natural armor, great stamina (For both of them the required lvl is 1)
**Current behaviour**:
I can't teach my pet skills natural armor and great stamina for lvl 1 even if my pet has lvl 9.
**Expected behaviour**: 
I can teach them those skills

It is worth checking the other skills too I saw only these two.

**Comment by mbzz88** [comment]
I assume you have enough training points? Both of those worked for me

**Comment by maronics** [comment]
Worked for me too.

**Comment by Gniddikon** [comment]
Same issue as https://github.com/Atlantiss/NetherwingBugtracker/issues/263

It worked for me as soon as my pet got level 10. So either the text is wrong or the requirement.

**Comment by Lukeroo** [comment]
Yes I have enough training points
