### ISSUE TITLE
Did not get Recipe or Item after completing A Costly Menace in Southshore

### ISSUE THREAD

**Issue by rodeoman17478** [Atlantiss/NetherwingBugtracker#5050]
[//]: # (Enclose links to things related to the bug using http://wowhead.com or any other TBC database.)
[//]: # (You can use screenshot ingame to visual the issue.)
[//]: # (Write your tickets according to the format:)
[//]: # ([Quest][Azuremyst Isle] Red Snapper - Very Tasty!)
[//]: # ([NPC] Magistrix Erona)
[//]: # ([Spell][Mage] Fireball)
[//]: # ([Npc][Drop] Ghostclaw Lynx)
[//]: # ([Web] Armory doesnt work)
[//]: # (To find server revision type `.server info` command in the game chat.)

**Description**: 
I did not receive the Recipe Tasty Lion Steak or the 5 Tasty Lion Steaks for completing the Quest A Costly Menace in Southshore

![no_recipe](https://user-images.githubusercontent.com/47699673/52904279-c0a17280-31f7-11e9-9f68-c1e16e5067af.png)

**Comment by Easyfraggy** [comment]
Can others confirm / deny this?

**Comment by rodeoman17478** [comment]
Is this directed at me or someone else? There is a screenshot right after I completed the quest you can see the info in the chat window and you can see that the items are not in my inventory. I can also show you that I have not learned the recipe also.

**Comment by Manaci** [comment]
Dead issue
