### ISSUE TITLE
Quest Items In Bank Makes "Clamlette Surprise" quest uncompletable

### ISSUE THREAD

**Issue by MelEnt** [Atlantiss/NetherwingBugtracker#5052]
[//]: # (Enclose links to things related to the bug using http://wowhead.com or any other TBC database.)
[//]: # (You can use screenshot ingame to visual the issue.)
[//]: # (Write your tickets according to the format:)
[//]: # ([Quest][Azuremyst Isle] Red Snapper - Very Tasty!)
[//]: # ([NPC] Magistrix Erona)
[//]: # ([Spell][Mage] Fireball)
[//]: # ([Npc][Drop] Ghostclaw Lynx)
[//]: # ([Web] Armory doesnt work)
[//]: # (To find server revision type `.server info` command in the game chat.)

**Description**: 

We all know how quest items in bank cannot be used to complete quests, but this is a consequence of that logic;
For this case we will use the quest Clamlette Surprise (Artisan cooking quest)
1. Attain every ingredient
2. Store any abundant required ingredient in bank. (1 Alterac Swiss in bank, while still having necessary amount in inventory)
3. Observe how the quest treated as not completable.

**Server Revision**: 
2799

**Comment by Tereneckla** [comment]
Fixed
