### ISSUE TITLE
Scare Beast (+ Intimidating Shout?) Not Breaking on Damage

### ISSUE THREAD

**Issue by jasonbourne109** [Atlantiss/NetherwingBugtracker#5053]
**Description:** Scare Beast and Intimidating Shout have an extremely high threshold for breaking on damage. Many others have made a similar report about Intimidating Shout but none of the others have mentioned Scare Beast. Notably, these are also the only two physical fear effects (i.e. not able to be dispelled by priests) in PvP.

**Current behaviour**: I have never actually seen Scare Beast break from damage. I just watched myself go from 100% to 0% health over the course of Scare Beast's 10 second duration and the fear did not break. This was in Bear Form with extremely high HP. There are a few hunters abusing this against druids in PvP.

I noticed the same thing with Intimidating Shout. I'm not 100% sure if Intimidating Shout is bugged, but others have reported it too so I think it's worth mentioning. It could have something to do with the fact that these are both physical fears. The magical fears (Psychic Scream, etc) definitely break on damage.

**Expected behaviour**: Scare Beast and Intimidating Shout should end early when the target takes any significant amount of damage.

**Server Revision**: Latest

**Comment by Tenoutoften** [comment]
https://github.com/Atlantiss/NetherwingBugtracker/issues/4539
