### ISSUE TITLE
Guild Log Broken

### ISSUE THREAD

**Issue by bbcgit** [Atlantiss/NetherwingBugtracker#5054]
The guild log is broken and not displaying any recent information, it does however still show the information from 21 days ago and beyond;

![guildlog](https://user-images.githubusercontent.com/42920284/52912732-2ef43c80-32ad-11e9-8902-bd69d993f023.png)

Roughly around that time (22/23 days ago) the following change was made, maybe it broke it further?

> 25/01/2019 [Core/Guild]:
> - Moved guild event log saving to separate transaction to avoid preventing key functionalities from working properly when a duplicate occurs

Current behaviour: The guild log is either not displaying or not saving information from recent changes to the guild.

Expected behaviour: The guild log should show all information from recent changes to the guild.

Server Revision: 2809

**Comment by sifiuocz** [comment]
As of 17th June this is still broken after the supposed fix in rev 2963.

**Comment by Tereneckla** [comment]
fixed
