### ISSUE TITLE
[SSC][Loot]Trash only drop the same two epic items.

### ISSUE THREAD

**Issue by Tenoutoften** [Atlantiss/NetherwingBugtracker#5055]
**Description**: 
A report was made about restricted trash loot epics dropping in Karazhan. It's likely the same in SSC: Our guild has only gotten Boots of Courage Unending & Pendant of the Perilous. I contacted two other SSC raiding guilds that has also killed a significant amount of trash, and they too have only gotten these boots and necklace.
https://github.com/Atlantiss/NetherwingBugtracker/issues/5020

**Current behaviour**:
Only Boots of Courage Unending & Pendant of the Perilous alongside of Vortexes drop

**Expected behaviour**: 
Lacks:
Spyglass of the Hidden Fleet
Totem of the Maelstrom
Wildfury Greatstaff
Serpentshrine Shuriken

**Server Revision**: 
2809

**Comment by DragunovUA** [comment]
batched lootlable

**Comment by Easyfraggy** [comment]
Dragunov keep your trolling on reddit.

**Comment by Wolffenstein** [comment]
Fixed in rev 2820.
