### ISSUE TITLE
[Movement] (Female) Draenei characters get stuck in animations

### ISSUE THREAD

**Issue by sandreid** [Atlantiss/NetherwingBugtracker#5056]
**Description**: 
(Female) Draenei characters get stuck in animations all the time. 

**Current behaviour**:
(Female) Draenei characters get stuck in animations all the time. 

**Expected behaviour**: 
(Female) Draenei characters shouldn't get stuck in animations all the time. 

Not this:
https://youtu.be/XAKAh5RB2KI

**Server Revision**: 
2809

**Comment by narayagh** [comment]
During 68 levels I've never enountered this issue.

**Comment by Wolffenstein** [comment]
I don't know if anyone else experienced this, looks like a client issue.

**Comment by Evolvee** [comment]
do other ppl see you stuck as well? or its just you

**Comment by sandreid** [comment]
Just myself. I have a guildy having that issue too though. Who is also playing a female draenei (Oulous).

**Comment by sandreid** [comment]
This is far from a new issue btw. I thought it was something that happened to everyone, so didnt think about reporting it. Have been like this for at least a few weeks.

**Comment by Wolffenstein** [comment]
Is your client modified in any way?

**Comment by sandreid** [comment]
No. Standard 2.4.3 client. Have used it on several TBC private servers, including Hellfire 2, Vengeance, Gummys, Feenix, and Excalibur

**Comment by knasen88** [comment]
it's not just draenei, it happens to probably everyone. it happened a lot more the first 2 dark weeks of the server though.

**Comment by Wolffenstein** [comment]
Can't do anything about it without reproduction steps.

**Comment by The14me** [comment]
Cant repo in 3441.
