### ISSUE TITLE
Recipe: Sporeling Snack is missing

### ISSUE THREAD

**Issue by moork** [Atlantiss/NetherwingBugtracker#5058]
[Recipe: Sporeling Snack](https://wow.gamepedia.com/Recipe:_Sporeling_Snack) is missing from Mycah Sporeggar Quartermaster

Server revision: 2809

**Comment by Evolvee** [comment]
not present until patch 2.1.0

**Comment by Kaziczek** [comment]
According to https://www.wowhead.com/item=27656/sporeling-snack
it was added in patch 2.0.1 so should be present right now

**Comment by Evolvee** [comment]
wowhead shows patch info incorrectly, use wowwiki or archives
