### ISSUE TITLE
Karazhan Back Enterance is Closed after 1 day passed.

### ISSUE THREAD

**Issue by Mikik3jr** [Atlantiss/NetherwingBugtracker#5059]
[//]: # (Enclose links to things related to the bug using http://wowhead.com or any other TBC database.)
[//]: # (You can use screenshot ingame to visual the issue.)
[//]: # (Write your tickets according to the format:)
[//]: # ([Quest][Azuremyst Isle] Red Snapper - Very Tasty!)
[//]: # ([NPC] Magistrix Erona)
[//]: # ([Spell][Mage] Fireball)
[//]: # ([Npc][Drop] Ghostclaw Lynx)
[//]: # ([Web] Armory doesnt work)
[//]: # (To find server revision type `.server info` command in the game chat.)

**Description**: 
On 2019.02.16 Saturday we killed every bosses in kara (except Prince and Nigthbane) and we used the back enterance multiple times.

**Current behaviour**:
The next day on Sunday the backdoor is closed and can't be opened.
![image](https://user-images.githubusercontent.com/43505031/52917425-9cbf5900-32eb-11e9-9934-ee9d5a1db2e4.png)

**Expected behaviour**: 
It should be still open imo.

**Server Revision**: 
2809

**Comment by Tenoutoften** [comment]
This issue probably has something to do with the server restarting, similar to the issue that has happened to Vashj Bridge

**Comment by The14me** [comment]
Rev.3483 Tested after a day+server restart=Door still works fine and open without a problem.
