### ISSUE TITLE
[Core][Mage][Water Elemental] Water elemental can't attack CC'd targets (sheep anyways)

### ISSUE THREAD

**Issue by killablink** [Atlantiss/NetherwingBugtracker#5060]
**Description**: Water elemental doesn't finish his cast on a sheeped target.
https://gfycat.com/ElementaryRadiantHerculesbeetle

**Current behaviour**:

**Expected behaviour**: Should be able to shoot a sheeped target

**Server Revision**: 2809

**Comment by Easyfraggy** [comment]
https://github.com/Atlantiss/NetherwingBugtracker/issues/456
