### ISSUE TITLE
[SSC][Vashj] Bridge that leads to Vashj is always bugged.

### ISSUE THREAD

**Issue by killablink** [Atlantiss/NetherwingBugtracker#5061]
**Description**: The bridge that leads to Vashj always gets bugged after opening it ( have to page a GM to manually open for people), and when it soft resets, the next time we go there it gets bugged again.

Every week we have to page GMs to open the gate, it would be nice to have it fixed asap

**Current behaviour**:

**Expected behaviour**: Working bridge to Vashj

**Server Revision**: 2806

**Comment by Wolffenstein** [comment]
It's getting fixed in rev 2816.
