### ISSUE TITLE
[Gruul's Lair][Spell] Olm the Summoner - Dark Decay

### ISSUE THREAD

**Issue by Firroth** [Atlantiss/NetherwingBugtracker#5063]
[NPC] https://www.wowhead.com/npc=18834/olm-the-summoner
[Spell] https://www.wowhead.com/spell=33129/dark-decay

**Current behaviour**:
He stacks his DoT way to randomly, which makes it trivial and 1 tank is enough for him for the entire fight.
During entire fight he only managed to stack 3 DoT's on our feral druid in 1-2min time. When it should be around 8 stacks by then.

**Expected behaviour**: 
He should stack his DoT every 8-9s, just before the DoT expires, which makes this add require 2 tanks taunting him off each other every few stacks, or enslaved felhunter tanking him, who can dispel his DoT's from himself.

![screenshot_1](https://user-images.githubusercontent.com/43505196/52922125-d3fb2d80-331e-11e9-96fd-35eb012322eb.png)
![screenshot_2](https://user-images.githubusercontent.com/43505196/52922126-d493c400-331e-11e9-88df-d7c54f68b2f6.png)

0:31 
https://www.youtube.com/watch?v=4302sPx4k-U

**Server Revision**: 
2809

**Comment by Tereneckla** [comment]
Fixed
