### ISSUE TITLE
Was not able to turin in SSC attune

### ISSUE THREAD

**Issue by Redpandaw** [Atlantiss/NetherwingBugtracker#5065]
[//]: # (Enclose links to things related to the bug using http://wowhead.com or any other TBC database.)
[//]: # (You can use screenshot ingame to visual the issue.)
[//]: # (Write your tickets according to the format:)
[//]: # ([Quest][Azuremyst Isle] Red Snapper - Very Tasty!)
[//]: # ([NPC] Magistrix Erona)
[//]: # ([Spell][Mage] Fireball)
[//]: # ([Npc][Drop] Ghostclaw Lynx)
[//]: # ([Web] Armory doesnt work)
[//]: # (To find server revision type `.server info` command in the game chat.)

Quest: http://db.hellfire-tbc.com/?quest=10901
**Description**: Hello, i was doing SSC attune [The Cudgel of Kar'desh], i had both quest items but was not able to turn in quest, tried relog, deleted cache but nothing helped

**Current behaviour**: I had both quest items in my bags but for some reason i was not able to turin in quest 

**Expected behaviour**: When i have both quest items in bags i should be able to turin in quest, so "Continue" button should be red, not grey. I will attach screenshot
![wowscrnshot_021719_225444](https://user-images.githubusercontent.com/47742215/52947342-764efb80-3387-11e9-93e6-b55eaf1b815a.jpg)

**Server Revision**: 2809 (Branch: master, Hash: 492fbc972c8a)

**Comment by bbcgit** [comment]
Did you try dropping and retaking the quest?

**Comment by Easyfraggy** [comment]
Did you try relogging and clearing cache?

**Comment by Easyfraggy** [comment]
Theres a bug when you have had items in the bank that sometimes you have to relog before you can turn in. Thats why im asking if you tried relogging.

**Comment by Wolffenstein** [comment]
The issue is a duplicate. Ask a GM for completion temporarily.
