### ISSUE TITLE
[Quest][Tooga's Quest] immidiatelly freezes the game

### ISSUE THREAD

**Issue by Abrosan** [Atlantiss/NetherwingBugtracker#5066]
[//]: # (Enclose links to things related to the bug using http://wowhead.com or any other TBC database.)
[//]: # (You can use screenshot ingame to visual the issue.)
[//]: # (Write your tickets according to the format:)
[//]: # ([Quest][Azuremyst Isle] Red Snapper - Very Tasty!)
[//]: # ([NPC] Magistrix Erona)
[//]: # ([Spell][Mage] Fireball)
[//]: # ([Npc][Drop] Ghostclaw Lynx)
[//]: # ([Web] Armory doesnt work)
[//]: # (To find server revision type `.server info` command in the game chat.)

**Description**: After accepting the quest my game froze and had to be closed.

**Current behaviour**: When I get into the game, on the character that i took the quest, game immidiately freezes. When I log onto other characters game runs fine.

**Expected behaviour**: Would continue playing the game without having to close it.

**Server Revision**: 2817

**Comment by Evolvee** [comment]
disable quest helper or other addons
