### ISSUE TITLE
[Karazhan][Spell] Nightbane - Bellowing Roar (Fear)

### ISSUE THREAD

**Issue by Firroth** [Atlantiss/NetherwingBugtracker#5068]
[NPC] https://wowwiki.fandom.com/wiki/Nightbane_(boss)
[Spell] https://www.wowhead.com/spell=36922/bellowing-roar

**Current behaviour**:
It has post 2.0 cast time of 2.5s.

**Expected behaviour**: 
It should have 1.5s cast time, before later patches.

1:11
https://www.youtube.com/watch?v=_iCONpSPTos

Here you can see him starting cast it on 1:11 and end it on 1:12.

**Server Revision**: 
2809

**Comment by Easyfraggy** [comment]
This was also reported back on closed beta just never changed :(

**Comment by Wolffenstein** [comment]
Fixed in rev 2822.
