### ISSUE TITLE
[SSC] [Boss] [Lady Vashj] Tainted Core

### ISSUE THREAD

**Issue by Drayo** [Atlantiss/NetherwingBugtracker#5069]
[//]: # (Enclose links to things related to the bug using http://wowhead.com or any other TBC database.)
[//]: # (You can use screenshot ingame to visual the issue.)
[//]: # (Write your tickets according to the format:)
[//]: # ([Quest][Azuremyst Isle] Red Snapper - Very Tasty!)
[//]: # ([NPC] Magistrix Erona)
[//]: # ([Spell][Mage] Fireball)
[//]: # ([Npc][Drop] Ghostclaw Lynx)
[//]: # ([Web] Armory doesnt work)
[//]: # (To find server revision type `.server info` command in the game chat.)

**Current behaviour**: Shapeshifting seems to remove the root, other stuff might also remove it.

**Expected behaviour**: The root should not be removed by anything.

**Server Revision**:  2808

**Comment by Wolffenstein** [comment]
Rev 2815.
