### ISSUE TITLE
[Ashenvale] Wrathtail Sorceress AI

### ISSUE THREAD

**Issue by Azalen** [Atlantiss/NetherwingBugtracker#507]
**Description**: 
Wrathtail Sorceress has Frost Nova and Frostbolt as available spells.

Entry ID = 3717
https://classicdb.ch/?npc=3717

**Current behaviour**:
Mob is using Frost Nova, runs away 5 yards to be out of melee range, casts a frost bolt and runs back into melee range to make a melee attack.

**Expected behaviour**: 
Mob should probably use Frost Nova and keep casting Frost Bolt after the first one and let the player move into melee range again. Imo only a Counter Spell should make her move into melee range again.
Maybe a CD on Frostbolt is not allowing this behaviour?

**Server Revision**: 
[2045]

**Comment by Evolvee** [comment]
@Wolffenstein probably water problem... the mobs script is perfectly fine

**Comment by The14me** [comment]
Confirm!

**Comment by Tereneckla** [comment]
Fixed
