### ISSUE TITLE
Paranoia doesn't work or stealth levels are bugged

### ISSUE THREAD

**Issue by fantom8** [Atlantiss/NetherwingBugtracker#5073]
**Description**: 
Paranoia is not functioning.

**Current behaviour**:
I have had a night elf who is 12 levels below me shadowmeld/stealth in my face 3 times and be undetectable until I'm literally right on top of him, while I had paranoia up the entire time.

**Expected behaviour**: 
Considering the ~42 difference in stealth level he should have been visible from a huge distance, Please investigate.

**Server Revision**: 
2809

**Comment by Easyfraggy** [comment]
Stealth levels do seem very bugged. Remember for example in hinterlands even when 6 levels above never being able to see any of the wolves before they attacked me.

**Comment by Tereneckla** [comment]
Fixed
