### ISSUE TITLE
Bride of the Embalmer

### ISSUE THREAD

**Issue by shanold** [Atlantiss/NetherwingBugtracker#5074]
[//]: # (Enclose links to things related to the bug using http://wowhead.com or any other TBC database.)
[//]: # (You can use screenshot ingame to visual the issue.)
[//]: # (Write your tickets according to the format:)
[//]: # ([Quest][Azuremyst Isle] Red Snapper - Very Tasty!)
[//]: # ([NPC] Magistrix Erona)
[//]: # ([Spell][Mage] Fireball)
[//]: # ([Npc][Drop] Ghostclaw Lynx)
[//]: # ([Web] Armory doesnt work)
[//]: # (To find server revision type `.server info` command in the game chat.)

**Description**: 
Bride of the Embalmer quest isn't working
**Current behaviour**: when you go to her grave behind the hermit its sparkling but you cannot interact with it.

**Expected behaviour**: It should summon a mob to kill to get the heart of the embalmer

**Server Revision**:

**Comment by Easyfraggy** [comment]
Can someone confirm/deny - kind of curious this hasn't been reported before with thousands leveling!

**Comment by Jalapan** [comment]
not working, grave not interractable

**Comment by shanold** [comment]
Quest worked for me now

**Comment by Jalapan** [comment]
its very few ppl who actually do whole questline (this is last q) and maybe it works only 1 time per server reset? yesterday it was not completeable, and there were 2-3 other players around the grave trying to complete it aswell. if required video can be produced.

**Comment by Wolffenstein** [comment]
Fixed in rev 2826.
