### ISSUE TITLE
Mage Armor and Demon Armor not magic effects

### ISSUE THREAD

**Issue by Hidehugo** [Atlantiss/NetherwingBugtracker#5075]
**Description**: Mage and warlock armors not dispellable even though it was a feature of 2.4.3 changes making mages almost unkillable for melee in pvp. Either make it dispellable in arena or enjoy your mage gladiators with no competition (https://wowwiki.fandom.com/wiki/Patch_2.4.3)

**Current behaviour**: Mage armors and warlock armors are not dispellable

**Expected behaviour**: Mage armor and Warlock armor are dispellable

**Server Revision**:

**Comment by Evolvee** [comment]
![image](https://user-images.githubusercontent.com/1942409/52980859-775e4800-33dc-11e9-8aa0-3f3e45fa4a5c.png)
?

**Comment by Hidehugo** [comment]
they are not dispellable on this server

**Comment by Brasso** [comment]
And they shouldn't be, because player mechanics/talents are 2.4.3 here, not 2.0.x.

**Comment by Hidehugo** [comment]
I mean the PvE environment doesn't get affected by it but the PvP is basically the weirdest experience since these two armors have a too high impact on low gear/earlier seasons where people do not have the resilience to outlast ice lance spam. Isn't this server trying to get the experience as blizzlike as possible? If you implement changes from 2.4.3 why not implement the healing=>spellpower conversion too. pretty twofaced mentality

**Comment by Easyfraggy** [comment]
PvP mechanics are all 2.4.3.

**Comment by Hidehugo** [comment]
So you really think the healing to spellpower conversion is no pvp mechanic?

**Comment by Easyfraggy** [comment]
Technically it's an item stat.

**Comment by Hidehugo** [comment]
Well i guess backpaddling mages get their chance on free points for now. It's just completely distorting for the arena experience since you cannot adapt from old pvp arena videos where mages and warlocks are viable targets with offensive dispel. Now you have to fight against constant random freezes into 2k icelances and warlocks can just enjoy their life as SL/SL tanks with a 20% healing received bonus in arena whereas back then offensive dispel was a clear way to pressure and counter these classes. And still people succeeded in arena without the armors being undispellable so i cannot understand the clear non-interest of balancing/adapting arena fights on netherwing
