### ISSUE TITLE
Paladin talent Reckoning

### ISSUE THREAD

**Issue by shanold** [Atlantiss/NetherwingBugtracker#5076]
[//]: # (Enclose links to things related to the bug using http://wowhead.com or any other TBC database.)
[//]: # (You can use screenshot ingame to visual the issue.)
[//]: # (Write your tickets according to the format:)
[//]: # ([Quest][Azuremyst Isle] Red Snapper - Very Tasty!)
[//]: # ([NPC] Magistrix Erona)
[//]: # ([Spell][Mage] Fireball)
[//]: # ([Npc][Drop] Ghostclaw Lynx)
[//]: # ([Web] Armory doesnt work)
[//]: # (To find server revision type `.server info` command in the game chat.)

**Description**: the talent reckoning isn't working after it procs the effect doesn't happen

**Current behaviour**:Reckoning activates and you loose stacks during attacks but no additional damage is done

**Expected behaviour**: After Reckoning activates your next 4 attacks within 8 seconds should cause another attack, This attack should work the same as a auto attack with any auto attack procs having a chance to happen as well 

**Server Revision**: 2816 [Bratch:master, Hash:b324dab210cd]

**Comment by Easyfraggy** [comment]
Can someone confirm/deny?

**Comment by totalscrubking** [comment]
yep its broken!

**Comment by Easyfraggy** [comment]
https://github.com/Atlantiss/NetherwingBugtracker/issues/4939 Duplicate just not gonna close them untill this is fixed - posting # for later reference.

**Comment by Wolffenstein** [comment]
Fixed in rev 2817.
