### ISSUE TITLE
Ring enchants issues

### ISSUE THREAD

**Issue by Redpandaw** [Atlantiss/NetherwingBugtracker#5077]
[//]: # (Enclose links to things related to the bug using http://wowhead.com or any other TBC database.)
[//]: # (You can use screenshot ingame to visual the issue.)
[//]: # (Write your tickets according to the format:)
[//]: # ([Quest][Azuremyst Isle] Red Snapper - Very Tasty!)
[//]: # ([NPC] Magistrix Erona)
[//]: # ([Spell][Mage] Fireball)
[//]: # ([Npc][Drop] Ghostclaw Lynx)
[//]: # ([Web] Armory doesnt work)
[//]: # (To find server revision type `.server info` command in the game chat.)

**Description**: On this video https://www.youtube.com/watch?v=BNl3UxCgZjc i show that one of healing enchant (http://db.hellfire-tbc.com/?item=22537) doesnt work: my both rings and enchants with this talent http://db.hellfire-tbc.com/?spell=31841 in summ should give like 122 bonus healing, but it gives 104. I tried relog and deleting cache, it doesnt help, so i've checked some topics here and decided to put 12 spell damage and healing (http://db.hellfire-tbc.com/?item=22536) on another ring since both healing enchants doesnt stack, but after death the only healing enchant which is left stops working, so i have to re equip it to make it work, proof: https://www.youtube.com/watch?v=zLxlQ2NX-9A
What is going on?:c

**Current behaviour**: 

**Expected behaviour**: Both healing enchants should stack and both of them should work after death, so we dont have to re equip it every time.

**Server Revision**: 2816 [Branch: master, Hash: b324dab210cd]

**Comment by Redpandaw** [comment]
Fixed second video link

**Comment by Easyfraggy** [comment]
https://github.com/Atlantiss/NetherwingBugtracker/issues/2779
