### ISSUE TITLE
[NPC] Crag Stalker

### ISSUE THREAD

**Issue by Aphroditus-Netherwing** [Atlantiss/NetherwingBugtracker#5078]
[//]: # (Enclose links to things related to the bug using http://wowhead.com or any other TBC database.)
[//]: # (You can use screenshot ingame to visual the issue.)
[//]: # (Write your tickets according to the format:)
[//]: # ([Quest][Azuremyst Isle] Red Snapper - Very Tasty!)
[//]: # ([NPC] Magistrix Erona)
[//]: # ([Spell][Mage] Fireball)
[//]: # ([Npc][Drop] Ghostclaw Lynx)
[//]: # ([Web] Armory doesnt work)
[//]: # (To find server revision type `.server info` command in the game chat.)

**Description**: Currently Crag Stalker's can attack you in stealth if you do not move or have a buff that deals damage when they attack you.

**Current behaviour**: Currently Crag Stalker's can attack you in stealth if you do not move or have a buff that deals damage when they attack you.

**Expected behaviour**: They should auto remove stealth upon hitting you even without damaging them first or moving.

**Server Revision**: 2816

**Comment by Easyfraggy** [comment]
I noticed this on several stealthed mobs when leveling. Seems like a global issue.

**Comment by Evolvee** [comment]
cant reproduce

**Comment by The14me** [comment]
Rev.3460 still an issue.It's hard to reproduce.

**Comment by Wolffenstein** [comment]
Fixed in rev 3470.
