### ISSUE TITLE
[QUEST] [Hellfire Peninsula]  [A Burden of Souls] 

### ISSUE THREAD

**Issue by skami1** [Atlantiss/NetherwingBugtracker#5079]
[//]: # (Enclose links to things related to the bug using http://wowhead.com or any other TBC database.)
[//]: # (You can use screenshot ingame to visual the issue.)
[//]: # (Write your tickets according to the format:)
[//]: # ([Quest][Azuremyst Isle] Red Snapper - Very Tasty!)
[//]: # ([NPC] Magistrix Erona)
[//]: # ([Spell][Mage] Fireball)
[//]: # ([Npc][Drop] Ghostclaw Lynx)
[//]: # ([Web] Armory doesnt work)
[//]: # (To find server revision type `.server info` command in the game chat.)

**Description**: The NPC Shattered Hand (ALL) is not giving credit for the quest.

**Current behaviour**: Not even one "Shattered Hand" mobs give credit for this quest.

**Expected behaviour**: All "Shattered Hand" mobs should give credit for this quest.

**Server Revision**: 2816

**Comment by Easyfraggy** [comment]
Sounds like addon/cache issue. Quest works fine. Which orcs are you killing? I did this quest 2 days ago.

**Comment by skami1** [comment]
Bug started yesterday, probably after Server Update or something. I killed all of kind "Shattered Hand" mobs at any location Thallanar and HH. Did it solo, party, with pet, without pet, and nothing. I am frost mage. Many people report issue in "World Channel" ingame.

**Comment by Easyfraggy** [comment]
Okay very strange! Skip it for now - not going to be fixed today! TK release. Apologies!

**Comment by skami1** [comment]
Thank you! Have a nice day!

**Comment by Umyron** [comment]
Still not working as of 2/20/19

**Comment by czarecoo** [comment]
pls fix 21.02

**Comment by Wolffenstein** [comment]
Fixed in rev 2826.

**Comment by skami1** [comment]
I tried 40 min ago. Didnt work!

**Comment by omonoia91** [comment]
Killed many of them, no credit. Does not work atm!

**Comment by czarecoo** [comment]
> Fixed in rev 2826.

server is on 2825 right now guys

**Comment by skami1** [comment]
Yea yea, i just sayed for other, if they wanna try :-)

**Comment by shinmadam** [comment]
Still this quest does not work.
fast fix plz

**Comment by Easyfraggy** [comment]
Server is not updated yet because next update is huge - 1-2 more days and it will be fixed.
