### ISSUE TITLE
Children's Week and quests during this event. [World Event] [NPC] [Quests]

### ISSUE THREAD

**Issue by Neophrone** [Atlantiss/NetherwingBugtracker#508]
[//]: # (Enclose links to things related to the bug using http://wowhead.com or any other TBC database.)
[//]: # (You can use screenshot ingame to visual the issue.)
[//]: # (Write your tickets according to the format:)
[//]: # ([Quest][Azuremyst Isle] Red Snapper - Very Tasty!)
[//]: # ([NPC] Magistrix Erona)
[//]: # ([Spell][Mage] Fireball)
[//]: # ([Npc][Drop] Ghostclaw Lynx)
[//]: # ([Web] Armory doesnt work)

**Description**: World Event ID [201]. Wowhead said this event should going in April/May https://www.wowhead.com/childrens-week#comments. But starting quest [Children's Week] is available right now. Also next quests after this one [The Bough of the Eternals] [The Stonewrought Dam] [Spooky Lighthouse] you can complete right after you took it (without doing the job). The following quest [You Scream, I Scream...] impossible to do because quest item [Tigule and Foror's Strawberry Ice Cream] sells by [Emmithue Smails] unobtainable. [Emmithue Smails] appears in Stormwind during Children's Week.

**Current behaviour**: Available quests linked to Children's Week, some quests [The Bough of the Eternals] [The Stonewrought Dam] [Spooky Lighthouse] - you can complete right after you took it (without doing the job).

**Expected behaviour**: Children's Week event should going in April/May, and any quests, NPCs linked to this event should be unobtainable.

**Server Revision**:

**Comment by Neophrone** [comment]
Where I can find server revision?

**Comment by Mikik3jr** [comment]
Write .server info to the chat and it will show that.

**Comment by wtRCH** [comment]
Refered to https://github.com/Atlantiss/NetherwingBugtracker/issues/146
