### ISSUE TITLE
[Hunter][Talent] Rapid killing does not proc from shots kill

### ISSUE THREAD

**Issue by Tokretsim** [Atlantiss/NetherwingBugtracker#5081]
[//]: # (Enclose links to things related to the bug using http://wowhead.com or any other TBC database.)
[//]: # (You can use screenshot ingame to visual the issue.)
[//]: # (Write your tickets according to the format:)
[//]: # ([Quest][Azuremyst Isle] Red Snapper - Very Tasty!)
[//]: # ([NPC] Magistrix Erona)
[//]: # ([Spell][Mage] Fireball)
[//]: # ([Npc][Drop] Ghostclaw Lynx)
[//]: # ([Web] Armory doesnt work)
[//]: # (To find server revision type `.server info` command in the game chat.)

**Description**: 
3rd tier talent in Marksmanship talent tree Rapid Killing: Reduce the cooldown of your Rapid Fire ability by 2 min. In addition, after killing an opponent that yields experience or honor, your next Aimed Shot, Arcane Shot, or Auto Shot causes 20% additional damage. Lasts 20 sec.
**Current behaviour**:
Rapid Killing doesn't apply if hunter killed an opponent by one of the shots (Arcane, Aimed, Auto), but still applies if hunter killed an opponent by melee attacks, sting, trap or pet.
![combat log mix](https://user-images.githubusercontent.com/38424067/53013793-9e0d9480-3457-11e9-8335-09a880d49556.jpg)
**Expected behaviour**: 
Rapid Killing should apply whenever hunter kills an opponent that yields experience or honor, no matter how hunter did it.
**Server Revision**: 
2817 [Branch: master, Hash: 648760a645fc]

**Comment by teddys** [comment]
same issue with [Victory rush](https://db.excalibur.ws/?spell=34428)

**Comment by Easyfraggy** [comment]
Can confirm Victory rush has same issue.

**Comment by NatsumeLily** [comment]
Bump. Major bug to hunter talents

**Comment by Manaci** [comment]
Fixed
