### ISSUE TITLE
[Hunter]3-2 macro rotation only shoots Steady Shots

### ISSUE THREAD

**Issue by natoxz** [Atlantiss/NetherwingBugtracker#5084]
# ([Spell][Hunter] Steady Shot)
# ([Spell][Hunter] Auto Shot)

**Description**: 
after the recent Auto Shot adjustments by Wolf on Sunday 17.02.19 3-2 rotation only shoots Steady Shots now with following macro that worked before:

#showtooltip Steady Shot
/console Sound_EnableSFX 0
/script UIErrorsFrame:Hide()
/cast !Auto Shot
/cast [exists,target=pettarget] Kill Command
/cast Steady Shot

**Current behaviour**:
3-2 macro only shoots Steady Shots

**Expected behaviour**: 
Auto Shots should fire in between

**Server Revision**: 
2817

**Comment by Zarant** [comment]
This particular bug is related to issues #2339 and #3259

**Comment by Easyfraggy** [comment]
Will be worked on soon. In general hunter auto shot and steady is broken in many ways.

**Comment by DaidalosNW** [comment]
I can confirm that the 3:2 macro isnt working as intended.

/cast !Auto Shot
/cast [target=pettarget, exists] Kill command
/cast Steady Shot

No Auto shots in between the Steady shots.

**Comment by knasen88** [comment]
please kill the 1button macro already, hunters is braindead as is.
