### ISSUE TITLE
[Visual Glitch] [NPC] female nagas

### ISSUE THREAD

**Issue by H2714** [Atlantiss/NetherwingBugtracker#5086]
[//]: # (Enclose links to things related to the bug using http://wowhead.com or any other TBC database.)
[//]: # (You can use screenshot ingame to visual the issue.)
[//]: # (Write your tickets according to the format:)
[//]: # ([Quest][Azuremyst Isle] Red Snapper - Very Tasty!)
[//]: # ([NPC] Magistrix Erona)
[//]: # ([Spell][Mage] Fireball)
[//]: # ([Npc][Drop] Ghostclaw Lynx)
[//]: # ([Web] Armory doesnt work)
[//]: # (To find server revision type `.server info` command in the game chat.)

**Description**: 
Female nagas (all colors) glitches when near the edge of water. Their fins light up and/or disappear partly/completely.

**Current behaviour**:
![wowscrnshot_021919_184530](https://user-images.githubusercontent.com/46264740/53035821-9a3d3a80-3476-11e9-8fb5-19c7b3c85709.jpg)
![wowscrnshot_021919_180532](https://user-images.githubusercontent.com/46264740/53035961-f1430f80-3476-11e9-9f4f-5620081475ff.jpg)

**Server Revision**: 
2817

**Comment by Easyfraggy** [comment]
Models are client side - likely client issue?
