### ISSUE TITLE
Several Shadowpine Oracle's#16343 not parolling

### ISSUE THREAD

**Issue by Tenoutoften** [Atlantiss/NetherwingBugtracker#509]
**Description**: 
Location for this place is around the Amani Catacombs ~58, 25

A Shadowpine Oracle#16343(https://db.excalibur.ws/?npc=16343) is not patrolling, the specific NPC I talk about is this one: https://i.gyazo.com/3ef38f8fd8a808ab9268a510ba35fe8d.jpg it can be seen patrolling to the right here: https://youtu.be/Yd4y1gpRRaY?t=58 video is from cataclysm but I am convinced it was patrolling on TBC as well.

Currently it is awkwardly standing very close to another Shadowpine Oracle#16343 as seen in the picture provided.

Inside the temple/cave is another Shadowpine Oracle#16343(https://db.excalibur.ws/?npc=16343) not patrolling but just hanging around https://i.gyazo.com/d9bcd328e49620193413547375c063c3.jpg can be seen patrolling here: https://youtu.be/Yd4y1gpRRaY?t=134

The third Shadowpine Oracle#16343(https://db.excalibur.ws/?npc=16343) not patrolling can be seen here: https://gyazo.com/458fefc8e037c80ff58bd4e9307b15a9 and as you can see on the video it is missing from it's spot, most likely because it is patrolling the room behind it(can be seen here https://youtu.be/Yd4y1gpRRaY?t=148), it can also been here https://youtu.be/45tFZB-2jwY?t=1

A fourth and potentially fifth Shadowpine Oracle#16343(https://db.excalibur.ws/?npc=16343) at the road to the back entrance at 67, 27. At this road there is two different Shadowpine Oracle's#16343(https://db.excalibur.ws/?npc=16343) stacked on top of each other.(This was edited at server revision 2072)

**Expected behaviour**: 
I expect the first Shadowpine Oracle to patrol up and down the road and around the cauldron.

I expect the second Shadowpine Oracle to patrol around the room and the hallway inside the chamber.

I also expect a third Shadowpine Oracle to be patrolling this place

Most likely one or two Shadowpine Oracle's#16343(https://db.excalibur.ws/?npc=16343) are suppose to patrol the back entrance road.(This was edited at server revision 2072)

**Server Revision**: 
2050 & 2072

**Comment by Tenoutoften** [comment]
In addition it looks like these are suppose to run rather fast when they are fleeing judging by wowhead comments: https://www.wowhead.com/npc=16343/shadowpine-oracle#comments

**Comment by aresbrutus** [comment]
Fixed the patrols, the running away faster seems to be bad perspective of people as videos show normal running speed. Please comment if you got further proof so I can re-open.
