### ISSUE TITLE
[Spell][Proc][Item] Mana-Etched 4 Piece Bonus not Procing

### ISSUE THREAD

**Issue by Aptitude09** [Atlantiss/NetherwingBugtracker#5090]
[//]: # (Enclose links to things related to the bug using http://wowhead.com or any other TBC database.)
[//]: # (You can use screenshot ingame to visual the issue.)
[//]: # (Write your tickets according to the format:)
[//]: # ([Quest][Azuremyst Isle] Red Snapper - Very Tasty!)
[//]: # ([NPC] Magistrix Erona)
[//]: # ([Spell][Mage] Fireball)
[//]: # ([Npc][Drop] Ghostclaw Lynx)
[//]: # ([Web] Armory doesnt work)
[//]: # (To find server revision type `.server info` command in the game chat.)

**Description**: I have recently acquired the 4 piece bonus for the Mana-Etched Regalia, which states "Your harmful spells have a chance to grant you 110 spell power for 15 sec." I have been killing countless mobs and have yet to see it proc once. Meanwhile, my Shiffar's Nexus-Horn, with a similar proc is happening just about every other pull. I feel like the proc chance on the Mana-Etched Regalia may be off or bugged somehow to not be procing. 

**Current behaviour**: Mana-Etched 4 Piece Bonus is not Procing when I cast spells on mobs. Should have x% chance to proc for each harmful spell I land on a target. Where I am not sure what the x value is, but believe there is something wrong with this proc's behaviour as I have yet to see it proc once. 
 
**Expected behaviour**: The Mana-Etched 4 Piece Bonus should have "x"% chance to proc when I land a harmful spell. The value of X should be easy to find here, but I do not know what that value is. 

**Server Revision**:

**Comment by ircfelix** [comment]
How long did you try? On ptr the proc rate was very low, like 1-2% or so

**Comment by Aptitude09** [comment]
> 
> 
> How long did you try? On ptr the proc rate was very low, like 1-2% or so

I have killed over 100 mobs with multiple spell casts on each mob so for it to not have proceed yet seems like its less than 1-2% But yeah i have still yet to see it proc. Sadly I did not try the ptr so you might be right and i've just gotten really unlucky and this set bonus is definitely not worth it if its this rare of a proc. More likely I think the proc value is off. Thanks for looking into it @Wolffenstein @ircfelix

**Comment by Aptitude09** [comment]
Update. After running Karazhan last night I can confirm it never proced once for me the yet.

**Comment by Aptitude09** [comment]
![wowscrnshot_022119_142422](https://user-images.githubusercontent.com/16050969/53205873-71d34e80-35e4-11e9-8646-67c1019419ce.jpg)

**Comment by Wolffenstein** [comment]
![image](https://user-images.githubusercontent.com/1576644/53228587-f0ca9480-3681-11e9-95a5-d0ba93da8d6f.png)
It works fine (tested), it just has only 2% proc chance.

**Comment by Aptitude09** [comment]
hmm literially havent seen it proc once @Wolffenstein can it be a char bug?

**Comment by ircfelix** [comment]
Maybe it does not appear when another proc like shiffar's nexus Horn is up like it is the case for the tirisfal regalia 4/5 set bonus? There is a report about it.

**Comment by Aptitude09** [comment]
Ok it did finally proc for me while i was aoeing like 50 mobs 💯

**Comment by zhuk90** [comment]
Not working for me and
