### ISSUE TITLE
[SPELL][MECHANIC] No "Dazed" immunity while having absorb on

### ISSUE THREAD

**Issue by Nuy** [Atlantiss/NetherwingBugtracker#5091]
[//]: # (Enclose links to things related to the bug using http://wowhead.com or any other TBC database.)
[//]: # (You can use screenshot ingame to visual the issue.)
[//]: # (Write your tickets according to the format:)
[//]: # ([Quest][Azuremyst Isle] Red Snapper - Very Tasty!)
[//]: # ([NPC] Magistrix Erona)
[//]: # ([Spell][Mage] Fireball)
[//]: # ([Npc][Drop] Ghostclaw Lynx)
[//]: # ([Web] Armory doesnt work)
[//]: # (To find server revision type `.server info` command in the game chat.)

**Description**: You can get "Dazed" even if you have absorb on. You should be immune to mob "Dazed" effect if the damage was completely absorbed. 

https://www.wowhead.com/spell=1604/dazed
https://wowwiki.fandom.com/wiki/Daze

"It also seems that daze debuff can't be applied by a mob if you are "Immune" (such as with a Paladin Divine Shield or Mage Ice Block), if you "Resist" the hit, or if all the damage from the hit is Absorbed."

**Current behaviour**: You can get "Dazed" even if you have absorb on.

**Expected behaviour**: You should be immune to "Dazed" effect if the damage is completely absorbed.

**Server Revision**: 2819

**Comment by Easyfraggy** [comment]
Can confirm you should not get dazed by NPC's while having absorb on. I haven't tested on server though someone else will have to confirm that this is indeed happening on NW atm!

Slows ofc should get applied through absorb just talking about NPC Daze mechanic.

**Comment by Wolffenstein** [comment]
Please retest after revision 2822.
