### ISSUE TITLE
The missing diplomat Mikhail

### ISSUE THREAD

**Issue by shanold** [Atlantiss/NetherwingBugtracker#5092]
[//]: # (Enclose links to things related to the bug using http://wowhead.com or any other TBC database.)
[//]: # (You can use screenshot ingame to visual the issue.)
[//]: # (Write your tickets according to the format:)
[//]: # ([Quest][Azuremyst Isle] Red Snapper - Very Tasty!)
[//]: # ([NPC] Magistrix Erona)
[//]: # ([Spell][Mage] Fireball)
[//]: # ([Npc][Drop] Ghostclaw Lynx)
[//]: # ([Web] Armory doesnt work)
[//]: # (To find server revision type `.server info` command in the game chat.)

**Description**: Mikhail isn't triggering as a quest objective Just the bartender 

**Current behaviour**:Mikhail just acts normal during the part of the quest that tells you to talk with him.  During typing this he "fixed" himself and I was able to complete the quest  He said I'm glad the commotion has died down some around here. The last thing this place needs is another brawl. I'm not sure if this is intended there wasn't any fighting going on I could see. 

**Expected behaviour**: You should be able to turn in the quest and get the next part of the quest chain.

**Server Revision**: 2819

**Comment by Evolvee** [comment]
its because someone was doing the "tapoke kill" quest meanwhile
