### ISSUE TITLE
[Quest] A dip in the Moonwell

### ISSUE THREAD

**Issue by Aphroditus-Netherwing** [Atlantiss/NetherwingBugtracker#5095]
[//]: # (Enclose links to things related to the bug using http://wowhead.com or any other TBC database.)
[//]: # (You can use screenshot ingame to visual the issue.)
[//]: # (Write your tickets according to the format:)
[//]: # ([Quest][Azuremyst Isle] Red Snapper - Very Tasty!)
[//]: # ([NPC] Magistrix Erona)
[//]: # ([Spell][Mage] Fireball)
[//]: # ([Npc][Drop] Ghostclaw Lynx)
[//]: # ([Web] Armory doesnt work)
[//]: # (To find server revision type `.server info` command in the game chat.)

**Description**: Use the Robotron Control while standing near the Concealed Command Console hidden in a small cluster of bushes on the rim of the needle closest to Thalanaar to take command of a Robotron 3000. Pilot the robot to the western edge of Thousand Needles where the Alliance outpost of Thalanaar is located. Use the robot to collect a sample of the moonwell's water and return it to Wizlo Bearingshiner at Whitereach Post.

**Current behaviour**: Upon collecting the sample of the moonwell's water you are granted credit for it but are unable to hand the quest back in to Wizlo Bearingshiner at Whitereach Post there is no option to do so. https://i.imgur.com/Nlo0kci.png

**Expected behaviour**: Upon completeing the quest and returning to Wizlo Bearingshiner he should offer you the option to hand in the quest.

**Server Revision**: 
2819

**Comment by Drayo** [comment]
Have you tried deleting your cache, this sounds like it could be cause by that.

**Comment by Aphroditus-Netherwing** [comment]
@Drayo My cache is cleared upon launch using custom .bat file to delete it before launching wow.exe

**Comment by Aphroditus-Netherwing** [comment]
[!image](https://i.imgur.com/Uwx6Qbs.jpg) to show it's not a cache related issue cache was deleted 11:03 screen take 2 mins later after running back to npc as can be seen by system clock in lower right.

**Comment by Drayo** [comment]
Oh, I believe you. ;P

I just thought it might be a good thing to try in case you have not done it. 
Seems like it either broke somehow or you are super unlucky and it only went wrong for you.

You could try and retake the quest, see if that helps, but aside from that there is nothing much that can be done, I think GM's can complete quests for you but not force the hand in, not 100% sure though.

**Comment by Tereneckla** [comment]
Fixed
