### ISSUE TITLE
[Loot][Arcatraz Sentinel][Loottable]

### ISSUE THREAD

**Issue by gabbat** [Atlantiss/NetherwingBugtracker#5098]
Pattern: Arcanoweave Bracers

I am suspecting that this item can not be dropped on Netherwing. However I have no proof of that as I can not check your Database. But:

Not a single Tailor on the Server knows this Pattern (been spamming trade and world for days).
The Sentinels (Robots) in Arcatraz that are supposed to drop it, dont drop anything at all, they appear to have no loottable or are not able to be looted I think. Not a single of those Robots could be looted by anyone in any of my arcatraz runs, which feels weird.
However, this is all speculation so I can not create a proper bug report on that.

According to Discord Moderator Ceago the Sentinels appear to have a normal loottable, so it might be the mobs state preventing it from beeing looted, as it is "dead" before you engage it. Duno, something for the devs to figure out.
If anyone has that pattern dropped feel free to comment (with a screenshot) and disprove me, that would just mean that I am unlucky but this is not a bug per se.

**Comment by Ceago** [comment]
Information from me about the loot table is just from me checking wowhead to see what patch it was added in and the loot list did show normal drops.  If this was different in patch 2.0 that could be the case but it should still at least drop the recipe.

**Comment by Easyfraggy** [comment]
Wowhead is not a good source for patch implementations of items unless you have comments on the item about it from that patch.

**Comment by gabbat** [comment]
All the research from players side has been done. I have asked for weeks in /trade and /world if anyone has this pattern - I did not get a single reply. As it stands, the item is currently not in the game due to Sentinels not dropping items. 
Only devs can investigate further here

**Comment by Ceago** [comment]
There is a heavily downvoted comment on WoWhead from 2.0.6 

By ashanoir (185 – 1·2) on 2007/02/12 (Patch 2.0.6)
I can make this on Icecrown server, Alliance side.

**Comment by gabbat** [comment]
what kind of research do you need? there is still not a single tailor on the server that has the pattern. The sentinels can simply not drop loot, even tho there is proof of ppl having that pattern in 2.0.6 (see above), so it should be able to drop. Can we please fix this already?

**Comment by Drayo** [comment]
Can kinda (subjectively) confirm this, I know no one with this pattern and the sentinels don't seem to drop any loot.

**Comment by gabbat** [comment]
still not fixed. pattern does not exist on this server. please fix sentiel loot

**Comment by gabbat** [comment]
sentinels still dont drop anything. Is there anything we can help u with?

**Comment by Evolvee** [comment]
their loot table is fine, the core script prevents them from being lootable rn

PM wolf ^^

**Comment by Wolffenstein** [comment]
Fixed
