### ISSUE TITLE
resurrect now, not working when arriving at corpse 

### ISSUE THREAD

**Issue by jaded75** [Atlantiss/NetherwingBugtracker#5099]
[//]: # (Enclose links to things related to the bug using http://wowhead.com or any other TBC database.)
[//]: # (You can use screenshot ingame to visual the issue.)
[//]: # (Write your tickets according to the format:)
[//]: # ([Quest][Azuremyst Isle] Red Snapper - Very Tasty!)
[//]: # ([NPC] Magistrix Erona)
[//]: # ([Spell][Mage] Fireball)
[//]: # ([Npc][Drop] Ghostclaw Lynx)
[//]: # ([Web] Armory doesnt work)
[//]: # (To find server revision type `.server info` command in the game chat.)

**Description**: 
When I arrive at my body from my corpse run I have to log out and then log back in to be able to press resurrect now, if I dont do it i can click it a hundred times and it doesn't do anything even if I move in and out of the zone
**Current behaviour**:
I have to relog to be able to press the resurrect now button about 1 out of every 5 times I die, it happens more often when another player will kill me
**Expected behaviour**: 
The resurrect now button will work when I arrive at my corpse from my corpse run from the spirit healer
**Server Revision**:

**Comment by Jalapan** [comment]
I have had this several times, for me it works if i spam the ressurect button, but it can take many seconds.

**Comment by Easyfraggy** [comment]
I have a theory that the timer on client is shorter than the timer server side not allowing you to res untill the server side timer is up. It seems to be mostly when it's 2minute+ timer.

**Comment by DragunovUA** [comment]
batched respawn, its fine

**Comment by Dimbleglim** [comment]
This problem still exists and in battlegrounds can prevent ressurecting entirely.

**Comment by The14me** [comment]
Rev .3460 cant reproduce.

**Comment by Godmatik** [comment]
Never heard of this issue, never seen this issue on Netherwing.
Probably fixed at some point, can close
