### ISSUE TITLE
[Quest][Azuremyst Isle] Tree's Company

### ISSUE THREAD

**Issue by kudryashov-n** [Atlantiss/NetherwingBugtracker#51]
[//]: # (Enclose links to things related to the bug using http://wowhead.com or any other TBC database.)
[//]: # (You can use screenshot ingame to visual the issue.)
[//]: # (Write your tickets according to the format:)
[//]: # ([Quest][Azuremyst Isle] Red Snapper - Very Tasty!)
[//]: # ([NPC] Magistrix Erona)
[//]: # ([Spell][Mage] Fireball)
[//]: # ([Npc][Drop] Ghostclaw Lynx)
[//]: # ([Web] Armory doesnt work)

**Description**: 
Cant complete the quest.
**Current behaviour**:
Cannot finish the quest, staying on the tree form doesnt pop 1/1 goal.
**Expected behaviour**: 
It should finish the quest.
**Server Revision**:

**Comment by Peglaa** [comment]
Works fine for me
