### ISSUE TITLE
[Ashenvale] Wrathtail Priestess AI

### ISSUE THREAD

**Issue by Azalen** [Atlantiss/NetherwingBugtracker#510]
**Current behaviour**:
Mob ID = 3944
https://classicdb.ch/?npc=3944#abilities

Mob is not using any spells.

**Expected behaviour**: 
Mob - as a priest category mob with mana - should at least use heal ability. No idea how to proof smth like that though.

**Server Revision**: 
[2045]

**Comment by Evolvee** [comment]
the heal is only for other units then her so if you fight 2 mobs, she will heal the other one, she cant heal self with it

**Comment by Evolvee** [comment]
she also sleeps you but only if there is more than 1 target on her threat list

**Comment by Evolvee** [comment]
@Wolffenstein For some reason the NPC doesnt cast heal on other NPCs despite having type "AI decision" and flag "wolf ai cant cast on self" ...

**Comment by Evolvee** [comment]
nevermind, just retarded unit_flag

will be fixed in next revision
