### ISSUE TITLE
[Spell] [Rogue] Using Stealth occasionally cancels eating Food (and Drinks)

### ISSUE THREAD

**Issue by someotherplayer** [Atlantiss/NetherwingBugtracker#5100]
Going into stealth sometimes cancels eating food (and drinks).

This happens to me all the time while leveling. I start eating food (i do see the food buff ticking for like half a second) and go into stealth very fast (almost instantly after clicking the food).
At least 1/10 times it cancels the eating process leaving my character just sitting on the ground and being in stealth.

**Comment by someotherplayer** [comment]
It just happend to me again going into stealth 2 secs after i started eating. So its not related to immediate stealthing.

**Comment by someotherplayer** [comment]
I was able to capture it

https://www.youtube.com/watch?v=Ehkj2-mT6k0

**Comment by Easyfraggy** [comment]
I mean isn't it cus you're doing it in the wrong order? Stealth then eat works fine or?

**Comment by someotherplayer** [comment]
If you stealth first and then start to eat it will break stealth (as it should).
A rogue should definitely be able to eat first and then go into stealth without it canceling the food buff.

As I said this doesn't happen every time. I could not reliably trigger it on purpose so far.

**Comment by Easyfraggy** [comment]
Would be nice with some evidence on this from retail so we don't have to fix and refix later if it turns out to be the opposite order that is correct.

**Comment by someotherplayer** [comment]
Thats a very specific thing to find an old video of

I have never encountered this on any private server ever be it vanilla, tbc...
Its so inconsistent that it can only be a bug. I can eat and instantly stealth most of the time without problems but sometimes for no reason it just cancels it (see video).

That can not be right unless there is a really good reason for it (which i don't see).

**Comment by Zarant** [comment]
You can find videos of resto druids using shadowmeld + drink, this is particularly difficult to spot because usually both buffs occur on the same spell batch, but if you look carefully you can see that the food/drink buff always precedes shadowmeld.

https://youtu.be/FAz6E6W4T-I?t=193
https://youtu.be/FAz6E6W4T-I?t=330

**Comment by someotherplayer** [comment]
https://youtu.be/14sFYHIKpX0?t=252

This dude also does it with shadowmeld but I am checking videos for rogues doing it with stealth right now.
It has definitely always worked even in later expansions and again it is crazy incsonsistent on Netherwing at the moment.

**Comment by someotherplayer** [comment]
Just writing that here it is
https://youtu.be/1K6LZ7OP6cQ?t=753

**Comment by someotherplayer** [comment]
And this is what i mean by inconsistent
https://www.youtube.com/watch?v=u6CBFpKeYII

**Comment by someotherplayer** [comment]
Also being in stealth and clicking the food sometimes cancels the foodbuff.
This is so annoying..... please fix.

**Comment by Mercymurv** [comment]
This doesn't need research. Eating/drinking 100% should be okay immediately followed by stealth, to continue recovering health. I played rogue and witnessed night elf druids through every expansion and only on this server has this glitch happened.

**Comment by Zsorrov** [comment]
Can confirm this still happens most of the time when I sit to eat and then hit stealth on my Rogue.

I feel like this used to work on Netherwing? This is a tactic I have always used when playing rogues and would have noticed it right away if it didn't work.

**Comment by Wolffenstein** [comment]
Please retest in rev 2889.
