### ISSUE TITLE
Extra combo points/rage in cat/bear form without primal fury talent

### ISSUE THREAD

**Issue by Cornfed14** [Atlantiss/NetherwingBugtracker#5101]
[//]: # (Enclose links to things related to the bug using http://wowhead.com or any other TBC database.)
[//]: # (You can use screenshot ingame to visual the issue.)
[//]: # (Write your tickets according to the format:)
[//]: # ([Quest][Azuremyst Isle] Red Snapper - Very Tasty!)
[//]: # ([NPC] Magistrix Erona)
[//]: # ([Spell][Mage] Fireball)
[//]: # ([Npc][Drop] Ghostclaw Lynx)
[//]: # ([Web] Armory doesnt work)
[//]: # (To find server revision type `.server info` command in the game chat.)

**Description**: I'm getting extra combo points with swipe, rake. etc. when I crit with them without the primal fury talent

**Current behaviour**: Extra combo point with crits without primal fury talent

**Expected behaviour**: no extra combo points with crits without 1/2 or 2/2 primal fury talent

**Server Revision**: 
current server as of 2/20/19

**Comment by Easyfraggy** [comment]
Probably need a lot more information - this also happening to other druids?

**Comment by Cornfed14** [comment]
> Probably need a lot more information - this also happening to other druids?

I'll try and get a video, recording software is bugging on me atm. I only started to notice this yesterday possibly because I maxed out the prerequisite of the talent? I've also had the talent maxed previously before a respec, but that was at level 30.

**Comment by Cornfed14** [comment]
okay, strange update: It won't wont even let me put points into primal fury. I put one talent point into it and it resets after I log...wtf lol
