### ISSUE TITLE
Necklace gone: Quest reward deleted!

### ISSUE THREAD

**Issue by bc003** [Atlantiss/NetherwingBugtracker#5103]
[//]: # (Enclose links to things related to the bug using http://wowhead.com or any other TBC database.)
[//]: # (You can use screenshot ingame to visual the issue.)
[//]: # (Write your tickets according to the format:)
[//]: # ([Quest][Azuremyst Isle] Red Snapper - Very Tasty!)
[//]: # ([NPC] Magistrix Erona)
[//]: # ([Spell][Mage] Fireball)
[//]: # ([Npc][Drop] Ghostclaw Lynx)
[//]: # ([Web] Armory doesnt work)
[//]: # (To find server revision type `.server info` command in the game chat.)

**Description**: In-game name "Cardab"

Hey my bis healing necklace from the quest https://tbc-twinhead.twinstar.cz/?quest=10323 got removed from my inventory. This happened two weeks ago when I was farming prebis and haven't reported on github until now. I messaged a GM on discord as soon as possible and he told me to make a bug report on here. I waited until now because I have been really busy IRL and farming with a new guild getting ready for raiding Karazhan and I just made my github account because I've never posted anything on here before. 

This necklace is best in slot for healers and I'm wondering if the item can be restored seeing as though it came from a quest reward. Any other information you need I can provide. 

**Current behaviour**:

**Expected behaviour**: 

**Server Revision**:

**Comment by bc003** [comment]
The item that I had that got removed: 
https://tbc-twinhead.twinstar.cz/?item=30377

**Comment by Easyfraggy** [comment]
It's a bit late now - but maybe a GM can help you - you'd probably have to contact Narilrave personally on discord. Anyone else experience something similar?

**Comment by The14me** [comment]
9.9/10 cases...player delete the item by mistake.
Can be closed.
