### ISSUE TITLE
Rep from killing Warp Splinter in Botanica

### ISSUE THREAD

**Issue by cathabv** [Atlantiss/NetherwingBugtracker#5104]
**Description**: Killing Warp Splinter in normal Botanica don't give any rep. Just killed him today and there was no rep given in my log. I received 1 rep from adds and nothing from boss. 

Edit: According to Wowwiki each boss should reward 120 rep.

**Comment by Easyfraggy** [comment]
Can someone confirm/deny?

**Comment by Evolvee** [comment]
work fine for me 
![image](https://user-images.githubusercontent.com/1942409/53268960-db885100-36e7-11e9-8da4-6392dafdbad0.png)
