### ISSUE TITLE
Escape Artist (gnome racial) does not remove druids roots 

### ISSUE THREAD

**Issue by weedzyx** [Atlantiss/NetherwingBugtracker#5105]
Hello,
escape arist - gnome racial, seems to be bugged. Sometimes happend, that after using it, does not remove druids root. Not always, but sometimes.

Please look on it, its very important racial.

Thank you in advance.

**Comment by Easyfraggy** [comment]
It's about the druid talent that reduces the chance that their spells are dispelled. Possibly shouldn't affect Escape artist. If someone has some info on this - please share.

**Comment by weedzyx** [comment]
Yes but then It should affect also medallion of the aliance ? Which is the same mechanism. I dont think so ..

**Comment by weedzyx** [comment]
Also rogues have talent for resist dispells. But never happend that i cannot remove cripling poison. 

This is not attempt to dispel, this should remove any movement reduction.

**Comment by killablink** [comment]
Escape artist is subject to dispel resistance. PVP trinket is something different as it always removes stuns/slows/ccs from you

**Comment by Zarant** [comment]
http://www.arenajunkies.com/topic/11968-escape-artist-failed/
Post from March 2008 (patch 2.4) indicating that escape artist should be affected by dispel resistance.

**Comment by Easyfraggy** [comment]
Seems like this issue is invalid then?
