### ISSUE TITLE
[NPC] [Quest] Skywing stucking

### ISSUE THREAD

**Issue by veekk** [Atlantiss/NetherwingBugtracker#5106]
**Description**:  [Skywing](https://db.excalibur.ws/?npc=22424) got stucked and patrolling small area if you accept quest in combat with mob around Skywing. He will start to fight this mob and do nothing after fight is finished. Also quest can't be abandoned or something, only server restart will help.

**Server Revision**: 2825

**Comment by Easyfraggy** [comment]
Can someone confirm this and add a video or something - not really clear what happens from this report.

**Comment by veekk** [comment]
Can't add video but have additional description and maybe route how to reproduce that:
Happened again in Nagrand, [quest](http://db.hellfire-tbc.com/?quest=9868), so that's mean that might be general escort quest. 
Steps:
1. Start event
2. Someone from not ur party running away from mobs through escort route
3. Hit one of those mobs and make escorted attack him
4. Mobs evaded 'cause not ur party member run away
5. Mobs comes to spawn spot, but event got stuck, and escorted guy just patrolling small area around him
6. Go to this pack, kill mobs
7. Event continued as usual
Hope I explain it well

**Comment by Evolvee** [comment]
its the regular core issue that has been present since 1999 --- npcs that have low respawn timer in creature table do not respawn randomly

**Comment by Evolvee** [comment]
lf a video on how to reproduce this

**Comment by Godmatik** [comment]
Duplicate #8873
