### ISSUE TITLE
Pvp healing offsets unavailable 

### ISSUE THREAD

**Issue by Danand838** [Atlantiss/NetherwingBugtracker#5107]
**Description**: S1 Pvp Healing offset gear unavailable for purchase on horde side

**Current behaviour**: Items not showing at the vendor

**Expected behaviour**: Items showing at vendor and are available for purchase

**Comment by teddys** [comment]
http://db.hellfire-tbc.com/?item=31594
http://db.hellfire-tbc.com/?item=31595
http://db.hellfire-tbc.com/?item=31598

**Comment by s2nratio** [comment]
I think the healing offset epics were added at a later patch, but correct me if i am wrong. stumbled upon this as well and i remember that they were not in game at 2.0.1 patch.

**Comment by Danand838** [comment]
If they plan on not adding them, then I suggest you remove and reimburse the ppl that alrdy have them to make it fair
