### ISSUE TITLE
[RAID] [SSC] Lurker Below fishing time 

### ISSUE THREAD

**Issue by Dollywog** [Atlantiss/NetherwingBugtracker#5108]
**Description**: I can see from a previous report that Lurker fishing behaviour was bugged and only needed one cast to fish him.  This appears to have been "fixed" in a previous revision. 

**Current behaviour**: Currently even with 6 people all fishing, we had fishing wait time of up to 12 minutes before spawning the boss.  What value has this fish rate been set too and where has it been sourced from?
This resulted in over 45 minutes of wasted raid time on just fishing the boss, lost 10 minute buffs. 
Also, players can allegedly fish Lurker even with level 1 fishing, any guide will tell you it should be fishing 250+

See: https://m.twitch.tv/videos/383896614
Around 1hr 44min for pull attempts

**Expected behaviour**:  Lurker should take at most 2-3 minutes for 3-4 people casting for him.  Typical pulls should result in him being fished in <1 minute. 

**Server Revision**:  If the current fishing spawn rate is intentional then could the spawn value please be sourced or at least justified.  Is the change Blizzlike? (does not appear to be so), if it is Blizzlike, what does it add to the game except wasting raiders time who just want to enjoy the content of the server. 

I would argue this is similar situation to the custom decision to not add aggro tables to the Adviser corpses on Kael'Thas as was the case in 2.0, as it is just an unnecessary bad game design mechanic.

**Comment by Easyfraggy** [comment]
This is how it was in the very first version - it is there merely for authenticity - that said I also think it's served it's purpose - maybe time to make it little less retarded!

**Comment by Wolffenstein** [comment]
"To summon him you must fish for him in the strange pool. While a very unique summoning mechanism for a boss, it can be annoying when it takes 10 minutes to get him to summon, and then the next time you get him on the second cast."

**Comment by Dollywog** [comment]
But Wolfenstein you coding it this way from that one comment is a little bit unreasonable; the commenter may have been exaggerating the time they spent waiting and right now it feels like the average wait time is 7-8 minutes all in the name of "authenticity".   What authenticity is it adding other than being an obnoxious delay, everyone knows you have to fish Lurker out of the pool in 2019 ; surely we don't have to do it everytime

**Comment by Brasso** [comment]
I'm going to have to agree with Dolly here, and I'm actually surprised Easy agrees as well. I'm all for authenticity, but we are clearly past blizzlike in raids, it's more of a qualified attempt at recreating raid experience at this point.

This detail serves no purpose. Fishing for over 12 minutes, buffs running out, trash respawning and people losing patience, only serves as an annoyance. I think the chance to fish him up should be drastically increased, but not first attempt as it was before, it's a unique mechanic that should be preserved but without making it tedious.

[In Nihilum second world kill](https://www.youtube.com/watch?v=eZJNTmHA7Cg) it took them less than 3 minutes to fish him up with 5 people, going by their buffs, this is a good time to aim for an average imo.

**Comment by Anduyon** [comment]
What I've noticed from observing the Pool itself is that it doesn't actually seem to be all that wide. Contrary to what the swirling water would suggest you only get the tooltip "Strange Pool" in a 5 yard radius in the very center. This might have something to do with the time you spend fishing with 5+ people. We can get it in 3-4 minutes with 2 people only fishing the very center.
