### ISSUE TITLE
[Dungeon] Scarlet Monastery - Cathedral door closes instantly

### ISSUE THREAD

**Issue by ghost** [Atlantiss/NetherwingBugtracker#5109]
**Description**: 
The door for the cathedral (midway through the dungeon, approx) is closed instantly with a single rightclick, which causes people to close it all the damn time accidentally in combat.
Not gamebreaking but definitely annoying and definitely not intended

**Current behaviour**:
Door closes instantly, people accidentally close it every pull

**Expected behaviour**: 
Like a 3 second timer

**Server Revision**: 
2825

**Comment by Tenoutoften** [comment]
This is a global issue with all doors on this server, both inside and outside of a dungeon.

**Comment by Godmatik** [comment]
Was fixed when the global timer was added to all doors - can be closed
