### ISSUE TITLE
Healthstone not sharing cd with health potion

### ISSUE THREAD

**Issue by Therev2018** [Atlantiss/NetherwingBugtracker#511]
Warlock healthstone and health potion aren't sharing CD.

Healthstone and health potions should share cds

**Server Revision**: 
2050

**Comment by Gniddikon** [comment]
Are you sure they should? Any source on this?

**Comment by Rickybobby90** [comment]
I don't believe this is a bug, separate CD's on gems and pots.

**Comment by Therev2018** [comment]
![image](https://user-images.githubusercontent.com/43570970/46009829-915b5f00-c0b8-11e8-8715-56f13ac6f7b8.png)
yep seperate cd, my bad!
