### ISSUE TITLE
[Spell] [Druid] Feral Charge causing permanent toggle walking

### ISSUE THREAD

**Issue by Imperator522** [Atlantiss/NetherwingBugtracker#5110]
[//]: # (Enclose links to things related to the bug using http://wowhead.com or any other TBC database.)
[//]: # (You can use screenshot ingame to visual the issue.)
[//]: # (Write your tickets according to the format:)
[//]: # ([Quest][Azuremyst Isle] Red Snapper - Very Tasty!)
[//]: # ([NPC] Magistrix Erona)
[//]: # ([Spell][Mage] Fireball)
[//]: # ([Npc][Drop] Ghostclaw Lynx)
[//]: # ([Web] Armory doesnt work)
[//]: # (To find server revision type `.server info` command in the game chat.)

**Description**: After using Feral Charge, the character is then permanently toggled to walk. 

**Current behaviour**: Doesn't happen on all casts; however, it randomly occurs and the druid mobility is reduced to only walking, even though no movement impairing debuffs are active. Relogging removes the effect of permanent walking, key binds will not toggle out of it.

**Expected behaviour**: Standard run speed should still be maintained after using Feral Charge.

**Server Revision**:

**Comment by Tenoutoften** [comment]
https://github.com/Atlantiss/NetherwingBugtracker/issues/5115

**Comment by Easyfraggy** [comment]
So this has nothing to do with feral charge?

**Comment by Imperator522** [comment]
I only witnessed perma-daze effect after using it. Can test later

**Comment by Valmere** [comment]
been trying to replicate this but can't, closest I can get is starting in walk mode and charging which forces you back to run mode

rev 2856

**Comment by Wolffenstein** [comment]
Should be fixed
