### ISSUE TITLE
Master of elixirs

### ISSUE THREAD

**Issue by jorsba** [Atlantiss/NetherwingBugtracker#5111]
[//]: # (Enclose links to things related to the bug using http://wowhead.com or any other TBC database.)
[//]: # (You can use screenshot ingame to visual the issue.)
[//]: # (Write your tickets according to the format:)
[//]: # ([Quest][Shattrat] Master of elixirs)
[//]: # ([NPC] Magistrix Erona)
[//]: # ([Spell][Mage] Fireball)
[//]: # ([Npc][Drop] Ghostclaw Lynx)
[//]: # ([Web] Armory doesnt work)
[//]: # (To find server revision type `.server info` command in the game chat.)

**Can not turn in the quest, even though i have materials in my back bags. Tried removing the quest after relogging several times, now lost all the materials for it.**: 

**Wont acept quest turn in**:

**Should appear as yellow question mark**: 

**Server Revision**: 
![issue](https://user-images.githubusercontent.com/47868338/53197560-22604300-3623-11e9-8825-25810d07e37d.jpg)

**Comment by Easyfraggy** [comment]
Anyone else experience this?

**Comment by jorsba** [comment]
Is it possible to get assistance on this one - or do I have to do the whole thing all over again?

**Comment by Wolffenstein** [comment]
Ask a GM for completion, this bug is known.
