### ISSUE TITLE
[quest] Arelion's Journal

### ISSUE THREAD

**Issue by sifiuocz** [Atlantiss/NetherwingBugtracker#5112]
**Description**: 
The container that is supposed to have the quest item in it is empty. It should have Arelion's Knapsack (http://db.excalibur.ws/?item=31955) in it. 
![wowscrnshot_022119_205444](https://user-images.githubusercontent.com/13140968/53197956-94348e80-361b-11e9-9cb8-9a1d31bbc8bf.jpg)

**Current behaviour**:

**Expected behaviour**: 

**Server Revision**: 
2825

**Comment by Easyfraggy** [comment]
Probably just didn't respawn yet? I looted the journal from it a few days ago.

Alternatively you can also get the journal from the slimes - just kill them instead.

**Comment by Modzel93** [comment]
Same issue here
![wowscrnshot_022219_092529](https://user-images.githubusercontent.com/5479431/53229200-e7422c00-3683-11e9-84e4-e2039de55869.jpg)

**Comment by Modzel93** [comment]
Journal dropped from slimes around this area
