### ISSUE TITLE
[RAID] [SSC] Morogrim skipping Quake damage

### ISSUE THREAD

**Issue by Gedlund** [Atlantiss/NetherwingBugtracker#5113]
[//]: # (Enclose links to things related to the bug using http://wowhead.com or any other TBC database.)
[//]: # (You can use screenshot ingame to visual the issue.)
[//]: # (Write your tickets according to the format:)
[//]: # ([Quest][Azuremyst Isle] Red Snapper - Very Tasty!)
[//]: # ([NPC] Magistrix Erona)
[//]: # ([Spell][Mage] Fireball)
[//]: # ([Npc][Drop] Ghostclaw Lynx)
[//]: # ([Web] Armory doesnt work)
[//]: # (To find server revision type `.server info` command in the game chat.)

**Description**: 
Morogrim Tidewalker sometimes skips out on dealing damage to the raid when he does his earthquake.
Guessing this is due to it triggering from targeting one player in the raid and then when this player resists the spell it dosen't trigger whatsoever.

This makes it super annoying since if you have a protection paladin who is healing healers to gain threat he can no longer do so since they don't take any damage (gain threat from the murlocs that is). We only have to use this strategy because warlocks for some reason dont show up on the murlocs threat table so healing a tapping warlock often results in murlocs simply running for random people (another issue with morogrim).

https://www.twitch.tv/videos/384416731?t=03h16m (Murlocs are alerted without the raid taking damage, happens multiple times if u watch the entire VOD)

Another clip of it happening:
https://www.twitch.tv/videos/384530633

**Current behaviour**:
Morogrim sometime's skips doing damage to the raid from his earthquake ability.

**Expected behaviour**: 
Morogrim casts earthquake on the entire raid and thus alerting murlocs, everyone in the raid takes damage / has a chance to resist the spell. 

**Server Revision**: 
2825

**Comment by Godmatik** [comment]
I have yet to see this once happen in either Kara or NW 2.0, I'm guessing it was fixed/resolved at some point, can close

**Comment by EtheriousNW** [comment]
Fixed a while back.
