### ISSUE TITLE
Spell Reflection not reflecting Damage

### ISSUE THREAD

**Issue by narobi123** [Atlantiss/NetherwingBugtracker#5116]
in arena i reflected multiple shatters by a mage and he was afflicted by frostbolt debuff, but the dmg didn't go through. he should take the full damage of his own spells.

**Comment by Jseay1313** [comment]
can confirm reflect isnt doing shit in pvp

**Comment by numiee** [comment]
can confirm it doesnt reflect any damage in PvE, however it seems to give the threat.

**Comment by The14me** [comment]
Rev.3483 
Frostbolt debuff+dmg is reflected just fine (In PVP)
Lightning bolt reflected just fine (In PVE) Tested with Coilfang Siren
