### ISSUE TITLE
Windfury overproc

### ISSUE THREAD

**Issue by Marthroy** [Atlantiss/NetherwingBugtracker#5117]
[//]: # (Enclose links to things related to the bug using http://wowhead.com or any other TBC database.)
[//]: # (You can use screenshot ingame to visual the issue.)
[//]: # (Write your tickets according to the format:)
[//]: # ([Quest][Azuremyst Isle] Red Snapper - Very Tasty!)
[//]: # ([NPC] Magistrix Erona)
[//]: # ([Spell][Mage] Fireball)
[//]: # ([Npc][Drop] Ghostclaw Lynx)
[//]: # ([Web] Armory doesnt work)
[//]: # (To find server revision type `.server info` command in the game chat.)

**Description**: 
Bug windfury
**Current behaviour**:
Magic damage from Off hand proc (flametongue and frostband) seems to be able to proc windfury in main hand.
![image](https://user-images.githubusercontent.com/47875674/54048069-fd4e0180-41d8-11e9-96ec-c98a62a293c2.png)

An exemple on grull : 

On the following screen, the dps from the Shaman "Lillefod", good geared and Slow/Slow WF/WF
![image](https://user-images.githubusercontent.com/47875674/54046727-7ba8a480-41d5-11e9-8a0e-67dd3dcb5361.png)

On the following screen, the dps from the Shaman "Osirus" good geared and Slow/Fast WF/Flametongue
![image](https://user-images.githubusercontent.com/47875674/54046809-b7436e80-41d5-11e9-9df8-24b128ef425c.png)

About 100K windfury damage for both !

**Expected behaviour**: 
Only phisycal damage from main hand should be able to proc Windfury main hand.
**Server Revision**: 
2825

**Comment by Wolffenstein** [comment]
Fixed in rev 2917.
