### ISSUE TITLE
Missing JC recipe Purified Jaggal pearl

### ISSUE THREAD

**Issue by Vanderez** [Atlantiss/NetherwingBugtracker#5119]
[//]: # (Enclose links to things related to the bug using http://wowhead.com or any other TBC database.)
[//]: # (You can use screenshot ingame to visual the issue.)
[//]: # (Write your tickets according to the format:)
[//]: # ([Quest][Azuremyst Isle] Red Snapper - Very Tasty!)
[//]: # ([NPC] Magistrix Erona)
[//]: # ([Spell][Mage] Fireball)
[//]: # ([Npc][Drop] Ghostclaw Lynx)
[//]: # ([Web] Armory doesnt work)
[//]: # (To find server revision type `.server info` command in the game chat.)

**Description**: 
The recipe for purified jaggal pearl is not trainable from any JC trainer.
**Current behaviour**:
According to http://db.hellfire-tbc.com/?spell=41420 it should be trainable by the etheral for Horde in Stormspire. However he does not teach it, as it is not listed.
**Expected behaviour**: 
The recipe should be trainable for anyon at 325 JC or above.
**Server Revision**:

**Comment by veekk** [comment]
[wowhead](https://www.wowhead.com/item=32833/purified-jaggal-pearl) says it was added in patch 2.1.0.6624
