### ISSUE TITLE
[Object] Warpwood Pod

### ISSUE THREAD

**Issue by ircfelix** [Atlantiss/NetherwingBugtracker#5120]
**Description**: 
There are no Warpwood pots in DM East, which makes leveling cooking a pain. 
https://wowwiki.fandom.com/wiki/Warpwood_Pod
The tubers from them can be used to level cooking. Currently, you have to buy over-priced fish from the AH or fish for hours to get a few levels in cooking.

*Current behaviour**:
There are no Warpwood pots in DM East, which makes leveling cooking a pain. 

**Expected behaviour**: 
There should be plenty of Warpwood pots in DM East.

**Server Revision**:

**Comment by Evolvee** [comment]
rev 2827

**Comment by ircfelix** [comment]
<3 much love

**Comment by ircfelix** [comment]
When clicking those objects, sometimes (about 50% of the times) there is just no cast animation and nothing happens. When it works, there is a 5s cast time for opening it, but the pods can be totally empty.

**Comment by Evolvee** [comment]
rev 2863

**Comment by Evolvee** [comment]
not all of them should have loot - some should just root you etc.
