### ISSUE TITLE
BG buffs and flag caps from stealth.

### ISSUE THREAD

**Issue by Johnkeyz** [Atlantiss/NetherwingBugtracker#5121]
[//]: # (Enclose links to things related to the bug using http://wowhead.com or any other TBC database.)
[//]: # (You can use screenshot ingame to visual the issue.)
[//]: # (Write your tickets according to the format:)
[//]: # ([Quest][Azuremyst Isle] Red Snapper - Very Tasty!)
[//]: # ([NPC] Magistrix Erona)
[//]: # ([Spell][Mage] Fireball)
[//]: # ([Npc][Drop] Ghostclaw Lynx)
[//]: # ([Web] Armory doesnt work)
[//]: # (To find server revision type `.server info` command in the game chat.)

**Description**: If you take a Battleground buff while stealthed, you won't get the buff.
Also if you try to capture flags from stealth, it doesn't work, you have to exit stealth to begin the capture process

**Current behaviour**: If you take a Battleground buff while stealthed, you won't get the buff.
Also if you try to capture flags from stealth, it doesn't work, you have to exit stealth to begin the capture process

**Expected behaviour**: You should get the buff even if you're in stealth.
You should leave stealth automatically when beginning flag captures.

**Server Revision**: 2825

**Comment by kemotix** [comment]
Moreover you can't disarm traps while stealthed.

**Comment by ScottieDOESknow** [comment]
Can confirm.

Unable to cap flags in AB or AV unless out of stealth.
Unable to pick WSG or EotS flag unless out of stealth.

**How it should work**
Attempting to interact with any of these flags should remove the stealth buff.

**Comment by kemotix** [comment]
It's also impossible in WSG to repick dropped flag right after leaving stealth.
Rogue should be able to cast Vanish to remove movement imparing effects and pick flag right after to continue running.
Right now even if you manually left stealth and remove Vanish buff you can't pick dropped flag.

**Comment by Johnkeyz** [comment]
Aye you should be able to pick up flags directly from Stealth, or Vanish... Also @Kemotix I recall TBC was like, as you say, with being able to Vanish / block etc and instantly pick up flag again. But on this server there is a debuff that last 2-3 seconds as i recall, preventing you from picking up flag again, it's the same for everyone, so i guess it's fine.

**Comment by tsuone** [comment]
Works.
