### ISSUE TITLE
[Quest] The Essence of Enmity - Brogg's Totem can just be used on the same corpse 10 times

### ISSUE THREAD

**Issue by MAY-THE-ETERNAL-SUN-SHINE-UPON-YOU** [Atlantiss/NetherwingBugtracker#5122]
**Description**: 
The quest requires you to use a totem on 10 corpses. However it does not despawn the corpses, so you can just use the same corpse 10 times.
Tested on a Firemane Scout.

**Current behaviour**:
It does not despawn the corpses, so you can just use the same corpse 10 times.

**Expected behaviour**: 
It should despawn the corpses.

**Server Revision**: 
2825

**Comment by Evolvee** [comment]
rev 2830
