### ISSUE TITLE
Hellfire Ramparts Heroic

### ISSUE THREAD

**Issue by femdead** [Atlantiss/NetherwingBugtracker#5124]
Last Boss and Chest give you 1 blue and no badge - Should be 2 blues and a badge, then later on 2 badges

**Comment by Jalapan** [comment]
@Evolvee 
https://wowwiki.fandom.com/wiki/Vazruden

"Upon killing Nazan, a Reinforced Fel Iron Chest spawns to the side and two pieces of loot from this encounter are in there."

**Comment by Evolvee** [comment]
yea thats 2.4.

on 2.0 chest spawned in center so everything they say is invalid

**Comment by femdead** [comment]
https://www.youtube.com/watch?v=f4EFZpgoafY& here's 2 items dropping in normal mode in 2006

**Comment by sifiuocz** [comment]
Femdead is still half right. Vazruden gives no badge when killed. There is no badge in the chest, no badge on the dragon and no badge on the orc.

**Comment by Evolvee** [comment]
https://github.com/Atlantiss/NetherwingBugtracker/issues/2790#issuecomment-439864135
