### ISSUE TITLE
[warlock][spell] Curse of recklessness (PVP)

### ISSUE THREAD

**Issue by Necroller** [Atlantiss/NetherwingBugtracker#5125]
**Description**: 
curse of recklessness not working properly
**Current behaviour**:
When warlock using CoR to enemy warrior(or npc) spell reflection cor reflection only for few seconds and not making warlock immune to fear.
**Expected behaviour**: 
Should be reflected back for 2 minutes (exept rank 1 spell) and make warlock immune to fear or horror effects like death coil for example.
**Server Revision**:

**Comment by Easyfraggy** [comment]
Need proof from retail on this.

**Comment by Zarant** [comment]
http://www.arenajunkies.com/topic/217-warlock-tip/

**Comment by Wolffenstein** [comment]
Fixed in rev 3536.
