### ISSUE TITLE
Bug Report GM: Gate to Baron Rivendare Not Opening on Stratholme Clear

### ISSUE THREAD

**Issue by DJT777** [Atlantiss/NetherwingBugtracker#5127]
[//]: # (Enclose links to things related to the bug using http://wowhead.com or any other TBC database.)
[//]: # (You can use screenshot ingame to visual the issue.)
[//]: # (Write your tickets according to the format:)
[//]: # ([Quest][Azuremyst Isle] Red Snapper - Very Tasty!)
[//]: # ([NPC] Magistrix Erona)
[//]: # ([Spell][Mage] Fireball)
[//]: # ([Npc][Drop] Ghostclaw Lynx)
[//]: # ([Web] Armory doesnt work)
[//]: # (To find server revision type `.server info` command in the game chat.)

**Description**: 

**Current behaviour**:

**Expected behaviour**: 

**Server Revision**:

**Comment by ttghnw** [comment]
I can confirm this

**Comment by Manaci** [comment]
It opens but it takes like 5-10 minutes.

**Comment by ircfelix** [comment]
orly? still happening

**Comment by ircfelix** [comment]
Please fix. It should open after the adds that spawn on Ramstein's death are dead.

**Comment by ircfelix** [comment]
@Evolvee 

if (ramstein = ded) open gate


Also the gate which you need to clear all 3 ziggurats for to open, stays closed if you wipe at the abomination part of stratholme

**Comment by Evolvee** [comment]
ramstein is in cpp

**Comment by ircfelix** [comment]
cpp?

**Comment by Evolvee** [comment]
c++

**Comment by ircfelix** [comment]
ah k pp tt rd fo.

U know what that means.

**Comment by ircfelix** [comment]
Thank you @Evolvee for commenting on that issue. Now my faith in you fixing this issue in the near future is renewed! Thanks in advance for fixing it, Wrdl.

**Comment by Evolvee** [comment]
i commented the reason why i cant fix it

**Comment by ircfelix** [comment]
:PepeHands:

**Comment by ircfelix** [comment]
Update:
As seen in this video around 7:30 and later https://www.youtube.com/watch?v=6DEEYMGS24w you see how baron rivendare's two doors (outside ziggurat door and rivendare's chamber door should behave):

- Last abomination on abomination square is killed: Rivendare's outside ziggurat door opens
- Ramstein is dead, Rivendare's chamber door is still closed, skeletons outside the ziggurat **do not** automatically aggro the player like they do on NW: Five Skeleton guardians spawn
- Skeleton guardians are dead: Baron Rivendare's Chamber door opens.

**Comment by Rushor** [comment]
the whole script must be reworked

**Comment by The14me** [comment]
Rev.3483 the door open by himself in 5 min after the kill.Still an issue.

**Comment by Wolffenstein** [comment]
Fixed in rev 3783.
