### ISSUE TITLE
Hunter Pet Abilities in Arena

### ISSUE THREAD

**Issue by Falathrin** [Atlantiss/NetherwingBugtracker#5129]
[//]: # (Enclose links to things related to the bug using http://wowhead.com or any other TBC database.)
[//]: # (You can use screenshot ingame to visual the issue.)
[//]: # (Write your tickets according to the format:)
[//]: # ([Quest][Azuremyst Isle] Red Snapper - Very Tasty!)
[//]: # ([NPC] Magistrix Erona)
[//]: # ([Spell][Mage] Fireball)
[//]: # ([Npc][Drop] Ghostclaw Lynx)
[//]: # ([Web] Armory doesnt work)
[//]: # (To find server revision type `.server info` command in the game chat.)

**Description**: 
They're not being auto casted by the pet.
Had to wonder where my pet was plenty of times because it's not automatically casting dive. I need to click dive myself even though it's on automated. Same with other abilities like claw and bite. Sometimes it works fine, but most of the times I need to click abilities myself.

**Current behaviour**:

**Expected behaviour**: 

**Server Revision**:

**Comment by Zarant** [comment]
I believe this is related to issue #3897, since the pet AI doesn't prioritize dash/growl/bite over common focus dumping abilities.

Might also be related to issue #5029, since sometimes my pet loses his passive abilities or in some extreme cases, opening the spell book shows that my pet loses all active abilities despite them being on the pet bar.

**Comment by Falathrin** [comment]
Just wanna add to this. Pets in PVP are extremely bugged. My ravager for example now doesn't cast ANY ability. I opened my spellbook to go check my pet tab for spells to see what the issue is and it wasn't there. I tried stable'ing it and relogging. The pet spellbook tab is gone and I'm assuming this is due to my queueing up for Arenas. Ravager is bugged now even outside Arenas.

**Comment by Falathrin** [comment]
The way to fix this is if I go to pet trainer and unlearn my pet abilities, and re-teach it everything. The pet spells tab appears to be fixed that way. But it still gets bugged frequently in PVP and the pet spells tab goes away and the pet doesnt cast its abilities.

I've found myself with bugged pets in Arenas multiple times now and it's really costly. Makes losing games way higher.

This seriously has to be addressed asap for hunters PVP pls.

**Comment by Falathrin** [comment]
Doing BGs on Kara and my ravager isn't casting dash even though it's on autocast.

**Comment by Godmatik** [comment]
Guessing this was fixed at some point - having played hunter in past year I have never once experienced such issues.

Closing.
