### ISSUE TITLE
Nightsaber + Infected Nsaber Runt Reset is too SLOW

### ISSUE THREAD

**Issue by ttghnw** [Atlantiss/NetherwingBugtracker#513]
[//]: # (Enclose links to things related to the bug using http://wowhead.com or any other TBC database.)
[//]: # (You can use screenshot ingame to visual the issue.)
[//]: # (Write your tickets according to the format:)
[//]: # ([Quest][Azuremyst Isle] Red Snapper - Very Tasty!)
[//]: # ([NPC] Magistrix Erona)
[//]: # ([Spell][Mage] Fireball)
[//]: # ([Npc][Drop] Ghostclaw Lynx)
[//]: # ([Web] Armory doesnt work)

**Description**: 

**Current behaviour**:
On this occasion unlike the too fast reset trend, the nightsabers and infected versions on azuremyst take a HUGE amount of running away to the point that when they reset sometimes the mob doesn't even run away but instead is seen despawning. 

**Expected behaviour**: 
Normal reset running.

**Server Revision**:

**Comment by Tereneckla** [comment]
Fixed
