### ISSUE TITLE
[Item][Engineering] Gnomish Poultryizer - Polymorph effect is only visual

### ISSUE THREAD

**Issue by isshpro** [Atlantiss/NetherwingBugtracker#5131]
**Description**:  Gnomish Poultryizer - Polymorph effect is only visua

**Current behaviour**: lIf you use Gnomish Poultryizer trinket on a player or monster, it makes only visual effect, enemy still will have free movement, and even be able to use any skills.

**Expected behaviour**: Polymorph effect from trinket equal to mage skill

**Server Revision**:  2825

**Comment by Sibrica** [comment]
No it's not the same as mage polymorph. "The target can still move and melee, just can't cast. It's a silence that breaks on damage."

**Comment by The14me** [comment]
https://www.wowhead.com/item=23835/gnomish-poultryizer#comments:id=25973
Rev.3478 not an issue anymore.You can move and auto, but cant cast.
Can be closed.
