### ISSUE TITLE
Priest disease release  doesn't work

### ISSUE THREAD

**Issue by shinmadam** [Atlantiss/NetherwingBugtracker#5133]
[//]: # (Enclose links to things related to the bug using http://wowhead.com or any other TBC database.)
[//]: # (You can use screenshot ingame to visual the issue.)
[//]: # (Write your tickets according to the format:)
[//]: # ([Quest][Azuremyst Isle] Red Snapper - Very Tasty!)
[//]: # ([NPC] Magistrix Erona)
[//]: # ([Spell][Mage] Fireball)
[//]: # ([Npc][Drop] Ghostclaw Lynx)
[//]: # ([Web] Armory doesnt work)
[//]: # (To find server revision type `.server info` command in the game chat.)

**Description**: # ([Spell][Priest] disease release)

**Current behaviour**:
It's not work automatically disease released every five seconds.
**Expected behaviour**: fix plz

**Server Revision**: 
203

**Comment by Dusky1** [comment]
Probably resist

**Comment by EnterLarry** [comment]
It works just fine. I bet you overlooked the debuff type and just figured it was a disease based on the icon.
Especially in Botanica, there's a lot of debuffs (magic, poison) that look like diseases, and magic effects that look like poison icons etc.
The spell name on the database is Abolish Disease.
