### ISSUE TITLE
[npc] Black Ravager [Tame Beast] Missing Ability

### ISSUE THREAD

**Issue by rzk435** [Atlantiss/NetherwingBugtracker#5134]
**Description**: 

**Current behaviour**:
Black Ravager (level 24) Wolf in duskwood doesn't know the ability Bite(rank4) when tamed.
**Expected behaviour**: 
Black Ravager should know Bite(rank4) when tamed.
http://www.wow-petopia.com/classic/abilities.php#bite
**Server Revision**: 
revision 2825

**Comment by Easyfraggy** [comment]
Afaik not all pets have their abilities right? You have to train them. This issue is invalid I think. 

Someone hunter savvy please pitch in.

**Comment by Jalapan** [comment]
Black ravagers have bite rank 4 however..
it's not the Young Black Ravagers that have (Bite Rank 4), only the Black Ravagers.

**Comment by The14me** [comment]
Rev.3478 Not an issue anymore.
Can be closed.
