### ISSUE TITLE
[Spell][Hunter] Tame Beast / Beast Training (Missing spell)

### ISSUE THREAD

**Issue by rzk435** [Atlantiss/NetherwingBugtracker#5135]
http://www.wow-petopia.com/classic/family.php?id=boar
http://www.wow-petopia.com/classic/abilities.php#bite
**Description**: 
I tamed a Giant Moss Creeper to learn the pet ability Bite(rank 4) so I could teach it to my Boar.
When I tamed the Giant Moss Creeper, It had Bite(rank 4). But now when I call my Boar and use Beast Training, I do not see Bite(rank 4) in my Beast Training menu.
**Current behaviour**:
Bite(rank 4) is not showing up in Beast Training menu after taming Giant Moss Creeper.
**Expected behaviour**: 
After taming a pet to learn a pet ability, that ability should be able to be taught to another pet that is able to learn it through the Beast Training spell.
**Server Revision**: 
revision 2825

**Comment by rzk435** [comment]
After killing 50 mobs it finally learned the spell. Wow. should happen after like 5 bites at the most if i remember correctly. *shrug*

**Comment by gunzbngbng** [comment]
There is a chance to learn the ability.  Dash/dive takes even longer.
