### ISSUE TITLE
[Quest] [Stormwind] The Missing Diplomat part 8 - can't retake quest

### ISSUE THREAD

**Issue by H2714** [Atlantiss/NetherwingBugtracker#5136]
[//]: # (Enclose links to things related to the bug using http://wowhead.com or any other TBC database.)
[//]: # (You can use screenshot ingame to visual the issue.)
[//]: # (Write your tickets according to the format:)
[//]: # ([Quest][Azuremyst Isle] Red Snapper - Very Tasty!)
[//]: # ([NPC] Magistrix Erona)
[//]: # ([Spell][Mage] Fireball)
[//]: # ([Npc][Drop] Ghostclaw Lynx)
[//]: # ([Web] Armory doesnt work)
[//]: # (To find server revision type `.server info` command in the game chat.)

**Description**: 
After abandoning [The Missing Diplomat](https://vanillawowdb.com/?quest=1447) part 8 I am unable to retake the quest.

This also happen in [another part](https://vanillawowdb.com/?quest=1266) of the chain, reported in this [issue](https://github.com/Atlantiss/NetherwingBugtracker/issues/4922).

**Current behaviour**:
Unable to speak with quest giver and no exclamation-mark is visible on the mini-map.

**Expected behaviour**: 
[Dashel Stonefist](https://vanillawowdb.com/?npc=4961) should offer the quest again after it has been abandoned.

**Server Revision**: 
2825

**Comment by H2714** [comment]
I have encountered a number of players also unable to talk to Dashel Stonefist, I suspect he is "stuck". After around 2 days the NPC has reset and is now offering the quest and other players are able to continue the chain as well.

**Comment by Tereneckla** [comment]
Fixed
