### ISSUE TITLE
[Spell][Shaman] Lightning Shield consumed by bandage

### ISSUE THREAD

**Issue by davismj** [Atlantiss/NetherwingBugtracker#5137]
**Current behaviour**:

I was bandaged and lost 1 charge of Lightning Shield.

**Expected behaviour**: 

I should not lose any charges of Lightning Shield when bandaged.

**Server Revision**:  203

**Comment by Easyfraggy** [comment]
Can someone confirm this bug?

**Comment by Dusky1** [comment]
I can confirm. Also, same happens for Water Shield.

**Comment by Wolffenstein** [comment]
Fixed in rev 2889.
