### ISSUE TITLE
[Loot] Vulture Gizzard is not shareable loot.

### ISSUE THREAD

**Issue by Hessels90** [Atlantiss/NetherwingBugtracker#5138]
**Description**: 
The questitem Vulture Gizzard for Vulture's Vigor and The Basilisk's Bite is not shareable loot.

**Current behaviour**:
Not Shareable loot.

**Expected behaviour**: 
Expected it to be shareable loot.

**Server Revision**: 
2825

**Comment by Manaci** [comment]
They're not quest items, can sell them on the AH or trad with other players = won't be shareable loot.

**Comment by Wolffenstein** [comment]
As Manaci wrote, it's not marked purely as a quest item, therefore will not be shared.
