### ISSUE TITLE
Arathi Basin bugged lose

### ISSUE THREAD

**Issue by weedzyx** [Atlantiss/NetherwingBugtracker#5139]
Hello,

we were winning in AB 110/40. Battleground ended due to not enough players, ended with score 110/40 for us, but we lost with 1 mark.

How is it possible ?

Thank you in advance.

**Comment by Wolffenstein** [comment]
It ends with a draw.

**Comment by Dusky1** [comment]
Wolf seems like you have no idea whats up on the server. There have never been draws on NW.

When the bg ends cuz there is not enugh ppl, its won by the Team that have more points
