### ISSUE TITLE
Summoning Stones

### ISSUE THREAD

**Issue by Azalen** [Atlantiss/NetherwingBugtracker#514]
**Current behaviour**:
They dont work. I get some frame for a split second but I cannot click anything or take the summon before the frame vanishes.
Disabled all AddOns, no change.

**Server Revision**: 
[2045]

**Comment by Azalen** [comment]
When I enable the AddOn "Automaton" for automatic summon accept it works - like I said, the summoning frame is there for a split second only.

**Comment by Azalen** [comment]
Okay, its possible to accept it without an AddOn as well if you spam summon.

**Comment by Wolffenstein** [comment]
Fixed
