### ISSUE TITLE
[Ragglesnout][Drop] Boar Champion's Belt

### ISSUE THREAD

**Issue by farmerdave3** [Atlantiss/NetherwingBugtracker#5140]
[missing loot.docx](https://github.com/Atlantiss/NetherwingBugtracker/files/2896970/missing.loot.docx)
[//]: # (Enclose links to things related to the bug using http://wowhead.com or any other TBC database.)
[//]: # (You can use screenshot ingame to visual the issue.)
[//]: # (Write your tickets according to the format:)
[//]: # ([Quest][Azuremyst Isle] Red Snapper - Very Tasty!)
[//]: # ([NPC] Magistrix Erona)
[//]: # ([Spell][Mage] Fireball)
[//]: # ([Npc][Drop] Ghostclaw Lynx)
[//]: # ([Web] Armory doesnt work)
[//]: # (To find server revision type `.server info` command in the game chat.)

**Description**: 
Bags were full, won roll on an item, opened bag space to go loot boss and pickup, item said "still being rolled for". Boss then despawned maybe 30 seconds later without assigning loot.
**Current behaviour**:

**Expected behaviour**: 

**Server Revision**:

**Comment by Manaci** [comment]
Fixed with loot rework
