### ISSUE TITLE
[NPC] Spectral Performer double explodes when dies

### ISSUE THREAD

**Issue by Mikik3jr** [Atlantiss/NetherwingBugtracker#5141]
[//]: # (Enclose links to things related to the bug using http://wowhead.com or any other TBC database.)
[//]: # (You can use screenshot ingame to visual the issue.)
[//]: # (Write your tickets according to the format:)
[//]: # ([Quest][Azuremyst Isle] Red Snapper - Very Tasty!)
[//]: # ([NPC] Magistrix Erona)
[//]: # ([Spell][Mage] Fireball)
[//]: # ([Npc][Drop] Ghostclaw Lynx)
[//]: # ([Web] Armory doesnt work)
[//]: # (To find server revision type `.server info` command in the game chat.)

**Description**: 
This NPC in Karazhan explodes when it dies.

**Current behaviour**:
When they die they explode twice:
![image](https://user-images.githubusercontent.com/43505031/53290756-e525bd80-37a8-11e9-9d75-e29d9a84e5bd.png)

**Expected behaviour**: 
They should explode once when they die.

**Server Revision**: 
2825, but it was like this since we first encountered them

**Comment by Mikik3jr** [comment]
If a random upvoted comment matters for proof (if you need)
![image](https://user-images.githubusercontent.com/43505031/53291171-45b7f900-37af-11e9-8641-07a0d50671c6.png)

**Comment by Wolffenstein** [comment]
Fixed in rev 2831.
