### ISSUE TITLE
[Core][PVP] Spell resists are still bugged, players resist way too much.

### ISSUE THREAD

**Issue by killablink** [Atlantiss/NetherwingBugtracker#5142]
**Description**: Players are still resisting spells way too much without even any resistances. At most players should have 1% chance to resist if you are spell hit capped and no resists, yet it feels more like 10-20%. Note I have 8% hit and 30 spell pen
https://gfycat.com/SimilarCarefulAnemoneshrimp
https://gfycat.com/NegligibleDisgustingBee

These are only 2 clips but it happens ALL the time. My priest partner complains about it too, a lot of ppl on discord and there was an earlier report about the same thing that was closed. #4954  This really needs to be looked at because casters are really unreliable right now in pvp.
**Current behaviour**:

**Expected behaviour**: Resists actually working

**Server Revision**:

**Comment by Wolffenstein** [comment]
Would be great if you could grab 2 characters, test in a duel and provide me with how much resist/penetration each character had so I could easily replicate it on local (and which spells were used).

**Comment by killablink** [comment]
It's hard to test by myself, but I just notice that druids resist a lot, even without MotW. In these 2 clips they both didn't have MotW yet they resisted 2 spells in a row, which would be 1% x 1% chance of happening. I really doubt that I'm just that unlucky to see it happening that much
