### ISSUE TITLE
[Spell][Bloodrage] Blood rage seems to have a chance to break frost nova from self dmg

### ISSUE THREAD

**Issue by killablink** [Atlantiss/NetherwingBugtracker#5144]
**Description**: Bloodrage can break frost nova//roots from the small self dmg inflicted.
https://gfycat.com/RealisticClosedIndianspinyloach
**Current behaviour**: Bloodrage can break frost nova//roots from the small self dmg inflicted.

**Expected behaviour**: Shouldn't be able to break a nova from a bloodrage self dmg. (also shows how frost nova is breaking from barely any dmg)

**Server Revision**: 2825

**Comment by Evolvee** [comment]
https://www.youtube.com/watch?v=0dSUsdp-Pwo&feature=youtu.be&t=1386
explain
