### ISSUE TITLE
Quest [Cipher of Damnation]

### ISSUE THREAD

**Issue by Naroo12** [Atlantiss/NetherwingBugtracker#5146]
[//]: # (Enclose links to things related to the bug using http://wowhead.com or any other TBC database.)
[//]: # (You can use screenshot ingame to visual the issue.)
[//]: # (Write your tickets according to the format:)
[//]: # ([Quest][Azuremyst Isle] Red Snapper - Very Tasty!)
[//]: # ([NPC] Magistrix Erona)
[//]: # ([Spell][Mage] Fireball)
[//]: # ([Npc][Drop] Ghostclaw Lynx)
[//]: # ([Web] Armory doesnt work)
[//]: # (To find server revision type `.server info` command in the game chat.)

**Description**: 
Cyrukh The Firelord
**Current behaviour**:
After using the stone, boss won't spawn.
**Expected behaviour**: 
After using the stone the boss should spawn normally.
**Server Revision**:

**Comment by Manaci** [comment]
Fixed
