### ISSUE TITLE
[Spell] Able to cast spell while dead

### ISSUE THREAD

**Issue by yun548** [Atlantiss/NetherwingBugtracker#5147]
[//]: # (Enclose links to things related to the bug using http://wowhead.com or any other TBC database.)
[//]: # (You can use screenshot ingame to visual the issue.)
[//]: # (Write your tickets according to the format:)
[//]: # ([Quest][Azuremyst Isle] Red Snapper - Very Tasty!)
[//]: # ([NPC] Magistrix Erona)
[//]: # ([Spell][Mage] Fireball)
[//]: # ([Npc][Drop] Ghostclaw Lynx)
[//]: # ([Web] Armory doesnt work)
[//]: # (To find server revision type `.server info` command in the game chat.)

![ezflkfzekoilefzklo](https://user-images.githubusercontent.com/6206386/53297849-7eafa680-385f-11e9-8d77-41672da57da1.png)

**Description**: I was casting flash heal and spamming the Psychic scream button. My flash heal completed but I died instead of being healed, then my Physchic scream casted itself.

**Current behaviour**: I was able to cast a spell without having the ffects of the previously casted spell applied. I was able to cast a spell while dead

**Expected behaviour**:  I should not be able to cast a spell if the effects of the previous spells haven't been applied yet. I should not be able to cast a spell while dead

**Server Revision**:  2825

**Comment by The14me** [comment]
Rev.3478 there is no way to reproduce that.
Can be closed.
