### ISSUE TITLE
Levitate randomly breaking

### ISSUE THREAD

**Issue by Hidehugo** [Atlantiss/NetherwingBugtracker#5148]
**Description**: While in Nagrand, the spell "Levitate" of priests doesn't keep the caster over water, just for the instant you cast it. Every movement seems to have a chance of letting the caster fall into the water. Weirdly enough, sometimes it happens while standing still. If you want to see the weird phenomenon in action, watch the priests trying to fish the pure water on skysong lake (55.87, 30.53). Sometimes it takes them 5-6 feathers to succeed in this weirdly hard task

**Current behaviour**: Levitate not giving waterwalking for the duration of the buff

**Expected behaviour**: Levitate giving waterwalking for the duration of the buff

**Server Revision**:

**Comment by Evolvee** [comment]
I cant reproduce this, you probably move with right mouse button and aim down (to the water).
