### ISSUE TITLE
Several missing Nerubis Guard#16313 patrols at Suncrown Village

### ISSUE THREAD

**Issue by Tenoutoften** [Atlantiss/NetherwingBugtracker#515]
**Description**: 
There seems to be 1 missing Nerubis Guard#16313(https://db.excalibur.ws/?npc=16313) patrol going up and down a ramp(and probably around the second level of the building) https://youtu.be/deJT_m2lp68?t=117

There is also 1 missing Nerubis Guard#16313(https://db.excalibur.ws/?npc=16313) patrol going around the place on the road https://youtu.be/deJT_m2lp68?t=146

I've done a few of these reports now, and I assume whoever is fixing them have done quite a bit more, you just have to look around for particularly awkwardly placed Nerubis Guard#16313(https://db.excalibur.ws/?npc=16313) and that's probably the missing patrol-mob rather than adding a whole new NPC.

**Current behaviour**:
Only Anok'suten#16357(ttps://db.excalibur.ws/?npc=16357) is patroling this place, everything else stand still.

**Expected behaviour**: 
I expect two  Nerubis Guard's#16313(https://db.excalibur.ws/?npc=16313) to be patrolling this place

**Server Revision**: 
2050

**Comment by aresbrutus** [comment]
This was fixed in rev `2086`
