### ISSUE TITLE
[Core][Combat] Spell resists not keeping you in combat .

### ISSUE THREAD

**Issue by Easyfraggy** [Atlantiss/NetherwingBugtracker#5150]
**Description**: If you start attacking a mob that is already attacking someone else with a spell, and your spell resists, you enter combat and leave combat right after.
**Current behaviour**: If you start attacking a mob that is already attacking someone else with a spell, and your spell resists, you enter combat and leave combat right after.
**Expected behaviour**: Should stay in combat even if you get resisted on your first spell.
**Server Revision**:

**Comment by Godmatik** [comment]
Can not reproduce.

Mob is attacking someone else. I attack with a spell --> resists --> I enter combat and do not leave it.

Guess this was fixed at some point.

Closing.
