### ISSUE TITLE
[Core][Mobs, PVP(?)] Blocking while casting.

### ISSUE THREAD

**Issue by Easyfraggy** [Atlantiss/NetherwingBugtracker#5151]
**Description**: Some spellcasters are able to block abilities while casting. A mob was casting hellfirerain of fire and my rogue kicked him, he blocked it but it still got interrupted anyways. (then again that should never happen so it doesn't matter) Venture Co. Geomancer for example

 **Current behaviour**:  Some spellcasters are able to block abilities while casting. A mob was casting hellfire and my rogue kicked him, he blocked it but it still got interrupted anyways. (So two bugs here)
  
  **Expected behaviour**: Shouldn't be able to block while casting.

  **Server Revision**:  2550

**Comment by Easyfraggy** [comment]
it's because interrupt is instant (no batching) but the damage is delayed - probably should decide wether the attack is blocked or not instantly without batching just the actual damage being delayed.

**Comment by Godmatik** [comment]
Unable to reproduce, perhaps fixed at some point
