### ISSUE TITLE
[Core][Targeting] Breaking an enemy player out of stealth + focus frame

### ISSUE THREAD

**Issue by Easyfraggy** [Atlantiss/NetherwingBugtracker#5152]
**Description**: If I use perception, see a druid in stealth, put him on my focus frame and break him out of stealth, he still disappears for 1 second to reappear out of stealth, making it so I lose him from my focus frame. (He was tauren so no shadowmeld shenanigans) I haven't been able to reproduce this it in an arena game again.

**Expected behaviour**: Should get out of stealth instantly and I shouldn't lose my focus target

**Server Revision**: 2551

**Comment by Zarant** [comment]
Same thing happens with party members, when they stealth they disappear for a split second, removing themselves from your focus frame.

**Comment by Zarant** [comment]
This bug seems fixed, I can't reproduce it anymore.

Revision: 3451
