### ISSUE TITLE
[Core][Shadowstep] Character location update

### ISSUE THREAD

**Issue by Easyfraggy** [Atlantiss/NetherwingBugtracker#5154]
* **Description**: Sometimes when people shadowstep while receiving a cc or a snare at the same time, the character won't be updated in the game. (Didn't manage to record the clip before that, it starts with him using shadowstep and you see that he teleports after the druids root ends. https://gfycat.com/PerkyKindAnole

**Current behaviour**:

**Expected behaviour**: Should update location no matter what

**Server Revision**: 2570

**Comment by Godmatik** [comment]
Unable to reproduce - and have not heard of this issue on Netherwing in the past year.
Probably fixed at some point.
