### ISSUE TITLE
[Arena] Game freezing for 3 seconds

### ISSUE THREAD

**Issue by Easyfraggy** [Atlantiss/NetherwingBugtracker#5155]
* **Description**: Every other arena game the game just freezes for around 3 seconds for no particular reason. Some other players also have that happen to them. It only happens in arena games. https://gfycat.com/CourageousWellmadeDonkey

**Current behaviour**:

**Expected behaviour**: No freezes

**Server Revision**: 2574

**Comment by Easyfraggy** [comment]
![image](https://user-images.githubusercontent.com/36134067/53298822-66299700-3833-11e9-854f-3c4e08b5fd91.png)

**Comment by Manaci** [comment]
Fixed at some point
