### ISSUE TITLE
[Mob][Spell] Firemane scout's Fire Shield

### ISSUE THREAD

**Issue by Easyfraggy** [Atlantiss/NetherwingBugtracker#5156]
**Description**: Should tick 30 dmg every 3 seconds,

**Current behaviour**: Should tick 30 dmg every 3 seconds,

**Expected behaviour**: Ticks every 1 second or less

**Server Revision**:

**Comment by Easyfraggy** [comment]
![image](https://user-images.githubusercontent.com/36134067/53298832-88231980-3833-11e9-91a7-bd293b8434f6.png)

**Comment by Godmatik** [comment]
Rev 4016 - no longer an issue - likely fixed with new spell aura branch.
Fire shield properly is ticking it's damage once every 3 seconds
