### ISSUE TITLE
[Spell][Mage] Combustion

### ISSUE THREAD

**Issue by Easyfraggy** [Atlantiss/NetherwingBugtracker#5157]
**Description**: Combustion is currently only gaining 1 charge even when you aoe multiple targets with blast wave for example.Also, when you get resisted, you are currently not gaining 1 charge.

**Current behaviour**:

**Expected behaviour**: If you hit 3 people with blast wave, you should gain 3 stacks of combustion, ( becomes combustion 4 if you just used it.https://youtu.be/uJfAo624wQA?t=424 (patch 3.0 clip but there are no changes in combustion if you look at the changelog http://wowwiki.wikia.com/wiki/Combustion_(old)Also, when you get resisted you should gain 1 charge, this was changed to not do so later in wotlk Wrath-Logo-Small Patch 3.2.0 (04-Aug-2009): Fire spell misses will no longer trigger this talent.

**Server Revision**: 2603

**Comment by Godmatik** [comment]
I am gaining 1 charge for each enemy hit when I AoE, must have been fixed at some point.

Closing.
