### ISSUE TITLE
[Blood Furnace] Keli'dan the breaker, wrong spells

### ISSUE THREAD

**Issue by Easyfraggy** [Atlantiss/NetherwingBugtracker#5158]
**Description**: Using an aoe corruption that ticks for 500 dmg that he shouldn't have at all. aoe shadow bolt volley seems way overtuned, 1800 dmg to everyone every few seconds. No comments about corruption on wowhead. https://www.wowhead.com/npc=17377/kelidan-the-breaker#comments https://gfycat.com/LivelySlowIrishterrier 

**Expected behaviour**: Normal boss.

**Server Revision**: Latest

**Comment by Easyfraggy** [comment]
![image](https://user-images.githubusercontent.com/36134067/53298870-dfc18500-3833-11e9-9c9e-62dca649dadc.png)

![image](https://user-images.githubusercontent.com/36134067/53298873-e64ffc80-3833-11e9-8805-329c6d6bd36c.png)

**Comment by sefamurat** [comment]
He shouldn't volley people that are not in front of him, same with 2nd boss. They both can cast volley on 360 degrees which I believe is wrong. Found a source on the front volley:

http://www.tentonhammer.com/guides/the-blood-furnace-guide

**Comment by Wolffenstein** [comment]
Fixed in rev 2889.
