### ISSUE TITLE
[Spell][Water Elemental] Pet attacking a frost immune mob

### ISSUE THREAD

**Issue by Easyfraggy** [Atlantiss/NetherwingBugtracker#5159]
**Description**: If I send my pet attack another frost immune mob, he will go to melee range and do nothing.

**Current behaviour**: If I send my pet attack another frost immune mob, he will go to melee range and do nothing.

**Expected behaviour**: He should keep normal behavior and cast his water bolts and get immune messages.

**Server Revision**: 2605

**Comment by Zarant** [comment]
Looking at the classic client for reference, sending your imp after a fire immune target will make your imp run to the target at firebolt range and then do nothing.

Also, a hunter pet with Growl on auto cast will not cast that spell if you send your pet to attack a target immune to it (like the harvest reapers in Westfall).

Everything seems to be working as intended, except for the part where the pet runs to melee range.
