### ISSUE TITLE
[NPC]Shadowpine Witch#16341 doesn't apply [Spell]Lightning Shield#12550 outside of combat.

### ISSUE THREAD

**Issue by Tenoutoften** [Atlantiss/NetherwingBugtracker#516]
**Description**: 
Shadowpine Witch's#16341 (https://db.excalibur.ws/?npc=16341#abilities) are suppose to keep Lightning Shield#12550(https://db.excalibur.ws/?spell=12550) on themselves outside of combat. One can be seen here with it on, and another one refreshing it while not being in combat a few seconds later.
https://youtu.be/AflIu9Vlw8c?t=18 Currently they don't use it unless they fight you.

**Expected behaviour**: 
Expected to keep their Lightning Shield#12550 up outside of combat.

**Server Revision**: 
2050

**Comment by Evolvee** [comment]
fixed in next revision
