### ISSUE TITLE
[Core][Mounting up + Pet] Summon Water Elemental

### ISSUE THREAD

**Issue by Easyfraggy** [Atlantiss/NetherwingBugtracker#5160]
* **Description**: When you are mounted and your pet is following you, the pet action bar should be greyed out and your pet shouldn't be able to attack mobs while your mounted.

**Current behaviour**:

**Expected behaviour**: Doesn't attack mobs while mounted

**Server Revision**: 2605

**Comment by Godmatik** [comment]
Pet bar is greyed out for me while mounted - guess it was fixed a while ago.

Closing.
