### ISSUE TITLE
[Core][pets][Mage][Water Elemental] Right clicking a mob sends your pet to attack it on defensive.

### ISSUE THREAD

**Issue by Easyfraggy** [Atlantiss/NetherwingBugtracker#5161]
**Description**: Currently, because of the current bug where you stay "in combat" (Your character tries to attack something even if you have no target, with your weapon out), your water elemental will try to and go attack ita mob you only clicked and you can't stop it, so it often pulls mobs that you didn't want to.
  **Current behaviour**:
  
  **Expected behaviour**: Your pet only goes to attack if you press pet attack, it shouldn't go attack because you clicked a mob

  **Server Revision**: 3605

**Comment by Easyfraggy** [comment]
![image](https://user-images.githubusercontent.com/36134067/53298907-52326500-3834-11e9-8701-6c37ca1f5052.png)

**Comment by Tereneckla** [comment]
Fixed
