### ISSUE TITLE
[Core][Mage][Water Elemental] Can't cancel pet's water bolt cast with passive.

### ISSUE THREAD

**Issue by Easyfraggy** [Atlantiss/NetherwingBugtracker#5162]
* **Description**: Currently there is no way to stop your pet from attacking a target with pet passive. As soon as your pet goes to attack something, you can't make it stop and bring it back close to you.

**Current behaviour**:

**Expected behaviour**: Pressing pet passive should bring back your pet and stop casting if he was

**Server Revision**: 2605

**Comment by Godmatik** [comment]
Already fixed, can close @EtheriousNW
