### ISSUE TITLE
[Spell][Spellsteal] Reflected spellsteal is giving the buff to the reflecter

### ISSUE THREAD

**Issue by Easyfraggy** [Atlantiss/NetherwingBugtracker#5163]
* **Description**: Using spellsteal on a target that has reflect is actually reflecting the spellsteal, making the target take a buff from the mage.

**Current behaviour**: Using spellsteal on a target that has reflect is actually reflecting the spellsteal, making the target take a buff from the mage.

**Expected behaviour**: Reflecting spellsteal shouldn't do anything, it shouldn't dispel the mage nor give the reflecter a buff.

**Server Revision**: 2646

**Comment by Easyfraggy** [comment]
![image](https://user-images.githubusercontent.com/36134067/53298930-99b8f100-3834-11e9-8317-58b42020ee4d.png)

**Comment by Easyfraggy** [comment]
![image](https://user-images.githubusercontent.com/36134067/53298933-a2112c00-3834-11e9-9c9a-219ddd2cfdd5.png)

**Comment by Godmatik** [comment]
Rev 4017 - no longer an issue.

Casting spellsteal on a target with spell reflect active - nothing happens.
