### ISSUE TITLE
[Core][Pathing][Summon Water Elemental] Water elemental often gets stuck on terrain and doesn't do anything.

### ISSUE THREAD

**Issue by Easyfraggy** [Atlantiss/NetherwingBugtracker#5166]
**Description**:**Description**: Water Elemental often gets stuck on terrain and you can't bring him back to you or attack using your pet commands. Will update post with videos.

**Current behaviour**:
  **Expected behaviour**: Doesn't get stuck.
  **Server Revision**:

**Comment by Zarant** [comment]
It's the same underlying issue behind issues #2311 and #2314

**Comment by Manaci** [comment]
Fixed
