### ISSUE TITLE
[Summoning Stone] Accepting a summon late doesn't do anything.

### ISSUE THREAD

**Issue by Easyfraggy** [Atlantiss/NetherwingBugtracker#5167]
* **Description**: If you accept the summon after maybe 20~ seconds have passed, nothing will happen.

**Current behaviour**: If you accept the summon after maybe 20~ seconds have passed, nothing will happen.

**Expected behaviour**: You should be summoned even if there is 1 second out of 2 minutes left.

**Server Revision**: 2646

**Comment by devo6969** [comment]
The only time I've ever encounter this problem playing on live servers is when someone is double summoned or they have the debuff from teleporting with engineering "Evil Twin".
