### ISSUE TITLE
[Spell][Shaman] Flametongue Weapon

### ISSUE THREAD

**Issue by Eidous** [Atlantiss/NetherwingBugtracker#517]
[//]: # (Enclose links to things related to the bug using http://wowhead.com or any other TBC database.)
[//]: # (You can use screenshot ingame to visual the issue.)
[//]: # (Write your tickets according to the format:)
[//]: # ([Quest][Azuremyst Isle] Red Snapper - Very Tasty!)
[//]: # ([NPC] Magistrix Erona)
[//]: # ([Spell][Mage] Fireball)
[//]: # ([Npc][Drop] Ghostclaw Lynx)
[//]: # ([Web] Armory doesnt work)

**Description**: 
Flametongue sometimes hits twice on 1 weapon swing.

**Current behaviour**:
https://imgur.com/a/xujozNu

**Expected behaviour**: 
Flametongue should only hit once per swing.

**Server Revision**: 
2050

**Extra Info**: I do have to note that I'm having a lot of trouble reproducing this bug myself, not quite sure what is causing it.

**Comment by Peglaa** [comment]
Have to say I didn't notice that as of yet. Will try to investigate.

**Comment by Eidous** [comment]
I still haven't found any consistent way to get this to happen. But I think so far it only happens when I'm fighting either satyrs, or the elder black bears in Bloodmyst isles. (So it might have something to do with the stats of these mobs)

**Comment by hitbutton** [comment]
Occurs quite regularly testing on the Test Dummys in Shattrath.
Flametongue is only on the MH here, with the OH using windfury:
![image](https://user-images.githubusercontent.com/16194079/50404282-f13bd180-079d-11e9-9c44-030b7d3add33.png)

**Comment by hitbutton** [comment]
This is happening pretty regularly for me, with multiple FT procs occurring around once every 15 swings on average (with either fast or slow weapons).

This has a pretty major effect on enhancement dps and weapon choice. At the very least it makes FT the preferable offhand enchant over WF, whereas WF/WF with slow weapons should be better.

**Comment by kiraleos** [comment]
This is still happening on rev 2783

![alt text](https://i.imgur.com/XK6BRPN.png)

**Comment by QuelSera** [comment]
Still randomly happening (I don't get double but triple hits of FT)

**Comment by Easyfraggy** [comment]
What weapon are you using?

**Comment by Easyfraggy** [comment]
I could replicate this issue easily on dummies on dev realm:

![image](https://user-images.githubusercontent.com/36134067/55683350-fd0f6600-593e-11e9-948c-e07c7616f7aa.png)

Should be less flametongue procs than swings (14 dodges).

![image](https://user-images.githubusercontent.com/36134067/55683361-1e705200-593f-11e9-89c1-e58851e0cb1e.png)

Here a few examples of double procs

**Comment by The14me** [comment]
rev 3441. still happen.

**Comment by Wolffenstein** [comment]
Fixed in rev 3451.
