### ISSUE TITLE
[Bug][Combat] Stuck in combat many times in Arcatraz

### ISSUE THREAD

**Issue by Easyfraggy** [Atlantiss/NetherwingBugtracker#5170]
* **Description**: Many times in Arcatraz you get stuck in combat after fighting mobs, can't figure what's triggering it.

**Current behaviour**:

**Expected behaviour**: No random stuck in combats with nothing.

**Server Revision**: 2647

**Comment by Easyfraggy** [comment]
![image](https://user-images.githubusercontent.com/36134067/53299024-c28db600-3835-11e9-8522-ab98e3eebb03.png)

**Comment by Wolffenstein** [comment]
was fixed
