### ISSUE TITLE
[Core][PVP] Spell resists are still bugged, players resist way too much.

### ISSUE THREAD

**Issue by Easyfraggy** [Atlantiss/NetherwingBugtracker#5171]
**Description**: Players are still resisting spells way too much without even any resistances. At most players should have 1% chance to resist if you are spell hit capped and no resists, yet it feels more like 10-20%. Note I have 8% hit and 30 spell pen
  https://gfycat.com/SimilarCarefulAnemoneshrimp
  https://gfycat.com/NegligibleDisgustingBee
  These are only 2 clips but it happens ALL the time. My priest partner complains about it too, a lot of ppl on discord and there was an earlier report about the same thing that was closed. #4954 This really needs to be looked at because casters are really unreliable right now in pvp. **Current behaviour**:
  **Expected behaviour**: Resists actually working
  **Server Revision**:

**Comment by Easyfraggy** [comment]
![image](https://user-images.githubusercontent.com/36134067/53299046-fa94f900-3835-11e9-9a4b-3819613d84b2.png)

**Comment by Zarant** [comment]
There's nothing much that us as players can do to test that hypothesis with any decent statistical significance, other than just cast the same spell thousands of times and record the outcome of each spell cast, it'll take an insurmountable amount of hours of testing to get to the bottom of the issue. 

I'm gonna provide a source that serves as reference on how spell mechanics should work in tbc, just in case a kind soul consider to embark on this adventure:

http://web.archive.org/web/20080210081348/http://dwarfpriest.com/2008/01/07/spell-hit-spell-penetration-and-resistances/

**Comment by Easyfraggy** [comment]
This is just a repost - like all my reports today. After a 10 year old went on a tantrum I had to repost them as mine. The only way we can test it is also casting a spell many times - though it seems to only happen in PvP it is probably easiest for some TESTER rank to test on dev realm.

**Comment by pleasse** [comment]
something wrong with resist, got 93hit rating on mage over hitcap... "80" spell pen and i get alot of resists mostly on warriors for some reason, had a arena game where literally 5 frost novas got resisted vs a warrior... spell steal and frost nova seem to resist alot for me, and i even remove the druid buff and still get alot of resists should be a rare thing to resist not common

maybe when buff gets removed it only is a visual effect? but he still has the resistance? 
should probably not even matter when having 80spell pen tho so im not sure whats up, rogue shiv seems to get resisted alot aswell 

elemental pet nova also misses frequently

**Comment by Lockanloads** [comment]
please fix this

**Comment by Frama1** [comment]
> something wrong with resist, got 93hit rating on mage over hitcap... "80" spell pen and i get alot of resists mostly on warriors for some reason, had a arena game where literally 5 frost novas got resisted vs a warrior... spell steal and frost nova seem to resist alot for me, and i even remove the druid buff and still get alot of resists should be a rare thing to resist not common
> 
> maybe when buff gets removed it only is a visual effect? but he still has the resistance?
> should probably not even matter when having 80spell pen tho so im not sure whats up, rogue shiv seems to get resisted alot aswell
> 
> elemental pet nova also misses frequently
> 
> warrior/warlocks resist all the time with 80spell pen
thats why?
https://tbc-twinhead.twinstar.cz/?item=22545
http://www.wowaura.com/talentstbc/talents.html?en&hunter&0000000000000000000000000000000000000000003303030400300000000000
https://tbc-twinhead.twinstar.cz/?item=25895

**Comment by Easyfraggy** [comment]
I don't see any proof or indication that this issue is valid at all.
