### ISSUE TITLE
A Burden of Souls questt 

### ISSUE THREAD

**Issue by burgerwow** [Atlantiss/NetherwingBugtracker#5172]
[//]: # (Enclose links to things related to the bug using http://wowhead.com or any other TBC database.)
[//]: # (You can use screenshot ingame to visual the issue.)
[//]: # (Write your tickets according to the format:)
[//]: # ([Quest][Azuremyst Isle] Red Snapper - Very Tasty!)
[//]: # ([NPC] Magistrix Erona)
[//]: # ([Spell][Mage] Fireball)
[//]: # ([Npc][Drop] Ghostclaw Lynx)
[//]: # ([Web] Armory doesnt work)
[//]: # (To find server revision type `.server info` command in the game chat.)

**Description**: ([Quest][Helfire Penisula] A barden of Souls )

**Current behaviour**: It's not work,  its just to need kill 20 mobs

**Expected behaviour**: 20 mobs need count

**Server Revision**: Netherwing

**Comment by The14me** [comment]
Fixed at next rev.
