### ISSUE TITLE
[Core][Casting bug][IMPORTANT] Casting fails, can't start casting for no reason

### ISSUE THREAD

**Issue by Easyfraggy** [Atlantiss/NetherwingBugtracker#5173]
**Description**: Sometimes when you start casting and interrupt your cast by moving (sometimes it interrupts by itself for no reason like in gif #2) when you want to start casting again you get bugged and nothing happens, you can't start casting for a few seconds. [https://gfycat.com/](https://gfycat.com/SmoggyDetailedFantail)[ImmaterialImpassionedAustraliancurlew](https://gfycat.com/ImmaterialImpassionedAustraliancurlew)[SmoggyDetailedFantail](https://gfycat.com/SmoggyDetailedFantail) Look after I move to stop casting my frostbolt, I am spamming frostbolt but my character is unable to cast it for 2-3 seconds. https://gfycat.com/DelightfulHatefulAnchovy Here you can see that I was just spamming frostbolts and it seems like the queueing system screwed my casts and interrupted frostbolt https://gfycat.com/DecentWelltodoBeetle
  **Current behaviour**:
  
  **Expected behaviour**: Should be able to cast.
  **Server Revision**: 2663

**Comment by Easyfraggy** [comment]
![image](https://user-images.githubusercontent.com/36134067/53299473-0505c180-383b-11e9-9866-bc43300afe4c.png)

**Comment by Easyfraggy** [comment]
![image](https://user-images.githubusercontent.com/36134067/53299474-0b943900-383b-11e9-91c9-ac6f7a98a9ea.png)

**Comment by Godmatik** [comment]
I am guessing this was resolved and issue never closed.
Have not heard of this on past year in Netherwing. And if it was spell delay related, that was disabled ages ago.
Closing.
