### ISSUE TITLE
[Core][Spellcasting][Autoattack] Channeled spells get interrupted due to autoattack not being cancelled

### ISSUE THREAD

**Issue by Easyfraggy** [Atlantiss/NetherwingBugtracker#5174]
* **Description**: I oftenly get interrupted by mobs that don't have any interrupts/silences. They autoattack you once and your cast gets interrupted and there is no school lockout. https://gfycat.com/LividSoggyJaguarundiI get hit once by the fire ele and my blizzard is interrupted.

**Current behaviour**: I oftenly get interrupted by mobs that don't have any lockouts. They autoattack you once and your cast gets interrupted and there is no school lockout.

**Expected behaviour**: No random interrupts when hit.

**Server Revision**: 2676

**Comment by Easyfraggy** [comment]
![image](https://user-images.githubusercontent.com/36134067/53299484-34b4c980-383b-11e9-9b0d-c2e233c3530f.png)

**Comment by Godmatik** [comment]
Unable to reproduce, fixed at some point i assume
