### ISSUE TITLE
[Spell][Iceblock] Going into iceblock sometimes reset mobs.

### ISSUE THREAD

**Issue by Easyfraggy** [Atlantiss/NetherwingBugtracker#5175]
**Description**: Used iceblock, almost every mob reset
  https://gfycat.com/ThatInsidiousCub
  **Current behaviour**:**Current behaviour**: I think it might be caused by a shadow priest's vampiric embrace, because my party member actually aggroed one of them from really far because of the heal. It might be some weird interaction with vampiric embrace threat with mobs from really far away.
**Expected behaviour**: Shouldn't reset
  **Server Revision**: 2676

**Comment by Godmatik** [comment]
Mobs do not aggro from a VE's heal alone, they need to actually be tagged.

Guessing this was fixed a while ago, can not reproduce and have never heard anyone experiencing this in past year on Netherwing.

Closing.
