### ISSUE TITLE
[Spell][Warrior] Intimidating Shout

### ISSUE THREAD

**Issue by Easyfraggy** [Atlantiss/NetherwingBugtracker#5176]
**Description**: Mobs feared by the second effect have a too high threshold on breaking fear. You can pump damage on the feared target and it will almost never break.

**Current behaviour**: Mobs feared by the second effect have a too high threshold on breaking fear. You can pump damage on the feared target and it will almost never break.

**Expected behaviour**: The damage threshold is known to be high but not that high. Should most likely be reduced slightly

**Server Revision**: Latest

**Comment by Easyfraggy** [comment]
![image](https://user-images.githubusercontent.com/36134067/53299505-85c4bd80-383b-11e9-9257-3a6357997547.png)

**Comment by teddys** [comment]
this has been fixed
