### ISSUE TITLE
[Core][Fall dmg] Dismounting flying mount and took 100% fall dmg

### ISSUE THREAD

**Issue by Easyfraggy** [Atlantiss/NetherwingBugtracker#5177]
**Description**: Took full fall dmg when dismounting close to the ground https://gfycat.com/SneakyPettyCrane 

**Current behaviour**: Took full fall dmg when dismounting close to the ground

**Expected behaviour**: Take fall dmg based from how far you fell

**Server Revision**: 2712

**Comment by The14me** [comment]
Must be fixed with 
''[3417][Core/Player] Fixed a rare edge-case issue with a player having invalid fall information after logging-in onto a flying mount''
