### ISSUE TITLE
[Core][Hostile] Able to attack Draenei in Shattrath

### ISSUE THREAD

**Issue by Easyfraggy** [Atlantiss/NetherwingBugtracker#5178]
**Description**: If you engage in pvp battle, teleport to shattrath right after, you will still be hostile and able to attack random NPCs in Shatt https://gfycat.com/EveryGrotesqueAndeancondor

**Current behaviour**:

**Expected behaviour**: Shouldn't be able

**Server Revision**: 2712

**Comment by Godmatik** [comment]
Unable to reproduce - perhaps this was fixed at some point.
