### ISSUE TITLE
Shadowpine Ripper#16340 sometimes jumps on top of the hut.

### ISSUE THREAD

**Issue by Tenoutoften** [Atlantiss/NetherwingBugtracker#518]
**Description**: 
Shadowpine Ripper#16340(https://db.excalibur.ws/?npc=16340) sometimes jumps on top of the hut, he is supposed to be standing, and walking a little around his spot nearby. Picture of him on top of the hut: https://i.gyazo.com/3b8af1692010d77f3c16acef32ac5e74.png

Entry: 16340, SpawnId - 10, GUIDlow: 62543, coords 75.25, 11.40

**Expected behaviour**: 
I expect him to never jump on top of the roof but just walk a little around his spot

**Server Revision**: 
2050

**Comment by aresbrutus** [comment]
I have checked the retail sniffs we got and it seems he should actually be standing still, not random walking. But nonetheless, it will be fixed in one of the next updates.
