### ISSUE TITLE
[Raid][SSC] Hydross changes to Water too fast

### ISSUE THREAD

**Issue by Easyfraggy** [Atlantiss/NetherwingBugtracker#5180]
**Description**: He currently changes to water before he is even close to the center. He should swap when he is closer to the center.https://gfycat.com/ImpracticalAnyCrownofthornsstarfish 

**Current behaviour**:

**Expected behaviour**: https://youtu.be/Y8aDFOfMY3U?t=337 Changes when he's in the center. You can look at other videos too

**Server Revision**: 2712

**Comment by Easyfraggy** [comment]
https://youtu.be/Y8aDFOfMY3U?t=187

![image](https://user-images.githubusercontent.com/36134067/53299565-27e4a580-383c-11e9-8a18-8e960274697a.png)

**Comment by Tereneckla** [comment]
He doesn't change too fast
