### ISSUE TITLE
[Mage][Spell][Water Elemental] Losing target when trying to cast pet nova and the pet disappears at the same time

### ISSUE THREAD

**Issue by Easyfraggy** [Atlantiss/NetherwingBugtracker#5181]
**Description**: If you attempt to cast a pet nova and hover your mouse over and your pet happens to die/disappears at the same time, you are losing your target. https://gfycat.com/NeedyCircularEchidna 

**Current behaviour**:

**Expected behaviour**: Shouldn't lose your target

**Server Revision**: 2719

**Comment by Godmatik** [comment]
Rev 4018 - can not reproduce, target is not lost 
Probably fixed at some point.
