### ISSUE TITLE
[Core][Mage][Spell][Polymorph] A more powerful spell is already active bug. (and other CCs)

### ISSUE THREAD

**Issue by Easyfraggy** [Atlantiss/NetherwingBugtracker#5182]
**Description**: If I sheep a mob with a max rank sheep, and then try to sheep it again with a lower rank when it has a few seconds left before breaking, it will say a more powerful spell is already active.

**Current behaviour**:

**Expected behaviour**: Should be able to cast a lower rank sheep over a higher rank.

**Server Revision**: 2719

**Comment by Easyfraggy** [comment]
![image](https://user-images.githubusercontent.com/36134067/53299580-74c87c00-383c-11e9-9433-fbbd01693722.png)

**Comment by Zarant** [comment]
Using the classic client as reference, this seems to be working as intended.

**Comment by Tereneckla** [comment]
He means fixed
