### ISSUE TITLE
Hunter frost trap bug upon ressurection.

### ISSUE THREAD

**Issue by dalabu** [Atlantiss/NetherwingBugtracker#5183]
**Description**: When hunter dies and gets ressurected he might still be in combat if someone is in his frost trap that was activated before he died.

**Current behaviour**:

**Expected behaviour**: Hunter shouldnt be in combat upon ressurection even if his trap is still active and affecting someone.

**Server Revision**: 2825

**Comment by The14me** [comment]
rev.3478 Not an issue anymore.
Can be closed.
