### ISSUE TITLE
[Spell][Mage][Invisibility] Invisibility broke again.

### ISSUE THREAD

**Issue by Easyfraggy** [Atlantiss/NetherwingBugtracker#5184]
**Description**: https://gfycat.com/ScarceComplicatedGoa Mobs aggroed me while invis and they shouldn't be able to detect me.

**Current behaviour**:

**Expected behaviour**: Doesn't aggro me while invis.

**Server Revision**: 2765

**Comment by Easyfraggy** [comment]
![image](https://user-images.githubusercontent.com/36134067/53299596-9f1a3980-383c-11e9-9d61-a50b43f994cb.png)

**Comment by Suzaru** [comment]
So while invis the mage should see only targets that are able to see him. Meaning if the mobs are able to detect an invisible mage, he should seem them with the blue "eye"  symbol above their heads. At the moment mobs detecting the invisible mage are invisible to the Caster and hence you have no chance to dodge them
