### ISSUE TITLE
[Spell][Polymorph] immune to sheep under water

### ISSUE THREAD

**Issue by Easyfraggy** [Atlantiss/NetherwingBugtracker#5185]
* **Description**: Paladin was immune to sheep while swimming underwater (no DR) https://gfycat.com/IdealisticWholeAsiansmallclawedotter

**Current behaviour**:

**Expected behaviour**: Shouldn't be immune.

**Server Revision**: 2771

**Comment by devo6969** [comment]
Tried to recreate on the PTR, was unable to. Tried dueling a pally, then opposing faction
