### ISSUE TITLE
[Hunter] Auto-Shot Swing Timer And Haste Effects

### ISSUE THREAD

**Issue by Notmelody** [Atlantiss/NetherwingBugtracker#5186]
[//]: # (Enclose links to things related to the bug using http://wowhead.com or any other TBC database.)
[//]: # (You can use screenshot ingame to visual the issue.)
[//]: # (Write your tickets according to the format:)
[//]: # ([Quest][Azuremyst Isle] Red Snapper - Very Tasty!)
[//]: # ([NPC] Magistrix Erona)
[//]: # ([Spell][Mage] Fireball)
[//]: # ([Npc][Drop] Ghostclaw Lynx)
[//]: # ([Web] Armory doesnt work)
[//]: # (To find server revision type `.server info` command in the game chat.)

**Description**: Haste effects gained during an auto shot swing immediately reduce the remaining swing time. Haste gained during Auto-shots should not reduce the current remaining swing, but should reduce the following swings.

**Current behaviour**: https://streamable.com/gcj86

**Expected behaviour**: https://youtu.be/BT270SIJtLY?t=55  (frame by frame version https://streamable.com/tzl2m)

**Server Revision**: 2825

**Comment by Godmatik** [comment]
Fixed several months ago.

Closing.
