### ISSUE TITLE
[Core][Warsong Gulch] LoS issues

### ISSUE THREAD

**Issue by Easyfraggy** [Atlantiss/NetherwingBugtracker#5188]
**Description**: https://gfycat.com/WetGlossyDarklingbeetle I am fairly certain that this wall shouldn't block LoS

**Current behaviour**:

**Expected behaviour**: Shouldn't block LoS

**Server Revision**: 2771

**Comment by Godmatik** [comment]
Broken image link.
Have heard no LoS complaints about WSG this past year on Netherwing, so likely whatever it is, working as intended.

Closing
