### ISSUE TITLE
[Raid][SSC][Hydross] Adds activate too quickly (still)

### ISSUE THREAD

**Issue by Easyfraggy** [Atlantiss/NetherwingBugtracker#5189]
https://gfycat.com/ReasonableMenacingGoldfishHydross adds are still moving too quickly, after spawning they move after less than 1second and untargetable, when it should be 2-3 seconds and targetable and damageablehttps://youtu.be/FmmSwbEzHk4?t=157

**Comment by Easyfraggy** [comment]
![image](https://user-images.githubusercontent.com/36134067/53299637-3aabaa00-383d-11e9-914e-32c9ab53f0b6.png)

**Comment by devo6969** [comment]
There does seem to be a slight delay on retail compare to what is on the PTR maybe just a second too soon. The warrior hits Demo shout to trigger them. I couldn't find a video of them exact timer on them without someone triggering them so i made a retail BFA video for reference.

PTR - https://www.youtube.com/watch?v=YBTFXvum6ZU
Retail BFA - https://www.youtube.com/watch?v=G_iBJtZN1z8
Retail TBC - https://youtu.be/J1Vph9r5ZnY?t=233

**Comment by Wolffenstein** [comment]
Fixed in rev 3473.
