### ISSUE TITLE
[Spell][Mage] Spellsteal not always stealing the buff (only dispelling)

### ISSUE THREAD

**Issue by Easyfraggy** [Atlantiss/NetherwingBugtracker#5190]
**Description**: Sometimes, you don't receive the buff that you spellstole. In this clip you can see that I didn't get arcane power nor underwater breathing.
  Also, I believe that Group version of buffs (GotW, Arcane brilliance) are replacing single target buffs of longer duration (mark of the wild, arcane intellect) If my own buff is has a longer duration, it shouldn't be replaced. https://gfycat.com/DistantFluidIslandcanary
  **Current behaviour**:
  
  **Expected behaviour**: The buffs should transfer. Buffs should transfer only if mine aren't stronger.
  **Server Revision**: 2785

**Comment by Easyfraggy** [comment]
![image](https://user-images.githubusercontent.com/36134067/53299647-544cf180-383d-11e9-8d86-000aac0ea77f.png)

**Comment by Godmatik** [comment]
All spellsteal related bugs fixed with the aura rework.

Closing
