### ISSUE TITLE
UB 3rd Boss(Swamplord Musel'ek

### ISSUE THREAD

**Issue by Flamelol** [Atlantiss/NetherwingBugtracker#5191]
**Description**: 
traps on the 3rd boss are activated even if you do not enter them

**Server Revision**:

**Comment by Obsolete85** [comment]
Traps don't despawn. Boss casts aimed shot while people are in melee and he 1shots group members.
Focus killed the boss and the bear stayed at 100% and would not take any damage when attacking him.
Group died to reset it and the bear despawned.
