### ISSUE TITLE
([Spell][Rogue] Slice and Dice)

### ISSUE THREAD

**Issue by Roga23** [Atlantiss/NetherwingBugtracker#5193]
**Description**:  Slice and Dice when activated into stealth output of stealth

**Current behaviour**: Same as above

**Expected behaviour**: Spell "Slice and Dice" not should output of stealth when activated into stealth

**Server Revision**:

**Comment by teddys** [comment]
incorrect, slice and dice breaks stealth in tbc

**Comment by Easyfraggy** [comment]
Need some proof to the contrary to reopen.

**Comment by Dusky1** [comment]
He probably mean that if you do fast enough SnD -> stealth it will break ur stealth cuz of spell delay on SnD
