### ISSUE TITLE
Humar the pridelord

### ISSUE THREAD

**Issue by Methelias** [Atlantiss/NetherwingBugtracker#5195]
Hey guys! I just tamed Humar because I heard he got the skill agonizing pain skill, but some reason it doesn't have that skill.

It's kinda annoying because I camped the spawn spot for like 3-4 days. And if Humar is dead the respawn time is like 8-12hrs 

[//]: # (Enclose links to things related to the bug using http://wowhead.com or any other TBC database.)
[//]: # (You can use screenshot ingame to visual the issue.)
[//]: # (Write your tickets according to the format:)
[//]: # ([Quest][Azuremyst Isle] Red Snapper - Very Tasty!)
[//]: # ([NPC] Magistrix Erona)
[//]: # ([Spell][Mage] Fireball)
[//]: # ([Npc][Drop] Ghostclaw Lynx)
[//]: # ([Web] Armory doesnt work)
[//]: # (To find server revision type `.server info` command in the game chat.)

**Description**: 

**Current behaviour**:

**Expected behaviour**: 

**Server Revision**:

**Comment by Manaci** [comment]
He does not
