### ISSUE TITLE
[Core][Spell reflects] Too much batching in spell reflects

### ISSUE THREAD

**Issue by Easyfraggy** [Atlantiss/NetherwingBugtracker#5196]
**Description**: There is too much batching on spell reflects. The damage should go through quickly after being hit by a reflect.You can see how slow it is in this clip, where I re reflect the frostbolt back to the warrior thanks to frost ward. https://gfycat.com/OrdinaryJealousHoneybee Also another bug, after reflecting the spell, you don't see the damage over the person's head, making it seem that it didn't do any damage.

**Current behaviour**:
**Expected behaviour**: Less batching on reflect, the damage after a reflect should be instant, so that if a spell gets reflected twice it actually gets reflected quickly.
**Server Revision**: 2785

**Comment by Easyfraggy** [comment]
![image](https://user-images.githubusercontent.com/36134067/53303498-86754800-386b-11e9-9aa3-1e093f7a47c6.png)

**Comment by totalscrubking** [comment]
i think this may be so people with high ping can still take advantage of mechanics like this
