### ISSUE TITLE
[spell][Vanish] Debuffs aren't properly applied when knocking rogue out of vanish

### ISSUE THREAD

**Issue by Easyfraggy** [Atlantiss/NetherwingBugtracker#5197]
**Description**: I knock off a rogue 1 second after he vanishes with cone of cold, but the slow debuff doesn't apply. (this always happens, it's not that he resisted the slow or something) https://gfycat.com/RectangularConfusedChital 
**Current behaviour**:
  **Expected behaviour**: Slow should be applied.
  **Server Revision**: 2788

**Comment by Easyfraggy** [comment]
![image](https://user-images.githubusercontent.com/36134067/53303506-43b37000-386b-11e9-8390-ec8c369ab127.png)

**Comment by Godmatik** [comment]
Rev 4020

Unable to reproduce
Improved sprint is not making you immune to slow effects either while the buff is active.

Must have been fixed at some point.
