### ISSUE TITLE
[Spell][Distract] Distract removing Mage's invis

### ISSUE THREAD

**Issue by Easyfraggy** [Atlantiss/NetherwingBugtracker#5198]
**Description**: Rogue distract is removing a mage's invis
**Current behaviour**: Rogue distract is removing a mage's invis
**Expected behaviour**: shouldn't remove invis
**Server Revision**: 2840

**Comment by Easyfraggy** [comment]
![image](https://user-images.githubusercontent.com/36134067/53303514-6d6c9700-386b-11e9-9412-b2b31804ff18.png)

**Comment by Wolffenstein** [comment]
Fixed
