### ISSUE TITLE
Shadowpine Ripper#16340 & Shadowpine Witch#16341 don't flee on low hp

### ISSUE THREAD

**Issue by Tenoutoften** [Atlantiss/NetherwingBugtracker#520]
**Description**: 
Shadowpine Ripper#16340 (https://db.excalibur.ws/?npc=16340) & Shadowpine Witch#16341(https://db.excalibur.ws/?npc=16341) don't flee on low HP, they should occasionally flee on low HP https://youtu.be/AflIu9Vlw8c?t=70

**Expected behaviour**: 
They are supposed to flee on low HP. https://youtu.be/AflIu9Vlw8c?t=70

**Server Revision**: 
2050

**Comment by Evolvee** [comment]
fixed in next rev
