### ISSUE TITLE
[Core][Interactions] Gouging a blink isn't working correctly.

### ISSUE THREAD

**Issue by Easyfraggy** [Atlantiss/NetherwingBugtracker#5200]
**Description**: If a rogue gouges a mages blink, the mage should be at the location he blinked and be gouged. https://gfycat.com/SophisticatedElderlyGnat
**Current behaviour**: Blink is used, but doesn't move the player.
**Expected behaviour**: Moves the player.
**Server Revision**:

**Comment by Easyfraggy** [comment]
![image](https://user-images.githubusercontent.com/36134067/53303541-bd4b5e00-386b-11e9-862c-f02388b76d0c.png)

**Comment by Wolffenstein** [comment]
Fixed in rev 3536.
