### ISSUE TITLE
[Core]//[SSC][Lady Vashj] Strider and pillar LoS issues.

### ISSUE THREAD

**Issue by Easyfraggy** [Atlantiss/NetherwingBugtracker#5201]
**Description**: So a lot of us has noticed LoS issues that felt really weird when casting on striders while kiting them around the room. Right now, when a strider is behind a pillar, we get LoS issues and can't finish our cast//start casting.
  I think I figured out why those LoS issues happen and it's because of how this server hitbox on big characters work. There is the same issue with the monster for "Cruel's Intentions", where he is in the small hole, but can't be attacked because of line of sight (It seems like the server looks at the most bottom part of the unit to consider LoS or not) but on retail, you can attack the mob, (the hitbox for LoS isn't completely on the bottom, it takes in account how big the mob is, big monster, you can attack him even if there's a small pillar in front.
  ![image](https://user-images.githubusercontent.com/43510874/52956045-3888ad80-335c-11e9-9b1f-fe1f3962105a.png)
  There was also this issue with #3245
  If you look at retail videos, you never see this LoS issue, people are always able to finish their cast//start casting even if a strider is behind a pillar
  https://youtu.be/7zxfo33PPyI?list=LLAh52rlc4AeX0HeSGIQDZ1Q&t=210
  https://youtu.be/7zxfo33PPyI?list=LLAh52rlc4AeX0HeSGIQDZ1Q&t=341
  https://youtu.be/ZvBAX_RqeFs?list=LLAh52rlc4AeX0HeSGIQDZ1Q&t=134
  Right now, we always have to be mindful of where the strider is and move to make sure our casts don't get LoS when it shouldn't be the case
  
  **Current behaviour**:
  **Expected behaviour**: Hitbox detection for LoS should take into account how tall the enemy is, the hitbox isn't at the foot of the enemy.enemy, I believe it should be towards where the projectiles fly to, so around the upper body
  **Server Revision**: 2806

**Comment by Easyfraggy** [comment]
![image](https://user-images.githubusercontent.com/36134067/53303554-e23fd100-386b-11e9-8d11-28e35aeb7c9f.png)

**Comment by Wolffenstein** [comment]
This was fixed
