### ISSUE TITLE
[SSC][Fathom Lord Karathress] Spit fire totem instantly casts his spell on spawn

### ISSUE THREAD

**Issue by Easyfraggy** [Atlantiss/NetherwingBugtracker#5202]
**Description**: Currently, when the totem is summoned, he spawns and instantly casts his first wave of fireballs.
**Current behaviour**: Currently, when the totem is summoned, he spawns and instantly casts his first wave of fireballs.
**Expected behaviour**: Should spawn and start casting normally. https://youtu.be/146wGV6C0iM?t=51
**Server Revision**: 2825

**Comment by Manaci** [comment]
Fixed
