### ISSUE TITLE
[Professions][Engineering] Specialization change doesnt work correctly

### ISSUE THREAD

**Issue by Digoxin1** [Atlantiss/NetherwingBugtracker#5204]
**Description**: I had 351 Gnomish engineering, I wanted to change to Goblin specialization, so I went to Tanaris where I can unlearn Gnome Spec for 150gold. After that the book gave me the option to learn goblin engi, I clicked on it, and the spec changed to goblin in my spellbook, but i couldnt learn goblin recipes from trainers because i didnt have a membership card. I unlearnt the specialisation again and I dropped engineering, and started it again from scratch. I am still not able to do the prequest what open the Goblin Engineering start quest, but i can learn gnomish recipes from trainers. Im at skill lvl 300.

**Current behaviour**: I can only learn recipes of specialization what i ve chosen first time. I cant redo the prequest when i unlearn spec in Tanaris.

**Expected behaviour**: I should be able to do Gobling Engineering quest line (Goblin Engineering -> The Pledge of Secrecy -> Show Your Work) or i should be able to learn from goblin trainers if i change to that spec.

**Server Revision**: 2825

**Comment by Larinio1** [comment]
can we get this fixed soon please?

**Comment by Wolffenstein** [comment]
Fixed in rev 2933.

**Comment by SlizeTBC** [comment]
Steamwheedle Port Book doesn't let me unlearn gnomish Engineering.

Server Revision: 2967
