### ISSUE TITLE
Battleground que broken if you try to que more then 7 ppl.

### ISSUE THREAD

**Issue by dalabu** [Atlantiss/NetherwingBugtracker#5207]
**Description**: Que gets stuck if you que more then 7 people for the same Battleground. Tried queing different numbers(15,8), only when we drop amount of qued people below 8 we get it poped.

**Current behaviour**:

**Expected behaviour**: You should be able to que Battlegrounds as a raid if number of people does not exceed 15(EOTS,AB) and 10(WSG).

**Server Revision**: 2825

**Comment by pbjtime** [comment]
+1

**Comment by Azalen** [comment]
+1

**Comment by nazarik** [comment]
@Wolffenstein any plans to prioritise this in the nearest future?

**Comment by tsu-1** [comment]
This obviously is a bug, but I think allowing for 10 premade queue would make Battlegrounds die really fast. Not worth to fix really. You have nice example of that on Endless.
