### ISSUE TITLE
[Battleground] Resurrect at enemy base.

### ISSUE THREAD

**Issue by dalabu** [Atlantiss/NetherwingBugtracker#5208]
**Description**: When you lose a base while being in the 30 sec timer for resurrection there is a chance you will still get resurrected even if you lost control of the base.

**Current behaviour**:

**Expected behaviour**: When you loose a base you shouldnt be able to resurrect there and you get moved to the nearest Spirit Healer.

**Server Revision**: 2825

**Comment by The14me** [comment]
Please add some retail proof of that.

**Comment by Godmatik** [comment]
Fixed a while ago, you property teleport to a GY you control now when losing a base.
