### ISSUE TITLE
[Core][Druid](Drums of War) Does not work in shape shifted form

### ISSUE THREAD

**Issue by Mistake33** [Atlantiss/NetherwingBugtracker#5209]
**Description**: 
Drums of War is not working as it should, in shapeshifted form as it says in the Tooltip. Not sure on the other Drums, but this one is not correct.
**Current behaviour**:
Not working in shapeshifted form.
**Expected behaviour**: 
To work properly in shapeshifted form.
**Server Revision**:

**Comment by Evolvee** [comment]
inteded

download https://github.com/nullfoxh/NWTooltipFix
