### ISSUE TITLE
[NPC] Red Dragonhawk Hatchling appears hostile (not duplicate)

### ISSUE THREAD

**Issue by leon12345** [Atlantiss/NetherwingBugtracker#521]
[//]: # (Enclose links to things related to the bug using http://wowhead.com or any other TBC database.)
[//]: # (You can use screenshot ingame to visual the issue.)
[//]: # (Write your tickets according to the format:)
[//]: # ([Quest][Azuremyst Isle] Red Snapper - Very Tasty!)
[//]: # ([NPC] Magistrix Erona)
[//]: # ([Spell][Mage] Fireball)
[//]: # ([Npc][Drop] Ghostclaw Lynx)
[//]: # ([Web] Armory doesnt work)

**Description**: 
https://gyazo.com/0f02a3a86cf603b1b5402395a1b970c9
**Current behaviour**:
appears hostile, cannot be attacked
**Expected behaviour**: 
should be friendly
**Server Revision**: 
2050

**Comment by Evolvee** [comment]
fixed in next revision
