### ISSUE TITLE
[Hunter][Spell] Frost Trap debuff and line of sight issues

### ISSUE THREAD

**Issue by Zarant** [Atlantiss/NetherwingBugtracker#5210]
**Description**: Frost trap rarely works as intended, very often you see enemies skating through the ice without ever getting affected by the slow effect.

**Current behaviour**: Frost trap slow effect is unreliable, depending on terrain elevation, obstacles, game objects and doodads in between the center of the trap and the enemy.

**Expected behaviour**: Frost trap debuff should not have the same line of sight constraints as regular damaging aoe spells like blizzard.

Source: 

https://youtu.be/FAz6E6W4T-I?t=499 - Looking closely at this clip from retail tbc can give us an idea on how to reproduce the intended behavior. 

![trap_los1](https://user-images.githubusercontent.com/26726709/53313154-cbfb3a80-3896-11e9-9417-65d89d8a58e7.png)
![trap_los2](https://user-images.githubusercontent.com/26726709/53313157-cef62b00-3896-11e9-92fd-4c003f0d8362.png)

Even when the priest is clearly out of LoS from the center of the enemy trap, he still gets affected by the frost trap debuff.

**Server Revision**: 2826

**Comment by gunzbngbng** [comment]
I've also noticed that druids can shift in Frost traps to remove the slow for a time.  Only a pure immunity like blessing of freedom should remove frost trap's effect.  Not even clos should break the effect iirc.

**Comment by 4egito** [comment]
@Tereneckla 
Fixed in rev 3276: 
[Core/Auras]: Fixed certain persistent area auras not affecting targets not in line of sight (e.g. Frost Trap)
