### ISSUE TITLE
Karazhan Wooden Door Bug

### ISSUE THREAD

**Issue by Digglez** [Atlantiss/NetherwingBugtracker#5211]
**Description**: 
Karazhan door bugged only for myself, and not the rest of my raid. Happened multiple occasions in different raid groups now

**Current behaviour**:
The wooden door just within the back door of Karazhan gives me an "Invalid Target" response when I try and click on it to open. The raid was cleared except for Netherspite/Nightbane, and I was in the raid for every boss kill.

**Expected behaviour**: 
I expect the door to open.
![capture-kara](https://user-images.githubusercontent.com/47973353/53330318-4e8d0400-3942-11e9-93b5-5c66a7a1537d.PNG)

**Comment by Digglez** [comment]
Also contacted a GM about this issue (Smaily) who asked me to raise this ticket.

**Comment by Easyfraggy** [comment]
Did you try clearing your cache?

**Comment by Digglez** [comment]
I've cleared my cache but kara reset. Can't try it until we clear kara agin now :(

**Comment by Digglez** [comment]
I don't see why an addon would interfere with a door though. addons being superficial to the game itself and the door being a hard coded item within it.

**Comment by Digglez** [comment]
New raid ID - new group. same issue with the door. I cleared my cache and my addons. "Invalid Target"

**Comment by Valmere** [comment]
if it's not addons then it might be your client, there's only 1 guy in my raid group as well that has issues with this door

**Comment by Digglez** [comment]
I've used this client on at least 3 other private servers all without any issues (running kara multiple times on each).

I'm really out of ideas on how to fix this, hence why I raised this ticket. If I had any way to fix this myself without any assistance I would've by now!

**Comment by Cyal** [comment]
Any update on this ? We are down to 2 people that can open the door in our runs. I tried with fresh downloaded client too and it's the same so.

Bump.

**Comment by Cyal** [comment]
Adding https://wowwiki.fandom.com/wiki/Patch_3.2.0_(undocumented_changes), that proves that all through TBC you could open the door without reaching the trigger and was actually fixed in 3.2.

**Comment by Wolffenstein** [comment]
Fixed in rev 3047.
