### ISSUE TITLE
A Burden of Souls broken

### ISSUE THREAD

**Issue by shinmadam** [Atlantiss/NetherwingBugtracker#5212]
[//]: # (Enclose links to things related to the bug using http://wowhead.com or any other TBC database.)
[//]: # (You can use screenshot ingame to visual the issue.)
[//]: # (Write your tickets according to the format:)
[//]: # ([Quest][Azuremyst Isle] Red Snapper - Very Tasty!)
[//]: # ([NPC] Magistrix Erona)
[//]: # ([Spell][Mage] Fireball)
[//]: # ([Npc][Drop] Ghostclaw Lynx)
[//]: # ([Web] Armory doesnt work)
[//]: # (To find server revision type `.server info` command in the game chat.)

**Description**: I kill the mob, not counting.

**Current behaviour**: mob kill no count

**Expected behaviour**: fix plz

**Server Revision**: 203

**Comment by Evolvee** [comment]
rev 2826
