### ISSUE TITLE
[Dungeon] Maraudon sends you to a new instance if the Portal from Scepter of Celebras is used

### ISSUE THREAD

**Issue by ghost** [Atlantiss/NetherwingBugtracker#5213]
**Description**: 
Party started doing Maraudon from the normal orange entrance. Got as far as Princess, wiped, decided that instead of corpserunning the entire dungeon they would jump into the normal orange entrance, jump back out, and use the Scepter Portal to get back faster.
When they did, the found all the bosses and trash had "respawned", and one person who stayed in their corpse could not be found anywhere afterwards. It seems to follow that this was a duplicate, new instance of Maraudon.

**Current behaviour**:
If your party started doing Mara from a regular entrance, they will be sent to a new instance if they go out and reenter through the Scepter Portal.

**Expected behaviour**: 
The party should be simply teleported to the waterfall on their old instance, with the trash cleared etc.

**Server Revision**: 
2825

**Comment by Imperator522** [comment]
Can confirm. Happened to my group too. 4 of us were inside the instance by princess, 5th walked back, used the Scepter, and was in a completely separate instance. We couldn't even summon a new 5th from the inside with a warlock, despite the old 5th member being hearthed.

**Comment by KevinTyrrell** [comment]
Cannot reproduce. Here are the steps I took:
* Entered Mauradon using the scepter while in a group.
* Killed a few mobs.
* Died and released spirit.
* Ran back into purple side instance portral.
* Ran out of the instance back into Desolace.
* Entered Maraudon again using the scepter

Mobs were still dead, did not get placed into a new instance.

**Comment by The14me** [comment]
Rev.3483 cant reproduce.
