### ISSUE TITLE
It is possible to drown on land in Terokkar Forest

### ISSUE THREAD

**Issue by Mikik3jr** [Atlantiss/NetherwingBugtracker#5214]
[//]: # (Enclose links to things related to the bug using http://wowhead.com or any other TBC database.)
[//]: # (You can use screenshot ingame to visual the issue.)
[//]: # (Write your tickets according to the format:)
[//]: # ([Quest][Azuremyst Isle] Red Snapper - Very Tasty!)
[//]: # ([NPC] Magistrix Erona)
[//]: # ([Spell][Mage] Fireball)
[//]: # ([Npc][Drop] Ghostclaw Lynx)
[//]: # ([Web] Armory doesnt work)
[//]: # (To find server revision type `.server info` command in the game chat.)

**Description**: 
Title

**Current behaviour**:
On this location:
![wowscrnshot_022519_150009](https://user-images.githubusercontent.com/43505031/53342514-664a9500-390e-11e9-9b06-d8a6e5ed0593.jpg)
This happens:
![wowscrnshot_022519_150038](https://user-images.githubusercontent.com/43505031/53342526-6ea2d000-390e-11e9-84c5-269384554e14.jpg)

**Expected behaviour**: 
I should not drown on land.

**Server Revision**: 
2825

**Comment by DragunovUA** [comment]
xd
batched

**Comment by Randelung** [comment]
Just came by this position, too. 67.2, 43.7 Terokkar Forest.

**Comment by Wolffenstein** [comment]
Fixed in rev 3198.
