### ISSUE TITLE
[NPC][Burning Steppes] Firegut Ogres

### ISSUE THREAD

**Issue by eryczek1615** [Atlantiss/NetherwingBugtracker#5216]
**Description**:
[Firegut Brute](https://www.wowhead.com/npc=7035/firegut-brute) , [Firegut Mage](https://www.wowhead.com/npc=7034/firegut-ogre-mage)

**Current behaviour**:
https://imgur.com/6yhsNCo
https://imgur.com/1RpJuHi

**Expected behaviour**: 
Shouldn't be xx ogres in one place.

**Server Revision**: 
2825

**Comment by Tenoutoften** [comment]
Already reported https://github.com/Atlantiss/NetherwingBugtracker/issues/4832
