### ISSUE TITLE
[Quest] A Strange Red Key, [Quest] Rescue From Jaedenar

### ISSUE THREAD

**Issue by granoz** [Atlantiss/NetherwingBugtracker#5217]
**Description**: 
The item [Blood Red Key](https://www.wowhead.com/item=13140/blood-red-key), starts the quest [A Strange Red Key](url), to turn in on a npc called  [Captured Arko'narin]([https://www.wowhead.com/npc=11016/captured-arkonarin) inside Jaedenar Shadow Hold at Felwood. The NPC has not respawned in 2 days now.

**Current behaviour**:
The NPC "Captured Arko'narin" [Captured Arko'narin]([https://www.wowhead.com/npc=11016/captured-arkonarin) from the quest "A Strange Red Key" also gives a followup escort quest [Rescue From Jaedenar](https://www.wowhead.com/quest=5203/deprecated-rescue-from-jaedenar) has not respawned for 2 days now, the quest works fine but someone managed to bug it, I've seen some allies killing couple hordes doing the escort quest, after that it seems the NPC did not respawn.

**Expected behaviour**: 
The NPC should respawn if he dies during the escort or the players that are on the escort quest get killed by the opposite faction. The Rp should somehow end, and the NPC respawn if the RP takes longer than x minutes. that would prevent it from being stuck.

**Server Revision**:  2825

**Comment by Evolvee** [comment]
most likely the same respawn core issue as already reported
