### ISSUE TITLE
[Raid][Serpentshrine Cavern][Fathom-Lord Karathress] Fathom-Guard Sharkkis Leeching Throw 

### ISSUE THREAD

**Issue by itsjojotbh** [Atlantiss/NetherwingBugtracker#5218]
[//]: # (Enclose links to things related to the bug using http://wowhead.com or any other TBC database.)
[//]: # (You can use screenshot ingame to visual the issue.)
[//]: # (Write your tickets according to the format:)
[//]: # ([Quest][Azuremyst Isle] Red Snapper - Very Tasty!)
[//]: # ([NPC] Magistrix Erona)
[//]: # ([Spell][Mage] Fireball)
[//]: # ([Npc][Drop] Ghostclaw Lynx)
[//]: # ([Web] Armory doesnt work)
[//]: # (To find server revision type `.server info` command in the game chat.)

**Description**: 
The leeching throw cast by Sharkkis will give spell pushback when it ticks. Additionally it will proc the Water Shield mana restore effect as it deals damage.
**Current behaviour**:
It will tick and drain mana and deal damage and your spell will get pushback as if a melee or ranged attack hit you.
**Expected behaviour**: 
Should just deal damage and drain mana.
**Server Revision**: 
2825

**Comment by Wolffenstein** [comment]
Fixed in rev 3662.
