### ISSUE TITLE
Died in Karazhan and had to log, logged in and in a raid went through the door and it ported me to shattrah dead.

### ISSUE THREAD

**Issue by Vannort86** [Atlantiss/NetherwingBugtracker#5219]
[//]: # (Enclose links to things related to the bug using http://wowhead.com or any other TBC database.)
[//]: # (You can use screenshot ingame to visual the issue.)
[//]: # (Write your tickets according to the format:)
[//]: # ([Quest][Azuremyst Isle] Red Snapper - Very Tasty!)
[//]: # ([NPC] Magistrix Erona)
[//]: # ([Spell][Mage] Fireball)
[//]: # ([Npc][Drop] Ghostclaw Lynx)
[//]: # ([Web] Armory doesnt work)
[//]: # (To find server revision type `.server info` command in the game chat.)

**Description**: 

Died in Karazhan and had to log, logged in and in a raid went through the door and it ported me to Shattrah dead.

**Expected behaviour**: 
Should res me without letting me into the instance.  
**Server Revision**: 
2825

**Comment by Manaci** [comment]
Prob 10 in the instance already and that's why
