### ISSUE TITLE
[Quest][Nagrand] Forge Camp: Forge Camp: Annihilated

### ISSUE THREAD

**Issue by TechnoPrep** [Atlantiss/NetherwingBugtracker#5221]
[//]: # (Enclose links to things related to the bug using http://wowhead.com or any other TBC database.)
[//]: # (You can use screenshot ingame to visual the issue.)
[//]: # (Write your tickets according to the format:)
[//]: # ([Quest][Azuremyst Isle] Red Snapper - Very Tasty!)
[//]: # ([NPC] Magistrix Erona)
[//]: # ([Spell][Mage] Fireball)
[//]: # ([Npc][Drop] Ghostclaw Lynx)
[//]: # ([Web] Armory doesnt work)
[//]: # (To find server revision type `.server info` command in the game chat.)

**Description**: 
You must use the key obtained from the demons to shoot the cannon.
**Current behaviour**:
Overseers do not drop a key to use on the cannons
**Expected behaviour**: 
Overseers should drop a key to use on the cannons to destroy the camps
**Server Revision**: 
2847

**Comment by Jalapan** [comment]
@Wolffenstein this quest is important, since it drops some BIS items before raids.

**Comment by Evolvee** [comment]
this is some new issue

when i reworked the cannons it dropped just fine for me

**Comment by Wolffenstein** [comment]
Should be fixed, please retest and reopen if needed.
