### ISSUE TITLE
Blessing of Sanctuary - 0 damage reduction

### ISSUE THREAD

**Issue by scruffer** [Atlantiss/NetherwingBugtracker#5222]
**Description**:
Blessing of Sanctuary rank 5 is reducing 0 damage from enemy hits
 https://puu.sh/CRUJ4/50c577cc35.jpg
edit~ Greater Blessing of Sanctuary rank 2 is also bugged - 0 reduction
https://puu.sh/CRUWo/8f17c6f514.jpg
**Current behaviour**: Blessing of Sanctuary rank 5 has lost all damage reduction qualities in the recent changes
edit~ Greater Sanctuary is also bugged - 0 reduction
**Expected behaviour**:  I don't know the exact math on how much it should reduce, but it's not doing anything right now - the damage taken should be much, much less than what is shown here.
>normal sanctuary
https://puu.sh/CRUJ4/50c577cc35.jpg
greater sanctuary
https://puu.sh/CRUWo/8f17c6f514.jpg
**Server Revision**: 2843

**Comment by Wolffenstein** [comment]
Fixed in rev 2844.
