### ISSUE TITLE
[Spell][Rogue] Deadly Throw

### ISSUE THREAD

**Issue by SlizeTBC** [Atlantiss/NetherwingBugtracker#5224]
**Description**: Deadly Throw interrupts Spellcasts without PvP Gloves

**Current behaviour**: Deadly Throw interrupts Spellcasts without PvP Gloves

**Expected behaviour**: Shouldnt interrupt any Spellcast without PvP Gloves

https://imgur.com/a/JwpyqmR

**Comment by Wolffenstein** [comment]
Fixed in rev 2846.
