### ISSUE TITLE
[Spell] Blessing of Sanctuary 5 damage reduce(after recent updates)

### ISSUE THREAD

**Issue by zodis6** [Atlantiss/NetherwingBugtracker#5226]
**Description**: Blessing of Sanctury 5 (prob all levels) doesnt reduce any magic/dots/auras damage

**Current behaviour**: Blessing of Sanctuary rank 5 doesnt reduce magic/dot/auras dmg taken 

**Expected behaviour**: Blessing of Sanctuary rank 5 should reduce same as phys dmg acording to tooltip thats say *Places a Blessing on the friendly target, reducing damage dealt from all sources by up to 80 for 10min.*

**Server Revision**: 2849

![wowscrnshot_022619_161238](https://user-images.githubusercontent.com/48017449/53415657-d1fe3200-39e2-11e9-873b-b6fdf5aabd62.jpg)
![wowscrnshot_022619_161028](https://user-images.githubusercontent.com/48017449/53415660-d296c880-39e2-11e9-9241-02195118e86a.jpg)
![wowscrnshot_022619_160829](https://user-images.githubusercontent.com/48017449/53415662-d32f5f00-39e2-11e9-9d55-80b94dbc1c0a.jpg)
![wowscrnshot_022619_160757](https://user-images.githubusercontent.com/48017449/53415667-d4608c00-39e2-11e9-855e-2847c272629d.jpg)
![wowscrnshot_022619_152650](https://user-images.githubusercontent.com/48017449/53415714-f2c68780-39e2-11e9-949f-658eea4b782c.jpg)

**Comment by Jalapan** [comment]
@Wolffenstein

**Comment by Wolffenstein** [comment]
Does not affect DoTs/Bleeds.  This is intended.

**Comment by zodis6** [comment]
how about thorns/ret aura and direct spells?

**Comment by Wolffenstein** [comment]
It works for direct spells, does not work for damage shields (Thorns/Retri Aura).
