### ISSUE TITLE
[Spell][Alchemy] [Transmute: Arcanite]

### ISSUE THREAD

**Issue by SimsenFriborg** [Atlantiss/NetherwingBugtracker#5228]
[Spell][Alchemy] [Transmute: Arcanite]

**Description**: 
Transmute: Arcanite shares cooldown with Transmute: Gold and Transmute: Truesilver. The cooldown timer is not shown on the Transmute: Arcanite spell, but it is shown on the other two spells.

**Current behaviour**:
Transmute: Arcanite has cooldown
Transmute: Arcanite shares cooldown with Transmute: Gold and Transmute: Truesilver

**Expected behaviour**: 
Transmute: Arcanite should not have any cooldown cf.:
https://wowwiki.fandom.com/wiki/Transmute:_Arcanite

**Server Revision**:
2850

**Comment by Drayo** [comment]
https://github.com/Atlantiss/NetherwingBugtracker/issues/4885

Sidenote, if you transmute Arcanite first, Pirmal Might is going on CD, if you do Primal first you can  transmute Arcanite after.

**Comment by Wolffenstein** [comment]
I removed the cooldown.
