### ISSUE TITLE
Withered Basidium - Zangarmarsh quest item

### ISSUE THREAD

**Issue by Erodraeda** [Atlantiss/NetherwingBugtracker#5229]
[//]: # (Enclose links to things related to the bug using http://wowhead.com or any other TBC database.)
[//]: # (You can use screenshot ingame to visual the issue.)
[//]: # (Write your tickets according to the format:)
[//]: # ([Quest][Azuremyst Isle] Red Snapper - Very Tasty!)
[//]: # ([NPC] Magistrix Erona)
[//]: # ([Spell][Mage] Fireball)
[//]: # ([Npc][Drop] Ghostclaw Lynx)
[//]: # ([Web] Armory doesnt work)
[//]: # (To find server revision type `.server info` command in the game chat.)

**Description**: 
Item Withered Basidium (24483) that starts the alliance quest for the item is dropping for horde players, where only the horde version (24484) should drop.
**Current behaviour**:
24483 is dropping for horde, instead of only 24484
**Expected behaviour**: 
24483 should only drop for alliance, and 24484 for horde. not both for both.
**Server Revision**: 2850

**Comment by The14me** [comment]
Rev.3478 think its a fixed, but worth a check.
