### ISSUE TITLE
[NPC] double Jailer Estons

### ISSUE THREAD

**Issue by DarthNekr0s** [Atlantiss/NetherwingBugtracker#523]
**Description**:  this npc in durnholde keep has spawned twice at the same time

**Current behaviour**: two spawns up at once

**Expected behaviour**:  should only be one version of him. also not sure if he's supposed to be in the building that doesn't contain quest mob Drull

**Server Revision**:  2050

![wowscrnshot_092518_230050](https://user-images.githubusercontent.com/16113944/46016571-80423a80-c118-11e8-931c-dfe8d0f4fb12.jpg)

**Comment by Evolvee** [comment]
fixed in next rev
