### ISSUE TITLE
Nightbanes fear causing people to clip through the wall.

### ISSUE THREAD

**Issue by DomitrekIndustries** [Atlantiss/NetherwingBugtracker#5230]
**Description**: 
We killed nightbane last night however on several attempts we had a single rdps constantly getting feared through the dome and into attumen's room where he would die.
**Current Behaviour**
https://clips.twitch.tv/SucculentCarefulSalamanderDansGame
**Expected behaviour**: 
As far as i know, people shouldnt clip through walls when feared
**Server Revision**: 
2850

**Comment by Tereneckla** [comment]
6355
