### ISSUE TITLE
[Spell][Shaman] Chain Heal double dipping in +healing after last update

### ISSUE THREAD

**Issue by Brasso** [Atlantiss/NetherwingBugtracker#5231]
[//]: # (Enclose links to things related to the bug using http://wowhead.com or any other TBC database.)
[//]: # (You can use screenshot ingame to visual the issue.)
[//]: # (Write your tickets according to the format:)
[//]: # ([Quest][Azuremyst Isle] Red Snapper - Very Tasty!)
[//]: # ([NPC] Magistrix Erona)
[//]: # ([Spell][Mage] Fireball)
[//]: # ([Npc][Drop] Ghostclaw Lynx)
[//]: # ([Web] Armory doesnt work)
[//]: # (To find server revision type `.server info` command in the game chat.)

**Current behaviour**:
Heals for almost double healing wave, rank 4 CH heals for 4k and crits for over 6k.

![image](https://user-images.githubusercontent.com/44345420/53442541-cd993f80-3a09-11e9-9a54-170c951f8a0b.png)

**Expected behaviour**: 
Not even close to this much.
**Server Revision**: 
2850

**Comment by Wolffenstein** [comment]
Fixed in rev 2851 (also on live rn already).
