### ISSUE TITLE
[Spell][Shaman] Flametongue Weapon not scaling with spell power

### ISSUE THREAD

**Issue by hitbutton** [Atlantiss/NetherwingBugtracker#5233]
**Description**: Flametongue Weapon is doing too little damage since the recent changes to spellpower coefficients.

**Current behaviour**: Flametongue Weapon imbue does not appear to be gaining any benefit from spellpower, doing only the base damage from weapon speed.

**Expected behaviour**: Flametongue Weapon should benefit from spellpower at a 10% coefficient for each proc.
Source: https://wowwiki.fandom.com/wiki/Flametongue_Weapon?oldid=1225158

**Server Revision**: 2850

**Comment by Wolffenstein** [comment]
Fixed in rev 2851.
