### ISSUE TITLE
Deep Borer Aren't Skinnable in Maradoun

### ISSUE THREAD

**Issue by Vartonis** [Atlantiss/NetherwingBugtracker#5234]
http://classicdb.ch/?npc=11789#skinning skinnable, should yield thick leather/thick hides.

 located throughout maurdon, especially in the caverns after you get rod. 

**Description**: Deep Borers should be skinnable, and yield thick leather or hides. Currently unable to be skinned. 

**Current behaviour**: Not skinnable

**Expected behaviour**: Skinnable; just checkedon ND they are skinnable, and on retail NA server, also skinnable still there. 

**Server Revision**:

**Comment by ircfelix** [comment]
ND is no valid source. Check old wowhead comments to see if they are skinable or not

**Comment by Vartonis** [comment]
I linked you the loot table and went on my retail account. They are
skinnable there as well.

**Comment by ircfelix** [comment]
Classicdb is a private Server loot table, so not valid. I am not sure how the staff handles retail sources.
Try this when looking for sources:

https://forum.atlantiss.eu/netherwing/topic/126-quick-how-to-search-and-find-sources-for-bug-reports/

**Comment by Vartonis** [comment]
These were skinnable up till cataclysm patch. Then "worm" became their
creature title. You can't see what they drop for skins on modern wowhead
because as a worm they are no longer skinnable. They were changed for
hunter taming and pet talent trees.

The way back machine goes to modern wow head saying there's a current
version.

https://classicdb.ch/?npc=11789 shows them as skinnable - every single data
base (yes for private servers) shows them as skinnable. But, all beasts
were skinnable in Vanilla and TBC. Classicdb also imported 99% of the stuff
before ZAM was formed and the old info was lost. This really should be
considered accurate.

**Comment by The14me** [comment]
https://classic.wowhead.com/npc=11789/deep-borer
No skinning/not a bug.
Can be closed.
