### ISSUE TITLE
[NPC] "Arikara" [Thousand Needles] 

### ISSUE THREAD

**Issue by aoses1** [Atlantiss/NetherwingBugtracker#5235]
**Description**: 

Arikara, the spirit of Vengeance that sometimes terrorizes the Tauren of Thousand Needles, also knows an impressive trick: when you call him (via Call Pet or when you dismount), he appears in a puff of smoke! Everyone in the area, not just the hunter, can see the smoke and hear the accompanying deep rumble.
This windserpent is summoned via a Horde quest, but can be tamed by Alliance once he's been summoned.

**Current behaviour**:
The npc cannot be tamed at all by any means.

**Expected behaviour**: 

A hunter should be able to tame this npc and have the unique special behavior this pet has.
Which is appearing in a puff of smoke everytime you summon it.
http://web.archive.org/web/20080213042706/http://petopia.brashendeavors.net/html/articles/special_qualities.shtml
No other wind serpent pet has this behaviour.

**Comment by Evolvee** [comment]
i made it not tamable intentionally as it was causing issues with summoning the NPC/breaking the event after

**Comment by Evolvee** [comment]
on the other hand, i strongly doubt it would have the "puff" smoke on NW as I added it via script and the tamed NPC wouldnt have that
