### ISSUE TITLE
Paladin Class Quest - True Masters of the Light

### ISSUE THREAD

**Issue by wadde006** [Atlantiss/NetherwingBugtracker#5236]
I've completed the requirements of this quest twice now by killing Aurius and the mobs he spawns after dousing the flame.  But, the quest doesn't show as complete in my quest log and I can't turn it in.  I've got screenshots of the mobs and boss down.  Also, I cleared cache before beginning quest the second time.

![wowscrnshot_022619_231903](https://user-images.githubusercontent.com/48043624/53468471-08a66d80-3a20-11e9-8807-151980d487e4.jpg)
![wowscrnshot_022619_231931](https://user-images.githubusercontent.com/48043624/53468472-08a66d80-3a20-11e9-8f02-71123009f91f.jpg)
![wowscrnshot_022619_231934](https://user-images.githubusercontent.com/48043624/53468473-08a66d80-3a20-11e9-8266-a2ff06e66b46.jpg)
![wowscrnshot_022619_231859](https://user-images.githubusercontent.com/48043624/53468480-0f34e500-3a20-11e9-8185-daa6d6b03de8.jpg)
![wowscrnshot_022619_231900](https://user-images.githubusercontent.com/48043624/53468481-0f34e500-3a20-11e9-94d8-f31688185c74.jpg)
![wowscrnshot_022619_231902](https://user-images.githubusercontent.com/48043624/53468482-0fcd7b80-3a20-11e9-9c51-1b4c30b30d87.jpg)
![wowscrnshot_022619_231732](https://user-images.githubusercontent.com/48043624/53468483-0fcd7b80-3a20-11e9-8c5b-e8b8d587918d.jpg)
![wowscrnshot_022619_231746](https://user-images.githubusercontent.com/48043624/53468484-0fcd7b80-3a20-11e9-8b10-20986a1e625b.jpg)
![wowscrnshot_022619_231846](https://user-images.githubusercontent.com/48043624/53468485-0fcd7b80-3a20-11e9-98aa-c1b48c288bac.jpg)

**Comment by tsu-1** [comment]
Duplicate.
