### ISSUE TITLE
[Rogue][Spell] Shadowstep not consistent

### ISSUE THREAD

**Issue by fantom8** [Atlantiss/NetherwingBugtracker#5238]
**Description**: Shadowstep sometimes doesn't place the user behind the target

**Current behaviour**: Sometimes the user will be placed inside of the target instead of behind it when using Shadowstep. This results in instant detection and breaking of stealth when the target is an NPC. This can happen even if the target's back is not up against a wall.

**Expected behaviour**: Shadowstep should place the user on the target's back, slightly behind them and far enough that an NPC won't instantly attack the user out of stealth before an action can be queued.

**Server Revision**:  2851

**Comment by fantom8** [comment]
Did some more testing, I think it happens more often (perhaps always) on slight inclines.

Example here: https://i.imgur.com/pLkPWec.jpg

**Comment by fantom8** [comment]
Another spot where it happened: https://i.imgur.com/EV2zmLh.jpg

**Comment by Greytt** [comment]
Here's a video of mobs getting me out of stealth just as I shadow step : https://www.youtube.com/watch?v=Cbx1QFWHqDI&hd=1

Note, this happens in arena VS warlocks too. I can shadow step + sap macro the warlock and the pet will hit me the exact time as I land resulting in me not getting sap off. I could understand if they see me after sap goes off but not the same second I land.

**Comment by Easyfraggy** [comment]
Players, NPC's and pets have stealth detection slightly behind them also - as they should - but stealth detection should be in ticks right? So not constant - So if you shadowstep you shouldn't get detected untill the next detection check. However this post @Greytt is Offtopic - you should make a seperate issue for this problem. It has nothing to do with the OP.
