### ISSUE TITLE
[NPC] Defias Pillager has incorrect sound effect for attacking

### ISSUE THREAD

**Issue by Mikik3jr** [Atlantiss/NetherwingBugtracker#524]
[//]: # (Enclose links to things related to the bug using http://wowhead.com or any other TBC database.)
[//]: # (You can use screenshot ingame to visual the issue.)
[//]: # (Write your tickets according to the format:)
[//]: # ([Quest][Azuremyst Isle] Red Snapper - Very Tasty!)
[//]: # ([NPC] Magistrix Erona)
[//]: # ([Spell][Mage] Fireball)
[//]: # ([Npc][Drop] Ghostclaw Lynx)
[//]: # ([Web] Armory doesnt work)

**Description**: 
Defias Pillagers don't have their correct audio when they hit.
**Current behaviour**:
When Defias Pillager attacks with their staff it gives a sword hit sound (or axe?) instead of a staff.
**Expected behaviour**: 
They should have staff sound when they melee hit.
**Server Revision**: 
2050

**Comment by Evolvee** [comment]
is this even server-side?

**Comment by Wolffenstein** [comment]
no
