### ISSUE TITLE
[//]: # ([Quest][Stranglethorn Vale]The Curse of the Tides)

### ISSUE THREAD

**Issue by alreadyd3ad** [Atlantiss/NetherwingBugtracker#5243]
**Description of Bug**: Stone of the Tides [does not interact](https://imgur.com/gallery/42WIlsY) with Catelyn's Blade properly and does not summon Gazban. 

**Expected Behavior**: Stone of the Tides recognizes Catelyn's Blade in the inventory and summons Gazban upon being able to interact with the Stone. As the Stone does not work with the blade as intended the quest is currently broken.

**Comment by Evolvee** [comment]
it was a 1-time issue
I dont see any reason it shouldnt work server-side.

will add another safety prevention in rev 2929

**Comment by Tompok** [comment]
Today at Karazhan, the issue remains. Altar is not clickable, so the NPC cant be summoned, and the quest cant be completed.
