### ISSUE TITLE
Priest Dispell Protection Broken

### ISSUE THREAD

**Issue by Luzzarax** [Atlantiss/NetherwingBugtracker#5244]
Priest talents "Pain Suppression" and "Silent resolve" together provide 85% Dispell protection which is an insane amount. however it is not working. I have done extensive testing in PvP battlegrounds. here is some video footage to prove my point. PLEASE watch both videos. i hope this helps PROVE that this is broken and needs to be fixed.

Video #1 https://youtu.be/GDKADsvt23A

Video #2 https://youtu.be/7VfzIBwGBUw

Respectfully,
Luzzarax

**Comment by Valmere** [comment]
second vid your pain supp is dispelled right off the bat, but you did manage to resist the last one when it tried removing shadow protection

actually it happens in the first vid too

**Comment by Wolffenstein** [comment]
Fixed in rev 2852.

**Comment by Luzzarax** [comment]
so @ 85% dispell protection you think this is how quickly and easily all my
buffs should be dispelled? something is not right ive spoken to other disc
priests they agree. yet when i try and dispell a faerie fire it takes 4 or
5 dispells

**Comment by Frama1** [comment]
Pain Suppression  resistance to dispell mechanics broken again.
It has been broken for many months, could you check it yourself please.

**Comment by Tereneckla** [comment]
Pain Suppression dispel resistance definitely is broken.
