### ISSUE TITLE
Quest  Guardians of the altar Winterspring

### ISSUE THREAD

**Issue by chucklezz11** [Atlantiss/NetherwingBugtracker#5245]
[//]: # (Enclose links to things related to the bug using http://wowhead.com or any other TBC database.)
[//]: # (You can use screenshot ingame to visual the issue.)
[//]: # (Write your tickets according to the format:)
[//]: # ([Quest][Azuremyst Isle] Red Snapper - Very Tasty!)
[//]: # ([NPC] Magistrix Erona)
[//]: # ([Spell][Mage] Fireball)
[//]: # ([Npc][Drop] Ghostclaw Lynx)
[//]: # ([Web] Armory doesnt work)
[//]: # (To find server revision type `.server info` command in the game chat.)

**Description**: 

**Current behaviour**:

**Expected behaviour**: 

**Server Revision**:

**Comment by chucklezz11** [comment]
https://www.youtube.com/watch?v=FgSLjneOUeI suppose to be working like this in here she gets on the otherside of the altar and doesnt spawn any ghosts to talk with etc.. basicly gets stuck when she ask u to light the altar of elune

**Comment by DragunovUA** [comment]
#1966 #4299

**Comment by Evolvee** [comment]
https://github.com/Atlantiss/NetherwingBugtracker/issues/4299
