### ISSUE TITLE
Mage Talent Ignite/Blast Wave

### ISSUE THREAD

**Issue by SlowxP** [Atlantiss/NetherwingBugtracker#5246]
[//]: # (Enclose links to things related to the bug using http://wowhead.com or any other TBC database.)
[//]: # (You can use screenshot ingame to visual the issue.)
[//]: # (Write your tickets according to the format:)
[//]: # ([Quest][Azuremyst Isle] Red Snapper - Very Tasty!)
[//]: # ([NPC] Magistrix Erona)
[//]: # ([Spell][Mage] Fireball)
[//]: # ([Npc][Drop] Ghostclaw Lynx)
[//]: # ([Web] Armory doesnt work)
[//]: # (To find server revision type `.server info` command in the game chat.)

**Description**: 
Ignite should be applied from all fire damage crits.
**Current behaviour**:
Does not apply when criting with Blast Wave
**Expected behaviour**: 
Should be procing ignite with blast wave crit also tested with flamestrike just to see if it had to something with it beeing aoe but works as it should.
**Server Revision**: 
2851

**Comment by SlowxP** [comment]
nvm it was working u just cant see the debuff on the first ignite tick

**Comment by SlowxP** [comment]
Accualy reopening found out that Blast Wave only applies one ignite if crits on more then one mob i would gues it has also something to do with https://github.com/Atlantiss/NetherwingBugtracker/issues/5157 maybe? dunno.

**Comment by Godmatik** [comment]
I am getting ignite with each target I critical strike on with AoE fire abilities.

Closing.
