### ISSUE TITLE
[Spell][Warlock] Eye of Kilrog

### ISSUE THREAD

**Issue by Moryjani** [Atlantiss/NetherwingBugtracker#5247]
**Description**: The Eye of Killrog can deal autoattack damage to players. 

**Current behaviour**: Moving close to an enemy player allows them to be attacked and dealt damage.

**Expected behaviour**: The spell should not be able to deal damage.

**Server Revision**: 2851

**Comment by Wolffenstein** [comment]
Fixed in rev 2856.
