### ISSUE TITLE
[Class][Rogue] Cheath Death + Absorbed Damage

### ISSUE THREAD

**Issue by Realnairoby** [Atlantiss/NetherwingBugtracker#5248]
[//]: # (Enclose links to things related to the bug using http://wowhead.com or any other TBC database.)
[//]: # (You can use screenshot ingame to visual the issue.)
[//]: # (Write your tickets according to the format:)
[//]: # ([Quest][Azuremyst Isle] Red Snapper - Very Tasty!)
[//]: # ([NPC] Magistrix Erona)
[//]: # ([Spell][Mage] Fireball)
[//]: # ([Npc][Drop] Ghostclaw Lynx)
[//]: # ([Web] Armory doesnt work)
[//]: # (To find server revision type `.server info` command in the game chat.)

**Description**: 
Cheat Deaths interaction with absorbed damage.
**Current behaviour**:
If an attack that would normally kill you is completly absorbed by any source, e.g. priests shield, cheat death will still procc.
![cheat death 2](https://user-images.githubusercontent.com/46440087/53528255-6b177080-3ae9-11e9-9146-5cdb72e8a3aa.jpg)
![cheat death1](https://user-images.githubusercontent.com/46440087/53528257-6b177080-3ae9-11e9-962b-6df91b5dac5f.jpg)

**Expected behaviour**: 
Cheat Death: You have a 100% chance that an attack which would otherwise kill you will instead reduce you to 10% of your maximum health. In addition, all damage taken will be reduced by up to 90% for 3 sec (modified by resilience). This effect cannot occur more than once per minute. (http://db.excalibur.ws/?spell=31230)

Cheat Death should only procc if the attack would kill you. A fully absorbed attack won't kill the rogue nor damage him at all, thus Cheat Death shouldn't procc. 

**Server Revision**: 
2851

**Comment by Wolffenstein** [comment]
Fixed in rev 2856.
