### ISSUE TITLE
Rage boken...

### ISSUE THREAD

**Issue by kaybye** [Atlantiss/NetherwingBugtracker#5249]
as im leveling my prot warrior i noticed rage isnt being built from being attacked.... can we fix or hey maybe just give rogues only 50 energy and cut the mana pool of casters and just have everyone playing on one leg because not building rage while being attacked is a huge part of warriors building rage

**Comment by Realnairoby** [comment]
It works completly fine and as intended. Provide some evidence like screenshots if you think something is bugged.

**Comment by Easyfraggy** [comment]
Rage formula is working perfectly fine. Supply some evidence - possibly bugged UI?
