### ISSUE TITLE
Polymorphed Mob Reset

### ISSUE THREAD

**Issue by ttghnw** [Atlantiss/NetherwingBugtracker#525]
[//]: # (Enclose links to things related to the bug using http://wowhead.com or any other TBC database.)
[//]: # (You can use screenshot ingame to visual the issue.)
[//]: # (Write your tickets according to the format:)
[//]: # ([Quest][Azuremyst Isle] Red Snapper - Very Tasty!)
[//]: # ([NPC] Magistrix Erona)
[//]: # ([Spell][Mage] Fireball)
[//]: # ([Npc][Drop] Ghostclaw Lynx)
[//]: # ([Web] Armory doesnt work)

**Description**: **Current behaviour**:
When you aggro a mob and remain in it's spawn area i.e. (fighting another mob whilst one is sheeped), provokes a too easy reset of the mob on the poly break that would typically require moving away further.
**Expected behaviour**: 
would typically require moving away further.

Tested on azure and bloodmyst isles

**Server Revision**:

**Comment by Easyfraggy** [comment]
Could you possibly rewrite this and give more detail? Possibly need someone to translate.

**Comment by Easyfraggy** [comment]
Should be fixed. Please retest and reopen if not.
