### ISSUE TITLE
PvP daily 15 arena and bgs played doesnt reset anymore

### ISSUE THREAD

**Issue by FIXTHISFASTERRR** [Atlantiss/NetherwingBugtracker#5251]
[//]: # (Enclose links to things related to the bug using http://wowhead.com or any other TBC database.)
[//]: # (You can use screenshot ingame to visual the issue.)
[//]: # (Write your tickets according to the format:)
[//]: # ([Quest][Azuremyst Isle] Red Snapper - Very Tasty!)
[//]: # ([NPC] Magistrix Erona)
[//]: # ([Spell][Mage] Fireball)
[//]: # ([Npc][Drop] Ghostclaw Lynx)
[//]: # ([Web] Armory doesnt work)
[//]: # (To find server revision type `.server info` command in the game chat.)

**Description**: 

**Current behaviour**:
The pvp daily and BG daily games played doesn't reset anymore so u can do it only once per week, also u dont get 2 points for arena win or 1 point for arena lose after the daily games anymore, dont know exaclty when this broke
**Expected behaviour**: 

**Server Revision**:

**Comment by Wolffenstein** [comment]
Server was offline during reset time...
