### ISSUE TITLE
Seal of Blood crit procs not proccing vengeance talent

### ISSUE THREAD

**Issue by Nehansen** [Atlantiss/NetherwingBugtracker#5252]
**Description**: 

The blood elf paladin only spell, Seal of Blood, does not grant a stack of the paladin talent, Vengeance, when proccing on a crit

**Current behaviour**:

SoB crits does not proc vengeance talent

**Expected behaviour**: 

SoB crit procs SHOULD proc vengeance talent

**Server Revision**:

**Comment by Tereneckla** [comment]
Fixed
