### ISSUE TITLE
[spell][Druid] Aquatic form

### ISSUE THREAD

**Issue by linxz1** [Atlantiss/NetherwingBugtracker#5253]
[//]: # (Enclose links to things related to the bug using http://wowhead.com or any other TBC database.)
[//]: # (You can use screenshot ingame to visual the issue.)
[//]: # (Write your tickets according to the format:)
[//]: # ([Quest][Azuremyst Isle] Red Snapper - Very Tasty!)
[//]: # ([NPC] Magistrix Erona)
[//]: # ([Spell][Mage] Fireball)
[//]: # ([Npc][Drop] Ghostclaw Lynx)
[//]: # ([Web] Armory doesnt work)
[//]: # (To find server revision type `.server info` command in the game chat.)

**Description**:
Switching to aquatic form while drowning will not stop the effect. You will drown and die anyway.

**Current behaviour**:
Aquatic form will not stop drowning effect.

**Expected behaviour**:
Aquatic form should allow you do breath underwater and stop the effect regardless.

**Server Revision**: 2856

**Comment by Valmere** [comment]
just tested in darnassus, works fine for me. tried:

- switching in and out with a breath bar
- letting the breath bar go all the way down and tried to drown myself

both times switching back into form worked fine

**Comment by linxz1** [comment]
Hmm thats odd, Ill be sure to post again if I can recreate it!

**Comment by PotatoTroll** [comment]
I had the same bug a few days ago in BFD dungeon if I remember correctly. The other druid said he also had this bug before.

**Comment by Godmatik** [comment]
Can't reproduce and have not heard of anyone coming across this issue in the past year on Netherwing.

Will close for now.
