### ISSUE TITLE
Able to stack up to 9 different food buffs!

### ISSUE THREAD

**Issue by Manaci** [Atlantiss/NetherwingBugtracker#5254]
![image](https://user-images.githubusercontent.com/26745981/53597755-4384de80-3ba3-11e9-9421-2a00bfa27a96.png)

**Description**
Right now you can stack every single 10 minute food buff with each other + any "Well Fed" food buff. They all also stack with normal buffs/flasks/elixirs etc.

**Current Behavior**
All of these food buffs stack
https://db.excalibur.ws/?spell=18194#triggered-by (8 MP5)
https://db.excalibur.ws/?spell=18222#triggered-by (6 HP5)
https://db.excalibur.ws/?spell=18191#triggered-by (10 Stamina)
https://db.excalibur.ws/?spell=18192#triggered-by (10 Agility)
https://db.excalibur.ws/?spell=18193#triggered-by (10 Spirit)
https://db.excalibur.ws/?spell=18141#triggered-by (Another 10 Spirit)
https://db.excalibur.ws/?spell=22730#triggered-by (10 Intellect)
https://db.excalibur.ws/?spell=18125#triggered-by (10 Strength)
Any "Well Fed" food buff

**Expected Behavior**
You should only be able to have a single food buff on you at all times, no matter the duration or form.

**Proof**
https://www.wowhead.com/item=13931/nightfin-soup#comments
https://web.archive.org/web/20071102224227/http://wow.allakhazam.com/db/item.html?witem=13934
http://web.archive.org/web/20070102022044/http://www.thottbot.com/?i=5184

**Further Information**
I noticed that there was a bugtracker about the initial problem of 2 food buffs stacking here https://github.com/Atlantiss/NetherwingBugtracker/issues/2400
but it dosn't really show the possibilities of buff stacking that this bug can achieve so I decided to make an updated and current one now.

**Server Revision: 2856**

**Comment by Brasso** [comment]
Nightfin soup DID stack with Well fed food buff back then but was patched later, which looks like it was 2.2.3 according to the comments. Can't speak for the other foods though.

**Comment by Manaci** [comment]
> 
> 
> Nightfin soup DID stack with Well fed food buff back then but was patched later, which looks like it was 2.2.3 according to the comments. Can't speak for the other foods though.
> 
> edit: I also kinda like it, it reminds me of the pot/elixir stacking you could do as well.

The Allakhazam one suggests that it was even earlier though (April 25th, 2007)
There's also the comment over it that says the food buff has been replaced with the "Well Fed" MP5 food buff, suggesting that they were overriding eachother (1st March, 2007, 2.0.8).
The 2.2.3 comment just looks like someone who thought it was still working like it was at release, and quickly edited that it had been patched a while ago.

**Comment by Wolffenstein** [comment]
Fixed in rev 2900.
