### ISSUE TITLE
[Core][Spell] Can't summon to TK balcony or inside

### ISSUE THREAD

**Issue by veekk** [Atlantiss/NetherwingBugtracker#5255]
**Description**:  "Can't use that here" for summon like this

**Current behaviour**: Impossible to summon for TK

**Expected behaviour**: Should be possible, 'cause lot of quests allowed to get'em from 68, e.g. [2nd 3rd keys](http://db.hellfire-tbc.com/?quest=9832) requires 68lvl, and next one [bm kara key](http://db.hellfire-tbc.com/?quest=9836) allowed from 69th lvl, but fly mount need 70th if u're not druid, also [this](http://db.hellfire-tbc.com/?quest=10705) req only 68

**Server Revision**: 2856

**Comment by Easyfraggy** [comment]
summons are disabled in entire netherstorm like they were in 2.0 patch.
