### ISSUE TITLE
[Core] Rooted/slowed mobs in dungeons charging up multiple attack swings for when reaching melee.

### ISSUE THREAD

**Issue by b15andga** [Atlantiss/NetherwingBugtracker#5256]
[//]: # (Enclose links to things related to the bug using http://wowhead.com or any other TBC database.)
[//]: # (You can use screenshot ingame to visual the issue.)
[//]: # (Write your tickets according to the format:)
[//]: # ([Quest][Azuremyst Isle] Red Snapper - Very Tasty!)
[//]: # ([NPC] Magistrix Erona)
[//]: # ([Spell][Mage] Fireball)
[//]: # ([Npc][Drop] Ghostclaw Lynx)
[//]: # ([Web] Armory doesnt work)
[//]: # (To find server revision type `.server info` command in the game chat.)

**Description**: 
Outland Dungeons. I, frost mage, get aggro -> nova while aggro -> keep the mob slowed until it reaches me. Often this results in the mob seemingly having "charged up" his/her swings somehow, and unload them all when reaching melee range. In the image below, you see how this mob hits me for 4 melee swings and 1 Mortal Strike in the very exact same time / batch. 
**Current behaviour**:
![image](https://user-images.githubusercontent.com/18015872/53600357-af6a4580-3ba9-11e9-9838-3640a34e915c.png)
Edit: I realize I had failed to remove the "Damage" curve. The damage seen would be Molten Armor damage on that particular mob from those swings. Yet, this is the best evidence I've gathered (it's hard to time in a print screen on the numbers when being surprisingly oneshotted, and NVidia Share wont even start)

**Expected behaviour**: 
Not "charging up" swings; the mob should reach me and use one, or depending on mob up to two, melee swings instantly and may add abilities into that.
**Server Revision**: 
2856

**Comment by Drayo** [comment]
I also noticed this on the "Crystalcore Devastator" in TK, he uses Counter-charge and immediately double hits on the next swing after casting it, pretty much one-shotting any tank.

https://cdn.discordapp.com/attachments/534703185617747968/552247701647917091/unknown.png

It might be a hidden aura, but it does seem a bit odd, pre-nerf or not.

**Comment by caiopmartins** [comment]
Nightbane does it as well, pretty much every time he lands. Something's screwy with the autoattack queue.

**Comment by gabbat** [comment]
can confirm, mobs do charge up autohits when kited. nightbane does it as well as caiopmartins says, as do the arcane protectors inside karazahn that u kite when they enrage.

**Comment by Drayo** [comment]
Since https://github.com/Atlantiss/NetherwingBugtracker/issues/4976 was fixed, this issue can be closed too.
