### ISSUE TITLE
Saving Princess Stillpine (not sure if blizzlike)

### ISSUE THREAD

**Issue by ttghnw** [Atlantiss/NetherwingBugtracker#526]
[//]: # (Enclose links to things related to the bug using http://wowhead.com or any other TBC database.)
[//]: # (You can use screenshot ingame to visual the issue.)
[//]: # (Write your tickets according to the format:)
[//]: # ([Quest][Azuremyst Isle] Red Snapper - Very Tasty!)
[//]: # ([NPC] Magistrix Erona)
[//]: # ([Spell][Mage] Fireball)
[//]: # ([Npc][Drop] Ghostclaw Lynx)
[//]: # ([Web] Armory doesnt work)

**Description**: **Current behaviour**:
In a group: The key droped by the high chief goes only for 1 of the group members - also the unlocking carried on by the receiving member does not give credit to the party members.

Please review if this is intended, looks unlikely blizzlike (specially with more ppl, you have to grind mobs to spawn the chief, then no key and no credit shared)

**Server Revision**:

**Comment by Tenoutoften** [comment]
Since no changes have been made this is still happening.
[[Quest]Saving Princess Stillpine#9667](https://www.wowhead.com/quest=9667/saving-princess-stillpine)

**Comment by Evolvee** [comment]
U cry on a wrong greav, this is the correct place: https://github.com/Atlantiss/NetherwingBugtracker/issues/529

**Comment by Evolvee** [comment]
rev 2531

**Comment by Tenoutoften** [comment]
This didn't work on 2538
