### ISSUE TITLE
Stormwind guards out of positions

### ISSUE THREAD

**Issue by eedijs** [Atlantiss/NetherwingBugtracker#5262]
[//]: # (Enclose links to things related to the bug using http://wowhead.com or any other TBC database.)
[//]: # (You can use screenshot ingame to visual the issue.)
[//]: # (Write your tickets according to the format:)
[//]: # ([Quest][Azuremyst Isle] Red Snapper - Very Tasty!)
[//]: # ([NPC] Magistrix Erona)
[//]: # ([Spell][Mage] Fireball)
[//]: # ([Npc][Drop] Ghostclaw Lynx)
[//]: # ([Web] Armory doesnt work)
[//]: # (To find server revision type `.server info` command in the game chat.)

**Description**: Stormwind guards in Trade district, mage quarters are out of position and inside of each other.

**Current behaviour**: They're out of position

**Expected behaviour**:  Should be in their regular positions

**Server Revision**:  2856

**Comment by Evolvee** [comment]
its fine on dev realm or on live after fresh restart, no idea what is causing this

**Comment by DaedalusMachina007** [comment]
If an opposite-faction member is seen/chased by a guard, they often get glitched/stuck in odd positions in capital cities and do not 'reset' back to their normal pathing/positions.

**Comment by The14me** [comment]
Rev.3483 they reset just fine to spawn position or path.

**Comment by Godmatik** [comment]
Still occurs.

https://cdn.discordapp.com/attachments/747656653452738700/778444500657766430/unknown.png
