### ISSUE TITLE
Rage generation on shielded targets

### ISSUE THREAD

**Issue by Hidehugo** [Atlantiss/NetherwingBugtracker#5263]
**Description**: Attacks against a shielded target (e.g. Powerword Shield) generate rage. This is unintended behaviour since the rage change on shielded targets was in 3.1 (Wrath of the Lich King Patch 3.1.0 (2009-04-14): Attacks that are absorbed (such as by [Power Word: Shield]) will now generate rage.  ; Source: https://wow.gamepedia.com/Rage). This has high impact on PvP and needs to be fixed

**Current behaviour**: Melee attacks against a target with an absorb-effect up let the attacker gain rage (tbh a really high amount of rage, on a pvp geared priest a warrior gets about 50-70 rage while hitting through the shield)

**Expected behaviour**: Melee attacks against a target with an absorb-effect up should not let the attacker gain any rage. (Bonus: my investigation on Reflective Shield talent from priests is that the rage generated is by the damage reflected to the attacker)

**Server Revision**:

**Comment by Wolffenstein** [comment]
Fixed in rev 2859.

**Comment by Hidehugo** [comment]
This in incorrect
I just did a duel against a lvl 62 warrior for testing and every autoattack gave the warrior about 20 rage per hit
