### ISSUE TITLE
The Talon Den mobs give no XP

### ISSUE THREAD

**Issue by brageboe** [Atlantiss/NetherwingBugtracker#5266]
[//]: # (Enclose links to things related to the bug using http://wowhead.com or any other TBC database.)
[//]: # (You can use screenshot ingame to visual the issue.)
[//]: # (Write your tickets according to the format:)
[//]: # ([Quest][Azuremyst Isle] Red Snapper - Very Tasty!)
[//]: # ([NPC] Magistrix Erona)
[//]: # ([Spell][Mage] Fireball)
[//]: # ([Npc][Drop] Ghostclaw Lynx)
[//]: # ([Web] Armory doesnt work)
[//]: # (To find server revision type `.server info` command in the game chat.)

**Description**: 
NPCs in the cave The Talon Den in ([Zone]Stonetalon Mountains) give no XP.

**Current behaviour**:
No XP when killing mobs solo, lvl 28 warrior.

Attempted kills when in a party as well (with a 34 hunter, mobs were grey/green for the hunter), then mobs gave 1 XP, and the rare occurrence of ~20-40 XP.

**Expected behaviour**: 
Normal XP gain. I did ([Quest]The Den) as a lvl 28 warrior, the mobs' lvl were within correct range to be receiving XP.

**Server Revision**:

**Comment by dinsfireyo** [comment]
you divided ur exp twice by groupong with a 34 hunter

**Comment by brageboe** [comment]
I get that. Even so, 1 xp still seems too low. And then randomly some mobs (of the same lvl) give 20-40 xp. 

Also, that still doesn't explain getting 0 xp when killing them solo. And yes, the mobs were my tag.

**Comment by duzyizly** [comment]
these mobs inside talon den does not provide XP:
gatekeeper kordurus https://tbcdb.com/?npc=4409
rynthariel https://tbcdb.com/?npc=8518
mirkfallon dryad https://tbcdb.com/?npc=4061
mirkfallon keeper https://tbcdb.com/?npc=4056
nal'taszar https://tbcdb.com/?npc=4066

rev 3404 ptr

![WoWScrnShot_062320_222856](https://user-images.githubusercontent.com/43931626/85459743-cbfe6e00-b5a2-11ea-9c1c-3568bd351f7d.jpg)
![WoWScrnShot_062320_222959](https://user-images.githubusercontent.com/43931626/85459745-cd2f9b00-b5a2-11ea-8bfa-72ce5c6b3fa9.jpg)
![WoWScrnShot_062320_223316](https://user-images.githubusercontent.com/43931626/85459747-cdc83180-b5a2-11ea-8953-68325025b93e.jpg)

**Comment by Wolffenstein** [comment]
Fixed in rev 3405.
