### ISSUE TITLE
[Core][Hunter] Pet doesn't tag mobs

### ISSUE THREAD

**Issue by Eidous** [Atlantiss/NetherwingBugtracker#5267]
[//]: # (Enclose links to things related to the bug using http://wowhead.com or any other TBC database.)
[//]: # (You can use screenshot ingame to visual the issue.)
[//]: # (Write your tickets according to the format:)
[//]: # ([Quest][Azuremyst Isle] Red Snapper - Very Tasty!)
[//]: # ([NPC] Magistrix Erona)
[//]: # ([Spell][Mage] Fireball)
[//]: # ([Npc][Drop] Ghostclaw Lynx)
[//]: # ([Web] Armory doesnt work)
[//]: # (To find server revision type `.server info` command in the game chat.)

**Description**:

Hunter pet damaging a mob doesnt count as hunter tagging it

**Current behaviour**:
If someone else attacks a target that has only been attacked by the hunter pet, the other person will get the tag

**Expected behaviour**: 
How about the pet counting as a tag for the hunter?????

**Server Revision**: 
who cares

**Comment by Jalapan** [comment]
@Wolffenstein

**Comment by Tenoutoften** [comment]
This has been reported before: https://github.com/Atlantiss/NetherwingBugtracker/issues/4230
Warlock pets do tag for their master on NW currently, but hunter pet's dont tag for their masters, surely one has got to change.

**Comment by Wolffenstein** [comment]
Fixed in rev 2861.
