### ISSUE TITLE
[Mobs] Image of Nexus-Prince Haramad

### ISSUE THREAD

**Issue by veekk** [Atlantiss/NetherwingBugtracker#5268]
**Description**: he is missing 
<img width="1079" alt="image" src="https://user-images.githubusercontent.com/12899687/53663418-629c7280-3c6e-11e9-93a6-4ba65cb07af1.png">

vanished after guards attack alliance player inside of room

**Server Revision**: 2857

**Comment by ircfelix** [comment]
That is part of a quest event. He will return.
