### ISSUE TITLE
Not correct Stats on items 

### ISSUE THREAD

**Issue by PFChan** [Atlantiss/NetherwingBugtracker#5269]
[//]: # (Enclose links to things related to the bug using http://wowhead.com or any other TBC database.)
[//]: # (You can use screenshot ingame to visual the issue.)
[//]: # (Write your tickets according to the format:)
[//]: # ([Quest][Azuremyst Isle] Red Snapper - Very Tasty!)
[//]: # ([NPC] Magistrix Erona)
[//]: # ([Spell][Mage] Fireball)
[//]: # ([Npc][Drop] Ghostclaw Lynx)
[//]: # ([Web] Armory doesnt work)
[//]: # (To find server revision type `.server info` command in the game chat.)

**Description**: 
The items bought with badges in Shattrath Infernoweave Gloves and Infernoweave Leggings gives less Stamina. I do have the addon NWTooltipFix from the site  
**Current behaviour**:
Infernoweave Gloves gives 33 stamina
Infernoweave Leggings  gives 39 stamina
**Expected behaviour**: 
Infernoweave Gloves gives 52 stamina https://wowwiki.fandom.com/wiki/Infernoweave_Gloves
the fire resist is correct so the patch note is same as the linked 
Infernoweave Leggings  gives 69 stamina https://wowwiki.fandom.com/wiki/Infernoweave_Leggings
the fire resist is correct so the patch note is same as the linked
**Server Revision**: 
2.0

**Comment by Tenoutoften** [comment]
Through checking the archive by searching up the NPC selling the items on May 14th you can see Infernoweave gloves with 33 Stamina & Leggings with 39 Stamina:
http://web.archive.org/web/20070514093903/http://www.thottbot.com:80/c18525

I'd assume this is working as intended. I think these values might be from a Blizzard PTR server given the date of the archive and wowhead comments, the item was certainly added very late in patch 2.0 by the looks of it... 2.0.12
