### ISSUE TITLE
[Talent][Warlock] Shadow Embrace

### ISSUE THREAD

**Issue by Effi28** [Atlantiss/NetherwingBugtracker#5270]
**Description**: 
Affliction Warlocks are disadvantaged in AoE fights because the Shadow Embrace Talent does not work correct. 
**Current behaviour**:

**Seed of Corruption** does not trigger the Shadow Embrace Effect.

**Expected behaviour**: 

**Seed of Corruption** spells also cause the Shadow Embrace effect, which reduces physical damage caused by 5%. 

**Server Revision**: 
2857

**Comment by Wolffenstein** [comment]
The explosion effect cannot proc anything. Only the main application of Seed of Corruption debuff applies Shadow Embrace.
