### ISSUE TITLE
[Winterspring] Died in Winterspring Cave - Released spirit in Alterac Mountains

### ISSUE THREAD

**Issue by fishworld** [Atlantiss/NetherwingBugtracker#5271]
So I died in the Winterspring cave where High Chief Winterfall is. However when I released my corpse, I had to run from Alterac Mountains. 

I went to Southshoure to talk to the angel to restore my corpse.

Instead I died, again, released in the same spot in alterac mountains.

This time, when I released my spirit, I got transfered to the GY of alterac.

???
![1 spirit release in alterac mountains](https://user-images.githubusercontent.com/1811912/53681260-44268d80-3ce7-11e9-98a0-8fb65160d44b.jpg)
![2](https://user-images.githubusercontent.com/1811912/53681261-45f05100-3ce7-11e9-8bf8-b306b8e87e92.jpg)
![3](https://user-images.githubusercontent.com/1811912/53681262-47217e00-3ce7-11e9-8db3-915c11bb1ed3.jpg)
![4 random alterac mountains cave](https://user-images.githubusercontent.com/1811912/53681263-4852ab00-3ce7-11e9-81cc-15badb6bc3cd.jpg)

See pictures.

**Comment by DragunovUA** [comment]
xd

**Comment by Kantrul** [comment]
Happened to me as of today. WTF

**Comment by Wolffenstein** [comment]
Fixed in rev 3198.
