### ISSUE TITLE
Lurker Below damage.

### ISSUE THREAD

**Issue by Anonyxx** [Atlantiss/NetherwingBugtracker#5272]
[//]: # (Enclose links to things related to the bug using http://wowhead.com or any other TBC database.)
[//]: # (You can use screenshot ingame to visual the issue.)
[//]: # (Write your tickets according to the format:)
[//]: # ([Quest][Azuremyst Isle] Red Snapper - Very Tasty!)
[//]: # ([NPC] Magistrix Erona)
[//]: # ([Spell][Mage] Fireball)
[//]: # ([Npc][Drop] Ghostclaw Lynx)
[//]: # ([Web] Armory doesnt work)
[//]: # (To find server revision type `.server info` command in the game chat.)

**Description**: 

Lurker below currently hits very hard and on par with a T6/SWP boss. One of our tanks had 20k damage in 1.5s. I understand this is a "custom behavior" to compensate for 2.4 talents, however this damage is still ridiculous and should be nerfed to a reasonable standard.

**Current behaviour**:

Lurker hits for 9k - 10k on a geared tank.

**Expected behaviour**: 

Lurker should hit for around 4-5k on a geared tank.

If you want to go for custom damage values, I would recommend going for around 6k damage on a geared tank.

**Server Revision**: 
2857

**Comment by Firroth** [comment]
If you use demo shout, he hits for measly 7-8k... try it sometimes. 7-8k is easily managable.

**Comment by Easyfraggy** [comment]
Like Firroth said you should keep all debuffs on bosses improved demo - TC scorpid sting etc.

Make sure your tanks are using Ironshield Potions when raiding aswell.
