### ISSUE TITLE
[NPC][Dungeon] Balnazzar

### ISSUE THREAD

**Issue by Szabinger** [Atlantiss/NetherwingBugtracker#5273]
**Description**: 
Balnazzar's sleeping cloud does not brake on damage, and cannot be broken with tremor totem.

**Current behaviour**:
See description.

**Expected behaviour**: 
The sleep effect should be broken on damage by the boss, or by tremor totem.

**Server Revision**: 
2857

**Comment by Silbotronic** [comment]
He's not even supposed to do a sleeping cloud, it should be a single target magic effect.
https://tbc-twinhead.twinstar.cz/?spell=12098

**Comment by Godmatik** [comment]
Fixed in Strat revamp, can be closed
