### ISSUE TITLE
[Item/NPC] Compact Harvest Reaper (Kit) despawns. Unlootable

### ISSUE THREAD

**Issue by b15andga** [Atlantiss/NetherwingBugtracker#5274]
[//]: # (Enclose links to things related to the bug using http://wowhead.com or any other TBC database.)
[//]: # (You can use screenshot ingame to visual the issue.)
[//]: # (Write your tickets according to the format:)
[//]: # ([Quest][Azuremyst Isle] Red Snapper - Very Tasty!)
[//]: # ([NPC] Magistrix Erona)
[//]: # ([Spell][Mage] Fireball)
[//]: # ([Npc][Drop] Ghostclaw Lynx)
[//]: # ([Web] Armory doesnt work)
[//]: # (To find server revision type `.server info` command in the game chat.)

**Description**: 
[Compact Harvest Reaper Kit] (item=4391) spawns a Compact Harvest Reaper (npc=2676) which, upon death by either damage or the 10 minuter timer, should be lootable. I've tried with 4 kits so far. All has despawned; first one charged in but didn't attack, despawned when it lost got aggro; second and third one got killed and despawned directly upon death. A 4th one has been up and kept out of combat for 15 minutes and counting.
**Current behaviour**:
Doesn't attack unless having initial and sustained aggro. Despawns directly upon death or losing aggro. Does not die/despawn after 10 minutes. Not lootable.
**Expected behaviour**: 
Should stay up for 10 minutes or until death and then become a lootable corpse. Should not despawn for losing aggro. Should attack despite not having aggro.
**Server Revision**: 
2857

**Comment by The14me** [comment]
Rev.3478 still an issue.

**Comment by Godmatik** [comment]
Duplicate - was fixed last year
