### ISSUE TITLE
[Hunter] [Frost Trap] Pillars should not prevent aoe slow.

### ISSUE THREAD

**Issue by gunzbngbng** [Atlantiss/NetherwingBugtracker#5275]
[//]: # (Enclose links to things related to the bug using http://wowhead.com or any other TBC database.)
[//]: # (You can use screenshot ingame to visual the issue.)
[//]: # (Write your tickets according to the format:)
[//]: # ([Quest][Azuremyst Isle] Red Snapper - Very Tasty!)
[//]: # ([NPC] Magistrix Erona)
[//]: # ([Spell][Mage] Fireball)
[//]: # ([Npc][Drop] Ghostclaw Lynx)
[//]: # ([Web] Armory doesnt work)
[//]: # (To find server revision type `.server info` command in the game chat.)

**Description**: Frost Trap positioned too close to a pillar causes the trap radius to not slow, even when players are clearly in the frosted area.

**Current behaviour**: Frost Trap positioned too close to a pillar causes the trap radius to not slow, even when players are clearly in the frosted area.  

**Expected behaviour**: Players in the frost area should be slowed.  

**Server Revision**: 2857

**Comment by Zarant** [comment]
Possibly related to #5210

**Comment by 4egito** [comment]
@Tereneckla fixed in rev [3276] Core fixes
[Core/Auras]:
- Fixed certain persistent area auras not affecting targets not in line of sight (e.g. Frost Trap)
