### ISSUE TITLE
Racial weapon specializations

### ISSUE THREAD

**Issue by Regimant** [Atlantiss/NetherwingBugtracker#5276]
[//]: # (Enclose links to things related to the bug using http://wowhead.com or any other TBC database.)
[//]: # (You can use screenshot ingame to visual the issue.)
[//]: # (Write your tickets according to the format:)
[//]: # ([Quest][Azuremyst Isle] Red Snapper - Very Tasty!)
[//]: # ([NPC] Magistrix Erona)
[//]: # ([Spell][Mage] Fireball)
[//]: # ([Npc][Drop] Ghostclaw Lynx)
[//]: # ([Web] Armory doesnt work)
[//]: # (To find server revision type `.server info` command in the game chat.)

**Description**: 

**Current behaviour**:
 Weapon specializations from racials giving 5 expertise
**Expected behaviour**: 
 Should be giving 1% crit respectively

https://wow.gamepedia.com/Patch_2.3.0 Patch 2.3 these were changed to 1% crit
**Server Revision**: 
203

**Comment by Godmatik** [comment]
You're mixing it up. Patch 2.3 changed it from Crit to Expertise. The spells are using the 2.4.3 database, so this is working as intended.

**Comment by Regimant** [comment]
Thats not what it sais at all actually.

**Comment by Regimant** [comment]
If this is wrong, logic could put together that other parts of the notes could be wrong correct? So another issue being proven by these notes that there is video evidence for, the counter argument using these notes should be thrown out, if they are wrong.

**Comment by Godmatik** [comment]
It very clearly says in the notes you listed that it was changed FROM crit TO expertise. That means it originally gave crit, but after patch 2.3, it gives expertise.

**Comment by Regimant** [comment]
"Dwarf:  [Gun Specialization] now increases chance to critically hit with Guns by 1% rather than increasing weapon skill.
Gnome:  [Escape Artist] cooldown increased to 1 min, 45 sec.
Humans: Mace Skill now increases the critical strike chance with maces and two-handed maces by 1%.
Humans: Sword Skill now increases the critical strike chance with swords and two-handed swords by 1%.
Orcs: Axe Skill now increases the critical strike chance with axes and two-handed axes by 1%.
Troll: Bow and Thrown Specialization now increases chance to critically hit with those weapons by 1% rather than increasing weapon skill."
