### ISSUE TITLE
[Event] Stranglethorn Fishing Extravaganza almost playable, but not quite

### ISSUE THREAD

**Issue by MAY-THE-ETERNAL-SUN-SHINE-UPON-YOU** [Atlantiss/NetherwingBugtracker#5282]
**Description**: 
The Tastyfish pools that spawn are invisible and fishing them gives 0 items. By invisible I mean that mousing over certain spots of the coast will show the "Tastyfish Pool" tooltip, as if a pool were really there, but visually there is no model for it.
These still appear to be the exact size of a pool and correctly work as you'd expect from an invisible pool, but when fished they give no items, as if they had an empty drop table.

Right at the start of the event, 1:59 server time, the first pool that I tried to fish somehow became visible and allowed me to fish it, giving me [1 Tastyfish](https://i.imgur.com/9AHImYv.jpg). It disappeared (fully, not invisibilized) after one catch. The other Tastyfish pools all remained invisible. Nobody else was able to get one single fish, as far as I know, which makes me the indisputable victor and I demand my reward.

Additionally, the NPC that you're supposed to turn in the 40 Tastyfish to was missing, and the secondary NPC said that a winner had already been found. I only found out about this 20 minutes into the event but given that this event takes minimum 20 minutes to win in Blizzlike servers where the event actually works I find this highly improbable.

**Current behaviour**:
Tastyfish pools can't be fished, save for one inexplicable exception.

**Expected behaviour**: 
Tastyfish pools can be fished.

**Server Revision**: 
2865

**Comment by Greytt** [comment]
Today I was able to catch 25 fish before the pools bugged. Tooltip shows them but they're invisible and nothing comes up from it.

https://i.imgur.com/x8NxBp3.png

**Comment by Tereneckla** [comment]
closed, see #960
