### ISSUE TITLE
Warchief Kargath Bladefist's Sweeping Strikes

### ISSUE THREAD

**Issue by Psychoz** [Atlantiss/NetherwingBugtracker#5284]
**Description**:  Shattered Halls (Heroic) Last boss Warchief Kargath Bladefist have an ability Sweeping Strikes. As it described, "Warchief Kargath Bladefist's next 5 melee attacks strike an additional player."

**Current behaviour**:  Sweeping Strikes suddenly hits 3 times instantly.

Link for description https://wow.gamepedia.com/Warchief_Kargath_Bladefist

Screenshot from Recount with instant tripple Sweeping Strikes attached.
![wowscrnshot_030419_034620](https://user-images.githubusercontent.com/13827887/53701588-43017780-3e31-11e9-9378-2f3a1802fe49.jpg)

**Comment by Tenoutoften** [comment]
https://github.com/Atlantiss/NetherwingBugtracker/issues/5256

**Comment by Drayo** [comment]
Since https://github.com/Atlantiss/NetherwingBugtracker/issues/4976 was fixed, this issue can be closed too.
