### ISSUE TITLE
Disenchanting Heavy Adamantite Rings yields less materials than expected

### ISSUE THREAD

**Issue by Vanderez** [Atlantiss/NetherwingBugtracker#5285]
[//]: # (Enclose links to things related to the bug using http://wowhead.com or any other TBC database.)
[//]: # (You can use screenshot ingame to visual the issue.)
[//]: # (Write your tickets according to the format:)
[//]: # ([Quest][Azuremyst Isle] Red Snapper - Very Tasty!)
[//]: # ([NPC] Magistrix Erona)
[//]: # ([Spell][Mage] Fireball)
[//]: # ([Npc][Drop] Ghostclaw Lynx)
[//]: # ([Web] Armory doesnt work)
[//]: # (To find server revision type `.server info` command in the game chat.)

**Description**: 
Disenchanting Heavy Adamantite Rings from the JC profession only yields 2-3 Arcane Dust, 
**Current behaviour**:
Disenchanting Heavy Adamantite Rings from the JC profession only yields 2-3 Arcane Dust, 
**Expected behaviour**: 
Should yield anywhere from 2-7 dust, according to wowhead: https://www.wowhead.com/item=24078/heavy-adamantite-ring#disenchanting
**Server Revision**:

**Comment by EnterLarry** [comment]
it's working as intended. wowhead is wrong.
