### ISSUE TITLE
[Spell][Mage][Fire Aoe Spells]

### ISSUE THREAD

**Issue by SlowxP** [Atlantiss/NetherwingBugtracker#5286]
[//]: # (Enclose links to things related to the bug using http://wowhead.com or any other TBC database.)
[//]: # (You can use screenshot ingame to visual the issue.)
[//]: # (Write your tickets according to the format:)
[//]: # ([Quest][Azuremyst Isle] Red Snapper - Very Tasty!)
[//]: # ([NPC] Magistrix Erona)
[//]: # ([Spell][Mage] Fireball)
[//]: # ([Npc][Drop] Ghostclaw Lynx)
[//]: # ([Web] Armory doesnt work)
[//]: # (To find server revision type `.server info` command in the game chat.)

**Description**: 
Im remaking my report earlier of https://github.com/Atlantiss/NetherwingBugtracker/issues/5246 as i have been testing alot with my fire aoe spells (Blast Wave, Dragon's Breath and Flamestrike)

**Current behaviour**:
All 3 spells is only giving 1 combustion stack with more then 1 target as mentions here with
blast wave https://github.com/Atlantiss/NetherwingBugtracker/issues/5157
Also all 3 spells is only applying one ignite if crited on more then one mob

**Expected behaviour**: 
All 3 spells should be giving X amount of combustion stacks on all mobs that u aoe
and all 3 spells should apply ignite on all mobs that u crit on.

**Server Revision**: 
2865

**Comment by Godmatik** [comment]
1 - I am getting 1 stack for each enemy i hit with AoE
2 - Ignite being applied to all

This must have been fixed at some point.

Closing.
