### ISSUE TITLE
[Item][Paladin] Crystalforge Greaves 

### ISSUE THREAD

**Issue by Fowdall** [Atlantiss/NetherwingBugtracker#5287]
[//]: # (Enclose links to things related to the bug using http://wowhead.com or any other TBC database.)
[//]: # (You can use screenshot ingame to visual the issue.)
[//]: # (Write your tickets according to the format:)
[//]: # ([Quest][Azuremyst Isle] Red Snapper - Very Tasty!)
[//]: # ([NPC] Magistrix Erona)
[//]: # ([Spell][Mage] Fireball)
[//]: # ([Npc][Drop] Ghostclaw Lynx)
[//]: # ([Web] Armory doesnt work)
[//]: # (To find server revision type `.server info` command in the game chat.)

**Description**: Crystalforge Greaves bonus spell damage is an on use effect rather than an equip effect

**Current behaviour**: The bonus spell damage and healing provided by Crystalforge Greaves is an on use effect and doesn't give any bonus damage or healing when equipped.

https://puu.sh/CUGWv/9a44caeb19.jpg

**Expected behaviour**: The bonus spell damage and healing provided by Crystalforge Greaves is provided whilst the item is equipped.

**Server Revision**: 2865

**Comment by Wolffenstein** [comment]
Fixed in rev 2902.
