### ISSUE TITLE
[Herb Nodes][The Hinterlands] herb nodes dont seem to be respawning. 12pm-13pm sever time.

### ISSUE THREAD

**Issue by ndnd123** [Atlantiss/NetherwingBugtracker#5290]
[//]: # (Enclose links to things related to the bug using http://wowhead.com or any other TBC database.)
[//]: # (You can use screenshot ingame to visual the issue.)
[//]: # (Write your tickets according to the format:)
[//]: # ([Quest][Azuremyst Isle] Red Snapper - Very Tasty!)
[//]: # ([NPC] Magistrix Erona)
[//]: # ([Spell][Mage] Fireball)
[//]: # ([Npc][Drop] Ghostclaw Lynx)
[//]: # ([Web] Armory doesnt work)
[//]: # (To find server revision type `.server info` command in the game chat.)

**Description**: 
Did several laps around, the entire zone was void of any herbs (and it was populated)
**Current behaviour**:

**Expected behaviour**: 

**Server Revision**:

**Comment by Exorcista** [comment]
Bumping this. Not even picking the herbs in the coast made them respawn.

**Comment by Tereneckla** [comment]
rev 3205
