### ISSUE TITLE
Gold in Guild Bank disappears

### ISSUE THREAD

**Issue by jmurraypplnet** [Atlantiss/NetherwingBugtracker#5291]
**Description**: 
Gold deposited in guild bank disappears following crash
**Current behaviour**:
Deposit gold in bank.  Deposit shows in bank log.  Gold disappears after crash, and from log, as if it were never deposited.  Gold is not re-added to users' amount, it's just straight gone.
**Expected behaviour**: 
Gold doesn't disappear from guild bank and log remains intact.
**Server Revision**: 
2867

I am reposting this because there has been zero indication if this is being worked on over the last month and I'm frustrated to have to handle all the transactions on my own character instead of using the guild bank as it is intended.  Guild bank gold is an integral part of the game.  Please address this.  Not asking for a refund, just asking for some attention to this.

**Comment by Jalapan** [comment]
I think guildsystem and guildbank has been rewritten and will go live on PTR soon for testing

**Comment by Tenoutoften** [comment]
Item & gold disappearing from guild banks is well known and been reported many times. No matter how much you lost Game Masters have decided to never refund.
https://github.com/Atlantiss/NetherwingBugtracker/issues/4928
https://github.com/Atlantiss/NetherwingBugtracker/issues/4859
https://github.com/Atlantiss/NetherwingBugtracker/issues/4837
https://github.com/Atlantiss/NetherwingBugtracker/issues/4809
https://github.com/Atlantiss/NetherwingBugtracker/issues/4770
https://github.com/Atlantiss/NetherwingBugtracker/issues/4722
https://github.com/Atlantiss/NetherwingBugtracker/issues/4331
