### ISSUE TITLE
[Quest][Thousand Needles] Henrig Lonebrow's Journal

### ISSUE THREAD

**Issue by Moryjani** [Atlantiss/NetherwingBugtracker#5292]
**Description**: The container Henrig Lonebrow's Journal doesn't drop "Lonebrow's Journal"

**Current behaviour**: Container can be looted but is empty.

**Expected behaviour**: Should drop Henrig Lonebrow's Journal.

**Server Revision**: 2865

![image](https://user-images.githubusercontent.com/10288894/53741320-64e11580-3e96-11e9-9489-1703b8bf3a84.png)

**Comment by wcraycroft** [comment]
Having same issue in revision 2930.

**Comment by noradora** [comment]
+1

**Comment by Zarant** [comment]
The journal dropped 15 out of 15 times for me, however, if you accept the quest and abandon it, you cannot loot the journal again.

**Comment by Wolffenstein** [comment]
I abandoned the quest and could loot the journal just fine:
![obraz](https://user-images.githubusercontent.com/1576644/87216680-3d2f7680-c342-11ea-9565-d720951c6088.png)

Perhaps a cache issue. Closing.
