### ISSUE TITLE
[Item] Rivenspike

### ISSUE THREAD

**Issue by Perfecthandz** [Atlantiss/NetherwingBugtracker#5293]
**Current behaviour**: The Rivenspike proc of puncturing the target's armor by 200x3 is applying just fine, but warrior sunder removes/overrides it.

**Expected behaviour**: Both are separate debuffs, and I don't believe it was nerfed until patch 6.2.

**Comment by Tenoutoften** [comment]
[[Item]Rivenspike#13286](https://db.excalibur.ws/?item=13286)'s [[Spell]Puncture Armor#17315](https://db.excalibur.ws/?spell=17315) should stack with [[Spell]Sunder Armor](https://db.excalibur.ws/?search=sunder+armor), but it shouldn't stack with [[Spell]Faerie Fire](https://db.excalibur.ws/?search=faerie+fire) based upon the official patch notes from Blizzard for [Patch 1.8.0](https://wow.gamepedia.com/Patch_1.8.0)
![](https://i.gyazo.com/25a656213f5bea11b9b6499c17b9abaf.png)

I think you got the item mixed up with [[Item]Annihilator#12798](https://db.excalibur.ws/?item=12798)'s [[Spell]Armor Shatter#16928](https://db.excalibur.ws/?spell=16928)  which did stack with [[Spell]Faerie Fire](https://db.excalibur.ws/?search=faerie+fire) and didn't get affected by the [Patch 1.8.0](https://wow.gamepedia.com/Patch_1.8.0) changes, more info here: https://github.com/Atlantiss/NetherwingBugtracker/issues/4728

However, the leadership of this server feels like they don't want this item to work properly and have decided to custom break it in such a way that it can't proc on bosses.

**Comment by Perfecthandz** [comment]
I will check to see if it works on bosses, but I was definitely in a Slave Pens with no druids and noticed the puncture debuff being pushed off by the warrior.

Will confirm and report back, after tonight's raid.

**Comment by Tereneckla** [comment]
Only Annihilator stacks with Sunder/Expose Armor
