### ISSUE TITLE
[Spell's][Mage][Portal's]

### ISSUE THREAD

**Issue by SlowxP** [Atlantiss/NetherwingBugtracker#5294]
[//]: # (Enclose links to things related to the bug using http://wowhead.com or any other TBC database.)
[//]: # (You can use screenshot ingame to visual the issue.)
[//]: # (Write your tickets according to the format:)
[//]: # ([Quest][Azuremyst Isle] Red Snapper - Very Tasty!)
[//]: # ([NPC] Magistrix Erona)
[//]: # ([Spell][Mage] Fireball)
[//]: # ([Npc][Drop] Ghostclaw Lynx)
[//]: # ([Web] Armory doesnt work)
[//]: # (To find server revision type `.server info` command in the game chat.)

**Description**: 
With all portals ur party/raid members cannot use the portal if the mage who made the port jumps in first

**Current behaviour**:
Canot be used if mage who made the portal jumps in first

**Expected behaviour**: 
Can be used if mage who made the portal jumps in first

**Server Revision**: 
2865

**Comment by The14me** [comment]
Rev.3478 not an issue anymore. Tested in Party and raid.
Can be closed.
