### ISSUE TITLE
Illidari-Bane Shard (id 30756) Shouldn't drop for horde

### ISSUE THREAD

**Issue by nullfoxh** [Atlantiss/NetherwingBugtracker#5295]
Illidari-Bane Shard (id 30756) Shouldn't drop for horde.

Monster dropped both the alliance and horde versions, should only drop horde version for horde players.

Alliance: https://db.excalibur.ws/?item=30756
Horde: https://db.excalibur.ws/?item=30579

**Comment by Evolvee** [comment]
thats impossible, there is a condition and it works fine for me, how did you manage to do that?

**Comment by nullfoxh** [comment]
Was just grinding some aldor rep stuff, one mob dropped them both for me, didn't allow me to start the alliance quest though..

**Comment by nullfoxh** [comment]
Same thing with Oshu'gun samples.
![unknown](https://user-images.githubusercontent.com/12772977/53963219-8429ae00-40f5-11e9-84b6-65a8be7bf364.png)

**Comment by Evolvee** [comment]
no idea... if it happens again, reopen.. i cant reproduce it
