### ISSUE TITLE
[Core] Incorrect Value of Honor

### ISSUE THREAD

**Issue by Dusyagonemad** [Atlantiss/NetherwingBugtracker#5297]
[//]: # (Enclose links to things related to the bug using http://wowhead.com or any other TBC database.)
[//]: # (You can use screenshot ingame to visual the issue.)
[//]: # (Write your tickets according to the format:)
[//]: # ([Quest][Azuremyst Isle] Red Snapper - Very Tasty!)
[//]: # ([NPC] Magistrix Erona)
[//]: # ([Spell][Mage] Fireball)
[//]: # ([Npc][Drop] Ghostclaw Lynx)
[//]: # ([Web] Armory doesnt work)
[//]: # (To find server revision type `.server info` command in the game chat.)

**Description**: 
One solo HK = 40 honor at level 70.
Solo HK should grant 20.9 honor.

All battlegrounds bonus honor should be calculated with formula which uses 20.9 honor for HK.

You can read about it for example in Alterac Valley description on old wowwiki:
https://wow.gamepedia.com/index.php?title=Alterac_Valley&oldid=1553302

> Official Blizzard values of bonus honour :
> 
> Killing Enemy General (4 kills)
> Killing Enemy Captain (3 kills)
> Destroying an Enemy Tower (3 kills per tower)
> Live Captain (2 kills)
> Surviving towers (2 kills per tower) - Note: Must be "Controlled", not "In Conflict."
> Completing AV during it's holiday weekend (4 kills)
> Having a Wing Commander safely return to his or her home base (1 kill)
> Each kill yields ~20.9 honor in the 61-70 bracket and ~14.1 honor in the 51-60 bracket.

> One kill = 20.9 honor at level 70.

**Current behaviour**:
HK at level 70 grants 40 honor.

**Expected behaviour**: 
HK at level 70 grants 20.9 honor.

**Server Revision**: 
2865

**Comment by Godmatik** [comment]
https://www.youtube.com/watch?v=LsgImO4Dh7U&t=800s

This timestamped video shows 40 honor gained for a kill.

We need more solid proof to change it - but at the moment it sounds like it is set correctly.

Closing.
