### ISSUE TITLE
[Shaman][talent][purification]

### ISSUE THREAD

**Issue by teddys** [Atlantiss/NetherwingBugtracker#5299]
**Description**:  https://wowwiki.fandom.com/wiki/Purification?oldid=1432246&fbclid=IwAR02ohbFkvN1nP4xG-gQwejgh1Ppx7eFbSmo_WUQQcT1ACmNk07MpI2ErQc

**Current behaviour**: Doesn't increase healing of nature's guardian

**Expected behaviour**: Increases the healing of nature's guardian

**Server Revision**:  2865

I'd also appreciate someone with access to a shaman on ptr to test this talent for all of the shaman's healing spells

**Comment by Jalapan** [comment]
Hit me up on discord and i can help u test on PTR

Malle#1337

**Comment by Wolffenstein** [comment]
Only Nature's Guardian should be broken due to the nature of how this talent is coded.

**Comment by Wolffenstein** [comment]
Fixed in rev 2889.
