### ISSUE TITLE
Pick Pocket working as intended?

### ISSUE THREAD

**Issue by deku100** [Atlantiss/NetherwingBugtracker#53]
[//]: # (Enclose links to things related to the bug using http://wowhead.com or any other TBC database.)
[//]: # (You can use screenshot ingame to visual the issue.)
[//]: # (Write your tickets according to the format:)
[//]: # ([Quest][Azuremyst Isle] Red Snapper - Very Tasty!)
[//]: # ([NPC] Magistrix Erona)
[//]: # ([Spell][Mage] Fireball)
[//]: # ([Npc][Drop] Ghostclaw Lynx)
[//]: # ([Web] Armory doesnt work)

**Description**: Does pick pocket work as intended?

**Current behaviour**: Majority of pickpocket attempts end in mob turning to attack me. No "Resist" comes up. Currently in Eversong Woods, and have picked everything from various types of wretched and undead.

**Expected behaviour**: If a mob resists pickpocket, it will say "Resist." Most mobs do not resist pick pocketing.

**Server Revision**:

**Comment by DarthNekr0s** [comment]
this has been happening to me as well, about 80% of the time they attack me, 
im sure that you should be able to pickpocket everything easily without this happening

**Comment by Erodraeda** [comment]
There should be a ~5% chance of resist, but it does, indeed, look a lot higher than that, + the "nothing happens" effect that has been happening.

**Comment by bloodwindz** [comment]
if your stealth i not high enough you have change berore the final attemp to get discovered  but if you activated the ability first then its a bug
