### ISSUE TITLE
Nazzivius Summoner not aggroing properly

### ISSUE THREAD

**Issue by ttghnw** [Atlantiss/NetherwingBugtracker#530]
[//]: # (Enclose links to things related to the bug using http://wowhead.com or any other TBC database.)
[//]: # (You can use screenshot ingame to visual the issue.)
[//]: # (Write your tickets according to the format:)
[//]: # ([Quest][Azuremyst Isle] Red Snapper - Very Tasty!)
[//]: # ([NPC] Magistrix Erona)
[//]: # ([Spell][Mage] Fireball)
[//]: # ([Npc][Drop] Ghostclaw Lynx)
[//]: # ([Web] Armory doesnt work)

**Description**: 

**Current behaviour**:
You can run in front of these mobs in nazzivius and they ignore you.
**Expected behaviour**: 
Larger aggro radius
**Server Revision**:

**Comment by Evolvee** [comment]
they arent supposed to aggro
they are used only for a Tzerak summoning event and they will all be removed after next revision restart ^^

**Comment by ttghnw** [comment]
haha LoL :D ok
