### ISSUE TITLE
Diabolical Plans

### ISSUE THREAD

**Issue by volundr1** [Atlantiss/NetherwingBugtracker#5300]
[//]: # (Enclose links to things related to the bug using http://wowhead.com or any other TBC database.)
[//]: # (You can use screenshot ingame to visual the issue.)
[//]: # (Write your tickets according to the format:)
[//]: # ([Quest][Azuremyst Isle] Red Snapper - Very Tasty!)
[//]: # ([NPC] Magistrix Erona)
[//]: # ([Spell][Mage] Fireball)
[//]: # ([Npc][Drop] Ghostclaw Lynx)
[//]: # ([Web] Armory doesnt work)
[//]: # (To find server revision type `.server info` command in the game chat.)

**Description**: 
I can't accept the quest from the item Diabolical Plans.

**Current behaviour**:
That quest is not available to your race.
This has happened to me on my orc and blood elf.

**Expected behaviour**: 
I should be able to accept the quest.

**Server Revision**: 
2865

**Comment by Drayo** [comment]
There are two different Diabolical Quest Items, one for Horde and one for Alliance.

https://www.wowhead.com/item=23797/diabolical-plans#starts
https://www.wowhead.com/item=23777/diabolical-plans#starts

Most likely the Alliance Plans are falsely dropping for Horde Players and maybe the other way around too.

**Comment by volundr1** [comment]
Thank you. This makes sense. I kept questing and held on to the plans I had. A little while later another set of plans dropped and I had both plans in my bad and was able to complete one of them.

Not sure where to go from here. It seems like a very minor issue at this point.

**Comment by duzyizly** [comment]
Works as intended.
