### ISSUE TITLE
An Audience with the Prince

### ISSUE THREAD

**Issue by JKardi** [Atlantiss/NetherwingBugtracker#5301]
[//]: # (Enclose links to things related to the bug using http://wowhead.com or any other TBC database.)
[//]: # (You can use screenshot ingame to visual the issue.)
[//]: # (Write your tickets according to the format:)
[//]: # ([Quest][Azuremyst Isle] Red Snapper - Very Tasty!)
[//]: # ([NPC] Magistrix Erona)
[//]: # ([Spell][Mage] Fireball)
[//]: # ([Npc][Drop] Ghostclaw Lynx)
[//]: # ([Web] Armory doesnt work)
[//]: # (To find server revision type `.server info` command in the game chat.)

**Description**: 
Quest NPC doesnt spawn
**Current behaviour**:

**Expected behaviour**: 

**Server Revision**:

**Comment by JKardi** [comment]
[https://gyazo.com/c6910bbbbd7ce3a56af0414bd79f211d](url)

**Comment by narayagh** [comment]
Worked just fine for me 2 weeks ago.

**Comment by Tenoutoften** [comment]
This is part of a quest event, he will return
https://github.com/Atlantiss/NetherwingBugtracker/issues/5268

**Comment by JKardi** [comment]
11 hours later, still not there

**Comment by Tenoutoften** [comment]
I know that he was there yesterday, but I was unable to deliver my quest to him. I do think something wrong is happening / he should return faster

**Comment by Tenoutoften** [comment]
Here is a report for the flower mobs just below this town that I did during the beta, the main issue is that they don't transform back and combined with lazy players, eventually all mobs are turned and new players taking the quest have to clear through other players mobs.
https://github.com/Atlantiss/NetherwingBugtracker/issues/2665

**Comment by JKardi** [comment]
Why even live tbh

**Comment by Manaci** [comment]
Fixed
