### ISSUE TITLE
Tideress 

### ISSUE THREAD

**Issue by Braderman88** [Atlantiss/NetherwingBugtracker#5302]
[//]: # (Enclose links to things related to the bug using http://wowhead.com or any other TBC database.)
[//]: # (You can use screenshot ingame to visual the issue.)
[//]: # (Write your tickets according to the format:)
[//]: # ([Quest][Azuremyst Isle] Red Snapper - Very Tasty!)
[//]: # ([NPC] Magistrix Erona)
[//]: # ([Spell][Mage] Fireball)
[//]: # ([Npc][Drop] Ghostclaw Lynx)
[//]: # ([Web] Armory doesnt work)
[//]: # (To find server revision type `.server info` command in the game chat.)

**Description**:  Tideress at Mystral lake in Ashenvale does not spawn

**Current behaviour**: Tideress at Mystral lake. I have waited from 09:30 server time until 09:50 server time and did not spawn once.

**Expected behaviour**:  Would hope to spawn within 5 minutes of last being killed.

**Server Revision**: 2865

**Comment by Drayo** [comment]
Did you check the entire lake? The fixed spawn was only implemented in Cata.

She can spawn all over the place.

**Comment by Manaci** [comment]
Fixed
