### ISSUE TITLE
{[Spell][Shaman][Windfury Weapon]} Bug

### ISSUE THREAD

**Issue by Nikrotip** [Atlantiss/NetherwingBugtracker#5303]
[//]: # (Enclose links to things related to the bug using http://wowhead.com or any other TBC database.)
[//]: # (You can use screenshot ingame to visual the issue.)
[//]: # (Write your tickets according to the format:)
[//]: # ([Quest][Azuremyst Isle] Red Snapper - Very Tasty!)
[//]: # ([NPC] Magistrix Erona)
[//]: # ([Spell][Mage] Fireball)
[//]: # ([Npc][Drop] Ghostclaw Lynx)
[//]: # ([Web] Armory doesnt work)
[//]: # (To find server revision type `.server info` command in the game chat.)

**Description**: Windfury Weapon doesn't  work correctly. Sometimes it deals additional damage equal to only one extra attack with no extra AP>>> [https://imgur.com/a/fQK1JwE](url) Sometimes it deals additional damage equal to two extra attacks but with no extra AP>>> [https://imgur.com/JQ0G2Hs](url) Moreover, sometimes it deals additional damage equal to only one extra attack but with extra AP (WTF?!)>>> [https://imgur.com/CKKNTFu](url)
And sometimes it seems to work as it should, dealing additional damage equal to two extra attacks with extra AP>>> [https://imgur.com/e9T2trW](url) 
Obviously, all these, according to the screenshot were tried without the talent 'Elemental Weapons' (which seems to be working)

**Current behaviour**: Windfury Weapon can deal additional damage equal to only one extra attack, with or without extra AP. Same goes for dealing two extra attacks>>>it can deal additional damage equal to two extra attacks with or without extra AP and all of this is a total random.

**Expected behaviour**: Tooltip: Each hit has a 20% chance of dealing additional damage equal to two extra attacks with 53 extra attack power. Simply speaking, windfury weapon MUST ALWAYS deal additional damage equal to two yellow attacks with extra AP.

P.S.: This is a big issue which makes enhancements' lives really hardcore. Please test it and fix it. Thank you!

**Server Revision**: 2865
![wowscrnshot_030519_000615](https://user-images.githubusercontent.com/48246079/53805966-4b9e9e80-3f54-11e9-882f-1eb6cf3250a1.jpg)
![wowscrnshot_030519_000348](https://user-images.githubusercontent.com/48246079/53805974-56593380-3f54-11e9-8bcb-35ca00e94850.jpg)
![wowscrnshot_030519_000145](https://user-images.githubusercontent.com/48246079/53805978-59542400-3f54-11e9-9ef7-87bdd9142e01.jpg)
![wowscrnshot_030519_000039](https://user-images.githubusercontent.com/48246079/53805982-5bb67e00-3f54-11e9-92f0-734f2a084220.jpg)

**Comment by hitbutton** [comment]
Playing at 70 with maxrank windfury I have not noticed this issue at all, and haven't been able to reproduce it with a small amount of testing.

The screenshots you show are inconclusive with regards to additional AP not functioning correctly, especially without knowing the expected damage range of your weapon (Also note that you don't have str totem down in the second screenshot).

Is your scrolling combat text addon configured to show Windfury Attacks that are missed/dodged/parried?

Can you reproduce single wf procs, or procs without AP bonus, with your Combat Log showing?

**Comment by Nikrotip** [comment]
MSBT addon (which is demonstrated on screenshots) shows correctly how many extra attacks (yellow hits) have been made. If, for example, wf attack is being parried/dodged/missed the addon will show that 1 hit was landed and 1 was parried/dodged/missed.
Thanks for the totem noticing, i'll make sure to test it with a combat log once i hit lvl 40 and get dual wield.

**Comment by Suptski** [comment]
The issue with windfury only granting one extra attack still persists and is in fact very frequent. Here you have not only one but two occurrences of windfury only giving one extra attack as opposed to the two expected:  
![WoWScrnShot_040619_212418](https://user-images.githubusercontent.com/49349935/55674413-a2312c80-58b4-11e9-98be-cd280399e47d.jpg)

**Comment by Easyfraggy** [comment]
Your last screenshot literally shows 2 WF attacks from 1 melee swing.

![image](https://user-images.githubusercontent.com/36134067/55683155-d0f2e580-593c-11e9-97f1-5645bce76e4a.png)

**Comment by Easyfraggy** [comment]
This is an addon issue.

![image](https://user-images.githubusercontent.com/36134067/55683202-7b6b0880-593d-11e9-9396-40c33db18702.png)
