### ISSUE TITLE
{[Spell][Shaman][Lightning Shield]} 

### ISSUE THREAD

**Issue by Nikrotip** [Atlantiss/NetherwingBugtracker#5304]
[//]: # (Enclose links to things related to the bug using http://wowhead.com or any other TBC database.)
[//]: # (You can use screenshot ingame to visual the issue.)
[//]: # (Write your tickets according to the format:)
[//]: # ([Quest][Azuremyst Isle] Red Snapper - Very Tasty!)
[//]: # ([NPC] Magistrix Erona)
[//]: # ([Spell][Mage] Fireball)
[//]: # ([Npc][Drop] Ghostclaw Lynx)
[//]: # ([Web] Armory doesnt work)
[//]: # (To find server revision type `.server info` command in the game chat.)

**Description**: Lightning Shield has 3 charges by default when cast on shaman. Whenever a shaman with lightning shield on him uses any bandages (from First Aid profession) he automatically loses one charge. 

**Current behaviour**: Whenever First Aid bandage is being used on a shaman with lightning shield on, the shaman loses one charge of the shield. It doesn't matter what kind of bandages were used. This only works for the shaman himself. If you try to heal any other player, pet or NPC you will not lose charges of the shield.

**Expected behaviour**: Tooltip: The caster is surrounded by 3 balls of lightning. When a spell, melee or ranged attack hits the caster, the attacker will be struck for X damage. This expends one lightning ball. Only one ball will fire every few seconds. Lasts 10 min. Only one Elemental Shield can be active on the Shaman at any one time.
And of course not to lose a ball from using bandages.

**Server Revision**: 2865
![wowscrnshot_030519_144019](https://user-images.githubusercontent.com/48246079/53806818-ae913500-3f56-11e9-9610-25a3e710570c.jpg)
![wowscrnshot_030519_144025](https://user-images.githubusercontent.com/48246079/53806841-bf41ab00-3f56-11e9-9d0a-52fb16237c4d.jpg)

**Comment by Tenoutoften** [comment]
Already reported https://github.com/Atlantiss/NetherwingBugtracker/issues/5137
