### ISSUE TITLE
Wolfshead Helm doesn't work.

### ISSUE THREAD

**Issue by Dollywog** [Atlantiss/NetherwingBugtracker#5305]
[//]: # (Enclose links to things related to the bug using http://wowhead.com or any other TBC database.)
[//]: # (You can use screenshot ingame to visual the issue.)
[//]: # (Write your tickets according to the format:)
[//]: # ([Quest][Azuremyst Isle] Red Snapper - Very Tasty!)
[//]: # ([NPC] Magistrix Erona)
[//]: # ([Spell][Mage] Fireball)
[//]: # ([Npc][Drop] Ghostclaw Lynx)
[//]: # ([Web] Armory doesnt work)
[//]: # (To find server revision type `.server info` command in the game chat.)

**Description**:  It stopped working after 20:00 Crash 05/03/2019

**Current behaviour**: 

**Expected behaviour**: Should give +20 energy on powershift

**Server Revision**:

**Comment by FabianMueller77** [comment]
can confirm

**Comment by Wolffenstein** [comment]
Fixed
