### ISSUE TITLE
[Core] Players die when logging out/disconnecting in combat.

### ISSUE THREAD

**Issue by Kristoferhh** [Atlantiss/NetherwingBugtracker#5309]
**Description**: Players die when logging out or disconnecting while in combat.

**Current behaviour**: Players die when logging out or disconnecting while in combat.

**Expected behaviour**: Players should either linger for a while until they disappear after about 30s or they disappear instantly, alive.

**Server Revision**: 2868

**Comment by Tenoutoften** [comment]
Can confirm this is happening, it was one of the first issues discovered on the open beta test:
https://github.com/Atlantiss/NetherwingBugtracker/issues/103

**Comment by Zarant** [comment]
I reported a similar issue on beta, issue #3694 might be related to this one.
