### ISSUE TITLE
Victims of Corruption (crystalized bark too low drop)

### ISSUE THREAD

**Issue by ttghnw** [Atlantiss/NetherwingBugtracker#531]
[//]: # (Enclose links to things related to the bug using http://wowhead.com or any other TBC database.)
[//]: # (You can use screenshot ingame to visual the issue.)
[//]: # (Write your tickets according to the format:)
[//]: # ([Quest][Azuremyst Isle] Red Snapper - Very Tasty!)
[//]: # ([NPC] Magistrix Erona)
[//]: # ([Spell][Mage] Fireball)
[//]: # ([Npc][Drop] Ghostclaw Lynx)
[//]: # ([Web] Armory doesnt work)

**Description**: 

**Current behaviour**: **Expected behaviour**: 
The drop for this quest item https://tbc-twinhead.twinstar.cz/?item=23869 should be higher.
Plenty of kills and no drop.

**Server Revision**:

**Comment by aresbrutus** [comment]
Fixed in one of the upcoming updates.
