### ISSUE TITLE
[NPC] SFK Haunting Spirits constantly missing

### ISSUE THREAD

**Issue by Imperator522** [Atlantiss/NetherwingBugtracker#5310]
[//]: # (Enclose links to things related to the bug using http://wowhead.com or any other TBC database.)
[//]: # (You can use screenshot ingame to visual the issue.)
[//]: # (Write your tickets according to the format:)
[//]: # ([Quest][Azuremyst Isle] Red Snapper - Very Tasty!)
[//]: # ([NPC] Magistrix Erona)
[//]: # ([Spell][Mage] Fireball)
[//]: # ([Npc][Drop] Ghostclaw Lynx)
[//]: # ([Web] Armory doesnt work)
[//]: # (To find server revision type `.server info` command in the game chat.)

**Description**: Was two manning SFK with a warrior friend on an level 21 undead priest. I threw on Touch of Weakness to kill the ghosts that are summoned by the curse debuff. The ghosts would never hit, and would not proc Touch of Weakness which should have killed them. (Yes, Touch of Weakness only has one charge). To test, I even stood there for 3 minutes and every hit missed.

**Current behaviour**: Haunting Spirits do not do damage constantly miss - thus they don't proc Touch of Weakness and die

**Expected behaviour**: They should be able to hit, proc the damage from ToW and subsequently die. 

**Server Revision**: Somewhere 2780-2868

**Comment by The14me** [comment]
Rev.3478 not an issue anymore.
Can be closed.
