### ISSUE TITLE
Terestian Illhoof bugged

### ISSUE THREAD

**Issue by KarlDenXII** [Atlantiss/NetherwingBugtracker#5313]
[//]: # (Enclose links to things related to the bug using http://wowhead.com or any other TBC database.)
[//]: # (You can use screenshot ingame to visual the issue.)
[//]: # (Write your tickets according to the format:)
[//]: # ([Quest][Azuremyst Isle] Red Snapper - Very Tasty!)
[//]: # ([NPC] Magistrix Erona)
[//]: # ([Spell][Mage] Fireball)
[//]: # ([Npc][Drop] Ghostclaw Lynx)
[//]: # ([Web] Armory doesnt work)
[//]: # (To find server revision type `.server info` command in the game chat.)

**Description**: 
After a reset on Terestian Illhof he keeps aggroing and reseting.

**Current behaviour**:
After reseting Terestian Illhoof screams, then he summons Kri'lek which aggros and puts the raid in combat.

**Expected behaviour**: 
Terestian Illhoof is not supposed to aggro after a reset.

**Server Revision**: 
2868

**Comment by Kristoferhh** [comment]
He fully resets if you run up the stairs to the bookcase door.

**Comment by Drayo** [comment]
https://github.com/Atlantiss/NetherwingBugtracker/issues/2862

Already reported.
