### ISSUE TITLE
Attumen didnt combine

### ISSUE THREAD

**Issue by Morganczaia** [Atlantiss/NetherwingBugtracker#5314]
[//]: # (Enclose links to things related to the bug using http://wowhead.com or any other TBC database.)
[//]: # (You can use screenshot ingame to visual the issue.)
[//]: # (Write your tickets according to the format:)
[//]: # ([Quest][Azuremyst Isle] Red Snapper - Very Tasty!)
[//]: # ([NPC] Magistrix Erona)
[//]: # ([Spell][Mage] Fireball)
[//]: # ([Npc][Drop] Ghostclaw Lynx)
[//]: # ([Web] Armory doesnt work)
[//]: # (To find server revision type `.server info` command in the game chat.)

**Description**: 
Attumen didnt combine and just stood still for the rest of the fight
**Current behaviour**:
https://www.youtube.com/watch?v=LT3qhF9GAjA&feature=youtu.be
**Expected behaviour**: 
should combine with the horse
**Server Revision**:

**Comment by Wolffenstein** [comment]
Fixed in rev 2877.
