### ISSUE TITLE
Something is wrong with ignore

### ISSUE THREAD

**Issue by ircfelix** [Atlantiss/NetherwingBugtracker#5317]
**Description**: 
Sometimes when you invite a player to a party, you get the message "xy is ignoring you.", even though when they aren't.
In my case I tried to invite someone to a group while I was in OG and he was in a Slave Pens HC group (and inside the dungeon).
Proof:
https://i.imgur.com/ZTsu9EG.jpg

**Current behaviour**:
Sometimes the game tells you that you are ignored by someone, even though the person doesn't ignore you.

**Expected behaviour**: 
The game should only tell you that you're ignored by someone, if it's really the case.

**Server Revision**: 
2868

**Comment by Kristoferhh** [comment]
It's happened to me when someone tries to invite me when I'm in a battleground or when I'm in a heroic dungeon but not in a group.
