### ISSUE TITLE
[Paladin][spell] Blessing of Light

### ISSUE THREAD

**Issue by sifiuocz** [Atlantiss/NetherwingBugtracker#5318]
**Description**: 
The spell is supposed to add flat bonus to the healing done by Holy Light and Flash of Light (The flat bonus is specified in the spell description)
Here is a proof:
https://wowwiki.fandom.com/wiki/Blessing_of_Light?direction=next&oldid=430174

**Current behaviour**:
Currently Blessing of Light(Rank 4) only adds ~100 healing done to the Flash of Light(Rank 7) instead of 185 as the description of the spell says. Same goes for Holy Light.

**Expected behaviour**: 
It's supposed to add the full value as the description of the spell says.

**Server Revision**: 
2868

**Comment by Gedlund** [comment]
Still broken, tested it today would love a fix on this.

**Comment by Saronitian** [comment]
Both Librams of Souls Redeemed  #3460  and Blessing of Light still don't work but from what I can tell after a few tests is that Libram and Blessing scale like +healing does (0.714 for Holy Light and 0.429 for Flash of Light) but they should always give the max amount.

At least neither Libram nor Blessing scale with  [Healing Light] (talent) for extra 12% healing. This is correct!

**Comment by Wolffenstein** [comment]
Fixed in rev 2935.
