### ISSUE TITLE
warrior talent: Bloodcrazy

### ISSUE THREAD

**Issue by jay070** [Atlantiss/NetherwingBugtracker#532]
[//]: # (Enclose links to things related to the bug using http://wowhead.com or any other TBC database.)
[//]: # (You can use screenshot ingame to visual the issue.)
[//]: # (Write your tickets according to the format:)
[//]: # ([Quest][Azuremyst Isle] Red Snapper - Very Tasty!)
[//]: # ([NPC] Magistrix Erona)
[//]: # ([Spell][Mage] Fireball)
[//]: # ([Npc][Drop] Ghostclaw Lynx)
[//]: # ([Web] Armory doesnt work)

**Description**: 
after i get a crit it wont proc blood crazy spell.
![bloodcrazy](https://user-images.githubusercontent.com/43524304/46020736-54ef2980-c0df-11e8-8c43-67d333250e88.png)

**Current behaviour**:

**Expected behaviour**: 

**Server Revision**:

**Comment by jay070** [comment]
to trigger a crit hit i just sit on the ground while fighting

**Comment by Evolvee** [comment]
thats the problem

sitting is excluded from "on crit" talents and abilities...
