### ISSUE TITLE
[Spell] Incorrect lasting time and some bugs/visual bugs.

### ISSUE THREAD

**Issue by MatrixMKD** [Atlantiss/NetherwingBugtracker#5320]
Description: There are couple of spells that aren't working as intended.

Current behaviour: 
• Death Coil 2 seconds.
• Netherweave Net 2 seconds (also useable if u click it without having a target).
• Charge feels like 3+ seconds sometimes.
• Curse of recklessness -> You get visual bug that the target is feared even though it is immune.
• Blessing of Protection -> When BoP is being used on a Warlock, if the Warlock sends pet back on "follow" he can no longer resend it to attack until the time ends.

Expected behaviour:
• Death Coil 3 seconds.
• Netherweave Net 3 seconds (also to not be useable without having a target).
• Charge 1 second.
• Curse of recklessness -> It should say "immune" instead of having "fake" fear icon on the target.
• Blessing of Protection -> BoP should not stop a Warlock from sending their pet to attack.

Server Revision:
2868

Edit: If you need me to have an individual report for each of the bugs, I would do that, let me know. Thx!

**Comment by Godmatik** [comment]
These were all fixed a long time ago.
