### ISSUE TITLE
[Spell][Rogue] Blade Flurry can cleave nearby totems

### ISSUE THREAD

**Issue by Brasso** [Atlantiss/NetherwingBugtracker#5321]
[//]: # (Enclose links to things related to the bug using http://wowhead.com or any other TBC database.)
[//]: # (You can use screenshot ingame to visual the issue.)
[//]: # (Write your tickets according to the format:)
[//]: # ([Quest][Azuremyst Isle] Red Snapper - Very Tasty!)
[//]: # ([NPC] Magistrix Erona)
[//]: # ([Spell][Mage] Fireball)
[//]: # ([Npc][Drop] Ghostclaw Lynx)
[//]: # ([Web] Armory doesnt work)
[//]: # (To find server revision type `.server info` command in the game chat.)

**Description**: 
Just like cleave could destroy totems here before, blade furry is now capable to doing is as well.
**Current behaviour**:
Destroys nearby totems instantly.
**Expected behaviour**: 
Totem need to be targeted specifically to be destroyed.
**Server Revision**: 
2876

**Comment by Wolffenstein** [comment]
Fixed in rev 2880.
