### ISSUE TITLE
[Priest][Spell] Dispell only removes one harmful/beneficial spell with rank 2

### ISSUE THREAD

**Issue by towneh** [Atlantiss/NetherwingBugtracker#5322]
**Description**: 
Dispell(rank 2) only removes one harmful or beneficial spell when it should remove two, as per the tooltip.

![image](https://user-images.githubusercontent.com/25694892/53981590-c27d9800-410a-11e9-9aec-7e80b2adc054.png)

**Current behaviour**:
Dispell(rank 2) only removes one harmful or beneficial spell when it should remove two, as per the tooltip.

**Expected behaviour**: 
Dispell(rank 2) only removes one harmful or beneficial spell when it should remove two, as per the tooltip.

**Server Revision**: 
2876

**Comment by Evolvee** [comment]
it does remove too, but you can resist 1 of them currently

**Comment by towneh** [comment]
OK confirmed with testing against Bladespire Mystics, who have two beneficial buffs on themselves, it does dispell both.

**Comment by towneh** [comment]
https://wow.gamepedia.com/index.php?title=Dispel&oldid=1644346

Dispels can be resisted. In fact, there are two different types of resists:

    Resists (caused by spell hit and resistances)
    Fails (caused by dispel resistance)

Normal resists do only exist for offensive dispels and follow the same rule as any other spell. When a dispel is normally resisted, it does not remove any buffs.

Fails are treated differently. They are calculated per buff and can also occur when dispelling friendly targets. There is an innate chance that this happens (however, this might be a bug). In addition, dispel resistance can be used to increase the chance, such as from [Silent Resolve]. Due to fails being calculated separately for each buff, a dispel which would remove two buffs could eliminate one buff while retaining the other. On spell hit procs are not affected by fails. As such, a Dispel Magic (rank 2) can trigger a proc even though it fails at removing both buffs.

**Comment by gabbat** [comment]
not the first time that this has occured to me (in pve), but this time I clearly remember:
tried dispelling the horror effect from Fen Ray in UB hc. One of my party members had 2 of those debuffs, but dispell only dispelled on of those. there is no dispell resistance whatsoever there, so it should have dispelled both horror effects (it was the same debuff twice). 

I somehow get the feeling that this bug report is not about pvp, but everyone is answering with pvp answers, while the real issue in pve is not even considered.

**Comment by Evolvee** [comment]
why is this report still open? we agreed you can dispel 0, 1 or 2...

**Comment by Evolvee** [comment]
https://github.com/Atlantiss/AtlantissTbcBTOLD/issues/1045

**Comment by Evolvee** [comment]
https://github.com/Atlantiss/AtlantissTbcBTOLD/issues/10454
https://github.com/Schaka/TBC-research/issues/26
https://www.warmane.com/bugtracker/report/46261

**Comment by Evolvee** [comment]
Anyway, this report is about Rank 2 dispel magic/purge removing only 1 buff sometimes, what is the problem with that?

**Comment by gabbat** [comment]
uff, okay.. its not according to threat titel and description but fine, ill open a correct one then

**Comment by towneh** [comment]
If all concerned are happy that both resists and fails are working as intended for dispel mechanics, then I will close accordingly.
