### ISSUE TITLE
[Core] Ingame cap of unique mail recipients

### ISSUE THREAD

**Issue by Umyron** [Atlantiss/NetherwingBugtracker#5323]
Just today something happened to where none of my alts can not send mail to my main. The message: You have reached the in-game cap of unique mail recipients shows up. Yet my main can send mail to my alts and my alts to each other.

 This is obviously an anti spamming mechanic but I have only ever mailed the same 7 characters of mine on the same account.

When researching on WoW forums I found a thread addressing this where a blue poster states that it isn't supposed to be in effect when mailing between alts and guild mates.
 But same blue poster admitted to not being certain of.
Here's a link to that thread: https://us.battle.net/forums/en/wow/topic/20755696013
Its allegedly triggered by x amount of mail over x amount of time but I think those values are broken as I have not played much the last week let alone mailed as much as in previous weeks of play.

**Comment by gabbat** [comment]
this usually means that your mail inbox on your main is full (aka to many items in your mail). this is pretty common

**Comment by nullfoxh** [comment]
Agreed with gabbat. At least on other pservers you would get this error message when the recipients mailbox was full.

**Comment by Tereneckla** [comment]
rev 3058
