### ISSUE TITLE
[Quest][Minor] The Scent of Lar'korwi

### ISSUE THREAD

**Issue by Godmatik** [Atlantiss/NetherwingBugtracker#5324]
**Description**/**Current behaviour** 
The Scent of Lar'korwi in Un'goro, running over the eggs spawns the mate instantly but it just sits there and don't aggro.

**Expected behaviour**: 
Should spawn in the distance and run toward you aggroed.
https://www.youtube.com/watch?v=STBnOaBxzuw @ 34:40

**Comment by Tenoutoften** [comment]
A lot of spawned creatures has 5-10 seconds delay before they aggro, did you test with standing around them for a few sec? I do agree they should aggro right away... Been reported several times

**Comment by Godmatik** [comment]
> A lot of spawned creatures has 5-10 seconds delay before they aggro, did you test with standing around them for a few sec? I do agree they should aggro right away... Been reported several times

The main thing I am trying to highlight is that the 'mate' is supposed to spawn in the distance after a few seconds and run toward you like it shows in Joana video. 

Right now when you run over eggs, the mob just spawns instantly in front of you. It's a minor issue I realize but it makes the quest feel more authentic.

**Comment by Evolvee** [comment]
rev 2891
