### ISSUE TITLE
Queued arena skirmish appears as rated arena

### ISSUE THREAD

**Issue by teddys** [Atlantiss/NetherwingBugtracker#5325]
**Description**:  RIght now you are able to queue for rated 2v2 match even though you have no group. It will result in you sitting in que, but nothing happening.
 
**Expected behaviour**:  You can't que rated 2v2 alone.

**Server Revision**:  2876

**Comment by Wolffenstein** [comment]
How did you manage that?

**Comment by teddys** [comment]
I queued it instead of queueing warsong gulch ... I just clicked on the npc and clicked join arena and only noticed it when it didn't pop after 40 min :D

**Comment by Wolffenstein** [comment]
You sure you didn't join skirmish? The client just grays out the button for 2v2 rated if you're not in a group.

**Comment by teddys** [comment]
You are actually right, it's just a visual bug then.
