### ISSUE TITLE
[Racial ability][orc][blood fury]

### ISSUE THREAD

**Issue by teddys** [Atlantiss/NetherwingBugtracker#5326]
**Description**: https://github.com/ccshiro/cc-buglist/issues/2523

**Current behaviour**: Blood fury doesn't remove any wound poisons when used.

**Expected behaviour**:  Blood fury removes all wound poisons when used.

**Server Revision**:  2716

**Comment by Wolffenstein** [comment]
Weird, I remember fixing it ages ago. Will check

**Comment by Evolvee** [comment]
u kidding?
you removed it from you disabled aura stacking system

**Comment by teddys** [comment]
What's the status on this? It's a big deal to all pvp orcs.

**Comment by liderer** [comment]
this is not only  one problem with rasical man , it affects a lot of mechanics on tbc . 

https://github.com/Atlantiss/NetherwingBugtracker/issues/5000 

this is the reason why my teammate dont want to play on this realm, what is the point of dispelling which effects should not be ?  , same with rasical rasical remove wounds => BOP remove rasical debuff eazy heal without wounds ...

**Comment by Wolffenstein** [comment]
Fixed in rev 2906.

**Comment by teddys** [comment]
It's not fixed

**Comment by Wolffenstein** [comment]
rip
