### ISSUE TITLE
Debuffs not removed after entering arena

### ISSUE THREAD

**Issue by teddys** [Atlantiss/NetherwingBugtracker#5327]
**Current behaviour**: Entering an arena does not remove all negative effects from the player.

**Expected behaviour**:  Upoin entering the arena, all negative effects are removed from the player.

**Server Revision**:  2716

**Comment by ircfelix** [comment]
They also aren't removed when you leave the arena. For instance if you have wound poison, it will stay on you after leaving arena.

**Comment by Wolffenstein** [comment]
Fixed in rev 2889.
