### ISSUE TITLE
Quest, Hillsbrad Foothills, Durnholde Keep, The Rescue

### ISSUE THREAD

**Issue by Erodraeda** [Atlantiss/NetherwingBugtracker#533]
[//]: # (Enclose links to things related to the bug using http://wowhead.com or any other TBC database.)
[//]: # (You can use screenshot ingame to visual the issue.)
[//]: # (Write your tickets according to the format:)
[//]: # ([Quest][Azuremyst Isle] Red Snapper - Very Tasty!)
[//]: # ([NPC] Magistrix Erona)
[//]: # ([Spell][Mage] Fireball)
[//]: # ([Npc][Drop] Ghostclaw Lynx)
[//]: # ([Web] Armory doesnt work)

**Description**: 
Jailor Eston is supposed to have 2 or 3 spawn points, and he was alive in 2 at the same time, which isn't intended.
![screenshot_490](https://user-images.githubusercontent.com/40346279/46021236-95867d00-c0b6-11e8-8ce1-d77b561f61d7.png)
![screenshot_491](https://user-images.githubusercontent.com/40346279/46021237-95867d00-c0b6-11e8-9091-17aa9a6c035f.png)
**Current behaviour**:
Alive in 2 places at the same moment
**Expected behaviour**: 
Only one alive at once
**Server Revision**:

**Comment by The14me** [comment]
https://github.com/Atlantiss/NetherwingBugtracker/issues/523
