### ISSUE TITLE
Shaman Water Walking is dispelled when mount cast is resolved

### ISSUE THREAD

**Issue by Jeff425** [Atlantiss/NetherwingBugtracker#5330]
[//]: # (Enclose links to things related to the bug using http://wowhead.com or any other TBC database.)
[//]: # (You can use screenshot ingame to visual the issue.)
[//]: # (Write your tickets according to the format:)
[//]: # ([Quest][Azuremyst Isle] Red Snapper - Very Tasty!)
[//]: # ([NPC] Magistrix Erona)
[//]: # ([Spell][Mage] Fireball)
[//]: # ([Npc][Drop] Ghostclaw Lynx)
[//]: # ([Web] Armory doesnt work)
[//]: # (To find server revision type `.server info` command in the game chat.)

**Description**: 
The Shaman Water Walking ability is not working correctly

**Current behaviour**:
Currently the Water Walking buff will be dispelled if a character gets on a mount

**Expected behaviour**: 
The Water Walking buff should remain on a player when they get on their mount

**Server Revision**: 
2878

**Comment by Brasso** [comment]
![image](https://user-images.githubusercontent.com/44345420/54018178-42961300-4188-11e9-9501-f6315285860e.png)

**Comment by Jeff425** [comment]
Huh. Thanks for your due diligence.
