### ISSUE TITLE
[Spell] [Shaman] Healing Way Calculation

### ISSUE THREAD

**Issue by Drayo** [Atlantiss/NetherwingBugtracker#5332]
[//]: # (Enclose links to things related to the bug using http://wowhead.com or any other TBC database.)
[//]: # (You can use screenshot ingame to visual the issue.)
[//]: # (Write your tickets according to the format:)
[//]: # ([Quest][Azuremyst Isle] Red Snapper - Very Tasty!)
[//]: # ([NPC] Magistrix Erona)
[//]: # ([Spell][Mage] Fireball)
[//]: # ([Npc][Drop] Ghostclaw Lynx)
[//]: # ([Web] Armory doesnt work)
[//]: # (To find server revision type `.server info` command in the game chat.)

Edit: Not too sure if what way it is broken exactly, two guesses are mentioned below.

**Current behaviour**:

~~It seems like Healing Way increases the Healing done by 18%, but does not take any bonuses into account.~~

It seems Healing Way Stacks x2 and x3 have the same effect as x1. (6%)

**Expected behaviour**: 

~~It should increase the healing done by 18% AFTER all bonuses have been applied.~~

Stacks x2 and x3 should increase the Healing done by 12 and 18% respectively.

**Server Revision**: 2879

Source: https://wow.gamepedia.com/Healing_Way

> Patch 2.1.0 (2007-05-22): This talent now correctly modifies the healing done after all bonus effects have been applied.

**Comment by Brasso** [comment]
Not sure it's working correctly at all. 

With 1718 +healing. Rank 8 healing wave.
0 Stacks: 2434, 2455, 2437, 2467, 2486, 2426, 2446, 2396, 2528, 2432
3 Stacks: 2628, 2541, 2671, 2693, 2590, 2542, 2555, 2684, 2589, 2691
Expected: 18%, observed: 6.84%

With 0 +healing. Rank 8 healing wave.
0 Stacks: 1311, 1281, 1298, 1296, 1307, 1315, 1213, 1298, 1221, 1200
3 Stacks: 1264, 1263, 1343, 1350, 1410, 1362, 1380, 1278, 1383, 1315
Expected: 18%, observed: 4.77%

**Comment by Wolffenstein** [comment]
Fixed in rev 2880.
