### ISSUE TITLE
Chests in high level instances

### ISSUE THREAD

**Issue by Tomekibae** [Atlantiss/NetherwingBugtracker#5333]
I'm not sure whether this is a bug or a conscious decision made by the Devs, but I used to be able to farm chests on my rogue in Mechanar, see here:

https://www.youtube.com/watch?v=MnbjkX70Mlc

However I've just tried to do the same only to be faced with a dungeon containing 0 chests.

One of your GM's told me to write up a report, so here it is - if you have made the decision to remove these chests I do understand. However I would really appreciate it if I could be notified of this, as I have based my professions around it.

Thank you!

**Comment by Valmere** [comment]
I have noticed this too in normal Slave Pens. Following old farming guides on youtube for ancient lichen, there is also supposed to be a chance for either a locked or unlocked chest at some locations, but after probably 50+ runs I have never seen a chest spawn.

**Comment by Tenoutoften** [comment]
Intentionally removed

**Comment by narayagh** [comment]
I haven't encountered a single chest in Outland in general, not even talking about dungeons.
