### ISSUE TITLE
[Quest][Stranglethorn Vale] The Green Hills of Stranglethorn + Chapters

### ISSUE THREAD

**Issue by SoIAS** [Atlantiss/NetherwingBugtracker#5335]
[//]: # (Enclose links to things related to the bug using http://wowhead.com or any other TBC database.)
[//]: # (You can use screenshot ingame to visual the issue.)
[//]: # (Write your tickets according to the format:)
[//]: # ([Quest][Azuremyst Isle] Red Snapper - Very Tasty!)
[//]: # ([NPC] Magistrix Erona)
[//]: # ([Spell][Mage] Fireball)
[//]: # ([Npc][Drop] Ghostclaw Lynx)
[//]: # ([Web] Armory doesnt work)
[//]: # (To find server revision type `.server info` command in the game chat.)

**Description**: 
By completing quests Chapter 1 through 4, player receives chapter 1-4 respectively which are needed for The Green Hills of Stranglethorn. 

**Current behaviour**:
If player has completed any Chapter quest and abandons the The Green Hills of Stranglethorn quest. The chapters are removed from his inventory which causes the The Green Hills of Stranglethorn to be incompletable, because the player is not able to get the removed chapters back (since the quest for them is already completed)

**Expected behaviour**: 
The chapters should not be removed from inventory when The Green Hills of Stranglethorn is abandoned.

**Server Revision**: 
2879

**Comment by Wolffenstein** [comment]
The chapters are properly removed. Barnil Stonepot will offer an option to retrieve them after revision 3164.
