### ISSUE TITLE
Warlock pet does not spawn after mounting and dismounting

### ISSUE THREAD

**Issue by qmsq04** [Atlantiss/NetherwingBugtracker#5337]
[//]: # (Enclose links to things related to the bug using http://wowhead.com or any other TBC database.)
[//]: # (You can use screenshot ingame to visual the issue.)
[//]: # (Write your tickets according to the format:)
[//]: # ([Quest][Azuremyst Isle] Red Snapper - Very Tasty!)
[//]: # ([NPC] Magistrix Erona)
[//]: # ([Spell][Mage] Fireball)
[//]: # ([Npc][Drop] Ghostclaw Lynx)
[//]: # ([Web] Armory doesnt work)
[//]: # (To find server revision type `.server info` command in the game chat.)

**Description**: Warlock pet does not respawn after mounting/dismounting 

**Current behaviour**: Sometimes warlock pet does not spawn after you mount/dismount, leaving you with no shard or any sign that you do not have pet

**Expected behaviour**: Have a pet after you dismunt

**Server Revision**: 2879

**Comment by Zarant** [comment]
Issue seems fixed, I can't reproduce it.
