### ISSUE TITLE
[NPC] Warp Chaser [Loot] Warped Flesh

### ISSUE THREAD

**Issue by The14me** [Atlantiss/NetherwingBugtracker#5338]
**Current behaviour**:Dont drop any Warped Flesh

**Expected behaviour**: Suppose to have.
https://www.wowhead.com/npc=18884/warp-chaser
https://www.wowhead.com/item=27681/warped-flesh#dropped-by

**Server Revision**:

**Comment by Manaci** [comment]
Fixed
