### ISSUE TITLE
Snake trap chases / attacks in vanish & Shiv has a problem applying poison in certain situations.

### ISSUE THREAD

**Issue by Johnkeyz** [Atlantiss/NetherwingBugtracker#5339]
[//]: # (https://www.twitch.tv/videos/392898136)
[//]: # (Write your tickets according to the format:)
[//]: # ([Web] Armory doesnt work)
[//]: # (To find server revision type `.server info` command in the game chat.)

**Description**: 
Snake trap: I walk on snake trap, snakes attack me, i cloak of shadows and vanish (no dots or nothing) Snakes keep chasing me and attacking / breaking stealth.

Shiv: If you shiv a target, while moving out of attack range, or turn your back while being out of melee range, unsure which one it is, the poison does not apply. I recorded this and posted a link to a video showing the issue... Also we captured Abolish poison bug randomly as well, others have made post about that topic as well, abolish poison does not dispel poisons after the initial dispel, but we captured it as well on the shiv video. Worth mentioning that i have 0/5 in vile poisons in the video.

**Current behaviour**: What i wrote above

**Expected behaviour**: Snake trap: to stop chasing the stealthed target once they stealth, unless there is hunters mark or similiar.

Shiv: To apply poison as soon as shiv hits, it seems it appears 0.5-1 second later, causing some issues if you move out of range or turn your back or something.

**Server Revision**: 2879

**Comment by Johnkeyz** [comment]
Apparently i messed up something and didn't link the shiv / abolish poison clip. But here it is: https://www.twitch.tv/videos/392898136

**Comment by HukNetherwing** [comment]
This is a super annoying bug

**Comment by Johnkeyz** [comment]
Aye, it's super annoying... I was able to reproduce the shiv bug a couple of times, it seems like a range issue, don't know, if direction you face matters, i feel like it shouldn't. And yeah snake trap being immune to damage and chasing after in vanish is so freaking annoying and broken... Are they even still invulnerable? (kinda been having a break)
