### ISSUE TITLE
[spell][shaman][mana tide totem]

### ISSUE THREAD

**Issue by teddys** [Atlantiss/NetherwingBugtracker#5340]
**Current behaviour**: Mana tide totem doesn't benefit people that are out of its line of sight.

**Expected behaviour**: Mana tide totem (same as all other totems that work correctly btw) benefit people thare are out of its line of sight.

**Server Revision**: 2879

high prio please

**Comment by Wolffenstein** [comment]
Fixed in rev 2880.
