### ISSUE TITLE
[Hunter] [Frost Trap] Doesn't always apply slow.

### ISSUE THREAD

**Issue by gunzbngbng** [Atlantiss/NetherwingBugtracker#5341]
[//]: # (Enclose links to things related to the bug using http://wowhead.com or any other TBC database.)
[//]: # (You can use screenshot ingame to visual the issue.)
[//]: # (Write your tickets according to the format:)
[//]: # ([Quest][Azuremyst Isle] Red Snapper - Very Tasty!)
[//]: # ([NPC] Magistrix Erona)
[//]: # ([Spell][Mage] Fireball)
[//]: # ([Npc][Drop] Ghostclaw Lynx)
[//]: # ([Web] Armory doesnt work)
[//]: # (To find server revision type `.server info` command in the game chat.)

**Description**: Frost trap, at least in arena, sometimes will not apply to players who should be slowed by it.

**Current behaviour**:  Sometimes Frost Trap is entirely ignored by a player.  Will run in and out repeatedly without being slowed.

**Expected behaviour**: Only players immune to slow should be disaffected by Frost Trap.  Players shifting should not break Frost Trap.

**Server Revision**: 2879

**Comment by Manaci** [comment]
Fixed in rev 3214
