### ISSUE TITLE
[Spell] Manticron Cubes applying too long of a debuff

### ISSUE THREAD

**Issue by Tsaav** [Atlantiss/NetherwingBugtracker#5343]
[//]: # (Enclose links to things related to the bug using http://wowhead.com or any other TBC database.)
[//]: # (You can use screenshot ingame to visual the issue.)
[//]: # (Write your tickets according to the format:)
[//]: # ([Quest][Azuremyst Isle] Red Snapper - Very Tasty!)
[//]: # ([NPC] Magistrix Erona)
[//]: # ([Spell][Mage] Fireball)
[//]: # ([Npc][Drop] Ghostclaw Lynx)
[//]: # ([Web] Armory doesnt work)
[//]: # (To find server revision type `.server info` command in the game chat.)

**Description**: In Magtheridon's Lair, after using the Manticron Cube, a 3 minute debuff is placed on the player, instead of a 2 minute debuff.

**Current behaviour**: Players are locked from using Manticron Cubes for 3 minutes.

**Expected behaviour**: Players should be able to use the cubes after only 2 minutes.

Source: https://www.youtube.com/watch?v=QpgdAHJANcA&t=3m23s At 3 minutes 23 seconds, the paladin activates the cube, at 5:17 the debuff falls off.

**Server Revision**: 2879

**Comment by Tsaav** [comment]
Here's a clip of Netherwing's behavior: https://clips.twitch.tv/RealGrossWoodpeckerJKanStyle

You can see I got a 3 minute debuff after using the cube

**Comment by Drayo** [comment]
Pretty sure that video of Nihilums kill is not their actual first kill. Kungen even said in /rw at the end "Bravo First Try" so I assume they already had it more or less on farm at that point.

World third kill from Last Resort has a full 15 Minute video, the mage clicks at 8.50 and the debuff runs out at 11.55. 

https://youtu.be/v0PNXZYuAnU?t=532

**Comment by Wolffenstein** [comment]
2.0.3 spell data has 180s cooldown. It's working correctly.
