### ISSUE TITLE
[warrior][spell reflection]

### ISSUE THREAD

**Issue by teddys** [Atlantiss/NetherwingBugtracker#5345]
**Description**:  https://youtu.be/Z_4QCCzInVs?t=49

**Current behaviour**: After reflecting a damaging spell, it doesn't show how much damage it did to the enemy target. See the video when warrior reflects ice lance? The damage shows on his screen.

**Expected behaviour**:  When you reflect a damaging spell, you should be able to see how much damage it does.

**Server Revision**:  2879

**Comment by numiee** [comment]
can confirm it doesnt reflect any damage at all in PvE, however it seems to give the threat.

**Comment by Wolffenstein** [comment]
Should be fixed
