### ISSUE TITLE
[Item][Engineering] Gnomish Battle Chicken doesn't attack or giving melee haste buff

### ISSUE THREAD

**Issue by CuteUndeadGirl** [Atlantiss/NetherwingBugtracker#5347]
**Current behaviour**: Gnomish Battle Chicken doesn't attack the taget, just standing nearby and doing nothing. Not enrages, not giving melee haste buff. (also doing weird stuff sometimes, like running not to the closest mob, but to the further ones, ninja pulls them = wipe).

**Expected behaviour**: "It hits for 1 damage every 2 seconds. If it enrages (does so often) it deals 40-70 damage (against a lvl70 target) every 1 second, lasts 10 seconds per enrage. Occassionally it Battle Squawks, the entire group has +5% attackspeed for 5 minutes." 

**DB links**: https://classicdb.ch/?item=10725#comments
https://www.wowhead.com/item=10725/gnomish-battle-chicken#comments

**Screenshots**: 
![image](https://user-images.githubusercontent.com/48400222/54081040-68a1eb80-431f-11e9-8e1a-5008fcb6c1e3.png)

![image](https://user-images.githubusercontent.com/48400222/54081045-735c8080-431f-11e9-9838-681021448d1b.png)

![image](https://user-images.githubusercontent.com/48400222/54081047-79526180-431f-11e9-9814-2b3443508697.png)

![image](https://user-images.githubusercontent.com/48400222/54081049-81aa9c80-431f-11e9-8294-ca4a37815794.png)

**Comment by ircfelix** [comment]
Many strong blizzlike melee buffs (e.g. Armor reduction stacking) have been intentionally nerfed to make the content feel more blizzlike. However, for top guilds this only means, that they need to replace melee DPS with ranged DPS and basically makes melees useless for specific encounters.
Maybe it is the same for your chickin.

**Comment by ircfelix** [comment]
P.s. classicdb is not a valid source. Please type .research in NW discord to find a quick guide on how to find old and valid sources.

**Comment by CuteUndeadGirl** [comment]
"intentionally broken X to make the content feel more blizzlike"? LOL!

**Comment by ircfelix** [comment]
Well, look at the annihilator report. Afaik it worked (and should still) but was nerfed.

**Comment by Unrelented** [comment]
Can we get a bump to confirm this was " Nerfed " 
Just remove it from the game then, dont tantalize a persons childhood. 
This alone makes me second guess playing here at level 45... ( Wasted hours then at that point ) 
Seems dumb that I chose Gnomish Engineering now huh? Heard the turret doesn't work along with a lot of the other pets. Makes the server seem trashy...

**Comment by Vidovit** [comment]
Confirmed that it still doesn't work - 10.11.2019

**Comment by Gurkenstyle** [comment]
Build this one for my 39 twink, sadly still not working, 26hp and doesn't attack with engineering skill 300

**Comment by Godmatik** [comment]
Duplicate issue now - was fully fixed - can be closed

**Comment by EtheriousNW** [comment]
Fixed a while back.
