### ISSUE TITLE
[Horde][Quest][Hinterlands] Horde Supply Crates - "A sticky situation" Quest

### ISSUE THREAD

**Issue by drewk8** [Atlantiss/NetherwingBugtracker#5349]
**Description**: 
Horde supply crates are empty and not despawning. 

**Current behavior**:
Some crates in the Skulk Rock cave (and outside) are empty and do not despawn. The need to be looted for the "A sticky situation" quest.

**Expected behavior**: 
Empty crates should despawn.

**Server Revision**: 
2879

**Comment by duzyizly** [comment]
all of em contains loot and despawns (ptr 3390)
![WoWScrnShot_061920_130345](https://user-images.githubusercontent.com/43931626/85126365-a59ca380-b22d-11ea-8e19-fc4602e8721e.jpg)
![WoWScrnShot_061920_130347](https://user-images.githubusercontent.com/43931626/85126367-a6cdd080-b22d-11ea-8e74-5e02ca31c4b5.jpg)
![WoWScrnShot_061920_130408](https://user-images.githubusercontent.com/43931626/85126368-a6cdd080-b22d-11ea-8cf5-8199a3cd7c4b.jpg)
![WoWScrnShot_061920_130413](https://user-images.githubusercontent.com/43931626/85126371-a7666700-b22d-11ea-837a-145782b71116.jpg)
![WoWScrnShot_061920_130451](https://user-images.githubusercontent.com/43931626/85126372-a7666700-b22d-11ea-9c60-49ab742fecad.jpg)
![WoWScrnShot_061920_130456](https://user-images.githubusercontent.com/43931626/85126373-a7fefd80-b22d-11ea-983d-7f6448359118.jpg)
![WoWScrnShot_061920_130503](https://user-images.githubusercontent.com/43931626/85126375-a8979400-b22d-11ea-816b-b31e4a98012b.jpg)
![WoWScrnShot_061920_130509](https://user-images.githubusercontent.com/43931626/85126377-a8979400-b22d-11ea-93d2-f3a353a7e5f7.jpg)
