### ISSUE TITLE
sudden minus armor?

### ISSUE THREAD

**Issue by Kjaeren** [Atlantiss/NetherwingBugtracker#5351]
[//]: # (Enclose links to things related to the bug using http://wowhead.com or any other TBC database.)
[//]: # (You can use screenshot ingame to visual the issue.)
[//]: # (Write your tickets according to the format:)
[//]: # ([Quest][Azuremyst Isle] Red Snapper - Very Tasty!)
[//]: # ([NPC] Magistrix Erona)
[//]: # ([Spell][Mage] Fireball)
[//]: # ([Npc][Drop] Ghostclaw Lynx)
[//]: # ([Web] Armory doesnt work)
[//]: # (To find server revision type `.server info` command in the game chat.)

**Description**: 
1st screenshot: minus 691 armor? no current debuffs
1st screenshot is when exited a dungeon
2nd screenshot: 0 minus armor?
2nd screenshot is after relog

**Current behaviour**:

**Expected behaviour**: 
there should not be minus armor.

**Server Revision**: 
![WoWScrnShot_031019_143616](https://user-images.githubusercontent.com/48409365/54085780-f098ed00-4341-11e9-9c42-133835b023dd.jpg)
![WoWScrnShot_031019_144025](https://user-images.githubusercontent.com/48409365/54085822-7e74d800-4342-11e9-85c3-cdc1940ea05a.jpg)

**Comment by Rixh1** [comment]
Might just be visual? Try to delete your cache

**Comment by Valmere** [comment]
fairly certain this is just a visual bug that happens on private servers, might have occurred on retail too

**Comment by Manaci** [comment]
Visual bug
