### ISSUE TITLE
[Quest][Loch Modan] The Algaz Gauntlet

### ISSUE THREAD

**Issue by Tasserski** [Atlantiss/NetherwingBugtracker#5352]
**Description**: 

**Current behaviour**:
The "Traverse Dun Algaz" objective of this quest auto-completes when all of the mobs required have been killed. One one of my characters, the objective did not complete from correct execution, which would be running to the end of the tunnel at the border of the Wetlands.

**Expected behaviour**: 
The objective of "Traverse Dun Algaz" should complete when the player reaches a trigger at the end of the tunnel from Loch Modan to the Wetlands.

**Server Revision**: 
2879

**Comment by Zarant** [comment]
Seems fixed, I was not able to reproduce this bug.
