### ISSUE TITLE
[NPC] Kurzen Witch Doctor

### ISSUE THREAD

**Issue by Tasserski** [Atlantiss/NetherwingBugtracker#5353]
**Description**: 
These NPCs use the wrong totem model.

**Current behaviour**:
The NPCs use the draenei totem model.

**Expected behaviour**: 
The NPCs should use the horde totem model, seeing as they are vanilla mobs.

**Server Revision**: 
2879

**Comment by The14me** [comment]
Must be fixed with latest rev.
Can be closed.
