### ISSUE TITLE
[Core] Melee haste debuffs should not affect ranged attack speed

### ISSUE THREAD

**Issue by Zarant** [Atlantiss/NetherwingBugtracker#5354]
**Description**: Melee haste debuffs like frost armor should not modify ranged attack speed

**Current behaviour**: Melee haste debuffs are also increasing ranged swing timer

**Expected behaviour**: Melee haste debuffs should not affect ranged attack speed

Source: https://youtu.be/FAz6E6W4T-I?t=1064

![LqYCMC51qP](https://user-images.githubusercontent.com/26726709/54091349-fa304e00-435d-11e9-8d46-9b572370cd34.png)
If you look closely at his swing timer, he has the frost armor debuff and his swing timer addon is returning a 2.6s swing timer on auto shot.
Since he is using the S3 bow (3.0) speed and a quiver (15% haste), his swing timer should be 3.0/1.15 = 2.6, which indicates that frost armor should not interfere with the ranged attack speed.

**Server Revision**: 2879

**Comment by Godmatik** [comment]
Must have been fixed at some point - my ranged attack speed stays the same regardless if I have a melee haste debuff on me or not.

Closing.
