### ISSUE TITLE
[Paladin] Greater Blessing of Sanctuary (Rank 1)

### ISSUE THREAD

**Issue by Lariari** [Atlantiss/NetherwingBugtracker#5357]
Greater Blessing of Sanctuary (Rank 1) can't be picked up at 60 because the requirement is Blessing of Sanctuary (Rank 5) and Blessing of Sanctuary (Rank 4), You learn Rank 5 at 70.
![WoWScrnShot_031019_200127](https://user-images.githubusercontent.com/43853367/54094611-3a98c780-4370-11e9-9fc0-6db95b4f9fae.jpg)

**Comment by Tenoutoften** [comment]
Another issue related to paladin trainers:
https://github.com/Atlantiss/NetherwingBugtracker/issues/889

**Comment by Wolffenstein** [comment]
Fixed in rev 2921.
