### ISSUE TITLE
[Paladin] Quest for Epic mount. Quest item

### ISSUE THREAD

**Issue by Fiordes** [Atlantiss/NetherwingBugtracker#5358]
Description:
Was problems with Arcanite barding, its disappeared.
I abandon quest https://wowwiki.fandom.com/wiki/Quest:Ancient_Equine_Spirit and take it 1 more time, and Lord Grayson give me barding, but [Manna-Enriched Horse Feed] disappeared from my inventory( from quest https://wowwiki.fandom.com/wiki/Quest:Manna-Enriched_Horse_Feed).
Now I can't take this quest/feed bcs I do it before.

Current behaviour:
Merideth Carlson don't give free feed to people who have ended she's quest.

Expected behaviour:
Patch 1.5.0 (2005-06-07): Merideth Carlson should only hand out her free horse feed now to people who have already completed the quest for it.

**Comment by Fiordes** [comment]
Description:
Was problems with Arcanite barding, its disappeared.
I abandon quest https://wowwiki.fandom.com/wiki/Quest:Ancient_Equine_Spirit and take it 1 more time, and Lord Grayson give me barding, but [Manna-Enriched Horse Feed] disappeared from my inventory( from quest https://wowwiki.fandom.com/wiki/Quest:Manna-Enriched_Horse_Feed). 
Now I can't take this quest bcs I do it before.

**Comment by Brian-Shaw** [comment]
I had this problem as well. I made an in game ticket but was told do write it here. If this is 17 days old I'm afraid it won't get fixed soon =(. My character is Mogthowr (alliance)

**Comment by Evolvee** [comment]
fixed in rev 2971
