### ISSUE TITLE
[Quest][Dustwallow Marsh] The Essence of Enmity

### ISSUE THREAD

**Issue by Tasserski** [Atlantiss/NetherwingBugtracker#5359]
**Description**: 
Using the quest item Brogg's Totem can despawn live dragons.

**Current behaviour**:
If used on a quest mob corpse when another, alive quest mob is nearby, Brogg's Totem will also despawn the live quest mob.

**Expected behaviour**: 
Despawning live mobs is likely unintentional.

**Server Revision**: 
2879

**Comment by The14me** [comment]
Rev.3483 not an issue anymore.If u try it on alive dragon--> ''Invalid target''
