### ISSUE TITLE
Rarespawn Eck'Alom

### ISSUE THREAD

**Issue by Trix115** [Atlantiss/NetherwingBugtracker#536]
Just killed the rare Eck'Alom in ashenvail, and it had 0 loot. Seems unrealistic for a rare spawn to not have any loot.
Entry: 10642, id: 1

**Comment by aresbrutus** [comment]
We have done the research but not ALL rares are bound to have a uncommon+ item. But the rare loot system is also at the moment getting overhauled so drops from rares currently do not reflect the same as during launch.
