### ISSUE TITLE
[Spell][Paladin] Seal of Justice

### ISSUE THREAD

**Issue by Tasserski** [Atlantiss/NetherwingBugtracker#5360]
**Description**: 
The Judgement of Seal of Justice does not limit druid forms' movement speed.

**Current behaviour**:
Judging Seal of Justice should limit a player's movement speed to 100%.

**Expected behaviour**: 
Judging Seal of Justice does not limit druid's movement speed to 100% when they use forms that increase movement speed.

**Server Revision**: 
2883

**Comment by dinsfireyo** [comment]
It does you are tripping

**Comment by Tasserski** [comment]
It didn't when we tested it last night in a duel. Could it be an issue with spell ranks, then? We were fairly low level.

**Comment by Tenoutoften** [comment]
Your issue is invalid because the effects of limiting a players movement speed only applies to rank 2, which is learned at level 48.

**Comment by Tenoutoften** [comment]
![](https://i.gyazo.com/0d528867a334692cba0733553dac59d7.png)
![](https://i.gyazo.com/4b7a6540238bdaf5d9184cb70805ed9e.png)
