### ISSUE TITLE
[Priest] [Spell] Inspiration not proccing properly

### ISSUE THREAD

**Issue by Spaztick** [Atlantiss/NetherwingBugtracker#5362]
**Description**: 
 Inspiration not proccing on self crits for Binding Heal or any crits for Prayer of healing.

**Server Revision**: 
2883

**Comment by Tenoutoften** [comment]
Should definitely proc on those:
![](https://i.gyazo.com/7157be9edeb0de204817f30336e44cf2.png)
[[Spell]Inspiration(Rank 1)#14892](https://db.excalibur.ws/?spell=14892)
[[Spell]Inspiration(Rank 2)#15362](https://db.excalibur.ws/?spell=15362)
[[Spell]Inspiration(Rank 3)#15363](https://db.excalibur.ws/?spell=15363)

**Comment by gabbat** [comment]
![image](https://user-images.githubusercontent.com/38278426/54271772-74d9b300-4582-11e9-8dfa-7951c4d7dd57.png)
prayer or healing does at least selfbuff inspiration from crits on yourself, didnt test for other party members.
Bindingheal however does not procc inspiration on yourself, which might be a correct interpretation of "your targets armor", not sure how it is supposed to work. It does procc inspiration on your target. I think it would be a good idea to support your report with screenshots

**Comment by Spaztick** [comment]
Yea I'll upload some stuff later today. It may be PoH is inconsistent in application, but Binding Heal definitely did not buff myself.

**Comment by Spaztick** [comment]
![poh](https://user-images.githubusercontent.com/29140342/54323685-5f877780-45c8-11e9-812e-0ae99e3f6fe2.jpg)
![binding](https://user-images.githubusercontent.com/29140342/54323772-affed500-45c8-11e9-971e-675c8ff43d9a.jpg)
Interestingly PoH did not proc inspiration on me (solo PoH by myself) and didn't proc off Binding Heal on either me or my target. My target was out of party, but I have had it work before with someone in my party. This might be a clue for what the issue is.

**Comment by Wolffenstein** [comment]
Fixed in rev 2889.
