### ISSUE TITLE
Demon armor

### ISSUE THREAD

**Issue by Vorborg91** [Atlantiss/NetherwingBugtracker#5363]
[//]: # (Enclose links to things related to the bug using http://wowhead.com or any other TBC database.)
[//]: # (You can use screenshot ingame to visual the issue.)
[//]: # (Write your tickets according to the format:)
[//]: # ([Quest][Azuremyst Isle] Red Snapper - Very Tasty!)
[//]: # ([NPC] Magistrix Erona)
[//]: # ([Spell][Mage] Fireball)
[//]: # ([Npc][Drop] Ghostclaw Lynx)
[//]: # ([Web] Armory doesnt work)
[//]: # (To find server revision type `.server info` command in the game chat.)

**Description**:  When my demon armor rank 3 is applied, it turns into rank 2.

**Current behaviour**: Same as above.

**Expected behaviour**: That it becomes the rank you have

**Server Revision**:  Netherwing
![WoWScrnShot_031119_054207](https://user-images.githubusercontent.com/48426819/54153298-88c8cc00-443f-11e9-8f5b-b5cb2ddc197c.jpg)
![WoWScrnShot_031119_054210](https://user-images.githubusercontent.com/48426819/54153302-8bc3bc80-443f-11e9-830d-7e2edfa70b66.jpg)

**Comment by Tenoutoften** [comment]
It doesn't turn into rank 2. What it looks like you have done is placing 3 points into Demonic Aegis, this increases the effect of Demon Armor by 30%.

Demon armor rank 3 gives 390 armor
390 armor * 1.3 = 507 armor

Talents effect on abilities wont be updated on aura buffs on yourself.

Working as intended.
