### ISSUE TITLE
Fishing nodes bugged in AM

### ISSUE THREAD

**Issue by caiopmartins** [Atlantiss/NetherwingBugtracker#5364]
[//]: # (Enclose links to things related to the bug using http://wowhead.com or any other TBC database.)
[//]: # (You can use screenshot ingame to visual the issue.)
[//]: # (Write your tickets according to the format:)
[//]: # ([Quest][Azuremyst Isle] Red Snapper - Very Tasty!)
[//]: # ([NPC] Magistrix Erona)
[//]: # ([Spell][Mage] Fireball)
[//]: # ([Npc][Drop] Ghostclaw Lynx)
[//]: # ([Web] Armory doesnt work)
[//]: # (To find server revision type `.server info` command in the game chat.)

**Description**: 
Two bugged Floating Wreckages in Alterac Mountains
One at 35.5-12.9 and another at 29.7-38.3

**Current behaviour**:
You cannot fish in or near them

**Expected behaviour**: 
You should be able to fish on them

**Server Revision**: 
2883

**Comment by Manaci** [comment]
Dead issue
