### ISSUE TITLE
[Talent][Druid[ After respec I should not generate rage after critting ability 'Primal Fury'

### ISSUE THREAD

**Issue by ndnd123** [Atlantiss/NetherwingBugtracker#5365]
[//]: # (Enclose links to things related to the bug using http://wowhead.com or any other TBC database.)
[//]: # (You can use screenshot ingame to visual the issue.)
[//]: # (Write your tickets according to the format:)
[//]: # ([Quest][Azuremyst Isle] Red Snapper - Very Tasty!)
[//]: # ([NPC] Magistrix Erona)
[//]: # ([Spell][Mage] Fireball)
[//]: # ([Npc][Drop] Ghostclaw Lynx)
[//]: # ([Web] Armory doesnt work)
[//]: # (To find server revision type `.server info` command in the game chat.)

**Description**: 

**Current behaviour**:
I dont have the ability "primal fury" because I respecced from feral to resto but when I crit I still get extra rage.
**Expected behaviour**: 
No extra rage.
**Server Revision**:

**Comment by Tenoutoften** [comment]
Did you try re-logging?

**Comment by Wolffenstein** [comment]
Fixed in rev 2889.
