### ISSUE TITLE
[Spell][Dungeon] Blessing of Auchindoun is lost when ressing at an instance, must run outside then back inside to regain it

### ISSUE THREAD

**Issue by ghost** [Atlantiss/NetherwingBugtracker#5366]
**Description**: 
https://tbc-twinhead.twinstar.cz/?spell=33377
This buff is required to gain Spirit Shards from killing bosses in dungeons. It's problematic, then, that this bug specifically applies to dungeons and is annoying to workaround.

**Current behaviour**:
Die at instance
Ghostwalk inside
Blessing of Auchindoun is lost!
Run out, Blessing of Auchindoun is regained, run inside, Blessing of Auchindoun remains

**Expected behaviour**: 
Die at instance
Ghostwalk inside
Blessing of Auchindoun is reapplied without having to rezone

**Server Revision**: 
2883

**Comment by Wolffenstein** [comment]
fixed
