### ISSUE TITLE
[Raid][Magtheridon's Lair] Missing Yell Texts and sounds

### ISSUE THREAD

**Issue by Firroth** [Atlantiss/NetherwingBugtracker#5367]
**Current behaviour**:
Boss doesn't yell any text which he should, when not in combat. Most of his yells during combat also seem to not work. Only working one so far was when he killed player, anything else doesn't.

**Expected behaviour**: 
He should yell randomly one of these texts when out of combat.

![Screenshot_1](https://user-images.githubusercontent.com/43505196/54164629-9db45800-445d-11e9-92f2-17d5cedf3b41.png)

And these when engaged in combat: (depending on scenario)

![Screenshot_2](https://user-images.githubusercontent.com/43505196/54164672-c4728e80-445d-11e9-81db-870abc454163.png)

**Server Revision**: 
2884

**Comment by Wolffenstein** [comment]
Not sure what's wrong with combat texts, but the ones out of combat are only in Blood Furnace.

**Comment by Firroth** [comment]
Yeah, on Blood Furnace I saw them. But in Lair not, but they should be there.

![Screenshot_4](https://user-images.githubusercontent.com/43505196/54166664-8d54ab00-4466-11e9-9f91-42ad66ec0df6.png)

![Screenshot_5](https://user-images.githubusercontent.com/43505196/54166674-96de1300-4466-11e9-8b82-b790cc301ef1.png)

And as seen here "before pull" there can be seen 1 yell on chat.
https://youtu.be/Av8wxeckDf4?t=21
