### ISSUE TITLE
[Dungeon][The Underbog][NPC] Swamplord Musel'ek and Windcaller Claw

### ISSUE THREAD

**Issue by rachmin** [Atlantiss/NetherwingBugtracker#5368]
[//]: # (Enclose links to things related to the bug using http://wowhead.com or any other TBC database.)
[//]: # (You can use screenshot ingame to visual the issue.)
[//]: # (Write your tickets according to the format:)
[//]: # ([Quest][Azuremyst Isle] Red Snapper - Very Tasty!)
[//]: # ([NPC] Magistrix Erona)
[//]: # ([Spell][Mage] Fireball)
[//]: # ([Npc][Drop] Ghostclaw Lynx)
[//]: # ([Web] Armory doesnt work)
[//]: # (To find server revision type `.server info` command in the game chat.)

**Description**: 
Regarding https://github.com/Atlantiss/NetherwingBugtracker/issues/4909 and https://github.com/Atlantiss/NetherwingBugtracker/issues/5082 there is (still) a bug with the third boss of the Underbog (Swamplord Musel'ek and "Claw"). It seems to occur, when you wipe or reset the encounter, and it especially affects Claw's beahaviour.

**Current behaviour**:
1) After your group "kills" Claw first (take him to or under 20% HP), he turns friendly and you get the credit for the associated quest (atleast if your are alive at this moment; couldn't test it if you are dead referring https://github.com/Atlantiss/NetherwingBugtracker/issues/5064). When your group wipes after that and you engage a new fight with the encounter, "Claw" doesn't take any damage. He is not immune to damage, he takes normal damage according to the combat log, but he doesn't drop below 100% (referring https://github.com/Atlantiss/NetherwingBugtracker/issues/4909 and https://github.com/Atlantiss/NetherwingBugtracker/issues/5082 and https://github.com/Atlantiss/NetherwingBugtracker/issues/5191#issuecomment-469430268 [Claw didn't despawn for us]).
2) After your group wipes or reset the encounter (for example feign death or vanish), the encounter/NPCs doesn't reset their position properly or don't reset to their starting position. Instead after a wipe, they stop standing on the position, where the killed the last player (referring https://github.com/Atlantiss/NetherwingBugtracker/issues/4909). Both NPCs are still linked when pulled from their "new" position.

**Expected behaviour**: 
to 1) As long as "Claw" is above 20% HP he is hostile to the player, can be attacked by the player and takes the normal amount of damage; at 20% he turns friendly, transforms to his Tauren form and no longer takes damage. There is no boss ability by the encounter himself, that reduces the damage taken by Claw or makes him invulernable before 20% (even after you kited Claw and killed the Swamplord while kiting, see annotation).
It seems, that there is a bug with turning Claw friendly and resetting him to hostile properly.

to 2) After a wipe or reset, both NPC move to their starting position.

Annotation: Kiting is a legit and valid tactic for the encounter.
https://wow.gamepedia.com/index.php?title=Swamplord_Musel%27ek&oldid=897180 (Sept 2007)
https://www.wowhead.com/npc=17826/swamplord-muselek#comments (search for "kite" and "kiting")

Referring https://github.com/Atlantiss/NetherwingBugtracker/issues/3019 we got the loot from the Swamplord nevertheless.

**Server Revision**: 2883

**Comment by Grommik** [comment]
HI all, 
this happend to us right now. According to description above, Claw stopped at the position, where last player died. Also tryed another pulls, where I took him back to his original or safe positions with bubble in hope we could skip this boss . Did not help. We could pull him from more than normal distance, so he did not allow us go around.

![WoWScrnShot_062219_230200](https://user-images.githubusercontent.com/52113745/59969107-8437a780-9546-11e9-8aa0-f9d899daf43f.jpg)

![WoWScrnShot_062219_225344](https://user-images.githubusercontent.com/52113745/59969060-60c02d00-9545-11e9-9096-8d7d22035678.jpg)
