### ISSUE TITLE
(Quest) Control- Azuremyst Isle - Class Quest - Mage Lvl 10

### ISSUE THREAD

**Issue by liin22** [Atlantiss/NetherwingBugtracker#5369]
Kill Murlocs Until quest mob Spawns.

Quest Mob Never spawns

**Comment by Evolvee** [comment]
it does spawn, but if you dont engage it within +- 40 seconds, it becomes hidden again

**Comment by KevinTyrrell** [comment]
Spent about an 15 minutes grinding murlocs at coords 34,16 while having this quest in my log. It's possible I may have missed his spawn once, but I went here to read @Evolvee 's comment. 
I spent about 30 minutes more grinding murlocs, all the while spamming `/tar Que` to target the mob. Unfortunately no such mob spawned. I'm not totally convinced this quest is working as intended.

**Comment by Evolvee** [comment]
hmm, i will try, maybe it didnt respawn due to core issue with respawns

**Comment by simson-suse** [comment]
So I can confirm that the quest works, it just takes ages, like 30 - 45 minutes as a small group.
