### ISSUE TITLE
Quest, Shadowfang Keep, The Book of  Ur

### ISSUE THREAD

**Issue by Erodraeda** [Atlantiss/NetherwingBugtracker#537]
[//]: # (Enclose links to things related to the bug using http://wowhead.com or any other TBC database.)
[//]: # (You can use screenshot ingame to visual the issue.)
[//]: # (Write your tickets according to the format:)
[//]: # ([Quest][Azuremyst Isle] Red Snapper - Very Tasty!)
[//]: # ([NPC] Magistrix Erona)
[//]: # ([Spell][Mage] Fireball)
[//]: # ([Npc][Drop] Ghostclaw Lynx)
[//]: # ([Web] Armory doesnt work)

**Description**: 
After completing the quest, the NPC still had the yellow question mark above his head
![screenshot_492](https://user-images.githubusercontent.com/40346279/46025853-3ded0f00-c0c0-11e8-8ac2-708d8f322e66.png)
**Current behaviour**:
The quest complete marker didn't disappear, even after reload
**Expected behaviour**: 
Should disappear after quest handing.
**Server Revision**:

**Comment by Shanghi** [comment]
So far I haven't been able to reproduce this and don't see anything special about any of his quests that could cause this. Have you deleted the cache before? It's very mysterious!

**Comment by Tereneckla** [comment]
Tried multiple times, cannot reproduce.
