### ISSUE TITLE
Warlock Quest: "Fragments of the Orb of Orahil" not working

### ISSUE THREAD

**Issue by Lukullus** [Atlantiss/NetherwingBugtracker#5370]
[//]: # (Enclose links to things related to the bug using http://wowhead.com or any other TBC database.)
[//]: # (You can use screenshot ingame to visual the issue.)
[//]: # (Write your tickets according to the format:)
[//]: # ([Quest][Azuremyst Isle] Red Snapper - Very Tasty!)
[//]: # ([NPC] Magistrix Erona)
[//]: # ([Spell][Mage] Fireball)
[//]: # ([Npc][Drop] Ghostclaw Lynx)
[//]: # ([Web] Armory doesnt work)
[//]: # (To find server revision type `.server info` command in the game chat.)

**Description**: 
Quest like described here: 
https://vanilla-twinhead.twinstar.cz/?quest=1799
**Current behaviour**:
The Quest is not working.
After accepting the Quest, the Acolytes inside the tower dont react, no question mark shown or something else.
**Expected behaviour**: 
See Quest description
**Server Revision**: 
Netherwing

**Comment by danbopes** [comment]
What was your resolution to this issue @Lukullus ?

**Comment by Lukullus** [comment]
Ignore the task with the acolytes and go on with the quest at Tabetha.
