### ISSUE TITLE
[STAT] Bonus spell damage vs demons

### ISSUE THREAD

**Issue by Nuy** [Atlantiss/NetherwingBugtracker#5373]
[//]: # (Enclose links to things related to the bug using http://wowhead.com or any other TBC database.)
[//]: # (You can use screenshot ingame to visual the issue.)
[//]: # (Write your tickets according to the format:)
[//]: # ([Quest][Azuremyst Isle] Red Snapper - Very Tasty!)
[//]: # ([NPC] Magistrix Erona)
[//]: # ([Spell][Mage] Fireball)
[//]: # ([Npc][Drop] Ghostclaw Lynx)
[//]: # ([Web] Armory doesnt work)
[//]: # (To find server revision type `.server info` command in the game chat.)

**Description**:  This stat doesn't work (doesn't increase BSD vs demon targets).

**Current behaviour**: Does nothing.

**Expected behaviour**: It's supposed to increase BSD vs demon targets. For example [Illidari-Bane Mageblade](http://db.hellfire-tbc.com/?item=30787) doesn't increase BSD vs demons.

**Server Revision**: 2883

**Comment by EnterLarry** [comment]
I tested it on price a few hours ago, and it worked perfectly fine.
Can you post some more info to display what made you come to that conclusion?

**Comment by Nuy** [comment]
I used it vs Ambassador Hellmaw in SL and I was dealing way less damage than with regular weapon.

**Comment by Drsmartinkus** [comment]
Same for me do not work details below
Test Case 1:
buffs: Divine spirit (50 spirit), Stamina
Total spell damage: 669
Mob: WrathWalker 67 lvl
Spell used: Smite
Range dmg (from 5 hits): 1063, 1032, 1043, 1045, 1049
Item used: Runesong Dagger

More or less always above 1k+

Test Case 2
buffs: Divine spirit (50 spirit), Stamina
Total spell damage: 548
Mob: WrathWalker 67 lvl
Spell used: Smite
Range dmg (from 5 hits): 993 ,941, 952, 973, 982
Item: Illidari-Bane Mageblade

More or less always below 1k with range of 900

**Comment by Wolffenstein** [comment]
Fixed in rev 3198.
