### ISSUE TITLE
snake trap 'evade' magma totem damage

### ISSUE THREAD

**Issue by zmthc93** [Atlantiss/NetherwingBugtracker#5374]
[//]: # (Enclose links to things related to the bug using http://wowhead.com or any other TBC database.)
[//]: # (You can use screenshot ingame to visual the issue.)
[//]: # (Write your tickets according to the format:)
[//]: # ([Quest][Azuremyst Isle] Red Snapper - Very Tasty!)
[//]: # ([NPC] Magistrix Erona)
[//]: # ([Spell][Mage] Fireball)
[//]: # ([Npc][Drop] Ghostclaw Lynx)
[//]: # ([Web] Armory doesnt work)
[//]: # (To find server revision type `.server info` command in the game chat.)

**Description**: 
magma totem doesnt kill snakes from snake trap, they 'evade' all dmg
**Current behaviour**:
magma totem doesnt kill snakes from snake trap, they 'evade' all dmg
**Expected behaviour**: 
snakes should not evade totems
**Server Revision**:

**Comment by The14me** [comment]
rev.3478 not an issue anymore.
Can be closed.
