### ISSUE TITLE
[NPC][Drop] Deadwood Headdress Feather

### ISSUE THREAD

**Issue by Fatchanium** [Atlantiss/NetherwingBugtracker#5375]
[//]: # (Enclose links to things related to the bug using http://wowhead.com or any other TBC database.)
[//]: # (You can use screenshot ingame to visual the issue.)
[//]: # (Write your tickets according to the format:)
[//]: # ([Quest][Azuremyst Isle] Red Snapper - Very Tasty!)
[//]: # ([NPC] Magistrix Erona)
[//]: # ([Spell][Mage] Fireball)
[//]: # ([Npc][Drop] Ghostclaw Lynx)
[//]: # ([Web] Armory doesnt work)
[//]: # (To find server revision type `.server info` command in the game chat.)

**Description**: 
Deadwood Headdress Feather https://db.excalibur.ws/?item=21377 are not dropping from certain mobs in Felpaw Village:
Deadwood Den Watcher https://db.excalibur.ws/?npc=7156
Deadwood Avenger https://db.excalibur.ws/?npc=7157
Deadwood Shaman https://db.excalibur.ws/?npc=7158
Chieftain Bloodmaw https://db.excalibur.ws/?npc=9462
**Current behaviour**:
Deadwood Headdress Feather are absent from loot tables.
Some proofs: https://ibb.co/LR233vR https://ibb.co/nfSjKqs
**Expected behaviour**: 
Deadwood Headdress Feather must have 35% chance of dropping from certain mobs in Felpaw Village.
**Server Revision**: 
2883

**Comment by Fatchanium** [comment]
Also - other furbolgs in Deadwood Village have the same problem:
Deadwood Warrior https://db.excalibur.ws/?npc=7153
Deadwood Gardener https://db.excalibur.ws/?npc=7154
Deadwood Pathfinder https://db.excalibur.ws/?npc=7155
Overlord Ror https://db.excalibur.ws/?npc=9464
However their chances of drop feathers are 25%
Proofs: https://ibb.co/pfNQB7b https://ibb.co/BZLxWVz

**Comment by Godmatik** [comment]
Confirmed - quested fully within Felwood and didn't see a single one drop.

**Comment by Tereneckla** [comment]
Tested in rev 3236, they drop
