### ISSUE TITLE
[Item][Priest] Earring of soulful meditation and Bangle of endless blessings, on-use does not stack

### ISSUE THREAD

**Issue by AndrewReynen** [Atlantiss/NetherwingBugtracker#5376]
**Description**: 
Two spirit based on-use trinkets override each other on use when they should stack. 
Trinket 1: Earring of Soulful Meditation
Trinket 2: Bangle of Endless Blessings

**Current behavior**:
Using one trinket removes the effects of the other (used in either order)

**Expected behavior**: 
Trinket +spirit bonuses should stack

**Server revision**:
2887

[Wowhead link with comments on how items should interact](https://www.wowhead.com/item=30665/earring-of-soulful-meditation#comments)
In game screenshot with only one buff active after using both trinkets [![WoWScrnShot_031319_073426](https://user-images.githubusercontent.com/25043909/54276019-932fb680-4562-11e9-896d-a3a0205dfcfa.jpg)]

**Comment by Vfonw** [comment]
This is still not working. The On-Use effects override eachother. 

"[23492](https://www.wowhead.com/user=23492) [on 2007/04/17](https://www.wowhead.com/tbc/item=30665/earring-of-soulful-meditation#comments:id=66795:reply=294249) (Patch 2.0.12)

Confirmed. This got a major buff on the test realms. Cooldown on the buff is 90-120 seconds. It also stacks with the Bangle of Endless Blessings."

**Comment by Godmatik** [comment]
Rev 4015
Still an issue

**Comment by Godmatik** [comment]
Fixed in upcoming spell proc revamp branch
