### ISSUE TITLE
Chests And Lockboxes

### ISSUE THREAD

**Issue by femdead** [Atlantiss/NetherwingBugtracker#5377]
Simply don't exist in outlands - is there a good reason for this?

**Comment by nikolay510** [comment]
I remember elysium devs nerfed pickpocket runs into oblivion and then get caught in gold selling. Deja vu.

https://github.com/Atlantiss/NetherwingBugtracker/issues/5333
https://github.com/Atlantiss/NetherwingBugtracker/issues/3787

Close this.

**Comment by femdead** [comment]
well it's every chest spawn in outlands, not just specific chests in instances

**Comment by Manaci** [comment]
Removed cause too easy to farm
