### ISSUE TITLE
[Fishing] Pure Water pools won't spawn anymore in Nagrand

### ISSUE THREAD

**Issue by x-com1** [Atlantiss/NetherwingBugtracker#5378]
**Description**: 
http://wowwiki.wikia.com/wiki/Pure_Water
Also in changelog posted by Evolve on 2019-03-09:
[2881] Reworked Pure Water pooling.
**Current behaviour**:
No Pure Water pools to be found in Nagrand since the rework on 2019-03-09. I checked all the spots in Nagrand, they all were up and all were either Bluefish or Mudfish. No Pure Water pools anywhere to be found in Nagrand.
**Expected behaviour**: 
There should be 4 or 5 Pure Water pools up in Nagrand, possible Locations:
- Sunspring post (3 pools)
- Rivers below Garadar (5 pools)
- Lake above Garadar (4 pools)
- Elemental Plateau (4 pools)

All pools were up when I checked them today, but none were Pure Water pools. Primal Water Prices are already rising in the auction house.
**Server Revision**: 
[2887]

**Comment by Evolvee** [comment]
the pools and pure waters are sharing the same spawns now, meaning if you fish out the fish schools, theres a chance for pure water to spawn

if noone fishes anything and just waits for pure water to spawn, it will never spawn

**Comment by x-com1** [comment]
Thanks for the info Evolvee. Could it be, that you also increased the pool respawn time? It used to be 5 minutes, but I believe it's anyhwhere between 10 and 15 minutes now.

In a first test I fished 8 pools empty and 1 of them respawned as Pure Water. Will do more testing later, but it seems it's not really worth the effort now. Could be problematic in peak hours too, when more people are fishing. You'd be better off to just kill water elementals, than hope for lucky Pure Water spawns.

**Comment by Evolvee** [comment]
yes i increased it as well

**Comment by Evolvee** [comment]
i will slightly increase the chance of pure water being spawned instead

**Comment by qmsq04** [comment]
Well 4 of the pools above Garadar are unfishable for small characters, since they are misspositioned far away from the shore. They need to be moved, because as a gnome you can't fish these locations

**Comment by Evolvee** [comment]
rev 2911
