### ISSUE TITLE
[Talent][Mage] Wand Specialization

### ISSUE THREAD

**Issue by Infailing** [Atlantiss/NetherwingBugtracker#5379]
[//]: # (Enclose links to things related to the bug using http://wowhead.com or any other TBC database.)
[//]: # (You can use screenshot ingame to visual the issue.)
[//]: # (Write your tickets according to the format:)
[//]: # ([Quest][Azuremyst Isle] Red Snapper - Very Tasty!)
[//]: # ([NPC] Magistrix Erona)
[//]: # ([Spell][Mage] Fireball)
[//]: # ([Npc][Drop] Ghostclaw Lynx)
[//]: # ([Web] Armory doesnt work)
[//]: # (To find server revision type `.server info` command in the game chat.)

**Description**: 
Increases the damage using wands by 25%.

**Current behaviour**: 
It does increase the damage you do with wands, but it also increases the damage from every spell by 25%.

**Expected behaviour**: 
This talent should increase only the amount of damage you do using your equipped wand.

**Comment by Wolffenstein** [comment]
Fixed in rev 2888.
