### ISSUE TITLE
[Item] Dark Iron Pulverizer procrate too low

### ISSUE THREAD

**Issue by nikolay510** [Atlantiss/NetherwingBugtracker#5380]
[//]: # (Enclose links to things related to the bug using http://wowhead.com or any other TBC database.)
[//]: # (You can use screenshot ingame to visual the issue.)
[//]: # (Write your tickets according to the format:)
[//]: # ([Quest][Azuremyst Isle] Red Snapper - Very Tasty!)
[//]: # ([NPC] Magistrix Erona)
[//]: # ([Spell][Mage] Fireball)
[//]: # ([Npc][Drop] Ghostclaw Lynx)
[//]: # ([Web] Armory doesnt work)
[//]: # (To find server revision type `.server info` command in the game chat.)
**Description**: 
Dark Iron Pulverizer got a chance to stun a target for 8 sec.
**Current behaviour**:
https://my.mixtape.moe/vumvpm.webm
Proc rate is abysmal. I killed mobs in Blasted Lands for like 10mins and it didnt even proc once, then I decided to make a 10min video to test. It procced only once on tiger, 4:30 timestamp, the name of the debuff is "Stunning Blow" (can be seen in combat log). 
**Expected behaviour**: 
According to https://classic.wowhead.com/item=11608/dark-iron-pulverizer#comments procrate should be 0.18 PPM, or 5 minutes per proc. Considering the fact that instant attacks affect PPM, it should proc around once every 3 minutes or so. Also according to https://xpoff.com/threads/weapon-proc-rates.60492/ (unknown source) proc should be 1PPM.
**Server Revision**: 
2883 (https://imgur.com/a/DdLH1bE)

**Comment by Jseay1313** [comment]
I had this thing on retail for the luls, everyone wants to test an 8 second stun right, proc rate was abyssmal, much less than 1 ppm. Wowhead comments confirm that its terrible as well.

**Comment by KevinTyrrell** [comment]
I can attest to what @Jseay1313 is saying. The proc rate back in vanilla would be like once per ten minutes of pure grinding. If it procced  all the time it would be incredibly overpowered.
