### ISSUE TITLE
[Spell][Item] Robe of the elder scribes and Spellstrike-set can't proc at the same time.

### ISSUE THREAD

**Issue by Cptnlobbe** [Atlantiss/NetherwingBugtracker#5381]
**Description**: 
During the time one of the items proc is active, the other one cannot activate. I dunno if this is actually correct behaviour, but I've seen its been a problem on other bugtrackers but where the buff got overwritten instead.

**Current behaviour**:
If robe proc, spellstrike cannot proc during this time and viceversa. They share the same internal cooldown.
**Expected behaviour**: 
Both should be able to be active at the same time.
**Server Revision**: 
2883

**Comment by devo6969** [comment]
Can confirm, I could never get them to proc together on the PTR.

https://www.wowhead.com/item=28602/robe-of-the-elder-scribes#comments
it is truly an amazing chest. looks good too unlike some others. spellstrike + this + trinket is a brutal combo. however chances are they wont proc at the same time but when they do it is a nice bonus

**Comment by Godmatik** [comment]
Fixed in upcoming spell proc branch update
