### ISSUE TITLE
Deadly throw sometimes doesn't slow.

### ISSUE THREAD

**Issue by maxfactor1** [Atlantiss/NetherwingBugtracker#5382]
Not sure if it's because of a "full absorb" or what. But in arena the slowing portion of my deadly throw wasn't applied and VERY LIKELY cost us a game.

https://i.imgur.com/2GMNNx8.png

Relevant screenshot with swearing. Sorry about the swearing. The 15 point loss is still fresh on my mind.

**Comment by Wolffenstein** [comment]
Could it be because of Improved Blink talent?

**Comment by yutsuku** [comment]
> 
> 
> Could it be because of Improved Blink talent?

Its not class specific, got issued with it too.

[pretty combat log picture with a warrior as example](http://u.cubeupload.com/moh/20190723004829.png)
