### ISSUE TITLE
Issue with seal of wisdom after judging.

### ISSUE THREAD

**Issue by shanold** [Atlantiss/NetherwingBugtracker#5383]
[//]: # (Enclose links to things related to the bug using http://wowhead.com or any other TBC database.)
[//]: # (You can use screenshot ingame to visual the issue.)
[//]: # (Write your tickets according to the format:)
[//]: # ([Quest][Azuremyst Isle] Red Snapper - Very Tasty!)
[//]: # ([NPC] Magistrix Erona)
[//]: # ([Spell][Mage] Fireball)
[//]: # ([Npc][Drop] Ghostclaw Lynx)
[//]: # ([Web] Armory doesnt work)
[//]: # (To find server revision type `.server info` command in the game chat.)

**Description**: 
Seal of wisdom's judgement effect isn't working
**Current behaviour**:
after judging seal of wisdom you don't regenerate mana on Hit.
**Expected behaviour**: 
after judging seal of wisdom you should recover some mana on hit
**Server Revision**: 
2883

**Comment by Tenoutoften** [comment]
This is regarding lower ranks of judge of wisdom right, you didn't use rank 4?

**Comment by Wolffenstein** [comment]
All ranks work fine for me.

**Comment by shanold** [comment]
It's rank 1 I'm leveling so that's my Max rank currently

**Comment by shanold** [comment]
Combat log is now showing something but its not popping up on floating combat text like the seal does and like judgement of light does

**Comment by Tereneckla** [comment]
All ranks work.
