### ISSUE TITLE
[Quest][Blackrock Depths] Recently added "The Challenge" for the tier 0.5 quest isn't working

### ISSUE THREAD

**Issue by Ousak1** [Atlantiss/NetherwingBugtracker#5384]
**Description:**
Recently added final quest for the Tier 0.5 isn't working as described:

Quest : https://www.wowhead.com/quest=9015/the-challenge#comments

**Current behaviour:**
For the quest you are supposed to use a Banner in the center of the **Ring of the Law** in **Blackrock Depths** when you are being judged, however no matter when you use the banner, the additional encounter required for the quest never spawns. 

**Expected behaviour:**
If you use the banner the first time **High Justice Grimstone** spawns, the first encounter will be the **Theldren group** encounter, instead of the dungeon normal encounter, if you use it on the second time that  **High Justice Grimstone** appears (after the first normal encounter), you will fight **Theldren group** after the second normal encounter (as a third encounter). After you kill the **Theldren group**, a chest will spawn in the center called **Arena Spoils** which will contain a blue item (Theldren's body has the quest item) as per reference:

Arena Spoil: https://www.wowhead.com/object=181074/arena-spoils#contains

**Server Revision:**
2888

**Comment by gvozdeni** [comment]
I'm also stuck on this quest, encountering the same thing as OP.

**Comment by Ousak1** [comment]
Any progress on this front? me and other ppl wants to test the tier 0.5 on outland raids, we would appreciate to be able to finish the quest.

**Comment by Evolvee** [comment]
no progress

**Comment by Evolvee** [comment]
I need to rewrite the entire BRD arena event because this quest interferes with it and I am unable to just edit it since its written in old shitty cpp.

**Comment by gvozdeni** [comment]
Is it possible to just finish the quest for us or something.. It's really annoying since it's basically limiting our playstyles.

**Comment by gvozdeni** [comment]
We spent a lot of time and gold on this quest, just to find out it's not working. That gear should be obtainable as soon as you can pick up the quest from the giver, but now it seems like we'll have to wait for a while.. Just trying to prove you that quite a few people care about this and really want it fixed as soon as possible, sorry if i sounded rude in any way, cheers.

**Comment by Evolvee** [comment]
i may just temporarily hackfix it before the whole arena is rewritten yea

**Comment by Ousak1** [comment]
Update: 23/03 went to BRD, quest still not working, just a heads up to the people waiting.

**Comment by Evolvee** [comment]
it will be in changelog if it gets fixed

**Comment by Cutiepand** [comment]
Good luck on thesis friend :)

**Comment by Evolvee** [comment]
rev 2913
