### ISSUE TITLE
[Spell][Talent][Shaman] Healing Focus not working as intended

### ISSUE THREAD

**Issue by Jalapan** [Atlantiss/NetherwingBugtracker#5386]
[//]: # (Enclose links to things related to the bug using http://wowhead.com or any other TBC database.)
[//]: # (You can use screenshot ingame to visual the issue.)
[//]: # (Write your tickets according to the format:)
[//]: # ([Quest][Azuremyst Isle] Red Snapper - Very Tasty!)
[//]: # ([NPC] Magistrix Erona)
[//]: # ([Spell][Mage] Fireball)
[//]: # ([Npc][Drop] Ghostclaw Lynx)
[//]: # ([Web] Armory doesnt work)
[//]: # (To find server revision type `.server info` command in the game chat.)

**Description**: 
Healing focus is not working as intended, it has some very strange behaviour that we saw yesterday on Curator.

**Current behaviour**:
The 70% to avoid castback is not working as intdended, it very rarely removes the pushback.
Even with Paladin concentration aura 140% chance not to get pushback, you are still getting pushbacked as a shaman.
Perhaps take a look how the behaviour is coded
**Expected behaviour**: 
The pushback should not exist, and you should only get pushedback on casting 30% of all spells.
**Server Revision**:

**Comment by Tereneckla** [comment]
Can not reproduce, manage to achieve 100% pushback avoidance as shaman with earthshield or concentration aura.
