### ISSUE TITLE
Ice Blocking a Fear effect will cause your character to permanently retain whatever movement speed it had while Feared

### ISSUE THREAD

**Issue by somnu** [Atlantiss/NetherwingBugtracker#5387]
**Description**: 
Ice Blocking a Fear effect will cause your character to permanently retain whatever movement speed it had while feared. For example: If you are mounted then feared and you ice block it, you will continue running at 160%(normal mount speed) while being unmounted. The same seems to happen with slows. Your character will continue being slowed while no longer having a slow debuff on.

This might work with other "fear" type effects like death coil and possibly blind(?). I couldn't test those out. Also might work for other immunes like divine shield.

**Current behaviour**:

**Expected behaviour**: 

After Ice Block, all movement imparing effects should go away from the character.

**Server Revision**: 
2883

**Comment by Wolffenstein** [comment]
It will be fixed next update.
