### ISSUE TITLE
[Fishing] Nagrand should have 30 pools and EP should have only Pure Water pools

### ISSUE THREAD

**Issue by x-com1** [Atlantiss/NetherwingBugtracker#5388]
[//]: # (Enclose links to things related to the bug using http://wowhead.com or any other TBC database.)
[//]: # (You can use screenshot ingame to visual the issue.)
[//]: # (Write your tickets according to the format:)
[//]: # ([Quest][Azuremyst Isle] Red Snapper - Very Tasty!)
[//]: # ([NPC] Magistrix Erona)
[//]: # ([Spell][Mage] Fireball)
[//]: # ([Npc][Drop] Ghostclaw Lynx)
[//]: # ([Web] Armory doesnt work)
[//]: # (To find server revision type `.server info` command in the game chat.)

**Description**: 
http://old.elsanglinreborn.com/fishing_pure_water.html
**Current behaviour**:
There are currently only 16 pools available in Nagrand:
- Sunspring post (3 pools)
- Rivers below Garadar (5 pools)
- Lake above Garadar (4 pools)
- Elemental Plateau (4 pools)

Also Elemental Plateau contains pools of Mudfish and Bluefin, but it should only have 6 pools of Pure Water.
**Expected behaviour**: 
There should be around 30 pools available in Nagrand (incl. Elemental Plateau). See chapter Nagrand Ground Level in the link above:

> There are about 30 possible pool spawning locations in total. Normally once one pool has been fished, another will appear elsewhere in the set. In practice, it isn't possible for one person to fish more than about 20 pools per hour, so unless the area is being heavily fished, you should always be able to find fresh pools.

Also under chapter Elemental Plateau it says:

> The area contains a completely separate set of six pool spawning locations which only contain Pure Water

**Server Revision**: 
[2888]

**Comment by Azalen** [comment]
#4724

**Comment by Evolvee** [comment]
rev 2891
