### ISSUE TITLE
[Quest][Orgrimmar]An Earnest Proposition

### ISSUE THREAD

**Issue by gvozdeni** [Atlantiss/NetherwingBugtracker#5389]
[//]: # (Enclose links to things related to the bug using http://wowhead.com or any other TBC database.)
[//]: # (You can use screenshot ingame to visual the issue.)
[//]: # (Write your tickets according to the format:)
[//]: # ([Quest][Azuremyst Isle] Red Snapper - Very Tasty!)
[//]: # ([NPC] Magistrix Erona)
[//]: # ([Spell][Mage] Fireball)
[//]: # ([Npc][Drop] Ghostclaw Lynx)
[//]: # ([Web] Armory doesnt work)
[//]: # (To find server revision type `.server info` command in the game chat.)

**Description**: 
First quest of the chain for t0.5 given by Mokvar, doesn't seem to be ingame. (Not rogue specific, it's not there for all classes.)

Quest: https://www.wowhead.com/quest=8917/an-earnest-proposition

**Current behaviour**: 
By speaking to Mokvar for the first time he offers you the quest: https://www.wowhead.com/quest=8923/a-supernatural-device instead of the one I linked earlier, which means t0.5 bracers are currently not obtainable.

**Expected behaviour**: 
The first time you talk to Mokvar he should offer you the quest called "An Earnest Proposition" instead of offering you "A Supernatural Device" which should come right after you finish "An Earnest Proposition".

**Server Revision**: 
2888

**Comment by Ousak1** [comment]
I have the same Issue as OP.

**Comment by Evolvee** [comment]
rev 2891
