### ISSUE TITLE
[NPC] [Gruul's Lair] Gruul Hurtful strike

### ISSUE THREAD

**Issue by quapuzi** [Atlantiss/NetherwingBugtracker#5390]
**Description**: Gruuls Hurtful strike is hitting the wrong target, if a ranged is above the Maintank or the second highest Threat target in melee range.

**Current behaviour**: Gruuls Hurtful strike is hitting the third highest instead of the second highest Threat target, if the second highest target is not in melee range. Ie. Maintank is highest on Threat, Hunter is second and Offtank is the third, the Offtank wont get the hit. Instead the 3rd highest in melee range will take the hurtful strike.

**Expected behaviour**: He should always hit the second highest in melee range, not matter if a ranged is above him.

**Server Revision**: 2888

**Comment by sifiuocz** [comment]
Did your off tank have aggro of the boss at any given time during the fight?
