### ISSUE TITLE
Gusting Vortex in Tanaris don't spawn

### ISSUE THREAD

**Issue by Blakangel72** [Atlantiss/NetherwingBugtracker#5391]
[NPC] Gusting Vortex (https://vanilla-twinhead.twinstar.cz/?npc=8667)

Mob is no longer spawning, Land Rager (https://vanilla-twinhead.twinstar.cz/?npc=5465) is instead spawning in its place, as well as it's own spawnpoints. Tried killing Land Ragers, and they always respawned as Land Rager. This makes Breath of Wind (https://tbc-twinhead.twinstar.cz/?item=7081) very difficult to get, and impossible to find on the AH.

**Comment by Evolvee** [comment]
i dont see any problem server-side, u were probably just unlucky
