### ISSUE TITLE
[Raid][Netherspite][Spell] Nether Portal - Dominance / Netherspite not increasing damage

### ISSUE THREAD

**Issue by towneh** [Atlantiss/NetherwingBugtracker#5392]
**Description**: 
Nether Beam Dominance (spell id 30423) is not increasing spell damage.

**Current behaviour**:
![image](https://user-images.githubusercontent.com/25694892/54396880-6daec400-46ac-11e9-8004-e47e93ecd445.png)
Shadow Priest, Elemental Shaman, Fire Mage, Rogue were rotating on the blue beam.
As a shadow priest I had up to 32 stacks (160%) of Dominance and was not observing any increased damage.
The image above is from the kill with all the DPS shown.

![image](https://user-images.githubusercontent.com/25694892/54396957-afd80580-46ac-11e9-9061-e0ee2684d04d.png)

**Expected behaviour**: 
Each stack of Dominance should modify attributes as shown in http://db.hellfire-tbc.com/?spell=30423

**Server Revision**: 
2888

**Comment by towneh** [comment]
Wont have a chance to test this on PTR yet until Saturday.

**Comment by towneh** [comment]
Verified on PTR by another tester. Frostbolt damage did not increase the entire time the person was taking Dominance stacks.

**Comment by Wolffenstein** [comment]
Fixed in rev 2890.
