### ISSUE TITLE
[Raid][Tempest Keep] Al'ar Flame Quill ability

### ISSUE THREAD

**Issue by Dollywog** [Atlantiss/NetherwingBugtracker#5393]
**Description**:  Al'ar's Flame Quill ability has a larger than normal radius and hits significant areas on the lower level outside of the expected range.

**Current behaviour**:  If you jump down from the central north platforms, the Flame Quills will continue to hit you on the ground for about 20 yards distance from the platforms until you reach the central lower level.  The Flame Quill works correctly hitting the upper parts of the ramps only and you can wait halfway up the ramps for it elsewhere, it is just the north section of the lower level which is incorrectly affected.
_**Will upload VOD soon if evidence needed**_

**Expected behaviour**:  _"Al'ar will fly to the center of the room instead of switching platforms. Al'ar then launches quills that hit anyone on the platforms or the outer part of the ramps_"

**Server Revision**: Reduce north-side radius of Flame quill ability.  I think this is a problem with their being a blanket radius of the ability to accommodate for the fact that the upper north platforms "stick out" from the rest of the upper level.  This means if you jump down from anywhere but the edge of a platform you are likely to take ticks of the Quills.

**Comment by Dollywog** [comment]
https://clips.twitch.tv/TiredArbitraryAntOneHand

If you pause on the 11 second frame you can see my corpse in the Northeast corner of the room (NOTE: Not the other player on the West side dead) .  This gives you an idea of how far the distance of Flame Quill still effects even after jumping down .  (Sorry no other VOD available)

**Comment by rychersky** [comment]
There seems to be a delay on the detection of the Y-axis. I frequently will jump down, be running on the ground, and die to flame quills on the bottom floor. As it stands currently, tanks need to jump within a second of seeing Al'ar going up to spin.

**Comment by icywire** [comment]
1. I can confirm the issue of inflicting dmg when player is already on the floor on the north part.
Quote from https://wowwiki.fandom.com/wiki/Al%27ar - "... Every person in the raid needs to be aware and fall down from the upper platform, especially the tanks, since anyone left there will take 6-8k fire damage per second. People standing on the outside of the room on the floor (south near the entry door) are also susceptible...."

So, in conjunction with what Dollywog already wrote - Flame Quill should hit at 3 places:
- platforms
- outer part of ramps
- near to entrance

2. Flame Quill ticks happens twice in the same milisecond after ever second.

**Comment by Easyfraggy** [comment]
Standing near the walls and on a large part of the ramp on retail would get you killed also. Pretty sure all this is blizzlike and would need some real retail proof not some circumstantial comment that simply does not talk about the north. 

The videoclip from Netherwing also does not show the person in question dying at all merely his corpse which is from what I can tell so close to the wall that if you were continuously moving and jumping off the platform you SHOULD have died as your corpse keeps moving after you die.

![image](https://user-images.githubusercontent.com/36134067/66180607-f3588800-e66d-11e9-940e-869bc9e5a1cd.png)

**Comment by icywire** [comment]
Here is proof that Flame Quill has doubled-ticks.
![WoWScrnShot_100919_224327](https://user-images.githubusercontent.com/830641/66520296-2fb23b00-eae9-11e9-9511-0d2a4a715d71.jpg)
![WoWScrnShot_100919_224340](https://user-images.githubusercontent.com/830641/66520298-2fb23b00-eae9-11e9-8cdd-cad71f8d9f2c.jpg)
