### ISSUE TITLE
Pendant of Triumph and Dominance cost too much Honor 

### ISSUE THREAD

**Issue by Manaci** [Atlantiss/NetherwingBugtracker#5394]
**Description**: 
Currently the [Pendant of Triumph](https://db.excalibur.ws/?item=28244) and [Dominance](https://db.excalibur.ws/?item=28245) cost too much honor.

**Current behaviour**:
Currently both of these PvP Necklaces cost a whole 22500 Honor and 10 Eye of the Storm Mark of Honor each.

**Expected behaviour**: 
They should only cost 15300 Honor and 10 Eye of the Storm Mark of Honor each.

**Proof**:
[Pendant of Triumph](https://db.excalibur.ws/?item=28244) is the real cost, seen as on the db the [Sergeant's heavy Cloak](https://db.excalibur.ws/?item=28377) costs only 9435 Honor and 20 Arathi Basin Mark of Honor and it does so as well in-game. 

**Server Revision**: 
2888

**Comment by Tenoutoften** [comment]
Working as intended
![](https://i.gyazo.com/3dff14f3656966739572e91f0aaad5eb.png)
http://web.archive.org/web/20070408165628/http://www.thottbot.com:80/i28244

**Comment by Manaci** [comment]
Well then everything else is too cheap?
