### ISSUE TITLE
[Spell][Warrior]Spellreflecting spells dosent return damage to the caster

### ISSUE THREAD

**Issue by Jalapan** [Atlantiss/NetherwingBugtracker#5395]
[//]: # (Enclose links to things related to the bug using http://wowhead.com or any other TBC database.)
[//]: # (You can use screenshot ingame to visual the issue.)
[//]: # (Write your tickets according to the format:)
[//]: # ([Quest][Azuremyst Isle] Red Snapper - Very Tasty!)
[//]: # ([NPC] Magistrix Erona)
[//]: # ([Spell][Mage] Fireball)
[//]: # ([Npc][Drop] Ghostclaw Lynx)
[//]: # ([Web] Armory doesnt work)
[//]: # (To find server revision type `.server info` command in the game chat.)

**Description**: 
When a warrior use spellreflect the returned spell deals no damage
**Current behaviour**:

**Expected behaviour**: 
The reflected spell should return the casters damage
**Server Revision**: 
2891

**Comment by numiee** [comment]
can confirm it doesnt reflect any damage in PvE, however it seems to give the threat.

**Comment by Wolffenstein** [comment]
fixed

**Comment by Azalen** [comment]
I do not think this is or ever was fixed. It is majorly broken in PvP.
