### ISSUE TITLE
[NPC] Exarch Maladaar's [Spell] Summon Dark Side summons level 70 mobs in normal mode

### ISSUE THREAD

**Issue by Albarok** [Atlantiss/NetherwingBugtracker#5397]
**Description**: 
Exarch Maladaar at the Auchenai Crypts summon high level enemies at normal mode.

**Current behaviour**:
Exarch Maladaar's spell "Summon Dark Side" summons level 70-71 Stolen Soul mobs in normal mode.

**Expected behaviour**: 
In normal mode, these summoned mobs should be around level 67.

https://wowwiki.fandom.com/wiki/Stolen_Soul

https://www.wowhead.com/npc=18441/stolen-soul#abilities

**Server Revision**:

**Comment by Evolvee** [comment]
rev 2983
