### ISSUE TITLE
([Quest][Ammen Vale] Inoculation)

### ISSUE THREAD

**Issue by Kantrul** [Atlantiss/NetherwingBugtracker#540]
[//]: # (Enclose links to things related to the bug using http://wowhead.com or any other TBC database.)
[//]: # (You can use screenshot ingame to visual the issue.)
[//]: # (Write your tickets according to the format:)
[//]: # ([Quest][Azuremyst Isle] Red Snapper - Very Tasty!)
[//]: # ([NPC] Magistrix Erona)
[//]: # ([Spell][Mage] Fireball)
[//]: # ([Npc][Drop] Ghostclaw Lynx)
[//]: # ([Web] Armory doesnt work)

**Description**: 
owlkins get the inoculation even when the channel cast gets interrupted
**Current behaviour**:
When you use the item Inoculating Crystal on Nestlewood Owlkins and get interrupted by a Mutated Owlkin the inoculation process still completes.
**Expected behaviour**: 
If your channel gets interrupted by another mob your inoculation process should not complete and therefore you are forced to get out of combat and try again.
**Server Revision**: 
2050

**Comment by xmesaj2** [comment]
fix in rev 2054
