### ISSUE TITLE
Holy Nova causing threat

### ISSUE THREAD

**Issue by wshamp** [Atlantiss/NetherwingBugtracker#5400]
[//]: # (Enclose links to things related to the bug using http://wowhead.com or any other TBC database.)
[//]: # (You can use screenshot ingame to visual the issue.)
[//]: # (Write your tickets according to the format:)
[//]: # ([Quest][Azuremyst Isle] Red Snapper - Very Tasty!)
[//]: # ([NPC] Magistrix Erona)
[//]: # ([Spell][Mage] Fireball)
[//]: # ([Npc][Drop] Ghostclaw Lynx)
[//]: # ([Web] Armory doesnt work)
[//]: # (To find server revision type `.server info` command in the game chat.)

Priest Holy Nova is causing threat when it clearly states it should not

One character gathers several mobs without tagging them i.e. just run through them
Priest get close and casts Holy Nova
Mobs will start attacking priest

Mobs should not attack priest as no threat should be generated with Holy Nova

Server revision 2891

**Comment by Easyfraggy** [comment]
Are you sure you aren't using some mana gain of some sort? That causes threat. I have done aoe with priest many times he never got agro.

**Comment by Wolffenstein** [comment]
Fixed in rev 2920.

**Comment by SlizeTBC** [comment]
I just tried to Heal someone with Holy Nova today, while he was pulling a bunch of Mobs. Like after the first Holy Nova the Mobs went straight after me. Shouldnt it be causing no threat at all?

https://www.youtube.com/watch?v=GZln40wkhDI
