### ISSUE TITLE
[QUEST] Luck Be With You

### ISSUE THREAD

**Issue by Godmatik** [Atlantiss/NetherwingBugtracker#5401]
**Description**: 
The quest has you gather 4 Frostmaul Shards, but it should be 10. It wasn't changed over to 4 until Patch 2.3
https://wowwiki.fandom.com/wiki/Quest%3ALuck_Be_With_You

**Current behaviour**:
You only need to gather 4 Frostmaul shards

**Expected behaviour**: 
It should be 10, until patch 2.3 hits

**Server Revision**: 
2891

**Comment by Manaci** [comment]
Irrelevant now

**Comment by Manaci** [comment]
Saved for the future

**Comment by Evolvee** [comment]
fixed in next rev
