### ISSUE TITLE
Cannot drag pet spells from spellbook to pet bar

### ISSUE THREAD

**Issue by toporc26** [Atlantiss/NetherwingBugtracker#5402]
[//]: # (Enclose links to things related to the bug using http://wowhead.com or any other TBC database.)
[//]: # (You can use screenshot ingame to visual the issue.)
[//]: # (Write your tickets according to the format:)
[//]: # ([Quest][Azuremyst Isle] Red Snapper - Very Tasty!)
[//]: # ([NPC] Magistrix Erona)
[//]: # ([Spell][Mage] Fireball)
[//]: # ([Npc][Drop] Ghostclaw Lynx)
[//]: # ([Web] Armory doesnt work)
[//]: # (To find server revision type `.server info` command in the game chat.)

**Description**: 
Cannot drag pet spells such as Gore, Claw, Bite, Torment, Consume Shadows, etc onto pet bar.
If you drag a spell off of the pet bar, your only option is to click it via your spellbook, or make a keybind and macro for the pet spell you wish to use.
**Current behaviour**:
Pet spells are unable to be dragged onto the pet bar.
**Expected behaviour**: 
Pet spells should be "unlocked" and able to be dragged onto pet bar.
**Server Revision**: 
2891

**Comment by ThousandNoodles** [comment]
I got the same issue on my Warlock and really hope to be fixed. This is obviously an old known bug (never fixed by Blizzard himself until 2017) and it also affects Hunters pets.

**Comment by toporc26** [comment]
issue was fixed in a recent rev
