### ISSUE TITLE
Khorium power core

### ISSUE THREAD

**Issue by Dimbleglim** [Atlantiss/NetherwingBugtracker#5403]
As of yet (rev 2891) the khorium power core (added 2.0.1) is not in the game but engineering schematics that require it are. The khorium power core should be trainable by several engineering trainers (Xyrol, Zebig, Mack Diver, Lebowski, K. Lee Smallfry) at skill 340 but non of them do.

**Comment by gunzbngbng** [comment]
Khorium Power Core is a 350 skill along with Felsteel Stabilizer and Hardened Adamantine Tube.

They are absolutely in the game.  Pump out a few more flares.

**Comment by Dimbleglim** [comment]
Then the skill requirement is set wrong as it should be 340. Furthermore trainers are supposed to let you see the things you can't train just yet. Currently the engineering trainers in outland don't seem to do that.
Except for the dimensional ripper trainer who will gladly teach you the super secret technology behind goblin dimensional rippers if you are a gnome engineer (were is not for the soulbound bomb needed you can even make it but not use it). Instead these trainers should just tell you they are looking for a skilled goblin engineer.

**Comment by gunzbngbng** [comment]
Every server I've been on has been 350 for those schematics.  Pretty sure you train them at yellow.

**Comment by SwiftieTBC** [comment]
This was changed in 2.1 to 340 down from 350(or 345 2 sources say different things)
I guess this is up to which version they want to keep/run with
