### ISSUE TITLE
Fel Domination not resetting Warlock Spell Lock

### ISSUE THREAD

**Issue by tehelelol** [Atlantiss/NetherwingBugtracker#5404]
[//]: # (Enclose links to things related to the bug using http://wowhead.com or any other TBC database.)
[//]: # (You can use screenshot ingame to visual the issue.)
[//]: # (Write your tickets according to the format:)
[//]: # ([Quest][Azuremyst Isle] Red Snapper - Very Tasty!)
[//]: # ([NPC] Magistrix Erona)
[//]: # ([Spell][Mage] Fireball)
[//]: # ([Npc][Drop] Ghostclaw Lynx)
[//]: # ([Web] Armory doesnt work)
[//]: # (To find server revision type `.server info` command in the game chat.)

**Description**: 
Fel Domination not resetting Warlock Spell Lock
**Current behaviour**:
Fel Domination not resetting Warlock Spell Lock
It worked 1-2 weeks ago but apperently you broke it now.
**Expected behaviour**: 
If you Fel Domination a new Pet it should reset it's special ability. (i.e. Spell Lock, Intercept..)
http://www.arenajunkies.com/topic/2549-warlock-trick/
**Server Revision**:

**Comment by gabbat** [comment]
same for mage water elemental and coldsnap

**Comment by Wolffenstein** [comment]
Fixed in rev 2907.
