### ISSUE TITLE
[Quest] Winds in the Desert

### ISSUE THREAD

**Issue by Polybolos** [Atlantiss/NetherwingBugtracker#5405]
[//]: # (Enclose links to things related to the bug using http://wowhead.com or any other TBC database.)
[//]: # (You can use screenshot ingame to visual the issue.)
[//]: # (Write your tickets according to the format:)
[//]: # ([Quest][Azuremyst Isle] Red Snapper - Very Tasty!)
[//]: # ([NPC] Magistrix Erona)
[//]: # ([Spell][Mage] Fireball)
[//]: # ([Npc][Drop] Ghostclaw Lynx)
[//]: # ([Web] Armory doesnt work)
[//]: # (To find server revision type `.server info` command in the game chat.)

**Description**: 
Quest Winds in the Desert cannot be taken by alliance characters
**Current behaviour**:
Quest Winds in the Desert cannot be taken by alliance characters
**Expected behaviour**: 
Should be possible to take and complete this quest and its follow-up "Securing the Lines" as Alliance character. Upon turning in, both quests should give only Ratchet reputation. 
Source: https://www.wowhead.com/quest=834/winds-in-the-desert#comments:id=52704
**Server Revision**: 
2891

**Comment by The14me** [comment]
Rev.3483 still an issue.

**Comment by EtheriousNW** [comment]
Fixed
