### ISSUE TITLE
Mark of Solarian

### ISSUE THREAD

**Issue by Frankenberryberry** [Atlantiss/NetherwingBugtracker#5408]
**Description**: 
The debuff at High Astromancer Solarian that lowers the arcane resistance of the raid currently lowers it by too much.

**Current behaviour**:
Currently each stack lowers the arcane resistance of the raid by 35 arcane resistance per stack (if I remember the correct values). The debuff slot says 35 arcane resistance. However if you check your character sheet it will lower your arcane resistance by double the amount shown in the debuff. So 70 at first stack. 140 at second. 210 at third and so on.

**Expected behaviour**: 
The debuff should lower the resistance by the amount shown in the debuff.

**Server Revision**: 
2891

**Comment by Wolffenstein** [comment]
It's -30 per stack in 2.0.3 and -15 per stack in 2.4.3. The tooltips are stored clientside, that's why they're inaccurate, but the reduction is working correctly according to 2.0.3 data.
