### ISSUE TITLE
[dungeon] UBRS absolutely overtuned

### ISSUE THREAD

**Issue by gabbat** [Atlantiss/NetherwingBugtracker#5409]
[//]: # (Enclose links to things related to the bug using http://wowhead.com or any other TBC database.)
[//]: # (You can use screenshot ingame to visual the issue.)
[//]: # (Write your tickets according to the format:)
[//]: # ([Quest][Azuremyst Isle] Red Snapper - Very Tasty!)
[//]: # ([NPC] Magistrix Erona)
[//]: # ([Spell][Mage] Fireball)
[//]: # ([Npc][Drop] Ghostclaw Lynx)
[//]: # ([Web] Armory doesnt work)
[//]: # (To find server revision type `.server info` command in the game chat.)

**Description**: I did not take screenshots, but draki flamestrike hitting for 2.5k (oneshotting entire groups/raids at 60), autohitting for 5k on 4k armor (1-2shotting tanks), beast fireball dot for 800initial and 400 dmg over time, trash hitting insanely hard on everything, etc etc etc

**Current behaviour**: see above

**Expected behaviour**: should be tuned for lvl60 not lvl70

**Server Revision**:

**Comment by Evolvee** [comment]
it was a 10man dungeon, should be considerably harder than the classic 5 man ones

i would need specific examples of overtuned damage, drakisath got nerfed few revs ago

spell damage is correct
