### ISSUE TITLE
Etched Phial

### ISSUE THREAD

**Issue by Trix115** [Atlantiss/NetherwingBugtracker#541]
The Laughing Sisters in Ashenvail are supposed to drop a quest item called "Etched Phial", but we've cleared them all twice over now and it still hasn't dropped. Checked and apparently it should be 100% drop on it so i don't think it's dropping at all.

https://tbc-twinhead.twinstar.cz/?item=5867 item in question
https://tbc-twinhead.twinstar.cz/?quest=1195 requirement for this quest

**Comment by Jezofine** [comment]
We killed them in party and without party, no drops in both cases.

**Comment by aresbrutus** [comment]
They are supposed to be low but there was an issue that will be corrected in one of the next updates.
