### ISSUE TITLE
Relearned Blacksmith, Weaponsmith Quest unavailable

### ISSUE THREAD

**Issue by Fexxd** [Atlantiss/NetherwingBugtracker#5410]
**Description**: 
Greetings, I relearned Blacksmith and wanted to became a weaponsmith. Now I can't accept the Quest "The Way of the Weaponsmith". https://www.wowhead.com/quest=5302/the-way-of-the-weaponsmith

More infos: I completed this Quest and unlearned the profession 1 month ago.
**Current behaviour**:
see above

**Expected behaviour**: 
Just to accept the Quest again. 
**Server Revision**: 
-
![hellpp](https://user-images.githubusercontent.com/48689033/54546297-aa780500-49a3-11e9-8e55-f28e7820aaf1.PNG)

**Comment by brobrobro187** [comment]
Having the same issue. lvl'd engineering to 370 as gnomeish realized its trash so i TRIED swapping to Goblin... and buggd out... so i went for blacksmithing then for weapon smithing... currently @ 372 and CANT pick up the quest to start WeaponSmithing... Please fix this issue, looks like i have to unlearn blacksmithing now and go for 2x gathering.... wtf.... another link to the quest is: http://db.excalibur.ws/?quest=5284

**Comment by Evolvee** [comment]
https://github.com/Atlantiss/NetherwingBugtracker/issues/2896
