### ISSUE TITLE
Pure Water pool spawning in "water too shallow" error place

### ISSUE THREAD

**Issue by rangobob** [Atlantiss/NetherwingBugtracker#5411]
[//]: # (Enclose links to things related to the bug using http://wowhead.com or any other TBC database.)
[//]: # (You can use screenshot ingame to visual the issue.)
[//]: # (Write your tickets according to the format:)
[//]: # ([Quest][Azuremyst Isle] Red Snapper - Very Tasty!)
[//]: # ([NPC] Magistrix Erona)
[//]: # ([Spell][Mage] Fireball)
[//]: # ([Npc][Drop] Ghostclaw Lynx)
[//]: # ([Web] Armory doesnt work)
[//]: # (To find server revision type `.server info` command in the game chat.)

**Description**: 
https://imgur.com/SeRvi6L

**Current behaviour**:
Can't be fished where it spawns.
**Expected behaviour**: 
should be able to spawn at a fishable location!
**Server Revision**: 
2893

**Comment by Evolvee** [comment]
can you screenshot a map spot where this is pls?

**Comment by Tenoutoften** [comment]
looks to be around the throne of elements

**Comment by rangobob** [comment]
yes its at the throne of elements. the very north side of the lake at garador

**Comment by Evolvee** [comment]
i dont see it, need a point on map or better screenshot with minimap

**Comment by rangobob** [comment]
okay, i'll provide that in a bit

**Comment by rangobob** [comment]
https://imgur.com/mCcmQbm

**Comment by Evolvee** [comment]
rev 2911
