### ISSUE TITLE
[Zone][Moonglade] Nighthaven should have an inn/place where you can rest

### ISSUE THREAD

**Issue by somnu** [Atlantiss/NetherwingBugtracker#5412]
**Description**: 
Moonglade should have a place where players can rest in the building where Lorelae Wintersong is.

**Current behaviour**:
Currently players can't receive rested bonus in Nighthaven

**Expected behaviour**: 
Proof: https://wowwiki.fandom.com/wiki/Nighthaven#Inn

**Server Revision**: 
2893

**Comment by Evolvee** [comment]
there is no area_trigger i can bind the rested status on, the rested mention on wowwiki got added in 2010+ so... may not be that case on tbc
