### ISSUE TITLE
[Spell][Mage]Arcane Missiles occasionally does not fire the 5th (last) missile

### ISSUE THREAD

**Issue by hudson1337** [Atlantiss/NetherwingBugtracker#5413]
**Description**: 

When channeling arcane missiles, sometimes the last missile (5th for max rank) does not fire, although the sound of the last missile "firing" does occur. No missile leaves the caster's hand and the mob does not receive any damage from the last one.

**Current behaviour**:

Arcane missiles does not always fire 5 missiles, the last one does not fire.

**Expected behaviour**: 

Arcane missiles should always fire 5 missiles for max rank

**Server Revision**: 
2893

**Comment by Tenoutoften** [comment]
Can you add a few recordings of this happening?

**Comment by hudson1337** [comment]
@Tenoutoften https://www.youtube.com/watch?v=2Y5aYVo5bXw&feature=youtu.be . It is this same thing everytime

**Comment by Spaztick** [comment]
This has been an issue with private servers across time, with arcane missiles and mind flay and channeled spells in general.

**Comment by BidingMyTime** [comment]
This is still an issue.
As seen in the video it has nothing to do with incoming damage.
What I would like to add that despite the mild phrasing by the OP ("sometimes the last missile does not fire"), in my experience it happens around 40-50% of the casts (appearantly at random).

Fixing this bug will notably increase the effctiveness of the spell by 50/33/25% on the bugged casts (for ranks 1/2/3+ respectively), which imo is a pretty big impact.

**Comment by bidaumm** [comment]
Description:
When casting Arcane Missiles (with no interuption) occasionally the final tick of damage and animation will not go out.

This happens inconsistently for me. Please see the following twitch clip for further information including my FPS/ping showing from pfUI
https://clips.twitch.tv/CheerfulQuaintAnacondaKippa
Server Revision:
Atlantiss Karazhan | Content patch: 2.0.3 | Revision: 3517

**Comment by Godmatik** [comment]
Duplicate #8376
