### ISSUE TITLE
A Little Help From My Friends - Get stuck

### ISSUE THREAD

**Issue by Brian-Shaw** [Atlantiss/NetherwingBugtracker#5415]
[//]: # (Enclose links to things related to the bug using http://wowhead.com or any other TBC database.)
[//]: # (You can use screenshot ingame to visual the issue.)
[//]: # (Write your tickets according to the format:)
[//]: # ([Quest][Azuremyst Isle] Red Snapper - Very Tasty!)
[//]: # ([NPC] Magistrix Erona)
[//]: # ([Spell][Mage] Fireball)
[//]: # ([Npc][Drop] Ghostclaw Lynx)
[//]: # ([Web] Armory doesnt work)
[//]: # (To find server revision type `.server info` command in the game chat.)

**Description**: I take the quest from Ringo and I move half a step and get stuck. The screen freezes and I can't do anything other than move the mouse. I try to control alt delete to get the manager tool up to close WoW and that doesn't even work. I can't even log back in till the timer goes away for the quest without the same thing happening. It's happened two times now, tried starting it again and no luck

**Current behaviour**: I can't log in without getting screen frozen

**Expected behaviour**: I don't get frozen

**Server Revision**: Not sure what goes here. It's 3/18/2019

**Comment by Godmatik** [comment]
Sounds like a client issue, try deleting your cache

**Comment by Drayo** [comment]
Pretty sure this is a timed quest, Questhelper was the problem.

**Comment by Tereneckla** [comment]
Questhelper problem with timed quests
