### ISSUE TITLE
enchanting

### ISSUE THREAD

**Issue by buxso** [Atlantiss/NetherwingBugtracker#5417]
enchanting trainer in Thrallmar didnt teach me the spell: [Small Prismatic Shard]. which one is turning 1 large prismatic shard in to the 3 small prismatic shard. fix this bug pls

**Comment by Tenoutoften** [comment]
This isn't a bug, it wasn't added before patch 2.2.
http://web.archive.org/web/20071117170106/http://thottbot.com/s42615

**Comment by buxso** [comment]
ok tnx for infor
