### ISSUE TITLE
(Rev: 2893) Trinket Macro not working anymore

### ISSUE THREAD

**Issue by frenkzenith** [Atlantiss/NetherwingBugtracker#5418]
Since revision 2893 using a macro:

#showtooltip
/use trinket 1
/use trinket 2

Trinket 1 will be launched but Trinket 2 will be put on a 20sec cooldown instead of being launched. (They are not both the same trinket)

It was not like that since the server launch so i dont know if this is a bug.

**Comment by Tenoutoften** [comment]
Got to tell us which trinkets you are using...
Some trinkets use the same spellID and share cooldown, despite being different trinkets

**Comment by frenkzenith** [comment]
Core of Ar'kelos
and
Bladefist's Breadth

both was working together before rev 2893

**Comment by gvozdeni** [comment]
Pretty sure those have a 15 sec cooldown before you can use another, at least that is how it was when i used them.

**Comment by frenkzenith** [comment]
So for trinket macro this revision is bugged or all the previous revision were bugged ?

**Comment by Evolvee** [comment]
there was a bug that allowed u to use 2 similar trinkets few days ago
