### ISSUE TITLE
Rumsey Rum Black Label drunk effect won't end

### ISSUE THREAD

**Issue by Lithits** [Atlantiss/NetherwingBugtracker#5419]
**Description**:  Before restart at 19.03.2019 I was doing Ramps hc and drank Rumsey Rum Black Label. Then server crashed 5min before the restart and my character was still under influence of drunk effect. When I logged back in the effect persisted even trough death in a form of uncontrollable wonky walking animation, when a character strafes from side to side(even in ghost form!!) I logged out for 30min, cleared cache, logged back in, but still have this effect applied to my character.

**Current behaviour**:

**Expected behaviour**: 

**Server Revision**:

**Comment by Wolffenstein** [comment]
fixed
