### ISSUE TITLE
[Warlock] [Pet] Pet passive mode

### ISSUE THREAD

**Issue by Kvel2D** [Atlantiss/NetherwingBugtracker#542]
[//]: # (Enclose links to things related to the bug using http://wowhead.com or any other TBC database.)
[//]: # (You can use screenshot ingame to visual the issue.)
[//]: # (Write your tickets according to the format:)
[//]: # ([Quest][Azuremyst Isle] Red Snapper - Very Tasty!)
[//]: # ([NPC] Magistrix Erona)
[//]: # ([Spell][Mage] Fireball)
[//]: # ([Npc][Drop] Ghostclaw Lynx)
[//]: # ([Web] Armory doesnt work)

**Description**: 
Putting warlock's pet into passive mode doesn't interrupt it's spell cast.

**Current behaviour**: 
Putting warlock's pet into passive mode stops it from casting later spells but the imp still finishes the current cast. Specifically, the pet resets it's position so that it stands next to the warlock and the spell still goes off even when the pet is facing away from the target.

**Expected behaviour**: 
Putting warlock's pet into passive mode should interrupt it's current cast.

**Server Revision**: 2050

**Comment by Easyfraggy** [comment]
> A related issue with warlock pets is that when you tell the pet to switch to a different target mid-cast, it will finish the cast on the old target before starting to cast spells on the new one.

Need proof of this, this sounds wrong. It should finish cast unless you directly tell it to stop casting/passive.

**Comment by Kvel2D** [comment]
https://www.mmo-champion.com/threads/823369-Warlock-pet-attack-when-I-start-casting
> Hmm, that's one issue I do have with my macro, my elemental breaks off casting and immediately starts attacking the new target. So the /cast !Firebolt syntax makes them finish the current cast?

http://www.arenajunkies.com/topic/177807-pet-stop-attack-macroed/
> Also don't bind your pet attack to one of your offensive abilities. Every time you spam that ability, your pet will start to recast his frostbolt so you kind lose a bit of dps

**Comment by Easyfraggy** [comment]
That is not proof of your claim though because the macro directly tells the imp to cast a fireball on a specific target (yours) in both of these cases, where as clicking the "attack" button doesn't tell it to cast a spell directly. If you however clicked the fireball button while targetting something else, then yes it would probably stop casting and start on the new one. 

I'm not sure if you are wrong, but what you linked above isn't really proof enough.

**Comment by Easyfraggy** [comment]
This is from 2010, need some proof from 2.4.3 september 2008 at the latest.
