### ISSUE TITLE
Wrong itemization on two SSC items

### ISSUE THREAD

**Issue by Manaci** [Atlantiss/NetherwingBugtracker#5420]
**Description**: Currently the Rift Stalker Gauntlets and Mantle of the Tireless Tracker have the wrong itemization.

**Current behaviour**:
Currently the Rift Stalker Gauntlets have MELEE critical strike rating as seen here
![current bugged one](https://user-images.githubusercontent.com/26745981/54619502-fb9bfd80-4a64-11e9-83e1-47c709f54f79.png)
Currently the Mantle of the Tireless Tracker have MELEE hit rating as seen here
![same shit](https://user-images.githubusercontent.com/26745981/54619510-0191de80-4a65-11e9-8a5e-dc733dcdbe28.png)

**Expected behaviour**: 
The Rift Stalker Gauntlets should have normal critical strike rating in 2.0. [Proof](https://web.archive.org/web/20070217190738/http://wow.allakhazam.com/db/itemset.html?setid=652)
The Mantle of the Tireless Tracker should have normal hit rating in 2.0. [Proof](https://web.archive.org/web/20070517071152/http://wow.allakhazam.com/db/item.html?witem=30085)

**Server Revision**: 
2893

**Comment by sifiuocz** [comment]
https://github.com/Atlantiss/NetherwingBugtracker/issues/3715
Still not fixed

**Comment by Kristoferhh** [comment]
Glad to know this is a bug, was really surprised when I saw melee crit on the gloves.

**Comment by Wolffenstein** [comment]
Fixed in rev 2902.
