### ISSUE TITLE
Mail, auctionhouse, mail fail to load, item disapear from mail

### ISSUE THREAD

**Issue by gorkig** [Atlantiss/NetherwingBugtracker#5421]
**Description**: 

Lost mail from Auctionhouse. I have exspirenced this two times. Lastly few days ago, i lost a mail from the auctionhouse when i cancelled the auction. I did receive a mail, but the icon wasent of the item (runic spellthreat), but it was only icon of a scroll (the same icon when you sell items). I autolooted this mail, but i dident get it in inventory. 
 
**Current behaviour**:

(rarely) lose item when autolooting the mailbox. It only happend for me when the items wasent fully loaded (the icon). 

**Expected behaviour**: 

The mail should't disapear. 

**Server Revision**: 
2893

maybe relevant info...

Addons: 
Postal <ace2>
Postman <ace2>

things i tried:
- delete cache 
- relog
- waited 2 days ~

**Comment by gorkig** [comment]
The issue happend again. I manage to capture a few screenshot if that helps to troubleshoot. 

first a picuture that shows how the mail looked when i looted it:
https://imgur.com/0NLSORK

Secound, a picture after i waited a few mintues to see if the item would load: 
https://imgur.com/F6jqRvK

Seems a fix on the user side is to simply wait for the mail to load, and not try to autoloot before.

**Comment by Tereneckla** [comment]
rev 3058
