### ISSUE TITLE
Healthstone  

### ISSUE THREAD

**Issue by sposobniy** [Atlantiss/NetherwingBugtracker#5422]
**Description**:  Warlock  (healthstone ) should restore currently amount of health . 
With tailents 2496 /without improve tailents 

**Current behaviour**: heals more than it should  (yesterday on arena was 5k+ critical heals 2-3 times ).  

noncrit heal me 3200+
https://imgur.com/ApG7RTl

**Comment by Evolvee** [comment]
do u have some trinket to increase potion effect?

**Comment by liderer** [comment]
Nope , i  dont have any effect. 
played today : 3311 noncrit 
https://clips.twitch.tv/SparklyKnottyMartenKlappa   
crit with 3 wounds 
www.twitch.tv/sposobniy/clip/SparklyKnottyMartenKlappa

**Comment by liderer** [comment]
about this bug , its looks like Healthstone affected bonus healing/spd .

**Comment by sposobniy** [comment]
https://youtu.be/sdToe5nqAUY?t=61 shaman used healthstone , he heal im based 2496  (without any spd bonus

**Comment by Evolvee** [comment]
@Manaci @Tereneckla test pls

**Comment by Tereneckla** [comment]
Yes, scales with +healing currently

**Comment by Wolffenstein** [comment]
Fixed in rev 3364.
