### ISSUE TITLE
 Mind Soothe 

### ISSUE THREAD

**Issue by liderer** [Atlantiss/NetherwingBugtracker#5423]
**Description**: 
Mind Soothe  http://db.deathside.ru/?spell=25596  have physical school.

**Current behaviour**: 
this spell priest removes spell reflect/grounding totems effects -what should not be . 

**Expected behaviour**:  

1) its tbc july 2008 - s4 on retail

www.arenajunkies.com/topic/28105-concerning-spell-reflect 
"as far as i know mind soothe does not work on spell reflect " 
"Yeah sorry about that, it gets reflected but doesn't eat the debuff. damn  " 
"mind soothe doesnt work on spell reflect for quite a while now because its a phisical"

2)  next proves past tbc ,but about tbc 

www.arenajunkies.com/topic/70334-interesting-priest-tricks-and-info/page-4  

in season 3 & 4, mind soothe was 'reflected' but didn't consume the spell reflect buff. i dont know if this has changed 
3)
http://www.arenajunkies.com/topic/89975-how-do-you-remove-spell-reflect
"mind soothe didnt consume spell reflect in TBC even though it got reflected, I supposed it still worked like that "

**Comment by gabbat** [comment]
also causes aggro and pulls if resisted on mobs

**Comment by narayagh** [comment]
> also causes aggro and pulls if resisted on mobs

This is correct.

https://wowwiki.fandom.com/wiki/Mind_Soothe
_Beware of casting it on higher level mobs, as they are more likely to resist, which puts you into combat._

**Comment by gabbat** [comment]
okay nvm my comment then, deleting in a bit

**Comment by Wolffenstein** [comment]
Fixed in rev 3111.
