### ISSUE TITLE
Warlock pet disappears after mounted (random) 

### ISSUE THREAD

**Issue by jaded75** [Atlantiss/NetherwingBugtracker#5424]
[//]: # (Enclose links to things related to the bug using http://wowhead.com or any other TBC database.)
[//]: # (You can use screenshot ingame to visual the issue.)
[//]: # (Write your tickets according to the format:)
[//]: # ([Quest][Azuremyst Isle] Red Snapper - Very Tasty!)
[//]: # ([NPC] Magistrix Erona)
[//]: # ([Spell][Mage] Fireball)
[//]: # ([Npc][Drop] Ghostclaw Lynx)
[//]: # ([Web] Armory doesnt work)
[//]: # (To find server revision type `.server info` command in the game chat.)

**Description**: 
When I mount up sometimes my voidwalker will disapear when i unmount and will not be there forcing me to resummon my pet, and this behavior is completely random and only happens sometimes and is VERY FRUSTRATING 
**Current behaviour**:Pets  despawn after getting off of your mount SOMETIMES 
**Expected behaviour**: 
pets never despawn after getting off of mount
**Server Revision**:

**Comment by Kristoferhh** [comment]
This has also started happening to me (hunter). Although not as annoying as it is for warlocks im sure :p still annoying to have to re-call the pet.

**Comment by Vaped** [comment]
Yup
Happens to me all the time.
Im at the stage of just getting soul shard off every mob cause it happens so much.
Really hope it gets fixed.

**Comment by DaedalusMachina007** [comment]
Please fix this issue as it still affects both warlock minions and hunter pets.

**Comment by The14me** [comment]
If u bring a way to reproduce...gonna take a very short time for a fix(hope so).I try to repo it too....but no luck so far.

**Comment by Wolffenstein** [comment]
Can't reproduce.
