### ISSUE TITLE
Scuffed arena system

### ISSUE THREAD

**Issue by teddys** [Atlantiss/NetherwingBugtracker#5425]
**Description**:  https://forum.atlantiss.eu/netherwing/topic/1176-explain-me-the-mmr-system-please/?tab=comments#comment-6270

**Current behaviour**: People are losing very little rating when they lose (because everyone's mmr is too high?)

**Expected behaviour**:  https://imgur.com/Me3ugOP The mmr loss formula might be wrong (need someone to help me find evidence for this though)
/e https://youtu.be/4MVPe4IUcnc?t=590 I know it's not wow, but it's the same system pmuch
**Server Revision**: 2893

**Comment by Wolffenstein** [comment]
I made some changes and reduced inflated mmr to proper values. Hopefully it should be better now.
