### ISSUE TITLE
Hunter pets need serious work in Arena (pathing + UI + abilities)

### ISSUE THREAD

**Issue by Falathrin** [Atlantiss/NetherwingBugtracker#5427]
[//]: # (Enclose links to things related to the bug using http://wowhead.com or any other TBC database.)
[//]: # (You can use screenshot ingame to visual the issue.)
[//]: # (Write your tickets according to the format:)
[//]: # ([Quest][Azuremyst Isle] Red Snapper - Very Tasty!)
[//]: # ([NPC] Magistrix Erona)
[//]: # ([Spell][Mage] Fireball)
[//]: # ([Npc][Drop] Ghostclaw Lynx)
[//]: # ([Web] Armory doesnt work)
[//]: # (To find server revision type `.server info` command in the game chat.)

**Description**: 

* when a pet dies and you revive it, the mini pet UI doesn't show up. So you can't call it back to you it just stays on enemy. The only way to fix this is dimissing and resummoning. That's very frustrating in Arena.

* Sometimes the pet glitches in place, mainly in BEM map's ramps. Again to fix it, you need to dismiss and recall.

* I reported this earlier in a different thread: pet not casting its abilities - the spell book disappears. The way to fix this is you need to go to trainer to unlearn pet abilities and reteach it everything again. Doesn't seem like a big deal but you literally have to check your pet spell book before every Arena game so you know you aren't queueing up with a bugged pet with no abilities. Sometimes you forget checking and you lose the game easily.

Pls fix hunter pets in PVP, and mainly Arenas. It's extremely frustrating.

**Current behaviour**:

**Expected behaviour**: 

**Server Revision**:

**Comment by gunzbngbng** [comment]
Work around for pets not having skills, dismiss and call again.  It will often fix with plenty of time before the match begins.

Hope this helps in the meantime.

**Comment by Godmatik** [comment]
These all were fixed long ago, closing.
