### ISSUE TITLE
[World] Deeprun Tram Trains

### ISSUE THREAD

**Issue by Avatarstate** [Atlantiss/NetherwingBugtracker#543]
[//]: # (Enclose links to things related to the bug using http://wowhead.com or any other TBC database.)
[//]: # (You can use screenshot ingame to visual the issue.)
[//]: # (Write your tickets according to the format:)
[//]: # ([Quest][Azuremyst Isle] Red Snapper - Very Tasty!)
[//]: # ([NPC] Magistrix Erona)
[//]: # ([Spell][Mage] Fireball)
[//]: # ([Npc][Drop] Ghostclaw Lynx)
[//]: # ([Web] Armory doesnt work)

**Description**: 
Both deeprun tram trains are going the same direction at the same time, synced with one another.
**Current behaviour**:
Both trains are synced together
**Expected behaviour**: 
Each train should be going the opposite direction. 
**Server Revision**: 
2050

**Comment by Wolffenstein** [comment]
Fixed
