### ISSUE TITLE
Stealth/Prowl/Shadowmeld is broken

### ISSUE THREAD

**Issue by killiaan** [Atlantiss/NetherwingBugtracker#5430]
**Description**: 
Stealth/Prowl/Shadowmeld is broken. People can see you from miles away. ever since today. Also when you your target is facing his back, it works  properly but as soon as he faces you he can instantly see you
**Current behaviour**:
When you either stealth, prowl or shadowmeld (even with improved prowl/stealth) you get detected from a very far distance. Tested this in arena/Bg's/Duels and most of the times you can be seen for 15+ yards away.

**Comment by killiaan** [comment]
![stealth](https://user-images.githubusercontent.com/8603726/54648992-a550ae00-4aa8-11e9-88ef-1511b590168f.jpg)

**Comment by killiaan** [comment]
This is just an example, people who dont have improved stealth = even worse

**Comment by ttghnw** [comment]
I can confirm this as of today. It is totally broken at least for mobs, I noticed right away whilst farming that the mobs were seeing through stealth super easily, went into a lvl 20 area at lvl 70 and they behave as if you are not stealthed at all.

**Comment by killiaan** [comment]
Its also in PVP, same thing. Tested several times and its unplayable in PV (esp arena as u might be able to imagine). Please fix!

**Comment by Jalapan** [comment]
from discord

[2895][Core] Visibility Rework

Is it better?

**Comment by imabearlol** [comment]
Better, however mobs still see you and aggro immediately when you Shadowstep on them from stealth. This shouldn't happen.

**Comment by Greytt** [comment]
> Better, however mobs still see you and aggro immediately when you Shadowstep on them from stealth. This shouldn't happen.

This happens now still, especially after 2939 - I can barerly pickpocket with 5/5 MoD on mobs, shadow step sap sometimes does not work because they detect etc. 
I haven't tried without 5/5 MoD yet.

**Comment by Nugsss** [comment]
Stealth has definitely seemed strange on this server. Without MoD, I can't sneak up behind anything unless they are 5 levels lower than me. If something has 2 or 3 levels on me, stealth has almost no effect.
With MoD, It's fairly useable, but still not great.
