### ISSUE TITLE
[warrior][rogue][ability] piercing howl does not break vanish

### ISSUE THREAD

**Issue by teddys** [Atlantiss/NetherwingBugtracker#5431]
**Description**:  Piercing howl does not break vanish

**Current behaviour**: https://www.twitch.tv/videos/398125993 6:06

**Expected behaviour**:  You are not able to "immune" piercing howl while under the effects of vanish

**Server Revision**:  2893

**Comment by Wolffenstein** [comment]
Fixed in rev 2906.

**Comment by teddys** [comment]
rev 2912
It's still happening .. not fixed

**Comment by santuzzo** [comment]
still broken

**Comment by teddys** [comment]
not fixed

**Comment by teddys** [comment]
bump

**Comment by tsuone** [comment]
Works.

**Comment by tsuone** [comment]
It does brake the Vanish but not instantly.
