### ISSUE TITLE
Sapper procs windfury

### ISSUE THREAD

**Issue by KarlDenXII** [Atlantiss/NetherwingBugtracker#5432]
[//]: # (Enclose links to things related to the bug using http://wowhead.com or any other TBC database.)
[//]: # (You can use screenshot ingame to visual the issue.)
[//]: # (Write your tickets according to the format:)
[//]: # ([Quest][Azuremyst Isle] Red Snapper - Very Tasty!)
[//]: # ([NPC] Magistrix Erona)
[//]: # ([Spell][Mage] Fireball)
[//]: # ([Npc][Drop] Ghostclaw Lynx)
[//]: # ([Web] Armory doesnt work)
[//]: # (To find server revision type `.server info` command in the game chat.)

**Description**: 
Sapper is bugged.

**Current behaviour**:
Sapper procs windfury

see: https://media.discordapp.net/attachments/406669860257660932/557721859118989333/unknown.png

**Expected behaviour**: 
Sapper shouldn't proc windfury

**Server Revision**: 
2893

**Comment by Regimant** [comment]
Sapper isn't bugged , WF is. all dots proc WF, but they proc for the dmg of the thing that proced them, when they should be procing auto attack damage.

**Comment by Wolffenstein** [comment]
It's a visual bug with proc tracking addons. Windfury does not proc from anything that shouldn't proc it.
