### ISSUE TITLE
[Spell] Misdirection

### ISSUE THREAD

**Issue by Drayo** [Atlantiss/NetherwingBugtracker#5433]
[//]: # (Enclose links to things related to the bug using http://wowhead.com or any other TBC database.)
[//]: # (You can use screenshot ingame to visual the issue.)
[//]: # (Write your tickets according to the format:)
[//]: # ([Quest][Azuremyst Isle] Red Snapper - Very Tasty!)
[//]: # ([NPC] Magistrix Erona)
[//]: # ([Spell][Mage] Fireball)
[//]: # ([Npc][Drop] Ghostclaw Lynx)
[//]: # ([Web] Armory doesnt work)
[//]: # (To find server revision type `.server info` command in the game chat.)

**Current behaviour**: 

The Misdirection Buff does not fade after all charges are used up.

**Expected behaviour**: 

The buff should fade after all 3 stacks were used, allowing other Hunters to MD after the first one.
Currently, the tank needs to manually remove the Buff, which is really awkward.

**Server Revision**: 2894

**Comment by Jalapan** [comment]
A note here, i think also only the first 2 shots out of the 3 is giving away the aggro to the target.

also related https://github.com/Atlantiss/NetherwingBugtracker/issues/2702

**Comment by Realnairoby** [comment]
Any news on this?

**Comment by Wolffenstein** [comment]
Fixed in rev 2984.
