### ISSUE TITLE
[Tempest Keep] [Boss] Solarian - Wrath of the Astromancer

### ISSUE THREAD

**Issue by Drayo** [Atlantiss/NetherwingBugtracker#5434]
[//]: # (Enclose links to things related to the bug using http://wowhead.com or any other TBC database.)
[//]: # (You can use screenshot ingame to visual the issue.)
[//]: # (Write your tickets according to the format:)
[//]: # ([Quest][Azuremyst Isle] Red Snapper - Very Tasty!)
[//]: # ([NPC] Magistrix Erona)
[//]: # ([Spell][Mage] Fireball)
[//]: # ([Npc][Drop] Ghostclaw Lynx)
[//]: # ([Web] Armory doesnt work)
[//]: # (To find server revision type `.server info` command in the game chat.)

**Current behaviour**: When this Spell jumps to a Priest in Spirit Form, the debuff simply vanishes.

**Expected behaviour**:  Wrath of the Astromancer must not be cast on, or jump to a Priest in Spirit Form.

**Server Revision**: 2894

**Comment by Wolffenstein** [comment]
I already fixed it
