### ISSUE TITLE
Priest Stun resist racial/Stun Resist Meta Gem not working

### ISSUE THREAD

**Issue by asdwdas** [Atlantiss/NetherwingBugtracker#5435]
Priest Stun resist talent in the disc tree as well as the meta gem with 5% stun resist is not working

The talent gives 15% chance to resist stun, so 20% with the gem combined.

I haven't resisted a stun ever

**Comment by Evolvee** [comment]
and i resisted 3 in a row..

see how irrelevant this message without any evidence is?
