### ISSUE TITLE
[Core][UI] Inspect target changes when hovering another player

### ISSUE THREAD

**Issue by Kristoferhh** [Atlantiss/NetherwingBugtracker#5436]
**Description**:  Inspect target changes when hovering another player

**Current behaviour**: When you're inspecting a player and viewing either the PvP or Talents tab, the inspect target changes when you hover another player and you start viewing the PvP/Talents for the player you hovered over.

**Expected behaviour**: The target being inspected should only change when you actually target the player, not only hover over them.

**Server Revision**: 2897

**Comment by Evolvee** [comment]
your addons issue

**Comment by Kristoferhh** [comment]
ah, my mistake then. I thought this had happened to me as well when I didn't have addons enabled.
