### ISSUE TITLE
Lack of Healing on Waffa

### ISSUE THREAD

**Issue by Papariven** [Atlantiss/NetherwingBugtracker#5437]
**Description**:  Waffa still dying in Exiled raids due to general lack of healing.

**Current behaviour**:  Currently, during multiple 10 and 25M raids, Waffa is still dying despite consistent  warnings to the raid.

**Expected behaviour**:  Waffa should receive healing.

**Server Revision**: Heal Waffa.

**Comment by Dollywog** [comment]
https://www.twitch.tv/varbane/clip/PerfectUglyPotatoWTRuck?filter=clips&range=7d&sort=time

Can confirm , vod above
