### ISSUE TITLE
Darkwingduck

### ISSUE THREAD

**Issue by blue100xx** [Atlantiss/NetherwingBugtracker#5438]
[//]: # (Enclose links to things related to the bug using http://wowhead.com or any other TBC database.)
[//]: # (You can use screenshot ingame to visual the issue.)
[//]: # (Write your tickets according to the format:)
[//]: # ([Quest][Azuremyst Isle] Red Snapper - Very Tasty!)
[//]: # ([NPC] Magistrix Erona)
[//]: # ([Spell][Mage] Fireball)
[//]: # ([Npc][Drop] Ghostclaw Lynx)
[//]: # ([Web] Armory doesnt work)
[//]: # (To find server revision type `.server info` command in the game chat.)

**Description**: 3 pieces of spellcloth that where made from me are now missing. logged on a couple days later and they were gone, was just wondering if I can get them back so my mom doesn't kill me cause you know they are expensive. Character name is DarkwingDuck, Thanks!

**Current behaviour**:

**Expected behaviour**: 

**Server Revision**:

**Comment by Evolvee** [comment]
this is a GM matter, doesnt belong to bugtracker
