### ISSUE TITLE
Group loot issue with party member in different zone.

### ISSUE THREAD

**Issue by LoGReeper** [Atlantiss/NetherwingBugtracker#544]
**Description**:  Group loot still pops up to roll for an item when you're not in the same zone as the person in your party. The party member left at the same moment that the item was being rolled for, which caused the item to be unlootable and then despawned with the mob that had the item on it.

**Current behaviour**:  Group loot still pops up to roll for an item when you're not in the same zone as the person in your party.

**Expected behaviour**: Either the item isn't rolled for unless both party members are nearby eachother, or the item does not despawn until looted (or longer timer is reached) when players leave party during item rolls.

**Server Revision**:

**Comment by Erodraeda** [comment]
https://clips.twitch.tv/QuaintIgnorantToadHassaanChop
Happens to me everytime too.
