### ISSUE TITLE
[quest][minor] Grillok "Darkeye"

### ISSUE THREAD

**Issue by Godmatik** [Atlantiss/NetherwingBugtracker#5440]
**Description**: 
Quest reward gives wrong amount of experience. It's such a minor difference but I found the amount it gave you to be quite random and amusing...

**Current behaviour**:
Gives 12,624 EXP

**Expected behaviour**: 
Should be 12,600 EXP

**Server Revision**: 
2897

**Comment by Tenoutoften** [comment]
It's well known that a lot of quests gives slightly incorrect amount of xp

**Comment by The14me** [comment]
Wowwiki 12,600 EXP
Wowhead 15,250 experience
Other source  12,624 experience
WoWDB 9,580 experience
Lets just....move on and be happy with the bonus of 24 xp :peepoHappy:
