### ISSUE TITLE
[MOB] Mistress of Doom in Hellfire Peninsula

### ISSUE THREAD

**Issue by Godmatik** [Atlantiss/NetherwingBugtracker#5441]
**Description**: 
This mob is supposed to summon imps but it's not working properly

**Current behaviour**:
Two imps get summoned when her health reaches around 33% health, but one despawns instantly, leaving you to deal with only one imp

**Expected behaviour**: 
Should spawn two imps for you to kill. Also, I believe there is a cast bar that should be present, but she is summoning them instantly instead.

**Server Revision**: 
2897

**Comment by Evolvee** [comment]
34237 spell problem - acts as a guardian/guardian ai
