### ISSUE TITLE
Scepter of Celebras Quest bugged

### ISSUE THREAD

**Issue by Talespinner** [Atlantiss/NetherwingBugtracker#5442]
Turned in my quest to Celebras to make the scepter and he took my two items to make the scepter, but never finished channeling to complete so I go no xp for the quest and no scepter. Could i please get my scepter? I really don't want to have to run Maraudon again to get it.

**Comment by Evolvee** [comment]
nick?

**Comment by ScottieDOESknow** [comment]
Same thing happened in Mara group just yesterday.

Everyone in group was on quest (2nd part) to create scepter - NPC started RP then stopped, was stuck, and then eventually disappeared.

still shows quest completed in quest log

![image](https://user-images.githubusercontent.com/43949261/54862630-e26ca880-4d13-11e9-813d-28be79f8b9b8.png)


IGN Abracadabra

**Comment by Evolvee** [comment]
fixed in next rev
