### ISSUE TITLE
Water Elemental Freeze

### ISSUE THREAD

**Issue by rawiel** [Atlantiss/NetherwingBugtracker#5443]
**Description**: 

When summoning a second Water Elemental using Cold Snap, your pet's Freeze cooldown isn't reset. Freeze was being reset up until this week. Something must have broken

**Current behaviour**:

Resummoning Water Elemental does not reset Freeze cooldown

**Expected behaviour**: 

Resummoning Water Elemental resets Freeze cooldown

**Comment by Tenoutoften** [comment]
https://github.com/Atlantiss/NetherwingBugtracker/issues/5404
