### ISSUE TITLE
Bug with water totem quest.

### ISSUE THREAD

**Issue by Smashstar** [Atlantiss/NetherwingBugtracker#5444]
So im on the last part of the quest to get the water totem quest. I accepted the quest off the water elemental in Silverpine Forest to go back to The Barrens to speak to the tauren in ratchet. Then the server rolls back. I no longer have the quest in my log and i've lost the sapta which allows you to the see the water elemental with the quest. There is also no way of getting the water sapta back at all. (Horde Side of course)

**Comment by Jalapan** [comment]
Go to discord support channel and ask for help

**Comment by Smashstar** [comment]
I've done this and it took 2 days just to get a mail saying put it in this bug tracker website with no solution to problem.

**Comment by danbopes** [comment]
Abandoning and repicking up the quest should give you the Water Sapta back

**Comment by Manaci** [comment]
Not a bug, just server restart fiesta
