### ISSUE TITLE
[Dungeon][Heroic] Hellfire Ramparts - Nazzan

### ISSUE THREAD

**Issue by Dragunovka** [Atlantiss/NetherwingBugtracker#5445]
Hello frens. I found a little bug some time ago (week, mb earlier) in Ramps HC (maybe in normal too, didnt check). When u fighting last Ramps boss and dragon shoot Fireball (https://www.wowhead.com/spell=33793/fireball) on u, fire becomes invisible. pls fix muh blizzlike!

**Comment by Wolffenstein** [comment]
Duplicate #5450.
