### ISSUE TITLE
[Priest] [Talent] Martyrdom - not proccing correctly

### ISSUE THREAD

**Issue by murxl** [Atlantiss/NetherwingBugtracker#5446]
[//]: # (Enclose links to things related to the bug using http://wowhead.com or any other TBC database.)
[//]: # (You can use screenshot ingame to visual the issue.)
[//]: # (Write your tickets according to the format:)
[//]: # ([Quest][Azuremyst Isle] Red Snapper - Very Tasty!)
[//]: # ([NPC] Magistrix Erona)
[//]: # ([Spell][Mage] Fireball)
[//]: # ([Npc][Drop] Ghostclaw Lynx)
[//]: # ([Web] Armory doesnt work)
[//]: # (To find server revision type `.server info` command in the game chat.)

**Description**: 
Martyrdom procc Focussed Casting is not proccing after you got critted
**Current behaviour**:
rarely proccs in rdm situations more like 5% after recieving a crit than 100%
**Expected behaviour**: 
it should procc 100% after being a victim of a critical melee or ranged crit
**Server Revision**: 
2897

**Comment by Evolvee** [comment]
are you trying to proc the crit by sitting?

**Comment by murxl** [comment]
i tried it with /sit and without. its in both ways not 100%

**Comment by Wolffenstein** [comment]
![image](https://user-images.githubusercontent.com/1576644/55018501-47195300-4ff3-11e9-91aa-caca02b2b1b8.png)
Seems fine to me. If you manage to record that happening I will reopen.
