### ISSUE TITLE
Engineering

### ISSUE THREAD

**Issue by firetruck69** [Atlantiss/NetherwingBugtracker#5448]
[//]: # (Enclose links to things related to the bug using http://wowhead.com or any other TBC database.)
[//]: # (You can use screenshot ingame to visual the issue.)
[//]: # (Write your tickets according to the format:)
[//]: # ([Quest][Azuremyst Isle] Red Snapper - Very Tasty!)
[//]: # ([NPC] Magistrix Erona)
[//]: # ([Spell][Mage] Fireball)
[//]: # ([Npc][Drop] Ghostclaw Lynx)
[//]: # ([Web] Armory doesnt work)
[//]: # (To find server revision type `.server info` command in the game chat.)

**Description**: Hello.  I've recently changed from gnomish engineering to goblin engineering,  But I can't learn any of the goblin recipes.  please help?  My characters name is Wasp.

**Current behaviour**:

**Expected behaviour**: 

**Server Revision**:

**Comment by Evolvee** [comment]
did you try to contact GMs?

**Comment by firetruck69** [comment]
Yes,  for a few days now.  I even spoke to one for a minute and all he had to say was  "I don't know much about engineering."

**Comment by devo6969** [comment]
This is how you can relearn Goblin/Gnomish. A book call "Soothsaying for Dummies"
How to Change specializations - https://youtu.be/7Iv_iSatN1w?t=93
PTR - https://i.imgur.com/5iOKj3P.jpeg
