### ISSUE TITLE
Shiv OFTEN not doing anything

### ISSUE THREAD

**Issue by Mercymurv** [Atlantiss/NetherwingBugtracker#5449]
[//]: # (Enclose links to things related to the bug using http://wowhead.com or any other TBC database.)
[//]: # (You can use screenshot ingame to visual the issue.)
[//]: # (Write your tickets according to the format:)
[//]: # ([Quest][Azuremyst Isle] Red Snapper - Very Tasty!)
[//]: # ([NPC] Magistrix Erona)
[//]: # ([Spell][Mage] Fireball)
[//]: # ([Npc][Drop] Ghostclaw Lynx)
[//]: # ([Web] Armory doesnt work)
[//]: # (To find server revision type `.server info` command in the game chat.)

**Description**: 
Shiv is very wonky. Rogues are not performing well in many PVP situations because of it. 
**Current behaviour**:
Out of 29 Shivs in a row, only 14 worked. https://youtu.be/Odsksg63fYI
Combat Log shows no miss, parry, dodge, for when Shiv doesn't work. It simply tells you Shiv damaged an enemy. But even if Shiv was dodged, the behavior wouldn't be so strange. For example, in the youtube video, Shiv won't work, but it especially won't work many times in a row. There's something to do with mobility and distance.
**Expected behaviour**: 
Shiv should work like most attacks, applying if it hits the enemy. There might be a resist chance.
**Server Revision**: 
Right now rogues lose energy, hit for offhand damage, but get no poison. It's as if we're using Shiv without any poison on our off hand. Not sure what's stopping it from applying, but I know it happens most often when people are running away, or when I turn away from the enemy quickly -- there's something to do with placement and maybe ping. 
Testing it again but with a stationary rogue could help isolate the problem.

**Comment by Evolvee** [comment]
it probably doesnt show resists in combat log

**Comment by Wolffenstein** [comment]
Please retest after rev 2898.
