### ISSUE TITLE
Summoning Stone

### ISSUE THREAD

**Issue by despairr1** [Atlantiss/NetherwingBugtracker#545]
[//]: # (Enclose links to things related to the bug using http://wowhead.com or any other TBC database.)
[//]: # (You can use screenshot ingame to visual the issue.)
[//]: # (Write your tickets according to the format:)
[//]: # ([Quest][Azuremyst Isle] Red Snapper - Very Tasty!)
[//]: # ([NPC] Magistrix Erona)
[//]: # ([Spell][Mage] Fireball)
[//]: # ([Npc][Drop] Ghostclaw Lynx)
[//]: # ([Web] Armory doesnt work)

**Description**: 
The Shadowfang Keep summoning stone is sending summons but they insta vanish. 
**Current behaviour**:
It goes through and disappears after a few milliseconds.
**Expected behaviour**: 
To successfully go through!
**Server Revision**:

**Comment by Evolvee** [comment]
https://github.com/Atlantiss/NetherwingBugtracker/issues/514
