### ISSUE TITLE
[Dungeon][NPC] Hellfire Ramparts. Nazan fire animation.

### ISSUE THREAD

**Issue by Nomicc** [Atlantiss/NetherwingBugtracker#5450]
[//]: # (Enclose links to things related to the bug using http://wowhead.com or any other TBC database.)
[//]: # (You can use screenshot ingame to visual the issue.)
[//]: # (Write your tickets according to the format:)
[//]: # ([Quest][Azuremyst Isle] Red Snapper - Very Tasty!)
[//]: # ([NPC] Magistrix Erona)
[//]: # ([Spell][Mage] Fireball)
[//]: # ([Npc][Drop] Ghostclaw Lynx)
[//]: # ([Web] Armory doesnt work)
[//]: # (To find server revision type `.server info` command in the game chat.)

**Description**: 
The visual ground effect for Nazan's fire is invisible.
**Current behaviour**:
The fires left behind from both Nazan's fireball, and firebreath are invisible but still very deadly.
**Expected behaviour**: 
The fires left behind from both Nazan's fireball, and firebreath should not be invisible but still very deadly.
**Server Revision**: 
2898

**Comment by MAY-THE-ETERNAL-SUN-SHINE-UPON-YOU** [comment]
Confirmed still happens.

**Comment by SlowxP** [comment]
bump plz fix this its anoying af :p

**Comment by KevinTyrrell** [comment]
Still happening as of rev. 2939. Invisible fire makes the fight much harder than normal.

**Comment by OffeSwedin** [comment]
Bump. Still happening as of 2948.

**Comment by laco76** [comment]
12.05.2019 still not working. Please fix it!

**Comment by williamtheturtle** [comment]
The fire is still invisible as of 6/1/2019 1:48am

**Comment by rychersky** [comment]
Revision 2993, 10-6-2019 still happening.

**Comment by randomuser69** [comment]
Still happening

**Comment by Wolffenstein** [comment]
Fixed in rev 3026.
