### ISSUE TITLE
[Core][Looting] Item disappearing from corpse after everyone passed on it

### ISSUE THREAD

**Issue by Swpain** [Atlantiss/NetherwingBugtracker#5451]
https://www.wowhead.com/item=30666/ritssyns-lost-pendant
[Npc][Drop] Arcane Anomaly or Syphoner
https://www.twitch.tv/videos/398035193 (Mobs in question at 00:20)

**Description**: We killed the trash before Curator in Karazhan Tuesday (around 8:20PM, Instance ID 2885), the neck dropped, everyone passed and the neck could not be recovered from any corpse. Some corpses were left with grey items on them but no trace of the neck. 

**Current behavior**:  We killed the trash before Curator in Karazhan Tuesday (around 8:20PM, Instance ID 2885), the neck dropped, everyone passed and the neck could not be recovered from any corpse. Some corpses were left with grey items on them but no trace of the neck. Nobody in group could find it, all present during the kill could not find it either

**Expected behavior**: After all pass in a group loot configuration, item should be lootable from the corpse by anyone.

**Server Revision**: 2897

**Comment by ScottieDOESknow** [comment]
Can confirm this happened in one of our raids 3-4 weeks back.
Same exact NPC's as detailed above (Syphoner) with same item (Ritssyn's Lost Pendant)
Was gone so fast nobody even had a chance to need/greed/loot.

**Comment by Godmatik** [comment]
Unable to reproduce + have not heard of anyone experiencing this issue in past year on Netherwing server.

Will close for now and re-open if I hear of it again.
