### ISSUE TITLE
[Spell][NPC] Deathforge Tinkerer's "Shrapnel Bomb"

### ISSUE THREAD

**Issue by EnterLarry** [Atlantiss/NetherwingBugtracker#5452]
**Description**: 
Deathforge Tinkerer uses [Shrapnel Bomb](http://db.excalibur.ws/?spell=38753)
It increases the damage taken by more than intended.

**Current behaviour**:
200-250 per hit without the shrapnel debuff (means the tinkerer itself does normal damage)
With shrapnel bomb debuff it's 1200-1400 (even got crit for 2.4k with debuff up)
![Damage breakdown](https://i.imgur.com/7Mne6y7.png)

**Expected behaviour**: 
The Shrapnel Bomb debuff should increase the physical damage taken by 150 per hit.
![Debuff](https://i.imgur.com/TyPxfI6.png)

**Server Revision**: 
2898

**Comment by Evolvee** [comment]
![image](https://user-images.githubusercontent.com/1942409/54867301-06b19f00-4d7f-11e9-9b2c-93e4f397ee9d.png)

it most likely scales with level

**Comment by Godmatik** [comment]
Unable to reproduce.

It increases physical damage taken by ~150 per wowhead  - and that is roughly what it is doing.

![sdadasdasdads](https://github.com/user-attachments/assets/6e835961-1cf8-4876-a9f2-3d4f3b853a13)

![wqeweqew](https://github.com/user-attachments/assets/59ed03e5-6ca4-476c-86cf-12d8475cd2ab)
