### ISSUE TITLE
Private Thorsen offering quest, but I don't see it.

### ISSUE THREAD

**Issue by AWIDIUS** [Atlantiss/NetherwingBugtracker#5453]
https://github.com/Atlantiss/NetherwingBugtracker/issues/4368 Regarding to this issue what is old 2 months and still not fixed yet 
![image](https://user-images.githubusercontent.com/45521546/54864900-d6a5d400-4d5d-11e9-9d8b-b5c6cea86f2d.png)

**Comment by Tenoutoften** [comment]
This was reported in the beta
https://github.com/Atlantiss/NetherwingBugtracker/issues/1137
https://github.com/Atlantiss/NetherwingBugtracker/issues/797
