### ISSUE TITLE
[Item][Spell] Medallion of the Horde / Alliance not shown in combatlog

### ISSUE THREAD

**Issue by Realnairoby** [Atlantiss/NetherwingBugtracker#5458]
[//]: # (Enclose links to things related to the bug using http://wowhead.com or any other TBC database.)
[//]: # (You can use screenshot ingame to visual the issue.)
[//]: # (Write your tickets according to the format:)
[//]: # ([Quest][Azuremyst Isle] Red Snapper - Very Tasty!)
[//]: # ([NPC] Magistrix Erona)
[//]: # ([Spell][Mage] Fireball)
[//]: # ([Npc][Drop] Ghostclaw Lynx)
[//]: # ([Web] Armory doesnt work)
[//]: # (To find server revision type `.server info` command in the game chat.)

**Description**: 
The spell casted by the usage of Medallion of the Horde / Alliance is not shown in the combatlog.
**Current behaviour**:
Spell "PvP Trinket" (http://db.excalibur.ws/?spell=42292) is not shown in the combatlog.
**Expected behaviour**: 
The spell should be displayed in the combatlog as every other trinket use as well.
**Server Revision**: 
2898

**Comment by Evolvee** [comment]
evidence?
