### ISSUE TITLE
Totem of Impact fully not working. 

### ISSUE THREAD

**Issue by liderer** [Atlantiss/NetherwingBugtracker#5461]
**Description**:  http://tbc.cavernoftime.com/item=27984  
 Increases damage done by Earth Shock, Flame Shock, and Frost Shock by up to 47.

**Current behaviour**:  totally no increase in shock damage . 
How test it ? - flame shock , he deal stability damage all time (can crit) . also same dot damage . 

1)  flameshock damage (with  totem) : 424 shock +146 dot tick

www.imgur.com/JYywlw9  

2) flameshock damage without totem : same damage like with

www.imgur.com/ecqGCjt

**Comment by Wolffenstein** [comment]
Fixed in rev 2917.
