### ISSUE TITLE
[The Eye] High Astromancer Solarian: Arcane Missiles should be cast on the main target in 2.0

### ISSUE THREAD

**Issue by 5f3759** [Atlantiss/NetherwingBugtracker#5462]
**Description**: 
Solarian should cast arcane missiles on the main target rather than on random target (Aran style).
He started targeting random players in 2.1.

Sources:
https://www.youtube.com/watch?v=it01BSGM_ko
Death wish first (or 2nd kill according to comment). They killed Solarian 24 april 2007.
The behavior is the most clear at 1:20 when there are no target close to the boss except for the tank.

http://restless.clan.su/publ/3-1-0-9
Most of it is in russian but the patch notes are in english.
"Patch 2.1 note: 
Arcane Missiles are now targetted randomly in the raid. Extensive strategy and gear changes to compensate.
Mark of Solarian reduces arcane resistance by 15 now, not 30
Solarium Agent does not hit so hard, and there are only 12, not 15. Phase 2 tactics simplified to account for this.
Adds in the room now have to be cleared."

PS. The last source also claims "Adds in the room now have to be cleared.". You can also see this in the Death Wish kill video. I don't know if this is the case on Netherwing, so just ignore this paragraph if so.

**Current behaviour**:
Solarian casts arcane missiles on random players.

**Expected behaviour**: 
Solarian should cast arcane missiles on the main target.

**Server Revision**: 2898
Note: I saw this from a stream 5 days ago, so I don't know if this has been fixed since then.

**Comment by Wolffenstein** [comment]
In the first version of Solarian she casted Arcane Missiles on a random target in front of her.
