### ISSUE TITLE
Engineering Sheeps not working!

### ISSUE THREAD

**Issue by rangobob** [Atlantiss/NetherwingBugtracker#5463]
[//]: # (Enclose links to things related to the bug using http://wowhead.com or any other TBC database.)
[//]: # (You can use screenshot ingame to visual the issue.)
[//]: # (Write your tickets according to the format:)
[//]: # ([Quest][Azuremyst Isle] Red Snapper - Very Tasty!)
[//]: # ([NPC] Magistrix Erona)
[//]: # ([Spell][Mage] Fireball)
[//]: # ([Npc][Drop] Ghostclaw Lynx)
[//]: # ([Web] Armory doesnt work)
[//]: # (To find server revision type `.server info` command in the game chat.)

**Description**: 
Explosive Sheep - Engineering lvl 150
https://imgur.com/87zQxwA
**Current behaviour**:
As soon as they get planted they disappear
**Expected behaviour**: 
Last for 3 minutes and run to nearby enemies and explode.
**Server Revision**: 
2898

**Comment by Godmatik** [comment]
fixed - can close
