### ISSUE TITLE
[Halaa] Killing honorable players does not grant Halaa Battle Token

### ISSUE THREAD

**Issue by gunzbngbng** [Atlantiss/NetherwingBugtracker#5464]
[//]: # (Enclose links to things related to the bug using http://wowhead.com or any other TBC database.)
[//]: # (You can use screenshot ingame to visual the issue.)
[//]: # (Write your tickets according to the format:)
[//]: # ([Quest][Azuremyst Isle] Red Snapper - Very Tasty!)
[//]: # ([NPC] Magistrix Erona)
[//]: # ([Spell][Mage] Fireball)
[//]: # ([Npc][Drop] Ghostclaw Lynx)
[//]: # ([Web] Armory doesnt work)
[//]: # (To find server revision type `.server info` command in the game chat.)

**Description**: Halaa Battle Tokens are the only path to obtain a resilience gem in 2.0.  Which is adversely affecting pvp imo, but that's another topic.

**Current behaviour**: Killing an honorable target does not grant a Battle Token.

**Expected behaviour**: Killing an honorable target in halaa and halaa basin should grant a Battle Mark.

**Server Revision**: 2898

**Comment by werwood** [comment]
Still not working for any faction. I only got one token when my faction had halaa, i got last hit on the enemy and we were inside the town itself. Since then however, I wasn't able to get one even if I met these conditions again. Tested today on rev.3072

**Comment by Tereneckla** [comment]
#6528 is more detailed
