### ISSUE TITLE
Black Battlestrider PvP mount able to be purchased, by non Dwarf/Gnome

### ISSUE THREAD

**Issue by danbopes** [Atlantiss/NetherwingBugtracker#5465]
**Description**: 
The [Black Battlestrider](https://tbc-twinhead.twinstar.cz/?item=29465#comments) (And possibly other PvP mounts), are able to be purchased by classes that are unable to use the item. Because they're BoP and unusable, it seems silly to allow them to even be bought, when they cannot be returned. I believe in Retail Servers, the server prevented these types of transactions.

**Current behavior**:
Black Battlestrider was bought by a human:

![WoWScrnShot_032419_020327](https://user-images.githubusercontent.com/4589840/54876234-e1567c80-4de2-11e9-80c9-0612ad35c69e.jpg)
![WoWScrnShot_032419_020346](https://user-images.githubusercontent.com/4589840/54876242-fd5a1e00-4de2-11e9-940d-ecea2fab6c7b.jpg)

**Expected behavior**: 
The server should disable purchasing, and prevent this sale from taking place.

**Server Revision**: 
2898

**Comment by Valmere** [comment]
buying it was your own fault and blizzlike

**Comment by danbopes** [comment]
I was not the purchaser, and according to some wowhead comments, I believe the server stopped the transaction.

**Comment by danbopes** [comment]
It does appear that you could buy them mistakenly on blizzards servers as well. /closed
