### ISSUE TITLE
Auction house mail stuck on pending 

### ISSUE THREAD

**Issue by Velocipeder** [Atlantiss/NetherwingBugtracker#5467]
![Pending mail](https://user-images.githubusercontent.com/48891585/54884978-0a920e00-4eb2-11e9-83de-b2be347007bc.gif)

Description: 
Sales proceeding mails from the Auction House are getting stuck with the Status of Pending

Current behavior:
Most of the mails are under pending for more 1hrs. Some of the mails are older than 1 day.

Expected behaviour:
Sales proceeding from the Auction sales should have been processed and delivered.

**Comment by Tereneckla** [comment]
Fixed
