### ISSUE TITLE
[Core Mechanic]Mobs stack on top of player if the player is restricting arch with terrain(Walls, objects)

### ISSUE THREAD

**Issue by Tenoutoften** [Atlantiss/NetherwingBugtracker#5468]
**Description**: 
On Netherwing, most notably when tanking multiple mobs, they will stack on top of your character sometimes:
- One of the reasons this happens, looks to me, is that on NW there is a limit to how closely stacked mobs can be. If they are too closely stacked the mobs stack on top of the player, this leads to some interesting situations: 
_When tanking a lot of mobs, and the mobs start stacking on top of the player, whether the player is back paddling or not into a wall/corner a lot of mobs start hitting the player in the back. Some mobs have a knock ability, which will force the player to constantly re-position making sure the mobs aren't hitting him/her in the back._ 

Obviously it's not optimal having to re-position when fighting these kind of mobs, because: 
1) You might get knocked in your attempt at correcting their position.
2) It might be dangerous for other surrounding players(For examples if mobs have cleave)

- A mob should only re-positions if:
1) The player is outside of the mobs attack range.
2) It's too crowded in the arch, however this only applies if there is more room in the arch, if the arch is restricted by terrain the arch will be forced to stack more densely.

**Videos from retail**
- [Paladin in SM](https://youtu.be/EN7KfJ7ZKXc?t=350)  - I first thought mobs shouldn't ever move behind you, but at 06:02-06:08 you can see one mob re-positioning to be hitting the player in the back. However, no mobs stack on top of the player.
- [Paladin tanking ~40-50 mobs in SMV](https://youtu.be/Bo1Sw5YZako?t=230) no mobs stack on top of the paladin.
- [Paladin tanking in SM](https://youtu.be/2ESPg2zuFng?t=40) This video is interesting because it displays a large attack radius of the monks in SM, Perhaps mobs have increased range if they get too stacked, preventing them from going closer to the player?
- [Paladin tanking in SMV](https://youtu.be/KKKgBQbQIkE?t=38) Looks like the arch is restricted by terrain, mobs stack closer to one another.

**Current behaviour**:
When you tank multiple mobs, they will stack on top of you if you try to use terrain to restrict their arch which would otherwise, but not always if not enough mobs, go so far as to have mobs hitting you in the back.

[NW behavior example](https://www.youtube.com/watch?v=5EAPocRZIO0&feature=youtu.be)

Obviously not reporting this because it affects Scarlet Monastery, but because it affects tanks in almost all dungeons and raids, or anyone aoe farming as a tank in the world.

**Expected behaviour**:
Mobs ability to surround a player in an arch formation should be restricted by terrain, when restricted mobs should not run in to stand on the player(especially not behind the player).

**Server Revision**: 
![](https://i.gyazo.com/b03c797aa951bb507b471861ab46cc1a.png)

**Comment by Easyfraggy** [comment]
This seems to only happen when tanking in a corner - might be related to fanning wanting to spread them inside the wall. I noticed it also when tanking mobs in corners sometimes but don't even think you need more than 2 mobs to make it happen. I can maybe play around with testing it a bit on the weekend.

**Comment by Tenoutoften** [comment]
Yeah it will happen even with just a few mobs. I think you're correct that it has to do with mobs & terrain, but you don't have to stand in a corner for this to happen, I think just a regular wall will do

**Comment by Tenoutoften** [comment]
Reproduced with a regular wall:
https://www.youtube.com/watch?v=5r8qbdXiu9s&feature=youtu.be

This means that if you tank multiple mobs that knock you have to pick:
1) Either get knocked all over the place
2) Accept mobs hitting you in the back

**Comment by Tenoutoften** [comment]
@Easyfraggy Please tag this report up and make sure it gets looked upon, it affects so much...

**Comment by gabbat** [comment]
super annoying bug, espacially on gruul trash, tanked mobs move CONSTANTLY, super frustrating

**Comment by Easyfraggy** [comment]
Maybe just don't tank them inside the wall then? Theres 0 reason to do so.

**Comment by randomuser69** [comment]
To add to this, and maybe its just me, but mobs seem to not fan out wide enough. Like theres not enough space between them, they hardly fan out. Not sure if this is blizzlike, will have to do some research

**Comment by Tenoutoften** [comment]
@Easyfraggy The reason to tank mobs in this way is to avoid constantly having to back paddle. If this worker properly you could tank X amount of mobs, standing still, as long as you are in a corner, and never be concerned with a mob walking behind you and start hitting you in such a way all your avoidance goes to waste

**Comment by Godmatik** [comment]
Mob fanning was fixed last year.

Closing.
