### ISSUE TITLE
[Talent][Rogue] Cheat Death

### ISSUE THREAD

**Issue by szadini** [Atlantiss/NetherwingBugtracker#5469]
Description: The "Cheat Death" talent in sub is broken

Current behaviour: If you for example are at 1% hp and someone lands the killing blow on you, it proccs and sometimes blocks the damage completely, other times it never proccs because you are dead - basically it proccs after a duel has ended.

Expected behaviour: It is intended to put you at 10% hp on the killing blow, so if a single source of damage puts you from 15% to 0%, instead it should put you back up to 10% hp and then give damage reduction. Also it is not supposed to take damage before the talent proccs, like in a duel where the duel ends and cheat death proccs afterwards at 1 total hp. I tested this and things like frostbolt can just flat out kill you from 20% to 0% while the talent is off cooldown.

**Comment by Wolffenstein** [comment]
Can you record that happening? I can't reproduce it.

**Comment by The14me** [comment]
Way to reproduce
Make rogue with 3 points on Cheat Death
.go c 20728
If he cast Gushing Wound before u are death....Cheat Death proc and u are dead at the next tick.
