### ISSUE TITLE
Unable to buy "Pattern: Drums of Battle" - requires honored rep, which I have but for some reason it says that I don't have the required reputation.

### ISSUE THREAD

**Issue by Hansoloed** [Atlantiss/NetherwingBugtracker#5471]
[//]: # (Enclose links to things related to the bug using http://wowhead.com or any other TBC database.)
[//]: # (You can use screenshot ingame to visual the issue.)
[//]: # (Write your tickets according to the format:)
[//]: # ([Quest][Azuremyst Isle] Red Snapper - Very Tasty!)
[//]: # ([NPC] Magistrix Erona)
[//]: # ([Spell][Mage] Fireball)
[//]: # ([Npc][Drop] Ghostclaw Lynx)
[//]: # ([Web] Armory doesnt work)
[//]: # (To find server revision type `.server info` command in the game chat.)

**Description**: 

**Current behaviour**:

**Expected behaviour**: 

**Server Revision**:

**Comment by Tenoutoften** [comment]
Requires exalted, delete cache
![](https://i.gyazo.com/1a2ab88fbdb827c9365af2ea6a8d0c9d.png)

**Comment by Godmatik** [comment]
Yep, they didn't change the reputation requirement until a later patch in TBC, you have outdated cache from a future patch. close the client completely and delete the folder.
