### ISSUE TITLE
[Core Mechanic] DOT Breaking stealth with shield

### ISSUE THREAD

**Issue by BeastUnknown** [Atlantiss/NetherwingBugtracker#5472]
[//]: # (Enclose links to things related to the bug using http://wowhead.com or any other TBC database.)
[//]: # (You can use screenshot ingame to visual the issue.)
[//]: # (Write your tickets according to the format:)
[//]: # ([Quest][Azuremyst Isle] Red Snapper - Very Tasty!)
[//]: # ([NPC] Magistrix Erona)
[//]: # ([Spell][Mage] Fireball)
[//]: # ([Npc][Drop] Ghostclaw Lynx)
[//]: # ([Web] Armory doesnt work)
[//]: # (To find server revision type `.server info` command in the game chat.)

**Description**: 
[Core Mechanic] DOT Breaking stealth with shield
**Current behaviour**:
DOT on rogue > Shield > Stealth > Damage tick [absorb] > stealth break
**Expected behaviour**: 
DOT on rogue > Shield > Stealth > Damage tick [absorb] > stay in stealth
**Server Revision**:

**Comment by teddys** [comment]
that was changed in wotlk, it's supposed to be like that on tbc
