### ISSUE TITLE
[Talent][Shaman] Eye of the Storm

### ISSUE THREAD

**Issue by sguccimane** [Atlantiss/NetherwingBugtracker#5474]
Description: Eye of the storm shaman talent not working while sitting

Current behaviour:  if you /sit you will get crit, but the talent will not activate.

Expected behaviour: you are supposed to activate talent by /sit and getting crit. this has been THE way to lvl as ele since vanilla, and I cound't find any patch notes stating they changed that. Like, why would they add talents for reducing crit chance (elemental shields) if you are supposed to roll for a crit against enemies?

**Comment by Wolffenstein** [comment]
That mechanic has been removed in 2.3 if I remember correctly.

**Comment by sguccimane** [comment]
thanks for reply, sorry didn't know! 

blizz suuucks at making talents
