### ISSUE TITLE
Can't get the Tome of Valor

### ISSUE THREAD

**Issue by volundr1** [Atlantiss/NetherwingBugtracker#5475]
[//]: # (Enclose links to things related to the bug using http://wowhead.com or any other TBC database.)
[//]: # (You can use screenshot ingame to visual the issue.)
[//]: # (Write your tickets according to the format:)
[//]: # ([Quest][Azuremyst Isle] Red Snapper - Very Tasty!)
[//]: # ([NPC] Magistrix Erona)
[//]: # ([Spell][Mage] Fireball)
[//]: # ([Npc][Drop] Ghostclaw Lynx)
[//]: # ([Web] Armory doesnt work)
[//]: # (To find server revision type `.server info` command in the game chat.)

**Description**: 
I can't get the Tome of Valor. Not sure if I deleted it thinking I could pick it up again later or what. Anyway I could get this item restored?

**Current behaviour**:
Duthorian Rall doesn't have a quest offering me the Tome of Valor.

**Expected behaviour**: 
Duthorian Rall should offer me a quest for Tome of Valor.

**Server Revision**: 
2898

**Comment by Evolvee** [comment]
contact GMs

**Comment by volundr1** [comment]
I contacted the GMs. They said they can't restore it. Is there any other way to get this restored?

**Comment by Evolvee** [comment]
pm me on discord
