### ISSUE TITLE
[spell][priest] Shadow resistance is bugged

### ISSUE THREAD

**Issue by Lockanloads** [Atlantiss/NetherwingBugtracker#5476]
**Description**: 
Priest buff Shadow Resistance makes player resist shadow spells even if they have 80 Spell penetration (to counter UD racial) and 4% hit
**Current behaviour**:
Priest buff Shadow Resistance makes player resist shadow spells even if they have 80 Spell penetration (to counter UD racial)  and 4% hit shadow spells  still totally resist between 10-20% of the times.
Dont know about other magic schools but there is a [Core] post from Easyfraggy 1 month old still no fix
https://github.com/Atlantiss/NetherwingBugtracker/issues/5171
**Expected behaviour**: 
Shadow resistance should be reduced to 0 and players should have only 1% chance to resist
**Server Revision**:

**Comment by Wolffenstein** [comment]
Which spells did you test? Are you sure the player did not have any additional shadow res?

**Comment by Lockanloads** [comment]
Mostly dots, gear, drains. I will test it later and post how many resists i get on 1000 casts (should be 10 as expected behaviour)
This bug is récurrent Shadow and shadow resist gear is bot something most players have.

**Comment by Lockanloads** [comment]
After testing, its actually working properly. Closing
