### ISSUE TITLE
stones That bind us

### ISSUE THREAD

**Issue by yeahbunny2** [Atlantiss/NetherwingBugtracker#5477]
[//]: # (Enclose links to things related to the bug using http://wowhead.com or any other TBC database.)
[//]: # (You can use screenshot ingame to visual the issue.)
[//]: # (Write your tickets according to the format:)
[//]: # ([Quest][Azuremyst Isle] Red Snapper - Very Tasty!)
[//]: # ([NPC] Magistrix Erona)
[//]: # ([Spell][Mage] Fireball)
[//]: # ([Npc][Drop] Ghostclaw Lynx)
[//]: # ([Web] Armory doesnt work)
[//]: # (To find server revision type `.server info` command in the game chat.)

**Description**: 

**Current behaviour**:

**Expected behaviour**: 

**Server Revision**:

**Comment by yeahbunny2** [comment]
u cant click stones for destory them. and mobs are immortal. please fix it. its important chain for me ...

**Comment by yeahbunny2** [comment]
idk should i report it. its a Azeroth quest in Blasted Land called " The Stones What Bind us" u have to slain servants, for do that u need to destroy a stone fst. Here u cant use the stone for destroy it.

**Comment by teddys** [comment]
Have you tried getting the mob low first, then clicking the totem and then killing the mob?

**Comment by yeahbunny2** [comment]
yea i tried still cant use shard

**Comment by Evolvee** [comment]
u need to kite the mob to the shard and THEN get it to low hp

**Comment by Evolvee** [comment]
works fine for me so... unless you provide some proof like a video im gonna close this.
