### ISSUE TITLE
[Item] [spell}The Lightning Capacitor + Arcane Missiles

### ISSUE THREAD

**Issue by knasen88** [Atlantiss/NetherwingBugtracker#5478]
[//]: # (Enclose links to things related to the bug using http://wowhead.com or any other TBC database.)
[//]: # (You can use screenshot ingame to visual the issue.)
[//]: # (Write your tickets according to the format:)
[//]: # ([Quest][Azuremyst Isle] Red Snapper - Very Tasty!)
[//]: # ([NPC] Magistrix Erona)
[//]: # ([Spell][Mage] Fireball)
[//]: # ([Npc][Drop] Ghostclaw Lynx)
[//]: # ([Web] Armory doesnt work)
[//]: # (To find server revision type `.server info` command in the game chat.)

**Description**: 
Currently the lightning cap trinket does not gain charge if your first arcane missile hit doesn't crit  you won't get a charge
**Current behaviour**:
Only gives charge if initial hit crits, also does not give 2 charges for example if first and last tick crits (more than 2.5 sec between)
**Expected behaviour**: 
critical hit = capacitator charge.
**Server Revision**: 
2907

**Comment by Godmatik** [comment]
Rev 4015 no longer an issue.

Individual missiles are granting charges if they critical strike.
