### ISSUE TITLE
[Item][Vendor][Recipe] Missing [Plans: Lesser Ward of Shielding] at vendor

### ISSUE THREAD

**Issue by veekk** [Atlantiss/NetherwingBugtracker#5479]
**Description**: 
<img width="351" alt="image" src="https://user-images.githubusercontent.com/12899687/55043469-1bbc5580-503f-11e9-9dd5-9ed2d2e324f8.png">
Recipe is missing at vendor, but it was added at 2.0.1 [wowhead](https://www.wowhead.com/item=23638/plans-lesser-ward-of-shielding)

**Current behaviour**: item missing

**Expected behaviour**:  should be available

**Server Revision**: 2908

**Comment by teddys** [comment]
it's a limited supply recipe ... if the vendor doesn't sell it then it's currently waiting for its respawn
