### ISSUE TITLE
Aggrorange to big

### ISSUE THREAD

**Issue by padomu** [Atlantiss/NetherwingBugtracker#548]
[//]: # (Enclose links to things related to the bug using http://wowhead.com or any other TBC database.)
[//]: # (You can use screenshot ingame to visual the issue.)
[//]: # (Write your tickets according to the format:)
[//]: # ([Quest][Azuremyst Isle] Red Snapper - Very Tasty!)
[//]: # ([NPC] Magistrix Erona)
[//]: # ([Spell][Mage] Fireball)
[//]: # ([Npc][Drop] Ghostclaw Lynx)
[//]: # ([Web] Armory doesnt work)

**Description**: 
So in the rogue quest (horde) I think the patrolling Venture Co- Drone's have a too big aggro range.

**Current behaviour**:
If you are in the tower on the lowest level and fight the 25lvl mobs, you can get aggro from the Venture Co Drone form outside

**Expected behaviour**: 
If I am in the tower, I don't expect to get aggro from the outside mob.

**Server Revision**: 
2050

**Comment by Tereneckla** [comment]
Fixed, they only come to help if they have LoS
