### ISSUE TITLE
[Enchant Gloves - Major Healing] 

### ISSUE THREAD

**Issue by PriestTankIsViable** [Atlantiss/NetherwingBugtracker#5480]
[//]: # (Enclose links to things related to the bug using http://wowhead.com or any other TBC database.)
[//]: # (You can use screenshot ingame to visual the issue.)
[//]: # (Write your tickets according to the format:)
[//]: # ([Quest][Azuremyst Isle] Red Snapper - Very Tasty!)
[//]: # ([NPC] Magistrix Erona)
[//]: # ([Spell][Mage] Fireball)
[//]: # ([Npc][Drop] Ghostclaw Lynx)
[//]: # ([Web] Armory doesnt work)
[//]: # (To find server revision type `.server info` command in the game chat.)

**Description**: 
My priest (ingame Trischtan) lost the Major Healing enchant on gloves (Prismatic Mittens of Mending). The enchant was first shown in white letters (like it was part of the attributes) and finally disappeared.

**Current behaviour**:
Enchant disappeared.

**Expected behaviour**: 
Enchant should be shown in green letters in the tool tip.

**Server Revision**: 
2908

**Comment by Tenoutoften** [comment]
Never had this happened, any additional information on what caused it?

**Comment by PriestTankIsViable** [comment]
No idea. When I logged off the day before, I still had the enchant (white letters though). I also tried to enchant the gloves again to check, if it is only a visual bug but it's definitely not.

**Comment by EnterLarry** [comment]
Not sure why it disapeared unless you equipped another pair and forgot to switch back again.
The reason it's in white text is most likely due to the 2.0 tooltip fix addon.

**Comment by Manaci** [comment]
Not a bug, delete addon next
