### ISSUE TITLE
PvP - Pets - 5% pvp hit not working when attacking pets

### ISSUE THREAD

**Issue by zmthc93** [Atlantiss/NetherwingBugtracker#5482]
[//]: # (Enclose links to things related to the bug using http://wowhead.com or any other TBC database.)
[//]: # (You can use screenshot ingame to visual the issue.)
[//]: # (Write your tickets according to the format:)
[//]: # ([Quest][Azuremyst Isle] Red Snapper - Very Tasty!)
[//]: # ([NPC] Magistrix Erona)
[//]: # ([Spell][Mage] Fireball)
[//]: # ([Npc][Drop] Ghostclaw Lynx)
[//]: # ([Web] Armory doesnt work)
[//]: # (To find server revision type `.server info` command in the game chat.)

**Description**: 
5% hit cap for PvP is not applying to players pets - resulting in a very high number of dodges, misses, parries etc on pets which make them harder than they should be to kill. Shouldn't have to be stacking 10%+ hit gear when facing a warlock/hunter + healer team jst to kill pet consistently. From memory and previous servers, pets were a lot more fragile to melee dps, with warlocks having to summon a voidwalker instead of felhunter etc when facing melee (not the case here). Reference from old arena junkies thread: http://www.arenajunkies.com/topic/19876-here-we-go-again-on-pet-scaling/

**Current behaviour**:
5% PvP hit cap not applying to players pets (classed as NPC or smth)

**Expected behaviour**: 
PvP hit cap should be in line with players + pets

**Server Revision**:

**Comment by teddys** [comment]
hit doesn't have anything to do with dodges and parries
what happened to you was probably the voidwalker ability suffering that gives you -%hit

I've never missed a single attack vs any pet in 80+- games (5% hit rating)

**Comment by zmthc93** [comment]
yeah sorry i should have been clearer
the dodges and parries are happening from behind
the misses from hit cap are seperate issue

**Comment by Evolvee** [comment]
LF confirmation if this is still valid
