### ISSUE TITLE
chain lightning hitting the same target twice

### ISSUE THREAD

**Issue by froggenpoppin** [Atlantiss/NetherwingBugtracker#5484]
https://db.excalibur.ws/?spell=25442
https://i.imgur.com/HZIA4Gj.png
(chain lightning[shaman]

**description**
chain lightning is bouncing to the same target more than once 
**Current behaviour**:
chain lightning is hitting the same target more than once

**Expected behaviour**: 
should only hit each target max 1 time
**Server Revision**:

**Comment by froggenpoppin** [comment]
https://youtu.be/5Sv1FV0X8M8?t=218 proof from tbc

**Comment by froggenpoppin** [comment]
https://youtu.be/MJziNPa95JM?t=357 proof #2

**Comment by Wolffenstein** [comment]
Isn't it because of Lightning Overload?

**Comment by froggenpoppin** [comment]
https://db.excalibur.ws/?talent#h the talent states it does half damage

**Comment by Godmatik** [comment]
?? 
Can't reproduce this at all, maybe fixed at some point?
Was able to get lightning overload proc which deals half damage, but that is it.
