### ISSUE TITLE
[Core] All spell partial resist damage reduction is too low.

### ISSUE THREAD

**Issue by Easyfraggy** [Atlantiss/NetherwingBugtracker#5485]
**Description**: 
Spell resistance is divided in partial (non binary) resist and binary resist spells.

**Current behaviour**:
Non binary resists atm are calculated as 20/40/60% reduced damage.

**Expected behaviour**: 
Non binary resists should be calculated as 25/50/75% reduced damage.

**Server Revision**: 2908

**Comment by Azalen** [comment]
This explains our problems with Hydross this ID.

**Comment by Easyfraggy** [comment]
I did not test it on damage done to players - only on players vs bosses - I'll see if I can find time to confirm.

**Comment by Evolvee** [comment]
@Wolffenstein

**Comment by Wolffenstein** [comment]
Fixed in rev 3021.

**Comment by Evolvee** [comment]
yikers
