### ISSUE TITLE
Tome of divinity Narm Faulk bug

### ISSUE THREAD

**Issue by gimlinn** [Atlantiss/NetherwingBugtracker#5486]
[//]: # (Enclose links to things related to the bug using http://wowhead.com or any other TBC database.)
[//]: # (You can use screenshot ingame to visual the issue.)
[//]: # (Write your tickets according to the format:)
[//]: # ([Quest][Azuremyst Isle] Red Snapper - Very Tasty!)
[//]: # ([NPC] Magistrix Erona)
[//]: # ([Spell][Mage] Fireball)
[//]: # ([Npc][Drop] Ghostclaw Lynx)
[//]: # ([Web] Armory doesnt work)
[//]: # (To find server revision type `.server info` command in the game chat.)

"While in the midst of completing the paladin quest line for the Tome of Divinity, I used the Symbol of Life on Narm Faulk but he died again before I could accept next quest in the chain. I cannot abandon the quest (stuck between two quests in chain), or go to quest giver to get a new Symbol of Life. I fear that if I cannot complete this quest, my pally will not be able to resurrect. Apparently this could be an issue during TBC, but I can find no apparent fix when searching online." quote from a thread on the forums for the exact issue I am having

**Current behaviour**:
Narm faulk dies within seconds of using the symbol of life on him
**Expected behaviour**: 
Narm stays alive so the player can read the quest text and accept the quest.
**Server Revision**:

**Comment by Endiae** [comment]
same issue

**Comment by danbopes** [comment]
rev 3249
