### ISSUE TITLE
[Hunter] [Wyvern Sting] Does not DR with Freezing Trap.

### ISSUE THREAD

**Issue by gunzbngbng** [Atlantiss/NetherwingBugtracker#5488]
[//]: # (Enclose links to things related to the bug using http://wowhead.com or any other TBC database.)
[//]: # (You can use screenshot ingame to visual the issue.)
[//]: # (Write your tickets according to the format:)
[//]: # ([Quest][Azuremyst Isle] Red Snapper - Very Tasty!)
[//]: # ([NPC] Magistrix Erona)
[//]: # ([Spell][Mage] Fireball)
[//]: # ([Npc][Drop] Ghostclaw Lynx)
[//]: # ([Web] Armory doesnt work)
[//]: # (To find server revision type `.server info` command in the game chat.)

**Description**: TBC has a list of diminishing returns here.  https://wowwiki.fandom.com/wiki/Diminishing_returns
Freezing Trap and Wyvern Sting are both incapacitates.

**Current behaviour**:  Wyvern Sting is not sharing DR's with Freezing trap.

**Expected behaviour**: Wyvern Sting should share DR's with Freezing trap.

**Server Revision**: 2909

**Comment by Tenoutoften** [comment]
Using the website you provided, and going back to the version from 2008 nov it claims you are wrong, Freezing Trap doesn't have  DR category, but Wyvern Sting shares with Sleep
https://wowwiki.fandom.com/wiki/Diminishing_returns?oldid=1663771
![](https://i.gyazo.com/f9d7486d31ae8427187eafed9ab4ba50.png)

**Comment by teddys** [comment]
lul

**Comment by gunzbngbng** [comment]
That list is incomplete and Wyvern Sting is listed as "TBD".  Whoever wrote that did not test WS.

https://www.wowhead.com/forums&topic=14930

"By Thunderhoof on 2008/03/04 at 5:13 AM (Patch 2.3.3)

I like it in PvP. 10 Sec sleep are very usefull to run away, bandage and then use a Aimed Shot. Also if a mob is hitting the healer i give my tank 12 seconds to taunt the mob. (Healers will love yaa) 

Im happy with it, in PvP it will often save your ass. For raiding its useless btw :(

back to topic:
Yes it has dimishing return, and it shares with the icetrap (trust me, bad arena experiense in 2.2 maybe changed)
You can do it on Mutiple enemys, but 2 Min CD....
Last edited by Thunderhoof on 2008/03/04 – edited 2 times"

https://forum.twinstar.cz/threads/big-theorycrafting-thread.57011/
"Diminishing returns affect any kind of CC ability, even short-time stuns and disables. Each ability is sorted into a category, inside which the diminishing returns are applied. The categories are as follows:

Root - Frost Nova, Entangling Roots, Nature's Grasp, Frost Shock (exception) and other root effects (Gnomish Net-o-Matic).
Stun - Bash, Concussion Blow, Charge, Inferno, Hammer of Justice, Intercept, Intimidation, Kidney Shot, War Stomp and other active stun effects (Tidal Charm).
Opener Stun - Cheap Shot, Pounce
Random Stun - Blackout, Impact, Improved Starfire, Improved Concussive Shot, Mace Spec, Pyroclasm, Improved Revenge, Seal of Justice and other effects from Chance on Hit: Stun.
Disarm - Disarm, Riposte
Incapacitate - Gouge, Repentance, Sap
Sleep/Disorient - Freezing Trap, Hibernate, Polymorph, Wyvern Sting, Blind, Scatter Shot and other Sleep or Disorient effects (Magic Dust).
Fear - Fear, Howl of Terror, Psychic Scream, Intimidating Shout, Scare Beast, Seduction (exception) and other fear effects (Warlock setbonus)
Horror - Death Coil"

http://www.arenajunkies.com/topic/24092-shared-drs/
"Posted 11 June 2008 - 04:39 PM
"Wyvvern and traps share cds, 
Imo every class should have their onw DC, for example, trap and wyvvern/entrapment and winclip proc etc "

That was a cursory google.  Pretty sure it's going to be easy to find tons of references.

**Comment by zmthc93** [comment]
you could be right about 2.0, but pretty sure it didnt share DR in 2.4.3 (played a lot in s3 s4 live and AT 2.4.3 server)
if we changing stuff back to 2.0 mechanics might as well make an issue that blind isn't a poison either

**Comment by gunzbngbng** [comment]
Both ares and gummys servers have dr'd freezing trap with wyvern.  I know in retail it was dr'd and have found documentation in 2.3 that it was indeed on dr.

I'm not citing 2.0 mechanics.

**Comment by Tenoutoften** [comment]
https://wow.gamepedia.com/Freezing_Trap
Patch 1.7.0 (2005-09-22): Freezing Trap now shares the same duration in pvp as other long-duration forms of crowd control (ie: polymorph, fear, sap).

**Comment by Evolvee** [comment]
ares is stock mangos and similar goes for gummys so, need a better evidence

**Comment by gunzbngbng** [comment]
> https://wow.gamepedia.com/Freezing_Trap
> Patch 1.7.0 (2005-09-22): Freezing Trap now shares the same duration in pvp as other long-duration forms of crowd control (ie: polymorph, fear, sap).

And I do not believe that was every changed throughout tbc.

**Comment by Evolvee** [comment]
the patch note has nothing to do with DR, its just reduced base time of CC

**Comment by gunzbngbng** [comment]
> the patch note has nothing to do with DR, its just reduced base time of CC

My mistake.  I'll keep looking for video documentation.

**Comment by Evolvee** [comment]
reopen when you fine some info
