### ISSUE TITLE
[Item] [Spell] [Shaman] Totem of Impact and shock damage

### ISSUE THREAD

**Issue by Kogud** [Atlantiss/NetherwingBugtracker#5489]
**Description**:  Totem of Impact (id: 27984, http://db.excalibur.ws/?item=27984) is not adding damage to the appropriate shocks.

**Current behaviour**: Currently, shocks do not gain any extra damage from having this relic equipped. Having this relic equipped adds no benefit.

**Expected behaviour**: With the relic/totem equipped, each of Flame Shock / Earth Shock / Frost Shock should gain up to an additional +46 damage. 

**Server Revision**:  http://puu.sh/D6iah.jpg

I have not been able to find data to determine whether the +46 buff is a straight buff of exactly 46 damage every time, or if the +46 factors in the spell damage coefficients for each spell. Either way, any sort of change to this totem will be an improvement over the current situation.

However:
Earth Shock has a .42 spell damage coefficient (.42 x 46 = 19.32 bonus damage); Flame Shock has a .67 spell damage coefficient: 15% up front, 52% DoT ([.15 x 46 + .52 x 46] = 30.82 bonus damage). Sourced from https://web.archive.org/web/20080811071236/http://elitistjerks.com/f47/t20765-shaman_enhancement/#Elemental_Shocks , section 1.1.4. I don't know the coefficient on frost shock.

**Comment by Wolffenstein** [comment]
Fixed in rev 2917.
