### ISSUE TITLE
[NPC] Baron Longshore pathing

### ISSUE THREAD

**Issue by Kidcudi123** [Atlantiss/NetherwingBugtracker#549]
When he's located at the top camp up on the mountain, he can run through the wall if you pull from that direction.

**Comment by The14me** [comment]
https://github.com/Atlantiss/NetherwingBugtracker/issues/479

**Comment by The14me** [comment]
@Kidcudi123  Sorry for closing the report,was pure miss read by me.

**Comment by Tereneckla** [comment]
Fixed
