### ISSUE TITLE
[NPC] Vazario Linkgrease <Goblin Engineering Trainer> is also offering Gnomish Engineering Schematics

### ISSUE THREAD

**Issue by Kolmarwow** [Atlantiss/NetherwingBugtracker#5490]
**Description**: 
The Goblin Engineering Trainer "Vazario Linkgrease" located in Gazlowe's hut in Ratchet offers all goblin & gnomish engineering schematics that existed in vanilla.
https://i.imgur.com/X8qcOce.png

**Current behaviour**:
Offers both gnomish & goblin engineering schematics.

**Expected behaviour**: 
Assume that he should only offer goblin engineering schematics.

**Server Revision**: 
2909

**Comment by Evolvee** [comment]
rev 2929
