### ISSUE TITLE
[MOB][SPELL] Curse of Mending from Witchwing Harpy

### ISSUE THREAD

**Issue by Godmatik** [Atlantiss/NetherwingBugtracker#5491]
**Description**: 
Witchwing Harpy casts "Curse of Mending", lasts for 3 minutes, 20% chance to heal enemy target on hit.

**Current behaviour**:
Doesn't seem to work, had the curse on me multiple times, never once proceed for any of my melee hits.

**Expected behaviour**: 
Should proc as intended and heal the enemy.

**Server Revision**: 
2909

**Comment by Wolffenstein** [comment]
![image](https://user-images.githubusercontent.com/1576644/55284487-09f8ec00-5378-11e9-80cb-f3edfe629186.png)
Works fine for me.
