### ISSUE TITLE
Area 52/Netherstorm Crashing Issue

### ISSUE THREAD

**Issue by GonzalesPants** [Atlantiss/NetherwingBugtracker#5492]
Currently experiencing intermittent hard crashing in Netherstorm in the close proximity of Area 52, 

The client freezes for a few seconds until user attempts to interact with the .exe before immediately closing. I have cleared cache and the issue was not fixed. This results in immediate player death if player is in combat regardless of if their target was dying or if they were at full health.

Server revision: 2909

**Comment by Evolvee** [comment]
try to download different client or screenshot where exactly it happens
