### ISSUE TITLE
[Spell][Mage] Frost Nova/Freeze/Frostbite DR

### ISSUE THREAD

**Issue by bajkorv** [Atlantiss/NetherwingBugtracker#5493]
[//]: # (Enclose links to things related to the bug using http://wowhead.com or any other TBC database.)
[//]: # (You can use screenshot ingame to visual the issue.)
[//]: # (Write your tickets according to the format:)
[//]: # ([Quest][Azuremyst Isle] Red Snapper - Very Tasty!)
[//]: # ([NPC] Magistrix Erona)
[//]: # ([Spell][Mage] Fireball)
[//]: # ([Npc][Drop] Ghostclaw Lynx)
[//]: # ([Web] Armory doesnt work)
[//]: # (To find server revision type `.server info` command in the game chat.)

**Description**: feels like there is definately something wrong with frost Nova/frostbite/Pet freeze DR

**Current behaviour**:
Dont have the means to test but i was just frost Nova 8 seconds into 8 seconds Pet Nova multiple times in arena

**Expected behaviour**: Not completely sure about this but I think all roots Should share DR with Freeze/Frost Nova and that perhaps Frostbite has its own DR, not sure though.

In clips:
https://youtu.be/evY1Q9KdXfM?t=1m49s
https://youtu.be/dxQvIEVPOO8?t=2m28s
It looks like all 3 are affected by DR in some way or another
**Server Revision**: 2905

**Comment by bajkorv** [comment]
Looks like in the first clip that frost Nova doesnt share DR with Frostbite but pet freeze definately share DR with one of them

**Comment by liderer** [comment]
its replacing buff mechanic (not active here) , only stronger spell can be active.... 
www.github.com/Atlantiss/NetherwingBugtracker/issues/5000

**Comment by bajkorv** [comment]
From the same page as u linked:
”In PvP, the Frostbite effect is subject to diminishing returns.”
And
”The Frostbite effect does not overwrite the Frost Nova effect or the Water Elemental's Freeze effect. These spells have a longer duration (8 seconds vs. 5 seconds) than Frostbite, and thus supersede it. Even if the Frost Nova or Freeze has fewer than 5 seconds remaining, Frostbite will not take effect.”

Seems like they do share DR but Frostbite shouldnt be able to procc when you are in Nova/Freeze.

**Comment by bajkorv** [comment]
Found this
The Burning Crusade Patch 2.1.0 (2007-05-22):
 [Frostbite] effect is now subject to diminishing returns in PvP.

**Comment by bajkorv** [comment]
Looking at https://www.youtube.com/watch?v=QyTyNaiEJKs&feature=youtu.be&t=57 one can see that pet freeze and frost nova defo share DR, however, Frostbite does not with them, it has its own DR then.

Controlled root:
Frost Nova
Pet Nova

Uncontrolled root:
Frostbite
for example Entrapment [hunter survival talent]

**Comment by gunzbngbng** [comment]
> Looking at https://www.youtube.com/watch?v=QyTyNaiEJKs&feature=youtu.be&t=57 one can see that pet freeze and frost nova defo share DR, however, Frostbite does not with them, it has its own DR then.
> 
> Controlled root:
> Frost Nova
> Pet Nova
> 
> Uncontrolled root:
> Frostbite
> for example Entrapment [hunter survival talent]

Which, until recently, was also DRing with entangling roots.  So the DR tables are a little wonky atm.
