### ISSUE TITLE
[Spell][Rogue][Hunter] Cloak of Shadows should not provide immunity to Flare

### ISSUE THREAD

**Issue by ronyc** [Atlantiss/NetherwingBugtracker#5494]
**Description**:  Flare doesn't work on Cloak of Shadows.

**Current behaviour**:  Cloak of Shadows provides immunity to the Flare debuff.

**Expected behaviour**:  Cloak of Shadows should not provide immunity to Flare.

**Server Revision**:  2909

**Comment by liderer** [comment]
https://wowwiki.fandom.com/wiki/Cloak_of_Shadows?oldid=1431899 

"Does not provide the rogue immunity to a Hunter's flare ability."

**Comment by Wolffenstein** [comment]
Fixed in rev 2918.
