### ISSUE TITLE
[Hunter][Pet] Pet level has decrese

### ISSUE THREAD

**Issue by kubawww7** [Atlantiss/NetherwingBugtracker#5495]
**Description**: being on Karazhan and after summ I got 3 crash, I cleaned the Cashe file and logged in after that I noticed that my pet has level 30 and it had level 69 (Wind Serpent from Netherstorm). I must now tame new pet.

**Comment by Godmatik** [comment]
Yes other hunters have been mentioning this, they are aware.

For now, I would recommend putting that pet in stable and getting a new one, might be a while until it is fixed.

**Comment by Evolvee** [comment]
should be fixed in rev 2912 according to changelog
