### ISSUE TITLE
[Hunter] [Entrapment] Is causing DR on Entangling Roots.

### ISSUE THREAD

**Issue by gunzbngbng** [Atlantiss/NetherwingBugtracker#5496]
[//]: # (Enclose links to things related to the bug using http://wowhead.com or any other TBC database.)
[//]: # (You can use screenshot ingame to visual the issue.)
[//]: # (Write your tickets according to the format:)
[//]: # ([Quest][Azuremyst Isle] Red Snapper - Very Tasty!)
[//]: # ([NPC] Magistrix Erona)
[//]: # ([Spell][Mage] Fireball)
[//]: # ([Npc][Drop] Ghostclaw Lynx)
[//]: # ([Web] Armory doesnt work)
[//]: # (To find server revision type `.server info` command in the game chat.)

**Description**: Entrapment is a talent that procs a 4 second immobilize.  In TBC, proccing CC does not cause DR with targetted CC.  Mace stuns do not cause other stuns to DR, Frostbite does not cause frost nova to DR.  The same goes for Entrapment.

**Current behaviour**:  Entrapment is causing Entangling roots (and probably other targeted roots) to DR.

**Expected behaviour**: Entrapment should DR against itself and only itself.

**Server Revision**: 2909

**Comment by Zarant** [comment]
https://youtu.be/FAz6E6W4T-I?t=287 At 4:48 the warrior gets affected by entrapment, at 4:51 he gets rooted and at 4:59 entangling roots ends and the warrior intercepts the hunter. So, yeah, i'm pretty sure it should be on a separate DR.

**Comment by Wolffenstein** [comment]
Fixed in rev 2916.
