### ISSUE TITLE
[Item] Honor's call

### ISSUE THREAD

**Issue by Bravehurt** [Atlantiss/NetherwingBugtracker#5497]
[//]: # (Enclose links to things related to the bug using http://wowhead.com or any other TBC database.)
[//]: # (You can use screenshot ingame to visual the issue.)
[//]: # (Write your tickets according to the format:)
[//]: # ([Quest][Azuremyst Isle] Red Snapper - Very Tasty!)
[//]: # ([NPC] Magistrix Erona)
[//]: # ([Spell][Mage] Fireball)
[//]: # ([Npc][Drop] Ghostclaw Lynx)
[//]: # ([Web] Armory doesnt work)
[//]: # (To find server revision type `.server info` command in the game chat.)

**Description**: Seems like the epic sword which has higher flat damage (both min and max) ends up with a lower minimum than the compared one (which is lower on both)
![Wow 2019-03-28 17-40-05](https://user-images.githubusercontent.com/46060170/55194630-ab1d5200-5180-11e9-8da2-4161d8ab8ff0.jpg)
![Wow 2019-03-28 17-39-50](https://user-images.githubusercontent.com/46060170/55194632-ac4e7f00-5180-11e9-9398-cf9ba471cdfc.jpg)

**Current behaviour**: flat damage on weapon seems incorrect

**Expected behaviour**: higher flat min and max damage should end up in higher min max damage than your previous lower damage sword

**Server Revision**: 2909

WILL UPDATE WITH PICTURE SHORTLY

**Comment by Evolvee** [comment]
did you try to measure the damage on recount? or is this just a visual bug

**Comment by Bravehurt** [comment]
yea i tried on a couple different, the gators around shatt with the blue lowest i manage to get was 178, with honors call lowest was 170 so its not just visual

**Comment by Bravehurt** [comment]
its even worse in battle stance
![Wow 2019-03-29 05-55-50](https://user-images.githubusercontent.com/46060170/55224719-81e3dc80-51e7-11e9-9f7a-de4597516d24.jpg)
![Wow 2019-03-29 05-55-38](https://user-images.githubusercontent.com/46060170/55224723-83ada000-51e7-11e9-920c-d1177fcebffc.jpg)
