### ISSUE TITLE
[Loot] Durotar boars drop Crag Boar Rib

### ISSUE THREAD

**Issue by Jezofine** [Atlantiss/NetherwingBugtracker#55]
http://db.hellfire-tbc.com/?item=2886
https://www.wowhead.com/item=2886
Should be dropped by different Crag Boars.

**Comment by Wolffenstein** [comment]
Any non-priv database source?

**Comment by Jezofine** [comment]
Added link to wowhead, but it's post Cata.

**Comment by aresbrutus** [comment]
https://i.imgur.com/bLvdN86.png

**Comment by lynxzor** [comment]
Had this drop also

**Comment by Shanghi** [comment]
I just noticed this but it was fixed in 2152.
