### ISSUE TITLE
[NPC] Sunscale Scytheclaw damage

### ISSUE THREAD

**Issue by Kidcudi123** [Atlantiss/NetherwingBugtracker#550]
This (specific?) raptor's hitting double time on every hit

https://gyazo.com/efb88c0d4b592b3aa0a0b3600e6225d3

My combat log says so aswell 

https://gyazo.com/1e94d3dcab01dcb839147644f9a48fa1

**Comment by Kidcudi123** [comment]
Ok checked the spawn right beside it, it does the same insane damage lol

**Comment by The14me** [comment]
blizzlike,just bad RNG with ''trash''

**Comment by Kidcudi123** [comment]
Cool
