### ISSUE TITLE
[Hunter] [Pet]  It's possible to enter arena with a prebuffed pet.

### ISSUE THREAD

**Issue by gunzbngbng** [Atlantiss/NetherwingBugtracker#5501]
[//]: # (Enclose links to things related to the bug using http://wowhead.com or any other TBC database.)
[//]: # (You can use screenshot ingame to visual the issue.)
[//]: # (Write your tickets according to the format:)
[//]: # ([Quest][Azuremyst Isle] Red Snapper - Very Tasty!)
[//]: # ([NPC] Magistrix Erona)
[//]: # ([Spell][Mage] Fireball)
[//]: # ([Npc][Drop] Ghostclaw Lynx)
[//]: # ([Web] Armory doesnt work)
[//]: # (To find server revision type `.server info` command in the game chat.)

**Description**: [Hunter] [Pet]  It's possible to enter arena with a prebuffed pet.

**Current behaviour**: If you buff a pet with might, kings, etc and mount, the pet will have buffs when you enter arena.

**Expected behaviour**: Pets should have all buffs and debuffs removed upon entering arena.

**Server Revision**: .2909

**Comment by Wolffenstein** [comment]
Fixed.
