### ISSUE TITLE
[NPC] Janice Felstone - Missing RP

### ISSUE THREAD

**Issue by Zarant** [Atlantiss/NetherwingBugtracker#5502]
NPC Janice Felstone should periodically scream for help

Source:

> Janice Felstone was a human ghost located at the Felstone Field farm in the contested territory of the Western Plaguelands. She would occasionally scream out for help.

https://wow.gamepedia.com/Janice_Felstone

You can also see the described behavior from Joana's speedrun from patch 1.10: https://youtu.be/jKPDoC8EraY?t=307

**Comment by Evolvee** [comment]
rev 2911
