### ISSUE TITLE
[NPC][Sell Price]Pendant of Triumph and Dominance cost too much honor.

### ISSUE THREAD

**Issue by bajkorv** [Atlantiss/NetherwingBugtracker#5503]
[//]: # (Enclose links to things related to the bug using http://wowhead.com or any other TBC database.)
[//]: # (You can use screenshot ingame to visual the issue.)
[//]: # (Write your tickets according to the format:)
[//]: # ([Quest][Azuremyst Isle] Red Snapper - Very Tasty!)
[//]: # ([NPC] Magistrix Erona)
[//]: # ([Spell][Mage] Fireball)
[//]: # ([Npc][Drop] Ghostclaw Lynx)
[//]: # ([Web] Armory doesnt work)
[//]: # (To find server revision type `.server info` command in the game chat.)

**Description**: Currently the Pendant of Triumph and Dominance cost too much honor in comparison to other items. Every item looks like honor cost has been reduced, except for necklaces which looks like theyve increased in pricing for some reason?

**Current behaviour**: Necklace costs 2.5x any other part atm, at 22950 honor

**Expected behaviour**: Necklace should cost somewhere around 15300 honor, High Warlord weapons (70) even cost 15300 atm

**Server Revision**: 2909

**Comment by Zarant** [comment]
http://web.archive.org/web/20070518141436/http://www.thottbot.com/i28245 (18 May 2007 - patch 2.1) 22500 honor

http://web.archive.org/web/20070709112030/http://www.thottbot.com/i28245  (9 July 2007 - Patch 2.1.2) 15300 honor

The pvp necklace honor cost got changed after the BT patch.

**Comment by Manaci** [comment]
The thing this all leads to is that EVERY other item than the PvP Necklace is using the Patch 2.1.2 price point.

**Comment by Evolvee** [comment]
if the price is incorrect on other items, report them

**Comment by bajkorv** [comment]
22950 is wrong price still, even if 2.1 is 22500 it is still 450 points wrong, and if this item has ”almost correct” price, all other pvp items have completely wrong price.


All pvp items for sale are using 2.1.2 prices, except for necklace which uses a number someone pulled from their asshole
