### ISSUE TITLE
(Quest) Malins Request - Cannot turn in quest at Skuerto

### ISSUE THREAD

**Issue by EmerisEB** [Atlantiss/NetherwingBugtracker#5506]
**Description**: 

The quest Malins Request, requires you to travel to Arathi Highlands and turn the quest in at a NPC Skuerto, although that is not possible. Even logging in and out, will not solve the bug or retaking the quest.

**Current behaviour**:

**Expected behaviour**: 

**Server Revision**:

**Comment by Evolvee** [comment]
its not supposed to be turned in arathi highlands

**Comment by Evolvee** [comment]
nvm

https://github.com/Atlantiss/NetherwingBugtracker/issues/4590
https://github.com/Atlantiss/NetherwingBugtracker/issues/757

its already reported here
