### ISSUE TITLE
[Dungeon][NPC][Spell] Murmur is not using Thundering Storm in Heroic mode

### ISSUE THREAD

**Issue by Albarok** [Atlantiss/NetherwingBugtracker#5507]
[//]: # (Enclose links to things related to the bug using http://wowhead.com or any other TBC database.)
[//]: # (You can use screenshot ingame to visual the issue.)
[//]: # (Write your tickets according to the format:)
[//]: # ([Quest][Azuremyst Isle] Red Snapper - Very Tasty!)
[//]: # ([NPC] Magistrix Erona)
[//]: # ([Spell][Mage] Fireball)
[//]: # ([Npc][Drop] Ghostclaw Lynx)
[//]: # ([Web] Armory doesnt work)
[//]: # (To find server revision type `.server info` command in the game chat.)

**Description**: 
Murmur in Heroic mode is not using his spell Thundering Storm.

**Current behaviour**:
Players who are standing far from Murmur (25 yards) are not being hit Thundering Storm. 

**Expected behaviour**: 
In heroic mode, anyone outside of Murmur's inner ring, including standing on the slopes of the ring, needs to be the target of Thundering Storm. All players must be within Murmur's inner ring to avoid damage.

Links:
https://wowwiki.fandom.com/wiki/Murmur#Heroic_mode

https://www.wowhead.com/spell=39365/thundering-storm

**Server Revision**: 
2912

**Comment by Wolffenstein** [comment]
Fixed in rev 2915.
