### ISSUE TITLE
Hunter swap target stutter

### ISSUE THREAD

**Issue by Cedevito** [Atlantiss/NetherwingBugtracker#5509]
[//]: # (Enclose links to things related to the bug using http://wowhead.com or any other TBC database.)
[//]: # (You can use screenshot ingame to visual the issue.)
[//]: # (Write your tickets according to the format:)
[//]: # ([Quest][Azuremyst Isle] Red Snapper - Very Tasty!)
[//]: # ([NPC] Magistrix Erona)
[//]: # ([Spell][Mage] Fireball)
[//]: # ([Npc][Drop] Ghostclaw Lynx)
[//]: # ([Web] Armory doesnt work)
[//]: # (To find server revision type `.server info` command in the game chat.)

**Description**: 
When I swap targets with right mouse click on my hunter, the weapon starts to stutter and it doesn't shot, it only starts after I press a spell or move, it gets annoying. 

**Current behaviour**:
Weapon stutters when right clicking on mobs.

**Expected behaviour**: 
It shouldn't stutter, it should just continue to fire.

**Server Revision**:

**Comment by Dragunovka** [comment]
broken since release

**Comment by Kristoferhh** [comment]
reeeeeeeeee please fix

**Comment by Dragunovka** [comment]
up

**Comment by Dragunovka** [comment]
up

**Comment by Dragunovka** [comment]
up, same with tab targeting

**Comment by Dragunovka** [comment]
@Wolffenstein

**Comment by Manaci** [comment]
Fixed
