### ISSUE TITLE
([NPC][Spell] Defensive Pet Stance Behavior)

### ISSUE THREAD

**Issue by boringdawg** [Atlantiss/NetherwingBugtracker#551]
[//]: # (Enclose links to things related to the bug using http://wowhead.com or any other TBC database.)
[//]: # (You can use screenshot ingame to visual the issue.)
[//]: # (Write your tickets according to the format:)
[//]: # ([Quest][Azuremyst Isle] Red Snapper - Very Tasty!)
[//]: # ([NPC] Magistrix Erona)
[//]: # ([Spell][Mage] Fireball)
[//]: # ([Npc][Drop] Ghostclaw Lynx)
[//]: # ([Web] Armory doesnt work)

**Description**: 
Pets will start attacking once you land a spell on a target.
**Current behaviour**:
They start attacking.
**Expected behaviour**: 
In this video from 2008 (https://youtu.be/KUmThmBgUck?t=1m40s), you see a warlock casting a shadow bolt that does not resist or miss - and his voidwalker, which is on defensive does not start attacking until the lock presses Attack himself.
**Server Revision**: 
2050

**Comment by Easyfraggy** [comment]
Gonna need some more videos of this if possible, while the video might be from 2008 it could have been recorded much earlier.

**Comment by boringdawg** [comment]
https://www.wowhead.com/forums&topic=48291
It's not a video, but I found this post from 9 days after patch 3.0.2 went live in the US.
"Before the patch, I used 'Defensive' most of the time - It would attack only if I got hit or if I sent it to attack.." 
I also found another post, about the scourge invasion event
https://www.wowhead.com/forums&topic=48283
Which was the same day as the first post. Which makes me think it was a change during 3.0.2
