### ISSUE TITLE
My body is gone...

### ISSUE THREAD

**Issue by makavell** [Atlantiss/NetherwingBugtracker#5510]
well i died a few days ago and instead of being smart and retreiving my body before i logged out i decided not too thinking this server wasnt so bugged logged in today after about 3 days im still dead but my body is knowhere to be found ive been in other pvt servers before and they have options to get your body back but this one does not can anyone hopefully a dev help me fix this i was really getting into tbc but honestly now im just reconsidering dropping it all together whats the point if im going to level up to 30 again just to lose it all... anyways i hope someone can help me with this have a great day everyone.

**Comment by Godmatik** [comment]
Open a GM ticket
