### ISSUE TITLE
Perception Bug

### ISSUE THREAD

**Issue by Pankakehouse** [Atlantiss/NetherwingBugtracker#5511]
[//]: # (Enclose links to things related to the bug using http://wowhead.com or any other TBC database.)
[//]: # (You can use screenshot ingame to visual the issue.)
[//]: # (Write your tickets according to the format:)
[//]: # ([Quest][Azuremyst Isle] Red Snapper - Very Tasty!)
[//]: # ([NPC] Magistrix Erona)
[//]: # ([Spell][Mage] Fireball)
[//]: # ([Npc][Drop] Ghostclaw Lynx)
[//]: # ([Web] Armory doesnt work)
[//]: # (To find server revision type `.server info` command in the game chat.)

**Description**: 
Perception Bug
**Current behaviour**:
Perception cannot detect Night Elf Druid until they are literally on top of you when the ability should let you see someone a mile away same thing with Night elf rogues and other rogues. I've tested it with my buds and they have tested it with other human rogues and results were the same. I've not tested it with a Tauren druid due to being Alliance
**Expected behaviour**: 
The ability perception should allow a human with the ability on to see a stealth person/creature from really far. If the person is a human rogue he should be able to detect another stealth person/creature from a ways away as well. Without having to have the stealth-ed person literally on top of them.
**Server Revision**:

**Comment by Wolffenstein** [comment]
It depends on the stealth level of the target. It seems to work fine for me without any talents or bonuses:

With Perception:
![image](https://user-images.githubusercontent.com/1576644/55284285-de740280-5373-11e9-98ee-751dbc9982ac.png)

Without Perception:
![image](https://user-images.githubusercontent.com/1576644/55284287-e5027a00-5373-11e9-8dc2-a5869b7c5ac6.png)
