### ISSUE TITLE
[PvP][Alterac Valley] Bugged warmaster/marshal auras

### ISSUE THREAD

**Issue by ghost** [Atlantiss/NetherwingBugtracker#5512]
[//]: # (Enclose links to things related to the bug using http://wowhead.com or any other TBC database.)
[//]: # (You can use screenshot ingame to visual the issue.)
[//]: # (Write your tickets according to the format:)
[//]: # ([Quest][Azuremyst Isle] Red Snapper - Very Tasty!)
[//]: # ([NPC] Magistrix Erona)
[//]: # ([Spell][Mage] Fireball)
[//]: # ([Npc][Drop] Ghostclaw Lynx)
[//]: # ([Web] Armory doesnt work)
[//]: # (To find server revision type `.server info` command in the game chat.)

**Description**: Marshals and Warmasters has an aura when u have not destroyed/killed bunker, at the moment this aura can be removed by pulling them too far from the others, and atm people abuse it in every game so AV finishes in a few minutes without a fight

**Current behaviour**: People can pull the NPCs too far apart and their auras disappear making AV rush take 5 min.

**Expected behaviour**: People should have to destroy the tower/bunker or try to kill the Marshals when they are buffed

**Server Revision**: 2910

**Comment by Zarant** [comment]
The only thing bugged about the marshal/warmaster auras is the fact that they are not being removed upon killing them. Their aura still persist after the NPC is dead.


As for pulling them away from Drek/Van, it was impossible after the AV changes in patch 2.3.

> Prior to 2.3, Warmasters and their counterparts, the Stormpike Marshals, could be pulled separately from their Generals. Additionally, the destruction of an Alliance Bunker would not only despawn a Marshal, but also spawn an extra Warmaster - and vice versa. Now, each side will only ever have the four guards they start the battle with. 

https://wowwiki.fandom.com/wiki/Warmaster

There is an inconsistency in their behavior, you should either have 8 marshals/warmasters total (as it was pre patch 2.3) or just have them reset whenever they are pulled outside (post 2.3).

**Comment by bajkorv** [comment]
The auras should still not disappear when u pull them too far from the others, that is a bug, and people are abusing it every game. That is the issue in this thread

**Comment by Saprape** [comment]
> AV finishes in a few minutes without a fight
This is the main problem. Current AV gameplay is terrible! Please make the end-game AV despite the current patch! Everybody will get their honor anyway. I want to play real AV, when you burn towers etc. instead of rushing to a boss and killing him spending 3 minutes for a round.

**Comment by Saprape** [comment]
This is the main problem. Current AV gameplay is terrible! Please make the end-game AV despite the current patch! Everybody will get their honor anyway. I want to play real AV, when you burn towers etc. instead of rushing to a boss and killing him spending 3 minutes for a round.

**Comment by Godmatik** [comment]
Closing - will consolidate all outstanding AV issues into one thread now.
