### ISSUE TITLE
[PvP][Alterac Valley] Warmaster/Marshal damage too low

### ISSUE THREAD

**Issue by ghost** [Atlantiss/NetherwingBugtracker#5513]
[//]: # (Enclose links to things related to the bug using http://wowhead.com or any other TBC database.)
[//]: # (You can use screenshot ingame to visual the issue.)
[//]: # (Write your tickets according to the format:)
[//]: # ([Quest][Azuremyst Isle] Red Snapper - Very Tasty!)
[//]: # ([NPC] Magistrix Erona)
[//]: # ([Spell][Mage] Fireball)
[//]: # ([Npc][Drop] Ghostclaw Lynx)
[//]: # ([Web] Armory doesnt work)
[//]: # (To find server revision type `.server info` command in the game chat.)

**Description**: Warmasters and Marshals hit like wet noodles even with all buffs up aka 100% damage and hp increase. People only bug abuse and pull them away from the others auras cause of the extra hp they get.

**Current behaviour**:  players pull and use 1 tank for 2 marshals and he barely takes any damage. No towers destroyed, all other Marshals up. Have even seen priest tank warmaster

**Expected behaviour**: Warmasters and Marshals should do some serious damage to incentivize destroying bunkers and towers. Especially when they have all auras
A priest should get 1-2 shot, not be able to solo heal himself while tanking and stay alive 

**Server Revision**: 2910

**Comment by Zarant** [comment]
I know that AV is a hot mess right now, but you should provide sources for your reports instead of going with your gut feeling.

**Comment by bajkorv** [comment]
ATM with patch 2.0 AV should be just like 1.12.1 AV, lieutenants and Marshals etc should be pretty hard still..
Patch 2.3 only removes lieutenants and makes van/drek chainpull with Marshals/Warmasters(further incentivizes and makes easier for bunker takedowns)

**Comment by Manaci** [comment]
Imo the prio if AV is gonna get fixed is to get it up to patch 2.3 standards before looking at patch 2.0 stuff. Although it would be nice if we could get the pre-2.3 AV too.

**Comment by Godmatik** [comment]
Closing - will consolidate all outstanding AV issues into one thread now.
