### ISSUE TITLE
[PvP][Alterac Valley] Vandarrs hp resets midfight

### ISSUE THREAD

**Issue by bajkorv** [Atlantiss/NetherwingBugtracker#5515]
[//]: # (Enclose links to things related to the bug using http://wowhead.com or any other TBC database.)
[//]: # (You can use screenshot ingame to visual the issue.)
[//]: # (Write your tickets according to the format:)
[//]: # ([Quest][Azuremyst Isle] Red Snapper - Very Tasty!)
[//]: # ([NPC] Magistrix Erona)
[//]: # ([Spell][Mage] Fireball)
[//]: # ([Npc][Drop] Ghostclaw Lynx)
[//]: # ([Web] Armory doesnt work)
[//]: # (To find server revision type `.server info` command in the game chat.)

**Description**: Vandarr Stormpike is the alliance boss of Alterac Valley who atm resets hp midfight at times even when nobody has run out of his room

**Current behaviour**: As Van shifts aggro and runs around in his room, his hp will reset at times. This is because his auras are not correctly removed when his Marshals are dead - when he runs around inside his room he gains and ’ungains’ his marshal buffauras all the time as he runs around, which in turn resets his hp.

**Expected behaviour**: Marshal buff auras should be removed from Vandarr when they die or bunker is destroyed. His hp should not reset unless all in combat die or someone runs out of his room and gets aggro when he is outside.

**Server Revision**: 2910

**Comment by Kristoferhh** [comment]
I mean, I don't know if this is a bug or not. But the reason he heals is because the buffs are auras given by the marshals, so if he goes in range of the marshals and gets the buff, he gets increased health and heals. Which is why you're supposed to drag the marshals far away when killing them so it doesn't happen when fighting vanndar

**Comment by danbopes** [comment]
Why did you close all your issues? Has this been fixed?

**Comment by bajkorv** [comment]
Closed them because AV is semi dead anyway, theres no 40v40, i rather them focus on stuff that matters. AV sucks anyway working or not... Aswell as this bug is 100% linked to the warmaster/marshal auras, which i saved the bug report for.
