### ISSUE TITLE
[Quest][Feralas] Rescue OOX-22/FE!

### ISSUE THREAD

**Issue by nicozagi** [Atlantiss/NetherwingBugtracker#5516]
**Description**: 

In my case, the chicken flew away after reaching the pathway going nord. Despite the fact that it did not complete my quest this is a version that was introduced in wotlk.

**Current behaviour**:

Escort path having short version from wotlk.

**Expected behaviour**: 

Escort path should be longer all the way up to the coast.

**Note**: 

Found this here: https://classicdb.ch/?quest=2767

On my second attempt I was able to complete the quest.

**Comment by Evolvee** [comment]
its known and already reported

**Comment by nicozagi** [comment]
Odd, used search function. Sorry for that:)
