### ISSUE TITLE
[Item][World drop] Design: Embrace of the Dawn

### ISSUE THREAD

**Issue by jauho-1** [Atlantiss/NetherwingBugtracker#5517]
**Description**: I have not been able to find the design or crafted necklace. Looked in auction house and asked in world. Proof is not conclusive, but it leads me to believe the recipe is not in the game.

According to https://www.wowhead.com/item=24170/design-embrace-of-the-dawn#dropped-by it should have been added in patch 2.0.1.6180.

**Current behaviour**: I can't find crafter/recipe.

**Expected behaviour**: I should be able to find crafter/recipe.

**Comment by Evolvee** [comment]
I dont see it in any loot table 🐌

**Comment by jauho-1** [comment]
This 2.0 item (world drop recipe) is still missing from the game.

**Comment by Evolvee** [comment]
fixed in next rev
