### ISSUE TITLE
[Quest][Horde][Mage] Investigate The Alchemist Shop

### ISSUE THREAD

**Issue by Gorebane** [Atlantiss/NetherwingBugtracker#5518]
**Description:** 
I am in the correct place to spawn the multiple 'Rift Spawn' npc's with my 'Cantation of Manifestation' but nothing happens. The quest is currenly broken and I can't complete it. This is at the alchemist store in Undercity.

**Current behaviour:**
The 'Rift Spawn' are not spawning when using the 'Cantation of Manifestation'.

**Expected behaviour:**
The 'Rift Spawn' should be spawning when using the 'Cantation of Manifestation' in front of the alchemist store in Undercity.

**Comment by Evolvee** [comment]
https://github.com/Atlantiss/NetherwingBugtracker/issues/5518

**Comment by Gorebane** [comment]
So, this will not be fixed?

The issue is open since september last year.
https://github.com/Atlantiss/NetherwingBugtracker/issues/582

**Comment by Evolvee** [comment]
i closed it because its a duplicate

**Comment by Gorebane** [comment]
Ah okay, but it's open since september.. Is there any progress in fixing it?

**Comment by Evolvee** [comment]
no

**Comment by Teakane** [comment]
https://youtu.be/5BLUjox_l4w
