### ISSUE TITLE
Windrunner Village several patrols missing

### ISSUE THREAD

**Issue by Tenoutoften** [Atlantiss/NetherwingBugtracker#552]
**Description**: 
One Stonewing Slayer#16324 (https://db.excalibur.ws/?npc=16324) should be patrolling around the village seen here https://youtu.be/CmTcUQWIAJk?t=166 (It's on the right side going around the building)

A Stonewing Slayer#16324 (https://db.excalibur.ws/?npc=16324)  is flying up the building at https://youtu.be/CmTcUQWIAJk?t=222 this one is probably just patrolling the building.

Judging by https://youtu.be/8sO8RaEnjmg?t=97 perhaps a lot of the bats around the village move about 15-20 yards on their spot?

A Phantasmal seeker#16323 (https://db.excalibur.ws/?npc=16323)should be patroling the roads, here it stands still at spawn position(coords: 20.50, 44.30, Id:18, GUIDLow: 78503)

**Expected behaviour**: 
I expect there to be a few patrols in this village based on video evidence from Cataclysm and what Blizzard usually does in villages around this level,  but there are none.

**Server Revision**: 
2050

**Comment by aresbrutus** [comment]
Fixed in one of the upcoming updates.
