### ISSUE TITLE
Die from Logout post-pvp interaction

### ISSUE THREAD

**Issue by Brian-Shaw** [Atlantiss/NetherwingBugtracker#5520]
[//]: # (Enclose links to things related to the bug using http://wowhead.com or any other TBC database.)
[//]: # (You can use screenshot ingame to visual the issue.)
[//]: # (Write your tickets according to the format:)
[//]: # ([Quest][Azuremyst Isle] Red Snapper - Very Tasty!)
[//]: # ([NPC] Magistrix Erona)
[//]: # ([Spell][Mage] Fireball)
[//]: # ([Npc][Drop] Ghostclaw Lynx)
[//]: # ([Web] Armory doesnt work)
[//]: # (To find server revision type `.server info` command in the game chat.)

**Description**: Two times, i have had a recent pvp experience and I get out of combat. I logout in an inn, within about 15 seconds of getting out of combat. When I am brought to login screen my character is a ghost, and when I log back in I am dead. This happened twice, once was in Shat, which is a neutral city so I could not have died due to pvp.

**Current behaviour**: Die when logout, not from player or monster

**Expected behaviour**: I live normally

**Server Revision**:

**Comment by Jumpinlord** [comment]
can confirm that after logout I saw a ghost at login screen, specially tested it, I was not in combat, no one enemy was near me, I watched all 20 sec while logout, it was good but on login screen - ghost.

**Comment by Zarant** [comment]
I couldn't reproduce it exactly the way you described, however, I think I found why that happens.

If you are in combat and enter a rested zone, you are able to log out in combat. You shouldn't be able to log out in combat, even inside a rested xp zone.

The reason you died there is related to issue #103
