### ISSUE TITLE
[Hunter] [Traps] Stealthed players cause hunter traps to fizzle entirely.

### ISSUE THREAD

**Issue by gunzbngbng** [Atlantiss/NetherwingBugtracker#5521]
[//]: # (Enclose links to things related to the bug using http://wowhead.com or any other TBC database.)
[//]: # (You can use screenshot ingame to visual the issue.)
[//]: # (Write your tickets according to the format:)
[//]: # ([Quest][Azuremyst Isle] Red Snapper - Very Tasty!)
[//]: # ([NPC] Magistrix Erona)
[//]: # ([Spell][Mage] Fireball)
[//]: # ([Npc][Drop] Ghostclaw Lynx)
[//]: # ([Web] Armory doesnt work)
[//]: # (To find server revision type `.server info` command in the game chat.)

**Description**: Frost Trap is an AOE slow that triggers when a player comes into contact with it. 
Freezing Trap should CC a player when they come into contact with it.  
Immolation trap should apply a dot when a player comes into contact with it.

Stealthed or not.

**Current behaviour**:  If a stealthed player comes into contact with Frost, Freeze, or Immo Trap while stealthed, the entire trap will fizzle.  Nothing will happen.

**Expected behaviour**: Players who come into contact with traps should be dealt the trap's effects.  Stealthed or not.

In addition, Frost Trap's aoe slow is intended to go through a pillar.  Wherever the frosted area is, should apply the slow immediately, only those immune ignoring it's effects.  Placing a Frost Trap on the coffin in Ruins, only slows the coffin, not the area around it currently.  In some cases, players ignore it's effects entirely, running through it multiple times without being slowed.

**Server Revision**: 2915

**Comment by Zarant** [comment]
I tested this earlier, on this server traps don't activate if the hunter doesn't have vision over the target.

**Comment by Zarant** [comment]
Adding a source from retail: https://youtu.be/9z2m9f8Z9P4?t=171
Rogue gets trapped after vanishing, even when the hunter had no vision over him

**Comment by Easyfraggy** [comment]
> In addition, Frost Trap's aoe slow is intended to go through a pillar.

Need some really solid proof of this.

**Comment by gunzbngbng** [comment]
At 14:40 a priest is in a frost trap, he hugs the pillar as he goes around it. Frost trap stays on him the whole time.

https://youtu.be/FAz6E6W4T-I?t=872

**Comment by Wolffenstein** [comment]
Fizzling fixed in rev 2933. Please open a new ticket for the LoS issue to avoid clusterfuck.
