### ISSUE TITLE
Buff/Debuff dispel mechanics

### ISSUE THREAD

**Issue by liderer** [Atlantiss/NetherwingBugtracker#5522]
Description:  
Buff/Debuff dispel mechanics are incorrect.  This mechanic worked in the days of retail TBC , and 
and in all next  patches. 

Current behaviour:  

Cast dispel/Devour magic on target with 5x charge of winter's chill debuff + polymorph.
Currently it's a 1/6 chance to remove polymorph.

Cast abolish/cure poison on target with 5x wound poison + 1x crippling poison
Currently it's a 1/6 chance to remove crippling poison

Expected behaviour: 

A debuff with multiple charges such as winter's chill or wound poison or scorpid poison etc. should still count as 1 debuff.
Should be a 50% chance to remove crippling poison and 50% chance to remove 1 charge of wound poison. 

Proofs  TBC : 

1) www.arenajunkies.com/topic/14796-viper-sting-easier-to-dispel

2) www.arenajunkies.com/topic/32697-why-does-devour-always-get-the-sheep 

3) www.arenajunkies.com/topic/34707-spell-pen-is-absolutely-worthless/#entry311213  

Past TBC :  

4) www.arenajunkies.com/topic/114054-do-you-stack-winters-chill-vs-warlocks/#entry1589618

5) www.arenajunkies.com/topic/140581-blizzard-winters-chill-5-stacks-at-once/page-4#entry2097447

**Comment by Wolffenstein** [comment]
Thats how it's implemented right now (unless there's a bug in the code).

**Comment by gabbat** [comment]
might be related to https://github.com/Atlantiss/NetherwingBugtracker/issues/5372

**Comment by Evolvee** [comment]
I just briefly tested it, it works as intended...

If you think it doesnt, provide some test results please.
