### ISSUE TITLE
[Quest][Scholomance] The Right Piece of Lord Valthalak's Amulet (Scholomance) quest for the tier 0.5 isn't working.

### ISSUE THREAD

**Issue by Ousak1** [Atlantiss/NetherwingBugtracker#5523]
**Description**: 
Quest for the Tier 0.5 isn't working as described down below

Quest : https://www.wowhead.com/quest=8992/the-right-piece-of-lord-valthalaks-amulet

Edit: there are four braziers, depending on the chain that you follow (https://www.wowhead.com/item=22056/brazier-of-beckoning#see-also), this one is this (with the **Kormok** text) https://www.wowhead.com/item=22052/brazier-of-beckoning.

**Current behaviour**:
Using "**Brazier of Beckoning**" at **Ras Frostwhisper** (Boss) room, doesn't spawn the NPC: **Kormok**, which has the quest item.

**Expected behaviour**: 
For the quest you are supposed to use an item called "**Brazier of Beckoning**" inside Scholomance at **Ras Frostwhisper** (Boss) room, and then NPC: **Kormok** will spawn which will give you the quest item.

**Server Revision**: 
2915

**Comment by Evolvee** [comment]
rev 2922
