### ISSUE TITLE
[Quest][Upper Blackrock Spire] Mea Culpa, Lord Valthalak quest for the tier 0.5 (D2) not working.

### ISSUE THREAD

**Issue by gvozdeni** [Atlantiss/NetherwingBugtracker#5525]
[//]: # (Enclose links to things related to the bug using http://wowhead.com or any other TBC database.)
[//]: # (You can use screenshot ingame to visual the issue.)
[//]: # (Write your tickets according to the format:)
[//]: # ([Quest][Azuremyst Isle] Red Snapper - Very Tasty!)
[//]: # ([NPC] Magistrix Erona)
[//]: # ([Spell][Mage] Fireball)
[//]: # ([Npc][Drop] Ghostclaw Lynx)
[//]: # ([Web] Armory doesnt work)
[//]: # (To find server revision type `.server info` command in the game chat.)

**Description**: 
The final quest for the Tier 0.5 (D2) chain isn't working, the quest is this: https://www.wowhead.com/quest=8995/mea-culpa-lord-valthalak

**Current behaviour**:
On this quest, you should use the **Brazier of Beckoning** (This version of the brazier https://www.wowhead.com/item=22056/brazier-of-beckoning) at the **Upper Blackrock Spire** dungeon, inside the **The Beast's** room, and then the boss **Lord Valthalak** (https://www.wowhead.com/npc=16042/lord-valthalak) should spawn, the spawn isn't happening.

**Expected behaviour**: 
On this quest, you should use the **Brazier of Beckoning** (This version of the brazier https://www.wowhead.com/item=22056/brazier-of-beckoning) at the **Upper Blackrock Spire** dungeon, inside the **The Beast's** room, and then the boss **Lord Valthalak** (https://www.wowhead.com/npc=16042/lord-valthalak) should spawn. Which you need to defeat and use the item on his corpse (this item https://www.wowhead.com/item=22048/lord-valthalaks-amulet), which should spawn **Spirit of Lord Valthalak** (https://www.wowhead.com/npc=16073/spirit-of-lord-valthalak) at the **Lord Valthalak's** corpse location who allows you to finish the quest, and will also give you the follow up quest (https://www.wowhead.com/quest=8996/return-to-bodley) to return to **Bodley** (https://www.wowhead.com/npc=16033/bodley) the npc that started the chain.

**Server Revision**: 
2915

**Comment by Evolvee** [comment]
rev 2922
