### ISSUE TITLE
[Object] Air bubbles do not correctly give Air Bubble debuff

### ISSUE THREAD

**Issue by danbopes** [Atlantiss/NetherwingBugtracker#5526]
**Description**: 
The air bubbles beneath The Forgotten Pool in Barrens (Coords: 45.07, 22.53) do not currently work correctly. They should give the debuff Air Bubbles, reset breath bar, and allow for breathing while under the effect of the debuff.

**Current behaviour**:
![2019-03-31_00-29-01](https://user-images.githubusercontent.com/4589840/55284819-0c455100-534c-11e9-90b5-c45f158893e1.png)
No debuff was applied, and I started drowning while underneath the water. Moving around in the general vicinity did not work either. No position applied the debuff.

**Expected behaviour**: 
The debuff should be applied correctly.

**Server Revision**: 
2915

**Comment by VoidLock92** [comment]
The same issue is happening beneath The Stagnant Oasis in Barrens (Coords: 55, 44)

**Comment by Zarant** [comment]
Same thing in faldirs cove (arathi highlands) and western desolace.

**Comment by Tereneckla** [comment]
#233
