### ISSUE TITLE
Getting kicked from my guild everytime i disconnects

### ISSUE THREAD

**Issue by Naarue** [Atlantiss/NetherwingBugtracker#5528]
[//]: # (Enclose links to things related to the bug using http://wowhead.com or any other TBC database.)
[//]: # (You can use screenshot ingame to visual the issue.)
[//]: # (Write your tickets according to the format:)
[//]: # ([Quest][Azuremyst Isle] Red Snapper - Very Tasty!)
[//]: # ([NPC] Magistrix Erona)
[//]: # ([Spell][Mage] Fireball)
[//]: # ([Npc][Drop] Ghostclaw Lynx)
[//]: # ([Web] Armory doesnt work)
[//]: # (To find server revision type `.server info` command in the game chat.)

**Description**:  Hi, i get kicked from my guild every time i disconnects from the game, 

**Current behaviour**:
![bug](https://user-images.githubusercontent.com/49115717/55286735-fbbec600-539f-11e9-823e-1cf51ae30d4a.png)

**Expected behaviour**: don't getting kicked every time i dc.

**Server Revision**: 
![serveur info](https://user-images.githubusercontent.com/49115717/55286739-024d3d80-53a0-11e9-9c35-ce8e89a58e44.png)

**Comment by Wolffenstein** [comment]
Ask a GameMaster to properly add you to the guild with a .guild invite command.
