### ISSUE TITLE
[Item] Flasks overwritten by less powerful elixirs

### ISSUE THREAD

**Issue by ScottieDOESknow** [Atlantiss/NetherwingBugtracker#5529]
**Current behaviour**: Flasks can be overwritten by less powerful elixirs

**Expected behaviour**:  Flasks should NOT be overwritten by less powerful elixirs

"A flask counts as both a Battle Elixir and a Guardian Elixir, so only one flask at a time may be used. Subsequent flasks imbibed will overwrite the effects of the former and **_prevent a player from using other elixirs._**"

source
http://legacy.zam.com/wiki/Flasks_%28WoW%29

---------------------------------------------------------------------------------------------------------

Flask patches since 2005
![image](https://user-images.githubusercontent.com/43949261/55294577-d8ad0a00-53d1-11e9-94ef-eee447b50617.png)

source
https://wow.gamepedia.com/Flask

**Server Revision**:  2915

**Comment by Dragunovka** [comment]
just use Elixirs - problem solved :)

**Comment by ScottieDOESknow** [comment]
Still happening as of today
20 Sept 2019

Revision 3132

**Comment by devo6969** [comment]
https://wow.allakhazam.com/wiki/Flasks_%28WoW%29
A flask counts as both a Battle Elixir and a Guardian Elixir, so only one flask at a time may be used. Subsequent flasks imbibed will overwrite the effects of the former and prevent a player from using other elixirs.

**Comment by Tereneckla** [comment]
https://www.wowhead.com/item=22854/flask-of-relentless-assault#comments:id=326999:reply=39762
you cannot use any [guardian/battle elixir] on top of this
if you use any on top, it will "overwrite" it.

**Comment by ScottieDOESknow** [comment]
So this was never fixed?

A flask counts as both **Battle** _and_ **Guardian** elixir
An elixir counts as either **Battle** _OR_ **Guardian** elixir
Flask = more powerful than elixir

A normal elixir (**Battle** _OR_ **Guardian**) should not overwrite flask since it is more powerful (**Battle** _and_ **Guardian**)

I figured this would be pretty straightforward since I linked the source back in March 2019 with original ticket

https://wow.allakhazam.com/wiki/Flasks_%28WoW%29

![image](https://user-images.githubusercontent.com/43949261/87416810-3f414180-c59d-11ea-9006-cb7980854891.png)

**Comment by ScottieDOESknow** [comment]
Should function like this...

https://gyazo.com/2bc699299e9730374e5add571cc1d7b5

Using a lesser buff should not overwrite a more powerful buff
Instead, game should give error message as shown in video

_A more powerful spell is already active_

**Comment by devo6969** [comment]
Retail BFA - https://www.youtube.com/watch?v=829EofqHFTM

**Comment by ScottieDOESknow** [comment]
https://www.wowhead.com/item=22831/elixir-of-major-agility#comments:id=38136
_2007/02/22 (Patch 2.0.8)
The two effects are treated separately for stacking purposes; the game will only take the strongest one of any type._

https://wowwiki.fandom.com/wiki/Flask
_Flasks created by alchemists count as both a Battle Elixir and a Guardian Elixir, so characters can only have the effect of one flask at a time, and it prevents them from having other elixir effects._

https://wowwiki.fandom.com/wiki/Battle_Elixir
_Elixirs will stack with ability-generated buffs (Trueshot Aura for example) but will not stack with other Battle Elixirs.
Players can only have one Guardian Elixir and one Battle Elixir active on them at one time, or one Flask, which counts as both Elixir slots._

https://wowwiki.fandom.com/wiki/Elixir#Battle_Elixirs
_Flask - A more powerful type of elixir in which effects persist through death, and counts as both a guardian elixir and a battle elixir._

**Comment by devo6969** [comment]
Of all those sources where does it state it prevents people using an elixir to over write a flask. It only ever says "consider to be both guardian/battle and prevents through death.

**Comment by devo6969** [comment]
2007/02/22 (Patch 2.0.8)
The two effects are treated separately for stacking purposes; the game will only take the strongest one of any type.

This is related to elixirs only from what I'm reading on the comment section. This is also before 2.1 where everything was changed with elixirs/flask usage. No where it states "Flasks prevents elixirs overwriting flasks"

"The two effects are treated separately for stacking purposes; the game will only take the strongest one of any type. So what you're seeing when using this with a mongoose is: 35 agility from this overrides the 25 agility from mongoose 28 crit rating from mongoose overrides the 20 crit rating from this (an increase of about .3% at 70)"

**Comment by fitqt** [comment]
> This is related to elixirs only from what I'm reading on the comment section. This is also before 2.1 where everything was changed with elixirs/flask usage. No where it states "Flasks prevents elixirs overwriting flasks"

Flask stacked with elixirs pre-2.1. 

Source: [https://www.youtube.com/watch?v=wm4XsKdLNzk](url)
[https://www.youtube.com/watch?v=u1LOAT96vEs](url)

**Comment by ScottieDOESknow** [comment]
> This is related to elixirs only

Flasks ARE elixirs, this is why you can proc extra flasks when using flask mastery alchemist.
Flasks are a stronger version of a singular elixir... they count as BOTH guardian and battle.

> No where it states "Flasks prevents elixirs overwriting flasks"

No, that is here, as linked above
https://wowwiki.fandom.com/wiki/Flask
_**and it prevents them from having other elixir effects**._
![image](https://user-images.githubusercontent.com/43949261/87450846-0faa2d80-c5cd-11ea-884c-f8b466ca1f21.png)


and here, again linked twice above
https://wow.allakhazam.com/wiki/Flasks_%28WoW%29
**_and prevent a player from using other elixirs_**
![image](https://user-images.githubusercontent.com/43949261/87450402-75e28080-c5cc-11ea-9684-77302ac0556f.png)

--
>Flask stacked with elixirs pre-2.1.

You are correct. I was mistaken with it being 2.0 patch
https://wowwiki.fandom.com/wiki/Patch_2.1.0
_Elixirs now stack in two categories, Battle (Offensive) and Guardian (Defensive) Elixirs. You can only have one of each type of Elixir up at a time. As a result Elixirs now stack with class abilities such as Arcane Intellect._
![image](https://user-images.githubusercontent.com/43949261/87451504-f190fd00-c5cd-11ea-9f79-1c74be53c578.png)

**Comment by ScottieDOESknow** [comment]
It basically comes down to this...

Consumable and class party/raid buffs were eventually consolidated to only be able to have the strongest active version available at any one time, _due to_ excessive stacking. This is true of flasks & elixirs, scrolls, world buffs, mark of the wild, blessings, fortitude, etc.. If a player tries to overwrite any of these with a lower power or lower rank of similar buff of the same category, then you SHOULD usually get the error message : _**A more powerful spell is already active**_

Flask is a more powerful version of a singular elixir. It's guardian + battle and persists through death.
You should not be able to overwrite it with a less powerful elixir buff from the same category.
Should follow suit just like with like party/raid class buffs, world buffs, scrolls, etc.

**Comment by devo6969** [comment]
I agree what you are saying, but when it says "prevents a player from using other elixirs". You can't assume it means "you can't overwrite an elixir with a flask". I _could_ mean it prevents them from stacking elixirs with flasks. Again, I agree what you are saying, but as it says, a flask is considered both a Battle/Guardian, and their is a comment stating that it will override the flask from patch 2.4.3. I searched through a lot of patch notes and was unable to find when or if it was ever changed.

(Patch 2.4.3)
"Does this flask stack with other elixirs? Such as elixir of major strength or fel strength elixir?"

"Use: Increases attack power by 120 for 2.00 hrs. Counts as both a Battle and Guardian elixir. This effect persists through death. No, you cannot use any of those on top of this. You can only have one of each, this counts as both and if you use any on top, it will "overwrite" it."

**Comment by devo6969** [comment]
Still having troubles finding any patch notes. Figured this would be a food for thought though because elixirs weren't more "powerful" than flasks for some classes in TBC/Wotlk. The reason Blizzard redesigned the flask/elixir system was to balance encounters for the future from 2.1 and on. It wasn't till Cata where they drastically changed the amount a flask would give over an elixir. _**"Thinking"**_  this is probably implemented "a more powerful spell is already active". People use Demonslaying in TBC in almost all of SWP content, makes no sense to gate someone from a error code when the situation calls for an elixir pop. 

https://www.wowhead.com/news=178945/ready-for-raiding-flasks-elixirs-potions-and-you#news-post-178945

"Back in the day, you were basically a pro if you rocked your class' most optimal guardian / battle elixir combination"
" Unfortunately, with the drastic changes brought by the Cataclysm, the secondary stats typically just aren't as amazingly awesome as the primary stats, and the lack of quality guardian elixirs makes using a single battle elixir's effect fairly lackluster compared to the big n' beefy flasks. "

**Comment by ScottieDOESknow** [comment]
> but when it says "prevents a player from using other elixirs".
You can't assume it means "you can't overwrite a flask with an elixir"

What do you mean assume? It **literally says exactly that**, from two separate sources.
Does _**prevent**_ mean something different to you? It's rather straightforward to me.
https://www.merriam-webster.com/dictionary/prevent
**1. to keep from happening or existing
2. to hold or keep back** 

https://wow.allakhazam.com/wiki/Flasks_%28WoW%29
_**and prevent a player from using other elixirs**_
![image](https://user-images.githubusercontent.com/43949261/87501885-38164400-c62e-11ea-9c8b-3141e9c8c0d2.png)

https://wowwiki.fandom.com/wiki/Flask
**_and it prevents them from having other elixir effects._**
![image](https://user-images.githubusercontent.com/43949261/87501959-62680180-c62e-11ea-815f-476d2e762d8d.png)

> a flask is considered both a Battle/Guardian, and their is a comment stating that it will override the flask

Yes. **Only a flask can overwrite a flask**, just as stated in sources above. Nobody was arguing that?

>You are turning the phrase "prevents a player from using other elixirs" and making it mean "elixirs don't overwrite a flask" which it doesn't say that at all.

Again, everything I linked above disproves your assertion.
 It means exactly what it's intended to mean. You are presenting a strawman argument.
- **_Subsequent flasks imbibed will overwrite the effects of the former and prevent a player from using other elixirs._**
- **_characters can only have the effect of one flask at a time, and it prevents them from having other elixir effects._**

--

> Still having troubles finding any patch notes.

I linked relevant patch notes above. Where are you looking for patch info?
Are you actually reading the sources I provide or just looking for confirmation bias?

> because elixirs weren't more "powerful" than flasks for some classes in TBC

Does not matter per class. It's already been established that flasks are a more powerful buff than single elixirs.
_Flask - **A more powerful type of elixir** in which effects persist through death, and counts as both a guardian elixir and a battle elixir._
Class preference is not the claim. This is your 2nd strawman argument.

> People use Demonslaying in TBC in almost all of SWP content, makes no sense to gate someone from a error code when the situation calls for an elixir pop.

Yes, and before SWP too. Most physical DPS who have done content on retail and/or pservers are aware of this.
There is not one boss fight in TBC where player would switch from assault flask to demonslaying mid-fight, it's either or.
The other problem is that this is again your third strawman argument... can we please stay on track?

> It wasn't till Cata...

I don't understand why you keep bringing up Cata or even BFA as example of how TBC should be.
Latter expansions are not relevant sources on how anything should or should not function in TBC.

--
I've provided sufficient evidence for my claims, which haven't changed since the original post March 2019.
We can keep going back and forth, but you should provide evidence to the contrary that is not based on a fallacy.

**Comment by devo6969** [comment]
I guess all pservers got this wrong then besides cata servers because every single one of them allows you to overwrite a flask buff with an elixir expect cata. What you are providing is not exactly saying "In TBC you can't overwrite a flask buff with an elixir" there is a comment stating you can, you haven't provided anything to prove otherwise. The word prevent does NOT mean "cant be overwriten". Everything you have linked is legit the same phrase. Prove that comment wrong from TBC (with 6 upvotes) with another comment from TBC or WOTLK (cause you can overwrite a flask with an elixir in wotlk). And big fyi, wowwiki isnt always right, its like wikipedia, seen wrong information on it before from looking at Wowhead and other sites, ingame retail.

**Comment by ScottieDOESknow** [comment]
I agree. Most private servers do have this wrong, among many other things.

**Comment by Godmatik** [comment]
![wwww](https://github.com/user-attachments/assets/873a63f9-909d-42fa-950d-0c0056c53ab7)

![dddd](https://github.com/user-attachments/assets/10e3e7e0-611f-480c-8e8d-9b36aabd4015)

On classic - you can replace flasks with elixirs, as shown above.
And I see no definitive proof otherwise that this should not be possible - so seems like an invalid report to me.

Closing.
