### ISSUE TITLE
[Shadowfang Keep][BOSS: ]Archmage Arugal is not porting himself

### ISSUE THREAD

**Issue by Emityx** [Atlantiss/NetherwingBugtracker#553]
**Current behaviour**:
Archmage Arugal isn't porting himself on the orher platform during the fight.

**Expected behaviour**: 
Archmage Arugal is supposed to port himself on the other platform during the fight. 

**Server Revision**: 
2050

**Comment by Wolffenstein** [comment]
Fixed in rev 2052.
