### ISSUE TITLE
[Raid][SSC][Hydross] crushing blows

### ISSUE THREAD

**Issue by knasen88** [Atlantiss/NetherwingBugtracker#5530]
[//]: # (Enclose links to things related to the bug using http://wowhead.com or any other TBC database.)
[//]: # (You can use screenshot ingame to visual the issue.)
[//]: # (Write your tickets according to the format:)
[//]: # ([Quest][Azuremyst Isle] Red Snapper - Very Tasty!)
[//]: # ([NPC] Magistrix Erona)
[//]: # ([Spell][Mage] Fireball)
[//]: # ([Npc][Drop] Ghostclaw Lynx)
[//]: # ([Web] Armory doesnt work)
[//]: # (To find server revision type `.server info` command in the game chat.)

**Description**: 
Hydross currently is able to deal crushing blows
several sources says he shouldn't be able to and no crushing is mentioned being patched away.
https://wowwiki.fandom.com/wiki/Hydross_the_Unstable
https://wowwiki.fandom.com/wiki/Patch_2.1.0 nothing about crushing being removed, aka it never existed
https://forum.twguild.org/index.php?topic=4067.0
**Current behaviour**:
can crush
**Expected behaviour**: 
should not be able to crush
**Server Revision**: 
2915

**Comment by Evolvee** [comment]
![image](https://user-images.githubusercontent.com/1942409/55295683-411adc00-5410-11e9-9a53-ce1ba407b1af.png)
confirmed by CC Nim

**Comment by knasen88** [comment]
confirmed where? All i see is he should not be able to crush

**Comment by Dragunovka** [comment]
confirmed by CC Nim
literally who?

**Comment by Evolvee** [comment]
you started playing private servers on nost?

**Comment by Drayo** [comment]
https://web.archive.org/web/20070328171232/http://forums.worldofwarcraft.com/thread.html?topicId=85661942&sid=1

Google is hard.

**Comment by knasen88** [comment]
0. This Week In Hot Fixes, March 19 - 25  |  03/20/2007 06:09:19 PM UTC
HOT FIX, DO YOU REALIZE WHAT THIS MEANS? Something that's not part of a content patch and is something that was fixed upon being discovered it was scuffed. not something you delay til heat death of the universe becasue at one point in the game it was actually in. But hey lets make this aswell then ?

> Corrected an issue where Coilfang Ambushers would evade unnecessarily. 
> Gruul should now correctly use his hurtful strike ability. 
 for correctness sake right?

Lady VashjNihilum (EU)29.03.2007 World first vashj kill was after this patch that, most other bosses in this raid died the same month, in march. so hydross being a crushlord was in the game for MAX 1½ month for the TOP guilds.
https://www.method.gg/raid-history/the-burning-crusade

**Comment by Drayo** [comment]
> Nightbane's melee damage has been reduced.

> Hydross the Unstable no longer deals a crushing blow.

> The Romulo and Julianne encounter has been retuned to be less difficult.

> Gruul's health has been lowered, and the damage from his shatter ability has been reduced. 

> The Magtheridon encounter has been rebalanced to be somewhat easier and should now better keep to proper raid progression. 

And the other half were simply tuning changes, conveniently left those out hm? 
Hotfix simply means that it did not require an actual Client Side patch to be changed, a simple Server restart was enough, hence the reason these went live on Wednesdays during maintenance.

There are a shitton of other things that should have been changed by now (even in Kara and Heroics) if we were strictly going by Blizzards timeline, but the intent is to make the content harder, it's 2019, not 2007 even the casuals that take longer to get to 70 might want to have a shot at it. Just because they don't put 20+ hours per week into the game to get to max level asap doesn't mean that they aren't interested in challenging content.

For Hydross this change simply requires a strategy adjustment, many guilds kill him week after week without any issues.

**Comment by knasen88** [comment]
Artificial difficulty =! hard content, just RNG fiesta.

**Comment by Evolvee** [comment]
hydros is being oneshoted by half of the server, what difficulty are we talking about

**Comment by Anselm123** [comment]
Hydross and his adds have double the amount health that he had during early 2.0 kills? maybe shit like that

**Comment by Evolvee** [comment]
you realize that the the recorded fights are already overnerfed right?

**Comment by Anselm123** [comment]
Doesn't that back up our arguments about overtuning? It was nerfed and changed before anyone even got to it, why implement obviously broken numbers that blizzard rapidly changed?

**Comment by femdead** [comment]
Why is this closed? It's still bugged

**Comment by Evolvee** [comment]
how?

**Comment by femdead** [comment]
it was bugfixed before vashj died

**Comment by femdead** [comment]
magic damage crushing is a bug

**Comment by DeerDance56** [comment]
Look at when that hotfix was implemented, @Evolvee. Like 1-2 months after release. It's quite clear that crushing blows aren't the intended behaviour for this boss.

**Comment by DeerDance56** [comment]
![image](https://user-images.githubusercontent.com/23196845/56460269-71ff8880-63a0-11e9-8867-df8d3781a12f.png)

Literally all it would take.

**Comment by Evolvee** [comment]
we dont have stock extra flags 🤕

**Comment by DeerDance56** [comment]
Guess it was restructured then. In either case, I'm sure it's easy enough to implement.

**Comment by Easyfraggy** [comment]
You can have your easymode when 2.1 hits - Nothing is getting nerfed prior to that.
