### ISSUE TITLE
[Hunter][Spell] Trap detection range

### ISSUE THREAD

**Issue by Zarant** [Atlantiss/NetherwingBugtracker#5531]
[//]: # (Enclose links to things related to the bug using http://wowhead.com or any other TBC database.)
[//]: # (You can use screenshot ingame to visual the issue.)
[//]: # (Write your tickets according to the format:)
[//]: # ([Quest][Azuremyst Isle] Red Snapper - Very Tasty!)
[//]: # ([NPC] Magistrix Erona)
[//]: # ([Spell][Mage] Fireball)
[//]: # ([Npc][Drop] Ghostclaw Lynx)
[//]: # ([Web] Armory doesnt work)
[//]: # (To find server revision type `.server info` command in the game chat.)

**Description**: Trap detection range is much larger than it was on retail

**Current behaviour**: Trap detection range is HUGE, you can see traps from very far away, 20+ yards.

**Expected behaviour**: Trap detection range should be equal or shorter than trigger radius 

Source: https://www.youtube.com/watch?v=hS82JzE6F0I&feature=youtu.be&t=410
If you watch the duel closely, the druid trigger multiple traps and is not able to see traps at all, however, at the 8 minutes, 30 seconds mark, the hunter laid down a trap right next to the druid and the druid is able to see it.

Also bringing another important issue is that the trap trigger radius on this server is much shorter than it was on retail, I already reported on beta almost 4 months ago: #3649

**Server Revision**: 2912

**Comment by Wolffenstein** [comment]
Fixed in rev 3536.
