### ISSUE TITLE
Snapshotting does not work per 01.04.19

### ISSUE THREAD

**Issue by Vertacy** [Atlantiss/NetherwingBugtracker#5532]
**Description**:  Core Issue

**Current behaviour**: As per today, 01.04.2019, (warlock and priest tested) DoTs do not work properly as they dynamically update with the casters spellpower/+%dmg buffs ( only tested with priest shadow form).

How to replicate: apply corruption to a mob and track the first tick, use a +spellpower trinket after the 1st tick. The 2nd tick will be updated accordingly with/to the trinket. Manually remove the trinket buff/aura and the 3rd tick will be updated again to the initial tick value.

**Expected behaviour**: As Evolvee correctly stated a few months ago (https://github.com/Atlantiss/NetherwingBugtracker/issues/3435) dots should take "a picture" of the Spellpower/attackpower and +%dmg modifier buffs (tricks of the trade, shadowform, paladin vengeance, ...) as their basis when applied to a target while dynamically changing with debuffs (e.g. Magtheridon/Curator channel). 

Example: Baseline Corruption doing 100 dmg per tick no matter what buffs you get after the application of the debuff. If, however, you were to pop a trinket and got tricks of the trade from a rogue before applying the corruption the dmg should be e.g. 125 dmg per tick for the entire duration even after tricks or the trinket fall off.

Possible reference points:
https://youtu.be/l9HcaDHmJFU?t=69 its a vanilla video but the mechanic worked the same until patch 3.3
https://youtu.be/jj6lKBTlmoI?t=1190 tbc paladin pvp video

**Server Revision**: 2923

**Comment by Wolffenstein** [comment]
Fixed in rev 2924.
