### ISSUE TITLE
[Dungeon][SHH][Event] SHH hall event didnt work properly

### ISSUE THREAD

**Issue by Dragunovka** [Atlantiss/NetherwingBugtracker#5533]
Hey dudes. SHH hall event didnt work propetly on your server right now, broken for 1 week i think, too bad u guys didnt watch players party runs sometimes. So problem is - hall event starts only at the end or the hall, not from beginning when u enter hall room. Muh blizzlike guys.

**Comment by Wolffenstein** [comment]
Yeah too bad we don't have time to sit on our asses and just watch players do dungeons.

I don't know what you mean by "end of the hall". A video would be nice (nothing was changed in SHH event code).

**Comment by Kolmarwow** [comment]
he's talking about the archer event right after 1st boss. currently the scout that's supposed to run through the gauntlet yelling something like "HOOOOOLD THE LINE, DO NOT LET THEM THROUGH!" will only start running once you reach the end of the gauntlet.

**Comment by Wolffenstein** [comment]
Should be fixed now.

**Comment by Dragunovka** [comment]
thx anyway
