### ISSUE TITLE
[Quest][Stranglethorn Vale] **[Supplies to Private Thorsen]**

### ISSUE THREAD

**Issue by EmerisEB** [Atlantiss/NetherwingBugtracker#5534]
[Quest][Stranglethorn Vale] **[Supplies to Private Thorsen]**
[NPC] Private Thorsen
[Spell] N/A
[Web] NPC is bugged. You cannot turn in the quest. There is no pending question mark on him.

**Comment by Tenoutoften** [comment]
Other reports on this NPC:
https://github.com/Atlantiss/NetherwingBugtracker/issues/4368
https://github.com/Atlantiss/NetherwingBugtracker/issues/1137
https://github.com/Atlantiss/NetherwingBugtracker/issues/797

**Comment by leeviathan** [comment]
I also cannot complete this quest. I waited for Private Thorsen to complete his route and he still would not complete the quest once he was back in the Rebel Camp. Level 31
