### ISSUE TITLE
[Website] Cannot setup 2FA as no barcode is generated

### ISSUE THREAD

**Issue by danbopes** [Atlantiss/NetherwingBugtracker#5537]
**Description**: 
Currently cannot setup 2-factor authentication via the website, as the barcode is not generating correctly for me to scan via my 2FA app.

**Current behaviour**:
![](https://i.imgur.com/ZgN6bZ1.png)

Looking at the DOM via inspector reveals an invalid image is attempting to be loaded:
![](https://i.imgur.com/whK07ur.png)

**Expected behaviour**: 
A barcode should appear.

**Comment by Emtec** [comment]
Fixed, thank for your report!
