### ISSUE TITLE
[Scholomance] Jandice Barov clones don't despawn

### ISSUE THREAD

**Issue by mn142** [Atlantiss/NetherwingBugtracker#5538]
[//]: # (Enclose links to things related to the bug using http://wowhead.com or any other TBC database.)
[//]: # (You can use screenshot ingame to visual the issue.)
[//]: # (Write your tickets according to the format:)
[//]: # ([Quest][Azuremyst Isle] Red Snapper - Very Tasty!)
[//]: # ([NPC] Magistrix Erona)
[//]: # ([Spell][Mage] Fireball)
[//]: # ([Npc][Drop] Ghostclaw Lynx)
[//]: # ([Web] Armory doesnt work)
[//]: # (To find server revision type `.server info` command in the game chat.)

**Description**: 
Tried to solo Jandice Barov in Scholomance as a level 70 resto druid.
**Current behaviour**:
She spawns her illusions, however they never despawn. This causes the room to fill with an excessive amount of illusions.

**Expected behaviour**: 
Her illusions should despawn after 10-15 seconds (?), before spawning new illusions, and thus keeping the illusions at a normal amount.

Video of it working correctly (13:00): [https://www.warcraftmovies.com/movieview.php?id=116709]

**Server Revision**: 
2927

**Comment by Evolvee** [comment]
rev 2929
