### ISSUE TITLE
Unable to turn in Quests with items that were Banked at any time.

### ISSUE THREAD

**Issue by Zaltec** [Atlantiss/NetherwingBugtracker#5539]
[//]: # (Enclose links to things related to the bug using http://wowhead.com or any other TBC database.)
[//]: # (You can use screenshot ingame to visual the issue.)
[//]: # (Write your tickets according to the format:)
[//]: # ([Quest][Azuremyst Isle] Red Snapper - Very Tasty!)
[//]: # ([NPC] Magistrix Erona)
[//]: # ([Spell][Mage] Fireball)
[//]: # ([Npc][Drop] Ghostclaw Lynx)
[//]: # ([Web] Armory doesnt work)
[//]: # (To find server revision type `.server info` command in the game chat.)

**Description**: After taking quest items out of bank unable to turn in Quest.

**Current behaviour**: Any banked quest item will not read as in inventory and therefore you cannot turn in.  Quests are labelled as grey but in log listed as Completed

**Expected behaviour**: Should be able to turn in quest.

**Server Revision**: ?

**Comment by Drayo** [comment]
Put the items into the bank, relog and take them both out. After that you can turn in the quest.

 I tried reproducing this, but I can't get it to bug out.
