### ISSUE TITLE
Imp Minion under Goldshire Inn is aggresive

### ISSUE THREAD

**Issue by Notmittz** [Atlantiss/NetherwingBugtracker#554]
**Description**: 
The Imp Minion, located next to Cylina Darkheart <Demon Trainer>, who is in the basement of the Goldshire inn will attack players (or at least attacked my warlock)

**Current behaviour**:
It's acting like a wild imp, instead of a passive npc minion

**Expected behaviour**: 
Stand there and look pretty, not be able to be attacked or attack players

**Comment by Evolvee** [comment]
rev 2538
