### ISSUE TITLE
[Spell][Priest] proccing on low level lasthits

### ISSUE THREAD

**Issue by b15andga** [Atlantiss/NetherwingBugtracker#5540]
[//]: # (Enclose links to things related to the bug using http://wowhead.com or any other TBC database.)

[//]: # (You can use screenshot ingame to visual the issue.)
[//]: # (Write your tickets according to the format:)
[//]: # ([Quest][Azuremyst Isle] Red Snapper - Very Tasty!)
[//]: # ([NPC] Magistrix Erona)
[//]: # ([Spell][Mage] Fireball)
[//]: # ([Npc][Drop] Ghostclaw Lynx)
[//]: # ([Web] Armory doesnt work)
[//]: # (To find server revision type `.server info` command in the game chat.)

**Description**: 
http://db.hellfire-tbc.com/?spell=15270
"Gives you a 20/40/60/80/100 % chance to gain a 100% bonus to your Spirit after killing a target that yields experience or honor"
**Current behaviour**:
Spirit Tap activated on lasthits in Uldaman, where the caster was level 70 and the mobs were around level 40 and gray, not giving any experience nor honor.
https://imgur.com/a/C8xDyrA
**Expected behaviour**: 
Spirit Tap should only activate after lasthits on targets that yield experience (or would have if it wasn't for levelcap) or honor. Not gray mobs.
**Server Revision**: 
2928

**Comment by teddys** [comment]
It procs only if you are in a party with someone that gets the experience. If you do the kill solo, it won't proc .. it's strange. Anyway it's the same with victory rush

**Comment by Wolffenstein** [comment]
Fixed in rev 2933.
