### ISSUE TITLE
[Warrior][Talent] Unbridled Wrath threat generation

### ISSUE THREAD

**Issue by Easyfraggy** [Atlantiss/NetherwingBugtracker#5541]
**Description**: 

Cannot find enough info on this to make conclusion - I have checked over 50 guides mentioning Unbridled Wrath - not a single one mentions it generating threat.

https://web.archive.org/web/20160801184924/http://blue.mmo-champion.com/topic/18607-how-do-aggro-and-threat-work-in-wow/

Mentions that passive abilities do not generate threat (for example Anger Management) but is Unbridled Wrath considered passive?

Cannot find any mention of rage generation in threat 2.0 lib causing threat however that is known to be false in the case of Bloodrage and Improved Berserker Rage.

**Current behaviour**:
Unbridled Wrath generates 5 threat per proc (non modified - always pure 5)

**Expected behaviour**: 
Unbridled Wrath does not generate 5 threat per proc.

**Server Revision**:

**Comment by Godmatik** [comment]
Tried to do some research but yeah I have no clue, even with classic data available.

Low prio - but someone will need to confirm.

**Comment by Godmatik** [comment]
Effect is so minor and I doubt anyone is going to ever find proof, closing for now
