### ISSUE TITLE
[quest][Mulgore] Taming the beast

### ISSUE THREAD

**Issue by 2knew** [Atlantiss/NetherwingBugtracker#5542]
**Description**: 
unable to complete the final stage of 'Taming The Beast' in Mulgore

**Current behaviour**:
The first two phases of the quest work correctly.  The last phase of the 'taming the beast' quest is broken. You need to tame a swoop. It naturally 'swoops' on you, breaking the tame

1.  Engaging the swoop and taming after the swoop does not work. The CD on swoop is way too quick.
2. Using really sticky glue, even at range, is not working either. The 10 seconds of CC ends, the swoop closes and knocks you on your ass before finishing the tame.
3. Just blindly redoing the quest over and over ought to get you by by having the swoop miss, but after about 20 attempts, this hasn't worked for me.

**Expected behaviour**: 
player should be able to tame the required quest animal.

**Server Revision**: 
rev: 2928 patch: 203

**Comment by Evolvee** [comment]
increased CD on the CC for npc "Swoop"
