### ISSUE TITLE
[Arena] 2v2 wrong stats 

### ISSUE THREAD

**Issue by Actionrizzl** [Atlantiss/NetherwingBugtracker#5546]
Hello team, i wrote a gmticket yesterday that got answered today saying i should talk to a dev since he cant fix that.  Issue is  that im on a 2v2team with a friend ( my name rizzl dwarf priest and alright human rog - teamname is "OMG LASERGUNS  PEW PEW" ) we played all games together and have not invited a 3rd person to the team but somehow team win lose is different to our stats and our stats are not the same either . can this be fixed smh? thanks for your time

**Comment by gunzbngbng** [comment]
It happens when you leave an arena before it ends.

Also, I like your team name.

**Comment by Actionrizzl** [comment]
hehe thx dude ! 
but it results in 3 different ratings fucking over all mmr it feels like ... we up/down atleast 10 or more games

**Comment by gunzbngbng** [comment]
Yes.  It affects personal, but my understanding is that mmr is no longer part of the matchmaking or points per game.

**Comment by Actionrizzl** [comment]
thing is we'd have to push our team to like 2.150 or even 2.2k to get our personal to weaponrating or how else would it work ?

**Comment by teddys** [comment]
it's because when you leave a game you lose twice xD

**Comment by teddys** [comment]
this can be now closed
