### ISSUE TITLE
[Dungeon] BRD Stuck in combat from fire in Magmus room

### ISSUE THREAD

**Issue by Haipethdev** [Atlantiss/NetherwingBugtracker#5547]
[//]: # (Enclose links to things related to the bug using http://wowhead.com or any other TBC database.)
[//]: # (You can use screenshot ingame to visual the issue.)
[//]: # (Write your tickets according to the format:)
[//]: # ([Quest][Azuremyst Isle] Red Snapper - Very Tasty!)
[//]: # ([NPC] Magistrix Erona)
[//]: # ([Spell][Mage] Fireball)
[//]: # ([Npc][Drop] Ghostclaw Lynx)
[//]: # ([Web] Armory doesnt work)
[//]: # (To find server revision type `.server info` command in the game chat.)

**Description**: 

If hit by fire in Magmus' room, you will get stuck in combat until you leave the instance all together.  It does not reset.

**Current behaviour**:

**Expected behaviour**: 

Combat ends after the fight, being struck by the fire after he is dead should only put you in combat momentarily.

**Server Revision**:

**Comment by Evolvee** [comment]
https://github.com/Atlantiss/NetherwingBugtracker/issues/4308 duplicate
