### ISSUE TITLE
[Website]Race change character model selector broken

### ISSUE THREAD

**Issue by Rampagingfungus** [Atlantiss/NetherwingBugtracker#5549]
![unknown (1)](https://user-images.githubusercontent.com/49215678/55444453-16d04680-55e9-11e9-83c8-7b8659d94eaa.png)
![unknown](https://user-images.githubusercontent.com/49215678/55444454-1768dd00-55e9-11e9-913e-6a24ee4a32fe.png)

**Description**: 
The Tauren male character model on the website's race change module is not visible aside from one bit of hair, meaning you can't select its appearance. I've used three separate devices with updated java (including mobile) and four up-to-date browsers with the cache cleared so definitely a website issue.

Find attached screenshots of the issue from two different browsers.
 
**Current behaviour**:
As above
**Expected behaviour**: 
Working like the other models

**Comment by Emtec** [comment]
Fixed. Thank for your report!
