### ISSUE TITLE
Satyr Horns

### ISSUE THREAD

**Issue by Trix115** [Atlantiss/NetherwingBugtracker#555]
Killing Satyrs at Night Run in Ashenvail for the quest "Satyr Horns" and i've gotten 0 horns after 10-15 kills, from what i can remember they should have a high drop chance.

https://tbc-twinhead.twinstar.cz/?quest=6441

*Edit 20 kills later and still no horns, definitely not dropping
*Edit moved over to Satyrnaar and here they seem to be dropping. But they should be dropping at Night Run as well

**Comment by aresbrutus** [comment]
They do drop there but the drop rate was way too low. Will be corrected in one of the next updates.

**Comment by aresbrutus** [comment]
Yes, they are included.
