### ISSUE TITLE
Bugged hit rating

### ISSUE THREAD

**Issue by Phoquedtotm** [Atlantiss/NetherwingBugtracker#5550]
[//]: # (Enclose links to things related to the bug using http://wowhead.com or any other TBC database.)
[//]: # (You can use screenshot ingame to visual the issue.)
[//]: # (Write your tickets according to the format:)
[//]: # ([Quest][Azuremyst Isle] Red Snapper - Very Tasty!)
[//]: # ([NPC] Magistrix Erona)
[//]: # ([Spell][Mage] Fireball)
[//]: # ([Npc][Drop] Ghostclaw Lynx)
[//]: # ([Web] Armory doesnt work)
[//]: # (To find server revision type `.server info` command in the game chat.)

**Description**:  After the server reset last night my hit rating has been bugged. The game will not pick up on the 28 hit rating from my legs and 2 out of 16 hit rating from my cape

**Current behaviour**:  My stats are showing me 144 hit rating with all of my gear on when I take my pants off my hit rating does not change at all and as stated above that is 28 hit rating that I am missing. My cape is also not registering 2 out of the 16 hit rating that it is supposed to give. My pants register the +4 hit rating gem I socketed but it will not register the base hit rating stat that is on them

**Expected behaviour**:  I should have in total 174 hit rating with all of my gear on. I have done the math multiple times. As shown in the pictures below when i take my gear off the hit rating does not change or if it does it is not the correct amount 
![WoWScrnShot_040219_174737](https://user-images.githubusercontent.com/49206362/55444940-be0f9800-556d-11e9-810c-976cc5f520dc.jpg)
![WoWScrnShot_040219_174747](https://user-images.githubusercontent.com/49206362/55444951-c36ce280-556d-11e9-86a9-f2268fba1401.jpg)
![WoWScrnShot_040219_174751](https://user-images.githubusercontent.com/49206362/55444955-c7990000-556d-11e9-84c2-c94d81505e00.jpg)
![WoWScrnShot_040219_174758](https://user-images.githubusercontent.com/49206362/55444958-cb2c8700-556d-11e9-9fce-7049bdf2bb34.jpg)

**Server Revision**: 2928

**Comment by Regimant** [comment]
Clear your cache, those arent the stats on those items.

**Comment by Phoquedtotm** [comment]
which item the "skulker's greaves"?

**Comment by Phoquedtotm** [comment]
everywhere I look online it says that BOTH items have the right stats. Why would they not be?

**Comment by Evolvee** [comment]
so did you clear cache?

**Comment by Phoquedtotm** [comment]
yes and it came up as dodge instead of hit rating and it was 23 dodge which doesn't make sense

**Comment by Evolvee** [comment]
2.0 items

**Comment by Phoquedtotm** [comment]
I just looked through all of the TBC patch notes and didn't see any changes to them. Could you link the patch when it does change?

**Comment by Evolvee** [comment]
u need to browse through archives if u want to find item changes for example https://web.archive.org/web/20070513105027/http://wow.allakhazam.com/db/item.html?witem=28741

**Comment by Phoquedtotm** [comment]
Ok. well i guess that makes sense but if you are going to change it to those stats then can you change the attack power as well? Cause its still showing up at 64 when the link you posted says it should be at 56 attack power. That still doesn't make sense... you know?

**Comment by Evolvee** [comment]
i dont think this is a correct timestamp history of 2.0.3, i just gave u random webarchive link i found in history

if you think, something is not correct tho, make a new report pls(with evidence)
