### ISSUE TITLE
[Dungeon][NPC][Drop] Carrion swarmer item pool fix

### ISSUE THREAD

**Issue by ghertruda** [Atlantiss/NetherwingBugtracker#5551]
[//]: # (Enclose links to things related to the bug using http://wowhead.com or any other TBC database.)
[//]: # (You can use screenshot ingame to visual the issue.)
[//]: # (Write your tickets according to the format:)
[//]: # ([Quest][Azuremyst Isle] Red Snapper - Very Tasty!)
[//]: # ([NPC] Magistrix Erona)
[//]: # ([Spell][Mage] Fireball)
[//]: # ([Npc][Drop] Ghostclaw Lynx)
[//]: # ([Web] Armory doesnt work)
[//]: # (To find server revision type `.server info` command in the game chat.)

**Description**: Carrion swarmer mobs (in dire maul north) item pool does not allow them to be skinnable.
It is the fastest way for skinners to farm rugged leather so i would really like to see this fixed.

**Current behaviour**: Mob is not skinnable.

**Expected behaviour**: Mob should be skinnable - Link to a DB : https://db.excalibur.ws/?npc=13160#drop

**Server Revision**: 2928

**Comment by The14me** [comment]
DM in general needs a full rework at some point.
