### ISSUE TITLE
Deathcoil breaks on damage (often breaks when shadowburning while deathcoiled)

### ISSUE THREAD

**Issue by gladwrap** [Atlantiss/NetherwingBugtracker#5554]
[//]: # (Enclose links to things related to the bug using http://wowhead.com or any other TBC database.)
[//]: # (You can use screenshot ingame to visual the issue.)
[//]: # (Write your tickets according to the format:)
[//]: # ([Quest][Azuremyst Isle] Red Snapper - Very Tasty!)
[//]: # ([NPC] Magistrix Erona)
[//]: # ([Spell][Mage] Fireball)
[//]: # ([Npc][Drop] Ghostclaw Lynx)
[//]: # ([Web] Armory doesnt work)
[//]: # (To find server revision type `.server info` command in the game chat.)

**Description**: 
Deathcoil breaking on damage, I've noticed it almost breaks 100% of the time if you shadowburn once deathcoil is applied. This is totally busted. It looks like it is overriding the debuff and ending the horror effect.
**Current behaviour**:
Deathcoil randomly breaks on damage. Deathcoil always breaks after shadow burning a target when the horror is applied. Horror is overridden perhaps?
**Expected behaviour**: 
Deathcoil cannot break on damage no matter what.
**Server Revision**:

**Comment by gladwrap** [comment]
Is it possible that deathcoil is scripted as a fear not a horror? Shouldn't break unless you bubble or trinket.

**Comment by Easyfraggy** [comment]
should be fixed after next update.
