### ISSUE TITLE
Getting kicked from my guild everytime i disconnects #2

### ISSUE THREAD

**Issue by Naarue** [Atlantiss/NetherwingBugtracker#5555]
[//]: # (Enclose links to things related to the bug using http://wowhead.com or any other TBC database.)
[//]: # (You can use screenshot ingame to visual the issue.)
[//]: # (Write your tickets according to the format:)
[//]: # ([Quest][Azuremyst Isle] Red Snapper - Very Tasty!)
[//]: # ([NPC] Magistrix Erona)
[//]: # ([Spell][Mage] Fireball)
[//]: # ([Npc][Drop] Ghostclaw Lynx)
[//]: # ([Web] Armory doesnt work)
[//]: # (To find server revision type `.server info` command in the game chat.)

**Description**: Hi, i get kicked from my guild every time i disconnects from the game,

**Current behaviour**:
![image](https://user-images.githubusercontent.com/49115717/55494513-31331000-563b-11e9-9a79-f69029e03d15.png)

**Expected behaviour**: don't getting kicked every time i dc.
![bugg](https://user-images.githubusercontent.com/49115717/55494681-85d68b00-563b-11e9-90b3-49b3cc6d14db.png)

**Server Revision**: 
![image](https://user-images.githubusercontent.com/49115717/55494560-47d96700-563b-11e9-8f1c-1cd545f23e58.png)

**Comment by Wolffenstein** [comment]
You didn't give your character name.

**Comment by Naarue** [comment]
Character name : Naarue
Guild name : VOSTFR

**Comment by Wolffenstein** [comment]
Fixed.
