### ISSUE TITLE
WoW Error Taure Druid

### ISSUE THREAD

**Issue by skydron** [Atlantiss/NetherwingBugtracker#5556]
![grafik](https://user-images.githubusercontent.com/13602527/55495505-54f75580-563d-11e9-8e4b-a44e59ffee4d.png)

**Description**: 
Sometimes after closing client (Alt + F4 / Exit Game) directly (+-2min) after a fight i cant login to my char for some minutes... All the time i got WoW Error. I ready the problem at other Druids horde too. Maybe Taure Druid problem? 
However its only on this server. 

Tryed to clear cache / WTF / reset interface / other client / other PC ... Fact: Its the Character.

Most time i got fixed by talking to GM at Discord Support channel. 

Please investigate.

**Comment by The14me** [comment]
Cant reproduce.
