### ISSUE TITLE
[Quest] NPC Miran for quest After the Ambush not at correct location

### ISSUE THREAD

**Issue by danbopes** [Atlantiss/NetherwingBugtracker#5557]
**Description**: 
Player had an issue with [After the Ambush](https://www.wowhead.com/quest=454/after-the-ambush) quest. After picking up the quest, [Miran](https://www.wowhead.com/npc=1379/miran) should have been at the cart next to Huldar ~52,69. His spawn point is correct, but his actual location in the world was near some tents by Ironband's Excavation Site.

**Current behavior**:
He may have been bugged during an escort quest, which caused him not to respawn at his correct location. He was docile, and appeared to be attackable/normal NPC.

**Expected behavior**: 
He should have been by his cart at ~52,69.

**Server Revision**: 
2928

**Comment by GMThunderan** [comment]
Still ongoing.

**Comment by Ehremir** [comment]
This is still an issue on the new server.

**Comment by Godmatik** [comment]
#9028
