### ISSUE TITLE
Leaving an arena match makes it so you lose twice

### ISSUE THREAD

**Issue by teddys** [Atlantiss/NetherwingBugtracker#5558]
**Current behaviour**: When you leave the arena, you get 2 losses

**Expected behaviour**:  When you leave the arena, you get 1 loss

**Server Revision**: 2928

**Comment by Wolffenstein** [comment]
Fixed in rev 2931.

**Comment by teddys** [comment]
2947

not fixed

**Comment by teddys** [comment]
Still not fixed

**Comment by Wolffenstein** [comment]
Fixed in rev 2990.
