### ISSUE TITLE
[warrior][ability] Intimidating shout

### ISSUE THREAD

**Issue by teddys** [Atlantiss/NetherwingBugtracker#5559]
**Description**: https://youtu.be/BKqWxkKw8VI?t=69
https://wowwiki.fandom.com/wiki/Intimidating_Shout = no changes regarding the necessity to face your target while casting intimidating shout so if it worked like this in mop, it worked the same way in TBC

**Current behaviour**: Intimidating shout requires you to face the target you are trying to fear

**Expected behaviour**:  Intimidating shout should not require you to face the target you want to cast it on

**Server Revision**:  2928

**Comment by teddys** [comment]
https://github.com/Atlantiss/NetherwingBugtracker/issues/3944 it was already reported btw

**Comment by Wolffenstein** [comment]
Fixed in rev 2931.

**Comment by Tenoutoften** [comment]
Both of these other reports have several players claiming you need to face the target. Do you have video evidence that you can use it on someone behind you?

**Comment by Easyfraggy** [comment]
As I also mentioned to wolf when i saw the changelog - MoP video is not proof for tbc.

**Comment by teddys** [comment]
Literally one person said that it's supposed to be like that. Why would you even assume so? Post me proof that it should only be castable if the target is in front of you .... it makes no sense

**Comment by Easyfraggy** [comment]
https://wowwiki.fandom.com/wiki/Intimidating_Shout?oldid=936942

**Comment by teddys** [comment]
No, the fear remains clicked until it goes off, your picture shows the situation AFTER the fears go off .. not when it is used, watch the video again
on the matter of "low fps and not from retail" I rather won't comment

**Comment by Easyfraggy** [comment]
Dude this is when he pushes the button:

![image](https://user-images.githubusercontent.com/36134067/55680212-f1a84480-5916-11e9-8d64-c279501e4787.png)

This is when golden delay ends: (server accepts the cast):

![image](https://user-images.githubusercontent.com/36134067/55680221-0a185f00-5917-11e9-99bf-5a1dc5b91b22.png)

This is when the fear is applied (debuff)

![image](https://user-images.githubusercontent.com/36134067/55680227-26b49700-5917-11e9-81b7-3d66b6a58773.png)

Wikis from august are during wotlk beta where they already change a ton of things on wikis to prepare for it. Even in late July wiki still reflects. https://wowwiki.fandom.com/wiki/Intimidating_Shout?oldid=1549074

Removal from a wiki also doesn't nessesarily mean it was changed. It is after all editable by regular people.

The fact that someone specificly wrote this:

"To use this spell you must have a target which you are facing, it is not 360 degrees and cannot be used like Psychic Scream."

Is way more solid than the absence of mention.

**Comment by Wolffenstein** [comment]
It never had SPELL_FACING_FLAG_INFRONT flag in client data, so I'm gonna trust it over the wowwiki entry.
