### ISSUE TITLE
Swapping targets with wand

### ISSUE THREAD

**Issue by nycheia** [Atlantiss/NetherwingBugtracker#556]
**Description**: 
This bug is about swapping wand targets while wanding. This is for swapping to enemies, but also to friendly targets. 

**Current behaviour**:
When you are wanding an enemy, and then swaps to a friendly target, it will still shoot the wand at the friendly target (even gain skill ups) and it will be shown as the target is 'Evading'. 
https://prnt.sc/kym84y

When you wand an enemy and then swap to an enemy target, it will do the same, except it will continue to say it deals damage, but it wont actually do any damage, even though the combat logs suggests that it does. 
https://prnt.sc/kym8mf

**Expected behaviour**: 
Shouldnt be able to swap to friendly targets, and its supposed to do damage when swapping to enemy targets. 

**Server Revision**: 
19:20 CEST 25-09-2018

**Comment by Wolffenstein** [comment]
Fixed in rev 2052.
