### ISSUE TITLE
[Spell][Paladin] Blessing of Light

### ISSUE THREAD

**Issue by Saronitian** [Atlantiss/NetherwingBugtracker#5560]
[//]: # (Enclose links to things related to the bug using http://wowhead.com or any other TBC database.)
[//]: # (You can use screenshot ingame to visual the issue.)
[//]: # (Write your tickets according to the format:)
[//]: # ([Quest][Azuremyst Isle] Red Snapper - Very Tasty!)
[//]: # ([NPC] Magistrix Erona)
[//]: # ([Spell][Mage] Fireball)
[//]: # ([Npc][Drop] Ghostclaw Lynx)
[//]: # ([Web] Armory doesnt work)
[//]: # (To find server revision type `.server info` command in the game chat.)

**Description**: 
This is related to #5318 and #3460 Where The Skill Blessing of Light does not give the correct Amount of Bonus healing to Holy Light and Flash of Light.
Libram of Souls Redeemed should buff the Blessing and increase the Bonus healing of the Blessing.

https://wowwiki.fandom.com/wiki/Blessing_of_Light
https://www.wowhead.com/item=28592/libram-of-souls-redeemed#comments:id=68367

https://theholylight.wordpress.com/2007/07/10/paladin-healing/
This Article was writen on the July 10, 2007 it describes the Healing reduction of Blessing of Light on lower Ranks as 

> At very low ranks, Blessing of Light does apply a downranking coefficient to its bonus healing but it is not particularly noticeable until Holy Light 4

-sadly I could not find any Informations on how much less it would be. I could maybe get the Values from ingame and the Addon Dr.Damage to figure it out.

> The addition granted by BoL is added at the end, after all other modifiers, and cannot be increased.

this screenshot shows that I healed way less than the minimum of my crits should be.

![WoWScrnShot_040419_063426](https://user-images.githubusercontent.com/49236238/55530069-ba326180-56a4-11e9-93fb-7b1a7f23d030.jpg)

**Current behaviour**:
Blessing of Light's Bonus Healing gets reduced by the casttime of the Heal used. with a multiplier of 1.5/3.5 for Flash of Light and 2.5/3.5 for Holy light, like any +healing on equipment does.

The Bonus Healing from Blessing of Light does not scale with the 12% Bonus healing on Holy Light and Flash of Light from the Talent  [Healing Light]

**Expected behaviour**: 
Blessing of Light should always give the maximum amount of Bonus Healing to the cast after all multiplier and Libram of Souls Redeemed should just buff the Blessing to increase the Bonus Healing of it.

The Bonus Healing did scale with the 12% increased Healing done by Holy Light and Flash of light from the Talent  [Healing Light]  on retail. But it was a bug cause it should not.

**Server Revision**: 
2930

**Comment by Saronitian** [comment]
I just took the Numbers DrDamage gives after looking at the Math behind it
https://docs.google.com/spreadsheets/d/18TZ4l55MRmNCcVUF9IdACNu2SEtT1slGE15OdYzqWXk/edit?usp=sharing

in this Document are the Multiplier / Bonus Healing done from BoL for the different Ranks of Healing spells.

The Part at the Bottom is the influence of the Talent. Apperently DrDamage gives the base 580 Bonus / 185 Bonus healing the 12% Bonus from the Talent but not for the Extra Healing done from the Libram.
it should either give the 12% to both or non of the 2 cause they are the same thing. I Could not reliable test how it currently behaves on this server but It's up to You how you want to implement this "bug".


I would really like a Fix for this Problem cause currently we are missing out on 500 flat healing done by Holy Light, that is not a small amount.

If I should do more research please say so I can help to fix it.

**Comment by sifiuocz** [comment]
Please fix this. Its a big deal for all holy paladins.

**Comment by Wolffenstein** [comment]
Fixed in rev 2935.
