### ISSUE TITLE
[NPC][Quest][Netherstorm]An Audience with the Prince, Image of Nexus-Prince Haramad

### ISSUE THREAD

**Issue by Dragunovka** [Atlantiss/NetherwingBugtracker#5563]
Hey, "respawn" time of the quest npc Image of Nexus-Prince Haramad (https://www.wowhead.com/quest=10268/an-audience-with-the-prince) is broken. Should have ~8 min respawn (https://www.wowhead.com/npc=20084/image-of-nexus-prince-haramad#comments:id=2009089)

http://i.piccy.info/i9/84907287fffd6c566fe76f0d63f74341/1554365508/344582/1309060/WoWScrnShot_040419_110615.jpg

fix, i cant quest.

#5301
#5268

**Comment by Evolvee** [comment]
its a respawn core issue, nothing related to this particular npc or quest

**Comment by Zebhor** [comment]
Nexus-Prince Haramad is bugged and doesnt show up if someone complete quest or evade him durning combat. Last time he wasnt there 18hours+

**Comment by Evolvee** [comment]
^^
