### ISSUE TITLE
[NPC] [proffesion] [Engineering] "pets" doesn't work or have a functioning AI

### ISSUE THREAD

**Issue by zkillertheman** [Atlantiss/NetherwingBugtracker#5565]
[//]: # (Enclose links to things related to the bug using http://wowhead.com or any other TBC database.)

**Description**: 
(tested) Gnomish Flame Turret and Gnomish Battle Chicken are both spawned in at level 1 with no AI, they just try to melee whatever target they can find, without success since they're level 1!

**Expected behaviour**: 
Pets summoned should be the same level as the summoner, aka 70 @ lvl 70. 
Gnomish Battle Chicken should also have a chance on hit to give the group Battle Squawk buff for 5mins
Gnomish Flame Turret should be a ranged attacking turret that is unable to move. it currently follows a target around in melee range, also should be same level as summoner (70 @ lvl 70)

**Server Revision**:

**Comment by Evolvee** [comment]
https://github.com/Atlantiss/AtlantissTBCBT/issues/3593

**Comment by Unrelented** [comment]
Bump~
This is bothering a lot of people who invested in one of the most fascinating professions of the entire expansion. To be the best level 70 server we need to be a complete experience, thank you <3

**Comment by The14me** [comment]
https://github.com/Atlantiss/NetherwingBugtracker/issues/3809
https://github.com/Atlantiss/NetherwingBugtracker/issues/6265
https://github.com/Atlantiss/NetherwingBugtracker/issues/5347
https://github.com/Atlantiss/NetherwingBugtracker/issues/5714
https://github.com/Atlantiss/NetherwingBugtracker/issues/5463
https://github.com/Atlantiss/NetherwingBugtracker/issues/4767
https://github.com/Atlantiss/NetherwingBugtracker/issues/2882

**Comment by Teakane** [comment]
Can confirm that as of writing this comment, the Flame Turret at least doesn't work as intended.

Vid on how it should work: https://youtu.be/qawuMAd0XuE?t=22

**Comment by BokChoyWarrior** [comment]
Would still like to see this fixed, the haste buff from chicken could really help my guild in raids :) and the Flame Turret would also be nice in MH.

**Comment by Godmatik** [comment]
Can be closed, was fixed
