### ISSUE TITLE
[Raid][Karazhan] - The Curator can be disarmed.

### ISSUE THREAD

**Issue by Firroth** [Atlantiss/NetherwingBugtracker#5566]
[NPC] [The Curator](https://www.wowhead.com/npc=15691/the-curator)

**Current behaviour**:
You can use disarm on him, even though he doesn't wield weapon. His damage is affected then too, hitting for 100-200dmg on t4 tank.

**Expected behaviour**: 
Since he doesn't wield weapon, he shouldn't be able to be disarmed.

**Server Revision**: 
 2930

**Comment by Evolvee** [comment]
rev 2932
