### ISSUE TITLE
[Item] Fused Wiring drops from wrong mobs.

### ISSUE THREAD

**Issue by bekonja** [Atlantiss/NetherwingBugtracker#5567]
[//]: # (Enclose links to things related to the bug using http://wowhead.com or any other TBC database.)
[//]: # (You can use screenshot ingame to visual the issue.)
[//]: # (Write your tickets according to the format:)
[//]: # ([Quest][Azuremyst Isle] Red Snapper - Very Tasty!)
[//]: # ([NPC] Magistrix Erona)
[//]: # ([Spell][Mage] Fireball)
[//]: # ([Npc][Drop] Ghostclaw Lynx)
[//]: # ([Web] Armory doesnt work)
[//]: # (To find server revision type `.server info` command in the game chat.)

**Description**: 

**Current behaviour**:
https://db.excalibur.ws/?item=7191 Item

https://www.wowhead.com/npc=2673/target-dummy#comments
https://www.wowhead.com/item=7191/fused-wiring#comments
https://www.wowhead.com/item=4366/target-dummy#comments
old pre-bc and early-bc comments describing their drop rules

**Expected behaviour**: 
You need to remove entries 10319 to 12897 included since they are not mechas and shouldnt be eligible to drop wirings.
You need to add entries 2673, 2674 and 12426 (all types of target dummies) and assign 15% droprate to them.

**Server Revision**: 
2930

**Comment by Evolvee** [comment]
rev 2930
