### ISSUE TITLE
[Quest] Bitter Rivals

### ISSUE THREAD

**Issue by sonikozerg** [Atlantiss/NetherwingBugtracker#5569]
[//]: # (Enclose links to things related to the bug using http://wowhead.com or any other TBC database.)
[//]: # (You can use screenshot ingame to visual the issue.)
[//]: # (Write your tickets according to the format:)
[//]: # ([Quest][Azuremyst Isle] Red Snapper - Very Tasty!)
[//]: # ([NPC] Magistrix Erona)
[//]: # ([Spell][Mage] Fireball)
[//]: # ([Npc][Drop] Ghostclaw Lynx)
[//]: # ([Web] Armory doesnt work)
[//]: # (To find server revision type `.server info` command in the game chat.)

**Description**: Having issues with Bitter Rivals ( the link https://tbc-twinhead.twinstar.cz/?quest=310) 

**Current behaviour**: Hello the quest "Biter rivals " at Kharanos doesn't work. I give the Thunder Ale to Jarven Thunderbrew, I go to the upstair but the barell disappears and nothing past. After few second Jarven come back and I can't turn in the quest.

I try the quest 3 times

**Expected behaviour**: Barrel should be replaceable to finish the quest.

**Server Revision**: 

(I open a ticket in game)

**Comment by The14me** [comment]
Duplicate
https://github.com/Atlantiss/NetherwingBugtracker/issues/4355
