### ISSUE TITLE
Curse of Agony Stacks

### ISSUE THREAD

**Issue by lnverto** [Atlantiss/NetherwingBugtracker#557]
[//]: # (Enclose links to things related to the bug using http://wowhead.com or any other TBC database.)
[//]: # (You can use screenshot ingame to visual the issue.)
[//]: # (Write your tickets according to the format:)
[//]: # ([Quest][Azuremyst Isle] Red Snapper - Very Tasty!)
[//]: # ([NPC] Magistrix Erona)
[//]: # ([Spell][Mage] Fireball)
[//]: # ([Npc][Drop] Ghostclaw Lynx)
[//]: # ([Web] Armory doesnt work)

**Description**: 
Curse of Agony casted by "Eye of Dar'Khan" at the gates of Deatholme stacks and does not expire if one of the versions is still on the player
**Current behaviour**:
Curse of Agony continues to tick even if the time has run out - If there is another version of Curse of Agony active on the player that has not run out yet.
**Expected behaviour**: 
Curse of Agony should run out when the timer has run out
**Server Revision**:

**Comment by Wolffenstein** [comment]
Fixed in rev 2055.
