### ISSUE TITLE
[core][sai] Update NPC template action refreshes NPC´s HP to 100% instead of keeping the current value before update

### ISSUE THREAD

**Issue by Evolvee** [Atlantiss/NetherwingBugtracker#5570]
also https://github.com/Atlantiss/AtlantissTBCBT/issues/4345
https://github.com/Atlantiss/AtlantissTBCBT/issues/4346

**Comment by Wolffenstein** [comment]
Won't be changed because it's intended.

**Comment by Evolvee** [comment]
well then give me SAI action that saves current HP

because right now it heals the NPC to full and i have no way to prevent it
