### ISSUE TITLE
[Raid][Karazhan] Trash mobs don't despawn after soft reset

### ISSUE THREAD

**Issue by mn142** [Atlantiss/NetherwingBugtracker#5571]
[//]: # (Enclose links to things related to the bug using http://wowhead.com or any other TBC database.)
[//]: # (You can use screenshot ingame to visual the issue.)
[//]: # (Write your tickets according to the format:)
[//]: # ([Quest][Azuremyst Isle] Red Snapper - Very Tasty!)
[//]: # ([NPC] Magistrix Erona)
[//]: # ([Spell][Mage] Fireball)
[//]: # ([Npc][Drop] Ghostclaw Lynx)
[//]: # ([Web] Armory doesnt work)
[//]: # (To find server revision type `.server info` command in the game chat.)

**Description**: 
Realised this issue when trying to complete the quest Keanna's Log inside karazhan after we had cleared the instance of bosses, however we did not clear trash for quest items.

**Current behaviour**:
Trash mobs for killed bosses don't despawn after a "soft" reset of the instance (30 minutes of no raid members inside the instance), 

**Expected behaviour**: 
Trash mobs for bosses killed should despawn after the instance has been without any occupants for 30 minutes. See comments by _FibriZzo_ and _uigrad_ on wowhead: https://www.wowhead.com/quest=9843/keannas-log#comments

**Server Revision**: 
2930

**Comment by veekk** [comment]
+, doesn't work for no-one

**Comment by The14me** [comment]
Rev.3483 not an issue anymore. Checked after 1h and the mobs weren't there.
