### ISSUE TITLE
[Class][Ability]Warrior Charge/Intercept bug relating to Stuns.

### ISSUE THREAD

**Issue by Gibi-gibii** [Atlantiss/NetherwingBugtracker#5572]
[//]: # (Enclose links to things related to the bug using http://wowhead.com or any other TBC database.)
[//]: # (You can use screenshot ingame to visual the issue.)
[//]: # (Write your tickets according to the format:)
[//]: # ([Quest][Azuremyst Isle] Red Snapper - Very Tasty!)
[//]: # ([NPC] Magistrix Erona)
[//]: # ([Spell][Mage] Fireball)
[//]: # ([Npc][Drop] Ghostclaw Lynx)
[//]: # ([Web] Armory doesnt work)
[//]: # (To find server revision type `.server info` command in the game chat.)

**Description**: There is a current issue with Charge/Intercept, where if you are stunned at the beginning/middle of the action you stop moving.

**Expected behaviour**: If a stun is applied during a charge/intercept, the warrior should continue along the path of the charge/intercept and finish off the duration of the stun at the target destination.

Video in below link shows Laintime getting HoJ'd mid-intercept and still continuing the path until he reaches the end-point of the intercept, where he then goes into a stun for the remainder of the HoJ

https://youtu.be/tb6yzXA7DhA?t=84

**Server Revision**: 2930

**Comment by Wolffenstein** [comment]
It looks like more like a teleport to the end destination the moment you receive the stun, but that would be in line with current packet handling when StopMoving() is not called.

**Comment by Wolffenstein** [comment]
Fixed in rev 2933.
