### ISSUE TITLE
[Raid][Magtheridon's Lair] Magtheridon is hitting for significantly harder than he should.

### ISSUE THREAD

**Issue by Gibi-gibii** [Atlantiss/NetherwingBugtracker#5573]
[//]: # (Enclose links to things related to the bug using http://wowhead.com or any other TBC database.)
[//]: # (You can use screenshot ingame to visual the issue.)
[//]: # (Write your tickets according to the format:)
[//]: # ([Quest][Azuremyst Isle] Red Snapper - Very Tasty!)
[//]: # ([NPC] Magistrix Erona)
[//]: # ([Spell][Mage] Fireball)
[//]: # ([Npc][Drop] Ghostclaw Lynx)
[//]: # ([Web] Armory doesnt work)
[//]: # (To find server revision type `.server info` command in the game chat.)

**Description**: Magtheridon is auto-attacking for incorrect damage values.

**Current behaviour**: Mag is hitting the MT for ~3000 to ~8000 per auto
https://legacyplayers.com/Raids/Viewer/Default.aspx?id=5763&exp=1&upl=8358
![image](https://user-images.githubusercontent.com/30094741/55653291-e46a4900-57a2-11e9-87be-51fd214cc669.png)

https://legacyplayers.com/Raids/Viewer/Default.aspx?id=5500&exp=1&upl=7903
https://legacyplayers.com/Raids/Viewer/Default.aspx?id=5443&exp=1&upl=7818

**Expected behaviour**: Nihilum World First Magtheridon video shows Kungen, MT, getting auto-attacked mostly between 1000 and 2500, with a couple above 3k, the highest I saw in the video was around 5k.
You can see that he is elixir stacking so the video is pre2.1. 
https://youtu.be/QpgdAHJANcA?t=37

**Server Revision**: 2930

**Comment by Tenoutoften** [comment]
Netherwing uses custom values, it's well known... expect significantly higher damage & health values compared to retail

**Comment by Anselm123** [comment]
NW not using retail values? shockedpikachu.jpg

**Comment by Wolffenstein** [comment]
Will not be changed until 2.1.
