### ISSUE TITLE
[NPC] Lawrence Schneider

### ISSUE THREAD

**Issue by noradora** [Atlantiss/NetherwingBugtracker#5574]
[//]: # (Enclose links to things related to the bug using http://wowhead.com or any other TBC database.)
[//]: # (You can use screenshot ingame to visual the issue.)
[//]: # (Write your tickets according to the format:)
[//]: # ([Quest][Azuremyst Isle] Red Snapper - Very Tasty!)
[//]: # ([NPC] Magistrix Erona)
[//]: # ([Spell][Mage] Fireball)
[//]: # ([Npc][Drop] Ghostclaw Lynx)
[//]: # ([Web] Armory doesnt work)
[//]: # (To find server revision type `.server info` command in the game chat.)

**Description**: 
Screenshot: https://i.imgur.com/yBTfFco.png

**Current behaviour**:
Shows limited recipes, doesn't offer tailoring as a skill, and shows incorrect image for skills offered
**Expected behaviour**: 
http://classicdb.ch/?npc=1300#teaches-ability

**Server Revision**: 
2390

**Comment by Godmatik** [comment]
They'll probably need proof from a database that isn't from another private server.

**Comment by Evolvee** [comment]
fixed in next rev
