### ISSUE TITLE
[PvP][Spell] Berserk/Healing/Sprint buffs consumed but not applied when stealth

### ISSUE THREAD

**Issue by ScottieDOESknow** [Atlantiss/NetherwingBugtracker#5575]
Picking up these buffs while in stealth will 'consume' them but no buff is applied to player.

**Current behaviour**: Consumed but not applied while stealth.

**Expected behaviour**:  Should be consumed and applied even while stealth.

**Server Revision**: 2930

**Comment by ScottieDOESknow** [comment]
Possible related
https://github.com/Atlantiss/NetherwingBugtracker/issues/5521

**Comment by ScottieDOESknow** [comment]
Same issue from Feb 22
https://github.com/Atlantiss/NetherwingBugtracker/issues/5121

**Comment by Wolffenstein** [comment]
Fixed in rev 2933.
