### ISSUE TITLE
Tree of life bonus healing aura does not apply to the bloom of lifebloom spell

### ISSUE THREAD

**Issue by OffeSwedin** [Atlantiss/NetherwingBugtracker#5577]
[//]: # (Enclose links to things related to the bug using http://wowhead.com or any other TBC database.)
[//]: # (You can use screenshot ingame to visual the issue.)
[//]: # (Write your tickets according to the format:)
[//]: # ([Quest][Azuremyst Isle] Red Snapper - Very Tasty!)
[//]: # ([NPC] Magistrix Erona)
[//]: # ([Spell][Mage] Fireball)
[//]: # ([Npc][Drop] Ghostclaw Lynx)
[//]: # ([Web] Armory doesnt work)
[//]: # (To find server revision type `.server info` command in the game chat.)

**Description**: 

Tree of life bonus healing aura does not apply to the big heal at the end of lifebloom spell

**Current behaviour**:

Lifebloom outside tree of life:
tick: 157
bloom: 1050

Lifebloom inside tree of life:
tick: 166
bloom: 1050

**Expected behaviour**: 

The finishing bloom should be increased by bonus healing of the tree of life aura.

**Server Revision**: 

[2932]

**Comment by Wolffenstein** [comment]
Fixed in rev 2933.
