### ISSUE TITLE
Crowd control stops your character from running unless you release W and press it again

### ISSUE THREAD

**Issue by teddys** [Atlantiss/NetherwingBugtracker#5579]
**Description**:  Now I don't really have any official evidence for this, but it's a thing I have not experienced on any other server before.  It makes trinketing cc worse because you trinket in order to keep up with a target, but you don't, because you are not moving .. until you realize you need to release w and press it again

**Current behaviour**: When you get cced (cyclone, scatter shot, blind, whatever) in order to keep running after you trinket said cc, you need to release your W key and press it again .. otherwise you will not move even though your W remains pressed

**Expected behaviour**:  You should be able to run after cc without having to release and press W again

**Server Revision**:  2930

**Comment by Evolvee** [comment]
was supposed to be fixed 2.5 years ago: 
https://github.com/Atlantiss/AtlantissTbcBTOLD/issues/188
ccshiro/cc-buglist#1370
ccshiro/cc-buglist#1866

**Comment by Wolffenstein** [comment]
I've done research on this in the past, including comparisons between packets sent by the server and concluded that there is no evidence that you should move after holding W (I think I had one source that actually claimed you needed to press it again but would have to search for it again). 

There is one way to hackfix it by intentionally sending root/deroot packets but it will lead to other desynchronization issues and as I said none of it was present in retail data from TBC/Wotlk.

**Comment by Evolvee** [comment]
rip

https://youtu.be/_qaVLKwBCR4

**Comment by teddys** [comment]
that's .... unfortunate :S
