### ISSUE TITLE
[NPC] Ranged mob leeshing

### ISSUE THREAD

**Issue by Kidcudi123** [Atlantiss/NetherwingBugtracker#558]
First of all I'd like to say I think all mobs reset too quickly when you run out of range.

Description: I was able to leesh a mob and right when it resetted I was heading towards them to avoid them resetting. This made them still have target on me and they got pulled again even though they resetted back to their spot. (Hard to reproduce?) Couldnt make them do it a 2nd time.

Was this mob https://gyazo.com/40844d55bd39934828b6964579cd5feb

**Comment by Tenoutoften** [comment]
This has been changed several times since this report has been made, likely invalid.
