### ISSUE TITLE
Guild problem

### ISSUE THREAD

**Issue by Naarue** [Atlantiss/NetherwingBugtracker#5581]
[//]: # (Enclose links to things related to the bug using http://wowhead.com or any other TBC database.)
[//]: # (You can use screenshot ingame to visual the issue.)
[//]: # (Write your tickets according to the format:)
[//]: # ([Quest][Azuremyst Isle] Red Snapper - Very Tasty!)
[//]: # ([NPC] Magistrix Erona)
[//]: # ([Spell][Mage] Fireball)
[//]: # ([Npc][Drop] Ghostclaw Lynx)
[//]: # ([Web] Armory doesnt work)
[//]: # (To find server revision type `.server info` command in the game chat.)

**Description**: My problem is not fixed, i don't get kicked anymore but i can't see any messages from my guild, and i can't send messages.

https://github.com/Atlantiss/NetherwingBugtracker/issues/5555

**Current behaviour**: I'm in guild but i can't see any messages.
![WoWScrnShot_040619_233412](https://user-images.githubusercontent.com/49115717/55675554-c268e780-58c4-11e9-9ed4-86035884085e.jpg)

**Expected behaviour**: Be in guild and see messages from my guild.

**Server Revision**: 

![zzzzz](https://user-images.githubusercontent.com/49115717/55675557-d14f9a00-58c4-11e9-9642-2d5ab7227752.png)

**Comment by Wolffenstein** [comment]
You will have to wait for next restart.
