### ISSUE TITLE
[Item][Reputation] Warden's Arrows require revered to purchase, but not to equip

### ISSUE THREAD

**Issue by Kristoferhh** [Atlantiss/NetherwingBugtracker#5582]
**Description**: Warden's Arrows require revered to purchase, but not to equip. So someone who has revered can purchase them then trade them to someone who doesn't have the rep for it and they will be able to equip it.

**Current behaviour**: Warden's Arrows require revered to purchase, but not to equip

**Expected behaviour**: The arrows should require revered with CE before being able to equip them

**Server Revision**: 2930

**Comment by Kristoferhh** [comment]
I'm guessing this applies to other arrows/bullets that are reputation-locked but not BoP

**Comment by gvozdeni** [comment]
Not sure if relevant but you can put them up on AH as well.

**Comment by Evolvee** [comment]
can you list all arrows/bullets that can be affected by this? also, is this intended?

**Comment by Zarant** [comment]
There are 2 warden's arrow on the database, one of them is level 62 and not bind on anything, with its earliest entry from april 2007 (patch 2.0.x)
The other one is level 68 and bop, having its earliest entry in july 2007 (patch 2.1)

http://web.archive.org/web/20070703221303/http://www.thottbot.com/i24412 (2.0 version)
http://web.archive.org/web/20070706164129/http://www.thottbot.com/i31949 (2.1 version)

Also notice that the bullet equivalent, hellfire shot and felbane slugs, should NOT be in the game in 2.0:
http://web.archive.org/web/20070704233135/http://www.thottbot.com/i32882 (earliest entry July 2007)
http://web.archive.org/web/20070704233350/http://www.thottbot.com/i32883 (earliest comment from may 2007)

**Comment by Evolvee** [comment]
This is a core issue. in DB the faction requirement is already pre-set and working...

I will remove hellfire shot/slugs from 2.0. content.

**Comment by Tereneckla** [comment]
They are BoP now
