### ISSUE TITLE
[NPC] Corporal Keeshan

### ISSUE THREAD

**Issue by noradora** [Atlantiss/NetherwingBugtracker#5584]
**Description**: 
At the end of the escort quest this NPC offers, instead of just disappearing, he dies at the turn-in. 

**Current behaviour**:
Dies after you turn in the quest at Marshal Marris in Redridge

**Expected behaviour**: 
He should just disappear. Muh immersion.

**Server Revision**: 
2930

**Comment by Evolvee** [comment]
![image](https://user-images.githubusercontent.com/1942409/58329155-2d01c280-7e34-11e9-8918-4294fafd738e.png)

**Comment by Godmatik** [comment]
Rev 4018 - no longer an issue - the NPC properly despawned once he reached the end of his escort and after he said his RP text.
