### ISSUE TITLE
[Paladin][Spell] Divine Intervention

### ISSUE THREAD

**Issue by veekk** [Atlantiss/NetherwingBugtracker#5585]
**Description**:  Sometime DI not make target invulnerable with buff applied, target player for stuck but after can get hit and die without cancel aura

**Server Revision**: 2930

**Comment by gabbat** [comment]
can e.g. happen on magtheridon: player gets DI'ed by a paladin while standing in a fire/beeing affected by conflag. player still takes dmg during DI and dies eventually.

**Comment by Godmatik** [comment]
Not able to reproduce, DIed target always is immune during entire duration. And have not heard of anyone saying this ever happened to them on Netherwing server either this past year.

Probably fixed at some point.
