### ISSUE TITLE
[Paladin][Spell] Divine Shield and Lay on Hands

### ISSUE THREAD

**Issue by veekk** [Atlantiss/NetherwingBugtracker#5586]
**Description**: Sometime when you use bubble or LoH on very low HP before death CD starting but spell not affect caster, no bubble or heal depends on spell

**Server Revision**: 2930

**Comment by Evolvee** [comment]
no spell delay 😢 😭 😿 🐺 😠

**Comment by veekk** [comment]
is it ok or that's bug then?

**Comment by Evolvee** [comment]
"bug"

**Comment by Godmatik** [comment]
Unable to reproduce and have not heard anyone complain about this in past year on Netherwing, perhaps fixed at some point.

Closing for now.
