### ISSUE TITLE
[Dungeon][Mechanar] Gatekeepers loot

### ISSUE THREAD

**Issue by veekk** [Atlantiss/NetherwingBugtracker#5587]
**Description**:  If you pull gatekeeper and die + release, but your party managed to kill gatekeeper there's no loot badge+piece of key except only gold

**Server Revision**: 2930

**Comment by Easyfraggy** [comment]
Not sure this is a bug.

**Comment by veekk** [comment]
Obviously yes, at least 'cause of two point:
1. we're in party and we've got kill
2. we can loot gold from corpse

**Comment by Easyfraggy** [comment]
On retail you wouldn't get loot at all if you released in TK instances since you would auto res outside. Maybe the bug is that you got the gold 🤔 Need some evidence from retail on how it should be.

**Comment by veekk** [comment]
No one get any loot, even 4 guys that don't die this fight. All party didn't get badge and part of key. Also only I'm was able to loot gold after I got back from graveyard, my party couldn't even loot this gold. Is this ok that 1 guy died+released and whole party didn't got loot(badge+key)? I guess not.

**Comment by Easyfraggy** [comment]
I think maybe you didn't specify the problem well enough the first time round - You are saying that noone in the party gets loot in the situation first explained in the OP? It sounded like you just ment the person who released.

**Comment by veekk** [comment]
yes, no one get loot when single person was released

**Comment by Easyfraggy** [comment]
Alright then yeah thats a loot issue. I think the entire loot system needs an overhaul when theres time for it. Thanks for reporting!
