### ISSUE TITLE
[Quest][Thousand Needles] Razorfen Kraul Quest - Journal interactable but there's no item

### ISSUE THREAD

**Issue by wowthings** [Atlantiss/NetherwingBugtracker#559]
[//]: # (Enclose links to things related to the bug using http://wowhead.com or any other TBC database.)
[//]: # (You can use screenshot ingame to visual the issue.)
[//]: # (Write your tickets according to the format:)
[//]: # ([Quest][Azuremyst Isle] Red Snapper - Very Tasty!)
[//]: # ([NPC] Magistrix Erona)
[//]: # ([Spell][Mage] Fireball)
[//]: # ([Npc][Drop] Ghostclaw Lynx)
[//]: # ([Web] Armory doesnt work)

**Description**: 
Alliance main quest for RFK, there should be [this journal ](https://www.wowhead.com/item=5791/henrig-lonebrows-journal) to loot from [this object](http://classicdb.ch/?object=19861).
**Current behaviour**:
No item to loot.
![wowscrnshot_092518_192239](https://user-images.githubusercontent.com/43504905/46031677-d8b60f80-c0f9-11e8-9674-da3ffd2b3f9a.jpg)

**Comment by xmesaj2** [comment]
fix in rev 2054
