### ISSUE TITLE
Owl diet issue

### ISSUE THREAD

**Issue by satorare** [Atlantiss/NetherwingBugtracker#5590]
Description: My Owl doesn't eat the Red Wolf Meat but my character does the animation and it doesn't trigger the error message

Current behaviour: The Owl doesn't eat the meat, it dosnt't trigger the error message but the animation shows that the character does indeed feed the meat to the pet 
Item: https://www.wowhead.com/item=12203/red-wolf-meat
Video Example of the problem: https://youtu.be/_E7R4xopcBc

Expected behaviour: The Owl should eat the Red Wolf Meat and raise his happiness level

Server Revision: 2930

**Comment by Easyfraggy** [comment]
The owl is too low level for that type of meat.
