### ISSUE TITLE
[SSC] [Vashj] Characters affected by Persuasion using inactive talents.

### ISSUE THREAD

**Issue by 5f3759** [Atlantiss/NetherwingBugtracker#5591]
**Description**: 
For example, I used Death Wish during MC when I don't have that talent.
![WoWScrnShot_040719_215307](https://user-images.githubusercontent.com/43552280/55689938-50a7a100-598b-11e9-9317-bd471942c4af.png)

**Expected behavior**: Players in Mind Control should only be able to use abilities they have learned.

**Server Revision**: 2930

**Comment by wtRCH** [comment]
@Wolffenstein

**Comment by Godmatik** [comment]
Was fixed a while ago
