### ISSUE TITLE
[NPC][Core] Sunfury Geologist ignoring geodata

### ISSUE THREAD

**Issue by veekk** [Atlantiss/NetherwingBugtracker#5592]
**Description**:  Sunfury Geologist ignoring geodata and throwing stones through stones, mountains and anything else

**Server Revision**: 2930

**Comment by Tenoutoften** [comment]
A lot of trees and rocks don't give los and that's blizzlike, do you have any proof about a specific rock that should give los but doesn't?

**Comment by Easyfraggy** [comment]
I noticed this aswell the rocks at mana forge do block LOS and they throw through them anyhow - I think this ability is just ignoring LOS for some reason.

**Comment by veekk** [comment]
They're trowing even through the land, I mean not trees/rocks etc, but through the part of landscape, like if they're on low ground, and u're staying on high ground and it's obviously LOS area, they're still throwing. Seems like full LOS ignore from those guys with "throw rock" ability

**Comment by Easyfraggy** [comment]
veekk the landscape doesn't grant LOS at all in wow - thats blizzlike. The rocks are what should cause (and do cause LOS) these mobs throw just ignores it.

**Comment by Tereneckla** [comment]
What Easy said
