### ISSUE TITLE
[Quest][Mana-Tombs] Safety Is Job One

### ISSUE THREAD

**Issue by skalken91** [Atlantiss/NetherwingBugtracker#5593]
Can't deliver quest when a person in the group has delivered it and started the scenario, Don't know if it is intended but I spoke to a GM and he told me to make a bug report.

**Comment by Evolvee** [comment]
If someone starts the 2nd quest before everyone rewarded the initial pre-quest, then it wont allow you to get the 2nd quest, thats blizzlike behavior according to wowhead comments.. soo.. you just have to make sure ppl dont start it too early.
