### ISSUE TITLE
BLADE'S EDGE BUGGED QUEST - [Prisoner of the Bladespire]

### ISSUE THREAD

**Issue by zmthc93** [Atlantiss/NetherwingBugtracker#5594]
[//]: # (Enclose links to things related to the bug using http://wowhead.com or any other TBC database.)
[//]: # (You can use screenshot ingame to visual the issue.)
[//]: # (Write your tickets according to the format:)
[//]: # ([Quest][Azuremyst Isle] Red Snapper - Very Tasty!)
[//]: # ([NPC] Magistrix Erona)
[//]: # ([Spell][Mage] Fireball)
[//]: # ([Npc][Drop] Ghostclaw Lynx)
[//]: # ([Web] Armory doesnt work)
[//]: # (To find server revision type `.server info` command in the game chat.)

**Description**: 
When quest item is used in this quest the animation works but does not count towards quest completed
**Current behaviour**:
animation works for quest item interaction but does not count towards quest completed
**Expected behaviour**: 
interacting with quest should complete quest
**Server Revision**:

**Comment by Drayo** [comment]
You need to use the Whistle under the cage. The quest says the spirit will then use the key to free him.

It works.

**Comment by Manaci** [comment]
Fixed
