### ISSUE TITLE
[Arena] When dead/ghost, you can spot stealthed players.

### ISSUE THREAD

**Issue by gunzbngbng** [Atlantiss/NetherwingBugtracker#5595]
[//]: # (Enclose links to things related to the bug using http://wowhead.com or any other TBC database.)
[//]: # (You can use screenshot ingame to visual the issue.)
[//]: # (Write your tickets according to the format:)
[//]: # ([Quest][Azuremyst Isle] Red Snapper - Very Tasty!)
[//]: # ([NPC] Magistrix Erona)
[//]: # ([Spell][Mage] Fireball)
[//]: # ([Npc][Drop] Ghostclaw Lynx)
[//]: # ([Web] Armory doesnt work)
[//]: # (To find server revision type `.server info` command in the game chat.)

**Description**: After you've died, your ghost can still detect stealthed players.

**Current behaviour**: After you've died, your ghost can still detect stealthed players.

**Expected behaviour**: Shouldn't happen.

**Server Revision**: 2930

**Comment by Easyfraggy** [comment]
maybe possible both can be fixed at the same time: https://github.com/Atlantiss/NetherwingBugtracker/issues/5544

**Comment by Greytt** [comment]
Confirming that this is true.

**Comment by Wolffenstein** [comment]
Fixed in rev 2941.
