### ISSUE TITLE
 Drunken Haze debuff Bloodmaul BRewmaster

### ISSUE THREAD

**Issue by ghost** [Atlantiss/NetherwingBugtracker#5596]
[//]: # (Enclose links to things related to the bug using http://wowhead.com or any other TBC database.)
[//]: # (You can use screenshot ingame to visual the issue.)
[//]: # (Write your tickets according to the format:)
[//]: # ([Quest][Azuremyst Isle] Red Snapper - Very Tasty!)
[//]: # ([NPC] Magistrix Erona)
[//]: # ([Spell][Mage] Fireball)
[//]: # ([Npc][Drop] Ghostclaw Lynx)
[//]: # ([Web] Armory doesnt work)
[//]: # (To find server revision type `.server info` command in the game chat.)

**Description**: 
When you get the drunken haze debuff from a Bloodmaul Brewmaster the debuff stays on and you can't remove it. 

**Current behaviour**:
When Drunken Haze debuff wears off you don't go back to "normal" state instead you get the full drunken haze state and there is no way to remove it ( been playing drunk for 1h now).  
**Expected behaviour**: 
When Drunken Haze debuff wears off you should be able to see the world "sober" again. 

**Server Revision**: 
2930

**Comment by Tenoutoften** [comment]
another report on drunken haze
https://github.com/Atlantiss/NetherwingBugtracker/issues/2754

**Comment by Tereneckla** [comment]
Fixed
