### ISSUE TITLE
[npc][raid][tempest keep] Crystalcore Devastator

### ISSUE THREAD

**Issue by towneh** [Atlantiss/NetherwingBugtracker#5598]
**Description**: 
Crystalcore Devastator appear to hit with arcane based melee attacks by default

**Current behaviour**:
Tanks are receiving melee damage from Crystalcore Devastator, which appears to be entirely based on arcane and is not being mitigated by armor. Tanks for raiding guilds in TK are being forced to use arcane resist gear (à la Ragnaros) on this npc in order to survive.

![image](https://user-images.githubusercontent.com/25694892/55720219-39eb6380-59f8-11e9-8176-cffa59e0448f.png)

**Expected behaviour**: 
Crystalcore Devastator should attack with melee physical damage, and gain an aura called "Countercharge" which adds arcane damage on top of their melee physical damage.

https://www.wowhead.com/npc=20040/crystalcore-devastator#comments:id=83187

*note: there are two versions, pre 2.1 and post 2.1*

Pre 2.1
> By huntergenwedar on 2007/05/15 (Patch 2.0.12)
> "These guys have about 1 million HP and have two abilities:
> 
> Countercharge:
> Charges the caster with Arcane energy, adding 1497 to 1653 additional Arcane damage to melee attacks. This energy can also be released to interrupt an enemy spell.
> 
> 50 yd range
> Counters an enemy's spell, preventing the enemy from casting that spell again for 10 sec. Targets multiple casters and is completely random. It doesn't make too much trouble though and is easy to deal with.
> 
> and 
> 
> Charged Arcane Explosion:
> 3.7 sec cast
> Sends out a blast wave of magic, inflicting Arcane damage to nearby enemies. Value: 5550-6450 Radius: 20 yards."

Post 2.1:
> By Wiggfield on 2007/06/24 (Patch 2.1.2)		
> Confirmed, no more arcane explosion. 
> Wiggfield <Risen>, Antonidas
> 
> Wiggfield on 2007/06/24 (Patch 2.1.2)
> These also seem to have a "knock away" ability which does about 2500 damage AE.
> Wiggfield <Risen>, Antonidas

WWS Log from 2007:
https://dreness.com/wow/uv/wws-20071112-1729/crystalcoredevastator.html

Post 2.1 video footage of devastator pulls:
https://www.youtube.com/watch?v=RbA-RJINyss&feature=youtu.be&t=194

**Server Revision**: 
2930

**Comment by Drayo** [comment]
Yes, pls fix. Or make him not triple hit, either ones is fine. ^^

**Comment by Easyfraggy** [comment]
should be fixed now - please confirm.

**Comment by TpyoNW** [comment]
![image](https://user-images.githubusercontent.com/50060615/56856009-b5a94380-6906-11e9-9bdc-a395d6a34132.png)
The damage school is fixed, but they are still hitting multiple times instantly as Drayo mentioned. The Phoenix-Hawk mobs earlier on in Al'ars' room do it as well. They both seem to have this ability to trash 2-5 hits instantly about half the time we pull them, and behave normally the other half.

**Comment by Easyfraggy** [comment]
The multihit is a global core issue with any mob in the game - it's a seperate issue (has it's own thread and wolf is aware). Closing this as it has been fixed.

**Comment by caiopmartins** [comment]
http://prntscr.com/nm9dzf
