### ISSUE TITLE
Item ("Savage Boar`s Guard") from the RAR Mob did not get into the bag

### ISSUE THREAD

**Issue by HomaAlex** [Atlantiss/NetherwingBugtracker#5599]
[//]: # (Enclose links to things related to the bug using http://wowhead.com or any other TBC database.)
[//]: # (You can use screenshot ingame to visual the issue.)
[//]: Hello, 07.04 late at night or 08.04 very early. I don’t remember exactly. I went to the dungeon of a "Razorfen Downs", I got a chic shield from a rare monster (I was in the role of a tank) and I won it, but this shield did not fall into my bag! I waited a long time, there were empty slots. Give me back the shield please. Screenshot chat log I have
![WoWScrnShot_040819_022332](https://user-images.githubusercontent.com/24225383/55741162-480ba500-5a35-11e9-8065-235fdad02ddc.jpg)

[//]: # ([Quest][Azuremyst Isle] Red Snapper - Very Tasty!)
[//]: # ([NPC] Magistrix Erona)
[//]: # ([Spell][Mage] Fireball)
[//]: # ([Npc][Drop] Ghostclaw Lynx)
[//]: # ([Web] Armory doesnt work)
[//]: # (To find server revision type `.server info` command in the game chat.)

**Description**:  Account's login
SmileGoodman
Assigned email address
haliaksandr@gmail.com

**Current behaviour**:

**Expected behaviour**: 

**Server Revision**: Netherwing

**Comment by wtRCH** [comment]
Report to GM.
