### ISSUE TITLE
[Spell] [Paladin] Blessing of Might

### ISSUE THREAD

**Issue by Mikik3jr** [Atlantiss/NetherwingBugtracker#56]
[//]: # (Enclose links to things related to the bug using http://wowhead.com or any other TBC database.)
[//]: # (You can use screenshot ingame to visual the issue.)
[//]: # (Write your tickets according to the format:)
[//]: # ([Quest][Azuremyst Isle] Red Snapper - Very Tasty!)
[//]: # ([NPC] Magistrix Erona)
[//]: # ([Spell][Mage] Fireball)
[//]: # ([Npc][Drop] Ghostclaw Lynx)
[//]: # ([Web] Armory doesnt work)

**Description**: 
I cannot give myself Blessing of Might buff when my Seal of the Crusader is active on me.
**Current behaviour**:
While Seal of the Crusader is up (which gives you more ap than might) I can't give myself Blessing of Might, because it says "A more powerful spell is already active"
![wowscrnshot_092218_234050](https://user-images.githubusercontent.com/43505031/45922009-7ffc3200-bec1-11e8-9e27-d4c81aad7c4e.jpg)
Even if I don't have the Blessing of Might buff on me I still can't give myself that buff if Seal of the Crusader is active
**Expected behaviour**: 
I should be able to buff myself when Seal of the Crusader is up on me.
**Server Revision**: 
2028

**Comment by wtRCH** [comment]
Also worth checking this issue https://github.com/Atlantiss/NetherwingBugtracker/issues/7

**Comment by Buggyswires** [comment]
Confirmed - the +AP from Seal of the Crusader seems to Block BoM which shouldnt be the case

**Comment by Wolffenstein** [comment]
Fixed in rev 2067.
