### ISSUE TITLE
[NPC][Kobold Worker][Elwynn Forest] NPC Pathing

### ISSUE THREAD

**Issue by Thugli** [Atlantiss/NetherwingBugtracker#560]
[//]: # (Enclose links to things related to the bug using http://wowhead.com or any other TBC database.)
[//]: # (You can use screenshot ingame to visual the issue.)
[//]: # (Write your tickets according to the format:)
[//]: # ([Quest][Azuremyst Isle] Red Snapper - Very Tasty!)
[//]: # ([NPC] Magistrix Erona)
[//]: # ([Spell][Mage] Fireball)
[//]: # ([Npc][Drop] Ghostclaw Lynx)
[//]: # ([Web] Armory doesnt work)

**Description**: 
A Kobold Worker had a pathing issue where he got stuck in one of the walls of echo ridge mine in North
shire.

**Current behaviour**:
A video of this bug can be seen here:
https://clips.twitch.tv/CaringSparklingTurnipAliens

**Expected behaviour**: 
This npc should get stuck in the wall

**Server Revision**: 
2050

**Comment by aresbrutus** [comment]
Will be fixed in one of the next updates.
