### ISSUE TITLE
[Shaman] [Spell] Windfury offhand criticals not triggering Flurry

### ISSUE THREAD

**Issue by TotemShitter** [Atlantiss/NetherwingBugtracker#5600]
[//]: # (Enclose links to things related to the bug using http://wowhead.com or any other TBC database.)
[//]: # (You can use screenshot ingame to visual the issue.)
[//]: # (Write your tickets according to the format:)
[//]: # ([Quest][Azuremyst Isle] Red Snapper - Very Tasty!)
[//]: # ([NPC] Magistrix Erona)
[//]: # ([Spell][Mage] Fireball)
[//]: # ([Npc][Drop] Ghostclaw Lynx)
[//]: # ([Web] Armory doesnt work)
[//]: # (To find server revision type `.server info` command in the game chat.)

**Description**: 
Windfury weapon critical strikes in the offhand do not trigger the Flurry talent.
**Current behaviour**: Offhand windfury critical strikes shown not triggering Flurry
https://imgur.com/a/ave8uCt
**Expected behaviour**: Mainhand windfury critical strikes correctly triggering Flurry
https://imgur.com/a/W3IvzlW
**Server Revision**: Server Revision 2930

**Comment by QuelSera** [comment]
Also doens't trigger Unleashed Rage Shamanistic Focus which it should.

**Comment by Lariari** [comment]
Has anyone looked any further into this? Any updates?

**Comment by Wolffenstein** [comment]
Fixed in rev 3020.
