### ISSUE TITLE
[Spell][Warlock] Improved Drain Soul

### ISSUE THREAD

**Issue by spacejamsnax** [Atlantiss/NetherwingBugtracker#5601]
[//]: # (Enclose links to things related to the bug using http://wowhead.com or any other TBC database.)
[//]: # (You can use screenshot ingame to visual the issue.)
[//]: # (Write your tickets according to the format:)
[//]: # ([Quest][Azuremyst Isle] Red Snapper - Very Tasty!)
[//]: # ([NPC] Magistrix Erona)
[//]: # ([Spell][Mage] Fireball)
[//]: # ([Npc][Drop] Ghostclaw Lynx)
[//]: # ([Web] Armory doesnt work)
[//]: # (To find server revision type `.server info` command in the game chat.)

**Description**: Improved Drain Soul should restore 15% of the warlock's mana if the warlock is draining a target's soul and either the warlock or their pet lands a killing blow on the mob. Realized that this hasn't been the case.

**Current behaviour**: Not returning any mana upon kill.

**Expected behaviour**:  Returns 15% mana if the target is killed while soul drain is on it,

https://tbc-twinhead.twinstar.cz/?spell=18372

**Comment by Wolffenstein** [comment]
Works fine for me.
