### ISSUE TITLE
[Quest] Arelion's Mistress

### ISSUE THREAD

**Issue by snackpak09** [Atlantiss/NetherwingBugtracker#5604]
**Description**: When doing the quest, the NPC Viera Sunwhisper will not move her spot when given the quest item Cenarion Spirits. 

**Current behaviour**: Viera does not move from her spot.

**Expected behaviour**: Viera will move and lead you to a excluded spot to use the other quest item Carinda's Scroll of Retribution.

**Server Revision**:

**Comment by nightwica** [comment]
This is bugged again.

**Comment by The14me** [comment]
Not working at all now.Use the bottle--->nothing happen.

**Comment by Evolvee** [comment]
still?
