### ISSUE TITLE
[TK] Kael'thas - Disorient affected some people despite having staff buff

### ISSUE THREAD

**Issue by BezawitNW** [Atlantiss/NetherwingBugtracker#5605]
During the last phase of Kael, his disorient is applying to some people in the raid despite everyone having the staff buff.

https://www.twitch.tv/videos/408252935

This happened three times during our kill to myself and a few others in the raid.

**Comment by Jseay1313** [comment]
to be fair this has been reported/known for 5 weeks but its probably good to have it on the bugtracker at this point
