### ISSUE TITLE
[Quest][Duskwood] The Missing Diplomat

### ISSUE THREAD

**Issue by noradora** [Atlantiss/NetherwingBugtracker#5607]
[//]: # (Enclose links to things related to the bug using http://wowhead.com or any other TBC database.)
[//]: # (You can use screenshot ingame to visual the issue.)
[//]: # (Write your tickets according to the format:)
[//]: # ([Quest][Azuremyst Isle] Red Snapper - Very Tasty!)
[//]: # ([NPC] Magistrix Erona)
[//]: # ([Spell][Mage] Fireball)
[//]: # ([Npc][Drop] Ghostclaw Lynx)
[//]: # ([Web] Armory doesnt work)
[//]: # (To find server revision type `.server info` command in the game chat.)

**Description**: 
Small error, localization or something? 
**Current behaviour**:
Item: Defias Docket 
on page 3 of this book, the word allies is enclosed by question marks. 
**Expected behaviour**: 
It should be double quotes. "allies" https://www.wowhead.com/item=5947/defias-docket
**Server Revision**: 
2930

**Comment by randomuser69** [comment]
This issue is still in the game, see "our??? allies???"

![WoWScrnShot_061119_010103](https://user-images.githubusercontent.com/51173000/59815569-f3af5c00-92e6-11e9-87b8-687ee1cb43c2.jpg)

**Comment by Evolvee** [comment]
fixed
