### ISSUE TITLE
[Spell] Mass Dispel@Divine Shield failed, "immune"

### ISSUE THREAD

**Issue by b15andga** [Atlantiss/NetherwingBugtracker#5608]
[//]: # (Enclose links to things related to the bug using http://wowhead.com or any other TBC database.)
[//]: # (You can use screenshot ingame to visual the issue.)
[//]: # (Write your tickets according to the format:)
[//]: # ([Quest][Azuremyst Isle] Red Snapper - Very Tasty!)
[//]: # ([NPC] Magistrix Erona)
[//]: # ([Spell][Mage] Fireball)
[//]: # ([Npc][Drop] Ghostclaw Lynx)
[//]: # ([Web] Armory doesnt work)
[//]: # (To find server revision type `.server info` command in the game chat.)

**Description**: 
Mass Dispel should dispel Divine Shield. Can be resisted.
**Current behaviour**:
Mass Dispel on Divine Shield frequently fails because of Diving Shield making the paladin immune to Mass Dispel. 
![WoWScrnShot_040919_024445](https://user-images.githubusercontent.com/18015872/55769667-ddcd2180-5a81-11e9-99f3-edcd90438abc.jpg)
![WoWScrnShot_040919_031352](https://user-images.githubusercontent.com/18015872/55769668-ddcd2180-5a81-11e9-909e-7a60b7b76416.jpg)
**Expected behaviour**: 
Mass Dispel should remove Divine Shield; Divine Shield should not make you immune to mass dispel. This is not a problem with resist, as it then should say "Resist" instead of "Immune". This is not strictly visual, either, it's actually a failed ("Immune") mass dispel.

**Server Revision**: 
2930

**Comment by Zarant** [comment]
From experience, mass dispel will always return the Immune text, regardless of the outcome. And as far as I can tell, the 30% dispel resistance from the Stoicism talent works just fine with Divine Shield.
