### ISSUE TITLE
[Spell] Devouring Plague not doing damage post-mortem in arenas.

### ISSUE THREAD

**Issue by b15andga** [Atlantiss/NetherwingBugtracker#5609]
[//]: # (Enclose links to things related to the bug using http://wowhead.com or any other TBC database.)
[//]: # (You can use screenshot ingame to visual the issue.)
[//]: # (Write your tickets according to the format:)
[//]: # ([Quest][Azuremyst Isle] Red Snapper - Very Tasty!)
[//]: # ([NPC] Magistrix Erona)
[//]: # ([Spell][Mage] Fireball)
[//]: # ([Npc][Drop] Ghostclaw Lynx)
[//]: # ([Web] Armory doesnt work)
[//]: # (To find server revision type `.server info` command in the game chat.)

**Description**: 
Devouring Plague is a dot which also heals the caster for it's damage done.
**Current behaviour**:
In arena (edit: everywhere), when the caster of Devouring Plague is dead, the Devouring Plague no longer damage the target.
![WoWScrnShot_040919_015957](https://user-images.githubusercontent.com/18015872/55769755-300e4280-5a82-11e9-8a19-8984fb491679.jpg)
**Expected behaviour**: 
When the caster of Devouring Plague is dead, Devouring Plague should keep doing damage to it's target.
**Server Revision**: 
2930

**Comment by Zarant** [comment]
Same thing apply to any kind of drain spell like siphon life and viper sting, they only tick if the caster is alive and on the same continent of its target.

**Comment by bajkorv** [comment]
Devouring plague is not a drain spell I think so it shouldnt work like Siphon Life. Devouring plague should tick even if the caster is dead, Siphon life should not. Feeling pretty solid on this, dont have links to back me up though

**Comment by b15andga** [comment]
What Bajkorv said. Devouring Plauge is a DoT that *also* heals the caster for the damage done. It should keep damaging it's target even though the caster is dead. While Siphon Life is a direct life leech.

**Comment by Zarant** [comment]
I'm not saying that's how it's supposed to work, I'm just stating that the core only handle these kind of spells if the caster is alive and on the same map.

**Comment by Wolffenstein** [comment]
Fixed in rev 3079.
