### ISSUE TITLE
[NPC][Barrens] Counterattack! issues

### ISSUE THREAD

**Issue by asatorrr** [Atlantiss/NetherwingBugtracker#561]
[//]: # (Enclose links to things related to the bug using http://wowhead.com or any other TBC database.)
[//]: # (You can use screenshot ingame to visual the issue.)
[//]: # (Write your tickets according to the format:)
[//]: # ([Quest][Azuremyst Isle] Red Snapper - Very Tasty!)
[//]: # ([NPC] Magistrix Erona)
[//]: # ([Spell][Mage] Fireball)
[//]: # ([Npc][Drop] Ghostclaw Lynx)
[//]: # ([Web] Armory doesnt work)

**Description**: The Horde defender and axe thrower NPCs that spawn for the quest Counterattack! stand still after killing a centaur. They should return to their spawning positions. I'm not sure if they are supposed to regen health, but they currently do not. I also think the dynamic spawns of the centaur might need adjustment, but I don't know the exact details of the quest. Right now the field is almost always full of enemies.

**Current behaviour**:

**Expected behaviour**: 

**Server Revision**: 2050

**Comment by pelekon** [comment]
fixed in rev 2182
