### ISSUE TITLE
[Item][Engineering] Gnomish Mind Control Cap oneshots

### ISSUE THREAD

**Issue by b15andga** [Atlantiss/NetherwingBugtracker#5610]
[//]: # (Enclose links to things related to the bug using http://wowhead.com or any other TBC database.)
[//]: # (You can use screenshot ingame to visual the issue.)
[//]: # (Write your tickets according to the format:)
[//]: # ([Quest][Azuremyst Isle] Red Snapper - Very Tasty!)
[//]: # ([NPC] Magistrix Erona)
[//]: # ([Spell][Mage] Fireball)
[//]: # ([Npc][Drop] Ghostclaw Lynx)
[//]: # ([Web] Armory doesnt work)
[//]: # (To find server revision type `.server info` command in the game chat.)

**Description**: 
Gnomish Mind Control Cap allows you to (supposedly) control a hostile unit like a pet. 
**Current behaviour**:
I used Gnomish Mind Control Cap successfully on a level 63 paladin that sat down as AFK. Only pet action button that showed was "Pet attack". I manually typed "/petfollow" to make this player take follow, which he did. When the mind control effect wore off mid-movement, the character instantly turned into a corpse.
**Expected behaviour**: 
Gnomish Mind Control Cap should not sap the last bit of life from you; it should just restore the character control to the player.
**Server Revision**: 
2930

**Comment by The14me** [comment]
Rev.3483 cant reproduces the one shot issue.
