### ISSUE TITLE
[Spell] Spellsteal Noggenfogger Elixir / Gnomish World Enlarger

### ISSUE THREAD

**Issue by b15andga** [Atlantiss/NetherwingBugtracker#5611]
[//]: # (Enclose links to things related to the bug using http://wowhead.com or any other TBC database.)
[//]: # (You can use screenshot ingame to visual the issue.)
[//]: # (Write your tickets according to the format:)
[//]: # ([Quest][Azuremyst Isle] Red Snapper - Very Tasty!)
[//]: # ([NPC] Magistrix Erona)
[//]: # ([Spell][Mage] Fireball)
[//]: # ([Npc][Drop] Ghostclaw Lynx)
[//]: # ([Web] Armory doesnt work)
[//]: # (To find server revision type `.server info` command in the game chat.)

**Description**: 
Spellsteal can steal magic buffs from hostile targets.
**Current behaviour**:
Spellstealing Noggenfogger Elixir (tested with shrink buff) or World Enlarger, both Magic buffs, does only dispel it from target, not actually steals them. In a duel, a mage spellstole my Noggenfogger (shrink) and World Enlarger buffs. They disappeared from me but did not appear on the mage.
**Expected behaviour**: 
This would be the mage getting the buffs (s)he stole, rather than just dispelling. Cannot verify against retail BC, but it'd make the more sense.
**Server Revision**: 
2930

**Comment by Godmatik** [comment]
Rev 4018 - no longer an issue - spellsteal issues were resolved after the aura branch update. I verified it properly steals these buffs.
