### ISSUE TITLE
[Spell] Shadowform removed upon attempt mounting during shapeshift

### ISSUE THREAD

**Issue by b15andga** [Atlantiss/NetherwingBugtracker#5612]
[//]: # (Enclose links to things related to the bug using http://wowhead.com or any other TBC database.)
[//]: # (You can use screenshot ingame to visual the issue.)
[//]: # (Write your tickets according to the format:)
[//]: # ([Quest][Azuremyst Isle] Red Snapper - Very Tasty!)
[//]: # ([NPC] Magistrix Erona)
[//]: # ([Spell][Mage] Fireball)
[//]: # ([Npc][Drop] Ghostclaw Lynx)
[//]: # ([Web] Armory doesnt work)
[//]: # (To find server revision type `.server info` command in the game chat.)

**Description**: 
Attempting to mount while under the affect of Noggenfogger (skeleton) should give an error message and prevent mounting.
**Current behaviour**:
Along with this error message when attempting to mount up during Noggenfogger (skeleton) Shadowform is also cancelled.
**Expected behaviour**: 
Shadowform should not be cancelled by attempting to mount while under the affect of Noggenfogger (skeleton).
**Server Revision**: 
2930

**Comment by Godmatik** [comment]
Must have been fixed at some point - unable to mount up when Noggenfogger skeleton is active. Gives error "You can't do that yet"

Closing.
