### ISSUE TITLE
[Item][Silithus] Wind Stones not respawning in Silithus

### ISSUE THREAD

**Issue by Dirtybird93** [Atlantiss/NetherwingBugtracker#5613]
[//]: # (Enclose links to things related to the bug using http://wowhead.com or any other TBC database.)
[//]: # (You can use screenshot ingame to visual the issue.)
[//]: # (Write your tickets according to the format:)
[//]: # ([Quest][Azuremyst Isle] Red Snapper - Very Tasty!)
[//]: # ([NPC] Magistrix Erona)
[//]: # ([Spell][Mage] Fireball)
[//]: # ([Npc][Drop] Ghostclaw Lynx)
[//]: # ([Web] Armory doesnt work)
[//]: # (To find server revision type `.server info` command in the game chat.)

**Description**: Hello, this is Dirtybird on Horde side, and this is my first bug report submission here. I have spent a majority of the last ~48 hours in Silithus attempting to complete Three Kings of Flame (http://db.hellfire-tbc.com/?quest=8961) by summoning the Duke of Cynders.

 In order to do that, I need to collect 3 Abyssal Crest (http://db.hellfire-tbc.com/?item=20513) from the Templars summoned from the Lesser Wind Stones to complete Dukes of the Council (http://db.hellfire-tbc.com/?quest=8332), to get the Medallion which allows me access to the "regular" Wind Stone that will summon the Duke of Cynders. 

**Current behaviour**: No Wind Stones or Lesser Wind Stones have spawned in a +/- 48 hour timeframe. 

**Expected behaviour**: Quoting the information at (https://wow.gamepedia.com/Wind_stone) - "The respawn time on the Wind stones seems to be approximately 15 minutes."

**Server Revision**: Currently 2930.

Attached are screenshots of each spawn point for the Lesser and "regular" Wind Stones.

![WoWScrnShot_040819_192741](https://user-images.githubusercontent.com/49427485/55776269-e0a32480-5a37-11e9-8201-6f6e260460bb.jpg)
![WoWScrnShot_040819_192759](https://user-images.githubusercontent.com/49427485/55776270-e13bbb00-5a37-11e9-8914-5db18958f3b0.jpg)
![WoWScrnShot_040819_192901](https://user-images.githubusercontent.com/49427485/55776271-e13bbb00-5a37-11e9-82eb-ef040b17ed30.jpg)
![WoWScrnShot_040819_192932](https://user-images.githubusercontent.com/49427485/55776272-e13bbb00-5a37-11e9-809e-ed7a89511fb4.jpg)
![WoWScrnShot_040819_193028](https://user-images.githubusercontent.com/49427485/55776273-e1d45180-5a37-11e9-99cb-c3279504e4a2.jpg)
![WoWScrnShot_040819_193426](https://user-images.githubusercontent.com/49427485/55776275-e1d45180-5a37-11e9-9c24-85b22bd18fcc.jpg)
![WoWScrnShot_040819_193557](https://user-images.githubusercontent.com/49427485/55776276-e3057e80-5a37-11e9-957f-bab3738fb95f.jpg)
![Uploading WoWScrnShot_040819_193626.jpg…]()

**Comment by samzispheq** [comment]
I have the same problem! i've been trying to complete this quest but no stones appearing

**Comment by Evolvee** [comment]
https://github.com/Atlantiss/NetherwingBugtracker/issues/6097
