### ISSUE TITLE
Thick Felsteel Necklace: AH

### ISSUE THREAD

**Issue by Rooik** [Atlantiss/NetherwingBugtracker#5614]
**Description**: 
Thick Felsteel necklace cant be posted on the Auction House. It gives the error message "You cannot auction an item with used charges even though it has no used charges.

**Current behaviour**:
Can't post "Thick Felsteel Necklace" on the auctionhouse due to having false "used charges"
**Expected behaviour**: 
Should be postable to the auctionhouse like their counterparts "Braided Eternium Chain", Eye of the night","Chain of the twilight owl".

**Comment by Wolffenstein** [comment]
Fixed in rev 3361.
