### ISSUE TITLE
Seal twisting paladin 

### ISSUE THREAD

**Issue by kyeda** [Atlantiss/NetherwingBugtracker#5615]
How it works : 
- using Seal of Blood .5sec **before** a white hit does nothing
- using Seal of Blood .5sec **after** a white hit does nothing
- using Seal of Blood .5sec **after or before** a white hit that procced Seal of Command does White hit damage + Seal of Command damage + Seal of Blood damage on both white hit and Seal of Command hit 

How it should work : 
- **using Seal of Blood .5sec before a white hit does white hit damage + Seal of Blood damage on this hit**
- using Seal of Blood .5sec **after** a white hit does nothing
- using Seal of Blood .5sec **after or before** a white hit that procced Seal of Command does White hit damage + Seal of Command damage + Seal of Blood damage on both white hit and Seal of Command hit 

https://youtu.be/w5YpDd4z7gw
You can see this situation occuring at 0:56 where he is under Seal of Command, then just before the white hit he switches to Seal of Blood. Both Crusader Strike and Judgement are on cooldown yet there are 2 damage numbers : white hit + Seal of Blood. 

Same thing at 1:07 where he is under Seal of Command then switches to Seal of Blood just before the white hit, then Crusader Strike next GCD : White hit damage + Seal of Blood damage + Crusader Strike after. Judgement was in cooldown. 

The idea of seal twisting as a paladin is that you can really use 2 seals at the same time. On Netherwing you can use 2 seals at the same time **only** after Seal of Command procs. 

![image](https://user-images.githubusercontent.com/16052997/55870965-fde80800-5b89-11e9-9ba3-bc00f3fb89d2.png)

**Comment by teddys** [comment]
You don't understand the mechanic.

Switching to blood anytime BEFORE the melee swing with command goes off and hoping for a command proc is just illogical, because you need the command to proc first and it will never proc if command is not up when the melee hit lands
You do blood after the swing with command, not before

**Comment by kyeda** [comment]
Taking advantage of the "lag" or whatever the mechanic involved is not only after. You can clearly see in the video (1:38) that he is doing Seal of Blood before the hit, or at least at the same time. He is not waiting for the proc and just hope it does. On Netherwing this is not possible because Seal of Blood will not be applied no matter what and this is what I am reporting. 

![image](https://user-images.githubusercontent.com/16052997/55864906-a80d6300-5b7d-11e9-8f44-59cf2a77af18.png)
![image](https://user-images.githubusercontent.com/16052997/55865136-1520f880-5b7e-11e9-8129-e077f04f9321.png)

From what I found, on retail people used to twist a little bit before the hit. 
Seal twisting **was** a DPS increase. On Netherwing it is **not**. No one is doing that on T5 because just having Seal of Blood damage when Command procs does not make up for all the time when it doesn't proc and we just do White hit or WFury + White hit instead of White hit + SoB or WFury + White hit + SoB on both.

**Comment by kyeda** [comment]
There is also the fact that Seal of Blood does not apply to the Wind Fury hit during a twist. Wind Fury or not + Seal of Command proc will always do White hit + Command proc hit + SoB + SoB 
instead of White hit + Command proc hit + WF hit + SoB + SoB + SoB as shown here 
![image](https://user-images.githubusercontent.com/16052997/55868220-4dc3d080-5b84-11e9-9090-d3be4d796af7.png)
(yes I know he twisted after the hit but i'm not saying this is not possible)
Should I make another reporting for the WF thingy ?

**Comment by kyeda** [comment]
https://streamable.com/n2c42
You can clearly see that I do exactly the same thing as on the retail video. I twist right **before** the hit and if it happen to be a Seal of Command proc, everything is fine. But if it is not, there is no Seal of Blood hit as there is on the retail video.

**Comment by Excinerus** [comment]
how it currently works:
have SoC up
after the hit that procs SoC use SoB fast
0.5s later you'll see 2 SoB procs popping

**Comment by Morfeush** [comment]
and how the works going ?

**Comment by kyeda** [comment]
Seal twisting was literally used as an advertisement for the server, I don't understand why this did not get more attention from the team

**Comment by Tereneckla** [comment]
After around 5 minutes of trying I had no problem seal twisting.
Using seal of blood ~0.5-0,3 seconds before the auto attack (according to abar auto attack timer) resulted in seal of blood damage in all cases.
