### ISSUE TITLE
Disenchanting items

### ISSUE THREAD

**Issue by Karisterra** [Atlantiss/NetherwingBugtracker#5616]
Good day. Today I found out I cannot disenchant Rough Bronze Shoulders even it is green quality.
![WoWScrnShot_040819_201211](https://user-images.githubusercontent.com/49451919/55820159-1d881d80-5b03-11e9-9e7b-c683fe667dd4.jpg)

**Comment by Dragunovka** [comment]
Pre 3.1

Common quality
124 Armor
Requires Level 17

3.1 Update

Uncommon quality
130 Armor
+3 Strength
+4 Stamina
Requires Level 17

its cos we have very strange core xd
they must be white in tbc

**Comment by Dragunovka** [comment]
feels bad for u mate

**Comment by Godmatik** [comment]
Delete your cache folder while the client is closed, make sure you have Netherwing Tooltip Fix installed. 

The item is actually white and not green.
