### ISSUE TITLE
Arcane missiles

### ISSUE THREAD

**Issue by Karisterra** [Atlantiss/NetherwingBugtracker#5618]
Description: when using mage skill “Arcane missiles” in around 30-40% of cases the last missile is not shoot (no resist visible) in this way only 4 missiles shoot out. The level of the skill does not seem somehow affect this bug. The problem seems stay during few weeks already.

**Comment by ScottieDOESknow** [comment]
Do you know if you are taking a hit when this happens? 
Receiving push-back during a channeled spell will reduce the total ticks.

**Comment by Godmatik** [comment]
#5413
