### ISSUE TITLE
[Ability][Warrior][Charge] Invalid Target

### ISSUE THREAD

**Issue by Thugli** [Atlantiss/NetherwingBugtracker#562]
[//]: # (Enclose links to things related to the bug using http://wowhead.com or any other TBC database.)
[//]: # (You can use screenshot ingame to visual the issue.)
[//]: # (Write your tickets according to the format:)
[//]: # ([Quest][Azuremyst Isle] Red Snapper - Very Tasty!)
[//]: # ([NPC] Magistrix Erona)
[//]: # ([Spell][Mage] Fireball)
[//]: # ([Npc][Drop] Ghostclaw Lynx)
[//]: # ([Web] Armory doesnt work)

**Description**: 
I was unable to use charge on a Stonetusk Boar in Elewynn Forest, as I was getting the error message "Invalid Target". I was able to charge the boar beside it, and I was able to melee the original one just fine, only charge seemed to be affected.

**Current behaviour**:
A video of this behaviour can be seen here:
https://clips.twitch.tv/CogentRelatedCarabeefNomNom

**Expected behaviour**: 
As long as players meet requirements for charge (Range, out of combat etc...), players should be able to charge any mob and not receive this error message.

**Server Revision**: 
2050

**Comment by The14me** [comment]
can u please do .npc info of the mob,will help a lot.

**Comment by Thugli** [comment]
ya, I'll go find the mob and do that

**Comment by Thugli** [comment]
@The14me 
I received the message "You should select a creature" when I typed .npc info

https://clips.twitch.tv/GlutenFreeWimpyChamoisGOWSkull

**Comment by Easyfraggy** [comment]
Duplicate https://github.com/Atlantiss/NetherwingBugtracker/issues/262
