### ISSUE TITLE
Demonic Rune drop rate is incorrect

### ISSUE THREAD

**Issue by Jseay1313** [Atlantiss/NetherwingBugtracker#5620]
**Description**: Demonic rune drop rate in Felwood (and most likely everywhere) is incorrect.

**Current behaviour**: Jadefire mobs have a reported 4 and 5% chance to drop demonic runes

**Expected behaviour**: 8 and 9% drop chance

**Server Revision**: 2930

https://www.wowhead.com/item=12662/demonic-rune 

npc 7108
npc 7107
npc 7111

**Comment by Tenoutoften** [comment]
[Thottbot, 2007, March 19th](http://web.archive.org/web/20070319182048/http://www.thottbot.com:80/i12662)
![](https://i.gyazo.com/f411270bb3905cf7c614927e833a83a5.png)

**Comment by bajkorv** [comment]
I beg to differ, i have personally farmed those mobs more than anyone ever probably and they should be 3-5% ish droprates at least in vanilla and I have trouble thinking they would change the droprates with bc

**Comment by bajkorv** [comment]
Close thread, should be ~3-6% droprate in felwood.
