### ISSUE TITLE
[Quest][Ironforge] Data Rescue

### ISSUE THREAD

**Issue by noradora** [Atlantiss/NetherwingBugtracker#5621]
[//]: # (Enclose links to things related to the bug using http://wowhead.com or any other TBC database.)
[//]: # (You can use screenshot ingame to visual the issue.)
[//]: # (Write your tickets according to the format:)
[//]: # ([Quest][Azuremyst Isle] Red Snapper - Very Tasty!)
[//]: # ([NPC] Magistrix Erona)
[//]: # ([Spell][Mage] Fireball)
[//]: # ([Npc][Drop] Ghostclaw Lynx)
[//]: # ([Web] Armory doesnt work)
[//]: # (To find server revision type `.server info` command in the game chat.)

**Description**: 
I want my coin back!
**Current behaviour**:
Interacting with the console with a punch card in your inventory, with a full inventory, will cause the console to take your existing punch and not give you the new one.
**Expected behaviour**: 
It should probably first check your inventory spaces and not take your punch, and give an inventory full warning.
**Server Revision**: 
2930

**Comment by Evolvee** [comment]
if you mean the gnomeregan matrix machine (punch cards), fixed, if not, reopen pls (and provide more info.. idk what this report is about)
