### ISSUE TITLE
Intervene Blind

### ISSUE THREAD

**Issue by Regimant** [Atlantiss/NetherwingBugtracker#5622]
[//]: # (Enclose links to things related to the bug using http://wowhead.com or any other TBC database.)
[//]: # (You can use screenshot ingame to visual the issue.)
[//]: # (Write your tickets according to the format:)
[//]: # ([Quest][Azuremyst Isle] Red Snapper - Very Tasty!)
[//]: # ([NPC] Magistrix Erona)
[//]: # ([Spell][Mage] Fireball)
[//]: # ([Npc][Drop] Ghostclaw Lynx)
[//]: # ([Web] Armory doesnt work)
[//]: # (To find server revision type `.server info` command in the game chat.)

**Description**: 
Intervene doesnt eat the blind if the warrior is no longer in range of being blinded by the rogue
**Current behaviour**:
If the warrior interves the target, moves away from the rogue, the blind will go through intervene onto the intervened target still
**Expected behaviour**: 
The blind should be sent to the warrior
**Server Revision**: 
Recorded a clip of this happening if necessary.

**Comment by Evolvee** [comment]
no

**Comment by Regimant** [comment]
Yes

**Comment by Evolvee** [comment]
where is your proof

**Comment by Regimant** [comment]
Ill upload video. Test it yourself is best obviously, intervene target then walk away.

**Comment by Regimant** [comment]
Sent you it on discord, it could possibly be this way with other spells aswell.

**Comment by Evolvee** [comment]
proof from retail lol, not from netherwing where you claim its bugged (despite it being public knowledge its working as intended)

**Comment by Regimant** [comment]
What level of aura distance for intervene is being used, 5,10, or 25?

**Comment by Evolvee** [comment]
intervene range

**Comment by Regimant** [comment]
Well the aura has been 3 different distances, the range for the intervene to absorb to the warrior be based off their distance to the intervened target, not the distance to the rogue. With your answer id assume your saying it should absorb if in within distance to intervene the target still, which would be 25yd

**Comment by Evolvee** [comment]
to the intervened target afaik

**Comment by teddys** [comment]
Record a video to show exactly what you mean because this has never happened to me
