### ISSUE TITLE
cant move item away from guild bank and guild log is broken

### ISSUE THREAD

**Issue by yihu0259** [Atlantiss/NetherwingBugtracker#5623]
[//]: # (Enclose links to things related to the bug using http://wowhead.com or any other TBC database.)
[//]: # (You can use screenshot ingame to visual the issue.)
[//]: # (Write your tickets according to the format:)
[//]: # ([Quest][Azuremyst Isle] Red Snapper - Very Tasty!)
[//]: # ([NPC] Magistrix Erona)
[//]: # ([Spell][Mage] Fireball)
[//]: # ([Npc][Drop] Ghostclaw Lynx)
[//]: # ([Web] Armory doesnt work)
[//]: # (To find server revision type `.server info` command in the game chat.)

**Description**: 
cant move some items away from guild bank and shown as a soulbound item
guild log is blank
**Current behaviour**:
cant move or take them away from the guild bank
![1](https://user-images.githubusercontent.com/28259542/55851902-14985a00-5b9e-11e9-9fc6-9b073bbcd617.png)
![2](https://user-images.githubusercontent.com/28259542/55851997-896b9400-5b9e-11e9-9423-62d8470a0340.png)

**Expected behaviour**: 

**Server Revision**: 
2930

**Comment by The14me** [comment]
Rev.3478 not an issue anymore.
Can  be closed.
