### ISSUE TITLE
Undead racial and pvp trinket dont work on some spells

### ISSUE THREAD

**Issue by NsxWarrior** [Atlantiss/NetherwingBugtracker#5624]
[//]: # (Enclose links to things related to the bug using http://wowhead.com or any other TBC database.)
[//]: # (You can use screenshot ingame to visual the issue.)
[//]: # (Write your tickets according to the format:)
[//]: # ([Quest][Azuremyst Isle] Red Snapper - Very Tasty!)
[//]: # ([NPC] Magistrix Erona)
[//]: # ([Spell][Mage] Fireball)
[//]: # ([Npc][Drop] Ghostclaw Lynx)
[//]: # ([Web] Armory doesnt work)
[//]: # (To find server revision type `.server info` command in the game chat.)

**Description**:  In Stratholme(Last boss in Scarlet side: Grand crusader Dathrohan)
The boss uses his CC abilitie sleep, and my undead racial and pvp trinket dont work,

**Current behaviour**:

**Expected behaviour**: 

**Server Revision**:

**Comment by NsxWarrior** [comment]
There is a problem in Stratholme(Last boss in Scarlet side: Grand crusader Dathrohan)
The boss uses his CC abilitie sleep, and my undead racial and pvp trinket dont work,
That sleep spell lasts until boss kills you, im not sure if it is blizzlike, but i definitly can say that my undead racial abilitie and Insignia trinket should drop that spell. There are many ppl solo farming that instance, and i realy hope that u will fix that sleep spell.

**Comment by The14me** [comment]
Rev.3483 Confirmed
https://classic.wowhead.com/npc=10813/balnazzar#comments:id=2843842 (at least for the trinket)

**Comment by Godmatik** [comment]
Stratholme was fully rescripted last year + WotF not working on some abilities fixed a couple weeks ago with new aura branch.
