### ISSUE TITLE
Items been missing from my bag

### ISSUE THREAD

**Issue by ImStiv** [Atlantiss/NetherwingBugtracker#5628]
[CHARNAME] Stive
[QUEST] The Cudgel of Kar'desh
[NPC] Gruul
[NPC][DROP] Earthen Signet

** DESCRIPTION **

Hi guys.

Couple days ago i spoke to Daystar/Narilrave about a problem in BF Heroic (Last boss didn't drop badge and the Green Gem that was dropped in the box simply disappeared when I picked it up.

Then one day after, I had GM <Insert GM name here that i don't remember> come over to BM and talk about the second boss in Heroic that didn't drop a badge or any loot (you simply couldn't open the body).

Now it was Gruul's Lair time. We did a full guild run two days ago and evreyone that had the SSC attun. quest picked up the item (myself included ofc). I went to bed shortly after and woke up the next day to find out that the item was missing and that quest part wasn't complete anymore.

Maybe my char is bugged or something? I know that there's an issue with bags being full but it was not my case in any of the situations.

I can live without those two badges and the green gem that simply didn't drop/disappeared but i really need help with the SSC attun. Gruul's quest item because my guild is starting SSC next week and I can't be out of it. Could I get priority in this subject if possible please?

Thanks in advice,
Stiv.

**Comment by Manaci** [comment]
Fixed
