### ISSUE TITLE
[Gruul's Lair] Damage output

### ISSUE THREAD

**Issue by Realnairoby** [Atlantiss/NetherwingBugtracker#5629]
[//]: # (Enclose links to things related to the bug using http://wowhead.com or any other TBC database.)
[//]: # (You can use screenshot ingame to visual the issue.)
[//]: # (Write your tickets according to the format:)
[//]: # ([Quest][Azuremyst Isle] Red Snapper - Very Tasty!)
[//]: # ([NPC] Magistrix Erona)
[//]: # ([Spell][Mage] Fireball)
[//]: # ([Npc][Drop] Ghostclaw Lynx)
[//]: # ([Web] Armory doesnt work)
[//]: # (To find server revision type `.server info` command in the game chat.)

**Description**: 
Gruul's Damage output is way to high since todays updates.
**Current behaviour**:
Gruul's Hurtful strike hits for 25597 with 8 Stacks of Growth on a full T4 Feraltank with 27.5k armor. 

Gruul's Hurtful strike hits for 26750 with 8 stacks of Growth on a Prot Paladin. 

Gruul's Cave In hits for 11.000 damage.

**Expected behaviour**: 
Hurtful Strike: always hits the second highest aggro target within his melee range; therefore essential that any melee dps classes maintain their aggro level not only below that of the MT, but also below that of the OT. The base damage on Hurtful Strike is 12,350-13,650 (this, of course, is reduced by armor, [Defensive Stance], etc.). A Hurtful Strike is performed on average every 20 seconds. 

Cave In: Random AoE which causes ~3000 damage every 3 seconds in the area. The AoE damage is preceded by ground shake in the affected area and is visible on the roof. This occurs more frequently as the fight progresses. Cave In damage counts as physical damage and can be mitigated by armor. Growth also affects Cave In.
**Server Revision**: 
2936

**Comment by Wolffenstein** [comment]
Fixed after next restart, sorry!
