### ISSUE TITLE
[Ev♂lve][blizzlike][custom changes]

### ISSUE THREAD

**Issue by Wahrheit42** [Atlantiss/NetherwingBugtracker#5631]
[//]: # (Enclose links to things related to the bug using http://wowhead.com or any other TBC database.)
[//]: # (You can use screenshot ingame to visual the issue.)
[//]: # (Write your tickets according to the format:)
[//]: # ([Quest][Azuremyst Isle] Red Snapper - Very Tasty!)
[//]: # ([NPC] Magistrix Erona)
[//]: # ([Spell][Mage] Fireball)
[//]: # ([Npc][Drop] Ghostclaw Lynx)
[//]: # ([Web] Armory doesnt work)
[//]: # (To find server revision type `.server info` command in the game chat.)

**Description**: 
Server was advertised as blizzlike
**Current behaviour**:
Ev♂lve launches custom changes whatever he sees fit to a item mechanic.
**Expected behaviour**: 
Aim to be the closest blizzlike server possible in terms of PVE and PVP gameplay mechanics.
**Server Revision**: 
2936

**Comment by teddys** [comment]
xd

**Comment by Azalen** [comment]
Evolve is a god. Deal with it.

**Comment by Evolvee** [comment]
?xd

**Comment by FuzzNFA** [comment]
If the server could evolve out of this issue that would be great, I agree.
