### ISSUE TITLE
Prayer of Mending healing 25% of value while having Mortal strike effect up

### ISSUE THREAD

**Issue by Hidehugo** [Atlantiss/NetherwingBugtracker#5632]
**Description**: Prayer of Mending Healing only 25% of the bounce healing while in arena while being affected by mortal strike effect

**Current behaviour**: it seems like mortal strike reduces healing of prayer of mending by 75% rather than 50%
In arena: (healing is increased due to Focused Will Talent)
![grafik](https://user-images.githubusercontent.com/47213262/56059866-8373df80-5d65-11e9-87bb-d58d032c2db5.png)
Outside arena:
![grafik](https://user-images.githubusercontent.com/47213262/56059995-d8aff100-5d65-11e9-9919-0833a6f2ef47.png)

**Expected behaviour**: 50% healing reduction properly implemented

**Server Revision**:

**Comment by liderer** [comment]
maybe it's your feelings because of talent Focused WIll  " increasing healing effects on you by Y%" .

**Comment by teddys** [comment]
Healing reduction debuffs stacking confirmed. Wound poison + blood fury = 75% healing reduction (blood fury STILL does not remove poisons btw https://github.com/Atlantiss/NetherwingBugtracker/issues/5326 )

this should absolutely be high prio

**Comment by Evolvee** [comment]
> just remove aura stacking completely loooooooooooool 4Head

- Wolf 2018

**Comment by Wolffenstein** [comment]
I'll fix it next week

**Comment by Hidehugo** [comment]
So this is still only a joke to you and you won't change it before 2.1?

**Comment by teddys** [comment]
The only person who ever cared about pvp on this server is Evolve and because he's not even playing ... noone else cares ... deal with it, wolf is busy with fixing black temple and hyjal (should have been fixed months ago) and doesn't have time for pvp fixes

**Comment by Hidehugo** [comment]
Is this being adressed at one point or does Evolve have to port somebody to Testing zone before smthin can happen?

**Comment by Wolffenstein** [comment]
Fixed
