### ISSUE TITLE
reputation not worked

### ISSUE THREAD

**Issue by Krap3c** [Atlantiss/NetherwingBugtracker#5633]
[//]: # (Enclose links to things related to the bug using http://wowhead.com or any other TBC database.)
[//]: # (You can use screenshot ingame to visual the issue.)
[//]: # (Write your tickets according to the format:)
[//]: # ([Quest][Azuremyst Isle] Red Snapper - Very Tasty!)
[//]: # ([NPC] Magistrix Erona)
[//]: # ([Spell][Mage] Fireball)
[//]: # ([Npc][Drop] Ghostclaw Lynx)
[//]: # ([Web] Armory doesnt work)
[//]: # (To find server revision type `.server info` command in the game chat.)

**Description**: 
Me cenarion reputation cant be increased. Please fix it i need farm it for HC dungeon or set me it to full please... Thx 

Nick in game KpC 
undead priest
**Current behaviour**:

**Expected behaviour**: 

**Server Revision**:

**Comment by Evolvee** [comment]
how are u trying to increase it?
