### ISSUE TITLE
[Quest][Zul'Farrak] The Spider God

### ISSUE THREAD

**Issue by Badnboujee** [Atlantiss/NetherwingBugtracker#5635]
**Description**:[Quest][Zul'Farrak] The Spider God
http://tbc.cavernoftime.com/quest=2936
https://www.wowhead.com/object=142715/tablet-of-theka#screenshots:id=267108
my PoV : https://www.youtube.com/watch?v=mGBcn2e0jbM&feature=youtu.be
**Current behaviour**:Can't read the Tablet of Theka

**Expected behaviour**:Everyone tells me that quest works fine but not my case 
IG : Badnboujee
**Server Revision**: 2939

**Comment by Manaci** [comment]
Works fine, must've been a client issue
