### ISSUE TITLE
[NPC][Theramore] Captain Garran Vimes

### ISSUE THREAD

**Issue by noradora** [Atlantiss/NetherwingBugtracker#5636]
[//]: # (Enclose links to things related to the bug using http://wowhead.com or any other TBC database.)
[//]: # (You can use screenshot ingame to visual the issue.)
[//]: # (Write your tickets according to the format:)
[//]: # ([Quest][Azuremyst Isle] Red Snapper - Very Tasty!)
[//]: # ([NPC] Magistrix Erona)
[//]: # ([Spell][Mage] Fireball)
[//]: # ([Npc][Drop] Ghostclaw Lynx)
[//]: # ([Web] Armory doesnt work)
[//]: # (To find server revision type `.server info` command in the game chat.)

**Description**: 
This NPC doesn't offer the quest after speaking with him.
**Current behaviour**:
You can get dialogue about the quest but he doesn't offer it.
**Expected behaviour**: 
https://www.wowhead.com/quest=27249/inspecting-the-ruins
**Server Revision**: 
2939

**Comment by noradora** [comment]
Note that you can still just go to the quest turn-in spot and pick up the next quests, so you aren't blocked from proceeding.

**Comment by Godmatik** [comment]
Works just fine for me - you must get the pre-req "They call him Smiling Jim"
