### ISSUE TITLE
Aggro on Magtheridon

### ISSUE THREAD

**Issue by femdead** [Atlantiss/NetherwingBugtracker#5637]
it's totally fucked, he's targetting the channeler tanks instead of the tank attacking him
could be aggro from channelers is applying to the boss or something retarded
not misdirecting other tanks or anything

**Comment by femdead** [comment]
Also before blast nova he aggros on a random raid member for no reason, should not be a mechanic

**Comment by Firroth** [comment]
Did maggy today, wasn't issue for me. One shield slam and boss was on me.

**Comment by Easyfraggy** [comment]
Probably just had your tanks on channelers with earth shield and PoM. Agro is not bugged on mag.

**Comment by gabbat** [comment]
requesting reopen with proof @Easyfraggy :
https://www.youtube.com/watch?v=_G2rIqWVXQU
check video at 3:07 : add tank gets aggro (far away over the room) just before blast nova happens. 
we had that happen very very often, multiple times during our attempts. it did not happen every time, but often enough to call it a bug, as he always went for the same add tank. or is magtheridon supposed to reset aggro just before casting blast nova and somehow earthshield always just ticked then?

**Comment by femdead** [comment]
This was closed prematurely. The aggro loss before each blast wave happens consistently enough that I have no idea how it was missed so far in testing, and Earth Shield and PoM do not explain Mag wailing on the 5th channeler tank for the entire attempt with 5 stacks of mangle + MD on the feral tank unable to rip aggro off of him despite not attacking the boss once. The threat table is clearly broken.

**Comment by Easyfraggy** [comment]
Your tank is disoriented by the fire - you loose agro when you are disoriented. No bug here.

**Comment by Easyfraggy** [comment]
![image](https://user-images.githubusercontent.com/36134067/56531564-8edcbd00-6554-11e9-9275-229a9e960cfb.png)

**Comment by gabbat** [comment]
sorry but wrong, the conflagration gets put onto the tank AFTER the offtank gets targeted. the threat loss is before the conflag even happens, rewatch the video.

**Comment by gabbat** [comment]
also to elaborate further on this: conflag fire cant be shot on the current threat target. so the only way our MT could get the fire was because he actually lost aggro, which further proofs the point

**Comment by Easyfraggy** [comment]
Thats just UI lag - you can clearly see that the tank is conflagged when the agro switch happens.

If you watch a few seconds later magtheridon shoots a new fire - meaning your tank walked into an existing fire - not mag throwing a new one on him. The fires have bigger radius than the animation.

**Comment by gabbat** [comment]
assuming you are correct and it is indeed interface lag, why does mag always (like 10 out of 10 times this happens) run to the channeler tank, when he should just target anyone with the highest aggro on him? (which cant be the channeler tank, as he has literally 0 aggro on him, while every healer has like a billion)

**Comment by Easyfraggy** [comment]
He hasn't done this a single time for me. If you can supply video of him actually doing it when the tank isn't conflagged that would be helpful.

On the video you linked he kills the healers and doesn't run to the offtank. He does target him at first strangely.

**Comment by Easyfraggy** [comment]
I'll reopen for now so others can see the issue and possibly pitch in - I'll assign Need Research - but I don't think theres a bug here - atleast not mag specific.

**Comment by Easyfraggy** [comment]
Spoke to another guild seems they also have the issue - might be valid after all. Very strange.

**Comment by gabbat** [comment]
still happening.

**Comment by gabbat** [comment]
another proof of magtheridon aggro beeing fucked after channeling:
https://clips.twitch.tv/SaltyImportantNewtPastaThat
idk what there is to research, numerous guilds know that the aggro is bugged, when do we get a dev to check the code?

**Comment by Firroth** [comment]
As to my last post from April (15), I am taking back what I wrote. 
This bug indeed exists and it's annoying. It always happens just before clicking the cubes (around 1 to 3s) before he starts channeling Blast Nova. 
It's annoying in term cause he goes for clicker even if he doesn't reach them in the end, before going back for the tank, which in turn makes him change his position - it's annoying to move him back into it so he won't cover cube near him or "cleave" melee during it.

**Comment by Godmatik** [comment]
Fixed at some point I presume.

Have done Magtheridon numerous times and never came across the issue. Mag always stays on the tank, never targets any of the channelers. And have not heard of anyone else having this issue in the past year.

Closing.
