### ISSUE TITLE
[Spell][Warrior] Spell Reflection

### ISSUE THREAD

**Issue by ghost** [Atlantiss/NetherwingBugtracker#5639]
[//]: # (Enclose links to things related to the bug using http://wowhead.com or any other TBC database.)
[//]: # (You can use screenshot ingame to visual the issue.)
[//]: # (Write your tickets according to the format:)
[//]: # ([Quest][Azuremyst Isle] Red Snapper - Very Tasty!)
[//]: # ([NPC] Magistrix Erona)
[//]: # ([Spell][Mage] Fireball)
[//]: # ([Npc][Drop] Ghostclaw Lynx)
[//]: # ([Web] Armory doesnt work)
[//]: # (To find server revision type `.server info` command in the game chat.)

**Description**: Spell reflection is a skill warriors can use to reflect projectiles before they leave their caster. The reflected spell will work as if the original caster cast it on him/herself. This means that its damage (if applicable) will not be modified by the 10% outgoing damage reduction from Defensive Stance (or any other damage modifiers affecting you). The reflected ability can be resisted (uses spell hit chance of the caster).

**Current behaviour**: Alot of the time in PvP, it doesnt do anything at all, it says you reflect but nothing happens. Aswell as when it actually does reflect back and damage the caster, it does minimal damage, if any at all. Most of the time reflecting a shatter combo does nothing at all to the caster. I have found that Spell Reflection works in PvE though, and in PvE you see the damage it does. In PvP you never see the damage, and 99% of the time there is no damage.

**Expected behaviour**: The reflect spell should mirror the casters stats when he casted it, and not be affected by either defensive stance or the warriors' low spell damage. The Warrior should also see the damage the spell did in his combat log. Now it just says "Yyy's Frostbolt was reflected by Xxx".
https://youtu.be/JbqGayDUeL0?t=8 <- This is how it should work(Full damage back at the caster and warrior should see the damage it does)

**Server Revision**: 2939

**Comment by Azalen** [comment]
Please give Spell Reflect a major overhaul. There are so many things about it broken right now starting with no damage shown as reflected, false combat bug and delayed reflection even though the buff is up.

**Comment by Easyfraggy** [comment]
It works fine for all intents and purposes in PvE - This is a PvP issue if anything please don't derail the thread.

**Comment by bajkorv** [comment]
New information on this bug:
- I’ve realized that spell reflection only does not work if you dont have the caster as your current target. This is only true for damaging spells, which will never reflect damage back at the caster if you dont have him targeted


- When you do have the caster targeted and reflect, damage usually reflects, however, does do less damage than what it would if it was a hit and not reflect.. For example this shaman shoots me with lightning bolt for ~1400 damage, if i reflect it - it does 1000-1100 damage approximately

**Comment by Wolffenstein** [comment]
Finally some good info how to reproduce, I'll check it out

**Comment by Wolffenstein** [comment]
Nope, still can't reproduce

**Comment by bajkorv** [comment]
I was targeting something else when we did the testing, perhaps you were not targeting anything, didnt really try that.

**Comment by Wolffenstein** [comment]
I tried both targetting self, something else as well as targetting nothing. There must be more to it

**Comment by tsuone** [comment]
@Wolffenstein What if reflected ability does resist calculation one more time when reflected?

**Comment by Godmatik** [comment]
Unable to reproduce - reflected spell hits everytime.

Regarding the low damage - There is a bug about how the spell reflected spell is using the warrior's spell power to calculate the damage and not the original caster - there is already a separate thread open about this.
