### ISSUE TITLE
[Core mechanic] Combat does state does not end once all enemies are dead 

### ISSUE THREAD

**Issue by Maelareth** [Atlantiss/NetherwingBugtracker#564]
[//]: # (Enclose links to things related to the bug using http://wowhead.com or any other TBC database.)
[//]: # (You can use screenshot ingame to visual the issue.)
[//]: # (Write your tickets according to the format:)
[//]: # ([Quest][Azuremyst Isle] Red Snapper - Very Tasty!)
[//]: # ([NPC] Magistrix Erona)
[//]: # ([Spell][Mage] Fireball)
[//]: # ([Npc][Drop] Ghostclaw Lynx)
[//]: # ([Web] Armory doesnt work)

**Description**: Sometimes after killing several mobs at the same time by entering combat one by one the combat state does not end once all enemies are dead. 

**Current behaviour**: At times combat state does not end once combat is over

**Expected behaviour**: Combat should enter upon attacking or getting attacked by enemy. Once attacker or attackers are dead or left combat by range combat state should end. 

**Server Revision**: 2050
![combatbug](https://user-images.githubusercontent.com/10581286/46034737-b2946d80-c101-11e8-8ee0-bc4cf9b44ea1.jpg)

**Comment by The14me** [comment]
its not set at stone.Blizzlike

**Comment by Maelareth** [comment]
> > its not set at stone.Blizzlike
> 
> ???
> 
> To the OP, can you specify for me, did you get stuck in combat, and if yes for how long?

I was stuck in combat until i quit the game. Nothing seemed to fix it e.g. time or range to area in which i got in combat the first place. The screenshot can show you exactly where it happened

**Comment by The14me** [comment]
@Maelareth  my bad,missread the report.Sorry about : )

**Comment by Maelareth** [comment]
> @Maelareth my bad,missread the report.Sorry about : )

No worries!

**Comment by 5f3759** [comment]
A few days ago we (entire party) got stuck in combat about halfway through Wailing Caverns.
Alt+F4 got me out of combat but got stuck after each fight again. Exiting the instance did fix it though.
I did another WC the next day and it didn't happen then.

Unfortunately I didn't record the event or remember what happened that triggered this.

**Comment by Tereneckla** [comment]
Fixed (except sometimes in dungeons)
