### ISSUE TITLE
Items missing from Alliance Auction House

### ISSUE THREAD

**Issue by Quot89** [Atlantiss/NetherwingBugtracker#5640]
[//]: # (Enclose links to things related to the bug using http://wowhead.com or any other TBC database.)
[//]: # (You can use screenshot ingame to visual the issue.)
[//]: # (Write your tickets according to the format:)
[//]: # ([Quest][Azuremyst Isle] Red Snapper - Very Tasty!)
[//]: # ([NPC] Magistrix Erona)
[//]: # ([Spell][Mage] Fireball)
[//]: # ([Npc][Drop] Ghostclaw Lynx)
[//]: # ([Web] Armory doesnt work)
[//]: # (To find server revision type `.server info` command in the game chat.)

**Description**: 
Missing items from AH
**Current behaviour**:
Character: Quot/ Alliance/ Human paladin/ server: Netherwing
I had following items stored in Alliance Auction House:
4x Felsteel leggings
https://tbc-twinhead.twinstar.cz/?item=23518 / https://www.wowhead.com/item=23606/plans-felsteel-leggings
1x Ragesteel helm
https://tbc-twinhead.twinstar.cz/?item=23521 / https://www.wowhead.com/item=23521/ragesteel-helm

After auction ended (like 3 days approx.) nothing has arrived back to my mailbox. It dissapeared from AH and from my post.

I tried to delete my WDB, switch of all my addons but without any luck they are lost:(
**Expected behaviour**: 
When your auction items in AH expires they are expected to return via ingame mail.
**Server Revision**:

**Comment by nillify** [comment]
I also had items disappear recently.   Nothing of much value; but same behavior.   The items ended without being bought but they never showed up.

Mine were random low-level greens.   (2-3 that I know of, not sure how much else has disappeared over time).

**Comment by Excinerus** [comment]
confirming this, bid on 5 stacks of fel iron bars, the auction ended and i didn't get the bars nor the gold back

**Comment by Firroth** [comment]
I lost today couple of meta gems cause of it, it is really annoying bug, I'm scared of posting on AH now cause of it, more items...
