### ISSUE TITLE
[NPC] Enchanted Elementals on Lady Vashj Evade Bug

### ISSUE THREAD

**Issue by Thugli** [Atlantiss/NetherwingBugtracker#5644]
[//]: # (Enclose links to things related to the bug using http://wowhead.com or any other TBC database.)
[//]: # (You can use screenshot ingame to visual the issue.)
[//]: # (Write your tickets according to the format:)
[//]: # ([Quest][Azuremyst Isle] Red Snapper - Very Tasty!)
[//]: # ([NPC] Magistrix Erona)
[//]: # ([Spell][Mage] Fireball)
[//]: # ([Npc][Drop] Ghostclaw Lynx)
[//]: # ([Web] Armory doesnt work)
[//]: # (To find server revision type `.server info` command in the game chat.)

**Description**: 
Enchanted Elementals frequently evading.
**Current behaviour**:
I'm a shadow priest and the first 1-2 casts I made on every enchanted elemental evaded, regardless of whether I was standing on the stairs or on the top of the platform.
**Expected behaviour**: 
These mobs should not evade.
**Server Revision**: 
2939

**Comment by Thugli** [comment]
Was not able to take a screenshot of my combat log as my combat log was wiped, which I assume was done automatically but one of my addons that fixes my combat log to avoid breaking recount or omen.

**Comment by teddys** [comment]
confirming this, the mobs sometimes randomly evade (and/or completely reset their hp)

**Comment by Tenoutoften** [comment]
It's a lot better with video than screenshots of a combat log...

**Comment by Thugli** [comment]
> It's a lot better with video than screenshots of a combat log...

Well yeah, but I wasn't recording.. so combat log would have been the next best thing. Thanks for the tip though, never crossed my mind /s

**Comment by Wolffenstein** [comment]
Fixed in rev 2941.
