### ISSUE TITLE
Cant See Messenges in the Guild chat 

### ISSUE THREAD

**Issue by Bargess** [Atlantiss/NetherwingBugtracker#5645]
[//]: # (Enclose links to things related to the bug using http://wowhead.com or any other TBC database.)
[//]: # (You can use screenshot ingame to visual the issue.)
[//]: # (Write your tickets according to the format:)
[//]: # ([Quest][Azuremyst Isle] Red Snapper - Very Tasty!)
[//]: # ([NPC] Magistrix Erona)
[//]: # ([Spell][Mage] Fireball)
[//]: # ([Npc][Drop] Ghostclaw Lynx)
[//]: # ([Web] Armory doesnt work)
[//]: # (To find server revision type `.server info` command in the game chat.)

**Description**: i cant see the messenges i've written in the Guild chat 

**Current behaviour**:
i cant see the messenges i've written in the Guild chat 

**Expected behaviour: i should See the messenges that i've written in the Guild chat 

**Server Revision**:

**Comment by danbopes** [comment]
This is something the Game Master's need to handle. Create a ticket, and wait for them to follow up. /issue

**Comment by Tenoutoften** [comment]
This can be solved by relogging and maybe /reload ui
It is definitely resolved after a client restart
