### ISSUE TITLE
greater blessing of kings

### ISSUE THREAD

**Issue by joceanlab** [Atlantiss/NetherwingBugtracker#5646]
[//]: # (Enclose links to things related to the bug using http://wowhead.com or any other TBC database.)
[//]: # (You can use screenshot ingame to visual the issue.)
[//]: # (Write your tickets according to the format:)
[//]: # ([Quest][Azuremyst Isle] Red Snapper - Very Tasty!)
[//]: # ([NPC] Magistrix Erona)
[//]: # ([Spell][Mage] Fireball)
[//]: # ([Npc][Drop] Ghostclaw Lynx)
[//]: # ([Web] Armory doesnt work)
[//]: # (To find server revision type `.server info` command in the game chat.)

**Description**: Whenever you respec you have to re-learn greater blessing of kings. Even though it's a talent just like blessing of sanc which you don't have to relearn the greater version

**Current behaviour**: Have to relearn GBoK from trainer after each respec

**Expected behaviour**: Should stay learned like the other talented blessing

**Server Revision**: 2939

**Comment by EnterLarry** [comment]
The same goes for other talent buffs such as Divine Spirit.

**Comment by Tenoutoften** [comment]
You also lose the 10% stats resources granted by the buff if you rebuff.
https://github.com/Atlantiss/NetherwingBugtracker/issues/3280

**Comment by totaemoeggerli** [comment]
this is still an issue

**Comment by Wolffenstein** [comment]
Fixed in rev 3533.
