### ISSUE TITLE
[Item] Dragonspine Trophy internal cooldown

### ISSUE THREAD

**Issue by quapuzi** [Atlantiss/NetherwingBugtracker#5647]
**Description**: Dragonspine Trophy appears to have an ICD of 29seconds, while it shouldnt have any.

**Current behaviour**:
https://imgur.com/a/TC2k2y2
Ive run Procodile for about 2 Weeks now and ive never had a DST proc faster than every 29seconds. 

**Expected behaviour**: 
It should have no cooldown at this point and should be nerfed with 2.2 to a 20seconds internal cd. Its not easy to find patchnotes to this, since it has been hotfixed in 2.2, you can just find wowhead comments etc. Its not even in undocumented changes.
https://www.wowhead.com/item=28830/dragonspine-trophy#comments:id=140159:reply=310352
I've also heard they've hotfixed // adding in patch 2.2 an internal cooldown for this beast.

https://www.wowhead.com/item=28830/dragonspine-trophy#comments:id=140159:reply=18360
Hidden cooldown is 20 seconds

Comment from patch 2.0:
https://www.wowhead.com/item=28830/dragonspine-trophy#comments:id=82559
It procced every second or third mob, sometimes it would proc 2 times in 1 fight, and Afaik there is a very little cooldown or none at all, as i've seen it refresh its self before the buff ran out.

Also comment from another private server:
From wiki: "This item has a 20 second hidden cooldown. The proc rate is 1ppm. Uptime averages around 25%."
It was nerfed to this state in 2.2.0. 

Not sure if this is helpful but patchnote from mangos:
https://www.getmangos.eu/forums/topic/357-patch6538-dragonspine-trophy-trinket/

**Server Revision**: 
2939

**Comment by Evolvee** [comment]
spell mechanics were not a subject for change when 2.0 items were being overridden
