### ISSUE TITLE
[Item] [Gnomish Poultrizer] Not breaking on damage

### ISSUE THREAD

**Issue by b15andga** [Atlantiss/NetherwingBugtracker#5648]
[//]: # (Enclose links to things related to the bug using http://wowhead.com or any other TBC database.)
[//]: # (You can use screenshot ingame to visual the issue.)
[//]: # (Write your tickets according to the format:)
[//]: # ([Quest][Azuremyst Isle] Red Snapper - Very Tasty!)
[//]: # ([NPC] Magistrix Erona)
[//]: # ([Spell][Mage] Fireball)
[//]: # ([Npc][Drop] Ghostclaw Lynx)
[//]: # ([Web] Armory doesnt work)
[//]: # (To find server revision type `.server info` command in the game chat.)

**Description**: 
Turns the target into a chicken for 15 sec. The effect is called Poultryized! and says "Cannot cast spells and damage is reduce by 66%." The effect is broken by any damage.
https://wow.gamepedia.com/Gnomish_Poultryizer
**Current behaviour**:
Does not always break on damage. This, for instance, kept me poultrized, silenced and slowed for 12 seconds while being pounded by this cheeky dude.
https://imgur.com/a/NCnS1jX
**Expected behaviour**: 
The effect SHOULD BE broken by any damage.
**Server Revision**: 
2939

**Comment by sabutnoy** [comment]
as of August 6th, the bug is still not fixed
**Expected behaviour:**
The effect SHOULD BE broken by any damage.
but this does not happen

**Comment by Wolffenstein** [comment]
Can't reproduce. Need more info as to what exactly prevents it from breaking since no matter what damage ability i try, it always breaks.
