### ISSUE TITLE
[Core] Stealth - Rev 2939

### ISSUE THREAD

**Issue by Greytt** [Atlantiss/NetherwingBugtracker#5649]
[//]: # (Enclose links to things related to the bug using http://wowhead.com or any other TBC database.)
[//]: # (You can use screenshot ingame to visual the issue.)
[//]: # (Write your tickets according to the format:)
[//]: # ([Quest][Azuremyst Isle] Red Snapper - Very Tasty!)
[//]: # ([NPC] Magistrix Erona)
[//]: # ([Spell][Mage] Fireball)
[//]: # ([Npc][Drop] Ghostclaw Lynx)
[//]: # ([Web] Armory doesnt work)
[//]: # (To find server revision type `.server info` command in the game chat.)

**Description**:  Mobs will find you in stealth way to easy. 

**Current behaviour**: Can't even get in range for pickpocket - Shadow step sap doesn't always work becasue they will find you before sap goes off. 

**Expected behaviour**: To be able to use stealth.

**Server Revision**: 2939

Video showing how bad it is: https://youtu.be/y2gqragygPs

This is with 5/5 Master of Deception.

**Comment by Wolffenstein** [comment]
![image](https://user-images.githubusercontent.com/1576644/56149506-02a72480-5fad-11e9-8a8e-5e01802f1c58.png)

I mean you are right in front of him when he turns around. Master of Deception at 5/5 grants only +15 bonus stealth level, which is not enough to offset the close distance to the mob you've shown.

**Comment by Greytt** [comment]
> ![image](https://user-images.githubusercontent.com/1576644/56149506-02a72480-5fad-11e9-8a8e-5e01802f1c58.png)
> 
> I mean you are right in front of him when he turns around. Master of Deception at 5/5 grants only +15 bonus stealth level, which is not enough to offset the close distance to the mob you've shown.

So on the second one, I am not even suppsoed to get in range for pickpocket without being attacked? I also get attack before I can get improved sap off. 
If 5/5 MoD + Imp sap is not enough to use sap then something is absolutely wrong.

**Comment by Wolffenstein** [comment]
The second one also turned around just as you were getting close:

![image](https://user-images.githubusercontent.com/1576644/56159202-61c46380-5fc4-11e9-9a9f-070e669399b6.png)

If a mob of the same level didn't detect you from this range while you're in front of him, something would be really wrong.

**Comment by Greytt** [comment]
> The second one also turned around just as you were getting close:
> 
> ![image](https://user-images.githubusercontent.com/1576644/56159202-61c46380-5fc4-11e9-9a9f-070e669399b6.png)
> 
> If a mob of the same level didn't detect you from this range while you're in front of him, something would be really wrong.

Ok

**Comment by Wolffenstein** [comment]
The exact stealth formula isn't known so it's an approximation of how it worked on retail - therefore isn't fully accurate, but the behaviour showcased on those videos does look to work as intended.
