### ISSUE TITLE
[NPC] Sarilus Foulborne hostile to Horde

### ISSUE THREAD

**Issue by totaemoeggerli** [Atlantiss/NetherwingBugtracker#565]
[//]: # (Enclose links to things related to the bug using http://wowhead.com or any other TBC database.)
[//]: # (You can use screenshot ingame to visual the issue.)
[//]: # (Write your tickets according to the format:)
[//]: # ([Quest][Azuremyst Isle] Red Snapper - Very Tasty!)
[//]: # ([NPC] Magistrix Erona)
[//]: # ([Spell][Mage] Fireball)
[//]: # ([Npc][Drop] Ghostclaw Lynx)
[//]: # ([Web] Armory doesnt work)

**Description**: 
https://www.wowhead.com/npc=3986/sarilus-foulborne#comments
Undead NPC on top Dreadmist Mountain in The Barrens

**Current behaviour**:
Is hostile to Horde

**Expected behaviour**: 
Shouldn't be hostile
Druids can't finish the quest https://www.wowhead.com/quest=6127/the-principal-source#screenshots
From wowhead comment:
By MooPoo (1,396 –  2·16)  on 2007/02/09 (Patch 2.0.6) 
"... You will also see an Undead that is Yellow to you and will not attack you, until you fill the flask. Once you fill it just run down or kill him."

**Server Revision**:

**Comment by aresbrutus** [comment]
Confirmed. He should start out as neutral and attack the player if they fill the flask for the quest https://www.wowhead.com/quest=6127/the-principal-source @Evolvee

**Comment by xmesaj2** [comment]
fix in rev 2054
