### ISSUE TITLE
[Spells][Rogue][Vanish Stealth][PvP Bugabuse] Removing stealth while under vanish doesnt cancel vanish thus still stealth at FULL movespeed !

### ISSUE THREAD

**Issue by Lockanloads** [Atlantiss/NetherwingBugtracker#5650]
**Description**: 
Removing Stealth while under Vanish doesnt cancel the Vanish buff so the rogue will remain Improved stealth at FULL movespeed (like if he was unstealthed walking) !
**Current behaviour**:
This bug abuse is INSANE on a human rogue vs a stealth comp.
**Expected behaviour**: 
![Maul](https://user-images.githubusercontent.com/47344478/56212236-e8775000-6059-11e9-9152-b7e86e1246e3.jpg)

Removing stealth should cancel the vanish buff SO the rogue shouldnt be stealth at all.
https://user-images.githubusercontent.com/47344478/56211775-ed87cf80-6058-11e9-939a-a3a072e87d48.jpg)

I hope you can find a fix, and also that its a recent bug.
**Server Revision**:

**Comment by Wolffenstein** [comment]
Fixed in rev 2943.
