### ISSUE TITLE
[PvP][Stealth] Seeing stealthed enemies when you're in ghostform in the arena.

### ISSUE THREAD

**Issue by b15andga** [Atlantiss/NetherwingBugtracker#5651]
[//]: # (Enclose links to things related to the bug using http://wowhead.com or any other TBC database.)
[//]: # (You can use screenshot ingame to visual the issue.)
[//]: # (Write your tickets according to the format:)
[//]: # ([Quest][Azuremyst Isle] Red Snapper - Very Tasty!)
[//]: # ([NPC] Magistrix Erona)
[//]: # ([Spell][Mage] Fireball)
[//]: # ([Npc][Drop] Ghostclaw Lynx)
[//]: # ([Web] Armory doesnt work)
[//]: # (To find server revision type `.server info` command in the game chat.)

**Description**: 
**Current behaviour**:
Can see stealthed enemies while in ghostform in the arena.
https://imgur.com/a/9Xae2Zj
**Expected behaviour**: 
Should not see stealthed enemies while in ghostform in the arena
**Server Revision**: 
2939

**Comment by Godmatik** [comment]
Fix has already been put in for upcoming 2941 rev, just need to wait for devs to restart servers and update them.
