### ISSUE TITLE
Windy Clouds in Nagrand Missing

### ISSUE THREAD

**Issue by ryang1989** [Atlantiss/NetherwingBugtracker#5653]
[//]: # (Enclose links to things related to the bug using http://wowhead.com or any other TBC database.)
[//]: # (You can use screenshot ingame to visual the issue.)
[//]: # (Write your tickets according to the format:)
[//]: # ([Quest][Azuremyst Isle] Red Snapper - Very Tasty!)
[//]: # ([NPC] Magistrix Erona)
[//]: # ([Spell][Mage] Fireball)
[//]: # ([Npc][Drop] Ghostclaw Lynx)
[//]: # ([Web] Armory doesnt work)
[//]: # (To find server revision type `.server info` command in the game chat.)

**Description**: 

**Current behaviour**: Windy Clouds do not spawn in Nagrand. After hours of flying all around the zone, 0 clouds pop up on my mini-map or are visible.

**Expected behaviour**:  Wind clouds should spawn all throughout Nagrand.

**Server Revision**:

**Comment by EnterLarry** [comment]
Added in patch 2.3.0.7521

We're on 2.0.3 currently

**Comment by Dimbleglim** [comment]
Then SSC should be closed as it wasn't open untill patch 2.1

**Comment by Kolmarwow** [comment]
serpentshrine is 2.0.3...not 2.1

tbc had kara + gruul + ssc + tk + mag + even hyjal on launch, so the only non-blizzlike thing is that hyjal isn't released yet on netherwing afaik (which would be understandable, blizzard were crazy to release 80% of the raid content on release)

**Comment by Easyfraggy** [comment]
> Then SSC should be closed as it wasn't open untill patch 2.1

:wutface:
