### ISSUE TITLE
[Spell][Hunter] Eyes of the Beast

### ISSUE THREAD

**Issue by czarecoo** [Atlantiss/NetherwingBugtracker#5654]
**Description**: 
Using Dash while controlling your pet with Eyes of the Beast, does not grant movement speed to pet. Furthermore, if you cast Dash before Eyes of the Beast, the pet will have increased movement speed for the whole Eyes of the Beast duration (even after Dash buff expires).
**Current behaviour**:
Look above
**Expected behaviour**: 
-Using dash during Eyes of the Beast, should grant movement speed as specified in tooltip.
-When you cast Dash before Eyes of the Beast, the movement speed should be returned to normal after buff expires.
**Server Revision**: 
2939

**Comment by The14me** [comment]
Rev.3483 not an issue anymore.
