### ISSUE TITLE
[Raid][SSC] Leotheras The blind - Whirlwind

### ISSUE THREAD

**Issue by Firroth** [Atlantiss/NetherwingBugtracker#5655]
**Current behaviour**:

His Whirlwind ability seems to be "lagging", which in return gives players more time to move out of range.

How it behaves on the server, couple of videos:
https://youtu.be/C6xTFgjzqco?t=1030
https://youtu.be/jZM7PfIeVqA?t=10841
https://youtu.be/ZjiKyGcpWjk?t=350

It's very easy to avoid it now.

Also I think his dmg is too low. He meele hits Shaman enh (no shield) for 2-3k (so tank gets hit for 500-1k?)
Correct me if I'm wrong, but I saw it happening here.

**Expected behaviour**: 

His whirlwind ability shouldn't be "lagging" like seen here f.e 
https://youtu.be/VbgkWIHbsoU?t=267

And he should deal 2k-3k dmg on plate tank.

**Comment by Manaci** [comment]
Fixed
