### ISSUE TITLE
 Resilience Bug

### ISSUE THREAD

**Issue by ufc123** [Atlantiss/NetherwingBugtracker#5656]
Resilience Bug
Calculator for resilience dosnt work good  ! With s1 boots my hunter have 219 res , but without boots have 203 (s1 boots give 18 ressi )
Give u screanshots !
https://cdn.discordapp.com/attachments/567443453198204945/567443652909989898/WoWScrnShot_041519_231715.jpg
https://cdn.discordapp.com/attachments/567443453198204945/567443657402351646/WoWScrnShot_041519_231722.jpg

**Comment by EnterLarry** [comment]
Not a bug.
We're in 2.0 - the stats are different.
![2.0 Stats](https://i.imgur.com/xwJV6E1.png)

I suggest installing the Netherwing Tooltip Fix (2.0) addon
[NWTooltipFix](https://github.com/nullfoxh/NWTooltipFix)

Remember to clear your cache.
