### ISSUE TITLE
Deep thunder stun shares dr with hammer of justice

### ISSUE THREAD

**Issue by teddys** [Atlantiss/NetherwingBugtracker#5657]
**Description**:  @ title

**Current behaviour**: deep thunder stun shares dr with hammer of justice
**Expected behaviour**:  deep thunder stun is random stun and hammer of justice is controlled stun .. 2 different dr categories

**Server Revision**:  2939

**Comment by Wolffenstein** [comment]
Fixed in rev 2943.
