### ISSUE TITLE
[Hunter] [Frost Trap]  Players sometimes are entirely unaffected.

### ISSUE THREAD

**Issue by gunzbngbng** [Atlantiss/NetherwingBugtracker#5658]
[//]: # (Enclose links to things related to the bug using http://wowhead.com or any other TBC database.)
[//]: # (You can use screenshot ingame to visual the issue.)
[//]: # (Write your tickets according to the format:)
[//]: # ([Quest][Azuremyst Isle] Red Snapper - Very Tasty!)
[//]: # ([NPC] Magistrix Erona)
[//]: # ([Spell][Mage] Fireball)
[//]: # ([Npc][Drop] Ghostclaw Lynx)
[//]: # ([Web] Armory doesnt work)
[//]: # (To find server revision type `.server info` command in the game chat.)

**Description**: Frost Trap is intended to slow any player or NPC in it's area that is not immune to it's effects.

**Current behaviour**: Sometimes, players or NPCs are entirely unaffected by Frost Trap, running through it multiple times without being slowed at all.

**Expected behaviour**: If a hostile player is in the Frost Trap, it should apply it's slow and cause entrapment procs, assuming they do not have BoF or another immune effect.

**Server Revision**: 2939

**Comment by Manaci** [comment]
Fixed in rev 3214
