### ISSUE TITLE
Hunter Auto-Shot Interruption 

### ISSUE THREAD

**Issue by Echoxias** [Atlantiss/NetherwingBugtracker#566]
**Description**: 
I had the interrupt auto-shot glitch occur to me after a patch was issued that was supposed to fix it.  I'm not entirely sure how to reproduce how it was caused, think it just happens at random.
**Current behaviour**:
Randomly causes my auto shot to keep being "interrupted."
**Expected behaviour**: 
Auto-shot should continue shooting without interruption.
**Server Revision**: 
[2052]

**Comment by Easyfraggy** [comment]
We need a way to reproduce this so wolf can find the issue.

**Comment by Tenoutoften** [comment]
2077 - 2018 / 09 / 28
[Core/Unit]:
- Fixed auto-shot/wand issues
