### ISSUE TITLE
[Nodes][Herb] Empty herb nodes in Felwood

### ISSUE THREAD

**Issue by Ignifex** [Atlantiss/NetherwingBugtracker#5660]
**Description**: 
Many of the herb nodes in Felwood appear empty. When opening them no herbs are inside, so they also cannot despawn to allow for new herb nodes to appear.
I thought this behaviour might be linked to gathering Fel Creep, the material that can be gathered from herbs when carrying a Cenarion Beacon, but I cannot find any evidence supporting this.
I cannot recall seeing this anywhere outside of Felwood.

**Current behaviour**:
After a successful attempt at gathering a herb, some herb containers can appear empty to players.

**Expected behaviour**:
Herb containers should never be empty.

**Server Revision**: 
2939

**Comment by Godmatik** [comment]
Was fixed several years ago - closing
