### ISSUE TITLE
Botanica Normal Warp Splinter provide 1 reputation for a kill

### ISSUE THREAD

**Issue by sljivke** [Atlantiss/NetherwingBugtracker#5661]
I have just killed Warp on normal mode and he provided us 1 reputation only.
My current reputation is 8000/12000

**Comment by Drayo** [comment]
- Warp Splinter stops giving reputation when reaching honored. He should grant 120 rep all the way to exalted.

All other bosses and mobs in are working correctly.

**Comment by Tereneckla** [comment]
Fixed
