### ISSUE TITLE
Blacksmith weaponsmith craft 260

### ISSUE THREAD

**Issue by sdaasdsgsdg** [Atlantiss/NetherwingBugtracker#5662]
[//]: # (Enclose links to things related to the bug using http://wowhead.com or any other TBC database.)
[//]: # (You can use screenshot ingame to visual the issue.)
[//]: # (Write your tickets according to the format:)
[//]: # ([Quest][Azuremyst Isle] Red Snapper - Very Tasty!)
[//]: # ([NPC] Magistrix Erona)
[//]: # ([Spell][Mage] Fireball)
[//]: # ([Npc][Drop] Ghostclaw Lynx)
[//]: # ([Web] Armory doesnt work)
[//]: # (To find server revision type `.server info` command in the game chat.)

**Description**: 

**Current behaviour**:

**Expected behaviour**: 

**Server Revision**:

**Comment by Godmatik** [comment]
???

**Comment by sdaasdsgsdg** [comment]
Cant learn weaponsmith crafted items on skill 260. 
I am 47 lvl 260 BS with weaponsmith.
There is crafted 47 lvl weapon. Can be learn at 260 skill BS with weaponsmith.
https://www.wowhead.com/item=30072/light-skyforged-axe
https://www.wowhead.com/spell=36128/light-emberforged-hammer
https://tbc-twinhead.twinstar.cz/?item=30071
Only access on Shatt master BS maybe on HF masters.
I am 47 lvl 260 BS with weaponsmith, cant reach Outland.
From WH comment:
Confirmed: BS WeaponSmith Only(!) and BoP, learnable at 260.
I learned this from a trainer in IF(Ironforge!!!) the day 2.0.0 dropped.
Check from a blacksmithing trainer ;)
Found two diffirent version of trainer list:
https://www.wow-freakz.com/spells.php?spell=36126&name=light-skyforged-axe
https://woehead.way-of-elendil.fr/?spell=36126
