### ISSUE TITLE
[Quest] [Netherstorm] You, Robot

### ISSUE THREAD

**Issue by Yakubay** [Atlantiss/NetherwingBugtracker#5663]
**Description**: 
The quest can't be completed because of a bug

**Current behaviour**:
When you start the quest "Negatron" appairs first and then "Scrap Reaver X6000" spawns. When you take control of "Scrap Reaver X6000" and send it to fight against "Negatron" the first one generates no threat and Negatron won't focus it until the controller dies or is under effect of spells like "Divine Shield". Even if you die during the fight X6000 will keep fighting Negatron and if you respawn, Negatron will instantly try to kill you again. At the end X6000 will kill Negatron anyway but the quest will not be completed. 

**Expected behaviour**: 
"Scrap Reaver X6000" should be there before the arrival of Negatron and the last one should appear only when you take control of X6000. During the fight X6000 should generate threat.

**Server Revision**:

**Comment by Yakubay** [comment]
Here there are wowhead links:
https://www.wowhead.com/quest=10248/you-robot
https://www.wowhead.com/npc=19849/scrap-reaver-x6000
https://www.wowhead.com/npc=19851/negatron

**Comment by aeldepaky** [comment]
confirmed

**Comment by darknessangelo** [comment]
still bugged

**Comment by Macumbafeh** [comment]
This quest bug a bit.
Actually you Can done it just if YOUR robot kill the robot enemy. (At 5% you stop dps)
I did this quest with my 2 chars, and i helped many poeple like this.

**Comment by Wolffenstein** [comment]
Fixed in rev 3327.
