### ISSUE TITLE
[Hunter] Huter's Mark AP bonus glitched.

### ISSUE THREAD

**Issue by Aceloth** [Atlantiss/NetherwingBugtracker#5664]
**Description**: The Hunter's Mark it should give initially a certain amount of Attack Power bonus on our target + certain bonus each range attack cast on the foe until reaches a certain point.

**Current behaviour**:
In my case level, 2 is based on 45 initially and that's all. it doesn't show anywhere the bonus of it. not on the marked target, not even checking the attributes during a fight, doesn't change and I have dr damage that for each skill based on my target gives an average dmg it does, during hunters mark it doesn't change anything even after 10 shots on the mob.

**Expected behaviour**: 
After the innitial 45 once cast, It should give an extra 5 attack power bonus for each ranged attack on my target to a cap of 180 total.

![WoWScrnShot_042019_031953](https://user-images.githubusercontent.com/49800924/56450166-38386e80-631b-11e9-8f7c-40941e82f918.jpg)

**Server Revision**:

**Comment by Zarant** [comment]
I've tested it a while ago and I'm pretty sure it's working at level 70 it doesn't show anywhere in the game client but it works. 
The sample size required to accurately spot the extra AP contribution is inversely proportional to the damage range of your weapon. Just to make sure, you should test it with a low level weapon, then you can determine if the damage ramps up over time.

**Comment by Aceloth** [comment]
Sorry but I need it all the way during my levelling, especially during dungeons. And it doesn't have to do anything with my range weapon. Zoom in and read it, please.

**Comment by Zarant** [comment]
What are you on about? I just told you, the bonus attack power from successful attacks is being properly applied. The bonus AP is doesn't show on the game client and I'm pretty sure this is a client side limitation, the server handles it just fine.

**Comment by Easyfraggy** [comment]
Tooltips are client side - the tooltip on the debuff will never change. Just like when you have talents increasing battleshout for example the buff will still only show the base amount but still grants the bonus from the talent to everyone affected.

It is a limitation witht he TBC client. Nothing no server can do about that.
