### ISSUE TITLE
Ogres in Bloodmaul Outpost (Blade's Edge Mountain)

### ISSUE THREAD

**Issue by BetrayedPrince** [Atlantiss/NetherwingBugtracker#5665]
[//]: # (Enclose links to things related to the bug using http://wowhead.com or any other TBC database.)
[//]: # (You can use screenshot ingame to visual the issue.)
[//]: # (Write your tickets according to the format:)
[//]: # ([Quest][Azuremyst Isle] Red Snapper - Very Tasty!)
[//]: # ([NPC] Magistrix Erona)
[//]: # ([Spell][Mage] Fireball)
[//]: # ([Npc][Drop] Ghostclaw Lynx)
[//]: # ([Web] Armory doesnt work)
[//]: # (To find server revision type `.server info` command in the game chat.)

**Description**: 
Ogres in Bloodmaul Outpost have an enrage which sometimes heals them to full HP

**Current behaviour**:
heals them to full HP
**Expected behaviour**: 
Heals them by a percentage amount not equal to their maximum HP.
**Server Revision**:

**Comment by Evolvee** [comment]
its already reported
