### ISSUE TITLE
The tome of divinity id=1783 (need to resurrect narm faulk)

### ISSUE THREAD

**Issue by oggundren** [Atlantiss/NetherwingBugtracker#5666]
"While in the midst of completing the paladin quest line for the Tome of Divinity, I used the Symbol of Life on Henze Faulk instead of narm. I cannot abandon a new symbol of life to resurrect Narm. I fear that if I cannot complete this quest, my pally will not be able to resurrect. Apparently this could be an issue during TBC.

Current behaviour:
Narm faulk cannot be ressurected
Expected behaviour:
Narm stays alive so the player can read the quest text and accept the quest.

**Comment by danbopes** [comment]
rev 3249
