### ISSUE TITLE
[NPC][Stratholme] Postmaster Malown

### ISSUE THREAD

**Issue by noradora** [Atlantiss/NetherwingBugtracker#5667]
[//]: # (Enclose links to things related to the bug using http://wowhead.com or any other TBC database.)
[//]: # (You can use screenshot ingame to visual the issue.)
[//]: # (Write your tickets according to the format:)
[//]: # ([Quest][Azuremyst Isle] Red Snapper - Very Tasty!)
[//]: # ([NPC] Magistrix Erona)
[//]: # ([Spell][Mage] Fireball)
[//]: # ([Npc][Drop] Ghostclaw Lynx)
[//]: # ([Web] Armory doesnt work)
[//]: # (To find server revision type `.server info` command in the game chat.)

**Description**: 
After opening three mailboxes in Strat, this boss should appear. https://www.youtube.com/watch?v=AgJiV22YJqM
**Current behaviour**:
Nothing happens after opening any mailboxes. 
**Expected behaviour**: 
Each mailbox should spawn elites, and after the third, this boss should be summoned. https://www.wowhead.com/npc=11143/postmaster-malown 
**Server Revision**: 
2939? I'm not currently in-game. I'll edit this later if it's incorrect.

**Comment by Wolffenstein** [comment]
Fixed in rev 3783.
