### ISSUE TITLE
Core class mechanics: Shadowguard Not Working vs Ranged or Spells while Shielded

### ISSUE THREAD

**Issue by Bigfatrussian** [Atlantiss/NetherwingBugtracker#5668]
[//]: # (Enclose links to things related to the bug using http://wowhead.com or any other TBC database.)
[//]: # (You can use screenshot ingame to visual the issue.)
[//]: # (Write your tickets according to the format:)
[//]: # ([Quest][Azuremyst Isle] Red Snapper - Very Tasty!)
[//]: # ([NPC] Magistrix Erona)
[//]: # ([Spell][Mage] Fireball)
[//]: # ([Npc][Drop] Ghostclaw Lynx)
[//]: # ([Web] Armory doesnt work)
[//]: # (To find server revision type `.server info` command in the game chat.)

**Description**: 
Shadowguard (Troll Priest) Not Working vs Ranged or Spells while Shielded
**Current behaviour**:
Shadowguard Not Working vs Ranged or Spells while Shielded from pw shield
**Expected behaviour**: 
Shadowguard should proc vs spells and ranged as well: According to in game tooltip: The caster is surrounded by shadows, when a SPELL, melee OR RANGED ATTACK hits the caster, the attacker shall be struck for xx shadow damage.
**Server Revision**:

**Comment by Godmatik** [comment]
Must have been fixed at some point - just tested and it procs off ranged attacks and spells for me.

Closing.
