### ISSUE TITLE
Possibly item missing from loot table? 

### ISSUE THREAD

**Issue by cathabv** [Atlantiss/NetherwingBugtracker#5670]
**Description**: 

I've been looking for a blacksmith with Earthpeace Breastplate since February without luck. Both in world and discord. After all this time I'm starting to wonder if its missing from the loot table? I've also been contacted by several others saying they've also been looking for it and also not seen anyone wearing it. It should be added in patch 2.0.3 according to information I found on gamepedia. GM confirmed for me it should be in game, but he couldnt see the loot table of bosses. So I'm just looking for a confirmation if its on the loot table? Pattern should drop from second boss in Botanica.

**Comment by cathabv** [comment]
Pattern for Arcanoweave Bracers from Arca also seems to be missing

**Comment by Wolffenstein** [comment]
Fixed in rev 3408.
