### ISSUE TITLE
[Item][NPC] missing healing cloth pvp items

### ISSUE THREAD

**Issue by McRic** [Atlantiss/NetherwingBugtracker#5671]
Hi I dont know how it is on aliance side but for Horde there missing healing cloth wrist/cloak/boots/ring etc. for honor (there is only cloth with spell dmamge in 2 version one is stronger in stats but cost same i belive that one of those versions should be for heal), leather versions are avaliable with bonus healing but its litle bit useless for priests.
hope that its wont be so difficult to fix this thx :)

**Comment by Tenoutoften** [comment]
There isn't any healing versions for cloth early, doesn't exist... Cloth will have healing versions starting next season.
