### ISSUE TITLE
[NPC] [Boss] [Karazhan] [Curator] Incorrect Debuff on Curator/Beta Debuff only

### ISSUE THREAD

**Issue by ErothT** [Atlantiss/NetherwingBugtracker#5672]
**Description**: Curator in Karazhan has a debuff called Astral Armor when he shouldn't.

**Current behaviour**: Astral Armor is a debuff that applies 90% damage reduction on the boss severely cutting into tank threat on pull. An unlucky crit heal while tank is establishing aggro can cause healers to pull aggro and get killed. Curator is untauntable.

**Expected behaviour**:  Astral Armor was not part of release Karazhan as far as any sort of research can be found on it. Videos from within 2 weeks of TBC release show it is not active on Curator. 
https://www.youtube.com/watch?v=2whzzWmpnvU

As far as it existing, it appears to have existed on the beta on a different version of the fight that had 4 sparks spawning that needed to be killed. 
https://wowwiki.fandom.com/wiki/The_Curator?oldid=394424

**Server Revision**: 2944

**Comment by Easyfraggy** [comment]
Working as intended. It will probably be removed with us moving into patch 2.1.

**Comment by ErothT** [comment]
Can I ask why the debuff was added without regard to Hateful Bolt tanking (healers will out aggro) or Paladin tanking (threat comes from damage)?

**Comment by Easyfraggy** [comment]
Hateful bolts targetting is blizzlike meaning:

Highest threat (minus tank) with above  8000 hp (don't remember the exact number but around that). So it wont kill your players unless everyone is below that threshold.

That said bosses aren't ment to be easy in any way in this patch. For example Shade of Aran also only had his dragons breath ability for a couple weeks on retail. 

Paladin tanks are indeed not optimal on this version.

**Comment by ErothT** [comment]
Hateful bolts go after the highest aggro that isn't the tank, which means it's going to be healers. On retail you were able to assign someone to soak Hateful Bolts by dpsing the boss (locks dotting boss in between killing sparks for example). This is not the case, so they go after healers. It's just an odd change to just apply changes to bosses without changing numbers and instead applying spells that weren't part of fights and only part of Beta TBC.
