### ISSUE TITLE
"Control" Mage quest bug

### ISSUE THREAD

**Issue by AetherV** [Atlantiss/NetherwingBugtracker#5674]
There's a mage quest called Control in Azuremyst Isle, that requires you to kill some murlocs in order to spawn a blood elf that you have to kill. 

     Well, I killed him, and my quest appears as "complete", yet when I tried to turn it in, the NPC acted as if I hadn't completed the quest. I contacted a GM and explained them the issue, but they told me that I hadn't completed the quest. I *have*.

It's a pretty annoying bug, considering that you have to kill many murlocs to make the npc finally spawn.

![WoWScrnShot_042119_182914](https://user-images.githubusercontent.com/49841245/56472969-6924ba80-6465-11e9-85cf-cccdfc491b85.jpg)

**Comment by Godmatik** [comment]
Duplicate.

#5369

**Comment by AetherV** [comment]
> Duplicate.
> 
> #5369

It's a different issue though

**Comment by The14me** [comment]
Duplicate https://github.com/Atlantiss/NetherwingBugtracker/issues/5369
