### ISSUE TITLE
[Quest][Thousand Needles] Free at Last

### ISSUE THREAD

**Issue by Frnit** [Atlantiss/NetherwingBugtracker#5676]
[//]: # ( https://tbc-twinhead.twinstar.cz/?quest=4904 )
[//]: # (You can use screenshot ingame to visual the issue.)
[//]: # (Write your tickets according to the format:)
[//]: # ([Quest][Azuremyst Isle] Red Snapper - Very Tasty!)
[//]: # ([NPC] Magistrix Erona)
[//]: # ([Spell][Mage] Fireball)
[//]: # ([Npc][Drop] Ghostclaw Lynx)
[//]: # ([Web] Armory doesnt work)
[//]: # (To find server revision type `.server info` command in the game chat.)
https://tbc-twinhead.twinstar.cz/?quest=4904
**Description**: 
Free at Last quest escortable NPC dies at the end.
**Current behaviour**:
We escorted the mob all the way to end as a party of two. Only one of us gained complete status, then the NPC died without reason or combat. I got failed. I started this escort. Same happened earlier with RFK escort.
**Expected behaviour**: 
Should give completed to everyone and fade away, not die. 
**Server Revision**: 
2944

**Comment by Tenoutoften** [comment]
also happens to [Quest#10310](https://www.wowhead.com/quest=10310/sabotage-the-warp-gate) - [[NPC]Drijya#20281](https://www.wowhead.com/npc=20281/drijya) kills himself after completed quest, shouldn't - [Retail vid](https://youtu.be/6hayqrW5SSk?t=321)

reported here: https://github.com/Atlantiss/NetherwingBugtracker/issues/3678

**Comment by duzyizly** [comment]
Done this quest yersterday - no problem, NPC was just fine.
Probably this issue has been fixed long long time ago.
rev 3323
