### ISSUE TITLE
FIX it immediately while people are still playing on your server!

### ISSUE THREAD

**Issue by wqweEWRWREQWR3WQR** [Atlantiss/NetherwingBugtracker#5677]
1) enemy's HP 100%, **MUST be** like 158 / 158
2) I Am invite my brother in game and u don''t give to us x3 or x2 rates in Recruit a Friend (RaF works only for 90 days) **don't work!**
3) pls add in your filesystem Locale ruRU and we can use (SET locale ruRU in our realmlist.wtf for russificate client)
T.Y.

**Comment by danbopes** [comment]
This is NOT a proper way to create a bug report.
1. This is client side. Get an addon like Mob Info 2: https://legacy-wow.com/tbc-addons/mob-info-2/
2. There isn't any current refer a friend rewards. If it's a suggestion, then recommend it in the forums.
3. Download a Russian 2.4.3 client. Again...client side.

**Comment by wqweEWRWREQWR3WQR** [comment]
1. it's NOT client side. in others servery My licensed client work good without any addons.
2. ...... ok better play and donate on ANY other server
3. Again - licensed client from Blizzard's CD v.2.4.3 ruRU
ALL problems on your side.

**Comment by Godmatik** [comment]
He is correct.

Back in TBC, Blizzard did not show health numbers for minions, only percentages, by default. You will need to get an addon to show the numbers.

TBC did not have any Recruit-a-friend, if you do not like it, you should go elsewhere.

**Comment by Easyfraggy** [comment]
Just to clarify.

1. This is how it was early on in TBC - Intentional.
2. no RAF in TBC.
3. Only enGB and enUS clients are allowed here to avoid ??? links and other mishaps ingame.
