### ISSUE TITLE
[PvP][Zangarmarsh][High Priority] Twin Spire Blessing

### ISSUE THREAD

**Issue by oldmanmcgee** [Atlantiss/NetherwingBugtracker#5678]
**Description**
In the center of the zone Zangarmarsh, there is an East Beacon, a West Beacon, and a graveyard between the two beacons. Having control of a beacon, and killing an opposing faction member in the vicinity of the beacon gives players a Mark of Honor, a currency that may be spent at Thrallmar, or in Zabra'jin. In the center graveyard is a banner. Having control of the banner is what gives your faction, within Zangarmarsh, a buff that increases the damage your faction deals by  5% in the zone, and usage of a convienent graveyard from the center of the zone, which when used should start your ghost closer to your corpse if you die.

**Current behaviour**:
The Alliance has permanent control over the zone's PvP objective. Taking the East and West Beacon is a nearly fruitless endeavor, because the Horde Field Scout in Zabra'jin doesn't hand out a banner if you speak to him while on-foot. There is no dialogue option available to receive it, while both beacons are in Horde possession. I checked while dismounted, which is the way it should work. Even server resets are futile. The flag remains an dreary, unaligned grey after a server reset, until it's pickings for the Alliance and turns blue as they are the only faction that can shift the banner, due to this bug. The Horde Field Scout will only open a vendor window to exchange items for Marks of Thrallmar, instead of allowing an option to be given a banner.

**Expected behaviour**: 
The banner should be allowed to be run to the Twin Spire Graveyard by foot, carrying a banner similarly to the flag in Warsong Gulch. The player carrying the banner has a timer to run the banner to the Twin Spire Ruins, to shift the banner, much like how it's done in the Arathi Basin Battleground. I've read it is a 5-minute timer, but having never seen it, I can't be sure.

**Server Revision**: 
2944

**Comment by Wolffenstein** [comment]
Fixed in rev 3328.
