### ISSUE TITLE
Armor Kit Disapear in guild bank

### ISSUE THREAD

**Issue by Telsau** [Atlantiss/NetherwingBugtracker#5679]
[//]: # (Enclose links to things related to the bug using http://wowhead.com or any other TBC database.)
[//]: # (You can use screenshot ingame to visual the issue.)
[//]: # (Write your tickets according to the format:)
[//]: # ([Quest][Azuremyst Isle] Red Snapper - Very Tasty!)
[//]: # ([NPC] Magistrix Erona)
[//]: # ([Spell][Mage] Fireball)
[//]: # ([Npc][Drop] Ghostclaw Lynx)
[//]: # ([Web] Armory doesnt work)
[//]: # (To find server revision type `.server info` command in the game chat.)

**Description**: Hello, in our guild bank we had 10 Nature Armor Kit & 4 Flame Armor Kit and they disapear ??? noting in the bank logs it's not a steal because we have tons of more interesting thing to steal ! We wait a bit but still nothing...

https://fr.wowhead.com/item=29485/flame-armor-kit x4
https://fr.wowhead.com/item=29487/nature-armor-kit x10

**Current behaviour**: Waiting for them to comeback :)

**Expected behaviour**: If we can have the armor kit back it will be awesome !!!!!

**Server Revision**: 2942

**Comment by Tenoutoften** [comment]
Leadership on this server never refund items lost in that fashion, even if they can show that they were illegitimately deleted by their own core. 
Guild banks have been known to not be safe since the first week of launch

**Comment by Manaci** [comment]
Should be fixed by now
