### ISSUE TITLE
Darnassian Druid#16331 does not occasionally flee at low HP

### ISSUE THREAD

**Issue by Tenoutoften** [Atlantiss/NetherwingBugtracker#568]
**Description**: 
Darnassian Druid#16331(https://db.excalibur.ws/?npc=16331) does not flee at low HP.

Should occasionally flee at low HP according to this Cataclysm video: https://youtu.be/4ZXaQ49QW6g?t=147

Cleared the camp several times never fled.

**Server Revision**: 
2050

**Comment by Kiperr** [comment]
DELETE FROM creature_text WHERE entry = 16331;
INSERT INTO creature_text (entry, groupid, id, text, type, language, probability, emote, duration, sound) VALUES
(16331, 0, 0, "%s attempts to run away in fear!", 16, 0, 100, 0, 0, 0);

(@ENTRY, 0, 4, 0, 2, 0, 100, 1, 30, 5, 4000, 4000, 0, 0, 0, 0, 0, 0, 25, 1, 0, 0, 0, 0, 0, 0, 0, 1, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, "When health between 30% and 5% (check every 4000 - 4000 ms) - Self: Flee for assist with emote // ");

**Comment by Evolvee** [comment]
Kiper xd

we dont use texts for flee anymore :D its inside the action already

**Comment by Evolvee** [comment]
rev xdd
