### ISSUE TITLE
Celebras the cursed not working properly [High Priority]

### ISSUE THREAD

**Issue by Azuluminos** [Atlantiss/NetherwingBugtracker#5680]
Hi guys,

Yesterday I ran a Maraudon run and turned in the rod @ Celebras the cursed. He then walks to the stone and wave his hands (they even glow white-blue'ish) and.... that's that...

No further speaking, no picking up the rod, just a Celebras and an endlessly long ritual.

**Comment by Drayo** [comment]
"High Priority" - lol

You need to click the Tome in front of him, just like he tells you, try that.

**Comment by danbopes** [comment]
Dupe of #1622
