### ISSUE TITLE
[Warrior][Ability] Intimidating Shout Damage Threshold

### ISSUE THREAD

**Issue by Phil4242** [Atlantiss/NetherwingBugtracker#5681]
**Description**: The damage threshold is way too low. Like ridiculously low. The fear effect breaks from a single deep wounds tick almost every single time. At the current state its more like a sap or a blind where the cc effect immediately breaks on a single point of damage received.

**Current behaviour**: The damage threshold is way too low. The fear effect breaks from a single deep wounds tick almost every single time.

**Expected behaviour**: You should be able to deal some damage to the npc/player before the fear effect breaks similar to a warlock fear.

**Server Revision**: https://github.com/Atlantiss/NetherwingBugtracker/issues/5176 In the attempt to fix the damage threshold it has been lowered way too much

https://imgur.com/a/639vFPB - Screenshot of combatlogs where the issue occurred

**Comment by Easyfraggy** [comment]
Are you talking about the main target of the fear or the secondary targets?

If you are talking about the main target this issue is invalid - it is a gouge effect not a fear.

**Comment by Phil4242** [comment]
Main target.
Is it really blizzlike like this? I have no memories about it beeing a gouge effect on the main target.
The tooltip isn't indicating that aswell. https://imgur.com/a/9ggEq2M
But when you are sure about this I will believe you :)

**Comment by Easyfraggy** [comment]
Yes I know it is a bit weird but it's definitely supposed to break on first damage on main target. 

The main target is rooted in place and doesn't run around however breaks on first hit - just like a gouge effect. The secondary targets are regular fears. You will find lots of comments if you browse various forums etc where they mention targetting a hunters pet with the fear making the hunter himself secondary target so you can focus him down while he is feared.
