### ISSUE TITLE
[Spell][Hunter] Scatter shot

### ISSUE THREAD

**Issue by Frama1** [Atlantiss/NetherwingBugtracker#5684]
[//]: # (Enclose links to things related to the bug using http://wowhead.com or any other TBC database.)
[//]: # (You can use screenshot ingame to visual the issue.)
[//]: # (Write your tickets according to the format:)
[//]: # ([Quest][Azuremyst Isle] Red Snapper - Very Tasty!)
[//]: # ([NPC] Magistrix Erona)
[//]: # ([Spell][Mage] Fireball)
[//]: # ([Npc][Drop] Ghostclaw Lynx)
[//]: # ([Web] Armory doesnt work)
[//]: # (To find server revision type `.server info` command in the game chat.)

**Description**: 
If you use a Scatter shot on the target, and then immediately use Psychic Scream, the target will run in a random direction, as is usually the case with Psychic Scream, which is not correct. While the Scatter Shot is operating, the target must continue to follow the Scatter Shot trajectory.

**Current behaviour**:
Target moves along a Psychic Scream trajectory, not a Scatter Shot.
**Expected behaviour**: 
The target must first finish the way of Scatter Shot, then Psychic Scream.
**Server Revision**: 
2944

**Comment by Wolffenstein** [comment]
Could you post some retail proof?

**Comment by Frama1** [comment]
It is very difficult to do, as such situations could arise in games with a not popular setup - hunter priest.

Its works fine if you use Psychic Scream then Scatter Shot. Its works bad if you use Scatter Shot then Psychic Scream.
How Scatter Shot+Psychic Scream works here: https://youtu.be/cQR_dmM03FI
How Psychic Scream+Scatter Shot works here: https://youtu.be/q9fmb2jMfFg

Also i found this: 
https://wowwiki.fandom.com/wiki/Disorient
Scatter Shot, Blind and Dragon Breathe - Disorients effects. Disorient effects cause the target to wander about in a confused fashion for the duration of the effect. This makes disorient effects different from sleep and other incapacitate effects, in which the targets don't move. Different from Stun, Disorient effects break on damage. 

With Blind its sometimes works right https://youtu.be/KCtxyz94S7I (not best attemt)

**Comment by Donell70** [comment]
Can you please respond?

**Comment by Frama1** [comment]
As I said above, Blind and Psychic Scream are disorienting effects, for this purpose the target under these effects should not run far. He should be ''stagnating'' as the video below : 

https://youtu.be/a0h9-V4b9_g?t=57

**Comment by Wolffenstein** [comment]
Fixed in rev 2992.
