### ISSUE TITLE
Rogue bugs 

### ISSUE THREAD

**Issue by lopentus** [Atlantiss/NetherwingBugtracker#5686]
[//]: # (Enclose links to things related to the bug using http://wowhead.com or any other TBC database.)
[//]: # (You can use screenshot ingame to visual the issue.)
[//]: # (Write your tickets according to the format:)
[//]: # ([Quest][Azuremyst Isle] Red Snapper - Very Tasty!)
[//]: # ([NPC] Magistrix Erona)
[//]: # ([Spell][Mage] Fireball)
[//]: # ([Npc][Drop] Ghostclaw Lynx)
[//]: # ([Web] Armory doesnt work)
[//]: # (To find server revision type `.server info` command in the game chat.)

**Description**: Talent Cheat Death is not working as it should. 10% of maximum hp are not given. 
Why changing my weapons giving gcd? Rogues had no gcd after changing them.
**Current behaviour**:

**Expected behaviour**: 

**Server Revision**:

**Comment by Easyfraggy** [comment]
Changing weapons always gave GCD. No bug compilations - edit OP to reflect only 1 bug or I will close this.

**Comment by KevinTyrrell** [comment]
Cheat Death is working properly. You need resilience to get the benefit.

**Comment by lopentus** [comment]
Thanks guys!
