### ISSUE TITLE
[Nodes][Herb/Mining] Empty or Lack of Nodes

### ISSUE THREAD

**Issue by danbopes** [Atlantiss/NetherwingBugtracker#5687]
In an effort to track down and get more information from the devs, let's combine all the other threads about lack of nodes/empty nodes into one thread.

This issue attempts to combine #4990, #4261, #5660, #5562.
This may also be the cause of #5292, #4719, #4800, #1054

Please reply to this issue with the following:
 - Current Server Uptime (You can find that using .server info)
 - If the issue is related to bugged nodes:
   - Location/Count of nodes that were bugged (Silverpine Forest/10 Nodes bugged)
   - Type of node that was bugged (Silverleaf/Iron Ore)
 - If the issue is related to no nodes to be found:
   - Zone attempting to farm from (Silverpine Forest)
   - Hours/Minutes attempting to farm, and how many nodes you've come across during this time. Please use a stopwatch, and get an accurate number.

**Server Revision**: 
2944

**Comment by Wolffenstein** [comment]
I believe the issue might be related to quest items found in those objects. I assume if a player with a quest does not loot the quest item, then the object will still remain spawned and other players will see it as empty. Would be great if someone could test it.

**Comment by Borkla** [comment]
i ran across atleast 10 bugged copper veins yesterday at about 10 pm in the underlight mine area in Ghostlands (i found one copper vein there that was lootable(not empty) and that one properly despawned after mining it so i also believe its related to quest items

**Comment by TheGreyMouser** [comment]
I'm going to add to this.. lack of ore nodes.  First, I haven't even seen anybody on the server so I doubt they are being mined.  2nd areas that usually have ore nodes are totally empty or only 1 or 2 nodes *example, tunnels leading to dead mine, gold coast quarry.  I think the mine outside Orgrimar had 1 or 2 nodes vs the usual 10+. So I know mining is 10x skill and blacksmithing is 10x skill, but this lack of materials is seriously bottle necking advancement to outland and outland materials and recipes.  Compounded by only getting 1 ore per node and the node is bugged and cant be mined after the first whack.

**Comment by AndrewNB41191** [comment]
Lvling herbalism from 1-375 from scratch the last few days. All nodes worked for me properly, except upon entering felwood. I think wolfenstein may be right as far as quest items. I say this because of the soul shards or whatever they are called that can be harvested from herbing. The empty nodes must have invisible soul shards or whatever in there loot, aka wont properly despawn. I did skill up on one of the empty nodes which i found strange.

**Comment by Rrecklessz** [comment]
at around 22;30 the copper nodes stopt working for me in ghostlands.   i do however get a skillpoint for it but there is no loot. i tried atleast 5 mines at the west of the land

**Comment by Barryua** [comment]
Today (20-08-2019) about 15:00-16:00 realm time, I have found 5 empty herb nodes in Felwood. Problem is described with details in https://github.com/Atlantiss/NetherwingBugtracker/issues/5660. It happened with https://classic.wowhead.com/item=11511/cenarion-beacon in bag and also without it. I don't remember exact names of herbs but there were empty nods of herbs like Gromsblood, Golden Sansam etc. I wrote down map coordinates of those empty nodes:
36.1 - 61.6
38.7 - 58.0
56.1 - 8.4
60.5 - 25.5
62.0 - 25.7
Uptime was about 3 days 11-12 hours when I found those empty nodes. It never happend to me before in any zone other than Felwood.

**Comment by Manaci** [comment]
This is mostly concerning Stranglekelp in all the zones the spawn in.
Let me just start of with this: I have NEVER heard of herbs actually DESPAWNING on a server disconnect. About 20 minutes ago the Server disconnected while I was 5 steps away from 2 stranglekelp spawns and then when I got back in they were gone. There is something fundamentally wrong with herbs in vanilla for this to be a thing. Do they have an initial respawn timer here? Then while running the route after the disconnect I find other respawned herbs. So did some despawn or are there different clusters and it switched cluster on the disconnect? 
But then yesterday I went the various routes for the first time and almost every single herb was there, but then even after 24 hours (and a server restart on the 22th hour and a dc on the 24th hour) only 5 out of the 35+ herbs had respawned in the various routes along the waters of The Barrens, Silverpine, Stranglethorn, Hillsbrad etc. I am so confused as to what is going on with herbs in vanilla zones.

Another weird thing was that I also had 5 herbs just appear out of nowhere in around me in SIlverpine while I was doing the initial herbing on land, like I went into another layer or something. Then while backtracking the route I did that minutes ago had 0 herbs was now flourishing with them. Like there had been some trigger to respawn every single one of the herbs in the zone. This might also be the reason I initially had so many stranglekelp on my routes and then afterwards there were only a few when many hours had passed. It's like there's a continent-wide limit of the herbs and only after a lot have been gathered, they all respawn or something. 
Not sure what the approach to fix this is even gonna be, and no, there are no quest items sharing spawns with these stranglekelp.

**Comment by Manaci** [comment]
Can you just give all the vanilla herbs a static 30-1 hour respawns (and probably make the respawn of Black Lotus a bit random). Like anything other than having to wait 24+ hours and not even having all the nodes respawn when they were all respawned 24 hours ago, there's no way this is Blizzlike and no servers have had it this bad. Thiscluster system is obviously not working.

**Comment by Tereneckla** [comment]
rev 3205
