### ISSUE TITLE
[Quest] [Netherstorm] Full Triangle

### ISSUE THREAD

**Issue by snackpak09** [Atlantiss/NetherwingBugtracker#5688]
https://www.wowhead.com/quest=10276/full-triangle#comments

https://imgur.com/a/S8BgqG6

In the quest "Full Triangle" you are meant to kill a demon and get his drop (which I did) and turn it into the NPC named "Image of Nexus-Prince Haramad". But you are unable to turn it into him. I checked other forums and it says that when it glitches out it takes 8 minutes for him to respawn but it has been much longer and nothing yet.

Unable to talk to quest NPC to turn in.

Be able to talk to quest NPC to turn in.

2944

**Comment by snackpak09** [comment]
Came back a few hours later and was able to finish.

**Comment by Easyfraggy** [comment]
Worked fine for me.

**Comment by Tenoutoften** [comment]
There is another quest which upon completion starts RP involving Nexus-Prince Haramad to disappear for some time.

**Comment by danbopes** [comment]
rev 3432
