### ISSUE TITLE
[NPC][Quest][Burning Steppes] Ogre Head On A Stick = Party

### ISSUE THREAD

**Issue by FilipMuratagic** [Atlantiss/NetherwingBugtracker#5689]
[//]: # (Enclose links to things related to the bug using http://wowhead.com or any other TBC database.)
[//]: # (You can use screenshot ingame to visual the issue.)
[//]: # (Write your tickets according to the format:)
[//]: # ([Quest][Azuremyst Isle] Red Snapper - Very Tasty!)
[//]: # ([NPC] Magistrix Erona)
[//]: # ([Spell][Mage] Fireball)
[//]: # ([Npc][Drop] Ghostclaw Lynx)
[//]: # ([Web] Armory doesnt work)
[//]: # (To find server revision type `.server info` command in the game chat.)

**Description**: 
Multiple unattackable non-aggroable mobs spawn on several locations on top of each other, on the hill where the quest is supposed to be completed.

https://www.wowhead.com/quest=3825/ogre-head-on-a-stick-party
https://imgur.com/a/EhdPAT0

This issue has already been addressed at #4832 (rev 2878), but has apparently re-emerged in the current revision.
**Current behaviour**:
Mobs spawn on top of each other, immobile and non interactable.

**Expected behaviour**: 
Upon piking the head of the ogre, non interactable mobs spawn running in fear around the piked head, and de-spawn after X seconds.

**Server Revision**:  
2944

**Comment by Brian-Shaw** [comment]
I had the same issue. It's not related to the quest though

**Comment by Tenoutoften** [comment]
https://github.com/Atlantiss/NetherwingBugtracker/issues/4832 was allegedly fixed, something might have broken it recently

**Comment by Evolvee** [comment]
its just an RP event that makes the ogres spawn and yell arooud when you stick the head into sand

there has to be some core fuckup since the script makes them run/despawn on their spawn

**Comment by Godmatik** [comment]
Fixed at some point I presume.

The ogres properly spawn, run around in fear, and /yell a bunch after planting the pike
