### ISSUE TITLE
[Spell][Talent] Improved Moonfire

### ISSUE THREAD

**Issue by Xynaps** [Atlantiss/NetherwingBugtracker#569]
**Description**: The talent Improved Moonfire in the Balance talent tree does not seem to work as intended. Testing with rank 3 moonfire gives incorrect values. Have not tried with different ranks so it might only be rank 3 that is affected. 

**Current behaviour**: Using rank 3 of Moonfire the spell has a the lowest value observed has been 25 damage. This should not be possible since the 10 % boost should increase the lower bound to 28. 
The dot damage also seems to be affected with allowing ticks of 12(for a total of 48) but the lowerbound should be 14 damage per tick (for a total of 54 dmg) according to tooltip.
The uppwerbound of the tooltip, 15 dmg per tick (total 60 dmg) has not been observed. 

**Expected behaviour**: Improve the damage output of the spell Moonfire by 10 % with 2/2 points spent. 

**Server Revision**: 2050

**Comment by xmesaj2** [comment]
https://github.com/Atlantiss/NetherwingBugtracker/issues/412 possibly related
