### ISSUE TITLE
[Core][Proc Mechanics] On Successful spellcast

### ISSUE THREAD

**Issue by GeorgDevv** [Atlantiss/NetherwingBugtracker#5690]
[//]: # (Enclose links to things related to the bug using http://wowhead.com or any other TBC database.)
[//]: # (You can use screenshot ingame to visual the issue.)
[//]: # (Write your tickets according to the format:)
[//]: # ([Quest][Azuremyst Isle] Red Snapper - Very Tasty!)
[//]: # ([NPC] Magistrix Erona)
[//]: # ([Spell][Mage] Fireball)
[//]: # ([Npc][Drop] Ghostclaw Lynx)
[//]: # ([Web] Armory doesnt work)
[//]: # (To find server revision type `.server info` command in the game chat.)

**Description**: 
Items/Procs with "On Successful spellcast" should proc from any spells. E.g. the darkmoon card blue dragon should proc from any spellcast, be it a hot/aura application or a direct spell.
https://www.wowhead.com/item=19288/darkmoon-card-blue-dragon#comments

**Current behaviour**:
The procflags:
- 14 Successful cast positive spell
- 16 Successful damage from harmful spell cast

Currently those are not properly implemented, procs which have both flags cannot proc from any spellcast, e.g. https://www.wowhead.com/item=24122/coronet-of-verdant-flame does not proc from non direct spells.

**Expected behaviour**: 
Proc on any spellcast.
Corecraft had it working with this implementation, might be useful to you:
https://github.com/ccshiro/corecraft/blob/f76c1d3dcb951ec9e39b480d860f002d9b0c4491/server/src/game/Unit.cpp#L11706

**Server Revision**: 
2944

**Comment by Wolffenstein** [comment]
Are you sure it doesn't? I believe multiple people have that card and nobody reported it not working. I believe the proc flags are handled correctly as well.

**Comment by GeorgDevvv** [comment]
dont have the card to test, but the https://www.wowhead.com/item=24122/coronet-of-verdant-flame has the same procflag and doesnt work on anything but direct spells. Blue dragon probably got a manual fix for just the card as it is more popular

**Comment by BezawitNW** [comment]
Could this be why the Druid T5 trinket (Living Root of the Wildheart) is not procing at all for healing?

**Comment by Wolffenstein** [comment]
Fixed in rev 2949.

**Comment by someaddons** [comment]
broken again on newest
