### ISSUE TITLE
Healer tailoring leg enchant gives bonus spell damage

### ISSUE THREAD

**Issue by OffeSwedin** [Atlantiss/NetherwingBugtracker#5691]
[//]: # (Enclose links to things related to the bug using http://wowhead.com or any other TBC database.)
[//]: # (You can use screenshot ingame to visual the issue.)
[//]: # (Write your tickets according to the format:)
[//]: # ([Quest][Azuremyst Isle] Red Snapper - Very Tasty!)
[//]: # ([NPC] Magistrix Erona)
[//]: # ([Spell][Mage] Fireball)
[//]: # ([Npc][Drop] Ghostclaw Lynx)
[//]: # ([Web] Armory doesnt work)
[//]: # (To find server revision type `.server info` command in the game chat.)

**Description**: 

Silver spellthread tailoring leg enchant gives bonus spell damage

**Current behaviour**:

The leg enchant gives:
+46 healing
+16 spell damage
+15 stamina

**Expected behaviour**: 

No bonus spell damage until later patch

**Server Revision**: 
[2947]

**Comment by Tenoutoften** [comment]
This can't be changed unless you use an older client according to Kutsal
https://github.com/Atlantiss/NetherwingBugtracker/issues/2932
https://github.com/Atlantiss/NetherwingBugtracker/issues/4731

**Comment by Tereneckla** [comment]
2.3 now anyways
