### ISSUE TITLE
defias brotherhood

### ISSUE THREAD

**Issue by maki1004** [Atlantiss/NetherwingBugtracker#5693]
**Description**: so last night i did deadmines with couple on people and we cleared the whole 
dungeon and on the last boss we killed him but ads killed us in the process , only healer stayed alive bcz he was soulstoned and by the time he ressurected us edwins corpse despawned witch took like 2 minutes. now we can't finnish the defias brotherhood quest witch was the main reason why we ran the dungeon. down below are screenshots.

![WoWScrnShot_042519_234129](https://user-images.githubusercontent.com/50015828/56800291-f592fc80-681a-11e9-9ce7-15141e87d0d5.jpg)
![WoWScrnShot_042519_234137](https://user-images.githubusercontent.com/50015828/56800402-33902080-681b-11e9-84ed-dfdc5e1ac10b.jpg)

**Comment by Drayo** [comment]
I just killed him and his corpse despawn is set for 60 minutes.

![image](https://user-images.githubusercontent.com/23145811/87220573-3f56fc80-c365-11ea-8fc8-e3e8d8b5bfe9.png)


Should not be an issue anymore.
