### ISSUE TITLE
Arclight Spanner is not recognized by raptor-strike

### ISSUE THREAD

**Issue by treutz** [Atlantiss/NetherwingBugtracker#5694]
**Description**:  **Current behaviour**:

Dear Developer-Team, 

on my Level 6-Hunter, I attached the Arclight-Spanner (Engeneer-Item) to my weaponhand, but I can't use the raptor-strike (rank 1), because I get the message: "melee-weapon needs to be attached".

**Expected behaviour**: 

The raptor-strike should be enabled with the arclight-spanner.

**Server Revision**: ?? current date: 2019-04-26.

**Comment by Easyfraggy** [comment]
Not sure this is valid - blacksmith hammer skinning dagger etc are not real weapons either and would not work with "melee weapon required" on retail.

**Comment by Dimbleglim** [comment]
They should work as any other weapon even though they are fairly worthless as weapons they still can be used as such.

**Comment by KenguruSafari** [comment]
Classless weapons never worked as Axes/Maces/Swords/Daggers etc.
A Mining Pick, Blacksmith Hammer and Skinning Knife works the same way, and are not considered Axe/Mace/Dagger.
http://tbc.cavernoftime.com/items=2.14
Checked in-game as well.
