### ISSUE TITLE
[Core][AI] Mob behavior with immunity abilities (Divine Shield)

### ISSUE THREAD

**Issue by psiven** [Atlantiss/NetherwingBugtracker#5695]
[//]: # (Enclose links to things related to the bug using http://wowhead.com or any other TBC database.)
[//]: # (You can use screenshot ingame to visual the issue.)
[//]: # (Write your tickets according to the format:)
[//]: # ([Quest][Azuremyst Isle] Red Snapper - Very Tasty!)
[//]: # ([NPC] Magistrix Erona)
[//]: # ([Spell][Mage] Fireball)
[//]: # ([Npc][Drop] Ghostclaw Lynx)
[//]: # ([Web] Armory doesnt work)
[//]: # (To find server revision type `.server info` command in the game chat.)

**Description**: Monster behavior is incorrect when the only player in combat with them is under Divine Shield. Presumably this also affects Ice Block etc.

**Current behaviour**: Enemies will continue to use abilities, shoot ranged weapons, cast and begin casting spells on players who are immune.

**Expected behaviour**: Enemies should consider the player an invalid target and stop casting targeted spells or using ranged attacks and attempt to melee the immune player until the effect wears off.

**Server Revision**: 2944

**Comment by Wolffenstein** [comment]
Proof?

**Comment by psiven** [comment]
I'll see if I can find some better examples, but it's still how it works on live. Here's an old video of mine from TBC:

https://youtu.be/gq--MQm0Jrk

First ten seconds you can see a bubble pull. The holy priest who would be spamming smite stops casting to run up, the arcane mage stops casting to... Fail to pathfind apparently.

**Comment by Wolffenstein** [comment]
Thanks, I'll see what I can do about it

**Comment by Drayo** [comment]
All immunities should be treated like Fear is working currently, all mobs should completely ignore the player IF there is a second player on the aggro list. If the player is alone they will just continue to hit him.

Odd thought because I though it was working. If you BoP players mobs fuck off and in SSC for example the Bog Lords instantly stop their spray ability.

**Comment by Wolffenstein** [comment]
It does work, but they just continue to cast spells even if all of their targets are immune

**Comment by Godmatik** [comment]
Rev 4018 - this appears fixed.

Tested and the mobs properly stop casting ranged/spells and come up to melee you if you have an invulnerability up and are the only one on aggro list, Wolf probably just forgot to close it out.
