### ISSUE TITLE
[Npc] Direhorn Grimtotem 

### ISSUE THREAD

**Issue by galediex** [Atlantiss/NetherwingBugtracker#5696]
**Description**: Direhorn Grimetotem npc's stealth detection is too high.

**Current behaviour**: Direhorn Grimetotem npc's detect stealth 15+ meters away with me being a level 38 rogue and the npc also being level 38.

**Expected behaviour**: Direhorn Grimetotem npc's stealth detection should no begin until roughly 8 meters if your the same level as the mob.

**Comment by Wolffenstein** [comment]
Could you maybe record it?

Also if you have a source for those 8 meters I would be very interested.

**Comment by duzyizly** [comment]
looks like fixed.
I was able to frost-sap as lvl 40, no master of deception.

![WoWScrnShot_062420_123416](https://user-images.githubusercontent.com/43931626/85540295-1c171800-b617-11ea-90db-cd390f21ca4d.jpg)
![WoWScrnShot_062420_123438](https://user-images.githubusercontent.com/43931626/85540313-1e797200-b617-11ea-8294-48a0c3cbad75.jpg)
