### ISSUE TITLE
[NPC] Voidwalker lost its' name

### ISSUE THREAD

**Issue by monoeko** [Atlantiss/NetherwingBugtracker#5698]
[//]: # (Enclose links to things related to the bug using http://wowhead.com or any other TBC database.)
[//]: # (You can use screenshot ingame to visual the issue.)
[//]: # (Write your tickets according to the format:)
[//]: # ([Quest][Azuremyst Isle] Red Snapper - Very Tasty!)
[//]: # ([NPC] Magistrix Erona)
[//]: # ([Spell][Mage] Fireball)
[//]: # ([Npc][Drop] Ghostclaw Lynx)
[//]: # ([Web] Armory doesnt work)
[//]: # (To find server revision type `.server info` command in the game chat.)

**Description**:  When I summoned the Voidwalker for the first time immediately after completing the necessary quest, he spawned with a regular random demon name (something like Kraz'kaz or something). I summoned the Imp soon after, and then when I next summoned the Voidwalker again he came in named just "Voidwalker". This name change has persisted through many dismisses and resummons, as well as restarting the game and clearing the cache.

**Current behaviour**:

**Expected behaviour**: 

**Server Revision**: 2947

**Comment by Manaci** [comment]
Dead issue
