### ISSUE TITLE
[Core][Critical][Mac Client] MacOS client crashes

### ISSUE THREAD

**Issue by veekk** [Atlantiss/NetherwingBugtracker#5699]
**Description**:  It's not single crashes but with some clean test cases, also it was tested on few different servers, includes "fun" servers and local mangos, and no any crashes there. In almost 100%(like 99%) macOS client crashing behind any elevators, not on them, but behind. It's can applied for shat (any of them), UC, TB, village on mountain at thousand needles, also MECHA and SSC. seems like it caused by some custom elevators implementation and hopefully can be fixed.

Also on [reddit](https://www.reddit.com/r/wowservers/comments/acawi7/native_mac_243_world_of_warcraftapp_runs_on_all/eddh1ip/) was mentioned lot of info regarding this transport serverside bug, that Windows client ignoring it, but not Mac one

**Current behaviour**: Crashes

**Expected behaviour**: No crashes

**Server Revision**: 2947

**Comment by drraga** [comment]
UP! 
have the same issues.

**Comment by veekk** [comment]
UP! Any answers at least from devs?

**Comment by JacksawHBO** [comment]
Same problem happened to me few days ago (Monday 22 July): I play on Mac and the client crashed the moment I stepped on the Telredor elevator platform (Zangarmarsh).

**Comment by veekk** [comment]
just trying to UP! with IoQD opening this issue became pretty annoying 'cause u can stack under portal for like 20 crashes in a row until u log in with good luck and click on portal

**Comment by Godmatik** [comment]
Mac client is no longer supported, closing
