### ISSUE TITLE
NPC at Farstrider Retreat is non-interactive.

### ISSUE THREAD

**Issue by Narec** [Atlantiss/NetherwingBugtracker#57]
(Apologies, I've never bug reported before, might be crummy at it.)

The NPC 'Zalene Firstlight' at Farstrider Retreat, in Eversong Woods is a Food & Drink vendor. She has an item for the quest: 'The Party Never Ends' where she will sell the player 'Springpaw Appetizers'

I am unable to interact with her and purchase the quest item. Can only target her, nothing else.

**Comment by Wolffenstein** [comment]
Fixed in rev 2020.
