### ISSUE TITLE
DB/Loot: Crag boar ribs belong to crag boars

### ISSUE THREAD

**Issue by Teppic1** [Atlantiss/NetherwingBugtracker#570]
**Description**: 

Crag boar ribs (item=2886) are supposed to drop from crag boars (1125, 1689).

**Current behaviour**:

They're dropping from stonetusk ones (113) in Elwynn Forest and possibly other places.

**Server Revision**: 

2050

**Comment by aresbrutus** [comment]
Duplicate.

#55
