### ISSUE TITLE
Sextant of Unstable Currents

### ISSUE THREAD

**Issue by artishoka1** [Atlantiss/NetherwingBugtracker#5700]
**Description**:

[ITEM][Sextant of Unstable Currents][Item ID: 30626]

Internal Cooldown of the trinket is incorrect, it should 45 seconds, but in the server the internal cooldown is 75 seconds. This have been tested and proven with 30 minutes of spell spamming at [NPC][Dr.Boom]

https://wow.gamepedia.com/Talk:Sextant_of_Unstable_Currents

https://dwarfpriest.wordpress.com/2007/10/08/procs-when-you-least-need-it/

https://wowwiki.fandom.com/wiki/Sextant_of_Unstable_Currents

https://imgur.com/18QY2Aj

**Current behaviour**:

Internal CD is 75 seconds

**Expected behaviour**: 

Internal CD should be 45 seconds

**Server Revision**: 

2947

**Comment by Saronitian** [comment]
https://de.wowhead.com/item=30626/sextant-der-unsteten-str%C3%B6mung#comments:id=57934

wowhead comment from 2.0.10 that states it should have 45seconds cooldown from when it proccs / 30 from after the buffs fades7
