### ISSUE TITLE
Quagmirran's Eye wrong internal cooldown

### ISSUE THREAD

**Issue by artishoka1** [Atlantiss/NetherwingBugtracker#5701]
**Description**: 

[Item][Quagmirran's Eye][Item ID: 29370] The procrate on this trinket seems to be 68 seconds, but as many sources state the internal cooldown should be 45 seconds, the same as Sextant of Unstable Currents

https://wowwiki.fandom.com/wiki/Talk:Quagmirran%27s_Eye
https://wowwiki.fandom.com/wiki/Quagmirran%27s_Eye
https://www.wowhead.com/item=27683/quagmirrans-eye&bonus=4105#comments

**Current behaviour**:

Internal Cooldown is 68 seconds

**Expected behaviour**: 

Internal Cooldown should be 45 seconds

**Server Revision**: 

2947

**Comment by Wolffenstein** [comment]
It does have 45 icd in the database. How did you measure it?

**Comment by artishoka1** [comment]
Procidile on Dr.Boom, same as the other thread I opened.
