### ISSUE TITLE
[Item][Engineering] Ornate Spyglass zooms but doesn't reveal distant objects

### ISSUE THREAD

**Issue by leeviathan** [Atlantiss/NetherwingBugtracker#5704]
**Description**: The engineering item Ornate Spyglass is not working correctly

**Current behaviour**: When you use Ornate Spyglass it will zoom-in, but you're still not able to see npc's or players from that distance. Also doesn't cancel when you try to move.

**Expected behaviour**: Ornate Spyglass is supposed to make the player able to see npc's, resource nodes, and players from a long distance when used. https://www.youtube.com/watch?v=0bfMJCOf-yI
Also should cancel when you move, as stated in the item's description.

**Server Revision**: 2947

**Comment by Manaci** [comment]
Fixed
