### ISSUE TITLE
AV guard bug

### ISSUE THREAD

**Issue by oldr1** [Atlantiss/NetherwingBugtracker#5705]
[//]: # (Enclose links to things related to the bug using http://wowhead.com or any other TBC database.)
[//]: # (You can use screenshot ingame to visual the issue.)
[//]: # (Write your tickets according to the format:)
[//]: # ([Quest][Azuremyst Isle] Red Snapper - Very Tasty!)
[//]: # ([NPC] Magistrix Erona)
[//]: # ([Spell][Mage] Fireball)
[//]: # ([Npc][Drop] Ghostclaw Lynx)
[//]: # ([Web] Armory doesnt work)
[//]: # (To find server revision type `.server info` command in the game chat.)

**Description**: 
It is possible to pull Dreks And Vandars guards out of the keep and kill em 1 by 1, this way you dont have to cap towers/bunkers in order to stand a chance against the boss.
Alliance wins every AV because of this

**Current behaviour**:

**Expected behaviour**: 

**Server Revision**:

**Comment by Godmatik** [comment]
Closing - will consolidate all outstanding AV issues into one thread now.
