### ISSUE TITLE
[NPC] Emberstrife - unable to use flames of black flight

### ISSUE THREAD

**Issue by shockave** [Atlantiss/NetherwingBugtracker#5707]
**Description**: 
unable to use/nothing happens when used his skill: flames of black flight by that u cant complete LBRS key quest Seal of Ascension
**Current behaviour**:
nothing happens
**Expected behaviour**: 
should make unforged seal of ascension into lootable seal of ascension

**Comment by Godmatik** [comment]
Worked fine for me, can close
