### ISSUE TITLE
[NPC] Mashrock

### ISSUE THREAD

**Issue by earywen** [Atlantiss/NetherwingBugtracker#5709]
[//]: # (Enclose links to things related to the bug using http://wowhead.com or any other TBC database.)
[//]: # (You can use screenshot ingame to visual the issue.)
[//]: # (Write your tickets according to the format:)
[//]: # ([Quest][Azuremyst Isle] Red Snapper - Very Tasty!)
[//]: # ([NPC] Magistrix Erona)
[//]: # ([Spell][Mage] Fireball)
[//]: # ([Npc][Drop] Ghostclaw Lynx)
[//]: # ([Web] Armory doesnt work)
[//]: # (To find server revision type `.server info` command in the game chat.)

**Description**: 

The Mashrock mobs in Zangarmash are bugged, their corpse "died" (the 3d model) but they are still alive. You can kill them but it's weird to hit "nothing"

**Current behaviour**:

**Expected behaviour**: 

**Server Revision**:

**Comment by Tereneckla** [comment]
Either a stroke or Ragestone Threshalisk
