### ISSUE TITLE
[Quest] Elixir of Agony

### ISSUE THREAD

**Issue by Anna-Molly** [Atlantiss/NetherwingBugtracker#571]
[//]: # (Enclose links to things related to the bug using http://wowhead.com or any other TBC database.)
[//]: # (You can use screenshot ingame to visual the issue.)
[//]: # (Write your tickets according to the format:)
[//]: # ([Quest][Azuremyst Isle] Red Snapper - Very Tasty!)
[//]: # ([NPC] Magistrix Erona)
[//]: # ([Spell][Mage] Fireball)
[//]: # ([Npc][Drop] Ghostclaw Lynx)
[//]: # ([Web] Armory doesnt work)

**Description**: 
Can't loot the Mudsnout Blossoms.

**Current behaviour**:
Invalid Target trying to loot.

**Expected behaviour**: 

**Server Revision**:

**Comment by aresbrutus** [comment]
I just tested it out and it worked for me. Try to restart client and/or disable addons and try again. PM Kutsal on discord if this still does not work for you.
