### ISSUE TITLE
vashj elementals drop trash loot

### ISSUE THREAD

**Issue by teddys** [Atlantiss/NetherwingBugtracker#5710]
**Description**:  An elemental in phase 2 of vashj fight just dropped the epic totem that's supposed to drop from trash

**Server Revision**:  2947

**Comment by teddys** [comment]
https://imgur.com/olZ9qkR

**Comment by teddys** [comment]
good trash farm I guess

**Comment by Wolffenstein** [comment]
Fixed in rev 2949.
