### ISSUE TITLE
[Core][Focus] Focus Kick sets current focus as target.

### ISSUE THREAD

**Issue by SlizeTBC** [Atlantiss/NetherwingBugtracker#5711]
Hello,
I am not sure if this is a bug or not. If you check the Video below you can see me using Gouge, Blind, Shadowstep and Kick on my Focus. 

https://www.twitch.tv/videos/417926268

All my Macros are very simple and look like that:

**#showtooltip 
/cast [target=focus] Kick**

You can see that neither Blind, Shadowstep or Gouge set my Focus to Target. I can use those abilities without havin a target. But as soon as I use kick on my focus, I instantly get my Focus as my Target and I can't figure out why.
Maybe it's a bug, maybe not. I never had any problems with my UI and used Macros on any Server.

Thanks for the help.

**Comment by Easyfraggy** [comment]
Probably because Kick sends /startattack command and the others don't.

Not sure if its proper behavior or not.

**Comment by bajkorv** [comment]
Same for other rogues?

**Comment by teddys** [comment]
use

**Comment by Macumbafeh** [comment]
Same problem with interv / charge on focus for War / drood...

**Comment by Tereneckla** [comment]
https://youtu.be/Vht-x3KDIK0?t=189
https://www.mmo-champion.com/threads/783087-Focus-charge-intercept-bug
Was an issue during wotlk until cataclysm at least

Likely was happening in tbc aswell

**Comment by Tereneckla** [comment]
Same blizzlike bug as described here 
https://github.com/Atlantiss/NetherwingBugtracker/issues/6399#issuecomment-656999541
