### ISSUE TITLE
[item] Orb of Deception

### ISSUE THREAD

**Issue by wandareu** [Atlantiss/NetherwingBugtracker#5712]
[//]: # (Enclose links to things related to the bug using http://wowhead.com or any other TBC database.)
[//]: # (You can use screenshot ingame to visual the issue.)
[//]: # (Write your tickets according to the format:)
[//]: # ([Quest][Azuremyst Isle] Red Snapper - Very Tasty!)
[//]: # ([NPC] Magistrix Erona)
[//]: # ([Spell][Mage] Fireball)
[//]: # ([Npc][Drop] Ghostclaw Lynx)
[//]: # ([Web] Armory doesnt work)
[//]: # (To find server revision type `.server info` command in the game chat.)

**Description**: 
Orb of Deception cancels effect upon unequip, even though it is not meant to in 2.4.3; this should only be how the item behaves from 3.0 onwards
**Current behaviour**:
Orb of Deception cancels effect upon unequip
**Expected behaviour**: 
Effect Remains
**Server Revision**: 
2948

**Comment by Tereneckla** [comment]
Cannot find proof for this.
