### ISSUE TITLE
[Profession][Tailoring] Mooncloth cannot be crafted in certain Moonwells

### ISSUE THREAD

**Issue by Moryjani** [Atlantiss/NetherwingBugtracker#5713]
**Description**: 
Some moonwells cannot be used to craft Mooncloth from Felcloth, such as the one in the Pools of Arlithrien in Teldrassil.
![image](https://user-images.githubusercontent.com/10288894/56897115-e962a580-6a8d-11e9-8c4a-51f983860b1c.png)

**Current behaviour**:
Trying to craft Mooncloth in the moonwell results in the message: "Requires Moonwell"

**Expected behaviour**: 
Should be able to craft Mooncloth.

**Server Revision**: 
Revision: 3982

**Comment by Wolffenstein** [comment]
Fixed in rev 2949.
