### ISSUE TITLE
[Item][Engineering] Explosive Sheep

### ISSUE THREAD

**Issue by leeviathan** [Atlantiss/NetherwingBugtracker#5714]
**Description**: 
Use: Summons an Explosive Sheep which will charge at a nearby enemy and explode for 135 to 166 damage. Lasts for 3 min or until it explodes.

**Current behaviour**:
Summoning the sheep makes it appear for a moment, then it despawns instantly without exploding. The item is then on permanent cooldown until relog.

**Expected behaviour**: 
https://www.youtube.com/watch?v=ShSrwCbYMbE

**Server Revision**: 
2947

**Comment by leeviathan** [comment]
oops, this is a duplicate of #5463 #4767

**Comment by Godmatik** [comment]
fixed - can close
