### ISSUE TITLE
[Item] Talon of the Phoenix 

### ISSUE THREAD

**Issue by HinataEvenus** [Atlantiss/NetherwingBugtracker#5715]
https://www.wowhead.com/item=32944/talon-of-the-phoenix

**Description**: According to wowhead, this item was not released until 2.1 (unlike Claw of the Phoenix which is 2.0). However ive already seen certain players owning said weapon so i looked into it.

**Current behaviour**: The weapon seems to drop since some players seem to own it.

**Expected behaviour**: Weapon shouldn't be added until 2.1

**Server Revision**: 2947

**Comment by Wolffenstein** [comment]
WoWHead's "Added in patch xxx" is completely broken. It's not a trustworthy source.

**Comment by Manaci** [comment]
This is true, he just gave a bad source. 4 other 2.1 items are ingame too. Easily noticed by how their weapon dmg and stats are not changed in 2.1 since they came with 2.1. Older archive databases also support this, but we're so close to 2.1 now and people got those items so it's not really worth to fix it I guess.

**Comment by Manaci** [comment]
Talon of the Phoenix - https://web.archive.org/web/20071016044117/http://wow.allakhazam.com/db/item.html?witem=32944 (high item number + just look at the damage on the weapon + no no changed stats from normal 2.4.3 databases)

Band of Vile Aggression - https://web.archive.org/web/20070526101807/http://wow.allakhazam.com:80/db/mob.html?wmob=21932 (2.0) vs https://web.archive.org/web/20070825025556/http://wow.allakhazam.com:80/db/mob.html?wmob=21932 (2.1) (Easiest to show from the archives)

Band of the Vigilant - https://web.archive.org/web/20071029131307/http://wow.allakhazam.com/db/item.html?witem=33058 (high item number + comments + no changed stats from normal 2.4.3 databases)

The Seal of Danzalar - https://web.archive.org/web/20070624145610/http://wow.allakhazam.com/db/item.html?witem=33054 (high item number + no comments before 2.1 + no changed stats from normal 2.4.3 databases)

Boots of the Resilient https://web.archive.org/web/20070705072217/http://wow.allakhazam.com/db/item.html?witem=32267(high item number + comments + no changed stats from normal 2.4.3 databases)

Then there's the raid items from 2.1 that ARE disabled

Runetotem's Mantle - https://db.excalibur.ws/?item=30111

Prism of Inner Calm - https://db.excalibur.ws/?item=30621

Wristguards of Determination - https://db.excalibur.ws/?item=32515

Gloves of the Searing Grip - https://db.excalibur.ws/?item=29947

**Comment by Tenoutoften** [comment]
The issue is valid, however we are closing in on 2.1 and I think this change would be more important for a potential relaunch than to change now since players have already obtained these items...
