### ISSUE TITLE
Full triangle quest: Can't turn in quest.

### ISSUE THREAD

**Issue by redyman777** [Atlantiss/NetherwingBugtracker#5717]
[//]: # https://tbc-twinhead.twinstar.cz/?quest=10276 
[//]: # 
![full triangle](https://user-images.githubusercontent.com/50152023/57015419-142b3600-6c15-11e9-8df3-0fd0957ea45a.PNG)

[//]: # (Full Triangle Quest Netherstorm 

[//]: # Image of Nexus-Prince Haramad

**Description**: 
Can't turn in quest after completing objective.
Tried abbandoning the quest and doing it again with same result, my mate 
' Leetpete ' is in the same situation. 

**Current behaviour**:
Not able to turn in quest.

**Expected behaviour**: 
Being able to turn in quest. 

**Server Revision**: 
Fix bug.

- Pikke

**Comment by danbopes** [comment]
Still happening

**Comment by danbopes** [comment]
His flags aren't resetting properly under certain circumstances:

Before reset:
![](https://i.imgur.com/jUq7YL8.png)

After reset:
![](https://i.imgur.com/z6WO5fw.png)

**Comment by danbopes** [comment]
rev 3432
