### ISSUE TITLE
Xi'ri's Gift and Scryer's Bloodgem

### ISSUE THREAD

**Issue by Jayriot** [Atlantiss/NetherwingBugtracker#5718]
[//]: # (Enclose links to things related to the bug using http://wowhead.com or any other TBC database.)
[//]: # (You can use screenshot ingame to visual the issue.)
[//]: # (Write your tickets according to the format:)
[//]: # ([Quest][Azuremyst Isle] Red Snapper - Very Tasty!)
[//]: # ([NPC] Magistrix Erona)
[//]: # ([Spell][Mage] Fireball)
[//]: # ([Npc][Drop] Ghostclaw Lynx)
[//]: # ([Web] Armory doesnt work)
[//]: # (To find server revision type `.server info` command in the game chat.)

**Description**: 
When I use Xi'ri's Gift in combat, I will not be able to use Scryer's Bloodgem once the effects of the former trinket wear off, and vice versa.

**Current behaviour**:
Unable to use both trinkets in battle. I am able to re-use whichever trinket I activated when the cooldown finishes, but not both.

**Expected behaviour**: 
Be able to use both trinkets in battle, like you can any other trinkets. This combination is the first problem I've had. I was able to use Xi'ri's Gift and Vengeance of the Illidari just fine (my previous trinket combination)

**Server Revision**: 
Unknown

**Comment by ircfelix** [comment]
I am not sure where you got the info that you can use both trinkets at the same time. Please provide a source that how you want it to work is as it should work, otherwise the bug report is invalid.

**Comment by Jayriot** [comment]
When I use one trinket, it won't let me use the other one during the same fight. I am not trying to use them at the same time. It won't let me use  the second trinket sequentially in a single fight.

**Comment by ircfelix** [comment]
Aaah I understand. Well, that makes no fucking sense and it should be addressed. Meanwhile I can only recommend you to use a passive trinket like Mark of Defiance or Shiffar's Nexus-Horn.

**Comment by Jayriot** [comment]
Haha, thank you! I’m gonna swap back to Vengeance in the meantime. I haven’t tried it to see if it works with the bloodgem yet, but I know that Xi’ri’s works with it.

**Comment by Baelek** [comment]
@Wolffenstein This is still an ongoing issue. Can we please have this fixed soon?

**Comment by Wolffenstein** [comment]
Fixed in rev 3198.

**Comment by Baelek** [comment]
This issue popped back up again in rev 3199 @Wolffenstein
