### ISSUE TITLE
[Quest] [Alterac Mountains] Cyclonian

### ISSUE THREAD

**Issue by NeverCleer** [Atlantiss/NetherwingBugtracker#5719]
[//]: # (Enclose links to things related to the bug using http://wowhead.com or any other TBC database.)
[//]: # (You can use screenshot ingame to visual the issue.)
[//]: # (Write your tickets according to the format:)
[//]: # ([Quest][Azuremyst Isle] Red Snapper - Very Tasty!)
[//]: # ([NPC] Magistrix Erona)
[//]: # ([Spell][Mage] Fireball)
[//]: # ([Npc][Drop] Ghostclaw Lynx)
[//]: # ([Web] Armory doesnt work)
[//]: # (To find server revision type `.server info` command in the game chat.)

**Description**: [Quest][Alterac Mountains] "Cyclonian" quest cannot be turned in with all required items. Likely related to completing and turning in [Quest][Stranglethorn Vale] "Hunt for Yenniku" in the meantime, similar to issue #923.

**Current behaviour**: Have all items in inventory, quest log shows complete, but quest giver remains silver question mark and quest unable to be turned in.

**Expected behaviour**: Quest should be able to be turned in.

**Server Revision**:

**Comment by KevinTyrrell** [comment]
Do you have [Bath'rah's Parchment] in your inventory? It is a quest item and deleting it may have softlocked you for the quest. If so, you will have to drop the quest and re-pick it up. That may include gathering the tusks again.

**Comment by NeverCleer** [comment]
Yes, I also have the parchment in my inventory along with the items to collect.

**Comment by KevinTyrrell** [comment]
Close WoW. Delete your cache folder. Open WoW.exe and try to turn in again. If that doesn't work, make 100% sure it's not some addon interfering.

**Comment by NeverCleer** [comment]
Thanks for your attention to this issue, KevinTyrrell.

Unfortunately, deleting the Cache folder also didn't fix the issue. I downloaded the game from the Atlantiss website and haven't downloaded any add-ons or other content to complement the game.

**Comment by KevinTyrrell** [comment]
@NeverCleer Try the following:
* Ensure nothing for the quest is in your bank, including extra bloodscalp tusks for example.
* Delete any extra quest items such as excess bloodscalp tusks.
* Assuming your quest says [Complete], try deleting a single bloodscalp tusk, putting you down to 29/30 incomplete. Then go farm a single bloodscalp tusk to 'refresh' the 30/30.

**Comment by NeverCleer** [comment]
I only had extra Liferoot in the bank. I took that out, traded it all away so that the quest was no longer [Complete] and recollected it. Still no good, unfortunately.

**Comment by NeverCleer** [comment]
I went to farm some more tusks, but I still cannot turn in. I think it's time to move on, but there seems to be an issue with the combination of [Quest] [Warrior] Cyclonian and [Quest] [Stranglethorn Vale] Hunt for Yenniku, as they have you farm the same item.

**Comment by danbopes** [comment]
What was your resolution?

**Comment by Manaci** [comment]
Way too obscure
