### ISSUE TITLE
[NPC] Syndicate Rogue/Watchman/Mage in Durnholde Keep

### ISSUE THREAD

**Issue by Kentamentiu** [Atlantiss/NetherwingBugtracker#572]
[//]: # (Enclose links to things related to the bug using http://wowhead.com or any other TBC database.)
[//]: # (You can use screenshot ingame to visual the issue.)
[//]: # (Write your tickets according to the format:)
[//]: # ([Quest][Azuremyst Isle] Red Snapper - Very Tasty!)
[//]: # ([NPC] Magistrix Erona)
[//]: # ([Spell][Mage] Fireball)
[//]: # ([Npc][Drop] Ghostclaw Lynx)
[//]: # ([Web] Armory doesnt work)

**Description**: 
Syndicate mobs are directly opposed to Ravenholdt. Killing syndicate personnel should give 5 reputation with Ravenholdt per kill.

**Current behaviour**:
Ravenholdt faction remains undiscovered and no reputation is granted for killing Syndicate mobs.

**Expected behaviour**: 
5 reputation per kill

**Server Revision**:
 2050

**Comment by Tereneckla** [comment]
Fixed

**Comment by Evolvee** [comment]
@Tereneckla it already works for me?

**Comment by Evolvee** [comment]
fixed in next rev
