### ISSUE TITLE
Psychic Scream

### ISSUE THREAD

**Issue by beefjurkey** [Atlantiss/NetherwingBugtracker#5720]
I play SL/SL lock in arena, my pet has over 200 resistance and priests don't gem spell pen generally (or not anywhere near 200 anyways) and are rarely hit capped (only if shadow). I also have 60+ resistance myself. Yet 99% of priest fears on NW hit me and my pet, even tho in the priest spellbook it comes under the shadow school and therefore should not even come close to hitting how much it does. (this includes disc priests that have 0 spell pen and little hit)
My 2 guesses are that its either not on any school of magic currently, or it got put in the holy school by mistake, either way its fucking up arenas really hard atm and the history of priv servers is when pvp dies, the server follow in that direction. There are already not enough locks playing and when you give warrior stormherald (bis mace till s4/5) it makes it even less attractive as they can 1 shot pets all the time!
Please look into this as i feel like not playing arena at all after being cucked by it all season already :(

**Comment by beefjurkey** [comment]
and then ontop of this my fears get resisted all the time when i'm almost hit and pen capped ..........

**Comment by bajkorv** [comment]
As resists seem fucked the opposit way, (ppl resist too much). Could it be so that priest fear currently is physical and not shadow as it should be? Only thing that would make sense if Pet actually almost never resists it

**Comment by ronyc** [comment]
May be unrelated but i feel like it's range is huge. It could be physical and benefiting from leeway which would explain lack of resists aswell.

**Comment by beefjurkey** [comment]
Also priest fear doesn't seem to brake as easily as warlock fear

**Comment by SwiftieTBC** [comment]
Psychic Scream is and should be Physical.
Proof : https://web.archive.org/web/20080307124021/http://www.wowhead.com/?spell=10891
