### ISSUE TITLE
[NPC]Leotheras the Blind HP too high

### ISSUE THREAD

**Issue by Spaztick** [Atlantiss/NetherwingBugtracker#5722]
**Description**: 
Leotheras in SSC (and rumor has it every other raid boss) has far too much HP.

**Current behaviour**:
HP is around 7.5 million

![leleo](https://user-images.githubusercontent.com/29140342/57117998-d0742180-6d25-11e9-81df-dcf659309033.png)

**Expected behaviour**: 
HP should be around 4.6 million [according to this video](https://www.youtube.com/watch?v=HnDQi2RCkSE) showing Nihilum killing Leo in 2008.

**Server Revision**: 
2950

**Comment by ircfelix** [comment]
I am not sure about Leo, but at least Vashj's HP are buffed, so the difficulty matches the 2.0 difficulty (back in 2007 pre nerf bosses had less hp, but people also did only like half or 2/3 of nowadays dps in patch 2.4.3 mechanics). It is possible that SSC and TK bosses will receive a nerf HP on 2.1 (only my guess, got no confirmation of that).

**Comment by Tenoutoften** [comment]
Netherwing uses custom values on lots of stuff and will continue to do so

**Comment by hederob** [comment]
"Leotheras the Blind's Chaos Blast radius has been significantly reduced, which will allow additional melee to damage Leotheras while he is in metamorphosis form. 
Leotheras the Blind will now also spend less time whirlwinding before shifting into his metamorphosis form. 
Leotheras the Blind's hit points have been reduced. "

From: <https://wowwiki.fandom.com/wiki/Patch_2.1.0>

Also this article: https://www.ownedcore.com/forums/world-of-warcraft/world-of-warcraft-guides/16185-leothoras-blind-strategy-guide.html

"Health - 2,300,000
Enrage - 10 minutes."

**Comment by Wolffenstein** [comment]
Intended.
