### ISSUE TITLE
[Quest][Mana Tombs] Someone_Else's_Hard_Work_Pays_Off

### ISSUE THREAD

**Issue by Tereneckla** [Atlantiss/NetherwingBugtracker#5723]
[//]: # (Enclose links to things related to the bug using http://wowhead.com or any other TBC database.)
[//]: # (You can use screenshot ingame to visual the issue.)
[//]: # (Write your tickets according to the format:)
[//]: # ([Quest][Azuremyst Isle] Red Snapper - Very Tasty!)
[//]: # ([NPC] Magistrix Erona)
[//]: # ([Spell][Mage] Fireball)
[//]: # ([Npc][Drop] Ghostclaw Lynx)
[//]: # ([Web] Armory doesnt work)
[//]: # (To find server revision type `.server info` command in the game chat.)

**Description**: 
https://www.wowhead.com/quest=10218/someone-elses-hard-work-pays-off
https://wowwiki.fandom.com/wiki/Quest:Someone_Else%27s_Hard_Work_Pays_Off

**Current behaviour**: 1 Nexus Terror stood at the 3rd spawn from the start, 1 Nexus Terror and 6 Mana Leeches spawned during the fight.
![WoWScrnShot_050319_120132](https://user-images.githubusercontent.com/50233983/57131727-a4948280-6d9d-11e9-9cc7-08fb5aa280bc.jpg)
**Expected behaviour**: 1 Nexus Terror stands at 3rd spawn from the start, 1 Nexus Terror spawns during the fight. 
The wowwiki link describes the escort. That is how it went on my earlier characters.

**Server Revision**: 2950

**Comment by Wolffenstein** [comment]
Fixed in rev 3365.
