### ISSUE TITLE
[Item] Ectoplasmic Distiller - Hunting for Ectoplasm

### ISSUE THREAD

**Issue by Kaini27** [Atlantiss/NetherwingBugtracker#5724]
[//]: # (Enclose links to things related to the bug using http://wowhead.com or any other TBC database.)
[//]: # (You can use screenshot ingame to visual the issue.)
[//]: # (Write your tickets according to the format:)
[//]: # ([Quest][Azuremyst Isle] Red Snapper - Very Tasty!)
[//]: # ([NPC] Magistrix Erona)
[//]: # ([Spell][Mage] Fireball)
[//]: # ([Npc][Drop] Ghostclaw Lynx)
[//]: # ([Web] Armory doesnt work)
[//]: # (To find server revision type `.server info` command in the game chat.)

**Description**: The item named Ectoplasmic Distiller (ID 21946) from quest Hunting for Ectoplasm (ID 8924) missing its animation.

**Current behaviour**: Completely missing animation

**Server Revision**: 2950

**Comment by Godmatik** [comment]
Fixed a few months ago
