### ISSUE TITLE
ARENA- SHAMAN- tremor totem not consistently removing fear

### ISSUE THREAD

**Issue by zmthc93** [Atlantiss/NetherwingBugtracker#5726]
[//]: # (Enclose links to things related to the bug using http://wowhead.com or any other TBC database.)
[//]: # (You can use screenshot ingame to visual the issue.)
[//]: # (Write your tickets according to the format:)
[//]: # ([Quest][Azuremyst Isle] Red Snapper - Very Tasty!)
[//]: # ([NPC] Magistrix Erona)
[//]: # ([Spell][Mage] Fireball)
[//]: # ([Npc][Drop] Ghostclaw Lynx)
[//]: # ([Web] Armory doesnt work)
[//]: # (To find server revision type `.server info` command in the game chat.)

**Description**: 
Tremor totem is not consistently removing fear on drop/ on pulse every 3 sec, even though it is down and in range. I believe this is either a line of sight issue on sloped terrain e.g. blades edge ramp, ruins of lordaeron stairs/ tomb (tremor shouldn't have line of sight) or priests dispel mechanics are being applied to tremors dispel (tremor dispel should not be affected by dispel resistance mechanics).

**Current behaviour**:
Tremor totem occasionaly does not work at all (particularly when placed on ramps

*Expected behaviour**: 
Tremor should remove fear every time on drop/ pulse if party member is in range

**Server Revision**:

**Comment by Macumbafeh** [comment]
+1

**Comment by Wolffenstein** [comment]
Fixed in rev 3198.
