### ISSUE TITLE
[Quest][Loot][Silithus]Field Duty

### ISSUE THREAD

**Issue by Shakill0Neal** [Atlantiss/NetherwingBugtracker#5727]
[//]: # (Enclose links to things related to the bug using http://wowhead.com or any other TBC database.)
[//]: # (You can use screenshot ingame to visual the issue.)
[//]: # (Write your tickets according to the format:)
[//]: # ([Quest][Azuremyst Isle] Red Snapper - Very Tasty!)
[//]: # ([NPC] Magistrix Erona)
[//]: # ([Spell][Mage] Fireball)
[//]: # ([Npc][Drop] Ghostclaw Lynx)
[//]: # ([Web] Armory doesnt work)
[//]: # (To find server revision type `.server info` command in the game chat.)

**Description**: A quest for reputation with Cenarion Circle that should let out from these letters as a reward a series of quests
https://wowwiki.fandom.com/wiki/Quest:Field_Duty

**Current behaviour**: At the moment each of the letters does not drop the quest items
![WoWScrnShot_050219_041654](https://user-images.githubusercontent.com/45425296/57187691-35c93d80-6ef3-11e9-9725-2de4d7e9ba65.jpg)

I also tried several times to make sure, but nothing
**Expected behaviour**: they should be found inside of the letters these quests
https://wowwiki.fandom.com/wiki/Hive%27Zora_Dossier
https://wowwiki.fandom.com/wiki/Hive%27Regal_Dossier
https://wowwiki.fandom.com/wiki/Hive%27Ashi_Dossier
https://wowwiki.fandom.com/wiki/Logistics_Assignment
https://wowwiki.fandom.com/wiki/Tactical_Assignment

**Server Revision**:

**Comment by Evolvee** [comment]
its because the quests were blocked (not available AQ content)

**Comment by Evolvee** [comment]
fixed in next rev
