### ISSUE TITLE
Distract is proccing mace stun

### ISSUE THREAD

**Issue by Vannort86** [Atlantiss/NetherwingBugtracker#5728]
[//]: # (Enclose links to things related to the bug using http://wowhead.com or any other TBC database.)
[//]: # (You can use screenshot ingame to visual the issue.)
[//]: # (Write your tickets according to the format:)
[//]: # ([Quest][Azuremyst Isle] Red Snapper - Very Tasty!)
[//]: # ([NPC] Magistrix Erona)
[//]: # ([Spell][Mage] Fireball)
[//]: # ([Npc][Drop] Ghostclaw Lynx)
[//]: # ([Web] Armory doesnt work)
[//]: # (To find server revision type `.server info` command in the game chat.)

**Description**: 
When using distract there is a 6% chance that the mob is affected by mace stun.

**Current behaviour**:
When using distract there is a 6% chance that the mob is affected by mace stun.
**Expected behaviour**: 
Distract shouldn't proc mace stun
**Server Revision**: 
2950

**Comment by Wolffenstein** [comment]
Can't reproduce.
