### ISSUE TITLE
[NPC] Venture Co. Enforcer

### ISSUE THREAD

**Issue by totaemoeggerli** [Atlantiss/NetherwingBugtracker#573]
[//]: # (Enclose links to things related to the bug using http://wowhead.com or any other TBC database.)
[//]: # (You can use screenshot ingame to visual the issue.)
[//]: # (Write your tickets according to the format:)
[//]: # ([Quest][Azuremyst Isle] Red Snapper - Very Tasty!)
[//]: # ([NPC] Magistrix Erona)
[//]: # ([Spell][Mage] Fireball)
[//]: # ([Npc][Drop] Ghostclaw Lynx)
[//]: # ([Web] Armory doesnt work)

**Description**: 
Venture Co. Enforcer appeares out of nothing.
https://www.wowhead.com/npc=3283/venture-co-enforcer

**Current behaviour**:
https://gfycat.com/gifs/detail/UnrulyHorribleAlaskankleekai
not sure if he was underground or something like that
doesn't look like respawn, didn't have any other mobs respawning 

**Expected behaviour**: 
The NPC should have been visible before I pulled the one in the back.

**Server Revision**:

**Comment by aresbrutus** [comment]
https://gfycat.com/PrestigiousRedGreyhounddog
https://gfycat.com/UnknownAmpleBinturong

Works fine for me.

**Comment by totaemoeggerli** [comment]
there was a guy that died further into the mine and he might have killed it back there but it later respawned at the entrance of the mine(later then the mobs around him)
however, shouldn't there be a grace periode between spawning and engaging combat?

**Comment by aresbrutus** [comment]
Client issue so closing it.
