### ISSUE TITLE
[Pet][Hunter]Pets loosing learned resistances after being ressurected

### ISSUE THREAD

**Issue by caiopmartins** [Atlantiss/NetherwingBugtracker#5730]
**Description**: After resurrecting your pet, sometimes he will spawn without any learned resistances.

**Current behavior**: Sometimes pet will resurrect without learned resistances.

**Expected behavior**: Pet shouldn't spawn without his learned resistances.

**Server Revision**: 2950

**Comment by Dragunovka** [comment]
up

**Comment by Kristoferhh** [comment]
Noticed this when we were on Curator and my pet with max arcane resistance wasn't resisting anything at all

**Comment by Zarant** [comment]
#5029

**Comment by shatich** [comment]
Can confirm it too, happened to me too yesterday

**Comment by czarecoo** [comment]
Can confirm it too, it happens when your pet dies and you resurrect it after its corpse is dispawned.

**Comment by Dragunovka** [comment]
guys, time to fix it

**Comment by Kristoferhh** [comment]
This also applies to avoidance so I'm guessing it's all passives including cobra reflexes?

**Comment by mbzz88** [comment]
Yep, everything it seems, pretty big issue for raiding, since you not only have to res your pet, but then dismiss it and resummon.
Possibily related to being in combat when casting Revive Pet?

**Comment by Dragunovka** [comment]
@Wolffenstein please

**Comment by Wolffenstein** [comment]
Fixed in rev 3028.
