### ISSUE TITLE
Ikiss immune

### ISSUE THREAD

**Issue by moonsinner** [Atlantiss/NetherwingBugtracker#5732]
# https://de.wowhead.com/npc=18473/klauenkönig-ikiss#english-comments
 # (The final Boss in Sethekk Halls normal is immune to taunt used by a druid)

[//]: # ([NpC][Auchindoun] sethekk halls)
[//]: # ([NPC] Ikiss )
[//]: # ([Spell][Druid] Growl)

**Description**: 
Final Boss Ikiss in Sh normal.

**Current behaviour**:
Ikiss is immune to taunt (at least for druid class taunt). According to guides he has no such immuny. https://de.wowhead.com/npc=18473/klauenkönig-ikiss#english-comments
**Expected behaviour**: 
Ikiss should be tauntable.

**Server Revision**: 
Dont know. I am online later.

**Comment by Kaini27** [comment]
its only immune to taunt for first couple of seconds after explosion/bubble?

**Comment by moonsinner** [comment]
1. Couple sec for shure.
Think it was complete time.
Next time ill try taunt before his first explosion

**Comment by DaedalusMachina007** [comment]
This is still an issue as of 18-November-2019.
Paladin Taunt (Rightous Defense) shows 'immune' message when attempting to taunt either before or even a few seconds after his blink/arcane explosion; tried multiple times at various parts of his fight and still immune.

Please remove the taunt immunity.  Leave it for heroic if you want but having it on normal is absurd and NOT blizzlike (according to wowhead comments).

**Comment by Easyfraggy** [comment]
Some video proof would be nice - The comments are post nerf heroics. I believe he should be tauntable in Normal the question is about HC.

**Comment by Wolffenstein** [comment]
Fixed in rev 3194.
