### ISSUE TITLE
[Quest]Attack on Camp Narache

### ISSUE THREAD

**Issue by ghost** [Atlantiss/NetherwingBugtracker#5734]
[//]: # (Enclose links to things related to the bug using http://wowhead.com or any other TBC database.)
[//]: # (You can use screenshot ingame to visual the issue.)
[//]: # (Write your tickets according to the format:)
[//]: # ([Quest][Azuremyst Isle] Red Snapper - Very Tasty!)
[//]: # ([NPC] Magistrix Erona)
[//]: # ([Spell][Mage] Fireball)
[//]: # ([Npc][Drop] Ghostclaw Lynx)
[//]: # ([Web] Armory doesnt work)
[//]: # (To find server revision type `.server info` command in the game chat.)

**Description**: 
Cannot start quest - Attack on Camp Narache 

**Current behaviour**:
Cannot loot https://www.wowhead.com/object=3076/dirt-stained-map

**Expected behaviour**: 
https://www.wowhead.com/object=3076/dirt-stained-map sould be looted in order to start the quest https://www.wowhead.com/quest=781/attack-on-camp-narache

**Server Revision**:

**Comment by Tereneckla** [comment]
works
