### ISSUE TITLE
[Item] Braided Eternium Chain

### ISSUE THREAD

**Issue by FabianMueller77** [Atlantiss/NetherwingBugtracker#5736]
**Description**: 
The buff from Braided Eternium Chain ( https://www.wowhead.com/item=24114/ ) gets removed upon shapeshifting. This might also happen with some of the other jewelcrafting necklaces that provide partywide buffs.

**Current behaviour**: 
https://giant.gfycat.com/MatureQuarterlyGhostshrimp.webm

**Expected behaviour**: 
There's very little information online about this, but this should probably not be the case.
Ít's not about Leader of the Pack overriding it, as it gets cancelled when shifting into travel form for example.

**Server Revision**: 
2950

**Comment by FabianMueller77** [comment]
Still not working correctly.
All other jewelcrafting necks that provide 30 minute buffs for the group get cancelled.
Also gets cancelled by Moonkin and Tree of Life shapeshifts.

This is kind a big deal for druid raid performance

**Comment by Wolffenstein** [comment]
It has SPELL_ATTR0_NOT_SHAPESHIFT.

It's working correctly.
