### ISSUE TITLE
[Item] The Hammer of Grace

### ISSUE THREAD

**Issue by dokuro3** [Atlantiss/NetherwingBugtracker#5738]
[//]: # (Enclose links to things related to the bug using http://wowhead.com or any other TBC database.)
[//]: # (You can use screenshot ingame to visual the issue.)
[//]: # (Write your tickets according to the format:)
[//]: # ([Quest][Azuremyst Isle] Red Snapper - Very Tasty!)
[//]: # ([NPC] Magistrix Erona)
[//]: # ([Spell][Mage] Fireball)
[//]: # ([Npc][Drop] Ghostclaw Lynx)
[//]: # ([Web] Armory doesnt work)
[//]: # (To find server revision type `.server info` command in the game chat.)

**Description**: 
[The Hammer of Grace](http://db.excalibur.ws/?item=11923) gives 31 healing and 11 spell power. The healing is being applied, the spell power is not. 

This is reflected in the character sheet in the screenshots: while bonus healing increases when the item is equipped, the listed spell power remains at 125 whether or not the item is equipped.

![Screenshot (19)](https://user-images.githubusercontent.com/50556904/57587791-f5f8ec00-74d8-11e9-98ed-9f07c651e6b0.png)
![Screenshot (20)](https://user-images.githubusercontent.com/50556904/57587792-f5f8ec00-74d8-11e9-9590-186c347f7a1a.png)

**Current behaviour**:
+31 healing

**Expected behaviour**: 
+31 healing and +11 spell power

**Server Revision**: 
2950

**Comment by Kaini27** [comment]
close to none of the items that give bonus healing would aslo give spell power on this patch

**Comment by Godmatik** [comment]
Items do not get spell power until patch 2.3.

You are viewing wrong data on your client. Delete your cache folder.

**Comment by Godmatik** [comment]
Not sure why this was flagged as 'need research', the item is fine.

The original poster simply has a game that is showing patch 2.3 details. It's client side and this issue should instead be closed.
