### ISSUE TITLE
[NPCs] Nameplates Cast bar bug.

### ISSUE THREAD

**Issue by Talarok** [Atlantiss/NetherwingBugtracker#5739]
[//]: # (Enclose links to things related to the bug using http://wowhead.com or any other TBC database.)
[//]: # (You can use screenshot ingame to visual the issue.)
[//]: # (Write your tickets according to the format:)
[//]: # ([Quest][Azuremyst Isle] Red Snapper - Very Tasty!)
[//]: # ([NPC] Magistrix Erona)
[//]: # ([Spell][Mage] Fireball)
[//]: # ([Npc][Drop] Ghostclaw Lynx)
[//]: # ([Web] Armory doesnt work)
[//]: # (To find server revision type `.server info` command in the game chat.)

**Description**: 
When an enemy NPC casts a spell with nameplates active, the cast bar remains after the cast has finished.
**Current behavior**:
NPC casts spell, nameplate shows cast properly, empty cast bar remains after cast complete.
**Expected behavior**: 
NPC cast bar should disappear after spell is cast and only show up once again on an addition spell being cast.
**Server Revision**: 
![image](https://user-images.githubusercontent.com/48861986/57589747-6eb97180-74f4-11e9-8c15-9ea9a8807017.png)

**Comment by randomuser69** [comment]
Hey, same issue here. I was able to fix it for now by getting the plate castbar addon. No link atm sry. I forgot where i got it. Ill update with more info once i can

**Comment by Tereneckla** [comment]
addon issue
