### ISSUE TITLE
[NPC] Maggoc

### ISSUE THREAD

**Issue by KevinTyrrell** [Atlantiss/NetherwingBugtracker#5741]
[//]: # (Enclose links to things related to the bug using http://wowhead.com or any other TBC database.)
[//]: # (You can use screenshot ingame to visual the issue.)
[//]: # (Write your tickets according to the format:)
[//]: # ([Quest][Azuremyst Isle] Red Snapper - Very Tasty!)
[//]: # ([NPC] Magistrix Erona)
[//]: # ([Spell][Mage] Fireball)
[//]: # ([Npc][Drop] Ghostclaw Lynx)
[//]: # ([Web] Armory doesnt work)
[//]: # (To find server revision type `.server info` command in the game chat.)

**Description**: 
[Streamable Clip](https://streamable.com/obf20)

Maggoc was seen flying directly to his normal pathing route seemingly out of nowhere. I don't know how to replicate this, but it should probably be looked at to determine if Maggoc's pathing is correctly setup at each waypoint. It is unlikely but also possible that a player aggroed him, kited him a far distance, and had him reset. Those resets over long distances tend to produce things like this. Though even then, if that were to be the case, Maggoc would disappear and reappear on his pathing route instead of fly through terrain.

**Current behaviour**:
N/A

**Expected behaviour**: 
N/A

**Server Revision**: 
2951

**Comment by Tereneckla** [comment]
it's a reset from a long distance
