### ISSUE TITLE
Fel Mana Potion debuff problems

### ISSUE THREAD

**Issue by Anselm123** [Atlantiss/NetherwingBugtracker#5742]
**Description**: Using a fel mana potion reduces your spell damage by 50 instead of 25. It also brings you into negative values of spell damage but not healing. Not sure if you are meant to have negative values of stats couldn't find anywhere that said this was ever possible and if it is, then it's not applying to +healing and if not then it's allowing minus spell damage and is 50 and not 25.

**Current behaviour**: Minus 50 spell damage and healing instead of 25/50 split and also bringing spell damage into minus values and not healing.

**Expected behaviour**: 25/50 split and not 100% about the minus values

**Server Revision**: 2951

![image](https://user-images.githubusercontent.com/36844570/57651976-e3f97500-75ce-11e9-9a01-246c3d31493d.png)

**Comment by Anselm123** [comment]
Picture is showing where the 27 Spell damage is coming from and why it's minus 23

**Comment by Anselm123** [comment]
also when it pop a second it takes me to minus 50

**Comment by devo6969** [comment]
This is fixed can not recreate even with the alchemist stone. 👍
