### ISSUE TITLE
[Withered Flesh ][Zangramarsh] 

### ISSUE THREAD

**Issue by LDGTL** [Atlantiss/NetherwingBugtracker#5743]
Parched Hydra

**Description**: 
Debuff from Parched Hydras is bugged and reduce the chance to hit by 100% instead of 35%
**Current behavior**:
The current debuff from quest mobs reduces the chance to hit bt 100%
**Expected behavior**: 
Debuff from the mobs should reduce the chance to hit by 35%
**Server Revision**: 
2951

**Comment by devo6969** [comment]
Still an issue on the PTR

**Comment by Godmatik** [comment]
Rev 4016
Seems like 35% to me
I am able to get some hits off even with the debuff on me - not a bug
