### ISSUE TITLE
Quest Guardians of the altar 

### ISSUE THREAD

**Issue by Picvajz** [Atlantiss/NetherwingBugtracker#5744]
Quest Guardians of the altar is not working.After you light all the torches in the caves Npc comes in front of the altar.She begins to cast her spell and after you click on the altar nothing happens.There should be a little scene with Elune talking about Wildkin and that does not happen.I stayed near the altar for about 5 minutes and as soon as I moved from the spot for like 5 meter quest failed.This quest is in Winterspring.

**Comment by leeviathan** [comment]
Here's a video of what's supposed to happen when the player clicks the Altar: https://www.youtube.com/watch?v=lemc6SKROJQ

**Comment by Vyriam** [comment]
This quest isn't still working as of patch 2.2.....
The problem imo is that when you're doing the escort, you light up the 5 torches(that works correctly) but when you approach the altar, you can see that it's already glowing like if it was activated before you clicked on it(it's supposed to not be glowing and start glowing after you click on it...)

Server Revision : 3109

**Comment by Evolvee** [comment]
https://github.com/Atlantiss/NetherwingBugtracker/issues/4299
