### ISSUE TITLE
[hunter] ammo pouch/quiver (?) speed bug

### ISSUE THREAD

**Issue by Dragunovka** [Atlantiss/NetherwingBugtracker#5745]
Need to fix

https://www.twitch.tv/videos/423962940?t=00h24m39s

**Comment by Manaci** [comment]
Video is dead so /shrug

**Comment by eri1997** [comment]
Smb on discord complained about this happening again today. The video was just a hunter randomly notices his attack speed bonus from quiver gonne mid raid . You have to unequip and reequip the quiver to regain the attack speed bonus.Annoying bug as its confusing and you don't think of checking your attack speed suddenly being wrong . @Manaci
