### ISSUE TITLE
[Quest][Silithus] Aurel Goldleaf not offering the quests towards summoning items

### ISSUE THREAD

**Issue by b15andga** [Atlantiss/NetherwingBugtracker#5746]
[//]: # (Enclose links to things related to the bug using http://wowhead.com or any other TBC database.)
[//]: # (You can use screenshot ingame to visual the issue.)
[//]: # (Write your tickets according to the format:)
[//]: # ([Quest][Azuremyst Isle] Red Snapper - Very Tasty!)
[//]: # ([NPC] Magistrix Erona)
[//]: # ([Spell][Mage] Fireball)
[//]: # ([Npc][Drop] Ghostclaw Lynx)
[//]: # ([Web] Armory doesnt work)
[//]: # (To find server revision type `.server info` command in the game chat.)

**Description**: 
Quests such as "Dukes of the Council"; "Lords of the Council" and "Twilight Ring of Lordship" should be offered. The first two mentioned should be repeatable. Dukes of the Council should require friendly, and Lords of the Council should require revered, with the Cenarion Circle IIRC.
More can be read at https://wowwiki.fandom.com/wiki/Wind_stone
**Current behaviour**:
These quests are still not being offered after having finished all prequests (as confirmed by a GM) and I grinded my way up to Exalted.

**Expected behaviour**: 
Reputation should unlock these repeatable quests. Unsure about the non-repeatable quests, I believe they should be unlocked at the same reputation or one rep tier below.
**Server Revision**: 
2951

**Comment by Manaci** [comment]
Part of an old [big post](https://github.com/Atlantiss/NetherwingBugtracker/issues/5473) I made 1.5 months ago. Was self-assigned by Evolve but only a small part of it has been fixed so far. Hopefully it'll be worked on further after 2.1 has been deployed.

**Comment by Dragunovka** [comment]
> 
> 
> Hopefully it'll be worked on further after 2.1 has been deployed.

or not xd, i see 0 activity on fixing bugs lately.

**Comment by Evolvee** [comment]
should already be fixed?
