### ISSUE TITLE
Warp-Spring Coil

### ISSUE THREAD

**Issue by TheRealRickle** [Atlantiss/NetherwingBugtracker#5747]
[//]: # (Enclose links to things related to the bug using http://wowhead.com or any other TBC database.)
[//]: # (You can use screenshot ingame to visual the issue.)
[//]: # (Write your tickets according to the format:)
[//]: # ([Quest][Azuremyst Isle] Red Snapper - Very Tasty!)
[//]: # ([NPC] Magistrix Erona)
[//]: # ([Spell][Mage] Fireball)
[//]: # ([Npc][Drop] Ghostclaw Lynx)
[//]: # ([Web] Armory doesnt work)
[//]: # (To find server revision type `.server info` command in the game chat.)

**Description**: 
Does not give increased armor pen on procs. If anything it makes you do less damage.
**Current behaviour**:
Does not give increased armor pen on procs. If anything it makes you do less damage.
**Expected behaviour**: 
Supposed to increase your damage.
**Server Revision**: 
2951

**Comment by ircfelix** [comment]
Source my lord?

**Comment by TheRealRickle** [comment]
Rogue in the guild has it, his dmg doesn't go up AT ALL when it procs

**Comment by ircfelix** [comment]
Looks like a case for aniki!

https://www.youtube.com/watch?v=WrhJz83WWPc

**Comment by TheRealRickle** [comment]
:GachiGasm:

**Comment by Haipethdev** [comment]
https://www.youtube.com/watch?v=7SuJfni3wD8&feature=youtu.be

Posting this on behalf of rogue guildy.  As seen, this is still broken as of 2.1 launch.  Any chance of an ETA on fix or intention to raise priority and if you require any help with testing?

**Comment by natoxz** [comment]
Hi everyone,

I've done a test with a cutlass and a wsc equipped. Everything else off.

Servant Allistarj has, according to excalibur db, 3216 - 3271 armor.

I hope this helps you fixing the issue as it's one of the best trinkets for t6 progression for rogues.

https://www.youtube.com/watch?v=7SuJfni3wD8&feature=youtu.be

Cheers

**Comment by Easyfraggy** [comment]
From what I can tell on that video it does work. I believe I also tested this for someone a while ago and it worked fine.
