### ISSUE TITLE
[NPC] "The Dukes of ___" not dropping loot as they should

### ISSUE THREAD

**Issue by b15andga** [Atlantiss/NetherwingBugtracker#5748]
[//]: # (Enclose links to things related to the bug using http://wowhead.com or any other TBC database.)
[//]: # (You can use screenshot ingame to visual the issue.)
[//]: # (Write your tickets according to the format:)
[//]: # ([Quest][Azuremyst Isle] Red Snapper - Very Tasty!)
[//]: # ([NPC] Magistrix Erona)
[//]: # ([Spell][Mage] Fireball)
[//]: # ([Npc][Drop] Ghostclaw Lynx)
[//]: # ([Web] Armory doesnt work)
[//]: # (To find server revision type `.server info` command in the game chat.)

**Description**: 
Drops:
[Abyssal Signet]
Always drops either a random BoE uncommon, a random BoE rare, or a BoP rare item
Assorted elemental drops
Source: https://wowwiki.fandom.com/wiki/Wind_stone
**Current behaviour**:
Does not always drop green/blue item. This kill, for instance, did only yield one Abyssal Signet and nothing more.
![image](https://user-images.githubusercontent.com/18015872/57738979-116b1f00-76b2-11e9-9c7b-b5e25b3c6fb0.png)

**Expected behaviour**: 
Should always drop "either a random BoE uncommon, a random BoE rare, or a BoP rare item", "Assorted elemental drops" and an Abyssal Signet.
**Server Revision**: 
2952

**Comment by Evolvee** [comment]
fixed in next rev
