### ISSUE TITLE
[Object] Windstones aren't respawning

### ISSUE THREAD

**Issue by b15andga** [Atlantiss/NetherwingBugtracker#5749]
[//]: # (Enclose links to things related to the bug using http://wowhead.com or any other TBC database.)
[//]: # (You can use screenshot ingame to visual the issue.)
[//]: # (Write your tickets according to the format:)
[//]: # ([Quest][Azuremyst Isle] Red Snapper - Very Tasty!)
[//]: # ([NPC] Magistrix Erona)
[//]: # ([Spell][Mage] Fireball)
[//]: # ([Npc][Drop] Ghostclaw Lynx)
[//]: # ([Web] Armory doesnt work)
[//]: # (To find server revision type `.server info` command in the game chat.)

**Description**: 
Wind Stones aren't respawning as intended. I have only found them respawn after server restarts, and I have been scouting them for days. Approx respawn time should be around 15 min.
**Current behaviour**:
Wind Stones are not respawning (save for server restarts).
**Expected behaviour**: 
"The respawn time on the Wind stones seems to be approximately 15 minutes."
Source: https://wowwiki.fandom.com/wiki/Wind_stone
**Server Revision**: 
2952

**Comment by Evolvee** [comment]
https://github.com/Atlantiss/NetherwingBugtracker/issues/5613
