### ISSUE TITLE
Sunhawk Reclaimer Aggro Links

### ISSUE THREAD

**Issue by ttghnw** [Atlantiss/NetherwingBugtracker#575]
[//]: # (Enclose links to things related to the bug using http://wowhead.com or any other TBC database.)
[//]: # (You can use screenshot ingame to visual the issue.)
[//]: # (Write your tickets according to the format:)
[//]: # ([Quest][Azuremyst Isle] Red Snapper - Very Tasty!)
[//]: # ([NPC] Magistrix Erona)
[//]: # ([Spell][Mage] Fireball)
[//]: # ([Npc][Drop] Ghostclaw Lynx)
[//]: # ([Web] Armory doesnt work)

**Description**: **Current behaviour**:
The three visible reclaimers on the SS aggroed all together even though they are at a respectable distance and I didn't go close enough to all of them
![wowscrnshot_092518_203946](https://user-images.githubusercontent.com/43508698/46038505-284d0900-c103-11e8-9c4c-64b2d90e0cb4.jpg)

**Expected behaviour**: 
Single aggro
**Server Revision**:

**Comment by Evolvee** [comment]
cant reproduce

**Comment by ttghnw** [comment]
It was odd, might have been fixed from some other core change. 
 
When this happened the mob you see on the left aggroed first from range as I was further on the left of the pillar, as I LOSd it and it moved it provoked the aggro from an unusual range of the second and third successively. 

Thanks for taking a look.
