### ISSUE TITLE
Totem's follow player

### ISSUE THREAD

**Issue by Hiukiji** [Atlantiss/NetherwingBugtracker#5750]
**Description**: 
The fire totems the Foulweald Totemic's drop in Ashenvale.
**Current behaviour**:
The fire totems glide across the ground if the player moves out of the range of the fire totem.
**Expected behaviour**: 
To not follow the player.
**Server Revision**: 
2952

**Comment by KevinTyrrell** [comment]
Can confirm.

Also I believe this issue may be the same on other mobs which summon totems. For example the second boss of Slave Pens.

**Comment by Tereneckla** [comment]
https://youtu.be/gbKOIv7EY8o

**Comment by Godmatik** [comment]
Duplicate
