### ISSUE TITLE
Power Word: Shield with 4/5 S1 weakened soul

### ISSUE THREAD

**Issue by Whatsthis880** [Atlantiss/NetherwingBugtracker#5751]
**Description**: Having at least 4/5 S1 set which should grants -2 seconds on the Weakened Soul effect does not apply when putting a shield on a different target than the priest

**Current behaviour**: see description

**Expected behaviour**: should be a 13 seconds debuff and not 15 seconds on a different target as-well

**Server Revision**: 2952

**Comment by Wolffenstein** [comment]
Fixed in rev 3079.
