### ISSUE TITLE
Dispelling spellstealed buffs

### ISSUE THREAD

**Issue by Whatsthis880** [Atlantiss/NetherwingBugtracker#5752]
**Description**: When a mage spellsteal a buff, it takes lots of dispel magic to remove it. It may be linked to the Silent Resolve talent , but it can take from 5 to 10 dispel magic to remove a spellstealed buff. It occured way more than once
This situation often occured with 2/5 Silent Resolve talent and Power Word : Shield as the spellstealed buff

**Current behaviour**: see description

**Expected behaviour**: Should not have such high undispellable percentage, if any?

**Server Revision**: 2952

**Comment by Hidehugo** [comment]
BUMP : Still takes 7-10 priest dispels to get a stolen shield off. Can we get an ETA on that?

**Comment by Wolffenstein** [comment]
Fixed in rev 3064.
