### ISSUE TITLE
Seal of Blood while MC'd

### ISSUE THREAD

**Issue by TheRealRickle** [Atlantiss/NetherwingBugtracker#5755]
[//]: # (Enclose links to things related to the bug using http://wowhead.com or any other TBC database.)
[//]: # (You can use screenshot ingame to visual the issue.)
[//]: # (Write your tickets according to the format:)
[//]: # ([Quest][Azuremyst Isle] Red Snapper - Very Tasty!)
[//]: # ([NPC] Magistrix Erona)
[//]: # ([Spell][Mage] Fireball)
[//]: # ([Npc][Drop] Ghostclaw Lynx)
[//]: # ([Web] Armory doesnt work)
[//]: # (To find server revision type `.server info` command in the game chat.)

**Description**: 
While MCd, Seal of Blood does around 3-400% of your white hit damage which is not supposed to happen. On vashj I can hit people for 2k melee hit and 8k normal hits with seal of blood, can crit for 11-12k.
**Current behaviour**:
Seal of blood does WAY too much damage while the paladin is MCd
**Expected behaviour**: 
Should do less damage than white melee hits while MCd
**Server Revision**: 
2952

**Comment by TheRealRickle** [comment]
https://www.youtube.com/watch?v=JM1qPZCK1HI&feature=youtu.be

**Comment by teddys** [comment]
question is why do you even have weapon equipped when mc is about to hit

**Comment by TheRealRickle** [comment]
Because we have a 2nd tank picking up melee MCs. Before the fix to MCs damage a couple of weeks ago it was working fine, but since then it's been busted

**Comment by teddys** [comment]
unequip weapon before mc and melee is harmless if mced

**Comment by TheRealRickle** [comment]
That's not the point. The point is it's bugged, hence why it's on the bugtracker. I don't understand why you're arguing the fact. It was working fine like a month ago and now it's not.

**Comment by Tereneckla** [comment]
closed, see #6408
