### ISSUE TITLE
[Raid][SSC][NPC] Fathom-Guard Tidalvess' Frostshock procs windfury

### ISSUE THREAD

**Issue by Spaztick** [Atlantiss/NetherwingBugtracker#5756]
**Description**: 
Fathom-Guard Tidalvess' Frostshock procs windfury, should not.

![LOL](https://user-images.githubusercontent.com/29140342/57897909-79d60f80-781c-11e9-8743-c0cd60a6526d.png)

**Server Revision**: 
2952

**Comment by coreymyers** [comment]
It's not actually proccing windfury it's a bug when someone has windfury that it will show abilities as being (Windfury) but not actually proccing windfury. Probably a recount related bug or combat log bug.  But it's not additional damage it's just regular Frost Shock damage that is mislabelled. You'll see the same bug in recount when you give a paladin windfury and their consecration shows up as (Windfury) as well.
