### ISSUE TITLE
Anger Guard does not drop mote of shadow

### ISSUE THREAD

**Issue by hederob** [Atlantiss/NetherwingBugtracker#5757]
**Description**: 
Anger Guard drops no mote of shadow 
**Current behaviour**:
Mote of shadow not on Anger Guard's loot table even having killed 50 of them. 
**Expected behaviour**: 
Should drop 1-2 motes of shadow about 20% of the time when killed.
**Server Revision**:

**Comment by Tereneckla** [comment]
only source for this is twinhead database,  lul
motes do not appear on thottbot or wowhead
