### ISSUE TITLE
[Spell][Warrior] Victory Rush does not proc itself

### ISSUE THREAD

**Issue by rychersky** [Atlantiss/NetherwingBugtracker#5758]
[//]: # (Enclose links to things related to the bug using http://wowhead.com or any other TBC database.)
[//]: # (You can use screenshot ingame to visual the issue.)
[//]: # (Write your tickets according to the format:)
[//]: # ([Quest][Azuremyst Isle] Red Snapper - Very Tasty!)
[//]: # ([NPC] Magistrix Erona)
[//]: # ([Spell][Mage] Fireball)
[//]: # ([Npc][Drop] Ghostclaw Lynx)
[//]: # ([Web] Armory doesnt work)
[//]: # (To find server revision type `.server info` command in the game chat.)

**Current behaviour**: If you land a killing blow with Victory Rush, it does not proc a subsequent Victory Rush.

**Expected behaviour**: A killing blow caused by Victory Rush should proc another Victory Rush.

**Server Revision**: 2952

**Comment by teddys** [comment]
confirming this

**Comment by Wolffenstein** [comment]
Fixed in rev 3536.
