### ISSUE TITLE
[Karazhan Quest]: (Restorer No More) Item issue

### ISSUE THREAD

**Issue by Kjaeren** [Atlantiss/NetherwingBugtracker#5759]
[//]: # (Enclose links to things related to the bug using http://wowhead.com or any other TBC database.)
[//]: # (You can use screenshot ingame to visual the issue.)
[//]: # (Write your tickets according to the format:)
[//]: # ([Quest][Azuremyst Isle] Red Snapper - Very Tasty!)
[//]: # ([NPC] Magistrix Erona)
[//]: # ([Spell][Mage] Fireball)
[//]: # ([Npc][Drop] Ghostclaw Lynx)
[//]: # ([Web] Armory doesnt work)
[//]: # (To find server revision type `.server info` command in the game chat.)

Link to the quest: https://tbc-twinhead.twinstar.cz/?quest=11034

**Description**:

 In order to complete the quest, you simply have to give her your old ring, and 75 gold. Upon completing the quest, you should be able to choose another ring.
Attached screenshot of current ring, and required ring for completing quest.
![WoWScrnShot_051719_190931](https://user-images.githubusercontent.com/48409365/57944585-1e6d5580-78e0-11e9-8b5c-24addd74c827.jpg)

**Current behaviour**:

 I can not complete the quest, because I dont have the right ring.

**Expected behaviour**:

 I should be able to complete the quest, but I dont have the right ring.

**Server Revision**: 

(2942)

**Comment by Manaci** [comment]
Fixed
