### ISSUE TITLE
Inoculated Nestlewood Owlkin causing aggro for Mutated Owlkin to player

### ISSUE THREAD

**Issue by Notmittz** [Atlantiss/NetherwingBugtracker#576]
([Quest][Azuremyst Isle] Inoculation)

**Description**: 
After Inoculating a Nestlewood Owlkin, they start to wonder around.  If they wander too close to a Mutated Owlkin, they will register it as a aggro and run at the player to attack them (the Mutate Owlkin, not the Inoculated one)

**Current behaviour**:
Mutated Owlkin will pull off and aggro from a wandering Inoculated Nestlewood Owlkin if the two NPC's are too close.

**Expected behaviour**: 
Mutated Owlkin should not pull from this patting mob.

**Server Revision**:

**Comment by Kiperr** [comment]
Add inhabittype civilan.

**Comment by Evolvee** [comment]
we have different extra flags now Kiper :D 
![image](https://user-images.githubusercontent.com/1942409/46309100-b0c42180-c5bb-11e8-8c23-234c705d4851.png)

i will try this bandage you posted above ^^ but the cpp should be rewritten

rev xdd
