### ISSUE TITLE
Warlock Dots Doing No Damage

### ISSUE THREAD

**Issue by chaostheory102** [Atlantiss/NetherwingBugtracker#5760]
[//]: # (Enclose links to things related to the bug using http://wowhead.com or any other TBC database.)
[//]: # (You can use screenshot ingame to visual the issue.)
[//]: # (Write your tickets according to the format:)
[//]: # ([Quest][Azuremyst Isle] Red Snapper - Very Tasty!)
[//]: # ([NPC] Magistrix Erona)
[//]: # ([Spell][Mage] Fireball)
[//]: # ([Npc][Drop] Ghostclaw Lynx)
[//]: # ([Web] Armory doesnt work)
[//]: # (To find server revision type `.server info` command in the game chat.)

**Description**: 
Dots are up and are ticking but they are doing 0 damage
**Current behaviour**:
Dots are doing 0 damage. Video Proof    https://youtu.be/egz9gkfdYV0
**Expected behaviour**: 
Dots do damage
**Server Revision**:

**Comment by wtRCH** [comment]
All shadow damage DoTs aren't doing damage when looking at the video.

@chaostheory102 Does the bug appears only on these mobs you showed in your video or it applies to any other?

**Comment by devo6969** [comment]
Seems fixed, tested on the PTR, could not recreate.
