### ISSUE TITLE
talent gain does not work

### ISSUE THREAD

**Issue by sleg13** [Atlantiss/NetherwingBugtracker#5761]
talent  [Improved Berserker Stance] gain does not work
http://images.vfl.ru/ii/1558157808/2b4a27be/26572234.jpg
http://images.vfl.ru/ii/1558157898/3f89f78b/26572250.jpg

**Comment by sleg13** [comment]
Server Revision: 2952

**Comment by Tenoutoften** [comment]
Did you try to log out and back in again?

**Comment by sleg13** [comment]
yes

**Comment by sleg13** [comment]
> Did you try to log out and back in again?

yes

**Comment by wtRCH** [comment]
@sleg13 Invalid, please read what does the talent tooltip say.
