### ISSUE TITLE
[Item] Demon Forged Breastplate no Scaling 

### ISSUE THREAD

**Issue by Nienis** [Atlantiss/NetherwingBugtracker#5762]
[//]: # (Enclose links to things related to the bug using http://wowhead.com or any other TBC database.)
[//]: # (You can use screenshot ingame to visual the issue.)
[//]: # (Write your tickets according to the format:)
[//]: # ([Quest][Azuremyst Isle] Red Snapper - Very Tasty!)
[//]: # ([NPC] Magistrix Erona)
[//]: # ([Spell][Mage] Fireball)
[//]: # ([Npc][Drop] Ghostclaw Lynx)
[//]: # ([Web] Armory doesnt work)
[//]: # (To find server revision type `.server info` command in the game chat.)

**Description**: 
The Item Demon Forged Breastplate ( https://tbcdb.com/?item=12628 ) does not scale with Spellpower as it should. 
**Current behaviour**:
No Spellpower is added to the Life-Drain
![WoWScrnShot_051819_102129](https://user-images.githubusercontent.com/50765667/57966841-c2deae80-7957-11e9-80e5-c48dfe7c7579.jpg)

**Expected behaviour**: 
Spellpower scales on this item with 40% (120 lifetrain +0,4*Spellpower)
https://www.wowhead.com/item=12628/demon-forged-breastplate#comments documents this.

**Server Revision**:

**Comment by Manaci** [comment]
Fixed in rev 3202
