### ISSUE TITLE
[Black Temple] - [Hibernate][NPC] Dragon Turtle 

### ISSUE THREAD

**Issue by Gedlund** [Atlantiss/NetherwingBugtracker#5763]
**Description** / **Current behaviour**:
Dragon Turtle(s) inside BT are currently immune to druid's hibernate ability.

**Expected behaviour**: 
Dragon Turtle(s) are supposed to be able to be CC'd with hibernate.

**Server Revision**: 
2954

**Comment by Wolffenstein** [comment]
Fixed
