### ISSUE TITLE
[Black Temple] - [Spell][NPC] [Teron Gorefiend] 

### ISSUE THREAD

**Issue by Gedlund** [Atlantiss/NetherwingBugtracker#5764]
**Description**: 
After Teron Gorefiend cast's his ability Shadow of Death a player dies (as expected) and turns a player into a ghost with four abilities. However Teron himself is not supposed to be able to be hit by any of these abilities. Right now u can use the Ghosts' "Spirit Chains" to hit teron and make him stay in place. 

**Current behaviour**:
Spirit Chains can be used to chain Teron Gorefiend into place.

**Expected behaviour**: 
Spirit Chains is not supposed to affect Teron Gorefiend

**Server Revision**: 
2954

**Comment by Wolffenstein** [comment]
Fixed
