### ISSUE TITLE
[Black Temple] - [Spell][NPC]  - Missing ability

### ISSUE THREAD

**Issue by Gedlund** [Atlantiss/NetherwingBugtracker#5765]
**Description**: 
Missing ability "Disgruntle"
Trash before Supremus. These pull with a pack of Bonechewer Workers. The 
Workers are basic melee AoE mobs, but the Taskmaster puts a Disgruntle buff on them, increasing their size, hp, and damage by 200%. The Taskmaster himself is nothing special

**Current behaviour**:
When a Bonechewer Worker is killed Bonewchewer Taskmaster only gains a 10% damage increase instead of casting the disgruntle ability. 

**Expected behaviour**: 
Bonewchewer Taskmaster buffs a Bonechewer Worker/Worker(s) with the disgruntle ability if a bonechewer worker is killed.

**Server Revision**: 
2954

**Comment by Wolffenstein** [comment]
Fixed
