### ISSUE TITLE
[Quest/Object] The Videre Elixir

### ISSUE THREAD

**Issue by leeviathan** [Atlantiss/NetherwingBugtracker#5766]
**Description**: Quest text:
"Bring me an Evoroot, and sure, I can make ya that Videre Elixir.

I know all kinds of things about herbs and alchemy... Why, let me tell you the story about the time I transmuted gold from the cheese I was going to eat for lunch... hey... Where are you going?"

**Current behaviour**: The wall behind the gnoll is non-clipping, you can walk right through it. 

**Expected behaviour**: You're supposed to buy bait from Gregan Brewspewer, which you then place in front of the gnoll to open the wall behind him (https://classicdb.ch/?quest=4041#comments:id=239986)

Also, apparently the item should be lootable if you aren't even on the quest, currently the evoroot containers are empty (https://www.youtube.com/watch?v=_oI3iefJ3_w) (https://www.wowhead.com/item=11242/evoroot#comments:id=146689)

**Server Revision**: 2952

**Comment by Evolvee** [comment]
works fine for me

**Comment by leeviathan** [comment]
Oops, sorry! Only when you aren't on the quest is the wall non-clipping and the plants not lootable. While _on_ the quest everything works perfectly.

**Comment by Evolvee** [comment]
hmmm

**Comment by Evolvee** [comment]
nope, still cant walk through it even with or without the quest :/ can u record it?
