### ISSUE TITLE
Function reset  instances DONT WORK!

### ISSUE THREAD

**Issue by vitrib79135** [Atlantiss/NetherwingBugtracker#5767]
Every time we need RE-PARTY for reset instances. Admis, mb u repair the function!?

**Comment by Godmatik** [comment]
Works fine for me. You need to use the following macro:

/script ResetInstances();

The capitalization, and the inclusion of the () and ; must be precise for it to work.

**Comment by vitrib79135** [comment]
Nothing happens when use the commant if im partyleader, work only when im without party

**Comment by vitrib79135** [comment]
any solutions for the command? I again write, the command work onle when I'M WITHOUT PARTY

**Comment by vitrib79135** [comment]
> Works fine for me. You need to use the following macro:
> 
> /script ResetInstances();
> 
> The capitalization, and the inclusion of the () and ; must be precise for it to work.

Heyy, please answer me, when repair the command?

**Comment by danbopes** [comment]
Since there are 2k+ other bug reports, I'd say it gets fixed when it gets fixed. We don't give ETA on bug fixes. Since you have a workaround ATM: (Leaving the party/resetting), it's not quite as high priority as other tickets.
