### ISSUE TITLE
[Mage] Winter's chill not debuffing all targets on aoe.

### ISSUE THREAD

**Issue by someaddons** [Atlantiss/NetherwingBugtracker#5768]
[//]: # (Enclose links to things related to the bug using http://wowhead.com or any other TBC database.)
[//]: # (You can use screenshot ingame to visual the issue.)
[//]: # (Write your tickets according to the format:)
[//]: # ([Quest][Azuremyst Isle] Red Snapper - Very Tasty!)
[//]: # ([NPC] Magistrix Erona)
[//]: # ([Spell][Mage] Fireball)
[//]: # ([Npc][Drop] Ghostclaw Lynx)
[//]: # ([Web] Armory doesnt work)
[//]: # (To find server revision type `.server info` command in the game chat.)

**Description**: 
The mage talent "Winter's chill" does not apply its debuff to multiple targets on aoe spells.
To reproduce: take a mage, spec winter's chill and cast cone of cold on multiple targets.
**Current behaviour**:
The mage talent "Winter's chill" does not apply its debuff to multiple targets on aoe spells.
**Expected behaviour**: 
The mage talent "Winter's chill" does apply its debuff to multiple targets on aoe spells. See https://wowwiki.fandom.com/wiki/Winter%27s_Chill?oldid=1295963
**Server Revision**: 
2952

**Comment by liderer** [comment]
Your link ,  Do you even read what is written there? 
"Blizzard is the only frost spell that can not apply the winter's chill affect to the target. It is also the only frost spell that can not benefit from winter's chill, as it can not crit."

**Comment by Wolffenstein** [comment]
Fixed
