### ISSUE TITLE
[Talent][Warlock] Shadow Embrace

### ISSUE THREAD

**Issue by Nugsss** [Atlantiss/NetherwingBugtracker#5769]
[//]: # (Enclose links to things related to the bug using http://wowhead.com or any other TBC database.)
[//]: # (You can use screenshot ingame to visual the issue.)
[//]: # (Write your tickets according to the format:)
[//]: # ([Quest][Azuremyst Isle] Red Snapper - Very Tasty!)
[//]: # ([NPC] Magistrix Erona)
[//]: # ([Spell][Mage] Fireball)
[//]: # ([Npc][Drop] Ghostclaw Lynx)
[//]: # ([Web] Armory doesnt work)
[//]: # (To find server revision type `.server info` command in the game chat.)

**Description**: 
I was in combat with a Warlock, and I got a debuff on me permanently that should only be temporary.

The debuff as it appears on my character:
https://imgur.com/a/A2lbHp5

As you can see, I am not in combat and I do not have any warlock DoT effects on me, however the debuff is still there.

The talent in the Warlock Affliction tree:
https://imgur.com/a/jfuqcaB

**Current behaviour**:
An ability (not sure which) was applied to me which inflicted "Shadow Embrace" which persisted after the spell expired.

**Expected behaviour**: 
The damage reduction should only last for the duration of Corruption, Curse of Agony, Siphon Life, and Seed of Corruption.

**Server Revision**: 
2952 [Branch: master, Hash: be4cfc3a7f71]

**Comment by Zarant** [comment]
That usually happens whenever the caster is in another zone/continent when the dot debuff that applied shadow embrace runs out. 
Might be related to issue #5769

**Comment by Godmatik** [comment]
Unable to reproduce.

When a DOT is on me and I change zones or continents, the Shadow Embrace is removed.
