### ISSUE TITLE
Owlkin double spawn on Azuremyst Isle

### ISSUE THREAD

**Issue by Notmittz** [Atlantiss/NetherwingBugtracker#577]
Owlkin doublespawning

**Description**: 
Mutated Owlkin and Nestlewood owlkin are double spawning under tree in specific area (coordinate of 80, 60)

https://imgur.com/a/6FdlY06

**Current behaviour**:
They are spawning in the exact same location

**Expected behaviour**: 
Either a Nestlewood Owlkin or a Mutated Owlkin should spawn in a given location, not both

**Server Revision**:

**Comment by aresbrutus** [comment]
Thanks for the report. Could you please next time use .npc info while you have the mob selected and then making a screenshot? That way I get all the necessary information and where to find the mob. 

This issue will be fixed in one of the upcoming updates.
