### ISSUE TITLE
[Quest] The Legend of Stalvin Quest Spawns Mob in Goldshire

### ISSUE THREAD

**Issue by billykitty** [Atlantiss/NetherwingBugtracker#5770]
**Description**: 
During this quest, twice a Forlorn Spirit will spawn and attack the player. 

It should ONLY spawn when you accept the following quests:
    - Alliance [28] The Legend of Stalvan (part 3)
    - Alliance [28] The Legend of Stalvan (part 7)

See https://wowwiki.fandom.com/wiki/Forlorn_Spirit for details and links.   

The issue is this mob is spawning in Goldshire when the chest upstairs is looted during part 5.

**QUEST:** The Legend of Stalvan (part 5)

**LINK:** https://wowwiki.fandom.com/wiki/Quest:The_Legend_of_Stalvan_(5)

**Current behavior**: When a player retrieves Stalvan's Undelivered Letter from the chest upstairs at the Lion's Pride Inn, a Forlorn Spirit spawns and kills unflagged players downstairs.  Players suffer 10% durability loss too.

**Expected behavior**: The Forlorn Spirit should not spawn during part 5. Only in Moonbrook and the SW Canals.

**Server Revision**: TBC 2.4.3 (8606)

**Comment by Evolvee** [comment]
rev 2971
