### ISSUE TITLE
[Talent][Mage] Permafrost

### ISSUE THREAD

**Issue by Xyan1337** [Atlantiss/NetherwingBugtracker#5771]
**Description**: 
Permafrost slow% probably not working correctly
**Current behaviour**:
If you specc into Permafrost, it shows the slow% in the tooltip from spells. i.e Frostbolt 50% slow, but it doesn't show on the debuff it only shows 40% slow. Might just not show correctly while the slow still goes up.
**Expected behaviour**: 
Increases your slows by 4/7/10% 
**Server Revision**: 2955

**Comment by Wolffenstein** [comment]
It's working correctly. The tooltips often don't include such effects.
