### ISSUE TITLE
[Black Temple] [Spell] [NPC] - Aqueous Spawn - Merge

### ISSUE THREAD

**Issue by Drayo** [Atlantiss/NetherwingBugtracker#5772]
[//]: # (Enclose links to things related to the bug using http://wowhead.com or any other TBC database.)
[//]: # (You can use screenshot ingame to visual the issue.)
[//]: # (Write your tickets according to the format:)
[//]: # ([Quest][Azuremyst Isle] Red Snapper - Very Tasty!)
[//]: # ([NPC] Magistrix Erona)
[//]: # ([Spell][Mage] Fireball)
[//]: # ([Npc][Drop] Ghostclaw Lynx)
[//]: # ([Web] Armory doesnt work)
[//]: # (To find server revision type `.server info` command in the game chat.)

**Description**:  The big pack of these after the first Boss all cast [Merge] at the same time, roughly 10 seconds after pull. They have no target, do nothing but channel it and go back to normal after it's over.

**Current behaviour**: Aqueous Spawn casts [Merge] even though there is no big elemental Mob that would benefit from it.

**Expected behaviour**: Aqueous Spawn should not cast [Merge] when there is no target present.

**Server Revision**: PTR

**Comment by Wolffenstein** [comment]
Fixed
