### ISSUE TITLE
[Black Temple] [NPC] Aqueous Spawn - Linking

### ISSUE THREAD

**Issue by Drayo** [Atlantiss/NetherwingBugtracker#5773]
[//]: # (Enclose links to things related to the bug using http://wowhead.com or any other TBC database.)
[//]: # (You can use screenshot ingame to visual the issue.)
[//]: # (Write your tickets according to the format:)
[//]: # ([Quest][Azuremyst Isle] Red Snapper - Very Tasty!)
[//]: # ([NPC] Magistrix Erona)
[//]: # ([Spell][Mage] Fireball)
[//]: # ([Npc][Drop] Ghostclaw Lynx)
[//]: # ([Web] Armory doesnt work)
[//]: # (To find server revision type `.server info` command in the game chat.)

**Current behaviour**: The big pack of Aqueous Spawn after the first Boss is not linked, the mobs can be pulled in increments of 2-3.

**Expected behaviour**: All Aqueous Spawn after the first boss, excluding the Patrol, should be linked and should pull as one big group.

**Server Revision**: PTR

**Comment by Wolffenstein** [comment]
Fixed
