### ISSUE TITLE
[Black Temple] [NPC] [Spell] Ashtongue Mystic - Windfury Totem

### ISSUE THREAD

**Issue by Drayo** [Atlantiss/NetherwingBugtracker#5775]
[//]: # (Enclose links to things related to the bug using http://wowhead.com or any other TBC database.)
[//]: # (You can use screenshot ingame to visual the issue.)
[//]: # (Write your tickets according to the format:)
[//]: # ([Quest][Azuremyst Isle] Red Snapper - Very Tasty!)
[//]: # ([NPC] Magistrix Erona)
[//]: # ([Spell][Mage] Fireball)
[//]: # ([Npc][Drop] Ghostclaw Lynx)
[//]: # ([Web] Armory doesnt work)
[//]: # (To find server revision type `.server info` command in the game chat.)

**Current behaviour**: The Totem buff does not ever wear off after it gets destroyed. The Totem grants 2 Buffs, a green one and a normal Windfury Icon. 
Every time the Ashtongue Mystic puts down a new Totem, all affected mobs gain an additional instance of the green buff, this stacks indefinitely, but does not seems to have any effect.

**Expected behaviour**: When the Totem gets destroyed the affected mobs should lose the Windfury buff at some point. The green debuff should probably not be visible and should not have multiple instances.

**Server Revision**: PTR

**Comment by Godmatik** [comment]
Fixed last year when BT was released on Netherwing
