### ISSUE TITLE
[Black Temple] [NPC] [Boss] Shade of Akama - Mob Waves Aggro

### ISSUE THREAD

**Issue by Drayo** [Atlantiss/NetherwingBugtracker#5776]
[//]: # (Enclose links to things related to the bug using http://wowhead.com or any other TBC database.)
[//]: # (You can use screenshot ingame to visual the issue.)
[//]: # (Write your tickets according to the format:)
[//]: # ([Quest][Azuremyst Isle] Red Snapper - Very Tasty!)
[//]: # ([NPC] Magistrix Erona)
[//]: # ([Spell][Mage] Fireball)
[//]: # ([Npc][Drop] Ghostclaw Lynx)
[//]: # ([Web] Armory doesnt work)
[//]: # (To find server revision type `.server info` command in the game chat.)

**Current behaviour**: The mobs that spawn the two sides during the encounter do not aggro if players stand too far away.

**Expected behaviour**: They need to aggro regardless of the players positioning.

**Server Revision**: PTR

**Comment by Wolffenstein** [comment]
Screenshot please?

**Comment by Drayo** [comment]
![WoWScrnShot_052219_184201](https://user-images.githubusercontent.com/23145811/58192755-d7a5a400-7cc1-11e9-8bf8-1c12cbd3820c.jpg)

**Comment by Drayo** [comment]
I'm pretty sure this one was already reported while we were raid testing it.

**Comment by Wolffenstein** [comment]
Should be fixed
