### ISSUE TITLE
[Black Temple] [NPC] [Boss] Supremus

### ISSUE THREAD

**Issue by Drayo** [Atlantiss/NetherwingBugtracker#5777]
[//]: # (Enclose links to things related to the bug using http://wowhead.com or any other TBC database.)
[//]: # (You can use screenshot ingame to visual the issue.)
[//]: # (Write your tickets according to the format:)
[//]: # ([Quest][Azuremyst Isle] Red Snapper - Very Tasty!)
[//]: # ([NPC] Magistrix Erona)
[//]: # ([Spell][Mage] Fireball)
[//]: # ([Npc][Drop] Ghostclaw Lynx)
[//]: # ([Web] Armory doesnt work)
[//]: # (To find server revision type `.server info` command in the game chat.)

**Current behaviour**: Supremus is mssing the ability to instantly Teleport players to him in case he is unable to reach them.

**Expected behaviour**: He should teleport players that are safespotting.

**Server Revision**: PTR

**Comment by Wolffenstein** [comment]
Source? First time I'm hearing about this.

**Comment by Drayo** [comment]
https://wowwiki.fandom.com/wiki/Supremus

> It is also possible for him to immediately teleport anyone outside of his ability to reach to his feet, which can be very nasty.

**Comment by Wolffenstein** [comment]
What range would you propose for the check?

**Comment by Drayo** [comment]
Hm, it only seems to happen when he can't find a path. Not sure if it has anything to do with the distance.

**Comment by Wolffenstein** [comment]
Eh, movemaps on NW are a bit more lenient than on retail there. I'm not gonna add it for now.
