### ISSUE TITLE
[Black Temple] [NPC] [Mechanic] Dragonmaw Wyrmcaller - Call for Help

### ISSUE THREAD

**Issue by Drayo** [Atlantiss/NetherwingBugtracker#5778]
[//]: # (Enclose links to things related to the bug using http://wowhead.com or any other TBC database.)
[//]: # (You can use screenshot ingame to visual the issue.)
[//]: # (Write your tickets according to the format:)
[//]: # ([Quest][Azuremyst Isle] Red Snapper - Very Tasty!)
[//]: # ([NPC] Magistrix Erona)
[//]: # ([Spell][Mage] Fireball)
[//]: # ([Npc][Drop] Ghostclaw Lynx)
[//]: # ([Web] Armory doesnt work)
[//]: # (To find server revision type `.server info` command in the game chat.)

**Description**:  Their call for help does not seem to be functioning correctly.

**Current behaviour**: When they call for help (which they do periodically) other Dragonmaw Wyrmcallers from far away seem to add.

**Expected behaviour**: 

> Dragonmaw Wyrmcallers can be found in Black Temple. They can call for help from the surrounding **dragon riders**. 

It sounds like when they call for help, not Dragonmaw Wyrmcallers, but the flying **dragon rider** packs should add, IF they are in range, 

This would also explain the massive range of the call.

**Server Revision**: PTR

**Comment by Wolffenstein** [comment]
They cast 40888 - Force Assist on the target, which in turn makes the target cast:

ID - 40887 Assist
=================================================
Description: Causes the caster to taunt a nearby Dragonmaw Drake-Handler onto him.

Which has a 100yd radius and only targets Wyrmcallers:

`ServerToClient: SMSG_SPELL_GO (0x2C39) Length: 146 ConnIdx: 0 Time: 05/21/2018 17:12:01.862 Number: 41797
(Cast) CasterGUID: Full: 0x0810F4000000000000000000086C05C1 Player/0 R1085/S0 Map: 0 (Eastern Kingdoms) Low: 141297089
(Cast) CasterUnit: Full: 0x0810F4000000000000000000086C05C1 Player/0 R1085/S0 Map: 0 (Eastern Kingdoms) Low: 141297089
(Cast) CastID: Full: 0xBC3ADC468027EDC3001653000302E1A1 Cast/3 R3767/S5715 Map: 564 (Black Temple) Low: 50520481
(Cast) OriginalCastID: Full: 0x0
(Cast) SpellID: Assist (40887)
(Cast) SpellXSpellVisualID: 0
(Cast) CastFlags: 16653
(Cast) CastTime: 2202099532
(Cast) (MissileTrajectory) TravelTime: 0
(Cast) (MissileTrajectory) Pitch: 0
(Cast) Ammo.DisplayID: 0
(Cast) DestLocSpellCastIndex: 0
(Cast) (Immunities) School: 0
(Cast) (Immunities) Value: 0
(Cast) (Predict) Points: 0
(Cast) (Predict) Type: 0
(Cast) (Predict) BeaconGUID: Full: 0x0
(Cast) CastFlagsEx: 16400
(Cast) HitTargetsCount: 2
(Cast) MissTargetsCount: 0
(Cast) MissStatusCount: 0
(Cast) RemainingPowerCount: 0
(Cast) HasRuneData: False
(Cast) TargetPointsCount: 0
(Cast) (Target) Flags: Unit, SourceLocation (34)
(Cast) (Target) HasSrcLocation: True
(Cast) (Target) HasDstLocation: False
(Cast) (Target) HasOrientation: False
(Cast) (Target) hasMapID : False
(Cast) (Target) Unit: Full: 0x0
(Cast) (Target) Item: Full: 0x0
(SrcLocation) Transport: Full: 0x0
(SrcLocation) Location: X: 730.0426 Y: 925.3826 Z: 53.05273
(Cast) (Target) Name: 
(Cast) [0] HitTarget: Full: 0x203ADC4680166C00001653000102E0BB Creature/0 R3767/S5715 Map: 564 (Black Temple) Entry: 22960 (Dragonmaw Wyrmcaller) Low: 16965819
(Cast) [1] HitTarget: Full: 0x203ADC4680166C00001653000082E0BB Creature/0 R3767/S5715 Map: 564 (Black Temple) Entry: 22960 (Dragonmaw Wyrmcaller) Low: 8577211`

Haven't seen it target anyone else in my sniffs and the creatures it targetted were quite far away.

**Comment by Drayo** [comment]
I'm checking it on retail (but it's annoying because they die so easily) and it seems like they only cast it when they get to around 40%.

Then another Dragonmaw Wyrmcaller uses a different emote and fixates on me. They are currently not using it on NW, or at least they do not get the enrage like buff.

![help](https://user-images.githubusercontent.com/23145811/58193150-ada0b180-7cc2-11e9-836a-6e451c0f0b81.png)

Here you can see the response Emote, they always happen in Pairs as long as I'm fighting at least two of them.

**Comment by Drayo** [comment]
I might be mistaken and they are independent things, but if I just stand there for 5 minutes they do nothing, as soon as one of them drops low, both things happen at once.

I can make some clips of it though, but I need to find a way to bring them down in a more controlled way.

**Comment by Wolffenstein** [comment]
Reworked.
