### ISSUE TITLE
[NPC] Rare mobs loot-table

### ISSUE THREAD

**Issue by Kidcudi123** [Atlantiss/NetherwingBugtracker#578]
All rare mobs are missing loot-tables? At least the ones I stumbled upon in Tirisfal Glades

(This was day 1/2 of beta)

**Comment by aresbrutus** [comment]
We have done the research but not ALL rares are bound to have a uncommon+ item. But the rare loot system is also at the moment getting overhauled so drops from rares currently do not reflect the same as during launch.

**Comment by tcberk12** [comment]
<img width="1439" alt="screen shot 2018-09-24 at 11 57 14 pm" src="https://user-images.githubusercontent.com/43530009/46099910-f9737900-c17c-11e8-9685-30eac6c5dfd1.png">
<img width="1440" alt="screen shot 2018-09-24 at 11 36 51 pm" src="https://user-images.githubusercontent.com/43530009/46099931-02644a80-c17d-11e8-98c6-58b037f962a1.png">

Attaching some SS's of the rare's I killed that had no loot (not even common gear) in case it is helpful. For the second SS, you can see I only looted copper in the chat log.

**Comment by Easyfraggy** [comment]
Rare loot is being reworked, no need for more data right now, thanks! =)

**Comment by Mentat33** [comment]
Not sure if Rare loot has been reworked yet, but Putridius has no loot either

![putridius no loot](https://user-images.githubusercontent.com/43624877/50190880-007fd280-02f9-11e9-85fe-d31afd2b1096.png)

**Comment by Mentat33** [comment]
![foulmane](https://user-images.githubusercontent.com/43624877/50190937-49d02200-02f9-11e9-94bc-f58a346a51e4.png)
Foulmane too

**Comment by Shanghi** [comment]
Not yet, but a core thing was added a few days ago that makes it possible to fix them properly so they should be fixed soon. Right now rares only have unique items (if they have any) set.
