### ISSUE TITLE
[2.1 PTR] Drinks such as Rumsey R um should not stack with Food Buffs anymore

### ISSUE THREAD

**Issue by Kolmarwow** [Atlantiss/NetherwingBugtracker#5780]
**Description**: 
In patch 2.1 all kinds of drinks that gave you +Stamina stopped stacking with the "Well Fed" buff that's gotten from food items. 
" [Rumsey Rum],  [Rumsey Rum Light],  [Rumsey Rum Dark],  [Rumsey Rum Black Label],  [Halaani Whiskey],  [Gordok Green Grog],  [Raptor Punch],  [Stormstout],  [Trogg Ale], and  [Keg of Thunderbrew Lager]: The stat bonuses from these drinks no longer stacks with stamina bonuses from other foods." from https://wow.gamepedia.com/Patch_2.1.0

The patch note specifically says "stamina bonuses from other foods." which might imply that non-stamina food should still stack with Rumsey Rum, but according to a Wowhead comment drinks just flat out do not stack with any kind of well fed buff at all. 
"In my experience the +stam buff on this drink does not stack with food buffs *at all*, not just +stam food buffs. As a Warlock, when I eat Blackened Basilisk (+23 spell damage, +20 spirit), then drink this, it removes my Well Fed buff. Vice versa, if I drink this, then eat Blackened Basilisk, it removes my Rum (+stam) buff." https://www.wowhead.com/item=21151/rumsey-rum-black-label#comments

**Current behaviour**:
Drinks such as Rumsey Rum currently stack with the Well Fed food buff

**Expected behaviour**: 
They should not stack anymore with Patch 2.1

**Server Revision**: 
2955 (PTR)

**Comment by Kolmarwow** [comment]
Noticed the server revision is out of date, will close this and re-open if Rumsey Rum still stacks after the big 2956 update

**Comment by Kolmarwow** [comment]
Re-opening this since it seems to have not been changed yet on the PTR. Don't know why this was marked as invalid since this is documented to be blizzlike, further proof here from 2008: https://wow.gamepedia.com/index.php?title=Rumsey_Rum_Black_Label&oldid=1446727
"The stamina buff granted by this beverage does not stack with any other food buffs."

**Comment by dshgrove** [comment]
I don't appreciate it when beneficial bugs like these are being kept in the game on purpose.
You should consider giving players abusing this a warning @Wolffenstein .

**Comment by Godmatik** [comment]
Was fixed on Netherwing server
