### ISSUE TITLE
[Dungeon][SSC] Leotheras running to melee range at 2nd phase

### ISSUE THREAD

**Issue by veekk** [Atlantiss/NetherwingBugtracker#5783]
**Description**:  Leotheras running to melee range at 2nd phase

**Current behaviour**: Leotheras running to melee range at 2nd phase, when wlock tanking. Happens when pulling on stairs, but after passing stairs still running to melee even on flat surface

**Expected behaviour**:  Shouldn't run into melee

**Server Revision**: 2955

**Comment by gabbat** [comment]
actually a bigger problem than it might sound at first, as melee dps can no longer dps the boss in demon form as they would get the aoe spread dmg from the fireball to the warlock.
also confirming this bug, keeps happening for weeks now

**Comment by veekk** [comment]
ye, that's main problem, huge dps loss 'cause of that

**Comment by Zadiel** [comment]
Can confirm this is still happening. He will cast a Chaos Blast at our Warlock tank, step forward ~5-8 yards, then cast another Chaos Blast. Once he gets into melee range he also starts swinging at the Warlock tank.

**Comment by Wolffenstein** [comment]
Fixed in rev 3104.

**Comment by dshgrove** [comment]
https://clips.twitch.tv/PhilanthropicPluckyCobblerFeelsBadMan
https://clips.twitch.tv/UnsightlyCooperativeDeerWholeWheat
https://clips.twitch.tv/HorribleDistinctJam4Head

Clips of this happening on Karazhan the 7th of september (did not note down the server revision, sorry.)

**Comment by Godmatik** [comment]
Confirmed, happens when the warlock tank moves.

He doesn't melee but whenever the warlock moves, so does Leo, even though the warlock is not getting out of range of his fireballs.

**Comment by Wolffenstein** [comment]
Fixed in rev 3533.
