### ISSUE TITLE
([NPC] all summoners) Invoked creatures do not disappear after the death of their master

### ISSUE THREAD

**Issue by Lorydon** [Atlantiss/NetherwingBugtracker#5785]
[//]: # (Enclose links to things related to the bug using http://wowhead.com or any other TBC database.)
[//]: # (You can use screenshot ingame to visual the issue.)
[//]: # (Write your tickets according to the format:)
[//]: # ([Quest][Azuremyst Isle] Red Snapper - Very Tasty!)
[//]: # ([NPC] Magistrix Erona)
[//]: # ([Spell][Mage] Fireball)
[//]: # ([Npc][Drop] Ghostclaw Lynx)
[//]: # ([Web] Armory doesnt work)
[//]: # (To find server revision type `.server info` command in the game chat.)

**Description**: 

when the NPC invokes any creature, then after his death the invoked creature does not disappear as it worked on the Blizzard servers even during the Classic WoW period.

**Current behaviour**:

 Invoked creatures do not disappear after the death of their master

**Expected behaviour**: 

I hope that the invoked creatures will disappear after the death of their master.

**Server Revision**: 

This worked in Classic and other updates of wow on the Blizzard servers.

**Comment by Evolvee** [comment]
it shouldnt automatically disappear if still in combat

you have wrong information
