### ISSUE TITLE
[Item][PTR] s2 PvP offset rings different honor prices

### ISSUE THREAD

**Issue by SlizeTBC** [Atlantiss/NetherwingBugtracker#5786]
PTR Server:

s2 offset rings are with different honor prices on different vendors in the Champions Hall.

https://i.imgur.com/aWVqoLn.png

https://i.imgur.com/yOGo7jH.png

ITEM ID'S:

http://us.battle.net/wow/en/item/33057
http://us.battle.net/wow/en/item/33056
http://us.battle.net/wow/en/item/33064

**Comment by bajkorv** [comment]
NPC ID: 12793 ”Brave Stonehide” in Hall of Legends also has this s2 rings for 9,5k honor, which is wrong.
Aswell as S1 necks and rings on this vendor has wrong pricing they cost same as s2 ones currently.
Also the S2 cloaks are same price as S1 cloaks - should be 11k something for s2 cloaks

**Comment by bajkorv** [comment]
Also wierd how for S1 2 hands and 1 hands cost same price.. aswell as weapons and set pieces all have the same price (any piece or weapon 40k honor no other req)

**Comment by Evolvee** [comment]
resolved
