### ISSUE TITLE
[Quest][Skettis] Fires Over Skettis Blasting Charges Range

### ISSUE THREAD

**Issue by Ceago** [Atlantiss/NetherwingBugtracker#5788]
**Description**:  Skyguard Blasting Charges can be used at any range to destroy eggs.

**Current behaviour**:  Can be used far outside of their max range and gives credit.  Video:  https://streamable.com/o3wzc

**Expected behaviour**:   Should only be useable when in range.

**Server Revision**: 2967

**Comment by Evolvee** [comment]
![image](https://user-images.githubusercontent.com/1942409/58517025-41ceb500-81aa-11e9-86ea-bf77ad1f612f.png)
mein got im himmel

everything is in fucking cpp

**Comment by Evolvee** [comment]
spell 39844 needs core fix, i dont think its a good idea to add a range condition here (peformance heavy)

**Comment by Wolffenstein** [comment]
Fixed
