### ISSUE TITLE
[NPC] Monstrous Kaliri - Does Not Dismount Players and When Leashes No Longer Patrols

### ISSUE THREAD

**Issue by Ceago** [Atlantiss/NetherwingBugtracker#5789]
**Description**: Does not dismount players and when outranged and leashed they do not resume patrolling.

**Current behaviour**:  Players are "Immune" to swoop and the NPC does not resume patrolling after leashing.  Video:  https://streamable.com/w4efd

**Expected behaviour**:   Should be dismounted by swoop and possibly knocked away and NPC should patrol normally after leashing.

**Server Revision**:  2967

**Comment by Manaci** [comment]
They still stop patrolling quite fast and just stand still in flying in midair

**Comment by Evolvee** [comment]
https://github.com/Atlantiss/NetherwingBugtracker/issues/5927

**Comment by Tereneckla** [comment]
does dismount, leaving other up
