### ISSUE TITLE
Draenei Level 10 Hunter Quest Not Working Properly

### ISSUE THREAD

**Issue by Silverdoa** [Atlantiss/NetherwingBugtracker#579]
Quest: Taming the Beast (Draenei 1))
NPC:    Huntress Kella Nightbow)

**Description**: 

Using the totem item (tame beast) on all 3 creatures during this chain quest leads all creatures to freeze in place.  In addition, you are not capable of dismissing these animals at all after you complete each quest, as one would expect.  Thus, this creates a new problem, whereby after taming said creature, your character now remains in permanent combat status, disallowing you from logging out or exiting the game.  One must then force-close the game and reopen to continue each quest or finish the chain entirely. 

**Expected behaviour**: 

Though I have never played hunter prior, one would expect each creature of each chain quest to follow your character back to the quest giver.  

**Server Revision**:

**Comment by Fenvarien1** [comment]
#push

**Comment by pelekon** [comment]
fixed in 2372
