### ISSUE TITLE
[Spell][Shaman][Stoneclaw totem][Stealth][Stoneclaw totem's pulses don't break stealth on nearby hostile units] 

### ISSUE THREAD

**Issue by whissper** [Atlantiss/NetherwingBugtracker#5791]
**Description**: 
Stoneclaw totem's pulses don't break stealth on nearby hostile units.

**Current behaviour**:
Stoneclaw totem's pulses don't break stealth on nearby hostile units.

**Expected behaviour**: 
Stoneclaw totem's pulses should break stealth on nearby hostile units. PvP/PvE

**changelog patch notes for WotLK v 3.2.2**:
https://imgur.com/Rfz2fOs
**Also**:
https://github.com/FeenixServerProject/Archangel_2.4.3_Bugtracker/issues/1868

**Server Revision**: 
2967

**Comment by whissper** [comment]
Are there any news? This issue affects pvp game play significantly for shaman class.

**Comment by Wolffenstein** [comment]
Fixed in rev 3198.
