### ISSUE TITLE
Tame issue

### ISSUE THREAD

**Issue by Hiukiji** [Atlantiss/NetherwingBugtracker#5792]
After abandoning a pet I am unable to tame another one until I relog since I am told I already have a creature summoned.

**Comment by Zarant** [comment]
Tested this at server revision 3430.
Very easy to reproduce, tame a pet abandon it and try to tame another pet. You won't be able to tame a new pet until you log out.

**Comment by Godmatik** [comment]
Confirmed - it is duplicate, so will close this one
