### ISSUE TITLE
[Item] Fist of Stone doesn't do damage when proc

### ISSUE THREAD

**Issue by microsoftsucksbad** [Atlantiss/NetherwingBugtracker#5793]
[//]: # (Enclose links to things related to the bug using http://wowhead.com or any other TBC database.)
[//]: # (You can use screenshot ingame to visual the issue.)
[//]: # (Write your tickets according to the format:)
[//]: # ([Quest][Azuremyst Isle] Red Snapper - Very Tasty!)
[//]: # ([NPC] Magistrix Erona)
[//]: # ([Spell][Mage] Fireball)
[//]: # ([Npc][Drop] Ghostclaw Lynx)
[//]: # ([Web] Armory doesnt work)
[//]: # (To find server revision type `.server info` command in the game chat.)

**Description**: 
Fist of Stone (https://tbc-twinhead.twinstar.cz/?item=17943) doesn't do damage when proc, just 50 mana restoration and no damage
**Current behaviour**:
Fist of Stone doesn't do damage when proc
**Expected behaviour**: 
Fist of Stone should do damage when proc
**Server Revision**:

**Comment by Evolvee** [comment]
![image](https://user-images.githubusercontent.com/1942409/58516342-ef8c9480-81a7-11e9-8ac1-0a97286f69c1.png)

it does damage?

if you cant see the dmg on your screen, it will happen (double) at the next swing, its a client bug
