### ISSUE TITLE
[Item] Pendant of Triumph and Dominance not discounted with Season 2

### ISSUE THREAD

**Issue by Manaci** [Atlantiss/NetherwingBugtracker#5794]
**Description**: 
These two Season 1 necklaces are missing their discount.
**Current behaviour**:
 Right now the Season 2 necklaces are cheaper than the Season 1 necklaces, who still cost 22500 honor + marks.
**Expected behaviour**: 
They should cost the same (this seems weird since the S1 ring is discounted compared to the S2 ring but it's only blue quality though). 
**Proof**:
[S1 Triumph](https://web.archive.org/web/20071102031147/http://wow.allakhazam.com/db/item.html?witem=28244) vs [S2 Triumph](https://web.archive.org/web/20071017204410/http://wow.allakhazam.com/db/item.html?witem=33066)
[S1 Dominance](https://web.archive.org/web/20071102031153/http://wow.allakhazam.com/db/item.html?witem=28245) vs [S2 Dominance](https://web.archive.org/web/20071018132030/http://wow.allakhazam.com/db/item.html?witem=33065)
Don't think it would hurt to set the S1 necklace price to the same as the S1 ring aka 11934 honor + the specific mark (10 EotS for necklaces). Because there is absolutely no reason to buy the S1 necklace or the S2 one even when the first discount is placed.

**Server Revision**: 
2967

**Comment by Evolvee** [comment]
the s2 price is correct

the s1 price should be 18k

so yea, either way s1 is more expensive than s2 .... blizzard logic

fixed
