### ISSUE TITLE
[Quest][Ghostlands] Investigate the Amani Catacombs

### ISSUE THREAD

**Issue by danbopes** [Atlantiss/NetherwingBugtracker#5795]
**Description**: 
Quest [Investigate the Amani Catacombs](https://www.wowhead.com/quest=9193/investigate-the-amani-catacombs). Heading to the catacombs, at X: 62.75 Y: 31.83 should trigger quest completion for the "Investigate the Amani Catacombs" portion of the quest.

**Current behaviour**:
Quest is not triggered properly (Even after killing all 10 mobs first):
![](https://i.imgur.com/QKFMCXe.png)
![](https://i.imgur.com/k1a8oLf.png)

**Expected behaviour**: 
Heading to X: 62.75 Y: 31.83 (Or anywhere in the vicinity) should trigger the objective completion.

**Server Revision**: 
2967

**Comment by Evolvee** [comment]
works fine for me

**Comment by Evolvee** [comment]
![Uploading image.png…]()
