### ISSUE TITLE
[Raid] [Boss] [Karazhan] Moroes Threat

### ISSUE THREAD

**Issue by Consita** [Atlantiss/NetherwingBugtracker#5797]
[//]: # (Enclose links to things related to the bug using http://wowhead.com or any other TBC database.)
[//]: # (You can use screenshot ingame to visual the issue.)
[//]: # (Write your tickets according to the format:)
[//]: # ([Quest][Azuremyst Isle] Red Snapper - Very Tasty!)
[//]: # ([NPC] Magistrix Erona)
[//]: # ([Spell][Mage] Fireball)
[//]: # ([Npc][Drop] Ghostclaw Lynx)
[//]: # ([Web] Armory doesnt work)
[//]: # (To find server revision type `.server info` command in the game chat.)

**Description**: 
After the Main Tank gets stunned by Moroes or one of the Adds Moroes completly ignores the Threat table and goes for a random Target in the Raid. Seems that DPS are still higher prefered by the boss.
**Current behaviour**:
Moroes ignores the threat table whenever the Main Tank gets stunned and goes for a random player in the raid (DPS higher on prio)
**Expected behaviour**: 
Moroes should always go for the Player that is second in Threat if the Main Tank gets stunned. After Main Tank gets out of stun Moroes should go back to the Main Tank unless someone was higher than 100% in terms of Threat.
**Server Revision**: 
2967

**Comment by SlizeTBC** [comment]
Can confirm, he is bugged!

**Comment by gabbat** [comment]
can not confirm, moroes always aggroes the 2nd on his aggro table as soon as he gouges (not stuns, thats a major difference) his current target. 
the issue you are facing is likely your dps not showing on omen and actually beeing over the 2nd tank in threat. 
this could have several causes: dps not having omen installed at all. dps using bufflib addons which conflict with omen, hence making them invisible to others on omen.

**Comment by Consita** [comment]
They all show up and it only appeared after the recent Season 2 Patch.
We all had Omen and no DPS was even close to our second Tank..

**Comment by Firroth** [comment]
Omen isn't trustworthy addon like every other threat meter too anyway. They tend to show not accurate aggro most of the time. On disorient(gouge) effect he should go for 2nd in aggro list, on stun though he should still be on his main target (stun isn't removed on hit after all unlike other effects) so it makes it easier to kill his target. If he switches target on stun it's bugged.

**Comment by Wolffenstein** [comment]
Threat measuring addons aren't accurate - until wotlk they only make a prediction based on combat log events and don't accurately display actual threat list that's stored server-side. Gouge (and similar effects) cause npcs to always go for the second target, never random.

**Comment by Consita** [comment]
Yeah, thats why I reported it. Cause it was random and not the second Threat target. A feral druid (T4/T5 Gear) that cannot outthreat a Boomkin with blue gear (Tranq and Salvation) is not possible.

**Comment by gabbat** [comment]
after trying moroes tonight and having an eye on it, moroes threat is actually not behaving normaly. the behavior described in this threat is coming pretty close to what we observed today. (gouge maintank, not going to 2nd tank who is BY FAR ahead of #3, only going to tank#2 and therefor aggro #2 after he killed someone randomly, not going back to aggro #1 even after gouge has wearn off and the tank has done abilities on moroes, while still being far ahead)
