### ISSUE TITLE
[core] Invisibility problem - Quest totem of vark

### ISSUE THREAD

**Issue by Evolvee** [Atlantiss/NetherwingBugtracker#5799]
@Wolffenstein During the event after you reward quest 9541 and accept the new one (as a shaman class), the NPC casts invis cat  buff on you...

problem is that once he does that, u lose the sight of that NPC so u cant see him unless u remove that buff... this is bad and isnt working as it was half year ago... so you changed something regarding invis in the core

fix pls

**Comment by Evolvee** [comment]
quest is handled in NPC 17393

![image](https://user-images.githubusercontent.com/1942409/58564689-b1d24f00-822d-11e9-98bd-e271bf33d72f.png)

**Comment by Wolffenstein** [comment]
Fixed in rev 3095.
