### ISSUE TITLE
[NPC] Hillsbrad Apprentice Blacksmith (2265)

### ISSUE THREAD

**Issue by Kentamentiu** [Atlantiss/NetherwingBugtracker#580]
[//]: # (Enclose links to things related to the bug using http://wowhead.com or any other TBC database.)
[//]: # (You can use screenshot ingame to visual the issue.)
[//]: # (Write your tickets according to the format:)
[//]: # ([Quest][Azuremyst Isle] Red Snapper - Very Tasty!)
[//]: # ([NPC] Magistrix Erona)
[//]: # ([Spell][Mage] Fireball)
[//]: # ([Npc][Drop] Ghostclaw Lynx)
[//]: # ([Web] Armory doesnt work)

**Description**: 
Hillsbrad Apprentice Blacksmith is an npc that sells low quality weapons to alliance. When horde kills them, they drop these items.

**Current behaviour**:
They do not drop the weapons they sell.

**Expected behaviour**: 
They drop the items at a high rate.

**Server Revision**: 
2050

**Comment by aresbrutus** [comment]
https://i.imgur.com/b5cU1gu.png
https://i.imgur.com/XgbQvAi.png

Seems to be not the case. Post with proof here so I can re-open.

**Comment by Kentamentiu** [comment]
Comments I found seem to all be from 3.0.1 and beyond. I will research further, but it's likely this was a WoTLK change.
