### ISSUE TITLE
Crabs (& other creatures?) make shallow water stepping sounds underwater

### ISSUE THREAD

**Issue by randomuser69** [Atlantiss/NetherwingBugtracker#5800]
**Description**: 
it appears that creatures make the shallow water stepping sound when fully underwater. Example, crabs on bloodmust isle will make the splashy shallow water sound even when they are fully underwater (coord 63.1, 67.9)
**Current behaviour**:
Shallow water stepping sounds for crabs on bloodmyst isle when fully submerged underwater

**Expected behaviour**: 
No sound for crabs when stepping underwater

**Server Revision**:

**Comment by Evolvee** [comment]
proof? 🤣

**Comment by Evolvee** [comment]
client side

**Comment by randomuser69** [comment]
@Evolvee 

Heres a video I shot showing what im talking about with the walking sound underwater https://www.youtube.com/watch?v=9onT3o8ubko&feature=youtu.be

_**I am using the NW client.**_ 

I also tried this on a fresh copy (freshly unzipped) and it was the same issue (i didnt shoot a video of this). So I dont think its client side. Please test on your end

I couldnt find a video of this quest in TBC, so the underwater sounds might be blizzlike, but theres this more modern video where you dont hear them: https://youtu.be/7UOhJC5TdqY?t=106

**Comment by randomuser69** [comment]
GM Daystar has looked into this matter and has found that he too hears the underwater splashing sounds when the crabs walk. So this is definitely not client side. Here is the video he provided me with to post here: https://www.youtube.com/watch?v=c_ciMZbjijo&feature=youtu.be

**Comment by randomuser69** [comment]
This issue could be fixed by removing the shallow water stepping sound from crabs completely

**Comment by Wolffenstein** [comment]
The sound creatures make is handled client-side. There's nothing I can change to make it go away. All of those mobs' server-side values are in line with what was sent to the client on retail.

**Comment by randomuser69** [comment]
Thanks for looking into this Wolf. Appreciate you and your teams hard work on this fantastic server!
