### ISSUE TITLE
[PvP] S2 and S1 relics missing at vendor

### ISSUE THREAD

**Issue by Macumbafeh** [Atlantiss/NetherwingBugtracker#5801]
**Description**: 
ATM there is only relics healer for s1 and s2.
I don't really know the s1, so i was thinking it was blizzlike, but it's the same for s2, and i know that for s2 it's not blizzlike. Doing some researches, i Saw that there was a prob with s1 too. It seems nobody Saw it.

S2 Relics missing : 
Merciless gladiator's Idol of resolve : 
https://www.thegeekcrusade-serveur.com/db/?item=33939

Merciless gladiator's Idol of steadfastness : 
https://www.thegeekcrusade-serveur.com/db/?item=33943

Merciless gladiator's libram of Fortitude : 
https://www.thegeekcrusade-serveur.com/db/?item=33937

Merciless gladiator's libram of justice : 
https://www.thegeekcrusade-serveur.com/db/?item=33077

Merciless gladiator's totem of indomitability : 
https://www.thegeekcrusade-serveur.com/db/?item=33940

Merciless gladiator's totem of survival : 
https://www.thegeekcrusade-serveur.com/db/?item=33952

S1 Relics missing : 
Gladiator's Idol of resolve : 
https://www.thegeekcrusade-serveur.com/db/?item=33945

Gladiator's Idol of steadfastness : 
https://www.thegeekcrusade-serveur.com/db/?item=33942

Gladiator's libram of Fortitude : 
https://www.thegeekcrusade-serveur.com/db/?item=33936

Gladiator's libram of justice : 
https://www.thegeekcrusade-serveur.com/db/?item=28356

Gladiator's totem of indomitability : 
https://www.thegeekcrusade-serveur.com/db/?item=33939

Gladiator's Totem of Survival : 
https://www.thegeekcrusade-serveur.com/db/?item=33951

Revision**: 2967

**Comment by Evolvee** [comment]
fixed
