### ISSUE TITLE
[PvP] Missing Gladiator's Gavel from Vendor

### ISSUE THREAD

**Issue by CostinRaz** [Atlantiss/NetherwingBugtracker#5802]
I assumed this was a Season 1 issue, but looking at Wowhead comments it should have been present: https://www.wowhead.com/item=32450/gladiators-gavel#comments

The item in question is Gladiator's Gavel:
https://tbc-twinhead.twinstar.cz/?item=32450

Revision: 2967

**Comment by Evolvee** [comment]
not in the game until patch 2.1.
