### ISSUE TITLE
Continuation of issue 5508 (Investigate The Blue Recluse)

### ISSUE THREAD

**Issue by HolteUnderscore** [Atlantiss/NetherwingBugtracker#5803]
You closed the previous issue as though it were resolved, this isn't the case.  I just tested it again 5 minutes ago and still no mobs are spawning when you click the scroll.

**Comment by Evolvee** [comment]
its not updated yet.....

**Comment by Evolvee** [comment]
server needs to restart or crash
as you can see in changelog it was commited "yesterday 2AM"

but server uptime is

![image](https://user-images.githubusercontent.com/1942409/58634435-99286e80-82eb-11e9-9707-ec1068bf4d67.png)


.....
