### ISSUE TITLE
proc rate of improved wingclip is too high

### ISSUE THREAD

**Issue by zmthc93** [Atlantiss/NetherwingBugtracker#5804]
[//]: # (Enclose links to things related to the bug using http://wowhead.com or any other TBC database.)
[//]: # (You can use screenshot ingame to visual the issue.)
[//]: # (Write your tickets according to the format:)
[//]: # ([Quest][Azuremyst Isle] Red Snapper - Very Tasty!)
[//]: # ([NPC] Magistrix Erona)
[//]: # ([Spell][Mage] Fireball)
[//]: # ([Npc][Drop] Ghostclaw Lynx)
[//]: # ([Web] Armory doesnt work)
[//]: # (To find server revision type `.server info` command in the game chat.)

**Description**: 
procrate of improved wingclip is too high
**Current behaviour**:
procrate of improved wingclip is too high
**Expected behaviour**: 
procrate of improved wingclip should match tooltip
**Server Revision**:

**Comment by Wolffenstein** [comment]
Nope.
