### ISSUE TITLE
[Object] Ghost Mushroom

### ISSUE THREAD

**Issue by leeviathan** [Atlantiss/NetherwingBugtracker#5805]
**Description**: Ghost Mushrooms are herbs. They tend to spawn in caves.

**Current behaviour**: Ghost Mushrooms are not spawning in the open world. They are only spawning in instances.

**Expected behaviour**: Ghost Mushrooms should spawn in the Hinterlands (Skulk Rock, Jintha'Alor) and the caves around Maraudon in Desolace. In the comments of old posts I've also heard they should spawn in Ungoro Crater in the Fungal Rock caves, but I've only seen that for 3.1.3 at the earliest so I can't be sure they were there in TBC.

**Server Revision**: 2967

**Comment by someaddons** [comment]
I've gathered a few stacks of them in the hinterlands :D

**Comment by leeviathan** [comment]
Thanks, maybe something a little weird was going on at the time. Glad to know it was just bad luck on my end. Closing!
