### ISSUE TITLE
Corporal Title Disappearing upon relogging

### ISSUE THREAD

**Issue by Kolgrim** [Atlantiss/NetherwingBugtracker#5806]
[//]: # (Enclose links to things related to the bug using http://wowhead.com or any other TBC database.)
[//]: # (You can use screenshot ingame to visual the issue.)
[//]: # (Write your tickets according to the format:)
[//]: # ([Quest][Azuremyst Isle] Red Snapper - Very Tasty!)
[//]: # ([NPC] Magistrix Erona)
[//]: # ([Spell][Mage] Fireball)
[//]: # ([Npc][Drop] Ghostclaw Lynx)
[//]: # ([Web] Armory doesnt work)
[//]: # (To find server revision type `.server info` command in the game chat.)

**Description**: Was doing some PVP this morning and hit 500 HKs. Received Corporal title and it was automatically applied. I logged out shortly after and did not return for some hours. Upon returning to the game I no longer had Corporal title and was reverted to Private. I still have the required amount of honorable kills.
If I go and get 1 honorable kill then Corporal is reapplied. However, upon relogging it goes away again.

**Current behaviour**: Don't have corporal title

**Expected behaviour**: Should have corporal title

**Server Revision**: 2967
Screenshot linked of issue
[https://imgur.com/a/m86RrG5](url)

**Comment by danbopes** [comment]
Broken Link:

![](https://i.imgur.com/iy5t2KB.jpg)

**Comment by Kolgrim** [comment]
Let me know if you want video evidence I can record the whole process.

**Comment by Evolvee** [comment]
Supposedly happens with other titles as well.

**Comment by Linknown** [comment]
Ranked up to 'Knight' yesterday and am having this same problem now. After a relog I revert to 'Sergeant Major' until I get 1 honor kill.

**Comment by Kolgrim** [comment]
Issue still persists

**Comment by danbopes** [comment]
@Evolvee Can you confirm that if a player earns the rank of Corporal, previous ranks get removed as well? ie. A corporal *can't* have the title of "private".

**Comment by Evolvee** [comment]
ofc its like being exhalted and revered at the same time

**Comment by danbopes** [comment]
Fixed rev 3118
