### ISSUE TITLE
[Core][Proc Mechanics] On Successful spellcast

### ISSUE THREAD

**Issue by someaddons** [Atlantiss/NetherwingBugtracker#5807]
repost of #5690 as it is broken again.

> **Description**:
> Items/Procs with "On Successful spellcast" should proc from any spells. E.g. the darkmoon card blue dragon should proc from any spellcast, be it a hot/aura application or a direct spell.
> https://www.wowhead.com/item=19288/darkmoon-card-blue-dragon#comments
> 
> **Current behaviour**:
> The procflags:
> 
> * 14 Successful cast positive spell
> * 16 Successful damage from harmful spell cast
> 
> Currently those are not properly implemented, procs which have both flags cannot proc from any spellcast, e.g. https://www.wowhead.com/item=24122/coronet-of-verdant-flame does not proc from non direct spells.
> 
> **Expected behaviour**:
> Proc on any spellcast.
> Corecraft had it working with this implementation, might be useful to you:
> https://github.com/ccshiro/corecraft/blob/f76c1d3dcb951ec9e39b480d860f002d9b0c4491/server/src/game/Unit.cpp#L11706
> 
> **Server Revision**:
> 2944

**Comment by 0815Priester** [comment]
Darkmoon Card Blue Dragon
Should really every healed target (e.g. with Circle of Healing / Prayer of Healing) trigger the buff?
Yesterday on the PTR-Server I had a ridiculous high buff  uptime with just spamming Circle of Healing

**Comment by Tereneckla** [comment]
It should have the 2% chance per spellcast, not per target healed.

**Comment by 0815Priester** [comment]
Okay, then I'm pretty sure it's not working right. It feels more like I get 10% instead of 2% per cast (2%x 5% with Circle of Healing)

**Comment by Godmatik** [comment]
Fixed on upcoming spell/weapon proc branch
