### ISSUE TITLE
+20 bonusheal on ring (s2 salvation Ring) vanishes when joining arena /bg 

### ISSUE THREAD

**Issue by layalaa** [Atlantiss/NetherwingBugtracker#5808]
[//]: # (Enclose links to things related to the bug using http://wowhead.com or any other TBC database.)
[//]: # (You can use screenshot ingame to visual the issue.)
[//]: # (Write your tickets according to the format:)
[//]: # ([Quest][Azuremyst Isle] Red Snapper - Very Tasty!)
[//]: # ([NPC] Magistrix Erona)
[//]: # ([Spell][Mage] Fireball)
[//]: # ([Npc][Drop] Ghostclaw Lynx)
[//]: # ([Web] Armory doesnt work)
[//]: # (To find server revision type `.server info` command in the game chat.)

**Description**: 
+20 bonusheal on ring (s2 salvation Ring) vanishes when joining arena /bg 
**Current behaviour**:
When joining the Arena with the s2 ring equipped and enchanted with + 20 bonusheal, the + 20 heal only count if u unequip and then requip the ring. Deleting cache doesnt work
**Expected behaviour**: 

**Server Revision**:

**Comment by Evolvee** [comment]
https://github.com/Atlantiss/NetherwingBugtracker/issues/2779
