### ISSUE TITLE
PvP: Warrior Taunt / Tauntshout should affect Pets (WL/Hunter) Mage) in BG / Arena 

### ISSUE THREAD

**Issue by layalaa** [Atlantiss/NetherwingBugtracker#5809]
[//]: # (Enclose links to things related to the bug using http://wowhead.com or any other TBC database.)
[//]: # (You can use screenshot ingame to visual the issue.)
[//]: # (Write your tickets according to the format:)
[//]: # ([Quest][Azuremyst Isle] Red Snapper - Very Tasty!)
[//]: # ([NPC] Magistrix Erona)
[//]: # ([Spell][Mage] Fireball)
[//]: # ([Npc][Drop] Ghostclaw Lynx)
[//]: # ([Web] Armory doesnt work)
[//]: # (To find server revision type `.server info` command in the game chat.)

**Description**: 
PvP: Warrior Taunt / Tauntshout should affect Pets (WL/Hunter) Mage) in BG / Arena 
**Current behaviour**:
Pets no matter of which class ignore taunts / tauntshout of the Warrior
**Expected behaviour**: 
Pets should be forced to attack the Warrior in the Time the Taunt / Tauntshout is up
**Server Revision**:

**Comment by teddys** [comment]
Taunt does not affect pets in passive stance .. and everyone has pets in passive

**Comment by Evolvee** [comment]
^^

**Comment by layalaa** [comment]
who decides that it doesnt affect them? it worked on retail and at.
U could do some insane shit like taunting mage elemental before sheep so it gets u out by an instant etc.
Why u keep making the server worse with horrible fixxing decisionmaking. Netherwing was a rly dope server at start, but u just keep making it a warmane 2.0 buth with lags. And Warmane definetly has the worst pvp core of all time

**Comment by Evolvee** [comment]
its literally written in patch notes, how more obvious can it get

sit down
