### ISSUE TITLE
[Razorfen Kraul] Minor Bugs 

### ISSUE THREAD

**Issue by Azalen** [Atlantiss/NetherwingBugtracker#581]
**Description**: 
We went RFK today on alliance side with a slightly overleveled group: 24,27 (tank),28,29 (heal),31. I noticed some minor bugs even though the overall quality of the dungeon is amazing and every quest (including the warrior quest) was tested and worked fine.

Before I list the bugs I feel like I have to say that I think the difficulty of this dungeon is way to low. Even though we had two CCs in our group we never had to use them. We could add an extra pack of 2-3 elite mobs without any major harm done. While all the mobs have proper abilities (stuns, snares, heals) they just don't hit hard enough to make them count. Our druid healer spend most of his time in cat form dps'ing after he hotted me up before the fight. Also, for me as a warrior tank the low damage was particular bad because I was rage starved very often.

**Bugs**
map: https://www.bilder-upload.eu/upload/dedc7d-1537907793.png

(1) This Pack is not linked. It is the last pack before the main boss of the dungeon and consists of four elite mobs. Bodypulling only made three of those attack me while one caster stayed behind.

(2) There are Elite Mobs in the dungeon (I remember 4-5 of them on the bridges) that seem a bit out of place. They are level 30-31 elite even though the endboss of the dungeon is 27. I think they are relics of some very old patch version when RFK was intended for higher level players.
All Databases show them as mobs for RFK up to level 31 elite ([vanillaDB](https://classicdb.ch/?npc=4525), [allakhazam](https://web.archive.org/web/20071230193633/http://wow.allakhazam.com:80/db/mob.html?wmob=4525), [thottbot](https://web.archive.org/web/20080329045054/http://thottbot.com:80/c4525)) but a [video I found from wotlk](https://www.youtube.com/watch?v=GX1cn6CeAOA) only has them between level 25-26 (for example at 7:57). I think they never got the level downgrade from some very old vanilla patch.

(3) The mob Razorfen Stalker (https://classicdb.ch/?npc=6035) needs a higher stealth level because even though I only was 1 level higher I could see him steathed from ~15y away - and I am no human.

**Server Revision**: 
[2053]

**Comment by Azalen** [comment]
I forgot one thing: The quest starter for the RFK main quest: https://classicdb.ch/?item=5791 shows it needs level 29. But I was able to pick up the quest with 27 and I think that is right (considering the fact the boss that needs to get killed is level 27)
-> The Tooltip on the item needs to get changed

**Comment by Kvel2D** [comment]
Regarding the difficulty comment, you have to remember that patch 2.3 significantly nerfed all vanilla dungeons. They are supposed to be a steamroll. 
Post 2.3 dungeon level ranges:
https://wow.gamepedia.com/index.php?title=Instances_by_level&oldid=923891
Also, 2.3 RFK is a level 24-27 instance, so your group was way above slightly overleveled.

**Comment by aresbrutus** [comment]
Issue 2, are you talking about? https://www.wowhead.com/npc=4525/razorfen-earthbreaker#comments 

They seem to hae been present post 2.3.

**Comment by Azalen** [comment]
Yes but the level of those mobs is to high. There are some of those mobs at 30/31 elite while they should probably be 25/26 elite instead after the 2.3 downgrade.

**Comment by aresbrutus** [comment]
Ahh I see. Confirmed.

https://i.imgur.com/T31a3lh.png
https://i.imgur.com/9r816w8.png
https://i.imgur.com/jSXu8C2.png
