### ISSUE TITLE
<Innkeeper> Caregiver Topher Loaal keeps changing facing direction 

### ISSUE THREAD

**Issue by randomuser69** [Atlantiss/NetherwingBugtracker#5811]
[//]: # (Enclose links to things related to the bug using http://wowhead.com or any other TBC database.)
[//]: # (You can use screenshot ingame to visual the issue.)
[//]: # (Write your tickets according to the format:)
[//]: # ([Quest][Azuremyst Isle] Red Snapper - Very Tasty!)
[//]: # ([NPC] Magistrix Erona)
[//]: # ([Spell][Mage] Fireball)
[//]: # ([Npc][Drop] Ghostclaw Lynx)
[//]: # ([Web] Armory doesnt work)
[//]: # (To find server revision type `.server info` command in the game chat.)

**Description**: 
<Innkeeper> Caregiver Topher Loaal, who is the innkeeper in Blood Watch on Bloodmyst Isle (https://tbcdb.com/?npc=17553) keeps changing the way he looks at different times and doesnt just look towards entrance like he should. If this is a client issue, please let me know.  

**Current behaviour**:
![WoWScrnShot_053119_233515](https://user-images.githubusercontent.com/51173000/58743341-84d49680-83fd-11e9-84a5-556df7a125ae.jpg)

**15 minutes later:**
![WoWScrnShot_060119_005754](https://user-images.githubusercontent.com/51173000/58743895-55775700-8408-11e9-949f-95884d1fb043.jpg)

**Hour later:** 
![WoWScrnShot_060119_022259](https://user-images.githubusercontent.com/51173000/58744907-efde9700-8416-11e9-8b5f-8f7ea3108c7f.jpg)

**A day later**
![WoWScrnShot_060119_231350](https://user-images.githubusercontent.com/51173000/58756732-65f10580-84cc-11e9-96c9-99baf7d74d80.jpg)

**Expected behaviour**: 
On retail he looks towards the entrance only:
VIDEO: https://youtu.be/5wNPj4dM22w?t=1568
![maxresdefault](https://user-images.githubusercontent.com/51173000/58743409-ad10c500-83fe-11e9-879b-65d318d50bd5.jpg)
![maxresdefault](https://user-images.githubusercontent.com/51173000/58743357-c107f700-83fd-11e9-875a-5c29b6e0cf54.jpg)

**Server Revision**: 
2976

**Comment by Evolvee** [comment]
rev 2986 (maybe, not sure whats causing this)
