### ISSUE TITLE
Quest: Saving Princess Stillpine: on hand-in progress text shows instead of completion text

### ISSUE THREAD

**Issue by randomuser69** [Atlantiss/NetherwingBugtracker#5812]
[//]: # (Enclose links to things related to the bug using http://wowhead.com or any other TBC database.)
[//]: # (You can use screenshot ingame to visual the issue.)
[//]: # (Write your tickets according to the format:)
[//]: # ([Quest][Azuremyst Isle] Red Snapper - Very Tasty!)
[//]: # ([NPC] Magistrix Erona)
[//]: # ([Spell][Mage] Fireball)
[//]: # ([Npc][Drop] Ghostclaw Lynx)
[//]: # ([Web] Armory doesnt work)
[//]: # (To find server revision type `.server info` command in the game chat.)

**Description**: 
After finishing the quest Saving Princess Stillpine (https://wowwiki.fandom.com/wiki/Quest:Saving_Princess_Stillpine) and talking to the turn in NPC (Stillpine Ambassador Frasaboo) he states the Princess' progress text (I don't have much longer, [Name]. They will kill me soon... ) which is obviously not correct. 

**Current behaviour**:
![WoWScrnShot_060119_000046](https://user-images.githubusercontent.com/51173000/58743524-24475880-8401-11e9-857d-c23125dee57a.jpg)
![WoWScrnShot_060119_000052](https://user-images.githubusercontent.com/51173000/58743525-24475880-8401-11e9-9e72-353c6f37ea69.jpg)
![WoWScrnShot_060119_000056](https://user-images.githubusercontent.com/51173000/58743526-24475880-8401-11e9-9301-0903cf517065.jpg)

**Expected behaviour**: 
The Progress text should not be displayed after talking to the ambassador and only the competition text should show:
VIDEO EXAMPLE FROM RETAIL: 
https://youtu.be/YdkdTDK9-cs?t=220

**Server Revision**: 
2976

**Comment by Evolvee** [comment]
rev 2986
