### ISSUE TITLE
[Druid] [Entangling Roots] is still DR'ing with proc'd roots.

### ISSUE THREAD

**Issue by gunzbngbng** [Atlantiss/NetherwingBugtracker#5813]
[//]: # (Enclose links to things related to the bug using http://wowhead.com or any other TBC database.)
[//]: # (You can use screenshot ingame to visual the issue.)
[//]: # (Write your tickets according to the format:)
[//]: # ([Quest][Azuremyst Isle] Red Snapper - Very Tasty!)
[//]: # ([NPC] Magistrix Erona)
[//]: # ([Spell][Mage] Fireball)
[//]: # ([Npc][Drop] Ghostclaw Lynx)
[//]: # ([Web] Armory doesnt work)
[//]: # (To find server revision type `.server info` command in the game chat.)

**Description**: There are various proc'd roots in TBC and they all are intended to DR against only themselves.  Currently, Entangling roots is being DR'd by proc'd roots like improved wing clip and entrapment.

**Current behaviour**: Entangling roots is being DR'd by proc'd roots like improved wing clip and entrapment.

**Expected behaviour**: Entangling roots should not be DR'd by proc'd roots like improved wing clip and entrapment.

**Server Revision**: 2976

**Comment by SwiftieTBC** [comment]
Proof :
Immobilizes effects come in two main categories, activated and random trigger, which are on separate diminishing returns timers. Nevertheless, all Immobilize effects are all functionally identical; they prevent the target from moving for the duration of the effect, but do not prevent the target from acting. Immobilize effects do not break automatically break on damage, but attacking an immobilized target does give them a heightened chance to cause them to break free.

Activated Immobilize effects include Druid's Entangling Roots, Mage's Frost Nova, Hunter's Counterattack. Random trigger Immobilize effects include Mage's Frostbite, Hunter's Entrapment and Warrior's Improved Hamstring.

http://wow.allakhazam.com/wiki/Immobilize_%28WoW%29

**Comment by gunzbngbng** [comment]
Entrapment is still causing DR with Entangling Roots.

**Comment by Wolffenstein** [comment]
Fixed in rev 3078.
