### ISSUE TITLE
Blackslit Scout levels up after being tagged for Catch and Release quest

### ISSUE THREAD

**Issue by randomuser69** [Atlantiss/NetherwingBugtracker#5814]
[//]: # (Enclose links to things related to the bug using http://wowhead.com or any other TBC database.)
[//]: # (You can use screenshot ingame to visual the issue.)
[//]: # (Write your tickets according to the format:)
[//]: # ([Quest][Azuremyst Isle] Red Snapper - Very Tasty!)
[//]: # ([NPC] Magistrix Erona)
[//]: # ([Spell][Mage] Fireball)
[//]: # ([Npc][Drop] Ghostclaw Lynx)
[//]: # ([Web] Armory doesnt work)
[//]: # (To find server revision type `.server info` command in the game chat.)

**Description**: 
For the quest "Catch and Release" (https://tbc-twinhead.twinstar.cz/?quest=9629) the player has to tag Blackslit Scouts. After tagging a "Blackslit Scout" it becomes a "Tagged Blackslit Scout". Sometimes, though not always (maybe ~25% of the time), the NPC levels up during this name/model transition and plays the level up noise and effect

**Current behaviour**:
![WoWScrnShot_060119_005221](https://user-images.githubusercontent.com/51173000/58743986-899f4780-8409-11e9-81ed-6334b68fdf33.jpg)

![WoWScrnShot_060119_005138](https://user-images.githubusercontent.com/51173000/58743940-eb12e680-8408-11e9-86d0-94531e3158a9.jpg)

**Expected behaviour**: 
The Blackslit Scout should not change levels after becoming a Tagged Blackslit Scout

**Server Revision**: 
2976

**Comment by Evolvee** [comment]
https://github.com/Atlantiss/NetherwingBugtracker/issues/3737 duplicate
