### ISSUE TITLE
Tzerak yells his scripted line twice in a row

### ISSUE THREAD

**Issue by randomuser69** [Atlantiss/NetherwingBugtracker#5815]
[//]: # (Enclose links to things related to the bug using http://wowhead.com or any other TBC database.)
[//]: # (You can use screenshot ingame to visual the issue.)
[//]: # (Write your tickets according to the format:)
[//]: # ([Quest][Azuremyst Isle] Red Snapper - Very Tasty!)
[//]: # ([NPC] Magistrix Erona)
[//]: # ([Spell][Mage] Fireball)
[//]: # ([Npc][Drop] Ghostclaw Lynx)
[//]: # ([Web] Armory doesnt work)
[//]: # (To find server revision type `.server info` command in the game chat.)

**Description**: 
Tzerak (https://tbc-twinhead.twinstar.cz/?npc=17528) yells his scripted line twice in a row after he spawns following the summoning scripted event.

**Current behaviour**:
Here he is right after being summoned:
![WoWScrnShot_060119_022137](https://user-images.githubusercontent.com/51173000/58744928-4a77f300-8417-11e9-850a-50acd90a7374.jpg)

This is from when I was far away from him about 15 min earlier (just to show that the line being said twice was not a one time thing...in fact I saw it happen 3 or 4 times total while I was questing in that area)
![WoWScrnShot_060119_020952](https://user-images.githubusercontent.com/51173000/58744931-582d7880-8417-11e9-8b71-88c916b7b7c6.jpg)

**Expected behaviour**: 
He should only say his scripted line once

**Server Revision**: 
2976

**Comment by Firroth** [comment]
I happened to report it during P1 of beta tests before release, seems like it still wasn't fixed to this day.
Issue #180

**Comment by Evolvee** [comment]
duplicate ^^
