### ISSUE TITLE
Feral druid crit chance in feral forms (Cat, Bear, Dire Bear)

### ISSUE THREAD

**Issue by Thunderclash** [Atlantiss/NetherwingBugtracker#5816]
**Description**: 
Feral druid - crit chance talent Sharpened Claws - **critical bug**

**Current behaviour**:
Feral druid talent branch, talent "Sharpened Claws" only adds up 3% crit chance in Cat Form, Dire Bear Form, Bear Form.

**Expected behaviour**: 
Talent should add 6% crit chance while in Cat Form, Dire Bear Form, Bear Form.

**Server Revision**: 
Tested in person, 3rd point in the 3/3 talent Sharpened Claws only did add 1% crit chance while I was in Cat Form. I had +- 12% crit chance while I was in Cat Form, then I entered 3rd point in Sharpened Claws talent and it went up only by 1% to total 13%. Talent seems to be giving half of the percentage crit that should be given by the talent according to the talent description in Talents.

More tests needed from testers/participants/devs.

**Comment by Thunderclash** [comment]
![Crit chance bug Netherwing](https://user-images.githubusercontent.com/32386207/58749496-60bd9780-8487-11e9-8f7c-d6c80027e2d5.png)

**Comment by Tenoutoften** [comment]
Did you try relogging? A lot of talents dont update unless you relog

**Comment by Thunderclash** [comment]
After relogging it stays the same. Same crit chance.

**Comment by Thunderclash** [comment]
Issue needs fixing.

**Comment by FabianMueller77** [comment]
can't reproduce (on PTR so maybe it's already fixed)
![Sharpened Claws](https://user-images.githubusercontent.com/46138731/59273214-f6abac00-8c57-11e9-9f9a-aa8e1d42723d.png)
