### ISSUE TITLE
Player health % visual bug

### ISSUE THREAD

**Issue by monoeko** [Atlantiss/NetherwingBugtracker#5818]
[//]: # (Enclose links to things related to the bug using http://wowhead.com or any other TBC database.)
[//]: # (You can use screenshot ingame to visual the issue.)
[//]: # (Write your tickets according to the format:)
[//]: # ([Quest][Azuremyst Isle] Red Snapper - Very Tasty!)
[//]: # ([NPC] Magistrix Erona)
[//]: # ([Spell][Mage] Fireball)
[//]: # ([Npc][Drop] Ghostclaw Lynx)
[//]: # ([Web] Armory doesnt work)
[//]: # (To find server revision type `.server info` command in the game chat.)

**Description**: On a fresh night elf character, upon leveling up to lvl 3 their health suddenly displayed as a percentage, while mana stayed the same (showing the simple numeric value). Messing around with settings and cache could not change this. I could still see other player characters' actual HP value, and NPCs as percentages. However, I encountered another lvl 3 night elf that also was showing their health as percentage, and this went away for both of us upon level up to 4. We were both Hunters.

**Current behaviour**: Everything back to normal, was clearly just tied to being level 3, and possibly the Hunter class/night elf race combo.

**Expected behaviour**: 

**Server Revision**: 2976

**Comment by Evolvee** [comment]
health is displayed in % always unless u are in a party
