### ISSUE TITLE
[Quest][Mage]Investigate the Alchemist Shop (1960)

### ISSUE THREAD

**Issue by Kentamentiu** [Atlantiss/NetherwingBugtracker#582]
[//]: # (Enclose links to things related to the bug using http://wowhead.com or any other TBC database.)
[//]: # (You can use screenshot ingame to visual the issue.)
[//]: # (Write your tickets according to the format:)
[//]: # ([Quest][Azuremyst Isle] Red Snapper - Very Tasty!)
[//]: # ([NPC] Magistrix Erona)
[//]: # ([Spell][Mage] Fireball)
[//]: # ([Npc][Drop] Ghostclaw Lynx)
[//]: # ([Web] Armory doesnt work)

**Description**: 
Use the Cantation of Manifestation (7308) in the Alchemist shop near an Arcane Disturbance. 3 Rift Spawn show up. You beat them to 1hp then use Chest of Containment Coffers to catch their soul in a Containment Coffer. You then click the containment coffer to loot and get credit.

**Current behaviour**:
*The clickable containment coffer is difficult to click, it requires some mouse finessing.
*When you defeat the Rift Spawn on top of the stairs, it is impossible to use the Chect of Containment Coffers on them.

**Expected behaviour**: 
*Easier to click.
*Be able to contain the soul of the Rift Spawn anywhere.

**Server Revision**: 
2050

**Comment by Evolvee** [comment]
https://github.com/Atlantiss/NetherwingBugtracker/issues/5518

**Comment by Borkla** [comment]
i cant even get the ghosts to spawn no matter where i use cantation so now you cant even spawn the ghosts anymore

**Comment by Ravengrudge** [comment]
Update 4/30/2019
Mobs still won't spawn :<

**Comment by Evolvee** [comment]
rev 2971
