### ISSUE TITLE
[Quest] Unable to retrieve Yeh'kinya Scroll after completing The God Hakkar

### ISSUE THREAD

**Issue by danbopes** [Atlantiss/NetherwingBugtracker#5820]
**Description**: 
According to wowhead, you should be able to talk with Yeh'kinya afterwards to receive a [Yeh'kinya Scroll](https://www.wowhead.com/item=10818/yehkinyas-scroll):

![](https://i.imgur.com/Fi60z8P.png)

**Current behaviour**:
Completed Quest 'The God Hakkar'. Gossip frame shows:
![](https://i.imgur.com/8J3mNHb.png)

**Expected behaviour**: 
Yeh'kinya should offer some way to retrieve the scroll.

**Server Revision**: 
2976

**Comment by Evolvee** [comment]
rev 2986
