### ISSUE TITLE
Not possible to enchant a lucky fishing hat with a lesser arcanum.

### ISSUE THREAD

**Issue by Moonzy123** [Atlantiss/NetherwingBugtracker#5822]
[//]: # (Enclose links to things related to the bug using http://wowhead.com or any other TBC database.) 
[//]: # (You can use screenshot ingame to visual the issue.)
[//]: # (Write your tickets according to the format:)
[//]: # ([Quest][Azuremyst Isle] Red Snapper - Very Tasty!)
[//]: # ([NPC] Magistrix Erona)
[//]: # ([Spell][Mage] Fireball)
[//]: # ([Npc][Drop] Ghostclaw Lynx)
[//]: # ([Web] Armory doesnt work)
[//]: # (To find server revision type `.server info` command in the game chat.)

**Description**: 
Lesser arcanums are items obtained from Burning Steppes. They are soulbound items and can be used to give +8 to a primary stat to a head or leg slot item. 
However, it is possible to enchant gear of other players if they put their head or leg armor in the 'will not be traded' slot. The player with the arcanum can then enchant the item, just like an enchanter can do this with any basically any enchant on any valid item. 
However, on Netherwing, you get an error message: "This item is already enchanted." This is because the item 'Lucky Fishing Hat' (link: https://classic.wowhead.com/item=19972/lucky-fishing-hat#comments) has an innate +5 fishing skill. 

**Current behaviour**: 

Enchanting the Lucky Fishing hat with a lesser arcanum of voracity (https://classic.wowhead.com/item=11647/lesser-arcanum-of-voracity) is impossible because the error message 'This item cannot be enchanted' prevents the enchant from being applied.

**Expected behaviour**: 

Enchanting arcanums to leg and head pieces was blizzlike and totally valid. There were no level requirements which means they were sough after by twinks. 
Proof: https://gnomeaggedon.wordpress.com/2008/08/14/twinking-your-level-19-warlock-part-4-enchanting-your-twink/ (guide from 2008.)

**Server Revision**: 
2976

**Comment by Manaci** [comment]
Fixed
