### ISSUE TITLE
[item] Solarian's sapphire not affected by [talent] commanding presence

### ISSUE THREAD

**Issue by teddys** [Atlantiss/NetherwingBugtracker#5823]
https://www.wowhead.com/item=30446/solarians-sapphire#comments

**Current behaviour**: with 5/5 the ap increase is only 70

**Expected behaviour**:  with 5/5 commanding presence, the ap should be increased by 87.5

**Server Revision**: 2976

**Comment by Manaci** [comment]
Fixed
