### ISSUE TITLE
[NPC][Raid][Spell] Lord Robin Daris

### ISSUE THREAD

**Issue by Spaztick** [Atlantiss/NetherwingBugtracker#5824]
**Description**: 
Lord Robin Daris in Karazahn has whirlwind range at ~10-15 yards. I can find no documentation on the range, but for a whirlwind effect I would expect it to have similar range of the warrior whirlwind (melee, ~5 yards).

**Server Revision**: 
2976

**Comment by Wolffenstein** [comment]
Effect 0: Id 17 (SPELL_EFFECT_WEAPON_DAMAGE_NOSCHOOL)
BasePoints = 300 + Level * 6,00
Targets (22, 15) (TARGET_SRC_CASTER, TARGET_UNIT_SRC_AREA_ENEMY)
Radius (Id 14) 8,00
