### ISSUE TITLE
[Spell][Paladin] Consecration Range Too Small

### ISSUE THREAD

**Issue by Cicinus** [Atlantiss/NetherwingBugtracker#5825]
[//]: # (Enclose links to things related to the bug using http://wowhead.com or any other TBC database.)

**Description**: 
Consecration Range is too small
**Current behaviour**:
Consecration using the centre of the targets hitbox to determine if it lands 
**Expected behaviour**: 
Should be enough to only hit the edge of the hit box with consecration 
Evidence for Proper Functioning
https://youtu.be/UyooXkH6mT8?t=30
**Server Revision**: 
2976

**Comment by Tenoutoften** [comment]
I think that in most cases it's an issue with the boss hit box. There are bosses that I have to stand very close on to use consecrate or it wont hit. Can happen with SP's last boss, or Fel Reaver, I believe it happens with Lurker to...

**Comment by veekk** [comment]
same with Magtheridon

**Comment by Tenoutoften** [comment]
The bosses might re-position in your attempt to land a successful consecration, quite annoying and dangerous, Quagmirre got a cleave, so I've ended up leaving my fellow melees since I need Consecration to hit or the ranged will pull agro

**Comment by Cicinus** [comment]
As it is obvious whoever priorities issues doesn't understand the full implication of this bug lets put it in easy to understand terms not being able to consecrations is approximately 30% threat reduction. In any serious guild that makes pally completely nonviable on certain bosses where they should be perfectly fine . Eg lurker, Gruul

**Comment by Wolffenstein** [comment]
Fixed in rev 2992.
