### ISSUE TITLE
Cookie kept using her healing ability "Cookie's Cooking" over and over nonstop making fight very long

### ISSUE THREAD

**Issue by randomuser69** [Atlantiss/NetherwingBugtracker#5827]
[//]: # (Enclose links to things related to the bug using http://wowhead.com or any other TBC database.)
[//]: # (You can use screenshot ingame to visual the issue.)
[//]: # (Write your tickets according to the format:)
[//]: # ([Quest][Azuremyst Isle] Red Snapper - Very Tasty!)
[//]: # ([NPC] Magistrix Erona)
[//]: # ([Spell][Mage] Fireball)
[//]: # ([Npc][Drop] Ghostclaw Lynx)
[//]: # ([Web] Armory doesnt work)
[//]: # (To find server revision type `.server info` command in the game chat.)

**Description**: 
Cookie kept using her ability "Cookie's Cooking" (https://classicdb.ch/?spell=5174) which heals her, over and over, making the fight a very long time.

**Current behaviour**:
![WoWScrnShot_060319_204353](https://user-images.githubusercontent.com/51173000/58851010-05460200-865f-11e9-936f-4b2d7dab1e50.jpg)
![WoWScrnShot_060319_204355](https://user-images.githubusercontent.com/51173000/58851011-05460200-865f-11e9-8f9c-c49988ec20f8.jpg)
![WoWScrnShot_060319_204359](https://user-images.githubusercontent.com/51173000/58851012-05de9880-865f-11e9-8559-b6d7423eb720.jpg)
![WoWScrnShot_060319_204411](https://user-images.githubusercontent.com/51173000/58851013-05de9880-865f-11e9-9664-ca2075ed77f7.jpg)
![WoWScrnShot_060319_204427](https://user-images.githubusercontent.com/51173000/58851014-05de9880-865f-11e9-88c9-abe1b7f4bc5f.jpg)
![WoWScrnShot_060319_204428](https://user-images.githubusercontent.com/51173000/58851015-05de9880-865f-11e9-8054-8f0d1a06b925.jpg)

**Looks like this bug re Cookie was reported here also (along with another bug):
https://github.com/Atlantiss/NetherwingBugtracker/issues/3637**

**Expected behaviour**: 
There should be a cooldown on the ability "Cookie's Cooking". Looking at Classic wow beta footage, I dont even see cookie using this ability (https://youtu.be/aiQF6aAM8nU?t=11356) but I assume its supposed to have a reasonable cooldown (30 seconds let say) and definitely not constantly one after the other

**Server Revision**: 
2976

**Comment by Evolvee** [comment]
rev 2986
