### ISSUE TITLE
[Spell][Goblin Engineer] No Quest available!

### ISSUE THREAD

**Issue by SlizeTBC** [Atlantiss/NetherwingBugtracker#5828]
**Description**: Relearning Goblin Engineering after someone had Gnomish Engineering doesn't work by paying 150g in Steamwheedle Port atm, so Narilrave unlearned Gnomish Engi for me. I was able to learn all the Goblin Engineering Items in Gadgetzan after that, but I wasn't able to do the Quest to receive "Goblin Engineer" in my Spellbook. And you need this to be able to use those Items, for example Area52 Teleport Trinket.

Atm I can make somehow Gnomish and Goblin Engi. Items, but I cant use any of those Items cause of the missing Quest. Somehow tho, I have the Goblin Engineering Member Ship Card in my Bags, but nothing in my Spellbook.

https://i.imgur.com/uCbi1c4.png
https://i.imgur.com/U68vnkZ.png

**Server Revision**: 2984

**Comment by Wolffenstein** [comment]
There was no option to unlearn Engineering specialization before wotlk (without removing the entire profession). Throw away the membership card and visit appropriate specialization trainer.

**Comment by SlizeTBC** [comment]
Well fair enough, Naril still removed gnomish engi and gave me goblin engi card. But I cant use any Item cause i Dont have the Spell "Goblin Engineer" in my Spellbook. Cause Naril forgot it.

**Comment by wtRCH** [comment]
@SlizeTBC Contact Narilrave on Discord to restore it for you. Cheers.
