### ISSUE TITLE
[Patch 2.1] SSC/TK weapons using patch 2.2 item stats

### ISSUE THREAD

**Issue by Azalen** [Atlantiss/NetherwingBugtracker#5829]
**Description**: 
The weapon-slot and ranged-weapon-slot raiddrops (every item with a dps-value) from SSC/TK got buffed twice on retail TBC. Once in patch 2.1 and once more in patch 2.2 which marks the final patch regarding item changes.

Right now on the PTR (and for Kael'Thas on live-server) Netherwing uses the final, and thus strongest forms of those items and not the correct ones for patch 2.1.

This will ofc impact melee dps in progress tier6 content since major weapons are tuned down and crafted blacksmithing weapons still reward the highest weapon dps ingame. As a rule of thumb in patch 2.0 a 1h raidepic (non-endboss) has 88dps, in 2.1 it has 93dps and in 2.2 it has 96dps.

It will also indirectly buff loot from worldbosses since those items reach their final form in patch 2.1 already.

### Affected Items

**Fang of the Leviathan (Leotheras, SSC)**
Patch 2.0: https://web.archive.org/web/20070514140517/http://www.thottbot.com/i30095
Patch 2.1: https://web.archive.org/web/20070825042942/http://www.thottbot.com/i30095
Patch 2.2: https://web.archive.org/web/20080111215309/http://www.thottbot.com/i30095

**Mallet of the Tides (Lurker Below, SSC)**
Patch 2.0: https://web.archive.org/web/20070501201915/http://www.thottbot.com/i30058
Patch 2.1: https://web.archive.org/web/20070713062004/http://www.thottbot.com/i30058
Patch 2.2: https://web.archive.org/web/20071002151025/http://www.thottbot.com/i30058

**World Breaker (FLK, SSC)**
Patch 2.0: https://web.archive.org/web/20070408131625/http://www.thottbot.com/i30090
Patch 2.1: https://web.archive.org/web/20070704003819/http://www.thottbot.com/i30090
Patch 2.2: https://web.archive.org/web/20071011034243/http://www.thottbot.com/i30090

**Talon of Azshara (Morogrim, SSC)**
Patch 2.0: https://web.archive.org/web/20070312092029/http://www.thottbot.com/i30082
Patch 2.1: https://web.archive.org/web/20070711055650/http://www.thottbot.com/i30082
Patch 2.2: https://web.archive.org/web/20071226184033/http://www.thottbot.com/i30082

**Luminescent Rod of the Naaru (Morogrim, SSC)**
Patch 2.0: https://web.archive.org/web/20070501210003/http://www.thottbot.com/i30080
Patch 2.1: https://web.archive.org/web/20070811024420/http://www.thottbot.com/i30080
Patch 2.2: https://web.archive.org/web/20071227062515/http://www.thottbot.com/i30080

**Fang of Vashj (Vashj, SSC)**
Patch 2.0: https://web.archive.org/web/20070501204532/http://www.thottbot.com/i30103
Patch 2.1: https://web.archive.org/web/20070910072310/http://www.thottbot.com/i30103
Patch 2.2: https://web.archive.org/web/20071029202148/http://www.thottbot.com/i30103

**Serpent Spine Longbow (Vashj, SSC)**
Patch 2.0: https://web.archive.org/web/20070504012821/http://www.thottbot.com/i30105
Patch 2.1: https://web.archive.org/web/20070819234111/http://www.thottbot.com/i30105
Patch 2.2: https://web.archive.org/web/20071030214909/http://www.thottbot.com/i30105

**Lightfathom Scepter (Vashj, SSC)**
Patch 2.0: No Data; correct on Netherwing though
Patch 2.1: https://web.archive.org/web/20070527085254/http://www.thottbot.com/i30108
Patch 2.2: https://web.archive.org/web/20071107062105/http://www.thottbot.com/i30108

**Lightfury Greatstaff (Trash, SSC)**
Patch 2.0: https://web.archive.org/web/20070312055909/http://www.thottbot.com/i30021
Patch 2.1: https://wowwiki.fandom.com/wiki/Wildfury_Greatstaff?oldid=837330 || https://web.archive.org/web/20071201101535/http://thottbot.com/i30021
Patch 2.2: https://wowwiki.fandom.com/wiki/Wildfury_Greatstaff?oldid=965418 || https://web.archive.org/web/20071107062105/http://www.thottbot.com/i30108

**Serpentshrine Shuriken (Trash, SSC)**
Patch 2.0: https://web.archive.org/web/20070508171708/http://www.thottbot.com/i30025
Patch 2.1: https://web.archive.org/web/20070706234028/http://www.thottbot.com/i30025
Patch 2.2: https://web.archive.org/web/20071124013902/http://www.thottbot.com/i30025

**Arcanite Steam Pistol (Al'ar, TK)**
Patch 2.0: No Data; correct on Netherwing though
Patch 2.1: https://web.archive.org/web/20070711030047/http://www.thottbot.com/i29949
Patch 2.2: https://web.archive.org/web/20071128062300/http://www.thottbot.com/i29949

**Netherbane (Al'ar, TK)**
Patch 2.0: No Data; correct on Netherwing though
Patch 2.1: https://web.archive.org/web/20070527085248/http://www.thottbot.com/i29924
Patch 2.2: https://web.archive.org/web/20071128073634/http://www.thottbot.com/i29924

**Claw of the Phoenix (Al'ar, TK)**
Patch 2.0: No Data; correct on Netherwing though
Patch 2.1: https://web.archive.org/web/20070710042746/http://www.thottbot.com/i29948
Patch 2.2: https://web.archive.org/web/20071006005941/http://www.thottbot.com/i29948

**Talon of the Phoenix (Al'ar, TK)**
Patch 2.0: No Data; correct on Netherwing though
Patch 2.1: https://web.archive.org/web/20070703055306/http://www.thottbot.com/i32944
Patch 2.2: https://web.archive.org/web/20071012031748/http://www.thottbot.com/i32944

**Heartrazor (Solarian, TK)**
Patch 2.0: https://web.archive.org/web/20070503053932/http://www.thottbot.com/i29962
Patch 2.1: https://web.archive.org/web/20070708201023/http://www.thottbot.com/i29962
Patch 2.2: https://web.archive.org/web/20071104193138/http://www.thottbot.com/i29962

**Wand of the Forgotten Star (Solarian, TK)**
Patch 2.0: https://web.archive.org/web/20070503052614/http://www.thottbot.com/i29982
Patch 2.1: https://web.archive.org/web/20070819100749/http://www.thottbot.com/i29982
Patch 2.2: https://web.archive.org/web/20071027161450/http://www.thottbot.com/i29982

**Ethereum Life-Staff (Solarian, TK)**
Patch 2.0: https://web.archive.org/web/20070509013703/http://www.thottbot.com/i29981
Patch 2.1: https://web.archive.org/web/20070711020850/http://www.thottbot.com/i29981
Patch 2.2: https://web.archive.org/web/20071011024519/http://www.thottbot.com/i29981

**Rod of the Sun King (Kael'Thas, TK)**
Patch 2.0: No Data
Patch 2.1: https://web.archive.org/web/20070704010654/http://www.thottbot.com/i29996
Patch 2.2: https://web.archive.org/web/20071103135018/http://www.thottbot.com/i29996

**The Nexus Key (Kael'Thas, TK)**
Patch 2.0: No Data
Patch 2.1: https://web.archive.org/web/20070630015926/http://www.thottbot.com/i29988
Patch 2.2: https://web.archive.org/web/20071011012738/http://www.thottbot.com/i29988

**Twinblade of the Phoenix (Kael'Thas, TK)**
Patch 2.0: No Data
Patch 2.1: https://web.archive.org/web/20070708200833/http://www.thottbot.com/i29993
Patch 2.2: https://web.archive.org/web/20071104193153/http://www.thottbot.com/i29993

**Comment by Tenoutoften** [comment]
Lightfathom Scepter should already be fixed:
https://github.com/Atlantiss/NetherwingBugtracker/issues/3208
https://github.com/Atlantiss/NetherwingBugtracker/issues/3141

**Comment by ircfelix** [comment]
Is this bug also affecting all tier sets and raid epics? Because if it is, it's a shitload of work to fix all this.

**Comment by Azalen** [comment]
I did some samples (obviously didnt test all items) but seems to only affect items with a dps-value on it (caster offhands are not affected, but wands are).

The only thing that changes between 2.1 and later patches are specific set-bonus for some classes (e.g. warlock T5 4p from 3% -> 10%)

**Comment by Evolvee** [comment]
rev 2994 by swiftie

**Comment by Evolvee** [comment]
check it on ptr again pls

**Comment by Azalen** [comment]
**Current Issues:** 
- Fang of Leviathan missing 209 Spellpower
- Lightfathom Scepter wrong dps and wrong enumeration (stamina first, then int is correct)
- Wildfury Greatstaff still in full 2.2 version
- Netherbane dps incorrect
- Claw of the Phoenix dps incorrect

**Comment by Azalen** [comment]
@SwiftieTBC

**Comment by Evolvee** [comment]
its on PTR, retest pls

**Comment by FabianMueller77** [comment]
in the case of the Wildfury Greatstaff this isn't a 2.2 itemlvl buff like the other weapons, but the 2.3 feral attack power reevaluation where blizzard noticed that feral weapons were scaling worse than 2h weapons of the same ilvl.
![wilfury](https://user-images.githubusercontent.com/46138731/59295103-2a4ffb80-8c83-11e9-93ba-6e82f3910771.png)
If you change the Greatstaff you got to readjust all feral ap weapons, including the t6 one.

**Comment by Azalen** [comment]
**Current Issues:** 
- Fang of Leviathan missing 209 Spellpower

**Comment by Azalen** [comment]
@SwiftieTBC
