### ISSUE TITLE
[Spell][Equip] Shoot Wand Animation Bug

### ISSUE THREAD

**Issue by towneh** [Atlantiss/NetherwingBugtracker#583]
**Description**: 
Shoot wand continues the shooting animation when you select yourself during combat

**Current behaviour**:
https://imgur.com/a/IHHwLis
Selecting yourself whilst shooting an enemy npc makes the wand animation continue, until you select the enemy npc again.

**Expected behaviour**: 
Wand animation should stop once you de-select a hostile npc.

**Server Revision**: 
2050

**Comment by Wolffenstein** [comment]
Rev 2052.
