### ISSUE TITLE
[Quest][Western Plaguelands] Unfinished Business

### ISSUE THREAD

**Issue by rychersky** [Atlantiss/NetherwingBugtracker#5830]
**Description**: Enter Hearthglen and find a high vantage point from which you can see the town and gauge the Scarlet Crusade's forces, then return to Kirsta Deepshadow in Western Plaguelands.

**Current behaviour**: 

![image](https://user-images.githubusercontent.com/45608488/58984845-46d9c880-8797-11e9-8bfc-8e75bc81c0ab.png)

**Expected behaviour**: From [Wowhead](https://www.wowhead.com/quest=6025/unfinished-business#comments): Just climb to the top of the tower, look across to the entrance and you'll get a quest complete message.

**Server Revision**: 2984

**Comment by rychersky** [comment]
Turns out you need to look slightly to the right. So it's not behaving exactly as expected from retail, but good enough (though I and another player stood there a bit confused trying to figure it out).

![image](https://user-images.githubusercontent.com/45608488/58984981-8c969100-8797-11e9-8af7-838de7ce848b.png)

**Comment by wtRCH** [comment]
Reopening.

**Comment by Evolvee** [comment]
6025

**Comment by Evolvee** [comment]
fixed
