### ISSUE TITLE
Shadowmeld occasionally undetectable

### ISSUE THREAD

**Issue by zmthc93** [Atlantiss/NetherwingBugtracker#5832]
[//]: # (Enclose links to things related to the bug using http://wowhead.com or any other TBC database.)
[//]: # (You can use screenshot ingame to visual the issue.)
[//]: # (Write your tickets according to the format:)
[//]: # ([Quest][Azuremyst Isle] Red Snapper - Very Tasty!)
[//]: # ([NPC] Magistrix Erona)
[//]: # ([Spell][Mage] Fireball)
[//]: # ([Npc][Drop] Ghostclaw Lynx)
[//]: # ([Web] Armory doesnt work)
[//]: # (To find server revision type `.server info` command in the game chat.)

**Description**: 
sometimes it is impossible to see a night left druid in shadowmeld even when u are standing right on top of them, an aoe spell is then needed to remove their stealth effect when it should be easily visible. shadowmeld should not be harder to detect than regular stealth effects.
**Current behaviour**:
sometimes it is impossible to see a night left druid in shadowmeld even when u are standing right on top of them
**Expected behaviour**: 
the night elf should always be visible when player is within stealth detection range.
**Server Revision**:

**Comment by Wolffenstein** [comment]
Fixed in rev 2985.
