### ISSUE TITLE
[Raid][Karazhan] Nightbane fear out of textures

### ISSUE THREAD

**Issue by veekk** [Atlantiss/NetherwingBugtracker#5833]
**Description**: In some cases Nightbane can fear you to textures with next falling onto Karazhan 1st level entrance but inside of Karazhan ID.

**Current behaviour**: fear out of textures

**Expected behaviour**:  shouldn't

**Server Revision**: 2976

**Comment by Evolvee** [comment]
that happened on retail too, and still happens btw(got it on video from 1y ago :D)

**Comment by veekk** [comment]
retail was and it is now full of bugs :D

**Comment by Easyfraggy** [comment]
Problem is we can't reproduce this - it seems to be extremely random.

**Comment by Tereneckla** [comment]
#6355
