### ISSUE TITLE
S2 PVP cloak different stats! 

### ISSUE THREAD

**Issue by samzispheq** [Atlantiss/NetherwingBugtracker#5834]
[//]: # (Enclose links to things related to the bug using http://wowhead.com or any other TBC database.)
[//]: # (You can use screenshot ingame to visual the issue.)
[//]: # (Write your tickets according to the format:)
[//]: # ([Quest][Azuremyst Isle] Red Snapper - Very Tasty!)
[//]: # ([NPC] Magistrix Erona)
[//]: # ([Spell][Mage] Fireball)
[//]: # ([Npc][Drop] Ghostclaw Lynx)
[//]: # ([Web] Armory doesnt work)
[//]: # (To find server revision type `.server info` command in the game chat.)

**Description**: 
The S2 PVP cloaks have different stats. The melee cloak has the wrong stats! the melee cloak is "sergeant's heavy cloak" the caster one with the correct stats is "Sergeant's heavy cape" both are sold by "Brave Stonehide" in hall of legens. Could you please fix the stats on the melee cloak?
**Current behaviour**:

**Expected behaviour**: 

**Server Revision**:

**Comment by wtRCH** [comment]
https://web.archive.org/web/20070705155036/http://www.thottbot.com:80/i28377

**Comment by samzispheq** [comment]
I dont understand! why was this issue set as invalid. The cloak has still the wrong stats! it should be like this https://web.archive.org/web/20070705155036/http://www.thottbot.com:80/i28377 instead it has 93 aarmor, 24 stamina, 17 resilience, 17 crit, and 34 ap
