### ISSUE TITLE
The Tome of Divinity quest line can get broken

### ISSUE THREAD

**Issue by Catalyst1995** [Atlantiss/NetherwingBugtracker#5835]
[//]: # (Enclose links to things related to the bug using http://wowhead.com or any other TBC database.)
[//]: # (You can use screenshot ingame to visual the issue.)
[//]: # (Write your tickets according to the format:)
[//]: # ([Quest][Azuremyst Isle] Red Snapper - Very Tasty!)
[//]: # ([NPC] Magistrix Erona)
[//]: # ([Spell][Mage] Fireball)
[//]: # ([Npc][Drop] Ghostclaw Lynx)
[//]: # ([Web] Armory doesnt work)
[//]: # (To find server revision type `.server info` command in the game chat.)

**Description**: 
The Tome of Divinity quest line can get broken after resurrecting the NPC.
**Current behaviour**:
Narm Faulk (and perhaps his counterparn in Elwynn) can die before their next quest is accepted, rendering the quest line broken.
**Expected behaviour**: 
NPC should not die while the player is nearby. Even better, the Symbol of Life should remain in the backpack
**Server Revision**:

**Comment by Evolvee** [comment]
proof of that?

**Comment by danbopes** [comment]
From the wowhead comment section:
![](https://i.imgur.com/wO1oiol.png)

https://www.wowhead.com/quest=1789/the-symbol-of-life

**Comment by Evolvee** [comment]
![image](https://user-images.githubusercontent.com/1942409/59145159-4d0eb580-89e0-11e9-95cd-2e23ff82e836.png)

it works already

**Comment by Evolvee** [comment]
![image](https://user-images.githubusercontent.com/1942409/59145191-c0182c00-89e0-11e9-9312-450d2ab67ac8.png)

**Comment by danbopes** [comment]
This does work, but the quests require a prerequisite quest:
- Quest ID 1783 (For Symbol of Life ID 1789)
- Quest ID 1786 (For Symbol of Life ID 1790)

The quest can still become bugged, if they've completed 1783 or 1786, but haven't actually rezzed the guy to pick up the next quest. So, essentially these 2 quests need 2 special conditions:

For Symbol of Life 1789: If 1783 is active, OR 1783 is rewarded, and 1784 is not active AT ALL.
For Symbol of Life 1790: If 1786 is active, OR 1786 is rewarded, and 1787 is not active AT ALL.

**Comment by danbopes** [comment]
Additionally, if they delete the tome from quest ID #1641 (Item ID 6775), they should be presented with the option to get another tome of divinity from Duthorian Rall.

**Comment by danbopes** [comment]
rev 3249
