### ISSUE TITLE
[Protocol][Guilds] Roster Result limited

### ISSUE THREAD

**Issue by Caydan** [Atlantiss/NetherwingBugtracker#5837]
**Description**: 
Create a guild and invite more than 499 different characters.

**Current behaviour**:
Amount of members, which are displayed in guild roster, is limited to 499. Only the first 499 guild members, which joined the guild, are visible.

**Expected behaviour**: 
All guild members should be visible.

**Server Revision**: 2991

**Example**:
See the alliance guild "Farmland". 

20 members online on the guild roster
![image](https://user-images.githubusercontent.com/18358158/59080436-f70b1680-88e8-11e9-91a3-edfaa1e4d532.png)

54 members online when you use the who-list
![image](https://user-images.githubusercontent.com/18358158/59080460-13a74e80-88e9-11e9-892c-7ec3119014cc.png)

**Discussion/Ideas**:
For the case the guild roster is limited to 499 by client, you should think about limiting the amount of guild members.

For the case that you have limited it on purpose (e.g. to speed up the worldserver boot or to improve the server runtime performance), it would be nice if you could find a better solution. If you are interessted in a technical discussion, we can also talk on discord.

**Comment by Wolffenstein** [comment]
The client will not accept a roster packet that contains more than 500 players - that is correct. Current guild member limit is set to 1000, we won't go below that.
