### ISSUE TITLE
[misc][npc][core] npc_captured_vanguard typo

### ISSUE THREAD

**Issue by Evolvee** [Atlantiss/NetherwingBugtracker#5838]
![image](https://user-images.githubusercontent.com/1942409/59105760-f5674000-8934-11e9-99cb-83345189bd89.png)
![image](https://user-images.githubusercontent.com/1942409/59105772-fac48a80-8934-11e9-9e29-a94e663ab1f2.png)

the NPC needs to target player for this text

cpp: npc_captured_vanguard

**Comment by danbopes** [comment]
Fixed rev 3118
