### ISSUE TITLE
Weather-Beaten Journal is not dropping 

### ISSUE THREAD

**Issue by Aurush** [Atlantiss/NetherwingBugtracker#5839]
**Description**: Unable to encounter the journal while on the tbc data base has a 43% chance in Curious Crate, 11% in Heavy Supply Crate and 5% in other crates while fishing.

**Current behaviour**: After fishing over 300 crates i can safely say that on this server the weather-beaten jurnal dones't drop.

**Expected behaviour**: https://tbcdb.com/?item=34109#contained-in-item

**Server Revision**: 2993
![server revision](https://user-images.githubusercontent.com/51484915/59111110-0de15580-8949-11e9-870a-7e58aec0d537.JPG)

**Comment by Manaci** [comment]
Added in [Patch 2.3](https://wowwiki.fandom.com/wiki/Weather-Beaten_Journal)
