### ISSUE TITLE
S2 cloak wrong stats

### ISSUE THREAD

**Issue by samzispheq** [Atlantiss/NetherwingBugtracker#5841]
[//]: # (Enclose links to things related to the bug using http://wowhead.com or any other TBC database.)
[//]: # (You can use screenshot ingame to visual the issue.)
[//]: # (Write your tickets according to the format:)
[//]: # ([Quest][Azuremyst Isle] Red Snapper - Very Tasty!)
[//]: # ([NPC] Magistrix Erona)
[//]: # ([Spell][Mage] Fireball)
[//]: # ([Npc][Drop] Ghostclaw Lynx)
[//]: # ([Web] Armory doesnt work)
[//]: # (To find server revision type `.server info` command in the game chat.)

**Description**: The s2 melee cloak has the wrong stats. Sergeant's heavy cloak has the wrong stats, however, Sergeant's heavy cape (for casters) is correct. Some player's bought it during S1 with the correct stats. 

**Current behaviour**: Current cloack has 93 armor, 24 stamina, 17 resilience, 17 crit, and 34 ap

**Expected behaviour**: It should be like this https://web.archive.org/web/20070705155036/http://www.thottbot.com:80/i28377

**Server Revision**:

**Comment by SwiftieTBC** [comment]
![image](https://user-images.githubusercontent.com/36549891/59127700-480a2180-8960-11e9-8c67-2482e1e172e3.png)
Taken on the main realm , seems stats are correct. Try clearing your cache, if not lemme know which npc your buying it from so we can look further into it

**Comment by samzispheq** [comment]
I'm horde side rogue. It's "Brave Stonehide" that sells it in the hall of legends. I tried clearing cache still doesn't appear correctly and other rogues are having the same problem!

**Comment by wtRCH** [comment]
![image](https://user-images.githubusercontent.com/11255782/59131452-bf48b100-8972-11e9-87e8-002fb729580d.png)
![image](https://user-images.githubusercontent.com/11255782/59131455-c40d6500-8972-11e9-945d-bed80c2b6710.png)

**Comment by wtRCH** [comment]
@samzispheq clear your cache.

**Comment by samzispheq** [comment]
![WoWScrnShot_060819_000659](https://user-images.githubusercontent.com/51425088/59133670-6a606700-8981-11e9-8e7e-63b0df0e8eb4.jpg)
![WoWScrnShot_060819_000708](https://user-images.githubusercontent.com/51425088/59133671-6a606700-8981-11e9-9509-25f63f47f0ca.jpg)

**Comment by samzispheq** [comment]
cleared cache multiple times
and apparently im not the only rogue who ahs this problem

**Comment by samzispheq** [comment]
player* not just rogues
