### ISSUE TITLE
[Spell][Priest] Holy Fire incorrect scaling

### ISSUE THREAD

**Issue by Silbotronic** [Atlantiss/NetherwingBugtracker#5842]
[//]: # (Enclose links to things related to the bug using http://wowhead.com or any other TBC database.)
[//]: # (You can use screenshot ingame to visual the issue.)
[//]: # (Write your tickets according to the format:)
[//]: # ([Quest][Azuremyst Isle] Red Snapper - Very Tasty!)
[//]: # ([NPC] Magistrix Erona)
[//]: # ([Spell][Mage] Fireball)
[//]: # ([Npc][Drop] Ghostclaw Lynx)
[//]: # ([Web] Armory doesnt work)
[//]: # (To find server revision type `.server info` command in the game chat.)

**Description**: The spell damage coefficient for Holy Fire's direct damage is too low, though the DoT scaling is too high.

**Current behaviour**: The coefficient for the direct damage part seems to be around 75%, and the DoT is around 20% (4% per tick)

**Expected behaviour**: According to https://wowwiki.fandom.com/wiki/Spell_power_coefficient?oldid=1549180, the direct damage part should recieve about 85.71% of your spell damage before talents and the DoT about 16.5% (3.3% per tick).

**Server Revision**: 2993

**Comment by Wolffenstein** [comment]
It's already set to those values.
