### ISSUE TITLE
S2 cloak wrong stats

### ISSUE THREAD

**Issue by samzispheq** [Atlantiss/NetherwingBugtracker#5844]
[//]: # (Enclose links to things related to the bug using http://wowhead.com or any other TBC database.)
[//]: # (You can use screenshot ingame to visual the issue.)
[//]: # (Write your tickets according to the format:)
[//]: # ([Quest][Azuremyst Isle] Red Snapper - Very Tasty!)
[//]: # ([NPC] Magistrix Erona)
[//]: # ([Spell][Mage] Fireball)
[//]: # ([Npc][Drop] Ghostclaw Lynx)
[//]: # ([Web] Armory doesnt work)
[//]: # (To find server revision type `.server info` command in the game chat.)

**Description**: The s2 melee cloak has the wrong stats. Sergeant's heavy cloak has the wrong stats, however, Sergeant's heavy cape (for casters) is correct. Some player's bought it during S1 with the correct stats.

**Current behaviour**:Current cloak has 93 armor, 24 stamina, 17 resilience, 17 crit, and 34 ap
as seen in the pic 
![WoWScrnShot_060819_000659](https://user-images.githubusercontent.com/51425088/59134177-f921b380-8982-11e9-812d-19cc6ef9224d.jpg)
The heavy cape is correct though as seen in this pic 
![WoWScrnShot_060819_000708](https://user-images.githubusercontent.com/51425088/59134244-25d5cb00-8983-11e9-8ea2-5ad20fa4d332.jpg)
I've deleted my cache folder many times already and its not showing the correct stats.
I've asked many friends to check as well, they seem to have the same problem as me. So im not the only one

**Expected behaviour**: It should be like this https://web.archive.org/web/20070705155036/http://www.thottbot.com:80/i28377

**Server Revision**:

**Comment by wtRCH** [comment]
Okay, we see the problem now. It was our mistake and we are sorry for inconvenience @samzispheq .

It should get taken care of shortly! :)

**Comment by Evolvee** [comment]
it will be fixed when patch 2.1. arrives
