### ISSUE TITLE
[Engineering][Ammo][2.1] Adamantite Shells

### ISSUE THREAD

**Issue by Evolvemademedothis** [Atlantiss/NetherwingBugtracker#5846]
[//]: # (Enclose links to things related to the bug using http://wowhead.com or any other TBC database.)
[//]: # (You can use screenshot ingame to visual the issue.)
[//]: # (Write your tickets according to the format:)
[//]: # ([Quest][Azuremyst Isle] Red Snapper - Very Tasty!)
[//]: # ([NPC] Magistrix Erona)
[//]: # ([Spell][Mage] Fireball)
[//]: # ([Npc][Drop] Ghostclaw Lynx)
[//]: # ([Web] Armory doesnt work)
[//]: # (To find server revision type `.server info` command in the game chat.)

**Description**: 
Adamantite Shells are bullets made by engineers introduced in 2.1 as a crafting skill requiring 1 Elemental Blasting Powder and 2 Adamantite Bars to make a stack of 200. Later on in patch 2.3 this craft got reworked into the Adamantite Shell Machine.

Since these bullets were obtainable in patch 2.1 they should be added in one way or another into the game with the upcoming patch considering how good their DPS is.

Adamantite Shells : https://www.wowhead.com/item=23773/adamantite-shells

Adamantite Shell Machine : https://www.wowhead.com/item=34504/adamantite-shell-machine#comments

Mats for the Adamantite Shells are based on the wowhead comment stating the following:

"By Kathucka (22,355 – 4·36·177) on 2007/07/30 (Patch 2.1.3)
--
For the non-engineers/non-miners:

1 Mote of Fire +
2 Motes of Earth +
8 Adamantite Ores =

800 Adamantite Shells (4 stacks)"

From this you can deduct that the materials are Elemental Blasting Powder(Mote of Fire & Mote of Earth | Creates 4) and Adamantite Bars.
This is also in line with the earlier bullets made by engineers "Thorium Shells" which required 1 Dense Blasting Powder & 2 Thorium Bars per stack(200)

**Comment by Manaci** [comment]
Irrelevant now

**Comment by Evolvee** [comment]
Still need to fix it for futute.

**Comment by Godmatik** [comment]
Rev 4015
Still an issue - would be nice to have, or if not, just fast forward the Adamantite Shell Machine/Arrow Maker up to 2.1

**Comment by Godmatik** [comment]
The Shell Machine/Arrow Maker is fast forwarded to 2.1, making this issue obsolete
