### ISSUE TITLE
mob stucking multiple poisons 

### ISSUE THREAD

**Issue by aggelosss** [Atlantiss/NetherwingBugtracker#5848]
Hello!
i would like to report a bug at  Deatholme . i notices that the monster ''nerubis Centurion " can cast multiple stuckable poisons on me and they deal 47 dmg every 10 sec. and the duration is 2 minutes !!! thats a big problem for low level players because that ends being 160+ dmg every 10 seconds like on my case he stucked them 3 times. this is a quest for progress on : [War on Deatholme]
thank you for your time and i wish you best luck :)

![WoWScrnShot_060819_105507](https://user-images.githubusercontent.com/51505050/59144305-c2798680-89de-11e9-93b1-acca76942483.jpg)

**Comment by Drayo** [comment]
Yeah, this is still the case. 

- One single mob won't put it on twice, but it stacks when you pull different mobs back to back.

150 damage every 10 seconds for 2 minutes is brutal at that level.

**Comment by Tereneckla** [comment]
Same debuff from different entities stack. That's just normal behaviour
