### ISSUE TITLE
2.1 PTR - Wrong stats on Fang of the Leviathan

### ISSUE THREAD

**Issue by Grookshank** [Atlantiss/NetherwingBugtracker#5849]
Those are the stats on the current 2.1 PTR. Whatever the correct stats are, these are not.
![grafik](https://user-images.githubusercontent.com/9802675/59145762-9bc04d80-89e8-11e9-8979-0dfe5070118c.png)

**Comment by Azalen** [comment]
It is correct but missing the 209 spellpower.
(https://web.archive.org/web/20070825042942/http://www.thottbot.com/i30095)
#5829

**Comment by SwiftieTBC** [comment]
Submitted a fix should be live on the PTR soon
