### ISSUE TITLE
Enemy channeled ability dealing no damage when moving out of line of sight (LoS)

### ISSUE THREAD

**Issue by Terefinz** [Atlantiss/NetherwingBugtracker#585]
**Description**: Involves either [NPC] Felendren the Banished specifically or potentially a bug to channeled abilities in general, in this case [Spell][NPC] Mind Flay 

**Current behaviour**: When moving out of Line of Sight of the NPC as he channels Mind Flay, sometimes damage is taken, sometimes not. This has happened more than one time as I've tested it on this specific mob around a pillar. To replicate, simply pull the mob and run tightly around a pillar. Video provided for example: https://streamable.com/sba21

While this obviously is not game breaking in this situation, I could see it being a problem in a different situation (in an arena for example, if an enemy is chasing you around a pillar closely and uses a channel ability and it ends up doing nothing).

**Expected behaviour**: If an enemy NPC or player begins to channel a spell on you, the channeling effect should work even if you move out of line of sight. This should apply in all situations (except if you run out of range), not just some of the time.

**Server Revision**: 2050

**Comment by Tereneckla** [comment]
Fixed
