### ISSUE TITLE
[NPC] Jaedenar Adept Spells Hit for Too Much

### ISSUE THREAD

**Issue by RemaniX** [Atlantiss/NetherwingBugtracker#5850]
[//]: # (Enclose links to things related to the bug using http://wowhead.com or any other TBC database.)
[//]: # (You can use screenshot ingame to visual the issue.)
[//]: # (Write your tickets according to the format:)
[//]: # ([Quest][Azuremyst Isle] Red Snapper - Very Tasty!)
[//]: # ([NPC] Magistrix Erona)
[//]: # ([Spell][Mage] Fireball)
[//]: # ([Npc][Drop] Ghostclaw Lynx)
[//]: # ([Web] Armory doesnt work)
[//]: # (To find server revision type `.server info` command in the game chat.)

**Description**: 
Jaedenar Adepts that are roughly 51-52 in level located in central Felwood are using ranks of their spells that are, apparently, far beyond their level.
**Current behaviour**:
Fire Blast and Fireball are hitting for nearly 650-800dmg each time.
**Expected behaviour**: 
The amount of damage for those spells should be far less.
**Server Revision**: 
2993

**Comment by duzyizly** [comment]
From joana's 1-60 speedrun vanilla

https://www.youtube.com/watch?v=Iis-scUq9bg&feature=youtu.be&list=PL49Ga_-r7iKkxrbckm9CkUhWzxqrOnw-n&t=1543

here hits pet for exact 223 (twice).

https://youtu.be/Iis-scUq9bg?list=PL49Ga_-r7iKkxrbckm9CkUhWzxqrOnw-n&t=1690

hits player for 311 and 273.

**Comment by duzyizly** [comment]
rev 3371, im 6 level ahead adept 58 - 52, my resistances are 0.

![WoWScrnShot_051720_171322](https://user-images.githubusercontent.com/43931626/82152505-fb161700-9861-11ea-876b-6a33c0cf8dbd.jpg)

**Comment by Wolffenstein** [comment]
Fixed in rev 3383.
