### ISSUE TITLE
mining nodes in felwood empty

### ISSUE THREAD

**Issue by alxmke** [Atlantiss/NetherwingBugtracker#5851]
[//]: # (Enclose links to things related to the bug using http://wowhead.com or any other TBC database.)
[//]: # (You can use screenshot ingame to visual the issue.)
[//]: # (Write your tickets according to the format:)
[//]: # ([Quest][Azuremyst Isle] Red Snapper - Very Tasty!)
[//]: # ([NPC] Magistrix Erona)
[//]: # ([Spell][Mage] Fireball)
[//]: # ([Npc][Drop] Ghostclaw Lynx)
[//]: # ([Web] Armory doesnt work)
[//]: # (To find server revision type `.server info` command in the game chat.)

**Description**: 
Many/most mining nodes in Felwood not populated with ores.

**Current behaviour**:
No loot within node; not disappearing.
https://i.imgur.com/AqTCr03.png

**Expected behaviour**: 
Having ores and then disappearing (ores between 2-4, percentage chance for rare gems)

**Server Revision**:

**Comment by Manaci** [comment]
Fixed with node rework
