### ISSUE TITLE
Stormwind Rendezvous

### ISSUE THREAD

**Issue by Dimbleglim** [Atlantiss/NetherwingBugtracker#5852]
The quest Stormwind Rendevouz (by Marshall Maxwell in Burning steppes) Is not available. This quest is a major part of the lore of human areas as well as part of the Onyxia raid chain.

The quest should be available once you have completed the Jailbreak! quest in Blackrock Depths.

https://wowwiki.fandom.com/wiki/The_Great_Masquerade_quest_chain

current rev 2993

**Comment by wtRCH** [comment]
I think It is disabled because all Level 60 raids aren't scripted. @Evolvee ?

**Comment by Evolvee** [comment]
yes
