### ISSUE TITLE
[Spell][Mage] Frost armor  debuff not affect mobs 

### ISSUE THREAD

**Issue by hesusinc** [Atlantiss/NetherwingBugtracker#5853]
**Current behaviour:**

When mob is affected with any slow debuff then frost armor does not affect mob with time between their attacks increase debuff. 

**Expected behaviour:** 

Chilled should affect mobs with time between their attacks increase 

Frost Armor
_Increases Armor by 470 and frost resistance by 12. If an enemy strikes the caster, they may have their movement slowed by 30% and **the time between their attacks increased by 25% for 5sec.** Only one type of Armor spell can be active on the Mage at any time. Lasts 30min._

Frost Armor Aura/debuff (Chilled)
_Movement slowed by 30% and time between attacks increased by 25%._

**Server Revision:** 
2993

**Comment by Hidehugo** [comment]
Bump, still not working. Relevant for both PvE and PvP since there are windows where melee mobs/players hit a mage constantly until the slow effekt goes to 1 sec and then swap with full movement speed even though there should still be a chill effect from the Ice Armor active

**Comment by Wolffenstein** [comment]
Fixed in rev 3047.
