### ISSUE TITLE
blind doesn't work in combat

### ISSUE THREAD

**Issue by iplaybk** [Atlantiss/NetherwingBugtracker#5854]
**Description:** if u use Blind as rogue (https://tbc-twinhead.twinstar.cz/?spell=2094) in combat it doesn't work .

**Current behaviour**:  Blind doesn't work in combat in combat log its just "Name casts Blind at Name" but after this happened nothing 10 times in a row. 

**Expected behaviour:** : Blind must appear on the target all the time except miss.

![1 nothing ](https://user-images.githubusercontent.com/51532486/59159883-8fb3b900-8ad8-11e9-94e8-3e7760fc272a.jpg)
![2 missed](https://user-images.githubusercontent.com/51532486/59159884-8fb3b900-8ad8-11e9-8ccf-ad5ded6e4314.jpg)
![3 nothing](https://user-images.githubusercontent.com/51532486/59159885-8fb3b900-8ad8-11e9-8aa4-fa89fcf52ba3.jpg)

**Comment by Wolffenstein** [comment]
Should be fixed now.

**Comment by iplaybk** [comment]
thank you


>Воскресенье,  9 июня 2019, 20:01 +03:00 от Wolfenstein <notifications@github.com>:
>
>Should be fixed now.
>—
>You are receiving this because you authored the thread.
>Reply to this email directly,  view it on GitHub , or  mute the thread .

-- 
Новое Письмо
