### ISSUE TITLE
MF interrupts when target have "slowing" debuff

### ISSUE THREAD

**Issue by Eithenhard** [Atlantiss/NetherwingBugtracker#5855]
[//]: # (Enclose links to things related to the bug using http://wowhead.com or any other TBC database.)
[//]: # (You can use screenshot ingame to visual the issue.)
[//]: # (Write your tickets according to the format:)
[//]: # ([Quest][Azuremyst Isle] Red Snapper - Very Tasty!)
[//]: # ([NPC] Magistrix Erona)
[//]: # ([Spell][Mage] Fireball)
[//]: # ([Npc][Drop] Ghostclaw Lynx)
[//]: # ([Web] Armory doesnt work)
[//]: # (To find server revision type `.server info` command in the game chat.)

**Description**: 
https://www.wowhead.com/spell=15407/mind-flay interrups when target have slow debuff.
**Current behaviour**:
Checked it on 24 lvl, when mage casts frostbolt, and target have "frostbolt" debuff, MF interrupting all time and doesn't affect any damage. I don't know works doest it works smooth on high lvl, just need it to know, cause it's "serious" bug for me
**Expected behaviour**: 

**Server Revision**:

**Comment by Wolffenstein** [comment]
Should be fixed now.
