### ISSUE TITLE
"You have reached the in-game cap of unique mail recipients" after faction transfer

### ISSUE THREAD

**Issue by jasonbourne109** [Atlantiss/NetherwingBugtracker#5856]
**Description**: When trying to send mail to someone, I am receiving the message "You have reached the in-game cap of unique mail recipients." I recently changed factions and have only sent mail to maybe one or two characters since my faction change. I believe this is a bug.

**Current behaviour**: Can't send mail to anyone.

**Expected behaviour**: "Unique mail recipients" should reset if a character has changed factions.

**Server Revision**: Current as of 6/9/2019

**Comment by Godmatik** [comment]
This error message is misleading but has nothing to do with faction change. All it means is that person you are sending mail to has mailbox full.
