### ISSUE TITLE
[Warlock] Pyroclasm doesn't proc.

### ISSUE THREAD

**Issue by KevinTyrrell** [Atlantiss/NetherwingBugtracker#5857]
[//]: # (Enclose links to things related to the bug using http://wowhead.com or any other TBC database.)
[//]: # (You can use screenshot ingame to visual the issue.)
[//]: # (Write your tickets according to the format:)
[//]: # ([Quest][Azuremyst Isle] Red Snapper - Very Tasty!)
[//]: # ([NPC] Magistrix Erona)
[//]: # ([Spell][Mage] Fireball)
[//]: # ([Npc][Drop] Ghostclaw Lynx)
[//]: # ([Web] Armory doesnt work)
[//]: # (To find server revision type `.server info` command in the game chat.)

**Description**: 
Repost of issue #4477 as that thread has not been addressed in over half a year.

Proclasm does not work in the slightest. No stun is applied through any of the aforementioned abilities in the talent tool-tip.

**Server Revision**: 
2993

**Comment by Zackis** [comment]
Bump. Please fix

**Comment by Wolffenstein** [comment]
The talent works now after periodic proc changes, but the chance is still low because it's divided by the number of ticks (therefore it's not 26% per tick, but rather 6.5% for Rain of Fire for example).

**Comment by KevinTyrrell** [comment]
@Wolffenstein

Is that the way it should work?
