### ISSUE TITLE
Wrekt slaves not sharing damage with their partner (in Zangarmash, Bloodscale Grounds).

### ISSUE THREAD

**Issue by alxmke** [Atlantiss/NetherwingBugtracker#5858]
[//]: # (Enclose links to things related to the bug using http://wowhead.com or any other TBC database.)
[//]: # (You can use screenshot ingame to visual the issue.)
[//]: # (Write your tickets according to the format:)
[//]: # ([Quest][Azuremyst Isle] Red Snapper - Very Tasty!)
[//]: # ([NPC] Magistrix Erona)
[//]: # ([Spell][Mage] Fireball)
[//]: # ([Npc][Drop] Ghostclaw Lynx)
[//]: # ([Web] Armory doesnt work)
[//]: # (To find server revision type `.server info` command in the game chat.)

**Description**: 
Wrekt slaves aren't sharing damage with their partner (in Zangarmash, Bloodscale Grounds).
**Current behaviour**:
Not sharing 50% damage with partner.
**Expected behaviour**: 
Sharing 50% damage with partner.
**Server Revision**:

**Comment by Tenoutoften** [comment]
They don't use [[Spell]Shared Bonds#34789](https://www.wowhead.com/spell=34789/shared-bonds)
[[Spell]Shared Bonds#34788](https://www.wowhead.com/spell=34788/shared-bonds)

I reported this in early beta
https://github.com/Atlantiss/NetherwingBugtracker/issues/2137
https://github.com/Atlantiss/NetherwingBugtracker/issues/2148

**Comment by Evolvee** [comment]
fixed
