### ISSUE TITLE
[Quest] [Burning steps]  [Extinguish the Firegut]

### ISSUE THREAD

**Issue by Broor** [Atlantiss/NetherwingBugtracker#5859]
**Description**- Slay 15 Firegut Ogre-Mages, 7 Firegut Ogres, and 7 Firegut Ogre Brutes, and return to Oralius when you are finished.

Most of the " Firegut Ogre-Mages"  i saw on the mountains were stuck together in groups of 3 in the exact same spot.

A such you cant attack or even agro them

**Comment by Evolvee** [comment]
its a bug of RP event, reported elsewhere already
