### ISSUE TITLE
Windfury weapon tells me i am to low level when i try to use it

### ISSUE THREAD

**Issue by Mobius11** [Atlantiss/NetherwingBugtracker#586]
[//]: # (Enclose links to things related to the bug using http://wowhead.com or any other TBC database.)
[//]: # (You can use screenshot ingame to visual the issue.
![wowscrnshot_092518_234527](https://user-images.githubusercontent.com/43588957/46045306-9b637900-c11d-11e8-96c8-e896ce81e90d.jpg)

[//]: # (Write your tickets according to the format:)
[//]: # ([Quest][Azuremyst Isle] Red Snapper - Very Tasty!)
[//]: # ([NPC] Magistrix Erona)
[//]: # ([windfury weapon rank1][Shaman] windfury)
[//]: # ([Npc][Drop] Ghostclaw Lynx)
[//]: # ([Web] Armory doesnt work)

**Description**: 
when i click windfury weapon i get the msg target is too  low level
**Current behaviour**:

**Expected behaviour**: 

**Server Revision**:

**Comment by Easyfraggy** [comment]
Same issue as https://github.com/Atlantiss/NetherwingBugtracker/issues/403 ?

**Comment by Mobius11** [comment]
ye same bug just whit windfury it looks like

**Comment by Wolffenstein** [comment]
Fixed in rev 2078.
