### ISSUE TITLE
Arena Voucher bugged

### ISSUE THREAD

**Issue by bc003** [Atlantiss/NetherwingBugtracker#5860]
[//]: # (Enclose links to things related to the bug using http://wowhead.com or any other TBC database.)
[//]: # (You can use screenshot ingame to visual the issue.)
[//]: # (Write your tickets according to the format:)
[//]: # ([Quest][Azuremyst Isle] Red Snapper - Very Tasty!)
[//]: # ([NPC] Magistrix Erona)
[//]: # ([Spell][Mage] Fireball)
[//]: # ([Npc][Drop] Ghostclaw Lynx)
[//]: # ([Web] Armory doesnt work)
[//]: # (To find server revision type `.server info` command in the game chat.)

**Description**: 
hey i bought a 2v2 arena team voucher from King Dond and was in the process of getting my teammate to sign it... 

but then I got an invite for a 2v2 team from another guy just now and I hit accept by accident, now i think the voucher is wasted and when I return to King Dond he is prompting me to purchase a fresh 80g voucher to make a 2v2 team. 

Is this normal? can i get this 80g back or another fresh voucher plz

**Current behaviour**:

**Expected behaviour**: 

**Server Revision**:

**Comment by Evolvee** [comment]
pm me on discord, i will refund

the problem is that if you let the voucher inactive in your bags for several days, it will gray out
