### ISSUE TITLE
[Item] s2 healing mace gives spell damage

### ISSUE THREAD

**Issue by Frama1** [Atlantiss/NetherwingBugtracker#5861]
[//]: # (Enclose links to things related to the bug using http://wowhead.com or any other TBC database.)
[//]: # (You can use screenshot ingame to visual the issue.)
[//]: # (Write your tickets according to the format:)
[//]: # ([Quest][Azuremyst Isle] Red Snapper - Very Tasty!)
[//]: # ([NPC] Magistrix Erona)
[//]: # ([Spell][Mage] Fireball)
[//]: # ([Npc][Drop] Ghostclaw Lynx)
[//]: # ([Web] Armory doesnt work)
[//]: # (To find server revision type `.server info` command in the game chat.)

**Description**: 
s2 healing mace gives bonus spell damage, not sure about rest healing gear

Weapon https://tbc-twinhead.twinstar.cz/?item=32964
Video https://youtu.be/QeUY93IfCyo
Timeline https://atlantiss.eu/images/Unofficial_Netherwing_Timeline.jpg

**Current behaviour**:
s2 healing mace gives bonus spell damage

**Expected behaviour**: 
s2 healing weapon should not gives spell damage before 2.3 patch
**Server Revision**: 2993 [Branch: master, Hash: 7da7117b136c]

**Comment by Evolvee** [comment]
rev 2997
