### ISSUE TITLE
D.I.S.C.O Donation shop item not playing 20 second music clip.

### ISSUE THREAD

**Issue by Purplefilth** [Atlantiss/NetherwingBugtracker#5862]
https://www.wowhead.com/item=38301/d-i-s-c-o#comments
(very first comment details the item)

**Description**: The Donation Shop item D.I.S.C.O is not playing the unique music it has when activated or clicked on. The music can be heard in game with command:
/script PlaySoundFile("Sound\\Events\\UD_DiscoBallMusic.wav")

**Current behaviour**: All other aspects of the item work. The "Boing" is heard on use. The buff "listening to music" is applied. The disco light show is visible and it makes users dance when interacted with (The other faction could interact with it at Shattrath). Only the 20 second music clip is not heard during its 5 minute duration.  

**Expected behaviour**: As of Wowhead posted 2.4.1 
When activated a box with mirror ball is placed at feet (with accompaning "boing" sound) and a unique disco sound is played for about 20sec.
The mirror ball lightshow continues for as long as the box remains active.
When the box is clicked (usable by either faction), player gains a "Listening to DISCO" buff and proceeds to /dance.
Useable at any level and therefore available for twinks.

**Server Revision**:  2995 [Branch: master, Hash: 6c2139fe6040]

**Comment by caiopmartins** [comment]
How about the purple orbs? Are they working correctly Mr. Purple?

**Comment by Purplefilth** [comment]
Update: Using D.I.S.C.O is now considered a hostile action. It provokes Guards in Area 52/Shattrath and even the Concert Bruisers at 2.1 launch.
