### ISSUE TITLE
[Quest] Membership Benefits doesn't show up

### ISSUE THREAD

**Issue by Kolmarwow** [Atlantiss/NetherwingBugtracker#5863]
**Description**: 
Once you get above Neutral reputation with the Consortium you should be able to complete a quest at the start of every month called "Membership Benefits" which gives you a sack of gems, where a higher reputation level gives you a higher quality gem sack. https://wow.gamepedia.com/Membership_Benefits

**Current behaviour**:
"Gezhe" at the Consortium camp in Nagrand has never offered this quest on Netherwing so far from what I've seen. 

**Expected behaviour**: 
Should offer you this quest at the start of every month. 

**Server Revision**: 
2995

**Comment by Manaci** [comment]
It will come with 2.1

**Comment by dshgrove** [comment]
Should this be reopened?
I remember picking up my sack of gems back in June and i have been periodically going back to see if a new one is available. Today i also reached exalted reputation and it did not reward me a new sack of gems. @Evolvee 
`https://www.wowhead.com/faction=933/the-consortium#comments`

**Comment by Evolvee** [comment]
its already open in some other report

**Comment by Evolvee** [comment]
https://github.com/Atlantiss/NetherwingBugtracker/issues/6065
