### ISSUE TITLE
UBRS Rookery Egg Does Not Respawn

### ISSUE THREAD

**Issue by KevinTyrrell** [Atlantiss/NetherwingBugtracker#5864]
[//]: # (Enclose links to things related to the bug using http://wowhead.com or any other TBC database.)
[//]: # (You can use screenshot ingame to visual the issue.)
[//]: # (Write your tickets according to the format:)
[//]: # ([Quest][Azuremyst Isle] Red Snapper - Very Tasty!)
[//]: # ([NPC] Magistrix Erona)
[//]: # ([Spell][Mage] Fireball)
[//]: # ([Npc][Drop] Ghostclaw Lynx)
[//]: # ([Web] Armory doesnt work)
[//]: # (To find server revision type `.server info` command in the game chat.)

**Description**: 
Rookery egg spawn time is incorrect.

**Current behaviour**:
Rookery eggs inside UBRS do not currently respawn (or respawn timer is greater than 10 minutes).

**Expected behaviour**:
According to [WoWWiki's page of the Rookery room](https://wowwiki.fandom.com/wiki/Rookery), it claims that "It contains a few dragonspawn guarding masses of dragon whelp eggs, which hatch if anyone comes near enough. **The eggs respawn very quickly**, so trying to clear the room is pointless." This implies the spawn time is fast enough so that clearing through the room leaves spawning eggs in your path, but not spawning ontop of you. 

If any evidence can be found of a specific spawn time, that would be ideal. A simple 5 minute timer **for now** should suffice, as that's what most other servers do.

**Server Revision**: 
2995

**Comment by KevinTyrrell** [comment]
Here is a similar issue found on another project, seems to side with the WoWWiki: https://github.com/azerothcore/azerothcore-wotlk/issues/609

**Comment by Evolvee** [comment]
https://github.com/Atlantiss/NetherwingBugtracker/issues/6097
