### ISSUE TITLE
Hellfire ramparts Normal, Chest

### ISSUE THREAD

**Issue by Lazydudu** [Atlantiss/NetherwingBugtracker#5865]
[//]: # (Enclose links to things related to the bug using http://wowhead.com or any other TBC database.)
[//]: # (You can use screenshot ingame to visual the issue.)
[//]: # (Write your tickets according to the format:)
[//]: # ([Quest][Azuremyst Isle] Red Snapper - Very Tasty!)
[//]: # ([NPC] Magistrix Erona)
[//]: # ([Spell][Mage] Fireball)
[//]: # ([Npc][Drop] Ghostclaw Lynx)
[//]: # ([Web] Armory doesnt work)
[//]: # (To find server revision type `.server info` command in the game chat.)

**Description**: 
<Lazydudu>We were on the last boss of Hellfire Ramparts. We managed to kill the boss but after we opened the chest, I was the only one who could not roll for items. 
**Current behaviour**:
My guildmate Lacha has the staff that dropped and he is willing to give to me with trade, Powel the pala of the group got the belt I needed with a Greed roll.
**Expected behaviour**: 
We would like at least the transfer of the druid staff from Lacha to Lazydudu.
**Server Revision**: 
I refere also to the case #2889 which is similar to this I guess.
I do not know, but the GM Smaily to write here

**Comment by tsu-1** [comment]
Duplicate.
