### ISSUE TITLE
Bugued Deeprun Tram

### ISSUE THREAD

**Issue by lefertile** [Atlantiss/NetherwingBugtracker#5866]
Hey , 

I went with my character (Lvl 8 Priest) from Darnassus to Ironforge and I tried to take the tram to get to Stormwind but the game crashed when I went inside the tram and from then I just can't log in with this character, it keeps crashing at the end of the loading screen xD

**Comment by danbopes** [comment]
Talk to a GM on discord, or create a ticket from an alternate account. They can move your character to a safe location. If the game can't place you in a valid location when you login, you'll crash to desktop.

**Comment by lefertile** [comment]
Hey man thank you so much for the quick response ! what do I type to talk to a GM ? I forgot

**Comment by lefertile** [comment]
Its ok i got it , thanks
