### ISSUE TITLE
Falling through ground in Arathi Highlands

### ISSUE THREAD

**Issue by Sleicreider** [Atlantiss/NetherwingBugtracker#5867]
**Description**: 
Fell through the ground when using the warrior charge on a melee quest troll who was next to a tree. After a few seconds falling I got ported to my alliance camp in the middle.
Location Arathi Highlands, Witherbark Village north close to the water.
Quest: Worth Its Weight in Gold

**Server Revision**: 
2.4.3 8606 Release

**Comment by devo6969** [comment]
Seems fixed, the Troll 66.91,61.67 in Arathi Highlands is north of the Witherbark Village near a big tree close to the water.
