### ISSUE TITLE
Daze effects should not fizzle when a superior slow effect is applied.

### ISSUE THREAD

**Issue by gunzbngbng** [Atlantiss/NetherwingBugtracker#5868]
[//]: # (Enclose links to things related to the bug using http://wowhead.com or any other TBC database.)
[//]: # (You can use screenshot ingame to visual the issue.)
[//]: # (Write your tickets according to the format:)
[//]: # ([Quest][Azuremyst Isle] Red Snapper - Very Tasty!)
[//]: # ([NPC] Magistrix Erona)
[//]: # ([Spell][Mage] Fireball)
[//]: # ([Npc][Drop] Ghostclaw Lynx)
[//]: # ([Web] Armory doesnt work)
[//]: # (To find server revision type `.server info` command in the game chat.)

**Description**: Currently, if a player has a slowing effect placed on them, it will cause all other weaker slowing effects to fall off the target.

**Current behaviour**: Currently, if a player has a slowing effect placed on them, it will cause all other weaker slowing effects to fall off the target.

**Expected behaviour**: Daze effects should persist with other slowing effects, such as frost trap, even though frost trap is a greater effect.

**Server Revision**: 2995  

In this video from TBC, you can clearly see Concussive Shot persisting at the same time as Frost Trap.
https://youtu.be/FAz6E6W4T-I?t=916

**Comment by Zarant** [comment]
https://youtu.be/0iuR6CwL9rc?t=23 - You can see both concussive shot and frost trap being applied at the same time. Although concussive shot is a 50% slow, it's also a hybrid spell, since the daze component affects steady shot damage.

https://youtu.be/AvMRpsUnFvI?t=216 here you can see concussive shot coexisting with frost shock, both are 50% slows

**Comment by gunzbngbng** [comment]
I'm not sure if it's intentional, but effects like Wing Clip are causing Frost Bolt effects to fizzle as well.  This seems incorrect as some mage spells rely on "chilled" targets.  Wing Clip also falls off if a target enters a Frost Trap, though I think that's the way it was.

**Comment by Zarant** [comment]
Any debuff with more than 1 effect like frost armor and concussive shot should not be overwritten by any simple slow effect.

As far as frost trap is concerned, it should be contemplated by the slow stacking mechanic:
https://youtu.be/0iuR6CwL9rc?t=12 - Both wing clip and frost trap are active on the same target, however, wing clip has a longer duration.

https://youtu.be/4jbSgaPROH0?t=217 - Mage gets hit by wing clip and run into a frost trap, wing clip gets overwritten by the frost trap debuff. Both slows are 60% slows.

**Comment by Evolvee** [comment]
@Wolffenstein told you frost trap is exception... read my damn reports 🤦‍♂
