### ISSUE TITLE
all rogue spells have 0% baseline chance to be resisted

### ISSUE THREAD

**Issue by zmthc93** [Atlantiss/NetherwingBugtracker#5869]
[//]: # (Enclose links to things related to the bug using http://wowhead.com or any other TBC database.)
[//]: # (You can use screenshot ingame to visual the issue.)
[//]: # (Write your tickets according to the format:)
[//]: # ([Quest][Azuremyst Isle] Red Snapper - Very Tasty!)
[//]: # ([NPC] Magistrix Erona)
[//]: # ([Spell][Mage] Fireball)
[//]: # ([Npc][Drop] Ghostclaw Lynx)
[//]: # ([Web] Armory doesnt work)
[//]: # (To find server revision type `.server info` command in the game chat.)

**Description**: 
on targets that do not have any racials/ talents/ gems to increase stun resistance, it is impossible for rogue stuns to be resisted. A lvl 20 rogue can sap a lvl 70 player 3 times in a row without fail every time. Same goes for cheap shot, kidney shot and blind.  They might (not tested) be able to miss but the baseline resistance is non existant. Guessing the same applies for 70v70. Spells like druid pounce, and undoubtedly others, are also working in this manner but I havent tested any.

**Current behaviour**:
 there is currently no chance whatsoever for these to be resisted (on targets without stun resistance modifier) , regardless of lvl. 

**Expected behaviour**: 
there should be a baseline chance to resist for these spells (I have no idea what it is but on live these could be resisted occasionally).

**Server Revision**:

**Comment by Godmatik** [comment]
Innate stun resistance was never proven, even from classic no solid proof was ever provided. 

Closing.
