### ISSUE TITLE
Horde Gnomeregan Teleporter

### ISSUE THREAD

**Issue by Tinnoan** [Atlantiss/NetherwingBugtracker#587]
I can teleport to Gnomeregan from Booty Bay just fine, but when I try to teleport back I immediately just get teleported back to Gnomeregan again.

![screenshot 2018-09-25 23 56 46](https://user-images.githubusercontent.com/25431721/46045725-c8645b80-c11e-11e8-9c38-bceeffc3b436.png)

**Comment by Emityx** [comment]
Do you have an actual proof that you are supposed to be able to port back with this Transpolyporter? If you do, make sure you post it here.

**Comment by Tinnoan** [comment]
Well it does teleport me back, it just teleports me to booty bay and then immediately back to Gnomeregan again.

**Comment by wtRCH** [comment]
![image](https://user-images.githubusercontent.com/11255782/46048935-23e91600-c12c-11e8-9cf3-c14c393df658.png)

**Comment by Easyfraggy** [comment]
Retest this

**Comment by Tinnoan** [comment]
I went back and tested it again, made [this](https://streamable.com/lezdq) video of it, Tauren hitbox problem would be my guess, I think you get teleported to a place too near the teleport trigger so the big Tauren hitbox triggers it immediately upon arrival, would be my guess.

**Comment by wtRCH** [comment]
- Make players spawn a little bit further from the teleporter should solve the problem.

@pelekon

**Comment by Tereneckla** [comment]
Fixed
