### ISSUE TITLE
Shattered Rumblers near Oshu'gun mineable, but if mined and not looted, become not lootable.

### ISSUE THREAD

**Issue by alxmke** [Atlantiss/NetherwingBugtracker#5870]
[//]: # (Enclose links to things related to the bug using http://wowhead.com or any other TBC database.)
[//]: # (You can use screenshot ingame to visual the issue.)
[//]: # (Write your tickets according to the format:)
[//]: # ([Quest][Azuremyst Isle] Red Snapper - Very Tasty!)
[//]: # ([NPC] Magistrix Erona)
[//]: # ([Spell][Mage] Fireball)
[//]: # ([Npc][Drop] Ghostclaw Lynx)
[//]: # ([Web] Armory doesnt work)
[//]: # (To find server revision type `.server info` command in the game chat.)

**Description**: 
Shattered Rumblers near Oshu'gun mineable, but if mined and not looted, become not lootable.
**Current behaviour**:
Shattered Rumblers near Oshu'gun mineable, but if mined and not looted, become not lootable.
**Expected behaviour**: 
Shattered Rumblers near Oshu'gun mineable, and loot persists after mining.
**Server Revision**:

**Comment by Godmatik** [comment]
Rev 4018 - Unable to reproduce

Was able to mine the Rumblers, not loot, and it was still lootable aftewards.
