### ISSUE TITLE
Feign death in Arathi highlands (azure lode mine)

### ISSUE THREAD

**Issue by qewken** [Atlantiss/NetherwingBugtracker#5871]
[//]: # (Enclose links to things related to the bug using http://wowhead.com or any other TBC database.)
[//]: # (You can use screenshot ingame to visual the issue.)
[//]: # (Write your tickets according to the format:)
[//]: # ([Quest][Azuremyst Isle] Red Snapper - Very Tasty!)
[//]: # ([NPC] Magistrix Erona)
[//]: # ([Spell][Mage] Fireball)
[//]: # ([Npc][Drop] Ghostclaw Lynx)
[//]: # ([Web] Armory doesnt work)
[//]: # (To find server revision type `.server info` command in the game chat.)

**Description**: 
Problem with feign death

In azure lode mine (hillsbrad foothills) I got attacked even though I used feign death (it worked as intended at first, all threat dropped and the mobs targeted my pet instead). Directly after casting feign death the mobs attacked my pet (I was still in feign death) and killed it. After they killed my pet they turned to me (still in feign death) and killed me.

**Current behaviour**:

I will test it again to see what happens. No problem second time, weird :S same setup

**Expected behaviour**: 

Sometimes one of the caves will have every single mob in it attack you and you wont be able to use feign death.

**Server Revision**: 

2995
2019-06-13
content patch 203
12:00

**Comment by Zarant** [comment]
It seems fixed, I cannot reproduce what you described.
