### ISSUE TITLE
[Priest][Spell] Mind Flay spam

### ISSUE THREAD

**Issue by b15andga** [Atlantiss/NetherwingBugtracker#5872]
[//]: # (Enclose links to things related to the bug using http://wowhead.com or any other TBC database.)
[//]: # (You can use screenshot ingame to visual the issue.)
[//]: # (Write your tickets according to the format:)
[//]: # ([Quest][Azuremyst Isle] Red Snapper - Very Tasty!)
[//]: # ([NPC] Magistrix Erona)
[//]: # ([Spell][Mage] Fireball)
[//]: # ([Npc][Drop] Ghostclaw Lynx)
[//]: # ([Web] Armory doesnt work)
[//]: # (To find server revision type `.server info` command in the game chat.)

**Description**: 
Mind Flay | Rank 7 | 230 mana |20 yd range | Channeled | Mind Flay | Rank 7 | 230 mana | 20 yd range
Assault the target's mind with Shadow energy, causing 528 Shadow damage over 3 sec and slowing the target to 50% of their movement speed.

**Current behaviour**:
Can bug out to gamebreaking overlap-spam. With quick tapping of the MF button, this makes just as quick work of your mana pool while yielding 0 DPS. See below. This broken bug alone, as one of many broken spells in the Priest arsenal, makes me consider not even playing. While I have had issues with Mind Flay before, it has at least been running on the GCD, only overlapping once per GCD. This is fairly unlimited overlap.
https://www.youtube.com/watch?v=eEnAxe2u2i0
https://www.youtube.com/watch?v=dGqvcdw31Q0
Edit: Added third video for extra clarity:
https://www.youtube.com/watch?v=P_sDWLaqcQg

**Expected behaviour**: 
Shouldn't be as spammable. Should be on GCD (1.5s) and channeled. 
**Server Revision**: 
2995

**Comment by b15andga** [comment]
This bug, while the severity of it has increased recently, is not new. It was posted [here]https://github.com/Atlantiss/NetherwingBugtracker/issues/3268) in late 2018. Another relevant bug report is [this one](https://github.com/Atlantiss/NetherwingBugtracker/issues/4018).

**Comment by Wolffenstein** [comment]
Should hopefully be fixed now? Let me know if it still happens.

**Comment by b15andga** [comment]
I logged in excited to check this. At first it felt like it worked much better, and eventually it didn't. Recorded [this](https://www.youtube.com/watch?v=J4i5f3vRNd8) just now. Happy to see that you paid this issue attention and time!
