### ISSUE TITLE
The Seer's Relic is not able to be completed.

### ISSUE THREAD

**Issue by captainmervil** [Atlantiss/NetherwingBugtracker#5876]
https://www.wowhead.com/quest=9545/the-seers-relic
Quest: The Seer's Relic: the issue is with the item *seer's relic* not actually doing anything once used on Sedai's corpse and  there is also an alive Sedia stood near by.

I believe he should do some sort of animation where he walks you up the hill but he does not.

**Comment by captainmervil** [comment]
> https://www.wowhead.com/quest=9545/the-seers-relic
> Quest: The Seer's Relic: the issue is with the item _seer's relic_ not actually doing anything once used on Sedai's corpse and it there is also an alive Sedia stood near by.
> 
> I believe he should do some sort of animation where he walks you up the hill but he does not.

**Comment by captainmervil** [comment]
> https://www.wowhead.com/quest=9545/the-seers-relic
> Quest: The Seer's Relic: the issue is with the item _seer's relic_ not actually doing anything once used on Sedai's corpse and it there is also an alive Sedia stood near by.
> 
> I believe he should do some sort of animation where he walks you up the hill but he does not.

**Comment by randomuser69** [comment]
This is how the RP event is supposed to play out for reference: https://youtu.be/w-OtZr01sCA?t=27

Not sure if its fully bugged on NW, as I did catch the part of the event playing for someone else (NPC walks up hill, comes back down, and gets stabbed in back), however when I did quest the event was bugged and no RP event seemed to play (maybe I missed it)...

Whats definitely bugged is that the NPC Krun Spinebreaker (the one who stabs Sedai in the back) seems to get frozen and stand over body without moving (he needs to despawn after stabbing: https://youtu.be/w-OtZr01sCA?t=132) 

Screenshots from NW, revision 3035:
![WoWScrnShot_062319_161122](https://user-images.githubusercontent.com/51173000/60063146-de14aa80-96c9-11e9-9306-d849760450df.jpg)

![WoWScrnShot_062319_161319](https://user-images.githubusercontent.com/51173000/60063086-9ee65980-96c9-11e9-8582-a3f9fd0327b8.jpg)

**Comment by Godmatik** [comment]
Rev 4018 - did the quest twice back-to-back, works just fine, completes with no issue, and the RP matches what is shown on classic
