### ISSUE TITLE
[Quest][BadLands] Coolant Heads Prevail

### ISSUE THREAD

**Issue by Malaise80** [Atlantiss/NetherwingBugtracker#5877]
https://www.wowhead.com/quest=713/coolant-heads-prevail

Quest NPC: Lotwil Veriatus

Description: You are to bring a vial of Frost Oil to Lotwil.

What happens: I bought a vial of Frost Oil off of the bazaar and flew back, in my quest log it says complete, however, the question mark over Lotwil's head is silver and it will not allow me to turn the quest in. 

https://imagizer.imageshack.com/img924/1280/vOEEMH.jpg
https://imagizer.imageshack.com/img921/2520/iPFO7p.jpg

**Comment by leeviathan** [comment]
worked for me

**Comment by Evolvee** [comment]
try to disable addons

**Comment by Manaci** [comment]
Fixable by yourself
