### ISSUE TITLE
[Maraudon] Scepter of Celebras does not drop you from a height

### ISSUE THREAD

**Issue by KevinTyrrell** [Atlantiss/NetherwingBugtracker#5878]
[//]: # (Enclose links to things related to the bug using http://wowhead.com or any other TBC database.)
[//]: # (You can use screenshot ingame to visual the issue.)
[//]: # (Write your tickets according to the format:)
[//]: # ([Quest][Azuremyst Isle] Red Snapper - Very Tasty!)
[//]: # ([NPC] Magistrix Erona)
[//]: # ([Spell][Mage] Fireball)
[//]: # ([Npc][Drop] Ghostclaw Lynx)
[//]: # ([Web] Armory doesnt work)
[//]: # (To find server revision type `.server info` command in the game chat.)

**Description**:
The Scepter of Celebras does not teleport you to the correct Y coordinate position.

**Current behaviour**:
The Scepter of Celebras portal teleports you directly into the water.

**Expected behaviour**: 
Scepter of Celebras portal should drop you from a large height into the water.

**Server Revision**: 
2995

**Comment by ircfelix** [comment]
Source for your claim?

**Comment by mbzz88** [comment]
I also remember falling into the water at some point, but looking at the videos, I'm not too sure, maybe it's randomised somewhat?
https://youtu.be/7e6dRnHrXXs?t=5 Does not fall down into water.
https://youtu.be/EC3KlRcZoMg?t=106 Does fall into water

**Comment by KevinTyrrell** [comment]
As indicated by @mbzz88 , it that comment states `You're teleported directly to land` as of patch 2.0.

Thus, [this video evidence](https://www.youtube.com/watch?v=7e6dRnHrXXs) provided by him is what should happen when clicking the portal @Evolvee @Wolffenstein .

**Comment by Evolvee** [comment]
fixed in next rev
