### ISSUE TITLE
 [Ribbly Screwspigot] not dropping the head 100%

### ISSUE THREAD

**Issue by Qouz** [Atlantiss/NetherwingBugtracker#5879]
[//]: # (Enclose links to things related to the bug using http://wowhead.com or any other TBC database.)
[//]: # (You can use screenshot ingame to visual the issue.)
[//]: # (Write your tickets according to the format:)
[//]: # ([Quest][Azuremyst Isle] Red Snapper - Very Tasty!)
[//]: # ([NPC] Magistrix Erona)
[//]: # ([Spell][Mage] Fireball)
[//]: # ([Npc][Drop] Ghostclaw Lynx)
[//]: # ([Web] Armory doesnt work)
[//]: # (To find server revision type `.server info` command in the game chat.)

**Description**: 

**Current behaviour**:

**Expected behaviour**: 

**Server Revision**:

**Comment by Qouz** [comment]
As its said in the title this quest should have 100% drop rate but it didnt drop.

**Comment by Evolvee** [comment]
its 100%

probably your addon causes this
