### ISSUE TITLE
Stealth goes on cooldown without stealthing

### ISSUE THREAD

**Issue by AnaVomvylas** [Atlantiss/NetherwingBugtracker#5880]
**Description**:  When you have a non damaging debuff like mage ice slow and you (Rogue) stealth as soon as you get out of combat, if the debuff times out at this time as well, stealth goes on cooldown and you don't enter stealth.

**Current behaviour**: Stealth goes on cooldown without getting in stealth

**Expected behaviour**: Rogue should get in stealth regardless of non damaging debuffs timing out the moment you stealth

**Server Revision**: 2995

**Comment by Wolffenstein** [comment]
Fixed in rev 3039.
