### ISSUE TITLE
[Item] Runed copper gauntlets

### ISSUE THREAD

**Issue by Jekenius** [Atlantiss/NetherwingBugtracker#5881]
[//]: # (Enclose links to things related to the bug using http://wowhead.com or any other TBC database.)
[//]: # (You can use screenshot ingame to visual the issue.)
[//]: # (Write your tickets according to the format:)
[//]: # ([Quest][Azuremyst Isle] Red Snapper - Very Tasty!)
[//]: # ([NPC] Magistrix Erona)
[//]: # ([Spell][Mage] Fireball)
[//]: # ([Npc][Drop] Ghostclaw Lynx)
[//]: # ([Web] Armory doesnt work)
[//]: # (To find server revision type `.server info` command in the game chat.)

**Description**: 
I found that Runed copper gauntlets(low-lvl craftable mail item) doesn't give stats it supposed to.

**Current behaviour**:
I gain 0 str while wearing this item.
![WoWScrnShot_061519_231006](https://user-images.githubusercontent.com/45003723/59553770-2d6d2380-8fc4-11e9-89f1-d5ce65e7c624.jpg)
![WoWScrnShot_061519_231010](https://user-images.githubusercontent.com/45003723/59553771-2f36e700-8fc4-11e9-8812-4fc20bfbe245.jpg)

**Expected behaviour**: 
Item should give that bonus.

**Server Revision**:

**Comment by mbzz88** [comment]
Should be white with no stats
https://www.wowhead.com/item=3472/runed-copper-gauntlets#comments
"Pre 3.1

Common quality
73 Armor
Requires Level 7

3.1 Update

Uncommon quality
77 Armor
+2 Strength
Requires Level 7"
