### ISSUE TITLE
[core][conditions] Condition 20 (allow quest accept golden mark above NPC to be displayed) is not updated in the real time - requires relog or regaining visibility of the NPC

### ISSUE THREAD

**Issue by Evolvee** [Atlantiss/NetherwingBugtracker#5882]
When conditions are not met, the condition works properly - quest accept golden "!" doesnt show up above the npc.

Problem is when the condition is met after a while , when ur still in visbibility of the NPC,... the condition doesnt update in real time and the quest ! mark is still not displayed.

Todo: When a condition is met, the golden mark should become available.

**Comment by Evolvee** [comment]
![Screenshot_2020-01-03-10-41-35](https://user-images.githubusercontent.com/1942409/71716817-48936980-2e16-11ea-93e4-461f70a77bf4.png)
This indicates bigger problem @Wolffenstein

**Comment by Wolffenstein** [comment]
It depends on what the condition requires to show you the quest - not every condition is updated (or can be updated dynamically when completed)

**Comment by Godmatik** [comment]
Have not heard of this issue ever happening on Netherwing this past year - fixed at some point?

Closing.

**Comment by Evolvee** [comment]
You didnt hear about the issue because ppl who made the server couldnt use the condition due to the bug in the first place.
