### ISSUE TITLE
Black Temple Attunement Chain Bottleneck Compendium

### ISSUE THREAD

**Issue by Evolvemademedothis** [Atlantiss/NetherwingBugtracker#5884]
[//]: # (Enclose links to things related to the bug using http://wowhead.com or any other TBC database.)
[//]: # (You can use screenshot ingame to visual the issue.)
[//]: # (Write your tickets according to the format:)
[//]: # ([Quest][Azuremyst Isle] Red Snapper - Very Tasty!)
[//]: # ([NPC] Magistrix Erona)
[//]: # ([Spell][Mage] Fireball)
[//]: # ([Npc][Drop] Ghostclaw Lynx)
[//]: # ([Web] Armory doesnt work)
[//]: # (To find server revision type `.server info` command in the game chat.)

**Description**: 
1) Quest : The Secret Compromised | Quest ID 10944
2) Quest : A Distraction for Akama ] Quest ID 13429

**Current behaviour**:
1) Currently when you turn in the quest a 4 minute RP event starts and you're unable to turn in the quest if the RP event is going on, furthermore after the RP event finishes from the first turn in then the RP event starts again when a second person turns in said quest.

2) As soon as you start the event Akama doesnt properly engage with the mobs but just stands around unless you pull mobs on top of him. The quest eventually completes itself(5 ~ mins) I'm assuming that's the time required for the whole event to complete normaly. Usually there should be a cooldown on the event but presently there is none and you can keep starting multiple events all giving proper quest completion after the according amount of time has passed.
This could potentialy lead to server crashes.

**Server Revision**: 3003 (PTR)

**Comment by Evolvee** [comment]
fixed
