### ISSUE TITLE
[Dungeon] Shadow Labs, Grandmaster Vorpil -  Mass Teleport & Rain of Fire 

### ISSUE THREAD

**Issue by Firroth** [Atlantiss/NetherwingBugtracker#5886]
**Current behaviour**:
When he uses  Mass Teleport & Rain of Fire, he teleports all players to the end of the hall near Murmur door entrance. As for himself he teleports correctly on the platform where he stands before pull and uses rain of fire, but since he teleported players to other place they won't take dmg from it.
In short critically broken ability.

**Expected behaviour**: 
He should teleport himself along with players onto the platform, where he normally stands and cast rain of fire, so players will be required to move out of it.

**Comment by Tereneckla** [comment]
Fixed
