### ISSUE TITLE
[Core] /stopcasting into /cast macro only works sometimes

### ISSUE THREAD

**Issue by sifiuocz** [Atlantiss/NetherwingBugtracker#5889]
**Description**: 
I made a simple macro that looks like this:

```
 /stopcasting
 /cast Seal of Righteousness
```

And it's supposed to demonstrate buggy /stopcasting behavior. 
In this demonstration i start casting any ordinary spell that has a cast time (Holy Light for me) and then try to use this macro. The macro is only an example.

**Current behaviour**:
Currently there is a chance that this macro will issue command to stop casting after issuing command to cast Seal of Righteousness and therefore Seal of Righteousness cast fails. This bug is not limited only to Seal of Righteousness but applies to all spell cast right after using a /stopcasting command.
In combat log it looks like this:
![WoWScrnShot_061719_110307](https://user-images.githubusercontent.com/13140968/59593034-8090c480-90f1-11e9-86a2-7edfea229f1b.jpg)

Sometimes the macro works as it should. Therefore I start casting Holy Light with my character and then use the macro shown above and I stop casting Holy Light and cast Seal of Righteousness right after.
![WoWScrnShot_061719_110307_correct](https://user-images.githubusercontent.com/13140968/59593180-bf267f00-90f1-11e9-823c-508fd44cbbbe.jpg)

**Expected behaviour**: 
There is no reason for the macro not to work half of the time.

**Server Revision**: 
2995

**Comment by raethkcj** [comment]
Casting a spell gives you a GCD whether you finish the cast or not. Therefore, if you do your stopcasting macro before the GCD is finished, the /stopcasting will work, but the /cast will not. That's what (Not yet recovered.) means.

**Comment by Wolffenstein** [comment]
Can't reproduce/don't know what the hell it's about.
