### ISSUE TITLE
[Visual Glitch] Objects Disappearing

### ISSUE THREAD

**Issue by Terefinz** [Atlantiss/NetherwingBugtracker#589]
[//]: # (Enclose links to things related to the bug using http://wowhead.com or any other TBC database.)
[//]: # (You can use screenshot ingame to visual the issue.)
[//]: # (Write your tickets according to the format:)
[//]: # ([Quest][Azuremyst Isle] Red Snapper - Very Tasty!)
[//]: # ([NPC] Magistrix Erona)
[//]: # ([Spell][Mage] Fireball)
[//]: # ([Npc][Drop] Ghostclaw Lynx)
[//]: # ([Web] Armory doesnt work)

**Description**: Objects outdoors disappear when looking from inside a building. Restarting and clearing cache does not help. May be generalizable to other buildings, and if so is quite jarring while playing.

**Current behaviour**: Objects disappear depending on the angle you look at them from inside a building. See: https://streamable.com/8pd3b

**Expected behaviour**: Objects should not disappear?

**Server Revision**: 2050

**Comment by Wolffenstein** [comment]
It's a clientside thing. Need to send a mail to blizzard I'm afraid.
