### ISSUE TITLE
[Patch 2.1] [Quest] [Ogri'la] the-relics-emanation

### ISSUE THREAD

**Issue by Gedlund** [Atlantiss/NetherwingBugtracker#5890]
**Description**: 
the-relics-emanation on the PTR is currently not working as intended. 
When you start the "event" you need to click crystals in the same order as the "white beam" shows. 

**Current behaviour**:
The pattern which you have to click the crystals for is currently completely random each time with increasing difficulty by 1 crystal extra per "turn" up to 8 turns before the event finishes.

**Expected behaviour**: 
The pattern is supposed to build on what was previously shown by the "white beam", for example; if the pattern for turn 1 is red, then turn 2 should be red + 1 (yellowI) and turn 3 should then be red, yellow (+1 red) adding a new color on top of the previous ones up to 7 turns before the event finishes.

https://www.wowhead.com/quest=11080/the-relics-emanation 

**Server Revision**: 
3007

**Comment by Godmatik** [comment]
Was fixed a while ago
