### ISSUE TITLE
[Patch 2.1] [Quest] [Ogri'la] Shartuul_Transporter_(event)

### ISSUE THREAD

**Issue by Gedlund** [Atlantiss/NetherwingBugtracker#5891]
**Description**: 
Shartuul's Transporter (event) is an event that becomes available in 2.1.

The event consists of three "phases" or battles, each of which places the player in control of a different demon. Each phase has a variety of objectives and mobs to battle, but generally, the idea is to defeat your enemies without letting your demon perish.

**Current behaviour**:
The event is not working since the Felguard_Degrader mob is currently not in-game.

**Expected behaviour**: 
Event should work as following:
https://wowwiki.fandom.com/wiki/Shartuul%27s_Transporter_(event)
https://www.youtube.com/watch?v=Cvmn5NIs4b0 
**Server Revision**: 
3007

**Comment by Evolvee** [comment]
https://github.com/Atlantiss/NetherwingBugtracker/issues/6087

**Comment by bekonja** [comment]
Script it! Make Outlands Great Again!

**Comment by Shaz21rus** [comment]
not ingame atm. 3068

**Comment by Gnimish** [comment]
Still not working. 3091

**Comment by Evolvee** [comment]
scripted in next revision

**Comment by lyubomeer** [comment]
still doesn't work

**Comment by Evolvee** [comment]
not live yet

**Comment by totaemoeggerli** [comment]
still doesn't work

**Comment by Shineslippers** [comment]
2024, still doesn't work
