### ISSUE TITLE
[Class][Warlock] Soullink disappear 

### ISSUE THREAD

**Issue by veekk** [Atlantiss/NetherwingBugtracker#5892]
**Description**: Soullink buff disappear after reloading

**Current behaviour**: Soullink buff disappear after reloading

**Expected behaviour**:  Shouldn't

**Server Revision**: 2995

**Comment by duzyizly** [comment]
still a thing as rev. 3483.

**Comment by Godmatik** [comment]
Guess it was fixed at some point - soul link was still there after reload UI
