### ISSUE TITLE
[Arena S1 weapon rating] Some weapons need 1850 instead of 1800 Rating

### ISSUE THREAD

**Issue by LenN3rD** [Atlantiss/NetherwingBugtracker#5894]
[//]: # (Enclose links to things related to the bug using http://wowhead.com or any other TBC database.)
[//]: # (You can use screenshot ingame to visual the issue.)
[//]: # (Write your tickets according to the format:)
[//]: # ([Quest][Azuremyst Isle] Red Snapper - Very Tasty!)
[//]: # ([NPC] Magistrix Erona)
[//]: # ([Spell][Mage] Fireball)
[//]: # ([Npc][Drop] Ghostclaw Lynx)
[//]: # ([Web] Armory doesnt work)
[//]: # (To find server revision type `.server info` command in the game chat.)

Description: 
Twohand-Weapons need 1800 Rating and Melee-Mainhand weapons need 1850 Rating

Expected behaviour: 
Every weapon should need 1800 Rating

**Comment by Evolvee** [comment]
fixed
