### ISSUE TITLE
Portal to Stormwind on The Stair of Destiny (HP, Outland) don't work.

### ISSUE THREAD

**Issue by bluntcrumb** [Atlantiss/NetherwingBugtracker#5895]
**Description**: the portal is visible but cannot be clicked,

**Current behaviour**: the portal is visible but cannot be clicked,

**Expected behaviour**: portal should be able to be clicked to teleport you to sw

**Server Revision**:  ^

**Comment by Evolvee** [comment]
its only visual, isnt supposed to work as portal
