### ISSUE TITLE
[Black Temple] [NPC] Dragonmaw Wyrmcaller and Flying Patrol Links/Assist

### ISSUE THREAD

**Issue by Drayo** [Atlantiss/NetherwingBugtracker#5896]
[//]: # (Enclose links to things related to the bug using http://wowhead.com or any other TBC database.)
[//]: # (You can use screenshot ingame to visual the issue.)
[//]: # (Write your tickets according to the format:)
[//]: # ([Quest][Azuremyst Isle] Red Snapper - Very Tasty!)
[//]: # ([NPC] Magistrix Erona)
[//]: # ([Spell][Mage] Fireball)
[//]: # ([Npc][Drop] Ghostclaw Lynx)
[//]: # ([Web] Armory doesnt work)
[//]: # (To find server revision type `.server info` command in the game chat.)

**Description**: The Flying Patrols in Supremus Room are not exactly like they are on Retail, but they are pretty close. When I was testing on retail, all of the Wyrmcallers were linked to one of the flying Patrols.

**Current behaviour**: When you pull a Wyrmcaller the flying mobs do not engage.

**Expected behaviour**: When you pull one of the Wyrmcallers, the flying Patrol corresponding to the area should engage.

**Details**: 

_Right Side_

**Entry: 22960 Id: 12** must be assisted by **Entry: 23330 Id: 1** and Entry: **23030 Id: 1** when pulled.

**Entry: 22960 Id: 1** must be assisted by **Entry: 23330 Id: 8** when pulled.

**Entry: 22960 Id: 10** must be assisted by **Entry: 23330 Id: 4** and Entry: **23030 Id: 3** when pulled.

_Left Side_

**Entry: 22960 Id: 11** must be assisted by **Entry: 23330 Id: 7**  and **Entry: 23030 Id: 2** when pulled.

**Entry: 22960 Id: 7** and **Entry: 22960 Id: 9** do not have a corresponding Pack on NW.

**Server Revision**: 3010

**Comment by Evolvee** [comment]
fixed

**Comment by Evolvee** [comment]
![image](https://user-images.githubusercontent.com/1942409/59759387-3c87f600-9290-11e9-8bd1-c11bc9ae7b5b.png)
what does this mean?

**Comment by Evolvee** [comment]
i had to remove this fix as theres a core issue that needs to be resolved

**Comment by Drayo** [comment]
> 
> 
> ![image](https://user-images.githubusercontent.com/1942409/59759387-3c87f600-9290-11e9-8bd1-c11bc9ae7b5b.png)
> what does this mean?

On Retail there are more Dragons flying low, so there is at least one more Pack. I can't tell you exactly how many (1 or 2?) because my sub ran out. But the trash is so fast and easily done, it's prob. enough to link what is there on NW right now and be done with it. I can maybe give exact details once I sub again, but that won't be before classic.^^

**Comment by Evolvee** [comment]
@Wolffenstein fixed?

**Comment by Easyfraggy** [comment]
Seemed to work this week.
