### ISSUE TITLE
Warlocks respeccing from Demonology to Affliction get to keep their Felguards!

### ISSUE THREAD

**Issue by CodiBloom** [Atlantiss/NetherwingBugtracker#5897]
[//]: # (Enclose links to things related to the bug using http://wowhead.com or any other TBC database.)
[//]: # (You can use screenshot ingame to visual the issue.)
[//]: # (Write your tickets according to the format:)
[//]: # ([Quest][Azuremyst Isle] Red Snapper - Very Tasty!)
[//]: # ([NPC] Magistrix Erona)
[//]: # ([Spell][Mage] Fireball)
[//]: # ([Npc][Drop] Ghostclaw Lynx)
[//]: # ([Web] Armory doesnt work)
[//]: # (To find server revision type `.server info` command in the game chat.)

**Description**: 
As a warlock, when respeccing from Demonology to Affliction.
**Current behaviour**:
If you have a Felguard summoned, then respec to Affliction, the Felguard will not be dismissed and you can have a Felguard as your summoned demon while specced as Affliction. See screenshot.
![WoWScrnShot_061819_090945](https://user-images.githubusercontent.com/51506752/59657510-9b267480-91a9-11e9-86b5-805a19e07982.jpg)
**Expected behaviour**: 
When respeccing, the Felguard should despawn.
**Server Revision**: 
2995 / Hash - 5f56ebc9f234

**Comment by duzyizly** [comment]
Not a bug anymore, can be closed, rev 3483.
All these respec stuff get fixed like month ago.

![WoWScrnShot_071620_001433](https://user-images.githubusercontent.com/43931626/87605618-657bf400-c6f9-11ea-84f8-898bf75e622d.jpg)
