### ISSUE TITLE
Overlapping Slow Fall effects are ignored

### ISSUE THREAD

**Issue by KevinTyrrell** [Atlantiss/NetherwingBugtracker#5898]
[//]: # (Enclose links to things related to the bug using http://wowhead.com or any other TBC database.)
[//]: # (You can use screenshot ingame to visual the issue.)
[//]: # (Write your tickets according to the format:)
[//]: # ([Quest][Azuremyst Isle] Red Snapper - Very Tasty!)
[//]: # ([NPC] Magistrix Erona)
[//]: # ([Spell][Mage] Fireball)
[//]: # ([Npc][Drop] Ghostclaw Lynx)
[//]: # ([Web] Armory doesnt work)
[//]: # (To find server revision type `.server info` command in the game chat.)

**Description**: 
Having two or more slow fall effects at the same time does not function properly.

**Current behaviour**:
The player casts slow fall, half way through the duration he drinks [Noggenfogger Elixir] granting the "You feel light" buff. When slow fall ends, the player will resume falling at normal speed despite having an active slow fall buff (from Noggenfogger).

**Expected behaviour**: 
A player should fall slower as long as he/she has at least one slow fall buff active, regardless of order cast or the number of buffs.

**Server Revision**: 
2995

**Comment by Wolffenstein** [comment]
Fixed in rev 3029.
