### ISSUE TITLE
Battleboar Snout/Flank drop rates are 100%

### ISSUE THREAD

**Issue by dwirony** [Atlantiss/NetherwingBugtracker#59]
[//]: # (Enclose links to things related to the bug using http://wowhead.com or any other TBC database.)
[//]: # (You can use screenshot ingame to visual the issue.)
[//]: # (Write your tickets according to the format:)
[//]: # ([Quest][Azuremyst Isle] Red Snapper - Very Tasty!)
[//]: # ([NPC] Magistrix Erona)
[//]: # ([Spell][Mage] Fireball)
[//]: # ([Npc][Drop] Ghostclaw Lynx)
[//]: # ([Web] Armory doesnt work)

**Description**: Battleboar Snout and Battleboar Flank (quest items for quest "The Battleboars") are 100%  drop rate - tested on 10 mobs, 100% drop rate (deleted two from inventory to test an extra 2 times).

**Current behaviour**: Dropping 100% of the time.

**Expected behaviour**: Drop 80% of the time (going off a vanilla database, https://classicdb.ch/?item=4848#dropped-by).

Second source: http://tbc-db.tk/?npc=2954

**Server Revision**:

**Comment by toto6** [comment]
Other private server databases are not sufficient sources to change this.

**Comment by aresbrutus** [comment]
Corrected in next rev.
