### ISSUE TITLE
[UI] Automatic Quest Tracking

### ISSUE THREAD

**Issue by Xandriarn** [Atlantiss/NetherwingBugtracker#590]
[//]: # (Enclose links to things related to the bug using http://wowhead.com or any other TBC database.)
[//]: # (You can use screenshot ingame to visual the issue.)
[//]: # (Write your tickets according to the format:)
[//]: # ([Quest][Azuremyst Isle] Red Snapper - Very Tasty!)
[//]: # ([NPC] Magistrix Erona)
[//]: # ([Spell][Mage] Fireball)
[//]: # ([Npc][Drop] Ghostclaw Lynx)
[//]: # ([Web] Armory doesnt work)

**Description**: 
Enabling Automatic Quest Tracking in the UI by going to the Options menu > Quests > Checking Automatic Quest Tracking does not actually cause quests to show up in the quest tracker. A player still has to open the Quest Log and double-click the quest to get it to appear in the quest tracker. 

**Current behaviour**:
Enabling Automatic Quest Tracking in the UI by going to the Options menu > Quests > Checking Automatic Quest Tracking does not actually cause quests to show up in the quest tracker. A player still has to open the Quest Log and double-click the quest to get it to appear in the quest tracker. 

**Expected behaviour**: 
Accepting a new quest with this option checked should automatically have the quest appear in the quest tracker. 

**Server Revision**:

**Comment by Wolffenstein** [comment]
Isn't this handled entirely by the client? Not sure if I can do anything about it

**Comment by Kvel2D** [comment]
Automatic Quest Tracking starts tracking quests once you complete a single objective for them(1/10 bear asses). It never behaved the way you described.
