### ISSUE TITLE
[HUNTER] Hunter pet randomly attacking other mobs even though on Defensive.

### ISSUE THREAD

**Issue by Kaidalen** [Atlantiss/NetherwingBugtracker#5900]
[//]: # (Enclose links to things related to the bug using http://wowhead.com or any other TBC database.)
[//]: # (You can use screenshot ingame to visual the issue.)
[//]: # (Write your tickets according to the format:)
[//]: # ([Quest][Azuremyst Isle] Red Snapper - Very Tasty!)
[//]: # ([NPC] Magistrix Erona)
[//]: # ([Spell][Mage] Fireball)
[//]: # ([Npc][Drop] Ghostclaw Lynx)
[//]: # ([Web] Armory doesnt work)
[//]: # (To find server revision type `.server info` command in the game chat.)

**Description**:  Hunter pet after killing one mob, it will randomly run to another mob and attack it, even though it wasn't aggro'd or pulled. Also I noticed Hunters take more damage than other classes (PvE) while questing I have been killed from 2-3 level lower NPCs because they hit like trucks

**Current behaviour**: Hunter pet Randomly attacking non aggro'd NPCs

**Expected behaviour**:  Hunter Pet NOT running around crazy pulling mobs while on Defensive stance

**Server Revision**:  2.4.2

**Comment by Drayo** [comment]
I cannot reproduce the pet stance issue, it only attacks mobs that hit me or the pet itself.

As for the second part .... yeeeah.

Issue can probably be closed.
