### ISSUE TITLE
[Druid][Quest] Waking The Sleeper

### ISSUE THREAD

**Issue by Kuumi** [Atlantiss/NetherwingBugtracker#5902]
[//]: # (Enclose links to things related to the bug using http://wowhead.com or any other TBC database.)
[//]: # (You can use screenshot ingame to visual the issue.)
[//]: # (Write your tickets according to the format:)
[//]: # ([Quest][Azuremyst Isle] Red Snapper - Very Tasty!)
[//]: # ([NPC] Magistrix Erona)
[//]: # ([Spell][Mage] Fireball)
[//]: # ([Npc][Drop] Ghostclaw Lynx)
[//]: # ([Web] Armory doesnt work)
[//]: # (To find server revision type `.server info` command in the game chat.)

**Description**: 

Cannot talk to Clintar Dreamwalker with item in the bag in order to complete quest. No '?' rests atop his head.

**Current behaviour**:

Just a sleepy NPC with no interaction.

**Expected behaviour**: 

Be able to turn in the quest.

**Server Revision**: 

3014

**Comment by Evolvee** [comment]
hopefully fixed in next rev

**Comment by Evolvee** [comment]
(if not, reopen pls)
