### ISSUE TITLE
[Item][Quest][Magtheridon's Lair] Magtheridon's Head

### ISSUE THREAD

**Issue by Navlexx** [Atlantiss/NetherwingBugtracker#5906]
**Description**: 

Magtheridon drops 2 Heads, but only one is usable by your faction.

**Current behaviour**:

https://i.gyazo.com/de3f63a04f4b1b0a43e91f3567b0a38e.png
Using the "wrong" head as an Horde player:
https://i.gyazo.com/a71e8a0568750862d7f506b5c560df1e.png + Error in chat "That quest is not available to your race. "
2nd head works as intended for horde.

**Expected behaviour**: 

Only 1 head drop but usable by own faction

**Server Revision**: 

3014

**Comment by veekk** [comment]
confirm

**Comment by Evolvee** [comment]
fixed
