### ISSUE TITLE
"Justicar" Title PVP is not given.

### ISSUE THREAD

**Issue by natgeowild** [Atlantiss/NetherwingBugtracker#5907]
[//]: # (Enclose links to things related to the bug using http://wowhead.com or any other TBC database.)
[//]: # (You can use screenshot ingame to visual the issue.)
[//]: # (Write your tickets according to the format:)
[//]: # ([Quest][Azuremyst Isle] Red Snapper - Very Tasty!)
[//]: # ([NPC] Magistrix Erona)
[//]: # ([Spell][Mage] Fireball)
[//]: # ([Npc][Drop] Ghostclaw Lynx)
[//]: # ([Web] Armory doesnt work)
[//]: # (To find server revision type `.server info` command in the game chat.)

**Description**:  As you can see i am exalted with every BG (WSG, AB, AV) however still no title.
![Reputations - Natgeowild Netherwing](https://user-images.githubusercontent.com/51029489/59713385-66093900-9220-11e9-8daa-5358cc229f75.jpg)

![image](https://user-images.githubusercontent.com/51029489/59713759-34dd3880-9221-11e9-97e5-2e3a16bbb046.png)

**Current behaviour**:  Does not award "Justicar Title" after obtaining the exalted reputation.

**Expected behaviour**:  Should award Justicar Title" after obtaining the exalted reputation.

**Server Revision**: 3014

**Comment by NWbianca** [comment]
I am experiencing this issue as well, I would greatly appreciate it getting solved.

**Comment by Evolvee** [comment]
contact @Wolffenstein olfenstein on discord, he will give it to you manually meanwhile

**Comment by GMThunderan** [comment]
Also happens with "Conqueror" title.
