### ISSUE TITLE
Ethereum Prisons

### ISSUE THREAD

**Issue by Tyton89** [Atlantiss/NetherwingBugtracker#5908]
**Description**: Ethereum Jailors and Ethereum Prisoners

**Current behaviour**: A semi transparent mob spawns that is untargetable and does not provide rep, or a hostile mob spawns and upon death despawns within 5 seconds.

**Expected behaviour**: When unlocking a ethereum prison with its key Friendly mobs ofcertain Outland factions and grant 500 reputation with the corresponding factions. The Hostile mob should despawn at a standard rate like every other mob in the world.

**Server Revision**: 2.1

**Comment by Evolvee** [comment]
need evidence of the reputation claim ^^

**Comment by Tyton89** [comment]
https://wowwiki.fandom.com/wiki/Ethereum_Prison
![Untitled-2323](https://user-images.githubusercontent.com/44953783/59809760-aa9bdf80-92c7-11e9-90e2-be56e71e5ad3.png)

The Hostile Mobs do not provide any faction rep besides the Ethereum Prisoner ID Card they drop which is turned in to the consortium NPC for 250 Consortium reputation each.

**Comment by Tyton89** [comment]
The hostile mobs also despawn almost instantaneously upon death, so it is next to impossible to roll for items or loot their drops.

**Comment by Evolvee** [comment]
fixed
