### ISSUE TITLE
Fisherman's Feast broken

### ISSUE THREAD

**Issue by frosten73** [Atlantiss/NetherwingBugtracker#5909]
[//]: # (Enclose links to things related to the bug using http://wowhead.com or any other TBC database.)
[//]: # (You can use screenshot ingame to visual the issue.)
[//]: # (Write your tickets according to the format:)
[//]: # ([Quest][Azuremyst Isle] Red Snapper - Very Tasty!)
[//]: # ([NPC] Magistrix Erona)
[//]: # ([Spell][Mage] Fireball)
[//]: # ([Npc][Drop] Ghostclaw Lynx)
[//]: # ([Web] Armory doesnt work)
[//]: # (To find server revision type `.server info` command in the game chat.)

**Description**: 
Cooking spell "Fisherman's Feast" is not working properly, instead of getting 6 cooked fish I received just one
**Current behaviour**:
1 cooked item
**Expected behaviour**: 
6 cooked item
https://wowwiki.fandom.com/wiki/Fisherman's_Feast
**Server Revision**:

**Comment by Evolvee** [comment]
thats correct

6cooked items is in patch 2.3.0
until then only 1

**Comment by raethkcj** [comment]
If this recipe is in the pre-2.3 state then it should only require 1xGoldenbark Apple and 1xSoothing Spices. Currently it requires 5 of each but only makes one feast.

**Comment by Evolvee** [comment]
its client

**Comment by raethkcj** [comment]
Just curious, why is this recipe in pre-2.3 state while recipes for e.g. Drums of Battle are in their final state?

Pre-2.3 drums (https://wowwiki.fandom.com/wiki/Drums_of_Battle?oldid=916094) all required Primals instead of just hides. I'm guessing there are other recipes like this as well.

**Comment by Evolvee** [comment]
the recipe isnt in pre 2.3 state

the spell is

**Comment by raethkcj** [comment]
Nice, love having things in a state that never existed in TBC

**Comment by ircfelix** [comment]
ok dude, if you change mats to pre 2.4.3 (client version) mats, you have to pay the mats your client displays you PLUS the mats that were used pre 2.4.3 (afaik). So for example if a potion uses 1 felweed and 1 fel lotus on 2.4.3 (client) version, and it costs e.g. 5 dreaming glory and 2 fel lotus in 2.1, all you can do with the 2.4.3 client is to make it cost 5 dreaming glory, 1 felweed, 3 fel lotus (afaik).

It's a client problem.

**Comment by raethkcj** [comment]
Yes, it's a client problem, that's what I said. And it would be solved by making the entire recipe 2.4.3 instead of 2.4.3 mats and 2.1 recipe

**Comment by Evolvee** [comment]
do u have a link to recipe pre 2.3.? (the materials needed)

**Comment by raethkcj** [comment]
https://wowwiki.fandom.com/wiki/Fisherman%27s_Feast?direction=prev&oldid=1129610

**Comment by Evolvee** [comment]
so it shouldnt be in the game at all rn?

**Comment by raethkcj** [comment]
?

**Comment by Evolvee** [comment]
this link isnt 2.1. ...

**Comment by raethkcj** [comment]
You asked for the recipe pre-2.3 so that's what I linked.

Literally just change the date, it goes back to 2.1:

https://wowwiki.fandom.com/wiki/Fisherman%27s_Feast?oldid=730763

**Comment by raethkcj** [comment]
Specifically it was added in 2.1.2, not 2.1.0. 

https://wow.gamepedia.com/Patch_2.1.2

>Some new cooking recipes are available from Kylene in Shattrath City.

**Comment by Evolvee** [comment]
oh ok, i have only 210 / 220 / 230 dbc, that explains it

**Comment by Evolvee** [comment]
fixed in next rev
