### ISSUE TITLE
[quest][Ogrila] Bombing Run ----- shatari skyguard quest

### ISSUE THREAD

**Issue by rangobob** [Atlantiss/NetherwingBugtracker#5910]
[//]: # (Enclose links to things related to the bug using http://wowhead.com or any other TBC database.)
[//]: # (You can use screenshot ingame to visual the issue.)
[//]: # (Write your tickets according to the format:)
[//]: # ([Quest][Azuremyst Isle] Red Snapper - Very Tasty!)
[//]: # ([NPC] Magistrix Erona)
[//]: # ([Spell][Mage] Fireball)
[//]: # ([Npc][Drop] Ghostclaw Lynx)
[//]: # ([Web] Armory doesnt work)
[//]: # (To find server revision type `.server info` command in the game chat.)

**Description**: 
The canon ball stacks should beam red when ready to be attacked, and the canons nearby those should attack you while flying, but they ain't.
**Current behaviour**:
Not getting bomb stacks destroyed, and not getting shot at.
**Expected behaviour**: 
Getting bomb stacks destroyed, and getting shot at.
**Server Revision**: 
3014

**Comment by Firroth** [comment]
Not to mention, there is a little too long reset timer... If you get 200 ppl doing this daily, with respawn timer 5min+ it would be a nightmare.

**Comment by Fazer1234** [comment]
still bugged. U cant destroy canon balls. doesnt give credit when u bomb it

**Comment by Kolmarwow** [comment]
can confirm still bugged, this heavily stifles o'grila reputation as there's a few dailies locked behind this quest.

**Comment by Dragunovka** [comment]
still bugged

**Comment by kulkan1** [comment]
Can confirm, this is putting a halt to everyone wanting to do the dailies that were just added to the game.

**Comment by Kolmarwow** [comment]
@Evolvee @Wolffenstein :hugs:

**Comment by Wolffenstein** [comment]
Fixed in rev 3040.
