### ISSUE TITLE
Cipher of Damnation bug

### ISSUE THREAD

**Issue by Zetalolxo** [Atlantiss/NetherwingBugtracker#5912]
Cipher of damnation bug... did it twice, no credit given for killing Cyrukh, even after Oronok hands over the weapons to earthmender Torlok, after the whole RP session quest still says uncompleted,  i have multiple screenshots to verify.
![CYRUKH BUG](https://user-images.githubusercontent.com/51973132/59719608-15dca780-921d-11e9-809a-a449cc1243b4.png)
![CYRUKH BUG 2](https://user-images.githubusercontent.com/51973132/59719630-242ac380-921d-11e9-80d5-2799bd9c1360.png)

**Comment by Evolvee** [comment]
because these npcs did more than 50% of the cyrukhs health pool
