### ISSUE TITLE
Netherwing Eggs yield no loot

### ISSUE THREAD

**Issue by SkulkBeaver** [Atlantiss/NetherwingBugtracker#5914]
[//]: # (Enclose links to things related to the bug using http://wowhead.com or any other TBC database.)
[//]: # (You can use screenshot ingame to visual the issue.)
[//]: # (Write your tickets according to the format:)
[//]: # ([Quest][Azuremyst Isle] Red Snapper - Very Tasty!)
[//]: # ([NPC] Magistrix Erona)
[//]: # ([Spell][Mage] Fireball)
[//]: # ([Npc][Drop] Ghostclaw Lynx)
[//]: # ([Web] Armory doesnt work)
[//]: # (To find server revision type `.server info` command in the game chat.)

**Description**: Sometimes Netherwing Eggs (which are meant to yield a Netherwing Egg that is turned in for Netherwing reputation) do not actually yield an egg.

**Current behaviour**: Occassionally the normal egg opening animation and cast bar act as intended but the loot window is empty with no egg in sight. When closed, the interactable egg vanishes giving you no chance of receiving the egg.

**Expected behaviour**: You should receive an egg 100% of the time from the interactable eggs on the ground.

**Server Revision**: 3014

**Comment by samzispheq** [comment]
I would also like to add that the eggs in blade's edge can't be looted! it should be possible to loot the eggs in blade's edge south of death's door!

**Comment by Godmatik** [comment]
Unable to reproduce - every egg I opened had an egg inside, and I never heard of anyone in the past year mentioning this on Netherwing server.

Likely fixed at some point.
