### ISSUE TITLE
[Quest][Stranglethorn Vale] Private Thorsen

### ISSUE THREAD

**Issue by m3dos** [Atlantiss/NetherwingBugtracker#5915]
[//]: # (Enclose links to things related to the bug using http://wowhead.com or any other TBC database.)
[//]: # (You can use screenshot ingame to visual the issue.)
[//]: # (Write your tickets according to the format:)
[//]: # ([Quest][Azuremyst Isle] Red Snapper - Very Tasty!)
[//]: # ([NPC] Magistrix Erona)
[//]: # ([Spell][Mage] Fireball)
[//]: # ([Npc][Drop] Ghostclaw Lynx)
[//]: # ([Web] Armory doesnt work)
[//]: # (To find server revision type `.server info` command in the game chat.)
![image](https://user-images.githubusercontent.com/12224799/59722429-80b7bf80-91d8-11e9-8fc8-8541184b5f95.png)

At level 31, Private Thorsen shows he has a quest, but when you click on him he doesn't offer one.  The yellow "!" stays above his head

Server Revision 2.1

**Comment by Tenoutoften** [comment]
https://github.com/Atlantiss/NetherwingBugtracker/issues/5534
https://github.com/Atlantiss/NetherwingBugtracker/issues/4368
https://github.com/Atlantiss/NetherwingBugtracker/issues/1137
https://github.com/Atlantiss/NetherwingBugtracker/issues/797
