### ISSUE TITLE
WC Loot Bug (Bags Full)

### ISSUE THREAD

**Issue by coolbreezes69** [Atlantiss/NetherwingBugtracker#5916]
![2](https://user-images.githubusercontent.com/51974843/59724482-0139e880-91f8-11e9-9ff1-e60c7e8af289.png)
![loot error 2](https://user-images.githubusercontent.com/51974843/59724483-0139e880-91f8-11e9-8751-bd0b171fbf41.png)

Won roll in WC (this happened twice today) and had full bags. Won loot roll and was unable to claim the item after clearing bag space.

**Comment by coolbreezes69** [comment]
![noaddons](https://user-images.githubusercontent.com/51974843/59724768-0481a400-91f9-11e9-8ca4-874d2f24523d.png)

Took off addons and still same error.

**** Was resolved by switching to Master Loot and then back to Group Loot which promted "Picking up this item will bind it to you" *******

**Comment by Godmatik** [comment]
Unable to reproduce - fixed at some point perhaps
