### ISSUE TITLE
[Quest] "The Not-So-Friendly Skies..." seems extremely unfriendly to meele

### ISSUE THREAD

**Issue by Kolmarwow** [Atlantiss/NetherwingBugtracker#5918]
**Description**: 
I'm not quite sure if this would count as a bug or a feature but doesn't hurt to throw this here just in case. 

"The Not-So-Friendly Skies..." is a daily quest for the Netherwing faction where you have to pick off mobs that fly back and forth from Dragonmaw Fortress to Netherwing Ledge. 

These mobs are called "Dragonmaw Transporters" and use ranged arrow attacks. When they're pulled they stay completely still in the sky and rain down hell on meele DPS, if you try to step back to lure them down to land they still stand still but this time seem to be evading and then they reset and fly away. 

I've tried stunning them to bring them down, which at first glance seems to work but then i find my meele attacks still cant hit them at all even though i'm practically hugging them. 

It feels practically impossible to kill 10 of these as meele, The only kills i made on my own was when i got them in literally the first second of their spawn and 1 time where i somehow managed to kite them down to land without having them evade-bug. I got the rest from an extremely helpful hunter that helped me finish since he saw how much trouble i was having (shoutout to Plushycat). 

**Server Revision**: 
3014

**Comment by Evolvee** [comment]
read wowhead comments

i made it specifically to reflect state of 2.1.

**Comment by Dollywog** [comment]
Hi Evolve.  Which comment are you referring to? Can't see any which describe the behaviour these mobs show

**Comment by Evolvee** [comment]
https://www.wowhead.com/npc=23188/dragonmaw-transporter#comments

they are cancer for melees
