### ISSUE TITLE
[Druid] Stealth cat - perfect invisibility while prowling

### ISSUE THREAD

**Issue by wowthings** [Atlantiss/NetherwingBugtracker#592]
[//]: # (Enclose links to things related to the bug using http://wowhead.com or any other TBC database.)
[//]: # (You can use screenshot ingame to visual the issue.)
[//]: # (Write your tickets according to the format:)
[//]: # ([Quest][Azuremyst Isle] Red Snapper - Very Tasty!)
[//]: # ([NPC] Magistrix Erona)
[//]: # ([Spell][Mage] Fireball)
[//]: # ([Npc][Drop] Ghostclaw Lynx)
[//]: # ([Web] Armory doesnt work)

**Description**: 
If you walk around enemies with prowl they can't see you unless you enter their collider.
**Current behaviour**:
Enemies can't see you even if you stand feet to feet in front of them.
Had 0/3 on Feral Instincs, a talent that reduces the chance of detection. Tested on 1/3 2/3 and 3/3.

Video:
https://streamable.com/qw1if

**Comment by Brasso** [comment]
Cannot reproduce on high level targets. https://gfycat.com/BetterAcclaimedChipmunk

**Comment by aresbrutus** [comment]
DM me or reply here if this can be reproduceable .
