### ISSUE TITLE
[NPC][Item] Nether Ray Fry

### ISSUE THREAD

**Issue by Tereneckla** [Atlantiss/NetherwingBugtracker#5923]
[//]: # (Enclose links to things related to the bug using http://wowhead.com or any other TBC database.)
[//]: # (You can use screenshot ingame to visual the issue.)
[//]: # (Write your tickets according to the format:)
[//]: # ([Quest][Azuremyst Isle] Red Snapper - Very Tasty!)
[//]: # ([NPC] Magistrix Erona)
[//]: # ([Spell][Mage] Fireball)
[//]: # ([Npc][Drop] Ghostclaw Lynx)
[//]: # ([Web] Armory doesnt work)
[//]: # (To find server revision type `.server info` command in the game chat.)

**Description**: The Nether Fry Ray from Exalted with Sha'tari Skyguard got added in 2.4.3
https://wowwiki.fandom.com/wiki/Patch_2.4.3
https://www.wowhead.com/item=38628/nether-ray-fry
![WoWScrnShot_061919_082507](https://user-images.githubusercontent.com/50233983/59741686-fc168100-926b-11e9-8fc9-cd2bc91944c0.jpg)

**Current behaviour**: The Nether Ray Fry is available at the Vendor.

**Expected behaviour**: The Nether Ray Fry is not available at the Vendor.

**Server Revision**: 3014

**Comment by Evolvee** [comment]
fixed
