### ISSUE TITLE
[Druid][Quest] No Mere Dream

### ISSUE THREAD

**Issue by Kolgrim** [Atlantiss/NetherwingBugtracker#5924]
[//]: # (Enclose links to things related to the bug using http://wowhead.com or any other TBC database.)
[//]: # (You can use screenshot ingame to visual the issue.)
[//]: # (Write your tickets according to the format:)
[//]: # ([Quest][Azuremyst Isle] Red Snapper - Very Tasty!)
[//]: # ([NPC] Magistrix Erona)
[//]: # ([Spell][Mage] Fireball)
[//]: # ([Npc][Drop] Ghostclaw Lynx)
[//]: # ([Web] Armory doesnt work)
[//]: # (To find server revision type `.server info` command in the game chat.)

**Description**: After completing the escort with Clintar Dreamwalker's spirit - He talks to Dreamwarden Lurosa and "Objective Complete" flashes on the top of screen. However, you cannot turn in the quest.

**Current behaviour**: Cannot interact with Dreamwarden Lurosa to turn in quest.

**Expected behaviour**: Should be able to turn in quest.

**Server Revision**: 3014

Steps Tried:
1.) Abandon and restart escort
2.) Abandon, log out, clear cache, and restart escort.

https://imgur.com/a/JN6vpFM

### UPDATE: In order to complete this you must clear cache WHILE GAME IS RUNNING. Then alt f4 and log back in. If you clear cache while game is not running then it doesn't seem to have any effect.

**Comment by Picajzla** [comment]
nah you can Alt f4 and then clear cache, doesn't matter. Just don't abandon the quest.

**Comment by Evolvee** [comment]
possibly fixed

**Comment by Evolvee** [comment]
its most likely caused by the aura that u get when accepting the escort quest ^^

i changed few things in the script but if the issue persists, simple relog should fix it
