### ISSUE TITLE
[Patch 2.1] [Quest] [Consortium] Monthly Quest "Membership Benefits"

### ISSUE THREAD

**Issue by Wookiefister** [Atlantiss/NetherwingBugtracker#5925]
[//]: # (Enclose links to things related to the bug using http://wowhead.com or any other TBC database.)
[//]: # (You can use screenshot ingame to visual the issue.)
[//]: # (Write your tickets according to the format:)
[//]: # ([Quest][Azuremyst Isle] Red Snapper - Very Tasty!)
[//]: # ([NPC] Magistrix Erona)
[//]: # ([Spell][Mage] Fireball)
[//]: # ([Npc][Drop] Ghostclaw Lynx)
[//]: # ([Web] Armory doesnt work)
[//]: # (To find server revision type `.server info` command in the game chat.)

**Description**: The monthly consortium quest "Membership Benefits" is missing. From: https://wowwiki.fandom.com/wiki/Consortium

"Upon reaching Friendly status, players are officially considered members of the Consortium and given a salary. The salary is a bag of gems at the beginning of every month, given by Gezhe at Aeris Landing. Higher reputation with the Consortium yields better and more jewels each month.

Note: Due to a bug, no gem payments were received between the expansion's release and the patch 2.1.0, where it was fixed. However, players will receive their gems by talking to Gezhe instead of through the mail. According to Blizzard poster Pavonum, there is no plan to reimburse players for missing gem payments." 

**Current behaviour**: It is not there

**Expected behaviour**: The monthly quest should have been added during patch 2.1, and you should get a bag of gems of proportional value to your reputation with the consortium. 

**Server Revision**: 3014

**Comment by Evolvee** [comment]
fixed in next rev
