### ISSUE TITLE
22274 doesnt patrol despite having all requirements filled

### ISSUE THREAD

**Issue by Evolvee** [Atlantiss/NetherwingBugtracker#5927]

**Comment by Evolvee** [comment]
same for
![image](https://user-images.githubusercontent.com/1942409/60021249-f2d54c00-9691-11e9-998f-931aa72edcc9.png)

seems like it affects all flying npcs with patrol
@Wolffenstein

**Comment by Tereneckla** [comment]
As said there, leashing disables their patrol behaviour.

**Comment by Evolvee** [comment]
u dont need to test my reports -.-
