### ISSUE TITLE
dragonmaw peon (Daily quest: A slow death)

### ISSUE THREAD

**Issue by samzispheq** [Atlantiss/NetherwingBugtracker#5929]
[//]: # (Enclose links to things related to the bug using http://wowhead.com or any other TBC database.)
[//]: # (You can use screenshot ingame to visual the issue.)
[//]: # (Write your tickets according to the format:)
[//]: # ([Quest][Azuremyst Isle] Red Snapper - Very Tasty!)
[//]: # ([NPC] Magistrix Erona)
[//]: # ([Spell][Mage] Fireball)
[//]: # ([Npc][Drop] Ghostclaw Lynx)
[//]: # ([Web] Armory doesnt work)
[//]: # (To find server revision type `.server info` command in the game chat.)

**Description**: The daily quest a slow death is not working properly. When I combine yarzill's mutton with a fel gland and peons eat it completes only 1/12.

**Current behaviour**: each mutton combined with fel gland completes 1/12

**Expected behaviour**: It should complete according to how many peons actually ate it and died. for example, if 3 peons eat it then it should complete 3/12

**Server Revision**:

**Comment by bekonja** [comment]
This is invalid. If you read quest description it even says that you need to poioson "camps" not "peons".
https://www.wowhead.com/quest=11020/a-slow-death
Reas comments, its pretty clear you need to do 12 camps.
