### ISSUE TITLE
[Spell] Blessing of MIght

### ISSUE THREAD

**Issue by Pennywise4569** [Atlantiss/NetherwingBugtracker#593]
[//]: # (Enclose links to things related to the bug using http://wowhead.com or any other TBC database.)
[//]: # (You can use screenshot ingame to visual the issue.)
[//]: # (Write your tickets according to the format:)
[//]: # ([Quest][Azuremyst Isle] Red Snapper - Very Tasty!)
[//]: # ([NPC] Magistrix Erona)
[//]: # ([Spell][Mage] Fireball)
[//]: # ([Npc][Drop] Ghostclaw Lynx)
[//]: # ([Web] Armory doesnt work)

**Description**: When you cast rank 1 of BoM, then rank 2. Remove your buff, and then repeat, your AP will infinitely stack

**Current behaviour**: You can infinitely stack AP by alternating multiple ranks of Blessing of Might, and erasing the buff, and repeating.

**Expected behaviour**: Higher rank should erase old buff, and you should not get stacking AP

**Server Revision**: 
![stackingbom](https://user-images.githubusercontent.com/43563816/46049143-6988ed00-c0f2-11e8-9893-3bee3828bb7f.PNG)

**Comment by wtRCH** [comment]
Worth checking if it's the same for other classes buffs

**Comment by Pennywise4569** [comment]
Relogging will revert the stacked AP.

**Comment by wowthings** [comment]
This happens with druids armor, cast Mark of the Wild with the same process, it only stacks armor
![wowscrnshot_092618_024134](https://user-images.githubusercontent.com/43504905/46050684-ce196b80-c135-11e8-8111-81c37c0097bf.jpg)

**Comment by mbzz88** [comment]
This is also occurring with Aspect of the Hawk

**Comment by Wolffenstein** [comment]
Fixed in rev 2067.
