### ISSUE TITLE
[Quest][Druid] Chasing the Moonstone

### ISSUE THREAD

**Issue by BezawitNW** [Atlantiss/NetherwingBugtracker#5930]
During the epic flightform quest chain, specifically "Chasing the Moonstone", the npc (Rizzle Sprysprocket) despawns immediately upon arriving at her destination so you cannot interact with her. You should be able to speak with her to gather the Southfury Moonstone to complete the quest. I also attempted to kill her (on my 2nd attempt) to see if she would drop the item and she did not. For reference this is how it should work:

https://www.youtube.com/watch?v=CCHjfiyZ25k

**Comment by BezawitNW** [comment]
Apparently on this server you have to melee her once in seal form to complete the quest. Not sure if this is intended.

**Comment by Evolvee** [comment]
https://github.com/Atlantiss/AtlantissTBCBT/issues/1491

**Comment by The14me** [comment]
Same issue + missing the speed buff's

**Comment by danbopes** [comment]
Rev 3278

**Comment by GioBego** [comment]
Karazhan realm ... speed buffs not working in this quest so it is impossible to get her

**Comment by danbopes** [comment]
What do you mean they're not working? You should be able to get them in the water: They appear as you're chasing her at random locations.

**Comment by GioBego** [comment]
they spawn but do nothing ... I suppose they should work like the one in Wasong and give me speed buff if I go through the spawned object ...

**Comment by GioBego** [comment]
5th attempt in Aquatic form did the job ... she seemd somehow slower this time ... but speed boost objects still not working!

**Comment by Godmatik** [comment]
its easier not to jump in water but instead stay on land and mount up, run past her, and then jump in water ahead and cut her off.
