### ISSUE TITLE
[Quest][skettis] Adversarial Blood[NPC] all four quest objectives not giving quest item when killed

### ISSUE THREAD

**Issue by rangobob** [Atlantiss/NetherwingBugtracker#5931]
[//]: # (Enclose links to things related to the bug using http://wowhead.com or any other TBC database.)
[//]: # (You can use screenshot ingame to visual the issue.)
[//]: # (Write your tickets according to the format:)
[//]: # ([Quest][Azuremyst Isle] Red Snapper - Very Tasty!)
[//]: # ([NPC] Magistrix Erona)
[//]: # ([Spell][Mage] Fireball)
[//]: # ([Npc][Drop] Ghostclaw Lynx)
[//]: # ([Web] Armory doesnt work)
[//]: # (To find server revision type `.server info` command in the game chat.)

**Description**: 

**Current behaviour**:

**Expected behaviour**: 

**Server Revision**:

**Comment by Wolffenstein** [comment]
Fixed in rev 3030.

**Comment by leeviathan** [comment]
I can't find any mention of how this is supposed to work, but I just killed one of the bosses and the quest item only dropped for 1 party member. Is it intended for a party of five to have to kill each boss 5 times?

**Comment by Evolvee** [comment]
fixed in next revision

**Comment by The14me** [comment]
Bugged again.

**Comment by Evolvee** [comment]
I cant even start it lul.

![image](https://user-images.githubusercontent.com/1942409/71375172-aaa1d280-25bd-11ea-9571-df331b35e7d2.png)

@Wolffenstein 😩

**Comment by Wolffenstein** [comment]
It says right there you need 10 scrolls you dumbass. The issue was fixed with loot rework.

**Comment by Evolvee** [comment]
and wtf do you think is this
![image](https://user-images.githubusercontent.com/1942409/71563857-d7ab2500-2a96-11ea-866c-1916e352df2b.png)
you dumbass.
