### ISSUE TITLE
[NPC][Spell] Aged Clefthoof should not have Hoof Stomp

### ISSUE THREAD

**Issue by raethkcj** [Atlantiss/NetherwingBugtracker#5932]
[//]: # (Enclose links to things related to the bug using http://wowhead.com or any other TBC database.)
[//]: # (You can use screenshot ingame to visual the issue.)
[//]: # (Write your tickets according to the format:)
[//]: # ([Quest][Azuremyst Isle] Red Snapper - Very Tasty!)
[//]: # ([NPC] Magistrix Erona)
[//]: # ([Spell][Mage] Fireball)
[//]: # ([Npc][Drop] Ghostclaw Lynx)
[//]: # ([Web] Armory doesnt work)
[//]: # (To find server revision type `.server info` command in the game chat.)

**Description**:
Aged Clefthoof should only have the ability Rushing Charge, but not Hoof Stomp

https://web.archive.org/web/20091217200721/http://wow.allakhazam.com/db/mob.html?wmob=17133

**Current behaviour**:
Aged Clefthoof has Hoof Stomp

**Expected behaviour**: 
Aged Clefthoof should not have Hoof Stomp

**Server Revision**: 
3014

**Comment by Evolvee** [comment]
fixed in next rev
