### ISSUE TITLE
[Quest] "Ethereum Secrets" - The prisons don't seem to respawn. 

### ISSUE THREAD

**Issue by Kolmarwow** [Atlantiss/NetherwingBugtracker#5933]
**Description**: 
Title, been flying around the prisons for about 30 mins and they haven't respawned at all. 
**Current behaviour**:
Currently looks like this
![image](https://user-images.githubusercontent.com/28187000/59789780-1a0cd180-92be-11e9-93ea-faeb04494b13.png)

**Expected behaviour**: 
Expected to look like this
![image](https://wow.zamimg.com/uploads/screenshots/normal/715017-ethereum-prisoner-i-d-catalogue.jpg)

**Server Revision**: 
3014

**Comment by goldeNjo3** [comment]
They still look like that past 15 hours

**Comment by enemy321** [comment]
Still bugged right now

**Comment by Evolvee** [comment]
fixed

**Comment by enemy321** [comment]
Doesn't seem fixed, the prisons are still bugged like in the top screenshot.

**Comment by Kolmarwow** [comment]
takes a few days for the fixes to go live, you can check if the changes are ingame through server revision. 

example: the #changelog channel on the netherwing discord says this is fixed in revision 3019 , if you type .server info ingame it says as of this comment "Server Revision: 3014". so we need to wait a bit for the fix to be applied

**Comment by The14me** [comment]
The issue is back (resetting the trigger didnt fix it too )

**Comment by Evolvee** [comment]
core issue @Wolffenstein --> more in discord history

**Comment by Evolvee** [comment]
https://github.com/Atlantiss/NetherwingBugtracker/issues/6374
