### ISSUE TITLE
[Quest] Redemption of the Ashtongue

### ISSUE THREAD

**Issue by bekonja** [Atlantiss/NetherwingBugtracker#5935]
[//]: # (Enclose links to things related to the bug using http://wowhead.com or any other TBC database.)
[//]: # (You can use screenshot ingame to visual the issue.)
[//]: # (Write your tickets according to the format:)
[//]: # ([Quest][Azuremyst Isle] Red Snapper - Very Tasty!)
[//]: # ([NPC] Magistrix Erona)
[//]: # ([Spell][Mage] Fireball)
[//]: # ([Npc][Drop] Ghostclaw Lynx)
[//]: # ([Web] Armory doesnt work)
[//]: # (To find server revision type `.server info` command in the game chat.)

**Description**: Go to BT, kill Akama.
https://db.excalibur.ws/?quest=10957

**Current behaviour**: Was in a boss room during kill, lying dead about 50-60 yards away from boss, didnt get credit for it.

**Expected behaviour**: Should give you credit in bigger radius, probably in whole room or instance.

**Server Revision**: 
3014

**Comment by Godmatik** [comment]
Can't reproduce, gave me credit no issues
