### ISSUE TITLE
[Spell][Priest] Circle of Healing

### ISSUE THREAD

**Issue by Hiraeth420** [Atlantiss/NetherwingBugtracker#5936]
**Description**: Priest ability Circle of Healing not receiving correct benefit from bonus healing

**Current behaviour**: Currently receives ~21.4% of bonus healing as it did in patch 2.0

**Expected behaviour**: Should receive ~42.8% of bonus healing. Scaling was buffed in patch 2.3.
https://wowwiki.fandom.com/wiki/Healing_comparison
https://wowwiki.fandom.com/wiki/Patch_2.3.0

**Server Revision**: 3014

**Comment by Hiraeth420** [comment]
Also found an old priest healing calculator:
http://smulan.se/priest/48554/

**Comment by gabbat** [comment]
what
