### ISSUE TITLE
Minor text issues

### ISSUE THREAD

**Issue by randomuser69** [Atlantiss/NetherwingBugtracker#5937]
[//]: # (Enclose links to things related to the bug using http://wowhead.com or any other TBC database.)
[//]: # (You can use screenshot ingame to visual the issue.)
[//]: # (Write your tickets according to the format:)
[//]: # ([Quest][Azuremyst Isle] Red Snapper - Very Tasty!)
[//]: # ([NPC] Magistrix Erona)
[//]: # ([Spell][Mage] Fireball)
[//]: # ([Npc][Drop] Ghostclaw Lynx)
[//]: # ([Web] Armory doesnt work)
[//]: # (To find server revision type `.server info` command in the game chat.)

**Description**: 
Minor text issues:

**Current behaviour**:

"::sigh::" should not have the colons " :: ::" 

![WoWScrnShot_060319_182815](https://user-images.githubusercontent.com/51173000/59815980-59e8ae80-92e8-11e9-9f1a-bb0c2712c995.jpg)

There should be no "n" after your name here "Battle hard, |name|n" 
![WoWScrnShot_060919_181445](https://user-images.githubusercontent.com/51173000/59816037-84d30280-92e8-11e9-952a-2395001ab35d.jpg)

**Comment by Evolvee** [comment]
![image](https://user-images.githubusercontent.com/1942409/59849373-bb039700-9367-11e9-8fdb-96c07577db05.png)

this is retail text, its blizzlike

**Comment by Evolvee** [comment]
the 2nd text corrected in next rev
