### ISSUE TITLE
[Title] Hand of A'dal

### ISSUE THREAD

**Issue by veekk** [Atlantiss/NetherwingBugtracker#5938]
**Description**:  wouldn't available until 2.4.0
The title Hand of A'dal was introduced in Patch 2.4.0 and was available to players who complete, or have completed, the attunement quests for Mount Hyjal (The Vials of Eternity) and Black Temple ([Medallion of Karabor]). Like Champion of the Naaru (the other attunement reward title), this will appear after the player's name, so it will appear something like this:

<Name>, Hand of A'dal

https://wowwiki.fandom.com/wiki/Hand_of_A%27dal

**Current behaviour**: available

**Expected behaviour**:  shouldn't be until 2.4.0

**Server Revision**: 3014

**Comment by Tenoutoften** [comment]
It's an intentional custom change

**Comment by veekk** [comment]
where's champion of Nauru in this case? blizzzlike it's blizzlike, isn't it?
