### ISSUE TITLE
Quest: Membership Benefits not working.

### ISSUE THREAD

**Issue by halvartbc** [Atlantiss/NetherwingBugtracker#5939]
[//]: # (Enclose links to things related to the bug using http://wowhead.com or any other TBC database.)
[//]: # (You can use screenshot ingame to visual the issue.)
[//]: # (Write your tickets according to the format:)
[//]: # ([Quest][Azuremyst Isle] Red Snapper - Very Tasty!)
[//]: # ([NPC] Magistrix Erona)
[//]: # ([Spell][Mage] Fireball)
[//]: # ([Npc][Drop] Ghostclaw Lynx)
[//]: # ([Web] Armory doesnt work)
[//]: # (To find server revision type `.server info` command in the game chat.)

**Description**: 
Monthly quest does not show up for me. Have done all the quests and have exalted reputation.
I did not do the repeatable version of 'More Chrystal Fragments' quest because it disappears after you get friendly reputation.
**Current behaviour**:
Quest does not show up.
**Expected behaviour**: 
Quest should show up once a month.
**Server Revision**:

**Comment by enemy321** [comment]
I just turned in the quest so the initial one at least works, idk if the repeating part works.

**Comment by Evolvee** [comment]
yea its not present only for exhalted

fixed in next rev
