### ISSUE TITLE
[Quest] "Dragonmaw Race: Captain Skyshatter" - Meteor target NPCs are visible

### ISSUE THREAD

**Issue by Kolmarwow** [Atlantiss/NetherwingBugtracker#5940]
**Description**: 
The final part of the "Dragonmaw Race" chain has a slight issue where you can see exactly where each meteor is going to land due targets constantly spawning called "Dragonmaw Race: Skyshatter's Target", making the race significantly easier. 
![skyshatter](https://user-images.githubusercontent.com/28187000/59864654-da55f080-9376-11e9-8516-acbdb2b408c8.png)

**Server Revision**: 
3014

**Comment by Evolvee** [comment]
fixed in next rev
