### ISSUE TITLE
[item] Botanist's Gloves of Growth incorrect stats

### ISSUE THREAD

**Issue by Zebhor** [Atlantiss/NetherwingBugtracker#5941]
**Description**: 
Botanist's Gloves of Growth have incorrect stats. 
World first kill by Nihilum on 26.05.2007(Patch 2.1.0.6692) they dropped Botanist's Gloves of Growth and Shadowmoon Destroyer's Drape

34/29 Stats are before nerf in Patch 2.4.2

1. Video: https://youtu.be/PkrjzsluP6k?t=379
2. Wowhead comment: https://www.wowhead.com/item=32328/botanists-gloves-of-growth#comments:id=328719
3. Elitist jerks info about it: http://web.archive.org/web/20080913120541/http://elitistjerks.com:80/f31/t19181-shaman_how_heal_like_pro/
![Clipboard02](https://user-images.githubusercontent.com/45159461/59865414-36297500-9389-11e9-9205-e14ade7d4b02.png)
4. World first kill screenshot : 
![gorefiend](https://user-images.githubusercontent.com/45159461/59865768-39713080-938a-11e9-936b-a680036c9987.jpg)

**Current behaviour**:
22 Stamina and 21 Intellect

**Expected behaviour**: 
34 Stamina and 29 Intellect

**Server Revision**: 
3014

**Comment by SwiftieTBC** [comment]
The stats on this item were nerfed to be in line with the new value of haste after its rework in patch 2.2. As we are playing with the post 2.2 haste value its only fair that the item remains in the state that represents this.
