### ISSUE TITLE
[Spell][Item] Item auras dispelled by form switch

### ISSUE THREAD

**Issue by xycz** [Atlantiss/NetherwingBugtracker#5942]
**Description**: 
1. Cast Moonkin form
2. Equip and use [Chain of the Twilight Owl](https://db.excalibur.ws/?item=24121) or [Eye of the Night](https://db.excalibur.ws/?item=24116)
3. Cast any other form (i.e. Cat or Bear)

**Note**: 
Seems to be related to the phasing into other forms rather than phasing out of Moonkin form since it is possible to go back into normal casting form and back to Moonkin without dispelling the item auras.

**Current behaviour**:
Dispells the aura effect created when using mentioned items.

**Expected behaviour**: 
Moonkin aura should be dispelled, NOT item auras.

**Server Revision**: 
3014

**Comment by devo6969** [comment]
This was a similar issue Fel mana potion receiving the alchemist stone 15% effect. Would work only in moonkin/tree but would not get the 15% effect in Cat/Bear. Can confirm this is still happening on the PTR

**Comment by Tereneckla** [comment]
Also happens to shamans going into Ghost Wolf

**Comment by tsuone** [comment]
@Tereneckla Those it not work only for the mentioned items or all item auras?

**Comment by Tereneckla** [comment]
Just the JC necklaces and alchemist stones.

**Comment by Wolffenstein** [comment]
Fixed in rev 3702.
