### ISSUE TITLE
[NPC]NPCs in the Sha'tari Skyguard camp die randomly

### ISSUE THREAD

**Issue by mhawkins30** [Atlantiss/NetherwingBugtracker#5943]
[//]: # (Enclose links to things related to the bug using http://wowhead.com or any other TBC database.)
[//]: # (You can use screenshot ingame to visual the issue.)
[//]: # (Write your tickets according to the format:)
[//]: # ([Quest][Azuremyst Isle] Red Snapper - Very Tasty!)
[//]: # ([NPC] Magistrix Erona)
[//]: # ([Spell][Mage] Fireball)
[//]: # ([Npc][Drop] Ghostclaw Lynx)
[//]: # ([Web] Armory doesnt work)
[//]: # (To find server revision type `.server info` command in the game chat.)

**Description**: 
I was browsing the Sha'tari Skyguard quartermaster's wares when suddenly, at around 20:17 server time on June 20, he and a bunch of other NPCs in the camp died all at once.
https://i.imgur.com/FAIpU30.jpg
https://i.imgur.com/kVfFhpe.png
**Current behaviour**:
^
**Expected behaviour**: 
These NPCs should not die randomly.
**Server Revision**: 
3014

**Comment by Imperator522** [comment]
Can anecdotally confirm. Same thing happened 6/19. Do not recall time of exact occurrence but around 7:30 PM CST

**Comment by rangobob** [comment]
I just saw it happen and what triggered it. Me playing as horde, accidently hit an alliance dude next to the quest npc in the camp, and that triggered the guards to run to the alliances rescue, but instead all the npc's died.
