### ISSUE TITLE
Singing ridge netherwing eggs cant be looted

### ISSUE THREAD

**Issue by samzispheq** [Atlantiss/NetherwingBugtracker#5944]
[//]: # (Enclose links to things related to the bug using http://wowhead.com or any other TBC database.)
[//]: # (You can use screenshot ingame to visual the issue.)
[//]: # (Write your tickets according to the format:)
[//]: # ([Quest][Azuremyst Isle] Red Snapper - Very Tasty!)
[//]: # ([NPC] Magistrix Erona)
[//]: # ([Spell][Mage] Fireball)
[//]: # ([Npc][Drop] Ghostclaw Lynx)
[//]: # ([Web] Armory doesnt work)
[//]: # (To find server revision type `.server info` command in the game chat.)

**Description**: The netherwings eggs in blade's edge singing ridge can't be looted.

**Current behaviour**: The eggs can't be looted

**Expected behaviour**: Should be able to loot them

**Server Revision**:

**Comment by Firroth** [comment]
You mean this in BEM quest category - use egg to spawn a dragonling? Or you simply think those are for netherwing rep eggs? If so those aren't for this purpose :]

**Comment by samzispheq** [comment]
oh yes i thought they were rep eggs!
