### ISSUE TITLE
[Quest] "Grim(oire) Business" - Not possible to summon the boss

### ISSUE THREAD

**Issue by Kolmarwow** [Atlantiss/NetherwingBugtracker#5946]
**Description**: 
You need 5 players to stand in each circle of fire around the area of "Vim'gol's Circle" in Blade's Edge Mountains. Standing in these circles currently does not summon the boss "Vim'gol the Vile", making it impossible to proceed through the quest chain without asking a GM to summon the boss for you.

**Server Revision**: 
3014

**Comment by Wolffenstein** [comment]
Fixed in rev 3023.
