### ISSUE TITLE
[Spell] Shared Bonds buggy

### ISSUE THREAD

**Issue by hamisto1510** [Atlantiss/NetherwingBugtracker#5947]
**Description**: 
([NPC] Dreghood Drudge),  ([Spell] Shared Bonds

**Current behaviour**:
Spell does nothing
**Expected behaviour**: 
Spell has to share the damage the caster gets
**Server Revision**: 
3014

**Comment by hamisto1510** [comment]
Ofc the Spell needs to work a nearly NPC, this was the case

**Comment by Tenoutoften** [comment]
https://github.com/Atlantiss/NetherwingBugtracker/issues/2136
