### ISSUE TITLE
[Quest][Ogrila] Guardian of the Monument [Item doesn't drop once the guardian is summoned and killed]

### ISSUE THREAD

**Issue by rangobob** [Atlantiss/NetherwingBugtracker#5948]
[//]: # (Enclose links to things related to the bug using http://wowhead.com or any other TBC database.)
[//]: # (You can use screenshot ingame to visual the issue.)
[//]: # (Write your tickets according to the format:)
[//]: # ([Quest][Azuremyst Isle] Red Snapper - Very Tasty!)
[//]: # ([NPC] Magistrix Erona)
[//]: # ([Spell][Mage] Fireball)
[//]: # ([Npc][Drop] Ghostclaw Lynx)
[//]: # ([Web] Armory doesnt work)
[//]: # (To find server revision type `.server info` command in the game chat.)

**Description**: 

**Current behaviour**:

**Expected behaviour**: 

**Server Revision**:

**Comment by Evolvee** [comment]
fixed in next rev

**Comment by rangobob** [comment]
It's not fixed, unless it is not a 100% drop chance

**Comment by Zebhor** [comment]
Killed him 2 times. First one dropped blue  Apexis Crystal, second boss nothing.
Server Revision: 3031

**Comment by Evolvee** [comment]
i guess its worth to read changelog then ^^

**Comment by rangobob** [comment]
"Fixed issue with Apexis Guardian not dropping quest item for quest "Guardian of the Monument", cleaned its loot table, script and added proper conditions."

What does that mean? is it a 100% drop rate? and in that case, why didn't i get a drop?

**Comment by rangobob** [comment]
Ohh

For 3032, and we are currently at 3031.
Thanks. Gj
