### ISSUE TITLE
[NPC] Incorrect droprates on Ethereum Prison hostile NPCs

### ISSUE THREAD

**Issue by Manaci** [Atlantiss/NetherwingBugtracker#5949]
**Description**: 
Right now all the summoned hostile NPCs from the Ethereum Prisons have a way too high droprate on blue BoPs. (NPC ID: [20783](https://db.excalibur.ws/?npc=20783), [20784](https://db.excalibur.ws/?npc=20784), [20785](https://db.excalibur.ws/?npc=20785), [20786](https://db.excalibur.ws/?npc=20786), [20788](https://db.excalibur.ws/?npc=20788), [20789](https://db.excalibur.ws/?npc=20789), [20790](https://db.excalibur.ws/?npc=20790))
**Current behaviour**:
Every single one of the 7 hostile NPCs always drop a blue BoP along with the [I.D item](https://db.excalibur.ws/?item=31957) and sometimes grey items. 
**Expected behaviour**: 
They should always drop at least 1 GREEN BoE, the [I.D item](https://db.excalibur.ws/?item=31957) and have a chance at a blue BoP (resistance gear like [this](https://db.excalibur.ws/?item=31937) and the tied blue BoP like [this](https://db.excalibur.ws/?item=31940) .
Here's the specific tied blue BoP for each:
NPC ID: [20783](https://db.excalibur.ws/?npc=20783) = ITEM ID [31557](https://db.excalibur.ws/?item=31557)
NPC ID: [20784](https://db.excalibur.ws/?npc=20784) = ITEM ID [31943](https://db.excalibur.ws/?item=31943)
NPC ID: [20785](https://db.excalibur.ws/?npc=20785) = ITEM ID [31573](https://db.excalibur.ws/?item=31573)
NPC ID: [20786](https://db.excalibur.ws/?npc=20786) = ITEM ID [31940](https://db.excalibur.ws/?item=31940)
NPC ID: [20788](https://db.excalibur.ws/?npc=20788) = ITEM ID [31565](https://db.excalibur.ws/?item=31565)
NPC ID: [20789](https://db.excalibur.ws/?npc=20789) = ITEM ID [32520](https://db.excalibur.ws/?item=32520)
NPC ID: [20790](https://db.excalibur.ws/?npc=20790) = ITEM ID [31581](https://db.excalibur.ws/?item=31581)
Then they all have a chance to drop an item in the pool of all the blue BoP resistance gear seen [here](https://db.excalibur.ws/?npc=20784), but they should also drop greens and white/grey items as said before.
Droprate should be something akin to [this](http://web.archive.org/web/20080502023258/http://wow.allakhazam.com/db/mob.html?wmob=20783) although those values might be a bit on the low side. Most reliable source though as stock databases have the at like 0.01% drop chance which is just absurd on the opposite spectrum. Here's another [proof](https://i.imgur.com/XX2yp7s.png) of the lower droprate screenshotted from an archived Allakhazam page
**Server Revision**: 
3014 (why is it still 3014?)

**Comment by Evolvee** [comment]
fixed
