### ISSUE TITLE
Rogue Combo points should remain after a missed Eviscerate.

### ISSUE THREAD

**Issue by craigsurbrook** [Atlantiss/NetherwingBugtracker#595]
Tuesday, September 25th, 2018

Description:
[Core Mechanic][Gnome start area]
A rogue will build combo points on a target, and then at some point use a finishing move. Starter rogues will use Eviscerate as their finishing move.

**Current behavior**
Sinister Strike builds combo points. When it comes time to use Eviscerate, if it "MISS"es, then the "MISS" is displayed and the combo points are removed from the target.

**Expected Behavior"
Sinister Strike builds combo points. When it comes time to use Eviscerate, it if "MISS"es, then the "MISS" is display but the combo points remain and are only removed after a successful Eviscerate.

From all my years of play, and from checking Vanilla and TBC mechanics on many private servers (I did this today), the correct form of behavior for a miss should leave the combo points on the target (and all of the other private servers do this, vanilla and TBC - note that there is nothing on the internet to say that this behavior "changed" from Vanilla to TBC, and there are no complaints out there in any old forum complaining about it; therefor, the correct behavior is to leave the combo points on the target if there is a "MISS").
In fact, the disappearing combo points were so jarring as to stand out to me immediately upon it happening.
To remove the combo points like this is such a massive, wrenching nerf, that rogues will be useless (if the removal of combo points from a miss remains). For this reason, I will discontinue trying to level and give other feedback in Open Beta until this is fixed.

**Comment by Wolffenstein** [comment]
Fixed in rev 2059.
