### ISSUE TITLE
[Item][NPC] Blade of Shahram

### ISSUE THREAD

**Issue by Tereneckla** [Atlantiss/NetherwingBugtracker#5950]
[//]: # (Enclose links to things related to the bug using http://wowhead.com or any other TBC database.)
[//]: # (You can use screenshot ingame to visual the issue.)
[//]: # (Write your tickets according to the format:)
[//]: # ([Quest][Azuremyst Isle] Red Snapper - Very Tasty!)
[//]: # ([NPC] Magistrix Erona)
[//]: # ([Spell][Mage] Fireball)
[//]: # ([Npc][Drop] Ghostclaw Lynx)
[//]: # ([Web] Armory doesnt work)
[//]: # (To find server revision type `.server info` command in the game chat.)

**Description**: The NPC spawned by the Blade of Shahram is not scripted.

**Current behaviour**: The NPC only autoattacks.

**Expected behaviour**: The NPC uses various abilities.
https://wowwiki.fandom.com/wiki/Blackblade_of_Shahram
https://www.wowhead.com/item=12592/blackblade-of-shahram#comments
https://www.youtube.com/watch?v=tZYPyCeeFpw
**Server Revision**: 3014

**Comment by Evolvee** [comment]
fixed in next rev
