### ISSUE TITLE
bugget NPC spawn in q What Came First, the Drake or the Egg?

### ISSUE THREAD

**Issue by Matombo19** [Atlantiss/NetherwingBugtracker#5951]
cannot spawn Mature Nether Drake to drop q item Mature Nether Drake Essence. there is chance to summon only forst two tipes on NPC. here is link to the q https://tbcdb.com/?quest=10609

**Comment by Evolvee** [comment]
you need to use your quest item

**Comment by Evolvee** [comment]
![image](https://user-images.githubusercontent.com/1942409/59964277-2af85580-94ff-11e9-99db-de7ad33d6ab6.png)
