### ISSUE TITLE
Water in Shadowmoon Valley being treated as lava

### ISSUE THREAD

**Issue by Kierwynn** [Atlantiss/NetherwingBugtracker#5952]
**Description**: The water in SMV at 55,27 is acting like lava

**Current behaviour**: its lava

**Expected behaviour**: its not lava

**Server Revision**: 
3014

https://www.youtube.com/watch?v=rJu5PCfLXcY
https://i.imgur.com/te5BXbj.png

**Comment by KevinTyrrell** [comment]
That area is a hotspring, essentially boiling water too hot to go in. Or at least that's the flavor the game designers put in with the steam. I'd assume the damage you take there is intentional.

**Comment by Kierwynn** [comment]
Incorrect, as you can see in the video, the lava effect only happens when you enter the water from a very specific point. if you enter the water from nearly ANY other point there is no damage incurred.

**Comment by KevinTyrrell** [comment]
@Kierwynn But does that indicate that any part of the water should burn you, or none of it should?

**Comment by Manaci** [comment]
No proof here
