### ISSUE TITLE
[Object] The Prisons at Bash'irs Landing seem to not be respawning

### ISSUE THREAD

**Issue by Kolmarwow** [Atlantiss/NetherwingBugtracker#5953]
**Description**: 
Title, basically same as the Ethereum Prisons back in Netherstorm it looks like. On the plus side, the "Stasis Chamber Alpha" at Bash'irs Landing is successfully respawning :D it's just the "Ethereum Stasis Chamber" that are scattered around the camp. 

**Server Revision**: 
3014

**Comment by Evolvee** [comment]
![image](https://user-images.githubusercontent.com/1942409/59963074-2b3c2500-94ee-11e9-97d7-4370289fe060.png)

these?

**Comment by Evolvee** [comment]
i scripted the alpha chamber earlier cuz its for a quest, thats why its respawning (changelog)

**Comment by Kolmarwow** [comment]
ah i see, yup it's those

**Comment by Evolvee** [comment]
fixed in next rev
