### ISSUE TITLE
[Spell][Priest] Prayer of Mending healing 25% of value while having Aimed shot effect up

### ISSUE THREAD

**Issue by Frama1** [Atlantiss/NetherwingBugtracker#5954]
[//]: # (Enclose links to things related to the bug using http://wowhead.com or any other TBC database.)
[//]: # (You can use screenshot ingame to visual the issue.)
[//]: # (Write your tickets according to the format:)
[//]: # ([Quest][Azuremyst Isle] Red Snapper - Very Tasty!)
[//]: # ([NPC] Magistrix Erona)al
[//]: # ([Spell][Mage] Fireball)
[//]: # ([Npc][Drop] Ghostclaw Lynxecf)
[//]: # ([Web] Armory doesnt work)
[//]: # (To find server revision type `.server info` command in the game chat.)

**Description**: 
Prayer of Mending treats less than it should while being affected by Aimed shot minus heal. Probably same issue with other minus heal effects.

Video without Aimed shot:
https://youtu.be/USIgCp-vHQU

Video with Aimed shot:

https://youtu.be/4Kus0qGA4hc

**Current behaviour**:
Prayer of Mending healing 25% of value while having Aimed shot effect up.
**Expected behaviour**: 
Prayer of Mending should heal 50% of value while having Aimed shot effect up.
**Server Revision**: 3014

**Comment by Wolffenstein** [comment]
It's an issue with all healing reduction effects interacting with PoM - essentially gets reduced twice instead of once.

**Comment by Wolffenstein** [comment]
Fixed in rev 3031.
