### ISSUE TITLE
Netherwing Egg spawn locations have smoke even when eggs are not spawned

### ISSUE THREAD

**Issue by randomuser69** [Atlantiss/NetherwingBugtracker#5955]
[//]: # (Enclose links to things related to the bug using http://wowhead.com or any other TBC database.)
[//]: # (You can use screenshot ingame to visual the issue.)
[//]: # (Write your tickets according to the format:)
[//]: # ([Quest][Azuremyst Isle] Red Snapper - Very Tasty!)
[//]: # ([NPC] Magistrix Erona)
[//]: # ([Spell][Mage] Fireball)
[//]: # ([Npc][Drop] Ghostclaw Lynx)
[//]: # ([Web] Armory doesnt work)
[//]: # (To find server revision type `.server info` command in the game chat.)

**Description**: 
Netherwing Egg spawn locations have smoke even when eggs are not spawned

**Current behaviour**:
There are smoke trails coming from invisible eggs (eggs that have not spawned): 
![WoWScrnShot_062119_185321](https://user-images.githubusercontent.com/51173000/59957908-4e25f500-946c-11e9-90c0-721526a82247.jpg)

**Expected behaviour**: 
There should be no smoke when eggs aren't there:
https://youtu.be/fzU4TOG0Z7M?t=126

**Server Revision**: 
3014

**Comment by Evolvee** [comment]
fixed in next rev
