### ISSUE TITLE
[HUNTER] Feign Death Not working as attended.

### ISSUE THREAD

**Issue by Kaidalen** [Atlantiss/NetherwingBugtracker#5958]
[//]: # (Enclose links to things related to the bug using http://wowhead.com or any other TBC database.)
[//]: # (You can use screenshot ingame to visual the issue.)
[//]: # (Write your tickets according to the format:)
[//]: # ([Quest][Azuremyst Isle] Red Snapper - Very Tasty!)
[//]: # ([NPC] Magistrix Erona)
[//]: # ([Spell][Mage] Fireball)
[//]: # ([Npc][Drop] Ghostclaw Lynx)
[//]: # ([Web] Armory doesnt work)
[//]: # (To find server revision type `.server info` command in the game chat.)

**Description**:  When using Feign Death, your character will either A) Stand there and not do what it is meant to do. B) When using Feign Death, An error will pop up saying "Resisted" this will either pop up during combat or out of combat. 

**Current behaviour**: When using Feign Death, your character will either A) Stand there and not do what it is meant to do. B) When using Feign Death, An error will pop up saying "Resisted" this will either pop up during combat or out of combat. 

**Expected behaviour**:  When Feign Death is activated, you are meant to pretend to be dead. And obviously not be resisted and lose aggro

**Server Revision**:  3031

**Comment by Manaci** [comment]
It can be resisted
