### ISSUE TITLE
[HUNTER PET] Hunter pets randomly attacking non aggro'd mobs

### ISSUE THREAD

**Issue by Kaidalen** [Atlantiss/NetherwingBugtracker#5959]
[//]: # (Enclose links to things related to the bug using http://wowhead.com or any other TBC database.)
[//]: # (You can use screenshot ingame to visual the issue.)
[//]: # (Write your tickets according to the format:)
[//]: # ([Quest][Azuremyst Isle] Red Snapper - Very Tasty!)
[//]: # ([NPC] Magistrix Erona)
[//]: # ([Spell][Mage] Fireball)
[//]: # ([Npc][Drop] Ghostclaw Lynx)
[//]: # ([Web] Armory doesnt work)
[//]: # (To find server revision type `.server info` command in the game chat.)

**Description**:  Hunter pets will aggro - non aggro enemies. Not always, its random, but i'd say 60% of the time. The pet will just run to another mob that isn't aggro'd even at Defensive mode.

**Current behaviour**: Hunter pets will aggro - non aggro enemies. Not always, its random, but i'd say 60% of the time. The pet will just run to another mob that isn't aggro'd even at Defensive mode.

**Expected behaviour**:  Hunter pets meant to attack what you choose to attack during "Defensive mode"

**Server Revision**:  3031

**Comment by shatich** [comment]
Can confirm it.

**Comment by Tereneckla** [comment]
Sound like you actually had aggressive on or accidentally clicked the pet-attack button
