### ISSUE TITLE
[Chat] "World" global channel typing bug.

### ISSUE THREAD

**Issue by Spaztick** [Atlantiss/NetherwingBugtracker#596]
**Description**: 
Typing in "world" global channel requires relog after joining.

**Current behaviour**:
Joining "world" global channel doesn't allow typing until a relog. This does not apply to other global channels created (tested china, oaiwnegoiae, and qwert).

**Expected behaviour**: 
Instant typing ability in global. Whether this is an intended feature for anti-spam and bots is unclear.

**Server Revision**: 
Not sure; I'm a shitposter not a coder.

**Comment by danbopes** [comment]
Fixed in rev 3116
