### ISSUE TITLE
[Enemies in Vanilla] Do more damage than supposed to.

### ISSUE THREAD

**Issue by Kaidalen** [Atlantiss/NetherwingBugtracker#5960]
[//]: # (Enclose links to things related to the bug using http://wowhead.com or any other TBC database.)
[//]: # (You can use screenshot ingame to visual the issue.)
[//]: # (Write your tickets according to the format:)
[//]: # ([Quest][Azuremyst Isle] Red Snapper - Very Tasty!)
[//]: # ([NPC] Magistrix Erona)
[//]: # ([Spell][Mage] Fireball)
[//]: # ([Npc][Drop] Ghostclaw Lynx)
[//]: # ([Web] Armory doesnt work)
[//]: # (To find server revision type `.server info` command in the game chat.)

**Description**:  Enemies in Vanilla hit harder than meant to

**Current behaviour**: Enemies are hitting like they are 2-3 times higher than your level even if they are your current level.

**Expected behaviour**:  Not do that.

**Server Revision**:  3031

**Comment by Evolvee** [comment]
depends from npc to npc

also any... proof/testing etc?

this report is useless otherwise
