### ISSUE TITLE
[Cursor flickering] Cursor started flickering since new update.

### ISSUE THREAD

**Issue by Kaidalen** [Atlantiss/NetherwingBugtracker#5961]
[//]: # (Enclose links to things related to the bug using http://wowhead.com or any other TBC database.)
[//]: # (You can use screenshot ingame to visual the issue.)
[//]: # (Write your tickets according to the format:)
[//]: # ([Quest][Azuremyst Isle] Red Snapper - Very Tasty!)
[//]: # ([NPC] Magistrix Erona)
[//]: # ([Spell][Mage] Fireball)
[//]: # ([Npc][Drop] Ghostclaw Lynx)
[//]: # ([Web] Armory doesnt work)
[//]: # (To find server revision type `.server info` command in the game chat.)

**Description**:  In-Game cursor slightly flickers when moving since new patch. Tried downgrading drivers, updating them. Nothing seems to work.

**Current behaviour**: In-Game cursor slightly flickers when moving since new patch

**Expected behaviour**:  Not Flicker.

**Server Revision**:  3031

**Comment by Evolvee** [comment]
not serverside

**Comment by Evolvee** [comment]
maybe u have enabled touched and accidentaly use it?
