### ISSUE TITLE
[Hunter Pet] Gets hungry faster than usual.

### ISSUE THREAD

**Issue by Kaidalen** [Atlantiss/NetherwingBugtracker#5962]
[//]: # (Enclose links to things related to the bug using http://wowhead.com or any other TBC database.)
[//]: # (You can use screenshot ingame to visual the issue.)
[//]: # (Write your tickets according to the format:)
[//]: # ([Quest][Azuremyst Isle] Red Snapper - Very Tasty!)
[//]: # ([NPC] Magistrix Erona)
[//]: # ([Spell][Mage] Fireball)
[//]: # ([Npc][Drop] Ghostclaw Lynx)
[//]: # ([Web] Armory doesnt work)
[//]: # (To find server revision type `.server info` command in the game chat.)

**Description**:  Hunter pets, new, old etc get hungry faster than I remember from retail vanilla

**Current behaviour**: Pets need food faster than usual.

**Expected behaviour**:  Pets shouldn't need food so quickly after being happy

**Server Revision**:  3031

**Comment by Tereneckla** [comment]
I have a hunch on from 14 years ago is not enough
