### ISSUE TITLE
[Hunter pets] Some if not most pets don't have abilities. And just have auto attack

### ISSUE THREAD

**Issue by Kaidalen** [Atlantiss/NetherwingBugtracker#5963]
[//]: # (Enclose links to things related to the bug using http://wowhead.com or any other TBC database.)
[//]: # (You can use screenshot ingame to visual the issue.)
[//]: # (Write your tickets according to the format:)
[//]: # ([Quest][Azuremyst Isle] Red Snapper - Very Tasty!)
[//]: # ([NPC] Magistrix Erona)
[//]: # ([Spell][Mage] Fireball)
[//]: # ([Npc][Drop] Ghostclaw Lynx)
[//]: # ([Web] Armory doesnt work)
[//]: # (To find server revision type `.server info` command in the game chat.)

**Description**:  Pets. Like Panthers, And most pets in STV don't have abilities like bite, scratch etc

**Current behaviour**: Some pets missing abilities that can't be bought. 

**Expected behaviour**:  Pets should have Abilities.

**Server Revision**:  3031

**Comment by gunzbngbng** [comment]
You need to tame a pet that has the ability and have it use it repeatedly until you get the chat message that you have learned the pet attack.

Then you can teach it to other pets.

Look up a tbc cache of petopia, it will have all the information you require.
