### ISSUE TITLE
[Mail Box] When you buy something from Auction House It doesn't show in your Mail box.

### ISSUE THREAD

**Issue by Kaidalen** [Atlantiss/NetherwingBugtracker#5964]
[//]: # (Enclose links to things related to the bug using http://wowhead.com or any other TBC database.)
[//]: # (You can use screenshot ingame to visual the issue.)
[//]: # (Write your tickets according to the format:)
[//]: # ([Quest][Azuremyst Isle] Red Snapper - Very Tasty!)
[//]: # ([NPC] Magistrix Erona)
[//]: # ([Spell][Mage] Fireball)
[//]: # ([Npc][Drop] Ghostclaw Lynx)
[//]: # ([Web] Armory doesnt work)
[//]: # (To find server revision type `.server info` command in the game chat.)

**Description**:  When buying an item from the AH, it does not appear in the Mail box, The fix? re-logging then it appears in your mail box.

**Current behaviour**: Bought items from AH don't appear in your mailbox without re-logging

**Expected behaviour**:  Bought items from AH should automatically appear in your mailbox without re-logging

**Server Revision**:  3031

**Comment by Kaidalen** [comment]
Bump, I also get this

**Comment by Easyfraggy** [comment]
You bumped your own post with the same account saying you have the same issue 👍 

Theres a 60 second refresh timer on mailbox - this was on retail also. Not a bug.
