### ISSUE TITLE
[Item][Quest] "The Great Murkblood Revolt" - Possibly bugged?

### ISSUE THREAD

**Issue by Kolmarwow** [Atlantiss/NetherwingBugtracker#5967]
**Description**: 
In the Netherwing Mines there are slimes scattered around called the "Black Blood of Draenor" which sometimes drop a "Slude-covered Object" which you can open to find random items inside, mostly grey vendor stuff. However there's a small chance (estimated 1-3%) to pull out the "Murkblood Escape Plans" which starts the quest "The Great Murkblood Revolt". 

I have a feeling that the escape plans might not be dropping at the moment as i asked around and haven't found anyone that has gotten this item, even ones that have spent hours farming slimes in the mines. It's difficult to tell since the drop rate is low so it's absolutely possible that we've all simply been unlucky, but thought i'd put this here just in case. 

**Server Revision**: 
3031

**Comment by Evolvee** [comment]
its there

**Comment by Evolvee** [comment]
you probably need netherwing-friendly rep in order to see it

**Comment by Kolmarwow** [comment]
aight, ty for info!
