### ISSUE TITLE
Into the Soulgrinder is bugged

### ISSUE THREAD

**Issue by Fazer1234** [Atlantiss/NetherwingBugtracker#5969]
ogri'la pre quests  Into the Soulgrinder is bugged. when we kill boss item despawn in less then 10 sec and client costantly crash in this area making it impossible to loot the item. Make item last longer time so we can relog after crash and loot it.

**Comment by Manaci** [comment]
Fixed

**Comment by The14me** [comment]
After the last loot update..that loot but out time to time and there is %  someone to be without the skull (cant loot it at all )
Rev:3243

**Comment by Evolvee** [comment]
can someone translate to english
