### ISSUE TITLE
[Quest] Iverron's Antidote: Moonpetal Lilly quest sparkle sprite too big

### ISSUE THREAD

**Issue by Spaztick** [Atlantiss/NetherwingBugtracker#597]
**Description**: 
Moonpetal Lilly quest sparkle sprite for the quest Iverron's Antidote too big
**Current behaviour**:
Big

**Expected behaviour**: 
Smaller (see screenshot)

**Server Revision**: 
![sparkle](https://user-images.githubusercontent.com/29140342/46050009-43198080-c0f7-11e8-8b84-bc68d8ba946c.jpg)

**Comment by Terefinz** [comment]
I remember the sparkles for these lily's being very big. I don't think this is a bug. The lily's are just large and so have their respective larger sparkles.

**Comment by Wolffenstein** [comment]
Yep, it's correct.
