### ISSUE TITLE
[Quest] Into The Soulgrinder - loot container despawns too fast

### ISSUE THREAD

**Issue by Kraggenlord** [Atlantiss/NetherwingBugtracker#5970]
When Skulloc is killed the container that has the quest item in it despawns after about 5-10 seconds which makes it more or less impossible to loot the item in time. This coupled with world PVP and the area being subject to frequent crashes makes this quest incredibly frustrating to complete. 

All the other elite gronns in the previous group quests leading up to this one have at least a minute or so on their shared loot container but not Skulloc for some reason. Some people try it 4-5 times in a row, crash every time and then ragequit. This is worth looking into.

**Comment by Tereneckla** [comment]
duplicate #5969
