### ISSUE TITLE
[Spell][Priest] Prayer of Mending no bonus healing

### ISSUE THREAD

**Issue by Silbotronic** [Atlantiss/NetherwingBugtracker#5971]
[//]: # (Enclose links to things related to the bug using http://wowhead.com or any other TBC database.)
[//]: # (You can use screenshot ingame to visual the issue.)
[//]: # (Write your tickets according to the format:)
[//]: # ([Quest][Azuremyst Isle] Red Snapper - Very Tasty!)
[//]: # ([NPC] Magistrix Erona)
[//]: # ([Spell][Mage] Fireball)
[//]: # ([Npc][Drop] Ghostclaw Lynx)
[//]: # ([Web] Armory doesnt work)
[//]: # (To find server revision type `.server info` command in the game chat.)

**Current behaviour**: When cast on self, Prayer of Mending recieves neither bonus healing nor increased healing from talents (Spiritual Healing), it simply heals for its base value of 800.

**Expected behaviour**: Regardless of who you target it should heal for 800 plus 42.86% of bonus healing, modified by talents that increases healing done.

**Server Revision**: 3031

**Comment by Wolffenstein** [comment]
Fixed in rev 3035.
