### ISSUE TITLE
[NOC] Terokk respawns way too fast

### ISSUE THREAD

**Issue by Manaci** [Atlantiss/NetherwingBugtracker#5973]
**Description**: 
The summoned boss [Terokk](https://db.excalibur.ws/?npc=21838) is despawning too fast.
**Current behaviour**:
[Terokk](https://db.excalibur.ws/?npc=21838) is despawning in like 20 seconds.
**Expected behaviour**: 
[Terokk](https://db.excalibur.ws/?npc=21838) should have a normal despawn timer.
**Server Revision**: 
3031

**Comment by Evolvee** [comment]
can u tell me how to summon him? quest/items/spells etc

**Comment by Evolvee** [comment]
180 after restart
