### ISSUE TITLE
[Quest][Zul'Farrak] Tiara of the Deep

### ISSUE THREAD

**Issue by Nitrogeni** [Atlantiss/NetherwingBugtracker#5974]
**Description**: 

NPC Weegli Blastfuse (7607) runs away after opening the gates. 

**Current behaviour**:

Mentioned NPC aggroes many mobs including a boss Hydromancer Velratha (7795), then the boss cannot be looted for a quest item (9234) required to finish the quest (2846).

**Expected behaviour**: 

Hydromancer Velratha can be looted regardless of being aggroed by a NPC.

**Server Revision**:

**Comment by Easyfraggy** [comment]
This happens when the goblin deals more than half of her hp in damage.

**Comment by Godmatik** [comment]
Rev 4020 - goblin did more than half of her HP and she still dropped loot, guess it is fixed
