### ISSUE TITLE
[Mage] [Frostbolt] Something is causing Frostbolt to DR.

### ISSUE THREAD

**Issue by gunzbngbng** [Atlantiss/NetherwingBugtracker#5975]
[//]: # (Enclose links to things related to the bug using http://wowhead.com or any other TBC database.)
[//]: # (You can use screenshot ingame to visual the issue.)
[//]: # (Write your tickets according to the format:)
[//]: # ([Quest][Azuremyst Isle] Red Snapper - Very Tasty!)
[//]: # ([NPC] Magistrix Erona)
[//]: # ([Spell][Mage] Fireball)
[//]: # ([Npc][Drop] Ghostclaw Lynx)
[//]: # ([Web] Armory doesnt work)
[//]: # (To find server revision type `.server info` command in the game chat.)

**Description**: Something is causing Frostbolt to DR to the point a target is immune to both the slow and the damage.

**Current behaviour**: Something is causing Frostbolt to DR to the point a target is immune to both the slow and the damage.

**Expected behaviour**: With the changes to slows, perhaps the slow should be overwritten, but the damage should still apply?

**Server Revision**: 3031

**Comment by devo6969** [comment]
From what I can see, it refreshes the slow debuff on the PTR. Target never becomes to immune to the slow or damage.

**Comment by Tereneckla** [comment]
Fixed
