### ISSUE TITLE
[Spell] Protection of Elune on Archimonde is not working properly

### ISSUE THREAD

**Issue by ircfelix** [Atlantiss/NetherwingBugtracker#5976]
**Description**: 
The Spell "Protection of Elune" should protect you from all attacks and spells for 1 minute. No converse info found in wowhead comments either in the comments of the aura and Archimonde himself (woulda been noted there if it didn't make immune to everything)

**Current behaviour**:
The Spell "Protection of Elune" does not protect you from all attacks and spells for 1 minute. In the source linked below, you can see me die with the buff on.
https://www.twitch.tv/videos/441796584?t=30m30s

**Expected behaviour**: 
The Spell "Protection of Elune" should protect you from all attacks and spells for 1 minute.

**Server Revision**: 
3033

**Comment by Wolffenstein** [comment]
Fixed in rev 3034.
