### ISSUE TITLE
[NPC][Tame] Enraged Ravager

### ISSUE THREAD

**Issue by Phyeuz** [Atlantiss/NetherwingBugtracker#5977]
**Description**: Enraged Ravagers are located on Bloodmyst Isle, near Vindicator's Rest. These ravagers are tamable by hunters to be pets, but due to some kind of bug, the ravager will become tamed without the ability to be fed food or leveled up.

**Current behaviour**: Once tamed, the Enraged Ravager comes with Gore (rank3) and appears to work properly in combat. However, the pet cannot be fed it's diet food to increase it's happiness. When using "Feed Pet" and clicking the food, the animation and sound of chewing is triggered but the food is not consumed, my pet is gains no "Eating" buff and no gains to the Happiness bar. The pet's Experience bar is also missing entirely, making the pet impossible to progress.

**Expected behaviour**: Working "Feed Pet" and experience progression.

**Server Revision**:

**Comment by Godmatik** [comment]
Very likely the original poster tried to feed food that was too high level for this pet. At the time there was a bug where it wouldn't give an error message when doing this.

Fixed now and can close.
