### ISSUE TITLE
[Quest] Incorrect quest item drop rate Quest:The Totems of My Enemy

### ISSUE THREAD

**Issue by wnap1** [Atlantiss/NetherwingBugtracker#5978]
[//]: # (Enclose links to things related to the bug using http://wowhead.com or any other TBC database.)
[//]: # (You can use screenshot ingame to visual the issue.)
[//]: # (Write your tickets according to the format:)
[//]: # ([Quest][Azuremyst Isle] Red Snapper - Very Tasty!)
[//]: # ([NPC] Magistrix Erona)
[//]: # ([Spell][Mage] Fireball)
[//]: # ([Npc][Drop] Ghostclaw Lynx)
[//]: # ([Web] Armory doesnt work)
[//]: # (To find server revision type `.server info` command in the game chat.)

**Description**: 
Quest: https://wowwiki.fandom.com/wiki/Quest:The_Totems_of_My_Enemy
According to https://db.excalibur.ws/?item=31651 quest item drop rate is 80%

**Current behaviour**:
Current quest item drop rate is below 10%

**Expected behaviour**: 

**Server Revision**:

**Comment by Evolvee** [comment]
stock db is not a proof of anything
