### ISSUE TITLE
[Hunter Pets] Follor acceleration not removed when pet gets in combat while already in accelerated follow

### ISSUE THREAD

**Issue by Donell70** [Atlantiss/NetherwingBugtracker#5979]
[//]: # (Enclose links to things related to the bug using http://wowhead.com or any other TBC database.)
[//]: # (You can use screenshot ingame to visual the issue.)
[//]: # (Write your tickets according to the format:)
[//]: # ([Quest][Azuremyst Isle] Red Snapper - Very Tasty!)
[//]: # ([NPC] Magistrix Erona)
[//]: # ([Spell][Mage] Fireball)
[//]: # ([Npc][Drop] Ghostclaw Lynx)
[//]: # ([Web] Armory doesnt work)
[//]: # (To find server revision type `.server info` command in the game chat.)

**Description**: 
Hunter pets move too fast while they running on "follow" mode to hunter, provided when they are dont get combat before activation "follow" mode.
**Current behaviour**:
~~1. This video shows how fast he move on "follow" mode. No combat before activation "follow" mode and after activation.
https://www.youtube.com/watch?v=I1qxcPBVRH8
2. He getting combat before activation "follow" mode.
https://www.youtube.com/watch?v=4xaNaz8G6q4&feature=youtu.be~~
3. He getting combat after activation "follow" mode.
https://www.youtube.com/watch?v=0ZcHJxPsl-I&feature=youtu.be
**Expected behaviour**: 
Hunter pets should not be accelerated without a reason.
**Server Revision**: 
3033

**Comment by Evolvee** [comment]
yes they should

only the point 3. is wrong, it should be slowed in middle of the way

do some research before u post ^^
