### ISSUE TITLE
[Core] [Quest] Collectable quest objects already obtained still able to be used

### ISSUE THREAD

**Issue by Spaztick** [Atlantiss/NetherwingBugtracker#598]
**Description**: 
Collectable quest containers (collect 7 Moonpetal Lilly in #597 for example) are still able to be used after the max/required items are collected.

**Current behaviour**:
Quest items can be collected when you have the required amount of objects needed. Item opens a blank loot window (nothing to collect) and despawns as normal. The issue fixes itself but **there is a significant server delay until it behaves as expected** (not able to loot the container).

**Expected behaviour**: 
Once max required quest items is reached item should no longer be collectable immediately.

**Server Revision**: 
Derp.

**Comment by Spaztick** [comment]
![sparkle](https://user-images.githubusercontent.com/29140342/46055294-fc388480-c110-11e8-9fd4-3738bf078925.jpg)

**Comment by Tereneckla** [comment]
Fixed
