### ISSUE TITLE
[Hunter] [Entrapment] Is on the same DR table as Entangling Roots.

### ISSUE THREAD

**Issue by gunzbngbng** [Atlantiss/NetherwingBugtracker#5980]
[//]: # (Enclose links to things related to the bug using http://wowhead.com or any other TBC database.)
[//]: # (You can use screenshot ingame to visual the issue.)
[//]: # (Write your tickets according to the format:)
[//]: # ([Quest][Azuremyst Isle] Red Snapper - Very Tasty!)
[//]: # ([NPC] Magistrix Erona)
[//]: # ([Spell][Mage] Fireball)
[//]: # ([Npc][Drop] Ghostclaw Lynx)
[//]: # ([Web] Armory doesnt work)
[//]: # (To find server revision type `.server info` command in the game chat.)

**Description**: Entrapment is a talent for hunters that can proc a 4 second root.  It is meant to only DR against itself.  

**Current behaviour**:  Currently, Entrapment procs are causing Entangling Roots diminishing returns.

**Expected behaviour**: Entrapment and Entangling Roots should not share DRs.

**Server Revision**: 3033

**Comment by gunzbngbng** [comment]
Bump.  Entrapment is still DR'ing with Entangling Roots.

**Comment by Hidehugo** [comment]
#5813 bump

**Comment by gunzbngbng** [comment]
Entrapment did not share DRs with anything but itself until patch 6.0.2.

https://wow.gamepedia.com/Entrapment

**Comment by Wolffenstein** [comment]
Fixed in rev 3078.
