### ISSUE TITLE
[Mage] [Ice Armor] Is not intended to drop off when subjected to superior slows.

### ISSUE THREAD

**Issue by gunzbngbng** [Atlantiss/NetherwingBugtracker#5981]
[//]: # (Enclose links to things related to the bug using http://wowhead.com or any other TBC database.)
[//]: # (You can use screenshot ingame to visual the issue.)
[//]: # (Write your tickets according to the format:)
[//]: # ([Quest][Azuremyst Isle] Red Snapper - Very Tasty!)
[//]: # ([NPC] Magistrix Erona)
[//]: # ([Spell][Mage] Fireball)
[//]: # ([Npc][Drop] Ghostclaw Lynx)
[//]: # ([Web] Armory doesnt work)
[//]: # (To find server revision type `.server info` command in the game chat.)

**Description**: The Chill effect applied by a mage's Ice Armor is being overwritten by superior slows.  This effect is not intended to drop off as it also applies an attack speed slow.

**Current behaviour**: The Chill effect applied by a mage's Ice Armor is being overwritten by superior slows.  This effect is not intended to drop off as it also applies an attack speed slow.

**Expected behaviour**: The Chill effect should stay applied to a target regardless of what other slows are present.

**Server Revision**: 3033

**Comment by Wolffenstein** [comment]
Should be fixed
