### ISSUE TITLE
[Quest][Netherstorm] Getting Down to Business --- I can't hand in the quest after having gotten the 8 nether dragon essences

### ISSUE THREAD

**Issue by rangobob** [Atlantiss/NetherwingBugtracker#5982]
[//]: # (Enclose links to things related to the bug using http://wowhead.com or any other TBC database.)
[//]: # (You can use screenshot ingame to visual the issue.)
[//]: # (Write your tickets according to the format:)
[//]: # ([Quest][Azuremyst Isle] Red Snapper - Very Tasty!)
[//]: # ([NPC] Magistrix Erona)
[//]: # ([Spell][Mage] Fireball)
[//]: # ([Npc][Drop] Ghostclaw Lynx)
[//]: # ([Web] Armory doesnt work)
[//]: # (To find server revision type `.server info` command in the game chat.)

**Description**: 
https://imgur.com/ARMTZMB
https://imgur.com/22Ug1x4

Im standing at the quest "pad" giver thingy and can't turn in the quest.
**Current behaviour**:

**Expected behaviour**: 

**Server Revision**:

**Comment by rangobob** [comment]
or is that because i have reputation with Netherwing ?

**Comment by mbzz88** [comment]
You don't turn the quest into that guy, you turn it into the "Shrouded Figure" who is sitting right next to the cliff nearby.
