### ISSUE TITLE
[NPC]Terrordar the Tormentor should be removed

### ISSUE THREAD

**Issue by kulkan1** [Atlantiss/NetherwingBugtracker#5983]
[//]: # (Enclose links to things related to the bug using http://wowhead.com or any other TBC database.)
[//]: # (You can use screenshot ingame to visual the issue.)
[//]: # (Write your tickets according to the format:)
[//]: # ([Quest][Azuremyst Isle] Red Snapper - Very Tasty!)
[//]: # ([NPC] Magistrix Erona)
[//]: # ([Spell][Mage] Fireball)
[//]: # ([Npc][Drop] Ghostclaw Lynx)
[//]: # ([Web] Armory doesnt work)
[//]: # (To find server revision type `.server info` command in the game chat.)

**Description**: 
A level 70 elite mob in Forge Camp: Terror, south of Ogri'la in BEM was removed in 2.1 on retail, but is still walking around on Netherwing

https://www.wowhead.com/npc=22385/terrordar-the-tormentor
https://wowwiki.fandom.com/wiki/Terrordar_the_Tormentor

**Current behaviour**:
Terrordar the Tormentor is spawning

**Expected behaviour**: 
Terrordar the Tormentor not spawning

**Server Revision**: 
3033

**Comment by Evolvee** [comment]
fixed
