### ISSUE TITLE
Warrior The Affray Quest Freezes every time I start it

### ISSUE THREAD

**Issue by ctlarson** [Atlantiss/NetherwingBugtracker#5984]
[//]: # (Enclose links to things related to the bug using http://wowhead.com or any other TBC database.)
[//]: # (You can use screenshot ingame to visual the issue.)
![image](https://user-images.githubusercontent.com/52127164/59975514-22932f80-957e-11e9-9061-117ab82ef592.png)

[//]: # (Write your tickets according to the format:)
[//]: # ([Quest][Azuremyst Isle] Red Snapper - Very Tasty!)
[//]: # ([NPC] Magistrix Erona)
[//]: # ([Spell][Mage] Fireball)
[//]: # ([Npc][Drop] Ghostclaw Lynx)
[//]: # ([Web] Armory doesnt work)
[//]: # (To find server revision type `.server info` command in the game chat.)

**Description**: 
Every time I start the warrior quest The Affray.  My game completely freezes and wont unfreeze until the quest is failed.  I need this quest to get berserker stance.
**Current behaviour**:

**Expected behaviour**: 

**Server Revision**:

**Comment by Evolvee** [comment]
remove quest helper
