### ISSUE TITLE
[Quest][Nagrand] A Visit With The Ancestors

### ISSUE THREAD

**Issue by mywebpage-rocks** [Atlantiss/NetherwingBugtracker#5985]
[//]: # (Enclose links to things related to the bug using http://wowhead.com or any other TBC database.)
[//]: # (You can use screenshot ingame to visual the issue.)
[//]: # (Write your tickets according to the format:)
[//]: # ([Quest][Azuremyst Isle] Red Snapper - Very Tasty!)
[//]: # ([NPC] Magistrix Erona)
[//]: # ([Spell][Mage] Fireball)
[//]: # ([Npc][Drop] Ghostclaw Lynx)
[//]: # ([Web] Armory doesnt work)
[//]: # (To find server revision type `.server info` command in the game chat.)

**Description**: 

You are supposed to get credit for "Visit Sunspring Post" as soon as you enter Sunspring Post.

**Current behaviour**:

You don't get credit, I've travelled Sunspring post through and could not manage to get the credit for Visit Sunspring Post which blocks remaning parts of the chain.

**Expected behaviour**: 

As soon as you enter Sunspring Post you are supposed to get credit.https://youtu.be/55ugZSqPs7w?t=25

Wowhead says:
Sunspring Post: 32, 43 (I think) you'll hit it running from the water to the big central building

**Server Revision**: 
3033

**Comment by Evolvee** [comment]
watch changelog
