### ISSUE TITLE
Scaled Basilisk shows death to early

### ISSUE THREAD

**Issue by thom4466** [Atlantiss/NetherwingBugtracker#5986]
**Description**: 
Scaled Basilisk shows death animation at around 10-20% HP
**Current behaviour**:
https://www.dropbox.com/s/u99ydjjv1xtj2v3/2019-06-23_14-14-39.mp4?dl=0 video showing the bug

**Comment by Wolffenstein** [comment]
It's intended. Those basilisks pretend to be dead while at low health to surprise their opponents.
