### ISSUE TITLE
Human race is broken!!

### ISSUE THREAD

**Issue by t0rag** [Atlantiss/NetherwingBugtracker#5987]
**Description**: Human Race is broken, and its not my bug or something, I redownloaded wow from your websites now. without addons. and still have the same problem..I´m not sure if i can descript it exactly, my english is not very well, but if I want to go up stairs or go over a curb, it actually blocking me.. i cannot go over stairs clearly. I already tested it, a Night elf was fine, gnome is fine also.. my Friend is Human and has the same problem, a random player human has same problem.. just look on humans in SW, they are stucking on stairs. it happens everywhere in the world, In rated arenas ... really annoying.. you have to see it

**Comment by danbopes** [comment]
Try creating a video to demonstrate the exact issue you're facing.

**Comment by t0rag** [comment]
lol, sorry but i dont know which programe use for video... just go to the SW as I said .. you can see humans whose go to Auction house and the stairs blocks them.

**Comment by t0rag** [comment]
downloading fraps... working on it

**Comment by t0rag** [comment]
I have the several videos but its 4-8GB.. I cant share here more than 10 MB. LOL

**Comment by t0rag** [comment]
https://www.youtube.com/watch?v=4tIyBPCcmxA&feature=youtu.be     link for the video

**Comment by Evolvee** [comment]
clientside
