### ISSUE TITLE
[Hunter] [Freezing Trap] Stealth is not removed when trap is activated.

### ISSUE THREAD

**Issue by gunzbngbng** [Atlantiss/NetherwingBugtracker#5988]
[//]: # (Enclose links to things related to the bug using http://wowhead.com or any other TBC database.)
[//]: # (You can use screenshot ingame to visual the issue.)
[//]: # (Write your tickets according to the format:)
[//]: # ([Quest][Azuremyst Isle] Red Snapper - Very Tasty!)
[//]: # ([NPC] Magistrix Erona)
[//]: # ([Spell][Mage] Fireball)
[//]: # ([Npc][Drop] Ghostclaw Lynx)
[//]: # ([Web] Armory doesnt work)
[//]: # (To find server revision type `.server info` command in the game chat.)

**Description**: If a player hits a freezing trap while stealthed, they will be frozen, but stealth is not removed.  It is quite funny to see a stealthed player in a freezing trap, but this is not blizzlike.

**Current behaviour**: If a player hits a freezing trap while stealthed, they will be frozen, but stealth is not be removed.

**Expected behaviour**: If a player hits a freezing trap, they should become visible.

**Server Revision**: 3033

**Comment by Evolvee** [comment]
proof?

**Comment by The14me** [comment]
Rev 3460.No more an issue.
