### ISSUE TITLE
[Hunter] [Pet Ability Screech] Pet skill does not create bonus threat.

### ISSUE THREAD

**Issue by gunzbngbng** [Atlantiss/NetherwingBugtracker#5989]
[//]: # (Enclose links to things related to the bug using http://wowhead.com or any other TBC database.)
[//]: # (You can use screenshot ingame to visual the issue.)
[//]: # (Write your tickets according to the format:)
[//]: # ([Quest][Azuremyst Isle] Red Snapper - Very Tasty!)
[//]: # ([NPC] Magistrix Erona)
[//]: # ([Spell][Mage] Fireball)
[//]: # ([Npc][Drop] Ghostclaw Lynx)
[//]: # ([Web] Armory doesnt work)
[//]: # (To find server revision type `.server info` command in the game chat.)

**Description**: Certain hunter pets can learn a spell called "Screech".  This ability is an aoe taunt that lowers the attack power of those affected, deals a small amount of damage, and applies a scaling amount of threat.

**Current behaviour**: Screech is currently applying the debuff and the damage, but not the additional threat.

**Expected behaviour**: Screech should apply an aoe debuff that deals damage and bonus threat.

**Server Revision**: 3034

**Comment by gunzbngbng** [comment]
I found a post back from 2018 where this was confirmed.  
https://github.com/Atlantiss/NetherwingBugtracker/issues/1679

**Comment by gunzbngbng** [comment]
Diamond Threat Meter appears to have the threat coefficient programmed.  By it's numbers I should not have threat under any circumstance.

https://puu.sh/DJVrW/7e34145582.jpg

**Comment by Manaci** [comment]
Fixed in rev 3162
