### ISSUE TITLE
Withered Poison from Scorpions

### ISSUE THREAD

**Issue by despairr1** [Atlantiss/NetherwingBugtracker#599]
[//]: # (Enclose links to things related to the bug using http://wowhead.com or any other TBC database.)
[//]: # (You can use screenshot ingame to visual the issue.)
[//]: # (Write your tickets according to the format:)
[//]: # ([Quest][Azuremyst Isle] Red Snapper - Very Tasty!)
[//]: # ([NPC] Magistrix Erona)
[//]: # ([Spell][Mage] Fireball)
[//]: # ([Npc][Drop] Ghostclaw Lynx)
[//]: # ([Web] Armory doesnt work)

**Description**: 
Scorpions in shimmering flats apply withered poison but it ticks at 0 seconds for quite awhile before falling off. 
**Current behaviour**:
Over ticks 
**Expected behaviour**: 
It to fall off at 0
**Server Revision**:

**Comment by The14me** [comment]
Work just fine to me now.
