### ISSUE TITLE
[Buff] Apexis Emanation

### ISSUE THREAD

**Issue by Tereneckla** [Atlantiss/NetherwingBugtracker#5990]
[//]: # (Enclose links to things related to the bug using http://wowhead.com or any other TBC database.)
[//]: # (You can use screenshot ingame to visual the issue.)
[//]: # (Write your tickets according to the format:)
[//]: # ([Quest][Azuremyst Isle] Red Snapper - Very Tasty!)
[//]: # ([NPC] Magistrix Erona)
[//]: # ([Spell][Mage] Fireball)
[//]: # ([Npc][Drop] Ghostclaw Lynx)
[//]: # ([Web] Armory doesnt work)
[//]: # (To find server revision type `.server info` command in the game chat.)

**Description**: Clicking away the Apexis Emanations buff doesn't remove the movement speed gained from it. The extra movement speed also works in places other than the Blade's Edge Plateaus.
Relogging, loading screens and death do not fix this.

**Current behaviour**: Buff works outside of Blade's Edge Plateus.
Buff persists after clicking away. Movement speed goes away after the buff normally would have ended.
![WoWScrnShot_062519_134253](https://user-images.githubusercontent.com/50233983/60095642-54a7bb80-974f-11e9-84fa-1a1e38b0160d.jpg)
![WoWScrnShot_062519_134301](https://user-images.githubusercontent.com/50233983/60095656-5bcec980-974f-11e9-809a-ded8cd0cd273.jpg)
See top right, buffbar and carbonite showing movement speed.

Also stays in Arena/Battleground btw

**Expected behaviour**: Clicking away the buff should end it.

**Server Revision**: 3034

**Comment by Wolffenstein** [comment]
Fixed in rev 3039.
