### ISSUE TITLE
[Quest] Apexis Relic

### ISSUE THREAD

**Issue by Tereneckla** [Atlantiss/NetherwingBugtracker#5991]
[//]: # (Enclose links to things related to the bug using http://wowhead.com or any other TBC database.)
[//]: # (You can use screenshot ingame to visual the issue.)
[//]: # (Write your tickets according to the format:)
[//]: # ([Quest][Azuremyst Isle] Red Snapper - Very Tasty!)
[//]: # ([NPC] Magistrix Erona)
[//]: # ([Spell][Mage] Fireball)
[//]: # ([Npc][Drop] Ghostclaw Lynx)
[//]: # ([Web] Armory doesnt work)
[//]: # (To find server revision type `.server info` command in the game chat.)

**Description**: ![WoWScrnShot_062419_104923](https://user-images.githubusercontent.com/50233983/60005700-4aae8b80-966f-11e9-9f74-c528aac70ae6.jpg)

**Current behaviour**: Cannot attempt the Apexis Relic Minigame again after doing it today.

**Expected behaviour**: You can attempt the Minigame as often as you want as long as you have Apexis Shards.

**Server Revision**: 3034

**Comment by Godmatik** [comment]
Fixed a while ago
