### ISSUE TITLE
[Quest] The Exorcism of Colonel Jules / Digging for Prayer Beads - pre-requisite? 

### ISSUE THREAD

**Issue by randomuser69** [Atlantiss/NetherwingBugtracker#5992]
[//]: # (Enclose links to things related to the bug using http://wowhead.com or any other TBC database.)
[//]: # (You can use screenshot ingame to visual the issue.)
[//]: # (Write your tickets according to the format:)
[//]: # ([Quest][Azuremyst Isle] Red Snapper - Very Tasty!)
[//]: # ([NPC] Magistrix Erona)
[//]: # ([Spell][Mage] Fireball)
[//]: # ([Npc][Drop] Ghostclaw Lynx)
[//]: # ([Web] Armory doesnt work)
[//]: # (To find server revision type `.server info` command in the game chat.)

**Description**: 
Not sure if this is a NW bug or blizzlike (couldn't confirm),  but the text that is stated in the quest "The Exorcism of Colonel Jules" makes it seem like "Digging for Prayer Beads" is a pre-requisite: 

"**Take the prayer beads you found** and speak with Anchorite Barada "

https://wowwiki.fandom.com/wiki/Quest:The_Exorcism_of_Colonel_Jules
https://wowwiki.fandom.com/wiki/Quest:Digging_for_Prayer_Beads

**Current behaviour**:
On NW, you can do the quest "The Exorcism of Colonel Jules" without first doing "Digging for Prayer Beads" (note my questlog which has "Digging for Prayer Beads" not yet complete:

![WoWScrnShot_062419_045753](https://user-images.githubusercontent.com/51173000/60008363-f50fba00-9641-11e9-8a25-cc0c15ae3b94.jpg)

**Expected behaviour**: 
I couldnt confirm if "Digging for Prayer Beads" is a pre-requisite for "The Exorcism of Colonel Jules", but going off the text "**Take the prayer beads you found** and speak with Anchorite Barada "
it seems like it should be. 

**Server Revision**: 
3034

**Comment by The14me** [comment]
Digging for Prayer Beads suppose to be pre-quest of The Exorcism of Colonel Jules
https://www.wowhead.com/quest=10916/digging-for-prayer-beads
https://www.wowhead.com/quest=10935/the-exorcism-of-colonel-jules
https://i.imgur.com/0QrlnMA.png

**Comment by Wolffenstein** [comment]
Fixed in rev 3470.
