### ISSUE TITLE
[NPC] Thun'grim Firegaze

### ISSUE THREAD

**Issue by Nimarioos** [Atlantiss/NetherwingBugtracker#5993]
**Description**: 
https://classic.wowhead.com/guides/warrior-class-quests-classic-wow
**Current behaviour**:

After finishing Brutal Armor https://classic.wowhead.com/quest=1838/brutal-armor Questline, Questgiver offer only 
https://classic.wowhead.com/quest=1839/ulaelek-and-the-brutal-gauntlets

**Expected behaviour**: 
He should offer also
https://classic.wowhead.com/quest=1840/orm-stonehoof-and-the-brutal-helm
https://classic.wowhead.com/quest=1841/velora-nitely-and-the-brutal-legguards
right away after finishing brutal armor

**Server Revision**: 
idk lol

**Comment by Shulishin** [comment]
Made an account just to comment here.

Thun'grim Firegaze does not offer all follow ups - for me he only offered Brutal Legguards. However you can visit each of the other NPCs yourself and get the follow up quests to get the last pieces of armor. So while no 'breadcrumb' quest is offered, the quests are unlocked and all armor is attainable.

**Comment by Evolvee** [comment]
its because these quests are race-limited

u get https://classic.wowhead.com/quest=1841/velora-nitely-and-the-brutal-legguards if u are undead etc.
