### ISSUE TITLE
[Item] Elixir of Shadows does not apply to pets

### ISSUE THREAD

**Issue by Manaci** [Atlantiss/NetherwingBugtracker#5994]
**Description**: 
In Skettis, when using the [Elixir of Shadows](https://db.excalibur.ws/?item=32446), players can see undead Arakkoa NPCs for 20 minutes. This effect does not apply correctly to pets though, making them unable to aggro the mobs, but still able to damage them.
**Current behaviour**:
Pets can damage the undead Arakkoa NPCs while the player is under the effect of the [Elixir of Shadows](https://db.excalibur.ws/?item=32446) but they are ignored by them.
**Expected behaviour**: 
Pets should be able to both damage and hold aggro from the undead Arakkoa NPCs while the player is under the effect of the [Elixir of Shadows](https://db.excalibur.ws/?item=32446).
**Server Revision**: 
3034

**Comment by Wolffenstein** [comment]
Fixed in rev 3104.
