### ISSUE TITLE
[NPC] Unkillable Skittering Cavern Crawler and can be abused to get weapon skill

### ISSUE THREAD

**Issue by iguessineedhelp** [Atlantiss/NetherwingBugtracker#5995]
[//]: # https://imgur.com/a/RDh6htA
[//]: # ([NPC] Skittering Cavern Crawler)
[//]: # server revision: 3034

**Skittering Cavern Crawler is unkillable and be abused to gain weapon skills**: 

Unkillable

Should be killable

**Comment by Evolvee** [comment]
hotfixed
