### ISSUE TITLE
[Item]Elixir of Demonslaying not working

### ISSUE THREAD

**Issue by Healweed** [Atlantiss/NetherwingBugtracker#5996]
**Description**: 
Use: Increases attack power by 265 against demons. Lasts 300 sec. Battle Elixir.

**Current behaviour**:
Does not increase your melee/ranged attack power by 265 if you fight **Demon** enemies.

**Expected behaviour**: 
Both Melee/Ranged Attack power should be increased if you're fighting **Demon** enemies

**Server Revision**: 
3034

**Comment by FabianMueller77** [comment]
Can't confirm.

I autohit a bunch Terrormasters in smv with and without demonslaying and the average damage/hit was 183 without and 195 with demonslaying. 
factoring in armor reduction, weaponspeed and 10% physical dmg increase from the druid talent naturalist this is roughly the effect you would expect from a 242 ap bonus (in the margin of error considering the small sample)
![Unbenannt](https://user-images.githubusercontent.com/46138731/60121055-84bc8200-9782-11e9-9b5b-3e5ce1406a81.PNG)

**Comment by Healweed** [comment]
@FabianMueller77 I tested this inside of KZ and on world. There are a lot of stuff that increase your ap against demons, which work, but not the elixir unfortunally. As i said previous, if you're fighting a demon enemy, your ap (both melee and ranged) should be increased by 265.

**Comment by FabianMueller77** [comment]
How about you provide any evidence then? 
I used the elixir and it increased my damage output against demons as shown in the picture i included.

**Comment by Healweed** [comment]
The evidence shows as it follows.
Without Elixir usage
![No_demon_slaying](https://user-images.githubusercontent.com/52166185/60176464-41a7f080-980e-11e9-8b84-f49c72e8df9a.jpg)
![Mental_quickness_no_elixir](https://user-images.githubusercontent.com/52166185/60176482-4ff60c80-980e-11e9-84a1-c57e43188b43.jpg)

**Comment by Healweed** [comment]
With Elixir:
![With_demon_slaying](https://user-images.githubusercontent.com/52166185/60176543-8469c880-980e-11e9-9213-b80b674eb0a3.jpg)
![Mental_quickness_with_elixir](https://user-images.githubusercontent.com/52166185/60176547-8764b900-980e-11e9-97be-00ce0aa03b31.jpg)
 In case anyone asks why there's a spell tab, check Mental Quickness talent for enh shamans plz(it does work)
This is one of the very few items that DOES NOT increase your damage and increases your ap. Like i said previous i tested this many times and i came to conclusion that the elixir is not working

**Comment by FabianMueller77** [comment]
Obviously it doesn't show in your melee tab since there is no "attack power against demons" section. 
Like what the hell did you expect to show up there?
Show me your average autohit damage with and without elixir (without ap procs like hourglass and unleashed rage)

**Comment by Healweed** [comment]
> Obviously it doesn't show in your melee tab since there is no "attack power against demons" section.
Like what the hell did you expect to show up there?
Show me your average autohit damage with and without elixir (without ap procs like hourglass and unleashed rage)

You're not reading what i said previously right? I said that the elixir should increase your attack power (Both melee and ap) on the condition you're fighting demons.  There are a crap tons of items(and weapons) that increases attack power against x type of enemy and IT does work. And for reference, YES it shows an increase of ap for those items but not for this. 
And for future reference, relying on average autohit dmg is just dumb and inaccurate if you're testing stuff.

**Comment by FabianMueller77** [comment]
>YES it shows an increase of ap for those items but not for this.
how about you show any proof for that?
>And for future reference, relying on average autohit dmg is just dumb and inaccurate if you're testing stuff.
as opposed to what you are doing to prove your point I assume

**Comment by FabianMueller77** [comment]
> YES it shows an increase of ap for those items but not for this.

how about you show any proof for that?
>And for future reference, relying on average autohit dmg is just dumb and inaccurate if you're testing stuff.

I provided evidence while you didn't. I don't have access to the game code, so testing damage ranges is the only way for me to figure stuff out.

**Comment by Healweed** [comment]
> how about you show any proof for that?
The proof is already displayed on the screenshots. All types of consumables should increase x stat. In this case Demonslaying should increase your Attack Power vs Demons. 

> I provided evidence while you didn't. I don't have access to the game code, so testing damage ranges is the only way for me to figure stuff out.
Then you should hit F5 really hard unless you didn't saw the screenshots. You provided an inaccurate evidence while i posted screenshots with/without the elixir. Ands again in case if you didn't read b4 , i said that mental quickness talent is the best way to test it, not some average auto attacks. Instead of bullshitting on stuff like that, read!

**Comment by FabianMueller77** [comment]
There is no fucking "Attack Power vs Demons" stat in your melee tab, neither is there a "Spell Damage vs Demons" stat in your spell tab. Holy shit how hard is it to grasp that. 
Check out this screenshot:
![Unbenannt](https://user-images.githubusercontent.com/46138731/60184482-6e690180-9828-11e9-9ef8-051a44a619cc.PNG)
Can you imagine? There's no "Attack Power vs Beasts" stat either! Amazing!
