### ISSUE TITLE
Earthbind totem removing rogues from stealth

### ISSUE THREAD

**Issue by Maikie1234** [Atlantiss/NetherwingBugtracker#5997]
**Description**: Was doing a PVP duel with a shaman, got kicked out of stealth by his Earthbind totem without any damage caused to me

**Current behaviour**:Earthbind removes stealth

**Expected behaviour**: I believe Earthbind totem shouldnt remove stealth, was looking it up on the internet, all i found were cases where rogue wasnt kicked out of stealth by Earthbind

**Server Revision**: 3034

**Comment by Evolvee** [comment]
@Wolffenstein ?????????????

**Comment by Maikie1234** [comment]
Edit : Demoralizing shout from mobs (dont know if warriors can do it as well) removes stealth as well

**Comment by Evolvee** [comment]
thats intended

**Comment by Wolffenstein** [comment]
Fixed in rev 3039.
