### ISSUE TITLE
[Item] Spetrecles do not apply to pets

### ISSUE THREAD

**Issue by bbeard12** [Atlantiss/NetherwingBugtracker#5998]
Description:
In Shadowmoon Valley, when using the Spectrecles, players can see Shadowmoon Zealot NPCs in Shadowmoon Village. This effect does not apply correctly to pets though, making them unable to aggro the mobs, but still able to damage them.
Current behaviour:
Pets can damage the Shadowmoon Zealot NPCs while the player is under the effect of the Spectrecles but they are ignored by them.
Expected behaviour:
Pets should be able to both damage and hold aggro from the Shadowmoon Zealot NPCs while the player is under the effect of the Spectrecles.
Server Revision:
3034

**Comment by bbeard12** [comment]
Similar issue as https://github.com/Atlantiss/NetherwingBugtracker/issues/5994

**Comment by Wolffenstein** [comment]
Fixed in rev 3104.
