### ISSUE TITLE
[mechanic] Whispers to players not working

### ISSUE THREAD

**Issue by towneh** [Atlantiss/NetherwingBugtracker#6]
[//]: # (Enclose links to things related to the bug using http://wowhead.com or any other TBC database.)
[//]: # (You can use screenshot ingame to visual the issue.)
[//]: # (Write your tickets according to the format:)
[//]: # ([Quest][Azuremyst Isle] Red Snapper - Very Tasty!)
[//]: # ([NPC] Magistrix Erona)
[//]: # ([Spell][Mage] Fireball)
[//]: # ([Npc][Drop] Ghostclaw Lynx)
[//]: # ([Web] Armory doesnt work)

**Description**: 
Whispering player not working.

**Current behaviour**:
Attempting to whisper "Toto" comes back with "No player named 'Toto' is playing" even when selecting the player from the right click context menu

![image](https://user-images.githubusercontent.com/25694892/45921248-e7a68300-bea9-11e8-8333-b3ec9d9f78fb.png)

**Expected behaviour**: 
Player to receive private message.

**Server Revision**:

**Comment by wtRCH** [comment]
Try whisper any other player. As a GM he doesn't get whispers from normal "non-gm" players.
