### ISSUE TITLE
Starter Zone Graveyards

### ISSUE THREAD

**Issue by Scylla420** [Atlantiss/NetherwingBugtracker#60]
It should be impossible to respawn inside of a starter zone graveyard if you die outside of a starter zone. 
 Currently, you can die just outside of Northshire and spawn inside of Northshire instead of spawning at the Goldshire graveyard. 

[Northshire](https://www.youtube.com/watch?v=eFZYIutqVjM&feature=youtu.be)

[Source](http://wowwiki.wikia.com/wiki/Patch_1.6.0?oldid=88936)

"Starting area graveyards are still reserved exclusively for characters of similar faction that die within their confines. For example, the spirit of a Horde character dying right outside of Deathknell will not use Deathknell graveyard, but will instead go to the next closest Tirisfal Glades graveyard."

**Comment by wtRCH** [comment]
Still occurs in:
- Mulgore
- Teldrassil

**Comment by toto6** [comment]
Fixed in Rev 2029
