### ISSUE TITLE
[NPC][Netherstorm] Dimensius the All-Devouring

### ISSUE THREAD

**Issue by raethkcj** [Atlantiss/NetherwingBugtracker#6000]
[//]: # (Enclose links to things related to the bug using http://wowhead.com or any other TBC database.)
[//]: # (You can use screenshot ingame to visual the issue.)
[//]: # (Write your tickets according to the format:)
[//]: # ([Quest][Azuremyst Isle] Red Snapper - Very Tasty!)
[//]: # ([NPC] Magistrix Erona)
[//]: # ([Spell][Mage] Fireball)
[//]: # ([Npc][Drop] Ghostclaw Lynx)
[//]: # ([Web] Armory doesnt work)
[//]: # (To find server revision type `.server info` command in the game chat.)

**Description**: 
Dimensius should be unable to move.

**Current behaviour**:
Dimensius moves from his position and melees ranged attackers.

**Expected behaviour**: 
Dimensius should be unable to move.

source:
https://www.wowhead.com/npc=19554/dimensius-the-all-devouring#comments:id=46636:reply=290204

**Server Revision**: 3035

**Comment by Evolvee** [comment]
only in his phase 2

**Comment by Evolvee** [comment]
if you have more info, feel free to reopen

**Comment by raethkcj** [comment]
https://youtu.be/HYuilDCG34Q
https://youtu.be/Ua8o3JAjQqU
https://youtu.be/s1fSK19wvZY
https://youtu.be/EfC3yIaI-yU

Never during any of these fights does Dimensius move from the center of the room

**Comment by Evolvee** [comment]
is there any time where there was no melee npc/player nearby him ?

**Comment by raethkcj** [comment]
No, but currently on Netherwing a single player ability is enough to pull threat off the NPCs, which doesn't happen in any of the "solo" videos. So either he can't move (and melees the closest NPC) or the NPCs should have a massive threat boost.

**Comment by Evolvee** [comment]
so... he should stand still and do nothing(if there are no units in his melee range) until phase 2? seems unlikely
