### ISSUE TITLE
[Dustwallow Marsh] [Quest] The Essence of Enmity

### ISSUE THREAD

**Issue by Malaise80** [Atlantiss/NetherwingBugtracker#6001]
[//]: # (Enclose links to things related to the bug using http://wowhead.com or any other TBC database.)
[//]: # (You can use screenshot ingame to visual the issue.)
[//]: # (Write your tickets according to the format:)
[//]: # ([Quest][Azuremyst Isle] Red Snapper - Very Tasty!)
[//]: # ([NPC] Magistrix Erona)
[//]: # ([Spell][Mage] Fireball)
[//]: # ([Npc][Drop] Ghostclaw Lynx)
[//]: # ([Web] Armory doesnt work)
[//]: # (To find server revision type `.server info` command in the game chat.)

**Description**: 
https://www.wowhead.com/quest=27409/the-essence-of-enmity

**Current behaviour**:
I discovered quite by accident this weird bug. I had killed a Firemane Ash Tail and used the totem on it to capture it's essence as per the quest description. As I am channeling the totem, another Ash Tail respawns and agros me. I complete the totem cast and both the body and the second Ash Tail poof. It is repeatable as I decided to see if it would do the same thing again. Killed a scout outside the cave and then ran over to an Ash Tail and got it agroed then ran back over to the body I killed and used the totem on it. Again both the body and the second agroed mob disappeared.

**Expected behaviour**: 
body should disappear but not any other mobs.

**Server Revision**:

**Comment by Evolvee** [comment]
fixed in next rev
