### ISSUE TITLE
[Extremely Poor Drop Rate] Skullsplitter Tusks & Troll Witchery [FIX IMMEDIATELY]

### ISSUE THREAD

**Issue by Kaidalen** [Atlantiss/NetherwingBugtracker#6002]
[//]: # (Enclose links to things related to the bug using http://wowhead.com or any other TBC database.)
[//]: # (You can use screenshot ingame to visual the issue.)
[//]: # (Write your tickets according to the format:)
[//]: # ([Quest][Azuremyst Isle] Red Snapper - Very Tasty!)
[//]: # ([NPC] Magistrix Erona)
[//]: # ([Spell][Mage] Fireball)
[//]: # ([Npc][Drop] Ghostclaw Lynx)
[//]: # ([Web] Armory doesnt work)
[//]: # (To find server revision type `.server info` command in the game chat.)

**Description**:  Quests requires to collect 18 Skullsplitter Tusks, collected 6 in the past 1hr, for Troll Wichery, collected 1/4 in 45 minutes. And I have continued to die because the respawn timers are so quick its ridiculous In STV.  They're multiple quests like this that are suffering from low drop rates. **PLEASE FIX IMMEDIATELY**. ****

**Current behaviour**: **Extremely low Drop rates**

**Expected behaviour**:  Drop rates should be normal or above normal, shouldn't be doing a quest for 2hrs. It is utter ridiculous. 

**Server Revision**:  3035

**Comment by danbopes** [comment]
Can you please show some research to back up your claim that drop rates should be normal or above normal?

Additionally, adding "[FIX IMMEDIATELY]" to your title, is likely going to detract the devs from fixing it.

**Comment by Drayo** [comment]
These shit quests are known to be completely fucked, they are the same on every vanilla server too. Either the drop-rates recorded are scuffed or they just simply were that retarded.

Not really the fault of NW though.

**Comment by Evolvee** [comment]
wtf is this report "Skullsplitter Tusks" are not for quest Troll Wichery.

**Comment by Evolvee** [comment]
both items are fine, actually slightly higher than retail had
