### ISSUE TITLE
[Pending sale in mail bug] Said my item got sold but it was pending

### ISSUE THREAD

**Issue by Kaidalen** [Atlantiss/NetherwingBugtracker#6003]
[//]: # (Enclose links to things related to the bug using http://wowhead.com or any other TBC database.)
[//]: # (You can use screenshot ingame to visual the issue.)
[//]: # (Write your tickets according to the format:)
[//]: # ([Quest][Azuremyst Isle] Red Snapper - Very Tasty!)
[//]: # ([NPC] Magistrix Erona)
[//]: # ([Spell][Mage] Fireball)
[//]: # ([Npc][Drop] Ghostclaw Lynx)
[//]: # ([Web] Armory doesnt work)
[//]: # (To find server revision type `.server info` command in the game chat.)

**Description**: The item that was sold was pending, but later that day when I logged in I clicked on the same letter and it just said it was sold, but the gold wasn't attatched to the mail. This has happened to five sales that I sold. Missed about 10g roughly. 

**Current behaviour**: Saying Pending sale Then not getting the gold

**Expected behaviour**:  Getting gold from my sales from Auction House.

**Server Revision**:  3035

**Comment by Easyfraggy** [comment]
The gold arrives in a seperate mail.
