### ISSUE TITLE
[Black Temple] [NPC] Flame of Azzinoth

### ISSUE THREAD

**Issue by Drayo** [Atlantiss/NetherwingBugtracker#6004]
[//]: # (Enclose links to things related to the bug using http://wowhead.com or any other TBC database.)
[//]: # (You can use screenshot ingame to visual the issue.)
[//]: # (Write your tickets according to the format:)
[//]: # ([Quest][Azuremyst Isle] Red Snapper - Very Tasty!)
[//]: # ([NPC] Magistrix Erona)
[//]: # ([Spell][Mage] Fireball)
[//]: # ([Npc][Drop] Ghostclaw Lynx)
[//]: # ([Web] Armory doesnt work)
[//]: # (To find server revision type `.server info` command in the game chat.)

**Current behaviour**: Flame of Azzinoth seem to be very sensitive when is comes to them adjusting their position. They were turning their back to the tank very often, when I compared their distance to the tank with some old videos I noticed that they stood much closer to the tank compared to NW.

This is an issue because they can VERY easily breathe the raid due to this.

**Expected behaviour**: I think they should not readjust as often as they do, I'm not sure what can be done to fix this. Maybe reduce their hitbox, then again, in the retail video you can see the melee attacking from a decent distance, so idk. He only tries to stand too close to the tank I guess?

 I can say with confidence though that they should indeed reposition, just in a less sensitive manner.

https://youtu.be/Y1v6BrxgJDY?t=342

**Server Revision**: 3035

**Comment by Tenoutoften** [comment]
You can notice the red circle is significantly larger compared to Netherwing

**Comment by Easyfraggy** [comment]
Melee range is correct size. Just need to reduce the trigger range to back away from target to 2-3 yards at most.

**Comment by Wolffenstein** [comment]
Fixed in rev 3050.
