### ISSUE TITLE
[Black Temple] [NPC] Illidan - Hitbox

### ISSUE THREAD

**Issue by Drayo** [Atlantiss/NetherwingBugtracker#6006]
[//]: # (Enclose links to things related to the bug using http://wowhead.com or any other TBC database.)
[//]: # (You can use screenshot ingame to visual the issue.)
[//]: # (Write your tickets according to the format:)
[//]: # ([Quest][Azuremyst Isle] Red Snapper - Very Tasty!)
[//]: # ([NPC] Magistrix Erona)
[//]: # ([Spell][Mage] Fireball)
[//]: # ([Npc][Drop] Ghostclaw Lynx)
[//]: # ([Web] Armory doesnt work)
[//]: # (To find server revision type `.server info` command in the game chat.)

**Current behaviour**: Illidans hitbox seems to be very small, making him spazz out from time to time, even going through the tank occasionally. Pets can also very easily parry haste him sometimes even though they are visually behind him.

**Expected behaviour**: His hitbox should be a tad bigger to prevent him from spazzing out.

**Server Revision**: 3035

**Comment by Wolffenstein** [comment]
Fixed in rev 3038.
