### ISSUE TITLE
[Core][Loot] Master Loot does not respect the set quality threshold

### ISSUE THREAD

**Issue by Mintey** [Atlantiss/NetherwingBugtracker#6007]
**Description**: 
Master loot doesn't respect the set quality threshold, and makes the master looter have to assign every single item that drops. It creates a very tedious experience for the masterlooter, who needs to check and assign every drop from every mob in a raid. 

**Current behaviour**:
Currently all items are flagged for master looting, regardless of item quality and the set threshold, with nothing being able to be picked up by other group members. 

**Expected behaviour**: 
Items of a quality below the set threshold should not be flagged for master looting, and be able to be picked up by the person whos mob it is, just as in group-loot. 

**Server Revision**: 
3035

**Comment by ircfelix** [comment]
Bump. Super annoying during raids.

**Comment by Suzaru** [comment]
Still going strong, sadly :(

**Comment by Manaci** [comment]
Fixed with loot rework
