### ISSUE TITLE
Rift Lords' threat table is criticallly non-functional in H BM.

### ISSUE THREAD

**Issue by alxmke** [Atlantiss/NetherwingBugtracker#6008]
[//]: # (Enclose links to things related to the bug using http://wowhead.com or any other TBC database.)
[//]: # (You can use screenshot ingame to visual the issue.)
[//]: # (Write your tickets according to the format:)
[//]: # ([Quest][Azuremyst Isle] Red Snapper - Very Tasty!)
[//]: # ([NPC] Magistrix Erona)
[//]: # ([Spell][Mage] Fireball)
[//]: # ([Npc][Drop] Ghostclaw Lynx)
[//]: # ([Web] Armory doesnt work)
[//]: # (To find server revision type `.server info` command in the game chat.)

**Description**: 
Rift Lords' threat table is criticallly non-functional in H BM.
**Current behaviour**:
Rift Lords reset during H BM even if someone dies (sometimes) even if there are other players attacking him.
**Expected behaviour**: 
They should be tethered to all players involved in combat.
**Server Revision**:

**Comment by Easyfraggy** [comment]
Did you pull him too far away from his portal? He is tethered to his portal so if you pull him too far he resets.

**Comment by The14me** [comment]
Cant reproduce in 3460.
