### ISSUE TITLE
[Quest]Voren'thal's Visions

### ISSUE THREAD

**Issue by AWIDIUS** [Atlantiss/NetherwingBugtracker#6011]
I'm not able to pick up quest "Voren'thal's Visions" from Arcanist Adyria. Basically the quest isn't shown. Quest should be avaiable right after Scyers reputation goes bellow neutral (unfriendly and further) https://db.excalibur.ws/?quest=10024 . I meet these requirements but still don't have any options how to turn to scyers.

**Comment by AWIDIUS** [comment]
![image](https://user-images.githubusercontent.com/45521546/60168527-49af6280-9805-11e9-902f-8d953643a651.png)

**Comment by Evolvee** [comment]
Requires "Allegiance to the Aldor" (10551) or "Allegiance to the Scryers" (10552) to take "Voren'thal's Visions" (10024)
