### ISSUE TITLE
[Dungeon] Tempest Keep summon 2.1

### ISSUE THREAD

**Issue by veekk** [Atlantiss/NetherwingBugtracker#6012]
**Description**: When I made bug while 203 that that's not possible to summon to TK and Netherstorm as well, I've got an answer that that was done before 2.1.0. Here is 2.1.0 and still not possible to summon

**Current behaviour**: not possible to summon

**Expected behaviour**:  should be 

**Server Revision**: 3032

**Comment by Kolmarwow** [comment]
https://www.engadget.com/2008/02/03/netherstorm-summoning-restriction-lifted/

"To accompany the information about patch 2.4 regarding the ability to summon into instances, Tigole popped into the Elitist Jerks forums with another handy detail."

warlock summons in netherstorm weren't a thing until 2.4 as you can see.
