### ISSUE TITLE
Riding speed enchants do not stack properly

### ISSUE THREAD

**Issue by ndnd123** [Atlantiss/NetherwingBugtracker#6014]
[//]: # (Enclose links to things related to the bug using http://wowhead.com or any other TBC database.)
[//]: # (You can use screenshot ingame to visual the issue.)
[//]: # (Write your tickets according to the format:)
[//]: # ([Quest][Azuremyst Isle] Red Snapper - Very Tasty!)
[//]: # ([NPC] Magistrix Erona)
[//]: # ([Spell][Mage] Fireball)
[//]: # ([Npc][Drop] Ghostclaw Lynx)
[//]: # ([Web] Armory doesnt work)
[//]: # (To find server revision type `.server info` command in the game chat.)

**Description**: Riding speed enchants do not stack properly. Enchant to gloves, boots, carrot on a stick and crop do not stack somehow.

The speed boost should be 19% but when compared to a Paladin on Crusader at 20% the speed difference seems huge, like 10% speed difference, which is obviously wrong.

**Current behaviour**:

The speed boost should be 19% but when compared to a Paladin on Crusader at 20% the speed difference seems huge, like 10% speed difference, which is obviously wrong.

**Expected behaviour**: 

**Server Revision**:

**Comment by Evolvemademedothis** [comment]
https://worldofwarcraft.fandom.com/et/wiki/Mount/Increasing_your_speed

Riding Crop doesn't stack with any other mounted speed increasing items, spells or effects

**Comment by Wolffenstein** [comment]
Those should not stack.
