### ISSUE TITLE
Can't pick up the quest 'I know a guy' in Ironforge

### ISSUE THREAD

**Issue by Trollwarlock** [Atlantiss/NetherwingBugtracker#6015]
[//]: # (https://www.wowhead.com/quest=6612/i-know-a-guy)
[//]: # (Write your tickets according to the format:)
[//]: # ([Quest][Ironforge] I know a guy...)
[//]: # ([NPC] Daryl Riknussun)
[//]: # ([Web] Can't pick up quest)
[//]: # (To find server revision type `.server info` command in the game chat.)

I cannot pick up the mentioned quest even though I am eligible (lvl 48, 225 cooking skill): 

No exclamation mark appears above Daryl Rikunussuns head. He acts as any other profession trainer.

Exclamation mark above his head and I should be able to pick up quest.

**Comment by Evolvee** [comment]
works for me

delete cache
