### ISSUE TITLE
[Dungeon] Slave Pens [NPC] Coilfang Enchantress and Sootsayer

### ISSUE THREAD

**Issue by tuverentetil** [Atlantiss/NetherwingBugtracker#6016]
**Description**: 
If player is entangled by roots and then mind controlled when MC expires and then roots, player is unable to move
**Current behaviour**:
Stuck in place until relog.
**Expected behaviour**: 
Obv. player should be able to move after roots expire.
**Server Revision**:

**Comment by Tenoutoften** [comment]
The Enchantress hurricane is incredibly weak in heroic version by the way

**Comment by Godmatik** [comment]
Already fixed with the general mind control update done on rev 3813

Can close
