### ISSUE TITLE
[Core] 2.1.0 stamina drink and food

### ISSUE THREAD

**Issue by veekk** [Atlantiss/NetherwingBugtracker#6017]
**Description**:  https://wowwiki.fandom.com/wiki/Patch_2.1.0
Rumsey Rum, Rumsey Rum Light, Rumsey Rum Dark, Rumsey Rum Black Label, Halaani Whiskey, Gordok Green Grog, Raptor Punch, Stormstout, Trogg Ale, and Thunderbrew Lager: The stat bonuses from these drinks no longer stacks with stamina bonuses from other foods.

**Current behaviour**: stacks

**Expected behaviour**: shouldn't

**Server Revision**:

**Comment by Evolvee** [comment]
which one in particular stacks rn?

**Comment by veekk** [comment]
crawdad (30stam) + Rumsey Rum black label e.g.

**Comment by Evolvee** [comment]
@Wolffenstein

**Comment by Manaci** [comment]
@Wolffenstein When is this gonna be fixed? It's been over a month now to revert it to stock and not the custom pre-2.1 that was made.

**Comment by The14me** [comment]
rev. 3460 still an issue.

**Comment by The14me** [comment]
Rev 3455 and 3460 still an issue (Tested on NW and Kara)

**Comment by Godmatik** [comment]
Was fixed on Netherwing last year, closing
