### ISSUE TITLE
[Raid][TK/SSC][Recipe] Plans: Red Havoc Boots

### ISSUE THREAD

**Issue by veekk** [Atlantiss/NetherwingBugtracker#6018]
**Description**: 2 bugs related to this recipe:
1. we've got like 6 this recipes and 0 another boots recipes by 2 raid id.
2. I'm as BS can't see this recipe in loot, but another members of raid can see that. It's BoE recipe, so should be shown for everyone, seems like loot filter flag broken

**Server Revision**: 3041

**Comment by Easyfraggy** [comment]
Can confirm the loot flag being wrong. The plans dropping 6 times is just rng though.

**Comment by veekk** [comment]
rnh that from like 8 diff recipes dropped 6 the same?

**Comment by veekk** [comment]
btw it's 8 same plans for 1.5week and no any different

**Comment by veekk** [comment]
9th boots and no any changes, that's almost impossible in case that each recipe have the same drop rate

**Comment by veekk** [comment]
3 more red havoc from 2 packs :) same for another guilds

**Comment by Evolvee** [comment]
is there a list of patterns that can drop from tk?

**Comment by veekk** [comment]
same problem with both t5 raids, gonna change title, sorry for that

**Comment by veekk** [comment]
by the way AH full of red havoc boots and nothing else, seems like at allys side situation the same

**Comment by veekk** [comment]
[Red Havoc Boots](https://www.wowhead.com/item=30324/plans-red-havoc-boots)
[Boots of the Protector](https://www.wowhead.com/item=30323/plans-boots-of-the-protector)
[Boots of Blasting](https://www.wowhead.com/item=30282/pattern-boots-of-blasting)
[Boots of the Long Road](https://www.wowhead.com/item=30283/pattern-boots-of-the-long-road)

As we can see those items (as any another recipes aswell) can be dropped from any almost any both  TK/SSC mobs with ALMOST same chances. In case of Boots of the protector chance even more then red havoc boots, but NOW it seems like bob recipe trigger proccing and rolling between recipes with red havoc 99.99% and another recipes 0.001% 0.001% 0.001%, not sure about current random implementation but seems like this

**Comment by Evolvee** [comment]
well i need a list of all recipes that got added with 2.1. and should drop in
A) TK
B) SSC
