### ISSUE TITLE
[Raid][TK] Trash shooting through the wall

### ISSUE THREAD

**Issue by veekk** [Atlantiss/NetherwingBugtracker#6019]
**Description**:  In room before alar when u're fighting birds and 2 elves, elves shooting through the wall and ruining los pulls at all

**Current behaviour**: in desc

**Expected behaviour**:  should run to raid until los is gone

**Server Revision**: 3041

**Comment by Easyfraggy** [comment]
It's not a bug afaik - these mobs just ignore LOS with their shots. Need some proof.

**Comment by veekk** [comment]
shooting by arrows through the wall that's fine?:D
I'll try to prove it in few days with actual wow pov

**Comment by Evolvemademedothis** [comment]
https://www.wowhead.com/npc=20037/tempest-falconer#comments


By Ssateneth (12,964 – 2·22·109) on 2008/05/16 (Patch 2.4.1) 

These guys can't be LoS'd anymore for some reason; they're shooting through the wall.

**Comment by veekk** [comment]
but that was about patch 2.4, and "anymore" means that previously there was possibility to los em

**Comment by Easyfraggy** [comment]
Post some proof if you want it reopened.
