### ISSUE TITLE
[Object][Ogri'la] Apexis Monuments & Fel Crystal Prisms have a few issues. 

### ISSUE THREAD

**Issue by Kolmarwow** [Atlantiss/NetherwingBugtracker#6020]
**Description**: 
In Blade's Edge Mountains there are some objects near Ogri'la that are used to summon bosses which drop Apexis Crystals that are used for reputation rewards. 

You insert 35 Apexis Shards into either the Apexis Monument or Fel Crystal Prism to summon these bosses, but currently you can only do so if you are on the respective quests for them (Apexis Monument = "Guardian of the Monument" and Fel Crystal Prism = "A Fel Whip for Gahk"). This makes it significantly harder to farm Apexis Crystals for reputation items and you should be able to summon them at any time as long as you have shards on you.

Additionally the bosses that come out of these objects feel like they might be undertuned, the quests recommend to bring 5 players but it's very easy to 2-man them since they have barely any health and do very low damage as well as having nearly 0 abilities. Their names are "Apexis Guardian" from the Monument and "Galvanoth" "Braxxus" "Mo'arg Incinerator" "Zarcsin" from the Fel Crystal Prisms.  

Lastly, the Fel Crystal Prisms seem to not have their RP scripted as they say "Greetings <Name" when I try to interact with them. 

The Fel Crystal Prisms are located in the Forge Camps to the North/South of Ogri'la and the Apexis Monuments are located near the border of the Forge Camps. 

**Server Revision**: 
3041

**Comment by Wolffenstein** [comment]
Fixed in rev 3673.
