### ISSUE TITLE
[Core][Flask] Flask bought for marks doesn't work until relog

### ISSUE THREAD

**Issue by veekk** [Atlantiss/NetherwingBugtracker#6021]
**Description**:  Flask that was bought for Marks doesn't affect player until reload if they're was used inside of raid instance. Also it works if it was outside, and when u enter raid after - it works

**Current behaviour**: works after reload or location changing to raid instance

**Expected behaviour**: right after usage inside of raid instance

**Server Revision**: 3041

**Comment by toporc26** [comment]
bump, this is still occurring and very annoying for the good folks still raiding T5+ content!

**Comment by Wolffenstein** [comment]
Fixed in rev 3163.
