### ISSUE TITLE
[Quest] "Banish The Demons" - Not getting kill credit

### ISSUE THREAD

**Issue by Kolmarwow** [Atlantiss/NetherwingBugtracker#6023]
**Description**: 
"Banish The Demons" is quest gotten from Kronk at Ogri'la after reaching honored with their faction.

What you do in this quest is you create a banishing portal with the use of an quest item called the "Banishing Crystal" which you get when accepting the quest. You lay down the portal in one of the Forge Camps near Ogri'la and start slaying demons near the portal to "banish" them. 

Currently killing them near the portal does not give quest credit, making the quest not possible to complete.  

**Server Revision**: 
3041

**Comment by bekonja** [comment]
Can confirm, not working properly.

**Comment by JevinCode** [comment]
Can confirm, not working.

**Comment by tetsugoro** [comment]
Having the same experience, can't get kills to count.

**Comment by earywen** [comment]
Can confirm, not working.

**Comment by thiccasian** [comment]
very much can confirm

**Comment by earywen** [comment]
Any ETA on this guys? :)

**Comment by rangobob** [comment]
Still not working

**Comment by Evolvee** [comment]
rev 3066
