### ISSUE TITLE
[Quest] Wrangle Some Aether Rays! - At least 1 aether ray remains after q complete.

### ISSUE THREAD

**Issue by eri1997** [Atlantiss/NetherwingBugtracker#6024]
**Description**: https://www.wowhead.com/quest=11065/wrangle-some-aether-rays

**Current behaviour**: After  you complete the quest at least 1 aether ray remains and follows you around until relog or leave the area.

**Expected behaviour**: All Aether Rays should dissapear/stop following you after you turn them in for the quest

**Server Revision**: 3041

**Comment by eri1997** [comment]
Did the quest again today and it seems the aether rays despawn after a set time instead of when you turn in the quest.

**Comment by Evolvee** [comment]
fixed
