### ISSUE TITLE
wsg flag cap

### ISSUE THREAD

**Issue by teddys** [Atlantiss/NetherwingBugtracker#6027]
**Current behaviour**: Standing on top of your team's flag with the enemy team's flag doesn't result in an instant cap once your flag is returned. You have to run out and run back in a couple of times before it works.

**Expected behaviour**:  Standing on top of your team's flag with the enemy team's flag results in an instant cap once your flag is returned. 

**Server Revision**:  3041

**Comment by Evolvee** [comment]
https://youtu.be/ZcozAF2c4-s?t=123

yikes

**Comment by DarthGamer** [comment]
I also noticed this in WSG as few weekends ago, so it's been here a while I believe. At the time though I did not really think about it.
