### ISSUE TITLE
[Item] Mark of Defiance

### ISSUE THREAD

**Issue by Turbie333** [Atlantiss/NetherwingBugtracker#6028]
**Description**: 
2.2 Mark of Defiance caster trinket from hellfire tower PvP should be proc'ing more often than current scripted version does now. 

**Current behaviour**:
Seems to only proc 2-3 times per 5 minutes if that. (Melee/hunter version of trinket seems to proc 6 per minute, not sure if that matters)

**Expected behaviour**: 
Link below is 2.2 version, comments seem to say this trinket was reliable for caster dps at the time. 
https://www.wowhead.com/item=27922/mark-of-defiance#comments

Only diff for 2.2 version is for dots and channeled spells. Proc rate still seems low for normal spells.
I would think it would be scripted for % instead of internal cd

**Comment by The14me** [comment]
There is nothing bugged in that.
Tested it with a warlock.
PS: https://www.wowhead.com/item=27922/mark-of-defiance#comments:id=153995:reply=15431
Can be closed.
