### ISSUE TITLE
Can't exchange [Item] Deathwing Brood Cloak for [Item] Apexis Crystal

### ISSUE THREAD

**Issue by kemotix** [Atlantiss/NetherwingBugtracker#6029]
[//]: # (Enclose links to things related to the bug using http://wowhead.com or any other TBC database.)
[//]: # (You can use screenshot ingame to visual the issue.)
[//]: # (Write your tickets according to the format:)
[//]: # ([Quest][Azuremyst Isle] Red Snapper - Very Tasty!)
[//]: # ([NPC] Magistrix Erona)
[//]: # ([Spell][Mage] Fireball)
[//]: # ([Npc][Drop] Ghostclaw Lynx)
[//]: # ([Web] Armory doesnt work)
[//]: # (To find server revision type `.server info` command in the game chat.)

**Description**: 
Can't exchange Deathwing Brood Cloak for Apexis Crystal.

**Current behaviour**:
[NPC] Sky Commander Keller won't talk to me, despite having [Item] Deathwing Brood Cloak in my bags.

**Expected behaviour**: 
Wowhead Comment from 2.1
the dragons themselves don't drop these, you need to kill all 4, combine their scales to make a cloak and then turn them in to Keller for a crystal 
https://www.wowhead.com/item=32572/apexis-crystal#comments

WoWwiki:
Combine the scales to create a [Deathwing Brood Cloak]. If you do not like the enchantment on the cloak, take it to Sky Commander Keller and he will trade you an Apexis Crystal.
https://wowwiki.fandom.com/wiki/Apexis_Crystal

**Server Revision**: 
3041

**Comment by kemotix** [comment]
Any ETA?
Without Crystals reputation rewards are unobtainable.

**Comment by mhawkins30** [comment]
Still an issue as of 3093.

**Comment by Wolffenstein** [comment]
Fixed in rev 3101.
