### ISSUE TITLE
Trading doesnt work sometimes

### ISSUE THREAD

**Issue by Knoox** [Atlantiss/NetherwingBugtracker#603]
**When doing a gnomer run, we tried to trade each other but it needed a relogg before it allowed us
![wowscrnshot_092618_013817](https://user-images.githubusercontent.com/18479169/46052401-9bc03c00-c13e-11e8-8a0f-4812b227a01d.jpg)
*:

**Comment by wtRCH** [comment]
Might happen in Raids too

**Comment by Tereneckla** [comment]
When you try to trade each other at the same time or trade someone who is busy with a vendor, mailbox or auctioneer for example the trading bugs out.
To reset this you have to run out of the trading range.

**Comment by Easyfraggy** [comment]
This is a client bug. Nothing server side can do about it afaik.
