### ISSUE TITLE
[Spell][Rogue] Deadly Throw

### ISSUE THREAD

**Issue by Scierwojad** [Atlantiss/NetherwingBugtracker#6030]
**Description**: Silience effect does not work properly

**Current behaviour**: Silience effect is triggered when the thrown hits the target. Target can finish the cast while thrown is mid flight.

**Expected behaviour**: Silience effect should occour on skill use. Target should get silienced in the moment you just use the skill.

**Server Revision**:

**Comment by teddys** [comment]
This was fixed like 3 years ago, why is it broken again?
