### ISSUE TITLE
[Spell][Druid] Feral Charge

### ISSUE THREAD

**Issue by Scierwojad** [Atlantiss/NetherwingBugtracker#6031]
**Description**: Feral Charge silience works incorrect

**Current behaviour**: Feral Charge silience effect occours when bear gets to the target. Target can finish while druid is in the proces of charging.

**Expected behaviour**: Silience effect should trigger immediatley after using the skill

**Server Revision**:

**Comment by Macumbafeh** [comment]
Still buging....

**Comment by tsuone** [comment]
No longer bugged.
