### ISSUE TITLE
[Spell][Paladin] Consecration

### ISSUE THREAD

**Issue by Scierwojad** [Atlantiss/NetherwingBugtracker#6032]
**Description**: Consecration hits target mid air

**Current behaviour**: Consecration ticks targets jumping over it.

**Expected behaviour**: It should be possible to jump over consecration without getting damage and interrupting stealth

**Server Revision**:

**Comment by Evolvee** [comment]
lol proof?

**Comment by Evolvemademedothis** [comment]
The way jumping works in WoW atleast in the earlier expansions, not sure if it's changed or when it was changed is that your characters hitbox is calculated from the area you initiated the jump from and it is then re calculated after you've landed again, therefore if a spell is used and would affect your character in the area you initiated the jump from and you still havent landed it should affect you mid air aswell.

**Comment by Godmatik** [comment]
Does not work on classic
