### ISSUE TITLE
[Spell][Warlock] Felhunter pet

### ISSUE THREAD

**Issue by Scierwojad** [Atlantiss/NetherwingBugtracker#6033]
**Description**: Felhunter Pet

**Current behaviour**: It is impossible to sap warlock with Felhunter on aggressive stance

**Expected behaviour**: It should be possible to sap warlock with Felhunter on aggressive stance

**Server Revision**:

**Comment by Evolvee** [comment]
@Wolffenstein stealth ticks probably not applied to pet detection, therefore it detects everyone instantly

**Comment by The14me** [comment]
Not an issue anymore in rev 3460.
Can be closed.

**Comment by Evolvee** [comment]
doubtful
