### ISSUE TITLE
[Spell][Racial] Shadowmeld

### ISSUE THREAD

**Issue by Scierwojad** [Atlantiss/NetherwingBugtracker#6034]
**Description**: Shadowmeld boosts rogues and druid stealth way too much.

**Current behaviour**: Being an elf makes your stealth too strong. In season one I was playing as a dwarf rogue (subtelity build with improved stealth), and was getting opened by resto druids all the time. In season two I changed my race to human (perception), crafted engineering goggles and jevelcrafting panthera, equiped stealth level boots to maximize my stealth properties. Dont have problem with druids anymore, but I am still failing to detect night elf rogues (I am getting sapped whit percpeption turned on and dont even see the rogue!! It happens almost every time !!) This makes playing arenas as a rogue a nightmare. 73 stealth level with stealth detecion goggles and perception turned on and still impossible to find night elf rogue on arena.
**Expected behaviour**: Shadowmeld should **slightly** increase the stealth level for night elves. 

**Server Revision**:

**Comment by ronyc** [comment]
Confirmed, shadowmeld should be 1 stealth level iirc.

**Comment by ronyc** [comment]
Can this get some attention? It's so stupid that night elf druid has better stealth than a rogue.

**Comment by Wolffenstein** [comment]
The stacking issue with Shadowmeld was already fixed. Night Elf Druids/Rogues also are much harder to detect as the tooltip says:

![image](https://user-images.githubusercontent.com/1576644/62834261-0b9dbf00-bc4a-11e9-8ef4-9479954e073f.png)

**Comment by ronyc** [comment]
Yes harder by 1 stealth level not 10 or whatever it currently is.

**Comment by ronyc** [comment]
> The stacking issue with Shadowmeld was already fixed. Night Elf Druids/Rogues also are much harder to detect as the tooltip says:
> 

"Much harder" in this case means 1 stealth level aka as if the druid/rogue is 71 instead of 70. Currently its close to 10 stealth levels. I have to be standing on top of them to see them.
