### ISSUE TITLE
Darkmoon Card: Crusade - procs from Arcane Missiles/Improved Scorch not correct

### ISSUE THREAD

**Issue by Grookshank** [Atlantiss/NetherwingBugtracker#6035]
**Description**: Casting Arcane Missiles should proc 1 stack of "Aura of the Crusader" from Darkmoon Card: Crusade **per missile** (3-5 depending on spell rank).
It should also get stacks from the Ignite effect (mage fire talent).

**Current behaviour**: Arcane Missiles only adds 1 stack of "Aura of the Crusader" in total. Ignite does not cause stacks.

**Expected behaviour**: Arcane Missiles should add 1 stack of "Aura of the Crusader" **per missile** (3-5 per cast depending on rank).
Ignite should also cause an additional stack.

**Server Revision**: 3041

Sources:
Wowhead from patch 2.1: https://www.wowhead.com/item=31856/darkmoon-card-crusade#comments:id=97645

Wowwiki from patch 2.1: https://wowwiki.fandom.com/wiki/Darkmoon_Card:_Crusade?oldid=1546651

**Comment by Dekirayne** [comment]
can confirm this

**Comment by Wolffenstein** [comment]
Proof for Ignite?

**Comment by Dekirayne** [comment]
erm idk about the ignite part, i only know for the AM

**Comment by Grookshank** [comment]
Proof for ignite: https://wowwiki.fandom.com/wiki/Darkmoon_Card:_Crusade?oldid=1546651. He calls it Scorch, but the tick is called ignite.

**Comment by Wolffenstein** [comment]
Arcane Missiles fixed in rev 3046.

**Comment by Dekirayne** [comment]
ty

**Comment by Grookshank** [comment]
Ok, I think my link to Ignite was wrong. The correct info in indeed it should double proc from Improved Scorch:
See: https://www.wowhead.com/forums&topic=10648/best-two-trinkets-pre-bt-hyjal-for-mage#p97498

**Comment by Wolffenstein** [comment]
Fixed in rev 3050.
