### ISSUE TITLE
[Raid][Black Temple] Reliquary of Souls mana issue for druids

### ISSUE THREAD

**Issue by Dollywog** [Atlantiss/NetherwingBugtracker#6036]
[//]: # (Enclose links to things related to the bug using http://wowhead.com or any other TBC database.)
[//]: # (You can use screenshot ingame to visual the issue.)
[//]: # (Write your tickets according to the format:)
[//]: # ([Quest][Azuremyst Isle] Red Snapper - Very Tasty!)
[//]: # ([NPC] Magistrix Erona)
[//]: # ([Spell][Mage] Fireball)
[//]: # ([Npc][Drop] Ghostclaw Lynx)
[//]: # ([Web] Armory doesnt work)
[//]: # (To find server revision type `.server info` command in the game chat.)

**Description**:  Playing feral druid causes big issues for mana on this boss.  During phase 2 with the mana aura, when you powershift forms you get what appears to be  a stacking exponentially +10% buff to mana pool.  Eventually once it reached somewhere around 99Million mana it completely bugs out and you have 0/0 maximum mana.

**Current behaviour**:  Doesn't reset on death.

**Expected behaviour**:  Fixed by logging out.  However, this wiped my guild as I needed to be in bear form and when I went to shift I had 0 maximum mana that I could replenish

[Similar issue occurs on mana effects of the Green Portal beam on Netherspite on this server]

**Comment by Manaci** [comment]
[Core/Black Temple]:
- Fixed a bug with Aura of Desire which caused player's mana to bug out

 Already in the changelog.

**Comment by Dollywog** [comment]
Still broken....

**Comment by Dollywog** [comment]
If anything it is even worse because now it consistently gives you 0 mana instead of double mana

**Comment by Tereneckla** [comment]
can't replicate anymore / fixed
