### ISSUE TITLE
Priest Spell damage issues

### ISSUE THREAD

**Issue by Crysanthemum** [Atlantiss/NetherwingBugtracker#6037]
[//]: # (Enclose links to things related to the bug using http://wowhead.com or any other TBC database.)
[//]: # (You can use screenshot ingame to visual the issue.)
[//]: # (Write your tickets according to the format:)
[//]: # ([Quest][Azuremyst Isle] Red Snapper - Very Tasty!)
[//]: # ([NPC] Magistrix Erona)
[//]: # ([Spell][Mage] Fireball)
[//]: # ([Npc][Drop] Ghostclaw Lynx)
[//]: # ([Web] Armory doesnt work)
[//]: # (To find server revision type `.server info` command in the game chat.)

**Description**: 
The spell damage for certain items either do not add up properly or are bugged with the priest talent Spiritual Guidance.
**Current behaviour**:
Adding up my gear/gems, i should have a naked, pre-talent spell damage of 250, with my talent it should be at 328, it is at 166.  I also have the Divine Spirit talent (which seems to work normally, adding 45ish to both) and the +healing calculates properly from items, it only seems to be the damage.  When i swap certain items that should increase my dmg, it goes down, and i cannot be certain about all of my gear, but i know Collar of Command should give me +29 bonus dmg (22 from the effect, 7 from the spirit with my talent), Shadowbrim Travel Hat, should give me 26 bonus dmg...instead, with Travel Hat i get to 184 dmg, and the Collar gets me only to 166...very weird.  There are other pieces that have similar effects like boots, idk how many other individual pcs are broken, or if it is an issue with the talent(s).  Please reach out if there is anything else i can do.
**Expected behaviour**: 
Math!!
**Server Revision**: 
i am not a coder nor do i know anyone that is, I very much hope this issue can be resolved, since i am at almost 1/2 spell damage as a result.

**Comment by Tereneckla** [comment]
Get the tooltip addon from Netherwing or simply ignore the +damage shown on healing items.
+Damage on healing items only got added in 2.3 and Netherwing is on 2.1
