### ISSUE TITLE
Stromgarde keep

### ISSUE THREAD

**Issue by Kraybana** [Atlantiss/NetherwingBugtracker#6038]
[//]: # (Enclose links to things related to the bug using http://wowhead.com or any other TBC database.)
[//]: # (You can use screenshot ingame to visual the issue.)
[//]: # (Write your tickets according to the format:)
[//]: # ([Quest][Azuremyst Isle] Red Snapper - Very Tasty!)
[//]: # ([NPC] Magistrix Erona)
[//]: # ([Spell][Mage] Fireball)
[//]: # ([Npc][Drop] Ghostclaw Lynx)
[//]: # ([Web] Armory doesnt work)
[//]: # (To find server revision type `.server info` command in the game chat.)

**Description**: 

**Current behaviour**:

**Expected behaviour**: 

**Server Revision**:

**Comment by Kraybana** [comment]
The mobs in the tower behind the keep are constantly respawning once you kill one.

**Comment by Evolvee** [comment]
cant reproduce

probably quest-related and you are mistaken

provide more info next time
