### ISSUE TITLE
[Core] Graveyards

### ISSUE THREAD

**Issue by NatsumeLily** [Atlantiss/NetherwingBugtracker#6039]
[//]: # (Enclose links to things related to the bug using http://wowhead.com or any other TBC database.)
[//]: # (You can use screenshot ingame to visual the issue.)
[//]: # (Write your tickets according to the format:)
[//]: # ([Quest][Azuremyst Isle] Red Snapper - Very Tasty!)
[//]: # ([NPC] Magistrix Erona)
[//]: # ([Spell][Mage] Fireball)
[//]: # ([Npc][Drop] Ghostclaw Lynx)
[//]: # ([Web] Armory doesnt work)
[//]: # (To find server revision type `.server info` command in the game chat.)

**Description**: What graveyards you should spawn at. Died in northern Darkshore as horde and was sent to the graveyard in Eastern Ashenvale   

**Current behaviour**: Some graveyards seem to be faction based.

**Expected behaviour**: Graveyards shouldn't be faction based. You should be sent to the nearest graveyard even if it isn't your factions graveyard.

**Server Revision**: 3041

**Comment by Evolvee** [comment]
> Graveyards shouldn't be faction based. You should be sent to the nearest graveyard even if it isn't your factions graveyard.

bs

**Comment by NatsumeLily** [comment]
That isn't "bs"...Where the hell do you think an Alliance player will be sent if they die in org? OHH the graveyard outside org. Graveyards are not locked the a faction.

But I'll edit this and reopen since that isn't what seems to be happening since there is a graveyard horde spawn at in southern Darkshore, so why didn't it send me there?

**Comment by Evolvee** [comment]
ashenvale
