### ISSUE TITLE
[Gnomeregan] Dark Iron Land Mine 

### ISSUE THREAD

**Issue by Knoox** [Atlantiss/NetherwingBugtracker#604]
**It does around 6 damage according to Tinno, was unable to find a entry in the combat log**: 
![wowscrnshot_092618_010613](https://user-images.githubusercontent.com/18479169/46052497-06717780-c13f-11e8-8868-050b0925140a.jpg)

**Comment by Tinnoan** [comment]
![screenshot 2018-09-26 01 05 43](https://user-images.githubusercontent.com/25431721/46052542-37ea4300-c13f-11e8-84cd-4f012d5c5fc8.png)

**Comment by Evolvee** [comment]
rev xdd
