### ISSUE TITLE
[Item][Drop] Schematic: Healing Potion Injector drop rate seems extremely low

### ISSUE THREAD

**Issue by Kolmarwow** [Atlantiss/NetherwingBugtracker#6041]
**Description**: 
The item "Schematic: Healing Potion Injector" is a random world drop and i believe the drop rate might be way too low at the moment, here's my reasoning:

1. Wowhead comments & Wowhead item drop data seem to indicate that both the healing & mana potion injector schematics should have a similar drop rate, dropping from roughly 75 - 100 mobs in the world. 
https://www.wowhead.com/item=23883/schematic-healing-potion-injector
https://www.wowhead.com/item=23884/schematic-mana-potion-injector

2. At the moment the above is absolutely not the case on Netherwing, I've been checking the AH daily for months for the recipe and i've seen the mana potion injector schematic daily but never the healing potion injector one. 
According to this [external auction house database site](https://www.wow-auctionhouse.com/atlantiss/Netherwing_Alliance?search=Schematic%3A+Healing+Potion+Injector&time=1y), it has only recorded the healing potion injector schematic **twice** on the alliance auction house on Netherwing since the server launched in January, once in March and once recently in June. On the other hand if you look at its [data for the mana potion injector schematic](https://www.wow-auctionhouse.com/atlantiss/Netherwing_Alliance?search=Schematic%3A+Mana+Potion+Injector&time=1y) it has been seen much more regularly.

3. Most private server TBC databases list the [Mana Potion Schematic](https://tbcdb.com/?item=23884) as dropping from about ~200 mobs while the [Healing Potion Injector](https://tbcdb.com/?item=23883) drops from exactly 12 mobs. I have a strong feeling that this is also how it is on Netherwing right now since it completely matches what the auction house database says & what i've seen by checking the AH daily. If this were blizzlike then I would imagine the Wowhead comments would be saying "this is an extremely rare recipe so expect to pay thousands of gold for it" but there are no such comments, they say that in their experience they could usually buy it for between 100-200g which seems to say that the overall world drop rate should be much higher. 

**Server Revision**: 
3041

**Comment by The14me** [comment]
Its supposed to be super low, but worth a check and if everything is ok-->close.

**Comment by Wolffenstein** [comment]
Fixed in rev 3462.
