### ISSUE TITLE
T4 Priest (flexibility buff broken/overpowered)

### ISSUE THREAD

**Issue by elvau** [Atlantiss/NetherwingBugtracker#6042]
[//]: # (Enclose links to things related to the bug using http://wowhead.com or any other TBC database.)
[//]: # (You can use screenshot ingame to visual the issue.)
[//]: # (Write your tickets according to the format:)
[//]: # ([Quest][Azuremyst Isle] Red Snapper - Very Tasty!)
[//]: # ([NPC] Magistrix Erona)
[//]: # ([Spell][Mage] Fireball)
[//]: # ([Npc][Drop] Ghostclaw Lynx)
[//]: # ([Web] Armory doesnt work)
[//]: # (To find server revision type `.server info` command in the game chat.)

**Description**: 
[Buff/Gear Bonus] Holy Priest T4 Bonus "flexibility" overpowered/broken
**Current behaviour**:
After casting 5 flash heals, a greater heal only consumes one stack of flexibility. That means you can switch between Flash Heal / GH and always have a 2 second (without haste) GH cast. 
**Expected behaviour**: 
A greater Heal should consume all the stacks from Flexibility and you should stack them again with new Flash Heals
**Server Revision**: 
3041

**Comment by Wolffenstein** [comment]
Fixed in rev 3050.
