### ISSUE TITLE
[ITEMS] with healing and damage doeas not give bonus dmg

### ISSUE THREAD

**Issue by ksotto** [Atlantiss/NetherwingBugtracker#6043]
![1](https://user-images.githubusercontent.com/52424941/60458985-3e629980-9c40-11e9-9657-07b97c46f44e.jpg)
![2](https://user-images.githubusercontent.com/52424941/60458986-3efb3000-9c40-11e9-9def-f2f6159ccc21.jpg)
![3](https://user-images.githubusercontent.com/52424941/60458987-3efb3000-9c40-11e9-9550-0c12dc203f7f.jpg)

[//]: # (Enclose links to things related to the bug using http://wowhead.com or any other TBC database.)
[//]: # (You can use screenshot ingame to visual the issue.)
[//]: # (Write your tickets according to the format:)
[//]: # ([Quest][Azuremyst Isle] Red Snapper - Very Tasty!)
[//]: # ([NPC] Magistrix Erona)
[//]: # ([Spell][Mage] Fireball)
[//]: # ([Npc][Drop] Ghostclaw Lynx)
[//]: # ([Web] Armory doesnt work)
[//]: # (To find server revision type `.server info` command in the game chat.)

**Description**: 
at least 2 items which should give bonus healing and bonus damage give only bonus healing which is horribly wrong!

**Current behaviour**:
atleast 2 items :  [Holy Shroud] [Truefaith Gloves] only give bonus healing, despite fact that it say it gives bonus damage too!

**Expected behaviour**: 
it shoul work as tooltip says healing done up to x and damage done up to y
**Server Revision**:

**Comment by Evolvee** [comment]
healing items dont add dmg until 2.3.
