### ISSUE TITLE
[NPC] Escape from Skettis

### ISSUE THREAD

**Issue by toporc26** [Atlantiss/NetherwingBugtracker#6046]
[//]: # (Enclose links to things related to the bug using http://wowhead.com or any other TBC database.)
[//]: # (You can use screenshot ingame to visual the issue.)
[//]: # (Write your tickets according to the format:)
[//]: # ([Quest][Azuremyst Isle] Red Snapper - Very Tasty!)
[//]: # ([NPC] Magistrix Erona)
[//]: # ([Spell][Mage] Fireball)
[//]: # ([Npc][Drop] Ghostclaw Lynx)
[//]: # ([Web] Armory doesnt work)
[//]: # (To find server revision type `.server info` command in the game chat.)

**Description**: 
Quest "Escape from Skettis" unable to be done since the NPC "Skyguard Prisoner" does not spawn. Had a party member sit at one spot for 10~ minutes while I flew around on my epic flyer to the other two spots. Not once did I see the NPC spawn, let alone someone else doing the escort.
**Current behaviour**:
NPC Skyguard Prisoner does not seem to respawn at any of the 3 current spawn locations
**Expected behaviour**: 
NPC Skyguard Prisoner should respawn, be it on a timer, or one of the other escorts completing/failing at one of the 3 spawn locations
**Server Revision**: 
3054

**Comment by Kolmarwow** [comment]
this still seems to be an issue but the weird thing is it only sometimes happens. like 80% of the time this quest has worked fine with no issues but the other 20% of the time i'd go to Skettis and the prisoners wouldn't spawn anywhere for over 30 minutes. i have no idea what's causing this to happen unfortunately.
