### ISSUE TITLE
[PTR] Theramore Combat Dummy

### ISSUE THREAD

**Issue by mbzz88** [Atlantiss/NetherwingBugtracker#6047]
**Description**: Dummies are not invincible

**Current behaviour**: Combat dummies have very low HP, and can be killed
![WoWScrnShot_070219_140207](https://user-images.githubusercontent.com/43509267/60477054-04da6e80-9cd2-11e9-955b-584caaf443b2.jpg)

**Expected behaviour**: Cannot kill dummy

**Server Revision**: 3055

**Comment by Easyfraggy** [comment]
Need some proof that these should even be attackable.

**Comment by mbzz88** [comment]
Can't find a video of it anywhere, but:
https://www.wowhead.com/npc=4952/theramore-combat-dummy

By Nerizor (18,481 – 3·30·128) on 2007/10/31 (Patch 2.2.3)
Immortal Dummies for everyone, Yay!

By MashedIdiot (11,537 – 2·8·54) on 2008/10/17 (Patch 3.0.2)		
They can be attacked as of patch 2.4.3.

**Comment by Evolvee** [comment]
fixed in next rev
