### ISSUE TITLE
[NPC][Mind Control][Priest]

### ISSUE THREAD

**Issue by Infailing** [Atlantiss/NetherwingBugtracker#6049]
[//]: # (Enclose links to things related to the bug using http://wowhead.com or any other TBC database.)
[//]: # (You can use screenshot ingame to visual the issue.)
[//]: # (Write your tickets according to the format:)
[//]: # ([Quest][Azuremyst Isle] Red Snapper - Very Tasty!)
[//]: # ([NPC] Magistrix Erona)
[//]: # ([Spell][Mage] Fireball)
[//]: # ([Npc][Drop] Ghostclaw Lynx)
[//]: # ([Web] Armory doesnt work)
[//]: # (To find server revision type `.server info` command in the game chat.)

**Description**: 
Using Mind Control on npcs should let you use some of their abilities.

**Current behaviour**:
Don't know really about the outworld, but most of Scarlet Monastery elite mobs don't have any active abilities for you to use. Exceptions are Scarlet Gallant and Scarlet Beastmaster.

**Expected behaviour**: 
There should many more abilities to use while you mind controlling the npcs.
For example, being able to heal while controlling Scarlet Chaplain.

**Comment by Evolvee** [comment]
thats npc to npc, not global mind control problem
