### ISSUE TITLE
Heroic strike happens after Disarm effect

### ISSUE THREAD

**Issue by FrozenBread** [Atlantiss/NetherwingBugtracker#605]
[//]: # (Enclose links to things related to the bug using http://wowhead.com or any other TBC database.)
[//]: # (You can use screenshot ingame to visual the issue.)
[//]: # (Write your tickets according to the format:)
[//]: # ([Quest][Azuremyst Isle] Red Snapper - Very Tasty!)
[//]: # ([NPC] Magistrix Erona)
[//]: # ([Spell][Mage] Fireball)
[//]: # ([Npc][Drop] Ghostclaw Lynx)
[//]: # ([Web] Armory doesnt work)

**Description**: 
Heroic Strike is still executed if you have queued the action after you get disarmed.
**Current behaviour**:
Heroic Strike is a skill that requires a weapon to be used. It seems that it has a weapon check to be queued for the next autoattack but there must not be a secondary weapon check on execution.
**Expected behaviour**: 
There should be a secondary weapon check on execution. If you have been disarmed, you are currently not wearing a weapon, thus rendering heroic strike cancelled and having a regular autoattack with fists happen.
**Server Revision**:

**Comment by Wolffenstein** [comment]
Fixed in rev 2061.
