### ISSUE TITLE
[Quest] Overseeing and You: Making the Right Choices

### ISSUE THREAD

**Issue by lordofdrapes** [Atlantiss/NetherwingBugtracker#6050]
[//]: # (Enclose links to things related to the bug using http://wowhead.com or any other TBC database.)
[//]: # (You can use screenshot ingame to visual the issue.)
[//]: # (Write your tickets according to the format:)
[//]: # ([Quest][Azuremyst Isle] Red Snapper - Very Tasty!)
[//]: # ([NPC] Magistrix Erona)
[//]: # ([Spell][Mage] Fireball)
[//]: # ([Npc][Drop] Ghostclaw Lynx)
[//]: # ([Web] Armory doesnt work)
[//]: # (To find server revision type `.server info` command in the game chat.)

**Description**: 
Can't turn in the quest [Overseeing and You: Making the Right Choices].
https://imgur.com/a/Wx8HuiR
**Current behaviour**:
Cannot turn in a completed quest.

**Expected behaviour**: 
Turning in a quest.

**Server Revision**:

**Comment by Evolvee** [comment]
disable your addons, clear cache and try to look for other quests in your quest log that require the same items
