### ISSUE TITLE
[NPC] Shadow Demons during Illidan

### ISSUE THREAD

**Issue by FabianMueller77** [Atlantiss/NetherwingBugtracker#6051]
[//]: # (Enclose links to things related to the bug using http://wowhead.com or any other TBC database.)
[//]: # (You can use screenshot ingame to visual the issue.)
[//]: # (Write your tickets according to the format:)
[//]: # ([Quest][Azuremyst Isle] Red Snapper - Very Tasty!)
[//]: # ([NPC] Magistrix Erona)
[//]: # ([Spell][Mage] Fireball)
[//]: # ([Npc][Drop] Ghostclaw Lynx)
[//]: # ([Web] Armory doesnt work)
[//]: # (To find server revision type `.server info` command in the game chat.)

**Description**: 
The Shadow Demons during Illidan's phase 4 don't target random raid members 
**Current behaviour**:
They target the players who are furthest away from Illidan:
![Shadow Demons](https://user-images.githubusercontent.com/46138731/60506623-85936d80-9cc6-11e9-95aa-f35576d00bc9.png)
**Expected behaviour**: 
They should target 5 random raid members
![nihilum](https://user-images.githubusercontent.com/46138731/60506639-8e843f00-9cc6-11e9-950b-9c9f0e2694d7.png)

**Server Revision**: 
3054

**Comment by ircfelix** [comment]
If they should target random people (targeting the tank makes no sense though, but maybe someone finds proof that they can), 54k hp is a bit too much. If they go for a very close target you NEED to have a frost mage with imp blizzard to slow them enough to not reach someone nearby.

**Comment by FabianMueller77** [comment]
Nihilum first kill video ( https://www.youtube.com/watch?v=k8_JbDiALkY ) shows them targetting people, who are closer to illidan than some other raid members AND targetting their warlock tank (player with the diamond raidmark in the picture)
![image](https://user-images.githubusercontent.com/46138731/61641856-2ced3a00-aca0-11e9-8eed-841f7502b228.png)

**Comment by Wolffenstein** [comment]
Fixed in rev 3087. I reduced their health a bit as well.
