### ISSUE TITLE
[Item] Murkblood Escape Plans

### ISSUE THREAD

**Issue by bekonja** [Atlantiss/NetherwingBugtracker#6052]
[//]: # (Enclose links to things related to the bug using http://wowhead.com or any other TBC database.)
[//]: # (You can use screenshot ingame to visual the issue.)
[//]: # (Write your tickets according to the format:)
[//]: # ([Quest][Azuremyst Isle] Red Snapper - Very Tasty!)
[//]: # ([NPC] Magistrix Erona)
[//]: # ([Spell][Mage] Fireball)
[//]: # ([Npc][Drop] Ghostclaw Lynx)
[//]: # ([Web] Armory doesnt work)
[//]: # (To find server revision type `.server info` command in the game chat.)

**Description**: 
https://db.excalibur.ws/?item=32726
https://www.wowhead.com/item=32726/murkblood-escape-plans

**Current behaviour**:
1% droprate

**Expected behaviour**: 
5-10% droprate after all conditions are met
(note that objects have 50% droprate from sludges so when someone reports 30 kills to get a quest it translates to ~6% actual droprate)
Proofs:

> Think I killed around 40-50 before the Sludge-covered Object with the plans dropped

> I had to kill 20-30 and it finally dropped

> Also notice, that the drop rate listed on wowhead is not correct. It's more like 5-10%

> I think the 1% drop rate is an overestimate.

> Actually the 1.4% droprate is an underestimate.

> Also notice, that the drop rate listed on wowhead is not correct. It's more like 5-10%.

> The Drop is more than 2% its about 20% so keep killing :)

Reason why it displays 1% in wowhead:

> It is considerably higher due to the fact that if you have done it already you will not get it in the Sludge-covered objects. So every person looting those objects after completing the quest help make the percentage lower :)

**Server Revision**: 
3054

**Comment by Evolvee** [comment]
fixed in next rev
