### ISSUE TITLE
[Item] Relentless Earthstorm Diamond only working for physical damage

### ISSUE THREAD

**Issue by kramnoitseuq** [Atlantiss/NetherwingBugtracker#6053]
In patch 2.1.2, Relentless Earthstorm Diamond was fixed to apply to ALL types of damage, not just physical. This is clearly stated in the patch notes:

_Relentless Earthstorm Diamond: The bonus damage to critical strikes from this metagem now applies to all types of damage, not just physical._

https://wowwiki.fandom.com/wiki/Patch_2.1.2

**Current behaviour**: Only affects physical critical damage.

**Expected behaviour**: Should apply to all critical damage.

**Server Revision**: 3054

**Comment by Wolffenstein** [comment]
I don't know how you've tested it, but it's working correctly. It's using 2.4.3 data.
