### ISSUE TITLE
Aether Ray respawn timers

### ISSUE THREAD

**Issue by Lyricah** [Atlantiss/NetherwingBugtracker#6058]
[//]: # (Enclose links to things related to the bug using http://wowhead.com or any other TBC database.)
[//]: # (You can use screenshot ingame to visual the issue.)
[//]: # (Write your tickets according to the format:)
[//]: # ([Quest][Azuremyst Isle] Red Snapper - Very Tasty!)
[//]: # ([NPC] Magistrix Erona)
[//]: # ([Spell][Mage] Fireball)
[//]: # ([Npc][Drop] Ghostclaw Lynx)
[//]: # ([Web] Armory doesnt work)
[//]: # (To find server revision type `.server info` command in the game chat.)

**Description**: Aether Ray spawn timers seem to be way off.

**Current behaviour**:very long respawn timers 

**Expected behaviour**: should be around 5 minute respawn time

**Server Revision**:

**Comment by Evolvee** [comment]
pooled in next rev
