### ISSUE TITLE
[Talent][Hunter] Rapid killing application

### ISSUE THREAD

**Issue by NatsumeLily** [Atlantiss/NetherwingBugtracker#6059]
[//]: # (Enclose links to things related to the bug using http://wowhead.com or any other TBC database.)
[//]: # (You can use screenshot ingame to visual the issue.)
[//]: # (Write your tickets according to the format:)
[//]: # ([Quest][Azuremyst Isle] Red Snapper - Very Tasty!)
[//]: # ([NPC] Magistrix Erona)
[//]: # ([Spell][Mage] Fireball)
[//]: # ([Npc][Drop] Ghostclaw Lynx)
[//]: # ([Web] Armory doesnt work)
[//]: # (To find server revision type `.server info` command in the game chat.)

**Description**: Hunter talent Rapid killing application.

**Current behaviour**: When killing a enemy that yields exp or honour, you get the Rapid killing buff but only if you kill it with melee and in melee range.

**Expected behaviour**: The buff should be applied at any range when killed by any ranged attack and all pet attacks.

**Server Revision**: 3054

**Comment by Kaidalen** [comment]
Bump this

**Comment by Manaci** [comment]
Fixed
