### ISSUE TITLE
[Gnomeregan] Irradiated debuff

### ISSUE THREAD

**Issue by Knoox** [Atlantiss/NetherwingBugtracker#606]
**Visual bugg of not displaying the apporiate time**:
![wowscrnshot_092618_001456](https://user-images.githubusercontent.com/18479169/46052596-6bc56880-c13f-11e8-80d9-03fa2240f9ec.jpg)

**Comment by Easyfraggy** [comment]
Should be fixed long ago, please reopen if it persist.
