### ISSUE TITLE
[Priest][Spell] Inner Focus expended by Touch of Weakness

### ISSUE THREAD

**Issue by b15andga** [Atlantiss/NetherwingBugtracker#6060]
[//]: # (Enclose links to things related to the bug using http://wowhead.com or any other TBC database.)
[//]: # (You can use screenshot ingame to visual the issue.)
[//]: # (Write your tickets according to the format:)
[//]: # ([Quest][Azuremyst Isle] Red Snapper - Very Tasty!)
[//]: # ([NPC] Magistrix Erona)
[//]: # ([Spell][Mage] Fireball)
[//]: # ([Npc][Drop] Ghostclaw Lynx)
[//]: # ([Web] Armory doesnt work)
[//]: # (To find server revision type `.server info` command in the game chat.)

**Description**: 
[Inner Focus](https://tbcdb.com/?spell=14751): When activated, reduces the mana cost of your next spell by 100% and increases its critical effect chance by 25% if it is capable of a critical effect.
[Touch of Weakness](https://tbcdb.com/?spell=25461): The next melee attack on the caster will cause 80 Shadow damage and reduce the damage caused by the attacker by 35 for 120 sec.
**Current behaviour**:
The Touch of Weakness debuff application, not cast, expends the Inner Focus buff. In the following images, I used Inner Focus, begun casting Mind Blast, had my cast interrupted by Intercept (yes, interrupted, no cast, no dmg, no CD), got melee swung, the melee swinger was afflicted by my Touch of Weakness, and that expended my Inner Focus.
![image](https://user-images.githubusercontent.com/18015872/60563620-de154a00-9d5c-11e9-825e-e43e5f9619f9.png)
![image](https://user-images.githubusercontent.com/18015872/60563638-f5ecce00-9d5c-11e9-8213-cb55c076794b.png)

**Expected behaviour**: 
Touch of Weakness debuff application should not expend Inner Focus buff. Pressumably the debuff application counts as a cast, thus expends Inner Focus and likely receives the +25 % crit chance as well.
**Server Revision**: 
3054

**Comment by Evolvee** [comment]
https://wowwiki.fandom.com/wiki/Patch_2.2.0
![image](https://user-images.githubusercontent.com/1942409/61372668-1443e500-a898-11e9-8119-b74ff5a5f4e8.png)

**Comment by Wolffenstein** [comment]
Fixed in rev 3078.
