### ISSUE TITLE
[Raid][SSC][Hydross] Spell Immunity during initial Phase

### ISSUE THREAD

**Issue by ecox245** [Atlantiss/NetherwingBugtracker#6061]
[//]: # (Enclose links to things related to the bug using http://wowhead.com or any other TBC database.)
[//]: # (You can use screenshot ingame to visual the issue.)
[//]: # (Write your tickets according to the format:)
[//]: # ([Quest][Azuremyst Isle] Red Snapper - Very Tasty!)
[//]: # ([NPC] Magistrix Erona)
[//]: # ([Spell][Mage] Fireball)
[//]: # ([Npc][Drop] Ghostclaw Lynx)
[//]: # ([Web] Armory doesnt work)
[//]: # (To find server revision type `.server info` command in the game chat.)

**Description**: 
On initial phase (when he is Frost) he is not immune to Frost damage. Transitioning to poison and back to frost again, he is now immune to frost like before. We tested nature damage on the first transition to Poison, but it seems transitioning fixes his wonky phase 1 resistance. 

**Current behaviour**:
Varying spell immunity between first Frost phase and the rest of the fight

**Expected behaviour**: 
Immune to Frost for the whole fight? I don't know whats intended but this aint right my dudes. 

**Server Revision**: 
3054

**Comment by ircfelix** [comment]
Like who the fuck does frost dmg in the initial phase 1?

**Comment by Wolffenstein** [comment]
Fixed in rev 3064.
