### ISSUE TITLE
Hunter Flare range not visually showing correctly

### ISSUE THREAD

**Issue by Maikie1234** [Atlantiss/NetherwingBugtracker#6064]
**Description**: The visual range of Flare is smaller than the range of the spell itself. Rogues/Ferals getting de-stealthed even they arent visually in range of the Flare spell. I tested it with 3 hunters, none of them had any "Flare range boost" whatsoever. Attaching two screenshots of me testing it with a hunter, flare on the ground, first screenshot of me in stealth aproaching the flare, second one is the moment i got kicked out of stealth by the Flare
![WoWScrnShot_070419_160303](https://user-images.githubusercontent.com/51025270/60672588-13618b00-9e76-11e9-9559-63014e88a981.jpg)
![WoWScrnShot_070419_160308](https://user-images.githubusercontent.com/51025270/60672589-13618b00-9e76-11e9-9c69-8c5208b890fc.jpg)

**Current behaviour**: Flare spell range larger than visually shown

**Expected behaviour**:  Flare spell range should be the exact same as shown by visual

**Server Revision**: 3057

**Comment by Evolvee** [comment]
turn "spell detail" into maximum in video settings

**Comment by Maikie1234** [comment]
I have all my video settings set to maximum, attaching a screenshot with my video settings. Also the hunters, which i tested this with, sayd that they see this the same way as I do, meaning from their point of view, i wasnt in the Flare range eighter.
![WoWScrnShot_070419_204651](https://user-images.githubusercontent.com/51025270/60684262-e5437180-9e9c-11e9-88e9-a5596045f71d.jpg)

**Comment by raethkcj** [comment]
Watch a video of a hunter placing a flare, the targeting reticle is much larger than the flare graphic. As a stealth class, you need to learn the size of that targeting reticle rather than just looking at the flare.

**Comment by The14me** [comment]
There is not a bug there.Its a client side.
Can be closed.
