### ISSUE TITLE
(Random server disconnect) Server randomly disconnects and stays stuck

### ISSUE THREAD

**Issue by Kaidalen** [Atlantiss/NetherwingBugtracker#6066]
[//]: # (Enclose links to things related to the bug using http://wowhead.com or any other TBC database.)
[//]: # (You can use screenshot ingame to visual the issue.)
[//]: # (Write your tickets according to the format:)
[//]: # ([Quest][Azuremyst Isle] Red Snapper - Very Tasty!)
[//]: # ([NPC] Magistrix Erona)
[//]: # ([Spell][Mage] Fireball)
[//]: # ([Npc][Drop] Ghostclaw Lynx)
[//]: # ([Web] Armory doesnt work)
[//]: # (To find server revision type `.server info` command in the game chat.)

**Description**:  Its happened about 6 times in the past four (4) days, I have randomly disconnected from server, I have tried to re connect and it just goes to server list and won't go to character select just server select. I have to wait 10-15 minutes, Maybe even more till it fixes itself before I can log in again

**Current behaviour**:  Random crashes to log in screen, log in get to server select screen and can't continue from there, its like the server is offline even though it shows its online. Have to wait 10-15 minutes or longer before I can log back in. Usually when I realise this happens I get a massive lag spike (from Australia) and it disconnects me. 

**Expected behaviour**:  Shouldn't server crash

**Server Revision**:  Latest server revision. Can't log in

**Comment by The14me** [comment]
I mean...its some strange personal issue. But since a lot of things get fixed, that issue must be fixed too (since no complaint about issue like that).
Can be closed.
