### ISSUE TITLE
Pet movement issues

### ISSUE THREAD

**Issue by Cukez** [Atlantiss/NetherwingBugtracker#6069]
[//]: # (Enclose links to things related to the bug using http://wowhead.com or any other TBC database.)
[//]: # (You can use screenshot ingame to visual the issue.)
[//]: # (Write your tickets according to the format:)
[//]: # ([Quest][Azuremyst Isle] Red Snapper - Very Tasty!)
[//]: # ([NPC] Magistrix Erona)
[//]: # ([Spell][Mage] Fireball)
[//]: # ([Npc][Drop] Ghostclaw Lynx)
[//]: # ([Web] Armory doesnt work)
[//]: # (To find server revision type `.server info` command in the game chat.)

**Description**: 
Hey Guys ✌️
Since i dont find any post to this bug I want to inform you about some issues with the movement of pets.

**Current behaviour**:
While fighting Lurker in SSC my pet didn't accomplished to walk from one platform to another. It just standing on the edge doing nothing. Petattack and Petfollow doesn't work. Sometimes it suddenly changes the platforms, but it seems to be random. Additionally when it stands on the middle circle platform it doesn't move into meele range. So as a BM hunter it's a loss of 30-40% dps. Since I tamed a Windserpent it does some dmg through lightning breath at least. Anyways I don't think that this behavior is wanted.

**Expected behaviour**: 
 I think it should be able to pass every stair I can pass as well as through jumping?

This is just one example for similar situations when the pet has to walk past minor stairs.
As a ingame workaround there is the only option to dismiss the pet and call it back everytime it has to change plattforms. To let it reach the meele range I had to move there myself while pet is passiv.
But in situations like fighting Lurker I will be busy postioning pet and avoiding Lurkers attaks and there will be more less dmg.

I hope there are some ways to fix this issue in future and i could help to improve this Server.
Thanks for your support and work on this Server 💕

**Server Revision**:

**Comment by Kaidalen** [comment]
BUMP. I Confirm this

**Comment by Kaidalen** [comment]
Bump I can **Confirm**. **Hunters are the MOST broken class on this server (in a bad way)**

**Comment by Tereneckla** [comment]
https://www.youtube.com/watch?v=FwQ1h5tt02E
https://www.youtube.com/watch?v=MFOK2zgJPYI
Park it on the middle platform
