### ISSUE TITLE
Zul'furak mallet

### ISSUE THREAD

**Issue by Triise** [Atlantiss/NetherwingBugtracker#6070]
[//]: #https://classic.wowhead.com/item=9241/sacred-mallet
[//]: # (You can use screenshot ingame to visual the issue.)
[//]: # (Write your tickets according to the format:)
[//]: # ([Quest][Azuremyst Isle] Red Snapper - Very Tasty!)
[//]: # ([NPC] Magistrix Erona)
[//]: # ([Spell][Mage] Fireball)
[//]: # ([Npc][Drop] Ghostclaw Lynx)
[//]: # ([Web] Armory doesnt work)
[//]: # (To find server revision type `.server info` command in the game chat.)

**Description**: The Sacred Mallet for Mallet of Zul'Farrak is not working at the alter after the last update.

**Current behaviour**: *Requires Alter to work*

**Expected behaviour**: Creates Mallet of Zul'Farrak

**Server Revision**:

**Comment by Evolvee** [comment]
you need to stand on the altar
![image](https://user-images.githubusercontent.com/1942409/61214868-60acea80-a709-11e9-9456-6d9bead0e786.png)
