### ISSUE TITLE
Friend List Bugged

### ISSUE THREAD

**Issue by auxplox** [Atlantiss/NetherwingBugtracker#6072]
All of online friends were NOT on the top of the friend list. Instead, they were scattered (some on the bottom, some in the middle, etc). it was very difficult to find friends, especially when some said 'Unknown'. And sometimes the friends list would not even load up at all.

A couple of ways of -sometimes- /temporarily/ fixing this was to add a friend (even if the friend list was full, which it always was), and then things would jump into order (for a while). 

Also, when no friends showed up on list, i had to click on a different tab, such as 'Who' and then back to 'Friends' and they will appear again (but still out of order usually)

The solution was: if there was a friend on your list that had deleted their character, then your whole friends list is bugged. @Daystar helped me find and remove the culprit!

**Comment by teddys** [comment]
confirming this, it's actually very annoying

**Comment by kramnoitseuq** [comment]
you dont have any friends, teddys

**Comment by danbopes** [comment]
Fixed in rev 3122

**Comment by teddys** [comment]
3140

not fixed
