### ISSUE TITLE
Mounting Brazen in CoT Durnholde as you are kicked from an instance group causes hilarious bug

### ISSUE THREAD

**Issue by trclocke** [Atlantiss/NetherwingBugtracker#6074]
[//]: # (Enclose links to things related to the bug using http://wowhead.com or any other TBC database.)
[//]: # (You can use screenshot ingame to visual the issue.)
[//]: # (Write your tickets according to the format:)
[//]: # ([Quest][Azuremyst Isle] Red Snapper - Very Tasty!)
[//]: # ([NPC] Magistrix Erona)
[//]: # ([Spell][Mage] Fireball)
[//]: # ([Npc][Drop] Ghostclaw Lynx)
[//]: # ([Web] Armory doesnt work)
[//]: # (To find server revision type `.server info` command in the game chat.)

**Description**: 
-Enter CoT Durnholde (Old Hillsbrad)
-leave group, starting the "you are not part of this instance's group and will be hearthed" timer
-Get incendiary bombs from [NPC] Erozion, then talk to the drake [NPC] Brazen near the entrance
-Just as you are about to be booted from the instance, click the "I'm ready to go to Durnholde" dialogue option
https://www.wowhead.com/npc=18723/erozion
https://www.wowhead.com/npc=18725/brazen

**Current behaviour**:
You will begin flying on the drake toward Durnholde, then (when the teleport timer ends) be ported to your hearth location (shattrath scryer's tier for me). You will remain on the drake, flying at the speed you were going (drake's wings flapping like crazy). I ended up flying northeast through Hellfire Peninsula, and eventually to the void beyond Netherstorm. Eventually the drake despawns, and your character falls.

**Expected behaviour**: 
Drake should instantly despawn when player is moved to hearthstone location.

**Server Revision**: 
3060

**Comment by Wolffenstein** [comment]
Fixed in rev 3063.
