### ISSUE TITLE
[Quest][Tanaris][Armorsmith] Can't find Heavy Mithril Boots 

### ISSUE THREAD

**Issue by OlhoVazio** [Atlantiss/NetherwingBugtracker#6075]
[//]: # (Enclose links to things related to the bug using http://wowhead.com or any other TBC database.)
[//]: # (You can use screenshot ingame to visual the issue.)
[//]: # (Write your tickets according to the format:)
[//]: # ([Quest][Azuremyst Isle] Red Snapper - Very Tasty!)
[//]: # ([NPC] Magistrix Erona)
[//]: # ([Spell][Mage] Fireball)
[//]: # ([Npc][Drop] Ghostclaw Lynx)
[//]: # ([Web] Armory doesnt work)
[//]: # (To find server revision type `.server info` command in the game chat.)

**Description**: 
I am currently trying to become an armorsmith. The quest chain requires me to get materials and items and deliver them to the NPCs. But I can't find any trainer nor recipe for the ([Spell][Blacksmith] Heavy Mithril Boots) which I must deliver to complete the quest ([Quest][Tanaris] The World at your feet).
**Current behaviour**:
The trainer doesn't teach it nor can I find a recipe for it.
**Expected behaviour**: 
Shouldn't the recipe be taught by a goblin by the name of ([NPC] Brikk Keencraft) at Booty Bay?

References: https://classicdb.ch/?spell=9968
**Server Revision**:

**Comment by The14me** [comment]
They are there 
https://i.imgur.com/OVIvxQI.png
Rev 3460 (tested on Kara).
Can be closed.
