### ISSUE TITLE
[Quest][Drop][Skettis] Terokk's Downfall

### ISSUE THREAD

**Issue by adroth23** [Atlantiss/NetherwingBugtracker#6076]
[//]: # (Enclose links to things related to the bug using http://wowhead.com or any other TBC database.)
[//]: # (You can use screenshot ingame to visual the issue.)
[//]: # (Write your tickets according to the format:)
[//]: # ([Quest][Azuremyst Isle] Red Snapper - Very Tasty!)
[//]: # ([NPC] Magistrix Erona)
[//]: # ([Spell][Mage] Fireball)
[//]: # ([Npc][Drop] Ghostclaw Lynx)
[//]: # ([Web] Armory doesnt work)
[//]: # (To find server revision type `.server info` command in the game chat.)

**Description**: 
The jar required to summon terokk for the final stage of the terokk's downfall quest chain isn't reobtainable. The quest to receive a new jar is incompleteable due to items necessary from the bosses not dropping.
**Current behaviour**:
The 4 skettis bosses are supposed to drop their trophies so you can replace the jar required to summon terokk incase of failure. Items are not dropping even though it's a 100% drop rate
**Expected behaviour**: 
The bosses drop their trophies so you can obtain a new jar from the daily quest next to the terokk's downfall questgiver
**Server Revision**: 
3060

**Comment by Muzeyyen48** [comment]
I can confirm that completing the quest "Tokens of the Descendants" is impossible because tokens from minibosses don't drop if u complete it before.If there is someone in your party hasn't compelted quest he can loot quest items but u can't.

**Comment by QuelSera** [comment]
Still not repeatable

**Comment by Wolffenstein** [comment]
Should now be fixed.
