### ISSUE TITLE
NPC caster behavior regarding player cast immunities

### ISSUE THREAD

**Issue by mordero** [Atlantiss/NetherwingBugtracker#6077]
[//]: # (Enclose links to things related to the bug using http://wowhead.com or any other TBC database.)
[//]: # (You can use screenshot ingame to visual the issue.)
[//]: # (Write your tickets according to the format:)
[//]: # ([Quest][Azuremyst Isle] Red Snapper - Very Tasty!)
[//]: # ([NPC] Magistrix Erona)
[//]: # ([Spell][Mage] Fireball)
[//]: # ([Npc][Drop] Ghostclaw Lynx)
[//]: # ([Web] Armory doesnt work)
[//]: # (To find server revision type `.server info` command in the game chat.)

**Description**: Casters NPC's don't behave properly when dealing with players

**Current behaviour**: When casting in to an iceblocked mage, upon the casting being immune, the npc continues standing at range and casting in to the iceblock

**Expected behaviour**: The NPC in question should stop casting and close to melee range as seen here
https://www.youtube.com/watch?v=rpNFLwpIJzU

This was an common farming method, and the one shown in this video was one i personally used for months, commonly respeccing in to permafrost just to do it.

**Server Revision**:

**Comment by Evolvee** [comment]
@Wolffenstein explain how the fuck is this bugged again... i specifically spammed you about this + water elemental vs ice block prior to release and u said its fixed -.-

**Comment by Wolffenstein** [comment]
Fixed in rev 3067.
