### ISSUE TITLE
[NPC]Skyguard Khatie randomly despawns

### ISSUE THREAD

**Issue by mhawkins30** [Atlantiss/NetherwingBugtracker#6078]
**Description**: 
The questgiver [Skyguard Khatie](https://db.excalibur.ws/?npc=23335) despawns seemingly randomly.
**Current behaviour**:
More than half the time I visit the Sha'tari questgiver area next to Ogri'la, there are several players clustered around the spot where Khatie is supposed to be waiting for her to spawn. Just now, I was talking to her trying to grab the quest when she suddenly despawned.
**Expected behaviour**: 
She should not randomly despawn.
**Server Revision**: 
3060

**Comment by kemotix** [comment]
Sky Commander Keller also despawns. They do it at the same time

**Comment by Godmatik** [comment]
Was fixed a long time ago - the quest NPCs no longer randomly despawn
