### ISSUE TITLE
Mailbox limitations

### ISSUE THREAD

**Issue by ircfelix** [Atlantiss/NetherwingBugtracker#6079]
**Description**: 
Hi,

**Current behaviour**:
currently when you open all your mails, there are only displayed 50 mails (some days or a week ago it was 200 mails per "session") in your mail list until you relog or let ~1 minute pass after opening your last mail. This can be very annoying, if you want to open lots of mails.

**Expected behaviour**: 
It would be lovely to have the mailbox refresh rate faster and to be able to open more than 50 mails in one "session".

**Server Revision**: 
3060

**Comment by Wolffenstein** [comment]
Both 50 mail limit and 1 minute cooldown are blizzlike.
