### ISSUE TITLE
[Scarlet Monastery Graveyard] When zoning out

### ISSUE THREAD

**Issue by Knoox** [Atlantiss/NetherwingBugtracker#608]
**My pet goes to space, disapears for around 15 -20 seconds. Seeing how mobs are pathing there, its extremly noticable when the pet is lacking**: 
![wowscrnshot_092518_063146](https://user-images.githubusercontent.com/18479169/46052757-07ef6f80-c140-11e8-83ca-ccd8e67ed299.jpg)

**Comment by Tereneckla** [comment]
![WoWScrnShot_010720_140805](https://user-images.githubusercontent.com/50233983/71897538-29b70f00-3157-11ea-84fe-05ef77951716.jpg)

**Comment by Godmatik** [comment]
Probably fixed a long time ago, can not reproduce.

Closing.
