### ISSUE TITLE
(Flight Master bug) Shattarah / Hellfire to Zangermarsh not showing

### ISSUE THREAD

**Issue by Kaidalen** [Atlantiss/NetherwingBugtracker#6080]
[//]: # (Enclose links to things related to the bug using http://wowhead.com or any other TBC database.)
[//]: # (You can use screenshot ingame to visual the issue.)
[//]: # (Write your tickets according to the format:)
[//]: # ([Quest][Azuremyst Isle] Red Snapper - Very Tasty!)
[//]: # ([NPC] Magistrix Erona)
[//]: # ([Spell][Mage] Fireball)
[//]: # ([Npc][Drop] Ghostclaw Lynx)
[//]: # ([Web] Armory doesnt work)
[//]: # (To find server revision type `.server info` command in the game chat.)

**Description**:  Even though I have the flight path for Zangermarsh it doesn't show up on either flight paths.

**Current behaviour**: On the map during choosing which flight to take Zangermarsh isn't there even though I have the Zangermarsh flight

**Expected behaviour**: It should work. 

**Server Revision**:  3060
![dsdsdsdsd](https://user-images.githubusercontent.com/51963601/60770711-84789b00-a121-11e9-990b-7ec4db05745b.PNG)

**Comment by The14me** [comment]
Rev 3460 not an issue anymore.
https://i.imgur.com/OtABlcC.jpg
(it may be just a UI/cashe issue back then)
Can be closed.
