### ISSUE TITLE
[PVP][Diminishing Returns] Silence effects

### ISSUE THREAD

**Issue by bajkorv** [Atlantiss/NetherwingBugtracker#6081]
[//]: # (Enclose links to things related to the bug using http://wowhead.com or any other TBC database.)
[//]: # (You can use screenshot ingame to visual the issue.)
[//]: # (Write your tickets according to the format:)
[//]: # ([Quest][Azuremyst Isle] Red Snapper - Very Tasty!)
[//]: # ([NPC] Magistrix Erona)
[//]: # ([Spell][Mage] Fireball)
[//]: # ([Npc][Drop] Ghostclaw Lynx)
[//]: # ([Web] Armory doesnt work)
[//]: # (To find server revision type `.server info` command in the game chat.)

**Description**: Silence effects should share Diminishing Returns, to my knowledge there is only one type of silence effect and that means that they all should DR with eachother.

**Current behaviour**: At least Rogue Garrote with Imp Counterspell does not DR with eachother properly, Garrotte doesnt seem to DR even by itself. Probably also the case for more silences.

**Expected behaviour**: All silence effects should share DR and reduce the duration of silences used in a row.

this is link shows DR categories at least: https://vanilla-wow.fandom.com/wiki/Diminishing_returns

**Server Revision**: 3060

**Comment by Evolvee** [comment]
no
