### ISSUE TITLE
[Black Temple] Some Trash respawns when assigned boss is dead/missing boss assignment

### ISSUE THREAD

**Issue by Azalen** [Atlantiss/NetherwingBugtracker#6082]
**Description**: 
There are three mobs in the Supremus Area and one on the way to Teron Gorefiend that respawn every 2h even though the bosses are dead.
Since I cannot use .npc info anymore I did some screenshots:
![WoWScrnShot_070619_215248](https://user-images.githubusercontent.com/20336567/60774041-47ef7400-a10e-11e9-8116-2778780b2a69.jpg)
![WoWScrnShot_070619_215958](https://user-images.githubusercontent.com/20336567/60774042-47ef7400-a10e-11e9-8cb5-b0650d2335fd.jpg)

**Expected behaviour**: 
Mobs should not respawn after boss is dead.

**Server Revision**: 
[3066]

**Comment by Manaci** [comment]
Fixed
