### ISSUE TITLE
[Item] Fist of the Damned no scaling

### ISSUE THREAD

**Issue by Silbotronic** [Atlantiss/NetherwingBugtracker#6083]
[//]: # (Enclose links to things related to the bug using http://wowhead.com or any other TBC database.)
[//]: # (You can use screenshot ingame to visual the issue.)
[//]: # (Write your tickets according to the format:)
[//]: # ([Quest][Azuremyst Isle] Red Snapper - Very Tasty!)
[//]: # ([NPC] Magistrix Erona)
[//]: # ([Spell][Mage] Fireball)
[//]: # ([Npc][Drop] Ghostclaw Lynx)
[//]: # ([Web] Armory doesnt work)
[//]: # (To find server revision type `.server info` command in the game chat.)
**Current behaviour**: Fist of the Damned's proc doesn't scale with spell damage at all.
https://tbc-twinhead.twinstar.cz/?item=10804

**Expected behaviour**: It should scale with 100% of spell damage.
https://www.wowhead.com/item=10804/fist-of-the-damned#comments

**Server Revision**: 3060

**Comment by Manaci** [comment]
Fixed in rev 3202
