### ISSUE TITLE
[Loot][Patch 2.1][Raid][Hyjal] Choker of Serrated Blades not dropping in Mount Hyjal?

### ISSUE THREAD

**Issue by Haipethdev** [Atlantiss/NetherwingBugtracker#6084]
[//]: # (Enclose links to things related to the bug using http://wowhead.com or any other TBC database.)
[//]: # (You can use screenshot ingame to visual the issue.)
[//]: # (Write your tickets according to the format:)
[//]: # ([Quest][Azuremyst Isle] Red Snapper - Very Tasty!)
[//]: # ([NPC] Magistrix Erona)
[//]: # ([Spell][Mage] Fireball)
[//]: # ([Npc][Drop] Ghostclaw Lynx)
[//]: # ([Web] Armory doesnt work)
[//]: # (To find server revision type `.server info` command in the game chat.)

**Description**: 

Would anyone with DB access be able to check that https://tbc-twinhead.twinstar.cz/?item=32591 (the arp neck) is correctly on the Hyjal trash loot table?  I don't believe a single one has dropped on the server despite several guilds being exalted with Scale of the Sands already.  Please correct me if I am wrong.  It could be a oversight since it was changed in a later patch.

There has also been talk between guilds of other loot not dropping such as [Nethervoid Cloak](https://tbc-twinhead.twinstar.cz/?item=32590) which may be a wider issue of 2.1 trash loot.  

**Current behaviour**:

Not dropping at all (?).

**Expected behaviour**: 

Drops in MH in 2.1.

**Server Revision**: 3060

**Comment by ScottieDOESknow** [comment]
Most likely one of the following...

1. Bad RNG

2. Correct PTE loot tables

On retail this neck only dropped from BT trash until 2.2
![image](https://user-images.githubusercontent.com/43949261/60854456-50a77f00-a1ce-11e9-828a-73fda9c1fe3f.png)

**Comment by Haipethdev** [comment]
Can we confirm it drops in BT then?  I remembered the wrong way round, BT at 2.1 and Hyjal at 2.2.  I thought the opposite.

**Comment by Easyfraggy** [comment]
Wolf says its in the loot table.
