### ISSUE TITLE
Hunter pet ress bugg

### ISSUE THREAD

**Issue by Nymfhora** [Atlantiss/NetherwingBugtracker#6085]
**Description**: 
As im playing as a Hunter. i got killed by some horde. When i was gonna call my pet it says "Your target is dead" - when i go for revieve "You do not have a pet" and when i even try too tame another one, it says " you already controll a summoned creature". My pet is not at my stables either. Cant get him back by myself or even get another one. 
**Current behaviour**:
as above stated
**Expected behaviour**: 
To be able too ress you pet.
**Server Revision**: 
Character name: Nymfhora
Race: Night elf
Class: Hunter
Server: Netherwing (PVP)
Faction: Alliance. 

Ty!

**Comment by Manaci** [comment]
Should post on Discord, not here
