### ISSUE TITLE
[Quest][Blade's Edge Mountains]Banish the Demons

### ISSUE THREAD

**Issue by Refuge001** [Atlantiss/NetherwingBugtracker#6086]
[//]: # (Enclose links to things related to the bug using http://wowhead.com or any other TBC database.)
[//]: # (You can use screenshot ingame to visual the issue.)
[//]: # (Write your tickets according to the format:)
[//]: # ([Quest][Azuremyst Isle] Red Snapper - Very Tasty!)
[//]: # ([NPC] Magistrix Erona)
[//]: # ([Spell][Mage] Fireball)
[//]: # ([Npc][Drop] Ghostclaw Lynx)
[//]: # ([Web] Armory doesnt work)
[//]: # (To find server revision type `.server info` command in the game chat.)

**Description**: 
The quest "Banish the Demons" requires that you go to Forge Camp Wrath or Forge Camp Terror, use an Apex shard to open a portal, and then kill demons near that portal 15 times to complete the quest.
**Current behaviour**:
You can open a portal, but killing demons near it does not update the quest objectives.
**Expected behaviour**: 
You should be able to kill demons near the opened portal to update quest objectives.
**Server Revision**: 
Server Revision: 3060

**Comment by Evolvee** [comment]
watch changelog
