### ISSUE TITLE
[Blade's Edge Mountains][Ogri'la] Shartuul's Transporter event might be unscripted

### ISSUE THREAD

**Issue by Kolmarwow** [Atlantiss/NetherwingBugtracker#6087]
**Description**: 
On the border of "Forge Camp: Wrath" in Blade's Edge Mountains is a demon transporter named "Shartuul's Transporter". 

There's an item called the "Crystalforged Darkrune" (gotten from the Ogri'la dailies Banish The Demons / Banish More Demons) which is used to mind control demons which starts a really cool solo-event where you hold off waves of spawning demons with your mind controlled demons. You start off this event by mind controling a "Felguard Degrader" with the Crystalforged Darkrune which patrols around the portal but it seems like he can't be found at the moment which makes it impossible to do this event. 

Since most of the Ogri'la quests in general have had some issues since 2.1 released, I'm assuming this whole event might be unscripted since this is somewhat of a "hidden event" type of thing that doesn't cross most peoples minds. 

If that's the case, Wowpedia has an extremely detailed page of the event which seems very useful https://wow.gamepedia.com/Shartuul%27s_Transporter_(event)
 
**Server Revision**: 
3068

**Comment by thiccasian** [comment]
Can confirm, felguard degrader is not spawned. Please fix soon :)

**Comment by earywen** [comment]
Can confirm, no felguard degrader around

**Comment by Shaz21rus** [comment]
Can confirm, no felguard degrader

**Comment by Evolvee** [comment]
duplicate
