### ISSUE TITLE
[SSC] [NPC] [Kael'thas] Phoenix Egg

### ISSUE THREAD

**Issue by Drayo** [Atlantiss/NetherwingBugtracker#6088]
[//]: # (Enclose links to things related to the bug using http://wowhead.com or any other TBC database.)
[//]: # (You can use screenshot ingame to visual the issue.)
[//]: # (Write your tickets according to the format:)
[//]: # ([Quest][Azuremyst Isle] Red Snapper - Very Tasty!)
[//]: # ([NPC] Magistrix Erona)
[//]: # ([Spell][Mage] Fireball)
[//]: # ([Npc][Drop] Ghostclaw Lynx)
[//]: # ([Web] Armory doesnt work)
[//]: # (To find server revision type `.server info` command in the game chat.)

**Current behaviour**: The Phoenix Egg moves (teleports) when it's hit by Stuns or Deathcoils.

**Expected behaviour**: The Egg should never move, it should either be immune to all effects that could cause movement, or simply ignore that part of the Spell e.g. take damage from the Deathcoil but not move.

**Server Revision**: 3065

**Comment by tcberk12** [comment]
https://www.twitch.tv/videos/449763283?t=10827s

confirmed.

**Comment by Manaci** [comment]
Fixed
