### ISSUE TITLE
[Core] [Master Looter] [Loot]

### ISSUE THREAD

**Issue by Evolvemademedothis** [Atlantiss/NetherwingBugtracker#6089]
[//]: # (Enclose links to things related to the bug using http://wowhead.com or any other TBC database.)
[//]: # (You can use screenshot ingame to visual the issue.)
[//]: # (Write your tickets according to the format:)
[//]: # ([Quest][Azuremyst Isle] Red Snapper - Very Tasty!)
[//]: # ([NPC] Magistrix Erona)
[//]: # ([Spell][Mage] Fireball)
[//]: # ([Npc][Drop] Ghostclaw Lynx)
[//]: # ([Web] Armory doesnt work)
[//]: # (To find server revision type `.server info` command in the game chat.)

**Description**: 
Magtheridon's Head item ID 32385(Alliance Version) 32386(Horde Version) can currently be looted by anyone even with Master Loot present
**Current behaviour**:
Anyone can loot the item even when loot rules prohibit it
**Expected behaviour**: 
Nobody should be able to loot the item when Masterloot is in place except the Masterlooter
**Server Revision**: 
3068

**Comment by Tereneckla** [comment]
Fixed
