### ISSUE TITLE
[TK] [NPC] [Kael'thas] [Grand Astromancer Capernian] [Combat Status]

### ISSUE THREAD

**Issue by Evolvemademedothis** [Atlantiss/NetherwingBugtracker#6090]
[//]: # (Enclose links to things related to the bug using http://wowhead.com or any other TBC database.)
[//]: # (You can use screenshot ingame to visual the issue.)
[//]: # (Write your tickets according to the format:)
[//]: # ([Quest][Azuremyst Isle] Red Snapper - Very Tasty!)
[//]: # ([NPC] Magistrix Erona)
[//]: # ([Spell][Mage] Fireball)
[//]: # ([Npc][Drop] Ghostclaw Lynx)
[//]: # ([Web] Armory doesnt work)
[//]: # (To find server revision type `.server info` command in the game chat.)

**Description**: 
Grand Astromancer Capernian should be engaged in combat with every player in the zone when activated
**Current behaviour**:
Last night during Phase 3 Grand Astromancer Capernian reset to her pre fight position and healed to full HP after her target(warlock tank) was killed by Thaladred The Darkener
**Expected behaviour**: 
Advisors shouldnt reset to their original positions if their current target dies but should instead go for the next person on their threatlist, if none is present then they should attack the closest player to them.
**Server Revision**: 
3068

**Comment by Godmatik** [comment]
Still occurs.

The mechanic where a boss is put into combat with everyone inside the instance is not present on each of the four advisers.

**Comment by Godmatik** [comment]
Duplicate from more recent issue - closing
