### ISSUE TITLE
[Buff] "Introspection" from the Apexis Relics/Monuments isn't classified as a debuff

### ISSUE THREAD

**Issue by Kolmarwow** [Atlantiss/NetherwingBugtracker#6092]
**Description**: 
In Blade's Edge Mountains there are these Simon-Says mini-games. When you play them and click on the buttons, you get a 10 second debuff called "Introspection" which heavily lowers your movement speed. I assume this is so that you can't do the big Simon Says mini-game on your own since the buttons are spread far apart.

The problem is that Introspection is classified as a regular buff at the moment, so you can just simply click it off every time you get it. 

**Server Revision**: 
3068

**Comment by Wolffenstein** [comment]
Fixed in rev 3079.
