### ISSUE TITLE
(Quest) Stealing back Mushrooms (Zangermarsh, Alliance)

### ISSUE THREAD

**Issue by Kaidalen** [Atlantiss/NetherwingBugtracker#6093]
[//]: # (Enclose links to things related to the bug using http://wowhead.com or any other TBC database.)
[//]: # (You can use screenshot ingame to visual the issue.)
[//]: # (Write your tickets according to the format:)
[//]: # ([Quest][Azuremyst Isle] Red Snapper - Very Tasty!)
[//]: # ([NPC] Magistrix Erona)
[//]: # ([Spell][Mage] Fireball)
[//]: # ([Npc][Drop] Ghostclaw Lynx)
[//]: # ([Web] Armory doesnt work)
[//]: # (To find server revision type `.server info` command in the game chat.)

**Description**:  The quest suggests there will be boxes to collect around the ogre camp but there isn't any. Even after waiting in case for respawns there are no "Boxes of Mushrooms" Only way to get the item is to kill the ogre and the drop rate is low.

**Current behaviour**: No "Boxes of Mushrooms" around ogre camp. Only way to complete quest is to kill Ogres and drop rate is low

**Expected behaviour**:  There should be "Boxes" to collect around the ogre camp. And Quest item drop rate should be slightly increased on ogres. 

**Server Revision**:  3068

**Comment by Easyfraggy** [comment]
I'm pretty sure I looted these when I was doing the quest. Invalid?

**Comment by Evolvee** [comment]
maybe its the core gob bug where gobs dont respawn idk

**Comment by Evolvee** [comment]
probably
