### ISSUE TITLE
Line Of Sight (LoS) In vanilla and outlands you can shoot through walls 

### ISSUE THREAD

**Issue by Kaidalen** [Atlantiss/NetherwingBugtracker#6094]
[//]: # (Enclose links to things related to the bug using http://wowhead.com or any other TBC database.)
[//]: # (You can use screenshot ingame to visual the issue.)
[//]: # (Write your tickets according to the format:)
[//]: # ([Quest][Azuremyst Isle] Red Snapper - Very Tasty!)
[//]: # ([NPC] Magistrix Erona)
[//]: # ([Spell][Mage] Fireball)
[//]: # ([Npc][Drop] Ghostclaw Lynx)
[//]: # ([Web] Armory doesnt work)
[//]: # (To find server revision type `.server info` command in the game chat.)

**Description**: Line of Sight system is a 50/50 chance to work. Sometimes it does, sometimes it doesn't. The times I have experienced I can target an enemy through a wall and shoot through the wall. 

**Current behaviour**: LoS not working properly can shoot through walls and mobs don't path to you if you are behind a wall. Sometimes. 

**Expected behaviour**:  You 100% should be able to LoS targets and NOT shoot enemies though walls. 

**Server Revision**:  3068

**Comment by Evolvee** [comment]
what wall

**Comment by Easyfraggy** [comment]
Line of sight is working correctly. Many objects don't cause LoS in WoW. This is the same on current retail.
