### ISSUE TITLE
(Hunter Quest chain) Hunter quest chain broken

### ISSUE THREAD

**Issue by Kaidalen** [Atlantiss/NetherwingBugtracker#6095]
[//]: # (Enclose links to things related to the bug using http://wowhead.com or any other TBC database.)
[//]: # (You can use screenshot ingame to visual the issue.)
[//]: # (Write your tickets according to the format:)
[//]: # ([Quest][Azuremyst Isle] Red Snapper - Very Tasty!)
[//]: # ([NPC] Magistrix Erona)
[//]: # ([Spell][Mage] Fireball)
[//]: # ([Npc][Drop] Ghostclaw Lynx)
[//]: # ([Web] Armory doesnt work)
[//]: # (To find server revision type `.server info` command in the game chat.)

**Description**: I rolled a dwarf Hunter, but never received any Hunter quests. When I turned level 62 I race changed to Night Elf and went to the Hunter trainer I had the level 10 quest chain waiting for me. So I had to go to the Night Elf Starting point to do the quest.

**Current behaviour**: Dwarf Hunter quest chain - or hunter quest chain broken I never got any quests while I was a dwarf hunter - soon as I became a Night Elf I got the level 10 quest to tame animals in the Night Elf Starting area.

**Expected behaviour**:  Not be broken like 90% of this server?

**Server Revision**:  3086
![Broken quest](https://user-images.githubusercontent.com/51963601/60972207-23430880-a369-11e9-93af-8ce7d31cbd78.PNG)

**Comment by Kaidalen** [comment]
And yes, I re tested it as a Dwarf and THERE IS NO HUNTER QUEST PAST LEVEL 10

**Comment by Easyfraggy** [comment]
Are you sure you attempted to get the hunter quests from Ironforge when you were a dwarf?

**Comment by SwiftieTBC** [comment]
i mean this is an obvious lie right? As on your bars you have beast training which is the end rewards of the taming the beast quest line. As your currently completing the night elf version the only understandable way for you to have that spell would be to have completed the dwarf version of taming the beast.

**Comment by Godmatik** [comment]
You wouldn't have been able to tame a pet if you didn't get ANY hunter quests as a Dwarf.

**Comment by Evolvee** [comment]
???
