### ISSUE TITLE
Pick pocket incorrect loot amount

### ISSUE THREAD

**Issue by Technowaffle** [Atlantiss/NetherwingBugtracker#6096]
Pick pocket for rogues does not give appropriate amount of copper/silver. At early levels 90% of the time it gives minimum amount and after early levels it gives 1-3 copper all the time, which breaks the ability completely. If working properly, should be a good source of cash during leveling times.

**Comment by Evolvee** [comment]
this report has 0 information inside...

when you find some evidence/research/info, please reopen
