### ISSUE TITLE
Enhacement talent Toughness

### ISSUE THREAD

**Issue by Furyfreak** [Atlantiss/NetherwingBugtracker#6098]
Hi, first i apologize for my English

**Description**: 

I have an issue with talent Toughness in ehnacement tree, in 5/5 points it may reduce all slow efects on you by 50%
http://calculators.iradei.eu/talents/shaman

**Current behaviour**:

Frost nova freezes me for all duration 8s  https://tbc-twinhead.twinstar.cz/?spell=27088
**Expected behaviour**: 

It may be half that duration so 4s, and so it may be with all slow efects 

**Server Revision**:

**Comment by whissper** [comment]
Frost Nova -- (6) Apply Aura #26: Root
Toughness (Enhancement talent) -- (6) Apply Aura #232: Mechanic Duration Mod (11)
Value: -50 

I.e. talent reduces "movement slowing effects" but not "root effects"

**Comment by Furyfreak** [comment]
Didnt know that thx, and that frost nova when im rooted , may any dmg interupt that efect...im stuck whole 8s and basicly dead
Any mage if i see them im done...rly that talent work well ?

**Comment by whissper** [comment]
This root effect (frost nova) has a **chance** to be interrupted on damage. 
Same for [entangling roots]
