### ISSUE TITLE
[Quest] WANTED: Murkdeep!

### ISSUE THREAD

**Issue by muhnow** [Atlantiss/NetherwingBugtracker#6099]
[//]: # (Enclose links to things related to the bug using http://wowhead.com or any other TBC database.)
[//]: # (You can use screenshot ingame to visual the issue.)
[//]: # (Write your tickets according to the format:)
[//]: # ([Quest][Azuremyst Isle] Red Snapper - Very Tasty!)
[//]: # ([NPC] Magistrix Erona)
[//]: # ([Spell][Mage] Fireball)
[//]: # ([Npc][Drop] Ghostclaw Lynx)
[//]: # ([Web] Armory doesnt work)
[//]: # (To find server revision type `.server info` command in the game chat.)

**Useful links**
https://classic.wowhead.com/npc=10323/murkdeep

**Description**: 
Murkdeep never spawns. Per the provided classic Wowhead link, they mention how you need to clear the camp he spawns at in order to get him to spawn. I have cleared the camp 3 times back to back and he has still not spawned.

**Current behaviour**:
Clearing the murloc camp that Murkdeep spawns it does not prompt his spawn.

**Expected behaviour**: 
Clearing the murloc camp once should prompt Murkdeep to spawn in the center of the camp.

**Server Revision**:

**Comment by Evolvee** [comment]
works fine for me

you clear the camp, then you kill murlocs that spawn out of the sea and then in the next 2 waves there is murkdeep
