### ISSUE TITLE
[Spell] Serpent Sting

### ISSUE THREAD

**Issue by DoctorRaymos** [Atlantiss/NetherwingBugtracker#61]
> Player reported that they used Serpent Sting and then began kiting mob, when it was time to re-apply Serpent shot, the spell highlighted and player was in range, but the spell would not cast unless player stood completely still and pressed spell repeatedly. Player was jumping and strafing when he noticed that the spell was not going off.

User specifically reported this while kiting Elder Boars near Razor Hill.

Reported by Discord user : locals#7353

Needs additional testing for confirmation.

**Comment by Easyfraggy** [comment]
Seems to work fine for me:

https://gfycat.com/DisguisedContentJanenschia

**Comment by DoctorRaymos** [comment]
> Seems to work fine for me:
> 
> https://gfycat.com/DisguisedContentJanenschia

User specifically reported this as his second use of the ability, and did not seem to have any problems with first use.

**Comment by Easyfraggy** [comment]
https://gfycat.com/AppropriateScarceIndianspinyloach

**Comment by maronics** [comment]
Yup, I'll support that theory. Right after an Auto Shot instants work normally, towards the wind up the situation the last gif (mine) Easy posted occurs until you fire another Auto Shot.

**Comment by Easyfraggy** [comment]
This is part of a larger issue: https://github.com/Atlantiss/NetherwingBugtracker/issues/135

**Comment by Easyfraggy** [comment]
Fixed in rev [2050]
