### ISSUE TITLE
An Unholy Alliance

### ISSUE THREAD

**Issue by Apokalypsewow** [Atlantiss/NetherwingBugtracker#6100]
https://classic.wowhead.com/quest=6521/an-unholy-alliance

**Description**: The head of the guy wont drop. 

https://classic.wowhead.com/item=17009/ambassador-malcins-head#objective-of

**Current behaviour**: not dropping the head

**Expected behaviour**: drop the head

**Server Revision**:

**Comment by Evolvee** [comment]
![image](https://user-images.githubusercontent.com/1942409/61214650-c351b680-a708-11e9-80c6-ca71727380e4.png)
works fine for me

make sure to disable all addons, clear cache and leave raid before trying again
