### ISSUE TITLE
[Chat Quest Link] Quest link is all numbers and letters

### ISSUE THREAD

**Issue by Kaidalen** [Atlantiss/NetherwingBugtracker#6101]
[//]: # (Enclose links to things related to the bug using http://wowhead.com or any other TBC database.)
[//]: # (You can use screenshot ingame to visual the issue.)
[//]: # (Write your tickets according to the format:)
[//]: # ([Quest][Azuremyst Isle] Red Snapper - Very Tasty!)
[//]: # ([NPC] Magistrix Erona)
[//]: # ([Spell][Mage] Fireball)
[//]: # ([Npc][Drop] Ghostclaw Lynx)
[//]: # ([Web] Armory doesnt work)
[//]: # (To find server revision type `.server info` command in the game chat.)

**Description**:  **Sometimes** Let me highlight that for some. When you link a quest in chat, it will come up with code, full of numbers and letters. 

**Current behaviour**: **Sometimes** When linking a quest to chat, whether it be Guild chat, Trade chat, General chat, it **Sometimes** just shows numbers and letters. **As seen by picture below**

**Expected behaviour**: Quest Linking to chat, Guild Chat, wherever. Should link properly.

**Server Revision**:  3068
![broken chat](https://user-images.githubusercontent.com/51963601/61172624-2be64980-a5ca-11e9-88f4-de6559d6cfb5.PNG)

**Comment by Evolvee** [comment]
Thats because you cant copy paste it. You need to link the quest every single time.

**Comment by Kaidalen** [comment]
> 
> 
> Thats because you cant copy paste it. You need to link the quest every single time straight from your quest log.

...can people read? Even when you link it, I never said anything about copy and pasting it...

**Comment by Realnairoby** [comment]
Its a bug caused by a chat addon and not by the server. Get your addons sorted and you wont „clink“ anymore

**Comment by Evolvee** [comment]
disable all addons and try again then

**Comment by Kaidalen** [comment]
I don't have any chat addons.

**Comment by Realnairoby** [comment]
Its caused by the one sending the message. So Finalzet is using the addon „Chatter“ and hasnt disabled the linking option. Means it will be shown as clink for everybody not using this addon. 

Its not a bug.
