### ISSUE TITLE
[Hunter Pet] Holding Aggro issue 

### ISSUE THREAD

**Issue by Kaidalen** [Atlantiss/NetherwingBugtracker#6102]
[//]: # (Enclose links to things related to the bug using http://wowhead.com or any other TBC database.)
[//]: # (You can use screenshot ingame to visual the issue.)
[//]: # (Write your tickets according to the format:)
[//]: # ([Quest][Azuremyst Isle] Red Snapper - Very Tasty!)
[//]: # ([NPC] Magistrix Erona)
[//]: # ([Spell][Mage] Fireball)
[//]: # ([Npc][Drop] Ghostclaw Lynx)
[//]: # ([Web] Armory doesnt work)
[//]: # (To find server revision type `.server info` command in the game chat.)

**Description**: Don't know if this is an issue or not, but my pet (Ravenger) has level 7 growl. It is finding it difficult to keep aggro. It's like my pet doesn't have growl at all. This just started probably two (2) days ago.

**Current behaviour**: Pet is not holding aggro properly. 

**Expected behaviour**:  Pet should hold aggro no matter what. (tested with Omen and soon as I drop aggro and attack the mob again, I get aggro straight away)

**Server Revision**:  3068

**Comment by The14me** [comment]
Rev 3460. It holds the aggro just fine.
Can be closed.
