### ISSUE TITLE
[Core Mechanic] [DR] [GAME BREAKING] 

### ISSUE THREAD

**Issue by LostInLyrics** [Atlantiss/NetherwingBugtracker#6106]
**Description**: 
It has been talked about quite a lot in the pvp channel, so I was surprised there is no bug report about it.
There is a strange bug with Kidney DR if you just got Kidney'd yourself.
The main observation I could make is that it **ONLY** happens during the first interaction after both characters had a instance change or relogged. This explains why it always happens in the opener during arena matches.

**Current behaviour**:
After an enemy uses Kidney Shot on you, the resulting DR will somehow carry over and make your own Kidney Shot on that person DR'ed

Video Proof (both chars just logged in right before that): 
https://streamable.com/efroc

**Expected behaviour**: 
DR's on yourself shouldn't influence DR's on other targets in any way.

**Server Revision**: 
3068

**Comment by Wolffenstein** [comment]
Fixed in rev 3078.
