### ISSUE TITLE
Macros with /use and /cast do not work properly

### ISSUE THREAD

**Issue by ircfelix** [Atlantiss/NetherwingBugtracker#6109]
**Description**: 
Some macros work only on first time use or when **all** macro conditions fit (=all cooldowns are available).

**Current behaviour**:
When I am using a 
`/use Super Mana Potion
/cast Arcane Blast`
macro, it stops working after the first use (each combat). As soon as my mana potion is off-cd and I press the macro button, it only casts arcane blast without properly using the mana potion before casting AB.

My other Macro which is 
`/use 14
/use mana emerald
/cast icy veins
/cast berserking
/cast Arcane Power
/cast Arcane Blast`
(14 is the lower trinket slot) only works when Icy veins, Berserking, Arcane power are off-cd. As long as the named spells are on CD, the macro won't /use 14, /use mana emerald /cast arcane blast as it should.

**Expected behaviour**: 
The macros should execute each spell available and skip the ones which are on cooldown.

**Server Revision**: 
3068

**Comment by Tereneckla** [comment]
Both macros and other macros with a row of /use and /cast work just fine for me.
