### ISSUE TITLE
[Quest] Leaders of the Fang

### ISSUE THREAD

**Issue by Aurush** [Atlantiss/NetherwingBugtracker#6110]
[//]: # (Enclose links to things related to the bug using http://wowhead.com or any other TBC database.)
[//]: # (You can use screenshot ingame to visual the issue.)
[//]: # (Write your tickets according to the format:)
[//]: # ([Quest][Azuremyst Isle] Red Snapper - Very Tasty!)
[//]: # ([NPC] Magistrix Erona)
[//]: # ([Spell][Mage] Fireball)
[//]: # ([Npc][Drop] Ghostclaw Lynx)
[//]: # ([Web] Armory doesnt work)
[//]: # (To find server revision type `.server info` command in the game chat.)

**Description**: 
[NPC] Lord Pythas
After killing Lord Pythas the gem did not drop .
**Current behaviour**:
Gem didn't drop.
![pythas1](https://user-images.githubusercontent.com/51484915/61216847-09ae1200-a717-11e9-9024-03f5a9aadfee.png)
![pythas2](https://user-images.githubusercontent.com/51484915/61216860-10d52000-a717-11e9-9bc7-766a3be1172d.png)
**Expected behaviour**: 
The gem has 100% change to drop.
https://tbc-twinhead.twinstar.cz/?item=9740
**Server Revision**: 
3068

**Comment by Evolvee** [comment]
works fine for me

disable your addons, clear cache and try again

**Comment by Godmatik** [comment]
Also make sure you weren't in a raid group
