### ISSUE TITLE
[Forge Camp: Wrath] Cannot drink or eat even while out of combat

### ISSUE THREAD

**Issue by raethkcj** [Atlantiss/NetherwingBugtracker#6111]
[//]: # (Enclose links to things related to the bug using http://wowhead.com or any other TBC database.)
[//]: # (You can use screenshot ingame to visual the issue.)
[//]: # (Write your tickets according to the format:)
[//]: # ([Quest][Azuremyst Isle] Red Snapper - Very Tasty!)
[//]: # ([NPC] Magistrix Erona)
[//]: # ([Spell][Mage] Fireball)
[//]: # ([Npc][Drop] Ghostclaw Lynx)
[//]: # ([Web] Armory doesnt work)
[//]: # (To find server revision type `.server info` command in the game chat.)

**Description**: 
While in Forge Camp: Wrath in Ogri'la, attempting to eat or drink will make your character sit and will apply the "Eat" or "Drink" buff, but before the first tick of hp/mp restore goes off, your character inexplicably stands up and cancels eating or drinking.

Video here: https://youtu.be/czSWevdfWJ8

Some other players have reported the same issue:

> 5:12 PM] Ridens: i cant drink at Forge Camp Wrath, Blade Edge, is it bug or
[6:16 PM] Etherious: @ Ridens Most likely just stuck in combat, could be a bugged mob for example
[6:18 PM] yesmaster: had the same issue
[6:18 PM] yesmaster: couldnt drink ever
[7:00 PM] Ridens: water button is active, but the aura immediately subsides, most likely due to the fact that the hero allegedly moves for some reason

**Server Revision**:
3068

**Comment by Wolffenstein** [comment]
Fixed in rev 3078.
