### ISSUE TITLE
[Core] Character title(s)

### ISSUE THREAD

**Issue by yutsuku** [Atlantiss/NetherwingBugtracker#6112]
**Description**: Character title changes after you gain honor points

**Current behaviour**: Every time after logging into the game (no character title selected / None) after I earn any amount of honor (tested only in battlegrounds). My character title changes from None to my current PvP rank. It does it only once per game session.

**Expected behaviour**: I except my title to not change at all unless I gain a new rank or manually change it from the character panel dropdown.

**Server Revision**: 3068

**Comment by Evolvee** [comment]
duplicate
