### ISSUE TITLE
Having a mail icons that never disappears.

### ISSUE THREAD

**Issue by axorian0** [Atlantiss/NetherwingBugtracker#6113]
**Description**: 
The mail icon is always there, i buy, i sell, i reload, i turn off my addons and still, always there. I have talk with other players and some have the same problem. I will show below some images to prove my point.

**Current behaviour**:
The icon never disappears.

**Expected behaviour**: 
Should disappear when the mailbox is empty.

**Server Revision**: 
Netherwing 2.4.3

### **_Thank you for your time._**

**Attachments**:
1- Mail Icon
![WoWScrnShot_071519_220310](https://user-images.githubusercontent.com/17536399/61253045-35e58500-a74f-11e9-98e9-9f7317826530.jpg)
2- With Addon (Postal)
![WoWScrnShot_071519_220316](https://user-images.githubusercontent.com/17536399/61253095-60cfd900-a74f-11e9-98d6-4a3516570f45.jpg)
3- With no Addon
![WoWScrnShot_071519_220542](https://user-images.githubusercontent.com/17536399/61253101-67f6e700-a74f-11e9-8bb4-0ae2ff79dab3.jpg)

**Comment by taurenrogue** [comment]
exit game -> clear cache -> log in -> mail me some gold to test the fixed mail :)

**Comment by danbopes** [comment]
This should now be fixed in the last update. If your mailbox is working normally, you can close this ticket.

**Comment by Wolffenstein** [comment]
Should be fixed.

**Comment by morielar** [comment]
Having the same problem, Tried the above solution and did not work. Tried cancelling an auction and icon briefly went away when i opened mail, then came back. otherwise mail is interacting normally
