### ISSUE TITLE
[DUNGEON] [ZUL'GURUB] [OBJECT] Battered Tackle Box to summon [NPC] Gahz'ranka 

### ISSUE THREAD

**Issue by ZoidC** [Atlantiss/NetherwingBugtracker#6114]
[//]: # (Enclose links to things related to the bug using http://wowhead.com or any other TBC database.)
[//]: # (You can use screenshot ingame to visual the issue.)
[//]: # (Write your tickets according to the format:)
[//]: # ([Quest][Azuremyst Isle] Red Snapper - Very Tasty!)
[//]: # ([NPC] Magistrix Erona)
[//]: # ([Spell][Mage] Fireball)
[//]: # ([Npc][Drop] Ghostclaw Lynx)
[//]: # ([Web] Armory doesnt work)
[//]: # (To find server revision type `.server info` command in the game chat.)

**Description**: 
• Final purpose : 
Summon [NPC] Gahz'ranka ( **https://www.wowhead.com/npc=15114/** )
• Progress issue : 
Click on [OBJECT] Battered Tackle Box ( **https://classic.wowhead.com/object=180366/** )
to get [QUEST] Nat's Measuring Tape ( **https://www.wowhead.com/quest=8227/** )
to buy [ITEM] Mudskunk Lure ( **https://www.wowhead.com/item=19974/** )

**Current behaviour**:
Battered Tackle Box is unclickable.

**Expected behaviour**: 
Battered Tackle Box should be clickable to get the quest.

**Server Revision**: 
[3072]

**Comment by ZoidC** [comment]
@Evolvee 
( Daystar asked me to tag you :) )

**Comment by Wolffenstein** [comment]
Fixed
