### ISSUE TITLE
[SSC][Fathom Lord Karathress] Slice and Dice cannot be cast on Spitfire Totem

### ISSUE THREAD

**Issue by TimCannady** [Atlantiss/NetherwingBugtracker#6115]
**Description**: 
When attempting to cast Slice and Dice on a Spitfire Totem, nothing happens. Other finishers like Eviscerate work correctly.

**Current behaviour**:
* Rogue uses an ability to generate Combo Points on a Spitfire Totem
* Rogue uses Slice and Dice as a finisher
* _nothing happens_

**Expected behaviour**: 
* Rogue uses an ability to generate Combo Points on a Spitfire Totem
* Rogue uses Slice and Dice as a finisher
* _Combo Points on the Spitfire Totem are consumed. Rogue gains Slice and Dice._ 

**Server Revision**: 
* 3072 (the number from the most recent post in the #changelog channel on Discord from today)

**Resources**:
* [In this Twitch VOD](https://clips.twitch.tv/SpinelessAbstruseRadishPJSugar) my rogue is unable to cast Slice and Dice against the Spitfire Totem. The totem is engaged without having SnD up. A Combo Point is generated. Attempts are made to cast SnD using a keybind. When that doesn't work, I can be seen trying to click the spell with the cursor (to no avail). The totem dies. The rogue switches to Fathom Lord Karathress, generates a Combo Point and can immediately cast SnD using the keybind.
* [In this Twitch VOD](https://clips.twitch.tv/AverageFaithfulDiamondTheThing) my rogue builds three Combo Points on a Spitfire Totem and uses Eviscerate as a Finishing Move.

**Comment by Wolffenstein** [comment]
Fixed in rev 3104.
