### ISSUE TITLE
[Quest] Zul'Gurub Quest Bugs

### ISSUE THREAD

**Issue by Manaci** [Atlantiss/NetherwingBugtracker#6116]
**Token Quests**
[Vinchaxa](https://db.excalibur.ws/?npc=15070) should offer the quest  [A Bijou for Zanza](https://db.excalibur.ws/?quest=8240) and the 3 repeatable quests called [Gurubashi, Vilebranch, and Witherbark Coins](https://db.excalibur.ws/?quest=8238), [Sandfury, Skullsplitter, and Bloodscalp Coins](https://db.excalibur.ws/?quest=8239) and [Zulian, Razzashi, and Hakkari Coins](https://db.excalibur.ws/?quest=8195) which he currently does not, halting token hand-ins. 

**Class Quests** 
The various class quests given by the Zandalar Trolls are currently not class-bound, meaning a hunter for example can pick up the warrior quests. So these all need to get class labeled. These 4 NPCs give them out [Al'tabim the All-Seeing](https://db.excalibur.ws/?npc=14903) (Mage, Warlock and Priest), [Maywiki of Zuldazar](https://db.excalibur.ws/?npc=14904) (Druid and Shaman) , [Jin'rokh the Breaker](https://db.excalibur.ws/?npc=14902) (Warrior and Paladin) and [Falthir the Sightless](https://db.excalibur.ws/?npc=14905) (Hunter and Rogue).
**Server Revision**: 
3072

**Comment by Manaci** [comment]
Got to Friendly now to check the necklace quests on earlier specified NPCs, and yes I could take every single one of them if I wanted to right now (some even have no description other than "NULL"). I just took my own class one that was fine. This "0 class assignment" probably also happens with [Zanza the Restless](https://db.excalibur.ws/?npc=15042) so those quests probably have to be class assigned as well here.

**Comment by bekonja** [comment]
can confirm.
coins cannot be turned in
can turn in every other class token
can take any other class necks quest

**Comment by Evolvee** [comment]
fixed in next rev
