### ISSUE TITLE
[Item] Heart of Hakkar

### ISSUE THREAD

**Issue by bekonja** [Atlantiss/NetherwingBugtracker#6120]
[//]: # (Enclose links to things related to the bug using http://wowhead.com or any other TBC database.)
[//]: # (You can use screenshot ingame to visual the issue.)
[//]: # (Write your tickets according to the format:)
[//]: # ([Quest][Azuremyst Isle] Red Snapper - Very Tasty!)
[//]: # ([NPC] Magistrix Erona)
[//]: # ([Spell][Mage] Fireball)
[//]: # ([Npc][Drop] Ghostclaw Lynx)
[//]: # ([Web] Armory doesnt work)
[//]: # (To find server revision type `.server info` command in the game chat.)

**Description**: https://db.excalibur.ws/?item=19802

**Current behaviour**: not drops

**Expected behaviour**: should drop

**Server Revision**: 
3072

**Comment by Evolvee** [comment]
oh its because the quest it starts was blocked

will be fixed in next rev
