### ISSUE TITLE
Chicken quest in  hinterlands broken

### ISSUE THREAD

**Issue by urzafyffe** [Atlantiss/NetherwingBugtracker#6121]
[//]: # https://tbc-twinhead.twinstar.cz/?quest=836
[//]: # [Quest][The Hinterlands] Rescue OOX-09/HL!
[//]: # [NPC] Homing Robot OOX-09/HL
**Description**:  Tried twice to do this quest.  Both times the chicken took off but after the first encounter with the owl beast, it just sat there and peaked the ground and didn't move.

**Current behaviour**: will stop after the first encounter and will not continue.

**Expected behaviour**: after the encounter, it should move to continue its quest.

**Server Revision**: not sure.

**Comment by SaSeggert** [comment]
Had this problem 5 Minutes ago.
One of the Owlbeasts is spawning under the rock on the left side. See picture enclosed.

The mob keeps the chicken infight. When the mob gets attacked it evades and let the chicken run further. Just fix the spawn position of the owl.

Server Revision: 3106

![WoWScrnShot_082219_203129](https://user-images.githubusercontent.com/37399495/63541212-ea788080-c51d-11e9-825c-32fd2aa1c13a.jpg)

**Comment by duzyizly** [comment]
still an issue as rev 3377 (ptr atm).
Second ambush is fine.

**Comment by Wolffenstein** [comment]
Fixed in rev 3387.
