### ISSUE TITLE
[ZG][Quest]Enchanted South Seas Kelp

### ISSUE THREAD

**Issue by bekonja** [Atlantiss/NetherwingBugtracker#6122]
[//]: # (Enclose links to things related to the bug using http://wowhead.com or any other TBC database.)
[//]: # (You can use screenshot ingame to visual the issue.)
[//]: # (Write your tickets according to the format:)
[//]: # ([Quest][Azuremyst Isle] Red Snapper - Very Tasty!)
[//]: # ([NPC] Magistrix Erona)
[//]: # ([Spell][Mage] Fireball)
[//]: # ([Npc][Drop] Ghostclaw Lynx)
[//]: # ([Web] Armory doesnt work)
[//]: # (To find server revision type `.server info` command in the game chat.)

**Description**: https://db.excalibur.ws/?quest=8111
got green neck from previous quest aswell as honored with Zandalar Tribe

**Current behaviour**: cannot obtain this quest, NPC simply doesnt have it. It might be some weird bug for my char only, but it might be for everyone, needs testing.

**Expected behaviour**: 

**Server Revision**: 
3072 (after quest-fix restart)

**Comment by Evolvee** [comment]
i cant even get the first quest

**Comment by Evolvee** [comment]
next rev

**Comment by Evolvee** [comment]
should be fixed?
