### ISSUE TITLE
Incorrect graveyard spawn in Forge Camp Wrath BEM

### ISSUE THREAD

**Issue by hederob** [Atlantiss/NetherwingBugtracker#6123]
**Description**: 
When dead in forge camp wrath Blades Edge Mountains, your ghost appears north of the mountains, providing no access to your body.
**Current behaviour**:
Your ghost arrives in the graveyard north of Forge Camp Wrath.
**Expected behaviour**: 
Your ghost should arrive at the Ogrila Graveyard.
**Server Revision**:

**Comment by Evolvee** [comment]
duplicate
