### ISSUE TITLE
[BT][Boss][Item] Naj'entus Spine

### ISSUE THREAD

**Issue by bekonja** [Atlantiss/NetherwingBugtracker#6125]
[//]: # (Enclose links to things related to the bug using http://wowhead.com or any other TBC database.)
[//]: # (You can use screenshot ingame to visual the issue.)
[//]: # (Write your tickets according to the format:)
[//]: # ([Quest][Azuremyst Isle] Red Snapper - Very Tasty!)
[//]: # ([NPC] Magistrix Erona)
[//]: # ([Spell][Mage] Fireball)
[//]: # ([Npc][Drop] Ghostclaw Lynx)
[//]: # ([Web] Armory doesnt work)
[//]: # (To find server revision type `.server info` command in the game chat.)

**Description**: 
https://db.excalibur.ws/?npc=22887#abilities
https://db.excalibur.ws/?item=32408
1st boss in BT, uses his Impaling Spine ability to immobilize one of the players and creates spine object ontop of them that could be "looted" to dispell it. Player who loots it recieves Naj'entus Spine item, that can be used to penetrate bosses' Tidal Shield ablilty.

**Current behaviour**: 1 big and 1 small issue with that mechanic rn.
Big issue: if you try loot spine object as a druid in cat form (or i guess any beast form) message appears of something like "you cannot do it while shapeshifted" which is fine, BUT it also destroys spine object and removes debuff, while not giving spine-item to feral who attempted to loot it. That results in soft-bricking boss and wiping it, happened to us in a raid.
Small issue: Tidal Shield ability counts as the part of bosses' model, it overlaps anything below it, making it hard to interact with spine object that lands in close proximity to the boss. Idk if its blizzlike or not but it feels so inconvenient that i doubt anyone would complain if you fix it.

**Expected behaviour**: TBH its such a niche case that i couldnt find any proofs of how feral-spine interaction should actually work. I guess any fix would do, either make it unlootable by ferals at all or make ferals be able to loot it like everyone else. Current behavior is bugged for sure.

**Server Revision**: 
3072

**Comment by Wolffenstein** [comment]
Fixed in rev 3078.

**Comment by Realnairoby** [comment]
> Big issue: if you try loot spine object as a druid in cat form (or i guess any beast form) message appears of something like "you cannot do it while shapeshifted" which is fine, BUT it also destroys spine object and removes debuff, while not giving spine-item to feral who attempted to loot it. That results in soft-bricking boss and wiping it, happened to us in a raid.

Still bugged in 3101

**Comment by WarriorTSW** [comment]
Hi, the Spine debuff/item is not interacting correctly with Cat Form. (again/still?)
Tonight i was stacked with cat as melee myself. I received Spine debuff twice. and both times the Feral was unable to receive the item and I was in a full duation debuff unable to perform any action.

**Comment by Godmatik** [comment]
It is a problem with melee in general as far as I know, it is difficult to loot the spine due to the boss's hitbox interfering
