### ISSUE TITLE
[NPC] Demon Hunter Initiate

### ISSUE THREAD

**Issue by zhuk90** [Atlantiss/NetherwingBugtracker#6126]
[//]: # (Enclose links to things related to the bug using http://wowhead.com or any other TBC database.)
[//]: # (You can use screenshot ingame to visual the issue.)
[//]: # (Write your tickets according to the format:)
[//]: # ([Quest][Azuremyst Isle] Red Snapper - Very Tasty!)
[//]: # ([NPC] Magistrix Erona)
[//]: # ([Spell][Mage] Fireball)
[//]: # ([Npc][Drop] Ghostclaw Lynx)
[//]: # ([Web] Armory doesnt work)
[//]: # (To find server revision type `.server info` command in the game chat.)

**Description**: 
some mobs are missing in the game
**Current behaviour**:
6 mobs are missing, near the NPC Varedis
**Expected behaviour**: 
There should be 11 mobs in total, next to the NPC Varedis, at the moment it's only 5
**Server Revision**: 
3072

**Comment by Evolvee** [comment]
they respawned just fine
they were dead probably

**Comment by zhuk90** [comment]
it is not, they are not reborn, return the ticket, please

**Comment by zhuk90** [comment]
> they respawned just fine
> they were dead probably

it is not, they are not reborn, return the ticket, please
