### ISSUE TITLE
[Quest] The Secret Compromised (BT attunement)

### ISSUE THREAD

**Issue by Firroth** [Atlantiss/NetherwingBugtracker#6127]
**Description**
Event occurs after turning in quest [The Secret Compromised](https://wowwiki.fandom.com/wiki/Quest:The_Secret_Compromised) to Akama

**Current behaviour**:
Event is mostly broken with it's cosmetic stuff. Akama facing the gate to Maiev when talking with Seer Olum and Illidan. Seer Olum doesn't have any speech text, but Akama has, so it looks like Akama is talking to himself the entire time. There is also missing a scene when Seer Olum dies and his ghost starts to float in the air.

**Expected behaviour**: 
Akama should be facing Seer Olum/Illidan during his speech patterns.
Seer Olum should have his text visible in the chat.
Entire death of Seer Olum scripted, and after his death appearance of Illidan .

**Server Revision**: 
3072

**Comment by Evolvee** [comment]
fixed in rev 3121
