### ISSUE TITLE
[Talent][Warlock] Improved Succubus

### ISSUE THREAD

**Issue by dukazzz** [Atlantiss/NetherwingBugtracker#6128]
[//]: # (Enclose links to things related to the bug using http://wowhead.com or any other TBC database.)
[//]: # (You can use screenshot ingame to visual the issue.)
[//]: # (Write your tickets according to the format:)
[//]: # ([Quest][Azuremyst Isle] Red Snapper - Very Tasty!)
[//]: # ([NPC] Magistrix Erona)
[//]: # ([Spell][Mage] Fireball)
[//]: # ([Npc][Drop] Ghostclaw Lynx)
[//]: # ([Web] Armory doesnt work)
[//]: # (To find server revision type `.server info` command in the game chat.)

**Description**: Improved Succubus talents doesn't appear to increase the damage of Succubus's spell Lash of Pain. At level 24 with 3/3 Improved Sccubus and 0 spell damage it deals 44 damage whereas tooltip says 42-43 (higher probably due to succubus being higher that lvl 20).

**Current behaviour**:Improved Succubus doesn't increase Lash of Pain damage

**Expected behaviour**: Lash of Pain damage should be be increased by 10/20/30%

**Server Revision**: 3072

**Comment by danbopes** [comment]
Talents don't effect tooltips, but the spells should deal the correct amount of damage. Are you sure it's dealing an incorrect amount?

**Comment by dukazzz** [comment]
It appears that in this case talent does affect the tooltip. Untalented rank 1 Lash of Pain deals 33 damage, so current values are correct. Sorry for the confusion.

For reference: https://tbc-twinhead.twinstar.cz/?spell=7814
