### ISSUE TITLE
[Ability] Mana Tap and crowd-control

### ISSUE THREAD

**Issue by dukazzz** [Atlantiss/NetherwingBugtracker#6129]
[//]: # (Enclose links to things related to the bug using http://wowhead.com or any other TBC database.)
[//]: # (You can use screenshot ingame to visual the issue.)
[//]: # (Write your tickets according to the format:)
[//]: # ([Quest][Azuremyst Isle] Red Snapper - Very Tasty!)
[//]: # ([NPC] Magistrix Erona)
[//]: # ([Spell][Mage] Fireball)
[//]: # ([Npc][Drop] Ghostclaw Lynx)
[//]: # ([Web] Armory doesnt work)
[//]: # (To find server revision type `.server info` command in the game chat.)

**Description**: Mana Tap should break crowd-control effects that break on damage such as Polymorph, Sap, etc. In TBC mana drains were counted as damage spells in regards to CC.

**Current behaviour**:Mana Tap doesn't break crowd-control effects.

**Expected behaviour**: Mana Tap should break "on damage" crowd-control effects (Polymorph, Sap, etc.)

**Server Revision**: 3072

**Comment by Wolffenstein** [comment]
Could you post some proof/source?

**Comment by Evolvee** [comment]
its true
idk mana tap

viper sting for sure

**Comment by Evolvee** [comment]
https://github.com/FeenixServerProject/Archangel_2.4.3_Bugtracker/issues/1989

we had this working btw  -.-

**Comment by teddys** [comment]
lul 2012

**Comment by Evolvee** [comment]
tfw worse than stock FeelsBadMan

**Comment by Wolffenstein** [comment]
Fixed in rev 3101.
