### ISSUE TITLE
[Stonetalon Mountians][NPC] Son of Cenarius

### ISSUE THREAD

**Issue by Knoox** [Atlantiss/NetherwingBugtracker#613]
**In some interaction that remains a mystery to me, he spawns multiple treant ally
![wowscrnshot_092418_225305](https://user-images.githubusercontent.com/18479169/46053144-f5763580-c141-11e8-8653-993b162b8019.jpg)
**:

**Comment by Kidcudi123** [comment]
This is because he spawns one everytime he's pulled
Expected Behaviour: Should not spawn multiple

**Comment by totaemoeggerli** [comment]
saw the same thing https://gfycat.com/InsistentBruisedDobermanpinscher
https://www.wowhead.com/npc=4057/son-of-cenarius
adds despawn if you run away after the son is dead

**Comment by Evolvee** [comment]
I cant reproduce the issue, but I made the pet to despawn on evade so "multiple spawns" cant happen.

rev xdd
