### ISSUE TITLE
[Talent][Mage] Arcane Concentration (clearcasting) + aoe

### ISSUE THREAD

**Issue by BezawitNW** [Atlantiss/NetherwingBugtracker#6130]
Arcane Concentration (Clearcasting) seems to currently be broken and having a chance to proc off of each enemy hit by an aoe spell. This is resulting in Mages having perma clearcast procs when they aoe on large packs. This is inflating Arcane dps due to 30% extra crit from Arcane Potency talent and dealing 50% more crit damage from Spell Power talent.

-Stolen from Drayo on an old bug report-

Source:
Faxxmonkey video episode 2, original upload to warcraftmovies june 2006.
https://www.youtube.com/watch?v=3O_pNDc73MM
13:35 - 14:13 ::::::: He attacks 93 mobs during the scourge event.
Stacks them up and uses Frost Nova, Arcane Explosions, Flamestrike and Cone of Cold.

Amount of Casts: 12
Amount of targets per Cast: 93
Clearcast Procs: 1

If it was on each hit he would proc Clearcasting on nearly every cast.
In the video his chance to proc clearcasting is clearly lower and about ~10% on each spell-cast.

**Comment by ircfelix** [comment]
This video is a vanilla source. I doubt it's different in TBC, but it's still vanilla. Please provide a tbc source (should not be hard to find)

**Comment by Evolvee** [comment]
@Wolffenstein how the fuck did you fuckup this

**Comment by Tenoutoften** [comment]
@ircfelix This mage does several casts on a 8 pack mob and you can't see the visual of him receiving clear cast at obscene rates. Maybe he doesn't have the talent, maybe he is having bad luck, who knows:]
https://youtu.be/aPigAzeC6Ig?t=36

**Comment by ircfelix** [comment]
Or maybe the earth is just flat.

**Comment by Evolvee** [comment]
u dont need to provide any evidence for this as this is well known and documented mechanic

**Comment by Easyfraggy** [comment]
Yeah I remember this being fixed before long time ago on closed beta.

**Comment by Wolffenstein** [comment]
Rev 3084.

**Comment by Nuy** [comment]
@Wolffenstein This seems to be broken again. Clearcasting procs all the time on Hyjal trash inflating its DPS during AoE.
