### ISSUE TITLE
[Hunter][Pet] Pet is breaking CCs

### ISSUE THREAD

**Issue by NatsumeLily** [Atlantiss/NetherwingBugtracker#6131]
[//]: # (Enclose links to things related to the bug using http://wowhead.com or any other TBC database.)
[//]: # (You can use screenshot ingame to visual the issue.)
[//]: # (Write your tickets according to the format:)
[//]: # ([Quest][Azuremyst Isle] Red Snapper - Very Tasty!)
[//]: # ([NPC] Magistrix Erona)
[//]: # ([Spell][Mage] Fireball)
[//]: # ([Npc][Drop] Ghostclaw Lynx)
[//]: # ([Web] Armory doesnt work)
[//]: # (To find server revision type `.server info` command in the game chat.)

**Description**: Pet is breaking CCs ( tested while being a hunter, 2 known so far are Scatter shot and freezing trap), while on defensive.

**Current behaviour**: Pet is breaking CCs while on defensive.

**Expected behaviour**: Pet shouldn't break CCs while on passive or defensive, even when told to.

 #456

**Server Revision**: 3072

**Comment by Kaidalen** [comment]
BUMP. Hunters are broke asf

**Comment by NatsumeLily** [comment]
Bump.

**Comment by Wolffenstein** [comment]
Fixed in rev 3174.
