### ISSUE TITLE
Auction House stops posting several items

### ISSUE THREAD

**Issue by ircfelix** [Atlantiss/NetherwingBugtracker#6132]
**Description**: 
Until like 6 days ago, you were able to post several stacks of an item very fast using an AH addon. If you, for instance, wanted to post 10 stacks of Destruction Potion, you could do that with addons like Auctioneer or Aux.
This behaviour has been confirmed by several people, so it must be a server-side issue.

**Current behaviour**:
Since like 6 days, your AH addon posts 1-3 items (if you set it to post 10 items) and then just stops.

**Expected behaviour**: 
Any addon should be able to post several items in a row without stopping.

**Server Revision**: 
3072

**Comment by Haipethdev** [comment]
Christ I was about to post this just as you did, good timing.

Yes, I am not sure if the update/request rate or a similar mechanic has been changed server side or not to combat scams?/bots?/abuse? but it has inadvertently killed the addon functionality listed above and this is not necessarily fixable without changing the addon itself.

**Comment by Lipmode** [comment]
It has to be server-side. I've deleted cache/wtf, redownloaded addon, tried different one and finally tried on a fresh client copy - nothing worked and it always only posts one stack.
Idk if it helps, but until I closed the AH window, I couldn't drag/split items after trying to post multiple stacks, as if the addon still tried to process the request. I'm really hoping it's not a deliberate move.

For now you can pretty much disable any posting addon.

**Comment by veekk** [comment]
can confirm that issue last few days - week

**Comment by ircfelix** [comment]
AH Addons work again for me.

**Comment by calekko** [comment]
Unless I'm missing something, Auctioneer certainly does not work for posting multiple items/stacks currently. Still all jacked up as of about a week ago. Auctionator, on the other hand, never had this feature stop working. Can you please reopen this?

**Comment by ircfelix** [comment]
Ok, the bug is back for me again. Like two/three days ago the addons worked just fine, not it's back to slow posting. Whatever you changed, in the past two/three days, revert it to test what causes the issue.

**Comment by ircfelix** [comment]
rev 3091

**Comment by calekko** [comment]
Awesome, thanks for reopening this mate!

**Comment by Haipethdev** [comment]
Can also confirm this was fixed in a revision 2/3 days ago and has now regressed again in case this helps identify the issue.

Currently not working on rev 3091.

**Comment by Kolgrim** [comment]
Still not working on Rev 3101

**Comment by Wolffenstein** [comment]
Fixed in rev 3104.
