### ISSUE TITLE
[Core] Windfury Totem extra weapon swings do not proc effects.

### ISSUE THREAD

**Issue by Easyfraggy** [Atlantiss/NetherwingBugtracker#6134]
**Description**: 
As it was the case for Windfury Weapon: https://github.com/Atlantiss/NetherwingBugtracker/issues/1951

The same problem persists for Windfury Totem extra weapon swings.

**Current behaviour**:
Extra procs from Windfury Totem do not proc effects like Flurry.

**Expected behaviour**: 
Extra procs from Windfury proc on crit/hit effects like Flurry.

**Server Revision**: 3070

**Comment by Wolffenstein** [comment]
Nope, it works correctly. It's just like every other autoattack.
