### ISSUE TITLE
[Quest][SMV] Frankly, It Makes No Sense...

### ISSUE THREAD

**Issue by mywebpage-rocks** [Atlantiss/NetherwingBugtracker#6135]
[//]: # (Enclose links to things related to the bug using http://wowhead.com or any other TBC database.)
[//]: # (You can use screenshot ingame to visual the issue.)
[//]: # (Write your tickets according to the format:)
[//]: # ([Quest][Azuremyst Isle] Red Snapper - Very Tasty!)
[//]: # ([NPC] Magistrix Erona)
[//]: # ([Spell][Mage] Fireball)
[//]: # ([Npc][Drop] Ghostclaw Lynx)
[//]: # ([Web] Armory doesnt work)
[//]: # (To find server revision type `.server info` command in the game chat.)

**Description**: Tried to complete the quest for 2 days. First uncompletable quest I encountered in Outland. You are supposed to use Arcano Control Unit which would let you control the scorpion which is used to tag mobs in the lava. Similar to Dip in the moonwell quest in Thousand Needles.

**Current behaviour**:
When you click on the console your toon gets the buff and start dancing, nothing else happens, you don't control the scorpion.

**Expected behaviour**: 
You should be able to control the scorpion, which should have tag the dinosaur ability and some other:
The arcanoscorps have other abilities besides tagging the Diemetradons. It's basically a mini-game you can play with 2 other friends, if you were really that bored.

a.) Arcano-Cloak, makes your scorp untargettable by other scorps
b.) Arcano-pince, does a weak melee attack to other scorps
c.) Arcano-dismantle, does a powerful attack to other scorps as well as stuns them for a short duration.

https://www.wowhead.com/quest=10672/frankly-it-makes-no-sense
https://youtu.be/ebySnNcXSnU

I've noticed that all arcano scorps are in lava. 3 of them should be behind the consoles. Maybe that's the reason of the quest not working.

**Server Revision**:

**Comment by Tereneckla** [comment]
actually works

**Comment by The14me** [comment]
Rev 3228 PTR
https://imgur.com/a/Ol8BaWe
Rev 3236 NW
https://imgur.com/a/uSUKawT

**Comment by Tereneckla** [comment]
Really are nowhere on live.

Anyways, on PTR they respawned.
They move back next to the control units, but only when in view distance of a player.
You get the closest one to you when you use a control unit, no matter how far away that is.
Life regen only when controlled.

[Arcano-cloak](https://www.wowhead.com/spell=37917/arcano-cloak) does the visual, but doesn't protect you from other Scorps in any way.
[Arcano-pince](https://www.wowhead.com/spell=37918/arcano-pince) deals damage to your Scorp and the targeted Scorp.
[Arcano-dismantle](https://www.wowhead.com/spell=37919/arcano-dismantle) also is on your Scorp and the targeted Scorp.

If any ability is used on another Scorp, your Scorp stays in combat until someone starts controlling it again. This disables the pathing back.
https://www.youtube.com/watch?v=Fj9Pf_prkow

**Comment by Tereneckla** [comment]
![image](https://user-images.githubusercontent.com/50233983/72264832-aba5ad00-361b-11ea-941f-1b6f9fc61e55.png)

**Comment by Tereneckla** [comment]
Should make Scorps despawn/reset when a certain distance away from the Control Units.

**Comment by Wolffenstein** [comment]
Fixed in rev 3332.
