### ISSUE TITLE
[Mage][Spell]Arcane Missiles damage per missile is wrong

### ISSUE THREAD

**Issue by ircfelix** [Atlantiss/NetherwingBugtracker#6136]
**Description**: 
Hi,

currently on NW Arcane Missiles (=AM) are doing too much damage. Dragonaut's shows in his stream, that AM is a better filler than Frostbolt, however old Elitistjerks considered Frostbolt to be the better filler. Driven by these two contradictory sources of information, I did some research and testing by myself.

How did I test?

1. First I tried to find out if the AM base damage in the tooltip is correct and yes, without any talents and spell damage gear, on the PTR AM do **264** damage non crit per tick (we are only going to talk about non crit missiles in the whole bug report).

2. Secondly, I tested the damage of AM without the 45% bonus spell damage talent:
With 642 arcane damage, no AM talent, missiles did 539 damage, but 264+(642 * 5/3,5)/5 suggests missiles should do 447,4 damage. So the issue is either the damage coefficient 5/3,5 (should be the coefficient) being wrong or the division by 5 (because 5 missiles) is wrong.
If we solve the equation 264+(642 * 5/3,5)/F = 539 for the mysterious five seconds F, we get:
1/F = (539 - 264)/(642 * 5/3,5)
F = 1/((539 - 264)/(642 * 5/3,5)) = 3,33
If we solve the equation 264+(642 * C)/5 = 539 for the mysterious spell damage coefficient C we get:
C= (529-264)*5/642 = 2,06    (remember, 5/3,5, which should be the coefficient, should be 1,429)

3. Thirdly, we can do the same by taking the 45% more spelldmg bonus talent into account, which makes our missiles hit for 596 damage.
If we solve the equation again for F we get:
264+(642 * (5/3,5 + 0,45))/F = 596
1/F = (596 - 264) / (642 * (5/3,5 + 0,45))
F = 1/((596 - 264) / (642 * (5/3,5 + 0,45))) = 3,63, which leaves the assumption that C is the culprit.
Solving for C:
264+(642 * (C + 0,45))/5 = 596
((596-264) * 5 -0,45 * 642)/642 = C = 2,14
So finally, in our equation non crit missile damage = 264 + spell damage * C/F it looks like C is more likely to be responsible for the wrong results in AM damage than F is. I suggest you look into the source code and check it out.
Afaik the spell damage coefficient of AM should be **base cast time/3,5**, which should be (as said above) 5/3,5 = 1,429,.

4. Retail Proof
The damage numbers in the following videos also suggest, that AM is currently bugged on NW. According to some logs and my testing, missiles on NW do like 1000dmg + non crit, in this video they only do ~747 non crit, which is a significant difference, that should not be explainable by missing 200 spell damage or so
In the end of the first video it also says "1173 spelldmg". With that number, the 747 non crit AMs seen in the video are close to what the equation would deliver: 264+1173*(5/3,5 + 0,45)/5 = 704 dmg. Assuming the mage wears 4-set T6, AM should get a 5% damage buff, which moves the damage in the equation (264+1173*(5/3,5 + 0,45)/5)*1,05 even closer to the observed number 747.
https://www.youtube.com/watch?v=5_ju3R_Sgxw
The second video, even though from 2007, also suggests that AM should not hit for 1000+ damage non crit:
https://www.youtube.com/watch?v=c2RtyFh5TnE

5. Additional thoughts
I am not really sure if 264 actually IS the base damage of AM. Several wow databases suggest it's 280 base damage (which would be wrong with the PVP video proof shown above), however, this is just an additional sidenote to the report.

**Current behaviour**:
Arcane Missiles are doing around 300-400 dps more than they should.

**Expected behaviour**: 
Arcane Missiles should do their intended damage, which should most likely be **non crit missile damage before partial resists = 264 + spell damage * (5/3,5 + number of points in the AM talent/3*0,45)/5**.

**Server Revision**: 
3072

**Comment by ircfelix** [comment]
https://wowwiki.fandom.com/wiki/Arcane_Empowerment?oldid=1631840

**Comment by ircfelix** [comment]
https://de.wowhead.com/spell=5143/arkane-geschosse#english-comments 
"well i have 1309 +arcane damage and my AM ticks for 780 "

**Comment by Wolffenstein** [comment]
Fixed in rev 3084.

**Comment by ircfelix** [comment]
What is the new coefficient now for testing if the fix worked?

**Comment by justheal** [comment]
> Retail Proof
> The damage numbers in the following videos also suggest, that AM is currently bugged on NW. 

What are u talking about? I see 893, 1k+, 900 etc damage in first video and according to mana (11k)  this mage have low gear (well, if take that he have 1173 spd - it's just full-t5, non-buffed). 747 non-crit? Why u talking only about lowest hit in whole video? (rly 747 lol, but it's pvp and players have a lot of damage reduction abilities/ways) So... he mostly hit for exatly the same dmg as it was! Not ur "calculations"
Btw video from private server it's just ridiculous and not argument (but still dont forget there 900+  average dmg, not 747)

> The second video, even though from 2007, also suggests that AM should not hit for 1000+ damage non crit:

omg.. This mage have 9.6k mana - he half-green and still make 700 dmg with missiles. idk is it official server or private too, but with this videos (both videos) u only show that AM **_must_** make higher dps than ur calculations

btw, there is a lot classic/tbc timeline posts (blizzard posts ofc) that said arcane it's highest dps mage spells, but also highest mana-needed. It was so, but now AM have lower dps with higher mana-per-damage than firebolt/frostbolt/or even scorch lol. That's not rudiculous anymore - that's stupid 


so... in the end 
### Where are took this formulas at all? I saw another ones, with damage results ~server previous revision. Why u think ur formules right (while posting videos that shows its wrong lol)?

**Comment by SwiftieTBC** [comment]
https://imgur.com/a/NGAhK7t
Just to clarify , the first video is taken from a private server ages ago and therefore should be discredited completely.
Secondly as shown in the Dr DMG addon the base dmg of rank 11 AM is 280 Evidence shown above.
Lastly retro porting videos is a very risky way of finding base values. You calculations also don't seem to take into account Arcane Instability which would add an additional 0.3.

**Comment by ircfelix** [comment]
Hi,

thank you for reply. I hope you can elaborate why those videos should be from a private server. Further, there's not only a pvp video, but also a video vs pve mobs where the damage of AM non crit is also in a low range.
Please also check the comment at wowhead:
https://de.wowhead.com/spell=5143/arkane-geschosse#english-comments
"well i have 1309 +arcane damage and my AM ticks for 780 "

With 1309 damage and the equation, non crit AM should tick for around (264 + 1309* (5/3,5 + 3/3*0,45)/5)*1,03 = 778.5 damage, which is pretty close to the suggested 780 in the comment. (actually I forgot the *1,03 modifier from Arcane Instability in my previous calculations).

If you had read the bug report, you would know that parts of the formula come from https://wowwiki.fandom.com/wiki/Arcane_Empowerment?oldid=1631840 and basic knowledge of how spell damage in wow is calculated.

For further questions or objections, feel free to give a well-written non-gibberish reply with solid facts of how AM should exactly work.
