### ISSUE TITLE
[CORE] [Feed pet] Feeding pets don't work

### ISSUE THREAD

**Issue by Kaidalen** [Atlantiss/NetherwingBugtracker#6137]
[//]: # (Enclose links to things related to the bug using http://wowhead.com or any other TBC database.)
[//]: # (You can use screenshot ingame to visual the issue.)
[//]: # (Write your tickets according to the format:)
[//]: # ([Quest][Azuremyst Isle] Red Snapper - Very Tasty!)
[//]: # ([NPC] Magistrix Erona)
[//]: # ([Spell][Mage] Fireball)
[//]: # ([Npc][Drop] Ghostclaw Lynx)
[//]: # ([Web] Armory doesnt work)
[//]: # (To find server revision type `.server info` command in the game chat.)

**Description**:  trying to feed my pet food and it won't eat it, like the item doesn't get consumed and there is no buff on the pet to make it happier. ADDONS ARE OFF

**Current behaviour**: Feed pet is bugged and wont allow me to feed pet

**Expected behaviour**:  I should be able to feed my pet

**Server Revision**:  3072

**Comment by taurenrogue** [comment]
have you:
1) made sure your pet can eat that food
2) tried clearing cache
?

**Comment by Evolvee** [comment]
lets hope he doesnt try to feed the pet with a wrong food 🤦‍♂

**Comment by Kaidalen** [comment]
I am not feeding my pet the wrong food, I am stupid, jesus christ. I am literally going to stop reporting bugs if idiots keep posting and not taking it seriously. IT WAS A CAT AND I WAS FEEDING IT MEAT. I have played hunter from beta vanilla all the way to BFA. So don't go around saying stupid stuff. Also Feign Death is broken and pet aggro is an issue (Not keeping aggro even if they the same level as you and enemies)

**Comment by Evolvemademedothis** [comment]
Have you tried feeding your pet by dragging food ontop of the pet frame? The ability isnt bugged and works fine on all 3 hunters I have access to, you have to be doing something wrong.

**Comment by Evolvee** [comment]
problem is, your report is worthless as you dont say anything worth for us to even take a look at it...

Record it, or tell us your nick, exact pet, exact food etc.

your report is literally "omg feed pet doesnt work, fix pls"

**Comment by NatsumeLily** [comment]
I've had this happen. But it's so easy to avoid and only happens in one certain instance. Just like pets aren't able to eat lower level food, they also can't eat higher level food. You won't get any message and it will look like it worked, but the food won't be consumed and the pet will not get the buff.

**Comment by Godmatik** [comment]
Either you feeding the pet the wrong food, or a food that is too high level for him to eat. 

Really simple ...

**Comment by Evolvee** [comment]
should u be able to feed pets high level food?

**Comment by Kaidalen** [comment]
My cat, Which now has disappeared from the Stables, was level 60, the FOOD I bought it said it LOVES this food. So it should've worked. It does the animation that its going to work but the pet doesn't get the buff of eating food. 

I no longer have this pet as it just went *POOF* from my stables. (Thanks for the amazing server Atlantiss) I am going to stop supporting this server with my money.

**Comment by Godmatik** [comment]
You're the only one that's having these issues mate, sounds likely a client or addon problem for why you can't feed the pet. 

Also, pets that are unhappy for too long will leave you, that is intended.

**Comment by Kaidalen** [comment]
The pet was in the STABLES pets dont vanish from stables. Even if unhappy, which, btw the cat was content. But whatever. I report bugs and I just get spat on. ok. I just threw like $300 to this server because I thought the admins were friendly and wanted their server to be good. I'll stop reporting "fake" bug reports then. Not like I did this for Blizzard on Retail for every expansion but nah you are right. A private server is going to function 100% perfect.
