### ISSUE TITLE
[PVP][Alterac Valley] Horde can pull Van without Marshall's

### ISSUE THREAD

**Issue by Kolgrim** [Atlantiss/NetherwingBugtracker#6139]
[//]: # (Enclose links to things related to the bug using http://wowhead.com or any other TBC database.)
[//]: # (You can use screenshot ingame to visual the issue.)
[//]: # (Write your tickets according to the format:)
[//]: # ([Quest][Azuremyst Isle] Red Snapper - Very Tasty!)
[//]: # ([NPC] Magistrix Erona)
[//]: # ([Spell][Mage] Fireball)
[//]: # ([Npc][Drop] Ghostclaw Lynx)
[//]: # ([Web] Armory doesnt work)
[//]: # (To find server revision type `.server info` command in the game chat.)

**Description**:  Currently horde can just pull Van without engaging the Marshalls at all. Making it nearly impossible for alliance to win

**Current behaviour**: They can do this ^

**Expected behaviour**: Should have to kill all Marshall's outside room before going in and engaging Van
Edit: Should have to take all towers to get rid of Marshall's obviously. But as the usual strategy goes on this server people usually just drag Marshall's out and kill them and then engage Vann. Same with Warchiefs and Drek. This seems to have been completely negated as now you can just zerg and kill because there is no Warmaster/Marshall buffs on the respective leader.

**Server Revision**: 3072

**Comment by kemotix** [comment]
AV weekend is coming next week. Is it gonna get fixed or Horde will crush Allies like month ago?
