### ISSUE TITLE
[Spell][Hunter] Freezing Trap

### ISSUE THREAD

**Issue by Thugli** [Atlantiss/NetherwingBugtracker#614]
[//]: # (Enclose links to things related to the bug using http://wowhead.com or any other TBC database.)
[//]: # (You can use screenshot ingame to visual the issue.)
[//]: # (Write your tickets according to the format:)
[//]: # ([Quest][Azuremyst Isle] Red Snapper - Very Tasty!)
[//]: # ([NPC] Magistrix Erona)
[//]: # ([Spell][Mage] Fireball)
[//]: # ([Npc][Drop] Ghostclaw Lynx)
[//]: # ([Web] Armory doesnt work)

**Description**: 
Occasionally freezing trap gets used but nothing happens. When this occurs, the trap's animation shows that it has been used, then it disappears entirely, but it doesn't get resisted or broken from damage, and the target is not immune. 

**Current behaviour**:
This is a screenshot of my combat log when this occurred on a bleakheart trickster @ 80,48 in Ashenvale. Though I have seen this happen on other mobs every now and then in the past, so it seems more related to the ability than the npc.
![image](https://user-images.githubusercontent.com/37326256/46052974-b8448000-c10e-11e8-84f6-2c1723864136.png)

**Expected behaviour**: 
Freezing trap should always properly CC the target, as long as:
A)Target isn't immune  
B)Target did not resist the trap

**Server Revision**: 
2060

**Comment by Manaci** [comment]
Fixed in rev 3214
