### ISSUE TITLE
[ZG][Quest] Zanza's Potent Potables

### ISSUE THREAD

**Issue by bekonja** [Atlantiss/NetherwingBugtracker#6140]
[//]: # (Enclose links to things related to the bug using http://wowhead.com or any other TBC database.)
[//]: # (You can use screenshot ingame to visual the issue.)
[//]: # (Write your tickets according to the format:)
[//]: # ([Quest][Azuremyst Isle] Red Snapper - Very Tasty!)
[//]: # ([NPC] Magistrix Erona)
[//]: # ([Spell][Mage] Fireball)
[//]: # ([Npc][Drop] Ghostclaw Lynx)
[//]: # ([Web] Armory doesnt work)
[//]: # (To find server revision type `.server info` command in the game chat.)

**Description**: https://db.excalibur.ws/?quest=8243
got rev rep

**Current behaviour**: not in game

**Expected behaviour**: should be in game

**Server Revision**: 3072

**Comment by Evolvee** [comment]
fixed in next rev
