### ISSUE TITLE
[Item] Battle Standard

### ISSUE THREAD

**Issue by yutsuku** [Atlantiss/NetherwingBugtracker#6141]
**Description**: [Horde Battle Standard] (18607) and [Frostwolf Battle Standard] (19046) cooldown timers (seen in Bag) sometimes don't reflect actual cooldown state.

**Current behaviour**: Using any of the above items in battlegrounds can lead to showing wrong cooldown time (Item is not ready yet - if used), especially if you use it shortly before battle ends and get into next battle very quickly.

**Expected behaviour**: Proper display if item is usable or not.

**Server Revision**: 3072

**Comment by Godmatik** [comment]
Unable to reproduce.

The cooldown timers work just fine for me during and in between multiple BGs.
