### ISSUE TITLE
LW recipe reputation gating

### ISSUE THREAD

**Issue by Sharpeyes1** [Atlantiss/NetherwingBugtracker#6143]
[//]: # (Enclose links to things related to the bug using http://wowhead.com or any other TBC database.)
[//]: # (You can use screenshot ingame to visual the issue.)
[//]: # (Write your tickets according to the format:)
[//]: # ([Quest][Azuremyst Isle] Red Snapper - Very Tasty!)
[//]: # ([NPC] Magistrix Erona)
[//]: # ([Spell][Mage] Fireball)
[//]: # ([Npc][Drop] Ghostclaw Lynx)
[//]: # ([Web] Armory doesnt work)
[//]: # (To find server revision type `.server info` command in the game chat.)

**Description**: 
Drums of battle and Drums of panic recipies
**Current behaviour**:
DoB require Exalted with shatar (the recipe rather), DoP require Honored with the keepers of time
**Expected behaviour**: 
as of post patch 2.3 BOTH DoB and DoP should only require honored with the corresponding faction. 
**Server Revision**:

**Comment by eri1997** [comment]
Items are based on patch we're on (patch 2.1 atm)
