### ISSUE TITLE
[Database] Make drop tables publicly available in some way

### ISSUE THREAD

**Issue by AlrightAllReady** [Atlantiss/NetherwingBugtracker#6147]
**Description**: 
As far as I know, the server's drop tables for items are not publicly available. This makes it very hard for players to report bugs on incorrect item drops, especially for items meant to have low drop chances. For example, I suspect there are patterns that should be on the drop tables of trash mobs in SSC, such as Boots of Natural Power, that aren't on the drop tables. However, I have no way of confirming whether this is simply bad luck my guild is experiencing or an actual bug. 

**Current behaviour**:
Players aren't given a way to view drop tables, which stymies the speed of discovering drop table bugs.

**Expected behaviour**: 
Please make the drop tables publicly available in some way. I understand that a database website would be a lot of work, but perhaps the drop tables could be shared as a raw file in this githib repo.

**Comment by Evolvee** [comment]
I can give you droprates of SSC on discord. There will not be a public DB viewer anytime soon.
