### ISSUE TITLE
[Core] Battlegrounds instance portals

### ISSUE THREAD

**Issue by yutsuku** [Atlantiss/NetherwingBugtracker#6148]
**Description**: Battleground portals are missing area trigger to en queue players into specific battlegrounds.

**Current behaviour**: None of the existing battleground portals allowed me (L70 Rogue, Horde) enter queue system. That includes portals for both Alliance and Horde players in: Alterac Mountains, Arathi Highlands, Ashenvale and Barrens.

**Expected behaviour**: As a horde player I expect to be able to queue for Warsong Gluch, Arathi Basin and Alterac Valley from horde specific locations:
- WSG: north Barrens
- AB: Hammerfall
- AV: Alterac Mountains, north from Tarren Mill

**Server Revision**: 3072

**Comment by Evolvee** [comment]
that was the TBC behavior
