### ISSUE TITLE
[TK][NPC] Kael'thas fight Bow unlootable

### ISSUE THREAD

**Issue by veekk** [Atlantiss/NetherwingBugtracker#6149]
**Description**: Bow after kill unlootable, seems like corpse spawning below textures

**Server Revision**: 3072

**Comment by Kolmarwow** [comment]
Believe this happens if any of the weapons are killed at an awkward angle on the stairs themselves, try to kill them on a flat surface to avoid this from happening

**Comment by Evolvemademedothis** [comment]
This can happen on a flat surface aswell, sometimes the bow just falls through the floor

**Comment by veekk** [comment]
happens to us 2 times in a row, first was on stairs under Kael back, and second at paladin tanking place  where's no any highground, on flat surface

**Comment by darknessangelo** [comment]
If you see him on the ground its there. Sometimes it happens that you can not loot the weapon because of wierd texture of the roof. try to close your camera and view from a different angle. Got the same issue on few servers before and this help.

**Comment by Godmatik** [comment]
Happens when the bow blinks same time it dies
https://github.com/Atlantiss/NetherwingBugtracker/issues/8567

**Comment by Godmatik** [comment]
Fixed, closing
