### ISSUE TITLE
[Battleground][NPC] Alterac Valley yell messages from Herald

### ISSUE THREAD

**Issue by yutsuku** [Atlantiss/NetherwingBugtracker#6150]
**Description**: Missing. ALL OF THEM. NPC id in question: 14848

**Current behaviour**: Every time something (graveyard, tower/bunker) gets captured, the Herald should announce that with proper YELL message.

**Expected behaviour**:

Herald yells the following messages for specific events:

- Tower/Bunker or Graveyard gets attacked: `(.+) is under attack!  If left unchecked, the (%w+) will (%w+) it.`
- Tower/Bunker or Graveyard gets defended: `(.+) was taken by the (%w+)!`
- Tower/Bunker gets destroyed: `(.+) was destroyed by the (%w+)!`

Patterns taken from Capping 2.4.011 and/or Deadly Boss Mod 3.22.

**Server Revision**: 3072

**Comment by Godmatik** [comment]
Closing - will consolidate all outstanding AV issues into one thread now.
