### ISSUE TITLE
[ITEM] Darkmoon Card: Crusade - Arcane missles don't get the benefit from the item except the 1st stack

### ISSUE THREAD

**Issue by Dekirayne** [Atlantiss/NetherwingBugtracker#6152]
Darkmoon card crusade gives 8 spelldamage per stack but arcane missles only get the benefit of the first stack of the darkmoon card.

It goes on until 10 stacks and the damags still stays exactly the same, and when the 4set tier 5 procs the damage goes up again which is less damage total than the 10 stacks of darkmoon card. Might be even possible that all spells benefit from the 1st stack but I have no way to test it.

It should benefit from all 80 spellpower the darkmoon card provides

![dadaaaaa](https://user-images.githubusercontent.com/12075744/61690517-cd3b7100-ad29-11e9-953d-b66905ddf679.png)

**Comment by Yolotan** [comment]
It does not work for walocks too.
I tested it with rain of fire only the first stack of the trinket (8sp) is being applied without trinket.
For me rain of fire ticks for 594 with the trinket it ticks for 596 from the first stack of the trinket up to the 10th stack, so in fact this is a 8sp trinket and not a 80sp trinket.
I tested it with dots and the same problem occurs.

**Comment by Dekirayne** [comment]
i have been raiding with a 8 spellpower trinket for 4 weeks now :S

**Comment by ZoidC** [comment]
Aswell here, I can confirm this topic..
Paying the high price for this card for .. nothing ? :D

**Comment by donatello4k** [comment]
The trinket works properly. Channeled spells snapshot the current spell power you have as you cast it, it should not update mid cast. The only thing that will affect your arcane missiles damage hit to hit would be if coefficients like Curse of the Elements are applied/removed while you're channeling.

**Comment by ZoidC** [comment]
Even if what you say is true.
Try any of your fix dmg spell (Blizzard as a mage for exemple) and use it at 0 stack then at 8 stack.
This trinket doesn't work :)

**Comment by donatello4k** [comment]
Yeah, you're absolutely right. At 10 stacks, +80 spell power is added on character stats but spells hit for the exact same amount with 0 stacks as 10 stacks.

**Comment by Wolffenstein** [comment]
Fixed in rev 3093.
