### ISSUE TITLE
[Item] Blade of Unquenched Thirst - proc dmg does not scale

### ISSUE THREAD

**Issue by Valtras** [Atlantiss/NetherwingBugtracker#6153]
**Description**: [Blade of Unquenched Thirst](https://tbc-twinhead.twinstar.cz/?item=31193)'s proc dmg does not scale with +spell dmg.

**Current behaviour**: The blade drains default amount of life.
![Blade](https://user-images.githubusercontent.com/22337597/61706284-f7039080-ad47-11e9-996d-110a82783113.png)

**Expected behaviour**: According to [wowhead comments](https://www.wowhead.com/item=31193/blade-of-unquenched-thirst#comments) the amount of life drained should scale with +spell dmg .
![Comments](https://user-images.githubusercontent.com/22337597/61706677-f15a7a80-ad48-11e9-843a-a233e4108c38.png)
For example, dmg scaling for [Axe of the Deep Woods](https://tbc-twinhead.twinstar.cz/?item=811) proc with similar effect works, eventhough it has probably different ratio than the blade.
![Axe](https://user-images.githubusercontent.com/22337597/61706286-f7039080-ad47-11e9-9423-acaaddb9bc63.png)

**Server Revision**: 3084

**Comment by Wolffenstein** [comment]
Fixed in rev 3198.
