### ISSUE TITLE
[NPC][Nightbane] Restless Skeleton

### ISSUE THREAD

**Issue by mywebpage-rocks** [Atlantiss/NetherwingBugtracker#6154]
[//]: # (Enclose links to things related to the bug using http://wowhead.com or any other TBC database.)
[//]: # (You can use screenshot ingame to visual the issue.)
[//]: # (Write your tickets according to the format:)
[//]: # ([Quest][Azuremyst Isle] Red Snapper - Very Tasty!)
[//]: # ([NPC] Magistrix Erona)
[//]: # ([Spell][Mage] Fireball)
[//]: # ([Npc][Drop] Ghostclaw Lynx)
[//]: # ([Web] Armory doesnt work)
[//]: # (To find server revision type `.server info` command in the game chat.)

**Description**: 
https://wowwiki.fandom.com/wiki/Nightbane_(boss)
https://wowwiki.fandom.com/wiki/Patch_2.0.10
https://wow.gamepedia.com/Nightbane_(tactics)

Bc icon Patch 2.0.10 (2007-03-06): Nightbane's Bone Shard Spray can no longer be interrupted by using an immunity effect.
Bc icon Patch 2.0.10 (2007-03-06): Restless Skeletons no longer have immolation.
Bc icon Patch 2.0.10 (2007-03-06): Nightbane's Restless Skeletons are now immune to non-holy magical damage. _Reverted in a hotfix several hours after the patch._

Restless Skeletons are not working as they are supposed to be on 2.1 Patch. They should no longer have their immolation aura. For few hours he was also immune to non-holy magic damage but this change was averted by Blizzard very quickly.

**Current behaviour**:

Restless Skeletons have their immolation aura as they are supposed to have on 2.0 patch.

**Expected behaviour**: 

Restless Skeletons should not have their immolation aura. 

**Server Revision**: 

3085.

**Comment by Wolffenstein** [comment]
Fixed in rev 3104.
