### ISSUE TITLE
[Item] Libram of the Eternal Rest

### ISSUE THREAD

**Issue by GitHubTheySaid** [Atlantiss/NetherwingBugtracker#6155]
Description:  Item level 112 Requires Level 68 ID 27917
Equip: Increases the damage of your Consecration spell by up to 47.

Current behaviour: Increases total damage count of consecration by 40.

Expected behaviour: It should increase total damage count of consecration by 47.

Server Revision: 3085
PS:its my first ticket, apologies for any mistakes :S

**Comment by Wolffenstein** [comment]
"by UP TO 47", not "by 47". It works properly and scales with coeff.
