### ISSUE TITLE
[Item][Shadow Labs Heroic][Loot]

### ISSUE THREAD

**Issue by delroy4** [Atlantiss/NetherwingBugtracker#6157]
[//]: # (Enclose links to things related to the bug using http://wowhead.com or any other TBC database.)
[//]: # (You can use screenshot ingame to visual the issue.)
[//]: # (Write your tickets according to the format:)
[//]: # ([Quest][Azuremyst Isle] Red Snapper - Very Tasty!)
[//]: # ([NPC] Magistrix Erona)
[//]: # ([Spell][Mage] Fireball)
[//]: # ([Npc][Drop] Ghostclaw Lynx)
[//]: # ([Web] Armory doesnt work)
[//]: # (To find server revision type `.server info` command in the game chat.)

**Description**: Incorrect Gem Drops in the Heroic... 1 of the 3 Gems that has a chance to drop off any boss is the incorrect gem.... 

**Current behaviour**: Dropping Glinting Fire Opal (5 Agility + 4 Hit), which is only supposed to drop in Black Morass Heroic according to every WoW Site I have found except  and Atlas Loot TBC

**Expected behaviour**: Should be dropping Etched Fire Opal (5 Strength + 4 Hit), which also is only Strength/Hit Gem in the game currently.
http://tbc.cavernoftime.com/npc=20657 (Loot Table For Murmur Heroic Mode)
https://wow.gamepedia.com/Shadow_Labyrinth_loot (Shows the Gem was Implemented Patch 2.0.3)
Also Shows it on Atlas Loot
**Server Revision**: 
AtlantisCoreTBC - Server Revision: 3085 [Branch: master, Hash: a2955196608c]

**Comment by Excinerus** [comment]
can confirm this :/

**Comment by Wolffenstein** [comment]
Fixed in rev 3104.
