### ISSUE TITLE
[Quest][Felwood] Verifying the Corruption

### ISSUE THREAD

**Issue by EysteinnO** [Atlantiss/NetherwingBugtracker#6158]
[//]: # (Enclose links to things related to the bug using http://wowhead.com or any other TBC database.)
[//]: # (You can use screenshot ingame to visual the issue.)
[//]: # (Write your tickets according to the format:)
[//]: # ([Quest][Azuremyst Isle] Red Snapper - Very Tasty!)
[//]: # ([NPC] Magistrix Erona)
[//]: # ([Spell][Mage] Fireball)
[//]: # ([Npc][Drop] Ghostclaw Lynx)
[//]: # ([Web] Armory doesnt work)
[//]: # (To find server revision type `.server info` command in the game chat.)

**Description**: 
A quest in Felwood that requires you to kill the two Entropic Beasts, two Entropic Horrors and Explore the Craters in the Shatter Scar Vale.
Wowhead link: https://www.wowhead.com/quest=5156/deprecated-verifying-the-corruption

**Current behaviour**:
Exploring part cannot be triggered by any means. I checked all the craters available, none worked.

**Expected behaviour**: 
Should trigger Explore the craters in Shatter Scar Vale.

**Server Revision**: 
Server version 2.4.3

**Comment by Evolvee** [comment]
fixed in next revision
