### ISSUE TITLE
([Spell][Shaman] Windfury)

### ISSUE THREAD

**Issue by natethegreat81** [Atlantiss/NetherwingBugtracker#6159]
**Description**: 
When using windfury on a mainhand weapon and offhand weapon the offhand weapon steals procs far more often than it should. By this I mean if you look at logs on this server of shamans using windfury on mainhand and offhand you notice that the number of hits is far greater on the offhand. This is incorrect and should have far more wf hits on mainhand. This is severely hurting putting WF on both weapons as the offhand does 50% less damage.

**Current behavior**:
Windfury, when applied to offhand and mainhand, is having the offhand proc wf far more often than it should. It should be about even if not more wf on mainhand as seen from data from elitist jerks testing in tbc retail. 

seen here: https://web.archive.org/web/20080811071236/http://elitistjerks.com/f47/t20765-shaman_enhancement/

Relevant text: 
"So I set off to the blasted lands tonight and though I don't have 1000 Stormstrikes worth of data, I do have 546, about 100mins worth.

Here were the results:

Xerel - WWS

Stormstrikes: 546
**Mainhand WF procs: 194
Offhand WF procs: 120**"

This clearly shows how mh wf procs would proc more often than offhand wf procs. 

Here is what is happening on this server. 
https://legacyplayers.com/Raids/Viewer/Default.aspx?id=8079&exp=1&upl=12078
(if it doesn't load the player, click on lillefod)
(image here for relevant information https://imgur.com/u7vpDy7  it can be accessed and looked more into depth on the legacyplayers link, however.)

**For gruul
MH wf proc 38
OH wf proc 58**

Here you can see the wf hits on both mh/oh have widely different hits. OH hits far more often than the mainhand and ends up doing about the same number of damage (even though OH hits for 50%  less). This should not be the case.

Since recount doesn't parse offhand wf and mh wf it is hard to show in game but on some ptr testing with rising tide/netherbane (both 2.6 speed axes) I got this data.

https://imgur.com/7fyt3b0
with both windfury on mh and oh. 

https://imgur.com/6O5Cmwb
This is with windfury mh and flametongue offhand. As you can see the windfury damage is much higher with mh only, this is because the OH is proccing far too often when both are imbued with WF. 

Here is information from another server with closer MH/OH windfury distribution and its closer to how it should be.

https://legacyplayers.com/Raids/Viewer/Default.aspx?id=4105&exp=1&upl=5814
(click on dankness or look at imgur link below to see relevant information) 
https://imgur.com/ftb5Mc9

**MH wf proc 244
OH wf proc 238**

(not saying this is correct but it is closer to correct than what netherwing is currently doing). 

**Expected behaviour**: 
Windfury should proc far more often on the mainhand and less often on the offhand. The overall % is about right but since it is proccing more often on the OH and not prioritizing the MH it is hurting the dps a lot (since oh does 50% less damage). 

**Server Revision**: 
3085 on live 3072 on ptr (shouldn't affect anything)

**Comment by zodis6** [comment]
Ye WF/WF combo feels like OH have prio on proc instead of MH

**Comment by Healweed** [comment]
> Expected behaviour:
Windfury should proc far more often on the mainhand and less often on the offhand. The overall % is about right but since it is proccing more often on the OH and not prioritizing the MH it is hurting the dps a lot (since oh does 50% less damage).

Off-hand should never and i mean never be a priority for any kind of melee. Things such as on-hit effects, enchantements and so on will always prioritize Main Hand. Atm as an Enh shaman i got Dragonstrike on MH equipped with a speed of 2.7s and Netherbane on OH with a 2.6. Netherbane is still proccing far more WF's than Dragonstrike itself. There are a number of abilities/enchant/items that DO give priority to MH and are working just fine, but WF users are being affected on overall as nate said because OH has a penalty of 50% dmg reduction, and it does also affect WF aswell.

**Comment by Easyfraggy** [comment]
The problem with this report is that it doesn't have enough data to say anything conclusively about anything. 

Someone go hit a mob in blasted lands for a couple hours and we will see whats up.

**Comment by Healweed** [comment]
If data is what you lack, then I assume that having 2 report samples for main hand equipped only(no off hand) , and the other report being only equipped with OH(no main hand equipped). That way gets more clear on procs report.

**Comment by Easyfraggy** [comment]
No you cannot test the priority by only equipping the 1 weapon - you need to test it with both weapons equipped.

**Comment by Peglaa** [comment]
Did a test of my own on the PTR, smacked Dr. Boom with SS. This is what I got:
SS: 546
MH: 184
OH: 148

I'm honestly not sure what to think here, slightly less MH procs than the elitist thread(but this could literally not mean anything, its statistics, it's never gonna be the same) but definitely a lot more relative OH procs(when compared to the difference between MH procs).

OH definitely doesn't seem to overtake MH tho, as for the spread between them being a bit tight, I'm not sure tbh. I'm thinking its fine.

Might just smack him with autos for a while and see what that yields me.

**Comment by Godmatik** [comment]
![wf1](https://github.com/user-attachments/assets/f2428e0f-80f6-479a-abb3-ec700baf277a)
![wf2](https://github.com/user-attachments/assets/0bff0f76-8d2c-4118-a4ae-aeb3f8c8d52e)
![wf3](https://github.com/user-attachments/assets/f331adc5-2e9a-403e-a4bd-2c17cc8cc88c)
![wf4](https://github.com/user-attachments/assets/9c87f8cd-316c-4e57-a023-4fc1ad7700b8)

Tested extensively and found that WF proc rate is currently correct.

Closing

**Comment by Godmatik** [comment]
Sample size performed with ~1200+ hits, and it matches what Pegla states as well

More MH procs than OH, and similar to results referenced from ElitiestJerks

We see no bug here.

Closing.

![wf5](https://github.com/user-attachments/assets/ef9fe911-2352-458f-b1f0-fcf8637d1650)
![wf6](https://github.com/user-attachments/assets/ef615cc8-a062-4448-9d44-13f3222a5e66)
![wf7](https://github.com/user-attachments/assets/07db9ce9-2538-4076-97a7-17ffe9d91a79)
