### ISSUE TITLE
[Walling Caverns] Serpentbloom

### ISSUE THREAD

**Issue by Knoox** [Atlantiss/NetherwingBugtracker#616]
**Apears when i track humanoids**: 
![wowscrnshot_092418_081218](https://user-images.githubusercontent.com/18479169/46053397-e8a61180-c142-11e8-889c-682dd628e3f0.jpg)

**Comment by xmesaj2** [comment]
is the rev 2054 on the server already? it should be fixed after it

**Comment by xmesaj2** [comment]
fixed in rev 2081
