### ISSUE TITLE
Apexis Enlightenmet

### ISSUE THREAD

**Issue by Saronitian** [Atlantiss/NetherwingBugtracker#6160]
[//]: # (Enclose links to things related to the bug using http://wowhead.com or any other TBC database.)
[//]: # (You can use screenshot ingame to visual the issue.)
[//]: # (Write your tickets according to the format:)
[//]: # ([Quest][Azuremyst Isle] Red Snapper - Very Tasty!)
[//]: # ([NPC] Magistrix Erona)
[//]: # ([Spell][Mage] Fireball)
[//]: # ([Npc][Drop] Ghostclaw Lynx)
[//]: # ([Web] Armory doesnt work)
[//]: # (To find server revision type `.server info` command in the game chat.)

**Description**: 
After a Wipe in Slave pens (heroic) one of our Member had the Apexis Enlightement buff on him an it was active. It also apperently stacked with other Effects because he was running faster than me (paladin with skilled Talent [Pursuit of Justice] wich gives also 15% movementspeed)
Related with #5990 
![WoWScrnShot_072519_121710](https://user-images.githubusercontent.com/49236238/61872177-f7845e80-aee2-11e9-9bc3-760d32a9c9dd.jpg)

I did not find any informations about if it does indead stack with enchantments or Talents So I do not know if that is correct or not.

**Current behaviour**:
Apexis Enlightments Movementspeed effect can still be active outside of Blades Edge Mountain
**Expected behaviour**: 
The Movementspeed buff should only be active while in Blade Edge Mountains.

**Server Revision**: 
3085

**Comment by Wolffenstein** [comment]
Fixed in rev 3091.
