### ISSUE TITLE
[Black Temple][Boss][Spell] Teron Gorefiend Shadow of Death

### ISSUE THREAD

**Issue by Haipethdev** [Atlantiss/NetherwingBugtracker#6162]
[//]: # (Enclose links to things related to the bug using http://wowhead.com or any other TBC database.)
[//]: # (You can use screenshot ingame to visual the issue.)
[//]: # (Write your tickets according to the format:)
[//]: # ([Quest][Azuremyst Isle] Red Snapper - Very Tasty!)
[//]: # ([NPC] Magistrix Erona)
[//]: # ([Spell][Mage] Fireball)
[//]: # ([Npc][Drop] Ghostclaw Lynx)
[//]: # ([Web] Armory doesnt work)
[//]: # (To find server revision type `.server info` command in the game chat.)

**Description**: 

Teron Gorefiend, after a player dies from Shadow of Death expiration, sometimes does not spawn in control of a ghost and therefore not able to use any of its abilities.  It will mostly appear as hostile.

https://images-ext-2.discordapp.net/external/Lcz6GOK-9BcDfs20UV9TonM1aZofXHhiSB6jqPvalCo/https/i.imgur.com/dvPapai.jpg?width=729&height=457

We ensure players do not stand too close to the corner, as this has been the source of similar bugs on other servers but that has not worked here.  We don't know what is causing it.

**Current behaviour**:

Sometimes, not sure how to reproduce, Shadow of Death doesn't give a player control of a ghost.

**Expected behaviour**: 

Player dies, gains control of ghost, can use abilities.

**Server Revision**: 

3085

**Comment by Haipethdev** [comment]
We are streaming it again now, if you wish to observe

**Comment by Haipethdev** [comment]
We have maybe identified it, if one ghost is stood on the person who is about to die, it might "block" the spawn.  There is some kind of area effect at play.

**Comment by gabbat** [comment]
just happend without anyone beeing near, a ghost standing on top of the next person is not the only cause at least. basically ghosts not spawning at random

**Comment by gabbat** [comment]
it might be related to ppl spamming buttons while they die? not sure, but very very frustrating to not spawn as a ghost

**Comment by Ceago** [comment]
Still an issue 3/5/2021.

**Comment by Godmatik** [comment]
Was fixed on Netherwing a while ago
