### ISSUE TITLE
[Black Temple][Boss][Spell] The Shadowmoon Deathshaper's Deathcoil is a buff instead of a debuff

### ISSUE THREAD

**Issue by Manaci** [Atlantiss/NetherwingBugtracker#6163]
**Current behaviour**:
The [Shadowmoon Deathshapers](https://db.excalibur.ws/?npc=22882) in Black Temple currently cast a [Death Coil](https://db.excalibur.ws/?spell=41070) that acts as a buff and can be toggled off, removing the fear.
**Expected behaviour**: 
Should be a debuff that you can't remove.
**Server Revision**: 
3085

**Comment by Wolffenstein** [comment]
Fixed in rev 3104.
