### ISSUE TITLE
[Spell][Polymorph] Applied 5 times in a row in PvP (instead of DR immunity)

### ISSUE THREAD

**Issue by b15andga** [Atlantiss/NetherwingBugtracker#6164]
[//]: # (Enclose links to things related to the bug using http://wowhead.com or any other TBC database.)
[//]: # (You can use screenshot ingame to visual the issue.)
[//]: # (Write your tickets according to the format:)
[//]: # ([Quest][Azuremyst Isle] Red Snapper - Very Tasty!)
[//]: # ([NPC] Magistrix Erona)
[//]: # ([Spell][Mage] Fireball)
[//]: # ([Npc][Drop] Ghostclaw Lynx)
[//]: # ([Web] Armory doesnt work)
[//]: # (To find server revision type `.server info` command in the game chat.)

**Description**: 
Poly should have a DR. Here, I was polymorphed 5 times in a row with DR in place - but not consistent.
**Current behaviour**:
Got polymorphed 5 times in a row in arena. Iirc it was full duration -> half duration -> half duration -> quarter duration -> quarter duration
https://imgur.com/a/3wRUOn7
**Expected behaviour**: 
Should be full duration -> half duration -> quarter duration -> immune
**Server Revision**: 
3091 (after server restart)

**Comment by The14me** [comment]
Rev.3460 not an issue anymore.
Can be closed.
