### ISSUE TITLE
Neutral guards do not aggro if players are killed in one attack

### ISSUE THREAD

**Issue by SchwarzCodes** [Atlantiss/NetherwingBugtracker#6165]
**Description**: 
Neutral guards do not aggro if players are killed in one attack.

**Current behaviour**:
Basically. if you one-shot enemy players in BB, the guards will not react and you can go about killing lowbies all day as long as you can kill them with a single spell.
**Expected behaviour**: 
Guards should aways attack the aggressor in pvp.
**Server Revision**: 
3091

**Comment by Wolffenstein** [comment]
Fixed in rev 3104.
