### ISSUE TITLE
[Spell][Priest] Vampiric Embrace Does Not Heal If Damage Kills Target.

### ISSUE THREAD

**Issue by Rdoolz51** [Atlantiss/NetherwingBugtracker#6166]
[//]: # (Enclose links to things related to the bug using http://wowhead.com or any other TBC database.)
[//]: # (You can use screenshot ingame to visual the issue.)
[//]: # (Write your tickets according to the format:)
[//]: # ([Quest][Azuremyst Isle] Red Snapper - Very Tasty!)
[//]: # ([NPC] Magistrix Erona)
[//]: # ([Spell][Mage] Fireball)
[//]: # ([Npc][Drop] Ghostclaw Lynx)
[//]: # ([Web] Armory doesnt work)
[//]: # (To find server revision type `.server info` command in the game chat.)

**Description**: 
Vampiric Embrace is a spell that you put on a target that heals you and your group for 25%(Talented up from original 15%) of any shadow spell damage you deal for 1 minute. Attaching a Link from TwinStar TBC to show the ability in a TBC time frame. https://tbc-twinhead.twinstar.cz/?spell=15286
**Current behaviour**:
Works as intended, but if you deal damage that kills the target, you or your group do not receive healing. (Ex. you mind blast at the beginning of a fight and deal 600damage, you are healed for ~120 Health (not calculating Spell Power/Healing bonus). But if you cast that same ability and the target has 500HP remaining, therefore killing the target, you will not receive healing.
**Expected behaviour**: 
You should be receiving healing for 25%(Talented up from original 15%) of shadow damage done whether the target dies or not.
**Server Revision**:

**Comment by SwiftieTBC** [comment]
Evidence https://youtu.be/zD2jDamEXJc?t=24 where as you can see the ~500 heal is from the mind blast and the ~300 heal is from the SWD. However the difference in the damage dealt and the healing recieved would suggest you only gain healing for the actual damage dealt and not the overkill amount.

**Comment by Rdoolz51** [comment]
I’ve tested in on multiple occasions and receive no healing at all. Even for non-overkill damage. Might be a different interaction for pvp and or shadow word: Death. But it is a real issue

**Comment by SwiftieTBC** [comment]
yeah im agreeing with you dude. It should heal for the amount it deals

**Comment by Wolffenstein** [comment]
Fixed in rev 3104.
