### ISSUE TITLE
[Item] Pendant of the Violet Eye

### ISSUE THREAD

**Issue by Firroth** [Atlantiss/NetherwingBugtracker#6168]
**Current behaviour**:
1 Chain heal = 3 stacks
1 Circle of healing = 5 stacks

Meaning it's OP trinket, for mana regen with it's current behaviour.

**Expected behaviour**: 

Should only stack 1 charge PER CAST, not per HOW MANY people were healed.

https://www.wowhead.com/item=28727/pendant-of-the-violet-eye#comments
https://wowwiki.fandom.com/wiki/Pendant_of_the_Violet_Eye
https://github.com/SunwellWoW/Sunwell-TBC-Bugtracker/issues/4316

**Server Revision**: 
3091

**Comment by gabbat** [comment]
where is the proof that it should work like you are saying?
your interpretation sounds logical, but thats not how blizzlike is determined.
the wowhead comments you linked even point in the other direction, even though not clearly:


"This definitely has some value for a holy spec priest. Just make a macro to pop it every time I hit Circle of Healing. I usually spam that 4-5 times when a group/groups get low anyways. It would be a great way to take the edge off of that mana useage."
--

**Comment by Firroth** [comment]
Proof is no people talking about it charging more stacks than 1. Only talks are about "direct heals" even for shammy about healing wave rank 1, not chain heal. Why use rank 1 HW, and not chain which would stack it faster?
If it should work like it does now people would comment spam about it, and it would be BiS item for every class pre 2.1 and so on, but there is none comments about it?

Also I gave link to "Sunwell's bug tracker report", which also provides some proofs to which he redirects (Corecraft's research by Shiro), so I didn't bother to post every link, when it's all included in these one.

**Comment by Wolffenstein** [comment]
Fixed in rev 3252.
