### ISSUE TITLE
[Raid][Magtheridon's Lair] - Magtheridon phase 3, blast nova

### ISSUE THREAD

**Issue by Firroth** [Atlantiss/NetherwingBugtracker#6169]
**Current behaviour**:
When you reach phase 3 (30%) of boss hp, his timer for blast nova bugs or doesn't occur at all.

In 2-3min. time he doesn't use his blast nova ability at all. We don't have super dps, so we should have 2-4 clicking rotations still during this phase, but he only used it once and and it happened only on 4% of his hp during this phase.

**Expected behaviour**: 
He should still use his blast nova ability, like he does in phase 2, with the same timer.
Right now Phase 3 is super easy, since it's just avoiding cave in, since blast nova's never occur.

**Server Revision**: 
3091

**Comment by Wookiefister** [comment]
I have done over 10 mag lockouts, and our blast novas always seems to go off reasonably close to his cd timer for it.

**Comment by Firroth** [comment]
@Wookiefister
You talking about phase 3 though? Since in phase 2 100% -> 30%, it does indeed work correctly. Case begins after 30% treshold, and it happened to us 3-4 times by now (every id, we attempted the boss).
I don't think we're doing anything special too for this to happen. We stop dps near 30% hp, wait for blast nova timer, after that we start dps again, to go into this phase 3 without any issues.

**Comment by Firroth** [comment]
Today it worked fine, for some reason. Will check it once more on next id, just to be sure.

**Comment by Easyfraggy** [comment]
It seems to be random - Thinking maybe if the blast nova coincides with him casting falling debree or some other spell causes it to get skipped?

**Comment by Godmatik** [comment]
Fixed a long time ago, Mag never skips a blast wave cast anymore.

Closing.
