### ISSUE TITLE
[Stonetalon Mountians] Random boat

### ISSUE THREAD

**Issue by Knoox** [Atlantiss/NetherwingBugtracker#617]
**Not much needs to be said, comes and goes**: 

![wowscrnshot_092418_071726](https://user-images.githubusercontent.com/18479169/46053427-14c19280-c143-11e8-96b5-8a4b8bdd46d7.jpg)

**Comment by manslaughter** [comment]
This appears to be the ratchet/booty bay boat.  When you hop on the boat, it will jump to the center of the continent before it continues on its expected path.  Same thing happens in eastern kingdoms (wetlands).

**Comment by Galawer** [comment]
A whole bunch of boats appears there. If you stand on them you'll eventually get teleported along with them to wherever they were going.

![image](https://user-images.githubusercontent.com/1574432/46290463-34feb080-c58c-11e8-845e-226d6a165d30.png)
![image](https://user-images.githubusercontent.com/1574432/46290520-5c557d80-c58c-11e8-8c86-f267f6ee90c5.png)

**Comment by Easyfraggy** [comment]
Retest in 2131 should be fixed.
