### ISSUE TITLE
[Core] Wierd teleporting issue, stuck porting between ratchet and booty bay.

### ISSUE THREAD

**Issue by truchonh** [Atlantiss/NetherwingBugtracker#6170]
[//]: # (Enclose links to things related to the bug using http://wowhead.com or any other TBC database.)
[//]: # (You can use screenshot ingame to visual the issue.)
[//]: # (Write your tickets according to the format:)
[//]: # ([Quest][Azuremyst Isle] Red Snapper - Very Tasty!)
[//]: # ([NPC] Magistrix Erona)
[//]: # ([Spell][Mage] Fireball)
[//]: # ([Npc][Drop] Ghostclaw Lynx)
[//]: # ([Web] Armory doesnt work)
[//]: # (To find server revision type `.server info` command in the game chat.)

**Description**: 
TLDR:
This lead me to believe that somehow, as I entered the Boulderslide Ravine area, the game thought I stepped on the boat in ratchet. It then kept me teleporting in the ocean from ratchet to booty bay until I correctly got out of the boat.

I was walking toward Boulderslide ravine in stonetalon mountain and as I entered the area, I clipped through the map and start flying everywhere super fast without control.
I logged out then back in, and got ported to booty bay as the boat entered the zone. From there, Im stuck in the water (where the boat arrive) constantly teleporting from ratchet to booty bay as the boats travel from one zone to the other.

I used the unstuck feature, but I keep getting teleported as a ghost in the same way as describe above.

My char name: Zaraydrael
Time: ~5h30 PM server time

I also opened a ticket to get a temporary fix, as I cannot play the game at the moment.

EDIT: I was able to get on the boat as a ghost, then once I stepped out, I stop being teleported. This lead me to believe that somehow, as I entered the Boulderslide Ravine area, the game thought I stepped on the boat in ratchet. It then kept me teleporting in the ocean from ratchet to booty bay until I correctly got out of the boat.
**Current behaviour**:

**Expected behaviour**: 

**Server Revision**:

**Comment by The14me** [comment]
That was fixed before by Emtec (cant find the right rev).
Can be closed.
