### ISSUE TITLE
[Nodes][Herb]Ragveil spawns in Zangarmarsh

### ISSUE THREAD

**Issue by Zadiel** [Atlantiss/NetherwingBugtracker#6171]
**Current behaviour**:
Ragveil spawns in Zangarmarsh are extremely rare; I flew over Zangarmarsh for 30 minutes with 2 other Alliance in the zone and found five total spawns. Even at the most camped it could be, I should be seeing significantly more than this given how many spawn points it has: https://www.wowhead.com/object=181275/ragveil

This is also evidenced by the fact that Ragveil has increased dramatically in price recently.
**Expected behaviour**: 
Ragveil shows up everywhere in Zangarmarsh as the primary herb in the zone.
**Server Revision**: 
3091

**Comment by danbopes** [comment]
#5687
