### ISSUE TITLE
[Quest] Life's Finer Pleasures

### ISSUE THREAD

**Issue by shatich** [Atlantiss/NetherwingBugtracker#6172]
[//]: # ([Quest][Hellfire Peninsula] Life's Finer Pleasures)
[//]: # ([NPC] Viera Sunwhisper)

**Description**: 
Need to give  Viera Sunwhisper bottle of Cenarion Spirits in order to move out of Falcons Watch 

**Current behaviour**:
After giving it, nothing happens, she stays at the same spot, and it says that objective is completed.
**Expected behaviour**: 
After completion, she should walk out Falcons Watch.

**Comment by Evolvee** [comment]
![image](https://user-images.githubusercontent.com/1942409/66254154-c3df7380-e772-11e9-8184-444a91409160.png)

works just fine for me, probably somehow bugged npc, ask GMs to reset the NPC if its still stuck

**Comment by The14me** [comment]
Still bugged-Reset her=nothing.
https://www.wowhead.com/quest=9472/arelions-mistress

**Comment by Evolvee** [comment]
core issue caused by wolf
