### ISSUE TITLE
missing friends

### ISSUE THREAD

**Issue by Dinqz** [Atlantiss/NetherwingBugtracker#6173]
[//]: # (Enclose links to things related to the bug using http://wowhead.com or any other TBC database.)
[//]: # (You can use screenshot ingame to visual the issue.)
[//]: # (Write your tickets according to the format:)
[//]: # ([Quest][Azuremyst Isle] Red Snapper - Very Tasty!)
[//]: # ([NPC] Magistrix Erona)
[//]: # ([Spell][Mage] Fireball)
[//]: # ([Npc][Drop] Ghostclaw Lynx)
[//]: # ([Web] Armory doesnt work)
[//]: # (To find server revision type `.server info` command in the game chat.

**Current behaviour**: cant open the cages, got keys, and children inside but nothing happen as of 28 of july. 

**Expected behaviour**: to free the children 12/12

**Server Revision**:

**Comment by Manaci** [comment]
Nice and detailed report kappa
