### ISSUE TITLE
[Dungeon] Botanica [Boss] Laj Elemental Shift ability does not change resistences

### ISSUE THREAD

**Issue by Fennas** [Atlantiss/NetherwingBugtracker#6175]
Laj is fourth boss in Botanica

**Description**: 
Laj Elemental Shift ability only changes color, not resistences

**Current behaviour**:
He does use this ability but it does only change his color and not his resistences. he always starts out with his black color and shadow resistence. 
This makes the fight terribly hard for warlocks and especially shadow priests.

**His Elemental Shift ability is supposed to work like this :**
Laj will randomly change color. When he does this, he will be resistant to certain types of magic (just like the mobs on both sides of the Botanist). The following are the colors/resistances he can change to:

    Blue (Frost Resistant)
    Red (Fire Resistant)
    Green (Nature Resistant)
    Black (Shadow Resistant)
    White (Arcane Resistant) 

(Source: own TBC experience, wowwiki https://wowwiki.fandom.com/wiki/Laj )

**Server Revision**: 
3091

**Comment by Wolffenstein** [comment]
Fixed in rev 3094.

**Comment by Fennas** [comment]
woohoo. That was fast. Ty
