### ISSUE TITLE
[Quest] [ZG] Signets of the Zandalar

### ISSUE THREAD

**Issue by Zakard1** [Atlantiss/NetherwingBugtracker#6176]
https://tbc-twinhead.twinstar.cz/?quest=8246
**Description**: 
You should be able to see and complete the quest by turning in 15 [Zandalar Honor Token] once you're Exalted with Zandalari Tribe. Should work just like Zanza's Potent Potables (8243) but with the reputation requirement.
**Current behaviour**:
Quest doesn't show up on Rin'wosho the Trader even while Exalted.
**Expected behaviour**: 
The quest should be available on Rin'wosho the Trader (14921) and repeatable once you reach Exalted.
**Server Revision**: 
3093

**Comment by Evolvee** [comment]
rev 3103
