### ISSUE TITLE
[Spell] Divine Intervention

### ISSUE THREAD

**Issue by joejoyce787** [Atlantiss/NetherwingBugtracker#6177]
Came across an old post which relates to this particular issue: https://github.com/Atlantiss/NetherwingBugtracker/issues/2912

**Description**: 
Character still alive after using Divine Intervention.

**Current behaviour**:
Used in conjunction with the Blessed Life talent (All attacks against you have a 10% chance to cause half damage) my character will only take 50% of the damage and will remain alive whilst still applying Divine Intervention to another target.

**Expected behaviour**: 
The paladin sacrifices himself to remove the targeted party member from harms way. Enemies will stop attacking the protected party member, who will be immune to all harmful attacks but cannot take any action for 3min.

**Server Revision**: 
3096

**Comment by Wolffenstein** [comment]
Fixed in rev 3104.
