### ISSUE TITLE
[Spell] [Shaman] Windfury totem proccing 15% instead of 20%

### ISSUE THREAD

**Issue by Easyfraggy** [Atlantiss/NetherwingBugtracker#6178]
**Description**: 

Either windfury can't proc from Glancing or the % is wrong.

**Current behaviour**:
Tested with only MH equipped and no special attacks used - to prevent the recount bug.

![image](https://user-images.githubusercontent.com/36134067/62143857-19ba1a00-b2f1-11e9-8453-b188353bba9b.png)

**Expected behaviour**: 

Should proc 20% of the time

**Server Revision**:

**Comment by mhawkins30** [comment]
What was the speed of the weapon you were using? Windfury has a hidden cooldown, it can't proc more often than once every 3 seconds. If the weapon you used to test this has <3.00 speed, then some of your hits coming within this cooldown would have thrown off the data.

**Comment by Easyfraggy** [comment]
Windfury Totem does not have a cooldown. You are thinking of Windfury weapon @mhawkins30

**Comment by liderer** [comment]
Windfury totem must not have hidden cooldown . pls fix this

At 1:48-1:50 in this video you can see the warrior got two proc . 

https://youtu.be/Hn8eMD8zdOo?t=101  


Revision as of 20:08, June 26, 2008

https://wowwiki.fandom.com/wiki/Windfury_Totem?oldid=1431588  

"The Windfury proc from the totem does not have a hidden cooldown like Windfury Weapon"  



https://www.mmo-champion.com/threads/603849-sword-spec-and-windfury 

"- Windfury Proc (totem) does not have a hidden CD."

**Comment by Easyfraggy** [comment]
Windfury totem does NOT have a hidden cooldown on NW atm - IDK why you suddenly think this. The proc rate is just wrong. I had plenty back to back procs with 1.0 weapon speed during the testing.

**Comment by Wolffenstein** [comment]
Fixed in rev 3104.
