### ISSUE TITLE
[NPC][Forge Camp: Terror] Fear Whisperer should be removed from game

### ISSUE THREAD

**Issue by raethkcj** [Atlantiss/NetherwingBugtracker#6179]
[//]: # (Enclose links to things related to the bug using http://wowhead.com or any other TBC database.)
[//]: # (You can use screenshot ingame to visual the issue.)
[//]: # (Write your tickets according to the format:)
[//]: # ([Quest][Azuremyst Isle] Red Snapper - Very Tasty!)
[//]: # ([NPC] Magistrix Erona)
[//]: # ([Spell][Mage] Fireball)
[//]: # ([Npc][Drop] Ghostclaw Lynx)
[//]: # ([Web] Armory doesnt work)
[//]: # (To find server revision type `.server info` command in the game chat.)

**Description**: 
https://www.wowhead.com/npc=22201/fear-whisperer#comments

**Current behaviour**:
Fear Whisperers still spawn at Terror.

**Expected behaviour**: 
Fear Whisperers should no longer spawn as of 2.1

**Server Revision**: 
3093

**Comment by Evolvee** [comment]
rev 3103
