### ISSUE TITLE
[Thunderbluff][NPC] Vhan

### ISSUE THREAD

**Issue by Knoox** [Atlantiss/NetherwingBugtracker#618]
**Some wierd tooltip images**: 

![wowscrnshot_092418_012527](https://user-images.githubusercontent.com/18479169/46053493-5d794b80-c143-11e8-89bc-70ab41316510.jpg)
![wowscrnshot_092418_012525](https://user-images.githubusercontent.com/18479169/46053495-5f430f00-c143-11e8-8a8d-a54105a18d78.jpg)

**Comment by Godmatik** [comment]
Delete cache folder and reload game, see if those icons are still that way.

**Comment by Easyfraggy** [comment]
Can someone confirm/deny this issue?

**Comment by wtRCH** [comment]
Confirmed.
![image](https://user-images.githubusercontent.com/11255782/49328971-1f503c00-f579-11e8-8e16-360d7c92929f.png)


@pelekon

**Comment by The14me** [comment]
rev 3441. still a issue.

**Comment by Wolffenstein** [comment]
Fixed in rev 3443.
