### ISSUE TITLE
[Dungeon]Stratholme Gate before Rivendare's Abomination square

### ISSUE THREAD

**Issue by ircfelix** [Atlantiss/NetherwingBugtracker#6180]
**Description**: 
If you die in the abomination room before Baron Rivendare, you can't go into this room any more because the gate keeps being closed.

Screenshot:

https://i.imgur.com/RTaV7r3.jpg

**Current behaviour**:
If you die in the abomination room before Baron Rivendare, you can't go into this room any more because the gate keeps being closed.

**Expected behaviour**: 
If you die in the abomination room before Baron Rivendare, you should be able to go into this room again (= the gate should be opened again).

**Server Revision**: 
3093

**Comment by Wolffenstein** [comment]
Fixed in rev 3783.
