### ISSUE TITLE
[Item]Deathcharger's Reins Drop Rate

### ISSUE THREAD

**Issue by ircfelix** [Atlantiss/NetherwingBugtracker#6181]
**Description**: 
Drop rate is currently at 0.01%.

**Current behaviour**:
Drop rate is currently at 0.01%.

**Expected behaviour**: 
Drop rate should be 1%, according to this comment on
https://de.classic.wowhead.com/item=13335/z%C3%BCgel-des-todesstreitrosses#english-comments :

> Von Tyrsenus (94,098 –  41·141·333)  am 2007.05.18 (Patch 2.0.12)
> The drop rate is now 1.0% (up from 0.02%) (source). I will leave the rest of this comment for nostalgic purposes.

**Server Revision**: 
3093

**Comment by Godmatik** [comment]
How do you know it is currently 0.01%?

**Comment by ircfelix** [comment]
Evolve told me

**Comment by mbzz88** [comment]
WowWiki says "Patch 3.0.2 (14-Oct-2008): Drop rate increased from 0.02% to 1%."
https://wowwiki.fandom.com/wiki/Deathcharger%27s_Reins
Also from that source link:  While random is indeed random, the chance of Deathchanger's Reins dropping was increased with 3.0.2. This is the second time the drop rate has been increased, from the rather crazy 1 in 5000 WAY back in the day to the 1 in 100 it is now. 
https://web.archive.org/web/20081217122736/http://forums.worldofwarcraft.com/thread.html?topicId=11675537865&sid=1&pageNo=5

**Comment by ircfelix** [comment]
Oh, well that's something solid. Even with a blue post! Still strange that the 1% comment I found is dated back to 2007.05.18 (Patch 2.0.12).

**Comment by Evolvee** [comment]
500 is not enough to test 0.4% drop rate

it will be 0.02% in rev 3103
