### ISSUE TITLE
[General]Mob Aggro/Pull Range is too High

### ISSUE THREAD

**Issue by ircfelix** [Atlantiss/NetherwingBugtracker#6182]
**Description**: 
Aggro range on low level mobs is too high

**Current behaviour**:
Aggro range on low level mobs is too high. Compare this vod https://www.twitch.tv/videos/460545443 to the retail video linked in expected behaviour.

**Expected behaviour**: 
Aggro range on low level mobs should be lower as seen in this vid (from 36s on), the mage can skip all trash by just walking by. This is not possible on NW. Every mob has a pull range like there's no tomorrow.
https://www.youtube.com/watch?v=fDLW5OalOLU

**Server Revision**: 
3093

**Comment by NatsumeLily** [comment]
The video you linked is from Wrath of the Lich king...

**Comment by ircfelix** [comment]
The guy in the video is still level 70 and the aggro range of mobs did not change in a miraculous way with patch 3.0.2

**Comment by ircfelix** [comment]
Also here you can see the paladin running into the mobs before they even aggro (around the 4 minute mark):
https://www.youtube.com/watch?v=WhOCMNAm2V8

**Comment by Easyfraggy** [comment]
Agro range is maybe half a yard larger than retail on those specific skeletons - either way this is lowest prio issue of all time. Lower than the water sounds when stepping in shallow water.

**Comment by Wolffenstein** [comment]
Fixed in rev 3104.

**Comment by ircfelix** [comment]
Tested on ptr, nothing changed compared to pre fix

**Comment by ircfelix** [comment]
@Wolffenstein  still not fixed
