### ISSUE TITLE
[Dungeon]Stratholme Ziggurat doors close + Acolytes bug after DC/Logout

### ISSUE THREAD

**Issue by ircfelix** [Atlantiss/NetherwingBugtracker#6183]
**Description**: 
In Stratholme UD there are 3 ziggurats with 5 acolytes per ziggurat. You need to kill all 15 acolytes in order to access the abomination room before Baron Rivendare.

**Current behaviour**:
When you kill acolytes in a ziggurat and relog, the ziggurat doors are closed and the acolytes are alive (I logged out due to afking fore more than 30 minutes). There is no way to open the doors and kill the acolytes again.

**Expected behaviour**: 
Once you've slain the ziggurat guardian (mini boss) in front of a ziggurat, the doors should stay open until the ID is reset and the acolytes should remain dead.

**Server Revision**: 
3093

**Comment by Wolffenstein** [comment]
Fixed in rev 3783.
