### ISSUE TITLE
[Quest] Unable to change Karazhan violet ring after first swap

### ISSUE THREAD

**Issue by danbopes** [Atlantiss/NetherwingBugtracker#6184]
**Description**: 
This is related to #5759. Upon reaching exalted with the Violet Eye, you're allowed to change from one ring to another by talking with Archmage Leryda. The problem is, when you switch to a different ring, the quest giver expects the first ring you originally had, and will not allow you to change again after the first time.

**Current behaviour**:
Head to Archmage Leryda:
`.mod rep 967 exalted`

Pickup/Handin quest "Path of the Violet Assassin" 10731
Continue to hand in quests:
Down the Violet Path - 10735
Distinguished Service - 10740
Eminence Among the Violet Eye - 10727

At this point you should have the item 'Violet Signet of the Master Assassin' (29283)
Archmage Leryda now offers: Assassin No More (11033)
Hand this quest in now with 75g and your Assassin ring, and choose Violet Signet of the Archmage
Archmage Leryda now continues to offer: Assassin No More (11033)
You're unable to click Continue, because you no longer have the assassin ring.

**Expected behaviour**: 
In the above example, it should remove the quest chain that you've completed already, and mark the other quest chain (for the item chosen) as rewarded, so they want to swap again, they have the correct "* no more" quest.

The quest chain:

|  |  |  |  |  |  |  |  | 
| ---: | --- | ---: | --- | ---: | --- | ---: | --- | 
| 10729 | Path of the Violet Mage | 10733 | Down the Violet Path | 10738 | Distinguished Service | 10725 | Eminence Among the Violet Eye | 
| 10730 | Path of the Violet Restorer | 10734 | Down the Violet Path | 10739 | Distinguished Service | 10726 | Eminence Among the Violet Eye | 
| 10731 | Path of the Violet Assassin | 10735 | Down the Violet Path | 10740 | Distinguished Service | 10727 | Eminence Among the Violet Eye | 
| 10732 | Path of the Violet Protector | 10736 | Down the Violet Path | 10741 | Distinguished Service | 10728 | Eminence Among the Violet Eye | 

So essentially, on completion of the following:

| ID | Title | 
| ---: | --- | 
| 11031 | Archmage No More | 
| 11032 | Protector No More | 
| 11033 | Assassin No More | 
| 11034 | Restorer No More | 

It should do the following:
Step 1: Remove ALL the following quests from the player (Easier to just nuke them all, instead of doing individual ones): From quest 10725 to 10741 (In total that's the 16 quests from above).
Step 2: Based on the reward chosen, mark the quests as rewarded:

| Item ID | Item Name                            | Quest Line                 |
|--------:|--------------------------------------|----------------------------|
|   29290 | Violet Signet of the Grand Restorer  | 10730, 10734, 10739, 10726 |
|   29279 | Violet Signet of the Great Protector | 10732, 10736, 10741, 10728 |
|   29283 | Violet Signet of the Master Assassin | 10731, 10735, 10740, 10727 |
|   29287 | Violet Signet of the Archmage        | 10729, 10733, 10738, 10725 |

This will now allow give the player the prerequisites to access the "* no more" quest for the current item he has. (Essentially allowing him to swap rings again)

**Server Revision**:
3072

**Comment by Evolvee** [comment]
Thanks for a good report 👍

**Comment by danbopes** [comment]
Fixed in rev 3122

**Comment by The14me** [comment]
Rev : 3157 its bugged again.

**Comment by subi900** [comment]
Hello,
i just tried to change my Karazhan Ring  "Violet Signet of the Great Protector" (Tank) to "Violet Signet of the Grand Restorer" (Heal) Unfortunately Archmage Leryda is only giving me the Option to change the Heal Ring to another one, which of course, I don't have anymore.

A Gamemaster led me to the bugtracker and i found this one here as fixed. But I have the exact same issue.  Traded the Heal Ring once to the Tank Ring and now cannot fullfill the "change" quest due it wants the Heal Ring again.

Maybe the issue got fixed for people who have not traded their Ring before rev 3122. I dont remember when i have traded the ring, but it happened already several months ago.

**Comment by danbopes** [comment]
This never got merged in. I'll push this tonight.

**Comment by Realnairoby** [comment]
Its still bugged

**Comment by danbopes** [comment]
Rev 3247

**Comment by bekonja** [comment]
still bugged for me

**Comment by danbopes** [comment]
If you're coming to this issue, and it's still bugged: This was not a retroactive change.

This is fixed for all characters moving forward, but if you've already swapped rings before this ring was changed, the easiest way to fix this, is to delete your current ring, and talk to the quest giver again (Who should give you your original ring back). If you swap after that point, your character will have the correct questline.

**Comment by subi900** [comment]
That is not entirely correct.  When you throw away your Ring, you will get the type of Ring again, which you obtained first for free. If you change it again you have to pay 75g but when going back you need to throw it away again.

It will safe you 75g for going back but it feels like bug using. :D
