### ISSUE TITLE
Character's macros won't save

### ISSUE THREAD

**Issue by smittythesmith** [Atlantiss/NetherwingBugtracker#6185]
**Description**: 
Character's macros will not save. Account macros save. Other character's macros save but not Jaredleto's macros.
**Current behaviour**:
The Macros belonging to Jaredleto disappear on logout.
**Expected behaviour**: 
The Macros belonging to Jaredleto should be saved on logout.
**Server Revision**: 
Server revision 3093

**Comment by smittythesmith** [comment]
I have deleted the cache and the WTF folder as instructed. This had no noticeable effect.

**Comment by Evolvee** [comment]
you have the wtf folders set to read-only, change that

**Comment by smittythesmith** [comment]
I deleted the WTF folder. The problem persists. I will make a new WTF
folder. I believe the problem has something to do with the fact that I made
a fighter with the same name, deleted him and then made this hunter. I
think there might be a server-side issue.

<http://www.avg.com/email-signature?utm_medium=email&utm_source=link&utm_campaign=sig-email&utm_content=webmail>
Virus-free.
www.avg.com
<http://www.avg.com/email-signature?utm_medium=email&utm_source=link&utm_campaign=sig-email&utm_content=webmail>
<#DAB4FAD8-2DD7-40BB-A1B8-4E2AA1F9FDF2>

**Comment by Evolvee** [comment]
macros are fully client side

as i said, you have the folder set as "read-only" mode, you need to change that

**Comment by smittythesmith** [comment]
how would that affect one character only?

<http://www.avg.com/email-signature?utm_medium=email&utm_source=link&utm_campaign=sig-email&utm_content=webmail>
Virus-free.
www.avg.com
<http://www.avg.com/email-signature?utm_medium=email&utm_source=link&utm_campaign=sig-email&utm_content=webmail>
<#DAB4FAD8-2DD7-40BB-A1B8-4E2AA1F9FDF2>

**Comment by smittythesmith** [comment]
As I said. on the advice of the discord channel I deleted the WTF folder. I
created a new folder it is empty. It is not read-only and if it was that
would affect more that just the one character.
BTW where are the macros saved client-side?

<http://www.avg.com/email-signature?utm_medium=email&utm_source=link&utm_campaign=sig-email&utm_content=webmail>
Virus-free.
www.avg.com
<http://www.avg.com/email-signature?utm_medium=email&utm_source=link&utm_campaign=sig-email&utm_content=webmail>
<#DAB4FAD8-2DD7-40BB-A1B8-4E2AA1F9FDF2>

**Comment by Evolvee** [comment]
in wtf folder...

only actions bars are saved server-side
