### ISSUE TITLE
Missing gossip option to restore Arthorn's Sparrowhawk Whistle

### ISSUE THREAD

**Issue by silmawien** [Atlantiss/NetherwingBugtracker#6186]
[//]: # (Enclose links to things related to the bug using http://wowhead.com or any other TBC database.)
[//]: # (You can use screenshot ingame to visual the issue.)
[//]: # (Write your tickets according to the format:)
[//]: # ([Quest][Azuremyst Isle] Red Snapper - Very Tasty!)
[//]: # ([NPC] Magistrix Erona)
[//]: # ([Spell][Mage] Fireball)
[//]: # ([Npc][Drop] Ghostclaw Lynx)
[//]: # ([Web] Armory doesnt work)
[//]: # (To find server revision type `.server info` command in the game chat.)

**Description**: 
I completed The Eagle's Essence, and used the whistle to summon Arthorn's Sparrowhawk and handed it in. When you hand in you lose the whistle. Before I could grab the followup The Falcon's Essence, the Sparrowhawk disappeared, and now there is no way to get on the followup.

**Current behaviour**:
If you fail to get the followup, you get stuck on the quest. Arthorn has no option to restore the whistle.

**Expected behaviour**: 
I believe Arthorn Windsong should have a gossip option to restore the whistle. This is according to the quest text here: https://tbcdb.com/?quest=10990

Here's a link to the spell from tbc-twinhead: https://tbc-twinhead.twinstar.cz/?spell=40886

**Server Revision**: 
210

EDIT: I managed to get on the followup using another druid's Sparrowhawk Whistle. This requires a bit of luck though. The issue remains.

**Comment by Evolvee** [comment]
rev 3103
