### ISSUE TITLE
[Spell][Shadowfiend] Attacking while feared

### ISSUE THREAD

**Issue by b15andga** [Atlantiss/NetherwingBugtracker#6187]
[//]: # (Enclose links to things related to the bug using http://wowhead.com or any other TBC database.)
[//]: # (You can use screenshot ingame to visual the issue.)
[//]: # (Write your tickets according to the format:)
[//]: # ([Quest][Azuremyst Isle] Red Snapper - Very Tasty!)
[//]: # ([NPC] Magistrix Erona)
[//]: # ([Spell][Mage] Fireball)
[//]: # ([Npc][Drop] Ghostclaw Lynx)
[//]: # ([Web] Armory doesnt work)
[//]: # (To find server revision type `.server info` command in the game chat.)

**Description**: 
In arena, my Shadowfiend was chasing and attacking his warrior target while being affected by Intimidating Shout. Might be worth adding that the Shadowfiend was summoned and ordered to attack the druid at first, and then changed target to the warrior.
https://www.youtube.com/watch?v=bVqOH6c8jmE
**Current behaviour**:
(Extremely rarily) chasing and attacking it's target while being feared.
**Expected behaviour**: 
Should not chase and attack it's target while feared, but rather run away (or stand still) in fear.
**Server Revision**: 
This is footage from 2019-07-26.

**Comment by Godmatik** [comment]
Rev 4016 - Unable to reproduce.

Tried multiple times, had the shadowfiend be the primary target of Intimidating shout and also be the secondary target so it gets feared - in either case it was correctly CCed and would not keep attacking. I also have not heard of this issue in the past year on Netherwing.

Likely fixed at some point.
