### ISSUE TITLE
Elemental Shaman T6 2 set bonus not working.

### ISSUE THREAD

**Issue by kubrick237** [Atlantiss/NetherwingBugtracker#6189]
Description:
I don't believe the two set bonus for elemental shaman T6 is working.

I see no buff when all four totems are down, and my character sheet does not reflect the increase crit/SP/MP5.

I also extensively watched my mana regen with all four totems down and it did not increase 15 mp5. I think this was the best way to test it rather than look at dps logs.

Unless I'm not seeing it, i don't believe it's working as intended. I own the T6 helm and gloves (if that helps - for all i know one of the items is not flagging the set bonus whereas a different combination of set pieces might)

**Comment by Easyfraggy** [comment]
Can confirm it does not appear to work at all.

**Comment by Wolffenstein** [comment]
Fixed in rev 3101.
