### ISSUE TITLE
[Quest][Bloodmyst Isle}The Hopeless Ones...

### ISSUE THREAD

**Issue by Sothanwow** [Atlantiss/NetherwingBugtracker#619]
**Description**: 
The quest [The hopeless Ones... ](https://www.wowhead.com/quest=9682/the-hopeless-ones)has a couple of issues the drop rate on the [BloodCursed soul](https://www.wowhead.com/item=24153/bloodcursed-soul) seemed very low on the level 16 my mob info showed after 12 kills a 12% chance to drop the item. While the 17 seemed to be dropping them fairly regularly. They also seemed to have a fair sloww respawn rate. 
I think there should of been some on the shelf down there but I didn't see any you can see them in this video here though https://www.youtube.com/watch?v=ZOQZGHt7BDM

Edit: This is how it looked on the shelf when I got there. https://imgur.com/a/BN1cO4a

**Current behaviour**:
Low droprate on quest item and low respawn rate.
**Expected behaviour**: 
Higher drop rate and higher respawn rate. 
**Server Revision**: 
2060

**Comment by ttghnw** [comment]
There seem to be not enough mobs to complete the quest even with a higher resp rate

**Comment by aresbrutus** [comment]
The drop rate is not really that low, but there were indeed some missing mobs. This will be fixed in one of the next updates.
