### ISSUE TITLE
[Loot][Dungeon]Baron Rivendare

### ISSUE THREAD

**Issue by ircfelix** [Atlantiss/NetherwingBugtracker#6191]
**Description**: 
Baron Rivendare does not drop enough loot.

**Current behaviour**:
He drops two items

**Expected behaviour**: 
He should drop three items as seen in https://www.youtube.com/watch?v=6DEEYMGS24w 9:45.

**Server Revision**: 
3097

**Comment by ircfelix** [comment]
https://www.youtube.com/watch?v=WhOCMNAm2V8 5:56

**Comment by Evolvee** [comment]
rev 3103
