### ISSUE TITLE
[Spell] Rescued Sporeggar Scout gives incorrect reputation

### ISSUE THREAD

**Issue by lajhar** [Atlantiss/NetherwingBugtracker#6192]
**Description**: 
Rescued Sporeggar Scout gives incorrect amount of reputation. It is spawned via opening an Ethereum Prison (spell 35349) using Ethereum Prison Key (item 29460).

**Current behaviour**:
Value of Effect #1 of spell Reputation: +500 Sporeggar (39476) is currently set to 150.

**Expected behaviour**: 
Value of Effect #1 of spell Reputation: +500 Sporeggar (39476) should be set to 450.

**Server Revision**: 
3099

Sources:
[Wowwiki](https://wowwiki.fandom.com/wiki/Ethereum_Prison)
[Wowhead](https://www.wowhead.com/npc=22814/rescued-sporeggar-scout#comments)

**Comment by Evolvee** [comment]
![image](https://user-images.githubusercontent.com/1942409/62422711-28208100-b6b7-11e9-84d8-b0344058bd64.png)

its correct

**Comment by Evolvee** [comment]
the spell is still the same from 2.1. to 2.4.3... it must have been custom retail server-side spell then

**Comment by lajhar** [comment]
Yeah that's odd.
There's a ticket for the same issue on [Twinstar ](https://webcache.googleusercontent.com/search?q=cache:NbZtp0rE454J:https://tbc-twinhead.twinstar.cz/%3Fissue%3D3978+&cd=3&hl=hu&ct=clnk&gl=hu)(I can access it only via webarchive).
In addition, in [this DB](http://wowka.su/?spell=39476) I see that they've added +300 Custom Reward Rate in addition to the Base value.

**Comment by Evolvee** [comment]
rev 3103
