### ISSUE TITLE
Black temple Shadowmoon Grunt Immune to slow's/nova and possibly other abilities

### ISSUE THREAD

**Issue by kizzymodo** [Atlantiss/NetherwingBugtracker#6193]
https://www.youtube.com/watch?v=ungvjpr9bGQ mage solo farming it in Oct 15, 2007 when BT was released in may 22, 2007 5 months after release

**Description**: Not 100% sure if its all CC but as u can see from the video the mob can be slowed and from patch notes from https://wowwiki.fandom.com/wiki/Shadowmoon_Grunt there has been changes to that mob state where it's immune to all CC. On the patch notes all it say's Patches and hotfixes Patch 2.1.0 (22-May-2007): Added. Looked for other video's but u rarely find guilds from 2007-2008 doing trash.

Also checked on https://wow.gamepedia.com/Patch_2.0.1 patch notes from 2.01-to 2.4.3 theres no changes thoughs Shadowmoon grunts.

**Current behaviour**:Currently u can't slow the mob down at all even with frost spells including nova which u see in the video also.

**Expected behaviour**: It show be slowable 100% from patch notes doesn't say at all there immune to everything.

**Server Revision**:

**Comment by Wolffenstein** [comment]
Fixed in rev 3104.
