### ISSUE TITLE
Durotar to Grom'Gol Zeppelin

### ISSUE THREAD

**Issue by Godmatik** [Atlantiss/NetherwingBugtracker#6195]
Snurk Bucksquick announces that the Grom'Gol Zeppelin has arrived about 10 seconds before it actually docks, should only yell his announcement once the Zeppelin has come to a complete stop and is fully docked. 

The announcement for the Durotar --> Undercity Zeppelin works perfectly.

Rev 3101

**Comment by Wolffenstein** [comment]
Blizzlike - check DBC.
