### ISSUE TITLE
Highland Mixed School in Skettis: I am fishing up "Empty Slot"

### ISSUE THREAD

**Issue by GerryBrown** [Atlantiss/NetherwingBugtracker#6196]
**Description**: 
While fishing Highland Mixed Schools in Skettis, I am occasionally (~5% of successful casts) looting "Empty Slot". As far as I can tell this is not intended. Screenshot available at https://imgur.com/a/jQgKcMR

**Server Revision**: 
3101

**Comment by Manaci** [comment]
Fixed
