### ISSUE TITLE
[Shaman][Spell] Windwall Totem doesn't reduce damage

### ISSUE THREAD

**Issue by raethkcj** [Atlantiss/NetherwingBugtracker#6197]
[//]: # (Enclose links to things related to the bug using http://wowhead.com or any other TBC database.)
[//]: # (You can use screenshot ingame to visual the issue.)
[//]: # (Write your tickets according to the format:)
[//]: # ([Quest][Azuremyst Isle] Red Snapper - Very Tasty!)
[//]: # ([NPC] Magistrix Erona)
[//]: # ([Spell][Mage] Fireball)
[//]: # ([Npc][Drop] Ghostclaw Lynx)
[//]: # ([Web] Armory doesnt work)
[//]: # (To find server revision type `.server info` command in the game chat.)

**Description**: 
Windwall Totem seems to have no effect on ranged damage. I tested Skettis Talonite in Skettis with no gear equipped, I had 122 armor giving me 1.14% damage mitigation (almost none). Rank 4 Windwall Totem should reduced ranged damage taken by 102.

Totem active:
![windwalltotem](https://user-images.githubusercontent.com/7716908/62553539-241a6d80-b835-11e9-8242-b2232353ff7d.jpg)

Totem not active:
![withouttotem](https://user-images.githubusercontent.com/7716908/62553546-27155e00-b835-11e9-937d-26074333c945.jpg)

Average/Median damage taken:
![image](https://user-images.githubusercontent.com/7716908/62554033-0a2d5a80-b836-11e9-9ed6-115ab4dd72b9.png)

**Current behaviour**:
Windwall Totem does not reduce ranged damage taken.

**Expected behaviour**: 
https://wow.gamepedia.com/Windwall_Totem
> XX damage is subtracted from each ranged hit received. Windwall Totem decreases the damage before, not after, armor mitigation.

**Server Revision**: 
3101

**Comment by Wolffenstein** [comment]
Fixed in rev 3104.
