### ISSUE TITLE
[Core] 6 People in group in raid

### ISSUE THREAD

**Issue by Tereneckla** [Atlantiss/NetherwingBugtracker#6199]
[//]: # (Enclose links to things related to the bug using http://wowhead.com or any other TBC database.)
[//]: # (You can use screenshot ingame to visual the issue.)
[//]: # (Write your tickets according to the format:)
[//]: # ([Quest][Azuremyst Isle] Red Snapper - Very Tasty!)
[//]: # ([NPC] Magistrix Erona)
[//]: # ([Spell][Mage] Fireball)
[//]: # ([Npc][Drop] Ghostclaw Lynx)
[//]: # ([Web] Armory doesnt work)
[//]: # (To find server revision type `.server info` command in the game chat.)

**Description**: You can have 6 (or maybe more) people in a group in a raid by inviting when g1 is full.

**Current behaviour**: You get 6 people in 1 group.
All 6 people received the druid crit aura.
No one was queueing bg.

**Expected behaviour**: Invited person gets put in the first group with an open spot.

**Server Revision**: 3101
![WoWScrnShot_080619_210116](https://user-images.githubusercontent.com/50233983/62568742-0f1df880-b88e-11e9-8e63-44df301901ef.jpg)

**Comment by Easyfraggy** [comment]
possibly UI issue? Never had this.

**Comment by Kolgrim** [comment]
It happens when someone is in a BG queue/inside of a BG when you invite them.

**Comment by bekonja** [comment]
@Easyfraggy we had this bug in our raid multiple times, i was just cba reporting it

**Comment by ScottieDOESknow** [comment]
Still happening as of today.

SR - 3185

**Comment by Godmatik** [comment]
Fixed last year
