### ISSUE TITLE
Initiating Hyjal trash generates a Raid ID.

### ISSUE THREAD

**Issue by maidros** [Atlantiss/NetherwingBugtracker#6200]
**Description**: 
Initiating Hyjal trash generates a Raid ID, locking all those inside to that ID. This ruins the ability for cross-guild trash/rep farming, since players will be saved to this ID instead of their guild's ID, and only one guild can potentially utilize the trash-generated ID thus locking out other guilds from Hyjal that week.

**Current behaviour**:
Upon talking to Jaina to initiate the 8 trash waves in the first base, every player inside the instance receives a message "You are now saved to this instance" and they now have a unique raid ID, locking them out from other Hyjal raids.

**Expected behaviour**: 
Only killing the first boss Rage Winterchill (after all 8 waves of trash) should save players to the instance and generate an ID - in common with all other raid instances on Netherwing.

**Server Revision**: 
AtlantissCoreTBC - Server Revision: 3101 [Branch: master, Hash: 8f7c0cc351d2]

**Comment by Easyfraggy** [comment]
Not sure this is a bug.

**Comment by Godmatik** [comment]
Looked up a quick Rage Winterchill video from 2007 which also included the trash before, at 5:02 (after he dies) it shows him saved to the raid instance, not when the trash begins.

https://www.youtube.com/watch?v=bo6yLMBwybU

**Comment by maidros** [comment]
Here is a video published in 2007 showing that the player in original TBC received the chat message "You are now saved to this instance" only after Rage Winterchill died, and not when Jaina was talked to or when the trash began. Skip to 5 minutes into the video and look at the chat window. It shows that random pugs were able to farm Hyjal trash without getting saved after starting the event. They should be able to trash farm with pugs and still go to their own guild's Hyjal raid so long as they avoid killing (not engaging, but killing) Rage Winterchill.

https://youtu.be/bo6yLMBwybU?t=305

**Comment by maidros** [comment]
sorry, godmatik posted this video before me, i hadn't refreshed the page yet. anyways...

**Comment by maidros** [comment]
Here is a screenshot from retail BfA today, showing that even up to this day it has not been changed/patched, and starting the event or killing trash has never saved you to the instance.

You can see that the player is not saved to Hyjal in his Raid ID tab, and the first trash wave is dead and the UI says it's on wave 2 of 8. 

https://cdn.discordapp.com/attachments/573390776138989568/608529048691539970/unknown.png

**Comment by tcberk12** [comment]
I'm not sure you are saved immediately upon talking to Jaina on NW. In my experience (went in for memes after I first was attuned), the lock only occured once she died to the trash.

**Comment by Godmatik** [comment]
ID initiated after you kill Rage, this was fixed at some point, can close
