### ISSUE TITLE
akama trash that you kill before you kill her will respawn as hostile after her death, even though it should be friendly

### ISSUE THREAD

**Issue by gabbat** [Atlantiss/NetherwingBugtracker#6201]
akama trash that you kill before you kill her will respawn as hostile after her death, even though it should be friendly

**Comment by Easyfraggy** [comment]
Akama trash doesn't respawn after you kill him.

**Comment by eri1997** [comment]
I believe he is talking about the trash that should become friendly after you do the akama event. If you kill any of those (usually the ones on the teleporter is what ppl kill) next time they spawn they will not be friendly if you did the akama event while they were dead.

**Comment by gabbat** [comment]
eri is correct. ashtongue dudes around the teleporter do respawn and then be hostile

**Comment by Easyfraggy** [comment]
Should you even be able to kill them? Or should they maybe not respawn if you do 🤔

**Comment by gabbat** [comment]
either not respawn or respawn friendly, but respawning hostile after akama is dead is bonkers

**Comment by Easyfraggy** [comment]
It seems unlikely that you should be able to kill them at all imo.

**Comment by Wolffenstein** [comment]
Fixed in rev 3104.
