### ISSUE TITLE
gnomish poultryizer

### ISSUE THREAD

**Issue by sabutnoy** [Atlantiss/NetherwingBugtracker#6202]
**Description**: 
Turns the target into a chicken for 15 sec. The effect is broken by any damage.
I would like to ask to raise the level of the problem #5648 
Almost any class of carriers of “clothes” will not live these 15 seconds in silence, and this is not counting the stuns.
often used in the world of PvP and on the battlefield.
**Current behaviour**:
Does not always break on damage.
**Expected behaviour**: 
The effect SHOULD BE broken by any damage.
**Server Revision**: 
3101

**Comment by Wolffenstein** [comment]
#5648.
