### ISSUE TITLE
[NPC][Raid][Mount Hyjal] Azgalor still casting Doom on Main Tank

### ISSUE THREAD

**Issue by Gibi-gibii** [Atlantiss/NetherwingBugtracker#6204]
**Current behaviour**: Azgalor is casting Doom on the Main tank

**Expected behaviour**: As of server revision 3035, Azgalor should no longer cast Doom on the Main Tank

https://clips.twitch.tv/RespectfulBraveBadgerStoneLightning

**Server Revision**: 3101

**Comment by Wolffenstein** [comment]
Fixed in rev 3104.

**Comment by Gibi-gibii** [comment]
https://clips.twitch.tv/IntelligentEagerGrasshopperEleGiggle
Server Revision 3106
Azgalor used Doom on MT

**Comment by Wolffenstein** [comment]
Hopefully fixed in rev 3109.
