### ISSUE TITLE
[Spell][Paladin] Seal of Blood : Deflections & Parries

### ISSUE THREAD

**Issue by Excinerus** [Atlantiss/NetherwingBugtracker#6205]
**Description**: 
Seal of Blood Procs are magical melee hits, and thus can miss, crit, be dodged and deflected (parried), deflection here acts like parries, is affected by defense and expertise ratings but just with a different flair.
https://wowwiki.fandom.com/wiki/Deflect
**Current behaviour**:
Currently, Seal of blood procs are being Deflected And Parried.
![unknown](https://user-images.githubusercontent.com/6299495/62824950-595fec00-bba4-11e9-94e8-89bd4c6639e9.png)
**Expected behaviour**: 
Seal of blood procs should be deflected but not parried.
**Server Revision**: 
3101

**Comment by Wolffenstein** [comment]
Fixed in rev 3104.
