### ISSUE TITLE
[Quest][Daily] Call to Arms only targets Warsong Gulch

### ISSUE THREAD

**Issue by raethkcj** [Atlantiss/NetherwingBugtracker#6206]
**Description**: 
The Battleground daily quest Call to Arms should rotate randomly between all 4 battlegrounds.

**Current behaviour**:
The only battleground daily available is Call to Arms: Warsong Gulch
[A] https://tbc-twinhead.twinstar.cz/?quest=11338
[H] https://tbc-twinhead.twinstar.cz/?quest=11342

**Expected behaviour**: 
The quest should randomly target any of the four battlegrounds each day.
Arathi Basin:
[A] https://tbc-twinhead.twinstar.cz/?quest=11335
[H] https://tbc-twinhead.twinstar.cz/?quest=11339

Alterac Valley:
[A] https://tbc-twinhead.twinstar.cz/?quest=11336
[H] https://tbc-twinhead.twinstar.cz/?quest=11340

Eye of the Storm:
[A] https://tbc-twinhead.twinstar.cz/?quest=11337
[H] https://tbc-twinhead.twinstar.cz/?quest=11341

**Server Revision**: 
3101

**Comment by Evolvee** [comment]
fixed in next rev
