### ISSUE TITLE
[Core] Recovering body after leaving raid group

### ISSUE THREAD

**Issue by raethkcj** [Atlantiss/NetherwingBugtracker#6207]
[//]: # (Enclose links to things related to the bug using http://wowhead.com or any other TBC database.)
[//]: # (You can use screenshot ingame to visual the issue.)
[//]: # (Write your tickets according to the format:)
[//]: # ([Quest][Azuremyst Isle] Red Snapper - Very Tasty!)
[//]: # ([NPC] Magistrix Erona)
[//]: # ([Spell][Mage] Fireball)
[//]: # ([Npc][Drop] Ghostclaw Lynx)
[//]: # ([Web] Armory doesnt work)
[//]: # (To find server revision type `.server info` command in the game chat.)

**Description**:
When you die inside a raid, and leave the raid group while running back, running into the instance portal should respawn you outside of the raid. Currently, you have to run back to spirit healer to take a res, since you cannot get to your body.

**Current behaviour**:
Running into the instance portal gives a "You must be in a raid group to enter the instance" but you stay as a ghost

**Expected behaviour**: 
Running into the instance portal still gives a "You must be in a raid group" message, but brings you back to life on top of the portal. 

**Server Revision**: 
3101

**Comment by Wolffenstein** [comment]
Fixed in rev 3104.
