### ISSUE TITLE
[Item][Strong Anti-Venom] Removes high level poisons

### ISSUE THREAD

**Issue by b15andga** [Atlantiss/NetherwingBugtracker#6208]
[//]: # (Enclose links to things related to the bug using http://wowhead.com or any other TBC database.)
[//]: # (You can use screenshot ingame to visual the issue.)
[//]: # (Write your tickets according to the format:)
[//]: # ([Quest][Azuremyst Isle] Red Snapper - Very Tasty!)
[//]: # ([NPC] Magistrix Erona)
[//]: # ([Spell][Mage] Fireball)
[//]: # ([Npc][Drop] Ghostclaw Lynx)
[//]: # ([Web] Armory doesnt work)
[//]: # (To find server revision type `.server info` command in the game chat.)

**Description**: 
"Target is cured of poisons up to level 35"
**Current behaviour**:
Removes stronger poisons, i e those from the Mother Shahraz trash in Black Temple. I believe something similar goes for Anti-Venom.
**Expected behaviour**: 
Asked Evolve. Replied it shouldn't work. Hence the report.
**Server Revision**: 
3101

**Comment by Wolffenstein** [comment]
Fixed in rev 3104.
