### ISSUE TITLE
[Tirisfal Glades][Drop] 

### ISSUE THREAD

**Issue by Ceago** [Atlantiss/NetherwingBugtracker#621]
Small bag drops may be a bit too high in Tirisfal.  Unless I'm stupidly lucky i have way too many at level 10.  
![bag drop](https://user-images.githubusercontent.com/43499757/46053618-9bf61280-c111-11e8-996a-48d928ddabb3.PNG)

**Comment by xmesaj2** [comment]
not using global loot perhaps

**Comment by Shanghi** [comment]
This should be fixed in revision 2121. It was using both global loot and old, normal loot!
