### ISSUE TITLE
Relentless Earthstorm Diamond

### ISSUE THREAD

**Issue by danelmore** [Atlantiss/NetherwingBugtracker#6211]
[//]: # (Enclose links to things related to the bug using http://wowhead.com or any other TBC database.)
[//]: # (You can use screenshot ingame to visual the issue.)
[//]: # (Write your tickets according to the format:)
[//]: # ([Quest][Azuremyst Isle] Red Snapper - Very Tasty!)
[//]: # ([NPC] Magistrix Erona)
[//]: # ([Spell][Mage] Fireball)
[//]: # ([Npc][Drop] Ghostclaw Lynx)
[//]: # ([Web] Armory doesnt work)
[//]: # (To find server revision type `.server info` command in the game chat.)

**Description**: The increased crit effect should work for spells until 2.2

**Current behaviour**:doesn't increase damage of shadowbolt at all

**Expected behaviour**: 3% increased crit effect

**Server Revision**:

**Comment by Wolffenstein** [comment]
It works properly, I tested it.
