### ISSUE TITLE
[core] negative class condition quest_template bug (SkillOrClass)

### ISSUE THREAD

**Issue by Manaci** [Atlantiss/NetherwingBugtracker#6212]
(Rip Excalibur database)

**ZG Necks**
The Necklace-upgrading quests from the Zandalar Tribe is currently not progressing past the initial quest. Right now you can, as a Hunter, only take the [The Maelstrom's Tendril](https://tbc-twinhead.twinstar.cz/?quest=81459) (Friendly) quest and then when you become honored, you can't take the next [The Maelstrom's Tendril](https://tbc-twinhead.twinstar.cz/?quest=8146) quest. 
Same can probably be said for the [revered version](https://tbc-twinhead.twinstar.cz/?quest=8147) and the [exalted version](https://tbc-twinhead.twinstar.cz/?quest=8148). This most likely affects every single class version of these necklaces too, so all the honored+ necklace quests from [Falthir the Sightless](https://tbcdb.com/?npc=14905), [Jin'rokh the Breaker](https://tbcdb.com/?npc=14902), [Al'tabim the All-Seeing](https://tbcdb.com/?npc=14903) and [Maywiki of Zuldazar](https://tbcdb.com/?npc=14904).

~~**Essence Mangoes**~~
The repeatable [Essence Mangoes Quest](https://tbc-twinhead.twinstar.cz/?quest=8196) is not given by [Rin'wosho the Trader](https://tbc-twinhead.twinstar.cz/?npc=14921) when players become honored with the Zandalar Tribe.

~~**The Hexxer's Head**~~
[Jin'do the Hexxer](https://tbc-twinhead.twinstar.cz/?npc=11380) drops an old removed quest item called [The Hexxer's Head](https://tbc-twinhead.twinstar.cz/?item=19882) that has no usage after 1.10.
**Server Revision**: 
3101

**Comment by Evolvee** [comment]
Essence Mangoes,The Hexxer's Head fixed in next rev.

**Comment by Manaci** [comment]
Btw this also involves all the head enchant quests from [Zanza the Restless](https://db.excalibur.ws/?npc=15042) like the hunter one called [Falcon's Call](https://db.excalibur.ws/?quest=8187) since you cannot accept those either cause of this bug.

**Comment by Wolffenstein** [comment]
Fixed in rev 3223.
