### ISSUE TITLE
Stalking the stalkers

### ISSUE THREAD

**Issue by notaslave** [Atlantiss/NetherwingBugtracker#6213]
Stalking the Stalkers

Silvermane Howlers npc 2925

**Description**: 
There should be 20 silvermane howlers spawned in the zone, with a fairly reasonable respawn timer.
**Current behavior**:
There is only 1 respawn with a 5 minute timer at any given moment which will respawn in one of the 20 possible locations. I don't think at any point in the 3 hours of being in the zone have I located 2 spawned at once.
**Expected behavior**: 
All 20 respawns should be up and on a roughly 5 minute timer.

**Comment by Evolvee** [comment]
u need to kill other howlers, they have shared spawn points (if u kill 1, there is a chance some other respawns instead of it)

**Comment by Evolvee** [comment]
https://www.wowhead.com/npc=2925/silvermane-howler#comments:id=559732
