### ISSUE TITLE
[Spell][Enchanting] Small Prismatic Shard

### ISSUE THREAD

**Issue by lyubomeer** [Atlantiss/NetherwingBugtracker#6214]
[//]: # (Enclose links to things related to the bug using http://wowhead.com or any other TBC database.)
[//]: # (You can use screenshot ingame to visual the issue.)
[//]: # (Write your tickets according to the format:)
[//]: # ([Quest][Azuremyst Isle] Red Snapper - Very Tasty!)
[//]: # ([NPC] Magistrix Erona)
[//]: # ([Spell][Mage] Fireball)
[//]: # ([Npc][Drop] Ghostclaw Lynx)
[//]: # ([Web] Armory doesnt work)
[//]: # (To find server revision type `.server info` command in the game chat.)

**Description**: Small Prismatic Shard spell is not available from any of the enchanting trainers.

**Current behaviour**: https://tbcdb.com/?spell=42615 is not in the game.

**Expected behaviour**: Should have been added for  Master Enchanting Trainers as of 2.2 along with the Nexus Transformation https://tbcdb.com/?spell=42613

http://web.archive.org/web/20071117170106/http://thottbot.com/s42615
http://web.archive.org/web/20071118191941/http://thottbot.com/s42613
![image](https://user-images.githubusercontent.com/11522170/63038476-ee772380-bec9-11e9-9312-27a0233576d7.png)
**Server Revision**: 3106

**Comment by ScottieDOESknow** [comment]
relevant trainers
![image](https://user-images.githubusercontent.com/43949261/63093804-8a3d7980-bf34-11e9-9a59-fc7ca8eb5e19.png)

**Comment by Evolvee** [comment]
rev 3107
