### ISSUE TITLE
[Spell][Enchanting] Nexus Transformation

### ISSUE THREAD

**Issue by Kolgrim** [Atlantiss/NetherwingBugtracker#6215]
[//]: # (Enclose links to things related to the bug using http://wowhead.com or any other TBC database.)
[//]: # (You can use screenshot ingame to visual the issue.)
[//]: # (Write your tickets according to the format:)
[//]: # ([Quest][Azuremyst Isle] Red Snapper - Very Tasty!)
[//]: # ([NPC] Magistrix Erona)
[//]: # ([Spell][Mage] Fireball)
[//]: # ([Npc][Drop] Ghostclaw Lynx)
[//]: # ([Web] Armory doesnt work)
[//]: # (To find server revision type `.server info` command in the game chat.)

**Description**: The spell to turn a Nexus Crystal into a Small Prismatic Shard was supposed to be added in 2.2 - Trainable by the enchanting trainers in hellfire, and the scryer enchanting trainer on scryer rise. There is already a bug report for the Small Prismatic Shard spell. Just figured I would make one specifically for Nexus Transformation.

**Current behaviour**: Not able to be trained (along with the spell to turn 1x Large Prismatic into 3x Small Prismatic)

**Expected behaviour**: Both should be able to be trained.

**Server Revision**: 3106

**Comment by Evolvee** [comment]
duplicate

**Comment by Evolvee** [comment]
https://github.com/Atlantiss/NetherwingBugtracker/issues/6214
