### ISSUE TITLE
[Item] Illidari-Bane Mageblade

### ISSUE THREAD

**Issue by Drsmartinkus** [Atlantiss/NetherwingBugtracker#6216]
**Description**: 

Was wondering if dmg againts demons works correctly?
Im using this Illidari-Bane Mageblade
https://www.wowhead.com/item=30787/illidari-bane-mageblade to fight demons and my first impression is that im doing less damage with that weapon than with my 
Runesong Dagger which is +121 spell dmg one

**Current behaviour**:

Test Case 1:
buffs: Divine spirit (50 spirit), Stamina
Total spell damage: 669
Mob: WrathWalker 67 lvl
Spell used: Smite
Range dmg (from 5 hits): 1063, 1032, 1043, 1045, 1049
Item used: Runesong Dagger

More or less always above 1k+

Test Case 2
buffs: Divine spirit (50 spirit), Stamina
Total spell damage: 548
Mob: WrathWalker 67 lvl
Spell used: Smite
Range dmg (from 5 hits): 993 ,941, 952, 973, 982
Item: Illidari-Bane Mageblade

More or less always below 1k with range of 900

**Expected behaviour**: 

I should do more dmg than with Runesong Dagger because Runesong Dagger has spell dmg 121
and Illidari-Bane Mageblade flighting demons has spell dmg 185

**Server Revision**:

**Comment by Godmatik** [comment]
Rev 4018 - not bugged.

Used spells on demons with 0 spell damage, and then only equipped the Mageblade - it definitely is increasing damage done, then also tested on a non-demon and it properly does not add damage against that.
