### ISSUE TITLE
[Raid][Loot][SSC/TK] Amount of drop should be increased

### ISSUE THREAD

**Issue by veekk** [Atlantiss/NetherwingBugtracker#6219]
**Description**:  [wowwiki](https://wowwiki.fandom.com/wiki/Patch_2.2.0)
Tempest Keep and Coilfang raid bosses will now all drop at least 3 items each.

**Current behaviour**:

**Expected behaviour**: 

**Server Revision**: 3106

**Comment by Wolffenstein** [comment]
Fixed in rev 3112.
