### ISSUE TITLE
NPC Pathing

### ISSUE THREAD

**Issue by Thugli** [Atlantiss/NetherwingBugtracker#622]
[//]: # (Enclose links to things related to the bug using http://wowhead.com or any other TBC database.)
[//]: # (You can use screenshot ingame to visual the issue.)
[//]: # (Write your tickets according to the format:)
[//]: # ([Quest][Azuremyst Isle] Red Snapper - Very Tasty!)
[//]: # ([NPC] Magistrix Erona)
[//]: # ([Spell][Mage] Fireball)
[//]: # ([Npc][Drop] Ghostclaw Lynx)
[//]: # ([Web] Armory doesnt work)

**Description**: 
NPC's seem to pause for several minutes after a player engages them, before they continue their pathing.  This is likely the same issue I was describing in #460

**Current behaviour**:
Here is a video of an example of what I am talking about:
https://clips.twitch.tv/ArborealMildLampDendiFace

**Expected behaviour**: 
NPC's should only pause for a brief moment (Roughly 10 seconds I beleive? Maybe a bit more) after a player exits the dialogue screen.

**Server Revision**: 
2060

**Comment by Easyfraggy** [comment]
This is intentional, if you have proof that it should be otherwise post it and reopen.
