### ISSUE TITLE
[Item][Core] T4 Justicar Armor 

### ISSUE THREAD

**Issue by unknown41** [Atlantiss/NetherwingBugtracker#6220]
[//]: # (Enclose links to things related to the bug using http://wowhead.com or any other TBC database.)
[//]: # (You can use screenshot ingame to visual the issue.)
[//]: # (Write your tickets according to the format:)
[//]: # ([Quest][Azuremyst Isle] Red Snapper - Very Tasty!)
[//]: # ([NPC] Magistrix Erona)
[//]: # ([Spell][Mage] Fireball)
[//]: # ([Npc][Drop] Ghostclaw Lynx)
[//]: # ([Web] Armory doesnt work)
[//]: # (To find server revision type `.server info` command in the game chat.)

**Description**: 
Protection Paladin T4 bonus:
(2) Set: Increases the damage dealt by your Seal of Righteousness, Seal of Vengeance, or Seal of Corruption by 10%.

**Current behaviour**:
The T4 Justicar Armor two piece bonus does not to work for Seal of Vengeance but works for Seal of Righteousness.
The dot damage is the same with and without - and the swing dmg if 5 stacks are applied is the same too.

**Expected behaviour**: 

**Server Revision**: 
23:47 AtlantissCoreTBC - Server Revision: 3106 [Branch: master, Hash: 7efcbcda604d]

**Comment by Wolffenstein** [comment]
Fixed in rev 3111.
