### ISSUE TITLE
[Spell][Ogri'la][Legion Flak Cannon] Fel Flak Fire either has incorrect tick rate or gets reapplied incorrectly

### ISSUE THREAD

**Issue by raethkcj** [Atlantiss/NetherwingBugtracker#6221]
[//]: # (Enclose links to things related to the bug using http://wowhead.com or any other TBC database.)
[//]: # (You can use screenshot ingame to visual the issue.)
[//]: # (Write your tickets according to the format:)
[//]: # ([Quest][Azuremyst Isle] Red Snapper - Very Tasty!)
[//]: # ([NPC] Magistrix Erona)
[//]: # ([Spell][Mage] Fireball)
[//]: # ([Npc][Drop] Ghostclaw Lynx)
[//]: # ([Web] Armory doesnt work)
[//]: # (To find server revision type `.server info` command in the game chat.)

**Description**: 
Getting hit by two clouds of Fel Flak Fire applies an insane amount of damage. My combat log shows "Fel Flak Fire was refreshed" twice, from flying through the two clouds. Somehow, though, either the debuff kept getting applied repeatedly after I fell out of the cloud, or the double stacks caused the tick rate to go through the roof. In my screenshots, I was hit by two clouds of Fel Flak Fire, and received 21 ticks of damage in less than 1.2 seconds.
![image](https://user-images.githubusercontent.com/7716908/63132345-6e62c380-bf86-11e9-8ee6-76591fa87d0f.png)
![image](https://user-images.githubusercontent.com/7716908/63131487-81c05f80-bf83-11e9-942a-15854a11a520.png)
![image](https://user-images.githubusercontent.com/7716908/63131871-d7493c00-bf84-11e9-9d75-b381be536d71.png)

This bug could be related to the Arcatraz Sentinels bug #4981, in that the spell appears to either get applied multiple times or it ticks MUCH faster than it should. 

**Current behaviour**:
Multiple stacks of Fel Flak Fire tick for 5% health every 0.05 seconds.

**Expected behaviour**: 
Multiple stacks of Fel Flak Fire tick for 5% hp per stack every 3 seconds.

**Server Revision**: 
3106

**Comment by Canderous** [comment]
Also, the cannons stop firing at you when you are on the ground on your flying mount (you can still throw the bombs then), which I believe is incorrect, as it completely trivializes the quest.

**Comment by raethkcj** [comment]
![image](https://user-images.githubusercontent.com/7716908/72310522-96df0e80-3647-11ea-8033-852a0dd5d69e.png)

**Comment by raethkcj** [comment]
21 ticks in less than a second

![image](https://user-images.githubusercontent.com/7716908/80043708-117dbc80-84c8-11ea-90f1-1246caddcd0c.png)

**Comment by Godmatik** [comment]
Unable to reproduce, potentially fixed at some point.
