### ISSUE TITLE
[Item][Buff] Kreeg's Stout Beatdown

### ISSUE THREAD

**Issue by lyubomeer** [Atlantiss/NetherwingBugtracker#6222]
[//]: # (Enclose links to things related to the bug using http://wowhead.com or any other TBC database.)
[//]: # (You can use screenshot ingame to visual the issue.)
[//]: # (Write your tickets according to the format:)
[//]: # ([Quest][Azuremyst Isle] Red Snapper - Very Tasty!)
[//]: # ([NPC] Magistrix Erona)
[//]: # ([Spell][Mage] Fireball)
[//]: # ([Npc][Drop] Ghostclaw Lynx)
[//]: # ([Web] Armory doesnt work)
[//]: # (To find server revision type `.server info` command in the game chat.)

**Description**: The [spirit buff](https://tbcdb.com/?spell=22790) from Dire Maul dispells with certain spells. 

**Current behaviour**:  [Buff](https://tbcdb.com/?spell=22790) from [Kreeg's Stout Beatdown](https://tbcdb.com/?item=18284) currently gets removed with Mage's Iceblock and Paladin's Blessing of Protection. 

**Expected behaviour**: Should not get dispelled.

**Server Revision**: 3106

**Comment by aplouding** [comment]
Bump. Still here. Tested on paladin and mage.

*Server revision:* 3701

**Comment by Godmatik** [comment]
Rev 4015
Still an issue

**Comment by Godmatik** [comment]
Rev 4015
No longer an issue - likely fixed with the new aura branch.
