### ISSUE TITLE
[NPC] [Spell] [Gurtogg Bloodboil] Mana pot/Mana Gem generates threat during Fel Rage/Insignificance.

### ISSUE THREAD

**Issue by Easyfraggy** [Atlantiss/NetherwingBugtracker#6223]
**Description**: 

Gurtogg Bloodboil 22948

**Current behaviour**:
Mana Potion/Mana Gem generates threat during Insignificance/Fel Rage.

We also tested Innervate but it seemed to work correctly (no threat).

**Expected behaviour**: 
Nothing generates threat during insignificance/Fel Rage.

**Server Revision**:

**Comment by Wolffenstein** [comment]
Fixed in rev 3111.
