### ISSUE TITLE
[Item]Mystical Skyfire Diamond

### ISSUE THREAD

**Issue by Aschevogel17** [Atlantiss/NetherwingBugtracker#6224]
**Description**: 
Item: https://www.wowhead.com/item=25893/mystical-skyfire-diamond
Mystical Skyfire Diamond appears to work as his 2.4.3 version. It should work another way at 2.2 server patch.

**Current behaviour**:
Gives 4 sec Focus buff on proc which gives +320 spell haste rating. Also gem has internal cd. So It works as it should be after 2.4.0 patch (according to https://wowwiki.fandom.com/wiki/Mystical_Skyfire_Diamond and https://wow.gamepedia.com/Mystical_Skyfire_Diamond)

**Expected behaviour**: 
As mentioned in links above at 2.2 patch Mystical Skyfire Diamond should work another way: 5% chance to proc --> gives you 10 sec Focus buff which halves casting times of your spells. Moreover gem shouldn't have internal cd before 2.3 patch.

2.1.0 patchnote: https://wowwiki.fandom.com/wiki/Patch_2.1.0
"Mystical Skyfire Diamond: The triggering rate on this item has been increased, but it now only reduces the cast time on spells by half; and Warlocks casting Corruption with maximum ranks in Improved Corruption will no longer consume the Focus buff from this gem."

2.2.0 patchnote: https://wow.gamepedia.com/Patch_2.2.0
"Increased the duration of the Mystical Skyfire Diamond’s cast speed buff to 10 seconds."

2.3.0 patchnote: https://wowwiki.fandom.com/wiki/Patch_2.3.0
"[Mystical Skyfire Diamond]: A cooldown has been added to this item's effect, but the chance for it to trigger has been increased."

**Server Revision**: 3106

**Comment by ircfelix** [comment]
If this gets fixed I want my lightning capacitor fixed, too.

**Comment by Aschevogel17** [comment]
But lighting capacitor works exactly as it should at 2.2 isn't it? 
I tested it with Arcane missiles: it gives charge for every crit (i mean in one AM sequence) and has 2,5 s cd only after lighting bolt release. Also it gives multiple charges from AoE criticals. Could you explain what is wrong with capacitor?

**Comment by ircfelix** [comment]
https://github.com/Atlantiss/NetherwingBugtracker/issues/3136

**Comment by Suzaru** [comment]
This. The gem is vital to arcane mages. It's not viable atm, hence severely damaging arcane mage spec. Are there plans to change that?

**Comment by Wolffenstein** [comment]
Will not be changed.
