### ISSUE TITLE
Shadowfiend doesn't scale it's hp with the casting priests hp

### ISSUE THREAD

**Issue by Esploye** [Atlantiss/NetherwingBugtracker#6225]
[//]: # (Enclose links to things related to the bug using http://wowhead.com or any other TBC database.)
[//]: # (You can use screenshot ingame to visual the issue.)
[//]: # (Write your tickets according to the format:)
[//]: # ([Quest][Azuremyst Isle] Red Snapper - Very Tasty!)
[//]: # ([NPC] Magistrix Erona)
[//]: # ([Spell][Mage] Fireball)
[//]: # ([Npc][Drop] Ghostclaw Lynx)
[//]: # ([Web] Armory doesnt work)
[//]: # (To find server revision type `.server info` command in the game chat.)

**Description**: Priest Shadowfiend spell it's not benefiting from the casting priest hp/mana when it is summoned

**Current behaviour**: when the shadowpriest summons the shadowfiend it starts with  1296hp and stays like that as its maximum hp.

**Expected behaviour**: when the shadowpriest summons the shadowfiend it should start with 1296/xxxx max hp and 1sec later it should go to (a higher than 1296) full hp.  The only thing i could not figure or find out is what is the exact formula for the amount of hp gain according to the priests health or stamina but it should have around at least 2-2,2k hp on a fully raid buffed priest

you can see it in videos like 

https://youtu.be/Fv_CJDCmGO8?t=321 at 5:21 summons shadowfiend starts with 1296/2328hp and 3155/5180 mana and 1 second later it goes to full hp and mana
at 7:33 same thing happens

https://youtu.be/veJZDANY6go?t=405 at 6:49 he summons shadowfiend and same behaviour happens with spawining at 1296hp and then jumping to a higher full hp

https://youtu.be/uhpexiXcFHw?t=271 at 4:36 in this one you can even see the shadowfiend has imp buff but shortly after it's summoned he loses the imp buff and still has more than 2k hp

**Server Revision**: 3106

**Comment by Esploye** [comment]
https://wowwiki.fandom.com/wiki/Shadowfiend proof that it should scale it's hp/mana from stamina/intelect 

 Patch 2.1.0 (22-May-2007): This pet will now come into the game with full health and mana, including that gained from a percentage of its master’s stamina and intellect.; The Shadowfiend will now correctly attack your target even if it is neutral or non-aggressive.; Increased the Shadowfiend’s chance to hit higher level enemies.

i don't think the exact amount is public so you will have to a guess on what % you do

**Comment by Wolffenstein** [comment]
Fixed in rev 3113.
