### ISSUE TITLE
[Dungeon][Blackrock Depths] Stuck in Combat Bug

### ISSUE THREAD

**Issue by DaedalusMachina007** [Atlantiss/NetherwingBugtracker#6226]
[//]: # (Enclose links to things related to the bug using http://wowhead.com or any other TBC database.)
[//]: # (You can use screenshot ingame to visual the issue.)
[//]: # (Write your tickets according to the format:)
[//]: # ([Quest][Azuremyst Isle] Red Snapper - Very Tasty!)
[//]: # ([NPC] Magistrix Erona)
[//]: # ([Spell][Mage] Fireball)
[//]: # ([Npc][Drop] Ghostclaw Lynx)
[//]: # ([Web] Armory doesnt work)
[//]: # (To find server revision type `.server info` command in the game chat.)

**Description**: Stuck in Combat in BlackRock Depths instance
Location: BlackRock Depths instance
Faction: Both

There's still issues with BlackRock Depths and the 'stuck in combat' bug for players there; may want to put in something into core to auto-release players from combat after ~30 seconds if no players in group receive or deal any damage to anything.

**Current behaviour**:  Certain bosses spawn bugged/invisible mobs and players are 'stuck in combat' unless they can Vanish (Rogue) Feign Death (Hunter) or die (everyone else).  Also happens in the 'Fire Spewing' room after killing a giant boss.

**Expected behaviour**:  Players should be automatically removed from combat if not taking/receiving any damage from any source for ~30 seconds.

**Server Revision**:  3106

**Comment by Drayo** [comment]
As always with combat bugs, the specific mob is needed for debugging. If this happens ask a GM to check which mob is causing it.

If that info is not available the report might as well be closed. 

Sometime after release a pretty huge combat bug regarding pets was fixed, so it might have been that.

**Comment by Godmatik** [comment]
Closing - all BRD information will be consolidated into one thread
