### ISSUE TITLE
[World][Inn] Rested Status Bug

### ISSUE THREAD

**Issue by DaedalusMachina007** [Atlantiss/NetherwingBugtracker#6227]
**Description**: No Rested Status in certain Inn Locations
Location: RevanTusk Village in Hinterlands Zone on Azeroth map
Faction: Horde

Hinterlands has a bug at the Horde inn on the east coast (RevanTusk Village) where the player is not 'rested' status when inside the Inn; only in very specific narrow portions of the Inn itself (including the upper level but not the lower level)

**Current behaviour**:  You only receive rested status if you stand in very specific tiny narrow portions of the lower Inn area (or on the upper level)

**Expected behaviour**:   Player should receive rested status anywhere in the Inn.

**Server Revision**: 3106

**Addendum**:  There's another inn in Terrokar (I believe) that someone said was bugged, not 100% on it but may be worthwhile to test on every inn in Azeroth & Outland.  Should take less than ~10 mins for any GM with instant teleporting.

**Comment by Wolffenstein** [comment]
Fixed in rev 3198.

**Comment by The14me** [comment]
Its bugged again.

**Comment by DaedalusMachina007** [comment]
Video not found :(

**Comment by Evolvee** [comment]
@The14me ?

**Comment by Godmatik** [comment]
Works fine... you need to be on the beds/cot to get rested status.

It's intended per posts from classic.
