### ISSUE TITLE
[Spell] [Paladin] Auras stacking

### ISSUE THREAD

**Issue by cuppycup12** [Atlantiss/NetherwingBugtracker#623]
[Spell][Paladin] Auras
Auras are able to be stacked. I can currently activate both devotion aura and retribution aura and receive benefits of both.

**Comment by cuppycup12** [comment]
[Spell][Paladin]
Auras are able to be stacked. I can currently activate both devotion aura and retribution aura and receive benefits of both.

**Comment by Wolffenstein** [comment]
Fixed in rev 2064.
