### ISSUE TITLE
[Item][Herb] Flame Cap Spawn

### ISSUE THREAD

**Issue by ImStiv** [Atlantiss/NetherwingBugtracker#6230]
[Item][Herb] Flame Cap

**Description:** 
Item: https://www.wowhead.com/object=181276/flame-cap

**Current behaviour:**
I assume Flame Cap is supposed to share spawn with other herbs and have a low spawn rate, but it's just absurd right now. I started playing the game 6 months ago, was able to buy 3 Flame Caps in the AH like 2 months ago and never seen it again.
Have tried gathering in Zangar for quite a few times (2h+ straight) without finding a single one. Have plenty of people on discord history saying they needed to wander around for EIGHT HOURS to find ONE.

**Expected behaviour:**
Have a higher/different spawn rate? The item is simply missing at the game right now.

**Server Revision:** 3106

EDIT: after some research i've found a post where it says Flame Cap should share spawn with Ragveil, so i collected all the Ragveil i cound find in Zangar flying in lines thru the whole map and waited for respawns. Zero Flame caps still. Wish I had more info to give on this but i can't seem to find much on google about it

EDIT2: Found a comment regarding drop rate [keep in mind this was made in a forum in 2011 so its not tbc based but i'd assume they didnt raise the drop rate 'tlil there 'cuz there is absolutly no mention on it whatsoever anywhere] -> "Considering Fire has received a nice boost, flame cap, this sweet herb will once again find themselves very useful. However farming these would be a pain. I was looking around in zangarmash for 30mins and found only 5-6 of them. Am I looking for them in the wrong places?"

EDIT3: This site says there were 29 spawn points (assuming they share spawn with other herbs, number should be considerably lower), as of patch 2.0.1
https://www.wow-freakz.com/item_finder.php?item=22788&name=flame-cap

**Comment by Easyfraggy** [comment]
Can confirm rate is absurd atm - On retail they were cheap on AH and relatively common.

**Comment by DaedalusMachina007** [comment]
Herbalist here; can confirm spawn/drop rate for this is absurdly skewed far too low; someone misplaced a decimal perhaps lol.  Also similar issues with Swiftthistle (used for Swiftness potions) and other '% chance of coming from a specific herb node' type of herbs.

**Comment by Evolvee** [comment]
The reason you think it doesnt spawn so often is because there are no hardspawns... It can only spawn as a replacement for other herb... For example: If you dont gather other herbs in the area, it has literally 0 chance to spawn.

**Comment by Evolvee** [comment]
I will increase the chance at which it can spawn instead of other herb in next revision.

**Comment by Evolvee** [comment]
When the revision takes the effect, please tell me how it changed because i literally doubled the chance...

**Comment by ImStiv** [comment]
Just did a test this morning:

Full Zangar clear: 15 Ragveil, 0 Flame caps
50min Break
Full Zangar clear: 13 Ragveil, 0 Flame caps
1 hour break
Full Zangar clear: 12 Ragveil, 0 Flame caps

@Evolvee doesn't seem to be working...

**Comment by Evolvee** [comment]
did you loot the ragveil?

**Comment by Evolvee** [comment]
its not live on the server yet

@Wolffenstein forgot to upload it

**Comment by ImStiv** [comment]
Did 3 full runs collecting all the ragveil on the way, no luck. Zero flame caps.

**Comment by Suzaru** [comment]
This is especially for fire mages quite important :(

**Comment by Evolvee** [comment]
there must be a core issue then ---> @Wolffenstein

**Comment by Wolffenstein** [comment]
Fixed in rev 3206.
