### ISSUE TITLE
[Core][Paladin] Mind Control and Divine Shield

### ISSUE THREAD

**Issue by veekk** [Atlantiss/NetherwingBugtracker#6231]
**Description**: In PvE MC can be dispelled when AI pressing bubble as MCed pala, but in this case character controlled by both mob AI and player: whole time by player but each "tick" of moving by MC AI timer character just running somewhere until hidden MC timer is gone.

**Expected behavior**: Didn't found any information related, but 1 of 2 options expected:
1. Bubble will not dispell MC
2. Bubble will dispell It completely

**Server Revision**: 3106

**Comment by DaedalusMachina007** [comment]
Paladin bubble removes Mind Control from any source (boss or enemy player) as removing all debuffs is part of what Divine Shield would do within TBC spell mechanics.

One common tactic in PvP was to MC a Paladin and immediately pop Avenging Wrath to prevent them from bubbling out of it since they'd get the Forbearance debuff.

**Comment by veekk** [comment]
in this case MC should be removed after AI popping bubble

**Comment by DaedalusMachina007** [comment]
So a major core mechanic of one of the primary classes in the game is ignored (for months) yet they took the time to make Consecration interrupt drinking.

Glad to know where dev priorities are at right now.

**Comment by Progressive335** [comment]
> So a major core mechanic of one of the primary classes in the game is ignored (for months) yet they took the time to make Consecration interrupt drinking.
> 
> Glad to know where dev priorities are at right now.

are these devs paid to bring a free source to you? if you want it fixed do it yourself.

**Comment by Godmatik** [comment]
Unable to reproduce.

The AI bubbled after I was MCed which broke the MC and I was able to control my own character just fine
