### ISSUE TITLE
[PvP] Feral s2 idol is missing (Merciless Gladiator's Idol of Resolve)

### ISSUE THREAD

**Issue by Macumbafeh** [Atlantiss/NetherwingBugtracker#6232]
**Description**:  
This Idol is missing at s2 vendor :
Merciless Gladiator's Idol of Resolve : Your Mangle ability also grants you 31 resilience rating for 6 sec.
https://www.thegeekcrusade-serveur.com/db/?item=33946

**Server Revision**: 3106

**Comment by Evolvee** [comment]
added
