### ISSUE TITLE
 Repeatable elites for Apexis Crystals bugged in Ogr'ila ( No option to summon for 35 Apexis shards)

### ISSUE THREAD

**Issue by Silentbabe** [Atlantiss/NetherwingBugtracker#6234]
[//]: # (Enclose links to things related to the bug using http://wowhead.com or any other TBC database.)
[//]: # (You can use screenshot ingame to visual the issue.)
[//]: # (Write your tickets according to the format:)
[//]: # ([Quest][Azuremyst Isle] Red Snapper - Very Tasty!)
[//]: # ([NPC] Magistrix Erona)
[//]: # ([Spell][Mage] Fireball)
[//]: # ([Npc][Drop] Ghostclaw Lynx)
[//]: # ([Web] Armory doesnt work)
[//]: # (To find server revision type `.server info` command in the game chat.)

**Description**: 

**Current behaviour**:  
 I can't summon elites, originally should be done by 35 Apexis shards and kill with party every day. But there is no such a option here . Only way to get it wait someone who never completed original quest and join party to kill . That way it's very hard to farm Apexis Crystals . 

**Expected behaviour**: 
Supposed to work with 35 Apexis Shards to summon elite demon daily to kill with party and after kill loot Apexis Crystal.. Working only  with first original quest. After quest is completed, there is no such a option again.
Similar to quest  The Relic's Amanation which is needed one shard to do puzzle game. It's repeatable every day. 

**Server Revision**:

**Comment by BishopXX** [comment]
I am facing the same issue. I see this bug was reported back in August. Is there any update on it?

**Comment by Godmatik** [comment]
Fixed a long time ago
