### ISSUE TITLE
Frozen Shadoweave not healing from Blizzard

### ISSUE THREAD

**Issue by hederob** [Atlantiss/NetherwingBugtracker#6235]
**Description**: 
The Frozen Shadoweave is providing no healing from doing damage with Blizzard.
**Current behaviour**:
While wearing this set, you receive 2% damage as healing from all other frost damage spells (Frostbolt, Cone of Cold, Frost nova) but not Blizzard.
**Expected behaviour**: 
Blizzard should heal the wearer of the 3/3 FSW set 2% of damage done.
**Server Revision**: 
2.2

**Comment by hederob** [comment]
old video evidence :) 

https://www.youtube.com/watch?v=beyRXulvycI

timestamp 2:20

**Comment by Wolffenstein** [comment]
Fixed in rev 3148.
