### ISSUE TITLE
[DMF][Quest]Sayge's Fortune Dungeon Quests not working

### ISSUE THREAD

**Issue by Manaci** [Atlantiss/NetherwingBugtracker#6236]
**Description**: 
Currently the special fortunes you can get from [Sayge](http://db.excalibur.ws/?npc=14822) has a chance to give you 4 special fortunes that acts as quest starter items. 2 of these quests are currently working (one requires you to click a tree stump and the other a haystack in Elwynn Forest)
The other 2 quests require you to venture into either Deadmines or Walling Caverns and click a special chest. The thing is, this chest will only spawn for the player who is on the specific quest and this is currently bugged and does not happen.

**Current behaviour**:
Going into Deadmines with this [quest](http://db.excalibur.ws/?quest=7938) or going into Walling Caverns with [this quest](http://db.excalibur.ws/?quest=7944) does not spawn a chest at the entrance = quest cannot be completed and Sayge won't give anymore fortunes since they're unique.

**Expected behaviour**: 
Going into Deadmines should spawn a [Mysterious Deadmines Chest](http://db.excalibur.ws/?object=180024) at the [entrance](https://wow.zamimg.com/uploads/screenshots/normal/163855-your-fortune-awaits-you-darkmoon-faire-quest-item-appears-after-walking-in-took-.jpg) of the dungeon. Same with the [Mysterious Wailing Caverns Chest](http://db.excalibur.ws/?object=180055), which should also spawn at the [entrance](https://www.wowhead.com/quest=7944/your-fortune-awaits-you#comments) of that dungeon.

**Server Revision**: 
3106

**Comment by Evolvee** [comment]
fixed in next rev

**Comment by Manaci** [comment]
@Evolvee No chest revealed in Deadmines after the new rev.

**Comment by Evolvee** [comment]
it will be in changelog when its pushed

**Comment by Manaci** [comment]
Sure thing, the Frostwhisper item was already fixed so wasn't sure.

**Comment by Evolvee** [comment]
rly? because the fix isnt live :D

**Comment by Manaci** [comment]
Inb4 it already worked but you needed to have the quest active for it to appear which I....may not have had when I checked a while ago.

**Comment by Manaci** [comment]
Hmm now I'm not sure if I had the Frostwhisper Fluid quest active when I couldn't loot one a while ago, you wrote about that negative value still though, not sure if it already worked WITH the quest active but it should still be dropping without as seen from [comments](https://www.wowhead.com/item=12736/frostwhispers-embalming-fluid#comments).

**Comment by Evolvee** [comment]
if the item is a "quest item" it should work with the negative value

anyway, after the fix it will work as well.. its just another way/method on how to make things work

**Comment by Evolvee** [comment]
well, if these items should drop even without quest, make a new issue for that pls and list all of them

**Comment by Manaci** [comment]
No problem, doesn't matter since they're useless outside of their quests anyways.

**Comment by Manaci** [comment]
The Deadmines chest is still not appearing :(

**Comment by Evolvee** [comment]
same as https://github.com/Atlantiss/NetherwingBugtracker/issues/6230#issuecomment-527192285

@Wolffenstein forgot to upload it
