### ISSUE TITLE
Shadowmeld passive improves stealth by more than it should.

### ISSUE THREAD

**Issue by ronyc** [Atlantiss/NetherwingBugtracker#6237]
**Description**:  Shadowmeld passive should provide just 1 level bonus to stealth.

**Current behaviour**: It's providing at least 5 stealth levels. I've never detected night elf rogue/druid in stealth without Paranoia(6 stealth levels detection)

**Expected behaviour**: Night elf druid/rogue should have 1 level bonus to stealth, no more.

**Server Revision**: 3106

**Comment by Evolvee** [comment]
where does it say it should add 1 "level"?

**Comment by DaedalusMachina007** [comment]
Tested this in-game by coordinating with a friend to get on their alliance druid alt and test this out; after doing tests on stealth and talents, the increase in stealth seems to be +5 or higher as the OP has posted.

**Comment by Wolffenstein** [comment]
Fixed in rev 3111.
