### ISSUE TITLE
[ITEM] Frostwhisper's Embalming Fluid is currently empty

### ISSUE THREAD

**Issue by Manaci** [Atlantiss/NetherwingBugtracker#6238]
**Description**: 
In Scholomance there is a [container](https://wow.zamimg.com/uploads/screenshots/normal/66599-frostwhispers-embalming-fluid.jpg) next to the Ras Frostwhisper boss, but it currently contains no item.

**Current behaviour**:
The [Frostwhisper's Embalming Fluid](http://db.excalibur.ws/?object=175965) container does currently not  contain the [Frostwhisper's Embalming Fluid](http://db.excalibur.ws/?item=12736) item.

**Expected behaviour**: 
The [Frostwhisper's Embalming Fluid](http://db.excalibur.ws/?object=175965) container should contain the [Frostwhisper's Embalming Fluid](http://db.excalibur.ws/?item=12736) item.

**Server Revision**: 
3106

**Comment by Evolvee** [comment]
Oh, its because it has "negative" value as a chance to drop, but the item itself isnt flagged as a quest item, so the core doesnt recognize the quest it is needed for... The fix is to put 100 and add a condition on the quest... or should it drop even without the quest?


Fixed in next rev

**Comment by Manaci** [comment]
Think it should drop without the quest but it has no use outside of the quest so /shrug.
