### ISSUE TITLE
Mage in Cat form after login

### ISSUE THREAD

**Issue by hirotaro1** [Atlantiss/NetherwingBugtracker#6241]
[//]: # (Enclose links to things related to the bug using http://wowhead.com or any other TBC database.)
[//]: # (You can use screenshot ingame to visual the issue.)
[//]: # (Write your tickets according to the format:)
[//]: # ([Quest][Azuremyst Isle] Red Snapper - Very Tasty!)
[//]: # ([NPC] Magistrix Erona)
[//]: # ([Spell][Mage] Fireball)
[//]: # ([Npc][Drop] Ghostclaw Lynx)
[//]: # ([Web] Armory doesnt work)
[//]: # (To find server revision type `.server info` command in the game chat.)

**Description**: 

**Current behaviour**:

**Expected behaviour**: 

**Server Revision**:

**Comment by hirotaro1** [comment]
Description: Upon login on a lvl 7 Gnome Mage I was somehow in the druid's cat form. The buff was present and when I cancel it the "attack" skill icon shows that of the cat form.

Current behaviour: Login after I cancel the buff is fine.

Expected behaviour: to not be a cat when logging into the mage

![WoWScrnShot_082419_223528](https://user-images.githubusercontent.com/54483604/63642017-c2755280-c6c0-11e9-88f9-824e811d47ce.jpg)
![WoWScrnShot_082419_224238](https://user-images.githubusercontent.com/54483604/63642018-c2755280-c6c0-11e9-8cc1-7f44c1169924.jpg)

**Comment by Wolffenstein** [comment]
Fixed
