### ISSUE TITLE
Bug in the Sunken Temple the boss Atal'alarion 

### ISSUE THREAD

**Issue by Dellearch** [Atlantiss/NetherwingBugtracker#6242]
First of all, thank you very much for giving me and my friends the opportunity to relive the good TBC days!

Yesterday, my fellows and i took a sweet run through the mysterius Sunken Temple. 
Unfortunately we saw a bug at one of the bosses (Atal'Alarion), which dropped good items :).

The boss has a mechanic that allows you to be thrown into the air, but at the same time it charges you. As a result, the boss remained in the air - the boss was stucked and we had no chance to loot it... Link to the image can be found at the bottom :). 

Hope you can fix the bug, and maybe have time for a small reward :D.

thanks in advance, 

Dellearch!

![Bug in ST](https://user-images.githubusercontent.com/54484654/63642621-35cb9400-c6c2-11e9-8ca4-87ca505844e5.png)

**Comment by Evolvee** [comment]
https://github.com/Atlantiss/NetherwingBugtracker/issues/1789
