### ISSUE TITLE
[Buff][Item] Mr. Pinchy's Blessing is not counted as a Flask. 

### ISSUE THREAD

**Issue by Kolmarwow** [Atlantiss/NetherwingBugtracker#6245]
**Description**: 
[Mr. Pinchy](https://tbcdb.com/?item=27388) is an item that you have a chance to get from fishing Highland Mixed Schools in Terokkar Forest.

It has 3 charges and gives you random effects when you use it, one of these effects is called [Mr Pinchy's Blessing](https://tbcdb.com/?spell=33053) which is a flask-effect that gives you 500 health for 2 hours and persists through death.

It correctly persists through death but it is not counted as a "Flask" in terms of the Battle/Guardian elixir system, so you can stack Mr. Pinchy's Blessing with another flask such as Flask of Fortification to get 1000 health for 2 hours. 

**Server Revision**: 
3109

**Comment by Wolffenstein** [comment]
Fixed in rev 3360.
