### ISSUE TITLE
[Raid] No loot on Solarian kill

### ISSUE THREAD

**Issue by Silun** [Atlantiss/NetherwingBugtracker#6246]
**Description**: "in Harmony" killed Solarian on 25.08. and the boss only dropped gold, no loot. I was told by a GM to post this here. Please give us loot.

**Current behaviour**: Boss dropped no loot on kill.

**Expected behaviour**:  Boss drops loot on kill.

**Server Revision**: 3109

Proof of kill:
https://www.twitch.tv/videos/472239292
Starting at ~1:19:30 you can see us fight, the caster releases spirit, and when he returns the gates are open, which means Solarian was killed. So this should prove that we killed him, and in our chats and in your server logs you'll see we had no loot.

**Comment by Evolvee** [comment]
post this to Daystar throught discord PM please

**Comment by danbopes** [comment]
Please ensure the MasterLooter is the one who DM's Daystar.
