### ISSUE TITLE
[Quest] Gyrodrillmatic Excavationators

### ISSUE THREAD

**Issue by T0mken** [Atlantiss/NetherwingBugtracker#6247]
[//]: # (Enclose links to things related to the bug using http://wowhead.com or any other TBC database.)
[//]: # (You can use screenshot ingame to visual the issue.)
[//]: # (Write your tickets according to the format:)
[//]: # ([Quest][Azuremyst Isle] Red Snapper - Very Tasty!)
[//]: # ([NPC] Magistrix Erona)
[//]: # ([Spell][Mage] Fireball)
[//]: # ([Npc][Drop] Ghostclaw Lynx)
[//]: # ([Web] Armory doesnt work)
[//]: # (To find server revision type `.server info` command in the game chat.)

**Description**: 
Cannot deliver the completed quest. https://i.imgur.com/qcICbGV.png
**Current behaviour**:
Quest is completed, but can't deliver.
**Expected behaviour**: 
Deliver the quest, get my reward and shout at Drain.
**Server Revision**: 
🤔

**Comment by Evolvee** [comment]
disable all addons, delete cache and try again

**Comment by T0mken** [comment]
> disable all addons, delete cache and try again

Now I can't even talk to the NPC lol

**Comment by Evolvee** [comment]
contact me on discord pls, i will check ingame when you get online
