### ISSUE TITLE
Curse of Exhaustion

### ISSUE THREAD

**Issue by liderer** [Atlantiss/NetherwingBugtracker#6248]
The Problem: Curse of Exhaustion should be an exception to the slow/debuff stacking ruleset.
https://youtu.be/rynmsLe_OV8

How it should work: Curse of Exhaustion should be an exception to the slow/debuff stacking ruleset.
For whatever reason it was always an exception on retail. The slow effect shouldn't "stack", as in increasing slow, but rather just allow both CoE & another slow debuff to be present at the same time.

Proof: 
https://youtu.be/t8iiLNszJpU?t=3m
Neilyo gets crippled while having Curse of Exhaustion on him, only to first have abolish poison remove crippling, then to remove CoE with improved sprint right after.

https://www.youtube.com/watch?v=-5Avkf8iM44&feature=youtu.be&t=520
Hunter is hamstringed, then gets Curse of Exhaustion casted on him.

**Comment by Evolvee** [comment]
@Wolffenstein 
![image](https://user-images.githubusercontent.com/1942409/63686775-0e301500-c803-11e9-87d6-da513f1e69d9.png)

![image](https://user-images.githubusercontent.com/1942409/63686793-22741200-c803-11e9-9694-8b53742ead5e.png)

**Comment by Wolffenstein** [comment]
Fixed in rev 3111.
