### ISSUE TITLE
[Quest] Quell the Silverwing Usurpers

### ISSUE THREAD

**Issue by veekk** [Atlantiss/NetherwingBugtracker#6249]
**Description**: [Quell the Silverwing Usurpers](https://classic.wowhead.com/quest=7789/quell-the-silverwing-usurpers) not in-game for some reasons

**Current behaviour**:[Quell the Silverwing Usurpers](https://classic.wowhead.com/quest=7789/quell-the-silverwing-usurpers)  isn't available

**Expected behaviour**:  should be

**Server Revision**: 3106

**Comment by lyubomeer** [comment]
![image](https://user-images.githubusercontent.com/11522170/63818736-1a26ee80-c94b-11e9-8742-52d38d50a288.png)
