### ISSUE TITLE
[Rogue][Spell] Slice and Dice Rank 1

### ISSUE THREAD

**Issue by deku100** [Atlantiss/NetherwingBugtracker#625]
[//]: # (Enclose links to things related to the bug using http://wowhead.com or any other TBC database.)
[//]: # (You can use screenshot ingame to visual the issue.)
[//]: # (Write your tickets according to the format:)
[//]: # ([Quest][Azuremyst Isle] Red Snapper - Very Tasty!)
[//]: # ([NPC] Magistrix Erona)
[//]: # ([Spell][Mage] Fireball)
[//]: # ([Npc][Drop] Ghostclaw Lynx)
[//]: # ([Web] Armory doesnt work)

**Description**: Slice and Dice does not work properly

**Current behaviour**: Slice and Dice (Rank 1) only gives a 5 sec buff regardless of how many combo points are put toward it.

**Expected behaviour**:  Slice and Dice should give a buff whose length corresponds with the number of combo points put toward it.

**Server Revision**:

**Comment by Wolffenstein** [comment]
Fixed in rev 2067.
