### ISSUE TITLE
Seal of the Crusader

### ISSUE THREAD

**Issue by Arisatheus** [Atlantiss/NetherwingBugtracker#6250]
[//]: # (Enclose links to things related to the bug using http://wowhead.com or any other TBC database.)
[//]: # (You can use screenshot ingame to visual the issue.)
[//]: # (Write your tickets according to the format:)
[//]: # ([Quest][Azuremyst Isle] Red Snapper - Very Tasty!)
[//]: # ([NPC] Magistrix Erona)
[//]: # ([Spell][Mage] Fireball)
[//]: # ([Npc][Drop] Ghostclaw Lynx)
[//]: # ([Web] Armory doesnt work)
[//]: # (To find server revision type `.server info` command in the game chat.)

**Description**: 

The skill gives X amount of attack power to the Paladin and makes his/her attack speed %40 faster, but Paladin's damage reduces after each attack.

**Current behaviour**:

On current behaviour of the skill, Paladin does not get increased attack, instead his/her the moment he/she uses the skill, he starts attacking with the lowest attack damage the seal can reduce, which is around %50

**Expected behaviour**: 

After using Seal of the Crusader, Paladin should be doing increased attack damage with first 2 attacks, after that he starts doing lower than his usual attack damage with each hit, so we can accept the skill as increasing the damage by %20 and droping %10 attack power after each strike up to %50.

**Server Revision**:

**Comment by Tereneckla** [comment]
You are the first person ever to say it should work like this, congratulations.

**Comment by ghost** [comment]
How this is archived, the dude just read what the spell says
https://tbcdb.com/?spell=21082
This should be fixed asap, it's incredible that using [Seal of the Crusader] reduces all your damage by half.
Is this an intentionally nerf?

**Comment by Tereneckla** [comment]
It says "deals less damage with each attack"
The buff says "deal less damage"

At no point there is a mention that the first attacks should deal more damage in the spell or buff or anywhere else in the internet
