### ISSUE TITLE
Elemental Plateau Pure Waters

### ISSUE THREAD

**Issue by Arisatheus** [Atlantiss/NetherwingBugtracker#6251]
[//]: # (Enclose links to things related to the bug using http://wowhead.com or any other TBC database.)
[//]: # (You can use screenshot ingame to visual the issue.)
[//]: # (Write your tickets according to the format:)
[//]: # ([Quest][Azuremyst Isle] Red Snapper - Very Tasty!)
[//]: # ([NPC] Magistrix Erona)
[//]: # ([Spell][Mage] Fireball)
[//]: # ([Npc][Drop] Ghostclaw Lynx)
[//]: # ([Web] Armory doesnt work)
[//]: # (To find server revision type `.server info` command in the game chat.)

**Description**: 
the issue is about respawn times ofr Pure Waters in the mentioned area.

**Current behaviour**:
The Pure Waters in Elemental Plateau seems to have respawning like once a day, thats how long the respawn timer is.

**Expected behaviour**: 
The Respawn Time of the Pure Waters should be random between 5 to 10 minute.
**Server Revision**:

**Comment by Evolvee** [comment]
its 1 hour
