### ISSUE TITLE
Mote drop rate

### ISSUE THREAD

**Issue by notaslave** [Atlantiss/NetherwingBugtracker#6252]
After digging through every patch note and undocumented changes from 2.0.1 to 3.0.1 there have not been any changes made to increase or lower the drop rate of motes.
**Description**: 
All motes appear to have lower drop rates than what they should be by quite a bit when dropped by mobs. [https://www.wowhead.com/item=22574/mote-of-fire](url) [https://tbcdb.com/?item=22574](url) For example only has a 24% drop rate on some mobs here.
**Current behaviour**:
Every motes drop rate is lower than it should be.
**Expected behaviour**: 
Most (not all) mobs which drop motes should have 33% drop rates of 1-2 motes

**Comment by Evolvee** [comment]
![image](https://user-images.githubusercontent.com/1942409/63944666-46895a80-ca72-11e9-96ee-03d0472d527e.png)

no it doesnt have 24% drop rate

**Comment by Evolvee** [comment]
If you think a certain mob has incorrect drop rate, report it separately. "All motes have low drop" will not get us anywhere as it has basically 0 info that could be helful to us --> no example, no evidence, no resource on how it should be etc.
