### ISSUE TITLE
Hyjal Trash Loot Table

### ISSUE THREAD

**Issue by astraeah** [Atlantiss/NetherwingBugtracker#6253]
[//]: # ([Npc][Drop] Hyjal Trash)

**Description**: 
Hyjal trash only seems to drop a select few items; in 4 weeks of continuous raiding, I have only seen Fist of Molten Fury, Pepe's Shroud of Pacification, and Hammer of Judgement. This is out of a table of 9 items. Fist of Molten Fury drops the most, 
**Current behaviour**:
Trash loot table seems to be tuned wrong in Hyjal. Fist of Molten fury constantly drops, but other items rarely drop or never drop.
**Expected behaviour**: 
Various items should drop in Hyjal.
**Server Revision**: 
Loot tables need adjusted.

**Comment by Evolvee** [comment]
@Easyfraggy

**Comment by veekk** [comment]
can confirm, got like 12 both oh/mh fists and 4 hammer from lot of runs neutral -> exalted

**Comment by Evolvee** [comment]
you realize patch 2.2. had only small amount of items that droped from hyjal right?

**Comment by Evolvee** [comment]
@Easyfraggy

**Comment by Easyfraggy** [comment]
Okay so heres the rundown.

Patch 2.1 

Nothing drops in Hyjal not even gold/Marks/HoD. 0 loot and reputation from the trash. Bosses give more rep per kill

Black temple drops all of the above and these following epics:

32593/treads-of-the-den-mother
32943/swiftsteel-bludgeon
32606/girdle-of-the-lightbearer
32608/pillagers-gauntlets
32609/boots-of-the-divine-light
32590/nethervoid-cloak
32592/chestguard-of-relentless-storms
32526/band-of-devastation
32527/ring-of-ancient-knowledge
32528/blessed-band-of-karabor
32589/hellfire-encased-pendant
32591/choker-of-serrated-blades
34012/shroud-of-the-final-stand

Patch 2.2

Hyjal trash starts dropping items, gold/Marks/HoD and these epics:

34009/hammer-of-judgment
32609/boots-of-the-divine-light
32592/chestguard-of-relentless-storms
32590/nethervoid-cloak
34010/pepes-shroud-of-pacification
32591/choker-of-serrated-blades
32589/hellfire-encased-pendant

Black Temple gets this item added to the drop table:

34009/hammer-of-judgment

Patch 2.3 

This item is added to Black Temple Trash
34011/illidari-runeshield

Patch 2.4 

These two items are added to the Hyjal trash loot:
32946/claw-of-molten-fury
32945/fist-of-molten-fury


Note all mobs in both BT (patch 2.1) and Hyjal (from 2.2) should be able to drop world drops as in outland lvl 70 greens/blues/epics.

**Comment by Suzaru** [comment]
BTW. we never saw 34009/hammer-of-judgment again since months. We clear Hyjal every week and nothing. Highly suspect something is off with the drop rate.

**Comment by Easyfraggy** [comment]
We had it last week from hyjal @Suzaru

**Comment by Evolvee** [comment]
![image](https://user-images.githubusercontent.com/1942409/71307941-251ff600-23f6-11ea-82f5-e57b749eeaa7.png)

so when does it start getting reputation for kill?

**Comment by Evolvee** [comment]
make some proper report ffs -.-

**Comment by Easyfraggy** [comment]
in 2.2

**Comment by Godmatik** [comment]
When T6 is released, the patch is always skipping straight to 2.2, so this information no longer relevant.

Closing.
