### ISSUE TITLE
Skullflame Shield proc not working

### ISSUE THREAD

**Issue by astraeah** [Atlantiss/NetherwingBugtracker#6256]
[//]: # ([Item] Skullflame Shield) https://tbc-twinhead.twinstar.cz/?item=1168

**Current behaviour**:
I've received reports from multiple players that Skullflame Shield's proc isn't firing off. 

**Expected behaviour**: 
Skullflame shield should proc both a lifesteal and an aoe fire damage that scale off of spell damage at a 1 to 1 ratio.

**Server Revision**: 
3109

**Comment by ircfelix** [comment]
check your damage meters for flamestrike and drain life and provide sources for your claim.
