### ISSUE TITLE
Beast Lore HP Bug.

### ISSUE THREAD

**Issue by ShaneDoyle** [Atlantiss/NetherwingBugtracker#6259]
[//]: # (Enclose links to things related to the bug using http://wowhead.com or any other TBC database.)
[//]: # (You can use screenshot ingame to visual the issue.)
[//]: # (Write your tickets according to the format:)
[//]: # ([Quest][Azuremyst Isle] Red Snapper - Very Tasty!)
[//]: # ([NPC] Magistrix Erona)
[//]: # ([Spell][Mage] Fireball)
[//]: # ([Npc][Drop] Ghostclaw Lynx)
[//]: # ([Web] Armory doesnt work)
[//]: # (To find server revision type `.server info` command in the game chat.)

**Description**: Using Beast Lore on a beast glitches out the NPC's HP.

**Current behaviour**: When using Beast Lore on a beast, HP will always display as 100%. 

**Expected behaviour**: Using Beast Lore on a beast shouldn't alter the % displayed on a beast.

**Server Revision**: 3116

Beast before using Beast Lore (Correct):
![WoWScrnShot_090319_185647](https://user-images.githubusercontent.com/17293385/64197000-f00a8a80-ce7c-11e9-82db-371ca7e8f1c2.jpg)

Beast after using Beast Lore (Bugged):
![WoWScrnShot_090319_185655](https://user-images.githubusercontent.com/17293385/64197002-f00a8a80-ce7c-11e9-9a90-65858c6e724e.jpg)

As seen in the screenshots, using Beast Lore on an NPC will cause HP% to be stuck at 100%.

**Comment by Wolffenstein** [comment]
Fixed in rev 3198.
