### ISSUE TITLE
[NPC][Blade's Edge Mountains] Bloodmaul Skirmishers and Gemoancers

### ISSUE THREAD

**Issue by Exorcista** [Atlantiss/NetherwingBugtracker#6261]
NPC LINK: https://www.wowhead.com/npc=19948/bloodmaul-skirmisher
And:
https://es.wowhead.com/npc=19952/bloodmaul-geomancer

Both should have a dymanic spawn between them. Meaning if you kill one there's a chance that on spawn one of the other might come up instead.

This is explained better in this ownedcore post from 2007:
https://www.ownedcore.com/forums/world-of-warcraft/world-of-warcraft-guides/20145-how-farm-enchant-bracer-spellpower.html

**Current behaviour**:
Once you kill the entire population of skirmishers no Geomancers ever show up in it's place, I did 2 rounds of killing them all and only the 8 Geomancers arround are the only ones that keep popping up every 10min.
**Expected behaviour**: 
Should have the respawn fixed so Geomancers show up (with a chance ofc) when you kill skirmishers.

**Comment by Evolvee** [comment]
fixed in rev 3121
