### ISSUE TITLE
Gnomish Battle Chicken Level Bug

### ISSUE THREAD

**Issue by ShaneDoyle** [Atlantiss/NetherwingBugtracker#6265]
[//]: # (Enclose links to things related to the bug using http://wowhead.com or any other TBC database.)
[//]: # (You can use screenshot ingame to visual the issue.)
[//]: # (Write your tickets according to the format:)
[//]: # ([Quest][Azuremyst Isle] Red Snapper - Very Tasty!)
[//]: # ([NPC] Magistrix Erona)
[//]: # ([Spell][Mage] Fireball)
[//]: # ([Npc][Drop] Ghostclaw Lynx)
[//]: # ([Web] Armory doesnt work)
[//]: # (To find server revision type `.server info` command in the game chat.)

**Description**: When summoning the Gnomish Battle Chicken, the level of the chicken is stuck at level 1, rather than scaling with the player's engineering level.
See: https://wowwiki.fandom.com/wiki/Gnomish_Battle_Chicken

**Current behaviour**: Spawns the Gnomish Battle Chicken at level 1.

**Expected behaviour**: The Gnomish Battle Chicken's level should scale with the player's engineering level.

**Server Revision**: 3119

**Screenshot**:
![image](https://user-images.githubusercontent.com/17293385/64481092-e8c0e500-d1cc-11e9-957d-0447b6be7f63.png)

**Comment by The14me** [comment]
rev. 3460 there is no ever a chicken when i click on the item to  summ.

**Comment by Godmatik** [comment]
Resolved, can close

**Comment by EtheriousNW** [comment]
Fixed a while back.
