### ISSUE TITLE
[raid][black temple]Reliquary of souls trash keeps you in combat at safe spot

### ISSUE THREAD

**Issue by ircfelix** [Atlantiss/NetherwingBugtracker#6266]
**Description**: 
Before fighting RoS, you need to kill some trash mob ghosts and you can go to a safe spot at the ramp between the boss and the adds.

**Current behaviour**:
After killing the trash mobs and hugging closely at the safe spot, some players stay in combat without new adds or the boss being pulled.

**Expected behaviour**: 
After killing the trash mobs and hugging closely at the safe spot, nobody should stay in combat without new adds or the boss being pulled.

**Server Revision**: 
3119

**Comment by Easyfraggy** [comment]
It happens if you leave totems behind that agro some of the invisible angered spirits and they can't find a path to you because you already moved on.
