### ISSUE TITLE
[NPC] Thrall shows the dialogue options of the last npc you talked to.

### ISSUE THREAD

**Issue by Tereneckla** [Atlantiss/NetherwingBugtracker#6267]
[//]: # (Enclose links to things related to the bug using http://wowhead.com or any other TBC database.)
[//]: # (You can use screenshot ingame to visual the issue.)
[//]: # (Write your tickets according to the format:)
[//]: # ([Quest][Azuremyst Isle] Red Snapper - Very Tasty!)
[//]: # ([NPC] Magistrix Erona)
[//]: # ([Spell][Mage] Fireball)
[//]: # ([Npc][Drop] Ghostclaw Lynx)
[//]: # ([Web] Armory doesnt work)
[//]: # (To find server revision type `.server info` command in the game chat.)

**Description**: 
![image](https://user-images.githubusercontent.com/50233983/64485934-da9fb280-d226-11e9-96e1-1aa33971f613.png)

**Current behaviour**:

**Expected behaviour**: 

**Server Revision**: 3119

**Comment by Evolvee** [comment]
its just shit cpp

**Comment by Wolffenstein** [comment]
Fixed in rev 3226.
