### ISSUE TITLE
[Raid] Can't use targeted abilites in  chess event.

### ISSUE THREAD

**Issue by Tereneckla** [Atlantiss/NetherwingBugtracker#6268]
[//]: # (Enclose links to things related to the bug using http://wowhead.com or any other TBC database.)
[//]: # (You can use screenshot ingame to visual the issue.)
[//]: # (Write your tickets according to the format:)
[//]: # ([Quest][Azuremyst Isle] Red Snapper - Very Tasty!)
[//]: # ([NPC] Magistrix Erona)
[//]: # ([Spell][Mage] Fireball)
[//]: # ([Npc][Drop] Ghostclaw Lynx)
[//]: # ([Web] Armory doesnt work)
[//]: # (To find server revision type `.server info` command in the game chat.)

**Description**: 

**Current behaviour**:

**Expected behaviour**: 

**Server Revision**: 3119

**Comment by Wolffenstein** [comment]
?

**Comment by Easyfraggy** [comment]
Sounds like a UI issue or just a you issue =) Likely invalid.

**Comment by hederob** [comment]
can confirm, it's been like this for 3 weeks for myself and my guildees.

**Comment by hederob** [comment]
problems with moving the chess pieces as well

**Comment by Wolffenstein** [comment]
Fixed in rev 3138.
