### ISSUE TITLE
Rogue disarm trap

### ISSUE THREAD

**Issue by Speank** [Atlantiss/NetherwingBugtracker#6269]
[//]: # (Enclose links to things related to the bug using http://wowhead.com or any other TBC database.)
[//]: # (You can use screenshot ingame to visual the issue.)
[//]: # (Write your tickets according to the format:)
[//]: # ([Quest][Azuremyst Isle] Red Snapper - Very Tasty!)
[//]: # ([NPC] Magistrix Erona)
[//]: # ([Spell][Mage] Fireball)
[//]: # ([Npc][Drop] Ghostclaw Lynx)
[//]: # ([Web] Armory doesnt work)
[//]: # (To find server revision type `.server info` command in the game chat.)

**Description**: Disarm trap not working as it should.

**Current behaviour**: Taking any damage from anything will cancel the disarm trap cast.

**Expected behaviour**: Taking any damage from anything should only push back the cast.
https://youtu.be/n5XVuHIpucE?t=751

**Server Revision**:

**Comment by Wolffenstein** [comment]
Was fixed in 3202.
