### ISSUE TITLE
[NPC] Horde Scout

### ISSUE THREAD

**Issue by mbzz88** [Atlantiss/NetherwingBugtracker#627]
**Description**:  "Horde Scout" uses Dark Iron mob emotes http://db.hellfire-tbc.com/?npc=11680

**Current behaviour**: Never cross a Dark Iron, Class.
![wowscrnshot_092618_140603](https://user-images.githubusercontent.com/43509267/46055433-0eadcf00-c1a0-11e8-97cc-38c8d9895f4f.jpg)

**Expected behaviour**:  Not sure what they are meant to say

**Comment by Sinyr** [comment]
Can confirm
![screenshot_19](https://user-images.githubusercontent.com/9539181/46262773-2cfc2d80-c506-11e8-8ee8-160c8b57a83c.png)

**Comment by Evolvee** [comment]
rev Xd
