### ISSUE TITLE
Herbalism -- 90% Ressources nodes missing 

### ISSUE THREAD

**Issue by Initic** [Atlantiss/NetherwingBugtracker#6270]
**Description**: 

Ressources nodes 

**Current behaviour**:
80% of ressources nodes are missing in herbalism

**Expected behaviour**: 
One image of the wowhead database on the map of barrens
https://ibb.co/pnj9TP8

**Server Revision**: 
3119

**Comment by Evolvee** [comment]
its not supposed to be spawned all at the same time
