### ISSUE TITLE
[Spell][Hunter] Eagle Eye

### ISSUE THREAD

**Issue by BDweller** [Atlantiss/NetherwingBugtracker#6271]
[//]: # (Enclose links to things related to the bug using http://wowhead.com or any other TBC database.)
[//]: # (You can use screenshot ingame to visual the issue.)
[//]: # (Write your tickets according to the format:)
[//]: # ([Quest][Azuremyst Isle] Red Snapper - Very Tasty!)
[//]: # ([NPC] Magistrix Erona)
[//]: # ([Spell][Mage] Fireball)
[//]: # ([Npc][Drop] Ghostclaw Lynx)
[//]: # ([Web] Armory doesnt work)
[//]: # (To find server revision type `.server info` command in the game chat.)

**Description**:  Eagle eye is behaving weirdly and can't be chained.

**Current behaviour**: Your vision of the area, even if cast overlapping with your current point of view, takes a "snapshot" of players which shows them immobile. For example, casting eagle eye while a player is moving in town will show them static, likely running in place and when they take a taxi their model will update to show them mounted, still in place.
The chaining behavior lets you cast the ability from one viewpoint to another , but it won't load  NPCs or players past the first cast(possibly missing other stuff too) nor does it carry the tracking with each new jump.

**Expected behaviour**: Eagle Eye lets you see a remote area you target and allows your tracking to carry over to this new point of view. Additionally, If cast with the ignore toggle modifier "/cast !Eagle Eye" ,the spell allows to chain itself  like the shaman version to travel around. Only usable outside.

[gamepedia link](https://wow.gamepedia.com/Eagle_Eye)

**Server Revision**: 3119

**Comment by Wolffenstein** [comment]
Fixed in rev 3167.
