### ISSUE TITLE
[Shadowmoon Valley][NPC] Akama Demon drop fps to like zero

### ISSUE THREAD

**Issue by veekk** [Atlantiss/NetherwingBugtracker#6272]
**Description**: When Akama summon vision of demon by script this fire dropping fps to like zero

**Server Revision**: 3113

**Comment by ircfelix** [comment]
lower spell detail

**Comment by veekk** [comment]
100 fps -> 5fps seems like not hardware problem, also was mentioned by another players
my config is: i7, 16gb ram, amd radeon m370x 2gb, pretty sure that's not hardware problem
