### ISSUE TITLE
Amani'shi Flame Caster Mind Control abilities

### ISSUE THREAD

**Issue by EtheriousNW** [Atlantiss/NetherwingBugtracker#6273]
**Current behaviour**: When mind controlled the priest can only auto attack

**Expected behaviour**: Should be able to use the mob's abilties as per wowhead comments https://www.wowhead.com/npc=23596/amanishi-flame-caster#comments 
**Server Revision**: PTR pre-release

**Comment by Evolvee** [comment]
fixed in next rev
