### ISSUE TITLE
"You cannot equip more than one of those"

### ISSUE THREAD

**Issue by tande308** [Atlantiss/NetherwingBugtracker#6274]
I got the Gronn-Stitched Girdle from Gruuls yesterday. I tried equipping it today but I would keep getting the notice saying "You cannot equip more than one of those". Confused I removed all my gear and put pieces on 1 at a time. For some reason I cannot wear my Warbringer Shouulderplates and Gronn-Stitched Girdle at the same time. I tried deleting my WTF folder and that didn't fix the problem either. Talked to a Game master and he told me to post on the Support forums. Any help would greatly be appreciated. My Character is named Strongheart on Alliance Side thank you

**Comment by danbopes** [comment]
Why did you close this?
