### ISSUE TITLE
[Item][Trinket] - Shared cooldown 

### ISSUE THREAD

**Issue by HyperAzur** [Atlantiss/NetherwingBugtracker#6275]
**Description**: Both trinkets are on a 1:30m cd and once one is popped the other one is put on the same cd as the first one
trinket1: [https://db.excalibur.ws/?item=31615](https://db.excalibur.ws/?item=31615)
trinket2: [https://db.excalibur.ws/?item=28040](https://db.excalibur.ws/?item=28040)

**Current behaviour**: Trinkets share a hidden cd of 1:30m even if is not showed. [https://youtu.be/mzjJdPu8SzI](https://youtu.be/mzjJdPu8SzI)

**Expected behaviour**: The 2nd trinket should work after the cd ends after the 1st one is popped
 *(it was working in the last revision)*

**Server Revision**: 3123

**Comment by hederob** [comment]
trinkets with a similar on use effect usually share cooldowns with one another.

**Comment by HyperAzur** [comment]
Well is a bit weird that it used to work.
