### ISSUE TITLE
[Spell][Warrior] Intervene

### ISSUE THREAD

**Issue by GitHubTheySaid** [Atlantiss/NetherwingBugtracker#6277]
Description: Run at high speed towards a party member, intercepting the next melee or ranged attack made against them.
Expectation is to be able to intervene on my party's shaman totems...

Current behavior: It describes the totems as invalid target.

Expected behavior: Totems are considered just as hunter pets, of the party's members. 
Intervene should work on targeted totems of your party's shaman.

Server Revision: 3128

**Comment by Evolvee** [comment]
Any proof?

**Comment by Easyfraggy** [comment]
Pretty sure I was intervening totems on Magtheridon just fine - I'll test it next raid. But yes you should definitely be able to interven totems.

**Comment by GitHubTheySaid** [comment]
https://www.youtube.com/watch?v=B3z3DEDOXXQ&feature=youtu.be

Video inside instance(Maghteridon's lair as e.i.) and outside world.

**Comment by Evolvee** [comment]
its deleted/private

**Comment by GitHubTheySaid** [comment]
Its set public now.

**Comment by Evolvee** [comment]
ok but we need evidence that it should be possible :D

**Comment by teddys** [comment]
[literally first result](http://letmegooglethat.com/?q=intervene+totem%3F)

**Comment by Evolvee** [comment]
what am i supposed to see? dont tell me the post from 2013

**Comment by Easyfraggy** [comment]
You should 100% be able to intervene totems how is this even a question.

**Comment by Evolvee** [comment]
idk.. never saw that?

**Comment by Wolffenstein** [comment]
Fixed in rev 3154.
