### ISSUE TITLE
Unreachable Windy Clouds

### ISSUE THREAD

**Issue by PolarCookie** [Atlantiss/NetherwingBugtracker#6279]
**Description**: 
![WoWScrnShot_091719_185132](https://user-images.githubusercontent.com/1158801/65067579-1ead5880-d987-11e9-82ef-b9964c194f53.jpg)
![WoWScrnShot_091719_191507](https://user-images.githubusercontent.com/1158801/65067581-20771c00-d987-11e9-985f-dd8eff4f5819.jpg)
![WoWScrnShot_091719_195633](https://user-images.githubusercontent.com/1158801/65067583-2240df80-d987-11e9-837d-a1afe92cdadd.jpg)
![WoWScrnShot_091719_195743](https://user-images.githubusercontent.com/1158801/65067590-23720c80-d987-11e9-86b1-607d96905f26.jpg)

There's probably more, here's what I found doing a few laps around Nagrand.

**Server Revision**: 
3128

**Comment by NatsumeLily** [comment]
Not a bug. The clouds move, so they will be reachable at some point.

**Comment by PolarCookie** [comment]
They move around, but not within reachable range and some are so far above the islands that you wouldn't be able to drain them even if you were directly beneath.

**Comment by PolarCookie** [comment]
![WoWScrnShot_091919_221330](https://user-images.githubusercontent.com/1158801/65277741-dc248100-db2a-11e9-9f2e-46082577cb25.jpg)
Here's the 2nd image from a different angle, it's not getting anywhere close.

**Comment by The14me** [comment]
Not a bug 
https://www.wowhead.com/npc=24222/windy-cloud#comments:id=187493
