### ISSUE TITLE
[Object] Unstable Mana Crystal Crate

### ISSUE THREAD

**Issue by Terefinz** [Atlantiss/NetherwingBugtracker#628]
[//]: # (Enclose links to things related to the bug using http://wowhead.com or any other TBC database.)
[//]: # (You can use screenshot ingame to visual the issue.)
[//]: # (Write your tickets according to the format:)
[//]: # ([Quest][Azuremyst Isle] Red Snapper - Very Tasty!)
[//]: # ([NPC] Magistrix Erona)
[//]: # ([Spell][Mage] Fireball)
[//]: # ([Npc][Drop] Ghostclaw Lynx)
[//]: # ([Web] Armory doesnt work)

**Description**: Unstable Mana Crystal Crate [object=180600] are looted to collect crystals for the quest Unstable Mana Crystals [quest=8463]. Each crate has a yellow glow.

**Current behaviour**: After looting the crate, the crate disappears but the yellow glow does not. See screenshot and compare the one I am standing next to which I recently looted the unlooted one in the distance: 
![wowscrnshot_092518_220023](https://user-images.githubusercontent.com/43561224/46056662-ef1a9600-c10e-11e8-92b3-e6a018458420.jpg)

**Expected behaviour**: The yellow glow should go away with the crate after looting one and taking the crystal contained within.

**Server Revision**: 2060

**Comment by Shanghi** [comment]
To Wolfenstein: Here's another report on the old bug tracker about this: https://github.com/Atlantiss/AtlantissTBCBT/issues/4169

**Comment by duzyizly** [comment]
PTR r
![WoWScrnShot_062020_115650](https://user-images.githubusercontent.com/43931626/85199075-3a1a0b00-b2ed-11ea-9786-9108e83e0a78.jpg)
![WoWScrnShot_062020_115655](https://user-images.githubusercontent.com/43931626/85199076-3b4b3800-b2ed-11ea-9965-7673853e3d10.jpg)
![WoWScrnShot_062020_115714](https://user-images.githubusercontent.com/43931626/85199077-3be3ce80-b2ed-11ea-96ec-eb26bbb22dc9.jpg)


3392

**Comment by Wolffenstein** [comment]
Fixed in rev 3393.
