### ISSUE TITLE
H-Mechanar Cache of Legion not Awarding Badge

### ISSUE THREAD

**Issue by Baelek** [Atlantiss/NetherwingBugtracker#6280]
[//]: # ([Quest][Azuremyst Isle] Red Snapper - Very Tasty!)
[//]: # ([NPC] Magistrix Erona)
[//]: # ([Spell][Mage] Fireball)
[//]: # ([Npc][Drop] Ghostclaw Lynx)
[//]: # ([Web] Armory doesnt work)
[//]: # (To find server revision type `.server info` command in the game chat.)

**Description**: In H-Mechanar, the Cache of the Legion remains locked and players cannot loot the badges.

**Current behaviour**: When the player who has collected the keyparts for the cache to unlock it, they themselves can open it and collect their badge. Players who did not have the key cannot open it since it remains locked.

**Expected behaviour**: The cache should become unlocked to all available participants.

**Server Revision**: 3128

**Comment by Wolffenstein** [comment]
Fixed in rev 3129.
