### ISSUE TITLE
[Quest] Natural Remedies

### ISSUE THREAD

**Issue by The14me** [Atlantiss/NetherwingBugtracker#6281]
**Current behaviour**:After the chanelling nothing happen (no RP or summ the NPC)

**Expected behaviour**: 
https://www.wowhead.com/quest=10351/natural-remedies
https://www.youtube.com/watch?v=iGrljCsdOy4

**Server Revision**:  3130

**Comment by Wolffenstein** [comment]
Fixed in rev 3134.
