### ISSUE TITLE
Pets comes with previous buffs in arena

### ISSUE THREAD

**Issue by 4egito** [Atlantiss/NetherwingBugtracker#6283]
[//]: # (Enclose links to things related to the bug using http://wowhead.com or any other TBC database.)
[//]: # (You can use screenshot ingame to visual the issue.)
[//]: # (Write your tickets according to the format:)
[//]: # ([Quest][Azuremyst Isle] Red Snapper - Very Tasty!)
[//]: # ([NPC] Magistrix Erona)
[//]: # ([Spell][Mage] Fireball)
[//]: # ([Npc][Drop] Ghostclaw Lynx)
[//]: # ([Web] Armory doesnt work)
[//]: # (To find server revision type `.server info` command in the game chat.)

**Description**: 
Pets comes with old buffs in the arena
**Current behaviour**:
Pets comes with old buffs in the arena. There is a screenshot: https://drive.google.com/open?id=18H-E19b_ISiZ_Myu3I5TcxVsY3c21bzX
**Expected behaviour**: 
Pets need to be unbuffed
**Server Revision**:

**Comment by Wolffenstein** [comment]
Fixed in rev 3138.
