### ISSUE TITLE
Hatchers on Jan'alai have erratic behavior

### ISSUE THREAD

**Issue by joshuacod** [Atlantiss/NetherwingBugtracker#6284]
[//]: # (Enclose links to things related to the bug using http://wowhead.com or any other TBC database.)
[//]: # (You can use screenshot ingame to visual the issue.)
[//]: # (Write your tickets according to the format:)
[//]: # ([Quest][Azuremyst Isle] Red Snapper - Very Tasty!)
[//]: # ([NPC] Magistrix Erona)
[//]: # ([Spell][Mage] Fireball)
[//]: # ([Npc][Drop] Ghostclaw Lynx)
[//]: # ([Web] Armory doesnt work)
[//]: # (To find server revision type `.server info` command in the game chat.)

**Description**: Hatchers and dragonhawk hatchlings sometimes do weird things 

**Current behaviour**: Sometimes on the second or third wave of hatchers, both will go to one side even if there is still eggs unhatched on both sides. 

**Expected behaviour**: Hatchers should each go to a different side unless all the eggs are broken on one side.

**Server Revision**: 3131

**Comment by Wolffenstein** [comment]
According to the sources I have the hatchers will move to the direction with more eggs remaining if the numbers are uneven and that's how it's scripted.
