### ISSUE TITLE
Pets don't try to get behind their targets in melee combat

### ISSUE THREAD

**Issue by darknessangelo** [Atlantiss/NetherwingBugtracker#6285]
[//]: # (Enclose links to things related to the bug using http://wowhead.com or any other TBC database.)
[//]: # (You can use screenshot ingame to visual the issue.)
[//]: # (Write your tickets according to the format:)
[//]: # ([Quest][Azuremyst Isle] Red Snapper - Very Tasty!)
[//]: # ([NPC] Magistrix Erona)
[//]: # ([Spell][Mage] Fireball)
[//]: # ([Npc][Drop] Ghostclaw Lynx)
[//]: # ([Web] Armory doesnt work)
[//]: # (To find server revision type `.server info` command in the game chat.)

**Description**: 
Pets don't always attack from behind. Since 2.3 they should.
"Pets will try to get behind their targets when engaging in melee combat."
https://wowwiki.fandom.com/wiki/Patch_2.3.0
**Current behaviour**:
At start pets attack from behind or alteast they are somehow trying to, but after mob is moved, they stay. Sometimes happens that on start pets start attacking from side or even from the front.
**Expected behaviour**: 

**Server Revision**: 
3131

**Comment by Evolvee** [comment]
its only for PVE

you mean pve?

**Comment by Evolvee** [comment]
its probably already reported here somewhere

note: it should work like that only in PVE
