### ISSUE TITLE
Pattern: Mycah's Botanical Bag

### ISSUE THREAD

**Issue by The14me** [Atlantiss/NetherwingBugtracker#6286]
**Current behaviour**: Missing from the vendor .

**Expected behaviour**: 
https://www.wowhead.com/npc=18382/mycah
https://www.wowhead.com/item=38229/pattern-mycahs-botanical-bag
https://www.wowhead.com/item=38229/pattern-mycahs-botanical-bag#comments:id=307824

**Server Revision**:

**Comment by lyubomeer** [comment]
shouldn't be in game yet. was added in 2.4.3
