### ISSUE TITLE
Mote of Air drop rate for Enraged Air Spirit

### ISSUE THREAD

**Issue by EyStan** [Atlantiss/NetherwingBugtracker#6287]
**Description**: It seems the drop rate of Mote of Air for Enraged Air Spirits in Shadowmoon Valley is significantly lower than it was on retail. Last night I killed roughly 200 of them in about 2 hours and only got 31 motes of air, whereas with the expected drop rate of 26% (referenced here: https://tbc-twinhead.twinstar.cz/?npc=21060) it should've been more like 50 drop (with 1-2 motes each time). I understand this could just be bad rng but I've heard others agree with this.

**Current behaviour**: Enraged Air Spirit dropping motes of air at roughly ~10%

**Expected behaviour**: Enraged Air Spirit should drop motes at roughly ~25%

**Server Revision**:

**Comment by Evolvee** [comment]
![image](https://user-images.githubusercontent.com/1942409/65354740-9205d300-dbf0-11e9-8854-a14b16adc118.png)
 it already is
