### ISSUE TITLE
[Spell][Shaman] Fire Elemental Totem

### ISSUE THREAD

**Issue by Nikrotip** [Atlantiss/NetherwingBugtracker#6288]
**Description**: Fire Elemental Totem suffers 100% from AoE damage dealt by bosses/mobs/players + wrong positioning

**Current behaviour**: When summoned Fire Elemental receives as much AoE damage from bosses or any other mobs as a player himself. So the elemental, having 3.9-4k health can be easily destroyed in 1-2 seconds by a single shadow (frost) bolt volley or any other AoE. And that makes a 20 min cooldown ability completely useless. Also the elemental when spawned goes where he wants, he can go and stand in front of the boss or on the sides instead of going each time behind.

**Expected behaviour**: There's not much information but judging by https://wowwiki.fandom.com/wiki/Avoidance_(passive) patch 3.3.0 increased AoE damage reduction of Doomguards and Infernals summoned by warlock from 80% to 90%. And there were no avoidance for pets fixes before that patch. So it would make sense to say that summoned pets had like 80% avoidance before the buff in 3.3.0? And being a summoned pet just like warlock's ones shouldn't Fire Elemental have X% of innately passive AoE damage reduction?
Also i found a long forgotten article on mmochamp which claimed [https://imgur.com/fwwK9Gy](url)

**Server Revision**: 3132
![5345345](https://user-images.githubusercontent.com/48246079/65338380-bfdc1f00-dbd2-11e9-91b9-c113a23ec7e5.png)

**Comment by Evolvee** [comment]
this is all about wotlk... try to find some info from TBC era
