### ISSUE TITLE
Shartuul's Transporter: Phase one and two

### ISSUE THREAD

**Issue by Kaini27** [Atlantiss/NetherwingBugtracker#6289]
### _**Phase One**_

~Current behaviour**: Demons stop to spawn too early. Even you don't skip a second on a throw you still will get last 25 seconds with no spawns at all.
**Expected behaviour**: Even if spawning not suppose to go eternally there still should be a couple of more waves.~

**Current behaviour**: Too few spawns.
**Expected behaviour**: Old videos show that there are waves with a lot of hounds spawning with small delay **(E: not a core issue, might tickle later)**

**Current behaviour**: Charge ability has too small of a dead area, its possible to cast it by during kite.
**Expected behaviour**: Should be impossible to cast charge without using fear as soon as mob gets into meleerange. **(E: CORE PROBLEM @Wolffenstein --> also included in my document I sent you to fix )**

~**Current behaviour**: Hounds hitting for 230-330 and imps doing fireballs with 4500-5800 damage
**Expected behaviour**: Hounds should be hitting for 170-230 and fire balls around 1300 damage~

### _**Phase Two**_  

~**Current behaviour**: Gan'arg hitting approximately for 600-1100
**Expected behaviour**: Gan'arg should be hitting around 215-430 damage per swing~

**Current behaviour**: Again same as "Chaos Charge" in p1 "Axe Throw" and  "Super Jump" easy to cast from melee range by kiting.
**Expected behaviour**: Should be impossible to cast Axe Throw and Super Jump when demon is chasing player.

**Current behaviour**: Consume Essence heals player controled demon for 30-40k in combat log ,but realistically heals for less then 1%
**Expected behaviour**: Old videos show heal around 15-20%

**Current behaviour**: Druing Fel Flames cannot perform any other abilities and right click for auto attack cancels cast
**Expected behaviour**: should be able to cast other abilities while Fel Flames cast and it should be not interrupted by auto attack.

**Server Revision**: 3132

**Comment by Evolvee** [comment]
there is no "fel fireball" that does "around 1300 damage"

**Comment by Evolvee** [comment]
--> used strikethrough on fixed things

**Comment by Evolvee** [comment]
@Wolffenstein the rest are core issues

**Comment by Shineslippers** [comment]
Up! 2024 is already here...

Phase 2
[Gan'arg Underling](https://www.wowhead.com/tbc/npc=23199/ganarg-underling#comments) has tendency to evade after spawn. Player can cast stun on it or just run out and they will return to spawn spot.

Phase 4
[Dreadmaw](https://www.wowhead.com/tbc/npc=23275/dreadmaw) always outrun a player. More stack he is getting - faster running. You just can't keep him on distance. On top of it after charge he is no apply [Lacerating Bite](https://www.wowhead.com/tbc/spell=41940/lacerating-bite)

Other
[Shivan Assassin](https://www.wowhead.com/tbc/npc=23220/shivan-assassin) spell [Death Blast](https://www.wowhead.com/tbc/spell=40736/death-blast) doesn't work properly. It's convert only initial damage into healing. Doesn't matter how long debuff is active on target healing always the same.
I don't know is it correct or not but seems very odd that a player can cast abilities on all of those demons. You can Fear it, apply Curse of Tongues and other debuffs. That makes whole event itrrelevant.

**Comment by Godmatik** [comment]
Closing - consolidating all information into one thread
