### ISSUE TITLE
[Druid] Changing form does not break net/entangling roots

### ISSUE THREAD

**Issue by Maelareth** [Atlantiss/NetherwingBugtracker#629]
[//]: # (Enclose links to things related to the bug using http://wowhead.com or any other TBC database.)
[//]: # (You can use screenshot ingame to visual the issue.)
[//]: # (Write your tickets according to the format:)
[//]: # ([Quest][Azuremyst Isle] Red Snapper - Very Tasty!)
[//]: # ([NPC] Magistrix Erona)
[//]: # ([Spell][Mage] Fireball)
[//]: # ([Npc][Drop] Ghostclaw Lynx)
[//]: # ([Web] Armory doesnt work)

**Description**: When netted or rooted to the ground, changing druid form does not break the effect.

**Current behaviour**: When netted or rooted to the ground, changing druid form does not break the effect.

**Expected behaviour**: Changing form should end the effect of rooting/netting

**Server Revision**: 2060

**Comment by totaemoeggerli** [comment]
I looked a little bit into it and I think I found the problem. Entering bearform removes net, leaving bearform doesn't. 
https://gfycat.com/ScarceFrightenedBunny

same thing is happening here: https://github.com/Atlantiss/NetherwingBugtracker/issues/574

**Comment by Maelareth** [comment]
> I looked a little bit into it and I think I found the problem. Entering bearform removes net, leaving bearform doesn't.
> https://gfycat.com/ScarceFrightenedBunny
> 
> same thing is happening here: #574

Exactly the same issue as I experienced

**Comment by Wolffenstein** [comment]
Fixed in rev 2064.
