### ISSUE TITLE
[Quest][Blade's Edge Mountains] The Softest Wings

### ISSUE THREAD

**Issue by narkil** [Atlantiss/NetherwingBugtracker#6290]
**Description**: Drop rate for quest item Iridescent Wing (https://www.wowhead.com/item=30792/iridescent-wing) is very low.

**Current behaviour**:
After killing about 30 mobs, I have only 2 quest items.

**Expected behaviour**: 
Drop rate should be much higher from NPC Mature Silkwing  (https://www.wowhead.com/npc=21839/mature-silkwing)

**Server Revision**: 3133

**Comment by Evolvee** [comment]
its 25% right now

which is way more than what it should be ^^ http://web.archive.org/web/20070908234018/http://thottbot.com/i30792
