### ISSUE TITLE
Daily Dungeon quests in Hellfire Citadel gives both Thrallmar and Honor Hold reputation

### ISSUE THREAD

**Issue by Manaci** [Atlantiss/NetherwingBugtracker#6291]
**Current behaviour**:
Currently completing [Wanted: Shattered Hand Centurions](https://db.excalibur.ws/?quest=11364) gives reputation with both the Honor Hold and the Thrallmar faction, putting you as hated with the enemy faction reputation on your list. This is most likely also the case with any other Hellfire Citadel daily dungeon quest, such as [Wanted: Nazan's Riding Crop](https://db.excalibur.ws/?quest=11354), [Wanted: Keli'dan's Feathered Stave](https://db.excalibur.ws/?quest=11362) and [Wanted: Bladefist's Seal](https://db.excalibur.ws/?quest=11363).
Images provided by guildies: [Reward](https://cdn.discordapp.com/attachments/545643457750761502/624754101523185694/lulwat.JPG) and [List](https://i.imgur.com/fcdV7kh.jpg).
**Expected behaviour**: 
These quests should only give reputation with the Consortium and the allied faction.

**Server Revision**: 
3133

**Comment by Evolvee** [comment]
will be fixed in next core rev
