### ISSUE TITLE
[NPC] Can't interact with the Zeppelin Vendors

### ISSUE THREAD

**Issue by Tereneckla** [Atlantiss/NetherwingBugtracker#6292]
[//]: # (Enclose links to things related to the bug using http://wowhead.com or any other TBC database.)
[//]: # (You can use screenshot ingame to visual the issue.)
[//]: # (Write your tickets according to the format:)
[//]: # ([Quest][Azuremyst Isle] Red Snapper - Very Tasty!)
[//]: # ([NPC] Magistrix Erona)
[//]: # ([Spell][Mage] Fireball)
[//]: # ([Npc][Drop] Ghostclaw Lynx)
[//]: # ([Web] Armory doesnt work)
[//]: # (To find server revision type `.server info` command in the game chat.)

**Description**: 
![image](https://user-images.githubusercontent.com/50233983/65386777-03a06700-dd40-11e9-8ab1-370b30998161.png)

**Current behaviour**: They should sell you stuff

**Expected behaviour**: They don't

**Server Revision**: 3133

**Comment by Evolvee** [comment]
they arent scripted yet

**Comment by Wolffenstein** [comment]
Fixed in rev 3138.
