### ISSUE TITLE
Tastyfish Schools don't show up with fishfinding

### ISSUE THREAD

**Issue by Tereneckla** [Atlantiss/NetherwingBugtracker#6293]
[//]: # (Enclose links to things related to the bug using http://wowhead.com or any other TBC database.)
[//]: # (You can use screenshot ingame to visual the issue.)
[//]: # (Write your tickets according to the format:)
[//]: # ([Quest][Azuremyst Isle] Red Snapper - Very Tasty!)
[//]: # ([NPC] Magistrix Erona)
[//]: # ([Spell][Mage] Fireball)
[//]: # ([Npc][Drop] Ghostclaw Lynx)
[//]: # ([Web] Armory doesnt work)
[//]: # (To find server revision type `.server info` command in the game chat.)

**Description**: 
![image](https://user-images.githubusercontent.com/50233983/65387183-dc986400-dd44-11e9-93cf-9bae0bff2247.png)

**Current behaviour**: Don't show up

**Expected behaviour**:  They should

**Server Revision**: 3133

**Comment by Wolffenstein** [comment]
Fixed in rev 3138.
