### ISSUE TITLE
[Raid] [Zul'Aman] Zul'jin bugs

### ISSUE THREAD

**Issue by Tereneckla** [Atlantiss/NetherwingBugtracker#6294]
[//]: # (Enclose links to things related to the bug using http://wowhead.com or any other TBC database.)
[//]: # (You can use screenshot ingame to visual the issue.)
[//]: # (Write your tickets according to the format:)
[//]: # ([Quest][Azuremyst Isle] Red Snapper - Very Tasty!)
[//]: # ([NPC] Magistrix Erona)
[//]: # ([Spell][Mage] Fireball)
[//]: # ([Npc][Drop] Ghostclaw Lynx)
[//]: # ([Web] Armory doesnt work)
[//]: # (To find server revision type `.server info` command in the game chat.)

**Description**: 
Eagle Phase: Spells with 0 mana cost should not trigger Energy Storm.
For example spells cast with Inner Focus or Holy Concentration Proc.

Lynx Phase: During Claw Rage he should switch to the player highest in threat if his target gets invulnerable/untargetable through Iceblock/Blessing of Protection

Sadly video capture did not work, so I will give videos with next reset.

**Server Revision**: 3133

**Comment by Wolffenstein** [comment]
Fixed in rev 3138.
