### ISSUE TITLE
[Spell][Hunter] Pet Skill Screech

### ISSUE THREAD

**Issue by BDweller** [Atlantiss/NetherwingBugtracker#6295]
[//]: # (Enclose links to things related to the bug using http://wowhead.com or any other TBC database.)
[//]: # (You can use screenshot ingame to visual the issue.)
[//]: # (Write your tickets according to the format:)
[//]: # ([Quest][Azuremyst Isle] Red Snapper - Very Tasty!)
[//]: # ([NPC] Magistrix Erona)
[//]: # ([Spell][Mage] Fireball)
[//]: # ([Npc][Drop] Ghostclaw Lynx)
[//]: # ([Web] Armory doesnt work)
[//]: # (To find server revision type `.server info` command in the game chat.)

**Description**: [Screech](https://wow.gamepedia.com/Screech_(pet)) is not generating any threat

**Current behaviour**: Screech seems to be generating zero threat. This can be replicated by sending a pet into multiple mobs and leaving it there, manually spamming screech. After any amount of screech applications, a single tick of Mend Pet will pull aggro from any adds.

**Expected behaviour**: 

> Screech is an ability for Hunters to teach their pets. It does physical damage to a single target and applies a debuff that lowers the attack power of all nearby enemies. **The AoE debuff of screech has an innate threat value built into it**, making Screech a powerful tool for pet-tanking multiple mobs. 
_Allow 4 applications of Screech, and then nearby targets can be shot with a Hunter's [Multi-Shot] without getting aggro._

**Server Revision**: 3139

[Wowpedia link of the pre WOTLK version](https://wow.gamepedia.com/Screech_(pet)) 
[Archive Petopia link](http://web.archive.org/web/20080619085357/http://petopia.brashendeavors.net/html/skills/skills_compare.php) Asterisk at the end backs up the ability's debuff causing threat

**Comment by Wolffenstein** [comment]
Fixed in rev 3162.
