### ISSUE TITLE
[Spell][Warlock] Summoning in Netherstorm/TK

### ISSUE THREAD

**Issue by NatsumeLily** [Atlantiss/NetherwingBugtracker#6297]
[//]: # (Enclose links to things related to the bug using http://wowhead.com or any other TBC database.)
[//]: # (You can use screenshot ingame to visual the issue.)
[//]: # (Write your tickets according to the format:)
[//]: # ([Quest][Azuremyst Isle] Red Snapper - Very Tasty!)
[//]: # ([NPC] Magistrix Erona)
[//]: # ([Spell][Mage] Fireball)
[//]: # ([Npc][Drop] Ghostclaw Lynx)
[//]: # ([Web] Armory doesnt work)
[//]: # (To find server revision type `.server info` command in the game chat.)

**Description**: Summoning in Netherstorm/TK is blocked. 

**Current behaviour**: Reports of people being able to summon in Netherstorm/TK.
*More testing required*

**Expected behaviour**: Summoning in Netherstorm/TK should be blocked until patch 2.4.

**Server Revision**: 3139

**Comment by eri1997** [comment]
This is an intentional change.

**Comment by NatsumeLily** [comment]
Why?

**Comment by Evolvee** [comment]
ask Wolfenstein
