### ISSUE TITLE
[Spell][Mage] Channelled spells sometimes get interrupted when a spider web debuff falls off

### ISSUE THREAD

**Issue by viktor-wolf** [Atlantiss/NetherwingBugtracker#6298]
[//]: # (Enclose links to things related to the bug using http://wowhead.com or any other TBC database.)
[//]: # (You can use screenshot ingame to visual the issue.)
[//]: # (Write your tickets according to the format:)
[//]: # ([Quest][Azuremyst Isle] Red Snapper - Very Tasty!)
[//]: # ([NPC] Magistrix Erona)
[//]: # ([Spell][Mage] Fireball)
[//]: # ([Npc][Drop] Ghostclaw Lynx)
[//]: # ([Web] Armory doesnt work)
[//]: # (To find server revision type `.server info` command in the game chat.)

**Description**: 
Certain spider mobs cast an immobilising web debuff. If this debuff falls off while a spell is being channelled, the spell will sometimes get interrupted. Tested on mage with Evocation and Blizzard, but likely affects all channelled spells. Tested with Venom Web Spiders (Duskwood) and Myst Spinners (Bloodmyst Isle), but likely happens with all webbing spider mobs.

**Current behaviour**:
Web debuff falling off sometimes interrupts channelled spells.

**Expected behaviour**: 
Web debuff falls off without interrupting channelled spells.

**Server Revision**: 
3139

**Comment by viktor-wolf** [comment]
Since making this report I have actually had the interruption happen with a different immobilizing debuff (mob-casted Frost Nova, can't remember which mob) and on regular casted spells as well.

**Comment by Macumbafeh** [comment]
Yes ! And i think is same thing for nova (mage) and others snare...
When you are casting in snare and the debuff end, it interrumpt your cast.

**Comment by Godmatik** [comment]
Fixed a long time ago
