### ISSUE TITLE
Hardiness Orc Racial

### ISSUE THREAD

**Issue by Miikell** [Atlantiss/NetherwingBugtracker#6299]
https://tbcdb.com/?spell=20573

**Description**: This racial should incresed Chance to resist Stun effects by an additional 15%.

**Current behaviour**: This racial does not work. Do not increased chance on stun.

**Expected behaviour**: It should increased chance on rezist stun and stacked with other the same efekts

**Server Revision**: 3139

**Comment by Evolvee** [comment]
proof it doesnt work??
