### ISSUE TITLE
Caster mobs - faulty mechanic

### ISSUE THREAD

**Issue by Mewmewww** [Atlantiss/NetherwingBugtracker#63]
[//]: # (Enclose links to things related to the bug using http://wowhead.com or any other TBC database.)
[//]: # (You can use screenshot ingame to visual the issue.)
[//]: # (Write your tickets according to the format:)
[//]: # ([Quest][Azuremyst Isle] Red Snapper - Very Tasty!)
[//]: # ([NPC] Magistrix Erona)
[//]: # ([Spell][Mage] Fireball)
[//]: # ([Npc][Drop] Ghostclaw Lynx)
[//]: # ([Web] Armory doesnt work)

**Description**: After casting an ability, NPC tries to run after me to melee attack me. after x amount of time, he recasts his spell

**Current behaviour**: Runs after me to melee attack

**Expected behaviour**: Shouldnt run after me to melee attack

**Server Revision**: https://gfycat.com/CavernousOldDartfrog <-- recording of the problem

**Comment by The14me** [comment]
Work just fine now (rev 3441)
Can be closed.
