### ISSUE TITLE
NPC Stillpine Ancestor Akida missing transparent ghost effect

### ISSUE THREAD

**Issue by Notmittz** [Atlantiss/NetherwingBugtracker#630]
([Quest][Azuremyst Isle] The Prophecy of Akida)
([NPC] Stillpine Ancestor Akida)

**Description**: 
He is not a semi transparent ghost

**Current behaviour**:
He looks fully corporeal

**Expected behaviour**: 
He is a spirit and supposed to look more ghost-like
See picture: https://www.wowhead.com/npc=17379/stillpine-ancestor-akida

**Server Revision**:

**Comment by aresbrutus** [comment]
https://youtu.be/Zhj7QxsLPg0?t=9

Confirmed.

**Comment by Evolvee** [comment]
rev xdd
