### ISSUE TITLE
[NPC][Hex lord Malacrass] Uncontrollable minions

### ISSUE THREAD

**Issue by XXimiCC** [Atlantiss/NetherwingBugtracker#6300]
[//]: # (Enclose links to things related to the bug using http://wowhead.com or any other TBC database.)
[//]: # (You can use screenshot ingame to visual the issue.)
[//]: # (Write your tickets according to the format:)
[//]: # ([Quest][Azuremyst Isle] Red Snapper - Very Tasty!)
[//]: # ([NPC] Magistrix Erona)
[//]: # ([Spell][Mage] Fireball)
[//]: # ([Npc][Drop] Ghostclaw Lynx)
[//]: # ([Web] Armory doesnt work)
[//]: # (To find server revision type `.server info` command in the game chat.)

**Description**: 
Minions of Hex lord Malacrass randomly threw off controll like ship, sleep

**Current behaviour**:
Randomly threw off controll like ship, sleep

**Expected behaviour**: 
Сontrol must act a certain number of seconds

**Server Revision**: 
3139, hash: 9be8430ba5cb

**Comment by Evolvee** [comment]
hearthbeat resist
