### ISSUE TITLE
Warlock Demon problem.

### ISSUE THREAD

**Issue by Abrith** [Atlantiss/NetherwingBugtracker#6301]
Hello!

After last update (s3) I'm facing annoying bug with my demons. Often (not always but very often) they do not appear after riding on mount from point A to B. Especially if it comes to fly mount in world. When I get on mount there is demon when I reach destination <poof> no demon. All time need to summon new one and gather large amounts of soulshards. Hope you can investigate it and fix the problem.

Regards

Abrith

**Comment by Baelek** [comment]
This issue has been extremely troublesome in the zone SMV.

**Comment by ziede725** [comment]
Hello I have this issue too and it's very annoying .

**Comment by Godmatik** [comment]
Was fixed at start of Netherwing last year.
