### ISSUE TITLE
"Name" is ignoring you message when inviting to group

### ISSUE THREAD

**Issue by ntbwow** [Atlantiss/NetherwingBugtracker#6303]
**Description**: 
When inviting players to group, sometimes you get a message "Char name" is ignoring you. However, those characters are not necessarily ignoring you.
Please see attached images
**Current behaviour**:
Receive a message "Char name" is ignoring you.
**Expected behaviour**: 
Receive a message: "Char name" is already in a group or "Char name" gets a group invite.
![WoWScrnShot_092819_131155](https://user-images.githubusercontent.com/55914354/65815110-89fef200-e1f3-11e9-94c0-08afc364f458.jpg)
![WoWScrnShot_092819_132646](https://user-images.githubusercontent.com/55914354/65815117-ad29a180-e1f3-11e9-91ce-1370bbc897bb.jpg)

**Server Revision**: 3140

**Comment by lajhar** [comment]
You get this answer when your invitee is using ghetto hs - during that 60 sec before he'd be teleported.
