### ISSUE TITLE
[Guild information][Log] Guild log empty

### ISSUE THREAD

**Issue by addi011** [Atlantiss/NetherwingBugtracker#6304]
**Description**: @danbopes Daystar told me that I should tag you. Our problem is that our guild log is empty unfortunately. We are the alliance guild "Lionhearts". Hopefully you can help us. 

**Current behaviour**: Empty guild log

**Expected behaviour**:  Guild log showing changes in guild member structure

**Server Revision**:  3140

Thanks in advance!
Xinaros

**Comment by addi011** [comment]
@danbopes I don't know if you changed anything today, but we can now see our guild log again. Thanks for your assistance!

**Comment by addi011** [comment]
@danbopes this issue came back again. It worked until today afternoon and as I checked it again in the evening, the log was empty unfortunately. Can you please have a look again?

**Comment by addi011** [comment]
It's working again ... If you have changed anything recently, you may have found the cause for this problem.

**Comment by addi011** [comment]
Ah, i see. Thanks for the feedback and your work on this topic. Really appreciate it!

**Comment by addi011** [comment]
@danbopes Do you have an update on this?

**Comment by danbopes** [comment]
Rev 3247
