### ISSUE TITLE
[NPC] Captain Saeed -Stuck after event.

### ISSUE THREAD

**Issue by The14me** [Atlantiss/NetherwingBugtracker#6305]
**Description**: 
https://www.wowhead.com/quest=10439/dimensius-the-all-devouring
https://www.wowhead.com/npc=20985/captain-saeed

**Current behaviour**: If u wipe/complete  ''Dimensius the All-Devouring'' Captain stuck at spawn and no dialog option.Need Gm to reset him.

**Expected behaviour**: 

**Server Revision**:

**Comment by danbopes** [comment]
This isn't wipe or reset. Something else is causing Captain to stuck.

**Comment by Evolvee** [comment]
i think i might have one possible cause(spell_dbc with too big entry/id range), will test later

**Comment by Evolvee** [comment]
possibly fixed in next rev

**Comment by Evolvee** [comment]
well it must be a core issue then

**Comment by Wolffenstein** [comment]
Fixed in rev 3198.
