### ISSUE TITLE
[Quest] The Raven Stones 

### ISSUE THREAD

**Issue by The14me** [Atlantiss/NetherwingBugtracker#6306]
**Description**: 
https://www.wowhead.com/quest=10988/the-raven-stones
https://www.wowhead.com/item=32315/cenarion-sparrowhawk-whistle

**Current behaviour**: Bird do nothing when u summ it.

**Expected behaviour**: Suppose to find the object that are needed for the quest in range.
https://www.wowhead.com/quest=10988/the-raven-stones#comments:id=87812

**Server Revision**:

**Comment by Evolvee** [comment]
https://github.com/Atlantiss/AtlantissTBCBT/issues/1472
