### ISSUE TITLE
Bugged defense stats.

### ISSUE THREAD

**Issue by Kawenda** [Atlantiss/NetherwingBugtracker#6307]
Description: Defense stats is incorrect.

Current behaviour: https://tbc-twinhead.twinstar.cz/?item=30300 This item has +30def. With this item I have 491 defense and without this item I have 479 defense ( 479def. + 30def. = 509def.) ant this happens with many other items.

Expected behaviour: Fixed defense statistics.

Server Revision:

**Comment by Tereneckla** [comment]
The item gives defense rating and not Defense
