### ISSUE TITLE
[Quest] The Batte for Arathi Basin! does not work

### ISSUE THREAD

**Issue by Tereneckla** [Atlantiss/NetherwingBugtracker#6309]
[//]: # (Enclose links to things related to the bug using http://wowhead.com or any other TBC database.)
[//]: # (You can use screenshot ingame to visual the issue.)
[//]: # (Write your tickets according to the format:)
[//]: # ([Quest][Azuremyst Isle] Red Snapper - Very Tasty!)
[//]: # ([NPC] Magistrix Erona)
[//]: # ([Spell][Mage] Fireball)
[//]: # ([Npc][Drop] Ghostclaw Lynx)
[//]: # ([Web] Armory doesnt work)
[//]: # (To find server revision type `.server info` command in the game chat.)

**Description**: 
![image](https://user-images.githubusercontent.com/50233983/65831435-90f03800-e2b9-11e9-91ea-38cda61797a0.png)

Alterac Valley quests "Capture a Mine", "Coldtooth Supplies", "The Graceyards of Alterac" and "Towers and Bunkers" also don't work
"Irondeep Supplies" probably does not work aswell.

I guess this happens because you technically are in a raid group.

**Current behaviour**: Capturing stables does not give progress for the quest.

**Expected behaviour**: Capturing stables gives progress for the quest.

**Server Revision**: 3140

**Comment by Manaci** [comment]
Reported ages ago [here](https://github.com/Atlantiss/NetherwingBugtracker/issues/5473)

**Comment by Evolvee** [comment]
this is ez fix tho xd

**Comment by Wolffenstein** [comment]
Fixed in rev 3166.
