### ISSUE TITLE
[Loot][Core Mechanic] Unable to Loot Corpses

### ISSUE THREAD

**Issue by Terefinz** [Atlantiss/NetherwingBugtracker#631]
[//]: # (Enclose links to things related to the bug using http://wowhead.com or any other TBC database.)
[//]: # (You can use screenshot ingame to visual the issue.)
[//]: # (Write your tickets according to the format:)
[//]: # ([Quest][Azuremyst Isle] Red Snapper - Very Tasty!)
[//]: # ([NPC] Magistrix Erona)
[//]: # ([Spell][Mage] Fireball)
[//]: # ([Npc][Drop] Ghostclaw Lynx)
[//]: # ([Web] Armory doesnt work)

**Description**: Don't know quite what went wrong but out of nowhere I was unable to loot enemies which I killed (in this case multiple murlocs) until I relogged, which fixed the issue. I am using no addons whatsoever and wish I could provide more information of what may have gone wrong. They were the first mobs I had killed following a respawn though so maybe it is related to that or also as seen in the video, I leveled up as I killed the mobs, so maybe it is related to that.

**Current behaviour**: https://streamable.com/mkohr

**Expected behaviour**: Mobs should be lootable upon death.

**Server Revision**: 2060

**Comment by Easyfraggy** [comment]
Need ways to recreate or we can't fix.

**Comment by Manaci** [comment]
Fixed
