### ISSUE TITLE
Sethekk Guards in Sethekk Halls Heroic damage/attack speed Too High!

### ISSUE THREAD

**Issue by Thordin88** [Atlantiss/NetherwingBugtracker#6310]
[NPC] Sethekk Guard (https://www.wowhead.com/npc=18323/sethekk-guard; https://wow.gamepedia.com/Sethekk_Guard)

**Description**: Sethekk Guards in Sethekk Halls Heroic damage/attack speed Too High! 
 They hit for 3K-4K (and come in pairs) on 14.000 armor karazhan geared tank. https://www.tentonhammer.com/guides/sethekk-halls-guide - QUOTE: _Sethekk Guards – You encounter these early and often in the instance. The big concern with them is their AOE Thunderclap ability that hits for up to 1500 damage with a range of about 10 yards._

**Current behaviour**: Way too high damage on geared tank (3K-4K melee). Their attack speed might also need be adjusted, though I am not sure of that.

**Expected behaviour**:  They are supposed to be tanky mobs (using thunderclap - see wowhead link) that shouldn't do more than 500-600 melee damage on high armor tanks (I had 14K armor and 58% dmg reduction). Their main damage is their Thunderclap which should, as stated above hit for around 1.5K nature.

**Server Revision**: 2.3

**Comment by danbopes** [comment]
Proof?

**Comment by Thordin88** [comment]
I just wiped twice in there (my second run there) and this time with way better gear 500 defense 15K hp unbuffed - this needs to be tested by the people in charge. I am sure this has been reported before. I actually rage quit after this.

**Comment by Thordin88** [comment]
I might get proof of this next time.

**Comment by Thordin88** [comment]
> Proof?

![WoWScrnShot_092919_235709](https://user-images.githubusercontent.com/10476595/65839377-6764fa00-e315-11e9-98f9-45251690844b.jpg)
![WoWScrnShot_092919_235742](https://user-images.githubusercontent.com/10476595/65839378-67fd9080-e315-11e9-9467-db3401a8fa59.jpg)

**Comment by Evolvee** [comment]
its just still in 2.0.3 state

**Comment by Thordin88** [comment]
Ok thanks for answering, but I guess I will just have to avoid tanking this dungeon in the future.

**Comment by Kolmarwow** [comment]
you can disarm them as a warrior to massively reduce their damage for 10 secs which makes them doable, but otherwise yeah they hit very hard and can't be CC'd through any other means as far as i know.

**Comment by Easyfraggy** [comment]
Thunderclap and demoshout are pretty strong abilities.

**Comment by Thordin88** [comment]
First of all, I believe I know how to play my class at least at a basic level (and I believe thunderclap and demo shout are spells learned early on) so these comments are not constructive. Secondly, as a guy that has tanked all heroics that don't require flying - I believe I have tested most stuff in there to see that these guys are a bit overtuned and a small nerf would definitely be required. I am also a donor to the server and trully believe in the quality of scripts and dungeon/boss/mob design, but **this problem might definitely deter new players from continuing on this server, especially tanks.**

**Comment by GitHubTheySaid** [comment]
i have tanked healed this HC dungeon myself. and its a simple case of gear check needed on both tank/heal. you just don't do it in low gear. i found 1k HPS and more depending on the tank is a threshold  to survive untill dps nukes 1st one down. it allways is hard but you tell your healer to not stop casting his best HPS (he should know for himself) Shettek guards: non disarmable so yes its hardest part, just spam heal, have a nightmare seed, or your defensives for it. 1cd per pack

**Comment by Easyfraggy** [comment]
I have tanked all of these heroics in blues aswell way back when and they certainly do hit hard but when they are debuffed and you can even include a disarm if nessesary they aren't quite that hard. Another strategy you can use except for the first pack is have 1 player kite one of them while you kill the other - A common strategy to deal with hard hitting mobs in general in dungeons.

**Comment by Kolmarwow** [comment]
Disarm especially is criminally underrated in dungeons, it reduces the damage of most weapon-wielding mobs by over 75%. If i recall right disarming one of the Fel Guards in Arcatraz even reduced its damage from ~3000 per hit to 5 (five!) per hit. After I discovered how useful Disarm was I never wiped to those Sethekk Guards again, not once.
