### ISSUE TITLE
[Shartuul event] - third demon (Shivan Assassin)

### ISSUE THREAD

**Issue by nlhil** [Atlantiss/NetherwingBugtracker#6311]
**Description**: 
On third phase when you fight Eye of Shartuul (and next bosses too) - Ice Block must reflect spells. Now it's just makes you immune.
Proofs - any combat logs/this one for example, from my last fight:
> 19:51:13> Shivan Assassin casts Ice Block.
> 19:51:13> Shivan Assassin gains Ice Block.
> 19:51:13> Eye of Shartuul suffers 1712 Physical damage from Shivan Assassin's Siphon Life.
> 19:51:13> Shivan Assassin's Siphon Life heals Shivan Assassin for 1712.
> 19:51:14> Eye of Shartuul **Dark Glare failed. Shivan Assassin was immune.**
> 19:51:15> Eye of Shartuul suffers 1712 Physical damage from Shivan Assassin's Siphon Life.

Second - looks like Chaos strike not works at all: 
> 19:51:27> Shivan Assassin casts Chaos Strike at Eye of Shartuul.
> 19:51:27> Shivan Assassin **begins casting Chaos Strike**.
> 19:51:29> Eye of Shartuul suffers 2000 Shadow damage from Shivan Assassin's Shadow Nova.
> 19:51:29> Shivan Assassin's Shadow Nova heals Shivan Assassin for 2000.
> 19:51:29> Eye of Shartuul suffers 1712 Physical damage from Shivan Assassin's Siphon Life.
> 19:51:29> Shivan Assassin's Siphon Life heals Shivan Assassin for 1712.
> 19:51:30> Shivan Assassin's Chaos Strike **hits Eye of Shartuul for 20961 Holy.
and that's all... no weakness effect at enemy, no chaos form for my demon and even no "very high damage" - same damage like bolt in any form**

Third - Death Blast (Shadow form) must heal u if target affected by Siphon life and consume it. But it's not heal u

> 19:50:32> Shivan Assassin's **Death Blast hits Eye of Shartuul for 12535 Shadow.**
> 19:50:32> Siphon Life dissipates from Eye of Shartuul.
> etc... **no healing**

Proofs that spells should work like I described:
https://wowwiki.fandom.com/wiki/Shartuul%27s_Transporter_(event)
https://www.wowhead.com/npc=23230/shartuul#comments
or any other Shartuul event guide...

btw.. I found only one version, how much damage Dark Glare should have - 100k. Netherwing version is much more... 
> 23:09:02> Eye of Shartuul's Dark Glare hits Shivan Assassin for 100000 Shadow.
> 23:09:03> Eye of Shartuul's Dark Glare hits Shivan Assassin for 30000 Shadow.
> 23:09:04> Eye of Shartuul's Dark Glare hits Shivan Assassin for 30000 Shadow.
> 23:09:05> Eye of Shartuul's Dark Glare hits Shivan Assassin for 30000 Shadow. 

But ofc it will be no problem if u fix Ice Block

**Current behaviour**:
- Ice Block not reflecting spells.
- Chaos Strike not give u chaos form (+haste & +300% dmg), not cause weakness effect etc
- Death Blast not heal u when hit, it just consume Siphon Life instead

**Expected behaviour**: 
Spells should work properly -_-

**Server Revision**: 
3140

**Comment by Canderous** [comment]
I would also like to add that Flame Buffet seems to do nothing at all. It should increase the damage of Pyroblast and subsequent Flame Buffets by the displayed amount (per stack).

**Comment by Godmatik** [comment]
Closing - consolidating all information into one thread
