### ISSUE TITLE
[raid][Serperntshrine cavern] [Lady Vashj] Persuasion

### ISSUE THREAD

**Issue by GitHubTheySaid** [Atlantiss/NetherwingBugtracker#6312]
Description: Persuasion 
Charmed.
Unstoppable.
Increased damage dealt by 75%.
Increased healing done by 200%.
Increased movement speed by 200%.
20 seconds remaining

Current behaviour: A mind control spell used by Lady Vashj in Serpentshrine Cavern on multiple raid members at once.

Expected behaviour: Expecting current patch notes 2.3 to follow the removal of previous patches of this mechanic which has since been removed from her ability table as of patch 2.1.
Server Revision: 3140

**Comment by Steve23x** [comment]
True.
_______________
Lady Vashj can no longer use the ability Persuasion
https://wowwiki.fandom.com/wiki/Patch_2.1.0

**Comment by eri1997** [comment]
Boss mechanics and tuning  in NW never followed patch notes . They try to tune and use spell mechanics that will keep the fights interesting

**Comment by Steve23x** [comment]
9k frost bolts from mage? Not cool.

**Comment by eri1997** [comment]
You are supposed to interrupt them. Usually we assign shamans to take care of that. If its a melee your offtank should taunt them.
 The first version guilds did on server launch any spell from mc was a pure 1 shot and it was very risky to try to tank the mele cuz they did a lot more dmg so meles used to remove weapons  like 2 secs before the mc. Compare that to the version you have now and you'll see its nerfed to it being a joke. Not to mention a much tighter enrage timer cuz vashj had more hp, and a chance for your tanks to be mindcontrolled aswell . All aspects of the fight that were nerfed .Every guild that was stuck on vashj through this phase and progressing on it managed to easily do it after the nerfs on 2.1 release. Keep trying and I'm sure you'll get it soon enough.

**Comment by Easyfraggy** [comment]
It was decided to keep the MC mechanic by devs.
