### ISSUE TITLE
[Spell] [Warlock] Eye of Kilrogg Causing Mobs to Attack You

### ISSUE THREAD

**Issue by Baelek** [Atlantiss/NetherwingBugtracker#6313]
**Description**: When Eye of Kilrogg pulls mobs, the mobs should attack the eye, then run up to the warlock to begin attacking the warlock.

**Current behaviour**: Currently, when the mobs attack the eye, they immediately melee the warlock too, even if the warlock is far out of range.

**Expected behaviour**: The mobs should be in range of the warlock to begin attacking.

**Server Revision**: 3140

**Video**: https://youtu.be/PXD-b2KJJFY

**Comment by The14me** [comment]
Rev.3460 not more an issue.
Can be closed.
