### ISSUE TITLE
[Arena/Warlock] 2 important Skills not working at all

### ISSUE THREAD

**Issue by Tweet1337** [Atlantiss/NetherwingBugtracker#6314]
[//]: # (Enclose links to things related to the bug using http://wowhead.com or any other TBC database.)
[//]: # (You can use screenshot ingame to visual the issue.)
[//]: # (Write your tickets according to the format:)
[//]: # ([Quest][Azuremyst Isle] Red Snapper - Very Tasty!)
[//]: # ([NPC] Magistrix Erona)
[//]: # ([Spell][Mage] Fireball)
[//]: # ([Npc][Drop] Ghostclaw Lynx)
[//]: # ([Web] Armory doesnt work)
[//]: # (To find server revision type `.server info` command in the game chat.)

**Description**:  "Demonic Knowledge" and "Master Demonologist" don't work in Arena.

**Current behaviour**: "Demonic Knowledge" and "Master Demonologist" don't work in Arena. The buffs don't show up in buffs. In Char-Screen the stats are also lower than outside arena (-> no visual bug). I summoned Imp, Voidwalker and Felhunter and with none of them i get the buffs (if you join arena with a pre-summoned pet you still got the buffs, but you lose it when you summon imp for fireshield and you don't get it back neither with Voidwalker nor Felhunter.)

**Expected behaviour**: Both Skills should work like everywhere else. 

**Server Revision**: 3140

**Comment by Wolffenstein** [comment]
Fixed in rev 3154.
