### ISSUE TITLE
Warlock felhunter stamina scaling

### ISSUE THREAD

**Issue by Speank** [Atlantiss/NetherwingBugtracker#6315]
[//]: # (Enclose links to things related to the bug using http://wowhead.com or any other TBC database.)
[//]: # (You can use screenshot ingame to visual the issue.)
[//]: # (Write your tickets according to the format:)
[//]: # ([Quest][Azuremyst Isle] Red Snapper - Very Tasty!)
[//]: # ([NPC] Magistrix Erona)
[//]: # ([Spell][Mage] Fireball)
[//]: # ([Npc][Drop] Ghostclaw Lynx)
[//]: # ([Web] Armory doesnt work)
[//]: # (To find server revision type `.server info` command in the game chat.)

**Description**: Felhunter gaining too little stamina via gear upgrades

**Current behaviour**: I equipped exactly same stamina as the warlock in the video, 813 stamina.
We have same talents for pet scaling, but his pet has 6127 hp, mine has 5944 hp
See video: https://youtu.be/aDGtKZ-xRuo?t=22
Screenshot, 813 stamina https://imgur.com/a/aG1wBZn

**Expected behaviour**: Should gain more stamina

**Server Revision**:

**Comment by Wolffenstein** [comment]
Fixed in rev 3160.
