### ISSUE TITLE
Gladiators Gloves

### ISSUE THREAD

**Issue by Miikell** [Atlantiss/NetherwingBugtracker#6318]
https://www.wowhead.com/item=25834/gladiators-leather-gloves#comments

**Description**: Gladiators gloves cost bad marks 

**Current behaviour**: Gladiators gloves now cost honors + 20 AB mark

**Expected behaviour**: Gladiators gloves should cost honors + 20 AV mark

**Server Revision**: 3142

**Comment by Evolvee** [comment]
fixed in 3143
