### ISSUE TITLE
Deatholme Darkmage#16319 should not flee on low HP & Possibly missing Dr. Whittherlimb#22062

### ISSUE THREAD

**Issue by Tenoutoften** [Atlantiss/NetherwingBugtracker#632]
**Description**: 
Deatholme Darkmage#16319 (https://db.excalibur.ws/?npc=16318) should not flee on low HP. Currently frequently flees on low HP: https://i.gyazo.com/5aec281d2c79f1bdcd9046648373f7cc.png

Ziggurath containing the Stone of Flame
https://youtu.be/hRCp3HHJaJw?t=45
https://youtu.be/kaVmjlTJGcA?t=72
https://youtu.be/qgT0SahSY1U?t=73

Ziggurath containing the Stone of Light
https://youtu.be/qgT0SahSY1U?t=162
https://youtu.be/hRCp3HHJaJw?t=110
https://youtu.be/kaVmjlTJGcA?t=246

I didn't see Dr. Whittherlimb#22062(https://db.excalibur.ws/?npc=22062) either, but that could just have been bad luck, it's a rarespawn. 
http://et.worldofwarcraft.wikia.com/wiki/Dr._Whitherlimb
https://i.gyazo.com/8effc6771679f612e95c0627e57b88d3.png wowhead comment, other comments say he isn't that rare.
https://i.gyazo.com/4e0bebadd558065ff37b60752e6ab941.png
https://i.gyazo.com/b2f64a69342e65232e03507692816f36.png
https://www.wowhead.com/npc=22062/dr-whitherlimb#comments

**Expected behaviour**: 
I expect Deathholme Darkmage#16319 to not flee on low HP.

**Server Revision**: 
2060

**Comment by Evolvee** [comment]
flee removed in rev xdd
Dr Whitherlimb has more spawn points ^^
