### ISSUE TITLE
[NPC][Illidan][BT] No shear animation while soft-enraged

### ISSUE THREAD

**Issue by Stogi7789** [Atlantiss/NetherwingBugtracker#6320]
[//]: # (Enclose links to things related to the bug using http://wowhead.com or any other TBC database.)
[//]: # (You can use screenshot ingame to visual the issue.)
[//]: # (Write your tickets according to the format:)
[//]: # ([Quest][Azuremyst Isle] Red Snapper - Very Tasty!)
[//]: # ([NPC] Magistrix Erona)
[//]: # ([Spell][Mage] Fireball)
[//]: # ([Npc][Drop] Ghostclaw Lynx)
[//]: # ([Web] Armory doesnt work)
[//]: # (To find server revision type `.server info` command in the game chat.)

**Description**: 
When casting his ability shear, Illidan's animation let's him jump up and dart down again. This animation does not happen while soft enraged.
https://db.excalibur.ws/?spell=41032

**Current behaviour**:
While soft enraged the shear animation does not show.
https://www.twitch.tv/videos/488132298?t=17m15s

**Expected behaviour**: 
Every time Illidan casts shear (soft enraged or not) the jump up and dart down animation should show. As it is clearly seen on Nihilums first kill:
https://youtu.be/k8_JbDiALkY?t=1036

**Server Revision**: 
[3142]

**Comment by Godmatik** [comment]
Confirmed - but only occurs if boss is moving while having enrage buff

**Comment by Godmatik** [comment]
Client side, can not be fixed
