### ISSUE TITLE
Bug in Dire Maul dungeon.

### ISSUE THREAD

**Issue by Skwayzer** [Atlantiss/NetherwingBugtracker#6321]
[//]: # (Enclose links to things related to the bug using http://wowhead.com or any other TBC database.)
[//]: # (You can use screenshot ingame to visual the issue.)
[//]: # (Write your tickets according to the format:)
[//]: # ([Quest][Azuremyst Isle] Red Snapper - Very Tasty!)
[//]: # ([NPC] Magistrix Erona)
[//]: # ([Spell][Mage] Fireball)
[//]: # ([Npc][Drop] Ghostclaw Lynx)
[//]: # ([Web] Armory doesnt work)
[//]: # (To find server revision type `.server info` command in the game chat.)

**Description**: My group and I discovered a bug in Dire maul regarding the West dungeon. In the west part of the dungeon there should be a few power pilons that need to be deactivated in order to fight a boss, Immol'thar. And after you kill him, Prince Totheldrin should turn hostile and attack you. (https://classic.wowhead.com/quest=7461/the-madness-within)

**Current behavior**: First problem: there are no pilons but you can fight the boss Immol'tar and kill him. Second Problem is that the Prince does not turn hostile and you still can't attack him as you should when all of the steps above are done. And the third one is there is a quest (The madness within) to kill both of them and it is an automatic fail from the start since you can't kill the Prince in the first place.

**Expected behaviour**: Should have pilons and should make the Prince hostile after killing Immol'thar. (https://classic.wowhead.com/quest=7461/the-madness-within)

**Server Revision**:

**Comment by Evolvee** [comment]
fixed in rev 3145
