### ISSUE TITLE
Halaa guard "missing"

### ISSUE THREAD

**Issue by Kirishiki** [Atlantiss/NetherwingBugtracker#6322]
[//]: # (Enclose links to things related to the bug using http://wowhead.com or any other TBC database.)
[//]: # (You can use screenshot ingame to visual the issue.)
[//]: # (Write your tickets according to the format:)
[//]: # ([Quest][Azuremyst Isle] Red Snapper - Very Tasty!)
[//]: # ([NPC] Magistrix Erona)
[//]: # ([Spell][Mage] Fireball)
[//]: # ([Npc][Drop] Ghostclaw Lynx)
[//]: # ([Web] Armory doesnt work)
[//]: # (To find server revision type `.server info` command in the game chat.)

**Description**:  tryed to go capture halaa but 1 guard aint there to be found. 

**Current behaviour**: they seem to go missing. swallowed by earth or went to holiday somewhere..

**Expected behaviour**: id expect them to stay in halaa and protect it somewhere where u can find them.

**Server Revision**:  fix plz

**Comment by danbopes** [comment]
Next Rev
