### ISSUE TITLE
Brewfest and other world events

### ISSUE THREAD

**Issue by Kirishiki** [Atlantiss/NetherwingBugtracker#6323]
[//]: # (Enclose links to things related to the bug using http://wowhead.com or any other TBC database.)
[//]: # (You can use screenshot ingame to visual the issue.)
[//]: # (Write your tickets according to the format:)
[//]: # ([Quest][Azuremyst Isle] Red Snapper - Very Tasty!)
[//]: # ([NPC] Magistrix Erona)
[//]: # ([Spell][Mage] Fireball)
[//]: # ([Npc][Drop] Ghostclaw Lynx)
[//]: # ([Web] Armory doesnt work)
[//]: # (To find server revision type `.server info` command in the game chat.)

**Description**: was just playing in wotlk server and there was brewfest going and then came to atlantiss to check and there was no brewfest. started googling and if i understood it right , brewfest was added in 2.2.2 patch in tbc that lasted from october 3 to 16 so isnt it supposed to be happening right now?? what about the upcomming halloween event?

**Current behaviour**: no brewfest :(

**Expected behaviour**: enjoy brewfest!

**Server Revision**: id like to know

**Comment by Evolvee** [comment]
known
majority of the seasonal events are disabled cuz we didnt rewrite them and we didnt want to leave them in a shitty stock state that you can see on other servers ^^ until they are rewritten, they will remain disabled
