### ISSUE TITLE
Infernal bugged

### ISSUE THREAD

**Issue by Firstonlogs** [Atlantiss/NetherwingBugtracker#6325]
**Description**: 
Infernal breaking within the first 10 seconds of summon. Happens on multiple bosses like Rage Winterchill, Anetheron, Archimonde and Supremus. Tried to play around it by sending it to attack at once, with a delay, leaving it by my side and staying close to the mob.
**Current behaviour**:
Breaking within 10-20 seconds of summon.
**Expected behaviour**: 
Controlled for 5 minutes as tooltip says.
**Server Revision**:

**Comment by Firstonlogs** [comment]
UPDATE:
It seems to be less of an issue for our affliction warlock which lead me to believe it must be talents / demonic sac. This doesn't make any sense though as i can use the inferno just fine in ZA and out in the world.

It must be either some boss script / raid mechanic that fucks with the infernal. Im sorry i can't be more precise. All the theories i tried testing doesn't add up given how it only breaks in certain situations.

As a final note I'd like to copy the spells text:
An infernal rises from the crater, UNDER THE COMMAND OF THE CASTER FOR 5 MINUTES.

**Comment by Godmatik** [comment]
Must have been fixed at some point, throughout entire Netherwing server never heard of any warlock complain about this, and never seen one break upon summon.

Closing.
