### ISSUE TITLE
Spellcloth Specialization CD

### ISSUE THREAD

**Issue by Vyveva** [Atlantiss/NetherwingBugtracker#6326]
[//]: # (Enclose links to things related to the bug using http://wowhead.com or any other TBC database.)
[//]: # (You can use screenshot ingame to visual the issue.)
[//]: # (Write your tickets according to the format:)
[//]: # ([Quest][Azuremyst Isle] Red Snapper - Very Tasty!)
[//]: # ([NPC] Magistrix Erona)
[//]: # ([Spell][Mage] Fireball)
[//]: # ([Npc][Drop] Ghostclaw Lynx)
[//]: # ([Web] Armory doesnt work)
[//]: # (To find server revision type `.server info` command in the game chat.)

**Description**: After i make Spellcloth(specialization) the Cooldown remaining: 3 Days 19 Hrs but the real time of it is allways whole 4 days. On other server was it correctly. On Primal Mooncloth(not specialization) it says: 3 Days 23 Hrs so it is correct: whole 4 days.

**Current behaviour**: 4 Days CD (exact time) on Specialization

**Expected behaviour**: 3 Days 20 Hrs CD (exact time) on Specialization

**Server Revision**:

**Comment by devo6969** [comment]
92 hours = shadoweave/spellcloth
96 hours = Primal Mooncloth

https://wow.gamepedia.com/Mooncloth_Tailoring
The cooldown on the crafting used to be 96 hours (4 days), and wasn't shared with the cooldowns on the other types of specialized cloth, namely Spellcloth and Shadowcloth. This cooldown has been removed.

https://wowwiki.fandom.com/wiki/Shadoweave_Tailoring
"(Shadoweave)The cooldown on the crafting is 92 hours (nearly 4 days), but it's not shared with the cooldowns on the other types of specialized cloth, namely Primal Mooncloth and Spellcloth

https://wowwiki.fandom.com/wiki/Spellfire_Tailoring
"(Spellcloth) The cooldown on the crafting is 92 hours (3 days, 20 hours), but it's not shared with the cooldowns on the other types of specialized cloth, namely Primal Mooncloth and Shadowcloth. As of Patch 3.0.8 there is no longer a cooldown."

**Comment by Tereneckla** [comment]
https://wowwiki.fandom.com/wiki/Patch_2.4.2

    Professions

    All 23-hour profession cooldowns are now 20-hour cooldowns.
    All 4-day cooldowns are now 3 days, 20 hours.

**Comment by Godmatik** [comment]
Unable to reproduce

Tested all 3 - and all of them are correctly set to 3days 20hr cooldown
