### ISSUE TITLE
[Vanilla]Quests that need to be enabled to upcoming Vanilla Raids and other stuff

### ISSUE THREAD

**Issue by Manaci** [Atlantiss/NetherwingBugtracker#6327]
**Molten Core**
Make sure [Attunement to the Core](https://db.excalibur.ws/?quest=7847)(Horde) [Attunement to the Core](https://db.excalibur.ws/?quest=7848) (Alliance) is enabled. (not sure if there is both a horde and alliance version needed but there's 2 versions on that database)
Hydraxian Waterlords chain quests that needs to be enabled.
[Duke Hydraxis](https://db.excalibur.ws/?npc=13278) starts by giving two quests, [Poisoned Waters](https://db.excalibur.ws/?quest=6804) and [Stormers and Rumblers](https://db.excalibur.ws/?quest=6805). After completing those, you get [Eye of the Emberseer](https://db.excalibur.ws/?quest=6821) into [The Molten Core](https://db.excalibur.ws/?quest=6822) into [Agent of Hydraxis](https://db.excalibur.ws/?quest=6823) (requiring honored reputation with Hydraxian Waterlords) into [Hands of the Enemy](https://db.excalibur.ws/?quest=6824) into the final quest [A Hero's reward](https://db.excalibur.ws/?quest=7486). Something to note here is that once you complete [Hands of the Enemy](https://db.excalibur.ws/?quest=6824), you gain access to the [Aqual Quintessence](https://db.excalibur.ws/?item=17333) needed to summon Ragnaros by talking to [Duke Hydraxis](https://db.excalibur.ws/?npc=13278). When you gain Revered with Hydraxian Waterlords, you can go get a permanent version of that item called an [Eternal Quintessence](https://db.excalibur.ws/?item=22754).
(All the quest IDs: 7847, 7848, 6804, 6805, 6821, 6822, 6823, 6824, 7486)

**Onyxia's Lair**
Enable the Onyxia chain.
**Horde version**
After completing the [For the Horde!](https://db.excalibur.ws/?quest=4974) quest (which is the last quest you can do already), [What the Wind Carries](https://db.excalibur.ws/?quest=6566) opens up into [Champion of the Horde](https://db.excalibur.ws/?quest=6567) into [Mistress of Deception](https://db.excalibur.ws/?quest=6568) into [Oculus Illusions](https://db.excalibur.ws/?quest=6569) into [Emberstrife](https://db.excalibur.ws/?quest=6570). This opens up 3 quests that can be taken at the same time called [The Test of Skulls, Scryer](https://db.excalibur.ws/?quest=6582), [The Test of Skulls, Somnus](https://db.excalibur.ws/?quest=6583) and [The Test of Skulls, Chronalis](https://db.excalibur.ws/?quest=6584). After doing these 3 quests, another one opens up called [The Test of Skulls, Axtroz](https://db.excalibur.ws/?quest=6585) into [Ascension...](https://db.excalibur.ws/?quest=6601) into the final quest [Blood of the Black Dragon Champion](https://db.excalibur.ws/?quest=6602) which awards the [Drakefire Amulet(https://db.excalibur.ws/?item=16309) that allows entry into Onyxia's Lair.
(All the quest IDs: 6566, 6567, 6568, 6569, 6570, 6582, 6583, 6584, 6585, 6601, 6602)
**Alliance version**
Not sure how many quests in their chain are already unlocked, so I'll just post all since it's so small on alliance side anyways.
They start by getting [A Crumpled Up Note](https://db.excalibur.ws/?item=11446) in BRD which leads to the quest [A Crumpled Up Note](https://db.excalibur.ws/?quest=4264) into [A Shred of Hope](https://db.excalibur.ws/?quest=4282) into [Jail Break!](https://db.excalibur.ws/?quest=4322) into [Stormwind Rendezvous](https://db.excalibur.ws/?quest=6402) into [The Great Masquerade](https://db.excalibur.ws/?quest=6403) into [The Dragon's Eye](https://db.excalibur.ws/?quest=6501) into the final quest [Drakefire Amulet](https://db.excalibur.ws/?quest=6502) that awards the same [Drakefire Amulet](https://db.excalibur.ws/?item=16309)
(All the quest IDs: 4264, 4282, 4322, 6402, 6403, 6501, 6502)

**Quel'Serrar chain**
Getting the [Foror's Compendium of Dragon Slaying](https://db.excalibur.ws/?item=18401) from Dire Maul opens up the quest [Foror's Compendium](https://db.excalibur.ws/?quest=7507) that leads into [The Forging of Quel'Serrar](https://db.excalibur.ws/?quest=7508) into the last quest [The Forging of Quel'Serrar](https://db.excalibur.ws/?quest=7509).
(All the quest IDs: 7507, 7508, 7509)

**Onyxia Scale Cloak Quests**
**Horde version**
Getting the [Head of Onyxia](https://db.excalibur.ws/?item=18422) quest stater which starts the quest [Victory for the Horde](https://db.excalibur.ws/?quest=7490) into [For All To See](https://db.excalibur.ws/?quest=7491) and if you're a Leatherworker, it then gives another quest after called [The Journey Has Just Begun](https://db.excalibur.ws/?quest=7493) to learn the recipe [Onyxia Scale Cloak](https://db.excalibur.ws/?spell=19093).
(All the quest IDs: 7490, 7491, 7493)
**Alliance Version**
Getting the [Head of Onyxia](https://db.excalibur.ws/?item=18423) quest stater which starts the quest [Victory for the Alliance](https://db.excalibur.ws/?quest=7495) into [Celebrating Good Times](https://db.excalibur.ws/?quest=7496) and if you're a Leatherworker, it then gives another quest after called [The Journey Has Just Begun](https://db.excalibur.ws/?quest=7497) to learn the recipe [Onyxia Scale Cloak](https://db.excalibur.ws/?spell=19093).
(All the quest IDs: 7495, 7496, 7497)

**Hunter Epic Quest**
Starts by getting the [Ancient Petrified Leaf](https://db.excalibur.ws/?item=18703) in Molten Core from the [Cache of the Firelord](https://db.excalibur.ws/?object=179703) spawned after defeating [Majordomo Executus](https://db.excalibur.ws/?npc=12018).
This item gives the quest called [The Ancient Leaf](https://db.excalibur.ws/?quest=7632) which opens a quest called [An introduction](https://db.excalibur.ws/?quest=7633) which then opens up 3 quests called [Ancient Sinew Wrapped Lamina](https://db.excalibur.ws/?quest=7634), [A Proper Sting](https://db.excalibur.ws/?quest=7635) and [Stave of the Ancients](https://db.excalibur.ws/?quest=7636). 
(All the quest IDs: 7632, 7633, 7634, 7635, 7636)

**Priest Epic Quest**
Starts by getting the [Eye of Divinity](https://db.excalibur.ws/?item=18646) in Molten Core from the [Cache of the Firelord](https://db.excalibur.ws/?object=179703) spawned after defeating [Majordomo Executus](https://db.excalibur.ws/?npc=12018).
Equipping this trinket allows the wearer to see [Eris Havenfire](https://db.excalibur.ws/?npc=14494) in EPL and take the quest [A Warning](https://db.excalibur.ws/?quest=7621) which leads into the quest [A Balance of Light and Shadow](https://db.excalibur.ws/?quest=7622).
(All the quest IDs: 7621, 7622)

**Legendary Quests**
**Sulfuras, Hand of Ragnaros**
When you obtain a [Sulfuron Ingot](https://db.excalibur.ws/?item=17203), you can go to [Lokhtos Darkbargainer](https://db.excalibur.ws/?npc=12944) who will then do some RP and give you a [Thorium Brotherhood Contract](https://db.excalibur.ws/?item=18628) that gives the quest [A Binding Contract](https://db.excalibur.ws/?quest=7604).
**Thunderfury, Blessed Blade of the Windseeker** (did someone just say that?)
When you obtain one of the bindings, either [Bindings of the Windseeker](https://db.excalibur.ws/?item=18563) or [Bindings of the Windseeker](https://db.excalibur.ws/?item=18564), you can obtain the [Vessel of Rebirth](https://db.excalibur.ws/?item=19016) from [Highlord Demitrian](https://db.excalibur.ws/?npc=14347) which starts the quest [Examine the Vessel](https://db.excalibur.ws/?quest=7785) into [Thunderaan the WIndseeker](https://db.excalibur.ws/?quest=7786) into [Rise, Thunderfury!](https://db.excalibur.ws/?quest=7787).
(All the quest IDs: 7604, 7785, 7786, 7787)

**Server Revision**: 
3142

**Comment by Evolvee** [comment]
autism

**Comment by Wolffenstein** [comment]
All fixed.
