### ISSUE TITLE
[Item][Drop] Mount Hyjal waves are missing some epics. 

### ISSUE THREAD

**Issue by MartMlr** [Atlantiss/NetherwingBugtracker#6328]
[//]: # (Enclose links to things related to the bug using http://wowhead.com or any other TBC database.)
[//]: # (You can use screenshot ingame to visual the issue.)
[//]: # (Write your tickets according to the format:)
[//]: # ([Quest][Azuremyst Isle] Red Snapper - Very Tasty!)
[//]: # ([NPC] Magistrix Erona)
[//]: # ([Spell][Mage] Fireball)
[//]: # ([Npc][Drop] Ghostclaw Lynx)
[//]: # ([Web] Armory doesnt work)
[//]: # (To find server revision type `.server info` command in the game chat.)

**Description**: 
As of 2.2 some Items which were only dropping in Black Temple before got moved/added to waves in Mount Hyjal. We are doing MH almost every week since 2.2 and never saw those drop.

**Current behaviour**:
Items are not in any loottable of Mount Hyjals trashmobs.

**Expected behaviour**: 
Following items should drop:

Boots of the Divine Light - ID: 32609
Choker of Serrated Blades - ID: 32591
Nethervoid Cloak - ID: 32590
Hellfire-Encased Pendant - ID: 32589
Chestguard of Relentless Storms - ID: 32592

**Server Revision**:  3142

**Comment by Evolvee** [comment]
fixed
