### ISSUE TITLE
[Arena]

### ISSUE THREAD

**Issue by Shamposik** [Atlantiss/NetherwingBugtracker#6329]
The issue occurs while playing PvP arena and you suddenly get **internet connection lost,** your daily games counters are cleared and arena points for completed daily arena are removed even they were already added

**Steps to reproduce:**
Enter Arena 3x3 
Play 1 game (get ~20 points)
Start Arena 2x2 
Get internet connection lost

**Actual result:** 
Arena points are removed

**Expected result:**
The current game should be counted even if you got disconnected (considered as leaving arena) after start

**Server info:**
Zull'Aman patch. 
Revision 3142

**Comment by tsuone** [comment]
No longer an issue - we don't have this system anymore.
