### ISSUE TITLE
[NPC] Dark Iron Saboteur, Demolitionist, Tunneler

### ISSUE THREAD

**Issue by mbzz88** [Atlantiss/NetherwingBugtracker#633]
**Description**: Spell used by these mobs "Gift of Ragnaros" should add fire damage to next attack
Spell: http://db.hellfire-tbc.com/?spell=7891
Mobs: http://db.hellfire-tbc.com/?npc=1052, http://db.hellfire-tbc.com/?npc=1053, http://db.hellfire-tbc.com/?npc=1054

**Current behaviour**: Spell is used as ranged attack, fire damage hits players at range
![wowscrnshot_092618_175337](https://user-images.githubusercontent.com/43509267/46059947-6c98e180-c1b5-11e8-9c2e-6e20732bd87e.jpg)

**Expected behaviour**: Add fire damage to next melee attack

**Comment by xmesaj2** [comment]
fixed in rev 2081
