### ISSUE TITLE
Bug quest Weaponsmith

### ISSUE THREAD

**Issue by Garok012** [Atlantiss/NetherwingBugtracker#6331]
Hello,I have a problem with blacksmithing.
I've had a blacksmith once and now I'm doing it again but I don't have a quest for weaponsmith.
NPC Borgosh Corebender does not give any Quest. Can you reset Quest to Weaponsmith please?

This is the nameof the quest "The Way of the Weaponsmith"

**Comment by Evolvee** [comment]
contact support via ticket/in discord to remove that quest from you

**Comment by Evolvee** [comment]
https://github.com/Atlantiss/NetherwingBugtracker/issues/2896
