### ISSUE TITLE
quest bugged call [Skywing]  i must follow some thing like a bird and keep him alive till the end there is an elite appear and i shoulde kill him then quest will be complete but no thing has happen quest did not complete or failed

### ISSUE THREAD

**Issue by fierychili** [Atlantiss/NetherwingBugtracker#6333]
[//]: # (Enclose links to things related to the bug using http://wowhead.com or any other TBC database.)
[//]: # (You can use screenshot ingame to visual the issue.)
[//]: # (Write your tickets according to the format:)
[//]: # ([Quest][Azuremyst Isle] Red Snapper - Very Tasty!)
[//]: # ([NPC] Magistrix Erona)
[//]: # ([Spell][Mage] Fireball)
[//]: # ([Npc][Drop] Ghostclaw Lynx)
[//]: # ([Web] Armory doesnt work)
[//]: # (To find server revision type `.server info` command in the game chat.)

**Description**: 

**Current behaviour**:

**Expected behaviour**: 

**Server Revision**:

**Comment by Evolvee** [comment]
it completed just fine for me, need it to be recorded if there is still some problem
