### ISSUE TITLE
[Dungeon]Dire Maul West Pillars Are Not Working

### ISSUE THREAD

**Issue by Manaci** [Atlantiss/NetherwingBugtracker#6334]
**Description**: 
With the latest server update, DM West had its pillars put in, but those pillars are still not working correctly, causing Immol'thar and Prince Tortheldrin to be unbeatable. (unless you use a super smart strategy)

**Current behaviour**:
Due to a wrong number of enemies around the pillars, they are not shutting down when those are all killed. One pillar has only 5 elementals while another pillar has 6 of some random non-elite elementals that should not be there. (it is known that the whole DM zone is kinda bare-bones)

**Expected behaviour**: 
Around each of the 5 pillars there should be 4 [Mana Remnants](https://db.excalibur.ws/?npc=11483) and 4 [Arcane Aberrations](https://db.excalibur.ws/?npc=11480). These should pull in packs of 2, consisting of 2 Mana Remnants and 2 Arcane Aberrations. When all 8 elementals around a pillar have been defeated, the pillar should [shut down](https://www.youtube.com/watch?v=HWO5mmXCA1A&feature=youtu.be&t=2042). Not really sure how this works, found something like [this](https://github.com/lh-server/core/commit/2e656b8fdcdbbd1f07d97fbb8ccef0624b5c4237) which might help. Then this should be the same for all of the 5 pillars in DM West and by shutting down all 5 of them, the big force-field around [Immol'thar](https://db.excalibur.ws/?npc=11496) should vanish so that you can enter and fight him. (There should also be many elementals patrolling around this force-field as well as patrols of big ones with small non-elites around, but that'll be for later)

**Server Revision**: 
3155

**Comment by Evolvee** [comment]
![image](https://user-images.githubusercontent.com/1942409/66687952-e4349400-ec84-11e9-8472-673213a3304c.png)

https://github.com/lh-server/core/commit/2e656b8fdcdbbd1f07d97fbb8ccef0624b5c4237

this checks if creature is alive within 20 yards, literally the worst hackfix way to implement it.. well its mangos, what can u expect

**Comment by Evolvee** [comment]
i reworked it but it wont work anyway because of wolfs core issue, if he fixes the core issue in time before my fix goes live, it will work

**Comment by Evolvee** [comment]
reworked in next rev

**Comment by polygxn** [comment]
Became an issue on 3422 server rev. again. Some pillars have 5 elementals around it, some only 4 makes to unable to get to the last boss.

**Comment by Godmatik** [comment]
Duplicate - Dire Maul right now is stock and needs a full rework, it is on Wolf's to-do list
