### ISSUE TITLE
[Recipe][Felwood] Missing Cooking Recipes

### ISSUE THREAD

**Issue by Randelung** [Atlantiss/NetherwingBugtracker#6335]
[//]: # (Enclose links to things related to the bug using http://wowhead.com or any other TBC database.)
[//]: # (You can use screenshot ingame to visual the issue.)
[//]: # (Write your tickets according to the format:)
[//]: # ([Quest][Azuremyst Isle] Red Snapper - Very Tasty!)
[//]: # ([NPC] Magistrix Erona)
[//]: # ([Spell][Mage] Fireball)
[//]: # ([Npc][Drop] Ghostclaw Lynx)
[//]: # ([Web] Armory doesnt work)
[//]: # (To find server revision type `.server info` command in the game chat.)

Related ticket: https://github.com/Atlantiss/NetherwingBugtracker/issues/1839
I don't know why the previous ticket was closed, but since it's a year old I'm opening a new one.

**Description**: There's two cooking recipes that should be sold by Malygen (A) or Bale (H) that bridge the gap between classic and TBC recipes without learning to fish.
https://tbcdb.com/?item=35564
https://tbcdb.com/?item=35566
They were introduced with patch 2.4 but are missing from the game, thus forcing you to learn fishing to advance to TBC cooking.

**Current behaviour**: Recipe can't be bought. (I checked Bale.)

**Expected behaviour**: Recipe can be bought.

**Server Revision**: 3155

**Comment by danbopes** [comment]
It says why it was closed in the previous ticket...they were added in patch 2.4. Our server currently emulates patch 2.3.

**Comment by Randelung** [comment]
I see. I guess I was confused with the game version saying 2.4.3 and the realm on the homepage saying the same.
![image](https://user-images.githubusercontent.com/3729270/66703161-d841e400-ed0f-11e9-9261-3a5cd9011ca6.png)
I just saw the announcement about 2.3, too.
Thanks for clarifying.
