### ISSUE TITLE
([Quest][Bloodmyst Isle] Ending their World - Unable to complete

### ISSUE THREAD

**Issue by Hunniz** [Atlantiss/NetherwingBugtracker#6336]
**Description**: Killing the final Mob, Elite Demon "Sironas" should mark the quest as completed as long as Demolitionist Legoso is still alive.

**Current behaviour**: When the final elite Mob (Demon Sironas) is attacked, Demolitionist Legoso first plays the death animation and then disappears without taking actual damage. Killing the Demon does not complete the quest.

**Expected behaviour**: Demolitionist Legoso should not disappear for no apparent reason.

**Server Revision**: 3155

**Comment by devo6969** [comment]
This quest appears to be fixed. Credit is given once the RP is done after killing Sironas.
Retail MoP - https://youtu.be/lARzK9CLu24?t=556
PTR - https://youtu.be/KwKJaXzc81s?t=249
