### ISSUE TITLE
List of guild members, some members are not visible.

### ISSUE THREAD

**Issue by fonifoni** [Atlantiss/NetherwingBugtracker#6337]
**Description**: 
Guild "Horde".
List of guild members, some members are not visible.(online and offline)
All members have a problem.

**Server Revision**: 3155

**Comment by danbopes** [comment]
Trim down to less than 500 members. Client has hard limit, and will only populate up to 500 players. This is mentioned in numerous wow posts. If you want to keep these members, to manage these excess members, you'll need to use chat commands.
