### ISSUE TITLE
Raptor Rib

### ISSUE THREAD

**Issue by Arisatheus** [Atlantiss/NetherwingBugtracker#6338]
Raptor Ribs from the Raptors in Blade's Edge Mountains have very low drop rate. They should be %50 chance to drop, it takes years to complete a cooking daily at the moment.

**Comment by Evolvee** [comment]
its around 30% which is exactly as it should be http://web.archive.org/web/20070824210912/http://www.thottbot.com/i31670

**Comment by Evolvee** [comment]
idk where u came up with 50%
