### ISSUE TITLE
[Quest] Hunter Epic Chain Bugs

### ISSUE THREAD

**Issue by Manaci** [Atlantiss/NetherwingBugtracker#6339]
[Stoma the Ancient](https://db.excalibur.ws/?npc=14525) is currently not in the game, making it impossible to take the quest [A Proper Sting](https://db.excalibur.ws/?quest=7635).

[Artorius the Amiable](https://db.excalibur.ws/?npc=14531) cannot be turned into his demon form called [Artorius the Doombringer](https://db.excalibur.ws/?npc=14535)  when you talk to him while on the quest [Stave of the Ancients](https://db.excalibur.ws/?quest=7636).

[Franklin the Friendly](https://db.excalibur.ws/?npc=14529) cannot be turned into his demon form called [Klinfran the Crazed](https://db.excalibur.ws/?npc=14534)  when you talk to him while on the quest [Stave of the Ancients](https://db.excalibur.ws/?quest=7636).

[Nelson the Nice](https://db.excalibur.ws/?npc=14536) cannot be turned into his demon form called [Solenor the Slayer](https://db.excalibur.ws/?npc=14530)  when you talk to him while on the quest [Stave of the Ancients](https://db.excalibur.ws/?quest=7636).

[Simone the Inconspicuous](https://db.excalibur.ws/?npc=14527) cannot be turned into his demon form called [Simone the Seductress](https://db.excalibur.ws/?npc=14533)  when you talk to him while on the quest [Stave of the Ancients](https://db.excalibur.ws/?quest=7636).

**Server Revision**: 
3155

**Comment by Evolvee** [comment]
fixed in next rev
