### ISSUE TITLE
The Dead Scar missing Deathcage Sorcerer#16308 patrols

### ISSUE THREAD

**Issue by Tenoutoften** [Atlantiss/NetherwingBugtracker#634]
**Description**: 
Deathcage Sorcerer#16308(https://db.excalibur.ws/?npc=16308) are suppose to patrol The Dead Scar:
https://youtu.be/RdP_FuR9WFw?t=114

Currently they just sit around on their spots. It makes sense that these should patrol as the slightly more north place in The Dead Scar also had patrols, which is lower level, this being a higher level place shouldn't be this lifeless. Here for my report on the more northern The Dead Scar missing patrols: https://github.com/Atlantiss/NetherwingBugtracker/issues/496

**Expected behaviour**: 
I expect Deathcage Sorcerer's#16308 to be patrolling it's respectable region of The Dead Scar.

**Server Revision**: 
2060

**Comment by aresbrutus** [comment]
Fixed in one of the next updates.
