### ISSUE TITLE
[Talent][Warlock]Demonic Knowledge

### ISSUE THREAD

**Issue by GitHubTheySaid** [Atlantiss/NetherwingBugtracker#6340]
https://imgur.com/gallery/Ao5ttTM

Description:  Demonic Knowledge ||| Rank 3 Instant ||| Increases your spell damage by an amount equal to 12% of the total of your active demon's Stamina plus Intellect. 

Current behaviour: Currently increases your spell damage by an amount equal to 12% of the total of your active demon's Stamina without Intellect. 

Expected behaviour: Should increases your spell damage by an amount equal to 12% of the total of your active demon's Stamina plus Intellect. 

Server Revision: 3155

**Comment by Wolffenstein** [comment]
Fixed in rev 3159.
