### ISSUE TITLE
[NPC] Vixton Pinchwhistle) Wrong price for Gladiator's Mail Helm

### ISSUE THREAD

**Issue by Brovakles** [Atlantiss/NetherwingBugtracker#6341]
**Description**: 
Vixton Pinchwhistle, S1 arena vendor from Area 52, have wrong price for Gladiator's Mail Helm. At this moment it is 14500 Honor Points and 30 Arathi Basin Marks. Instead of AB marks, it should have been 30 Alterac Valley marks. Price for other two Shamans S1 Helms are correct.

**Current behaviour**:
Vixton Pinchwhistle sells Gladiator's Mail Helm for 14500 HP and 30 AB Marks.

**Expected behaviour**: 
Vixton Pinchwhistle  should sell Gladiator's Mail Helm for 14500 HP and 30 AV Marks.

**Server Revision**: 3155

https://tbc-twinhead.twinstar.cz/?item=27471
http://tbc.cavernoftime.com/npc=20278#sells:50+1

**Comment by Evolvee** [comment]
fixed
