### ISSUE TITLE
Weekly arena cap! arena points not given!

### ISSUE THREAD

**Issue by glocan** [Atlantiss/NetherwingBugtracker#6342]
**Description**: 
Arena weekly cap is not working for me 2 weeks in a row now!

**Current behaviour**:
Reciving zero points on weekly reset at monday.

**Expected behaviour**: 
Get weekly arena points at monday.

**Server Revision**: 3155

**Comment by lyubomeer** [comment]
Are you sure the team played at least 10 games and you have at least 30% played?

**Comment by Godmatik** [comment]
Never heard of issue about this in current realm, points always distributed properly, unless they didn't play 30% of the games.

Can close
