### ISSUE TITLE
[Quest] Arelion's Mistress

### ISSUE THREAD

**Issue by nightwica** [Atlantiss/NetherwingBugtracker#6343]
This used to work until like last week but now it is bugged again.

Description: When doing the quest, the NPC Viera Sunwhisper will not move her spot when given the quest item Cenarion Spirits.

Current behaviour: Viera does not move from her spot.

Expected behaviour: Viera will move and lead you to an excluded spot to use the other quest item Carinda's Scroll of Retribution.

Server Revision:

**Comment by danbopes** [comment]
Dupe #5604

**Comment by nightwica** [comment]
Sorry for basically posting a duplicate but it was from April and this quest worked up until last week and I didn't know how I can bump that or something.
