### ISSUE TITLE
[Paladin][Quest] True Masters of the Light - Not completed?

### ISSUE THREAD

**Issue by Nasblo** [Atlantiss/NetherwingBugtracker#6344]
**Description**: I entered the side entrance of Stratholme, in party with another player, using the [Key to the City]. We eliminated the mobs in front of the chapel and the boss, then I went inside the chapel and burnt it using the vial. The NPC inside animated and attacked us. Soon after, other NPCs (elite) spawned. This should all normally happen.
We then died during the fight, came back inside the dungeon, and finished the remaining NPCs. At this point, the quest should be completed, according to multiple sources I checked online, as videos and guides. However the quest still shows "Not completed" as of now. I tried waiting for a bit, or logging out/in again, but nothing changed. 
This is quite bad for me because I invested all my gold in this quest, and this should be the final step after which I get the mount, but I remained without gold and mount.
Thank you for your time. If it helps, this happened yesterday at around 7 pm CET, and my IGN is Nasblo.

**Comment by The14me** [comment]
Related https://github.com/Atlantiss/NetherwingBugtracker/issues/5236 And Confirmed, sadly can't reproduce it so far.
