### ISSUE TITLE
[quest][BEM]Showdown - Broken Again

### ISSUE THREAD

**Issue by jasondilltx** [Atlantiss/NetherwingBugtracker#6345]
[Showdown] : https://tbc-twinhead.twinstar.cz/?quest=10742

**Description**: not functioning.  no action upon using the battle horn quest item

**Current behaviour**: no response to using quest item

**Expected behaviour**: goc and rexxar both appear and fight

**Server Revision**:

**Comment by Evolvee** [comment]
this is caused by a core issue that we are experiencing now, will be fixed asap
