### ISSUE TITLE
[Event][Core] Shartuul Transporter

### ISSUE THREAD

**Issue by bekonja** [Atlantiss/NetherwingBugtracker#6346]
[//]: # (Enclose links to things related to the bug using http://wowhead.com or any other TBC database.)
[//]: # (You can use screenshot ingame to visual the issue.)
[//]: # (Write your tickets according to the format:)
[//]: # ([Quest][Azuremyst Isle] Red Snapper - Very Tasty!)
[//]: # ([NPC] Magistrix Erona)
[//]: # ([Spell][Mage] Fireball)
[//]: # ([Npc][Drop] Ghostclaw Lynx)
[//]: # ([Web] Armory doesnt work)
[//]: # (To find server revision type `.server info` command in the game chat.)

**Description**: BEM Shartuul Transporter event
https://www.youtube.com/watch?v=Cvmn5NIs4b0

**Current behaviour**: 
Demons that are controlled by player or summoned by event can interact with other players.
Demons that are controlled by player or summoned by event can interact with other NPCs.
Player that using Shartuul Transporter can use his abilities.
Player that using Shartuul Transporter builds threat on summoned demons and can overaggro them.

**Expected behaviour**: 
None above. Player that using transporter should be completely phased out and unable to use anything. Demons that are part of the event also shouldnt be able to interact with anything but themselves.

**Server Revision**: 
3155

**Comment by hederob** [comment]
Can we make the Shartuul's transporter event closer to what is in this video:

https://www.youtube.com/watch?v=Cvmn5NIs4b0


Everything seems to do a lot less damage in the video and it's soloable. It's nearly impossible to do it now as that the ice block doesn't reflect any damage.

**Comment by Evolvee** [comment]
for sure! all you have to do is to make Wolf fix core issues with it

**Comment by Godmatik** [comment]
Closing - consolidating all information into one thread
