### ISSUE TITLE
[NPC][Loot] Dust Devil

### ISSUE THREAD

**Issue by Kaini27** [Atlantiss/NetherwingBugtracker#6348]
[//]: # (Enclose links to things related to the bug using http://wowhead.com or any other TBC database.)
[//]: # (You can use screenshot ingame to visual the issue.)
[//]: # (Write your tickets according to the format:)
[//]: # ([Quest][Azuremyst Isle] Red Snapper - Very Tasty!)
[//]: # ([NPC] Magistrix Erona)
[//]: # ([Spell][Mage] Fireball)
[//]: # ([Npc][Drop] Ghostclaw Lynx)
[//]: # ([Web] Armory doesnt work)
[//]: # (To find server revision type `.server info` command in the game chat.)

**Description**: NPC ID: 832
**Current behaviour**: Elementals in Westfall named "Dust Devil" has more then 50% chance oh having empty loot window. Even tho you can loot it- loot window is empty most of the times.

My guess is that it drops quest starting item for opposite faction which leads to empty loot table for mine faction. Might be a global issue with also some other NPCs having same loot table issues.

**Expected behaviour**: If corpse is lootable (its shiny and cursor changes to bag icon) it should have some kind of loot inside.

**Server Revision**: 3157

**Comment by devo6969** [comment]
Could not recreate on the PTR. It was either "lootable" with loot on it, or not lootable at all.
