### ISSUE TITLE
[NPC][Quest] Dragonmaw Transporter - The Not-So-Friendly Skies...

### ISSUE THREAD

**Issue by Kaini27** [Atlantiss/NetherwingBugtracker#6349]
**Description**: NPC ID: 23188

**Current behaviour**: Dragonmaw Transporters stoped patrolling recently after some patch and they are stuck at their spawn location

**Expected behaviour**: They should fly around as they use to do it until recenlty (3-5 days ago)

**Server Revision**: 3157

**Comment by Evolvee** [comment]
fixed in rev 3175 @Wolffenstein but this is a core issue - hackfixed it by adding small delay before starting wp
![image](https://user-images.githubusercontent.com/1942409/67601837-9edc9000-f775-11e9-8e9a-4ec46b3af366.png)
