### ISSUE TITLE
Luzran#16245 incorrect patrol, should patrol The Dead Scar

### ISSUE THREAD

**Issue by Tenoutoften** [Atlantiss/NetherwingBugtracker#635]
**Description**: 
https://www.wowhead.com/npc=16245/luzran#comments
https://www.wowhead.com/npc=16245/luzran#comments:id=129093 - Patch 2.1.3

> Luzran spawns at "The Bleeding Ziggurat" @ aprox. 34,50
> He then paths South to North in the scar walking back and forth.
> 
> As of this writing once he is killed he respawns quite quickly. Hybrid classes(Paladin, Shaman, Druid) should be able to solo him @ lvl 20. Other classes will want to have a healer handy.
> 
> Abilities noticed during the fight were a knockback.

From quest Spinal Dust wowhead comments:
https://www.wowhead.com/quest=9218/spinal-dust#comments:id=24604:reply=318214

> Also while grinding out on these mobs be careful of Luzran who every 8 minutes or so (don't have exact timing) comes, a level 21 elite.

https://www.wowhead.com/quest=9218/spinal-dust#comments:id=194564 - Patch 2.3.0
> be careful when pulling, if Luzran is next to a mob you pull, he'll come too and make your life miserable.

https://www.wowhead.com/quest=9218/spinal-dust#comments:id=72857 - Patch 2.0.12

> This was a good quest. I soloed it at lvl 17 on my bloodelf mage. The drop rate was typical for me. The Spinal Dust dropped every 2-4 kills off of Dreadbone Sentinels and it dropped off a few Deathcage Sorcerers too. I found these mobs in the Dead Scar west of the Andilien Estate. And yes, do watch out for Luzran, he's quite a pain and although he is fat and moves slow he'll sneak up on ya and whack u down in no time. GL and have fun!
> 
> ~Kristalhart, Dragonblight server

**Current behaviour**:
Seems to be patrolling roads and around Windrunner Village according to other people. Never enters The Dead Scar, I've been here for over an hour and never seen him.

**Expected behaviour**: 
Expected to spawn near the Bleeding Ziggurat(34,50) and patrol up and down The Dead Scar

**Server Revision**: 
2060

**Comment by aresbrutus** [comment]
Corrected in one of the next updates.

**Comment by Tenoutoften** [comment]
Good job
