### ISSUE TITLE
[Quest] Garments of the Moon

### ISSUE THREAD

**Issue by The14me** [Atlantiss/NetherwingBugtracker#6350]
**Current behaviour**: You use Lesser Heal (Rank 2) + Power Word: Fortitude and never happen.
Missing the RP and everything.

**Expected behaviour**: 
https://youtu.be/LO6SoEjz87g?t=71
https://classic.wowhead.com/quest=5621/garments-of-the-moon

**Server Revision**:

**Comment by Evolvee** [comment]
works fine for me

![image](https://user-images.githubusercontent.com/1942409/67602330-a3ee0f00-f776-11e9-9b47-25bf8ac0577e.png)


u did something wrong

**Comment by Evolvee** [comment]
oh i know why its core issue
