### ISSUE TITLE
[Core] Automatic quest tracker displays the incorrect number of quest items obtained.

### ISSUE THREAD

**Issue by Moryjani** [Atlantiss/NetherwingBugtracker#6351]
**Description**: 
Picking up a Quest item shows 1 less item than the player actually got in his or her inventory.

**Current behaviour**:
Whenever a quest item is picked up if automatic tracking is enabled, the automatic quest tracker appears and shows one item less than what the player actually has in the inventory. For example if you pick up your first Sunfury Signet, the automatic quest tracker will appear and display "0/10 Sunfury Signets", even though there is 1 in your inventory.

**Expected behaviour**: 
The automatic quest tracker should display the correct number of quest items.

**Server Revision**: 
Revision 3157

We suspect that this is due to the order how the server updates quests and items, the server probably updates the quest first and then adds the item to the inventory, causing the automatic quest tracking to use the incorrect local value.

**Comment by Evolvee** [comment]
this "bug" is present ever since i started on privates in 2009

maybe its a client bug tbh

**Comment by natiewow** [comment]
This issue has been resolved in cmangos. It is indeed server-side.

https://github.com/cmangos/issues/issues/1244

**Comment by Wolffenstein** [comment]
Fixed in rev 3194.

**Comment by natiewow** [comment]
This has reverted back to broken state :( Please reopen.

![bug](https://i.imgur.com/6BvKYjW.jpeg)

**Comment by Wolffenstein** [comment]
Fixed in rev 3736.
