### ISSUE TITLE
([Item] Thick Felsteel Necklace) Stamina buff is removed when shapeshifting

### ISSUE THREAD

**Issue by mcmaistro** [Atlantiss/NetherwingBugtracker#6352]
**Description**: Item ID: 24106

**Current behaviour**: Gives the group a +20 stamina buff for 30 minutes or until death, however the buff is removed from the druid and the entire group when entering bearform/catform. 

**Expected behaviour**: Expected to give the group a +20 stamina buff. The buff should drop off after 30 minutes, removal of the neck or until death. 

**Server Revision**: 3157

**Comment by Wolffenstein** [comment]
The item has SPELL_ATTR0_NOT_SHAPESHIFT attribute, which makes it unusable while shapeshifted as well as getting cancelled if you shapeshift, which is in line with other, similar items/abilities. If you find proof that it should persist I will hackfix it not disappear, but for now that is by default proper behaviour.
