### ISSUE TITLE
Flying though buildings

### ISSUE THREAD

**Issue by cathabv** [Atlantiss/NetherwingBugtracker#6353]
Just took the flight from desolace (alli) to tenaris, and on the way in theramore I just flew through both walls and buildings. 

Also, side note, not sure if I've only noticed now or its always been bad, but especially in Nagrand I noticed a lot of mobs just "floating" on the ground/under the ground/above the ground. Last mob of the talbuk mastery quest (bach'lor?)together with his pack for instance on parts of his route.

**Comment by Godmatik** [comment]
Took the flight from Nijel's to Tanaris - watched it the entire time - never saw my character going through walls or buildings in Theramore.
