### ISSUE TITLE
Omor's Hoof

### ISSUE THREAD

**Issue by Kokonat137** [Atlantiss/NetherwingBugtracker#6357]
[//]: # (Enclose links to things related to the bug using http://wowhead.com or any other TBC database.)
[//]: # (You can use screenshot ingame to visual the issue.)
[//]: # (Write your tickets according to the format:)
[//]: # ([Quest][Azuremyst Isle] Red Snapper - Very Tasty!)
[//]: # ([NPC] Magistrix Erona)
[//]: # ([Spell][Mage] Fireball)
[//]: # ([Npc][Drop] Ghostclaw Lynx)
[//]: # ([Web] Armory doesnt work)
[//]: # (To find server revision type `.server info` command in the game chat.)

**Description**: Yesterday I've done the Ramparts for the quest "Weaken the Ramparts" but, once beated Omor, i was not able to loot the corpe and take the hoof for the quest. So i can't complete the quest 

**Current behaviour**:

**Expected behaviour**: 

**Server Revision**:

**Comment by ccueto36** [comment]
Were you dead when the boss died? I had a group yesterday that tank druid died during fight and he didn't get the option to roll on boss loot at all and thus he didn't get any loot.
