### ISSUE TITLE
[Quest] Captain Sander's Hidden Treasure

### ISSUE THREAD

**Issue by Tereneckla** [Atlantiss/NetherwingBugtracker#6358]
[//]: # (Enclose links to things related to the bug using http://wowhead.com or any other TBC database.)
[//]: # (You can use screenshot ingame to visual the issue.)
[//]: # (Write your tickets according to the format:)
[//]: # ([Quest][Azuremyst Isle] Red Snapper - Very Tasty!)
[//]: # ([NPC] Magistrix Erona)
[//]: # ([Spell][Mage] Fireball)
[//]: # ([Npc][Drop] Ghostclaw Lynx)
[//]: # ([Web] Armory doesnt work)
[//]: # (To find server revision type `.server info` command in the game chat.)

**Description**: https://classicdb.ch/?quest=136

**Current behaviour**: The quest and followups are not available for horde players.

**Expected behaviour**: They should be

**Server Revision**: 3157

**Comment by Evolvee** [comment]
any evidence it should?

**Comment by Manaci** [comment]
[Wowhead comments](https://www.wowhead.com/item=1357/captain-sanders-treasure-map#comments), [EveryQuest Addon](), [Wowwiki lists it as a neutral quest](https://wowwiki.fandom.com/wiki/Quest:Captain_Sanders%27_Hidden_Treasure), [Old Guide](https://www.ownedcore.com/forums/world-of-warcraft/world-of-warcraft-guides/246619-captain-sanders-treasure.html)

**Comment by Evolvee** [comment]
wowhead:

![image](https://user-images.githubusercontent.com/1942409/67604312-8c655500-f77b-11e9-9a7f-4049bfd0fb56.png)
![image](https://user-images.githubusercontent.com/1942409/67604314-8ec7af00-f77b-11e9-8093-13433775170d.png)

**Comment by Evolvee** [comment]
rev 3175
