### ISSUE TITLE
[NPC] Captain Saeed - No way to start event to complete quest.

### ISSUE THREAD

**Issue by bastian626** [Atlantiss/NetherwingBugtracker#6359]
[//]: # ([Quest][Netherstorm] Dimensius the All-Devouring)
[//]: # ([NPC] Captain Saeed)
Description:
https://www.wowhead.com/quest=10439/dimensius-the-all-devouring
https://www.wowhead.com/npc=20985/captain-saeed

Current behaviour: Talking to Captain doesn't open a dialog option to start the event.

Expected behaviour: Talking to Captain  open a dialog option to start the event.

**Comment by danbopes** [comment]
Dupe #6305

**Comment by bastian626** [comment]
> Dupe #6305
Oh, i saw the report didn't
 see the fix was on progress.

Ty (at the begining didnt stood why closed my report)
