### ISSUE TITLE
XP from ?? level mobs

### ISSUE THREAD

**Issue by mbzz88** [Atlantiss/NetherwingBugtracker#636]
**Description**: Not sure if this is related to these specific mobs, but killing Lingering Highborne, Highborne Apparition and Highborne Lichling resulted in 0 XP gained. Level 46-50 mobs as level 30 player. 100% player damage, 0% pet damage.
http://db.hellfire-tbc.com/?npc=7864
http://db.hellfire-tbc.com/?npc=6116
http://db.hellfire-tbc.com/?npc=6117

**Current behaviour**: 0 XP gained on kill.

**Expected behaviour**: XP gained should be equivalent to an "orange" level mob (I think)

**Comment by Tereneckla** [comment]
Can't find anything that says you shouldn't get experience either.

**Comment by Evolvee** [comment]
no idea why this happens only to these 3 mobs, or is it all npcs with "??" level?

**Comment by Evolvee** [comment]
@Tereneckla

**Comment by Evolvee** [comment]
@Wolffenstein @danbopes global thign, all "??" mobs give no xp KEKW

**Comment by Wolffenstein** [comment]
Fixed in rev 3360.
