### ISSUE TITLE
[Quest] "The Calling" quest does not have the followup"Armaments of War" quest

### ISSUE THREAD

**Issue by Manaci** [Atlantiss/NetherwingBugtracker#6361]
**Current behaviour**:
When completing [The Calling](https://db.excalibur.ws/?quest=8315) and watching the 5 min RP, there is no followup quest.
**Expected behaviour**: 
There should be a followup quest based on the player's class called "Armaments of War":
[Warrior](https://db.excalibur.ws/?quest=8316)
[Paladin](https://db.excalibur.ws/?quest=8376)
[Rogue](https://db.excalibur.ws/?quest=8378)
[Priest](https://db.excalibur.ws/?quest=8379)
[Mage/Warlock](https://db.excalibur.ws/?quest=8381)
[Hunter](https://db.excalibur.ws/?quest=8377)
[Shaman](https://db.excalibur.ws/?quest=8380)
[Druid](https://db.excalibur.ws/?quest=8382)

**Server Revision**: 
3157

**Comment by Evolvee** [comment]
rev 3175
