### ISSUE TITLE
[core] Aoe Channeled spells dont show the first damage tic into stealthed units

### ISSUE THREAD

**Issue by Evolvee** [Atlantiss/NetherwingBugtracker#6362]
tldr
Rogue has stealth, you cast blizzard on him, stealth breaks, dmg is taken but caster of the blizzard does not see this tic, therefore it may seem like the blizzard broken stealth before any dmg was even done. From rogue PoV, the stealth breaks correctly after dmg taken.

**Comment by Wolffenstein** [comment]
Rev 3171
