### ISSUE TITLE
Enchant Boots - Dexterity Not Applying additional Agility to all items

### ISSUE THREAD

**Issue by EyStan** [Atlantiss/NetherwingBugtracker#6363]
**Description**: The item "Boots of Effortless Striking" should have 54 agility on it (42 base plus 12 from Enchant Boots: Dexterity). Coincidentally, my other boots, "Edgewalker Longboots", also have 54 agility (29 base, 12 from Enchant Boots: Dexterity, and 13 from gems). When I swap these items, however, the "Boots of Effortless Striking" give me 12 less agility than the "Edgewalker Longboots". See the attached screenshots for proof.

![WoWScrnShot_102219_124229](https://user-images.githubusercontent.com/55593238/67528736-6a82aa00-f677-11e9-8244-6289e86e2f8d.jpg)
![WoWScrnShot_102219_124237](https://user-images.githubusercontent.com/55593238/67528737-6a82aa00-f677-11e9-95a3-f7ffc837a61b.jpg)

**Current behaviour**: +12 Agility from Enchant Boots: Dexterity not applying to item "Boots of Effortless Striking"

**Expected behaviour**: +12 Agility from Enchant Boots: Dexterity should apply to item "Boots of Effortless Striking"

**Comment by Wolffenstein** [comment]
It's working fine. Are you sure you're not losing any meta bonuses by taking out the socketed boots?

**Comment by EyStan** [comment]
Well, I'm dumb. You're right, sorry Wolf.
