### ISSUE TITLE
[Hunter][Frost trap] It stops working if use it after Bestial Wrath

### ISSUE THREAD

**Issue by Arclitee** [Atlantiss/NetherwingBugtracker#6364]
**Description: Frost trap not working under specific conditions. 
------------------------------------------------------------------------------
**Current behaviour: This bug happens under 2 situations: 

1.- Uses Bestial Wrath, then set the trap and make someone step into it. People will become immune to his slowing effect. This one its most likely to happen

2.- Set the trap, uses Bestial Wrath, then get someone step into it, it ll become immune to the trap, even with the slow debuff on

-------------------------------------------------------------------------------

**Expected behaviour**: Bestial wrath shouldnt be making other ppl immune to frost trap

**Comment by Arclitee** [comment]
With that bug, BM hunters really sucks against melees.

**Comment by Manaci** [comment]
Can vouch for this, checked and ran into the same problems.

**Comment by Wolffenstein** [comment]
Fixed in rev 3172.
