### ISSUE TITLE
cant loot chest in heroic ramparts

### ISSUE THREAD

**Issue by dideymage** [Atlantiss/NetherwingBugtracker#6365]
[//]: # (Enclose links to things related to the bug using http://wowhead.com or any other TBC database.)
[//]: # (You can use screenshot ingame to visual the issue.)
[//]: # (Write your tickets according to the format:)
[//]: # ([Quest][Azuremyst Isle] Red Snapper - Very Tasty!)
[//]: # ([NPC] Magistrix Erona)
[//]: # ([Spell][Mage] Fireball)
[//]: # ([Npc][Drop] Ghostclaw Lynx)
[//]: # ([Web] Armory doesnt work)
[//]: # (To find server revision type `.server info` command in the game chat.)

**Description**:  
I cant loot the chest after last boss in heroic ramparts. this has been going on for the past 3 days. 

**Current behaviour**:
says invalid target 

**Expected behaviour**: 
should be able to loot badge of justice

![invalid 1](https://user-images.githubusercontent.com/56760173/67558724-cd2b8280-f717-11e9-938b-a28ccaf68f07.jpg)
![invalid 2](https://user-images.githubusercontent.com/56760173/67558734-d3216380-f717-11e9-81d2-ed4c0138cfd3.jpg)
**Server Revision**:

**Comment by hederob** [comment]
There's always been an issue with this chest since the start.
