### ISSUE TITLE
[Spell][Shaman] Earth Elemental Totem

### ISSUE THREAD

**Issue by Healweed** [Atlantiss/NetherwingBugtracker#6366]
**Description**: 
There are quite a bunch of issues with the Earth Elemental Totem which makes Earth Elemental VERY unreliable and useless. This is the bugs i have found so far (hopefully there's no more bugs about this spell)

**Current behaviour**:
1st:  Earth Elemental gained HP from shaman % HP is not applying when being summoned

2nd: Earth Elemental at this moment is immune to all Shaman healing spells

3rd: Earth Elemental is VERY squishy, even fighting 2-3 mobs 10-15levels below him. (I'ma need to test thoroughly to see if the base stats are bugged or not) 

4th: Earth Elemental level is 66 when summoned, which shouldn't be

**Expected behaviour**: 
1st: Earth Elemental does not get  a percentage of its master’s stamina (This was a buff from patch 2.1 retail)
https://wowwiki.fandom.com/wiki/Earth_Elemental_Totem

>This pet will now come into the game with full health, including that gained from a percentage of its master’s stamina.

2nd: Earth Elemental shouldn't be  immune to Shaman healing spells, which shouldn't. The elemental is only immune to all nature type damage.
https://www.wowhead.com/forums&topic=147449

> The Earth Elemental has more HP (I'm sure) than the Fire Elemental so is suitable for backup tanking. It can also be healed.

3rd: Earth Elemental should not have any issues when fighting 2-3 mobs which are 10-15levels below him.(I'ma need to test thoroughly to see if the base stats are bugged or not) 

4th: Like Fire Elemental, Earth Elemental is supposed to be summoned with the same level as shaman's level. 

**Server Revision**: 
Currently, the server revision is **3157**.

**Comment by Wolffenstein** [comment]
Fixed in rev 3173.
