### ISSUE TITLE
[Core] [On-Next-Swing] On-next-swing abilities should cause offhand attacks to ignore dual wield hit penalty.

### ISSUE THREAD

**Issue by Easyfraggy** [Atlantiss/NetherwingBugtracker#6367]
**Description**: 
On-next-swing abilities should cause offhand attacks to ignore dual wield hit penalty.

![image](https://user-images.githubusercontent.com/36134067/67607397-a8212900-f784-11e9-987f-f6ce03b381d6.png)
https://us.forums.blizzard.com/en/wow/t/wow-classic-not-a-bug-list/175887

![image](https://user-images.githubusercontent.com/36134067/67607355-888a0080-f784-11e9-8b46-c88b81aa1a0a.png)

Retail video - note 0 misses when HS is toggled.
https://www.youtube.com/watch?v=p2Hq2zVB6ZE&t=34s

**Current behaviour**:
On-next-swing abilities have no impact on your offhand attacks.

**Expected behaviour**: 
Your offhand should ignore dual-wield hit penalty while an on-next-hit attack is queued.

**Server Revision**: Any

**Comment by Easyfraggy** [comment]
Edited to clarify that it is only the dual wield hit penalty that is affected.

**Comment by Wolffenstein** [comment]
Fixed in rev 3178.
