### ISSUE TITLE
[Fishing] Skill ups don't work like they should

### ISSUE THREAD

**Issue by aeturnum** [Atlantiss/NetherwingBugtracker#6368]
**Description**: 
Fishing on retail wow worked based on one skillup per a set number of catches (initially one skill per catch, then one every other catch and so on). Fishing on netherwing does not appear to work in that way.

**Current behaviour**:
You do not gain skills at predictable intervals, but appear to gain it probabilisticly like you do with other skills. 

Screenshot from me fishing around 160 skill: https://i.imgur.com/IhqQzmR.jpg

**Expected behaviour**: 
You would consistently gain skill similar to this table:
https://wowwiki.fandom.com/wiki/Fishing#Approximate_skill_up_table

In the screenshot I would expect to gain a skill point every third fish caught
**Server Revision**: 
3174

**Comment by Tereneckla** [comment]
![image](https://user-images.githubusercontent.com/50233983/71772872-65818700-2f53-11ea-8a3f-1594dbd25d8d.png)
The fishing guide wowwiki references speaks of the skillups being random.
