### ISSUE TITLE
[PVP][Core] Lifebloom stacks on cycloned target

### ISSUE THREAD

**Issue by bekonja** [Atlantiss/NetherwingBugtracker#6369]
[//]: # (Enclose links to things related to the bug using http://wowhead.com or any other TBC database.)
[//]: # (You can use screenshot ingame to visual the issue.)
[//]: # (Write your tickets according to the format:)
[//]: # ([Quest][Azuremyst Isle] Red Snapper - Very Tasty!)
[//]: # ([NPC] Magistrix Erona)
[//]: # ([Spell][Mage] Fireball)
[//]: # ([Npc][Drop] Ghostclaw Lynx)
[//]: # ([Web] Armory doesnt work)
[//]: # (To find server revision type `.server info` command in the game chat.)

**Description**: 

**Current behaviour**:
Apperantly you can refresh lifebloom stack on a target that is cycloned. Wasnt like that 3 days ago or so.
**Expected behaviour**: 
Cycloned target should be invulnerable to most of auras including lifebloom,
**Server Revision**: 
3174

**Comment by Evolvee** [comment]
did you test it yourself?

**Comment by bekonja** [comment]
Not really, i noticed it happened on arena. First i thought im seing things or it some 1 out of 1000 occasion, but then one of my guildies also reported that his druid can refresh LBs on cycloned target. Needs proper testing.

**Comment by Wolffenstein** [comment]
Fixed in rev 3179.
