### ISSUE TITLE
[core] aoe spells - core

### ISSUE THREAD

**Issue by Evolvee** [Atlantiss/NetherwingBugtracker#6370]
26029
my favourite spell to kill mobs stopped working recently. it used to kill everything in front of you
now you cast it 30 times and nothing happens, sometimes it kills 1 random npc

i noticed you have to be in ranged range in order for it to atleast semi-work

--> could be a global core fuckup

**Comment by kelno** [comment]
That's probably because you implemented some cone angle logic recently and if you're using the same data as me, that spell has 5°

**Comment by Evolvee** [comment]
@Wolffenstein reee 
![image](https://user-images.githubusercontent.com/1942409/71376776-da070e00-25c2-11ea-89b4-8314a7fc83de.png) giev my favourite spell´s functionality back
