### ISSUE TITLE
[Item] Ethereum Prison Key doesn't open the Prisons in Netherstorm

### ISSUE THREAD

**Issue by TobyBeam** [Atlantiss/NetherwingBugtracker#6374]
![Server Revision](https://user-images.githubusercontent.com/43545229/67658842-14ee1c00-f95b-11e9-8826-087c6a0b5916.png)
**Description**: The ethereum prisons at both localizations in Ethereum Staging Ground - Netherstorm don't open properly. I already wasted 3 [Ethereum Prison Key]s 

**Current behaviour**: the opening animation on one of the ethereum prisons ends without despawning the prison cell and without spawning any NPCs.

**Expected behaviour**: After using an [Ethereum Prison Key] on one of the prison cells there should spawn randomly an either friendly or hostile NPC for gaining reputation for some factions.

**Server Revision**: 3174 [Branch: master, Hash: 5da45e171b0f]

**Comment by Evolvee** [comment]
https://github.com/Atlantiss/NetherwingBugtracker/issues/5933

**Comment by danbopes** [comment]
Rev 3177
