### ISSUE TITLE
Felhunter intellect scaling

### ISSUE THREAD

**Issue by Speank** [Atlantiss/NetherwingBugtracker#6375]
[//]: # (Enclose links to things related to the bug using http://wowhead.com or any other TBC database.)
[//]: # (You can use screenshot ingame to visual the issue.)
[//]: # (Write your tickets according to the format:)
[//]: # ([Quest][Azuremyst Isle] Red Snapper - Very Tasty!)
[//]: # ([NPC] Magistrix Erona)
[//]: # ([Spell][Mage] Fireball)
[//]: # ([Npc][Drop] Ghostclaw Lynx)
[//]: # ([Web] Armory doesnt work)
[//]: # (To find server revision type `.server info` command in the game chat.)

**Description**: Fel hunter's intellect scaling is also lower then it should be.

**Current behaviour**: https://imgur.com/a/99dcTf8 my character has 383 intellect, felhunter has 4072 mana (with Fel intellect talented, 15% more intellect for felhunter) 

**Expected behaviour**: https://youtu.be/aDGtKZ-xRuo?t=5 warlock in video has 375 intellect and his fel hunter has 4127 mana.
Same scaling issue as the Felhunter stamina scaling, which is resolved. 
If anyone has any data on felhunter armor scaling, it would be much appriciated. 

**Server Revision**: Server revision: 3174

**Comment by Evolvee** [comment]
https://github.com/ccshiro/cc-buglist/issues/847

**Comment by Wolffenstein** [comment]
Fixed in rev 3276.
