### ISSUE TITLE
Shiv 1/2 the time doesn't apply poison

### ISSUE THREAD

**Issue by Mitchw1989** [Atlantiss/NetherwingBugtracker#6378]
Shiv is doing dmg, making the sound, Not applying poison 1/4 of the time. I've only seen it when 5 stacks of Deadly Poison are about to fall off & when reapplied.. Deadly Poison doesn't renew..

**Comment by Evolvee** [comment]
resist

**Comment by Mitchw1989** [comment]
I have 320 Melee hit with Boomkin IFF( aka Hit capped) . Is shiv acting as Spell & Not a melee hit ?

**Comment by Evolvee** [comment]
poisons are spell, not melee

**Comment by Mitchw1989** [comment]
No because I'm already hit capped for poisons & they have 100% hit rate. If they needed Spell I would maintain a 15% miss rate.

**Comment by Evolvee** [comment]
spell hit rating does nothing against spell resistance, you need spell penetration
