### ISSUE TITLE
Wailer#16321 & Eye of Dar'khan#16320 lacking patrols in Deatholme 

### ISSUE THREAD

**Issue by Tenoutoften** [Atlantiss/NetherwingBugtracker#638]
**Description**: 
Wailer#16321(ID:1, GUIDLow: 32378, Coords: 34, 75) https://db.excalibur.ws/?npc=16321 should be patroling the roads. Currently just sits there

**Expected behaviour**: 
I expect this NPC to be patroling the roads:
https://youtu.be/BRhyUXVwcwE?t=137
https://youtu.be/21Om2Qkdtvg?t=79
https://youtu.be/99YQW74daxo?t=976

Eye of Dar'khan#16320(https://db.excalibur.ws/?npc=16320 coords: 33.3 82.8, Id: 11, GUIDLow: 11945) seems to lack patrol path, should patrol around the building I am guessing. Currently awkwardly sits around two guards to the entrance(https://i.gyazo.com/6ec6f780abff8c14a2612458296f4827.png). Don't have video evidence for this one, but it looks bizarre enough. 

**Server Revision**: 
2060

**Comment by aresbrutus** [comment]
This is fixed in rev `Ilus`
