### ISSUE TITLE
[QUEST] Skywing from terokkar.

### ISSUE THREAD

**Issue by sergiocg91** [Atlantiss/NetherwingBugtracker#6380]
[//]: # (Enclose links to things related to the bug using http://wowhead.com or any other TBC database.)
[//]: # (You can use screenshot ingame to visual the issue.)
[//]: # (Write your tickets according to the format:)
[//]: # ([Quest][Azuremyst Isle] Red Snapper - Very Tasty!)
[//]: # ([NPC] Magistrix Erona)
[//]: # ([Spell][Mage] Fireball)
[//]: # ([Npc][Drop] Ghostclaw Lynx)
[//]: # ([Web] Armory doesnt work)
[//]: # (To find server revision type `.server info` command in the game chat.)

**Description**: 

**Current behaviour**:

**Expected behaviour**: 

**Server Revision**:

**Comment by sergiocg91** [comment]
Hi!!

I post the ticket for the quest Skywing (the scort), when you finish the quest, the bird desapear before is completed and u cant speak with him to complete.

Ty for the help.

Kind Regards.

**Comment by lyubomeer** [comment]
u turn it in in shattrath https://tbcdb.com/?quest=10898

**Comment by Evolvee** [comment]
works fine for me, need it recorded if there is still any problem
