### ISSUE TITLE
Windy Cloud Respawn

### ISSUE THREAD

**Issue by The14me** [Atlantiss/NetherwingBugtracker#6381]
**Current behaviour**: Respawn every 10 min at the same spot.

**Expected behaviour**: Must be dynamic spot and respawn time (at least 1h)
https://www.wowhead.com/npc=24222/windy-cloud

**Server Revision**:

**Comment by Arclitee** [comment]
that explains how Ritter could sells 20 stack of those primals every day lol

**Comment by Evolvee** [comment]
it already is 
@Wolffenstein 
![image](https://user-images.githubusercontent.com/1942409/71257691-ab740380-2334-11ea-9dfd-e9d38d5f5cb0.png)

i will add it to creature table as well just to be sure creature_spawn_pool_entries didnt break.. it would be a worth checking tho... @The14me need more evidence/info on the problem(PM wolf on discord)

**Comment by Evolvee** [comment]
next rev increased spawn timer

**Comment by Evolvee** [comment]
it if respawns always on the same spot --> @Wolffenstein thats a bigass core issue with pooling (which is broken confirmed by the bugreport from isle i sent you)
