### ISSUE TITLE
[Raid] Doomfire stacks on Archimonde

### ISSUE THREAD

**Issue by Tereneckla** [Atlantiss/NetherwingBugtracker#6383]
[//]: # (Enclose links to things related to the bug using http://wowhead.com or any other TBC database.)
[//]: # (You can use screenshot ingame to visual the issue.)
[//]: # (Write your tickets according to the format:)
[//]: # ([Quest][Azuremyst Isle] Red Snapper - Very Tasty!)
[//]: # ([NPC] Magistrix Erona)
[//]: # ([Spell][Mage] Fireball)
[//]: # ([Npc][Drop] Ghostclaw Lynx)
[//]: # ([Web] Armory doesnt work)
[//]: # (To find server revision type `.server info` command in the game chat.)

**Description**: 

**Current behaviour**:
![WoWScrnShot_103119_233309](https://user-images.githubusercontent.com/50233983/67990976-e1034700-fc37-11e9-8f2c-567c09f5fa1f.jpg)
**Expected behaviour**: Not stacking 
https://youtu.be/ZV2uiI7CbCM?t=256

You see him standing in the doomfire for around 5 seconds, which only refreshes the debuff.

**Server Revision**: 3181

**Comment by Wolffenstein** [comment]
Fixed in rev 3186.
