### ISSUE TITLE
[Hunter] Pet scaling --> Hit rating not working

### ISSUE THREAD

**Issue by Arclitee** [Atlantiss/NetherwingBugtracker#6384]
Even with 9% hit on gear + 4% hit on talents, my pet, lvl 70, keeps missings strikes on the mobs and players. Some of his abilities miss too.
The damage loss is huge because of that, and some times in pvp that means a kill.

**Comment by Evolvee** [comment]
pets dont inherit hit rating from owner until wotlk+
