### ISSUE TITLE
[ZA][Jan'alai] A few Jan'alai eggs spawn birds even if there is no hatcher at that side.

### ISSUE THREAD

**Issue by eri1997** [Atlantiss/NetherwingBugtracker#6385]
**Description**: https://imgur.com/a/Va6PidH
In the screenshot you can see a few birds spawned even though  the  1 hatcher alive  is still on the other side hatching eggs . Has happened  a few times not very often so minor issue.

**Current behaviour**: above

**Expected behaviour**: Eggs only spawn birds if a hatcher is there.

**Server Revision**: 3181

**Comment by Tereneckla** [comment]
Other issue has more information and a possible way to reproduce
