### ISSUE TITLE
[PvP][Shaman][Paladin] Shaman toughness and Seal of Justice

### ISSUE THREAD

**Issue by Jumpka** [Atlantiss/NetherwingBugtracker#6387]
**Current behaviour**: 
Judgment of Justice is currently affected by the shaman toughness talent, making it a 10 seconds debuff instead of 20 seconds.

**Expected behaviour**: 
Judgment of Justice shouldn't be affected by this talent.

https://www.youtube.com/watch?v=dbKaU_LMCCk#t=12m40s
Judgment is clearly 20 sec duration and the paladin is using frost oil, which only lasts 3 seconds in this duel, that means the shaman didn't skip the talent (in previous duels in this video when the shaman is ele, frost oil is 6 seconds).

**Comment by Wolffenstein** [comment]
Fixed in rev 3184.
