### ISSUE TITLE
[core][arena] Arena end of match delay is not present

### ISSUE THREAD

**Issue by Evolvee** [Atlantiss/NetherwingBugtracker#6388]
@Wolffenstein u fucked up something, its not present anymore, match ends instantly with no delay for draw

http://tbc.internal.atlantiss.eu/showthread.php?tid=947&highlight=arena

**Comment by Wolffenstein** [comment]
no

**Comment by Wolffenstein** [comment]
3184

**Comment by Evolvee** [comment]
weirdChamp again

**Comment by Evolvee** [comment]
and again
