### ISSUE TITLE
Mounts and water

### ISSUE THREAD

**Issue by mbzz88** [Atlantiss/NetherwingBugtracker#639]
**Description**: Player is unable to mount after swimming and is 100% back on land

**Current behaviour**:"Cannot use while swimming" error message, even when standing in very shallow water, where you can eat/drink etc. https://youtu.be/3LAJ-8L7TYw

**Expected behaviour**: Able to mount after you stand up, even if you are in water

**Comment by Emityx** [comment]
Mounts cannot swim or be used in water in TBC. This feature was added in Wotlk in patch 3.1.0.

![x](https://user-images.githubusercontent.com/37587544/46070084-3b9cba80-c17d-11e8-841a-b2f456d5a77e.PNG)

**Comment by Gniddikon** [comment]
His report was about not being able to mount in “shallow” water though where you stand and not swim.

Should be possible imo.

**Comment by Wolffenstein** [comment]
Fixed in rev 2063.
