### ISSUE TITLE
[Item]Force Reactive Disk (Engineering Item) is dealing 0 Damage and always damages itself

### ISSUE THREAD

**Issue by JoyyNefarian** [Atlantiss/NetherwingBugtracker#6390]
****Description**:** 
https://tbcdb.com/?item=18168 (Force Reactive Disk) does 0 Damage to Enemies around the wearer. It procs visually, but does no damage. Also it damages itself with every proc. 

****Current behaviour**:**
Force Reactive Disk does 0 Damage to Enemies around the wearer. Also it damages itself with every proc. 

****Expected behaviour**:** 
It should proc on block and deal damage to all surrounding enemies. It should not damage itself on every single proc.
ZF farming in TBC: https://www.youtube.com/watch?v=AaCMBnscv6o

**Server Revision**: 
3181

**Comment by Wolffenstein** [comment]
Fixed in rev 3185.
