### ISSUE TITLE
[Core] Each item with haste rating acts as its own source of %haste

### ISSUE THREAD

**Issue by Tereneckla** [Atlantiss/NetherwingBugtracker#6391]
[//]: # (Enclose links to things related to the bug using http://wowhead.com or any other TBC database.)
[//]: # (You can use screenshot ingame to visual the issue.)
[//]: # (Write your tickets according to the format:)
[//]: # ([Quest][Azuremyst Isle] Red Snapper - Very Tasty!)
[//]: # ([NPC] Magistrix Erona)
[//]: # ([Spell][Mage] Fireball)
[//]: # ([Npc][Drop] Ghostclaw Lynx)
[//]: # ([Web] Armory doesnt work)
[//]: # (To find server revision type `.server info` command in the game chat.)

**Description**: https://docs.google.com/spreadsheets/d/1EtzA2ubv1a7NVuYqqaUYrgtka-GQlBeEVRj_LviF8sk

Noted down cast speed of lightning bolt with various pieces of haste gear equipped because the normal formula with 15.77 haste rating = 1% haste didn't give me the ingame tooltip cast time.

Found no clear value of haste rating to % haste conversion

**Current behaviour**:
![WoWScrnShot_110519_223246](https://user-images.githubusercontent.com/50233983/68248072-66ae3a80-001c-11ea-82ea-8869786c4b35.jpg)
![WoWScrnShot_110519_223250](https://user-images.githubusercontent.com/50233983/68248078-6c0b8500-001c-11ea-905f-c9b56fe737fc.jpg)

2.5/2.08 = 1.201923077
Meaning 20% Haste while Character Pane shows 18% (which is expected. 291/15.77 = 18.45)

After some testing each item with rating seems to be converted to %haste first and then the calc starts.
Itemhaste: 25 28 30 30 30 33 37 38 40 =291

1.015923567 * 1.017834395 * 1.01910828 * 1.01910828 * 1.01910828 * 1.021019108 * 1.023566879 * 1.024203822 * 1.025477707 = 1.20 -> 20% haste

**Expected behaviour**: 
All rating gets added together first.
25+28+30+30+30+33+37+38+40=291 -> 18% haste

**Server Revision**: 3181

**Comment by Easyfraggy** [comment]
Just to be clear even procs that give +haste rating should be added together with the gear aswell. Basicly all haste rating should count as 1 multiplier.

**Comment by ircfelix** [comment]
source

**Comment by Tereneckla** [comment]
With full Sunwell Gear and Haste Drums I got to a difference of 10% in Haste
43% Expected, 53% Actual

![image](https://user-images.githubusercontent.com/50233983/76699575-08225880-66af-11ea-9738-1d56bbc41e12.png)
![image](https://user-images.githubusercontent.com/50233983/76699579-0f496680-66af-11ea-98f2-6d23b71850b9.png)
2/1.3 = 1.538 -> 53% Haste

**Comment by Tereneckla** [comment]
fixed in aura rework

**Comment by Nghedi** [comment]
For me (Resto shaman) it still seems to still be wrong. Chainheal casttime is to short (for 300 or more haste.) We can test it together if you want.

**Comment by Tereneckla** [comment]
Aura rework is not live yet.

**Comment by Nghedi** [comment]
Even not on PTR?

**Comment by Tereneckla** [comment]
PTR also is on the master branch currently, so no aura rework.
