### ISSUE TITLE
[Raid] Anetheron (MH) - Towering Infernals are the wrong level

### ISSUE THREAD

**Issue by hederob** [Atlantiss/NetherwingBugtracker#6392]
https://db.excalibur.ws/?npc=17818
https://tbc-twinhead.twinstar.cz/?npc=17818
https://youtu.be/zo_LWN5ZqZY?t=58

**Description**: 
During the Anetheron fight in Mount Hyjal, he spawns level 73 Towering Infernals. They should be level 72 ( as shown on all databases and older youtube videos). Being 73 makes them much harder to tank and damage. It also makes them able to crush tanks much more easily. They do about 6k damage on plate and seem to have much more than 221k hp.

**Current behaviour**: 
Towering Infernals are level 73. They do about 6k damage on plate and have more than 221k hp.

**Expected behaviour**: 
Towering Infernals should be level 72. They should do about 3-4k on plate and have 221k hp.

**Server Revision**: 
3181

**Comment by Evolvee** [comment]
core issue - summon spell forces the level of the guardian

**Comment by Wolffenstein** [comment]
Fixed in rev 3186.
