### ISSUE TITLE
[Item] Furor's Compendium of Dragonslaying follow up quest is broken

### ISSUE THREAD

**Issue by hederob** [Atlantiss/NetherwingBugtracker#6393]
**Description**: 
When turning in the [Furor's Compendium of Dragonslaying] to ([NPC] Lorekeeper Lydros), he doesn't follow up with giving you [A Dull and Flat Elven Blade] from the gossip text.
**Current behaviour**:
Lorekeeper Lydros' gossip doesn't reward you with [A Dull and Flat Elven Blade].
**Expected behaviour**: 
Lorekeeper Lydros' gossip should be clickable and he should reward you with a [Dull and Flat Elven Blade].
**Server Revision**: 
3181

**Comment by Jinadaxoxo** [comment]
I have the same problem pls help me

**Comment by Evolvee** [comment]
fixed in rev 3188
