### ISSUE TITLE
D2 q chain, brd, The Challenge quest bug

### ISSUE THREAD

**Issue by Lepo71** [Atlantiss/NetherwingBugtracker#6394]
[//]: # (Enclose links to things related to the bug using http://wowhead.com or any other TBC database.) https://classic.wowhead.com/quest=9015/the-challenge
[//]: # (You can use screenshot ingame to visual the issue.)
[//]: # (Write your tickets according to the format:)
[//]: # ([Quest][Azuremyst Isle] Red Snapper - Very Tasty!)
[//]: # ([NPC] Magistrix Erona)
[//]: # ([Spell][Mage] Fireball)
[//]: # ([Npc][Drop] Ghostclaw Lynx)
[//]: # ([Web] Armory doesnt work)
[//]: # (To find server revision type `.server info` command in the game chat.)

**Description**:  when i use the item (Banner of Provocation) the boss dont spawn and nothing happen so i cant kill and finish my q and cant continue my quest chain

**Current behaviour**:

**Expected behaviour**: 

**Server Revision**:

**Comment by Manaci** [comment]
It should be working, did it months ago. You gotta use the banner in the middle of the arena while the hostile dwarf is walking to ensure that he will summon the special boss encounter and not the normal encounter instead.

**Comment by Evolvee** [comment]
provide video of it pls, otherwise i will close it as its working for everyone else

**Comment by Lepo71** [comment]
I use when the dwarf is coming and he just stay and nothing happen and i
just get locked in the aréna but i wait 10 min and use again but nothing
still, after this i try kill the normal boss and use the item i know not
this needd to do but try and still nothing happen

Evolve <notifications@github.com> ezt írta (időpont: 2019. nov. 8., P
21:47):

**Comment by Lepo71** [comment]
Tomorrow i creat  video if u dont trust 😄

Róbert Huszár <penge210@gmail.com> ezt írta (időpont: 2019. nov. 9., Szo
1:14):

**Comment by Lepo71** [comment]
https://www.youtube.com/watch?v=Njk9Dm9LCkM&feature=youtu.be

**Comment by Lepo71** [comment]
probably how much time i need to wait to can finish the q? ^^

**Comment by Evolvee** [comment]
its low priority, if we are being honest, it depends on my mood and motivation :D

**Comment by Lepo71** [comment]
ehhh..:D i just need one boots for the set bonus.. :D now i can wait 2-3 mounth to get this? ^^

**Comment by Lepo71** [comment]
i want get the rank 1  2s with this gear :D

**Comment by Evolvee** [comment]
you just need to cast the flag AFTER the npc starts moving towards the gate, not before (if u want to finish it now)

**Comment by Evolvee** [comment]
fixed in next rev (u can still do that even now, just wait until the NPC starts moving towards the gate and then use it... or at any other gate after)
