### ISSUE TITLE
Forum issue. NO, it's NOT working

### ISSUE THREAD

**Issue by nlhil** [Atlantiss/NetherwingBugtracker#6395]
**Description**: Well, I already told this twise. Time to tell it third time (LH tranfered players will be very happy see forum dead).

**Current behaviour**: Auto-login from main site to forum not work for new players (since 14.07.19 I think). I tryed this with 4 computers from 3 places used different ip and all possible browsers  + even try vpn. That !@#$ not work and it's not only for me -  asked 2 friends and they cant log at forum too. Also I checked "forum online" list periodically since SEPTEMBER & here is only old players (14.07.19 is last reg date I saw) + a lot of guests. Same with the posts/new topics at forum - they only from old players.

**Expected behaviour**: 
Expected behavior? U told u will double check this & obviously u check it with ur account - ofc there was no problem. Try to clear browser cash/other !@#$ and make new acc - u'll be surprised.
Even if YOU will have no problem again for some reason - a lot of players have it. Forum activity shows that for sure. 
What's the problem to make captcha if u have spam issues???? And how it can help at all? spamers can register at forum, but cant with main site?
**Server Revision**:

**Comment by ircfelix** [comment]
Do you really expect people will work for you if you insult them?
If you want to fuck, you gotta be nice.

**Comment by nlhil** [comment]
I rly think people should work _for themself_ cause it's not **my** server. I won’t even communicate there if they fix it, I only care about online (dead forum ofc not increase server attraction) = they should do it not for me, again.
btw, yeah I was little drunk yesterday but it's not first time I report that !@#$ and sometimes u need just take attention. I dont wanna fuck I wanna be heard
