### ISSUE TITLE
Foror`s

### ISSUE THREAD

**Issue by Jinadaxoxo** [Atlantiss/NetherwingBugtracker#6396]
[//]: # (Enclose links to things related to the bug using http://wowhead.com or any other TBC database.)
[//]: # (You can use screenshot ingame to visual the issue.)
[//]: # (Write your tickets according to the format:)
[//]: # ([Quest][Azuremyst Isle] Red Snapper - Very Tasty!)
[//]: # ([NPC] Magistrix Erona)
[//]: # ([Spell][Mage] Fireball)
[//]: # ([Npc][Drop] Ghostclaw Lynx)
[//]: # ([Web] Armory doesnt work)
[//]: # (To find server revision type `.server info` command in the game chat.)

**Description**: When turning in the [Furor's Compendium of Dragonslaying] to ([NPC] Lorekeeper Lydros), he doesn't follow up with giving you [A Dull and Flat Elven Blade] from the gossip text.

**Current behaviour**: Lorekeeper Lydros' gossip doesn't reward you with [A Dull and Flat Elven Blade].

**Expected behaviour**: Lorekeeper Lydros' gossip should be clickable and he should reward you with a [Dull and Flat Elven Blade].
**Server Revision**: 3181

**Comment by Evolvee** [comment]
https://github.com/Atlantiss/NetherwingBugtracker/issues/6393

**Comment by Jinadaxoxo** [comment]
it isnt working still ;/
