### ISSUE TITLE
Noggenfogger Elixir not allowing mounting

### ISSUE THREAD

**Issue by Maikie1234** [Atlantiss/NetherwingBugtracker#6397]
[Item] Noggenfogger Elixir

**Description**: Noggenfogger Elixir not allowing mounting

**Current behaviour**: Noggenfogger Elixir´s transformation into a skeleton doesnt allow you to mount up on your ground mount (dont know if the same thing applies for flying mounts, didnt test that). If you use your mount under the effect of the skeleton transformation, it just throws up a error message : "You cant´t do that yet". Both Shrink effect and Slow Fall effect work as intended

**Expected behaviour**: You should be allowed to mount up with the elixir´s effect 

**Server Revision**: 3185

**Comment by Maikie1234** [comment]
*doesnt allow mounting up on flying mounts, eighter

**Comment by Evolvee** [comment]
evidence?

**Comment by Evolvee** [comment]
https://github.com/Atlantiss/NetherwingBugtracker/issues/2381
https://github.com/Atlantiss/NetherwingBugtracker/issues/4499
just a quick search, use it before you post pls
