### ISSUE TITLE
t2 set qw

### ISSUE THREAD

**Issue by Mystinger** [Atlantiss/NetherwingBugtracker#6398]
Hey! is "The Right Piece Of Lord VaLthalaks Amulet" qw not whork ? cant sumon Mor Grayhoof in LBRS and can sumon Jarien and Sothos in Stratholme . i have Brazer of Beckoning
 im gonna to do al qwests for my d2 set.
https://classic.wowhead.com/quest=8990/the-right-piece-of-lord-valthalaks-amulet

**Comment by Evolvee** [comment]
the quest you linked is for Isalien

**Comment by Evolvee** [comment]
mor grahoof fixed

**Comment by Evolvee** [comment]
Jarien and Sothos fixed

in next rev ^^ (check changelog)
