### ISSUE TITLE
[Warrior] Focus Intercept switches attack target to the Intercepted target

### ISSUE THREAD

**Issue by sposobniy** [Atlantiss/NetherwingBugtracker#6399]
Describe the bug : - Focus Intercept switches attack target to the Intercepted target

Intercept (25275)

To Reproduce

1)Attack Target A
2)Focus Intercept Target B with autto-attack on Target A (/cast [target=focus] Intercept).
3)The attack target will switch to Target B

**Comment by Easyfraggy** [comment]
I've had some problems similar to this with Pummel macro making my melee swings swap to the pummeled target.

**Comment by Speank** [comment]
Can confirm using focus intercept just for the stun effect while not swapping any target causes your melee swings to que up to attack focus target, rather then ur current target. extremly annoying

**Comment by Evolvee** [comment]
![image](https://user-images.githubusercontent.com/1942409/68698218-bb076c00-0580-11ea-9dca-d1a3ada36ba8.png)

this needs to be researched first

**Comment by sposobniy** [comment]
I described  issue a bit incorrectly  , after auto attack switched to target B . It is possible to return to the main target A only if i  clear target and start it again . Any macros with /startattack and skill not return swing to main target . This is the main problem.  

Found only wotlk focus intercept video : https://youtu.be/z73ZsVb6aCE?t=149  moment at 2:33

**Comment by Jumpka** [comment]
Would adding this to the end of the macro work?
/target player
/targetlasttarget
/startattack

**Comment by Easyfraggy** [comment]
I don't know why this tweet guy thinks that way. There was never ever a situation on retail where you would melee (white) swing something that wasn't your target.

**Comment by Macumbafeh** [comment]
I Saw it too with my feral when i was testing a charge focus macro.
When i charge the focus, my auto attack is on him, but i still Can use my skills on my current target... Strange. I will add a video

**Comment by Macumbafeh** [comment]
My test video here : https://youtu.be/p8zDHzRcpXE

You can see my auto attack on focus when i charged, even if my target is not the focus.
Tweet say truth, charge/interv start attack, BUT ! it start attack on your target. And here we charge / interv focus to switch after the target. So the auto attack have to be on the target not on the focus.

it's a bug because, try to auto attack a target that you don't target. 
it's impossible, cause when you will switch target, it will auto attack the other target OR if in your settings option you didn't took it, it will stop attack.

Then Imho it's a bug.

**Comment by nexumus** [comment]
Still bugged.
Focus intercept / charge turns off autoattacks from main target.
How it should work: https://www.youtube.com/watch?v=z73ZsVb6aCE
2:32

i found something maybe helpful to sort it out, not a dev, just saying.
https://github.com/TrinityCore/TrinityCore/issues/17589

**Comment by Tereneckla** [comment]
https://youtu.be/Vht-x3KDIK0?t=189
https://www.mmo-champion.com/threads/783087-Focus-charge-intercept-bug
Was an issue during wotlk until cataclysm at least
Says it happens 50% of the time

Likely was happening in tbc aswell
