### ISSUE TITLE
Wretched Ringleader (Quest)

### ISSUE THREAD

**Issue by deku100** [Atlantiss/NetherwingBugtracker#64]
[//]: # (Enclose links to things related to the bug using http://wowhead.com or any other TBC database.)
[//]: # (You can use screenshot ingame to visual the issue.)
[//]: # (Write your tickets according to the format:)
[//]: # ([Quest][Azuremyst Isle] Red Snapper - Very Tasty!)
[//]: # ([NPC] Magistrix Erona)
[//]: # ([Spell][Mage] Fireball)
[//]: # ([Npc][Drop] Ghostclaw Lynx)
[//]: # ([Web] Armory doesnt work)

**Description**: Wretched Ringleader (Quest), Eversong Woods

**Current behaviour**: It is possible to loot Aldaron's Head from Aldaron the Wretched at Sunsail Anchorage before accepting the quest.

**Expected behaviour**: Mobs don't drop quest items before the player accepts the corresponding quest.

**Server Revision**:

**Comment by Wolffenstein** [comment]
Fixed in rev 2022.
