### ISSUE TITLE
[Paladin] [Spell] Paladin Blessing of Might issue.

### ISSUE THREAD

**Issue by Irishmeatpie** [Atlantiss/NetherwingBugtracker#640]
**Description**: 
Player is unable to cast Blessing of Might (all ranks) https://classicdb.ch/?spell=19834 while Seal of the Crusader (all ranks) https://classicdb.ch/?spell=21083 is active.

**Expected behaviour**: 
Able to cast Blessing of Might while Seal of the Crusader is active.
**Server Revision**: 
2061

**Comment by Buggyswires** [comment]
I can confirm this. If SoC is active the +AP blocks Blessing of Might

**Comment by Wolffenstein** [comment]
Fixed in rev 2067.
