### ISSUE TITLE
Totems sometimes dodge attacks 

### ISSUE THREAD

**Issue by sposobniy** [Atlantiss/NetherwingBugtracker#6400]
Problem : sometimes enemy totems can "dodge" attack . 

https://www.twitch.tv/sposobniy/clip/SassyCrispyCheetahNerfBlueBlaster?filter=clips&range=all&sort=time  

https://www.twitch.tv/sposobniy/clip/AmazonianProudPigeonBIRB?filter=clips&range=all&sort=time

**Comment by Evolvee** [comment]
https://youtu.be/ZcozAF2c4-s?t=179

**Comment by Wolffenstein** [comment]
Fixed in rev 3187.
