### ISSUE TITLE
Some spells give combat, but dont cancel drinking effect 

### ISSUE THREAD

**Issue by sposobniy** [Atlantiss/NetherwingBugtracker#6401]
Problem :
 Spells : Paladin Consecration http://tbc.cavernoftime.com/spell=27173
Warlock : Devour Magic http://tbc.cavernoftime.com/spell=27277 

Perhaps there are some more spells maybe , this is what we saw so found

https://clips.twitch.tv/SaltyLazyChimpanzeeKAPOW

**Comment by Wolffenstein** [comment]
Fixed in rev 3198.

**Comment by Evolvee** [comment]
rev 3236
still bugged (devour magic), it gives combat but doesnt stop drinking

**Comment by tsuone** [comment]
3545
