### ISSUE TITLE
frostbite shouldnt stack with frostnova/freeze

### ISSUE THREAD

**Issue by sposobniy** [Atlantiss/NetherwingBugtracker#6402]
Problem : frostbite can proc when you are under the effect of frost nova or pet nova 

https://clips.twitch.tv/CrazyBumblingKittenDAESuppy 

https://imgur.com/KUTKRvC

How it should work :  

https://wowwiki.fandom.com/wiki/Frostbite_(mage_talent)?oldid=1402999 

"The Frostbite effect does not overwrite the Frost Nova effect or the Water Elemental's Freeze effect. These spells have a longer duration (8 seconds vs. 5 seconds) than Frostbite, and thus supersede it. Even if the Frost Nova or Freeze has fewer than 5 seconds remaining, Frostbite will not take effect. However, if the attack with a chill happens to break the freezing effect, it is possible for the Frosbite freeze to take effect immediately." 

 
https://youtu.be/evY1Q9KdXfM?t=1m49s
https://youtu.be/dxQvIEVPOO8?t=2m38s 
https://youtu.be/hDBIyF0O9bE?t=4m54s
Rogue gets frostbite proc, and its replaced by frost nova from mage

**Comment by Evolvee** [comment]
I researched this in the past. Will provide some stuff when i get home.

**Comment by sposobniy** [comment]
i am corrected cos link wrong clip before , i was frostbite into frost nova

**Comment by Jumpka** [comment]
You can also have pet nova and frost nova at the same time on this server. (can find the clip later if needed)

**Comment by Evolvee** [comment]
![image](https://user-images.githubusercontent.com/1942409/68695747-e5a2f600-057b-11ea-85ef-c64164b29107.png)
![image](https://user-images.githubusercontent.com/1942409/68695756-e9cf1380-057b-11ea-8d27-b4428d5ccfbc.png)
![image](https://user-images.githubusercontent.com/1942409/68695805-09fed280-057c-11ea-8773-5942e3d199cf.png)

**Comment by Jumpka** [comment]
I think that the wowwiki is incorrect in this case. If I'm not mistaken, nova only breaks on actual damage taken, and not absorbed damage, right? (at least that's my understanding and in this entire video there's no nova break during absorb)
https://www.youtube.com/watch?v=GWC6vPoqD4U&t=9m45s
Last second of nova gets replaced by frostbite proc, entire damage was absorbed so there's no reason for nova to break. I would say there's no exception to aura stacking rule for frostbite (also proving that would be pretty much impossible), wowwiki is just incorrect.

**Comment by Evolvee** [comment]
yea, absorb didnt count towards dmg threshold, afaik

**Comment by Evolvee** [comment]
https://github.com/Atlantiss/AtlantissTbcBTOLD/issues/153

**Comment by Wolffenstein** [comment]
Fixed in rev 3194.
