### ISSUE TITLE
Сharacter position desynchronization . 

### ISSUE THREAD

**Issue by sposobniy** [Atlantiss/NetherwingBugtracker#6404]
Problem ; Very often the positions of the players on your monitor are different from the actual position on the server . 
Spell  Castes are also observed during movement and jumping. 

How it looks :  

1) https://www.twitch.tv/sposobniy/clip/IncredulousCrypticElephantBCouch 

https://imgur.com/Z0pn93z  this moment from 15 seconds on clip .  Ret got mortal from war , when the war  was not in sight on my screen and he aswell .  

https://imgur.com/IBv40MI  after 5 seconds  (20s momemt on clip ), the druid jumps and casts us a cyclone on the fly 

2)  https://www.twitch.tv/sposobniy/clip/PrettyAntsyTeaHeyGirl 

https://imgur.com/FPqEVOB  The druid gave me the bash being on the other side of the pillar 

3) https://clips.twitch.tv/BrainyDeterminedTriangleStinkyCheese   I am tauren with large  hitbox , also with leeway my attack distance should be ~8 yards .  Priests  slowed with hamstring debuff . I could not attack him (look at mortal icon and auto attack timer ).  Also in the end of this clip he casts "Flash heal " while jumping . 

4)  https://www.twitch.tv/jumpka/clip/SmoggyPeacefulNoodleEleGiggle  its  stream of my friend 
 starting from 12 seconds of this clip  it completely disappears auto-attack (look at swing timer ) although when he pressed "crusaider strike"  he also did not receive an auto attack  

5) https://www.twitch.tv/sposobniy/clip/SparklingSquareSowKappaWealth this clip made 4 month ago .

Very global issue for all melee classes  when you just can't hitt a character .

**Comment by Jumpka** [comment]
In my opinion it seems to happen only after someone lagspikes. The problem here is, it never gets fixed unless your game reloads (be it the command or changing zone etc.) so you can be stuck in a 20 minute arena with someone being desynched the entire game (or as in the case of the first clip, server lag desynched all 4 of us) cause he lagged at the beginning. 

(btw /reload in arena on this server takes insanely long time, the last time I tried it it took around 2 minutes or so...)

**Comment by Macumbafeh** [comment]
Bad issue :(

**Comment by Jumpka** [comment]
That's actually true. I've been farming a lot of BGs past few days and it hasn't happened once, but it happens at least once every arena session.

**Comment by Godmatik** [comment]
Duplicate #7805
