### ISSUE TITLE
[Paladin] Judgment delay

### ISSUE THREAD

**Issue by Jumpka** [Atlantiss/NetherwingBugtracker#6405]
I'm not exactly sure what's this server's stance on the 0-400ms spell batching delay on every spell, but right now judgment's spell delay is so small it causes two issues:

1) Having seal A active and then changing into seal B while judging instantly after will cause seal A to be judged first and then seal B buff appears.
https://clips.twitch.tv/NurturingVivaciousPoultrySwiftRage
In the clip, I've used macro just to show order of spells, but the delay on seals is so big that this issue happens every time when doing it manually. (Self buffs like seals shouldn't have delay at all, is this some workaround to make sealtwisting work?)

2) Using seal of blood judgment to break CCs is sometimes pretty much impossible, the delay seems random, but sometimes too small, casting judgment after poly cast has already finished, but still taking the backlash damage before poly debuff is on me.
Here's my old CC bugreport of this issue https://github.com/ccshiro/cc-buglist/issues/1598

**Comment by Evolvee** [comment]
spell delay is turned off, intentionally  sadly :( :( :(

**Comment by Jumpka** [comment]
I see, don't understand this spell delay hate, it's only about getting used to it.. 

Anyway, coudln't the Seal of Blood part be fixed with some bandaid SWD like delay? The backlash delay is clearly wrong, if there's any delay at all on this server (the worst part is that it feels so random here).
For example in this clip, the backlash damage and judgment damage happen at the same time 
https://clips.twitch.tv/SassySquareSardineShadyLulu
In the retail videos from CC bug report, it was 800ms after judgment hit if I'm not mistaken (two spellbatches I suppose), but even if this number isn't correct, it definitely didn't happen at the same time as judgment damage.

And one thing that I don't understand about the first issue is, why is there delay on seals (shouldn't be even on retail with spellbatching), but no delay on judgments?

**Comment by Evolvee** [comment]
The seals were manually fixed I believe during the time where we had spell delay on as it was causing issue where the seal was consumed but the wrong seal was judgemented...or something like that, i would have to search for it when i get home. The reason is because spell delay is a big system. Its bigger than any other core system when it comes to the influence it has on game. When it was turned off, remnants of it still remained active as they werent strictly bound on the system but were rather a support of it. E.g. a spell got fixed in order to properly behave with spell delay system. Spell delay got turned off. The spell fix still remained tho...

**Comment by Evolvee** [comment]
And about the spell delay hate: it was Wolfenstein who decided to turn it off. I spent literally years on research, but he was unable to implement it properly, so it caused some issues and with the hate of ~retards~ ppl who couldnt understand why there is some delay when the pinacle, the god, the savior, the best server to ever be created, ~stock mangos~ Nostalrius had everything instantly(if you dont count the half second update time diff lag it had)

**Comment by Evolvee** [comment]
https://www.youtube.com/playlist?list=PLPcjlmbddtblTONSqUmRjUmsbGQBEHTwy

Small part of the research is in the description link of those vids.
Some videos got copyright striked by blizz tho :(

**Comment by Evolvee** [comment]
https://github.com/Atlantiss/AtlantissTbcBTOLD/issues/902

![image](https://user-images.githubusercontent.com/1942409/68872065-b7e5ba80-06fd-11ea-81e8-30b9dc300a63.png)
![image](https://user-images.githubusercontent.com/1942409/68872090-c16f2280-06fd-11ea-89a9-9b9c505bdd97.png)
![image](https://user-images.githubusercontent.com/1942409/68872110-caf88a80-06fd-11ea-99cb-5347ef649809.png)

**Comment by Tereneckla** [comment]
So the manual fix on seals should be removed? As you currently judge seal A after casting Seal B.

![image](https://user-images.githubusercontent.com/50233983/84669293-fc039c80-af24-11ea-8dfa-7b11ce5e36ce.png)

**Comment by empor0** [comment]
So what's gonna happen with the "broken" interaction between seals and judgement? It's really pointless that judgement ignores global cooldown when you have to wait 0,5 for new seal to be active for judgement.

**Comment by Godmatik** [comment]
Irrelevant now as classic sealtwisting has been implemented.

Closing.
