### ISSUE TITLE
[Daily Quest][Battleground] Call to Arms - X battleground

### ISSUE THREAD

**Issue by Healweed** [Atlantiss/NetherwingBugtracker#6407]
**Description**: 
As of 13th November, i came to login at 1:32pm server time and i noticed the BG daily quest that gives the battleground dailies has two quests, instead of one.  

**Current behaviour**:
![WoWScrnShot_111319_121252](https://user-images.githubusercontent.com/52166185/68763323-12085200-0610-11ea-946a-07b5de07186b.jpg)

As said above, the BG daily quest giver has two battleground quests available to do, which shouldn't happen.
Edit: When accepting one of them ,  the other one disappears. However abandoning the quest, makes the two quests avaliable again.

**Expected behaviour**: 

Should only one battleground daily quest per day.

**Server Revision**: 
As of now, the server revision is 3187.

**Comment by Wolffenstein** [comment]
It will be fine after next restart.
