### ISSUE TITLE
[Paladin] Seal of Command/Blood double dips %dmg mods

### ISSUE THREAD

**Issue by Jumpka** [Atlantiss/NetherwingBugtracker#6408]
I'm not 100% sure about this, since weapon damage can be quite random, but imo both seals double dip %DMG increase buffs. It should be pretty obvious and easy to confirm with some huge %dmg increase buff.

**Description**: Just to make it clear what I mean by double dipping: Lets say I do 100 auto attack damage, then my SoCommand will do 70 damage. If I get 100% DMG increase buff, my auto will do 200 damage, seal will calculate it's damage as 70% of this 200, but then this 140 seal damage gets increased by my 100% damage buff, making it 280.

I'm not sure if vengeance should double dip or not. I've found some random 2008 wowhead comments saying it does with no real proof, but I've looked at some videos of paladins having berserking+avenging wrath on and seals weren't doing some crazy damage, so it definitely shouldn't double dip those buffs imo.

(btw I'm pretty sure this bug report is 100% just SoB double dipping the %DMG increase of vashj MC https://github.com/Atlantiss/NetherwingBugtracker/issues/5755 )

**Comment by Evolvee** [comment]
https://github.com/Atlantiss/AtlantissTBCBT/issues/4225
![image](https://user-images.githubusercontent.com/1942409/68871816-50c80600-06fd-11ea-8d06-df1de2eb1ac8.png)
![image](https://user-images.githubusercontent.com/1942409/68871830-57ef1400-06fd-11ea-855e-13c615f60be9.png)
https://github.com/Atlantiss/AtlantissTbcBTOLD/issues/2430
![image](https://user-images.githubusercontent.com/1942409/68871950-866cef00-06fd-11ea-84a8-bd8eb07e84aa.png)
![image](https://user-images.githubusercontent.com/1942409/68871958-8967df80-06fd-11ea-9255-829a604bda92.png)
![image](https://user-images.githubusercontent.com/1942409/68871970-8e2c9380-06fd-11ea-8277-1e211e638c93.png)

**Comment by Healweed** [comment]
> I'm not 100% sure about this, since weapon damage can be quite random
It's not random. Weapons equipped on main hand slot always deal 100% base (without any other modifiers) of your weapon damage. Off hand deals 50% damage

**Comment by Wolffenstein** [comment]
SoC gets a bonus from spell damage, did you include that?

**Comment by Wolffenstein** [comment]
I tested Seal of Command with +x% bonus damage buffs and various spell damage numbers, it even does LESS than what Dr Damage shows. I really don't see the problem with it.

**Comment by Wolffenstein** [comment]
Seal of Blood seems to behave properly as well.

**Comment by Jumpka** [comment]
Are you actually looking at the numbers or going by an addon (probably bugged one). 
https://clips.twitch.tv/MoistOpenOilFailFish
From 79 to 177 damage with +45% damage from vengeance and wings.
To me, it seems like 79 * 1.15 * 1.3 * 1.15 * 1.3 = 176.5.
First of all, I'm pretty sure things like vengeance and wings should be additive not multiplicative, so it should be 45% total, not 1.15 * 1.3 => 49.5%. And then the much more important part where your server first applies damage increase to weapon damage, calculates SoB/SoC damaged off this already increased damage, and then applies those damage increases to SoC/SoB itself, making vengeance + wings 123.5% DMG increase for those seals instead of just 45%.

Also sanc aura doesn't increase damage of SoC/SoB hits, only the 2% damage increase from improved sanc aura applies (which also double dips, as does the 6% increase from two handed weapon spec talent, that works even with one handed weapons...)
https://clips.twitch.tv/AbstemiousPiliableFerretFutureMan

**Comment by Easyfraggy** [comment]
![image](https://user-images.githubusercontent.com/36134067/70577747-1fcbdb80-1bac-11ea-8450-a8169b976c68.png)

This is from gurtogg as you can see smth is really wrong. 31K SoB during fel rage.

**Comment by Wolffenstein** [comment]
Fixed in rev 3215.
