### ISSUE TITLE
[Tempest Keep] Thaladred the Darkener is not using his Gazy ability anymore

### ISSUE THREAD

**Issue by Manaci** [Atlantiss/NetherwingBugtracker#6409]
**Current behaviour**:
Right now Thaladred the Darkener does not use his Gaze ability in the 1st phase, and just walks slowly towards the player with the most aggro.

**Expected behaviour**: 
Thaladred the Darkener should use his gaze ability in phase 1 to focus a random player for 9 seconds like he used to do a few weeks ago and like he still does in phase 3.

**Server Revision**: 
3187

**Comment by Easyfraggy** [comment]
Confirmed yesterday did not appear to use Gaze anymore. Only the Knock away.

**Comment by Wolffenstein** [comment]
It's a removed prenerf ability, the only bug here was that he got to use it in Phase 3.

Fixed in rev 3194.

**Comment by Manaci** [comment]
@Wolffenstein Weird, thought he was only losing his "teleport on gaze" ability with the nerfs, as you can see on this [video](https://youtu.be/7NkaUwX0IQA?t=66) I just found of a late kill in 2.4 or later he is still using his gaze but he's not teleporting on each gaze like he did pre-nerf.
