### ISSUE TITLE
[Item]Dragonbreath Chili does not proc

### ISSUE THREAD

**Issue by JoyyNefarian** [Atlantiss/NetherwingBugtracker#6410]
**Description**: 

https://tbcdb.com/?item=12217 does not proc.

**Expected behaviour**: 

https://tbcdb.com/?item=12217 should occasionally proc a fiery breath on attacking with melee

**Server Revision**: 

3187

**Comment by Easyfraggy** [comment]
It does proc just not when you have windfury totem / weapon effect. Atleast thats the current theory.

Would need some proof that this should work while having these effects.

**Comment by Healweed** [comment]
> https://tbcdb.com/?item=12217 should occasionally proc a fiery breath on attacking with melee

It's not supposed to proc when you attack. It's supposed however to proc when your being attacked in melee.

**Comment by Easyfraggy** [comment]
![image](https://user-images.githubusercontent.com/36134067/69149883-bfc7a500-0ad7-11ea-8268-7c1584e31276.png)

Not sure there is any bug here other than the fact that atm it does not count as a Well Fed effect and it should.

**Comment by Wolffenstein** [comment]
The proc flags are set to your attacks, it's working correctly.
