### ISSUE TITLE
3s aréna daily points

### ISSUE THREAD

**Issue by Lepo71** [Atlantiss/NetherwingBugtracker#6411]
[//]: # (Enclose links to things related to the bug using http://wowhead.com or any other TBC database.)
[//]: # (You can use screenshot ingame to visual the issue.)
[//]: # (Write your tickets according to the format:)
[//]: # ([Quest][Azuremyst Isle] Red Snapper - Very Tasty!)
[//]: # ([NPC] Magistrix Erona)
[//]: # ([Spell][Mage] Fireball)
[//]: # ([Npc][Drop] Ghostclaw Lynx)
[//]: # ([Web] Armory doesnt work)
[//]: # (To find server revision type `.server info` command in the game chat.)

**Description**: this is the second time i gont get the 20 points, 10 games played today still dont give
https://i.imgur.com/nPisp7r.png

**Current behaviour**:

**Expected behaviour**: 

**Server Revision**:

**Comment by Evolvee** [comment]
changelog
