### ISSUE TITLE
[Item]Black Bow of The Betrayer Mana Gain/Drain proc is not working correctly

### ISSUE THREAD

**Issue by Manaci** [Atlantiss/NetherwingBugtracker#6412]
**Current behaviour**:
Currently the mana gain from the [Black Bow of the Betrayer](https://db.excalibur.ws/?item=32336) is only working on [enemies without mana](https://i.imgur.com/0txidUu.png). If you shoot an enemy with a mana pool with this bow you currently do not gain any mana and [only drain 8 mana from their mana pool](https://i.imgur.com/9wqLPV7.png).

**Expected behaviour**: 
If you shoot an enemy with a mana pool with this bow you should gain 8 mana AND also drain 8 mana from their mana pool. The effect is currently useless on any enemy NPC with a mana pool.

**Server Revision**: 
3187

**Comment by Wolffenstein** [comment]
Fixed in rev 3194.
