### ISSUE TITLE
[Core][Loot] Loot issues in raid

### ISSUE THREAD

**Issue by veekk** [Atlantiss/NetherwingBugtracker#6413]
**Description**:  Here's 3 issues related to raid loot:
1. Loot range to small and lot of loot missing by some raid members 'cause of that even in case of different size of the single room (e.g. first Mother's trash room)
2. In case of Uncommon+ loot in corpse, this corpse must be lootable for any of raid members to start "group loot" event, but for now it's working only partially and lot of loot missing 'cause it can't be opened by any another raid member except assigned.
3. Partially related to 2nd one, in some cases loot can be assigned to some player, but it's still unlootable for him, until he's run away from corpse and come back. After this "manipulation" mob become lootable

**Current behaviour**: not kek

**Expected behaviour**: kek

**Server Revision**: 3187

**Comment by danbopes** [comment]
There's been a massive undertaking in the past week to clean it up by rewriting loot handlers from scratch. We'll have some more information soon when we release testing for the PTR.
