### ISSUE TITLE
[Raid][TK][Loot] Seventh Ring of the Tirisfalen probably missing in loot table 

### ISSUE THREAD

**Issue by veekk** [Atlantiss/NetherwingBugtracker#6414]
**Description**: [Seventh Ring of the Tirisfalen](http://db.excalibur.ws/?item=30028) probably missing in loot table, for long months of TK farming didn't drop any and also didn't saw any tankdain with this BIS ring 

**Current behaviour**: no ring T__T

**Expected behaviour**:  My Precious •__•

**Server Revision**: 3187

**Comment by Evolvee** [comment]
it was assigned as a global world drop with condition "only in tk" so it had pretty much close to 0% xd 
wolf 😞 

fixed

**Comment by veekk** [comment]
@Evolvee is this on live already?

**Comment by raethkcj** [comment]
@veekk revision 3192

`.server info` to check in game
