### ISSUE TITLE
[Raid][BT] Mother Shahraz

### ISSUE THREAD

**Issue by veekk** [Atlantiss/NetherwingBugtracker#6415]
**Description**:  [proof](https://www.youtube.com/watch?v=ItLDhtnjB54) of 10% soft enrage, and youtube full of retail mother videos where we can see 10% soft enrage, so it can't be "wowwiki myth" as Wolf said here #6376 

**Current behaviour**: soft kitty %)

**Expected behaviour**: soft rage! }:-|

**Server Revision**: 3187

**Comment by Wolffenstein** [comment]
It's not a proper enrage despite the message, she gets to do more random beams but does not gain any damage/attack speed buff. It already is implemented.
