### ISSUE TITLE
[Quest] Membership Benefits #5863

### ISSUE THREAD

**Issue by dshgrove** [Atlantiss/NetherwingBugtracker#6416]
[//]: # (Enclose links to things related to the bug using http://wowhead.com or any other TBC database.)
[//]: # (You can use screenshot ingame to visual the issue.)
[//]: # (Write your tickets according to the format:)
[//]: # ([Quest][Azuremyst Isle] Red Snapper - Very Tasty!)
[//]: # ([NPC] Magistrix Erona)
[//]: # ([Spell][Mage] Fireball)
[//]: # ([Npc][Drop] Ghostclaw Lynx)
[//]: # ([Web] Armory doesnt work)
[//]: # (To find server revision type `.server info` command in the game chat.)

**Description**: 
The quest [**Membership Benefits**](https://www.wowhead.com/quest=9887/membership-benefits) in Nagrand should be repeatable and reward players a sack of gem. The gem quality and amount depends on their reputation with The Consortium. 

**Current behaviour**:
You can do the quest once. It is seemingly not repeatable and does not _respawn_ at the start of a new month. Neither does it give a new quest/sack of gems when you hit a new reputation rank in the same month.

**Expected behaviour**: 
The quest should respawn at the start of each month.
The player should unlock the higher quality sack of gems when they increase their reputation rank. _E.g. if a player has already completed the revered quest and gets exalted within the same month, the exalted quest should become available._

**Server Revision**: 
3187

**Comment by Evolvee** [comment]
https://github.com/Atlantiss/NetherwingBugtracker/issues/6065
