### ISSUE TITLE
[Shaman] Grounding totem avalaible after 0.5 sec

### ISSUE THREAD

**Issue by Macumbafeh** [Atlantiss/NetherwingBugtracker#6418]
**Description**: Grounding totem have a prob. When you pop it, it is avalaible after 1 sec. (Or 0.5 sec...)

For example : a drood cast cyclone, you use Grounding totem at last Time. You will be cycloned, even if your Grounding totem is on ground...

**Current behaviour**: Grounding totem is avalaible after 1 sec (or 0.5 sec)

**Expected behaviour**: Grounding totem have to eat spell when it is casted / on the ground

**Server Revision**: 3196

I Can join video.

**Comment by Macumbafeh** [comment]
Video of my tests here : https://youtu.be/K4PHlLxA2ck

You can see at 00:40, i cast Grounding Totem at the end of cyclone, totem pop but i get cycloned ...

**Comment by Healweed** [comment]
I can confirm this. When you summon Grounding Totem, the aura of it should be immediate and never with a 0.5s, 1s delay.

**Comment by sposobniy** [comment]
the totem is really applied with a delay, and playing is very uncomfortable so many terrible moments like this : 

https://www.twitch.tv/sposobniy/clip/TalentedEphemeralAubergineArgieB8 

Grounding totem didn't take counterspell after fake cast

**Comment by Wolffenstein** [comment]
Fixed in rev 3197.
