### ISSUE TITLE
[Raid][BT]High Warlod Naj'entus tidal shield ability

### ISSUE THREAD

**Issue by kurixx** [Atlantiss/NetherwingBugtracker#6419]
[//]: # (Enclose links to things related to the bug using http://wowhead.com or any other TBC database.)
[//]: # (You can use screenshot ingame to visual the issue.)
[//]: # (Write your tickets according to the format:)
[//]: # ([Quest][Azuremyst Isle] Red Snapper - Very Tasty!)
[//]: # ([NPC] Magistrix Erona)
[//]: # ([Spell][Mage] Fireball)
[//]: # ([Npc][Drop] Ghostclaw Lynx)
[//]: # ([Web] Armory doesnt work)
[//]: # (To find server revision type `.server info` command in the game chat.)

**Description**: 
An issue with High Warlord Naj'entus who sometimes does not use his Tidal Shield ability and skips a cast. 
**Current behaviour**:
Tidal Shield ability not being used by Naj'entus every minute and skips a "rotation"  VoD: https://clips.twitch.tv/LaconicBelovedAlpacaTakeNRG
**Expected behaviour**: 
Tidal Shield Ability should be used around every minute during the encounter
**Server Revision**: 
3194

**Comment by Easyfraggy** [comment]
This must be some really rare ocurrance - been doing this boss every week since BT came out and not seen it happen once.

**Comment by kurixx** [comment]
Yeah it is also the first time I saw it yesterday, so don't know if something happened with the update just before the raid or something doesn't trigger it properly. But it was only once during the encounter at 4 min mark

**Comment by Suzaru** [comment]
Haven't seen it once and we doing the boss quite some time.

**Comment by Godmatik** [comment]
Also have never seen it once on Netherwing server, nor has anyone ever reported it.
