### ISSUE TITLE
[Object] Gurubashi Arena Chest 

### ISSUE THREAD

**Issue by d3aths** [Atlantiss/NetherwingBugtracker#642]
**Description**:  looted the chest and it hasn't despawned yet 15 min after being opened. you can see in the chat log times vs local time in the screenshot how long its been.

**Current behaviour**: empty chest is still there and able to be opened again, revealing no contents/ no popup

**Expected behaviour**:  chest should despawn in 0~5 min after being looted according to wowhead comments from tbc patches

**Server Revision**:  2060

![wowscrnshot_092618_180548](https://user-images.githubusercontent.com/16113944/46066129-4a07c800-c1b7-11e8-90f7-25972c46a745.jpg)

**Comment by maronics** [comment]
rev 2073: Chest was empty, was there directly after it spawning 2min ago all alone.

**Comment by Mentat33** [comment]
Confirming what netherwingbta said - Chest appears empty after looting first Arena Master Trinket and completing the quest "Arena Master" with Short John Mithril. Each subsequent open of the chest will not show the trinket that is in the chest unless the player HAS/IS ON the quest "Arena Grandmaster". 

This is a bug in that the Arena Master Trinket should ALWAYS be visible / lootable to a player even if they are NOT on the "Arena Grandmaster" Quest or have even COMPLETED the "Arena Grandmaster" Quest.

**Comment by Tereneckla** [comment]
Fixed

**Comment by The14me** [comment]
Still bugged

**Comment by barnabbas1** [comment]
Having the same issue
