### ISSUE TITLE
[Item][Proc] Rod of the Sun King proc chance very poor

### ISSUE THREAD

**Issue by veekk** [Atlantiss/NetherwingBugtracker#6420]
**Description**:  [Rod of the Sun King](https://www.wowhead.com/item=29996/rod-of-the-sun-king#comments) very low, giving like 100-150 for 6 min fight, old wowhead saying that it must be like 120/min, for now it's pretty useless weapon, when must be BiS

**Current behaviour**:  kek

**Expected behaviour**: pew-pew

**Server Revision**: 3196

**Comment by sposobniy** [comment]
if this guy right , proc rate is to high .  should be ~6 PPM 
old bug report of this item on warmane: 
https://www.warmane.com/bugtracker/report/57015  

https://web.archive.org/web/20140511233840/http://forums.elitistjerks.com/topic/22887-fury-dps-spreadsheet-for-30/#entry670898  

https://www.wowhead.com/item=29996/rod-of-the-sun-king#comments

**Comment by Wolffenstein** [comment]
Fixed in rev 3197.

**Comment by veekk** [comment]
@sposobniy proc is too low, 'cause 100-150 energy for 6 mins it's like 10-15 proc, so dat means 2 ppm avg

**Comment by Easyfraggy** [comment]
This should not have been changed to 6PPM it was working correctly.

6PPM is literally 10-14 procs per minute. Completely retarded.

somewhere between 1 and 3ppm AT MOST is what all the other comments than the very 2 cherrypicked ones suggest.

![image](https://user-images.githubusercontent.com/36134067/70091292-1bd41280-161c-11ea-8a05-911199f4f6a9.png)

![image](https://user-images.githubusercontent.com/36134067/70091348-3908e100-161c-11ea-867d-010ce0122e0d.png)

**Comment by Easyfraggy** [comment]
Just to show how retarded it really is right now: 

![image](https://user-images.githubusercontent.com/36134067/70095858-0fed4e00-1626-11ea-950e-ca91c4700b9c.png)

on a 229s fight thats 1 proc every 3 seconds. That's 200 energy per minute/ 20 procs/min.

**Comment by Wolffenstein** [comment]
Fixed.
