### ISSUE TITLE
[Talent] [Mage] Ignite 

### ISSUE THREAD

**Issue by th3p1n3appl3** [Atlantiss/NetherwingBugtracker#6421]
[//]: # (Talent] Mage Ignite)
[//]: # https://wowwiki.fandom.com/wiki/Ignite_(old)

The Ignite DoT deals its damage split into two equal ticks, the first at two seconds after the crit, and the second at four seconds. Using the Fireball example above, a crit of 1500 will apply an Ignite DoT of 600. The spell lands at time t, and deals 300 damage at times t+2.0 sec and t+4.0 sec. If another Fire crit occurs before either tick, any remaining damage is added to the new Ignite, resetting the duration back to 4 seconds.[1] This effectively pushes Ignite damage back when multiple crits happen in quick succession. In any event, the Ignite will only start to tick two seconds after the most recent crit, and the sum damage will always be 40% of all crit damage over time (except under certain conditions, see known bugs).

"Known bugs
Another bug occurs when two Fire crits land nearly simultaneously. Both crits should Ignite, but only one will take effect. To trigger this condition, cast an instant such as Fire Blast just as a projectile spell such as Fireball is about to land. This frequently affects elementalist mages who often double-crit with Shatter."

The issue can be closed as we have done the math and the report has found to be faulty. The math checks out.

**Description**: 
Every fire spell crit is supposed to start its own ignite DoT.
Ignite ticks 4 times in its whole duration.
I will get some spreadsheets and recount data about the number of crits correlating with the number of ignite ticks, therefore concluding that ignite is currently only able to be applied once at a time.

**Current behaviour**:
Only one ignite DoT is applied even if multiple spells crit in short period of time, not adding ignite damage from previous ticks.

**Expected behaviour**: 
Ignite damage from the previous DoT should be added up correctly.

**Server Revision**: 
3196 (not sure if that's the correct information, sorry if not)

**Comment by Suzaru** [comment]
I noticed this aswell and thought my math was off :(.

**Comment by Tereneckla** [comment]
The only bug present with ignite is this bug not existing.

"Known bugs
Another bug occurs when two Fire crits land nearly simultaneously. Both crits should Ignite, but only one will take effect. To trigger this condition, cast an instant such as Fire Blast just as a projectile spell such as Fireball is about to land. This frequently affects elementalist mages who often double-crit with Shatter."

**Comment by Godmatik** [comment]
Ignite was changed in TBC and no longer has the multiplicative damage added in from multiple crits, was confirmed from classic and it was a vanilla mechanic only.

Closing.
