### ISSUE TITLE
Position feared target 

### ISSUE THREAD

**Issue by sposobniy** [Atlantiss/NetherwingBugtracker#6423]
Description:  If you are   try to use : Shadowstep , Charge/Intercept , or Intervene .  While enemy/ (friendly target ) moving in fear effect -you will find yourself in a completely different place. 

 (look at enemy war intervene )

https://www.twitch.tv/sposobniy/clip/ZanyMildCheddarPMSTwin  

Sometimes not possible make good intervene for redirect sap , cos you just move in wrong place and your "shout" out of range on rogue .

**Comment by Tereneckla** [comment]
fixed rev 3234
