### ISSUE TITLE
Pet doesn't autocast skill "Claw"

### ISSUE THREAD

**Issue by ookkrr** [Atlantiss/NetherwingBugtracker#6424]
[//]: # (Enclose links to things related to the bug using http://wowhead.com or any other TBC database.)
[//]: # (You can use screenshot ingame to visual the issue.)
[//]: # (Write your tickets according to the format:)
[//]: # ([Quest][Azuremyst Isle] Red Snapper - Very Tasty!)
[//]: # ([NPC] Magistrix Erona)
[//]: # ([Spell][Mage] Fireball)
[//]: # ([Npc][Drop] Ghostclaw Lynx)
[//]: # ([Web] Armory doesnt work)
[//]: # (To find server revision type `.server info` command in the game chat.)

**Description**: 
My pet (cat) does not autocast its skill "Claw".

**Current behaviour**:
My pet (cat) does not autocast its skill "Claw" even when no other skill / cool downs are active and the pet has therefore enough Focus.
By clicking it, the cat uses it.

**Expected behaviour**: 
Pet should autocast "Claw" when no global cooldown is active and it has enough Focus.
(I don't know the priority of the pet's skills, perhaps from left to right?)

**Server Revision**:

**Comment by Tereneckla** [comment]
rev 3236
