### ISSUE TITLE
[bug]where did my armor disappear? 

### ISSUE THREAD

**Issue by sposobniy** [Atlantiss/NetherwingBugtracker#6425]
I can’t fully describe what exactly happened . But after 2h stream session i am found what my character is not getting armor bonus  from equipment items .  

https://clips.twitch.tv/SucculentSpineyCookieBrainSlug 

its not visual bug , but i have not idea what is this

**Comment by DaedalusMachina007** [comment]
Potentially the addons you're using are causing issues.  Try changing gear w/o addons and see if it still happens.

**Comment by Easyfraggy** [comment]
Likely addon issue. Need replication steps (without addons).

**Comment by Manaci** [comment]
dead issue

**Comment by sposobniy** [comment]
This issue  applied after respec 
https://www.twitch.tv/videos/556024271?t=04h03m31s

**Comment by Evolvee** [comment]
? u unlearned duel wield
what do u expect?
