### ISSUE TITLE
Tremor totems sometimes have "resist " fear remove .

### ISSUE THREAD

**Issue by sposobniy** [Atlantiss/NetherwingBugtracker#6426]
Problem : 

Tremor totem , sometimes not remove fear effect  cos affected dispel resistance  talent like
: [Silent resolve] priests,  and [Contagion] warlocks .  (reduces the chance your spells will be dispelled by X)

https://youtu.be/m-_Fa9Xo650   Psychic scream  not was remove after 3 Tremor tick . 

https://www.twitch.tv/sposobniy/clip/InexpensiveDifficultGrasshopperTheTarFu  fresh tremor not remove fear from my teammate (look at party debuffs) 

How it shold work : 

https://wowwiki.fandom.com/wiki/Dispel?oldid=1432725  tremor totems its not "dispel , and cant be resisted .

**Comment by Wolffenstein** [comment]
I really can't decipher this bug report.

**Comment by sposobniy** [comment]
I mean tremor totem dispel cant be resisted . 
After i drop Tremor ,totem fear not was "remove " from my teammate (look at party debuffs) in clip. 
Btw  my bad , found old bugreport of this issue https://github.com/Atlantiss/NetherwingBugtracker/issues/5726

**Comment by whissper** [comment]
I guess this report about [Tremor Totem]'s dispel mechanic that is able to fail removing fear/sleep/charm effects. Probably the main cause is aura that provides chance reduction for caster's spells to be dispelled. For example some talents got this aura effect: 
https://tbcdb.com/?spell=14787  seems like Priest's fear can be affected by this talent
https://tbcdb.com/?spell=30064  same for Warlock

**Comment by Macumbafeh** [comment]
True @whissper  but Tremor can't be resisted.
I was asking my self about it too...
In Arena i asked my self sometimes that if i were far of my totem or not when i was feared...
And it happened many Times...
I Need to test that and put a video, but i don't have a Priest or warlock...

**Comment by DaedalusMachina007** [comment]
I believe what the OP is trying to say is that Tremor Totem's dispell mechanics (for Fear, Charm, and Sleep) should not be affected by talents from other players.  The dispell cannot be prevented.

Personally would love to see Death Coil counted as a 'Fear' for purposes of Tremor Totem dispell mechanics.  According to online TBC databases (and Classic WoWhead), it has the 'Apply Aura Mod: Fear' flag as far as spell mechanics go.

PvP aside (as PvP on this server is not exactly popular), having such dispell capability for PvE would be quite useful to have.

**Comment by Wolffenstein** [comment]
Fixed in rev 3198.
