### ISSUE TITLE
Quest bug - Getting Down To Business

### ISSUE THREAD

**Issue by EdTuBrutus** [Atlantiss/NetherwingBugtracker#6427]
[//]: # ([Quest][Netherstorm] Getting Down To Business)
[//]: # ([NPC] Image of Wind Trader Marid)

**Description**:  Image of Wind Trader Marid will not complete the quest

**Current behaviour**: After returning to the summoning platform and re-summoning Wind Trader Marid, he will not complete the quest or offer any interaction.

**Expected behaviour**:  The NPC should be summoned with the question mark above its head.  It is not.

**Comment by Evolvee** [comment]
https://www.wowhead.com/quest=10271/getting-down-to-business

![image](https://user-images.githubusercontent.com/1942409/69477583-34585780-0de8-11ea-8f64-b0e23a45674a.png)
