### ISSUE TITLE
Mark of the Champion  - Bonus Damage does not get applied

### ISSUE THREAD

**Issue by DonHofbeck** [Atlantiss/NetherwingBugtracker#6428]
Faulty item: https://classicdb.ch/?item=23207

http://prntscr.com/q16ecl - Shadowbolt dmg on an undead Target without having "Mark of the Champion equipped"

http://prntscr.com/q16ews - Shadowbolt dmg on an undead target with equipped "Mark of the Champion

I have reproduced this behavior a few dozen times.

This item is a reward from Kelthuzads quest : https://classicdb.ch/?quest=9120
The bonusdamage from https://classicdb.ch/?item=19812 might also be broken.

.server info http://prntscr.com/q16j0p

**Comment by Evolvee** [comment]
@Wolffenstein https://github.com/Atlantiss/NetherwingBugtracker/issues/6156#issuecomment-520599718 similar

**Comment by Wolffenstein** [comment]
Fixed in rev 3198.
