### ISSUE TITLE
[Loot] Felmusk Shadowstalker drops Copper Ore and Rough Stone with high rate

### ISSUE THREAD

**Issue by Jezofine** [Atlantiss/NetherwingBugtracker#643]
**Current behaviour**:
[Felmusk Shadowstalker (thottbot archive)](http://web.archive.org/web/20080917163713/http://thottbot.com:80/c3763) drops Copper Ore with ~90% and Rough Stone with ~50% chance.
But this behavior totally matches other private servers db [Felmusk Shadowstalker on hellground](http://db.hellfire-tbc.com/?npc=3763).

**Expected behaviour**:
Thottbot link has no sign of this loot.

**Server Revision**: 2060

**Comment by DarthNekr0s** [comment]
that database isn't blizzard accurate though, looked on it before and it showed multiple mobs that aren't attackable as well as things like shaman totems having loot, its best to use archived thottbots etc for loot tables here

**Comment by Jezofine** [comment]
First link is literally thottbot archive with data that confirms title. Hellground link is just for example,

**Comment by xmesaj2** [comment]
fixed in rev 2081
