### ISSUE TITLE
[ZA] Mobs falling under texture

### ISSUE THREAD

**Issue by eri1997** [Atlantiss/NetherwingBugtracker#6430]
**Description**:  On the guantlet event toward Akil'zon these 2 mobs fall under textures in this exact spot. They don't go up after they fall and they can only be hit by range. Its always the same spot. 
https://imgur.com/a/z1uJEr9

**Current behaviour**  above

**Expected behaviour**:  Mobs not falling under textures.

**Server Revision**: 3196

**Comment by Easyfraggy** [comment]
Happened in the same spot for us once.

**Comment by Suzaru** [comment]
It happens when you don't pull the tempest quickly enough and you are near the stairs. The two spawning guards always fall down at the exact same spot there on the corner. Happened multiple times to us.

**Comment by Godmatik** [comment]
Duplicate
