### ISSUE TITLE
Arena pet bugged (abuse)

### ISSUE THREAD

**Issue by Highclaw** [Atlantiss/NetherwingBugtracker#6432]
[//]: # (Enclose links to things related to the bug using http://wowhead.com or any other TBC database.)
[//]: # (You can use screenshot ingame to visual the issue.)
[//]: # (Write your tickets according to the format:)
[//]: # ([Quest][Azuremyst Isle] Red Snapper - Very Tasty!)
[//]: # ([NPC] Magistrix Erona)
[//]: # ([Spell][Mage] Fireball)
[//]: # ([Npc][Drop] Ghostclaw Lynx)
[//]: # ([Web] Armory doesnt work)
[//]: # (To find server revision type `.server info` command in the game chat.)

**Description**: 

**Current behaviour**:

**Expected behaviour**: 

**Server Revision**:

**Comment by Highclaw** [comment]
Hello,

I was playing some 2s with a warlock and came across a hunter using an interesting pet. Player Hayl 

Hayleigh was using a Gutripper. After our first matchup my lock said he couldnt dot the pet when close to the pillar. On the second and third matchup I found that not only was this pet able to walk straight through the Nagrand Arena pillars but was also permanently immune to roots/hibernate/cyclone. Of course it is not unusual that a BM hunters pet gain immunity during Beastal Wraith, however I am certain this was not the case on my 6 attempts to cc the pet, repeatedly, near pillar, away from pillar and even with Natures grasp I was met with Immunity messages.

The pet was also visibly half phased into the ground.


![WoWScrnShot_112519_013512](https://user-images.githubusercontent.com/58154439/69505172-bbace480-0f28-11ea-8606-cbcd6cbb9e2b.jpg)
![WoWScrnShot_112519_013509](https://user-images.githubusercontent.com/58154439/69505173-bbace480-0f28-11ea-926b-d2159e104d85.jpg)
![WoWScrnShot_112519_013518](https://user-images.githubusercontent.com/58154439/69505174-bc457b00-0f28-11ea-8d9a-d5cced7b96e4.jpg)

**Comment by Evolvee** [comment]
Need a video of the pathing problem.

**Comment by Tereneckla** [comment]
I assume the weird pathing was because bird pets retained their ability to fly.
The other bugs likely stemmed from that.
