### ISSUE TITLE
Scryers/Aldor are not teleporting out the player in Shattrath

### ISSUE THREAD

**Issue by Healweed** [Atlantiss/NetherwingBugtracker#6433]
**Description**: 
At this moment i'm exalted with Aldor and hated with Scryers and if i try to go into the Scryers terrace, the Guardians are not kicking me out of their terrace. This is the same way as in Dalaran on WotLK

**Current behaviour**:
Player with the hated faction (Aldor or Scryers) are not being kicked out of their terrace the moment when guardians spot them and not being teleported to the elevator(lower level ofc)

**Expected behaviour**: 
Players with the hated faction (Aldor or Scryers) should be immediatly kicked out of their terrace the moment they are in range of any scryers/aldor npcs.

**Server Revision**: 
As of now, server revision is 3196

**Comment by Easyfraggy** [comment]
Some proof of what it should look like when you get "kicked out"?

**Comment by Healweed** [comment]
Yeah. Go retail.

**Comment by Healweed** [comment]
That kick thing was a thing they introduced  in retail and even on many private servers. This also appears in Wotlk when if your alliance and you try to access the sunreavers side, they simple kick you out.

**Comment by Easyfraggy** [comment]
Post a video of it - we aren't subbed to retail.

**Comment by Healweed** [comment]
> Post a video of it - we aren't subbed to retail.
I would have posted if have found something. This kick feature was a thing added in tbc, it appears in Wotlk and never appearing again. Plus no one mention anything regarding being subbed to ret

> The more work the dev has to do the less bugs get fixed. Help by supplying all the information.
Devs do what they can. Plus it's not a major bug so it can be fixed when it's avaliable.

**Comment by Easyfraggy** [comment]
Well where do you get ported to and is there an rp emote etc - this is why we need a video.

**Comment by Evolvee** [comment]
it was already working

just core fuckup again

**Comment by Healweed** [comment]
As stated before on first post, i explained that if you're in range of any Scryers/Aldor NPC that you are hated, they will teleport you to their elevator location(the bottow level)

**Comment by Healweed** [comment]
@Evolvee ty :)

**Comment by Wolffenstein** [comment]
Fixed in rev 3198.
