### ISSUE TITLE
Justicar Armor T4 4/5 set bonus' numbers are off

### ISSUE THREAD

**Issue by hederob** [Atlantiss/NetherwingBugtracker#6434]
![WoWScrnShot_112519_120015](https://user-images.githubusercontent.com/25690905/69570456-79fe5700-0f85-11ea-8c9d-b157638e246d.jpg)
![WoWScrnShot_112519_120059](https://user-images.githubusercontent.com/25690905/69570462-7ec30b00-0f85-11ea-9533-a9c7cfa8e08c.jpg)
![WoWScrnShot_112519_120221](https://user-images.githubusercontent.com/25690905/69570481-884c7300-0f85-11ea-8425-b3c6f74c354d.jpg)

**Description**:  The numbers are off 4/5 T4 4 set bonus for protection paladins. It should a % increase and not a static additive value of 15

**Current behavior**: Tested with my character; a block with holy shield hits for 239 with the 4 set and 224 without the 4 set. It should be a 15% increase in damage and not +15.

**Expected behavior**: It should be a 15% increase in damage on holy shield, therefore it should hit for 257-258. Even with a difference of 4 spell power, holy shield scales very poorly with spell power so it's contribution to the holy shield damage is negligible at most and it should not be considered.

**Server Revision**: 
3196

**Comment by Easyfraggy** [comment]
You don't show your block value on the screenshots.

**Comment by hederob** [comment]
Block value matters for shield slam not for holy shield.

**Comment by devo6969** [comment]
Still an issue on the PTR. Holy Shield 225 hits with 4piece 250 spellpower after (took off shoulders with 22 spellpower) and put on  Ashyen's Gift (has 22 spellpower). Holy shield only hit for 210, should of been 243,75 with 4 piece.

**Comment by Godmatik** [comment]
Looks like an in-game tooltip typo.

On wowhead, it says it increases holy shield damage by "15", and not "15%".
The aura mod states this also

https://www.wowhead.com/tbc/spell=37185/increased-holy-shield

Closing
