### ISSUE TITLE
[Item][Spell] Fel Reaver Piston incorrectly scales with bonus healing

### ISSUE THREAD

**Issue by Tereneckla** [Atlantiss/NetherwingBugtracker#6435]
[//]: # (Enclose links to things related to the bug using http://wowhead.com or any other TBC database.)
[//]: # (You can use screenshot ingame to visual the issue.)
[//]: # (Write your tickets according to the format:)
[//]: # ([Quest][Azuremyst Isle] Red Snapper - Very Tasty!)
[//]: # ([NPC] Magistrix Erona)
[//]: # ([Spell][Mage] Fireball)
[//]: # ([Npc][Drop] Ghostclaw Lynx)
[//]: # ([Web] Armory doesnt work)
[//]: # (To find server revision type `.server info` command in the game chat.)

**Description**: 
![image](https://user-images.githubusercontent.com/50233983/69581573-084ef900-0fd7-11ea-9391-30300ea2dc28.png)
https://www.wowhead.com/item=30619/fel-reavers-piston#comments
https://github.com/OregonCore/OregonCore/issues/1165

**Current behaviour**:
It ticks for 125+something from bonus healing
**Expected behaviour**: 
It ticks for 125
**Server Revision**: 3196

**Comment by Wolffenstein** [comment]
Fixed in rev 3198.
