### ISSUE TITLE
Bugged stealth Succubus in Arca hc

### ISSUE THREAD

**Issue by RealFundin** [Atlantiss/NetherwingBugtracker#6436]
[//]: # (Enclose links to things related to the bug using http://wowhead.com or any other TBC database.)
[//]: # (You can use screenshot ingame to visual the issue.)
[//]: # (Write your tickets according to the format:)
[//]: # ([Quest][Azuremyst Isle] Red Snapper - Very Tasty!)
[//]: # ([NPC] Magistrix Erona)
[//]: # ([Spell][Mage] Fireball)
[//]: # ([Npc][Drop] Ghostclaw Lynx)
[//]: # ([Web] Armory doesnt work)
[//]: # (To find server revision type `.server info` command in the game chat.)

**Description**: 
In Arcatraz heroic mods, the 2 mobs Skulking Witch (succubus types) are bugged in the room where stand Wrath-Scryer Soccothrates and Dalliah the Doomsayer.
**Current behaviour**:
Those mobs dont take damages unless they kill one of the party members and go back to stealth unless AOE are casted at their location
**Expected behaviour**: 
Those mobs should take damages once unstealth and should keep being in combat without "soft" reseting
**Server Revision**: 
[3197]

**Comment by Healweed** [comment]
Also you forgot to mention that by doing a soft reset, you can actually despawn the succubus. This doesn't happen always, but lots of arca groups have done it always @Wolffenstein

**Comment by Wolffenstein** [comment]
Fixed in rev 3198.
