### ISSUE TITLE
[Core Mechanic] [Reupload] Low level damage/dodge is improper

### ISSUE THREAD

**Issue by G3dSage** [Atlantiss/NetherwingBugtracker#6438]
**Description**: While fighting low-level mobs, some do zero damage entirely while others do too little. I have compiled a video-comparison showcasing 2008 TBC gameplay and current Netherwing gameplay.

**Comparison**:
 There is a nice channel on youtube with some 2008 TBC wow videos on it. I decided to recreate some moments from those videos to see how authentic the starting experience is in Netherwing. Overall it's very well done, with NPC idles and patrol paths, the dynamic respawning is awesome. But some issues arose.
 We are both running a **stock level 4 warlock** and we will be completing the "wolves across the border" and "Brotherhood of thieves" quests in Elwynn Forest starting area.

**Video 1: "Wolves across the border"** 
- Original:  https://www.youtube.com/watch?v=T4OY9FRvFoU
- Netherwing:  https://vimeo.com/375727402
 As can be noticed
>The _level 1 Young Wolf_ constantly whiffs it's attacks! I even disabled the "Demon Skin" defense/regen buff to see if it's a defense issue. If you look closely, you can see my character performing the "took damage" animation and pain grunt. So it seems to be an interesting issue.

>My melee attacks do _1-2 damage_ instead of the _2-3_ done in the video

>The _level 2 Timber Wolf_ reaches me with damage, however it does a measly _1 damage_ compared to _1-2 (2 mostly)_ being done in the original.

**Video 2: "Brotherhood of thieves"**
-Original:  https://www.youtube.com/watch?v=hPxfRq8M9ek
-Netherwing:  https://vimeo.com/375733584
 >The _level 3 Defias Thugs_ all dealt _1-2 damage_ while I did _1-2_ to them. In the video, the _Level 3 Defias Thug_ did _2-3 damage_ and the player did _2-3_ as well.

>Ignore the first _Level 4 Defias Thug_. I accidentaly cast a damage-lowering curse on her. The second one did _1-2 damage_ while I did _1 (presumably 1-2)_ to her. In the video, the _level 4 Defias Thug_  does _3-4 damage_ while the player does _2-3_

**Conclusion**
 It may all seem like a **giant nitpick** but I picked the low-level areas precisely because the damage dispersion at higher levels is even higher and in raids would mean a difference between life and death. Blizzard have very carefully balanced these things out. Don't let it go to waste.

**Server Revision**: 
https://prnt.sc/q2g60g

**Comment by Evolvee** [comment]
its just some core bug, all the NPCs used to do normal dmg(way more than on stock)

**Comment by Wolffenstein** [comment]
Fixed in rev 3198.

**Comment by G3dSage** [comment]
noice
thanks devs
