### ISSUE TITLE
[Quest][Daily][ Wanted: Rift Lords ] Not giving credit

### ISSUE THREAD

**Issue by Healweed** [Atlantiss/NetherwingBugtracker#6439]
**Description**: 
Today, as of 29th November, i went into a Black Morass Heroic and successfuly i got 4 Rift Lords spawned during the Heroic. The issue at hand is that of the 4 Rift Lords spawned, i've got only 2 of them credited.
**Current behaviour**:
At this moment, rift lords are giving and not giving credit towards the quest. Might be because core has two NPCs IDs(Not sure about this tbh)

**Expected behaviour**: 
Like many other normal wanted daily quests, it should give you credit, regardless of what mode you are, either be normal or Heroic version

**Server Revision**: 
As of now, server revision is 3196

**Comment by Wolffenstein** [comment]
Fixed in rev 3198.
