### ISSUE TITLE
Improved Blizzard; Permafrost

### ISSUE THREAD

**Issue by superstar333** [Atlantiss/NetherwingBugtracker#644]
**Current behaviour**:
Sometimes a Mob gets the debuff of the Blizzard slow but the effect doesnt work
**Expected behaviour**: 
Mob should be slowed

Edit: While they run towards you and arent already slowed, they wont get the effect of "Improved Blizzard" if you cast it

Maybe Permafrost doesnt work correctly, seems like the mobs are moving too fast

**Comment by xmesaj2** [comment]
permafrost probably https://github.com/Atlantiss/NetherwingBugtracker/issues/412

**Comment by Easyfraggy** [comment]
Possibly related to https://github.com/Atlantiss/NetherwingBugtracker/issues/93

**Comment by Easyfraggy** [comment]
Did you retest after the fix to #93 ?

**Comment by Brasso** [comment]
This works now, just tested. Can close.
