### ISSUE TITLE
[Spell] Judgement seems to never miss

### ISSUE THREAD

**Issue by Tereneckla** [Atlantiss/NetherwingBugtracker#6442]
[//]: # (Enclose links to things related to the bug using http://wowhead.com or any other TBC database.)
[//]: # (You can use screenshot ingame to visual the issue.)
[//]: # (Write your tickets according to the format:)
[//]: # ([Quest][Azuremyst Isle] Red Snapper - Very Tasty!)
[//]: # ([NPC] Magistrix Erona)
[//]: # ([Spell][Mage] Fireball)
[//]: # ([Npc][Drop] Ghostclaw Lynx)
[//]: # ([Web] Armory doesnt work)
[//]: # (To find server revision type `.server info` command in the game chat.)

**Description**: https://www.youtube.com/watch?v=B6RIMIBsIPk

![](https://cdn.discordapp.com/attachments/596075260705767450/650332418292711426/bugreport.png)
![](https://cdn.discordapp.com/attachments/596075260705767450/650332447766085673/bugreport2.png)
![](https://cdn.discordapp.com/attachments/596075260705767450/650332472869126154/bugreport3.png)
![](https://cdn.discordapp.com/attachments/596075260705767450/650332501826469898/bugreport4.png)

![](https://i.imgur.com/DGxg5uV.jpg)
This is the DrDamage window where it gets classified as spell.
![](https://i.imgur.com/LSiJY4Y.jpg)

**Server Revision**: 3196

**Comment by Easyfraggy** [comment]
DrDamage is not a valid source.

**Comment by Tereneckla** [comment]
closed same as #6507
