### ISSUE TITLE
[Spell][Mage] Fireball DoT scales with +dmg

### ISSUE THREAD

**Issue by Aite89** [Atlantiss/NetherwingBugtracker#6443]
Currently, the fireball DoT scales quite strongly with +dmg, a short test suggests about 17.5% scaling per tick. Fireball DoT should not scale at all with +dmg.

This leads to firemages doing significantly more damage than they should.

**Comment by Wolffenstein** [comment]
Any sources?

**Comment by Aite89** [comment]
https://wowwiki.fandom.com/wiki/Spell_power_coefficient?oldid=1492745
wowwiki from July 2008.
You can also verify this from dr. damage /rawr etc.

**Comment by Wolffenstein** [comment]
It has 0 coeff set to DoT in the database, so not sure how that's possible, I'll test it out later.

**Comment by Aite89** [comment]
Thank you. Looking at firemage's logs, they seem to be making around 7-8% of their damage from the dot, where it should be around 1.5%.

**Comment by Silbotronic** [comment]
This is caused by the talent "Empowered Fireball", which erroneously adds 15% to the DoT portion as well as the DD portion.

**Comment by Tereneckla** [comment]
Fixed
