### ISSUE TITLE
[Quest]Araj's Scarab

### ISSUE THREAD

**Issue by isnake120** [Atlantiss/NetherwingBugtracker#6444]
https://classic.wowhead.com/quest=5804/arajs-scarab

**Description**: 
this quest is in trouble, when Mob Araj the Summoner is killed and releases the object "the araj phylactery, and when you click on an object to get the beetle beetle, an" invalid target "message appears so no complete the quest

**Current behaviour**:
the object dropped by mob has no loot, "invalid target" appears
**Expected behaviour**: 
the object dropped by mob needs to be looted so getting Araj's Scarab to complete the quest
**Server Revision**:

**Comment by Evolvee** [comment]
works fine for me, try to delete cache, if the problem persists, reopen
