### ISSUE TITLE
Pet seems to be always unhappy

### ISSUE THREAD

**Issue by raidenbeast** [Atlantiss/NetherwingBugtracker#6445]
[//]: # (Enclose links to things related to the bug using http://wowhead.com or any other TBC database.)
[//]: # (You can use screenshot ingame to visual the issue.)
[//]: # (Write your tickets according to the format:)
[//]: # ([Quest][Azuremyst Isle] Red Snapper - Very Tasty!)
[//]: # ([NPC] Magistrix Erona)
[//]: # ([Spell][Mage] Fireball)
[//]: # ([Npc][Drop] Ghostclaw Lynx)
[//]: # ([Web] Armory doesnt work)
[//]: # (To find server revision type `.server info` command in the game chat.)

**Description**: 
My pet is suddenly unhappy and doesnt become happy no matter how much food I give
**Current behaviour**:
Unhappy
**Expected behaviour**: 
Happy
**Server Revision**:

**Comment by eri1997** [comment]
Food needs to be the highest level your pet can take  . Also at early loyalty levels pet happiness drops fast. It's a lot better later on. Don't think there is any bug here imo.

**Comment by Evolvee** [comment]
need more info
