### ISSUE TITLE
[Quest] The Cudgel of Kar’desh 

### ISSUE THREAD

**Issue by tsey123** [Atlantiss/NetherwingBugtracker#6446]
![B4CE15BB-CE92-4822-9C5C-09FCC5229B73](https://user-images.githubusercontent.com/58397141/69919920-5c982400-1482-11ea-9a82-9e55459a16cf.jpeg)
![0FDBCC70-9166-42C0-ADF8-43F6992882A0](https://user-images.githubusercontent.com/58397141/69919921-5d30ba80-1482-11ea-9192-28e5583eef14.jpeg)
![1F1F6E6E-49CD-43E5-BF3A-DEBA5D1CB4AD](https://user-images.githubusercontent.com/58397141/69919922-5d30ba80-1482-11ea-8b08-99a53d14606e.jpeg)

[//]: # (Enclose links to things related to the bug using http://wowhead.com or any other TBC database.)
[//]: # (You can use screenshot ingame to visual the issue.)
[//]: # (Write your tickets according to the format:)
[//]: # ([Quest] Slave Pens- The Cudgel of Kar’desh)
[//]: # ([NPC] Skar’this the Heretic
[//]: # (To find server revision type `.server info` command in the game chat.)

**Description**: 
I can’t turn the quest. NPC can’t see the two items needed in my inventory (Earthen Signet and Blazing Signet). 
**Current behaviour**:
Players cant turn the quest and get the reward.
**Expected behaviour**: 
Players should turn the quest and receive the reward.
**Server Revision**: 3196

**Comment by Healweed** [comment]
Don't wanna be mean or anything, but you really should provide the screenshot with both the quest items and being in front of the Npc.

**Comment by tsey123** [comment]
Just uploaded screenshots with the issue.

**Comment by Healweed** [comment]
damn :O that is terrible luck unfortunally. Well you got both signets and you're in front of the NPC. Try speak to one of the GMs in discord to see if they can help ya with this @tsey123

**Comment by lyubomeer** [comment]
try to put items in bank and take them out again.

**Comment by Drayo** [comment]
Yeah it can happen when you put stuff in your bank, moving them back and forth and relogging in between often helps.

- One fix making life easier on GMs would be to prevent the items from being destroyed when abandoning this specific quest.

Does not seem like many had this problem though. Can probably be closed since it would kind of a global issue.
