### ISSUE TITLE
[NPC] Gravelsnout Forager is floating in the air on his way

### ISSUE THREAD

**Issue by Jezofine** [Atlantiss/NetherwingBugtracker#645]
**Current behaviour**:
SpawnId - (Entry: 4114, Id: 1) GUIDLow: 33524

**Server Revision**: 2060

**Comment by Emityx** [comment]
ID: 1 and ID: 2 cannot be found any more.  I saw ID: 2 walk into the texture.  Might be the same issue with ID: 1. Their path need to be corrected though.

**Comment by aresbrutus** [comment]
Corrected in one of the next updates.
