### ISSUE TITLE
Enslaved archeologist

### ISSUE THREAD

**Issue by alandrar** [Atlantiss/NetherwingBugtracker#6450]
**Description**: NPC Enslaved Archeologist doesn't drop anything https://tbcdb.com/?npc=8402

**Current behaviour**: They don't drop anything

**Expected behaviour**: Those NPCs should drop items...

**Server Revision**: 3196

**Comment by Evolvee** [comment]
its not supposed to drop anything, dont use stock server DBs, use only official sources
