### ISSUE TITLE
[Profession] Engineering bugged for LH transferred chars

### ISSUE THREAD

**Issue by vladkuzm** [Atlantiss/NetherwingBugtracker#6451]
Lights hope transferred characters with engineering cant learn Master Engineering at the trainer even with 300 skill. Atm only available option is Apprentice and when i try to learn it i get warning "You may only know two professions at any time....". Also spellbook is missing Engineering button, but there is specialization(Gnomish Engineer).

Server revision: 3196

**Comment by GMThunderan** [comment]
Send a GM ticket if this happens. Should be fixed, if not I can fix it with a command.
