### ISSUE TITLE
[Item] Black Bow of the Betrayer breaking Scatter Shot and possibly Wyvern Sting + remaining bugs

### ISSUE THREAD

**Issue by Manaci** [Atlantiss/NetherwingBugtracker#6452]
Since I don't play MM, a guy on the Discord (who was too lazy to make an account here) said that has Scatter Shot was being interrupted by his own mana drain from said bow, an old bug that got fixed in late TBC as seen [here](https://wowwiki.fandom.com/wiki/Patch_2.4.0).  Fairly sure this also happens with Wyvern Sting and said bow too.

_"The proc from [Black Bow of the Betrayer] will no longer break crowd control effects such as Scatter Shot."_

After the other post I made [here](https://github.com/Atlantiss/NetherwingBugtracker/issues/6412), the mana drain got fixed but not 100%, as seen in [this](https://i.imgur.com/uoNLvUR.jpg) screenshot, where the old bugged 0 mana drain is still shown in the combat log and clutters it because of this. 

The mana gain also seems to do a miniscule amount of "invisible" aoe threat that is annoying when you pull 4 mobs with your pet and then 3 of them go to you because you gain mana from the enemy your pet is on. The mana gain should do 0 threat here and not pull mobs with 0 threat from anything on you.
So with these 3 bug fixes, this bow should be bug free.

**Server Revision**: 
3196

**Comment by Easyfraggy** [comment]
Are you sure that it shouldn't generate threat? Mana gain / drain generated agro at 0,5x on every target in combat. Would need some source I think that this should be exempt

**Comment by Manaci** [comment]
@Easyfraggy 

Mana Drains **NEVER** generate threat (checked both Mana Burn and Viper Sting on the server and they both generate 0 threat (outside of the dmg from Mana Burn) and Mana Gain **USUALLY** generates threat. The 0.5x amount you mentioned was for mana gain only and not for all mana gains in the game. As far as I know, the [Insightful Earthstorm Diamond](https://db.excalibur.ws/?item=25901) mana proc does not generate any threat.

Anyways, I have checked old archives, old forums, Cheeky's Hunter Spreadsheet etc. and found **ZERO** mention of any threat generation from this ability. It also makes 0 sense that Blizzard would have it work like that since it's only annoying people who farm. Pretty sure it's just a stock bug of them putting some mana gain abilities in the threat pool or else there would surely have been mentions of such a thing somewhere. This bow has been bugged plenty already.

**Comment by Godmatik** [comment]
Fixed now
