### ISSUE TITLE
[Loot System] Got the same item twice

### ISSUE THREAD

**Issue by Tereneckla** [Atlantiss/NetherwingBugtracker#6453]
[//]: # (Enclose links to things related to the bug using http://wowhead.com or any other TBC database.)
[//]: # (You can use screenshot ingame to visual the issue.)
[//]: # (Write your tickets according to the format:)
[//]: # ([Quest][Azuremyst Isle] Red Snapper - Very Tasty!)
[//]: # ([NPC] Magistrix Erona)
[//]: # ([Spell][Mage] Fireball)
[//]: # ([Npc][Drop] Ghostclaw Lynx)
[//]: # ([Web] Armory doesnt work)
[//]: # (To find server revision type `.server info` command in the game chat.)

**Description**: 
![image](https://user-images.githubusercontent.com/50233983/70087051-d7447900-1613-11ea-8e25-26bdc0e27153.png)
Insidious Bands x2

**Current behaviour**:

**Expected behaviour**: 

**Server Revision**: 3199

**Comment by veekk** [comment]
![image](https://user-images.githubusercontent.com/12899687/70090951-d3b8ee00-1623-11ea-99f4-27c9a0cba341.png)
same

**Comment by Wolffenstein** [comment]
Fixed.
