### ISSUE TITLE
Akilzon Bug: Boss evades midfight

### ISSUE THREAD

**Issue by Pulodin** [Atlantiss/NetherwingBugtracker#6454]
[//]: # (Enclose links to things related to the bug using http://wowhead.com or any other TBC database.)
[//]: # (You can use screenshot ingame to visual the issue.)
[//]: # (Write your tickets according to the format:)
[//]: # ([Quest][Azuremyst Isle] Red Snapper - Very Tasty!)
[//]: # ([NPC] Magistrix Erona)
[//]: # ([Spell][Mage] Fireball)
[//]: # ([Npc][Drop] Ghostclaw Lynx)
[//]: # ([Web] Armory doesnt work)
[//]: # (To find server revision type `.server info` command in the game chat.)

**Description**: Boss evades midfight. 
https://youtu.be/akcvhbvSxH8
Video of it. Time in description. It occured after server update. Happened at all pulls. 

**Current behaviour**:

**Expected behaviour**: 

**Server Revision**:

**Comment by Easyfraggy** [comment]
The video has very bad angles but as far as I can tell its either related to the knock into the air shortly after the cloud or the cloud itself.

**Comment by Pulodin** [comment]
@Easyfraggy I was healing, not making video. We watched. Sometimes after knock up in the iar, after storm, after someone dies. We havent figured it out. But the problem is still there.

**Comment by Wolffenstein** [comment]
Should now be fixed.
