### ISSUE TITLE
[Core][Loot] New loot system completely broken

### ISSUE THREAD

**Issue by veekk** [Atlantiss/NetherwingBugtracker#6455]
**Description**: 
Lot of issues there, I'll try to list what I managed to get:
1. Duplicate loot #6453 
2. Loot message appears twice after roll like Username won: 99 - Need Username received [VERY EPIC RARE ITEM]
3. Master loot completely broken, not possible to give loot except passing master looter to this guy who must get loot, moving to the same group don't work or works in very rare situations.
4. Loot range awesome low, it was low before update, but now it's like nothing. E.g. at Azgalor guys who died under Thrall get boss as unlootable and it's like... ******
5. will add another stuff if something else will occur
6. upd: quest items from bosses bugged and lootable for all 25 guys, WOW
![telegram-cloud-photo-size-2-5420150115559123852-m](https://user-images.githubusercontent.com/12899687/70110189-e00a6e80-1656-11ea-866c-bbe94542b059.jpg)

7. duplicate loot after win stacking items 
![telegram-cloud-photo-size-2-5420565400241941361-y](https://user-images.githubusercontent.com/12899687/70105197-d712a080-1648-11ea-895c-d9ee89d93543.jpg)

**Current behaviour**: wtf

**Expected behaviour**: nice

**Server Revision**: 3199

**Comment by Easyfraggy** [comment]
Seems people didn't test it much on the ptr.

**Comment by Wolffenstein** [comment]
2. Not a bug
4. It's literally 1yd bigger compared to the state before the rework
7. Not a bug, if it dropped 2 Fel Armaments it will tell you, you've won 2 of them after a roll (even if the roll window displays only 1). Nothing has changed except for the message.

**Comment by veekk** [comment]
3. why those guys cant see loot then? no corpse release, no dc, just following tactics
4. there's shouldn't be any mobs with multiple armaments, seems to be related to dullicate loot (1)

**Comment by lyubomeer** [comment]
7. It's not duplicate loot. It used to drop more than one before as well.

**Comment by Wolffenstein** [comment]
1. Fixed
2. Not a bug
3. Fixed
4. Should work better now
6. Fixed
7. Was already happening before, related to individual loot tables, not the loot system entirely

**Comment by veekk** [comment]
6. @Wolffenstein if nothing was changed there, how can be real that entire raid get Kaels bis necks for a singe run? When large part of server doing in very commonly and nothing like was reported before? I'm just curious
