### ISSUE TITLE
The Bait for Lar'korwi

### ISSUE THREAD

**Issue by Daimss** [Atlantiss/NetherwingBugtracker#6458]
Quest: The Bait for Lar'korwi (https://classic.wowhead.com/quest=4292/the-bait-for-larkorwi)

**Description**: Have to use item [Preserved Threshadon Meat] near the rock at 80.0, 50.0 in Un'Goro. This should spawn [Preserved Threshadon Carcass] on the rock. With carcass spawned, 2nd quest item can be used to summon the mob.

**Current behaviour**: [Preserved Threshadon Meat] is consumed upon use, but carcass does not spawn. Cannot use 2nd quest item to summon the quest mob, as it requires the carcass to be spawned.
Tried in 4 different locations near the rock.

Proof: https://youtu.be/AtUkq4C3ESg

**Comment by Easyfraggy** [comment]
Seems to have broken with the latest patch.

**Comment by Daimss** [comment]
One restart later and it seems to have fixed itself. Just completed without issue.
