### ISSUE TITLE
Pet is dead and I can't catch a new one

### ISSUE THREAD

**Issue by vikanka85** [Atlantiss/NetherwingBugtracker#6459]
Hi Description:
As im playing as a Hunter. When i was die and gonna call my pet it says "Your target is dead" -  and when i even try too tame another one, it says " you already controll a summoned creature". My pet is not at my stables either. Cant get him back by myself or even get another one.
Current behaviour:
as above stated
Expected behaviour:
To be able too catch new  pet.
Server Revision:
Character name: Hawanna
Race: Troll 
Class: Hunter
Server: Netherwing (PVP)
Faction: Horde.

Ty!

**Comment by Evolvee** [comment]
contact GMs

**Comment by Evolvee** [comment]
btw use revive

**Comment by Easyfraggy** [comment]
Delete cache and errors folder.
