### ISSUE TITLE
[Lootsystem] Trashloot FFA even when grouplooting

### ISSUE THREAD

**Issue by Suzaru** [Atlantiss/NetherwingBugtracker#6460]
**Description**: 
Trashloot (cloth for example) is free for all, even when loot is set to grouploot. Not entirely sure if this is intended? No answer in discord. Thus the bugtracker.

**Current behaviour**:
White/below quality is free for all.

**Expected behaviour**: 
"Trashloot" should be evenly split when grouplooting.

**Server Revision**: 
3199

**Comment by Wolffenstein** [comment]
Fixed.
