### ISSUE TITLE
Group Loot distribution leaves corpses unskinnable

### ISSUE THREAD

**Issue by aeturnum** [Atlantiss/NetherwingBugtracker#6461]
Description:
When the loot system distributes loot based on rolls, the corpse is left empty, but is still marked in game as lootable and never becomes skinnable.

Current behaviour:
The icon lights up the corpse can be looted and your character will bend over if you click it, but no window opens and you stand right back up. The corpse never becomes skinnable

Expected behaviour:
Once the loot system gives out an item based on rolls and the corpse is empty, it should transition to skinnable. 

Server Revision:
3199

**Comment by Wolffenstein** [comment]
Should be fixed now.
