### ISSUE TITLE
[Raid][Black Temple] Teleport issues

### ISSUE THREAD

**Issue by veekk** [Atlantiss/NetherwingBugtracker#6462]
**Description**: There's 2 known issues related to teleport:
1. after tp hunters pet losing all buffs, e.g. food etc.
2. after council killing akama tp replaced by council room, but second option must be added instead of

**Server Revision**: 3199

**Comment by Wolffenstein** [comment]
Source?

**Comment by veekk** [comment]
![image](https://user-images.githubusercontent.com/12899687/71049084-0e557700-214a-11ea-9b29-f2782591e485.png)
screenshot from current BFA version

**Comment by veekk** [comment]
![image](https://user-images.githubusercontent.com/12899687/71049100-1b726600-214a-11ea-997a-d42d620725b9.png)

**Comment by Wolffenstein** [comment]
Fixed in rev 3212.
