### ISSUE TITLE
[Raid][Black Temple] Reliquary of Soul 

### ISSUE THREAD

**Issue by veekk** [Atlantiss/NetherwingBugtracker#6463]
**Description**: curse of tongues can be applied at 2nd phase, must not be

**Current behaviour**: kek

**Expected behaviour**: not kek

**Server Revision**: 3199

**Comment by Wolffenstein** [comment]
Can someone translate this to English?

**Comment by veekk** [comment]
@Wolffenstein updrafts

**Comment by veekk** [comment]
wrong bugreport
