### ISSUE TITLE
[Item] Weapon procs that steal life not scaling with spell power

### ISSUE THREAD

**Issue by sgilmour91** [Atlantiss/NetherwingBugtracker#6465]
[//]: # (Enclose links to things related to the bug using http://wowhead.com or any other TBC database.)
[//]: # (You can use screenshot ingame to visual the issue.)
[//]: # (Write your tickets according to the format:)
[//]: # ([Quest][Azuremyst Isle] Red Snapper - Very Tasty!)
[//]: # ([NPC] Magistrix Erona)
[//]: # ([Spell][Mage] Fireball)
[//]: # ([Npc][Drop] Ghostclaw Lynx)
[//]: # ([Web] Armory doesnt work)
[//]: # (To find server revision type `.server info` command in the game chat.)

**Description**: Multiple items that have a chance on hit to steal life proc, aren't scaling with spell power. Here is a list of the items that should be scaling in this manner:

Fist of the Damned
https://classic.wowhead.com/item=10804/fist-of-the-damned      
[[Item] Fist of the Damned no scaling #6083](https://github.com/Atlantiss/NetherwingBugtracker/issues/6083)

Demon Forged Breastplate
https://classic.wowhead.com/item=12628/demon-forged-breastplate#comments
[[Item] Demon Forged Breastplate no Scaling #5762](https://github.com/Atlantiss/NetherwingBugtracker/issues/5762)

Wraith Scythe
https://classic.wowhead.com/item=11920/wraith-scythe

Revenger
https://www.wowhead.com/item=28311/revenger&bonus=4099#comments

Ancient Hakkari Manslayer
https://classic.wowhead.com/item=19852/ancient-hakkari-manslayer

Neretzek, the Blood Drinker 
https://classic.wowhead.com/item=21856/neretzek-the-blood-drinker

Glaive of the Pit
https://www.wowhead.com/item=28774/glaive-of-the-pit

Shadowstrike
https://classic.wowhead.com/item=17074/shadowstrike#comments:80

FIXED
Blade of Unquenched Thirst
https://www.wowhead.com/item=31193/blade-of-unquenched-thirst
[[Item] Blade of Unquenched Thirst - proc dmg does not scale #6153 ](https://github.com/Atlantiss/NetherwingBugtracker/issues/6153)

**Current behaviour**:

The listed weapons/armor currently do not scale with any spell power at all.

Wraith Scythe
![image](https://user-images.githubusercontent.com/42743582/70294713-67202980-17b2-11ea-9c6f-e1ef8c8106c4.png)
![image](https://user-images.githubusercontent.com/42743582/70294737-756e4580-17b2-11ea-9ce7-a5dc23f38dcb.png)

Demon Forged Breastplate
![image](https://user-images.githubusercontent.com/42743582/70294756-8028da80-17b2-11ea-85f7-859c3434aff7.png)
![image](https://user-images.githubusercontent.com/42743582/70294774-92a31400-17b2-11ea-9673-af6a5f9b5e6e.png)

**Expected behaviour**: 

All of the weapons/armor should scale with 100% spell power.

For all the weapons, this results in 100% increase from spell power for both the heal and damage
For Demon Forged Breastplate, this 100% increase is divided by 4, for each tick of the proc.

Wraith Scythe:
![image](https://user-images.githubusercontent.com/42743582/70294801-ad758880-17b2-11ea-856c-0961de8d8d8b.png)

Fist of the Damned:
![image](https://user-images.githubusercontent.com/42743582/70294845-d8f87300-17b2-11ea-9b2f-5379433a8c5f.png)

Revenger:
![image](https://user-images.githubusercontent.com/42743582/70294908-207eff00-17b3-11ea-9d7c-973cfbb443d9.png)

Ancient Hakkari Manslayer:
![image](https://user-images.githubusercontent.com/42743582/70294941-38ef1980-17b3-11ea-97fe-dfb50b9645b1.png)

Neretzek, the Blood Drinker:
![image](https://user-images.githubusercontent.com/42743582/70295009-6cca3f00-17b3-11ea-85c3-80cb5d156e1e.png)

**Server Revision**: 3199

**Comment by Wolffenstein** [comment]
Fixed in rev 3202.
