### ISSUE TITLE
Unable to Loot Vials (Kael and Vashj)

### ISSUE THREAD

**Issue by Baelek** [Atlantiss/NetherwingBugtracker#6466]
**Description**:  When killing Lady Vashj and Kael'thas Sunstrider, the members needing vials cannot loot it.

**Current behaviour**: When a raid member attempts to loot it, it says that they do not have permission to loot that item. This issue persists even when switching it to FFA or moving the people to the ML's group.

**Expected behaviour**: The raid member should be able to loot the vial.

**Server Revision**: 3199

**Comment by Suzaru** [comment]
Can anybody confirm this? No need to do attunements then until fixed.

**Comment by Baelek** [comment]
The guild <Lethal> can confirm that his has happened for Vashj, and there was a horde side guild that confirmed this on Kael'thas (per world chat and #support in Discord)

**Comment by Baelek** [comment]
And here's the kill where we ran into the issue https://youtu.be/TNke4SuAoVA

**Comment by Wolffenstein** [comment]
Fixed.
