### ISSUE TITLE
[Item] [Silithus] Wind Stone problems

### ISSUE THREAD

**Issue by Tereneckla** [Atlantiss/NetherwingBugtracker#6467]
[//]: # (Enclose links to things related to the bug using http://wowhead.com or any other TBC database.)
[//]: # (You can use screenshot ingame to visual the issue.)
[//]: # (Write your tickets according to the format:)
[//]: # ([Quest][Azuremyst Isle] Red Snapper - Very Tasty!)
[//]: # ([NPC] Magistrix Erona)
[//]: # ([Spell][Mage] Fireball)
[//]: # ([Npc][Drop] Ghostclaw Lynx)
[//]: # ([Web] Armory doesnt work)
[//]: # (To find server revision type `.server info` command in the game chat.)

**Description**: Wind Stones don't respawn or their respawn timer is way too long.
https://wowwiki.fandom.com/wiki/Wind_stone
This speaks of around 15 minute respawn for the regular Wind Stones and around 3 hours for a greater Wind Stone. Lesser Wind Stones likely have an a lot shorter respawn timer than 15 minutes or almost instant.

It has been 1:30 hours and I have seen no respawns at all.
4 more hours (so 5:30 total), still no respawn. So I'd say they don't respawn at all.

Furthermore, when summoning a  member of the abyssal council, the stones only attempt to remove the set items from your inventory. You get to keep everything you have equipped and can summon indefinitely.
![WoWScrnShot_120619_195256](https://user-images.githubusercontent.com/50233983/70348095-46afa800-1862-11ea-9b01-98b77a0560e3.jpg)
Head, Shoulders and Robe equipped. 2 Head and 1 Robe in inventory.
![WoWScrnShot_120619_195300](https://user-images.githubusercontent.com/50233983/70348117-54652d80-1862-11ea-973c-41e0e01f3aab.jpg)
Only items from inventory removed. 1 Head, 1 Robe less.
No shoulders removed, cause none in inventory.

https://classic.wowhead.com/item-set=492/twilight-trappings
https://classic.wowhead.com/item=20422/twilight-cultist-medallion-of-station
https://classic.wowhead.com/item=20451/twilight-cultist-ring-of-lordship

**Server Revision**: 3199

**Comment by Evolvee** [comment]
https://github.com/Atlantiss/NetherwingBugtracker/issues/1408

**Comment by Manaci** [comment]
#1408 is ancient and shows how the stone is a quest vendor which got fixed ages ago, this current post is still a problem and is the most detailed and up-to-date version of the problem.

**Comment by Kruzen** [comment]
Hi! Any update on the issue?
I can add two things to it:
1) Wind stones **DO** spawn, but only once after server restart
2) This kinda blocks _Dungeon Set 2_ quest chain, where you have to get an item from the _Duke of Cynders_ which is summoned from a wind stone

**Comment by Godmatik** [comment]
They were all fixed last year
