### ISSUE TITLE
[Loot] PvP Looting/Removing Badge of enemy player in battle ground does not work

### ISSUE THREAD

**Issue by Tereneckla** [Atlantiss/NetherwingBugtracker#6468]
[//]: # (Enclose links to things related to the bug using http://wowhead.com or any other TBC database.)
[//]: # (You can use screenshot ingame to visual the issue.)
[//]: # (Write your tickets according to the format:)
[//]: # ([Quest][Azuremyst Isle] Red Snapper - Very Tasty!)
[//]: # ([NPC] Magistrix Erona)
[//]: # ([Spell][Mage] Fireball)
[//]: # ([Npc][Drop] Ghostclaw Lynx)
[//]: # ([Web] Armory doesnt work)
[//]: # (To find server revision type `.server info` command in the game chat.)

**Description**: 
![WoWScrnShot_120619_222958](https://user-images.githubusercontent.com/50233983/70357902-59cd7280-1878-11ea-89c2-bc2fd69efd9c.jpg)
Says invalid target when you try to remove the badge of the dead enemy.
Update: Only happens if the enemy has released.

**Current behaviour**:
Invalid target
**Expected behaviour**: 
Loot the corpse, enemy player can't resurrect at corpse anymore, you get some silver (and some other stuff in alterac valley)

**Server Revision**: 3199

**Comment by Wolffenstein** [comment]
It was always like that.
