### ISSUE TITLE
[Quest] The Bait for Lar'korwi 

### ISSUE THREAD

**Issue by The14me** [Atlantiss/NetherwingBugtracker#6469]
**Current behaviour**: Object Preserved Threshadon Carcass missing.

**Expected behaviour**: Preserved Threshadon Carcass suppose to be on the rock
Object ID: 169216
https://classic.wowhead.com/quest=4292/the-bait-for-larkorwi

**Server Revision**: 
3199
In 3197 the  object is there.

**Comment by Wolffenstein** [comment]
Fixed in rev 3202.
