### ISSUE TITLE
[Spell] [Hunter] Pet boar not actually charging when using charge

### ISSUE THREAD

**Issue by Cigeso** [Atlantiss/NetherwingBugtracker#647]
**Description**: 
Pet boar charge is not working correctly when out of range of the target.
**Current behaviour**:
When I want my pet boar to charge a target that's out of range, he just runs up to him normally. He does turn red and does immobilize the target, but he does not actually charge the mob. When the mob is in range of charge and I press the charge button, it does work.
**Expected behaviour**: 
The boar should run into charge range and then actually charge the target.
**Server Revision**: 
2060

**Comment by Tereneckla** [comment]
Fixed

**Comment by raethkcj** [comment]
This is not fixed as of rev 3556 @Tereneckla @Wolffenstein. 

Exactly as described in the OP, Charge works fine if the mob is already in range, but if you command your pet to charge from out of range, it partially fails. 

The boar gains the Charge buff and the target gains the Boar Charge debuff, but the pet doesn't actually charge, it just runs up at normal speed.
