### ISSUE TITLE
[Paladin] Blessing of protection

### ISSUE THREAD

**Issue by 4egito** [Atlantiss/NetherwingBugtracker#6470]
[//]: # (Enclose links to things related to the bug using http://wowhead.com or any other TBC database.)
[//]: # (You can use screenshot ingame to visual the issue.)
[//]: # (Write your tickets according to the format:)
[//]: # ([Quest][Azuremyst Isle] Red Snapper - Very Tasty!)
[//]: # ([NPC] Magistrix Erona)
[//]: # ([Spell][Mage] Fireball)
[//]: # ([Npc][Drop] Ghostclaw Lynx)
[//]: # ([Web] Armory doesnt work)
[//]: # (To find server revision type `.server info` command in the game chat.)

**Description**: 
Paladins can cast "Blessing of protection" on friendly targets even when they are in CC (sapped, blinded etc)
**Current behaviour**:
Paladins can cast "Blessing of protection" on friendly targets even when they are in CC (sapped, blinded etc)
**Expected behaviour**: 
Blessing of Protection: This spell can no longer be cast on others when stunned. It can only be cast on self (to break the stun) under those circumstances.

There is patch notes for 2.2: https://www.wowinterface.com/forums/showthread.php?t=12398
**Server Revision**:

**Comment by Evolvee** [comment]
https://github.com/ccshiro/cc-buglist/issues/1114

**Comment by AWIDIUS** [comment]
![image](https://user-images.githubusercontent.com/45521546/79642353-36f38900-819d-11ea-8f9a-366702978684.png)

After spell overhaul it happens again. Paladins are able to cast BoP on their friendly party members while they are in CC

**Comment by Evolvee** [comment]
the spell overhaul was reverted afaik

**Comment by AWIDIUS** [comment]
Then its more than obvious what happened right there.
