### ISSUE TITLE
[Quest][Durotar] Zalazane (minor, visual)

### ISSUE THREAD

**Issue by tomatosz** [Atlantiss/NetherwingBugtracker#6471]
[//]: # (Enclose links to things related to the bug using http://wowhead.com or any other TBC database.)
[//]: # (You can use screenshot ingame to visual the issue.)
[//]: # (Write your tickets according to the format:)
[//]: # ([Quest][Azuremyst Isle] Red Snapper - Very Tasty!)
[//]: # ([NPC] Magistrix Erona)
[//]: # ([Spell][Mage] Fireball)
[//]: # ([Npc][Drop] Ghostclaw Lynx)
[//]: # ([Web] Armory doesnt work)
[//]: # (To find server revision type `.server info` command in the game chat.)

**Description**: The objective counter for the [Hexed Troll](https://classic.wowhead.com/npc=3207/hexed-troll)s does not behave properly.

**Current behaviour**: When killing the first Hexed Troll, the counter jumps to 2. In the end it goes to 9/8 (the counter popping up in the middle of the screen when you kill one is correct). 
![image](https://user-images.githubusercontent.com/18441882/70379046-585b8300-1928-11ea-9bdf-0c98dd4b7194.png)
![image](https://user-images.githubusercontent.com/18441882/70379054-70cb9d80-1928-11ea-9ec5-d81da5a211dd.png)
I have not tried to see whether I can hand in the quest before 9/8.

**Expected behaviour**: It should count the first kill as 1 and count up to 8.

**Server Revision**: 3199

**Comment by Wolffenstein** [comment]
Fixed in rev 3202.
