### ISSUE TITLE
[Quest] Quenching the Blade

### ISSUE THREAD

**Issue by The14me** [Atlantiss/NetherwingBugtracker#6472]
**Current behaviour**: The sword is missing

**Expected behaviour**: The sword suppose to be there
https://www.wowhead.com/quest=10679/quenching-the-blade
Sword object ID: 185032

**Server Revision**: 
3199
In 3197 sword is there.

**Comment by Evolvee** [comment]
https://github.com/Atlantiss/NetherwingBugtracker/issues/6457
