### ISSUE TITLE
[Item] Shattered Necklace

### ISSUE THREAD

**Issue by Superschabe** [Atlantiss/NetherwingBugtracker#6473]
[//]: # ([Web] Armory doesnt work)
[//]: # (To find server revision type `.server info` command in the game chat.)

**Description**: After accepting the quest [The Shattered Necklace](https://classic.wowhead.com/quest=2283/necklace-recovery), I grinded in front of Uldaman for the quest item for roughly 45 minutes and played through the whole dungeon with a group, yet the necklace didn't drop.

**Current behaviour**: The Shattered Necklace doesn't drop.

**Expected behaviour**: The Shattered Necklace typically drops rather quickly, inside Uldaman in particular.

**Server Revision**: 3199

**Comment by Evolvee** [comment]
![image](https://user-images.githubusercontent.com/1942409/70862759-b992e000-1f40-11ea-9ffb-95962f359aa2.png)

**Comment by Evolvee** [comment]
What mobs did you kill? Works fine for me... it will not drop if you already rewarded the quest for it (even the alliance one if you faction transfered).

**Comment by Superschabe** [comment]
I do have the quest Necklace Recovery, so that prevents that item from dropping? I killed Shadowforge Diggers, Shadowforge Surveyors and Shadowforge Ruffians

**Comment by Evolvee** [comment]
PM me on discord when you are online, I will check ingame.

**Comment by Evolvee** [comment]
@Wolffenstein this is some voodoo shit, might be related to core loot rework last month.
Basically the item is 1) a quest item for quest1 2) starter of a quest2 (unrelated to quest1).
It should drop for both horde and alliance.

Now the current server-side implementation is a flat drop (no negatives etc.) with 2 conditions: 
1) player not rewarded quest 2283
AND
2) player not rewarded quest 2198

(condition 8)

Now there should be absolutely no reason for this to not drop to a new character.. I even tested it with my own chars that never made any quest and upped the chance to 100%.. still no drop.

**Comment by danbopes** [comment]
@Evolvee The reason this happened was due to the fact that quest_template had a quest in the  "StartsQuest" field, and players were unable to start the actual quest associated with the item. This triggered ineligibility for the item, and so it didn't drop.

I've enabled the use of ITEM_FLAG_MULTI_LOOT_QUEST which you can add to specific items that need to be considered both quest items, and non quest items. Closed in [3260].
