### ISSUE TITLE
[Object][Durotar] Gnomish Toolbox (minor, animation)

### ISSUE THREAD

**Issue by tomatosz** [Atlantiss/NetherwingBugtracker#6474]
[//]: # (Enclose links to things related to the bug using http://wowhead.com or any other TBC database.)
[//]: # (You can use screenshot ingame to visual the issue.)
[//]: # (Write your tickets according to the format:)
[//]: # ([Quest][Azuremyst Isle] Red Snapper - Very Tasty!)
[//]: # ([NPC] Magistrix Erona)
[//]: # ([Spell][Mage] Fireball)
[//]: # ([Npc][Drop] Ghostclaw Lynx)
[//]: # ([Web] Armory doesnt work)
[//]: # (To find server revision type `.server info` command in the game chat.)

**Description**: The player character does not visually interact with the [Gnomish Toolbox](https://classic.wowhead.com/object=3236/gnomish-toolbox) (used during the quest [From The Wreckage...](https://classic.wowhead.com/quest=825/from-the-wreckage))

**Current behaviour**: While opening the box, the character remains standing. Even when swimming, the standing animation shows instead. It does show the animation once the box is open.

**Expected behaviour**: The character should look like it's interacting with the object while it's opening. 

**Server Revision**: 3199

**Comment by Wolffenstein** [comment]
Not a bug in vanilla/tbc.
