### ISSUE TITLE
[NPC] Voidwalker Minion

### ISSUE THREAD

**Issue by tomatosz** [Atlantiss/NetherwingBugtracker#6475]
[//]: # (Enclose links to things related to the bug using http://wowhead.com or any other TBC database.)
[//]: # (You can use screenshot ingame to visual the issue.)
[//]: # (Write your tickets according to the format:)
[//]: # ([Quest][Azuremyst Isle] Red Snapper - Very Tasty!)
[//]: # ([NPC] Magistrix Erona)
[//]: # ([Spell][Mage] Fireball)
[//]: # ([Npc][Drop] Ghostclaw Lynx)
[//]: # ([Web] Armory doesnt work)
[//]: # (To find server revision type `.server info` command in the game chat.)

**Description**: The [Voidwalker Minion](https://classic.wowhead.com/npc=8996/voidwalker-minion) does not drop aggro (reported earlier in #286 / #528, but those were closed).

**Current behaviour**: The Voidwalker minion will seemingly drop aggro at the end of its aggro range, but then will immediately aggro again instead of returning to its spawn point. It does not evade.

**Expected behaviour**: It should not aggro while returning to its spawn point. 

**Server Revision**: 3199

**Comment by Evolvee** [comment]
which one exactly?

**Comment by Wolffenstein** [comment]
Need video

**Comment by tomatosz** [comment]
Can't reproduce it to capture it on video unfortunately, possibly because I've outlevelled them and therefore the re-aggro doesn't happen.

**Comment by Godmatik** [comment]
Can not reproduce. 

After leashed, the voidwalker despawns if you kill the master.
