### ISSUE TITLE
Rotten Arakkoa Egg; Of Thistleheads and Eggs (Cipher of Damnation quest line)

### ISSUE THREAD

**Issue by dman59847** [Atlantiss/NetherwingBugtracker#6476]
[//]: # (Enclose links to things related to the bug using http://wowhead.com or any other TBC database.)
[//]: # (You can use screenshot ingame to visual the issue.)
[//]: # (Write your tickets according to the format:)
[//]: # ([Quest][Azuremyst Isle] Red Snapper - Very Tasty!)
[//]: # ([NPC] Magistrix Erona)
[//]: # ([Spell][Mage] Fireball)
[//]: # ([Npc][Drop] Ghostclaw Lynx)
[//]: # ([Web] Armory doesnt work)
[//]: # (To find server revision type `.server info` command in the game chat.)

**Description**: 
Rotten Arakkoa Egg does not drop (Shadowmoon Valley)
**Current behaviour**:
Right clicking egg does not drop the quest item "rotten arakkoa egg"

**Expected behaviour**: 
Opening the Rotten Arakkoa egg, Containing "Rotten Arakkoa Egg" https://www.wowhead.com/item=30500/rotten-arakkoa-egg
**Server Revision**:

**Comment by eri1997** [comment]
It's not any egg that gives the quest item. Back when I did it i just clicked a LOT of them but reading wowhead now it says:
 "You never actually have to guess as to which egg is correct. Just mouse over it. If the tooltip just says "Rotten Arakkoa Egg" and nothing else, it will never drop the egg, and will just give you a debuff. If the tooltip says "Rotten Arakkoa Egg" and below that has a marker of quest progress (Rotten Arakkoa Egg: 0/1), you've got the right one.".
Can't confirm the wowhead comment cuz I've already done the quest before but quest was working before so unless it broke recently it should still be working.

**Comment by Wolffenstein** [comment]
There are two types of eggs - one of them gives you the quest item and the other one doesn't. The difficulty of this quest is based on opening eggs until you get the right one.
