### ISSUE TITLE
[Profession][Blacksmithing] Armorsmith -> Weaponsmith 

### ISSUE THREAD

**Issue by veekk** [Atlantiss/NetherwingBugtracker#6477]
**Description**: after specialization change from armorsmith to weaponsmith [Armor specialization] not removing from character and player getting possibility to use like armorsmith chest + deep thunder etc.

**Current behaviour**: both spec

**Expected behaviour**: after changing first one must be removed

**Server Revision**: 3199

**Comment by Evolvee** [comment]
its already reported somewhere

**Comment by Evolvee** [comment]
https://github.com/Atlantiss/NetherwingBugtracker/issues/2896 add it here if it enhances the information provided there
