### ISSUE TITLE
Channeled spells interruption

### ISSUE THREAD

**Issue by Eleneria** [Atlantiss/NetherwingBugtracker#6478]
Hello, there is a problem with channeled spells (warlock's Drain Life and priest's Mind flay). Sometimes the channelled spell starts to get interrupted, like if it was resisted by a mob, but it wasn't and its never let you to "connect" to a mob again, till the mob dies from a poison. Was happening alot in Azeroth (around 30 times) and in Outland just couple of times by now. (In Outland it was well seen in a cave with Ogres, notised couple of times)

**Comment by Evolvee** [comment]
can you record it?

**Comment by Eleneria** [comment]
> can you record it?

No, it happens randomly, I can't tell when it will happen to me next time, I'm sorry.

**Comment by Healweed** [comment]
Just to make sure, did you check on your combat log to see if your Drain Life/Mind Flay was being interrupted due to an Earth Shock from Ogre Magi?

**Comment by Eleneria** [comment]
> Just to make sure, did you check on your combat log to see if your Drain Life/Mind Flay was being interrupted due to an Earth Shock from Ogre Magi?

No no, its not that, I'm sure of it. It happens as long as I play warlock on this server and same for my friend -priest.

**Comment by Speank** [comment]
can confirm channeling spells being randomly canceled, happens very often when im draining life on a mob that about to die, and i spam drain soul to get a shard, just an example

**Comment by lyubomeer** [comment]
sometimes happens when channeling blizzard, it just interrupts randomly.
