### ISSUE TITLE
[Quest][The Barrens] The Disruption Ends (visual)

### ISSUE THREAD

**Issue by tomatosz** [Atlantiss/NetherwingBugtracker#6479]
[//]: # (Enclose links to things related to the bug using http://wowhead.com or any other TBC database.)
[//]: # (You can use screenshot ingame to visual the issue.)
[//]: # (Write your tickets according to the format:)
[//]: # ([Quest][Azuremyst Isle] Red Snapper - Very Tasty!)
[//]: # ([NPC] Magistrix Erona)
[//]: # ([Spell][Mage] Fireball)
[//]: # ([Npc][Drop] Ghostclaw Lynx)
[//]: # ([Web] Armory doesnt work)
[//]: # (To find server revision type `.server info` command in the game chat.)

**Description**: The [Razormane Geomancer](https://classic.wowhead.com/npc=3269/razormane-geomancer) for [The Disruption Ends](https://classic.wowhead.com/quest=872/the-disruption-ends) stays stuck at 7/8.

**Current behaviour**: Currently, the counter for the geomancers does not complete. I have not checked whether it skips the first one (and then counts to 7), or doesn't trigger on the 8th. It is still possible to hand in the quest, however.
![image](https://user-images.githubusercontent.com/18441882/70526734-8cae8980-1b4a-11ea-9462-54a9e654df9d.png)

**Expected behaviour**: It should count up to 8/8.

**Server Revision**: 3199

**Comment by Wolffenstein** [comment]
Fixed in rev 3202.
