### ISSUE TITLE
[NPC] killing children in elwynn forest

### ISSUE THREAD

**Issue by DarthNekr0s** [Atlantiss/NetherwingBugtracker#648]
**Description**:  killing these kids at eastvale logging camp results in their dead bodies just standing up until they disappear. people in discord have said this might be as children arent supposed to be killable therefore dont have one. also this kid Jay (entry 802, guidlow 18699) is overlevelled compared with the rest of them and hits for about 200 dmg a pop

**Current behaviour**: no death animations / are attackable, not sure which is the wrong behaviour here. npc is too high level.

**Expected behaviour**: 

**Server Revision**: 2060

![wowscrnshot_092618_201833](https://user-images.githubusercontent.com/16113944/46074506-29e20400-c1cb-11e8-915b-daaefd10dd2c.jpg)

**Comment by paoea** [comment]
They were always unkillable.

"_Children are unkillable NPCs.[citation needed] They cannot be attacked and are not caught in AoE attacks. Presumably, the designers feel that the possibility of killing children would not be appropriate game content. Games that allow violence against children would get higher content ratings[1] in some countries._"

sauce: http://wowwiki.wikia.com/wiki/Child

offtopic: What mini map addon do you use? I

**Comment by DarthNekr0s** [comment]
> They were always unkillable.
> 
> "_Children are unkillable NPCs.[citation needed] They cannot be attacked and are not caught in AoE attacks. Presumably, the designers feel that the possibility of killing children would not be appropriate game content. Games that allow violence against children would get higher content ratings[1] in some countries._"
> 
> sauce: http://wowwiki.wikia.com/wiki/Child
> 
> offtopic: What mini map addon do you use? I

least i can enjoy it while it lasts >:)  also the minimap is sexymap

**Comment by blinkmaster** [comment]
leave it as a feature <3

**Comment by xmesaj2** [comment]
fixed in rev 2081
