### ISSUE TITLE
[Item] Azure Whelpling

### ISSUE THREAD

**Issue by Tereneckla** [Atlantiss/NetherwingBugtracker#6480]
[//]: # (Enclose links to things related to the bug using http://wowhead.com or any other TBC database.)
[//]: # (You can use screenshot ingame to visual the issue.)
[//]: # (Write your tickets according to the format:)
[//]: # ([Quest][Azuremyst Isle] Red Snapper - Very Tasty!)
[//]: # ([NPC] Magistrix Erona)
[//]: # ([Spell][Mage] Fireball)
[//]: # ([Npc][Drop] Ghostclaw Lynx)
[//]: # ([Web] Armory doesnt work)
[//]: # (To find server revision type `.server info` command in the game chat.)

**Description**: Was https://wowwiki.fandom.com/wiki/Azure_Whelpling added to the loot table with 2.3?
The wowhead data obviously is wrong as it got changed in Cataclysm.
Should be 0.1% chance from the blue dragonkin in azshara

Just seems like something that could have been forgotten and I'm only ~2k kills in so I'm well it statistic to not have gotten it.

**Comment by Evolvee** [comment]
its not there afaik

**Comment by Tereneckla** [comment]
http://web.archive.org/web/20081012082519/http://thottbot.com/i34535
2 days before 3.0.2
http://web.archive.org/web/20080424115604/http://thottbot.com:80/i34535 (last one with comments)
Mob ids: 193, 6129, 6130, 6131

**Comment by Evolvee** [comment]
turns out it was there the entire time, just wasnt patch-gated

**Comment by Evolvee** [comment]
added patch 2.3. in next rev

**Comment by Evolvee** [comment]
its 0,05 btw
