### ISSUE TITLE
[Spell][Shaman] Greater Fire Elemental

### ISSUE THREAD

**Issue by Healweed** [Atlantiss/NetherwingBugtracker#6482]
**Description**: 
 Yesterday i was in ZA on 3rd boss and used the fire elemental totem, since the fight is perfect for this totem. The issue at hand was when he teleported the entire raid to the center, the fire elemental target was immediatly removed and on top of that it was doing the fire nova animation(just the animation itself, not casting the ability). This happened twice in the raid
![WoWScrnShot_121019_035253](https://user-images.githubusercontent.com/52166185/70552164-bda1b500-1b70-11ea-909d-1e2dc1a6f71b.jpg)

**Current behaviour**:
Fire Elemental target loss and casting channeling animation(just the animation itself, not actually casting Fire Nova)

**Expected behaviour**: 
Shouldn't lose it's target, even if the target uses somekind of teleport.
**Server Revision**: 
3199

**Comment by DaedalusMachina007** [comment]
I can confirm this happens in Outland in Setthek Halls with Talon King Ikiss whenever they teleport/blink around.  Since shaman pet doesn't have a pet bar or any way to manually set 'attack', it should automatically go after the Shaman's hostile target or (if no target) the nearest hostile target in range.

**Comment by Healweed** [comment]
yesterday i was fighting anetheron and he was evading 30% of the fire ele attacks(not dodge, but purely evade). this NEEDS to be fixed as it is a big cooldown and it's part of a burst dps for enh/elemental

**Comment by Godmatik** [comment]
Rev 4015 - No longer an issue
Fire elemental properly follows target whenever they blink or teleport
