### ISSUE TITLE
Bt Chain quest problems

### ISSUE THREAD

**Issue by Ariyana86** [Atlantiss/NetherwingBugtracker#6484]
Hi guys, 
I have some problems with my BT attunement chain quest.. Somehow im stucked on quest Akama's promise I think, cuz i have the item  [Medallion of Karabor], but i dont have quest Akama's promise on my quest log. (seems like its taken already and abandoned, and i cant take it again or so).
Can you help me somehow to solve this mess so i can get my attun and pick the quest from SSC from Seer Olum (The Secret Compromised ) and to continue my progress on BT attunement.
Thanks in advance , My ingame char name is Ftn
Kind Regards @gamemasters

**Comment by Baelek** [comment]
Do you recall at all going from Akama to A'dal? Once you turn in Akama's Promise, the quest line looks like it just stops with the Medallion of Karabor being left in your bags. It resumes once you go into SSC and kill Fathom-Lord Karathress, where Seer Olum spawns and gives you a new quest (there's no quest that guides you there).

Here's the full chain detailed: [(https://wow.gamepedia.com/Black_Temple_attunement)]

**Comment by Evolvee** [comment]
contact GMs via ticket/support on discord, this is a bugtracker, not a ticket
