### ISSUE TITLE
Guard marker Orgrimmar Zeppelin Tower

### ISSUE THREAD

**Issue by tomatosz** [Atlantiss/NetherwingBugtracker#6485]
[//]: # (Enclose links to things related to the bug using http://wowhead.com or any other TBC database.)
[//]: # (You can use screenshot ingame to visual the issue.)
[//]: # (Write your tickets according to the format:)
[//]: # ([Quest][Azuremyst Isle] Red Snapper - Very Tasty!)
[//]: # ([NPC] Magistrix Erona)
[//]: # ([Spell][Mage] Fireball)
[//]: # ([Npc][Drop] Ghostclaw Lynx)
[//]: # ([Web] Armory doesnt work)
[//]: # (To find server revision type `.server info` command in the game chat.)

**Description**: Orgrimmar guards send you to the wrong place for the zeppelin tower.

**Current behaviour**: When you ask an [Orgrimmar Grunt](https://classic.wowhead.com/npc=3296/orgrimmar-grunt) where the zeppelin master is, the marker on the map is on (/around) the place where the second tower is built during WOTLK, to the west rather than to the east.
![image](https://user-images.githubusercontent.com/18441882/70658989-75ad8b80-1c5f-11ea-95be-7e1c962de956.png)

**Expected behaviour**: The marker should be to the east, around (50.6, 12.8) in Durotar.

**Server Revision**: 3202

**Comment by Evolvee** [comment]
fixed in next rev
