### ISSUE TITLE
[Quest] [Object] Attack on the Tower

### ISSUE THREAD

**Issue by The14me** [Atlantiss/NetherwingBugtracker#6486]
**Current behaviour**:You cant interact with Trelane's Footlocker

**Expected behaviour**: You must be able to loot that chest if u have ''Attack on the Tower '' quest https://classic.wowhead.com/quest=696/attack-on-the-tower
https://classic.wowhead.com/object=2717/trelanes-footlocker
Chest ID: 2717

**Server Revision**: 
3202

**Comment by Wolffenstein** [comment]
Fixed in rev 3203.
