### ISSUE TITLE
[Quest] [Object] Book of the Ancients

### ISSUE THREAD

**Issue by The14me** [Atlantiss/NetherwingBugtracker#6487]
**Current behaviour**: [Gem of the Serpent](https://classic.wowhead.com/item=15766/gem-of-the-serpent)  (Item ID : 15766) Cant trigger summon on Serpent Statue (object ID: 177673 )

**Expected behaviour**:  
https://classic.wowhead.com/quest=6027/book-of-the-ancients
Go to the statue-->Use the Gem--> [Lord Kragaru](https://classic.wowhead.com/npc=12369/lord-kragaru) (ID: 12369 ).

**Server Revision**:

**Comment by Wolffenstein** [comment]
Fixed in rev 3206.
