### ISSUE TITLE
Xi'ri's Gift and Scryer's Bloodgem

### ISSUE THREAD

**Issue by Baelek** [Atlantiss/NetherwingBugtracker#6488]
**Description**: Xi'ri's Gift and Scyer's Bloodgem seem to be sharing a cooldown when either is used. This was supposed to be fixed in rev 3198, but popped up again in rev 3199 and continues now per #5718 

**Current behaviour**: When you use either trinket, the other one cannot be used until the aforementioned trinket is off cooldown (1m30s). 

**Expected behaviour**: When you use either trinket, you should be able to use the other trinket after 15s have elapsed from popping the aforementioned trinket.

**Server Revision**: 3202

**Comment by devo6969** [comment]
This is fixed on the PTR, You can  use either or and then use the next one in 15 seconds.
