### ISSUE TITLE
[Quest] [Object] Vyletongue Corruption 

### ISSUE THREAD

**Issue by The14me** [Atlantiss/NetherwingBugtracker#6489]
**Current behaviour**: Cant heal Vylestem Vine (object ID: 178905) when u use [Filled Cerulean Vial](https://classic.wowhead.com/item=17696/filled-cerulean-vial) (Item ID: 17696 ) on them.

**Expected behaviour**: 
https://classic.wowhead.com/quest=7041/vyletongue-corruption
https://classic.wowhead.com/item=17696/filled-cerulean-vial
https://classicdb.ch/?object=178905

**Server Revision**: 
3202

**Comment by Evolvee** [comment]
core issue, explained in pm on discord

**Comment by Evolvee** [comment]
should be fixed in next restart according to wolf
