### ISSUE TITLE
[NPC][Voidwalker Minion]

### ISSUE THREAD

**Issue by Nasudaa** [Atlantiss/NetherwingBugtracker#649]
[//]: # (Enclose links to things related to the bug using http://wowhead.com or any other TBC database.)
[//]: # (You can use screenshot ingame to visual the issue.)
[//]: # (Write your tickets according to the format:)
[//]: # ([Quest][Azuremyst Isle] Red Snapper - Very Tasty!)
[//]: # ([NPC] Magistrix Erona)
[//]: # ([Spell][Mage] Fireball)
[//]: # ([Npc][Drop] Ghostclaw Lynx)
[//]: # ([Web] Armory doesnt work)

**Description**: Problem is about Voidwalker Minions in Skull Rock (Durotar) Killing them doesnt work as intended

**Current behaviour**: Voidwalker Minions are completely shadow immune and therefore can only be killed by immolating them down as a warlock. 

**Expected behaviour**: Minions should be able to be damaged by shadowspells OR despawn after killing their master, though i am not sure if this was in TBC already

**Server Revision**: 

2060

**Comment by Bezawitt** [comment]
I wanted to add that you can verify this by looking at old Wowhead comments from Warlocks doing this quest during TBC:

https://www.wowhead.com/quest=1501/creature-of-the-void

> Now have your imp attack the VW and pull it off of you, then drop a CoA, corruption, immolate on the VW and followup with a shadowbolt. 

> Getting there can still be a pain though, what i did was have my imp tank the voidwalker minions while I took down the caster. I threw up my DOTs on them and then shadow bolt/wanded them down. 

I also wanted to add that both Humanoids and Voidwalkers in Skull Rock should be able to be feared according to these wowhead comments:

> Fear the woidwalkers and don't loot the mobs to keep respawns at a minimum. Once you reach the chest with the lvl14 humanoid and woidwalker keep fearing the ww and dot the humanoid. Run around the corners of the passage to cancels his casts, only stay in sight long enough to put up more dots.

> I wouldn't recommend fear in here, mobs will 99% of the time run right into another add, so that only messes up the fight.

**Comment by Evolvee** [comment]
![image](https://user-images.githubusercontent.com/1942409/46286435-75a3fd00-c57f-11e8-89bc-c3a0757e59b5.png)

@Shanghi idk if you made these resists, so I will just leave this to you I guess
problem might that this is a summoned voidwalker and idk if they shouldnt be immune just in this place or everywhere - so I could give u all NPCs that use this spells in the game

**Comment by Easyfraggy** [comment]
2121
