### ISSUE TITLE
[Item] Adamantite sharpening stone & weightstone

### ISSUE THREAD

**Issue by NatsumeLily** [Atlantiss/NetherwingBugtracker#6490]
[//]: # (Enclose links to things related to the bug using http://wowhead.com or any other TBC database.)
[//]: # (You can use screenshot ingame to visual the issue.)
[//]: # (Write your tickets according to the format:)
[//]: # ([Quest][Azuremyst Isle] Red Snapper - Very Tasty!)
[//]: # ([NPC] Magistrix Erona)
[//]: # ([Spell][Mage] Fireball)
[//]: # ([Npc][Drop] Ghostclaw Lynx)
[//]: # ([Web] Armory doesnt work)
[//]: # (To find server revision type `.server info` command in the game chat.)

**Description**: The adamantite sharpening stone and weightstone can be applied to melee weapons to improve stats temporary. 

**Current behaviour**: The sharpening stone and weightstone are applying to ranged stats too. But only the damage part is being applied to ranged.

**Expected behaviour**: The sharpening stone and weightstone damage and crit buff should only work for melee attacks.

**Server Revision**: 3208

**Comment by Manaci** [comment]
You're wrong, the stones should affect ranged weapons and only the weight stone's normal crit is affecting ranged since it's not "melee crit" like the sharpening stones are. That's the reason why hunters use fist weapons here and on any other TBC server.
