### ISSUE TITLE
[Item] Mad Alchemist's Potion side effects.

### ISSUE THREAD

**Issue by NatsumeLily** [Atlantiss/NetherwingBugtracker#6492]
[//]: # (Enclose links to things related to the bug using http://wowhead.com or any other TBC database.)
[//]: # (You can use screenshot ingame to visual the issue.)
[//]: # (Write your tickets according to the format:)
[//]: # ([Quest][Azuremyst Isle] Red Snapper - Very Tasty!)
[//]: # ([NPC] Magistrix Erona)
[//]: # ([Spell][Mage] Fireball)
[//]: # ([Npc][Drop] Ghostclaw Lynx)
[//]: # ([Web] Armory doesnt work)
[//]: # (To find server revision type `.server info` command in the game chat.)

**Description**: Mad alchemist's potion can be consumed for health and mana, and a side effect. The side effect is a semi-random list of buffs.

https://www.wowhead.com/item=34440/mad-alchemists-potion#comments

>I did some of my own testing today. Here are my conclusions:
> - When drinking a Mad Alchemist Potion it always tries to give you one random buff.
> - The selection of buffs is randomly chosen from the list of high level battle and guardian elixirs new in BC, as long as your class might possibly be able to use it.
> - It first chooses the elixir buff to apply, then attempts to apply it once decided.
> - If the user already has an elixir of this type (battle/guardian) active, the buff never happens, but you still get the health and mana.

**Current behaviour**: The potion will heal health and mana but not give any buffs. It can also be consumed at full health and mana

**Ignore healing amounts, tested on character with 20% bonus healing**
![Test](https://i.imgur.com/ljwUHtG.jpgg)

**Expected behaviour**:

1. You shouldn't be able to consume the potion when at full health and mana.
2. The potion should grant a buff (100% proc chance) each time you consume one. Following these rules: 
> - When drinking a Mad Alchemist Potion it always tries to give you one random buff.
> - The selection of buffs is randomly chosen from the list of high level battle and guardian elixirs new in BC, as long as your class might possibly be able to use it.
> - It first chooses the elixir buff to apply, then attempts to apply it once decided.
> - If the user already has an elixir of this type (battle/guardian) active, the buff never happens, but you still get the health and mana.
 
**Server Revision**: 3208

**Comment by ircfelix** [comment]
I think somewhere in the comments also stands that the alch pot should refresh (or have a chante to refresh) your existing elixir buffs.

**Comment by lyubomeer** [comment]
Yes, it should have a chance to refresh the elixir or flask on you (if it applies the same elixir/flask you currently have buffed)

**Comment by ircfelix** [comment]
found nothing about refreshing flasks but

"After doing some testing in a raid tonight I discovered this potion will only give you the type of elixir that you have open. If you have a battle elixir already on it will either refresh that elixir or give you a guardian elixir. Vise versa if you have a guardian elixir on. Also it does not buff you with an elixir that would help your class. It is completely random in that sense. For example: Onslaught elixir buff on a priest."

**Comment by ircfelix** [comment]
more info bout flasks but remind that this is PTR testing:
http://jagoex.blogspot.com/2007/11/ptr-mad-alchemists-potion-effects.html

**Comment by NatsumeLily** [comment]
>Also it does not buff you with an elixir that would help your class. It is completely random in that sense. For example: Onslaught elixir buff on a priest.

Incorrect. It applies elixirs based on class. 

And it can not proc flask buffs.

**Comment by ircfelix** [comment]
> 
> 
> > Also it does not buff you with an elixir that would help your class. It is completely random in that sense. For example: Onslaught elixir buff on a priest.
> 
> Incorrect. It applies elixirs based on class.
> 
> And it can not proc flask buffs.

If you are so sure, please provide evidence.

**Comment by NatsumeLily** [comment]
>If you are so sure, please provide evidence.

Ok. Double checking the comments, buffs based on class is wrong. Buff is random from all TBC elixirs.

**Comment by NatsumeLily** [comment]
>so it seems like the above comment is wrong (about refreshing durations) but it should be able to proc flask buffs as well.

This is also wrong. If it procs a elixir you already have on, then it will refresh it.

>If you get the same elixir buff you already have it renews it. But that's the only over-riding it does. Otherwise it won't' replace what you already have on.

>After doing some testing in a raid tonight I discovered this potion will only give you the type of elixir that you have open. If you have a battle elixir already on it will either refresh that elixir or give you a guardian elixir. Vise versa if you have a guardian elixir on.

**Comment by ircfelix** [comment]
check the link I posted. there you see the flask buff happen. it's ptr though

**Comment by NatsumeLily** [comment]
Bump.

**Comment by Wolffenstein** [comment]
Fixed in rev 3368.

**Comment by NatsumeLily** [comment]
The list of possible elixirs it can proc should be only from tbc elixirs. It's currently doing ones from vanilla/old world too but should only be from tbc elixirs.
