### ISSUE TITLE
[Quest][Warrior] Brutal Armor follow-ups

### ISSUE THREAD

**Issue by tomatosz** [Atlantiss/NetherwingBugtracker#6493]
[//]: # (Enclose links to things related to the bug using http://wowhead.com or any other TBC database.)
[//]: # (You can use screenshot ingame to visual the issue.)
[//]: # (Write your tickets according to the format:)
[//]: # ([Quest][Azuremyst Isle] Red Snapper - Very Tasty!)
[//]: # ([NPC] Magistrix Erona)
[//]: # ([Spell][Mage] Fireball)
[//]: # ([Npc][Drop] Ghostclaw Lynx)
[//]: # ([Web] Armory doesnt work)
[//]: # (To find server revision type `.server info` command in the game chat.)

**Description**: The quest [Brutal Armor](https://classic.wowhead.com/quest=1838/brutal-armor) has three follow-ups, that should all be given. It currently only gives one of the three depending on race. (Earlier bugreport #5993 was closed saying it should be race-dependent, but I can find no source saying so).

**Current behaviour**: Currently the followup is either only the Troll/Orc one ([Ula'elek and the Brutal Gauntlets](https://classic.wowhead.com/quest=1839/ulaelek-and-the-brutal-gauntlets)), the Tauren one ([Orm Stonehoof and the Brutal Helm](https://classic.wowhead.com/quest=1840/orm-stonehoof-and-the-brutal-helm)) or only the Forsaken one ([Velora Nitely and the Brutal Legguards](https://classic.wowhead.com/quest=1841/velora-nitely-and-the-brutal-legguards)).

**Expected behaviour**: [Comments](https://classic.wowhead.com/quest=1840/orm-stonehoof-and-the-brutal-helm#comments:id=2725437) [like](https://classic.wowhead.com/quest=1838/brutal-armor#comments:id=2569) [these](https://classic.wowhead.com/quest=1838/brutal-armor#comments:id=2952974) [and](https://classic.wowhead.com/quest=1838/brutal-armor#comments:id=2952971) [more](https://classic.wowhead.com/quest=1838/brutal-armor#comments:id=2783448), as well as this [guide](https://classic.wowhead.com/guides/warrior-class-quests-classic-wow#brutal-armor-and-fire-hardened-armor-level-20-30) imply that you should be able to get all quests regardless of race.

**Server Revision**: 3208

**Comment by Evolvee** [comment]
I believe this was corrected during closed beta when pyralis and kutsal were around, I dont have their sources and it was made based on some retail book afaik. Need more evidence on this like classic videos.

**Comment by GMThunderan** [comment]
Alright, I had a player today submitting a ticket about this and he provided a source for it.
Apparently all quests show up at once after finishing the first step.
See here: https://classic.wowhead.com/guides/warrior-class-quests-classic-wow

Hope this helps.

**Comment by tomatosz** [comment]
@GMThunderan I also linked that source, but thanks regardless :) It seems we need to find video's though.

**Comment by tomatosz** [comment]
@Evolvee Here is a Classic vid showing it: https://youtu.be/iXIGg4MSiYM . [12:31](https://youtu.be/iXIGg4MSiYM?t=751) shows the three followups.

**Comment by Evolvee** [comment]
fixed in next rev
