### ISSUE TITLE
[Item] Dragonmaw Shinbone

### ISSUE THREAD

**Issue by tomatosz** [Atlantiss/NetherwingBugtracker#6494]
[//]: # (Enclose links to things related to the bug using http://wowhead.com or any other TBC database.)
[//]: # (You can use screenshot ingame to visual the issue.)
[//]: # (Write your tickets according to the format:)
[//]: # ([Quest][Azuremyst Isle] Red Snapper - Very Tasty!)
[//]: # ([NPC] Magistrix Erona)
[//]: # ([Spell][Mage] Fireball)
[//]: # ([Npc][Drop] Ghostclaw Lynx)
[//]: # ([Web] Armory doesnt work)
[//]: # (To find server revision type `.server info` command in the game chat.)

**Description**: During the quest [Dragonmaw Shinbones](https://classic.wowhead.com/quest=1846/dragonmaw-shinbones), the [Dragonmaw Shinbone](https://classic.wowhead.com/item=7131/dragonmaw-shinbone)s should have a 100% droprate (implied by all comments). (It takes more kills because the bones have to be tested, not because the droprate is low).

**Current behaviour**: The droprate is low-ish, around 25% maybe?

**Expected behaviour**: The droprate should be 100%.

**Server Revision**: 3208

**Comment by Evolvee** [comment]
next rev
