### ISSUE TITLE
[Quest][Stonetalon Mountains] Gerenzo's Orders

### ISSUE THREAD

**Issue by tomatosz** [Atlantiss/NetherwingBugtracker#6495]
[//]: # (Enclose links to things related to the bug using http://wowhead.com or any other TBC database.)
[//]: # (You can use screenshot ingame to visual the issue.)
[//]: # (Write your tickets according to the format:)
[//]: # ([Quest][Azuremyst Isle] Red Snapper - Very Tasty!)
[//]: # ([NPC] Magistrix Erona)
[//]: # ([Spell][Mage] Fireball)
[//]: # ([Npc][Drop] Ghostclaw Lynx)
[//]: # ([Web] Armory doesnt work)
[//]: # (To find server revision type `.server info` command in the game chat.)

**Description**: The waves of mobs for [Gerenzo's Orders](https://classic.wowhead.com/quest=1090/gerenzos-orders) don't aggro [Piznik](https://classic.wowhead.com/npc=4276/piznik) and despawn rather quickly, making it possible to cheat-finish the quest by avoiding combat altogether.

**Current behaviour**: If you die/otherwise get out of combat with the waves of mobs, they stop attacking and despawn before the next wave appears. The last wave despawns before Piznik is done mining.

**Expected behaviour**: The waves should attack Piznik, both at the start and when there is no other target available. As shown in this [vid](https://youtu.be/goCKRHabPsE?t=891), you can see the initial target of the waves and the damage Piznik took.

**Server Revision**: 3208

**Comment by Evolvee** [comment]
prolly fixed in next rev
