### ISSUE TITLE
Argent Dawn Quartermaster

### ISSUE THREAD

**Issue by tripsixes** [Atlantiss/NetherwingBugtracker#6496]
**Description**:  I am a transfer character that is exalted with Argent Dawn, but neither quartermaster gives me an option to purchase anything from them. They both only offer 2 armament quests as seen in the attached image.
![image](https://user-images.githubusercontent.com/58953452/70934900-9df10d80-2004-11ea-9784-2dbe2357ee0f.png)

**Comment by Evolvee** [comment]
transfer character you mean.. imported from LH or faction changed?

**Comment by Tereneckla** [comment]
Looking at the reputation, it's from LH

**Comment by tripsixes** [comment]
LH transfer

**Comment by Evolvee** [comment]
you need to complete one of these quests: 
https://classic.wowhead.com/quest=5503/argent-dawn-commission
https://classic.wowhead.com/quest=5405/argent-dawn-commission
https://classic.wowhead.com/quest=5401/argent-dawn-commission

**Comment by tripsixes** [comment]
@Evolvee ive already completed that quest on LH and had the trinket upgraded Seal of the Dawn (https://classic.wowhead.com/item=13209/seal-of-the-dawn), but deleted it sometime in the past because it wasn't needed. The quests you are asking me to complete aren't available to me.

**Comment by tripsixes** [comment]
never mind. although I'm horde, I was able to complete the quest again at the alliance camp in WPL. It wasn't available to me at the horde camp or at LHC.
