### ISSUE TITLE
[Zul'aman] Chests and their NPC's despawn on server crash

### ISSUE THREAD

**Issue by dshgrove** [Atlantiss/NetherwingBugtracker#6497]
[//]: # (Enclose links to things related to the bug using http://wowhead.com or any other TBC database.)
[//]: # (You can use screenshot ingame to visual the issue.)
[//]: # (Write your tickets according to the format:)
[//]: # ([Quest][Azuremyst Isle] Red Snapper - Very Tasty!)
[//]: # ([NPC] Magistrix Erona)
[//]: # ([Spell][Mage] Fireball)
[//]: # ([Npc][Drop] Ghostclaw Lynx)
[//]: # ([Web] Armory doesnt work)
[//]: # (To find server revision type `.server info` command in the game chat.)

**Description**: 
In the event of a server crash the NPC's and the chests tied to already completed Zul'Aman timed event despawns.

**Current behavior**:
Server crashed when we were fighting thrash between third and fourth boss. When we came back online, we killed the fourth boss before the timer ended. The chest and the NPC after the fourth boss was there, but when we went back to the other three bosses they had all despawned.

**Expected behavior**: 
Chests to be there and their corresponding NPC still being alive when we come online after a crash.

**Server Revision**: 
3208

**Comment by Wolffenstein** [comment]
It's intended because the loot eligibility cannot be preserved after server crashes/restarts.
