### ISSUE TITLE
[Raid][Black Temple] Gathios the Shatterer

### ISSUE THREAD

**Issue by Dschagannad** [Atlantiss/NetherwingBugtracker#6498]
[//]: # (Enclose links to things related to the bug using http://wowhead.com or any other TBC database.)
[//]: # (You can use screenshot ingame to visual the issue.)
[//]: # (Write your tickets according to the format:)
[//]: # ([Quest][Azuremyst Isle] Red Snapper - Very Tasty!)
[//]: # ([NPC] Magistrix Erona)
[//]: # ([Spell][Mage] Fireball)
[//]: # ([Npc][Drop] Ghostclaw Lynx)
[//]: # ([Web] Armory doesnt work)
[//]: # (To find server revision type `.server info` command in the game chat.)

**Description**: Gathios the Shatterer (Paladin of the Illidari Council Encounter, https://tbcdb.com/?npc=22949) is immune to Life Drain Effects.
This was observed as a warlock with Drain Life (https://tbcdb.com/?spell=27220) and Siphon Life (https://tbcdb.com/?spell=30911).
He is not immune to other spells, he just behaves as if he was a mechanical creature (like https://tbcdb.com/?npc=23394 for example), which you cant drain life from. Should be a normal humanoid mob and not immune.
Can't find any other reason why he should behave like a mechanical creature nor any sources stating that he is immune, therefore I assume it's a bug.

**Current behaviour**: Gathios the Shatterer is immune ot Life Drain Effects,

**Expected behaviour**: Shouldn't be.

**Server Revision**: 3208

**Comment by Wolffenstein** [comment]
Fixed in rev 3213.
