### ISSUE TITLE
[Archimonde] Doomfire only doing the first tick of dmg

### ISSUE THREAD

**Issue by eri1997** [Atlantiss/NetherwingBugtracker#6499]
**Description**:  Title

**Current behaviour**:  It's only doing the first 2.4k dmg tick and doing no dmg after.

**Expected behaviour**:  Should tick dmg during the debuff duration

**Server Revision**: 3213

**Comment by Wolffenstein** [comment]
Fixed in rev 3214.

**Comment by Manaci** [comment]
Just did our first raid after Christmas break, this is still bugged btw.

**Comment by Wolffenstein** [comment]
3235
