### ISSUE TITLE
[NPC] Venture Co. Saboteur

### ISSUE THREAD

**Issue by Sinyr** [Atlantiss/NetherwingBugtracker#65]
[//]: # (Enclose links to things related to the bug using http://wowhead.com or any other TBC database.)
[//]: # (You can use screenshot ingame to visual the issue.)
[//]: # (Write your tickets according to the format:)
[//]: # ([Quest][Azuremyst Isle] Red Snapper - Very Tasty!)
[//]: # ([NPC] Magistrix Erona)
[//]: # ([Spell][Mage] Fireball)
[//]: # ([Npc][Drop] Ghostclaw Lynx)
[//]: # ([Web] Armory doesnt work)

**Current behaviour**:
Venture Co. Saboteur buffs himself with Thorns properly, but the buff has no effect. It deals no damage and doesn't show up in combat log. Melee attacked him as a Paladin.
**Expected behaviour**: 
Thorns should deal damage to the attacker.

**Comment by Evolvee** [comment]
fixed in next hotfix revision
