### ISSUE TITLE
Skittering Crawler pathing is a off. 

### ISSUE THREAD

**Issue by Emityx** [Atlantiss/NetherwingBugtracker#650]
**Current behaviour**:
Skittering Crawler [17216] walks on pier. Sometimes strangly walking in air.  Not supposed to walk on pier at all. 

**Server Revision**: 
2060

![wow_2018-09-26_13-13-33](https://user-images.githubusercontent.com/37587544/46076798-f1243980-c18e-11e8-9061-3ed2c7cb547c.jpg)

**Comment by aresbrutus** [comment]
Corrected in one of the next updates.
