### ISSUE TITLE
[Spell][Paladin] Seal Twisting issue

### ISSUE THREAD

**Issue by Shanrolol** [Atlantiss/NetherwingBugtracker#6501]
[//]: # (Enclose links to things related to the bug using http://wowhead.com or any other TBC database.)
[//]: # (You can use screenshot ingame to visual the issue.)
[//]: # (Write your tickets according to the format:)
[//]: # ([Quest][Azuremyst Isle] Red Snapper - Very Tasty!)
[//]: # ([NPC] Magistrix Erona)
[//]: # ([Spell][Mage] Fireball)
[//]: # ([Npc][Drop] Ghostclaw Lynx)
[//]: # ([Web] Armory doesnt work)
[//]: # (To find server revision type `.server info` command in the game chat.)

**Description**: 
Approximately on the night, from 18 to 19th this December there happened some kind of a change to a previously more or less authentic way that Paladin Seal Twisting mechanic worked.
**Current behaviour**:
It used to properly pop 2 Seal of Blood hits, after you swap to Seal of Blood during your swing animation + Seal of Command proc, with an odd minor delay, but the overall damage was still as it should be. Now, after some sort of an update or a hotfix, SoB procs the same way, but there's one hit missing now. You hit your white auto damage, SoCommand, and just one Seal of Blood, instead of two.
**Expected behaviour**: 
You should be getting 2 SoBlood procs if you properly Sealtwist at the moment of Seal of Command proc. Also, since you are going to dig into the issue, might aswell fix the way Sealtwisting interracts with Windfury totem procs, where the additional autoattack occuring during the Sealtwist is, for some reason, replacing the 2nd SoB hit, instead of adding another one, making it [Auto + SoComm +WF Auto + 1x SoBlood], instead of [Auto + Socomm + 2x SoBlood (proper sealtwist components) + WF Auto + SoBlood from WF Auto]. Please, atleast fix the base state of the mechanic, thanks.
**Server Revision**: 
3213

**Comment by Shanrolol** [comment]
![Sealtwisting](https://user-images.githubusercontent.com/16698440/71312053-7bb62000-2448-11ea-905b-8494c8c9bf49.jpg)
Also, the combat log counts the autoattack's damage landing as soon as you start attacking, not when your character's swing animation is actually over, and a big white number pops on the screen. That might be what's causing one of two Seal of Blood hits to be missing atm.

**Comment by Shanrolol** [comment]
This is taking quite a while at this point, could you maybe just dig up whatever you changed about paladin seals and their delays, or w/e else it was, and backtrack those? Its not fun investing gcd's and mana into the mechanic and not getting a proper pay-off in damage.

**Comment by Shulishin** [comment]
can confirm, seal twisting isn't working as it should

**Comment by Shulishin** [comment]
can confirm, seal twisting isn't working as it should

**Comment by Wolffenstein** [comment]
I intentionally removed the double Seal of Blood proc because I believe it was a bit too easy to achieve and combined with the double dipping damage bug it resulted in way too much dps. I will bring it back in revision 3225.

**Comment by Shanrolol** [comment]
Dear Wolfenstein, please avoid "fixing" things on your own in the future, cause it seems you didnt know how the mechanic's supposed to work, and just nerfed it X fkin 2, based on personal wishes. Idk if you got rekt by a ret paladin in pvp, I cant find another reason for you to go and fuck up the core advanced mechanic. In pve its easy to sealtwist, bcause pve is fkin easy, some classes press 1 button, and top the meters anyway. In pvp it wasnt nearly as easy, with all the attack speed slows and getting kited and cced. Rets are underdogs of TBC already, dont kill them off completely, let more skillful ppl get more out of the spec, thanks.28.12.2019, 20:50, "Wolfenstein" <notifications@github.com>:I intentionally removed the double Seal of Blood proc because I believe it was a bit too easy to achieve and combined with the double dipping damage bug it resulted in way too much dps. I will bring it back in revision 3225.

**Comment by danbopes** [comment]
@Shanrolol Please be respectful or your privileges on our bug tracker will be revoked. If you have criticism, please do it in a constructive manner.

**Comment by Wolffenstein** [comment]
@Shanrolol I was the one who implemented it in the first place, and i spent way more time on researching it then you could possibly imagine, so yes, I do know how it's supposed to work, more so than you. The bug regarding damage modifiers double dipping combined with Seal Twisting resulted in ret damage being way too high, that's why double proc was temporarily disabled. Since I fixed the bug, the Seal Twisting is now back to normal.

PS. My first ever character was a ret pally and I also had the most fun in WoW playing a paladin. If I actually had some sort of retarded balancing agenda, it would certainly not be against this class.

**Comment by Shanrolol** [comment]
Sorry about that, I had a shitty day, my arena partner's quit, bcause we failed to get the s3 weapon rating in a double DPS comp, losing many games due to the lack of damage and enemies surviving with little to no HP, I lashed out a bit too much, my bad.29.12.2019, 04:23, "danbopes" <notifications@github.com>:@Shanrolol Please be respectful or your privileges on our bug tracker will be revoked. If you have criticism, please do it in a constructive manner.
