### ISSUE TITLE
Pain supression far too easily dispelled

### ISSUE THREAD

**Issue by Speank** [Atlantiss/NetherwingBugtracker#6502]
[//]: # (Enclose links to things related to the bug using http://wowhead.com or any other TBC database.)
[//]: # (You can use screenshot ingame to visual the issue.)
[//]: # (Write your tickets according to the format:)
[//]: # ([Quest][Azuremyst Isle] Red Snapper - Very Tasty!)
[//]: # ([NPC] Magistrix Erona)
[//]: # ([Spell][Mage] Fireball)
[//]: # ([Npc][Drop] Ghostclaw Lynx)
[//]: # ([Web] Armory doesnt work)
[//]: # (To find server revision type `.server info` command in the game chat.)

**Description**: Pain supression's increased chance to resist dispel mechanics is not working

**Current behaviour**: Pain supression not giving the 65% increased chance to resist dispel mechanics during its duration
https://www.twitch.tv/speankitsover/clip/EasyAcceptableAlligatorGivePLZ?filter=clips&range=7d&sort=time
https://www.twitch.tv/speankitsover/clip/ConcernedCredulousDragonflyLitFam?filter=clips&range=all&sort=time
https://www.twitch.tv/speankitsover/clip/UgliestFlirtyTildeMrDestructoid?filter=clips&range=all&sort=time
https://www.twitch.tv/speankitsover/clip/CrazyKitschyLaptopRlyTho?filter=clips&range=7d&sort=time
https://www.twitch.tv/speankitsover/clip/FaithfulCoweringKoupreyNotLikeThis?filter=clips&range=7d&sort=time
https://www.twitch.tv/speankitsover/clip/FriendlyCrowdedGnatSpicyBoy?filter=clips&range=all&sort=time
https://www.twitch.tv/speankitsover/clip/CrazyAdventurousOrcaAliens?filter=clips&range=all&sort=time
https://www.twitch.tv/speankitsover/clip/OriginalNastyNostrilBCouch?filter=clips&range=all&sort=time
https://www.twitch.tv/speankitsover/clip/OriginalNastyNostrilBCouch?filter=clips&range=all&sort=time
https://www.twitch.tv/speankitsover/clip/IronicAltruisticOctopusRuleFive?filter=clips&range=all&sort=time

**Expected behaviour**: You should have a 73% chance during pain supression uptime to resist dispel mechanics (assuming you are using the most common spec 2/5 silent resolve, 8% chance to resist dispels on your buffs)

**Server Revision**: 3213

**Comment by DarthGamer** [comment]
It's worth adding same resistance should also be observed by spell steal.

**Comment by Wolffenstein** [comment]
Fixed in rev 3217.
