### ISSUE TITLE
[Quest] Illidan doesn't despawn at the Netherwing Ledge

### ISSUE THREAD

**Issue by Tereneckla** [Atlantiss/NetherwingBugtracker#6504]
[//]: # (Enclose links to things related to the bug using http://wowhead.com or any other TBC database.)
[//]: # (You can use screenshot ingame to visual the issue.)
[//]: # (Write your tickets according to the format:)
[//]: # ([Quest][Azuremyst Isle] Red Snapper - Very Tasty!)
[//]: # ([NPC] Magistrix Erona)
[//]: # ([Spell][Mage] Fireball)
[//]: # ([Npc][Drop] Ghostclaw Lynx)
[//]: # ([Web] Armory doesnt work)
[//]: # (To find server revision type `.server info` command in the game chat.)

**Description**: 
https://cdn.discordapp.com/attachments/614472015272738836/658083200064552980/bugged.png
https://www.wowhead.com/quest=11108/lord-illidan-stormrage
**Current behaviour**:
Doesn't despawn at the end.
**Expected behaviour**: 
Despawns at the end.
**Server Revision**: 3213

**Comment by Wolffenstein** [comment]
Fixed in rev 3218.

**Comment by Tereneckla** [comment]
He's back
