### ISSUE TITLE
Zul'jin Flame Columns damage

### ISSUE THREAD

**Issue by Drainlock** [Atlantiss/NetherwingBugtracker#6505]
Zul'jin's Flame Columns deal damage twice at same time: 1st from Column and 2nd from Zul'jin.
![Zul'jin damage](https://user-images.githubusercontent.com/59121561/71324700-eb7ce700-24ea-11ea-9bb1-07827b5b8bcd.jpg)
Makes last phase a lot harder. Should be 900 DPS (increased by debuff) and here it's like 1800 base DPS.
https://wow.gamepedia.com/Zul%27jin_(tactics)

**Comment by Drainlock** [comment]
https://www.twitch.tv/videos/525486229
Video footage from today raid.

**Comment by Wolffenstein** [comment]
Fixed in rev 3231.
