### ISSUE TITLE
Offhand auto attack swing hits starts in the same time as the main hand . 

### ISSUE THREAD

**Issue by sposobniy** [Atlantiss/NetherwingBugtracker#6506]
Problem : Title.

https://youtu.be/EaIMnBD5nJM  

Auto attack offhand start instant with main hand (should be delay ~ 1 sec) , and rogue have "double hits " in during all video 

also this hits different then client swing animation , and summary MH+OH damage better then have 2h?lul

IF you will look for number of HP after first hit  11281-467 druid HP should be 10814 ,but he have 10748 cos he have offhand hit instant (not visible at screen) 

https://imgur.com/BCVxpEK 

How it should work :  

https://youtu.be/Ba6Ty72eSH8?t=51 acrono using garrote and first offhand attack with delay 
https://youtu.be/VdMIA6QkgFk?t=432 he shiv war , and get only 1 main hand  attack
https://youtu.be/VdMIA6QkgFk?t=502  delay for offhand swing ~ 1 sec aswell 
https://youtu.be/VdMIA6QkgFk?t=96  first offhand hit ~ after 1 sec after main hand  
https://youtu.be/Ba6Ty72eSH8?t=391 

Also this report https://github.com/Atlantiss/NetherwingBugtracker/issues/6408 was closed 
but this part "Also sanc aura doesn't increase damage of SoC/SoB hits, only the 2% damage increase from improved sanc aura applies (which also double dips, as does the 6% increase from two handed weapon spec talent, that works even with one handed weapons...)
https://clips.twitch.tv/AbstemiousPiliableFerretFutureMan "  not was fixed

**Comment by Easyfraggy** [comment]
This report is invalid you are comparing using 2 same speed weapons to using a fast offhand and slow mainhand on all the videos. Ofcourse the attacks won't land at the same time when you use different speeds.

**Comment by sposobniy** [comment]
> This report is invalid you are comparing using 2 same speed weapons to using a fast offhand and slow mainhand on all the videos. Ofcourse the attacks won't land at the same time when you use different speeds.

id you even read the contents of this report? or brain dead ?

Auto attack shoudnt start from both weapons Mh and offhand doesnt matter what speed do they have . First offhand swing should start with ~1 sec delay (with your character  swing animation ) . If you lost this MH hit , and your target kite this next time when your connect this act should be reset : prior MH swing >delay >offhand swing .   

On NW , always when you connect you have 2  instant hit from MH and offhand .

**Comment by Easyfraggy** [comment]
You are literally making things up.

You can see clearly in your own video that only your MH swings first hit then 2nd hit with 2.6/2.6 happens at the same time which is correct behavior.

On your videos the rogues are using fast offhands which means the first offhand attack will be around 1 second after the first MH swing just like it would on NW if you equipped a 1.4 speed offhand.

**Comment by Easyfraggy** [comment]
On NW only your MH hits when you connect. It's even on your own video.

**Comment by sposobniy** [comment]
> On NW only your MH hits when you connect. It's even on your own video.

yes , but look at number of HP druid he was Offhand hit too (not visible ) and start offhand attack timer => next hit comming faster then should  

https://youtu.be/8GFEvYMwUtA?t=8 same with 1.5 weapon

**Comment by Easyfraggy** [comment]
11281 hp
after MH 467 + yellow 66
10748

Stop making things up.

**Comment by sposobniy** [comment]
ok i think this report was wrong , Thanks for the clarification . i am not sure in one moment , but dont need some more time for using youtube in during week .
