### ISSUE TITLE
Felhunter quest not available [Seeking Strahad] 

### ISSUE THREAD

**Issue by Swansonsby** [Atlantiss/NetherwingBugtracker#6508]
[//]: # (You can use screenshot ingame to visual the issue.)
[//]: # (Write your tickets according to the format:)
[//]: # ([Quest][Seeking Strahad)
[//]: # (NPC Gakin the Darkbinder)

**Description**: 
[Alliance] - Swans, Human Warlock - Could you please check my quest progression? I went everywhere and can't start the Felhunter quest
I don't have any Warlock quests in my log except for the epic mount (Mor'zul Bloodbringer)
**Current behaviour**:
Cannot start Seeking Strahad from Gakin the Darkbinder
![WoWScrnShot_122419_202915](https://user-images.githubusercontent.com/59228103/71446683-0a9a9500-26f4-11ea-90d0-430508717c05.jpg)

**Comment by GMThunderan** [comment]
Fel Hunter Questchain – Lvl 30
__________________________________________________________________
Legend:
N-Step
Queststarter NPC ID (NPC Name) 
Quest ID (Quest Name) 
Questender NPC ID (NPC Name) 
__________________________________________________________________

1st    Step
https://tbc-twinhead.twinstar.cz/?npc=6122  (Gakin the Darkbinder)
https://tbc-twinhead.twinstar.cz/?quest=1798 (Seeking Strahad)
https://tbc-twinhead.twinstar.cz/?npc=6251 (Strahad Farsan) <<<<------------This is the last step players are able to turn in!

2nd    Step
https://tbc-twinhead.twinstar.cz/?npc=6251 (Strahad Farsan) <<<<------------This quest can not be obtained!
https://tbc-twinhead.twinstar.cz/?quest=1758 (Tome of the Cabal "I")
https://tbc-twinhead.twinstar.cz/?npc=6294 (Krom Stoutarm)

3rd    Step
https://tbc-twinhead.twinstar.cz/?npc=6294 (Krom Stoutarm)
https://tbc-twinhead.twinstar.cz/?quest=1802 (Tome of the Cabal "II")
https://tbc-twinhead.twinstar.cz/?npc=6294 (Krom Stoutarm)

4th Step
https://tbc-twinhead.twinstar.cz/?npc=6294 (Krom Stoutarm)
https://tbc-twinhead.twinstar.cz/?quest=1804 (Tome of the Cabal "III")
https://tbc-twinhead.twinstar.cz/?npc=6251 (Strahad Farsan)

5th Step
https://tbc-twinhead.twinstar.cz/?npc=6251 (Strahad Farsan)
https://tbc-twinhead.twinstar.cz/?quest=1795 (The Binding)
https://tbc-twinhead.twinstar.cz/?npc=6251 (Strahad Farsan)

Notes:
So after you turn in the first quest (QuestID 1798) at Strahad Farsan (NPC 6251) the next quest (QuestID 1758) pops up briefly, but you are not able to accept it ("You don't meet the requirements for that quest"). After you close this dialogue, the queststarter (NPC 6251) does not offer the next quest (QuestID 1758) anymore. Thus players are unable to complete the chain.

(Tested on PTR)

**Comment by Evolvee** [comment]
https://github.com/Atlantiss/NetherwingBugtracker/issues/6514#issuecomment-569244848
