### ISSUE TITLE
[Battlegrounds] Alterac Valley uncompletable quests

### ISSUE THREAD

**Issue by Manaci** [Atlantiss/NetherwingBugtracker#6509]
**Description**: 
These quests all involve capturing a specific point in AV, so for Horde there's [Capture a Mine](https://db.excalibur.ws/?quest=7124) (ID 7124), [Assault a Graveyard](https://db.excalibur.ws/?quest=7082) (ID 7082) and [Destroy a Bunker/Tower](https://db.excalibur.ws/?quest=7101) (ID 7101).
Alliance counterparts are [Capture a Mine](https://db.excalibur.ws/?quest=7122) (ID 7122), [Assault a Graveyard](https://db.excalibur.ws/?quest=7081) (ID 7081) and [Destroy a Bunker/Tower](https://db.excalibur.ws/?quest=7102) (ID 7102).
These quests are currently not giving said credit when the objectives are either captured or destroyed, which should be the job of the [Mine Credit Marker](https://db.excalibur.ws/?npc=13796), [Graveyard Credit Marker](https://db.excalibur.ws/?npc=13756) and [Tower Credit Marker](https://db.excalibur.ws/?npc=13778) just like how it works in Arathi Basin.

Moved from the old post [here](https://github.com/Atlantiss/NetherwingBugtracker/issues/5473).

**Server Revision**: 
3213

**Comment by Godmatik** [comment]
Closing - will consolidate all outstanding AV issues into one thread now.
