### ISSUE TITLE
[Quest] The Battle of Darrowshire cannot be completed 

### ISSUE THREAD

**Issue by Manaci** [Atlantiss/NetherwingBugtracker#6510]
**Description**: 
The quest called [The Battle of Darrowshire](http://db.excalibur.ws/?quest=5721) currently cannot be completed. When the [Relic Bundle](http://db.excalibur.ws/?item=15209) is placed in the middle of the town, the following [event](https://www.youtube.com/watch?v=mgsMh8klozg) does not begin as it should.

Moved from the old post [here](https://github.com/Atlantiss/NetherwingBugtracker/issues/5473).

**Server Revision**: 
3213

**Comment by Evolvee** [comment]
https://github.com/Atlantiss/NetherwingBugtracker/issues/1279
