### ISSUE TITLE
[Priest][Spell] Shadowfiend

### ISSUE THREAD

**Issue by sposobniy** [Atlantiss/NetherwingBugtracker#6512]
http://tbc.cavernoftime.com/spell=34433 

Problem : 
Shadowfiend -deal much more damage then should , which results in a much more  regeneration mana per hit for for priests . 

https://clips.twitch.tv/TriumphantAnimatedPandaSpicyBoy

https://www.twitch.tv/videos/504448855?t=00h00m45s  

All this priests have ~600 spd , With 6% SPD bonus per hit  damage should be ~140  , 
but their pets hit 200-240 

 How it should work : 
 https://wowwiki.fandom.com/wiki/Shadowfiend?oldid=1550132  

"Without shadow damage bonus, the Shadowfiends' hits deal an average of 110 damage to an equal level mob without shadow resistance, it's average damage per attack however is 100 because of being mitigated as melee." 

""The Shadowfiend receives 60-66% of your shadow damage bonus over the 15 second duration depending on 10 to 11 attacks, or 6% per hit for 10 hits. Giving in optimal conditions an additional 1.5 mana for 1 shadow spell damage per use.""  

Some video sources : 

https://youtu.be/TYawfgVBSEc?t=289 ~ 130  damage per hit same season and spec 

https://youtu.be/QyTyNaiEJKs?t=298 ~ 140 per hit 

https://youtu.be/Fv_CJDCmGO8?t=323 retail shadow priests , with much more BSD and additional tailents for + shadow dmg . Still less damage than DISCIPLENE priests on netherwing lul

**Comment by Evolvee** [comment]
http://tbc.internal.atlantiss.eu/showthread.php?tid=315&highlight=shadowfiend

Shadowfiend scales based on:
Attack power, Caster shadow dmg, strength, buffs(spell AND melee), casters buffs, target debuffs

**Comment by sposobniy** [comment]
I dont think all priests have different numbers of attack power (based), yes they should scaling from buff etc  .
At the moment we are talking about Priest and his own buffs  : 


~100 +/- base damage and 6% scalling from spd  per hit .  2  Different sources wowwiki and this wowhead  comments : 
https://www.wowhead.com/spell=34433/shadowfiend#comments

By alclarity    "Pre-3.1 shadowfiend:  Approximately hits for 111 dmg @ 1.5 speed = 74dps = 1110 shadow damage " 

and this 
"As soon as I'm down about 2k mana from my max, I use my shadowfiend. Basically wait until I'm low enough that the shadowfiends mana gain will put me near full but won't be wasted. True the shadowfiend will restore more than 2k mana, but it comes over time so I will still be casting heals and losing mana during this time. " 
 
https://youtu.be/Fv_CJDCmGO8?t=456  Shadow priest with : Berserker stance warrior ~10% more dmg , Shadowform, Darkness, Shadow Weaving, Misery : and hes pet hit same like  on NW with ~s2+ geared priest )

**Comment by sposobniy** [comment]
https://youtu.be/h504-JLlG6k  Check this pls , outgeared HOLY priests shadowfiend hits more then geread SP in s4 retail movies . Should hit ~100 . 
I hope this will be fixed before tournament will start

**Comment by Evolvee** [comment]
true, it gives too much mana currently

**Comment by Evolvee** [comment]
hmmm, today it looks fine :D will need more testing, its probably 1 element that makes the mana gain be off the charts, gotta research what its caused be

**Comment by bekonja** [comment]
Still bugged, deals x2 damage of what it should be.

**Comment by Wolffenstein** [comment]
Fixed in rev 3615.
