### ISSUE TITLE
[core] arena draw fucked (again)

### ISSUE THREAD

**Issue by The14me** [Atlantiss/NetherwingBugtracker#6513]
**Current behaviour**:If both team's die at the same time they stuck at the arena and no draw

**Expected behaviour**:  Evolve

**Server Revision**: 
3210

**Comment by Evolvee** [comment]
when both teams die within the arena end delay, they dont get draw --> more on discord (smaily).. he said something about one team being forced to leave(and these would lose the rating)

**Comment by Wolffenstein** [comment]
Fixed in rev 3224.
