### ISSUE TITLE
Zandalar tribe quests

### ISSUE THREAD

**Issue by Drainlock** [Atlantiss/NetherwingBugtracker#6514]
You can't start any of those quests: https://wowwiki.fandom.com/wiki/Zandalar_armor_sets
For example https://wowwiki.fandom.com/wiki/Quest:Paragons_of_Power:_The_Demoniac%27s_Wraps
https://classic.wowhead.com/quest=8059/paragons-of-power-the-demoniacs-wraps
I have item and friendly rep, but NPC doesn't give me quest and I haven't done it before, coz i would have more rep in that case.
![WoWScrnShot_122619_224627](https://user-images.githubusercontent.com/59121561/71490506-cb735d80-2833-11ea-8d71-d19d7665e6d8.jpg)
AtlantissCoreTBC - Server Revision: 3213 [Branch: master, Hash: 6bf7a054e23d]

**Comment by Evolvee** [comment]
same reason as
https://github.com/Atlantiss/NetherwingBugtracker/issues/6508
https://github.com/Atlantiss/NetherwingBugtracker/issues/6212
negative class condition core bug
