### ISSUE TITLE
[Quest] objects not lootable in order to get questitem.

### ISSUE THREAD

**Issue by GMThunderan** [Atlantiss/NetherwingBugtracker#6515]
**Description**: 
There are a few objects that can not be looted by players in order to obtain a questitem. 
To specify, players are able to open the object, but there is no loot inside. Note: as GM the Item is lootable, if that helps.

I'll update them constantly.

**Server Revision**: 
3213

**Confirmed (by me on PTR) quests/objects**:
Kurzen's Mystery (only the 2nd legend doesn't work)
https://tbc-twinhead.twinstar.cz/?quest=207 / https://tbc-twinhead.twinstar.cz/?object=179426

The Vile Reef
https://tbc-twinhead.twinstar.cz/?quest=629 / https://tbc-twinhead.twinstar.cz/?object=58

**Comment by Wolffenstein** [comment]
Fixed in rev 3222.
