### ISSUE TITLE
[2.4 PTR] Isle of Quel'Danas bugs

### ISSUE THREAD

**Issue by Manaci** [Atlantiss/NetherwingBugtracker#6516]
- [x]  **[Maintaining the Sunwell Portal](https://db.excalibur.ws/?quest=11514)** 
Bugged but completable, the [Smuggled Mana Cell containers](https://db.excalibur.ws/?object=187039) should not be visible until one gets a [Bash'ir Phasing Device](https://db.excalibur.ws/?item=34248) and uses it. The [Phase Wyrms](https://db.excalibur.ws/?npc=24917) should not be visible either until said item is used. 

**E by evolve: Requires core TBC Phasing system implemented (similar to wotlk)** / done
**Server Revision**: 
PTR 3225

**Comment by Tereneckla** [comment]
[General Tiras'alan](https://wowwiki.fandom.com/wiki/General_Tiras%27alan) is missing (ID 25167)
[Exarch Larethor](https://wowwiki.fandom.com/wiki/Exarch_Larethor) is missing (ID 24813)

**Comment by Tereneckla** [comment]
![WoWScrnShot_122819_175749](https://user-images.githubusercontent.com/50233983/71548765-43b45d00-29b3-11ea-9acf-965245810e8e.jpg)
Orbs of Translocation teleport you inside the target orb, so that you have to jump out.

**Comment by Tereneckla** [comment]
[**Erratic Behaviour**](https://wowwiki.fandom.com/wiki/Quest:Erratic_Behavior)/[**Further Conversions**](https://wowwiki.fandom.com/wiki/Quest:Further_Conversions)
Chance to not get quest credit upon using the [Attuned Crystal Cores](https://wowwiki.fandom.com/wiki/Attuned_Crystal_Cores) on an [Erratic Sentry](https://wowwiki.fandom.com/wiki/Erratic_Sentry).

**Comment by Tereneckla** [comment]
[**Know Your Ley Lines**](https://wowwiki.fandom.com/wiki/Quest:Know_Your_Ley_Lines)
You can't take readings at all.
![WoWScrnShot_122819_185054](https://user-images.githubusercontent.com/50233983/71548826-3c418380-29b4-11ea-8fa9-1fbdd7591908.jpg)
![WoWScrnShot_122819_184258](https://user-images.githubusercontent.com/50233983/71548827-3c418380-29b4-11ea-9c9e-5ada6aad34dc.jpg)
![WoWScrnShot_122819_184831](https://user-images.githubusercontent.com/50233983/71548828-3cda1a00-29b4-11ea-896f-a7bf1eab5a6d.jpg)

**Comment by Tereneckla** [comment]
[**K'iru**](https://wowwiki.fandom.com/wiki/K%27iru) is present but you don't get the Buff [K'iru's Song of Victory](https://wowwiki.fandom.com/wiki/K%27iru%27s_Song_of_Victory) on the Isle or in Magister's Terrace.
![WoWScrnShot_122819_202924](https://user-images.githubusercontent.com/50233983/71548876-d1dd1300-29b4-11ea-855c-b280b7c23602.jpg)

**Comment by Tereneckla** [comment]
Upon being freed with the [Orb of Murloc Control](https://wowwiki.fandom.com/wiki/Orb_of_Murloc_Control) [Greengill Slaves](https://wowwiki.fandom.com/wiki/Greengill_Slave) just run to the nearest Naga and stand around instead of attacking them.
![WoWScrnShot_122819_185431](https://user-images.githubusercontent.com/50233983/71548899-31d3b980-29b5-11ea-86ac-c0e9ab1cd353.jpg)

**Comment by Tereneckla** [comment]
[**https://wowwiki.fandom.com/wiki/Quest:Rediscovering_Your_Roots**](https://wowwiki.fandom.com/wiki/Quest:Rediscovering_Your_Roots)
Bugged and not completable. You can tame the ravager with the gland and it is usable as a pet. However it disables your autoattacks completely.
Digging out the roots does not work at all.
Either the ravager runs to a mound and does nothing or it digs at the mound, which despawns the mound but does not spawn a root to pickup.
The dig command also disables the follow command completely.

**Comment by Manaci** [comment]
- [ ] [Anwehu](https://db.excalibur.ws/?npc=27667) is missing.

**Comment by Tereneckla** [comment]
- [ ] [Ata'mal Armaments](https://wowwiki.fandom.com/wiki/Quest:Ata%27mal_Armaments)
Bugged and not completable. Hauthaa's Anvil not defined.
![WoWScrnShot_122819_214034](https://user-images.githubusercontent.com/50233983/71549255-eb815900-29ba-11ea-930c-ed86fbb71492.jpg)

**Comment by Tereneckla** [comment]
- [ ] Nether Vortex missing @G'eras

- [ ] Trainers don't teach [Brilliant Glass](https://wowwiki.fandom.com/wiki/Brilliant_Glass)

- [ ] Outland World Boss drops become BoE in 2.4

**Comment by Tereneckla** [comment]
- [ ] Bleed should work on Mechanical creatures
![image](https://user-images.githubusercontent.com/50233983/71549795-d230da80-29c3-11ea-8a56-1e519763975e.png)
![WoWScrnShot_122819_224322](https://user-images.githubusercontent.com/50233983/71549800-d52bcb00-29c3-11ea-8e9d-858de62bcd72.jpg)

**Comment by Manaci** [comment]
- [ ] [Haughty Modiste <Fashion Designer>](https://db.excalibur.ws/?npc=15165) is not a vendor, which she should be in 2.4 and sell 3 unique Tailoring recipes.
![dawawdawdawdaw](https://user-images.githubusercontent.com/26745981/71549838-a3ffca80-29c4-11ea-9f3f-dba89432e360.png)

**Comment by Manaci** [comment]
- [ ] [The Missing Magistrix](https://db.excalibur.ws/?quest=11526) you cannot use the [scroll](https://db.excalibur.ws/?item=34420) to teleport at the demon portal at the Dawning Square to Throne of Kil'jaeden in Hellfire.

**Comment by Manaci** [comment]
- [ ] [Lord Torvos](https://db.excalibur.ws/?npc=25140) is missing.

**Comment by Tereneckla** [comment]
- [ ] Dummy Infernal NPC at the demon portal at the Dawning Square visible.

**Comment by Manaci** [comment]
- [ ] [Bloodberry Bushes](https://db.excalibur.ws/?object=187333) are not respawning.

**Comment by Evolvee** [comment]
^^ it is respawning, its just pooled all over the isle, dont wait at one spot it will respawn somewhere else...

**Comment by Manaci** [comment]
- [ ] [Lord Torvos](https://db.excalibur.ws/?npc=25140) (ID 25140) is still missing.

**Comment by Evolvee** [comment]
its just not updated yet

**Comment by ozhanbinici** [comment]
**The Battle Must Go On**

after killing some of the demons in the area, emissary of hate should spawn, but she is not spawning, so quest can not be completed.

**Comment by ozhanbinici** [comment]
**Arm The Wards**

The wretched devourers constantly mana tap and silence the caster when in range, without any cd, and at every gcd, preventing the caster to cast anything.

**Comment by ozhanbinici** [comment]
**The Air Strikes Must Continue**

The mobs that you bomb in the dead scar are not respawning fast enough. The mobs i bombed in the first flight were still dead when i took a second flight.

**Comment by ozhanbinici** [comment]
**Don't Stop Now**

Darkspine Myrmidons do drop the keys but chests are not clickable.

**Comment by ozhanbinici** [comment]
**Disrupt the Greengill Coast**

Orb of Murloc Control is dropping and is functional but you are not getting any credit.

**Comment by ozhanbinici** [comment]
**Further Conversions**

Attuned Crystal Cores work after you kill an erratic sentry but you are not getting credit for the quest.

**Comment by ozhanbinici** [comment]
**Open for Business**

Bloodberry nodes are not respawning, or very low respawn rate.

**Comment by ozhanbinici** [comment]
**The Battle Must Go On**

Emissary of Hate did spawn, placing Shattered Sun Banner worked and did see the banner but did not give quest credit.

**Comment by ozhanbinici** [comment]
you can purchase epic gems for 15 badges, which should not be available at launch.

**Comment by Tereneckla** [comment]
PTR is on the last phase, so gem point is moot

**Comment by ozhanbinici** [comment]
**Rediscovering Your Roots**

the pet ability, "Expose Razorthorn Ability" is not working, pet also is not engaging in combat.

**Comment by Tereneckla** [comment]
The Battle Must Go On works, Emissary spawns, flag gives quest credit

- [ ] https://github.com/Atlantiss/NetherwingBugtracker/issues/6516#issuecomment-586753961

- [ ] https://github.com/Atlantiss/NetherwingBugtracker/issues/6516#issuecomment-586755353

Don't stop now: Chests are clickable
Disrupt the Greengill Coast: Getting credit
Further Conversions: Chance to not get credit still there, as described earlier
Open for Business: Pooled all over the Isle, more players will fix that.

**Comment by ozhanbinici** [comment]
**Rediscovering Your Roots**

after controlling a razorthorn ravager, you can use it like a hunter pet, will follow you everywhere (even if you go to the isle if quel'danas) and fight for you, warlocks can heal it with health funnel, etc.

**Comment by Tereneckla** [comment]
- [ ] https://www.wowhead.com/quest=11515/blood-for-blood
Not getting quest progress for kills

**Comment by Ychap** [comment]
First boss at Magister' Terrace [Selin Fireheart](https://db.excalibur.ws/?npc=24723)

You interrupt his spell [Drain Life](https://db.excalibur.ws/?spell=44294). When the boss now has no mana he should run to one of his crystals. But instead he bugs out of his camber.

**Comment by MartMlr** [comment]
Quest: "The Sanctum Wards"
Bug: You can finish the quest after collecting and using 4x Mana Remnants from anywhere on the Isle. 
Expected behavior: Need to be standing close to a Crystal Ward to be able to use it.

**Comment by Kersoph** [comment]
Kael'thas in Magisters' Terrace heroic. 
Could not cast heals as "You are in Shapeshift form" while im in Gravity Lapse.

**Comment by Kersoph** [comment]
Kael'thas in Magisters' Terrace heroic:
Wretched Bruiser, Wretched Husk and Wretched Skulker:
"Fel Infusion: Infuse the wretched with Fel Energy, dramatically increasing damage done by 2000 and attack speed by 100% for 10 sec." and
"Melee: 600 - to 800 on plate, dramatically increased to over 2k with Fel Infusion." But they hit 20'000+ on plate with that buff and normally onshot most tanks.
https://wow.gamepedia.com/Wretched_Bruiser
https://wow.gamepedia.com/Wretched_Husk
https://wow.gamepedia.com/Wretched_Skulker
So Tj20 is right, it is not working normally at the moment: https://github.com/Atlantiss/BugTracker/issues/572#issuecomment-72294953

**Comment by Evolvee** [comment]
![image](https://user-images.githubusercontent.com/1942409/75185455-6a3e0c80-5746-11ea-81f8-84947f8162d9.png)
@Tereneckla test this after update pls, i changed something, it might work now

**Comment by Evolvee** [comment]
fixed all (except the things i noted my edit in and the MGT stuff, which doesnt belong here)

**Comment by Tereneckla** [comment]
Erratic behaviour still has the chance
