### ISSUE TITLE
[Spell][Paladin] Seal of Command

### ISSUE THREAD

**Issue by Tankdiehutte** [Atlantiss/NetherwingBugtracker#6517]
**Description**: The Seal of Command has a ~1% chance to resist, like a spell here.

**Current behaviour**: The Paladin spell Seal of Command procs 7 times per minute ( blizzlike ), doesnt proc on parries/dodges/misses(not blizzlike), the damage is reduced by blocks (blizzlike), gets resisted by ~1% (like a spell, not blizzlike ) and doesn't miss when not hitcapped (not blizzlike)

**Expected behaviour**: The Seal shouldn't be resistable. Instead it should be dodge, parry, block and missable. Also it should be able to proc on every autoattack. 
"Although unreliable due to the fact that it's based on a chance to proc on every melee attack [...]" - https://wowwiki.fandom.com/wiki/Seal_of_Command_(old)?oldid=1432430#Usage
" The actual attack made when Seal of Command procs is resolved as a separate melee special-attack that deals holy damage. It is resolved identically to any Instant Attack -- it can miss, be dodged, be parried, and be blocked, and will do double damage on a crit (rather than 1.5x damage as a normal spell crit would). " - https://wowwiki.fandom.com/wiki/Seal_of_Command_(old)?oldid=1432430#Damage

Here i have a Screenshot of a Resist: https://www.bilder-upload.eu/bild-f8aba0-1577641667.jpg.html

Because my guild isnt raiding til january i dont have a screenshot of a raidrecount. But usually the amound of resists is about 1% sometime higher, sometimes a bit lower, but resists shouldnt be possible.

**Server Revision**:

**Comment by Wolffenstein** [comment]
Fixed in rev 3230.

**Comment by Tankdiehutte** [comment]
![image](https://user-images.githubusercontent.com/56139988/71692474-4267a380-2daa-11ea-9e61-dd7aa8bd296e.png)

Seems to be even worse now ( Full ZA Recount ) Bosses around 16% resist

**Comment by Tankdiehutte** [comment]
![image](https://user-images.githubusercontent.com/56139988/71692555-835fb800-2daa-11ea-9524-3e398e65db0b.png)

Hexlord fight.

![image](https://user-images.githubusercontent.com/56139988/71692581-95415b00-2daa-11ea-980e-399855049353.png)

Zul'jin
