### ISSUE TITLE
Arena icon on minimap upon joining is not visible.

### ISSUE THREAD

**Issue by AWIDIUS** [Atlantiss/NetherwingBugtracker#6519]
Arena icon on minimap upon joining is not visible.
![image](https://user-images.githubusercontent.com/45521546/71564004-5d2fd480-2a99-11ea-9c2f-33bde55e912a.png)

**Comment by Evolvee** [comment]
joining what

**Comment by veekk** [comment]
can confirm, if ur mate que arena u can't see icon until arena pop

**Comment by AWIDIUS** [comment]
Upon joining an arena battle. Either 2v2 or 3v3.

**Comment by Evolvee** [comment]
confirmed, not sure yet if its due to the partner being on different map

**Comment by AWIDIUS** [comment]
😂😂

**Comment by AWIDIUS** [comment]
Faith in NW PvP is slowly restoring 🙄

**Comment by Wolffenstein** [comment]
Fixed in rev 3350.
