### ISSUE TITLE
Wrathscale Siren

### ISSUE THREAD

**Issue by AlteredAli** [Atlantiss/NetherwingBugtracker#652]
[//]: # (Enclose links to things related to the bug using http://wowhead.com or any other TBC database.)
[//]: # (You can use screenshot ingame to visual the issue.)
[//]: # (Write your tickets according to the format:)
[//]: # ([Quest][Azuremyst Isle] Red Snapper - Very Tasty!)
[//]: # ([NPC] Magistrix Erona)
[//]: # ([Spell][Mage] Fireball)
[//]: # ([Npc][Drop] Ghostclaw Lynx)
[//]: # ([Web] Armory doesnt work)

**Description**: 
Wrathscale siren's on Azuremyst Isle are not casting frostbolt/frostnova
**Current behaviour**:
only meeleing
**Expected behaviour**: 
should be casting spells like frostbolt and frostnova and shouldn't ever meele unless out of mana
**Server Revision**: 
2060

**Comment by The14me** [comment]
Frostbolt ID 32984
Missing Screech ID 31273
Not suppose to have Frost nova

**Comment by Evolvee** [comment]
rev xdd
