### ISSUE TITLE
Ravagers in Razorthorn Trail - Hellfire Peninsula 

### ISSUE THREAD

**Issue by Bonenemesis** [Atlantiss/NetherwingBugtracker#6521]
Hi,

I have discovered 2 days ago while questing, the ravager mobs will cause a 'Fatal Condition' crash if you are attacking them. I had to restart my pc several times after testing to see if the crash was going to continue. I do not have any proof to support my claim but I am unable to complete a quest from the area. Can you please take a look at it when you have a moment?

Many thanks,
Some random player reporting bugs

**Comment by Evolvee** [comment]
Write a ticket or note down your ingame nickname to gamemasters on discord...

**Comment by Evolvee** [comment]
It is probably your clients problem, I cant reproduce this.
