### ISSUE TITLE
[NPC] Jubjub is stuck :(

### ISSUE THREAD

**Issue by Tereneckla** [Atlantiss/NetherwingBugtracker#6522]
[//]: # (Enclose links to things related to the bug using http://wowhead.com or any other TBC database.)
[//]: # (You can use screenshot ingame to visual the issue.)
[//]: # (Write your tickets according to the format:)
[//]: # ([Quest][Azuremyst Isle] Red Snapper - Very Tasty!)
[//]: # ([NPC] Magistrix Erona)
[//]: # ([Spell][Mage] Fireball)
[//]: # ([Npc][Drop] Ghostclaw Lynx)
[//]: # ([Web] Armory doesnt work)
[//]: # (To find server revision type `.server info` command in the game chat.)

**Description**: 
![image](https://user-images.githubusercontent.com/50233983/71595323-5c4f7f00-2b3b-11ea-9a92-a4d2cf628c86.png)

**Current behaviour**: He is stuck in the fence.

**Expected behaviour**:  He moves around dark moon fair.

**Server Revision**: 3226

**Comment by Evolvee** [comment]
moves around... where? how?

**Comment by Evolvee** [comment]
anyway this is DF-related, the entire DF needs complete rework

**Comment by Godmatik** [comment]
Darkmoon Faire fully reworked last year in Rev 3668
