### ISSUE TITLE
Ranshalla in Winterspring is bugged

### ISSUE THREAD

**Issue by Jopeppy** [Atlantiss/NetherwingBugtracker#6523]
I tried 3 times to do the quest "Guardian of the Altar". Ranshalla arrives in the first cave to do her thing, then remains there with the arms stretched out in the air for what seems like forever, but nothing happens. There is no other sound. Of course if you leave the cave and get to a certain distance away from her, the quest fails.

**Comment by Evolvee** [comment]
![image](https://user-images.githubusercontent.com/1942409/71619909-117b4900-2bc7-11ea-97ad-69deb860518e.png)

**Comment by Jopeppy** [comment]
The quest "Guardian of the Altar" with Ranshalla is still not working. She is bugged same as i reported 17 days ago. Was an attempt made to debug the quest?

**Comment by Tereneckla** [comment]
Yes, the torches in the caves do not become usable once she starts her spell.

**Comment by moemiki** [comment]
Still broken

**Comment by Evolvee** [comment]
xd cpp scripts in a nutshell
