### ISSUE TITLE
[core/sai/gameobject] The corrupted flowers in Felwood are bugged

### ISSUE THREAD

**Issue by Jopeppy** [Atlantiss/NetherwingBugtracker#6524]
I  tried to collect many different flowers in Felwood, you click on the flower, but it never reappears as cleansed. No matter how you place your cursor, the flower cannot be clicked on. If you`re a herb collector, you see the herd flickering on your map.

**Comment by Evolvee** [comment]
Possibly broken by new loot rework.

**Comment by Evolvee** [comment]
@Wolffenstein this seems to be a problem of
![image](https://user-images.githubusercontent.com/1942409/71641551-3e4e5f80-2c9e-11ea-8f49-15f674bee175.png)

negative spawntime secs combined with SAI:
![image](https://user-images.githubusercontent.com/1942409/71641561-58883d80-2c9e-11ea-89f0-8691224894cd.png)

repro gobs: 164886/164882

**Comment by Evolvee** [comment]
^^ I can easily hackfix this but this is a global issue I guess, considering theres 72 different templates with negatives in them

**Comment by Godmatik** [comment]
Duplicate #8359
