### ISSUE TITLE
Acidic Splash incorrect damage

### ISSUE THREAD

**Issue by AWIDIUS** [Atlantiss/NetherwingBugtracker#6526]
https://imgur.com/a/AZwWCMn Damage done by this DoT incorrectly dealing damage. Also doesn't reducing armor.

**Comment by Evolvee** [comment]
![image](https://user-images.githubusercontent.com/1942409/71676726-40d5b580-2d81-11ea-974f-553bc0f42804.png)

it scaled with level of caster

**Comment by AWIDIUS** [comment]
Im perfectly fine with that mob dealing more damage, but tooltip isn't correct.

**Comment by Evolvee** [comment]
Tooltips are static, they cant update

**Comment by Evolvee** [comment]
Are u sure about the armor part?

**Comment by AWIDIUS** [comment]
Yep, I've pulled that mob and immediatelly looked at armor values, there was no sign of armor been reduced by that amount stated in tooltip.

**Comment by Tereneckla** [comment]
Armor does not get reduced

**Comment by Tereneckla** [comment]
#2714
