### ISSUE TITLE
[PvP] Halaa Bugs

### ISSUE THREAD

**Issue by Manaci** [Atlantiss/NetherwingBugtracker#6528]
In the wake of the upcoming patch 2.4 and the [Halaa daily quests](https://db.excalibur.ws/?npc=24867) arriving, I figured I'd try and report the bugs that are currently plaguing Halaa.

**1st bug** - The Wyverns you fly to bomb the guards with are flying at flightpath speed when they should only fly as fast as [this](https://youtu.be/USPHP6a9IaI?t=69). I timed the current speed of a  full flying round lasting about 1 minute while in the video it lasts 1 minute and 35 seconds.

**2nd bug** - The Alliance/Horde Wyvern roosts don't despawn when Halaa is recaptured and they don't explode when interacting with the Bomb Wagons next to them as it should, leaving you with 2x Destroyed Wyvern Roosts and 2x Wyvern Roosts at the same time = Horde/Alliance can go bombing when they control Halaa. (Can't screenshot this cause newly restarted server but it is noticable after the 1st recapture)
The objects are all placed correctly but just have to be despawned on enemy captures, see [Destroyed Wyvern/ Wyvern Roosts](https://db.excalibur.ws/?search=Wyvern%20Roost) and [Bomb Wagon](https://db.excalibur.ws/?object=182222) .

**3rd bug** - The vendor NPCs in Halaa don't despawn when Halaa is recaptured, ending up with endless amounts of them depending on how many recaptures are done until a new server update is out. (Can't screenshot this cause newly restarted server but it is noticable after the 1st recapture)

Full list of NPCs that despawn when HORDE recaptures Halaa and respawn(as they already do) when Alliance recaptures Halaa.
[Quartermaster Davian Vaclav](https://db.excalibur.ws/?npc=18822) (ID 18822)
[Chief Researcher Kartos](https://db.excalibur.ws/?npc=18817) (ID 18817)
[Cendrii](https://db.excalibur.ws/?npc=21487) (ID 21487)
[Aldraan](https://db.excalibur.ws/?npc=21485) (ID 21485)
[Banro](https://db.excalibur.ws/?npc=21488) (ID 21488)
Full list of NPCs that despawn when ALLIANCE recaptures Halaa and respawn(as they already do) when Horde recaptures Halaa.
[Quartermaster Jaffrey Noreliqe](https://db.excalibur.ws/?npc=18821) (ID 18821)
[Chief Researcher Amereldine](https://db.excalibur.ws/?npc=18816) (ID 18816)
[Embelar](https://db.excalibur.ws/?npc=21484) (ID 21484)
[Coreiel](https://db.excalibur.ws/?npc=21474) (ID 21474)
[Tasaldan](https://db.excalibur.ws/?npc=21483) (ID 21483)
These NPCs are also ordered in both lists as their horde/ally equivalent to easier show who despawns who. 

**4th bug** - The Horde and Alliance Halaani Guards don't have their [Shoot](https://db.excalibur.ws/?spell=23337) ability, so enemies can just fly into the other faction's controlled Halaa on flying mounts without getting knockbacked. This is why all old videos have people going to attacks on Halaa by ground mounts as it was not possible to fly in there without getting knockbacked to hell if you were the attacker unless one side of guards had been killed or was occupied with shooting someone else. [Proof of shooting](https://youtu.be/1cATKL5273I?t=20) (Left side you can see a guard shooting an arrow up at a flying attacker)

**5th bug** - After a Halaa capture, Halaa Battle Tokens are obtainable on kills, but after a few hours it is not possible to gain anymore until the opposite factions recaptures Halaa adn then you can obtain them for a limited time again. Might have something to do with the [Nagrand Tower Token](https://db.excalibur.ws/?search=nagrand+tower+token) spell that generates the tokens and maybe tied into the [Halaa Banner](https://db.excalibur.ws/?object=182210) too.

**6th bug** - It is still possible to kite some (ONLY some, have them all work like the ones that run back pretty quick and can't be kited) of the [Alliance Halaani Guards](https://db.excalibur.ws/?npc=182569) and possibly some of the [Horde Halaani Guards](https://db.excalibur.ws/?npc=18192) so far away that when they try and get back, they get stuck in terrain and don't come back for hours until they force-reset or possibly if the server crashes.

**Server Revision**: 
3236

**Comment by Evolvee** [comment]
@jannitor
![image](https://user-images.githubusercontent.com/1942409/71736751-2ddee600-2e52-11ea-91c6-8013e1841aee.png)

**Comment by Tereneckla** [comment]
this is more detailed than any of those
#4994 is fixed
will clean once I can

**Comment by Wolffenstein** [comment]
Fixed in rev 3328.
