### ISSUE TITLE
[Spell][Warrior] Spell Reflection

### ISSUE THREAD

**Issue by Drainlock** [Atlantiss/NetherwingBugtracker#6530]
Spell reflected by warrior dealing damage based on warriors spell damage instead of spell damage of  person who casted spell.
Also reflected siphon life doesn't heals warlock like it should. Proof https://youtu.be/yU6T3RA77ZE?t=270
Warrior reflected rank 6 sl 
![siphon life](https://user-images.githubusercontent.com/59121561/71737480-6f748e80-2e5c-11ea-9e9c-b58d2c0537af.jpg)
Damage from SL on enemy 
![SL damage](https://user-images.githubusercontent.com/59121561/71737525-929f3e00-2e5c-11ea-9f05-a2cf0cd552f6.jpg)

**Comment by Godmatik** [comment]
Rev 4017 - no longer an issue
Reflected spells are doing proper damage based on the spell power of the original person who cast the spell
