### ISSUE TITLE
[Spell] [Shaman] Searing Totem's damage gets attributed to the Shaman

### ISSUE THREAD

**Issue by Tereneckla** [Atlantiss/NetherwingBugtracker#6531]
[//]: # (Enclose links to things related to the bug using http://wowhead.com or any other TBC database.)
[//]: # (You can use screenshot ingame to visual the issue.)
[//]: # (Write your tickets according to the format:)
[//]: # ([Quest][Azuremyst Isle] Red Snapper - Very Tasty!)
[//]: # ([NPC] Magistrix Erona)
[//]: # ([Spell][Mage] Fireball)
[//]: # ([Npc][Drop] Ghostclaw Lynx)
[//]: # ([Web] Armory doesnt work)
[//]: # (To find server revision type `.server info` command in the game chat.)

**Description**: 
![image](https://user-images.githubusercontent.com/50233983/71765626-874d2080-2ef7-11ea-885c-7216e24b11d5.png)
It even procs Lightning Capacitor.

https://github.com/Atlantiss/NetherwingBugtracker/issues/393#issuecomment-425100028

**Current behaviour**: Searing Totem's damage is dealt by the Shaman, making it able to proc various talents, trinkets or also Judgement of Wisdom for the Shaman.

**Expected behaviour**: Searing Totem's damage is dealt by the totem.
No such procs happen.
**Server Revision**: 3236

**Comment by The14me** [comment]
Still issue in 3441

**Comment by Godmatik** [comment]
Was fixed last year
