### ISSUE TITLE
[Megathread] Spell Delay collection thread

### ISSUE THREAD

**Issue by Tereneckla** [Atlantiss/NetherwingBugtracker#6532]
[//]: # (Enclose links to things related to the bug using http://wowhead.com or any other TBC database.)
[//]: # (You can use screenshot ingame to visual the issue.)
[//]: # (Write your tickets according to the format:)
[//]: # ([Quest][Azuremyst Isle] Red Snapper - Very Tasty!)
[//]: # ([NPC] Magistrix Erona)
[//]: # ([Spell][Mage] Fireball)
[//]: # ([Npc][Drop] Ghostclaw Lynx)
[//]: # ([Web] Armory doesnt work)
[//]: # (To find server revision type `.server info` command in the game chat.)

Just collecting all reports related to ~~spellbatching~~ spell delay

- [ ] #4124
- [ ] #5196
- [ ] #3914 probably
- [ ] #1875

**Comment by Godmatik** [comment]
Spell batching/delay was disabled, so will close this
