### ISSUE TITLE
[Quest][Raising Spirits]Highland Raptor Eye  - missing double drop

### ISSUE THREAD

**Issue by 0R1Ch1** [Atlantiss/NetherwingBugtracker#6533]
[Quest][Raising Spirits][item][drop]Highland Raptor Eye  - missing double drop

** Description **:
There is just one chance of a Highland Raptor Eye drop item from the Highland Striders and Highland Thrashers monsters.

** Current behavior **:
- item drop for Highland Raptor Eye is set only once

** Expected behavior **:
- Highland Raptor Eye should have two chances to drop from one mob.

**Comment by Tereneckla** [comment]
Do you have some kind of proof that there should be double drops?

**Comment by duzyizly** [comment]
https://youtu.be/XccyLbaij2c?list=PL49Ga_-r7iKkxrbckm9CkUhWzxqrOnw-n&t=1397

here is joana doing this quest back in vanilla.
It never dropped for Him twice (grinding about 20 min).

**Comment by Tereneckla** [comment]
Only finding people trying to apply common sense to a video game
