### ISSUE TITLE
[MC] [core] Fire at Will! AA bugged.

### ISSUE THREAD

**Issue by AWIDIUS** [Atlantiss/NetherwingBugtracker#6534]
Everything described in description under video.
https://www.youtube.com/watch?v=1TWo8pGCE5k&feature=youtu.be

**Comment by Evolvee** [comment]
@Wolffenstein same issue as i told you about in the discord PM with ravagers

**Comment by Godmatik** [comment]
Unable to reproduce - can auto-attack just fine while having the cannon as a pet for the quest.
Fixed at some point i presume
