### ISSUE TITLE
[Item] Netherwing Egg missing on Netherspite loot table

### ISSUE THREAD

**Issue by Healweed** [Atlantiss/NetherwingBugtracker#6535]
**Description**: 
Confirmed with @Evolvee  As of still now, Netherwing eggs is missing on Netherspite loot table. Netherspite should drop 1-3 eggs (drop rate not guaranteed, but way above 60%).

**Current behaviour**:
Netherspite doesnt have netherwing eggs on loot table

**Expected behaviour**: 
Should drop between 1-3 eggs.
Proof:
https://wowwiki.fandom.com/wiki/Netherwing_Egg

> Patch 2.2.0 (25-Sep-2007): Drops from Netherspite.

**Server Revision**: 
3236

**Comment by Evolvee** [comment]
next rev

**Comment by Tereneckla** [comment]
rip evolve, wowwiki is full of shit
earliest mention on other places is 2013, 5.2/5.3

**Comment by Evolvee** [comment]
wat

**Comment by Evolvee** [comment]
i liked it :( :(

**Comment by Tereneckla** [comment]
Not on thotbot either, sooooo

**Comment by Evolvee** [comment]
https://youtu.be/ee925OTFBCA?t=14
