### ISSUE TITLE
[Item] S1 Paladin Healing Helmet costs wrong marks

### ISSUE THREAD

**Issue by Tereneckla** [Atlantiss/NetherwingBugtracker#6536]
[//]: # (Enclose links to things related to the bug using http://wowhead.com or any other TBC database.)
[//]: # (You can use screenshot ingame to visual the issue.)
[//]: # (Write your tickets according to the format:)
[//]: # ([Quest][Azuremyst Isle] Red Snapper - Very Tasty!)
[//]: # ([NPC] Magistrix Erona)
[//]: # ([Spell][Mage] Fireball)
[//]: # ([Npc][Drop] Ghostclaw Lynx)
[//]: # ([Web] Armory doesnt work)
[//]: # (To find server revision type `.server info` command in the game chat.)

**Description**: 
https://i.imgur.com/w2lejS1.jpg
Ret and Shockadin for Alterac
https://i.imgur.com/N8ligss.jpg
Healing for Arathi

**Current behaviour**: Healing Helmet costs Arathi Marks

**Expected behaviour**: Healing Helmet costs Alterac Marks

**Server Revision**: 3236

**Comment by AWIDIUS** [comment]
Lul golds

**Comment by Evolvee** [comment]
fixed
