### ISSUE TITLE
[spell][warrior]  "Sunder Armor" part of Devastate is broken

### ISSUE THREAD

**Issue by sifiuocz** [Atlantiss/NetherwingBugtracker#6538]
**Description**: 
This bug is significantly limiting warrior tank's threat output and should be prioritized.

**Current behaviour**:
Currently after the player uses the ability Devastate all seems to be well but sometimes Sunder armor gets, independently from devastate, mitigated by the enemy (tested on NPCs) resulting in a loss of valuable debuff in the enemy as well as limiting the warrior's threat potentintial. 
Here are some screeshots:

![WoWScrnShot_010620_174302](https://user-images.githubusercontent.com/13140968/71839024-87e1e480-30ba-11ea-81a6-804889336ba1.jpg)

Here you can see my devastate landing and my sunder armor being parried at the same time.

![WoWScrnShot_010620_173646](https://user-images.githubusercontent.com/13140968/71839065-a1832c00-30ba-11ea-9f5f-affcc887bd4f.jpg)

Here you can see something similar. The sunder armor is dodged here. Sunder armor missing target also happened to me. This means that Sunder armor application from devastate ability is a subject of a hit table roll.

![WoWScrnShot_010620_163914](https://user-images.githubusercontent.com/13140968/71839231-fcb51e80-30ba-11ea-93d7-1eef1440503f.jpg)
![WoWScrnShot_010620_163910](https://user-images.githubusercontent.com/13140968/71839242-02126900-30bb-11ea-9f08-641dc2e0a6cd.jpg)
In these two pictures of my multiple dungeon run damage summary. You can see that I used devastate 1073 times of which 898 landed on the target. On the second picture you can see that Recount counted 80 non-hits (parries, misses, dodges) on Sunder armor. I never used sunder armor as a independant ability in this case. 

**Expected behaviour**: 
Sunder armor application part of devastate should be exempt from hit table rolling. The debuff should be applied every time devastate lands on target.

**Server Revision**: 
3236

**Comment by Godmatik** [comment]
Something to double check / watch for after the weapon proc rework branch goes live

**Comment by Godmatik** [comment]
Being fixed with next server update
