### ISSUE TITLE
[Quest] Data Resque

### ISSUE THREAD

**Issue by Tereneckla** [Atlantiss/NetherwingBugtracker#6539]
[//]: # (Enclose links to things related to the bug using http://wowhead.com or any other TBC database.)
[//]: # (You can use screenshot ingame to visual the issue.)
[//]: # (Write your tickets according to the format:)
[//]: # ([Quest][Azuremyst Isle] Red Snapper - Very Tasty!)
[//]: # ([NPC] Magistrix Erona)
[//]: # ([Spell][Mage] Fireball)
[//]: # ([Npc][Drop] Ghostclaw Lynx)
[//]: # ([Web] Armory doesnt work)
[//]: # (To find server revision type `.server info` command in the game chat.)

**Description**: White Punch Card (Item 9279) are supposed to drop for Alliance and Horde without having the quest [Data Resque](https://classic.wowhead.com/quest=2930/data-rescue)
**Current behaviour**: Only drops for Alliance if you have the quest.
Doesn't drop for Horde at all.

**Expected behaviour**: Drops anytime on any faction.

**Comment by Evolvee** [comment]
there is some fuckery in wowhead comments, can u check?

![image](https://user-images.githubusercontent.com/1942409/73140486-baf41400-4079-11ea-9888-74103821a784.png)


![image](https://user-images.githubusercontent.com/1942409/73140493-cba48a00-4079-11ea-8a60-54a03dff2ed9.png)

**Comment by Tereneckla** [comment]
Make https://wowwiki.fandom.com/wiki/White_Punch_Card drop without Quest.

Using https://wowwiki.fandom.com/wiki/Yellow_Punch_Card on https://classic.wowhead.com/object=142475/matrix-punchograph-3005-b should teach you Minor Recombobulator if you have Engi 140+ (in addition to giving you the Red Punch Card)

https://wowwiki.fandom.com/wiki/Minor_Recombobulator

**Comment by Evolvee** [comment]
so this is fixed?

**Comment by Evolvee** [comment]
fixed -.-
