### ISSUE TITLE
[Object][Desolace] Shellfish Trap

### ISSUE THREAD

**Issue by tomatosz** [Atlantiss/NetherwingBugtracker#6540]
[//]: # (Enclose links to things related to the bug using http://wowhead.com or any other TBC database.)
[//]: # (You can use screenshot ingame to visual the issue.)
[//]: # (Write your tickets according to the format:)
[//]: # ([Quest][Azuremyst Isle] Red Snapper - Very Tasty!)
[//]: # ([NPC] Magistrix Erona)
[//]: # ([Spell][Mage] Fireball)
[//]: # ([Npc][Drop] Ghostclaw Lynx)
[//]: # ([Web] Armory doesnt work)
[//]: # (To find server revision type `.server info` command in the game chat.)

**Description**: The [shellfish trap](https://classic.wowhead.com/object=176635/shellfish-trap)s that will spawn an enemy (and will not be lootable) are recognizable. This causes the droprate to seem low as people avoid the empty ones.

**Current behaviour**: The traps that spawn an enemy have a red crystal in them, that remains there until the trap respawns. 
![image](https://user-images.githubusercontent.com/18441882/72281454-e539e080-363a-11ea-97c1-a920651bcfa2.png)

**Expected behaviour**: The traps should be indistinguishable from lootable traps (here is a [vid](https://youtu.be/Nkid2f4Vv2Q?t=74) showing an enemy spawning)

**Server Revision**: 3236

(ETA screenshot)

**Comment by Evolvee** [comment]
same as https://github.com/Atlantiss/NetherwingBugtracker/issues/6552  @Wolffenstein

**Comment by Wolffenstein** [comment]
Fixed in rev 3368.
