### ISSUE TITLE
[NPC] Forsaken Bodyguard

### ISSUE THREAD

**Issue by Tereneckla** [Atlantiss/NetherwingBugtracker#6541]
[//]: # (Enclose links to things related to the bug using http://wowhead.com or any other TBC database.)
[//]: # (You can use screenshot ingame to visual the issue.)
[//]: # (Write your tickets according to the format:)
[//]: # ([Quest][Azuremyst Isle] Red Snapper - Very Tasty!)
[//]: # ([NPC] Magistrix Erona)
[//]: # ([Spell][Mage] Fireball)
[//]: # ([Npc][Drop] Ghostclaw Lynx)
[//]: # ([Web] Armory doesnt work)
[//]: # (To find server revision type `.server info` command in the game chat.)

**Description**: Forsaken Bodyguard bug out if you pull them and then reset them.

**Current behaviour**: They float in a straight path, also underground.
![WoWScrnShot_010820_003742](https://user-images.githubusercontent.com/50233983/71938391-8219fb00-31af-11ea-923c-fc2eb0de6246.jpg)

**Expected behaviour**: They keep following the path.

**Comment by Evolvee** [comment]
converted old wps to new waypoint standart, should hopefully fix it (otherwise its core fuckup)

**Comment by Evolvee** [comment]
(could also very possibly be shit waypoints xd)
