### ISSUE TITLE
The Relic's Emanation

### ISSUE THREAD

**Issue by Proprvilin** [Atlantiss/NetherwingBugtracker#6545]
[//]: # (Enclose links to things related to the bug using http://wowhead.com or any other TBC database.)
[//]: # (You can use screenshot ingame to visual the issue.)
[//]: # (Write your tickets according to the format:)
[//]: # ([Quest][Azuremyst Isle] Red Snapper - Very Tasty!)
[//]: # ([NPC] Magistrix Erona)
[//]: # ([Spell][Mage] Fireball)
[//]: # ([Npc][Drop] Ghostclaw Lynx)
[//]: # ([Web] Armory doesnt work)
[//]: # (To find server revision type `.server info` command in the game chat.)

**Description**: Initially offered upon completing the predecessor quest, but when the escape key was hit to turn on instant quest text prior to accepting the quest, the quest-giver (Chu'a'lor) no longer had a quest to offer - nor did the quest enter the quest log.

**Current behaviour**: No quest being offered.

**Expected behaviour**:  The quest 'The Relic's Emanation' being offered.

**Server Revision**: 3236.

**Comment by GMThunderan** [comment]
I could reproduce that on PTR. When you try to accept the follow-up, which is "The Relic's Emanation", it says "You don't meet the requirements for that quest". Maybe related to the [negative class condition bug](https://github.com/Atlantiss/NetherwingBugtracker/issues/6212)? It was the same behaviour with the fel hunter quest [here](https://github.com/Atlantiss/NetherwingBugtracker/issues/6508).

**Comment by Proprvilin** [comment]
Upon becoming eligible for a different quest by the same NPC, he once again offers The Relic's Emanation, and it properly appears in the quest log.

**Comment by GMThunderan** [comment]
Thank you for letting us know! Apparently it's just the wrong order of opening the quests. 
Correct order can be found [here](https://wowwiki.fandom.com/wiki/Quest:The_Relic%27s_Emanation).
