### ISSUE TITLE
[API][macro] SetRaidSubgroup() and SwapRaidSubgroup()

### ISSUE THREAD

**Issue by Stogi7789** [Atlantiss/NetherwingBugtracker#6546]
[//]: # (Enclose links to things related to the bug using http://wowhead.com or any other TBC database.)
[//]: # (You can use screenshot ingame to visual the issue.)
[//]: # (Write your tickets according to the format:)
[//]: # ([Quest][Azuremyst Isle] Red Snapper - Very Tasty!)
[//]: # ([NPC] Magistrix Erona)
[//]: # ([Spell][Mage] Fireball)
[//]: # ([Npc][Drop] Ghostclaw Lynx)
[//]: # ([Web] Armory doesnt work)
[//]: # (To find server revision type `.server info` command in the game chat.)

**Description**: 
There are two API commands to swap people inside a raid.
First one is SwapRaidSubgroup(index1, index2);
https://wowwiki.fandom.com/wiki/API_SwapRaidSubgroup?oldid=1399153

Second one is SetRaidSubgroup(index, subgroup);
https://wowwiki.fandom.com/wiki/API_SetRaidSubgroup?oldid=1020137

Both of them work outfight but stop working as soon as the person using the macro is infight.

**Current behaviour**:
API commands work outfight, but not infight.

**Expected behaviour**: 
Both API commands should work infight.
The first one got protected at Cata but not before. 
https://wow.gamepedia.com/API_SwapRaidSubgroup

**Server Revision**: 
[3239]

**Comment by Wolffenstein** [comment]
It's blocked by the client, not the server.
