### ISSUE TITLE
Rescue OOX-09/hl no group completion

### ISSUE THREAD

**Issue by temperrr** [Atlantiss/NetherwingBugtracker#6548]
[//]: # (Enclose links to things related to the bug using http://wowhead.com or any other TBC database.)
[//]: # (You can use screenshot ingame to visual the issue.)
[//]: # (Write your tickets according to the format:)
[//]: # ([Quest][Hinterlands]Rescue OOX-09/hl )
[//]: # ([NPC] Homing Robot OOX-09/HL

**Description**: 
Quest will not give the group completion of the quest when succesfully escorted. Instead, only the person that takes the quest  will get completion
**Current behaviour**:
Only the person that takes the quest gets the quest completed at the end.
**Expected behaviour**: 
The whole party should get the quest completed at the end
**Server Revision**: 
 3236

**Comment by duzyizly** [comment]
ptr 3403, just done this as 2 players, looks fine.

![WoWScrnShot_062320_221659](https://user-images.githubusercontent.com/43931626/85456836-acb21180-b59f-11ea-8e0f-4a00219327cc.jpg)
