### ISSUE TITLE
[NPC] Savage Owlbeast [event]

### ISSUE THREAD

**Issue by The14me** [Atlantiss/NetherwingBugtracker#6549]
**Current behaviour**:

**Expected behaviour**: 
The [Owl ](https://classic.wowhead.com/npc=2929/savage-owlbeast#comments:id=2801431) 

During the day you'll find them all over where they're supposed to be, but at night they don't seem to spawn at all.
https://classic.wowhead.com/npc=2929/savage-owlbeast#comments:id=2801431
**Server Revision**:

**Comment by Evolvee** [comment]
![image](https://user-images.githubusercontent.com/1942409/72217239-0a8bf900-352c-11ea-904a-cb805954831d.png)

**Comment by Evolvee** [comment]
bring more evidence or close, its a hearsay as of now

**Comment by The14me** [comment]
Leave the night ''event'' .Just check for shared spawn and if its ok-->close.
