### ISSUE TITLE
[Quest] Your fortune awaits you... (darkmoon faire quest)

### ISSUE THREAD

**Issue by DarthNekr0s** [Atlantiss/NetherwingBugtracker#655]
**Description**:  for this quest it sends you to deadmines dungeon and when you enter, a chest should spawn in the entrance zone https://www.wowhead.com/quest=7938/your-fortune-awaits-you (see screenshots) comments say it may take up to 2min to appear. have been standing at the location for 15min and no chest

**Current behaviour**: chest not spawning

**Expected behaviour**:  chest spawns after zoning in, turn in quest by opening it

**Server Revision**: 2060

![wowscrnshot_092618_220439](https://user-images.githubusercontent.com/16113944/46078827-a0393300-c1d8-11e8-9669-16fb9112cd62.jpg)

**Comment by Manaci** [comment]
[Fixed](https://github.com/Atlantiss/NetherwingBugtracker/issues/6236)
