### ISSUE TITLE
not give daily PvP in Terokkar Forest 

### ISSUE THREAD

**Issue by pgswow** [Atlantiss/NetherwingBugtracker#6550]
Hello! I cant give daily PvP in Terokkar Forest, at NPC Exorcist Sullivan without blue "?".
![WoWScrnShot_011120_200306](https://user-images.githubusercontent.com/15922431/72252827-aef86300-3632-11ea-8963-c178fa6c41e5.jpg)

**Comment by Tereneckla** [comment]
https://www.wowhead.com/quest=11505/spirits-of-auchindoun is added in 2.4

**Comment by pgswow** [comment]
> 
> 
> https://www.wowhead.com/quest=11505/spirits-of-auchindoun is added in 2.4

Netherwing 2.4.3 - why i cant give quest?

**Comment by eri1997** [comment]
It's because game content is in 2.3 state right now. I't will be available when the server launches 2.4 content (swp isle and so on) .
