### ISSUE TITLE
Most Main-Hand weapons

### ISSUE THREAD

**Issue by GeorgieTragnar** [Atlantiss/NetherwingBugtracker#6551]
[//]: # (Enclose links to things related to the bug using http://wowhead.com or any other TBC database.)
[//]: # (You can use screenshot ingame to visual the issue.)
[//]: # (Write your tickets according to the format:)
[//]: # ([Quest][Azuremyst Isle] Red Snapper - Very Tasty!)
[//]: # ([NPC] Magistrix Erona)
[//]: # ([Spell][Mage] Fireball)
[//]: # ([Npc][Drop] Ghostclaw Lynx)
[//]: # ([Web] Armory doesnt work)
[//]: # (To find server revision type `.server info` command in the game chat.)

**Description**: 
In 2.4.2 patch notes is this quote:
```Most Main-Hand weapons are now One-Hand weapons. ```
the list:
``` 
Fireguard -> Blazeguard -> Blazefury
The Planar Edge -> Black Planar Edge -> Wicked Edge of the Planes
Drakefist Hammer -> Dragonmaw -> Dragonstrike
Annihilator
Axe of the deep wounds
most of vanilla 60 blue main hand weapons
 ```
**Current behaviour**:
I've seen only Blacksmithing weapons as unique and Main-hand ingame.
As for other items, I did not find an online mention about the change to be one-handed, but they are listed as one handed in online tbc databases
**Expected behaviour**: 
These weapons had their unique status removed and are now classified as one-hand weapons, enabling them to be equipped in off-hand
**Server Revision**:

**Comment by Evolvee** [comment]
we are not in 2.4. content yet

**Comment by GeorgieTragnar** [comment]
I know, when I asked if this is going to be part of 2.4 content patch I was told to create this report.

**Comment by Evolvee** [comment]
It will
