### ISSUE TITLE
[Object][Desolace] Kodo Bones

### ISSUE THREAD

**Issue by tomatosz** [Atlantiss/NetherwingBugtracker#6552]
[//]: # (Enclose links to things related to the bug using http://wowhead.com or any other TBC database.)
[//]: # (You can use screenshot ingame to visual the issue.)
[//]: # (Write your tickets according to the format:)
[//]: # ([Quest][Azuremyst Isle] Red Snapper - Very Tasty!)
[//]: # ([NPC] Magistrix Erona)
[//]: # ([Spell][Mage] Fireball)
[//]: # ([Npc][Drop] Ghostclaw Lynx)
[//]: # ([Web] Armory doesnt work)
[//]: # (To find server revision type `.server info` command in the game chat.)

**Description**: The Kodo Bones ([link 1](https://classic.wowhead.com/object=176751/) and [link 2](https://classic.wowhead.com/object=176752/)) for the quest [Bone Collector](https://classic.wowhead.com/quest=5501/) spawn too many [Kodo Apparition](https://classic.wowhead.com/npc=11521)s, and the ones spawning two are recognizable. Similar to #6540 

**Current behaviour**: The Kodo Bones always spawn at least one Kodo Apparition, and the ones with a red crystal above them spawn two.
![image](https://user-images.githubusercontent.com/18441882/72279907-73ac6300-3637-11ea-8202-a7f3de9e4c48.png)

**Expected behaviour**: They should sometimes spawn one, never two. As seen in this [vid](https://youtu.be/NcsAToxsJ14). They should not have a crystal.

**Server Revision**: 3236

**Comment by Evolvee** [comment]
how the fuck did this even happen lol, some core change i guess.. it wasnt fucked like this before @Wolffenstein 😩

**Comment by Evolvee** [comment]
@Wolffenstein this is some core shit.... both gameobjects are literally the same template-wise
i hackfixed the "spawning" 2 by setting cooldown on the event (it probably triggered on loot state open + loot state activate [loot])

but the crystal is some 5Head shit

**Comment by drewk8** [comment]
I want to confirm that it's not only happening for the Kodo Bones quest. Shellfish quest in Desolace also (when interacting with the underwater cages), and i believe it's related to intractable quest object in the world.

**Comment by Wolffenstein** [comment]
Fixed in rev 3368.
