### ISSUE TITLE
[NPC] Digmaster Shovelphlange [Spawn]

### ISSUE THREAD

**Issue by The14me** [Atlantiss/NetherwingBugtracker#6553]
Current behaviour: [Digmaster Shovelphlange](https://classic.wowhead.com/npc=7057/digmaster-shovelphlange) is missing.

Expected behaviour: NPC is missing or bad RNG for the dung ID.Spawn points are ok,but npc wasnt there.LF DB recheck.

Rev:3240

**Comment by Tereneckla** [comment]
He's there. Outside of Uldaman obviously.
