### ISSUE TITLE
[Spell] Curse of Tongues, Mind-Numbing Poison and Slow stack with each other.

### ISSUE THREAD

**Issue by Tereneckla** [Atlantiss/NetherwingBugtracker#6554]
[//]: # (Enclose links to things related to the bug using http://wowhead.com or any other TBC database.)
[//]: # (You can use screenshot ingame to visual the issue.)
[//]: # (Write your tickets according to the format:)
[//]: # ([Quest][Azuremyst Isle] Red Snapper - Very Tasty!)
[//]: # ([NPC] Magistrix Erona)
[//]: # ([Spell][Mage] Fireball)
[//]: # ([Npc][Drop] Ghostclaw Lynx)
[//]: # ([Web] Armory doesnt work)
[//]: # (To find server revision type `.server info` command in the game chat.)

**Description**: 
![WoWScrnShot_011520_000349](https://user-images.githubusercontent.com/50233983/72390372-d9c5e280-372a-11ea-93b3-cebc5fe9d995.jpg)
Nothing  5.93 seconds cast time
![WoWScrnShot_011520_000358](https://user-images.githubusercontent.com/50233983/72390375-daf70f80-372a-11ea-97ed-8f909802806a.jpg)
Mind-Numbing  9.49 seconds
![WoWScrnShot_011520_000404](https://user-images.githubusercontent.com/50233983/72390376-db8fa600-372a-11ea-82b7-c6fd5c667374.jpg)
Mind-Numbing + Tongues  15.2 seconds
![WoWScrnShot_011520_000505](https://user-images.githubusercontent.com/50233983/72390380-dcc0d300-372a-11ea-9821-da932787c3e2.jpg)
Mind-Numbing + Tongues + Slow    22.8 seconds

![image](https://user-images.githubusercontent.com/50233983/72390394-ed714900-372a-11ea-9f7a-5a616c7b00c9.png)

**Current behaviour**:
They stack

**Expected behaviour**: 
They don't stack
**Server Revision**: 3228

**Comment by Evolvee** [comment]
you cant test it with gm commands

**Comment by Tereneckla** [comment]
![WoWScrnShot_011520_201833](https://user-images.githubusercontent.com/50233983/72463763-4943dc80-37d4-11ea-9d62-825b909cebaa.jpg)

**Comment by Evolvee** [comment]
@Wolffenstein 🤦‍♂ 👊

**Comment by Evolvee** [comment]
https://youtu.be/PZnYPAirIaY

**Comment by Evolvee** [comment]
this shiit was working since summer 2016 btw

rip nw 2016-2018

**Comment by Evolvee** [comment]
make sure to retest this @Tereneckla 
after rev
![image](https://user-images.githubusercontent.com/1942409/72470597-50bdb280-37e1-11ea-9de2-54a7da5444aa.png)

idk if that was the fix.. wolf a habit of not closing issues -.-
