### ISSUE TITLE
Grizlak Rare casts too powerful of a Renew

### ISSUE THREAD

**Issue by temperrr** [Atlantiss/NetherwingBugtracker#6555]
[//]: # (Enclose links to things related to the bug using http://wowhead.com or any other TBC database.)
[//]: # (You can use screenshot ingame to visual the issue.)
[//]: # (Write your tickets according to the format:)
[//]: # ([Quest][Azuremyst Isle] Red Snapper - Very Tasty!)
[//]: # ([NPC] Magistrix Erona)
[//]: # ([Spell][Mage] Fireball)
[//]: # ([Npc][Drop] Ghostclaw Lynx)
[//]: # ([Web] Armory doesnt work)
[//]: # (To find server revision type `.server info` command in the game chat.)

**Description**: 
Grizlak Rare in Silver Stream Mines in Loch Modam casts a renew that is way too powerful (lv 15 rare that heals himself for 88-95 every 3 sec..)
**Current behaviour**:
It heals for 88-95 every 3 secs. I deal about 30 damage every 3 sec....
**Expected behaviour**: 
The renew should be more in range of the 10-20 range.
https://classic.wowhead.com/npc=1425
**Server Revision**: 3240

**Comment by Evolvee** [comment]
fixed in next rev
