### ISSUE TITLE
Loch Frenzies come out of water sometimes

### ISSUE THREAD

**Issue by temperrr** [Atlantiss/NetherwingBugtracker#6556]
[//]: # (Enclose links to things related to the bug using http://wowhead.com or any other TBC database.)
[//]: # (You can use screenshot ingame to visual the issue.)
[//]: # (Write your tickets according to the format:)
[//]: # ([Quest][Azuremyst Isle] Red Snapper - Very Tasty!)
[//]: # ([NPC] Magistrix Erona)
[//]: # ([Spell][Mage] Fireball)
[//]: # ([Npc][Drop] Ghostclaw Lynx)
[//]: # ([Web] Armory doesnt work)
[//]: # (To find server revision type `.server info` command in the game chat.)

**Description**: 
Loch Frenzies can follow you out of the water. Not always the case... (Stonewroughtdam near the dark iron dwarves ones followed me out of the water)
https://classic.wowhead.com/npc=1193/loch-frenzy
**Current behaviour**:
They come out of the water sometimes
https://imgur.com/a/puREmvx
**Expected behaviour**: 
They should stay in the water, eventually deaggro you.
**Server Revision**: 
3240

**Comment by Evolvee** [comment]
I cant reproduces this, all flags are also correct, could be a map problem instead.

**Comment by Evolvee** [comment]
if someone finds a way to reproduce this (or record)--> reopen
