### ISSUE TITLE
[Item] Idol of the Emerald Queen

### ISSUE THREAD

**Issue by sposobniy** [Atlantiss/NetherwingBugtracker#6557]
http://tbc.cavernoftime.com/item=27886
Describe the bug : Adds a full boost (+88) to every Lifebloom. Not reduced by spell power coefficient .

How it should work :
Healing bonus from this idol should reduce to
https://wowwiki.fandom.com/wiki/Spell_power_coefficient?oldid=1492745
LifebloomHoT : approx. 51.80% (~62.16% with Empowered Rejuvenation)

Affected Empowered Rejuvenation) works correctly- which makes the increase even more powerful.

Info about this :

https://www.wowhead.com/item=27886/idol-of-the-emerald-queen#comments

1)By TheKaz
"Just won this item last night in Shadow Lab. Based on my tests, it seems to add +8-9 to each tick of Lifebloom."

2)By jfowle02 on 2007/02/05 (Patch 2.0.6)
"can confirm the increase of about 7-8 per tick on Lifebloom,"

3)By Anger on 2007/12/11 (Patch 2.3.0)
"This does NOT grant 88 to the HoT-Component of Lifebloom, only 55 (with 4/5 Empowered Rejuvenation and 5/5 Gift of Nature). This is 62.5%. Theoretically you would expect 58.3% (= 7s / 12s) untalented and 74.4% (= 7s / 12s * 1.1 * 1.16) with above mentioned spec. It seems quite clear that the Healing Bonus of this Idol does not benefit from Empowered Rejuvenation at all, but maybe half from Gift of Nature (2 component spell or something...). But since I seem to be doing ~60% of my healing in 2vs2 with Lifebloom (~2/3 from HoT), I will still be using this Idol frequently :)"

also in this comment some tests results
By Anassar (1,195 – 15) on 2007/08/11 (Patch 2.1.3)
"So thats ~20 healing per tick of Lifebloom once you have it stacked up."

**Comment by Tereneckla** [comment]
![image](https://user-images.githubusercontent.com/50233983/73163450-545e0d00-40f0-11ea-9a3f-887338e51663.png)
No Idol, Idol
5/5 Gift of Nature No Idol, Idol

You also see that the final heal is not affected by the 10% healing increase.

![image](https://user-images.githubusercontent.com/50233983/73163797-fa117c00-40f0-11ea-8a6b-6a63fa0ba8b4.png)
5/5 Gift of Nature, 5/5 Empowered Rejuvenation, Idol
Idol does not scale with Empowered Rejuvenation as written in the comments.


![image](https://user-images.githubusercontent.com/50233983/73164039-668c7b00-40f1-11ea-837a-a81b5452350c.png)
Lifebloom with 550 Healing and no talents.
![image](https://user-images.githubusercontent.com/50233983/73164223-cd119900-40f1-11ea-9d8e-3472692f65f3.png)
550 Healing with 5/5 Empowered Rejuvenation.
![image](https://user-images.githubusercontent.com/50233983/73164316-02b68200-40f2-11ea-9bf1-4b891d7c3dc4.png)
You forgot a patch there. 235/550 ≈ 0.42
