### ISSUE TITLE
Hunter Pet

### ISSUE THREAD

**Issue by mah5592mood** [Atlantiss/NetherwingBugtracker#6559]
[//]: # (You can use screenshot ingame to visual the issue.)

**Description**: 
Warp stalkers ability warp doesnt work on enemy targets, while description says it should. tested many times (retame another pet, try use skill manually, lvl cap pet for hit%). it works only against neutrals
**Current behaviour**:

**Expected behaviour**: 

**Server Revision**:

**Comment by mah5592mood** [comment]
ty for respond! respect

**Comment by The14me** [comment]
Rev 3460. It works just fine.
Can be closed.
