### ISSUE TITLE
Clearing the Way credit (not sure if blizzlike)

### ISSUE THREAD

**Issue by ttghnw** [Atlantiss/NetherwingBugtracker#656]
[//]: # (Enclose links to things related to the bug using http://wowhead.com or any other TBC database.)
[//]: # (You can use screenshot ingame to visual the issue.)
[//]: # (Write your tickets according to the format:)
[//]: # ([Quest][Azuremyst Isle] Red Snapper - Very Tasty!)
[//]: # ([NPC] Magistrix Erona)
[//]: # ([Spell][Mage] Fireball)
[//]: # ([Npc][Drop] Ghostclaw Lynx)
[//]: # ([Web] Armory doesnt work)

**Description**: 

**Current behaviour**:
The mobs for "clearing the way" you find on the course of Demolitionist Legoso escort for "ending their world", will not give you any credit if Demolitionist helps. This includes me doing dps to the mob.

**Expected behaviour**: 
Unsure if this is blizzlike, pelase review.

**Server Revision**:

**Comment by Evolvee** [comment]
You need to do atleast 50%+ total dmg to NPC to get a credit if guard helps you. Maybe even more, not sure now.

**Comment by ttghnw** [comment]
Yes that is typically so, however his damage is quite considerable to catch up to and since the quests overlap, I wondered, it's not surprising if it's blizzlike since the kill quest mentions that it is for more than one player and I was solo. Thanks for taking a look.

**Comment by narayagh** [comment]
Agree with @ttghnw - I'm quite sure I did more than 50% damage to several mobs but still didn't get the credit.

**Comment by Tenoutoften** [comment]
Maybe you should be given credit? @Evolvee 
https://github.com/Atlantiss/NetherwingBugtracker/issues/2596#issuecomment-438877264

**Comment by Tenoutoften** [comment]
I went ahead and read some on [[Quest]Ending their world#9759](https://www.wowhead.com/quest=9759/ending-their-world#comments:id=90915) and found this [Wowhead comment](https://www.wowhead.com/quest=9759/ending-their-world#comments:id=90915)
![](https://i.gyazo.com/2d2fbc3cf9f0f5b0f6457d01c784df24.png)

This is a player doing the quest, alone, getting experience and only gives a heads up to "...make sure to get the first hit on the mobs... to get xp and be able to loot"

Doesn't this seem very strange if you are required to deal 50% of the damage?
