### ISSUE TITLE
[Item] Fizzle Brassbolts' Letter (minor)

### ISSUE THREAD

**Issue by tomatosz** [Atlantiss/NetherwingBugtracker#6560]
[//]: # (Enclose links to things related to the bug using http://wowhead.com or any other TBC database.)
[//]: # (You can use screenshot ingame to visual the issue.)
[//]: # (Write your tickets according to the format:)
[//]: # ([Quest][Azuremyst Isle] Red Snapper - Very Tasty!)
[//]: # ([NPC] Magistrix Erona)
[//]: # ([Spell][Mage] Fireball)
[//]: # ([Npc][Drop] Ghostclaw Lynx)
[//]: # ([Web] Armory doesnt work)
[//]: # (To find server revision type `.server info` command in the game chat.)

**Description**: The text in [Fizzle Brassbolts' Letter](https://classic.wowhead.com/item=5827) is missing line breaks, and contains a typo.

**Current behaviour**: No line breaks, and the last instance of "IBG" (on the second page) is spelled "IGB" instead.
![image](https://user-images.githubusercontent.com/18441882/72551443-27f6f500-3895-11ea-87ae-01242822cd08.png)
![image](https://user-images.githubusercontent.com/18441882/72551468-2fb69980-3895-11ea-8a1f-47e77ab0a906.png)

**Expected behaviour**: It should have line breaks as shown in the preview on wowhead. 

**Server Revision**: 3240

**Comment by Evolvee** [comment]
fixed in next rev
