### ISSUE TITLE
[Talent][Paladin] Eye for an Eye procs incorrectly

### ISSUE THREAD

**Issue by 4egito** [Atlantiss/NetherwingBugtracker#6565]
[//]: # (Enclose links to things related to the bug using http://wowhead.com or any other TBC database.)
[//]: # (You can use screenshot ingame to visual the issue.)
[//]: # (Write your tickets according to the format:)
[//]: # ([Quest][Azuremyst Isle] Red Snapper - Very Tasty!)
[//]: # ([NPC] Magistrix Erona)
[//]: # ([Spell][Mage] Fireball)
[//]: # ([Npc][Drop] Ghostclaw Lynx)
[//]: # ([Web] Armory doesnt work)
[//]: # (To find server revision type `.server info` command in the game chat.)

**Current behaviour**:
![WoWScrnShot_011820_013928](https://user-images.githubusercontent.com/52432938/72654611-f6ffe880-3998-11ea-9b16-807f07345140.jpg)
As u see on the screenshot i'm using rank 1 Moonfire which is not even a crit but it returns 380 damage to me...
**Expected behaviour**: 
All spell criticals against you cause 30% of the damage taken to the caster as well.  The damage caused by Eye for an Eye will not exceed 50% of the Paladin's total health.
**Server Revision**: 
3240

**Comment by Tereneckla** [comment]
Eye for an Eye does scale with your spelldamage currently.
However the the damage return on "non-crit" is intended.
![image](https://user-images.githubusercontent.com/50233983/73315489-87a7b580-4230-11ea-8e0b-5ba25c9ad43d.png)
https://classic.wowhead.com/forums&topic=60153

**Comment by 4egito** [comment]
![WoWScrnShot_052520_010409](https://user-images.githubusercontent.com/52432938/83308180-f14fc480-a20e-11ea-891f-c0f1f85c1512.jpg) 4 months later...

**Comment by Wolffenstein** [comment]
Crit part is correct as @Tereneckla wrote.

Damage fixed in rev 3590.
