### ISSUE TITLE
[NPC] Season 4 PvP vendor issues

### ISSUE THREAD

**Issue by Manaci** [Atlantiss/NetherwingBugtracker#6566]
**1st issue**
The current "Sergeant Thunderhorn" in Hall of Legends and the current "Captain O'Neal" in Champion's Hall are still selling the old useless blue lvl 70 High Warlord weapons at higher honor prices than Merciless weapons. So [Sergeant Thunderhorn](https://db.excalibur.ws/?npc=26396) and [Captain O'Neal](https://db.excalibur.ws/?npc=26394) should be selling Merciless weapons for honor instead. (as seen on the linked NPCs)
[Some Webarchive proof (scroll down)](http://web.archive.org/web/20090113091324/http://wow.allakhazam.com/db/item.html?witem=33313)

**2nd Issue**
The Current "Doris Volanthius" in Hall of Legends and "Lieutenant Tristia" in Champion's Hall are only selling the Vindicator offpieces, Vindicator rings and trinkets right now. [Doris Volanthius](https://db.excalibur.ws/?npc=26398) and [Lieutenant Tristia](https://db.excalibur.ws/?npc=26395) should be selling all the Guardian offpieces, Guardian rings and necks + Vindicator necks along with their current Vindicator offpieces, Vindicator rings and trinkets. 
[Some Webarchive proof (scroll down)](http://web.archive.org/web/20080803102144/http://wow.allakhazam.com/db/item.html?witem=37927)

**3rd issue**
The current Lady Palanseer in Hall of Legends and Captain Dirgehammer in Champion's Hall are selling the wrong items, namely Guardian offpieces, Guardian rings and necks. [Lady Palanseer](https://db.excalibur.ws/?npc=26397) and [Captain Dirgehammer](https://db.excalibur.ws/?npc=26393) should be selling Merciless armor only
[Some Webarchive proof (scroll down)](http://web.archive.org/web/20081224165220/http://wow.allakhazam.com/db/item.html?witem=32004)

When this is all fixed, [Krixel Pinchwhistle](https://db.excalibur.ws/?npc=23396) in Area 52 should be removed as he is only supposed to be selling Merciless items for arena points, as they are sold in Hall of Legends and Champion's Hall for honor points now.
[Some Webarchive proof (scroll down)](http://web.archive.org/web/20080621183249/http://wow.allakhazam.com/db/mob.html?wmob=23396)

**Server Revision**: 
3240

**Comment by Godmatik** [comment]
Issue 1 - they are selling Merciless weapons
Issue 2 - they are selling all the missing pieces referenced
Issue 3 - they are selling merciless pieces

I am guessing this was all fixed a while ago and this issue was never closed ... so ... closing
