### ISSUE TITLE
Magespell ''Icy Veins'' - Krallka

### ISSUE THREAD

**Issue by Krallka** [Atlantiss/NetherwingBugtracker#6568]
[//]: # (Enclose links to things related to the bug using http://wowhead.com or any other TBC database.)
[//]: # (You can use screenshot ingame to visual the issue.)
[//]: # (Write your tickets according to the format:)
[//]: # ([Quest][Azuremyst Isle] Red Snapper - Very Tasty!)
[//]: # ([NPC] Magistrix Erona)
[//]: # ([Spell][Mage] Fireball)
[//]: # ([Npc][Drop] Ghostclaw Lynx)
[//]: # ([Web] Armory doesnt work)
[//]: # (To find server revision type `.server info` command in the game chat.)

**Description**: 
Hello GM,
I'd like to announce a little problem with a mage spell ''Icy Veins''. When I activate it there's no casting speed increase moreover it deactivates other cast time shortcut spells such as heroism. Even after retalent this problem still remains. It seems other mages don't have this problem. Is it possible to fix it somehow ? Nick of the character is: Krallka. 
Thank you for your time. 

**Current behaviour**:
Spell ''Icy Veins'' does not increase casting speed by 20% but it does give me 100% chance to avoid interuption while being attacked
**Expected behaviour**: 
Spell ''Icy Veins'' should increase casting speed by 20% and gives 100% chance to avoid interuption while being attacked.
**Server Revision**:

**Comment by Evolvee** [comment]
should be fixed in next rev according to changelog
