### ISSUE TITLE
Reliquary of Souls - Deaden

### ISSUE THREAD

**Issue by Firroth** [Atlantiss/NetherwingBugtracker#6569]
First things first, I congratulate to all people who knew of this bug and didn't bother to report it in "at least 3months++ time" so they could easily farm this boss, like some loot pinata. You guys are worthless stupid bug users, I applaud you.

I got this info recently, since it was going around between guilds, so I went and checked it, since from what I see you lazy assess only care about loot, rather than good scripted content.

<end of rant>

**Current behaviour**:
RoS 2nd phase, you reflect deaden and you DON'T NEED to reflect it ever again, since retri paladin's seal can "refresh it's duration" so deaden can be mantained for ENTIRE PHASE 2.

**Expected behaviour**: 
Deaden shouldn't be able to be refreshed by any of the spells.

**Server Revision**: 
3241

**Comment by Wolffenstein** [comment]
Which Seal exactly?

**Comment by Wolffenstein** [comment]
Fixed in rev 3243.
