### ISSUE TITLE
[Npc][Darkshore] Rabid Thistle Bear stuck in Tree.

### ISSUE THREAD

**Issue by toki90** [Atlantiss/NetherwingBugtracker#657]
**Description**: 
Bugged mob stuck in a tree in northern Darkshore near the Cliffspring River. (https://imgur.com/SWIU8BG)

**Current behaviour**:
Bear is stuck in tree. Will attack when youre within range, but doesnt follow and instead resets. Hes stuck in tree right now, respawned in same spot. Im here but im gonna dl coords to give you the exact location. Or come see me ingame again :)

**Expected behaviour**: 
Shouldnt be stuck.

**Server Revision**:

**Comment by Emityx** [comment]
Entry 2164, Id 43

**Comment by aresbrutus** [comment]
Corrected in one of the next updates.
