### ISSUE TITLE
[Hunter] Snake trap deadly poison dont tick after the snakes dies

### ISSUE THREAD

**Issue by 4egito** [Atlantiss/NetherwingBugtracker#6570]
[//]: # (Enclose links to things related to the bug using http://wowhead.com or any other TBC database.)
[//]: # (You can use screenshot ingame to visual the issue.)
[//]: # (Write your tickets according to the format:)
[//]: # ([Quest][Azuremyst Isle] Red Snapper - Very Tasty!)
[//]: # ([NPC] Magistrix Erona)
[//]: # ([Spell][Mage] Fireball)
[//]: # ([Npc][Drop] Ghostclaw Lynx)
[//]: # ([Web] Armory doesnt work)
[//]: # (To find server revision type `.server info` command in the game chat.)

**Description**: 
Deadly poison from snake trap dont does damage after the snakes dies
**Current behaviour**:
![image](https://user-images.githubusercontent.com/52432938/72757395-81825b00-3bd8-11ea-99b7-36fd80132efb.png)

**Expected behaviour**: 
Deadly poison from snake trap should do damage till the duration expires
**Server Revision**: 
3241

**Comment by 4egito** [comment]
https://drive.google.com/open?id=1QaHgLATDANUJIFUf5AB04oHLFfTV7F0V There is a video for more info

**Comment by Wolffenstein** [comment]
Fixed in rev 3407.
