### ISSUE TITLE
[Spell][rogue] Cloak of Shadows and Vanish issues vs certain magical attacks and effects

### ISSUE THREAD

**Issue by Shanrolol** [Atlantiss/NetherwingBugtracker#6572]
[//]: # (Enclose links to things related to the bug using http://wowhead.com or any other TBC database.)
[//]: # (You can use screenshot ingame to visual the issue.)
[//]: # (Write your tickets according to the format:)
[//]: # ([Quest][Azuremyst Isle] Red Snapper - Very Tasty!)
[//]: # ([NPC] Magistrix Erona)
[//]: # ([Spell][Mage] Fireball)
[//]: # ([Npc][Drop] Ghostclaw Lynx)
[//]: # ([Web] Armory doesnt work)
[//]: # (To find server revision type `.server info` command in the game chat.)

**Description**: 
You cannot acquire proper Immunity using a Cloak of Shadows ability, or a properly timed Vanish, atleast for mages Pyroblast's damage and its DoT debuff.
**Current behaviour**:
Today, in several arena matches I played with a rogue, my rogue teammate was using CoS and Vanish, exactly timing it to catch the Presence of Mind Pyroblast from a mage, and every time he did those, both the spell damage and DoT effect got through, when they were supposed to get immuned. Yes CoS was on him just before the Pyro hit, and with Vanish, he had both Vanish and Stealth buffs, meaning he did press it on time, but the pyroblast DoT and its damage still went through, and with its first tick he got knocked out of stealth. Additionally, Ive seen a Druid apply a faerie fire on him, and mage a nova, when he had CoS on him for more than half of its duration, which makes me think those Pyro's hitting him on CoS werent all 10% flukes, something must be wrong with the Cloak itself.
**Expected behaviour**: 
CoS is supposed to provide a nigh-complete immunity to spells, not letting them through THAT consistently, Also, a well timed Vanish is supposed to completely absorb any kind of a spell or an attack, that hits you right as you disappear.
**Server Revision**: 
3243

**Comment by Godmatik** [comment]
Rev 4016.

Still an issue - Cloak of Shadows does not remove either pyroblast DOT or Ignite debuff

**Comment by Godmatik** [comment]
Fixed in upcoming new aura branch update
