### ISSUE TITLE
[Raid][SSC][TK] T5 patterns drop rate too low

### ISSUE THREAD

**Issue by raethkcj** [Atlantiss/NetherwingBugtracker#6573]
[//]: # (Enclose links to things related to the bug using http://wowhead.com or any other TBC database.)
[//]: # (You can use screenshot ingame to visual the issue.)
[//]: # (Write your tickets according to the format:)
[//]: # ([Quest][Azuremyst Isle] Red Snapper - Very Tasty!)
[//]: # ([NPC] Magistrix Erona)
[//]: # ([Spell][Mage] Fireball)
[//]: # ([Npc][Drop] Ghostclaw Lynx)
[//]: # ([Web] Armory doesnt work)
[//]: # (To find server revision type `.server info` command in the game chat.)

**Description**: 
Many guilds are unable to obtain T5 patterns after weeks of raiding. They should have a chance to drop from all trash, but currently seem to only rarely drop from bosses.

![image](https://user-images.githubusercontent.com/7716908/72922645-05406280-3d13-11ea-9194-6d91f36cc67e.png)
![image](https://user-images.githubusercontent.com/7716908/72922664-11c4bb00-3d13-11ea-8f96-2d1a1b336b67.png)
![image](https://user-images.githubusercontent.com/7716908/72922700-22753100-3d13-11ea-90ed-2b6e01bdda16.png)
![image](https://user-images.githubusercontent.com/7716908/72922752-3b7de200-3d13-11ea-9626-c0affd9e129e.png)
![image](https://user-images.githubusercontent.com/7716908/72922763-42a4f000-3d13-11ea-916c-6dd9307d5242.png)
![image](https://user-images.githubusercontent.com/7716908/72922821-5fd9be80-3d13-11ea-8b6c-72665ef1b766.png)

**Server Revision**: 
3243

**Comment by DaedalusMachina007** [comment]
Droprates for Netherwing should be public IMHO, especially in some kind of dedicated database site if they are not 'blizzlike' droprates.

That said, it really wouldn't hurt to double the existing droprates for stuff like this so people can get the things they need to do the content that is being released.  SWP won't be much use if people are stuck doing dailies and nothing else.

**Comment by Evolvee** [comment]
this report provides no proof whatsoever... 0 data, 0 link, nothing... just ppl saying drop is low without saying how much it should be

its like saying "gm fix bug"

**Comment by raethkcj** [comment]
http://web.archive.org/web/20070917094323/http://wow.allakhazam.com/db/item.html?witem=30280
http://web.archive.org/web/20070920132303/http://wow.allakhazam.com/db/item.html?witem=30281
http://web.archive.org/web/20070921220942/http://wow.allakhazam.com/db/item.html?witem=30282
http://web.archive.org/web/20071102062421/http://wow.allakhazam.com/db/item.html?witem=30283
http://web.archive.org/web/20071102225242/http://wow.allakhazam.com/db/item.html?witem=30301
http://web.archive.org/web/20071102225242/http://wow.allakhazam.com/db/item.html?witem=30302
http://web.archive.org/web/20071102225242/http://wow.allakhazam.com/db/item.html?witem=30303
http://web.archive.org/web/20071102225242/http://wow.allakhazam.com/db/item.html?witem=30304
http://web.archive.org/web/20071102225242/http://wow.allakhazam.com/db/item.html?witem=30305
http://web.archive.org/web/20071102225242/http://wow.allakhazam.com/db/item.html?witem=30306
http://web.archive.org/web/20071102225242/http://wow.allakhazam.com/db/item.html?witem=30307
http://web.archive.org/web/20071102225242/http://wow.allakhazam.com/db/item.html?witem=30308
http://web.archive.org/web/20071102225242/http://wow.allakhazam.com/db/item.html?witem=30321
http://web.archive.org/web/20071102225242/http://wow.allakhazam.com/db/item.html?witem=30322
http://web.archive.org/web/20071102225242/http://wow.allakhazam.com/db/item.html?witem=30323
http://web.archive.org/web/20071102225242/http://wow.allakhazam.com/db/item.html?witem=30324

These suggest a drop rate of about 0.5% on trash and 2% on bosses. 

With 14 patterns and a 0.5% drop rate, there should be approximately 1-(99.5)^14 = 6.8% chance per trash mob to drop a pattern of some type, which is not the case right now.

**Comment by raethkcj** [comment]
Thottbot links for the same patterns, showing mostly the same drop rate on trash (~0.5%) but often higher drop rates on bosses (~5%)

http://web.archive.org/web/20080108090121/http://thottbot.com/i30280
http://web.archive.org/web/20071016053326/http://thottbot.com/i30281
http://web.archive.org/web/20071127084346/http://thottbot.com/i30282
http://web.archive.org/web/20071201064445/http://thottbot.com/i30283
http://web.archive.org/web/20080109091301/http://thottbot.com/i30301
http://web.archive.org/web/20080105001454/http://thottbot.com/i30302
http://web.archive.org/web/20080114020751/http://thottbot.com/i30303
http://web.archive.org/web/20071126123419/http://thottbot.com/i30304
http://web.archive.org/web/20080113170445/http://thottbot.com/i30305
http://web.archive.org/web/20080210000906/http://thottbot.com/i30306
http://web.archive.org/web/20080119180412/http://thottbot.com/i30307
http://web.archive.org/web/20080112090022/http://thottbot.com/i30321
http://web.archive.org/web/20080113140312/http://thottbot.com/i30322
http://web.archive.org/web/20080109184854/http://thottbot.com/i30323
http://web.archive.org/web/20080119041447/http://thottbot.com/i30324

**Comment by BamboozleNW** [comment]
> this report provides no proof whatsoever... 0 data, 0 link, nothing... just ppl saying drop is low without saying how much it should be
> 
> its like saying "gm fix bug"
Is this really how NW service works? Multiple guilds saying the same thing with no "proof" . You'd think with that many people, you guys would just look into it. My guild was in T5 months, I got 2 patterns. Literally. You need reports to see that's not how it should be? lol. Cmon, the service on this server is something else....You'd think with your pop dwindling you would want to make the people who still dedicate hours of their time on the server happy. But hey, what do I know..

**Comment by Evolvee** [comment]
i did look into it, the retail has even lower % drop than we do have now so wtf do u expect me to do

i did my research and didnt find anything incorrect, its up to you to prove me wrong now...

**Comment by Evolvee** [comment]
2.1. drops are 2% trash 8% bosses right now which is way more than what you came up with above ^^ either provide different data or fuck off with the "service on this server" entitled attitude.

**Comment by Evolvee** [comment]
I will double check if all the npcs are added to the global template but thats pretty much all what I can do with it rn without making some funserver/stock shit % drop values just to satisfy your needs.

**Comment by Evolvee** [comment]
E: seems like there might be a problem with the loot system to begin with, nothing to do with % drop chance (so after that is resolved, we might want to take the drop even down)

**Comment by Evolvee** [comment]
ok so, check again after the next crash/restart pls
