### ISSUE TITLE
[PVP][BATTLEGROUNDS]------ NEED HOTFIX --------- No working textures in BGs.

### ISSUE THREAD

**Issue by vexladdie** [Atlantiss/NetherwingBugtracker#6574]
Hello,
there are not working textures in BGs. There is not so much to explain - you can charge enemy behind an tree, you can cast heals behind trees - everything. There is working i think 30% of textures.

This behaviour is worst what i saw at any server.

For example: in WSG when you are staying at graveyard(closer to cliff) and enemy is down, not have los on you you are getting dmg! This problem is everywhere on this server (BGs).

If this server, wants to be an atleast little bit PVP, this must works.

Is there any posibility to get it working please?

**Server Revision**:  3243

**Comment by DaedalusMachina007** [comment]
I believe @vexladdie is referring to 'geodata' which is specific map data that determines line of sight, pathfinding, and other situations that involve elevation/blockage between entities (players/mobs) within a specific area.

**Comment by vexladdie** [comment]
@DaedalusMachina007  yes, thats it :))

**Comment by Evolvee** [comment]
m2 models shouldnt not block los

try it on retail/classic yourself

if you mean some other issue, reopen and provide something more specific (video/screenshot)
