### ISSUE TITLE
[Core] Swing timer resets when disabled

### ISSUE THREAD

**Issue by Easyfraggy** [Atlantiss/NetherwingBugtracker#6577]
**Description**: 

**Current behaviour**:'
Atm Swing timer resets whenever you are CC'd.

**Expected behaviour**: 
Swing timer should continue while CC'd and not reset at all.

**Server Revision**:

**Comment by Godmatik** [comment]
Rev 4018 - no longer an issue
Swing timer properly continues while CCed, and a melee attack occurs right after exiting it.
