### ISSUE TITLE
[ARENA/PVP] Warlock "Spell Lock"-Cast -> School Lock not working

### ISSUE THREAD

**Issue by Tweet1337** [Atlantiss/NetherwingBugtracker#6579]
Warlock-Pet-Spell "Spell Lock" atm only silences for 3 seconds, but does not use his School-Lock-effect (f.e. when using Spell Lock while a paladin is casting Holy Light he should be locked out of Holy-Spells for 6 seconds)

**Spell:**
[https://tbc-twinhead.twinstar.cz/?spell=19647](url)
**Tooltip-Text:**
_Silences the enemy for 3sec. If used on a casting target, it will counter the enemy's spellcast, preventing any spell from that school of magic from being cast for 6sec._

Server Revision:
3243

**Comment by Wolffenstein** [comment]
Fixed in rev 3245.
