### ISSUE TITLE
Daily quests are using repeatable non-daily indicators/icons

### ISSUE THREAD

**Issue by Balanarr** [Atlantiss/NetherwingBugtracker#6580]
**Description**: 
Complete a daily quest for the first time
Return to the npc after daily reset

**Current behaviour**:
Daily quest is no longer displayed as a blue exclamation mark above the quest giver and is also not displayed on the minimap.
Upon completion, it is not displayed as a yellow question mark and also not displayed on the minimap.
In both cases the non-daily repeatable blue question mark is displayed (the one used mostly for repeatable turn-ins

**Expected behaviour**: 
Daily quests not picked up are displayed as a blue exclamation mark above npc's and on minimap (after reset if they have been completed once)
Daily quests picked up and with objectives not completed are displayed as a grey question mark above npc
Daily quests picked and with objectives finished are diplayed as a yellow question mark above npcs and on minimap
**Server Revision**:

**Comment by Godmatik** [comment]
This must have all been fixed at some point and this old issue was never closed out.

Daily quests are properly showing as blue exclamation mark when not picked up, gray question mark when not completed, and yellow question mark when completed. They are also showing properly on the minimap
