### ISSUE TITLE
[Missing][NPC]Ghok Bashguud

### ISSUE THREAD

**Issue by Healweed** [Atlantiss/NetherwingBugtracker#6581]
**Description**: 
Confirmed with @Tereneckla . Rare on LBRS Ghok Bashguud is missing
ID: 9718

**Current behaviour**:
NPC ID Doesn't exist on Database

**Expected behaviour**: 
Should be existent and located in LBRS

**Server Revision**: 
3243

**Comment by Evolvee** [comment]
fixed in next rev
