### ISSUE TITLE
[Shaman] Far Sight removing summoned totems

### ISSUE THREAD

**Issue by Healweed** [Atlantiss/NetherwingBugtracker#6584]
**Description**: 
Far Sight is removing the totems that the shaman summoned in prior. Summoning all four totems (doesn't matter which totems it is), and then using Far Sight( scout tool) is removing the summoned totems( which shouldn't).

The removal only happens when you use Far Sight over 20yrds.

**Current behaviour**:

   Currently as of now, Far Sight is removing summoned totems when used on a distance of 20 yrds and above

**Expected behaviour**: 
Shouldn't remove your summoned totems, regardless of the distance between totems and Far Sight location.

**Server Revision**: 
3243

**Comment by GMThunderan** [comment]
Could confirm the issue on PTR (r3228).
Happens only if you "farsight" out of visibility range of the totems.
[Video of my testing.](https://streamable.com/llo3h)

_inb4: character name is completely random._

**Comment by The14me** [comment]
Confirmed 2.0.3

**Comment by Healweed** [comment]
> Confirmed 2.0.3

This was also bugged since 2,0,3 from Netherwing server :thinking:

**Comment by The14me** [comment]
Yea...somehow i put the patch not the Rev.Still bugged at 3441

**Comment by Wolffenstein** [comment]
Fixed in rev 3443.
