### ISSUE TITLE
[Spells]Fear effects - Fearing a stunned target causes the target to be displayed running in different directions than it's actually running

### ISSUE THREAD

**Issue by Balanarr** [Atlantiss/NetherwingBugtracker#6585]
**Description**: Fearing a stunned target causes the target to be displayed running in different directions than it's actually running

Stun a target and then fear it while it is stunned. Easy to reproduce as a FG warlock, start casting fear and use felguard's intercept before the cast is finished.

**Current behaviour**: After the stun is over, the target will start running but the directions it runs that are displayed by the client are not the directions it actually runs (pets follow it's "true" direction and continues to attack it, even though it displays as attacking nothing)
When Fear ends, the target is shifted to it's actual position.
May also occur when the target is unable to move like rooted and not only stunned (not sure about this)

**Expected behaviour**: The directions the feared target runs are accurately shown by the client

**Server Revision**: 3243

**Comment by Tereneckla** [comment]
Not happening on PTR.
3234 changed that maybe
[Core/Protocol]:
- Speed change packet will no longer be broadcasted if the player movement status changed to server controlled in the meantime. This should help with Fear position desynchronization

**Comment by Drainlock** [comment]
https://www.twitch.tv/videos/545759204
Fearing pala > warrior intercept > when 3sec stun ends Pala teleporting to location what I was facing (maybe just a coincidence) > after fear ends Pala teleporting to location where he was before.
serv rev 3248
