### ISSUE TITLE
[NPC] High Astromancer Solarians melee attack is too high again?

### ISSUE THREAD

**Issue by Easyfraggy** [Atlantiss/NetherwingBugtracker#6586]
[//]: # (Enclose links to things related to the bug using http://wowhead.com or any other TBC database.)
[//]: # (You can use screenshot ingame to visual the issue.)
[//]: # (Write your tickets according to the format:)
[//]: # ([Quest][Azuremyst Isle] Red Snapper - Very Tasty!)
[//]: # ([NPC] Magistrix Erona)
[//]: # ([Spell][Mage] Fireball)
[//]: # ([Npc][Drop] Ghostclaw Lynx)
[//]: # ([Web] Armory doesnt work)
[//]: # (To find server revision type `.server info` command in the game chat.)

**Description**: 

**Current behaviour**:
Hits for 10-15k arcane damage in last phase. He hits for the same amount in normal phase but that damage is reduced by armor which makes it fine. But in void form he does arcane damage which is not reduced and makes it way too high.

**Expected behaviour**: 
Should hit for less in void form. 20-30% nerf or so.

**Server Revision**: 3228+

**Comment by Tereneckla** [comment]
Same experience. Our bear suddenly got bitchslapped.

![image](https://user-images.githubusercontent.com/50233983/73287306-5cee3a80-41f9-11ea-923c-b080369691d8.png)

**Comment by Easyfraggy** [comment]
This was fixed looong time ago - not sure why its suddenly back.

**Comment by raethkcj** [comment]
Sadly don't have a combat log but our bear was crushed today for 26k arcane

**Comment by Wolffenstein** [comment]
Fixed in rev 3387.
