### ISSUE TITLE
[Loot][Black Temple] NPCS currently not dropping epic BT loot.

### ISSUE THREAD

**Issue by Easyfraggy** [Atlantiss/NetherwingBugtracker#6587]
[//]: # (Enclose links to things related to the bug using http://wowhead.com or any other TBC database.)
[//]: # (You can use screenshot ingame to visual the issue.)
[//]: # (Write your tickets according to the format:)
[//]: # ([Quest][Azuremyst Isle] Red Snapper - Very Tasty!)
[//]: # ([NPC] Magistrix Erona)
[//]: # ([Spell][Mage] Fireball)
[//]: # ([Npc][Drop] Ghostclaw Lynx)
[//]: # ([Web] Armory doesnt work)
[//]: # (To find server revision type `.server info` command in the game chat.)

**Description**: 

**Expected behaviour**: 

Should all be part of the Black Temple epic trash loot - gems/epics/recipes

Drops nothing at all:
22847
22844
22846
22845
22849
23374
22962

Drops normal world drop trash items already just not BT Epics etc)
22946

**Server Revision**: 3228

**Comment by Manaci** [comment]
Think this was done intentionally to discourage farming those packs with like 5 people.

**Comment by Evolvee** [comment]
22962 hello?

**Comment by Evolvee** [comment]
fixd
