### ISSUE TITLE
[Quest][Stonetalon Mountains] Protect Kaya

### ISSUE THREAD

**Issue by totaemoeggerli** [Atlantiss/NetherwingBugtracker#659]
[//]: # (Enclose links to things related to the bug using http://wowhead.com or any other TBC database.)
[//]: # (You can use screenshot ingame to visual the issue.)
[//]: # (Write your tickets according to the format:)
[//]: # ([Quest][Azuremyst Isle] Red Snapper - Very Tasty!)
[//]: # ([NPC] Magistrix Erona)
[//]: # ([Spell][Mage] Fireball)
[//]: # ([Npc][Drop] Ghostclaw Lynx)
[//]: # ([Web] Armory doesnt work)

**Description**: 
NPC is missing assist flag
https://www.wowhead.com/quest=6523/protect-kaya

**Current behaviour**:
NPC doesn't engage mobs that are in combat with the player.
https://gfycat.com/QuarterlyYawningBactrian

**Expected behaviour**: 
NPC should engage mobs that are in combat with the palyer.

**Server Revision**: 
2060

**Comment by Jezofine** [comment]
She engaged in combat for me 1-2 days ago.

**Comment by Easyfraggy** [comment]
https://github.com/Atlantiss/NetherwingBugtracker/issues/783

**Comment by totaemoeggerli** [comment]
worked fine on alt
