### ISSUE TITLE
[Item]Minor Recombobulator for horde

### ISSUE THREAD

**Issue by phrenorrhagia** [Atlantiss/NetherwingBugtracker#6590]
[//]: # (Enclose links to things related to the bug using http://wowhead.com or any other TBC database.)
[//]: # (You can use screenshot ingame to visual the issue.)
[//]: # (Write your tickets according to the format:)
[//]: # ([Quest][Azuremyst Isle] Red Snapper - Very Tasty!)
[//]: # ([NPC] Magistrix Erona)
[//]: # ([Spell][Mage] Fireball)
[//]: # ([Npc][Drop] Ghostclaw Lynx)
[//]: # ([Web] Armory doesnt work)
[//]: # (To find server revision type `.server info` command in the game chat.)

**Description**: 
The recipe https://tbc-twinhead.twinstar.cz/?item=14639 for Minor Recombobulator should be sold  by Gagsprocket in Ratchet since BC (he does not sell it in vanilla). It is a 1 in stock item, the same as the Schematic: Green Firework (https://tbc-twinhead.twinstar.cz/?item=18648) that Gagsprocket currently sells, but does not seem to sell the Schematic: Minor Recombobulator at all. If the horde cannot buy it in Ratchet, it makes this schematic alliance only. 
**Current behaviour**:
Gagsprocket does not sell the Schematic: Minor Recombobulator
**Expected behaviour**: 
Gagsprocket should sell the Schematic: Minor Recombobulator
**Server Revision**:

**Comment by Tereneckla** [comment]
It's there
![image](https://user-images.githubusercontent.com/50233983/73357047-ebb39380-429b-11ea-9491-00c4c2e73abb.png)
