### ISSUE TITLE
[Raid][Spell][Zul'Aman] Tranquilizing Poison does not put you to sleep.

### ISSUE THREAD

**Issue by Tereneckla** [Atlantiss/NetherwingBugtracker#6591]
[//]: # (Enclose links to things related to the bug using http://wowhead.com or any other TBC database.)
[//]: # (You can use screenshot ingame to visual the issue.)
[//]: # (Write your tickets according to the format:)
[//]: # ([Quest][Azuremyst Isle] Red Snapper - Very Tasty!)
[//]: # ([NPC] Magistrix Erona)
[//]: # ([Spell][Mage] Fireball)
[//]: # ([Npc][Drop] Ghostclaw Lynx)
[//]: # ([Web] Armory doesnt work)
[//]: # (To find server revision type `.server info` command in the game chat.)

**Description**: https://www.youtube.com/watch?v=4qR_QmGIxbc
![image](https://user-images.githubusercontent.com/50233983/73396306-62bf4b00-42e1-11ea-94b0-b8680467e803.png)

Spell 43364
Sadly I could not find information which sleep or how long it should be. The only behavior I can find is the wowhead comment.
https://www.wowhead.com/npc=24065/amanishi-handler#comments

**Current behaviour**: No sleep after 8 seconds.

**Expected behaviour**: Puts you to sleep after the 8 seconds.

**Server Revision**: 3228 (and whatever current live server is)

**Comment by Wolffenstein** [comment]
Should trigger 41396

**Comment by Wolffenstein** [comment]
Fixed in rev 3425.
