### ISSUE TITLE
[Raid] Lady Malande disappeared

### ISSUE THREAD

**Issue by Tereneckla** [Atlantiss/NetherwingBugtracker#6592]
[//]: # (Enclose links to things related to the bug using http://wowhead.com or any other TBC database.)
[//]: # (You can use screenshot ingame to visual the issue.)
[//]: # (Write your tickets according to the format:)
[//]: # ([Quest][Azuremyst Isle] Red Snapper - Very Tasty!)
[//]: # ([NPC] Magistrix Erona)
[//]: # ([Spell][Mage] Fireball)
[//]: # ([Npc][Drop] Ghostclaw Lynx)
[//]: # ([Web] Armory doesnt work)
[//]: # (To find server revision type `.server info` command in the game chat.)

**Description**: https://clips.twitch.tv/PiercingVastToadOSfrog

**Current behaviour**: Fell into the ground.

**Expected behaviour**: No falling into the ground.

**Server Revision**: 3243

**Comment by Evolvee** [comment]
OMEGALUL

**Comment by Tereneckla** [comment]
https://www.youtube.com/watch?v=jHt1N1w5S4

**Comment by The14me** [comment]
Rev.3478 can't reproduce it...but must be still like that.

**Comment by Godmatik** [comment]
Have not once seen this happen ever on Netherwing - nor heard of it ever happening.

Hopefully was fixed or just an incredibly rare bug that can not be reproduced easily.
