### ISSUE TITLE
[Spell][Paladin] Greater Blessing of Kings has to be relearned after every respec

### ISSUE THREAD

**Issue by hederob** [Atlantiss/NetherwingBugtracker#6593]
[Spell][Paladin] Greater Blessing of Kings has to be relearned after every respec

**Description**: 
Greater Blessing of Kings is required to be trained after every re-spec.
**Current behaviour**:
You're required to relearn Greater Blessing of Kings even after the first time you spec into Blessing of Kings.
**Expected behaviour**: 
Respeccing should require you to not re-learn Greater Blessing of Kings a second time when you talent into Blessing of Kings.
**Server Revision**: 
3243

**Comment by veekk** [comment]
can confirm, pretty annoying, afaik same stuff with spirit buff, and everything fine with sanctuary

**Comment by Tereneckla** [comment]
Duplicate of #5646
