### ISSUE TITLE
[Core] Almost everything respawns on server restart/crash

### ISSUE THREAD

**Issue by Tereneckla** [Atlantiss/NetherwingBugtracker#6597]
[//]: # (Enclose links to things related to the bug using http://wowhead.com or any other TBC database.)
[//]: # (You can use screenshot ingame to visual the issue.)
[//]: # (Write your tickets according to the format:)
[//]: # ([Quest][Azuremyst Isle] Red Snapper - Very Tasty!)
[//]: # ([NPC] Magistrix Erona)
[//]: # ([Spell][Mage] Fireball)
[//]: # ([Npc][Drop] Ghostclaw Lynx)
[//]: # ([Web] Armory doesnt work)
[//]: # (To find server revision type `.server info` command in the game chat.)

**Description**: Fish schools, rare mobs, limited vendor items all respawn on server crash/restart

**Current behaviour**: ^

**Expected behaviour**:  They should not I guess.

**Server Revision**: 3247

**Comment by Evolvee** [comment]
.................... nw in a nutshell
everything keeps falling apart

**Comment by Tereneckla** [comment]
Not 100% on Outland rares respawning, but old world ones definitely do.
