### ISSUE TITLE
Gates of Ironforge Graveyard

### ISSUE THREAD

**Issue by Scylla420** [Atlantiss/NetherwingBugtracker#66]
The Spirit Healer at the Gates of Ironforge Graveyard is currently in the wrong location, and you spawn with improper orientation when you release there.

[Spirit Healer location + Character Spawn location/orientation on retail](https://i.imgur.com/RQETBLp.jpg)

[Netherwing](https://i.imgur.com/CowUZDu.jpg)

As you can see, the spirit healer should be closer to Ironforge itself instead of being located at the end of the path, and it should be turned the other way.  The actual place your character spawns seems to be close to correct but you should be spawned facing the spirit healer.

**Comment by aresbrutus** [comment]
Can you provide the video link please?

**Comment by Scylla420** [comment]
> Can you provide the video link please?

[Here's another vid that shows the GY in higher quality](https://youtu.be/yCGxxj2A5so?t=35s)

**Comment by Evolvee** [comment]
fixed in next hotfix rev

**Comment by Evolvee** [comment]
I cant change the orientation of the player btw. Its probably taken from the orientation the player had when he died.

**Comment by Tenoutoften** [comment]
https://www.youtube.com/watch?v=wRtEGQax-CU
Video of Highlord Kruul invading Stormwind 11th of January
