### ISSUE TITLE
[NPC] missing assist flag for escort NPC

### ISSUE THREAD

**Issue by totaemoeggerli** [Atlantiss/NetherwingBugtracker#660]
[//]: # (Enclose links to things related to the bug using http://wowhead.com or any other TBC database.)
[//]: # (You can use screenshot ingame to visual the issue.)
[//]: # (Write your tickets according to the format:)
[//]: # ([Quest][Azuremyst Isle] Red Snapper - Very Tasty!)
[//]: # ([NPC] Magistrix Erona)
[//]: # ([Spell][Mage] Fireball)
[//]: # ([Npc][Drop] Ghostclaw Lynx)
[//]: # ([Web] Armory doesnt work)

**Description**: 
Several escort quest NPCs are not engaging mobs that are in combat with the player.
https://github.com/Atlantiss/NetherwingBugtracker/issues/659
https://github.com/Atlantiss/NetherwingBugtracker/issues/658
https://github.com/Atlantiss/NetherwingBugtracker/issues/343
https://github.com/Atlantiss/NetherwingBugtracker/issues/267
https://github.com/Atlantiss/NetherwingBugtracker/issues/204
https://github.com/Atlantiss/NetherwingBugtracker/issues/323

**Current behaviour**:
NPCs don't egage in combat.

**Expected behaviour**: 
NPCs should engage in combat.

**Server Revision**:

**Comment by tcberk12** [comment]
Found some retail proof from 2008: https://www.youtube.com/watch?v=7eVju9ndvBE

Arrives in moonbrook around 2:25, from then on he engages with mobs before the escort does, but the escort does assist.

**Comment by tcberk12** [comment]
Oddly enough, when completing Therylune's Escape (https://www.wowhead.com/quest=945/therylunes-escape) in Darkshore today, Therylune DID engage with mobs that were already in combat with the player.
