### ISSUE TITLE
The Left/Right Piece (2 quests) of Lord Valthalak's Amulet

### ISSUE THREAD

**Issue by Proprvilin** [Atlantiss/NetherwingBugtracker#6600]
The quests give players a brazier which, when used, summons a quest-related boss inside upper 50s instances (such as Dire Maul). These spawn - when used - in regular boss rooms. However, currently these summoned bosses are spawned automatically upon entering the instance; Isalien and her pet, for instance, spawns next to Alzzin. This forces players to fight both an instance end boss and a higher leveled spawned boss - or two - simultaneously where they should be free to engage only one at a time.
**Server Revision**: 3247.

**Comment by Evolvee** [comment]
https://github.com/Atlantiss/NetherwingBugtracker/issues/5545 already reported
