### ISSUE TITLE
[core][npc cpp script] Hand of Kargath wolfs script

### ISSUE THREAD

**Issue by Evolvee** [Atlantiss/NetherwingBugtracker#6601]
npc_hand_of_kargath
![image](https://user-images.githubusercontent.com/1942409/73592057-56f8a200-44f6-11ea-9f51-60bdf4fcf90b.png)
when 19264 dies, 22374 spawns

problems:

1) yells 2 times on spawn: 
![image](https://user-images.githubusercontent.com/1942409/73592062-6546be00-44f6-11ea-8939-aea363a71ef6.png)

2) 
![image](https://user-images.githubusercontent.com/1942409/73592094-c8385500-44f6-11ea-80e6-4891d43503c4.png)

**Comment by Wolffenstein** [comment]
Fixed in rev 3368.
