### ISSUE TITLE
[Spell] Flametongue double procs with specific weapons

### ISSUE THREAD

**Issue by Tereneckla** [Atlantiss/NetherwingBugtracker#6602]
[//]: # (Enclose links to things related to the bug using http://wowhead.com or any other TBC database.)
[//]: # (You can use screenshot ingame to visual the issue.)
[//]: # (Write your tickets according to the format:)
[//]: # ([Quest][Azuremyst Isle] Red Snapper - Very Tasty!)
[//]: # ([NPC] Magistrix Erona)
[//]: # ([Spell][Mage] Fireball)
[//]: # ([Npc][Drop] Ghostclaw Lynx)
[//]: # ([Web] Armory doesnt work)
[//]: # (To find server revision type `.server info` command in the game chat.)

**Description**: 
https://classic.wowhead.com/item=7682/torturing-poker
https://classic.wowhead.com/item=13952/iceblade-hacker
and other weapons with extra damage are counted as 2 attacks and thus proc flametongue twice.

**Current behaviour**:
![image](https://user-images.githubusercontent.com/50233983/73593451-d0978c80-4504-11ea-9dc3-76fc3f1d1739.png)

**Expected behaviour**: Only 1 flametongue damage proc per attack

**Server Revision**: 3247

**Comment by Tereneckla** [comment]
![image](https://user-images.githubusercontent.com/50233983/74101483-a2d0ca00-4b3a-11ea-8940-9c24e0a5cba3.png)
https://us.forums.blizzard.com/en/wow/t/weapon-enhancement-questions/334107/10
Found a comment on the wow classic forums that it is like that there aswell.
Only comment I found on the interaction.

**Comment by Evolvee** [comment]
still?
