### ISSUE TITLE
[Spell] Mass Dispel can't dispel immunities

### ISSUE THREAD

**Issue by Tereneckla** [Atlantiss/NetherwingBugtracker#6603]
[//]: # (Enclose links to things related to the bug using http://wowhead.com or any other TBC database.)
[//]: # (You can use screenshot ingame to visual the issue.)
[//]: # (Write your tickets according to the format:)
[//]: # ([Quest][Azuremyst Isle] Red Snapper - Very Tasty!)
[//]: # ([NPC] Magistrix Erona)
[//]: # ([Spell][Mage] Fireball)
[//]: # ([Npc][Drop] Ghostclaw Lynx)
[//]: # ([Web] Armory doesnt work)
[//]: # (To find server revision type `.server info` command in the game chat.)

**Description**: https://youtu.be/ojUaZ6aA1yk

**Current behaviour**: Block there

**Expected behaviour**: Block gone

**Server Revision**: 3247

**Comment by Evolvee** [comment]
jfc

**Comment by Wolffenstein** [comment]
I don't know, I can't reproduce it. I even extracted those two characters onto my local and it's still working fine.

**Comment by Wolffenstein** [comment]
Possibly fixed in 3248.
