### ISSUE TITLE
[Fishes] Highland Mixed School all over the place

### ISSUE THREAD

**Issue by Tereneckla** [Atlantiss/NetherwingBugtracker#6605]
[//]: # (Enclose links to things related to the bug using http://wowhead.com or any other TBC database.)
[//]: # (You can use screenshot ingame to visual the issue.)
[//]: # (Write your tickets according to the format:)
[//]: # ([Quest][Azuremyst Isle] Red Snapper - Very Tasty!)
[//]: # ([NPC] Magistrix Erona)
[//]: # ([Spell][Mage] Fireball)
[//]: # ([Npc][Drop] Ghostclaw Lynx)
[//]: # ([Web] Armory doesnt work)
[//]: # (To find server revision type `.server info` command in the game chat.)

**Description**: 
![image](https://user-images.githubusercontent.com/50233983/73599498-6acaf500-4544-11ea-86b1-6b81ee4d5147.png)
https://www.wowhead.com/object=182957/highland-mixed-school

Didn't care that much before that they spawn all over Terokkar, but now I saw one in Nagrand.

**Current behaviour**: Spawn anywhere in Terokkar and apparently also in Nagrand.

**Expected behaviour**: They only spawn in the Highlands of Terokkar, as seen on the map on wowhead.

**Server Revision**: 3247

**Comment by Healweed** [comment]
They are also spawning on Zangarmarsh, tho it's the spawn pool rate is below average. That's how easily a person can get 375 fishing atm on the server

**Comment by Evolvee** [comment]
its cuz wolf forget some old pooling tables still existed when he tried to fix the isle pooling shait -.-

core issue... should be resolved soon™

**Comment by Evolvee** [comment]
next rev
