### ISSUE TITLE
Diminishing Returns

### ISSUE THREAD

**Issue by Tereneckla** [Atlantiss/NetherwingBugtracker#6607]
[//]: # (Enclose links to things related to the bug using http://wowhead.com or any other TBC database.)
[//]: # (You can use screenshot ingame to visual the issue.)
[//]: # (Write your tickets according to the format:)
[//]: # ([Quest][Azuremyst Isle] Red Snapper - Very Tasty!)
[//]: # ([NPC] Magistrix Erona)
[//]: # ([Spell][Mage] Fireball)
[//]: # ([Npc][Drop] Ghostclaw Lynx)
[//]: # ([Web] Armory doesnt work)
[//]: # (To find server revision type `.server info` command in the game chat.)

**Description**: https://www.twitch.tv/videos/545661496
9 sec blind, 9 sec sap, 3 sec free, 3 sec cyclone, 6 sec cyclone
on his druid mate

**Current behaviour**: DR timer is not resetted with the 1st cyclone, so the 2nd is 6 seconds

**Expected behaviour**: DR timer resets after 1st cyclone, 2nd cyclone is 1.5 seconds

**Server Revision**: 3248

**Comment by Evolvee** [comment]
basically what i think what happened @Wolffenstein is that the 3 sec cyclone end didnt reset the DR timer of that specific DR cathegory so the 5 sec tick happened right after which reseted the entire DR cathegory back to 0 --> therefore 6 sec instead of 1.5

**Comment by Drainlock** [comment]
I rewatched full VOD https://www.twitch.tv/videos/544682797?filter=archives&sort=time (from 29:40) And it's looks like it was addon bug (showed that cyclone is 6sec and that my druid used trinket) at 30:05 there are new 6 sec cyclone that was probably trinketed.
Asked Kurca himself and he don't remember, when he used  trinket.
