### ISSUE TITLE
Ending their World issues bloodmyst

### ISSUE THREAD

**Issue by ttghnw** [Atlantiss/NetherwingBugtracker#661]
[//]: # (Enclose links to things related to the bug using http://wowhead.com or any other TBC database.)
[//]: # (You can use screenshot ingame to visual the issue.)
[//]: # (Write your tickets according to the format:)
[//]: # ([Quest][Azuremyst Isle] Red Snapper - Very Tasty!)
[//]: # ([NPC] Magistrix Erona)
[//]: # ([Spell][Mage] Fireball)
[//]: # ([Npc][Drop] Ghostclaw Lynx)
[//]: # ([Web] Armory doesnt work)

**Description**: 

**Current behaviour**:
Escort will despawn on a bare distance from players not even 35 yards happened twice
Escort does not assist with the elite Rare when she attacks the players (blabla the assassin)
**Expected behaviour**: 

**Server Revision**:

**Comment by Peglaa** [comment]
Escorts will despawn if they leave your view distance, it's just how it is. You have to stay close to them.

**Comment by ttghnw** [comment]
Sorry but that is not how it is and if I'm posting this its because it is short. View distance is not 35 yards. I could see mobs further even with the server's low draft distance.

**Comment by Tereneckla** [comment]
Fixed
