### ISSUE TITLE
[Hunter] Frost Trap slow doesn't apply debuff on players inside him

### ISSUE THREAD

**Issue by 4egito** [Atlantiss/NetherwingBugtracker#6610]
[//]: # (Enclose links to things related to the bug using http://wowhead.com or any other TBC database.)
[//]: # (You can use screenshot ingame to visual the issue.)
[//]: # (Write your tickets according to the format:)
[//]: # ([Quest][Azuremyst Isle] Red Snapper - Very Tasty!)
[//]: # ([NPC] Magistrix Erona)
[//]: # ([Spell][Mage] Fireball)
[//]: # ([Npc][Drop] Ghostclaw Lynx)
[//]: # ([Web] Armory doesnt work)
[//]: # (To find server revision type `.server info` command in the game chat.)

**Description**: 
Sometimes "Frost trap" does't apply debuff on players and they are running inside with 100% speed.
**Current behaviour**:
https://www.twitch.tv/videos/545322728?t=1h19m2s
I found that video which shows how the debuff from the trap appears and in a sec dissapears. Meanwhile players running without slow effect. I'm not sure but maybe that happens because the priest is not in the line of sight of triggering position. And when he comes in LOS slow effect shows again...
**Expected behaviour**: 
Frost trap should apply debuff on players which reduce movement speed with 60% and effect should persist LOS
**Server Revision**:

**Comment by 4egito** [comment]
https://drive.google.com/open?id=1CdobgBHms91lVNocM-Nn_uJFvPLJ4OMQ There is a video which can confirm the bug. Trap doesn't affect targets which is in LOS of the aiming position.

**Comment by Wolffenstein** [comment]
Fixed in rev 3276.
