### ISSUE TITLE
[Spell][Priest] Holy Nova

### ISSUE THREAD

**Issue by tsuone** [Atlantiss/NetherwingBugtracker#6611]
[//]: # (Enclose links to things related to the bug using http://wowhead.com or any other TBC database.)
[//]: # (You can use screenshot ingame to visual the issue.)
[//]: # (Write your tickets according to the format:)
[//]: # ([Quest][Azuremyst Isle] Red Snapper - Very Tasty!)
[//]: # ([NPC] Magistrix Erona)
[//]: # ([Spell][Mage] Fireball)
[//]: # ([Npc][Drop] Ghostclaw Lynx)
[//]: # ([Web] Armory doesnt work)
[//]: # (To find server revision type `.server info` command in the game chat.)

**Description**: Incorrect behaviour of Holy Nova Priest ability.

**Current behaviour**: You can heal/damage players on the other side of the pillar on Arenas. https://clips.twitch.tv/FitGenerousBeeKappaClaus

**Expected behaviour**: Shouldn't be able to damage/heal players that are on the other side of the pillar.

**Server Revision**:

**Comment by Wolffenstein** [comment]
Fixed in rev 3389.
