### ISSUE TITLE
[Pathing] Mobs falling into ground before Teron

### ISSUE THREAD

**Issue by Tereneckla** [Atlantiss/NetherwingBugtracker#6613]
[//]: # (Enclose links to things related to the bug using http://wowhead.com or any other TBC database.)
[//]: # (You can use screenshot ingame to visual the issue.)
[//]: # (Write your tickets according to the format:)
[//]: # ([Quest][Azuremyst Isle] Red Snapper - Very Tasty!)
[//]: # ([NPC] Magistrix Erona)
[//]: # ([Spell][Mage] Fireball)
[//]: # ([Npc][Drop] Ghostclaw Lynx)
[//]: # ([Web] Armory doesnt work)
[//]: # (To find server revision type `.server info` command in the game chat.)

**Description**: 
![image](https://user-images.githubusercontent.com/50233983/73829934-181f6080-4804-11ea-9043-1b2bcd92fff2.png)
https://www.youtube.com/watch?v=XMApqlVRWmo

Maybe related to #6592
Both are at the edge of stairs

**Current behaviour**: Mobs fall into ground

**Expected behaviour**: Mobs don't fall into ground

**Server Revision**: 3249

**Comment by The14me** [comment]
Rev.3478 still an issue.
The First pick is npc GPS, the second pick is mine
https://imgur.com/a/TqJ5To0

**Comment by Godmatik** [comment]
Rev 4018 - no longer an issue
Probably fixed with pathing updates  done last year
