### ISSUE TITLE
[Spell] Illidan - Flame Crash reflectable

### ISSUE THREAD

**Issue by dshgrove** [Atlantiss/NetherwingBugtracker#6614]
[//]: # (Enclose links to things related to the bug using http://wowhead.com or any other TBC database.)
[//]: # (You can use screenshot ingame to visual the issue.)
[//]: # (Write your tickets according to the format:)
[//]: # ([Quest][Azuremyst Isle] Red Snapper - Very Tasty!)
[//]: # ([NPC] Magistrix Erona)
[//]: # ([Spell][Mage] Fireball)
[//]: # ([Npc][Drop] Ghostclaw Lynx)
[//]: # ([Web] Armory doesnt work)
[//]: # (To find server revision type `.server info` command in the game chat.)

**Description**: 
You can currently spell reflect illidans flame crash ability, causing it to deal no damage to players even if the spell animation is still there under the boss. It also deals damage to illidan during demon phase (which makes him aggro the warrior instead of the warlock tank, so its not very useful.)

**Current behaviour**:
Can be reflected, placing the spell animation under illidan. Wont do damage to players even if they stand in it.

**Expected behaviour**: 
Should not be reflectable.

**Server Revision**: 
3248

**Comment by The14me** [comment]
https://www.wowhead.com/spell=40841/flame-crash#triggered-by
''Cannot be reflected''
Rev.3478 still an issue.

**Comment by Godmatik** [comment]
Fixed a long time ago, closing
