### ISSUE TITLE
[Spell] Grand Astromancer Capernian - Conflagration

### ISSUE THREAD

**Issue by dshgrove** [Atlantiss/NetherwingBugtracker#6615]
[//]: # (Enclose links to things related to the bug using http://wowhead.com or any other TBC database.)
[//]: # (You can use screenshot ingame to visual the issue.)
[//]: # (Write your tickets according to the format:)
[//]: # ([Quest][Azuremyst Isle] Red Snapper - Very Tasty!)
[//]: # ([NPC] Magistrix Erona)
[//]: # ([Spell][Mage] Fireball)
[//]: # ([Npc][Drop] Ghostclaw Lynx)
[//]: # ([Web] Armory doesnt work)
[//]: # (To find server revision type `.server info` command in the game chat.)

**Description**: 
During the Kael'thas encounter in Tempest Keep, while fighting Capernian you can circumvent the conflagration spell by having a tank standing in melee range for Capernian.

**Current behaviour**:
She always targets the closest target with conflagration. Ranged DPS can then stand closer then 30 yards away from the boss and do damage without any risk.

**Expected behaviour**: 
[https://wowwiki.fandom.com/wiki/Kael%27thas_Sunstrider_(tactics)](url) 
_Conflagration – **Randomly targets players within 30 yards**; causes disorient effect with 600-900 damage per second plus 300 damage per second to all players within 8 yards of the debuffed player. Capernian will not attack players afflicted by conflagaration._

**Server Revision**: 
3248

**Comment by Wolffenstein** [comment]
That's incorrect, Capernian targets a random player other than current tank.
