### ISSUE TITLE
Tempest Keep - Kael'thas pyroblast

### ISSUE THREAD

**Issue by Selphius** [Atlantiss/NetherwingBugtracker#6616]
**Current behaviour**:
Kael'thas randomly uses his pyroblast ability. One time he will use it after along with his shield ability and start 3 pyroblasts sequence, and other time he will not cast pyroblasts at all for the entire p4.

Happened to me for 3 weeks now, so it's not some random occurence, it must be his timer issue maybe cause it overlaps with fireball or something and it breaks the cycle of pyroblasts. Right now P4 is very easy, since tank has no danger of dying.

**Expected behaviour**: 

He should cast his shield, after which he will cast 3 pyroblasts every 1min.

**Server Revision**:

**Comment by BamboozleNW** [comment]
Res 3483. Working correctly , can be closed. 
https://www.youtube.com/watch?v=pc7u2nuUQS0
