### ISSUE TITLE
Water shield is triggered by Furious Howl

### ISSUE THREAD

**Issue by elenmerbau** [Atlantiss/NetherwingBugtracker#6617]
**Description**: Hunter's wolf pets got Furious Howl buff that triggers shaman's water shield every time it lands on a shaman as if shaman is taking damage.

**Expected behaviour**: 
It shouldn't
**Server Revision**: 
3252

**Comment by Tereneckla** [comment]
It is also triggered by a friendly mass dispel.

**Comment by Wolffenstein** [comment]
Fixed in rev 3425.
