### ISSUE TITLE
[NPC] Grunter [Spawn]

### ISSUE THREAD

**Issue by The14me** [Atlantiss/NetherwingBugtracker#6618]
**Current behaviour**: Rare NPC [Grunter](https://classic.wowhead.com/npc=8303/grunter)
 is missing
**Expected behaviour**: 

**Server Revision**:

**Comment by Evolvee** [comment]
![image](https://user-images.githubusercontent.com/1942409/78821624-1461b300-79da-11ea-93ad-95f1468f6a07.png)

?
