### ISSUE TITLE
[NPC] [ZA] Amani'shi Wind Walker

### ISSUE THREAD

**Issue by Sagoona** [Atlantiss/NetherwingBugtracker#6619]
[//]: # (Enclose links to things related to the bug using http://wowhead.com or any other TBC database.)
[//]: # (You can use screenshot ingame to visual the issue.)
[//]: # (Write your tickets according to the format:)
[//]: # ([Quest][Azuremyst Isle] Red Snapper - Very Tasty!)
[//]: # ([NPC] Magistrix Erona)
[//]: # ([Spell][Mage] Fireball)
[//]: # ([Npc][Drop] Ghostclaw Lynx)
[//]: # ([Web] Armory doesnt work)
[//]: # (To find server revision type `.server info` command in the game chat.)

**Description**: 
Counterspelling [Amani'shi Wind Walker](https://www.wowhead.com/npc=24179/amanishi-wind-walker)
**Current behaviour**:
You cannot counter spells of them. Only stunning does the job.
**Expected behaviour**: 
You should be able to counter their spells. At least their chainheals (i.e. with Earthshock) as can be seen here:
https://youtu.be/eczxxR7hnkQ?t=98
**Server Revision**: 
3252

**Comment by Wolffenstein** [comment]
Fixed in rev 3332.
