### ISSUE TITLE
DRUID : rip does not do tool tip damage

### ISSUE THREAD

**Issue by Omarthegreatone** [Atlantiss/NetherwingBugtracker#662]
**Description**: 
rip does not do tool tip damage 
**Current behaviour**:
Rip current rank (2) deals 4 damage per tick, doesnt matter how many combo points I use.
**Expected behaviour**: 
66-234 damage (+ap) over 12 seconds, depending on combo points used
**Server Revision**:

**Comment by DarthNekr0s** [comment]
this happens with a 4 combo point rupture as a rogue too. captured vid, you can see it only applies for about 5 seconds and ticks at 8 damage per second when the 4 point should be doing 112 dmg over 14 sec (rank 1)
https://streamable.com/w3ufs

**Comment by wowthings** [comment]
Can confirm https://streamable.com/01y1w 
Like Omar says doesn't matter the quantity of combo points

**Comment by Wolffenstein** [comment]
Fixed in rev 2067.
