### ISSUE TITLE
[Quest]Alchemy specialization quests

### ISSUE THREAD

**Issue by T0mken** [Atlantiss/NetherwingBugtracker#6621]
[//]: # (Enclose links to things related to the bug using http://wowhead.com or any other TBC database.)
[//]: # (You can use screenshot ingame to visual the issue.)
[//]: # (Write your tickets according to the format:)
[//]: # ([Quest][Azuremyst Isle] Red Snapper - Very Tasty!)
[//]: # ([NPC] Magistrix Erona)
[//]: # ([Spell][Mage] Fireball)
[//]: # ([Npc][Drop] Ghostclaw Lynx)
[//]: # ([Web] Armory doesnt work)
[//]: # (To find server revision type `.server info` command in the game chat.)

**Description**: 
Can't pickup alchemy specialization prequest from [Apothecary Antonivich](https://wowwiki.fandom.com/wiki/Apothecary_Antonivich) even I got lvl 330 alchemy & lvl 70.
**Current behaviour**:
No quest to pickup from Apothecary Antonivich
**Expected behaviour**: 
Requirement for alchemy specialization quests is Alchemy lvl 325 and lvl 68.
**Server Revision**: 
🤔

**Comment by Tereneckla** [comment]
Did you have alchemy before and unlearned it?

**Comment by T0mken** [comment]
> Did you have alchemy before and unlearned it?

I had early on, but not sure if I had specialization or not that time..

**Comment by Tereneckla** [comment]
Related to  #2896 then likely
Unlearning a profession doesn't reset the specialization quests

**Comment by T0mken** [comment]
> Related to #2896 then likely
> Unlearning a profession doesn't reset the specialization quests
Then how do I know what specialization I have? Or how do I gain it again..?

**Comment by Tereneckla** [comment]
ping gm/evolve on discord

**Comment by The14me** [comment]
Fixed.
