### ISSUE TITLE
[Spell][Paladin] Crusaderstrike Wrong Damage

### ISSUE THREAD

**Issue by Tankdiehutte** [Atlantiss/NetherwingBugtracker#6626]
**Description**: Crusaderstrike deals to low damage

**Current behaviour**: Crusaderstrike deals 100% weapon damage

**Expected behaviour**: It should deal 110% weapon damage or 115 to 116% weapon damage with S3 / S4 gloves ( see spell description when equipped)

![Crusaderstrike bugg](https://user-images.githubusercontent.com/56139988/74106859-95cbcf00-4b6a-11ea-8a98-3dd304be889d.jpg)
![Autoattack buggy](https://user-images.githubusercontent.com/56139988/74106868-ada35300-4b6a-11ea-8e6d-029e0a73d680.jpg)

**Server Revision**:

**Comment by Tereneckla** [comment]
![image](https://user-images.githubusercontent.com/50233983/74108045-4b504f80-4b76-11ea-937d-b6ffb6c72c3a.png)
![image](https://user-images.githubusercontent.com/50233983/74108049-4f7c6d00-4b76-11ea-9482-f1340a41d685.png)

And with PvP gloves
![image](https://user-images.githubusercontent.com/50233983/74108089-c285e380-4b76-11ea-9986-5122319a41b0.png)
![image](https://user-images.githubusercontent.com/50233983/74108090-c6196a80-4b76-11ea-9d70-6f38a36dd1b1.png)


Maybe you shouldn't base your tests on a dungeon with variable buff uptime.

**Comment by Tankdiehutte** [comment]
I did the Test on the Dreadfang Widows(lvl 64, and some 65) with S4 Gloves on.
My Meleeattack:

![TestNahkampf](https://user-images.githubusercontent.com/56139988/74786387-e18a2100-52ac-11ea-9010-614f2341f4db.jpg)

My Crusaderstrike:

![TestCrusaderstrike](https://user-images.githubusercontent.com/56139988/74786410-f070d380-52ac-11ea-9e8d-55e897b33763.jpg)

I have ~ 50 damage more on my Crusaderstrikenoncrit, ( Instead of 90 ) & ~ 102Damage more on my Crit ( +3% Crit damage Meta works  fine ^^) . I unequipped all Proccs (Talents, no libram, no hourglass or other procstuff). I Didnt use wings or other ablilities than Crusaderstrike.

How do i get to the 50 damage?
My Weapon, Torch of the Damned ( https://tbcdb.rising-gods.de/?item=32332 ) has an average damage of  495,5. The S4 Gloves bonus makes the crusaderstrike dead 115,5% damage. So the Crusaderstrike deals 0,155 * 495.5 damage, which is 76,8.
With my average Weapon damage i should deal 1094 Damage in average to 0 Armor.
With the Average damage dealt to the Dreadfang Widow ( 686 ) i calcutate the Damage that gets through the Widows armor -> 686 / 1094 = 0,6271

0,6271 * 76,8 = 48,2 Damage, which is pretty close to the 50.

Conclusion: Crusaderstrike uses 115,5% or 110% of the equipped Weapons Damage but not The full weapon Damage shown in the Character info. 
It should do the full damage shown in the Characterinfo, not 10% or 15,5% more weaponbasedamage.

**Comment by Tankdiehutte** [comment]
The difference between my test and yours is that i equipped other items than just a weapon. Making the bug in damage calculation visible.

**Comment by Tereneckla** [comment]
Should have shown my gear then. I had full sunwell bis on my test char and a lvl 1 weapon.
For minimal variance on hit.

**Comment by Tankdiehutte** [comment]
hmm then i dont know where the mistake is, since your difference between my normal & Crusaderstrike and your normalhit &Crusaderstrike look pretty much the same. 
I hope the devs can find the reason. A fixed damage difference could be the reason for the damage looking the same with buffs in fights. 
Today in our Raid we had 2 Ret paladins. Both having the same issue:
Brewmasters Crusaderstrike:

![CrusaderstrikeBrewraid](https://user-images.githubusercontent.com/56139988/74790988-8a3e7d80-52b9-11ea-861e-4d4748271e91.jpg)

His Autohit:

![NahkampfBrewRaid](https://user-images.githubusercontent.com/56139988/74791040-b1954a80-52b9-11ea-8138-d4096ba5a4fe.jpg)

My Crusaderstrike:

![CrusaderstrikeHutteraid](https://user-images.githubusercontent.com/56139988/74791108-dee1f880-52b9-11ea-9078-ea98284a79d8.jpg)

My Autohit 

![NahkampfHutteRaid](https://user-images.githubusercontent.com/56139988/74791157-ff11b780-52b9-11ea-89f4-271b15b9c6ac.jpg)

These values only show that im not getting the 15,5% on CS and Brew is not getting the 10% on his one but the damages of crusaderstrike is still a bit more than normal.

**Comment by Tereneckla** [comment]
[W:From] [Excineris]: the crusader strike issue may be a result of weapon speed normalization, testing with a 3.3 weapon, cs is dealing exactly 110% of the white hits

**Comment by Godmatik** [comment]
Unable to reproduce

Tested with both a very fast and very slow 2H weapon
Same results - roughly 110% weapon damage for Crusader Strike
