### ISSUE TITLE
[Quest] Kael'thas and the Verdant Sphere buff is missing.

### ISSUE THREAD

**Issue by Tereneckla** [Atlantiss/NetherwingBugtracker#6627]
[//]: # (Enclose links to things related to the bug using http://wowhead.com or any other TBC database.)
[//]: # (You can use screenshot ingame to visual the issue.)
[//]: # (Write your tickets according to the format:)
[//]: # ([Quest][Azuremyst Isle] Red Snapper - Very Tasty!)
[//]: # ([NPC] Magistrix Erona)
[//]: # ([Spell][Mage] Fireball)
[//]: # ([Npc][Drop] Ghostclaw Lynx)
[//]: # ([Web] Armory doesnt work)
[//]: # (To find server revision type `.server info` command in the game chat.)

**Description**: https://wowwiki.fandom.com/wiki/Quest:Kael%27thas_and_the_Verdant_Sphere
https://wowwiki.fandom.com/wiki/A%27dal%27s_Song_of_Battle

Upon completing the quest everyone in Shattrath should receive the buff A'dal's Song of Battle

**Current behaviour**: No one gets a buff

**Expected behaviour**: People get buffed

**Server Revision**: 3249

**Comment by Evolvee** [comment]
requires the core thing i was talking about
same for isle, same for hellfire(mgt head)

**Comment by Evolvee** [comment]
btw it shouldnt be just shattrath, it should be shattrath + all TK instances

same for the mgt head --> hellfire + hellfire instances

isle --> isle + mgt

**Comment by Godmatik** [comment]
Fixed in #8659

can close
