### ISSUE TITLE
[Shop] More incentives to donate money

### ISSUE THREAD

**Issue by Tereneckla** [Atlantiss/NetherwingBugtracker#6628]
Description:
These TCG/Event items are not available in the Atlantiss Shop
~~https://www.wowhead.com/item=39656/tyraels-hilt~~
~~https://www.wowhead.com/item=34499/paper-flying-machine-kit~~
~~https://www.wowhead.com/item=23714/perpetual-purple-firework~~
~~https://www.wowhead.com/item=32542/imp-in-a-ball~~
~~https://www.wowhead.com/item=32566/picnic-basket~~
~~https://www.wowhead.com/item=33219/goblin-gumbo-kettle~~

**Comment by Evolvee** [comment]
lulw

**Comment by Evolvee** [comment]
@wtRCH stop fucking up with this tracker or you will be removed

last warning

**Comment by Evolvee** [comment]
fixed all
