### ISSUE TITLE
Combatressing while bossfight

### ISSUE THREAD

**Issue by GMThunderan** [Atlantiss/NetherwingBugtracker#6629]
**Current behaviour**:
When you CR a player who died while in a boss encounter and he logged off and back in again while being dead at any point before being CRd (maybe even due to criterrors), leads the player to be ress'd outside of the instance and not on the coordinates where he got ress'd.

This leads to 
a) the raid wasting a CR and 
b) the player being ineligible for the loot (should the boss die nonetheless).

**Expected behaviour**: 
Player should be ress'd where the combatresser stood while performing the cast. Thus players should be able to rejoin the fight.

**Server Revision**: 
3252

**Comment by veekk** [comment]
same issue in case of **RIP->release->braze**

**Comment by Wolffenstein** [comment]
Fixed in rev 3368.
