### ISSUE TITLE
[Spell] Hunter's Mark

### ISSUE THREAD

**Issue by Pennywise4569** [Atlantiss/NetherwingBugtracker#663]
[//]: # (Enclose links to things related to the bug using http://wowhead.com or any other TBC database.)
[//]: # (You can use screenshot ingame to visual the issue.)
[//]: # (Write your tickets according to the format:)
[//]: # ([Quest][Azuremyst Isle] Red Snapper - Very Tasty!)
[//]: # ([NPC] Magistrix Erona)
[//]: # ([Spell][Mage] Fireball)
[//]: # ([Npc][Drop] Ghostclaw Lynx)
[//]: # ([Web] Armory doesnt work)

**Description**: While questing in Stonetalon Mountain I noticed a mob marked on my map with a red dot. It was a mob a hunter from the other faction had hunter's marked.

**Current behaviour**: Mobs marked with hunter's mark are tracked for everybody on mini map

**Expected behaviour**: Tracking will not show up for anybody not grouped with the hunter.

**Server Revision**:

**Comment by Easyfraggy** [comment]
I could have sworn this is a duplicate, but I can't find the other issue.

**Comment by Easyfraggy** [comment]
I believe this is blizzlike untill some patch, unsure if it was vanilla tbc or wrath. Can someone elaborate?

**Comment by Eidous** [comment]
hunters mark should only show on the map for the hunter that has cast it

hunter pov on Illidan, you can clearly see the difference between the first and second infernal.

On the first infernal the hunter pov casts hunters mark so it shows up on his map, on the second infernal another hunter has cast hunters mark, so it doesnt show up on the hunter pov map

https://youtu.be/BT270SIJtLY?t=283

https://youtu.be/BT270SIJtLY?t=312

**Comment by Wolffenstein** [comment]
Fixed in rev 2298.
