### ISSUE TITLE
[NPC] Mekthorg the Wild behavior

### ISSUE THREAD

**Issue by duzyizly** [Atlantiss/NetherwingBugtracker#6630]
**Description**: 
NPC https://db.excalibur.ws/?npc=18677 Mekthorg the Wild - werid behavior.

**Current behaviour**:
NPC keeps following You out of combat and he's "untouchable" (not evading just ignoring his existance).
This happend after he used his whirlwind ability https://db.excalibur.ws/?spell=37704 so this might be a problem.
running away was not possible - he kept following me.
It takes like 60-70 seconds for him to reset.

![WoWScrnShot_021120_112349](https://user-images.githubusercontent.com/43931626/74279784-dfa7e700-4d1b-11ea-9b7b-af8ea4787a63.jpg)
![WoWScrnShot_021120_112358](https://user-images.githubusercontent.com/43931626/74279790-e0d91400-4d1b-11ea-807a-250359cbdafb.jpg)

**Expected behaviour**: 
Like every outdoors npc he should go back to his patrol position once out of combat.

**Server Revision**: 
3252

**Comment by Evolvee** [comment]
cant reproduce this, you probably stayed after the knock-up on 1 spot for too long = the leash timer reseted

lf vid/steps to reproduce this, reopen afterwards pls
