### ISSUE TITLE
Dps damage bug 

### ISSUE THREAD

**Issue by mokhefi1** [Atlantiss/NetherwingBugtracker#6631]
Hello Netherwing , My dps damage is buged for one week from now , I'm not doing damage like before ,Sometimes  i do normal damage , Sometimes i do really low damage and same in autoattacks no critiques, i'm sure about this bug ,i did some test duels and bgs ,  That bug happens to me 7 years ago in another server name (Wowmania) And Gm fix it to me , He deleted my char and creat new one with same stats , Please i really need help , Please help ,  Char name ( Mokhei ) Thanks you.

**Comment by danbopes** [comment]
You'll have to clarify some more with evidence of the issue, and why it's incorrect. (Showing combat log, and evidence why auto attacks or anything else shouldn't be that low)

**Comment by mokhefi1** [comment]
At the moment i have only screen, tonight i'l make a védio on youtube and send you here , i hope i will get help , Thanks you , if you are a gm just log on my war and you can test by you'r self !

**Comment by mokhefi1** [comment]
@danbopes Here is the védio , i hope my char will get débug , Thanks you , After my char get début or not getting début i'delete the video 
https://www.youtube.com/watch?v=sbjTgf7MLN0&feature=youtu.be

**Comment by mokhefi1** [comment]
> @danbopes Here is the védio , i hope my char will get débug , Thanks you , After my char get débug or not getting débug i'delete the video
> https://www.youtube.com/watch?v=sbjTgf7MLN0&feature=youtu.be

**Comment by mokhefi1** [comment]
@danbopes Here is the védio , i hope my char will get débug , Thanks you , After my char get débug or not getting débug i'delete the video
https://www.youtube.com/watch?v=sbjTgf7MLN0&feature=youtu.be

**Comment by Tereneckla** [comment]
What exactly is the problem there?
Your targets have armor, so your damage will be lower than in your character sheet.

**Comment by 4egito** [comment]
Mate u are the 1st warrior with damage issues seriously ... I don't want to be toxic but look at some warriors stream (Azie for example) and check the numbers... Also just do the simple math while u dueling druids in human form. Your weapon damage is around 1150 which will be reduced by the druids armor (3500-3800) which is around 25% damage reduction. And now 1150 - 288 = 862 normal dmg swing. In 1st duel full s2 druid gets 700-850 normal hits which is completely fine for me. Also in some situations druid had "Natural Protection" stacked buff for 9% dmg reduce thats why normal swings is like 700 otherwise u do 820-840...

**Comment by mokhefi1** [comment]
dude did you see no critical with autoattacks... ! did you see in the end attack critical with 720 ! this bug happens to me 7 years ago in another server and gm fix it to me , if you think this is not a bug i'm sure you didn't play war before , i've played wow from 2008 and break 6 years , my damage is not like before and i'm sure he's bugged , i hope i will get help because this take all my energy and make me won't play , Thanks you and have good day !

**Comment by mokhefi1** [comment]
dude did you see no critical with autoattacks... ! did you see in the end attack critical with 720 !Did you see in low gear druid i do no damage ... ! on warrior 9K hp he have no gear i do 600-700 !!! my damage was better one week ago and now he's bugged and i'm sure about it , this bug happens to me 7 years ago in another server and gm fix it to me , if you think this is not a bug i'm sure you didn't play war before , i've played wow from 2008 only war and break 6 years , my damage is not like before and i'm sure he's bugged , i hope i will get help because this take all my energy and make me won't play , Thanks you and have good day !

**Comment by 4egito** [comment]
Well i can agree that you are doing critical hits very rarely (its 5% not like 35). But from your first explanation i can't understand where is the problem. If u start with "I'm not doing CRITICAL HITS" then people will know where they need to watch.... With my calculations numbers are fine but without crits all make sense...

**Comment by Tereneckla** [comment]
720 crit vs a bear, 60% damage reduction is not unheard of.
Don't forget that most enemies in pvp have resilience.
Can you get recount, so that you can gather stats of all your attacks instead of relying on manual counting or your gut?

**Comment by mokhefi1** [comment]
he was not a bear dude !!!

**Comment by mokhefi1** [comment]
Anyway i'm sure about this bug , i've played war from 2008 , and a gm fix a bug for me in another server , you just dont know how to fix it or you dont know playing warrior that's all , if you can't fix it thanks you i dont wanna keep playing with this damage dps because this take me all my energy and motivation & skills too , so thnaks you and have good day cya

**Comment by mokhefi1** [comment]
720 crit wasn't in bear in last of védio , i know about résilience , My dps was not the same as last week ,  i get little bit help now , i buy another weapon probably my weapon bugged , i will test for 4 more days and i hope this will be fixed , Thanks you anyway guys and i wish you good time & day :)

**Comment by Evolvee** [comment]
seems like individual problem, if any at all

try to compare to other warriors or if your dmg is different on PTR etc.. need more data on this
