### ISSUE TITLE
[Hunter] Kill Command don't hit the target

### ISSUE THREAD

**Issue by 4egito** [Atlantiss/NetherwingBugtracker#6632]
[//]: # (Enclose links to things related to the bug using http://wowhead.com or any other TBC database.)
[//]: # (You can use screenshot ingame to visual the issue.)
[//]: # (Write your tickets according to the format:)
[//]: # ([Quest][Azuremyst Isle] Red Snapper - Very Tasty!)
[//]: # ([NPC] Magistrix Erona)
[//]: # ([Spell][Mage] Fireball)
[//]: # ([Npc][Drop] Ghostclaw Lynx)
[//]: # ([Web] Armory doesnt work)
[//]: # (To find server revision type `.server info` command in the game chat.)

**Description**: 
"Kill Command" don't do damage if the target is not in melee range.  Also proc gets CD and you lose mana without any benefit. In PVE is fine but for PVP is just wasted mana....
**Current behaviour**:
https://drive.google.com/open?id=1iPT0CeQmwMSdFttK5FIUVhWWa5RGzWkW
**Expected behaviour**: 
I think "Kill Command" proc should not gone if the pet don't make a hit
**Server Revision**: 
3255

**Comment by The14me** [comment]
Please try to find some proof. ''I think'' wont work =/

**Comment by 4egito** [comment]
Well i cant find some retail videos and evidence how this spell should actually work but i found this: https://wow.gamepedia.com/Kill_Command -  **Patch 2.2.0 (2007-09-25): Will not charge the hunter mana if their pet is on passive.**
I believe that "pet is on passive" means while he can't land attack or while he have no target because my pet is always on passive mode... So then probably the only problem here is that "Kill Command" charges hunter's mana even when the pet cant land a hit with the ability (u can see this in the video)

**Comment by The14me** [comment]
rev.3478 ''No charge mana if a pet is on passive'' is still an issue.

**Comment by Easyfraggy** [comment]
You currently also gain the buff from Beast Lord Set when you use KC even if it doesn't land.

**Comment by SMDFB** [comment]
> Пожалуйста, попытайтесь найти доказательства. ''Я думаю'' не сработает =/

What evidence is needed, if it is obvious even without the fact that the spell does not work correctly, it is not logical. The pet received a command, but did not deal damage with this spell, even when it reached the target.
On many servers, KC dealt damage even at a distance, since nowhere in the spell description is there a minimum required distance!

**Comment by Wolffenstein** [comment]
Fixed in rev 3834.
