### ISSUE TITLE
[NPC][Spell] Fear Fiend Fel Flames 11k damage

### ISSUE THREAD

**Issue by Tankdiehutte** [Atlantiss/NetherwingBugtracker#6633]
**Description**: The Mob Fear Fiend has a Spell called "Fel Flames". They do way tooo much damage ( xD ) ... 

**Current behaviour**: The Spell is dealing 11k damage. 
![Fear fiend bug](https://user-images.githubusercontent.com/56139988/74548878-ec605100-4f4e-11ea-95da-9d77ff60cc11.png)

**Expected behaviour**:  The spell should deal way less damage and not oneshot the player
 ( https://www.wowhead.com/spell=36248/fel-flames) 

**Server Revision**: 3255

**Comment by GMThunderan** [comment]
It's already on the bugtracker -> [#3157]https://github.com/Atlantiss/NetherwingBugtracker/issues/3157)
