### ISSUE TITLE
[Pets] Hunter pets pathing issue

### ISSUE THREAD

**Issue by eri1997** [Atlantiss/NetherwingBugtracker#6634]
EDIT: Better examples and explanations on the comments below.

**Description**: Pets seems to like to go inside the boss hitbox and die to cleave/fire . At first I assumed it was because I wasn't exactly behind the boss but after changing positions on archimonde to be right behind him this still happened. Whenever pet got bloodlust (might require Beastial Wrath too) pet will go from behind the boss to making a step backwards and move straight through the middle of boss hitbox to trying to get infront of the boss for some reason . After they reach the front of the boss they move back behind the boss (assuming they didn't die to cleave or fire cuz of that). I think this happens because of pet size changes and it happens the most on big radius bosses ( archimonde , supremus is where I see it the most) . My pet is Ravager type , haven't heard complains from Wind Serpent hunters so not sure if it happens for those pets too.

**Current behaviour**: Pet suicidal 

**Expected behaviour**:  Pet not suicidal // Pets attacks the boss from behind.

**Server Revision**: 3256

**Comment by eri1997** [comment]
This week in BT:
Couldn't record Supremus because smb ninjapulled early but Ravager pet went through the boss hitbox in slowmotion after he got bloodlust and beastwrath and died :) (same thing that happens on archimonde every week)

Here is bloodboil death:
https://streamable.com/trk30
 Pet goes retard mode and goes inside the boss hitbox after the boss changed position for a second and went back to the way he was facing. Wind serpents and owl didn't suicide or move much like raveger did. I know its hard to see because of dbm timer wasn't expecting pet to suicide even on small hitbox bosses. Pet dies inside boss hitbox because of cleave somehow. This one on small hitbox bosses is rare but pets should never die to cleave like that ravagers have smth very wrong with their pathing and boss hit box interactions.

**Comment by Red461** [comment]
Adding my voice to this.
Yesterday in BT had the pet die to Bloodboil cleave 5 times. This always happened when the boss was being tanked in the exact same position as the video shown above. The pet looks like it's behind the boss but, it's apparently too close since it keeps getting killed by the cleave. 

Unlike the above post though, my pet was a wind serpent and not a ravager. The other 2 hunters in raid one of with a Wind Serpent, another with a ravager experienced the same issue.

This also leads to pets getting parried which could lead to a tank getting gibbed due to parry haste on more challenging content.

**Comment by eri1997** [comment]
Pet pathing is bad SWP Edition (look at ravager pet) : 

https://streamable.com/p2esz

Idk what to even say about this one. I'm not moving him back he is doing that himself.Pet has no idea where behind the boss is and gets stuck in a loop of back and forth inside the boss hitbox. This kills pets on any boss with cleave like felmyst  and more but that one is hard to get video of because of the green effects. Don't think I can get any better example of pet pathing being shit so this is my last one unless I find another big pathing bug.

**Comment by Red461** [comment]
That is a great video and highlights some of the issues with pet pathing:

- Right at the start, you see two winds erpents on the left, they are slowly (40% speed or so) moving through the boss to reach its back. Somehow the ravager is happy to stay in the front (why?)

- The ravager positioning (apart from being in the front) is ok up until you activate bestial wrath. At this point, his hitbox changes and I suspect the same mechanics that makes mobs backpedal when you're inside their hitbox apply:

1. The pet feels like now that his hitbox has increased, he's too much inside brutallus' hitbox and so he backpedals.

2. Once he's backpedaled he figures out that he's a bit too far from whatever the AI max range is and tries to move back in, only for him to go back to point #1 

This behaviour somehow continues even after bestial wrath ends and he goes back to normal size.

The issues that need to be looked at are twol:

-Pet positioning relative to the target hitbox, right now pet positioning is borked as demonstrated they're getting hit by attacks that should only hit IN THE FRONT (bloodboil arching smash for example)

-Pet should go straight from the back whenever possible not first attack from the front then slowly move through the boss until they reach its back (you can see the wind serpents moving like that at the beginning of the video)

**Comment by NatsumeLily** [comment]
Whats happening with the wind serpents too? Why did they back off that far? I've never done swp, so if it's an aoe why didn't the ravager back off too?

**Comment by eri1997** [comment]
Wind serpents are doing the walk at slow motion speed while moving inside boss hitboxes that happens to all pets .They are heading toward the back of the boss sort of. Ravager pathing just completely bugged out happens a lot with ravagers the comment above explained it really well.

**Comment by Wolffenstein** [comment]
Should work better after revision 3294.
