### ISSUE TITLE
[EN][NPC][Drop] Addled Leper

### ISSUE THREAD

**Issue by HadiSalehWeb** [Atlantiss/NetherwingBugtracker#6635]
[//]: # (Enclose links to things related to the bug using http://wowhead.com or any other TBC database.)
[//]: # (You can use screenshot ingame to visual the issue.)
[//]: # (Write your tickets according to the format:)
[//]: # ([Quest][Azuremyst Isle] Red Snapper - Very Tasty!)
[//]: # ([NPC] Magistrix Erona)
[//]: # ([Spell][Mage] Fireball)
[//]: # ([Npc][Drop] Ghostclaw Lynx)
[//]: # ([Web] Armory doesnt work)
[//]: # (To find server revision type `.server info` command in the game chat.)

**Description**: Mobs outside of Gnomeregan don't drop the [White Punching Card](https://classic.wowhead.com/item=9279/white-punch-card), an item necessary for an engineering recipe.

**Current behaviour**: Mobs don't drop the item.

**Expected behaviour**: Mobs _drop_ the item. 

**Server Revision**: 3255

**Comment by Evolvee** [comment]
fixed in next rev
