### ISSUE TITLE
[Quest][Item] Cooking daily in shattrath doesn't give recipes.

### ISSUE THREAD

**Issue by Tereneckla** [Atlantiss/NetherwingBugtracker#6636]
[//]: # (Enclose links to things related to the bug using http://wowhead.com or any other TBC database.)
[//]: # (You can use screenshot ingame to visual the issue.)
[//]: # (Write your tickets according to the format:)
[//]: # ([Quest][Azuremyst Isle] Red Snapper - Very Tasty!)
[//]: # ([NPC] Magistrix Erona)
[//]: # ([Spell][Mage] Fireball)
[//]: # ([Npc][Drop] Ghostclaw Lynx)
[//]: # ([Web] Armory doesnt work)
[//]: # (To find server revision type `.server info` command in the game chat.)

**Description**: https://www.wowhead.com/item=33857/crate-of-meat#contains
https://www.wowhead.com/item=33844/barrel-of-fish#contains
rewarded by the cooking daily don't have their recipes in the drop table or the drop chance is insanely low. 

**Current behaviour**: Opened 500 of each on PTR and no recipe at all.

**Expected behaviour**: 
![image](https://user-images.githubusercontent.com/50233983/74596557-2dd92500-5051-11ea-9ff6-17bacbd275d5.png)
Barrel of Fish

![image](https://user-images.githubusercontent.com/50233983/74596562-3893ba00-5051-11ea-9dbf-7e27a8088dab.png)
Crate of Meat

ps. please don't forget https://wowwiki.fandom.com/wiki/Recipe:_Captain_Rumsey%27s_Lager in 2.4

**Comment by raethkcj** [comment]
On live server I have gotten every recipe except for Kibler's and Stormchops. Maybe a recent breaking change?

**Comment by Healweed** [comment]
It's just RNG. Myself im missing Skullfish soup and Broilled Bloodfin

**Comment by Tereneckla** [comment]
The chance to get 0 recipes in 1000 boxes is astronomically low.

**Comment by Healweed** [comment]
In 1000 boxes, at least at bare minimum should give what? 100 and so recipes drop? 
Considering that they are *"individual?"* on looting it should have guaranteed you at least a couple of it
--------------------------------------------------------------------------------------------------------------
*But then again RNG is friend of no one*

**Comment by raethkcj** [comment]
![image](https://user-images.githubusercontent.com/7716908/75052163-c11cbb00-5494-11ea-8803-41d8eb7cd820.png)

**Comment by Evolvee** [comment]
https://www.wowhead.com/item=34834/recipe-captain-rumseys-lager#comments:id=235081
![image](https://user-images.githubusercontent.com/1942409/75072040-ef32e700-54f6-11ea-9789-f80b7895d1a7.png)

?

**Comment by Tereneckla** [comment]
yeah, ignore that actually, didn't check enough
was added to those crates in 3.2

**Comment by Evolvee** [comment]
k adjusted some droprates then (it will still not drop 24/7 tho, like 2-3% drop boost to these green shits, blue stay the same)
