### ISSUE TITLE
[Raid][BWL] Suppression Device in Blacking Lair should despawn after killing Broodlord Lashlayer

### ISSUE THREAD

**Issue by raethkcj** [Atlantiss/NetherwingBugtracker#6638]
[//]: # (Enclose links to things related to the bug using http://wowhead.com or any other TBC database.)
[//]: # (You can use screenshot ingame to visual the issue.)
[//]: # (Write your tickets according to the format:)
[//]: # ([Quest][Azuremyst Isle] Red Snapper - Very Tasty!)
[//]: # ([NPC] Magistrix Erona)
[//]: # ([Spell][Mage] Fireball)
[//]: # ([Npc][Drop] Ghostclaw Lynx)
[//]: # ([Web] Armory doesnt work)
[//]: # (To find server revision type `.server info` command in the game chat.)

**Description**: 
Suppression Device object ID 179784 (or maybe 155203)
Broodlord Lashlayer NPC ID 12017

**Current behaviour**:
Suppression Devices remain active, forcing the raid to have a rogue to disable them every time they run through, even after the boss is dead.

**Expected behaviour**: 
The Devices despawn after Broodlord Lashlayer is killed, allowing the raid to move freely through the room.

**Server Revision**: 
3255

**Comment by The14me** [comment]
object ID 179784 is the correct one

**Comment by Wolffenstein** [comment]
Not a bug.
