### ISSUE TITLE
[NPC] Deepmoss Hatchling

### ISSUE THREAD

**Issue by totaemoeggerli** [Atlantiss/NetherwingBugtracker#664]
[//]: # (Enclose links to things related to the bug using http://wowhead.com or any other TBC database.)
[//]: # (You can use screenshot ingame to visual the issue.)
[//]: # (Write your tickets according to the format:)
[//]: # ([Quest][Azuremyst Isle] Red Snapper - Very Tasty!)
[//]: # ([NPC] Magistrix Erona)
[//]: # ([Spell][Mage] Fireball)
[//]: # ([Npc][Drop] Ghostclaw Lynx)
[//]: # ([Web] Armory doesnt work)

**Description**: 
Opening Deepmoss eggs for the quest [Deepmoss Spider Eggs](https://www.wowhead.com/quest=1069/deprecated-deepmoss-spider-eggs) spawns two [Deepmoss Hatchlings](https://www.wowhead.com/npc=4263/deepmoss-hatchling#sounds). When on low life they will spawn a [Deepmoss Matriarch](https://www.wowhead.com/npc=4264/deepmoss-matriarch#comments).
Players get 2 eggs per egg sack looted, two hatchlings will spawn and each of them will spawn a matriarch. 15 eggs are required for the quest witch means every player needs to kill around 15 level 22 Matriarchs for a level 16 quest, if done properly. However, this isn't what happens since player will just run away and reset the Hatchlings. While this is doable solo, it gets cancerous fast with many players in the area.

**Current behaviour**:
Hatchlings summons a matriach whenever they are at low HP.
~~They also seem to deal too much damage, almost same amount as Venture Co Loggers (4 level higher), no proff for that.~~
~~Deepmoss Matriach is a level 22 mob in a level 16 area.~~
https://gfycat.com/UnimportantVastAtlasmoth

**Expected behaviour**: 
Hatchlings shouldn't summon a matriarch all the time as it is suggested in [the comment here](https://www.wowhead.com/npc=4264/deepmoss-matriarch#comments).
~~There aren't bad comments [here](https://www.wowhead.com/quest=1069/deprecated-deepmoss-spider-eggs) which is why I think that the hatchlings are way to powerful and they spawned the matriarch extremly rarely. Also a level 22 mob in a level 16 area is pretty retarded by itself.~~
Without any hard facts I suggest to lower the chance to spawn matriarch ~~and reduce the level of the matriarch to 17-18, maybe even lower the hatchling damage.~~

**Server Revision**: 
2060

**Comment by SwiftieTBC** [comment]
Okay hatchlings melee hit Joana for about 19ish here -https://youtu.be/1KdPk6Jj3vk?t=3m4s
which isn't to dissimilar to the dmg they deal to your outside of bear form in your video.

The mobs were also level 22 in retail as shown - https://youtu.be/1KdPk6Jj3vk?t=4m52s

The video does show the that potentially the damage from the matriarchs are too high but its hard to confirm without being able to estimate both your and Joana's pets armor value ( potentially someone more knowledgeable with hunters pets could add their input)

Last throughout the video there are 2 attempts to call for a matriarch, 1 successful and 1 unsuccessful even after the emote went through.  
The failed attempt - https://youtu.be/1KdPk6Jj3vk?t=3m8s call went out at ~3% hp (Evidently not time based or the other hatchling would of matched the call)
The successful attempt - https://youtu.be/1KdPk6Jj3vk?t=4m48s again the call went out at sub 10% hp

Throughout the Video mobs drop to below 10% hp reinforcing OP's point that its not on every hatchling attempts to call for help.
Overall 10 hatchlings were fought and 2 attempted to call. giving it a 20% chance on this low sample size.
My take on this would be to either put it at a 30% call chance at a 10% HP trigger (which could be nuked through)
or a 20% chance to call on a 25% hp to trigger to give parity too the video evidence.

**Comment by pmachielsen** [comment]
can confirm 9/10 hatchlings did spawn a matriach  when lowhp/killed which only shopuld happen rarely

**Comment by wtRCH** [comment]
- Lower chance to summon Matriatch to 20-25%.
@pelekon

**Comment by Evolvee** [comment]
fixed in next rev
