### ISSUE TITLE
Socrethar is unattackable

### ISSUE THREAD

**Issue by nogi1** [Atlantiss/NetherwingBugtracker#6641]
[//]: # (Enclose links to things related to the bug using http://wowhead.com or any other TBC database.)
[//]: # (You can use screenshot ingame to visual the issue.)
[//]: # (Write your tickets according to the format:)
[//]: # ([Quest][Azuremyst Isle] Red Snapper - Very Tasty!)
[//]: # ([NPC] Magistrix Erona)
[//]: # ([Spell][Mage] Fireball)
[//]: # ([Npc][Drop] Ghostclaw Lynx)
[//]: # ([Web] Armory doesnt work)
[//]: # (To find server revision type `.server info` command in the game chat.)

**Description**: 
[Socrethar](https://www.wowhead.com/npc=20132/socrethar) in the quest [Turning Point](https://www.wowhead.com/quest=10507/turning-point) cannot be attacked, and item cannot be used on him
**Current behaviour**:
Sometimes Socrethar cannot be attacked. Maybe it happes when someone fails to kill him or something because when he dies and respawns everything is ok.
**Expected behaviour**: 
Socrethar should be attackable at any moment.
**Server Revision**:

**Comment by Evolvee** [comment]
requires full rework
its written by pelekon in the most retarded way possible...as always, im actually surprised it worked at some point at all

**Comment by Evolvee** [comment]
lf someone to give me full research (best would be retail video with all of the details showing all misc shits of the event)

**Comment by NatsumeLily** [comment]
I think it can bug when someone fails and hes always attackable. 

Does he have the shield buff, nogi? Did you start the rp event, so you actually fight him?
You should not be able to just walk up and attack him, you need to start the rp event. To start the event someone needs to use the item the teleport, then talk to the npcs. If he can be attacked without the rp event it means someone failed and he didn't reset.

**Comment by nogi1** [comment]
I was there few times in different days and times, there were never any scryers/aldor npcs, even when i used the teleport, he has never had shield on him and was attackable, this one time he wasnt attackable, there was still no shield buff on him, and i couldnt use that item on him, and there were few aldor NPCS some of them dead, couldnt talk to any of them. Its probably not working at all.

**Comment by danbopes** [comment]
This should all be resolved now
