### ISSUE TITLE
[core] [bigass problem] NPC Update Template - when updating multiple times, it doesnt properly inherit dmg multipliers from default template 

### ISSUE THREAD

**Issue by Evolvee** [Atlantiss/NetherwingBugtracker#6642]
when you update npc template of NPC 1 to NPC 2, it correctly changes the dmg to template of NPC 2 but when you then update once again back to NPC 1, the damage stats from NPC 2 stays

e.g. 24918

**Comment by Godmatik** [comment]
Fixed at some point I presume or one of the recent reworks fixed it.

24918 damage was lower in NPC 2 as expected, and when it went back to NPC 1, it properly reverted back to its higher damage.
