### ISSUE TITLE
[Event][Warden Mellichar in Arcatraz] The warden moves out of his location when pulled and the event bugs out.

### ISSUE THREAD

**Issue by HadiSalehWeb** [Atlantiss/NetherwingBugtracker#6643]
[//]: # (Enclose links to things related to the bug using http://wowhead.com or any other TBC database.)
[//]: # (You can use screenshot ingame to visual the issue.)
[//]: # (Write your tickets according to the format:)
[//]: # ([Quest][Azuremyst Isle] Red Snapper - Very Tasty!)
[//]: # ([NPC] Magistrix Erona)
[//]: # ([Spell][Mage] Fireball)
[//]: # ([Npc][Drop] Ghostclaw Lynx)
[//]: # ([Web] Armory doesnt work)
[//]: # (To find server revision type `.server info` command in the game chat.)

**Description**: I'm not sure what the reason is but my best guess is because we were still in combat with the last trash mob in the instance when we pulled Warden Mellichar. This caused him to move out of his little spot and then make the bubble where he was standing (so now he's standing outside it). He then did his RP and the event went on. When Millhouse Manastorm spawned he just moved to the center of the room and became a ghost, didn't move or fight after that. When we wiped the event __didn't__ reset immediately, and we continued where we left off (at the third mini-boss). The mini-boss didn't fight Millhouse as we corpse walked. When we killed Harbinger Skyriss the Naaru trial quest wasn't complete even though Millhouse was alive.

**Current behaviour**: Mellichar moves, Millhouse doesn't fight, Skyriss's death doesn't complete the quest.

**Expected behaviour**: Mellichar stays in his location, Millhouse fights with the group, the quest is completed if Millhouse is alive.

**Server Revision**: 3259

**Comment by Godmatik** [comment]
The event needs to be rescripted in general
More info here:
https://github.com/Atlantiss/NetherwingBugtracker/issues/4600
