### ISSUE TITLE
[Druid] Gather clouds in fly form

### ISSUE THREAD

**Issue by The14me** [Atlantiss/NetherwingBugtracker#6648]
**Current behavior**:
https://streamable.com/9gpky
Learn Engineering
Add 23821
It needs a little spam to time it right, but if u were fast enough u can extract the cloud and be in fly form at the same time.

**Expected behavior**: 
https://www.wowhead.com/item=23821/zapthrottle-mote-extractor
https://cdn.discordapp.com/attachments/518196472831803395/666572237960118292/WoWScrnShot_011420_111945.jpg

**Server Revision**:

**Comment by The14me** [comment]
rev  3319 (Aura rework) still possible to do it.

**Comment by Godmatik** [comment]
Fixed at some point I presume - unable to reproduce.
In past year on Netherwing - have not seen any druids be able to do this.
