### ISSUE TITLE
[Class][Priest] Mind Control / [NPC] Cabal Spellbinder (Shadow Labs)

### ISSUE THREAD

**Issue by UnmeiArcana** [Atlantiss/NetherwingBugtracker#6649]
[//]: # (Enclose links to things related to the bug using http://wowhead.com or any other TBC database.)
[//]: # (You can use screenshot ingame to visual the issue.)
[//]: # (Write your tickets according to the format:)
[//]: # ([Quest][Azuremyst Isle] Red Snapper - Very Tasty!)
[//]: # ([NPC] Magistrix Erona)
[//]: # ([Spell][Mage] Fireball)
[//]: # ([Npc][Drop] Ghostclaw Lynx)
[//]: # ([Web] Armory doesnt work)
[//]: # (To find server revision type `.server info` command in the game chat.)

**Description**: 
Cabal Spellbinders in Murmur's Room at Shadow Labs do not have Earth Shock when Mind Controlled. It is an essential mechanic for shadow priests to be able to interrupt summoners in that room.

**Current behaviour**:
Cabal Spellbinders have no spells to use when Mind Controlled.

**Expected behaviour**: 
They should be able to cast Earth Shock to interrupt summoners.

**Server Revision**: 
3260

**Comment by Evolvee** [comment]
fixed in next rev
