### ISSUE TITLE
[Quest][Arathi Highlands] Hints of a New Plague? pt 2 

### ISSUE THREAD

**Issue by tinkzorg** [Atlantiss/NetherwingBugtracker#665]
[//]: # (Enclose links to things related to the bug using http://wowhead.com or any other TBC database.)
[//]: # (You can use screenshot ingame to visual the issue.)
[//]: # (Write your tickets according to the format:)
[//]: # ([Quest][Azuremyst Isle] Red Snapper - Very Tasty!)
[//]: # ([NPC] Magistrix Erona)
[//]: # ([Spell][Mage] Fireball)
[//]: # ([Npc][Drop] Ghostclaw Lynx)
[//]: # ([Web] Armory doesnt work)

**Description**: Currently, this quest is not in a working state, due to the quest mobs being missing.

**Current behaviour**: Neither the courier nor any escorts spawn at Go'shek farm.

**Expected behaviour**: The courier is meant to spawn at Go'shek (near the apothecary cabin) and make their way slowly to Tarren Mill and back again along the main road.

**Server Revision**: 2060

**Comment by tcberk12** [comment]
How long were you sat there?

Also,

>The courier is meant to spawn at Go'shek (near the apothecary cabin) and make their way slowly to Tarren Mill and back again along the main road.

I don't believe that's entirely true. 

Wowhead comment from 2007: (http://classicdb.ch/?npc=2714#comments)
> When she reaches Tarren Mill, she and her bodyguards despawn.

**Comment by tinkzorg** [comment]
I didn't sit at the farm, I travelled back and forth across the entire length of road, from Go'shek to Tarren Mill and back again. I then repeated this some thirty minutes later. 

Re: wheter the courier despawns, I find that point to be somewhat beside the issue at stake here. The courier DID move from tarren mill to Go'shek during retail, and not just from Go'shek to Tarren Mill. While it might be true that the courier does despawn at Tarren Mill, that also means that the courier is meant to *spawn* there as well. The salient point being that the courier does move northwest along the road, as well as southeast along the same road.

**Comment by tcberk12** [comment]
You're right that it's beside the point, just something I noted while researching.

Sounds like the courier is indeed not there if you ran the whole route two times. Will leave it to staff to confirm.

**Comment by Neophrone** [comment]
I found courier near Taren Mill and 4 Bodyguards with her. They are patroling from Taren Mill to Go'shek. They didn't spawn near Go'shek, when I took quest.

**Comment by aresbrutus** [comment]
Works just fine for me. Any sources on that they should spawn at Tarren Mill and also despawn at Tarren Mill when they return?

**Comment by aresbrutus** [comment]
No additional info, closing this.
