### ISSUE TITLE
Blacksmithing BoP epic weapons are still Main-hand only and unique on 2.4 PTR

### ISSUE THREAD

**Issue by elenmerbau** [Atlantiss/NetherwingBugtracker#6650]
[//]: # (Enclose links to things related to the bug using http://wowhead.com or any other TBC database.)
[//]: # (You can use screenshot ingame to visual the issue.)
[//]: # (Write your tickets according to the format:)
[//]: # ([Quest][Azuremyst Isle] Red Snapper - Very Tasty!)
[//]: # ([NPC] Magistrix Erona)
[//]: # ([Spell][Mage] Fireball)
[//]: # ([Npc][Drop] Ghostclaw Lynx)
[//]: # ([Web] Armory doesnt work)
[//]: # (To find server revision type `.server info` command in the game chat.)

**Description**: 
Blacksmithing weapons such as Drakefist Hammer > Dragonmaw > Dragonstrike and The Planar Edge > Black Planar Edge > Wicked Edge of the Planes are still Main-Hand only and unique. The same applies to the Swordsmith spec with Fireguard sword.
**Expected behaviour**: 
They all should change to One-handed and lose their unique property so people can dual wield them.
https://www.wowhead.com/item=28439/dragonstrike
https://tbcdb.com/?item=28439 Dragonstrike
https://tbcdb.com/?item=28433 Wicked Edge of the Planes
**Server Revision**: 
PTR 3255

**Comment by Evolvee** [comment]
still?

**Comment by elenmerbau** [comment]
Everything works just fine now!
![image](https://user-images.githubusercontent.com/23418072/75123183-586d5280-56cf-11ea-80a9-909d48f4acd0.png)
