### ISSUE TITLE
[Quest] Deathblow to the Legion 2.4

### ISSUE THREAD

**Issue by The14me** [Atlantiss/NetherwingBugtracker#6652]
**Current behaviour**: Event start disappear after a wipe.

**Expected behaviour**:  add quest 10409 ->use the portal-> talk with Adyen The Lightwarden (18537 ) ->start the event and wipe.
Use the portal again->talk with Adyen The Lightwarden ->U don't have the option to start the event again. Now u have only the new quest for Sunwell  and none can start the event anymore.

**Server Revision**:

**Comment by Evolvee** [comment]
https://github.com/Atlantiss/NetherwingBugtracker/issues/6641
