### ISSUE TITLE
[2.4] Squashing some 2.4 bugs before release

### ISSUE THREAD

**Issue by Manaci** [Atlantiss/NetherwingBugtracker#6653]
**Minor visual issues**
~~During the quest [Blast the Gateway](https://tbcdb.com/?quest=11516) the Living Flare doesn't change it's name into Unstable Living Flare like it should (as seen [here](https://youtu.be/khWyssRJy9w?t=207) ). Still gives quest credit but people might think they need 10 kills cause the buff stacks to 10 when you only need 8 of it to explode the gateway.~~ Fixed

During the quest [Blood for Blood](https://tbcdb.com/?quest=11515), the [Felblood Initiates](https://tbcdb.com/?npc=24918) have a default icon which they shouldn't.
![2134124](https://user-images.githubusercontent.com/26745981/75203791-6c689100-576f-11ea-94f1-50c54b7da9d2.png)

**Annoying Issues**
~~The [Felblood Initiates](https://tbcdb.com/?npc=24918) have no leash and will follow the player forever unless killed with the quest item.~~ Fixed

**Progress-halting issues**
~~The quest [Sunfury Attack Plans](https://tbcdb.com/?quest=11877) cannot be taken as the NPC [Lord Torvos](https://tbcdb.com/?npc=25140) has not been spawned on Shattrath, which he should.~~ Fixed

**Server Revision**: 
3262 (PTR)

**Comment by Evolvee** [comment]
living flare name fixed

**Comment by Evolvee** [comment]
kneel fixed

**Comment by Evolvee** [comment]
leash fixed

**Comment by Evolvee** [comment]
torvos will be fixed after SC rework

**Comment by Evolvee** [comment]
@Manaci edit the report to the kneel only

we will need to find a better hackfix xd

**Comment by Evolvee** [comment]
torvos fixed

**Comment by danbopes** [comment]
Kneel aura has been hotfixed.

**Comment by Evolvee** [comment]
nope
