### ISSUE TITLE
Enchant not showing on Brutal Fist weapons S4

### ISSUE THREAD

**Issue by michz28** [Atlantiss/NetherwingBugtracker#6657]
**Description**: 
Enchants do not appear on new S4 Brutal fist weapons
**Current behaviour**:
Enchant glowing effect does not appear
**Expected behaviour**: 
Enchant glowing effect should appear like it appears on dagger or sword or any other weapon
![WoWScrnShot_022520_155851](https://user-images.githubusercontent.com/61463896/75253823-feac7b80-57e7-11ea-90dd-8e342e44233e.jpg)
![WoWScrnShot_022520_155836](https://user-images.githubusercontent.com/61463896/75253846-04a25c80-57e8-11ea-843f-1542a7eb3f55.jpg)
![WoWScrnShot_022520_155108](https://user-images.githubusercontent.com/61463896/75253850-0835e380-57e8-11ea-9f78-3a266f2751df.jpg)

**Comment by Manaci** [comment]
Apparently the glow effect on it counts as [ a weapon glow](https://www.wowhead.com/item=35076/brutal-gladiators-ripper#comments:id=318117:reply=42755) so it won't be overwritten by enchant glows like with the Phoenix Claws.
