### ISSUE TITLE
[NPC][Spell] Freezing Circle

### ISSUE THREAD

**Issue by tsuone** [Atlantiss/NetherwingBugtracker#6658]
[//]: # (Enclose links to things related to the bug using http://wowhead.com or any other TBC database.)
[//]: # (You can use screenshot ingame to visual the issue.)
[//]: # (Write your tickets according to the format:)
[//]: # ([Quest][Azuremyst Isle] Red Snapper - Very Tasty!)
[//]: # ([NPC] Magistrix Erona)
[//]: # ([Spell][Mage] Fireball)
[//]: # ([Npc][Drop] Ghostclaw Lynx)
[//]: # ([Web] Armory doesnt work)
[//]: # (To find server revision type `.server info` command in the game chat.)

**Description**: There is an issue with Freezing Circle spell.

**Current behaviour**: Freezing Circle ability used by Bloodscale Enchantress hits out of radius.

![image](https://user-images.githubusercontent.com/11255782/75279983-e4d15f80-580c-11ea-950b-14cf26ac7147.png)

**Expected behaviour**: Shouldn't hit you when outside the circle 

**Server Revision**: current

**Comment by Wolffenstein** [comment]
Fixed in rev 3432.
