### ISSUE TITLE
Priestess Delrissa in MGT

### ISSUE THREAD

**Issue by sinfer** [Atlantiss/NetherwingBugtracker#6659]
*Description* Priestess Delrissa keeps targeting you after she dies and is unlootable. When you alt f4 to fix the cobat bug, she spawns back with full hp.

**Current behaviour**: Told in "Description.

**Expected behaviour**: Does not target you after she dies and could be looted and moved forward in the dungeon.

**Server Revision**: I have no idea what this means
![WoWScrnShot_022520_214553](https://user-images.githubusercontent.com/45524181/75282298-7fd03680-5819-11ea-9094-cfe8a405ec58.jpg)

**Comment by Wolffenstein** [comment]
Which adds did she spawn and in what order did you kill them?

**Comment by sinfer** [comment]
> Which adds did she spawn and in what order did you kill them?

Now that you mention, I think it spawned only 2 mobs, can't remember which ones though. One was rouge for sure. And no idea on the kill order, im just a healer who minds his own business

**Comment by Wolffenstein** [comment]
Should be fixed.
