### ISSUE TITLE
 [quest][stranglethorn vale] The Second Rebellion

### ISSUE THREAD

**Issue by tinkzorg** [Atlantiss/NetherwingBugtracker#666]
[//]: # (Enclose links to things related to the bug using http://wowhead.com or any other TBC database.)
[//]: # (You can use screenshot ingame to visual the issue.)
[//]: # (Write your tickets according to the format:)
[//]: # ([Quest][Azuremyst Isle] Red Snapper - Very Tasty!)
[//]: # ([NPC] Magistrix Erona)
[//]: # ([Spell][Mage] Fireball)
[//]: # ([Npc][Drop] Ghostclaw Lynx)
[//]: # ([Web] Armory doesnt work)

**Description**: This quest is currently very hard to complete reliably, due to spawns being assigned incorrectly.

**Current behaviour**: Currently, Kurzen Headshrinkers spawn in the same locations as Kurzen Medicine Men and Jungle Fighters.

**Expected behaviour**: Headshrinkers are only supposed to spawn inside the cavern compound; the main camp should consist ONLY of Jungle Fighters and Medicine Men.

**Server Revision**: 2060

**Comment by SwiftieTBC** [comment]
Supported by https://www.youtube.com/watch?v=5A7WkQJxKVU
https://web.archive.org/web/20080630000531/http://wow.allakhazam.com:80/db/quest.html?wquest=574
https://web.archive.org/web/20071208223106/http://thottbot.com:80/q574

**Comment by aresbrutus** [comment]
Seems they were in the same group that are pooled outside of the cave. Will be fixed in one of the upcoming updates.
