### ISSUE TITLE
[SWP] Combat ress bug on Kalecgos

### ISSUE THREAD

**Issue by eri1997** [Atlantiss/NetherwingBugtracker#6660]
**Description**:  Getting combat ressed during the portal realm makes you unable to see the boss when ressed but you can see the players inside. Also you are stuck there not getting teleported out untill its a wipe and boss resets. Other players could see me and the boss.

**Current behaviour**:This is how it looked like when I got combat ressed 
https://streamable.com/fjijf

**Expected behaviour**: -

**Server Revision**: -

**Comment by Wolffenstein** [comment]
Should be fixed.
