### ISSUE TITLE
[NPC][ITEM] Trader Narasu

### ISSUE THREAD

**Issue by wtRCH** [Atlantiss/NetherwingBugtracker#6661]
[//]: # (Enclose links to things related to the bug using http://wowhead.com or any other TBC database.)
[//]: # (You can use screenshot ingame to visual the issue.)
[//]: # (Write your tickets according to the format:)
[//]: # ([Quest][Azuremyst Isle] Red Snapper - Very Tasty!)
[//]: # ([NPC] Magistrix Erona)
[//]: # ([Spell][Mage] Fireball)
[//]: # ([Npc][Drop] Ghostclaw Lynx)
[//]: # ([Web] Armory doesnt work)
[//]: # (To find server revision type `.server info` command in the game chat.)

**Description**: Sells duplicates.

**Current behaviour**: Trader Narasu has 2x of each of Talbuk for sale.

![image](https://user-images.githubusercontent.com/11255782/75297245-9ed9c300-582f-11ea-819a-9c496ac906ee.png)

**Expected behaviour**: I suppose he shouldn't have for sale the same Talbuk for 66 and 95 gold.
**Server Revision**: current

**Comment by NatsumeLily** [comment]
They aren't the same. They are both 100% speed, but they are like normal mounts and epic mounts. 

One is armoured and the other isn't.
