### ISSUE TITLE
[Quest][Daily][SSO]Blast the Gateway

### ISSUE THREAD

**Issue by bekonja** [Atlantiss/NetherwingBugtracker#6662]
[//]: # (Enclose links to things related to the bug using http://wowhead.com or any other TBC database.)
[//]: # (You can use screenshot ingame to visual the issue.)
[//]: # (Write your tickets according to the format:)
[//]: # ([Quest][Azuremyst Isle] Red Snapper - Very Tasty!)
[//]: # ([NPC] Magistrix Erona)
[//]: # ([Spell][Mage] Fireball)
[//]: # ([Npc][Drop] Ghostclaw Lynx)
[//]: # ([Web] Armory doesnt work)
[//]: # (To find server revision type `.server info` command in the game chat.)

**Description**: 
https://www.wowhead.com/quest=11516/blast-the-gateway

**Current behaviour**:
dying fire elems doesnt "share" kill amongst all Living Flares around them, instead only reward 1

**Expected behaviour**: 

>  When the elementals die, they give a charge to all of the living flares around them, even if you didn't aid in the kill.

from comments on wowhead

**Server Revision**: 
3266

**Comment by danbopes** [comment]
This has been hotfixed, and is now live.
