### ISSUE TITLE
MGT buff issue

### ISSUE THREAD

**Issue by Flamelol** [Atlantiss/NetherwingBugtracker#6664]
**Description**: 
https://wowwiki.fandom.com/wiki/Sunblade_Blood_Knight
**Current behaviour**:
Buff from Sunblade blood knight doesnt work for every spell. When i steal it as a mage it works for fireball for example, but it doesnt work for blizzard. 
**Expected behaviour**: 
Every tick of blizzard deals damage so buff should make him stronger and add additional damage from buff. 
**Server Revision**:

**Comment by Wolffenstein** [comment]
It procs from harmful spell casts, Blizzard ticks are just a periodic effect. It is not a bug.

**Comment by Flamelol** [comment]
It not proc from harmful spell casts, description of spell says - every time u deal mele or spell damage.

**Comment by Flamelol** [comment]
U miss 2x different spells, https://www.wowhead.com/spell=44480/seal-of-wrath with https://www.wowhead.com/spell=45096/seal-of-wrath
