### ISSUE TITLE
[NPC] Weird "wolf" bug

### ISSUE THREAD

**Issue by tsuone** [Atlantiss/NetherwingBugtracker#6667]
[//]: # (Enclose links to things related to the bug using http://wowhead.com or any other TBC database.)
[//]: # (You can use screenshot ingame to visual the issue.)
[//]: # (Write your tickets according to the format:)
[//]: # ([Quest][Azuremyst Isle] Red Snapper - Very Tasty!)
[//]: # ([NPC] Magistrix Erona)
[//]: # ([Spell][Mage] Fireball)
[//]: # ([Npc][Drop] Ghostclaw Lynx)
[//]: # ([Web] Armory doesnt work)
[//]: # (To find server revision type `.server info` command in the game chat.)

**Description**: If Wolf type NPC is targeting and going to kill a critter like rabit and at the same time you are targeting this wolf npc with autoattack on, wolf will come and attack you even tho you didn't hit it.

Happened on Timber Worg Alpha in Terokkar Forest.

**Current behaviour**: Wolf aggroes on you even when you don't hit it or come close.

**Expected behaviour**: I don't think wolf should aggro on you.

**Server Revision**: Latest

**Comment by The14me** [comment]
Rev.3478 not an issue anymore.
Can be closed.
