### ISSUE TITLE
[2.4][Raid][Loot] Illidari Council priest loot missing 

### ISSUE THREAD

**Issue by veekk** [Atlantiss/NetherwingBugtracker#6668]
**Description**: Illidari Council must drop 1 additional token after 2.4, but  still 2 tokens + item, must be 3tokens + item

**Current behaviour**: not kek

**Expected behaviour**:  kek

**Server Revision**: latest

**Comment by Evolvee** [comment]
is this some 1 time bug?

**Comment by veekk** [comment]
idk, first ID with 2.4 and we've got only 2 tokens and 1 item

**Comment by veekk** [comment]
illi and mother was fine

**Comment by Evolvee** [comment]
oh you mean it should drop more?
report it properly please

**Comment by veekk** [comment]
Illidari council must drop 3x tokens + 1 item, for now it's 2x tokens + 1 item as pre-2.4

**Comment by Zaorr** [comment]
Can confirm this bug - happend in our ID, too

**Comment by Wolffenstein** [comment]
Fixed in rev 3285.
