### ISSUE TITLE
Missing Sunwell teleport options after bosskills.

### ISSUE THREAD

**Issue by Suzaru** [Atlantiss/NetherwingBugtracker#6670]
**Description**: 
After you kill a Boss NPC in Sunwell, the NPC [Vindicator Moorba (25632)](https://www.wowhead.com/npc=25632/vindicator-moorba) should offer you an option to teleport to certain places. Options are as follows:

1) After you killed "[Kalecgos](https://www.wowhead.com/npc=24850/kalecgos)" He offers an option to teleport to the coordinates where the boss NPC is placed. 
[Gossip](https://i.imgur.com/dLK51d2.jpg): _"With Kalecgos freed, can you provide a teleport up to Apex Point?"_

2) After you killed "The Eredar Twins" [Grand Warlock Alythess](https://www.wowhead.com/npc=25166/grand-warlock-alythess) & [Lady Sacrolash](https://www.wowhead.com/npc=25165/lady-sacrolash), the following option should be offered:
[Gossip](https://i.imgur.com/egQrWNX.png): _"Now that Lady Sacrolash and Grand Warlock Alythess have been defeated, can you teleport me to the Witch's Sanctum."_ It takes you right inbetween the position of the Eredar Twins.

3) The last teleport takes you to the "[Terrace of the Sun](https://i.imgur.com/IKztSjY.jpg)" [(Minimap)](https://i.imgur.com/cgwS1IY.png). It becomes available after players defeated [M'uru](https://www.wowhead.com/npc=25741/muru).
_[Gossip](https://i.imgur.com/ezqAWeC.png) : "We've cleared the way to Kil'jaeden! Can you transport me close to the Sunwell?"_

**Current behaviour**:
Not available.
**Expected behaviour**: 
Available.
**Server Revision**: 
3272

**Comment by Wolffenstein** [comment]
Fixed in rev 3274.
