### ISSUE TITLE
[Item] Prismstone Ring

### ISSUE THREAD

**Issue by UnmeiArcana** [Atlantiss/NetherwingBugtracker#6671]
[//]: # (Enclose links to things related to the bug using http://wowhead.com or any other TBC database.)
[//]: # (You can use screenshot ingame to visual the issue.)
[//]: # (Write your tickets according to the format:)
[//]: # ([Quest][Azuremyst Isle] Red Snapper - Very Tasty!)
[//]: # ([NPC] Magistrix Erona)
[//]: # ([Spell][Mage] Fireball)
[//]: # ([Npc][Drop] Ghostclaw Lynx)
[//]: # ([Web] Armory doesnt work)
[//]: # (To find server revision type `.server info` command in the game chat.)

**Description**: 
The uncommon item Prismstone Ring has wrong stats.

**Current behaviour**:
It gives +9 Health.

**Expected behaviour**: 
Supposed to give +9 Intellect.

**Server Revision**: 
3274

**Comment by Evolvee** [comment]
fixed in next rev
