### ISSUE TITLE
Charm of Swift Flight vs Riding Crop. Something is off.

### ISSUE THREAD

**Issue by Suzaru** [Atlantiss/NetherwingBugtracker#6672]
**Description**: 
Currently the trinket [Charm of Swift Flight (32481)](https://tbcdb.com/?item=32481) (Aura "[Crow Speed (48403)](https://tbcdb.com/?item=32481)") seems to be off, in comparison to the [Riding Crop (25653)](https://tbcdb.com/?item=25653) (Aura: [Mount Speed (48776)](https://tbcdb.com/?spell=48776))

To establish a [baseline (both without trinkets)](https://youtu.be/xoxExqWYVWg) you can see here, that follow works perfectly fine. We will not get disconnected. Thus no talents/other items/auras interfere with the following calculation.

Here [both player's are using the respective trinket](https://youtu.be/BF4oMMtvWFk) (Riding Crop for the mage, and Charm of Swift Flight for the druid). The druid gets disconnected fairly quickly.

[Here](https://youtu.be/dhcmw6W7ins), the mage does not use a flightspeed trinket, but the druid uses Charm of Swift Flight. What happens is, that one player gets disconnected after a longer amount of time. 

If I'm not wrong this means, that the [Charm of Swift Flight (32481)](https://tbcdb.com/?item=32481) does indeed work, but not enough. Or the [Riding Crop (25653)](https://tbcdb.com/?item=25653) gives too much of speedboost.

**Server Revision**: 
3274

**Comment by wtRCH** [comment]
Hmm, I noticed that players with Riding Crop seemed to be way more faster than 10%.

**Comment by NatsumeLily** [comment]
I'm guessing the flight form trinket is incorrectly adding a flat 10% speed buff. It should be 10% of the speed not a flat 10%.

(100% base speed + 280% mount speed) x 1.10 = 418% mount speed

**Comment by cockychan** [comment]
this is still relevant today on karazhan server

**Comment by Wolffenstein** [comment]
Fixed in rev 3562.
