### ISSUE TITLE
[Fishing] Skillups happen too rarely

### ISSUE THREAD

**Issue by aeturnum** [Atlantiss/NetherwingBugtracker#6673]
**Description**: 
Fishing should have skillups on average every X casts, depending on level. Currently, at some fishing skill levels, the actual skillup % chance seems too low.

Based on this chart:
![fishing_skillups](https://user-images.githubusercontent.com/2303837/75489202-ce97e080-597f-11ea-8bca-b63eade08e25.png)

Previously opened #6368 complaining incorrectly about fishing being random.
**Current behaviour**:
Skillups were within expected ranges up to 150.

Fished from 155 to 165: expected ~3 casts per skillup or ~30 casts. Instead it took 86 casts, or an average 8.6 casts per skillup. 
![Fishing155_165](https://user-images.githubusercontent.com/2303837/75489403-28000f80-5980-11ea-9704-abd14d8cacfa.png)

Given the suggested 35% chance per skillup, the chance of getting 10 skillups with this many casts is extremely close to 0. A skillup chance of 10-15% would make more sense for these numbers, but would be far below the Vanilla wow rate.

**Expected behaviour**: 
It's a little hard to say. An average of 3 casts per skillup for the range 145-190 (per the graphic from #6368) could be a probability of 35% per cast.
<img width="651" alt="Screen Shot 2020-02-27 at 4 43 35 PM" src="https://user-images.githubusercontent.com/2303837/75489499-58e04480-5980-11ea-91ba-0909e4bec62e.png">

source: https://homepage.divms.uiowa.edu/~mbognar/applets/bin.html
**Server Revision**: 
3274

**Comment by NatsumeLily** [comment]
Wait till you get to 300+.
Took me 100+ catches to get 1 skill point. My highest was 146, I think.

**Comment by aeturnum** [comment]
Did another 20 points of fishing on the same toon with interesting results:

165-175 took 77 catches, or 7.7 catches per skillpoint.
![Fishing165_175](https://user-images.githubusercontent.com/2303837/75897931-5a3dc100-5e07-11ea-82da-ac39c67d47cb.png)

175-185 took 59 catches, or 5.9 catches per skillpoint
![Fishing175_185](https://user-images.githubusercontent.com/2303837/75898081-940ec780-5e07-11ea-8589-1d7035824f11.png)

Both of these are above the number of catches it *should* take (30), but clearly I am getting skillpoints *faster* as my skill level gets *higher*.  This is also the reverse of what it should be.

**Comment by Wolffenstein** [comment]
Fixed in rev 3409.
