### ISSUE TITLE
Maurading Crust Bursters and Tunnelers in outlands have major targeting issues

### ISSUE THREAD

**Issue by dpeteland** [Atlantiss/NetherwingBugtracker#6674]
[//]: # (Enclose links to things related to the bug using http://wowhead.com or any other TBC database.)
[//]: # (You can use screenshot ingame to visual the issue.)
[//]: # (Write your tickets according to the format:)
[//]: # ([Quest][Azuremyst Isle] Red Snapper - Very Tasty!)
[//]: # ([NPC] Magistrix Erona)
[//]: # ([Spell][Mage] Fireball)
[//]: # ([Npc][Drop] Ghostclaw Lynx)
[//]: # ([Web] Armory doesnt work)
[//]: # (To find server revision type `.server info` command in the game chat.)
3274 content patch 240

**Description**: 
Wrote this to GMs who told me to report here. After one of the worms goes underground they become almost untargetable. They get stuck in a loop popping out of the ground or appear to be infront of you when they are to the side/behind you. Thus attacking them becomes a huge issue because visually they are infront of you but you get an error "Target needs to be in front of you". You can however rotate 90* and then attack normally but this seems to be a huge issue especially with outland quests. 
**Current behaviour**:
un-engageable once they go back underground.
**Expected behaviour**: 
normal targeting
**Server Revision**:

**Comment by Wolffenstein** [comment]
Fix pending.

**Comment by The14me** [comment]
Related https://github.com/Atlantiss/NetherwingBugtracker/issues/2298

**Comment by danbopes** [comment]
Will be deployed in todays server update.
