### ISSUE TITLE
Temp Icon Displayed when using Attuned Crystal Cores

### ISSUE THREAD

**Issue by KevgenPrimus** [Atlantiss/NetherwingBugtracker#6675]
![Bug Sentry](https://user-images.githubusercontent.com/61580738/75528824-980ba580-5a13-11ea-915c-397e24194899.jpeg)

**Description**: 
When using Attuned Crystal Cores, (From quest id 11524 Erratic Behavior), it casts spell 44997, which has a SpellIconId = 1. (Meme Face)

**Current behaviour**:
Icon is Meme Face (SpellIconId = 1)

**Expected behaviour**: 
Spell Icon should be a cog: https://www.wowhead.com/spell=44997/converting-sentry.

**Server Revision**: 
3274

**Comment by danbopes** [comment]
@Evolvee I tried a few things on my end. If this needs core support, let me know.

**Comment by Wolffenstein** [comment]
Not a bug in 2.4.3.
