### ISSUE TITLE
[NPC] Stormwind City Guard

### ISSUE THREAD

**Issue by tsu-1** [Atlantiss/NetherwingBugtracker#6676]
[//]: # (Enclose links to things related to the bug using http://wowhead.com or any other TBC database.)
[//]: # (You can use screenshot ingame to visual the issue.)
[//]: # (Write your tickets according to the format:)
[//]: # ([Quest][Azuremyst Isle] Red Snapper - Very Tasty!)
[//]: # ([NPC] Magistrix Erona)
[//]: # ([Spell][Mage] Fireball)
[//]: # ([Npc][Drop] Ghostclaw Lynx)
[//]: # ([Web] Armory doesnt work)
[//]: # (To find server revision type `.server info` command in the game chat.)

**Description**: Multiple spawns in one place.

**Current behaviour**: There are 3 Stormwind City Guard spawned in one place when you go from Trade District to Mage Quarter.
![image](https://user-images.githubusercontent.com/11255782/75543985-5125ac00-5a23-11ea-8a4c-d8b2235db7d8.png)

**Expected behaviour**: There should be only one.

**Server Revision**: 3274

**Comment by Manaci** [comment]
Most likely some horde when there and triggered the city alert system but they didn't despawn properly.

**Comment by Godmatik** [comment]
Unable to reproduce - triggered the extra guards many times as a horde player but never more than 1 spawn at a spot.
