### ISSUE TITLE
On SWP trash drop rates

### ISSUE THREAD

**Issue by Azalen** [Atlantiss/NetherwingBugtracker#6677]
I think SWP trash drop rates are way off and need fixing **unless ofc the low drop rates are intended** in which case that should be communicated properly.

Simple Example:
https://web.archive.org/web/20090130143951/http://thottbot.com/c25369#A::A

From 765 tracked kills we get 94 Mark of the Illidari (fixed already thanks to discussion in discord), 165 Epic Gems of different type, 34 Sunmotes and then we have 13 other sides of potential loot that was included in the 765 tracked kills.
It is important to note that these dropchances add up, meaning, just because the chance of Lionseye is 4.4% doesnt mean there should be ~4% chance for the mob to drop an epic gem but only 4.4% chance for the mob to drop that specific epic gem thus 21% to drop an epic gem at all.

This is also true - and more important - for the recipe drops and random epics. If we only look at the patterns (23 in the linked loottable) they sum up to pretty big percentages. 
Be aware: every player in a raid needs the chest pattern for his class/spec. It is not like it drops once and everyone gets it since the actual item is BOP. Thus at least the droprates for the patterns of the BOP-patterns should get adjusted.

Everyone who spend time in SWP in the last 4 days knows that we are not even close to these numbers, thus I wanted to make this post since discord discussion was getting out of hand.

**Comment by Wolffenstein** [comment]
Upped
