### ISSUE TITLE
[Quest] [Wetlands] The Missing Diplomat

### ISSUE THREAD

**Issue by tinkzorg** [Atlantiss/NetherwingBugtracker#668]
[//]: # (Enclose links to things related to the bug using http://wowhead.com or any other TBC database.)
[//]: # (You can use screenshot ingame to visual the issue.)
[//]: # (Write your tickets according to the format:)
[//]: # ([Quest][Azuremyst Isle] Red Snapper - Very Tasty!)
[//]: # ([NPC] Magistrix Erona)
[//]: # ([Spell][Mage] Fireball)
[//]: # ([Npc][Drop] Ghostclaw Lynx)
[//]: # ([Web] Armory doesnt work)

**Description**: Alright, this one is a bit hard to really put concisely, but my feeling is that you guys need to test various scenarios in this particular stage of the quest chain to eliminate all the kinks. The quest is technically quite easy to complete, but it can also break quite easily, with some pretty severe consequences.

**Current behaviour**: A few things: 1) The NPC you are supposed to fight does not despawn on his own. At one point, I fought him, got killed, and then went back to respawn. He was still there. Returning a few hours later, the NPC still hadnt respawned. This is obviously not intended.

2) The actual quest giver (Mikhail) breaks easily, at which point he will not give out the quest again if you abandon it. I'd wager this is connected to the fact that the spy does not despawn on his own; a flag that should be tripped is probably NOT being tripped.

3) I was able to reaquire this quest (and complete it) after waiting for a server restart. So the quest itself is not broken, provided you do all the steps correctly. Not doing them correctly runs the risk of breaking the entire quest script, however.

**Expected behaviour**: The quest target should walk (in stealth) out of the Deepwater Inn, then start running, and then quickly respawn, at which point the player should be able to abandon the quest and then immediately reaquire it from Mikhail.

**Server Revision**: 2060

**Comment by tcberk12** [comment]
Trying to complete right now, Tapoke is just standing outside the inn and won't despawn. Consistent with OPs report.

**Comment by Tenoutoften** [comment]
* [[NPC]Tapoke "Slim" Jahn#4962](https://www.wowhead.com/npc=4962/tapoke-slim-jahn#screenshots) is facing the wrong way. Should face [[NPC]Mikhail#4963](https://www.wowhead.com/npc=4963/mikhail)
![](https://www.wow-freakz.com/img/screenshots/wowhead_74932.jpg)

* After accepting [[Quest]The Missing Diplomat#1249](https://www.wowhead.com/quest=1249/the-missing-diplomat) [[NPC]Tapoke "Slim" Jahn#4962](https://www.wowhead.com/npc=4962/tapoke-slim-jahn#screenshots) should stealth and go for the exit, after exiting he should leave stealth and start running and despawn shortly after.

* [Video from Wrath](https://youtu.be/tMRfdjbVJTg?t=83) displaying it.

* Note that [[NPC]Tapoke "Slim" Jahn#4962](https://www.wowhead.com/npc=4962/tapoke-slim-jahn#screenshots) doesn't die. One he is defeated he will remain alive, turn friendly and give out information.

* After getting this quest complete on NW(Killing  [[NPC]Tapoke "Slim" Jahn#4962](https://www.wowhead.com/npc=4962/tapoke-slim-jahn#screenshots)  [[NPC]Mikhail#4963](https://www.wowhead.com/npc=4963/mikhail) stuck completely and wouldn't let me turn in.

![](https://i.gyazo.com/d1c2e1a383305585f30507345acd0704.png)

* Abandoned [[Quest]The Missing Diplomat#1249](https://www.wowhead.com/quest=1249/the-missing-diplomat) and [[NPC]Mikhail#4963](https://www.wowhead.com/npc=4963/mikhail) doesn't offer the quest.
![](https://i.gyazo.com/c80060ad42af87b5e6e5c99c88d96f06.png)

----
* [[NPC]Tapoke "Slim" Jahn#4962](https://www.wowhead.com/npc=4962/tapoke-slim-jahn#screenshots) faces the wrong way
* [[NPC]Tapoke "Slim" Jahn#4962](https://www.wowhead.com/npc=4962/tapoke-slim-jahn#screenshots) shouldn't die when defeated
* Missing RP from [[NPC]Tapoke "Slim" Jahn#4962](https://www.wowhead.com/npc=4962/tapoke-slim-jahn#screenshots) & [[NPC]Mikhail#4963](https://www.wowhead.com/npc=4963/mikhail)

**Comment by killablink** [comment]
Confirmed, was doing it in a group of 2, I did it before my party member took the quest, and after I killed Tapoke, my teammate couldn't pick up the quest from Mikhail. Can't turn the quest after either.

**Comment by Evolvee** [comment]
You need to kill that npc...

**Comment by Evolvee** [comment]
I will make a timed check for the npc to return if noone attacks him in time eventually.

**Comment by eedijs** [comment]
I cannot interact with Mikhail to complete the quest, this is after I got the quest in Stormwind from Elias, this is before the fight I guess. I can only trade to buy and sell stuff from him.

**Comment by Javinyx** [comment]
Same thing happening to me, can't talk to Mikhalis.

**Comment by Evolvee** [comment]
kill tapoke in front of the tavern

**Comment by Javinyx** [comment]
It worked, but I think it's supposed to be the other way around, as in kill Tapoke after speaking

**Comment by Evolvee** [comment]
Someone accpted it and didnt kill him so it got stucked.

**Comment by Evolvee** [comment]
added automatic return if noone attacks Tapoke and reset of the questgiver state in the next rev
