### ISSUE TITLE
[NPC] Squirrel - MGT non attackable

### ISSUE THREAD

**Issue by Leiya1337** [Atlantiss/NetherwingBugtracker#6682]
[//]: # (Enclose links to things related to the bug using http://wowhead.com or any other TBC database.)
[//]: # (You can use screenshot ingame to visual the issue.)
[//]: # (Write your tickets according to the format:)
[//]: # ([Quest][Azuremyst Isle] Red Snapper - Very Tasty!)
[//]: # ([NPC] Magistrix Erona)
[//]: # ([Spell][Mage] Fireball)
[//]: # ([Npc][Drop] Ghostclaw Lynx)
[//]: # ([Web] Armory doesnt work)
[//]: # (To find server revision type `.server info` command in the game chat.)

**Description**: NPC 1412 ID 444-454 in MGT are not attackable and don't randommove. 452 and 444 are douplicates. 1412 outside MGT are attackable just fine.

**Current behaviour**:

**Expected behaviour**: 

**Server Revision**: 3277

**Comment by Suzaru** [comment]
Attackable with spells, but not with melee.

**Comment by Wolffenstein** [comment]
Fixed in rev 3281.
