### ISSUE TITLE
[Obejct] Nightmae Vines aren't spawning at the Dead Scar on Isle of Quel'Danas

### ISSUE THREAD

**Issue by Manaci** [Atlantiss/NetherwingBugtracker#6683]
**Description**: 
There is supposed to be 4 spawns of Nightmare Vine at the bottom of the Isle of Quel'Danas map at the Dead Scar [here](https://i.imgur.com/ZvcjcA6.png). Pooling is unknown, but lets say 1 or 2 out of 4 can be spawned at the same time. [Proof](https://www.ownedcore.com/forums/world-of-warcraft/world-of-warcraft-guides/113932-herbing-queldanas.html)

**Server Revision**: 
3277

**Comment by The14me** [comment]
All are spawned in rev 3442.
Can be closed.

**Comment by Evolvee** [comment]
doubt, afaik i didnt spawn any and i dont think anyone else but me did anything on isle
