### ISSUE TITLE
[Paladin spell] Darkmoon Crusade card and Seal of blood judgement

### ISSUE THREAD

**Issue by spade93** [Atlantiss/NetherwingBugtracker#6684]
[//]: # (Enclose links to things related to the bug using http://wowhead.com or any other TBC database.)
[//]: # (You can use screenshot ingame to visual the issue.)
[//]: # (Write your tickets according to the format:)
[//]: # ([Quest][Azuremyst Isle] Red Snapper - Very Tasty!)
[//]: # ([NPC] Magistrix Erona)
[//]: # ([Spell][Mage] Fireball)
[//]: # ([Npc][Drop] Ghostclaw Lynx)
[//]: # ([Web] Armory doesnt work)
[//]: # (To find server revision type `.server info` command in the game chat.)

**Description**: 
Darkmoon Crusade Card effect on Seal of blood judgement
**Current behaviour**:
effect on Seal of blood judgement is considered physical dmg 
**Expected behaviour**: 
Effect should be considered as holy dmg (magic) (works fine with other seal judgements, just the sob that's bugged)
**Server Revision**:

**Comment by Tereneckla** [comment]
![image](https://user-images.githubusercontent.com/50233983/81474247-5f066300-9204-11ea-954d-f22319e4da00.png)

Judgement of Blood is the outlier. It giving the AP buff is correct.
