### ISSUE TITLE
[Dungeon][Magister's terrace]Linked packs

### ISSUE THREAD

**Issue by Wilmya** [Atlantiss/NetherwingBugtracker#6685]
**Current behaviour**: Entering the room of third boss (Priestess Delrissa) the pack of 4, to the right, surronding a broken down robot and the pack behind it that are standing in the hut are currently linked. Reproduce it by pulling the Blood Knight mob in the first pack and watch as the 3 mobs in the little hut also comes out to fight.

**Expected behaviour**: 2 different packs, 2 pulls.

**Server Revision**: 3277

**Comment by Wolffenstein** [comment]
Fixed in rev 3281.
