### ISSUE TITLE
[Quest] Vessels of Power

### ISSUE THREAD

**Issue by wtRCH** [Atlantiss/NetherwingBugtracker#6686]
[//]: # (Enclose links to things related to the bug using http://wowhead.com or any other TBC database.)
[//]: # (You can use screenshot ingame to visual the issue.)
[//]: # (Write your tickets according to the format:)
[//]: # ([Quest][Azuremyst Isle] Red Snapper - Very Tasty!)
[//]: # ([NPC] Magistrix Erona)
[//]: # ([Spell][Mage] Fireball)
[//]: # ([Npc][Drop] Ghostclaw Lynx)
[//]: # ([Web] Armory doesnt work)
[//]: # (To find server revision type `.server info` command in the game chat.)

**Description**: Picking up vessel doesn't give credit/item from it.
Previous issues: #6481

**Current behaviour**: Vessels don't give credit or item after picking up.

**Expected behaviour**: Should give a credit.

**Server Revision**: 3277

**Comment by Wolffenstein** [comment]
Some vessels are traps that don't give credit.

**Comment by wtRCH** [comment]
I picked up 10 and 10 of them were traps then 🥴
