### ISSUE TITLE
Feign death doesnt show cd

### ISSUE THREAD

**Issue by darknessangelo** [Atlantiss/NetherwingBugtracker#6687]
[//]: # (Enclose links to things related to the bug using http://wowhead.com or any other TBC database.)
[//]: # (You can use screenshot ingame to visual the issue.)
[//]: # (Write your tickets according to the format:)
[//]: # ([Quest][Azuremyst Isle] Red Snapper - Very Tasty!)
[//]: # ([NPC] Magistrix Erona)
[//]: # ([Spell][Mage] Fireball)
[//]: # ([Npc][Drop] Ghostclaw Lynx)
[//]: # ([Web] Armory doesnt work)
[//]: # (To find server revision type `.server info` command in the game chat.)

**Description**: 
If you cast FD from spellbook or manually from bar it's fine, but if you cast it via shortcut it doesn't show CD. Was fine before SWP comes out.
**Current behaviour**:

**Expected behaviour**: 

**Server Revision**: 
3277

**Comment by The14me** [comment]
Die/relog 'fix'' the issue.

**Comment by darknessangelo** [comment]
nope it don't for me, died, reloged, deleted cash a lot of time and nothing.

**Comment by Evolvee** [comment]
what shortcut

**Comment by darknessangelo** [comment]
I got FD in macro with stopcast and keybinded on mouse wheel down

**Comment by Manaci** [comment]
I've had this happen too, also macroed with /stopcast.

**Comment by eri1997** [comment]
Every fd after this one didn't show cd either. Very annoying bug which wiped us later this try. Icon doesn't show cd after you use it .This used to be super rare before swp patch so not sure what changed at that point.
https://streamable.com/cz8os

**Comment by Godmatik** [comment]
![3891](https://github.com/user-attachments/assets/19e11301-3ffa-4e30-b61e-3ea32fe6ffc1)

Fixed back in rev 3891
