### ISSUE TITLE
[Loot] Bag from Fishing Daily "Crocolisks in the City" has no loot

### ISSUE THREAD

**Issue by Tereneckla** [Atlantiss/NetherwingBugtracker#6688]
[//]: # (Enclose links to things related to the bug using http://wowhead.com or any other TBC database.)
[//]: # (You can use screenshot ingame to visual the issue.)
[//]: # (Write your tickets according to the format:)
[//]: # ([Quest][Azuremyst Isle] Red Snapper - Very Tasty!)
[//]: # ([NPC] Magistrix Erona)
[//]: # ([Spell][Mage] Fireball)
[//]: # ([Npc][Drop] Ghostclaw Lynx)
[//]: # ([Web] Armory doesnt work)
[//]: # (To find server revision type `.server info` command in the game chat.)

**Description**: There's 2 types of bags from the Fishing Daily
https://www.wowhead.com/item=34863 from 4 of the quests.
https://www.wowhead.com/item=35348 from "Crokolisks in the City"

**Current behaviour**: 35348 only drops gold.

**Expected behaviour**: 35348 has the same regular drops as 34863 and additionally a chance to get 1 of the 4 Crocolisk Pets

**Server Revision**: 3277

**Comment by Manaci** [comment]
Went on PTR and spawned a bunch of 35348 bags, looks like it mostly only drops gold BUT can also have the Crocolisk Pets, just missing the rest of the rewards that also drop in the 34863 version of the bag.
![12345](https://user-images.githubusercontent.com/26745981/75679912-c9dd7000-5c90-11ea-96ab-5f25789e25ce.png)

**Comment by Evolvee** [comment]
next rev
