### ISSUE TITLE
[Spell] Spirit Heal buff

### ISSUE THREAD

**Issue by wtRCH** [Atlantiss/NetherwingBugtracker#6689]
[//]: # (Enclose links to things related to the bug using http://wowhead.com or any other TBC database.)
[//]: # (You can use screenshot ingame to visual the issue.)
[//]: # (Write your tickets according to the format:)
[//]: # ([Quest][Azuremyst Isle] Red Snapper - Very Tasty!)
[//]: # ([NPC] Magistrix Erona)
[//]: # ([Spell][Mage] Fireball)
[//]: # ([Npc][Drop] Ghostclaw Lynx)
[//]: # ([Web] Armory doesnt work)
[//]: # (To find server revision type `.server info` command in the game chat.)

**Description**: Spirit Heal reduces cost of your spells by 100%.

**Current behaviour**: Spirit Heal doesn't reduce cost of Rage required spells.

**Expected behaviour**: Spirit Heal should reduce cost of all spells including Rage required.

**Server Revision**: 3277

**Comment by Wolffenstein** [comment]
No it shouldn't, at least in TBC. Only affects magical spells.
