### ISSUE TITLE
[Sunstrider Isle] Death in the air

### ISSUE THREAD

**Issue by LookinGood** [Atlantiss/NetherwingBugtracker#669]
[//]: # (Enclose links to things related to the bug using http://wowhead.com or any other TBC database.)
[//]: # (You can use screenshot ingame to visual the issue.)
[//]: # (Write your tickets according to the format:)
[//]: # ([Quest][Azuremyst Isle] Red Snapper - Very Tasty!)
[//]: # ([NPC] Magistrix Erona)
[//]: # ([Spell][Mage] Fireball)
[//]: # ([Npc][Drop] Ghostclaw Lynx)
[//]: # ([Web] Armory doesnt work)

**Description**: 
Died from falling on the water, corpse in the air 
![wowscrnshot_092618_122207](https://user-images.githubusercontent.com/38701596/46090394-18e4c300-c1ca-11e8-94db-29c9ba1aaae9.jpg)
![wowscrnshot_092618_122218](https://user-images.githubusercontent.com/38701596/46090433-213cfe00-c1ca-11e8-8c49-cb20f30e69cd.jpg)
![wowscrnshot_092618_122220](https://user-images.githubusercontent.com/38701596/46090505-45004400-c1ca-11e8-8209-be6554e07201.jpg)

**Current behaviour**:

**Expected behaviour**: 
Swimming
**Server Revision**:

**Comment by Easyfraggy** [comment]
Believe it or not corpse in the air is actually blizzlike, I can't tell you how many times i saw dead people mid air in vanilla and tbc. IDK when blizzard fixed it (possibly late tbc) but none the less I hope wolf can fix it, cus it just looks bad.  

Just wanted to share that TY for reporting!

Ofc fall dmg when hitting water is wrong too xD

**Comment by Wolffenstein** [comment]
Fixed in rev 2063.
