### ISSUE TITLE
[Battleground][NPC] Taking mines in Alterac Valley despawns enemy NPCs

### ISSUE THREAD

**Issue by tsu-1** [Atlantiss/NetherwingBugtracker#6690]
[//]: # (Enclose links to things related to the bug using http://wowhead.com or any other TBC database.)
[//]: # (You can use screenshot ingame to visual the issue.)
[//]: # (Write your tickets according to the format:)
[//]: # ([Quest][Azuremyst Isle] Red Snapper - Very Tasty!)
[//]: # ([NPC] Magistrix Erona)
[//]: # ([Spell][Mage] Fireball)
[//]: # ([Npc][Drop] Ghostclaw Lynx)
[//]: # ([Web] Armory doesnt work)
[//]: # (To find server revision type `.server info` command in the game chat.)

**Description**: Taking mines in Atlerac Valley works incorrectly

**Current behaviour**: Taking neutral or enemy mines in Alterac Valley despawns enemy NPCs inside.

**Expected behaviour**: Taking mines shouldn't despawn enemy NPCs inside, they should fight instead.

**Server Revision**: 3277

**Comment by Godmatik** [comment]
Closing - will consolidate all outstanding AV issues into one thread now.
