### ISSUE TITLE
[Loot] Tier 6 Token drops in 2.4

### ISSUE THREAD

**Issue by Zaorr** [Atlantiss/NetherwingBugtracker#6691]
[//]: # (Enclose links to things related to the bug using http://wowhead.com or any other TBC database.)
[//]: # (You can use screenshot ingame to visual the issue.)
[//]: # (Write your tickets according to the format:)
[//]: # ([Quest][Azuremyst Isle] Red Snapper - Very Tasty!)
[//]: # ([NPC] Magistrix Erona)
[//]: # ([Spell][Mage] Fireball)
[//]: # ([Npc][Drop] Ghostclaw Lynx)
[//]: # ([Web] Armory doesnt work)
[//]: # (To find server revision type `.server info` command in the game chat.)

**Description**: 
Since 2.4 each boss drops three Tier Set tokens instead of two.
This bug is based on experience on Hyjal, Black Temple and Sunwell Plateau.

**Current behaviour**:
Each boss **always** drops one token each:
1x Protector, 1x Vindicator, 1x Conqueror

**Expected behaviour**: 
Each boss drops three tokens, but the distribution is random.

**Server Revision**: 
3277

**Comment by Drainlock** [comment]
Also last reset Council dropped only 2 tokens.

**Comment by veekk** [comment]
#6668 lost 2 tokens already

**Comment by Wolffenstein** [comment]
Fixed in rev 3285.
