### ISSUE TITLE
Veins in Hyjal not giving epic gems since 2.4

### ISSUE THREAD

**Issue by asaphlive** [Atlantiss/NetherwingBugtracker#6692]
**Description**: 
Since 2.4 it seems that in Hyjal the epic gems out of the mine able veins are not loot able or not in loot table.

**Expected behaviour**: 

Epic gems should be loot able out of the veins

**Comment by veekk** [comment]
can confirm, lot of grey junk and few blue gems

**Comment by Manaci** [comment]
Also I went to test the veins in MH on PTR, looks like they lost their epic gems. I mined all 9 of them and only got 14 blue gems and the shattered fragments, 0 epic gems so something definitely happened here with a newer update

**Comment by Wolffenstein** [comment]
Fixed in rev 3284.
