### ISSUE TITLE
[Battleground] [AB/EOS/AV] Spirit Healer

### ISSUE THREAD

**Issue by tsu-1** [Atlantiss/NetherwingBugtracker#6693]
[//]: # (Enclose links to things related to the bug using http://wowhead.com or any other TBC database.)
[//]: # (You can use screenshot ingame to visual the issue.)
[//]: # (Write your tickets according to the format:)
[//]: # ([Quest][Azuremyst Isle] Red Snapper - Very Tasty!)
[//]: # ([NPC] Magistrix Erona)
[//]: # ([Spell][Mage] Fireball)
[//]: # ([Npc][Drop] Ghostclaw Lynx)
[//]: # ([Web] Armory doesnt work)
[//]: # (To find server revision type `.server info` command in the game chat.)

**Description**: Game doesn't teleport player to nearest/available spirit healer when base he is ressurecting at is taken.

**Current behaviour**: If you are dead and enemy faction takes base you are ressurecting at, you don't teleport to the nearest available Spirit Healer of your faction. It makes it quite hard to respawn when all 4 bases are being taken over on EotS.

EDIT: Worth noticing that it might be related to sometimes not being able to pick up enemy insignia. Maybe if your body is picked up game teleports you no problem.

**Expected behaviour**: If base you are ressurecting at gets taken over by enemy faction, you should get teleported to the nearest available spirit healer.

**Server Revision**: 3277

**Comment by tsuone** [comment]
@Wolffenstein can we get this fixed?

**Comment by tsuone** [comment]
@Wolffenstein Seems to be fixed, did u do it?
