### ISSUE TITLE
[Dungeon][Magister's terrace] Vexallus adds

### ISSUE THREAD

**Issue by NatsumeLily** [Atlantiss/NetherwingBugtracker#6695]
[//]: # (Enclose links to things related to the bug using http://wowhead.com or any other TBC database.)
[//]: # (You can use screenshot ingame to visual the issue.)
[//]: # (Write your tickets according to the format:)
[//]: # ([Quest][Azuremyst Isle] Red Snapper - Very Tasty!)
[//]: # ([NPC] Magistrix Erona)
[//]: # ([Spell][Mage] Fireball)
[//]: # ([Npc][Drop] Ghostclaw Lynx)
[//]: # ([Web] Armory doesnt work)
[//]: # (To find server revision type `.server info` command in the game chat.)

**Description**: 
Vexallus will spawn Pure Energy adds every time his health drops 15% and starts to AoE the entire party at around 20% health. These adds must be taken down immediately, otherwise they will start AoEing the entire party for ~2k each.

When the adds are killed, the player who killed the add gains "Energy Feedback", a debuff that causes 300 Arcane damage per second, but also increases all damage dealt by 50% (this debuff can stack multiple times, renewing its timer on application, increasing both the damage taken and the damage increase buff). Allowing too many stacks of the debuff to build up on a single player will likely kill them if the healer can not keep up, so it is best to spread them out among the tank and DPS'ers, or otherwise. (See: Sample Group). 

**Current behaviour**:
The debuff that gets applied can not be removed with rogues cloak of shadows.
The damage the adds do is arcane damage but can't be resisted with cloak of shadows.

**Expected behaviour**: 
The debuff should be removed with cloak of shadows.

> For groups with a Rogue, the Rogue can use [Cloak of Shadows] to remove the debuff.

The damage the sparks do should be resistible with arcane resist or cloak of shadows ( just the aoe damage they do, not the debuff ).

>  Stacking Arcane resist will help immensely, although high DPS must be maintained, and quick bursts of 5K-6K damage are very common. The damage portion of the debuff from killing an add is not resistible in part or whole. Arcane Protection Potions will significantly ease the load on your healers.

**Server Revision**: 3277

**Comment by The14me** [comment]
''Need Research'' is for lack of proof, but a good ticket.

**Comment by NatsumeLily** [comment]
https://wow.gamepedia.com/index.php?title=Vexallus&oldid=1657086 - From 2008.

"Vexallus will spawn Pure Energy adds every time his health drops 15% and starts to AoE the entire party at around 20% health. These adds must be taken down immediately, otherwise they will start AoEing the entire party for ~2k each.

When the adds are killed, the player who killed the add gains "Energy Feedback", a debuff that causes 300 Arcane damage per second, but also increases all damage dealt by 50% (this debuff can stack multiple times, renewing its timer on application, increasing both the damage taken and the damage increase buff). Allowing too many stacks of the debuff to build up on a single player will likely kill them if the healer can not keep up, so it is best to spread them out among the tank and DPS'ers, or otherwise. (See: Sample Group).

The fight is essentially a race against your healer's mana pool and maximum HPS (healing per second). As more and more debuffs pile up, it becomes harder and harder to keep everyone alive (similar to the combined Garottes in the Moroes fight). However, in order to kill Vexallus fast enough when he enrages, you must accumulate debuffs in order to increase your group's DPS (unless you substantially out-gear the encounter).

All damage dealt by Vexallus and the adds is Arcane (including his melee attack) and cannot be shield blocked or spell reflected. Stacking Arcane resist will help immensely, although high DPS must be maintained, and quick bursts of 5K-6K damage are very common. The damage portion of the debuff from killing an add is not resistible in part or whole. Arcane Protection Potions will significantly ease the load on your healers. "

"For groups with a Rogue, the Rogue can use [Cloak of Shadows] to remove the debuff."

**Comment by Wolffenstein** [comment]
Fixed in rev 3355.
