### ISSUE TITLE
[Dungeon][Magister's terrace] Trash mobs immune to distract

### ISSUE THREAD

**Issue by NatsumeLily** [Atlantiss/NetherwingBugtracker#6696]
[//]: # (Enclose links to things related to the bug using http://wowhead.com or any other TBC database.)
[//]: # (You can use screenshot ingame to visual the issue.)
[//]: # (Write your tickets according to the format:)
[//]: # ([Quest][Azuremyst Isle] Red Snapper - Very Tasty!)
[//]: # ([NPC] Magistrix Erona)
[//]: # ([Spell][Mage] Fireball)
[//]: # ([Npc][Drop] Ghostclaw Lynx)
[//]: # ([Web] Armory doesnt work)
[//]: # (To find server revision type `.server info` command in the game chat.)

**Description**: A lot of the trash in here should be susceptible to distract. *

**Current behaviour**: Almost all the mobs are immune to distract. ~~Most are immune to blind. Some are immune to sap.~~

**Expected behaviour**: The humanoids should not be immune to distract ~~, blind, or sap.~~ The Sentinels should be immune to those CCs.

[Sentinel is shown to be immune to distract](https://youtu.be/Mqdch5gVY18?t=325)
[Distract is used on a group](https://youtu.be/Mqdch5gVY18?t=443)
~~[When starting combat he blinds one of the mobs](https://youtu.be/Mqdch5gVY18?t=470)~~

**Server Revision**: 3277

**Comment by The14me** [comment]
All of these videos are way after TBC, so I'm not sure if that ever counts.Please try to find some proof's from TBC era.

**Comment by NatsumeLily** [comment]
All the links are from one video, it is indeed from wotlk but it still stands (somewhat).

Conflicting info from that time on the CCs, some sources say some are immune to everything but others say they can be polyed.

Common sense and the general status on distract is, if the target can be sapped then they shouldn't be immune to distract.

**Comment by Wolffenstein** [comment]
Fixed in rev 3358.
