### ISSUE TITLE
[Battleground] Render rate

### ISSUE THREAD

**Issue by wtRCH** [Atlantiss/NetherwingBugtracker#6697]
[//]: # (Enclose links to things related to the bug using http://wowhead.com or any other TBC database.)
[//]: # (You can use screenshot ingame to visual the issue.)
[//]: # (Write your tickets according to the format:)
[//]: # ([Quest][Azuremyst Isle] Red Snapper - Very Tasty!)
[//]: # ([NPC] Magistrix Erona)
[//]: # ([Spell][Mage] Fireball)
[//]: # ([Npc][Drop] Ghostclaw Lynx)
[//]: # ([Web] Armory doesnt work)
[//]: # (To find server revision type `.server info` command in the game chat.)

**Description**: Would be nice to increase player render rate on Battlegrounds like EOTS, WSG and AB.

**Current behaviour**: Decreased render rate.

**Expected behaviour**: Increase render rate to be able to target and see players on the other side of the Battleground.

**Server Revision**: 3277

**Comment by Evolvee** [comment]
is it possible in classic or retail? its around 200 now, could be 300 +-

**Comment by wtRCH** [comment]
@Evolvee It is like that on retail. You can see and target players on the other side of the battleground. Even on Alterac Valley.

**Comment by Wolffenstein** [comment]
Fixed in rev 3285.
