### ISSUE TITLE
Mechano-Lord Capacitus 2.4 patch Drop

### ISSUE THREAD

**Issue by Drainlock** [Atlantiss/NetherwingBugtracker#6699]
**Description**: 
https://www.wowhead.com/item=35582/schematic-rocket-boots-xtreme-lite
was added to the game in 2.4 patch
**Current behaviour**:
1 week passed an there are (as far I know) 0 engineers who can craft it
**Expected behaviour**: 
Should have 10% drop chance on normal (if there is engineer in group) and 20% on heroic from Mechano-Lord Capacitus (1st Boss in Mechanar)
**Server Revision**: 
3277

**Comment by Evolvee** [comment]
where did you get the %? the wowhead comment?

**Comment by Drainlock** [comment]
> where did you get the %? the wowhead comment?

This + private data bases, coz drop chance from wowhead calculated with all pre 2.4 patch kills + all kills where there where no engineer in group. Thats why it's so low.

**Comment by Evolvee** [comment]
my bad, it already is in game

**Comment by Evolvee** [comment]
try harder xd
