### ISSUE TITLE
[npc] Enraged Ravager

### ISSUE THREAD

**Issue by Sothanwow** [Atlantiss/NetherwingBugtracker#670]
**Description**: 
I have noticed a lot of [enraged ravagers](https://www.wowhead.com/npc=17527/enraged-ravager) around in places they shouldn't be at first I was going to report this just from the missing expedition quest but I have noticed that there are a few around places they should be. So to start with there shouldn't be any enraged ravagers on the path up to Zarakh or anywhere right by the spiders heres a video of that quest being done.
https://youtu.be/g1GdarYtAD4?t=129

https://imgur.com/a/1FvSmJX is a album with the enraged ravagers I found.
There are others around as well in places they shouldn't be I was having a hard time running around getting screenshots though without dieing but will add more as I see them. 
One other thing I notced they have a less movement then on live they are a lot stiffer.

**Current behaviour**:
To many Enraged Ravagers

**Expected behaviour**: 
Enraged ravagers in places they shouldn't be.
**Server Revision**: 
2060

**Comment by aresbrutus** [comment]
Please make sure to select the bugged mob and do .npc info command before you take a screenshot. That way I know exactly which mob has the issue and where to find him.

This issue will be fixed on one of the next updates.
