### ISSUE TITLE
Mage Fireball's DOT not being affected by spellpower

### ISSUE THREAD

**Issue by Musgante** [Atlantiss/NetherwingBugtracker#6700]
**Description**:  Since yesterday (02/03), my fireball's DOT stopped being affected by spell power. It used to do like 200-250 damage (dont really remember) per tick, now it's doing 22-25 damage per tick. I suspect if it had anything to do with me equiping the trinket Timbal's Focusing Crystal (from Magister Terrace Heroic, 3rd boss) for the first time (i got it that night). 
But some other mage told me his fireball also has only 22-25 DOT damage, so I'am getting really confused about what is causing this bug.

**Current behaviour**:
Fireball's DOT is not being affected by spell power
**Expected behaviour**: 
It has always been
**Server Revision**:

**Comment by Tereneckla** [comment]
That was a bug #6443
