### ISSUE TITLE
[Core] Mail being added to the back, not front, of mailboxes

### ISSUE THREAD

**Issue by aeturnum** [Atlantiss/NetherwingBugtracker#6701]
[//]: # (Enclose links to things related to the bug using http://wowhead.com or any other TBC database.)
[//]: # (You can use screenshot ingame to visual the issue.)
[//]: # (Write your tickets according to the format:)
[//]: # ([Quest][Azuremyst Isle] Red Snapper - Very Tasty!)
[//]: # ([NPC] Magistrix Erona)
[//]: # ([Spell][Mage] Fireball)
[//]: # ([Npc][Drop] Ghostclaw Lynx)
[//]: # ([Web] Armory doesnt work)
[//]: # (To find server revision type `.server info` command in the game chat.)

**Description**: 
Mail is being added on the wrong "end" of the mail list.

**Current behaviour**:
New mail is added behind existing mail.

Example (newer mail showing up under older mail):
![WoWScrnShot_030320_162500](https://user-images.githubusercontent.com/2303837/75832972-7a6c7200-5d6c-11ea-9d84-691477711eac.jpg)

**Expected behaviour**: 
New mail should be added in front of existing mail.

**Server Revision**: 
3282

**Comment by wtRCH** [comment]
It was happening in rev. 3277 too.

**Comment by aeturnum** [comment]
This seems fixed as of 3283? I got a piece of mail from the AH at the top of my mailbox.
