### ISSUE TITLE
[Quest] Chasing the Moonstone

### ISSUE THREAD

**Issue by Tereneckla** [Atlantiss/NetherwingBugtracker#6702]
[//]: # (Enclose links to things related to the bug using http://wowhead.com or any other TBC database.)
[//]: # (You can use screenshot ingame to visual the issue.)
[//]: # (Write your tickets according to the format:)
[//]: # ([Quest][Azuremyst Isle] Red Snapper - Very Tasty!)
[//]: # ([NPC] Magistrix Erona)
[//]: # ([Spell][Mage] Fireball)
[//]: # ([Npc][Drop] Ghostclaw Lynx)
[//]: # ([Web] Armory doesnt work)
[//]: # (To find server revision type `.server info` command in the game chat.)

**Description**: No failure set for quest.

**Current behaviour**: If you let Rizzle Sprysprocket get out of your view distance (~120 yards), she stops moving and spawns an endless mass of bombs.

**Expected behaviour**: Event should have a fail-state when she gets to far away and she yells "See? I've got the Southfury moonstone and there is not a thing you can do about it. So long!" and despawns.

You are then free to retry by going to the Moonstone again.

**Server Revision**: 3283

**Comment by danbopes** [comment]
@Tereneckla Does Rizzle say it also when despawning at the end?

**Comment by Tereneckla** [comment]
Only when she despawns because she got too far away.

**Comment by danbopes** [comment]
So she's just expected to despawn without saying anything at the end of the path she's on?

**Comment by Tereneckla** [comment]
At the end of the path she roots herself. If the player can't catch her then idk
So there's also no precedent of here reaching the path and despawning without the player getting to here.
