### ISSUE TITLE
[Battleground] Capping

### ISSUE THREAD

**Issue by tsuone** [Atlantiss/NetherwingBugtracker#6703]
[//]: # (Enclose links to things related to the bug using http://wowhead.com or any other TBC database.)
[//]: # (You can use screenshot ingame to visual the issue.)
[//]: # (Write your tickets according to the format:)
[//]: # ([Quest][Azuremyst Isle] Red Snapper - Very Tasty!)
[//]: # ([NPC] Magistrix Erona)
[//]: # ([Spell][Mage] Fireball)
[//]: # ([Npc][Drop] Ghostclaw Lynx)
[//]: # ([Web] Armory doesnt work)
[//]: # (To find server revision type `.server info` command in the game chat.)

**Description**: Problem happening while capping flag on Arathi Basin or tower on Alterac Valley.

**Current behaviour**: If player who is capping flag has shield on him (Power Word: Shield) or any sort of "Absorbtion" effect, you can't interrupt him capping it.

**Expected behaviour**: Player who got hit with "Absorbtion" effect on him while capping flag/tower on Battleground should get interrupted when taking damage that got absorbed.

**Server Revision**: 3283

**Comment by Wolffenstein** [comment]
Proof?

**Comment by wtRCH** [comment]
![image](https://user-images.githubusercontent.com/11255782/76090136-52268280-5fbb-11ea-9c01-fe854a752c15.png)

**Comment by tsuone** [comment]
Fixed
