### ISSUE TITLE
[Battleground][Arathi Basin] Flag Beams

### ISSUE THREAD

**Issue by tsuone** [Atlantiss/NetherwingBugtracker#6704]
**Description:** Beams over flags on Arathi Basin

**Current behaviour:** There are custom beams over flags on Arathi Basin

**Expected behaviour:** No beams on top of the flags on Arathi Basin which makes it harder to see whose base it is and if someone is ninja-capping it.

**Revision:** 3283

**Comment by wtRCH** [comment]
Either it is wrong aura or effect or it is too small, because the beam effect sure was on the retail back then but not that small.

**Comment by Healweed** [comment]
The effect itself is small. Makes it harder to notice imo

**Comment by tsuone** [comment]
![image](https://user-images.githubusercontent.com/11255782/76555981-f8c9c200-6498-11ea-9c9a-cd12f81b2af0.png)

**Comment by Wolffenstein** [comment]
Fixed in rev 3536.
