### ISSUE TITLE
[Raid] Hyjal - Azgalor Cleave

### ISSUE THREAD

**Issue by Firroth** [Atlantiss/NetherwingBugtracker#6706]
**Current behaviour**:
He casts cleave too often (2s cd?), and does it even if only Tank is in front of him.

Proof of 2s cleave cooldown:
![Screenshot_1](https://user-images.githubusercontent.com/43505196/75938930-420e8600-5e89-11ea-9d25-e4e0180dbabb.png)

Proof that cleave shouldn't be used, if only Tank is in front of him:
![Screenshot_2](https://user-images.githubusercontent.com/43505196/75938992-64a09f00-5e89-11ea-93aa-3eff62ae38aa.png)

https://wowwiki.fandom.com/wiki/Azgalor_(tactics)
https://www.youtube.com/watch?v=YmcQI6Jdnvs&pbjreload=10

**Expected behaviour**: 
Cleave should have longer cd (not 2s), and he shouldn't use cleave if there is only Tank in front of him.

**Server Revision**:

**Comment by NatsumeLily** [comment]
Was there any pets attacking? Seems pets have broke again and like standing to far in the mobs hitbox. Which can cause them to get hit by cleaves or cause this problem you're seeing.

**Comment by Firroth** [comment]
I think they did, since only 1-2 ppl dps doomguard. But as to their position I can't say for sure where they stood, but for sure not in front of me at least.

**Comment by Wolffenstein** [comment]
Wowwiki bullshit, he casts it even if there's just tank on retail.

The cleave cooldown is correct as well, it's between 2s and 12s.
