### ISSUE TITLE
[NPC][Object][Terokkar Forest] Terokk, Ancient Skull Pile

### ISSUE THREAD

**Issue by Illariaxe** [Atlantiss/NetherwingBugtracker#6709]
[//]: # (Enclose links to things related to the bug using http://wowhead.com or any other TBC database.)
[//]: # (You can use screenshot ingame to visual the issue.)
[//]: # (Write your tickets according to the format:)
[//]: # ([Quest][Azuremyst Isle] Red Snapper - Very Tasty!)
[//]: # ([NPC] Magistrix Erona)
[//]: # ([Spell][Mage] Fireball)
[//]: # ([Npc][Drop] Ghostclaw Lynx)
[//]: # ([Web] Armory doesnt work)
[//]: # (To find server revision type `.server info` command in the game chat.)

**Description**: Object for summon Terokk doesn't run event.

**Current behaviour**: There is nothing happens when someone from group has https://www.wowhead.com/item=32720/time-lost-offering#comments for summon Terokk and he tries to summon it, using it at Ancient Skull Pile. Dialogue appears for starting that event, but it doesn't start for every party's player.

**Expected behaviour**:  When you have https://www.wowhead.com/item=32720/time-lost-offering#comments you can summon Terokk at Ancient Skull Pile in Terokkar Forest.

**Server Revision**:

**Comment by Wolffenstein** [comment]
If nothing happened then the player probably did not have Adversarial Blood quest completed (which is a requirement).

Ancient Skull Pile will no longer offer that gossip option if it happens after revision 3286.

**Comment by Illariaxe** [comment]
But I've completed this quest Adversarial Blood and I stand now at the quest Terokk's Downfall - last stage of this chain but I can't start it. And even our party member, who has completed it all already can't start it. We tried to start it even with GM Smaily, but nothing happened and he said us to create this report.

**Comment by The14me** [comment]
Confirmed (it's still bugged). After this rev 3286 I can't ever see the gossip option anymore (added and completed ''Adversarial Blood'' before that). Before that rev, I added and completed the same quest...seen the gossip, but the mob didn't spawn as the report owner say.

**Comment by Wolffenstein** [comment]
Sorry, will be fixed in rev 3287.

**Comment by The14me** [comment]
Rev 3289 -rip again.

**Comment by Wolffenstein** [comment]
3292
