### ISSUE TITLE
[Quest][Stormwind] Tome of Divinity

### ISSUE THREAD

**Issue by Buggyswires** [Atlantiss/NetherwingBugtracker#671]
[//]: # (Enclose links to things related to the bug using http://wowhead.com or any other TBC database.)
[//]: # (You can use screenshot ingame to visual the issue.)
[//]: # (Write your tickets according to the format:)
[//]: # ([Quest][Azuremyst Isle] Red Snapper - Very Tasty!)
[//]: # ([NPC] Magistrix Erona)
[//]: # ([Spell][Mage] Fireball)
[//]: # ([Npc][Drop] Ghostclaw Lynx)
[//]: # ([Web] Armory doesnt work)

**Description**: 
[Quest][Stormwind] Tome of Divinity not obtainable

**Current behaviour**:
Not obtainable after you do the prequest from Brother Wilhelm in Goldshire. I am level 18  and cannot pick up the quest (tried from level 12-18)
Duthorian Rall shows the yellow exclamation mark, but only greets you without offering the quest

**Expected behaviour**: 
You should be able to get the quest at level 12

**Server Revision**:

**Comment by Buggyswires** [comment]
![wow 2018-09-27 13-46-47](https://user-images.githubusercontent.com/43603807/46143987-06b36500-c25c-11e8-899f-1a15db944cd6.jpg)

**Comment by tehfriz** [comment]
Here is a video of what happened when I tried to turn in the quest. https://www.youtube.com/watch?v=IrgrC6wZzmA&feature=youtu.be

**Comment by Shanghi** [comment]
This should be fixed in revision 2121. It should also be one of those quests you accept and complete on the same window instead of showing an extra part with empty text, but you may need to delete the cache to see that properly.
