### ISSUE TITLE
[Quest] Fish in a Bucket [Misc]

### ISSUE THREAD

**Issue by The14me** [Atlantiss/NetherwingBugtracker#6710]
**Current behavior**:  [Fish in a Bucket](https://classic.wowhead.com/quest=5421/fish-in-a-bucket) can be done only once.
Think it bugs out with 2.4 patch.
**Expected behavior**: 
It must be [repeatable](https://classic.wowhead.com/quest=5421/fish-in-a-bucket#comments:id=2968151:reply=1252960) as before.
**Server Revision**: 
3286

**Comment by duzyizly** [comment]
Please fix before fraish - it's mandatory leveling quest ^^
