### ISSUE TITLE
Free faction change service not working.

### ISSUE THREAD

**Issue by Tayeni** [Atlantiss/NetherwingBugtracker#6711]
[//]: # (Enclose links to things related to the bug using http://wowhead.com or any other TBC database.)
[//]: # (You can use screenshot ingame to visual the issue.)
[//]: # (Write your tickets according to the format:)
[//]: # ([Quest][Azuremyst Isle] Red Snapper - Very Tasty!)
[//]: # ([NPC] Magistrix Erona)
[//]: # ([Spell][Mage] Fireball)
[//]: # ([Npc][Drop] Ghostclaw Lynx)
[//]: # ([Web] Armory doesnt work)
[//]: # (To find server revision type `.server info` command in the game chat.)

**Description**: The service of free faction change is currently not working from what I can tell. I've tried transfering from horde to alliance but i get stuck when I finish customizing the character and press the "Change faction" button. After that i get a pop up message : Invalid Information given.
I have tried relogging, left my arena team and guild, but it did not help

**Current behaviour**: After pressing the change faction button, pop up message "Invalid Information given" appears

**Expected behaviour**: Get the transfer :D
![Untitled](https://user-images.githubusercontent.com/11783699/76116500-6635a880-5fea-11ea-8931-f2b44a15c1db.png)

**Server Revision**:

**Comment by GMThunderan** [comment]
Made sure:
-No other (horde) toons on account
-Not in a guild
-Not in a arena team
-No mail
-No auctions
... can't think of anything else.

**Comment by Healweed** [comment]
I do see WoW opened up on your screenshot. If you are logged in on your while you're trying to do the transfer just...close it :D

**Comment by Tayeni** [comment]
I am not logged in on any of the accounts I have, just the client was turned on.
Doesn't work with client closed either

**Comment by Emtec** [comment]
@Tayeni I had no problem with **Faction Change** on your account. I transfered your character to the Alliance (race Human) and gave you **Appearence Change** on your account.  (check your account on the website).

**Comment by Tayeni** [comment]
Thank you for the assistance, I have no idea what was the issue then really
