### ISSUE TITLE
[Quest] The Opening of the Dark Portal

### ISSUE THREAD

**Issue by tsu-1** [Atlantiss/NetherwingBugtracker#6712]
[//]: # (Enclose links to things related to the bug using http://wowhead.com or any other TBC database.)
[//]: # (You can use screenshot ingame to visual the issue.)
[//]: # (Write your tickets according to the format:)
[//]: # ([Quest][Azuremyst Isle] Red Snapper - Very Tasty!)
[//]: # ([NPC] Magistrix Erona)
[//]: # ([Spell][Mage] Fireball)
[//]: # ([Npc][Drop] Ghostclaw Lynx)
[//]: # ([Web] Armory doesnt work)
[//]: # (To find server revision type `.server info` command in the game chat.)

**Description**: Quest giver doesn't finish the quest.

**Current behaviour**: If you complete the quest and try to hand in it to the guy who finishes it, it doesn't work. You have to leave the party and go in to BM to finish the quest.

**Expected behaviour**: Should be able to finish the quest in the same ID, without leaving the party or anything.

**Server Revision**: 3286

**Comment by The14me** [comment]
Duplicate https://github.com/Atlantiss/NetherwingBugtracker/issues/2914

**Comment by tsuone** [comment]
#2914 was closed but bug still appears ingame, please reopne @The14me

**Comment by Godmatik** [comment]
Unable to reproduce.
The linked report mentions it can't be completed in heroic, but I was able to do it just fine and turn it in after.
