### ISSUE TITLE
[Quest] Arcane Disturbances

### ISSUE THREAD

**Issue by wtRCH** [Atlantiss/NetherwingBugtracker#6714]
[//]: # (Enclose links to things related to the bug using http://wowhead.com or any other TBC database.)
[//]: # (You can use screenshot ingame to visual the issue.)
[//]: # (Write your tickets according to the format:)
[//]: # ([Quest][Azuremyst Isle] Red Snapper - Very Tasty!)
[//]: # ([NPC] Magistrix Erona)
[//]: # ([Spell][Mage] Fireball)
[//]: # ([Npc][Drop] Ghostclaw Lynx)
[//]: # ([Web] Armory doesnt work)
[//]: # (To find server revision type `.server info` command in the game chat.)

**Description**: Can't use the item near/in the pond.

**Current behaviour**: You have to be in one, specified location to use the item.

**Expected behaviour**: You should be able to use the item in other places in the underground pond too.

**Server Revision**: 3286

**Comment by The14me** [comment]
Work just fine to me 
https://streamable.com/eqa3c
https://streamable.com/1dq3a
https://youtu.be/CZz7hYB1bd0?t=29

**Comment by wtRCH** [comment]
How is it working fine for you if it clearly doesn't on the video?
