### ISSUE TITLE
[Class] Warlock [Dungeon] Dire Maul West [Boss] Immol'thar

### ISSUE THREAD

**Issue by The14me** [Atlantiss/NetherwingBugtracker#6715]
**Current behaviour**: You can't turn off/remove force shield around Immol'thar.
So every warlock who wanna take the mount....cant.

**Expected behaviour**: Once u kill all the mobs around all five pylons they must ''Turn off''.Once every pylon is off...shield must then off too.
https://wow.gamepedia.com/Immol%27thar
https://classic.wowhead.com/guides/dire-maul-west-classic-dungeon-strategy
https://www.youtube.com/watch?v=uVT1hnEcV1Q (gonna do the job)

General speaking DM: W and the other's need remark from 0, but that gonna take some time.A temporary fix will do the job too (Disable the force shield or something)

**Server Revision**: 
3287

**Comment by MisaHack** [comment]
@Evolvee - we cleared whole Dire Maul West today and yes - this is still an issue in this server "You can't turn off/remove force shield around Immol'thar." as it is mentioned above.

**Comment by MisaHack** [comment]
@The14me @Evolvee any progression on this one?

**Comment by MisaHack** [comment]
@The14me @Evolvee @Wolffenstein @Emtec - we still have quests from Dire Maul to finish.
If would be nice to know is there fix on the way?

**Comment by csffonseca** [comment]
just had this happen today, but we got to kill immol'thar. When we tried to get out of its little area, we couldnt, seems like the collider for the barrier came back somehow

**Comment by Godmatik** [comment]
Duplicate - Dire Maul right now is stock and needs a full rework, it is on Wolf's to-do list.
