### ISSUE TITLE
[SWP][Kalecgos] Dragon can be kitet

### ISSUE THREAD

**Issue by Stogi7789** [Atlantiss/NetherwingBugtracker#6716]
[//]: # (Enclose links to things related to the bug using http://wowhead.com or any other TBC database.)
[//]: # (You can use screenshot ingame to visual the issue.)
[//]: # (Write your tickets according to the format:)
[//]: # ([Quest][Azuremyst Isle] Red Snapper - Very Tasty!)
[//]: # ([NPC] Magistrix Erona)
[//]: # ([Spell][Mage] Fireball)
[//]: # ([Npc][Drop] Ghostclaw Lynx)
[//]: # ([Web] Armory doesnt work)
[//]: # (To find server revision type `.server info` command in the game chat.)

**Description**: 
The Dragon Kalecgos can be kitet in a circle by anybody at enrage.
**Current behaviour**:
Dragon can be kitet. When enraged (under 10%), you can just run in a circle around the platform and never get hit by the dragon. Combination of hitbox, meleeswing and his spells make it impossible for him to catch up to a player. So it is possible to avoid the soft enrage completly after killing the demon.
**Expected behaviour**: 
I assume a boss should not be kiteable
**Server Revision**: 
Last seen on Thursday -> ~ [3284]

**Comment by Wolffenstein** [comment]
Please retest.
