### ISSUE TITLE
[Battleground][Quests] Alterac Valley

### ISSUE THREAD

**Issue by tsu-1** [Atlantiss/NetherwingBugtracker#6717]
[//]: # (Enclose links to things related to the bug using http://wowhead.com or any other TBC database.)
[//]: # (You can use screenshot ingame to visual the issue.)
[//]: # (Write your tickets according to the format:)
[//]: # ([Quest][Azuremyst Isle] Red Snapper - Very Tasty!)
[//]: # ([NPC] Magistrix Erona)
[//]: # ([Spell][Mage] Fireball)
[//]: # ([Npc][Drop] Ghostclaw Lynx)
[//]: # ([Web] Armory doesnt work)
[//]: # (To find server revision type `.server info` command in the game chat.)
### Alterac Valley Graveyards

**Description**: Not getting credit.

**Current behaviour**: When you assault a graveyard in Alterac Valley you don't get credit towards the quest.

**Expected behaviour**: Assaulting graveyard should give credit.

**Server Revision**: 3289

### Capture a Mine

**Description**: Not getting credit.

**Current behaviour**: When you captured a mine, either horde or neutral in Alterac Valley you don't get credit towards the quest.

**Expected behaviour**: Capturing mine should give credit.

**Server Revision**: 3289

**Comment by Godmatik** [comment]
Closing - will consolidate all outstanding AV issues into one thread now.
