### ISSUE TITLE
[Item][Spell] Flame Wrath buff has no scaling

### ISSUE THREAD

**Issue by Silbotronic** [Atlantiss/NetherwingBugtracker#6718]
[//]: # (Enclose links to things related to the bug using http://wowhead.com or any other TBC database.)
[//]: # (You can use screenshot ingame to visual the issue.)
[//]: # (Write your tickets according to the format:)
[//]: # ([Quest][Azuremyst Isle] Red Snapper - Very Tasty!)
[//]: # ([NPC] Magistrix Erona)
[//]: # ([Spell][Mage] Fireball)
[//]: # ([Npc][Drop] Ghostclaw Lynx)
[//]: # ([Web] Armory doesnt work)
[//]: # (To find server revision type `.server info` command in the game chat.)

**Current behaviour**: The buff granted by Flame Wrath's proc doesn't scale with spell damage. 

**Expected behaviour**: The buff should scale with 100% of spell damage, according to several comments.
https://www.wowhead.com/item=11809/flame-wrath#comments

**Server Revision**: 3289

**Comment by Wolffenstein** [comment]
Fixed in rev 3356.
