### ISSUE TITLE
[NPC] Death Knight Soulbearer

### ISSUE THREAD

**Issue by drewk8** [Atlantiss/NetherwingBugtracker#6719]
**Description**: 
Death Knight Soulbearer currently spawns as a rare NPC in the Eastern Plaguelands in Northdate

**Current behavior**:
Said NPC spawns, can be killed, drops no loot.

**Expected behavior**: 
Should not spawn? Data i found online is just conflicting. For example:
According to: https://wow.gamepedia.com/Death_Knight_Soulbearer it was added in 4.0.6
According to: https://classic.wowhead.com/npc=10818/death-knight-soulbearer, it was added in 1.13.2.30406
If this is not a valid issue, just close it.

**Server Revision**: 
3289

**Comment by The14me** [comment]
More like 4.0 added according to this
https://ptr.wowhead.com/npc=10818/death-knight-soulbearer#comments

**Comment by Evolvee** [comment]
I think the NPC never made it past vanilla beta xd i added it for keks and lulz because it was noted in some retail book.
