### ISSUE TITLE
[ITEM][Vial of the Sunwell] Holy energy not stacking for HOTS

### ISSUE THREAD

**Issue by oso5876** [Atlantiss/NetherwingBugtracker#6720]
[//]: # (Enclose links to things related to the bug using http://wowhead.com or any other TBC database.)
[//]: # (You can use screenshot ingame to visual the issue.)
[//]: # (Write your tickets according to the format:)
[//]: # ([Quest][Azuremyst Isle] Red Snapper - Very Tasty!)
[//]: # ([NPC] Magistrix Erona)
[//]: # ([Spell][Mage] Fireball)
[//]: # ([Npc][Drop] Ghostclaw Lynx)
[//]: # ([Web] Armory doesnt work)
[//]: # (To find server revision type `.server info` command in the game chat.)

**Description**: 
https://wowwiki.fandom.com/wiki/Vial_of_the_Sunwell

**Current behaviour**:
Vial is only gaining holy energy stacks from direct-healing even though it is not specified like other items that are direct only.

**Expected behaviour**: 
Vial should get getting stacks of holy energy from hots, but is only working with direct healing spells.

**Server Revision**: 
3289 hash 86962fab0c1c

**Comment by Wolffenstein** [comment]
Fixed in rev 3294.

**Comment by oso5876** [comment]
Still not working in revision 3295

**Comment by Wolffenstein** [comment]
will be fixed after restart
