### ISSUE TITLE
[SWP][Felmyst] Enrage bug

### ISSUE THREAD

**Issue by eri1997** [Atlantiss/NetherwingBugtracker#6722]
[//]: # (Enclose links to things related to the bug using http://wowhead.com or any other TBC database.)
[//]: # (You can use screenshot ingame to visual the issue.)
[//]: # (Write your tickets according to the format:)
[//]: # ([Quest][Azuremyst Isle] Red Snapper - Very Tasty!)
[//]: # ([NPC] Magistrix Erona)
[//]: # ([Spell][Mage] Fireball)
[//]: # ([Npc][Drop] Ghostclaw Lynx)
[//]: # ([Web] Armory doesnt work)
[//]: # (To find server revision type `.server info` command in the game chat.)

**Description**: This was this wednesday (march 4) if anything has changed since then. Felmyst enrages at 1% in the air causes the dmg going on by the spells in the ground to also be increased which it shouldn't. You can see in this video near the end that the aura still ticks for 1k after the enrage.
https://www.youtube.com/watch?v=pcv5LlawB1A

**Current behaviour**: Enrage in the air -> wipe because the spells tick for unhealable dmg

**Expected behaviour**: Enrage in the air -> spell dmg is the same while he is in the air.

**Server Revision**:

**Comment by Wolffenstein** [comment]
Fixed in rev 3294.
