### ISSUE TITLE
[SWP][Felmyst][Spell] Encapsulate unresistable

### ISSUE THREAD

**Issue by eri1997** [Atlantiss/NetherwingBugtracker#6723]
**Description**:  You should be able to get partial resists very frequently on encapsulate with arcane resistance.
https://www.youtube.com/watch?v=pcv5LlawB1A
You can see the priest getting a lot of partial resists on felmyst fight.

ALSO sometimes it seems like we get ground phases without any encapsulates at all not sure if thats supposed to happen but probably not.

**Current behaviour**: You can't get any partial resists 

**Expected behaviour**:  Encapsulate can be partially resisted 

**Server Revision**:

**Comment by Wolffenstein** [comment]
Fixed in rev 3294.
