### ISSUE TITLE
[SPELL][NPC] Haunted - Darrowshire Poltergeist

### ISSUE THREAD

**Issue by drewk8** [Atlantiss/NetherwingBugtracker#6724]
**Description**: 
When picking up Redpath's Shield of Davil's Libram for the quest Heroes of Darrowshire, a curse is cast upon you (Haunted). It periodically spawns a companion called Darrowshire Poltergeist that tells random lore.

**Current behavior**:
Companion is spawned as a <Player's> "Minion" and aggroes mobs, can be attacked by mobs.

**Expected behavior**: 
According to: https://classic.wowhead.com/spell=18347/haunted as of 2.0.12 companion was marked as <Player's> Guardian, not Minion. 

**Server Revision**: 
3289

**Comment by Godmatik** [comment]
![zasdasdas](https://github.com/user-attachments/assets/8e2470ef-167d-4ebf-8249-0716de9c70c5)

Looks like it was changed late in TBC.
