### ISSUE TITLE
[Other] PvP Durability

### ISSUE THREAD

**Issue by tsuone** [Atlantiss/NetherwingBugtracker#6727]
[//]: # (Enclose links to things related to the bug using http://wowhead.com or any other TBC database.)
[//]: # (You can use screenshot ingame to visual the issue.)
[//]: # (Write your tickets according to the format:)
[//]: # ([Quest][Azuremyst Isle] Red Snapper - Very Tasty!)
[//]: # ([NPC] Magistrix Erona)
[//]: # ([Spell][Mage] Fireball)
[//]: # ([Npc][Drop] Ghostclaw Lynx)
[//]: # ([Web] Armory doesnt work)
[//]: # (To find server revision type `.server info` command in the game chat.)

**Description**: Durability loss in PvP combat.

**Current behaviour**: When you get killed on battleground in PvP combat, you loss durability.

**Expected behaviour**: You shouldn't lose durability in any PvP combat.

**Server Revision**: 3289

**Comment by Wolffenstein** [comment]
Fixed in rev 3351.
