### ISSUE TITLE
[Party] Instance group

### ISSUE THREAD

**Issue by tsu-1** [Atlantiss/NetherwingBugtracker#6728]
[//]: # (Enclose links to things related to the bug using http://wowhead.com or any other TBC database.)
[//]: # (You can use screenshot ingame to visual the issue.)
[//]: # (Write your tickets according to the format:)
[//]: # ([Quest][Azuremyst Isle] Red Snapper - Very Tasty!)
[//]: # ([NPC] Magistrix Erona)
[//]: # ([Spell][Mage] Fireball)
[//]: # ([Npc][Drop] Ghostclaw Lynx)
[//]: # ([Web] Armory doesnt work)
[//]: # (To find server revision type `.server info` command in the game chat.)

**Description**: If you join to the party or raid group while in the instance (battleground) group, you get double messages displayed in your chat.

**Current behaviour**: Joining party or raid group while on the battleground kicks you out of your instance (battleground) group and if not you get double messages displayed in your chat.
![image](https://user-images.githubusercontent.com/11255782/76239627-2f51d380-6232-11ea-8078-87b5b5c93230.png)

**Expected behaviour**: Should left you in the battleground group with an access to the chat under "/bg" and access to the raid or party under "/r" and "/p" - or any better solution like not being able to join other party/group while in the battleground.

**Server Revision**: 3289

**Comment by Godmatik** [comment]
Was fixed last year
