### ISSUE TITLE
[quest] [arathi highlands] Attack on the tower

### ISSUE THREAD

**Issue by tinkzorg** [Atlantiss/NetherwingBugtracker#673]
[//]: # (Enclose links to things related to the bug using http://wowhead.com or any other TBC database.)
[//]: # (You can use screenshot ingame to visual the issue.)
[//]: # (Write your tickets according to the format:)
[//]: # ([Quest][Azuremyst Isle] Red Snapper - Very Tasty!)
[//]: # ([NPC] Magistrix Erona)
[//]: # ([Spell][Mage] Fireball)
[//]: # ([Npc][Drop] Ghostclaw Lynx)
[//]: # ([Web] Armory doesnt work)

**Description**: The quest items are not where they're supposed to be.

**Current behaviour**: Currently, one quest item is gotten from the first chest you encounter while climbing the tower, while the next chest contains the remaining two quest items.

**Expected behaviour**:  Each chest should contain one of the three quest items.

**Server Revision**: 2060

**Comment by Shanghi** [comment]
This should be fixed in revision 2121.
