### ISSUE TITLE
[Battleground] Battlemasters

### ISSUE THREAD

**Issue by tsuone** [Atlantiss/NetherwingBugtracker#6730]
[//]: # (Enclose links to things related to the bug using http://wowhead.com or any other TBC database.)
[//]: # (You can use screenshot ingame to visual the issue.)
[//]: # (Write your tickets according to the format:)
[//]: # ([Quest][Azuremyst Isle] Red Snapper - Very Tasty!)
[//]: # ([NPC] Magistrix Erona)
[//]: # ([Spell][Mage] Fireball)
[//]: # ([Npc][Drop] Ghostclaw Lynx)
[//]: # ([Web] Armory doesnt work)
[//]: # (To find server revision type `.server info` command in the game chat.)

**Description**: There are no ongoing battlefield instances displayed in Battlemasters menu.

**Current behaviour**: Ongoing battlefield instances are not displayed in battlematers menu.

**Expected behaviour**: Ongoing Battlefield instances should be displayed in battlemasters menu.

**Server Revision**: 3289

**Comment by Wolffenstein** [comment]
Fixed in rev 3352.
