### ISSUE TITLE
[Spell][Warlock] Summon Voidwalker

### ISSUE THREAD

**Issue by Sememitnr** [Atlantiss/NetherwingBugtracker#6733]
[//]: # (Enclose links to things related to the bug using http://wowhead.com or any other TBC database.)
[//]: # (You can use screenshot ingame to visual the issue.)
[//]: # (Write your tickets according to the format:)
[//]: # ([Quest][Azuremyst Isle] Red Snapper - Very Tasty!)
[//]: # ([NPC] Magistrix Erona)
[//]: # ([Spell][Mage] Fireball)
[//]: # ([Npc][Drop] Ghostclaw Lynx)
[//]: # ([Web] Armory doesnt work)
[//]: # (To find server revision type `.server info` command in the game chat.)

**Description**: 
When I summon Voidwalker and then want to get it on my fly mount and fly a bit further, when I land the Woidwalker dissapear

**Current behaviour**:
Woidwalker dissapear after landing and dismount from fly mount

**Expected behaviour**: 
Voidwalker should not to dissapear after summoning him until death or dissmis him

**Server Revision**: 
3289

**Comment by The14me** [comment]
Maybe related https://github.com/Atlantiss/NetherwingBugtracker/issues/5424

**Comment by veekk** [comment]
#5972

**Comment by The14me** [comment]
Duplicate https://github.com/Atlantiss/NetherwingBugtracker/issues/5424
