### ISSUE TITLE
Windy clouds that are unreachable

### ISSUE THREAD

**Issue by VeritassNW** [Atlantiss/NetherwingBugtracker#6734]
[[//]:](url) # (Enclose links to things related to the bug using http://wowhead.com or any other TBC database.)
[//]: # https://ezgif.com/jpg-to-webp/ezgif-2-80b0f98b145a.png   https://ezgif.com/jpg-to-webp/ezgif-2-0b0cbca320b2.png  https://ezgif.com/jpg-to-webp/ezgif-2-0289603d5553.png
[//]: # (Write your tickets according to the format:)
[//]: # Windy Clouds out of reach and dont pat close enough to land
[//]: # ([NPC] Windy Clouds

**Current behaviour**:
Windy Clouds dont pat close to land. These clouds are always up because no one can harvest them. Ive spent hours trying to find every possible location that i can harvest them none will work.  

**Expected behaviour**: 
They need to be closer to the land masses they patrol.

**Server Revision**:

**Comment by VeritassNW** [comment]
https://wowwiki.fandom.com/wiki/Windy_Cloud please see where it said there are 6 and they were all flixed in 2.4.2 to be reachable

**Comment by Evolvee** [comment]
fixed in next rev
