### ISSUE TITLE
[NPC][Spell] Brutallus Burn

### ISSUE THREAD

**Issue by Tankdiehutte** [Atlantiss/NetherwingBugtracker#6735]
**Description**: The last big tick of the Burn of Brutallus doesnt happen.
https://www.wowhead.com/spell=45141/burn

**Current behaviour**: Burn debuff of Brutallus ticks normal but when running sometimes there is no 6,2k tick 

**Expected behaviour**: The first 10 ticks will tick for 100, the next 11 will tick for 200, then 400 for 11 more, 800 for 11 more, 1600 for 11 more and finally the last six ticks will do 3200 and the very last tick will do 6200.
(https://wowwiki.fandom.com/wiki/Brutallus)

**Server Revision**: 3289

**Comment by Wolffenstein** [comment]
Fixed in rev 3308.
