### ISSUE TITLE
[Enchant] Weapon - Crusader

### ISSUE THREAD

**Issue by Tankdiehutte** [Atlantiss/NetherwingBugtracker#6736]
**Description**: The Enchant gives too much strength for lvl 70 characters

**Current behaviour**: A level 70 Character gets 100 strength but correct healing.

![WoWScrnShot_031020_174510](https://user-images.githubusercontent.com/56139988/76338498-0f391780-62f9-11ea-8c5f-5f79055ba729.jpg)

**Expected behaviour**: The enchant should give only 60 strength for lvl 70 and 100 strength for lvl 60 characters. https://wowwiki.fandom.com/wiki/Enchant_Weapon_-_Crusader

**Server Revision**: 3289

**Comment by The14me** [comment]
https://classic.wowhead.com/item=16252/formula-enchant-weapon-crusader#comments:id=22461:reply=2634 Confirm

**Comment by AWIDIUS** [comment]
Its just tooltip, Strength gain should be 60.

**Comment by AWIDIUS** [comment]
Or atleast I had one weapon with crusader back then on NW and it worked correctly. Tooltip was wrong, but strength gain correct.

**Comment by Tereneckla** [comment]
Just tbc being tbc. Buffs and debuffs don't show changes because of talents/bonus damage or healing or anything
