### ISSUE TITLE
[Suggestion][RP][Fishing] Accelerated Day/Night Cycle

### ISSUE THREAD

**Issue by DaedalusMachina007** [Atlantiss/NetherwingBugtracker#6737]
**Description**: 
Requesting Acclerated Day/Night Cycle be implemented.  Kinda lame to always login and have it always be only day/night depending on what time of day a person plays.

**Current behaviour**:
1 hour WoW game time = 1 hour IRL (real world) time

**New/Requested behaviour**: 
1 hour WoW Game Time = 5 mins IRL (real world) time

This is a 5x increase in day/night cycle speed.  This greatly helps with stuff primarily like Fishing (certain pools are active at certain times of day/night) as well as adding some variety/flavor to the world (for that RP goodness that @Evolvee loves so much).

This allows for 40 minutes IRL (real world) to equal an entire 8 hour in-game time cycle (enough to go from day to night or vice versa even depending on when you login).

I'm not sure of the wider ramifications of such a change or if it can be accomplished without significantly affecting existing game content/questing/etc.  Testing would be needed, but it may be easier to just do the change and get a gauge on how players react to it since the change is (mostly) cosmetic for any players who don't Fish.

**Server Revision**: 
3289

**Comment by Evolvee** [comment]
most likely not gonna happen

1) custom
2) would bring problems
3) problems not worth the "possitives" if there are any?
