### ISSUE TITLE
[Spell][Druid] Nature's Swiftness

### ISSUE THREAD

**Issue by tsuone** [Atlantiss/NetherwingBugtracker#6738]
[//]: # (Enclose links to things related to the bug using http://wowhead.com or any other TBC database.)
[//]: # (You can use screenshot ingame to visual the issue.)
[//]: # (Write your tickets according to the format:)
[//]: # ([Quest][Azuremyst Isle] Red Snapper - Very Tasty!)
[//]: # ([NPC] Magistrix Erona)
[//]: # ([Spell][Mage] Fireball)
[//]: # ([Npc][Drop] Ghostclaw Lynx)
[//]: # ([Web] Armory doesnt work)
[//]: # (To find server revision type `.server info` command in the game chat.)

**Description**: No CD is shown after using.

**Current behaviour**: After using Nature's Swiftness on arena there is no cooldown displayed.

**Expected behaviour**: Should display cooldown.

**Server Revision**: 3289

**Comment by 4egito** [comment]
There is a video for that bug: https://drive.google.com/open?id=1nx3sM4tm9aBZzhszAy81rZCQb8pnqhCV
Also its not only in arena

**Comment by Wolffenstein** [comment]
Fixed in rev 3457.
