### ISSUE TITLE
[Item][Vial of the Sunwell] Heal is affected by Mortal Strike

### ISSUE THREAD

**Issue by oso5876** [Atlantiss/NetherwingBugtracker#6739]
[//]: # (Enclose links to things related to the bug using http://wowhead.com or any other TBC database.)
[//]: # (You can use screenshot ingame to visual the issue.)
[//]: # (Write your tickets according to the format:)
[//]: # ([Quest][Azuremyst Isle] Red Snapper - Very Tasty!)
[//]: # ([NPC] Magistrix Erona)
[//]: # ([Spell][Mage] Fireball)
[//]: # ([Npc][Drop] Ghostclaw Lynx)
[//]: # ([Web] Armory doesnt work)
[//]: # (To find server revision type `.server info` command in the game chat.)

**Description**: 
https://wowwiki.fandom.com/wiki/Vial_of_the_Sunwell

Previous ticket was on trinket not gaining stacks from hots.

**Current behaviour**:
When using Vial of the Sunwell at full 20 stacks on a target with Mortal Strike, it is only healing for 1000.

**Expected behaviour**: 
According to wowiki, Vial of the Sunwell should heal for the full amount of 2000 with a chance to crit for 3000.

**Server Revision**: 
3289 hash 86962fab0c1c

**Comment by oso5876** [comment]
@Wolffenstein who addressed the hots issue

**Comment by Evolvee** [comment]
thats correct behavior
