### ISSUE TITLE
[Quest] [Hillsbrad foothills] Soothing turtle bisque

### ISSUE THREAD

**Issue by tinkzorg** [Atlantiss/NetherwingBugtracker#674]
[//]: # (Enclose links to things related to the bug using http://wowhead.com or any other TBC database.)
[//]: # (You can use screenshot ingame to visual the issue.)
[//]: # (Write your tickets according to the format:)
[//]: # ([Quest][Azuremyst Isle] Red Snapper - Very Tasty!)
[//]: # ([NPC] Magistrix Erona)
[//]: # ([Spell][Mage] Fireball)
[//]: # ([Npc][Drop] Ghostclaw Lynx)
[//]: # ([Web] Armory doesnt work)

**Description**: This quest cannot be completed, because it cannot currently be obtained.

**Current behaviour**: Chef Jessen in Southshore does not offer this quest to a character of appropriate level, nor can he be interacted with in any other capacity.

**Expected behaviour**: Chef Jessen is supposed to offer the following quest: https://www.wowhead.com/quest=555/deprecated-soothing-turtle-bisque

**Server Revision**: 2060

**Comment by Pennywise4569** [comment]
Do you have the cooking skill? He only gives the quest if you have cooking, even if you have it at skill level 1.

**Comment by tinkzorg** [comment]
Damn, now I have egg on my face. I am almost certain I forgot to pick the skill up. I think this requirement was changed at some later date in retail, but that could be my memory throwing me off.

**Comment by The14me** [comment]
@tinkzorg  ill close this issue since u didnt have the cooking. Tag me if im wrong to re-open it.
https://www.wowhead.com/quest=555/deprecated-soothing-turtle-bisque#comments:id=110090
