### ISSUE TITLE
[Item][NPC] Gnomish Battle Chicken

### ISSUE THREAD

**Issue by aydarar** [Atlantiss/NetherwingBugtracker#6740]
Description: Gnomish Battle Chicken doesn't work properly.

Current behaviour: Gnomish Battle Chicken (https://tbcdb.com/?item=10725) doesn't attack and doesn't generate proc Battle Squawk, +5% attack speed (https://tbcdb.com/?spell=23060)

Expected behaviour: Gnomish Battle Chicken should attack close enemies (or sent by attack on target) and randomly generate proc Battle Squawk from attacks (https://wowwiki.fandom.com/wiki/Gnomish_Battle_Chicken)

Server Revision: 3289

**Comment by The14me** [comment]
https://classic.wowhead.com/item=10725/gnomish-battle-chicken#comments:id=2637389
https://classic.wowhead.com/item=10725/gnomish-battle-chicken#comments:id=16609

**Comment by Evolvee** [comment]
it doesnt have 100% chance to proc

**Comment by Evolvee** [comment]
it doesnt have 100% chance to proc

**Comment by aydarar** [comment]
yes, its not 100% chance, but chicken doesn't attack any target and couldn't generate proc obviously. If its attack bug, then it still bug. Also regarding https://wowwiki.fandom.com/wiki/Gnomish_Battle_Chicken chicken should have scaled level with engi skill, not level 1 (current behaviour).

**Comment by Evolvee** [comment]
level issue is already reported

**Comment by Evolvee** [comment]
https://github.com/Atlantiss/NetherwingBugtracker/issues/5347

the attack is also reported
