### ISSUE TITLE
[Loot] Loot System issue

### ISSUE THREAD

**Issue by The14me** [Atlantiss/NetherwingBugtracker#6741]
**Current behaviour**: Go in MgT or any other dung and kill a Boss with Unique loot like [Sun Touched Satchel
](https://www.wowhead.com/item=35516/sun-touched-satchel)
One of the party members has it already but still rolls. He wins the roll but can't take the bag since its unique and already have it. The second highers bidder cant loot it too and none can loot the bag anymore.
**Expected behaviour**: You wont be able to roll if u have Unique item already
https://www.wowhead.com/item=35516/sun-touched-satchel

**Server Revision**:

**Comment by tetsugoro** [comment]
This happened to me prior to 2.4 with the unique epic gems off the bosses in heroic dungeons. What ended up happening is it got sent to my mailbox in a way that it wouldn't expire like a GM restoring an item or something (couldn't take from mailbox still). I ended up able to delete the gem in the piece of gear I was using and grab the new one from the mailbox quite a while later to use in a different piece of gear.

**Comment by Tereneckla** [comment]
Fixed in big bugfixing session (rev 3330-3370 or something)
