### ISSUE TITLE
[Loot] Skill required recipes 

### ISSUE THREAD

**Issue by veekk** [Atlantiss/NetherwingBugtracker#6742]
**Description**:  for now BoP skill-requried recipes can be rolled even without this profession, and it 'cause issue when e.g. priest can can roll LW gloves recipes just for vendor instead of not be able to roll for it all

**Current behaviour**: visible for every1

**Expected behaviour**:  invisible with group loot, visible with ML

**Server Revision**: 3289

**Comment by NatsumeLily** [comment]
Be aware that some are like that. Some are invisible to everyone without that profession, others aren't invisible and anyone can roll on it/take it.

*Not confirming a bug, I'm saying there is no bug.*
