### ISSUE TITLE
[Silvermoon City] [RP] Faction RP NPCs don't path around the city.

### ISSUE THREAD

**Issue by DaedalusMachina007** [Atlantiss/NetherwingBugtracker#6743]
**Description**: 
NPCs are 'stuck' in one spot and don't path around like they should.
Several other issues about this but they're all over a year old and therefore obsolete/irrelevant unless some regression happened along the way.

NPCs are currently stuck at this spot in Silvermoon City near the Royal Exchange banking/auction area.

![2020-03-12 11_32_46-Greenshot](https://user-images.githubusercontent.com/54285152/76539346-08281b80-6457-11ea-965b-a424bd801d84.png)

**Current behaviour**:
NPCs stand in place

**Expected behaviour**: 
NPCs should path around Silvermoon in a predetermined path along waypoints.

**Server Revision**: 
3295 but has been broken since at least 3285 and possibly a bit earlier; was confirmed working in 3270 and prior revisions.

**Further Details/Issue**
I don't think Ambassador Kelemar (the Belf male) should say 'We lost many of our kin in the water' but rather 'we lost many of our kin in the war'.  It makes more sense to say 'war' than 'water' since there isn't much water around Eversong Woods/Ghostlands aside from a single pond near Silvermoon and the ocean areas to the west.

![2020-03-12 11_44_51-Greenshot](https://user-images.githubusercontent.com/54285152/76539867-bd5ad380-6457-11ea-8413-25155e6b8896.png)

**Comment by Wolffenstein** [comment]
Fixed in rev 3297.
