### ISSUE TITLE
[Class][Mage][Warlock] Table/soulwell interrupt

### ISSUE THREAD

**Issue by veekk** [Atlantiss/NetherwingBugtracker#6744]
**Description**:  in case of casting those 2 spells when 1 of casters moving while clicking (jump, running around and clicking) this spell going on CD w/o result

**Current behaviour**: *poof*

**Expected behaviour**: *ohm-nom-nom*

**Server Revision**: anything less  3295

**Comment by Suzaru** [comment]
Also the mage table should spawn where the "portal" was and not where the caster stands. Just like the soulwell.

**Comment by veekk** [comment]
[wiki](https://wowwiki.fandom.com/wiki/Patch_2.4.2) 

> Ritual of Souls (Warlock) and Ritual of Refreshment (Mage) will no longer be placed on cooldown without having completed the summon.

**Comment by devo6969** [comment]
They have changed how the soulwell/table spawn now, you need 3 people total (yourself and 2 others) and once the portal is clicked a self cast goes on the mage. I haven't seen either of them bug since this change was made.
