### ISSUE TITLE
[NPC][Drop][Nagrand] Agitated Orc Spirit doesn't drop Oshu'gun Crystal Powder Sample

### ISSUE THREAD

**Issue by raethkcj** [Atlantiss/NetherwingBugtracker#6745]
**Description**: 
According to: https://www.wowhead.com/npc=18043/agitated-orc-spirit#comments:id=343098
> Good for farming http://www.wowhead.com/?item=26042#dropped-by as a prot pally. Been farming them for about an hour and gotten 18 dust

I just killed almost the entire spawn of them 4 times over 25 minutes (about 24 kills per spawn or 100 kills total) and got zero powder. The powder seems to drop frequently from other mobs in Nagrand. I killed them on Alliance, it's possible these mobs are dropping the Horde version but not the Alliance version.

https://www.wowhead.com/item=26042 (Horde version of the drop)
https://www.wowhead.com/item=26043 (Alliance version
https://www.wowhead.com/npc=18043

**Current behaviour**:
These mobs don't drop Oshu'gun Crystal Powder Sample for Alliance.

**Expected behaviour**: 
They drop it.

**Server Revision**: 
3295

**Comment by Evolvee** [comment]
fixed in next rev
