### ISSUE TITLE
[QUEST][Stranglethorn Vale]Hunt for Yenniku

### ISSUE THREAD

**Issue by Grommaldus** [Atlantiss/NetherwingBugtracker#6746]
[//]: # (Enclose links to things related to the bug using http://wowhead.com or any other TBC database.)
[//]: # (You can use screenshot ingame to visual the issue.)
[//]: # (Write your tickets according to the format:)
[//]: # ([Quest][Azuremyst Isle] Red Snapper - Very Tasty!)
[//]: # ([NPC] Magistrix Erona)
[//]: # ([Spell][Mage] Fireball)
[//]: # ([Npc][Drop] Ghostclaw Lynx)
[//]: # ([Web] Armory doesnt work)
[//]: # (To find server revision type `.server info` command in the game chat.)

**Description**: 
When working on this quest concurrently with Cyclonian, the warrior class quest, the required items, bloodscalp tusk is needed for both quests.
Hunt for Yenniku quest link https://www.wowhead.com/quest=26298/hunt-for-yenniku
Cyclonian quest link https://classic.wowhead.com/quest=1712/cyclonian
**Current behaviour**:
When abandoning Hunt for Yenniku, it removes the bloodscalp tusks from your inventory even when you have Cyclonian in your quest log. There was no notification that the tusks would be removed when abandoning Hunt for Yenniku.
**Expected behaviour**: 
It should not remove tusks from your inventory when you have the warrior class quest Cyclonian still in your quest log and/or it should prompt you if they are being removed.
**Server Revision**:

**Comment by danbopes** [comment]
This was how it worked in TBC, this is working as intended. Unless you can show proof to the contrary: This is not a bug.
