### ISSUE TITLE
[Quest] Claiming the Light cannot be completed!

### ISSUE THREAD

**Issue by DaedalusMachina007** [Atlantiss/NetherwingBugtracker#6748]
**Description**: 
'Claiming the Light' cannot be completed.
Quest ID: 9684

**Current behaviour**:
Cannot proceed past this quest because quest item (Shimmering Vessel) requires presence of M'uru (who is gone) and the quest hasn't been updated to reflect this updated situation.

**Expected behaviour**: 
The quest should allow for 'draining' the risidual energy from the Magisters.  Per retail they should be crouched and look fatigued in a looping 'panting breath' animation.  See photo album for screens.

**Server Revision**: 
3297; was working as of 3295 (the version on PTR) with M'uru still present.

Additional info & screenshots in the provided imgur album here:
https://imgur.com/a/N1XqhoP

Album screenshots are dated May 17, 2009 (during WotLK timeframe).

**Comment by The14me** [comment]
https://www.wowhead.com/quest=9684/claiming-the-light#comments:id=288518
https://www.wowhead.com/quest=9684/claiming-the-light#comments:id=352217
Once u are there and click on the Vessel u get ''You can't do that yet''

**Comment by Evolvee** [comment]
I nees to rework it, its probably still in pre-2.4 state

**Comment by DaedalusMachina007** [comment]
This is a critical issue as zero Horde Paladins can get their required Resurrection spell!

A temporary workaround can be done on the 'Shimmering Vessel' item to set the value of 'Is M'uru Present' to always be 'True' so the item can be used right away and filled.  A proper fix can be done later on.  That way the item can be used and it will do its thing without blocking Horde Paladin players from progression.

**Comment by The14me** [comment]
That must be fixed at the next crash/restart (according to Evolve). Until then, if u need that quest just make an in-game ticket and a GM will complete it for you.

**Comment by Wolffenstein** [comment]
Fixed in rev 3304.
