### ISSUE TITLE
[NPC] Invisible npcs/objects

### ISSUE THREAD

**Issue by moemiki** [Atlantiss/NetherwingBugtracker#675]
**Description**: 
https://imgur.com/a/TAnIQtO

**Current behaviour**: Found with track humanoids "fucking fuck this shit fuck" named thing in darkshore, where Murkdeep event takes place. Some objects in named "hehexdlmao" are found with track beasts in northern darkshore (Ruins of Mathystra).

**Expected behaviour**: These aren't supposed to exist.

**Server Revision**:  2060

**Comment by The14me** [comment]
Known issue with the Hunter
