### ISSUE TITLE
[Daily][Quest] Distraction at the dead star

### ISSUE THREAD

**Issue by eri1997** [Atlantiss/NetherwingBugtracker#6750]
[//]: # (Enclose links to things related to the bug using http://wowhead.com or any other TBC database.)
[//]: # (You can use screenshot ingame to visual the issue.)
[//]: # (Write your tickets according to the format:)
[//]: # ([Quest][Azuremyst Isle] Red Snapper - Very Tasty!)
[//]: # ([NPC] Magistrix Erona)
[//]: # ([Spell][Mage] Fireball)
[//]: # ([Npc][Drop] Ghostclaw Lynx)
[//]: # ([Web] Armory doesnt work)
[//]: # (To find server revision type `.server info` command in the game chat.)

**Description**:  Mobs spawning too slow. The flight speed might be a bit too fast(maybe hard to tell )

**Current behaviour**: Quest takes 1233132 fly runs to complete

**Expected behaviour**: Quest doesn't make you give up 

**Server Revision**:

**Comment by Evolvee** [comment]
@Wolffenstein pooling system is broken on live,works on local

**Comment by Wolffenstein** [comment]
Fixed in rev 3306.
