### ISSUE TITLE
[PvP][BG][EotS] Breaking gear after MC

### ISSUE THREAD

**Issue by veekk** [Atlantiss/NetherwingBugtracker#6752]
**Description**:  if some1 MC u on EotS and drop into void ur gear going broken

**Current behaviour**: wtf

**Expected behaviour**: noice

**Server Revision**: everything below 3297

**Comment by tsuone** [comment]
In general you are losing durability on the Netherwing while PvPing which is wrong.

**Comment by veekk** [comment]
@tsuone not really, while pvping atm u're losing durability only if its environmental shit (when u dying from falling)

**Comment by tsuone** [comment]
I am constantly losing durability in PvP even when not dying from falling. Had to repair last time because my gear started to get yellow

**Comment by Wolffenstein** [comment]
Fixed in rev 3351.
