### ISSUE TITLE
Power Word Shield:  Spell power and healing bonuses do not apply to shield

### ISSUE THREAD

**Issue by TheDdraig** [Atlantiss/NetherwingBugtracker#6753]
**Description**: 
Power Word Shield: Spell Power and Healing bonuses do not apply which was applied in patch: "Patch 2.3.0 (13-Nov-2007): Now gains additional benefit from spell damage and healing bonuses. Base absorb values of ranks 10, 11 and 12 have been reduced."
**Current behaviour**:
Just showing baseline which is way weaker than it was intended from patch 2.3 going forward
**Expected behaviour**: 
The baseline should scale with the spell damage and healing bonuses and here is the source info: https://wowwiki.fandom.com/wiki/Power_Word:_Shield
**Server Revision**: 
3297

**Comment by Evolvee** [comment]
did you even test it? or did you looked at tooltip

**Comment by TheDdraig** [comment]
So I worked out some math in regards to this even though the actual hover over tooltip should show different absorb amount depending on if your spell power  goes lower or higher but it stays the same so what I did was attacked a Clefthoof Bull with all gear on, lasted 15 seconds before it broke, removed my spell power/healing bonus gear attacked again lasted 15 seconds before breaking.

**Comment by Evolvee** [comment]
tooltip doesnt change, it should not change

![image](https://user-images.githubusercontent.com/1942409/76708298-0465f480-66f6-11ea-9b28-d5133aec8aae.png)
no talents, 2099 bonus healing

![image](https://user-images.githubusercontent.com/1942409/76708308-1a73b500-66f6-11ea-8e0a-b53a42bd12b8.png)
no talents, 494 bonus healing
