### ISSUE TITLE
[ZA] [NPC] Halazzi

### ISSUE THREAD

**Issue by Sagoona** [Atlantiss/NetherwingBugtracker#6754]
[//]: # (Enclose links to things related to the bug using http://wowhead.com or any other TBC database.)
[//]: # (You can use screenshot ingame to visual the issue.)
[//]: # (Write your tickets according to the format:)
[//]: # ([Quest][Azuremyst Isle] Red Snapper - Very Tasty!)
[//]: # ([NPC] Magistrix Erona)
[//]: # ([Spell][Mage] Fireball)
[//]: # ([Npc][Drop] Ghostclaw Lynx)
[//]: # ([Web] Armory doesnt work)
[//]: # (To find server revision type `.server info` command in the game chat.)

**Description**: 
Halazzi can crush and does very low dmg in spirit phase.
**Current behaviour**:
Halazzi (Spirit phase) is able to crush but does very low hits: https://i.imgur.com/RJAbVhi.jpg ( Raid ID 742. 14th of march around 9:11 pm ST). Normal form still hits like a truck and can crush too.
**Expected behaviour**: 
Halazzi shouldn't be able to crush at all and do some sort of damage in spirit form. Unfortunately i couldn't find any footage from back then with Tank PoV.
Only this source [Halazzi tbc](https://wow.gamepedia.com/Halazzi_(removed))
**Server Revision**: 
3297

**Comment by Wolffenstein** [comment]
Fixed in rev 3388.
