### ISSUE TITLE
[Quest] Lost in action was made repeatable

### ISSUE THREAD

**Issue by Tereneckla** [Atlantiss/NetherwingBugtracker#6757]
[//]: # (Enclose links to things related to the bug using http://wowhead.com or any other TBC database.)
[//]: # (You can use screenshot ingame to visual the issue.)
[//]: # (Write your tickets according to the format:)
[//]: # ([Quest][Azuremyst Isle] Red Snapper - Very Tasty!)
[//]: # ([NPC] Magistrix Erona)
[//]: # ([Spell][Mage] Fireball)
[//]: # ([Npc][Drop] Ghostclaw Lynx)
[//]: # ([Web] Armory doesnt work)
[//]: # (To find server revision type `.server info` command in the game chat.)

**Description**: The quest [Lost in Action](https://www.wowhead.com/quest=9738/lost-in-action) was made repeatable for some reason.

**Current behaviour**: Is a repeatable quest

**Expected behaviour**: Is not a repeatable quest

**Server Revision**: 3307

**Comment by Wolffenstein** [comment]
Will be fixed after next server update.
