### ISSUE TITLE
[NPC] Pyralis - [Zone] Hillsbrad Foothills

### ISSUE THREAD

**Issue by drewk8** [Atlantiss/NetherwingBugtracker#6758]
**Description**: 
While farming some herbs, during the night (around 01:00+ in game time), near the coffin that leads to the Ravenholdt pass when walking from Durnholde Keep,  I encountered a ghost NPC of a Tauren, lvl 71 and two non selectable children NPCs crying. Location: [77.7, 28.8]

**Current behavior**:
Explained above. Could not find any mentions online of this NPC. Also, i don't remember seeing this NPC while leveling there in my 30s, but it might just be a long time since then. Might be custom content only available during the night? Just speculating.

**Expected behavior**: 
Does not spawn? Like i said, i could not find any mentions online of this NPC or the crying children near the grave site.

**Server Revision**: 
3306

![WoWScrnShot_031720_013442](https://user-images.githubusercontent.com/46622080/76809937-1a0e1380-67f5-11ea-85cc-2499ace22634.jpg)

![WoWScrnShot_031720_022227](https://user-images.githubusercontent.com/46622080/76810352-6b6ad280-67f6-11ea-8af5-01851089d0c5.jpg)

**Comment by Wolffenstein** [comment]
@Evolvee

**Comment by The14me** [comment]
:PepeHands:

**Comment by Evolvee** [comment]
PepeHands

**Comment by tsuone** [comment]
KEKW
