### ISSUE TITLE
[Quest][Throne of Kil'Jaeden] Blood for Blood

### ISSUE THREAD

**Issue by djobf** [Atlantiss/NetherwingBugtracker#6760]
[//]: # (Enclose links to things related to the bug using http://wowhead.com or any other TBC database.)
[//]: # (You can use screenshot ingame to visual the issue.)
[//]: # (Write your tickets according to the format:)
[//]: # ([Quest][Azuremyst Isle] Red Snapper - Very Tasty!)
[//]: # ([NPC] Magistrix Erona)
[//]: # ([Spell][Mage] Fireball)
[//]: # ([Npc][Drop] Ghostclaw Lynx)
[//]: # ([Web] Armory doesnt work)
[//]: # (To find server revision type `.server info` command in the game chat.)

**Description**: 
Demonic Blood item doesn't work as intended
**Current behaviour**:
The Demonic Blood doesn't do anything against Felblood Initiate when in a party
**Expected behaviour**: 
Transforms Felblood Initiate into Emaciated Felblood
**Server Revision**: 
3307

**Comment by Wolffenstein** [comment]
@Evolvee

**Comment by Suzaru** [comment]
I do this quest in party every day and it works perfectly fine. Try to delete your cache folder inside your wow folder.

**Comment by Wolffenstein** [comment]
Closing then. Can be reopened if other people report the same.
