### ISSUE TITLE
[Spell][NPC][Raid][SSC] Underbog Colossus vulnerabilities affect all schools instead of just one

### ISSUE THREAD

**Issue by raethkcj** [Atlantiss/NetherwingBugtracker#6763]
[//]: # (Enclose links to things related to the bug using http://wowhead.com or any other TBC database.)
[//]: # (You can use screenshot ingame to visual the issue.)
[//]: # (Write your tickets according to the format:)
[//]: # ([Quest][Azuremyst Isle] Red Snapper - Very Tasty!)
[//]: # ([NPC] Magistrix Erona)
[//]: # ([Spell][Mage] Fireball)
[//]: # ([Npc][Drop] Ghostclaw Lynx)
[//]: # ([Web] Armory doesnt work)
[//]: # (To find server revision type `.server info` command in the game chat.)

**Description**: 
Underbog Colossus (21251) spawn with a vulnerability to a random spell school (Spell IDs 38714, 38715, 38717). This should make them take increased damage from certain spell critical hits. Currently these vulnerabilities affect ALL spell schools, for example, this colossus took 7215 damage from my lightning bolt while it had Fire Vulnerability:

![WoWScrnShot_031820_150803](https://user-images.githubusercontent.com/7716908/77003597-a3bffd00-692b-11ea-8b55-31d2890d2501.jpg)

**Current behaviour**:
Spell vulnerabilites affect all spell schools.

**Expected behaviour**: 
Vulnerabilities only affect one school.

**Server Revision**: 
3312

**Comment by Wolffenstein** [comment]
Fixed in rev 3368.
