### ISSUE TITLE
[Item][Shattered Sun Pendant of Restoration] Not procing with HOTS

### ISSUE THREAD

**Issue by oso5876** [Atlantiss/NetherwingBugtracker#6765]
[//]: # (Enclose links to things related to the bug using http://wowhead.com or any other TBC database.)
[//]: # (You can use screenshot ingame to visual the issue.)
[//]: # (Write your tickets according to the format:)
[//]: # ([Quest][Azuremyst Isle] Red Snapper - Very Tasty!)
[//]: # ([NPC] Magistrix Erona)
[//]: # ([Spell][Mage] Fireball)
[//]: # ([Npc][Drop] Ghostclaw Lynx)
[//]: # ([Web] Armory doesnt work)
[//]: # (To find server revision type `.server info` command in the game chat.)

**Description**: 
https://www.wowhead.com/item=34677/shattered-sun-pendant-of-restoration

**Current behaviour**:
Item is not procing Scryer bonus when healing with Hots. Works with direct healing.

**Expected behaviour**: 
Item should be procing with hots and direct heals

**Server Revision**: 
3312

**Comment by NatsumeLily** [comment]
It does proc on hots, but there are two important requirements about it doing so -

-The hot tick needs to heal (no overhealing) 
-You need to be targeting the player or a player

**Comment by oso5876** [comment]
@NatsumeLily no, it is not working. Several rounds of arena and bg's with no procs from lifebloom and rejuv. Target has health missing. Only healing touch and regrowth procs the necklace
