### ISSUE TITLE
[Sunwell Plateau - Kalecgos] No portal delay

### ISSUE THREAD

**Issue by dshgrove** [Atlantiss/NetherwingBugtracker#6767]
[//]: # (Enclose links to things related to the bug using http://wowhead.com or any other TBC database.)
[//]: # (You can use screenshot ingame to visual the issue.)
[//]: # (Write your tickets according to the format:)
[//]: # ([Quest][Azuremyst Isle] Red Snapper - Very Tasty!)
[//]: # ([NPC] Magistrix Erona)
[//]: # ([Spell][Mage] Fireball)
[//]: # ([Npc][Drop] Ghostclaw Lynx)
[//]: # ([Web] Armory doesnt work)
[//]: # (To find server revision type `.server info` command in the game chat.)

**Description**: 
There should be a delay between players entering the portals during the kalecgos encounter. 

**Current behaviour**:
There is no delay. You can have several people entering at the same second.
[Image of DBM portal timer (on Netherwing)](https://i.imgur.com/1WWVrue.png)

**Expected behaviour**: 
When a player enters, the remaining players should not be able to click the portal for around one second.
[Video from retail with several players trying to click the portal at the same time](https://www.youtube.com/watch?v=Kd0YIXxdoAA&start=186)

**Server Revision**: 
3312

**Comment by Godmatik** [comment]
Was fixed at start of Netherwing server's Sunwell
