### ISSUE TITLE
[Fishing) Mr. Pinchy fished from Terokkar open water

### ISSUE THREAD

**Issue by Tereneckla** [Atlantiss/NetherwingBugtracker#6768]
[//]: # (Enclose links to things related to the bug using http://wowhead.com or any other TBC database.)
[//]: # (You can use screenshot ingame to visual the issue.)
[//]: # (Write your tickets according to the format:)
[//]: # ([Quest][Azuremyst Isle] Red Snapper - Very Tasty!)
[//]: # ([NPC] Magistrix Erona)
[//]: # ([Spell][Mage] Fireball)
[//]: # ([Npc][Drop] Ghostclaw Lynx)
[//]: # ([Web] Armory doesnt work)
[//]: # (To find server revision type `.server info` command in the game chat.)

**Description**: [Mr. Pinchy](https://www.wowhead.com/item=27388/mr-pinchy)

**Current behaviour**: Fished Mr. Pinchy in Terokkar open water

**Expected behaviour**: Only fished from Highland Mixed Schools

**Server Revision**: 3312

**Comment by Evolvee** [comment]
should be fixed in next rev
