### ISSUE TITLE
[Item] [Hunter] Shivering Felspine model bug on blood elf hunters

### ISSUE THREAD

**Issue by bnkyo** [Atlantiss/NetherwingBugtracker#6769]
[//]: # (Enclose links to things related to the bug using http://wowhead.com or any other TBC database.)
[//]: # (You can use screenshot ingame to visual the issue.)
[//]: # (Write your tickets according to the format:)
[//]: # ([Quest][Azuremyst Isle] Red Snapper - Very Tasty!)
[//]: # ([NPC] Magistrix Erona)
[//]: # ([Spell][Mage] Fireball)
[//]: # ([Npc][Drop] Ghostclaw Lynx)
[//]: # ([Web] Armory doesnt work)
[//]: # (To find server revision type `.server info` command in the game chat.)

**Description**: 

https://www.wowhead.com/item=34183/shivering-felspine

Shivering Felspine seem to disappear when you're about to auto attack with a ranged weapon. this is a slight bug that kinda annoys people that value aesthetics which is a part of the game too

**Current behaviour**:
Shivering Felspine disappears from the back whilst auto attacking. (the item re-appears on your back after you sheathe the bow)

![Screen Shot 2020-03-20 at 20 08 45](https://user-images.githubusercontent.com/62430784/77166389-c6e2dc00-6ae6-11ea-85d7-2ad3a5bbf2fa.png)

**Expected behaviour**: 
Shivering Felspine should still be in the back whilst auto attacking, like any other polearms. (example below is Sonic Spear, which is also a polearm)

![Screen Shot 2020-03-20 at 20 06 25](https://user-images.githubusercontent.com/62430784/77166447-deba6000-6ae6-11ea-8b83-3fc98dd2178c.png)

**Server Revision**: 3312

**Comment by Evolvee** [comment]
are you sure this works on other servers/retail? (dont wanna waste time figuring it out until we have confirmed its bugged)

**Comment by Wolffenstein** [comment]
This is most likely blizzlike.
