### ISSUE TITLE
[NPC] Knucklerot and Luzran

### ISSUE THREAD

**Issue by cuppycup12** [Atlantiss/NetherwingBugtracker#677]
[//]: # (Enclose links to things related to the bug using http://wowhead.com or any other TBC database.)
[//]: # (You can use screenshot ingame to visual the issue.)
[//]: # (Write your tickets according to the format:)
[//]: # ([Quest][Azuremyst Isle] Red Snapper - Very Tasty!)
[//]: # ([NPC] Magistrix Erona)
[//]: # ([Spell][Mage] Fireball)
[//]: # ([Npc][Drop] Ghostclaw Lynx)
[//]: # ([Web] Armory doesnt work)

**Description**: 

**Current behaviour**:

**Expected behaviour**: 

**Server Revision**:

**Comment by cuppycup12** [comment]
Knucklerot and Luzran seem to be hitting a little too hard (including against appropriate-level tanks).

**Comment by The14me** [comment]
Please add at least screenshot from combat log and more info about your character(level/armor)

**Comment by cuppycup12** [comment]
![wowscrnshot_092618_114330](https://user-images.githubusercontent.com/43590862/46095270-b7990180-c181-11e8-9122-05cf717db4cb.jpg)

Level 20 paladin with 1594 armor (43.15% reduced physical damage). I understand that this is a 4-5 man quest but I am being bursted down extremely quickly even with very good armor for the level.

**Comment by Wolffenstein** [comment]
Fixed in rev 2070.
