### ISSUE TITLE
[Spell][Warrior] Execute

### ISSUE THREAD

**Issue by tsu-1** [Atlantiss/NetherwingBugtracker#6770]
[//]: # (Enclose links to things related to the bug using http://wowhead.com or any other TBC database.)
[//]: # (You can use screenshot ingame to visual the issue.)
[//]: # (Write your tickets according to the format:)
[//]: # ([Quest][Azuremyst Isle] Red Snapper - Very Tasty!)
[//]: # ([NPC] Magistrix Erona)
[//]: # ([Spell][Mage] Fireball)
[//]: # ([Npc][Drop] Ghostclaw Lynx)
[//]: # ([Web] Armory doesnt work)
[//]: # (To find server revision type `.server info` command in the game chat.)

**Description**: Pressing "Execute" when it is available sometimes results in an "empty" swing - gcd goes, it isn't missed or dodged, rage isn't wasted just execute doesn't hit the target like it is an empty swing.

**Current behaviour**: Pressing "Execute" when it is available sometimes results in an "empty" swing - gcd goes, it isn't missed or dodged, rage isn't wasted just execute doesn't hit the target like it is an empty swing.

**Expected behaviour**: Pressing Execute as soon as it pops availalbe should result in a swing.

**Server Revision**: 3312

**Comment by Godmatik** [comment]
It happens when you get it parried/missed/dodged. It was not showing it properly.

Wolf is implementing a fix soon:

[Core/Warrior]:
- Warriors will now be properly notified when Execute misses
- Triggered damaging component of Execute will no longer check hit result/be able to miss
