### ISSUE TITLE
[BG][WSG] Time limit

### ISSUE THREAD

**Issue by tsuone** [Atlantiss/NetherwingBugtracker#6773]
[//]: # (Enclose links to things related to the bug using http://wowhead.com or any other TBC database.)
[//]: # (You can use screenshot ingame to visual the issue.)
[//]: # (Write your tickets according to the format:)
[//]: # ([Quest][Azuremyst Isle] Red Snapper - Very Tasty!)
[//]: # ([NPC] Magistrix Erona)
[//]: # ([Spell][Mage] Fireball)
[//]: # ([Npc][Drop] Ghostclaw Lynx)
[//]: # ([Web] Armory doesnt work)
[//]: # (To find server revision type `.server info` command in the game chat.)

**Description**: Suggestion adding time limit for Warsong Gulch as sometimes games take very long to finish.

**Current behaviour**: Inifnite time to finish Warsong Gulch.

**Expected behaviour**: Add 10 minute time limit.

**Server Revision**: 3312

**Comment by Evolvee** [comment]
bugtracker is not a place for suggestions
