### ISSUE TITLE
[Spell] Buff/Debuff timer stuck

### ISSUE THREAD

**Issue by tsuone** [Atlantiss/NetherwingBugtracker#6774]
[//]: # (Enclose links to things related to the bug using http://wowhead.com or any other TBC database.)
[//]: # (You can use screenshot ingame to visual the issue.)
[//]: # (Write your tickets according to the format:)
[//]: # ([Quest][Azuremyst Isle] Red Snapper - Very Tasty!)
[//]: # ([NPC] Magistrix Erona)
[//]: # ([Spell][Mage] Fireball)
[//]: # ([Npc][Drop] Ghostclaw Lynx)
[//]: # ([Web] Armory doesnt work)
[//]: # (To find server revision type `.server info` command in the game chat.)

**Description**: Buff/debuff visual cooldown timer is sometimes stuck at 0.

**Current behaviour**: Buff and debuff visual cooldown timer (black overlay) is sometimes stuck at 0(sec). It happens on unitframes and buff/debuff bar. 
![image](https://user-images.githubusercontent.com/11255782/77213461-2fdc4b00-6b0b-11ea-9f32-91e4c0131194.png)

**Expected behaviour**: Display correct cooldown timer.

**Server Revision**: 3312

**Comment by 4egito** [comment]
There is video about this: https://drive.google.com/open?id=1T3U0A6cFk_o6Vx6ay1jPNPB0PvRKDnJj

**Comment by Wolffenstein** [comment]
Fixed,
