### ISSUE TITLE
[Core] Honor

### ISSUE THREAD

**Issue by tsuone** [Atlantiss/NetherwingBugtracker#6775]
[//]: # (Enclose links to things related to the bug using http://wowhead.com or any other TBC database.)
[//]: # (You can use screenshot ingame to visual the issue.)
[//]: # (Write your tickets according to the format:)
[//]: # ([Quest][Azuremyst Isle] Red Snapper - Very Tasty!)
[//]: # ([NPC] Magistrix Erona)
[//]: # ([Spell][Mage] Fireball)
[//]: # ([Npc][Drop] Ghostclaw Lynx)
[//]: # ([Web] Armory doesnt work)
[//]: # (To find server revision type `.server info` command in the game chat.)

**Description**: Honor is being displayed wrong and lifetime isn't shown.

**Current behaviour**: Currently there isn't lifetime honor earned showed in PvP tab and "yesterday" HKs are being shown bad. On the screenshot I should have ~150 (or something like this, don't remember) HKs but it shows 50 for "yesterday". Worth mentioning, sometimes inspecting other player characters display summarize of today and yesterday honor as a today.
![image](https://user-images.githubusercontent.com/11255782/77213591-a5e0b200-6b0b-11ea-8604-39a932ec4fbd.png)

**Expected behaviour**: Show correct values.

**Server Revision**: 3312

**Comment by Wolffenstein** [comment]
Fixed in rev 3435.
