### ISSUE TITLE
[Core][WSG] Able to DoT/Cast through huts/walls

### ISSUE THREAD

**Issue by tsuone** [Atlantiss/NetherwingBugtracker#6776]
[//]: # (Enclose links to things related to the bug using http://wowhead.com or any other TBC database.)
[//]: # (You can use screenshot ingame to visual the issue.)
[//]: # (Write your tickets according to the format:)
[//]: # ([Quest][Azuremyst Isle] Red Snapper - Very Tasty!)
[//]: # ([NPC] Magistrix Erona)
[//]: # ([Spell][Mage] Fireball)
[//]: # ([Npc][Drop] Ghostclaw Lynx)
[//]: # ([Web] Armory doesnt work)
[//]: # (To find server revision type `.server info` command in the game chat.)

**Description**: If you are close to the wall you are able to DoT players through walls.

**Current behaviour**: DoTing and meleeing through walls (fx. attacking through Drek/Galv/Ballinda or Van walls).

**Expected behaviour**: Not be able to do so.

**Server Revision**: 3312

**Comment by Evolvee** [comment]
? where can you dot through wall ?
need screenshots

**Comment by tsuone** [comment]
Horde zerk/rest huts

**Comment by Evolvee** [comment]
lf screenshot/video of that

cant reproduce, melee through wall is blizzlike
