### ISSUE TITLE
[Quest][Ironforge] Data Rescue - No Prismatic Punch Card handed out

### ISSUE THREAD

**Issue by addi011** [Atlantiss/NetherwingBugtracker#6777]
[//]: # (Enclose links to things related to the bug using http://wowhead.com or any other TBC database.)
[//]: # (You can use screenshot ingame to visual the issue.)
[//]: # (Write your tickets according to the format:)
[//]: # ([Quest][Azuremyst Isle] Red Snapper - Very Tasty!)
[//]: # ([NPC] Magistrix Erona)
[//]: # ([Spell][Mage] Fireball)
[//]: # ([Npc][Drop] Ghostclaw Lynx)
[//]: # ([Web] Armory doesnt work)
[//]: # (To find server revision type `.server info` command in the game chat.)

**Description**: The quest https://classic.wowhead.com/quest=2930/data-rescue cannot be completed, because you are not getting the Prismatic Punch Card from the last machine in Gnomeregan.

**Current behaviour**: Last machine of the quest line does not give out the needed Prismatic Punch Card, but only the Security DELTA Data Access Card for engineers. 

**Expected behaviour**: Last machine of the quest line should exchange the Red Punch Card with the Prismatic Punch Card, which is the item needed for completing the quest.

**Server Revision**: 3315

**Comment by Evolvee** [comment]
fixed in next rev
