### ISSUE TITLE
[Hunter] Improved Concussive Shot stun share DR with other stuns

### ISSUE THREAD

**Issue by 4egito** [Atlantiss/NetherwingBugtracker#6778]
[//]: # (Enclose links to things related to the bug using http://wowhead.com or any other TBC database.)
[//]: # (You can use screenshot ingame to visual the issue.)
[//]: # (Write your tickets according to the format:)
[//]: # ([Quest][Azuremyst Isle] Red Snapper - Very Tasty!)
[//]: # ([NPC] Magistrix Erona)
[//]: # ([Spell][Mage] Fireball)
[//]: # ([Npc][Drop] Ghostclaw Lynx)
[//]: # ([Web] Armory doesnt work)
[//]: # (To find server revision type `.server info` command in the game chat.)

**Description**: 
Improved Concussive Shot stun share DR with other stuns
**Current behaviour**:
https://drive.google.com/open?id=1ghgbZhOHfwLZE4nBh8V6D8expUf6tZoj
**Expected behaviour**: 
https://wowwiki.fandom.com/wiki/Improved_Concussive_Shot
**Patch 1.9.0 (03-Jan-2006): The stun effect's duration no longer diminishes or is diminished by controlled stun abilities and spells (e.g. Cheap Shot, Hammer of Justice, Charge etc.).**
**Server Revision**: 
3315

**Comment by Evolvee** [comment]
![image](https://user-images.githubusercontent.com/1942409/77233113-99109c80-6ba5-11ea-9422-580557ee8436.png)
from above post ^^

anyways, need to confirm this with 100% certainty (research/retail videos)

**Comment by 4egito** [comment]
https://wow.gamepedia.com/Improved_Concussive_Shot
https://www.wowhead.com/forums&topic=181967&p=2520060#p2517238

**Comment by Evolvee** [comment]
k it should be shared with random stuns(mace stuns for example) @Wolffenstein

**Comment by 4egito** [comment]
Thanks for the quick research!

**Comment by Wolffenstein** [comment]
Fixed in rev 3322.
