### ISSUE TITLE
[Core][Spell] Dimishing Returns

### ISSUE THREAD

**Issue by tsu-1** [Atlantiss/NetherwingBugtracker#6779]
[//]: # (Enclose links to things related to the bug using http://wowhead.com or any other TBC database.)
[//]: # (You can use screenshot ingame to visual the issue.)
[//]: # (Write your tickets according to the format:)
[//]: # ([Quest][Azuremyst Isle] Red Snapper - Very Tasty!)
[//]: # ([NPC] Magistrix Erona)
[//]: # ([Spell][Mage] Fireball)
[//]: # ([Npc][Drop] Ghostclaw Lynx)
[//]: # ([Web] Armory doesnt work)
[//]: # (To find server revision type `.server info` command in the game chat.)

**Description**: Using a DR ability fx. roots on enemy 2nd time while on DR makes it display "28 sec" instead of "4 sec".

**Current behaviour**: Wrong timer, 28 sec instead of 4 sec but roots fall after 4 seconds at 24.

**Expected behaviour**: Display 4 sec at 1/2 instead of 28 sec.

**Server Revision**: 3312

PS. Fresh cache

**Comment by Godmatik** [comment]
huh?
Maybe this was fixed at some point, I don't see where it ever says 28 seconds.
