### ISSUE TITLE
Silvermoon Guard Engineering Trainer Text

### ISSUE THREAD

**Issue by Northlol** [Atlantiss/NetherwingBugtracker#678]
**Description**: Silvermoon Engineering Trainer Directions have a typo

**Current behaviour**: Guard says "Old choice"

**Expected behaviour**:  Guard Should say "Odd choice"

https://imgur.com/a/EFzKHJD

**Comment by danbopes** [comment]
Imgur link is broken, and searching the db for "Old choice" yields no results. If you want to provide additional information if you still have it, I'll reopen the ticket (Just tag me).
