### ISSUE TITLE
[Fishing] Fishing Bobber

### ISSUE THREAD

**Issue by taigaqt** [Atlantiss/NetherwingBugtracker#6782]
[//]: # (Enclose links to things related to the bug using http://wowhead.com or any other TBC database.)
[//]: # (You can use screenshot ingame to visual the issue.)
[//]: # (Write your tickets according to the format:)
[//]: # ([Quest][Azuremyst Isle] Red Snapper - Very Tasty!)
[//]: # ([NPC] Magistrix Erona)
[//]: # ([Spell][Mage] Fireball)
[//]: # ([Npc][Drop] Ghostclaw Lynx)
[//]: # ([Web] Armory doesnt work)
[//]: # (To find server revision type `.server info` command in the game chat.)

**Description**: Fishing Bobber.

**Current behaviour**: Fishing Bobber disappears when you miss the catch, but cast is still going on.
![image](https://user-images.githubusercontent.com/11255782/77263304-4fed4500-6c98-11ea-920e-d7255385aa62.png)

**Expected behaviour**: Fishing Bobber shouldn't disappear when you miss the fish and there shouldn't be a chance to catch another fish in the same cast (just saying).

**Server Revision**: 3312

**Comment by Wolffenstein** [comment]
Fixed in rev 3830.
