### ISSUE TITLE
[Item][Loot] Weather-Beaten Journal

### ISSUE THREAD

**Issue by tsuone** [Atlantiss/NetherwingBugtracker#6783]
[//]: # (Enclose links to things related to the bug using http://wowhead.com or any other TBC database.)
[//]: # (You can use screenshot ingame to visual the issue.)
[//]: # (Write your tickets according to the format:)
[//]: # ([Quest][Azuremyst Isle] Red Snapper - Very Tasty!)
[//]: # ([NPC] Magistrix Erona)
[//]: # ([Spell][Mage] Fireball)
[//]: # ([Npc][Drop] Ghostclaw Lynx)
[//]: # ([Web] Armory doesnt work)
[//]: # (To find server revision type `.server info` command in the game chat.)

**Description**: Weather-Beaten Journal can be looted from Watertight Trunk twice from the same chest.

**Current behaviour**: You can loot two Weather-Beaten Journals from one Watertight Trunk.

**Expected behaviour**: You **shouldn't be able to loot two** Weather-Beaten Journals, **only one drops** from the Watertight Trunk.

**Server Revision**: 3315

**Comment by Evolvee** [comment]
next rev
