### ISSUE TITLE
[NPC] Starving Hellboar

### ISSUE THREAD

**Issue by tsuone** [Atlantiss/NetherwingBugtracker#6784]
[//]: # (Enclose links to things related to the bug using http://wowhead.com or any other TBC database.)
[//]: # (You can use screenshot ingame to visual the issue.)
[//]: # (Write your tickets according to the format:)
[//]: # ([Quest][Azuremyst Isle] Red Snapper - Very Tasty!)
[//]: # ([NPC] Magistrix Erona)
[//]: # ([Spell][Mage] Fireball)
[//]: # ([Npc][Drop] Ghostclaw Lynx)
[//]: # ([Web] Armory doesnt work)
[//]: # (To find server revision type `.server info` command in the game chat.)

**Description**: Very big aggro radius even when grey (I am 70).

**Current behaviour**: Starving Hellboars are too big of an aggro range radius when you are level 70.

**Expected behaviour**: Aggro range radius should be lower for level 70 (when mob is grey) players.

**Server Revision**: 3315

**Comment by raethkcj** [comment]
#2279

It's blizzlike and intentional (they're "starving" so they aggro from far away)

**Comment by tsuone** [comment]
But when they are grey? Shouldn't aggro range radius get smaller with higher level gap between player?

**Comment by Evolvee** [comment]
this npc should have higher aggro range, same as other dogs, hounds, hyenas etc. 

if the issue is that npcs with boosted threat distance dont lose aggro range per usual (level scaling) and still act as if the level wasnt gray, make a core issue about it (with proof of testing)
