### ISSUE TITLE
[Class][Warlock] Pets reset their CDs after resummoning

### ISSUE THREAD

**Issue by Silun** [Atlantiss/NetherwingBugtracker#6785]
**Description**: 
Warlocks can use their fel hunter's Spell Lock on a target. If the pet is killed, and the warlock uses Fel Domination to resummon the fel hunter instantly, the cooldown is gone and the warlock can use Spell Lock again instantly.

**Current behaviour**:
The pet's cooldown is gone after death and resummoning. Not sure about resummon without death.

**Expected behaviour**: 
The pet's cooldown should remain and carry over to the resummoned pet.

**Server Revision**: 
3315

**Comment by Evolvee** [comment]
did this happen inside arena?

**Comment by Silun** [comment]
Yes, it did.

**Comment by Evolvee** [comment]
thats correct behavior then
