### ISSUE TITLE
[Mechanics][Possibly Mage] It's possible to miss in PvP with 5% hit

### ISSUE THREAD

**Issue by Silun** [Atlantiss/NetherwingBugtracker#6786]
**Description**: 
Being a warrior with more than 5% hit and capped weapon skill, I repeatedly missed a mage with both melee swings and Hamstring. The mage used Presence of Mind and Pyroblast, which means **he could not have specced** into Arctic Winds, which would increase the miss chance.

**Current behaviour**:
It's possible to miss PvP targets (at least mages) when the melee attacker has over 5% hit.

**Expected behaviour**: 
It should not be possible to miss PvP targets when the melee attacker has 5% hit or more.

**Server Revision**: 
3315

**Comment by duzyizly** [comment]
improved blink maybe?

**Comment by Silun** [comment]
Oh my. That would certainly explain it. I must not have seen that one when I checked the mage talents, I thought they had just Arctic Winds for miss chance.
