### ISSUE TITLE
Foulweald furbolgs (Ashenvale) rubber-banding, improperly evading, impossible to attack, et al.

### ISSUE THREAD

**Issue by zakethtrarr** [Atlantiss/NetherwingBugtracker#6787]
Hi!  This is to report a set of bugs that I have discussed with Etherious.  We tried clearing my cache and accounting for various things that could go wrong on the client side, to no avail.

As an introduction to the bug list below:  I am in Ashenvale and am killing Foulweald warriors, totemics, ursas, and den watchers.  All of them have exhibited improper, buggy behaviors.  These bugs were encountered on a connection with consistently low latency (less than 200ms) and were unique-- no other mobs I have encountered on this server have exhibited such behaviors.  Also, I had done a number of quests that day, in Ashenvale, and all other mobs functioned correctly.  

Note:  I am a feral druid, and all of the below bugs were observed while I was in Cat Form and engaging in melee combat.

1.) **Furbolg not in correct location as per its graphical representation.**  On my attack, Furbolg will rubberband to a nearby location.  As he rubberbands, the "Evade" notification is shown.  Once I approach him in his new location, I am able to attack him normally.  Furbolg appears to attack me normally.
2.) **Furbolg behaves as per #1, but can only be attacked with Special Attacks** (yellow combat text).  Furbolg appears to attack me normally.
3.) **Furbolg behaves as per #1, but is completely inaccessible when I try to attack it.**  Furbolg will not attack.

I believe there were other variations, as well, but I have trouble keeping track of them all.

**Comment by Godmatik** [comment]
Can not reproduce any of this
