### ISSUE TITLE
[Core][Spell][Warlock] Summons on kill

### ISSUE THREAD

**Issue by tsu-1** [Atlantiss/NetherwingBugtracker#6788]
[//]: # (Enclose links to things related to the bug using http://wowhead.com or any other TBC database.)
[//]: # (You can use screenshot ingame to visual the issue.)
[//]: # (Write your tickets according to the format:)
[//]: # ([Quest][Azuremyst Isle] Red Snapper - Very Tasty!)
[//]: # ([NPC] Magistrix Erona)
[//]: # ([Spell][Mage] Fireball)
[//]: # ([Npc][Drop] Ghostclaw Lynx)
[//]: # ([Web] Armory doesnt work)
[//]: # (To find server revision type `.server info` command in the game chat.)

**Description**: WTF?

**Current behaviour**: WTF is this? Warlock got killed but his pet survived and started to attack everyone. (fyi. there was only one warlock in the BG)
![image](https://user-images.githubusercontent.com/11255782/77378534-7f727f00-6d76-11ea-8ca6-3187d8928f0b.png)

**Expected behaviour**: Summoned pet despawns on Warlock death.

**Server Revision**: 3315

**Comment by Elannreportujerzeczy** [comment]
byłem tam potwierdzam
I was there I confirm

Pozdrawiam,
Jakub

**Comment by tsuone** [comment]
Update: It happens with hunter pets too (probably when "graveyard" is near the warlock corpses)

**Comment by tsuone** [comment]
![image](https://user-images.githubusercontent.com/11255782/78473759-51f8de80-7743-11ea-895a-9f414af2d1f8.png)

**Comment by Godmatik** [comment]
Was fixed last year - closing
