### ISSUE TITLE
Shadowpine Catlord#16345 doesn't flee on low HP

### ISSUE THREAD

**Issue by Tenoutoften** [Atlantiss/NetherwingBugtracker#679]
**Description**: 
Shadowpine Catlord#16345(https://db.excalibur.ws/?npc=16345) doesn't occasionally flee on low HP: https://i.gyazo.com/9fdb54c8b3d74b8d614673310d05e5f3.png
Should occasionally flee on low HP: https://youtu.be/Ryg1KLVOH9w?t=341

**Server Revision**: 
2060

**Comment by tcberk12** [comment]
out of curiosity, are those mobs casting a bloodlust type spell?

wowhead comment from 2007: (https://www.wowhead.com/npc=16345/shadowpine-catlord#comments)

>Not only that, but they can also cast Bloodlust upon themselves, their allies, or the lower level cat (Ghostclaw Lynx).

**Comment by Tenoutoften** [comment]
I don't think I have ever seen a cat receiving a bloodlust, Ill check it out

**Comment by Evolvee** [comment]
rev sample_text
