### ISSUE TITLE
The fake roll macro works on the server!

### ISSUE THREAD

**Issue by Kersoph** [Atlantiss/NetherwingBugtracker#6790]
**Description**: 
There was a macro to fake rolls and it is working on the Server. That breaks all turst in rolls and is already abused by ppl for trash farm rolls.

**Current behaviour**:
The roll macro works on the server to fake rolls! So ppl can roll high when they want to.
![grafik](https://user-images.githubusercontent.com/26461040/77422258-7365dc00-6dcd-11ea-924b-506f1c340a1b.png)
Ppl can set rolls whatever they want to. Noone can trust in rolls liek that one. I dont know how to detect if tis fake.

**Expected behaviour**: 
Fake rolls should be not possible or lead to banns if abused.

**Server Revision**: 
3315

**Comment by Evolvee** [comment]
client side
