### ISSUE TITLE
[Battleground] Flag visual

### ISSUE THREAD

**Issue by tsu-1** [Atlantiss/NetherwingBugtracker#6791]
[//]: # (Enclose links to things related to the bug using http://wowhead.com or any other TBC database.)
[//]: # (You can use screenshot ingame to visual the issue.)
[//]: # (Write your tickets according to the format:)
[//]: # ([Quest][Azuremyst Isle] Red Snapper - Very Tasty!)
[//]: # ([NPC] Magistrix Erona)
[//]: # ([Spell][Mage] Fireball)
[//]: # ([Npc][Drop] Ghostclaw Lynx)
[//]: # ([Web] Armory doesnt work)
[//]: # (To find server revision type `.server info` command in the game chat.)

**Description**: I don't know how it happened and how to describe it.

**Current behaviour**: There was a bear druid who tried to get flag and ended up like this (ran away whole battleground with flag on back when flag was in the middle): 
![image](https://user-images.githubusercontent.com/11255782/77472547-66b8a680-6e14-11ea-8971-7630c4043d90.png)

**Expected behaviour**: Proper behaviour.

**Server Revision**: 3315

**Comment by Godmatik** [comment]
Never once seen it happen + never been reported in past year.

Closing
