### ISSUE TITLE
Dispel protection

### ISSUE THREAD

**Issue by Hidehugo** [Atlantiss/NetherwingBugtracker#6792]
[//]: # (Enclose links to things related to the bug using http://wowhead.com or any other TBC database.)
[//]: # (You can use screenshot ingame to visual the issue.)
[//]: # (Write your tickets according to the format:)
[//]: # ([Quest][Azuremyst Isle] Red Snapper - Very Tasty!)
[//]: # ([NPC] Magistrix Erona)
[//]: # ([Spell][Mage] Fireball)
[//]: # ([Npc][Drop] Ghostclaw Lynx)
[//]: # ([Web] Armory doesnt work)
[//]: # (To find server revision type `.server info` command in the game chat.)

**Description**: Dispel protection talents from shamans and druids seem to grant absurdly high protection against dispels (can't tell about priests dispel protection since i am playing one). 5 dispels in a row for Rank 1 debuffs needed for dispels. Please investigate

**Current behaviour**: Dispel protection in pvp seems like certain debuffs are undispellable, given that they run out before you get through to dispel it. Dispel Magic e.g. as a priest has 2 chances to dispel a debuff and it seems like it either a) doesn't remove 2 debuffs or b) dispel protection from talents like Healing Grace from shamans or Subtlety from druids is way above the percentage that it should give (got a couple of clips where 4-5 dispels don't lead to a debuff being dispelled which would mean 0.3^10 chance to have this happen while it just happens every second game so i don't believe in "unlucky" or "rng" anymore)

**Expected behaviour**: Talents properly working with the percentages that they should give and no scenarios where 10 dispels in a row don't lead to a debuff being dispelled 

**Server Revision**:

**Comment by Evolvee** [comment]
> Dispel Magic e.g. as a priest has 2 chances to dispel a debuff

thats not true, only one

**Comment by Hidehugo** [comment]
> 
> 
> > Dispel Magic e.g. as a priest has 2 chances to dispel a debuff
> 
> thats not true, only one

Kk, sounds weird but ok. makes the probability of the event to happen only 2 in 1000 and not 4 in 1000000 :D

**Comment by Hidehugo** [comment]
That it only dispels one, where do you take that information from? Couldn't really find data on the logic behind the spell, wether it has a separate logic for the case of only 1 debuff/buff on the target: e.g. first dispel tries to remove debuff and if it fails, second dispel inside the spellcast tries to remove it too or wether it tries to remove the debuff twice simultaneously or wether it tries to only once remove the debuff in that case

**Comment by Evolvee** [comment]
general knowledge

**Comment by DaedalusMachina007** [comment]
Surprised nobody linked the actual spell.  Here's how WoW Classic has it:

https://classic.wowhead.com/spell=988/dispel-magic

> Dispels magic on the target, removing 2 harmful spell from a friend or 2 beneficial spell from an enemy.

So no it isn't 'two chances' to remove a single debuffs/buffs it is a chance to remove 2 individual ones.  It is one 'roll' but if successful it works on both (if both are dispellable) if you have Rank 2 of Dispel Magic.

Certain classes have built in resistances/immunities via talents that can't be mitigated against.  As one example of pure immunity (with enough talent points):

https://tbcdb.com/?spell=35397

> ... reduces the chance your Seals will be dispelled by 100%.

**Comment by Wolffenstein** [comment]
Please test whatever is bugged on the PTR.
