### ISSUE TITLE
[Spell] Perception

### ISSUE THREAD

**Issue by tsuone** [Atlantiss/NetherwingBugtracker#6795]
[//]: # (Enclose links to things related to the bug using http://wowhead.com or any other TBC database.)
[//]: # (You can use screenshot ingame to visual the issue.)
[//]: # (Write your tickets according to the format:)
[//]: # ([Quest][Azuremyst Isle] Red Snapper - Very Tasty!)
[//]: # ([NPC] Magistrix Erona)
[//]: # ([Spell][Mage] Fireball)
[//]: # ([Npc][Drop] Ghostclaw Lynx)
[//]: # ([Web] Armory doesnt work)
[//]: # (To find server revision type `.server info` command in the game chat.)

**Description**: Perception detection is too big.

**Current behaviour**: Perception detection is too big resulting in being able to see Druid in a boot from the grave on Loraderon Arena.

**Expected behaviour**: Perception additional stealth detection be slightly reduced from current value. It should increase stealth detection by 50 points (10 levels), so if the current value is any higher than that it should be reduced to 50.

**Server Revision**: 3315

**Comment by DaedalusMachina007** [comment]
Druids aren't rogues.  Catform is 'fake' as Nhym has always said.  Nelf Shadowmeld used to be broken (for weeks, if I recall) until it was hotfixed later and alliance naturally took full advantage of this (and some still try to do so) not realizing it isn't 'actual' stealth.

Test it with a rogue and provide video please via live/latest server revision if you can.
I'll gladly test with alliance alts if needed.
