### ISSUE TITLE
[Illidan] Illidan randomly moving during transition

### ISSUE THREAD

**Issue by dshgrove** [Atlantiss/NetherwingBugtracker#6798]
[//]: # (Enclose links to things related to the bug using http://wowhead.com or any other TBC database.)
[//]: # (You can use screenshot ingame to visual the issue.)
[//]: # (Write your tickets according to the format:)
[//]: # ([Quest][Azuremyst Isle] Red Snapper - Very Tasty!)
[//]: # ([NPC] Magistrix Erona)
[//]: # ([Spell][Mage] Fireball)
[//]: # ([Npc][Drop] Ghostclaw Lynx)
[//]: # ([Web] Armory doesnt work)
[//]: # (To find server revision type `.server info` command in the game chat.)

**Description**: 
On the transition from phase three to phase four illidan sometimes take a few steps towards the warlock tank before he starts casting. Sometimes even close enough for the warlock to get the increased shadow damage taken debuff.
Although not as severe, this is very similar to #5783.

**Current behaviour**:
illidan moves toward the warlock tank before he starts casting his regular abilities.
[Illidan moving after transition](https://clips.twitch.tv/TubularManlyHamsterMikeHogu)

**Expected behaviour**: 
If he is within range of his target he should just instantly start casting his spells, without moving.
[illidan **not** moving after transition (how it should be)](https://clips.twitch.tv/SuaveDeafJuice4Head)

**Server Revision**: 
3315

**Comment by veekk** [comment]
can confirm this bug, few times killed our hunter, also same on supremus

**Comment by Godmatik** [comment]
Still occurs

**Comment by Godmatik** [comment]
@Wolffenstein @danbopes 

https://www.twitch.tv/cillo/clip/ClumsySlipperyOkapiStoneLightning-_bpqvwYIl4soxgQh?filter=clips&range=7d&sort=time

**Comment by Godmatik** [comment]
Don't remember when, but this was fixed - in demon form Illidan properly goes idle and doesn't attempt to melee the warlock tank anymore.

Can close
