### ISSUE TITLE
[arena] The Arena Eye (for stealth + invis detection) triggers combat upon taking it

### ISSUE THREAD

**Issue by Evolvee** [Atlantiss/NetherwingBugtracker#6799]
this is probably your hackfix @Wolffenstein on how to make the eye drop stealth from ppl

dont think this is intended or should be working this way

**Comment by tsuone** [comment]
It shouldn't trigger a combat, def. a bug.

**Comment by Wolffenstein** [comment]
Fixed in rev 3321.
