### ISSUE TITLE
corpse still on the ground after rezzing

### ISSUE THREAD

**Issue by DarthNekr0s** [Atlantiss/NetherwingBugtracker#68]
![wowscrnshot_092318_082350](https://user-images.githubusercontent.com/16113944/45922284-bb6f1e80-bf0a-11e8-819a-4be77ae5573d.jpg)

**Description**:  died and when i rezzed i saw my corpse still laying there

**Current behaviour**:  for that not to happen

**Expected behaviour**:  should disappear and be replaced with skeleton 

**Server Revision**:

**Comment by wtRCH** [comment]
We are currently working on fixing this issue along with graveyard/release bug.
