### ISSUE TITLE
Slice and Dice bugged

### ISSUE THREAD

**Issue by Giantulol** [Atlantiss/NetherwingBugtracker#680]
**Description**: 
Slice and Dice bugged

**Current behaviour**:
Slice and Dice with 1 combo point awards a 5 second SnD buff, while the 2, 3, 4 and 5 combo points does the same. Tooltip says even 1 combo point has to give a 9 second SnD buff. This makes even the 1 combo point buff to short.

**Expected behaviour**: 
The more combo points the longer the SnD buff according to the tooltip.

**Comment by aresbrutus** [comment]
#625

Duplicate.
