### ISSUE TITLE
all along the watchtowers

### ISSUE THREAD

**Issue by edrake44** [Atlantiss/NetherwingBugtracker#6800]
[//]: # (Enclose links to things related to the bug using http://wowhead.com or any other TBC database.)
[//]: # (You can use screenshot ingame to visual the issue.)
[//]: # (Write your tickets according to the format:)
[//]: # ([Quest][Azuremyst Isle] Red Snapper - Very Tasty!)
[//]: # ([NPC] Magistrix Erona)
[//]: # ([Spell][Mage] Fireball)
[//]: # ([Npc][Drop] Ghostclaw Lynx)
[//]: # ([Web] Armory doesnt work)
[//]: # (To find server revision type `.server info` command in the game chat.)

**Description**: 

**Current behaviour**:

**Expected behaviour**: 

**Server Revision**:

**Comment by edrake44** [comment]
I stand in the doorway just like the quest description says but it doesn't give credit for marking the tower.  It only gives a finite number of charges on the torch and won't let me go back to the quest giver to re-charge or get a new torch.  I can abandon quest and accept again, but at least one of the towers always fails to give credit each time I try, leading me back to the beginning.  The GM directed me here.

**Comment by Evolvee** [comment]
which one of these towers did not work?

**Comment by edrake44** [comment]
It was a different one every time I tried it.  I finally got it at about the 7th or 8th attempt.

**Comment by Evolvee** [comment]
quest rewritten and scripted in next revision
