### ISSUE TITLE
[Hunter] Pets immune to fear

### ISSUE THREAD

**Issue by 4egito** [Atlantiss/NetherwingBugtracker#6802]
[//]: # (Enclose links to things related to the bug using http://wowhead.com or any other TBC database.)
[//]: # (You can use screenshot ingame to visual the issue.)
[//]: # (Write your tickets according to the format:)
[//]: # ([Quest][Azuremyst Isle] Red Snapper - Very Tasty!)
[//]: # ([NPC] Magistrix Erona)
[//]: # ([Spell][Mage] Fireball)
[//]: # ([Npc][Drop] Ghostclaw Lynx)
[//]: # ([Web] Armory doesnt work)
[//]: # (To find server revision type `.server info` command in the game chat.)

**Description**: 
I saw some people in battlegrounds with pets which is immune to fear. I get "Shy-rotam" to test it and that is the result (check video). I believe that "Rak'shiri" have the same issue. 
**Current behaviour**:
https://drive.google.com/open?id=142Z0GjbsvEcqU5ToE0bTkZsY7PhLcWM5
**Expected behaviour**: 
Pets should't be immune to CC except in "Bestial Wrath" or after DR's
**Server Revision**:

**Comment by Evolvee** [comment]
jfc... @Wolffenstein somehow pets probably inherit their creature_template mechanic_immune_mask xdd

**Comment by Wolffenstein** [comment]
Fixed in rev 3320.
