### ISSUE TITLE
Unable to create an account

### ISSUE THREAD

**Issue by MargaritBelichev** [Atlantiss/NetherwingBugtracker#6804]
## Discritpion:
When I try to register I get `500` for `https://atlantiss.eu/account/register`. But when I try to create the same account a second time it says that the email, name, etc. is already taken. If I try to re-send the verification link I get `500` for `https://atlantiss.eu/account/recovery/activation`.

**Comment by Wolffenstein** [comment]
Should be fixed, please retry.

**Comment by MargaritBelichev** [comment]
@Wolffenstein  Yes it's ok now thank you.
