### ISSUE TITLE
[Might of the Scourge]

### ISSUE THREAD

**Issue by tripsixes** [Atlantiss/NetherwingBugtracker#6805]
https://classic.wowhead.com/item=23548/might-of-the-scourge

**Description**: This item is supposed to be able to be applied thru the trade window

**Current behaviour**: When attempting to apply thru the trade window, says that it is only allowed to be applied to your own items

**Expected behaviour**: should be able to be applied to anyone's shoulder armor thru trade

**Comment by veekk** [comment]
same issue with oil via trade
