### ISSUE TITLE
Aura rework

### ISSUE THREAD

**Issue by Dionizodoros** [Atlantiss/NetherwingBugtracker#6806]
These are issues i found on ptr server

 - DST doesn't proc (tested on 1kk dmg done on dummy)

- Proc of Shard of Contempt trinket (Disdain) cancels Sancticity aura

- Judgement of Command doesn't do any damage

- Got some blocks from random mobs like:
![BLOCK](https://user-images.githubusercontent.com/47219637/77795708-4e43c880-706e-11ea-9eda-18c3c804a4bb.png)

- Libram of Divine Judgement procs of Seal of Command and not of Judgement of Comman how it should (tbh not sure if on ptr it's random proc of any damaging ability or just command proc)

- Seal of crusader works incorectly; to reproduce: 
1. use seal of crusader
2. Stack vangance (you could use any other dmg modifying skill like wings or sancticity aura)
3. Switch to seal of command (or any other seal)

**Comment by Wolffenstein** [comment]
![obraz](https://user-images.githubusercontent.com/1576644/77806617-7ee32c80-7085-11ea-9b46-84b08c91d2be.png)
DST seems to be working fine for me, it has 1.5 PPM so the chance might depend on your weapon speed (also half a min cooldown)

**Comment by Wolffenstein** [comment]
Also blocks can happen even on mobs that don't wield shields - ask Blizzard why. Nothing has changed in that regards on the branch

**Comment by Dionizodoros** [comment]
- Oh, well, it just didnt happen on live (as far as i remeber). Tested dst again with help of etherious. No procs after  several minutes of hitting hitting (with haste effect to speed it up).

**Comment by Wolffenstein** [comment]
I don't understand what you mean with Seal of the Crusader.

**Comment by Dionizodoros** [comment]
So if you have seal of crusader up then you get some dmg modyfing ability/proc (vangance/sancticity aura/wings), your base attack dmg changes like seal of crusader didnt lower it. If you then switch seal to another one your base dmg increases quite ridiculously. Im aware my explanation might be confusing. Was trying to explain it as good as i only can though. Here is SS with the final effect:
![Big numbers](https://user-images.githubusercontent.com/47219637/77811032-09cd2280-7098-11ea-972e-9e8e82b209e8.jpg)

**Comment by Wolffenstein** [comment]
Can you just record it for me?

**Comment by Wolffenstein** [comment]
All issues except for DST should be fixed now.

**Comment by Wolffenstein** [comment]
![obraz](https://user-images.githubusercontent.com/1576644/77813300-de523400-70a7-11ea-954b-a53f8334e5c5.png)
Popped for me on PTR on an almost blank character.
