### ISSUE TITLE
Magtheridon's Lair - Trash broken

### ISSUE THREAD

**Issue by Firroth** [Atlantiss/NetherwingBugtracker#6808]
**Current behaviour**:
Trash to Magtheridon, broke after some fix. They are now simply tank and spank, they don't use any abilities except death coil on tank.

**Expected behaviour**: 
This trash should use shadow word pain DoT on entire raid, cast rain of fire on random player, use unstable affiction, cast shadowbolt volley's.

**Server Revision**:

**Comment by Wolffenstein** [comment]
The only bug here is that they don't cast Shadow Burst, which will be fixed in rev 3318. 

The rest is just patch 2.4 nerfs - removal of some of their spells and change of timers for Shadow Bolt Volley.
