### ISSUE TITLE
[Quest] Report to Nasuun

### ISSUE THREAD

**Issue by Tereneckla** [Atlantiss/NetherwingBugtracker#6809]
[//]: # (Enclose links to things related to the bug using http://wowhead.com or any other TBC database.)
[//]: # (You can use screenshot ingame to visual the issue.)
[//]: # (Write your tickets according to the format:)
[//]: # ([Quest][Azuremyst Isle] Red Snapper - Very Tasty!)
[//]: # ([NPC] Magistrix Erona)
[//]: # ([Spell][Mage] Fireball)
[//]: # ([Npc][Drop] Ghostclaw Lynx)
[//]: # ([Web] Armory doesnt work)
[//]: # (To find server revision type `.server info` command in the game chat.)

**Description**: Quest 11517 is the prequest for 11513 during P2b on isle (creating the portal)
These get replaced with 11534 and 11514 after this phase is done.

**Current behaviour**: You need to do 11534 to be able to do 11514, even if you have 11517 completed.

**Expected behaviour**: Having 11517 done should disable 11534 for you and allow you to pick up 11514.

**Server Revision**: 3317

**Comment by Evolvee** [comment]
next rev
