### ISSUE TITLE
[Eversong Woods] Player character hangs in the air after jumping off the ramp

### ISSUE THREAD

**Issue by xml21** [Atlantiss/NetherwingBugtracker#681]
[//]: # (Enclose links to things related to the bug using http://wowhead.com or any other TBC database.)
[//]: # (You can use screenshot ingame to visual the issue.)
[//]: # (Write your tickets according to the format:)
[//]: # ([Quest][Azuremyst Isle] Red Snapper - Very Tasty!)
[//]: # ([NPC] Magistrix Erona)
[//]: # ([Spell][Mage] Fireball)
[//]: # ([Npc][Drop] Ghostclaw Lynx)
[//]: # ([Web] Armory doesnt work)

**Description**: 
While doing quest "Felendren the Banished" (quest id 8335), after killing Felendren I wanted to jump off the top ramp to the water in order to avoid getting down and killing all mobs. While doing so I got stuck in the air and died before reaching water surface.

![wowscrnshot_092618_181845](https://user-images.githubusercontent.com/7996207/46094188-9ce27f00-c1b9-11e8-9362-19c8cdc3d809.jpg)

**Current behaviour**:
Player character hangs in the air after jumping off the ramp

**Expected behaviour**: 
Player character should properly/safely land in water

**Comment by Wolffenstein** [comment]
Fixed in rev 2063.
