### ISSUE TITLE
[Core][Arena] Blade's Edge Moutain pit los

### ISSUE THREAD

**Issue by tsuone** [Atlantiss/NetherwingBugtracker#6811]
[//]: # (Enclose links to things related to the bug using http://wowhead.com or any other TBC database.)
[//]: # (You can use screenshot ingame to visual the issue.)
[//]: # (Write your tickets according to the format:)
[//]: # ([Quest][Azuremyst Isle] Red Snapper - Very Tasty!)
[//]: # ([NPC] Magistrix Erona)
[//]: # ([Spell][Mage] Fireball)
[//]: # ([Npc][Drop] Ghostclaw Lynx)
[//]: # ([Web] Armory doesnt work)
[//]: # (To find server revision type `.server info` command in the game chat.)

**Description**: When you are playing a gnome and sit in the pit underneeth the bridge, you are LoS from the healer who is on the ground near the pit... @Evolvee 

**Current behaviour**: Pit line of sight incoming spells if you are a gnome.

**Expected behaviour**: Pit shouldn't los incomign spells when playing a small size character fx. gnome.

**Server Revision**: 3317

**Comment by Evolvee** [comment]
screenshot?

**Comment by Wolffenstein** [comment]
Different models have different heights. Blizzlike.
