### ISSUE TITLE
[Quest] The Rescue [NPC] Drull - [Zone] Durnholde Keep 

### ISSUE THREAD

**Issue by drewk8** [Atlantiss/NetherwingBugtracker#6812]
**Description**: 
During the rescue quest where you have to release the prisioners (unlock ball&chains), as a rogue, you are able to lockpick the chains. The NPC talks and thanks you for releasing him, but progress is not marked in the quest log.

**Current behavior**:
Able to lockpick the chains, NPC acknowledges the action, but no progress is logged. It works fine with the key drops though.

**Expected behavior**: 
I found few references that the ball and chain can actually be lock-picked. If this is the case, then the progress should also be logged correctly.

**Server Revision**: 
3317

**Comment by Evolvee** [comment]
fixed in next revision
