### ISSUE TITLE
[Battlegrounds] Queue battleground not working properly for grouped people

### ISSUE THREAD

**Issue by ArnaudRm** [Atlantiss/NetherwingBugtracker#6813]
Description:

The issue comes when you tag a battleground while in a group. The person who actually tags has no problem, but the people grouped can't see the waiting time and other info that are actually displayed in the top-right corner (red icon). Moreover, grouped people can still tag on their own despite the fact that they are already tagged in the group, and this resets their position in queue (tag causes to cancel the group tag)

Current behaviour:

Group tag doesn't work for people grouped as intended. It doesn't allow grouped people to see queue related informations. Moreover, grouped people (except the person who tag, group leader) can still queue for bg despite the fact that they have already been queued with the group, which resets their position in queue. 

Expected behaviour:

Grouped people should see the queue informations. They shouldn't be able to queu on their own once they have been queued in a group to a battleground.

Server Revision: 3317

**Comment by Evolvee** [comment]
related to this
https://github.com/Atlantiss/NetherwingBugtracker/issues/6519

**Comment by Wolffenstein** [comment]
Fixed in rev 3350.
