### ISSUE TITLE
[core][spell][aura stacking] Multiple visual spells targeting the same 1 trigger gets canceled for all NPCs if 1 spell cast is canceled/interrupted

### ISSUE THREAD

**Issue by Evolvee** [Atlantiss/NetherwingBugtracker#6814]
the stacking probably identifies 1 stack of the spell removal = entire buff removal

example: throne of kiljeaden npcs casting beams on trigger, when you aggro 1, the rest cancels the visual spell cast (my guess is that its triggered by the trigger itself)

example 2: you kill one of these npcs, all stop channeling 
![image](https://user-images.githubusercontent.com/1942409/78056855-10a0b180-7386-11ea-86e7-a56b2614e138.png)

**Comment by Wolffenstein** [comment]
Please retest on the PTR.

**Comment by Evolvee** [comment]
seems working
