### ISSUE TITLE
TK - Al'ar

### ISSUE THREAD

**Issue by Bonenemesis** [Atlantiss/NetherwingBugtracker#6815]
Dear Developers,

During Phase 1, the boss is supposed to fly to platform 1, 2, 3, 4 and dive. atm, the boss is flying to random platforms and diving. for example he was flying to platform 4, then dive and flying to 'playform 5', which isn't a platform at all. Can you please take a look at it whenever you have time?

Many thanks,
Bonenemesis

**Comment by eri1997** [comment]
This is intended. It's a prenerf boss mechanic that was kept from 2.0 version like some other boss mechanics that were changed on retail later patches but we're kept here to not make the fights a joke
