### ISSUE TITLE
[Quest]The First Trial (horde paladin) can not be turned in

### ISSUE THREAD

**Issue by Xlatus** [Atlantiss/NetherwingBugtracker#6816]
[//]: # (Enclose links to things related to the bug using http://wowhead.com or any other TBC database.)
[//]: # (You can use screenshot ingame to visual the issue.)
[//]: # (Write your tickets according to the format:)
[//]: # ([Quest][Azuremyst Isle] Red Snapper - Very Tasty!)
[//]: # ([NPC] Magistrix Erona)
[//]: # ([Spell][Mage] Fireball)
[//]: # ([Npc][Drop] Ghostclaw Lynx)
[//]: # ([Web] Armory doesnt work)
[//]: # (To find server revision type `.server info` command in the game chat.)

**Description**: 
The First Trial (horde paladin) quest can not be turned in to NPC Lord Bloodvalor in Silvermoon City
**Current behaviour**:
I have completed the quest by summoning and killing the required mob on the island in Ghostlands, and the quest shows as Completed in my questlog, but I can not turn it in to the Questgiver
**Expected behaviour**: 
The questgiver Should allow for a Completed quest to be turned in.
**Server Revision**:

**Comment by Evolvee** [comment]
works fine for me, try to delete cache
