### ISSUE TITLE
[Pets][SWP][Twins] Twins debuffs don't get removed from pets on boss reset

### ISSUE THREAD

**Issue by eri1997** [Atlantiss/NetherwingBugtracker#6819]
[//]: # (Enclose links to things related to the bug using http://wowhead.com or any other TBC database.)
[//]: # (You can use screenshot ingame to visual the issue.)
[//]: # (Write your tickets according to the format:)
[//]: # ([Quest][Azuremyst Isle] Red Snapper - Very Tasty!)
[//]: # ([NPC] Magistrix Erona)
[//]: # ([Spell][Mage] Fireball)
[//]: # ([Npc][Drop] Ghostclaw Lynx)
[//]: # ([Web] Armory doesnt work)
[//]: # (To find server revision type `.server info` command in the game chat.)

**Description**: Title

**Current behaviour**: Title

**Expected behaviour**: debuffs get removed from players so I assume they should be removed from pets too 

**Server Revision**: 3319

**Comment by Wolffenstein** [comment]
Fixed in rev 3320.
