### ISSUE TITLE
Zeb'Nowa Shadowpine Catlord#16345 & Shadowpine Hexxer#16346 missing patrols

### ISSUE THREAD

**Issue by Tenoutoften** [Atlantiss/NetherwingBugtracker#682]
**Description**: 
A [[NPC]Shadowpine Catlord#16345](https://db.excalibur.ws/?npc=16345) is suppose to patrol at 67.50, 54.50 can be seen here: https://youtu.be/Ryg1KLVOH9w?t=354

A [[NPC]Shadowpine Hexxer#16346](https://db.excalibur.ws/?npc=16346) is spotted at https://youtu.be/Ryg1KLVOH9w?t=360 waking south out of vision as the guy kills the [[NPC]Shadowpine Catlord#16345](https://db.excalibur.ws/?npc=16345) patrol mentioned above. He re-appears at https://youtu.be/Ryg1KLVOH9w?t=395 you can see him through the gap of the trees, now walking north towards the player. Indicating a not too long patrol.

At https://youtu.be/Ryg1KLVOH9w?t=523 a patrolling [[NPC]Shadowpine Hexxer#16346](https://db.excalibur.ws/?npc=16346) is observed, on Netherwing this NPC is a [[NPC]Shadowpine Catlord#16345](https://db.excalibur.ws/?npc=16345) picture [here](https://i.gyazo.com/e7e96a422a43c45139dbd41cbbd4c578.png) instead, location; 64.0, 67.8 roughly

At https://youtu.be/E1LRcXR-Sqc?t=146 it looks like a patrolling [[NPC]Shadowpine Hexxer#16346](https://db.excalibur.ws/?npc=16346) is spawning, it is quickly killed though so not sure where it was heading. Coords 64.2, 68.5

**Current behaviour**:
Zero patrols

**Expected behaviour**: 
Expecting several patrols at this place

**Server Revision**: 
2060

**Comment by aresbrutus** [comment]
Fixed in rev `Ilus`
