### ISSUE TITLE
[NPC] Exarch Nasuun not showing progress on Sun's Reach Harbor

### ISSUE THREAD

**Issue by eri1997** [Atlantiss/NetherwingBugtracker#6820]
[//]: # (Enclose links to things related to the bug using http://wowhead.com or any other TBC database.)
[//]: # (You can use screenshot ingame to visual the issue.)
[//]: # (Write your tickets according to the format:)
[//]: # ([Quest][Azuremyst Isle] Red Snapper - Very Tasty!)
[//]: # ([NPC] Magistrix Erona)
[//]: # ([Spell][Mage] Fireball)
[//]: # ([Npc][Drop] Ghostclaw Lynx)
[//]: # ([Web] Armory doesnt work)
[//]: # (To find server revision type `.server info` command in the game chat.)

**Description**: Sun's Reach Harbor progress shows as 0 % on this npc(2nd chat option). He shows correct % for Sun's Reach Armory(1st chat option).

**Current behaviour**: bugged for 1 of the options, the other option works

**Expected behaviour**: Sun's harbor should show progress too

**Server Revision**: 3319

**Comment by Wolffenstein** [comment]
It should be fixed now.
