### ISSUE TITLE
[PTR][Druid] Nature's grace proc does not occur

### ISSUE THREAD

**Issue by Onsty** [Atlantiss/NetherwingBugtracker#6821]
**Description**: 
Nature's grace proc does not occur at all

**Current behaviour**:
None of druids spells does not proc [Nature's grace] (balance druids talent)
![41c20eb60099246da21336786620d599](https://user-images.githubusercontent.com/44346265/78281433-547ced80-7523-11ea-843a-8f78880e8dbd.png)

**Expected behaviour**: 

**Server Revision**: 
[PTR]

**Comment by Wolffenstein** [comment]
Will be fixed after restart.
