### ISSUE TITLE
[Item][Quest] Shattered Necklace

### ISSUE THREAD

**Issue by The14me** [Atlantiss/NetherwingBugtracker#6822]
**Current behaviour**: You got an error with alliance too when u try to pick up the item and start the quest
https://imgur.com/a/dUzbJuD

**Expected behaviour**: 
You suppose to be able to pick up and start the quest if u are an alliance
https://classic.wowhead.com/item=7666/shattered-necklace
https://classic.wowhead.com/item=7666/shattered-necklace

**Server Revision**: 
3320

**Comment by DaedalusMachina007** [comment]
Here's the quest that the item refers to:
https://classic.wowhead.com/quest=2198/the-shattered-necklace

**Comment by Wolffenstein** [comment]
Fixed in rev 3387.
