### ISSUE TITLE
[PTR] [Paladin] Illumination and Divine Illumination

### ISSUE THREAD

**Issue by Sagoona** [Atlantiss/NetherwingBugtracker#6823]
[//]: # (Enclose links to things related to the bug using http://wowhead.com or any other TBC database.)
[//]: # (You can use screenshot ingame to visual the issue.)
[//]: # (Write your tickets according to the format:)
[//]: # ([Quest][Azuremyst Isle] Red Snapper - Very Tasty!)
[//]: # ([NPC] Magistrix Erona)
[//]: # ([Spell][Mage] Fireball)
[//]: # ([Npc][Drop] Ghostclaw Lynx)
[//]: # ([Web] Armory doesnt work)
[//]: # (To find server revision type `.server info` command in the game chat.)

**Description**: 
Illumination combined with using Divine Illumination returns the wrong amount of Mana on crits.
**Current behaviour**:
Illumination and its profit on crits is being derived from the current mana costs. While Divine Illumination is active the current mana cost drops to 50%.
PTR (Rev. 3319 [Branch: auras_2020]):
https://i.imgur.com/5mENC9B.png
**Expected behaviour**: 
Illumination should derive its benefit from the base mana costs no matter if Divine Illumination is active or not.
Live (Rev. 3320):
https://i.imgur.com/MV6lyZm.png

**Comment by Wolffenstein** [comment]
Should be fixed.
