### ISSUE TITLE
[Profession] Fel Iron Shells

### ISSUE THREAD

**Issue by tsuone** [Atlantiss/NetherwingBugtracker#6826]
[//]: # (Enclose links to things related to the bug using http://wowhead.com or any other TBC database.)
[//]: # (You can use screenshot ingame to visual the issue.)
[//]: # (Write your tickets according to the format:)
[//]: # ([Quest][Azuremyst Isle] Red Snapper - Very Tasty!)
[//]: # ([NPC] Magistrix Erona)
[//]: # ([Spell][Mage] Fireball)
[//]: # ([Npc][Drop] Ghostclaw Lynx)
[//]: # ([Web] Armory doesnt work)
[//]: # (To find server revision type `.server info` command in the game chat.)

**Description**: Incorrect amount of shells on craft.

**Current behaviour**: You get twice as much Fel Iron Shells than described.
![image](https://user-images.githubusercontent.com/11255782/78433447-00cee900-7676-11ea-89a2-c4ce2a98323e.png)

**Expected behaviour**: You should get 200 Fel Iron Shells instead of 400.

**Server Revision**: 3320

**Comment by Evolvee** [comment]
![image](https://user-images.githubusercontent.com/1942409/78471657-3dace580-7733-11ea-9f8a-a7b25e62c1cc.png)

**Comment by Evolvee** [comment]
its working as the spell is intended, would need proof of the 200 stack only

**Comment by DaedalusMachina007** [comment]
Confirmed this is 2 stacks of 200 each (total 400) according to TBC databases and wowwiki/wowpedia archives:

https://tbcdb.com/?spell=30346
http://tbc.cavernoftime.com/spell=30346
https://wow.gamepedia.com/Fel_Iron_Shells

**Comment by Tereneckla** [comment]
http://web.archive.org/web/20080329192943/http://thottbot.com:80/i23772

**Comment by Evolvee** [comment]
?

**Comment by Evolvee** [comment]
should be 400
