### ISSUE TITLE
[Dungeon] The Mechanar Cache of the Legion

### ISSUE THREAD

**Issue by Msbhv1** [Atlantiss/NetherwingBugtracker#6827]
[//]: # (Enclose links to things related to the bug using http://wowhead.com or any other TBC database.)
[//]: # (You can use screenshot ingame to visual the issue.)
[//]: # (Write your tickets according to the format:)
[//]: # ([Quest][Azuremyst Isle] Red Snapper - Very Tasty!)
[//]: # ([NPC] Magistrix Erona)
[//]: # ([Spell][Mage] Fireball)
[//]: # ([Npc][Drop] Ghostclaw Lynx)
[//]: # ([Web] Armory doesnt work)
[//]: # (To find server revision type `.server info` command in the game chat.)

**Description**: Upon doing The Mechanar dungeon couldn't open cache of the legion

**Current behaviour**:
Collected all of the parts to combine the key, key got consumed but the cache remained closed.
**Expected behaviour**: 
Open the cache due to completing the key.
**Server Revision**:

**Comment by tsuone** [comment]
Appears like hispanic inquisition... each patch 🤣

**Comment by DaedalusMachina007** [comment]
I realize this is a later patch (4.0.3 according to wowhead), but Blizzard made the chest automatically unlock itself once Gatekeeper Gyro-Kill is defeated.  This may be a better workaround than 'fixing' this issue whenever it comes up.

Another potential workaround is permit this chest to be opened by rogues with lockpicking, blacksmiths with arcanite key, engineers with the seaforium charge, etc. in case the key doesn't spawn.  Just require the chest spawn be triggered by the defeat of a boss to mitigate 'stealth-only' runs.

**Comment by Godmatik** [comment]
Have not once heard of this issue occurring on Netherwing server.

Probably was fixed at some point.
