### ISSUE TITLE
Blackrock Depths doors closing

### ISSUE THREAD

**Issue by Chipslock** [Atlantiss/NetherwingBugtracker#6829]
[//]: # (Enclose links to things related to the bug using http://wowhead.com or any other TBC database.)

**Description**: The bar door in blackroc depths shut themselves

**Current behaviour**: Doors shut after 10 mins

**Expected behaviour**: Doors dont shut

**Server Revision**:

**Comment by Evolvee** [comment]
which door

**Comment by DaedalusMachina007** [comment]
@Evolvee The 'Rear Door' of the Grim Guzzler:
https://wow.gamepedia.com/Grim_Guzzler

Easiest way to open it without fuss is to have at least one person in group do 'The Love Potion' quest:
https://wow.gamepedia.com/The_Love_Potion_(quest)

There are too many ways for the door to bug out closed if your group doesn't move fast enough.

On Blizzard servers, the door gets closed by 'additional security' if you fight Phalanx in the bar and after defeating them then the door opens for good.  I don't believe this triggers properly on this server so if you don't immediately pull Phalanx outside the bar and fight him there, then there's a good chance of the door being stuck shut and not opening again.

Another easier way is to either kill Plugger Spazzring or have a rogue pickpocket him and stack the group away from the other bar patrons while the rogue opens the door.

**Comment by Godmatik** [comment]
Closing - all BRD information will be consolidated into one thread
