### ISSUE TITLE
[NPC] Neutral mobs suspect stealthed player

### ISSUE THREAD

**Issue by weirdbiz** [Atlantiss/NetherwingBugtracker#683]
**Description**: 
Yellow (Neutral attackable) mobs are aware of rogue presence while player is in stealth nearby.
**Current behaviour**:
Neutral mobs turn and stare to stealthed rogue (like if it were Agressive Red mobs, they would become 'suspecting' but would not aggro to player). Being able to reproduce this on Neutral Kobolds in Northshire.
**Expected behaviour**: 
Neutral mobs should not care of stealthed rogue, like they don't care of normal character.
**Server Revision**: 
2060

**Comment by The14me** [comment]
can u give some mob for example or its any neutral mob?

**Comment by weirdbiz** [comment]
Young Wolf, Kobold Worker, both in Northshire Valley

**Comment by Wolffenstein** [comment]
Fixed in rev 2063.
