### ISSUE TITLE
[Core] Arena "/afk"

### ISSUE THREAD

**Issue by tsuone** [Atlantiss/NetherwingBugtracker#6830]
[//]: # (Enclose links to things related to the bug using http://wowhead.com or any other TBC database.)
[//]: # (You can use screenshot ingame to visual the issue.)
[//]: # (Write your tickets according to the format:)
[//]: # ([Quest][Azuremyst Isle] Red Snapper - Very Tasty!)
[//]: # ([NPC] Magistrix Erona)
[//]: # ([Spell][Mage] Fireball)
[//]: # ([Npc][Drop] Ghostclaw Lynx)
[//]: # ([Web] Armory doesnt work)
[//]: # (To find server revision type `.server info` command in the game chat.)

**Description**: /AFK doens't remove you from arena.

**Current behaviour**: "/afk" doesn't remove you from the arena.

**Expected behaviour**: "/afk" should remove you from the arena.

**Server Revision**: 3320

**Comment by Evolvee** [comment]
proof?

**Comment by tsuone** [comment]
Do it on retail. It is easier and faster to leave arena when your teammate die. QoL feature.

**Comment by tsuone** [comment]
https://www.ownedcore.com/forums/world-of-warcraft/world-of-warcraft-general/136220-question-leave-arena-bg-macro.html

**Comment by tsuone** [comment]
![image](https://user-images.githubusercontent.com/11255782/78509351-b17bdc00-778d-11ea-87c5-6991968cd91b.png)

**Comment by Evolvee** [comment]
we are talking about arenas, not bgs

and the link doesnt say anything
