### ISSUE TITLE
[core][wolf ai] Combat triggered aoe spellcasts need to be a little smarter

### ISSUE THREAD

**Issue by Evolvee** [Atlantiss/NetherwingBugtracker#6831]
E.g. npc 22323 spell 39055

![image](https://user-images.githubusercontent.com/1942409/78462010-59ca6b80-76ce-11ea-9e7e-f9a6621f000d.png)

is being casted even when the object(npc) is 30 yards away from its victim
it should only be casted when in range to the victim - i hope this still works for all the other usual aoes (no matter if target caster or victim)

**Comment by Wolffenstein** [comment]
Problem is 39055 itself doesnt have any radius or range

**Comment by DaedalusMachina007** [comment]
SpellRange: (ID 1) "Self Only" is why it doesn't have a specified radius/range.  Might need to change it to a different spellrange id category in order to give it a minimum/max range.

**Comment by Evolvee** [comment]
the fix is to ignore attributes of the main spell and consider only data from the triggered spell... doing this globally would probably cause fucktons of issues, so some new flag could be implemented and manually added to npcs with similar spells

**Comment by Godmatik** [comment]
Wolf fixed this a few months ago before 2.4 patch launched - closing
