### ISSUE TITLE
[Talent][Paladin] One-handed weapon specialization increases two-handed damage

### ISSUE THREAD

**Issue by tvararu** [Atlantiss/NetherwingBugtracker#6834]
**Description**: 1h weapon specialization increases 2h weapon damage.

Here's a screenshot; you can tell it's a 2h weapon because it's sheathed on the back. I have 2 points invested into 1h weapon specialization, I get a multiplier of 102% applied to my autos.

![1hws](https://user-images.githubusercontent.com/1650875/78473527-41dc0180-7739-11ea-8a55-b53bcb3da426.png)

**Current behaviour**: 1h weapon specialization increases 2h weapon damage.

**Expected behaviour**: 1h weapon specialization does not increase 2h weapon damage.

**Server Revision**: 3320

**Comment by Tereneckla** [comment]
Will be fixed in the aura rework
