### ISSUE TITLE
 DMF(Darkmoon Faire) schedule not matching the blizzlike times.

### ISSUE THREAD

**Issue by bastian626** [Atlantiss/NetherwingBugtracker#6835]
**Description**: DMF(Darkmoon Faire) schedule not matching the blizzlike times.

**Current behaviour**: According to various players Darkmoon Faire was up until Saturday 4th of April.  
Last month was about the same, went to check Darkmoon Faire  at the end of Sunday 8th of March, people told me it was up last week. 

So looks like DMF is being cheduled 1 week earlier, and ending on thw wrong day.

**Expected behaviour**: 
https://es.classic.wowhead.com/guides/classic-darkmoon-faire
Darkmoon Faire arrives on the first Friday of every month and begins setup.
Sets up over the weekend
Opens on Monday
Closes the following Sunday

**Server Revision**: 3320

**Comment by DaedalusMachina007** [comment]
Confirmed this is an issue.  DMF was up a week early and nobody said anything about it in announcements or otherwise.

**Comment by DaedalusMachina007** [comment]
DMF is gone now (Tuesday April 7th at midnight server time).  This is really non-Blizzlike if it is gonna keep poofing like this.

Will we get DMF for the entire week or will we have to wait a month again?

**Comment by NatsumeLily** [comment]
It was only up for extra day (2 days?) because a GM triggered. 

Yes, you will need to wait if you missed the extra day(s).

**Comment by preydog** [comment]
This is still bugged as of 7/10/2020.  I've been checking the major cities since first weekend of the month and never showed up.  Any updates on this?

**Comment by therealCrysis** [comment]
Still bugged

**Comment by Godmatik** [comment]
Fixed - please can close
