### ISSUE TITLE
[Darkmoon Faire][Quest] Your Fortune Awaits You (All)

### ISSUE THREAD

**Issue by DaedalusMachina007** [Atlantiss/NetherwingBugtracker#6838]
**Quest Links:**
Wailing Caverns (The Barrens): https://classic.wowhead.com/quest=7944/your-fortune-awaits-you
Eastvale Logging Camp (Elwynn Forest): https://classic.wowhead.com/quest=7937/your-fortune-awaits-you
Palemane Rock (Mulgore): https://classic.wowhead.com/quest=7945/your-fortune-awaits-you
The Deadmines (Westfall): https://classic.wowhead.com/quest=7938/your-fortune-awaits-you

**Description**:
These quests are provided by NPC 'Sayge' of the Darkmoon Faire (https://classic.wowhead.com/npc=14822/sayge) after obtaining a fortune buff. 

**Current behaviour**:
The quests can only be completed ONCE and are NOT repeatable.

**Expected behaviour**: 
The quests should be repeatable as they are the ONLY source of reputation gain (after Friendly) outside of collecting full decks of DMF cards. 

**Server Revision**:  Current live server version

**Comment by Evolvee** [comment]
any proof it should be repeatable?
also repeatable per event or repeatable every day? every month?

**Comment by DaedalusMachina007** [comment]
Just found this:
https://classicdb.ch/?quest=7944

It is live on retail WoW Classic if anyone there wants to double-check it.

**Comment by Tereneckla** [comment]
The should be repeatable, are repeatable on PTR and were repeatable on live a month ago.

**Comment by DaedalusMachina007** [comment]
Why was this closed?  They are repeatable and here is your proof:
https://wow.gamepedia.com/Darkmoon_Faire_(Classic)

That's from the TBC version of Darkmoon Faire that states:

> A final method of gaining reputation above 2000 Friendly is completing any of the four versions of the quest entitled Your Fortune Awaits You.... Four of the possible twenty-nine fortunes offered by Sayge at the Darkmoon Faire start this quest. They have players seek a chest in The Deadmines, The Wailing Caverns, Palemane Rock, or Eastvale Logging Camp. These quests reward 75 reputation each, (as well as the contents of the chest) and they can be repeated, provided you are able to get the fortune again. Because of the long cooldown on Sayge's fortunes and the approximate 14% chance to get one of these fortunes, increasing your reputation this way is very slow work.

Changing things and then demanding 'proof' from retail is not the way to run things.  One does not change things like this unless it is a bugfix (and actually verified as a bug).

The quests only reward reputation.  They don't reward exp.  So repeating them offers only the reputation benefit (and the mediocre item rewards from the chest).

**Comment by Evolvee** [comment]
they are repeatable on NW someone said ^^

**Comment by DaedalusMachina007** [comment]
> they are repeatable on NW someone said ^^

I don't know who told you that, but they should've checked on the live servers (where the bug is) not the PTR.  They are NOT repeatable on live servers.  I literally just checked right now.

This quest specifically is what I checked:
https://classic.wowhead.com/quest=7937/your-fortune-awaits-you

I had two fortunes for this quest, one actually active and one on standby from the fortune item that Sayge (the fortune NPC) gives you.  Completed quest the first time, tried to 'use' the other (same) fortune again but it gave me the 'You are already on that quest' error, meaning I had already completed it and the quests are NOT marked as repeatables.

Please re-open this issue until it is fixed because it is NOT resolved!

**Comment by Tereneckla** [comment]
Still repeatable on live aswell. Did 2 Wailing Caverns last DMF
