### ISSUE TITLE
Items disappearing from the mobs after invisible roll

### ISSUE THREAD

**Issue by Makuuuu** [Atlantiss/NetherwingBugtracker#6839]
[//]: # (Enclose links to things related to the bug using http://wowhead.com or any other TBC database.)
[//]: # (You can use screenshot ingame to visual the issue.)
[//]: # (Write your tickets according to the format:)
[//]: # ([Quest][Azuremyst Isle] Red Snapper - Very Tasty!)
[//]: # ([NPC] Magistrix Erona)
[//]: # ([Spell][Mage] Fireball)
[//]: # ([Npc][Drop] Ghostclaw Lynx)
[//]: # ([Web] Armory doesnt work)
[//]: # (To find server revision type `.server info` command in the game chat.)

**Description**: 
While progressing Hyjal with my guild, I died during one wave. I decided to run back in the spirit form and I missed one wave entirely. I joined the fight on the next one. After the wave was killed, we started looting the mobs. Suddenly my guildmates started cheering because they saw that a fist dropped. I was already there, but I didn't see any roll for that item, so I was very confused. They said that also a back dropped, but I didn't see it either. After the roll ended, noone won the items and they disappeared from the mobs.
There's a video that I filmed that day, it's from my perspective and it's in czech language. It's 12 minutes long, but the "roll" itself starts at 7:40.
https://www.twitch.tv/videos/585527471
**Current behaviour**:
I don't know, it happened last week.
**Expected behaviour**: 
I would expect to see the roll as well or at least to see that someone won the items, if I wasn't eligible due to the spirit form.
**Server Revision**: 
3320

**Comment by Wolffenstein** [comment]
The info about rolls is only broadcasted to eligible players.

**Comment by Makuuuu** [comment]
Yes, but they didn't get the items either, even tho they could roll on them.
