### ISSUE TITLE
[Suggestion] 100% Quest Item Droprate

### ISSUE THREAD

**Issue by DaedalusMachina007** [Atlantiss/NetherwingBugtracker#6842]
**Description**:   Quest Item Droprates on a wide variety of quests (mostly in Azeroth but many in Outland as well) are far lower than necessary.  It isn't 'fun' and just having higher XP rates or 'instant 58' is just a band-aid fix on what should be a much easier solution.

**Current behaviour**:  Quest Item Droprates are 'blizzlike' for better or worse, with droprates as low as 15% (Nearly any drop quest in Barrens) or worse depending on RNG and how many others are competing with mob kills.

One of many (retail) threads complaining about it in WoW Classic:
https://us.forums.blizzard.com/en/wow/t/drop-rates-in-the-barrens-are-a-freaking-jokes/284069/10

**Suggested behaviour**:  Make any item marked as a 'Quest' item have a 100% droprate.  That's it.  Items that drop WITHOUT requiring the quest wouldn't be affected.

Affected: https://classic.wowhead.com/quest=867/harpy-raiders
They drop this item marked as 'Quest' item only and ONLY drops when you have the quest: https://classic.wowhead.com/item=5064/witchwing-talon

NOT Affected: https://classic.wowhead.com/quest=338/the-green-hills-of-stranglethorn
They are from these types of items: https://classic.wowhead.com/item=2725/green-hills-of-stranglethorn-page-1  that are NOT marked as quest items.
They drop various pages with a random % chance and they drop even if you don't have the quest.

**Server Revision**:  Irrelevant, but whatever the current version is.

Literally do a search on this github (or the Discord) for 'low droprate' and see how many times it comes up.  It was an issue in Vanilla and TBC and is still an issue here.  There's no need for 'blizzlike' drop rates anymore.

**Comment by Wolffenstein** [comment]
no
