### ISSUE TITLE
Sathrovarr doesn't wipe your threat if you die and are battle rezzed on Kalecgos fight.

### ISSUE THREAD

**Issue by maidros** [Atlantiss/NetherwingBugtracker#6843]
**Description**: 
https://www.youtube.com/watch?v=K3sJ1Gzd5bI

During the Kalecgos encounter, I took a portal downstairs to attack Sathrovarr but our druid tank got ported up. Sath immediately turned and started attacking me instead of Kalec. After I died, I was battle rezzed and immediately was portalled down stairs, whereupon SATHROVARR RAN OVER AND CHASED ME DOWN AGAIN after I had already died and my threat was (should have been) wiped off his threat table.

If you look in the video above, my target and target of target frames are at the bottom. Initially he is targetting Brambie, the orange nameplate, then he switches to me, the pink nameplate. And then after I go down again, he switches to again to target me if you look at the nameplates, and I get melee'd for no reason except that I am a straight white male.

**Current behaviour**:
Sathrovarr (and possibly Kalecgos) maintain you on their threat table after you die.

**Expected behaviour**: 
When you die, you leave combat and so should be erased from their threat table.

**Server Revision**: 
AtlantissCoreTBC - Server Revision: 3320 [Branch: master, Hash: dec9343bd819]

**Comment by veekk** [comment]
Also weird that Sath attacking some1 else instead of Kalecgos when tank tped out

**Comment by maidros** [comment]
here is the legacyplayers log, go to the kill attempt, it's where i died twice in the video above: https://legacyplayers.com/Raids/Viewer/Default.aspx?id=11179&exp=1&upl=17133

**Comment by Godmatik** [comment]
Tank threat issue was resolved on Netherwing
