### ISSUE TITLE
[PTR] Master Firestone

### ISSUE THREAD

**Issue by AWIDIUS** [Atlantiss/NetherwingBugtracker#6844]
Warlock's "Master Firestone" item is replacing wand slot. Its own weapon buff overwrites current temporary enchantment (e.g. Superior Wizard Oil). 
![image](https://user-images.githubusercontent.com/45521546/78899468-bc788a00-7a75-11ea-9555-f4cf7ad051e3.png)

**Comment by Wolffenstein** [comment]
Not a bug, these don't stack.

**Comment by AWIDIUS** [comment]
I do not talk about stacking. I have problems with keeping my Wizard Oil enchantment on that weapon whilst Master Firestone is equipped
Give me a minute Ill record that

**Comment by lyubomeer** [comment]
![image](https://user-images.githubusercontent.com/11522170/79047331-9b9f6880-7c1e-11ea-9edf-9ac54d18bb8b.png)

**Comment by AWIDIUS** [comment]
https://www.youtube.com/watch?v=U7s-h3ngcco&feature=youtu.be @Wolffenstein
