### ISSUE TITLE
[Quest] The Cipher of Damnation - Ar'tor's Charge [Item]

### ISSUE THREAD

**Issue by The14me** [Atlantiss/NetherwingBugtracker#6845]
**Current behaviour**:
[Second Fragment ](https://www.wowhead.com/item=30453/second-fragment-of-the-cipher-of-damnation) is way below 99% drop rate.

**Expected behaviour**: 
[The Cipher of Damnation - Ar'tor's Charge](https://www.wowhead.com/quest=10540/the-cipher-of-damnation-artors-charge)
 The fragment must have 99% drop rate 
Related  issue for the quest
https://github.com/Atlantiss/NetherwingBugtracker/issues/2704
**Server Revision**: 
3320

**Comment by Godmatik** [comment]
![rtyrtyrtyrt](https://github.com/Atlantiss/NetherwingBugtracker/assets/37913400/7d537de5-8a75-4a39-822e-5ad7fd3e5db6)

Also classic wowhead shows it at 87%

Seems it is set correctly.

Closing
