### ISSUE TITLE
 [Quest] When the Cows Come Home

### ISSUE THREAD

**Issue by The14me** [Atlantiss/NetherwingBugtracker#6846]
**Current behaviour**:Some times when u are in party quest fail for one of the players
https://www.wowhead.com/quest=10337/when-the-cows-come-home
https://cdn.discordapp.com/attachments/698134399618646137/698134462302519346/WoWScrnShot_041020_043327.jpg

**Expected behaviour**: 

**Server Revision**:

**Comment by Wolffenstein** [comment]
Fixed in rev 3387.
