### ISSUE TITLE
[PTR]Warior -Deep wounds, Bloodthirst

### ISSUE THREAD

**Issue by Miikell** [Atlantiss/NetherwingBugtracker#6847]
Bloodthirst
https://tbc-twinhead.twinstar.cz/?spell=30335
Deep Wounds
https://tbc-twinhead.twinstar.cz/?spell=12867

**Current behaviour:** 
Bloodthirst dont restore health

Deep Wounds dot refreshed after each crit, and countdown starting from 0.
So when you have fast weapons and lot of crit chance the DOT dont doing dmg, only refresh timer.

**Expected behaviour:** 
Blloodthirst should restore health
In addition, the next 5 successful melee attacks will restore 30 health

DeepWound
The dot from deepwound should be prolong after crit, but dmg should be still applied every 3s.

**Server Revision** :3319

**Comment by Wolffenstein** [comment]
The Deep Wounds part is not a bug, that's just how the spell works.

**Comment by Wolffenstein** [comment]
Bloodthirst fixed.
