### ISSUE TITLE
[PTR] [Aura systemg] Warp-Spring Coil

### ISSUE THREAD

**Issue by Erodraeda** [Atlantiss/NetherwingBugtracker#6848]
[//]: # (Enclose links to things related to the bug using http://wowhead.com or any other TBC database.)
[//]: # (You can use screenshot ingame to visual the issue.)
[//]: # (Write your tickets according to the format:)
[//]: # ([Quest][Azuremyst Isle] Red Snapper - Very Tasty!)
[//]: # ([NPC] Magistrix Erona)
[//]: # ([Spell][Mage] Fireball)
[//]: # ([Npc][Drop] Ghostclaw Lynx)
[//]: # ([Web] Armory doesnt work)
[//]: # (To find server revision type `.server info` command in the game chat.)

**Description**: 
On the PTR server, testing new auras and procs, the Warp-Spring Coil proc (+1k armor penetration for 15 seconds) is only lasting about 3 seconds.
**Current behaviour**:
Proc only lasts 3 seconds
Edit: Upon more testing, noticed the proc lasts until the next attack/special attack, not a set amount of time.
**Expected behaviour**: 
Should last 15 seconds.
**Server Revision**: 
3319 (auras_2020)

**Comment by Wolffenstein** [comment]
Will be fixed after PTR update.
