### ISSUE TITLE
[NPC]=3111 

### ISSUE THREAD

**Issue by duzyizly** [Atlantiss/NetherwingBugtracker#6849]
**Description**: 
Few of these mobs in current area are untouchable.
https://tbcdb.com/?npc=3111

**Current behaviour**:
yeah....

**Expected behaviour**: 
mhm...

**Server Revision**: 
3320

**Comment by duzyizly** [comment]
![WoWScrnShot_041020_235005](https://user-images.githubusercontent.com/43931626/79042404-f70a3000-7bf7-11ea-9eb1-b65e69b757c5.jpg)
![WoWScrnShot_041020_235141](https://user-images.githubusercontent.com/43931626/79042407-f7a2c680-7bf7-11ea-995d-7690f7dd0581.jpg)
![WoWScrnShot_041020_235144](https://user-images.githubusercontent.com/43931626/79042408-f83b5d00-7bf7-11ea-838d-044bbdad9934.jpg)

**Comment by The14me** [comment]
3111 ID 15
https://streamable.com/b4jabl

**Comment by Evolvee** [comment]
cant reproduce
