### ISSUE TITLE
[Quest][Redridge Mountains] Messenger to Stormwind || Messenger to Westfall || Messenger to Darkshire

### ISSUE THREAD

**Issue by Firroth** [Atlantiss/NetherwingBugtracker#685]
[Quest][Redridge Mountains] Messenger to Stormwind || Messenger to Westfall || Messenger to Darkshire

**Current behaviour**:
You can take all 3 quests:
https://www.wowhead.com/quest=121/messenger-to-stormwind
https://www.wowhead.com/quest=143/messenger-to-westfall
https://www.wowhead.com/quest=145/messenger-to-darkshire

**Expected behaviour**: 
You start by getting
https://www.wowhead.com/quest=121/messenger-to-stormwind
after completing it, you get next one in chain:
https://www.wowhead.com/quest=143/messenger-to-westfall
and like before, after this one is done you get last q in chain
https://www.wowhead.com/quest=145/messenger-to-darkshire

**Server Revision**: 
2060

**Comment by tcberk12** [comment]
There is at least a level requirement going on right now.

I was able to get Stormwind/Westfall at the same time and turn them in, but not Darkshire till a later level (I think 18)

I can do more research on this today.

**Comment by Firroth** [comment]
Well level requirement aside, you shouldn't be able to get those quests anyway, no matter what level you are, even if 70, till you won't complete Stormwind one, you won't get Westfall one, same for Darkshire one you won't get it till you won't finish Westfall one

It's even stated in comments on wowhead:

By adashiel (276,081 –  15·89·931)  on 2008/06/17 (Patch 2.4.2) |   |  
Once you've completed this quest Magistrate Solomon will ask you to seek aid from the People's Militia with Messenger to Westfall.

And for Darkshire one:

By adashiel (276,081 – 15·89·931) on 2008/06/17 (Patch 2.4.2)
After you complete your run to and from Sentinel Hill, you'll be sent to Duskwood with Messenger to Darkshire.

**Comment by tcberk12** [comment]
I wasn't trying to disprove you, just was trying to give more info on what is currently happening on the beta realm.

Your evidence looks solid, i think you are right!

**Comment by Shanghi** [comment]
This should be fixed in revision 2152.
