### ISSUE TITLE
[core] creature formations are not always behaving properly when leader dies/respawns

### ISSUE THREAD

**Issue by duzyizly** [Atlantiss/NetherwingBugtracker#6850]
[//]: # (Enclose links to things related to the bug using http://wowhead.com or any other TBC database.)
[//]: # (You can use screenshot ingame to visual the issue.)
[//]: # (Write your tickets according to the format:)
[//]: # ([Quest][Azuremyst Isle] Red Snapper - Very Tasty!)
[//]: # ([NPC] Magistrix Erona)
[//]: # ([Spell][Mage] Fireball)
[//]: # ([Npc][Drop] Ghostclaw Lynx)
[//]: # ([Web] Armory doesnt work)
[//]: # (To find server revision type `.server info` command in the game chat.)

**Description**: 
There is a NPC called Boss Tho'grun https://tbcdb.com/?npc=2944
And he has patrol with 4 mobs moving around him.

**Current behaviour**:
Once you kill Boss Tho'grun and save his patrol - these four mobs will **FLY** to his next spawn.
They are even flying through mountains/objects etc.

**Expected behaviour**: 
I 30% sure they should be running  (not flying).

**Server Revision**: 
3320

**How to reproduce**
kill the boss and wait 1 minute.

![WoWScrnShot_040620_220647](https://user-images.githubusercontent.com/43931626/79042570-24a3a900-7bf9-11ea-9e9e-3104bd098eb7.jpg)

**Comment by Evolvee** [comment]
just shait core issue

**Comment by Wolffenstein** [comment]
Fixed in rev 3344.
