### ISSUE TITLE
Consecration doesn't triggering guards to attack.

### ISSUE THREAD

**Issue by AWIDIUS** [Atlantiss/NetherwingBugtracker#6854]
![image](https://user-images.githubusercontent.com/45521546/79069890-1b3a3f80-7cd2-11ea-9259-024c43fdf426.png)

**Comment by Evolvee** [comment]
should it? need evidence

**Comment by AWIDIUS** [comment]
Its damage caused by a player, thus he should be considered as someone who hurts opposite faction. Guards should be about to attack this player. Doesn't happen. Good to know then I can go 5x pallys and abuse this all over Isle.

**Comment by AWIDIUS** [comment]
Its more than self explainatory and evident, what else you need lol ?

**Comment by Evolvee** [comment]
logic doesnt apply to wow

need evidence

**Comment by NatsumeLily** [comment]
https://www.tentonhammer.com/guides/staying-alive-on-the-isle-of-quel-danas.amp

> Paladins have consecrate which can make someone awfully mad if they step in it.

> Traps like Frost Trap, Explosive Trap, and Snake Trap will attack nearby players who enter their radius.

https://www.wowhead.com/forums&topic=32255.2

> The guards don't care if you're actually Exalted with them or not, or if someone else is picking the fight in the first place. The guards will indeed kill the one who did damage last time.and who's closest.

**Comment by Evolvee** [comment]
https://github.com/ccshiro/cc-buglist/issues/19

**Comment by NatsumeLily** [comment]
Difference being this is a pvp zone, no pvp flags on the isle (or anywhere you got neutral guards).

**Comment by Godmatik** [comment]
Rev 4018 - no longer an issue
Consecrate is properly triggering neutral guards to attack
