### ISSUE TITLE
[MGT][Npc][Drop] Heroic MGT Kael'thas loot table

### ISSUE THREAD

**Issue by gmforghieri** [Atlantiss/NetherwingBugtracker#6855]
[//]: # (Enclose links to things related to the bug using http://wowhead.com or any other TBC database.)
[//]: # (You can use screenshot ingame to visual the issue.)
[//]: # (Write your tickets according to the format:)
[//]: # ([Quest][Azuremyst Isle] Red Snapper - Very Tasty!)
[//]: # ([NPC] Magistrix Erona)
[//]: # ([Spell][Mage] Fireball)
[//]: # ([Npc][Drop] Ghostclaw Lynx)
[//]: # ([Web] Armory doesnt work)
[//]: # (To find server revision type `.server info` command in the game chat.)

**Description**: 
Heroic MGT last boss Kael'thas only drops 1 item instead of 2. 
Source: 
First comment on the following wowheadlink and numerous youtube videos.
https://www.wowhead.com/npc=24664/kaelthas-sunstrider#comments 
**Current behaviour**:
He only drops 1 epic.
**Expected behaviour**: 
He should drop 2 epics.
**Server Revision**:

**Comment by Wolffenstein** [comment]
Fixed in rev 3332.
