### ISSUE TITLE
[core] NPC Chasing mechanics are back to STOCK, nothing works anymore

### ISSUE THREAD

**Issue by Evolvee** [Atlantiss/NetherwingBugtracker#6858]
When you damage npcs to low % HP, NPC doesnt slow itself anymore.

When you walk (either walk or run with slow debuffs), the npc chases you in melee range with full speed... 

Prediction movement nonexistent

everything is fucking **stock shit** again!

just rewatch all NW videos and fix again pls 🤷‍♂️ 

--------------------------

idk what you did but I want to keep telling myself this is just a 1 time error and I dont have to re-research everything we ever fixed since 2016

**Comment by Wolffenstein** [comment]
im not fixing your imaginary bugs

**Comment by Evolvee** [comment]
??? you want me to record it?

**Comment by Evolvee** [comment]
nonexistent prediction movement: https://www.youtube.com/watch?v=OnV16eYvhZo

nonexistent slow movement at low hp: https://www.youtube.com/watch?v=cBz8Ml6_kY4

completely stock shait chasing movement when target is slowed: https://www.youtube.com/watch?v=l7_qI9O_F08 and https://www.youtube.com/watch?v=d9eXtsSRbXs


**how it should work:**

**Comment by Wolffenstein** [comment]
3348
