### ISSUE TITLE
Zeb'Tela Shadowpine Shadowcaster#16469 missing patrols

### ISSUE THREAD

**Issue by Tenoutoften** [Atlantiss/NetherwingBugtracker#686]
**Description**: 
Shadowpine Shadowcaster#16469(https://db.excalibur.ws/?npc=16469) should be patroling around the house. Doesn't patrol here. https://youtu.be/h9UMRo7P4dU?t=95 location: 81.0, 39.4 Ghostlands

There is another '"house" at 75.8, 43.4 on the second level two mobs are very awkwardly standing close to each other: https://i.gyazo.com/4ef8751d05899f14b47d8068ad155322.png most likely another missing patrol.

**Expected behaviour**: 
I expect the Shadowpine Shadowcaster to patrol around the house as seen in the video, instead he is awkwardly standing in the doorway I think(https://i.gyazo.com/c71cfed77819453a0f23a00f81bef99c.png).

Very likely missing a patrol in the 75.8, 43.4 house as well(second level).
**Server Revision**: 
2060

**Comment by aresbrutus** [comment]
Fixed in rev `Ilus`
