### ISSUE TITLE
[PTR] [Buff] Kreeg's Stout Beatdown

### ISSUE THREAD

**Issue by lyubomeer** [Atlantiss/NetherwingBugtracker#6860]
[//]: # (Enclose links to things related to the bug using http://wowhead.com or any other TBC database.)
[//]: # (You can use screenshot ingame to visual the issue.)
[//]: # (Write your tickets according to the format:)
[//]: # ([Quest][Azuremyst Isle] Red Snapper - Very Tasty!)
[//]: # ([NPC] Magistrix Erona)
[//]: # ([Spell][Mage] Fireball)
[//]: # ([Npc][Drop] Ghostclaw Lynx)
[//]: # ([Web] Armory doesnt work)
[//]: # (To find server revision type `.server info` command in the game chat.)

**Description**: 

**Current behaviour**: https://tbcdb.com/?item=18284 currently replaces well fed buff. 

**Expected behaviour**: should stack 
![image](https://user-images.githubusercontent.com/11522170/79097666-f5ac4500-7d68-11ea-8811-de8df73dd414.png)

**Server Revision**: 3323

**Comment by Hazel-Code** [comment]
based on my research it was ingame until wotlk 3.3.0

https://wowwiki.fandom.com/wiki/Kreeg%27s_Stout_Beatdown

and also it was NOT named in the list for changes in 2.1 patch

"Rumsey Rum, Rumsey Rum Light, Rumsey Rum Dark, Rumsey Rum Black Label, Halaani Whiskey, Gordok Green Grog, Raptor Punch, Stormstout, Trogg Ale, and Thunderbrew Lager: The stat bonuses from these drinks no longer stacks with stamina bonuses from other foods."

**Comment by Easyfraggy** [comment]
It is pretty clear from what blizzard did in patch 2.1 that they only wanted

1 food buff
1 flask / 2 elixirs

This item is merely an oversight as noone used it, and was nerfed in 3.2 when it was discovered.

It's up to admins wether this should be a thing or not.

**Comment by Wolffenstein** [comment]
Will be fixed after PTR update.
