### ISSUE TITLE
[Talent][Warrior] Deep Wounds

### ISSUE THREAD

**Issue by Alar1s** [Atlantiss/NetherwingBugtracker#6862]
**Description**: 
The talent deep Wounds is no longer applied on crit. Last time I am sure it worked was yesterday.
As you can see in this screenshot of the combatlog, it is not applied to enemies und deals no damage.
Deep Wounds https://tbc-twinhead.twinstar.cz/?spell=12867

![Deepwounds_notapplied](https://user-images.githubusercontent.com/63605530/79141816-ccb4a000-7dba-11ea-9fa1-6f3ea09717f0.jpg)

**Server Revision**: 
3323
Branch: master

**Comment by Wolffenstein** [comment]
Will be fixed after restart.
