### ISSUE TITLE
[Spell][Paladin] Eye for an Eye PvP-flags the Paladin for Guards

### ISSUE THREAD

**Issue by Tankdiehutte** [Atlantiss/NetherwingBugtracker#6863]
**Description**: When a caster critically hits a Ret Paladin (Friendly to the guards)  with that Talent the guards attack the Paladin.
https://classic.wowhead.com/spell=25988/eye-for-an-eye

**Current behaviour**: The Reflected passive damage make the guards attack the paladin, if he is in range. Instead of going fo the attacker ( who stands further away from the guard)

![Eye for an Eye](https://user-images.githubusercontent.com/56139988/79146922-6d0ec280-7dc3-11ea-9be1-b7ff3d26ae62.png)

**Expected behaviour**: The Guards shouldnt attack the Paladin. Should be the same behavior like if sb runs into a Paladins Consecration or if sb hits a Druid with Thorns.

**Server Revision**: 
3323

**Comment by NatsumeLily** [comment]
https://www.tentonhammer.com/guides/staying-alive-on-the-isle-of-quel-danas.amp

> Paladins have consecrate which can make someone awfully mad if they step in it.


**https://www.wowhead.com/forums&topic=32255.2**

> The stupidiest thing is when you have Thorns on you, and a hordy attacks you and taking damage from ur Thorns, he can run to a guard, and it will actually Help him killing you.
> The World PvP system is flawed in many ways. This doesn't only happen on that bloody island. But also in any other town with shared horde and alliance quests. Like Booty Bay, Gadgetzan, Argent Dawn. etc.
> 
> The guards don't care if you're actually Exalted with them or not, or if someone else is picking the fight in the first place. The guards will indeed kill the one who did damage last time.and who's closest.
