### ISSUE TITLE
[SWP] [NPC] Vindicator Moorba: Teleport to Eredar Twins Room

### ISSUE THREAD

**Issue by Sagoona** [Atlantiss/NetherwingBugtracker#6864]
[//]: # (Enclose links to things related to the bug using http://wowhead.com or any other TBC database.)
[//]: # (You can use screenshot ingame to visual the issue.)
[//]: # (Write your tickets according to the format:)
[//]: # ([Quest][Azuremyst Isle] Red Snapper - Very Tasty!)
[//]: # ([NPC] Magistrix Erona)
[//]: # ([Spell][Mage] Fireball)
[//]: # ([Npc][Drop] Ghostclaw Lynx)
[//]: # ([Web] Armory doesnt work)
[//]: # (To find server revision type `.server info` command in the game chat.)

**Description**: 
[Vindicator Moorba](https://www.wowhead.com/npc=25632/vindicator-moorba) Offers the dialog to get teleported to the Twins Room after they were killed but nothing happens.
Related to https://github.com/Atlantiss/NetherwingBugtracker/issues/6670
**Current behaviour**:
Teleport to Twins Room doesn't work. (our Raid-ID: 6925)
**Expected behaviour**: 
Teleport should work.
**Server Revision**: 
3323

**Comment by Wolffenstein** [comment]
Will be fixed once muru goes live.
