### ISSUE TITLE
[Pet] [Hunter] Pet base damage is too high.

### ISSUE THREAD

**Issue by Easyfraggy** [Atlantiss/NetherwingBugtracker#6865]
Atm, pet base damage appears to be around 53-88

(118-157 in pet sheet) with 365 AP as orc on wind serpent at yellow happiness (100%):

(53+365/14*2) * 1,05 (orc)* 1,07 (serpent fam) = 118
(88+365/14*2) * 1,05 (orc)* 1,07 (serpent fam) = 157

With 695 AP I get 171 - 210 which also suggest 53-88 base dmg with same calculation done.

Sources:
Would love some better sources on pet base damage! But this is what I was able to find so far.

Hunter Spreadsheet:
![image](https://user-images.githubusercontent.com/36134067/79166003-968c1600-7de4-11ea-962f-1a3e3dd253b3.png)

Videos supporting evidence (looking for damage variance)

20 variance base = 20*(fam bonus)*(if orc)*1,25(happi)*(1,2talent)
Expected for WS that would be 33 dmg if orc - 32 if not orc.
With 35 variance (current NW) you would see: 59 if orc 56 if not orc.

Observed: https://www.youtube.com/watch?v=LStllWoXKCM&feature=youtu.be&t=215 till 4:21 he doesn't gain/lose any ap/dmg mod other than having 2 FI at one point and only 1 rest of the time, but thats a very small multiplier and would only increase the variance. Variance observed 32 dmg (max 244 min 212). 4:33-5:16 also max variance 29 (doesnt gain/lose ap/mod other than FI).

I'll add more video evidence when I have more time.

**Server Revision**:

**Comment by Tereneckla** [comment]
The base damage listed here is from some elitist jerks spreadsheet, so there should be some truth to it.

**Comment by Wolffenstein** [comment]
Fixed in rev 3555.
