### ISSUE TITLE
[Quest] Stranglethorn Fever

### ISSUE THREAD

**Issue by drewk8** [Atlantiss/NetherwingBugtracker#6866]
**Description**: 
Quest is bugged in a party of three, the apes would continuously spawn, even when not triggered. Also, quest entry is bugged in the questlog.

**Current behavior**:
Above 
![bugged_quest_log](https://user-images.githubusercontent.com/46622080/79230268-fcbc7b80-7e6c-11ea-870b-1ed66c7ae347.JPG)

**Expected behavior**: 
At least it should not continuously spawn the apes if not triggered by players. Questlog entry not bugged.

**Server Revision**: 
3323

**Comment by drewk8** [comment]
Just to add, i can't confirm 100% that neither party member triggered the quest, but it seemed so. The quest log entry still remains.

**Comment by Evolvee** [comment]
https://classic.wowhead.com/quest=349/stranglethorn-fever#comments

![image](https://user-images.githubusercontent.com/1942409/81197392-7c4aef80-8fc0-11ea-951e-bba186c09dd3.png)
![image](https://user-images.githubusercontent.com/1942409/81197409-8371fd80-8fc0-11ea-9b3b-38c8821bad0f.png)

**Comment by Evolvee** [comment]
questlog is your addon problem most likely as the quest can not be even accepted
