### ISSUE TITLE
[Hunter] Concussive Shot stun share DR with Intimidation

### ISSUE THREAD

**Issue by 4egito** [Atlantiss/NetherwingBugtracker#6867]
[//]: # (Enclose links to things related to the bug using http://wowhead.com or any other TBC database.)
[//]: # (You can use screenshot ingame to visual the issue.)
[//]: # (Write your tickets according to the format:)
[//]: # ([Quest][Azuremyst Isle] Red Snapper - Very Tasty!)
[//]: # ([NPC] Magistrix Erona)
[//]: # ([Spell][Mage] Fireball)
[//]: # ([Npc][Drop] Ghostclaw Lynx)
[//]: # ([Web] Armory doesnt work)
[//]: # (To find server revision type `.server info` command in the game chat.)

**Description**: 
I don't know which is the correct: "Concussive Shot stun share DR with player controlled stuns like Intimidation" or "Intimidation share DR with random stuns" but there is a video...
**Current behaviour**:
https://drive.google.com/open?id=1rrqGznEYSNa1NA-bUBMu4FYNG3IJEzEe
**Expected behaviour**: 
#6778
**Server Revision**: 
3323

**Comment by Wolffenstein** [comment]
Fixed in rev 3345.
