### ISSUE TITLE
[Item] Gavel of Naaru Blessings no glow

### ISSUE THREAD

**Issue by hederob** [Atlantiss/NetherwingBugtracker#6868]
**Description**: Enchant glows don't appear on Gavel of Naaru Blessings

**Current behavior**:
No enchant glows appear on Gavel of Naaru Blessings and it has no glow on its own.
**Expected behavior**: 
Glows should appear on Gavel of Naaru Blessings.
**Server Revision**: 
3323

according to the comments:
178029 on 2008/07/24 (Patch 2.4.3)
Spellsurge shows.

symet on 2008/10/18 (Patch 3.0.2)
After patch 3.0.2 this weapon now glows with enchants.

It appears that only certain enchants glow (spellsurge) but some months later it was fixed to where all enchant glows appear since the weapon has no glow of its own. However, this was a few weeks before WOTLK was released.
https://www.wowhead.com/item=34896/gavel-of-naaru-blessings

**Comment by Wolffenstein** [comment]
I'm pretty sure it's a client bug and I have no means to fix it.

**Comment by Evolvee** [comment]
find a retail video/picture of it pre-wotlk -.-

**Comment by PrincessBLARITY** [comment]
Hey Sweet thang I missed you.
