### ISSUE TITLE
[PTR] Instant 58 Boost - Warrior

### ISSUE THREAD

**Issue by Erodraeda** [Atlantiss/NetherwingBugtracker#6869]
[//]: # (Enclose links to things related to the bug using http://wowhead.com or any other TBC database.)
[//]: # (You can use screenshot ingame to visual the issue.)
[//]: # (Write your tickets according to the format:)
[//]: # ([Quest][Azuremyst Isle] Red Snapper - Very Tasty!)
[//]: # ([NPC] Magistrix Erona)
[//]: # ([Spell][Mage] Fireball)
[//]: # ([Npc][Drop] Ghostclaw Lynx)
[//]: # ([Web] Armory doesnt work)
[//]: # (To find server revision type `.server info` command in the game chat.)

**Description**: 
Missing one ring, both trinkets; no weapon skills other than the racial ones (as an orc, missing maces, throws, bows, two-handed swords, crossbows, guns, two-handed maces); no second onehanded weapon for dual wielding; intellect shield(?).

**Server Revision**: 
3323

**Comment by Tereneckla** [comment]
Warrior weapon skills are everything but daggers, swords, axes, maces, fist weapons, 2H swords, 2H maces, 2H axes, polearms, guns, bows, crossbows, thrown.
