### ISSUE TITLE
[Quest] Mission: Possible but not probable

### ISSUE THREAD

**Issue by padomu** [Atlantiss/NetherwingBugtracker#687]
[//]: # (Enclose links to things related to the bug using http://wowhead.com or any other TBC database.)
[//]: # (You can use screenshot ingame to visual the issue.)
[//]: # (Write your tickets according to the format:)
[//]: # ([Quest][Azuremyst Isle] Red Snapper - Very Tasty!)
[//]: # ([NPC] Magistrix Erona)
[//]: # ([Spell][Mage] Fireball)
[//]: # ([Npc][Drop] Ghostclaw Lynx)
[//]: # ([Web] Armory doesnt work)

**Description**: 
https://www.wowhead.com/quest=2478/mission-possible-but-not-probable

**Current behaviour**:
Problem 1: We were two in a group and killed Grand Foreman Gallywix. Only my friend could loot the head. We both picklocked the chest and got the Cache of Zanzil's Altered Mixture. But by opening the cehst you get the 7 day debuff s.t. you cant stealth anymore. Stealth is crucial to be able to kill Grand Foremane Gallywix since you have to ambush him (about 40% HP). So I couldn't really get the head anymore. 

Problem 2: When you accept the quest, you also get https://www.wowhead.com/item=8066/fizzules-whistle, it basically does nothing. ALso: Not sure if thats a problem: Usually you have to use the Flare Item 2 times and /salute him so he gets friendly. If you are several people, one could make each a flare and a 3th could /salute and he would be friendly. Not sure if that's expected.

**Expected behaviour**: 

Problem 1: Everyone who helped kill Foreman should get the head
Problem 2: The whistle should make Fizzule friendly. Al

**Server Revision**: 
2060

**Comment by dupedful** [comment]
I confirm. Tried to finish the quest this morning. The whistle didn't work. The faction is still hostile. Since this is an important quest for rogues, I ask the developers to take care of it quickly.

**Comment by Manaci** [comment]
Fixed in rev 2793
