### ISSUE TITLE
[PTR] Instant 58 Boost - Paladin

### ISSUE THREAD

**Issue by Erodraeda** [Atlantiss/NetherwingBugtracker#6870]
[//]: # (Enclose links to things related to the bug using http://wowhead.com or any other TBC database.)
[//]: # (You can use screenshot ingame to visual the issue.)
[//]: # (Write your tickets according to the format:)
[//]: # ([Quest][Azuremyst Isle] Red Snapper - Very Tasty!)
[//]: # ([NPC] Magistrix Erona)
[//]: # ([Spell][Mage] Fireball)
[//]: # ([Npc][Drop] Ghostclaw Lynx)
[//]: # ([Web] Armory doesnt work)
[//]: # (To find server revision type `.server info` command in the game chat.)

**Description**: 
Missing weapon skills (as a blood elf, only have swords and two-handed swords) being both weapon options maces; missing both trinkets; 

**Server Revision**: 
3323

**Comment by Tereneckla** [comment]
Paladin weapon skills are swords, maces, axes, 2H swords, 2H maces, 2H axes, polearms
