### ISSUE TITLE
[PTR] Instant 58 Boost - Hunter

### ISSUE THREAD

**Issue by Erodraeda** [Atlantiss/NetherwingBugtracker#6871]
[//]: # (Enclose links to things related to the bug using http://wowhead.com or any other TBC database.)
[//]: # (You can use screenshot ingame to visual the issue.)
[//]: # (Write your tickets according to the format:)
[//]: # ([Quest][Azuremyst Isle] Red Snapper - Very Tasty!)
[//]: # ([NPC] Magistrix Erona)
[//]: # ([Spell][Mage] Fireball)
[//]: # ([Npc][Drop] Ghostclaw Lynx)
[//]: # ([Web] Armory doesnt work)
[//]: # (To find server revision type `.server info` command in the game chat.)

**Description**: 
Missing one ring, both trinkets, melee weapons, maybe a better quiver/ammo pouch; only 200 ammo(?); missing weapon skills.

**Server Revision**: 
3323

**Comment by Tereneckla** [comment]
Hunter weapon skills daggers, axes, swords, polearm, fist weapons, guns, bows, crossbows, thrown
