### ISSUE TITLE
[PTR] Instant 58 Boost - Druid

### ISSUE THREAD

**Issue by Erodraeda** [Atlantiss/NetherwingBugtracker#6872]
[//]: # (Enclose links to things related to the bug using http://wowhead.com or any other TBC database.)
[//]: # (You can use screenshot ingame to visual the issue.)
[//]: # (Write your tickets according to the format:)
[//]: # ([Quest][Azuremyst Isle] Red Snapper - Very Tasty!)
[//]: # ([NPC] Magistrix Erona)
[//]: # ([Spell][Mage] Fireball)
[//]: # ([Npc][Drop] Ghostclaw Lynx)
[//]: # ([Web] Armory doesnt work)
[//]: # (To find server revision type `.server info` command in the game chat.)

**Description**: 
Spawned below Silithus?? https://imgur.com/a/Rj850YW
Missing both trinkets; missing skill with weapons (as tauren only have maces and staves).

**Server Revision**: 
3323

**Comment by Tereneckla** [comment]
Druid weapon skills are daggers, maces, staves, 2H maces.
