### ISSUE TITLE
[PTR] Instant 58 Boost - Shaman

### ISSUE THREAD

**Issue by Erodraeda** [Atlantiss/NetherwingBugtracker#6873]
[//]: # (Enclose links to things related to the bug using http://wowhead.com or any other TBC database.)
[//]: # (You can use screenshot ingame to visual the issue.)
[//]: # (Write your tickets according to the format:)
[//]: # ([Quest][Azuremyst Isle] Red Snapper - Very Tasty!)
[//]: # ([NPC] Magistrix Erona)
[//]: # ([Spell][Mage] Fireball)
[//]: # ([Npc][Drop] Ghostclaw Lynx)
[//]: # ([Web] Armory doesnt work)
[//]: # (To find server revision type `.server info` command in the game chat.)

**Description**: 
Missing both trinkets and dualwielding weapon, also twohander; missing weapon skills (as tauren, only maces and staves).

**Server Revision**: 
3323

**Comment by Tereneckla** [comment]
Shaman weapon skills are daggers, maces, axes, 2H maces, 2H axes, staves, fist weapons.

**Comment by Zaorr** [comment]
Missing Totem quest completion & totems in inventory.
