### ISSUE TITLE
[PTR] Instant 58 Boost - Priest

### ISSUE THREAD

**Issue by Erodraeda** [Atlantiss/NetherwingBugtracker#6877]
[//]: # (Enclose links to things related to the bug using http://wowhead.com or any other TBC database.)
[//]: # (You can use screenshot ingame to visual the issue.)
[//]: # (Write your tickets according to the format:)
[//]: # ([Quest][Azuremyst Isle] Red Snapper - Very Tasty!)
[//]: # ([NPC] Magistrix Erona)
[//]: # ([Spell][Mage] Fireball)
[//]: # ([Npc][Drop] Ghostclaw Lynx)
[//]: # ([Web] Armory doesnt work)
[//]: # (To find server revision type `.server info` command in the game chat.)

**Description**: 
Missing one ring, both trinkets; missing weapon skills (as blood elf, only maces and wands), therefore can't equip given staff.

**Server Revision**: 
3323

**Comment by Tereneckla** [comment]
Priest weapon skills are maces, daggers, staffs, wands.
