### ISSUE TITLE
[Class][Warlock] Inferno dismiss instantly on some bosses

### ISSUE THREAD

**Issue by veekk** [Atlantiss/NetherwingBugtracker#6878]
**Description**: On some bosses, e.g. Archimonde or Brutallus warlock Inferno (Summon Infernal) not working at all, right after summon he became hostile and killing wlock, but those bosses can deal only fire aoe, and infernal must be immune to it and can't break enslave at all with only exceptions warlock death, 5m timer and manual dismiss

**Current behaviour**: no big dick infernal dps

**Expected behaviour**: big dick infernal dps

**Server Revision**: latest

**Comment by Easyfraggy** [comment]
There was a fix recently on PTR that Tremor totem would remove enslave. Not sure if its live or not yet.
