### ISSUE TITLE
[Raid] Hyjal Summit - Waves to Azgalor (infernals)

### ISSUE THREAD

**Issue by Firroth** [Atlantiss/NetherwingBugtracker#6879]
**Current behaviour**:
3rd, 4th, 7th waves where infernals should spawn, are bugging a lot of times and don't spawn all of the infernals, or in rare cases don't spawn any of them, making the said wave only have couple of trash to kill.

**Expected behaviour**: 
3rd wave should always spawn 4 ghouls, 8 infernals.
4th wave should always spawn 8 stalkers, 6 infernals
7th wave should always spawn 2 ghouls, 2 crypts, 2 stalkers, 8 infernals.

**Server Revision**: 
3323

**Comment by Easyfraggy** [comment]
They don't spawn if all the npcs are dead. It's blizzlike.

**Comment by Firroth** [comment]
Source? I've never heard of such stuff before. It would simply be a joke when waves to 4rth boss were the easiest of all. Only 4 ghouls in a wave ? omg it would wipe entire raid!

**Comment by Healweed** [comment]
> They don't spawn if all the npcs are dead. It's blizzlike.

Shouldnt be. Regardless if the NPCs are dead (not counting thrall ofc) it should  spawn the waves correctly by their own wave number

**Comment by Firroth** [comment]
Not to mention, if it was "blizzlike" this way, then people would simply let those npc's die during waves to kaz'rogal, or on first infernal wave, so they could speed up clearing the wave (4,7) and not risk wiping by getting outnumbered. Yet people never did it on retail? why?

**Comment by Easyfraggy** [comment]
Most people were simply unaware that this was possible for the most part on retail, as with many things in TBC. It is not really a question if it's blizzlike or not, because it definitely is (its in the spell db). 

The question is if admins want to prevent it and change it to spawn anyway. Which would not be blizzlike, but a perfectly reasonable change to make in my opinion.

**Comment by Wolffenstein** [comment]
It's a bug.

**Comment by Wolffenstein** [comment]
Should be fixed in rev 3348.
