### ISSUE TITLE
[Quest] Arikara sometimes evades after spawn if you stand too close to fire.

### ISSUE THREAD

**Issue by Jezofine** [Atlantiss/NetherwingBugtracker#688]
**Current behaviour**:
Arikara (npc id = 10882) for quest Arikara (5088),. Got this evade on the 1st try, so someone else can easily encounter that too. Need to stand close to fire to make it evade.
[Video](https://youtu.be/uVvV4jit0dE)
It doesn't break the quest tho, you can still resummon it and aggro safely from slightly different spot.

**Expected behaviour**:
Not evading.

**Server Revision**: 2060

**Comment by Easyfraggy** [comment]
I think in general evade behavior is broken, they evade instantly and reset, while they should evade for 3-5 seconds before resetting when they cant find a path. This allows player to "unevade" them by moving or shifting position.

**Comment by Evolvee** [comment]
@Wolffenstein 
confirmed this issue

the issue is that u need to aggro the arikara and then move with her from the fire gameobject, otherwise she cant reach you and evades... its caused by the gameobject

the arikara is spawned on top of it ^^ so thats causing the issue most likely

**Comment by Tereneckla** [comment]
Fixed
