### ISSUE TITLE
Khorium Boar summoned from [Figurine - Khorium Boar] trinket has wrong (12) hp

### ISSUE THREAD

**Issue by RealFundin** [Atlantiss/NetherwingBugtracker#6880]
[//]: # (Enclose links to things related to the bug using http://wowhead.com or any other TBC database.)
[//]: # (You can use screenshot ingame to visual the issue.)
[//]: # (Write your tickets according to the format:)
[//]: # ([Quest][Azuremyst Isle] Red Snapper - Very Tasty!)
[//]: # ([NPC] Magistrix Erona)
[//]: # ([Spell][Mage] Fireball)
[//]: # ([Npc][Drop] Ghostclaw Lynx)
[//]: # ([Web] Armory doesnt work)
[//]: # (To find server revision type `.server info` command in the game chat.)

**Description**: 
When using the epic BOP Jewelcrafting trinket [Figurine - Khorium Boar], the summoned boar has wrong hp (incredibly low). The others stats might have to be checked too but pet died instantly to a mob from Terrokar.

**Current behaviour**:
The current hp are 12/12.

**Expected behaviour**: 
It should have 990/990 hp as suggest the third comment of this link : https://www.wowhead.com/item=35694/figurine-khorium-boar#comments

<img width="960" alt="khorium" src="https://user-images.githubusercontent.com/58194627/79376433-75e5cc80-7f5a-11ea-9f3b-c6f3942d156e.png">

**Server Revision**: 
3323

**Comment by Evolvee** [comment]
https://github.com/Atlantiss/AtlantissTBCBT/issues/3593
