### ISSUE TITLE
[PTR] Character Boost Inventory - Shaman

### ISSUE THREAD

**Issue by tkirche** [Atlantiss/NetherwingBugtracker#6881]
[//]: # (Enclose links to things related to the bug using http://wowhead.com or any other TBC database.)
[//]: # (You can use screenshot ingame to visual the issue.)
[//]: # (Write your tickets according to the format:)
[//]: # ([Quest][Azuremyst Isle] Red Snapper - Very Tasty!)
[//]: # ([NPC] Magistrix Erona)
[//]: # ([Spell][Mage] Fireball)
[//]: # ([Npc][Drop] Ghostclaw Lynx)
[//]: # ([Web] Armory doesnt work)
[//]: # (To find server revision type `.server info` command in the game chat.)

**Description**: 
Totems mailed to character that already has totems due to character not being fresh lvl 1 when boosted cannot be retrieved and therefore will always have an unopened mail from 'Customer Support'.
**Current behaviour**:
Totems cannot be retrieved from mail. Totems are indestructible.
**Expected behaviour**: 
Deleting out class items (such as totems) during boost in programming so can be retrieved as if a level 1 fresh character.
![WoWScrnShot_041520_163152](https://user-images.githubusercontent.com/63750496/79385952-67d28480-7f37-11ea-99bf-82b544f6a9d5.jpg)

**Server Revision**:

**Comment by Evolvee** [comment]
should be fixed
