### ISSUE TITLE
[PTR] 58 boost - missing flight paths

### ISSUE THREAD

**Issue by duzyizly** [Atlantiss/NetherwingBugtracker#6882]
You don't get any flight paths after boost, running to blasted lands/CoT etc. gonna be painful.
Not sure if intended.

Also it will be not possible to use 'em cause of 0 gold.

**Comment by duzyizly** [comment]
rev 3323

**Comment by Evolvee** [comment]
thats intended unfortunately.. technical difficulties, with the way how flights are learned, you could transfer to horde as alliance and get the alliance flypaths and then transfer back to alliance and get all the horde flypaths...

you can use hearthstone to get to dark portal
