### ISSUE TITLE
[PTR] Troll priest boost suggestion

### ISSUE THREAD

**Issue by duzyizly** [Atlantiss/NetherwingBugtracker#6883]
Not a big deal but once you are boosted, You teleport next to Portal trainer instead of class trainer (Troll priest).

https://tbcdb.com/?npc=5958 - Portal trainer [Orgrimmar]
https://tbcdb.com/?npc=6018 - Class trainer [Orgrimmar]

rev 3323

**Comment by Evolvee** [comment]
it teleports me just fine
