### ISSUE TITLE
[PTR} 57 boost - Warlock - summoned demons spells / soul shards

### ISSUE THREAD

**Issue by duzyizly** [Atlantiss/NetherwingBugtracker#6884]
**Description**: 
Once boosted - summoned demons have no skills (other than basic)

Would be great to send demon books via email - also for Felguard.
Would be also nice to give warlocks at least Two/three soul shards via email.

**Server Revision**: 
3323

![WoWScrnShot_041620_134529](https://user-images.githubusercontent.com/43931626/79452625-b68c2700-7fe8-11ea-9d9b-129c8f9336d8.jpg)

**Comment by duzyizly** [comment]
It's not possible to just buy those books coz you know... MONEY.

**Comment by Evolvee** [comment]
fixed
