### ISSUE TITLE
Dragonmaw Race: Wing Commander Mulverick

### ISSUE THREAD

**Issue by Lexon-Netherwing** [Atlantiss/NetherwingBugtracker#6886]
[//]: # (Enclose links to things related to the bug using http://wowhead.com or any other TBC database.)
[//]: # (You can use screenshot ingame to visual the issue.)
[//]: # (Write your tickets according to the format:)
[//]: # ([Quest][Azuremyst Isle] Red Snapper - Very Tasty!)
[//]: # ([NPC] Magistrix Erona)
[//]: # ([Spell][Mage] Fireball)
[//]: # ([Npc][Drop] Ghostclaw Lynx)
[//]: # ([Web] Armory doesnt work)
[//]: # (To find server revision type `.server info` command in the game chat.)

**Description**: Hi, folks! Have an issue with quest https://www.wowhead.com/quest=11070/dragonmaw-race-wing-commander-mulverick . Shadowmoon Valley.This guy is "smashing" into crystal and mission is failing. I've tried more than 20 times to complete this quest but without success (hes fast like a bullet and throwing lightbolts like punisher.. is that normal?), it means that sometimes he can cross this smashing checkpoint, but now, last 5 times of trying hes failing my quest in the same position near crystal. Here the screen of "problem" point. 
![WoWScrnShot_041620_190233](https://user-images.githubusercontent.com/63805147/79480762-35985400-8017-11ea-9dac-db590ed56ebe.jpg). You can find me in game or discord to verify more points. Nick: Lexon. PS: sorry, if something wrong - my first experience at bug tracker. Thank you.

**Current behaviour**: Quest is failing each time for now at one point. Fly speed and amount of attacks is very high.

**Expected behaviour**: Quest cannot be failed if player is in zone and wasnt dropped from mount.

**Server Revision**: 3323

**Comment by Wolffenstein** [comment]
It's just how the quest works, it's hard but certainly doable.
