### ISSUE TITLE
Lady Vashj - Persuasion Spell

### ISSUE THREAD

**Issue by Dirtysprite420** [Atlantiss/NetherwingBugtracker#6887]
Due to our latest try at SSC / Lady Vashj, we approved the fact, that the boss mechanics might be a bit wrong for this patch. Somehow Lady Vashj should not (after Nerf) use the ability Persuasion. Here are the links for the videos and an other forum post.

Pre-nerf kill video: https://www.youtube.com/watch?v=SYypbzs9d44
Post-nerf kill video: https://www.youtube.com/watch?v=OFzbd7udjEU (forum post for it: http://www.lrguild.org/viewtopic.php?f=48&t=3574)

Patch 2.1 notes
https://wowwiki.fandom.com/wiki/Patch_2.1.0
.... -Lady Vashj can no longer use the ability Persuasion.

**Comment by Wolffenstein** [comment]
I left the ability there on purpose due to guilds asking for it, although it's been nerfed a bit.

**Comment by Dirtysprite420** [comment]
Okay , but shouldnt it be better for T5 progressing guilds to atleast be able to CC MC Targets? Because then u probably cant kill Vashj with meeles in the raid setup. And for fresh guilds who want to finish T5 to start with T6 it will be pretty hard to get a setup like this. Also u can not equip meeles then with the MH pre quest ring and Vashj loot.

**Comment by raethkcj** [comment]
You can have melee unequip their weapons between Persuasion casts, then reequip them when someone else gets MCd.

**Comment by Easyfraggy** [comment]
The MC'd players are also tauntable and have regular threat table.

**Comment by bisquiit** [comment]
polak scripts
