### ISSUE TITLE
Epic gems in heroic dungeons "Unique-Equipped"

### ISSUE THREAD

**Issue by Dirtysprite420** [Atlantiss/NetherwingBugtracker#6888]
Epic gems dropping in heroic dungeons should not be "unique" after Patch 2.4 like they are on NW

Patchnotes : https://wowwiki.fandom.com/wiki/Patch_2.4.0
... Gems obtained through Heroic difficulty instances are no longer Unique-Equipped.

**Comment by raethkcj** [comment]
Delete your cache folder, they are correctly non-unique
