### ISSUE TITLE
[Hunter] [Item] Ammo pouch/quiver bonus attack speed lost on dc if dead/while dead

### ISSUE THREAD

**Issue by eri1997** [Atlantiss/NetherwingBugtracker#6889]
[//]: # (Enclose links to things related to the bug using http://wowhead.com or any other TBC database.)
[//]: # (You can use screenshot ingame to visual the issue.)
[//]: # (Write your tickets according to the format:)
[//]: # ([Quest][Azuremyst Isle] Red Snapper - Very Tasty!)
[//]: # ([NPC] Magistrix Erona)
[//]: # ([Spell][Mage] Fireball)
[//]: # ([Npc][Drop] Ghostclaw Lynx)
[//]: # ([Web] Armory doesnt work)
[//]: # (To find server revision type `.server info` command in the game chat.)

**Description**: If you die -> release spirit and logout in spirit form  you'll lose quiver bonus when you ress/enter raid. 

**Current behaviour**: No quiver bonus

**Expected behaviour**:  Quiver bonus 

**Server Revision**: latest

**Comment by veekk** [comment]
can approve this [video](https://www.twitch.tv/skazzzzus/clip/FineGrotesqueMageOSfrog?filter=clips&range=7d&sort=time)

**Comment by Godmatik** [comment]
Was fixed at some point, tested on PTR and retained my quiver bonus even after releasing spirit and relog.

Issue can be closed
