### ISSUE TITLE
Pathing, mobs resetting, perhaps due to angle?

### ISSUE THREAD

**Issue by Tenoutoften** [Atlantiss/NetherwingBugtracker#689]
**Description**: 
This video is unlisted: https://www.youtube.com/watch?v=DBsQQCW_lGA&feature=youtu.be
I am agroing the mob over and over, not sure what exactly causes it to reset. I once fought it roughly this position and once it was fleeing it reset itself.

**Expected behaviour**: 
Preferably to not reset I suppose:)

**Server Revision**: 
2060

**Comment by Dpthx** [comment]
next time when you encounter this do a .gsp and an .npc info

**Comment by Tenoutoften** [comment]
Reproduced and uploading with .gsp & .npc: video can be found at https://www.youtube.com/watch?v=QHs7YrOiVc4&feature=youtu.be once it is done processing

**Comment by Easyfraggy** [comment]
I believe this may have been fixed, please retest!

**Comment by Tenoutoften** [comment]
I still managed to get this NPC evaded here

@ server rev 2186

**Comment by Tereneckla** [comment]
Videos are gone, no information on this left.
