### ISSUE TITLE
Suggestion:  Revoke instant-58 and Rollback those who did it

### ISSUE THREAD

**Issue by DaedalusMachina007** [Atlantiss/NetherwingBugtracker#6891]
Instant 58 is a terrible thing and has resulted in a peak player drop of over 700+ players!

![2020-04-17 11_39_36-Greenshot](https://user-images.githubusercontent.com/54285152/79587943-442b4d80-80a1-11ea-99b4-571e9e5ffcd9.png)

Imgur Archive: https://i.imgur.com/k7QzxjL.png

That's peak EU player time with far less than the 2k+ peaks we've enjoyed over the past few weeks.  COVID-19 isn't going to poof anytime soon (for several months) and doing instant-58 was way overkill.

Alternatives to instant-58:
-bring back the expanded Rested XP (up to 180 bars if I recall)
-do 'leveling xp events' on weekends with default xp increased to 5x or something (with a toggle back to 1x or 2x if people want to take their time)
-ASK THE PLAYERS WHAT THEY WANT BEFORE JUST DOING WHATEVER YOU FEEL LIKE because a server without players is a dead server.

I hope the Reddit 'freshtards' who dogpiled into the Discord server and spammed the devs to get what they want are happy for ruining the only decent TBC server that was around.

It still isn't too late to reverse course on this and revoke/revert the instant-58 by doing a server rollback as soon as possible to before it was implemented.  Apologize and do an actual community poll (in-game poll counting once per IP) and post the results publicly before doing these kinds of sweeping changes.

Devs wanted to do a major rewrite of procs/auras and live-test them during NA raiding times because nobody wanted to do free testing on the PTR from a dev who told people to 'shut up and stop whining' when they expressed concerns over it.

Reminds me of another server that went down the drain just as fast: ScapeGaming.  Feel free to look up the history of it if you like.

The upside is that this can still be salvaged/reverted if the devs own up to their mistakes and do what they should do (vote on major changes and offer incentives for testing on PTR) instead of whatever they want to do.

**Comment by Kruszek** [comment]
xD
