### ISSUE TITLE
i58 rogues should get poison mats

### ISSUE THREAD

**Issue by EtheriousNW** [Atlantiss/NetherwingBugtracker#6892]
**Description**: Rogues don't have any money to buy the mats they need to create poisons.

**Current behaviour**: no money or mats = no poisons

**Expected behaviour**: Should get a stack of:
Crystal Vial - 8925
Essence of Agony - 8923
Deathweed - 5173
Dust of Deterioration - 8924

**Comment by Erodraeda** [comment]
I'd recommend adding:
- 3 stacks of the vials (8925);
- 2 stacks of 8924 (for 1 stack of instant poison);
- 2 stacks of 5173 (for 1 stack of deadly poison);
- 1 stack of 8923 (for 1 stack of crippling, wound or mind-numbing poisons, which rogues usually use during leveling)

Either that or just add 20 of each straight up (8985, 8927, 9186, 3776, 10922)
