### ISSUE TITLE
[Warlock][Spell] Unstable Affiction 

### ISSUE THREAD

**Issue by Firroth** [Atlantiss/NetherwingBugtracker#6894]
**Current behaviour**:
On dispel Unstable Affiction "one shoots" the dispeller for ridiculous amounts. Isn''t it a bit too OP? It's scaling with Spell Power must be wrong, since it hits more than Curse of Doom does.

Right now what it does is: it gives dispel immunity altogether. Throw UA on your target + rest of DoT's and some kind of CC, like roots/frost nova/fear and simply put you can't do shit about it, cause you will oneshoot yourself... 

Tested it today with green warlock 650-700 bsd. And that's for how much it hit me:
![Screenshot_7](https://user-images.githubusercontent.com/43505196/79673998-4c89a280-81df-11ea-85e6-48543729348d.png)

When I fought some s4/t6 geared warlocks it even went as far as to 21k dmg.

Only source I could find about it was from WoTLK, and it didn't go as far as on NW does.

![Screenshot_5](https://user-images.githubusercontent.com/43505196/79674043-b4d88400-81df-11ea-8356-9426d51f190a.png)

https://www.mmo-champion.com/threads/698245-Unstable-Affliction-Extremely-OP-Nerf-time!

Edit: Tested it with another warlock (1063 bsd). On 200 resilence 
![Screenshot_6](https://user-images.githubusercontent.com/43505196/79674629-3f6fb200-81e5-11ea-8c47-477cfc243e99.png)

**Expected behaviour**: 
It should act as deterent for dispels, cause of 4s silence effect and hitting for like 1/4 or at best 1/2 of total hp of the dispeller, not his entire health bar.

If it really did hit for this much on TBC I will accept it, but I would like to see some kind of proof.

**Server Revision**: 
3323

**Comment by Wolffenstein** [comment]
Should be fixed.
