### ISSUE TITLE
Instant 58 Feed Pet issue

### ISSUE THREAD

**Issue by coendorf** [Atlantiss/NetherwingBugtracker#6897]
[//]: # (Enclose links to things related to the bug using http://wowhead.com or any other TBC database.)
[//]: # (You can use screenshot ingame to visual the issue.)
[//]: # (Write your tickets according to the format:)
[//]: # ([Quest][Azuremyst Isle] Red Snapper - Very Tasty!)
[//]: # ([NPC] Magistrix Erona)
[/Feet Pet/]: # ([Spell][Mage] Fireball)
[//]: # ([Npc][Drop] Ghostclaw Lynx)
[//]: # ([Web] Armory doesnt work)
[//]: # (To find server revision type `.server info` command in the game chat.)

**Description**: Feeding pet does not seem to work on instant 58 characters. If I feed the pet, the animation occurs but the pet does not receive the feeding buff and does not gain happiness. This happens whether I drag a food from inventory or click on the Feed Pet ability and then on the food. I have the Feed Pet ability and I have the correct food to feed the pet.

**Current behaviour**:

**Expected behaviour**: 

**Server Revision**:

**Comment by Evolvee** [comment]
![image](https://user-images.githubusercontent.com/1942409/79693373-8bb10580-826a-11ea-990e-f1a1376d5dc4.png)

it works perfectly fine for me...

what food are you using? are u sure u are using the proper food?

**Comment by coendorf** [comment]
Apologies, my mistake. I used food that was too high level for the pet.
