### ISSUE TITLE
Shartuul's transporter event 4th boss Dreadmaw not working properly, and 3rd one quite possibly overtuned

### ISSUE THREAD

**Issue by thunderingroar** [Atlantiss/NetherwingBugtracker#6899]
**Description**: Dreadmaw moves much faster than he should, somehow gets even faster with his growth stacks, even with several stacks his hitbox increses to the point where its impossible to outrun him even with the 30% blazing speed buff in fire form. Also im pretty sure his charge doesnt apply slow and DoT debuff on you(that you re suppose to dispell), im not too certain on this one because i can only do this once every few days when i collect enough darkrune shards.
Video of how slow he usually moves: https://youtu.be/Jsi6lHxVjuM?t=245
13 year old video with shittier quality: https://youtu.be/Cvmn5NIs4b0?t=416 (even the clicker manages to outrun him)

On a side note i also think that the 3rd Eyeballs boss is overtuned, in those videos people kill it with ease by just applying syphon life and ice blocking the Dark glare from time to time, but on this server i have to bait his electric field thingy far away from the warp-gate only so that i can LoS his fel fireballs (or whatever its called) because it hits really hard.

Other than that first 2 bosses work fine except some minor issues during the 2nd fight (the doomguard one) where the small Gan'arg sometimes randomly evade the fight after you use jump ability or even after chasing you and they become transparent and just stand there until you attack them (they become almost impossible to target without tab key), also they rarely ever construct the fel cannons. Still this isnt a big problem since its only the ads and they have rather low hp anyway.
**Current behaviour**: Dog boss too fast, pretty sure he doesnt apply debuff after charge

**Expected behaviour**: Sluggish, should put a DoT/slow on you after charge

**Comment by hederob** [comment]
Just recall that the the fire stance of the demons runs faster. Ya, there are many issues with the last demon. Ice block should reflect half the damage, her abilities should be doing more percentage of health as damage, her self heals should be higher, and her ultimate should do a lot of damage/heal quote a large amount.

**Comment by Evolvee** [comment]
yea unfortunately all the issues are spell-related and only wolfenstein can fix them (requires core)

**Comment by hederob** [comment]
Any way you can nerf it to the point so it can be soloed? Like still requiring focus, soloable, and challenging until it can restored to retail values?

**Comment by Evolvee** [comment]
yea but i would rather get it fixed properly.. :/

**Comment by Shineslippers** [comment]
Up! 2024 is already here...

Phase 2
[Gan'arg Underling](https://www.wowhead.com/tbc/npc=23199/ganarg-underling#comments) has tendency to evade after spawn. Player can cast stun on it or just run out and they will return to spawn spot.

Phase 4
[Dreadmaw](https://www.wowhead.com/tbc/npc=23275/dreadmaw) always outrun a player. More stack he is getting - faster running. You just can't keep him on distance. On top of it after charge he is no apply [Lacerating Bite](https://www.wowhead.com/tbc/spell=41940/lacerating-bite)

Other
[Shivan Assassin](https://www.wowhead.com/tbc/npc=23220/shivan-assassin) spell [Death Blast](https://www.wowhead.com/tbc/spell=40736/death-blast) doesn't work properly. It's convert only initial damage into healing. Doesn't matter how long debuff is active on target healing always the same.
I don't know is it correct or not but seems very odd that a player can cast abilities on all of those demons. You can Fear it, apply Curse of Tongues and other debuffs. That makes whole event itrrelevant.

**Comment by Godmatik** [comment]
Closing - consolidating all information into one thread
