### ISSUE TITLE
Hunter Pet Quest XP

### ISSUE THREAD

**Issue by Ahmpy** [Atlantiss/NetherwingBugtracker#69]
[//]: # (Enclose links to things related to the bug using http://wowhead.com or any other TBC database.)
[//]: # (You can use screenshot ingame to visual the issue.)
[//]: # (Write your tickets according to the format:)
[//]: # ([Quest][Azuremyst Isle] Red Snapper - Very Tasty!)
[//]: # ([NPC] Magistrix Erona)
[//]: # ([Spell][Mage] Fireball)
[//]: # ([Npc][Drop] Ghostclaw Lynx)
[//]: # ([Web] Armory doesnt work)

**Description**: 
[Quest] Taming the Beast hunter class quests should give experience
**Current behaviour**:
Troll and orc taming the beast quests do not give any experience
**Expected behaviour**: 
All three steps of [Quest] Taming the beast should give 850 exp
http://wowwiki.wikia.com/wiki/Quest:Taming_the_Beast

**Server Revision**:

**Comment by Evolvee** [comment]
https://github.com/Atlantiss/AtlantissTBCBT/issues/1521

**Comment by wtRCH** [comment]
@pelekon

**Comment by pelekon** [comment]
fixed in rev 2432
