### ISSUE TITLE
Flight Master in UC only provides flights if you accept his quest

### ISSUE THREAD

**Issue by padomu** [Atlantiss/NetherwingBugtracker#690]
[//]: # (Enclose links to things related to the bug using http://wowhead.com or any other TBC database.)
[//]: # (You can use screenshot ingame to visual the issue.)
[//]: # (Write your tickets according to the format:)
[//]: # ([Quest][Azuremyst Isle] Red Snapper - Very Tasty!)
[//]: # ([NPC] Magistrix Erona)
[//]: # ([Spell][Mage] Fireball)
[//]: # ([Npc][Drop] Ghostclaw Lynx)
[//]: # ([Web] Armory doesnt work)

**Description**:  & **Current behaviour**:

I'm a lvl 20 rogue. The flight master in UC, Michael Garrett only provides me the option to fly if I accept the Quest "Return to Podrig". This is a follow up quest (I think, guessing from the name). So that might be part of the problem.

**Expected behaviour**: 

I should always be able to fly.

**Server Revision**: 
2060

**Comment by wtRCH** [comment]
Work as intended.
