### ISSUE TITLE
[Spell] Hellscream's Warsong increases ranged attack speed

### ISSUE THREAD

**Issue by Tereneckla** [Atlantiss/NetherwingBugtracker#6901]
[//]: # (Enclose links to things related to the bug using http://wowhead.com or any other TBC database.)
[//]: # (You can use screenshot ingame to visual the issue.)
[//]: # (Write your tickets according to the format:)
[//]: # ([Quest][Azuremyst Isle] Red Snapper - Very Tasty!)
[//]: # ([NPC] Magistrix Erona)
[//]: # ([Spell][Mage] Fireball)
[//]: # ([Npc][Drop] Ghostclaw Lynx)
[//]: # ([Web] Armory doesnt work)
[//]: # (To find server revision type `.server info` command in the game chat.)

**Description**: https://www.wowhead.com/spell=34410
It probably also should be removed when entering raids, as it is a world buff.

**Current behaviour**: Increases melee and ranged attack speed by 15%

**Expected behaviour**: Increases melee attack speed by 15%

**Server Revision**: 3323

**Comment by Wolffenstein** [comment]
Fixed in rev 3435.
