### ISSUE TITLE
[Quest] Discovering your roots

### ISSUE THREAD

**Issue by Tereneckla** [Atlantiss/NetherwingBugtracker#6903]
[//]: # (Enclose links to things related to the bug using http://wowhead.com or any other TBC database.)
[//]: # (You can use screenshot ingame to visual the issue.)
[//]: # (Write your tickets according to the format:)
[//]: # ([Quest][Azuremyst Isle] Red Snapper - Very Tasty!)
[//]: # ([NPC] Magistrix Erona)
[//]: # ([Spell][Mage] Fireball)
[//]: # ([Npc][Drop] Ghostclaw Lynx)
[//]: # ([Web] Armory doesnt work)
[//]: # (To find server revision type `.server info` command in the game chat.)

**Description**: there is a core problem with MC (autoattack of main char) and there needs to be added max distance to evade while in MC (core as well)

Furthermore the the pets Ravager Taunt (46276) makes the target focus you instead of the pet.

Digging out a root sometimes makes the pet unresponsive to commands until you issue an attack command.

**Server Revision**: 3223

**Comment by eri1997** [comment]
Was fine for me. I think autoattacks worked fine for hunter (wasn't really looking for that so maybe I'm wrong) . For the mounds you have to manually spam click the pet spell and it works fine

**Comment by raethkcj** [comment]
I was able to complete the quest fine. The first click on the dig ability makes the pet run to a mound, the second click makes it uncover the root. If there's a 2nd mound in range, sometimes it will run back and forth between them instead of digging at either.

**Comment by Tankdiehutte** [comment]
The Player is still unable to autoattack while controling the pet, but spells work. 
https://youtu.be/E8QL4xUG1rY

**Comment by iMuuli** [comment]
Okay. A further bug with the quest. If you fly away with the pet active, it gets dismissed. I don't get my frames despawned or anything but that might just be my addons. However, if you then dismount and "/reload ui" the pet spawns back and is fully controllable.

**Comment by Godmatik** [comment]
Auto-attack not working while having a pet was fixed a long time ago
Can not reproduce the issue about the ravager taunt making the target focus you instead of the pet
