### ISSUE TITLE
Fresh instant lvl 58 rogue with no lockpicking skill

### ISSUE THREAD

**Issue by ptk92** [Atlantiss/NetherwingBugtracker#6904]
Hi, I've opened a ingame ticket and the GM left me a letter saying to post my problem here for someone to read and help me with that. 
http://prntscr.com/s3jy6b

greets ptk

**Comment by Evolvee** [comment]
nick ingame?

**Comment by ptk92** [comment]
Neckbreakerr

**Comment by ptk92** [comment]
@Evolvee u gonna help me with that ??

**Comment by Evolvee** [comment]
you are never online when you write...

**Comment by ptk92** [comment]
I was online when i wrote, i will be online rn too..
