### ISSUE TITLE
[Spell][Item] Glimmering Naaru Sliver

### ISSUE THREAD

**Issue by Ychap** [Atlantiss/NetherwingBugtracker#6905]
[//]: # (Enclose links to things related to the bug using http://wowhead.com or any other TBC database.)
[//]: # (You can use screenshot ingame to visual the issue.)
[//]: # (Write your tickets according to the format:)
[//]: # ([Quest][Azuremyst Isle] Red Snapper - Very Tasty!)
[//]: # ([NPC] Magistrix Erona)
[//]: # ([Spell][Mage] Fireball)
[//]: # ([Npc][Drop] Ghostclaw Lynx)
[//]: # ([Web] Armory doesnt work)
[//]: # (To find server revision type `.server info` command in the game chat.)

**Description**:
The use-effect of [Glimmering Naaru Sliver](https://tbcdb.com/?item=34430) does not scale with haste. But the tooltip of the item changes, when you equip haste-items.

**Current behaviour**:
The use-effect channels always fully 8 seconds.

**Expected behaviour**:
The use-effect should scale with haste as written in the tooltip.

**Server Revision**:
3323

**Source**:
https://www.wowhead.com/item=34430/glimmering-naaru-sliver#comments:id=298959

**Comment by Wolffenstein** [comment]
Fixed in rev 3378.
