### ISSUE TITLE
[Hunter][Spell]Steady/Auto shot interaction

### ISSUE THREAD

**Issue by Red86** [Atlantiss/NetherwingBugtracker#6906]
**Description**: 
Right now it seems that there's some wierd interaction between Auto/Steady shot that doesn't cause it to reset properly.

**Current behaviour**:
The following was observed on the PTR against the dummies **without** using any macro.

-**Target a dummy  and cast steady shot.** 
Cast bar appears, if you cancel the cast (by pressing esc or moving) when you try to cast again, you'll get again the cast bar for steady shot (this will be important in a moment)

-**Cast one steady shot**.
 Steady shot will hit the target immediately followed by an auto shot and, stop attacking the target.

-**Try to cast Steady shot again**. 
This time no cast bar appears but instead your character will first auto shoot then immediately after start casting the steady shot. Even if you wait long enough to be out of combat or change targets, your character will be "stuck" in this "First auto then steady" state.  This also persists between logins, if you logout then back in and try to cast Steady Shot, your character will first try and cast auto before steady.

Feign Death will fix this most of the times but, not always, I had times where it was still getting stuck in that state.

If you allow the character to cast first that auto shot then stop attacking you will once again be able to get SS to cast when you press 2.

It almost feels like the whole 0.5 seconds buffer for AS protection gets cleared only when the autoshoot goes off and this stays in the server memory until finally that AS goes off.  

**Expected behaviour**: 

Steady shot casts should not be delayed, unless the steady shot is casted within 0.5 seconds of the auto shoot going off as detailed here:

https://wow.allakhazam.com/wiki/shot_rotation_%28WoW%29#Solution_#3:_Steady_Shot_Spam_(3:2_rotation)

In my case, this behaviour was observed several seconds after I last attacked the target. While the behaviour is correct if steady is being spammed, if you cast it several second after the last attack, it should behave like it does when you first target an enemy.

**Server Revision**: 
3323 (PTR)

**Comment by Red86** [comment]
Okay I've done further testing and found a way to 100% fix this behaviour.

As I've detailed abow, after a successful cast your character will be stuck in this "first auto then steady" state regardless of how long it has been since you last attacked.

Further observations made:

**What happens during the "auto first then steady" state**

Once you press steady again and your character will autoshoot first, even if you press ESC to stop autoattacking, your character will then stand still until 1 second after where a steady shot will go off, no cast bar will be displayed but the Steady will go out and, turn your auto shot back on.

**How you fix this**

once you press steady and your character starts the auto shoot animation, you should allow the Auto shoot to go off but then move or turn around to prevent the upcoming steady from casting.

Trying to /stopattack or canceling the attack with ESC will results either in:

- The "invisible steady" situation described above where your steady will still go off without displaying a bar, if you cancel immediately after the autoshot goes off

-The "auto first then steady" behaviour reoccurring if you cancel while the cast bar for the steady shot that occurs after the auto is being displayed.

Again, the behaviour of delaying a steady shot to allow an auto shot to go through is correct only and exclusively when the steady shot key is pressed within 0.5 seconds of your next auto. All steady shot casts occurring outside this time frame should result in steady shot being casted.

**Comment by TheMoneyHater** [comment]
https://streamable.com/6lg3jf
https://streamable.com/am4cjh
Idk what u are on but u shouldn't be getting these full gcd. Ofc the autoshot can push it forward but here it is taking much longer for it to do so then on retail.

**Comment by Wolffenstein** [comment]
Please retest in rev 3420.

**Comment by TheMoneyHater** [comment]
@Wolffenstein What did u change exactly? Seems to be even more wrong now.
the 3:2 rotation is still not working as it should since there is a issue with the spell batching that was implented months ago. those fake gcds are a huge issue to playstyle.

**Comment by Wolffenstein** [comment]
Continued in #7069.
