### ISSUE TITLE
Spirit Tap 5/5

### ISSUE THREAD

**Issue by alexclapou** [Atlantiss/NetherwingBugtracker#6907]
**Description**: 
so the spirit tap at 5 points should give you a 100% chance to increase your spirit by 100% but it doesn't work everytime, i couldn't notice the cases where it doesn't work but it doesn't always work.(same mobs, sometimes proc sometimes not)
**Current behaviour**:
Does not give 100% bonus spirit every time you kill a creature that gives you xp/honor
**Expected behaviour**: 
100% bonus spirit everytime you kill a creature that gives you xp/honor
**Server Revision**:

**Comment by duzyizly** [comment]
make sure that:
1. **YOU** killed the mob (not your teammate or pet)
2. Mob givex XP [not some summoned shiet worth 0xp]

**Comment by Tereneckla** [comment]
Could not recreate this. Would you please clarify the situation when it happened?

**Comment by Tereneckla** [comment]
Dead Issue
