### ISSUE TITLE
Priest 6p D1 / 4p D2 set Removed by Power word shield 

### ISSUE THREAD

**Issue by Bartolhomer** [Atlantiss/NetherwingBugtracker#6908]
Item sets Devout Armor (D1) 
And Vestment of the virtuous(D2) ttps://tbcdb.com/?itemset=182
https://tbcdb.com/?itemset=514     

Using spell https://tbcdb.com/?spell=27778 
To apply 
https://tbcdb.com/?spell=27779 
on the wearer. 

**Current behaviour**:  The proc rate seems fine. Proc gets removed by priest Power word Shield. They do not Stack as indented. 

**Expected behaviour**: 
Should be able to stack the proc  buff with all PW:Shield Buffs

**Server Revision**:  <- what does this mean ?

**Comment by Wolffenstein** [comment]
Fixed in rev 3354.
