### ISSUE TITLE
Bugs in Karazhan

### ISSUE THREAD

**Issue by blazzerbg** [Atlantiss/NetherwingBugtracker#6909]
![WoWScrnShot_042320_213748](https://user-images.githubusercontent.com/64227878/80145633-28500c00-85b9-11ea-9522-f90cdd7b2d1a.jpg)
[//]: # (Enclose links to things related to the bug using http://wowhead.com or any other TBC database.)
[//]: # (You can use screenshot ingame to visual the issue.)
[//]: # (Write your tickets according to the format:)
[//]: # ([Quest][Azuremyst Isle] Red Snapper - Very Tasty!)
[//]: # ([NPC] Magistrix Erona)
[//]: # ([Spell][Mage] Fireball)
[//]: # ([Npc][Drop] Ghostclaw Lynx)
[//]: # ([Web] Armory doesnt work)
[//]: # (To find server revision type `.server info` command in the game chat.)

**Description**: During a fight with Nightbane his fear got me trough the wall and i fell down off the terrace

**Current behaviour**: Fear bugged people trough the wall

**Expected behaviour**: Players should stop at wall and turn to another side

**Server Revision**:

**Comment by Easyfraggy** [comment]
We have had this issue before but cannot recreate, we need video of the specific spots that this happens on.

**Comment by Evolvee** [comment]
https://github.com/Atlantiss/NetherwingBugtracker/issues/6355
