### ISSUE TITLE
[Quest][Stranglethorn Vale] Bookie Herod

### ISSUE THREAD

**Issue by kudryashov-n** [Atlantiss/NetherwingBugtracker#691]
[//]: # (Enclose links to things related to the bug using http://wowhead.com or any other TBC database.)
[//]: # (You can use screenshot ingame to visual the issue.)
[//]: # (Write your tickets according to the format:)
[//]: # ([Quest][Azuremyst Isle] Red Snapper - Very Tasty!)
[//]: # ([NPC] Magistrix Erona)
[//]: # ([Spell][Mage] Fireball)
[//]: # ([Npc][Drop] Ghostclaw Lynx)
[//]: # ([Web] Armory doesnt work)

**Description**: 
At least one of the quest can't be picked up: Jungle Secrets or Bookie Herod (need research)
**Current behaviour**:
Can't pick up the quest. Lieutenant Doren doesn't even have a menu to speak.
**Expected behaviour**: 
Should give Bookie Herod quest.
**Server Revision**:

**Comment by tcberk12** [comment]
It looks like this quest is only available after saving Thorsen from an ambush by Kurzen lackeys while he is patrolling away from the camp.

Comment from November 2006 on http://classicdb.ch/?quest=215:
> Every so often, Thorsen will go on patrol. If you follow him, he will be ambushed by two of Kurzen's lackeys (at around (40, 8) ) - if he survives, you will be able to start this quest off him then.

I am not sure if this event is in the game however, and if he correctly provides the quest after saving him. 

More info can be found on Private Thorsen's page as well: http://classicdb.ch/?npc=738

**Comment by aresbrutus** [comment]
This is scripted and in game. You just have to indeed either wait for him to move out on his patrol, or luckily stumble on him and save him.
