### ISSUE TITLE
[Spell][Mage] Polymorph regeneration rate on pets is low

### ISSUE THREAD

**Issue by 4egito** [Atlantiss/NetherwingBugtracker#6910]
[//]: # (Enclose links to things related to the bug using http://wowhead.com or any other TBC database.)
[//]: # (You can use screenshot ingame to visual the issue.)
[//]: # (Write your tickets according to the format:)
[//]: # ([Quest][Azuremyst Isle] Red Snapper - Very Tasty!)
[//]: # ([NPC] Magistrix Erona)
[//]: # ([Spell][Mage] Fireball)
[//]: # ([Npc][Drop] Ghostclaw Lynx)
[//]: # ([Web] Armory doesnt work)
[//]: # (To find server revision type `.server info` command in the game chat.)

**Description**: 
Polymorph regeneration rate on pets is low
**Current behaviour**:
https://drive.google.com/open?id=1Cj_S0k9pReioMwL-NdLJ0CKUt_Tps7OC
**Expected behaviour**: 
![image](https://user-images.githubusercontent.com/52432938/80264257-3aef4180-869c-11ea-9f7f-ddcafc3046f3.png)

**Server Revision**: 
3332

**Comment by Wolffenstein** [comment]
Fixed in rev 3347.
