### ISSUE TITLE
[Spell][Hunter] Freezing trap choosing target rework

### ISSUE THREAD

**Issue by 4egito** [Atlantiss/NetherwingBugtracker#6911]
[//]: # (Enclose links to things related to the bug using http://wowhead.com or any other TBC database.)
[//]: # (You can use screenshot ingame to visual the issue.)
[//]: # (Write your tickets according to the format:)
[//]: # ([Quest][Azuremyst Isle] Red Snapper - Very Tasty!)
[//]: # ([NPC] Magistrix Erona)
[//]: # ([Spell][Mage] Fireball)
[//]: # ([Npc][Drop] Ghostclaw Lynx)
[//]: # ([Web] Armory doesnt work)
[//]: # (To find server revision type `.server info` command in the game chat.)

**Description**: 
Freezing trap pick target like "if u are gay -> take that trap"... there is a video for it (please watch whole video)
**Current behaviour**:
https://drive.google.com/open?id=1b0HAVur9DtNW_G9N4_aOiA8kDtpg1UBd
**Expected behaviour**: 
![image](https://user-images.githubusercontent.com/52432938/80264859-36c42380-869e-11ea-91c7-8d65dbbd889b.png)
I can't find proper information about how it should work but i think that should be the closest person... Only this seems logical for me
**Server Revision**: 
3332

**Comment by Wolffenstein** [comment]
Fixed in rev 3340.
