### ISSUE TITLE
[Pets] Warlock and Hunter pets does not accept commands properly

### ISSUE THREAD

**Issue by 4egito** [Atlantiss/NetherwingBugtracker#6912]
[//]: # (Enclose links to things related to the bug using http://wowhead.com or any other TBC database.)
[//]: # (You can use screenshot ingame to visual the issue.)
[//]: # (Write your tickets according to the format:)
[//]: # ([Quest][Azuremyst Isle] Red Snapper - Very Tasty!)
[//]: # ([NPC] Magistrix Erona)
[//]: # ([Spell][Mage] Fireball)
[//]: # ([Npc][Drop] Ghostclaw Lynx)
[//]: # ([Web] Armory doesnt work)
[//]: # (To find server revision type `.server info` command in the game chat.)

**Description**: 
Pets have some strange queue for commands which is weird. In this video u will see what i'm doing but the pet does shits anyway. 
1. Devour magic
2. Pet follow
3. Spell lock
4. Pet follow
And in the end the pet goes automatically without any command...
As hunter is a bit better but still shit. Sometimes pet does weird things like this, maybe because of auto casting abilities.
**Current behaviour**:
https://drive.google.com/open?id=1UPbbx41eYULWXvh-3FH7Jri7EtAp1TDZ
**Expected behaviour**: 
Pets on passive mode should does exactly what their master orders...
https://wow.gamepedia.com/Passive
**Server Revision**: 
3332

**Comment by Wolffenstein** [comment]
Fixed in rev 3340.
