### ISSUE TITLE
[Core][Spell] Frost Nova interrupts cast

### ISSUE THREAD

**Issue by Drainlock** [Atlantiss/NetherwingBugtracker#6914]
https://clips.twitch.tv/BoxyBombasticMomCurseLit
Frost nova interrutping cast when it wear off

server rev 3322

**Comment by raethkcj** [comment]
Due to frost nova fading, or due to exiting arena placing you slightly above the ground? It might just be the latter, and frost nova wearing off causes your character to fall slightly to the ground, interrupting your cast.

**Comment by Godmatik** [comment]
Unable to reproduce - must have been fixed at some point.
