### ISSUE TITLE
[You, Robot] quest is bugged.

### ISSUE THREAD

**Issue by diminian** [Atlantiss/NetherwingBugtracker#6917]
[//]: # (Enclose links to things related to the bug using http://wowhead.com or any other TBC database.)
[//]: # (You can use screenshot ingame to visual the issue.)
[//]: # (Write your tickets according to the format:)
[//]: # ([Quest][Azuremyst Isle] Red Snapper - Very Tasty!)
[//]: # ([NPC] Magistrix Erona)
[//]: # ([Spell][Mage] Fireball)
[//]: # ([Npc][Drop] Ghostclaw Lynx)
[//]: # ([Web] Armory doesnt work)
[//]: # (To find server revision type `.server info` command in the game chat.)

**Description**: 
I've came across an odd issue with quest [You, Robot] in Area-52.
When I enable the 'Scrap Reaver X6000' the enemy 'Negatron' approaches, but I cannot attack it. It says 'invalid target'. Not my character, nor 'Scrap Reaver X6000' can attack 'Negatron'.
Also when I use an ability of 'Scrap Reaver X6000' - stomp - everything reset - both 'Scrap Reaver X6000' & 'Negatron' disapper.
When I cancel the quest also quest giver does not reset, so I cannot take the quest again, unless I leave the area and come back.
I tried this multiple times, tried cache removal and etc, nothing helped.

**Current behaviour**:
Quest is not complitable.

**Expected behaviour**: 
Quest is working correctly.

**Server Revision**: 
3336

**Comment by Wolffenstein** [comment]
![obraz](https://user-images.githubusercontent.com/1576644/80396433-e96dcf00-88b4-11ea-9c6e-5004c00c7d20.png)

Works fine, just tested it on live realm.
