### ISSUE TITLE
[Quest][Pet] Discovering Your Roots bugs pet

### ISSUE THREAD

**Issue by veekk** [Atlantiss/NetherwingBugtracker#6919]
**Description**:  after completing quest, if u don't dismiss ravager and flying to isle to hand quest, u'll get bugged pet (unknown, can't be dismissed) and can't resummon demon e.g. 'cause of it until relog
<img width="1920" alt="Screen Shot 2020-04-27 at 1 07 29 PM" src="https://user-images.githubusercontent.com/12899687/80379352-a9075480-88a6-11ea-87e8-7b7673a6720a.png">
<img width="1920" alt="Screen Shot 2020-04-27 at 1 07 31 PM" src="https://user-images.githubusercontent.com/12899687/80379430-c2100580-88a6-11ea-999e-748fd22f3e2e.png">

**Current behaviour**:

**Expected behaviour**: 

**Server Revision**:

**Comment by Evolvee** [comment]
https://github.com/Atlantiss/NetherwingBugtracker/issues/6516#issuecomment-587576516
requires @Wolffenstein to fix "area changed" SAI action
