### ISSUE TITLE
Wyvern Sting doesn't poison the target after it expires.

### ISSUE THREAD

**Issue by elenmerbau** [Atlantiss/NetherwingBugtracker#6920]
[//]: # (Enclose links to things related to the bug using http://wowhead.com or any other TBC database.)
[//]: # (You can use screenshot ingame to visual the issue.)
[//]: # (Write your tickets according to the format:)
[//]: # ([Quest][Azuremyst Isle] Red Snapper - Very Tasty!)
[//]: # ([NPC] Magistrix Erona)
[//]: # ([Spell][Mage] Fireball)
[//]: # ([Npc][Drop] Ghostclaw Lynx)
[//]: # ([Web] Armory doesnt work)
[//]: # (To find server revision type `.server info` command in the game chat.)

**Description**: 
Wyvern Sting puts the target into sleep, but after that it doesn't poison it as it should. Sleep wasn't broken by any damage or other hunter stings.
**Current behaviour**:
^
**Expected behaviour**: 
It should sleep and poison after the sleep effect expires.
https://tbcdb.com/?spell=27068
**Server Revision**: 
3336

**Comment by Excinerus** [comment]
i didn't get poisoned after sting in BG

**Comment by Wolffenstein** [comment]
Fixed in rev 3387.
