### ISSUE TITLE
[Spell]Stealth detection icon

### ISSUE THREAD

**Issue by subi900** [Atlantiss/NetherwingBugtracker#6921]
[//]: # (Enclose links to things related to the bug using http://wowhead.com or any other TBC database.)
[//]: # (You can use screenshot ingame to visual the issue.)
[//]: # (Write your tickets according to the format:)
[//]: # ([Quest][Azuremyst Isle] Red Snapper - Very Tasty!)
[//]: # ([NPC] Magistrix Erona)
[//]: # ([Spell][Mage] Fireball)
[//]: # ([Npc][Drop] Ghostclaw Lynx)
[//]: # ([Web] Armory doesnt work)
[//]: # (To find server revision type `.server info` command in the game chat.)

**Description**: 
Today, after the restart from 5pm, I don't see stealth detection Icons on enemies anymore.
I've deleted my cache folder.
**Current behaviour**:
The stealth detection icons are missing. At least for Stratholme Ghouls and Undead where I am right now.

**Expected behaviour**: 
As Rogue or Druid, as soon you go in stealth, you see an icon above enemies which have stealth detection.

**Server Revision**: 
3338
<img width="431" alt="Capture" src="https://user-images.githubusercontent.com/56795326/80514411-c1e43880-8980-11ea-89fd-537a4b88c6ae.PNG">

**Comment by subi900** [comment]
The sprites are back now. Maybe it was related to the no whirlwind sprites in ZA issue.

**Comment by Wolffenstein** [comment]
fixed
