### ISSUE TITLE
[Item] Frostguard poor proc chance

### ISSUE THREAD

**Issue by veekk** [Atlantiss/NetherwingBugtracker#6923]
**Description**:  
<img width="240" alt="image" src="https://user-images.githubusercontent.com/12899687/80710686-d7c83980-8af7-11ea-8d28-d4cca0fa46d4.png"> don't have annotation about proc on targets above level 60, but it's not pricing at all
not confirmed [source](https://xpoff.com/threads/weapon-proc-rates.60492/) with 15%, same as [Annihilator]

**Current behaviour**: 0 procs from 150+ attacks
 
**Expected behaviour**: procs

**Server Revision**: 3338

**Comment by Wolffenstein** [comment]
Fixed in rev 3345.
