### ISSUE TITLE
[SWP][M'uru] Humanoid mobs sometimes reset on low hp

### ISSUE THREAD

**Issue by eri1997** [Atlantiss/NetherwingBugtracker#6924]
[//]: # (Enclose links to things related to the bug using http://wowhead.com or any other TBC database.)
[//]: # (You can use screenshot ingame to visual the issue.)
[//]: # (Write your tickets according to the format:)
[//]: # ([Quest][Azuremyst Isle] Red Snapper - Very Tasty!)
[//]: # ([NPC] Magistrix Erona)
[//]: # ([Spell][Mage] Fireball)
[//]: # ([Npc][Drop] Ghostclaw Lynx)
[//]: # ([Web] Armory doesnt work)
[//]: # (To find server revision type `.server info` command in the game chat.)

**Description**: https://streamable.com/g7d0rt
Look at the fury mage went from low hp to reseting and going back to the side it spawned on with full hp .

**Current behaviour**: Humanoid wave mobs randomly reset

**Expected behaviour**: Humanoid waves mobs  don't reset :(

**Server Revision**: latest

**Comment by Wolffenstein** [comment]
Fixed in rev 3346.
