### ISSUE TITLE
Gnomish Engineering to Goblin Engineering specialization switch

### ISSUE THREAD

**Issue by jorixnetherwing** [Atlantiss/NetherwingBugtracker#6925]
hello there,

i have opened a ticket regarding switching engineering specialization from gnomish to goblin, and the GM advised me to visit all of: Gadgetzan, Rachet, Booty Bay and Orgrimmar but I could not switch. Please help me
Note: The book in Tanaris named [Book "Soothsaying for Dummies"] is not working for me which is the main issue.

**Comment by Wolffenstein** [comment]
You can't switch specialization in TBC, that option was only added in Wotlk. The only solution is to abandon your current specialization, pick up the new one and start from scratch.
