### ISSUE TITLE
[PvP] Warsong Horde gates not despawning after match start.

### ISSUE THREAD

**Issue by Tereneckla** [Atlantiss/NetherwingBugtracker#6926]
[//]: # (Enclose links to things related to the bug using http://wowhead.com or any other TBC database.)
[//]: # (You can use screenshot ingame to visual the issue.)
[//]: # (Write your tickets according to the format:)
[//]: # ([Quest][Azuremyst Isle] Red Snapper - Very Tasty!)
[//]: # ([NPC] Magistrix Erona)
[//]: # ([Spell][Mage] Fireball)
[//]: # ([Npc][Drop] Ghostclaw Lynx)
[//]: # ([Web] Armory doesnt work)
[//]: # (To find server revision type `.server info` command in the game chat.)

**Description**: 
![image](https://user-images.githubusercontent.com/50233983/80868779-f0258900-8c9c-11ea-9bd0-468c980fb726.png)
![image](https://user-images.githubusercontent.com/50233983/80868782-f74c9700-8c9c-11ea-97e5-f26c9e4438b9.png)

**Current behaviour**: Staying there forever.

**Expected behaviour**: Despawn after they opened.

**Server Revision**: 3338

**Comment by Wolffenstein** [comment]
Proof?

**Comment by Tereneckla** [comment]
https://www.youtube.com/watch?v=Hv2GHjNvIqA
![image](https://user-images.githubusercontent.com/50233983/80870251-89589d80-8ca5-11ea-820a-7ba9321dfc94.png)

**Comment by Wolffenstein** [comment]
Fixed in rev 3357.
