### ISSUE TITLE
[NPC][Essence of Anger] Casts Spite on tank

### ISSUE THREAD

**Issue by Refuge001** [Atlantiss/NetherwingBugtracker#6927]
[//]: # (Enclose links to things related to the bug using http://wowhead.com or any other TBC database.)
[//]: # (You can use screenshot ingame to visual the issue.)
[//]: # (Write your tickets according to the format:)
[//]: # ([Quest][Azuremyst Isle] Red Snapper - Very Tasty!)
[//]: # ([NPC] Magistrix Erona)
[//]: # ([Spell][Mage] Fireball)
[//]: # ([Npc][Drop] Ghostclaw Lynx)
[//]: # ([Web] Armory doesnt work)
[//]: # (To find server revision type `.server info` command in the game chat.)

Description: Describe the problem
Essence of Anger is currently casting Spite on tanks - which is causing them to go immune and drop threat temporarily. Included are two pictures of recount taken of our warrior and paladin tank both having spite cast on them on different attempts. (It happened every attempt).

-Spite: 3 random targets get a debuff which grants 2 sec immunity, then deals 7444-7556 nature damage followed by another 2 sec immunity.

Current behaviour: Tank becomes immune causing him to lose threat, causing Boss to attack next highest threat, which causes the Seethe debuff on the entire raid.

Expected behaviour: What should happen instead
He should not cast Spite on tanks.

Proof:
![Spite 1](https://user-images.githubusercontent.com/48739878/80869711-9b1b5000-8c67-11ea-99c5-d244bccbf25e.png)
![Spite 2](https://user-images.githubusercontent.com/48739878/80869713-9e164080-8c67-11ea-9fd5-2fbf8d5bbbe5.png)

Steps to reproduce the problem:

1. Maintain aggro on Essence of Anger
2. Wait until he casts Spite on tank

Revision: Current server revision: 3338
(You can see current server revision by typing ".server info" in the in-game chat.

**Comment by Wolffenstein** [comment]
Fixed in rev 3353.

**Comment by Refuge001** [comment]
Thanks Wolffenstein
