### ISSUE TITLE
[NPC] Alchemist Pestlezugg

### ISSUE THREAD

**Issue by Lexhor** [Atlantiss/NetherwingBugtracker#6928]
[//]: # (Enclose links to things related to the bug using http://wowhead.com or any other TBC database.)
[//]: # (You can use screenshot ingame to visual the issue.)
[//]: # (Write your tickets according to the format:)
[//]: # ([Quest][Azuremyst Isle] Red Snapper - Very Tasty!)
[//]: # ([NPC] Magistrix Erona)
[//]: # ([Spell][Mage] Fireball)
[//]: # ([Npc][Drop] Ghostclaw Lynx)
[//]: # ([Web] Armory doesnt work)
[//]: # (To find server revision type `.server info` command in the game chat.)

**Description**:  The NPC [Alchemist Pestlezugg](https://tbc-twinhead.twinstar.cz/?npc=5594) sell recipes, but not  all things he can

**Current behaviour**: The NPC is supposed to sell the recipes [Transmute Mithril to Truesilver](https://tbc-twinhead.twinstar.cz/?item=9305) and [Nature Protection Potion](https://tbc-twinhead.twinstar.cz/?item=6057), but he dont sell it

**Expected behaviour**: [He](https://tbc-twinhead.twinstar.cz/?npc=5594) can sell Recipe: Nature Protection Potion, Recipe: Transmute Mithril to Truesilver, Recipe: Transmute Iron to Gold, Recipe: Transmute Arcanite and Recipe: Philosopher's Stone

**Server Revision**: Idk

**Comment by Wolffenstein** [comment]
He does sell them. When a recipe is out of stock it will not be displayed in the vendor window.
