### ISSUE TITLE
[NPC] Exarch Nasuun attack and killable after PvP

### ISSUE THREAD

**Issue by Tankdiehutte** [Atlantiss/NetherwingBugtracker#6931]
**Description**: After attacking another player (Shattered sun turns hostile to player for ~30s)  the player can attack and kill the mob + The mob attacks the player if he comes too close.
Mob link: https://www.wowhead.com/npc=24932/exarch-nasuun

**Current behaviour**: Exarch Nasuun (gives daily quest) is attack and killable by a player. If players use Danarian's Scroll of Teleportation ( https://www.wowhead.com/item=35230/darnarians-scroll-of-teleportation) right after a pvp fight on the Island they immediately get attacked by him because they are hostile for the shattered sun.

**Expected behaviour**: Should not be attackable like other questmobs, since it takes a while til he respawns and Players cant accept the daily quest meanwhile. (Correct me if im wrong)

**Server Revision**: 3365

**Comment by Wolffenstein** [comment]
Fixed.
