### ISSUE TITLE
[Raid][BT] Sister Pack problems

### ISSUE THREAD

**Issue by Tereneckla** [Atlantiss/NetherwingBugtracker#6932]
[//]: # (Enclose links to things related to the bug using http://wowhead.com or any other TBC database.)
[//]: # (You can use screenshot ingame to visual the issue.)
[//]: # (Write your tickets according to the format:)
[//]: # ([Quest][Azuremyst Isle] Red Snapper - Very Tasty!)
[//]: # ([NPC] Magistrix Erona)
[//]: # ([Spell][Mage] Fireball)
[//]: # ([Npc][Drop] Ghostclaw Lynx)
[//]: # ([Web] Armory doesnt work)
[//]: # (To find server revision type `.server info` command in the game chat.)

**Description**: Sister of Pain and Sister of Pleasure got some issues.

**Current behaviour**: Sister of Pain stops attacking after she has cast Shell of Pain with Shared Bonds up.

They sometimes forget to buff themselves with Shared Bonds.

**Expected behaviour**: Sister of Pain keeps attacking after she has cast [Shell of Pain](https://www.wowhead.com/spell=41371)

They don't forget to buff themselves with [Shared Bonds](https://www.wowhead.com/spell=41362)/[Shared Bonds](https://www.wowhead.com/spell=41363)

**Server Revision**: 3366

**Comment by veekk** [comment]
can confirm

**Comment by Godmatik** [comment]
First issue about Shell of Pain stopping her melee attack was fixed

Second issue about them forgetting to buff with Shared Bonds (their link) still exists - it is rare and I am unsure how to reproduce, but it does happen at times when you pull them.
