### ISSUE TITLE
Felsworn Daggermaw Raptors

### ISSUE THREAD

**Issue by KenguruSafari** [Atlantiss/NetherwingBugtracker#6934]
Day two of raptors not being where they think they are.
Seems like server can't keep up with client or something strange.
Thunderan requested I submitted issue here with proof.

https://www.bitchute.com/video/G3wZX07B83E7/
Excuse the sound.
All three raptors in the video are pulled, but hey are all having issues.
This also makes pet sometimes unable to attack them.

**Comment by Wolffenstein** [comment]
Video gone, no info about reproduction. Closing.
