### ISSUE TITLE
[NPC][QUEST] Dark Iron Legacy / Franclorn Forgewright

### ISSUE THREAD

**Issue by Vantalim** [Atlantiss/NetherwingBugtracker#6935]
Server revision: 3367

This one has been opened before, but I'm facing the exact same issue.

![image](https://user-images.githubusercontent.com/32138244/81320399-6bb67a00-9091-11ea-91f7-f6fb65bfb20a.png)

Description: NPC Franclorn Forgewright is here as "unknown" npc and he doesn't offer an brd quest key aka dark iron legacy. It has been reported before and closed by "fixed in rev" at 5th october 2018 but still not working correctly.

Current behaviour: ^

Expected behaviour: should be named Franclorn Forgewright and offer a quest.

**Comment by Tereneckla** [comment]
clear cache
