### ISSUE TITLE
[General] Casting is interrupted randomly near Amani Lynx in Zul'Aman

### ISSUE THREAD

**Issue by raethkcj** [Atlantiss/NetherwingBugtracker#6936]
**Description**: 
Opening new issue based on #2909 since that one is apparently fixed. On a certain path in ZA, casting is randomly interrupted or not possible at all, giving "Interrupted." or "You can't do that while moving" errors. It's hard to tell whether it's related to the mobs, or the geometry of the ground. I haven't encountered this isssue elsewhere in ZA or other instances. Nothing special appears to happen in the combat log either. Video here: https://www.youtube.com/watch?v=kbv4UrpLxLw

**Current behaviour**:
Casting is interrupted for no apparent reason.

**Expected behaviour**: 
Casting works as normal.

**Server Revision**: 
3367

**Comment by raethkcj** [comment]
Here's another example with a different cast bar, if that helps: https://youtu.be/IEoEzB3vmKM?t=1380

**Comment by Wolffenstein** [comment]
Cannot reproduce.
