### ISSUE TITLE
[Loot][Skinning] Black Morass Skinning Loot Table

### ISSUE THREAD

**Issue by gmforghieri** [Atlantiss/NetherwingBugtracker#6937]
[//]: # (Enclose links to things related to the bug using http://wowhead.com or any other TBC database.)
[//]: # (You can use screenshot ingame to visual the issue.)
[//]: # (Write your tickets according to the format:)
[//]: # ([Quest][Azuremyst Isle] Red Snapper - Very Tasty!)
[//]: # ([NPC] Magistrix Erona)
[//]: # ([Spell][Mage] Fireball)
[//]: # ([Npc][Drop] Ghostclaw Lynx)
[//]: # ([Web] Armory doesnt work)
[//]: # (To find server revision type `.server info` command in the game chat.)

**Description**: 
Darkwater Crocolisk and Sable Jaguar in Black Morass should be able to drop multiple Knothide Leathers just as they do with Knothide Leather Scraps.

I only have the source for the crocolisk, but I believe this feature should apply to all skinnable creatures in dungeons in general, first comment:
https://www.wowhead.com/npc=17952/darkwater-crocolisk#comments

**Current behaviour**:
So far I haven't been able to loot more than 1 Knothide leather/creature in dungeons or raids, I am not entirely sure if I'm just unlucky or the loot table doesn't contain more than 1 leather/creature, thus some verification is needed. The loot table for mobs in Azeroth seems to be correct since the Gordok Hounds in Dire Maul can be skinned for multiple rugged leathers as it's also indicated by the comments on wowhead.
https://www.wowhead.com/npc=13036/gordok-hound#comments

**Expected behaviour**: 
Skinnable creatures in dungeons/raids should be able to drop multiple knothide leathers, according to the above mentioned sources. More specifically creatures that I believe should have this feature are: Amani Bear, Amani Lynx, Underbat, Sable Jaguar, Darkwater Crocolisk, Fen Ray, Shattered Hand Warhound, Rabid Warhound as well as all skinnable bosses.

**Comment by Wolffenstein** [comment]
Fixed in rev 3387.
