### ISSUE TITLE
[Raid][SWP] M'uru Bug - Enslaved 'Void Spawns' 

### ISSUE THREAD

**Issue by Tweet1337** [Atlantiss/NetherwingBugtracker#6938]
**Description:** Enslaved Void Spawns don't use their special ability "Shadow Bolt Volley" automatically, altough autocast is activated.

**Current behaviour:** When you enslave a Void Spawn (as warlock) it's only possible to use the pet's special ability by manually activating it. Activated autocast of the spell has no effect.

**Expected behaviour:** The pet should use its spell automatically if autocast is activated.

Void Spawn: https://tbcdb.com/?npc=25824
Spell: https://tbcdb.com/?spell=46082

**Server Revision:** 3367

**Comment by Godmatik** [comment]
Enslaving void spawns was disabled on previous server and I assume it will be the same when Sunwell is released later this year - so issue can be closed.
