### ISSUE TITLE
[warlock][spell] curse of doom - chance to summon doomguard

### ISSUE THREAD

**Issue by duzyizly** [Atlantiss/NetherwingBugtracker#6939]
**Description**: 
Not sure if badluck but curse's of doom chance to summon a doomguard seems very low % or no chance at all.
Killed exact 80 mobs - not a single proc.
Tested with rank 1 curse of doom on random mobs at barrens/hellfire peninsula.

**Expected behaviour**: 
https://classic.wowhead.com/spell=603/curse-of-doom#comments
https://wow.gamepedia.com/Doom
I'm almost sure it should be close to 5% or more.

**Server Revision**: 
3367

**Comment by duzyizly** [comment]
0/160 so far : (

**Comment by duzyizly** [comment]
if someone else could test it please with rank 1 and rank 2...

**Comment by BamboozleNW** [comment]
Currently tested about 40 mobs to 0 dooms. % is currently like 6.5% i'm guessing bad RNG. But still looking into this.

**Comment by devo6969** [comment]
Tried 102 mobs, no Doomguard

**Comment by ChekistNSK** [comment]
Yesterday, I and another warlock tried to call Doomguard by attacking by Curse of Doom animals in Durotar. However, after about 80 attempts, it was never summoned. We assumed that the mechanics of the game are such that you need to kill creatures that would give you experience. I killed about 20 more wolves in Terrokar Forest, and he killed about the same number in Netherstorm. No Doomguard has been summoned. Tell me, have you changed the mechanics of this spell or what is the percentage?

**Comment by Wolffenstein** [comment]
Fixed in rev 3690.
