### ISSUE TITLE
[Quest][Warsong Supplies] Warsong oil doesn't spawn!

### ISSUE THREAD

**Issue by navarro0527** [Atlantiss/NetherwingBugtracker#6940]
![WoWScrnShot_050920_215430](https://user-images.githubusercontent.com/65101027/81489866-7bc08c00-9240-11ea-97bf-b3906badd1e7.jpg)

Warsong oil item doesn't spawn in its site. I can't find it anywhere. Please, help!

**Comment by Tereneckla** [comment]
![image](https://user-images.githubusercontent.com/50233983/81494931-ce379200-92ac-11ea-944a-bb7e7c76eecb.png)
![image](https://user-images.githubusercontent.com/50233983/81494934-d1cb1900-92ac-11ea-81e6-ae7c8d1ec669.png)

Ran there, instantly found 2
