### ISSUE TITLE
[NPC][Hunter] Tameable beast Razzashi Serpent can not be tought any abilities, disappears when Stabled, and more.

### ISSUE THREAD

**Issue by worugru** [Atlantiss/NetherwingBugtracker#6941]
**Description**: 
The beast named "Razzashi Serpent" from Zul'Gurub dungeon, which can be tamed by hunters as pet, does not behave (and kind of basicly doesnt count) as a normal hunter pet. 

**Current behaviour**:
Some of the problems:

Pet can not be trained any ability. This include general abilities like Growl, or Nature Resistence spell.

It gives the Error that "The ability is not available to your pet" for any trainable skill (Growl, etc..)

SS: https://i.ibb.co/86z9xdt/2.png

At Pet profile ui, his level and type is not shown, but is shown simply as "Level level race class"

SS: https://i.ibb.co/rdpjV8R/1.png

The ability of the pet, which is "Poison Spit" does not damage as it should. At base, it should hit 120 (in total, as 4x ticks) , and should scale upward to 200+. But it hits about 96.

SS: https://i.ibb.co/vwQnsrg/3.png

When put on stables, the pet is not shown, and the slot is shown as empty (as pet is lost). Yet when any other pet is put at "empty" slot, the Snake reappears.

Video of it : https://streamable.com/n3wsdb

Info about pet: https://web.archive.org/web/20080527105045/http://petopia.brashendeavors.net/html/mobs/mob_razzashiserpent.php

**Expected behaviour**: 

Should be trained and behave like any hunter pet.

**Server Revision**: 3367

**Comment by Tereneckla** [comment]
https://web.archive.org/web/20080313113741/http://thottbot.com/s35392
96 damage over 8 seconds (24 per tick is correct) as baseline and it also does not scale
https://wowwiki.fandom.com/wiki/Poison_Spit?oldid=1464540

**Comment by worugru** [comment]
> 
> 
> https://web.archive.org/web/20080313113741/http://thottbot.com/s35392
> 96 damage over 8 seconds (24 per tick is correct) as baseline and it also does not scale
> https://wowwiki.fandom.com/wiki/Poison_Spit?oldid=1464540

Petopia states 120 from the 27th of may 2008 snapshot:

https://web.archive.org/web/20080527102302/http://petopia.brashendeavors.net/html/skills/skills_poisonspit.php

**Comment by Tereneckla** [comment]
Was also not able to recreate any of the issues you had with the pet. 
Maybe it was cause by one of your addons.
Clearing cache can also solve various random issues.

**Comment by worugru** [comment]
> 
> 
> Was also not able to recreate any of the issues you had with the pet.
> Maybe it was cause by one of your addons.
> Clearing cache can also solve various random issues.

Did you tame that exact mob from zulgurup, or just a random snake?

**Comment by Tereneckla** [comment]
Tamed a Razzashi Serpent obviously.

**Comment by worugru** [comment]
clearing the cache seems to fix it. I cant really say if that was it (as i cleared cache in the morning but changed the pet at the evening) certainly, but can be. Thanks for help.
