### ISSUE TITLE
[Percentage BUG]Locked percentage hp on NPC and mobs

### ISSUE THREAD

**Issue by badhacker2** [Atlantiss/NetherwingBugtracker#6943]
Description:
Percentage hp is always forced enabled on NPC and mobs, even if "Display Percentages" is not checked. Tried to change the client but still the same result.
![Wow 2020-05-11 05-49-39-520](https://user-images.githubusercontent.com/65145341/81520333-aa2b8d80-934c-11ea-9f8d-0b0ac4fb9238.jpg)
![Wow 2020-05-11 05-49-09-748](https://user-images.githubusercontent.com/65145341/81520342-adbf1480-934c-11ea-908b-cd29e67d0fdf.jpg)
![Wow 2020-05-11 05-49-22-576](https://user-images.githubusercontent.com/65145341/81520349-b0ba0500-934c-11ea-8597-785aff353a28.jpg)
![Wow 2020-05-11 05-49-30-607](https://user-images.githubusercontent.com/65145341/81520354-b4e62280-934c-11ea-83a5-eb31f3a6be47.jpg)

**Comment by Drayo** [comment]
The Option is only for Party members.

In TBC you need https://www.wowace.com/projects/project-14300/files/134391 to see mob health properly.

**Comment by Drayo** [comment]
You have to hit the mobs for it to calculate.

Regardless of that, the way it works now is not a bug.

**Comment by Wolffenstein** [comment]
Not a bug.
