### ISSUE TITLE
[Quest][Hellfire][Spell][Warrior][Whirlwind] Blast the Gateway

### ISSUE THREAD

**Issue by thure-CodeMeister** [Atlantiss/NetherwingBugtracker#6944]
I was doing Blast the gateway, and my flare kept disappearing. After it disappearing on me something like 7 times, I figured out the my whirlwind was hitting it and killing it. Don't know if this applies to all aoe, only know it happens with whirlwind

**Comment by Godmatik** [comment]
Can not reproduce - must have been fixed at some point.
