### ISSUE TITLE
[Raid][SWP] Eredar Twins flame seer on dead target

### ISSUE THREAD

**Issue by veekk** [Atlantiss/NetherwingBugtracker#6949]
**Description**:  after death flame seer became permanent, and it's preventing from bress (yes we tried to, guy just died again 'cause of this
![image](https://user-images.githubusercontent.com/12899687/81627424-d0adff00-9406-11ea-973c-8700721d1232.png)

**Current behaviour**: permanent pain

**Expected behaviour**: death will help with pain

**Server Revision**: 3371

**Comment by Wolffenstein** [comment]
Cannot reproduce.
