### ISSUE TITLE
[Spell] Resurrection Sickness

### ISSUE THREAD

**Issue by RzuF** [Atlantiss/NetherwingBugtracker#695]
**Description**: 

I used revive at graveyard (Dolanaar) after i died about 5 times. I accepted terms about Ressurection Sickness but after revived to life I did not recived Ressurection Sickness debuff.

Play Nelf Druid lvl 7 - nick: Rzuf

**Current behaviour**:

No Ressurection Sickness after revive at graveyard.

**Expected behaviour**: 

Ressurection Sickness after revive at graveyard.

**Server Revision**: 

Current at 26.09.2018 21:27

**Comment by Dpthx** [comment]
you don't recive the Ressurection Sicknes debuff if you're lower than level 10

**Comment by Firroth** [comment]
Yup, if you're lower than 10 you don't get it, after 10 each lvl you get 1min, so on lvl 20 you have full ress sickness with 10min on it.

Invalid report, so you can close it.
