### ISSUE TITLE
[Spell][Warlock] Ritual of doom

### ISSUE THREAD

**Issue by uzlik11** [Atlantiss/NetherwingBugtracker#6950]
**Description**:  https://tbcdb.com/?spell=18540

**Current behaviour**: Ritual of doom is OK, but after enslave demon it will disapper in few sec without any reason. 

**Expected behaviour**:  I think, that problem is just with doom, because enslave demon is working good on another demons. 

Thanks.

**Comment by lyubomeer** [comment]
Btw, it always sacrifices the last person who clicked on the stone. Should be random.

**Comment by Godmatik** [comment]
Duplicate
https://github.com/Atlantiss/NetherwingBugtracker/issues/8737
