### ISSUE TITLE
[Halaa] Horde and Alliance guards present and also nowhere to be found.

### ISSUE THREAD

**Issue by Tereneckla** [Atlantiss/NetherwingBugtracker#6951]
[//]: # (Enclose links to things related to the bug using http://wowhead.com or any other TBC database.)
[//]: # (You can use screenshot ingame to visual the issue.)
[//]: # (Write your tickets according to the format:)
[//]: # ([Quest][Azuremyst Isle] Red Snapper - Very Tasty!)
[//]: # ([NPC] Magistrix Erona)
[//]: # ([Spell][Mage] Fireball)
[//]: # ([Npc][Drop] Ghostclaw Lynx)
[//]: # ([Web] Armory doesnt work)
[//]: # (To find server revision type `.server info` command in the game chat.)

**Description**: 
![image](https://user-images.githubusercontent.com/50233983/81704401-06d29980-946e-11ea-8e9e-92d00f75d289.png)

**Current behaviour**:
27/15 Guards remaining.
Horde and Alliance guards present with alliance controlling.
Only 5 guards are physically in Halaa, 3 Alliance and 2 Horde. Can't find more.

**Expected behaviour**: 
Counter showing the actual number of guards left.
Only guards of the controlling faction present.

**Server Revision**: 3371

**Comment by Wolffenstein** [comment]
Will be fixed after update.
