### ISSUE TITLE
Figurine - Khorium Boar

### ISSUE THREAD

**Issue by Dirtybird93** [Atlantiss/NetherwingBugtracker#6952]
[//]: # (Enclose links to things related to the bug using http://wowhead.com or any other TBC database.)
[//]: # (You can use screenshot ingame to visual the issue.)
[//]: # (Write your tickets according to the format:)
[//]: # ([Quest][Azuremyst Isle] Red Snapper - Very Tasty!)
[//]: # ([NPC] Magistrix Erona)
[//]: # ([Spell][Mage] Fireball)
[//]: # ([Npc][Drop] Ghostclaw Lynx)
[//]: # ([Web] Armory doesnt work)
[//]: # (To find server revision type `.server info` command in the game chat.)

**Description**:  The item Figurine - Khorium Boar (https://tbc-twinhead.twinstar.cz/?item=35694) seems to be bugged at the moment. The summoned boar is level 1, has an incredibly large aggro radius (likely due to being level 1) and cannot hit anything in combat (because it's level 1).

**Current behaviour**: The summoned boar is level 1, engages in combat with hostile NPCs at a huge range, and cannot hit anything (all likely due to it's level.)

**Expected behaviour**: The summoned boar should be the same level as the player, engage in combat at the same aggro radius as the player, and be able to assist in combat meaningfully like any other summoned guardian. 

**Server Revision**: 3371

**Comment by Evolvee** [comment]
next rev
