### ISSUE TITLE
[Item] Bloodberry Elixir only usable in SWP

### ISSUE THREAD

**Issue by hederob** [Atlantiss/NetherwingBugtracker#6953]
![bloodberry comments](https://user-images.githubusercontent.com/25690905/81730676-8010c300-9453-11ea-9b6b-f77e34f5cacf.png)

**Description**: Bloodberry Elixir not working as intended. It's not able to be used unless you're in Sunwell Plateau. It should affect players in all of Isle of Quel'Danas, Magister's Terrace, and Sunwell Plateau.

**Current behaviour**: You can only use it in Sunwell Plateau and no where else. It disappears when you zone out of Sunwell Plateau.

**Expected behaviour**: Should be able to be used in all of Isle of Quel'Danas, Magister's Terrace, and Sunwell Plateau. Buff should not disappear when you zone out of these areas but stats should temporarily be lost until you go into active zones again. This is should be similar to the Shattrath flasks and Blade's Edge flasks. It should also persist through death.

**Server Revision**: 3371

**Comment by Wolffenstein** [comment]
Fixed in rev 3375.
