### ISSUE TITLE
[Shadow Labs][Boss] Vorpil fight pulls two Cabal Executioners from Murmur's room.

### ISSUE THREAD

**Issue by Syfte-oss** [Atlantiss/NetherwingBugtracker#6954]
[//]: # (Enclose links to things related to the bug using http://wowhead.com or any other TBC database.)
[//]: # (You can use screenshot ingame to visual the issue.)
[//]: # (Write your tickets according to the format:)
[//]: # ([Quest][Azuremyst Isle] Red Snapper - Very Tasty!)
[//]: # ([NPC] Magistrix Erona)
[//]: # ([Spell][Mage] Fireball)
[//]: # ([Npc][Drop] Ghostclaw Lynx)
[//]: # ([Web] Armory doesnt work)
[//]: # (To find server revision type `.server info` command in the game chat.)

**Description**:  During our first two attempts at the Vorpil fight two additional Cabal Executioners came running down the hallway from Murmur's room and joined him.  They did not appear on our third attempt.
On a side note when we beat Vorpil and ran up the hallway we found the door already open.  Maybe the fight is causing the door to open which in turn allows the Executioners to run back to us.

Possibly related to this issue:  https://github.com/Atlantiss/NetherwingBugtracker/issues/6547

Screenshot from our second try:  https://i.imgur.com/IA2tHJv.jpg

**Current behaviour**:  Two Cabal Executioners sometimes join the Vorpil fight, running to it from Murmur's room.

**Expected behaviour**:  No adds other than the Void Travelers.

**Server Revision**:  3371

**Comment by veekk** [comment]
and also he's porting players into this corridor before murmur room, instead of he's starting "throne"

**Comment by Syfte-oss** [comment]
That was reported in this closed ticket.
https://github.com/Atlantiss/NetherwingBugtracker/issues/5886

I guess the fix has come undone.

**Comment by Wolffenstein** [comment]
Fixed in rev 3388.
