### ISSUE TITLE
[PVP][Quest] Call to Arms (daily pvp)

### ISSUE THREAD

**Issue by bekonja** [Atlantiss/NetherwingBugtracker#6955]
[//]: # (Enclose links to things related to the bug using http://wowhead.com or any other TBC database.)
[//]: # (You can use screenshot ingame to visual the issue.)
[//]: # (Write your tickets according to the format:)
[//]: # ([Quest][Azuremyst Isle] Red Snapper - Very Tasty!)
[//]: # ([NPC] Magistrix Erona)
[//]: # ([Spell][Mage] Fireball)
[//]: # ([Npc][Drop] Ghostclaw Lynx)
[//]: # ([Web] Armory doesnt work)
[//]: # (To find server revision type `.server info` command in the game chat.)

**Description**: 
Daily pvp quests that you can pick up from your factions' BG NPCs
I guess you can find their IDs there: https://tbcdb.com/?search=call+to+arms#quests

**Current behaviour**:
I can pick one up being level 12 and it gives me 4g+ as a reward. Obv cant test it properly since no1 plays BGs at lv12.

**Expected behaviour**: 
Would be an issue for F R E S H, people would q WSG asap to abuse easy 4g.

**Server Revision**:

**Comment by Tereneckla** [comment]
![image](https://user-images.githubusercontent.com/50233983/81801172-4ce23880-9514-11ea-8354-e0b5d0a216dc.png)

Gold and XP doesn't scale with level.

**Comment by Wolffenstein** [comment]
Fixed in rev 3408.
