### ISSUE TITLE
Lady vashj bug

### ISSUE THREAD

**Issue by Flamelol** [Atlantiss/NetherwingBugtracker#6956]
**Current behaviour**:
Lady vashj spawns naga&striders b4 expected time. When we are killing naga or stider and its like 20-30 sec to another one we are opening last generator to p3 and suddenly another mobs spawns again. We tried even to leave last naga alive >> open last generator on p2 >> and plan was to kill naga and vashj but again another stider respawned even if its like 30 sec to another strider
**Expected behaviour**: 
Nagas and striders should spawn with expected time. https://wowwiki.fandom.com/wiki/Lady_Vashj_(tactics)
Naga every 45s, Strider every 1min
**Server Revision**:

**Comment by Tereneckla** [comment]
Nagas spawned every 40 seconds after the first one.
Rest is exactly on my DBM timer.

**Comment by Flamelol** [comment]
Ok but when we are opening 4th generator and everything is killed naga should not spawn if its like 20 sec to another one.

**Comment by Tereneckla** [comment]
40 seconds instead of 45 means.
1st on time
2nd 5 seconds early
3rd 10 seconds early
4th 15 seconds early
5th 20 seconds early <- You are there at 4th generator
