### ISSUE TITLE
[NPC] npc=12246 Super-Seller 680 is missing few recipes

### ISSUE THREAD

**Issue by duzyizly** [Atlantiss/NetherwingBugtracker#6957]
**Description**: 
Super-Seller 680 is an NPC who spawns at the end of scripted patrol in Desolace.
Due to old database comments he should contain more recipes in his stock.
Those recipes should also always refresh once he spawns (one recipe of all kind per spawn).

**Current behaviour**:
He is missing those 6 recipes:
https://tbcdb.com/?item=13310
https://tbcdb.com/?item=7561
https://tbcdb.com/?item=13308
https://tbcdb.com/?item=7087
https://tbcdb.com/?item=6401
https://tbcdb.com/?item=14630

**links to comments**
https://classic.wowhead.com/npc=12246/super-seller-680#comments

_Each robot sells Limit 1 supply recipe.
But if you buy out all the recipe of a single type & want more, wait for it to go to other end then come back.  When it respawns again all its items will be restocked & you can buy more of the same recipe again (still Limit 1 though)._

_All of the recipes are limited stock - one copy per item, per journey._

**Here are the ss of his inventory**
![WoWScrnShot_051320_141631](https://user-images.githubusercontent.com/43931626/81811954-b9196800-9525-11ea-963d-7417416270b7.jpg)
![WoWScrnShot_051320_141633](https://user-images.githubusercontent.com/43931626/81811959-ba4a9500-9525-11ea-8c6f-cb6b9b42d6e7.jpg)
![WoWScrnShot_051320_141634](https://user-images.githubusercontent.com/43931626/81811964-bae32b80-9525-11ea-9a32-361a6720a4f5.jpg)
![WoWScrnShot_051320_141636](https://user-images.githubusercontent.com/43931626/81811965-bb7bc200-9525-11ea-95b0-06a3edc7b9cc.jpg)

**Server Revision**: 
3371

The 2nd robot NPC https://tbcdb.com/?npc=12245 (Vendor-Tron 1000) is fine.

**Comment by Evolvee** [comment]
next rev
