### ISSUE TITLE
[Raid][SWP][Black Temple] Disorient tanking

### ISSUE THREAD

**Issue by veekk** [Atlantiss/NetherwingBugtracker#6958]
**Description**:  on encounters like Eredar Twins and Gurtogg Bloodboil, after disorient (e.g. confounding blow) boss must switch target to 2nd tank, but on both those bosses they're stay hitting 1st disoriented tank

**Current behaviour**: disorient crush crush crush death

**Expected behaviour**: disorient switch happiness rainbow

**Server Revision**: 3371

**Comment by Tereneckla** [comment]
Gurtogg Bloodboil does not have a disorient.

**Comment by Tereneckla** [comment]
Duplicate of #6797

**Comment by veekk** [comment]
@Tereneckla it's different issue and another boss were mentioned, so that's not really duplicate as u marked it
