### ISSUE TITLE
[NPC] Emissary of Hate, fire damage is too high.

### ISSUE THREAD

**Issue by Red86** [Atlantiss/NetherwingBugtracker#6959]
The emissary of hate NPC (ID 25003) that you need to kill for the quest "The battle must go on" on the isle of quel'danas, does way too high fire damage.

**Description**: 

While the melee damage seems appropriate for the creature location and level, the damage of his fire trail skill seems way too high

**Current behaviour**:

Right now the fire skill he uses seems to tick multiple times a second for 2k damage each time. to put that into perspective that's comparable to the fire damage an elemental tank receives in the p2 of illidan. 

**Expected behaviour**: 

The damage and the frequency of the ticks should be scaled down to match the creature level and location.

**Server Revision**: 

3371

**Comment by Wolffenstein** [comment]
Fixed in rev 3386.
