### ISSUE TITLE
[NPC] Arcane Devourer or Wand? Behavior

### ISSUE THREAD

**Issue by nycheia** [Atlantiss/NetherwingBugtracker#696]
http://prntscr.com/kz3nra @ Combatlog
https://prnt.sc/kz3j3v

**Description**: 
Arcane Elemental in Ghostlands currently not arcane resistant. Or wand currently not registering correctly as arcane. It does however say it hits arcane dmg in the combatlog.

**Current behaviour**:
My arcane wand is currently hitting the arcane devourers for as much arcane damage as it would on any other mob.

**Expected behaviour**: 
Its supposed to be immune to this damage.

**Server Revision**: 
2060

**Comment by duzyizly** [comment]
this npc is immune to arcane spells (like for example arcane missles/explosion) but takes full damage from arcane wands (tested with greater magic wand). PTR rev 3392?

![WoWScrnShot_062020_114542](https://user-images.githubusercontent.com/43931626/85198817-b1e73600-b2eb-11ea-818e-7a474ce439ef.jpg)
![WoWScrnShot_062020_114340](https://user-images.githubusercontent.com/43931626/85198811-af84dc00-b2eb-11ea-8b68-e55ec2700dd1.jpg)
![WoWScrnShot_062020_114409](https://user-images.githubusercontent.com/43931626/85198812-b0b60900-b2eb-11ea-9573-3f728e26373c.jpg)
![WoWScrnShot_062020_114452](https://user-images.githubusercontent.com/43931626/85198814-b14e9f80-b2eb-11ea-81ec-0620720c80f1.jpg)
![WoWScrnShot_062020_114500](https://user-images.githubusercontent.com/43931626/85198816-b1e73600-b2eb-11ea-9276-bf0ce3e95b93.jpg)

**Comment by Tereneckla** [comment]
Put in bigger topic
