### ISSUE TITLE
[NPC] Shaani's shop has the wrong icon.

### ISSUE THREAD

**Issue by Tereneckla** [Atlantiss/NetherwingBugtracker#6960]
[//]: # (Enclose links to things related to the bug using http://wowhead.com or any other TBC database.)
[//]: # (You can use screenshot ingame to visual the issue.)
[//]: # (Write your tickets according to the format:)
[//]: # ([Quest][Azuremyst Isle] Red Snapper - Very Tasty!)
[//]: # ([NPC] Magistrix Erona)
[//]: # ([Spell][Mage] Fireball)
[//]: # ([Npc][Drop] Ghostclaw Lynx)
[//]: # ([Web] Armory doesnt work)
[//]: # (To find server revision type `.server info` command in the game chat.)

**Description**: 
![image](https://user-images.githubusercontent.com/50233983/81922483-78305a80-95dc-11ea-9b56-60b83bb3b818.png)

**Current behaviour**:
Dialogue Icon
**Expected behaviour**: 
Shop Icon
**Server Revision**: 3371

**Comment by Evolvee** [comment]
if it was the shop icon, client would go straight into the vendor and skip the gossip text entirely, making it absolutely useless
the text is very relevant to isle phases so i kept it in
