### ISSUE TITLE
Dragonmaw Transporter Bug

### ISSUE THREAD

**Issue by Tollkirsch** [Atlantiss/NetherwingBugtracker#6962]
Zone= Shadowmoonvalley / Netherwing Ledge
Quest= The Not-So-Friendly Skies...
NPC= Dragonmaw Transporter

After Starting the Fight with Dragonmaw Tranporter, the Enemy will not Land (never) on the Ground. Makes it impossible to kill for Meeleclasses.

Current Behavior= Dragonmaw Transporter never Landing on the Ground while beeing Attacked**:

Expected behaviour= Dragonmaw Transporter Fly on the Ground,  Meeleclass can hit them in Meelerange**:

**Comment by Tereneckla** [comment]
https://www.wowhead.com/npc=23188/dragonmaw-transporter#comments

That's how they are
