### ISSUE TITLE
[Item] Booldberry Elixir (SWP exclusive buff)

### ISSUE THREAD

**Issue by bekonja** [Atlantiss/NetherwingBugtracker#6965]
[//]: # (Enclose links to things related to the bug using http://wowhead.com or any other TBC database.)
[//]: # (You can use screenshot ingame to visual the issue.)
[//]: # (Write your tickets according to the format:)
[//]: # ([Quest][Azuremyst Isle] Red Snapper - Very Tasty!)
[//]: # ([NPC] Magistrix Erona)
[//]: # ([Spell][Mage] Fireball)
[//]: # ([Npc][Drop] Ghostclaw Lynx)
[//]: # ([Web] Armory doesnt work)
[//]: # (To find server revision type `.server info` command in the game chat.)

**Description**: 
https://tbcdb.com/?item=34537

**Current behaviour**:
If you use it as you enter SWP and override it with another flask or elixir you still gonna keep +15 stats it gives.

**Expected behaviour**: 
Battle elixir, any other flask or elixir should override its effects.

**Server Revision**:

**Comment by Tereneckla** [comment]
The hidden buff 45374 stays even after you removed the visible buff 45373.

**Comment by Wolffenstein** [comment]
Fixed.
