### ISSUE TITLE
Item not appearing in bags

### ISSUE THREAD

**Issue by Gliga023** [Atlantiss/NetherwingBugtracker#6966]
[//]: # (Enclose links to things related to the bug using http://wowhead.com or any other TBC database.)
[//]: # (You can use screenshot ingame to visual the issue.)
[//]: # (Write your tickets according to the format:)
[//]: # ([Quest][Azuremyst Isle] Red Snapper - Very Tasty!)
[//]: # ([NPC] Magistrix Erona)
[//]: # ([Spell][Mage] Fireball)
[//]: # ([Npc][Drop] Ghostclaw Lynx)
[//]: # ([Web] Armory doesnt work)
[//]: # (To find server revision type `.server info` command in the game chat.)

**Description**: 
Hello. i have problem. When ever i make (instant potion VII) it does not apear in my bags.
Other problem i have that my marks of AV disapeared from inventory, i had around 50 of them.
Can you please help me?
Deleting cache folder and restarting client did not help.
I posted screenshots of making potion that does not apear in inventory
**Current behaviour**:
![WoWScrnShot_051520_114137](https://user-images.githubusercontent.com/65396000/82037075-f571d300-96a1-11ea-8523-8d8751e43ad5.jpg)
![WoWScrnShot_051520_114141](https://user-images.githubusercontent.com/65396000/82037143-0589b280-96a2-11ea-91ab-d192fd9786e5.jpg)

**Expected behaviour**: 
problem resolve
**Server Revision**:

**Comment by Tereneckla** [comment]
Click "Show Bags"
Make sure that every bag you have is shown.
