### ISSUE TITLE
[Raid][Black Temple] Prismatic auras

### ISSUE THREAD

**Issue by veekk** [Atlantiss/NetherwingBugtracker#6968]
**Description**:  damage reduction working fine, except #6963, but damage increase damage doesn't work

**Current behaviour**: reduction works, increase doesn't work

**Expected behaviour**:  shadow stacks provide -shadow dmg, holy stacks provide +shadow dmg

**Server Revision**: 3371

**Comment by Godmatik** [comment]
Seems intended - the original prismatic aura (before Blizz nerfed it) had it only apply damage reduction and not any sort of damage increase. 

I am guessing the tooltip just incorrectly is showing the 'nerfed' version details which indicates that you should get a damage increase of the opposite school.

![PrisAura](https://github.com/Atlantiss/NetherwingBugtracker/assets/37913400/19c28a70-39fc-4af3-a5bf-c200c13041d7)
