### ISSUE TITLE
[Quest] The Annals of Darrowshire

### ISSUE THREAD

**Issue by bekonja** [Atlantiss/NetherwingBugtracker#6969]
[//]: # (Enclose links to things related to the bug using http://wowhead.com or any other TBC database.)
[//]: # (You can use screenshot ingame to visual the issue.)
[//]: # (Write your tickets according to the format:)
[//]: # ([Quest][Azuremyst Isle] Red Snapper - Very Tasty!)
[//]: # ([NPC] Magistrix Erona)
[//]: # ([Spell][Mage] Fireball)
[//]: # ([Npc][Drop] Ghostclaw Lynx)
[//]: # ([Web] Armory doesnt work)
[//]: # (To find server revision type `.server info` command in the game chat.)

**Description**: 
https://classic.wowhead.com/quest=5154/the-annals-of-darrowshire#comments:0

**Current behaviour**:
1. Mob spawns on looting wrong books are doubled, they spawn 2 or 4 Decrepit Guardians instead of 1-2
2. "Right" book spawnrate either atrociously low or it doesnt spawn at all on this server rev. I gave up after 40 attemtps, shouldnt take more than 10 on avg. 

Neither of issues were present couple of months ago.

Edit1: spawned 2 after 63 attempts so atleast quest is working. Not sure what is wrong with spawnrates tho, might be that some spots not eligible to spawn right books or rate is somehow lower than it should be.

**Expected behaviour**: 

**Server Revision**: 
3371

**Comment by Evolvee** [comment]
next rev
