### ISSUE TITLE
[Spell] Mark of the Wild/Demon Skin

### ISSUE THREAD

**Issue by totaemoeggerli** [Atlantiss/NetherwingBugtracker#697]
[//]: # (Enclose links to things related to the bug using http://wowhead.com or any other TBC database.)
[//]: # (You can use screenshot ingame to visual the issue.)
[//]: # (Write your tickets according to the format:)
[//]: # ([Quest][Azuremyst Isle] Red Snapper - Very Tasty!)
[//]: # ([NPC] Magistrix Erona)
[//]: # ([Spell][Mage] Fireball)
[//]: # ([Npc][Drop] Ghostclaw Lynx)
[//]: # ([Web] Armory doesnt work)

**Description**: 
Can't buff player with MotW if they have Demon Skin active. Error message "a more powerful spell is already active" appears. Buffs stack if Demon Skin is buffed after MotW.

**Current behaviour**:
Can't buff player with MotW if Demon Skin is active (someone should try Demon Armor too btw)

**Expected behaviour**: 
MotW and Demon Skin should stack.

**Server Revision**: 
2060

**Comment by totaemoeggerli** [comment]
Duplicate
issue has been reported here https://github.com/Atlantiss/NetherwingBugtracker/issues/390

**Comment by Wolffenstein** [comment]
Fixed in rev 2067.
