### ISSUE TITLE
[core][spell] SPELL_EFFECT_APPLY_AREA_AURA_PARTY

### ISSUE THREAD

**Issue by Evolvee** [Atlantiss/NetherwingBugtracker#6973]
Spell effects with SPELL_EFFECT_APPLY_AREA_AURA_PARTY should be applied even between creatures of the same faction (devotion aura).

**Comment by Wolffenstein** [comment]
It does that already (AllFriendlyCreaturesInGrid check). Give me exact creature/spell so I can test if it doesn't work.

**Comment by Wolffenstein** [comment]
Found the issue, fixed in rev 3452.
