### ISSUE TITLE
[core][dbc spells] Certain summoned NPCs inherit invoker dmg modifiers instead of their own, making them almost pointless

### ISSUE THREAD

**Issue by Evolvee** [Atlantiss/NetherwingBugtracker#6975]
summon enraged mounts 29110
summon enraged wyvern 14307
summon enraged gryphon 14313

summon enraged felbat 14252
summon enraged hippogryph 14329
hackfix 143070

e.g. aggro NPC 352

**Comment by Wolffenstein** [comment]
It's working fine.
Gryphon:
![obraz](https://user-images.githubusercontent.com/1576644/85046779-2a85af80-b191-11ea-83d6-db8432f02810.png)

Flight Master:
![obraz](https://user-images.githubusercontent.com/1576644/85046791-31acbd80-b191-11ea-8e5a-0acb54e6bfe6.png)
