### ISSUE TITLE
[core][dbc spell][pet] [Flight Masters] Summoned guards often miss 1 spawn due to core issue

### ISSUE THREAD

**Issue by Evolvee** [Atlantiss/NetherwingBugtracker#6976]
if i had to guess, core probably thinks the invoker already has 1 pet active and therefore blocks summoning another one

all flight masters must always summon 2 spawns, never 1

Also, currently its displayed as "PET", but it should be "GUARDIAN".

summon enraged mounts 29110
summon enraged wyvern 14307
summon enraged gryphon 14313

summon enraged felbat 14252
summon enraged hippogryph 14329
hackfix 143070

**Comment by Godmatik** [comment]
This still occurs, I aggroed an enemy flight master in Moonglade, only one wyvern spawned

**Comment by Godmatik** [comment]
Was fixed back in Rev 3855

Flight masters now properly summon 2 spawns when attacked.
