### ISSUE TITLE
[Mechanic] Summon NPCs via interaction with object

### ISSUE THREAD

**Issue by bekonja** [Atlantiss/NetherwingBugtracker#6982]
[//]: # (Enclose links to things related to the bug using http://wowhead.com or any other TBC database.)
[//]: # (You can use screenshot ingame to visual the issue.)
[//]: # (Write your tickets according to the format:)
[//]: # ([Quest][Azuremyst Isle] Red Snapper - Very Tasty!)
[//]: # ([NPC] Magistrix Erona)
[//]: # ([Spell][Mage] Fireball)
[//]: # ([Npc][Drop] Ghostclaw Lynx)
[//]: # ([Web] Armory doesnt work)
[//]: # (To find server revision type `.server info` command in the game chat.)

**Description**: 
https://github.com/Atlantiss/NetherwingBugtracker/issues/6969
I mentioned in this bugreport that interacting with quest object summons double amount of NPCs. 
https://tbcdb.com/?quest=10861
https://tbcdb.com/?quest=9709
There are 2 more quests with same behaviour

**Current behaviour**:
Seems like this problem might be global. Each time script calls to summon NPC after interaction with object it executes twice.

**Expected behaviour**: 

**Server Revision**: 
3371

**Comment by Evolvee** [comment]
its because fucking gameobjects traps that didnt work for 4 years suddenly started to work, so there is my script + the trap effect on top of my script

**Comment by Evolvee** [comment]
i fixed the above but i will keep this topic open for now until all the gobs are "fixed"

**Comment by Wolffenstein** [comment]
Open a new ticket when other similar problems occur.
