### ISSUE TITLE
[Core][Dungeons][Raid] Dungeons/Raid respawn monsters too fast!

### ISSUE THREAD

**Issue by MisaHack** [Atlantiss/NetherwingBugtracker#6983]
[//]: # (Enclose links to things related to the bug using http://wowhead.com or any other TBC database.)
[//]: # (You can use screenshot ingame to visual the issue.)
[//]: # (Write your tickets according to the format:)
[//]: # ([Quest][Azuremyst Isle] Red Snapper - Very Tasty!)
[//]: # ([NPC] Magistrix Erona)
[//]: # ([Spell][Mage] Fireball)
[//]: # ([Npc][Drop] Ghostclaw Lynx)
[//]: # ([Web] Armory doesnt work)
[//]: # (To find server revision type `.server info` command in the game chat.)

**Description**: 
@ Game Masters - is anyone of developers aware that longer dungeons respawn enemies too fast?
I do not understand why dungeons respawn enemies in the first place if we cleared portions of dungeons.
That said Boss Monsters never respawn if we did not explicitely restarted Instance.
In my opinion enemies could only respawn if Dungeon Leader restart Dungeon/Raid.
This issue is very, very iritating and annoying, also very not fun, and it takes too much time to clear single dungeon/Raid from start to the end.
If our group, for example, dies by the end of the dungeon, we must clear whole first section of dungeon (because of respawned enemies) and it can be more that first section!
Dungeons/Raid we encountered that this issue is obvious are longer dungeons such as: "Blackrock Depths", "Lower Blackrock Spire", "Upper Blackrock Spire"

**Current behaviour**:
Monsters respawn in dungeons too fast! 

**Expected behaviour**: 
Monsters should respawn ONLY if Dungeon Leader explicitely restart dungeon/Raid.

**Server Revision**: 3371

**Comment by Drayo** [comment]
> In my opinion enemies could only respawn if Dungeon Leader restart Dungeon/Raid.

That is only the case for trash in raid instances that are bound to a specific boss.

Trashmobs in 5 man Dungeons can just respawn normally in most cases. This is pretty much common knowledge, but I added a source anyway. 

I just randomly tested two and just like the wiki says, the respawn is set to 2 hours on NW.  BRD in OPs example was always notorious for it's respawns.

![image](https://user-images.githubusercontent.com/23145811/87232620-950cc280-c3c0-11ea-822b-09a1d8e5e6a3.png)


https://wowwiki.fandom.com/wiki/Spawn?oldid=1424094

>      Instance trash mobs: 

> In instances, mobs usually are on a 2 hour respawn timer. There may be exceptions though, sometimes the instance designer use short respawn timers to create an extra challenge (e.g. Ancient Core Hounds). In raid instances, trash mobs are usually "bound" to a boss, and after that boss is killed, the trash does not spawn any more. 

>      Instance boss mobs: 

> Instance bosses do not have a respawn timer at all. They only return on instance reset. 

Can be closed.
