### ISSUE TITLE
Bug - it doesn't work the Scryers' proc for Shattered Sun Pendant of Restoration [neck] with ticks of Heal over time powers [Lifebloom]

### ISSUE THREAD

**Issue by Ragnaarok** [Atlantiss/NetherwingBugtracker#6984]
[//]: https://wow.gamepedia.com/Shattered_Sun_Pendant_of_Restoration
[//]: # ([Spell][Druid] Lifebloom)
[//]: # the Scryers' proc for Shattered Sun Pendant of Restoration [neck] with ticks of Heal over time powers [Lifebloom] doesn't work

**Description**: It has been tested a lot of times about the Scryers' proc for [Shattered Sun Pendant of Restoration] with ticks of Heal over time powers [Lifebloom] and it was no proc at all with the HoT spell. But Mechanics of the proc says it must be. 

**Current behaviour**: The Scryers' proc for [Shattered Sun Pendant of Restoration] work just with such healing spells as [Regrowth] and [Swiftmend]

**Expected behaviour**: The Scryers proc will occur on ticks of Heal over time powers such as  [Renew] and  [Lifebloom].

[https://wow.gamepedia.com/Shattered_Sun_Pendant_of_Restoration](url)

**Server Revision**:

**Comment by Ragnaarok** [comment]
![image](https://user-images.githubusercontent.com/65601059/82321602-c4650b80-99dd-11ea-9d7b-151eef76b8b1.png)

**Comment by Wolffenstein** [comment]
Fixed in rev 3387.
