### ISSUE TITLE
BEM Flask stuck

### ISSUE THREAD

**Issue by TomaszPop** [Atlantiss/NetherwingBugtracker#6986]
[//]: # (You can use screenshot ingame to visual the issue.)
YT Link: https://youtu.be/-qa1pwifOrI
(its private type of film, so you have to have acces to this link to watch this)
[//]: # ([Quest][Azuremyst Isle] Red Snapper - Very Tasty!)
All kind of "Unstable flask of..." from BEM 

[//]: # (To find server revision type `.server info` command in the game chat.)
 .server info - few last sec of the movie

**Description**:

**Current behaviour**:
You can stack up all of the BEM flask, and mask it using other any kind of elixir as a last, and leave BEM area.
**Expected behaviour**: 
1. You can not stuck flasks
2. Flask are removed after leaving the BEM area.

**Server Revision**: 
3374
Branch: master, Hash: 64dfa08f606b

**Comment by TomaszPop** [comment]
BTW, simmilar bug is with Flask (15 all stats) from Isle.

**Comment by Wolffenstein** [comment]
Fixed in rev 3375.
