### ISSUE TITLE
[NPC] Ethereum Relay

### ISSUE THREAD

**Issue by bekonja** [Atlantiss/NetherwingBugtracker#6987]
[//]: # (Enclose links to things related to the bug using http://wowhead.com or any other TBC database.)
[//]: # (You can use screenshot ingame to visual the issue.)
[//]: # (Write your tickets according to the format:)
[//]: # ([Quest][Azuremyst Isle] Red Snapper - Very Tasty!)
[//]: # ([NPC] Magistrix Erona)
[//]: # ([Spell][Mage] Fireball)
[//]: # ([Npc][Drop] Ghostclaw Lynx)
[//]: # ([Web] Armory doesnt work)
[//]: # (To find server revision type `.server info` command in the game chat.)

**Description**: 
https://www.wowhead.com/npc=20619/ethereum-relay

**Current behaviour**:
8-9 spawns. Quest requires you to kill 15 of them meaning that you need to wait atleast 1 spawning cycle to complete it.

**Expected behaviour**: 
25 spawns according to wowhead. 

**Server Revision**:

**Comment by The14me** [comment]
Can be added 2-3 more spawn points, but that 25 u see on Wowhead is possible to spawn points. Not how many of them must be alive at same time.

**Comment by Godmatik** [comment]
Watched a classic video and the current amount looks correct to me.
