### ISSUE TITLE
[Spell][Hunter] Flare reveals targets on the bridge in "Blade Edge" arena even while it was placed on under it

### ISSUE THREAD

**Issue by 4egito** [Atlantiss/NetherwingBugtracker#6988]
[//]: # (Enclose links to things related to the bug using http://wowhead.com or any other TBC database.)
[//]: # (You can use screenshot ingame to visual the issue.)
[//]: # (Write your tickets according to the format:)
[//]: # ([Quest][Azuremyst Isle] Red Snapper - Very Tasty!)
[//]: # ([NPC] Magistrix Erona)
[//]: # ([Spell][Mage] Fireball)
[//]: # ([Npc][Drop] Ghostclaw Lynx)
[//]: # ([Web] Armory doesnt work)
[//]: # (To find server revision type `.server info` command in the game chat.)

**Description**: 
Flare reveals targets on the bridge in "Blade Edge" arena even while it was placed on under it
**Current behaviour**:
https://drive.google.com/open?id=1OqsoTyHHcwj89zKz76Qg_SFVKSiuyc9o
https://drive.google.com/open?id=1o9dXYKkul88i3pBKs_NAlVGnUgfBiV85
**Expected behaviour**: 

**Server Revision**: 
3374

**Comment by Wolffenstein** [comment]
Fixed in rev 3384.
