### ISSUE TITLE
[Spell] Summon sometimes doesent go through

### ISSUE THREAD

**Issue by dshgrove** [Atlantiss/NetherwingBugtracker#6989]
[//]: # (Enclose links to things related to the bug using http://wowhead.com or any other TBC database.)
[//]: # (You can use screenshot ingame to visual the issue.)
[//]: # (Write your tickets according to the format:)
[//]: # ([Quest][Azuremyst Isle] Red Snapper - Very Tasty!)
[//]: # ([NPC] Magistrix Erona)
[//]: # ([Spell][Mage] Fireball)
[//]: # ([Npc][Drop] Ghostclaw Lynx)
[//]: # ([Web] Armory doesnt work)
[//]: # (To find server revision type `.server info` command in the game chat.)

**Description**: 
Sometimes when accepting a summon you do not get teleported. 
[Video of this happening](https://streamable.com/p1d401)
_Although i have not done a lot of testing trying to reproduce this, there might be a pattern with a higher chance for the summon not to go through if you wait long before you accept it._ 

**Current behaviour**:
You accept the summon and nothing happens.

**Expected behaviour**: 
You accept the summon and get teleported to the location where you are getting summoned.

**Server Revision**: 
Current (i am not online right now, sorry)

**Comment by networm555** [comment]
its happens when you getting summoned more than once without accepting

**Comment by Wolffenstein** [comment]
Fixed in rev 3458.
