### ISSUE TITLE
Gray/white loot in loot window during group loot

### ISSUE THREAD

**Issue by nycheia** [Atlantiss/NetherwingBugtracker#699]
https://prnt.sc/kz3idk

**Description**: 
I am currently in a group, with group loot on. 
**Current behaviour**:
We are both able to see each others gray/white loot in the loot window (not quest items, that is correct), but we cant loot it. 
So if its his loot, i can see his loot, but not be able to loot it. And the other way around.
In the screenshot it shows that im the 'looter', but i guess thats for the next mob, since i couldnt loot that one mob, but my friend could.

**Expected behaviour**: 
Only copper/silver is supposed to show in the loot window, along with rollable items afaik. Except if you are using master loot

**Server Revision**: 
2060

**Comment by Teppic1** [comment]
This is still an issue, a lot of players have been encountering it since launch.

**Comment by sifiuocz** [comment]
This bug's life span is long overdue. Please fix it. In raids too many people check trash loot instead of actually raiding.

**Comment by Manaci** [comment]
Fixed with loot rework
