### ISSUE TITLE
Auchenai doomslayer - insane amount of npc's

### ISSUE THREAD

**Issue by Selphius** [Atlantiss/NetherwingBugtracker#6990]
**Current behaviour**:
Screen says it all.

![1](https://user-images.githubusercontent.com/13300602/82609800-83c3e880-9bbd-11ea-9fbb-c6297ad49e3a.png)

**Expected behaviour**: 
Less mobs overall, so it can be done by low lvls.

**Server Revision**: 
3374

**Comment by Evolvee** [comment]
most likely broken pooling - core

**Comment by Evolvee** [comment]
3377
