### ISSUE TITLE
[Quest][NPC] The Earthbinder

### ISSUE THREAD

**Issue by bekonja** [Atlantiss/NetherwingBugtracker#6992]
[//]: # (Enclose links to things related to the bug using http://wowhead.com or any other TBC database.)
[//]: # (You can use screenshot ingame to visual the issue.)
[//]: # (Write your tickets according to the format:)
[//]: # ([Quest][Azuremyst Isle] Red Snapper - Very Tasty!)
[//]: # ([NPC] Magistrix Erona)
[//]: # ([Spell][Mage] Fireball)
[//]: # ([Npc][Drop] Ghostclaw Lynx)
[//]: # ([Web] Armory doesnt work)
[//]: # (To find server revision type `.server info` command in the game chat.)

**Description**: 
https://tbcdb.com/?quest=10349
https://tbcdb.com/?npc=19294
Simple travel quest. Pick it up from one NPC and turn it to another one standing 10 yards away.

**Current behaviour**:
Unable to complete. Earthbinder Galandria Nightbreeze has no "golden question mark" above her head. It isnt working for anyone who tried to do it, not only for me.

I have no idea either NPC is glitching and reset would fix it or quest just isnt working after recent update, need futher testing on that. All i know is that quest was working just fine couple of days ago.

**Expected behaviour**: 

**Server Revision**: 
3375

**Comment by hederob** [comment]
This NPC might need to be reset,

**Comment by bekonja** [comment]
was an npc glitch, fixed

**Comment by sk6868** [comment]
This happened again 4:09AM Server time Karazhan server

**Comment by Godmatik** [comment]
I reset the NPC.
In future you can always open a ticket in-game
