### ISSUE TITLE
[Tempest Keep] A'lar - two Ember of A'lars spawn after each position change in Phase 1.

### ISSUE THREAD

**Issue by Syfte-oss** [Atlantiss/NetherwingBugtracker#6993]
**Description**:  During the fight A'lar moves from one platform to the next.  This position change is supposed to release a single Ember of A'lar.

**Current behaviour**: Two Embers of A'lar are released on every position change.

**Expected behaviour**:  One position change, one Ember.

**Server Revision**:  3376

https://wowwiki.fandom.com/wiki/Al%27ar
>Ember of Al'ar
>One is spawned after each position change in Phase 1, and two are spawned after each Dive Bomb in Phase 2.

Our last attempt:  https://youtu.be/l6AFeVYXjm8?t=55
At first it looks like there is only one but after a few seconds they separate.

**Comment by Tereneckla** [comment]
> 
> 
> Al'ar on Netherwing is intentionally using mechanics from before Patch 2.1.0. You can read about these mechanics at your wiki link from that time:
> 
> https://wowwiki.fandom.com/wiki/Al%27ar?oldid=659101
> 
> This addresses the 6 platforms, the Meteor (not Dive Bomb) damage, and the platform order. Al'ar originally spawned 3 adds on Netherwing, as the wiki page says, but it was nerfed to 2 at some point.
