### ISSUE TITLE
[Tempest Keep] A'lar - random platform order.

### ISSUE THREAD

**Issue by Syfte-oss** [Atlantiss/NetherwingBugtracker#6994]
**Description**:  The fight is supposed to start with A'lar aggro'ing to the first platform and then moving around the room in a clockwise fashion.

**Current behaviour**:  A'lar aggro's to the fourth platform and each subsequent platform is random.

**Expected behaviour**:  Fight starts on platform one, moves to platform two and so on to the fourth platform.

**Server Revision**:  3376

https://wowwiki.fandom.com/wiki/Al%27ar
>Phase I
>Phase I is straightforward.
>Al'ar will always fly to the left ramp when pulled. A tank needs to wait there to avoid Flame Buffet. 

What happens: https://www.youtube.com/watch?v=l6AFeVYXjm8

**Comment by Tereneckla** [comment]
> 
> 
> Al'ar on Netherwing is intentionally using mechanics from before Patch 2.1.0. You can read about these mechanics at your wiki link from that time:
> 
> https://wowwiki.fandom.com/wiki/Al%27ar?oldid=659101
> 
> This addresses the 6 platforms, the Meteor (not Dive Bomb) damage, and the platform order. Al'ar originally spawned 3 adds on Netherwing, as the wiki page says, but it was nerfed to 2 at some point.
