### ISSUE TITLE
[Tempest Keep] A'lar uses two additional locations as platforms.

### ISSUE THREAD

**Issue by Syfte-oss** [Atlantiss/NetherwingBugtracker#6995]
**Description**: A'lar uses two additional locations flanking the lower door as platforms bringing the total number of possible platforms to six.

**Current behaviour**:  See above.

**Expected behaviour**:  Four fixed locations.

**Server Revision**:  3376

https://wowwiki.fandom.com/wiki/Al%27ar
>Al'ar spends around 30 seconds on each platform, then moves on to the next, flying clockwise (W, NW, NE, E, repeat).

What happens: https://youtu.be/l6AFeVYXjm8?t=106
He went to one but not both on this try.  But throughout our other tries A'lar did go to both.

**Comment by Tereneckla** [comment]
> 
> 
> Al'ar on Netherwing is intentionally using mechanics from before Patch 2.1.0. You can read about these mechanics at your wiki link from that time:
> 
> https://wowwiki.fandom.com/wiki/Al%27ar?oldid=659101
> 
> This addresses the 6 platforms, the Meteor (not Dive Bomb) damage, and the platform order. Al'ar originally spawned 3 adds on Netherwing, as the wiki page says, but it was nerfed to 2 at some point.
