### ISSUE TITLE
[Tempest Keep] A'lar's Dive Bomb hits for 6 times correct damage.

### ISSUE THREAD

**Issue by Syfte-oss** [Atlantiss/NetherwingBugtracker#6996]
**Description**:  The Dive Bomb attack should strike one player for ~1000 fire damage.  Instead it one-shots players with ~30000 fire damage.

**Current behaviour**:  Dive Bomb = ~30000 fire damage.

**Expected behaviour**:  Dive Bomb = ~5000 fire damage.

**Server Revision**:  3376

https://wowwiki.fandom.com/wiki/Al%27ar
>Dive Bomb: Al'ar flies up, and targets the ground beneath a random player. Al'ar then crashes into the ground at that location. This deals ~5000 fire damage, and spawns two Ember of Al'ar adds. Al'ar then uses Rebirth at that location. 30 second cooldown. 

30k hit on our Ember tank: https://i.imgur.com/2JPSe0W.jpg

**Comment by raethkcj** [comment]
Al'ar on Netherwing is intentionally using mechanics from before Patch 2.1.0. You can read about these mechanics at your wiki link from that time:

https://wowwiki.fandom.com/wiki/Al%27ar?oldid=659101

**Comment by Tereneckla** [comment]
Recount death log doesn't prove anything about the damage being to high, as it is split up on everyone hit.

We generally had 4-5k damage on each person with everyone stacked up. As described in the link raethkcj gave.

**Comment by Syfte-oss** [comment]
> 
> 
> Recount death log doesn't prove anything about the damage being to high, as it is split up on everyone hit.
> 
> We generally had 4-5k damage on each person with everyone stacked up. As described in the link raethkcj gave.
> ![image](https://user-images.githubusercontent.com/50233983/82751411-462aaf80-9db7-11ea-8ee7-26beef057c81.png)
> Gives you a nice 5k damage each split up on 28 targets (full raid and some pets)

Thank you for this and the other replies and I hope you'll pardon my TK spam.  On the upside, we're going to try it again this week now that we have the correct information about the fight.
