### ISSUE TITLE
[Spell][Rogue] Poisons proc rate is too low

### ISSUE THREAD

**Issue by fosquaker** [Atlantiss/NetherwingBugtracker#6997]
[//]: # (Enclose links to things related to the bug using http://wowhead.com or any other TBC database.)
[//]: # (You can use screenshot ingame to visual the issue.)
[//]: # (Write your tickets according to the format:)
[//]: # ([Quest][Azuremyst Isle] Red Snapper - Very Tasty!)
[//]: # ([NPC] Magistrix Erona)
[//]: # ([Spell][Mage] Fireball)
[//]: # ([Npc][Drop] Ghostclaw Lynx)
[//]: # ([Web] Armory doesnt work)
[//]: # (To find server revision type `.server info` command in the game chat.)

**Description**: 
Poison proc rate is way too low. Rogues cant use crippling on shiv / mind-numbing on 2nd OH jsut because wound poison just dont stack properly even with full hemo spam.
**Current behaviour**:
its like 10% proc rate accodning by tests
**Expected behaviour**: 
should be 30%
**Server Revision**: 
3376

**Comment by Wolffenstein** [comment]
![obraz](https://user-images.githubusercontent.com/1576644/86051374-96033300-ba55-11ea-95ca-64491c3ecea1.png)
Works fine.
