### ISSUE TITLE
[Warlock] Felhunter's Steals Detection is broken

### ISSUE THREAD

**Issue by fosquaker** [Atlantiss/NetherwingBugtracker#6998]
[//]: # (Enclose links to things related to the bug using http://wowhead.com or any other TBC database.)
[//]: # (You can use screenshot ingame to visual the issue.)
[//]: # (Write your tickets according to the format:)
[//]: # ([Quest][Azuremyst Isle] Red Snapper - Very Tasty!)
[//]: # ([NPC] Magistrix Erona)
[//]: # ([Spell][Mage] Fireball)
[//]: # ([Npc][Drop] Ghostclaw Lynx)
[//]: # ([Web] Armory doesnt work)
[//]: # (To find server revision type `.server info` command in the game chat.)

**Description**: 
Felhunter can detect any stealth (except Vanish) in HUGE radius atm, atm you cant Sap Warlock w/o using Vanish. (even shadowstep -> sap combo can be ruined by Felhunter)
**Current behaviour**:
Stealth detection is overbuffed
**Expected behaviour**: 
SHould me much lower
**Server Revision**: 
3376

**Comment by Wolffenstein** [comment]
Fixed in rev 3390.
