### ISSUE TITLE
[warrior] Taunt trick vs Frost trap aint working as supposed

### ISSUE THREAD

**Issue by Cobratr** [Atlantiss/NetherwingBugtracker#6999]
**Description**: 
Warrior taunt trick vs Hunter frost trap is not working as it should be.
**Current behaviour**:
Even though pet is on aggressive-defensive;when i taunt/mocking/aoe taunt the pet before getting trapped;pet goes afk to near his hunter.
**Expected behaviour**: 
Pet should come and break trap while under my taunt icon.
**Server Screenshot**: 
https://hizliresim.com/b8VQ0Z
https://hizliresim.com/2C2WT3
**My google research about topic with their dates**
https://github.com/SunstriderEmu/BugTracker/issues/1813
https://wowwiki.fandom.com/wiki/Mocking_Blow?oldid=707574 (date:2007)
https://gamefaqs.gamespot.com/pc/534914-world-of-warcraft/faqs/49970 (date:2007) (control+F:write ''taunt'')
https://vanilla-twinhead.twinstar.cz/?issue=11428

**Comment by 4egito** [comment]
Stoneclaw should work in the same way but keep this in mind -> 
**"Pets are subtle to taunt effects, so yes Stoneclaw will taunt pets away from you (any good hunter will have the pet on you in a second though)."** That means the hunter still can control his creature...
There is the source ->
https://gamefaqs.gamespot.com/boards/534914-world-of-warcraft/42529631

**Comment by 4egito** [comment]
**Pet under taunt effect**
from this comments possible to tell that pet should be controllable under taunt effect
Stoneclaw will taunt pets away from you (any good hunter will have the pet on you in a second though). http://www.gamefaqs.com/boards/534914-world-of-warcraft/42529631
**Passive pets will no longer attack due to AoE taunt spells.** -> https://wowwiki.fandom.com/wiki/Patch_2.4.3

**Comment by 4egito** [comment]
From the post above^^ 
![image](https://user-images.githubusercontent.com/52432938/82970221-f6c3c980-9fd8-11ea-9af0-70c7788f2746.png)

https://vanilla-twinhead.twinstar.cz/?issue=11428#comments:id=50079

**Comment by Wolffenstein** [comment]
Fixed in rev 3383.
