### ISSUE TITLE
Battle Shout and Blessing of Might not stacking

### ISSUE THREAD

**Issue by Kibir34** [Atlantiss/NetherwingBugtracker#7]
Currently BS and BoM aren't stacking even though that was only changed in patch 3.0.2

http://wowwiki.wikia.com/wiki/Patch_3.0.2_(undocumented_changes)
Warriors
Battle Shout: No longer stacks with Blessing of Might or Greater Blessing of Might.

**Comment by notsofamous** [comment]
Blood Fury removes Battle Shout, Battle Shout does not buff on the caster if he has Blood Fury active. Buff stacking issue?

**Comment by Jacksn5** [comment]
[2025][Core] Blood Fury should now properly stack with other similar buffs

BUT it's not possible to apply Battle Shout during Blood Fury. See https://youtu.be/ArD6C6d3kxs?t=20 at sec 20

**Comment by Wolffenstein** [comment]
Fixed in rev 2067.
