### ISSUE TITLE
Lord Melenas - Rake Ability

### ISSUE THREAD

**Issue by Azalen** [Atlantiss/NetherwingBugtracker#70]
https://classicdb.ch/?npc=2038

Melenas transforms nice into catform but I think he is using a to high level "Rake Ability". Right now it does 24 damage every 3 seconds which is a lot for a 170 hp target. I also have high armor (shield, 3 mail pieces) so probably even more damage for clothies.

PS: yes, i died :)
PPS: please rethink the big input lag :)
PPPS: still most stuff is working great, having fun!

**Comment by Wolffenstein** [comment]
Fixed in rev 2022.
