### ISSUE TITLE
[Rogue] Rupture Rank 1: Always 5s with 8dmg

### ISSUE THREAD

**Issue by padomu** [Atlantiss/NetherwingBugtracker#700]
[//]: # (Enclose links to things related to the bug using http://wowhead.com or any other TBC database.)
[//]: # (You can use screenshot ingame to visual the issue.)
[//]: # (Write your tickets according to the format:)
[//]: # ([Quest][Azuremyst Isle] Red Snapper - Very Tasty!)
[//]: # ([NPC] Magistrix Erona)
[//]: # ([Spell][Mage] Fireball)
[//]: # ([Npc][Drop] Ghostclaw Lynx)
[//]: # ([Web] Armory doesnt work)

**Description**: 

**Current behaviour**:

Rank one of Rupture is always 5s and makes 8dmg, it does not depend on the amount of CP

**Expected behaviour**: 
Rupture should work like in the tooltip with proper scaling with AP etc. It should also ignore armor etc.

**Server Revision**: 
2065

**Comment by Wolffenstein** [comment]
Fixed in rev 2067.
