### ISSUE TITLE
[Quest] Return to Sha'tari Base Camp

### ISSUE THREAD

**Issue by bekonja** [Atlantiss/NetherwingBugtracker#7000]
[//]: # (Enclose links to things related to the bug using http://wowhead.com or any other TBC database.)
[//]: # (You can use screenshot ingame to visual the issue.)
[//]: # (Write your tickets according to the format:)
[//]: # ([Quest][Azuremyst Isle] Red Snapper - Very Tasty!)
[//]: # ([NPC] Magistrix Erona)
[//]: # ([Spell][Mage] Fireball)
[//]: # ([Npc][Drop] Ghostclaw Lynx)
[//]: # ([Web] Armory doesnt work)
[//]: # (To find server revision type `.server info` command in the game chat.)

**Description**: 
https://tbcdb.com/?quest=10926

**Current behaviour**:
Requires lv65 to pick up

**Expected behaviour**: 
https://tbcdb.com/?quests=8.3519#100+3+1+2
^ all other Terokkar naitive quests are lv63 req max
https://www.wowhead.com/quest=10926/return-to-shatari-base-camp
^ lv62 req according to wowhead

Nothing i can find about this quest being an outlier for level requirement. It isnt significant quest, it leads to nothing, just random 8k exp and bunch of gold coins. Most likely PServers got its lv req wrong.

**Server Revision**: 
3374

**Comment by Evolvee** [comment]
it requires level 63 currently
http://web.archive.org/web/20070315182543/http://www.thottbot.com/q10926
![image](https://user-images.githubusercontent.com/1942409/83330770-c35f9400-a291-11ea-894d-910b4a7b5802.png)
