### ISSUE TITLE
[Quest] Vision Guide

### ISSUE THREAD

**Issue by bekonja** [Atlantiss/NetherwingBugtracker#7002]
[//]: # (Enclose links to things related to the bug using http://wowhead.com or any other TBC database.)
[//]: # (You can use screenshot ingame to visual the issue.)
[//]: # (Write your tickets according to the format:)
[//]: # ([Quest][Azuremyst Isle] Red Snapper - Very Tasty!)
[//]: # ([NPC] Magistrix Erona)
[//]: # ([Spell][Mage] Fireball)
[//]: # ([Npc][Drop] Ghostclaw Lynx)
[//]: # ([Web] Armory doesnt work)
[//]: # (To find server revision type `.server info` command in the game chat.)

**Description**: 
https://tbcdb.com/?quest=10525
https://www.youtube.com/watch?v=zxoqA8_VIoI&feature=youtu.be
After accepting the quest "Fiery Soul Fragment" item is handed to player. Using said item transforms player to a wisp, making them to lose control of their character. Small "cutscene" plays when wisp files into a cave and then quest completes.

**Current behaviour**:
After cutscene ends player gets teleported to a cave. 

**Expected behaviour**: 
Player's character should get teleported back to questgiver NPC.
Quest was working properly couple of months ago, no idea why it broke.

**Server Revision**: 
3376

**Comment by Evolvee** [comment]
taxi_vision_guide 632

**Comment by Wolffenstein** [comment]
Fixed in rev 3386.
