### ISSUE TITLE
 [NPC] [Horde Halaani Guard] Not all guards exist

### ISSUE THREAD

**Issue by marytit** [Atlantiss/NetherwingBugtracker#7004]
**Description**: > Not all guards exist, but it shows 15/15 are alive.

**Current behaviour**: Only 9 guards are alive. Can't take Halaa. They are not died, we killed all of them, but it shows that 6 guards are still alive, what is a lie.

**Expected behaviour**: 15 guards are alive.

**Server Revision**:  3376

**Comment by Wolffenstein** [comment]
This should be fixed now.
