### ISSUE TITLE
Crystalforged Dark Rune - Event NPC is Bugged/Doesn't Spawn correctly.

### ISSUE THREAD

**Issue by Purplepills4746** [Atlantiss/NetherwingBugtracker#7005]
Like the title says,
NPC(Felguard) for the Crystalforged Dark Rune Ogrila event doesn't spawn, had a GM try and reset the NPC but then the NPC wasn't even target able.
Hope this info helps?
Cheers and all the best.
Purplepills.

**Comment by Godmatik** [comment]
Duplicate
