### ISSUE TITLE
[Item] Pendant of the Violet Eye

### ISSUE THREAD

**Issue by arcwizard** [Atlantiss/NetherwingBugtracker#7006]
https://www.wowhead.com/item=28727/pendant-of-the-violet-eye
**Description**: 
Use: Each spell cast within 20 seconds will grant a stacking bonus of 21 mana regen per 5 sec. Expires after 20 sec.  Abilities with no mana cost will not trigger this trinket. (2 Min Cooldown)

**Current behaviour**:
-  1 Chain Arcane missiles (5 missiles) [mage spell] give 1 charge (enlightment). 
-  1 Cast Arcane Explosion [mage spell] give 1 charge (enlightment), no matter how much targets take hit.

**Expected behaviour**: 
-  Every arcane missile from chain (arcane missiles) should give 1 charge (enlightment), so 1 chain arcane missiles rank 10 (which have 5 volley) should give 5 charge (enlightment) .
-  Every target which took hit from Arcane Explosion should give 1 charge(1 buff enlightment).

**Server Revision**: 
3376

https://www.wowhead.com/item=28727/pendant-of-the-violet-eye#comments
"By Elektron (305 – 2) on 2008/05/09 (Patch 2.4.1)
2/ it is very easy to get the buff - just 3x Arcane Missles as the trinket proc's on each missle hit (= 15 stacks in 15 sec with haste rating)"
"By 103959 (117 – 1) on 2008/07/09 (Patch 2.4.1)
 I on an average get it to, 12 to 16 stacks, and gain around 750 to 1100 mana from this trinket just doing the stacks with Arcane Missiles."
Both of these comments say that the mage receives not 1 charge for 1 spell cast, but 1 for each hit. In comments there’s not talking about Arcane Explosion, but it’s talking about the charge from each arcane missile from the chain, from which we can conclude that the charges are based on the hit (direct damage), and not on the casting spells,

**Comment by Tereneckla** [comment]
Interestingly those 2 are the only comments overall that talk about it stacking per spell hit.
Everyone else is talking about using downranked fast spells to stack it, even shamans which have the notorious chain heal for other per spell cast trinkets like [Eye of Gruul](https://wowwiki.fandom.com/wiki/Eye_of_Gruul). (That one can proc on each target healed by chain heal)

**Comment by arcwizard** [comment]
There are also one more comment:
>> By gomash (184 – 3·2) on 2007/09/23 (Patch 2.1.3) 1. how much mana will i gain if i spam arcane missiles (each missile procs it, and you shoot one every second) ? with bloodlust/heroism this thing will be so nice i bet.

Another source (elitist jerks). Look 239 message from Vokzhen (<Wraith>
Spinebreaker) at 08/28/07, 2:41 AM.  https://web.archive.org/web/20071222211936/http://elitistjerks.com/f31/t10907-vontre_s_mage_dps_spreadsheet/p10/  
>> By the sounds of some of the arcane mage threads, you'll have some updated to do come 2.2 :P Wondering if, during that, you could include [Pendant of the Violet Eye] and [Mark of Defiance] as well, since (last I checked the threads anywho) they're both **proccing off every AM tick, which gives a huge advantage to AM spam**.

**Comment by Tereneckla** [comment]
So it's just each missile of arcane missile counting as a spellcast.

**Comment by Godmatik** [comment]
Arcane explosion is properly giving 1 charge for each target hit

Arcane missiles is getting 2 charges every time you cast the spell, rather than 1 charge for each missile

Rev 4016

**Comment by Godmatik** [comment]
Fixed in upcoming spell proc rework branch

**Comment by Godmatik** [comment]
Follow-up:
This report is actually invalid, should give only 1 stack per arcane missile cast, not 1 stack per missile, it was nerfed in patch 2.3

![qweqweqwqq](https://github.com/user-attachments/assets/0f4a0617-3d63-43fb-a32d-b5b52647959f)
