### ISSUE TITLE
Shattered sun pendant of accumen proc

### ISSUE THREAD

**Issue by waaliiid** [Atlantiss/NetherwingBugtracker#7007]
https://fr.wowhead.com/item=34678/pendentif-de-sagacit%C3%A9-du-soleil-bris%C3%A9

The item dosent proc

**Description**: 

The item dont proc his bonus at all , while i'am exalted with the two factions ( SCYERS / SHATTERED SUN OFFENSIVE )

**Expected behaviour**: 

The item should proc a bonus damage of 120.

**Comment by arcwizard** [comment]
It does.
![2131](https://user-images.githubusercontent.com/43764742/83352518-47765200-a34c-11ea-8e8f-d99ec7296495.jpg)

**Comment by raethkcj** [comment]
The Scryer proc is working correctly:

![image](https://user-images.githubusercontent.com/7716908/83355542-aeccdb80-a325-11ea-9379-d612515ba4d2.png)
