### ISSUE TITLE
[Quest][Netherwing Ledge] Dragonmaw Race: Wing Commander Mulverick

### ISSUE THREAD

**Issue by Ricedaddy** [Atlantiss/NetherwingBugtracker#7008]
[//]: # (Enclose links to things related to the bug using http://wowhead.com or any other TBC database.)
[//]: # (You can use screenshot ingame to visual the issue.)
[//]: # (Write your tickets according to the format:)
[//]: # ([Quest][Azuremyst Isle] Red Snapper - Very Tasty!)
[//]: # ([NPC] Magistrix Erona)
[//]: # ([Spell][Mage] Fireball)
[//]: # ([Npc][Drop] Ghostclaw Lynx)
[//]: # ([Web] Armory doesnt work)
[//]: # (To find server revision type `.server info` command in the game chat.)

**Description**: (https://www.wowhead.com/quest=11070/dragonmaw-race-wing-commander-mulverick))
  [QUEST TEXT]Follow Wing Commander Mulverick while attempting to stay on your flying mount.  Should you defeat Wing Commander Mulverick, report your victory to Ja'y Nosliw at the Dragonmaw Base Camp in Shadowmoon Valley.

 [OBJECTIVE] Stay within range and on your flying mount for the duration of the race.

**Current behaviour**:
    -Wing Commander Mulverick is casting lightning bolts at a much higher rate compared to other videos.  In addition, the quest will fail no matter how close the player is to Wing Commander Mulverick when rounding the first corner off the landing strip.  As mentioned in a previous issue reported (see https://github.com/Atlantiss/NetherwingBugtracker/issues/6886 ), Wing Commander Mulverick will disappear when approaching crystals, no matter the player's distance to him.  

See my race below.  (If you would like the full video, please let me know where I can send that size file.)

![2020-05-31-17-45-08-Trim-Trim-Tr](https://user-images.githubusercontent.com/66224922/83364537-e95b6600-a36f-11ea-8119-1f398f954d90.gif)

**Expected behaviour**: 
    -Wing Commander Mulverick does not disappear when the player is in close proximity.  Wing Commander Mulverick will disappear if the player is too far away due to the player being knocked off the mount or not keeping up in the race.

See wowhead videos:
https://www.youtube.com/watch?v=UX0yysWOtMc
https://www.youtube.com/watch?v=8hN3I37hjAQ

**Server Revision**: 3376

**Comment by raethkcj** [comment]
I encountered the issue with the crystal in the gif 10+ times in a row, no matter how close I flew to him, the quest failed at that exact point and Mulverick disappeared. I'm not sure if it's some kind of line of sight issue, or if there's some spot there that doesn't count as being on Netherwing Ledge that causes you to fail. It's very frustrating.

**Comment by Logo251** [comment]
I've done this many times as well and had the same issue. I can supply video if needed. Mulverick seems to fly partly into the crystal, perhaps that causes me to be considered out of range?

**Comment by hederob** [comment]
In my experience doing this on 2 toons, try not to fly in front of him.

**Comment by Ricedaddy** [comment]
I appreciate your feedback, but this is not the issue.  I have flown in front of him, above him, below him, and behind him. He does not make it further than this point during any attempt.  Other riders you can fly in front or anywhere around them, so long as you are within range.

**Comment by Logo251** [comment]
Based on the prevalence of nether drake mounts and when this bug was opened, I assume the developer changed something that broke this quest, if that helps explain why it may have worked for you and not others. I personally tried many times, including in front, far right, far above, far left (above the mountains), nearly inside of him (for the part where it breaks) and behind him, and none worked.

**Comment by Wolffenstein** [comment]
Fixed in rev 3676.
