### ISSUE TITLE
[Item] Darkmoon Card: Vengeance

### ISSUE THREAD

**Issue by SlavaLysak** [Atlantiss/NetherwingBugtracker#7009]
[//]: # (Enclose links to things related to the bug using http://wowhead.com or any other TBC database.)
[//]: # (You can use screenshot ingame to visual the issue.)
[//]: # (Write your tickets according to the format:)
[//]: # ([Quest][Azuremyst Isle] Red Snapper - Very Tasty!)
[//]: # ([NPC] Magistrix Erona)
[//]: # ([Spell][Mage] Fireball)
[//]: # ([Npc][Drop] Ghostclaw Lynx)
[//]: # ([Web] Armory doesnt work)
[//]: # (To find server revision type `.server info` command in the game chat.)
https://www.wowhead.com/item=31858/darkmoon-card-vengeance
**Description**: 
Equip: You have a 10% chance when hit by an attack or harmful spell to deal 11 holy damage to your attacker.
**Current behaviour**:
proc not work on blocked attack
**Expected behaviour**: 
proc  work off a block, full block
**Server Revision**: 
3376

https://www.wowhead.com/item=31858/darkmoon-card-vengeance#comments

By 51974 (545 – 1·5) on 2007/06/08 (Patch 2.1.1) 
So far this doesn't seem to proc if you avoid an attack via miss, dodge, or parry.
However, it does proc off a block, even a full block.

aleph on 2007/06/09 (Patch 2.1.1)
That makes sense, since a block counts as being hit even if it does no damage.

**Comment by Godmatik** [comment]
Rev 4016 - confirmed and still an issue

**Comment by Godmatik** [comment]
Fixed in upcoming spell proc rework branch
