### ISSUE TITLE
[CORE] Resist chances feels too high

### ISSUE THREAD

**Issue by 4egito** [Atlantiss/NetherwingBugtracker#7010]
[//]: # (Enclose links to things related to the bug using http://wowhead.com or any other TBC database.)
[//]: # (You can use screenshot ingame to visual the issue.)
[//]: # (Write your tickets according to the format:)
[//]: # ([Quest][Azuremyst Isle] Red Snapper - Very Tasty!)
[//]: # ([NPC] Magistrix Erona)
[//]: # ([Spell][Mage] Fireball)
[//]: # ([Npc][Drop] Ghostclaw Lynx)
[//]: # ([Web] Armory doesnt work)
[//]: # (To find server revision type `.server info` command in the game chat.)

**Description**: 
4 wound poison resist in a row vs night elf resto druid with "Mark of the wild" buff (28 nature resist from "Mark of the wild" and 10 from racial ability = 38)
Based on this formula: **Average Resist Rate of Defender (as a decimal) = 0.75 * (defenderSpellResistance) / (5*attackerLevel)** a.k.a
0.75 * 38 / 5*70 = 28,5 / 350 = 0.08143 (that means round 8% resist chance)
And the calculations bellow represent whats the chance for this to happen in a row
![chance](https://user-images.githubusercontent.com/52432938/83413799-1ddd2980-a425-11ea-9aaf-d49575df5634.png)

**Current behaviour**:
![WoWScrnShot_060120_000252](https://user-images.githubusercontent.com/52432938/83402000-a3091400-a40e-11ea-8965-f5ca2a220184.jpg)
This post is not about wound poisons only... Sometimes for example spell hit/spell penetration capped locks resist 3-4 spells in a row which is weird (i mean in pvp) that makes me thinking that spell resist calculations are wrong... Or RNG generator don't work as he should...

**Expected behaviour**: 
https://dwarfpriest.wordpress.com/2008/01/07/spell-hit-spell-penetration-and-resistances/
Here u can check all the formulas for pve/pvp with spell pen calculations etc.

**Server Revision**:

**Comment by Idabegei** [comment]
Hopefully gets looked into. Please devs!

**Comment by raethkcj** [comment]
Tropiq has 34 points in the Balance tree, do you know whether he has the Balance of Power talent? It would give him an extra 4% resist rate.

https://alpha.legacyplayers.com/armory/character/Netherwing/Tropiq
https://tbc-twinhead.twinstar.cz/?spell=33596

**Comment by raethkcj** [comment]
Whether or not Tropiq has that talent, you're only doing half of the resistance calculation described in your link. You correctly found what the blog post calls "average resist rate" which is 8.143%. The next step is subtracting that from 1 to get the "resistance non-mitigation chance".

`Resistance non-mitigation chance: 1 - 8.143% = 91.857%`

Next, all players vs. players of equal level have a base 4% spell miss chance. The Balance talent would increase this to 8%, giving you a hit rate of 96% or 92%. In either case, the blog post suggests you *multiply* this hit rate with the resistance non-mitigation chance to get the actual chance to hit.

Without talent:
`91.857% * 96% = 88% hit chance`

With talent:
`91.857% * 92% = 85% hit chance`

**Comment by 4egito** [comment]
You are totally right, but don't you think that is strange for poisons who comes after physical attack to be affected by spell hit chance? I think when shiv successfully connects on target we can talk about spell resist not spell hit chance...

**Comment by raethkcj** [comment]
Well, I think that's the point of the Master Poisoner talent in Assassination tree. Poisons can resist (spell miss). Shiv has a 100% proc rate on poison but doesn't guarantee it will hit.

**Comment by raethkcj** [comment]
Even with all that you should have 85% poison hit chance when you shiv, so 4 resists in a row is *still* questionable. It is possible there is a bug, or we still don't have the whole story, or just bad RNG.

**Comment by 4egito** [comment]
Yeah its kinda hard to know what really happens on the server because you can't see "miss" on spells in TBC (in WOTLK+ you can), there is always shown "resist" no matter what really happens behind (spell miss or spell resist). That's why i gave information for calculating formulas etc in order for devs to check does it really works as it should. If it is then is a bad RNG and i'm not gonna blame anybody except myself...

**Comment by Wolffenstein** [comment]
I've tested everything related to resists and pushed some changes that should hopefully fix this issue. If this still happens then you're just unlucky or there's something else going on.
