### ISSUE TITLE
[Item] Timbal's Focusing Crystal turns both players in combat state when proc

### ISSUE THREAD

**Issue by 4egito** [Atlantiss/NetherwingBugtracker#7011]
[//]: # (Enclose links to things related to the bug using http://wowhead.com or any other TBC database.)
[//]: # (You can use screenshot ingame to visual the issue.)
[//]: # (Write your tickets according to the format:)
[//]: # ([Quest][Azuremyst Isle] Red Snapper - Very Tasty!)
[//]: # ([NPC] Magistrix Erona)
[//]: # ([Spell][Mage] Fireball)
[//]: # ([Npc][Drop] Ghostclaw Lynx)
[//]: # ([Web] Armory doesnt work)
[//]: # (To find server revision type `.server info` command in the game chat.)

**Description**: 
Timbal's Focusing Crystal turns both players in combat state when proc.
for example if i have dots from warlock and he is blinded, dots can proc the effect of the trinket and i can't sap him after because proc reset the combat timer... Or just stops me while i'm eating/drinking in arena.

**Current behaviour**:
Timbal's Focusing Crystal turns both players in combat state when proc.
**Expected behaviour**: 
Timbal's Focusing Crystal should **not** turns both players in combat state when proc.
**Server Revision**:

**Comment by Tweet1337** [comment]
Source?

I mean - all damage done by players to other players will put both of them into combat and ofc interrupts eating/drinking. Why that should be different in this case?

**Comment by 4egito** [comment]
https://wowwiki.fandom.com/wiki/Timbal%27s_Focusing_Crystal
**This trinket gives a chance to deal extra damage in the form of a Shadow Bolt, which is capable to do a spell critical strike, at every tick of a DoT or channeled spell.** Its called extra damage not separate cast. In Netherwing u throwing instant shadow bolt while u are in CC effect. Is that enough?

**Comment by 4egito** [comment]
https://www.wowhead.com/item=34470/timbals-focusing-crystal&bonus=4080#comments:id=270717:reply=47728
![image](https://user-images.githubusercontent.com/52432938/83943099-e514ca00-a801-11ea-87c8-bb870d3298ae.png)

**Comment by Wolffenstein** [comment]
Fixed in rev 3412.
