### ISSUE TITLE
[core] devilsaurs patrol stacking issue / fishing nodes stacking

### ISSUE THREAD

**Issue by duzyizly** [Atlantiss/NetherwingBugtracker#7012]
**Description**: 
3 different devilsaurs are patroling same path at once.
There's the same issue with another devilsaurs at un'goro area, so most likely core issue?

![WoWScrnShot_060120_162137](https://user-images.githubusercontent.com/43931626/83418752-6516ea80-a424-11ea-8ef5-aa9eba4fc0bf.jpg)
![WoWScrnShot_060120_162200](https://user-images.githubusercontent.com/43931626/83418767-69430800-a424-11ea-80df-132aefdb81e7.jpg)

**Server Revision**: 
been tested on 3376 ptr (not sure about live version)

**Comment by duzyizly** [comment]
looks like different fishing nodes are stacking aswell.
![WoWScrnShot_060120_165231](https://user-images.githubusercontent.com/43931626/83421547-92659780-a428-11ea-8343-a9faca6613eb.jpg)

**Comment by Evolvee** [comment]
![2x](https://user-images.githubusercontent.com/1942409/83438589-f779b700-a441-11ea-89ce-ec1782331db8.gif) pooling broken for the 6th time ![2x](https://user-images.githubusercontent.com/1942409/83438589-f779b700-a441-11ea-89ce-ec1782331db8.gif)

**Comment by Wolffenstein** [comment]
Fixed in rev 3406.
