### ISSUE TITLE
Hunter unable to learn Dive 3

### ISSUE THREAD

**Issue by Laadna** [Atlantiss/NetherwingBugtracker#7013]
I tamed 4 different pets who all have dive 3 skill : shadowing owl, kaliri swooper, dire raven, ironbeak screecher. I fought with all of them for hours with dive on auto-use and never learnt the skill. Usually it takes maximum ten minutes for a 30s cooldown skill.

I didnt have any issue with learning dash or prowl, but I did this a few monthes ago.

**Comment by Frostsack** [comment]
Having the same problem here. Spoke with a Game Master but he said he can't fix anything and linked me to github.. This sucks and hunters need to be able to train their pets properly so can someone please look into this?

**Comment by Laadna** [comment]
When I first opened a ticket, the GM asked me to report the bug here and said he would escalate my ticket so the head GM would fix my bug. Which he didn't : he just wrote me he couldnt find me online and closed my ticket.

**Comment by Red86** [comment]
To learn dive 3 you got to tame one of the azeroth beasts that have it, you'll be able to learn it from those.

**Comment by The14me** [comment]
U can learn Dive 3 only from this mobs .
https://i.imgur.com/2xBUh9H.png

**Comment by Tereneckla** [comment]
Had no problem learning dive from any of those birds
