### ISSUE TITLE
[Object][Fishing]Terokkar Fishing Schools

### ISSUE THREAD

**Issue by bekonja** [Atlantiss/NetherwingBugtracker#7014]
[//]: # (Enclose links to things related to the bug using http://wowhead.com or any other TBC database.)
[//]: # (You can use screenshot ingame to visual the issue.)
[//]: # (Write your tickets according to the format:)
[//]: # ([Quest][Azuremyst Isle] Red Snapper - Very Tasty!)
[//]: # ([NPC] Magistrix Erona)
[//]: # ([Spell][Mage] Fireball)
[//]: # ([Npc][Drop] Ghostclaw Lynx)
[//]: # ([Web] Armory doesnt work)
[//]: # (To find server revision type `.server info` command in the game chat.)

**Description**: 
https://www.wowhead.com/object=182954/brackish-mixed-school
https://www.wowhead.com/object=182956/school-of-darter
https://www.wowhead.com/object=182957/highland-mixed-school

**Current behaviour**:
PTR: multiple types of schools spawn ontop of eachother.
LIVE: same behavior as on PTR in Skettis; Terokkar ground level seems ok.
Not sure why its more bugged on PTR than LIVE, need futher research.

**Expected behaviour**: 
Only 1 school per spot.

**Server Revision**: 
PTR: 3376
LIVE: 3376

**Comment by duzyizly** [comment]
https://github.com/Atlantiss/NetherwingBugtracker/issues/7012
