### ISSUE TITLE
[NPC] Booty Bay Bruiser give wrong rep penalty

### ISSUE THREAD

**Issue by Tereneckla** [Atlantiss/NetherwingBugtracker#7016]
[//]: # (Enclose links to things related to the bug using http://wowhead.com or any other TBC database.)
[//]: # (You can use screenshot ingame to visual the issue.)
[//]: # (Write your tickets according to the format:)
[//]: # ([Quest][Azuremyst Isle] Red Snapper - Very Tasty!)
[//]: # ([NPC] Magistrix Erona)
[//]: # ([Spell][Mage] Fireball)
[//]: # ([Npc][Drop] Ghostclaw Lynx)
[//]: # ([Web] Armory doesnt work)
[//]: # (To find server revision type `.server info` command in the game chat.)

**Description**: Steamwheedle Cartel is a unused filler faction.

**Current behaviour**: Reduce your rep with Steamwheedle Cartel by 312

**Expected behaviour**: Reduce your rep with Booty Bay by 312 and the other goblin factions by half of that (156)

**Server Revision**: 3376

**Comment by Wolffenstein** [comment]
That's just what the client displays. In reality all the other goblin factions have their rep reduced properly.

**Comment by Wolffenstein** [comment]
Fixed in rev 3387.

**Comment by Tereneckla** [comment]
You misunderstood me there.
![image](https://user-images.githubusercontent.com/50233983/85111325-74fc4000-b214-11ea-8da0-8edae898e887.png)

![image](https://user-images.githubusercontent.com/50233983/85111380-89d8d380-b214-11ea-8e00-aee059db6595.png)

Steamwheedle Cartel is just a hidden faction that is used to divide in the tab.
https://wow.spectralcoding.com/insane/index.html#section_2.1
![image](https://user-images.githubusercontent.com/50233983/85112162-83972700-b215-11ea-84b9-a41b8fbbe48e.png)

Actually the whole rep gain and loss is too high
+25 for Bloodsail
-125 for Booty Bay (and half of that for the other goblin factions because of spillover)

**Comment by Wolffenstein** [comment]
I still don't understand. While the client displays reputation loss with Steemwheedle Cartel, you simply lose rep with other goblin towns. So where's the problem?

**Comment by Tereneckla** [comment]
The thing is that you don't

**Comment by Wolffenstein** [comment]
![obraz](https://user-images.githubusercontent.com/1576644/85162858-4dcc5f80-b262-11ea-9f45-2ba56b937a78.png)
![obraz](https://user-images.githubusercontent.com/1576644/85162881-558c0400-b262-11ea-90e1-831b6142fdab.png)

Seems to be working fine for me.

**Comment by Wolffenstein** [comment]
Okay, I figured it out. The max cap (honored) was applied not only to Bloodsail gain, but also to Booty Bay/Steemwheedle loss.

**Comment by Wolffenstein** [comment]
Fixed in rev 3391.
