### ISSUE TITLE
[NPC] Feero Ironhand does not respawn

### ISSUE THREAD

**Issue by Tereneckla** [Atlantiss/NetherwingBugtracker#7017]
[//]: # (Enclose links to things related to the bug using http://wowhead.com or any other TBC database.)
[//]: # (You can use screenshot ingame to visual the issue.)
[//]: # (Write your tickets according to the format:)
[//]: # ([Quest][Azuremyst Isle] Red Snapper - Very Tasty!)
[//]: # ([NPC] Magistrix Erona)
[//]: # ([Spell][Mage] Fireball)
[//]: # ([Npc][Drop] Ghostclaw Lynx)
[//]: # ([Web] Armory doesnt work)
[//]: # (To find server revision type `.server info` command in the game chat.)

**Description**: [Feero Ironhand](https://classic.wowhead.com/npc=4484/feero-ironhand) who gives the quest https://classic.wowhead.com/quest=976/supplies-to-auberdine is not respawning.

He is respawning just fine on PTR, same revision

**Current behaviour**: Waited 20 minutes and ran his escort path, he is not in sight.

**Expected behaviour**: Respawns.

**Server Revision**: 3376

**Comment by Tereneckla** [comment]
In the same vein, [Shay Leafrunner](https://classic.wowhead.com/npc=7774/shay-leafrunner#comments) also is not respawning.

**Comment by Evolvee** [comment]
thats just a missing core function for SAI escorts... there is no way to check for the player to be in vicinity of the NPC outside of using performance-heavy range checks every few seconds

**Comment by Godmatik** [comment]
Can't reproduce it, and in past year's two servers never had a request to reset either Feero or Shay (also I failed the quest for her and she despawned just fine)
Probably has been fixed/hackfixed at some point. But will reopen if I hear of it again.
