### ISSUE TITLE
[Spell][Warrior] Intimidating Shout don't share diminishing returns with other fears

### ISSUE THREAD

**Issue by 4egito** [Atlantiss/NetherwingBugtracker#7018]
[//]: # (Enclose links to things related to the bug using http://wowhead.com or any other TBC database.)
[//]: # (You can use screenshot ingame to visual the issue.)
[//]: # (Write your tickets according to the format:)
[//]: # ([Quest][Azuremyst Isle] Red Snapper - Very Tasty!)
[//]: # ([NPC] Magistrix Erona)
[//]: # ([Spell][Mage] Fireball)
[//]: # ([Npc][Drop] Ghostclaw Lynx)
[//]: # ([Web] Armory doesnt work)
[//]: # (To find server revision type `.server info` command in the game chat.)

**Description**: 
Intimidating Shout dont share diminishing returns with other fears (check video)
**Current behaviour**:
https://drive.google.com/file/d/1MGqevOj7xFV4hFKsxDRZ_wBDFYCo4hlA/view?usp=sharing
As you can see after second fear from warlock i get full Intimidating Shout...
**Expected behaviour**: 
Intimidating Shout **should** share diminishing returns with other fears
**Server Revision**:

**Comment by Wolffenstein** [comment]
Right now it's the same group as triggered stuns. Any proof it should be fear instead?

**Comment by 4egito** [comment]
https://classic.wowhead.com/spell=5246/intimidating-shout 
http://tbc.cavernoftime.com/spell=5246
Vanilla + TBC -> **Effect #2 | Apply Aura: Mod Fear**
https://wow.gamepedia.com/Intimidating_Shout -> Here is the spell in wiki with whole change log which says [Fear Effect](https://wow.gamepedia.com/Fear_effect)
I hope that will help...

**Comment by 4egito** [comment]
![image](https://user-images.githubusercontent.com/52432938/83977520-af5b0880-a909-11ea-9aae-30c6bbfd6652.png)
Also in that note from the links above i see the mechanic type: **"Fleeing"** but in the video i'm staying 8 seconds in the same place... Maybe because at the moment the spell counters as stun.

**Comment by raethkcj** [comment]
Check that Effect #1 Trigger Spell, it should say stun. Intimidating Shout has 2 effects: It stuns the target it's used on, and fears anyone else in range that's not being targeted.

**Comment by 4egito** [comment]
**Intimidating Shout is a core warrior ability learned at level 52. This shout is a Fear AoE special which lasts 8 seconds. It causes the target to become incapacitated for 8 seconds (any damage will break it). At the same time, it causes 5 other enemies within 10 yards to run away randomly; this fear is not as easy to break as the primary target's.** 
source: https://wowwiki.fandom.com/wiki/Intimidating_Shout
my bad

**Comment by 4egito** [comment]
![image](https://user-images.githubusercontent.com/52432938/87733115-80249a80-c7d7-11ea-9de9-c9ce20aaa4c9.png)
https://youtu.be/3tREJtTzgH4?t=20 This is vanilla video but you can see how undead rogue uses "Will of forsaken" and removes the effect from "Intimidating shout" which is being cast directly on him. If the effect is stun then how it was removed by undead racial?
![image](https://user-images.githubusercontent.com/52432938/87733269-04771d80-c7d8-11ea-943c-1334d8aa8fc1.png)
Also there is link for Intimidating shout which shows patch changes so that spell should work in TBC in the same way:
https://wowwiki.fandom.com/wiki/Intimidating_Shout
