### ISSUE TITLE
[NPC][Spell] Emissary of Hate's Flame Wave should have a cast time

### ISSUE THREAD

**Issue by raethkcj** [Atlantiss/NetherwingBugtracker#7019]
[//]: # (Enclose links to things related to the bug using http://wowhead.com or any other TBC database.)
[//]: # (You can use screenshot ingame to visual the issue.)
[//]: # (Write your tickets according to the format:)
[//]: # ([Quest][Azuremyst Isle] Red Snapper - Very Tasty!)
[//]: # ([NPC] Magistrix Erona)
[//]: # ([Spell][Mage] Fireball)
[//]: # ([Npc][Drop] Ghostclaw Lynx)
[//]: # ([Web] Armory doesnt work)
[//]: # (To find server revision type `.server info` command in the game chat.)

**Description**: 
Emissary of Hate (https://tbc-twinhead.twinstar.cz/?npc=25003) has an ability called Flame Wave. This ability has 2 components, a casted spell (https://tbc-twinhead.twinstar.cz/?spell=38607) and a triggered spell effect (https://tbc-twinhead.twinstar.cz/?spell=38611).

**Current behaviour**:
He instantly casts the trigger effect, giving players no time to interrupt or move out of the way.

**Expected behaviour**: 
First he uses the Flame Wave with a 3 second cast time, which then triggers the damage effect on the ground.

**Server Revision**: 
3376

**Comment by Wolffenstein** [comment]
Fixed in rev 3386.
