### ISSUE TITLE
[Quest] Ashenvale hunt

### ISSUE THREAD

**Issue by asatorrr** [Atlantiss/NetherwingBugtracker#702]
[//]: # (Enclose links to things related to the bug using http://wowhead.com or any other TBC database.)
[//]: # (You can use screenshot ingame to visual the issue.)
[//]: # (Write your tickets according to the format:)
[//]: # ([Quest][Azuremyst Isle] Red Snapper - Very Tasty!)
[//]: # ([NPC] Magistrix Erona)
[//]: # ([Spell][Mage] Fireball)
[//]: # ([Npc][Drop] Ghostclaw Lynx)
[//]: # ([Web] Armory doesnt work)

**Description**: I picked up the quest, either from TB or camp t, cant remember which, and had to turn it in twice. once got me experience and gold, the second reputation.

[https://imgur.com/a/3tuLZkT](url)
**Current behaviour**:

**Expected behaviour**: 

**Server Revision**:

**Comment by aresbrutus** [comment]
Working as intended. 1 is a quest to lead you there, the other opens up the 3 mob drops related to the hunt.
