### ISSUE TITLE
[General][Chat] Ignore feature doesn't prevent Yell messages

### ISSUE THREAD

**Issue by raethkcj** [Atlantiss/NetherwingBugtracker#7020]
[//]: # (Enclose links to things related to the bug using http://wowhead.com or any other TBC database.)
[//]: # (You can use screenshot ingame to visual the issue.)
[//]: # (Write your tickets according to the format:)
[//]: # ([Quest][Azuremyst Isle] Red Snapper - Very Tasty!)
[//]: # ([NPC] Magistrix Erona)
[//]: # ([Spell][Mage] Fireball)
[//]: # ([Npc][Drop] Ghostclaw Lynx)
[//]: # ([Web] Armory doesnt work)
[//]: # (To find server revision type `.server info` command in the game chat.)

**Description**: 
![image](https://user-images.githubusercontent.com/7716908/83984233-c2fe7300-a8f9-11ea-88d1-287854ad92f5.png)

**Current behaviour**:
Yell messages from ignored players still show up in chat.

**Expected behaviour**:
They don't.

**Server Revision**: 
3376

**Comment by Tereneckla** [comment]
That is weird, cause it worked for me.

**Comment by duzyizly** [comment]
addon?

**Comment by Tereneckla** [comment]
Just chatter for anything chat related, but that shouldn't change anything to ignore

**Comment by veekk** [comment]
It's not only for /y, sometimes it's happening even with /s /w /ra /bg /g whatever, never had this issue on other servers with the same add-on pack, seems like /ignore a bit broken

**Comment by Wolffenstein** [comment]
Fixed in rev 3379.
