### ISSUE TITLE
[Quest] The Deserters - Combat Flag stays after fight with Balos Jacken

### ISSUE THREAD

**Issue by Tereneckla** [Atlantiss/NetherwingBugtracker#7023]
[//]: # (Enclose links to things related to the bug using http://wowhead.com or any other TBC database.)
[//]: # (You can use screenshot ingame to visual the issue.)
[//]: # (Write your tickets according to the format:)
[//]: # ([Quest][Azuremyst Isle] Red Snapper - Very Tasty!)
[//]: # ([NPC] Magistrix Erona)
[//]: # ([Spell][Mage] Fireball)
[//]: # ([Npc][Drop] Ghostclaw Lynx)
[//]: # ([Web] Armory doesnt work)
[//]: # (To find server revision type `.server info` command in the game chat.)

**Description**: Balos Jacken turns friendly on low life to turn the quest in.
https://classic.wowhead.com/quest=1286/the-deserters

**Current behaviour**: Combat Flag stays after he turns friendly.

**Expected behaviour**: Combat Flag gets cleared after he turns friendly.

**Server Revision**: 3376

**Comment by Wolffenstein** [comment]
Fixed in rev 3382.
