### ISSUE TITLE
[Core][AI][Maps] Incorrect syncing between server and client of player and mob position

### ISSUE THREAD

**Issue by H4Xx0R-PC** [Atlantiss/NetherwingBugtracker#7025]
[//]: # (Enclose links to things related to the bug using http://wowhead.com or any other TBC database.)
[//]: # (You can use screenshot ingame to visual the issue.)
[//]: # (Write your tickets according to the format:)
[//]: # ([Quest][Azuremyst Isle] Red Snapper - Very Tasty!)
[//]: # ([NPC] Magistrix Erona)
[//]: # ([Spell][Mage] Fireball)
[//]: # ([Npc][Drop] Ghostclaw Lynx)
[//]: # ([Web] Armory doesnt work)
[//]: # (To find server revision type `.server info` command in the game chat.)

**Description**: 
There seems to be issues with the syncing of player and mob positions between the server and client. Mobs are not standing where they are supposed to be. Because of this you cannot sometimes melee or cast a spell to a mob when it's right in your face.

**Current behaviour**:
https://streamable.com/u5lxz9 - The first clip (on the test realm) shows this issue. At the end of the clip you can see that the mob parries my attack from behind while it's fleeing. This could be a separate bug or related to this one.

https://streamable.com/q8n8uf - The second clip (on the live realm) shows this issue again. The player cannot kill the mob while looking at it. Only after the player turns around is he able to kill it.

**Expected behaviour**: 
Mob and player positions should be synced properly between the server and client.

**Server Revision**: 
Live and Test realm (both rev 3377).

**Comment by Wolffenstein** [comment]
Should be fixed after restart.
