### ISSUE TITLE
[Quest][Item] Draconic for Dummies should only drop while on quest

### ISSUE THREAD

**Issue by raethkcj** [Atlantiss/NetherwingBugtracker#7026]
[//]: # (Enclose links to things related to the bug using http://wowhead.com or any other TBC database.)
[//]: # (You can use screenshot ingame to visual the issue.)
[//]: # (Write your tickets according to the format:)
[//]: # ([Quest][Azuremyst Isle] Red Snapper - Very Tasty!)
[//]: # ([NPC] Magistrix Erona)
[//]: # ([Spell][Mage] Fireball)
[//]: # ([Npc][Drop] Ghostclaw Lynx)
[//]: # ([Web] Armory doesnt work)
[//]: # (To find server revision type `.server info` command in the game chat.)

**Description**:
The eight pages of Draconic for Dummies are required for the quest The Only Prescription. https://tbc-twinhead.twinstar.cz/?quest=8620

**Current behaviour**:
Page 3 drops from Hederine Slayer and Hederine Initiate without being on the quest. It's possible/likely that other pages drop as well.
![image](https://user-images.githubusercontent.com/7716908/84161478-f1cd3400-aa34-11ea-9f39-448e9af16ecc.png)

**Expected behaviour**: 
Pages don't drop unless you are on the quest.

**Server Revision**: 
3377

**Comment by duzyizly** [comment]
Found the same issue with Wavethrasher Scales
https://tbcdb.com/?item=20087
Objective of
https://tbcdb.com/?quest=8231
The item drop even if you don't have the current quest (this is hunter quest and I'm playing warlock here on screenshot).
Rev 3377 PTR, So not sure if random bug or some core issue.

![WoWScrnShot_061020_113810](https://user-images.githubusercontent.com/43931626/84252467-e6e6d200-ab0e-11ea-967c-3532533178c8.jpg)

**Comment by Wolffenstein** [comment]
Fixed in rev 3386.
