### ISSUE TITLE
Grand Warlock Alythess is incorrectly meleeing the Warlock tank.

### ISSUE THREAD

**Issue by franticx187** [Atlantiss/NetherwingBugtracker#7028]
**Description**: 
Grand Warlock Alythess is incorrectly meleeing the Warlock tank. 

**Current behaviour**:
Meleeing

**Expected behaviour**: 
Casting

**Server Revision**:  3377

![melee](https://user-images.githubusercontent.com/44210210/84464094-92903f00-ac41-11ea-8e84-25387fc12973.png)

**Comment by duzyizly** [comment]
Nether protection again? ^^
https://github.com/Atlantiss/NetherwingBugtracker/issues/6861

**Comment by Wolffenstein** [comment]
You really need to figure out what interaction causes her to go "melee mode". I patched stuff like Nether Protection so I don't know what else could do that.

**Comment by franticx187** [comment]
Our warlock doesn't have nether protection at all, he's deep soul link. I believe he got into melee range during Phase 2 to clear his fire debuff. Should she still melee if she's in melee range?

**Comment by Wolffenstein** [comment]
If there's a pause between casts she might. I think I will just disable her melee entirely.

**Comment by Wolffenstein** [comment]
Fixed in rev 3378.
