### ISSUE TITLE
[Spell] [Hunter] Pet Skill Screech incorrect autocast behaviour

### ISSUE THREAD

**Issue by Talthos** [Atlantiss/NetherwingBugtracker#7029]
[//]: # (Enclose links to things related to the bug using http://wowhead.com or any other TBC database.)
[//]: # (You can use screenshot ingame to visual the issue.)
[//]: # (Write your tickets according to the format:)
[//]: # ([Quest][Azuremyst Isle] Red Snapper - Very Tasty!)
[//]: # ([NPC] Magistrix Erona)
[//]: # ([Spell][Mage] Fireball)
[//]: # ([Npc][Drop] Ghostclaw Lynx)
[//]: # ([Web] Armory doesnt work)
[//]: # (To find server revision type `.server info` command in the game chat.)

**Description**: 
[Screech](https://wow.gamepedia.com/index.php?title=Screech_(pet)&oldid=1564169) isn't being used correctly by hunter pets.

**Current behaviour**:
Hunter pet delays recasting Screech until the debuff has fallen off the main target.

**Expected behaviour**: 
As long as the pet has Focus available to cast it with, Screech should be cast repeatedly if set to autocast (the GCD means that Screech has an 'effective cooldown' of 1.5 seconds).

**Server Revision**: 
3377

[Wowhead link to a reply that directly mentions Screech only being affected by the GCD](https://www.wowhead.com/forums&topic=12768#p255336)

[Archived Petopia link to the pre-WotLK pet skills, including Screech](http://web.archive.org/web/20080619085357/http://petopia.brashendeavors.net/html/skills/skills_compare.php)

**Comment by Wolffenstein** [comment]
Fixed in rev 3378.
