### ISSUE TITLE
[Spell][Druid][Paladin] MotW doesn´t stack with Palas Devotion Aura

### ISSUE THREAD

**Issue by toki90** [Atlantiss/NetherwingBugtracker#703]
**Description**: 
Can´t buff Paladins MotW that have Devotion Aura active.

**Current behaviour**:
Gives you error message "A more powerful spell is already active". (https://imgur.com/R02Po5t)

**Expected behaviour**: 
Should stack.

**Server Revision**:

**Comment by toki90** [comment]
Seems to be the same with any buffs that adds armor.

https://github.com/Atlantiss/NetherwingBugtracker/issues/390
https://github.com/Atlantiss/NetherwingBugtracker/issues/198

**Comment by Wolffenstein** [comment]
Fixed in rev 2067.
