### ISSUE TITLE
[Quest] The Lich, Ras Frostwhisper

### ISSUE THREAD

**Issue by Tereneckla** [Atlantiss/NetherwingBugtracker#7030]
[//]: # (Enclose links to things related to the bug using http://wowhead.com or any other TBC database.)
[//]: # (You can use screenshot ingame to visual the issue.)
[//]: # (Write your tickets according to the format:)
[//]: # ([Quest][Azuremyst Isle] Red Snapper - Very Tasty!)
[//]: # ([NPC] Magistrix Erona)
[//]: # ([Spell][Mage] Fireball)
[//]: # ([Npc][Drop] Ghostclaw Lynx)
[//]: # ([Web] Armory doesnt work)
[//]: # (To find server revision type `.server info` command in the game chat.)

**Description**: 
Quest item/RP is not scripted.
That person saying the channel takes 10 seconds sadly can't count. The channel lasts 20 seconds and it does so currently.

**Current behaviour**:
Human Head of Ras Frostwhisper is in Lich Ras Frostwhisper loot table
Using the quest item does not turn him human.

**Expected behaviour**:
https://youtu.be/_hhQWZE87os?t=60
https://classic.wowhead.com/quest=5466/the-lich-ras-frostwhisper#comments
![image](https://user-images.githubusercontent.com/50233983/84578811-d5c8ea00-adc8-11ea-9f53-577cb8e093d2.png)
![image](https://user-images.githubusercontent.com/50233983/84578824-f133f500-adc8-11ea-9675-04f12206bc3e.png)

Use Soulbound Keepsake to cast Boon of Life on Ras Frostwhisper.
After the channel is done he becomes human, neutral, unattackable and combat ends.
At the same time of the transformation he yells: "NO!", a second later: "THIS CANNOT BE!!".
Another second later he becomes aggressive.
Human Ras Frostwhisper has the same abilities as Lich.
Human Ras Frostwhisper has Human Head of Ras Frostwhisper added to his loot table.

**Server Revision**: 3377

**Comment by Wolffenstein** [comment]
Fixed in rev 3378.
