### ISSUE TITLE
[NPC][Spell] Lake Spirit's Water Bolt ability should be interruptable

### ISSUE THREAD

**Issue by raethkcj** [Atlantiss/NetherwingBugtracker#7031]
[//]: # (Enclose links to things related to the bug using http://wowhead.com or any other TBC database.)
[//]: # (You can use screenshot ingame to visual the issue.)
[//]: # (Write your tickets according to the format:)
[//]: # ([Quest][Azuremyst Isle] Red Snapper - Very Tasty!)
[//]: # ([NPC] Magistrix Erona)
[//]: # ([Spell][Mage] Fireball)
[//]: # ([Npc][Drop] Ghostclaw Lynx)
[//]: # ([Web] Armory doesnt work)
[//]: # (To find server revision type `.server info` command in the game chat.)

**Description**: 
Lake Spirit (npc 17153) has ability Water Bolt (spell 34425) that should be interruptable.

https://www.wowhead.com/npc=17153/lake-spirit#comments:id=131094
> They are also immune to their own waterbolt spell, so warriors should avoid spell reflection and **use pummel/shield bash** instead. :)

**Current behaviour**:
My kick ability lands, but does not interrupt Water Bolt.
![image](https://user-images.githubusercontent.com/7716908/84599722-cb930400-ae39-11ea-9430-0153c994e126.png)

**Expected behaviour**: 
Water Bolt should be interruptable.

**Server Revision**: 
3377

**Comment by Wolffenstein** [comment]
Fixed in rev 3379.
