### ISSUE TITLE
[Spell][Paladin] Casting a greater Blessing on a Warlock doesnt buff Enslaved pets

### ISSUE THREAD

**Issue by Tankdiehutte** [Atlantiss/NetherwingBugtracker#7034]
**Description**: Usually when a paladin buffs a warrior with a greater blessing, the buff is also applied on the hunterpets and if he buffs a warlock he buffs the warlocks demon. 

**Current behaviour**: If the warlocks demon is an enslaved one this doesnt happen.

**Expected behaviour**: Enslaved pets should get buffed by greater blessings casted on the warlock.

**Server Revision**: 3382

**Comment by Wolffenstein** [comment]
I had to disable it for now, since buffs like pally blessings use the same targetting type as stuff like Tremor Totem. Tremor Totem was being a dick and removing enslave from demons (because enslave is classified as Charm). I need to figure out how to make it not remove actual beneficial charms

**Comment by Tankdiehutte** [comment]
Actually the tremortotem doesnt remove the sleep from Anetheron (2nd boss mount hyjal). Is that classified as Stun or could there be the answer ?
Another idea could be to make the warlock (or priest, in case of mindcontrol) apply a buff on the target just like the 2nd boss in shadowlabs, instead of giving the target a debuff.

**Comment by Godmatik** [comment]
The issue here is part of a bigger problem with buffing pets.
Closing this and moving discussion to #4243
