### ISSUE TITLE
[Hunter][Spell] Tame Beast and pet gender

### ISSUE THREAD

**Issue by Talthos** [Atlantiss/NetherwingBugtracker#7035]
[//]: # (Enclose links to things related to the bug using http://wowhead.com or any other TBC database.)
[//]: # (You can use screenshot ingame to visual the issue.)
[//]: # (Write your tickets according to the format:)
[//]: # ([Quest][Azuremyst Isle] Red Snapper - Very Tasty!)
[//]: # ([NPC] Magistrix Erona)
[//]: # ([Spell][Mage] Fireball)
[//]: # ([Npc][Drop] Ghostclaw Lynx)
[//]: # ([Web] Armory doesnt work)
[//]: # (To find server revision type `.server info` command in the game chat.)

**Description**: 
Tame Beast isn't retaining the gender of the beast being tamed.

**Current behaviour**:
Upon taming a beast, the pet inexplicably defaults to 'Neutrum/Unknown', regardless of the original gender of the beast being tamed.

Case in point: Rak'shiri, a tameable rare spawn cat from Winterspring that starts off as a female prior to taming; she inexplicably stops having a gender at all, after being tamed by a hunter.

**Expected behaviour**: 
Any beast should retain its original starting gender upon being tamed, whether male, female, or otherwise.

**Server Revision**: 
3382

[Wowpedia page with a list of 'useful macros', including one that can check the gender of a target](https://wow.gamepedia.com/Useful_macros#Target.27s_Gender)

[Wowpedia page that details the API function that handles checking the gender of a target](https://wow.gamepedia.com/API_UnitSex)

[Wowhead forum post from February 2008, that directly mentions pet gender and one method of checking it](https://www.wowhead.com/forums&topic=11040)

[OwnedCore forum post from February 2008, which also talks about checking pet gender](https://www.ownedcore.com/forums/world-of-warcraft/world-of-warcraft-guides/91549-hunter-pet-gender.html)

**Comment by Wolffenstein** [comment]
Fixed in rev 3433 (will require re-taming).
