### ISSUE TITLE
[Quest] Teron Gorefiend, I am

### ISSUE THREAD

**Issue by Tereneckla** [Atlantiss/NetherwingBugtracker#7036]
[//]: # (Enclose links to things related to the bug using http://wowhead.com or any other TBC database.)
[//]: # (You can use screenshot ingame to visual the issue.)
[//]: # (Write your tickets according to the format:)
[//]: # ([Quest][Azuremyst Isle] Red Snapper - Very Tasty!)
[//]: # ([NPC] Magistrix Erona)
[//]: # ([Spell][Mage] Fireball)
[//]: # ([Npc][Drop] Ghostclaw Lynx)
[//]: # ([Web] Armory doesnt work)
[//]: # (To find server revision type `.server info` command in the game chat.)

**Description**: 
![image](https://user-images.githubusercontent.com/50233983/85019879-cc94a000-b16f-11ea-80eb-fddf8526879e.png)

**Current behaviour**: You still have control of Teron Gorefiend after killing Karsius

**Expected behaviour**: You stop controlling Teron Gorefiend after killing Karsius

**Server Revision**: 3385

**Comment by Wolffenstein** [comment]
Fixed in rev 3387.
