### ISSUE TITLE
[best-in-slot Trinket][Item] Skull of Gul'dan - nonblizzlike cooldown sharing

### ISSUE THREAD

**Issue by Tweet1337** [Atlantiss/NetherwingBugtracker#7037]
**Description:** 
Skull of Gul'dan's on-use-haste-effect shares cooldown with on-use-spellpower-effects. 

If you use your Spellpower-Trinket a 20 second cooldown on Skull of Guldan is generated - if you use your Skull of Guldan a 20 second cooldown on the Spellpower-Trinket is generated. 

Normally it should be possible to activate both at the same time, because they dont have the same effect (haste <> spellpower).

**Sources:**
https://www.youtube.com/watch?v=cDvMZ2o6R2w
Minute 2:12 (in his Buffs) - it's TBC

https://de.wowhead.com/item=32483/der-sch%C3%A4del-des-guldan#english-comments
Von Patze (4,675 – 1·17·25) am 2007.06.30 (Patch 2.1.2)
Also this doesn't share cooldown with damage trinkets, so you can have both on same time.

Server Revision: 3385

**Comment by Wolffenstein** [comment]
It's blizzlike in 2.4.3 - it's the client blocking the usage, not the server.
