### ISSUE TITLE
[Spell][Paladin] Consecration broken since [3384] or [3389] 

### ISSUE THREAD

**Issue by Excinerus** [Atlantiss/NetherwingBugtracker#7038]
Terrain geometry is breaking consecration, i did botanica earlier and on seemingly continuous homogenous flat terrain, it will work on one spot and not do any damage when recast one meter to the side,  no LOS obstructions, just flat terrain.

it seems like a vertical line of sight issue, where the hazard is spawned a bit beneath the ground and thus deemed off LOS

**Comment by Tereneckla** [comment]
![image](https://user-images.githubusercontent.com/50233983/85102062-1b8c1500-b204-11ea-8adb-763b281ccaff.png)

![image](https://user-images.githubusercontent.com/50233983/85102104-39f21080-b204-11ea-862e-f453deba95a0.png)
Many spots on the slopes surrounding Sarennis

![image](https://user-images.githubusercontent.com/50233983/85102442-fa77f400-b204-11ea-8329-c8745769139c.png)

![image](https://user-images.githubusercontent.com/50233983/85102743-8ee25680-b205-11ea-962e-c8f970c629f2.png)

![image](https://user-images.githubusercontent.com/50233983/85102800-ac172500-b205-11ea-8f3c-ee906ffc5ed3.png)

![image](https://user-images.githubusercontent.com/50233983/85102841-c3561280-b205-11ea-8922-5408b28ca4f3.png)

![image](https://user-images.githubusercontent.com/50233983/85102886-db2d9680-b205-11ea-9591-c8662121daa6.png)

![image](https://user-images.githubusercontent.com/50233983/85102915-eb457600-b205-11ea-9517-6bb728425181.png)

![image](https://user-images.githubusercontent.com/50233983/85102966-0a440800-b206-11ea-879f-3774a4938a71.png)

![image](https://user-images.githubusercontent.com/50233983/85102995-18922400-b206-11ea-8379-64203c8d2199.png)

![image](https://user-images.githubusercontent.com/50233983/85103040-2f387b00-b206-11ea-9ab3-02b830098b33.png)

![image](https://user-images.githubusercontent.com/50233983/85103056-3a8ba680-b206-11ea-80c1-eab6c0fc1861.png)

![image](https://user-images.githubusercontent.com/50233983/85103311-b4bc2b00-b206-11ea-89eb-d7200ffb4d8f.png)

![image](https://user-images.githubusercontent.com/50233983/85103377-d3babd00-b206-11ea-8fec-e9ecf250472e.png)

![image](https://user-images.githubusercontent.com/50233983/85103401-de755200-b206-11ea-844b-b289ed31e8d5.png)

![image](https://user-images.githubusercontent.com/50233983/85103433-ef25c800-b206-11ea-9805-92ca0de97558.png)

![image](https://user-images.githubusercontent.com/50233983/85103454-f947c680-b206-11ea-88f9-692b623c7baa.png)

**Comment by Tereneckla** [comment]
![image](https://user-images.githubusercontent.com/50233983/85104099-3a8ca600-b208-11ea-9547-7576d520fcc7.png)

It's all over the Tempest Keep dungeons.

**Comment by Wolffenstein** [comment]
Fixed in rev 3390.
