### ISSUE TITLE
[Hunter] Multi-Shot targeting

### ISSUE THREAD

**Issue by x-x-x-x-x-x-x-x-x-x-x-x** [Atlantiss/NetherwingBugtracker#7039]
**Bug Description**: 
MS cannot chain to secondary targets that are out of range.
**Expected behaviour**: 
As a chain ability, it should be able to hit secondary targets that are out of range or within deadzone, but not those behind the hunter.
https://youtu.be/aL64YWN0134?t=338  
It was "fixed" [here](https://github.com/Atlantiss/NetherwingBugtracker/issues/3222) without any real proof provided.
**Server Revision**: 
3390

**Comment by Wolffenstein** [comment]
Fixed in rev 3391.
