### ISSUE TITLE
[NPC]Laughing sisters in Ashenvale do not give EXP.

### ISSUE THREAD

**Issue by queeb3** [Atlantiss/NetherwingBugtracker#704]
[//]: # (Enclose links to things related to the bug using http://wowhead.com or any other TBC database.)
[//]: # (You can use screenshot ingame to visual the issue.)
[//]: # (Write your tickets according to the format:)
[//]: # ([Quest][Azuremyst Isle] Red Snapper - Very Tasty!)
[//]: # ([NPC] Magistrix Erona)
[//]: # ([Spell][Mage] Fireball)
[//]: # ([Npc][Drop] Ghostclaw Lynx)
[//]: # ([Web] Armory doesn't work)
[https://imgur.com/a/2qwqWK0](https://imgur.com/a/2qwqWK0)
**Description**: 
When in Ashenvale and killing the NPC laughing sisters that are also tagged as pvp, you do not gain experience.
**Current behavior**:
No EXP gain on killing Laughing sisters
**Expected behavior**: 
Should gain EXP if within the level range.
**Server Revision**:

**Comment by totaemoeggerli** [comment]
[Laughing Sister](https://www.wowhead.com/npc=4054/laughing-sister)
[Keeper Ordanus](https://www.wowhead.com/npc=4273/keeper-ordanus) gives no XP too
the other two mobs in the area give XP (Cenarion Protector/Vindicator)
**Server Revision:** 2083

**Comment by Easyfraggy** [comment]
Duplicate https://github.com/Atlantiss/NetherwingBugtracker/issues/426#issuecomment-425627272
