### ISSUE TITLE
[Hunter][Spell] Flare and enemies with 'true' invisibility effects

### ISSUE THREAD

**Issue by Talthos** [Atlantiss/NetherwingBugtracker#7041]
[//]: # (Enclose links to things related to the bug using http://wowhead.com or any other TBC database.)
[//]: # (You can use screenshot ingame to visual the issue.)
[//]: # (Write your tickets according to the format:)
[//]: # ([Quest][Azuremyst Isle] Red Snapper - Very Tasty!)
[//]: # ([NPC] Magistrix Erona)
[//]: # ([Spell][Mage] Fireball)
[//]: # ([Npc][Drop] Ghostclaw Lynx)
[//]: # ([Web] Armory doesnt work)
[//]: # (To find server revision type `.server info` command in the game chat.)

**Description**: 
[Flare](https://www.wowhead.com/spell=1543/flare) is not immediately removing 'true' invisibility effects from hostiles.

**Current behaviour**:
Flare is not exposing enemies under the effects of a 'true' invisibility effect at all.

Video footage of current behaviour, tested against a Warp Stalker mob, which periodically uses a 'true' invisibility effect that lasts several seconds while out of combat:
[Youtube link](https://www.youtube.com/watch?v=ajBKyddKHeY)

**Expected behaviour**: 
If the Flare debuff itself lands on a hostile under the effects of a 'true' invisibility effect, it should immediately remove the invisibility effect, exposing them.

**Server Revision**: 
3385

[Patch 2.0.3 official notes, where Flare was specifically bugfixed to properly reveal Mages that use the "Invisibility" spell, which itself also uses a 'true' invisibility effect](https://wow.gamepedia.com/Patch_2.0.3#Bug_Fixes)

**Comment by Wolffenstein** [comment]
Flare removes auras with DISPEL_STEALTH and DISPEL_INVISIBILITY. Warp Stalkers' invisibility has DispelType = 0 (DISPEL_NONE) in client spell data, therefore Flare will not reveal them. Unless Blizzard changed them server-side only later on, I'm going to assume this is blizzlike and their invisibility is not considered removable.
