### ISSUE TITLE
[Hunter] Trap radius

### ISSUE THREAD

**Issue by x-x-x-x-x-x-x-x-x-x-x-x** [Atlantiss/NetherwingBugtracker#7043]
**Bug description**: 
Trigger radius of traps is lower than it should be.
**Expected behaviour**: 
[classic comparison](https://gitlab.com/lights-vengeance/issues/-/issues/220#note_298363523)
[bunch of videos](https://github.com/SunstriderEmu/BugTracker/issues/1699#issuecomment-574538453)
**Server Revision**: 
3392

**Comment by The14me** [comment]
What sunstrider core has to do with Netherwing/Kara?
Aside that...range looks fine to me 
https://imgur.com/a/k9K7ZJj

**Comment by x-x-x-x-x-x-x-x-x-x-x-x** [comment]
"Looke fine to me" XD good luck with that approach
