### ISSUE TITLE
[Spell/Item] Wand damage is being treated as physical

### ISSUE THREAD

**Issue by Tereneckla** [Atlantiss/NetherwingBugtracker#7044]
[//]: # (Enclose links to things related to the bug using http://wowhead.com or any other TBC database.)
[//]: # (You can use screenshot ingame to visual the issue.)
[//]: # (Write your tickets according to the format:)
[//]: # ([Quest][Azuremyst Isle] Red Snapper - Very Tasty!)
[//]: # ([NPC] Magistrix Erona)
[//]: # ([Spell][Mage] Fireball)
[//]: # ([Npc][Drop] Ghostclaw Lynx)
[//]: # ([Web] Armory doesnt work)
[//]: # (To find server revision type `.server info` command in the game chat.)

**Description**: 
#1377
#4582
https://github.com/Atlantiss/NetherwingBugtracker/issues/2879#issuecomment-441341848
#696

![image](https://user-images.githubusercontent.com/50233983/85199671-9717c000-b2f1-11ea-9ebf-7e604c34f0f0.png)
No curse of elements

![image](https://user-images.githubusercontent.com/50233983/85199715-055c8280-b2f2-11ea-8a15-3a62cc643eff.png)
curse of elements
**Current behaviour**:
Able to damage magic immune mobs (or with immunity to the damage type of the wand)
Affected by reductions to physical damage 
**Expected behaviour**: 
Not able to damage magic immune mobs (or with immunity to the damage type of the wand)
Not affected by physical damage reducing abilities

**Server Revision**: 3392

**Comment by Wolffenstein** [comment]
Proof that it should be magical? It has SpellSchoolMask = 1 (MASK_PHYSICAL).

**Comment by Tereneckla** [comment]
https://www.wowhead.com/npc=16491/mana-feeder#comments

Mana Feeder are immune to magic. They are also immune to wands.
Wands itself say they deal fire, frost, shadow, holy, nature, arcane damage.

https://classic.wowhead.com/item=16997/stormrager#comments:id=10187
Nature Wand being used against mob with nature weakness

**Comment by Evolvee** [comment]
wand definitely not should be magical, only the damage is magic

**Comment by Tereneckla** [comment]
I am just saying the damage should be magic (and at least be treated as the element the wand says it does)

**Comment by Drayo** [comment]
- On classic they get increased **Crit Chance** from **Agility** but do not scale with haste or RAP.

- On classic they benefit from stuff like Shadow Weaving or CoE, but NOT auras that specifically say "shadow SPELL damage".

- On Classic, mobs that are immune to fire damage are also immune to the damage of fire damage wands. On the other hand, the Draknoids with the vulnerability in BWL take increased damage from wands of the respective element.

**Comment by Wolffenstein** [comment]
Fixed in rev 3430.
