### ISSUE TITLE
[Raid][BT] Shadowmoon Houndmaster summon doesn't despawn on combat end

### ISSUE THREAD

**Issue by Tereneckla** [Atlantiss/NetherwingBugtracker#7045]
[//]: # (Enclose links to things related to the bug using http://wowhead.com or any other TBC database.)
[//]: # (You can use screenshot ingame to visual the issue.)
[//]: # (Write your tickets according to the format:)
[//]: # ([Quest][Azuremyst Isle] Red Snapper - Very Tasty!)
[//]: # ([NPC] Magistrix Erona)
[//]: # ([Spell][Mage] Fireball)
[//]: # ([Npc][Drop] Ghostclaw Lynx)
[//]: # ([Web] Armory doesnt work)
[//]: # (To find server revision type `.server info` command in the game chat.)

**Description**: [Shadowmoon Houndmaster](https://www.wowhead.com/npc=23018/shadowmoon-houndmaster) summons [Shadowmoon Riding Hound](https://www.wowhead.com/npc=23083/shadowmoon-riding-hound) when he engages combat.

**Current behaviour**: The riding hound doesn't despawn when combat ends, making them potentially stack up on multiple wipes.
https://www.youtube.com/watch?v=cHLUrddNPIc

**Expected behaviour**: He "mounts up" after combat, making the summoned hound despawn.

**Server Revision**: 3392

**Comment by Wolffenstein** [comment]
Fixed in rev 3393.
