### ISSUE TITLE
[NPC] [Enraged Air Spirit]  - Northern Ledge missing 16 Spawns

### ISSUE THREAD

**Issue by Drayo** [Atlantiss/NetherwingBugtracker#7046]
**Description**: There are a **lot** of missing spawns for Enraged Air Spirits in Shadowmoon Valley, mostly on the Northern ledges. (Marked Areas: https://i.imgur.com/F6WEME2.jpg)
This issue is pretty important because it affects the economy a lot, 16 missing high value mobs is kind of a lot. Especially if the Server has higher than blizzlike population.

**Current behaviour**: 

- The entire Northern Ledge only has **THREE** spawns on Netherwing.

- WoWhead Comments mention these mobs should be linked. in the sense that they will force respawn once their overall population is below a certain threshold. It is likely that these mobs have this due to them being Quest mobs for the TK pre-Quest.

**Expected behaviour**: 

- There should be NINETEEN spawns in the North.

- They should force respawn if their overall population is reduced too much.

**Source**: Retail+WoWhead

- https://youtu.be/8gjUrg0lMbI  -> Shows all spawns on the ledges on retail.

https://www.wowhead.com/npc=21060/enraged-air-spirit#comments
- Lots of comments mentioning the Northern area as a competitive spot to farm.
- Also one comment mentioning them respawning instantly on top of the player. if too many players are farming them.

**Server Revision**: 3392

**Comment by Wolffenstein** [comment]
Fixed in rev 3393.
