### ISSUE TITLE
[NPC] [Shadow Serpent] - Missing Visual

### ISSUE THREAD

**Issue by Drayo** [Atlantiss/NetherwingBugtracker#7047]
[//]: # (Enclose links to things related to the bug using http://wowhead.com or any other TBC database.)
[//]: # (You can use screenshot ingame to visual the issue.)
[//]: # (Write your tickets according to the format:)
[//]: # ([Quest][Azuremyst Isle] Red Snapper - Very Tasty!)
[//]: # ([NPC] Magistrix Erona)
[//]: # ([Spell][Mage] Fireball)
[//]: # ([Npc][Drop] Ghostclaw Lynx)
[//]: # ([Web] Armory doesnt work)
[//]: # (To find server revision type `.server info` command in the game chat.)

**Description**: These mobs should have a shadow aura effect around them.

**Current behaviour**: 

- The effect is missing on Netherwing. (https://i.imgur.com/xcTthT4.jpg)

**Expected behaviour**: 

- Should look like the picture (2007) on wowhead. (https://wow.zamimg.com/uploads/screenshots/normal/24487-shadow-serpent.jpg)

**Source**: https://www.wowhead.com/npc=23020/shadow-serpent#comments

**Server Revision**: 3392

**Comment by Wolffenstein** [comment]
Fixed in rev 3393.
