### ISSUE TITLE
[Spell][Rogue] Vexallus debuff not being removed by Cloak of Shadows

### ISSUE THREAD

**Issue by nevrozac** [Atlantiss/NetherwingBugtracker#7050]
**Description**: 
([Spell][Rogue] Cloak of Shadows) 
([NPC] Vexallus) ([NPC] Pure energy) 
Debuff placed on player during the fight with Vexallus is supposed to be removable by Cloak of Shadows according to the wiki: [x](https://wowwiki.fandom.com/wiki/Vexallus)
**Current behaviour**:
Nothing happens
**Expected behaviour**: 
Debuff is removed from rogue
**Server Revision**:

**Comment by Tereneckla** [comment]
https://youtu.be/vDY90B1a5GM?t=73

**Comment by NatsumeLily** [comment]
#6695

**Comment by Wolffenstein** [comment]
Fixed in rev 3407.
