### ISSUE TITLE
[NPC] [Shadow Labyrinth] - One Patrol before Vorpil does not move

### ISSUE THREAD

**Issue by Drayo** [Atlantiss/NetherwingBugtracker#7051]
[//]: # (Enclose links to things related to the bug using http://wowhead.com or any other TBC database.)
[//]: # (You can use screenshot ingame to visual the issue.)
[//]: # (Write your tickets according to the format:)
[//]: # ([Quest][Azuremyst Isle] Red Snapper - Very Tasty!)
[//]: # ([NPC] Magistrix Erona)
[//]: # ([Spell][Mage] Fireball)
[//]: # ([Npc][Drop] Ghostclaw Lynx)
[//]: # ([Web] Armory doesnt work)
[//]: # (To find server revision type `.server info` command in the game chat.)

**Description**: This Patrol does not move. https://i.imgur.com/h6IRLMo.jpg

**Current behaviour**: 

- They are not moving.

**Expected behaviour**: 

- They should move between two spots and kneel like the other groups.
Spot 1: https://i.imgur.com/QG0jmW9.jpg
Spot 2: https://i.imgur.com/QLzjYJ9.jpg

**Server Revision**: 3396

**Comment by Tereneckla** [comment]
They were moving before. Weird.

**Comment by Wolffenstein** [comment]
Fixed in rev 3412.
