### ISSUE TITLE
[NPC] [The Underbog] [HC] - Bog Giant aggro range

### ISSUE THREAD

**Issue by Drayo** [Atlantiss/NetherwingBugtracker#7053]
**Description**: The Aggro range of the Bog Giants seems to be too small.

**Current behaviour**: 

- I can get very close without pulling them. https://i.imgur.com/c5lGUot.jpg

This enables groups to always skip the two in front of Hungarfen. https://i.imgur.com/4PJxAu8.png

**Expected behaviour**: 

- The aggro range should be higher, preventing this skip. 

https://i.imgur.com/IH8YWlT.jpg - This is the distance of the spot, where you pass them on the right. At 30y you would always pull them when trying to pass. 

https://i.imgur.com/skxSgbS.png -It would put you at this range when pulling them normally. Which I think seems reasonable.

**Server Revision**: 3396

**Comment by Wolffenstein** [comment]
Fixed in rev 3402.
