### ISSUE TITLE
[NPC] Detection of NPCs in LBRS seems too high

### ISSUE THREAD

**Issue by Throndar** [Atlantiss/NetherwingBugtracker#7054]
[//]: # (Enclose links to things related to the bug using http://wowhead.com or any other TBC database.)
[//]: # (You can use screenshot ingame to visual the issue.)
[//]: # (Write your tickets according to the format:)
[//]: # ([Quest][Azuremyst Isle] Red Snapper - Very Tasty!)
[//]: # ([NPC] Magistrix Erona)
[//]: # ([Spell][Mage] Fireball)
[//]: # ([Npc][Drop] Ghostclaw Lynx)
[//]: # ([Web] Armory doesnt work)
[//]: # (To find server revision type `.server info` command in the game chat.)

**Description**: 
The NPCs in LBRS detect my lvl 70 rogue like he was lvl 60. I used to farm shards there on Alliance side with my human rogue and could easily sneak through everything without getting detected. Now on my orc rogue they detect me when i'm 10m away, although they are 15 level below me. I'm not sure wether it's a hitbox, race or recent update problem. Tested it with lvl 55-60 NPCs in Scholomance and there it's fine, they could only detect me at point blank range.
**Current behaviour**:
Level 70 orc rogue gets detected in stealth by NPCs 15 levels below (LBRS) far too easily. Feels like level 60 rogue.
**Expected behaviour**: 
Like some weeks ago, sneaking past them undetected should be possible.

**Server Revision**: 
3400

**Comment by Wolffenstein** [comment]
Should be resolved in rev 3401.
