### ISSUE TITLE
[NPC] Wretched Hooligan

### ISSUE THREAD

**Issue by xycz** [Atlantiss/NetherwingBugtracker#7055]
**Description**: [Wretched Hooligan](https://tbcdb.com/?npc=16162) can not be killed for credit required to complete the quest [Situation at Sunsail Anchorage](https://tbcdb.com/?quest=8892) which is required to start the quest chain beginning with [Farstrider Retreat](https://tbcdb.com/?quest=9359). [Wretched Thug](https://tbcdb.com/?npc=15645) which is the other required quest credit seem to be working.

**Current behaviour**: When engaged in combat the NPC runs a specific path and then resets after a few seconds.

**Expected behaviour**: [Wretched Hooligan](https://tbcdb.com/?npc=16162) should not reset after a few seconds but instead find a path to the engaging player and begin using its attack rotation.

**Server Revision**: 3400

**Video capture of issue**: https://www.youtube.com/watch?v=gx7oodexcow

**Comment by xycz** [comment]
Also tested on PTR (Server Revision: 3396) where it seems to be working. The issue seems to occur somewhere between 3396-3400.

**Comment by Wolffenstein** [comment]
Fixed in rev 3402.
