### ISSUE TITLE
[Npc][Drop] Scourgestones

### ISSUE THREAD

**Issue by Throndar** [Atlantiss/NetherwingBugtracker#7056]
[//]: # (Enclose links to things related to the bug using http://wowhead.com or any other TBC database.)
[//]: # (You can use screenshot ingame to visual the issue.)
[//]: # (Write your tickets according to the format:)
[//]: # ([Quest][Azuremyst Isle] Red Snapper - Very Tasty!)
[//]: # ([NPC] Magistrix Erona)
[//]: # ([Spell][Mage] Fireball)
[//]: # ([Npc][Drop] Ghostclaw Lynx)
[//]: # ([Web] Armory doesnt work)
[//]: # (To find server revision type `.server info` command in the game chat.)

**Description**: 
While farming darkrunes and shards in Scholomance i was able to loot all 3 kind of scourgestones without having the Argent Dawn Commission (https://classic.wowhead.com/item=12846/argent-dawn-commission) equiped.
https://classic.wowhead.com/item=12840/minions-scourgestone
https://classic.wowhead.com/item=12841/invaders-scourgestone
https://classic.wowhead.com/item=12843/corruptors-scourgestone
**Current behaviour**:
Scourgestones can be seen and looted without having the Argent Dawn Commission or a similar item equiped.
**Expected behaviour**: 
Scourgestones should only be visible and lootable when having the Argent Dawn Commission or a similar item equiped.
**Server Revision**: 
3400

**Comment by Wolffenstein** [comment]
Fixed in rev 3412.
