### ISSUE TITLE
[Quest][Warlock][Dungeon] Dreadsteed of Xoroth

### ISSUE THREAD

**Issue by bekonja** [Atlantiss/NetherwingBugtracker#7057]
[//]: # (Enclose links to things related to the bug using http://wowhead.com or any other TBC database.)
[//]: # (You can use screenshot ingame to visual the issue.)
[//]: # (Write your tickets according to the format:)
[//]: # ([Quest][Azuremyst Isle] Red Snapper - Very Tasty!)
[//]: # ([NPC] Magistrix Erona)
[//]: # ([Spell][Mage] Fireball)
[//]: # ([Npc][Drop] Ghostclaw Lynx)
[//]: # ([Web] Armory doesnt work)
[//]: # (To find server revision type `.server info` command in the game chat.)

**Description**: 
https://classic.wowhead.com/quest=7631/dreadsteed-of-xoroth

**Current behaviour**:
Whole DM event is unscripted so warlock can abuse it summoning horses and loot them for easy dark runes farm.

**Expected behaviour**: 
https://youtu.be/jNe_U7WNtdU?t=1297

**Server Revision**: 
3400

**Comment by Tereneckla** [comment]
Correct, you currently can summon the Dreadsteed with the Xorothian Glyph over and over, without doing any other part of the even.

However it drops Demonic Runes (the non-tradeable runes) as it should.

**Comment by The14me** [comment]
Just add this report to the big DM issues topic. That thing need to be stripped and re-written from 0.

**Comment by EtheriousNW** [comment]
Fixed a long time ago, event itself is still stock garbage tho.
