### ISSUE TITLE
[NPC][Blood Furnace] Last boss doesn't cast AoE

### ISSUE THREAD

**Issue by Minimix186** [Atlantiss/NetherwingBugtracker#7059]
[//]: # (Enclose links to things related to the bug using http://wowhead.com or any other TBC database.)
[//]: # (You can use screenshot ingame to visual the issue.)
[//]: # (Write your tickets according to the format:)
[//]: # ([Quest][Azuremyst Isle] Red Snapper - Very Tasty!)
[//]: # ([NPC] Magistrix Erona)
[//]: # ([Spell][Mage] Fireball)
[//]: # ([Npc][Drop] Ghostclaw Lynx)
[//]: # ([Web] Armory doesnt work)
[//]: # (To find server revision type `.server info` command in the game chat.)

**Description**: 

The last boss is meant to shout "Come close and burn", then cast a huge AoE fire nova type spell.

**Current behaviour**:

No spell is cast, the emote goes off, but no spell

**Expected behaviour**: 

AoE fire nova type ability after emote.

**Server Revision**: 

23/6/20

**Comment by Tereneckla** [comment]
![image](https://user-images.githubusercontent.com/50233983/85420667-cd647200-b573-11ea-9d91-987cc0312189.png)

**Comment by Wolffenstein** [comment]
Fixed in rev 3407.
