### ISSUE TITLE
[Quest] [NPC] Escape from the catacombs

### ISSUE THREAD

**Issue by nycheia** [Atlantiss/NetherwingBugtracker#706]
https://cdn.discordapp.com/attachments/395987464470396929/494613273547898880/unknown.png

**Description**: 
At the end of the quest, escape from the catacombs, it spawns two mobs. The Mummified Headhunter attacked the escort npc correctly.

**Current behaviour**:
The second mob, Shadowpine Oracle, did not attack the escort npc or engage in combat. It did the heal/life swap spell on the headhunter when it was low health, and then ran away in fear. It did not attack at any point.

**Expected behaviour**: 
Its supposed to engage in combat with the escort npc, and attack it. The heal was correct though.

**Server Revision**: 
2065

**Comment by tcberk12** [comment]
retail tbc video evidence: https://www.youtube.com/watch?v=_R5IaZJoUxw

Starts at about 2:40

**Comment by Tenoutoften** [comment]
I had it the other way around... Shadowpine Oracle worked correctly but the mummified did not

**Comment by aresbrutus** [comment]
https://github.com/Atlantiss/NetherwingBugtracker/issues/3678
