### ISSUE TITLE
[Blood Furnace]No speed boost in "Green" tunnel after last boss

### ISSUE THREAD

**Issue by Minimix186** [Atlantiss/NetherwingBugtracker#7060]
[//]: # (Enclose links to things related to the bug using http://wowhead.com or any other TBC database.)
[//]: # (You can use screenshot ingame to visual the issue.)
[//]: # (Write your tickets according to the format:)
[//]: # ([Quest][Azuremyst Isle] Red Snapper - Very Tasty!)
[//]: # ([NPC] Magistrix Erona)
[//]: # ([Spell][Mage] Fireball)
[//]: # ([Npc][Drop] Ghostclaw Lynx)
[//]: # ([Web] Armory doesnt work)
[//]: # (To find server revision type `.server info` command in the game chat.)

**Description**: 

There should be a speed boost after the last boss, to boost you down the green tunnel

**Current behaviour**:

No speed boost

**Expected behaviour**: 

A speed boost

**Server Revision**: 

23/6/20

**Comment by Wolffenstein** [comment]
Source?

**Comment by Tereneckla** [comment]
https://youtu.be/Hj9WSkeTP5Y?t=368
compare that tbc video to a later one
https://youtu.be/OqAjmGTk1BM?t=551

In the later patch there is a red thingy, that gives a buff to turn the character red, give a trail and movement speed.
All of that is absent in the tbc video
