### ISSUE TITLE
[NPC][Mudfin Frenzy] Too many spawns located around Coilfang Reservoir

### ISSUE THREAD

**Issue by Minimix186** [Atlantiss/NetherwingBugtracker#7061]
[//]: # (Enclose links to things related to the bug using http://wowhead.com or any other TBC database.)
[//]: # (You can use screenshot ingame to visual the issue.)
[//]: # (Write your tickets according to the format:)
[//]: # ([Quest][Azuremyst Isle] Red Snapper - Very Tasty!)
[//]: # ([NPC] Magistrix Erona)
[//]: # ([Spell][Mage] Fireball)
[//]: # ([Npc][Drop] Ghostclaw Lynx)
[//]: # ([Web] Armory doesnt work)
[//]: # (To find server revision type `.server info` command in the game chat.)

**Description**: 

From what i recall, they should only spawn 1 per location

**Current behaviour**:

1-4 are spawning in the location

https://i.imgur.com/7V7AK9B.jpg

**Expected behaviour**: 

A lot less spawning

**Server Revision**: 

23/6/20

**Comment by The14me** [comment]
https://www.wowhead.com/npc=18212/mudfin-frenzy#comments:id=105619
"They always come in groups of four"
