### ISSUE TITLE
[Snake Trap][Hunter] Snake trap rework

### ISSUE THREAD

**Issue by 4egito** [Atlantiss/NetherwingBugtracker#7062]
[//]: # (Enclose links to things related to the bug using http://wowhead.com or any other TBC database.)
[//]: # (You can use screenshot ingame to visual the issue.)
[//]: # (Write your tickets according to the format:)
[//]: # ([Quest][Azuremyst Isle] Red Snapper - Very Tasty!)
[//]: # ([NPC] Magistrix Erona)
[//]: # ([Spell][Mage] Fireball)
[//]: # ([Npc][Drop] Ghostclaw Lynx)
[//]: # ([Web] Armory doesnt work)
[//]: # (To find server revision type `.server info` command in the game chat.)

**Description**: 
1. Entrapment does not proc with snake trap.(There is a video for like 10 min = 0 procs)
2. Also about "Snake Trap issue" - #6570 you can see how deadly poison no longer ticks when the snakes dies.
3. Also in [this retail video](https://youtu.be/XyZyuExJah8?t=195) you can see how big is the snake aggro range but in the video attack only enemies in 5-10 yards (I can make new video for that if u want)
**Current behaviour**:
https://drive.google.com/file/d/155S8nqCJXbcUdqk838A6c4q0bwyrhIOT/view?usp=sharing
**Expected behaviour**: 
![image](https://user-images.githubusercontent.com/52432938/85416018-a9eef680-b576-11ea-9eb3-c838435e5011.png)
![image](https://user-images.githubusercontent.com/52432938/85419257-86c64600-b57a-11ea-865a-6ac614afaec9.png)
**Sources:** 
https://tbc-twinhead.twinstar.cz/?spell=19388 
https://wowwiki.fandom.com/wiki/Snake_Trap

**Server Revision**: 
3404

**Comment by Tereneckla** [comment]
Your videos are private

**Comment by 4egito** [comment]
Sorry... It should be fixed!

**Comment by Wolffenstein** [comment]
Fixed in rev 3407.
