### ISSUE TITLE
[Sap][Rogue] Targets in stealth are immune 

### ISSUE THREAD

**Issue by 4egito** [Atlantiss/NetherwingBugtracker#7063]
[//]: # (Enclose links to things related to the bug using http://wowhead.com or any other TBC database.)
[//]: # (You can use screenshot ingame to visual the issue.)
[//]: # (Write your tickets according to the format:)
[//]: # ([Quest][Azuremyst Isle] Red Snapper - Very Tasty!)
[//]: # ([NPC] Magistrix Erona)
[//]: # ([Spell][Mage] Fireball)
[//]: # ([Npc][Drop] Ghostclaw Lynx)
[//]: # ([Web] Armory doesnt work)
[//]: # (To find server revision type `.server info` command in the game chat.)

**Description**: 
In the video you can see how both of the rogues vanishes and somehow when i was trying to sap UI says "Immune" (and gets me in GCD) even without any DR's on target (gladdy on the right side can approve that or i can upload full arena) also second after that the another rogue tries to open on me with cheap shot (u can hear cheap shot sound which turns me in combat but there's no resist in the combat log -> probably i'm immune...). 
I think some of the last stealth changes might be the reason for this.
**Current behaviour**:
https://drive.google.com/file/d/1rTe2UE9cY6A5FuXE3wGSf8TbqOjL8krD/view?usp=sharing
**Expected behaviour**: 

**Server Revision**: 
It happens yesterday and im not sure what was the exact server revision maybe 3400

**Comment by Tereneckla** [comment]
Your videos are private

**Comment by 4egito** [comment]
Sorry... It should be fixed!

**Comment by Wolffenstein** [comment]
Fixed in rev 3407.
