### ISSUE TITLE
[NPC] [Blood Furnace] [H] - Keli'dan the Breakers Pull Mechanic

### ISSUE THREAD

**Issue by Drayo** [Atlantiss/NetherwingBugtracker#7064]
[//]: # (Enclose links to things related to the bug using http://wowhead.com or any other TBC database.)
[//]: # (You can use screenshot ingame to visual the issue.)
[//]: # (Write your tickets according to the format:)
[//]: # ([Quest][Azuremyst Isle] Red Snapper - Very Tasty!)
[//]: # ([NPC] Magistrix Erona)
[//]: # ([Spell][Mage] Fireball)
[//]: # ([Npc][Drop] Ghostclaw Lynx)
[//]: # ([Web] Armory doesnt work)
[//]: # (To find server revision type `.server info` command in the game chat.)

**Description**: On Heroic he gets a pull mechanic before he does the fire nova.

**Current behaviour**: 

- It seems to lift players up way too high, scaling with distance.

https://youtu.be/wk6-Fb-pfXI (Still okayish but definitely differrent)

https://youtu.be/aRMImga9kdo (If you are far away it gets pretty nuts)

**Expected behaviour**: 

- The pull should be flat and pretty fast.

Source: 

- https://youtu.be/czktuJaw4IA?t=223

**Server Revision**: 3403

**Comment by Wolffenstein** [comment]
Fixed in rev 3407.
