### ISSUE TITLE
[Blood Furnace] [Object] - Rifts in the last room are missing

### ISSUE THREAD

**Issue by Drayo** [Atlantiss/NetherwingBugtracker#7065]
[//]: # (Enclose links to things related to the bug using http://wowhead.com or any other TBC database.)
[//]: # (You can use screenshot ingame to visual the issue.)
[//]: # (Write your tickets according to the format:)
[//]: # ([Quest][Azuremyst Isle] Red Snapper - Very Tasty!)
[//]: # ([NPC] Magistrix Erona)
[//]: # ([Spell][Mage] Fireball)
[//]: # ([Npc][Drop] Ghostclaw Lynx)
[//]: # ([Web] Armory doesnt work)
[//]: # (To find server revision type `.server info` command in the game chat.)

**Description**: There should be Rifts in the last room of the Dungeon. These rifts should give the players a beneficial debuff called "Rage of Magtheridon" ONCE EACH.

**Current behaviour**: 

- **I can only see the rifts in GM mode**, once I toggle it off they are gone. I can still get the debuff [Rage of Magtheridon](https://www.wowhead.com/spell=30939/rage-of-magtheridon) if I stand where they should be. **The debuff can be obtained over and over.** 

https://i.imgur.com/WihaE6a.png (with GM toggled)
https://i.imgur.com/4HVoGhJ.png (normal)
https://i.imgur.com/EkAI823.png (buff refreshing)

**Expected behaviour**: 

- **The rifts should be visible to the players.** https://www.youtube.com/watch?v=czktuJaw4IA

-The rifts should give a player the debuff [Rage of Magtheridon](https://www.wowhead.com/spell=30939/rage-of-magtheridon) **ONCE** as mentioned in the [wowwiki article](https://wowwiki.fandom.com/wiki/Keli%27dan_the_Breaker_(tactics)?oldid=564295). (This is also the first date it's mentioned with an explanation on how to obtain the debuff)

[Wowhead comments](https://www.wowhead.com/spell=30939/rage-of-magtheridon#comments) seem to imply that the effect was changed at some point.

By 43442 (381 – 1·3) on 2007/04/15 (Patch 2.0.12)

> This buff is applied when stepping into the pools of blue glowing blood in the corners of the room when fighting the last boss in Blood Furnace.
> 
> Edit - **lately I have noticed I cannot trigger this effect again in the same way I did previously. It has possibly been removed from the last portion of BF.**

By 93865 (27,451 – 6·40·202) on 2008/05/25 (Patch 2.4.1)

> The effect is present, but very inconsistent.
> 
> It is obtained, as stated above, by standing in the bluish light emanating from cracks in the floor along the edges of Kelidan the Breaker's room in Blood Furnace. The best time to acquire it is when running away as he casts his massive AoE.
> 
> **It is not clear how to acquire the buff in a consistent way. Sometimes standing in a particular crack yields the buff; other times it does not. It is active in both Normal and Heroic mode.**
> 
> I **managed to acquire it during 2.4.2** on my paladin.

By 93865 (27,451 – 6·40·202) on 2008/08/28 (Patch 3.0.1)

> Upon closer examination, green gas can **occasionally** be seen puffing up from the cracks. **This is what gives the buff.** It can spawn **more than once per encounter** - I got the buff twice on a single pull.

**Maybe always getting the buff was a bug and it was supposed to be random which rift gives the buff, changing as the fight goes on.**

**Server Revision**: 3403

**Comment by Wolffenstein** [comment]
Fixed in rev 3407.
