### ISSUE TITLE
[NPC] The mobs around the south of Auchindoun should be fighting each other

### ISSUE THREAD

**Issue by Minimix186** [Atlantiss/NetherwingBugtracker#7068]
[//]: # (Enclose links to things related to the bug using http://wowhead.com or any other TBC database.)
[//]: # (You can use screenshot ingame to visual the issue.)
[//]: # (Write your tickets according to the format:)
[//]: # ([Quest][Azuremyst Isle] Red Snapper - Very Tasty!)
[//]: # ([NPC] Magistrix Erona)
[//]: # ([Spell][Mage] Fireball)
[//]: # ([Npc][Drop] Ghostclaw Lynx)
[//]: # ([Web] Armory doesnt work)
[//]: # (To find server revision type `.server info` command in the game chat.)

**Description**: 

The mobs to the south of Auchindoun should be engaged in combat.

**Current behaviour**:

They stand around and stare at each other

**Expected behaviour**: 

As seen in this video:

https://www.youtube.com/watch?v=i1zLenjSupA

They should be fighting each other

**Server Revision**: 

24/6/20

**Comment by Tereneckla** [comment]
Vindicators can be slow to engage with the Warrior next to them.
They should be more aggressive.

**Comment by Minimix186** [comment]
While i was questing there, i did not see any engage in combat. I was there roughly 20mins or so.

**Comment by Evolvee** [comment]
its a known bug i encountered during scripting the zone, confirmed core issue with aggro between 2 different factions

**Comment by Godmatik** [comment]
Guess it was fixed - they are fighting
