### ISSUE TITLE
[npc][item] emerald dragon whelp is passive (dragon's call summon) 

### ISSUE THREAD

**Issue by duzyizly** [Atlantiss/NetherwingBugtracker#7070]
**Description**: 
Emerald dragon whelp https://www.wowhead.com/npc=8776/emerald-dragon-whelp#comments
summoned from https://tbcdb.com/?item=10847
is not atacking enemies **unless he's attacked first by the enemy**

**Expected behaviour**: 
I'm sure whelp should attack/spell cast on his own - most likely same target as his "master".

**Server Revision**: 
3403 ptr

![WoWScrnShot_062520_152727](https://user-images.githubusercontent.com/43931626/85729446-1eea3980-b6f9-11ea-97f7-39d71d154310.jpg)
![WoWScrnShot_062520_152735](https://user-images.githubusercontent.com/43931626/85729473-2578b100-b6f9-11ea-8746-0d19e8849e41.jpg)
![WoWScrnShot_062520_153011](https://user-images.githubusercontent.com/43931626/85729502-29a4ce80-b6f9-11ea-96d6-974b673e4bdb.jpg)

**Comment by Tereneckla** [comment]
https://www.wowhead.com/item=10847/dragons-call#comments:id=2842
![image](https://user-images.githubusercontent.com/50233983/85733693-af764900-b6fc-11ea-8019-42504ef6aa5f.png)

**Comment by Wolffenstein** [comment]
Fixed in rev 3412.
