### ISSUE TITLE
[Npc][Spell] K'iru's Song of Victory 

### ISSUE THREAD

**Issue by NatsumeLily** [Atlantiss/NetherwingBugtracker#7071]
[//]: # (Enclose links to things related to the bug using http://wowhead.com or any other TBC database.)
[//]: # (You can use screenshot ingame to visual the issue.)
[//]: # (Write your tickets according to the format:)
[//]: # ([Quest][Azuremyst Isle] Red Snapper - Very Tasty!)
[//]: # ([NPC] Magistrix Erona)
[//]: # ([Spell][Mage] Fireball)
[//]: # ([Npc][Drop] Ghostclaw Lynx)
[//]: # ([Web] Armory doesnt work)
[//]: # (To find server revision type `.server info` command in the game chat.)

**Description**: K'iru's Song of Victory is a buff that is applied to Isle of Quel'Danas, Magister's Terrace, and Sunwell plateau when the Isle dailys/progress is complete. It is applied by the npc K'iru, who appears when the progress is complete.

**Current behaviour**: Currently K'iru is spawned and has the buff, but the buff isn't being applied to players in the zones.

**Expected behaviour**: K'iru's Song of Victory buff should be applied to all players on the Isle, inside MGT, and inside Swp.

Edit: Further info in case it is needed. 

- It's one buff but 2 semi-separate effects.
- Both stat increases don't stack with their respectable class buffs (mage buff and priest buff).
- Priest buff doesn't stack with the stamina increase but improved power word: fortitude overwrites the K'iru's Song of Victory stamina increase buff.
- Mage buff doesn't stack with the intellect increase but K'iru's Song of Victory intellect increase should still be active if the stamina increase is overwritten by improved priest buff.

**Server Revision**: 3404

**Comment by NatsumeLily** [comment]
Can we get this fixed for the guilds still in swp?

**Comment by Godmatik** [comment]
Already implemented, can close
