### ISSUE TITLE
Lines of Sight Vastly incorrect

### ISSUE THREAD

**Issue by slicplaya** [Atlantiss/NetherwingBugtracker#7072]
Description:  Many areas of the game have incorrect lines of sight.  In this instance a boat south of Booty Bay with multiple Bloodsail mobs.
Current behavior: Walking on/in the boat and down the steps will cause one mob on the other side of the boat wall to aggro, and chain pull the entire ship full of mobs all the way to the bottom level. There are other cases of this from the wood trunk errected walls at Grom'Gol. Players are able to cast spells right through the walled terrain. This predominantly changes the interactions from players and NPCs in the game, and is technically not "Blizzlike". 
Expected behavior: Mobs/hostile NPCs shouldn't see through walled terrain in these cases.

**Comment by Wolffenstein** [comment]
It only affects certain objects (such as stairwells on Bloodsail Boats) and already has been reported.
