### ISSUE TITLE
[NPC] Razorthorn Ravager and Hunter pets

### ISSUE THREAD

**Issue by a20eac1d** [Atlantiss/NetherwingBugtracker#7076]
**Description**: 
I tamed a "Razorthorn Ravager" and it had absolutely no spells or abilities.

**Current behaviour**:
Tame a Razorthorn Ravager and get an "empty" pet with no spells 

**Expected behaviour**:
Tame a Razorthorn Ravager with its default spells

**Server Revision**: 
Karazhan PTR # 3413

**References**:
https://tbcdb.com/?npc=24922#abilities

![Image of mobs](https://i.imgur.com/eXxkaKk.png)

**Comment by Tereneckla** [comment]
It should be untameable
http://web.archive.org/web/20080723125025/http://petopia.brashendeavors.net/html/mobs/mob_razorthornravager.php

**Comment by Wolffenstein** [comment]
Will no longer be tameable after rev 3415.
