### ISSUE TITLE
[NPC] Sunfury mobs are completely passive under certain conditions

### ISSUE THREAD

**Issue by a20eac1d** [Atlantiss/NetherwingBugtracker#7077]
**Description**:
The "Sunfury" mobs around Manaforge Duro (Netherstorm) are permanently passive and don't mind you attacking them. They just stay where they are. ("Sunfury Centurion", "Sunfury Bowman"). This happens when you attack them with a Hunter's range abilities or if the pet attacks them alone.

**Current behaviour**:
The mobs don't attack you or even defend themselves

**Expected behaviour**:
The mobs should be aggressive and attack you

**Server Revision**:
Karazhan PTR 3413

https://tbcdb.com/?npc=20207

**Comment by Wolffenstein** [comment]
Can you record that happening?

**Comment by Tereneckla** [comment]
Just happens on the Kara PTR
https://www.youtube.com/watch?v=NiGeyt2VZfg&feature=youtu.be

**Comment by Wolffenstein** [comment]
Are you sure you don't have GM on?

**Comment by Wolffenstein** [comment]
Never mind, I reproduced it.

**Comment by Wolffenstein** [comment]
Fixed in rev 3415.
