### ISSUE TITLE
[Spell][Hunter] Cannot feed pet because "you are in combat"

### ISSUE THREAD

**Issue by a20eac1d** [Atlantiss/NetherwingBugtracker#7078]
**Description**:
I am a Hunter killing mobs around "Manaforge Duro" in Netherstorm. After killing all mobs and leaving combat I still cannot use the spell "Feed Pet" because "You are still in combat".

**Current behaviour**:
Cannot feed pet because "still in combat".

**Expected behaviour**:
I should be able to feed my pet outside of combat

**Server Revision**:
Karazhan PTR 3413

**Comment by Wolffenstein** [comment]
What about the pet? Was your pet still in combat with something?

**Comment by Wolffenstein** [comment]
I corrected the error message to show something different when the player isn't in combat but pet is in rev 3415. If the same issue is still present after that patch, please record it and post the video in a new issue.
