### ISSUE TITLE
[Item][Hunter] Cannot move quiver from one bag slot to another

### ISSUE THREAD

**Issue by a20eac1d** [Atlantiss/NetherwingBugtracker#7079]
**Description**:
You cannot change the position of your quiver from one bag slot to another.

**Current behaviour**:
You cannot move your quiver from one bag slot to another bag slot because the game thinks that you are trying to equip another quiver and gives the error message "You can only equip one quiver". In order to switch the quiver position you have to:

1. empty your quiver ammo into the regular inventory

2. put the quiver into your regular inventory

3. equip it into the right slot

4. move the ammo bag into the quiver.

**Expected behaviour**: 
You should be able to move the quiver including the ammo to another bag slot.

**Server Revision**: 
Karazhan PTR 3415

**Comment by Wolffenstein** [comment]
Fixed in rev 3416.
