### ISSUE TITLE
 [Spell][Warrior] Hamstring

### ISSUE THREAD

**Issue by Firroth** [Atlantiss/NetherwingBugtracker#708]
https://www.wowhead.com/spell=1715/hamstring

**Current behaviour**:
Hamstring "slow effect" isn't added to target, if target blocks hamstring's initial dmg. On rank 1 it's "5damage". 
What this means is if all damage is blocked, be it mob/player from hamstring, he/she won't get slow effect - warriors with shields/ paladins / shamans can block it too which in turn will make fury/arms warrior impossible to slow them down (in arena's f.e it would be tragic), when hunters f.e with their wing clip won't have any problems.

Tested it in Duskwood on Skeletal Horrors.

**Expected behaviour**: 
Hamstring initial damage "can be blocked" but even if it's damage is fully blocked, hamstring slow effect should apply to the target.

**Server Revision**: 
2065

**Comment by Easyfraggy** [comment]
I'm not sure this is correct, will need proof.

**Comment by Easyfraggy** [comment]
![image](https://user-images.githubusercontent.com/36134067/46111979-3c6b3600-c1e9-11e8-879b-792d1fd58343.png)

**Comment by Easyfraggy** [comment]
Reopen if you find some proof.
