### ISSUE TITLE
[NPC] Dialog has invalid characters in names

### ISSUE THREAD

**Issue by a20eac1d** [Atlantiss/NetherwingBugtracker#7080]
**Description**:
The NPCs in the Lower City of Shattrath have some timed dialog event where they talk to each other in chat. The text they say seems correct, but their names don't show up in chat correctly. It seems like they contain invalid characters or maybe some world packet is malformed? AFAIK the error appears only on Atlantiss realms, other servers work fine for me so it has to be a server-side issue.

**Current behaviour**:
The NPC names are mangled in chat, maybe because of invalid characters.

**Expected behaviour**:
The chat should correctly print the name of the NPCs.

**Additional info**:
WoW 2.4.3 (8606), US client, no addons, no custom MPQ patches, cache + WTF folder deleted

**Server Revision**: 
Karazhan PTR 3415

![Invalid characters](https://i.imgur.com/4ZUe0T2.png)

**Comment by Wolffenstein** [comment]
![obraz](https://user-images.githubusercontent.com/1576644/86093718-b7910880-baaf-11ea-81d5-4f8dec4d031d.png)
Looks fine to me, either it's some PTR-only bug or your client has some issue.

**Comment by a20eac1d** [comment]
@Wolffenstein Do you have a download / torrent link for a client that is confirmed good and working? Will test and report back

**Comment by Wolffenstein** [comment]
Try the ones here: https://atlantiss.eu/how-to-connect (hopefully these work, I have had the same client for like 4 years).

**Comment by eri1997** [comment]
I see the same in karazhan ptr
![image](https://user-images.githubusercontent.com/52356864/86094045-44d45d00-bab0-11ea-8a86-bc4a7a48fe4d.png)

**Comment by Wolffenstein** [comment]
Hmm, seems like I have the same issue on PTR, weird.

**Comment by Wolffenstein** [comment]
Eh, I messed something up with locales. Will fix it when I get some sleep.

**Comment by Wolffenstein** [comment]
Fixed in rev 3419.
