### ISSUE TITLE
[GameObject] Flying crate in Lower City, Shattrath

### ISSUE THREAD

**Issue by a20eac1d** [Atlantiss/NetherwingBugtracker#7081]
**Description**:
This crate is so magical that it can fly.

**Server Revision**:
Karazhan PTR 3418

![Magical crate](https://i.imgur.com/sHn3Pnz.jpg)

**Comment by Tereneckla** [comment]
gob 181015 13

**Comment by Wolffenstein** [comment]
Fixed in rev 3419.

**Comment by a20eac1d** [comment]
As of r3420 the crate is still flying and seems to be unchanged
