### ISSUE TITLE
[NPC] Cro Threadstrong has gone crazy

### ISSUE THREAD

**Issue by Tereneckla** [Atlantiss/NetherwingBugtracker#7082]
[//]: # (Enclose links to things related to the bug using http://wowhead.com or any other TBC database.)
[//]: # (You can use screenshot ingame to visual the issue.)
[//]: # (Write your tickets according to the format:)
[//]: # ([Quest][Azuremyst Isle] Red Snapper - Very Tasty!)
[//]: # ([NPC] Magistrix Erona)
[//]: # ([Spell][Mage] Fireball)
[//]: # ([Npc][Drop] Ghostclaw Lynx)
[//]: # ([Web] Armory doesnt work)
[//]: # (To find server revision type `.server info` command in the game chat.)

**Description**: 
![image](https://user-images.githubusercontent.com/50233983/86119611-1a47cb80-bad3-11ea-89fe-18498b821af1.png)

**Server Revision**: 3418 (Netherwing PTR but not Kara PTR)

**Comment by Wolffenstein** [comment]
I was testing stuff, it will be normal there after restart.
