### ISSUE TITLE
[Quest] Battle-Mage Dathric [NPC]  Battle-Mage Dathric

### ISSUE THREAD

**Issue by The14me** [Atlantiss/NetherwingBugtracker#7083]
**Description**: https://www.wowhead.com/quest=10182/battle-mage-dathric

**Current behavior**:https://streamable.com/hhogf5
 Once u click and spawn the NPC, he turn neutral and follow u forever.

**Expected behavior**: thttps://www.youtube.com/watch?v=zbZwgRIaryI

**Server Revision**: 3418 (2.0.3) Kara PTR.

**Comment by Tereneckla** [comment]
Same issue with Belmara(10305) and Luminrath(10306)
https://www.youtube.com/watch?v=KZyq_JGcHAc
https://www.youtube.com/watch?v=KSUeqWJvlu4

**Comment by The14me** [comment]
True 
https://streamable.com/hhogf5

**Comment by Minimix186** [comment]
Description:

https://www.wowhead.com/quest=10306/conjurer-luminrath

Current behaviour:

Once you click the quest item by the wardrobe, the NPC spawns, but you are unable to attack them. They will also follow you forever.

**Comment by Minimix186** [comment]
Also Abjurist Belmara for the quest Abjurist Belmara does exactly the same behaviour as Battle-Mage Dathric. 

All 3 are repeatble bugs.

**Comment by Evolvee** [comment]
![1530379214_3x (1)](https://user-images.githubusercontent.com/1942409/86152382-60675400-bb00-11ea-8c44-abc933dab960.gif) core updates 
![1530379214_3x (1)](https://user-images.githubusercontent.com/1942409/86152405-65c49e80-bb00-11ea-8990-35a8cffedbdc.gif)

**Comment by Wolffenstein** [comment]
Fixed in rev 3419.
