### ISSUE TITLE
[Core/Hunter] Wrong Calculation of a base stat

### ISSUE THREAD

**Issue by cackgithub** [Atlantiss/NetherwingBugtracker#7085]
I have a hunter, Survivor Hunter. Yesterday I won an item with more agility than t4 chest, so I was happy to replace it as an upgrade only to see that the t4 has 5 more Agility. 
[Demon Stalker Harness](https://tbcdb.com/?item=29082) with three sockets, each with 4 agility and 6 stats ench
26+12+6=44, right? I have the talent to get 15% more agility, so I do the math 44+(44x15%)= 44+6.6=50,6
on the other hand I have [Shadowtooth Trollskin Cuirass](https://tbcdb.com/?item=33329) which has 45 agility, no gem slots and 6 stats enchant 45+6=51 right? 51+(51x15%)=51+7,65=58,65.

I don't know how you round up the numbers after the dot, point or whatever you might call it, but when switching the item for the chest I noticed this and thought of it as weird.
![Untitled](https://user-images.githubusercontent.com/67645918/86142151-8c340b00-bafb-11ea-80a1-1de43cd2ae98.jpg)

To keep anything private I do not show my character, name and so on, just the important stuff on the image unless you claim that those are more important than the issue at hand. I already spoke with a GM in discord and he said twice to write it in the bug tracker and that he is not a developer. I do own the original images and my character is in Atlantiss(Netherwing) TBC private server.

P.S. If I failed to post it right in any way, please excuse me. I thought those little things can be fixed quick, but guess not. Not fan of a 3rd site to post Bugs either.

**Comment by Tereneckla** [comment]
99% sure you lose the requirements for the Relentless Earthstorm Diamond Meta Gem and that causes it.

https://wowwiki.fandom.com/wiki/Relentless_Earthstorm_Diamond
