### ISSUE TITLE
Eye of Magtheridon on Karazhan PTR

### ISSUE THREAD

**Issue by ztkay** [Atlantiss/NetherwingBugtracker#7086]
Hey, basically when the trinket procs it'll cancel my current cast (usually Mind Flay) instead of just giving the buff.
It's not when Mind Flay resists, but it seems to only occur when shadowfiend is up actually.

I was able to reproduce it atleast 10 times.

**Comment by Wolffenstein** [comment]
Cannot reproduce, please make a video.
