### ISSUE TITLE
Cannot Find realm when log in

### ISSUE THREAD

**Issue by Goreshifter** [Atlantiss/NetherwingBugtracker#7087]
Hello

**Description**: 
when i log in to the game i am not able to log in to server Atlantis netherwing

**Current behaviour**:
when i click Change realm i can select between 2 realms
![image](https://user-images.githubusercontent.com/67653626/86160131-9bbb5000-bb0b-11ea-9674-a79c4ce2c9c4.png)

realm list is 
![image](https://user-images.githubusercontent.com/67653626/86160265-ca392b00-bb0b-11ea-91b6-51087c73d378.png)

I see there only few characters and my paladin on old gear
don't know if this is a save character.. but he is mine in gear that i had long ago

**Comment by Goreshifter** [comment]
deleted cache but that didnt help

**Comment by Wolffenstein** [comment]
Choose the "English" tab at the bottom, you'll find Netherwing there.

**Comment by Goreshifter** [comment]
Thank you :)
