### ISSUE TITLE
Instant crash on log in

### ISSUE THREAD

**Issue by Ambrusius** [Atlantiss/NetherwingBugtracker#7088]
[//]: # (Enclose links to things related to the bug using http://wowhead.com or any other TBC database.)
[//]: # (You can use screenshot ingame to visual the issue.)
[//]: # (Write your tickets according to the format:)
[//]: # ([Quest][Azuremyst Isle] Red Snapper - Very Tasty!)
[//]: # ([NPC] Magistrix Erona)
[//]: # ([Spell][Mage] Fireball)
[//]: # ([Npc][Drop] Ghostclaw Lynx)
[//]: # ([Web] Armory doesnt work)
[//]: # (To find server revision type `.server info` command in the game chat.)

When i log in on the ptr i get the following error message as the client crashes:
ERROR #132 (0x85100084) Fatal Exception
Program:	Wow.exe
Exception:	0xC0000005 (ACCESS_VIOLATION) at 0023:00604D83

The instruction at "0x00604D83" referenced memory at "0x000000E0".
The memory could not be "read".

WoWBuild: 8606

This only affects one of my characters "Umph" who got logged out during the server restart on the elevator to the scryers

Karazhan PTR

**Comment by Wolffenstein** [comment]
![obraz](https://user-images.githubusercontent.com/1576644/86170467-75051580-bb1b-11ea-94bd-a46cbbcd939b.png)
I managed to log in just fine, try cleaning up your cache folder/disabling addons.
