### ISSUE TITLE
[NPC][MMAPS] Diremaul North missing paths

### ISSUE THREAD

**Issue by a20eac1d** [Atlantiss/NetherwingBugtracker#7089]
**Description**:
These mobs in Diremaul North are missing correct MMap data, because they evade and cannot get to you in certain locations.

**Current behaviour**:
The "Gordok Mastiff"s evade

**Expected behaviour**:
They should be able to get onto the ledge

**Server Revision**: 
3420

Correct behavior: https://www.youtube.com/watch?v=Hh6nn1oPPlY&t=34s

![Current behavior](https://i.imgur.com/coMiVBX.jpg)

**Comment by The14me** [comment]
All of the DM's need rework.

**Comment by MisaHack** [comment]
@a20eac1d @The14me can confirm that all 3, Dire Maul (east, west, north) have a lot of bugs.
East - imp at begining of dungeon (I think it is called Pipiap) has bug that you can not find him where quest has to finish, instead he resets him self at the start of dungeon - but smaller bug
North - is ok, but Ogre Ghosts can not be killed and they attack you to the end of dungeon, but can not kill you,, everything else is ok
West - is complete bug mess, it should be scripted all over again

**Comment by Wolffenstein** [comment]
That was never in doubt, I simply lack the time to rewrite it from scratch at the moment.

**Comment by Godmatik** [comment]
Duplicate - Dire Maul right now is stock and needs a full rework, it is on Wolf's to-do list
