### ISSUE TITLE
[Quest] [Dustwallow marsh] Discrediting the Deserters

### ISSUE THREAD

**Issue by tinkzorg** [Atlantiss/NetherwingBugtracker#709]
[//]: # (Enclose links to things related to the bug using http://wowhead.com or any other TBC database.)
[//]: # (You can use screenshot ingame to visual the issue.)
[//]: # (Write your tickets according to the format:)
[//]: # ([Quest][Azuremyst Isle] Red Snapper - Very Tasty!)
[//]: # ([NPC] Magistrix Erona)
[//]: # ([Spell][Mage] Fireball)
[//]: # ([Npc][Drop] Ghostclaw Lynx)
[//]: # ([Web] Armory doesnt work)

**Description**: Currently, this quest cannot be completed.

**Current behaviour**: After accepting the quest, Theramore Guards still cannot be interacted with in any way. Hence, handing them the altered deserter propaganda is impossible.

**Expected behaviour**: Generic Theramore Guards should be interactable.

**Server Revision**: 2066

**Comment by Evolvee** [comment]
rev Xd
