### ISSUE TITLE
[PTR 2.0] BS crafts in 2.4 state

### ISSUE THREAD

**Issue by networm555** [Atlantiss/NetherwingBugtracker#7090]
![WoWScrnShot_070120_161540](https://user-images.githubusercontent.com/43811642/86226768-5011b080-bbb6-11ea-91ce-47e2054d8db3.jpg)

**Comment by networm555** [comment]
Ragesteel Shoulders missing in the loot table

**Comment by Tereneckla** [comment]
ragesteel shoulders was added in 2.2

**Comment by Wolffenstein** [comment]
Fixed - delete cache.
