### ISSUE TITLE
[Quest][Valley of Trials] Lazy Peons

### ISSUE THREAD

**Issue by Dract** [Atlantiss/NetherwingBugtracker#7091]
[Quest][Valley of Trials] Lazy Peons
rev: 3418

Description: Lazy Peons doesn't give shared quest credit when maybe it should.

Current behaviour: 
In a group with two people on the quest only the player who hits the peon gets the credit

Expected behaviour: 
In a group with two people on the quest both players get the credit when the peon is hit

I don't know if you accept classic wow as proof, if not I'll try and find something from actual retail but that will be hard.

( https://youtu.be/TAuNRfnKaoo?t=943 ) In this livestream the quest credit is obviously shared.

**Comment by Tereneckla** [comment]
Fixed in 3425

**Comment by Easyfraggy** [comment]
Doesn't seem to work still.

**Comment by Wolffenstein** [comment]
Fixed in rev 3484.
