### ISSUE TITLE
Npc-s missing

### ISSUE THREAD

**Issue by Skwayzer** [Atlantiss/NetherwingBugtracker#7092]
[//]: # (Enclose links to things related to the bug using http://wowhead.com or any other TBC database.)
[//]: # (You can use screenshot ingame to visual the issue.)
[//]: # (Write your tickets according to the format:)
[//]: # ([Quest][Azuremyst Isle] Red Snapper - Very Tasty!)
[//]: # ([NPC] Magistrix Erona)
[//]: # ([Spell][Mage] Fireball)
[//]: # ([Npc][Drop] Ghostclaw Lynx)
[//]: # ([Web] Armory doesnt work)
[//]: # (To find server revision type `.server info` command in the game chat.)

**Description**: Hello, today after the hotfix went live, all the NPC-s from isle of quell danas progression have disappeared and those around the portal also. it is like the server has been rolled back to its previous state.

**Current behaviour**:Npc-s missing.

**Expected behaviour**: Npc-s being where they are supposed to be.

**Server Revision**:

**Comment by Tereneckla** [comment]
No rollback. Just NPCs that are assigned to events are missing.

**Comment by Skwayzer** [comment]
I don't know how or why they disappeared but people find it strange for them to be gone. Those vendors should stay permanent no?

**Comment by Wolffenstein** [comment]
Fixed in rev 3422.
