### ISSUE TITLE
[Gear][Auras] Auras gain snapshot benefits from gear bonuses

### ISSUE THREAD

**Issue by bekonja** [Atlantiss/NetherwingBugtracker#7093]
[//]: # (Enclose links to things related to the bug using http://wowhead.com or any other TBC database.)
[//]: # (You can use screenshot ingame to visual the issue.)
[//]: # (Write your tickets according to the format:)
[//]: # ([Quest][Azuremyst Isle] Red Snapper - Very Tasty!)
[//]: # ([NPC] Magistrix Erona)
[//]: # ([Spell][Mage] Fireball)
[//]: # ([Npc][Drop] Ghostclaw Lynx)
[//]: # ([Web] Armory doesnt work)
[//]: # (To find server revision type `.server info` command in the game chat.)

**Description**: 
https://tbcdb.com/?spell=23559
https://tbcdb.com/?spell=23557
and many other bonuses from gear that provide buffs to certain spells and auras

**Current behaviour**:
Snapshots. You are able to equip 3 pieces of hunters' t2 for example and buff imroved hawk. After switching back to normal gear ap bonus remains.

**Expected behaviour**: 
Should update on every gear change: https://www.youtube.com/watch?v=XAvZi_KxYUI&feature=youtu.be
^ current behavior on classic

With current snapshot system its only matter of time when some retarded abuse will be discovered that gonna skyrocket one of classes into heavily imbalanced state.

**Server Revision**: 
3418

**Comment by Tereneckla** [comment]
Isn't the classic core based on the current retail BFA core, which had snapshotting completely removed because warlocks could abuse it with some trinket.

**Comment by bekonja** [comment]
https://tbcdb.com/?item=32387 on the other hand refreshes your auras calculations when you swap it on NW.
I think swapping any gear should result in calculations reset, but i dont have any proofs for it working one way or another back in OG TBC.
Way it currently works on NW could be easily abused. Simple example is https://tbcdb.com/?spell=33182 being buffed on a person who equips full spirit set, resulting in much higher SP bonus from it.

**Comment by Wolffenstein** [comment]
Aspects are permanent auras, they should get snapshotted.
