### ISSUE TITLE
(Ritual of) Summoning does not work

### ISSUE THREAD

**Issue by Nghedi** [Atlantiss/NetherwingBugtracker#7095]
[//]: # (Enclose links to things related to the bug using http://wowhead.com or any other TBC database.)
[//]: # (You can use screenshot ingame to visual the issue.)
[//]: # (Write your tickets according to the format:)
[//]: # ([Quest][Azuremyst Isle] Red Snapper - Very Tasty!)
[//]: # ([NPC] Magistrix Erona)
[//]: # ([Spell][Mage] Fireball)
[//]: # ([Npc][Drop] Ghostclaw Lynx)
[//]: # ([Web] Armory doesnt work)
[//]: # (To find server revision type `.server info` command in the game chat.)

**Description**: 
Ritual of summoning (and also summoning stones i was told) don't work quite often/in general. 

**Current behaviour**:
It says "you have no target". 

**Expected behaviour**: 
You should be able to summon people
**Server Revision**: 
3421

**Comment by Wolffenstein** [comment]
Fixed in rev 3422.
