### ISSUE TITLE
[NPC][MMAPS] Scarlet Monastery: Cathedral has broken movement maps

### ISSUE THREAD

**Issue by a20eac1d** [Atlantiss/NetherwingBugtracker#7097]
**Description**:
The mobs in SM: Cath often ignore MMaps completely and fly through the air:

https://gfycat.com/spiritedyearlygossamerwingedbutterfly

**Current behaviour**:
Mobs flying through the air taking the shortest route

**Expected behaviour**: 
Mobs should follow the paths

**Server Revision**:
PTR 3422

**Comment by Godmatik** [comment]
Rev 4017 - they follow MMaps just fine and are not flying or moving through the air.

Likely fixed last year with the pathing updates.
