### ISSUE TITLE
[PTR 2.0] Fire Nova totem

### ISSUE THREAD

**Issue by networm555** [Atlantiss/NetherwingBugtracker#7099]
Combat log doesn't see this totem. Fix this, please. No damage from it is registered.
![WoWScrnShot_070220_190226](https://user-images.githubusercontent.com/43811642/86356790-0ea50200-bc97-11ea-848b-fb2bb6f95d05.jpg)

**Comment by raethkcj** [comment]
Check the "Everything" tab of the combat log

**Comment by Tereneckla** [comment]
![image](https://user-images.githubusercontent.com/50233983/86360231-5b2a1680-bc72-11ea-94cf-7db065ab8516.png)

**Comment by networm555** [comment]
hmmm. but why omen and recount didn't read damage and threat from them?

**Comment by networm555** [comment]
Figured out what causing this behavior. Magma and Fire Nova totem doesn't put you in combat after dealing damage. Request reopen.
