### ISSUE TITLE
Eversong Woods

### ISSUE THREAD

**Issue by Trix115** [Atlantiss/NetherwingBugtracker#71]
* Skeletons in The Dread Scar is stacked up ontop of each other. (Around 5 mobs standing ontop of each other in a huddle)
* Can't interact with Zalene Firstlight at Farstrider Retreat (Food & Drink vendor, need to buy something from her for the quest "The Party Never Ends")
* Springpaw Pelt from the quest Pelt Collection in Eversong woods seem exceedingly rare (1 in about every 10 mobs)

**Comment by Wolffenstein** [comment]
Fixed in rev 2022.
