### ISSUE TITLE
[NPC]Guards outside city not setting map waypoint

### ISSUE THREAD

**Issue by snerfy** [Atlantiss/NetherwingBugtracker#710]
[//]: # ([NPC] Silvermoon Guardian)

**Description**: When asking Guardian _outside_ of Silvermoon where a location is (druid trainer) a waypoint is not set on the world map. However, when asked _inside_, a waypoint location is set. 

**Current behaviour**:
No waypoint set from outside guard
**Expected behaviour**: 
Waypoint should be set on map
**Server Revision**: 
[2066]

**Comment by The14me** [comment]
Work fine in rev. 3441
