### ISSUE TITLE
[Druid] Mana regen seems to be too low when compared to Classic

### ISSUE THREAD

**Issue by BezawitNW** [Atlantiss/NetherwingBugtracker#7101]
**Description**:  On private servers, Druid leveling from 1-10 has always seemed excessively bad. You end up having to melee most of the time to kill mobs. I decided to compare a Tauren Druid on Netherwing and Classic for levels 1 - 5 and record total mana at each level and how much mana you gain per tick of out of combat regen. I also noticed that Netherwing and Classic have different total mana values for Tauren Druid at each level.

**Current behaviour**: 

-Level 1-
Netherwing (Total MP 77): 2 8 14 20 26 32 38 44 50 56 62 68 74 :: 6 mana regenned per tick
Classic (Total MP 67): 17 29 41 53 65 :: 12 mana regenned per tick

========================================
-Level 2-
Netherwing (Total MP 84): 9 16 23 30 37 44 51 58 65 72 79 :: 7 mana regenned per tick
Classic (Total MP 75): 0 12 25 38 50 63 max :: 13 mana regenned per tick

========================================
-Level 3-
Netherwing (Total MP 92): 17 24 31 38 45 52 59 66 73 80 87 max :: 7 mana regenned per tick
Classic (Total MP 84): 9 22 35 48 61 74 max :: 13 mana regenned per tick

========================================
-Level 4-
Netherwing (Total MP 101): 1 8 15 22 29 36 43 50 57 64 71 78 85 92 99 max :: 7 mana regenned per tick
Classic (Total MP 94): 19 32 46 60 73 87 max :: 13 mana regenned per tick

========================================
-Level 5-
Netherwing (Total MP 125): 0 8 16 24 32 40 48 56 64 72 80 88 96 104 112 120 max :: 8 mana regenned per tick
Classic (Total MP 119): 19 33 47 61 75 89 104 118 max :: 14 mana regenned per tick

**Expected behaviour**: You should be regenning more mana per tick out of combat as a Druid on Netherwing.

I am attempting to acquire data from a level 60 Druid on classic so we can compare with level 60 on Netherwing. I will update when I have that information. Judging from the 1-5 data though, it seems like on Classic you are always regenning 6 more mana get tick (at every level) than what we are getting on Netherwing.

**Comment by Tereneckla** [comment]
Do remember tbc has a different mp5 calculation based on spirit
TBC: Mana Regen = 5 * (0.001 + sqrt(Int) * Spirit * Base_Regen ) * 0.60
Vanilla(Druid): 37.5 + S/2
https://wowwiki.fandom.com/wiki/Spirit
https://wowwiki.fandom.com/wiki/Spirit?oldid=541932

**Comment by BezawitNW** [comment]
Using level 1 Tauren stats (17int and 24spirit) and the formula you provided:

10.3828359503 is the result (warning I am bad at math if anyone wants to double check it), which would still make the NW value too low

**Comment by Tereneckla** [comment]
The math is for mp5, not ticks.
If anything that would make the math too low, as the current value for a lvl 1 tauren druid is 17 mp5

**Comment by BezawitNW** [comment]
Verified it is working properly with EJ source
