### ISSUE TITLE
[Item][PTR 2.0] Several feral items not in their 2.0 state

### ISSUE THREAD

**Issue by NetheG** [Atlantiss/NetherwingBugtracker#7102]
[//]: # (Enclose links to things related to the bug using http://wowhead.com or any other TBC database.)
[//]: # (You can use screenshot ingame to visual the issue.)
[//]: # (Write your tickets according to the format:)
[//]: # ([Quest][Azuremyst Isle] Red Snapper - Very Tasty!)
[//]: # ([NPC] Magistrix Erona)
[//]: # ([Spell][Mage] Fireball)
[//]: # ([Npc][Drop] Ghostclaw Lynx)
[//]: # ([Web] Armory doesnt work)
[//]: # (To find server revision type `.server info` command in the game chat.)

Description:
Several feral items not in their 2.0 state

Current behaviour:
[Staff of Natural Fury](https://tbcdb.com/?item=31334)
[Dreamer's Dragonstaff](https://tbcdb.com/?item=28325)
[Draenic Wildstaff](https://tbcdb.com/?item=27877)
[Wildcaller](https://tbcdb.com/?item=31009)
[Fleshling Simulation Staff](https://tbcdb.com/?item=30010)
[Staff of Beasts](https://tbcdb.com/?item=25761)
[Resolute Cape](https://tbcdb.com/?item=24258)
[Thoriumweave Cloak](https://tbcdb.com/?item=28256)
[Bogstrok Scale Cloak](https://tbcdb.com/?item=24379)
[Cloak of the Valiant Defender](https://tbcdb.com/?item=29777)
[Umberhowl's Collar](https://tbcdb.com/?item=30944)
[Verdant Gloves](https://tbcdb.com/?item=30943)
[Manimal's Cinch](https://tbcdb.com/?item=30942)

Expected behaviour:
[Staff of Natural Fury](https://web.archive.org/web/20070312203601/thottbot.com/i31334)
Staff of Natural Fury should have 5 less strength, 1 less stamina, and 187 less feral attack power.
[Dreamer's Dragonstaff](https://web.archive.org/web/20070313195019/thottbot.com/i28325)
Dreamer's Dragonstaff should have 116 less feral attack power.
[Draenic Wildstaff](https://web.archive.org/web/20070320165204/http://thottbot.com/i27877)
Draenic Wildstaff should have 116 less feral attack power.
[Wildcaller](https://web.archive.org/web/20070314034055/thottbot.com/i31009)
Wildcaller should have 96 less feral attack power.
[Fleshling Simulation Staff](https://web.archive.org/web/20070314063720/thottbot.com/i30010)
Fleshling Simulation Staff should have 96 less feral attack power.
[Staff of Beasts](https://web.archive.org/web/20070315160448/thottbot.com/i25761)
Staff of Beasts should have 77 less feral attack power.
[Resolute Cape](https://web.archive.org/web/20070320023933/thottbot.com/i24258)
Resolute Cape should have 60 less armor.
[Thoriumweave Cloak](https://web.archive.org/web/20070314062712/thottbot.com/i28256)
Thoriumweave Cloak should have 72 less armor.
[Bogstrok Scale Cloak](https://web.archive.org/web/20070510205324/thottbot.com/i24379)
Bogstrok Scale Cloak should have 48 less armor.
[Cloak of the Valiant Defender](https://web.archive.org/web/20070330051608/thottbot.com/i29777)
Cloak of the Valiant Defender should have 45 less armor.
[Umberhowl's Collar](https://web.archive.org/web/20070313190508/thottbot.com/i30944)
Umberhowl's Collar should have 3 less strength.
[Verdant Gloves](https://web.archive.org/web/20070314064057/thottbot.com/i30943)
Verdant Gloves should have 3 less strength.
[Manimal's Cinch](https://web.archive.org/web/20070312203303/thottbot.com/i30942)
Manimal's Cinch should have 3 less strength.

Server Revision:
3422

**Comment by Wolffenstein** [comment]
Fixed in rev 3426.
