### ISSUE TITLE
[Guild] Guild Cap Bug

### ISSUE THREAD

**Issue by Loken-coolguy** [Atlantiss/NetherwingBugtracker#7103]
**Description**: Guilds are incorrectly capped

**Current behaviour**: 500 soft cap, 600 hard cap

**Expected behaviour**:  500 soft cap, no hard cap is blizzlike

https://web.archive.org/web/20101008201950/http://forums.worldofwarcraft.com/thread.html?topicId=27026377821&sid=2000

Blue Post proving that 600 hard cap was implemented in Cataclysm and previously there was only a soft cap

**Comment by Wolffenstein** [comment]
Intended, will not be changed.
