### ISSUE TITLE
[Quest][Mulgore] Spawn of Jubjub

### ISSUE THREAD

**Issue by srfoley** [Atlantiss/NetherwingBugtracker#7104]
**Description**

Quest for the Darkmoon Faire; Morja (loc: 35, 35) is the questgiver. Morja shows a yellow (?) over her head and on the minimap for no reason.

**Current behavior**

Morja shows a yellow (?) over her head and on the minimap.
However, I do not have any quests in my log at all, and I do not have any Dark Iron Ale Mugs (https://tbcdb.com/?item=11325) in my inventory.

**Expected behavior**

Morja should probably have a blue (?) over her head similar to other nearby NPCs, such as Chronos.

**Server Revision**: 

3422 (f152f74bec21)

**Comment by Tereneckla** [comment]
Blue quests are repeatable, A yellow question marker is correct, however it should only appear when Jubjub has been led to her recently.

**Comment by Godmatik** [comment]
Was fixed when Wolf revamped Darkmoon Faire last year
