### ISSUE TITLE
[PTR 2.0] Fire Nova totem

### ISSUE THREAD

**Issue by networm555** [Atlantiss/NetherwingBugtracker#7105]
#7099 Figured out what causing this behavior. Magma and Fire Nova totem doesn't put you in combat after dealing damage.
That's why you don't see anything in omen or recount unless you hit your target in melee.

**Comment by Tereneckla** [comment]
Hard to find information on it, but they should probably put you in combat in the same way as pets do.

combat in PvE
no combat in PvP

**Comment by Wolffenstein** [comment]
Fixed in rev 3428.

**Comment by Evolvee** [comment]
so we are now implementing custom shit based on... feelings?
