### ISSUE TITLE
[Spell][Warrior] Intervene redirect breaks the effect of "blind"

### ISSUE THREAD

**Issue by 4egito** [Atlantiss/NetherwingBugtracker#7106]
[//]: # (Enclose links to things related to the bug using http://wowhead.com or any other TBC database.)
[//]: # (You can use screenshot ingame to visual the issue.)
[//]: # (Write your tickets according to the format:)
[//]: # ([Quest][Azuremyst Isle] Red Snapper - Very Tasty!)
[//]: # ([NPC] Magistrix Erona)
[//]: # ([Spell][Mage] Fireball)
[//]: # ([Npc][Drop] Ghostclaw Lynx)
[//]: # ([Web] Armory doesnt work)
[//]: # (To find server revision type `.server info` command in the game chat.)

**Description**: 
As you see in the video warrior gets the blind through the pillar but he was able to control his character (moving/jumping etc.)
**Current behaviour**:
https://drive.google.com/file/d/1L9QSIr5AkUwTmuRckUaNQh6tt3eJOs8x/view?usp=sharing
**Expected behaviour**: 
**Server Revision**:

**Comment by Wolffenstein** [comment]
Fixed in rev 3432.

**Comment by tsuone** [comment]
@Wolffenstein Did you fix edited or original issue? If you fixed original issue, revert it.
