### ISSUE TITLE
# ([Quest][Ghostlands] Into Occupied Territory - https://www.wowhead.com/quest=9163/into-occupied-territory

### ISSUE THREAD

**Issue by koochy414** [Atlantiss/NetherwingBugtracker#7107]
[//]: # (Enclose links to things related to the bug using http://wowhead.com or any other TBC database.)
[//]: # (You can use screenshot ingame to visual the issue.)
[//]: # (Write your tickets according to the format:)
[//]: # ([Quest][Azuremyst Isle] Red Snapper - Very Tasty!)
[//]: # ([NPC] Magistrix Erona)
[//]: # ([Spell][Mage] Fireball)
[//]: # ([Npc][Drop] Ghostclaw Lynx)
[//]: # ([Web] Armory doesnt work)
[//]: # (To find server revision type `.server info` command in the game chat.)

**Description**: 
When looting Night Elf Plans: An'daroth you recieve no loot. The item is a spawned pick up off the ground, other 2 plans work fine, when picking up the third plan you recieve no loot.

**Current behaviour**:
Looting item gives no loot

**Expected behaviour**: 
Looting item should give you a plan. 

**Server Revision**: 
3430

**Comment by Tereneckla** [comment]
There is no problem looting the correct plan. However it can be confusing if you still need the plan in front of you if you don't read.
https://youtu.be/7hUTmiVCZrY

Current behaviour:
Glimmering of lootable gameobjects stops when you have all 3 plans.

Expected behaviour:
No glimmering on the plans you have.

**Comment by koochy414** [comment]
it definitly bugged for me, i checked several times, but may have been a one off

**Comment by polygxn** [comment]
This is indeed bugged, on Karazhan launch multiple people tried to loot the correct plan, but the object contained nothing. Deleted cache folder does nothing to this quest either. Rev: 3486

**Comment by Wolffenstein** [comment]
Should be solved.
