### ISSUE TITLE
Bad language

### ISSUE THREAD

**Issue by vladgg21** [Atlantiss/NetherwingBugtracker#7108]
Hello, 

During a transaction over whispers, the player started using bad language and insults out of the blue. I ll attach screenshot
![WoWScrnShot_070420_110903](https://user-images.githubusercontent.com/67825095/86510519-440d3500-bde8-11ea-8e9b-323ef5e57434.jpg)

**Comment by Tereneckla** [comment]
This is the bugtracker. For reports follow these instructions.
https://forum.atlantiss.org/topic/684-how-to-appeal-for-unbanreport-a-game-masterplayer/
