### ISSUE TITLE
[Quest] Dangerous!

### ISSUE THREAD

**Issue by Ahmpy** [Atlantiss/NetherwingBugtracker#711]
[//]: # (Enclose links to things related to the bug using http://wowhead.com or any other TBC database.)
[//]: # (You can use screenshot ingame to visual the issue.)
[//]: # (Write your tickets according to the format:)
[//]: # ([Quest][Azuremyst Isle] Red Snapper - Very Tasty!)
[//]: # ([NPC] Magistrix Erona)
[//]: # ([Spell][Mage] Fireball)
[//]: # ([Npc][Drop] Ghostclaw Lynx)
[//]: # ([Web] Armory doesnt work)

**Description**: 
This report is not exclusively about the Dangerous! quest, it is more aimed at the issue where an item will get deleted upon completing the quest without enough inventory spots available. This quest [Dangerous!] rewards the player with a choice of one item and a guaranteed [Hooded Cowl]
**Current behaviour**:
Upon completing this quest with 1 inventory slot, the guaranteed item [Hooded Cowl] gets deleted.
**Expected behaviour**: 
You should not be able to complete this quest unless you have enough bag spaces open
**Server Revision**: 
2065

**Comment by Manaci** [comment]
Fixed
