### ISSUE TITLE
[Hunter][Pet][Spell] Can't revive pet if the corpse has disappeared

### ISSUE THREAD

**Issue by Tereneckla** [Atlantiss/NetherwingBugtracker#7110]
[//]: # (Enclose links to things related to the bug using http://wowhead.com or any other TBC database.)
[//]: # (You can use screenshot ingame to visual the issue.)
[//]: # (Write your tickets according to the format:)
[//]: # ([Quest][Azuremyst Isle] Red Snapper - Very Tasty!)
[//]: # ([NPC] Magistrix Erona)
[//]: # ([Spell][Mage] Fireball)
[//]: # ([Npc][Drop] Ghostclaw Lynx)
[//]: # ([Web] Armory doesnt work)
[//]: # (To find server revision type `.server info` command in the game chat.)

**Description**: 
https://youtu.be/nXC3TJRkCkE
**Current behaviour**:
You are not able to revive your pet, losing it forever.
You are also not able to tame a new pet, as you currently have one active.
**Expected behaviour**: 
You revive your pet
**Server Revision**: 3430

**Comment by Zarant** [comment]
Issue seems partially fixed. As a side effect, issue #5730 is back again, whenever your pet despawn and appear again dead your pet will lose all passive abilities.

**Comment by Wolffenstein** [comment]
Fixed in rev 3443.
