### ISSUE TITLE
[Class] Shaman [ Spell] Fire elemental,Earth elemental totems

### ISSUE THREAD

**Issue by The14me** [Atlantiss/NetherwingBugtracker#7113]
**Current behaviour**: Both totem models bug out from time to time and show up as opposite faction.
https://streamable.com/dzvf4c

**Expected behaviour**: 
https://www.wowhead.com/npc=40830/fire-elemental-totem
https://www.wowhead.com/spell=73903/earth-elemental-totem

**Server Revision**: 
3436

**Comment by Healweed** [comment]
Also on a side note:
- Fire Elemental Fire Aura/Immolate Aura makes most of bosses "evading" the damage. Not dodge/resist or anything else. Pure "Evade"

**Comment by The14me** [comment]
I see that report, tested on some bosses=never evade. Strange

**Comment by Healweed** [comment]
This is what im speaking off
![WoWScrnShot_011520_023311](https://user-images.githubusercontent.com/52166185/86518263-37a8cc80-be28-11ea-9843-5685404d2be5.jpg)

**Comment by The14me** [comment]
That must be the issue u talking about ye.
https://github.com/Atlantiss/NetherwingBugtracker/issues/6482
I tested it on HC boss and was fine.

**Comment by Healweed** [comment]
I only came to encounter that bug only on Rage Winterchill, Anetheron, Kaz'rogal and Jan'lai(Dragonhawk boss ZA). Those i can say they had a fair share time of "evading" which was bullshit

**Comment by Tereneckla** [comment]
Model is fixed, evade has seperate issue
