### ISSUE TITLE
[Class] Shaman [Spell] Fire nova totem

### ISSUE THREAD

**Issue by The14me** [Atlantiss/NetherwingBugtracker#7116]
**Current behaviour**: Fire Nova Totem does 0 threat at summoning.

**Expected behaviour**:  ''The totem immediately drew aggro from mobs once it is put on the ground, causing them to attack and destroy often before it does any damage. Patch 3.0.8 removed this threat generation.''
'' Patch 3.0.8 (2009-01-20): Now no longer generates threat.'' so Pre that suppose to generate threat.
https://wowwiki.fandom.com/wiki/Fire_Nova_Totem#:~:text=8%20removed%20this%20threat%20generation,high%20Fire%20resistant%20players%2Fmobs.
https://medium.com/@wshsy1984/wow-classics-most-comprehensive-shaman-totems-information-analysis-dfcea6efba70
"When this totem is dropped, it causes a large amount of threat for the totem itself. This means that if all mobs in the area do not already have a decent amount of threat on yourself or other players in your group, they will attack the Fire Nova totem"

**Server Revision**: 
2.0.3

**Comment by Wolffenstein** [comment]
Fixed in rev 3438.
