### ISSUE TITLE
[Class] Warrior [Spell] Intervene

### ISSUE THREAD

**Issue by The14me** [Atlantiss/NetherwingBugtracker#7117]
**Current behaviour**: You can ''bypass'' the spell effect if u spam the spell.Testen with Blind+Sap
https://streamable.com/w5ea4i

**Expected behaviour**: 
https://shadowlands.wowhead.com/spell=3411/intervene
https://shadowlands.wowhead.com/spell=3411/intervene#comments:id=340551
Tested on top of each other...still didn't work.

**Server Revision**: 
3436

**Comment by tsuone** [comment]
This only happened when you spammed Sap on the target. When you waited a bit between clicks it worked right.

**Comment by Tereneckla** [comment]
Fixed in 3432
