### ISSUE TITLE
[Spell][Warrior] Sweeping strikes

### ISSUE THREAD

**Issue by fosquaker** [Atlantiss/NetherwingBugtracker#7118]
**Description**
Sweeping strikes additional attack is not affected by target armour/dodge/block chance which is abused by warriors (for exapmle dealing dmg to shaman's totems -> shaman gets full amount of dmg (like w/o armour/block etc)
**Expected behaviour**:
 addition attack must check for target's defence
**Server Revision**: 
3422

**Comment by Wolffenstein** [comment]
Need proof.

**Comment by Tereneckla** [comment]
The sweep damage is reduced by the secondary targets armor.

http://www.skill-capped.com/forums/showthread.php?18484-Sweeping-Strikes-and-Avoidance
Sweeping Strikes could not be evaded at least in cataclysm

**Comment by Easyfraggy** [comment]
This report is invalid. Theres already a dodge/parry check on the initial attack and armor is already calculated individually on NW, so that part of the report is simply false.

The only thing that might have merrit would be block but would need some very clear evidence of this.

**Comment by Tereneckla** [comment]
Yeah, looked some more
