### ISSUE TITLE
Ashenvale Quest Never Again

### ISSUE THREAD

**Issue by despairr1** [Atlantiss/NetherwingBugtracker#712]
[//]: # (Enclose links to things related to the bug using http://wowhead.com or any other TBC database.)
[//]: # (You can use screenshot ingame to visual the issue.)
[//]: # (Write your tickets according to the format:)
[//]: # ([Quest][Azuremyst Isle] Red Snapper - Very Tasty!)
[//]: # ([NPC] Magistrix Erona)
[//]: # ([Spell][Mage] Fireball)
[//]: # ([Npc][Drop] Ghostclaw Lynx)
[//]: # ([Web] Armory doesnt work)

**Description**: 
Quest to kill 2 demons
**Current behaviour**:
Diathorous is glitched out of the map. I can target him but cannot see him where he is supposed to be.
**Expected behaviour**: 
Capability of actually killing the mob
**Server Revision**: 
2065

**Comment by aresbrutus** [comment]
He is not glitched, he has 4 spawn points in that cave. You probably could target him due to him being in view distance but he might have been at a different floro.

**Comment by despairr1** [comment]
I had checked all spawn points multiple times while targeting him. Maybe I
missed one I guess but I covered that entire cave!
