### ISSUE TITLE
Deep thunder/storm herald able to stun bosses

### ISSUE THREAD

**Issue by Ell1988** [Atlantiss/NetherwingBugtracker#7120]
i was on karazhan ptr and ran some hcs with a group and my deep thunder was able to stun bosses! i also then tested if hammer of justice would work and it did the bosses are stunable and we was able to slow them with frost shock and kite them. not sure if this is due to the ptr but wanted to let you guys know.

**Comment by Wolffenstein** [comment]
Fixed in rev 3440.
