### ISSUE TITLE
[Spell][Warlock] Seduction does not share DR with Fear

### ISSUE THREAD

**Issue by 4egito** [Atlantiss/NetherwingBugtracker#7121]
[//]: # (Enclose links to things related to the bug using http://wowhead.com or any other TBC database.)
[//]: # (You can use screenshot ingame to visual the issue.)
[//]: # (Write your tickets according to the format:)
[//]: # ([Quest][Azuremyst Isle] Red Snapper - Very Tasty!)
[//]: # ([NPC] Magistrix Erona)
[//]: # ([Spell][Mage] Fireball)
[//]: # ([Npc][Drop] Ghostclaw Lynx)
[//]: # ([Web] Armory doesnt work)
[//]: # (To find server revision type `.server info` command in the game chat.)

**Description**: 
Seduction does not share DR with Fear
**Current behaviour**:
https://drive.google.com/file/d/1EmmV6D9pSOAmBTDoQZDybqV1F0hPAUvF/view?usp=sharing
**Expected behaviour**: 
![image](https://user-images.githubusercontent.com/52432938/86523426-e07d1900-be74-11ea-86b8-a00333fe3310.png)
![image](https://user-images.githubusercontent.com/52432938/86523436-073b4f80-be75-11ea-90b1-8bbc3fa0de54.png)
Sources: https://wow.gamepedia.com/index.php?title=Diminishing_returns&oldid=1663771 , https://classic.wowhead.com/spell=6358/seduction#comments:id=8883
**Server Revision**:

**Comment by BamboozleNW** [comment]
These do share DR. Tested, can be closed.
