### ISSUE TITLE
[Spell][Hunter] Scatter Shot does not DR with itself in PvP

### ISSUE THREAD

**Issue by 4egito** [Atlantiss/NetherwingBugtracker#7122]
[//]: # (Enclose links to things related to the bug using http://wowhead.com or any other TBC database.)
[//]: # (You can use screenshot ingame to visual the issue.)
[//]: # (Write your tickets according to the format:)
[//]: # ([Quest][Azuremyst Isle] Red Snapper - Very Tasty!)
[//]: # ([NPC] Magistrix Erona)
[//]: # ([Spell][Mage] Fireball)
[//]: # ([Npc][Drop] Ghostclaw Lynx)
[//]: # ([Web] Armory doesnt work)
[//]: # (To find server revision type `.server info` command in the game chat.)

**Description**: 
Scatter Shot does not DR with itself in PvP
**Current behaviour**:
https://drive.google.com/file/d/1ygHPMhOrsVY7B4rSUEOHcHWa75RWbSCf/view?usp=sharing
**Expected behaviour**: 
"Scatter shot" is on his own DR category so it should share diminishing return with other scatter shots in PvP
**Server Revision**:

**Comment by Wolffenstein** [comment]
Fixed in rev 3446.
