### ISSUE TITLE
[Spell][Mage] Dragon's Breath does not share DR with itself in PvP

### ISSUE THREAD

**Issue by 4egito** [Atlantiss/NetherwingBugtracker#7123]
[//]: # (Enclose links to things related to the bug using http://wowhead.com or any other TBC database.)
[//]: # (You can use screenshot ingame to visual the issue.)
[//]: # (Write your tickets according to the format:)
[//]: # ([Quest][Azuremyst Isle] Red Snapper - Very Tasty!)
[//]: # ([NPC] Magistrix Erona)
[//]: # ([Spell][Mage] Fireball)
[//]: # ([Npc][Drop] Ghostclaw Lynx)
[//]: # ([Web] Armory doesnt work)
[//]: # (To find server revision type `.server info` command in the game chat.)

**Description**: 
Dragon's Breath does not share DR with itself in PvP
**Current behaviour**:
https://drive.google.com/file/d/15vSUpzSY2dIN3Y4x177bkYP1GqHvJi2c/view?usp=sharing
**Expected behaviour**: 
"Dragon's Breath" is on his own DR category so it should share diminishing return with other Dragon's Breats in PvP
**Server Revision**:

**Comment by BamboozleNW** [comment]
Tested and it does not have a DR with itself, however, I cannot find any data on this. Will look into it more.

**Comment by 4egito** [comment]
I cant find anything too. Also i checked source code of addons like "Gladdy" and "DRTracker" but there's nothing for "Dragon's Breath"... But like every CC effect in PvP it should DR at least with itself.

**Comment by Wolffenstein** [comment]
Fixed in rev 3446.
