### ISSUE TITLE
[Item] Stormherald stun proc does not share DR with "Mace stun specialization"

### ISSUE THREAD

**Issue by 4egito** [Atlantiss/NetherwingBugtracker#7124]
[//]: # (Enclose links to things related to the bug using http://wowhead.com or any other TBC database.)
[//]: # (You can use screenshot ingame to visual the issue.)
[//]: # (Write your tickets according to the format:)
[//]: # ([Quest][Azuremyst Isle] Red Snapper - Very Tasty!)
[//]: # ([NPC] Magistrix Erona)
[//]: # ([Spell][Mage] Fireball)
[//]: # ([Npc][Drop] Ghostclaw Lynx)
[//]: # ([Web] Armory doesnt work)
[//]: # (To find server revision type `.server info` command in the game chat.)

**Description**: 
Stormherald stun proc does not share DR with "Mace stun specialization"
**Current behaviour**:
https://drive.google.com/file/d/1qmKNl8QUXBXuDzQLgOsO91yfU73HGxFo/view?usp=sharing
**Expected behaviour**: 
Stormherald stun proc **SHOULD** share DR with "Mace stun specialization" because they are both in random stuns category.
![image](https://user-images.githubusercontent.com/52432938/86523663-1243af00-be78-11ea-9bd5-81c3872c11f6.png)
https://www.wowhead.com/forums&topic=21733
**Server Revision**:

**Comment by Tereneckla** [comment]
Sharing DR when actually using the weapon and having the talent
