### ISSUE TITLE
[Mage] Enigma Vestments 3 piece bonus

### ISSUE THREAD

**Issue by x-x-x-x-x-x-x-x-x-x-x-x** [Atlantiss/NetherwingBugtracker#7125]
[Enigma's Solitude](https://tbc-twinhead.twinstar.cz/?spell=26132) never procs
**Expected behaviour**
>> 3-set: Despite the wording, this is not 30% spell pushback resistance. It's a 30% chance to gain Enigma's Solitude, which grants spell pushback immunity for Blizzard (and no other spell) for 8 seconds. A rather weak, unreliable set bonus, though far from our worst (see: Improved Arcane Intellect). [[source](https://classic.wowhead.com/item-set=503/enigma-vestments#comments:id=3193548)]

**Server Revision**: 
3441

**Comment by ScottieDOESknow** [comment]
Did you test this at level 70? If so, it has a lower, nearly non-existent proc chance like many other pre-TBC items.

Also, isn't this set from AQ? It most likely won't be available outside of PTR since you can't enter AQ.

**Comment by SwiftieTBC** [comment]
Confirmed, this doesn't proc. Tested as a level 60 mage versus level 60 mobs and still no proc.

**Comment by networm555** [comment]
why even bother. there will be no war event. aq gates closed. item unobtainable.

**Comment by Godmatik** [comment]
Was fixed several months ago.
