### ISSUE TITLE
[Quest] The Black Shield

### ISSUE THREAD

**Issue by xycz** [Atlantiss/NetherwingBugtracker#7126]
**Description**: The "second" quest chain which starts off by sending the player to [Mosarn](https://tbcdb.com/?npc=4943) in Thunder Bluff is not started by [Krog](https://tbcdb.com/?npc=4926)

**Current behaviour**: [Krog](https://tbcdb.com/?npc=4926) does not start the quest chain beginning with "[The Black Shield (Part 5)](https://tbcdb.com/?quest=1276)" after a player has finished [The Black Shield (Part 4)](https://tbcdb.com/?quest=1323)

**Expected behaviour**: [Krog](https://tbcdb.com/?npc=4926) should start the quest chain beginning with "[The Black Shield (Part 5)](https://tbcdb.com/?quest=1276)" after a player has finished [The Black Shield (Part 4)](https://tbcdb.com/?quest=1323)

**Server Revision**: 3441

**Comment by Tereneckla** [comment]
You need to have done https://tbcdb.com/?quest=1273 aswell.
Easy to miss as no quest leads there. It's just in the text when you turn in the quest that you should seek out Ogron.
