### ISSUE TITLE
[NPC] [Pathing] Swimming/Underwater NPCs

### ISSUE THREAD

**Issue by Drayo** [Atlantiss/NetherwingBugtracker#7127]
[//]: # (Enclose links to things related to the bug using http://wowhead.com or any other TBC database.)
[//]: # (You can use screenshot ingame to visual the issue.)
[//]: # (Write your tickets according to the format:)
[//]: # ([Quest][Azuremyst Isle] Red Snapper - Very Tasty!)
[//]: # ([NPC] Magistrix Erona)
[//]: # ([Spell][Mage] Fireball)
[//]: # ([Npc][Drop] Ghostclaw Lynx)
[//]: # ([Web] Armory doesnt work)
[//]: # (To find server revision type `.server info` command in the game chat.)

**Issues**:

- Some mobs can be reset by strafe jumping at the surface. https://youtu.be/kDf9szAQYQg 
_This was fixed for some mobs, maybe it has to do with their size? (https://github.com/Atlantiss/NetherwingBugtracker/issues/3087 these no longer reset prematurely)_

- The bigger mobs that do not reset have weird pathing when you strafe jump in the water. https://youtu.be/8hWwLk9JrSQ
_They always try to swim to the bottom while the player is in the air. If done right, you can avoid any damage after a few jumps._

- Levitate/Water Walking makes you completely immune to mobs aggroing you, it shouldn't. https://i.imgur.com/Mnr7svb.jpg

I remember them aggroing you on retail since forever. Best Source I could find is this: http://zemalf.blogspot.com/2009/01/wow-achievements-accomplished-angler.html

> Head into ZG again and water walk to the Zulian Mudfish pools and fish 5 up (bring a few water walking pots with you--if you can't solo the groups of alligator's that is--**because the fish that live there will attack you from time to time** (make sure you can solo a level 60 elite fish) **and take off the water walking buff.**

**Server Revision**: 3442

**Comment by Wolffenstein** [comment]
Fixed in rev 3444.
