### ISSUE TITLE
[NPC] [The Underbog] [2.0] - Overseer Tidewrath

### ISSUE THREAD

**Issue by Drayo** [Atlantiss/NetherwingBugtracker#7128]
**Description**: 

Early on in TBC and throughout the Beta, there was an extra Boss in The Underbog named Overseer Tidewrath.

- He stood on Gaz'han's platform. _https://i.imgur.com/8E7QS6N.jpg_ 
_A .gps of the spot: https://i.imgur.com/3Gt3tcK.jpg_

- When players reach the area around the pool, Gaz'han starts his RP walk moving up to the Platform. 
When Gaz'han reaches Overseer Tidewrath he kills him. If the players managed to reach him before he got killed by Gaz'han, they could kill and loot him. _https://wowwiki.fandom.com/wiki/Overseer_Tidewrath_

- The Beastiary has an entry for him. Stats for heroic would have to be made up, but that should not be too difficult. https://i.imgur.com/69otT8E.png

_Spout might be: https://www.wowhead.com/spell=39207/water-spout-warning or https://www.wowhead.com/spell=35499/water-spout and could potentially be cast on random players instead of just the main target._

- While the Wiki says players would be rewarded with "nice loot", accounts from the beta imply that he had no loottable on the Beta.  _https://web.archive.org/web/20070208185024/http://thottbot.com/beta?n=4445_

Now the only issue is the loot, it would be boring if he would drop nothing at all. 

My recommendation would be to just let him drop some Mana/Health Potions and maybe 2-3 Coilfang Armaments on normal and Heroic. On Heroic only he could also drop an extra Badge of Justice, just like Blood Guard Porung in SHH HC. But like I said, that would just be my thoughts on it, maybe someone has a more fitting idea.

**Server Revision**: 3442

**Comment by Wolffenstein** [comment]
He was only in the Beta, we already discussed him prior to Netherwing launch and decided to not add him.
