### ISSUE TITLE
Blizzard on Shade of Aran

### ISSUE THREAD

**Issue by koochy414** [Atlantiss/NetherwingBugtracker#7129]
[//]: # (Enclose links to things related to the bug using http://wowhead.com or any other TBC database.)
[//]: # (You can use screenshot ingame to visual the issue.)
[//]: # (Write your tickets according to the format:)
[//]: # ([Quest][Azuremyst Isle] Red Snapper - Very Tasty!)
[//]: # ([NPC] Magistrix Erona)
[//]: # ([Spell][Mage] Fireball)
[//]: # ([Npc][Drop] Ghostclaw Lynx)
[//]: # ([Web] Armory doesnt work)
[//]: # (To find server revision type `.server info` command in the game chat.)

**Description**: 
Shade of Aran is casting multiple blizzards instead of 1 instance of blizzard.

**Current behaviour**:
shade of aran cycling through his spells like usual, when he casts blizzard, multiple will spawn instead of one

**Expected behaviour**: 
One blizzard should spawn not several

**Server Revision**: 
3441

**Comment by Wolffenstein** [comment]
Fixed in rev 3445.
