### ISSUE TITLE
Quest Innoculation, Not Working

### ISSUE THREAD

**Issue by diablokls** [Atlantiss/NetherwingBugtracker#713]
([Quest][Azuremyst Isle] Inoculation)

Not getting any sort of credit for using the crystal on the Nestlewood Owlkin. Attempted at different ranges. This is on a Priest if that matters at all.

I am getting credit from killing the mobs rather than using the crystal on them.

**Comment by Easyfraggy** [comment]
Refer to https://github.com/Atlantiss/NetherwingBugtracker/issues/790 for more details

**Comment by Azalen** [comment]
This is still not working. You get quest credit for killing them but not for using the item. Super weird.

**Comment by Wolffenstein** [comment]
Fixed in rev 2401. Remember to remove the quest from your log, logout and delete cache.
