### ISSUE TITLE
Shade of Aran Arcane Explosion 

### ISSUE THREAD

**Issue by koochy414** [Atlantiss/NetherwingBugtracker#7130]
[//]: # (Enclose links to things related to the bug using http://wowhead.com or any other TBC database.)
[//]: # (You can use screenshot ingame to visual the issue.)
[//]: # (Write your tickets according to the format:)
[//]: # ([Quest][Azuremyst Isle] Red Snapper - Very Tasty!)
[//]: # ([NPC] Magistrix Erona)
[//]: # ([Spell][Mage] Fireball)
[//]: # ([Npc][Drop] Ghostclaw Lynx)
[//]: # ([Web] Armory doesnt work)
[//]: # (To find server revision type `.server info` command in the game chat.)

**Description**: 
Shade of Aran pulls everyone in to cast arcane explosion, but people are teleported in random locations

**Current behaviour**:
When everyone gets pulled in they are teleported to random locations instead of the middle

**Expected behaviour**: 
people should get pulled in to the middle

**Server Revision**: 
3441

**Comment by Wolffenstein** [comment]
Video?

**Comment by Wolffenstein** [comment]
Fixed in rev 3445.
