### ISSUE TITLE
Skeletal Ushers can't be shackled.

### ISSUE THREAD

**Issue by ArchivisX** [Atlantiss/NetherwingBugtracker#7131]
On Karazhan server, the Skeletal Ushers cannot be shackled, even though I know they can in original TBC.  They also immediately use their abilities (ice block/vortex).  Those typically have a CD before they can activate.

**Comment by Drayo** [comment]
https://wowwiki.fandom.com/wiki/Patch_2.1.0

> Skeletal Ushers can now be affected by Shackle Undead. 

Kara is on Patch 2.0

Small Tip: You can you a free action Potion on tanks to beat them easily.

**Comment by Tereneckla** [comment]
Prenerf behaviour and intended
