### ISSUE TITLE
Falling outside of the raid (kara - nightbane)

### ISSUE THREAD

**Issue by notoriouscow** [Atlantiss/NetherwingBugtracker#7132]
[//]: # (Enclose links to things related to the bug using http://wowhead.com or any other TBC database.)
[//]: # (You can use screenshot ingame to visual the issue.)
[//]: # (Write your tickets according to the format:)
[//]: # ([Quest][Azuremyst Isle] Red Snapper - Very Tasty!)
[//]: # ([NPC] Magistrix Erona)
[//]: # ([Spell][Mage] Fireball)
[//]: # ([Npc][Drop] Ghostclaw Lynx)
[//]: # ([Web] Armory doesnt work)
[//]: # (To find server revision type `.server info` command in the game chat.)

**Description**: 
Felt outside of the raid In kara PTR server while fighting nightbane
character name: testinggreen (warlock).
reason of falling: nightbane fear. I was close to the left wall, and it made me fall through the wall into the outside of karazhan.
recording of the moment (sadly doesn't capture me, from the paladin POV): [](https://www.youtube.com/watch?v=YM6OfVFhsrY&feature=youtu.be&t=6547)
race: Female orc
discord name: ilovekababs#1574 (in case i can help with anthing).

**Comment by Wolffenstein** [comment]
Already reported in the past, impossible to reproduce reliably.
