### ISSUE TITLE
[NPC] [The Botanica] - High Botanist Freywinn

### ISSUE THREAD

**Issue by Drayo** [Atlantiss/NetherwingBugtracker#7133]
**Current behaviour**: 

When he changes into Tree Form, three Frayer Protectors spawn. When you kill the adds, the boss goes back into his normal form and the fight goes on as usual. This is working fine.

- However, when you simply **wait for the Boss to finish channeling** his Tranquillity, **the Frayer Protectors instantly despawn** and the Boss **will not cast anything anymore for the rest of the fight.** (You can also kill 1-2 out of the 3 Frayer Protectors to make the waiting time easier)

**Expected behaviour**:  

- If you do not manage to kill the 3 Frayer Protectors in time, **they should die and their corpses should despawn** after ~10 seconds. The Boss should **continue to summon his small Seedlings** as usual. After around 30s **he should cast the next Tranquillity and summon 3 Frayer Protectors** again.

**Note:** **For this fix to be worth it, https://github.com/Atlantiss/NetherwingBugtracker/issues/4518 also needs to be fixed.**

**Server Revision**: 3442

**Comment by Wolffenstein** [comment]
Fixed in rev 3452.
