### ISSUE TITLE
Alchemy

### ISSUE THREAD

**Issue by networm555** [Atlantiss/NetherwingBugtracker#7136]
Elixir of Draenic wisdom. You can learn it from Apothecary Antonivich, but the system can't see the data about it. You can learn but cant craft. If I remember correctly, it's a later patch elixir.
Also, the profession window didn't renew information for me after I crafted something. Has to reopen the window. That's something new lol.

**Comment by Tereneckla** [comment]
Yes, it's a 2.1 recipe
I have no clue what you mean about the profession window not renewing though.

**Comment by networm555** [comment]
This bug was on the pre-release ptr. When you crafted something you didn't see reagents spending. How it is possible that it appeared again?

**Comment by Tereneckla** [comment]
I cannot recreate that. It might be an addon that you use.

**Comment by networm555** [comment]
![WoWScrnShot_070820_005823](https://user-images.githubusercontent.com/43811642/86822790-44425480-c0b6-11ea-9979-0e8a3044da4b.jpg)
addons disabled cache deleted

**Comment by networm555** [comment]
thinking that recipe i have learned killed my client for good O_O.

**Comment by networm555** [comment]
dowloaded fresh client from your site. Its the same shit. 100% server side

**Comment by Wolffenstein** [comment]
The NPC probably teaches it even though the item itself is not available, leading to client issues

**Comment by networm555** [comment]
Can you delete it from my char?

**Comment by Wolffenstein** [comment]
Fixed in rev 3459.
