### ISSUE TITLE
[Quest] Call of Fire (Alliance)

### ISSUE THREAD

**Issue by totaemoeggerli** [Atlantiss/NetherwingBugtracker#7138]
**Current behaviour**:
Draenai Shamans don't get [Call of Fire(2)](https://www.wowhead.com/quest=9464/call-of-fire) from [Tuluun](https://www.wowhead.com/npc=17212) in Azure Watch. They have to complete the breadcrumb quest [Call to Fire(1)](https://www.wowhead.com/quest=9462/call-of-fire) first. Currently there is no quest in Azure Watch that leads you to your level 10 class quest and you have to run to Exodar and back for no reason.

**Expected behaviour**:
[Call to Fire(1)](https://www.wowhead.com/quest=9462/call-of-fire) is a "breadcrumb quest that isn't required to start the actual quest line. Here is a blue post from 2007 that refers to it as such: https://blue.mmo-champion.com/topic/39870-fire-totem-quest-bugged-for-select-draenei/ . It should be possible to start the actual quest line from Tuluun in Azure Watch.

**Server Revision**: 3454
This was tested on the Netherwing server.

**Comment by Wolffenstein** [comment]
Fixed in rev 3461.
