### ISSUE TITLE
[Class] Warrior [Spell] Thunder Clap

### ISSUE THREAD

**Issue by Zubrahz** [Atlantiss/NetherwingBugtracker#7139]
Description: 
Improved Thunder Clap talent doesn't work or visual bug.  
Current behaviour:
Improved Thunder Clap reducing attack speed by 10%.

Expected behaviour: 
Improved Thunder Clap should reduce attack speed by 20%.
![WoWScrnShot_070820_220149](https://user-images.githubusercontent.com/68028990/86959565-b5d9db80-c166-11ea-949f-7ead6052e5a7.jpg)
![WoWScrnShot_070820_220145](https://user-images.githubusercontent.com/68028990/86959568-b6727200-c166-11ea-81c8-34e6e9d3dbf5.jpg)

Server Revision: 
Karazhan PTR

**Comment by Tereneckla** [comment]
Buffs/debuffs don't get changed with talents in tbc
