### ISSUE TITLE
[NPC][Quest] Teribus the Cursed/Evil Draws Near

### ISSUE THREAD

**Issue by bekonja** [Atlantiss/NetherwingBugtracker#7140]
[//]: # (Enclose links to things related to the bug using http://wowhead.com or any other TBC database.)
[//]: # (You can use screenshot ingame to visual the issue.)
[//]: # (Write your tickets according to the format:)
[//]: # ([Quest][Azuremyst Isle] Red Snapper - Very Tasty!)
[//]: # ([NPC] Magistrix Erona)
[//]: # ([Spell][Mage] Fireball)
[//]: # ([Npc][Drop] Ghostclaw Lynx)
[//]: # ([Web] Armory doesnt work)
[//]: # (To find server revision type `.server info` command in the game chat.)

**Description**: 
https://tbcdb.com/?quest=10923
https://tbcdb.com/?npc=22441

**Current behaviour**:
After summonning the dragon he got stuck in his landing spot, evading if attacking from afar.

**Expected behaviour**: 
Shouldnt get stuck

**Server Revision**: 
3460

**Comment by Wolffenstein** [comment]
Fixed in rev 3492.
