### ISSUE TITLE
[NPC] [Spell] [Karazhan] Spectral Stable Hand

### ISSUE THREAD

**Issue by Drayo** [Atlantiss/NetherwingBugtracker#7141]
**Current behaviour**: 

- They do not seem to use [Whip Rage](https://www.wowhead.com/spell=29340/whip-rage).

**Expected behaviour**:  

- They should cast Whip Rage at the Horses from time to time. Similar CD as the heal I guess.

**Source**: https://www.wowhead.com/npc=15551/spectral-stable-hand#abilities 

**Server Revision**: 3460

**Comment by Wolffenstein** [comment]
Fixed in rev 3469.
