### ISSUE TITLE
[Item]Draenic Leather Pack

### ISSUE THREAD

**Issue by bekonja** [Atlantiss/NetherwingBugtracker#7143]
[//]: # (Enclose links to things related to the bug using http://wowhead.com or any other TBC database.)
[//]: # (You can use screenshot ingame to visual the issue.)
[//]: # (Write your tickets according to the format:)
[//]: # ([Quest][Azuremyst Isle] Red Snapper - Very Tasty!)
[//]: # ([NPC] Magistrix Erona)
[//]: # ([Spell][Mage] Fireball)
[//]: # ([Npc][Drop] Ghostclaw Lynx)
[//]: # ([Web] Armory doesnt work)
[//]: # (To find server revision type `.server info` command in the game chat.)

**Description**: 
https://tbcdb.com/?item=30744
https://www.wowhead.com/item=30744/draenic-leather-pack#sold-by
https://web.archive.org/web/20111016162222/https://www.wowhead.com/item=30744#sold-by

**Current behaviour**:
Only sold by 1 horde and 2 ally vendors

**Expected behaviour**: 
From earliest archive snapshots and comments it should be sold by other Outlands' Innkeepers as well.

**Server Revision**: 
3472

**Comment by Tereneckla** [comment]
Only 3 npcs sell it on [thottbot](http://web.archive.org/web/20080916131637/http://thottbot.com/i30744)
I cannot find any changes to that in patchnotes or comments
thottbot data might be incomplete

**Comment by Wolffenstein** [comment]
Fixed in rev 3473.
