### ISSUE TITLE
[NPC][Spell] Collapsing Voidwalker doesn't explode on death

### ISSUE THREAD

**Issue by Tereneckla** [Atlantiss/NetherwingBugtracker#7144]
[//]: # (Enclose links to things related to the bug using http://wowhead.com or any other TBC database.)
[//]: # (You can use screenshot ingame to visual the issue.)
[//]: # (Write your tickets according to the format:)
[//]: # ([Quest][Azuremyst Isle] Red Snapper - Very Tasty!)
[//]: # ([NPC] Magistrix Erona)
[//]: # ([Spell][Mage] Fireball)
[//]: # ([Npc][Drop] Ghostclaw Lynx)
[//]: # ([Web] Armory doesnt work)
[//]: # (To find server revision type `.server info` command in the game chat.)

**Description**: 
![image](https://user-images.githubusercontent.com/50233983/87154858-3ceb9880-c2ba-11ea-999f-4f372250a4d9.png)
https://www.wowhead.com/npc=17014/collapsing-voidwalker#abilities
**Current behaviour**:
https://www.wowhead.com/spell=34234/collapse is not cast on death
**Expected behaviour**: 
It is cast on death
**Server Revision**: 3472

**Comment by The14me** [comment]
Its supposed trigger at like 20% HP, not on the dead.

**Comment by Tereneckla** [comment]
He does the self destruct. The explosion on death is seperate.

**Comment by Godmatik** [comment]
Rev 4015 - no longer an issue, they proper hit you with collapse upon death.
