### ISSUE TITLE
[Spell][Warrior] Intervene

### ISSUE THREAD

**Issue by tsuone** [Atlantiss/NetherwingBugtracker#7146]
[//]: # (Enclose links to things related to the bug using http://wowhead.com or any other TBC database.)
[//]: # (You can use screenshot ingame to visual the issue.)
[//]: # (Write your tickets according to the format:)
[//]: # ([Quest][Azuremyst Isle] Red Snapper - Very Tasty!)
[//]: # ([NPC] Magistrix Erona)
[//]: # ([Spell][Mage] Fireball)
[//]: # ([Npc][Drop] Ghostclaw Lynx)
[//]: # ([Web] Armory doesnt work)
[//]: # (To find server revision type `.server info` command in the game chat.)

**Description**: Intervene Redirect Damage Aura changes.

**Current behaviour**: Intervene redirects damage up to 25 yards away from the intervened target.

**Expected behaviour**: Intervene should redirect damage if you are maximum of _10 YARDS (tooltip)_ but in reality **7.5 YARDS** (bug on the retail wow back in the day) away from the **INTERVENED** friendly target. It should also redirect only **PHYSICAL** type damage. _(This part I did not test on the server, but I am putting it out to confirm it will be checked and fixed.)_

**Server Revision**: After Intervene Rework.

**Comment by Wolffenstein** [comment]
Fixed in rev 3475.
