### ISSUE TITLE
[NPC] [Ability] Fetid Zombie - Overwhelming Musk

### ISSUE THREAD

**Issue by Drayo** [Atlantiss/NetherwingBugtracker#7147]
**Description**: 

- [Fetid Zombies](https://classic.wowhead.com/npc=10580/fetid-zombie#abilities) Ability [Overwhelming Musk](https://classic.wowhead.com/spell=8713/overwhelming-musk) seems to stack, thus ticking about 10 times a second.

https://i.imgur.com/JciDmwJ.jpg

**Server Revision**: 3472

**Comment by Wolffenstein** [comment]
Fixed in rev 3475.
