### ISSUE TITLE
Spellqueue

### ISSUE THREAD

**Issue by malboroman1** [Atlantiss/NetherwingBugtracker#7148]
[//]: # (Enclose links to things related to the bug using http://wowhead.com or any other TBC database.)
[//]: # (You can use screenshot ingame to visual the issue.)
[//]: # (Write your tickets according to the format:)
[//]: # ([Quest][Azuremyst Isle] Red Snapper - Very Tasty!)
[//]: # ([NPC] Magistrix Erona)
[//]: # ([Spell][Mage] Fireball)
[//]: # ([Npc][Drop] Ghostclaw Lynx)
[//]: # ([Web] Armory doesnt work)
[//]: # (To find server revision type `.server info` command in the game chat.)

**Description**: 
Spellqueue is not working for melee abilities.
**Current behaviour**:
If sunder armor is pressed just before the gcd finishes the ability is not used.
**Expected behaviour**: 
If a spell is used within the spellqueue window it should be used immediately after the gcd ends. This should included melee abilities such as sunder armor. I tested this is classic and attached a recorded video. During the gcd sunder armor is used once and it applies after the gcd ends. I tried this on Netherwing and sunder armor is not used after the gcd ends.

[World of Warcraft 2020-07-10 20-57-06.zip](https://github.com/Atlantiss/NetherwingBugtracker/files/4906089/World.of.Warcraft.2020-07-10.20-57-06.zip)

**Server Revision**:

**Comment by Wolffenstein** [comment]
Classic has a different architecture than 2.4.3 or old vanilla. What currently blocks you is not the server but the client - no packets are even sent to the server (unless you cheat the client in which case the server will deny you). Nothing can be done with this unfortunately.
