### ISSUE TITLE
[PTR 2.0] Healing stream totems

### ISSUE THREAD

**Issue by networm555** [Atlantiss/NetherwingBugtracker#7149]
Healing stream totem not appearing in the recount and not affecting threat. Fix it please its essential to see it for some encounters like Reaver, Morogrim, Netherspite, Solarian and etc. It appears in the combat log but doesn't matter if you in combat or not, addons ignoring it like it does not exist.  Mana stream totem is working properly, what's wrong with healing one?

**Comment by Drayo** [comment]
- Mana Spring and Healing Stream not causing threat is correct. https://blue.mmo-champion.com/topic/18607-how-do-aggro-and-threat-work-in-wow/


Healing Stream totem not showing up on recount is 99% just recount being trash. 

- Recount CAN actually show the healing done by the Healing Stream Totem. AND it also shows as the casters "pet". https://i.imgur.com/pZtE31X.png

It is unfortunately just unable to merge it with it's owner. That is a recount isssue though, not a server issue. https://i.imgur.com/62LP25I.png
