### ISSUE TITLE
[Quest][Ashenvale] Freedom to Ruul

### ISSUE THREAD

**Issue by Pennywise4569** [Atlantiss/NetherwingBugtracker#715]
[//]: # (Enclose links to things related to the bug using http://wowhead.com or any other TBC database.)
[//]: # (You can use screenshot ingame to visual the issue.)
[//]: # (Write your tickets according to the format:)
[//]: # ([Quest][Azuremyst Isle] Red Snapper - Very Tasty!)
[//]: # ([NPC] Magistrix Erona)
[//]: # ([Spell][Mage] Fireball)
[//]: # ([Npc][Drop] Ghostclaw Lynx)
[//]: # ([Web] Armory doesnt work)

**Description**: While the quest is able to be completed, there are a few things wrong. 

**Current behaviour**: When ambushing mobs spawn during quest, they won't instantly aggro like normal. Also the quest ends very early, right outside the cave, when you are supposed to escort him out of the camp entirely.

**Expected behaviour**: Ambushing mobs aggro instantly, quest ends outside the camp, and the NPC says dialogue about being saved.

**Server Revision**: 2067

**Comment by aresbrutus** [comment]
Thank you for the report. The issue is known: https://github.com/Atlantiss/AtlantissTBCBT/issues/1943

**Comment by totaemoeggerli** [comment]
wowhead comment confirms that the escort should be longer
By hhallahh (1,966 – 3·16) on 2007/08/23 (Patch 2.1.3)

> ...At the end (past one of the gates, I forget exactly where), you have to deal with another 3-pack.

**Comment by aresbrutus** [comment]
https://github.com/Atlantiss/NetherwingBugtracker/issues/3678
