### ISSUE TITLE
[Quest] You, Robot

### ISSUE THREAD

**Issue by bekonja** [Atlantiss/NetherwingBugtracker#7150]
[//]: # (Enclose links to things related to the bug using http://wowhead.com or any other TBC database.)
[//]: # (You can use screenshot ingame to visual the issue.)
[//]: # (Write your tickets according to the format:)
[//]: # ([Quest][Azuremyst Isle] Red Snapper - Very Tasty!)
[//]: # ([NPC] Magistrix Erona)
[//]: # ([Spell][Mage] Fireball)
[//]: # ([Npc][Drop] Ghostclaw Lynx)
[//]: # ([Web] Armory doesnt work)
[//]: # (To find server revision type `.server info` command in the game chat.)

**Description**: 
https://tbcdb.com/?quest=10248
https://tbcdb.com/?npc=19851

**Current behaviour**:
Spawns 2 Negatrons. One stays inactive and despawns couple of minutes after. Doctor Vomisa, Ph.T. (questgiver NPC) stays in "locked" state unill second Negatron despawns.

**Expected behaviour**: 
1 Negatron.

**Server Revision**: 
3478

**Comment by Wolffenstein** [comment]
Can't reproduce.
