### ISSUE TITLE
[NPC][Spell] Unstable Voidwraith - Unstable Rift

### ISSUE THREAD

**Issue by bekonja** [Atlantiss/NetherwingBugtracker#7151]
[//]: # (Enclose links to things related to the bug using http://wowhead.com or any other TBC database.)
[//]: # (You can use screenshot ingame to visual the issue.)
[//]: # (Write your tickets according to the format:)
[//]: # ([Quest][Azuremyst Isle] Red Snapper - Very Tasty!)
[//]: # ([NPC] Magistrix Erona)
[//]: # ([Spell][Mage] Fireball)
[//]: # ([Npc][Drop] Ghostclaw Lynx)
[//]: # ([Web] Armory doesnt work)
[//]: # (To find server revision type `.server info` command in the game chat.)

**Description**: 
https://tbcdb.com/?npc=18869
https://www.wowhead.com/npc=18869/unstable-voidwraith

**Current behaviour**:
Doesnt leave a corpse after self-destruction into a rift.

**Expected behaviour**: 
https://www.wowhead.com/npc=18869/unstable-voidwraith#comments:id=248211
> You might get clipped by the first "wave" of damage, but after that you're fine until it's over and you can **loot**. 

**Server Revision**: 
3478

**Comment by EtheriousNW** [comment]
Fixed
