### ISSUE TITLE
[Druid][Spell] Nature's Grace procs twice on spells with travel time

### ISSUE THREAD

**Issue by Tereneckla** [Atlantiss/NetherwingBugtracker#7152]
[//]: # (Enclose links to things related to the bug using http://wowhead.com or any other TBC database.)
[//]: # (You can use screenshot ingame to visual the issue.)
[//]: # (Write your tickets according to the format:)
[//]: # ([Quest][Azuremyst Isle] Red Snapper - Very Tasty!)
[//]: # ([NPC] Magistrix Erona)
[//]: # ([Spell][Mage] Fireball)
[//]: # ([Npc][Drop] Ghostclaw Lynx)
[//]: # ([Web] Armory doesnt work)
[//]: # (To find server revision type `.server info` command in the game chat.)

**Description**: 
![image](https://user-images.githubusercontent.com/50233983/87222069-01f86c00-c371-11ea-9a02-5d78d49f579b.png)
Nature's Grace procs when the critical spellcast has finished casting (as it should) and another time when the spell lands.

**Current behaviour**:
Procs when the critical spell lands.
**Expected behaviour**: 
Only procs when the spellcast has finished.
**Server Revision**: 3478

**Comment by Godmatik** [comment]
Duplicate
#8166
