### ISSUE TITLE
[NPC] Voidshrieker

### ISSUE THREAD

**Issue by bekonja** [Atlantiss/NetherwingBugtracker#7153]
[//]: # (Enclose links to things related to the bug using http://wowhead.com or any other TBC database.)
[//]: # (You can use screenshot ingame to visual the issue.)
[//]: # (Write your tickets according to the format:)
[//]: # ([Quest][Azuremyst Isle] Red Snapper - Very Tasty!)
[//]: # ([NPC] Magistrix Erona)
[//]: # ([Spell][Mage] Fireball)
[//]: # ([Npc][Drop] Ghostclaw Lynx)
[//]: # ([Web] Armory doesnt work)
[//]: # (To find server revision type `.server info` command in the game chat.)

**Description**: 
https://tbcdb.com/?npc=18870
https://www.wowhead.com/npc=18870

**Current behaviour**:
Casts spells from random schools. I blasted them with nature and saw shadow bolts, fireballs and lightning bolts.

**Expected behaviour**: 
https://www.wowhead.com/npc=18870/voidshrieker#comments:id=340602

> Night elf balance druids can make this particularly easy by opening with a wrath. You already have +10 nature resistance to the attacks they'll inevitably use next

Should cast school of magic that they adopted resistance for.
**Server Revision**: 
3478

**Comment by Evolvee** [comment]
its already reported
