### ISSUE TITLE
[Spell] Hex of Weakness stacking

### ISSUE THREAD

**Issue by Tereneckla** [Atlantiss/NetherwingBugtracker#7154]
[//]: # (Enclose links to things related to the bug using http://wowhead.com or any other TBC database.)
[//]: # (You can use screenshot ingame to visual the issue.)
[//]: # (Write your tickets according to the format:)
[//]: # ([Quest][Azuremyst Isle] Red Snapper - Very Tasty!)
[//]: # ([NPC] Magistrix Erona)
[//]: # ([Spell][Mage] Fireball)
[//]: # ([Npc][Drop] Ghostclaw Lynx)
[//]: # ([Web] Armory doesnt work)
[//]: # (To find server revision type `.server info` command in the game chat.)

**Description**: 
![image](https://user-images.githubusercontent.com/50233983/87226783-71348700-c396-11ea-882f-e55492b0864b.png)
![image](https://user-images.githubusercontent.com/50233983/87226871-f9b32780-c396-11ea-85fe-7ff41055e2d4.png)

**Current behaviour**: Rank 1-5 and rank 6 and rank 7 can be active at the same time for a total of 3 debuffs

**Expected behaviour**: Only 1 rank of hex of weakness can be active at the same time

**Server Revision**: 3478

**Comment by Godmatik** [comment]
Fixed in upcoming new aura branch update
