### ISSUE TITLE
Shade of Aran Polymorph Tree of Life

### ISSUE THREAD

**Issue by devo6969** [Atlantiss/NetherwingBugtracker#7155]
**Description**:
 Shade of Aran's Polymorph is still happening on players with Tree of life on the PTR. 

**Current behaviour**:
PTR - https://www.youtube.com/watch?v=xBx15KUl3Ow

**Expected behaviour**: 
https://wow.gamepedia.com/Shade_of_Aran#:~:text=after%2090%20seconds.-,Polymorph%20%2F%20Drink%20%2F%20Pyroblast,damage%20on%20the%20whole%20raid.
"Only druids in Tree of Life form remain unaffected"
Retail TBC - https://youtu.be/l0DB4lzAttw?t=206

**Server Revision**: 
3478

**Comment by Wolffenstein** [comment]
Fixed in rev 3484.
