### ISSUE TITLE
[Item][PTR 2.0] Master Hammersmith items not having their correct 2.0 procs

### ISSUE THREAD

**Issue by NetheG** [Atlantiss/NetherwingBugtracker#7157]
[//]: # (Enclose links to things related to the bug using http://wowhead.com or any other TBC database.)
[//]: # (You can use screenshot ingame to visual the issue.)
[//]: # (Write your tickets according to the format:)
[//]: # ([Quest][Azuremyst Isle] Red Snapper - Very Tasty!)
[//]: # ([NPC] Magistrix Erona)
[//]: # ([Spell][Mage] Fireball)
[//]: # ([Npc][Drop] Ghostclaw Lynx)
[//]: # ([Web] Armory doesnt work)
[//]: # (To find server revision type `.server info` command in the game chat.)

Description:
Master Hammersmith items not having their correct 2.0 procs

Current behaviour:
Drakefist Hammer (same stats but with incorrect haste rating proc)
Dragonmaw (same stats but with incorrect haste rating proc)
Dragonstrike (same stats but with incorrect haste rating proc)

Expected behaviour:
Drakefist Hammer (https://web.archive.org/web/20070312055016/thottbot.com/i28437)
Drakefist Hammer should have 12 less haste rating on proc.
Dragonmaw (https://web.archive.org/web/20070311221156/thottbot.com/i28438)
Dragonmaw should have 12 less haste rating on proc.
Dragonstrike (https://web.archive.org/web/20070315161747/thottbot.com/i28439)
Dragonstrike should have 12 less haste rating on proc.

Server Revision:
3478

**Comment by Easyfraggy** [comment]
If we start going down this road we also need to make DST with no ICD and all other proc/item changes through the patches, like Lightning capacitor etc.

**Comment by aresbrutus** [comment]
Socket changes could cause issues when it goes from 2.0 to 2.1 with already equiped sockets, but Wolf could also make all sockets unequipped and mail them back to the player with 2.1. I can provide a list of all socket color + bonus changes pre-2.1, but Wolf will have to agree to go this route. IMO they are minor changes and sadly with 2.4.3 we can't have the perfect 2.0. I would consider this minor enough not to care but up to Wolf.

**Comment by TheMoneyHater** [comment]
This is just to much, as Easyfraggy said there is thousands of changes that needs to be done then.

**Comment by Godmatik** [comment]
We are no longer doing any 2.0 stats/procs regardless, closing
