### ISSUE TITLE
[Item][PTR 2.0] Several items not in their 2.0 state

### ISSUE THREAD

**Issue by NetheG** [Atlantiss/NetherwingBugtracker#7158]
[//]: # (Enclose links to things related to the bug using http://wowhead.com or any other TBC database.)
[//]: # (You can use screenshot ingame to visual the issue.)
[//]: # (Write your tickets according to the format:)
[//]: # ([Quest][Azuremyst Isle] Red Snapper - Very Tasty!)
[//]: # ([NPC] Magistrix Erona)
[//]: # ([Spell][Mage] Fireball)
[//]: # ([Npc][Drop] Ghostclaw Lynx)
[//]: # ([Web] Armory doesnt work)
[//]: # (To find server revision type `.server info` command in the game chat.)

Description:
Several items not in their 2.0 state

Current behaviour:
Braxxis' Staff of Slumber (https://tbcdb.com/?item=31186)
Nigh Invulnerability Belt (https://tbcdb.com/?item=23825)
Destroyer Legguards (same stats but with socket)
Destroyer Greaves (same stats but with socket)
Crystalforge Legguards (same stats but with socket)
Rift Stalker Mantle (same stats but with incorrect socket bonus)
Mantle of Tirisfal (same stats but with incorrect socket bonus)
Crystalforge Pauldrons (same stats but with incorrect socket bonus)

Expected behaviour:
Braxxis' Staff of Slumber (https://web.archive.org/web/20070318140831/thottbot.com/i31186)
Braxxis' Staff of Slumber should have 58 less feral attack power and 39 less stamina.
Nigh Invulnerability Belt (https://web.archive.org/web/20070314061356/thottbot.com/i23825)
Nigh Invulnerability Belt should have 168 less armor and 5 less stamina.
Destroyer Legguards (https://web.archive.org/web/20070510195612/thottbot.com/i30116)
Destroyer Legguards shouldn't have a gem socket.
Destroyer Greaves (https://web.archive.org/web/20070519043341/thottbot.com/i30121)
Destroyer Greaves shouldn't have a gem socket.
Crystalforge Legguards (https://web.archive.org/web/20070319191922/thottbot.com/i30126)
Crystalforge Legguards shouldn't have a gem socket.
Rift Stalker Mantle (https://web.archive.org/web/20070328223440/http://thottbot.com/i30143)
Rift Stalker Mantle should have a gem socket bonus of +3 hit rating.
Mantle of Tirisfal (https://web.archive.org/web/20070421061305/thottbot.com/i30210)
Mantle of Tirsifal should have a gem socket bonus of +3 spell hit rating.
Crystalforge Pauldrons (https://web.archive.org/web/20070510051509/thottbot.com/i30138)
Crystalforge Pauldrons should have a gem socket bonus of +3 spell crit rating.

Server Revision:
3478

**Comment by aresbrutus** [comment]
Socket changes could cause issues when it goes from 2.0 to 2.1 with already equiped sockets, but Wolf could also make all sockets unequipped and mail them back to the player with 2.1. I can provide a list of all socket color + bonus changes pre-2.1, but Wolf will have to agree to go this route. IMO they are minor changes and sadly with 2.4.3 we can't have the perfect 2.0. I would consider this minor enough not to care but up to Wolf.

**Comment by Godmatik** [comment]
We are not longer doing 2.0 itemization - closing
