### ISSUE TITLE
Nightmare Seed

### ISSUE THREAD

**Issue by GeorgieTragnar** [Atlantiss/NetherwingBugtracker#7163]
Hello,
I have a question - why was Nightmare seed (item ID 22797) changed to be herbable after patch 2.1? The changelog about this is from 18.11.2018 

I ask because patch 2.1 official patch notes clearly state that :
`Nightmare Seed found with herbalism now requires level 60 to use.`
https://wowwiki.fandom.com/wiki/Patch_2.1.0

Which clearly implies that it was usable ingame pre2.1

I ask if this is intentional nerf for player options for the launch (as it was for netherwing)

**Comment by Tereneckla** [comment]
http://web.archive.org/web/20070317192003/http://www.thottbot.com/i22797
March 2007 has it (2 months before 2.1) with comments from a month earlier

**Comment by bekonja** [comment]
https://www.wowhead.com/item=22797/nightmare-seed#comments:id=73693
apperantly it was indeed ingame for 2.0 patch and without level requirements
"Added in patch 2.1.0.6678" refers not to addition of the item but to its level req change

**Comment by TheMoneyHater** [comment]
Nightmare seed were in the game 2.0 and had 0 level req which made it INSANE for twinking. It was changed in 2.1 so I belive the change that was made was wrong.

**Comment by Godmatik** [comment]
These still aren't in-game, but should be.

**Comment by Wolffenstein** [comment]
Fixed in rev 3532.
