### ISSUE TITLE
[Core] Health/mana regen ticks from food buffs

### ISSUE THREAD

**Issue by Zarant** [Atlantiss/NetherwingBugtracker#7164]
**How it works:**
Right now food/drink buffs ticks every 5 seconds and they are separate from your normal HP/mana regen which happens every 2 seconds. This is not how food/drink buffs are supposed to work.

**How it's supposed to work:**
Regen gained from food/drink buffs should be added to your normal HP/mana regen and tick every 2 seconds.

**Proof:**

Patch 2.1: https://youtu.be/RPGXNosqD5I?t=1314
Patch 2.3: https://youtu.be/IB7bUNWTlh4?t=339

This same behavior is also observed on the classic client.

From the patch 2.4.0 patch notes:
> The benefits of drinking out of combat have been delayed while in the Arena. It will now take four seconds before the full benefit of the mana regeneration will come into effect.

Now a clip from S4: https://youtu.be/DEaljH6TK6g?t=389 
Mage sits to drink for about 4 seconds, gets 2 ticks off the food buff, he gets almost no mana from the first tick and on the second tick he gets mana from it. The quality is pretty shit but if you pay close attention on his mana, it goes from 1500 and something to 2000 and something (15xx to 2xxx), he got at least 500 mana from that tick.

Doing simple math you can figure out that level 70 water gives 7200/30*2 = 480 mana per tick, which leads to believe that both issues #5034 and #6013 are invalid. You should either get full mana or very close to full mana per tick after the 4 second mark.

**Comment by Wolffenstein** [comment]
Fixed in rev 3959.
