### ISSUE TITLE
Currently Heroic/Inspiring Presence arent working on PTR/Netherwing

### ISSUE THREAD

**Issue by SwiftieTBC** [Atlantiss/NetherwingBugtracker#7165]
Expected Behavior
Should gain 1% hit to either melee or spell (depending on class)

Current behavior
No buff is given

**Comment by Easyfraggy** [comment]
Afaik this buff doesn't show up on yourself, only on group members. Blizzlike afaik.

**Comment by SwiftieTBC** [comment]
The buff shouldn't visually show up but should be active on the player. However even when in a group with others atm no-one gets the buff

**Comment by Tereneckla** [comment]
![image](https://user-images.githubusercontent.com/50233983/87391702-833b4300-c5ab-11ea-9f00-ecffdbd1c8e6.png)

?? Both show up
