### ISSUE TITLE
HolyLight downranks

### ISSUE THREAD

**Issue by Cryingnugget** [Atlantiss/NetherwingBugtracker#7167]
Healing Done of Holy Light downranks(#10-#1) is off
its only small amounts so i guess some rankbased coeff issue
with 1276 BH
#11 working
#10 roughly 30heal less than expected
#9 ≈60heal less
[..] #1 ≈20 heal less
mostlikely happend with the Libram of the Lightbringer "Fix" because all ranks did work when i tested the libram
https://github.com/Atlantiss/NetherwingBugtracker/issues/7137

also the Libram is still not working (cant reopen the issue for some reason)

**Comment by Godmatik** [comment]
Fixed in upcoming update.
Spell coefficients being ported directly from TBC classic database
