### ISSUE TITLE
Restless Spirit of Earth not fighting other elemental spirits and very low player aggro radius - Draenei shaman quest  Call of Earth

### ISSUE THREAD

**Issue by daddylongneck123** [Atlantiss/NetherwingBugtracker#7173]
[//]: # (Enclose links to things related to the bug using http://wowhead.com or any other TBC database.)
[//]: # (You can use screenshot ingame to visual the issue.)
[//]: # (Write your tickets according to the format:)
[//]: # ([Quest][Azuremyst Isle] Red Snapper - Very Tasty!)
[//]: # ([NPC] Magistrix Erona)
[//]: # ([Spell][Mage] Fireball)
[//]: # ([Npc][Drop] Ghostclaw Lynx)
[//]: # ([Web] Armory doesnt work)
[//]: # (To find server revision type `.server info` command in the game chat.)

**Description**: 
Restless Spirit of Earth not fighting other elemental spirits - Draenei shaman quest  Call of Earth. 

Also the aggro radius on the player is very low. The Restless Spirtis wont aggro on player unless standing right on top of em. In my case I am lvl 5 and they are lvl 4

**Current behaviour**:

![WoWScrnShot_071520_001912](https://user-images.githubusercontent.com/63481493/87503204-9c86d280-c631-11ea-90a2-41261ea92da5.jpg)
![WoWScrnShot_071520_001920](https://user-images.githubusercontent.com/63481493/87503229-ad374880-c631-11ea-8ed8-d2af27f58171.jpg)
![WoWScrnShot_071520_001925](https://user-images.githubusercontent.com/63481493/87503240-b7f1dd80-c631-11ea-844d-595e324782c8.jpg)
![WoWScrnShot_071520_001930](https://user-images.githubusercontent.com/63481493/87503245-ba543780-c631-11ea-929d-452cc527082b.jpg)
![WoWScrnShot_071520_003342](https://user-images.githubusercontent.com/63481493/87503708-e91edd80-c632-11ea-80b6-5b86539a9df7.jpg)

**Expected behaviour**: 
The spirits are supposed to be attacking each other, see retail TBC video: https://www.youtube.com/watch?v=Z0Ccd9BDGiw

**Server Revision**: 
3483

**Comment by Wolffenstein** [comment]
Fixed in rev 3484.
