### ISSUE TITLE
Bounty on Murlocs [Quest]

### ISSUE THREAD

**Issue by revrox** [Atlantiss/NetherwingBugtracker#7174]
**Description**: 
Guard thomas does not offer this quest after handing in the prerequisite (Deliver Thomas' Report) untill past level 8.
**Current behaviour**:
Quest isn't availible untill 9+
**Expected behaviour**: 
The quest should be availible at level 7.
**Server Revision**: 
current PTR ( didnt check revision - tested last night)

**Comment by Tereneckla** [comment]
https://wowwiki.fandom.com/wiki/Quest:Bounty_on_Murlocs
https://classic.wowhead.com/quest=46/bounty-on-murlocs
requires level 7

**Comment by Godmatik** [comment]
Rev 4016 - either fixed at some point or was never an issue
I was able to pick it up at level 7 after finishing the pre-req
