### ISSUE TITLE
Captain Sander's Treasure Map

### ISSUE THREAD

**Issue by revrox** [Atlantiss/NetherwingBugtracker#7175]
**Description**: 
The treasure map itself doesn't share on drop
https://classic.wowhead.com/item=1357/captain-sanders-treasure-map#comments

**Current behaviour**:
The treasure map itself doesn't share on drop
**Expected behaviour**: 
The map should should for all party members when dropped
**Server Revision**:

**Comment by Godmatik** [comment]
Rev 4018 - no longer an issue
