### ISSUE TITLE
[Spell][Mage] Freeze + Shatter

### ISSUE THREAD

**Issue by Kaminbobby** [Atlantiss/NetherwingBugtracker#7179]
**Description** : 
Casting Frostbolt then summoning water elemental and casting Freeze before said Frostbolt lands on target does not proc shatter.

**Current behaviour** :
Casts Frostbolt from a distance, summon water elemental and casts Freeze while Frostbolt is in midflight, Frostbolt lands on target and breaks Freeze but **does not** gain the extra crit from Shatter talent. 

**Expected behaviour** : 
Casts Frostbolt from a distance, summon water elemental and casts Freeze while Frostbolt is in midflight, Frostbolt lands on target, Shatters the Freeze for x% extra crit.

Server Revision: 
3483

**Comment by Wolffenstein** [comment]
It's because crit is calculated when the spell launches, not when it hits the target (whether that's correct or not is the question).

**Comment by Kaminbobby** [comment]
> It's because crit is calculated when the spell launches, not when it hits the target (whether that's correct or not is the question).

Yeah you are right.

Did some digging and I can't find any proof of how it worked in retail 2.4.3, so if someone knows of any proof how it worked it would be really helpful

**Comment by Evolvee** [comment]
the only thing that should be checked on hit instead of cast are immunities

**Comment by Kaminbobby** [comment]
> the only thing that should be checked on hit instead of cast are immunities

Alright thanks for answer i will close this issue.
