### ISSUE TITLE
[Hunter] Trap visibility

### ISSUE THREAD

**Issue by x-x-x-x-x-x-x-x-x-x-x-x** [Atlantiss/NetherwingBugtracker#7181]
**Bug description**: 
traps are currently visible (when placed, for a short period of time) from any distance.
**Expected behaviour**: 
should not be visible to the enemy unless hes very close to it (practically on top of it). common strat back in the day was to lay down a trap and cancel the animation (jump,start running etc.), so that the opponent is unaware of it.
**Server Revision**: 
3483

**Comment by Zarant** [comment]
Duplicate of #5531
