### ISSUE TITLE
Attumen Trash

### ISSUE THREAD

**Issue by Nekomemi** [Atlantiss/NetherwingBugtracker#7182]
[//]: # (Enclose links to things related to the bug using http://wowhead.com or any other TBC database.)
[//]: # (You can use screenshot ingame to visual the issue.)
[//]: # (Write your tickets according to the format:)
[//]: # ([Quest][Azuremyst Isle] Red Snapper - Very Tasty!)
[//]: # ([NPC] Magistrix Erona)
[//]: # ([Spell][Mage] Fireball)
[//]: # ([Npc][Drop] Ghostclaw Lynx)
[//]: # ([Web] Armory doesnt work)
[//]: # (To find server revision type `.server info` command in the game chat.)

**Description**: 
Trash up to attumen,.
**Current behaviour**:
Respawn timer is like 15 minutes
**Expected behaviour**: 
as far as i know i should be 1,5 hours
**Server Revision**: 
3483 [Branch: optimization, Hash: 1b3bd8701ba9]

**Comment by Tereneckla** [comment]
Attumen trash has a 30 minutes respawn timer and that is correct
