### ISSUE TITLE
Priest Fade

### ISSUE THREAD

**Issue by Nekomemi** [Atlantiss/NetherwingBugtracker#7183]
[//]: # (Enclose links to things related to the bug using http://wowhead.com or any other TBC database.)
[//]: # (You can use screenshot ingame to visual the issue.)
[//]: # (Write your tickets according to the format:)
[//]: # ([Quest][Azuremyst Isle] Red Snapper - Very Tasty!)
[//]: # ([NPC] Magistrix Erona)
[//]: # ([Spell][Mage] Fireball)
[//]: # ([Npc][Drop] Ghostclaw Lynx)
[//]: # ([Web] Armory doesnt work)
[//]: # (To find server revision type `.server info` command in the game chat.)

**Description**: dont seem to work half the times you  use it

**Current behaviour**: works, dont work, its a gamble

**Expected behaviour**:  reduce threat

**Server Revision**: 
3483 [Branch: optimization, Hash: 1b3bd8701ba9]

**Comment by devo6969** [comment]
It really depends how much HPS they are putting out in pulling threat. If your a tank that doesn't generate enough threat and you have a healing priest, they will generate a lot of threat over you. Fade reduces the threat generated not by 100%. HpS threat is real in tbc. :)

https://classic.wowhead.com/spell=586/fade#comments
(Classic)
"Pretty much the worst threat reset ever."

**Comment by Tereneckla** [comment]
What devo says, 1k flat threat reduction for the time it is active
