### ISSUE TITLE
Prot warrior threat

### ISSUE THREAD

**Issue by Nekomemi** [Atlantiss/NetherwingBugtracker#7184]
[//]: # (Enclose links to things related to the bug using http://wowhead.com or any other TBC database.)
[//]: # (You can use screenshot ingame to visual the issue.)
[//]: # (Write your tickets according to the format:)
[//]: # ([Quest][Azuremyst Isle] Red Snapper - Very Tasty!)
[//]: # ([NPC] Magistrix Erona)
[//]: # ([Spell][Mage] Fireball)
[//]: # ([Npc][Drop] Ghostclaw Lynx)
[//]: # ([Web] Armory doesnt work)
[//]: # (To find server revision type `.server info` command in the game chat.)

**Description**: 
The tps from a warrior is to low, even with slowing my dps down to half speed, i over aggro (i have all threat reducing talends + subtlety on cloak) this is single target btw.
**Current behaviour**:
Low TPS output sub 1000
**Expected behaviour**: 
close to 1500 tps
**Server Revision**: 
3483 [Branch: optimization, Hash: 1b3bd8701ba9]

**Comment by devo6969** [comment]
Invalid 
https://youtu.be/VZODk7LqnM4?t=116
https://youtu.be/JS6KswGQ48k?t=40
