### ISSUE TITLE
Nightfall Suggestion

### ISSUE THREAD

**Issue by TheMoneyHater** [Atlantiss/NetherwingBugtracker#7185]
**Description**: Since the Dragonstrike is going to be main-hand until 2.4 then I think the Nightfall should proc until 2.4 also.

**Current behaviour**: Nightfall have the proc chance of after 2.4.2 (IT WAS NERFED TO THE GROUND 2.4.2)

**Expected behaviour**: I think it makes the game more fair if both these iconic Blacksmith items was untouched since they **both** were changed in 2.4.2 on retail.

**Comment by Easyfraggy** [comment]
Same answer as here: https://github.com/Atlantiss/NetherwingBugtracker/issues/7157

**Comment by TheMoneyHater** [comment]
For these SUPER iconic weapons, yes

**Comment by tsuone** [comment]
No.
