### ISSUE TITLE
[Item] Stormherald / Deep Thunder

### ISSUE THREAD

**Issue by tsuone** [Atlantiss/NetherwingBugtracker#7187]
[//]: # (Enclose links to things related to the bug using http://wowhead.com or any other TBC database.)
[//]: # (You can use screenshot ingame to visual the issue.)
[//]: # (Write your tickets according to the format:)
[//]: # ([Quest][Azuremyst Isle] Red Snapper - Very Tasty!)
[//]: # ([NPC] Magistrix Erona)
[//]: # ([Spell][Mage] Fireball)
[//]: # ([Npc][Drop] Ghostclaw Lynx)
[//]: # ([Web] Armory doesnt work)
[//]: # (To find server revision type `.server info` command in the game chat.)

**Description**: % chance to stun the target adjustments.

**Current behaviour**: Chance to stun the target is too high.

**Expected behaviour**: Deep Thunder and Stormherald on hit effect should've 1-2% chance to stun the target. People reported it being closer to 2%, so I'd put it at 1.6%. Also, aura value states that It should be either 1% or 1ppm (6.3%). Looking at what people say I am more biased towards first option. 

**Server Revision**: Current

**Comment by Easyfraggy** [comment]
This report is invalid, No supporting data and doesn't understand how ppm works.

**Comment by tsuone** [comment]
Tested, proc is good.
