### ISSUE TITLE
[Warrior][Talent] Mace Specialization

### ISSUE THREAD

**Issue by tsu-1** [Atlantiss/NetherwingBugtracker#7188]
[//]: # (Enclose links to things related to the bug using http://wowhead.com or any other TBC database.)
[//]: # (You can use screenshot ingame to visual the issue.)
[//]: # (Write your tickets according to the format:)
[//]: # ([Quest][Azuremyst Isle] Red Snapper - Very Tasty!)
[//]: # ([NPC] Magistrix Erona)
[//]: # ([Spell][Mage] Fireball)
[//]: # ([Npc][Drop] Ghostclaw Lynx)
[//]: # ([Web] Armory doesnt work)
[//]: # (To find server revision type `.server info` command in the game chat.)

**Description**: % chance to stun adjustments

**Current behaviour**: Mace Specialization stun chance is set for ~11% (3.8 weapon speed) / 1.7 PPM prior to Patch 2.3.

**Expected behaviour**: With a Patch 2.3 Mace Specialization effect was nerfed to 6% (3.6 weapon speed) with 6.3% (3.8 weapon speed). This means that it should roughly equal to **1PPM**. With lesser ranks lower chance to stun the target.

```
5/5 - 6% (1 PPM)
4/5 - 4% (0.63 PPM)
3/5 - 3% (0.47 PPM)
2/5 - 2% (0.31 PPM)
1/5 - 1% (0.16 PPM)
```
All of the above is calculated with 3.6 weapon speed.
 
**Server Revision**: Current.

**Comment by The14me** [comment]
Nerf by [1%](https://www.wowhead.com/forums&topic=4118#p42566) in 2.3.0
[Presuming]( Presuming you have 5/5 Mace spec. then a weapon with 3.8 speed has ~11% chance to stun, 2.8 speed has ~8% and 1.7 speed has 4%.) you have 5/5 Mace spec. then a weapon with 3.8 speed has ~11% chance to stun, 2.8 speed has ~8% and 1.7 speed has 4%.

**Comment by Easyfraggy** [comment]
Need sources. Also again OP doesn't understand how ppm works so it's kind of difficult to fix. I highly doubt the talent would have a flat proc chance % like he suggests.

**Comment by Easyfraggy** [comment]
Still no sources for this information so we can't check your numbers at all.

**Comment by Easyfraggy** [comment]
["Warriors

Talent tree shifts = two specs. Warriors speccing for more solo-oriented PVP will have MS, Imp Intercept, Last Stand and Concussion Blow, which I can see being rather scary. Mace nerf is apparently not as significant as first thought (proc rate down from 11%ish with Arena weapons to 9%ish). Warriors continue to be scary in organized PVP (but not really any more so than before), and get a bit scarier unsupported. Good change, in my opinion." ](https://forum.rpg.net/index.php?threads/wow-2-3-wherein-we-talk-specifically-about-pvp-implications.359755/)

This would put it in line with a nerf from 1,7 ppm at 5/5 with 3,8 speed (11%) to 1,4/1,5 ppm (8,8-9,5%) it would stand to reason that it would be a flat number per point where 0,3ppm per point would make it 1,5ppm at 5 points. However 1,4 is also possible.

The OP's suggestion of 1 ppm is pretty far fetched though and would need some serious support as they only buffed the rage gain from 6 to 7 to compensate for the lower procrate, it makes no sense they would almost half it.

**Comment by tsu-1** [comment]
Bringing up after Classic TBC.

https://eu.forums.blizzard.com/en/wow/en/wow/t/mace-stun-proc-rate/293696/47

The values presented by Easyfraggy in the comment above are correct.

> This would put it in line with a nerf from 1,7 ppm at 5/5 with 3,8 speed (11%) to 1,4/1,5 ppm (8,8-9,5%) it would stand to reason that it would be a flat number per point where 0,3ppm per point would make it 1,5ppm at 5 points. However 1,4 is also possible and would then be 0,28 per point.
>

**Comment by Godmatik** [comment]
Something to watch for after the upcoming weapon proc rework

**Comment by Godmatik** [comment]
Fixed in next server rev
