### ISSUE TITLE
[NPC][Spell] Nazan's fire pools dealing damage through divine shield.

### ISSUE THREAD

**Issue by balo-git** [Atlantiss/NetherwingBugtracker#7189]
**Description**: 
In reference to #4768, that issue has no tags, so perhaps this is a better successor.
The stationary fire hazards spit out by Nazan in Hellfire Ramparts killed my paladin during Divine Shield. Presumably this is because it is implemented in such a way that the source of damage is the player and not Nazan. See the combat log screenshot below. Presumably this would also affect players in Ice block and other invulnerabilites.

Bae's (player's) Blaze hits Bae for 5326 Fire.

**Current behaviour**:
A player in divine shield will take damage from the fire pools spit by Nazan during the encounter.

**Expected behaviour**: 
Divine Shield should most likely prevent the damage.

**Server Revision**: 
Karazhan PTR Revision 3483

![image](https://user-images.githubusercontent.com/47939551/87866645-4af08780-c952-11ea-9b22-77189bbf94fc.png)
![image](https://user-images.githubusercontent.com/47939551/87866648-4fb53b80-c952-11ea-81b4-907acfc61ac8.png)

**Comment by Easyfraggy** [comment]
Not that I think this is wrong, but if you can find a video from retail with someone in it with bubble on standing in it then it would be 100%. There are some effects that go through bubble, so proof would be nice.

**Comment by The14me** [comment]
https://github.com/Atlantiss/NetherwingBugtracker/issues/2030

**Comment by Wolffenstein** [comment]
Fixed in rev 3484.
