### ISSUE TITLE
[Warrior] The Affray (Berserker Stance Quest)

### ISSUE THREAD

**Issue by Azalen** [Atlantiss/NetherwingBugtracker#719]
**Description**: 

1) When the quest (for whatever reason) fails it gets pruned from the questlog and the player is unable to take it again. I had to ask a GM to reset the quest for me.

2) Quests seems to get wonky when the player leaves the fighting area. In one of three tries (thanks to the GM) I did not die but stayed at 1 hp unable to move at all. After a relogin I was dead and the quest was failed and thus deleted from questlog.

**Server Revision**: 
[2067]

**Comment by Tereneckla** [comment]
Fixed
