### ISSUE TITLE
[Quest] [Ghostlands] Underlight Ore Samples - quests drops are not shared

### ISSUE THREAD

**Issue by Isoles** [Atlantiss/NetherwingBugtracker#7190]
**Description**: The quest item drops for Underlight Ore Samples (https://tbcdb.com/?quest=9207) are not shared between group members. 

**Current behaviour**: Only one player in the group can loot Underlight Ore from a dead monster.

**Expected behaviour**: All players in the group should be able to loot Underlight Ore from a dead monster.

**Server Revision**: 4483

**Comment by Tereneckla** [comment]
> 
> 
> This one was purposefully not set as group loot because it also comes from an object, and objects with group loot items act strangely out in the open world where multiple groups can interact with it.

#3874 :/

**Comment by Isoles** [comment]
Ah, these can be mined from copper and tin veins as well?

**Comment by Tereneckla** [comment]
yes
