### ISSUE TITLE
[Spell][Warrior] Intimidating Shout

### ISSUE THREAD

**Issue by tsuone** [Atlantiss/NetherwingBugtracker#7191]
[//]: # (Enclose links to things related to the bug using http://wowhead.com or any other TBC database.)
[//]: # (You can use screenshot ingame to visual the issue.)
[//]: # (Write your tickets according to the format:)
[//]: # ([Quest][Azuremyst Isle] Red Snapper - Very Tasty!)
[//]: # ([NPC] Magistrix Erona)
[//]: # ([Spell][Mage] Fireball)
[//]: # ([Npc][Drop] Ghostclaw Lynx)
[//]: # ([Web] Armory doesnt work)
[//]: # (To find server revision type `.server info` command in the game chat.)
_This is continuation of previous thread created by Chegito: https://github.com/Atlantiss/NetherwingBugtracker/issues/7018_

**Description**: 
Intimidating Shout (main target) effect in PvP scenario.

**Current behaviour**: 
Intimidating Shout (main target, ```Aura Effect: Stun```) doesn't share DR with Fear abilities.

Video representing current behaviour of Intimidating Shout in relations to Fear ability:
https://youtu.be/htzKiVoaEiQ

**Expected behaviour**: 
Intimidating Shout is a Warrior spell that Fears everyone in the 8 yard. Additionaly besides fearing everyone it also "stuns" target we used Intimidating Shout on. I say "stuns" because **it is not a stun** but still a **fear**. This `Aura Effect: Stun` is only applied to the main target in order to lock him in place! Mechanic for the main target Intimidating Shout doesn't change, it is still fleeing and **should be DR with other Fear abilities** within controlled stun category!
![image](https://user-images.githubusercontent.com/11255782/87876441-656d4400-c9d8-11ea-9ff4-498fb9cdd732.png)
This is **spell details of Intimidating Shout** effect applied to the main target. As you can see, it is `Mechanic: Fleeing` which should make it DR with other Fear (Controlled Stun) abilities.

Another point of proof would be spell details of Intimidating Shout (ability) that is applied to everyone.
![image](https://user-images.githubusercontent.com/11255782/87876850-05c46800-c9db-11ea-8bb2-cd913eaeb48f.png)
As you can see it applies Intimidating Shout (20511) to the main target, and then Fear effects to everyone including main target. Additionaly the main target gets the `Aura Effect: Stun` applied.

Also, keep in mind that you can use WotF to get out of Intimidating Shout during the duel (so you are the main target 100% of the time) as presented here in the video from Classic WoW:
https://youtu.be/3tREJtTzgH4?t=20

**Server Revision**: Current.

**Comment by Easyfraggy** [comment]
The behavior currently where the main target breaks on any damage and is rooted in place while "feared" is correct. The only thing that appears wrong is that it should DR fear and be breakable with spells that cancel fears such as wotf.

**Comment by devo6969** [comment]
On Classic these do share a DR (they didn't have the short duration visual, but you can see the "clock" timer on the Intimidating Shout always stops at 4 seconds. *Half the Durationn*.

Warlock fear/Shout - https://www.youtube.com/watch?v=tGq9cxby1JQ
Priest fear/Shout - https://www.youtube.com/watch?v=vStJTL-Lzls
