### ISSUE TITLE
[Talent][Rogue] Vile Poisons

### ISSUE THREAD

**Issue by unjoined** [Atlantiss/NetherwingBugtracker#7192]
**Description**: 
The damage increase from the talent 'Vile Poisons' is not being applied to Wound Poison.

**Current behaviour**:
Tested on dummys on Karazhan PTR and the damage from Wound Poison [Rank V] is 66 Nature Damage with or without the talent.

**Expected behaviour**: 
Should be applied the correct percentage on top of the base damage. I.e. 5/5 Vile Poisons increases poison damage by 20% thus in this particular scenario Wound Poison would hit for roughly 79 damage.

The talent is working for Deadly Poison. I did not test for anymore poisons nor the resist spell effect.

**Comment by Wolffenstein** [comment]
Fixed in rev 3593.
