### ISSUE TITLE
[Guild] Guild Bank logs broken

### ISSUE THREAD

**Issue by eri1997** [Atlantiss/NetherwingBugtracker#7193]
[//]: # (Enclose links to things related to the bug using http://wowhead.com or any other TBC database.)
[//]: # (You can use screenshot ingame to visual the issue.)
[//]: # (Write your tickets according to the format:)
[//]: # ([Quest][Azuremyst Isle] Red Snapper - Very Tasty!)
[//]: # ([NPC] Magistrix Erona)
[//]: # ([Spell][Mage] Fireball)
[//]: # ([Npc][Drop] Ghostclaw Lynx)
[//]: # ([Web] Armory doesnt work)
[//]: # (To find server revision type `.server info` command in the game chat.)

**Description**: One of the recent updates broke guild bank logs.

**Current behaviour**: Most of the guild bank logs show Unknown withdrew (x hours). Name of the player and the item they took doesn't show. This isn't a deleted character showing as unknown as my own logs show as unknown when I get smth from the bank.
![image](https://user-images.githubusercontent.com/52356864/87880589-1ed91300-c9f3-11ea-9dc1-08dac11087b0.png)

**Expected behaviour**:  Name withdrew itemName (x hours)

**Server Revision**: 3483 netherwing server

**Comment by duzyizly** [comment]
Are you sure it's not because someone (Unknown) deleted his character?

**Comment by eri1997** [comment]
Yes very sure . As i said in the report I got smth out of the bank myself and it showed my name as unknown
