### ISSUE TITLE
Quest "Fire at Will!" bugged

### ISSUE THREAD

**Issue by kalblake11** [Atlantiss/NetherwingBugtracker#7197]
**Description**:  The Quest "Fire at Will!" in Blades Edge Mountains is not working correctly.

**Current behaviour**: After you use the Item u are not able to attack anything. Also the "4" Ability has no cooldown and the "5" Ability is not working.

**Expected behaviour**:  You should be able to use your "4" ability to attack the Portal on a cooldown and kill the waves of mobs coming out of it.

**Comment by Tereneckla** [comment]
Duplicate of #6534
