### ISSUE TITLE
[Core] Area Damage Caps

### ISSUE THREAD

**Issue by Easyfraggy** [Atlantiss/NetherwingBugtracker#7198]
**Sources**: 

https://cdn.discordapp.com/attachments/718496124457189468/735208691577651261/Area_Damage_Caps.PNG
https://wowwiki.fandom.com/wiki/Area_damage_caps?oldid=1432529
https://web.archive.org/web/20100317201500/http://forums.worldofwarcraft.com/thread.html?topicId=443123919&sid=1&pageNo=1

![image](https://user-images.githubusercontent.com/36134067/88097093-f4748a80-cb97-11ea-8b98-2578db094dc2.png)

So it seems that the damage cap for AE and Blizzard are significantly higher than retail. I'm also looking for help gathering sources for other aoe spells

Seed of Corruption
Frost Nova
Magma Totem

Fx

Questions need research:

Are ground effects included, like flamestrike ground effect, consecration etc.

**Server Revision**:

**Comment by SwiftieTBC** [comment]
http://web.archive.org/web/20081023033855/http://elitistjerks.com/f47/t25902-aoe_spell_cap_mechanics/
