### ISSUE TITLE
[Quest][Item]Iridescent Wing

### ISSUE THREAD

**Issue by bekonja** [Atlantiss/NetherwingBugtracker#7199]
[//]: # (Enclose links to things related to the bug using http://wowhead.com or any other TBC database.)
[//]: # (You can use screenshot ingame to visual the issue.)
[//]: # (Write your tickets according to the format:)
[//]: # ([Quest][Azuremyst Isle] Red Snapper - Very Tasty!)
[//]: # ([NPC] Magistrix Erona)
[//]: # ([Spell][Mage] Fireball)
[//]: # ([Npc][Drop] Ghostclaw Lynx)
[//]: # ([Web] Armory doesnt work)
[//]: # (To find server revision type `.server info` command in the game chat.)

**Description**: 
https://tbcdb.com/?item=30792
https://tbcdb.com/?quest=10618

**Current behaviour**:
Absolutely horrible droprate

**Expected behaviour**: 
https://web.archive.org/web/20080119125539/http://thottbot.com/q10618
This is archive from 2.3 patch, read latest comments:
>Just went for mature silverwings and had 80% drop.. done in 15 mins

>ye i think they fixed the droprate of these mobs. I got one every 3 mobs that I killed, was done in ap. 10 minutes.

>Droprate fix confirmed, done in ~15 mins

And around another 20 comments like that. Atrocious droprate was fixed to 80% sometime after release.

**Server Revision**: 
3483

**Comment by Wolffenstein** [comment]
Fixed in rev 3487.
