### ISSUE TITLE
Firebolt from Imp doesn't activate combat upon completion.

### ISSUE THREAD

**Issue by Scylla420** [Atlantiss/NetherwingBugtracker#72]
I'm not put into combat until the firebolt (3110) actually hits the target and deals damage.  Currently with player spells as soon as the cast finishes you're put into combat with the target which is blizzlike but I'm not sure how combat should work with pets.  Easy told me to write a report about it anyway >__<

**Comment by wtRCH** [comment]
Probably the same issue for Hunter class.

**Comment by Scylla420** [comment]
Some people thought that pet and owner shouldn't share combat at all but that's untrue as you can see [https://www.youtube.com/watch?v=CO-kRCYacsc&t=38s](in this video.)  As soon as his pet enters combat with the target Joana enters combat as well.  Still need to see if imp should gain combat on spell completion like players or not though.

**Comment by Evolvee** [comment]
@Wolffenstein its different for PVE and PVP https://github.com/Atlantiss/AtlantissTbcBTOLD/issues/566

**Comment by Evolvee** [comment]
@Wolffenstein the PVP part is working correctly currently

**Comment by SwiftieTBC** [comment]
https://youtu.be/5RT55m3GNVM?t=26
Footage from during TBC, the player entering combat doesnt start untill the warlock fireball hits the raptor

**Comment by Evolvee** [comment]
the combat started as soon as the cast of the player was finished, the imp fireball had no effect

**Comment by SwiftieTBC** [comment]
"I'm not put into combat until the firebolt (3110) actually hits the target and deals damage" was the original bug post, this is verified to be correct as the player is out of combat whilst the projectile is in the air.
