### ISSUE TITLE
Quest, Hillsbrad Foothills, Soothing Turtle Bisque

### ISSUE THREAD

**Issue by Erodraeda** [Atlantiss/NetherwingBugtracker#720]
[//]: # (Enclose links to things related to the bug using http://wowhead.com or any other TBC database.)
[//]: # (You can use screenshot ingame to visual the issue.)
[//]: # (Write your tickets according to the format:)
[//]: # ([Quest][Azuremyst Isle] Red Snapper - Very Tasty!)
[//]: # ([NPC] Magistrix Erona)
[//]: # ([Spell][Mage] Fireball)
[//]: # ([Npc][Drop] Ghostclaw Lynx)
[//]: # ([Web] Armory doesnt work)

**Description**: 
The turtles, Snapjaw (2408, 77) should have a higher drop chance on Turtle Meat. It should be around 80%, according to some vanilla and TBC databases.
**Current behaviour**:
The drop chance is way too low, only got 1 in 10-15 kills.
**Expected behaviour**: 
The drop chance should be around 80%, or at least higher than 50%, because I remember getting it way more often.
**Server Revision**:

**Comment by tcberk12** [comment]
https://web.archive.org/web/20070630113442/http://www.thottbot.com:80/?i=6218

Check the comments/data on the droprate made by people in 2007, when tbc was live. It looks like people had the same low drop rate you experienced.

**Comment by aresbrutus** [comment]
Global loot related.

**Comment by Shanghi** [comment]
We don't even trust our own memories here! But it was fixed in revision 2152 and shouldn't take 10-15 kills anymore unless you're cursed.
