### ISSUE TITLE
Hunter Pets Lagging

### ISSUE THREAD

**Issue by ninjawarrior077** [Atlantiss/NetherwingBugtracker#7204]
Recently I have been having an issue with my hunter pets. While they act as they usually would out of combat, in combat the pet moves from front to back of the enemy's frontmost hitbox between its attacks. While my pet is the primary aggro target, the enemy also attempts to return to the front of my pet's hitbox to continue attacking, thus resulting in the two entities frantically running back and forth to try and face each other. I'm not entirely positive on what's happening, but I've tested this out on multiple pets and have tried multiple different solutions (letting the pet die, dismissing the pet, putting it in the stable, taming a new pet, and relogging into the game while pet is dismissed among others). So far, what's given me the impression that the pet itself is lagging is when using the "Eyes of the Beast" skill. When moving as my pet the game stutters every couple frames, though the timer on the skill remains unaffected by the massive stuttering. 

This isn't game-breaking, as the pet and enemy are still able to hit each other during either situation I mentioned above when in combat, but it is otherwise inconvenient since it makes "Eyes of the Beast" completely unusable.

**Comment by Tereneckla** [comment]
https://www.youtube.com/watch?v=RSyEh2WXTy8
Not lag. Pet walks into the hitbox of the mob to attack, which causes the mob to back off.
Pet follows into hitbox again, pet backs off this time. 
Repeat.

**Comment by Easyfraggy** [comment]
I guess the pet should just not attempt to move behind the target if it has agro on it.

**Comment by Qtec66** [comment]
We had the same issue yesterday, was really annoying. Hope this will be fixed till Karazahn Launch.

**Comment by Wolffenstein** [comment]
Fixed in rev 3485.
