### ISSUE TITLE
[PvP] Diminishing Returns 

### ISSUE THREAD

**Issue by tsuone** [Atlantiss/NetherwingBugtracker#7207]
[//]: # (Enclose links to things related to the bug using http://wowhead.com or any other TBC database.)
[//]: # (You can use screenshot ingame to visual the issue.)
[//]: # (Write your tickets according to the format:)
[//]: # ([Quest][Azuremyst Isle] Red Snapper - Very Tasty!)
[//]: # ([NPC] Magistrix Erona)
[//]: # ([Spell][Mage] Fireball)
[//]: # ([Npc][Drop] Ghostclaw Lynx)
[//]: # ([Web] Armory doesnt work)
[//]: # (To find server revision type `.server info` command in the game chat.)
Currently opened issues: https://github.com/Atlantiss/NetherwingBugtracker/issues/7111 https://github.com/Atlantiss/NetherwingBugtracker/issues/7123 https://github.com/Atlantiss/NetherwingBugtracker/issues/7122 https://github.com/Atlantiss/NetherwingBugtracker/issues/7191

**Description**: Merged thread about Dimishing Returns in PvP scenario (not PvE).

**Current behaviour**: Several abilities doesn't share Dimishing Return properly with their assigned category. This was tested on server revision `[3483]` after `[3446]` DR fixes.

**Expected behaviour**: 
- **Maim** `[22570]` should share DR with `Incapacitate` DR category (Polymorph, Sap, Gouge, Maim, Repentance)
- https://github.com/Atlantiss/NetherwingBugtracker/issues/7111 **Repentance** `[20066]` should share DR with `Incapacitate` DR category (Polymorph, Sap, Gouge, Maim, Repentance)
- https://github.com/Atlantiss/NetherwingBugtracker/issues/7191 **Intimidating Shout** `[5246]` should share DR with `Fear` DR category (Psychic Scream, Fear, Howl of Terror, Seduction, Intimidating Shout) - **Also, main target effect from Intimidating Shout should also share DR with `Fear` DR category!**
- https://github.com/Atlantiss/NetherwingBugtracker/issues/7122 **Scatter Shot** `[19503]` still doesn't share DR with itself as it should  after revision `[3446]`.
- https://github.com/Atlantiss/NetherwingBugtracker/issues/7123 **Dragon's Breath** `[31661, 33041, 33042, 33043]` still doesn't share DR with itself as it should after revision `[3446]`.

**Server Revision**: 3483

**Comment by Wolffenstein** [comment]
Fixed in rev 3533.
