### ISSUE TITLE
[Pet] Right clicking pet in Defensive Stance

### ISSUE THREAD

**Issue by tsuone** [Atlantiss/NetherwingBugtracker#7209]
[//]: # (Enclose links to things related to the bug using http://wowhead.com or any other TBC database.)
[//]: # (You can use screenshot ingame to visual the issue.)
[//]: # (Write your tickets according to the format:)
[//]: # ([Quest][Azuremyst Isle] Red Snapper - Very Tasty!)
[//]: # ([NPC] Magistrix Erona)
[//]: # ([Spell][Mage] Fireball)
[//]: # ([Npc][Drop] Ghostclaw Lynx)
[//]: # ([Web] Armory doesnt work)
[//]: # (To find server revision type `.server info` command in the game chat.)

**Description**: Right clicking pet in Defensive Stance.

**Current behaviour**: If you right click pet that is set to Defensive Stance, it automatically starts to attack you even if you are 50 yards away from the pet. Video showcasing the issue:
https://youtu.be/eLToBz6jVXg

**Expected behaviour**: Hunter and Warlock pet shouldn't auto-attack enemy when he right clicks their pet that is set to Defensive Stance. Pet with Defensive Stance should only attack, if pet gets attacked, their master gets damage or hit the target (even with a miss).

**Server Revision**: `3483`

**Comment by The14me** [comment]
https://github.com/Atlantiss/NetherwingBugtracker/issues/384
https://github.com/Atlantiss/NetherwingBugtracker/issues/4240

**Comment by Wolffenstein** [comment]
Fixed in rev 3520.
