### ISSUE TITLE
[PvP][Pet] Taunting pet in PvP

### ISSUE THREAD

**Issue by tsuone** [Atlantiss/NetherwingBugtracker#7210]
[//]: # (Enclose links to things related to the bug using http://wowhead.com or any other TBC database.)
[//]: # (You can use screenshot ingame to visual the issue.)
[//]: # (Write your tickets according to the format:)
[//]: # ([Quest][Azuremyst Isle] Red Snapper - Very Tasty!)
[//]: # ([NPC] Magistrix Erona)
[//]: # ([Spell][Mage] Fireball)
[//]: # ([Npc][Drop] Ghostclaw Lynx)
[//]: # ([Web] Armory doesnt work)
[//]: # (To find server revision type `.server info` command in the game chat.)

**Description**: In depth look and issue report for taunting pet in PvP when in Aggresive / Defensive / Passive stance.

**Current behaviour**: Not all "taunt" type abilities and spell effects are working as they supposed to when used on the PlayerControlledUnit (Pet) in PvP. You can check table below to see test results on server revision `[3483]`.
Ability/Spell | Aggresive Stance | Defensive Stance | Passive Stance
------------ | ------------- | ------------- | -------------
Stoneclaw Totem (Shaman) `[25525]` | Works | **Not working** | **-**
Taunt (Warrior)`[355]` | Works | Works | **-**
Mocking Blow (Warrior) `[25266]` | **Works partially** | **Works partially** | **-**
Challenging Shout (Warrior) `[1161]` | **Works partially** | **Works partially** | **-**
Challenging Roar (Druid) `[5209]` | **Works partially** | **Works partially** | **-**
Growl (Druid) `[6795]` | Works | Works | **-**

```
Table legend:
Works - Ability interaction with pet stance is working correctly.
Works partially - Ability interaction with pet stance is half working.
Not working - Ability interaction with pet stance doesn't work properly.
```
**Expected behaviour**: PlayerControlledUnit (Pet) should work the following way when interacting with the Abilities/Spells mentioned in the table above.
- **Stoneclaw Totem** (Shaman) `[25525]` _(Not working - Defensive Stance)_ - When placing Stoneclaw Totem, nearby Pets aren't taunted/forced to attack it, when their stance is set to passive.
- **Mocking Blow** (Warrior) `[25266]` _(Works partially - Both stances)_ - Using Mocking Blow should only make Pet attack the "caster" for the duration of the Mocking Blow debuff on the Pet!
- **Challenging Shout** (Warrior) `[1161]` _(Works partially - Both stances)_ - Challenging Shout should make Pet attack the "caster" only for the duration of the Challenging Shout. If "caster" do make enough threat, Pet should continue to attack the "caster". When "caster" will use Challenging Shout but not make enough threat, it should return to attacking previous target/highest player on threat table.
- **Challenging Roar** (Druid) `[5209]` _(Works partially - Both stances)_ - Challenging Roar should make Pet attack the "caster" only for the duration of the Challenging Roar. If "caster" do make enough threat, Pet should continue to attack the "caster". When "caster" will use Challenging Roar but not make enough threat, it should return to attacking previous target/highest player on threat table.

**Server Revision**: `[3483]`

**Comment by Wolffenstein** [comment]
Fixed in rev 3520.
