### ISSUE TITLE
[Core]Controlling NPC

### ISSUE THREAD

**Issue by bekonja** [Atlantiss/NetherwingBugtracker#7211]
[//]: # (Enclose links to things related to the bug using http://wowhead.com or any other TBC database.)
[//]: # (You can use screenshot ingame to visual the issue.)
[//]: # (Write your tickets according to the format:)
[//]: # ([Quest][Azuremyst Isle] Red Snapper - Very Tasty!)
[//]: # ([NPC] Magistrix Erona)
[//]: # ([Spell][Mage] Fireball)
[//]: # ([Npc][Drop] Ghostclaw Lynx)
[//]: # ([Web] Armory doesnt work)
[//]: # (To find server revision type `.server info` command in the game chat.)

**Description**: 
https://tbcdb.com/?quest=9433
https://tbcdb.com/?quest=10857
and probably other quests where you need to take controll of some NPC

**Current behaviour**:
https://www.youtube.com/watch?v=JD-JJViNPaQ
Controlled minion spazzes out moving in random directions while your wow client tries to shit itself and crash with error.

**Expected behaviour**: 
As it worked 3 days ago. Please stop trying to sabotage fresh by changing core mechanics.

**Server Revision**: 
3483

**Comment by Wolffenstein** [comment]
Fixed in rev 3485.
