### ISSUE TITLE
[Creature] [Tempest Keep] Phaseshift Bulwark - Corpse

### ISSUE THREAD

**Issue by Drayo** [Atlantiss/NetherwingBugtracker#7215]
[//]: # (Enclose links to things related to the bug using http://wowhead.com or any other TBC database.)
[//]: # (You can use screenshot ingame to visual the issue.)
[//]: # (Write your tickets according to the format:)
[//]: # ([Quest][Azuremyst Isle] Red Snapper - Very Tasty!)
[//]: # ([NPC] Magistrix Erona)
[//]: # ([Spell][Mage] Fireball)
[//]: # ([Npc][Drop] Ghostclaw Lynx)
[//]: # ([Web] Armory doesnt work)
[//]: # (To find server revision type `.server info` command in the game chat.)

**Current behaviour**: 

- Phaseshift Bulwark's corpse never despawns. It's coprse despawn timer initially shows 60s and when it runs out it just resets to 5m.
![image](https://user-images.githubusercontent.com/23145811/88353523-1c154f80-cd5e-11ea-9a03-56863fd8e683.png)

**Edit:** This seems to happen to other weapons too. On my first try, only the shield had this issue. On my second pull, the bow also did not despawn.

**Expected behaviour**: 

- Phaseshift Bulwark's corpse should despawn after 60s, just like all the other weapons.

**Server Revision**: 3486

**Comment by Godmatik** [comment]
Fixed a few months ago, can close
