### ISSUE TITLE
drinking animation not working properly

### ISSUE THREAD

**Issue by daddylongneck123** [Atlantiss/NetherwingBugtracker#7217]
[//]: # (Enclose links to things related to the bug using http://wowhead.com or any other TBC database.)
[//]: # (You can use screenshot ingame to visual the issue.)
[//]: # (Write your tickets according to the format:)
[//]: # ([Quest][Azuremyst Isle] Red Snapper - Very Tasty!)
[//]: # ([NPC] Magistrix Erona)
[//]: # ([Spell][Mage] Fireball)
[//]: # ([Npc][Drop] Ghostclaw Lynx)
[//]: # ([Web] Armory doesnt work)
[//]: # (To find server revision type `.server info` command in the game chat.)

**Description**: 
drinking animation not working properly

**Current behaviour**:
When drinking water character sits down, drinks with ~1.5sec breaks between for two sips, but then starts drinking fast (no break between sips) for the rest of the drink duration

**Expected behaviour**: 
The character should take breaks between sips the whole time the drink buff is going on (food eating animation plays fine through whole buff)

**Server Revision**: 
3483

**Comment by Godmatik** [comment]
Animations are client side
