### ISSUE TITLE
NPC Cookie McWeaksauce scripted animation doesnt play

### ISSUE THREAD

**Issue by daddylongneck123** [Atlantiss/NetherwingBugtracker#7218]
[//]: # (Enclose links to things related to the bug using http://wowhead.com or any other TBC database.)
[//]: # (You can use screenshot ingame to visual the issue.)
[//]: # (Write your tickets according to the format:)
[//]: # ([Quest][Azuremyst Isle] Red Snapper - Very Tasty!)
[//]: # ([NPC] Magistrix Erona)
[//]: # ([Spell][Mage] Fireball)
[//]: # ([Npc][Drop] Ghostclaw Lynx)
[//]: # ([Web] Armory doesnt work)
[//]: # (To find server revision type `.server info` command in the game chat.)

**Description**: 
NPC Cookie McWeaksauce scripted animation doesnt play

**Current behaviour**:
Cookie McWeaksauce says "It be chicken..." but doesnt shoot a nearby chicken

**Expected behaviour**: 
Cookie McWeaksauce should shoot a nearby chicken and say "It be chicken..." this is how it used to work on NW but I guess it got broken somehow.

This isnt tbc retail footage (I couldnt find same) but as you can see here Cookie is supposed to shoot a nearby chicken and says It be chicken..." starting ~ 01:10: https://www.youtube.com/watch?v=KSZ5RmMkjrA

**Server Revision**: 
3483

**Comment by Tereneckla** [comment]
https://wowwiki.fandom.com/wiki/%22Cookie%22_McWeaksauce

**Comment by EtheriousNW** [comment]
Fixed in 3846
