### ISSUE TITLE
[Shadowmoon Valley] [NPC] Enraged Air Spirit - Multiple Spawns

### ISSUE THREAD

**Issue by Drayo** [Atlantiss/NetherwingBugtracker#7219]
[//]: # (Enclose links to things related to the bug using http://wowhead.com or any other TBC database.)
[//]: # (You can use screenshot ingame to visual the issue.)
[//]: # (Write your tickets according to the format:)
[//]: # ([Quest][Azuremyst Isle] Red Snapper - Very Tasty!)
[//]: # ([NPC] Magistrix Erona)
[//]: # ([Spell][Mage] Fireball)
[//]: # ([Npc][Drop] Ghostclaw Lynx)
[//]: # ([Web] Armory doesnt work)
[//]: # (To find server revision type `.server info` command in the game chat.)

**Current behaviour**: 

- There is a spot that has multiple spwans.
![image](https://user-images.githubusercontent.com/23145811/88429263-9abdcb80-cdf6-11ea-8b51-e7edd99442df.png)
![image](https://user-images.githubusercontent.com/23145811/88429347-c0e36b80-cdf6-11ea-8d43-6b24e01ed8dd.png)

**Expected behaviour**: 

- Should only be one mob spawned there.

**Server Revision**: 3486

**Comment by Wolffenstein** [comment]
PTR bug
