### ISSUE TITLE
Major Warlock Demonic Sacrifice Bug

### ISSUE THREAD

**Issue by Tun9sten** [Atlantiss/NetherwingBugtracker#7220]
**Description**: There's a way to keep your pet after demonic sacrifice.

**Current behaviour**: If you immediately mount after using demonic sacrifice you will keep your pet and it will respawn every time you unmount. Meaning you have the buff + the pet.

**Expected behaviour**: After using demonic sacrifice and mounting your pet should not come back after unmounting

**Server Revision**: 3486

**Comment by tsuone** [comment]
Worth noticing that Warlock Pet is summoned back again with minimal health (1%).

**Comment by Tun9sten** [comment]
Have to add that because of many issue's with a warlock's pet. This bug actually makes demonology somewhat viable.

**Comment by Wolffenstein** [comment]
Fixed in rev 3503.
