### ISSUE TITLE
[Quest item drops - General] Being grouped with someone who carries unique quest item blocks said item from dropping for you

### ISSUE THREAD

**Issue by Tvingman** [Atlantiss/NetherwingBugtracker#7222]
[//]: # (Enclose links to things related to the bug using http://wowhead.com or any other TBC database.)
[//]: # (You can use screenshot ingame to visual the issue.)
[//]: # (Write your tickets according to the format:)
[//]: # ([Quest][Azuremyst Isle] Red Snapper - Very Tasty!)
[//]: # ([NPC] Magistrix Erona)
[//]: # ([Spell][Mage] Fireball)
[//]: # ([Npc][Drop] Ghostclaw Lynx)
[//]: # ([Web] Armory doesnt work)
[//]: # (To find server revision type `.server info` command in the game chat.)

**Description**: I had just accepted the Salvaging the Data quest in Bloodmyst Isle (http://tbc.cavernoftime.com/quest=9628), and without realising it picked up the quest item Survey Data Crystal from one of my first kills. I then invited a nearby player, we started hunting some mobs while in party, for me to then realise that I looted the item already. Since he hadn't, I stuck around to kill more Naga - but after 50 or so kills we started thinking something was weird. The guy said for me to go on questing, he'd grind it out solo, so we parted ways. 2 mobs later he got the quest item.

While it's impossible for us to verify, we suspect that since I already had the (unique) quest item and quest drops are shared, that I blocked him from picking one up as his party member is ineligible.

**Current behaviour**:
Player A has unique item, entire party is unable to loot a new one.

**Expected behaviour**: 
Player A has unique quest item, player B still loots his own

**Server Revision**: 
3486

**Comment by Wolffenstein** [comment]
Are you sure you didn't actually create a raid or were just unlucky (10% drop rate).
I just tested it with two characters grouped together, one already had the crystal. With 100% drop rate it dropped every time:

![obraz](https://user-images.githubusercontent.com/1576644/88484368-59502c00-cf6e-11ea-8bf9-489f9f9c835a.png)

**Comment by Tvingman** [comment]
We weren't in a raid, but it's certainly possible that we had an extreme string of bad luck. Thanks for testing!
