### ISSUE TITLE
Don't get messages on mailbox

### ISSUE THREAD

**Issue by drywulek** [Atlantiss/NetherwingBugtracker#7223]
[//]: # (Enclose links to things related to the bug using http://wowhead.com or any other TBC database.)
[//]: # (You can use screenshot ingame to visual the issue.)
[//]: # (Write your tickets according to the format:)
[//]: # ([Quest][Azuremyst Isle] Red Snapper - Very Tasty!)
[//]: # ([NPC] Magistrix Erona)
[//]: # ([Spell][Mage] Fireball)
[//]: # ([Npc][Drop] Ghostclaw Lynx)
[//]: # ([Web] Armory doesnt work)
[//]: # (To find server revision type `.server info` command in the game chat.)

**Description**: 
Realm Karazhan (cause there is no Karazhan bugtracker site)
When I log in to game I saw that I get mail in my mailbox, but when I opened it there was no message.

Tried relog, clear catch, but nothing works.

![WoWScrnShot_072620_102941](https://user-images.githubusercontent.com/68807034/88475412-bed0f800-cf2f-11ea-925a-03f51bb3706c.jpg)

**Comment by Wolffenstein** [comment]
I don't see any mails directed to you in the database. Is the issue resolved?

**Comment by Wolffenstein** [comment]
Should be solved in revision 3487.
