### ISSUE TITLE
Tome of Valor Part 2 or 3 Doesnt work

### ISSUE THREAD

**Issue by Sooflaahn** [Atlantiss/NetherwingBugtracker#7224]
[//]: # (Enclose links to things related to the bug using http://wowhead.com or any other TBC database.)
[//]: # (You can use screenshot ingame to visual the issue.)
[//]: # (Write your tickets according to the format:)
[//]: # ([Quest][Azuremyst Isle] Red Snapper - Very Tasty!)
[//]: # ([NPC] Magistrix Erona)
[//]: # ([Spell][Mage] Fireball)
[//]: # ([Npc][Drop] Ghostclaw Lynx)
[//]: # ([Web] Armory doesnt work)
[//]: # (To find server revision type `.server info` command in the game chat.)

**Description**:  Daphne the npc needed to talk to was just zoning in and out, my mate stood there waiting for 10+min

**Current behaviour**:

**Expected behaviour**: 

**Server Revision**:

**Comment by therealCrysis** [comment]
https://youtu.be/XeNhvv6OPqg

It looks like this.

**Comment by Tereneckla** [comment]
#707
