### ISSUE TITLE
Tome of Valor part 2

### ISSUE THREAD

**Issue by Magibum** [Atlantiss/NetherwingBugtracker#7227]
https://classic.wowhead.com/npc=6182/daphne-stilwell#comments

[Quest][Westfall] The Tome of Valor
[NPC] Daphne Stilwell

**Description**: 
Bugged Paladin Quest
**Current behaviour**:
The Npc just despawns 1 second after spawning
**Expected behaviour**: 
The Npc shouldnt despawn instantly and let me do my Quest

**Comment by Tereneckla** [comment]
Duplicate of #707
