### ISSUE TITLE
Looting is not round-robin / group loot

### ISSUE THREAD

**Issue by identitateliviu** [Atlantiss/NetherwingBugtracker#7228]
[//]: # (Enclose links to things related to the bug using http://wowhead.com or any other TBC database.)
[//]: # (You can use screenshot ingame to visual the issue.)
[//]: # (Write your tickets according to the format:)
[//]: # ([Quest][Azuremyst Isle] Red Snapper - Very Tasty!)
[//]: # ([NPC] Magistrix Erona)
[//]: # ([Spell][Mage] Fireball)
[//]: # ([Npc][Drop] Ghostclaw Lynx)
[//]: # ([Web] Armory doesnt work)
[//]: # (To find server revision type `.server info` command in the game chat.)

**Description**: 

This is a bug that is taking place on Karazhan (the new server).

While you're in an instance with group loot ON and the threshold set to uncommon, "trash" loot (white or grey items) are not actually being distributed in a round-robin manner. Instead, they appear to be lootable by anyone (FFA), despite group loot being set to on.

What this means is that melee are able to loot everything quickly, whereas ranged/casters/healers get nothing.

This is a serious bug and it will result in casters/ranged ending up at 58-60 with no gold at all.

**Current behaviour**:

Mobs are lootable by anyone who gets to their corpses first (this applies to grey/white items only). "My" mob is always looted by whoever reached it first (typically the tank or a melee char). As a result, I get no "trash" loot and I have nothing to vendor at the end of the instance.

**Expected behaviour**: 

White/grey items on "my" mobs should only be lootable by me.

**Server Revision**: 

3486

**Comment by Wolffenstein** [comment]
I could use a video of that happening, because it works as intended when I'm testing it locally. I have two characters - Netherwing and Shamanus. This Defias Miner's loot was tied to Shamanus:

What Netherwing sees:
![obraz](https://user-images.githubusercontent.com/1576644/88484224-586aca80-cf6d-11ea-9de5-9051ffb11c75.png)

What Shamanus sees:
![obraz](https://user-images.githubusercontent.com/1576644/88484240-6a4c6d80-cf6d-11ea-8e98-292ef42d4b21.png)

One important thing to note is that once Shamanus closes the loot window, the remaining loot is turned into FFA, perhaps leading to the issue you have described. The mob's little status info should show who the loot belongs to:
![obraz](https://user-images.githubusercontent.com/1576644/88484266-97008500-cf6d-11ea-9a0c-672f967f5c16.png)

Which should help debug this problem, if the issue is actually present.

**Comment by identitateliviu** [comment]
I suppose the only option I've got is to record it, so you can understand what I'm talking about.

I'll try to do that this evening, although I'm not sure of whether I'll be able to (I need a group etc).

**Comment by Krieos** [comment]
I made a video showing the issue. I've never actually recorded and I do not have a video editor so it is a bit scuffed, but you can skip around to see the issue. I purposefully was not looting so you could see that it was acting as free for all and the first person to loot would get all the trash on the mob. Greens and higher quality items work correctly. 

Around 0:50, 2:35, and 4:30 are they times with examples. https://www.youtube.com/watch?v=f1OHahLymoM&feature=youtu.be

**Comment by identitateliviu** [comment]
A brief video (not the best, but I believe it's enough to explain the issue) here:

https://www.youtube.com/watch?v=pcMqJb0FVHc&feature=youtu.be

It took me a while to find a group today so...

The idea is that that's what I'm seeing in EVERY.SINGLE.INSTANCE. 

I leave instance poorer than I was when I entered simply because I get nothing, but I spent silver on arrows/meat for the pet.

This can't possibly be intended....or can it?

**Comment by identitateliviu** [comment]
I'll try to clarify one thing - I should've underlined that thing above.

This isn't about SM GY or about that particular type of mob. This happened in every instance I've been in since launch, with every mob. I get loot off a mob once in a blue moon and I usually wonder whether the tank's bags are now full or something, because it's certainly unexpected.

Basically, the idea is....no cloth, no whites, no greys. Hardly anything to vendor - ever.

**Comment by abechang23** [comment]
I have experienced this exact issue and I spent hours today running SM with the same group of people. Group loot does not work as intended at all - it is basically on FFA so melee get to loot all the cloth and vendor trash. I went more than one instance without a single dead mob looted. Pretty game-breaking if you ask me and according to people on the Discord this is something we are all noticing.

**Comment by Wolffenstein** [comment]
Please check again in revision 3489. Also try setting the loot to round robin instead of group loot, and see if that helps.

**Comment by identitateliviu** [comment]
> Please check again in revision 3489. Also try setting the loot to round robin instead of group loot, and see if that helps.

This wasn't fixed earlier, in 3494. However, the server is supposed to restart again now to "fix a loot issue", so perhaps that will fix it?
