### ISSUE TITLE
Bestial Swiftness 

### ISSUE THREAD

**Issue by Malevolance** [Atlantiss/NetherwingBugtracker#7230]
**Description**: 
bestial swiftness gets bugged if you log in inside a building or when you get off a flightpath inside a city 
video links: https://streamable.com/n43g7o
https://streamable.com/3ymw99
https://streamable.com/6tu9iq

https://tbc-twinhead.twinstar.cz/?spell=19596
**Current behaviour**:
 the pet speed increase doesnt apply
**Expected behaviour**: 
the movement speed should apply in all outdoor areas
**Server Revision**: 
3488

**Comment by 4egito** [comment]
**"It's important to note that the effects that increase pet pursuit speed are all multiplicative: that is, when it says that Bestial Swiftness increases the pet's speed by 30%, it really means that it multiplies the pet's base speed by 1.3, not that it adds 30% to the base speed. So a 115% pet under the effects of Bestial Swiftness actually pursues at 149.5%, not 145%."**
Source with additional info about pet pursuit speed: http://web.archive.org/web/20070326181404/http://petopia.brashendeavors.net:80/html/articles/stats_pursuitspeed.shtml There is some info about pet

**Comment by yoyosan** [comment]
This is so annoying 😢

**Comment by Isz55** [comment]
Talent is still bugged. (exactly as described in the first post). The only way to fix it, is talent reset/respec. (relog or dismiss pet dosen't work)

Server Revision:
3987

**Comment by Godmatik** [comment]
Duplicate #9124
