### ISSUE TITLE
[Quest] Multiple escort quests

### ISSUE THREAD

**Issue by polygxn** [Atlantiss/NetherwingBugtracker#7231]
**Description**: You can start the quest with no issues, encounters appear during the escort then at the end Cork Gizelton (NPC ID: 11625) says it's dialouge, thanks you for the escort and just walks off. The quest does not get completed however. https://tbcdb.com/?quest=5943

Same issue with the following quests:
https://tbcdb.com/?quest=9759
https://tbcdb.com/?quest=2904

**Current behaviour**: The caravan should start from 40.6, 79.2, or 45.6, 75.2 in Desolace, and end around 67.2, 39.4. Everything works fine with this quest other than the fact that you don't get your quest completed.

Same thing with the other quests, the script works just fine, but at the end the quest does not get flagged as completed.

**Expected behaviour**: 
https://www.youtube.com/watch?v=v1HdOknErOw
https://www.youtube.com/watch?v=lARzK9CLu24
https://www.youtube.com/watch?v=Bv0WKTNodJI

**Server Revision**: 3488

**Comment by Godmatik** [comment]
Both Quest 5821 (Bodyguard for Hire) + Quest 5943 (Gizelton Caravan) worked just fine for me, got completion at the end of each no problems.

Tested the other two quests linked here (9759 and 2904), both also worked fine
