### ISSUE TITLE
[NPC] Night Elf Ambusher

### ISSUE THREAD

**Issue by polygxn** [Atlantiss/NetherwingBugtracker#7232]
**Description**: Night Elf Ambushers (NPC ID: 16238) spawn way too quickly, constantly killing the quest giver Magister Sylastor (NPC ID: 16237) and it's bodyguards. Also, Magister Sylastor sometimes spawn back in a weird position, and his bodyguards does not help him killing the Ambushers (https://i.imgur.com/IjZi23R.jpeg).

**Current behaviour**: Night Elf Ambushers spawn in a group of two, every 5-10 seconds until Magister Sylastor is dead. After that they despawn. Also, they not always attack Sylastor, most of the time they just stack on eachother. I assume there is an issue with the Ambushers aggro range, or something like that.

**Expected behaviour**: I have no proof that this is not the normal behaviour, couldn't find any older video or simple information about it but if you guys have couple of free minutes to look at it please do so. The quick respawn time of Sylastor makes things better though.

**Server Revision**: 3488

**Comment by Wolffenstein** [comment]
Fixed in rev 3493.
