### ISSUE TITLE
Desolace | Fish in a Bucket / Bone Collector

### ISSUE THREAD

**Issue by zygzz** [Atlantiss/NetherwingBugtracker#7233]
https://classic.wowhead.com/quest=5421/fish-in-a-bucket

https://classic.wowhead.com/quest=5501/bone-collector

**Description**:  Both quests are located in Desolace and function similarly involving looting items off the ground with a chance to summon mobs or grant items needed for quests.

**Current behaviour**: For Bone Collector, kodo ghosts spawn non stock every click. For Fish in a Bucket, the crabs that can spawn can be spawned in a delayed manner for each right click attempt to open the pots. This can lead to duplicate mobs that stack perfectly ontop of eachother -- apprearing as a single crab until u agro and get one shot.

**Expected behaviour**:  Crabs should spawn AFTER pot is opened and despawned to avoid the ability to stack multiple crabs together. For the kodo bones, there is a percentage chance to loot the bone without a kodo ghost spawning. 

**Server Revision**: 3488

**Comment by Wolffenstein** [comment]
Fixed in rev 3491.
