### ISSUE TITLE
[NPC] Stonewing Tracker, Wand interaction

### ISSUE THREAD

**Issue by biggiestronk** [Atlantiss/NetherwingBugtracker#7234]
minor bug:
**[NPC] Stonewing Tracker** mob in Ghostlands casts **"Stone Skin":**

**[Physical damage taken is reduced by 15.
Movement speed reduced by 67%.]**

This appears to apply to wand damage, which is supposed to be magic damage. I'm seeing the 15 dmg reduction on my wand casts. 

Not sure if other effects are currently acting in the same way--which could mean this bug is more important than a ghostlands mob.

**Comment by Wolffenstein** [comment]
Which wand are you using exactly?

**Comment by Godmatik** [comment]
Wand is coded as physical damage, same as classic
