### ISSUE TITLE
Heroic Strike unqueues itself when attempting to use Execute

### ISSUE THREAD

**Issue by Kaiokenx** [Atlantiss/NetherwingBugtracker#7235]
[//]: # (Enclose links to things related to the bug using http://wowhead.com or any other TBC database.)
[//]: # (You can use screenshot ingame to visual the issue.)
[//]: # (Write your tickets according to the format:)
[//]: # ([Quest][Azuremyst Isle] Red Snapper - Very Tasty!)
[//]: # ([NPC] Magistrix Erona)
[//]: # ([Spell][Mage] Fireball)
[//]: # ([Npc][Drop] Ghostclaw Lynx)
[//]: # ([Web] Armory doesnt work)
[//]: # (To find server revision type `.server info` command in the game chat.)

**Description**: 
Heroic Strike will cancel in the middle of the swing timer if Execute is attempted when a mob is above 20% and is not able to cast. A white swing will result instead.
**Current behaviour**:
https://www.youtube.com/watch?v=hQx3SwmgZ_U

Execute currently "interrupts" something which I believe to be Heroic Strike.
**Expected behaviour**: 
https://www.youtube.com/watch?v=Lgg4R8Tlpas

In both videos, I spam execute while having heroic strike queued up and the expected behavior should be that Execute does not interact whatsoever with Heroic Strike. This may also be bugged with Cleave but I didn't test that in the videos.
**Server Revision**: 
3488

**Comment by Wolffenstein** [comment]
Fixed in rev 3517.
