### ISSUE TITLE
Questbug "Notshared" Alas, Andorhal

### ISSUE THREAD

**Issue by Kliern** [Atlantiss/NetherwingBugtracker#7236]
[//]: # (Enclose links to things related to the bug using http://wowhead.com or any other TBC database.)
https://classic.wowhead.com/quest=105/alas-andorhal
[//]: # (Write your tickets according to the format:)
[//]: # ([Quest][Azuremyst Isle] Red Snapper - Very Tasty!)
[//]: # ([NPC] Magistrix Erona)
[//]: # ([Spell][Mage] Fireball)
[//]: # ([Npc][Drop] Ghostclaw Lynx)
[//]: # ([Web] Armory doesnt work)
[//]: # (To find server revision type `.server info` command in the game chat.)

**Description**: 
Quest: [Western Plaguelands] Alas, Andorhal.
**Current behaviour**:
Only giving 1 questreward per kill (Drops container which you need to pickup) 
**Expected behaviour**: 
Questsharing on server would mean all in party atleast could pick it up?
**Server Revision**: 
2488

**Comment by Wolffenstein** [comment]
Fixed in revision 3489.
