### ISSUE TITLE
Paladin spell delay

### ISSUE THREAD

**Issue by B0nisek** [Atlantiss/NetherwingBugtracker#7237]
**Description**:  got some weird delay between casting a bubble.

**Current behavior**: cast a bubble, it goes on CD, still die

**Expected behaviour**: cast a bubble, it goes on CD, you no die

![image](https://user-images.githubusercontent.com/22475895/88670339-3ac07100-d0e5-11ea-9fb2-0ad04dedaca2.png)

**Comment by Evolvee** [comment]
@B0nisek kedy dojedes do ty prahy? dame gym s křídlem

**Comment by Evolvee** [comment]
bonisek boomer xd

**Comment by empor0** [comment]
I have experience with seal activation delay, that is about 0,5 sec. If you cast seal of crusader and switch to seal of righteousness and cast judgement immediately it will apply effect of CRUSADER not righteousness. And this applies even to attacks with seals, if you cast seal and hit target under 0,5 sec, it will apply no effect of the seal. GM told me that this is to enable seal twisting, this could be true for attacking with seals but NOT for judgement effects. This can be real problem for pala tanks. You start with seal of crusader to judgement for increasing holy damage but if someone accidentally pulls you cast seal of righteousness to do holy damage to make threat but if you do it fast you judgement crusader instead altough you activated righteousness, it will do no damage and no threat. Thank you.

**Comment by Tereneckla** [comment]
@empor0 #6405
Your issue is described there

**Comment by Godmatik** [comment]
Can not reproduce it, have not heard any paladin experiencing this issue in the past year on Netherwing.

Closing.
