### ISSUE TITLE
[NPC][Drop] Mutanus the Devourer

### ISSUE THREAD

**Issue by polygxn** [Atlantiss/NetherwingBugtracker#7238]
**Description**: Mutanus the Devourer (NPC ID: 3654) should drop the item Glowing Shard (Item ID: 10441) with a 100% chance. We got multiple tickets about this issue.

**Current behaviour**: It is not 100% drop chance, or does not even drop at all.

**Expected behaviour**: Most of the TBC databases says 100% drop chance, so it should be that way.

**Server Revision**: 3488

**Comment by Godmatik** [comment]
Confirmed it is 100% in database.
Must have been fixed at some point - closing
