### ISSUE TITLE
Gurky donator pet no idle dance [Pink Murloc Egg]

### ISSUE THREAD

**Issue by whateverbrah** [Atlantiss/NetherwingBugtracker#7239]
[//]: # (You can use screenshot ingame to visual the issue.)
[//]: # (Write your tickets according to the format:)
[//]: # ([Quest][Azuremyst Isle] Red Snapper - Very Tasty!)
[//]: # ([NPC] Magistrix Erona)
[//]: # ([Spell][Mage] Fireball)
[//]: # ([Npc][Drop] Ghostclaw Lynx)
[//]: # (To find server revision type `.server info` command in the game chat.)

**Description**: 
The donator pet murloc Gurky idle dance animation does not work

**Current behaviour**:
It doesn't dance when idle like the other murloc pets on the donator store.

**Server Revision**: 
3488

**Comment by Wolffenstein** [comment]
Should be fixed now.
