### ISSUE TITLE
Razormane Pathfinder spawning constantly outside Call of Water hut in Barrens. Causing client side lag

### ISSUE THREAD

**Issue by Minimix186** [Atlantiss/NetherwingBugtracker#7240]
[//]: # (Enclose links to things related to the bug using http://wowhead.com or any other TBC database.)
[//]: # (You can use screenshot ingame to visual the issue.)
[//]: # (Write your tickets according to the format:)
[//]: # ([Quest][Azuremyst Isle] Red Snapper - Very Tasty!)
[//]: # ([NPC] Magistrix Erona)
[//]: # ([Spell][Mage] Fireball)
[//]: # ([Npc][Drop] Ghostclaw Lynx)
[//]: # ([Web] Armory doesnt work)
[//]: # (To find server revision type `.server info` command in the game chat.)

**Description**: 

https://i.imgur.com/6XEnDlg.jpg

Location is outside Call of Water quest area. Brine is the NPC if you want to teleport to them. 44, 76 is roughly the cords

**Current behaviour**:

As image above

**Expected behaviour**: 

Only 1 should spawn.

**Server Revision**:

**Comment by Tereneckla** [comment]
Fixed in 3493
