### ISSUE TITLE
Players appearing to fall from sky while on taxi

### ISSUE THREAD

**Issue by Minimix186** [Atlantiss/NetherwingBugtracker#7241]
[//]: # (Enclose links to things related to the bug using http://wowhead.com or any other TBC database.)
[//]: # (You can use screenshot ingame to visual the issue.)
[//]: # (Write your tickets according to the format:)
[//]: # ([Quest][Azuremyst Isle] Red Snapper - Very Tasty!)
[//]: # ([NPC] Magistrix Erona)
[//]: # ([Spell][Mage] Fireball)
[//]: # ([Npc][Drop] Ghostclaw Lynx)
[//]: # ([Web] Armory doesnt work)
[//]: # (To find server revision type `.server info` command in the game chat.)

**Description**: 

https://i.imgur.com/eO9NWL6.jpg

Happens with both factions, fairly frequently. They will disappear after 5-10secs

**Current behaviour**:

As image above

**Expected behaviour**: 

**Server Revision**:

**Comment by Tereneckla** [comment]
Errm, movement packets I think

**Comment by Wolffenstein** [comment]
Visual bug, happened to me on classic as well I think.
