### ISSUE TITLE
Player send message in /dnd

### ISSUE THREAD

**Issue by cssarto** [Atlantiss/NetherwingBugtracker#7242]
**Description**: 
a player typed me a message at random, after I ignore it, but even so, a yellow message appears on the / dnd that it displays gold.

could you do something to take this off please

![image](https://user-images.githubusercontent.com/17818760/88812128-c097f700-d18d-11ea-95d1-1a1bc0c85ffc.png)

**Comment by Tereneckla** [comment]
Just don't write them after you ignore
