### ISSUE TITLE
Daze rates are incorrect

### ISSUE THREAD

**Issue by Jseay1313** [Atlantiss/NetherwingBugtracker#7243]
**Description**: Daze rates are extremely incorrect on Karazahn (and was a problem on netherwing as well) with daze chance being up to 50% on same level mobs.

**Current behaviour**: Daze rate is incorrect, and likely higher than the 40% cap

**Expected behaviour**:  Daze should be 20% if the mob is the same level/and or same defense # as the player, scaling higher if the players level is lower or the mobs defense is higher, and scaling lower if the defense of the player/level are higher.

https://vanilla-wow.fandom.com/wiki/Daze  ~ Relative to classic a mob 10 levels below you will not daze you, so I believe the reduction is 2% in each direction per level.

**Server Revision**: 3493

**Comment by Tenoutoften** [comment]
>Relative to classic a mob 10 levels below you will not daze you
This should mean that if you got +50 Defense skill above the mob the chance is 0%. 
Currently you get dazed even if you are +150 Defense skills above the mobs, not sure if there is any limited at all.

**Comment by Wolffenstein** [comment]
Fixed in rev 3536.
