### ISSUE TITLE
Zangarmarsh Stealth Bug

### ISSUE THREAD

**Issue by MrShiny64** [Atlantiss/NetherwingBugtracker#7244]
[//]: # (Enclose links to things related to the bug using http://wowhead.com or any other TBC database.)
[//]: # (You can use screenshot ingame to visual the issue.)
[//]: # (Write your tickets according to the format:)
[//]: # ([Quest][Azuremyst Isle] Red Snapper - Very Tasty!)
[//]: # ([NPC] Magistrix Erona)
[//]: # ([Spell][Mage] Fireball)
[//]: # ([Npc][Drop] Ghostclaw Lynx)
[//]: # ([Web] Armory doesnt work)
[//]: # (To find server revision type `.server info` command in the game chat.)

**Description**: Been leveling for 62 levels with no issues, but as soon as I'm in Zangarmarsh theres been two instances of not being able to stealth while not in combat. Once when I entered a cave to the south and the second after I resssed, it says the 'ability is not ready yet'. I'm not in combat from anything and the ability is just blacked out. Logging out is the only fix so far.

**Current behaviour**:

**Expected behaviour**: 

**Server Revision**:

**Comment by Wolffenstein** [comment]
Perhaps you had this debuff on you? https://www.wowhead.com/spell=35328/lambent-blood

**Comment by MrShiny64** [comment]
Definitely not, a hunter in my guild just got the same bug in hellfire. He couldn't feign death, said 'ability is not ready yet' while its just greyed out. Not on cooldown

**Comment by Godmatik** [comment]
The feign death bug was fixed a few weeks ago that he describes. 

Dunno about the stealth bug but I have not heard of any issues personally of rogues not being able to stealth, this bug either never existed or was resolved
