### ISSUE TITLE
[Spell] [Cheap Shot]

### ISSUE THREAD

**Issue by fosquaker** [Atlantiss/NetherwingBugtracker#7246]
https://gfycat.com/LikelyEagerAfricanparadiseflycatcher
you can drop combat right after cheap shot if u'll stop auto attack

rev 3494

**Comment by nullfoxh** [comment]
Also seen this with mobs while grouped, but is probably limited to PvE when mob is targeting someone else. Have not had this occur in pvp so far.

**Comment by Wolffenstein** [comment]
Fixed in rev 3520.
