### ISSUE TITLE
([Spell][Shaman] Windfury Totem) Windfury attacks generate no rage for the additional attacks

### ISSUE THREAD

**Issue by bmiles2001** [Atlantiss/NetherwingBugtracker#7247]
[//]: # (Enclose links to things related to the bug using http://wowhead.com or any other TBC database.)
[//]: # (You can use screenshot ingame to visual the issue.)
[//]: # (Write your tickets according to the format:)
[//]: # ([Quest][Azuremyst Isle] Red Snapper - Very Tasty!)
[//]: # ([NPC] Magistrix Erona)
[//]: # ([Spell][Mage] Fireball)
[//]: # ([Npc][Drop] Ghostclaw Lynx)
[//]: # ([Web] Armory doesnt work)
[//]: # (To find server revision type `.server info` command in the game chat.)

**Description**: 
As a warrior, I've observed that the extra attacks generated with a windfury proc appear to generate zero rage. I see the tornado animation over my character and I assume it generates damage.

**Current behaviour**:
- I hit a mob and generate rage from that initial hit. Windfury procs
- Extra attacks appear on my screen hitting the mob extra times
- Those extra attacks deal damage, but add 0 rage to my bar. 

**Expected behaviour**: 
- The extra attacks generated via windfury should generate rage based on the damage dealt from those attacks

**Server Revision**: 
Karazhan | Content Patch 2.0.3 | Revision: 3494

**Comment by Peglaa** [comment]
Possibly true. Do you have any evidence of your own? All I could dig up was this post which could probably count as proof:
https://blue.mmo-champion.com/topic/18050-tbc-enhancement-shaman-faq/#:~:text=%2D%20The%20windfury%20totem%20enchant%20for,These%20attacks%20also%20generate%20rage.

_"- The windfury totem enchant for your group will proc on ALL melee attacks except for itself, such as sinister strike, sword spec, heroic strike, etc. These attacks also generate rage. Windfury totem is the best melee buff in the game for combat rogues, ret paladins, and warriors."_

note that this is supposed to apparently be for patch 2.1, not sure if it changes later on in the expansion or not.

There are also some classic wow discussions about this, for whats its worth(which is prolly not much but they do confirm this behavior):
https://www.reddit.com/r/classicwow/comments/b2lt51/do_windfury_totem_attacks_generate_rage_for/

https://us.forums.blizzard.com/en/wow/t/warriors-and-wf-totem/162988/6

**Comment by bmiles2001** [comment]
Well in Classic, I know that when I'm not yelling at Shamans, I was getting decent rage out of windfury as DPS but I never paid attention to it 100%. I just never had rage issues.  On this server, I consistently have no or very little rage, as a tank, with windfury. On Classic, if I am tanking it's like endless rage.

However, another unsupported question would be, is the rage algorithm different on Classic vs TBC ?

**Comment by Tereneckla** [comment]
I am getting rage from the windfury attacks.
