### ISSUE TITLE
Companion Names

### ISSUE THREAD

**Issue by Scyllaqt** [Atlantiss/NetherwingBugtracker#725]
**Description**: 
Whenever you /emote someone's companion or their companion speaks in chat, their name shows up as "Player's Companion" instead of the companions actual name. "Murky" for example.
**Current behaviour**:
https://imgur.com/A1a2iZT
**Expected behaviour**: 
It should say "You gently pat Ethereal Soul-Trader."
**Server Revision**: 
2065

**Comment by Wolffenstein** [comment]
I think this issue is only for Ethereal Soul-Trader

**Comment by Tenoutoften** [comment]
It's also only when he spawns, other than that he will use his NPC name

**Comment by Tenoutoften** [comment]
![](https://i.gyazo.com/920401a7122e329c16fcab313c804ed0.png)

**Comment by Tereneckla** [comment]
This issue is for all companions.

**Comment by Godmatik** [comment]
Guess it was fixed at some point.

Closing.

![trader](https://github.com/Atlantiss/NetherwingBugtracker/assets/37913400/68723a48-8afb-463f-8de4-97878691a680)
