### ISSUE TITLE
Hunter Frost Trap Trigger Radius

### ISSUE THREAD

**Issue by bagda391** [Atlantiss/NetherwingBugtracker#7250]
[//]: # (Enclose links to things related to the bug using http://wowhead.com or any other TBC database.)
[//]: # (You can use screenshot ingame to visual the issue.)
[//]: # (Write your tickets according to the format:)
[//]: # ([Quest][Azuremyst Isle] Red Snapper - Very Tasty!)
[//]: # ([NPC] Magistrix Erona)
[//]: # ([Spell][Mage] Fireball)
[//]: # ([Npc][Drop] Ghostclaw Lynx)
[//]: # ([Web] Armory doesnt work)
[//]: # (To find server revision type `.server info` command in the game chat.)

**Description**: 
I believe the freezing of hunters is triggering in a wider radius than normal. My friend and I have gone through several hunter pvp encounters where the trap triggers on anyone around 5-10 yards radius around it.
**Current behaviour**:
Trap triggers on enemies up to 10 yards around the trap
**Expected behaviour**: 
Trap should trigger on people who walk over it.
**Server Revision**:

**Comment by Tereneckla** [comment]
#3649 The trigger radius is supposed to be bigger than just the trap.
