### ISSUE TITLE
Drain Life being cancelled randomly (says interrupted multiple times on-screen) but uses mana etc. HAVE checked combat log, and it's not being resisted

### ISSUE THREAD

**Issue by Popmycherry** [Atlantiss/NetherwingBugtracker#7252]
[//]: # (Enclose links to things related to the bug using http://wowhead.com or any other TBC database.)
[//]: # (You can use screenshot ingame to visual the issue.)
[//]: # (Write your tickets according to the format:)
[//]: # ([Quest][Azuremyst Isle] Red Snapper - Very Tasty!)
[//]: # ([NPC] Magistrix Erona)
[//]: # ([Spell][Mage] Fireball)
[//]: # ([Npc][Drop] Ghostclaw Lynx)
[//]: # ([Web] Armory doesnt work)
[//]: # (To find server revision type `.server info` command in the game chat.)

**Description**: 
Well, much as title says. It randomly just gets interrupted, and once it starts, you can spam Drain Life multiple times and it will keep being interrupted until mob dies. Doesn't work to de-target and target, nor can you drain life another target, it will Interrupted as well. I will upload a video on YT and reply it here.
**Current behaviour**:
Well, read above.
**Expected behaviour**: 
Either say resisted (and so in combat log as well) OR actually go through and drain life as expected.
**Server Revision**: 
I dont know? Karazhan? so 3494 ?

**Comment by Popmycherry** [comment]
https://youtu.be/Bp7tmd_Cz3g

Unsure why the video doesn't have sound

**Comment by Tereneckla** [comment]
Same as #4018

**Comment by Godmatik** [comment]
Resolved several months ago
