### ISSUE TITLE
just Too many vein spawns

### ISSUE THREAD

**Issue by TechnoMulen** [Atlantiss/NetherwingBugtracker#7253]
[//]: # (Enclose links to things related to the bug using http://wowhead.com or any other TBC database.)
[//]: # (You can use screenshot ingame to visual the issue.)
[//]: # (Write your tickets according to the format:)
[//]: # ([Quest][Azuremyst Isle] Red Snapper - Very Tasty!)
[//]: # ([NPC] Magistrix Erona)
[//]: # ([Spell][Mage] Fireball)
[//]: # ([Npc][Drop] Ghostclaw Lynx)
[//]: # ([Web] Armory doesnt work)
[//]: # (To find server revision type `.server info` command in the game chat.)

**Description**: 
As a miner i just see too many vein spawns.. i can go into a cave and have 8 spawns on the minimap and  thats for almost every cave.  Tin ores are worth about 1 silver each?! 
Mithril normally should sell for around 20-25g pr stack on tbc servers - here it is less than 6g 
Thorium ore is almost the same. 
**Current behaviour**:

**Expected behaviour**: 
you can take that number down by 80% and it would be normal rates

**Server Revision**:

**Comment by The14me** [comment]
True
https://www.youtube.com/watch?v=EUjEga4YeA8

**Comment by Wolffenstein** [comment]
Fixed in rev 3503.
