### ISSUE TITLE
[Quest][Item] "Waste No, Want Not" can't gather wood

### ISSUE THREAD

**Issue by KurtySuit** [Atlantiss/NetherwingBugtracker#7255]
https://i.imgur.com/NMKgzoy.png

Can't loot any wood or metal from this quest (i saw horde players took it, so it seems to only apply to me)

EDIT: abandon quest, took it again, seems to work so far

**Comment by The14me** [comment]
U cant pick opposite faction ''wood/metal'' so stick to your side of the map and everything will be ok (Horde top half/ Allies button half) 
https://www.wowhead.com/quest=10055/waste-not-want-not#comments:id=224097
Can be closed.

**Comment by KurtySuit** [comment]
Damn, i feel stupid, sorry about that.
