### ISSUE TITLE
Auction House "Usable Items" Checkbox Broken 

### ISSUE THREAD

**Issue by aeturnum** [Atlantiss/NetherwingBugtracker#7256]
[//]: # (Enclose links to things related to the bug using http://wowhead.com or any other TBC database.)
[//]: # (You can use screenshot ingame to visual the issue.)
[//]: # (Write your tickets according to the format:)
[//]: # ([Quest][Azuremyst Isle] Red Snapper - Very Tasty!)
[//]: # ([NPC] Magistrix Erona)
[//]: # ([Spell][Mage] Fireball)
[//]: # ([Npc][Drop] Ghostclaw Lynx)
[//]: # ([Web] Armory doesnt work)
[//]: # (To find server revision type `.server info` command in the game chat.)

**Description**: 
Checking "Usable Items" returns no results, even though my character can use many of the items on the auction house.

**Current behaviour**:
Checking the Usable Items checkbox eliminates all results:
![Auction_Usable](https://user-images.githubusercontent.com/2303837/89067083-721c6100-d323-11ea-8205-00353b8aeccb.png)

**Expected behaviour**: 
Here is a search for leather that requires level 30-35 on my 36 druid (I can use all of these items):
![Auction_NoUsable](https://user-images.githubusercontent.com/2303837/89066954-34b7d380-d323-11ea-867a-6c9b742285f3.png)

The same parameters, using the "Usable Items" checkbox, should have this result.

**Server Revision**: 
Karazhaan / content 2.0.3 / revision 3494

**Comment by Wolffenstein** [comment]
Fixed a while ago.
