### ISSUE TITLE
[Spell][Paladin] Seal of Wisdom

### ISSUE THREAD

**Issue by abacus789** [Atlantiss/NetherwingBugtracker#7259]
[//]: # (Enclose links to things related to the bug using http://wowhead.com or any other TBC database.)
[//]: # (You can use screenshot ingame to visual the issue.)
[//]: # (Write your tickets according to the format:)
[//]: # ([Quest][Azuremyst Isle] Red Snapper - Very Tasty!)
[//]: # ([NPC] Magistrix Erona)
[//]: # ([Spell][Mage] Fireball)
[//]: # ([Npc][Drop] Ghostclaw Lynx)
[//]: # ([Web] Armory doesnt work)
[//]: # (To find server revision type `.server info` command in the game chat.)

**Description**: I purchased Seal of Wisdom and it doesn't appear in my spellbook or the trainer's book. I checked each filter in their book. I also cleared my cache and restarted the client. Rank 2 appears in the trainer's book but Rank 1 isn't available to my character.

**Current behaviour**: Seal of Wisdom Rank 1 is not available to my character after purchasing.

**Expected behaviour**: Seal of Wisdom Rank 1 would appear in my spellbook.

**Server Revision**: 3494

**Comment by Tereneckla** [comment]
Did you try disabling addons. It's showing up fine for me.
