### ISSUE TITLE
Lieutenant Valorcall Arathi Highlands

### ISSUE THREAD

**Issue by Piledriversn** [Atlantiss/NetherwingBugtracker#726]
Lieutenant Valorcall and his Guards seem to be frozen in place. 
![image](https://user-images.githubusercontent.com/43560552/46117187-7d515380-c1c5-11e8-9b0f-64007e1b0e3e.png)

**Comment by Piledriversn** [comment]
After I took this screenshot I killed him but he didn't do much but his bubble. Later i saw him back on his patrol. I

**Comment by aresbrutus** [comment]
It seems to work for me, will re-check if it gets reported again since then the issue might be something else.
