### ISSUE TITLE
Loot rolls deny skinning while in group

### ISSUE THREAD

**Issue by moemiki** [Atlantiss/NetherwingBugtracker#7260]
**Description**: 
Green (blue and epic too?) items, which drop while being in group (group loot) deny the mob in question to be skinned after the green/blue/epic items have been looted and received.

**Expected behaviour**: 
Skinnable mobs should be able to be skinned after loot has been distributed.

**Server Revision**: 3497

EDIT: Found out about this while being in a "dungeon group forming up" and noone else in the group was in the zone with me.

**Comment by danbopes** [comment]
Is this issue still happening?

**Comment by Godmatik** [comment]
Rev 4016 - no longer an issue
