### ISSUE TITLE
[Spell] Fear [Movement] Teleport player

### ISSUE THREAD

**Issue by The14me** [Atlantiss/NetherwingBugtracker#7261]
**Current behaviour**: Every spell that have ''fear'' effect teleport the player around. Its fast movement + small teleports.

**Expected behaviour**:  No teleport.

**Server Revision**:  3497

**Comment by The14me** [comment]
https://github.com/Atlantiss/NetherwingBugtracker/issues/2116
https://github.com/Atlantiss/NetherwingBugtracker/issues/1956

**Comment by Godmatik** [comment]
Can't reproduce... must have been fixed at some point.
