### ISSUE TITLE
[Quest] Broken Alliances [Movement] 

### ISSUE THREAD

**Issue by The14me** [Atlantiss/NetherwingBugtracker#7263]
**Current behaviour**: The path is.... bit strange.
https://cdn.discordapp.com/attachments/720108153047613462/739139459882156133/unknown.png

**Expected behaviour**:  Not supposed to fly
https://classic.wowhead.com/quest=782/broken-alliances

**Server Revision**:  3497

**Comment by Godmatik** [comment]
Followed him during his entire path around Badlands - I noticed nothing strange nor any flying - original image link is broken
