### ISSUE TITLE
Pet pathfinding

### ISSUE THREAD

**Issue by x-x-x-x-x-x-x-x-x-x-x-x** [Atlantiss/NetherwingBugtracker#7265]
**Description**: 
Pets get stuck often when trying to attack a mob or follow. Sometimes there's no visible obstacle, other times it's a slope or w/e

**Server Revision**: 
3497

**Comment by Tereneckla** [comment]
Could you tell us the places where you experienced this please. I had no problems with the pet pathing so far.

**Comment by x-x-x-x-x-x-x-x-x-x-x-x** [comment]
All over the place. I think it happened to most when I was in Feralas.

**Comment by Godmatik** [comment]
Description much too vague - I've been a hunter this past year, have not noticed this issue.

Perhaps fixed a while ago.
