### ISSUE TITLE
[Druid] Cannot auto-dismount/cast spells while in flight form.

### ISSUE THREAD

**Issue by Jseay1313** [Atlantiss/NetherwingBugtracker#7267]
**Description**: TBC adds the auto shift feature for druids, including being force shifted out when casting any spell, this flag is currently not on flight form as well forcing the player to manually deshift.

**Current behaviour**: You are given a "you are in shapeshift form" error text when trying to use any ability when in flight form.

**Expected behaviour**:  The form has the same behavior as cat/bear/travel etc.

**Server Revision**: 3496

**https://www.wowace.com/projects/mounted/issues/47 looking through google just for additional evidence found something similar on an ancient private server.

**Comment by Tereneckla** [comment]
Auto shift out of flight form only works, when you're on the ground.

https://wowwiki.fandom.com/wiki/Flight_Form
Tips and tactics here speak of unshifting before doing stuff while flying.
