### ISSUE TITLE
[Warlock][Pet] Felguard name reset.

### ISSUE THREAD

**Issue by Rycezul** [Atlantiss/NetherwingBugtracker#7268]
[//]: # (Enclose links to things related to the bug using http://wowhead.com or any other TBC database.)
[//]: # (You can use screenshot ingame to visual the issue.)
[//]: # (Write your tickets according to the format:)
[//]: # ([Quest][Azuremyst Isle] Red Snapper - Very Tasty!)
[//]: # ([NPC] Magistrix Erona)
[//]: # ([Spell][Mage] Fireball)
[//]: # ([Npc][Drop] Ghostclaw Lynx)
[//]: # ([Web] Armory doesnt work)
[//]: # (To find server revision type `.server info` command in the game chat.)

**Description**: 
Warlock pet(Felguard) change its name to default "Felguard" after being re summoned. Had pet for less then 10min before named got reset.

**Current behaviour**:
Default pet name"Felguard" only on Felguard pet.

**Expected behaviour**: 
For pet(Felguard) to have unique a name.

**Server Revision**: 
3497

**Comment by Tereneckla** [comment]
Mine is keeping his name for multiple days already
