### ISSUE TITLE
[Quest] Pawn Captures Queen

### ISSUE THREAD

**Issue by The14me** [Atlantiss/NetherwingBugtracker#7269]
**Current behaviour**: Everything works fine, but once u use the potion and guards spawn, they never despawn. So if u use it, kite away  the queen and kill her, guards reset and next person who supposes to do the quest is cucked.
https://imgur.com/a/VFGuDL7

**Expected behaviour**:  They suppose to despawn after ''N'' time.
https://classic.wowhead.com/quest=4507/pawn-captures-queen

**Server Revision**: 
3497

**Comment by Godmatik** [comment]
Rev 4016 - still an issue
NPC 10040 needs a despawn time attached to it

**Comment by EtheriousNW** [comment]
fix is live
