### ISSUE TITLE
[Warlock][Spell] Pet doesn't despawn when changing spec.

### ISSUE THREAD

**Issue by tsuone** [Atlantiss/NetherwingBugtracker#7272]
[//]: # (Enclose links to things related to the bug using http://wowhead.com or any other TBC database.)
[//]: # (You can use screenshot ingame to visual the issue.)
[//]: # (Write your tickets according to the format:)
[//]: # ([Quest][Azuremyst Isle] Red Snapper - Very Tasty!)
[//]: # ([NPC] Magistrix Erona)
[//]: # ([Spell][Mage] Fireball)
[//]: # ([Npc][Drop] Ghostclaw Lynx)
[//]: # ([Web] Armory doesnt work)
[//]: # (To find server revision type `.server info` command in the game chat.)

**Description**: Warlock's pet issue.

**Current behaviour**: When changing spec pet doesn't despawn.

**Expected behaviour**: When warlock is changing spec, his current pet should despawn and recompensated with soul shard, if pet needs it to summon.

**Server Revision**: Current.

**Comment by Wolffenstein** [comment]
Fixed in rev 3499.
