### ISSUE TITLE
Hunter Feign Death bug

### ISSUE THREAD

**Issue by Jinglz** [Atlantiss/NetherwingBugtracker#7273]
**Description**: Hunter Feign Death bug

**Current behaviour**: Sometimes when you use Feign death it bugs out and is no longer useable unless you relog.

**Expected behaviour**: Well go on cooldown and work as intended again after the cooldown has finished, but it is grayed out as you can see here https://gyazo.com/abc608769da89a2d3fea605062c9c087

**Server Revision**: 
current

**Comment by Godmatik** [comment]
Fixed a while ago, closing
