### ISSUE TITLE
Black Qiraji Resonating Crystal mounting up doesn't get cancelled by movement

### ISSUE THREAD

**Issue by kelsul** [Atlantiss/NetherwingBugtracker#7274]
[//]: # (Enclose links to things related to the bug using http://wowhead.com or any other TBC database.)
[//]: # (You can use screenshot ingame to visual the issue.)
[//]: # (Write your tickets according to the format:)
[//]: # ([Quest][Azuremyst Isle] Red Snapper - Very Tasty!)
[//]: # ([NPC] Magistrix Erona)
[//]: # ([Spell][Mage] Fireball)
[//]: # ([Npc][Drop] Ghostclaw Lynx)
[//]: # ([Web] Armory doesnt work)
[//]: # (To find server revision type `.server info` command in the game chat.)

**Description**: Hi, the shop mount Black Qiraji Resonating Crystal doesn't cancel when moving. So, I can click the mount, start moving, and it will keep channeling and mount me up. 

**Current behaviour**: Black Qiraji Resonating Crystal doesn't cancel mounting up on moving.

**Expected behaviour**: Should stop me form mounting up if i move

**Server Revision**: 3497

**Comment by Wolffenstein** [comment]
Fixed in rev 3499.
