### ISSUE TITLE
Hunter ability "Eyes of the Beast" not functionning properly (cannot be used as intended as a result)

### ISSUE THREAD

**Issue by Pmt112** [Atlantiss/NetherwingBugtracker#7275]
[//]: # ([Spell][Hunter] Eyes of the Beast) https://classic.wowhead.com/spell=1002/eyes-of-the-beast#comments
**Description**: This spell allows the hunter to control his pet while losing control of the hunter who stays in place channeling the spell.

**Current behaviour**: Everything works except that while controlling the pet, the information about surrounding players is not received properly, causing the characters around to freeze and be mislocated.

**Expected behaviour**: Should be able to keep track of players (and mobs) around the controlled pet normally as you move the pet around for as long as the spell lasts, allowing also to attack them, or follow them, etc. I think it's a fun spell to use for roleplay, hope you can fix it. It seems that it's just the information stops being received properly while being in control of the pet. This spell can also have its uses to scout forward or attack enemies.

**Server Revision**: Karazhan

**Comment by Wolffenstein** [comment]
Fixed in revision 3501.

**Comment by Pmt112** [comment]
Server on revision 3509 : the spell doesn't work indeed, neither does Eagle Eyes spell
