### ISSUE TITLE
Gan'Arg Tinkerer Freeze the Game if hit by Arcane Explosion (Mage)

### ISSUE THREAD

**Issue by Sunaqt** [Atlantiss/NetherwingBugtracker#7276]
[//]: # ([NPC] Gan'arg Tinkerer - https://tbc-twinhead.twinstar.cz/?npc=17151)
[//]: # ([Spell][Mage] Arcane Explosion)
[//]: # 3497

**Description**: 
Gan'arg Tinkerer  in Nagrand (Forge Camp Fear and Forge Camp Hate) seems to Freeze the Game  for a few seconds which affects every Player near them  when they get hit by the Mage Spell Arcane Explosion 

**Server Revision**: 3497

**Comment by Tereneckla** [comment]
Smooth as butter when I arcane explosion them

**Comment by Drayo** [comment]
We also had serious frame-drops in Forge Camp Hate, though we did not find out why.
