### ISSUE TITLE
Wrong reputations awarded when changing faction

### ISSUE THREAD

**Issue by SilverArrow1** [Atlantiss/NetherwingBugtracker#7277]
I was an ORC and switched to NIGHT ELF, when i changed i got the wrong reputations, instead of getting the rep with darnassus as expected i got stormwind one, and now the mount is way expensiver than it should be. Help plz

**Comment by tsuone** [comment]
It isn't a bug. Orgrimmar reputation changes to Stormwind City reputation which is how it supposed to work. Same with mounts, if you had Orc Wolf mount, it would change to Horse and not Night Elf saber.
