### ISSUE TITLE
[Quest] The Missing Diplomat [Id: 1447]

### ISSUE THREAD

**Issue by Tereneckla** [Atlantiss/NetherwingBugtracker#7278]
[//]: # (Enclose links to things related to the bug using http://wowhead.com or any other TBC database.)
[//]: # (You can use screenshot ingame to visual the issue.)
[//]: # (Write your tickets according to the format:)
[//]: # ([Quest][Azuremyst Isle] Red Snapper - Very Tasty!)
[//]: # ([NPC] Magistrix Erona)
[//]: # ([Spell][Mage] Fireball)
[//]: # ([Npc][Drop] Ghostclaw Lynx)
[//]: # ([Web] Armory doesnt work)
[//]: # (To find server revision type `.server info` command in the game chat.)

**Description**: To complete the quest you have to defeat him after he turns attackable.

**Current behaviour**: If you mind control him he is friendly after it runs out and then never resets. Making this uncompletable for everyone.

**Expected behaviour**: He doesn't stay friendly after the mind control ran out.
(This issue also happens on quest 1249 (same name))

**Server Revision**: 3493

**Comment by Godmatik** [comment]
Duplicate #7251
