### ISSUE TITLE
Felhunter Quest Bugged

### ISSUE THREAD

**Issue by Jboogie1901** [Atlantiss/NetherwingBugtracker#7280]
[//]: # (Enclose links to things related to the bug using http://wowhead.com or any other TBC database.)
[//]: # (You can use screenshot ingame to visual the issue.)
[//]: # (Write your tickets according to the format:)
[//]: # ([Quest][Azuremyst Isle] Red Snapper - Very Tasty!)
[//]: # ([NPC] Magistrix Erona)
[//]: # ([Spell][Mage] Fireball)
[//]: # ([Npc][Drop] Ghostclaw Lynx)
[//]: # ([Web] Armory doesnt work)
[//]: # (To find server revision type `.server info` command in the game chat.)

**Description**: Felhunter Quest is bugged

**Current behaviour** The quest for felhunter on my warlock is no longer obtainable, can't be finished or failed. I was finishing the quest when i realized I had messed up a part in the quest where Menara Voidrender lays down a summoning circle so i figured if deleted the quest and restarted it I would be fine. Sadly now I cant accept the quest... It wont even show it. Could you please be so kind and enable felhunter on my character? Thank you.

Quest giver is Zevrost and the quest is called In Search of Menara Voidrender

Thank you!

**Comment by Jboogie1901** [comment]
The quest for felhunter on my warlock is no longer obtainable, can't be finished or failed. I was finishing the quest when i realized I had messed up a part in the quest where Menara Voidrender lays down a summoning circle so i figured if deleted the quest and restarted it I would be fine. Sadly now I cant accept the quest... It wont even show it.  Could you please be so kind and enable felhunter on my character? Thank you.

Quest giver is Zevrost and the quest is called In Search of Menara Voidrender

Thank you!

**Comment by Tereneckla** [comment]
https://classic.wowhead.com/quest=4737/in-search-of-menara-voidrender
This is a breadcrumbs quest that leads to the enchanted gold bloodrobe


https://classic.wowhead.com/quest=1795/the-binding
These are the felhunter quests

**Comment by Jboogie1901** [comment]
@Tereneckla ,

The quest I need to start all of this is Seeking Strahad given by Gan'rul Bloodeye and its not available

**Comment by Jboogie1901** [comment]
"If you fail, you can abandon this quest and accept it again straight away from Strahad Farsan. Your old Tome of the Cabal will be destroyed, but do not worry. You get a new Tome when you re-accept the quest."

I didn't fail it but there was no summoning circle so I abandon the quest to re-accept it but its not showing up.

**Comment by Tereneckla** [comment]
So, you started the quest "The Binding", last part of the chain for the felhunter.
https://youtu.be/EOt6uVMi5F4?t=360
This RP event did not create a summon circle where you could summon the felhunter.
So you abandoned the quest and after Strahad went back to his regular position he did not offer that quest for you again.

**Comment by Jboogie1901** [comment]
Yes exactly that =c
