### ISSUE TITLE
[Hunter][Spell] Eyes of the Beast

### ISSUE THREAD

**Issue by x-x-x-x-x-x-x-x-x-x-x-x** [Atlantiss/NetherwingBugtracker#7282]
1) Commands given during Eyes of the Beast are not being executed when the spell ends (example: Eyes > move the pet to a desired location > Stay ... the pet will continue to Follow after the spell, no matter what was commanded prior and during the spell)
2) The spell cannot be "refreshed" without interruption. https://youtu.be/YvYiRsCV9FM?t=77

**Server Revision**: 3497

**Comment by Wolffenstein** [comment]
2. Is not a bug, its something that was changed in one of the tbc patches and u need a macro to circumvent that.

**Comment by Wolffenstein** [comment]
Fixed in rev 3503.
