### ISSUE TITLE
[Quest][Nagrand]I Must Have Them! - wrong questitem drop chance

### ISSUE THREAD

**Issue by Argentru** [Atlantiss/NetherwingBugtracker#7283]
**Description**: 
Extremely low drop chance of quest item "Air Elemental Gas" https://www.wowhead.com/item=27807/air-elemental-gas for quest "I Must Have Them!" https://www.wowhead.com/quest=10109/i-must-have-them
Related NPC:
https://www.wowhead.com/npc=17158/dust-howler
https://www.wowhead.com/npc=17159/storm-rager
https://www.wowhead.com/npc=17160/living-cyclone

**Current behaviour**:
Like less than 5% drop chance.

**Expected behaviour**: 
Almost guaranteed drop accordingly to wowhead comments https://www.wowhead.com/item=27807/air-elemental-gas#comments People state there, that calculated database drop chance is completely wrong comparing to actual in-game situation when you are in this quest.
I leveled numerous characters during BC 15 years ago and I remember that it was very easy to acquire required quest items just killing nearby air elementals.

**Server Revision**: 
3497

**Comment by duzyizly** [comment]
HI, I get 3 items of 8 kills. Maybe I'm just lucky.

**Comment by Argentru** [comment]
> HI, I get 3 items of 8 kills. Maybe I'm just lucky.

Actually, after several hours I created a ticked I managed to get remaining 2 items in 4-5 kills. Dunno what to think.

**Comment by Godmatik** [comment]
Seemed fine to me.
