### ISSUE TITLE
Shore Strider level up animation when transformed to Zapped Shore Strider

### ISSUE THREAD

**Issue by Justfor49** [Atlantiss/NetherwingBugtracker#7284]
[//]: # (Enclose links to things related to the bug using http://wowhead.com or any other TBC database.)
[//]: # (You can use screenshot ingame to visual the issue.)
[//]: # (Write your tickets according to the format:)
[//]: # ([Quest][Azuremyst Isle] Red Snapper - Very Tasty!)
[//]: # ([NPC] Magistrix Erona)
[//]: # ([Spell][Mage] Fireball)
[//]: # ([Npc][Drop] Ghostclaw Lynx)
[//]: # ([Web] Armory doesnt work)
[//]: # (To find server revision type `.server info` command in the game chat.)

**Current behaviour**:

Shore Striders in Feralas occasionally play level up animation when transformed to Zapped Shore Striders for quest "Zapped Giants." Not sure if this also happens with the nearby named mobs "Wave Strider." 

![zap](https://user-images.githubusercontent.com/69169443/89222867-c3d31e80-d5a3-11ea-899a-56a66860e309.jpg)

**Expected behaviour**: 
Mob should not play level up animation when transformed. 

**Server Revision**: 
3497

**Comment by Tereneckla** [comment]
https://youtu.be/chO4UA2egZY?t=530

**Comment by Wolffenstein** [comment]
Fixed in rev 3503.

**Comment by Peglaa** [comment]
Happening again. Tried it on all kind of giants in Feralas, even [Land Walkers](https://tbc-twinhead.twinstar.cz/?npc=5357) and [Cliff Giants](https://tbc-twinhead.twinstar.cz/?npc=5358). Sometimes it works correctly but sometimes they shrink instantly and play levelup animation. I can't seem to reproduce it consistently, it seems random.

**Comment by Wolffenstein** [comment]
I only fixed the shore striders.

**Comment by Peglaa** [comment]
The remaining ones are:

[Wave Strider](https://tbc-twinhead.twinstar.cz/?npc=5361) - [Zapped Wave Strider](https://tbc-twinhead.twinstar.cz/?npc=14638)

[Cliff Gaint](https://tbc-twinhead.twinstar.cz/?npc=5358) - [Zapped Cliff Giant](https://tbc-twinhead.twinstar.cz/?npc=14640)

[Deep Strider](https://tbc-twinhead.twinstar.cz/?npc=5360) - [Zapped Deep Strider](https://tbc-twinhead.twinstar.cz/?npc=14639)

[Land Walker](https://tbc-twinhead.twinstar.cz/?npc=5357) - [Zapped Land Walker](https://tbc-twinhead.twinstar.cz/?npc=14604)

**Comment by Wolffenstein** [comment]
Fixed in rev 3523.
