### ISSUE TITLE
Rogue Black Drakes and Expeditionary Mountaineer aren't fighting eachother 

### ISSUE THREAD

**Issue by Justfor49** [Atlantiss/NetherwingBugtracker#7285]
[//]: # (Enclose links to things related to the bug using http://wowhead.com or any other TBC database.)
[//]: # (You can use screenshot ingame to visual the issue.)
[//]: # (Write your tickets according to the format:)
[//]: # ([Quest][Azuremyst Isle] Red Snapper - Very Tasty!)
[//]: # ([NPC] Magistrix Erona)
[//]: # ([Spell][Mage] Fireball)
[//]: # ([Npc][Drop] Ghostclaw Lynx)
[//]: # ([Web] Armory doesnt work)
[//]: # (To find server revision type `.server info` command in the game chat.)

**Current behaviour**:
Rogue Black Drakes and Expeditionary Mountaineers aren't fighting each other, just path around - probably aggro range is very small (need to be practically in each other to fight):

![fight](https://user-images.githubusercontent.com/69169443/89223327-99ce2c00-d5a4-11ea-9cae-0074187abce2.jpg)

**Expected behaviour**: 
They should be fighting each other:
https://wowwiki.fandom.com/wiki/Rogue_Black_Drake

"The Rogue Black Drake can be seen while flying between the Burning Steppes and Elwynn Forest. It battles Expeditionary Priests and Expeditionary Mountaineers."

**Server Revision**: 
3497

**Comment by Wolffenstein** [comment]
Fixed in rev 3503.
