### ISSUE TITLE
[Quest][Hillsbrad Foothills] Elixir of Agony

### ISSUE THREAD

**Issue by AleGlowa** [Atlantiss/NetherwingBugtracker#7287]
[//]: # (Enclose links to things related to the bug using http://wowhead.com or any other TBC database.)
[//]: # (You can use screenshot ingame to visual the issue.)
[//]: # (Write your tickets according to the format:)
[//]: # ([Quest][Azuremyst Isle] Red Snapper - Very Tasty!)
[//]: # ([NPC] Magistrix Erona)
[//]: # ([Spell][Mage] Fireball)
[//]: # ([Npc][Drop] Ghostclaw Lynx)
[//]: # ([Web] Armory doesnt work)
[//]: # (To find server revision type `.server info` command in the game chat.)

**Description**: 
The 4th stage of the quest "Elixir of Agony" doesn't work.

**Current behaviour**:
Keg of Shindigger Stout doesn't appear in the desired location on Karazhan realm.

**Expected behaviour**: 
[wowhead](https://classic.wowhead.com/quest=517/elixir-of-agony)

**Server Revision**:

**Comment by Tereneckla** [comment]
It has 3 different spawnlocations and does appear.
