### ISSUE TITLE
Alliance bench in the lava river atop Fire Plume Ridge

### ISSUE THREAD

**Issue by ghusergh** [Atlantiss/NetherwingBugtracker#7288]
![bug](https://user-images.githubusercontent.com/69173301/89233131-e6cff380-d5e0-11ea-80da-fb8358dd79b8.png)

**Comment by tsuone** [comment]
I guess that's a marker or trigger for some quest, it should be visible to players.
![image](https://user-images.githubusercontent.com/11255782/89235923-84322400-d5ef-11ea-98ed-942ecd7cadb4.png)

@Wolffenstein

**Comment by Tereneckla** [comment]
That's the forge for the Scholomance Key, I think.
Shouldn't be visible obviously.

**Comment by Wolffenstein** [comment]
Fixed in rev 3503.
