### ISSUE TITLE
[Mage][Pet] Freeze

### ISSUE THREAD

**Issue by tsuone** [Atlantiss/NetherwingBugtracker#7289]
[//]: # (Enclose links to things related to the bug using http://wowhead.com or any other TBC database.)
[//]: # (You can use screenshot ingame to visual the issue.)
[//]: # (Write your tickets according to the format:)
[//]: # ([Quest][Azuremyst Isle] Red Snapper - Very Tasty!)
[//]: # ([NPC] Magistrix Erona)
[//]: # ([Spell][Mage] Fireball)
[//]: # ([Npc][Drop] Ghostclaw Lynx)
[//]: # ([Web] Armory doesnt work)
[//]: # (To find server revision type `.server info` command in the game chat.)

**Description**: Mage Water Elemental's `Freeze` ability.

**Current behaviour**: You can't use the following macro to cast `Freeze` and `#showtooltip` doesn't display it:
```
#showtooltip
/cast Freeze
```

**Expected behaviour**: You should be able to use macro pasted above to cast Water Elemental's `Freeze` ability.

**Server Revision**: 3497

> **Note for all mages:** For the time when it isn't fixed, please use the following workaround macro to use the Freeze ability:
>```
>/click PetActionButton5
>```

**Comment by Wolffenstein** [comment]
Fixed in rev 3520.
