### ISSUE TITLE
[Spell][Warlock] Fear

### ISSUE THREAD

**Issue by Bulba75** [Atlantiss/NetherwingBugtracker#729]
[//]: # (Enclose links to things related to the bug using http://wowhead.com or any other TBC database.)
[//]: # (You can use screenshot ingame to visual the issue.)
[//]: # (Write your tickets according to the format:)
[//]: # ([Quest][Azuremyst Isle] Red Snapper - Very Tasty!)
[//]: # ([NPC] Magistrix Erona)
[//]: # ([Spell][Mage] Fireball)
[//]: # ([Npc][Drop] Ghostclaw Lynx)
[//]: # ([Web] Armory doesnt work)

**Description**: 
Fear currently breaks far too easily, even from DoT damage only. With only a single DoT on target fear is lucky to last three ticks. With full DoTs (Immo, Corr and Agony) Fear will rarely last over a second. In addition direct damage spells like Shadow Bolt seem to break it near 100% of the time. 

**Current behaviour**:
Fear currently breaks too easily from any source of damage. 

**Expected behaviour**: 
DoT damage should not break Fear so quickly. Direct high damage spells should break it often, but are not guaranteed too.

**Server Revision**: 
2070

**Comment by The14me** [comment]
Can u please add some retail proof of that? Thx!

**Comment by Dpthx** [comment]
this will need tons of evidence. and i mean not 3 sources, but at least 10+ sources.

**Comment by Jezofine** [comment]
As priest I've seen many times that enemies run full duration of Fear with 1 dot (shadow word pain). I don't know about actual damage threshold but at least it didn't break too easily for me.

**Comment by bloodwindz** [comment]
https://www.youtube.com/watch?v=8FtLzikcGGA

fear warr or lock should not break that easyly check how he hits the feared shaman few times and it dont break

**Comment by Lunasoll** [comment]
> https://www.youtube.com/watch?v=RaEVmuEryBU

@Developers, note the 2nd time he casted fear in the video. It lasted for 12 seconds with dots up before it was broken with a direct damage spell (Shadow Bolt). On NW at the moment, fear won't last even 3 secs with dots up. And it happens every single fear cast. It should happen that it can break faster with dots fast, but not as often.

**Comment by corkus1111** [comment]
Fear still breaking from very little damage and only dots, not actual hard casts. Please fix, the class is currently unplayable in PVP and more difficult to level than it should be.

**Comment by devo6969** [comment]
This is the most i could find about it and to be honest it seems that is working as intended from patch 2.1 they nerfed it to break easier and give it a "heartbeat" resist.

https://classic.wowhead.com/spell=5782/fear#comments
"Having played a Warlock, it most definately CAN break on damage and does so quite often.Fear can only last around 10 seconds in PvP anyways, not to mention there are quite a few ways to break it."

https://wowwiki.fandom.com/wiki/Patch_3.1.0
"The damage threshold for Fear, Psychic Scream, Hex, Intimidating Shout, and Turn Evil to break early has been significantly reduced." 

https://wowwiki.fandom.com/wiki/Patch_1.2.0
Players now have an increasing chance to break free of the effect, such that it is unlikely the effect will last more than 15 seconds.

https://wow.gamepedia.com/Fear
Fear has a damage limit. If the target takes damage equal to the limit, the Fear spell will break, regardless of the potential duration of the spell.

https://www.mmo-champion.com/threads/711283-The-History-of-Fear
Patch 2.1
Chance to break crowd control from damage: The increased chance for a spell to break from taking a critical strike has been removed. Instead, all targets over level 60 have a slightly larger chance to break out of crowd-controlling effects when they take damage. (Affliction (and Demo) nerf)
- In addition, fear and seduce both have "heartbeat" resists and can break at any time, whether damage has been applied or not.

**Comment by Lunasoll** [comment]
has it been fixed for Karazhan?

**Comment by Tereneckla** [comment]
They are definitely higher values than what was described before.
In my tests Fear lasted lasted 5-6 seconds on average on a fully dotted target.
And direct damage broke the fear 33-50% of the time.
