### ISSUE TITLE
[Quest][Body and Heart][Kharazhan] Lunaclaw doesn't move and can just kill outside melee range

### ISSUE THREAD

**Issue by bidaumm** [Atlantiss/NetherwingBugtracker#7291]
[Quest Name] : Body and Heart
[NPC] : Lunaclaw
[Location] : Darkshore x44/y45
**Description**: 
Lunaclaw during NE Druid bear form quest didn't move from its spot.
**Current behaviour**:
I could just out melee range it and it'd stay stuck not moving
**Expected behaviour**: 
mob should move into melee range
**Server Revision**:

**Comment by Godmatik** [comment]
Can not reproduce
