### ISSUE TITLE
[NPC] Wrong gossip text for Thamarian

### ISSUE THREAD

**Issue by Peglaa** [Atlantiss/NetherwingBugtracker#7292]
[//]: # (Enclose links to things related to the bug using http://wowhead.com or any other TBC database.)
[//]: # (You can use screenshot ingame to visual the issue.)
[//]: # (Write your tickets according to the format:)
[//]: # ([Quest][Azuremyst Isle] Red Snapper - Very Tasty!)
[//]: # ([NPC] Magistrix Erona)
[//]: # ([Spell][Mage] Fireball)
[//]: # ([Npc][Drop] Ghostclaw Lynx)
[//]: # ([Web] Armory doesnt work)
[//]: # (To find server revision type `.server info` command in the game chat.)

**Description**: [Thamarian](https://tbc-twinhead.twinstar.cz/?npc=12656) mentions that the ship on the southern dock will take you to Stormwind, instead of Menethil Harbor.

**Current behaviour**:
![thamarian](https://user-images.githubusercontent.com/15163719/89329083-9f07a580-d68e-11ea-97e7-8ccd59809e25.png)

**Expected behaviour**: 
Should probably replace "Stormwind Harbor" with "Menethil Harbor".

**Server Revision**: 3497

**Comment by Wolffenstein** [comment]
Fixed in rev 3503.

**Comment by schanzee** [comment]
This is not fixed or bugged again.
