### ISSUE TITLE
Grand Warlock Nethekurse

### ISSUE THREAD

**Issue by Godmatik** [Atlantiss/NetherwingBugtracker#7295]
When you wipe to him, he doesn't despawn and reset back to his normal position.

Also if you wipe to him in final phase when he is spinning, he will stay spinning when you pull him, making him unkillable.

**Comment by Tereneckla** [comment]
In my tests this only happens when he is spinning.
Stays at his position, resets to full hp, keeps spinning.

**Comment by Wolffenstein** [comment]
Fixed in rev 3503.
