### ISSUE TITLE
Evil Draws near quest

### ISSUE THREAD

**Issue by Vasquea** [Atlantiss/NetherwingBugtracker#7296]
[//]: # (Enclose links to things related to the bug using http://wowhead.com or any other TBC database.)
[//]: # (You can use screenshot ingame to visual the issue.)
[//]: # (Write your tickets according to the format:)
[//]: # ([Quest][Azuremyst Isle] Red Snapper - Very Tasty!)
[//]: # ([NPC] Magistrix Erona)
[//]: # ([Spell][Mage] Fireball)
[//]: # ([Npc][Drop] Ghostclaw Lynx)
[//]: # ([Web] Armory doesnt work)
[//]: # (To find server revision type `.server info` command in the game chat.)

**Description**: 
(https://www.wowhead.com/quest=10923/evil-draws-near)
doing this quest you need to farm 20 skulls to summ the boss which is a dragon that flys down, if someone else summons boss while it on the ground or flying it despawns and the new one also despawns
**Current behaviour**:
2nd one is allowed to be summed
**Expected behaviour**: 
it should either not desumm the boss or not allow someone to summ new one if one is present
**Server Revision**:

**Comment by Wolffenstein** [comment]
Fixed in rev 3503.
