### ISSUE TITLE
Fear and Fear Ward interaction

### ISSUE THREAD

**Issue by czarecoo** [Atlantiss/NetherwingBugtracker#7298]
[//]: # (Enclose links to things related to the bug using http://wowhead.com or any other TBC database.)
[//]: # (You can use screenshot ingame to visual the issue.)
[//]: # (Write your tickets according to the format:)
[//]: # ([Quest][Azuremyst Isle] Red Snapper - Very Tasty!)
[//]: # ([NPC] Magistrix Erona)
[//]: # ([Spell][Mage] Fireball)
[//]: # ([Npc][Drop] Ghostclaw Lynx)
[//]: # ([Web] Armory doesnt work)
[//]: # (To find server revision type `.server info` command in the game chat.)

**Description**: 
Some monsters suddenly stop using using their fear spells when player has Fear Ward on him OR Fear Ward does not expire after blocking fear from mobs.
**Current behaviour**:
Reproduction:
Find Crushridge Enforcer from Alterac Mountains or Skeletal Horror from Duskwood.
Aggro it.
After some time it will fear you. So far so good.
Now cast Fear Ward on yourself.
The monster will never fear you again and you will have Fear Ward for its whole duration.
After 3 min monster will start using fear again

**Expected behaviour**: 
Monsters should still use fear even when you are warded OR Fear Ward should expire after blocking fear from mobs, depending on which one is bugged.

**Server Revision**: 
3497

**Comment by Tereneckla** [comment]
They stop casting the fear altogether right now.
I guess that is because you register as immune in their AI

**Comment by Wolffenstein** [comment]
Fixed in rev 3503.
