### ISSUE TITLE
Pet gone after it died !

### ISSUE THREAD

**Issue by Tricklerxd** [Atlantiss/NetherwingBugtracker#7299]
[//]: # (Enclose links to things related to the bug using http://wowhead.com or any other TBC database.)
[//]: # (You can use screenshot ingame to visual the issue.)
[//]: # (Write your tickets according to the format:)
[//]: # ([Quest][Azuremyst Isle] Red Snapper - Very Tasty!)
[//]: # ([NPC] Magistrix Erona)
[//]: # ([Spell][Mage] Fireball)
[//]: # ([Npc][Drop] Ghostclaw Lynx)
[//]: # ([Web] Armory doesnt work)
[//]: # (To find server revision type `.server info` command in the game chat.)

**Description**: 
Hey, my Pet died in SM-Bib and for some reason i'm not able to rez it. It was full on happiness. No clue but i hope you can fix it !
**Current behaviour**:

**Expected behaviour**: 

**Server Revision**:

**Comment by Tereneckla** [comment]
Call it-> A corpse appears next to you->rez it
