### ISSUE TITLE
[Springpaw Stalker] Springpaw Pelt

### ISSUE THREAD

**Issue by DoctorRaymos** [Atlantiss/NetherwingBugtracker#73]
Reported by Discord user Kes#1233

Springpaw Stalker's drop rate for Springpaw Pelt (quest item for Pelt Collection) seems low. Farmed 8 in a row, with no drop. Current research indicates around a 44% drop rate for these, but still haven't been able to find an accurate drop rate from archives. Maybe take a look into this early quest drop, players tending to skip it because CBA.

**Comment by Wolffenstein** [comment]
Fixed in rev 2022.
