### ISSUE TITLE
[Spell / Attack][Mage][Frostbolt into Wand]

### ISSUE THREAD

**Issue by Northlol** [Atlantiss/NetherwingBugtracker#730]
Description: Frostbolting immediately prior to wanding causes the wand shoot to delay several seconds.

Current behaviour: Using shoot after frostbolt will delay the wand attack.

Expected behaviour: Shoot should fire after the wand's attack speed and not be delayed because of frostbolt

Server Revision: 2072

Proof:
https://clips.twitch.tv/TenderGorgeousDiamondChocolateRain
https://clips.twitch.tv/ShortEndearingMarrowPlanking
https://clips.twitch.tv/WiseVictoriousLobsterShadyLulu

EDIT: Using Greater Magic Wand https://db.excalibur.ws/?item=11288

**Comment by Easyfraggy** [comment]
This looks proper, it should 100% reset your swingtimer (wand timer) when you finish cast.

**Comment by Northlol** [comment]
It's about 3 times the wand swingtimer - Wand in 1.8 speed and it takes around 5 seconds to have the wand go through- it isn't a reset, it's a delay, look at the videos.

**Comment by Easyfraggy** [comment]
This is working properly.

**Comment by aresbrutus** [comment]
OP requesting this to be re-opened so he can do more research + post any updates here.

**Comment by Northlol** [comment]
Okay so here are two new clips to demonstrate the bug

https://clips.twitch.tv/OriginalSmoggyBarracudaBudStar

In this first clip, like before, there is a significant delay after I frostbolt and wand afterwards- it is actually faster to walk away and wand after it resets whatever funk its in.

https://clips.twitch.tv/CrypticVainStrawberryBudStar

This second clip is the reason i INSIST the mechanic is bugged- in this clip my wand goes off immediately after I frostbolt. Either A. The extremely slow post cast wand is correct, or this post cast wanding is correct- both occur often.

The reason I believe the delay is incorrect is in part because walking away will result in a faster wand cast, but at the end of the day one or the other, the delay or lack of delay should be consistent in post cast wands.

**Comment by Northlol** [comment]
https://clips.twitch.tv/TentativePlainChipmunkCurseLit

I timed it, wand cast starts at 16.95~ seconds, ends at 19.45~ seconds, or 2.5 seconds for a 1.8 speed wand

**Comment by Kantrul** [comment]
The same occurs with other spells such as Fireball, Ice Lance, Arcane Explosion, Scorch, Flamestrike and Blizzard.

**Comment by Xyter** [comment]
Wand delay is absolutely off after spells. In this video the first and last mob are opened with wand to see how fast it normally fires. The two mobs in between are wanded after a cast and it can clearly be seen that the delay to fire is about 2x as long. This is with a lesser magic wand 1.50 delay.

Crap video quality, but you can see the issue nonetheless.
https://www.dropbox.com/s/h3y9bxwgu7m4hoz/Wand%20delay%20is%20off.mp4?dl=0

**Comment by Kantrul** [comment]
Yeah, its a known issue @aresbrutus fix pls 👍

**Comment by wtRCH** [comment]
b

**Comment by devo6969** [comment]
PTR - https://www.youtube.com/watch?v=o8EXfGmsYxE
Classic - https://www.youtube.com/watch?v=rOUh9KYLlI4
Warmane - https://www.youtube.com/watch?v=LmlayhJNA0U 
Endless - https://www.youtube.com/watch?v=UBOCunfHL5k

For the most blizzlike experience it appears classic has included this wand delay. "Shooting a wand is a separate thing, it's not akin to auto-attack or auto-shot for melee classes or hunters, so as such you cannot do it at the same time as casting spells."
https://www.mmo-champion.com/threads/964962-cast-spell-and-shoot-wand-at-same-time

Though I will say it is interesting that when a spell resists the wand delay becomes instant on the PTR
