### ISSUE TITLE
Mail

### ISSUE THREAD

**Issue by x-x-x-x-x-x-x-x-x-x-x-x** [Atlantiss/NetherwingBugtracker#7300]
Sending items via mail doesnt work sometimes. 'Mail sent.' msg appears, but the items remain in the bags
rev. 3497

**Comment by Tereneckla** [comment]
Do you have any mail addons that might cause it. Sending lots of mail and never had that happen.

**Comment by x-x-x-x-x-x-x-x-x-x-x-x** [comment]
Nope, no addons. It actually happened multiple times in the past few days, no idea why. Relog doesn't fix it either

**Comment by The14me** [comment]
delete cache or re-check the names.Its UI issue.

**Comment by x-x-x-x-x-x-x-x-x-x-x-x** [comment]
That's not it, @The14me . Still cant send items btw. Maybe there's something wrong with my character?

**Comment by danbopes** [comment]
This is a player issue. Open a GM ticket, and let them know what the issue is, and they can assist.
