### ISSUE TITLE
Eternium Ore Drop Rate too high

### ISSUE THREAD

**Issue by Dredddd** [Atlantiss/NetherwingBugtracker#7301]
Hi,
i am finding tons of Eternium Ore in Deposites that should only have 1,2% drop chance (Fel iron) and 2% for Adamantium Deposites.
My average Rates are at least 5-10 Times higher. I asked around and others in my guild say the same. Its totaly not fun.
Is this intended?
Please fix it. Its already not fun to have so many Deposites everywhere. Having the drop rates so high destroyes the whole reason to Mine at all.
Its better to buy it for nothing on th AH in that Case. Thinking about how this will go in a view Month...

**Comment by Dredddd** [comment]
Its not invalid! The amount of ore deopsits is already increased. Its not ok to increase the drop chance too. its 100% not correct.
Maybe its not 20% instead of 2% but it must be at least 10%. I have 10 Eternium ore in one day. lets say its 50/50 Fel iron and adamantium and its averages to 1.5% would be 1500 ore or 750 bars. thats almost 40 stacks. NEVER i have at best 8. Not at all Blizz like Server! Sorry for all the people that took mining. At least gems are not changed.

**Comment by Tereneckla** [comment]
![image](https://user-images.githubusercontent.com/50233983/89567188-8a0f4b80-d821-11ea-9ab2-19880b5617b5.png)
![image](https://user-images.githubusercontent.com/50233983/89567201-909dc300-d821-11ea-8294-59859fc89242.png)
![image](https://user-images.githubusercontent.com/50233983/89567231-9a272b00-d821-11ea-9842-8e40b2269ef1.png)

These are my droprates from many hours of mining on NW. They haven't been changed.

On the second point, spawnrate of nodes has been reduced already.
