### ISSUE TITLE
[Item] Rough Bronze Shoulders have the wrong stats

### ISSUE THREAD

**Issue by Tereneckla** [Atlantiss/NetherwingBugtracker#7302]
[//]: # (Enclose links to things related to the bug using http://wowhead.com or any other TBC database.)
[//]: # (You can use screenshot ingame to visual the issue.)
[//]: # (Write your tickets according to the format:)
[//]: # ([Quest][Azuremyst Isle] Red Snapper - Very Tasty!)
[//]: # ([NPC] Magistrix Erona)
[//]: # ([Spell][Mage] Fireball)
[//]: # ([Npc][Drop] Ghostclaw Lynx)
[//]: # ([Web] Armory doesnt work)
[//]: # (To find server revision type `.server info` command in the game chat.)

**Description**: https://www.wowhead.com/item=3480/rough-bronze-shoulders#english-comments
![image](https://user-images.githubusercontent.com/50233983/89443321-6a5c2280-d750-11ea-95c0-eda0ad218b5b.png)

**Current behaviour**: 
![image](https://user-images.githubusercontent.com/50233983/89443351-72b45d80-d750-11ea-956e-4ee1e49876fa.png)

**Expected behaviour**:
![image](https://user-images.githubusercontent.com/50233983/89443367-7a740200-d750-11ea-849c-6111e6b93e02.png)

**Server Revision**: 3497

**Comment by Wolffenstein** [comment]
Fixed in rev 3503.
