### ISSUE TITLE
Priest Talent Bug:  Force of Will

### ISSUE THREAD

**Issue by smitepriest** [Atlantiss/NetherwingBugtracker#7303]
![ScreenShot_080520_142616](https://user-images.githubusercontent.com/69261443/89449932-c8c0db00-d727-11ea-920d-f1d784ac692c.jpeg)
![ScreenShot_080520_142621](https://user-images.githubusercontent.com/69261443/89449935-c9597180-d727-11ea-8ece-382a9bdc5589.jpeg)
![ScreenShot_080520_142624](https://user-images.githubusercontent.com/69261443/89449937-c9f20800-d727-11ea-89cb-40bf6ff0a5c3.jpeg)
![ScreenShot_080520_142627](https://user-images.githubusercontent.com/69261443/89449941-ca8a9e80-d727-11ea-80d8-5d803bb69bbf.jpeg)
![ScreenShot_080520_142629](https://user-images.githubusercontent.com/69261443/89449946-cb233500-d727-11ea-9f77-bdb11406631e.jpeg)
![ScreenShot_080520_142631](https://user-images.githubusercontent.com/69261443/89449951-cbbbcb80-d727-11ea-9c1a-d987e0c9b9af.jpeg)

[//]: # (Enclose links to things related to the bug using http://wowhead.com or any other TBC database.)
[//]: # (You can use screenshot ingame to visual the issue.)
[//]: # (Write your tickets according to the format:)
[//]: # ([Quest][Azuremyst Isle] Red Snapper - Very Tasty!)
[//]: # ([NPC] Magistrix Erona)
[//]: # ([Spell][Mage] Fireball)
[//]: # ([Npc][Drop] Ghostclaw Lynx)
[//]: # ([Web] Armory doesnt work)
[//]: # (To find server revision type `.server info` command in the game chat.)

**Description**:  Priest Talent Force of Will is bugged

**Current behaviour**: No matter how many points you put into Force of Will the crit % and sp increase does not change.

**Expected behaviour**:  Should increase spell crit by 5% as well as 5% more spell damage

**Server Revision**: Make it give 5% spell crit and 5% more spell damage

**Comment by Tereneckla** [comment]
It increases the damage your spells deal, not the spelldamage stat.
The crit also is only for offensive spells, so that doesn't show in the sheet.
