### ISSUE TITLE
The Quillfang Skitterer has a wildly incorrect ability.

### ISSUE THREAD

**Issue by Captchacard** [Atlantiss/NetherwingBugtracker#7304]
**Description**: 

The Quillfang Skitterer in the Hellfire Peninsula currently has the "Gore" ability. Gore is an ability that's supposed to be restricted ONLY to boars. 

**Expected behaviour**: 

All Ravagers should have the Ravage ability.

https://www.wowhead.com/pet=31/ravager#abilities

https://wowwiki.fandom.com/wiki/Gore

**Comment by Captchacard** [comment]
To add to this, the Thornfang Venomspitter also does not have the Ravage ability. It only comes with Bite for some reason. Are Ravagers broken entirely? Where is the Ravage ability? What is the point of introducing this family of pets without their signature ability?

**Comment by raethkcj** [comment]
TBC didn't have signature abilities yet. Ravagers learn Gore, Bite, and Dash in TBC.
