### ISSUE TITLE
No combat log output on a character

### ISSUE THREAD

**Issue by VirtualReign** [Atlantiss/NetherwingBugtracker#7306]
One of my characters (Kharazan: Shock) has an issue where the combat log will be completely inactive for the a whole session. Randomly it will start working for a bit and then stop again. Game damage (floating text over enemies) is displayed fine, but the log just remains empty.

I've also noticed an issue on other characters where the combat log will not work for the duration of a fight, but never for a whole session.

**Comment by Drayo** [comment]
It's a 2.4.3 client bug. 

https://www.wowinterface.com/downloads/info16001-CombatLogFix.html

This helps, there are a few different ones out there, they all pretty much do the same though.

**Comment by VirtualReign** [comment]
Thanks! I'll try that out.
