### ISSUE TITLE
Showdown BEM quest

### ISSUE THREAD

**Issue by thedonald420** [Atlantiss/NetherwingBugtracker#7307]
[//]: # https://tbcdb.com/?quest=10742
[//]: # 
[//]: # (Write your tickets according to the format:)
[//]: # ([Quest][Blade's Edge Mountain] Showdown)
[//]: # 
[//]: # (
[//]: # (
[//]: # (
[//]: # (

**Description**: 
Using the Horn to summon Rexxar and fight Goc does nothing
**Current behaviour**:
Horn doesn't summon Rexxar
**Expected behaviour**: 
Horn should summon Rexxar
**Server Revision**: 
Karazhan

**Comment by Tereneckla** [comment]
Duplicate of #4840
