### ISSUE TITLE
[Spell][Priest] You have to buy Prayer of Spirit every time you respec

### ISSUE THREAD

**Issue by KurtySuit** [Atlantiss/NetherwingBugtracker#7312]
Title.

https://i.imgur.com/xLN2AWU.png proof that i have it before the respec, but have to buy it again

**Comment by Tereneckla** [comment]
also see #5646

**Comment by Tereneckla** [comment]
also see #5646

**Comment by Wolffenstein** [comment]
Fixed in rev 3533.
