### ISSUE TITLE
[Spell][Hunter] Raptor Strike

### ISSUE THREAD

**Issue by x-x-x-x-x-x-x-x-x-x-x-x** [Atlantiss/NetherwingBugtracker#7313]
When queued, prevents autoshot from firing ( **Auto Attack/Auto Shot** checked in Interface>Combat). From what I've seen in old tbc videos, it's temporarily turned off while casting autoshot, then turned back on. Special shots seemed to turn it off permanently, not sure.
rev. 3504

**Comment by Godmatik** [comment]
Was fixed last year, closing
