### ISSUE TITLE
Guild Bank withdrawls shows as Unknown

### ISSUE THREAD

**Issue by Crza96** [Atlantiss/NetherwingBugtracker#7314]
**Description**: 
All guild bank withdrawls are showing up as 'Unknown withdrew ____'.  Withdrawls are happening by existing characters.  Deposits remain unaffected.

**Current behaviour**:
Guild Bank Log is showing Unknown withdrew ____ 
**Expected behaviour**: 
Guild Bank Log tracks what people deposit and withdraw.
**Server Revision**: 
Karazhan Live

**Comment by Crza96** [comment]
Additional details - happening to the <Storm Breaker> guild on horde side.  Screenshot attached.  All Unknown withdraws are active characters in guild.
![image](https://user-images.githubusercontent.com/69319758/89585694-28d08380-d7f3-11ea-976d-a12a78887335.png)

**Comment by danbopes** [comment]
The character will be marked as Unknown if the character has been deleted afterwards. Can you message danbopes#0001 on discord with your guild name, and I can look into this more.
