### ISSUE TITLE
[Hunter][Aimed Shot][Auto Shot] The first Auto Shot after an Aimed Shot does not benefit from haste

### ISSUE THREAD

**Issue by raethkcj** [Atlantiss/NetherwingBugtracker#7315]
**Description**: 
Sometimes Aimed Shot resets the auto shot swing timer, sometimes it does not. (#3781).
When it works correctly and resets the swing timer, the swing timer of the first shot does not benefit from any haste effects, and instead uses the ranged weapon's base attack speed. This only applies to the first auto shot. All other auto shots appear to be correctly hasted.

**Current behaviour**:
Listening for UNIT_SPELLCAST_SUCCEEDED, you can see that the time between the completion of Aimed Shot and the next Auto Shot is ~2.7 seconds, even though my character's ranged attack speed is 2.01 with only a quiver and the BM talent.
![image](https://user-images.githubusercontent.com/7716908/89566358-ae4d3700-d7e5-11ea-967d-aa92789e33d3.png)

**Expected behaviour**: 
The first Auto Shot after an Aimed shot uses haste calculations as usual.

**Server Revision**: 
3504

**Comment by Godmatik** [comment]
Aimed shot in general needs rework as stated in the other thread, it is completely broken. Will close this and keep info in other thread.
