### ISSUE TITLE
[core][conditions] Unkor the Ruthless doesn't turn friendly if his aggro is on a pet

### ISSUE THREAD

**Issue by raethkcj** [Atlantiss/NetherwingBugtracker#7319]
**Description**: 

**Current behaviour**:
Fights until death if his aggro target is a player's pet

**Expected behaviour**: 
Turns friendly when fighting a pet whose owner is on the quest

**Server Revision**: 
3504

**Comment by Evolvee** [comment]
its the same core shit that was supposed to be fixed years ago (when npc says $c or $r, it has to target the owner of the pet instead)... same for all quest conditions obviously
