### ISSUE TITLE
[Desolace][Quest][Event]Gizelton Caravan 

### ISSUE THREAD

**Issue by Knoox** [Atlantiss/NetherwingBugtracker#732]
**This is part one, Gizelton Caravan. Recorded the yell @ 06:54, and he departed @ 06:59**: 

**Server Revision 2072**: 
![wowscrnshot_092718_065606](https://user-images.githubusercontent.com/18479169/46124583-562a6e80-c225-11e8-802d-c60937911f88.jpg)
![wowscrnshot_092718_070559](https://user-images.githubusercontent.com/18479169/46124585-59255f00-c225-11e8-971d-986b68189abd.jpg)

**Comment by tcberk12** [comment]
https://www.wowhead.com/quest=5821/bodyguard-for-hire

Comment from February 2008:
>This is the first of two quests on the caravan trade route between Kormek's Hut and the Gelkis Village. It is also the easier of the two. After returning to Kormek's Hut, the caravan sets up shop and rests for 10 minutes. Then it departs headed east along the road and stops just north of the Kolkar Village. **At this point the quest becomes available for only 4 minutes.** If it is not recieved within that period, the caravan continues south along the road and then west straight to the Gelkis Village. You have to then wait for the caravan to complete it's circut before you can pick up the quest (which takes approx. 40-60 minutes! depending on the quests being picked up or not along the way) 

Looks like 4 minutes to me.

**Comment by Evolvee** [comment]
so whats wrong/what needs to be done exactly?

**Comment by Easyfraggy** [comment]
I think the report is invalid, he said that they only stayed for 4 minutes, and berk provided info that they should only stay for 4 minutes. So yeah.
