### ISSUE TITLE
AH and enchanted items

### ISSUE THREAD

**Issue by czarecoo** [Atlantiss/NetherwingBugtracker#7320]
[//]: # (Enclose links to things related to the bug using http://wowhead.com or any other TBC database.)
[//]: # (You can use screenshot ingame to visual the issue.)
[//]: # (Write your tickets according to the format:)
[//]: # ([Quest][Azuremyst Isle] Red Snapper - Very Tasty!)
[//]: # ([NPC] Magistrix Erona)
[//]: # ([Spell][Mage] Fireball)
[//]: # ([Npc][Drop] Ghostclaw Lynx)
[//]: # ([Web] Armory doesnt work)
[//]: # (To find server revision type `.server info` command in the game chat.)

**Description**: 
Enchanted items look like normal items on AH.
**Current behaviour**:
Reproduction:
Get some low level bracers. (Blacksmithing: Patterned Bronze Bracers) 
Enchant them with +3 stamina. (Enchanting: Enchant Bracers - Lesser Stamina)
Place them on AH.
When you hover over the items, +3 stam is not shown.
Cancel auction.
See mailbox.
The item looks correctly now.

**Expected behaviour**: 
You can see that the item is enchanted while browsing AH.
**Server Revision**: 
3504

I checked without addons and I still cannot see enchants.

**Comment by Wolffenstein** [comment]
Fixed in rev 3511.
