### ISSUE TITLE
[NPC][Quest] Small text typo during escort in Hints of a New Plague?

### ISSUE THREAD

**Issue by Peglaa** [Atlantiss/NetherwingBugtracker#7321]
[//]: # (Enclose links to things related to the bug using http://wowhead.com or any other TBC database.)
[//]: # (You can use screenshot ingame to visual the issue.)
[//]: # (Write your tickets according to the format:)
[//]: # ([Quest][Azuremyst Isle] Red Snapper - Very Tasty!)
[//]: # ([NPC] Magistrix Erona)
[//]: # ([Spell][Mage] Fireball)
[//]: # ([Npc][Drop] Ghostclaw Lynx)
[//]: # ([Web] Armory doesnt work)
[//]: # (To find server revision type `.server info` command in the game chat.)

**Description**: During the escort quest [Hints of a New Plague?](https://classic.wowhead.com/quest=660/hints-of-a-new-plague), the NPC [Kinelory](https://classic.wowhead.com/npc=2713/kinelory) has a small typo in one of her texts.
![kinelory](https://user-images.githubusercontent.com/15163719/89635268-0304b680-d8a7-11ea-95b0-aba99a3e6b1a.png)

The text contains the word "quick" 2 times. Should only be 1 time of course.

**Current behaviour**:

**Expected behaviour**: 

**Server Revision**: 3504

**Comment by Tereneckla** [comment]
Kinelory says: Okay, let's get out of here quick quick! Try and keep up. I'm going to make a break for it. 

https://wowwiki.fandom.com/wiki/Quest:Hints_of_a_New_Plague%3F_(4)

This got 2 quick aswell.

**Comment by Peglaa** [comment]
Yeah even blizz texts tend to have typos in them.
