### ISSUE TITLE
[npc] [drop] Oronu the Elder

### ISSUE THREAD

**Issue by knasen88** [Atlantiss/NetherwingBugtracker#7322]
[//]: # (Enclose links to things related to the bug using http://wowhead.com or any other TBC database.)
[//]: # (You can use screenshot ingame to visual the issue.)
[//]: # (Write your tickets according to the format:)
[//]: # ([Quest][Azuremyst Isle] Red Snapper - Very Tasty!)
[//]: # ([NPC] Magistrix Erona)
[//]: # ([Spell][Mage] Fireball)
[//]: # ([Npc][Drop] Ghostclaw Lynx)
[//]: # ([Web] Armory doesnt work)
[//]: # (To find server revision type `.server info` command in the game chat.)

**Description**: 
Oronu the elder doesn't have 100% drop rate on his quest item? unheard of a kill x guy for y not having 100%
quest and npc same name. not in a raid
**Current behaviour**:
did not drop the item
https://i.imgur.com/aBwW4dt.jpg
**Expected behaviour**: 
100% drop
**Server Revision**: 
3504

**Comment by Tereneckla** [comment]
https://www.wowhead.com/quest=10571/oronu-the-elder#comments

![image](https://user-images.githubusercontent.com/50233983/89637673-d5217100-d8aa-11ea-9170-7836ccbc6bc3.png)

Yes, weird
