### ISSUE TITLE
Taking damage on elevators

### ISSUE THREAD

**Issue by EboneXx** [Atlantiss/NetherwingBugtracker#7324]
**Description**: I was in undercity jumping on the elevator and i was constantly receiving fall damage, that happened too in gnomeregan elevators but i though it was just a thing of that specific elevator
**Server Revision**: 3504
![image](https://user-images.githubusercontent.com/69278794/89650063-2bd17f80-d898-11ea-969f-8cedce1a1bbf.png)

**Comment by Tereneckla** [comment]
You jump, elevator moves down, you land further down than where you jumped from = fall damage

**Comment by EboneXx** [comment]
Yea but i think isnt supposed to happen, on classic at least it doesnt
happens, since it works like when you jump in a zepelin, you are stick to
the floor until you move out of it
