### ISSUE TITLE
lvl 70 enchants on low lvl pieces

### ISSUE THREAD

**Issue by EboneXx** [Atlantiss/NetherwingBugtracker#7325]
**Description**: i got lvl 31 bracers enchanted with Brawl, when the enchant says than isnt available for pieces lower than lvl 35

**Current behaviour**:Low lvl items able to get high lvl enchants

**Expected behaviour**: Not being able to use high lvl enchants on low lvl items

**Server Revision**: 3504

**Comment by EboneXx** [comment]
![image](https://user-images.githubusercontent.com/69278794/89650451-d5b10c00-d898-11ea-8aaa-0193e90f5dac.png)

**Comment by Tereneckla** [comment]
Item level 36

https://classic.wowhead.com/item=10333/scarlet-wristguards
