### ISSUE TITLE
1st AA after Charge/Intercept connects too early

### ISSUE THREAD

**Issue by Ph1Lx** [Atlantiss/NetherwingBugtracker#7327]
When using Charge or Intercept as a Warrior, the first Auto Attack connects with the target, before the warrior even reaches the target. The problem here is, if warriors want to swap stance mid charge (while still in the cast animation and not in aarange) they lose the rage from the first AA because it already counts as connected before connecting with the target.

**Comment by Wolffenstein** [comment]
This should be fixed now.
