### ISSUE TITLE
[Item] Black Qiraji Resonating Crystal dismount bug

### ISSUE THREAD

**Issue by kelsul** [Atlantiss/NetherwingBugtracker#7328]
[//]: # (Enclose links to things related to the bug using http://wowhead.com or any other TBC database.)
[//]: # (You can use screenshot ingame to visual the issue.)
[//]: # (Write your tickets according to the format:)
[//]: # ([Quest][Azuremyst Isle] Red Snapper - Very Tasty!)
[//]: # ([NPC] Magistrix Erona)
[//]: # ([Spell][Mage] Fireball)
[//]: # ([Npc][Drop] Ghostclaw Lynx)
[//]: # ([Web] Armory doesnt work)
[//]: # (To find server revision type `.server info` command in the game chat.)

**Description**: If you click on the Black Qiraji Resonating Crystal while already mounted on it, it doesnt dismount you, but instead channels the mount again, then dismounts you but allows you to run at 100% speed.

**Current behaviour**: Black Qiraji Resonating Crystal doesn't dismount when clicked, channels it again and gives you 100% speed while appearing dismounted. [https://gfycat.com/anotherveneratedguernseycow](url)

**Expected behaviour**: Clicking it should dismount you if youre already mounted. 

**Server Revision**: 3504

**Comment by Wolffenstein** [comment]
Can you retry after deleting cache?

**Comment by kelsul** [comment]
ok that fixed it
