### ISSUE TITLE
Fear causes player to blink around and run too fast

### ISSUE THREAD

**Issue by Ph1Lx** [Atlantiss/NetherwingBugtracker#7329]
Fear from players (only noticed it for priest fear but might also be for wls) causes the feared players to run around too fast and sometimes teleport (short distances) back and forth aswell.

**Comment by x-x-x-x-x-x-x-x-x-x-x-x** [comment]
Not sure what you mean by "too fast", but feared players should run faster than usual.

**Comment by Ph1Lx** [comment]
Yes but in the open world they occationally run faster than they should and even blink around.

**Comment by knasen88** [comment]
yep, usually at the end of the effect you teleport some random distance.
