### ISSUE TITLE
[Spell][Hunter] Feign Death

### ISSUE THREAD

**Issue by mbzz88** [Atlantiss/NetherwingBugtracker#733]
**Description**:  Auto Shot does not cancel Feign death

**Current behaviour**: FD is not cancelled, player remains in FD
https://youtu.be/PPG-cW-m5FA

**Expected behaviour**: Auto Shot causes player to stand up/cancel FD

**Comment by wtRCH** [comment]
Invalid

**Comment by Easyfraggy** [comment]
I don't think this is invalid? Either way need proof from retail.

**Comment by mbzz88** [comment]
Not sure about video evidence, but from http://wowwiki.wikia.com/wiki/Feign_Death,
"Moving or performing any action while feigning death will cancel the spell.".
Instant cast spells are correctly cancelling FD on Netherwing, it's just auto shot that doesn't. You have never been able to shoot arrows out of your "dead" body haha

**Comment by Wolffenstein** [comment]
Should be fixed
