### ISSUE TITLE
Spitelash Nagas in Azshara dont give xp

### ISSUE THREAD

**Issue by Furioko** [Atlantiss/NetherwingBugtracker#7330]
[//]: # (Enclose links to things related to the bug using http://wowhead.com or any other TBC database.)
[//]: # (You can use screenshot ingame to visual the issue.)
[//]: # (Write your tickets according to the format:)
[//]: # ([Quest][Azuremyst Isle] Red Snapper - Very Tasty!)
[//]: # ([NPC] Magistrix Erona)
[//]: # ([Spell][Mage] Fireball)
[//]: # ([Npc][Drop] Ghostclaw Lynx)
[//]: # ([Web] Armory doesnt work)
[//]: # (To find server revision type `.server info` command in the game chat.)

**Description**:  #[Npc] Spitelash Myrmidon) https://vanilla-twinhead.twinstar.cz/?npc=6196

**Current behaviour**: When you kill them they reward you no xp. Spllcasters however does.

**Expected behaviour**: Kill xp should be granted upon kill. for myrmidons.

**Server Revision**: 3504

**Comment by Wolffenstein** [comment]
Fixed in rev 3511.
