### ISSUE TITLE
Warlock - Demon disappears while mounted

### ISSUE THREAD

**Issue by Gamemechanicwow** [Atlantiss/NetherwingBugtracker#7332]
[//]: # (Enclose links to things related to the bug using http://wowhead.com or any other TBC database.)
[//]: # (You can use screenshot ingame to visual the issue.)
[//]: # (Write your tickets according to the format:)
[//]: # ([Quest][Azuremyst Isle] Red Snapper - Very Tasty!)
[//]: # ([NPC] Magistrix Erona)
[//]: # ([Spell][Mage] Fireball)
[//]: # ([Npc][Drop] Ghostclaw Lynx)
[//]: # ([Web] Armory doesnt work)
[//]: # (To find server revision type `.server info` command in the game chat.)

**Description**: 
Having a pet out - in my case a felguard. I mount up and sometimes when i dismount, my demon is gone. I have lost at least 5 felguards during the last 1-2 hours. It seems like it happens when if i mount up shortly after combat. Just mounting/dismounting in a city seems fine.

I suspect the fix to https://github.com/Atlantiss/NetherwingBugtracker/issues/7220 is causing the issue.

**Current behaviour**:

**Expected behaviour**: 

**Server Revision**:

**Comment by Gamemechanicwow** [comment]
I have done some testing and can reproduce it.

**Comment by Tereneckla** [comment]
Then tell us the steps to reproduce or make a clear video.

**Comment by Silbotronic** [comment]
Potential reproduce: dismount while on a slope, might have something to do with the terrain.

Also, when resummoning, the pet retains all of its previous buffs so the game assumes it never disappeared in the first place. The pet can also disappear when hearthing and joining a battleground.

**Comment by Godmatik** [comment]
Was fixed a while ago
