### ISSUE TITLE
Twinspire Graveyard does not work

### ISSUE THREAD

**Issue by Godmatik** [Atlantiss/NetherwingBugtracker#7333]
If your faction controls the graveyard, your spirit should be sent there when you die in any coilfang dungeon. As Alliance, it still sends us to the GY near Telredor.

**Comment by Wolffenstein** [comment]
Can you tell me in which dungeon you died? I tested the Graveyard a few months back and it worked fine.

**Comment by Godmatik** [comment]
Underbog

**Comment by Tereneckla** [comment]
Deaths in the dungeons always brought me to the alliance graveyard instead of Twinspire.

**Comment by Wolffenstein** [comment]
Fixed in rev 3545.
