### ISSUE TITLE
Arcane Int Rank Bug.

### ISSUE THREAD

**Issue by JitlanBG** [Atlantiss/NetherwingBugtracker#7334]
If you are affected by a higher rank of Arcane int than you intent to cast on others. it will say the target already has a more powerful effect. Example: Arcane Int Rank 2 is on me. I attempt to cast arcane int rank 1 on Jeff. Jeff cannot get this buff until i click off my higher rank of Arcane int.

**Comment by Godmatik** [comment]
That's not a bug

**Comment by JitlanBG** [comment]
Keep in mind Jeff in this case has no Arcane int in the first place. I am the only one. So why can't i buff jeff? why is that a feature?

**Comment by Tereneckla** [comment]
I can do so without problems at all

**Comment by JitlanBG** [comment]
Try and test it with a second player. I was given the Arcane int higher rank than I could myself. seems it might be more specific than I expected.

**Comment by Tereneckla** [comment]
Really can't reproduce this. Even with 3 characters. 1 buffing 2 with higher rank than 2 has. 2 buffing 3 with lower rank.
