### ISSUE TITLE
[Item][Libram of the Eternal Rest]

### ISSUE THREAD

**Issue by arcwizard** [Atlantiss/NetherwingBugtracker#7335]
**Description**: 
Equip: Increases the damage of your Consecration spell by 47.

**Current behaviour**:
Libram increase every "tick" consecration by 47, even more (seems more like it add 47 for every tick + 47 for total dmg).
Combat log without libram: 
![sdasd](https://user-images.githubusercontent.com/43764742/89712427-1be99680-d991-11ea-8f48-97099213d5ed.jpg)
Combat log with libram: 
![sadasd](https://user-images.githubusercontent.com/43764742/89712439-2441d180-d991-11ea-8ae2-941a089125c4.jpg)

**Expected behaviour**: 
Libram should add 47 dmg for total dmg consecration, it's means  for every tick = 1/8 from 47 dmg ~ +5-6 dmg. 

**Server Revision**: 
3507 Karazhan realm

https://www.wowhead.com/item=27917/libram-of-the-eternal-rest
> camarouge on 2007/10/16 (Patch 2.2.3)
> Agreed.. I've noticed this **libram adds around 5-6 damage per tick** to my consecration(reinforcing the original statement that it adds 47 damage to the whole spell, or 47/8 = ~5-6 per tick), which is +9-10 TPS if you use consecration.

**Comment by Wolffenstein** [comment]
Fixed in rev 3511.
