### ISSUE TITLE
Razorthorn Ravagers are not tameable

### ISSUE THREAD

**Issue by Gooberter** [Atlantiss/NetherwingBugtracker#7336]
[//]: # (Enclose links to things related to the bug using http://wowhead.com or any other TBC database.)
[//]: # (You can use screenshot ingame to visual the issue.)
[//]: # (Write your tickets according to the format:)
[//]: # ([Quest][Azuremyst Isle] Red Snapper - Very Tasty!)
[//]: # ([NPC] Magistrix Erona)
[//]: # ([Spell][Mage] Fireball)
[//]: # ([Npc][Drop] Ghostclaw Lynx)
[//]: # ([Web] Armory doesnt work)
[//]: # (To find server revision type `.server info` command in the game chat.)

**Description**:  Razorthorn Ravagers (only level 70 ravagers in the game) in Southwest Hellfire are not tameable

**Current behaviour**: Not tameable as pets for hunters

**Expected behaviour**: Should be tameable as pets for hunters

**Server Revision**:

**Comment by Drayo** [comment]
http://web.archive.org/web/20080723125025/http://petopia.brashendeavors.net/html/mobs/mob_razorthornravager.php

These are not supposed to be tameable.
