### ISSUE TITLE
[Raid] [Azeroth] Attempting to reset Zul'Gurub fails

### ISSUE THREAD

**Issue by Drayo** [Atlantiss/NetherwingBugtracker#7337]
[//]: # (Enclose links to things related to the bug using http://wowhead.com or any other TBC database.)
[//]: # (You can use screenshot ingame to visual the issue.)
[//]: # (Write your tickets according to the format:)
[//]: # ([Quest][Azuremyst Isle] Red Snapper - Very Tasty!)
[//]: # ([NPC] Magistrix Erona)
[//]: # ([Spell][Mage] Fireball)
[//]: # ([Npc][Drop] Ghostclaw Lynx)
[//]: # ([Web] Armory doesnt work)
[//]: # (To find server revision type `.server info` command in the game chat.)

**Current behaviour**: 

- When I try to reset Zul'Gurub (no bosses killed) I get the message that "Zul'Farrak has been reset." 
![image](https://user-images.githubusercontent.com/23145811/89717902-1bfe8c00-d9bb-11ea-8c7d-15b0940bd680.png)

**Expected behaviour**: 

- Zul'Gurub should reset, not Zul'Farrak

**Server Revision**: 3507

**Comment by Tereneckla** [comment]
https://wowwiki.fandom.com/wiki/Instance_reset?oldid=1145830

![image](https://user-images.githubusercontent.com/50233983/90320378-1a940d00-df41-11ea-9cb4-26b09f6999cb.png)
