### ISSUE TITLE
Server-side delay when shapeshifting

### ISSUE THREAD

**Issue by recreantus** [Atlantiss/NetherwingBugtracker#7338]
**Description**: 
Shapeshifting in and out of form as a Druid causes a slight delay before the action is performed. This results in major difficulties trying to properly time powershifts with the upcoming energy ticks when playing Feral DPS. The spec is heavily reliant on timing and quick decisions. I have between 48 and 51ms ping to Karazhan and I went back to other TBC servers I played on where shapeshifting works instantly and flawlessly and my ping is very similar, between 30 and 60. I have spoken to several other Feral Druids here who have all experienced this delay as well. This problem causes a significant decrease in our ability to play the spec well.

**Current behaviour**:
When pressing a button to shapeshift or powershift it almost appears as if there's a slight cast time before the shift happens. This is very visible when standing in normal form and going into Cat Form. It's difficult to say, but it looks to be roughly 200-400ms between the click and the shift, whereas on other servers this action is as close to instantaneous as can be. Other spells (instant casts) also seem to have a very small delay, although not as expressed or damaging as shapeshifting - given the time-sensitiveness. Try Omen of Clarity for example, where you can also see almost a cast going off before the buff is applied.

**Expected behaviour**: 
Shifting in and out of form should not have any type of delay beforehand, no visible "cast time" or anything like this. Same goes for all instant casts really.

**Server Revision**: 
Karazhan: 3507

**Comment by kalmasc** [comment]
Can confirm, destroys ferals completely.

**Comment by Notmelody** [comment]
Really clunky to play with for sure. Hope it gets addressed.

**Comment by LopoEvil** [comment]
Bump, This is BAD!!!!!

You can't use normal Macros, that are a MUST while playing a Druid.

unshifting and/or shifting should NOT use a GCD, which i feel it is.

Normally i can go from any Shift, like BEAR, into Stealth Cat, in one click macro, but on the PS, it doesnt work, you need to click twice, this is also with other macros that use spells or anything a normal bear would do in a quick power-shift move.

Please look into this. Not sure why this is not Top Priority and pushed harder by Druid players.

Thanks :)

**Comment by Easyfraggy** [comment]
Unshifting doesn't give GCD, shifting into form does and should though. This report seems invalid. @thundermaul

**Comment by Easyfraggy** [comment]
What are are describing might be https://github.com/Atlantiss/NetherwingBugtracker/issues/5578

Shifting works properly. Talked to both leading ferals on the server.
