### ISSUE TITLE
[Core] Can't attack after getting mind controlled by npcs

### ISSUE THREAD

**Issue by eri1997** [Atlantiss/NetherwingBugtracker#7339]
[//]: # (Enclose links to things related to the bug using http://wowhead.com or any other TBC database.)
[//]: # (You can use screenshot ingame to visual the issue.)
[//]: # (Write your tickets according to the format:)
[//]: # ([Quest][Azuremyst Isle] Red Snapper - Very Tasty!)
[//]: # ([NPC] Magistrix Erona)
[//]: # ([Spell][Mage] Fireball)
[//]: # ([Npc][Drop] Ghostclaw Lynx)
[//]: # ([Web] Armory doesnt work)
[//]: # (To find server revision type `.server info` command in the game chat.)

**Description**:  If you get mind controlled by any different spell from the npcs in the game you can't attack until you clear target (press esc) and target again. ( I'm a hunter in case this doesn't happen to other classes )

**Current behaviour**: Attacking after mindcontroll requires you to clear target and target again

**Expected behaviour**:  Can attack after getting mindcontrolled.

**Server Revision**: 3507

**Comment by Godmatik** [comment]
Unable to reproduce
Able to attack again with no issues after being mind controlled from NPC - did not have to clear target.

Probably addon related issue
