### ISSUE TITLE
[Spell] touch of zanzil debuff

### ISSUE THREAD

**Issue by DarthNekr0s** [Atlantiss/NetherwingBugtracker#734]
**Description**:  when afflicted with touch of zanzil while on the rogue class quest, your character should turn a darker colour than normal
https://youtu.be/gUUIAchcl8s?t=266 <- can see the slight change here after this person removes the debuff. it is minor but should still be noticeable.

**Current behaviour**: i am still bright

**Expected behaviour**:  character changes to darker colour similiar to when poisoned/enraged/etc

**Server Revision**: 2072

![untitled](https://user-images.githubusercontent.com/16113944/46125117-07072c80-c26b-11e8-8e9c-487e0a24035e.png)

**Comment by Wolffenstein** [comment]
Graphical settings perhaps? It seems to be working fine for me:
https://gfycat.com/pl/CarefreeColossalHen
