### ISSUE TITLE
[Quest][Elwynn Forest] Princess Must Die!

### ISSUE THREAD

**Issue by Hosampsich** [Atlantiss/NetherwingBugtracker#7341]
**Mobs that appear too quickly prevent the task from being completed, making them too difficult for a low-level player.**
_I apologize in advance for my English_

**Youtube:** https://youtu.be/AbPndpB7J7s

**Wowhead:** https://classic.wowhead.com/quest=88/princess-must-die

**Server Revision**:  3507

**Comment by Wolffenstein** [comment]
Fixed in rev 3946.
