### ISSUE TITLE
Divination: Gorefiend's Cloak

### ISSUE THREAD

**Issue by Godmatik** [Atlantiss/NetherwingBugtracker#7344]
Even with the spectrecles on, most of the mobs in the general area (around 64, 47) are still invisible to you and will aggro and slowly kill you when you can't do anything in return.

**Comment by Tereneckla** [comment]
Item 30721 allows me to see them. Item 30719 doesn't.

**Comment by Godmatik** [comment]
If I unequip/re-equip the goggles it sometimes works, and if i de-aggro the invisble mobs they become visible to me after i leash them

**Comment by 6ix9inescumgang** [comment]
As a followup to this thread i also had this issue, the second i vanished i could suddenly see 2 previously invisible mobs that were hitting me now running away from me, without changing any gear.

**Comment by ScottieDOESknow** [comment]
When these mobs respawn they are invisible even if you have the Spectracles on
They will attack you and kill you slowly. Nothing even shows in combat log.
Very bugged at the moment. Not sure what happened, as this quest was working fine on NW.
Literally have to run 100 yrs away out of combat after every 1-2 mobs.

**Comment by danbopes** [comment]
Rev 3601
