### ISSUE TITLE
Cleansing Witch Hill in DMW not summoning the bat that you're supposed to kill

### ISSUE THREAD

**Issue by Popmycherry** [Atlantiss/NetherwingBugtracker#7346]
**Description**: When using the flame quest thingie you're supposed to put at the end of the dock, it doesn't summon gargoyle/bat

**Current behaviour**: Nothing happens when you use the flame quest item (not only me, saw several alliance AND horde players come after me and nothing happened then either.

**Expected behaviour**: A bat/Gargoyle is supposed to be spawn at the end of the dock, mid-air and you can kill it.

**Server Revision**: 3507

**Comment by Peglaa** [comment]
The quest definitely has an issue. It didn't work for me either but I was doing with another person and when they used their item the gargoyle spawned and everything worked fine. It's like there some internal cooldown that lasts too long or some other issue that prevents it from spawning but only sometimes. I've seen multiple people successfully do the quest while being in the area tho so it's definitely not completely broken.

**Comment by Godmatik** [comment]
Confirmed.

When "Swamp Eye" Jarl and Mordant Grimsby were having their RP chat and I used the torch nothing happened. Abandoned and re-took the quest, then it worked.

**Comment by Popmycherry** [comment]
> Confirmed.
> 
> When "Swamp Eye" Jarl and Mordant Grimsby were having their RP chat and I used the torch nothing happened. Abandoned and re-took the quest, then it worked.

Yeah, I tried that many times myself before I posted this bug, but it didn't work for me. But I can confirm what Peglaa said, that it worked for some. As I was around that area for about an hour, and I saw maybe 20-40 people try it, and 2 managed to summon it.

**Comment by Wolffenstein** [comment]
Fixed in rev 3511.
