### ISSUE TITLE
Double and bugged NPC's in Halaa

### ISSUE THREAD

**Issue by Vessler** [Atlantiss/NetherwingBugtracker#7347]
**Current behaviour**: Currently there is one npc for each faction which isn't supposed to happen, also those NPC's are killing each other and eventually Halaa goes to other faction just by NPC's killing guards randomly.

**Expected behaviour**: There should be one NPC for the faction that's controlling Halaa

![BUg](https://user-images.githubusercontent.com/37425406/89742517-fba5fe80-da9a-11ea-9475-8331e2481e48.png)

**Comment by Vessler** [comment]
PS: Another screenshot where you can see that there's 2 ammunition vendors, and the alliance one is killing guards cuz it has more stats the the actual guard. 
![Bug 2](https://user-images.githubusercontent.com/37425406/89742571-4e7fb600-da9b-11ea-8b87-fa7e230ce749.png)

**Comment by Wolffenstein** [comment]
Fixed in rev 3511.
