### ISSUE TITLE
[Npc][Drop]Formula: Enchant Bracer - Spellpower

### ISSUE THREAD

**Issue by nevrozac** [Atlantiss/NetherwingBugtracker#7348]
**Description**: The recipe [Formula: Enchant Bracer - Spellpower] is supposed to be drop from Bloodmaul Ogres in Blade's Edge Mountains to any enchanters regardless of their profession level, but it has not dropped yet on Karazhan.
Wowhead mentions it existing in 2.0: https://www.wowhead.com/item=22534/formula-enchant-bracer-spellpower

**Current behaviour**: Formula doesn't drop

**Expected behaviour**: Formula drops
**Server Revision**: 
2.0.3 3507

**Comment by Notmelody** [comment]
It exists

**Comment by nevrozac** [comment]
Game Master mentioned that it has not dropped once yet on Karazhan despite it being a formula that drops in a questing area from quest related NPCs. Needs verifying

**Comment by Notmelody** [comment]
https://i.imgur.com/NtR1w6K.png

**Comment by Tereneckla** [comment]
Thank you for proving this wrong, sadly I have no DB access to check it myself.
