### ISSUE TITLE
Body and Heart Quest Turn in Issue, Quest Complete but unable to turn in for Bear Form 

### ISSUE THREAD

**Issue by andrewstrutt09** [Atlantiss/NetherwingBugtracker#7349]
[//]: # (Enclose links to things related to the bug using http://wowhead.com or any other TBC database.)
[//]: # (You can use screenshot ingame to visual the issue.)
[//]: # (Write your tickets according to the format:)
[//]: # ([Quest][Azuremyst Isle] Red Snapper - Very Tasty!)
[//]: # ([NPC] Magistrix Erona)
[//]: # ([Spell][Mage] Fireball)
[//]: # ([Npc][Drop] Ghostclaw Lynx)
[//]: # ([Web] Armory doesnt work)
[//]: # (To find server revision type `.server info` command in the game chat.)

**Description**: 

**Current behaviour**:

**Expected behaviour**: 

**Server Revision**:

**Comment by Godmatik** [comment]
just did the quest with no issue, did you talk to the bear spirit? you have to go through all of the dialog boxes until the very end

**Comment by Tereneckla** [comment]
Also don't have a problem with it. What is your problem specifically?
Did you not get the Bear Form spell?
Does the Bear Form spell not work?

**Comment by Tereneckla** [comment]
@Godmatik

**Comment by Tereneckla** [comment]
@andrewstrutt09
