### ISSUE TITLE
[NPC] Synge

### ISSUE THREAD

**Issue by mbzz88** [Atlantiss/NetherwingBugtracker#735]
**Description**: The NPC "Synge", ammo vendor at the Shimmering Flats in Thousand Needles, is missing.
http://db.hellfire-tbc.com/?npc=3053

**Current behaviour**: No Synge
![wowscrnshot_092718_175233](https://user-images.githubusercontent.com/43509267/46125696-61f64f00-c27e-11e8-94a1-e2b7244986b7.jpg)

**Expected behaviour**: Standing by this hut

**Comment by aresbrutus** [comment]
Will be fixed in one of the upcoming updates.
