### ISSUE TITLE
[Spell][NPC] Spore Cloud

### ISSUE THREAD

**Issue by Lariari** [Atlantiss/NetherwingBugtracker#7350]
[//]: # (Enclose links to things related to the bug using http://wowhead.com or any other TBC database.)
[//]: # (You can use screenshot ingame to visual the issue.)
[//]: # (Write your tickets according to the format:)
[//]: # ([Quest][Azuremyst Isle] Red Snapper - Very Tasty!)
[//]: # ([NPC] Magistrix Erona)
[//]: # ([Spell][Mage] Fireball)
[//]: # ([Npc][Drop] Ghostclaw Lynx)
[//]: # ([Web] Armory doesnt work)
[//]: # (To find server revision type `.server info` command in the game chat.)

**Description**: 
Spore Cloud armor reduction debuff is incorrect. Not sure if it's just the Spore Bat's Spore Cloud or other mobs.
**Current behaviour**:
The armor reduction seems to be 99% (8501 Armor debuffed to 85 armor)
**Expected behaviour**: 
The armor reduced should be 15%
**Server Revision**: 
3507
![aaa](https://user-images.githubusercontent.com/43853367/89750150-5e45cd00-da90-11ea-9dad-ba71e69fff89.png)

**Comment by Wolffenstein** [comment]
Was fixed a while ago.
