### ISSUE TITLE
[AH] Attempting to auction an item with full charges fails

### ISSUE THREAD

**Issue by krombopulos2020** [Atlantiss/NetherwingBugtracker#7351]
![AH Error](https://user-images.githubusercontent.com/69445721/89750664-431aa200-db10-11ea-906c-81b22bd7de86.JPG)

**Description**: I'm trying to auction Thick Felsteel Necklaces that I just crafted and am receiving the error in the attached screenshot.

**Current behaviour**: The AH registers these newly crafted items as not having full charges so will not allow them to be posted.

**Expected behaviour**: The items have full charges so should be able to be posted to the AH.

**Server Revision**: 3507

**Comment by Tereneckla** [comment]
I have no problems doing so. Other items also work. Try deleting your cache.

**Comment by krombopulos2020** [comment]
Deleted cache, same issue.

**Comment by Wolffenstein** [comment]
Works fine for me as well. Cannot reproduce.
