### ISSUE TITLE
[Spell][Warlock][Summon Voidwalker]Voidwalker disappears

### ISSUE THREAD

**Issue by manbeerpigg** [Atlantiss/NetherwingBugtracker#7352]
[//]: # ([Spell][Warlock][Summon Voidwalker]
**Description**:  Voidwalker very often disappears after mounting and then dismounting...

**Current behaviour**: Voidwalker disappears

**Expected behaviour**: Voidwalker should not disappear after dismounting

**Server Revision**: 3507

**Comment by manbeerpigg** [comment]
happens a lot while questing in SMV

**Comment by Wolffenstein** [comment]
Not enough info.
