### ISSUE TITLE
([NPC] Balnazzar) Stratholme last boss

### ISSUE THREAD

**Issue by EboneXx** [Atlantiss/NetherwingBugtracker#7354]
**Description**: Stratholme Live side last boss 

**Current behaviour**: Being way too big when he transforms, also name doesnt changes to Balnazzar

**Expected behaviour**:  have a smaller model and change name to Balnazzar 

**Server Revision**:3504
![image](https://user-images.githubusercontent.com/69278794/89819085-38b4d400-db21-11ea-9779-2dd42e370fa5.png)

**Comment by Tereneckla** [comment]
Duplicate of #7027
