### ISSUE TITLE
Bleakheart Satyrs

### ISSUE THREAD

**Issue by Godmatik** [Atlantiss/NetherwingBugtracker#7356]
Bleakheart Satyrs, Hellcallers, Shadowstalkers, and Tricksters should be using "Curse of the Bleakheart" on the player, which causes "Chest Pains" debuff.

Instead, they appear to be debuffing and stunning themselves.

https://classic.wowhead.com/spell=6946/curse-of-the-bleakheart#used-by-npc
https://classic.wowhead.com/spell=6945/chest-pains

**Comment by The14me** [comment]
Confirm

**Comment by Peglaa** [comment]
Confirming also

**Comment by Godmatik** [comment]
Casual bump, as I level an alt, it's amusing but completely unintentional to see these NPCs stunning themselves.

**Comment by Godmatik** [comment]
Casual final bump as this still occurs when I last tested a couple of weeks ago

**Comment by EtheriousNW** [comment]
Fixed in 3846
