### ISSUE TITLE
Demonic Knowledge bug (Karazhan)

### ISSUE THREAD

**Issue by ChekistNSK** [Atlantiss/NetherwingBugtracker#7357]
Description: "Demonic Knowledge" is not dynamically refreshed and does not work on enslaved demons.

Current behavior: Buffing your pet with Stamina/Intellect/Blessing of Kings does not give you bonus Spell Damage - it requires a "manual" refresh (which is impossible to do due to another bug concerning pets being resummoned every time you teleport/zone/mount), and a "manual" refresh can only be achieved by completely logging out of the game (and never teleporting/zoning/mounting ever again.)
Also, the talent simply does not work at all on enslaved demons.

Expected behavior: Buffing your pet with Stamina/Intellect/Blessing of Kings should refresh the Spell Damage provided through "Demonic Knowledge" instantly.
Enslaving a demon should still give the "Demonic Knowledge" buff - Source: "You can demonic sacrifice your demon pet and then enslave a regular demon and get not only the demonic knowledge buff but also soul-link if you are specc'd for it. Basically, it's an awesome trick but only lasts until your enslave wears off."

Server: Karazhan

**Comment by Tereneckla** [comment]
https://youtu.be/rlVDc0I2cfM

Demonic Knowledge on Enslaved Demon: check
Dynamic Refresh on Normal Demon: check
I don't know what bug you mean with the pet being resummoned on teleport/zone/mount, my pet keeps all buffs on those events.

Only thing that is not working is dynamic refresh of Demonic Knowledge on an Enslaved Demon

**Comment by ChekistNSK** [comment]
It was 2 days ago, but looks like all works now.

**Comment by ChekistNSK** [comment]
Fixed.
