### ISSUE TITLE
Eagle Eyes and Eyes of the Beast hunter spells not working properly

### ISSUE THREAD

**Issue by Pmt112** [Atlantiss/NetherwingBugtracker#7358]
Fixed in revision 3501.

_Originally posted by @Wolffenstein in https://github.com/Atlantiss/NetherwingBugtracker/issues/7275#issuecomment-667702100_

Hi reporting bug, now in revision 3509 these two hunter spells Eagle Eyes and Eyes of the Beast do not work properly / are not usuable. They both create a new point of view for the player, but this point of view does not receive information about nearby players properly resulting in frozen entities and bad interaction and information.

EDIT: After trying again it seems that Eyes of the Beast now works after all but Eagle Eyes doesn't work (same bug as occured before with Eyes of the Beast too, nearby players freezing/wrongly updated/not updated)

**Comment by Wolffenstein** [comment]
Fixed in rev 3511.
