### ISSUE TITLE
Tabetha Mage Quest Order

### ISSUE THREAD

**Issue by alexw0610** [Atlantiss/NetherwingBugtracker#7359]
[//]: # (Enclose links to things related to the bug using http://wowhead.com or any other TBC database.)
[//]: # (You can use screenshot ingame to visual the issue.)
[//]: # (Write your tickets according to the format:)
[//]: # ([Quest][Azuremyst Isle] Red Snapper - Very Tasty!)
[//]: # ([NPC] Magistrix Erona)
[//]: # ([Spell][Mage] Fireball)
[//]: # ([Npc][Drop] Ghostclaw Lynx)
[//]: # ([Web] Armory doesnt work)
[//]: # (To find server revision type `.server info` command in the game chat.)

**Description**: 
Tabetha currently gives the Items of Power Quest before you complete Rituals of Power. According to Wowhead this is wrong https://classic.wowhead.com/quest=1948/items-of-power 
This happens on the TBC Realm Karazhan.

**Current behaviour**:

1. Hidden Secrets | 4. Items of Power (can be started at the same time)
2. Get the Scoop
3. Rituals of Power
5. Mages Wand

**Expected behaviour**: 

1. Hidden Secrets
2. Get the Scoop
3. Rituals of Power
4. Items of Power
5. Mages Wand

**Server Revision**:

**Comment by Wolffenstein** [comment]
Fixed in rev 3511.
