### ISSUE TITLE
[Spell][Hunter]Track Beasts

### ISSUE THREAD

**Issue by mbzz88** [Atlantiss/NetherwingBugtracker#736]
**Description**: I'm guessing this is related to other things being incorrectly untrackable. The starting point for the race at Shimmering Flats shows up on tracking as "You think you can beat me 123?"

**Current behaviour**:![wowscrnshot_092718_182141](https://user-images.githubusercontent.com/43509267/46126742-894f1b00-c282-11e8-9184-c58576b45ed1.jpg)

**Expected behaviour**: Not trackable

**Comment by wtRCH** [comment]
@Evolvee

**Comment by Wolffenstein** [comment]
Should be fixed in rev 2081 by Herkor.
