### ISSUE TITLE
[ITEM] "Drums of Battle" dont work in shapeshift forms

### ISSUE THREAD

**Issue by sugargliderwow** [Atlantiss/NetherwingBugtracker#7361]
https://www.wowhead.com/item=29529/drums-of-battle

**Description**: 
Leatherworking Item "Drums of Battle" (and maybe other leatherworking drums as well) dont work in Druid`s shapeshift forms. It should work because descriptions of item says "Drums can be used while shapeshifted".

**Current behaviour**:
Now when player used drums in Bear/Cat/Travel form he recieved red text message "You are in shapeshift form"

**Expected behaviour**: 
Start of Drums cast

**Server Revision**: 
?

**Comment by Tereneckla** [comment]
This is the correct 2.0 state and not changeable server side. To get perfect tooltips use this addon https://github.com/nullfoxh/NWTooltipFix
