### ISSUE TITLE
parched hydra ability heat wave bugged

### ISSUE THREAD

**Issue by babno** [Atlantiss/NetherwingBugtracker#7362]
1. It doesn't have a cooldown and can be kept up 100% of the time

2. It is supposed to increase miss chance by 35%, but actually does much more, I'd say at least 70%. Take into account that the first two include swings when I wasn't under the debuff, so the miss rate is actually closer to the last one (ferocious bite, where all attempts were under debuff). I'll note I have 3.15% hit rating, so I should have just under 40% chance to miss with the debuff up.
![image](https://user-images.githubusercontent.com/244626/89961181-f7025700-dc0e-11ea-8d9c-d20f00ebd0be.png)
![image](https://user-images.githubusercontent.com/244626/89961189-fec1fb80-dc0e-11ea-9103-df4361072c53.png)
![image](https://user-images.githubusercontent.com/244626/89961204-07b2cd00-dc0f-11ea-8b6e-51089f97d035.png)

**Comment by Wolffenstein** [comment]
Fixed in rev 3511.
