### ISSUE TITLE
[Item][Iron Shield Spike] Does not do damage

### ISSUE THREAD

**Issue by gscharf94** [Atlantiss/NetherwingBugtracker#7364]
[//]: # (Enclose links to things related to the bug using http://wowhead.com or any other TBC database.)
[//]: # (You can use screenshot ingame to visual the issue.)
[//]: # (Write your tickets according to the format:)
[//]: # ([Quest][Azuremyst Isle] Red Snapper - Very Tasty!)
[//]: # ([NPC] Magistrix Erona)
[//]: # ([Spell][Mage] Fireball)
[//]: # ([Npc][Drop] Ghostclaw Lynx)
[//]: # ([Web] Armory doesnt work)
[//]: # (To find server revision type `.server info` command in the game chat.)

**Description**: 

Iron Shield Spike, an item you place onto a shield to do 8-12 damage whenever you get hit by enemies does not do any damage.

**Current behaviour**:

It does nothing.

**Expected behaviour**: 

It should do between 8 to 12 damage every time you get hit by an enemy while wearing the shield with the shield spike

**Server Revision**: 

I'm on Karazhan

**Comment by raethkcj** [comment]
Shield spikes activate when you block, not every time you get hit. Check again on hits where you block

**Comment by Tereneckla** [comment]
Deals damage on block for me
