### ISSUE TITLE
[Rogue] Pick Pocket skill

### ISSUE THREAD

**Issue by deniya** [Atlantiss/NetherwingBugtracker#7365]
[//]: # (Enclose links to things related to the bug using http://wowhead.com or any other TBC database.)
[//]: # (You can use screenshot ingame to visual the issue.)
[//]: # (Write your tickets according to the format:)
[//]: # ([Quest][Azuremyst Isle] Red Snapper - Very Tasty!)
[//]: # ([NPC] Magistrix Erona)
[//]: # ([Spell][Mage] Fireball)
[//]: # ([Npc][Drop] Ghostclaw Lynx)
[//]: # ([Web] Armory doesnt work)
[//]: # (To find server revision type `.server info` command in the game chat.)

**Description**: 
[Pick Pocket] allows rogue to obtain some additional loot before the fight starts and while being in [Stealth] mode. 
**Current behaviour**:
Unless macroing or spamming the ability one can loot mostly just meagre amounts of copper even at 40+ level (might even end with 10+ copper). Spamming might get you up to 7 bunches of copper and an item as well. If pushing the skill only once in some really short time range, then you won't be able to do it again. In my opinion, somewhat seems quite similar to differences between Herbalism looting and Mining (looting once or the requirement to spam).
**Expected behaviour**: 
Although multiple attempts on a given mob are possible, only the initial (successful) attempt will yield any results. 
 https://wow.gamepedia.com/Pick_Pocket
**Server Revision**:
Karazhan server: 3509
![WoWScrnShot_081220_060543](https://user-images.githubusercontent.com/7021734/89970679-0232a280-dc62-11ea-8359-bf44b7bf1589.jpg)

**Comment by deniya** [comment]
just got a lagspike while pickpocketing and it resulted in around 15 loots of copper from a single mob

**Comment by Wolffenstein** [comment]
Are you sure it's not just a visual bug? Can you try checking before/after how much money you actually received?

**Comment by deniya** [comment]
hmm yea, now that you mentioned it, it seems that it's a visual bug, have checked the amounts gained. I guess may close now.
