### ISSUE TITLE
Kodo Bones - Kodo Apparition

### ISSUE THREAD

**Issue by Godmatik** [Atlantiss/NetherwingBugtracker#7366]
Some of the Kodo Bones have a red crystal on top of them (see screenshot below). if you loot these bones, a kodo apparition spawns. If you loot the bones without a crystal on top of them, then no kodo spawns.

Those crystals I'm assuming are a trigger that are not supposed to be visible to players.

https://classic.wowhead.com/item=13703/kodo-bone
https://classic.wowhead.com/npc=11521/kodo-apparition

![Kodo Bones](https://user-images.githubusercontent.com/37913400/89972690-063fcf80-dc24-11ea-8fcc-d342c9691f1c.png)

**Comment by Tereneckla** [comment]
gob 176751

**Comment by Wolffenstein** [comment]
Fixed in rev 3511.
