### ISSUE TITLE
I cant ress myself and Auto-stuck doesn´t work

### ISSUE THREAD

**Issue by Vadnychov** [Atlantiss/NetherwingBugtracker#7368]
**Description**: the alliance killed me and I went offline when I reconnected, so the spirit in the cemetery is not and the auto-stuck doesn't work
**Current behaviour**: still doesn´t work

**Expected behaviour**: I´ll use Auto-stuck for teleport to closer spirit and ress myself with Sickness

Server: Karazhan
![Bez názvu](https://user-images.githubusercontent.com/61821076/89997527-88fc7500-dc8c-11ea-83ae-7d3f36bf53c0.png)

**Comment by Wolffenstein** [comment]
Cannot reproduce. If you're still having issues, open a ticket.
