### ISSUE TITLE
Quest in BEM: Showdown 

### ISSUE THREAD

**Issue by Vessler** [Atlantiss/NetherwingBugtracker#7369]
**Description**: Once you use the quest item on altar Rexxar should spawn and you kill the gronn.

**Current behaviour**: Once you use the quest item, nothing happens, rexxar doesnt spawn.

**Expected behaviour**: Rexxar should spawn to summon and help you kill Gronn

**Server Revision**: 

How it should work: https://www.youtube.com/watch?v=_e2Z-gQmz_o

**Comment by Tereneckla** [comment]
Letting Rexxar die or killing Roc without participation of Rexxar makes anyone unable to start the even again.
I don't think these are the causes on Live, but they are causes.

**Comment by Vessler** [comment]
Problem is, you cant even summon Rexxar, we used the item on altar and
nothing happens thats the problem

čet, 13. kol 2020. 11:56 Tereneckla <notifications@github.com> je napisao:

**Comment by Wolffenstein** [comment]
Fixed in rev 3511.
