### ISSUE TITLE
Free Action Pot undispellable / not a magic effect

### ISSUE THREAD

**Issue by knasen88** [Atlantiss/NetherwingBugtracker#7370]
[//]: # (Enclose links to things related to the bug using http://wowhead.com or any other TBC database.)
[//]: # (You can use screenshot ingame to visual the issue.)
[//]: # (Write your tickets according to the format:)
[//]: # ([Quest][Azuremyst Isle] Red Snapper - Very Tasty!)
[//]: # ([NPC] Magistrix Erona)
[//]: # ([Spell][Mage] Fireball)
[//]: # ([Npc][Drop] Ghostclaw Lynx)
[//]: # ([Web] Armory doesnt work)
[//]: # (To find server revision type `.server info` command in the game chat.)

**Description**: 
https://wow.gamepedia.com/Free_Action_Potion
1.7 changed to dispellable, because its obviously goddamn bullshit with 25sec fap that cannot be dispelled
**Current behaviour**:
not a magic effect
**Expected behaviour**: 
buff is a magic effect
**Server Revision**: 
3509

**Comment by raethkcj** [comment]
Unfortunately they changed it back in Patch 2.3:

https://wow.gamepedia.com/Patch_2.3.0

>  [Free Action Potion]: The buff from this potion can no longer be dispelled or taken via  [Spellsteal].

I totally agree that it's bullshit, but Blizzard loves bullshit.

**Comment by knasen88** [comment]
then do they goddamn right thing and make it magic, give it counterplay.
and I don't even play a class that purges, this is ridiculous
