### ISSUE TITLE
(Hunter) Cat's Dash casting incorrectly

### ISSUE THREAD

**Issue by Falathrin** [Atlantiss/NetherwingBugtracker#7371]
[//]: # (Enclose links to things related to the bug using http://wowhead.com or any other TBC database.)
[//]: # (You can use screenshot ingame to visual the issue.)
[//]: # (Write your tickets according to the format:)
[//]: # ([Quest][Azuremyst Isle] Red Snapper - Very Tasty!)
[//]: # ([NPC] Magistrix Erona)
[//]: # ([Spell][Mage] Fireball)
[//]: # ([Npc][Drop] Ghostclaw Lynx)
[//]: # ([Web] Armory doesnt work)
[//]: # (To find server revision type `.server info` command in the game chat.)

**Description**: 
I have my pet on passive, and dash is set on auto-cast. If I attack my target without commanding my pet to attack, it'll still cast dash on its own while standing still in place. That shouldn't happen. Dash should only be casted if the pet has been commanded/sent to attack the target.
**Current behaviour**:
Dash is being auto-casted even if you don't command your cat to attack the target.
**Expected behaviour**: 
Dash should only be auto-casted if you command your cat to attack the target.
**Server Revision**:

**Comment by Wolffenstein** [comment]
Already fixed
