### ISSUE TITLE
[Spell][Rogue] Garrote Cheap Shot

### ISSUE THREAD

**Issue by Shenkall** [Atlantiss/NetherwingBugtracker#7372]
**Description**: 
Garrote and Cheap shot procs Poisons (wound poison, instant poison, etc), which remove sap on target instantly due to damage inherent to some poisons.

**Current behaviour**:
Garrote and Cheap shot procs Poisons.

**Expected behaviour**: 
Garrote and Cheap shot should'nt proc Poisons, never saw that kind of thing on any server.

Thanks of your time.

**Comment by tsuone** [comment]
https://github.com/Atlantiss/NetherwingBugtracker/issues/3130

**Comment by tsuone** [comment]
@Shenkall Invalid.
