### ISSUE TITLE
[Quest][Blade's Edge Mountains] Favor of the Gronn

### ISSUE THREAD

**Issue by silly-wet** [Atlantiss/NetherwingBugtracker#7373]
[//]: # (Enclose links to things related to the bug using http://wowhead.com or any other TBC database.)
[//]: # (You can use screenshot ingame to visual the issue.)
[//]: # (Write your tickets according to the format:)
[//]: # ([Quest][Azuremyst Isle] Red Snapper - Very Tasty!)
[//]: # ([NPC] Magistrix Erona)
[//]: # ([Spell][Mage] Fireball)
[//]: # ([Npc][Drop] Ghostclaw Lynx)
[//]: # ([Web] Armory doesnt work)
[//]: # (To find server revision type `.server info` command in the game chat.)

**Description**: 
There's an incorrect prerequisite for the item "Gorgrom's Favor".  Currently, it only drops after you turn in the quest to kill the mob that drops the item. Guides from the TBC era (Zygor's for example) are written that it should drop from Dorgok while you're on "A Date with Dorgok".

**Current behaviour**:
Dorgok drops Gorgrom's Favor after you -turn in- the quest A Date with Dorgok.

**Expected behaviour**: 
Dorgok drops Gorgrom's Favor after you -accept- the quest A Date with Dorgok.

id's
Gorgrom's Favor -- https://tbcdb.com/?item=31363
Dorgok -- https://tbcdb.com/?npc=20753
A Date with Dorgok -- https://tbcdb.com/?quest=10795

**Server Revision**: 
3509

**Comment by Wolffenstein** [comment]
Fixed in rev 3511.
