### ISSUE TITLE
[Quest][Spell] Seer's Presence used on the quest Turning Point stacks

### ISSUE THREAD

**Issue by Tereneckla** [Atlantiss/NetherwingBugtracker#7374]
[//]: # (Enclose links to things related to the bug using http://wowhead.com or any other TBC database.)
[//]: # (You can use screenshot ingame to visual the issue.)
[//]: # (Write your tickets according to the format:)
[//]: # ([Quest][Azuremyst Isle] Red Snapper - Very Tasty!)
[//]: # ([NPC] Magistrix Erona)
[//]: # ([Spell][Mage] Fireball)
[//]: # ([Npc][Drop] Ghostclaw Lynx)
[//]: # ([Web] Armory doesnt work)
[//]: # (To find server revision type `.server info` command in the game chat.)

**Description**: 
![image](https://user-images.githubusercontent.com/50233983/90174169-db7d8480-dda5-11ea-9c2b-fe30a80859fe.png)
https://www.wowhead.com/spell=36314/the-seers-presence
https://www.wowhead.com/quest=10507/turning-point#comments

No clear proof that it shouldn't stack, but also no videos or comments mentioning it stacking.

**Current behaviour**:
Stacks when multiple people use it.
**Expected behaviour**: 
Doesn't stack when multiple people use it.
**Server Revision**: 3510

**Comment by Wolffenstein** [comment]
Fixed in rev 3511.
