### ISSUE TITLE
Damage through obstacles

### ISSUE THREAD

**Issue by Mystery32** [Atlantiss/NetherwingBugtracker#7375]
**Description**: There is a bug in the ability to inflict damage from a distance through obstacles that cannot be passed through.

**Current behaviour**: damage can be dealt through walls and other obstacles

**Expected behaviour**: the inability to cast or shoot (hunters) at targets located behind obstacles through which you cannot pass

**Server Revision**: Wow 2.4.3 (8606)

**Comment by Tereneckla** [comment]
Many trees and some other objects that you can't walk through correct don't block LoS in tbc.

Please elaborate which you mean and if it is trees you can close this issue yourself.

**Comment by Mystery32** [comment]
They are really trees in most cases.

**Comment by Godmatik** [comment]
A lot of stock private servers make trees an LoS object when they should not be, it's intended for enemies to shoot through them.
