### ISSUE TITLE
[Quest] Deathblow to the Legion RP errors

### ISSUE THREAD

**Issue by Tereneckla** [Atlantiss/NetherwingBugtracker#7376]
[//]: # (Enclose links to things related to the bug using http://wowhead.com or any other TBC database.)
[//]: # (You can use screenshot ingame to visual the issue.)
[//]: # (Write your tickets according to the format:)
[//]: # ([Quest][Azuremyst Isle] Red Snapper - Very Tasty!)
[//]: # ([NPC] Magistrix Erona)
[//]: # ([Spell][Mage] Fireball)
[//]: # ([Npc][Drop] Ghostclaw Lynx)
[//]: # ([Web] Armory doesnt work)
[//]: # (To find server revision type `.server info` command in the game chat.)

**Description**: 

**Current behaviour**:
https://youtu.be/51Ocg_QWMJU
**Expected behaviour**: 
Ishanah actually dies https://youtu.be/j9oVkY8dH1o?t=559
![image](https://user-images.githubusercontent.com/50233983/90179752-39ae6580-ddae-11ea-8688-161336624993.png)

Kaylan stays hostile until he arrives at the corpse of Ishanah https://youtu.be/j9oVkY8dH1o?t=566

Ishanah only offers to turn in Deathblow to the Legion without additional gossip https://youtu.be/j9oVkY8dH1o?t=603
**Server Revision**: 3510

**Comment by Godmatik** [comment]
#9162
