### ISSUE TITLE
[PvP][Quest] Call to Arms

### ISSUE THREAD

**Issue by tsuone** [Atlantiss/NetherwingBugtracker#7377]
[//]: # (Enclose links to things related to the bug using http://wowhead.com or any other TBC database.)
[//]: # (You can use screenshot ingame to visual the issue.)
[//]: # (Write your tickets according to the format:)
[//]: # ([Quest][Azuremyst Isle] Red Snapper - Very Tasty!)
[//]: # ([NPC] Magistrix Erona)
[//]: # ([Spell][Mage] Fireball)
[//]: # ([Npc][Drop] Ghostclaw Lynx)
[//]: # ([Web] Armory doesnt work)
[//]: # (To find server revision type `.server info` command in the game chat.)

**Description**: Call to Arms quests rotation.

**Current behaviour**: Daily rotation of Call to Arms quests doesn't work. NPCs give `Call to Arms: Alterac Valley` quest only since the release.

**Expected behaviour**: There should be a daily rotation of Call to Arms quests available at Brigadier General and Warbringer NPCs. 

**Server Revision**: 3509

**Comment by Wolffenstein** [comment]
Fixed in rev 3520.

**Comment by Godmatik** [comment]
Not fixed, still always AV
