### ISSUE TITLE
[Paladin][Spell] Seal of Blood, Seal of Command don't deal increased damage with Sanctity Aura

### ISSUE THREAD

**Issue by Mikik3jr** [Atlantiss/NetherwingBugtracker#7378]
[//]: # (Enclose links to things related to the bug using http://wowhead.com or any other TBC database.)
[//]: # (You can use screenshot ingame to visual the issue.)
[//]: # (Write your tickets according to the format:)
[//]: # ([Quest][Azuremyst Isle] Red Snapper - Very Tasty!)
[//]: # ([NPC] Magistrix Erona)
[//]: # ([Spell][Mage] Fireball)
[//]: # ([Npc][Drop] Ghostclaw Lynx)
[//]: # ([Web] Armory doesnt work)
[//]: # (To find server revision type `.server info` command in the game chat.)

**Description**: 
I created a paladin on the test server and took some talents not really chaning my damage:
![image](https://user-images.githubusercontent.com/43505031/90262258-6023dd80-de4e-11ea-8637-38f221e351ba.png)
![image](https://user-images.githubusercontent.com/43505031/90262174-44b8d280-de4e-11ea-95b5-6f5fe3ccd967.png)

**Current behaviour**:
Currently with seal of blood I deal 32-33 dmg/hit with my really bad gear:
![image](https://user-images.githubusercontent.com/43505031/90262364-85b0e700-de4e-11ea-97f3-bdf2b46d9ca0.png)

When I apply Judgement of the Crusader (increases holy damage taken by 219) and Sanctity Aura (increases holy damage done by 10%) it does not increase my seal of blood damage which is supposed to deal 35% of my weapon damage as HOLY damage:
![image](https://user-images.githubusercontent.com/43505031/90262500-ab3df080-de4e-11ea-9986-0b6283e4138e.png)

If I use seal of command Judgement of the Crusader increases the damage, but Sanctity Aura doesn't.

**Expected behaviour**: 
I think as it says it increases holy damage taken/done, then they should be applied accordingly.

**Server Revision**: 
3510 on test server, but saw the same on the real server on 3509.

**Comment by Tereneckla** [comment]
Increases holy damage taken means your holy spell power when attacking that target is increased.

Neither seals scale with spell power so your damage is not increased.

**Comment by Mikik3jr** [comment]
It is stupid that is says holy damage taken, but only says for spells.

**Comment by Ashfall7x** [comment]
Using Sanc Aura -> Consec and No Aura -> Consec, deals the same damage.
Sanc Aura does not work...

**Comment by Wolffenstein** [comment]
Fixed in rev 3511.
