### ISSUE TITLE
Rogue instant poisons 

### ISSUE THREAD

**Issue by DarthNekr0s** [Atlantiss/NetherwingBugtracker#738]
**Description**:  unable to apply instant poison to my offhand sword - Defias Rapier. move it to mainhand and also unequipped it but still wouldnt apply. gives an error that says "target too low level". bought various white qualityswords from vendors ranging from lvl 1-14 and tried to apply as well but they all wouldn't let me

**Current behaviour**: instant poison needing an item level requirement

**Expected behaviour**:  should be able to apply this to any sword regardless of level

**Server Revision**: 2072

https://streamable.com/v8co3

**Comment by Easyfraggy** [comment]
Same problem as https://github.com/Atlantiss/NetherwingBugtracker/issues/403

**Comment by DarthNekr0s** [comment]
fixed in rev 2078
