### ISSUE TITLE
Temple of Telhamat Guards not attack Horde players.

### ISSUE THREAD

**Issue by Schmoopylt** [Atlantiss/NetherwingBugtracker#7380]
[//]: # (Enclose links to things related to the bug using http://wowhead.com or any other TBC database.)
[//]: # (You can use screenshot ingame to visual the issue.)
[//]: # (Write your tickets according to the format:)
[//]: # ([Quest][Azuremyst Isle] Red Snapper - Very Tasty!)
[//]: # ([NPC] Magistrix Erona)
[//]: # ([Spell][Mage] Fireball)
[//]: # ([Npc][Drop] Ghostclaw Lynx)
[//]: # ([Web] Armory doesnt work)
[//]: # (To find server revision type `.server info` command in the game chat.)

**Description**: Temple of Telhamat Guards are not attack opposing faction players, making it a easy hunting ground for horde.

**Current behaviour**: 

**Expected behaviour**: 

**Server Revision**:

**Comment by Wolffenstein** [comment]
They work fine, they're just low level (and it's apparently blizzlike).
