### ISSUE TITLE
Mana Regen in Starting area / gear with no stats, Super Low.

### ISSUE THREAD

**Issue by LopoEvil** [Atlantiss/NetherwingBugtracker#7383]
I Noticed that when i made a mana using character, the mana regen is Super Low! compared to even Classic.
Not sure if there is something from having no stats on gear, but it doesn't seem correct, I have been playing WOW for years and can't remember ever having to stop and drink after almost every mob, in the starting zones. I could cast a few, mobs get to be, melee or wand, then by the time they were dead or i would get to the next mob, my mana  would be about full, once more.

Low Mana Regen - Starting Zones / No stats on gear

Mana to Refill quicker, where you do not need to stop and drink after each mob or two, if you play correctly; Cast spells, Wand/Melee - Regen to almost full.

2.3.4

**Comment by raethkcj** [comment]
Here's a page describing the formula for 2.4.3:

https://wow.gamepedia.com/index.php?title=Mana_regeneration&oldid=1422970

Note that it's not the same formula used in classic, and often means a smaller base regen but better scaling with spirit. I've tested it and found it to match Netherwing/Karazhan's regen. Check and see if it matche your character's regen!

**Comment by Wolffenstein** [comment]
I checked the regen formulas a while ago, and they seem to be matching the 2.4.3 ones - as raethkcj said they're different from classic.
