### ISSUE TITLE
[NPC][Mechanics] Mob melee range bonus still active while mob is slowed 

### ISSUE THREAD

**Issue by mecher529** [Atlantiss/NetherwingBugtracker#7384]
See issue  #3635 for reference, as the issues presented in that bug report are still present on the current Karazhan core, making hamstring kiting impossible. 

Definition:

    If you and your target is running, the game client will give you a +2.5 yard leeway range, same goes for your target, basically the range indicator for your melee abilities will be white when you're within 7.5 yards of the target(point to point)

    *Leeway mechanic will immediately stop if you or your target becomes slowed to more than -29% of normal run speed(-30% is when your character will switch animation to walking instead of running). Note that it has to be more than -29% of normal running speed, meaning if you or your enemy is on a 100% and become slowed, but the slow doesn't slow down enough to go below -29% normal run speed, then mechanic will still work. Example: Warlock with Curse of Exhaustion talented to grant 30% slow, you cast it on a rogue that has 8% run speed boots enchant. Then leeway mechanic will still work.

https://www.reddit.com/r/lightshope/comments/8yh841/melee_leeway_mechanic/

Current behaviour:
Mob is able to hit melee within 5.1-8yards and i can't return a hit because my range is 5yards less.(slowed)
https://gfycat.com/AgileScarceHumpbackwhale

I run into 5yards less and i am able to attack.
https://gfycat.com/AmpleBronzeAmbushbug

running around the target within 5-8y without movement back and forth.
https://gfycat.com/BraveWarmBluemorphobutterfly

Expected behaviour:
You are able to trade even at 5yards or less because of the slow.

**Comment by WarlordTF** [comment]
Please also record server latency, as melee leeway is also affected by that.

**Comment by Godmatik** [comment]
Melee leeway was fixed last year.

Closing.
