### ISSUE TITLE
[NPC][Mechanics] Ice Thistle Yeti/Matriarch/Patriarch

### ISSUE THREAD

**Issue by razloo** [Atlantiss/NetherwingBugtracker#7385]
**Description**: 
NPCs are spaming ice blast (2s stuns) too often
**Current behaviour**:
You can get stunned several times in a row 
**Expected behaviour**: 
Less stun proc/cast
**Server Revision**:

**Comment by Tereneckla** [comment]
On the other hand I though multiple of them over 10 minutes now and not a single ice blast was casted.

**Comment by Godmatik** [comment]
It procs on melee hit from the player, not the yeti. So if you are dual wielding or have a fast attack speed, then you will get frozen more often.

**Comment by Tereneckla** [comment]
Current proc rate would warrant a mass of comments on retail DBs that these are very annoying. I agree.

**Comment by razloo** [comment]
> Current proc rate would warrant a mass of comments on retail DBs that these are very annoying. I agree.
> But those comments don't exist.

Yeah, i posted this only because i have leveled a warrior on classic not long ago and these mobs didn't give me a problem. Certainly seems incorrect.

**Comment by Wolffenstein** [comment]
Fixed in rev 3545.
