### ISSUE TITLE
"In Case of Emergency" Cogs flat on ground don't disappear after looting them

### ISSUE THREAD

**Issue by Justfor49** [Atlantiss/NetherwingBugtracker#7386]
[//]: # (Enclose links to things related to the bug using http://wowhead.com or any other TBC database.)
[//]: # (You can use screenshot ingame to visual the issue.)
[//]: # (Write your tickets according to the format:)
[//]: # ([Quest][Azuremyst Isle] Red Snapper - Very Tasty!)
[//]: # ([NPC] Magistrix Erona)
[//]: # ([Spell][Mage] Fireball)
[//]: # ([Npc][Drop] Ghostclaw Lynx)
[//]: # ([Web] Armory doesnt work)
[//]: # (To find server revision type `.server info` command in the game chat.)

**Description**: 
"In Case of Emergency" Cogs flat on ground don't disappear after looting them

**Current behaviour**:
After looting the cogs that are flat on the ground, your character gets the loot, but the cog stays on the ground with sparkles but cannot be looted again. Interact cursor appears, but cog can't be looted:

![cog](https://user-images.githubusercontent.com/69169443/90310304-4f12b500-debe-11ea-9e77-0485feaaef21.jpg)

Note that the cogs that are stuck straight up in the ground work as normal:

![cog2](https://user-images.githubusercontent.com/69169443/90310331-9a2cc800-debe-11ea-8b95-f0403cb0f45d.jpg)

**Expected behaviour**: 

Like the other lootable items on the ground, the cog should disappear after being looted. 

**Server Revision**: 
Revision before 3511

**Comment by Wolffenstein** [comment]
Clientside bug.
