### ISSUE TITLE
Maraudon entrance stone door closes much too quickly after being opened

### ISSUE THREAD

**Issue by Justfor49** [Atlantiss/NetherwingBugtracker#7388]
[//]: # (Enclose links to things related to the bug using http://wowhead.com or any other TBC database.)
[//]: # (You can use screenshot ingame to visual the issue.)
[//]: # (Write your tickets according to the format:)
[//]: # ([Quest][Azuremyst Isle] Red Snapper - Very Tasty!)
[//]: # ([NPC] Magistrix Erona)
[//]: # ([Spell][Mage] Fireball)
[//]: # ([Npc][Drop] Ghostclaw Lynx)
[//]: # ([Web] Armory doesnt work)
[//]: # (To find server revision type `.server info` command in the game chat.)

**Description**: 

Maraudon entrance stone door closes much too quickly after being opened. It closes right after being opened. No delay before closing

**Expected behaviour**: 

There should be a delay of about 2 seconds from being fully open to closing again: 

https://youtu.be/L-6K_XTrTYQ?t=57

https://youtu.be/gwaiVicbtoc?t=1402

**Server Revision**: 
This was about 2 weeks ago

**Comment by EtheriousNW** [comment]
Fixed
