### ISSUE TITLE
Wizbang Cranktoggle - quest NPC

### ISSUE THREAD

**Issue by narayagh** [Atlantiss/NetherwingBugtracker#739]
[//]: # (Enclose links to things related to the bug using http://wowhead.com or any other TBC database.)
[//]: # (You can use screenshot ingame to visual the issue.)
[//]: # (Write your tickets according to the format:)
[//]: # ([Quest][Azuremyst Isle] Red Snapper - Very Tasty!)
[//]: # ([NPC] Magistrix Erona)
[//]: # ([Spell][Mage] Fireball)
[//]: # ([Npc][Drop] Ghostclaw Lynx)
[//]: # ([Web] Armory doesnt work)

**Description**: 
Wizbang Crantoggle offers you a quest "Gaffer Jacks" **only** if you have a fishing pole equipped.

**Current behaviour**:
Wizbang Crantoggle offers you a quest "Gaffer Jacks" **only** if you have a fishing pole equipped.
See: https://streamable.com/ngigl

**Expected behaviour**: 
Wizbang Crantoggle should offer a quest "Gaffer Jacks" regardless of the player having a fishing pole equipped or not.

**Server Revision**: 
2072

**Comment by narayagh** [comment]
Update: I think this might be connected to the fact that according to wowhead, this quest requires fishing level 30 to be obtainable - see https://www.wowhead.com/quest=1579/gaffer-jacks#comments:id=277935. My fishing rod in the video was "enchanted" with fishing lure giving me +25 fishing skill, which probably got me up to 30 at that time - so the quest was obtainable.

**What it means is that the current behaviour is probably correct!**

**Comment by Wolffenstein** [comment]
Yep. Should be fine.
