### ISSUE TITLE
[NPC] Incandescent Fel Sparks at Throne of Kil-Jaeden should be named  Greater Fel-Sparks

### ISSUE THREAD

**Issue by Tereneckla** [Atlantiss/NetherwingBugtracker#7390]
[//]: # (Enclose links to things related to the bug using http://wowhead.com or any other TBC database.)
[//]: # (You can use screenshot ingame to visual the issue.)
[//]: # (Write your tickets according to the format:)
[//]: # ([Quest][Azuremyst Isle] Red Snapper - Very Tasty!)
[//]: # ([NPC] Magistrix Erona)
[//]: # ([Spell][Mage] Fireball)
[//]: # ([Npc][Drop] Ghostclaw Lynx)
[//]: # ([Web] Armory doesnt work)
[//]: # (To find server revision type `.server info` command in the game chat.)

**Description**: 
https://wowwiki.fandom.com/wiki/Greater_Fel-Spark
**Current behaviour**:
Incandescent Fel Sparks
**Expected behaviour**: 
Greater Fel-Sparks
**Server Revision**: 3510

**Comment by Godmatik** [comment]
Won't be changed
