### ISSUE TITLE
The "Piercing Ice" upgrade for the Blizzard spell does not work

### ISSUE THREAD

**Issue by Mystery32** [Atlantiss/NetherwingBugtracker#7391]
**Description**: The "Piercing Ice" upgrade in mage talents only works correctly for the spells "Frostbolt" and "Frost Nova"

**Current behaviour**: 3 points of improvement "Piercing Ice" in the talents of the mage increases the damage of the spell "Blizzard" level 1 from 200 to 208 units

**Expected behaviour**: 3 points of improvement "Piercing Ice" in the talents of the mage increases the damage of the spell "Blizzard" level 1 from 200 to **212** units

**Server Revision**:

**Comment by Tereneckla** [comment]
![image](https://user-images.githubusercontent.com/50233983/90320304-5c708380-df40-11ea-8463-9d5034f86fe5.png)

Works just fine for me.

**Comment by Mystery32** [comment]
In practice, I dealt damage with the level 1 spell "Blizzard" to one target with 3 points of improvement "Piercing Ice": the damage was exactly 208 units. The tooltip for the "Blizzard" spell also indicates 208 damage. But after all, from a base level of damage of 200 units, the damage should increase to: 200 * 1.06 = 212 units

**Comment by Mystery32** [comment]
In addition, within the framework of this topic, I want to say that the damage of the "Blazzard" spell is not affected by Bonus Spell Damage (BSP). My BSP is 5, but the damage of the "Blazzard" spell is still 208 units.

**Comment by Tereneckla** [comment]
You did discover something. But you got the wrong conclusion.
Talent and spelldamage does work on Blizzard. However currently they only increase the damage if each tick can deal more damage.

So currently damage increases on Blizzard work in steps of 8
