### ISSUE TITLE
[NPC] Fiendling Flesh Beast not turning hostile when hit by energizing beam

### ISSUE THREAD

**Issue by mn142** [Atlantiss/NetherwingBugtracker#7393]
[//]: # (Enclose links to things related to the bug using http://wowhead.com or any other TBC database.)
[//]: # (You can use screenshot ingame to visual the issue.)
[//]: # (Write your tickets according to the format:)
[//]: # ([Quest][Azuremyst Isle] Red Snapper - Very Tasty!)
[//]: # ([NPC] Magistrix Erona)
[//]: # ([Spell][Mage] Fireball)
[//]: # ([Npc][Drop] Ghostclaw Lynx)
[//]: # ([Web] Armory doesnt work)
[//]: # (To find server revision type `.server info` command in the game chat.)

**Description**: 
Fiendling Flesh Beasts, required for the quest [More than a Pound of Flesh] are all neutral (non-hostile) to the player. 

**Current behaviour**:
Fiendling Flesh Beast are all neutral even though they are getting beamed by the energizing beams.

**Expected behaviour**: 
Should turn hostile when hit by the energizing beam as described on wowhead. 
https://www.wowhead.com/quest=10671/more-than-a-pound-of-flesh#comments

**Server Revision**: 
3511

**Comment by Wolffenstein** [comment]
Fixed in rev 3532.
