### ISSUE TITLE
[Hunter] dropping [spell] auto shots or after a concussive shot

### ISSUE THREAD

**Issue by SwimzwithSharkz** [Atlantiss/NetherwingBugtracker#7394]
[//]: # (Enclose links to things related to the bug using http://wowhead.com or any other TBC database.)
[//]: # (You can use screenshot ingame to visual the issue.)
[//]: # (Write your tickets according to the format:)
[//]: # ([Quest][Azuremyst Isle] Red Snapper - Very Tasty!)
[//]: # ([NPC] Magistrix Erona)
[//]: # ([Spell][Mage] Fireball)
[//]: # ([Npc][Drop] Ghostclaw Lynx)
[//]: # ([Web] Armory doesnt work)
[//]: # (To find server revision type `.server info` command in the game chat.)

**Description**: 
My BM Hunter often drops auto shot or drops firing also after a concussive shot, to standing still, doing nothing. (This just occured 4 times on two mobs in hfp on a quest, so came to report it here. & I did not mouse over or target anything else to cause this. Once I believe it dropped auto shots right at mana gone also.)

https://tbc-twinhead.twinstar.cz/?spell=75

**Current behaviour**:
Hunter stops doing auto attack shots by bow with arrows, then is standing still. No shots fired.
**Expected behaviour**: 
Hunter should be firing till death of the mob or selecting another spell like Serpent Sting then return to auto shot spell.

**Server Revision**: 
2.4.3

**Comment by raethkcj** [comment]
Are you using any macros?

**Comment by SwimzwithSharkz** [comment]
not yet @raethkcj , am waiting to set them up near 70. so yeah, that's not it.

**Comment by raethkcj** [comment]
Just asking because I have not experienced any problems myself, and thought you might have a /stopcasting on concussive shot for whatever reason.

**Comment by Tereneckla** [comment]
Also having no luck recreating it

**Comment by SwimzwithSharkz** [comment]
aha, coz I came here just now @Tereneckla to write this again Did Occur at OOM last night, 
but got pinged so didn't write it here till now. 
Can yall read the toon's log to see what the mechanic jargon says? coz it was in Terokkar Forest in the village of 
Tuurem, on Gankerz, between 8 - 9 am server today.

**Comment by raethkcj** [comment]
I tried on the PTR by spamming mend pet until low mana, then starting to attack and using Skull of Impending Doom (drains your character's mana). My character kept on firing. Were you getting in melee range of the mob perhaps? What do your auto attack combat settings look like? Mine are as below and I'm having no issues:
![image](https://user-images.githubusercontent.com/7716908/90545544-6b2c8580-e14e-11ea-891a-22de6852d877.png)

**Comment by SwimzwithSharkz** [comment]
k thankz, 
mine is same, cept I added "auto self cast" now also.
[https://imgur.com/a/km3eY92](url)

**Comment by SwimzwithSharkz** [comment]
This isn't a game breaker bug, but it is annoying, it just happened again & in case the logs can be looked at,
it's Gankerz lvl 67 BM Hunter
in Netherstorm, on a Shaleskin Flayer mob, and the time was 06:57am 21 Aug 20. 
Just like 3 shots or even 2 b4 end of fight, was firing arrow, then dead still, dindunuffin. Had to reaim and shoot again.
TY
