### ISSUE TITLE
[NPC][Vendor] Malygen

### ISSUE THREAD

**Issue by redplasticface** [Atlantiss/NetherwingBugtracker#7395]
[//]: # (Enclose links to things related to the bug using http://wowhead.com or any other TBC database.)
[//]: # (You can use screenshot ingame to visual the issue.)
[//]: # (Write your tickets according to the format:)
[//]: # ([Quest][Azuremyst Isle] Red Snapper - Very Tasty!)
[//]: # ([NPC] Magistrix Erona)
[//]: # ([Spell][Mage] Fireball)
[//]: # ([Npc][Drop] Ghostclaw Lynx)
[//]: # ([Web] Armory doesnt work)
[//]: # (To find server revision type `.server info` command in the game chat.)

**Description**: Vendor NPC Malygen in Felwood doesn't sell all the TBC cooking recipes. https://tbcdb.com/?npc=2803

**Current behaviour**: She sells only one recipe like in Vanilla, Recipe: Monster Omelet.

**Expected behaviour**: She should sell in TBC 3 recipes for cooking, She should also sell: Recipe: Juicy Bear Burger and Recipe: Charred Bear Kabobs. And the stock should be infinite.

**Server Revision**: 3511

**Comment by Tereneckla** [comment]
These 3 recipes have been added in 2.4
The server is in 2.0
