### ISSUE TITLE
[Quest][The Ring of Blood] possible to finish in raid

### ISSUE THREAD

**Issue by m-hynek** [Atlantiss/NetherwingBugtracker#7396]
[//]: # (Enclose links to things related to the bug using http://wowhead.com or any other TBC database.)
[//]: # (You can use screenshot ingame to visual the issue.)
[//]: # (Write your tickets according to the format:)
[//]: # ([Quest][Azuremyst Isle] Red Snapper - Very Tasty!)
[//]: # ([NPC] Magistrix Erona)
[//]: # ([Spell][Mage] Fireball)
[//]: # ([Npc][Drop] Ghostclaw Lynx)
[//]: # ([Web] Armory doesnt work)
[//]: # (To find server revision type `.server info` command in the game chat.)

**Description**: 
Quests starting with https://tbcdb.com/?quest=9962 is possible to finish in raid group, which is super easy and just wrong.

**Current behaviour**: 
Can be done in raid group.

**Expected behaviour**: 
Quest is not flagged as complete if NPC is killed in raid group

**Server Revision**: 
3511

**Comment by Wolffenstein** [comment]
Fixed in rev 3523.
