### ISSUE TITLE
LW Drums cannot be used while shapeshifted

### ISSUE THREAD

**Issue by recreantus** [Atlantiss/NetherwingBugtracker#7398]
**Description**: 
Drums made from Leatherworking cannot be used in shapeshift form, despite them saying so on the tooltip.

**Current behaviour**:
https://www.youtube.com/watch?v=6CfVnzYwqFU
Video demonstration

**Expected behaviour**: 
As per the tooltip, you should be able to bang the drums while shapeshifted.

**Server Revision**: 
3511

**Comment by raethkcj** [comment]
This gets changed in [Patch 2.3](https://wow.gamepedia.com/Patch_2.3.0). Unfortunately I don't think they can change the tooltip because of the 2.4.3 client.

> * Increased the range at which you can gain leatherworking skill from crafting drums.
> * Removed the casting time from the Drums of Battle, Drums of Restoration, Drums of Speed, and Drums of War.
> * Slightly increased the radius of  [Drums of Panic].
> * Reduced the casting time of Drums of Panic and added a global cooldown equal to the casting time.
> * Reduced the faction required to obtain Drums of Battle and Drums of Panic.
> * Drums of Speed and Drums of Restoration are no longer world drop recipes, and can now be obtained from the Mag'har and Kurenai faction vendors with revered standing.
> * Drums can now be used while shapeshifted.

**Comment by recreantus** [comment]
> This gets changed in [Patch 2.3](https://wow.gamepedia.com/Patch_2.3.0). Unfortunately I don't think they can change the tooltip because of the 2.4.3 client.
> 
> > * Increased the range at which you can gain leatherworking skill from crafting drums.
> > * Removed the casting time from the Drums of Battle, Drums of Restoration, Drums of Speed, and Drums of War.
> > * Slightly increased the radius of  [Drums of Panic].
> > * Reduced the casting time of Drums of Panic and added a global cooldown equal to the casting time.
> > * Reduced the faction required to obtain Drums of Battle and Drums of Panic.
> > * Drums of Speed and Drums of Restoration are no longer world drop recipes, and can now be obtained from the Mag'har and Kurenai faction vendors with revered standing.
> > * Drums can now be used while shapeshifted.

All right, thanks for clearing it up!
