### ISSUE TITLE
Pair of Springpaw Lynxes following eachother

### ISSUE THREAD

**Issue by spizzo83** [Atlantiss/NetherwingBugtracker#74]
[//]: # (Enclose links to things related to the bug using http://wowhead.com or any other TBC database.)
[//]: # (You can use screenshot ingame to visual the issue.)
[//]: # (Write your tickets according to the format:)
[//]: # ([Quest][Azuremyst Isle] Red Snapper - Very Tasty!)
[//]: # ([NPC] Magistrix Erona)
[//]: # ([Spell][Mage] Fireball)
[//]: # ([Npc][Drop] Ghostclaw Lynx)
[//]: # ([Web] Armory doesnt work)

**Multiple Springpaw Lynxes pairs in Eversong woods are following each other**: 
![2018-09-23_003045](https://user-images.githubusercontent.com/31452363/45922403-842d4d00-becb-11e8-813b-c6c74df21dd9.jpg)

**Comment by Peglaa** [comment]
Blizzlike

**Comment by knasen88** [comment]
Should be a cub following not the other way around?

**Comment by Peglaa** [comment]
Wolf prolly goofed. I'll send him some proof and he'll fix it.
