### ISSUE TITLE
Windrunner Spire Missing/wrongfully placed NPCS, Ghostlands

### ISSUE THREAD

**Issue by Tenoutoften** [Atlantiss/NetherwingBugtracker#740]
**Description**: 
Deatholme Acolyte#16315(https://db.excalibur.ws/?npc=16315) missing at 12.52, 58.82 Ghostlands
Currently no Acolyt at this exact spot, however, there is a double stacked Deatholme Acolyte#16315(https://db.excalibur.ws/?npc=16315) on the road just beneath .

The missing one can be seen here: https://youtu.be/sXyLfw4HsqU?t=195

I'd expect one of the Acolyte's below should be placed on the road just above.

There is 3 Fallen Ranger's#16314(https://db.excalibur.ws/?npc=16314) suppose to be on the circle platform below the one you see as you just enter, seen here: https://youtu.be/sXyLfw4HsqU?t=225 currently missing all 3.

Appears to be one too many Deatholme Acolyte#16315(https://db.excalibur.ws/?npc=16315) at the road that appears here https://youtu.be/sXyLfw4HsqU?t=246 Netherwing has two standing still on this road, retail has 1. I expect this one to be on the road above as seen here(very briefly on the right): https://youtu.be/sXyLfw4HsqU?t=163

**Server Revision**: 
2072

**Comment by aresbrutus** [comment]
Fixed in one of the upcoming updates.
