### ISSUE TITLE
[Spell] Debuff "Evil Twin" prevents being summoned

### ISSUE THREAD

**Issue by Tereneckla** [Atlantiss/NetherwingBugtracker#7402]
[//]: # (Enclose links to things related to the bug using http://wowhead.com or any other TBC database.)
[//]: # (You can use screenshot ingame to visual the issue.)
[//]: # (Write your tickets according to the format:)
[//]: # ([Quest][Azuremyst Isle] Red Snapper - Very Tasty!)
[//]: # ([NPC] Magistrix Erona)
[//]: # ([Spell][Mage] Fireball)
[//]: # ([Npc][Drop] Ghostclaw Lynx)
[//]: # ([Web] Armory doesnt work)
[//]: # (To find server revision type `.server info` command in the game chat.)

**Description**: 
The debuff "Evil Twin" (Id 23445) is mentioned to prevent summons in some versions in the history of edits on wowwiki/gamepedia.
Those are the only mentions of that behavior and they are not based on anything.
**Current behaviour**:
Prevents being summoned by stones or warlocks
**Expected behaviour**: 
Doesn't prevent it
**Server Revision**: 3511

**Comment by raethkcj** [comment]
Test in Classic? This isn't really proof that it shouldn't prevent summons.

**Comment by raethkcj** [comment]
WoWWiki/Gamepedia (one is a copy of the other) said it in their oldest 2006 version:
https://wow.gamepedia.com/index.php?title=Evil_Twin&oldid=76791
https://wowwiki.fandom.com/wiki/Evil_Twin?oldid=76791
> Prevents you from being summoned by a Warlock.

As well as multiple wowhead comments:
https://classic.wowhead.com/item=18984/dimensional-ripper-everlook#comments:id=2684001:reply=1167073
> prevents you from being summoned by a warlock

https://classic.wowhead.com/item=18984/dimensional-ripper-everlook#comments:id=2684042
> No, it just makes it so you can't be summoned.

https://classic.wowhead.com/item=18986/ultrasafe-transporter-gadgetzan#comments:id=2714760
> Guys,
> I had 'Evil Twin' and no Warlocks could summon me.
> As soon as 'Evil Twin' was gone - summon away.
> Interesting the Summons used a shard, and the Warlocks thought the summon was sucessful, until I never showed up (and I got no message either)...

https://classic.wowhead.com/item=18986/ultrasafe-transporter-gadgetzan#comments:id=3071392
> When you have the 'Evil Twin' debuff you can't be summoned. It wears off upon death.

There's also one comment saying the opposite.
https://classic.wowhead.com/item=18984/dimensional-ripper-everlook#comments:id=3071376
> The speculation that the Evil Twin debuff pevents you from being summoned by a warlock is false. I'd used the ripper to go to Everlook and got the debuff while on my way to an Azuregos raid. One of the warlocks in the raid decided it would just be quicker to summon me, did, and the next moment I was standing in Azhara.
>
> I also took a mage portal out afterwards.
>
> The debuff does absolutely nothing. At most it is a tribute to Star Trek. I do have fun pretending that I'm "evil" while the debuff is on, though. lol!
