### ISSUE TITLE
[Core][PvP] Joining Battleground doesn't remove you from the queue.

### ISSUE THREAD

**Issue by tsuone** [Atlantiss/NetherwingBugtracker#7403]
[//]: # (Enclose links to things related to the bug using http://wowhead.com or any other TBC database.)
[//]: # (You can use screenshot ingame to visual the issue.)
[//]: # (Write your tickets according to the format:)
[//]: # ([Quest][Azuremyst Isle] Red Snapper - Very Tasty!)
[//]: # ([NPC] Magistrix Erona)
[//]: # ([Spell][Mage] Fireball)
[//]: # ([Npc][Drop] Ghostclaw Lynx)
[//]: # ([Web] Armory doesnt work)
[//]: # (To find server revision type `.server info` command in the game chat.)

**Description**: Battleground queue

**Current behaviour**: Joining battleground like Warsong Gulch doesn't remove you from the queue for other Battlegrounds: Eye of the Storm and Arathi Basin.

**Expected behaviour**: Joining Warsong Gulch, Arathi Basin and Eye of the Storm should remove you from the queue from other queued Battlegrounds (Arathi Basin, Eye of the Storm and Warsong Gulch).

`
This shouldn't remove you from the Alterac Valley queue.
`

**Server Revision**: 3511

**Comment by Godmatik** [comment]
IMO this is a quality of life feature that should remain, or else it will be difficult to get marks for inactive BGs.
