### ISSUE TITLE
Revantusk Village (hinterlands) inn is not registering as an inn (only in one small part of the building) (kara server)

### ISSUE THREAD

**Issue by Dahun22** [Atlantiss/NetherwingBugtracker#7404]
[//]: # (Enclose links to things related to the bug using http://wowhead.com or any other TBC database.)
[//]: # (You can use screenshot ingame to visual the issue.)
[//]: # (Write your tickets according to the format:)
[//]: # ([Quest][Azuremyst Isle] Red Snapper - Very Tasty!)
[//]: # ([NPC] Magistrix Erona)
[//]: # ([Spell][Mage] Fireball)
[//]: # ([Npc][Drop] Ghostclaw Lynx)
[//]: # ([Web] Armory doesnt work)
[//]: # (To find server revision type `.server info` command in the game chat.)

**Description**: 
I noticed today that the horde inn in Revantusk Village (hinterlands) wasn't acting like an inn (no rested bonus, no zzz on character portrait, no instant logout etc.) for the majority of the building, which seemed a little strange. The small balcony area does still register as an inn, however. Opened a ticket and the GM suggested I post here instead. Not a serious issue but wanted to let you guys know.

Thank you guys for the awesome server btw, it's lovely adventuring through tbc yet again.
**Current behaviour**:

**Expected behaviour**: 

**Server Revision**:

**Comment by Tereneckla** [comment]
Blizzlike, the resting area starts slightly above the ground.
Jump on a hammock or something
