### ISSUE TITLE
Thunderlord dire wolf has truesight icon but don't have truesight

### ISSUE THREAD

**Issue by babno** [Atlantiss/NetherwingBugtracker#7405]
![image](https://user-images.githubusercontent.com/244626/90434188-0106d880-e09b-11ea-9446-dc9e97884487.png)

**Comment by Tereneckla** [comment]
Detecting me just fine from miles away.
Obviously not when standing behind it or at its side.

**Comment by babno** [comment]
Truesight basically means stealth doesnt matter, so being behind them doesn't matter. Also as you can see I'm clearly infront of it.

**Comment by babno** [comment]
@Tereneckla

**Comment by Tereneckla** [comment]
No, they can't detect you from behind
https://wow.gamepedia.com/Stealth
However, they won't be able to see you when their backs are turned, so it is possible to sap truesight humanoids, but requires skill and perfect timing.

Anyways, I still cannot get into the same position you have there.
Either it just respawned or just ran back to its position which gave you a small window on non detection
