### ISSUE TITLE
Alterac Valley Capping All Towers and Killing Captain Removed Incorrect Resources

### ISSUE THREAD

**Issue by seitzcasey** [Atlantiss/NetherwingBugtracker#7408]
**Description**:
We took all 4 towers and killed enemy captain as alliance but Horde had 100 more resources than they should have. Neither faction had capped a mine.

**Current behaviour**:
Capping all 4 towers and killing the enemy faction captain resulted in the enemy losing 400 resources.

**Expected behaviour**:
Capping all 4 towers and killing the enemy faction captain resulted in the enemy losing 500 resources.

**Server Revision**: 
3517

**Comment by Godmatik** [comment]
Closing - will consolidate all outstanding AV issues into one thread now.
