### ISSUE TITLE
Spell power coefficients

### ISSUE THREAD

**Issue by GeorgieTragnar** [Atlantiss/NetherwingBugtracker#741]
I don't know if you have a hidden Issue or just with different tag/name so I create this one.

Because I have just started playing on beta this might be irrelevant, but I post this now anyway and also for an easy check up **(reason is that this might not be an issue for max ranks)**. I am not sure if this is related to orc racial Blood Fury not applying the spell damage bonus to the spells (character overview has updated +spell dmg value) or just spell power coefficients are just messed up for lower ranks. 

Exact Issue:

**Orc level 4 Blood Fury spell gives 11 spell damage, however the damage of Shadow bolt is not increased even though the shadow bolt base coefficient is 85.71% so shadow bolt should have its damage range increased to 22-27 (I have always assumed that decimal fraction is cut rather than rounded).**

> List of spell IDs and their assumed coefficient values from several sources (wiki history, EJ)
There were extensive issue research for Gummy's server, but I did not save those links and I am not sure if I could find them again :D
27209 - 85.71% 
27216 - 93,6%
27218 - 120%
27220 - 71.43%
27217 - 214.3%
30459 - 42.86%
6219 - 95.2%
30546 - 42.86%
30911 - 100%
27213 - 214.29%/142.86% Direct/DoT
27223 - 22%
27215 - 20%/65.3% - Direct/DoT
30545 - 115% 
30405 - 120%/?% Direct/DoT(could not find DoT coeff)
30910 - 200%
30912 - 42.86%
30414 - 19.5%
27222 - 80%
27265 - 96%
32231 - 71.43%
27243 - 120%/22% Direct/DoT
25368 - 110% pre2.3 is 120% 2.4.3 is 110%
34917 - 100%
25375 - 42.86%
25387 - 57%
25446 - 171% pre2.3 - 83.5% 2.4.3 
25467 - 80%
32996 - 42.86%
25222 - 100%
25235 - 42.86%
25213 - 85.71%
25364 - 71.43%
25218 - 30%
25331 - 16%
25384 - 85.71%/16.5% Direct/DoT
25308 - 42.85%
28275 - 0%
34866 - 21.4%
32546- 42.86%
33076 - 42.86%
38692 - 100%/0%
38697 - 81.43%
27079 - 42.86%
38704 - 142.86%
27085 - 76.19%
27074 - 42.86%
27087 - 13.57%
27082 - 21.28%
33938 - 115%/20%  Direct/DoT
27086 - 17.61%/10.96% Direct/DoT
33933 - 13.57%
27088 - 13.57%
33043 - 13.57%
33405 -10%
30482 - 0%
30451 - 71.43%
30455 - 14,29% (1.5/3.5 * 1/3 - normal damage calculation against frozen; one third against non-frozen)
32700 - 13.57% - base crit is 200%
27173 - 95.24% - it should tick 8 times
27180 - 42.86%
27179 - 5% per charge/block 
27137 - 42.86% 
27136 - 71.43% 
33072 - 42.86%
27138 - 42.86%
27139 - 19.05%
27170 - 20%/42.86% (first part is seal dmg second judgement)
31801 - 3.4% per tick (application after max stacks 2.2%)/42.86% judgement
27155 - 71.43% (judgement)
1H wep speed*9.2% 
2H wep speed*10.8%
Seal of Righteousness coefficients pre2.3
26986 - 100%
26985 - 57.1%
26988 - 15%/52%
26989 - 90%
26979 - 100%
26982 - 80%
26980 - 30%/70% Direct/DoT
27013 - 76%
27012 - 128%
26983 - 73% on lvl 70 scales with lvl (on lvl 52 only 26%)
33763 - 51.8%/34.29%  Direct/DoT
25396 - 85.71%
25420 - 42.86%
25423 - 125% (that is sum of all jumps - 71-36-18)
32594 - 285.7%
25449 - 79.4%
25442 - 125% (that is sum of all jumps - 71-36-18)
25454 - 42.86%
25464 - 42.86%
25457 - 15%/52% Direct/DoT
25489 - 10% per hit
25500 - 10% per hit
25533 - 16.67% per shot randomly also +1 dmg
25547 - 21.4%
25552 - 66.7%
25567 - 4.5% per tick
2894 ??? if any
2062 ??? if any
33736 ??? if any
source for coef values (these values are pre 2.3.2)
http://web.archive.org/web/20130209185426/http://elitistjerks.com/f15/t9363-damage_coefficients/
post 2.4.3
http://wowwiki.wikia.com/index.php?title=Spell_power_coefficient&diff=1549180&oldid=1549176
some coefficients are not present in the 2.4.3 wowwiki source so are used ones from pre2.3

**Comment by 0815Priester** [comment]
I don't think you get the full dmg coefficient for spells you have learned before LVL 20.

**Penalty Rules**
https://wow.gamepedia.com/index.php?title=Spell_power&direction=prev&oldid=298315#Penalty_Rules

**Comment by Neophrone** [comment]
U can calculate bonus damage gain from spell damage for direct casting spells (like Shadow bolt or Fireball) by yourself. Formula is x/3.5. Where is X - base cast time of the spell. 
For example: Base Shadow bolt[Rank 11] cast time is 3.0. So bonus dmg from spell damage is 3.0/3.5= 0.857.
But Rank 1 Shadow bolt has 1.7 cast time, so bonus damage should be 1.7/3.5=0.485. So with 11 SPD damage should be 18-23.
But even now Netherwing formula is incorrect. At lvl 70 with Destro talents and 1238 SPD rank 1 Shadow bolt dealing around 60 damage. But it should be 13(base SB rank 1 damage) + 0.485*1238 = 613 and this is even without Shadow and Flame talent bonus multiplier, curse of elements multiplier, Demon sacriface multiplier.
![wowscrnshot_111918_122744](https://user-images.githubusercontent.com/43533040/48701217-abb44380-ebf6-11e8-8887-ca9817d42894.jpg)

**Comment by 0815Priester** [comment]
you forgot the penalty in your calculation.

[Basic Coefficient] * [Downranking Penalty] * [Sub Level 20 Penalty] = [Effective Coefficient]

http://wow.allakhazam.com/wiki/spell_coefficient_(wow)

**Comment by Tereneckla** [comment]
Downranked shadowbolt at 70 had the expected damage for me.
