### ISSUE TITLE
[Item] Sublime Mystic Dawnstone costed 500 battle marks until 2.1

### ISSUE THREAD

**Issue by Tereneckla** [Atlantiss/NetherwingBugtracker#7410]
[//]: # (Enclose links to things related to the bug using http://wowhead.com or any other TBC database.)
[//]: # (You can use screenshot ingame to visual the issue.)
[//]: # (Write your tickets according to the format:)
[//]: # ([Quest][Azuremyst Isle] Red Snapper - Very Tasty!)
[//]: # ([NPC] Magistrix Erona)
[//]: # ([Spell][Mage] Fireball)
[//]: # ([Npc][Drop] Ghostclaw Lynx)
[//]: # ([Web] Armory doesnt work)
[//]: # (To find server revision type `.server info` command in the game chat.)

**Description**: 
![image](https://user-images.githubusercontent.com/50233983/90538050-523bc880-e17e-11ea-9f2b-bd416b016a9e.png)
https://wowwiki.fandom.com/wiki/Patch_2.1.0_(undocumented_changes)

**Current behaviour**:
Costs 100 [Halaa Battle Tokens](https://www.wowhead.com/item=26045/halaa-battle-token)
**Expected behaviour**: 
Costs 500  [Halaa Battle Tokens](https://www.wowhead.com/item=26045/halaa-battle-token)
**Server Revision**: 3515

**Comment by Wolffenstein** [comment]
Can't be fixed. The 500 token extended cost is no longer in dbc.
