### ISSUE TITLE
Wrong weapon sounds for certain weapon types.

### ISSUE THREAD

**Issue by Citano** [Atlantiss/NetherwingBugtracker#7411]
A thing I noticed when playing was that the weapon hit sound for some reason seem to be the 1h axe sound for multiple weapons.
I thought this was something wrong with my client and/or addons, but I have tried to reproduce this issue on a "different" project and I can't get this issue to occur over there.

An example: the Rattlecage Skeleton mobs at starter zone for Undead wield 1h swords, but when they melee you and their attacks hit/crit, it plays the 1h axe sounds. Same goes for the Vile Familiar imps at starter zone for Orc/Troll that wield 1h maces but plays 1h axe sounds upon hit/crit.
Just noticed that the Southshore Guard in Hillsbrad Foothills, whom also wield 1h swords, use the 1x axe sounds upon hit/crit.

This also seem to occur with players too and not just NPCs. 
I tested on some horde shaman using the lv.3 staff called "Long Bo Staff" and even that weapon produce the 1h axe sounds upon hit/crit. However, if I equipped another staff named  "Primitive Walking Stick", then I get the regular staff sounds upon hit/crit as expected.
On my horde hunter that has the 2h sword named "Polished Zweihander of the Monkey", it also produces 1h axe sounds upon hit/crit.

Since I cant reproduce these things on different TBC projects then I think this is not player-related but server-related in a way. Not sure what the exact pattern is that make these sound play wrong (since not all weapons of one type cause the wrong sounds) but hopefully someone can find out.

If possible, I can always record a video to show the examples from both Karazhan(Atlantiss) and other TBC projects if required.

**Comment by Wolffenstein** [comment]
Have you tried deleting your cache?

**Comment by Citano** [comment]
> Have you tried deleting your cache?

Can't believe I didn't think of that. Not sure how the cache managed to use axe sounds for everything for me.
Worked like a charm! Thanks! 👍

**Comment by Citano** [comment]
I have tried with a freshly downloaded client and it still occurs for me. No Addons, no Cache and no WTF.
And as noted earlier, its strange I can only reproduce this issue on Karazhan and not on other projects. Seems to be a bug on your servers.

The issue is certainly "open" and not "closed". (@Tereneckla )

**Comment by Wolffenstein** [comment]
Can't reproduce.
