### ISSUE TITLE
Quest item glow doesn't disappear after pickup

### ISSUE THREAD

**Issue by Justfor49** [Atlantiss/NetherwingBugtracker#7414]
[//]: # (Enclose links to things related to the bug using http://wowhead.com or any other TBC database.)
[//]: # (You can use screenshot ingame to visual the issue.)
[//]: # (Write your tickets according to the format:)
[//]: # ([Quest][Azuremyst Isle] Red Snapper - Very Tasty!)
[//]: # ([NPC] Magistrix Erona)
[//]: # ([Spell][Mage] Fireball)
[//]: # ([Npc][Drop] Ghostclaw Lynx)
[//]: # ([Web] Armory doesnt work)
[//]: # (To find server revision type `.server info` command in the game chat.)

**Description**: 
Quest item glow doesn't disappear after pickup:

1. A Question of Gluttony quest (https://www.wowhead.com/quest=9702/a-question-of-gluttony), discarded nutrients item glow doesn't disappear after pickup:

![nutrient](https://user-images.githubusercontent.com/69169443/90590692-30a70500-e1af-11ea-9c89-d0b735ee1183.jpg)

2. Same issue with "Restless Bones" for quest "Recover the Bones" (https://www.wowhead.com/quest=10030/recover-the-bones), the item glow remains after pickup: 

PRE PICKUP:
![bones1](https://user-images.githubusercontent.com/69169443/90722795-80f29580-e289-11ea-9bbd-ccdd02188993.jpg)

POST PICKUP (Glow remains): 
![bones0](https://user-images.githubusercontent.com/69169443/90722784-79cb8780-e289-11ea-814c-adea711b9dc1.jpg)

**Expected behaviour**: 
Item glow should disappear after pickup. Currently, the glow stays behind and shows where next spawn will be. 

**Server Revision**: 
3517

**Comment by Justfor49** [comment]
Same issue with "Restless Bones" for quest "Recover the Bones" (https://www.wowhead.com/quest=10030/recover-the-bones), the item glow remains after pickup: 

PRE PICKUP:
![bones1](https://user-images.githubusercontent.com/69169443/90722795-80f29580-e289-11ea-9bbd-ccdd02188993.jpg)

POST PICKUP (Glow remains): 
![bones0](https://user-images.githubusercontent.com/69169443/90722784-79cb8780-e289-11ea-814c-adea711b9dc1.jpg)

**Comment by Godmatik** [comment]
This applies to any quest object that has a "glow" effect.

Ravenous Flayer Eggs in Shadowmoon Valley are another example.

**Comment by Wolffenstein** [comment]
Fixed in rev 3674.
