### ISSUE TITLE
[Core] ".appear" command

### ISSUE THREAD

**Issue by tsuone** [Atlantiss/NetherwingBugtracker#7417]
[//]: # (Enclose links to things related to the bug using http://wowhead.com or any other TBC database.)
[//]: # (You can use screenshot ingame to visual the issue.)
[//]: # (Write your tickets according to the format:)
[//]: # ([Quest][Azuremyst Isle] Red Snapper - Very Tasty!)
[//]: # ([NPC] Magistrix Erona)
[//]: # ([Spell][Mage] Fireball)
[//]: # ([Npc][Drop] Ghostclaw Lynx)
[//]: # ([Web] Armory doesnt work)
[//]: # (To find server revision type `.server info` command in the game chat.)

**Description**: `.appear` command.

**Current behaviour**: Using `.appear` command to teleport to the player on the Arena makes you visible to other players when in GM mode.

**Expected behaviour**: Shouldn't make you visible to other players.

**Server Revision**: 3517

**Comment by danbopes** [comment]
It doesn't. It may remove the transparency debuff, but you're still hidden to players. You can always type `.gm vis` to check your current visible status (It's a hard flag server side).
