### ISSUE TITLE
[NPC] Moroes - Vanish with threat drop

### ISSUE THREAD

**Issue by wjutterback** [Atlantiss/NetherwingBugtracker#7423]
**Description**: Moroes seems to have a problem with his threat table immediately after vanishing. It's not gouge related, e.g. (MT is gouged, then he goes to 2nd threat) which seems to be working properly. The problem occurs immediately after vanish. We killed him last Friday without issue (all mechanics working as intended). The adds that accompanied him were Lady Keira Berrybuck, Baron Rafe Dreuger, Lord Robin Daris, Lord Crispin Ference. This was the only other difference noticed from our previous kill and are included for completion's sake.

**Current behaviour**: Moroes will vanish, garrote a player, and then he will stay on them until they are dead before he'll switch target to someone else, potentially not a tank. We tried multiple methods to test it: a rogue vanished shortly before his vanish, was the garrote target and Moroes still stayed on him, Warlocks would Soul Shatter on a vanish and would still be #1 threat, it is almost as if he has a massive threat drop on tanks or a temporary threat drop on all players. It seems somewhat similar to Veras Darkshadow from the Illidari Council fight.

**Expected behaviour**: Moroes should vanish, garrote a player, then return to the player who is first on aggro.

**Server Revision**: 3517

**Comment by Godmatik** [comment]
This must've been resolved at some point.

No reports of this happening ever on Netherwing realm this past year.

Closing.
