### ISSUE TITLE
Grand warlock Netherkurse shadow fissure is double hitting and doing ~5x intended damage

### ISSUE THREAD

**Issue by babno** [Atlantiss/NetherwingBugtracker#7426]
![image](https://user-images.githubusercontent.com/244626/90790852-862a0180-e2d6-11ea-9ae2-3256eaf4b390.png)
It looks like the first tic is as it should be, but there's a second tic that hits at the same time for way too much damage.

https://wowwiki.fandom.com/wiki/Grand_Warlock_Nethekurse

**Comment by Wolffenstein** [comment]
Fixed in rev 3523.
