### ISSUE TITLE
Dreadbone Skeleton#16303 resetting despite repeatedly struck.

### ISSUE THREAD

**Issue by Tenoutoften** [Atlantiss/NetherwingBugtracker#743]
**Description**: 
Dreadbone Skeleton#16303(https://db.excalibur.ws/?npc=16303) resets even though I am repeatedly hitting it: https://www.youtube.com/watch?v=B_QM03lM99g&feature=youtu.be

.gps & .npc info
https://i.gyazo.com/2db461550520490053ea3ac7572cfa03.png
https://i.gyazo.com/00b2807e43b71162e5bcbe4fc56feed3.png

**Expected behaviour**: 
The NPC is expected to not reset when it is repeatedly hit.

**Server Revision**: 
2072

**Comment by Wolffenstein** [comment]
It's because this one is a summon of the Necromancer next to him. The necromancer evaded so the Skeleton did too. Intended.
