### ISSUE TITLE
[Botanica] Thorngrin the tender level 73, should be 72

### ISSUE THREAD

**Issue by babno** [Atlantiss/NetherwingBugtracker#7433]
![image](https://user-images.githubusercontent.com/244626/90942246-f32abd80-e3e2-11ea-884b-a1db6e3a0036.png)
https://wowwiki.fandom.com/wiki/Thorngrin_the_Tender

pretty sure all bosses in level 70 dungeons should be 72.

**Comment by Wolffenstein** [comment]
Fixed in rev 3523.
