### ISSUE TITLE
Blackheart the Inciter - mind control

### ISSUE THREAD

**Issue by Godmatik** [Atlantiss/NetherwingBugtracker#7434]
The mind control ability done by Blackheart on a tree of life druid, the druid does nothing except go melee and auto-attacks. No other abilities used.

**Comment by Godmatik** [comment]
Same result from being mind controlled vs Pantheon (final fight in Mech)

**Comment by Godmatik** [comment]
Still occurs, also happens during any other scripted MC (such as the Nether Scryers in Tempest Keep)

**Comment by Wolffenstein** [comment]
Fixed in rev 3944.
