### ISSUE TITLE
Socrethar's Shadow Quest Mob, Silroth is bugged.

### ISSUE THREAD

**Issue by Ashfall7x** [Atlantiss/NetherwingBugtracker#7435]
**Description**: Silroth constantly falling from the sky to the underground.

![image](https://user-images.githubusercontent.com/46924400/90945909-bb4a6700-e430-11ea-88ea-19e90a6fc175.png)

**Comment by Godmatik** [comment]
Fixed at some point I guess? 

I watched him for a while and do not see this happening, also have not heard of anyone mentioning this in past year on Netherwing.

Closing.
