### ISSUE TITLE
0

### ISSUE THREAD

**Issue by alanparrish** [Atlantiss/NetherwingBugtracker#7439]
0

**Comment by alanparrish** [comment]
any fix planned BEFORE going to the patch where it is being nerfed? shouldnt be too hard to adjust the value and every day it is not being updated time in 2.0 is lost where the item is insanely powerful

**Comment by raethkcj** [comment]
Spinesever was added in 2.3.0, and nerfed in 2.3.2. 

https://wow.gamepedia.com/index.php?title=Spinesever_(weapon)&direction=next&oldid=981189

There is no time when it should have 2.3.0 stats on Karazhan.
