### ISSUE TITLE
[NPC] Lost Soul

### ISSUE THREAD

**Issue by Dusky1** [Atlantiss/NetherwingBugtracker#744]
I cant attack npc Lost Soul 7lv rare patroling near Brill.

Rev.: 2072

**Comment by wtRCH** [comment]
When I did ".npc info" on it. It showed me "Please target a creature" or something like this.

**Comment by Dusky1** [comment]
Yea. Same for .gps

**Comment by aresbrutus** [comment]
https://gfycat.com/ZanyDisastrousCurlew

Works for me. You sure it was not due to some client bug?

**Comment by Wolffenstein** [comment]
Should be fine
