### ISSUE TITLE
[Karazhan] Servant Access Door

### ISSUE THREAD

**Issue by Drayo** [Atlantiss/NetherwingBugtracker#7441]
[//]: # (Enclose links to things related to the bug using http://wowhead.com or any other TBC database.)
[//]: # (You can use screenshot ingame to visual the issue.)
[//]: # (Write your tickets according to the format:)
[//]: # ([Quest][Azuremyst Isle] Red Snapper - Very Tasty!)
[//]: # ([NPC] Magistrix Erona)
[//]: # ([Spell][Mage] Fireball)
[//]: # ([Npc][Drop] Ghostclaw Lynx)
[//]: # ([Web] Armory doesnt work)
[//]: # (To find server revision type `.server info` command in the game chat.)

**Current behaviour**: 

**- The Servant Access Doors [184281] "Locked" Status is green to everybody, allowing raids to open it anytime and skip the entire lower floor.**

- A little less impactful: The Side Entrance Door [184275] seems to unlock after clearing Opera, instead of someone passing the Trigger.

Servant Access state when no bosses have been killed: 
![image](https://user-images.githubusercontent.com/23145811/90967524-96adc800-e4e0-11ea-99c4-2090d63a46aa.png)

**Expected behaviour**: 

- The Servant Access Door [184281] and the Side Entrance Door [184275] should unlock by passing a trigger between the Opera Hall and the Broken Staircase.

Trigger:
![image](https://user-images.githubusercontent.com/23145811/90967496-43d41080-e4e0-11ea-82a3-4b2d5ecde7ba.png)

**Server Revision**: 3515

**Comment by Wolffenstein** [comment]
Fixed in rev 3659.
