### ISSUE TITLE
Freez the game client after accept quest with a timet for execution

### ISSUE THREAD

**Issue by terekhovkg** [Atlantiss/NetherwingBugtracker#7443]
**Description**: 
All quests that have a timer for execution freez the game client (the client freezes and only os restart helps). For example, quest Freedom for All Creatures

**Comment by raethkcj** [comment]
It's a bug with the addon QuestHelper, disable it when you do timed quests.

**Comment by terekhovkg** [comment]
@raethkcj Oh well, i will try this, thank you
