### ISSUE TITLE
[Quest] The Affray 

### ISSUE THREAD

**Issue by Roak** [Atlantiss/NetherwingBugtracker#7444]
[//]: # (Enclose links to things related to the bug using http://wowhead.com or any other TBC database.)
[//]: # (You can use screenshot ingame to visual the issue.)
[//]: # (Write your tickets according to the format:)
[//]: # ([Quest][Azuremyst Isle] Red Snapper - Very Tasty!)
[//]: # ([NPC] Magistrix Erona)
[//]: # ([Spell][Mage] Fireball)
[//]: # ([Npc][Drop] Ghostclaw Lynx)
[//]: # ([Web] Armory doesnt work)
[//]: # (To find server revision type `.server info` command in the game chat.)

**Description**: Lvl 30 Warrior quest to obtain Berserker stance, consisting of chain killing NPCs.

**Current behaviour**: NPCs spawn with random intervals, even as short as spawning in doubles (resulting in a swarm). Sometimes the quest spawns 2 NPCs at once in every wave.

**Expected behaviour**: NPCs dont spawn 2 at the time and there are actual windows to kill them. If there are 6 NPCs in 4 seconds, this quest is impossible for lvl 30 player character to complete. (Irrelevant for high level chars who AoE it down with 1 skill)

**Server Revision**:

**Comment by Tereneckla** [comment]
Always had 20 seconds between 2 Challengers. Plenty of time to kill them.

**Comment by Roak** [comment]
Didnt. Had to restart the quest 5 times. One time i had 6 NPCs as i was using second Thunder clap and they were spawning 2 at the same time. As i wrote ticket and tried it one last time, i finally had them come 1 by 1 and had even downtime between them (safe for last who joined before finishing second to last one). 4 attempts before quest didnt work properly (As i mentioned - sometimes smaller windows, sometimes double spawn, once 3 double spawns with small window).
