### ISSUE TITLE
[Item] Xi'ri's Gift and Scryer Bloodgem interaction.

### ISSUE THREAD

**Issue by danelmore** [Atlantiss/NetherwingBugtracker#7446]
[//]: # (Enclose links to things related to the bug using http://wowhead.com or any other TBC database.)
[//]: # (You can use screenshot ingame to visual the issue.)
[//]: # (Write your tickets according to the format:)
[//]: # ([Quest][Azuremyst Isle] Red Snapper - Very Tasty!)
[//]: # ([NPC] Magistrix Erona)
[//]: # ([Spell][Mage] Fireball)
[//]: # ([Npc][Drop] Ghostclaw Lynx)
[//]: # ([Web] Armory doesnt work)
[//]: # (To find server revision type `.server info` command in the game chat.)

**Description**: 
the two trinkets cool each other down for the entire duration instead of the 15 seconds. there is a closed ticket from netherwing where this was fixed.
**Current behaviour**:
the two trinkets cool each other down for the entire duration instead of the 15 seconds. 1 cools the other down for the entire duration even though it shows it is ready to use after 15 seconds.
**Expected behaviour**: 
should be able to use the other trinket after the 15 second cooldown

**Server Revision**:

**Comment by tsuone** [comment]
Bump

**Comment by Wolffenstein** [comment]
Fixed in rev 3585.

**Comment by Wolffenstein** [comment]
Reverted

**Comment by Godmatik** [comment]
How come? Some proof from TBC retail emerged that says otherwise?

**Comment by Wolffenstein** [comment]
It was reverted because the fix caused issues with certain spell cooldowns. It should be fixed in rev 3587.
