### ISSUE TITLE
attunement the huntsman cleave hits ~3-4 times more than it should, 1 shotting melee

### ISSUE THREAD

**Issue by babno** [Atlantiss/NetherwingBugtracker#7448]
![image](https://user-images.githubusercontent.com/244626/91067651-32cef080-e601-11ea-8915-43c9813a88dd.png)
Here you can see it hits for 9446 on this server.

https://youtu.be/7xeqvc1DUc0?t=356
Here you see it hits the druid for 2767.

If you want to overtune fights that's a defensible choice, but turning mechanics that should just stress healers a bit into literally 1 shotting people is a whole different thing.

**Comment by Tereneckla** [comment]
You are comparing upper end here to lower end retail.

Retail: ~2700-4000
Here: 6500-9500

The cleave is easily avoidable by standing behind the boss.

**Comment by babno** [comment]
As you noted in my other post, cleave is 360, so no it can't be avoided by standing behind the boss.

**Comment by Tenoutoften** [comment]
@babno Cleave is 360 degrees around the target being cleaved, not the NPC doing the cleave. So if you are too close to whoever is getting cleaved you will also be cleaved - If you stand max range you will avoid it.

**Comment by Godmatik** [comment]
If you stand behind the boss and max melee range you won't get cleaved
