### ISSUE TITLE
Deathblow to the Legion/Turning Point - NPC's bug Socrethar

### ISSUE THREAD

**Issue by radioslave** [Atlantiss/NetherwingBugtracker#7449]
[//]: # ([Quest][Azuremyst Isle] Red Snapper - Very Tasty!)
https://www.wowhead.com/quest=10409/deathblow-to-the-legion
https://www.wowhead.com/quest=10507/turning-point#criteria-of
[//]: # NPC's
Kaylaan The Lost & Socrethar
**Description**: 
Socrethar attempts to bring in Kaylaan the lost which bugs out causing the event to stop. The NPC's wont move and need to be killed by the fire from a pulled Wrath Lord. They still dont generally reset properly as Kaylaan wont move rendering Socrethar un-engagable 

**Server Revision**: 
Karazhan

**Comment by grand-baboon** [comment]
Having the same issues. To provide more detail: 

If the quest is functional (after a server restart), Adyen can be interacted with and the quest started. He'll walk up to the platform with Socrethar and begin the conversation. After Socrethar says, _"Yes, let's settle this....",_ the quest stops. The boss will be an invalid target for about 30 sec to 1 min, and then he can be attacked.

At this point if the quest is failed (group wiping), Socrethar will reset to his normal position. Adyen, however, will bug out on the platform. He cannot be interacted with. Socrethar will become an invalid target. At this point groups have been able to get Adyen killed by pulling surrounding mobs to him. This restarts the quest. 

If a group is successful in killing Socrethar, Ayden will still bug on the platform. Again, once he bugs, he cannot be interacted with. 

I've also found him wanting Marks at the portal for some reason. 

![edit2](https://user-images.githubusercontent.com/70199752/91156015-485d1c80-e6cc-11ea-89e2-89cdd2ea9b63.jpg)
![edit1](https://user-images.githubusercontent.com/70199752/91156003-45622c00-e6cc-11ea-8946-f0c8ea9ed9f0.jpg)

**Comment by Godmatik** [comment]
#9162
