### ISSUE TITLE
[NPC] Silithid Swarmer

### ISSUE THREAD

**Issue by totaemoeggerli** [Atlantiss/NetherwingBugtracker#745]
[//]: # (Enclose links to things related to the bug using http://wowhead.com or any other TBC database.)
[//]: # (You can use screenshot ingame to visual the issue.)
[//]: # (Write your tickets according to the format:)
[//]: # ([Quest][Azuremyst Isle] Red Snapper - Very Tasty!)
[//]: # ([NPC] Magistrix Erona)
[//]: # ([Spell][Mage] Fireball)
[//]: # ([Npc][Drop] Ghostclaw Lynx)
[//]: # ([Web] Armory doesnt work)

**Description**: 
[Silithid Swarmer](https://www.wowhead.com/npc=3252/silithid-swarmer#comments) sacrifices [Silithid Swarm](https://www.wowhead.com/npc=4196/silithid-swarm) and heals to 100% life.

**Current behaviour**:
Silithid Swarmer sacrifices Silithid Swarm and heals to 100% life.
https://gfycat.com/BareRemarkableIbex

**Expected behaviour**: 
Silithid Swarmers shouldn't use this ability. However the rare [Silithid Harvester](https://www.wowhead.com/npc=3253/silithid-harvester#comments) should use this ability (didn't test if it odes or not).

**Server Revision**: 
2072

**Comment by totaemoeggerli** [comment]
forgot about important wowhead comment: 
By DrCheis (49,483 – 6·36·409) on 2007/06/19 (Patch 2.1.2)
`This Silithid summons Harvester Swarm
http://www.wowhead.com/?npc=5409#go-to-comment-106871
They function just like regular Silithid Sarms, but they are much larger than the ones found in the Barrens. At low health, the Silithid Harvester will sacrifice one of the Harvester Swarms, bringing itself back to full health. The best way to prevent this from happening is to kill the Harvester Swarms. Melee damage reflectors such as Thorns work best for this purpose.`

**Comment by Evolvee** [comment]
rev xdd
