### ISSUE TITLE
Macro to join bgs not working after recently exiting bg

### ISSUE THREAD

**Issue by babno** [Atlantiss/NetherwingBugtracker#7451]
So I made a macro

.join av
.join ab
.join eots

It works fine, except when I have recently finished a bg. For ~2 minutes after I get this

![image](https://user-images.githubusercontent.com/244626/91177252-6a957100-e6b1-11ea-9f00-51adf735205c.png)

If I manually type out the command it works fine.

**Comment by raethkcj** [comment]
This is because your client is tying to send chat messages to the /bg channel, and you are not in a battleground. Send your chat messages to say instead:

```
/s .join ws
/s .join ab
/s .join eots
```
