### ISSUE TITLE
enchant weapon major spellpower

### ISSUE THREAD

**Issue by danelmore** [Atlantiss/NetherwingBugtracker#7453]
[//]: # (Enclose links to things related to the bug using http://wowhead.com or any other TBC database.)
[//]: # (You can use screenshot ingame to visual the issue.)
[//]: # (Write your tickets according to the format:)
[//]: # ([Quest][Azuremyst Isle] Red Snapper - Very Tasty!)
[//]: # ([NPC] Magistrix Erona)
[//]: # ([Spell][Mage] Fireball)
[//]: # ([Npc][Drop] Ghostclaw Lynx)
[//]: # ([Web] Armory doesnt work)
[//]: # (To find server revision type `.server info` command in the game chat.)

**Description**: drop rate has to be wrong

**Current behaviour**:kill closed to 400 mobs per mob info 70-71 bash'ir spell theif with no drop, been above 350 since i started farming it.

**Expected behaviour**: 2% drop rate, should've dropped by now, believe the decimal is in the wrong place making it .2%

**Server Revision**:

**Comment by Drayo** [comment]
lol ... RIP my man

On Patch 2.0 this guy drops it: https://www.wowhead.com/npc=20614/razaani-spell-thief
