### ISSUE TITLE
Beast mastery spells

### ISSUE THREAD

**Issue by Danouche** [Atlantiss/NetherwingBugtracker#7455]
[//]: # (Enclose links to things related to the bug using http://wowhead.com or any other TBC database.)
[//]: # (You can use screenshot ingame to visual the issue.)
[//]: # (Write your tickets according to the format:)
[//]: # ([Quest][Azuremyst Isle] Red Snapper - Very Tasty!)
[//]: # ([NPC] Magistrix Erona)
[//]: # ([Spell][Mage] Fireball)
[//]: # ([Npc][Drop] Ghostclaw Lynx)
[//]: # ([Web] Armory doesnt work)
[//]: # (To find server revision type `.server info` command in the game chat.)

**Description**: 
Revive pet, feed pet
**Current behaviour**:
I can't learn revive pet and feed pet from trainer
**Expected behaviour**: 

**Server Revision**:

**Comment by Tereneckla** [comment]
You learn them from the quest that's the direct followup of your tame quest.
