### ISSUE TITLE
/who command broken

### ISSUE THREAD

**Issue by rschinkoeth** [Atlantiss/NetherwingBugtracker#7456]
[//]: # (Enclose links to things related to the bug using http://wowhead.com or any other TBC database.)
[//]: # (You can use screenshot ingame to visual the issue.)
[//]: # (Write your tickets according to the format:)
[//]: # ([Quest][Azuremyst Isle] Red Snapper - Very Tasty!)
[//]: # ([NPC] Magistrix Erona)
[//]: # ([Spell][Mage] Fireball)
[//]: # ([Npc][Drop] Ghostclaw Lynx)
[//]: # ([Web] Armory doesnt work)
[//]: # (To find server revision type `.server info` command in the game chat.)

**Description**: 
if you enter /who mage 70 shattrath a list of players should come up in chat, also reflected in the social tab under the who pane. however if you enter said command, it just shows random people- not the filtered list you expect from the command.

**Current behaviour**:
broken /who list, cause it's obviously not filtered correctly

**Expected behaviour**: 
filtered list of people that match the criteria you entered

**Server Revision**:

**Comment by Tereneckla** [comment]
If you want to find the class mage you have to search for c-mage
