### ISSUE TITLE
Disconnect on Alterac Valley BG (Karazhan)

### ISSUE THREAD

**Issue by ChekistNSK** [Atlantiss/NetherwingBugtracker#7458]
I got disconnect every time i take our goldmine as Horde on Alterac Valley (at the begin of battle)

Server: Karazhan

// warlock

**Comment by ChekistNSK** [comment]
Not only me get DC:
https://imgur.com/a/a7VCDXn

**Comment by tsuone** [comment]
Duplicate. Copied your issue content to the main issue.
