### ISSUE TITLE
Reputation in Eastern Plaguelands is not given to Alliance fractions (Karazhan)

### ISSUE THREAD

**Issue by carcin** [Atlantiss/NetherwingBugtracker#7459]
[//]: # (Enclose links to things related to the bug using http://wowhead.com or any other TBC database.)
[//]: # (You can use screenshot ingame to visual the issue.)
[//]: # (Write your tickets according to the format:)
[//]: # ([Quest][Azuremyst Isle] Red Snapper - Very Tasty!)
[//]: # ([NPC] Magistrix Erona)
[//]: # ([Spell][Mage] Fireball)
[//]: # ([Npc][Drop] Ghostclaw Lynx)
[//]: # ([Web] Armory doesnt work)
[//]: # (To find server revision type `.server info` command in the game chat.)

**Description**: 
Quests in Chillwind Camp (cauldrons for example) should give rep for all Alliance fractions. But it doesn't give any rep to them. It does give rep only to Argent Dawn.

**Current behaviour**:

**Expected behaviour**: 
Rep for Alliance should be split between all Ali fractions

**Server Revision**: 3519

**Comment by Godmatik** [comment]
Was fixed several months ago
