### ISSUE TITLE
[NPC][LOOT]Wendigo in Dun Morogh

### ISSUE THREAD

**Issue by Dekirayne** [Atlantiss/NetherwingBugtracker#746]
[//]: # (Enclose links to things related to the bug using http://wowhead.com or any other TBC database.)
[//]: # (You can use screenshot ingame to visual the issue.)
[//]: # (Write your tickets according to the format:)
[//]: # ([Quest][Azuremyst Isle] Red Snapper - Very Tasty!)
[//]: # ([NPC] Magistrix Erona)
[//]: # ([Spell][Mage] Fireball)
[//]: # ([Npc][Drop] Ghostclaw Lynx)
[//]: # ([Web] Armory doesnt work)

**Description**: 
Wendigos in Dun Morogh cave seem to have a much much lower drop chance for linen cloth.
**Current behaviour**:
I tried both Wendigos in dun morogh and defias humanoids in elwyn forests since they both have 30% drop rate and the defias dropped much more linen than wendigos.
**Expected behaviour**: 
Should be the same drop chance, since i was rly farming them for quite a long time. Maybe it was just very bad luck.
**Server Revision**:

**Comment by aresbrutus** [comment]
Need proof.

Retail data:
https://i.imgur.com/G2IacvN.png
https://i.imgur.com/Di92EOk.png

**Comment by Wolffenstein** [comment]
It was just bad luck, I simulated 10000 drops and it seems in line with every other mob that uses global loot for it.
