### ISSUE TITLE
Heroism(Ally Bloodlust) and Power Infusion(Priest Buff) not stacking

### ISSUE THREAD

**Issue by KevgenPrimus** [Atlantiss/NetherwingBugtracker#7460]
[//]: # (Enclose links to things related to the bug using http://wowhead.com or any other TBC database.)
[//]: # (You can use screenshot ingame to visual the issue.)
[//]: # (Write your tickets according to the format:)
[//]: # ([Quest][Azuremyst Isle] Red Snapper - Very Tasty!)
[//]: # ([NPC] Magistrix Erona)
[//]: # ([Spell][Mage] Fireball)
[//]: # ([Npc][Drop] Ghostclaw Lynx)
[//]: # ([Web] Armory doesnt work)
[//]: # (To find server revision type `.server info` command in the game chat.)

**Description**: 
^^Title
**Current behaviour**:
It overwrites the existing buff to apply the other; remember it stackng on horde side
**Expected behaviour**: 
they shouldnt stack apparently
**Server Revision**:

**Comment by Godmatik** [comment]
It's intended not to stack

https://wowwiki.fandom.com/wiki/Power_Infusion
