### ISSUE TITLE
[Pets] Pets don't always melee attack targets when send to attack targets

### ISSUE THREAD

**Issue by eri1997** [Atlantiss/NetherwingBugtracker#7463]
[//]: # (Enclose links to things related to the bug using http://wowhead.com or any other TBC database.)
[//]: # (You can use screenshot ingame to visual the issue.)
[//]: # (Write your tickets according to the format:)
[//]: # ([Quest][Azuremyst Isle] Red Snapper - Very Tasty!)
[//]: # ([NPC] Magistrix Erona)
[//]: # ([Spell][Mage] Fireball)
[//]: # ([Npc][Drop] Ghostclaw Lynx)
[//]: # ([Web] Armory doesnt work)
[//]: # (To find server revision type `.server info` command in the game chat.)

**Description**:  Pets seems to get stuck slightly outside of attack range staring the target instead of attacking them. Happens with any mob in the world or raids dungeons .

**Current behaviour**: Pets do this : https://imgur.com/a/ThfHq9N

**Expected behaviour**: I send pet to attack the target. Pet attacks the target.

**Server Revision**: 3519

**Comment by raethkcj** [comment]
I'm also experiencing this on Netherspite.

**Comment by rustwo** [comment]
Please look into this, it is happening very frequently these days.

I suspect that it might be a Z-axis issue, because it is most common against bosses that stand on a dais. Vashj and Solarian are 2 such bosses and pets often bug and stand still outside of melee range against those two. Netherspite also has a dais.

Even calling pet back and sending it back out does not consistently fix the issue. Pets seem to have to return completely to idle next to the player before the /petattack command can be issued and obeyed.

**Comment by eri1997** [comment]
I'd also add Hydros to that list and even Gruul from some positions. Might have smth to do with different altitudes . You send pet in to attack and it gets stuck in attack animation outside the boss hitbox like its trying to attack the target but it can't.Happens very frequently and it's very annoying on some fights

**Comment by rustwo** [comment]
Yes Z-axis appears to have a strong correlation with this problem. I noticed it even on Gruul trash when an ogre was being tanked on the wall where the floor slopes up after HKM's room.

It also seems to bug sometimes when the mob has an ability with CC that hits the pet, like a knockback. The pet will stop attacking after getting hit.

Also mobs with big hit boxes like the Crystalcore trash mobs in TK seem to be problematic, pets can refuse to go into melee range against them no matter how many times you recall and send back in.

**Comment by rustwo** [comment]
Further testing seems to show that ranged pets (like Wind Serpent) are able to get around this bug. I am guessing that rather than getting stuck out of range trying to execute a melee attack like Claw, they are able to use Lightning Breath and break their AI routine out of a loop it's stuck in. They are then able to move into melee and do normal damage.

**Comment by rustwo** [comment]
Never mind on that last comment. Seems that Wind Serpents still suffer from this bug, even while using their lightning breath. They will stand outside of melee and use their breath but won't move in to get auto attacks off.

Still seems to be mainly happening in situations with Z-axis differences, like Solarian's platform.

**Comment by eri1997** [comment]
Beginning to doubt its just Z-axis related today my pet refused to attack while being inside the mana drain birds range circle  in alar's room. Extremely annoying bug. Also pet randomly stop attacking while chasing now for some reason happened a couple of times on Hydros idk wtf is even happening anymore pets are completely fked

**Comment by raethkcj** [comment]
Hydross does have a "platform" with subtle elevation changes, and those mana birds are flying, so it could still be Z-axis for whatever reason.

**Comment by eri1997** [comment]
Today my pet didn't didn't attack on Prince and opera on Karazhan. Both have no platforms so that should confirm it's at least not just a Z-axis problem

**Comment by eri1997** [comment]
@tsuone Here is proff change tags please and get smb to fix it please. Raveger on the clip can't attack the boss for no reason. Happens every situation imaginable but most frequently when hunter and boss aren't on the same height level or on big hitbox targets.Very frequent and super annoying bug. Very annoying to "fix" your pet too mid fight you either have to go melee and drag your pet inside targets hitbox which is big yikes midfights or just spam pull back and attack in hopes of maybe it decides to attack this time. Idk how this bug suddenly shows up since Karazhan launch and never once happened in NW 
https://clips.twitch.tv/QuaintColorfulLarkRickroll

**Comment by Wolffenstein** [comment]
Reopen or make a new issue if it still breaks after rev 3576.

**Comment by Wurlington** [comment]
Still occuring especially on rapid movements of target.. For instance on Illidari Council when moving out of aoe pets will not follow all the way and wont autoattack until you pull the pet all the way back to your side or tank has to back pedal a bit so the pets register and actually get back in to auto attack

**Comment by Wolffenstein** [comment]
When exactly did you test it? It only went live yesterday.
