### ISSUE TITLE
[Quest] [Blade's Edge Mountains] Creating the Pendant

### ISSUE THREAD

**Issue by InsertLink** [Atlantiss/NetherwingBugtracker#7464]
[//]: # (Enclose links to things related to the bug using http://wowhead.com or any other TBC database.)
[//]: # (You can use screenshot ingame to visual the issue.)
[//]: # (Write your tickets according to the format:)
[//]: # ([Quest][Azuremyst Isle] Red Snapper - Very Tasty!)
[//]: # ([NPC] Magistrix Erona)
[//]: # ([Spell][Mage] Fireball)
[//]: # ([Npc][Drop] Ghostclaw Lynx)
[//]: # ([Web] Armory doesnt work)
[//]: # (To find server revision type `.server info` command in the game chat.)

**Description**: 
According to wowhead (https://www.wowhead.com/item=30704/ruuanok-claw) the drop rate of the claw needed to complete this quest is beetween 37% and 69%.
**Current behaviour**: 
The claw doesn't drop from the mobs at all, having killed at least 20, with the rates shown in wowhead should be more than enough for the quest, only managed to obtain one claw from the Ruuan'ok Matriarch (https://www.wowhead.com/npc=20211/ruuanok-matriarch) which is shown to have the lowest drop rate of the item.

**Expected behaviour**: 
Killing several enemies should yield enough claws to complete the quest.

**Server Revision**:

**Comment by Tereneckla** [comment]
The chances all around are ~30-33%
