### ISSUE TITLE
Not teleported from eots GY if you lose control

### ISSUE THREAD

**Issue by babno** [Atlantiss/NetherwingBugtracker#7467]
If you die and are awaiting rez at a gy, and lose control, you are not teleported. If it's neutral at the end of the timer you will rez, and if it's controlled by the opposing faction you are forced to ghost walk to another GY

**Comment by nullfoxh** [comment]
Same in AV

**Comment by tsuone** [comment]
Every BG.

**Comment by Wolffenstein** [comment]
Fixed in rev 3523.
