### ISSUE TITLE
[Mining] Item is already being used bug

### ISSUE THREAD

**Issue by bugseeker159** [Atlantiss/NetherwingBugtracker#7469]
[//]: # (Enclose links to things related to the bug using http://wowhead.com or any other TBC database.)
[//]: # (You can use screenshot ingame to visual the issue.)
[//]: # (Write your tickets according to the format:)
[//]: # ([Quest][Azuremyst Isle] Red Snapper - Very Tasty!)
[//]: # ([NPC] Magistrix Erona)
[//]: # ([Spell][Mage] Fireball)
[//]: # ([Npc][Drop] Ghostclaw Lynx)
[//]: # ([Web] Armory doesnt work)
[//]: # (To find server revision type `.server info` command in the game chat.)

**Description**: Sometimes when i mine a node in Outlands i get an error message with "Item is already being used", i wait a little then try to mine again, the mining channeling goes normally, loot window opens up and when i click on the items to loot them nothing happens, i don't get the ore and the mining tick goes off, i repeat and the same thing happens again and again until the node disappears. 

**Current behaviour**:

**Expected behaviour**: 

**Server Revision**:

**Comment by eri1997** [comment]
I believe this started with the loot rework in netherwing

**Comment by Minnona** [comment]
This is happening to me quite often now, server rev 3596. Asked guildies and some of them experienced it as well. I get channeling, get loot window with a few items in it, but none of them go to my bag. It can be fixed if I go and mine any other node and come back.

**Comment by Godmatik** [comment]
Issue likely now resolved - have not heard of any problems on Netherwing server
