### ISSUE TITLE
[NPC] Redridge Thrasher, 3x autoattack instead of 1

### ISSUE THREAD

**Issue by toki90** [Atlantiss/NetherwingBugtracker#747]
**Description**: 
Redridge Thrashers seem to be doing far too much damage, instead of a single autoattack hit theyll hit you three times (at once) most of the time.

**Current behaviour**:
As you can see in the combat log they hit you three times with auto attack. (https://imgur.com/kZrI7iL)

**Expected behaviour**: 
Should be 1 attack Im pretty sure.

**Server Revision**:

**Comment by Firroth** [comment]
This mob has spell https://classicdb.ch/?spell=8876 
So it works fine.

Invalid report.
