### ISSUE TITLE
[Item][Hunter] Projectiles with 0.5 dps increments are rounded down

### ISSUE THREAD

**Issue by raethkcj** [Atlantiss/NetherwingBugtracker#7470]
**Description**: 
Projectiles come in a large range of DPS numbers, but the first decimal place is always either 0 or 0.5.

It appears that all projectiles with a 0.5 are rounded down before being used in ranged weapon damage calculations. I tested with multiple ranged weapons and attack power values to try to see if those affected the rounding, but it seems that only the projectiles affect it.
![image](https://user-images.githubusercontent.com/7716908/91617100-db0bee80-e94c-11ea-96ee-d94ececaff87.png)

![image](https://user-images.githubusercontent.com/7716908/91616497-72704200-e94b-11ea-81c6-abff6737df2d.png)
|Arrows|Actual|Expected|
|----------------------|-------------|-------------|
| No Arrows            |0dps             |0dps             |
| Low                  | 224.1142857 | 224.1142857 |
| High                 | 359.1142857 | 359.1142857 |
| Rough Arrow          |1.0dps             |1.5dps             |
| Low                  | 227.0142857 | 228.4642857 |
| High                 | 362.0142857 | 363.4642857 |
| Thorium Headed Arrow |17.0dps          |17.5dps             |
| Low                  | 273.4142857 | 274.8642857 |
| High                 | 408.4142857 | 409.8642857 |
| Timeless Arrow       |53dps             |53dps             |
| Low                  | 377.8142857 | 377.8142857 |
| High                 | 512.8142857 | 512.8142857 |

**Current behaviour**:
0.5 dps is rounded down.
`Damage = (AP/14 + FLOOR(Arrow) + WeaponDamage/Speed) * Speed`

**Expected behaviour**: 
0.5 dps is used in damage calculations:
`Damage = (AP/14 + Arrow + WeaponDamage/Speed) * Speed`

**Server Revision**: 
3515

**Comment by Easyfraggy** [comment]
I don't see any proof that this is a bug.

**Comment by raethkcj** [comment]
There are 3 components to auto damage; AP, weapon base damage, and projectiles. Neither the `AP/14` nor the weapon damage are rounded down. They are calculated as floats and sent from server to client as floats. Projectile damage is the only part that gets  rounded down.

**Comment by raethkcj** [comment]
It's difficult to find a source for something so specific, but Cheeky's Hunter Spreadsheet from ElitistJerks does not round in its ammo calculation:

![image](https://user-images.githubusercontent.com/7716908/91644216-af960c00-e9ff-11ea-9e1d-b8e1606be83b.png)

**Comment by raethkcj** [comment]
The oldest wiki page I can find that shows damage calculations doesn't use a fractional arrow, but also doesn't make any mention of rounding:

https://wowwiki.fandom.com/wiki/Damage_per_second?direction=next&oldid=1556558

**Comment by Wolffenstein** [comment]
Fixed in rev 3944.
