### ISSUE TITLE
[Spell][Shaman] Rockbiter Weapon

### ISSUE THREAD

**Issue by sodafloofy123** [Atlantiss/NetherwingBugtracker#7472]
Current behaviour: Rockbiter weapon applies the buff to both weapons with a single cast when dual wielding.

Expected behaviour: Like Flametongue, Windfury and frostbrand it should first apply to main hand weapon then off hand weapon.

**Comment by Peglaa** [comment]
Duplicate. https://github.com/Atlantiss/NetherwingBugtracker/issues/2352
