### ISSUE TITLE
Totem of Wrath not adding hit rating

### ISSUE THREAD

**Issue by grayjedithebalance** [Atlantiss/NetherwingBugtracker#7473]
[//]: # (Enclose links to things related to the bug using http://wowhead.com or any other TBC database.)
[//]: # (You can use screenshot ingame to visual the issue.)
[//]: # (Write your tickets according to the format:)
[//]: # ([Quest][Azuremyst Isle] Red Snapper - Very Tasty!)
[//]: # ([NPC] Magistrix Erona)
[//]: # ([Spell][Mage] Fireball)
[//]: # ([Npc][Drop] Ghostclaw Lynx)
[//]: # ([Web] Armory doesnt work)
[//]: # (To find server revision type `.server info` command in the game chat.)

Naturesown lvl 70 troll shaman on kara server. totem of wrath not adding hit

**Current behaviour**:

**Expected behaviour**: 

**Server Revision**:

**Comment by Godmatik** [comment]
It doesn't add hit rating, it increases your hit by 3% on the target, it won't reflect on the character sheet.
