### ISSUE TITLE
[Quest] Defiling Uther's Tomb ghost not playing RP, quest uncompletable 

### ISSUE THREAD

**Issue by kelsul** [Atlantiss/NetherwingBugtracker#7474]
[//]: # (Enclose links to things related to the bug using http://wowhead.com or any other TBC database.)
[//]: # (You can use screenshot ingame to visual the issue.)
[//]: # (Write your tickets according to the format:)
[//]: # ([Quest][Azuremyst Isle] Red Snapper - Very Tasty!)
[//]: # ([NPC] Magistrix Erona)
[//]: # ([Spell][Mage] Fireball)
[//]: # ([Npc][Drop] Ghostclaw Lynx)
[//]: # ([Web] Armory doesnt work)
[//]: # (To find server revision type `.server info` command in the game chat.)

**Description**:  The quest  Defiling Uther's Tomb is uncompletable. You can summon the ghost with the item, but it doesnt do or say anything, and despawns after a while. 

**Current behaviour**: Uther's ghost doesnt say anything, no quest credit is given. 

**Expected behaviour**: Uther's ghost should talk for a bit after being summoned, then give quest credit.

**Server Revision**:  3519

**Comment by Easyfraggy** [comment]
worked fine a month ago.

**Comment by Tereneckla** [comment]
Not anymore. Not even getting a ghost.

**Comment by Drayo** [comment]
Worked for me after repeated use of the Item. Still complete-able but kinda annoying.

**Comment by Godmatik** [comment]
Still broken - every time I used the quest item the ghost would appear but no dialogue or quest completion. 
EDIT: Worked on 5th try

**Comment by EtheriousNW** [comment]
Fixed in 3846
