### ISSUE TITLE
[Tempest Keep] Al'ar

### ISSUE THREAD

**Issue by Arkie08** [Atlantiss/NetherwingBugtracker#7475]
**Description**: 
Priests shadowfiend are _sometimes_ unable to target Al'ar if used during phase 1.
**Current behaviour**:

Sometimes(might depend on which platform Al'ar is tanked on when priest use shadowfiend) the shadowfiend wont be able to target/attack Al'ar and will instead run away from the platform and eventually just despawn. Everytime this occured, it was while a tank already was tanking Al'ar on the respective platform.

**Expected behaviour**: 
As experienced on the Netherwing server, the shadowfiend should be able to attack Al'ar when its already being tanked on one of the diffrrent platforms during phase 1. 
I dont have any proof other than raidexperience on Netherwing, but other priests are experincing the same issue. Other priests can also confirm that it did work on all platforms on Netherwing.

**Server Revision**:

**Comment by Easyfraggy** [comment]
Do you hvae dots running on other targets while this is happening?

I know from retail we needed /petattack macro to make sure he didn't bounce between the targets you were attacking while multidotting.

**Comment by Arkie08** [comment]
The issue occurs with/without dots on adds. I've noticed if Al'ar ends up on one of "corner" platforms the shadowfiend will always work as intented. That is, platform "7 o'clock" and "5 o'clock" seem to work fine but the others dont.

**Comment by Godmatik** [comment]
Was fixed on Netherwing server last year - closing
