### ISSUE TITLE
([Pummel][Warrior] charge, intercept, pummel, hamstring)

### ISSUE THREAD

**Issue by Unreal0ps** [Atlantiss/NetherwingBugtracker#7477]
[//]: # (Enclose links to things related to the bug using http://wowhead.com or any other TBC database.)
[//]: # (You can use screenshot ingame to visual the issue.)
[//]: # (Write your tickets according to the format:)
[//]: # ([Quest][Azuremyst Isle] Red Snapper - Very Tasty!)
[//]: # ([NPC] Magistrix Erona)
[//]: # ([Spell][Mage] Fireball)
[//]: # ([Npc][Drop] Ghostclaw Lynx)
[//]: # ([Web] Armory doesnt work)
[//]: # (To find server revision type `.server info` command in the game chat.)

**Description**: Warrior charge, intercept, pummel, hamstring appear to be using spell hit 

**Current behaviour**: pummel, hamstring, intercept can currently be resisted (not sure thats the case for intercept exactly)

**Expected behaviour**: these abilities should miss, not be resisted

**Server Revision**: 3519

**Comment by Easyfraggy** [comment]
Charge and intercept should resist, you get more resists than hitcap because of talents and items that give stun resist.

Pummel and Hamstring is on melee hit and gives "miss" message properly.

So all of this is invalid.

**Comment by Unreal0ps** [comment]
![hamstring](https://user-images.githubusercontent.com/70499797/91725571-8ba00b00-eb64-11ea-91f6-37c2b9adc096.PNG)

**Comment by Tereneckla** [comment]
![image](https://user-images.githubusercontent.com/50233983/91744982-97b6b780-ebba-11ea-8015-a13f4b3b8642.png)
