### ISSUE TITLE
[Spell] Bloodlust and Power Infusion stack

### ISSUE THREAD

**Issue by Tereneckla** [Atlantiss/NetherwingBugtracker#7479]
[//]: # (Enclose links to things related to the bug using http://wowhead.com or any other TBC database.)
[//]: # (You can use screenshot ingame to visual the issue.)
[//]: # (Write your tickets according to the format:)
[//]: # ([Quest][Azuremyst Isle] Red Snapper - Very Tasty!)
[//]: # ([NPC] Magistrix Erona)
[//]: # ([Spell][Mage] Fireball)
[//]: # ([Npc][Drop] Ghostclaw Lynx)
[//]: # ([Web] Armory doesnt work)
[//]: # (To find server revision type `.server info` command in the game chat.)

**Description**: 
Bloodlust and Power Infusion should not stack (as Heroism and Power Infusion currently do not do)
**Current behaviour**:
Bloodlust and Power Infusion stack
**Expected behaviour**: 
Bloodlust and Power Infusion don't stack
**Server Revision**: 
3515

**Comment by Wolffenstein** [comment]
Fixed in rev 3523.
