### ISSUE TITLE
low rank gift of the wild overrides high rank mark of the wild

### ISSUE THREAD

**Issue by babno** [Atlantiss/NetherwingBugtracker#7481]
![image](https://user-images.githubusercontent.com/244626/91746110-13e4d700-eb8a-11ea-80f0-68c9d587b8dc.png)
This was a rank 2 gift overriding a rank 8 mark. I was able to override gift by casting mark again. I'm also able to override gift with a rank 1 mark.

I suspect a similar behavior for priest and paladin buffs.

**Comment by Wolffenstein** [comment]
Fixed in rev 3523.
