### ISSUE TITLE
[Karazhan][Boss] Strawman in opera event

### ISSUE THREAD

**Issue by babno** [Atlantiss/NetherwingBugtracker#7482]
same exact issue as #4278

**Comment by Godmatik** [comment]
Somewhat confirmed, for me it was difficult to get him disoriented, took about 10 seconds of spamming scorches before he finally did it after spawning. It appears inconsistent.

**Comment by Godmatik** [comment]
Faced this boss again, and it still occurs.

He should gain a disorient debuff after every fire attack, but sometimes (around 25% of the time or so) a fire attack is put on him but he doesn't get disoriented.

**Comment by Godmatik** [comment]
Was fixed here:

https://github.com/Atlantiss/NetherwingBugtracker/issues/8089

Can close
