### ISSUE TITLE
Bonus Damage (spell) from healer items

### ISSUE THREAD

**Issue by Rapcat55** [Atlantiss/NetherwingBugtracker#7484]
[//]: # (https://tbcdb.com/?item=25759) and other healing itmes like this dont get you any bonus spell damage.
[//]: # (https://imgur.com/a/eEwebpH)

**When you equip a "healer" item, you dont get any bonus spelldmg (except from intellect if you are a paladin)**: 

**0 bonus dmg from an item with "160 bonus healing, 54 bonus dmg"**:

**54 bonus dmg + the bonus healing**: 

**3519**:

**Comment by Tereneckla** [comment]
Until 2.3 they don't give healing.
For correct tooltips in that matter use this addon
https://github.com/nullfoxh/NWTooltipFix
