### ISSUE TITLE
[Item] Wolfshead Helm - not always giving 20 energy

### ISSUE THREAD

**Issue by jensfredgaard** [Atlantiss/NetherwingBugtracker#7486]
**Description**: Sometimes the Wolfhead Helm doesn't give the 20 extra energy when powershifting.

**Current behaviour**: With 5/5 furor talent + Wolfshead Helm you should get 60 energy on shift and it works like this in most cases. Sometimes it does not give the +20 energy from Wolfhead Helm, the furor talents always work. I have noticed that it happens when i am powershifting really close to a new energy tick. This error does not occur that often, 1-3 times during 25 man boss encounter. When this is happening i get 40 energy from a shift (waiting for tick) and then + 20 from energy tick.

**Expected behaviour**:  Shift = 60 energy, not 40 + 20 most of the time.

**Server Revision**:

**Comment by Godmatik** [comment]
Talked to a couple of feral druids who used it this past year - not bugged, it gives the correct energy every time.
