### ISSUE TITLE
[Quest] The Cipher of Damnation 

### ISSUE THREAD

**Issue by CptMarkka** [Atlantiss/NetherwingBugtracker#7487]
**Description**: 
Oronok Torn-Heart does not despawn, and Cyrukh the Firelord does not spawn when the Cipher of Damnation quest item is used in the Cipher of Damnation quest chain finale.

**Current behaviour**:
Currently when using the Cipher of Damnation quest item, Cyrukh the Firelord does not spawn as he should. Oronok Torn-Heart is standing to the right of the altar, waiting to attack the Firelord who is not there. Oronok's sons are not there with him.

**Expected behaviour**: 
The quest event should begin once the Cipher of Damnation quest item cast has been completed. Oronok Torn-Heart should despawn after the quest event is completed, or failed due to time limit.

**Server Revision**: 
Content patch: 2.0.3 | Revision: 3519

**Comment by Godmatik** [comment]
Fixed last year
