### ISSUE TITLE
I want to transfer this character to Karazhan

### ISSUE THREAD

**Issue by Josefzx** [Atlantiss/NetherwingBugtracker#7488]
I want to transfer this character to Karazhan
please
I started on this server when there was only Netherwing server, and I never play again, today I want to play again and I find that most of the players are in Karazhan, could you transfer my account to Karazhan please?

**Comment by Josefzx** [comment]
my account is: Josefzx

**Comment by Godmatik** [comment]
characters can't be transferred mate, karazhan is fresh and still on the first patch of the game, wouldn't be fair to others.

**Comment by Wolffenstein** [comment]
Nope.
