### ISSUE TITLE
capping BG objectives NOT interrupted by damage if target has a shield

### ISSUE THREAD

**Issue by babno** [Atlantiss/NetherwingBugtracker#7491]
If someone has a PWS or other absorb effect, damage does not interrupt them if they're capping a flag/tower/fy/etc.

**Comment by Wolffenstein** [comment]
Proof that it should?

**Comment by babno** [comment]
wow classic. The fact such a huge factor is never mentioned anywhere. Here is an extensive guide specifically for priests and arathi basin. Not mentioned. https://classic.wowhead.com/guides/priest-healing-arathi-basin-tips-ab-classic-wow

**Comment by Tereneckla** [comment]
![image](https://user-images.githubusercontent.com/50233983/92252252-46663b00-eece-11ea-8bc0-5c4a8dc42056.png)
![image](https://user-images.githubusercontent.com/50233983/92252277-4cf4b280-eece-11ea-8767-f994f8da54ba.png)
https://wowwiki.fandom.com/wiki/Arathi_Basin_strategy

Just as credible as that wowhead guide

**Comment by babno** [comment]
That's from a much later version of AB with 8 second caps and 1600 resources.

**Comment by Tereneckla** [comment]
https://wowwiki.fandom.com/wiki/Arathi_Basin_strategy?oldid=1291249
