### ISSUE TITLE
Slave Pens - Coilfang Ray's respawn

### ISSUE THREAD

**Issue by Godmatik** [Atlantiss/NetherwingBugtracker#7492]
After leaving a cleared ID for 2 hours, all trash is supposed to despawn. 

In Slave Pens, the Coilfang Ray's actually respawn.

![WoWScrnShot_090220_230530](https://user-images.githubusercontent.com/37913400/92070191-03428580-ed71-11ea-9594-3bb505b49abf.jpg)

**Comment by Wolffenstein** [comment]
Fixed in rev 3523.
