### ISSUE TITLE
Entering a BG will remove you from all other BG qs EXCEPT AV

### ISSUE THREAD

**Issue by babno** [Atlantiss/NetherwingBugtracker#7495]
Title. IIRC it shouldn't remove you from any, though I'm 100% sure it shouldn't play favorites. Possibly related to the call to arms bug as well.

**Comment by Godmatik** [comment]
This was an intentional feature they added, so that people don't constantly BG hop, but left it in for AV so that BG can still stay somewhat active.

**Comment by Tereneckla** [comment]
What Godmatik says. Wolf activated it for a bit on Kara, which kickstarted bg activity.
But BG hopping was a pretty big problem in that time.
