### ISSUE TITLE
[Quest] The Cipher of Damnation - NPCs don't die

### ISSUE THREAD

**Issue by Godmatik** [Atlantiss/NetherwingBugtracker#7496]
The three NPCs that fight with you can not die and only get lowered to 1 health, so you can let them tank the entire fight and just run back if you die until Cyrukh is dead.

**Comment by Evolvee** [comment]
and get no quest credit

**Comment by Godmatik** [comment]
I just did the quest about an hour ago with 4 others, we all received quest credit. 

We had to corpse run back a couple of times since the boss drops aggro on the NPC tanks periodically, but it was just an inconvenience, we waited it out and only did occasional light DPS until Cyrukh was dead as the three NPCs fought him, all of them sitting at 1 health.

**Comment by Evolvee** [comment]
someone must have added a q complete spell on death then

it wasnt there when i made it ergo required player participation and not relying on players

**Comment by Godmatik** [comment]
This still occurs
