### ISSUE TITLE
[Item][Patch 2.3] Spinesever should only be obtainable after Patch 2.3

### ISSUE THREAD

**Issue by raethkcj** [Atlantiss/NetherwingBugtracker#7497]
**Current behaviour**:
Spinesever is obtainable in-game

**Expected behaviour**: 
Shouldn't be obtainable until 2.3
https://wow.gamepedia.com/index.php?title=Spinesever_(weapon)&direction=next&oldid=981189

**Server Revision**: 
3519

**Comment by Wolffenstein** [comment]
Fixed in rev 3521.
