### ISSUE TITLE
Star's tears incorrect cost

### ISSUE THREAD

**Issue by babno** [Atlantiss/NetherwingBugtracker#7498]
![image](https://user-images.githubusercontent.com/244626/92274383-20836b00-eebb-11ea-846e-51717bd37a19.png)

https://www.wowhead.com/item=32453/stars-tears#comments
"Costs 25 silver and 2 honor points per 5."

**Comment by Tereneckla** [comment]
Check again with neutral reputation. The vendors have a faction and as such the discount applies
