### ISSUE TITLE
[Spell][Paladin] Righteous Defense - PRIORITY

### ISSUE THREAD

**Issue by wtRCH** [Atlantiss/NetherwingBugtracker#750]
[//]: # (Enclose links to things related to the bug using http://wowhead.com or any other TBC database.)
[//]: # (You can use screenshot ingame to visual the issue.)
[//]: # (Write your tickets according to the format:)
[//]: # ([Quest][Azuremyst Isle] Red Snapper - Very Tasty!)
[//]: # ([NPC] Magistrix Erona)
[//]: # ([Spell][Mage] Fireball)
[//]: # ([Npc][Drop] Ghostclaw Lynx)
[//]: # ([Web] Armory doesnt work)

**Description**: After using Rigteous Defense server crashes

**Comment by Wolffenstein** [comment]
Rev 2073
