### ISSUE TITLE
(Karazhan 2.x) Leatherworking Drums unusable while Shapeshifted

### ISSUE THREAD

**Issue by MartinBrandstrup** [Atlantiss/NetherwingBugtracker#7501]
[//]: # (Enclose links to things related to the bug using http://wowhead.com or any other TBC database.)
[//]: # (You can use screenshot ingame to visual the issue.)
[//]: # (Write your tickets according to the format:)
[//]: # ([Quest][Azuremyst Isle] Red Snapper - Very Tasty!)
[//]: # ([NPC] Magistrix Erona)
[//]: # ([Spell][Mage] Fireball)
[//]: # ([Npc][Drop] Ghostclaw Lynx)
[//]: # ([Web] Armory doesnt work)
[//]: # (To find server revision type `.server info` command in the game chat.)

**Description**: 
Leatherworking drums should be usable while shapeshifted as a Druid; even says so in the item description.
So far I have only tested with Drums of Restoration (https://tbcdb.com/?item=29531) but I strongly assume that all drums use the same script, and thus the issue will be universal.

**Current behaviour**:
When attempting to use the drums the sound effect plays locally, but no cast initiates and an error message "You are in shapeshift form" appears.

**Expected behaviour**: 
Drums are supposed to be castable while shapeshifted

**Server Revision**: 
TBC 2.x

**Comment by raethkcj** [comment]
See #7398
