### ISSUE TITLE
open pvp quest item abuse

### ISSUE THREAD

**Issue by fotren** [Atlantiss/NetherwingBugtracker#7503]
[//]: # (https://tbcdb.com/?item=30847
![WoWScrnShot_090520_052449](https://user-images.githubusercontent.com/54596562/92297294-240c0600-ef3e-11ea-8212-955d56f61f94.jpg)
)
[//]: # (Write your tickets according to the format:)
[//]: # ([Item][X-52 Rocket Helmet)
**Description**: 
Use the item, get oneshotted.
**Current behaviour**:
Use the item, fire aoe bursts out, and oneshot everything around you.
**Expected behaviour**: 
Probably not a nuclear weapon that korea would envy. 
**Server Revision**:

**Comment by tsuone** [comment]
Doesn't work for me.

Need more proof, some video would be nice.

**Comment by raethkcj** [comment]
For me it is ticking 3 times for 100 damage each, which appears to be correct.

I'm not sure what he's doing to get it to tick 6 times for 120.

**Comment by fotren** [comment]
i've got a total of 2k from it, that on the screenshot is not all the damage done by it. "since the item doesnt work in combat, he sap/blind to get out of combat,"@tsuone and uses it, how he manages to get that much damage dunno

**Comment by Wolffenstein** [comment]
Fixed in rev 3521.
