### ISSUE TITLE
[NPC] Great Goretusk

### ISSUE THREAD

**Issue by sefamurat** [Atlantiss/NetherwingBugtracker#7504]
**Description**: 
There should be Great Goretusks at southern end of Westfall

**Current behaviour**:
There are no Great Goretusks at southern end of Westfall

**Expected behaviour**: 
There should be Great Goretusks at southern end of Westfall

**Server Revision**: 3519

source: https://classic.wowhead.com/npc=547/great-goretusk

**Comment by tsuone** [comment]
Confirmed, didn't find any boar.

**Comment by Wolffenstein** [comment]
Fixed in rev 3545.
