### ISSUE TITLE
Error at Pvp vendor

### ISSUE THREAD

**Issue by Ceo1993** [Atlantiss/NetherwingBugtracker#7505]
![image](https://user-images.githubusercontent.com/70841930/92323790-de356780-f03b-11ea-98b6-3b26b3adc1fa.png)

**Description**: I was going to buy High Warlord's Dragonhide Gloves at honor hall and I got High Warlord's Wirmhide Gloves instead.

**Current behaviour**: I clicked in the High Warlord's Dragonhide Gloves simbol and I got High Warlord's Wirmhide Gloves.

**Expected behaviour**: Click in the High Warlord's Dragonhide Gloves simbol and get High Warlord's Dragonhide Gloves.

**Server Revision**: Karazhan

**Comment by tsuone** [comment]
**Invalid**
I tried doing that, and got Dragonhide Gloves.

@Ceo1993 If you want to refund Wyrmhide Gloves for full amount of Honor Points and Mark of Honors, please contact Game Master ingame via ticket.

**Comment by Ceo1993** [comment]
Weird, I can swear that i did it well and didn't got the correct item. Thanks for your time.

**Comment by Godmatik** [comment]
@Ceo1993 
you probably have outdated data, delete your cache folder
