### ISSUE TITLE
Spell haste values using Pre-updated values

### ISSUE THREAD

**Issue by Pixystickz** [Atlantiss/NetherwingBugtracker#7506]
https://wowwiki.fandom.com/wiki/Patch_2.2.0 - "Haste has been rebalanced. It has returned to the ratios from the launch of Burning Crusade. Melee attacks and spell casts will now benefit at identical rates from haste. This change results in a reduction in the benefit of haste for melee attacks and an increase in the benefit for spellcasters."

i think spell haste values are using the pre-2.2 formula, even know all spells and mechanics should have been updated to the post-patch values. in 2.1, 320 haste rating was ~= 15.2% reduction in casting time; in 2.2 it's ~= 20.3% reduction in casting time. but because blizzard didn't add more spell haste onto gear to make the change, and instead edited the formula to benefit spell haste more, it didn't get automatically updated on this server like the rest of _spells_ on items did.

if they added 33% more spell haste onto peoples gear, the server would be using the updated values on gear, but because they changed the formula for it, it wasn't changed. spell haste correctly reduces the global cooldown though, which was added in 2.4.0-- which is why I think this is just a problem of using the 2.1 values for spell haste instead of the post-2.2 values.

**Comment by Pixystickz** [comment]
My shadow bolt with 320 spell haste is a 2.5/3s (16.6%) cast, my fear is a 1.3/1.5s (13.34%) cast, and my rain of fire is a 6.7/8s (16.25%) cast (according to quartz).

**Comment by raethkcj** [comment]
You're dividing the wrong way. 2.5sec Shadowbolt is `3/2.5 - 1 = 20% haste`, same with your other spells.

Haste is an *increase in casting speed*, not a *reduction in cast time*.

To get casting time from haste:

`HastedCast = BaseCast / (1 + Haste)`
