### ISSUE TITLE
[Core] Unable to log in (with reproduce)

### ISSUE THREAD

**Issue by tsu-1** [Atlantiss/NetherwingBugtracker#7507]
[//]: # (Enclose links to things related to the bug using http://wowhead.com or any other TBC database.)
[//]: # (You can use screenshot ingame to visual the issue.)
[//]: # (Write your tickets according to the format:)
[//]: # ([Quest][Azuremyst Isle] Red Snapper - Very Tasty!)
[//]: # ([NPC] Magistrix Erona)
[//]: # ([Spell][Mage] Fireball)
[//]: # ([Npc][Drop] Ghostclaw Lynx)
[//]: # ([Web] Armory doesnt work)
[//]: # (To find server revision type `.server info` command in the game chat.)

**Description**: If you log out from the game right before when Alterac Valley (or any battleground probably) ends, you won't be able to log in back on your character. I think this might be tied to the "void" bug.

Player characters aren't properly removed from the instance/map when it ends (Battlegrounds, Arenas).

**Comment by danbopes** [comment]
What happens to their characters, when they attempt to login?

**Comment by tsuone** [comment]
@danbopes Disconnect and doing `.appear <name>` doesn't do anything.

**Comment by Godmatik** [comment]
Fixed in rev 4015 by Wolf:

[Core/Player]:
Battleground Instance ID will now be properly cleared when the server restarts or when the player is being loaded into a non-bg map
