### ISSUE TITLE
Druid armor scaling

### ISSUE THREAD

**Issue by hadoor04** [Atlantiss/NetherwingBugtracker#7508]
[//]: # (Enclose links to things related to the bug using http://wowhead.com or any other TBC database.)
[//]: # (You can use screenshot ingame to visual the issue.)
[//]: # (Write your tickets according to the format:)
[//]: # ([Quest][Azuremyst Isle] Red Snapper - Very Tasty!)
[//]: # ([NPC] Magistrix Erona)
[//]: # ([Spell][Mage] Fireball)
[//]: # ([Npc][Drop] Ghostclaw Lynx)
[//]: # ([Web] Armory doesnt work)
[//]: # (To find server revision type `.server info` command in the game chat.)

**Description**: 

Bonus base armor on items(items with armor amount in green) is not scaling with its bonus amount only its base. This bonus armor should be figured into bear armor calculations and is not.

**Current behaviour**:

Heavy Clefthoof Vest (Armor written in green) 500 armor
as it is: 1595

**Expected behaviour**: 
Direbear + Thick hide
as it should be: 500 Armor* 550% = 2750 Armor

**Server Revision**: 
karazhan server rev 3519

Sources:
https://wowwiki.fandom.com/wiki/BC_tanking_equipment_(druid) has an item list with what your total stats should be

**Comment by Tereneckla** [comment]
Delete your cache, it has 290 armor in the current patch
