### ISSUE TITLE
[WARRIOR][TALENT]Blood Frenzy

### ISSUE THREAD

**Issue by Nuy** [Atlantiss/NetherwingBugtracker#7509]
[//]: # (Enclose links to things related to the bug using http://wowhead.com or any other TBC database.)
[//]: # (You can use screenshot ingame to visual the issue.)
[//]: # (Write your tickets according to the format:)
[//]: # ([Quest][Azuremyst Isle] Red Snapper - Very Tasty!)
[//]: # ([NPC] Magistrix Erona)
[//]: # ([Spell][Mage] Fireball)
[//]: # ([Npc][Drop] Ghostclaw Lynx)
[//]: # ([Web] Armory doesnt work)
[//]: # (To find server revision type `.server info` command in the game chat.)

**Description**:  Blood Frenzy doesn't work correctly. It disappears when Deep Wounds expires even if Rend is still up.

**Current behaviour**: Blood Frenzy disappears when Deep Wounds expires even if Rend is up.

**Expected behaviour**: Blood Frenzy shouldn't end with Deep Wounds if Rend is still up.

**Server Revision**: 3519

**Comment by Wolffenstein** [comment]
Fixed in rev 3536.
