### ISSUE TITLE
[NPC] Temporus can deal crushing blows to defense capped tank

### ISSUE THREAD

**Issue by Onionpaste** [Atlantiss/NetherwingBugtracker#7511]
[NPC] Temporus (Heroic mode Black Morass): 

Current behaviour: Temporus is dealing crushing blows against a level 70 tank with max base defense (350). See attached screenshot:

![image](https://user-images.githubusercontent.com/70921165/92418768-2a58d880-f11e-11ea-9558-fd7a06f59019.png)

Expected behaviour: As a level 72 monster, Temporus should not be able to deal crushing blows to any level 70 character with 350 base defense.

Confirming base defense is at cap: 
![image](https://user-images.githubusercontent.com/70921165/92418830-8885bb80-f11e-11ea-9c67-2f616876c25f.png)

Server Revision: 3519

**Comment by Godmatik** [comment]
Just an FYI, Defense has nothing to do with Crushing blows, it prevents you from getting crit when you are capped.

But you are still correct that if the mob is only 2 levels above the player, that crushing blows should not occur.

**Comment by raethkcj** [comment]
Defense above 350 doesn't prevent crushing blows, but a *lack of defense* before 350 can actually cause them. E.g. a level 70 with only 345 defense would take crushing blows from a 72. But you're right, you are capped and should not take crushes either way.

**Comment by Onionpaste** [comment]
@raethkcj is correct, the reason I'm showing the defense skill is to confirm that it is level-capped and not lacking (which would cause crushing blows to be possible).

**Comment by Wolffenstein** [comment]
Fixed in rev 3529.
