### ISSUE TITLE
Magtheridon skips Blast Nova casts

### ISSUE THREAD

**Issue by Godmatik** [Atlantiss/NetherwingBugtracker#7512]
If Mag uses quake and it happens at the same time his Blast Nova comes off cooldown, he will completely skip using that blast nova and wait another full 50 seconds before casting it again.

**Comment by Godmatik** [comment]
Killed Mag a few more times, didn't see this issue occur again. 
Either was fixed or just a random very unlikely event, will close for now.

**Comment by Godmatik** [comment]
Reopening because if happened again.

**Comment by Wolffenstein** [comment]
Fixed in rev 3544.
