### ISSUE TITLE
Wrong stats calculation in character info

### ISSUE THREAD

**Issue by Ceo1993** [Atlantiss/NetherwingBugtracker#7513]
![image](https://user-images.githubusercontent.com/70841930/92457023-fa641080-f1c3-11ea-9da5-ed2059b3e2f3.png)
![image](https://user-images.githubusercontent.com/70841930/92457204-3b5c2500-f1c4-11ea-9e4b-d40116d12443.png)

**Description**: There is a problem in stats calculator because stamina stat doesn't change when I switch between a item with 39 stamina and a item with 0 stamina on it.

**Current behaviour**:
When i change the weapon between Earthwander and a fishing pool stamina doesn't change although Earthwander has 39 stamina and fishing pool has 0 stamina.

**Expected behaviour**: Stamina should change when I switch weapon.

**Server Revision**: Karazhan

**Comment by eri1997** [comment]
That's because that weapon has no stamina in 2.0 itemization. Delete your cache to see correct stats for this patch

**Comment by Ceo1993** [comment]
Yea, you are right, thank you for your help.
