### ISSUE TITLE
Need turn in for each type of mark

### ISSUE THREAD

**Issue by babno** [Atlantiss/NetherwingBugtracker#7514]
With the custom non blizzlike changes to the call to arms quests and the bg q system, I, and many people I know, have mark counts that look rather like this

![image](https://user-images.githubusercontent.com/244626/92474579-15c22200-f1aa-11ea-965a-c27e114d273b.png)

There needs to be something to do with the excess of AV marks, and I'd suggest adding these quests in

https://classic.wowhead.com/quest=8383/remember-alterac-valley
https://classic.wowhead.com/quest=8387/invaders-of-alterac-valley

**Comment by Tereneckla** [comment]
@tsuone

**Comment by Wolffenstein** [comment]
Bugtracker isn't the place for suggestions.
