### ISSUE TITLE
[QUEST] Deathblow to the Legion

### ISSUE THREAD

**Issue by Msbhv1** [Atlantiss/NetherwingBugtracker#7516]
**Description**: Grouped up to do the 5-man Socrethar quest but when we arrived it seems like someone started the event before and didnt finish it. Since then we have been waiting for 15 minutes and nothing happen. Seems like the NPCs are bugged.

**Current behaviour**: NPC stand in the middle of arena and doesn't interact

**Expected behaviour**: Reset the event for another group to start it

**Server Revision**:

**Comment by Tereneckla** [comment]
When Ayden dies before Kaylaan is defeated he walks towards the throne on before talking to him on the next spawns.

**Comment by Godmatik** [comment]
#9162
