### ISSUE TITLE
[Movement][NPC][Alterac Valley]Several NPCs lacking patrols

### ISSUE THREAD

**Issue by Tenoutoften** [Atlantiss/NetherwingBugtracker#7517]
**Description**: 
* The patrols routes for several groups of NPCs in Alterac Valley is missing. Given that this is a Battleground played throughout the day by many players I think it would be nice to have them fixed visually.

This image is taken at the horde base
- 2 x [[NPC]Frostwolf Bloodhound#14282](https://classic.wowhead.com/npc=14282/frostwolf-bloodhound)
- 1 x [[NPC]Frostwolf Legionnaire#12051](https://classic.wowhead.com/npc=12051/frostwolf-legionnaire)
![Horde base](https://user-images.githubusercontent.com/34839199/92511009-fdcfba00-f20c-11ea-8cb8-155d2224fd7c.png)

Further north, quite close to the third tower of the horde there is another pack standing still with
- 2 x 1 x [[NPC]Frostwolf Legionnaire#12051](https://classic.wowhead.com/npc=12051/frostwolf-legionnaire)
![Mid horde base](https://user-images.githubusercontent.com/34839199/92511208-4d15ea80-f20d-11ea-9973-937674e70ec7.png)

Secondly a few of them have incorrect levels, I've seen [[NPC]Frostwolf Bloodhound#14282](https://classic.wowhead.com/npc=14282/frostwolf-bloodhound) around ~54.

Same level issue seems to apply to [[NPC]Stormpike Owl#14283](https://classic.wowhead.com/npc=14283/stormpike-owl)

This is by Icewing Bunker, 2 x [[NPC]Stormpike Guardsman#12127](https://classic.wowhead.com/npc=12127/stormpike-guardsman)
![WoWScrnShot_090820_201431](https://user-images.githubusercontent.com/34839199/92513963-6caf1200-f211-11ea-92e1-6e401b4a62a9.jpg)

Running further north you get to a 2 x [[NPC]Stormpike Owl#14283](https://classic.wowhead.com/npc=14283/stormpike-owl) + 
[[NPC]Stormpike Guardsman#12127](https://classic.wowhead.com/npc=12127/stormpike-guardsman) pack
![WoWScrnShot_090820_201453](https://user-images.githubusercontent.com/34839199/92514036-8e0ffe00-f211-11ea-8217-70a335de2e15.jpg)

As you move towards alliance "entrance" there are a few packs of 2 x [[NPC]Stormpike Guardsman#12127](https://classic.wowhead.com/npc=12127/stormpike-guardsman) standing still too
![WoWScrnShot_090820_201536](https://user-images.githubusercontent.com/34839199/92514165-c0b9f680-f211-11ea-8415-588da3e1a419.jpg)

![WoWScrnShot_090820_201550](https://user-images.githubusercontent.com/34839199/92514229-d7604d80-f211-11ea-872f-bf76c5e5f882.jpg)

![WoWScrnShot_090820_201612](https://user-images.githubusercontent.com/34839199/92514278-eba44a80-f211-11ea-84b6-98d5e9b19c6e.jpg)

----
Additionally the guards( For alliance [[NPC]Seasoned Defender#13326](https://classic.wowhead.com/npc=13326/seasoned-defender) & [[NPC]Frostwolf Guardian#12053](https://www.wowhead.com/npc=12053/frostwolf-guardian) for horde) protecting graveyard banners are standing still, but should be walking around a bit on their spot. These are the ones that when upgraded by armor scraps get changed out to the following:

Alliance:
* [[NPC]Stormpike Defender#12050](https://www.wowhead.com/npc=12050/stormpike-defender)
* [[NPC]Seasoned Defender#13326](https://www.wowhead.com/npc=13326/seasoned-defender)
* [[NPC]Veteran Defender#13331](https://www.wowhead.com/npc=13331/veteran-defender)
* [[NPC]Champion Defender#13422](https://www.wowhead.com/npc=13422/champion-defender)

Likewise for horde:
* [[NPC]Frostwolf Guardian#12053](https://www.wowhead.com/npc=12053/frostwolf-guardian)
* [[NPC]Seasoned Guardian#13328](https://www.wowhead.com/npc=13328/seasoned-guardian)
* [[NPC]Veteran Guardian#13332](https://www.wowhead.com/npc=13332/veteran-guardian)
* [[NPC]Champion Guardian#13421](https://www.wowhead.com/npc=13421/champion-guardian)

**Current behaviour**:
Currently most of the patrols are standing still.

**Expected behaviour**: 
Expect these NPCs to patrol

**Server Revision**: 
3519

**Comment by Godmatik** [comment]
Closing - will consolidate all outstanding AV issues into one thread now.
