### ISSUE TITLE
[Dungeon][NPC]Old Hillsbrad Foothills Captain Skarloc's Holy Light should be interrupt-able

### ISSUE THREAD

**Issue by Tenoutoften** [Atlantiss/NetherwingBugtracker#7518]
**Description**: 
[[NPC]Captain Skarloc#20521's](http://tbc.cavernoftime.com/npc=20521) should be vulnerable to interrupts when he casts his [[Spell]Holy Light#29427](http://tbc.cavernoftime.com/spell=29427) can be seen [here](https://youtu.be/afbf54etkcY?t=271) recorded in heroic version

**Current behaviour**:
Not possible to interrupt

**Expected behaviour**: 
Expected to be vulnerable to interruptions

**Server Revision**: 
3519

**Comment by Wolffenstein** [comment]
Fixed in rev 3529.
