### ISSUE TITLE
[Dungeon][NPC][Spell]Old Hillsbrad Foothills, Riflemen & Lookouts should Scatter others than the Main Target

### ISSUE THREAD

**Issue by Tenoutoften** [Atlantiss/NetherwingBugtracker#7519]
**Description**: 

[[NPC]Durnholde Rifleman#17820, Normal](http://tbc.cavernoftime.com/npc=20526) & [[NPC]Durnholde Rifleman#20526, Heroic](http://tbc.cavernoftime.com/npc=20526) should not be casting their [[Spell]Scatter Shot](http://tbc.cavernoftime.com/?search=scatter+shot) on main tank only.

**evidence**
[Here](https://youtu.be/K925aSBarOU?t=36) you can see that the main tank is tanking the Rifleman, and a warlock's pet is tanking a non-rifleman, yet the [[NPC]Durnholde Rifleman#17820/20526, Normal/Heroic](http://tbc.cavernoftime.com/npc=20526) decides to [[Spell]Scatter Shot](http://tbc.cavernoftime.com/?search=scatter+shot) the pet.

[Here](https://youtu.be/K925aSBarOU?t=215) the hunter of the group pulls the [[NPC]Durnholde Rifleman#17820/20526, Normal/Heroic](http://tbc.cavernoftime.com/npc=20526) with a autoshot, yet when it comes closer it [[Spell]Scatter Shot](http://tbc.cavernoftime.com/?search=scatter+shot)'s the warlock

[Here](https://youtu.be/K925aSBarOU?t=261) it shoots a player, likely the healer of the group and follows up with a [[Spell]Scatter Shot](http://tbc.cavernoftime.com/?search=scatter+shot) on a pet that isn't targeting it. 

[Here](https://youtu.be/K925aSBarOU?t=300) the tank has taunted the  [[NPC]Durnholde Rifleman#17820/20526, Normal/Heroic](http://tbc.cavernoftime.com/npc=20526) shortly after it [[Spell]Scatter Shot](http://tbc.cavernoftime.com/?search=scatter+shot)'s the warlock

[Here](https://youtu.be/K925aSBarOU?t=507) it [[Spell]Scatter Shot](http://tbc.cavernoftime.com/?search=scatter+shot)'s the groups healer, who is highest on threat, the [[NPC]Durnholde Rifleman#17820/20526, Normal/Heroic](http://tbc.cavernoftime.com/npc=20526) then proceeds to auto shoot, breaking it's own [[Spell]Scatter Shot](http://tbc.cavernoftime.com/?search=scatter+shot).

The clear up to the house is included if you check out the channel

----
To make sure nothing is missed, there is 3/6 NPCs doing this currently:
* Durnholde Rifleman#17820/20526
* Durnholde Lookout#22128/22129
* Tauren Mill Lookout#18094/23178

**Current behaviour**:
Currently in Old Hillsbrad the Riflemen and Lookouts are casting [[Spell]Scatter Shot](http://tbc.cavernoftime.com/?search=scatter+shot) only on the main target, then they swap to the rest of the group.

**Expected behaviour**: 

Riflemen & Lookouts are to at the very least to take players and player's pet into their consideration when attempting to [[Spell]Scatter Shot](http://tbc.cavernoftime.com/?search=scatter+shot) rather than the main target. Possibly they shouldn't [[Spell]Scatter Shot](http://tbc.cavernoftime.com/?search=scatter+shot) the main tank at all. And they should continue to attack the target they [[Spell]Scatter Shot](http://tbc.cavernoftime.com/?search=scatter+shot)ed if it is highest on threat.

**Server Revision**: 
3519

**Comment by Tenoutoften** [comment]
[This](https://youtu.be/ZmZFuPjNdLo?t=165) & [This](https://www.youtube.com/watch?v=x7XbFbbibSY) is from Shattered Halls(H) uploaded 2008, May.

A prot paladin tanks all the three packs of scatter shotters, not a single scattershot is fired from [[NPC]Shattered Hand Sharpshooter#16704/20594](https://tbc-twinhead.twinstar.cz/?search=shattered+hand#npcs)

Is this due to it being a later patch, or is this an ability they rarely use? Perhaps a timer of 1min before they use it?

**Comment by Wolffenstein** [comment]
Fixed in rev 3529.
