### ISSUE TITLE
[Dungeon][NPC][Movement]Durnholde Lookout & Durnholde Tracking Hound missing patrol

### ISSUE THREAD

**Issue by Tenoutoften** [Atlantiss/NetherwingBugtracker#7520]
**Description**: 
I can't see the still standing NPCs [here](https://youtu.be/OIL743ikk3w?t=35), though this is wrath, the current position doesn't look authentic, given that the formation of the group is a typical patrol I think it is safe to assume it should either not be in game or be patrolling.

**Current behaviour**:
[[NPC]Durnholde Lookout#22129/22128](http://tbc.cavernoftime.com/?search=durnholde#npcs) & [[NPC]Durnholde Tracking Dog#17840/20528](http://tbc.cavernoftime.com/?search=durnholde#npcs) standing still just outside of the keep in OHF.

**Expected behaviour**: 
The patrol formation of [[NPC]Durnholde Lookout#22129/22128](http://tbc.cavernoftime.com/?search=durnholde#npcs) & [[NPC]Durnholde Tracking Dog#17840/20528](http://tbc.cavernoftime.com/?search=durnholde#npcs) standing still just outside of the keep in OHF should be patrolling.

**Server Revision**: 
3519

**Comment by Tereneckla** [comment]
Also wrath https://youtu.be/2holFQRMEoc?t=17 (Watch in 0.25 speed)
They are patrolling.

**Comment by Wolffenstein** [comment]
Fixed in rev 3529.
