### ISSUE TITLE
[Dungeon][NPC][Movement]Spawned pack in OHF stands still for too long

### ISSUE THREAD

**Issue by Tenoutoften** [Atlantiss/NetherwingBugtracker#7521]
**Description**: 
After you have escorted Thrall past Captain Skerloc you end up at Tauren Mill. When you start the next event with Thrall he runs into the stables where he will get ambushed by a pack.

Can be seen [here](https://youtu.be/VUOcYSwoZFs?t=246), video from TBC.

**Current behaviour**:
Currently this pack spawns, stands still for ~20 seconds, unattackable, until Thrall comes outside of the house and they become attackable.

**Expected behaviour**: 
I expect this pack to be spawned  slightly outside of the stables and instantly start moving towards thrall who is inside the stables. 

**Server Revision**: 
3519

**Comment by Tereneckla** [comment]
https://youtu.be/2holFQRMEoc?t=270

They become hostile here a bit after one of them says "Let's go"
Which is how I am experiencing it on the server.
