### ISSUE TITLE
[Item][Patch 2.0  / 2.4] Annihilator should be Main Hand only until patch 2.4

### ISSUE THREAD

**Issue by raethkcj** [Atlantiss/NetherwingBugtracker#7522]
https://wow.gamepedia.com/Patch_2.4.2
> Most Main-Hand weapons are now One-Hand weapons.

Thotbot links before and after patch 2.4.2:
http://web.archive.org/web/20080327123247/http://www.thottbot.com/i12798
http://web.archive.org/web/20080915185031/http://www.thottbot.com/i12798

**Current behaviour**:
One-Hand

**Expected behaviour**: 
Main Hand

**Server Revision**: 
3519

**Comment by Wolffenstein** [comment]
Fixed in rev 3529.
