### ISSUE TITLE
Tank over Def cap but crit twice

### ISSUE THREAD

**Issue by Sotomatic** [Atlantiss/NetherwingBugtracker#7525]
![Capture](https://user-images.githubusercontent.com/22602019/92636588-9b76c800-f2a5-11ea-94f0-8f8f62d92a67.PNG)
[//]: # (Enclose links to things related to the bug using http://wowhead.com or any other TBC database.)
[//]: # (You can use screenshot ingame to visual the issue.)
[//]: # (Write your tickets according to the format:)
[//]: # ([Quest][Azuremyst Isle] Red Snapper - Very Tasty!)
[//]: # ([NPC] Magistrix Erona)
[//]: # ([Spell][Mage] Fireball)
[//]: # ([Npc][Drop] Ghostclaw Lynx)
[//]: # ([Web] Armory doesnt work)
[//]: # (To find server revision type `.server info` command in the game chat.)

**Description**: 
Tank was over the 490 defense cap but was crit twice by Gruul's

**Current behaviour**:
Getting crit is possible despite being over defense cap

**Expected behaviour**: 
tank at 490+ defense should not be able to be crit

**Server Revision**: 
Karazhan 2.0.3 3526

**Comment by Tereneckla** [comment]
#7511 NPCs might have to high weapon skill

**Comment by Wolffenstein** [comment]
Fixed in rev 3529.
