### ISSUE TITLE
[Quest][Shattrath City] A call to battle! (Daily PvP) has wrong reward in text

### ISSUE THREAD

**Issue by JohnEU** [Atlantiss/NetherwingBugtracker#7526]
**Current behaviour**:
Quest states to reward 10 AP, but rewards 20 AP (due to recent buff on quest)

**Expected behaviour**: 
Should state to reward 20 AP.

**Server Revision**: 
3526

I did delete cache just in case. Did not resolve the issue.

![image](https://user-images.githubusercontent.com/55697857/92720539-063b0880-f365-11ea-9a96-2fbf2f512cce.png)

**Comment by Wolffenstein** [comment]
A fix has already been pushed and will be active after next server restart (will require cache clearing).
