### ISSUE TITLE
[NPC] Certain pirates don't give Steamwheedle Cartel reputation or spillover reputation 

### ISSUE THREAD

**Issue by filipboev** [Atlantiss/NetherwingBugtracker#7527]
[//]: # (Enclose links to things related to the bug using http://wowhead.com or any other TBC database.)
[//]: # (You can use screenshot ingame to visual the issue.)
[//]: # (Write your tickets according to the format:)
[//]: # ([Quest][Azuremyst Isle] Red Snapper - Very Tasty!)
[//]: # ([NPC] Magistrix Erona)
[//]: # ([Spell][Mage] Fireball)
[//]: # ([Npc][Drop] Ghostclaw Lynx)
[//]: # ([Web] Armory doesnt work)
[//]: # (To find server revision type `.server info` command in the game chat.)

**Description**: 
At a certain reputation standing with Steamwheedle Cartel factions, no reputation or spillover reputation is given anymore whilst killing pirates. Certain factions do have a reputation cap where they no longer receive any reputation from killing certain pirates, but the spillover for the other three remaining sibling factions should still occur.

Here are examples from retail players on how this is supposed to work, hold true from vanilla wow: https://wow.spectralcoding.com/insane/index.html#section_2.2.4

**Current behaviour**:
As per testing done on the main Netherwing realm, as well as on the PTR (at the time of writing rev. 3522) I have concluded that this is the current behaviour.

### Reputation status

Booty Bay: Revered
Everlook: Revered
Gadgetzan: Revered
Ratchet: Revered

Only Baron Longshore ([3467](https://tbcdb.com/?npc=3467)) has given rep, 25 for Ratchet and 12 spillover on the reset
Andre Firebrand([7883](https://tbcdb.com/?npc=7883))/Caliph Scorpidsting([7847](https://tbcdb.com/?npc=7847)) 0 rep (Albeit it says it adds 12 rep to Steamwheedle Cartel)
Non-unique pirates: 0 rep Booty Bay and 0 spillover
Fleet Master Firallon: 0 rep Booty Bay and 0 spillover (Albeit it says it adds 12 rep to Steamwheedle Cartel)

Booty Bay: Honored
Everlook: Honored
Gadgetzan: Honored
Ratchet: Honored

Andre Firebrand/Caliph Scorpidsting: 25 Gadgetzan rep, with 12 spillover
Tanaris non-unique pirates: 5 rep, 2 spillover
Fleet Master Firallon: 25 Booty Bay rep, 12 spillover
Bloodsail non-unique pirates: 0 rep and 0 spillover (Albeit it says it adds 2 rep to Steamwheedle Cartel)

Booty Bay: Friendly
Everlook: Friendly
Gadgetzan: Friendly
Ratchet: Friendly

Andre Firebrand/Caliph Scorpidsting: 25 Gadgetzan rep, with 12 spillover
Southsea non-unique pirates: 5 Gadgetzan rep, 2 spillover
Fleet Master Firallon: 25 Booty Bay rep, 12 spillover
Bloodsail non-unique pirates: 0 rep and 0 spillover (Albeit it says it adds 2 rep to Steamwheedle Cartel)

Screenshots:
These two following images do a correct spillover:
<img width="1893" alt="Screen Shot 2020-09-11 at 14 57 16" src="https://user-images.githubusercontent.com/1146940/92930211-107f0480-f442-11ea-85f7-6ce7ef0dc646.png">
<img width="1893" alt="Screen Shot 2020-09-11 at 14 57 25" src="https://user-images.githubusercontent.com/1146940/92930099-e9283780-f441-11ea-8659-ab032bbdf5c6.png">
The other two, do not do a correct spillover:
<img width="1893" alt="Screen Shot 2020-09-11 at 14 50 05" src="https://user-images.githubusercontent.com/1146940/92930172-01985200-f442-11ea-9481-93fea1ae12b1.png">
<img width="1893" alt="Screen Shot 2020-09-11 at 14 50 15" src="https://user-images.githubusercontent.com/1146940/92930147-f8a78080-f441-11ea-8451-03628ab29edc.png">

**Expected behaviour**: 

**_Southsea Freebooters_**: Give 5 Ratchet Rep until 11999 honored. 0 Ratchet Rep after. 2.5 spill over rep to all others through Exalted. Named mobs work the same except 25 rep and 12.5 spill over.
**_Venture Co.*_*: Give 5 Booty Bay until 11999 honored. 0 BB Rep after. 2.5 spill over rep to all others through Exalted. Named mobs supposedly work give 25 rep and 12.5 spill over, if any exist. 
**_Wastewander_**: Unconfirmed rep at friendly. Do not give Gadgetzan Rep past Friendly. 2.5 spill over rep to all others through Exalted.
**_Southsea Pirates_**: Give 5 Gadgetzan rep until 11999 honored. 0 Gadget Rep after. 2.5 spill over rep to all others through Exalted. Named mobs give 25 rep and 12.5 spill over.

**Server Revision**: 
_3519_

Related: #872  #7016

**Comment by sobiech6** [comment]
After reaching revered rep in Booty Bay, Gadgetzan and Ratchet pirates don't give reputation. Killing pirates in Tanaris giving informaciot +5 rep in steamwheedle cartel bo reputation don't grow.

**Comment by Godmatik** [comment]
Fixed several months ago - closing
