### ISSUE TITLE
([Quest][Alchemy] Master of Elixirs)

### ISSUE THREAD

**Issue by shawn571** [Atlantiss/NetherwingBugtracker#7528]
[//]: # (Enclose links to things related to the bug using http://wowhead.com or any other TBC database.)
[//]: # (You can use screenshot ingame to visual the issue.)
[//]: # (Write your tickets according to the format:)
[//]: # ([Quest][Azuremyst Isle] Red Snapper - Very Tasty!)
[//]: # ([NPC] Magistrix Erona)
[//]: # ([Spell][Mage] Fireball)
[//]: # ([Npc][Drop] Ghostclaw Lynx)
[//]: # ([Web] Armory doesnt work)
[//]: # (To find server revision type `.server info` command in the game chat.)

**Description**: The Master of Elixirs quest is not working with shared loot like other quests do.

**Current behaviour**: Shared loot system not working, someone else on same quest able to loot Essence of Infinity while I am not.

**Expected behaviour**: All players on this quest should be able to loot Essence of Infinity.

**Server Revision**: 3528

**Comment by Wolffenstein** [comment]
Shared loot is not enabled for quest items dropping in dungeons.
