### ISSUE TITLE
Spellpen is it working correctly in PvP?

### ISSUE THREAD

**Issue by Zippah** [Atlantiss/NetherwingBugtracker#7529]
Is spellpen working how it is supposed to? 

Reason im asking is that i have 70spellpen 5% spell hit. Im aware that racials and talents do require you to build more hit then that but its just not worth building more. 

But my main issue is that it really feels like a complete waste going for 70 spellpen. Its wierd when u have these stats and a druids mark of the wild buff is enough for him to fully resist my counterspell my frostbolt spells or other damaging spells. 

This happens way more often with my pets waterbolt and especially often my pet nova is resisted.

Can anyone confirm if spellpen actully is working how its supposed to?
And if so does my water elemental get any of my stats from spellhit and spellpen ?

Thanks for reading and hopefully i can get some confirmed info regarding this.

**Comment by Wolffenstein** [comment]
Yes, it's working correctly. No, water elemental does not inherit those values (as far as I'm aware).
