### ISSUE TITLE
[Pathing] One of the tresher pathing is off

### ISSUE THREAD

**Issue by mikefirefly** [Atlantiss/NetherwingBugtracker#753]
[//]: # (Enclose links to things related to the bug using http://wowhead.com or any other TBC database.)
[//]: # (You can use screenshot ingame to visual the issue.)
[//]: # (Write your tickets according to the format:)
[//]: # ([Quest][Azuremyst Isle] Red Snapper - Very Tasty!)
[//]: # ([NPC] Magistrix Erona)
[//]: # ([Spell][Mage] Fireball)
[//]: # ([Npc][Drop] Ghostclaw Lynx)
[//]: # ([Web] Armory doesnt work)

**Description**: 
One of the tresher pathing is off.

**Current behaviour**:
Takes a long detour when attacked: https://streamable.com/mvgw0

**Expected behaviour**: 
Should take straight path to the player.

**Server Revision**: 
2072

**Comment by Dpthx** [comment]
.gps when you encounter this problem

**Comment by narayagh** [comment]
> .gps when you encounter this problem

Will do next time, for now you can see the exact coords in my clip.

**Comment by Wolffenstein** [comment]
Fixed
