### ISSUE TITLE
[item] Druid Tier5 for Moonkin has incorrect 2.0 stats/gem colors/socket bonuses

### ISSUE THREAD

**Issue by BezawitNW** [Atlantiss/NetherwingBugtracker#7530]
The current stats of Druid Tier5 (Moonkin) are incorrect (they seem to be pulled from beta). Credit goes to Daytrip for finding the correct stats. These were the stats as of 18 days before 2.1 launched: 

http://web.archive.org/web/20070504054330/http://wow.allakhazam.com:80/db/itemset.html?setid=643

Changes that need to be made:

Helm: Socket bonus needs to be changed to +6 Stamina

Shoulder: +3 damage/healing needs to be added and +3 Stamina needs to be added. Socket colors changed to Red + Blue. Socket bonus changed to +5 Spell damage/healing.

Chest: Socket bonus needs to be changed to +4 Spell Hit

Gloves: No changes

Pants: No Changes

Also thank you to Terenckla for looking into this + helping verify.

**Comment by Tereneckla** [comment]
Resto Druid T5 shoulders also use the pre 2.0.10 values currently

![image](https://user-images.githubusercontent.com/50233983/92993482-3368f180-f4f2-11ea-9993-1f6d06f4160a.png)
![image](https://user-images.githubusercontent.com/50233983/92993488-4085e080-f4f2-11ea-8ca7-379727f33cab.png)
http://web.archive.org/web/20070504052630/http://wow.allakhazam.com/db/itemset.html?setid=642

**Comment by Wolffenstein** [comment]
Fixed in rev 3529.
