### ISSUE TITLE
Able to fly at max flying mount speed underwater (with steps to repeat)

### ISSUE THREAD

**Issue by BugSquasher01** [Atlantiss/NetherwingBugtracker#7531]
[//]: # (Enclose links to things related to the bug using http://wowhead.com or any other TBC database.)
[//]: # (You can use screenshot ingame to visual the issue.)
[//]: # (Write your tickets according to the format:)
[//]: # ([Quest][Azuremyst Isle] Red Snapper - Very Tasty!)
[//]: # ([NPC] Magistrix Erona)
[//]: # ([Spell][Mage] Fireball)
[//]: # ([Npc][Drop] Ghostclaw Lynx)
[//]: # ([Web] Armory doesnt work)
[//]: # (To find server revision type `.server info` command in the game chat.)

**Description**: 
You are able to retain your flying mounted status whilst under water, and continue travelling underwater at your flying mount's maximum mount speed.

**Current behaviour**:
Currently you can stay mounted on a flying mount underwater, and travel under water on your mount's maximum mounted speed.

Steps to re-produce:
1) Stand on the edge of a body of water, just far enough in before you become "swimming"
2) Cast flying mount
3) Move forward and down into the body of water
4) When deep enough inside the water, press spacebar once to force your characters direction upwards
5) Full flying mount speed underwater is now enabled

Youtube video displaying steps: https://www.youtube.com/watch?v=OeeTCHDocIU&feature=youtu.be

**Expected behaviour**: 
To instantly dismount when your character is deep enough to be considered underwater/would need to swim.

**Comment by Wolffenstein** [comment]
Fixed in rev 3529.
