### ISSUE TITLE
[Quest] Triage bugged for me

### ISSUE THREAD

**Issue by SwimzwithSharkz** [Atlantiss/NetherwingBugtracker#7533]
[//]: # (Enclose links to things related to the bug using http://wowhead.com or any other TBC database.)
[//]: # (You can use screenshot ingame to visual the issue.)
[//]: # (Write your tickets according to the format:)
[//]: # ([Quest][Azuremyst Isle] Red Snapper - Very Tasty!)
[//]: # ([NPC] Magistrix Erona)
[//]: # ([Spell][Mage] Fireball)
[//]: # ([Npc][Drop] Ghostclaw Lynx)
[//]: # ([Web] Armory doesnt work)
[//]: # (To find server revision type `.server info` command in the game chat.)

**Description**: The First Aid Quest, Triage, is bugged for me. (necessary for bandage progression.)
https://classic.wowhead.com/quest=6624/triage
I just tried yet again, but failed. Add-ons are all off, Cache is deleted. 
I have level 225 first aid, so qualify and able to Accept the Quest.
https://imgur.com/a/qPcUylm   The mobs you can see in my minimap Are Not Visible to me in game.
https://imgur.com/a/8u5rrKV

**Current behaviour**: For starters I would think it should show a yellow font on the screen for the progress after a successful bandage on a mob, but doesn't.  & the injured mobs often spawn on top of each other, plus only One spawn type will usually show at a time. 

**Expected behaviour**: More than one should spawn at a time and not on top of each other, plus it took awhile for the first one to appear. And should probably show the number of mobs healed progression.

**Server Revision**: 2.0.3 rev 3528

**Comment by Tereneckla** [comment]
I sadly am not able to reproduce this.

For the quest progress matter: Your goal is 15 saved before you fail the event, not save 15 overall.
#1533

**Comment by SwimzwithSharkz** [comment]
aha, yet w/ only one injured spawning at a time, then towards the end of healing one
 (yet usually multiple copies of the mob stacked) another arrives (or more) there is no way
I will be able to further progress my First Aid.
Someone can dm me & I can go flunk Triage quest again and show yu.
Or hmmmm, autocomplete is also possible. hint hint.
TY
Gankerz Ally 70 nelf huntard

**Comment by raethkcj** [comment]
They did spawn on top of each other for me, but that didn't prevent me from completing the quest.

**Comment by SwimzwithSharkz** [comment]
Thats nice Raeth, yet I just retried to do Triage yet again. 
There is no way I can complete it with a late start for the One at a time mobs, 
then No Mobs At All. sigh.
ss of empty room  https://imgur.com/a/7cQ8s4O
& the quest never "Failed" this time.  
https://imgur.com/a/Mu3jWNU

**Comment by raethkcj** [comment]
**Current Behavior:**
https://www.youtube.com/watch?v=_zVTV9_EKTQ
Only one injured soldier is spawns upon acceping the quest. They continue to spawn one at a time unless you fall behind. They are able  to spawn multiple on the same spawn point.

**Expected Behavior:**
https://www.youtube.com/watch?v=3Pn7Eg7u9uo
Six injured soldiers immediately spawn, exactly one on each spawn point.
When a soldier dies or is finished being bandaged, it triggers a 25 second respawn.
They cannot spawn multiple at the same spawn point.

**Comment by SwimzwithSharkz** [comment]
Interesting.
Yet I do believe my mobs or my latency coz mine to be undoable.
The first mob takes forever to arrive, some spawn on top of each other,
some die after I bandage them &  must be bugged coz this time I ran out
of mobs to heal and the Quest Never Failed, still in my book as g2g sigh.

**Comment by Godmatik** [comment]
It's definitely not blizzlike, but as long as you heal them in-time, it can be completed, worked fine for me.

**Comment by SwimzwithSharkz** [comment]
Halp,  
Plz Auto Complete this Quest for me, 
as I am UNABLE to COMPLETE it. 
Shank yu
Gankerz

**Comment by SwimzwithSharkz** [comment]
TY! 
Completed, 
Close plz.
<3
