### ISSUE TITLE
[Priest] [Spell] Lightwell

### ISSUE THREAD

**Issue by AndrewReynen** [Atlantiss/NetherwingBugtracker#7534]
**Current behaviour**:

- Lightwell breaks casting/eating/drinking when clicked on
- [https://www.youtube.com/watch?v=6ofbHD6BBBE](https://www.youtube.com/watch?v=6ofbHD6BBBE)

**Expected behaviour**: 

- Lightwell should be able to be clicked while doing other animations without breaking the animation
- [https://vanilla-wow.fandom.com/wiki/Lightwell](https://vanilla-wow.fandom.com/wiki/Lightwell)

**Comment by Tereneckla** [comment]
Some proof of that would be nice.

**Comment by AndrewReynen** [comment]
Updated with some proof @Tereneckla

**Comment by Wolffenstein** [comment]
Fixed in rev 3529.
