### ISSUE TITLE
[Spell][Hunter] Some pet abilities cost a LOT more to learn from pet trainers than they should

### ISSUE THREAD

**Issue by viktor-wolf** [Atlantiss/NetherwingBugtracker#7535]
[//]: # (Enclose links to things related to the bug using http://wowhead.com or any other TBC database.)
[//]: # (You can use screenshot ingame to visual the issue.)
[//]: # (Write your tickets according to the format:)
[//]: # ([Quest][Azuremyst Isle] Red Snapper - Very Tasty!)
[//]: # ([NPC] Magistrix Erona)
[//]: # ([Spell][Mage] Fireball)
[//]: # ([Npc][Drop] Ghostclaw Lynx)
[//]: # ([Web] Armory doesnt work)
[//]: # (To find server revision type `.server info` command in the game chat.)

**Description**: 
Pretty much the title. For example, at revered rep it would cost me 3g6s to learn Frost Resistance (rank 4) while [WoWWiki says it should cost 64s80c (unsure if with discount)](https://wowwiki.fandom.com/wiki/Resistance_(pet)). This seems to be corroborated by Classic Wowhead, where the cost is similar. Some other skills like Great Stamina and Natural Armor also seem to be affected, but I wasn't able to find a source about them apart from Classic Wowhead.

**Current behaviour**:
Makes my coin pouch cry.

**Expected behaviour**: 
Should cost less.

**Server Revision**: 3528

**Comment by Wolffenstein** [comment]
Fixed in rev 3532.
