### ISSUE TITLE
Stoneclaw totem threat reset bug

### ISSUE THREAD

**Issue by Zuntrix** [Atlantiss/NetherwingBugtracker#7536]
[//]: # (Enclose links to things related to the bug using http://wowhead.com or any other TBC database.)
[//]: # (You can use screenshot ingame to visual the issue.)
[//]: # (Write your tickets according to the format:)
[//]: # ([Quest][Azuremyst Isle] Red Snapper - Very Tasty!)
[//]: # ([NPC] Magistrix Erona)
[//]: # ([Spell][Mage] Fireball)
[//]: # ([Npc][Drop] Ghostclaw Lynx)
[//]: # ([Web] Armory doesnt work)
[//]: # (To find server revision type `.server info` command in the game chat.)

**Description**: 
Stoneclaw totem can be used to reset mobs at will.

**Current behaviour**:
https://www.youtube.com/watch?v=n5CpWuOyr98

This is 100% reproducible and can be used to reset mobs if you accidentally pull too many.

**Expected behaviour**: 
Not reset non-targeted enemy.

**Server Revision**: 
3528

**Comment by Madjarid** [comment]
Same here

**Comment by Wolffenstein** [comment]
Fixed in rev 3533.
