### ISSUE TITLE
[Dungeon][NPC] Mechanar Tempest-Forge Destroyer & 2 x Astromage shouldn't be linked

### ISSUE THREAD

**Issue by Tenoutoften** [Atlantiss/NetherwingBugtracker#7538]
**Description /Current behaviour**: 
The [[NPC]Tempest-forge destroyer#19735(N) / 21542(H)](https://tbc-twinhead.twinstar.cz/?search=tempest-forge+destroyer) & 2 x [[NPC]Sunseeker Astromancer#19168(N) / 21539(H)](https://tbc-twinhead.twinstar.cz/?search=sunseeker+astromage) by the elevator in Mechanar are incorrectly linked together.

**Expected behaviour**: 
The [[NPC]Tempest-forge destroyer#19735(N) / 21542(H)](https://tbc-twinhead.twinstar.cz/?search=tempest-forge+destroyer) shouldn't be linked together with the 2 x [[NPC]Sunseeker Astromancer#19168(N) / 21539(H)](https://tbc-twinhead.twinstar.cz/?search=sunseeker+astromage) but be possible to single pull when it's patrolling away from the 2 x [[NPC]Sunseeker Astromancer#19168(N) / 21539(H)](https://tbc-twinhead.twinstar.cz/?search=sunseeker+astromage).

The 2 x [[NPC]Sunseeker Astromancer#19168(N) / 21539(H)](https://tbc-twinhead.twinstar.cz/?search=sunseeker+astromage) should be linked with one another

**Server Revision**: 
3528

**Comment by Wolffenstein** [comment]
Fixed in rev 3658.
