### ISSUE TITLE
Pendant of the Agate Shield respawn timer

### ISSUE THREAD

**Issue by berezkinalexey** [Atlantiss/NetherwingBugtracker#7539]
[//]: # (Enclose links to things related to the bug using http://wowhead.com or any other TBC database.)
[//]: # (You can use screenshot ingame to visual the issue.)
[//]: # (Write your tickets according to the format:)
[//]: # ([Quest][Azuremyst Isle] Red Snapper - Very Tasty!)
[//]: # ([NPC] Magistrix Erona)
[//]: # ([Spell][Mage] Fireball)
[//]: # ([Npc][Drop] Ghostclaw Lynx)
[//]: # ([Web] Armory doesnt work)
[//]: # (To find server revision type `.server info` command in the game chat.)

Decription:
The respawn timer is way too long.

How it works:
It takes a  very long time to respawn the next recipe in the vendor.

How it should work:
It should be back in the vendor's table 5 minutes after the previous purchase.

Source (you should point out proofs of your report, please give us some source):
"Only one recipe on stock, recipe repopped 5 minutes after buying." on 2009/10/22 (Patch 3.2.2)
http://www.wowhead.com/item=20970/design-pendant-of-the-agate-shield#comments

**Comment by Wolffenstein** [comment]
Fixed in rev 3532.
