### ISSUE TITLE
[NPC] Invisivle Beal'dun Rifleman

### ISSUE THREAD

**Issue by totaemoeggerli** [Atlantiss/NetherwingBugtracker#754]
[//]: # (Enclose links to things related to the bug using http://wowhead.com or any other TBC database.)
[//]: # (You can use screenshot ingame to visual the issue.)
[//]: # (Write your tickets according to the format:)
[//]: # ([Quest][Azuremyst Isle] Red Snapper - Very Tasty!)
[//]: # ([NPC] Magistrix Erona)
[//]: # ([Spell][Mage] Fireball)
[//]: # ([Npc][Drop] Ghostclaw Lynx)
[//]: # ([Web] Armory doesnt work)

**Description**: 
[Beal'dun Rifleman](https://www.wowhead.com/npc=3377/baeldun-rifleman) is invisible and attacks player, reappeares when moved away.
I saw the same NPC act normal after it respawn. Similar thing happened here: https://github.com/Atlantiss/NetherwingBugtracker/issues/573 . 99% sure there was no respawn involved in this case.

**Current behaviour**:
https://gfycat.com/PhonyBoringDragonfly

**Expected behaviour**: 
https://gfycat.com/gifs/detail/GrimyMenacingBasenji

**Server Revision**: 
2072

**Comment by aresbrutus** [comment]
This is due to a TBC client issue. Nothing the server can do unfortunately.
