### ISSUE TITLE
[Movement][Mount] Dismount in shallow waters

### ISSUE THREAD

**Issue by kern3lpan1c** [Atlantiss/NetherwingBugtracker#7540]
**Description**: 
Players should not get dismounted in shallow waters (waters that are a lower number z axis than the mount's height)
**Current behaviour**:
Players are dismounted when treading through shallow waters.

Example:
![eg](https://user-images.githubusercontent.com/1146940/93020665-946df380-f5de-11ea-8b57-2758b4e4bb18.gif)

**Expected behaviour**: 
Players are not dismounted in shallow, walkable waters.
**Server Revision**: 
3529

**Comment by Godmatik** [comment]
I'm guessing it's a side-effect from the fix on https://github.com/Atlantiss/NetherwingBugtracker/issues/7531

**Comment by Peglaa** [comment]
![image](https://user-images.githubusercontent.com/15163719/93025478-9f388080-f5fe-11ea-933e-caba4b8be2bd.png)

Doesn't seem to be live yet so could be its own issue.

**Comment by Wolffenstein** [comment]
![obraz](https://user-images.githubusercontent.com/1576644/93722218-83505400-fb95-11ea-9a43-19e934e082e9.png)

can't reproduce.

**Comment by kern3lpan1c** [comment]
I am still able to reproduce it. @Wolffenstein. This is on the Netherwing realm, by the way.
![nw-water-test](https://user-images.githubusercontent.com/1146940/93754749-7cabf600-fc02-11ea-89db-a1c61b09c080.gif)

The same thing happens with a flying mount as well, on deeper waters it's fine, but as soon as it hits shallow water it dismounts.

**Comment by kern3lpan1c** [comment]
@Wolffenstein, this should be re-opened as it is reproducible constantly on Netherwing.
