### ISSUE TITLE
Mongoose PPM too low

### ISSUE THREAD

**Issue by Fierywind** [Atlantiss/NetherwingBugtracker#7542]
[//]: # (Enclose links to things related to the bug using http://wowhead.com or any other TBC database.)
[//]: # (You can use screenshot ingame to visual the issue.)
[//]: # (Write your tickets according to the format:)
[//]: # ([Quest][Azuremyst Isle] Red Snapper - Very Tasty!)
[//]: # ([NPC] Magistrix Erona)
[//]: # ([Spell][Mage] Fireball)
[//]: # ([Npc][Drop] Ghostclaw Lynx)
[//]: # ([Web] Armory doesnt work)
[//]: # (To find server revision type `.server info` command in the game chat.)

**Description**: The Mongoose enchant has a 0.56 PPM after 130 minutes of auto attacking a target, which is very low

**Current behaviour**: Mongoose has a 0.56 PPM, or somewhere close to that

**Expected behaviour**: All sources I can find put Mongoose at 1-1.2 PPM

**Server Revision**: 3528

**Comment by raethkcj** [comment]
I'm not sure what you're using to count PPM, but I'm going to guess Procodile. If so, a few things to keep in mind:

1) PPM is not an actual time-based mechanic, it's simply a way of normalising weapon speed to proc chance.
`1 PPM enchant on 3.5 speed weapon: 1 * 3.5 / 60 = 5.83% chance per hit`
`1.5 PPM enchant on 1.7 speed weapon: 1.5 * 1.7 / 60 = 4.25% chance per hit`

2) Mongoose can only proc on *hits*. You didn't say how you were testing, but make sure you're only counting actual hits (or crits), and not miss, dodge, or parry. If you're not hit/expertise capped for your target, your proc rate in a given time period will appear low.

3) Procodile does not count procs that happen while you already have the buff active. Mongoose has no internal cooldown, and it can refresh itself while it is active. If you are using this to count procs, you are missing many of them.

**Comment by Fierywind** [comment]
I am using DPSmate to count, and the test was performed on the unkillable mob in blasted lands - I'll double check that dpsmate is tracking procs while the buff is already active, and will change my test target and make sure I filter for hits only. I know how PPM works, but when doing nothing abut auto attacking there's no reason to present weapon speed because it's not relevant.

**Comment by raethkcj** [comment]
I'm currently testing on Servant of Razelikh in Blasted Lands on PTR, here's my results after 25 minutes / 1000 swings (will keep  going, this is just what I have so far):

![image](https://user-images.githubusercontent.com/7716908/93041590-81751680-f612-11ea-8cba-fcc4f55c5521.png)

**Comment by raethkcj** [comment]
Just for reference, here are the macros I'm using to track hits:
`/run local k,f=0,CreateFrame('frame')f:RegisterEvent("UNIT_COMBAT")f:SetScript('OnEvent', function(n,e,u,s) if(u=="target") then k=k+1 DEFAULT_CHAT_FRAME:AddMessage("h: "..k) end end)
`

And to track procs:
`/run  local m,k,f=1,0,CreateFrame('frame')f:RegisterEvent("COMBAT_LOG_EVENT")f:SetScript('OnEvent',function(_,e,t,s,_,_,_,_,_,_,_,n)if(s:match("REFR") and n:match("Spee")) then k=k+m m=1-m if(m==1)then DEFAULT_CHAT_FRAME:AddMessage("p: "..k) end end end)`

**Comment by raethkcj** [comment]
Bit lower after ~3700 hits

![image](https://user-images.githubusercontent.com/7716908/93045342-8e970300-f61c-11ea-84d1-4746ed4c7787.png)

**Comment by Fierywind** [comment]
that's a fairly large gap after 3700 swings

**Comment by raethkcj** [comment]
Here's my hits so far with a 3.2 two-handed weapon:
![image](https://user-images.githubusercontent.com/7716908/93125026-28e45e80-f690-11ea-91c0-144f1dd093b2.png)

**Comment by Fierywind** [comment]
I've been busy, but finally did some testing of my own again. I used the macros provided by @raethkcj and attacked the Servant of Groll in Blasted lands, and here are my results:

1.7 weapon speed
9000 hits
215 procs
proc % 2.388%
PPM 0.8431372549 -  very in line with the 3.2 speed testing done by raeth.

At 9000 hits, unless there is something that hasn't been addressed now that is flawed in these rounds of testing, I think it's apparent that mongoose's PPM, while being higher than my initial testing, is definitely below 1 PPM.

**Comment by Wolffenstein** [comment]
It has exactly 1 PPM in the database. If you wish to calculate the proc chance, here's the formula currently used by core:

`std::floor((WeaponSpeed * PPM) / 600.0f);`

**Comment by Fierywind** [comment]
@Wolffenstein you might have it set to 1 ppm in the database, but are you going to write off a test of 9k autos? Do you think it's still variance at that point, or could it indicate there's an issue somewhere?

**Comment by MghTG** [comment]
Isn't it the case that the core uses std:floor when calculating the chance of ppm based spells, causing it to round down the actual chance?
