### ISSUE TITLE
Blood Oath of the Netherwing Quest bug (can't be picked up after incorrect completion of pre-Q)

### ISSUE THREAD

**Issue by me4again** [Atlantiss/NetherwingBugtracker#7543]
[Blood Oath of the Netherwing] Quest can not be picked up after completing the quest [Ally of the Netherwing] incorrectly by not talking to Karynaku to ''return you to Mordenai in the Netherwing Fields'' to talk to Mordenai.

Please fix a way so players can pick up the quest: Blood Oath of the Netherwing at questgiver Mordenai after completing [Ally of the Netherwing] incorrectly.

**Comment by me4again** [comment]
Have to confirm if after restart it works.

**Comment by lejosh86** [comment]
This seems to still be bugged.
I've finished the pre-quest Ally of the Netherwing, and I have 300 riding but I can't pick-up blood Oath of the Netherwing :(

**Comment by Godmatik** [comment]
@lejosh86 
We are not in patch 2.1 yet so that part of the Netherwing chain and the dailies that come after it are not yet released.
