### ISSUE TITLE
Warrior charge trough walls in arena .

### ISSUE THREAD

**Issue by mobshiv** [Atlantiss/NetherwingBugtracker#7545]
Warrior in battle stance can charge his enemies trough wall .

More here https://clips.twitch.tv/AntediluvianFlirtyHippoCmonBruh

Thanks

**Comment by Easyfraggy** [comment]
Is that pillar even LOS?

**Comment by Wolffenstein** [comment]
That pillar does not block Line of Sight, therefore you can charge targets hiding behind it as long as a path can be found. Invalid.
