### ISSUE TITLE
[NPC] Twilight Keeper Havunth

### ISSUE THREAD

**Issue by Roak** [Atlantiss/NetherwingBugtracker#7547]
[//]: # (Enclose links to things related to the bug using http://wowhead.com or any other TBC database.)
[//]: # (You can use screenshot ingame to visual the issue.)
[//]: # (Write your tickets according to the format:)
[//]: # ([Quest][Azuremyst Isle] Red Snapper - Very Tasty!)
[//]: # ([NPC] Magistrix Erona)
[//]: # ([Spell][Mage] Fireball)
[//]: # ([Npc][Drop] Ghostclaw Lynx)
[//]: # ([Web] Armory doesnt work)
[//]: # (To find server revision type `.server info` command in the game chat.)

**Description**: NPC is bugged and is dealing IKs to lower geared people and too strong spell explosion hits overall.

**Current behaviour**: Fire nova deals 1200-2000 damage.

**Expected behaviour**: https://classic.wowhead.com/npc=11804/twilight-keeper-havunth#comments Should deal 200-300 damage 

**Server Revision**:

**Comment by Wolffenstein** [comment]
Fixed in rev 3532.
