### ISSUE TITLE
[Dungeon][Movement][NPC]Shattered Halls, Warhounds go way off their Houndmaster

### ISSUE THREAD

**Issue by Tenoutoften** [Atlantiss/NetherwingBugtracker#7548]
**Description/Current behaviour**: 
The patrols with [[NPC]Shattered Hand Houndmaster#17670(N)/20588(H)](http://tbc.cavernoftime.com/?search=shattered+hand+houndmaster) & 2 x [[NPC]Rabid Warhound#17669(N)/20574(H)](http://tbc.cavernoftime.com/?search=warhound#npcs) within Shattered Halls has an issue with the  2 x [[NPC]Rabid Warhound#17669(N)/20574(H)](http://tbc.cavernoftime.com/?search=warhound#npcs) going off on their own waypoints several times.

There are two of these patrols, both of them are after the gauntlet, but before the ogre boss [[NPC]Warbringer O'mrogg#16809(N)/20596(H)](https://tbc-twinhead.twinstar.cz/?search=warbringer+o%27mrogg).

You wont see the dogs going far off in any of these videos
https://youtu.be/cKWItzTqJ1g?t=65
https://youtu.be/DKDGhZ6F5vE?t=917
https://youtu.be/DKDGhZ6F5vE?t=955
https://youtu.be/4VFpnpn4_ng?t=425
https://youtu.be/4VFpnpn4_ng?t=632

**Expected behaviour**: 
2 x [[NPC]Rabid Warhound#17669(N)/20574(H)](http://tbc.cavernoftime.com/?search=warhound#npcs) expected to follow closely with their  [[NPC]Shattered Hand Houndmaster#17670(N)/20588(H)](http://tbc.cavernoftime.com/?search=shattered+hand+houndmaster) rather than going back and forth.

**Server Revision**: 
3530

**Comment by Godmatik** [comment]
Rev 4016 - still an issue - their waypoints need to be reworked just a bit, occasionally the dogs go off a bit on their own but correct themselves after a couple of seconds.

Dogs that are with IDs 2, 3, and 4 of 17670/20588

**Comment by Godmatik** [comment]
Fixed now with movement rework
