### ISSUE TITLE
Ritual of Souls Consuming Charges When Player Already Has That Healthstone

### ISSUE THREAD

**Issue by Fierywind** [Atlantiss/NetherwingBugtracker#7549]
[//]: # (Enclose links to things related to the bug using http://wowhead.com or any other TBC database.)
[//]: # (You can use screenshot ingame to visual the issue.)
[//]: # (Write your tickets according to the format:)
[//]: # ([Quest][Azuremyst Isle] Red Snapper - Very Tasty!)
[//]: # ([NPC] Magistrix Erona)
[//]: # ([Spell][Mage] Fireball)
[//]: # ([Npc][Drop] Ghostclaw Lynx)
[//]: # ([Web] Armory doesnt work)
[//]: # (To find server revision type `.server info` command in the game chat.)

**Description**: Up until now, if a player already had a certain rank of healthstone, and they then clicked on a soulwell giving that rank, it would not consume a charge of the soulwell. Since the last update, or one of the very recent ones at least, a charge is now consumed every single click. I believe this was affecting the mage table as well.

**Current behaviour**: Soulwell charge is consumed for every click, regardless of whether a healthstone is given or not.

**Expected behaviour**: Soulwell charge is only consumed if a healthstone is given.

**Server Revision**: 3530

**Comment by Wolffenstein** [comment]
Fixed in rev 3533.
