### ISSUE TITLE
[quest] [droprate] Stone tokens

### ISSUE THREAD

**Issue by Omarthegreatone** [Atlantiss/NetherwingBugtracker#755]
**Description**: 
Extremly low droprate of "Stone Tokens" quest, might take hour(s) to complete.
**Current behaviour**:

**Expected behaviour**: 

**Server Revision**:

**Comment by tcberk12** [comment]
http://classicdb.ch/?quest=556
https://www.wowhead.com/item=3714/worn-stone-token

The comments seem to follow a trend. If the comment was made before 3.0, there are complains about the drop rate. Any comment after patch 3.0 indicates a near 100% drop rate.

Not sure what your sample size is, but it seems like the rate should be rather low.

Some comment snippets:

Patch 2.3.0
> After clearing the entire camp, I received 2 Worn Stone Tokens.

Patch 2.4.2
> I killed more than 20 and only got 2.

Patch 2.4.3
> While I find the drop rate of this quest horrific, I've developed a saner way of doing it rather than accessing it through Hillsbrad.

--------

Patch 3.0.3
> Drop rate has been changed to 100%. omg awesome

Patch 3.1.3
> Also, drop rate confirmed at 100%.

**Comment by Easyfraggy** [comment]
Linked for reference https://github.com/Atlantiss/NetherwingBugtracker/issues/756

**Comment by aresbrutus** [comment]
They are supposed to be very low as tcberk already mentioned. But NW had it set to too low so it will be upped a bit in one of the upcoming updates.
