### ISSUE TITLE
Action bars become always shown after opening the spellbook for a minute or so 

### ISSUE THREAD

**Issue by Madjarid** [Atlantiss/NetherwingBugtracker#7550]
**Description**: 
Action bars become always shown upon looking at the spellbook for about a minute. The only way to turn it off again (that I know of) is relogging. 

**Current behaviour**:
Action bars become always shown upon looking at the spellbook for about a minute. 

**Expected behaviour**: 
Action bars stay hidden/not always shown. 

**Server Revision**: 
3531

**Comment by Wolffenstein** [comment]
Clientside.

**Comment by Godmatik** [comment]
@Madjarid reloading UI fixes it also and is faster, it's a TBC client bug
