### ISSUE TITLE
[Core][Spell]Max rank Power Word: Fortitude can be overwritten by lower ranks & Other lots of other buff bugs

### ISSUE THREAD

**Issue by Tenoutoften** [Atlantiss/NetherwingBugtracker#7551]
**Description / Current behaviour**: 
* Currently max rank of [[Spell]Power Word: Fortitude](http://tbc.cavernoftime.com/?search=power+word%3A+fortitude) can be overwritten by lower ranks, it can also be overwritten by [[Spell]Scroll of Stamina](http://tbc.cavernoftime.com/?search=scroll+of+stamina)
* Whenever you respec as a Paladin you have to re-learn [[Spell]Greater Blessing of Kings](http://tbc.cavernoftime.com/spell=25898) from the trainer; previously reported https://github.com/Atlantiss/NetherwingBugtracker/issues/5646, and  [[Spell]Prayer of Spirit](http://tbc.cavernoftime.com/?search=prayer+of+spirit) is similarly affected
* Rebuffing a variety of buffs causes the player/NPC to lose the resources, they should be kept, reported previously https://github.com/Atlantiss/NetherwingBugtracker/issues/3280 this was fixed for Fortitude https://github.com/Atlantiss/NetherwingBugtracker/issues/1934
* Currently you can overwrite [[Spell]Greater Blessing of Kings](http://tbc.cavernoftime.com/spell=25898), with more than 10 minutes duration remaining with lesser blessings of the same type. Greater Blessings shouldn't be able to be overwritten by a lesser blessing of the same type, unless it has less than 10 minutes remaining. This bug might apply to other classes priest/mage etc, I haven't checked.

**Expected behaviour**: 
* Higher ranks of buffs should not be removed by lower ranks of buffs.
* Once respeced, abilities should be automatically re-learned if the player has trained them previously.
* One should not lose the power resources from re-buffing.
* Greater blessings with >10 min remaining shouldn't be able to be overwritten by lesser blessings of the same type. 

**Server Revision**: 
3531

**Comment by Wolffenstein** [comment]
Fixed in rev 3533.
