### ISSUE TITLE
[Spell] [Priest] Mind Control - Teleporting caster to the target's position.

### ISSUE THREAD

**Issue by tazmonian** [Atlantiss/NetherwingBugtracker#7552]
[//]: # (Enclose links to things related to the bug using http://wowhead.com or any other TBC database.)
[//]: # (You can use screenshot ingame to visual the issue.)
[//]: # (Write your tickets according to the format:)
[//]: # ([Quest][Azuremyst Isle] Red Snapper - Very Tasty!)
[//]: # ([NPC] Magistrix Erona)
[//]: # ([Spell][Mage] Fireball)
[//]: # ([Npc][Drop] Ghostclaw Lynx)
[//]: # ([Web] Armory doesnt work)
[//]: # (To find server revision type `.server info` command in the game chat.)

**Description**: In arena match ID 36943 manually removing the Mind Control buff teleported the casting priest to the target's new position. 

**Current behaviour**: 
Mind Control behaving strangely in many situations when used versus other Players. Teleporting caster to targets position. Caster taking target's fall damage. Most unintended behaviors seem to occur when Mind Control ends prematurely.

**Expected behaviour**: 
Mind Control's caster should be unaffected by target's damage or positional changes regardless of how or when it is broken.

**Server Revision**: 
3531

**Comment by Godmatik** [comment]
Was fixed last year sometime - closing
