### ISSUE TITLE
[Quest][Object] Silithid Mound for quest Egg Hunt not autolooting

### ISSUE THREAD

**Issue by raethkcj** [Atlantiss/NetherwingBugtracker#7553]
**Description**: 
When looting Silithid Mound, several types of silithid mobs spawn, all in groups of 2.

**Current behaviour**:
With autoloot on, the mobs attack you before the items are looted. This cancels the loot window. Whether you kill or reset the mobs, the Silithid Mound despawns instantly the next time you click it, making the items totally unlootable.

**Expected behaviour**: 
With autoloot on, the items get looted into your inventory before the mobs hit you, allowing you to complete the quest.

**Server Revision**: 
3531

**Comment by Wolffenstein** [comment]
Can't reproduce/works fine for me.
