### ISSUE TITLE
[Paladin] Crit Rating vanishes when equipping Hammer of Destiny

### ISSUE THREAD

**Issue by Eripbuster** [Atlantiss/NetherwingBugtracker#7554]
**Description**: Crit Rating drops when equipping Hammer of Destiny

**Current behaviour**: Crit rating inexplicably drops when equipping Hammer of Destiny

**Expected behaviour**: Crit rating remains the same

**Server Revision**: 3531^

![image](https://user-images.githubusercontent.com/71376084/93312762-dfb71a80-f807-11ea-8741-18081724e2c4.png)
![image](https://user-images.githubusercontent.com/71376084/93312799-ecd40980-f807-11ea-8ee3-76a9fd59930a.png)

**Comment by Godmatik** [comment]
weapon skill?
