### ISSUE TITLE
[Quest - NPC] Cyrukh the Firelord Overtuned.

### ISSUE THREAD

**Issue by bidaumm** [Atlantiss/NetherwingBugtracker#7555]
**Description**: 
The NPC that spawns for the quest  The Cipher of Damnation named Cyrukh the Firelord is incorrectly tuned.
He is hitting a bear form tank for 4k per melee swing this makes the quest next to impossible to complete properly and has to be cheesed by just letting the NPCs kill him whilst you afk.

https://www.wowhead.com/npc=21181/cyrukh-the-firelord#comments:id=38571
Players from wowhead show him hitting for 1k melee swings max.

**Server Revision**: 
Atlantiss Karazhan | Content patch: 2.0.3 | Revision: 3531

**Comment by Wolffenstein** [comment]
Fixed in rev 3532.
