### ISSUE TITLE
mace sp not scaling right

### ISSUE THREAD

**Issue by cremariokara** [Atlantiss/NetherwingBugtracker#7556]
[//]: # (Enclose links to things related to the bug using http://wowhead.com or any other TBC database.)
[//]: # (You can use screenshot ingame to visual the issue.)
[//]: # (Write your tickets according to the format:)
[//]: # ([Quest][Azuremyst Isle] Red Snapper - Very Tasty!)
[//]: # ([NPC] Magistrix Erona)
[//]: # ([Spell][Mage] Fireball)
[//]: # ([Npc][Drop] Ghostclaw Lynx)
[//]: # ([Web] Armory doesnt work)
[//]: # (To find server revision type `.server info` command in the game chat.)

**Description**: Hammer of the Penitent not working correct

**Current behaviour**: Gives 1 SP

**Expected behaviour**: Should give 76 SP
![womace](https://user-images.githubusercontent.com/71411412/93395963-2abc4680-f877-11ea-9e72-ffbc946397e3.jpg)
![wmace](https://user-images.githubusercontent.com/71411412/93395969-2c860a00-f877-11ea-96f1-a60a6a3a3aa4.jpg)

**Server Revision**:

**Comment by eri1997** [comment]
You should delete your cache. That item only gives healing bonus in 2.0 itemization.

**Comment by Godmatik** [comment]
Healing items do not provide spellpower in the current patch.

Download and use this add-on to show the true values:

https://github.com/nullfoxh/NWTooltipFix
