### ISSUE TITLE
[Class] Hunter [Pet] Dead pet in stable/Corpse pet on login  [Pet Manager Branch] 

### ISSUE THREAD

**Issue by The14me** [Atlantiss/NetherwingBugtracker#7557]
**Current behaviour**: Summon your pet and send him to die. After the pet is dead relog. After u back in, u are able to put your dead pet in the stable. Once u bring it back again u aren't able to put it back.
If u log out with dead pet (corps around u) and log back in, there is no pet corps around u so u need to ''call pet'' to bring the corps back.
https://streamable.com/76g8v6

**Expected behaviour**: If your pet is dead u are not supposed to put him in a stable.
At login pet must be always summoned /dead or alive/

**Server Revision**: 
PTR

**Comment by Wolffenstein** [comment]
Wrong. You should be able to stable a dead pet and it shouldn't be summoned on login if it's dead.
