### ISSUE TITLE
[Quests][Core] Escort NPCs despawn instantly if the original acceptor leaves party

### ISSUE THREAD

**Issue by raethkcj** [Atlantiss/NetherwingBugtracker#7559]
**Current behaviour**:
If the person who starts an escort quest leaves party, the NPC despawns instantly, even if other players are on the quest.

**Expected behaviour**: 
NPC attempts to finish escort route until they are killed.

**Server Revision**: 
3531

**Comment by Wolffenstein** [comment]
Fixed in rev 3659.
