### ISSUE TITLE
[Quest][NPC][Item] Stone Tokens

### ISSUE THREAD

**Issue by Rickybobby90** [Atlantiss/NetherwingBugtracker#756]
[//]: # (Enclose links to things related to the bug using http://wowhead.com or any other TBC database.)
[//]: # (You can use screenshot ingame to visual the issue.)
[//]: # (Write your tickets according to the format:)
[//]: # ([Quest][Azuremyst Isle] Red Snapper - Very Tasty!)
[//]: # ([NPC] Magistrix Erona)
[//]: # ([Spell][Mage] Fireball)
[//]: # ([Npc][Drop] Ghostclaw Lynx)
[//]: # ([Web] Armory doesnt work)

**Description**: Stone Tokens quests in Alterac Mountins, drop rate is way to low.

**Current behaviour**: About 10% chance to drop item.

**Expected behaviour**: Significantly higher drop rate.

**Server Revision**: 2072

**Comment by Jezofine** [comment]
[Worn Stone Token (thottbot)](http://web.archive.org/web/20091204122555/http://thottbot.com:80/i3714)

**Comment by SwiftieTBC** [comment]
https://web.archive.org/web/20080320040918/http://wow.allakhazam.com/db/item.html?witem=3714

**Comment by Easyfraggy** [comment]
Linked for reference https://github.com/Atlantiss/NetherwingBugtracker/issues/755
