### ISSUE TITLE
[Dungeon][Movement/NPC] Steamvault Siren & Warrior patrol has bad way-points

### ISSUE THREAD

**Issue by Tenoutoften** [Atlantiss/NetherwingBugtracker#7561]
**Description/Current behaviour**: 
The 2 x [[NPC]Coilfang Siren#17801(N)/20623(H)](https://tbc-twinhead.twinstar.cz/?search=coilfang+siren) patrolling along with 1 x [[NPC]Coilfang Warrior#17802(N)/20626(H)](https://tbc-twinhead.twinstar.cz/?search=coilfang+warrior), just before [[NPC]Hydromancer Thespia#17797(N)/20629(H)](https://tbc-twinhead.twinstar.cz/?search=Hydromancer+Thespia), share similar issue of https://github.com/Atlantiss/NetherwingBugtracker/issues/7548, way-points should be improved as the 2 x [[NPC]Coilfang Siren#17801(N)/20623(H)](https://tbc-twinhead.twinstar.cz/?search=coilfang+siren) go up and down as they are on their patrol.

---

There is another more significant way-point issue in Mechanar that I have previously reported: https://github.com/Atlantiss/NetherwingBugtracker/issues/7537 

---

**Expected behaviour**: 
Normally patrolling without going up and down repeatedly.

**Server Revision**: 
3531

**Comment by Godmatik** [comment]
Rev 4016 - confirmed and still an issue, their waypoint movement is a bit janky and needs some small rework.

**Comment by Godmatik** [comment]
Fixed in movement rework branch
