### ISSUE TITLE
[Core][Spell] Conjure Refreshment Table spends charges even if players have maxed out the amount of Manna Biscuits

### ISSUE THREAD

**Issue by Tenoutoften** [Atlantiss/NetherwingBugtracker#7562]
**Description/Current behaviour**: 
A while ago my previous report on the [[Spell]Ritual of Refreshment#43987](https://tbc-twinhead.twinstar.cz/?spell=43987) spawning the [[Object]Refreshment Table#186812](https://tbc-twinhead.twinstar.cz/?object=186812) at the mage who casted it rather than at the [[Object]Refreshment Portal#186811](https://tbc-twinhead.twinstar.cz/?object=186811) got solved, even though nothing was noted in the changelog and the bug report remained open https://github.com/Atlantiss/NetherwingBugtracker/issues/2940 - I'll close this one in hopes that it wont break again, and leave this report open instead.

Now the [[Object]Refreshment Table#186812](https://tbc-twinhead.twinstar.cz/?object=186812) is once again spam-able so that one player can eat up plenty of charges beyond the first 4 - it despawns after 50 charges so this is rather frustrating in BGs or raids, or anytime anyone is trolling. Would be nice to have this fixed as this spell is used all the time.

**Expected behaviour**: 
Players clicking the [[Object]Refreshment Table#186812](https://tbc-twinhead.twinstar.cz/?object=186812) when they already got 80 x [[Item]Conjured Manna Biscuit#34062](https://tbc-twinhead.twinstar.cz/?item=34062) shouldn't continue to spend the [[Object]Refreshment Table#186812](https://tbc-twinhead.twinstar.cz/?object=186812)'s remaining charges

**Server Revision**: 
3531

**Comment by Tenoutoften** [comment]
This issue seems to be shared with warlocks healthstones: https://github.com/Atlantiss/NetherwingBugtracker/issues/7549

**Comment by Wolffenstein** [comment]
Fixed in rev 3533.
