### ISSUE TITLE
[Hunter] Hunter shoot abilities charges GCD but no shots fired

### ISSUE THREAD

**Issue by 4egito** [Atlantiss/NetherwingBugtracker#7563]
[//]: # (Enclose links to things related to the bug using http://wowhead.com or any other TBC database.)
[//]: # (You can use screenshot ingame to visual the issue.)
[//]: # (Write your tickets according to the format:)
[//]: # ([Quest][Azuremyst Isle] Red Snapper - Very Tasty!)
[//]: # ([NPC] Magistrix Erona)
[//]: # ([Spell][Mage] Fireball)
[//]: # ([Npc][Drop] Ghostclaw Lynx)
[//]: # ([Web] Armory doesnt work)
[//]: # (To find server revision type `.server info` command in the game chat.)

**Description**: 
As you can see in the video if you move in the moment of ammunition load and use some shoot ability the game charges your GCD but no shots fired (you can also hear the sound of load around 0:08 sec). This happens really often between melee and range when you kite mob/player and want to shoot it. I have played in "Netherwing" since season 2 and had no problems with this but seems after some changes about 3:2 macro usage things are fucked up.
You can turn the video speed to 0.25x to review the problem. Im pressing "V" which is bind for "Serpent sting" but it happens on all shots.
**Current behaviour**:
https://drive.google.com/file/d/1Jc3bKYRL8b6ohIKa2o2EynisEgsWmY-R/view?usp=sharing
**Expected behaviour**: 

**Server Revision**: 
3531

**Comment by Falathrin** [comment]
Sometimes not only casting an Aimed Shot triggers a GCD, but completing an Aimed Shot cast triggers another GCD as well.

I've experienced plenty of scenarios where I would press multi shot after Aimed Shot but had to wait because of Aimed Shot's completion GCD trigger which I don't think should happen.
Aimed Shot should only trigger a GCD if caster, not another one when completed.

**Comment by Wolffenstein** [comment]
Fixed in rev 3533.

**Comment by gunzbngbng** [comment]
@Wolffenstein This issue has not been fixed.  Hunter shots constantly use a GCD without activating.  And Aimed Shot constantly eats a GCD after use, even though it is a cast time longer than the GCD.
