### ISSUE TITLE
There is no priest trainer in Human starting zone

### ISSUE THREAD

**Issue by MonsterDooty** [Atlantiss/NetherwingBugtracker#7564]
[//]: # (Enclose links to things related to the bug using http://wowhead.com or any other TBC database.)
[//]: # (You can use screenshot ingame to visual the issue.)
[//]: # (Write your tickets according to the format:)
[//]: # ([Quest][Azuremyst Isle] Red Snapper - Very Tasty!)
[//]: # ([NPC] Magistrix Erona)
[//]: # ([Spell][Mage] Fireball)
[//]: # ([Npc][Drop] Ghostclaw Lynx)
[//]: # ([Web] Armory doesnt work)
[//]: # (To find server revision type `.server info` command in the game chat.)

**Description**: 
No priest trainer.

**Current behaviour**:
Doesn't exist.

**Expected behaviour**: 
Should exist.

**Server Revision**: 
how tf do you make a priest trainer go missing 
![priesttrainermissing](https://user-images.githubusercontent.com/47052511/93669276-26ec1800-fa61-11ea-8297-a010485ae660.png)

**Comment by raethkcj** [comment]
He's upstairs.

**Comment by Godmatik** [comment]
She should be on the lower floor.

https://www.youtube.com/watch?v=pp9Upxcg-2I
