### ISSUE TITLE
[Core] Flasks are disappearing on death in Raid.

### ISSUE THREAD

**Issue by tkauffman1** [Atlantiss/NetherwingBugtracker#7565]
[//]: # (Enclose links to things related to the bug using http://wowhead.com or any other TBC database.)
[//]: # (You can use screenshot ingame to visual the issue.)
[//]: # (Write your tickets according to the format:)
[//]: # ([Quest][Azuremyst Isle] Red Snapper - Very Tasty!)
[//]: # ([NPC] Magistrix Erona)
[//]: # ([Spell][Mage] Fireball)
[//]: # ([Npc][Drop] Ghostclaw Lynx)
[//]: # ([Web] Armory doesnt work)
[//]: # (To find server revision type `.server info` command in the game chat.)

**Description**: 
Every time I die I am losing my Flask of Fort Buff.
Both weekends and 4 flasks.

**Current behaviour**:

**Expected behaviour**: 
The flasks should persist through death.

**Server Revision**: 
3531

**Comment by Godmatik** [comment]
You sure you aren't overwriting your flask with elixirs or something? 
I've never once seen this happen.
