### ISSUE TITLE
Spell: Intervene

### ISSUE THREAD

**Issue by Vessler** [Atlantiss/NetherwingBugtracker#7567]
Intervene just doesn't work sometimes, its fine for the most part but ocassionaly it just doesnt redirect the next hit / spell like Sap/cheap shot etc.. to the warrior, target will still get sapped while having intervene buff active and warrior being in melee range, and no this isn't a spell baching problem or latency thing cuz Intervene has like 3+ seconds uptime already before the sap (this happened in my last arena game)

**Comment by Wolffenstein** [comment]
Not going to be fixed without reproduction/video.
