### ISSUE TITLE
[Spell][Paladin] Greater Blessing of Kings isnt relearned after respec

### ISSUE THREAD

**Issue by Cywiel** [Atlantiss/NetherwingBugtracker#7568]
**Description**: 
Problem with Greater BoK
**Current behaviour**:
Greater BoK isnt relearned if you respec even if you have learned it befor. 
**Expected behaviour**: 
Expected to behave like Greater BoSan, getting relearned once u spec into it again.
**Server Revision**: 
3531 (i think atleast)

**Comment by Tenoutoften** [comment]
This has been previously reported here: https://github.com/Atlantiss/NetherwingBugtracker/issues/7551
It also affects [[Spell]Prayer of Spirit](http://tbc.cavernoftime.com/?search=prayer+of+spirit): https://github.com/Atlantiss/NetherwingBugtracker/issues/7312

**Comment by raethkcj** [comment]
Also reported here #5646 😢

**Comment by Cywiel** [comment]
rip, didnt find them when i search for BoK, srry for repost i guess D:

**Comment by Wolffenstein** [comment]
Fixed in rev 3533.
