### ISSUE TITLE
[PVP] Hunter pet abilities not being (auto) casted / pet abilities are auto unlearned / pet spell book tab & action bar missing

### ISSUE THREAD

**Issue by Falathrin** [Atlantiss/NetherwingBugtracker#7569]
[//]: # (Enclose links to things related to the bug using http://wowhead.com or any other TBC database.)
[//]: # (You can use screenshot ingame to visual the issue.)
[//]: # (Write your tickets according to the format:)
[//]: # ([Quest][Azuremyst Isle] Red Snapper - Very Tasty!)
[//]: # ([NPC] Magistrix Erona)
[//]: # ([Spell][Mage] Fireball)
[//]: # ([Npc][Drop] Ghostclaw Lynx)
[//]: # ([Web] Armory doesnt work)
[//]: # (To find server revision type `.server info` command in the game chat.)

**Description**: 
As the title suggests, the spellbook pet tab is going missing frequently. I've had to go to the Pet Trainer, unlearn pet abilities and reteach my pet its abilities for this to get fixed.

**Current behaviour**:

I made similar threads earlier on Karazhan and even Netherwing:
https://github.com/Atlantiss/NetherwingBugtracker/issues/5129
https://github.com/Atlantiss/NetherwingBugtracker/issues/7371

Having your pet abilities not being casted mid BG or Arena is not ideal in PvP scenarios.
Sometimes I'd wonder why Dash isn't being casted. Then I'd open my spellbook only to notice my spellbook doesn't have a pet tab. I'd fix it by reteaching my pet all its abilities.

Then it bugs again frequently.

Also I remember from Netherwing arenas, if a pet dies and you revive it, its action bar would go missing. You'd need to dismiss it then resummon it to have it pop again which is frustrating in arenas. Not sure if this is fixed on Kara yet.

**Expected behaviour**: 

Pets should auto cast their abilities when commanded to attack the target only or if they're on defensive/aggressive stance obv. Pet spell books shouldn't disappear / pet spells shouldn't be unlearned on their own. Res'd arena pets should have their action bar pop up again upon resurrection.

**Server Revision**:

**Comment by Godmatik** [comment]
Guessing this was fixed at some point - having played hunter in past year I have never once experienced such issues.

Closing.
