### ISSUE TITLE
[Quest][Arathi Highlands] Worth Its Weight in Gold

### ISSUE THREAD

**Issue by Firroth** [Atlantiss/NetherwingBugtracker#757]
[Quest][Arathi Highlands] Worth Its Weight in Gold

**Current behaviour**:
You can get http://wowwiki.wikia.com/wiki/Quest:Worth_Its_Weight_in_Gold without turning in quest
http://wowwiki.wikia.com/wiki/Quest:Malin%27s_Request

**Expected behaviour**: 
You should be able to get this quest, after turning in quest 
http://wowwiki.wikia.com/wiki/Quest:Malin%27s_Request

**Server Revision**: 
2072

**Comment by Shanghi** [comment]
Malin's Request is an optional breadcrumb quest that's just meant to send you somewhere to get real quests. You can do Worth Its Weight In Gold without it, but if you do then you can't do Malin's Request after that. A lot of these quests were fixed here.

A few comments from wowhead and allakhazam:
> "Malin won't give me the quest"
> Reply: "you can go directly to the refuge post in the hinterlands, you can get on the questline directly there"
>
> "If you've done the followup in Arathi then this breadcrumb is no longer available to you."

**Comment by Firroth** [comment]
Are you 100% sure? since on wowhead there is also such post.
![screenshot_1](https://user-images.githubusercontent.com/43505196/46239004-affc7700-c392-11e8-94f4-7cfc10a8b617.png)

And I remember it always being where it was needed as pre-q to get this one.
Even just looking logically at this quest chain start with malin (he makes request for help) -> end with malin (he rewards you after completing all tasks personally), looks normal.
Start in arathi -> end with Malin doesn't since it doesn't feel connected to him at all.

Also are you sure you're recalling good expansion? since
https://www.wowhead.com/quest=691/worth-its-weight-in-gold is vanilla one, where it was needed from my knowledge.
And https://www.wowhead.com/quest=26035/worth-its-weight-in-gold is from Cata where it was not necessary anymore as even seen on quest chain list.

**Comment by Shanghi** [comment]
Never 100%, but:

* the World of Warcraft Master Guide book shows it having no requirement.
* it's just a basic talking quest like normal optional quests usually are and the beginning of the 2nd quest tells you the basics of what's happening.
* When going over all the requirements a few months ago, there were too many comments thinking something was required that were wrong, so a single comment like that is hard to trust when it goes against more official sources. For example:
![image](https://user-images.githubusercontent.com/2672633/46240990-bc2a0980-c37d-11e8-9b6b-3c1ff0f45082.png)
![image](https://user-images.githubusercontent.com/2672633/46240999-cf3cd980-c37d-11e8-8461-e44432ce6582.png)
* The comment above saying you can skip Malin was around patch 1.6 on [Allakhazam](https://web.archive.org/web/20080418073311/http://wow.allakhazam.com:80/db/quest.html?wquest=690). He says the hinterlands and refuge post, but the place is called Refuge Pointe so he's probably thinking of the same thing.
* The quest complete text for the 2nd quest mentions Malin sending you, which can be a sign the 1st quest is required so it makes sense, or just a sign of lazy writing!

ClassicDB is just a stock private server database so won't be able to help us. It also has [Magic Dust](https://classicdb.ch/?quest=8251) requiring Magecraft, but both the Master Guide and a wowhead comment ("FYI: Magic Dust can be completed prior to this quest") say there's no requirement.

I'll reopen it so others will see though! I could certainly be wrong so I'll let them decide.

**Comment by Tereneckla** [comment]
I guess people are fine with it as no one else voiced their opinion.
