### ISSUE TITLE
Faerie Fire (Feral) still overrides Improved Faerie Fire

### ISSUE THREAD

**Issue by Lapinkulta** [Atlantiss/NetherwingBugtracker#7570]
[//]: # (Enclose links to things related to the bug using http://wowhead.com or any other TBC database.)
[//]: # (You can use screenshot ingame to visual the issue.)
[//]: # (Write your tickets according to the format:)
[//]: # ([Quest][Azuremyst Isle] Red Snapper - Very Tasty!)
[//]: # ([NPC] Magistrix Erona)
[//]: # ([Spell][Mage] Fireball)
[//]: # ([Npc][Drop] Ghostclaw Lynx)
[//]: # ([Web] Armory doesnt work)
[//]: # (To find server revision type `.server info` command in the game chat.)

**Description**: 
From 2020-09-07 in changelog on disc: 
"[Core/Druid]:
- It will no longer be possible to use Faerie Fire (Feral) on a target with an enhanced Faerie Fire debuff (Improved Faerie Fire _talent)"

**Current behaviour**:
You can still override Improved Faerie Fire from a boomkin with the feral (and humanoid) version of Faerie Fire.

**Expected behaviour**: 
You shouldnt be able to override Improved Faerie Fire with a none improved version (or just feral one).

**Server Revision**:

**Comment by Godmatik** [comment]
Confirmed.

**Comment by Wolffenstein** [comment]
Should now be fixed.
