### ISSUE TITLE
[Spell] [Mage] Flamestrike

### ISSUE THREAD

**Issue by Shivashambo** [Atlantiss/NetherwingBugtracker#7571]
[//]: # ([Spell][Mage] Flamestrike)
Good evening, everyone . I wondered why the spell Flamestrike restores mana in the amount of 1 crit, even if it passed 5 out of 10.
I ask experienced players who caught wow bc on official to comment on this spell

**Comment by Godmatik** [comment]
Your post is a bit confusing, are you referring to "Master of Elements" talent that restores 30% of mana if a critical strike happens? That doesn't proc off multiple targets from AoE, you just get 30% back of the cost of the spell. Otherwise it would end up giving you more mana than you spent.

**Comment by Wolffenstein** [comment]
Works as intended.

**Comment by Shivashambo** [comment]
> Your post is a bit confusing, are you referring to "Master of Elements" talent that restores 30% of mana if a critical strike happens? That doesn't proc off multiple targets from AoE, you just get 30% back of the cost of the spell. Otherwise it would end up giving you more mana than you spent.
 . i write about  Flamestrike Fire AOE spell with Master of Elements .  always regen 1 crit ,may be it must work for all crit ,?
example:
i cast on 10 targets. 6/10 hit critical damage but mana I restored for 1 person

**Comment by Shivashambo** [comment]
> Works as intended.
i write about Flamestrike Fire AOE spell with Master of Elements . always regen 1 crit ,may be it must work for all crit ,?

example:
i cast on 10 targets. 6/10 hit critical damage but mana I restored for 1 person

**Comment by Godmatik** [comment]
as said above, it is working as intended. You don't get mana from each crit for an AoE spell.
