### ISSUE TITLE
Martyrdom procs while sitting doesn't work. Maybe Enrage for warrior either

### ISSUE THREAD

**Issue by HoofarES** [Atlantiss/NetherwingBugtracker#7572]
**Description**:  The Martyrdom talent in the discipline tree in priest allows the caster to avoid interrupts by 20% chance and prevents casting time to be lost for 5 seconds after being the victim of a melee or ranged critical strike. 

**Current behaviour**: If stood up, the talent seems to proc right, the buff shows and everything seems to work correctly. However, if critically hit while sitting (which grants an automatic critical hit for the attacker), the talent does not proc at all. This tactic is used notoriously while leveling warrior for enrage mechanics and, at least by myself, in priest to avoid using so much Power word: shield, thus being much more efficient when it comes to mana.

**Expected behaviour**:  It really should proc to any ranged or melee critical hit recieved, independently of any circumstance, whether I'm sitting, stood, swimming, flying or playing dice in a tabern.

**Server Revision**:

**Comment by Wolffenstein** [comment]
Crit talents were reworked to not proc from sitting crits in either 2.3 or 2.4. As far as I know, this works as intended at the moment.
