### ISSUE TITLE
Mark of Honor Hold

### ISSUE THREAD

**Issue by Godmatik** [Atlantiss/NetherwingBugtracker#7573]
If you kill yourself (falling off flying mount at great height is easiest) while within the vicinity of a Hellfire Peninsula PvP objective, you gain an honor hold mark. This should not be possible.

The only way you should be able to get a mark (besides the PvP daily):

> Delivering a killing blow a player of the opposing faction in the vicinity of Outdoor PVP objectives in either Hellfire Peninsula or Zangarmarsh awards one mark to each member of the killer's group or raid.

**Comment by Wolffenstein** [comment]
Fix pending
