### ISSUE TITLE
vanish -> stealthed status too slow [spell] [rogue] [stealth]

### ISSUE THREAD

**Issue by knasen88** [Atlantiss/NetherwingBugtracker#7574]
[//]: # (Enclose links to things related to the bug using http://wowhead.com or any other TBC database.)
[//]: # (You can use screenshot ingame to visual the issue.)
[//]: # (Write your tickets according to the format:)
[//]: # ([Quest][Azuremyst Isle] Red Snapper - Very Tasty!)
[//]: # ([NPC] Magistrix Erona)
[//]: # ([Spell][Mage] Fireball)
[//]: # ([Npc][Drop] Ghostclaw Lynx)
[//]: # ([Web] Armory doesnt work)
[//]: # (To find server revision type `.server info` command in the game chat.)

**Description**: 

![image](https://user-images.githubusercontent.com/16074363/93816659-1fdb2a80-fc58-11ea-82ae-040a259ac4b4.png)

**Current behaviour**:
casting any ability instantly out of vanish even if made with the conditional [stealth] will cast the non stealthed ability instead.
there is no GCD from vanish, and the combat log agrees that the character is stealthed, but something is not letting you use it.
**Expected behaviour**: 
shouldn't the check to see if character is stealthed or not be made clientside, then decide what ability it sends to the server? The one ability that doesn't match the conditional should not ever be sent
**Server Revision**: 
3531

**Comment by raethkcj** [comment]
Works fine for me with this macro:

`/cast [steath] Cheap Shot; Hemorrhage`

**Comment by knasen88** [comment]
have you tried when you press it really fast after vanish? I have similar macro.

**Comment by raethkcj** [comment]
Can you post your exact macro?

**Comment by knasen88** [comment]
```
 #showtooltip hemorrhage
/cast [stealth] Cheap Shot; [stance:2] Cheap Shot; [nostealth] Hemorrhage
```
added stance 2 some said it was for "vanish stance", but didn't change shit

**Comment by raethkcj** [comment]
The "not recovered" is because you cast Hemorrhage and it gives you a GCD; just trying to figure out why it cast Hemo

**Comment by raethkcj** [comment]
Are you sure you didn't have a different macro when you took the screenshot in the OP? Can't reproduce anything like that with the one you posted.

**Comment by raethkcj** [comment]
After testing more, there is a 50-100ms delay between SPELL_AURA_REFRESH and SPELL_AURA_APPLIED (timestamps are the first number in screenshot). Using the cs/hemo macro during this delay window will cause the macro's [stealth] conditional to fail.
![image](https://user-images.githubusercontent.com/7716908/94175346-2c2fd500-fe5c-11ea-8941-52069260ce60.png)
