### ISSUE TITLE
[Cosmetic] No collision on tombstones at human start

### ISSUE THREAD

**Issue by Diazonium** [Atlantiss/NetherwingBugtracker#7575]
[//]: # (Enclose links to things related to the bug using http://wowhead.com or any other TBC database.)
[//]: # (You can use screenshot ingame to visual the issue.)
[//]: # (Write your tickets according to the format:)
[//]: # ([Quest][Azuremyst Isle] Red Snapper - Very Tasty!)
[//]: # ([NPC] Magistrix Erona)
[//]: # ([Spell][Mage] Fireball)
[//]: # ([Npc][Drop] Ghostclaw Lynx)
[//]: # ([Web] Armory doesnt work)
[//]: # (To find server revision type `.server info` command in the game chat.)

**Description**: 
The tombstones near the warlock trainer at the human start lack collision.
**Current behaviour**:
![WoWScrnShot_092220_020433](https://user-images.githubusercontent.com/6989626/93833292-7c4e4200-fc78-11ea-934c-981c4511a55f.jpg)

**Expected behaviour**: 
The tombstones should have proper collision, not letting players walk through them.
**Server Revision**: 
3531

**Comment by Wolffenstein** [comment]
Clientside - not a bug.
