### ISSUE TITLE
Greater and normal blessings stack

### ISSUE THREAD

**Issue by JohnEU** [Atlantiss/NetherwingBugtracker#7576]
It seems that greater and normal blessing stack. Pretty sure they are not supposed to do that.

![WoWScrnShot_092220_131345](https://user-images.githubusercontent.com/55697857/93875836-0973b400-fcd6-11ea-8e2d-688303bd1b2c.jpg)
![WoWScrnShot_092220_131430](https://user-images.githubusercontent.com/55697857/93875840-0b3d7780-fcd6-11ea-93a9-0754a467c92b.jpg)

**Comment by Wolffenstein** [comment]
Can't reproduce.

**Comment by JohnEU** [comment]
Did you try with lower rank might and greater full rank?

**Comment by raethkcj** [comment]
If you tried to reproduce on PTR, it doesn't appear to have the buff group changes that live has yet. So repro on live or update PTR.
