### ISSUE TITLE
Cheat Death (Rogue Talent)

### ISSUE THREAD

**Issue by fearoftaco** [Atlantiss/NetherwingBugtracker#7577]
[//]: # (Enclose links to things related to the bug using http://wowhead.com or any other TBC database.)
[//]: # (You can use screenshot ingame to visual the issue.)
[//]: # (Write your tickets according to the format:)
[//]: # ([Quest][Azuremyst Isle] Red Snapper - Very Tasty!)
[//]: # ([NPC] Magistrix Erona)
[//]: # ([Spell][Mage] Fireball)
[//]: # ([Npc][Drop] Ghostclaw Lynx)
[//]: # ([Web] Armory doesnt work)
[//]: # (To find server revision type `.server info` command in the game chat.)

**Description**: Cheat Death is not working as it's supposed to.

**Current behaviour**: Cheat Death will save you from the killing blow but does not provide you with the 90% reduced damage buff for 3 seconds as the talent says. It will save you from the 1 killing blow but any other instance of damage received after that will do full dmg and kill you anyway. Please fix.

**Expected behaviour**: You have a 100% chance that an attack which would otherwise kill you will instead reduce you to 10% of your maximum health. In addition, all damage taken will be reduced by up to 90% for 3 seconds (modified by resilience). This effect cannot occur more than once per minute.

**Server Revision**: 3534

**Comment by raethkcj** [comment]
> In Patch 2.4.3, Cheat Death received a large change to it's mechanics. "Killing blows are no longer 100% absorbed. If the Rogue is below 10% health, the killing blow is still completely absorbed; if the Rogue is over 10% health, enough damage will be absorbed to reduce the Rogue’s health down to 10%. For the following 3 seconds, damage is not always reduced by 90%; it is now reduced by a maximum of 90%, depending on how much resilience the Rogue has. The damage reduction will be four times the damage reduction resilience causes against critical strikes."
> 
> The resilience required to reach 90% damage reduction is 22.5% critical strike damage reduction, or 444 resilience.

**Comment by raethkcj** [comment]
It does appear to be working on PTR:
![image](https://user-images.githubusercontent.com/7716908/93924618-99b3f800-fcda-11ea-9317-c36a0b5540a9.png)

**Comment by fearoftaco** [comment]
Thanks for sharing this. I wasn't aware of this change but you're right it does appear to be functioning as intended then. I guess my memory of the damage reduction was a lot more significant, but it might have been pre 2.4.3 change.

**Comment by fearoftaco** [comment]
After testing it appears to be working correctly on the live realm as well and the conclusion here is that I'm an idiot with a bad memory who needs more resil. Thanks for your help mate.
![Desktop Screenshot 2020 09 22 - 12 40 55 48 (2)](https://user-images.githubusercontent.com/71718587/93929975-80f31480-fcd1-11ea-9b42-060b74527917.png)
