### ISSUE TITLE
unique-equip gems treated as unique, disappearing from bags

### ISSUE THREAD

**Issue by babno** [Atlantiss/NetherwingBugtracker#7578]
I won a Vivid Chrysoprase from heroic SP, while already having one in my chest piece. I got it in my bag as normal. I tried to put it in my bank, but I got a message saying I couldn't have any more of that item, so in my bag it remained. I logged off and when I logged in about an hour later, the gem had disappeared from my bags. I got it in the mail from customer support as recovered lost item, but again can't grab it due to being unique.

**Comment by raethkcj** [comment]
In 2.0 they are unique, not just unique-equipped. Clear your cache.

**Comment by babno** [comment]
It shouldn't even allow me to roll on it let alone give it to me if that were the case, so still bugged either way.

**Comment by Healweed** [comment]
> I won a Vivid Chrysoprase from heroic SP, while already having one in my chest piece. I got it in my bag as normal. I tried to put it in my bank, but I got a message saying I couldn't have any more of that item, so in my bag it remained. I logged off and when I logged in about an hour later, the gem had disappeared from my bags. I got it in the mail from customer support as recovered lost item, but again can't grab it due to being unique.

You can't have more than 1 type of unique gem. This will count regardless if the gem is gemmed into one of your equipment pieces, stored into bank or in your backpacks.
You can only hold one of each anyway

**Comment by babno** [comment]
Well I held 2 of the vivid chrsoprase.

**Comment by Tereneckla** [comment]
Not unique anymore
