### ISSUE TITLE
Hardwood Cudgel or just maces in general

### ISSUE THREAD

**Issue by Mewmewww** [Atlantiss/NetherwingBugtracker#758]
[//]: # (Enclose links to things related to the bug using http://wowhead.com or any other TBC database.)
[//]: # (You can use screenshot ingame to visual the issue.)
[//]: # (Write your tickets according to the format:)
[//]: # ([Quest][Azuremyst Isle] Red Snapper - Very Tasty!)
[//]: # ([NPC] Magistrix Erona)
[//]: # ([Spell][Mage] Fireball)
[//]: # ([Npc][Drop] Ghostclaw Lynx)
[//]: # ([Web] Armory doesnt work)

**Description**: Awful skillup rate on my 1h mace (Hardwood Cudgel)

**Current behaviour**: Really low skillup rate on 1h mace (Hardwood Cudgel)

**Expected behaviour**: Leveling weapons is annoying, but it should have a higher chance of skilling up

**Server Revision**: 2072 NW

**Comment by asatorrr** [comment]
If you want to level weapon skills in the meantime, fight grey mobs, you should get a skill up every swing. If you find certain enemies aren't giving you skill ups, go for lower level.
