### ISSUE TITLE
Buggy Travel-boat/ships in Stonetalon Mountains.

### ISSUE THREAD

**Issue by XanMercury** [Atlantiss/NetherwingBugtracker#7580]
[//]: # (Enclose links to things related to the bug using http://wowhead.com or any other TBC database.)
[//]: # (You can use screenshot ingame to visual the issue.)
[//]: # (Write your tickets according to the format:)
[//]: # ([Quest][Azuremyst Isle] Red Snapper - Very Tasty!)
[//]: # ([NPC] Magistrix Erona)
[//]: # ([Spell][Mage] Fireball)
[//]: # ([Npc][Drop] Ghostclaw Lynx)
[//]: # ([Web] Armory doesnt work)
[//]: # (To find server revision type `.server info` command in the game chat.)

**Description**: 
At a specific location in the south of Stonetalon Mountains (66.6, 89,0), Boats will appear in the floor roughly every 3 minutes. Walking into the sails/mast as they spawn will take your character on a fantastic journey, depending on which of the boats you clip into.
https://cdn.discordapp.com/attachments/740410580657242114/758298850372091934/unknown.png
https://media.discordapp.net/attachments/740410580657242114/758290528340017192/unknown.png
https://media.discordapp.net/attachments/740410580657242114/758290702286585886/unknown.png

**Current behaviour**:
Magical teleporting boats are in the floor.

**Expected behaviour**: 
No magical teleporting boats in the floor.

**Server Revision**: 
3534

**Comment by Godmatik** [comment]
Looks like same bug from #617

**Comment by Godmatik** [comment]
Hasn't happened since then, must've been fixed, 

Closing.
