### ISSUE TITLE
Feral charge failing when rooted/stunned but still put on cooldown

### ISSUE THREAD

**Issue by babno** [Atlantiss/NetherwingBugtracker#7581]
if you feral charge at the same time as a stun or root you won't move at all but it will consume the cooldown.

**Comment by Healweed** [comment]
If you get a root/stun while in feral charge animation, then yes, it will be put in cooldown as intentionally.
If you're trying to use Feral charge while in a stun/root and the ability goes on cooldown, then it's a bug

Point is, you gotta clarify better on the wording and explain in detail imo

**Comment by babno** [comment]
I think it's a latency issue. I've never been rooted mid animation, it's only just as I try. I won't move, my target will not be rooted or interrupted, but I will have the cooldown triggered. I do remember it occuring in retail where I would charge as I was stunned, but it would basically just be treated as if I were stunned after the charge, with the travel/root/interrupt all taking place, but sitting stunned even though I'm 20yd from rogue.

**Comment by Godmatik** [comment]
Unable to reproduce.
