### ISSUE TITLE
[QUEST] The Dread Relic event not scripted

### ISSUE THREAD

**Issue by Godmatik** [Atlantiss/NetherwingBugtracker#7583]
After you open the chest and and loot the Dread relic, a bunch of "Dread Relic Thrall"s should spawn and slowly converge on you, but currently on Karazhan realm, when you open the chest, nothing happens.

https://www.wowhead.com/quest=10877/the-dread-relic
https://www.wowhead.com/npc=22369/dread-relic-thrall

See video:

https://www.youtube.com/watch?v=E1iN9XWIeoU

**Comment by EtheriousNW** [comment]
Fixed in 3846
