### ISSUE TITLE
[Warlock/PvP] Soul Link-Buff missing on pet

### ISSUE THREAD

**Issue by Tweet1337** [Atlantiss/NetherwingBugtracker#7587]
**Description:**
Warlock summons should get a visual Soul Link buff on them - it's currently missing. It should also provide 5% Damage for the pet.

**Current behaviour:**
Pet gets no Buff.
https://i.imgur.com/cvQPNjG.jpg

**Expected behaviour:**
When active, 20% of all damage taken by the caster is taken by your Imp, Voidwalker, Succubus, Felhunter, Felguard, or enslaved demon instead. That damage cannot be prevented. In addition, both the demon and master will inflict 5% more damage. Lasts as long as the demon is active and controlled.

Screenshot of a video from retail ("Noone 3 frost mage pvp"):
https://i.imgur.com/MnElLO4.png

**Soul Link in Database:**
https://tbc-twinhead.twinstar.cz/?spell=19028
https://tbc-twinhead.twinstar.cz/?spell=25228

**Server Revision:**
3534

**Comment by Wolffenstein** [comment]
Fixed in rev 3536.
