### ISSUE TITLE
ore veins sometimes have nothing in them

### ISSUE THREAD

**Issue by babno** [Atlantiss/NetherwingBugtracker#7588]
![image](https://user-images.githubusercontent.com/244626/94277721-f2240900-ff17-11ea-8550-57cb0c82bda4.png)

**Comment by Wolffenstein** [comment]
Not fixing "sometimes" bugs without reproduction steps.

**Comment by babno** [comment]
Just seems to happen 5-10% of the time. Look into rate tables at least for them. Mine 20 nodes and you'll see it happen I pretty much guarantee it.
