### ISSUE TITLE
What the hell is this? 

### ISSUE THREAD

**Issue by AlteredAli** [Atlantiss/NetherwingBugtracker#759]
[//]: # (Enclose links to things related to the bug using http://wowhead.com or any other TBC database.)
[//]: # (You can use screenshot ingame to visual the issue.)
[//]: # (Write your tickets according to the format:)
[//]: # ([Quest][Azuremyst Isle] Red Snapper - Very Tasty!)
[//]: # ([NPC] Magistrix Erona)
[//]: # ([Spell][Mage] Fireball)
[//]: # ([Npc][Drop] Ghostclaw Lynx)
[//]: # ([Web] Armory doesnt work)

**Description**: 
![wowscrnshot_092718_235450](https://user-images.githubusercontent.com/43499721/46150898-02656700-c2b1-11e8-8562-602d159a83d0.jpg)
????????????
**Current behaviour**:
looks like a png image of #000000 
**Expected behaviour**: 

**Server Revision**: 
2072

**Comment by xmesaj2** [comment]
either your pc only or some item might cause it but this report tells nothing specific
