### ISSUE TITLE
[NPC] Blasted lands servants

### ISSUE THREAD

**Issue by Yotag** [Atlantiss/NetherwingBugtracker#7590]
[//]: # (Enclose links to things related to the bug using http://wowhead.com or any other TBC database.)
[//]: # (You can use screenshot ingame to visual the issue.)
[//]: # (Write your tickets according to the format:)
[//]: # ([Quest][Azuremyst Isle] Red Snapper - Very Tasty!)
[//]: # ([NPC] Magistrix Erona)
[//]: # ([Spell][Mage] Fireball)
[//]: # ([Npc][Drop] Ghostclaw Lynx)
[//]: # ([Web] Armory doesnt work)
[//]: # (To find server revision type `.server info` command in the game chat.)

Infinite leash on the servants in blasted lands 
they followed me all the way to stonard without me activly attacking them, they should reset like normal mobs.

**Comment by Godmatik** [comment]
Fixed last year
