### ISSUE TITLE
[NPC] Blasted land cultist have too much SR

### ISSUE THREAD

**Issue by Yotag** [Atlantiss/NetherwingBugtracker#7591]
[//]: # (Enclose links to things related to the bug using http://wowhead.com or any other TBC database.)
[//]: # (You can use screenshot ingame to visual the issue.)
[//]: # (Write your tickets according to the format:)
[//]: # ([Quest][Azuremyst Isle] Red Snapper - Very Tasty!)
[//]: # ([NPC] Magistrix Erona)
[//]: # ([Spell][Mage] Fireball)
[//]: # ([Npc][Drop] Ghostclaw Lynx)
[//]: # ([Web] Armory doesnt work)
[//]: # (To find server revision type `.server info` command in the game chat.)

![image](https://user-images.githubusercontent.com/31243916/94336718-ce32f700-ffed-11ea-82af-c5b02ba0cac2.png)

SR on cultist is way too high

in order to resist so much of my dmg the mobs probably have more than 200 SR, I dont know how much they SHOULD have but I am guessing they aren't ment to be raid bosses. 
revision 3534

**Comment by Wolffenstein** [comment]
They have 106 Shadow Resistance, which comes from the Bestiary:

![image](https://user-images.githubusercontent.com/1576644/96891429-f268e300-1488-11eb-836d-e19eb2e49ab1.png)
