### ISSUE TITLE
[Quest]Membership Benefits

### ISSUE THREAD

**Issue by Healweed** [Atlantiss/NetherwingBugtracker#7593]
**Description**: 
"Membership Benefits" from Nagrand quest can only be done. The same quest should be a repetable quest time avaliable once per month(at the start of the month), doesn't become avaliable for all players. Netherwing aswell has this issue.

Proof of it:
https://www.wowhead.com/quest=9887/membership-benefits#comments

**Current behaviour**:
After doing the "Membership Benefits" 1st time, it wont become avaliable once per month at the start of the month itself.

**Expected behaviour**: 
Should be avaliable once per month with the chest rewards depending on what reputation you got with Consortium
**Server Revision**: 
3534 Server Revision || Karazhan Realm

**Comment by astarielko** [comment]
True it should be done once every month and the reward should scale with the reputation level.

**Comment by Ceago** [comment]
Bump

**Comment by Godmatik** [comment]
Duplicate
https://github.com/Atlantiss/NetherwingBugtracker/issues/6065
