### ISSUE TITLE
[Netherstorm][NPC][Movement] Nuramoc # 20932 missing patrol route

### ISSUE THREAD

**Issue by Tenoutoften** [Atlantiss/NetherwingBugtracker#7594]
**Description**: 
[[NPC]Nuramoc#20932](https://www.wowhead.com/npc=20932/nuramoc) missing patrol route on at least 1 spawning position.
![WoWScrnShot_092620_223859](https://user-images.githubusercontent.com/34839199/94532278-f0bb4f00-023d-11eb-8f4f-00a1a29ed4ce.jpg)

**Current behaviour**:
[[NPC]Nuramoc#20932](https://www.wowhead.com/npc=20932/nuramoc) is standing still just behind the Forge Base Oblivion. I don't know if all of his spawning points lack patrol. 

**Expected behaviour**: 
[[NPC]Nuramoc#20932](https://www.wowhead.com/npc=20932/nuramoc) is expected to have patrol routes on all of his spawning positions, the routes can be found with somewhat good accuracy just looking at the [wowhead map](https://www.wowhead.com/npc=20932/nuramoc#map)

**Server Revision**: 
3534

**Comment by Tenoutoften** [comment]
Netherstorm in general is by far the least worked zone when it comes to NPC placement and movements. Stock, misplaced and stillstanding NPC all over Manaforge B'naar.


https://github.com/Atlantiss/NetherwingBugtracker/issues/2606
https://github.com/Atlantiss/NetherwingBugtracker/issues/2633
https://github.com/Atlantiss/NetherwingBugtracker/issues/2662
https://github.com/Atlantiss/NetherwingBugtracker/issues/2699

It also has [[NPC]Nether Ray#18880](https://www.wowhead.com/npc=18880/nether-ray#comments) - [Video here](https://youtu.be/NVO4QnH2FuE?t=29) which spawns with full mana just like all the other similar mobs just like it across Outlands(Zangarmarsh, Shadowmoon Valley, 
 https://github.com/Atlantiss/NetherwingBugtracker/issues/2604

> Need add core feature like "HealthRegen" to mana.

> ```sql
> -- Creature Nether Ray 18880 SAI
> SET @ENTRY := 18880;
> UPDATE creature_template SET AIName="SmartAI" WHERE entry= @ENTRY;
> DELETE FROM smart_scripts WHERE entry=@ENTRY AND script_source_type=0 AND `id`=3;
> INSERT INTO smart_scripts (entry, script_source_type, id, link, event_type, event_phase_mask, event_chance, event_flags, event_param1, event_param2, event_param3, event_param4, event_param5, event_param6, event_param7, event_param8, event_cooldown_min, event_cooldown_max, action_type, action_param1, action_param2, action_param3, action_param4, action_param5, action_param6, action_param7, action_param8, source_type, source_param1, source_param2, source_param3, source_condition_id, target_type, target_param1, target_param2, target_param3, target_condition_id, target_x, target_y, target_z, target_o, comment) VALUES
> (@ENTRY, 0, 3, 0, 11, 0, 100, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 102, 0, 0, 0, 0, 0, 0, 0, 0, 1, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, "On respawn  - Self: Set mana 0 // ");
> ```

**Comment by Tenoutoften** [comment]
Found him stuck at a second position today, this time also behind Forge Base Oblivion
![Nuramoc pos2](https://user-images.githubusercontent.com/34839199/94532662-72ab7800-023e-11eb-8359-eb3ed3b218ad.jpg)

**Comment by Godmatik** [comment]
Nuramoc also spawned at 57, 56 in Netherstorm and is just sitting there, not moving or patrolling at all.

**Comment by Godmatik** [comment]
Another spawn point:
43,70

Standing still, not patrolling
