### ISSUE TITLE
[Spell][Core] Turning your character on a slope while casting with Water Walking buff interrupts your cast

### ISSUE THREAD

**Issue by raethkcj** [Atlantiss/NetherwingBugtracker#7598]
**Steps to reproduce**:
1. Find any sloped ground in the game, for example a ramp in Shattrath.
2. Cast Water Walking on yourself.
3. Begin casting any spell with a decent cast time, such as Healing Wave.
4. While casting, use the right mouse button to move your camera. Your character sort of snaps into different positions.
5. Your cast is interrupted when your character snaps positions.

**Video**:
https://www.youtube.com/watch?v=-jBJxV07CxI

If you follow the same steps without Water Walking, turning the camera does not interrupt your cast.

**Expected behaviour**: 
Water Walking does not affect your ability to turn while casting.

**Server Revision**: 
3534

**Comment by Godmatik** [comment]
Rev 4018 - still an issue

**Comment by Godmatik** [comment]
2.4.3 Clientside issue, so can not be fixed.

Same as this:
https://github.com/Atlantiss/NetherwingBugtracker/issues/8463
