### ISSUE TITLE
[Interface] Wrong Hitpoint Display

### ISSUE THREAD

**Issue by Azalen** [Atlantiss/NetherwingBugtracker#760]
**Description**: 
Sometimes the hitpoints shown in the interface are not reflecting the actual hitpoints or the interface gets bugged. Best to show this with two consecutive screenshots I took earlier today. Focus on the target frame.

https://i.imgur.com/4GcQw6d.jpg
https://i.imgur.com/4Qjm10F.jpg

**Server Revision**: 
[2067]

**Comment by The14me** [comment]
try without the addon's and confirm if the bug is still there. : )

**Comment by Azalen** [comment]
![wowscrnshot_101418_180725](https://user-images.githubusercontent.com/20336567/46919227-a1da6780-cfdc-11e8-9126-f2aa04c426a1.jpg)

Still persists.

**Comment by Azalen** [comment]
![wowscrnshot_102218_215811](https://user-images.githubusercontent.com/20336567/47315726-ae4a6a00-d645-11e8-8536-2246debb410f.jpg)
![wowscrnshot_102218_215820](https://user-images.githubusercontent.com/20336567/47315727-ae4a6a00-d645-11e8-888e-f022520d964c.jpg)

Here I got some proof without any AddOns.
@The14me

**Comment by Tereneckla** [comment]
Fixed
