### ISSUE TITLE
[Warlock] VW random disappear after dismounting a mount

### ISSUE THREAD

**Issue by iljakorolev** [Atlantiss/NetherwingBugtracker#7600]
**Description**: 
The VW disappears randomly after dismounting a ground mount. 

**Current behaviour**:
The VW disappears randomly. Sometimes straight away when dismounting the mount sometimes after long time spending on mount and dismounting. Haven't tried with other demons.

**Expected behaviour**: 
Demon shouldn't disappear.

**Server Revision**: 
3534

**Comment by Tenoutoften** [comment]
https://github.com/Atlantiss/NetherwingBugtracker/issues/7332
https://github.com/Atlantiss/NetherwingBugtracker/issues/4566
https://github.com/Atlantiss/NetherwingBugtracker/issues/4775

>If I unmount while I am in combat or initiate combat while I am mounted, the pet does not spawn

>Having a pet out - in my case a felguard. I mount up and sometimes when i dismount, my demon is gone. I have lost at least 5 felguards during the last 1-2 hours. It seems like it happens when if i mount up shortly after combat. Just mounting/dismounting in a city seems fine.

This has probably already been reported

**Comment by Godmatik** [comment]
Was an issue in Shadowmoon Valley, was fixed last year.

Closing.
