### ISSUE TITLE
[KARA] The Crone - Cyclones

### ISSUE THREAD

**Issue by Godmatik** [Atlantiss/NetherwingBugtracker#7602]
The cyclones by the Crone (in the opera event) should do damage before patch 2.1.

In addition, you should be taking fall damage if you get caught in one, but right now you just fall down slowly with no damage done.

> She spawns cyclones that will knock raid members straight up into the air, dealing a significant (but not fatal) amount of damage; HoT's can keep the cycloned victims alive. When you land, you will take fall damage as well.

> NOTE: Patch 2.1 removed damage done by cyclones. Expected falling damage is 1500-3000 depending on max health.

**Comment by Godmatik** [comment]
Best patch 2.0 video I could find =/

https://www.youtube.com/watch?v=mrSF8CVE3tY&t=7m30s

**Comment by knasen88** [comment]
except he doesn't take dmg from clone, only from fall damage? and rarely at that

**Comment by Godmatik** [comment]
2.0 is done, but you should still fall damage from the cyclones on this encounter even in patch 2.1 and beyond.
