### ISSUE TITLE
[Spell][Hunter] Volley should scale with Ranged Attack Power

### ISSUE THREAD

**Issue by raethkcj** [Atlantiss/NetherwingBugtracker#7603]
**Description**: 
> **2.2.0**: Volley: This spell is now affected by area damage caps. Its bonus damage coefficients have also been increased. It also correctly consumes charges of Misdirection.
> **3.0.8**: Volley: The damage has been reduced on all ranks by approximately 30% (including attack power scaling).
> **3.2.2**: Volley: The attack power coefficient has been increased from 0.0586 to 0.0837. Base points did not change.

Based on these patch notes, we know that Volley definitely scaled in patches 2.2 and 3.0.8.  
Patch 3.0.8 reduced the scaling by 30%; Patch 3.2.2 reversed the scaling nerf but not the base damage nerf.
.0586 is exactly 70% of .0837, suggesting that the coefficent before 3.0.8 was .0837 (or 8.37%). 

**Current behaviour**:
Volley only does base damage.

**Expected behaviour**: 
Volley does base damage + 8.37% of Ranged Attack Power every tick.

**Server Revision**: 
3536

**Comment by Fierywind** [comment]
Currently in classic, volley scales with 33% of *spellpower*. I can't find a reference to when it started scaling with ranged attack power, but it could have been 3.0+ as the 2.2 notes are unclear about what exactly it's scaling with.

**Comment by raethkcj** [comment]
Yes, Volley currently scales with SP.

However, all other abilities that scaled with SP in vanilla are currently scaling with RAP (Arcane Shot, Serpent Sting, Explosive Trap, etc.). Volley is the only odd one out.

**Comment by tsuone** [comment]
Closing for now. Tag me if you find more research.
