### ISSUE TITLE
[Spell] water elemental

### ISSUE THREAD

**Issue by exist8308** [Atlantiss/NetherwingBugtracker#7604]
**Description**: 
Aggressive is one of the three "postures" available to pets; the others are Defensive and Passive.

**Current behaviour**:
sometimes when pet is in agressive. he do nothing when i fight with mob

**Expected behaviour**: 

An aggressive pet will attack any mob that enters its aggro radius. In this mode, the pet will be constantly starting fights with mobs in its vicinity. This may be useful to a hunter or warlock who wants to grind a lot of monsters, or in certain PvP situations, but it can be very detrimental even while soloing, but especially in an instance, where drawing the attention of a swarm of monsters can quickly wipe out a party. In an instance, all pets are expected to be passive and remain so. The master of the pet is expected to command the pet to do exactly what he wants it to do, so that it doesn't pull unintended clusters.

**Server Revision**: 
3534

**Comment by Godmatik** [comment]
The aggro radius was much lower than it should be for aggressive pet stance - was fixed a couple of weeks ago.

Closing
