### ISSUE TITLE
[spell] ice barrier

### ISSUE THREAD

**Issue by exist8308** [Atlantiss/NetherwingBugtracker#7605]
**Description**: 

Instantly shields you, absorbing x damage. Lasts 1min.  **While the shield holds, spells will not be interrupted.**

**Current behaviour**:
While shield holds even damage or when shield holds after 1 min. always spell is interrupted, by increase casting time

**Expected behaviour**: 

While shielded, spells do not lose casting time due to push-back interruption. However, debuffs such as snares, counterspell, and silence still pass through.

https://wowwiki.fandom.com/wiki/Ice_Barrier

**Server Revision**: 

3534

**Comment by tsuone** [comment]
Worked okay for me.

**Comment by exist8308** [comment]
Its still work wrong ...

śr., 7 paź 2020, 06:17 użytkownik tsu <notifications@github.com> napisał:
