### ISSUE TITLE
[Spell - Visual] Amplify Magic

### ISSUE THREAD

**Issue by Godmatik** [Atlantiss/NetherwingBugtracker#7606]
Amplify Magic adds +120 Bonus Spell Damage (at max rank) onto the character sheet.

Tested and it appears to be a visual bug only.

**Comment by kenneth-wow** [comment]
Confirmed it was a visual bug.

Case 1: Nonamped mage arcane missiles nonamped shaman for 592.
Case 2: Amped mage arcane missiles nonamped shaman for 592.
Case 3: Nonamped mage arcane missiles amped shaman for 626.

**Comment by Wolffenstein** [comment]
Was fixed
