### ISSUE TITLE
BG daily not rewarding Weekly Honor Bonus

### ISSUE THREAD

**Issue by Lilchurlz** [Atlantiss/NetherwingBugtracker#7609]
**Description**:  Completed the daily play BG x 5 quest for now 8 days in a row, did not receive in additional honor on the 7th day.

**Current behaviour**: No additional honor for completing BG daily 7 times in a row

**Expected behaviour**: Recieve additional honor for completing the daily 7 times in a row

**Comment by tsuone** [comment]
There is nothing like additional honor for complething the daily 7 time in a row. You misread the news. Completing daily for a whole week (7 days) gives total of X amount of honor.
