### ISSUE TITLE
Wrathtail Sorceress

### ISSUE THREAD

**Issue by Mewmewww** [Atlantiss/NetherwingBugtracker#761]
[//]: # (Enclose links to things related to the bug using http://wowhead.com or any other TBC database.)
[//]: # (You can use screenshot ingame to visual the issue.)
[//]: # (Write your tickets according to the format:)
[//]: # ([Quest][Azuremyst Isle] Red Snapper - Very Tasty!)
[//]: # ([NPC] Magistrix Erona)
[//]: # ([Spell][Mage] Fireball)
[//]: # ([Npc][Drop] Ghostclaw Lynx)
[//]: # ([Web] Armory doesnt work)

**Description**: Casts frost nova and walks back, then goes melee range again

**Current behaviour**: ^

**Expected behaviour**: Should cast frost nova and go away from melee

**Server Revision**: 2072 NW

**Comment by Azalen** [comment]
Duplicate
-> https://github.com/Atlantiss/NetherwingBugtracker/issues/507
