### ISSUE TITLE
Don Carlos

### ISSUE THREAD

**Issue by astarielko** [Atlantiss/NetherwingBugtracker#7612]
[//]: # (Enclose links to things related to the bug using http://wowhead.com or any other TBC database.)
[//]: # (You can use screenshot ingame to visual the issue.)
[//]: # (Write your tickets according to the format:)
[//]: # ([Quest][Azuremyst Isle] Red Snapper - Very Tasty!)
[//]: # ([NPC] Magistrix Erona)
[//]: # ([Spell][Mage] Fireball)
[//]: # ([Npc][Drop] Ghostclaw Lynx)
[//]: # ([Web] Armory doesnt work)
[//]: # (To find server revision type `.server info` command in the game chat.)

**Description**: 
Don Carlos is missing. Hes an NPC that gives the quest for Escape From Durnholde Keep. He should be at the Gadgetzan graveyard.  Hes not standing where he should be. Only his horse is there.
**Current behaviour**:
Don Carlos is missing
**Expected behaviour**: 
Don Carlos should be spawned
**Server Revision**:

**Comment by raethkcj** [comment]
He'll be there in 2.4.3

https://wow.gamepedia.com/index.php?title=Don_Carlos&oldid=1415720

**Comment by astarielko** [comment]
Well the server is already on 2.4.3 isnt it?

**Comment by nonameform** [comment]
> Well the server is already on 2.4.3 isnt it?

The client is 2.4.3, content-wise we are pre-2.1.

**Comment by Godmatik** [comment]
only the spells and talents are 2.4.3, everything else is gated and we are only on 2.0 currently, otherwise we would have Sunwell raid and such already released. @astarielko

**Comment by tsuone** [comment]
Invalid. 2.4
