### ISSUE TITLE
Quick Flame Ward

### ISSUE THREAD

**Issue by Godmatik** [Atlantiss/NetherwingBugtracker#7613]
Quick Flame Ward Spell 4979

When used by the NPC - also dispells any shadow-based debuffs I had on the target (Shadow Word Pain and such), should only remove Fire debuffs and make the target immune to fire spells.

https://classic.wowhead.com/spell=4979/quick-flame-ward

**Comment by Wolffenstein** [comment]
Fixed in rev 3545.
