### ISSUE TITLE
Game crashes on login

### ISSUE THREAD

**Issue by Ambrusius** [Atlantiss/NetherwingBugtracker#7614]
My Character Re cannot log in, whenever i try my game crashes. i have cleared cache and addons and i still have this problem
![error](https://user-images.githubusercontent.com/17181725/95174488-700ace80-07ba-11eb-87ee-82ea2f4c28ed.PNG)

**Comment by nonameform** [comment]
I believe [that error still exists in retail version of WoW](https://eu.battle.net/support/en/article/8288). Not really associated with the server.

**Comment by Ambrusius** [comment]
I can log into all other chars though

**Comment by nonameform** [comment]
Try moving Cache, Interface and WTF folders at the same time. Perhaps there is an issue with certain setting in config.wtf.

**Comment by Godmatik** [comment]
If all else else fails, try to re-install a fresh client. 

If you can only not login to one character, then probably you have a corrupt game file for that specific location.

**Comment by Ambrusius** [comment]
i tried a fresh client, no luck

**Comment by nonameform** [comment]
Try contacting a GM from another char or on Discord and ask them to move your character to a major city to check if that helps.

**Comment by Ambrusius** [comment]
I was logged out on the elevator, seems RNG helped when i logged in while it was not moving or maybe a gm moved my char
