### ISSUE TITLE
[Spell][Warlock] Leech Effects Generating Threat

### ISSUE THREAD

**Issue by Fierywind** [Atlantiss/NetherwingBugtracker#7618]
[//]: # (Enclose links to things related to the bug using http://wowhead.com or any other TBC database.)
[//]: # (You can use screenshot ingame to visual the issue.)
[//]: # (Write your tickets according to the format:)
[//]: # ([Quest][Azuremyst Isle] Red Snapper - Very Tasty!)
[//]: # ([NPC] Magistrix Erona)
[//]: # ([Spell][Mage] Fireball)
[//]: # ([Npc][Drop] Ghostclaw Lynx)
[//]: # ([Web] Armory doesnt work)
[//]: # (To find server revision type `.server info` command in the game chat.)

**Description**: Drain Life and Siphon Life are leech effects, not healing effects, and thus should not generate healing threat

**Current behaviour**: Drain Life and Siphon Life generate healing threat for their healing portions

**Expected behaviour**: These spells are categorized as leech effects and have never generated threat (nor should they be affected by healing reduction effects, which they are on this server - separate but likely related issue). This is a wowwiki article pulled from its 2007 revisions: https://wowwiki.fandom.com/wiki/Drain?diff=1042482&oldid=732306 and here is it being addressed in classic: https://www.reddit.com/r/classicwow/comments/egscd0/warlocks_common_misconceptions_bugs_and_open/

**Server Revision**: 3536

**Comment by raethkcj** [comment]
Threat part sounds correct, but you said that they should not be affected by Mortal Strike effects, even though your link says that they were changed to be affected by reduction effects during TBC.

**Comment by Fierywind** [comment]
I probably missed that - but there's a reason this is a bug report about threat, and not mortal strike!

**Comment by Wolffenstein** [comment]
Fixed in rev 3545.
