### ISSUE TITLE
Quest, Hillsbrad Foothills, Helcular's Revenge

### ISSUE THREAD

**Issue by Erodraeda** [Atlantiss/NetherwingBugtracker#762]
[//]: # (Enclose links to things related to the bug using http://wowhead.com or any other TBC database.)
[//]: # (You can use screenshot ingame to visual the issue.)
[//]: # (Write your tickets according to the format:)
[//]: # ([Quest][Azuremyst Isle] Red Snapper - Very Tasty!)
[//]: # ([NPC] Magistrix Erona)
[//]: # ([Spell][Mage] Fireball)
[//]: # ([Npc][Drop] Ghostclaw Lynx)
[//]: # ([Web] Armory doesnt work)

**Description**: 
Drop chance is supposed to be low, but not as low to have to kill more than 100 mobs, as I did, and get no loot
**Current behaviour**:
Drop chance is way lower than it should be
**Expected behaviour**: 
Drop chance should be 5-10%
**Server Revision**:

**Comment by manslaughter** [comment]
Took me 77 yetis here.

**Comment by Dpthx** [comment]
https://www.wowhead.com/item=3708/helculars-rod#comments

The drop rates are not that far away from 0,5% / 1% at the moment and never were. This is working "as intended", this item takes AGES to drop.

advice on the drop rates for the rod: it's really unpredictable. with my shammy, i got it after 10 kills. with my priest, the other night i killed yeti for 2 hours didn't get it, logged out. this morning on the second kill i got the rod. both times i got it, i was the only one in the cave. just have time to give to this quest.

OMFG the droprate is insane, I'll never get this thing...

Also if you watch Joana's vid, he grinds the yetis for more than 1 hour (I belive it's actually 2 hours)

**Comment by aresbrutus** [comment]
Drop rates are correct.
