### ISSUE TITLE
[Trinket][Proc Mechanics] Living Root of the Wildheart proc

### ISSUE THREAD

**Issue by Onsty** [Atlantiss/NetherwingBugtracker#7621]
[//]: # (Enclose links to things related to the bug using http://wowhead.com or any other TBC database.)
[//]: # (You can use screenshot ingame to visual the issue.)
[//]: # (Write your tickets according to the format:)
[//]: # ([Quest][Azuremyst Isle] Red Snapper - Very Tasty!)
[//]: # ([NPC] Magistrix Erona)
[//]: # ([Spell][Mage] Fireball)
[//]: # ([Npc][Drop] Ghostclaw Lynx)
[//]: # ([Web] Armory doesnt work)
[//]: # (To find server revision type `.server info` command in the game chat.)

**Description**: Druids T5 trinket [[Living Root of the Wildheart]](https://wowwiki.fandom.com/wiki/Living_Root_of_the_Wildheart) does not proc on healing spells.

**Current behaviour**:
Have tried it for an hour and have 0 procs in tree form.  
Work well in other forms though.

[There is](https://github.com/Atlantiss/NetherwingBugtracker/issues/5690) a mention of this issue back in NW days

**Expected behaviour**: 

**Server Revision**:

**Comment by Wolffenstein** [comment]
Fixed in rev 3657.
