### ISSUE TITLE
Unarmed Skill doesn't apply to Fist Weapons until relog

### ISSUE THREAD

**Issue by raethkcj** [Atlantiss/NetherwingBugtracker#7624]
**Description**: 
The first time you equip any Fist Weapon, your Unarmed Skill does not apply to the attack table. You are able to gain points in Unarmed Skill, but you will always get miss/parry/dodge as if your weapon skill is 0. This is fixed after relogging, but is very confusing to players who get to Hellfire Peninsula and then equip a Fist Weapon for the first time.

Steps to reproduce:
1. Create a rogue
1. Level 70
1. Learn Fist Weapons but leave skill at 1
1. Equip any Fist Weapon
1. Hit a 60+ mob until your Unarmed Skill is at an appropriate level for that mob
1. Observe that you continue to only miss even with high weapon skill
1. Relog, and it's fixed

This doesn't happen with any other type of weapon.

**Current behaviour**:
Unarmed Skill doesn't apply to Fist Weapon attack table the first time a character equips a fist weapon

**Expected behaviour**: 
Unarmed Skill always applies to attacks made with Fist Weapons.

**Server Revision**: 
3536

**Comment by Godmatik** [comment]
Confirmed

**Comment by ProfessorLagg** [comment]
Confirmed. Relog fixed it.

**Comment by Godmatik** [comment]
Duplicate, closing this one
