### ISSUE TITLE
Karazhan - Attunmen the Huntsman

### ISSUE THREAD

**Issue by Godmatik** [Atlantiss/NetherwingBugtracker#7628]
Noticed some odd behavior of Attumen this past raid reset in Karazhan.

I understand his cleave is 360 degrees, however he was cleaving people that were 10-15 yards away from him, so healers were getting randomly sniped. 

It should only be melee range.

**Comment by raethkcj** [comment]
His cleave chains from the tank hitting 3 additional targets, and can chain 5 yards from each person it hits. So if there are people between the healer and tank, the healer can be hit up to 15 yards away from the tank.
