### ISSUE TITLE
[NPC][Ashenvale] Foulweald Totemic

### ISSUE THREAD

**Issue by EvanEricWells** [Atlantiss/NetherwingBugtracker#763]
[//]: # (Enclose links to things related to the bug using http://wowhead.com or any other TBC database.)
[//]: # (You can use screenshot ingame to visual the issue.)
[//]: # (Write your tickets according to the format:)
[//]: # ([Quest][Azuremyst Isle] Red Snapper - Very Tasty!)
[//]: # ([NPC] Magistrix Erona)
[//]: # ([Spell][Mage] Fireball)
[//]: # ([Npc][Drop] Ghostclaw Lynx)
[//]: # ([Web] Armory doesnt work)

**Description**: [NPC] Foulweald Totemic https://www.wowhead.com/npc=3750/foulweald-totemic#abilities

**Current behaviour**: Summoned Totem looks a Draenei totem

**Expected behaviour**: Should look like a Tauren totem https://www.wowhead.com/spell=39591/searing-totem#used-by-npc

**Server Revision**: 2072

**Comment by xmesaj2** [comment]
fixed in rev 2081
