### ISSUE TITLE
Warlock Pet Bug in Arena

### ISSUE THREAD

**Issue by budgebudge** [Atlantiss/NetherwingBugtracker#7631]
[//]: # (Enclose links to things related to the bug using http://wowhead.com or any other TBC database.)
[//]: # (You can use screenshot ingame to visual the issue.)
[//]: # (Write your tickets according to the format:)
[//]: # ([Quest][Azuremyst Isle] Red Snapper - Very Tasty!)
[//]: # ([NPC] Magistrix Erona)
[//]: # ([Spell][Mage] Fireball)
[//]: # ([Npc][Drop] Ghostclaw Lynx)
[//]: # ([Web] Armory doesnt work)
[//]: # (To find server revision type `.server info` command in the game chat.)

**Description**: 
when I target a totem and send my pet there in blades edge arena it gets stuck if the totem is on another floor level. meaning when me and my pet are upstairs and the totem is downstairs the pet gets stuck when I order it to kill the totem.

**Current behaviour**:
Pet gets stuck and doesn't move anymore. it stays on the spot.

**Expected behaviour**: 
Pet runs down/upstairs and kill the totem.

**Server Revision**:

**Comment by Godmatik** [comment]
Unable to reproduce - pet goes after the totem just fine on a different level.

Probably fixed at some point in the past.
