### ISSUE TITLE
[Core][Pet] Arena Warlock pet bug

### ISSUE THREAD

**Issue by budgebudge** [Atlantiss/NetherwingBugtracker#7632]
[//]: # (Enclose links to things related to the bug using http://wowhead.com or any other TBC database.)
[//]: # (You can use screenshot ingame to visual the issue.)
[//]: # (Write your tickets according to the format:)
[//]: # ([Quest][Azuremyst Isle] Red Snapper - Very Tasty!)
[//]: # ([NPC] Magistrix Erona)
[//]: # ([Spell][Mage] Fireball)
[//]: # ([Npc][Drop] Ghostclaw Lynx)
[//]: # ([Web] Armory doesnt work)
[//]: # (To find server revision type `.server info` command in the game chat.)

**Description**: 
in arena, when my pet gets distracted by a rogue. I cant make it follow anymore. it stays on the spot forever and gets stuck. only exception is if i find another target to send it directly to and then send it back to me. pressing stay/follow doesnt do anything. it just stays there.

**Current behaviour**:
pet gets stuck and cant be moved UNTIL i send it to attack another player.

**Expected behaviour**: 
when the pet gets distracted it should either auto move after me after a few seconds or i should be able to command it by "follow" or "stay"+"follow" or something

**Server Revision**: 3571

----

https://github.com/Atlantiss/NetherwingBugtracker/issues/7631

**Description**: 
when I target a totem and send my pet there in blades edge arena it gets stuck if the totem is on another floor level. meaning when me and my pet are upstairs and the totem is downstairs the pet gets stuck when I order it to kill the totem.

**Current behaviour**:
Pet gets stuck and doesn't move anymore. it stays on the spot.

**Expected behaviour**: 
Pet runs down/upstairs and kill the totem.

**Comment by Godmatik** [comment]
was fixed, can close
