### ISSUE TITLE
Target dummy - drops nothing

### ISSUE THREAD

**Issue by Makakumba** [Atlantiss/NetherwingBugtracker#7634]
Target dummy (https://www.wowhead.com/item=4366/target-dummy) schould be dropping materials when it dies. 
Instead, it just dissapears.
This makes farming fused wiring (https://www.wowhead.com/search?q=fused+wiring), which is used for a lot of engineering recipes, extremly hard to get.

**Comment by Godmatik** [comment]
Been a bug for years now... sadly

https://github.com/Atlantiss/NetherwingBugtracker/issues/2882

**Comment by tsuone** [comment]
Duplicated
#2882
