### ISSUE TITLE
[Alterac Valley] capturing mine loops player into disconnected state not being able to reconnect. 

### ISSUE THREAD

**Issue by cladyz** [Atlantiss/NetherwingBugtracker#7635]
[//]: # (Enclose links to things related to the bug using http://wowhead.com or any other TBC database.)
[//]: # (You can use screenshot ingame to visual the issue.)
[//]: # (Write your tickets according to the format:)
[//]: # ([Quest][Azuremyst Isle] Red Snapper - Very Tasty!)
[//]: # ([NPC] Magistrix Erona)
[//]: # ([Spell][Mage] Fireball)
[//]: # ([Npc][Drop] Ghostclaw Lynx)
[//]: # ([Web] Armory doesnt work)
[//]: # (To find server revision type `.server info` command in the game chat.)

**Description**: Upon capturing Horde mine player gets disconnected unable to reconnect back to the game until the game is over. 

**Current behaviour**: seconds before getting disconnected player received 107 million of healing. Could be the reason

**Expected behaviour**: Smooth capture of a mine without having player to disconnect. 

**Server Revision**:

**Comment by danbopes** [comment]
Dupe #7458
