### ISSUE TITLE
The Stones That Bind Us aggro

### ISSUE THREAD

**Issue by fabrusso** [Atlantiss/NetherwingBugtracker#7636]
**Description**: 
I'm on Karazhan.
During the quest The Stones That Bind Us in the Blasted Lands.
If you aggro a mob, the aggro will never be lose. Km away from the aggro point.
The mob can't die without a certain stone, so it can follow forever without dying.

**Current behaviour**:
The aggro last forever and kms away

**Expected behaviour**: 
The mob should lose aggro

**Server Revision**:

**Comment by Godmatik** [comment]
Fixed last year on Netherwing server
