### ISSUE TITLE
[Item][Trinket] - Shared cooldown again

### ISSUE THREAD

**Issue by knicklichtknicklicht** [Atlantiss/NetherwingBugtracker#7637]
[//]: # (Enclose links to things related to the bug using http://wowhead.com or any other TBC database.)
[//]: # (You can use screenshot ingame to visual the issue.)
[//]: # (Write your tickets according to the format:)
[//]: # ([Quest][Azuremyst Isle] Red Snapper - Very Tasty!)
[//]: # ([NPC] Magistrix Erona)
[//]: # ([Spell][Mage] Fireball)
[//]: # ([Npc][Drop] Ghostclaw Lynx)
[//]: # ([Web] Armory doesnt work)
[//]: # (To find server revision type `.server info` command in the game chat.)

**Description**: 
If two different trinkets have the same cooldowntime and provide the exact same buff, they still never share a a full cooldown.
Behaviour on patch 2.0.8 and before: 
Two different items providing the same buff with the same duration whilst beeing on the same cooldowntime could be used simultaniously for buffstacking. For example using "Bladefist's Breadth" (https://www.wowhead.com/item=28041/bladefists-breadth) and "Ancient Dranei War Talisman" (https://www.wowhead.com/item=31617/ancient-draenei-war-talisman) at the same time provided their buff "Ferocity" (https://www.wowhead.com/spell=33667/ferocity) twice. 
This however was patched in 2.0.10:
Having both trinkets equipped and using trinket A to gain the buff triggers a short and visible cooldown on trinket B for the duration of the buff caused by using trinket A whilst correctly applying the 90seconds cooldown to item A. Once the buff caused by using trinket A ended, it could be reapplied by using trinket B. So if both trinkets have a 1minute30sec cooldown and a 15sec duration per use, it was possible to chain both buffs for a full duration of 30seconds. 
This behaviour is well documented and noted on several later patches such as 2.3.2, 2.4.1 and 2.4.3 in the comment sections of each noted item. I am sure the list of items actually facing this issue is even longer but those are the first ones coming to my mind.
Also the same Issue appeared some time ago on another private server: https://github.com/SunwellWoW/Sunwell-TBC-Bugtracker/issues/2802 

**Current behaviour**:
Equipping both   https://www.wowhead.com/item=31617/ancient-draenei-war-talisman   and   https://www.wowhead.com/item=28041/bladefists-breadth   to get their buff   https://www.wowhead.com/spell=33667/ferocity   provides the buff once but triggers a full 90 second cooldown on both items whilst beeing visible on the used item but not one the other equipped item. This effectivly leaves one of both items useless except for the passive stats.
The same issue appears on   https://www.wowhead.com/item=31615/ancient-draenei-arcane-relic   and   https://www.wowhead.com/item=28040/vengeance-of-the-illidari   for their buff https://www.wowhead.com/spell=33662/arcane-energy, which was falsly stated to be correct in the Issue: "[Item][Trinket] - Shared cooldown #6275" few weeks ago.

**Expected behaviour**: 
Equipping two DIFFERENT trinkets with the same cooldowntime which provide the same buff should not trigger a full trinketcooldown on both items but instead trigger a full cooldown on the used item and and a short visible cooldown on the unused trinket in duration of the applied buff by the first item. Chaining the buffs of both items was possible on retail after patch 2.0.10 even on wotlk and later patches. 
It shall be noted that having the exact same item equipped twice (Lower City Prayerbook for example) should correctly trigger the full cooldown on both items (chaining same effect from same item = not possible, but chaining same effect caused by different sources = possible!)

**Server Revision**: 
3537

**Comment by Godmatik** [comment]
Rev 4018 - no longer an issue
Activating the first trinket properly puts the other trinket only on 15 second cooldown, not a full 90 second cooldown.
