### ISSUE TITLE
Global Potion 2 minute Cooldown Not Implemented

### ISSUE THREAD

**Issue by HeavyLiftin** [Atlantiss/NetherwingBugtracker#7638]
[//]: # (Enclose links to things related to the bug using http://wowhead.com or any other TBC database.)
[//]: # (You can use screenshot ingame to visual the issue.)
[//]: # (Write your tickets according to the format:)
[//]: # ([Quest][Azuremyst Isle] Red Snapper - Very Tasty!)
[//]: # ([NPC] Magistrix Erona)
[//]: # ([Spell][Mage] Fireball)
[//]: # ([Npc][Drop] Ghostclaw Lynx)
[//]: # ([Web] Armory doesnt work)
[//]: # (To find server revision type `.server info` command in the game chat.)

**Description**: 
10 minute invisibility potions are putting every kind of potion on a 10 minute cooldown. I'm pretty sure that each potion has an individual cooldown timer, and outside of that potions have a global, separate 2 minute cooldown that they go on for that specific type of potion. This probably goes un-reported because the vast majority of potions have a 2 minute or less cooldown to begin with.

**Current behaviour**: Potions are putting every other potion on **their specific cooldown timer,** rather than a universal/global 2 minute cooldown for all other short-term potion effects (i.e. Invisibility, Mighty Rage, Mana Potions, Health Potions, Stoneshield). 

**Expected behaviour**: Potions in TBC during every live patch were able to be used in succession after 2 minutes. I GM'd a raiding guild who would routinely skip one pack with an Invisibility Potion, clear the next pack, then the next pack after the 2 minute cooldown, by using a Lesser Invisibility Potion. We were also able to use Invisibility potions to skip a pack and dive right into a boss fight, without a 10-minute cooldown preventing the next 4 uses of a mana potion. You should be able to use any type of potion and have it put every other *potion* on a 2-minute cooldown. This is specific to **POTIONS** not elixirs or long-term buff items. Potions have both an individual cooldown timer and a global, 2 minute timer for potions of different types. Invisibility potions are expected to go on a 10 minute cooldown, and put every other type (including lesser invis, and vice versa) of potion on a 2 minute cooldown. 

**Server Revision**: Enable the 2-minute universal potion cooldown timer, rather than just putting every other potion on the last-used pot's cooldown.

**Comment by Godmatik** [comment]
Working as intended, not a bug, can close.

![2 4 3](https://github.com/Atlantiss/NetherwingBugtracker/assets/37913400/f8d4c7c7-e0aa-4bc9-99ec-20c03d2e51d8)
