### ISSUE TITLE
[Quest] [Eastern Plaguelands] Redemption

### ISSUE THREAD

**Issue by nonameform** [Atlantiss/NetherwingBugtracker#7640]
[//]: # (Enclose links to things related to the bug using http://wowhead.com or any other TBC database.)
[//]: # (You can use screenshot ingame to visual the issue.)
[//]: # (Write your tickets according to the format:)
[//]: # ([Quest][Azuremyst Isle] Red Snapper - Very Tasty!)
[//]: # ([NPC] Magistrix Erona)
[//]: # ([Spell][Mage] Fireball)
[//]: # ([Npc][Drop] Ghostclaw Lynx)
[//]: # ([Web] Armory doesnt work)
[//]: # (To find server revision type `.server info` command in the game chat.)

**Description**: NPC [Tirion Fordring](https://tbcdb.com/?npc=1855) in Eastern Plaguelands offers a quest [Redemption](https://tbcdb.com/?quest=5742). This quest involves clicking on gossip and reading the lore behind the character.

**Current behaviour**: Currently there are no gossip options and the quest cannot be completed. GM did reset the NPC for me, but that did not help.

![WoWScrnShot_101820_151550](https://user-images.githubusercontent.com/34381716/96375866-54bd9d00-1184-11eb-95d9-2dcc6cbfbc4c.jpg)
![WoWScrnShot_101820_151552](https://user-images.githubusercontent.com/34381716/96375894-7fa7f100-1184-11eb-968b-5b92d5a00066.jpg)

**Expected behaviour**: Tirion should offer gossip.

```
Sit and listen to my story, <race>.

>>I am ready to hear your tale, Tirion.

I must apologize for not being entirely truthful with you in regards to my identity.  I had to be certain that you could be trusted - few people would have selflessly lent assistance to an old and forgotten hermit.

You have proven yourself as one of those people: A person of integrity and honor.

>>Thank you, Tirion.  What of your identity?

My son, Taelan, was only a child when I was found guilty of treason and banished from the Alliance to live a life in exile.  I chose to remain here so that I could watch over him; to somehow insure that he would group up an honorable man.

As I had hoped, he took my place as lord of Mardenholde; but in a cruel twist of fate, joined the ranks of the Scarlet Crusade.  He is now their Highlord, <race>.

>>That is terrible.

Indeed.  The Scarlet Crusade are an aberration of the Order of the Silver Hand.

You must believe me, <race>; Taelan is a good man.  He needs guidance.  He needs to remember... remember what it is to be noble and honorable.  I know that in his heart, he knows what he does is wrong.  Will you help him?  Will you help him remember?

>>I will, Tirion.
```

**Server Revision**: Atlantiss Karazhan | Content patch: 2.0.3 | Revision: 3537

**Comment by Tereneckla** [comment]
As he says. SIT and listen to his tale.
