### ISSUE TITLE
Rise, Obsidion! does not become available after finishing the preceding quest.

### ISSUE THREAD

**Issue by J-Daniel-S** [Atlantiss/NetherwingBugtracker#7641]
[//]: # (Enclose links to things related to the bug using http://wowhead.com or any other TBC database.)
[//]: # (You can use screenshot ingame to visual the issue.)
[//]: # (Write your tickets according to the format:)
[//]: # ([Quest][Azuremyst Isle] Red Snapper - Very Tasty!)
[//]: # ([NPC] Magistrix Erona)
[//]: # ([Spell][Mage] Fireball)
[//]: # ([Npc][Drop] Ghostclaw Lynx)
[//]: # ([Web] Armory doesnt work)
[//]: # (To find server revision type `.server info` command in the game chat.)

**Description**: 

**Current behaviour**:

**Expected behaviour**: 

**Server Revision**:

**Comment by Godmatik** [comment]
Worked ok for me on my alt... although the exclamation point didn't show up because it was a "low level quest", perhaps that's what happened to you?

**Comment by J-Daniel-S** [comment]
Perhaps it was just me.  I thought I clicked on the npc but maybe I didn't.  I'll go check again next time I play and make sure.  I'll mark as resolved or delete this if I'm wrong.
