### ISSUE TITLE
Gnomish Poultryizer

### ISSUE THREAD

**Issue by Kayakangler** [Atlantiss/NetherwingBugtracker#7642]
[//]: # (Enclose links to things related to the bug using http://wowhead.com or any other TBC database.)
[//]: # (You can use screenshot ingame to visual the issue.)
[//]: # (Write your tickets according to the format:)
[//]: # ([Quest][Azuremyst Isle] Red Snapper - Very Tasty!)
[//]: # ([NPC] Magistrix Erona)
[//]: # ([Spell][Mage] Fireball)
[//]: # ([Npc][Drop] Ghostclaw Lynx)
[//]: # ([Web] Armory doesnt work)
[//]: # (To find server revision type `.server info` command in the game chat.)

**Description**: Gnomish Poultryizer Engineering 340 trinket, item 23835   It was expensive to make, please fix.

**Current behaviour**: Gnomish Poultryizer only changes the npc's/players appearance, they still attack with damage

**Expected behaviour**:  15 second version of a mage polymorph for npc and player.

**Server Revision**:

**Comment by Kayakangler** [comment]
I see this hasn't hit a priority list, probably because you are so Arena focused you miss the utility of this in ALL other PVP situations.   Or maybe you don't even know it existed or have never used it.  This trinket is literally why people level engineering pvp wise, yet it does not work.  Either offer refunds for what has become a very expensive worthless 45 stam tank trinket, or fix it please.

**Comment by Wolffenstein** [comment]
ID - 30501 Poultryized!
=================================================
Description: Transforms the enemy into a chicken that cannot cast, and does $s3% less damage for up to $d or until they are damaged.
ToolTip: Cannot cast spells and damage reduced by $s3%.


![image](https://user-images.githubusercontent.com/1576644/99040750-f7055080-2589-11eb-90d8-e133191416b1.png)
