### ISSUE TITLE
[Quest] Quests that award "Horde" reputation don't grant any reputation at all

### ISSUE THREAD

**Issue by Kryzarel** [Atlantiss/NetherwingBugtracker#7644]
[//]: # (Enclose links to things related to the bug using http://wowhead.com or any other TBC database.)
[//]: # (You can use screenshot ingame to visual the issue.)
[//]: # (Write your tickets according to the format:)
[//]: # ([Quest][Azuremyst Isle] Red Snapper - Very Tasty!)
[//]: # ([NPC] Magistrix Erona)
[//]: # ([Spell][Mage] Fireball)
[//]: # ([Npc][Drop] Ghostclaw Lynx)
[//]: # ([Web] Armory doesnt work)
[//]: # (To find server revision type `.server info` command in the game chat.)

**Description**: Any quest that awards "Horde" reputation doesn't award any reputation at all. It might be broken for Alliance as well, but can't confirm since I'm playing on Horde.

**Current behaviour**: After completing a quest that awards +X Horde reputation, notice that none of the Horde faction reputations actually increase. Even though in-game text says you gained +X Horde reputation.

An example quest is All Along the Watchtowers (https://tbc-twinhead.twinstar.cz/?quest=5098), in Western Plaguelands. There's plenty of others in WP besides this one.

**Expected behaviour**: It should award that amount of reputation to all Horde factions.

**Server Revision**: 3540

**Comment by Godmatik** [comment]
Was fixed - closing
