### ISSUE TITLE
[Hunter][Talent][Focused Fire][Spirit Bond] Focused Fire and Spirit Bond don't activate if you revive your pet

### ISSUE THREAD

**Issue by Kryzarel** [Atlantiss/NetherwingBugtracker#7645]
[//]: # (Enclose links to things related to the bug using http://wowhead.com or any other TBC database.)
[//]: # (You can use screenshot ingame to visual the issue.)
[//]: # (Write your tickets according to the format:)
[//]: # ([Quest][Azuremyst Isle] Red Snapper - Very Tasty!)
[//]: # ([NPC] Magistrix Erona)
[//]: # ([Spell][Mage] Fireball)
[//]: # ([Npc][Drop] Ghostclaw Lynx)
[//]: # ([Web] Armory doesnt work)
[//]: # (To find server revision type `.server info` command in the game chat.)

**Description**: Effects that state "while your pet is active", such as the Focused Fire and Spirit Bond talents, are lost when your pet dies and do NOT reactivate if you revive it. This can be confirmed by checking that you don't receive the Buff from Spirit Bond and the 2% damage multiplier from Focused Fire is not visible on the "Ranged" tab of the character sheet. If you dismiss and call pet or mount and dismount, these effects are activated again.

This is especially bad during long boss fights, you will lose 2% of your damage after your pet dies for the first time, with no way of getting it back until the end of the fight. Unless you waste 5 seconds to dismiss the pet and call it back.

**Current behaviour**: Focused Fire and Spirit Bond don't activate if you revive your pet. You need to dismiss or mount+dismount to reactivate them.

**Expected behaviour**: Reviving pet should restore those buffs. You should get the Spirit Bond buff back and see health gain ticks. Under the Ranged tab of your character sheet, the Damage number should turn green and you should see the text "x102%" in the tooltip.

**Server Revision**: 3560

**Comment by eri1997** [comment]
More info here:
https://github.com/Atlantiss/NetherwingBugtracker/issues/6890

**Comment by Wolffenstein** [comment]
Fixed in rev 3544.

**Comment by Kryzarel** [comment]
My bad, guess I took too long to report it and didn't even noticed the fix 👍
