### ISSUE TITLE
[Item] Bug ?

### ISSUE THREAD

**Issue by alpagut1** [Atlantiss/NetherwingBugtracker#7647]
[//]: # (Enclose links to things related to the bug using http://wowhead.com or any other TBC database.)
[//]: # (You can use screenshot ingame to visual the issue.)
[//]: # (Write your tickets according to the format:)
[//]: # ([Quest][Azuremyst Isle] Red Snapper - Very Tasty!)
[//]: # ([NPC] Magistrix Erona)
[//]: # ([Spell][Mage] Fireball)
[//]: # ([Npc][Drop] Ghostclaw Lynx)
[//]: # ([Web] Armory doesnt work)
[//]: # (To find server revision type `.server info` command in the game chat.)

**Description**:  Hello. i have a problem. When i was equip  [Melmorta's Twilight Longbow]  my damage 545-663  [https://hizliresim.com/iUQcMW](url)   and i have a new crossbow  [Steelhawk Crossbow] but i use crossbow my attack 526-652.   
 [https://hizliresim.com/ksrR2C](url)   absolutely crossbow better than other bow but how can it be ? is that bug ? (both skill level 350 )   [https://hizliresim.com/vUdtPD](url)      [https://hizliresim.com/taZgPm](url)

**Current `behaviour**`

**Expected behaviour**: 

**Server Revision**:

**Comment by Wolffenstein** [comment]
Delete cache.

**Comment by alpagut1** [comment]
> Delete cache.

not work .same problem
