### ISSUE TITLE
[npc][Stonetalon mountains] Pridewing Consort & Pridewing Wyvern

### ISSUE THREAD

**Issue by Sothanwow** [Atlantiss/NetherwingBugtracker#765]
**Description**: 
While doing the quest Pridewings of Stonetalon they would drop the quest item as they should but they wouldn't drop any one other loot they should have various trash loot that they drop but they had nothing.

[Pridewing Consort](http://db.hellfire-tbc.com/?npc=4014)
[Pridewing Wyvern ](http://db.hellfire-tbc.com/?npc=4012)

https://imgur.com/a/3UOi8Kd

**Edit adding onto this [Pridewing Skyhunters](http://db.hellfire-tbc.com/?npc=4013) have the same problem. 
**Current behaviour**:
Currently drops nothing but the quest item
**Expected behaviour**: 
Should drop various trash items.
**Server Revision**: 
2072

**Comment by aresbrutus** [comment]
They are supposed to be dropping very low amounts of trash items. They DO drop but very low chance.

Retail: https://youtu.be/FG8pkhreZjU?t=1100

**Comment by Sothanwow** [comment]
I understand a small droprate but I just did the entire quest and had nothing drop not a single trash item just the quest item. he was at least getting some items I did the entire quest and didn't get any and those are also the wrong wyverns that video has him killing Highperch Wyverns in thousand needles I am talking about the ones in stonetalon mountains 3 types of wyverns there.

**Comment by aresbrutus** [comment]
Alright, I will reopen so we can check it later.

**Comment by Tereneckla** [comment]
Fixed
