### ISSUE TITLE
[Spell][Mage] Water Elemental

### ISSUE THREAD

**Issue by parkis22** [Atlantiss/NetherwingBugtracker#7651]
2nd pet summoned has a bug where it does not listen to attack/follow/stay commands. Can still use special freeze ability, but not the pet frostbolt attack since it just stays by your side or often times runs in place. Only an issue with the 2nd pet summoned in arena, I'm not sure if this has anything to do with dismissing the 1st pet, and summoning a new pet right after.

**Comment by Godmatik** [comment]
Fixed last year
