### ISSUE TITLE
[Item][Event][2.0]Hallow End's welfare epics' stats

### ISSUE THREAD

**Issue by bekonja** [Atlantiss/NetherwingBugtracker#7652]
[//]: # (Enclose links to things related to the bug using http://wowhead.com or any other TBC database.)
[//]: # (You can use screenshot ingame to visual the issue.)
[//]: # (Write your tickets according to the format:)
[//]: # ([Quest][Azuremyst Isle] Red Snapper - Very Tasty!)
[//]: # ([NPC] Magistrix Erona)
[//]: # ([Spell][Mage] Fireball)
[//]: # ([Npc][Drop] Ghostclaw Lynx)
[//]: # ([Web] Armory doesnt work)
[//]: # (To find server revision type `.server info` command in the game chat.)

**Description**: 
https://wowwiki.fandom.com/wiki/Patch_2.1.0
https://wowwiki.fandom.com/wiki/Headless_Horseman
https://www.wowhead.com/npc=23682/headless-horseman#comments
Due to original TBC release schedule Hallows End event wasnt present during 2.0 patch. First time in TBC it was released somewhere at the end of 2.2 and 2nd time already in 2.4. Due to that there could be no information on 2.0 stats of items that Headless Horsemand drops during this event.

**Current behaviour**:
As it currently implemented on this server epics from this event surpass in stats some of the raid items, obviously they werent pruned to match 2.0 itemization.

**Expected behaviour**: 
https://www.wowhead.com/item=38175/the-horsemans-blade#comments
In comments section you can see someone mentioning blade's stats being similar to Spiteblade from Karazhan. That comparisson could be an expample of how much you need to nerf epics from this event.
Need futher research on rings and helm.

**Server Revision**: 
2306

**Comment by tsuone** [comment]
Stats converted to 2.0, based on information it is equal to Spiteblade from Karazhan.
```
Main-Hand                                 Sword
153 - 285 Damage              Speed 2.70
(81.1 damage per second)
+ 12 Agility
+ 13 Stamina
Durability 105 / 105
Requires Level 70
Equip: Increases attack power by 42.
Use: Summon Pumpkin Soldiers to burn your foes. (10 Mins Cooldown)

"Soldiers arise, stand and fight!"
```

**Comment by Wolffenstein** [comment]
Fixed in rev 3546.

**Comment by tsuone** [comment]
Hallow's End rings stats converted to 2.0 values:

**Witches Band** (Equivelant of Band of Halos):
```
+ 19 Stamina (-3)
+ 19 Intellect (-2)
Equip: Increases healing done by you up to 44 (-2) and damage done by up to 15 (-1) for all magical spells and effects.
Equip: Restores 6 mana per 5 sec.
```

**The Horseman's Signet Ring** (Equivelant of Cobalt Band of Tyrigosa):
```
+16 Stamina (-3)
+15 Intellect (-2)
Equip: Increases damage and healing done by magical spells and effects by up to 33. (-2)
```

**Ring of Ghoulish Delight** (Equivelant of Eye of the Stalker `Added in 2.1`):
```
+24 Stamina (-7)
Equip: Increases attack power by 46. (-14)
```

**Comment by bekonja** [comment]
https://www.wowhead.com/item=33808/the-horsemans-helm#comments
helm has no direct equivalent so comparing its closest counterpart Fel-Steel Warhelm 2.0->2.1 stats change it might look like this:
```
1018 Armor
+36 Strength
+37 Stamina
Red Socket
Meta Socket
Blue Socket
Socket Bonus: +4 Strength
Equip: Increases your critical strike rating by 24.
Use: Let the Horseman laugh through you.
```
