### ISSUE TITLE
People dying in OHF HC are teleported to the Gadgetzan graveyard

### ISSUE THREAD

**Issue by yoyosan** [Atlantiss/NetherwingBugtracker#7653]
[//]: # (Enclose links to things related to the bug using http://wowhead.com or any other TBC database.)
[//]: # (You can use screenshot ingame to visual the issue.)
[//]: # (Write your tickets according to the format:)
[//]: # ([Quest][Azuremyst Isle] Red Snapper - Very Tasty!)
[//]: # ([NPC] Magistrix Erona)
[//]: # ([Spell][Mage] Fireball)
[//]: # ([Npc][Drop] Ghostclaw Lynx)
[//]: # ([Web] Armory doesnt work)
[//]: # (To find server revision type `.server info` command in the game chat.)

**Description**: 

My group just died in OHF heroic and got teleported all the way back to the Gadgetzan graveyard.

**Current behaviour**:

We were teleported all the way to the Gadgetzan graveyard, which is a long way to run back.

**Expected behaviour**: 

We should be revived near the instances spirit.

**Server Revision**: 

3546

**Comment by Wolffenstein** [comment]
Fixed in rev 3547.
