### ISSUE TITLE
[spell=8955][druid] Soothe Animal(rank 2)

### ISSUE THREAD

**Issue by Smokdacave** [Atlantiss/NetherwingBugtracker#7654]
[//]: # (Enclose links to things related to the bug using http://wowhead.com or any other TBC database.)
[//]: # (You can use screenshot ingame to visual the issue.)
[//]: # (Write your tickets according to the format:)
[//]: # ([Quest][Azuremyst Isle] Red Snapper - Very Tasty!)
[//]: # ([NPC] Magistrix Erona)
[//]: # ([Spell][Mage] Fireball)
[//]: # ([Npc][Drop] Ghostclaw Lynx)
[//]: # ([Web] Armory doesnt work)
[//]: # (To find server revision type `.server info` command in the game chat.)

**Description**: 
 works wrong [https://imgur.com/a/p0TNDHV](url) on the screen you can see beast lvl 59 affected by rank 2 soothe animal
**Current behaviour**:
affects targets whos levels are higher than in description
**Expected behaviour**: 
affect targets level 55 or lower
**Server Revision**:

**Comment by raethkcj** [comment]
I belive Soothe Animal and Mind Soothe scale with level. Rank 2 is learned at 36 and works up to 55 at that level; it gains one additional level up to level 51, and then you learn the next rank at 52. So if you are level 51+, rank 2 should work on targets up to level 69.

**Comment by Wolffenstein** [comment]
Working correctly.
