### ISSUE TITLE
[QUEST][NPC] Haalum banishment totems spawning incorrect amount of mobs

### ISSUE THREAD

**Issue by mn142** [Atlantiss/NetherwingBugtracker#7656]
[//]: # (Enclose links to things related to the bug using http://wowhead.com or any other TBC database.)
[//]: # (You can use screenshot ingame to visual the issue.)
[//]: # (Write your tickets according to the format:)
[//]: # ([Quest][Azuremyst Isle] Red Snapper - Very Tasty!)
[//]: # ([NPC] Magistrix Erona)
[//]: # ([Spell][Mage] Fireball)
[//]: # ([Npc][Drop] Ghostclaw Lynx)
[//]: # ([Web] Armory doesnt work)
[//]: # (To find server revision type `.server info` command in the game chat.)

**Description**: 
For the quest The Ashtongue Corruptors in SMV, the totems to release the air NPC Haalum spawn elementals in pairs of 3 instead of 1 when each totem is destroyed. Location: 57.1, 73.6
Furthermore, the totems can be feared - making the totems themselves run away. 
I also suspect the air elementals hit abit too hard (600-700 lightning bolt), but have not been able to find any source for this.

**Current behaviour**:
Upon destroying each air totem it spawns 3 air elementals. Every time.
The totems can be feared. I suspect this is also an issues for the other similar totems for the Corrupter NPCs in SMV.

**Expected behaviour**: 
Should only spawn 1 when each totem is destroyed. 
The totems should not be affected by fear.
https://www.wowhead.com/quest=10574/the-ashtongue-corruptors#comments;comments:id=63470

**Server Revision**: 
3546

**Comment by Wolffenstein** [comment]
Fixed in rev 3556.
