### ISSUE TITLE
[Karazhan] Trash respawns after one wipe to Attumen the Huntsman

### ISSUE THREAD

**Issue by yoyosan** [Atlantiss/NetherwingBugtracker#7657]
[//]: # (Enclose links to things related to the bug using http://wowhead.com or any other TBC database.)
[//]: # (You can use screenshot ingame to visual the issue.)
[//]: # (Write your tickets according to the format:)
[//]: # ([Quest][Azuremyst Isle] Red Snapper - Very Tasty!)
[//]: # ([NPC] Magistrix Erona)
[//]: # ([Spell][Mage] Fireball)
[//]: # ([Npc][Drop] Ghostclaw Lynx)
[//]: # ([Web] Armory doesnt work)
[//]: # (To find server revision type `.server info` command in the game chat.)

**Description**: 

The trash preceding `Attumen the Huntsman` started respawning after we wiped to the boss one time.
We did the raid on the 22th of October, around 7PM - 8PM server time.

Hopefully I've recorded the raid and have proof.  Check [here](https://youtu.be/JtQ_U0uyU08?t=868) when we're pulling after we wiped:
* Three horses that we killed before came and we had to wipe.
* Then the rest of the trash started to respawn so we had to clear the trash all over again.

Raid ID `10867`

**Current behaviour**:

For our run, the trash started respawning after one wipe to the boss.

**Expected behaviour**: 

From what I remember from 12 years ago, it should take some time for the trash to respawn.

**Server Revision**: 

Not sure but it was on the 22th of October, during the evening.

**Comment by Wolffenstein** [comment]
Attumen trash has a 30 minute respawn in 2.0.
