### ISSUE TITLE
[npc][Ashenvale]Foulweald Totemic Dropping wrong totem

### ISSUE THREAD

**Issue by Sothanwow** [Atlantiss/NetherwingBugtracker#766]
**Description**: 
This mob has a similar problem to another mob I reported some of them drop the drenai totem and some drop the correct looking totem.
https://imgur.com/a/BrrK5Aq
https://www.wowhead.com/npc=3750/foulweald-totemic

**Edit Adding another npc this time with a different drenai totem
https://imgur.com/a/M2zs2fB

**Current behaviour**:
Foulweald totemic drops a drenai fire loooking totem
**Expected behaviour**: 
Should drop the regular totem with horns.
**Server Revision**: 
2072

**Comment by The14me** [comment]
duplicate https://github.com/Atlantiss/NetherwingBugtracker/issues/763
