### ISSUE TITLE
Durnholde Lookout and Durnholde Reinforcement, wrong level in normal

### ISSUE THREAD

**Issue by Godmatik** [Atlantiss/NetherwingBugtracker#7661]
These mobs are level 71 when spawned in normal mode, they should be level 66/67 like all the other mobs.

https://www.wowhead.com/npc=22128/durnholde-lookout
https://www.wowhead.com/npc=22398/durnholde-reinforcement

**Comment by Wolffenstein** [comment]
Fixed in rev 3556.
