### ISSUE TITLE
[Spell] Healing Wave Incorrect Downrank Penalty

### ISSUE THREAD

**Issue by kenneth-wow** [Atlantiss/NetherwingBugtracker#7664]
Overview of expected vs actual healing: (includes common but wrong formulas to attempt to derive what atlantiss is using)
https://docs.google.com/spreadsheets/d/1d0iWU25_3zretpmsUZEXdVHqwRLUzdbkt6BVa_0oQ98/edit?usp=sharing

Values for Healing Wave 5:
* min = basemin + (healing * coefficient * downrankPenalty)
* max = basemax + (healing * coefficient * downrankPenalty)
* basemin = 376
* basemax = 441
* healing = 1456
* spell coefficient = .857 [Source](https://web.archive.org/web/20080915225056/http://elitistjerks.com/f47/t19038-spell_coefficients/)
* downrank penalty = 0.5 [Source](https://web.archive.org/web/20080920071548/http://elitistjerks.com/691947-post839.html)

Expected vs. Actual Healing
Expected min **1000**, Observed min **923**
Expected max **1065**, Observed max **987**

Testing:
* Improved Healing Wave was used - Should not effect spell coefficient
* Purification **not** used

Links to combatlog and sorted heal numbers with crits removed:
[WoWCombatLog.txt](https://github.com/Atlantiss/NetherwingBugtracker/files/5434911/WoWCombatLog.txt)
[sorted.txt](https://github.com/Atlantiss/NetherwingBugtracker/files/5434912/sorted.txt)

**Comment by kenneth-wow** [comment]
![image](https://user-images.githubusercontent.com/16741112/97509414-97d3f900-1958-11eb-81ca-c61f47965612.png)
More testing shows HW12 matches predictions exactly, but HW8 predictions are off. Sample size over 1k casts.

**Comment by Wolffenstein** [comment]
Fixed in rev 3550.
