### ISSUE TITLE
[Kael'thas Sunstrider] Shock Barrier + Pyroblast combo

### ISSUE THREAD

**Issue by Anduyon** [Atlantiss/NetherwingBugtracker#7666]
**Description**: 
Kael'thas will sometimes not cast Pyroblast when he puts up his Shock Barrier
**Current behaviour**:
If Kael'thas is locked out of his fire school by an interrupt on his Fireball before he casts Shock Barrier, he will not cast Pyroblast. Instead he will just melee his current target which makes the entire mechanic pointless.
https://www.twitch.tv/videos/781675025?t=02h20m40s
**Expected behaviour**: 
After a Shock Barrier is applied, Kael'thas should be chain casting Pyroblasts until the Shock Barrier is broken. 
https://www.twitch.tv/videos/781675025?t=02h19m25s
**Server Revision**: 
3547

**Comment by Easyfraggy** [comment]
Can confirm this issue

**Comment by Wolffenstein** [comment]
Fixed in rev 3556.
