### ISSUE TITLE
Druid Swimform Quest Bugged

### ISSUE THREAD

**Issue by HokagoTT** [Atlantiss/NetherwingBugtracker#7668]
Quest: Trial of the Sea Lion

Item: Chest

2nd Item: Pendant of the Sea Lion

Issue:  Chest is not lootable

**Comment by Godmatik** [comment]
worked fine for me.. close game and delete cache folder?

**Comment by HokagoTT** [comment]
> worked fine for me.. close game and delete cache folder?

did that, still not lootable. the Strange Lootbox is not even giving me the "loot" Icon. if got 1 part from Westfall, but the one in Silverpine is not working.

**Comment by raethkcj** [comment]
The Silverpine box is for Horde. If you got your first part from Westfall, then your second part is in Darkshore:

https://classic.wowhead.com/object=177792

**Comment by HokagoTT** [comment]
> The Silverpine box is for Horde. If you got your first part from Westfall, then your second part is in Darkshore:
> 
> https://classic.wowhead.com/object=177792

i know i play horde. 
so from my understanding i need the 2 parts from silverpine and westfall

**Comment by Godmatik** [comment]
if you are Horde, then you go silverpine and barrens
