### ISSUE TITLE
Venture Co Overseer Poison

### ISSUE THREAD

**Issue by miraage** [Atlantiss/NetherwingBugtracker#7670]
[//]: # (Enclose links to things related to the bug using http://wowhead.com or any other TBC database.)
[//]: # (You can use screenshot ingame to visual the issue.)
[//]: # (Write your tickets according to the format:)
[//]: # ([Quest][Azuremyst Isle] Red Snapper - Very Tasty!)
[//]: # ([NPC] Magistrix Erona)
[//]: # ([Spell][Mage] Fireball)
[//]: # ([Npc][Drop] Ghostclaw Lynx)
[//]: # ([Web] Armory doesnt work)
[//]: # (To find server revision type `.server info` command in the game chat.)

**Description**: 
https://www.wowhead.com/npc=3286/venture-co-overseer
You need to kill'em for https://www.wowhead.com/quest=896/miners-fortune
Poison lasts too long

**Current behaviour**:
Poison lasts for 50 seconds

**Expected behaviour**: 
Poison lasts for 10 seconds
https://www.wowhead.com/spell=6531/overseers-poison

**Server Revision**: 
N/A

**Comment by Wolffenstein** [comment]
It's 60s in TBC.
