### ISSUE TITLE
Warlock Pet can't use abilitys

### ISSUE THREAD

**Issue by Svedinos** [Atlantiss/NetherwingBugtracker#7672]
[//]: # (Enclose links to things related to the bug using http://wowhead.com or any other TBC database.)
[//]: # (You can use screenshot ingame to visual the issue.)
[//]: # (Write your tickets according to the format:)
[//]: # ([Quest][Azuremyst Isle] Red Snapper - Very Tasty!)
[//]: # ([NPC] Magistrix Erona)
[//]: # ([Spell][Mage] Fireball)
[//]: # ([Npc][Drop] Ghostclaw Lynx)
[//]: # ([Web] Armory doesnt work)
[//]: # (To find server revision type `.server info` command in the game chat.)

**Description**: 
After i got the books for lvl 62, all of my pets can't use any abilitys except for the imp and Blood pact
**Current behaviour**:
all of my pets can't use any abilitys except for the imp and Blood pact
**Expected behaviour**: 
Use abilitys like taunt and so on
**Server Revision**:

**Comment by Godmatik** [comment]
Unable to reproduce, no other warlocks have mentioned these issues.

Client or addon issue most likely.
