### ISSUE TITLE
Cleaves!!! Please fix

### ISSUE THREAD

**Issue by Patriot-gera** [Atlantiss/NetherwingBugtracker#7674]
Hello. Please, fix mob's cleaves! it doesn't work in the right way. They hit you if you stand behind them! It's a 360* now, not 180*. It happens in dungeons 70 lvl. like SL, OHF, etc.

**Comment by Godmatik** [comment]
It's working properly, cleaves were 360 degrees in patch 2.0.

**Comment by Patriot-gera** [comment]
Cleave is an ability that hit INFRONT of you, NOT behind

**Comment by Godmatik** [comment]
In Patch 2.0, the cleave was 360, blizz changed it to 180 starting 2.1

The game is running using 2.0 rules currently.

Only Blizz knows why this was done, but that's the way it is.
