### ISSUE TITLE
Worn Stone Token

### ISSUE THREAD

**Issue by miraage** [Atlantiss/NetherwingBugtracker#7676]
[//]: # (Enclose links to things related to the bug using http://wowhead.com or any other TBC database.)
[//]: # (You can use screenshot ingame to visual the issue.)
[//]: # (Write your tickets according to the format:)
[//]: # ([Quest][Azuremyst Isle] Red Snapper - Very Tasty!)
[//]: # ([NPC] Magistrix Erona)
[//]: # ([Spell][Mage] Fireball)
[//]: # ([Npc][Drop] Ghostclaw Lynx)
[//]: # ([Web] Armory doesnt work)
[//]: # (To find server revision type `.server info` command in the game chat.)

**Description**: 
Item drop rate is extremely low

**Current behaviour**:
About 50 Shield Guards yeilded 3 tokens.

**Expected behaviour**: 
~25 tokens due to 50% drop chance
https://classic.wowhead.com/item=3714/worn-stone-token

**Server Revision**: 
N/A

**Comment by Wolffenstein** [comment]
Fixed in rev 3550.
