### ISSUE TITLE
[spell][Warlock] Curse of Exhaustion

### ISSUE THREAD

**Issue by alanparrish** [Atlantiss/NetherwingBugtracker#7677]
[//]: # (Enclose links to things related to the bug using http://wowhead.com or any other TBC database.)
[//]: # (You can use screenshot ingame to visual the issue.)
[//]: # (Write your tickets according to the format:)
[//]: # ([Quest][Azuremyst Isle] Red Snapper - Very Tasty!)
[//]: # ([NPC] Magistrix Erona)
[//]: # ([Spell][Mage] Fireball)
[//]: # ([Npc][Drop] Ghostclaw Lynx)
[//]: # ([Web] Armory doesnt work)
[//]: # (To find server revision type `.server info` command in the game chat.)

**Description**: 
when you stealth or prowl while being affected by curse of exhaustion stealth will get removed after curse of exhaustion duration expires. havent tested the behavior with other curses as they expire or how the interaction works when the curse is being decursed. easy to reproduce, just have a warlock put the curse on a stealth class
**Current behaviour**:
put curse of exhaustion on someone, let them stealth/prowl, wait 12sec and see stealth gets removed
**Expected behaviour**: 
curse should run out but stealth/prowl should not be removed from the target
**Server Revision**: 
3548

**Comment by Wolffenstein** [comment]
Fixed in rev 3556.
