### ISSUE TITLE
[Item][Legs]

### ISSUE THREAD

**Issue by MikeBison1** [Atlantiss/NetherwingBugtracker#7678]
**Description**: 
The item Consortium Plated Legguards should be adding damage to spells but doesn't on either Character page or to spells

**Current behaviour**:
The tooltip states:
Equip: Increases healing done by up to 51 and 
damage done by up to 17 for all magical spells and effects
Equip: Restores 8 mana per 5 sec.

Spell damage doesn't appear on Character Sheet or in damaging spells

**Expected behaviour**: 
The character pane should update to reflect the damage increase & spell damage should apply.

Example video:
https://drive.google.com/file/d/1SB85ye5_pIxxaCyqlOjF0aTi--A4HR5F/view?usp=sharing
[50mb video file]

**Server Revision**: 
3548

**Comment by raethkcj** [comment]
This is part of Karazhan's 2.0 itemization. In retail TBC, healing items didn't get spell damage added until Patch 2.3 (Zul'Aman). If you would like to hide the spell damage from the tooltips, you can use this addon: https://github.com/nullfoxh/NWTooltipFix

**Comment by MikeBison1** [comment]
Ah interesting. Using that video as an example, does this mean that only "healing & damage" items will therefore apply spelldamage as the ring has both whereas the legs have "healing x / damage y" ?

**Comment by raethkcj** [comment]
Yes, exactly. When it says "damage and healing by X" it's both.
When it's "Healing by X and Damage by Y" , it's actually only the "Healing by X" part.

**Comment by MikeBison1** [comment]
Understood, hopefully this is addressed in the ZA update but for now, closing this ticket.
