### ISSUE TITLE
Getting Down to Business doesn't work

### ISSUE THREAD

**Issue by Patriot-gera** [Atlantiss/NetherwingBugtracker#7679]
Quest Getting Down to Business doesn't work. I cannot pass it when it done, no ?question? mark on the npc. Netherstorm

**Comment by raethkcj** [comment]
This quest is not turned in to the same NPC where you accept it. There is another NPC hiding in the shadows behind the hologram pad.

**Comment by Patriot-gera** [comment]
where is he?
