### ISSUE TITLE
[Spell][Shaman] Purge

### ISSUE THREAD

**Issue by Retinus** [Atlantiss/NetherwingBugtracker#768]
**Description**: If you are out of combat and cast an offensive spell on a mob then you should get in combat with the mob. 

**Current behavior**: If you cast purge on a mob which don't have a buff then you get the message "Nothing To Dispel". If you cast purge on a mob which have a buff mob just buff himself again. Tested on Bristleback Thornweaver (Entry: 3261, SpawnId - (Entry: 3261, Id: 1), GUIDLow: 41776)

**Expected behavior**: If you cast purge on a mob which have a buff mob should attack you and get you in combat. I suppose priest's dispel should work the same way.

**Server Revision**: 2072

**Comment by killablink** [comment]
If a mob has no buff to dispel//purge//spellsteal you should get the message nothing to dispel though (not sure why it was mentioned). But indeed if the mob has a buff and you dispel him when out of the combat, it should aggro the mob

**Comment by Retinus** [comment]
Wasn't sure what system should do when the mob has no buff and i just described what i tested
