### ISSUE TITLE
Gnomeregan: Data Rescue Quest, White keycard does not drop for me

### ISSUE THREAD

**Issue by Retheion** [Atlantiss/NetherwingBugtracker#7681]
[//]: # (Enclose links to things related to the bug using http://wowhead.com or any other TBC database.)
[//]: # (You can use screenshot ingame to visual the issue.)
[//]: # (Write your tickets according to the format:)
[//]: # ([Quest][Azuremyst Isle] Red Snapper - Very Tasty!)
[//]: # ([NPC] Magistrix Erona)
[//]: # ([Spell][Mage] Fireball)
[//]: # ([Npc][Drop] Ghostclaw Lynx)
[//]: # ([Web] Armory doesnt work)
[//]: # (To find server revision type `.server info` command in the game chat.)

**Description**: 
White keycard does not drop for me, three members in group got it, another member and me did not get keycard.

**Current behaviour**:

**Expected behaviour**: 
Keycard expected to drop from non-elites outside instance.

**Server Revision**:

**Comment by Wolffenstein** [comment]
Fixed in rev 3556.
