### ISSUE TITLE
Paladin Seal of Blood

### ISSUE THREAD

**Issue by Bongyii** [Atlantiss/NetherwingBugtracker#7683]
[//]: # (Enclose links to things related to the bug using http://wowhead.com or any other TBC database.)
[//]: # (You can use screenshot ingame to visual the issue.)
[//]: # (Write your tickets according to the format:)
[//]: # ([Quest][Azuremyst Isle] Red Snapper - Very Tasty!)
[//]: # ([NPC] Magistrix Erona)
[//]: # ([Spell][Mage] Fireball)
[//]: # ([Npc][Drop] Ghostclaw Lynx)
[//]: # ([Web] Armory doesnt work)
[//]: # (To find server revision type `.server info` command in the game chat.)

**Description**: 
([Spell][Paladin] Seal of Blood) is not working as expected. Already contacted a GM and he said he checked and it is a bug.
**Current behaviour**:
When I use seal of the crusader on a mob the extra holy damage is not added to the Seal of Blood damage when I hit the mob with a weapon and using that seal. However it gives bonus damage when I unleashed the Seal of Blood on the target (using judgement).
**Expected behaviour**: 
When I use seal of the crusader on a mob I should get extra holy damage when I hit with Seal of Blood.
**Server Revision**:

**Comment by raethkcj** [comment]
https://wowwiki.fandom.com/wiki/Spell_power_coefficient?oldid=1336186

This page suggests that Judgement of Blood scales with spell power, but Seal of Blood does not. 

Do you have a source for Seal of Blood having a spell power coefficient?

**Comment by Ibuprofeno** [comment]
This is a tooltip problem: JotC does not increase Holy DMG but Holy SPELL DMG:
https://www.wowhead.com/forums&topic=35733#p327974
"The Jotc tooltip is a little off, it says dmg taken by but really only increases your spellpower against the target so abilities without any or a low coefficient receive very little to no benefit."

Seal of Command is the only weapon dmg based seal that scales off spellpower (implied by patch notes changes in vanilla 1.9, hard to get sp coeficient sources but this is close https://www.reddit.com/r/classicwow/comments/95abc8/list_of_spellcoefficients_1121/ https://us.forums.blizzard.com/en/wow/t/seal-of-crusader-increase-holy-damage/430407/7
![imagen](https://user-images.githubusercontent.com/5463460/101186982-0ee56700-3654-11eb-8457-4d8588f48233.png)
)
SOB: https://wow.gamepedia.com/Seal_of_Blood
![imagen](https://user-images.githubusercontent.com/5463460/101186148-fcb6f900-3652-11eb-9635-97fe27b6ecbb.png)
![imagen](https://user-images.githubusercontent.com/5463460/101186654-ab5b3980-3653-11eb-93fc-e4bdac39ea5a.png)
SOC: https://wow.gamepedia.com/Seal_of_Command
![imagen](https://user-images.githubusercontent.com/5463460/101186767-d0e84300-3653-11eb-895f-04af4f177406.png)
