### ISSUE TITLE
Swift Flying Broom can be used in combat

### ISSUE THREAD

**Issue by BaldurKara** [Atlantiss/NetherwingBugtracker#7684]
[//]: # (Enclose links to things related to the bug using http://wowhead.com or any other TBC database.)
[//]: # (You can use screenshot ingame to visual the issue.)
[//]: # (Write your tickets according to the format:)
[//]: # ([Quest][Azuremyst Isle] Red Snapper - Very Tasty!)
[//]: # ([NPC] Magistrix Erona)
[//]: # ([Spell][Mage] Fireball)
[//]: # ([Npc][Drop] Ghostclaw Lynx)
[//]: # ([Web] Armory doesnt work)
[//]: # (To find server revision type `.server info` command in the game chat.)

**Description**: 
Swift Flying Broom can be used in combat. (either this or somehow the hunter managed to Feign Death and instant cast it)
Sadly i cant test it myself since i dont have one.

**Current behaviour**:
See above.

**Expected behaviour**: 
You need to drop combat to use mounts.

**Server Revision**: 
3550

**Comment by Wolffenstein** [comment]
Fixed
