### ISSUE TITLE
[Quest][Item] Bleeding Hollow Blood is acting like it's Unique for some players

### ISSUE THREAD

**Issue by raethkcj** [Atlantiss/NetherwingBugtracker#7685]
**Description**: 
For the quest [Boiling Blood], players collect 12 Bleeding Hollow Blood and use the cauldron to convert them into Boiled Blood.

**Current behaviour**:
For *some* players, Bleeding Hollow blood is acting like a Unique item. If you have one in your bags, no more will drop until you use the cauldron to convert it. If you join a party, you will see party members' shared loot drops, but you get an error message when attempting to loot them. 

This is *NOT* an RNG / drop rate issue. Many players in the zone were talking about this issue, having killed 20+ orcs and receiving exactly one drop. As soon as they convert the blood, they get another drop in 1-2 kills max.

It appears that it's only affecting certain characters; some players reported quickly farming all 12 bloods before converting any.

**Expected behaviour**: 
[Bleeding Hollow Blood] drops and stacks normally, regardless of whether you have one in your inventory.

**Server Revision**: 
3548

**Comment by Wolffenstein** [comment]
Fixed in rev 3556.
