### ISSUE TITLE
[NPC] Astromancer Solarian - Bugged Arcane Missile behavior

### ISSUE THREAD

**Issue by MecAtlantiss** [Atlantiss/NetherwingBugtracker#7686]
[//]: # (Enclose links to things related to the bug using http://wowhead.com or any other TBC database.)
[//]: # (You can use screenshot ingame to visual the issue.)
[//]: # (Write your tickets according to the format:)
[//]: # ([Quest][Azuremyst Isle] Red Snapper - Very Tasty!)
[//]: # ([NPC] Magistrix Erona)
[//]: # ([Spell][Mage] Fireball)
[//]: # ([Npc][Drop] Ghostclaw Lynx)
[//]: # ([Web] Armory doesnt work)
[//]: # (To find server revision type `.server info` command in the game chat.)

**Description**: 
Astromancer Solarian is casting Arcane Missiles on people she does not have targeted and who I believe should not be able to be targeted. An explanation and a few videos are provided in the next section.

**Current behaviour**:
After Astromancer Solarian finishes a "Wrath of the Astromancer" cast, she will often briefly target, or not target at all, a random person that she was facing at the end of the "Wrath of the Astromancer" cast and then cast Arcane Missiles on this person. If she does target the person, it will be for a matter of milliseconds and then she will target the person with highest threat (i.e. the main tank) even when the person with highest threat is not the person currently having Arcane Missiles firing on them.

Example #1: https://clips.twitch.tv/FurrySeductivePastaSeemsGood

This clip is from the perspective of Medry, who has the highest threat on Astromancer Solarian. Astromancer Solarian turns to cast Wrath of the Astromancer on Sevomira who is a warlock standing behind Astromancer Solarian. At the end of the Wrath cast, Solarian BRIEFLY targets Tripsixes (who is also standing behind Solarian), begins casting Arcane Missiles on Tripsixes, but then Solarian immediately re-targets and faces Medry despite Medry not being the target of the Arcane Missiles.

Example #2: https://clips.twitch.tv/BrightAlluringWatermelonMVGame

Again, Solarian turns to cast Wrath on Anticipating, then BRIEFLY targets Tb, casts Arcane Missiles on Tb, and then immediately goes back to targeting and facing Medry. 

Example #3: https://clips.twitch.tv/TiredBeautifulCroissantPipeHype

Here's an even worse version of the bug, because here she doesn't even target the person who gets Arcane Missiled. She casts Wrath on Yorva and then targets and faces Medry, but she's actually casting Arcane Missiles on Tb. You can see how Solarian is facing Medry, but the Arcane Missiles are not being cast on him and are instead firing behind Solarian. 

Example #4: https://clips.twitch.tv/ElegantBadDinosaurEleGiggle

Here is another example of the version of the bug where she never targets the person she is Arcane Missiling. This time she casts Wrath on Appears, but then casts Arcane Missiles on Minerva without ever targeting him.

**Expected behaviour**: 

I admit I am not sure how this spell interaction worked with Astromancer Solarian worked on patch 2.0, but I have to think that it is a bug that Astromancer Solarian is casting Arcane Missiles immediately after finishing her Wrath of the Astromancer cast, since this presumed bug allows her to cast Arcane Missiles on raid members who would not be in the 180 degree cone in front of her when she's facing the person with highest threat. I would think that there should be some delay between the end of a Wrath cast and the beginning of the next Arcane Missile cast, so that Solarian has time to face the main tank again before choosing an Arcane Missile target.

At the very least, shouldn't she be targeting the person she's casting Arcane Missiles on for the entire duration of the Arcane Missile cast and not just for a few milliseconds? At least this way healers would have an easier time healing through the damage. But I worry that this would not fix the issue, because if she is targeting that person for the full duration then she'd be facing them at the end of the Arcane Missile cast and the bug would just repeat.... She must at some point have time to face the person with highest threat before choosing the next Arcane Missile target, no?

**Server Revision**: 3548

**Comment by Easyfraggy** [comment]
Bit of a wall of text.

Known issue that she casts arcane missiles in the wrong direction after casting wrath. Maybe a quick fix would just be to delay arcane missiles cast 2 seconds after wrath cast end (so like 4 seconds from cast)

**Comment by Wolffenstein** [comment]
Fixed in rev 3556.
