### ISSUE TITLE
Drek'thar crushing for 2x damage, crushes should do 1.5x

### ISSUE THREAD

**Issue by babno** [Atlantiss/NetherwingBugtracker#7687]
![image](https://user-images.githubusercontent.com/244626/98393869-ea33aa80-2027-11eb-9a00-fcae8bc8ec07.png)

**Comment by raethkcj** [comment]
Drek'Thar is dual wielding; is it possible the first hit was an offhand hit? Offhands usually do less damage.

**Comment by babno** [comment]
His offhand was doing about 2k hits
