### ISSUE TITLE
Durotar Tiger Fur

### ISSUE THREAD

**Issue by Incipitt** [Atlantiss/NetherwingBugtracker#7689]
[//]: # (Enclose links to things related to the bug using http://wowhead.com or any other TBC database.)
[//]: # (You can use screenshot ingame to visual the issue.)
[//]: # (Write your tickets according to the format:)
[//]: # ([Quest][Azuremyst Isle] Red Snapper - Very Tasty!)
[//]: # ([NPC] Magistrix Erona)
[//]: # ([Spell][Mage] Fireball)
[//]: # ([Npc][Drop] Ghostclaw Lynx)
[//]: # ([Web] Armory doesnt work)
[//]: # (To find server revision type `.server info` command in the game chat.)

**Description**: 
http://tbc.cavernoftime.com/npc=3121

Durotar Tiger Fur is not dropped (at least at expected drop rate)
**Current behaviour**:
1/13 durotar tigers didnt drop a single fur
**Expected behaviour**: 
not scuffed droprates
**Server Revision**:

**Comment by Godmatik** [comment]
Should be 45% according, at least that's what it is on classic.

https://classic.wowhead.com/item=4892/durotar-tiger-fur

**Comment by Wolffenstein** [comment]
Fixed in rev 3556.
