### ISSUE TITLE
[NPC][Quest] Aldraon the Reckless chain pull - Eversong Forest

### ISSUE THREAD

**Issue by anonyReporter** [Atlantiss/NetherwingBugtracker#769]
**Description**: 
Killing Aldron the Reckless chain pulls the Wretched Thug next to him, after killing Aldron, the Wretched Thug drops aggro and resets.
**Current behaviour**:
Chain pulled mob resets after killing Aldron
**Expected behaviour**: 
Chain pulled mob should not reset
**Server Revision**: 
2073

**Comment by Evolvee** [comment]
Cant reproduce that, it probably evaded based on regular leashing mechanic.
