### ISSUE TITLE
[Quest] Master of Elixir Drop Rate

### ISSUE THREAD

**Issue by totaemoeggerli** [Atlantiss/NetherwingBugtracker#7690]
**Current behaviour**:
Drop chance for [Essence of Infitiy](https://www.wowhead.com/item=31753/essence-of-infinity#dropped-by) required for the quest [Master of Elixir](https://www.wowhead.com/quest=10902/master-of-elixirs) seems to be extremely low. I ran two full runs and only got 1 Essence from 30 mobs that could drop the item. 

**Expected behaviour**: 
Many commenters from TBC and WotLK reported that they've completed the quest with 2-3 runs. This is contradicts the 3% drop chance listed on wowhead. However, Drop chances from that period often included players who were not on that quest and therefore falsified the data in a big way. The drop chance listed on tbcdb 40-55% is a lot more inline with the comments.

**Server Revision**: 3551

**Comment by totaemoeggerli** [comment]
In other words: Assuming the drop chance is 50%, I didn't get a single head when tossing 30 coins. The probability for this to happen is 1/35.79 million

**Comment by Godmatik** [comment]
Sounds like bad luck, I got all my essences in 3 runs.

**Comment by Wolffenstein** [comment]
It's set to 35%. The majority of wowhead comments also seem to be complaining about the drop rates and empty runs so it appears to be in line with what it was on retail.
