### ISSUE TITLE
Magic Broom and Swift Magic Broom durations

### ISSUE THREAD

**Issue by Godmatik** [Atlantiss/NetherwingBugtracker#7693]
The "days left" duration of these items isn't counting down properly.

Mine still show 12 days left, but I received them almost two weeks ago.

**Comment by alanparrish** [comment]
maybe it is counting actual time spent in the game aka playtime instead of real time when expiring?

**Comment by Godmatik** [comment]
Makes sense, but it should instead go off real time, otherwise we'll have brooms flying around well into December.

**Comment by tsuone** [comment]
It should be real time and not game time.

**Comment by Godmatik** [comment]
I see it was fixed, closing
