### ISSUE TITLE
[Patch 2.1] Epic crafted Blacksmithing weapons should have updated DPS in Patch 2.1

### ISSUE THREAD

**Issue by raethkcj** [Atlantiss/NetherwingBugtracker#7696]
**Description**: 
Patch 2.1 updated the DPS values for blacksmithing weapons. It seems Karazhan's patch updated 2-handed weapons, but not 1-handed weapons.

Here is Dragonstrike in June 2007, during Patch 2.1 with 97.6 dps, while ingame it still has 95.0 dps: http://web.archive.org/web/20070605235501/http://www.thottbot.com/i28439

This change affects the 9 weapon specialization weapons; the three progressive versions of 1-handed hammers, axes, and swords. Item IDs:

28425
28426
28427

28437
28438
28439

28431
28432
28433

**Current behaviour**:
1-handed BS weapons still using 2.0 DPS values

**Expected behaviour**: 
1-handed BS weapons use 2.1 DPS values (the updates values are equal to their final 2.4 values)

**Server Revision**: 
3553

**Comment by Wolffenstein** [comment]
Dragonstrike was updated in 2.4, not 2.1.

**Comment by raethkcj** [comment]
2.4 updated the Unique and Main-Hand proprieties of Dragonstrike. That's not the change this report is addressing.

This report is *only* about the DPS and damage range. Compare the thotbot archive in May and July, it's clear it was changed @Wolffenstein 
http://web.archive.org/web/20070605235501/http://www.thottbot.com/i28439
