### ISSUE TITLE
Pauldrons of Wild Magic not in game but Stormsong Kilt is

### ISSUE THREAD

**Issue by lykann1337** [Atlantiss/NetherwingBugtracker#7697]
Both the Stormsong Kilt and Pauldrons of Wild Magic were meant to be released in 2.1 however Stormsong Kilt is already in the game which would lead me to believe that Pauldrons of Wild Magic also should be in the game and yet they do not appear to be

Twinstar link for Stormsong Kilt - 
https://tbc-twinhead.twinstar.cz/?item=30541#dropped-by

Twinstar link for Pauldrons of Wild Magic - 
https://tbc-twinhead.twinstar.cz/?item=32078

**Comment by lykann1337** [comment]
this is on Karazhan server btw, sorry should have specified

**Comment by Godmatik** [comment]
Wowhead comments are from 2.0 regarding this item dropping so I think it was added in 2.0.

Don't rely on the "added in" patch note from the wowhead info

https://www.wowhead.com/item=30541/stormsong-kilt?bonus=6710#comments
