### ISSUE TITLE
Alchemy learn

### ISSUE THREAD

**Issue by Tjadyda** [Atlantiss/NetherwingBugtracker#7698]
Hello, I don't know why the coach at Alchemy won't teach me [Elixir of Draenic Wisdom](https://www.wowhead.com/item=32067/elixir-of-draenic-wisdom), I have skill 368 and the coach at Helfire doesn't offer me anything to learn. I tested clear cache, nothing, i go coach Helfire or SC nothing learn for me. Thank you for your help.
Server Karazhan TBC

**Comment by Godmatik** [comment]
That elixir is not released until patch 2.1
