### ISSUE TITLE
Stalker's War Bands give less AP then they should

### ISSUE THREAD

**Issue by Cathzulu** [Atlantiss/NetherwingBugtracker#7699]
**Description**: 
![InkedWoWScrnShot_111120_233440_L](https://user-images.githubusercontent.com/74330613/98876320-5413e000-247e-11eb-8e34-559397f6d71a.jpg)
![WoWScrnShot_111220_002810](https://user-images.githubusercontent.com/74330613/98876328-570ed080-247e-11eb-9929-728549500a81.jpg)
As you can see, when i equip Stalker's i get 20 less AP than Auchendai Bracers even though they should give the same ammount when you count in the enchants and gem. Since 1 str gives 2 AP (for shamans) both bracers should give 68 AP, but they don't.

**Current behaviour**:
Auchendai Bracers gives 20 more AP than Stalker's War Bands.

**Expected behaviour**: 
Both bracers should at least give the same ammount of AP.

**Server Revision**: 3553

**Comment by raethkcj** [comment]
You're losing 20 AP from your Meta Gem because you lose the 1 required yellow gem.
