### ISSUE TITLE
[Spell][Rogue]Eviscerate bugged

### ISSUE THREAD

**Issue by galediex** [Atlantiss/NetherwingBugtracker#77]
[//]: # (Enclose links to things related to the bug using http://wowhead.com or any other TBC database.)
[//]: # (You can use screenshot ingame to visual the issue.)
[//]: # (Write your tickets according to the format:)
[//]: # ([Quest][Azuremyst Isle] Red Snapper - Very Tasty!)
[//]: # ([NPC] Magistrix Erona)
[//]: # ([Spell][Mage] Fireball)
[//]: # ([Npc][Drop] Ghostclaw Lynx)
[//]: # ([Web] Armory doesnt work)

**Description**: Eviscerate spending combo points and energy incorrectly.

**Current behaviour**: Eviscerate spending combo points when dodged and parried. Eviscerate spending max energy when dodged/parried when it should only spend a portion of the energy.

**Expected behaviour**: Eviscerate should not spend any combo points when dodged or parried. Eviscerate should only spend a portion of the energy required to use Eviscerate when dodged or parried.

**Server Revision**: 2.4.3 Netherwing Open Beta Server

**Comment by Wolffenstein** [comment]
Proof?

**Comment by galediex** [comment]
how should i go about proving it?

**Comment by galediex** [comment]
I'm not saying finishers don't spend energy when missed. I'm saying they only spend a portion when missed idk the exact number but i'm sure most rogues will notice this change. For example eviscerate cost 35 energy to use and when missed/parried it cost maybe 20 energy. that talent would still take that 20 down another 40% so it wouldn't be useless. i hope this clears it up but the best proff i can provide it this is how it works on warmanes TBC realm and a few others i've tested even on other expansion i've seen this.

**Comment by Wolffenstein** [comment]
My bad, I see that there was just stuff missing in certain part of the code. Should be fixed in rev 2028.

**Comment by galediex** [comment]
i just tested it again and it's still bugged i'm still losing all my combo points when i miss my finisher.

**Comment by ahlens** [comment]
Tested eviscerate and it seems ok in terms of combo points. 

I lost full value of energy. I have no idea how much energy should be consumed on dodge or parry though

https://vimeo.com/user9632932/review/299879626/15c3afd517

**Comment by Wolffenstein** [comment]
Should be fixed now
