### ISSUE TITLE
[Movement] Sometimes underwater creatures use landscape instead of just swimming towards target.

### ISSUE THREAD

**Issue by Jezofine** [Atlantiss/NetherwingBugtracker#770]
**Current behaviour**:
Subj happened with lobsters near Shadowprey Village in Desolace (when opening traps with shellfish). Multiple Drysnap Crawlers and Pincers that spawn near underwater floor use ground-like movement map over landscape.
[Regular crawler spawn](https://youtu.be/0728OEGdCAs) SpawnId - (Entry: 11562, Id: 4)
[Crawler spawned from trap](https://youtu.be/0HUZEc6AKVg)

UPD.
Same as #753

**Expected behaviour**:
Maybe swim and not walk on a landscape?

**Server Revision**: 2072

**Comment by Wolffenstein** [comment]
Fixed
