### ISSUE TITLE
[Hunter] [Steady Shot] Double dipping with attack power debuffs

### ISSUE THREAD

**Issue by Easyfraggy** [Atlantiss/NetherwingBugtracker#7700]
**Description**: 

**Current behaviour**:
Steady Shot double dips on attack power debuffs (Hunter's Mark and Expose Weakness)

Testing on PTR found that Hunter's Mark and Expose Weakness increased steadyshot damage by way too much.

Steadyshot with 278 attackpower and 3,3 weapon dps (5-10 damage), 2,3 speed bow. Base damage on 680 armor (6% dmg red)

Steadyshot = RAP * 0,2 + (weapondps * 2,8) + BaseDmg
Steadyshot = 278 * 0,2 + (3,3 * 2,8) +150 = 214,84 - Multiply with 0,94 for armor reduction 201 damage.

Ingame observed: Avg damage 201

Add 440 RAP from maxed out hunters mark:

Steadyshot = (278 + 440) * 0,2 + (3,3 * 2,8) +150 = 302,84 - Multiply with 0,94 for armor reduction 284,67

Ingame we observed ~352 avg damage

The same thing was tested with Expose Weakness 750 agi / 4 = 187,5 RAP

When added ontop of the hunters mark it becomes

(278+440+187,5) * 0,2 + (3,3 * 2,8) +150 = 340,34 - Multipy with 0,94 for armor reduction = 319,92

Ingame we observed 414 average.

We tested multi-shot and auto shot aswell and those lined up perfectly with our calculations with both hunters mark and expose weakness up.

We also tested with warrior Bloodthirst to see if it was a general problem and it also worked correctly there, so it seems to only affect steadyshot.

This in conjunction with https://github.com/Atlantiss/NetherwingBugtracker/issues/6865
 
Is making hunters much stronger than they should be.

**Server Revision**: 
3551

**Comment by Wolffenstein** [comment]
Fixed in rev 3554.
