### ISSUE TITLE
upgrade of higher rank pet abilities dont show up

### ISSUE THREAD

**Issue by goraxxx** [Atlantiss/NetherwingBugtracker#7702]
I am lvl 41 Draenei Hunter.
since lvl 10 i tamed a Death Ravager from Draenei starting zone "Azuremyst Isle".
I have learend the skills and abilities that the pet can use.
Gore
Bite
Dash
Growl

But when I am at the pet trainer and i can learn a higher rank of these abilities, they dont appear neither on my pet action bar or my pet spellbook.
For example i have Gore rank 3. I learned rank 4 and rank 5 at my pet trainer. But on my pet actionbar and in pet spellbook i still have rank 3. 
If i press "Already known" on the pet trainer it says that i have learned rank 4 and 5 already.

**Comment by raethkcj** [comment]
In the "General" tab of your player spellbook, use the Beast Training ability to teach new ranks to your pet.

**Comment by goraxxx** [comment]
Thank you solved
