### ISSUE TITLE
[Quest][Shadowmoon Valley] To Catch A Thistlehead

### ISSUE THREAD

**Issue by therealCrysis** [Atlantiss/NetherwingBugtracker#7703]
**Description**: 
This quest sends player to set a https://www.wowhead.com/item=30616/bundle-of-bloodthistle  on the bridge which starts an event. Two NPCs:
https://www.wowhead.com/npc=21410/blood-lord-zarath
https://www.wowhead.com/npc=21409/envoy-icarius
appear, and after short chat Envoy Icarius sends Blood-Lord Zarath away and then player has to kill this envoy to get item: https://www.wowhead.com/item=30617/stormrage-missive which is needed to complete quest.

**Current behaviour**:
https://youtu.be/EqV-WTaY1j4
**Expected behaviour**: 
Icarius should be targettable and possible to kill so player might loot essential quest item.
**Server Revision**: 
3555

**Comment by Wolffenstein** [comment]
Fixed in rev 3556.
