### ISSUE TITLE
[spell][paladin]consecration

### ISSUE THREAD

**Issue by alanparrish** [Atlantiss/NetherwingBugtracker#7704]
[//]: # (Enclose links to things related to the bug using http://wowhead.com or any other TBC database.)
[//]: # (You can use screenshot ingame to visual the issue.)
[//]: # (Write your tickets according to the format:)
[//]: # ([Quest][Azuremyst Isle] Red Snapper - Very Tasty!)
[//]: # ([NPC] Magistrix Erona)
[//]: # ([Spell][Mage] Fireball)
[//]: # ([Npc][Drop] Ghostclaw Lynx)
[//]: # ([Web] Armory doesnt work)
[//]: # (To find server revision type `.server info` command in the game chat.)

**Description**: 
consecration is an aoe ground effect that should break stealth/prowl of enemy players upon inflicting damage to them
**Current behaviour**:

whenever you enter the consecration ground radius and gain the aura effect of "consecration" stealth/prowl buffs are removed from the player without any damage calculation being done.
tested so far:

entering stealth and using cloak of shadows, then approaching the consecration ground effect but stealth is still immediately removed.

tested same scenario without cloak of shadows, same result

did not test interaction while being shielded 
**Expected behaviour**: 

consecration should break stealth/prowl effects after damage calculations are done so only upon inflicting damage to the target rather than immediately breaking them while applying the aura effect

how to reproduce:

create a paladin, use consecration, enter stealth on a rogue and approach the consecration

**Server Revision**: 
3556

**Comment by Wolffenstein** [comment]
Not a bug, intended mechanic.

**Comment by alanparrish** [comment]
hi, do you perhaps have a video or stuff showing that it should work as it currently is on kara? from old posts i found so far it says https://www.wowhead.com/forums&topic=31807 " If they are in stealth spam Conscreation lvl 1, no matter what you should be topped of for mana, n the damage will break there stealth."

on the other active tbc servers right now it also breaks stealth only when damage is applied but maybe they are bugged then? would like to see some material on this issue if possible since i couldnt find any specific videos showcasing it

**Comment by alanparrish** [comment]
found some material from wotlk with the help of my mates https://www.youtube.com/watch?v=EwLOcI4h_kg&feature=youtu.be&t=16m39s timestamp showing how kalimist straight up runs through consecration in stealth (has a shield tho and its different on wotlk with shield and stealth) but you can see the aura gain of consecration doesnt break it

http://www.arenajunkies.com/topic/133038-druid-stealth-working-differently-than-rogue-stealth/

    Consecrate only pops you out of stealth if you are hit by it when they cast it (caught in the 'wave' it creates..) the first time or it actually ticks and deals damage so that would be a bad example (unless you mean you can pounce for 2 seconds after taking damage which would be extremely weird and far-fetched).

says that it breaks on damage 

which material did you look at for scripting the effects as they are now if you still remember/have access to it?

**Comment by alanparrish** [comment]
anything?
