### ISSUE TITLE
Dire Maul Tribute Run

### ISSUE THREAD

**Issue by chadyelias** [Atlantiss/NetherwingBugtracker#7705]
"Stomper Kreeg" is now showing as hostile after wearing the Gordok Ogre Suit. And therefore it's not possible to buy stuff from him.

**Comment by Shakawkawkaw** [comment]
push, or make this guy friendly permanently

**Comment by tsu-1** [comment]
Dire Maul requires complete overhaul, it has never been touched. Such issues would not be important as if it is going to be fixed, we are going to make it from scratch. Closing.
