### ISSUE TITLE
.join not working after logging out

### ISSUE THREAD

**Issue by Dumbledood** [Atlantiss/NetherwingBugtracker#7706]
.Join has been acting up occasionally. Both out in the world and in cities. Last time it happened was right after logging onto on an alt and then back on my main. The time before may have been caused by something else.

**Comment by tsuone** [comment]
@Dumbledood Is it not working for some amount of time or you can't use the comment after logging out at all?

**Comment by Godmatik** [comment]
Unable to reproduce - probably fixed at some point
