### ISSUE TITLE
Hunters have no deadzone

### ISSUE THREAD

**Issue by Dumbledood** [Atlantiss/NetherwingBugtracker#7709]
I've played a lot of hunter, and they definitely have a deadzone, or should. But on this server if it exists it's absolutely tiny. TBH, I don't think they have one, and can either hit you at range or with a melee attack. It makes them a little more OP than usual.

**Comment by raethkcj** [comment]
Hunter dead zone was removed in Patch 2.3, so this is working as intended: https://wowwiki.fandom.com/wiki/Dead_zone
