### ISSUE TITLE
[NPC]Splinter Fist Firemonger

### ISSUE THREAD

**Issue by Thorgrimme** [Atlantiss/NetherwingBugtracker#771]
[//]: # (Enclose links to things related to the bug using http://wowhead.com or any other TBC database.)
[//]: # (You can use screenshot ingame to visual the issue.)
[//]: # (Write your tickets according to the format:)
[//]: # ([Quest][Azuremyst Isle] Red Snapper - Very Tasty!)
[//]: # ([NPC] Splinter Fist Firemonger)
[//]: # ([Spell]Qucik Flame Ward)
[//]: # ([Npc][Drop] Ghostclaw Lynx)
[//]: # ([Web] Armory doesnt work)

**Description**: The npc casts the Quick Flame Ward on its enemy, making "me" immune to his firespells.

**Current behaviour**:

**Expected behaviour**: 

**Server Revision**: 

![wow_2018-09-27_19-34-02](https://user-images.githubusercontent.com/43525297/46163767-5742b680-c28c-11e8-8680-4ecf58236722.jpg)

**Comment by Easyfraggy** [comment]
You closed this, was it invalid report or?
