### ISSUE TITLE
[NPC] Kael'Thas Sunstrider - Gravity Lapse teleporting people into Flamestrike

### ISSUE THREAD

**Issue by MecAtlantiss** [Atlantiss/NetherwingBugtracker#7711]
[//]: # (Enclose links to things related to the bug using http://wowhead.com or any other TBC database.)
[//]: # (You can use screenshot ingame to visual the issue.)
[//]: # (Write your tickets according to the format:)
[//]: # ([Quest][Azuremyst Isle] Red Snapper - Very Tasty!)
[//]: # ([NPC] Magistrix Erona)
[//]: # ([Spell][Mage] Fireball)
[//]: # ([Npc][Drop] Ghostclaw Lynx)
[//]: # ([Web] Armory doesnt work)
[//]: # (To find server revision type `.server info` command in the game chat.)

**Description**: Kael'Thas is killing people in a way with little to no counterplay.

**Current behaviour**: Kael'Thas is currently able to cast flamestrikes just before casting Gravity Lapse, which can cause people to get teleported onto the flamestrike as the flamestrike is going off. This instantly kills people and I don't think there's always counterplay. 

Here is a clip of this occurring: https://clips.twitch.tv/TolerantOriginalOctopusKappaClaus

**Expected behaviour**: I'm not sure exactly what the expected behavior is, but my thinking is that Kael'Thas should not be able to cast flamestrike for maybe 10 seconds prior to an incoming Gravity Lapse cast. Something like that so that this combination doesn't happen. Or maybe just teleport players high enough into the air initially so that the flamestrike can't hit them?

**Server Revision**: 3555

**Comment by Godmatik** [comment]
Still an issue, see below video, tank died to unavoidable gravity lapse into flamestrike.

https://www.youtube.com/watch?v=BUHWxDmfWlo

**Comment by Wolffenstein** [comment]
Fixed in rev 3585.
