### ISSUE TITLE
[Item] [Shiffar's Nexus-Horn] Equip effect on critical hit is not working

### ISSUE THREAD

**Issue by korner11** [Atlantiss/NetherwingBugtracker#7712]
https://wowwiki.fandom.com/wiki/Shiffar%27s_Nexus-Horn

**Description**: Shiffar's Nexus-Horn equip effect on critical hit is not triggering bonus effect. I know its not on every crit hit, but was watching it for whole the dungeon and was not triggered once

**Current behaviour**: Equiped item on critical hit is not triggering bonus effect.

**Expected behaviour**: Equiped item on critical hit will trigger bonus effect.

**Server Revision**:  3555

**Comment by bidaumm** [comment]
It has a 20% chance on crit to proc. I was using it yesterday and it is proccing fine.

**Comment by korner11** [comment]
I moved item to second trinket slot and noticed bonus effect. Maybe on first slot is somehow broken.

**Comment by Wolffenstein** [comment]
Can't reproduce.
