### ISSUE TITLE
[NPC] Arcane Anomaly in Karazhan - One pack constantly spawning in the pillar

### ISSUE THREAD

**Issue by bidaumm** [Atlantiss/NetherwingBugtracker#7713]
**Description**: 
One of the Arcane Anomaly packs on the right side facing towards curator is consistently spawning in the pillar
We have had this bug happen in the last 4 of our Karazhan runs.
The Arcane Anomaly may teleport out but wraiths will often stay evade bugged inside the pillar and be unattackable forcing the group to be stuck in combat

Server Revision: 3556

**Comment by Wolffenstein** [comment]
Fixed in rev 3830.
