### ISSUE TITLE
[PTR] Many GM commands have recently stopped working on PTR

### ISSUE THREAD

**Issue by MecAtlantiss** [Atlantiss/NetherwingBugtracker#7714]
[//]: # (Enclose links to things related to the bug using http://wowhead.com or any other TBC database.)
[//]: # (You can use screenshot ingame to visual the issue.)
[//]: # (Write your tickets according to the format:)
[//]: # ([Quest][Azuremyst Isle] Red Snapper - Very Tasty!)
[//]: # ([NPC] Magistrix Erona)
[//]: # ([Spell][Mage] Fireball)
[//]: # ([Npc][Drop] Ghostclaw Lynx)
[//]: # ([Web] Armory doesnt work)
[//]: # (To find server revision type `.server info` command in the game chat.)

**Description**: Prior to the 2.1 itemization server restart, the PTR allowed anyone to use a wide variety of commands such as `.tele`, `.modify`, `.die`, and `.learn`. After the 2.1 itemization restart, it looks like a new copy of the production server was created to be the new PTR and now we cannot use most commands. These commands are really important for those of us who want to test/develop addons or boss encounters. If requested, I can provide a list of the commands which I personally know were working previously but are no longer working.

**Current behaviour**: Cannot use important testing commands like `.tele` and `.modify`.

**Expected behaviour**: Can use the same commands we could use prior to the 2.1 itemization restart.

**Server Revision**: PTR server on revision 3555

**Comment by danbopes** [comment]
Type `.account` give me your level (Or let me know if that command doesn't work), and I'll fix it.

Database got wiped, and the command levels were shifted around a bit.

**Comment by Xpd1** [comment]
.account gives me incorrect syntax, same issue as MecAtlantiss

**Comment by MecAtlantiss** [comment]
I also get the message "Incorrect syntax." when I type .account

**Comment by Godmatik** [comment]
Any update please?

**Comment by tilipitappi** [comment]
Any updates please? If commands cant easily be fixed could you add a test dummy in shattrath or somewhere?

**Comment by Fierywind** [comment]
Can you add dummies even if you do fix the commands? lol

**Comment by tilipitappi** [comment]
Please update

**Comment by Godmatik** [comment]
Why was this closed? 
Will this be fixed?
