### ISSUE TITLE
Warp-Raider Nesaad Energy Flux hitting about 10 times harder than it should be.

### ISSUE THREAD

**Issue by shawn571** [Atlantiss/NetherwingBugtracker#7715]
[//]: # (Enclose links to things related to the bug using http://wowhead.com or any other TBC database.)
[//]: # (You can use screenshot ingame to visual the issue.)
[//]: # (Write your tickets according to the format:)
[//]: # ([Quest][Azuremyst Isle] Red Snapper - Very Tasty!)
[//]: # ([NPC] Magistrix Erona)
[//]: # ([Spell][Mage] Fireball)
[//]: # ([Npc][Drop] Ghostclaw Lynx)
[//]: # ([Web] Armory doesnt work)
[//]: # (To find server revision type `.server info` command in the game chat.)

**Description**: Warp-Raider Nesaad's Energy Flux ability seems to be hitting a lot harder than it should. 
([NPC] Warp-Raider Nesaad)
([Spell][Warp-Raider Nesaad] Energy Flux)

**Current behaviour**: Energy Flux is hitting for about 3k per explosion
![Energy Flux damage](https://user-images.githubusercontent.com/71139409/99186823-f4892f00-2720-11eb-8ccd-a05499936903.png)

**Expected behaviour**: According to a Wowhead comment from retail version 2.0.12 dated 2007/05/06 this ability should be hitting for about 383 on a level 70 with no arcane resistance. 

(https://www.wowhead.com/quest=10205/warp-raider-nesaad)

**Server Revision**: 3556

**Comment by shawn571** [comment]
Ethereum Archon casts the same spell doing the same damage, makes the quest Delivering the Message all but impossible because one blast and the escort dies.

**Comment by Wolffenstein** [comment]
Fixed in rev 3557.
