### ISSUE TITLE
Unable to enter SSC directly after attunement removal. 

### ISSUE THREAD

**Issue by schweppes2** [Atlantiss/NetherwingBugtracker#7716]
The waterfall door is not disappearing upon approach of SSC despite the attunement removal on the 11th of November and is thus preventing direct entry.

**Comment by tsuone** [comment]
Can someone confirm this?

**Comment by Godmatik** [comment]
We've had numerous people be able to enter SSC without being attuned, never run into it.

@schweppes2 were you in a raid group?

**Comment by raethkcj** [comment]
@Godmatik you can go in just fine if you have someone who is attuned with you to remove the waterfall. If your whole raid is already inside, and you run up to the waterfall alone, it will not open for you. I don't know if this is blizzlike or not.

**Comment by Wolffenstein** [comment]
Fixed in rev 3557.
