### ISSUE TITLE
[AH] "Sold by" shows your own name

### ISSUE THREAD

**Issue by Tereneckla** [Atlantiss/NetherwingBugtracker#7719]
[//]: # (Enclose links to things related to the bug using http://wowhead.com or any other TBC database.)
[//]: # (You can use screenshot ingame to visual the issue.)
[//]: # (Write your tickets according to the format:)
[//]: # ([Quest][Azuremyst Isle] Red Snapper - Very Tasty!)
[//]: # ([NPC] Magistrix Erona)
[//]: # ([Spell][Mage] Fireball)
[//]: # ([Npc][Drop] Ghostclaw Lynx)
[//]: # ([Web] Armory doesnt work)
[//]: # (To find server revision type `.server info` command in the game chat.)

**Description**: 
![image](https://user-images.githubusercontent.com/50233983/99232883-c5db8900-27f2-11eb-908b-2d5690366a8c.png)
Mail received from winning an auction bid

**Current behaviour**:
Sold by: "my name"

**Expected behaviour**: 
Sold by: "seller name"

**Server Revision**: 3556

**Comment by Wolffenstein** [comment]
Fixed in rev 3557.
