### ISSUE TITLE
[NPC] 14305 Children's week quests

### ISSUE THREAD

**Issue by Lephidiles** [Atlantiss/NetherwingBugtracker#772]
[//]: # (Enclose links to things related to the bug using http://wowhead.com or any other TBC database.)
[//]: # (You can use screenshot ingame to visual the issue.)
[//]: # (Write your tickets according to the format:)
[//]: # ([Quest][Azuremyst Isle] Red Snapper - Very Tasty!)
[//]: # ([NPC] Magistrix Erona)
[//]: # ([Spell][Mage] Fireball)
[//]: # ([Npc][Drop] Ghostclaw Lynx)
[//]: # ([Web] Armory doesnt work)

**Description**: 
Start of this quest seemed wrong although i am not sure how it is suppose to work.
The 4 or 5 first quest was just completed with the text of the last one saying "Thanks for taking me to Darnassus"
**Current behaviour**:

**Expected behaviour**: 
Guess you should actually take him some places

**Server Revision**: 
2072

**Comment by tcberk12** [comment]
#146

**Comment by Lephidiles** [comment]
Indeed it is
