### ISSUE TITLE
[Quest][Item] Divination Questlines, Goggles wont work probably

### ISSUE THREAD

**Issue by iguessineedhelp** [Atlantiss/NetherwingBugtracker#7720]
Goggles for the Divination Quests is not working probably. Equipping the goggles wont make every invisible mob appear and it also makes people unable to see the dragon/riders

**Current behaviour**:
Goggles not showing all the mobs for everyone equipping the goggles including far away

**Expected behaviour**: 
Equipping the goggles should show all the invisible mobs related to the questline including far way

**Server Revision**: 
3556

**Comment by Godmatik** [comment]
Yep I made similar report.
Still an issue.

https://github.com/Atlantiss/NetherwingBugtracker/issues/7344

**Comment by Godmatik** [comment]
Was fixed
