### ISSUE TITLE
Quest progress incorrectly counting items in bank rather than just items in inventory

### ISSUE THREAD

**Issue by shawn571** [Atlantiss/NetherwingBugtracker#7721]
[//]: # (Enclose links to things related to the bug using http://wowhead.com or any other TBC database.)
[//]: # (You can use screenshot ingame to visual the issue.)
[//]: # (Write your tickets according to the format:)
[//]: # ([Quest][Azuremyst Isle] Red Snapper - Very Tasty!)
[//]: # ([NPC] Magistrix Erona)
[//]: # ([Spell][Mage] Fireball)
[//]: # ([Npc][Drop] Ghostclaw Lynx)
[//]: # ([Web] Armory doesnt work)
[//]: # (To find server revision type `.server info` command in the game chat.)

**Description**: Quests are showing complete even when all items required for the quest completion aren't in inventory.

**Current behaviour**: I have 2 of 4 quest items in my bag, but it is saying quest is complete. This is apparently because I have the other 2 in my bank.

![WoWScrnShot_111720_082719](https://user-images.githubusercontent.com/71139409/99396007-35af4980-28af-11eb-9678-17c30876ba0f.jpg)

**Expected behaviour**: Quest objectives shouldn't say complete unless all quest items are in inventory.

**Server Revision**: 3556

**Comment by Godmatik** [comment]
Duplicate, closing
