### ISSUE TITLE
[Conjure Water/food] [Mage] Triggers the gcd when spammed

### ISSUE THREAD

**Issue by balsh** [Atlantiss/NetherwingBugtracker#7723]
**Description**: 

**Current behaviour**:
When you spam conjure water or food it will trigger the gcd (when you press the button again during the cast), preventing you to actualy spam it
**Expected behaviour**: 
You should be able to spam the button without triggering the gcd, like any other cast such as frostbolt etc.
**Server Revision**:

**Comment by Godmatik** [comment]
This happens with a lot of other abilities as well.

https://github.com/Atlantiss/NetherwingBugtracker/issues/5578

**Comment by tsuone** [comment]
Closing this one as a duplicate. Tagged Wolf in the main #5578 issue.
