### ISSUE TITLE
[Tempest Keep][NPC] Al'ar should probably reset swingtimer after Melt Armor is cast.

### ISSUE THREAD

**Issue by Easyfraggy** [Atlantiss/NetherwingBugtracker#7724]
[//]: # (Enclose links to things related to the bug using http://wowhead.com or any other TBC database.)
[//]: # (You can use screenshot ingame to visual the issue.)
[//]: # (Write your tickets according to the format:)
[//]: # ([Quest][Azuremyst Isle] Red Snapper - Very Tasty!)
[//]: # ([NPC] Magistrix Erona)
[//]: # ([Spell][Mage] Fireball)
[//]: # ([Npc][Drop] Ghostclaw Lynx)
[//]: # ([Web] Armory doesnt work)
[//]: # (To find server revision type `.server info` command in the game chat.)

**Description**: 

**Current behaviour**:
Can instakill the tank after Melt Armor with no way to outplay.

**Expected behaviour**: 
Reset swingtimer so you atleast have 1,5s (down to 0,45s from double parry haste). Right now it can happen within 0,1s of each other.

**Server Revision**:

**Comment by Wolffenstein** [comment]
Fixed in rev 3558.
