### ISSUE TITLE
AV mine disconnect issue

### ISSUE THREAD

**Issue by Dumbledood** [Atlantiss/NetherwingBugtracker#7726]
When I take the lower mine in AV, specifically the instant that the foreman dies, it disconnect me from the server. And in addition, when I try to log back in on that character while still in AV, it repeats it. 

I was able to log onto alts fine, but it disconnected me once again after I got back on my main in AV. 

I think that I remember from the last time this happened that once the game ends I'll be able to log on without issue. 

I can't imagine this is effecting everyone, so is it on my side of things?

**Comment by tsuone** [comment]
Reported and forwarded. Duplicate. Copied content of your issue to the main one.
