### ISSUE TITLE
Aldor rep disappeared on Hatshepsut

### ISSUE THREAD

**Issue by ivanelettrico** [Atlantiss/NetherwingBugtracker#7727]
Character: Hatshepsut lvl 70 priest on Karazhan server
**Description**: 
Today i turned some Marks of Kil'Jaeden, i wanted to check my Aldor rep and i noticed that rep was gone, i became neutral to Aldor. I already completed Allegiance to the Aldor quest before reaching 70.

**Expected behaviour**: 
I hope you can restore my rep points, i don't remember how muche rep i had before, i just remember i turned some Marks to the appropriate NPC and i was frendly.

**Comment by Godmatik** [comment]
Did you transfer faction ?

**Comment by ivanelettrico** [comment]
No, my char was from 1 to 70 horde side

**Comment by Godmatik** [comment]
Are you blood elf ?

**Comment by ivanelettrico** [comment]
Yes

**Comment by Godmatik** [comment]
This is likely why, Aldor don't like Blood elf cause they are Draenei faction, so you start with less rep compare to other classes (and if you went Scryer you start with bonus rep)

**Comment by ivanelettrico** [comment]
Wait what? I never noticed it in many years!
Thanks for the help mate!

**Comment by tsuone** [comment]
Solved.
