### ISSUE TITLE
[Tooltip][Paladin] Tooltips on buffs don't display correct values.

### ISSUE THREAD

**Issue by Tharagorn** [Atlantiss/NetherwingBugtracker#7728]
**Description**: 
Hello, Im currently leveling a paladin on the Karazhan realm and I've noticed that the tooltips of the buffs at the top right of the screen dont show the correct nubmers. I have 5 pts in Improved Devotion aura which is a 40% increase. The armor bonus is given and the tooltip of the spell (at the aura bar) shows the correct value. However when the aura is active, the Buff tooltip on the top right of the screen shows 40% less armor as if I dont have points in the talent. Same issues for Righteous Fury. With 3pts in improved RF the bonus threat is 90%. The spell tooltip shows 90%, when the buff is active it shows 60% (at top right of the screen).
Attaching screenshots
![WoWScrnShot_111920_161330](https://user-images.githubusercontent.com/74727799/99694764-acea0680-2a84-11eb-8839-3cd16ab54f64.jpg)
![WoWScrnShot_111920_161334](https://user-images.githubusercontent.com/74727799/99694776-aeb3ca00-2a84-11eb-97ea-bd2842d08e9a.jpg)
![WoWScrnShot_111920_161338](https://user-images.githubusercontent.com/74727799/99694787-afe4f700-2a84-11eb-9d45-27966810c29c.jpg)
![WoWScrnShot_111920_161342](https://user-images.githubusercontent.com/74727799/99694792-b1162400-2a84-11eb-9820-934e1ac2ed90.jpg)

**Comment by raethkcj** [comment]
This is just how the TBC client works. Not a bug.
