### ISSUE TITLE
Ethereum Jailor - Energy Flux

### ISSUE THREAD

**Issue by kern3lpan1c** [Atlantiss/NetherwingBugtracker#7731]
**Description**: 
[Ethereum Jailor](https://tbcdb.com/?npc=23008#drop)'s [Energy Flux](https://tbcdb.com/?spell=35924) spell currently does way too much damage.

**Current behaviour**:
The spell's damage modifier is way too high and hits above 3k per channel tick.

Example:
<img width="395" alt="Screen Shot 2020-11-21 at 14 26 49" src="https://user-images.githubusercontent.com/1146940/99878494-0e85ae80-2c06-11eb-911c-16b29b47f57b.png">

**Expected behaviour**: 
The spell has the correct damage modifier. It used to work in the past.

**Server Revision**: 
Atlantiss Netherwing | 3529

**Comment by Wolffenstein** [comment]
Fixed in rev 3557.
