### ISSUE TITLE
[Talent/Mechanic] [Warlock] Demonic Knowledge Deactivated On Pet Banish

### ISSUE THREAD

**Issue by F4play** [Atlantiss/NetherwingBugtracker#7733]
[//]: # ([Talent][Warlock] Demonic Knowledge
[//]: # Video: https://www.youtube.com/watch?v=l-1MnWwbeiI
[//]: # Revision: 3556

**Description**: 

When a warlock with the Demonic Knowledge talent has their pet banished, the warlock loses Demonic Knowledge. Blizzard applied a fix in patch 2.2 to prevent this.

Video: https://www.youtube.com/watch?v=l-1MnWwbeiI

**Current behaviour**:

Loses Demonic Knowledge buff when pet is banished.

**Expected behaviour**: 

Shouldn't lose the buff when pet is banished.

[From Patch 2.2 Notes - ](https://wowwiki.fandom.com/wiki/Patch_2.2.0)

> Demonic Knowledge: This effect will no longer deactivate when the Warlock's pet is Banished.

**Server Revision**: 3556

**Comment by Wolffenstein** [comment]
Fixed in rev 3557.
