### ISSUE TITLE
[QUEST] Into the Breach - still available, can not be completed

### ISSUE THREAD

**Issue by Godmatik** [Atlantiss/NetherwingBugtracker#7734]
The quest "Into the Breach" is still available, but should not be since the dark portal event was disabled, the quest is impossible to complete.

In addition, there are six Argent Protectors and Argent Guardians frantically patrolling around in front of the Dark Portal entrance, expecting to fight some demons that are no longer arriving.

https://www.wowhead.com/quest=10259/into-the-breach

**Comment by tsuone** [comment]
Fixed.
