### ISSUE TITLE
Talent rogue dirty deeds 

### ISSUE THREAD

**Issue by fulerst34** [Atlantiss/NetherwingBugtracker#7736]
Reduces the Energy cost of your Cheap Shot and Garrote abilities by 10/20. Additionally, your special abilities cause 10/20% more damage against targets below 35% health.

does not work correctly
you can get  20% only if you get critical strike    special abilities     low 35%hp

you never can kill warrior

**Comment by Easyfraggy** [comment]
Seems invalid, reporter doesn't understand the wording of the talent correctly.
