### ISSUE TITLE
Warrior can get  2  white attack instantly

### ISSUE THREAD

**Issue by fulerst34** [Atlantiss/NetherwingBugtracker#7737]
You need wait animation  wave  or  use addon wave       , and then almost wave done    , use  any scream 
and next hit   you get 2 instantly white attack

**Comment by Easyfraggy** [comment]
this is a client issue, your damage was delt the first time just the scrolling combat text doesnt show up untill the next swing. Nothing any server can do to fix this with the standard blizzard client.
