### ISSUE TITLE
([Quest][Darkshore] A Lost Master)

### ISSUE THREAD

**Issue by ixnilatis** [Atlantiss/NetherwingBugtracker#7738]
[//]: # (Enclose links to things related to the bug using http://wowhead.com or any other TBC database.)
[//]: # (You can use screenshot ingame to visual the issue.)
[//]: # (Write your tickets according to the format:)
[//]: # ([Quest][Azuremyst Isle] Red Snapper - Very Tasty!)
[//]: # ([NPC] Magistrix Erona)
[//]: # ([Spell][Mage] Fireball)
[//]: # ([Npc][Drop] Ghostclaw Lynx)
[//]: # ([Web] Armory doesnt work)
[//]: # (To find server revision type `.server info` command in the game chat.)

**Description**: https://classic.wowhead.com/quest=986/a-lost-master

**Current behaviour**: Terenthis is supposed to give you this quest however on my Dranei hunter he isnt.

**Expected behaviour**: 

**Server Revision**:

**Comment by ixnilatis** [comment]
Terenthis is supposed to give you this quest however on my Dranei hunter he isnt.

**Comment by tsuone** [comment]
Deleted comment, updated the main issue.

**Comment by Wolffenstein** [comment]
It has no racial requirements, you need to finish "How Big a Threat?" Part 2 beforehand
