### ISSUE TITLE
[Spell][Priest] Mana stops regenerating for 1 minute after Using Mind Control.

### ISSUE THREAD

**Issue by Jezofine** [Atlantiss/NetherwingBugtracker#774]
**Current behaviour**:
Mana does not regenerate after breaking Mind Control channeling early. 
Mana potions or drinks restore mana but do not force regeneration until I use any other spell or after 1 minute from time of using MC (exact maximum duration).
Might also affect Tranquility and other spells with channeling time >5 sec.

**Expected behaviour**: 
Regeneration is interrupted during MC channeling, but after breaking it should regenerate as usual (5SR).

[From wikia 2008](http://wowwiki.wikia.com/wiki/Mana_regeneration?oldid=1585064#Five_Second_Rule):
"Channeled spells are handled a little differently. The FSR starts when the spell's channeling starts; i.e. when mana is expended. The interruption continues for at least five seconds, and longer if the channeled takes more than five seconds. For example, Mind Flay channels for 3 seconds and interrupts regeneration for 5 seconds (from the moment the spell cast starts), while Tranquility channels for 10 seconds and interrupts regeneration for the full 10 seconds, but not longer."

**Server Revision**: 2073

**Comment by Jezofine** [comment]
Rev 2371: mana regenerates even when channeling Mind Control.

**Comment by Wolffenstein** [comment]
Fixed in rev 2399.
