### ISSUE TITLE
[Event][Fishing Extravaganza] Ends too soon.

### ISSUE THREAD

**Issue by Bull3r** [Atlantiss/NetherwingBugtracker#7740]
[//]: # (Enclose links to things related to the bug using http://wowhead.com or any other TBC database.)
[//]: # (You can use screenshot ingame to visual the issue.)
[//]: # (Write your tickets according to the format:)
[//]: # ([Quest][Azuremyst Isle] Red Snapper - Very Tasty!)
[//]: # ([NPC] Magistrix Erona)
[//]: # ([Spell][Mage] Fireball)
[//]: # ([Npc][Drop] Ghostclaw Lynx)
[//]: # ([Web] Armory doesnt work)
[//]: # (To find server revision type `.server info` command in the game chat.)

**Description**: 
Fishing Extravaganza event in STV
**Current behaviour**:
Stopped at 3PM server time insted of the inteded 4PM
**Expected behaviour**: 
Should stop at 4PM server time
**Server Revision**:

**Comment by tsuone** [comment]
It starts earlier and ends earlier here as far as I remember. Worth finally changing.

**Comment by Tereneckla** [comment]
It's not exactly the Fishing Extravaganza that's wrong in that regard.
#4625
Server changes servertime with summer/winter time but not when any events happen
Time of daily reset also changes (in relation to the displayed servertime)

**Comment by Wolffenstein** [comment]
Fixed in rev 3787.
