### ISSUE TITLE
[NPC][Movement] Bladewing Bloodletter evades in the middle of combat

### ISSUE THREAD

**Issue by raethkcj** [Atlantiss/NetherwingBugtracker#7741]
**Description**: 
They randomly evade while fighting, likely because they're flying mobs. Happend to me 5 of them in a row, doesn't seem to matter where you stand.

**Current behaviour**:
https://streamable.com/4auhhs

**Server Revision**: 
3556

**Comment by raethkcj** [comment]
Phase Hunter in Netherstorm is doing the exact same thing. Constantly evading to full health.

**Comment by Wolffenstein** [comment]
Fixed in rev 3680.
