### ISSUE TITLE
[Patch 2.1] Specialization bs-crafted 1-handed weapons are not upgraded to 2.1 damage and stat values, yet the 2-handed bs-crafts are.

### ISSUE THREAD

**Issue by HerculePoirotTBC** [Atlantiss/NetherwingBugtracker#7744]
[//]: # (Enclose links to things related to the bug using http://wowhead.com or any other TBC database.)
[//]: # (You can use screenshot ingame to visual the issue.)
[//]: # (Write your tickets according to the format:)
[//]: # ([Quest][Azuremyst Isle] Red Snapper - Very Tasty!)
[//]: # ([NPC] Magistrix Erona)
[//]: # ([Spell][Mage] Fireball)
[//]: # ([Npc][Drop] Ghostclaw Lynx)
[//]: # ([Web] Armory doesnt work)
[//]: # (To find server revision type `.server info` command in the game chat.)

**Description**: 
On Karazhan Stormherald and other specialization BS-crafted 2-handers got their damage and stats upgraded by the 2.1 itemization patch as their DPS got bumped to 126.9-127. According to multiple archived sources the specialization BS-crafted 1-handers get bumped to 97.5-97.6 DPS at patch 2.1, but currently on Kara they still have the lower patch 2.0 damage values (and stats) with 95.0 DPS.

[A ticket was made (#7696)](https://github.com/Atlantiss/NetherwingBugtracker/issues/7696) about this on the tracker, however the links provided in the ticket were partially off and there might've been a slight misunderstanding:

The ticket creator was specifically referring to the damage and stat values of the 1-h weapons being off, he was not stating that the 1-h weapons lost their unique / main-hand status at this point (that is introduced in 2.4). It seems clear that the issue has not been resolved if Kara's 2.1 itemization patch was supposed to bump up the damage and stat values consistently the way the original patch 2.1 did. The original 2.1 patch bumped up the damage and stats of all the 1-h and 2-h specialization bs-crafted weapons.

The following is a comparison of the final tier (Nether Vortex) bs-crafted 1-h weapons on patch 2.0 and 2.1 archived versions of Thottbot, Allakhazam and Wowhead. The 1st and 2nd tier (Drakefist Hammer, Dragonmaw, Fireguard, Blazeguard etc.) items’ values were bumped by the original 2.1 patch too and they can be found on the following sites as well. They too currently have the 2.0 values on Kara. Stormherald is listed here for reference to prove the earlier point about Kara having proper values for the 2-h bs-crafts. Rest of the 2-h BS-crafts (Bloodmoon, Lionheart Executioner etc., all tiers of them) also have their values buffed to proper 2.1 values currently on Karazhan. The links to 2.0 items are from archives timestamped between February 2007 to before May 15th 2007 (original 2.1 release). The 2.1 item links are from between late May 2007 to July 2007 (well before the original release of patch 2.2):

--- Stormherald 2.0 (this is what we had before the 2.1 itemization patch on Kara)
http://web.archive.org/web/20070510210539/http://www.thottbot.com/i28442
https://web.archive.org/web/20070323140157/http://wow.allakhazam.com/item.html?witem=28442
http://web.archive.org/web/20070509040753/http://www.wowhead.com/?item=28442

--- Stormherald 2.1 (this is what we currently have on Kara, after the 2.1 itemization patch)
http://web.archive.org/web/20070605235501/http://www.thottbot.com/i28442
(on Allakhazam the item ID page isn’t archived near the 2.1 patch but the 2-h maces listing where the values can be seen is, ctrl+f for Stormherald):
https://web.archive.org/web/20070616194816/http://wow.allakhazam.com/dyn/items/wname5.html
http://web.archive.org/web/20070520111944/http://www.wowhead.com/?item=28442

--- Dragonstrike 2.0 (this is what we currently have on Kara, after the 2.1 itemization patch), 179-334dmg, 95 DPS +16 stamina
http://web.archive.org/web/20070406190404/http://thottbot.com/i28439
(ctrl+f for Dragonstrike):
https://web.archive.org/web/20070407095855/http://wow.allakhazam.com/dyn/items/wname4.html
https://web.archive.org/web/20070510000823/http://www.wowhead.com/?item=28439

--- Dragonstrike 2.1, 184-343dmg, 97.6 DPS, +19 stam
http://web.archive.org/web/20070704022359/http://thottbot.com/i28439
(ctrl+f for Dragonstrike):
https://web.archive.org/web/20070601233418/http://wow.allakhazam.com/dyn/items/wname4.html
https://web.archive.org/web/20070610204341/http://www.wowhead.com/?item=28439

--- Blazefury 2.0 (this is what we currently have on Kara, after the 2.1 itemization patch) 106-198dmg, 95 DPS, 18agi, 27stam
http://web.archive.org/web/20070406203513/http://www.thottbot.com/i28427
https://web.archive.org/web/20070427053047/http://wow.allakhazam.com/item.html?witem=28427
https://web.archive.org/web/20070407210804/http://www.wowhead.com/?item=28427

--- Blazefury 2.1, 109-203dmg, 97.5 DPS, 19agi, 28stam
http://web.archive.org/web/20070609150211/http://www.thottbot.com/i28427
(ctrl+f for Blazefury):
https://web.archive.org/web/20070601023101/http://wow.allakhazam.com/item.html?witem=28427
https://web.archive.org/web/20070611072157/http://www.wowhead.com/?item=28427

--- Wicked Edge of the Planes 2.0 (this is what we currently have on Kara, after the 2.1 itemization patch), 179-334dmg, 95 DPS, 22crit, 45AP
http://web.archive.org/web/20070407041215/http://www.thottbot.com/i28433
https://web.archive.org/web/20070311210400/http://wow.allakhazam.com/item.html?witem=28433
https://web.archive.org/web/20070222171003/http://www.wowhead.com/?item=28433

--- Wicked Edge of the Planes 2.1: 184-343dmg , 97.6 DPS, 23crit, 48AP
http://web.archive.org/web/20070705063439/http://www.thottbot.com/i28433
(ctrl+f for Wicked Edge):
https://web.archive.org/web/20070614012250/http://wow.allakhazam.com/dyn/items/wname0.html
https://web.archive.org/web/20070619043421/http://www.wowhead.com/?item=28433

**Current behaviour**:

The following specialization BS-crafted 1-handers still have 2.0 damage and stat values on Karazhan (ID, name):
28425, Fireguard
28426, Blazeguard
28427, Blazefury
28437, Drakefist Hammer 
28438, Dragonmaw
28439, Dragonstrike
28431, Planar Edge
28432, Black Planar Edge
28433, Wicked Edge of the Planes 

**Expected behaviour**: 
Both 1-handed and 2-handed specialization BS-crafted weapons having 2.1 damage and stat values.

**Server Revision**: 
3556

**Comment by recreantus** [comment]
Nice research. Good question, why should the 2-handers be better than 1-handers on the same patch?

**Comment by Wolffenstein** [comment]
It appears the 2.1 changes got grouped together with 2.3 changes, that's why the stats are wrong.

**Comment by HerculePoirotTBC** [comment]
@Wolffenstein thanks for the update.

Does this mean that the mentioned 1-h crafts will be updated to proper 2.1 stats soon or that they shall wait till 2.3? I find it odd that the 2.1 upgrades for 2-h crafts were selectively implemented earlier (or in other words were not grouped up with the 1-h changes of patch 2.3 you refer to).

**Comment by Wolffenstein** [comment]
Fixed in rev 3566.
