### ISSUE TITLE
Healing gear isn't showing the spell damage increase on character pane

### ISSUE THREAD

**Issue by lukskywaffle** [Atlantiss/NetherwingBugtracker#7745]
![healing:dmg numbers](https://user-images.githubusercontent.com/75092031/100382964-58d5a980-2fd1-11eb-8a4c-4890ee5874ee.jpg)

![no staff ](https://user-images.githubusercontent.com/75092031/100383298-24aeb880-2fd2-11eb-810c-968b77c6b769.jpg)

**Description**: All  my healing gear also is supposed to increase my spell damage, but in the character pane, its only showing the +healing. My shoulders are the only piece of gear that is increases damage and healing which is why it shows +35 bonus damage. First picture is with all my gear on. Second is with my staff removed. As you can see, the +healing goes down but the spell damage stays the same. I played on Netherwing server and never had this problem. 

I did try clearing the cache and turning off all add-ons. This didn't fix the problem.

**Current behaviour**:Healing gear incorrectly not showing the spell damage info on character pane.

**Expected behaviour**: Healing gear says it increases your spell damage by a small amount and this should be reflected in the character pane accurately.

**Server Revision**: Atlantiss Karazhan / 2.0.3 / 3556

**Comment by Wolffenstein** [comment]
Spell changes were not affected by the prepatch, it will be fixed next week when 2.1 is fully active.
