### ISSUE TITLE
Buffs Not Stacking Issue/Bug

### ISSUE THREAD

**Issue by Jedibot1** [Atlantiss/NetherwingBugtracker#7747]
[//]: # (Enclose links to things related to the bug using http://wowhead.com or any other TBC database.)
[//]: # (You can use screenshot ingame to visual the issue.)
[//]: # (Write your tickets according to the format:)
[//]: # ([Quest][Azuremyst Isle] Red Snapper - Very Tasty!)
[//]: # ([NPC] Magistrix Erona)
[//]: # ([Spell][Mage] Fireball)
[//]: # ([Npc][Drop] Ghostclaw Lynx)
[//]: # ([Web] Armory doesnt work)
[//]: # (To find server revision type `.server info` command in the game chat.)

**Description**: 

Hello, I have noticed that the buffs from food that should stack do not stack and also override one another when this should not be the case. 

The Buffs that I have currently tested are the following.

 Poached Sunscale Salmon = 6Hp per 5sec
 Grilled Squid = 10 Agility Buff
 Ravager Egg Omelet = 10 Stamina Buff
 Well Fed

I will continue to check the others when I am able to gather them up and test them. These buffs are meant to stack and do so on many other servers and on classic retail.

**Current behaviour**:

All these buffs should stack together however they override each other which should not be the case.

**Expected behaviour**: 

Each of these buffs are meant to stack with each other and provide the buff in the description.
Note: buffs that give the same buff below that are not listed next to each other with a forwards slash "/" are not meant to stack and simple override the other listed.
Buffs that should stack are:

10 Agility from Grilled Squid
10 Stamina from Ravager Egg Omelet/ Cooked Glossy Mightfish/ Dried Fruit Rations
10 Spirit from Hot Smoked Bass/ Blessed Sunfruit Juice
10 Intellect from Runn Tum Tuber Surprise
10 Strength from Blessed Sunfruit
20 Spell Critical Rate and 20 Spirit from Skullfish Soup
8 Mana Per 5 Seconds from Nightfin Soup
6 Health Per 5 Seconds from Poached Sunscale Salmon
Fire breathe on proc from Dragonbreath Chili
Lighting Zaps around players from Stormchops
15 Stamina from Rumsey Rum Black Label however overrided by Rumsey Rum Dark/Rumsey Rum Light
10 Stamina from Rumsey Rum Dark however overrided by Rumsey Rum Black Label/Rumsey Rum Light
5 Stamina from Rumsey Rum Light, however overrided by Rumsey Rum Dark/ Rumsey Rum Black Label
14 Spell Damage and Healing from Juicy Bear Burger
Well Fed from all foods that provide it

**Server Revision**: 
Content Patch: 2.0.3 Revision: 3556

**Comment by tsuone** [comment]
@Jedibot1 Source

**Comment by Godmatik** [comment]
![gfhgfhfgh](https://github.com/user-attachments/assets/2c757129-50d4-4de6-86b0-c8551c792132)

Based on my research and checking wowhead comments from various foods - the original post is incorrect.
You can only have one food buff up at one time.
