### ISSUE TITLE
Spell damage from items is not applied correctly

### ISSUE THREAD

**Issue by Eithnee** [Atlantiss/NetherwingBugtracker#7748]
**Description**: Spell damage is not applied correctly to my character. It happened after respec. In the image you can see that from one item only it is 39, not to mention the whole gear which should total to 405 spell damage.
![image](https://user-images.githubusercontent.com/75165381/100514531-d20e0180-3175-11eb-95e8-1c528a2bc676.png)

**Current behaviour**: Spell damage from items is not applied correctly.

**Expected behaviour**: Spell damage from items is applied correctly.

**Server Revision**: 3556

**Comment by Godmatik** [comment]
This has been mentioned about 100 times now...

Spell damage from healing items does not get added until patch 2.3

If you want the items to be shown proper without the healing numbers, then install the following add-on:
https://github.com/nullfoxh/NWTooltipFix/archive/master.zip

**Comment by tsuone** [comment]
Closing
