### ISSUE TITLE
Cannot link items (Shift+Click) I don't own in chat

### ISSUE THREAD

**Issue by UncleSweaty** [Atlantiss/NetherwingBugtracker#7749]
[//]: # (Enclose links to things related to the bug using http://wowhead.com or any other TBC database.)
[//]: # (You can use screenshot ingame to visual the issue.)
[//]: # (Write your tickets according to the format:)
[//]: # ([Quest][Azuremyst Isle] Red Snapper - Very Tasty!)
[//]: # ([NPC] Magistrix Erona)
[//]: # ([Spell][Mage] Fireball)
[//]: # ([Npc][Drop] Ghostclaw Lynx)
[//]: # ([Web] Armory doesnt work)
[//]: # (To find server revision type `.server info` command in the game chat.)

**Description**: 
I've got a really weird issue where I can't link items (Shift+Click) I don't own in chat, for instance when playing as Master Looter. I just get a weird warning instead, saying: "You can't send message with colored font". Thought it was an addon causing this but disabled all addons this morning, tried to link an item from auction house in chat and still wasn't working. This wasn't really an issue for me until I started becoming Master Looter. I think this issue started around when the server switched the item stats to their 2.1 version, and after I deleted my Cache folder (as instructed to).
![image](https://user-images.githubusercontent.com/28244401/100517253-36828e00-3181-11eb-9ea4-30a6c59de91d.png)
**Current behaviour**:
Can link every item in my bags, bank, guild bank, equipped, from own profession books Can link spells from Spellbook. Cannot link everything else with a rarity of Uncommon or above.
**Expected behaviour**: 
Able to link all items in chat, regardless of ownership. Able to link dropped items in raid or party chat when set as MasterLooter.
**Server Revision**: 
Karazhan - 28/11/2020

**Comment by Godmatik** [comment]
If you don't put any text in front of the linked item, it will work

**Comment by UncleSweaty** [comment]
From my testing I never pit any text in front, or behind, or any text other than an item for that matter.
