### ISSUE TITLE
NPC [Stonetusk Boar] Elwynn Forest.

### ISSUE THREAD

**Issue by EsionaEU** [Atlantiss/NetherwingBugtracker#775]
[//]: # (Enclose links to things related to the bug using http://wowhead.com or any other TBC database.)
[//]: # (You can use screenshot ingame to visual the issue.)
[//]: # (Write your tickets according to the format:)
[//]: # ([Quest][Azuremyst Isle] Red Snapper - Very Tasty!)
[//]: # ([NPC] Magistrix Erona)
[//]: # ([Spell][Mage] Fireball)
[//]: # ([Npc][Drop] Ghostclaw Lynx)
[//]: # ([Web] Armory doesnt work)

**Description**: 
Several Boars targetable as expected, however will not allow interaction via spell or melee combat initiation.
**Current behaviour**:

**Expected behaviour**: 

**Server Revision**:

**Comment by tcberk12** [comment]
Can you post some sort of video or screenshot to show the issue?

**Comment by Easyfraggy** [comment]
Duplicate https://github.com/Atlantiss/NetherwingBugtracker/issues/262
