### ISSUE TITLE
[Core] Breath Bar without water (one spot)

### ISSUE THREAD

**Issue by iguessineedhelp** [Atlantiss/NetherwingBugtracker#7751]
Showing the breath meter and you'll able to die from it

https://imgur.com/a/1jrbxj2 <- showing the breath meter
https://imgur.com/a/s5OYZXp <- prove that'll be able to die from it

**Server Revision**: 
3559

**Comment by tsuone** [comment]
@Wolffenstein @danbopes

**Comment by danbopes** [comment]
@Bastek I believe this is an map issue.

**Comment by Godmatik** [comment]
Duplicate #2555
