### ISSUE TITLE
[Error][132] Guardian of the Falcon

### ISSUE THREAD

**Issue by Godmatik** [Atlantiss/NetherwingBugtracker#7752]
Guardian of the Falcon is giving Error 132s when you engage him for the quest "The Falcon's Essence"

Other druids are telling me they having similar issues.

EDIT: Forgot to mention, not an add-on issue, disabled all of them on 3rd attempt, same result.

**Comment by Godmatik** [comment]
I think it is when he does his Nether Vortex ability, was finally able to kill it when he didn't use that skill.

**Comment by CptMarkka** [comment]
Can confirm, Nether Vortex causes a Divide by Zero error and crashed the game. Tried the encounter twice, and both times the game crashed in the same exact manner when Nether Vortex was cast by the Guardian of the Falcon.

![DivideByZero](https://user-images.githubusercontent.com/43807621/101035068-52bc6b80-3583-11eb-80d7-f4c9fb03b418.PNG)

[Stacktrace.txt](https://github.com/Atlantiss/NetherwingBugtracker/files/5636647/Stacktrace.txt)

**Comment by bidaumm** [comment]
Can also confirm - just happened to me

**Comment by Wolffenstein** [comment]
Fixed in rev 3563.
