### ISSUE TITLE
[Quest][Blade's Edge Mountains] Into the Soulgrinder

### ISSUE THREAD

**Issue by MecAtlantiss** [Atlantiss/NetherwingBugtracker#7753]
[//]: # (Enclose links to things related to the bug using http://wowhead.com or any other TBC database.)
[//]: # (You can use screenshot ingame to visual the issue.)
[//]: # (Write your tickets according to the format:)
[//]: # ([Quest][Azuremyst Isle] Red Snapper - Very Tasty!)
[//]: # ([NPC] Magistrix Erona)
[//]: # ([Spell][Mage] Fireball)
[//]: # ([Npc][Drop] Ghostclaw Lynx)
[//]: # ([Web] Armory doesnt work)
[//]: # (To find server revision type `.server info` command in the game chat.)

**Description**: The soul that you need to loot from after killing Skulloc is not behaving correctly. 

**Current behaviour**: After killing Skulloc, the soul that spawns appears to be limited so that only 5 people can loot it before it despawns. Since 2.1 just came out, there's tons of people hanging around this quest area sniping the loot. And the event to spawn Skulloc takes so long that it's going to get worse and worse with people piling up to try to loot this thing.

**Expected behaviour**: The soul should stay spawned for some fixed amount of time and have unlimited stock. That's it works for the 4 prior quests in this chain...

**Comment by Wolffenstein** [comment]
Fixed in rev 3560.
