### ISSUE TITLE
[Spell][Warlock][MAJOR BUG] Nether Protection

### ISSUE THREAD

**Issue by sprawlpane** [Atlantiss/NetherwingBugtracker#7756]
[//]: # (Enclose links to things related to the bug using http://wowhead.com or any other TBC database.)
[//]: # (You can use screenshot ingame to visual the issue.)
[//]: # (Write your tickets according to the format:)
[//]: # ([Quest][Azuremyst Isle] Red Snapper - Very Tasty!)
[//]: # ([NPC] Magistrix Erona)
[//]: # ([Spell][Mage] Fireball)
[//]: # ([Npc][Drop] Ghostclaw Lynx)
[//]: # ([Web] Armory doesnt work)
[//]: # (To find server revision type `.server info` command in the game chat.)

**Description**: Warlock Destruction Talent Nether Protection is not functioning properly in a VERY big way. Currently it only procs off of direct damage shadow and fire spells, IE Shadowbolt, Fireblast, Pyroblast etc, and does not proc off enemy Rain of Fire nor players own Hellfire. Functioning properly it can proc off application of any shadow/fire spell, damaging or not. This SERVERELY cripples not only Nether Protection but also the Destruction spec as a whole, most notably in PvP.

https://tbc-twinhead.twinstar.cz/?spell=30302  the talent

**Current behaviour**: As said above, it only procs off DIRECT DAMAGE shadow/fire spells.
So I exclusively play Destruction with 3/3 Nether Protection (After being hit with a Shadow or Fire spell, you have a 30% chance to become immune to Shadow and Fire spells for 4sec.) and I pretty much only pvp, and do it very often. I run into many warlocks and shadowpriests that dot me up and I have never gotten a proc unless direct damaged, non-dot, IE sbolt/pyroblast. 

Here is a stream VOD showing it procs off direct damage (shadowbolt, immolate, searing pain) but does NOT proc off being "hit" by other shadow spells such as Corruption, Curse of Elements and Agony, and even the application of Drain Life.

https://www.twitch.tv/videos/824179150

this is 12/3/2020, 2.1 patch, karazhan server

--

**Expected behaviour**: Nether Protection is supposed to proc off of the application of any shadow/fire spell, not only damage, including Shadow Priest Silence, Felhunter Counterspell, applying of Curses and the application of things such as Corruption, Shadow Word: Pain, and Siphon Life, among others. 

PROOF:
This initially started when players stated in original tbc/on other servers Nether Protection procs off the application of mostly any shadow/fire spell, not just direct damaging ones. Proof was then found swiftly.

This Video at timestamps:
1:49, shadow priest proc's the warlocks nether protection with a silence
8:08, shadow priest proc's the warlocks nether protection with a silence
9:25 warlock felhunter counterspell (shadow spell) procs nether protection on the other warlock (if you think it is shadowburn, watch at half speed)
14:13 enemy warlock fear onto the warlock with nether protection procs nether protection
14:18 enemy warlock siphon life application on the warlock with nether protection procs nether protection

: https://www.youtube.com/watch?v=kDbmRr6PsNA

Video 2 timestamps:
2:20, priest shadow word: pain procs nether protection

**Server Revision**: 3560

**Comment by Wolffenstein** [comment]
Fixed in rev 3564.
