### ISSUE TITLE
[Spell] Bloodscalp Shaman's Fire Nova spell is instant instead of 2 sec cast.

### ISSUE THREAD

**Issue by Jezofine** [Atlantiss/NetherwingBugtracker#776]
**Current behaviour**:
[Bloodscalp Shaman's abilities]9https://www.wowhead.com/npc=697/bloodscalp-shaman#abilities), looks like this NPC was not replaced after Cata.
He uses [Fire Nova](https://www.wowhead.com/spell=11969/fire-nova) as instant spell.

**Expected behaviour**:
Fire Nova should have 2 sec cast time.

**Server Revision**: 2073

**Comment by Wolffenstein** [comment]
The ability could have changed though. Could you try going through Joana's STV vids and checking it?

**Comment by Easyfraggy** [comment]
https://youtu.be/Ufb0OmKT3Qk?t=13m31s

no cast time
