### ISSUE TITLE
[Quest][Terokkar Forest] Adversarial blood

### ISSUE THREAD

**Issue by Warlocket** [Atlantiss/NetherwingBugtracker#7760]
[//]: # (Enclose links to things related to the bug using http://wowhead.com or any other TBC database.)
[//]: # (You can use screenshot ingame to visual the issue.)
[//]: # (Write your tickets according to the format:)
[//]: # ([Quest][Azuremyst Isle] Red Snapper - Very Tasty!)
[//]: # ([NPC] Magistrix Erona)
[//]: # ([Spell][Mage] Fireball)
[//]: # ([Npc][Drop] Ghostclaw Lynx)
[//]: # ([Web] Armory doesnt work)
[//]: # (To find server revision type `.server info` command in the game chat.)

**Description**:  I tried this quest twice now, abandoned and pick it up again; with two different groups the quest object skull pile is bugged. I followed all the suggested instructions each time: at least 10 Time-Lost Scrolls and used the elixir of shadows, then I click the skull pile at the summoning circles and instead being able to summon the specific mobs needed for the quest. It reads: "The pile of skulls reeks of foulness. You fear the arakkoa have made an addition to the pile fairly recently." 

**Current behaviour**: 

**Expected behaviour**: 

**Server Revision**:

**Comment by Godmatik** [comment]
Confirmed

**Comment by EmileQL2P** [comment]
Confirmed

**Comment by Godmatik** [comment]
I informed Wolf and he fixed it - but won't be updated until tomorrow when server restarts, and you will need to delete cache folder
