### ISSUE TITLE
Meta Gem - Mystical Skyfire Diamond

### ISSUE THREAD

**Issue by m17a4y** [Atlantiss/NetherwingBugtracker#7761]
[//]: # (Enclose links to things related to the bug using http://wowhead.com or any other TBC database.)
[//]: # (You can use screenshot ingame to visual the issue.)
[//]: # (Write your tickets according to the format:)
[//]: # ([Quest][Azuremyst Isle] Red Snapper - Very Tasty!)
[//]: # ([NPC] Magistrix Erona)
[//]: # ([Spell][Mage] Fireball)
[//]: # ([Npc][Drop] Ghostclaw Lynx)
[//]: # ([Web] Armory doesnt work)
[//]: # (To find server revision type `.server info` command in the game chat.)

**Description**: Mystical Skyfire Diamond is a meta gem with a 15% chance to grant 6 seconds of 320 Spell Haste Rating, with a 45 second internal cooldown. The buff given is called focus. The gem can proc off instant casts, but they will not consume focus. - From Wowwiki https://wowwiki.fandom.com/wiki/Mystical_Skyfire_Diamond

**Current behaviour**: The buff looks like to be pre nerfed to 4sec duration at current patch 2.1

**Expected behaviour**: A buff which lasts for 6 sec during 2.1 - 2.4 patch

**Server Revision**: 3563

**Comment by Tereneckla** [comment]
https://github.com/Atlantiss/NetherwingBugtracker/issues/6224#issuecomment-555248680
