### ISSUE TITLE
[Quest] The Hawk's Essence - NPC doesn't take extra damage from Spells.

### ISSUE THREAD

**Issue by bidaumm** [Atlantiss/NetherwingBugtracker#7762]
The Guardian of the Hawk is supposed to take increased damage from spells - however it currently doesnt.

https://www.wowhead.com/quest=10992/the-hawks-essence

By jef3189 (812 – 2·4) on 2007/05/23 (Patch 2.1.0)
"DO NOT attempt to use melee combat, and take advantage of barksin. Preempt your roots to make sure that he doesnt come within melee range, and use your wrath/moonfire to burn him down as quickly as possible. They do almost 400% damage (all your druid spells)."

https://wowwiki.fandom.com/wiki/Quest:The_Hawk%27s_Essence#Notes

This guardian take enormous amounts of damage from magic, and if your casting criticals, it does even more. A report of Roots doing 300 damage every 3 seconds, Wrath doing 2650, Moonfire doing 1850, and Starfire doing 4200 may well understate the case. Recent experience, with moderate-good casting gear, had Starfire doing 10-12k per strike. This makes the fight fairly short despite his having some 50k HP.

**Server Revision**: 
Atlantiss Karazhan | Content patch: 2.1.0 | Revision: 3560

**Comment by Wolffenstein** [comment]
Fixed in rev 3576.
