### ISSUE TITLE
[NPC] Kiggler the Crazed (Shaman) - High King Maulgar Fight.

### ISSUE THREAD

**Issue by bidaumm** [Atlantiss/NetherwingBugtracker#7764]
Currently if Kiggler ever has agro on a target outside of his cast range, he will run all the way up to that target and attempt to do at least 2 melee attacks before resuming his casting. His melee attacks currently one shot both a boomkin and hunter with 10k HP and are impossible to tank through. 

If this is intended behavior by Atlantiss I believe should either have his melee attack damage reduced enough to avoid one/two-shots on non tanks in melee to allow repositioning. 
Or if this is not he should be adjusted to resume casting spells once he returns to casting range on a target and only melee once in melee range.

**Server Revision**: 
Atlantiss Karazhan | Content patch: 2.1.0 | Revision: 3560

**Comment by Godmatik** [comment]
Confirmed, have noticed similar behavior.
