### ISSUE TITLE
[Quest][NPC] Sethhek Halls HC Anzu Boss Fight - Spirits not receiving hots

### ISSUE THREAD

**Issue by bidaumm** [Atlantiss/NetherwingBugtracker#7765]
The 3 Bird Spirits around Anzu that are supposed to be activated by a druid heal over time and stay alive for the length of the spell are not currently receiving the HoT buff, and therefore are deactivating quickly after coming alive.

I have tested this with Regrowth/Rejuvenation/Lifebloom

**Server Revision**: 
Atlantiss Karazhan | Content patch: 2.1.0 | Revision: 3560

**Comment by Godmatik** [comment]
Worked fine for me both times I did the fight, and all 3 were active and giving their buffs (while rejuv was on them).

**Comment by Wolffenstein** [comment]
They activate for a set amount of time, it does not depend on the length of the spell.
