### ISSUE TITLE
[Quest][Teldrassil] The Sprouted Fronds

### ISSUE THREAD

**Issue by netbean2** [Atlantiss/NetherwingBugtracker#7766]
[//]: # (Enclose links to things related to the bug using http://wowhead.com or any other TBC database.)
[//]: # (You can use screenshot ingame to visual the issue.)
[//]: # (Write your tickets according to the format:)
[//]: # ([Quest][Azuremyst Isle] Red Snapper - Very Tasty!)
[//]: # ([NPC] Magistrix Erona)
[//]: # ([Spell][Mage] Fireball)
[//]: # ([Npc][Drop] Ghostclaw Lynx)
[//]: # ([Web] Armory doesnt work)
[//]: # (To find server revision type `.server info` command in the game chat.)

**Description**: The quest giver for this quest (https://tbc-twinhead.twinstar.cz/?quest=2399) which is https://tbc-twinhead.twinstar.cz/?object=7510 despawns very quickly after spawning after you complete the prequest : https://tbc-twinhead.twinstar.cz/?quest=931 which does not give you the time to take the quest at all. Once it despawns it will never spawn again unless some other player finishes again the prequest and gives the npc the time to play the even and spawn the object quest giver again.

**Current behaviour**: https://tbc-twinhead.twinstar.cz/?object=7510 despawns very quickly (10s max max)

**Expected behaviour**:  https://tbc-twinhead.twinstar.cz/?object=7510 despawns very quickly should not despawn that fast (i dont know how many secs/mins it should be there) . I wanna say again that once it despawns i cannot get this quest anymore, unless another player finishes the prequest again.

**Server Revision**: 3560

**Comment by danbopes** [comment]
Updated it to 60 seconds, up from 20. Rev 3601
