### ISSUE TITLE
Seer Omul despawns too quickly in SSC

### ISSUE THREAD

**Issue by Godmatik** [Atlantiss/NetherwingBugtracker#7767]
Seer Omul, who gives the quest "The Secret Compound" in SSC after you kill FLK, despawns after only a certain amount of minutes.

Per wowhead comments, he should instead only despawn after a soft reset.

https://www.wowhead.com/quest=10944/the-secret-compromised
https://www.wowhead.com/npc=22820/seer-olum#comments

**Comment by Wolffenstein** [comment]
wrong

**Comment by Godmatik** [comment]
Wowhead comments from 2.1 mention that he should despawn either after a soft reset or 1 hour
