### ISSUE TITLE
Unholy Enchant doesn't have its animation

### ISSUE THREAD

**Issue by radioslave** [Atlantiss/NetherwingBugtracker#7769]
[//]: # (Enclose links to things related to the bug using http://wowhead.com or any other TBC database.)
https://classic.wowhead.com/spell=20033/enchant-weapon-unholy-weapon

**Description**: 
Pretty straight forward - the Unholy enchant should have a swirly animation, it doesn't

**Current behaviour**:
No swirly green animation

**Expected behaviour**: 
swirly green animation

**Comment by Tereneckla** [comment]
Various weapons have an enchant effect already. That makes them not show effects like unholy weapon
