### ISSUE TITLE
[Gnomeregan] Missing Patrol in the Crowd Pummeler 9-60 Area

### ISSUE THREAD

**Issue by Azalen** [Atlantiss/NetherwingBugtracker#777]
**Current behaviour**:
Patrols in the Crowd Pummeler 9-60 area are missing/not working

**Expected behaviour**: 
https://youtu.be/2CEwXWxhW-8?t=2m56s shows two of those patrols. There should be patrols between all the major camps/rooms. The mobs patrolling should be "Mechano-Flamewalker" and/or "Mechano-Frostwalker".

There are probably more patrols missing but those I remember because they did hurt.

**Server Revision**: 
[2067]

**Comment by aresbrutus** [comment]
These missing patrols will be added in the next update. If you find any more missing, please make a new report and it will get added.
