### ISSUE TITLE
rogue  stats  %  crit chance

### ISSUE THREAD

**Issue by fulerst34** [Atlantiss/NetherwingBugtracker#7773]
**Description**: 
rogue  stats  %  crit chance    working  wrong  ,  when i get  25-30 %  crit    i have every  white attack critical dmg
if  you  get less  25%    no  one  critical  white attack  hit    ,    how it  can be  
i  dont  this in any  server  

**Current behaviour**:
shouldn't have some cap  

because of this in pvp  build  Sub.   rogue  have  more  dps in  pve      how  it  can be  ???
**Expected behaviour**: 
critical chance  need  to  be randomly  ,  
shouldn't have some cap 
**Server Revision**:

**Comment by Godmatik** [comment]
no idea what you talking about... got any logs that show proof?
