### ISSUE TITLE
Quest "Digging Through Bones"

### ISSUE THREAD

**Issue by Godmatik** [Atlantiss/NetherwingBugtracker#7774]
When you arrive at the site with the dwarves, the drum is already visible, but shouldn't be until they "dig it up"

![WoWScrnShot_120820_120721](https://user-images.githubusercontent.com/37913400/101523292-063faa00-394e-11eb-885c-4d3d2b7f1260.jpg)

**Comment by Wolffenstein** [comment]
Someone might have not looted it.

**Comment by Godmatik** [comment]
It's a game object part of the RP of the quest, not something you loot
