### ISSUE TITLE
Karazhan Realm: Shartuul event bug

### ISSUE THREAD

**Issue by Yevhen-Shcherbak** [Atlantiss/NetherwingBugtracker#7776]
Shartuul event bug

When Eye of Shartuul casts his ray and i turn into ice aspect and do the Ice block spell- Eye targets my character instead and as a result- no dmg from reflecting the ray

Eye must traget a demon i control, not my character

**Server Revision**:

**Comment by Godmatik** [comment]
Closing - consolidating all information into one thread
