### ISSUE TITLE
[Talent][Priest] Shadow Weaving

### ISSUE THREAD

**Issue by Queck32** [Atlantiss/NetherwingBugtracker#7777]
[//]: # (Enclose links to things related to the bug using http://wowhead.com or any other TBC database.)
[//]: # (You can use screenshot ingame to visual the issue.)
[//]: # (Write your tickets according to the format:)
[//]: # ([Quest][Azuremyst Isle] Red Snapper - Very Tasty!)
[//]: # ([NPC] Magistrix Erona)
[//]: # ([Spell][Mage] Fireball)
[//]: # ([Npc][Drop] Ghostclaw Lynx)
[//]: # ([Web] Armory doesnt work)
[//]: # (To find server revision type `.server info` command in the game chat.)

**Description**: 
**Shadow Weaving** (https://tbc-twinhead.twinstar.cz/?spell=15334) does not have a separate resist chance as it should.

**Current behaviour**:
Shadow Weaving Is always applied (if 5/5 in talent points) if the first spell (shadow damage base) hits /isnt resisted. 

**Expected behaviour**: 
In the same way that a mages Winters Chill (https://tbc-twinhead.twinstar.cz/?spell=28595 or bug report that was rejected: https://github.com/Atlantiss/NetherwingBugtracker/issues/4405) has a separate chance to be resisted even if the spell that applies the debuff hits. 

_(I am unsure if its the same case with misery talent (https://tbc-twinhead.twinstar.cz/?spell=33195)  (spell that also cannot be resisted by itself and always hits if the spell accomodating it hits) as the wording on the talent is different but it might be the same thing)_

The shadow weaving debuff should be coded in the same way, so that shadow priests can benefit from items such as Eye of Maghteridon (https://www.wowhead.com/item=28789/eye-of-magtheridon#comments) properly and for balancing reasons.

**Server Revision**: 3567

**Comment by Wolffenstein** [comment]
Fixed in rev 3576.
