### ISSUE TITLE
[Mount Hyjal] Infernos may not spawn - Anetheron

### ISSUE THREAD

**Issue by Godmatik** [Atlantiss/NetherwingBugtracker#7779]
If Anetheron targets a player with inferno who has the ability to get out of combat (hunter feign death, rogue vanish), then you can use that ability, and the inferno won't spawn.

**Comment by Godmatik** [comment]
Divine Intervention on the targeted player also works.

**Comment by Tereneckla** [comment]
Those spells drop being targeted. Unless you have definitive proof that Inferno should be an exception to the rule it is intended.

**Comment by Godmatik** [comment]
Works on classic, so probably intended, closing
