### ISSUE TITLE
Kodo Round up desolace not working 

### ISSUE THREAD

**Issue by ThriceFilter** [Atlantiss/NetherwingBugtracker#778]
[//]: # (Enclose links to things related to the bug using http://wowhead.com or any other TBC database.)
[//]: # (You can use screenshot ingame to visual the issue.)
[//]: # (Write your tickets according to the format:)
[//]: # ([Quest][Azuremyst Isle] Red Snapper - Very Tasty!)
[//]: # ([NPC] Magistrix Erona)
[//]: # ([Spell][Mage] Fireball)
[//]: # ([Npc][Drop] Ghostclaw Lynx)
[//]: # ([Web] Armory doesnt work)
#([quest][Desolace] Kodo Round Up)
**Description**: 
The quest Kodo Round up is not working, the quest item is failing to transform the kodo and have them follow me

**Current behaviour**:
(https://youtu.be/Rz5nhX4lAUo)

**Expected behaviour**: 

**Server Revision**:

**Comment by Jezofine** [comment]
Duplicate #371
