### ISSUE TITLE
[NPC] Eye of Shartuul

### ISSUE THREAD

**Issue by totaemoeggerli** [Atlantiss/NetherwingBugtracker#7780]
**Current behaviour**:
[Eye of Shartuul](https://www.wowhead.com/npc=23228/eye-of-shartuul) uses Dark Glare too often and the damage can not be reflected by [Shivan Assassin](https://www.wowhead.com/npc=23220/shivarra-assassin)'s [Ice Block](https://www.wowhead.com/spell=41590/ice-block)

10.12.2020 Atlantis Karazhan
https://youtu.be/Dw-vyz4_Yjg
eye spawns: 0:00
dark glare 1: 0:15
dark glare 2: 0:48
dark glare 3: 1:20
dark glare 4: 1:53
dark glare 5: 2:27

Short clip of Dark Glare not being reflected: https://imgur.com/qBNz5Wm

**Expected behaviour**: 

20.10.2008 Retail TBC
https://youtu.be/I8FlaFkfahc 

eye spawns: 5:30
dark glare: 6:30
The mob dies before it can cast it again.

**Server Revision**: 
3567

**Comment by Godmatik** [comment]
Closing - consolidating all information into one thread
