### ISSUE TITLE
Loot system bugged

### ISSUE THREAD

**Issue by Lightspell** [Atlantiss/NetherwingBugtracker#7782]
![WoW_loot issue](https://user-images.githubusercontent.com/75849455/101923311-87f23a80-3bcf-11eb-985b-c217a23d07e0.jpg)

**Description**:  Loot System is bugged.

**Current behaviour**: In the dungeons cant some people "need" Items they really need.
The system automatically pass on these items. I met this issue in Shadowfang Keep and Sethek Halls N with two different charakter in the last 2-3 days. I had enough free bag space.
Its very sadly, because the drop chances for Items I need arent high. If they dropp, I loose them because this loot bug.

Thank you!

**Comment by Lightspell** [comment]
![WoW_loot issue](https://user-images.githubusercontent.com/75849455/101923238-727d1080-3bcf-11eb-9117-10a0befa90a4.jpg)

**Comment by Wolffenstein** [comment]
Disable auto-passing on loot for your character.
