### ISSUE TITLE
[Spell][Mage] Water Elemental not immune to hunter Freezing Trap

### ISSUE THREAD

**Issue by balsh** [Atlantiss/NetherwingBugtracker#7783]
**Description**: 

**Current behaviour**: The Water Elemental can be CCd by Freezing Trap.

**Expected behaviour**: I can't prove it, can't find any reference but I'm pretty sure Water Elemental was immune to all things frost including Freezing Trap, eating the trap without getting the debuff.

**Comment by tsuone** [comment]
Water Elemental should be immune to Frost and Poison effects.

**Comment by Wolffenstein** [comment]
Fixed in rev 3591.
