### ISSUE TITLE
[NPC]Shartuul's Transporter event

### ISSUE THREAD

**Issue by EzioAu** [Atlantiss/NetherwingBugtracker#7786]
**Description**: 

**Current behaviour**:
1. character stats have an impact on demon's melee attack and skills
   for example:if u equip a weapon with low weapon skill ,most of their skill and attacks will be parried/missed/dodged and u can even level ur weapons kills while u controls the demons 

2.mob behaviors
https://wow.gamepedia.com/Shartuul%27s_Transporter_(event)
according to the link ,dreadmaw has 2 skills 

1>Growth: Increases damage and size by 15%. Permanent and stacks.
2>Rampaging Charge: Charges at an enemy applying a large DoT and slowing their speed.

Rampaging charge applys a dot on u which slows down your movement speed  and u can dispell it with Cleansing Flame,but i cant see the dot on the minion i control ,so im not sure its dispelled correctly ,but i think its not because:
according to the stratedy ,as long as u are in flame form ,u can easily kite Dreadmaw without getting too much damage ,but on karazhan server ,Dreadmaw moves faster and faster and in the end u'll be unable to kite it and fail the event.

not sure if growth or rampaging charge boosts his movement speed periodically or he moves faster and faster because player cant dispell the dot properly

**Expected behaviour**: 
the video shows how the fight should be:

https://youtu.be/zQE-mXFx6n0?t=424

**Server Revision**: 
3571

**Comment by Shineslippers** [comment]
Up! 2024 is already here...

Phase 2
[Gan'arg Underling](https://www.wowhead.com/tbc/npc=23199/ganarg-underling#comments) has tendency to evade after spawn. Player can cast stun on it or just run out and they will return to spawn spot.

Phase 4
[Dreadmaw](https://www.wowhead.com/tbc/npc=23275/dreadmaw) always outrun a player. More stack he is getting - faster running. You just can't keep him on distance. On top of it after charge he is no apply [Lacerating Bite](https://www.wowhead.com/tbc/spell=41940/lacerating-bite)

Other
[Shivan Assassin](https://www.wowhead.com/tbc/npc=23220/shivan-assassin) spell [Death Blast](https://www.wowhead.com/tbc/spell=40736/death-blast) doesn't work properly. It's convert only initial damage into healing. Doesn't matter how long debuff is active on target healing always the same.
I don't know is it correct or not but seems very odd that a player can cast abilities on all of those demons. You can Fear it, apply Curse of Tongues and other debuffs. That makes whole event itrrelevant.

**Comment by Godmatik** [comment]
Closing - consolidating all information into one thread
