### ISSUE TITLE
[Warlock][Spell] Curse of Elements duration in PvP

### ISSUE THREAD

**Issue by tsuone** [Atlantiss/NetherwingBugtracker#7788]
[//]: # (Enclose links to things related to the bug using http://wowhead.com or any other TBC database.)
[//]: # (You can use screenshot ingame to visual the issue.)
[//]: # (Write your tickets according to the format:)
[//]: # ([Quest][Azuremyst Isle] Red Snapper - Very Tasty!)
[//]: # ([NPC] Magistrix Erona)
[//]: # ([Spell][Mage] Fireball)
[//]: # ([Npc][Drop] Ghostclaw Lynx)
[//]: # ([Web] Armory doesnt work)
[//]: # (To find server revision type `.server info` command in the game chat.)
Same as: https://github.com/tsuone/pvp/issues/83

**Description**: Curse of Elements

**Current behaviour**: Curse of Elements debuff duration in PvP is 5 minutes.

**Expected behaviour**: The duration of the debuff should be 2 minutes when used on PvP targets.

>Patch 2.1.0 (22-May-2007): Curse of the Elements and Curse of Shadow now have a duration of 2 minutes when used on PvP targets.

**Server Revision**: 3563

**Comment by Wolffenstein** [comment]
Fixed in rev 3594.
