### ISSUE TITLE
[Warlock][Spell] Curse of Recklessness duration in PvP

### ISSUE THREAD

**Issue by tsuone** [Atlantiss/NetherwingBugtracker#7789]
[//]: # (Enclose links to things related to the bug using http://wowhead.com or any other TBC database.)
[//]: # (You can use screenshot ingame to visual the issue.)
[//]: # (Write your tickets according to the format:)
[//]: # ([Quest][Azuremyst Isle] Red Snapper - Very Tasty!)
[//]: # ([NPC] Magistrix Erona)
[//]: # ([Spell][Mage] Fireball)
[//]: # ([Npc][Drop] Ghostclaw Lynx)
[//]: # ([Web] Armory doesnt work)
[//]: # (To find server revision type `.server info` command in the game chat.)

**Description**: Curse of Recklessness

**Current behaviour**: When casted / spell reflected on an enemy player Curse of Recklessness duration is 12 seconds.

**Expected behaviour**: Curse of Recklessness duration should be 2 minutes when casted / spell reflected on PvP target.

- Proof: https://youtu.be/oo_vcsdBKXc?t=206

**Server Revision**: 3536

**Comment by Wolffenstein** [comment]
Fixed in rev 3594.
