### ISSUE TITLE
Mobs, Fences, Pathing

### ISSUE THREAD

**Issue by Erodraeda** [Atlantiss/NetherwingBugtracker#779]
[//]: # (Enclose links to things related to the bug using http://wowhead.com or any other TBC database.)
[//]: # (You can use screenshot ingame to visual the issue.)
[//]: # (Write your tickets according to the format:)
[//]: # ([Quest][Azuremyst Isle] Red Snapper - Very Tasty!)
[//]: # ([NPC] Magistrix Erona)
[//]: # ([Spell][Mage] Fireball)
[//]: # ([Npc][Drop] Ghostclaw Lynx)
[//]: # ([Web] Armory doesnt work)

**Description**: 
Mobs should go around fences when running after players, not over them.
**Current behaviour**:
https://clips.twitch.tv/BillowingKawaiiNostrilBigBrother
**Expected behaviour**: 
Go around the fence, like explained on the video
**Server Revision**:

**Comment by Emityx** [comment]
Mobs are supposed to go over fences. This is made by blizzard. Blame blizzard ^^

**Comment by Wolffenstein** [comment]
Incorrect. Mobs can go over fences like that on retail.
