### ISSUE TITLE
[Warlock][Succubus] Lesser Invisibility 

### ISSUE THREAD

**Issue by taigaqt** [Atlantiss/NetherwingBugtracker#7793]
[//]: # (Enclose links to things related to the bug using http://wowhead.com or any other TBC database.)
[//]: # (You can use screenshot ingame to visual the issue.)
[//]: # (Write your tickets according to the format:)
[//]: # ([Quest][Azuremyst Isle] Red Snapper - Very Tasty!)
[//]: # ([NPC] Magistrix Erona)
[//]: # ([Spell][Mage] Fireball)
[//]: # ([Npc][Drop] Ghostclaw Lynx)
[//]: # ([Web] Armory doesnt work)
[//]: # (To find server revision type `.server info` command in the game chat.)

**Description**: Lesser Invisibility / Seduction

**Current behaviour**: When Succubus is under effect of Lesser Invisibility, casting a Seduction on an enemy target doesn't take the pet out of Invisibility.

**Expected behaviour**: Using a Seduction while in Lesser Invisibility should take the Succubus out of it.

> By frmorrison (37,847 – 4·41·446) on 2007/07/23 (Patch 2.1.3)
> Useful abilty for the succy for PvP. Since other players cannot see invis pets (unless they have the warlock buff), you can keep it hidden until you cast seduce.

**Server Revision**: 3536

**Comment by Wolffenstein** [comment]
Fixed in rev 3670.
