### ISSUE TITLE
[Spell][Warlock][Pet] Devour Magic

### ISSUE THREAD

**Issue by tsu-1** [Atlantiss/NetherwingBugtracker#7794]
[//]: # (Enclose links to things related to the bug using http://wowhead.com or any other TBC database.)
[//]: # (You can use screenshot ingame to visual the issue.)
[//]: # (Write your tickets according to the format:)
[//]: # ([Quest][Azuremyst Isle] Red Snapper - Very Tasty!)
[//]: # ([NPC] Magistrix Erona)
[//]: # ([Spell][Mage] Fireball)
[//]: # ([Npc][Drop] Ghostclaw Lynx)
[//]: # ([Web] Armory doesnt work)
[//]: # (To find server revision type `.server info` command in the game chat.)

**Description**: Felhunter's Devour Magic pet ability.

**Current behaviour**: When Felhunter uses Devour Magic in order to remove Unstable Affliction from the friendly target, the silence debuff and dispell damage is applied to Warlock instead of the pet.

**Expected behaviour**: When Felhunter dispells Unstable Affliction, pet should receive the silence and damage from the debuff instead of the Warlock.

**Server Revision**: 3536

**Comment by Godmatik** [comment]
Can not reproduce - damage and silence is properly dealt to felhunter and not the warlock
