### ISSUE TITLE
[Core] Arena location visible on friends list

### ISSUE THREAD

**Issue by tsu-1** [Atlantiss/NetherwingBugtracker#7795]
[//]: # (Enclose links to things related to the bug using http://wowhead.com or any other TBC database.)
[//]: # (You can use screenshot ingame to visual the issue.)
[//]: # (Write your tickets according to the format:)
[//]: # ([Quest][Azuremyst Isle] Red Snapper - Very Tasty!)
[//]: # ([NPC] Magistrix Erona)
[//]: # ([Spell][Mage] Fireball)
[//]: # ([Npc][Drop] Ghostclaw Lynx)
[//]: # ([Web] Armory doesnt work)
[//]: # (To find server revision type `.server info` command in the game chat.)

**Description**: Current player location is visible when on arenas and added to the friends list.

**Current behaviour**: You can see current player location (Arena) when added to the friends list.

**Expected behaviour**: Display last player position when joining Arena match.

**Server Revision**: 3536

**Comment by danbopes** [comment]
Should be fixed now

**Comment by tsu-1** [comment]
Still shows Arena location on the friends list.

**Comment by Godmatik** [comment]
You can use .invisible command to hide it now
