### ISSUE TITLE
[Warrior][Spell] Piercing Howl 

### ISSUE THREAD

**Issue by tsu-1** [Atlantiss/NetherwingBugtracker#7796]
[//]: # (Enclose links to things related to the bug using http://wowhead.com or any other TBC database.)
[//]: # (You can use screenshot ingame to visual the issue.)
[//]: # (Write your tickets according to the format:)
[//]: # ([Quest][Azuremyst Isle] Red Snapper - Very Tasty!)
[//]: # ([NPC] Magistrix Erona)
[//]: # ([Spell][Mage] Fireball)
[//]: # ([Npc][Drop] Ghostclaw Lynx)
[//]: # ([Web] Armory doesnt work)
[//]: # (To find server revision type `.server info` command in the game chat.)
https://github.com/Atlantiss/NetherwingBugtracker/issues/5431

**Description**: Piercing Howl / Vanish

**Current behaviour**: Using Piercing Howl instantly after rogue Vanishes doesn't take the rogue out of stealth.

> It does remove the Vanish ~1 second after Rogue uses vanish ability, earlier it print "IMMUNE" message.

**Expected behaviour**: Vanish should be able to break with Piercing Howl in the first second after rogue uses Vanish.

**Server Revision**: 3536

**Comment by Godmatik** [comment]
Vanish gives them a 1 second immunity so I do not believe this is the case. Closing this one out as there are other threads discussing cloak
