### ISSUE TITLE
[Mage][Spell] Water Elemental

### ISSUE THREAD

**Issue by tsuone** [Atlantiss/NetherwingBugtracker#7797]
[//]: # (Enclose links to things related to the bug using http://wowhead.com or any other TBC database.)
[//]: # (You can use screenshot ingame to visual the issue.)
[//]: # (Write your tickets according to the format:)
[//]: # ([Quest][Azuremyst Isle] Red Snapper - Very Tasty!)
[//]: # ([NPC] Magistrix Erona)
[//]: # ([Spell][Mage] Fireball)
[//]: # ([Npc][Drop] Ghostclaw Lynx)
[//]: # ([Web] Armory doesnt work)
[//]: # (To find server revision type `.server info` command in the game chat.)

**Description**: Water Elemental scaling and abilities

**Current behaviour**: Water Elemental scaling is wrong, providing player with an **Elemental having too much health and mana.** On top of that `Water Bolt` and `Freeze` abilities **mana cost are too low.**

**Expected behaviour**: 

1. **Water Elemental HP and Mana scaling formula:**
```
Pet HP = Round(2126 + 7.5*Math.floor(Mage.Stamina * 0.3))
Pet Mana = Math.floor(2375 + 4.95*Math.floor(Mage.Intellect * 0.3))
```

2. **Freeze**
Freeze should cost `313 Mana`

3. **Water Bolt**
Waterbolt should cost `224 Mana`

**Server Revision**: 3536

_Sources:_ 
_Water Elemental scaling:_
https://github.com/ccshiro/cc-buglist/issues/2052#issue-118209209 
https://github.com/Atlantiss/NetherwingBugtracker/issues/3606#issuecomment-657066085

https://github.com/tsuone/pvp/issues/87#issuecomment-704689137
SunstriderEmu/BugTracker#163

**Comment by tsu-1** [comment]
https://github.com/Atlantiss/NetherwingBugtracker/issues/7783

**Comment by Wolffenstein** [comment]
Fixed in rev 3583.
