### ISSUE TITLE
[Spell][Rogue]Backstab bugged

### ISSUE THREAD

**Issue by galediex** [Atlantiss/NetherwingBugtracker#78]
[//]: # (Enclose links to things related to the bug using http://wowhead.com or any other TBC database.)
[//]: # (You can use screenshot ingame to visual the issue.)
[//]: # (Write your tickets according to the format:)
[//]: # ([Quest][Azuremyst Isle] Red Snapper - Very Tasty!)
[//]: # ([NPC] Magistrix Erona)
[//]: # ([Spell][Mage] Fireball)
[//]: # ([Npc][Drop] Ghostclaw Lynx)
[//]: # ([Web] Armory doesnt work)

**Description**: Backstab spending energy incorrectly. 

**Current behaviour**: Backstab when dodged or parried is spending the full amount of energy.

**Expected behaviour**: Backstab when dodged or parried should only spend a portion of the energy when dodged or parried.

**Server Revision**: 2.4.3 Netherwing Open Beta Server

**Comment by zrmapmnewb** [comment]
Other spell of rougue also has this problem. Please check them one by one.

**Comment by ahlens** [comment]
How on earth backstab can be dodged? It's done from behind only?

**Comment by Easyfraggy** [comment]
Mobs dodge from behind. They don't parry though.

**Comment by Wolffenstein** [comment]
Should be fixed now
