### ISSUE TITLE
Quest Innoculation

### ISSUE THREAD

**Issue by Piledriversn** [Atlantiss/NetherwingBugtracker#780]
[//]: # ([Quest][Azuremyst Isle] Innoculation)

**Description**: The quest item sometimes works and sometimes doesn't.

**Current behaviour**:They stand there and nothing happens. Also I killed one and it gave me credit for curing it. I don't believe a quest to cure them is supposed to work by killing them 

**Expected behaviour**: The item is supposed to cure the moonkin or fail and cause them to attack.

**Server Revision**:

**Comment by tcberk12** [comment]
#713 

Please use search function so we can control the amount of duplicate reports.
