### ISSUE TITLE
[Core?] Delayed/wrong Enchantment buff update.

### ISSUE THREAD

**Issue by tsu-1** [Atlantiss/NetherwingBugtracker#7800]
[//]: # (Enclose links to things related to the bug using http://wowhead.com or any other TBC database.)
[//]: # (You can use screenshot ingame to visual the issue.)
[//]: # (Write your tickets according to the format:)
[//]: # ([Quest][Azuremyst Isle] Red Snapper - Very Tasty!)
[//]: # ([NPC] Magistrix Erona)
[//]: # ([Spell][Mage] Fireball)
[//]: # ([Npc][Drop] Ghostclaw Lynx)
[//]: # ([Web] Armory doesnt work)
[//]: # (To find server revision type `.server info` command in the game chat.)

**Description**: Enchantment buff update.

**Current behaviour**: When weapon swapping in arenas a lot, sometimes there is a chance it will show wrong graphic for which weapon is equipped as a poison buff. 

- Example: It can show "Crippling" but when using **Shiv** ability, it is Wound poison instead.

**Expected behaviour**: Display properly equipped weapon.

**Server Revision**: 3571

**Comment by Godmatik** [comment]
Unable to reproduce - weapon swapped a bunch and it never showed the incorrect graphic
