### ISSUE TITLE
[Spell][Warlock][Pet] Seduction breaks due to Pet Stance.

### ISSUE THREAD

**Issue by tsu-1** [Atlantiss/NetherwingBugtracker#7801]
[//]: # (Enclose links to things related to the bug using http://wowhead.com or any other TBC database.)
[//]: # (You can use screenshot ingame to visual the issue.)
[//]: # (Write your tickets according to the format:)
[//]: # ([Quest][Azuremyst Isle] Red Snapper - Very Tasty!)
[//]: # ([NPC] Magistrix Erona)
[//]: # ([Spell][Mage] Fireball)
[//]: # ([Npc][Drop] Ghostclaw Lynx)
[//]: # ([Web] Armory doesnt work)
[//]: # (To find server revision type `.server info` command in the game chat.)

**Description**: Seduction cast.

**Current behaviour**: Seduce breaks if pet is on Defensive/Aggresive, for some reason pet prioritizes to "defend" or "attack" instead of finishing the channel.

**Expected behaviour**: Pet should prioritize finishing channel cast. 

**Server Revision**: 3571

**Comment by Godmatik** [comment]
Unable to reproduce
Succubus seduction cast is being done on full duration, regardless if aggressive or defensive stance
