### ISSUE TITLE
[Core][Arena] Arena Matches results on server restart/crash.

### ISSUE THREAD

**Issue by tsu-1** [Atlantiss/NetherwingBugtracker#7802]
[//]: # (Enclose links to things related to the bug using http://wowhead.com or any other TBC database.)
[//]: # (You can use screenshot ingame to visual the issue.)
[//]: # (Write your tickets according to the format:)
[//]: # ([Quest][Azuremyst Isle] Red Snapper - Very Tasty!)
[//]: # ([NPC] Magistrix Erona)
[//]: # ([Spell][Mage] Fireball)
[//]: # ([Npc][Drop] Ghostclaw Lynx)
[//]: # ([Web] Armory doesnt work)
[//]: # (To find server revision type `.server info` command in the game chat.)

**Description**: Arena Matches result on server restart/crash.

**Current behaviour**: Arena Matches results are randomly decided when server restarts or crashes and match is in progress.

**Expected behaviour**: All Arena Matches during server restart or crash should end in a draw - players shouldn't gain or lose any points.

**Server Revision**: 3571

**Comment by Godmatik** [comment]
Rev 4015 - no longer an issue. 
Verified that a tie is given when server crashes.
