### ISSUE TITLE
Enemies Attacking After Eye of Kilrogg Dies

### ISSUE THREAD

**Issue by Fierywind** [Atlantiss/NetherwingBugtracker#7803]
**Description**: When doing pulls with the Eye of Kilrogg in Hyjal, I at times take multiple melee hits from the enemies, despite being a considerable distance away and out of los, when the eye dies. When this happened, it was mentioned hunters had a similar issue with eyes of the beast, so it seems related to the vehicle system used for these abilities.

**Current behaviour**: Enemies at times melee when the eye of kilrogg dies, despite being far away.

**Expected behaviour**: Enemies never attack the summoner after the eye dies unless actually in range.

**Server Revision**: 3571

**Comment by Godmatik** [comment]
Resolved several months ago - closing
