### ISSUE TITLE
[NPC] Dreadmaw movement speed - Shaartul event

### ISSUE THREAD

**Issue by nevrozac** [Atlantiss/NetherwingBugtracker#7804]
**Description**: 
[NPC] Dreadmaw
Dreadmaw is using incorect movement speed making the fight impossible(?).  According to 2007 Ownedcore guide and Youtube videos Dreadmaw is supposed to be slower, at the very least slower than the Shivan Assassin when in Fire form. 
["Deals heavy melee damage, but moves very slow."](https://www.ownedcore.com/forums/world-of-warcraft/world-of-warcraft-guides/42678-shartuuls-transporter-event-guide.html)
https://www.ownedcore.com/forums/world-of-warcraft/world-of-warcraft-guides/42678-shartuuls-transporter-event-guide.html
https://youtu.be/zQE-mXFx6n0?t=429
https://youtu.be/Cvmn5NIs4b0?t=417
https://youtu.be/qVyAISnY4Es?t=236
**Current behaviour**:
NPC moves at default hostile NPC movement speed
**Expected behaviour**: 
NPC should move slower than normal to allow kiting
**Server Revision**: 
3571

**Comment by Godmatik** [comment]
Closing - consolidating all information into one thread
