### ISSUE TITLE
[Core] Player desync on Arenas

### ISSUE THREAD

**Issue by tsu-1** [Atlantiss/NetherwingBugtracker#7805]
[//]: # (Enclose links to things related to the bug using http://wowhead.com or any other TBC database.)
[//]: # (You can use screenshot ingame to visual the issue.)
[//]: # (Write your tickets according to the format:)
[//]: # ([Quest][Azuremyst Isle] Red Snapper - Very Tasty!)
[//]: # ([NPC] Magistrix Erona)
[//]: # ([Spell][Mage] Fireball)
[//]: # ([Npc][Drop] Ghostclaw Lynx)
[//]: # ([Web] Armory doesnt work)
[//]: # (To find server revision type `.server info` command in the game chat.)

**Description**: Player movement desync on Arenas

**Current behaviour**: I am not sure yet, but this is something that might be related to the latency difference between players:

- https://gfycat.com/pl/evergreenactivealaskajingle
- https://streamable.com/rloczc (not sure, if related or hack)
- https://streamable.com/ihjvax (Pet desynchronization?)
- https://gfycat.com/pl/differentrepulsivehake
- https://gfycat.com/pl/raresillyisopod

From what I gathered so far and Fosquaker says, he has the same problem versus EU and NA players.

**Expected behaviour**: No desynchronization between players.

**Server Revision**: 3571

**Comment by Godmatik** [comment]
All of the links are broken.
Need research to determine if this still occurs.

**Comment by Godmatik** [comment]
No further information, closing
