### ISSUE TITLE
NPC - Servant of XY (Blasted Lands) aggro and kill issues

### ISSUE THREAD

**Issue by OmubiKarazhan** [Atlantiss/NetherwingBugtracker#7808]
Hello there,

I have recently found a bug - at least that is what it looks like to me - with mobs in Blasted Lands:
- Servant of Allistarj, Servant of Razelikh, etc.

These mobs' aggro range is either immense, or infinite (tested). It also appears they are unkillable; At 1% HP, they reach an unkillable stasis for about 30 seconds, that is when the game prompts you about a nearby crystal which you should strike to.. I guess kill the NPC? Well, the crystal is untargetable. When the NPC leaves the stasis, it continues to attack you and follow you through Azeroth, and is still invincible - All attacks are Missed. As a Rogue, I was able to Vanish out of combat, don't know about other classis.

Cheers!

Omubi

**Comment by Godmatik** [comment]
https://github.com/Atlantiss/NetherwingBugtracker/issues/7066

**Comment by Wolffenstein** [comment]
Fixed in rev 3577.

**Comment by Kuszki** [comment]
Problem with "1hp and unable to kill" still exists.
