### ISSUE TITLE
[Black Temple] Supremus - Knockback

### ISSUE THREAD

**Issue by Godmatik** [Atlantiss/NetherwingBugtracker#7809]
Supremus uses an ability in phase 2 on the gaze target to knock you back if you are too close, it should also deal damage when he does this, but it currently does not.

https://www.wowhead.com/npc=22898/supremus#comments;mode:tw

> Phase2; Very similair to The Darkener (first add at Kael'Thas). Supremus will gaze on someone and follow him around for 10 seconds. He will also do the knockbacks from a few yards for ~5k dmg, just like the Darkener.

**Comment by Wolffenstein** [comment]
His charge spell does not have a damage component. I presume the damage the guy meant was fall damage from knockback.
