### ISSUE TITLE
[Gnomeregan] The Sparklematic 5200

### ISSUE THREAD

**Issue by Azalen** [Atlantiss/NetherwingBugtracker#781]
**Current behaviour**:
Two of those gameobjects work fine with animation and everything while the third is missing animation while turning in quests.
https://classicdb.ch/?search=The+Sparklematic+5200

https://i.imgur.com/8WPkbER.jpg <- this one

**Server Revision**: 
[2067]

**Comment by Evolvee** [comment]
fixed in next rev
