### ISSUE TITLE
[Quest] [Hinterlands] Find OOX-09/HL!

### ISSUE THREAD

**Issue by dukelele67** [Atlantiss/NetherwingBugtracker#7811]
[//]: # (Enclose links to things related to the bug using http://wowhead.com or any other TBC database.)
[//]: # (You can use screenshot ingame to visual the issue.)
[//]: # (Write your tickets according to the format:)
[//]: # ([Quest][Azuremyst Isle] Red Snapper - Very Tasty!)
[//]: # ([NPC] Magistrix Erona)
[//]: # ([Spell][Mage] Fireball)
[//]: # ([Npc][Drop] Ghostclaw Lynx)
[//]: # ([Web] Armory doesnt work)
[//]: # (To find server revision type `.server info` command in the game chat.)

**Description**: At the second ambush close to Jintha'Alor the spawning Vilebranch Ambusher's aren't properly despawning.

**Current behaviour**: Vilebranch Ambusher's spawn at the second ambush point and don't despawn after quest is failed. 

**Expected behaviour**: Vilebranch Ambusher's should spawn at the second ambush point and despawn after quest is failed. 

**Server Revision**: 3571
![WoWScrnShot_121620_055237](https://user-images.githubusercontent.com/32690506/102307021-e880cf00-3f63-11eb-98ce-339c8e31c43f.jpg)

**Comment by Wolffenstein** [comment]
Fixed in rev 4006.
