### ISSUE TITLE
[Quest][Epic] Waking Legends

### ISSUE THREAD

**Issue by Aegaren** [Atlantiss/NetherwingBugtracker#7812]
[//]: # (Enclose links to things related to the bug using http://wowhead.com or any other TBC database.)
[//]: # (You can use screenshot ingame to visual the issue.)
[//]: # (Write your tickets according to the format:)
[//]: # ([Quest][Azuremyst Isle] Red Snapper - Very Tasty!)
[//]: # ([NPC] Magistrix Erona)
[//]: # ([Spell][Mage] Fireball)
[//]: # ([Npc][Drop] Ghostclaw Lynx)
[//]: # ([Web] Armory doesnt work)
[//]: # (To find server revision type `.server info` command in the game chat.)

**Description**: There is no event to cleanse 'Nightmare Engulfed Object' and turn it into 'Malfurion's Signet Ring'.

**Current behaviour**: Keeper Remulos gives me the quest 'Waking Legends' and just stands there. GM tried to help me ingame but ended up asking for a bugreport here.

**Expected behaviour**: I think he is supposed to walk to the water and make an event with Malfurion Stromrage and give the reward 'Malfurion's Signet Ring'.

**Server Revision**: 3575

**Comment by Godmatik** [comment]
None of the world dragons are scripted at the moment, along with the quest you get from them.

Low prio.

**Comment by Godmatik** [comment]
Duplicate #5277
