### ISSUE TITLE
Gurtogg Bloodboil ability timers are inconsistent

### ISSUE THREAD

**Issue by rustwo** [Atlantiss/NetherwingBugtracker#7814]
**Description**: 
Gurtogg Bloodboil's bloodboil and fel rage abilities are not used at correct intervals and are not consistent between pulls as they should be

**Current behaviour**:
Bloodboil sometimes does not happen every 10 seconds in phase 1. Fel Rage sometimes does not happen the same number of seconds after phase 1 began.

What this means is that the last bloodboil is delayed and sometimes doesn't even happen until after fel rage is cast! This results in not only preventing the raid from spreading for fel rage but also putting a super powered bloodboil out in the raid that ticks for 2220 damage on 5 people instead of 1200.

Attached is a combat log screenshot demonstrating this problem. You can see that the player did not have a previous stack of bloodboil ticking (so it was not 2 stack damage) but instead immediately began taking 2220 damage ticks. This happened because fel rage was cast at the same time as the last bloodboil and buffed the damage of it.

Backup of screenshot: https://i.imgur.com/5d334je.png

**Expected behaviour**: 
Bloodboil should happen at a consistent interval every 10 seconds in phase 1 (5 total casts, 50 seconds). Fel Rage should happen and cause a phase 2 every 60 seconds (i.e. 10 second gap between last blood boil and fel rage).

Proof of correct timers here: https://wowwiki.fandom.com/wiki/Gurtogg_Bloodboil

**Server Revision**: 
3575

**Comment by rustwo** [comment]
![bboildmg](https://user-images.githubusercontent.com/60513730/102545314-13624480-4084-11eb-94e8-70cb1a7ccde6.png)

**Comment by Wolffenstein** [comment]
Fixed in rev 3576.
