### ISSUE TITLE
[Core][Arena] Disconnecting during Arena Matches doesn't allow you to "rejoin" the match.

### ISSUE THREAD

**Issue by tsu-1** [Atlantiss/NetherwingBugtracker#7815]
[//]: # (Enclose links to things related to the bug using http://wowhead.com or any other TBC database.)
[//]: # (You can use screenshot ingame to visual the issue.)
[//]: # (Write your tickets according to the format:)
[//]: # ([Quest][Azuremyst Isle] Red Snapper - Very Tasty!)
[//]: # ([NPC] Magistrix Erona)
[//]: # ([Spell][Mage] Fireball)
[//]: # ([Npc][Drop] Ghostclaw Lynx)
[//]: # ([Web] Armory doesnt work)
[//]: # (To find server revision type `.server info` command in the game chat.)

**Description**: Arena rejoin after disconnect.

**Current behaviour**: When you get disconnected when in the Arena, after logging back in, you don't appear in the match but instead in the place where you queued from.

**Expected behaviour**: Disconnecting/Quit Game during the Arena match should leave your character ingame, make it available to kill by other players. 
- If your characters is alive/dead and you reconnect to the game, you should appear on the Arena.
- If Arena Match ended, after reconnecting to the game, you should appear in the place you queued from.

**Server Revision**: 3575

**Comment by Godmatik** [comment]
Closing this out as Wolf is in the process of working on reconnect
