### ISSUE TITLE
[Core][Arena] Weapon skill shouldn't matter when engaged in PvP.

### ISSUE THREAD

**Issue by tsu-1** [Atlantiss/NetherwingBugtracker#7817]
[//]: # (Enclose links to things related to the bug using http://wowhead.com or any other TBC database.)
[//]: # (You can use screenshot ingame to visual the issue.)
[//]: # (Write your tickets according to the format:)
[//]: # ([Quest][Azuremyst Isle] Red Snapper - Very Tasty!)
[//]: # ([NPC] Magistrix Erona)
[//]: # ([Spell][Mage] Fireball)
[//]: # ([Npc][Drop] Ghostclaw Lynx)
[//]: # ([Web] Armory doesnt work)
[//]: # (To find server revision type `.server info` command in the game chat.)

**Description**: Weapon skill when engaged in PvP combat.

**Current behaviour**: Weapon Skill isn't automatically maxed when engaged in PvP combat.

**Expected behaviour**: If you have 1/350 Weapon Skill, when engaging in a PvP combat, you should have it "maxed" as Weapon Skill doesn't affect the hit chance in PvP scenario (Arena/Battleground). Only when in World PvP or Duel.

**Server Revision**: 3575

**Comment by raethkcj** [comment]
From testing in Classic, Weapon Skill matters in PvP, but at a reduced rate compared to PvE:

https://github.com/magey/classic-warrior/wiki/Attack-table#weapon-skill

**Comment by raethkcj** [comment]
From testing in Classic, Weapon Skill matters in PvP, but at a reduced rate compared to PvE:

https://github.com/magey/classic-warrior/wiki/Attack-table#weapon-skill

Note that the line on wowwiki was added in March 2010:
https://wowwiki.fandom.com/wiki/Weapon_skill?diff=prev&oldid=2223237

**Comment by Wolffenstein** [comment]
Fixed in rev 3595.
