### ISSUE TITLE
[Quest] The Great Masquerade

### ISSUE THREAD

**Issue by Lio2424** [Atlantiss/NetherwingBugtracker#7818]
[//]: # (Enclose links to things related to the bug using http://wowhead.com or any other TBC database.)
[//]: # (You can use screenshot ingame to visual the issue.)
[//]: # (Write your tickets according to the format:)
[//]: # ([Quest][Azuremyst Isle] Red Snapper - Very Tasty!)
[//]: # ([NPC] Magistrix Erona)
[//]: # ([Spell][Mage] Fireball)
[//]: # ([Npc][Drop] Ghostclaw Lynx)
[//]: # ([Web] Armory doesnt work)
[//]: # (To find server revision type `.server info` command in the game chat.)

**Description**: After doing the quest "Jail Break" you meet up with Squire Rowe who tells Windsor to get out of hiding. Then Windsor and you go to unmask Lady Prestor as Onyxia, Windsor dies in the fight and Bolvar gives you the next quest.

**Current behaviour**: Bolvar Fordragon does not have text to complete the quest after you escort Reginald Windsor.

**Expected behaviour**: Bolvar should complete the quest for you and give you another quest called "The Dragon's Eye"

**Extra**: After you abandon the quest "The Great Masquerade" You cannot speak to Squire Rowe again.

**Server Revision**: 3575

**Comment by Godmatik** [comment]
Unable to reproduce.

Did the full escort - Bolvar killed the dragons - quest completed and I was able to get the next one
