### ISSUE TITLE
[Spell][Hunter] Aimed shot does not reset auto shot

### ISSUE THREAD

**Issue by 4egito** [Atlantiss/NetherwingBugtracker#7819]
[//]: # (Enclose links to things related to the bug using http://wowhead.com or any other TBC database.)
[//]: # (You can use screenshot ingame to visual the issue.)
[//]: # (Write your tickets according to the format:)
[//]: # ([Quest][Azuremyst Isle] Red Snapper - Very Tasty!)
[//]: # ([NPC] Magistrix Erona)
[//]: # ([Spell][Mage] Fireball)
[//]: # ([Npc][Drop] Ghostclaw Lynx)
[//]: # ([Web] Armory doesnt work)
[//]: # (To find server revision type `.server info` command in the game chat.)

**Description**: 
Aimed shot does not reset auto shot as you can see in the video bellow
**Current behaviour**:
https://drive.google.com/file/d/17xOHPv4Hl1ZkhZ5n1athunnrMdcc4fP8/view?usp=sharing
**Expected behaviour**: 
![AimedShot1](https://user-images.githubusercontent.com/52432938/102721709-38191f00-4305-11eb-8422-5082414e80f4.jpg)
![AimedShot2](https://user-images.githubusercontent.com/52432938/102721710-38b1b580-4305-11eb-90ec-0fec3c2dfdef.jpg)
Sources:
https://www.wowhead.com/forums&topic=1945.2
https://wow.gamepedia.com/Patch_2.0.1
https://wowwiki.fandom.com/wiki/Patch_2.0.1
**Server Revision**: 
3575

**Comment by Wolffenstein** [comment]
Yes it does

![image](https://user-images.githubusercontent.com/1576644/102815084-15057280-43cc-11eb-9a97-98580e82637a.png)

**Comment by raethkcj** [comment]
@Wolffenstein @eri1997 as described in #3781, it doesn't happen 100% of the time. Easiest to reproduce when standing at max possible range.

![image](https://user-images.githubusercontent.com/7716908/102824456-79abd780-43a2-11eb-80a5-5020b2c41f14.png)

**Comment by 4egito** [comment]
> Yes it does
> 
> ![image](https://user-images.githubusercontent.com/1576644/102815084-15057280-43cc-11eb-9a97-98580e82637a.png)

i see autoshot lands 3 seconds after aimed... is should lands right after cast. in the same way when u cast "steady shot", auto shot lands right after

**Comment by 4egito** [comment]
Fixed in rev: 3578
