### ISSUE TITLE
[Quest] Stone Tokens

### ISSUE THREAD

**Issue by despairr1** [Atlantiss/NetherwingBugtracker#782]
[//]: # (Enclose links to things related to the bug using http://wowhead.com or any other TBC database.)
[//]: # (You can use screenshot ingame to visual the issue.)
[//]: # (Write your tickets according to the format:)
[//]: # ([Quest][Azuremyst Isle] Red Snapper - Very Tasty!)
[//]: # ([NPC] Magistrix Erona)
[//]: # ([Spell][Mage] Fireball)
[//]: # ([Npc][Drop] Ghostclaw Lynx)
[//]: # ([Web] Armory doesnt work)

**Description**: 
Killed around 15 and didn't get one! Need to up the drop rate!
**Current behaviour**:
Low low low drop rate!
**Expected behaviour**: 
Better
**Server Revision**:

**Comment by tcberk12** [comment]
#755 

Similar report was created 7 hours ago. Please use search functionality before making reports to reduce duplicates.

When reporting low drop rates, please also look up sources to prove it should be higher. There are alot of sources claiming this item has a low drop rate pre patch 3.0, and 15 is probably not a large enough sample size to say it is too low.
