### ISSUE TITLE
[Spell][Hunter] Rapid fire does not provide bonus attack speed when casted

### ISSUE THREAD

**Issue by 4egito** [Atlantiss/NetherwingBugtracker#7820]
[//]: # (Enclose links to things related to the bug using http://wowhead.com or any other TBC database.)
[//]: # (You can use screenshot ingame to visual the issue.)
[//]: # (Write your tickets according to the format:)
[//]: # ([Quest][Azuremyst Isle] Red Snapper - Very Tasty!)
[//]: # ([NPC] Magistrix Erona)
[//]: # ([Spell][Mage] Fireball)
[//]: # ([Npc][Drop] Ghostclaw Lynx)
[//]: # ([Web] Armory doesnt work)
[//]: # (To find server revision type `.server info` command in the game chat.)

**Description**: 
This issue is continuation of #7001 
As you can see in the video i just make macro for rapid fire + aimed shot cast but the cast speed didn't changed. In that case you need to wait like 1-2 seconds in order to get haste bonus which in pve is not a big deal but in some pvp situations u need that haste in the same moment.
**Current behaviour**:
https://drive.google.com/open?id=1L8C5yFBrOrSI1tLhpbuwpypPo8CfY4w7
**Expected behaviour**: 
Rapid fire should provide haste bonus instantly without delay
![RapidFIre](https://user-images.githubusercontent.com/52432938/102721898-43207f00-4306-11eb-9558-911831b8d15e.jpg)
Sources:
https://wow.gamepedia.com/Rapid_Fire?oldid=1569864
**Server Revision**: 
3575

**Comment by Wolffenstein** [comment]
Fixed in rev 3576.
