### ISSUE TITLE
[Spell][Hunter] Aspect of the viper mana regen broken 

### ISSUE THREAD

**Issue by 4egito** [Atlantiss/NetherwingBugtracker#7821]
[//]: # (Enclose links to things related to the bug using http://wowhead.com or any other TBC database.)
[//]: # (You can use screenshot ingame to visual the issue.)
[//]: # (Write your tickets according to the format:)
[//]: # ([Quest][Azuremyst Isle] Red Snapper - Very Tasty!)
[//]: # ([NPC] Magistrix Erona)
[//]: # ([Spell][Mage] Fireball)
[//]: # ([Npc][Drop] Ghostclaw Lynx)
[//]: # ([Web] Armory doesnt work)
[//]: # (To find server revision type `.server info` command in the game chat.)

**Description**: 
This is continuation of #7566
**Current behaviour**:
![WoWScrnShot_122020_210213](https://user-images.githubusercontent.com/52432938/102722050-2fc1e380-4307-11eb-9073-e8cc905db4c4.jpg)
**Expected behaviour**: 
Enough info here: #7566
**Server Revision**: 
3575

**Comment by Wolffenstein** [comment]
Fixed in rev 3576.
