### ISSUE TITLE
[Core] Incorrect charges/intercepts behind line of sight

### ISSUE THREAD

**Issue by 4egito** [Atlantiss/NetherwingBugtracker#7822]
[//]: # (Enclose links to things related to the bug using http://wowhead.com or any other TBC database.)
[//]: # (You can use screenshot ingame to visual the issue.)
[//]: # (Write your tickets according to the format:)
[//]: # ([Quest][Azuremyst Isle] Red Snapper - Very Tasty!)
[//]: # ([NPC] Magistrix Erona)
[//]: # ([Spell][Mage] Fireball)
[//]: # ([Npc][Drop] Ghostclaw Lynx)
[//]: # ([Web] Armory doesnt work)
[//]: # (To find server revision type `.server info` command in the game chat.)

**Description**: 
As you can see in the video bellow the shaman is not even close to LOS but still i was able to charge from Africa which is not correct...
**Current behaviour**:
https://clips.twitch.tv/SucculentPreciousTildeNotATK
**Expected behaviour**: 
![los1](https://user-images.githubusercontent.com/52432938/102722708-98ab5a80-430b-11eb-9633-e568deba6d65.jpg)
![LOS](https://user-images.githubusercontent.com/52432938/102722709-9943f100-430b-11eb-812e-873f49320174.jpg)
Sources:
https://wow.gamepedia.com/Line_of_sight?oldid=1540851
https://worldofwarcraft.fandom.com/et/wiki/Line_of_sight?oldid=28290
**Server Revision**: 
3575

**Comment by Godmatik** [comment]
Ruins of Lordaeron altar was fixed several months ago.

Closing.
