### ISSUE TITLE
Resistance not stacking properly

### ISSUE THREAD

**Issue by grrwuf** [Atlantiss/NetherwingBugtracker#7823]
Location: Scholomance
Problem: Currently using Shadow Resistance aura from Paladin (60 Shadow Resistance) and Shadow Protection form Priest (45 Shadow Resistance), yet the total Shadow Resistance in my and another character`s screen wont go over 65

**Comment by Godmatik** [comment]
Intended, shadow resistance aura and priest shadow protection buff don't stack
