### ISSUE TITLE
[NPC] Willix the Importer

### ISSUE THREAD

**Issue by dekayius** [Atlantiss/NetherwingBugtracker#7824]
[//]: # (Enclose links to things related to the bug using http://wowhead.com or any other TBC database.)
[//]: # (You can use screenshot ingame to visual the issue.)
[//]: # (Write your tickets according to the format:)
[//]: # ([Quest][Azuremyst Isle] Red Snapper - Very Tasty!)
[//]: # ([NPC] Magistrix Erona)
[//]: # ([Spell][Mage] Fireball)
[//]: # ([Npc][Drop] Ghostclaw Lynx)
[//]: # ([Web] Armory doesnt work)
[//]: # (To find server revision type `.server info` command in the game chat.)

**Description**: Horde Friendly Escort NPC Goblin, Willix the Importer, states "$n incoming!" in various ways.
Dungeon RFK
![willix](https://user-images.githubusercontent.com/76267822/102743450-1af04a80-431d-11eb-854b-31fe38f58445.png)

**Current behaviour**: $n incoming! Help!

**Expected behaviour**: %n incoming! Help!

**Server Revision**: unknown.  Dec 20th 2020

**Comment by Wolffenstein** [comment]
Fixed in rev 3661.
