### ISSUE TITLE
Banish and Demonic knowlage

### ISSUE THREAD

**Issue by Drainlock** [Atlantiss/NetherwingBugtracker#7825]
[//]: # (Enclose links to things related to the bug using http://wowhead.com or any other TBC database.)
[//]: # (You can use screenshot ingame to visual the issue.)
[//]: # (Write your tickets according to the format:)
[//]: # ([Quest][Azuremyst Isle] Red Snapper - Very Tasty!)
[//]: # ([NPC] Magistrix Erona)
[//]: # ([Spell][Mage] Fireball)
[//]: # ([Npc][Drop] Ghostclaw Lynx)
[//]: # ([Web] Armory doesnt work)
[//]: # (To find server revision type `.server info` command in the game chat.)

**Description**: 
After last changes banish don't remove Demonic Knowledge from pet owner
**Current behaviour**:
[3557][Core] Bugtracker Fixes
[Core/Warlock]:
- Demonic Knowledge will no longer disappear from the Warlock when their pet is banished
**Expected behaviour**: 
Banishing/cycloning pet of slsl lock should remove all buffs linked to pet: Demonic Knowledge, Soul link, Master Demonologist.
Proofs:
https://youtu.be/yU6T3RA77ZE?t=1506
https://youtu.be/_HNqnWD1JBs?t=314
**Server Revision**: 
Every revision after 3557

**Comment by Wolffenstein** [comment]
https://wowwiki.fandom.com/wiki/Patch_2.2.0

"Demonic Knowledge: This effect will no longer deactivate when the Warlock's pet is Banished."
