### ISSUE TITLE
Shartuul LOS casting

### ISSUE THREAD

**Issue by Romuus** [Atlantiss/NetherwingBugtracker#7826]
[//]: # (Enclose links to things related to the bug using http://wowhead.com or any other TBC database.)
[//]: # (You can use screenshot ingame to visual the issue.)
[//]: # (Write your tickets according to the format:)
[//]: # ([Quest][Azuremyst Isle] Red Snapper - Very Tasty!)
[//]: # ([NPC] Magistrix Erona)
[//]: # ([Spell][Mage] Fireball)
[//]: # ([Npc][Drop] Ghostclaw Lynx)
[//]: # ([Web] Armory doesnt work)
[//]: # (To find server revision type `.server info` command in the game chat.)

**Description**:  While fightning with Shartuul on Shartuul's Transporter event, i am out of line of sight but he can still hit me and cast but i can not cast. 

**Current behaviour**:

**Expected behaviour**: 

**Server Revision**:

**Comment by Godmatik** [comment]
Closing - consolidating all information into one thread
