### ISSUE TITLE
[Core][Battleground] Wrong battleground result in Warsong Gulch.

### ISSUE THREAD

**Issue by tsu-1** [Atlantiss/NetherwingBugtracker#7828]
[//]: # (Enclose links to things related to the bug using http://wowhead.com or any other TBC database.)
[//]: # (You can use screenshot ingame to visual the issue.)
[//]: # (Write your tickets according to the format:)
[//]: # ([Quest][Azuremyst Isle] Red Snapper - Very Tasty!)
[//]: # ([NPC] Magistrix Erona)
[//]: # ([Spell][Mage] Fireball)
[//]: # ([Npc][Drop] Ghostclaw Lynx)
[//]: # ([Web] Armory doesnt work)
[//]: # (To find server revision type `.server info` command in the game chat.)

**Description**: Wrong battleground results (win, lose) in relation to score - Warsong Gulch.

**Current behaviour**: When you run out of time on Warsong Gulch matches end with a draw regardless of who capped more/last.

**Expected behaviour**: Warsong Gulch result should be determined by "`who was last to score a capture the flag`".

This means:
- If Horde team captures the flag first for the score 1:0, and then Alliance ties with them just before match ends - **Alliance should get the win.** 

**Server Revision**: 3575

**Comment by Wolffenstein** [comment]
You wanted this change yourself...
