### ISSUE TITLE
[Hunter][Spell]Aimed Shot

### ISSUE THREAD

**Issue by zeronxz** [Atlantiss/NetherwingBugtracker#7829]
[//]: # (Enclose links to things related to the bug using http://wowhead.com or any other TBC database.)
[//]: # (You can use screenshot ingame to visual the issue.)
[//]: # (Write your tickets according to the format:)
[//]: # ([Quest][Azuremyst Isle] Red Snapper - Very Tasty!)
[//]: # ([NPC] Magistrix Erona)
[//]: # ([Spell][Mage] Fireball)
[//]: # ([Npc][Drop] Ghostclaw Lynx)
[//]: # ([Web] Armory doesnt work)
[//]: # (To find server revision type `.server info` command in the game chat.)

**Description**: There is extremely big inconsistency of what happens after firing Aimed Shot which ruins the damage combo of a hunter in PvP. Autoshot->Aimed Shot->Auto Shot->Steady Shot becomes exteremly unreliable and absolutely random in a way that the last two attacks cannot even happen. I tried it with Steady Shot macros and without, the issue still remains.

**Current behaviour**: After firing Aimed Shot 2 things may often happen:
1). Autoshot doesn't occur at all, I need to wait for entire windup time (like 3 seconds) until an autoshot happens. 
2). I will get a global cooldown AFTER the cast of Aimed Shot which prevents me from using any ability at all right after that, for example I cannot cast steady shot.
Sometimes none of the mentioned things happen at all but their occurence is frequent.

**Expected behaviour**: Aimed Shot should properly reset the Autoshot. It also shouldn't cause a GCD after the cast finishes. After casting aimed shot I should be able to instantly follow up with Auto Shot and Steady Shot. If I fire Autoshot before casting Aimed Shot, it should also reset the Autoshot.

**Server Revision**: 3575

**Comment by Wolffenstein** [comment]
Read changelog
