### ISSUE TITLE
[Quest][Stonetalon Mountains] Protect Kaya

### ISSUE THREAD

**Issue by Xynaps** [Atlantiss/NetherwingBugtracker#783]
Quest: https://www.wowhead.com/quest=6523/protect-kaya
**Description**:  After being in combat where one of 2 mobs reset Kaya just freezes in place after exiting combat. 

**Current behaviour**: Does not return to the escort quest pathing.

**Expected behaviour**:  Return to the point from where she engaged in combat and continue walking the escort route.

**Server Revision**:  2073

**Comment by Easyfraggy** [comment]
https://github.com/Atlantiss/NetherwingBugtracker/issues/659

**Comment by Manaci** [comment]
Fixed
