### ISSUE TITLE
[Item][Spell] Eye of Magtheridon not interacting properly with resists from secondary spell effects

### ISSUE THREAD

**Issue by hiddenprayer** [Atlantiss/NetherwingBugtracker#7831]
**Description**: 

The "resist" effect from your recent change to Shadow Weaving isn't applying the proc effect from [Eye of Magtheridon] https://tbc-twinhead.twinstar.cz/?item=28789.

The Eye of Magtheridon proc effect reads - Equip: Grants 170 increased spell damage for 10sec when one of your spells is resisted.

 Karazhan's most recent change to Shadow Weaving reads - [Core/Priest]:- Shadow Weaving will now have a separate chance to be resisted, similar to Winter's Chill.

**Current behaviour**:

Eye of Magtheridon isn't applying the proc effect when secondary spell effects like Shadow Weaving are resisted. 

**Expected behaviour**: 

Eye of Magtheridon should proc when secondary spell effects like Shadow Weaving are resisted. Anecdotal but users on wowhead (https://www.wowhead.com/item=28789/eye-of-magtheridon#comments) at the time confirm that secondary spell effects like Shadow Weaving did apply the proc effect during retail Burning Crusade.

**Comment by vertria** [comment]
up please

**Comment by Godmatik** [comment]
Need to double check that this is still happening after spell rework.

**Comment by Godmatik** [comment]
Rev 4018 - still an issue. 

Resisting the Shadow Weaving application will not proc the trinket, but it should:

![1122](https://github.com/user-attachments/assets/ec1ce738-1ea0-4122-bbb5-40bdbfea7cfb)

**Comment by Godmatik** [comment]
Fixed in upcoming spell proc rework branch
