### ISSUE TITLE
Aether Rays - random evade

### ISSUE THREAD

**Issue by kemotix** [Atlantiss/NetherwingBugtracker#7833]
**Description**: 
Aether Rays tend to evade randomly and reset while standing next to player.

**Expected behaviour**: 
No mobs should reset during fight while beeing able to attack player.

**Server Revision**: 
3578

**Comment by Godmatik** [comment]
This occurs on all flying enemies, sometimes they will simply evade and reset mid-combat

**Comment by Godmatik** [comment]
Still an issue.

**Comment by Wolffenstein** [comment]
Can't reproduce it, I'll increase leash range for flying units just in case in rev 3677.
