### ISSUE TITLE
[Core] Dismounted when entering any water

### ISSUE THREAD

**Issue by iStuff0** [Atlantiss/NetherwingBugtracker#7836]
**Description**: 
The game dismounts you when you enter any water. I don't mean deep water, i mean shallow water. Water whose depth shouldn't dismount you.

All add ons disabled.

**Current behaviour**:
As above

**Expected behaviour**: 
Should only dismount you for water that requires swimming.

**Server Revision**: 
This is the Netherwing realm (doesn't happen on Karazhan), and .server info returns 'there is no such subcommand'.

**Comment by Wolffenstein** [comment]
Can you provide some specific places (screenshots/videos) where that happens so I can test it?

**Comment by iStuff0** [comment]
Any water in Zangarmarsh. Pools of Aggonar in Hellfire Perninsula. I also put my front paws in the rivers of Terokkar Forest and it did the same. Haven't been anywhere else yet.

**Comment by tsu-1** [comment]
@iStuff0 Race?

**Comment by iStuff0** [comment]
Both human and nelf. No idea if this is still a thing though as haven't been on there for quite a while. 

Edit: no longer a thing. I can run through water just fine now.
