### ISSUE TITLE
Combat bug

### ISSUE THREAD

**Issue by Scratch741** [Atlantiss/NetherwingBugtracker#7837]
**Description**: While out of combat, buffing / healing a teammate who is in combat causes a 0,5s delay in gaining in combat state. Rogues abuse it or healers casts big heal and then they can drink immediately.

**Current behaviour**: 0,5s delay

**Expected behaviour**: 0s delay

**Server Revision**:  3578

**Comment by Wolffenstein** [comment]
Not a bug, spell delay.
