### ISSUE TITLE
[Item Set][Spell] Warlock Oblivion Raiment 2x set bonus

### ISSUE THREAD

**Issue by Drainlock** [Atlantiss/NetherwingBugtracker#7839]
[//]: # (Enclose links to things related to the bug using http://wowhead.com or any other TBC database.)
[//]: # (You can use screenshot ingame to visual the issue.)
[//]: # (Write your tickets according to the format:)
[//]: # ([Quest][Azuremyst Isle] Red Snapper - Very Tasty!)
[//]: # ([NPC] Magistrix Erona)
[//]: # ([Spell][Mage] Fireball)
[//]: # ([Npc][Drop] Ghostclaw Lynx)
[//]: # ([Web] Armory doesnt work)
[//]: # (To find server revision type `.server info` command in the game chat.)

**Description**: 
2 pieces of Warlocks D3 set should grant next bonus : Grants your pet 45 mana per 5 sec.
https://www.wowhead.com/item-set=644/oblivion-raiment#comments
**Current behaviour**:
Doesn't increas pet mana regeneration at all. Tested with Felguard, felhunter and void.
**Expected behaviour**: 
Should give extra 45 mp5 to pet no matter in combat or OOC
**Server Revision**: 
3619

P.S. Haven't tested 4x bonus, coz I have only 2 items, might be bugged as well.

**Comment by Wolffenstein** [comment]
Fixed in rev 3691.
