### ISSUE TITLE
[Gnomeregan] Quest Level and Level Requirements

### ISSUE THREAD

**Issue by Azalen** [Atlantiss/NetherwingBugtracker#784]
**Current behaviour**:
https://i.imgur.com/m9emj1y.jpg

**Expected behaviour**: 
All quest level and level requirements to take the quests are still pre patch 2.3. After patch 2.3 Gnomeregan got downgraded from 29-38 to 25-28; [Source](https://wow.gamepedia.com/index.php?title=Instances_by_level&oldid=923891).

While all the mobs are downgraded right now the quests are not. For example a level 24 player can not take the mainquest at the moment since it is a level 35 quest that needs level 25 requirement ([Source](https://classicdb.ch/?quest=2929)) even though the endboss is only level 28. 

-> All quests needs adjustments in their level and level requirements. Sadly I wasn't able to find a list of those. All I know is, that you can enter the dungeon at level 15.

**Server Revision**: 
[2067]

**Comment by Shanghi** [comment]
I couldn't find any changes from tcberk12's list anywhere (besides Chief-Engineer Scooty and Gnomer-gooooone! being 20 on archived Wowhead and a bit later on Thottbot but they're already set that way). If you can find any sources about the levels being lowered then reopen this and they'll surely be fixed!
