### ISSUE TITLE
Loot of eclipsion archmage for Ench and Alch

### ISSUE THREAD

**Issue by winter9596** [Atlantiss/NetherwingBugtracker#7840]
[//]: # (Enclose links to things related to the bug using http://wowhead.com or any other TBC database.)
[//]: # (You can use screenshot ingame to visual the issue.)
[//]: # (Write your tickets according to the format:)
[//]: # ([Quest][Azuremyst Isle] Red Snapper - Very Tasty!)
[//]: # ([NPC] Magistrix Erona)
[//]: # ([Spell][Mage] Fireball)
[//]: # ([Npc][Drop] Ghostclaw Lynx)
[//]: # ([Web] Armory doesnt work)
[//]: # (To find server revision type `.server info` command in the game chat.)

**Description**: 
I am both Ench and Alch, trying to kill archmage for formula and recipe. The recipe is easy but formula is hard. I kill few hours with more than 500 kills but no loot. May the system buged here cause i am both Ench and Alch?  
**Current behaviour**:
https://www.wowhead.com/npc=19796/eclipsion-archmage
**Expected behaviour**: 
right loot for them
**Server Revision**: 
3578

**Comment by Godmatik** [comment]
What is your enchanting skill at? 
The formula will only drop if you are high enough skill to learn it.

**Comment by winter9596** [comment]
around 370, I farm the shadow res first then come here. I can loot shadow res, this arcane res should also work

**Comment by winter9596** [comment]
i got it we can close

**Comment by Godmatik** [comment]
you can close it yourself
