### ISSUE TITLE
"Thunderlord Clan Artifacts" quest bugged

### ISSUE THREAD

**Issue by Lightspell** [Atlantiss/NetherwingBugtracker#7841]
**Current behaviour**:

Hello,

the quest "Thunderlord Clan Artifacts" in Blades Edge Mountains is bugged.
I collected 2 of 3 Artifacts. But the last artifact - the arrow, isnt activ, so I cant 
interact with it to receive it.
I abaddoned the quest and started it again. But the problem persisnt.

Help me with this isuue please.

Best Regards,

**Comment by Godmatik** [comment]
close game, delete cache folder, try again
