### ISSUE TITLE
[Spell][Warlock] Death Coil - Bosses Immune - Broken Since Revision 3545

### ISSUE THREAD

**Issue by F4play** [Atlantiss/NetherwingBugtracker#7842]
[//]: **# https://tbcdb.com/?spell=27223
[//]: # Revision: 3578

**Description**: 

Death Coil has two components, horrify and health leech. **In Server Revision 3545, Death Coil was modified** so that bosses seem to consider Death Coil as a single component. Since bosses are immune to horrify effects, death coil's damage/leech no longer works on bosses.

**Current behaviour**:

Death Coil's leech component no longer works on bosses. (immune)

From 3545 (this is the revision that broke death coil's leech on bosses) - 

[Core/Spell]:
- Health Leech effects will no longer generate assist threat due to healing

**Expected behaviour**: 
Bosses are not immune to health leech/damage spells.

Reasoning: [Spell][Priest] Devouring Plague is considered a health leech. Bosses are not immune to devouring plague. https://tbcdb.com/?spell=25467

**Server Revision**: 
3578

**Comment by Wolffenstein** [comment]
That revision has nothing to do with breaking Death Coil and I doubt it worked before in the first place (if this is really a bug).

**Comment by Wolffenstein** [comment]
![image](https://user-images.githubusercontent.com/1576644/104150137-29d89300-53d9-11eb-82fc-1fc1ea846728.png)
Works fine for me. Tested on Quagmirran and Teron Gorefiend.

**Comment by F4play** [comment]
> ![image](https://user-images.githubusercontent.com/1576644/104150137-29d89300-53d9-11eb-82fc-1fc1ea846728.png)
> Works fine for me. Tested on Quagmirran and Teron Gorefiend.

Tested tonight on multiple bosses. Still not working :(

Character: Next

Archimonde - Demon - log: https://legacyplayers.com/Raids/Viewer/Default.aspx?id=16220&exp=1&upl=24741
Gurtogg Bloodboil - Humanoid - log: https://legacyplayers.com/Raids/Viewer/Default.aspx?id=16219&exp=1

Character: Sevomira

Anetheron - Demon - log: https://legacyplayers.com/Raids/Viewer/Default.aspx?id=16220&exp=1&upl=24741
Azgalor - Demon - log: https://legacyplayers.com/Raids/Viewer/Default.aspx?id=16220&exp=1&upl=24741

Teron Gorefiend is an Undead and Quagg is a Giant so I'm wondering if there's an issue with the NPC classification that is causing this issue. Oddly enough it worked on Supremus for me tonight when he was in his kite phase.. 

Another thought I had, maybe there's some sort of class-specific debuff that is being applied by someone else in our raid that is causing this unpredictable immunity. I noticed that death coil pretty much always works for me on Council, and it worked for me on Supremus during kite phase tonight when I swear I've had nights where I death coiled him and it didn't work.. maybe our shadow priest is putting something debuff up (shadow weaving?) and when he isn't attacking it the death coil goes through. That's the first class I thought of since he has shadow weaving, but it could very well be a melee or something. 

![death-coil-bug](https://user-images.githubusercontent.com/41980757/104690146-bd031880-56b8-11eb-971c-59d47dc4dc8a.jpg)

**Comment by MecAtlantiss** [comment]
![image](https://user-images.githubusercontent.com/16357005/104690294-2cd1cd00-56d2-11eb-819a-7f5f9c2cdf98.png)
![image](https://user-images.githubusercontent.com/16357005/104690429-6acef100-56d2-11eb-8816-ea1439481b2f.png)

**Comment by F4play** [comment]
It's Curse of Recklessness. Just tested it on a wolf outside of shatt and it's immune to death coil's damage/healing when I put reck up. 

Proof from Classic. Healing/Damage comes through with curse of reck on a boss
 Classic WoW: https://clips.twitch.tv/EphemeralAthleticHorsePermaSmug
