### ISSUE TITLE
Wizard Oil, Mystic Spellthread do not actually increase Spellpower

### ISSUE THREAD

**Issue by dezzra** [Atlantiss/NetherwingBugtracker#7843]
[//]: # (Enclose links to things related to the bug using http://wowhead.com or any other TBC database.)
[//]: # (You can use screenshot ingame to visual the issue.)
[//]: # (Write your tickets according to the format:)
[//]: # ([Quest][Azuremyst Isle] Red Snapper - Very Tasty!)
[//]: # ([NPC] Magistrix Erona)
[//]: # ([Spell][Mage] Fireball)
[//]: # ([Npc][Drop] Ghostclaw Lynx)
[//]: # ([Web] Armory doesnt work)
[//]: # (To find server revision type `.server info` command in the game chat.)

**Description**: I sent an enchanted weapon and enchanted pants to my lvl 13 alt through the mail.  The enchants still appear on the items, but do not seem to be actually working.  

**Current behaviour**: Moonfire still hits for the base amount of 15-20.  The greatest damage was only 28.  

**Expected behaviour**: Moonfire should be hitting for 15-20 + 68 damage (83-88).  

**Server Revision**: 3578

Screenshots: https://imgur.com/a/n5smxDx

**Comment by Tereneckla** [comment]
Low level spells have very low spell coefficients
