### ISSUE TITLE
Quest: A Slow Death 

### ISSUE THREAD

**Issue by Psyhh1337** [Atlantiss/NetherwingBugtracker#7844]
**Description**: 
Quest  A Slow Death ---  if  i use  Yarzill's Mutton where 3 Dragonmaw Peon are mining and they come eat it only 1 out of 3 gets poisoned , but they all have to get it not just one.  To use Yarzill's Mutton i need to farm Fel Gland that all ready takes about 30min to farm as a melee dps. if  I remember Fel Gland drop was 90-100% form mobs not 20%

Help me with this isuue please.

Best Regards,

**Comment by Tereneckla** [comment]
You need to farm 12 fel glands for the quest. Getting multiple quest credits with one use is and was never possible.
Most mobs have a very bad droprate of fel glands. Only Greater Diemetradons and Netherskates are worth farming.
