### ISSUE TITLE
[Spell][Rogue] Eviscerate

### ISSUE THREAD

**Issue by stabbydonkey** [Atlantiss/NetherwingBugtracker#7845]
[//]: # (Enclose links to things related to the bug using http://wowhead.com or any other TBC database.)
[//]: # (You can use screenshot ingame to visual the issue.)
[//]: # (Write your tickets according to the format:)
[//]: # ([Quest][Azuremyst Isle] Red Snapper - Very Tasty!)
[//]: # ([NPC] Magistrix Erona)
[//]: # ([Spell][Mage] Fireball)
[//]: # ([Npc][Drop] Ghostclaw Lynx)
[//]: # ([Web] Armory doesnt work)
[//]: # (To find server revision type `.server info` command in the game chat.)

**Description**: Skill toolltip and dmg from skill are different

**Current behaviour**:Numbers are based on skill rank 6. With 3 combo points skill tooltip says i should deal 265-309dmg but i deal less. it's around 200 as if i had 2 combo points on target (184-228).
Below are pasted numbers form combatlog

Stabbydonkey's **Sinister Strike** hits Highland Thrasher for 127 Physical.
Stabbydonkey's melee swing hits Highland Thrasher for 188 Physical. (Critical)
Stabbydonkey's melee swing hits Highland Thrasher for 102 Physical.
Stabbydonkey's gains 1 extra attacks through Sword Specialization.
Highland Thrasher's melee swing hits Stabbydonkey for 60 Physical.
Stabbydonkey's **Sinister Strike** hits Highland Thrasher for 85 Physical. (20 Blocked)
Stabbydonkey's melee swing hits Highland Thrasher for 60 Physical.
Highland Thrasher's attack was dodged by Stabbydonkey.
Stabbydonkey's attack misses Highland Thrasher.
Stabbydonkey's **Sinister Strike** hits Highland Thrasher for 234 Physical. (Critical)
Stabbydonkey's attack misses Highland Thrasher.
Highland Thrasher's melee swing hits Stabbydonkey for 54 Physical.
Stabbydonkey's melee swing hits Highland Thrasher for 79 Physical.
Stabbydonkey's **Eviscerate** hits Highland Thrasher for 219 Physical.
Stabbydonkey's melee swing hits Highland Thrasher for 62 Physical.
Highland Thrasher's melee swing hits Stabbydonkey for 61 Physical.
Stabbydonkey's attack misses Highland Thrasher.
Stabbydonkey's melee swing hits Highland Thrasher for 62 Physical.
Highland Thrasher's melee swing hits Stabbydonkey for 48 Physical.
Stabbydonkey's melee swing hits Highland Thrasher for 83 Physical.
10bStabbydonkey has slain Highland Thrasher!
**Expected behaviour**: 

**Server Revision**: 3578

**Comment by Tereneckla** [comment]
Armor exists
