### ISSUE TITLE
[Spell][Mage] Summon Water Elemental incorrect stats

### ISSUE THREAD

**Issue by 4egito** [Atlantiss/NetherwingBugtracker#7847]
[//]: # (Enclose links to things related to the bug using http://wowhead.com or any other TBC database.)
[//]: # (You can use screenshot ingame to visual the issue.)
[//]: # (Write your tickets according to the format:)
[//]: # ([Quest][Azuremyst Isle] Red Snapper - Very Tasty!)
[//]: # ([NPC] Magistrix Erona)
[//]: # ([Spell][Mage] Fireball)
[//]: # ([Npc][Drop] Ghostclaw Lynx)
[//]: # ([Web] Armory doesnt work)
[//]: # (To find server revision type `.server info` command in the game chat.)

**Description**: 
This is continuation of this issue: #3606
**Current behaviour**:
Current stats are pretty high even for naked mage where the water elemental has above 3k hp... In pve this means nothing cause nobody focuses the pet but in pvp situation you need to spend much more time to kill it when his stats are buffed like this.
![87225638-3bdc6900-c397-11ea-8b24-ee26752c3678](https://user-images.githubusercontent.com/52432938/103278493-484f8f00-49d4-11eb-80ed-7ddc7e4f2aab.jpg)

**Expected behaviour**: 
![87225346-e1420d80-c394-11ea-80de-325bff79ece2](https://user-images.githubusercontent.com/52432938/103278591-877de000-49d4-11eb-9dbb-14a1b5316c75.png)
**Pet HP = Round(2126 + 7.5*Math.floor(Mage Stam * 0.3))
Pet Mana = Math.floor(2375 + 4.95*Math.floor(Mage Int * 0.3))**
Sources: https://github.com/ccshiro/cc-buglist/issues/2052
More info in previous thread: #3606
**Server Revision**: 
3578

**Comment by tsu-1** [comment]
https://github.com/Atlantiss/NetherwingBugtracker/issues/7797

Duplicate, add info there.
