### ISSUE TITLE
Hunter pet auto attack bug 

### ISSUE THREAD

**Issue by versaac** [Atlantiss/NetherwingBugtracker#7848]
[//]: # (Enclose links to things related to the bug using http://wowhead.com or any other TBC database.)
[//]: # (You can use screenshot ingame to visual the issue.)
[//]: # (Write your tickets according to the format:)
[//]: # ([Quest][Azuremyst Isle] Red Snapper - Very Tasty!)
[//]: # ([NPC] Magistrix Erona)
[//]: # ([Spell][Mage] Fireball)
[//]: # ([Npc][Drop] Ghostclaw Lynx)
[//]: # ([Web] Armory doesnt work)
[//]: # (To find server revision type `.server info` command in the game chat.)

**Description**: [Core/Movement]:
- Fixed potential issue with Pets not moving close enough to the target to be able to attack

**Current behaviour**:
I have experienced many times in raid after this bug fix that this is still happening to hunter pets. They’re not in range for auto attack but their ranged spells like “Lightning Breath” works fine. You have to call back your pet back and forth in order to make them being able to hit with their auto attacks
**Expected behaviour**: 
That they’re in range for auto attack when you /petattack them
**Server Revision**:

**Comment by eri1997** [comment]
https://github.com/Atlantiss/NetherwingBugtracker/issues/7463
Can confirm still bugged. Happened a couple of times on moving targets for me . Pet forgets to auto attack if boss moves too much but still does Lightning Breath .

**Comment by Wolffenstein** [comment]
Should be fixed in rev 3582.
