### ISSUE TITLE
Section of Wrathscale Lair causing mobs to evade bug

### ISSUE THREAD

**Issue by Notmittz** [Atlantiss/NetherwingBugtracker#785]
Bloodmyst Isle, Wrathscale Lair, at coords 68.82, 65.76

Area highlighted in red is region that is causing mobs to evade when trying to cross in/out of: 
 https://imgur.com/a/OcNjlI0

**Description**: 
There is a lowered section at the top of this hill that causes mobs to evade bug.  I can sometimes pull mobs here and they stop attacking back.

**Current behaviour**:
Mobs have problems transitioning between the normal flat ground and this lowered, destroyed section

**Expected behaviour**: 
Mobs shouldn't have any issues moving across this section

**Server Revision**: 
[2073]

**Comment by Tereneckla** [comment]
Fixed
