### ISSUE TITLE
Guild Bank Tab Information not saving.

### ISSUE THREAD

**Issue by TinoniVT** [Atlantiss/NetherwingBugtracker#7850]
[//]: # (Enclose links to things related to the bug using http://wowhead.com or any other TBC database.)
[//]: # (You can use screenshot ingame to visual the issue.)
[//]: # (Write your tickets according to the format:)
[//]: # ([Quest][Azuremyst Isle] Red Snapper - Very Tasty!)
[//]: # ([NPC] Magistrix Erona)
[//]: # ([Spell][Mage] Fireball)
[//]: # ([Npc][Drop] Ghostclaw Lynx)
[//]: # ([Web] Armory doesnt work)
[//]: # (To find server revision type `.server info` command in the game chat.)

**Description**: 
Saving Guild Bank Tab Information doesn't correctly save.

**Current behaviour**:
Clicking "Save Changes" once or twice does not save information. Requires spamming clicking of the save button, which does save the information but also disconnects you due to spam/unknown reason.

**Expected behaviour**: 
Clicking "Save Changes" on Guild Bank Information tab to save information.

**Server Revision**: 
3578

**Comment by danbopes** [comment]
Rev 3601
