### ISSUE TITLE
[Spell][Warlock] - Felguard stays summoned when unlearning talents while mounted

### ISSUE THREAD

**Issue by ghost** [Atlantiss/NetherwingBugtracker#7852]
**Description**:

I have unlearned my talents while I had a Felguard summoned and was mounted. After dismounting my Felguard was still summoned. Filling out a different talent tree had no effect. The Felguard persisted through a relog. 

![felguard](https://user-images.githubusercontent.com/31778748/103389467-42aa9400-4b0f-11eb-81fc-9e214d615ad5.png)

**Current behaviour**:

Felguard isn't despawned when unlearning talents while mounted.

**Expected behaviour**: 

Felguard despawns after unlearning talents.

**Server Revision**:

3578

**Comment by Wolffenstein** [comment]
Fixed in rev 3585.
