### ISSUE TITLE
[Spell][Shaman] Fire Elemental Totem

### ISSUE THREAD

**Issue by winter9596** [Atlantiss/NetherwingBugtracker#7854]
[//]: # (Enclose links to things related to the bug using http://wowhead.com or any other TBC database.)
[//]: # (You can use screenshot ingame to visual the issue.)
[//]: # (Write your tickets according to the format:)
[//]: # ([Quest][Azuremyst Isle] Red Snapper - Very Tasty!)
[//]: # ([NPC] Magistrix Erona)
[//]: # ([Spell][Mage] Fireball)
[//]: # ([Npc][Drop] Ghostclaw Lynx)
[//]: # ([Web] Armory doesnt work)
[//]: # (To find server revision type `.server info` command in the game chat.)

**Description**: 
If shaman's fire elemental totem hit the mobs first, no loot for shaman himself. 
**Current behaviour**:

**Expected behaviour**: 

**Server Revision**: 
3578

**Comment by Tereneckla** [comment]
No such thing happening. Only way to not get loot when the fire elemental attacks first is if you deal less than 50% of the damage yourself.
