### ISSUE TITLE
Nagrand Consortium vendors

### ISSUE THREAD

**Issue by aplouding** [Atlantiss/NetherwingBugtracker#7855]
[//]: # (Enclose links to things related to the bug using http://wowhead.com or any other TBC database.)
[//]: # (You can use screenshot ingame to visual the issue.)
[//]: # (Write your tickets according to the format:)
[//]: # ([Quest][Azuremyst Isle] Red Snapper - Very Tasty!)
[//]: # ([NPC] Magistrix Erona)
[//]: # ([Spell][Mage] Fireball)
[//]: # ([Npc][Drop] Ghostclaw Lynx)
[//]: # ([Web] Armory doesnt work)
[//]: # (To find server revision type `.server info` command in the game chat.)

**Description**: 
I believe there have to be multiple Consortium vendors in Nagrand camp. However I can't buy a single thing.
**Current behaviour**:
No Consortium vendors available for players on Alliance side in Nagrand. Not tested on Horde side.
**Expected behaviour**: 
There should be Paulsta'ats <Consortium Quartermaster>. He is available already from patch 2.2.0.7272.
**Server Revision**:

**Comment by Tereneckla** [comment]
It is patch 2.1
