### ISSUE TITLE
[2.4][Item] Rocket Boots are able to fail

### ISSUE THREAD

**Issue by Drainlock** [Atlantiss/NetherwingBugtracker#7856]
[//]: # (Enclose links to things related to the bug using http://wowhead.com or any other TBC database.)
[//]: # (You can use screenshot ingame to visual the issue.)
[//]: # (Write your tickets according to the format:)
[//]: # ([Quest][Azuremyst Isle] Red Snapper - Very Tasty!)
[//]: # ([NPC] Magistrix Erona)
[//]: # ([Spell][Mage] Fireball)
[//]: # ([Npc][Drop] Ghostclaw Lynx)
[//]: # ([Web] Armory doesnt work)
[//]: # (To find server revision type `.server info` command in the game chat.)

**Description**: 
When rocket boost where banned for arena they got buffed for open world and BGs
**Current behaviour**:
We cannot use rocket boots in arena, but they still can fail
![WoWScrnShot_010221_192741](https://user-images.githubusercontent.com/59121561/103462937-6f3df600-4d31-11eb-8ee3-000c343b1b2f.jpg)
**Expected behaviour**: 
[Rocket Boots Xtreme] and [Rocket Boots Xtreme Lite] can no longer be used in the arena. **These no longer have a failure chance.**
https://wowwiki.fandom.com/wiki/Patch_2.4.3
**Server Revision**: 
Tested on Netherwing where no .serv info command

**Comment by Wolffenstein** [comment]
Fixed in rev 3581.
