### ISSUE TITLE
[Quest][Desolace] Ghost-o-plasm Round Up

### ISSUE THREAD

**Issue by Wosser** [Atlantiss/NetherwingBugtracker#7858]
[//]: # (Enclose links to things related to the bug using http://wowhead.com or any other TBC database.)
[//]: # (You can use screenshot ingame to visual the issue.)
[//]: # (Write your tickets according to the format:)
[//]: # ([Quest][Azuremyst Isle] Red Snapper - Very Tasty!)
[//]: # ([NPC] Magistrix Erona)
[//]: # ([Spell][Mage] Fireball)
[//]: # ([Npc][Drop] Ghostclaw Lynx)
[//]: # ([Web] Armory doesnt work)
[//]: # (To find server revision type `.server info` command in the game chat.)

**Description**: 
Quest: https://tbcdb.com/?quest=6134
Mob: https://tbcdb.com/?npc=11560
**Current behaviour**:
after placing down the Crate, up to 15 of the Magrami Spectre spawn in a very short time (while you only need to kill 8 of them for the quest), making it impossible to pull less than 4 at once and the quest a pain in the ass
**Expected behaviour**: 
There should be one mob spawning about every 20 seconds.
**Server Revision**: 
3578

**Comment by Baelek** [comment]
For this quest, it is still bugged, but mobs should not spawn one at a time. A group of mobs should spawn at once in different areas and be neutral (not hostile) so that you can pick them off and attack them. Currently, the mobs spawn already being hostile. They instead should only become hostile once they reach the magnet.

**Comment by duzyizly** [comment]
They are spawing like crazy on classic aswell, this bug report seems incorrect.
https://youtu.be/BRQXbCJ8yjU?t=128

**Comment by sk6868** [comment]
this bug is definitely not fixed, and who cares if it's also happening in classic--a bug is a bug no matter where it is happening
