### ISSUE TITLE
Purified Jaggal Pearl jewelcrafting recipe not at trainer

### ISSUE THREAD

**Issue by Swjones92** [Atlantiss/NetherwingBugtracker#7859]
**Description**: 
Went to the Thrallmar and Aldor jewelcrafting trainers neither offered the recipe for Purified Jaggal Pearl

**Comment by Wosser** [comment]
https://tbcdb.com/?spell=41420 Stormspire

**Comment by Tereneckla** [comment]
NPCs in question are 18751 and 19063

**Comment by Wolffenstein** [comment]
Fixed in rev 3585.
