### ISSUE TITLE
[Npc][Drop] Random Item Grouproll

### ISSUE THREAD

**Issue by Needorfeed** [Atlantiss/NetherwingBugtracker#786]
**Description**: 
Wrong items being group-roll for errortext

**Current behaviour**:
When questing in group, some items will give the error "This item is still being rolled for", while it is a grey item.

**Expected behaviour**: 
Only green items and up should have the roll errortext, while the error text for items on a mob in group should not. Not sure what the actual text used to be, but there's no items being rolled for.

**Server Revision**:

**Comment by Easyfraggy** [comment]
Duplicate https://github.com/Atlantiss/NetherwingBugtracker/issues/12
