### ISSUE TITLE
([NPC] Raptor) Karazhan

### ISSUE THREAD

**Issue by mahkeemoh** [Atlantiss/NetherwingBugtracker#7861]
[//]: # (Enclose links to things related to the bug using http://wowhead.com or any other TBC database.)
[//]: # (You can use screenshot ingame to visual the issue.)
[//]: # (Write your tickets according to the format:)
[//]: # ([Quest][Azuremyst Isle] Red Snapper - Very Tasty!)
[//]: # ([NPC] Magistrix Erona)
[//]: # ([Spell][Mage] Fireball)
[//]: # ([Npc][Drop] Ghostclaw Lynx)
[//]: # ([Web] Armory doesnt work)
[//]: # (To find server revision type `.server info` command in the game chat.)

**Description**: Pet Raptor missing active abilites(e.g. Claw).

**Current behaviour**: Ability doesn't exist

**Expected behaviour**: Pet has abilities

**Server Revision**:

**Comment by Tereneckla** [comment]
You have to teach them the abilities.
Raptors don't start with many skills
http://web.archive.org/web/20070406193220/http://petopia.brashendeavors.net/html/families/family_raptor.shtml

**Comment by mahkeemoh** [comment]
My raptor is already level 39 and the Pet Trainer does not have the
abilities. When tamed, it had Growl and never learned other active skills.

**Comment by Tereneckla** [comment]
As written somewhere else on the site I linked, you learn skills like Bite, Claw, Gore, etc by taming a pet that has it and using that pet until you can teach it.
