### ISSUE TITLE
[Item][Warlock] Band of Eternal Sage Won't Proc From DoT Casts

### ISSUE THREAD

**Issue by Fierywind** [Atlantiss/NetherwingBugtracker#7862]
**Description**: Band of eternal sage is not proccing from dot casts. I cast Curse of Agony and Corruption about 100 times on a wolf outside Shatt with not a single proc, meanwhile it procced on my third sbolt.

**Current behaviour**: Band of Eternal sage is not proccing from the cast of dots.

**Expected behaviour**: It should have a chance to proc when any offensive spell is cast, including dots.

**Server Revision**: 3578

**Comment by Wolffenstein** [comment]
Fixed in rev 3585.
