### ISSUE TITLE
Oil Covered Fish

### ISSUE THREAD

**Issue by kirinha** [Atlantiss/NetherwingBugtracker#7863]
[//]: # (Enclose links to things related to the bug using http://wowhead.com or any other TBC database.)
[//]: # (You can use screenshot ingame to visual the issue.)
[//]: # (Write your tickets according to the format:)
[//]: # ([Quest][Azuremyst Isle] Red Snapper - Very Tasty!)
[//]: # ([NPC] Magistrix Erona)
[//]: # ([Spell][Mage] Fireball)
[//]: # ([Npc][Drop] Ghostclaw Lynx)
[//]: # ([Web] Armory doesnt work)
[//]: # (To find server revision type `.server info` command in the game chat.)

**Description**: Schools of fish containing Oil Covered Fish.

**Current behaviour**: Whenever fishing in pools like Firefin Snapper, Oily Blackmouth, etc, I keep looting "Oil Covered Fish" (item=6458) every other cast. 

**Expected behaviour**: Oil Covered Fish is a fish that drops off of Gahz'ranka in Zul'Gurub and is not supposed to be fished up in any fishing pools or lakes/oceans, to my knowledge.

**Server Revision**:

**Comment by Wolffenstein** [comment]
Fixed in rev 3585.
