### ISSUE TITLE
Quest Earthen Templar can`t be complete - location Silithus

### ISSUE THREAD

**Issue by annthi** [Atlantiss/NetherwingBugtracker#7864]
[//]: # (Enclose links to things related to the bug using http://wowhead.com or any other TBC database.)
[//]: # (You can use screenshot ingame to visual the issue.)
[//]: # (Write your tickets according to the format:)
[//]: # ([Quest][Azuremyst Isle] Red Snapper - Very Tasty!)
[//]: # ([NPC] Magistrix Erona)
[//]: # ([Spell][Mage] Fireball)
[//]: # ([Npc][Drop] Ghostclaw Lynx)
[//]: # ([Web] Armory doesnt work)
[//]: # (To find server revision type `.server info` command in the game chat.)

**Description**: To summon Crimson Templar you have to loot three items from nearby cultists: Twilight Cultist Cowl, Twilight Cultist Mantle, Twilight Cultist Robe. If use you'll be look as cultist (there three buff icons will be added), to interacting Lesser wind stone

**Current behaviour**: After wearing Twilight Cultist Cowl, Twilight Cultist Mantle, Twilight Cultist Robe no buffs added at all and no Lesser wind stone can be found in Silithus

**Expected behaviour**: After looting three items -Twilight Cultist Cowl, Twilight Cultist Mantle, Twilight Cultist Robe, there three buff icons will be added to interacting with Lesser wind stone to summon Crimson Templar

**Server Revision**: 3578

**Comment by Tereneckla** [comment]
They're not respawning, see #6467
