### ISSUE TITLE
Hunter Survival Talent - Master Tactician

### ISSUE THREAD

**Issue by justinforest1337** [Atlantiss/NetherwingBugtracker#7866]
[//]: # (34839) https://www.wowhead.com/spell=34839/master-tactician

**Description**: Master Tactician talent from survival spec , is not working at all.  you can not skip becouse its linked to Readiness talent wich is last one from Survival tree.

**Current behaviour**:  Master tactician 5/5 is not proc.

**Expected behaviour**: 6% chance to increase critical strike by 10% 

**Server Revision**:  Atlantiss Karazhan realm

**Comment by Tereneckla** [comment]
It is proccing
