### ISSUE TITLE
Goretusk Rushing charge double damage

### ISSUE THREAD

**Issue by themrbluestar** [Atlantiss/NetherwingBugtracker#7867]
[//]: # (Enclose links to things related to the bug using http://wowhead.com or any other TBC database.)
[//]: # (You can use screenshot ingame to visual the issue.)
[//]: # (Write your tickets according to the format:)
[//]: # ([Quest][Azuremyst Isle] Red Snapper - Very Tasty!)
[//]: # ([NPC] Magistrix Erona)
[//]: # ([Spell][Mage] Fireball)
[//]: # ([Npc][Drop] Ghostclaw Lynx)
[//]: # ([Web] Armory doesnt work)
[//]: # (To find server revision type `.server info` command in the game chat.)

**Description**: 
(NPC) Goretusk
(Spell) Rushing Charge: https://www.wowhead.com/spell=6268/rushing-charge
**Current behaviour**:
When a priest uses power word shield against the Rushing Charge ability, the buff remains on the Goretusk after the initial damage absorption. This causes the Goretusk to hit twice for the increased damage value.
**Expected behaviour**: 
When an absorb shield is present and the charge damage it absorbed the spell buff should expire from the Goretusk.
**Server Revision**:

**Comment by Wolffenstein** [comment]
Fixed in rev 3585.
