### ISSUE TITLE
[Spell][Priest] - Psychic Scream fails - "is refreshed" in combat log

### ISSUE THREAD

**Issue by kemotix** [Atlantiss/NetherwingBugtracker#7868]
Video link: https://www.youtube.com/watch?v=XdFwuu_2aFU - 0:40 or 18:21:32 in combat log time stamp
Screenshoot: https://i.imgur.com/3bOR65K.png

As seen on the video previous fear was casted more than 30 seconds ago yet it fails with incomprehensible message for me.
Asked on the discord - no luck. Google wasn't helpful either.
So I guess it may be some 

serious bug.

**Server Revision**: 
No idea, recorded 04.01.2021

**Comment by raethkcj** [comment]
"Not yet recovered" is the message you get when you mash the button after it's on cooldown or on GCD. You successfully cast the fear, so it goes on cooldown, but you mashed the button so you got a "Not yet recovered" message. This message has nothing to do with the rogue breaking the fear.

"is refreshed" is the message you get every single time a buff/debuff is applied. In this case it means your fear *is successful*.

To be clear, I'm not sure how the rogue instantly broke the fear, but these messages are not related to it.

**Comment by kemotix** [comment]
I know "not yet recovered", it fine and clear :)

When fear is successful combat log says:
"Ironspine Petrifier's Psychic Scream is refreshed. 
Ironspine Petrifier is afflicted by Psychic Scream."

In reported situation "is refreshed" is logged twice, there's no info line sating "is afflicted"

What's more when fear is broken combat log says "Psychic Scream dissipates from <player>"

Checked original video once again, there's no message like that.

**Comment by Wolffenstein** [comment]
Combat log message has nothing to do with this. Fear was applied and broke almost instantly due to damage (very low chance given how little damage was done in that short timespan but can happen if you're extremely unlucky).
