### ISSUE TITLE
 [TrinketBug] Cooldown Bug

### ISSUE THREAD

**Issue by yzjstc2002** [Atlantiss/NetherwingBugtracker#7869]
[Xi'ri's Gift] https://tbc-twinhead.twinstar.cz/?item=29132
[Scryer's Bloodgem] https://tbc-twinhead.twinstar.cz/?item=29179

**Description**: The two trinkets  [Xi'ri's Gift]  and [Scryer's Bloodgem] share same cd which should not be on retail.
The cd stated here not refer to the 15 sec public cd for all trinkets. But the item cd of themselves which are usually be 1min30sec.
I have found the similar problem when playing a rogue before. This time two other trinkets shared cd which should have not be.  They are:
[Bladefist's Breadth] https://tbc-twinhead.twinstar.cz/?item=28041
[Ancient Draenei War Talisman] https://tbc-twinhead.twinstar.cz/?item=31617

It looks like this will happen whenever two trinkets have same trigger spell power or attack power.

I have sent a ticket in game and the GM acknowledged this bug and needs to be published here.

**Current behaviour**: sharing cd

**Expected behaviour**: not sharing cd

**Server Revision**: Karazhan

**Comment by Godmatik** [comment]
Duplicate.

https://github.com/Atlantiss/NetherwingBugtracker/issues/7446

**Comment by Wolffenstein** [comment]
Fixed in rev 3585.
