### ISSUE TITLE
[Spell] Mind Control issues.

### ISSUE THREAD

**Issue by Jezofine** [Atlantiss/NetherwingBugtracker#787]
**Current behaviour**:
If you Mind Control enemy and start attacking another enemy, after MC ends non-mindcontrolled enemy might still use CC spells on mindcontrolled enemy.
[Video](https://youtu.be/CAHyD9V2QeI)
Battle Lord is still flagged as enemy for Wind Chaser after MC ends?

Also:
1. When you start attack with MCed mob (by right click for example) mob completely stops going forward and you can move only left-right until press "Move forward" again.
~~2. [Meelee NPC often stuck in place](https://youtu.be/LITCDZjL95Y) after MC, happens in different places. They stand still until you unleash them.~~
3. If you attack enemy with MCed NPC's ranged spell or shot, enemy starts attacking you, not MCed mob that attacked him.
4. MC channeling buff disappears from buff panel and the only way to break MC willingly is to try another cast.
5. Some warrior NPC abilities of MCed creatures seem not working: 
- "next meelee" ailities: Heroic Strike on Kolkar Battle Lord (id 4636) and Execute on Kolkar Destroyer (4637) for example), they don't use them even without MC, maybe should make separate issue;
- Battle Stance often does not active (maybe 3 min cooldown is not indicated properly)
6. You can loot mobs that you killed with only MCed npc damage.
7. Some abilities on MCed mobs (like Shoot, Shield Bash, Earthgrab Totem) have no cooldown. Possibly applies to all mobs with such abilities. Although "Throw" works as intented, with correct cooldown.
8. You can summon multiple totems ([Skullsplitter Witch Doctor's totems](https://www.youtube.com/watch?v=sKQd-utgpSE&feature=youtu.be)).
9. You can MC hunter npc with summon pet ability, summon new pet and it will become your pet, but without any abilities, If you summon pet, you cannot use MCed mob's abilities anymore cause it's action bar gets replaced with player's standard bar.
![2018-10-01_23-34-16](https://user-images.githubusercontent.com/2833746/46308611-8e3e0280-c5d3-11e8-9ca0-89cfe7b31048.jpg)

2 more from [this video](https://www.youtube.com/watch?v=mlPpmylq6qY):
1. I gain weapon skill points from using MCed npc's attacks and abilities (Thrash, for example)
2. Sometimes after using MC 2nd time I cannot attack mob that I was attacking before losing MC, until I attack another mob.

**Expected behaviour**:
Friends don't hurt friends.

From [Mind Control tips](http://wowwiki.wikia.com/wiki/Mind_Control) (could not find source in patch notes).
>Mobs must take damage from players in order to generate loot; should they be killed solely by a Mind Controlled mob they will drop no items. In addition, a Mind Controlled mob will generate no loot if it dies while still MCed; it must be released if you wish to take its items. 

**Server Revision**: 2105

**Comment by Jezofine** [comment]
Also meelee NPC often stuck in place after MC, happens in different places. They stand still until you unleash them.
[NPC stuck after MC](https://youtu.be/LITCDZjL95Y)

**Comment by Wolffenstein** [comment]
2. fixed in rev 2077.

**Comment by Easyfraggy** [comment]
I've crossed out the part that was fixed - just remove ~~ infront and after and comment below if it still bugs out after you re-test!

**Comment by mr2tal** [comment]
Another issue with mindcontrol, is that retaliation does damage to priest instead of mindcontrolled target: https://clips.twitch.tv/SincereHorribleSquirrelDeIlluminati

**Comment by Wolffenstein** [comment]
Fixed in rev 2262 (all of it I think).

**Comment by Jezofine** [comment]
Looks like these are all fixed, however there is some interactions between MCed and non-MCed npcs which I'm suspicious about, but not sure if they are bugs:
1. When you drop MC all mobs, except for MCed one, evade. Shouldn't they all agro onto priest?
2. When I MC npc with pet sometimes pet starts attacking immediately, sometimes not. About 50/50.
