### ISSUE TITLE
[Quest][Dissencion amongst the ranks] bug quest

### ISSUE THREAD

**Issue by Aramdel22** [Atlantiss/NetherwingBugtracker#7870]
[//]: # (Enclose links to things related to the bug using http://wowhead.com or any other TBC database.)
[//]: # (You can use screenshot ingame to visual the issue.)
[//]: # (Write your tickets according to the format:)
[//]: # ([Quest][Azuremyst Isle] Red Snapper - Very Tasty!)
[//]: # ([NPC] Magistrix Erona)
[//]: # ([Spell][Mage] Fireball)
[//]: # ([Npc][Drop] Ghostclaw Lynx)
[//]: # ([Web] Armory doesnt work)
[//]: # (To find server revision type `.server info` command in the game chat.)

**Description**: This quest asks me to kill 5 elite mobs in the shadowsmoon valley area using a tabard to disguise myself as a blood elgo and thus be able to kill these mobs, however when I use the tabard I disguise myself and kill the mobs the game does not count me deaths, please check this quest

**Current behaviour**: bug 

**Expected behaviour**: 

**Server Revision**: karazhan

**Comment by Wolffenstein** [comment]
It works fine. Make sure you're not doing it while in a raid. You might also try unequipping and equipping back the tabard to make sure the necessary aura is present on you.
