### ISSUE TITLE
[Profession] [Herbalism] Nodes are severely lacking / Respawn rates are too low (Karazhan)

### ISSUE THREAD

**Issue by Skengyute** [Atlantiss/NetherwingBugtracker#7872]
**Description:**
The herb nodes are too few and far between, and respawn rates are too low given the server population. The amount of time spent traipsing around looking for low level herbs is wasteful and a hindrance to progression. 

**Current behaviour**
I have been levelling alchemy along with herbalism and have been getting very few briarthorn (about 3-4 per hour) in the most popular zones (Silverpine, Duskwood, etc). This has been an issue from the beginning (very low level herbs). I am using the gatherer addon to track the nodes.

The same goes for Liferoot which I have just begun farming. It should be noted that there are also very few players in the zones I have been farming in for both herbs.

There were 1550 players on this morning when I was farming Briarthorn, there are 2320 as of now, after I gave up on Liferoot.

**Expected behaviour:**
There should be higher respawn rates for vanilla herbs and the rates should increase to suit the fluctuation in server population.

**Comment by Godmatik** [comment]
Confirmed, vanilla herb spawn rate is lower than it should be, but this problem has been around for years now, since Netherwing.

**Comment by Wolffenstein** [comment]
The number was increased at the start of Karazhan but it was way too much so it was tuned down (still to higher numbers than on Netherwing). I will increase it a bit in rev 3588.
