### ISSUE TITLE
[Spell][Hunter] Mend Pet

### ISSUE THREAD

**Issue by mrjsj** [Atlantiss/NetherwingBugtracker#7873]
[//]: # (Enclose links to things related to the bug using http://wowhead.com or any other TBC database.)
[//]: # (You can use screenshot ingame to visual the issue.)
[//]: # (Write your tickets according to the format:)
[//]: # ([Quest][Azuremyst Isle] Red Snapper - Very Tasty!)
[//]: # ([NPC] Magistrix Erona)
[//]: # ([Spell][Mage] Fireball)
[//]: # ([Npc][Drop] Ghostclaw Lynx)
[//]: # ([Web] Armory doesnt work)
[//]: # (To find server revision type `.server info` command in the game chat.)

**Description**: 
Mend Pet is currently scaling with bonus healing effects. The scaling was removed in 2.1.
https://wowwiki.fandom.com/wiki/Patch_2.1.0#Improved_mend_pet_changes

**Current behaviour**:
Mend Pet is scaling 100% (over the duration) or 20% per tick with healing power. 

**Expected behaviour**: 
Mend Pet should not scale with healing power.

**Server Revision**: 
3578

**Comment by Godmatik** [comment]
Yep confirmed, some hunters are stacking +healing on a couple fights to keep their pet alive.

**Comment by Wolffenstein** [comment]
Fixed in rev 3587.
