### ISSUE TITLE
[Item][Band of the Eternal Defender] - Proc chance not working properly

### ISSUE THREAD

**Issue by cbarzotti** [Atlantiss/NetherwingBugtracker#7874]
[Item][<a href="https://tbcdb.com/?item=29297">Band of the Eternal Defender </a>]

**Description**: 
The proc chance of the item seems to be incorrect. 

**Current behaviour**:
I was in MH as a prot paladin last night and in a 3 hours raid, it never procced. It was always equiped, I have a WA to track it and I double checked the logs to see. Seems like I never got a proc ( <a href="https://legacyplayers.com/Raids/Viewer/?data=I5LTG6TBOR2FIN3UO5KHIWSEPBXGYQ2IGFHWUMLQNNHTM5RSMVUVKZCOLJGEM6SWKV4WQSRZKRITQYKXK5LVOZLBFNZGYODMJ44FINRQNZVXSWSWJNMWE6STNRWDGU3FKZ3TG22LJBVGI2S2OJDHMWLOJNFGOTKVKNBTMZLNGVTGYVKCIN3E2VDRIE4UWWSXNNDGKM2BN5MS6RLSIJETSRKMO54XGUTBNY3GESLULJTFA2SBGBDXAVLTGR5GGMKDMJAW2OLTGFLXA6SBJE2FC4SZIQZVOY2EIUZGUVTWNN5HUZTWMNWQ">Check under "Aura Gained" for reference </a>).
I checked the logs of other Prot Paladins, and talked to a few of them in game as well, and seems like a common issue.

**Expected behaviour**: 
I don't know the exact proc rate, for the comments I saw around should be pretty high, with and ICD of about 45 sec starting after the debuff expire.

I don't know if that can help, but I saw a comment stating
"The effect doesn't stack with scroll of protection, so the scroll-buff is completely removed when the ring proccs. Be aware of that."
I am using those scrolls myself, and other pallyes are from time to time. Don't know if that is relevant or not. I was speculating it was either that or the "struck in combat" part working only if you get a full hit without any reduction/mitigation.

**Server Revision**: 
Atlantiss Karazhan | Content patch: 2.1.0 | Revision: 3586

**Comment by Wolffenstein** [comment]
It only has 3% chance to proc but currently it requires you to actually sustain damage (doesn't trigger with full mitigation). I don't believe that's correct since it causes the item to proc a lot less than expected, so starting from rev. 3589 it will be possible to proc it even when the melee attack caused no damage (miss/dodge/parry/block/etc.).
