### ISSUE TITLE
[Mind Control][Priest] Target can't be charmed

### ISSUE THREAD

**Issue by marcinkroszel** [Atlantiss/NetherwingBugtracker#7875]
**Description**: 
A target can't be charmed
![WoWScrnShot_011521_233426](https://user-images.githubusercontent.com/55636544/104785857-daed7d80-578b-11eb-9154-52f1cd67cb52.jpg)

**Current behavior**:
I couldn't mind control an enemy from the opposite faction
I didn't work neither on priest, neither on druid in humanoid form, neither on hunter.

**Expected behavior**: 
I should be able to mind control the enemy

**Server Revision**: 
3586

**Comment by Wolffenstein** [comment]
Fixed in rev 3587.
