### ISSUE TITLE
Fear and Root debuff causes problems

### ISSUE THREAD

**Issue by fixbugplez** [Atlantiss/NetherwingBugtracker#7877]
****Description**:** 
After 'fear' effect ends, _you temporarily get immobilized._. for example warlock 'fear'
After 'root' effect ends, _any spells you were casting are interrupted_. for example druid 'entangling roots' or mage 'frost nova'

****Expected behaviour**:** 
no immobilization after fear, no interrupt when casting spell as root effect ends.

i dont think screenshot/video is necessary. its very easy to replicate

**Comment by Weuyn** [comment]
its because the root raises you a little into the air, its very funny

**Comment by fixbugplez** [comment]
> its because the root raises you a little into the air, its very funny

seems like a logical explanation, but that's not how I remember the bug functioning. anyway...

you're telling me that after 2 years that the bug isn't fixed? kinda cringe. Had a bad feeling about that server, very glad I left 2 days after making this bug report.

**Comment by tsu-1** [comment]
https://github.com/Atlantiss/NetherwingBugtracker/issues/6914

**Comment by tsu-1** [comment]
@Wolffenstein #6914 #4026

Clip of it happening provided by Werwood:

https://youtu.be/V0oeKgF_838

**Comment by Godmatik** [comment]
Unable to reproduce - must have been fixed at some point.
When roots expire, the cast is not interrupted
