### ISSUE TITLE
[Spell] [Warlock] Death Coil - Curse of Recklessness Causing Immunity To Leech

### ISSUE THREAD

**Issue by F4play** [Atlantiss/NetherwingBugtracker#7878]
This is a continuation of a previously closed bug report here - https://github.com/Atlantiss/NetherwingBugtracker/issues/7842

It seems when Curse of Recklessness is on any mob, the mob immunes the leech component of death coil.

So I took two videos: 

1. With Curse of Recklessness Applied: https://www.youtube.com/watch?v=CXRPKiuPSYU&feature=youtu.be
2. Without: https://www.youtube.com/watch?v=K8DVjYTQ9b4

Now, to verify that this is a bug, here's a clip from classic showing that the leech component should still go through when curse of reck is applied to an enemy.

Classic Clip: https://clips.twitch.tv/EphemeralAthleticHorsePermaSmug

**Comment by Wolffenstein** [comment]
Fixed in rev 3587.
