### ISSUE TITLE
[Quest][Repeatable][Felwood] Corrupted Windblossom

### ISSUE THREAD

**Issue by Napolarbear** [Atlantiss/NetherwingBugtracker#7879]
https://classic.wowhead.com/quest=996/corrupted-windblossom

When trying to do the repeatable quest, the Corrupted Windblossom disappears when applying the Cenarian Plant Salve, but a Cleansed Windblossom never appears, wasting the salve. This happens at different nodes, and I waited for 5 or so minutes and it never appeared, so I could not receive Windblossom Berries.

**Comment by Ildsint** [comment]
It's the same for the other plant types aswell. Whipper Roots was a little more forthcoming, but the Night Dragon was a real nightmare

**Comment by tsu-1** [comment]
Related: https://github.com/Atlantiss/NetherwingBugtracker/issues/7889

**Comment by Godmatik** [comment]
Duplicate #8359
