### ISSUE TITLE
[Quest][Ghostlands] Dealing with Zeb'Sora!

### ISSUE THREAD

**Issue by jacerm** [Atlantiss/NetherwingBugtracker#788]
**Description**: Drop rate seems to be low.

**Current behaviour**: Have gottne 1 in about ~12 kills

**Expected behaviour**: https://tbc-twinhead.twinstar.cz/?item=22639 states it should be about 36% drop rate.

**Server Revision**:

**Comment by aresbrutus** [comment]
You have just gotten unlucky, the drop rates are correct.
