### ISSUE TITLE
My pet (cat) dont run, just walk like his prowling whole time, also when i send him to attack, i can fix this issue when i dismiss the pet and call back, but the bug/glitch came again everytime i mount, the cat just dont run. I tamed this Elite White Lion "Siam Rotam", by the quest "Shy Rotam" at Winterspring where you need to summon them if this info helps. I got a Serpent Wind and a Ravager, but i really want to use this lion. Thanks on advice.

### ISSUE THREAD

**Issue by Asobin1903** [Atlantiss/NetherwingBugtracker#7880]
[//]: # (Enclose links to things related to the bug using http://wowhead.com or any other TBC database.)
[//]: # (You can use screenshot ingame to visual the issue.)
[//]: # (Write your tickets according to the format:)
[//]: # ([Quest][Azuremyst Isle] Red Snapper - Very Tasty!)
[//]: # ([NPC] Magistrix Erona)
[//]: # ([Spell][Mage] Fireball)
[//]: # ([Npc][Drop] Ghostclaw Lynx)
[//]: # ([Web] Armory doesnt work)
[//]: # (To find server revision type `.server info` command in the game chat.)

**Description**: 

**Current behaviour**:

**Expected behaviour**: 

**Server Revision**:

**Comment by Godmatik** [comment]
Longest bug report title ever lol

**Comment by MecAtlantiss** [comment]
It is important to me that this bug report not be closed or altered in any way.

**Comment by Asobin1903** [comment]
bug still on
