### ISSUE TITLE
Wrath Priestesses not dropping Freshly Drawn Blood to summon Sathal for Against the Legion

### ISSUE THREAD

**Issue by shawn571** [Atlantiss/NetherwingBugtracker#7881]
[//]: # (Enclose links to things related to the bug using http://wowhead.com or any other TBC database.)
[//]: # (You can use screenshot ingame to visual the issue.)
[//]: # (Write your tickets according to the format:)
[//]: # ([Quest][Azuremyst Isle] Red Snapper - Very Tasty!)
[//]: # ([NPC] Magistrix Erona)
[//]: # ([Spell][Mage] Fireball)
[//]: # ([Npc][Drop] Ghostclaw Lynx)
[//]: # ([Web] Armory doesnt work)
[//]: # (To find server revision type `.server info` command in the game chat.)

**Description**: 
When on the quest ([Quest][Nagrand] Against the Legion), ([NPC] Wrath Priestess) should drop ([Npc][Drop] Freshly Drawn Blood) to allow for the summoning of Sathal.
(https://www.wowhead.com/item=30850/freshly-drawn-blood)

**Current behaviour**:
Currently the Freshly Drawn blood does not drop from Wrath Priestesses even while on the quest.

**Expected behaviour**: 
Freshly Drawn Blood should have 100% drop rate off Wrath Priestesses while on the quest Against the Legion.

**Server Revision**: 
3586

**Comment by shawn571** [comment]
Editing to add that the blood finally did drop after about 10 kills, but I'm pretty sure it should be 100%?

**Comment by therealCrysis** [comment]
You are wrong, friend. It was never 100% on retail. it was less than 40%.
It's above 25% here so it works correctly.
