### ISSUE TITLE
[Spell][Warlock] Inferno - Unlimited Range Infernal Enslave Bug

### ISSUE THREAD

**Issue by F4play** [Atlantiss/NetherwingBugtracker#7882]
**Current behaviour**:

Enslave has unlimited range, allowing infernals to be safely used in encounters such as Archimonde, Kalecgos, etc.

Video: https://www.youtube.com/watch?v=9NQsTk7OnGY&feature=youtu.be

**Expected behaviour**: 

Enslavement should drop once the caster and infernal are separated more than 100yds. Infernal should run and attack caster once enslavement is broken. 

Enslave Demon Range: https://web.archive.org/web/20080919235837/http://thottbot.com/s20882

**Server Revision**: 3586

Original EJ thread that prompted this
<img width="1414" alt="Screen Shot 2021-01-19 at 10 42 54 AM" src="https://user-images.githubusercontent.com/41980757/105111933-d6b8ad00-5a76-11eb-902f-69d93af51ec4.png">

**Comment by F4play** [comment]
Still bugged

**Comment by Godmatik** [comment]
Was fixed when 100 yard pet leasing was implemented, can close
