### ISSUE TITLE
Character turns invisible

### ISSUE THREAD

**Issue by ASRoux** [Atlantiss/NetherwingBugtracker#7883]
[//]: # (Enclose links to things related to the bug using http://wowhead.com or any other TBC database.)
[//]: # (You can use screenshot ingame to visual the issue.)
[//]: # (Write your tickets according to the format:)
[//]: # ([Quest][Azuremyst Isle] Red Snapper - Very Tasty!)
[//]: # ([NPC] Magistrix Erona)
[//]: # ([Spell][Mage] Fireball)
[//]: # ([Npc][Drop] Ghostclaw Lynx)
[//]: # ([Web] Armory doesnt work)
[//]: # (To find server revision type `.server info` command in the game chat.)

**Description**: Character turns invisible.

**Current behaviour**: When I'm walking in certain locations (Northshire, Stormwind, Mines etc.) my character alternates between invisible and visible at random.

**Expected behaviour**: My character should stay visible.

**Server Revision**: 3596

**Comment by ASRoux** [comment]
Looks like it isn't just Northshire, I'm turning invisible in Echo Ridge Mine and Goldshire Inn as well.

**Comment by Godmatik** [comment]
It's a client issue, don't think it can be fixed.

**Comment by EtheriousNW** [comment]
Indeed a client issue.
