### ISSUE TITLE
Quick respawn for Porcine Entourage.

### ISSUE THREAD

**Issue by ASRoux** [Atlantiss/NetherwingBugtracker#7884]
[//]: # (Enclose links to things related to the bug using http://wowhead.com or any other TBC database.)
[//]: # (You can use screenshot ingame to visual the issue.)
[//]: # (Write your tickets according to the format:)
[//]: # ([Quest][Azuremyst Isle] Red Snapper - Very Tasty!)
[//]: # ([NPC] Magistrix Erona)
[//]: # ([Spell][Mage] Fireball)
[//]: # ([Npc][Drop] Ghostclaw Lynx)
[//]: # ([Web] Armory doesnt work)
[//]: # (To find server revision type `.server info` command in the game chat.)

**Description**: The Porcine Entourage that Princess has at Brackwell Pumpkin Patch respawn too quickly.

**Current behaviour**: It isn't even 2 seconds from me killing a Porcine Entourage that another one respawns.

**Expected behaviour**: When you kill a Porcine Entourage, they need to stay dead longer and not respawn too quickly.

**Server Revision**: 3596

**Comment by danbopes** [comment]
@Tereneckla Can you confirm on live if this is how it works?

**Comment by Tereneckla** [comment]
Yes, the entourage respawns while you still are in combat with the princess immediately aggroing you

**Comment by danbopes** [comment]
How long should they take to respawn @Tereneckla ?

**Comment by Tereneckla** [comment]
Can you just tie their respawn to Princess? Her timer is just a few seconds
Or make them not respawn when Princess is in combat?
