### ISSUE TITLE
Paladin, "Blessing"

### ISSUE THREAD

**Issue by Vladyslav9777** [Atlantiss/NetherwingBugtracker#7885]
[//]: # (Enclose links to things related to the bug using http://wowhead.com or any other TBC database.)
[//]: # (You can use screenshot ingame to visual the issue.)
[//]: # (Write your tickets according to the format:)
[//]: # ([Quest][Azuremyst Isle] Red Snapper - Very Tasty!)
[//]: # ([NPC] Magistrix Erona)
[//]: # ([Spell][Mage] Fireball)
[//]: # ([Npc][Drop] Ghostclaw Lynx)
[//]: # ([Web] Armory doesnt work)
[//]: # (To find server revision type `.server info` command in the game chat.)

**Description**: 

**Current behaviour**:

**Expected behaviour**: 

**Server Revision**: 
Hello, i found a broblem with the ability of the paladins.
When i use "Blessing of Freedom", that "Blessing of Might", "Blessing of wisdom" and other - gets out.
It should not be, this it a separate type of ability, despite the fact that it is also "Blessing"

**Comment by Vladyslav9777** [comment]
Hello, i found a broblem with the ability of the paladins.
When i use "Blessing of Freedom", that "Blessing of Might", "Blessing of wisdom" and other - gets out.
It should not be, this it a separate type of ability, despite the fact that it is also "Blessing"

**Comment by Tereneckla** [comment]
It is a blessing

**Comment by Vladyslav9777** [comment]
> Это благословение

"Blessing of Freedom" should not interfere with other Blessing.
check

**Comment by Godmatik** [comment]
You are thinking of wrath of the lich king, this is TBC.

A person can only have one blessing on them at a time from one paladin. That includes blessing of freedom, blessing of protection, etc.

In Wrath, it was changed to HAND of Freedom, so that you could use freedom on someone and they wouldn't lose their might buff or whatever.

**Comment by Godmatik** [comment]
TBC version: https://tbc-twinhead.twinstar.cz/?spell=1044
**Players may only have one Blessing on them per Paladin at any one time.**

WotLK version: https://wotlk-twinhead.twinstar.cz/?spell=1044
