### ISSUE TITLE
Impale Talent for Warriors dont Suffer 20% extra crit Damage

### ISSUE THREAD

**Issue by Hogosh81** [Atlantiss/NetherwingBugtracker#7886]
The title says all.
The Talent in the Arms tree to make 20% more Damage with a Crit dont work correctly, you will only get the normal 100%, not the 20% extra

**Comment by raethkcj** [comment]
This talent only  applies to *abilities*, e.g. Heroic Strike, not your regular white melee attacks.

**Comment by Godmatik** [comment]
It works fine

**Comment by Hogosh81** [comment]
then, why shield slam, Devastate and Revenge dont suffer the 20% extra Damage on Crits?

**Comment by Godmatik** [comment]
It certainly does increase the critical strike damage done by those abilities of 20%.

You need to provide proof that it does not.

**Comment by Hogosh81** [comment]
try it one more time,
revenge without 660 (with impale around the same)
Shield Slam 1000 (with Impale the same)
Devastate 500 (with Impale the same)

you can write me ingame Hogosha, and we can make duells to test it out

**Comment by Wolffenstein** [comment]
It should be working fine from what I can see in the codebase and the database. Please test properly in game and reopen with evidence if it's indeed bugged.
