### ISSUE TITLE
Shartuul’s Transporter event

### ISSUE THREAD

**Issue by Frostages** [Atlantiss/NetherwingBugtracker#7887]
Phase 2 (The Doomguard):
if u use “Super Jump” skill, some mobs will just disappear and won’t attack u. They’re still there, but u can find them only with “target” function.

Phase 3 ( The Shivan Assassin):
- Sometimes you’re unable to use skillbar

**Comment by Shineslippers** [comment]
Up! 2024 is already here...

Phase 2
[Gan'arg Underling](https://www.wowhead.com/tbc/npc=23199/ganarg-underling#comments) has tendency to evade after spawn. Player can cast stun on it or just run out and they will return to spawn spot.

Phase 4
[Dreadmaw](https://www.wowhead.com/tbc/npc=23275/dreadmaw) always outrun a player. More stack he is getting - faster running. You just can't keep him on distance. On top of it after charge he is no apply [Lacerating Bite](https://www.wowhead.com/tbc/spell=41940/lacerating-bite)

Other
[Shivan Assassin](https://www.wowhead.com/tbc/npc=23220/shivan-assassin) spell [Death Blast](https://www.wowhead.com/tbc/spell=40736/death-blast) doesn't work properly. It's convert only initial damage into healing. Doesn't matter how long debuff is active on target healing always the same.
I don't know is it correct or not but seems very odd that a player can cast abilities on all of those demons. You can Fear it, apply Curse of Tongues and other debuffs. That makes whole event itrrelevant.

**Comment by Godmatik** [comment]
Closing - consolidating all information into one thread
