### ISSUE TITLE
[Quest][Repeatable][Felwood] Corrupted Night Dragon

### ISSUE THREAD

**Issue by Blep90** [Atlantiss/NetherwingBugtracker#7889]
[//]: # (Enclose links to things related to the bug using http://wowhead.com or any other TBC database.)

**Description**: I tried to complete the repeatable quest [Corrupted Night Dragon](https://tbc-twinhead.twinstar.cz/?quest=4119) using [Cenarion Plant Salve](https://tbc-twinhead.twinstar.cz/?item=11516) x4 at 3 different sites in Felwood. I did this in order to create [Cleansed Night Dragon](https://tbc-twinhead.twinstar.cz/?object=164881) from which [Night Dragon's Breath](https://tbc-twinhead.twinstar.cz/?item=11952)s are supposed to be collected (3-10 can be collected each time a player cleanses a Corrupted Night Dragon).

To be clear, I used 20 Cenarion Plant Salves altogether. These were used in 5 separate cleansings across 3 different sites.

**Current behaviour**: The Corrupted Night Dragons were cleansable, but they did not spawn Cleansed Night Dragons after I completed the repeatable quest.

**Expected behaviour**:  Cleansed Night Dragons are supposed to spawn as objects the player can interact with. Players are supposed to be able to collect 3 to 10 Night Dragon's Breaths from each Cleansed Night Dragon.

**Comment by Ildsint** [comment]
Had exactly the same experience. Running circles around felwood with exactly nothing to show for it.

**Comment by KrystalWoW** [comment]
Confirmed via WoWhead WoWClassic:
https://classic.wowhead.com/item=11952/night-dragons-breath#comments
![2021-03-08 08_45_02-Night Dragon's Breath](https://user-images.githubusercontent.com/80262401/110329418-8bd50380-7fea-11eb-8a14-2e3f35588357.png)

**Comment by Godmatik** [comment]
Duplicate #8359
