### ISSUE TITLE
[Quest][NPC][Item] souvenirs of death! wants 30 human skulls, but the drop might be too low for them

### ISSUE THREAD

**Issue by queeb3** [Atlantiss/NetherwingBugtracker#789]
[//]: # (Enclose links to things related to the bug using http://wowhead.com or any other TBC database.)
[//]: # (You can use screenshot ingame to visual the issue.)
[//]: # (Write your tickets according to the format:)
[//]: # ([Quest][Azuremyst Isle] Red Snapper - Very Tasty!)
[//]: # ([NPC] Magistrix Erona)
[//]: # ([Spell][Mage] Fireball)
[//]: # ([Npc][Drop] Ghostclaw Lynx)
[//]: # ([Web] Armory doesnt work)

**Description**: 
I don't know if its just me but I think of humans having a skull all the time is normal, so why do they not always drop one, on the wow side of things I get that a 100% drop will make the quest to easy and just adding 60 to the number and it becomes a horrible grind. I do however think that skulls should drop more often from the humans in the farms of hilsbrad.
**Current behaviour**:
out of every 5 humans, I've killed I got one skull.
**Expected behaviour**: 
out of every 5 humans I kill I would expect to get at least 3 for a quest that requires 30 skulls.
**Server Revision**:

**Comment by aresbrutus** [comment]
Yup, drop rate is fine.
