### ISSUE TITLE
[Spell][Priest] Prayer of Mending casts overwriting each other

### ISSUE THREAD

**Issue by chadyelias** [Atlantiss/NetherwingBugtracker#7890]
**Description**: Prayer of Mending from two different priests can overwrite each other and therefore makes one of them disappear (before running out of charges)

**Current behaviour**: Tried it in a group, had 1 person be lowest HP (%), 2x PoM on 2 other people that get hit, both PoM went to the person with the lowest HP and therefore one of them was overwritten.

**Expected behaviour**: The second PoM shouldn't go to someone that already has PoM, but instead, go to the member with 2nd lowest HP (%).

**Comment by Wolffenstein** [comment]
Fixed in rev 3597.
