### ISSUE TITLE
Rogues can stealth with hunter's mark on them

### ISSUE THREAD

**Issue by siweizhao** [Atlantiss/NetherwingBugtracker#7891]
**Description**: 
Rogues can stealth with hunter's mark on them

**Current behaviour**:
Rogues can stealth with hunter's mark on them

**Expected behaviour**: 
They should not be able to

**Server Revision**:

**Comment by ghost** [comment]
Wrong. They can stealth, but remain visible to the hunter. Vanish dispels Hunter's Mark.
