### ISSUE TITLE
[Item] Band of the Eternal Defender

### ISSUE THREAD

**Issue by cbarzotti** [Atlantiss/NetherwingBugtracker#7892]
[//]: # (Enclose links to things related to the bug using http://wowhead.com or any other TBC database.)
[//]: # (You can use screenshot ingame to visual the issue.)
[//]: # (Write your tickets according to the format:)
[//]: # ([Quest][Azuremyst Isle] Red Snapper - Very Tasty!)
[//]: # ([NPC] Magistrix Erona)
[//]: # ([Spell][Mage] Fireball)
[//]: # ([Npc][Drop] Ghostclaw Lynx)
[//]: # ([Web] Armory doesnt work)
[//]: # (To find server revision type `.server info` command in the game chat.)

**Description**: 
<a href="https://tbcdb.com/?item=29297">Band of the Eternal Defender</a> proc doesn't stack with <a href="https://tbcdb.com/?spell=27149">Devotion Aura (Rank 8)</a> or <a href="https://tbcdb.com/?item=27500">Scroll of Protection V</a>.

Didn't test with lower ranks of aura/scroll, but I am assuming it works in the same way.

**Current behaviour**:
<a href="https://tbcdb.com/?item=29297">Band of the Eternal Defender</a> doesn't proc if you have <a href="https://tbcdb.com/?spell=27149">Devotion Aura (Rank 8)</a> or <a href="https://tbcdb.com/?item=27500">Scroll of Protection V</a> up. 
If you make the item proc and then use the aura/scroll, the proc buff will disappear.

**Expected behaviour**: 
For what I was able to find around, the proc should stack wtih <a href="https://tbcdb.com/?spell=27149">Devotion Aura (Rank 8)</a>, but not with <a href="https://tbcdb.com/?item=27500">Scroll of Protection V</a>.
Assuming you have only the aura, the ring should be able to proc and you get both armor buffs (not 100% sure about this, couldn't find a lot of info about it).
Assuming you have only the scroll, the ring should be able to proc and cancel the scroll buff (altho that would make scrolls of protection basically useless, so maybe disabling the scroll momentarily in favor of the buff could be considered).

**Server Revision**: 
Atlantiss Karazhan | Content patch: 2.1.0 | Revision: 3596

**Comment by tsu-1** [comment]
It should overwrite buff from Scroll of Protection V.
