### ISSUE TITLE
[Dungeons][NPC] Mizzle The Crafty - Dire Maul North

### ISSUE THREAD

**Issue by 13Thirteenn** [Atlantiss/NetherwingBugtracker#7893]
**Description**
When the King Gordok (last boss) is dead Mizzle the Crafty will run up onto the dais. Have everyone talk to him to get the buff. However on my second run of this instance the NPC still does not spawn! 

First time few months ago I talked to few GM's and developers and I had the buff granted manually.

Atlantiss - Karazhan

**Comment by Godmatik** [comment]
Duplicate - Dire Maul right now is stock and needs a full rework, it is on Wolf's to-do list
