### ISSUE TITLE
Warlock succubus stays invisible while casting and channeling seduce

### ISSUE THREAD

**Issue by vermura** [Atlantiss/NetherwingBugtracker#7894]
[//]: # ([Spell][Warlock] Seduce)

**Description**: Warlock Pet has seduce spell

**Current behaviour**:
Warlock pet on passive and invisible stays invisible when it begins casting and continues to stay invisible while channeling seduce.
**Expected behaviour**: 
Succubus should immediately leave invisibility when it begins to cast seduce and remain visible until it leaves combat.

**Server Revision**: 3596

**Comment by tsu-1** [comment]
Duplicate.
