### ISSUE TITLE
[Quest][Eastern Plaguelands] Redemption

### ISSUE THREAD

**Issue by Vishiswaz** [Atlantiss/NetherwingBugtracker#7895]
[//]: # (Enclose links to things related to the bug using http://wowhead.com or any other TBC database.)
[//]: # (You can use screenshot ingame to visual the issue.)
[//]: # (Write your tickets according to the format:)
[//]: # ([Quest][Azuremyst Isle] Red Snapper - Very Tasty!)
[//]: # ([NPC] Magistrix Erona)
[//]: # ([Spell][Mage] Fireball)
[//]: # ([Npc][Drop] Ghostclaw Lynx)
[//]: # ([Web] Armory doesnt work)
[//]: # (To find server revision type `.server info` command in the game chat.)

**Description**: 
The quest "Redemption" cannot be completed.

**Current behaviour**:
You can accept the quest, but nothing happens. No rp or clickable dialogue can complete the quest.

**Expected behaviour**: 
You should be able to click through a dialogue with him as seen here: https://classic.wowhead.com/quest=5742/redemption#comments:id=2743139

**Server Revision**: 
3596

**Comment by raethkcj** [comment]
Not bugged, you have to use the `/sit` emote.

**Comment by Vishiswaz** [comment]
Ah yep. Sorry.
