### ISSUE TITLE
No improve imp 

### ISSUE THREAD

**Issue by hajribaha** [Atlantiss/NetherwingBugtracker#7896]
[//]: # (Enclose links to things related to the bug using http://wowhead.com or any other TBC database.)
[//]: # (You can use screenshot ingame to visual the issue.)
[//]: # (Write your tickets according to the format:)
[//]: # ([Quest][Azuremyst Isle] Red Snapper - Very Tasty!)
[//]: # ([NPC] Magistrix Erona)
[//]: # ([Spell][Mage] Fireball)
[//]: # ([Npc][Drop] Ghostclaw Lynx)
[//]: # ([Web] Armory doesnt work)
[//]: # (To find server revision type `.server info` command in the game chat.)

**Description**: 
when taking the talent improve imp from demonology  it should improve it ability 
**Current behaviour**:
no improve ability it  Exemple with my imp  blood pact should give 23 stamina as said in his ability but it just give me 17 the value before taking the talent  ,also applies for the rest of ability 
**Expected behaviour**: 
well i should improve imp
**Server Revision**: 
did a ticket to GM how told me to make a bugtrack in here also clear cache and nothing changed 
![image: GM tell me to go here  ](https://user-images.githubusercontent.com/47065230/106387533-81678e80-63da-11eb-88e5-66534d8034a3.png)

**Comment by Godmatik** [comment]
Are you looking at the tooltip only? Those doesn't reflect buffs from talents, that's a TBC thing.

**Comment by danbopes** [comment]
Tooltip values may not always reflect actual values. Please confirm the issue is beyond the tooltip, and you can feel free to ping back here if it's still an issue.
