### ISSUE TITLE
[Spell][Priest] Mind Vision

### ISSUE THREAD

**Issue by Vishiswaz** [Atlantiss/NetherwingBugtracker#7898]
[//]: # (Enclose links to things related to the bug using http://wowhead.com or any other TBC database.)
[//]: # (You can use screenshot ingame to visual the issue.)
[//]: # (Write your tickets according to the format:)
[//]: # ([Quest][Azuremyst Isle] Red Snapper - Very Tasty!)
[//]: # ([NPC] Magistrix Erona)
[//]: # ([Spell][Mage] Fireball)
[//]: # ([Npc][Drop] Ghostclaw Lynx)
[//]: # ([Web] Armory doesnt work)
[//]: # (To find server revision type `.server info` command in the game chat.)

**Description**: 
Mind Vision can't be canceled.

**Current behaviour**:
You cannot cancel Mind Vision, forcing you to sit there for the whole minute.

**Expected behaviour**: 
You should be able to cancel it in the same way as any other channeled spell. Movement, escape key, casting something else, etc.

**Server Revision**: 
3596

**Comment by danbopes** [comment]
Unable to repo: Jumping pulled me out of Mind Vision:
![](https://i.imgur.com/jsb8Ako.png)
