### ISSUE TITLE
[Spell][Paladin]Hammer of Justice bugged in pvp

### ISSUE THREAD

**Issue by ryanrossprogrammer** [Atlantiss/NetherwingBugtracker#7899]
**Description**: 
Hammer of Justice is resisted way too much.  

**Current behaviour**:
I understand talents that provide anti-stun, character abilities that make them immune to stun(warrior hunter), and racials that add stun resist.  But a large percentage of my attempts get resisted no matter the class.

**Expected behaviour**: 
Hammer of Justice shouldn't be resisted so much.

**Server Revision**: 
Current

**Comment by Godmatik** [comment]
You need to provide more evidence and a large sample size with proof, can't just say "it's bugged" without any additional information.
