### ISSUE TITLE
Dranei start area quest "Inoculation"

### ISSUE THREAD

**Issue by craigsurbrook** [Atlantiss/NetherwingBugtracker#790]
You use an inoculation crystal on Nestlewood Owlkin (who have yellow titles, unlike the other Owlkin in the area which have red titles and are hostile).

[Current Behavior]
When you use the innoculation crystal, it takes many tries to get an inoculated owlkin (with a corresponding randomized text in orange saying how the Owlkin feels).
For example:
1st encountered, after 80 tries gave up.
2nd encountered, after 2 tries it worked.
3rd encountered, after 9 tries it worked.
4th encountered, 22 tries it worked.
5th encountered, 41 tries it worked.
6th encountered, 9 tries it worked.

[Expected Behavior]
You rarely, if ever, fail on the first try, giving one of the randomized orange texts saying how the Owlkin feels. Less often than not, the Owlkin enrages and you have to fight it like the ones that are enemies.

I don't know how to bring up the server revision from the chat (typing .s doesn't give any info).

**Comment by tcberk12** [comment]
#713

**Comment by Easyfraggy** [comment]
Duplicate like berk says above, please provide your feedback in the existing thread.

**Comment by craigsurbrook** [comment]
Easyfraggy, the other Inoculation (#790) didn't accurately report the
behavior that was happening, nor did it describe what the behavior should
be.
This should COUNT.

**Comment by tcberk12** [comment]
#790 is another Inoculation bug that has been referred on to #713.

Your experience of the issue is slightly different, yes, but they are probably all resulting from the same underlying issue.

**Comment by tcberk12** [comment]
I would say this report is more detailed, I guess you could refer #713 onto this one. But as long as the info is in the same place i dont think it really matters.

**Comment by craigsurbrook** [comment]
Thanks. :)

**Comment by Easyfraggy** [comment]
The way quests are scripted having all the relevant info about the quest in 1 thread is preferable even if it is seperate issues with the quest. Same goes for same mob having several issues.

I've referred this post in the other thread. If you want to you can copy pasta your OP from here over there! Thanks for reporting, The more details are very welcome.

**Comment by craigsurbrook** [comment]
Got it. :)

**Comment by Frankenberryberry** [comment]
The following description from #1589 is still the way this quest works =( Tested 27th of November.

Description:
The Quest (https://www.wowhead.com/quest=9303/inoculation) Inoculation doesn't work right anymore.
When I did this quest 2 weeks ago, everything was fine.
Current behaviour:
When you use the Inoculating Crystal, nothing happens but when you kill a Nestlewood Owlkin you get 1 point for the quest.
Expected behaviour:
Should only give credit for the quest if you use the crystal.
