### ISSUE TITLE
[VoidWalker] Spells wont upgrade

### ISSUE THREAD

**Issue by Znotwow** [Atlantiss/NetherwingBugtracker#7900]
Hello, I apologize if this isn't the correct format to report. I'm new to this and i'll try my best.

Ingame name : Znot

Issue: I bought the Grimoires of Torment Rank 2,Sacrifice Rank 2,Shadows Rank 2  and Suffering.

On the voidwalkers hotbar nothing has been updated, they are all rank 1, rank 1 and 2 of  consume shadows and suffering is missing. 

I cleared the cache folder,reloged,turned off the addons, tried to re-summon the void, but nothing changed.
![WoWScrnShot_020321_023356](https://user-images.githubusercontent.com/78456072/106685360-89852100-65c8-11eb-971a-790e82549506.jpg)

I contacted a GM, he sent me here since it's a dev thing. Looking forward for you help guys.

**Comment by Wosser** [comment]
You have consume shadows twice in your pet bar, did you drag them there yourself? Maybe that causes the ranks to not upgrade. Open your spellbook, go to the demon tab at the bottom and drag the max rank spells manually to the pet bar so every spell is there only once and see if they update automatically again when learning new ranks.

**Comment by Znotwow** [comment]
No i haven't dragged them. It happend as i learnt them. I will try to do what you said, and will let you know if this resolves my issues. Thanks.

**Comment by Znotwow** [comment]
Thank you Wosser. I did as you said, and now it's all fine.
