### ISSUE TITLE
[Quest][Shadowmoon Valley] The Not-So-Friendly Skies

### ISSUE THREAD

**Issue by kirinha** [Atlantiss/NetherwingBugtracker#7901]
**Description**: For this quest, you're supposed to kill Dragonmaw Transporters that fly overhead on the floating islands north of Netherwing Ledge.

**Current behaviour**: The Dragonmaw Transporters do not come down to melee range after their initial ranged attack but stay at range, up in the air. As it is, it is literally impossible to do as a melee class. There are also barely any spawns.

**Expected behaviour**: The Dragonmaw Transporters are supposed to come down into melee range after firing a ranged attack or two, as described here: https://www.wowhead.com/npc=23188/dragonmaw-transporter#comments:id=259660

**Comment by Tereneckla** [comment]
That is a 2.4 change. Until then they don't
