### ISSUE TITLE
Warriors

### ISSUE THREAD

**Issue by BuizzyGER** [Atlantiss/NetherwingBugtracker#7902]
Warriors are not like they were on Official Servers.....they are way too strong here. And the Stuns (Crafted- Weapon and Specc) dont have same delay here... Its kinda Buggy that a Warrior can hold u in a Stunlock for about 8 Seconds only because of his Stuns! Nex step is that the dmg of Warriors is too high on this Server....please check this...

**Comment by danbopes** [comment]
This is too vague. If you have specific instances, feel free to reopen, with some actual evidence between retail/here, and we can look into it further.
