### ISSUE TITLE
Shartuul teleporter event - solution

### ISSUE THREAD

**Issue by Kmotr123** [Atlantiss/NetherwingBugtracker#7903]
**Description**: 
As we all know there are many threads about bugs with this specific event and it doesnt look like anything would change in the future; however there is an easy solution how to appease disappointed players. The chance for the the quest item, Darkrune, to drop from a quest reward  Banish More Demons would be 100% instead od 34% so we will have more tries to accomplish this hellish event. 
**Current behaviour**:
Current drop chance of Darkrune is 34%
**Expected behaviour**: 
Raise the drop chance to 100%
**Server Revision**: 
Raise the drop chance so players will have more chances to complete the event. 

I know that there are dozens of players that tried and failed this event so a little help would be greatly appreciated. I have tried to accomplish it for many a week and yet unsucessful. We would all be so glad if it could be helped by this revision so the disadvantage wouldnt be that great.

**Comment by danbopes** [comment]
We're not going to increase drop chance to cover up for a bug on the server. If you have specific issues, I would encourage you to direct your comments to the actual issues, so we can get the bugs fixed.
