### ISSUE TITLE
Warlock Pet Continuously Vanishing in Shadowmoon Valley

### ISSUE THREAD

**Issue by Baelek** [Atlantiss/NetherwingBugtracker#7904]
**Description**: When questing around in the Shadowmoon Valley zone, warlock pets will continuously vanish when mounting/dismounting.

**Current behaviour**: Frequently, when having a pet out, mounting, moving to another area, and then dismounting, the pet will vanish.

**Expected behaviour**: When having a pet out, mounting, moving to another area, and then dismounting, the pet will always appear (unless it died, of course).

**Server Revision**: 3596

**Comment by Wolffenstein** [comment]
Fixed in rev 3754.
