### ISSUE TITLE
[Spell][Priest] Mind Control bugged

### ISSUE THREAD

**Issue by chadyelias** [Atlantiss/NetherwingBugtracker#7905]
**Description**: MC'd people off cliffs in bgs, took the fall damage instead of the people who actually got thrown

**Current behaviour**: Mind Control makes the caster (priest) take fall damage instead of the person who got thrown off a cliff.

**Expected behaviour**: The player who got MC'd and thrown off should take the fall damage instead of the caster(priest) himself.

**Comment by Godmatik** [comment]
Was fixed in a previous revision, can close
