### ISSUE TITLE
([Spell][Shaman] Windfury Totem)

### ISSUE THREAD

**Issue by Reblau** [Atlantiss/NetherwingBugtracker#7906]
**Description**: My guild has noticed the windfury proc rate seems off. At first we blamed the shamans for poor uptime like any sensible individual would. With near perfect uptime however, the problem persisted.
I did some testing and Windfury totem seems to somehow interact with sinister strike (SS) causing less procs to occur than intended. I do not know if this has anything to do with sinister strike itself, or if it is an issue with mainhand instant attacks. 

**Current behaviour**: When using sinister strike with windfury the totem buff proc rate drops way below 20%. I have done some testing, links provided below. WF looks weird in the logs because recount attributes to procs to sometimes incorrect damage instances. 

Here i have tested spaming SS with Slince and Dice (SnD) up using only my mainhand weapon. I did two sessions so the results of both images need to be added together. The reason for doing 2 sessions was because the white hit analysis was not statistically significant with the amount of data from the first one:
https://media.discordapp.net/attachments/804372167465762857/805840900486987826/unknown.png?width=956&height=465
https://media.discordapp.net/attachments/804372167465762857/805848132884627504/unknown.png?width=956&height=437

The results are 770 white hits, 131 windfury procs, 271 SS. SS + white hits = total amount of attacks eligible to proc WF = 1041
Proc chance for all attacks: 131/1041 = 12.58%
Proc chance if not counting SS 131/770 = 17.01%

I wanted to see if the problem was that SS for some reason did not procs WF, but as we can see from the results the problem is not that simple. For some reason using SS causes a reduction in WF procs attributable to white hits as well. 

To examine if there was a problem with the speed of the weapon i examined the behavior of windfury totem using first a slow dagger without SnD or other haste buffs, and then a fast dagger. The slow dagger became redundant after testing fast dagger. Linking to it anyway for extra data:
https://media.discordapp.net/attachments/804372167465762857/806535833972375562/slow_dagger.png?width=956&height=443
https://media.discordapp.net/attachments/804372167465762857/806538057033449523/fast_dagger_white_hits_no_SnD.png?width=956&height=456

Fast dagger white hits only with WF: 732 white hits, 151 WF procs
Proc chance: 151/732 = 20.63%
Looks like normal behavior. 
To exclude my normal mainhand, its haste buff, or mongoose to be the cause of problems i tested the fast dagger with SnD + SS spam, like in my first test, to see if the problem persists:
https://media.discordapp.net/attachments/804372167465762857/806549036098256897/fast_dagger_max_Sinister__SnD.png?width=944&height=465

Results are: 961 white hits, 166 WF procs, 202 SS. Total hits eligible to proc WF 1163
Proc chance for all attacks: 166/1162 = 14.27%
Proc chance if not counting SS: 17.27%

As we can see the problem persists. 

To examine if the problem is related to SnD i tested equipping 2 slow daggers (same speed for convenient calculations). I did as few shiv attacks as possible to generate combo points for keeping SnD up.
https://media.discordapp.net/attachments/804372167465762857/806559995474083880/double_slow_dagger_SnD_with_shiv.png?width=942&height=465

Results are 1403 white hits of which half 701 (rounded down) should be by the mainhand, 136 WF procs, 41 shivs (which are made by off hand, and thus NOT eligible for WF). Furthermore, 30 attacks missed. Half of those misses can be expected to be mainhand, making the total amount of hits eligible for WF 701-15 = 686
Proc chance for WF with SnD up: 136/686 = 19.86%

The results would indicate the problem is not related to SnD, or the fact that an off hand is equipped. 

Then i tested whether haste effects from mainhand or mongoose could, together with SnD have an impact on WF behavior using my normal setup with MH + OH. As in the dagger test, Shiv was used to generate combo points for SnD upkeep. 
https://media.discordapp.net/attachments/804372167465762857/806571067551907890/unknown.png?width=956&height=457

Results are 1127 white hits, 28 sword specialization hits, 81 WF procs, 17 Shiv, 23 miss. Excluding the misses 1104 attacks landed. The number of hits performed by the MH can be calculated by finding the ratio of MH hits to OH hits, which is OH speed / (OH speed + MH speed) = 1.5/4.2. This ratio is constant with haste effects and the base speed of the weapons can thus be used for calculations. 1104x(1.5/4.2) = 394. Sword spec attacks are always made by the MH, total number of attacks eligible for WF is thus 394+28 = 422
Proc chance for WF: 81/411 = 19.19%

Results display normal behavior.

**Expected behaviour**: 
WF totem proc chance should be 20% for all **EDIT** white attacks made by the mainhand other than WF attacks themselves. Before someone comes in here and says WF totem effect has a 3 second internal cooldown i will just state that this is wrong. It never was, and shouldn’t be. 

http://web.archive.org/web/20080811071236/http://elitistjerks.com/f47/t20765-shaman_enhancement/#How_to_choose_totems This doesn’t implicitly state no CD, it is however implied. 
https://www.mmo-champion.com/threads/603849-sword-spec-and-windfury Citation from the link: “windfury totem tho has a secret cooldown on its proc (?) which is said to be 3 secs.”
“incorrect, this is only with the shamans windfury weapon buff. the cooldown is also shared with both mh and oh.and, of course, as the poster above stated... **the 3 sec hidden CD just affects, windfury WEAPON. windfury TOTEM are just clean 20% per white**”
https://github.com/Atlantiss/NetherwingBugtracker/issues/6178 This issue has been dealt with before on netherwing and was corrected to no CD, further proof in the link posted by some else.

To conclude: Sinister strike, or possibly instant attack spells by the mainhand somehow prevents WF procs, reducing the rate by a significant amount. I couldn’t find the root cause of the problem during my tests, but I feel there is sufficient evidence to show that there is indeed a problem with the totem effect. **EDIT** As shown, this problem cannot be explained simply by SS not being able to proc WF as white hit proc rate is reduced even if SS hits are excluded. 

**EDIT** I would like to add that the percentages deviating from the intended proc rate of 20% in the tests using SS are statistically significant at a confidence level of 95%.

Thanks 

**Server Revision**: 3596

**Comment by Tereneckla** [comment]
![image](https://user-images.githubusercontent.com/50233983/112381425-d80e8c00-8cea-11eb-8dd3-ae337ac78963.png)
![image](https://user-images.githubusercontent.com/50233983/112381436-dc3aa980-8cea-11eb-82b7-159bd66b96b2.png)

Neither Only SS nor SS+SnD with a fast dagger gave me a lower number of windfury procs
