### ISSUE TITLE
Invisible Cleric of Karabor

### ISSUE THREAD

**Issue by Dirtsleeper** [Atlantiss/NetherwingBugtracker#7907]
([Quest][Shadowmoon Valley] Divination: Gorefiend's Cloak)
([NPC] Cleric of Karabor)

**Description**: 
There are invisible NPCs that are able to attack you. If you run out of range, they become visible and attackable.
Has nothing to do with spectacles being equipped.

**Current behaviour**:
Invisible NPCs

**Expected behaviour**: 
Visible NPCs

**Server Revision**: 
3599

**Comment by Godmatik** [comment]
Been an issue for a long time now, still needs a fix.

https://github.com/Atlantiss/NetherwingBugtracker/issues/7344
