### ISSUE TITLE
Mind Control while mounted

### ISSUE THREAD

**Issue by fabrusso** [Atlantiss/NetherwingBugtracker#7908]
[//]: # (Enclose links to things related to the bug using http://wowhead.com or any other TBC database.)
[//]: # (You can use screenshot ingame to visual the issue.)
[//]: # (Write your tickets according to the format:)
[//]: # ([Quest][Azuremyst Isle] Red Snapper - Very Tasty!)
[//]: # ([NPC] Magistrix Erona)
[//]: # ([Spell][Mage] Fireball)
[//]: # ([Npc][Drop] Ghostclaw Lynx)
[//]: # ([Web] Armory doesnt work)
[//]: # (To find server revision type `.server info` command in the game chat.)

**Description**: 
While on mount. I've been Mind Controlled. Dismounted I was able to run as mounted.

**Current behaviour**:
I can run as mounted after MC on mount.

**Expected behaviour**: 
I should run normally after MC on mount.

**Server Revision**:

**Comment by Tereneckla** [comment]
If an aura that changes movement speed expires during mind control the movement speed is not updated until a loading screen.
Expected: Movement speed updates even while you are mind controlled

**Comment by Godmatik** [comment]
Fixed in 3813, can close
