### ISSUE TITLE
[Spell][NPC] Crimson Hand Battle Mage

### ISSUE THREAD

**Issue by nikko8085** [Atlantiss/NetherwingBugtracker#7910]
**Description**: 
The ability Frost Attack from Crimson Hand Battle Mage in Tempest Keep: The Eye deals 21k damage. This is patch 2.0 behaviour, but was nerfed in 2.1 to 2k. The server currently runs on patch 2.1, so I would assume the change to this ability should be implemented.

**Current behaviour**:
Frost Attack (id 39087) deals 21k damage.
https://cdn.discordapp.com/attachments/808836783038005249/808839772268265502/unknown.png

**Expected behaviour**: 
Frost Attack should deal 2k damage.
https://tbc-twinhead.twinstar.cz/?npc=20047#reported-fixes
https://www.wowhead.com/spell=39087/frost-attack

**Server Revision**: 
3604

**Comment by therealCrysis** [comment]
It should not be 2k damage. It should have been reduced by max 30% I believe.
Damage of these mobs has been reduced, which you can see in our Changelog. Frost Attack does not one-shot tank anymore but it still should be kited.
