### ISSUE TITLE
[NPC] Nethermancer Sepethrea mechanic can be avoided

### ISSUE THREAD

**Issue by Mikik3jr** [Atlantiss/NetherwingBugtracker#7914]
[//]: # (Enclose links to things related to the bug using http://wowhead.com or any other TBC database.)
[//]: # (You can use screenshot ingame to visual the issue.)
[//]: # (Write your tickets according to the format:)
[//]: # ([Quest][Azuremyst Isle] Red Snapper - Very Tasty!)
[//]: # ([NPC] Magistrix Erona)
[//]: # ([Spell][Mage] Fireball)
[//]: # ([Npc][Drop] Ghostclaw Lynx)
[//]: # ([Web] Armory doesnt work)
[//]: # (To find server revision type `.server info` command in the game chat.)

**Description**: 
This is a boss in Mechanar. It summons some fire elementals at the start and they target randomly(?) and chase their targets.

**Current behaviour**:
If standing behind a boxes left from the boss at pull (looking from the front) the elementals will evade and won't attack anyone. They remain at their platform all the time during the fight.

In our case the dps was behind the boxes and the tank pulled. The healer maybe was healing from behind the boxes as well.
![image](https://user-images.githubusercontent.com/43505031/107873625-280c5e80-6eb4-11eb-884e-3061783fc428.png)

**Expected behaviour**: 
I don't think it is intended, so it shouldn't work?

**Server Revision**: 
3604

**Comment by danbopes** [comment]
Hotfixed
