### ISSUE TITLE
[Raid][Spell] Tempest Keep - P2. A'lar Dive Bomb can be spell reflected

### ISSUE THREAD

**Issue by Selphius** [Atlantiss/NetherwingBugtracker#7916]
**Current behaviour**:
When A'lar casts dive bomb - meteor, warrior can use reflect shield before damage is dealt. This way you reflect entire meteor damage you were supposed to take and reflect it into small adds, which come out with 20% hp cause of it making this phase trivial since adds will go down in several seconds since they lost 100k hp+.

**Expected behaviour**: 
Meteor (dive bomb) shouldn't be able to be reflected or at least not reflect the damage into the adds.

**Server Revision**: 
3604

**Comment by Wolffenstein** [comment]
Fixed in rev 3656.
