### ISSUE TITLE
[Spell][Priest] Power Word: Shield / Stealth while shieldied

### ISSUE THREAD

**Issue by SmyakaMF** [Atlantiss/NetherwingBugtracker#7918]
[//]: # (Enclose links to things related to the bug using http://wowhead.com or any other TBC database.)
[//]: # (You can use screenshot ingame to visual the issue.)
[//]: # (Write your tickets according to the format:)
[//]: # ([Quest][Azuremyst Isle] Red Snapper - Very Tasty!)
[//]: # ([NPC] Magistrix Erona)
[//]: # ([Spell][Mage] Fireball)
[//]: # ([Npc][Drop] Ghostclaw Lynx)
[//]: # ([Web] Armory doesnt work)
[//]: # (To find server revision type `.server info` command in the game chat.)

**Description**: 
Shields dont work right
**Current behaviour**:
DoT ticks even when shielded
**Expected behaviour**: 
Shield must absorb DoT dmg.
**Server Revision**: 
Atlantiss/Karazhan

**Comment by SmyakaMF** [comment]
Priest shiled dont absorb dmg properly.
 If rogue got DoT and get shield (any shield rly) cant restealth because dmg ticks still brought u out of stealth.

**Comment by Godmatik** [comment]
Rev 4014 - still an issue
The shield absorbs the DOT, but will break you out of stealth when it ticks, even if it is full absorb.
I ASSUME this is not intended, but might need to verify with some proof from classic.

**Comment by Godmatik** [comment]
Confirmed not a bug via classic TBC - absorbed damage breaks you out of stealth as intended. 

Same as if you had a CC on you like polymorph while shielded - the absorbed damage will break the CC.
