### ISSUE TITLE
[Raid][ZA] Hatchers on Jan'alai sometimes hatch eggs from the other platform

### ISSUE THREAD

**Issue by Tereneckla** [Atlantiss/NetherwingBugtracker#7919]
[//]: # (Enclose links to things related to the bug using http://wowhead.com or any other TBC database.)
[//]: # (You can use screenshot ingame to visual the issue.)
[//]: # (Write your tickets according to the format:)
[//]: # ([Quest][Azuremyst Isle] Red Snapper - Very Tasty!)
[//]: # ([NPC] Magistrix Erona)
[//]: # ([Spell][Mage] Fireball)
[//]: # ([Npc][Drop] Ghostclaw Lynx)
[//]: # ([Web] Armory doesnt work)
[//]: # (To find server revision type `.server info` command in the game chat.)

**Description**: 
It is pretty random and even the method I found only has a 50% chance to "succeed"
On the first wave of hatchers you let both through and hatch eggs 2 times before killing them.
Second wave you only kill the western (left if you walk up the stairs to the boss) hatcher. The other hatcher will go to the eastern platform and hatch the eggs there and a few from the western platform.
https://youtu.be/E74VKNL75S8
First wave of hatchers at 0:10
Second at 1:40

**Current behaviour**:
Hatchers sometimes hatch from the wrong platform

**Expected behaviour**: 
Hatchers only hatch on the platform they are currently at

**Server Revision**: 3606

**Comment by Godmatik** [comment]
We've also occasionally seen eggs hatched from the opposite side of where the hatcher is at.

**Comment by eri1997** [comment]
Had the same thing happen in nw once from all the runs we did 
https://github.com/Atlantiss/NetherwingBugtracker/issues/6385

**Comment by Godmatik** [comment]
We've seen it happen two runs in a row.

**Comment by Godmatik** [comment]
Was fixed on Netherwing, closing
