### ISSUE TITLE
Dranei start area Bloodmyst Isle, Blood Elves heals fail to do anything.

### ISSUE THREAD

**Issue by craigsurbrook** [Atlantiss/NetherwingBugtracker#792]
*From Icehole, Gnome rogue - 

It does not matter if you are on a quest or not, the Blood Elf Scouts just past the immediate start area for the Dranei have a bug.

[Current Behavior]
They cast heal and spend mana, but no heal actually occurs.

[Expected Behavior]
They cast heal and spend mana, and actually get a heal to themselves or a nearby Blood Elf.

**Comment by craigsurbrook** [comment]
Except I was there with another player who actually discovered the bug.
The Blood Elf Scouts were make a cast that showed "green leaves" swirling
around them, the same graphic as this Dranei that I was with does when she
was doing a heal.
If these Blood Elf Scouts were doing Faerie Fire, the cast would have been
purple (and I believe it's also an instant cast, not a channel).
There wasn't a purple Faerie Fire graphic anywhere to be seen (nor did we
ever receive a faerie fire debuff).
Again, they do a channel cast with green leaves (the heal graphic), their
mana would get spent, and nothing would ever happen.

These are the Blood Elf Scouts an the way out of the Dranei start area.

**Comment by Easyfraggy** [comment]
![image](https://user-images.githubusercontent.com/36134067/46236983-e8e02000-c381-11e8-8743-5aeafcbebd74.png)

**Comment by craigsurbrook** [comment]
Thanks fraggy, somehow neither I nor the Dranei I was with ever got the
debuff. Does that debuff actually happen? We had quite a few of those casts
without a debuff. I will go back and check to see if faerie fire ever can
land successfully on a player (in a few hours).

**Comment by Easyfraggy** [comment]
Faerie Fire works fine from them. Just tested it.

**Comment by tcberk12** [comment]
<img width="1435" alt="screen shot 2018-09-28 at 4 06 47 pm" src="https://user-images.githubusercontent.com/43530009/46237326-9e868100-c338-11e8-8391-97b456e61535.png">

**Comment by craigsurbrook** [comment]
Thank you!
