### ISSUE TITLE
Deadwood Headdress Feather

### ISSUE THREAD

**Issue by sobiech6** [Atlantiss/NetherwingBugtracker#7920]
Description:
Deadwood Headdress Feather https://db.excalibur.ws/?item=21377 are not dropping from certain mobs in Felpaw Village:
Deadwood Den Watcher https://db.excalibur.ws/?npc=7156
Deadwood Avenger https://db.excalibur.ws/?npc=7157
Deadwood Shaman https://db.excalibur.ws/?npc=7158
Chieftain Bloodmaw https://db.excalibur.ws/?npc=9462
Current behaviour:
Deadwood Headdress Feather are absent from loot tables.
Some proofs: https://ibb.co/LR233vR https://ibb.co/nfSjKqs
Expected behaviour:
Deadwood Headdress Feather must have 35% chance of dropping from certain mobs in Felpaw Village.
Server Revision:
3606

**Comment by Tereneckla** [comment]
![image](https://user-images.githubusercontent.com/50233983/108591298-597ba300-7368-11eb-9649-43fccc92e960.png)
https://classic.wowhead.com/item=21377/deadwood-headdress-feather#comments:id=3157942
![image](https://user-images.githubusercontent.com/50233983/108591303-64cece80-7368-11eb-96a6-c400ab733654.png)

**Comment by sobiech6** [comment]
I made all q and killed 500 mobs - drop 0, yesterday and day before. done this rep on wotlk and feathers dropped.
Earlier was ok cause i have this q repetable.
