### ISSUE TITLE
[Spell][NPC] Mangled Cadaver - Cadaver Worms debuff stacks infinately on player.

### ISSUE THREAD

**Issue by Zetamaniac** [Atlantiss/NetherwingBugtracker#7922]
[//]: # (Enclose links to things related to the bug using http://wowhead.com or any other TBC database.)
[//]: # (You can use screenshot ingame to visual the issue.)
[//]: # (Write your tickets according to the format:)
[//]: # ([Quest][Azuremyst Isle] Red Snapper - Very Tasty!)
[//]: # ([NPC] Magistrix Erona)
[//]: # ([Spell][Mage] Fireball)
[//]: # ([Npc][Drop] Ghostclaw Lynx)
[//]: # ([Web] Armory doesnt work)
[//]: # (To find server revision type `.server info` command in the game chat.)

**Description**: 
The skill CADAVER WORMS [https://classic.wowhead.com/spell=16143/cadaver-worms](url) from the enemy NPC Mangled Cadaver [https://classic.wowhead.com/npc=10382/mangled-cadaver](url) stacks infinately on the player character.
**Current behaviour**:
Stacks infinately on the player character, as each different zombie casts a new one on you, leading to ridiculous amounts of damage taken as stacks build up.
![Screenshot 2021-02-28 011723](https://user-images.githubusercontent.com/45523886/109408191-bd542c00-7965-11eb-913e-1f160fbbf224.png)
![Screenshot 2021-02-28 013742](https://user-images.githubusercontent.com/45523886/109408190-baf1d200-7965-11eb-88bb-ee5a87ff01b2.png)

**Expected behaviour**: 
It should only be 1 instance at all times regardless of which zombie casts it on the player.
**Server Revision**: 
3607
@Wolffenstein

**Comment by therealCrysis** [comment]
This debuff indeed should not stack with each other iirc.

**Comment by aplouding** [comment]
Bug still present on server revision 3701

**Comment by Godmatik** [comment]
Was fixed with the Stratholme revamp, can be closed
