### ISSUE TITLE
Warlock sacrifice does nothing

### ISSUE THREAD

**Issue by hillelg123** [Atlantiss/NetherwingBugtracker#7923]
[//]: # (Enclose links to things related to the bug using http://wowhead.com or any other TBC database.)
[//]: # (You can use screenshot ingame to visual the issue.)
[//]: # (Write your tickets according to the format:)
[//]: # ([Quest][Azuremyst Isle] Red Snapper - Very Tasty!)
[//]: # ([NPC] Magistrix Erona)
[//]: # ([Spell][Mage] Fireball)
[//]: # ([Npc][Drop] Ghostclaw Lynx)
[//]: # ([Web] Armory doesnt work)
[//]: # (To find server revision type `.server info` command in the game chat.)

**Description**: 

I have voidwalker that had learn sacrifice.
Clicking on the x sacrifice does nothing

**Current behaviour**:

**Expected behaviour**: 

**Server Revision**:

**Comment by Tereneckla** [comment]
All ranks are working just fine. Did your voidwalker not have enough mana?

**Comment by hillelg123** [comment]
In town I summoned a new vw. I and the VW full health and mana. I tried to press the X for sacrifice and nothing happened. Warlock name is Wiccan. Another strange thing is that when I mouse over the X it says "sacrifice rank 1". I read enough books to be in a higher rank than that. I tested a couple of minutes ago, 9:00 server time.

**Comment by Tereneckla** [comment]
You have to pull the new rank from the spellbook into the pet bar yourself,
