### ISSUE TITLE
Final Boss in AV Evade after cyclone/blind 

### ISSUE THREAD

**Issue by najhorsi** [Atlantiss/NetherwingBugtracker#7925]
[//]: # (Enclose links to things related to the bug using http://wowhead.com or any other TBC database.)
[//]: # (You can use screenshot ingame to visual the issue.)
[//]: # (Write your tickets according to the format:)
[//]: # ([Quest][Azuremyst Isle] Red Snapper - Very Tasty!)
[//]: # ([NPC] Magistrix Erona)
[//]: # ([Spell][Mage] Fireball)
[//]: # ([Npc][Drop] Ghostclaw Lynx)
[//]: # ([Web] Armory doesnt work)
[//]: # (To find server revision type `.server info` command in the game chat.)

**Description**: 
Final Boss in AV Evade after he gets cyclone or blind, it should retarget another player and not evade. The opponents can easily win because of this bug.

**Current behaviour**:
Final Boss evade after cyclone or blind

**Expected behaviour**: 
Final Boss should retarget another player and not leave the combat

**Server Revision**:

**Comment by danbopes** [comment]
Please provide evidence this is how it should work in TBC.

**Comment by najhorsi** [comment]
What type of evidence do you need ?

**Comment by danbopes** [comment]
That the boss shouldn't evade, and should switch/retarget another player. Last I remember, this was how this worked.

**Comment by najhorsi** [comment]
So every AV I played, some enemy druid cyclone Tank and the boss went back to his place (Evade)

**Comment by Godmatik** [comment]
He has asking for proof from how it was back during TBC in Retail.
