### ISSUE TITLE
PROBLEM SUCCUBUS PET WARLOCK

### ISSUE THREAD

**Issue by diegcagi** [Atlantiss/NetherwingBugtracker#7926]
Hello and i appreciate this space for can read my issue. This is my problem, im trying to keep doing my warlock missions and can get the succubus but that is the issue, im looking for help with warlock Friends and internet guides and Steel the same problem i can keep doing quests because dont appear, maybe i lost one step or i think maybe my character is bug.  Thanks for read this ticket and have a great day.

**Comment by Godmatik** [comment]
try a GM ticket in-game instead
