### ISSUE TITLE
"Budd's Map of Zul'Aman" not respawning after being looted

### ISSUE THREAD

**Issue by bbcgit** [Atlantiss/NetherwingBugtracker#7927]
[Quest][Zul'Aman] Promises, Promises...

The quest item "Budd's Map of Zul'Aman" did not respawn for our group after it was looted for the first time, re-entered the same ID the day after and it still was not spawned.

**Comment by danbopes** [comment]
I believe this was fixed in the last update. Can you please double check.

**Comment by bbcgit** [comment]
Confirming that this reset it was still lootable after the first looting. Seems fixed
