### ISSUE TITLE
Stealthed Succubus

### ISSUE THREAD

**Issue by juroki123** [Atlantiss/NetherwingBugtracker#7928]
[//]: # (Enclose links to things related to the bug using http://wowhead.com or any other TBC database.)
[//]: # (You can use screenshot ingame to visual the issue.)
[//]: # (Write your tickets according to the format:)
[//]: # ([Quest][Azuremyst Isle] Red Snapper - Very Tasty!)
[//]: # ([NPC] Magistrix Erona)
[//]: # ([Spell][Mage] Fireball)
[//]: # ([Npc][Drop] Ghostclaw Lynx)
[//]: # ([Web] Armory doesnt work)
[//]: # (To find server revision type `.server info` command in the game chat.)

**Description**: In Arcatraz (HC) the stationary stealthed Succubus standing near the boxes on the right side of the room before bosses Dalilah/Wrath-Scryer, does NOT reveal/pull as it should. 

**Current behaviour**: Succubus could not be pulled by aoe damaging spells, shouts nor mass dispel, and she could not be revealed by flare. The party managed to pull her by placing explosive trap on her spot, or by pulling the boss Wrath-Scryer, in which case she would insta join the combat and reveal herself.

**Expected behaviour**: Should be revealed with flare, pulled by any damaging spell and/or shouts, and should be body-pullable.

**Server Revision**:  [3606]

**Comment by therealCrysis** [comment]
https://youtu.be/u2LeL2TR86M

Just tested it on PTR. 
There are two NPCs in the boss room. One of them appears to stay, second is patrolling. 
As you can see on video above - flare did reveal them. They were also body pulled.
