### ISSUE TITLE
[Item] Necks buffs

### ISSUE THREAD

**Issue by Msbhv1** [Atlantiss/NetherwingBugtracker#7929]
**Description**: Hello, 

Every time I equip a necklace like Eye of the Night or Chain of Twilight Owl to buff my party as druid and I switch forms the necklace buff tends to dissapear.It happens even during combat when I use Rebirth and then switch back to Moonkin form.

**Current behaviour**: Necklace buffs dissapears

**Expected behaviour**: I have been looking for a proof that it should dissapear but didn't find any. So i think it should stick no matter of the form.

**Comment by therealCrysis** [comment]
https://youtu.be/Gi7Iyvvy_HQ

Okay, so these items:
https://www.wowhead.com/item=24116/eye-of-the-night
https://www.wowhead.com/item=24121/chain-of-the-twilight-owl
https://www.wowhead.com/item=24117/embrace-of-the-dawn
give some nice buffs which are shared to party/raid members.

One part of its mechanic works properly - if caster loses this buff -> whole group will lose it.
About switching forms... I am not sure, but if class buffs stay on druid after he switches form - this buff should works similarly.

**Comment by Godmatik** [comment]
Still happens and it is annoying. If I go into a new druid form, the neck buff goes away and won't come back.

**Comment by Wolffenstein** [comment]
Fixed in rev 3702.
