### ISSUE TITLE
[Item][Blacksmithing] Unable to create second Drakefist Hammer

### ISSUE THREAD

**Issue by nikotakk** [Atlantiss/NetherwingBugtracker#7930]
[//]: # (Enclose links to things related to the bug using http://wowhead.com or any other TBC database.)
[//]: # (You can use screenshot ingame to visual the issue.)
[//]: # (Write your tickets according to the format:)
[//]: # ([Quest][Azuremyst Isle] Red Snapper - Very Tasty!)
[//]: # ([NPC] Magistrix Erona)
[//]: # ([Spell][Mage] Fireball)
[//]: # ([Npc][Drop] Ghostclaw Lynx)
[//]: # ([Web] Armory doesnt work)
[//]: # (To find server revision type `.server info` command in the game chat.)

**Description**: 
Trying to create a second Drakefist Hammer (https://www.wowhead.com/item=28437/drakefist-hammer?bonus=6883) fails due to "You can't carry any more of those items": 
![image](https://user-images.githubusercontent.com/17097583/109398221-3773b900-7944-11eb-90d8-a10c3cd797ca.png)

The weapon is not unique ( I dualwielded them in Retail):
![image](https://user-images.githubusercontent.com/17097583/109398055-eca57180-7942-11eb-8245-d7422b11273e.png)

**Current behaviour**:

**Expected behaviour**: 
Second weapon should be created and be able to wield it.

**Server Revision**: 3607

**Comment by Tereneckla** [comment]
Delete your cache folder, they are unique until 2.4
