### ISSUE TITLE
Defias Bandits run through fences instead of going around them 

### ISSUE THREAD

**Issue by Staburus** [Atlantiss/NetherwingBugtracker#7931]
**Description**: 
Defias Bandits in the Northshire Valley as well as Elwynn Forest run through or over fences instead of going around the fence to get you
**Current behaviour**:

**Expected behaviour**: 

**Server Revision**:

**Comment by EtheriousNW** [comment]
This is intended behaviour https://www.youtube.com/watch?t=52&v=ybn_YXTJBWc&feature=youtu.be
