### ISSUE TITLE
Princess in Elwynn Forest respawns too fast

### ISSUE THREAD

**Issue by Staburus** [Atlantiss/NetherwingBugtracker#7932]
**Description**: 
Respawn time is too fast than how it should be
**Current behaviour**:

**Expected behaviour**: 

**Server Revision**:

**Comment by therealCrysis** [comment]
It apparently has 10-12 seconds respawn time which indeed can be annoying for low levels trying to solo Princess (330)

increasing respawn time to maybe 45 seconds would not be a bad idea.

https://www.youtube.com/watch?v=L95HGiebI2k

**Comment by Wolffenstein** [comment]
Fixed in rev 3656.
