### ISSUE TITLE
The Bundle of Trouble Quest

### ISSUE THREAD

**Issue by Staburus** [Atlantiss/NetherwingBugtracker#7933]
**Description**: 
While collecting the wood some of them don't disappear showing you collected them and just keep sparkling but unable to right click them
**Current behaviour**:

**Expected behaviour**: 

**Server Revision**:

**Comment by therealCrysis** [comment]
https://youtu.be/XH20Bvjn19w

Bundle of Wood - 13872
Whole quest works properly. The only issue is that apparently after looting one piece of these items, there is little visual bug which allows object with "sparkly" animation to stay on the ground for few seconds only. These items respawn properly though so it does not break gameplay at all. It's obvious that you will not be able to collect 8/8 bundles of wood only from one spot, THAT would be a bigger issue.
