### ISSUE TITLE
Big Battle Bear dismounts gnome in shallow water

### ISSUE THREAD

**Issue by Rhegon94** [Atlantiss/NetherwingBugtracker#7935]
**Description**:  Big Battle Bear mount is bugged on gnome and it makes gnome get dismounted once he enters shallow water, meanwhile riding other mount and crossing the same shallow water does not dismount.

**Current behaviour**: Gnome getting dismounted in shallow water when it's riding Big Battle Bear mount.

**Expected behaviour**: Big Battle Bear mount should act like every other mount on gnome allowing it to cross shallow water.

**Server Revision**:

**Comment by EtheriousNW** [comment]
Doesn't seem able to reproduce this - any specific spots where this happens? A video would be helpful @Rhegon94

**Comment by therealCrysis** [comment]
https://youtu.be/77H6vsBNA8g

Tested it on PTR. It works fine - the moments when it dismounts it's when gnome starts swimming. And that's obvious that tauren would not dismount in the same places.
