### ISSUE TITLE
[Quest][Stormwind City]/[Feralas] Jonespyre's Request

### ISSUE THREAD

**Issue by netbean2** [Atlantiss/NetherwingBugtracker#7936]
**Description**: Hello, unless im missing a prereq, the mutually exclusive quests : [Jonespyre's Request from Stormwind City](https://tbc-twinhead.twinstar.cz/?quest=3787) & [Jonespyre's Request from Feralas](https://tbc-twinhead.twinstar.cz/?quest=3788) are missing. Im lvl 53, normally i should be able to get them starting from lvl 45. Eventhough this is a breadcrumb kind of quest, i checked the follow up quest : [The Mystery of Morrowgrain](https://tbc-twinhead.twinstar.cz/?quest=3791) and i could not take it directly.

**Current behaviour**: The mutually exclusive quests : [Jonespyre's Request from Stormwind City](https://tbc-twinhead.twinstar.cz/?quest=3787) & [Jonespyre's Request from Feralas](https://tbc-twinhead.twinstar.cz/?quest=3788) are missing ingame.

**Expected behaviour**: I should be able to take one of these 2 quests starting from lvl 45.

**Server Revision**: 3607

**Comment by Tereneckla** [comment]
You need to have done Un'goro Soil /Morrowgrain quests
