### ISSUE TITLE
[Enchanting] Formula: Enchant Ring - Stats - wrong reputation

### ISSUE THREAD

**Issue by Flacha88** [Atlantiss/NetherwingBugtracker#7937]
[//]: # (Enclose links to things related to the bug using http://wowhead.com or any other TBC database.)
[//]: # (You can use screenshot ingame to visual the issue.)
[//]: # (Write your tickets according to the format:)
[//]: # ([Quest][Azuremyst Isle] Red Snapper - Very Tasty!)
[//]: # ([NPC] Magistrix Erona)
[//]: # ([Spell][Mage] Fireball)
[//]: # ([Npc][Drop] Ghostclaw Lynx)
[//]: # ([Web] Armory doesnt work)
[//]: # (To find server revision type `.server info` command in the game chat.)

**Description**: 
https://www.wowhead.com/item=22538/formula-enchant-ring-stats was not changed with 2.3 patch. Was only moved from one quatermaster to another, but the item was not updated. 

**Current behaviour**:
Can be bought from Lower City quatermaster but to learn it still require The Scale of the Sands reputation. 

**Expected behaviour**: 
Should be bought from LC vendor and learning/using that should be dictated by LC reputation. 

**Server Revision**: 
Atlantiss Karazhan | Content patch: 2.1.0

**Comment by Tereneckla** [comment]
delete your cache to see the correct tooltip

**Comment by Flacha88** [comment]
I tryied it before without succes - now it suddenly helps... thank you
