### ISSUE TITLE
Fire Mage's Combustion talent

### ISSUE THREAD

**Issue by Amanveche** [Atlantiss/NetherwingBugtracker#7938]
Greetings! The issue I've encountered with the spell is that it isn't actually counting that bonus crit chance increase.
I have 32% crit chance with fire spells,and I've stacked up to 7 times the buff,which makes it +70% crit chance.
So with a chance to crit above the 100%,I still did a normal hit.
If possible to be double-checked,and fixed.
Many thanks in advance!

**Comment by Tereneckla** [comment]
Did that happen in pvp or against an enemy of a higher level than you?

**Comment by Amanveche** [comment]
I've noticed the issue while fighting the mana creatures at Kirin'var village,Netherstorm.








 >-------- Оригинално писмо --------

 >От: Tereneckla notifications@github.com

 >Относно: Re: [Atlantiss/NetherwingBugtracker] Fire Mage's Combustion talent
 (#7938)

 >До: Atlantiss/NetherwingBugtracker  

 >Изпратено на: 03.03.2021 01:33



 
 
  
  
  
Did that happen in pvp or against an enemy of a higher level than you?

**Comment by Tereneckla** [comment]
Barring misses I achieved 100% crits over a significant test period. I tested with 30% crit + 70% from Combustion.
Are you 100% sure you did not have 7 stacks just after that spell?

**Comment by Amanveche** [comment]
I m pretty sure I was above the 100%.I was 102,07% or somehting like that,not sure for the exact number,but the percentages were above the 100,which should be a critical hit and it wasnt,thats why I made the tiket. To be fair I've noticed that difference in the crit chance even earlier,but I was simply thinking that I have a bad RNG moment.But even now when playing,I am feeling that with crit chance around 70 or 80 percents it simply isnt critting..Something which wasn't happenning before-I could barelly stack the combustion buff more than 2 or 3 times,simply because my crit chance till then is growing,and the crits were obvious,but not anymore...








 >-------- Оригинално писмо --------

 >От: Tereneckla notifications@github.com

 >Относно: Re: [Atlantiss/NetherwingBugtracker] Fire Mage's Combustion talent
 (#7938)

 >До: Atlantiss/NetherwingBugtracker  

 >Изпратено на: 03.03.2021 16:51



 
 
  
  
  
Barring misses I achieved 100% crits over a significant test period. I tested with 30% crit + 70% from Combustion.
 Are you 100% sure you did not have 7 stacks just after that spell?

**Comment by Amanveche** [comment]
From today's botanica run. You see my crit chance with fire spells,and the 8 stacks of combustion.Hope that proves my point :]








 >-------- Оригинално писмо --------

 >От: Tereneckla notifications@github.com

 >Относно: Re: [Atlantiss/NetherwingBugtracker] Fire Mage's Combustion talent
 (#7938)

 >До: Atlantiss/NetherwingBugtracker  

 >Изпратено на: 03.03.2021 16:51



 
 
  
  
  
Barring misses I achieved 100% crits over a significant test period. I tested with 30% crit + 70% from Combustion.
 Are you 100% sure you did not have 7 stacks just after that spell?

**Comment by Tereneckla** [comment]
I guess you attached a file to the e-mail you are writing to reply to this topic. That does not work. You need to either add a link or upload it on github

**Comment by Amanveche** [comment]
![WoWScrnShot_030421_174955](https://user-images.githubusercontent.com/79943623/110027146-4ab6c800-7d3a-11eb-9004-31f1d6906f22.jpg)

**Comment by Tereneckla** [comment]
That just shows that the 3 crits during combustion weren't used up yet.

**Comment by Amanveche** [comment]
With 8 stacks of combustion and with my 32% it becomes 112% crit. Which means that on the previous cast with 7 stacks of combustion I did not made a critical hit with chances to crit above the 100% (~102%).Obvious bug with the talent.









 -------- Оригинално писмо --------

От: Tereneckla notifications@github.com

Относно: Re: [Atlantiss/NetherwingBugtracker] Fire Mage's Combustion talent
 (#7938)

До: Atlantiss/NetherwingBugtracker  

Изпратено на: 04.03.2021 22:47



 
 
  
  
  
That just shows that the 3 crits during combustion weren't used up yet.

**Comment by Tereneckla** [comment]
It does not show any combat log text of the spell you cast. One can see you gained the 8th stack of combustion, that ignite ticked and that fireball ticked.
All without timestamps.
The only conclusive things are:
You did not crit 3 times during combustion, because the buff is there.
You crit at some point during combustion, as you dealt damage with ignite there.

**Comment by Amanveche** [comment]
My intention with the screenshot wasn't to show any combat logs. I am showing the crit chances. Ignite ticks does NOT affect combustion...should be direct fire damage,not a dot. The fact , that I made 8 stacks of the buff,proves that on the previous cast,when I was with 7 stacks and was with ~102% crit (above 100%,hence-crittical hit!) I did NOT crit (when it should've).

**Comment by PeluWins** [comment]
Actually its impossible for him to have 8 stacks of combustion if he has basically 32% crit. Combustion stacks increase only when you don't crit with your fire spells.
 So at 7 stacks he had 102% of crit rating, so at this point every his fireball should be crit. It's impossible that his spell wouldn't be crit to increase the stack of combustion.

**Comment by Tereneckla** [comment]
![image](https://user-images.githubusercontent.com/50233983/110099456-9ea8c780-7da1-11eb-8cef-0cf534edba11.png)
Combustion gains a stack no matter if it was a crit or not

**Comment by Amanveche** [comment]
Yes. Combustion gains a stack no matter normal hit ot crit. The problem here,which you obviously can't see so far,is that above 100% crit chance is still normal hitting. Make your conclusions,I've made mine...

**Comment by Tereneckla** [comment]
As I said, you cannot see that there is a normal hit. Your screenshot only shows you gaining a combustion stack, ignite dot and fireball dot.

There also is a crit suppression of 1% per level your target is above yours. So as Thorngrin doesn't have a debuff that increases the chance he takes a critical strike (only improved seal of the crusader does that) you actually had a 99.94% chance to crit with a Fireball at 7 stack Combustion.

**Comment by Tereneckla** [comment]
As there was no meaningful contribution and I never could reproduce it.
