### ISSUE TITLE
BUG SUCCUBUS

### ISSUE THREAD

**Issue by diegcagi** [Atlantiss/NetherwingBugtracker#7941]
Good Morning. A few days ago I presented my case and please I need if you can help me by restarting the chain of missions to obtain the succubus with my warlock. since this bug is the mission and I have not been able to obtain it since I was level 20. It would be for me to redo the entire chain of missions. Thanks a lot.

**Comment by diegcagi** [comment]
My ingame name is DIOSELINA

**Comment by Tereneckla** [comment]
This is for bugreports, not gm contact. Either write a ticket ingame or get in contact on our discord https://discord.com/invite/jT24fut
