### ISSUE TITLE
[Item] Various Relics work wrong

### ISSUE THREAD

**Issue by Tereneckla** [Atlantiss/NetherwingBugtracker#7942]
[//]: # (Enclose links to things related to the bug using http://wowhead.com or any other TBC database.)
[//]: # (You can use screenshot ingame to visual the issue.)
[//]: # (Write your tickets according to the format:)
[//]: # ([Quest][Azuremyst Isle] Red Snapper - Very Tasty!)
[//]: # ([NPC] Magistrix Erona)
[//]: # ([Spell][Mage] Fireball)
[//]: # ([Npc][Drop] Ghostclaw Lynx)
[//]: # ([Web] Armory doesnt work)
[//]: # (To find server revision type `.server info` command in the game chat.)

**Description**: 
Relics all work the same way, if their text says "increases by up to". "up to" is the key phrase here. Those relics just add the listed value to the spelldamage or healing of those spells, meaning the coefficient and everything affect it.

**Current behaviour**:

These relics add double the listed amount flat to the spell: 
Totem of Ancestral Guidance (32330), Totem of the Void (28248), Totem of the Storm (23199), Ivory Idol of the Moongoddess (27518)

These relics add the listed amount flat to the direct and/or dot/hot portion of the spell. The spells with both components double dip from the relic here:
Totem of Impact (27984, 27947), Totem of Rage (22395), Idol of Rejuvenation (22398), Idol of the Moon (23917), Libram of the Eternal Rest (27917)

The added spelldamage here ignores the undercast penalty for some reason: Libram of Divine Purpose (33504)

**Expected behaviour**: 
All these relics just add their spelldamage or healing to your spelldamage/healing for the purpose of the listed spells

**Server Revision**: 
3608

**Comment by Wolffenstein** [comment]
Fixed in rev 3692.
