### ISSUE TITLE
Gnome Racial Spell (Escape Artist) doesn't work properly

### ISSUE THREAD

**Issue by Dankeca** [Atlantiss/NetherwingBugtracker#7943]
**Description**:  I'm playing a gnome warrior on Karazhan realm, used to be a night elf but swapped to gnome because of the racial. My issue is with the racial spell Escape Artist, which is crucial for me in arenas and PvP overall.

**Current behaviour**: I noticed that sometimes(not always) when a druid uses Entangling Roots on me, or a rogue applies Crippling Poison on me, and I use Escape Artist somehow the effect still remains and I'm still rooted(or crippling poison still stays on me). This happened to me more than once, I wrote a ticket to talk to a GM and he pointed me towards here. I know I said sometimes, but as I said it's a crucial spell for me and it cost me a few losses in arena.

**Expected behaviour**:  Escape Artist racial says: "Escapes the effect of ANY immobilization or movement speed reduction effect." I was thinking that I'm wrong, I thought maybe the druid has that talent which reduces the chance your spells will be dispelled, or the rogue has the talent with the same effect but for poisons. But then I thought, wait a minute.. I'm not dispelling it, am I? Spell clearly says that removes any immobilization or movement speed reduction effect.

**Server Revision**: 
First time doing a bug/issue report so I don't know what to say here :/

**Comment by Tereneckla** [comment]
Escape Artist is a dispell. It is working properly
