### ISSUE TITLE
[Rogue][Spell] Disarm Trap breaks stealth

### ISSUE THREAD

**Issue by Mastercry** [Atlantiss/NetherwingBugtracker#7944]
[//]: # (Enclose links to things related to the bug using http://wowhead.com or any other TBC database.)
[//]: # (You can use screenshot ingame to visual the issue.)
[//]: # (Write your tickets according to the format:)
[//]: # ([Quest][Azuremyst Isle] Red Snapper - Very Tasty!)
[//]: # ([NPC] Magistrix Erona)
[//]: # ([Spell][Mage] Fireball)
[//]: # ([Npc][Drop] Ghostclaw Lynx)
[//]: # ([Web] Armory doesnt work)
[//]: # (To find server revision type `.server info` command in the game chat.)

**Description**: 

**Current behaviour**: disarm trap breaks stealth

**Expected behaviour**: should not

**Server Revision**:

**Comment by therealCrysis** [comment]
https://youtu.be/5aEFZBYKjSM

It apparently breaks out Stealth and, according to wowhead comment section and wowwiki, it should not do this.

**Comment by Wolffenstein** [comment]
Fixed in rev 3654.
