### ISSUE TITLE
[Item] Darkmoon Card: Crusade

### ISSUE THREAD

**Issue by Lenni-s** [Atlantiss/NetherwingBugtracker#7947]
**Description**: 
this trinket should give you proc stack only when your spell is dealing damage to enemy target

**Current behaviour**:
currently you can spam blizzard/rain of fire on 0 targets and still get stacks of this trinket

**Expected behaviour**: 
trinket should give stack only when your spell is dealing damage

**Server Revision**: 
3610

**Comment by Tereneckla** [comment]
It should only proc of harmful spell hits.

**Comment by Wolffenstein** [comment]
Fixed in rev 3655.
