### ISSUE TITLE
[Profession] Alchemy Specialization dialogues require too high skill

### ISSUE THREAD

**Issue by Tereneckla** [Atlantiss/NetherwingBugtracker#7948]
[//]: # (Enclose links to things related to the bug using http://wowhead.com or any other TBC database.)
[//]: # (You can use screenshot ingame to visual the issue.)
[//]: # (Write your tickets according to the format:)
[//]: # ([Quest][Azuremyst Isle] Red Snapper - Very Tasty!)
[//]: # ([NPC] Magistrix Erona)
[//]: # ([Spell][Mage] Fireball)
[//]: # ([Npc][Drop] Ghostclaw Lynx)
[//]: # ([Web] Armory doesnt work)
[//]: # (To find server revision type `.server info` command in the game chat.)

**Description**: 
The quests for specializations are offered at skill 325 while the dialogues only are shown with skill 350
The npcs in question are Zarevhi (22427), Lauranna Thar'well (17909) and Lorokeem (19052)
Both the dialogue to learn and unlearn the specialization are affected.

**Current behaviour**:
Dialogues require skill 350
**Expected behaviour**: 
Dialogues require skill 325
**Server Revision**:  3612

**Comment by Wolffenstein** [comment]
Fixed in rev 3692.
