### ISSUE TITLE
[NPC] Darkweaver Syth (SH first boss) pulls additional pack with him during fight

### ISSUE THREAD

**Issue by Mikik3jr** [Atlantiss/NetherwingBugtracker#7949]
[//]: # (Enclose links to things related to the bug using http://wowhead.com or any other TBC database.)
[//]: # (You can use screenshot ingame to visual the issue.)
[//]: # (Write your tickets according to the format:)
[//]: # ([Quest][Azuremyst Isle] Red Snapper - Very Tasty!)
[//]: # ([NPC] Magistrix Erona)
[//]: # ([Spell][Mage] Fireball)
[//]: # ([Npc][Drop] Ghostclaw Lynx)
[//]: # ([Web] Armory doesnt work)
[//]: # (To find server revision type `.server info` command in the game chat.)

**Description**: 
First boss in SH HC was pulled. During the pull additional pack joined the fight. I didn't find out what was the issue.

**Current behaviour**:
[Just look at this](https://www.youtube.com/watch?v=horK0q4DAs4)

**Expected behaviour**: 
It should not happen imo.

**Server Revision**: 
3610

**Comment by Mikik3jr** [comment]
Update: this happened twice (the video was the 2nd). When we pulled the boss out of the room they didn't come.

**Comment by Wolffenstein** [comment]
Cannot reproduce
