### ISSUE TITLE
[Quest] Steelsnap

### ISSUE THREAD

**Issue by Pennywise4569** [Atlantiss/NetherwingBugtracker#795]
[//]: # (Enclose links to things related to the bug using http://wowhead.com or any other TBC database.)
[//]: # (You can use screenshot ingame to visual the issue.)
[//]: # (Write your tickets according to the format:)
[//]: # ([Quest][Azuremyst Isle] Red Snapper - Very Tasty!)
[//]: # ([NPC] Magistrix Erona)
[//]: # ([Spell][Mage] Fireball)
[//]: # ([Npc][Drop] Ghostclaw Lynx)
[//]: # ([Web] Armory doesnt work)

**Description**: I killed Steelsnap in Thousand Needles, and died to his two buddies he patrols with. When I came back I was unable to loot Steelsnap for his rib.

**Current behaviour**: Can't loot steelsnap on kill, at least after dying and running back to corpse.

**Expected behaviour**: Should be able to loot for his rib.

**Server Revision**:

**Comment by Easyfraggy** [comment]
Can you elaborate, was his corpse despawned or were you unable to loot his corpse?

**Comment by Dpthx** [comment]
was the corpse sparkling before you died?

**Comment by Pennywise4569** [comment]
Yes, the corpse was sparkling before I died. When I got back it was still sparkling, and able to be right clicked. My character would start to bend down but immediately stand back up with no loot window. This occurred until the body despawned.

**Comment by Tereneckla** [comment]
Fixed
