### ISSUE TITLE
[Item] Mists of Dawn banner has no description when right clicking on it

### ISSUE THREAD

**Issue by ta340** [Atlantiss/NetherwingBugtracker#7950]
**Description**: 
Mists of Dawn banner has no description when right clicking on it

**Current behaviour**:
Mists of Dawn banner has no description when right clicking on it

**Expected behaviour**: 
Should list some lore text, as seen here: https://www.wowhead.com/object=177207/mists-of-dawn

**Server Revision**: 
3610

**Comment by Tereneckla** [comment]
![image](https://user-images.githubusercontent.com/50233983/111310926-e65f0700-865d-11eb-99d5-5783c322cb16.png)

These are missing aswell:
https://classic.wowhead.com/object=177209/hatred-of-the-centaur
https://classic.wowhead.com/object=177208/the-white-stag-and-the-moon

**Comment by Wolffenstein** [comment]
Fixed in rev 3834.
