### ISSUE TITLE
Fel Lotus not droping with  [Netherbloom]

### ISSUE THREAD

**Issue by dontfaket30** [Atlantiss/NetherwingBugtracker#7951]
**Description**: 
Farmed over 2k+  [Netherbloom] and 0 fel lotus
Can you plz check is bug or something.

Fel lotus  drop % should be increased

Fel lotus cost more than FLASKS.

**Comment by Tereneckla** [comment]
Drop rate has not been changed and they still drop.

**Comment by Godmatik** [comment]
Fel Lotus can sometimes cost more because elixir spec alchemists can proc extra flasks when crafting. 

I just looted 4 lotus during my farming these past couple of hours in netherstorm.
