### ISSUE TITLE
[Quest][Hillsbrad Foothills] Soothing Turtle Bisque

### ISSUE THREAD

**Issue by Skandergod** [Atlantiss/NetherwingBugtracker#7952]
[//]: # (Enclose links to things related to the bug using http://wowhead.com or any other TBC database.)
[//]: # (You can use screenshot ingame to visual the issue.)
[//]: # (Write your tickets according to the format:)
[//]: # ([Quest][Azuremyst Isle] Red Snapper - Very Tasty!)
[//]: # ([NPC] Magistrix Erona)
[//]: # ([Spell][Mage] Fireball)
[//]: # ([Npc][Drop] Ghostclaw Lynx)
[//]: # ([Web] Armory doesnt work)
[//]: # (To find server revision type `.server info` command in the game chat.)

![WoWScrnShot_031821_031404](https://user-images.githubusercontent.com/25189627/111591413-cd5d6f80-879d-11eb-882c-4de17ede9e96.jpg)
![WoWScrnShot_031821_031602](https://user-images.githubusercontent.com/25189627/111591537-f7169680-879d-11eb-83d6-21648ca55e01.jpg)

Description**: 

The snapjaws are not dropping the turtle meat as they should, i killed 12 so far and yet not a single drop of meat, in wowhead says it's 30% chance. https://classic.wowhead.com/quest=7321/soothing-turtle-bisque , https://classic.wowhead.com/item=3712/turtle-meat#dropped-by

**Current behaviour**:
Snapjaws are not dropping the quest Item

**Expected behaviour**: 
Snapjaws are should drop the quest Item at a 30% rate

**Server Revision**: 
3613

**Comment by Skandergod** [comment]
Sorry if i'm miss interpreting the problem, so far i have killed 20 turtles but only got 1 drop of meat, maybe im just the unluckiest guy ever or something, but i'll keep updating the issue with my % droprates

**Comment by netbean2** [comment]
hi @Skandergod 
I confirm the quest works, its just the drop rate is waaay too low.

**Comment by Skandergod** [comment]
Alright, i managed to finish the quest with a healthy 11 in 39 kills, i managed to start getting meat drops when started killing snapjaws a in the river where my character is located in the 1st capture.

![WoWScrnShot_031821_034756](https://user-images.githubusercontent.com/25189627/111595534-98075080-87a2-11eb-895e-b623bff5a879.jpg)

I killed the first 12 snapjaws in the zone of the 2nd capture, the ones that gave me 0 meat drops 12 kills, im sorry if i miss interpreted the drop chances as i said before, but this felt weird for me

![unknown](https://user-images.githubusercontent.com/25189627/111595595-a81f3000-87a2-11eb-8a43-794aa81ea5e4.png)

when i moved up to the river, snapjaw kills started giving me meat drops.

**Comment by Skandergod** [comment]
> hi @Skandergod
> I confirm the quest works, its just the drop rate is waaay too low.

thank you, im really sorry if i miss interpreted the % rates, it just felt weird that i had to switch the farming place in order to start getting meat drops.

**Comment by Tereneckla** [comment]
![image](https://user-images.githubusercontent.com/50233983/111602832-0adcef80-87d4-11eb-9061-61efcc2395c9.png)
Classic wow also has the droprate too high (These values are accurate, because it's not a quest item
