### ISSUE TITLE
[Quest][Eastern Plaguelands] Establishing New Outposts

### ISSUE THREAD

**Issue by netbean2** [Atlantiss/NetherwingBugtracker#7953]
**Description**: the quest [Establishing New Outposts](https://tbc-twinhead.twinstar.cz/?quest=9664) is not given from the npc [Emissary Whitebeard](https://tbc-twinhead.twinstar.cz/?npc=17069) . Found an old ticket related to this NPC : https://github.com/Atlantiss/NetherwingBugtracker/issues/1764 but it does not mention anything about the quest he gives.

**Current behaviour**: the quest [Establishing New Outposts](https://tbc-twinhead.twinstar.cz/?quest=9664) is not given from the npc [Emissary Whitebeard](https://tbc-twinhead.twinstar.cz/?npc=17069) . By checking with Tereneckla at discord, he/she said that the quest is simply not activated

**Expected behaviour**: This quest should be given by the mentioned npc without any prereq at all starting at lvl 55.

**Server Revision**: 3613

**Comment by Wolffenstein** [comment]
Fixed in rev 3834.
