### ISSUE TITLE
[Spell][Druid] Lifebloom - Blooming effect acting weird.

### ISSUE THREAD

**Issue by cladyz** [Atlantiss/NetherwingBugtracker#7955]
**Description**: 
Lifebloom final heal (upon completion of the 6 sec duration) is not working properly. 

**Current behaviour**:
Lifebloom heal over time effect is working properly, as well as blooming for the correct amount upon 6sec duration. 
However, extra stacks of Lifebloom (x2 or x3) do not modify the amount healed upon completion of the 6sec duration. As of 22nd of March 2021 it is healing for the exact same amount at x1, x2 and x3 stacks. 

**Expected behaviour**: 
The amount healed upon blooming is supposed to be modified by the corresponding amount of stacks. I am not aware of the intended modifier (600 final healing on x1 is not supposed to be 1200 on x2, however, it's not supposed to be 600 on x2 either).

**Server Revision**: 
3610

**Comment by Tereneckla** [comment]
The bloom is unaffected by the number of stacks and that is the correct behavior.
![image](https://user-images.githubusercontent.com/50233983/111990408-89f36000-8b13-11eb-9ba4-d7db7aa79faa.png)

**Comment by cladyz** [comment]
> The bloom is unaffected by the number of stacks and that is the correct behavior.

As mentioned before, it is not expected to multiply the effect depending on the number of stacks, however, the amount of stacks affected the final bloom by a comparatively small amount. Point being, it's never been the same with x2 and x3. 
Even on Karazhan it's been the case until recent week(s).

Is there a source you're quoting when saying the opposite? 
What you linked is a completely different expansion and was in fact affected directly by x2 and x3 (1 stack 600, 2 stacks 1200, 3 stacks 1800). 
My point is it's not supposed to be (1 stack 600, 2 stacks 600, 3 stacks 600). Supposed to be modified based on some other numbers (approx 1 stack 600, 2 stacks 698, 3 stacks 741 or something like that)

**Comment by Tereneckla** [comment]
![image](https://user-images.githubusercontent.com/50233983/111991640-d25f4d80-8b14-11eb-8b54-56f712bdcd48.png)
