### ISSUE TITLE
[Battleground][NPC] Able to kill boss with towers.

### ISSUE THREAD

**Issue by PacMan1993** [Atlantiss/NetherwingBugtracker#7956]
Hello, I'm a player from your server.
I want to report a bug that needs to be fixed. 
Problem is: Altrec Velly, Bossies Vann & Dereck is one pulling can separate from marshals, and marshals and easy can kill boss, without cap towers, and this AV duration is 5 min...
That's not how it should work Altrac Velly..
They just need to fix it so they can't separate Dereck & vann from marshals on pull, that they have to fight inside, and thus give the charm of playing, that AV is played properly and properly. 
I hope you like me and that you will do it, thanks in advance... :)

**Comment by Metalica** [comment]
Derek is now linked with all guard and 2 wolfs in the room:

UPDATE `creature_linking_template` SET `master_entry` = 11946, `flag` = 1, `search_range` = 15 WHERE `entry` = 14776 AND `map` = 530;

UPDATE `creature_linking_template` SET `master_entry` = 11946, `flag` = 1, `search_range` = 15 WHERE `entry` = 14773 AND `map` = 530;

UPDATE `creature_linking_template` SET `master_entry` = 11946, `flag` = 1, `search_range` = 15 WHERE `entry` = 0 AND `map` = 0;

UPDATE `creature_linking_template` SET `master_entry` = 11946, `flag` = 1, `search_range` = 15 WHERE `entry` = 0 AND `map` = 0;

UPDATE `creature_linking_template` SET `master_entry` = 11946, `flag` = 1, `search_range` = 15 WHERE `entry` = 0 AND `map` = 0;

UPDATE `creature_linking_template` SET `master_entry` = 11946, `flag` = 1, `search_range` = 15 WHERE `entry` = 12122 AND `map` = 530;

UPDATE `creature_linking_template` SET `master_entry` = 11946, `flag` = 1, `search_range` = 15 WHERE `entry` = 12121 AND `map` = 530;

**Comment by Metalica** [comment]
Vandar is now linked with all guards inside the room:

UPDATE `creature_linking_template` SET `master_entry` = 11948, `flag` = 1, `search_range` = 15 WHERE `entry` = 14768 AND `map` = 530;

UPDATE `creature_linking_template` SET `master_entry` = 11948, `flag` = 1, `search_range` = 15 WHERE `entry` = 0 AND `map` = 0;

UPDATE `creature_linking_template` SET `master_entry` = 11948, `flag` = 1, `search_range` = 15 WHERE `entry` = 14766 AND `map` = 530;

UPDATE `creature_linking_template` SET `master_entry` = 11948, `flag` = 1, `search_range` = 15 WHERE `entry` = 12127 AND `map` = 530;

UPDATE `creature_linking_template` SET `master_entry` = 11948, `flag` = 1, `search_range` = 15 WHERE `entry` = 14769 AND `map` = 530;

UPDATE `creature_linking_template` SET `master_entry` = 11948, `flag` = 1, `search_range` = 15 WHERE `entry` = 14764 AND `map` = 530;

UPDATE `creature_linking_template` SET `master_entry` = 11948, `flag` = 1, `search_range` = 15 WHERE `entry` = 14763 AND `map` = 530;

UPDATE `creature_linking_template` SET `master_entry` = 11948, `flag` = 1, `search_range` = 15 WHERE `entry` = 14765 AND `map` = 530;

UPDATE `creature_linking_template` SET `master_entry` = 11948, `flag` = 1, `search_range` = 15 WHERE `entry` = 14762 AND `map` = 530;

**Comment by Metalica** [comment]
If it would not work as it should, just change from flag 1 to flag 2;

1 | FLAG_AGGRO_ON_AGGRO | the "slave" aggroes when the "master" aggroes

2 | FLAG_TO_AGGRO_ON_AGGRO | the master aggroes when the slave aggroes

**Comment by Wolffenstein** [comment]
We don't have `creature_linking_template` :(

**Comment by Godmatik** [comment]
Closing - will consolidate all outstanding AV issues into one thread now.
