### ISSUE TITLE
[Profession] Some herbs give this error message "You do not have permission to loot this corpse"

### ISSUE THREAD

**Issue by MnmZilla** [Atlantiss/NetherwingBugtracker#7957]
Some herb nodes seem to have become bugged, I noticed this issue a few days ago. Personally it's been mostly Dreaming glories but some felweed have had this issue as well. I tried reinstalling the client, disabling addons, clearing cache folder but none of these things cleared this issue for me. Asking around in world chat I realised I was no the only person with this problem.
![WoWScrnShot_032321_171831](https://user-images.githubusercontent.com/10366139/112180401-d31edf00-8bfb-11eb-8d03-fa331b5cfe98.jpg)

**Comment by eri1997** [comment]
This also happens to mining nodes

**Comment by danbopes** [comment]
This is all fixed.
