### ISSUE TITLE
[Spell][Paladin] Judgement change on mob fails

### ISSUE THREAD

**Issue by lasseloef** [Atlantiss/NetherwingBugtracker#7958]
[//]: # (Enclose links to things related to the bug using http://wowhead.com or any other TBC database.)
[//]: # (You can use screenshot ingame to visual the issue.)
[//]: # (Write your tickets according to the format:)
[//]: # ([Quest][Azuremyst Isle] Red Snapper - Very Tasty!)
[//]: # ([NPC] Magistrix Erona)
[//]: # ([Spell][Mage] Fireball)
[//]: # ([Npc][Drop] Ghostclaw Lynx)
[//]: # ([Web] Armory doesnt work)
[//]: # (To find server revision type `.server info` command in the game chat.)

**Description**: 
At random times if Judgement of the Crusader has been applied to a mob, trying to change to, for example, judgement of wisdom or justice fails and crusader judgement is still applied on the mob.

**Current behaviour**:
Mob has the Judgement of the Crusader debuff
Judgement of wisdom is used on the mob
Judgement of the Crusader is still applied to the mob

**Expected behaviour**: 
Mob has the Judgement of the Crusader debuff
Judgement of wisdom is used on the mob
Judgement of Wisdom is applied to othe mob

**Server Revision**: 
3613

**Comment by Tereneckla** [comment]
Are those cases with you twisting to seal of wisdom shortly before the judgement?

**Comment by lasseloef** [comment]
> Are those cases with you twisting to seal of wisdom shortly before the judgement?

As in I would twist to another seal and then immediately judge it? I don't think so. I believe it has still happened even if I had fx. seal of wisdom on for a few seconds. I'll keep an eye on it and come back to you

**Comment by lasseloef** [comment]
Yes it seems like it. I was able to recreate the "bug".

If you twist to another seal and immediately press judgement afterwards, the game isn't quick enough to actually see that you've changed seal, so it judges the prior seal you were using.

**Comment by Tereneckla** [comment]
#6405 
Was a hackfix for spelldelay that wasn't removed
