### ISSUE TITLE
[Core] Threat Table Updates During Stun

### ISSUE THREAD

**Issue by F4play** [Atlantiss/NetherwingBugtracker#7959]
[From Patch 2.4.3 Notes](https://wowwiki-archive.fandom.com/wiki/Patch_2.4.3): When a stun wears off, the creature that was stunned will prefer the last target with the highest threat, versus the current target.

**Current behaviour**: Threat table calculates threat and updates during stuns. 

**Expected behaviour**: Threat table shouldn't be affected during stun. Whoever had the highest threat prior to the stun landing should have threat of the mob after the stun wears off.

**Comment by F4play** [comment]
This video from 2008 has some good examples during a ZA run where the person who had the highest threat on a mob pre-stun still maintains the highest threat after a stun. https://www.youtube.com/watch?v=eczxxR7hnkQ

**Comment by Wolffenstein** [comment]
Very interesting. So everyone should be doing 0 threat to stunned targets? That sounds really weird. Is that still a thing in later expansions?

**Comment by F4play** [comment]
> Very interesting. So everyone should be doing 0 threat to stunned targets? That sounds really weird. Is that still a thing in later expansions?

I've been looking for some good videos to help showcase if this change happened or not, but it's been hard to find something during TBC. I'll see if I can find something from WOTLK era to see if this change was actually working as the patch notes suggest or if it was never really implemented.

**Comment by Godmatik** [comment]
Can't find any evidence of this,
