### ISSUE TITLE
[Item] Gas Clouds Unreachable in Telaar, Nagrand

### ISSUE THREAD

**Issue by SwimzwithSharkz** [Atlantiss/NetherwingBugtracker#7960]
**Description**: At times there are now Two and often Three Gas Clouds that are unreachable by engineers to extract the motes of air from in Telaar, Nagrand. 

**Current behaviour**: See above. The Gas Clouds are far away from platforms. Two are permanent this way. One is just to the left of Flight Master and the other is at 56. 65. 
At times a third is stuck also.

**Expected behaviour**: Usually all but the one by FM is reachable & can be extracted.
welp, just read the below link and this Was a Known Issue sigh. 
https://wowwiki-archive.fandom.com/wiki/Windy_Cloud

**Server Revision**: 3616

Dan, can you unstick them plz and prevent this, 
perhaps to newer spawn points? TY

**Comment by Drevil-Dion** [comment]
Flight path one in nagrand seems to have been resolved with the 2.4 update I have not seen it spawn there since the update.

**Comment by Godmatik** [comment]
Two of them already resolved in the past.
The third unreachable one is listed here and Etherious will be fixing it soon:
https://github.com/Atlantiss/NetherwingBugtracker/issues/8874
