### ISSUE TITLE
<The Deadliest Trap Ever Laid>

### ISSUE THREAD

**Issue by Calsifer98** [Atlantiss/NetherwingBugtracker#7962]
[//]: # https://tbcdb.com/?quest=11101
[//]: # [Quest] The Deadliest Trap Ever Laid
[//]: # [NPC] Commander Hobb

**Description**: 
Deadliest Trap ever laid is a daily quest from both aldors and scryers that give reputation for the Netherwing faction.
**Current behaviour**:
The quest is a one time only and it's not repeatable
**Expected behaviour**: 
The quest should be a daily and so repeatable every day 
**Server Revision**:

**Comment by Tereneckla** [comment]
It is repeatable, there are cases where the event can break so that the commander stays in his not questgiver state
