### ISSUE TITLE
[Battleground] [Target] Unable to Cursor Target Certain Foe, & Strange Icons. Updated

### ISSUE THREAD

**Issue by SwimzwithSharkz** [Atlantiss/NetherwingBugtracker#7963]
[//]: # (Enclose links to things related to the bug using http://wowhead.com or any other TBC database.)
[//]: # (You can use screenshot ingame to visual the issue.)
[//]: # (Write your tickets according to the format:)
[//]: # ([Quest][Azuremyst Isle] Red Snapper - Very Tasty!)
[//]: # ([NPC] Magistrix Erona)
[//]: # ([Spell][Mage] Fireball)
[//]: # ([Npc][Drop] Ghostclaw Lynx)
[//]: # ([Web] Armory doesnt work)
[//]: # (To find server revision type `.server info` command in the game chat.)

**Description**: Occasionally in Battlegrounds, usually Arathi Basin & WSG, I will get a strange cursor icon
& unable to Cursor Click my selected target. So I must use /tar or my kb key /t
I would like to know if this is a glitch or hack plz. (it doesn't happen on All targets in bg, just Consistently
the Specific One, if this is occurring.)
& the strange icon does not Appear when taking a screenshot. Suspicious.

**Current behaviour**: See above. The icon is a greyish red circle w/ a rectange at a 90 degree angle 
coming out from sw side of it. I looked up the WoW TBC cursor icons but didn't find it.
* Update: It just occurred again recently in Arathi Basin, I could not get this toon by mouse click and it had a Different Weird Icon, YET it did show up on a screenshot.  https://imgur.com/a/JbR65MF
* there can be so many near me that at times I prefer to use cursor vs /t or keep going thru /t to get the toon I want to gank. ty

**Expected behaviour**: The usual cursor icon should be there on /targets and clickable to acquire.

**Server Revision**: 3616

**Comment by Drevil-Dion** [comment]
That icon is a old classic icon as can be seen in the link below I have not been able to find any information about what it might have been used for so far but will update when I have found any information.

[img](https://i.imgur.com/Owpjrr3.png)

**Comment by Drevil-Dion** [comment]
found out why the image shows up when a player die's in a battleground body becomes lootable (skinnable sort of) hence the name of the icon SkinHorde

This is working as it should so can be closed.

**Comment by Wolffenstein** [comment]
If there's an issue with skinnable flag persisting after revival, it should hopefully be fixed in rev 3631.
