### ISSUE TITLE
[Item] Gnomish Battle Chicken

### ISSUE THREAD

**Issue by BokChoyWarrior** [Atlantiss/NetherwingBugtracker#7964]
[//]: # (Enclose links to things related to the bug using http://wowhead.com or any other TBC database.)
[//]: # (You can use screenshot ingame to visual the issue.)
[//]: # (Write your tickets according to the format:)
[//]: # ([Quest][Azuremyst Isle] Red Snapper - Very Tasty!)
[//]: # ([NPC] Magistrix Erona)
[//]: # ([Spell][Mage] Fireball)
[//]: # ([Npc][Drop] Ghostclaw Lynx)
[//]: # ([Web] Armory doesnt work)
[//]: # (To find server revision type `.server info` command in the game chat.)

**Description**: 
Gnomish Battle Chicken does not spawn at correct level.

**Current behaviour**:
Gnomish Battle Chicken spawns at level 1, despite the player's engineering level.

**Expected behaviour**: 
Should spawn at level [Player's engineering level / 5]
See: [https://wowwiki-archive.fandom.com/wiki/Gnomish_Battle_Chicken](https://wowwiki-archive.fandom.com/wiki/Gnomish_Battle_Chicken)

**Server Revision**: 
3617

**Comment by Wearetestingstuff** [comment]
Just to add more information to this post in the hopes that this will be fixed, for the majority of TBC the pets stopped scaling with engineering level but in 2.4 they were changed to be level 55 and in 2.4.3 they were changed to scale with engineering level (going up to either 73 or 75, can not find confirmation on 73 or 75). 

You can see the patch note revisions at the bottom (this would apply to all engineering pets, for a specific example the arcanite dragonling would also scale)

These two pets specifically on a 2.4.3 patch are pretty significant raid buffs and could be utilized in pretty unique ways, especially arcanite dragonling. Fixing these you might see some pretty interesting consumes and strategies evolve. 

https://wowwiki-archive.fandom.com/wiki/Gnomish_Battle_Chicken#:~:text=The%20Gnomish%20Battle%20Chicken%20is,90%20at%20450%20engineering.).

**Comment by Wolffenstein** [comment]
Fixed in rev 3671.
