### ISSUE TITLE
Quest says Complete - Yellow questionmark - but items are 3/5 and not attainable by mobs

### ISSUE THREAD

**Issue by evringelly** [Atlantiss/NetherwingBugtracker#7966]
[//]: # (Enclose links to things related to the bug using http://wowhead.com or any other TBC database.)
[//]: # (You can use screenshot ingame to visual the issue.)
[//]: # (Write your tickets according to the format:)
[//]: # ([Quest][Azuremyst Isle] Red Snapper - Very Tasty!)
[//]: # ([NPC] Magistrix Erona)
[//]: # ([Spell][Mage] Fireball)
[//]: # ([Npc][Drop] Ghostclaw Lynx)
[//]: # ([Web] Armory doesnt work)
[//]: # (To find server revision type `.server info` command in the game chat.)

**Description**: 

**Current behaviour**:

**Expected behaviour**: 

**Server Revision**:

**Comment by Godmatik** [comment]
Which quest?

**Comment by danbopes** [comment]
Needs more information:

We can't help if we don't have any information, or way to reproduce the issue. The Template that was asked of you when you created the issue was not optional: Without this information we cannot proceed.

**Comment by evringelly** [comment]
It's already fixed, thank you!


________________________________

**Comment by evringelly** [comment]
> Which quest?

It's been fixed, thanks!
