### ISSUE TITLE
The Battle of Darrowshire

### ISSUE THREAD

**Issue by Warmanesucks** [Atlantiss/NetherwingBugtracker#7967]
When I put the bag on the ground, it stays placed on the ground but the event doesn't start. I tried to do it again after abandoning after I waited like 10mins, and still, the event doesn't happen.

**Comment by danbopes** [comment]
This is a generic bugtracker. If you're looking for specific support regarding this quest, you should create a GM ticket.

**Comment by Tereneckla** [comment]
It's not scripted #1279
