### ISSUE TITLE
[Orc] [Racial] Blood Fury Not On Global Cooldown

### ISSUE THREAD

**Issue by F4play** [Atlantiss/NetherwingBugtracker#7968]
**Description**: Blood Fury was on the global cooldown prior to WOTLK patch 3.0.3. https://wowwiki-archive.fandom.com/wiki/Patch_3.0.3

**Current behaviour**: Currently doesn't activate a GCD.

**Expected behaviour**: Blood Fury usage should cost a GCD.

**Server Revision**: 3617

**Comment by raethkcj** [comment]
It's odd that that's in the WOTLK patch notes, because users documented it as not triggering GCD in patch 2.0: https://wowpedia.fandom.com/wiki/Blood_Fury?oldid=413713

**Comment by F4play** [comment]
> It's odd that that's in the WOTLK patch notes, because users documented it as not triggering GCD in patch 2.0: https://wowpedia.fandom.com/wiki/Blood_Fury?oldid=413713

I think that information on wowpedia is incorrect. I looked at the world first m'uru kill and it looks like blood fury is on the GCD.

https://youtu.be/0bZi5KWON38?t=69

**Comment by F4play** [comment]
Ehhhh but now I'm watching this speed kill brutallus from SK Gaming and I don't see any GCD for the Blood Fury. https://youtu.be/NqORheQREkI?t=166

Weird stuff, gonna close it.
