### ISSUE TITLE
[Quest][Icecrown] Amped for Revolt!

### ISSUE THREAD

**Issue by Seizzz** [Atlantiss/NetherwingBugtracker#7969]
[//]: # (Enclose links to things related to the bug using http://wowhead.com or any other TBC database.)
[//]: # (You can use screenshot ingame to visual the issue.)
[//]: # (Write your tickets according to the format:)
[//]: # ([Quest][Azuremyst Isle] Red Snapper - Very Tasty!)
[//]: # ([NPC] Magistrix Erona)
[//]: # ([Spell][Mage] Fireball)
[//]: # ([Npc][Drop] Ghostclaw Lynx)
[//]: # ([Web] Armory doesnt work)
[//]: # (To find server revision type `.server info` command in the game chat.)

**Description**: During the bombing, the Gargoyle Ambusher are in Evade! mode 99% of the time, which render the quest alsmot impossible to do

**Current behaviour**:

**Expected behaviour**: Gargoyle Ambusher shouldnt be in Evade! 

**Server Revision**:

**Comment by Tereneckla** [comment]
You've got the wrong bugtracker. This is for a tbc server
