### ISSUE TITLE
Faerie Fire sometimes not preventing stealth

### ISSUE THREAD

**Issue by werwood** [Atlantiss/NetherwingBugtracker#7970]
**Description**: 
Sometimes it is possible to vanish/stealth even with faerie fire up

In general it works as intended, however sometimes the [Faerie Fire](https://tbcdb.com/?spell=26993) function to prevent stealth stops working. I suspect it has something to do with overwriting a rank 1 version with a full rank version. The armor reduction part seems to still work.
evidence of such behavior: https://www.youtube.com/watch?v=jO8rpSYPji8

**Server Revision**: 
3617

**Comment by Wolffenstein** [comment]
Fixed in rev 3622.
