### ISSUE TITLE
Fishing nodes

### ISSUE THREAD

**Issue by Calsifer98** [Atlantiss/NetherwingBugtracker#7972]
[//]: # https://www.wowhead.com/object=182957/highland-mixed-school

**Description**: Highlands Fishing pools don't spawn in the 2 lakes over Allerian Stronghold and Stonebreaker Hold, only 3 spawn in Blackwing Lake

**Current behaviour**: only 4 nodes are available

**Expected behaviour**: should be 9, and at least 1 in stonebreaker

**Server Revision**:

**Comment by Tereneckla** [comment]
Just the possible spawn in Lake Jorune is missing. All those spots are 
1. Not necessarily up all the time
2. Share the spawn with other fishing schools

**Comment by Godmatik** [comment]
Rev 4020 - I know very little about fishing profession, so someone will need to review and confirm. Probably correct though.

**Comment by Godmatik** [comment]
Duplicate #7979
