### ISSUE TITLE
[NPC][Encounter] Kalecgos -- Prior Tank Gets Aggro Immediately After Porting Back From Shadow Realm

### ISSUE THREAD

**Issue by F4play** [Atlantiss/NetherwingBugtracker#7973]
**Description**:  When a previous tank ports back from the shadow realm during the Kalecgos encounter, Kalecgos sometimes switches targets to the tank that just ported back instead of the tank that is maintaining aggro. 

**Current behaviour**:  Kalecgos switches aggro to the tank that was just ported back from the shadow realm. 

**Expected behaviour**: Kalecgos should remain aggro'd onto whoever was the last tank to taunt/maintain threat. 

**Server Revision**: PTR

This didn't happen every time, it really only happened once for us. Basically our 2nd tank came out of the shadow realm and Kalecgos immediately changed target to him and started running over to where he ported in, even though the last tank to taunt Kalecgos was still tanking at the time.

**Comment by F4play** [comment]
Here's a video example: https://youtu.be/oebidVQuN7g?t=642

Events that led up to this:

Tank 1 had aggro on kalecgos, then Died
Tank 2 was in spectral realm
Tank 3 was in live realm with aggro on Kalecgos after tank 1 died

Tank 2 ported out of spectral realm with threat lower than 110% on both Omen and DTM. When tank 2 ported out (Xrp), Kalecgos immediately changed targets to him, forcing tank 3 to taunt back.

**Comment by Godmatik** [comment]
Resolved a few months ago, closing
