### ISSUE TITLE
[NPC][Encounter] Kalecgos - Weird Infernal/Pet AI Issues

### ISSUE THREAD

**Issue by F4play** [Atlantiss/NetherwingBugtracker#7974]
**Description**:  Summoning an infernal on Kalegos can cause some weird issues where the infernal sometimes gets ported into the shadow realm with you, and other times it doesn't. It can get left behind in the shadow realm, or it can get left behind in the normal realm. It's very random, I'm guessing it has something to do with whether you manually clicked the portal or if you were targeted and ported by Kalecgos. 

**Current behaviour**: Summoning an infernal causes weird issues where it sometimes follows you into the shadow realm, then gets left behind, or it just stays in the live realm and doesn't port at all. 

**Expected behaviour**: Pets/Infernals should either follow the player into the shadow realm and out of the shadow realm, or just stay outside in the live realm the entire time. 

**Server Revision**:  PTR

**Comment by F4play** [comment]
After testing more on PTR, it looks like if you have a warlock pet (imp/succy/infernal) and you get chosen by Kalecgos to be ported, your pet won't come down with you. 

If you manually click the portal, still some weird interaction with the pet AI on infernals but mostly okay..

**Comment by Godmatik** [comment]
Still happens
