### ISSUE TITLE
[SPELL][SHAMAN] Stoneclaw Totem

### ISSUE THREAD

**Issue by Nuy** [Atlantiss/NetherwingBugtracker#7975]
[//]: # (Enclose links to things related to the bug using http://wowhead.com or any other TBC database.)
[//]: # (You can use screenshot ingame to visual the issue.)
[//]: # (Write your tickets according to the format:)
[//]: # ([Quest][Azuremyst Isle] Red Snapper - Very Tasty!)
[//]: # ([NPC] Magistrix Erona)
[//]: # ([Spell][Mage] Fireball)
[//]: # ([Npc][Drop] Ghostclaw Lynx)
[//]: # ([Web] Armory doesnt work)
[//]: # (To find server revision type `.server info` command in the game chat.)

**Description**: There were incorrect bug reports of threat generated by this totem like this one - [#3600](https://github.com/Atlantiss/NetherwingBugtracker/issues/3600). This totem's threat generating SHOULD be pretty low and it should only draw aggro if no one is attacking the mob. Basically one auto-attack should be enough for Stoneclaw Totem to lose aggro. Right now this totem's threat is so high that it basically functions as pet-tank for shaman making it the BEST totem for leveling or farming and because of how it works you can solo almost every elite by yourself.

https://wowwiki-archive.fandom.com/wiki/Stoneclaw_Totem - "it pulses a weak aggro threat (weaker than the Warrior's taunting abilities) every 2 seconds. Since the totem lacks any damage output, it is very easy for any player to peel a mob from the totem with only using his/her auto-attack, and it is highly unlikely that the totem will regain aggro on its own. Thus, this totem is ill-suited for any type of aggro management during combat."

**Current behaviour**: Draws way too much threat.

**Expected behaviour**: Should only draw tiny amount of threat. One auto-attack should overaggro this totem.

**Server Revision**: 3625

**Comment by raethkcj** [comment]
From testing on classic using https://wowpedia.fandom.com/wiki/API_UnitDetailedThreatSituation

| Rank | Threat per tick |
|------|-----------------|
| 1    | 22              |
| 2    | 37              |
| 3    | 60              |
| 4    | 75              |
| 5    | 115             |
| 6    | 150             |

In Classic the totem ticks immediately on placement, and every two seconds after that, for a total of 8 ticks.

I don't have beta yet, but if we plot the threat vs hp values of each rank and extrapolate to rank 7, it would be approximately 400 threat per tick: https://www.desmos.com/calculator/bxwg7ooqtu

**Comment by Tereneckla** [comment]
Ranks 1-6 are doing the threat raethkcj listed.
Rank 7 does 170 threat so if anything it could be too low.

**Comment by Nuy** [comment]
> Ranks 1-6 are doing the threat raethkcj listed.
> Rank 7 does 170 threat so if anything it could be too low.

It seems the way it works now is that it actually taunts targets around it every 2 seconds putting it on top of threat table every 2 seconds so no matter how hard you hit the mob you will never overaggro this totem and that's incorrect. I know there's "taunts" in spell description but that's not how this totem should work blizzlike way and it's a fail on Blizzard's part that the spell description doesn't fit how it actually works.

**Comment by Tereneckla** [comment]
Yes, shouldnt be a taunt effect

**Comment by Wolffenstein** [comment]
It's only a taunt effect for non-passive player pets. Works correctly.
