### ISSUE TITLE
Targrom <Food & Drink>NPC stuck under textures

### ISSUE THREAD

**Issue by therealCrysis** [Atlantiss/NetherwingBugtracker#7976]
https://www.wowhead.com/npc=19348/targrom

This NPC is a Food and Drink vendor who should be placed in Shadowmoon Village in cords: [28.2, 27.0]

Right now he is spawned in Netherstorm, under textures.
https://i.imgur.com/BXy5GeF.png

He should be despawned from this Netherstorm location and spawned in correct position in Shadowmoon Village.

**Comment by Wolffenstein** [comment]
Fixed in rev 3680.
