### ISSUE TITLE
Missing Honor Points

### ISSUE THREAD

**Issue by Swordsister** [Atlantiss/NetherwingBugtracker#7977]
Grinding battlegrounds and winning but not getting any honor points.   Have 7000+ points yesterday and says I only have 5000+ total...haven't bought or used the points on anything!   

[Doc1.docx](https://github.com/Atlantiss/NetherwingBugtracker/files/6328365/Doc1.docx)

**Comment by tsu-1** [comment]
File in a ticket ingame.
