### ISSUE TITLE
karazhan opera bug

### ISSUE THREAD

**Issue by bootystab** [Atlantiss/NetherwingBugtracker#7984]
**Description**: 
in the past 3-4 months ive been doing karazhan every week and i have only seen big bad wolf in opera
**Current behaviour**:
i have only seen big bad wolf while playing on this server. maybe my seeding is bugged in some way (i have been raid lead for 90% of those kara's )
**Expected behaviour**: 
seeing other bosses there, should be 33.3% chance for each boss, i want my romeo trinket
**Server Revision**:

**Comment by Godmatik** [comment]
RNG is RNG
Not a bug

**Comment by Wolffenstein** [comment]
It's just random, I promise it's working correctly.
