### ISSUE TITLE
[Rogue] poison scalling, needs research

### ISSUE THREAD

**Issue by bootystab** [Atlantiss/NetherwingBugtracker#7985]
**Description**: 
in vanilla and tbc poisons used to scale with spellpower/nature dmg gear
**Current behaviour**:
instant poison has 0% sp coefficient, deadly has 50%, didnt test wound/anesthetic scalling
**Expected behaviour**: 
no data on the exact coefficients exist that i can find, but it should be 100% potentially, was changed in wotlk prepatch to scale with ap instead, i used to sell flasks of supreme power to my guildie rogues back in vanilla naxx times for some extra poison dps, people wouldnt buy it every week if it didnt work
it also does not work in wow classic/tbc classic, but that is one of the bugs added by using a legion client
Patch 3.0.2 (2008-10-14): Damaging poisons now scale with attack power.
**Server Revision**:

**Comment by Godmatik** [comment]
Was fixed, closing
