### ISSUE TITLE
Cast Bar is acting strangely.

### ISSUE THREAD

**Issue by simeondp** [Atlantiss/NetherwingBugtracker#7986]
Castbar is acting strangely. I can cast through obstacles most of the time. Monsters attack me while they are not in range and while moving. I cast polymorph on a mob run a way 1 km and I dont get out of combat, then the mob gets out of poly and follows me without retreating. Monsters reset cooldown is wrong.

**Comment by Tereneckla** [comment]
> Castbar is acting strangely. 

Be more precise and make a seperate issue. Make sure it's not a client or addon issue.
> I can cast through obstacles most of the time.

Yes, that is normal. Most objects just blocked line of sight with wotlk
> Monsters attack me while they are not in range and while moving.

Be more precise and make a seperate issue
> I cast polymorph on a mob run a way 1 km and I dont get out of combat, then the mob gets out of poly and follows me without retreating.

Mobs obviously can't go out of leash range when polymorphed. After the polymorph ran out they reset as normal.
> Monsters reset cooldown is wrong.

Be more precise and make a seperate issue
