### ISSUE TITLE
[NPC][Tiny Voodoo Mask] Hex Lord Malacrass - Tiny Voodoo Mask affecting loot table incorrectly

### ISSUE THREAD

**Issue by cillo1** [Atlantiss/NetherwingBugtracker#7988]
**Description**: 
Hex Lord Malacrass should drop 2 items, and also a 3rd item being the Tiny Voodoo Mask - which is on it's own separate loot table/drop chance and not the 2 guaranteed item drops for a kill.

**Current behaviour**: 
Tiny Voodoo Mask shares loot table with all current possible drops, and will always award 2 items, sometimes one of those being the mask.

**Expected behaviour**: 
Hex Lord Malacrass should drop 2 items, and sometimes a 3rd. The 3rd item is always the Tiny Voodoo Mask on it's own seperate loot table. 

**Server Revision**: 3630

**Sources**
https://youtu.be/vasI6dmibBI?t=355
https://youtu.be/OJnSKZWrc3k?t=155 
https://www.youtube.com/watch?v=-reMBCUQLG4&t=380s
https://www.wowhead.com/item=34029/tiny-voodoo-mask#comments 

Each of the 3 videos from 12-13 years ago show 3 items being dropped, all having 1 Tiny Voodoo Mask + 2 drops from default loot table. Wowhead comments show many old comments referring to this behavior of the Tiny Voodoo Mask drop.

**Comment by Godmatik** [comment]
Bump, please fix

**Comment by Wolffenstein** [comment]
Fixed in rev 3631.
