### ISSUE TITLE
(Paladin) Tome of Divinity

### ISSUE THREAD

**Issue by Helvorn** [Atlantiss/NetherwingBugtracker#7989]
[//]: # (Enclose links to things related to the bug using http://wowhead.com or any other TBC database.)

https://classic.wowhead.com/quest=1644/the-tome-of-divinity#see-also 

[//]: # (You can use screenshot ingame to visual the issue.)
[//]: # (Write your tickets according to the format:)
[//]: # ([Quest][Tome of Divinity])
[//]: # ([NPC] Stephanie Turner)

**Description**: 
I have the 10 linen cloth on my inventory but cannot turn in the quest Tome of divinity to Stephanie Turner in Stormwind - Trade District. 
**Current behaviour**:
Can't finish the quest. She seems to not recognize the linen cloth on my backpack.

**Expected behaviour**: 
She should get the linen and complete my quest.
**Server Revision**:

**Comment by aplouding** [comment]
It works now on server revision 3701. 

Please close @Wolffenstein
