### ISSUE TITLE
When dying on UC elevator you respawn rather than becoming a ghost

### ISSUE THREAD

**Issue by Ceago** [Atlantiss/NetherwingBugtracker#799]
**Description**:  When you die on the Undercity elevator you respawn at the graveyard rather than becoming a ghost.  https://streamable.com/wdv8z

**Current behaviour**:  You become alive again.

**Expected behaviour**: Should be a ghost and have to wait for the elevator.

**Server Revision**: 203

**Comment by The14me** [comment]
rev 3441 the issue is still active.

**Comment by Wolffenstein** [comment]
It's done on purpose to avoid having issues with reclaiming the body.
