### ISSUE TITLE
Curator and Prince drops 

### ISSUE THREAD

**Issue by Vettall** [Atlantiss/NetherwingBugtracker#7990]
[//]: # (Enclose links to things related to the bug using http://wowhead.com or any other TBC database.)
[//]: # (You can use screenshot ingame to visual the issue.)
[//]: # (Write your tickets according to the format:) t4 drops are not working properly they should drop 3x token for each class 
[//]: # ([Quest][Azuremyst Isle] Red Snapper - Very Tasty!)
[//]: # ([NPC] Magistrix Erona)
[//]: # ([Spell][Mage] Fireball)
[//]: # ([Npc][Drop] Ghostclaw Lynx)
[//]: # ([Web] Armory doesnt work)
[//]: # (To find server revision type `.server info` command in the game chat.)

**Description**:  the bosses loot are not correctly scripted , they don't drop 3x token as it should do 

**Current behaviour**: just 1x drop from the Prince and 2x from Curator 

**Expected behaviour**: 3x token drop for all bosses 

**Server Revision**:

**Comment by Godmatik** [comment]
Karazhan is only 2x token drops that is intended, it was never increased to 3x
