### ISSUE TITLE
Windowed mode bugged

### ISSUE THREAD

**Issue by SweetChaoss** [Atlantiss/NetherwingBugtracker#7992]
Hello! 

Seems like when I am changing to windowed mode it's just a black screen and without hitting "esc" you can't do anything. I hate to use full screens and a hand to solve this issue will be much appreciated.

Thanks, 

[//]: # (Enclose links to things related to the bug using http://wowhead.com or any other TBC database.)
[//]: # (You can use screenshot ingame to visual the issue.)
[//]: # (Write your tickets according to the format:)
[//]: # ([Quest][Azuremyst Isle] Red Snapper - Very Tasty!)
[//]: # ([NPC] Magistrix Erona)
[//]: # ([Spell][Mage] Fireball)
[//]: # ([Npc][Drop] Ghostclaw Lynx)
[//]: # ([Web] Armory doesnt work)
[//]: # (To find server revision type `.server info` command in the game chat.)

**Description**: 

**Current behaviour**:

**Expected behaviour**: 

**Server Revision**:

**Comment by Godmatik** [comment]
copy/paste from pinned message in their discord:

If you're getting a black screen when swapping to windowed mode - it's a GAMMA issue. Open up config.wtf inside of your WTF folder and add these 2 lines:
SET gxWindow "1"
SET gxMaximize "1"
