### ISSUE TITLE
[QUEST][NPC] Escape from Skettis

### ISSUE THREAD

**Issue by Nuy** [Atlantiss/NetherwingBugtracker#7993]
[//]: # (Enclose links to things related to the bug using http://wowhead.com or any other TBC database.)
[//]: # (You can use screenshot ingame to visual the issue.)
[//]: # (Write your tickets according to the format:)
[//]: # ([Quest][Azuremyst Isle] Red Snapper - Very Tasty!)
[//]: # ([NPC] Magistrix Erona)
[//]: # ([Spell][Mage] Fireball)
[//]: # ([Npc][Drop] Ghostclaw Lynx)
[//]: # ([Web] Armory doesnt work)
[//]: # (To find server revision type `.server info` command in the game chat.)

**Description**: Impossible to do this daily quest right now because Skyguard Prisoner that is supposed to be locked in the cage isn't respawning.

**Current behaviour**: Skyguard Prisoner that is supposed to be locked in the cage isn't respawning.

**Expected behaviour**: He should respawn after someone has done a quest and the cage should close.

**Server Revision**: 3630

**Comment by raethkcj** [comment]
He can spawn in at least 3 different cages, did you check all of Skettis or just wait at the same cage?

I just did the quest myself, and he immediately respawned in one of the other cages.
