### ISSUE TITLE
[Item] Solarian's sapphire doesn't scale properly

### ISSUE THREAD

**Issue by ghost** [Atlantiss/NetherwingBugtracker#7994]
**Description**: [Item] Solarian's Sapphire trinket bonus ap doesnt benefit from Commanding Presence

**Current behaviour**: increases ap by 452 with solarian's sapphire

**Expected behaviour**: Should give 470 (according to tooltip) attack power with Commanding Presence 5/5

**Server Revision**: 3630

**Comment by Deyanis1337** [comment]
![s2](https://user-images.githubusercontent.com/84371650/118604304-97615980-b7e7-11eb-911a-3c6dfbc6c2e5.png)
![s1](https://user-images.githubusercontent.com/84371650/118604309-992b1d00-b7e7-11eb-90c5-6484e36c3f2e.png)

**Comment by ghost** [comment]
https://tbc.wowhead.com/item=30446/solarians-sapphire#comments
According to comments it worked that way in retail tbc

**Comment by ghost** [comment]
elitist jerks also confirms it works that way
https://web.archive.org/web/20130810120034/http://elitistjerks.com/f81/t22705-dps_compendium//
![s3](https://user-images.githubusercontent.com/84371650/118653815-7d8d3a00-b81a-11eb-8421-9e1b3535b67e.PNG)

**Comment by Wolffenstein** [comment]
Fixed in rev 3653.
