### ISSUE TITLE
[Hunter] [Pet] Special attacks block auto attacks.

### ISSUE THREAD

**Issue by dexiefy** [Atlantiss/NetherwingBugtracker#7997]
**Current behaviour**:
Pet auto attack gets blocked by his special attacks.

**Description**: 

When pet reaches the target it auto attacks it once and starts spamming his focus dump ability until he is out of focus after which he starts autoattacking again. 

This is the result in recount.
![This is the result in recount](https://user-images.githubusercontent.com/3316071/119964425-7e0b9a80-bfa9-11eb-93aa-25fdeb8bce47.png)

4 claws(25 focus each) take 6 seconds to execute (4.5 if we ignore the last gcd happening). That was done with pet(Cat) with cobra reflexes (which puts him at 1.54 attack speed) but it happens the same way without cobra reflexes (2.0 attack speed). Needless to say there should be few more auto attacks done on the target.

Here are some examples from last NFA raid where i played survival with screech pet and noticed something is off.  Pet used was Carrion Bird.

*Mother Shahraz.*
![Mother Shahraz](https://user-images.githubusercontent.com/3316071/119965590-b8296c00-bfaa-11eb-999e-fa78e15de11d.png)
269 screeches but only 19 autoattacks in that time.

*Naj'entus.*
![Naj'entus](https://user-images.githubusercontent.com/3316071/119965737-e313c000-bfaa-11eb-9da2-fd38021482bb.png)
This is my favourite, pet managed to get 4 autoattacks in entire fight and i managed to do more dmg with single Demonic Rune than my pet with his autoattacks.

Pet stayed alive entire fight in both cases, yet only managed a handful of autoattacks. Initially thought it was some 'not in range' issue we used to have but it also happens in the wild as described above and only autoattack that idd does happen is the one when pet reaches its target. 

Some more examples from MH.

*Rage Winterchill.*
![Rage Winterchill](https://user-images.githubusercontent.com/3316071/119966735-e6f41200-bfab-11eb-99c6-c3b09da86ea7.png)

*Anatheron.*
![Anatheron](https://user-images.githubusercontent.com/3316071/119966881-0d19b200-bfac-11eb-9856-1c45fa1b7002.png)
Ammount of misses seem weird here, but its possible pet was not decursed on time, though screeches should also miss more in such case, so dunno what is wrong in this case.

As you can see(especially from najentus fight) its entirely possible to completly stop your pet from autoattacking if you manage to supply the pet with endless focus(ie naj'entus where pet managed 4 attacks).
I tested it with Owl, Carrion Bird, Bat, Cat, Wind Serpent.
With wind serpent its much harder to notice and document but the issue is there aswell. So i belive its quite possible it affects all pets. Possibly issue lies with animation?  Would explain why wind serpent doesnt seem as affected by it than the pets who use their 'entire body animation' to execute those special attacks.
I also do not recall this happening early on in servers life while i played with cat.

Edit: Forgot to mention that i noticed im getting no pet attacks in on mother and disabled screech for a moment, pet started autoattacking without problem, so it couldnt be issue of him being out of range.

**Expected behaviour**: 
Pet should autoattack regardless of instant attacks being used just like it is the case with players.

**Reproduction:**
Attack a mob (to force recount to show current fight dmg), wait for mob to reach you. Send pet to attack, observe how after first auto attack there is no orange dmg number or combat log entry until pet runs out of focus.

**Server Revision**:  
3638

**Comment by Wolffenstein** [comment]
Fixed in rev 3692.

**Comment by Howizter** [comment]
Current behaviour:
Both pets had same group, both were alive whole fight as their owners so expected number of autoattacks should be similar.

https://i.imgur.com/Cfa2WKd.png

https://i.imgur.com/vjbJ2B9.png
Expected behaviour:
 Wind serpent should have similar number of autoattack  as ravager.
Server Revision:
3819
