### ISSUE TITLE
[Item] Madness of the Betrayer

### ISSUE THREAD

**Issue by zhorzhyordanov** [Atlantiss/NetherwingBugtracker#7998]
**Description**:  The trinket has extremely low PPM (proc per minute) for a feral druid, although feral druids attack with the lowest possible speed in game.

**Current behaviour**: I ran five tests and each one continued for 12 minutes. The trinket procced 4,3,3,2,3 times 
or a total of 15 procs for 60 minutes. This is simply impossible to be a bad RNG. I know that for hunters it procs a lot more often. Sometimes it procs 2-3 times in a row.

**Expected behaviour**:  According to other testers the real PPM should be around 2 PPM. https://www.wowhead.com/item=32505/madness-of-the-betrayer#comments

**Server Revision**: 3638

**Comment by ImCasual** [comment]
U really dont need worry about it, if are u using it as feral, there is something very wrong on your guild.

**Comment by Godmatik** [comment]
Some sources says 2ppm, some say 1.5, some say 1
Currently it is set at 1ppm
Need to check warcraftlogs and verify

**Comment by EtheriousNW** [comment]
Most things seem to point to 1.5 rather than 2. Set to 1.5 for now. Need more definitive proof to set it higher.
