### ISSUE TITLE
[NPC] Shambling Horror Evade bug

### ISSUE THREAD

**Issue by Ceago** [Atlantiss/NetherwingBugtracker#800]
[NPC] Shambling Horror at Brightwater Lake

**Description**:   First Evading: https://streamable.com/geq05 , Following: https://streamable.com/hnku1
The Shambling Horrors at brightwater lake evade if a spell is cast on them at range but if you walk up to them they will chase you into the water.

**Current behaviour**:  Evade when a spell is cast but run into the water if range aggro

**Expected behaviour**: Should either run into the water after you cast a spell or they should reset after you go into the water.

**Server Revision**: 203

**Comment by Tereneckla** [comment]
Fixed
