### ISSUE TITLE
Mob respawn issue, Shadowmoon Valley

### ISSUE THREAD

**Issue by Ptidej** [Atlantiss/NetherwingBugtracker#8000]
[//]: # (Enclose links to things related to the bug using http://wowhead.com or any other TBC database.)
[//]: # (You can use screenshot ingame to visual the issue.)
[//]: # (Write your tickets according to the format:)
[//]: # ([Quest][Azuremyst Isle] Red Snapper - Very Tasty!)
[//]: # ([NPC] Magistrix Erona)
[//]: # ([Spell][Mage] Fireball)
[//]: # ([Npc][Drop] Ghostclaw Lynx)
[//]: # ([Web] Armory doesnt work)
[//]: # (To find server revision type `.server info` command in the game chat.)

**Description**: 
Since last reboot over 23 mobs did not spawn in at The Path of Conquest in Shadowmoon Valley.
NPC names: 
Eclipsion Soldier (x16)
Eclipsion Spellbinder (x7)
**Current behaviour**:
![image](https://user-images.githubusercontent.com/85415610/120904853-bfa5e080-c64e-11eb-9b84-0c7571421b7d.png)
![image](https://user-images.githubusercontent.com/85415610/120904874-e19f6300-c64e-11eb-9f54-9a14977d42c5.png)
![image](https://user-images.githubusercontent.com/85415610/120904897-f0861580-c64e-11eb-892f-df34bb20470c.png)
Screenshots from LIVE server
**Expected behaviour**: 
![image](https://user-images.githubusercontent.com/85415610/120904967-638f8c00-c64f-11eb-88c3-c834fe08a477.png)
![image](https://user-images.githubusercontent.com/85415610/120904982-71dda800-c64f-11eb-8591-3cd68eca61ca.png)
![image](https://user-images.githubusercontent.com/85415610/120904995-83bf4b00-c64f-11eb-9cff-ab2c89a2d086.png)
Screenshots from PTR server
**Server Revision**: 
3642

**Comment by Ptidej** [comment]
First time I report a bug so I hope I have brought enough information

**Comment by Godmatik** [comment]
Not a bug, this is the normal spawns
