### ISSUE TITLE
[Quest][Felwood] Corrupted Whipper Root 

### ISSUE THREAD

**Issue by Figar00** [Atlantiss/NetherwingBugtracker#8001]
[//]: # (Enclose links to things related to the bug using http://wowhead.com or any other TBC database.)
[//]: # (You can use screenshot ingame to visual the issue.)
[//]: # (Write your tickets according to the format:)
[//]: # ([Quest][Azuremyst Isle] Red Snapper - Very Tasty!)
[//]: # ([NPC] Magistrix Erona)
[//]: # ([Spell][Mage] Fireball)
[//]: # ([Npc][Drop] Ghostclaw Lynx)
[//]: # ([Web] Armory doesnt work)
[//]: # (To find server revision type `.server info` command in the game chat.)

**Description**: 
[Quest][Felwood] Corrupted Whipper Root 
[https://www.wowhead.com/quest=4443/corrupted-whipper-root]

[Game object][Felwood] Corrupted Whipper Root 
[https://www.wowhead.com/object=164888/corrupted-whipper-root](url)
**Current behaviour**:
After cleansing this corrupted flower, the Cleansed Whipper Root isnt spawning. All the corrupted whipper nodes in Felwood does not work.
**Expected behaviour**: 
When Corrupted Whipper Root is cleansed by finishing the quest it offers, the Cleansed Whipper Root should spawn, where you can loot Whipper Root Tubbers from it in random amount of 3-10 pieces. detailed info : `https://www.wowhead.com/item=11951/whipper-root-tuber#comments`
**Server Revision**:

**Comment by Godmatik** [comment]
Duplicate
