### ISSUE TITLE
[Felmyst] Encapsulate damage causes spell pushback

### ISSUE THREAD

**Issue by Godmatik** [Atlantiss/NetherwingBugtracker#8002]
Damage taken by Encapsulate during the Felmyst encounter is causing spell pushback, but it should not.

A few guides back during TBC retail reference this special caveat about the ability.

https://www.mmo-champion.com/content/314

>  Note that encapsulate does not cause spell push back, so even if it lands on the main healer group, they have no excuses for not putting out massive loads of healing during it's duration. Furthermore, the raid can DPS while encap is going out, even if it is on their group.

Here's a video showing it as well (at 0:40)
https://www.youtube.com/watch?v=bxpbz5sQyuA

**Comment by EtheriousNW** [comment]
Working as intended https://youtu.be/pcv5LlawB1A?t=851
