### ISSUE TITLE
[Spell] Petrification

### ISSUE THREAD

**Issue by Ptidej** [Atlantiss/NetherwingBugtracker#8005]
**Description**: 
The debuff "Petrification" from using "Flask of Petrification" does not work properly.

**Current behaviour**:
When using "Flask of Petrification" you get affected by a debuff named "Petrification": when affected by this debuff you cannot attack, move or use spells for 1min. 
Currently: you can remove this debuff whenever you want just by right-clicking any enemy target.

**Expected behaviour**: 
You should not be able to remove this debuff as it is a typeless debuff (red border) instead you should be frozen for the entire 60s duration.

Flask of Petrification item:
https://tbc.wowhead.com/item=13506/flask-of-petrification#created-by-spell
Petrification debuff:
https://tbc.wowhead.com/spell=17624/petrification#used-by-item

**Server Revision**: 
3642

**Comment by Wolffenstein** [comment]
Works correctly
