### ISSUE TITLE
[Dungeon] Shattered Halls hc

### ISSUE THREAD

**Issue by random2214** [Atlantiss/NetherwingBugtracker#8006]
**Description**:  I am a tank paladin with 12k health, invited ret paladin, mage, wlock and priest and we cc'd the hell out of dungeon's npcs. We were always fighting one or two at a time (and im above def cap) yet they legit were one shotting us. Can you tune it down cuz its impossible to do this dungeon even with the most stupidly op dungeon group.

**Current behaviour**: You need at least t4 or t5 group in order to get through this dungeon.

**Expected behaviour**: Dungeons are made to be cleared before raids.

**Server Revision**: 3645

**Comment by Godmatik** [comment]
Not a bug, have run the dungeon multiple times with no issues.
