### ISSUE TITLE
Permanent slow after being mind controlled 

### ISSUE THREAD

**Issue by Jkhuri** [Atlantiss/NetherwingBugtracker#8007]
[//]: # (Enclose links to things related to the bug using http://wowhead.com or any other TBC database.)
[//]: # (You can use screenshot ingame to visual the issue.)
[//]: # (Write your tickets according to the format:)
[//]: # ([Quest][Azuremyst Isle] Red Snapper - Very Tasty!)
[//]: # ([NPC] Magistrix Erona)
[//]: # ([Spell][Mage] Fireball)
[//]: # ([Npc][Drop] Ghostclaw Lynx)
[//]: # ([Web] Armory doesnt work)
[//]: # (To find server revision type `.server info` command in the game chat.)

**Description**: 
Permanent slow after mind controlled if slowed before the mind control is cast. The slow lasts until you mount or changes move speed by potion etc. 
**Current behaviour**:
If you are slowed and then you get mind controlled and if the slow duration ends before the mind control duration ends then you get slowed permanently until you mount or drink a move pot. Blessing of freedom does not remove the slow. Priest abusing this in the arena.
**Expected behaviour**: 
If you are slow then you get mind controlled and the slow ends when the slow duration 
**Server Revision**:

**Comment by Wolffenstein** [comment]
Fixed in rev 3813.
