### ISSUE TITLE
([NPC] Eldinarcus Rare Spawn - no rare spawn loot

### ISSUE THREAD

**Issue by Rebelyna** [Atlantiss/NetherwingBugtracker#801]
**Description**: 
Rare Spawn loot

**Current behaviour**:
Rare Spawn Eldinarcus in [Eversong Woods] did only drop grey junk

**Expected behaviour**: 
Rare Spawns are expected to drop at least 1 item of value, armor or a weapon

**Server Revision**: 
2077

**Comment by tcberk12** [comment]
#536 and #578 

duplicate isssue.

**Comment by wtRCH** [comment]
Closed due to @tcberk12 comment.
