### ISSUE TITLE
[Priest] Focused Power, Discipline Talent, not applying it's hit chance to Smite

### ISSUE THREAD

**Issue by Altruismos** [Atlantiss/NetherwingBugtracker#8010]
[//]: # (Enclose links to things related to the bug using http://wowhead.com or any other TBC database.)
[//]: # (You can use screenshot ingame to visual the issue.)
[//]: # (Write your tickets according to the format:)
[//]: # ([Quest][Azuremyst Isle] Red Snapper - Very Tasty!)
[//]: # ([NPC] Magistrix Erona)
[//]: # ([Spell][Mage] Fireball)
[//]: # ([Npc][Drop] Ghostclaw Lynx)
[//]: # ([Web] Armory doesnt work)
[//]: # (To find server revision type `.server info` command in the game chat.)

**Description**: 

Priest Talent "Focused Power"  https://tbc.wowhead.com/spell=33186/focused-power

**Current behavior**:

Had a suspicion after a few raids that the above talent was not applying to my smite spells, so I recreated it in a tested environment on the PTR

![image](https://user-images.githubusercontent.com/86939885/124416693-c50d4e00-dd14-11eb-81c1-1d2afa01ca3e.png)

The above screenshot shows 500 smite casts at a level 73 target dummy with 153 spell hit rating (12.13% spell chance to hit) with the above talent allocated, we should expect much closer to 1% resist chance, instead we are at about 6%, which is far and above 1% and is statistically almost impossible.

**Expected behavior**: 

Should experience between 0-2% chance to resist, allowing variance.

**Server Revision**: 

3645

**Comment by Wolffenstein** [comment]
Works correctly
