### ISSUE TITLE
[Spell] [Paladin] Judgement of Wisdom , proc problem

### ISSUE THREAD

**Issue by guarjamer** [Atlantiss/NetherwingBugtracker#8011]
https://tbc.wowhead.com/spell=20186/judgement-of-wisdom

**Description**:  "Attacks and spells used against you have a chance of restoring 33 of the attacker's mana."

**Current behaviour**: just melee attacks are activating this   ability, tested this with ranks 1 ,2 ,3 and 4.

**Expected behaviour**: like the tooltip stated , all attacks and spells should work, in the case of the paladin , autoattacks, crusder strike, seals melee hits ( righteouesness, blood , command , vengeance )  damaging judgements,  hammer of wrath , exorcism, etc... all with 50% chance proc.

**Server Revision**: 3646

**Comment by aplouding** [comment]
Tested on revision 3701, paladin procs correctly on all attacks and spells

**Comment by Godmatik** [comment]
Works fine for me as well
