### ISSUE TITLE
Instant Shadowbolt can be casted through Nagrand's Arena pillar

### ISSUE THREAD

**Issue by kemotix** [Atlantiss/NetherwingBugtracker#8012]
I'm nowhere near lock's line of sight yet he blasts my face with instant Shadowbolt.

https://user-images.githubusercontent.com/4163921/125850002-eb99ab11-973a-4258-a947-655f97ba5039.mp4
![screen](https://user-images.githubusercontent.com/4163921/125849496-dd8f3daf-5a9e-4d45-ac73-b13cd352522e.jpg)

**Comment by VorpalSoul** [comment]
Its proc from trinket from mgt hc: TImbal's Focusing Crystal: https://tbc.wowhead.com/item=34470/timbals-focusing-crystal. It has same animation as shadowbolt, but don't require line of sight.

**Comment by tsu-1** [comment]
Not a bug. 

> Its proc from trinket from mgt hc: TImbal's Focusing Crystal: https://tbc.wowhead.com/item=34470/timbals-focusing-crystal. It has same animation as shadowbolt, but don't require line of sight.
