### ISSUE TITLE
Vanish effect makes rogue immune to Faerie Fire

### ISSUE THREAD

**Issue by kemotix** [Atlantiss/NetherwingBugtracker#8013]
https://www.youtube.com/watch?v=jWgwLhQhf98

At the end of my clip. Cloak fades and Rogue is immune to my Faerie Fire.

**Comment by tsu-1** [comment]
https://github.com/Atlantiss/NetherwingBugtracker/issues/7796

Prio.

Worth checking if Demo/Piercing Shout properly removes stealthed targets too (including druids)

**Comment by dedestus** [comment]
still bugged

**Comment by Godmatik** [comment]
Vanish right now has a ~1 second immunity buff when using it.

Unsure if blizzlike/intended

**Comment by Godmatik** [comment]
All of the sources I check confirm that vanish gives you a small less than a second immunity when used and that this was how it was back in retail TBC also. I am hearing people say similar on classic TBC.

Would need some specific source to prove otherwise

Closing
