### ISSUE TITLE
[Spell][Paladin] Rigtheous Defense

### ISSUE THREAD

**Issue by wtRCH** [Atlantiss/NetherwingBugtracker#802]
[//]: # (Enclose links to things related to the bug using http://wowhead.com or any other TBC database.)
[//]: # (You can use screenshot ingame to visual the issue.)
[//]: # (Write your tickets according to the format:)
[//]: # ([Quest][Azuremyst Isle] Red Snapper - Very Tasty!)
[//]: # ([NPC] Magistrix Erona)
[//]: # ([Spell][Mage] Fireball)
[//]: # ([Npc][Drop] Ghostclaw Lynx)
[//]: # ([Web] Armory doesnt work)

**Description**: Still happening after revision 2073 and on 2077. Doesn't matter if you cast it on the player or NPC.

**Comment by wtRCH** [comment]
@toto6

**Comment by Wolffenstein** [comment]
fixed
