### ISSUE TITLE
API Server Error - character Merge

### ISSUE THREAD

**Issue by MisaHack** [Atlantiss/NetherwingBugtracker#8023]
[//]: # (Enclose links to things related to the bug using http://wowhead.com or any other TBC database.)
[//]: # (You can use screenshot ingame to visual the issue.)
[//]: # (Write your tickets according to the format:)
[//]: # ([Quest][Azuremyst Isle] Red Snapper - Very Tasty!)
[//]: # ([NPC] Magistrix Erona)
[//]: # ([Spell][Mage] Fireball)
[//]: # ([Npc][Drop] Ghostclaw Lynx)
[//]: # ([Web] Armory doesnt work)
[//]: # (To find server revision type `.server info` command in the game chat.)

**Description**: 
"API Server Error, try again or email us at support@atlantiss.eu if you continue to have issues.""
I get this message when I try to press "Merge" button for character-merge on Atlantiss web-site
Maybe problem is that on Karazhan realm I have horde character and on Netherwing realm I have 2 Alliance characters.
Is there any way to convert Factions from Netherwing to Karazhan realm, so those Alliance become Horde?

**Current behaviour**:

**Expected behaviour**: 

**Server Revision**:

**Comment by VorpalSoul** [comment]
I do get same message when I try to put new name for character that already exists on Karazhan. Any new name is rejected with Api Server Error.
