### ISSUE TITLE
 [Quest][Netherstorm] Fel Reavers, No Thanks! 

### ISSUE THREAD

**Issue by Varnae** [Atlantiss/NetherwingBugtracker#8024]
[//]: # (Enclose links to things related to the bug using http://wowhead.com or any other TBC database.)
[//]: # (You can use screenshot ingame to visual the issue.)
[//]: # (Write your tickets according to the format:)
[//]: # ([Quest][Azuremyst Isle] Red Snapper - Very Tasty!)
[//]: # ([NPC] Magistrix Erona)
[//]: # ([Spell][Mage] Fireball)
[//]: # ([Npc][Drop] Ghostclaw Lynx)
[//]: # ([Web] Armory doesnt work)
[//]: # (To find server revision type `.server info` command in the game chat.)

**Description**: Obtain 5 Condensed Nether Gas from Gan'arg Mekgineers at Forge Base: Oblivion, northwest of the Stormspire, and load them into a nearby Inactive Fel Reaver. Return to Nether-Stalker Nauthis after you've completed this task.
https://tbc.wowhead.com/quest=10855/fel-reavers-no-thanks

**Quest ID**: #10855

**Current behaviour**: Quest doesn't get completed after destroying the Inactive Fel Reaver, "Completed" message is printed on the players screen once they destroy the Inactive Fel Reaver,but in the quest log it's status stays "active" instead of "completed".

**Expected behaviour**: https://www.youtube.com/watch?v=0DekRBZn3CY

**Server Revision**: 3650

**Comment by Wolffenstein** [comment]
works fine
