### ISSUE TITLE
[Quest] [NPC] Headless Horseman.  The loot & the loot roll windows did not appear for me. 

### ISSUE THREAD

**Issue by SwimzwithSharkz** [Atlantiss/NetherwingBugtracker#8027]
**Description**: 
     In Scartet Monestary, Graveyard dungeon, on our group's fourth ganking of the Headless Horseman, 
the loot and the loot roll windows Did Not Appear for me. Nope. 
Everyone else saw them tho, but I did not.
https://tbc.wowhead.com/quest=11405/call-the-headless-horseman

**Current behaviour**: The other loot windows after HH died were fine.

**Expected behaviour**: the loot and loot roll windows should appear.

**Server Revision**: 3651

**Comment by Godmatik** [comment]
Disable your lazypig or other addon

**Comment by SwimzwithSharkz** [comment]
> 
> 
> Disable your lazypig or other addon

nope, don't have that addon  nor any other active that would prolly interfere w/ a loot roll. like dbm. 
Don't think that was it but was weird to not get the loot windows, on two items.
