### ISSUE TITLE
Investigating The Blue Recluse Quest bugged

### ISSUE THREAD

**Issue by q7w7e7r** [Atlantiss/NetherwingBugtracker#8028]
Description:
There is class quest for mages in Ally side https://classicdb.ch/?quest=1920 It's bugged atm

Current behaviour:
Mage cannot get stun debuff on mob when quest item could be used, mage cannot kill the mob to try to use quest item on mob's remains. https://cdn.discordapp.com/attachments/297494762834100225/496633336303714314/WoWScrnShot_100218_131656.jpg

Expected behaviour:
Successful using of the quest item on the mob with debuff you can see on this video (start viewing from 135s)
https://youtu.be/t0jFkP1k2ag?t=135
Server Revision:
8606

**Comment by Godmatik** [comment]
#5508
