### ISSUE TITLE
Beren's Peril missing Ravenclaw Guardian#1973 patrol

### ISSUE THREAD

**Issue by Tenoutoften** [Atlantiss/NetherwingBugtracker#803]
**Description**: 
Ravenclaw Guardian#1973(https://db.excalibur.ws/?npc=1973) should most likely patrol the cave
On Netherwing there is three of them at the same spot: https://i.gyazo.com/5c88f1ef8242a5ff69c2bc228596af92.png

Patrol also indicated by wowhead comment from TBC:
https://www.wowhead.com/quest=516/berens-peril#comments:id=186008:reply=336383

> I am a lvl 19 rogue and am managing to pull them one at a time. Wait till the ones who patroil move away and throw an axe at the others, dont stealth upon them, just gouge and backstab if u want, but AFTER u pull the mob away.

**Expected behaviour**: 
Expect one patrol in this cave

**Server Revision**: 
2077

**Comment by aresbrutus** [comment]
Fixed in one of the upcoming updates.
