### ISSUE TITLE
 Bloody riper is not elite.

### ISSUE THREAD

**Issue by Metalica** [Atlantiss/NetherwingBugtracker#8030]
https://classic.wowhead.com/npc=12579/bloodfury-ripper

 Bloody riper is not elite.

**Comment by Metalica** [comment]
Fix hp and elite status: UPDATE `creature_template` SET `Rank` = 1, `MinLevelHealth` = 2250, `MaxLevelHealth` = 2250 WHERE `Entry` = 12579;

Reference: https://classic.wowhead.com/npc=12579/bloodfury-ripper

**Comment by Wolffenstein** [comment]
This NPC is no longer elite since patch 2.3, he's correct as is.
