### ISSUE TITLE
[Talent][Paladin][Fanaticism] Threat reduction works even with Righteous Fury

### ISSUE THREAD

**Issue by nikko8085** [Atlantiss/NetherwingBugtracker#8031]
**Description**: 
The paladin talent "Fanaticism" gives a threat reduction. This threat reduction is still present even if the paladin uses Righteous Fury.

**Current behaviour**:
The threat reduction persists through application of Righteous Fury. We tested it while debugging threat meters.
**Expected behaviour**: 
The threat reduction should be removed through application of Righteous Fury.
**Server Revision**: 
3651

Source that it should be removed:
https://tbcdb.com/?spell=31883 (and in-game tooltip)

**Comment by Wolffenstein** [comment]
Fixed in rev 3652.
