### ISSUE TITLE
The S2 off-hand weapon is need AV-medal?

### ISSUE THREAD

**Issue by wangzong214** [Atlantiss/NetherwingBugtracker#8033]
[//]: # (Enclose links to things related to the bug using http://wowhead.com or any other TBC database.)
https://tbc.wowhead.com/item=28346/gladiators-endgame
[//]: # (You can use screenshot ingame to visual the [issue.)](url)
![image](https://user-images.githubusercontent.com/98457364/151147144-5a50ec67-feb4-496f-b000-f3704b06cf37.png)

[//]: # (Write your tickets according to the 

[//]: # ([Quest][Azuremyst Isle] Red Snapper - Very Tasty!)
[//]: # ([NPC] Magistrix Erona)
[//]: # ([Spell][Mage] Fireball)
[//]: # ([Npc][Drop] Ghostclaw Lynx)
[//]: # ([Web] Armory doesnt work)
[//]: # (To find server revision type `.server info` command in the game chat.)

**Description**: 
i think the S2 off-hand weapon maybe need 20xeots mark of honor,dont need av mark of honor.
**Current behaviour**:

**Expected behaviour**: 

**Server Revision**:

**Comment by Godmatik** [comment]
Confirmed - it should be 20 EOTS marks and not AV marks. Something to note when S4 launches.

It also mentions the cost is 9000 honor, not 10,500

https://www.wowhead.com/tbc/item=31978/merciless-gladiators-endgame#comments
https://www.wowhead.com/tbc/item=32961/merciless-gladiators-reprieve#comments
