### ISSUE TITLE
Gladiator 2h bug, losing 13%. Crit when equipping vengeful gladiator’s bonecracker

### ISSUE THREAD

**Issue by Dizzy44** [Atlantiss/NetherwingBugtracker#8036]
**Expected 
![F718CAF9-4117-42BE-A424-68262DAD4EC8](https://user-images.githubusercontent.com/101353243/157718228-2d5b3a65-8125-494a-b0a1-e56ccea0536a.jpeg)
![2B571C43-BDA6-4A55-8634-C19BC0EF2AB1](https://user-images.githubusercontent.com/101353243/157718188-5785fefa-175a-41f2-88e2-7adf526eaa12.jpeg)

**Server Revision**:

**Comment by Godmatik** [comment]
You need to max your weapon skill
