### ISSUE TITLE
[NPC] Mobaz (Rare spawn)

### ISSUE THREAD

**Issue by Godmatik** [Atlantiss/NetherwingBugtracker#8037]
Named mob in Hellfire Peninsula named "Mobaz" drops no loot and his inhale ability doesn't work.

His loot/ability info is not present anywhere on wowhead, nor are there any comments, leading me to believe this was an unreleased mob that shouldn't exist.

https://www.wowhead.com/tbc/npc=18979/mobaz

**Comment by Wolffenstein** [comment]
Fixed in rev 3688.
