### ISSUE TITLE
Cast Bar/Animation vanishing

### ISSUE THREAD

**Issue by Foodlenz** [Atlantiss/NetherwingBugtracker#8038]
**Description**: 
Sometimes after canceling a cast and then spamming keys for the next cast, the second cast bar and animation will vanish. Not sure if this is lag related or code related, visually bugged locally or for all people around you. 
I remembered it happening a few times back when I was playing on Kara and jumped back on to test it and see if I could reproduce it due to the upcoming new realm. Seems I could, about 50% of the time.

Step 1: Begin casting a spell.
Step 2: Cancel the cast by moving.
Step 3: Press your keybind to begin casting a new spell. 
Step 4: Press that same keybind again ~0.2sec after the initial press.
Step 5: Your cast bar will appear to cancel, though if you continue to stand still your spell will still complete.
Video: https://www.youtube.com/watch?v=lq_MEoDzYfM

You'll see the second cast bar show up briefly, then once the server registers the second press, it'll look like the cast cancels. The bar will vanish and the cast animation will fade.

If you then don't move (and therefore cancel the hidden cast), the spell that you were spamming will cast once the hidden cast bar completes.

It's more annoying than gamebreaking, as you'll move try cast again, cast bar vanishes and you're not sure if the cast is still happening or if you accidentally stopped it by moving. Gambling with the tanks life :D

**Current behaviour**:
Double tapping (with a slight delay) a cast time spell after having canceled a spell via moving will cause the cast bar/animation to vanish.

**Expected behaviour**: 
Server should register to first command to cast and begin casting, the second press should be seen as "spell already casting" and either ignored or queued.

**Server Revision**: 
Atlantis Kara.

**Comment by Wolffenstein** [comment]
Can't reproduce on low ping, since you have like 300ms weird shit can happen

**Comment by Foodlenz** [comment]
Yeah one of the many joys of being on the opposite side of the world. 
Works fine if i don't spam the button so i'll just try not to do that when making micro movement adjustments.
