### ISSUE TITLE
[Spell] [On cast/ On hit procs] [Druid] Nature's Grace proc twice

### ISSUE THREAD

**Issue by Onsty** [Atlantiss/NetherwingBugtracker#8039]
[//]: # (Enclose links to things related to the bug using http://wowhead.com or any other TBC database.)
[//]: # (You can use screenshot ingame to visual the issue.)
[//]: # (Write your tickets according to the format:)
[//]: # ([Quest][Azuremyst Isle] Red Snapper - Very Tasty!)
[//]: # ([NPC] Magistrix Erona)
[//]: # ([Spell][Mage] Fireball)
[//]: # ([Npc][Drop] Ghostclaw Lynx)
[//]: # ([Web] Armory doesnt work)
[//]: # (To find server revision type `.server info` command in the game chat.)

**Description**: Nature's Grace proc twice, on cast and on hit. Other classes on cast only procs might be also fucked up, didn't check tho. This one wasn't a case just 2 weeks ago, so it probably comes with some of early January updates.

**Current behaviour**: Nature's Grace proc twice

**Expected behaviour**: Should proc only on cast (that will crit)

**Server Revision**: 3651

https://user-images.githubusercontent.com/44346265/213867297-72fe5d5c-2a8c-4f4d-b8ac-1414242f775c.mp4

**Comment by Wolffenstein** [comment]
Fixed in rev 3685.
