### ISSUE TITLE
[Quest][Hillsbrad Foothills] Elixir of Suffering/Agony/Pain

### ISSUE THREAD

**Issue by totaemoeggerli** [Atlantiss/NetherwingBugtracker#804]
[//]: # (Enclose links to things related to the bug using http://wowhead.com or any other TBC database.)
[//]: # (You can use screenshot ingame to visual the issue.)
[//]: # (Write your tickets according to the format:)
[//]: # ([Quest][Azuremyst Isle] Red Snapper - Very Tasty!)
[//]: # ([NPC] Magistrix Erona)
[//]: # ([Spell][Mage] Fireball)
[//]: # ([Npc][Drop] Ghostclaw Lynx)
[//]: # ([Web] Armory doesnt work)

**Description**: 
[Elixir of Suffering](https://www.wowhead.com/quest=496/deprecated-elixir-of-suffering)
[Elixir of Pain](https://www.wowhead.com/quest=501/deprecated-elixir-of-pain) 
[Elixir of Agony](https://www.wowhead.com/quest=509/deprecated-elixir-of-agony)
This is a huge quest chain in Hillsbrad Foothills that start at [Apothecary Lydon](https://www.wowhead.com/npc=2216/apothecary-lydon#comments) in Tarrens Mill.

**Current behaviour**:
Players can pick up Elixir of Pain and Elixir of Agony without doing the pre quest.
[All three quests are active](https://imgur.com/a/2STKFC1)

**Expected behaviour**: 
Players shouldn't be able to accept all three quests right away. The quest chain starts with Elixir of Suffering. After finishing this part you can pick up Elixir of Pain. Elixir of Agony is the final part of the chain.

**Server Revision**: 
2078

**Comment by Easyfraggy** [comment]
Duplicate https://github.com/Atlantiss/NetherwingBugtracker/issues/408
