### ISSUE TITLE
Curse of the Bleeding Hollow

### ISSUE THREAD

**Issue by Carneyy** [Atlantiss/NetherwingBugtracker#8040]
[//]: # (Enclose links to things related to the bug using http://wowhead.com or any other TBC database.)
[//]: # (You can use screenshot ingame to visual the issue.)
[//]: # (Write your tickets according to the format:)
[//]: # ([Quest][Azuremyst Isle] Red Snapper - Very Tasty!)
[//]: # ([NPC] Magistrix Erona)
[//]: # ([Spell][Mage] Fireball)
[//]: # ([Npc][Drop] Ghostclaw Lynx)
[//]: # ([Web] Armory doesnt work)
[//]: # (To find server revision type `.server info` command in the game chat.)

**Description**: https://www.wowhead.com/tbc/spell=34073/curse-of-the-bleeding-hollow
I couldn't remove this spell by hunter talents mend pet.

**Current behaviour**:
Improved Mend Pet from talents doesn't remove this effect.
**Expected behaviour**: 
Should be dispelled by Mend Pet with hunter tallents into it.
**Server Revision**:

**Comment by Wolffenstein** [comment]
Fixed in rev 3829.
