### ISSUE TITLE
Centaur Ear - drop rate

### ISSUE THREAD

**Issue by Carneyy** [Atlantiss/NetherwingBugtracker#8041]
[//]: # (Enclose links to things related to the bug using http://wowhead.com or any other TBC database.)
[//]: # (You can use screenshot ingame to visual the issue.)
[//]: # (Write your tickets according to the format:)
[//]: # ([Quest][Azuremyst Isle] Red Snapper - Very Tasty!)
[//]: # ([NPC] Magistrix Erona)
[//]: # ([Spell][Mage] Fireball)
[//]: # ([Npc][Drop] Ghostclaw Lynx)
[//]: # ([Web] Armory doesnt work)
[//]: # (To find server revision type `.server info` command in the game chat.)

**Description**: 
https://www.wowhead.com/tbc/item=6067/centaur-ear 
https://www.wowhead.com/tbc/quest=1366/centaur-bounty
Centaur Ears seems to drop too low I had to kill between 120-140 mobs (tested 3 times) to get 15 ears for quest while expected drop chance on mob I killed supposed to be 31%-29%. I might be wrong but worth to check it.
**Current behaviour**:
Low drop rate from mobs:
https://www.wowhead.com/tbc/npc=4642/magram-stormer
https://www.wowhead.com/tbc/npc=4645/magram-mauler
https://www.wowhead.com/tbc/npc=4641/magram-windchaser
https://www.wowhead.com/tbc/npc=4640/magram-wrangler
https://www.wowhead.com/tbc/npc=4639/magram-outrunner
https://www.wowhead.com/tbc/npc=4638/magram-scout#sounds
**Expected behaviour**: 
Correct drop rate from linked mobs above.
**Server Revision**:

**Comment by Wolffenstein** [comment]
Fixed in rev 3688.
