### ISSUE TITLE
Hunter pet abilities

### ISSUE THREAD

**Issue by Carneyy** [Atlantiss/NetherwingBugtracker#8042]
[//]: # (Enclose links to things related to the bug using http://wowhead.com or any other TBC database.)
[//]: # (You can use screenshot ingame to visual the issue.)
[//]: # (Write your tickets according to the format:)
[//]: # ([Quest][Azuremyst Isle] Red Snapper - Very Tasty!)
[//]: # ([NPC] Magistrix Erona)
[//]: # ([Spell][Mage] Fireball)
[//]: # ([Npc][Drop] Ghostclaw Lynx)
[//]: # ([Web] Armory doesnt work)
[//]: # (To find server revision type `.server info` command in the game chat.)

**Description**: 
So when you learn pet new rank of abilities for example you have Growl rank 3 then you teach him Growl rank 4 you will have both ranks on your pet bar that activate every time you call him. The only solution I found is reach 4 spells that you use during pet endgame so those new spells won't take empty slot. Also when you learn new rank it doesn't uptade spell on bar automaticly you have to drag it from spell book.
![obraz](https://i.imgur.com/5BusWHJ.png)

**Current behaviour**:
You can have pet with 3 different growls/any other spell that you upgrade rank level scaling them from lowest to highest levels 
on pet bar.
**Expected behaviour**: 
You have 1 type of pet ability on pet bar & automaticly upgrade ranks when you teach your pet new rank of spell.
**Server Revision**: 
[3685]

**Comment by Wolffenstein** [comment]
Fixed in rev 3689.
