### ISSUE TITLE
[QUEST] War on the Woodpaw

### ISSUE THREAD

**Issue by Godmatik** [Atlantiss/NetherwingBugtracker#8043]
Quest item that drops for quest War of the Woodpaw appears too low: 

Should be: 
45% or so for most mobs - based on wowhead
https://www.wowhead.com/classic/item=9237/woodpaw-gnoll-mane#dropped-by

Is currently: 
Probably closer to 25%

**Comment by Wolffenstein** [comment]
Fixed in rev 3688.
