### ISSUE TITLE
[TALENT][SPELL][WARLOCK] Nether Protection pops while using Rain of FIre

### ISSUE THREAD

**Issue by duzyizly** [Atlantiss/NetherwingBugtracker#8044]
**Description**: 
While using rain of fire there's a chance to get Nether Protection buff (tested with 3/3 talent).

![image](https://user-images.githubusercontent.com/43931626/215549211-8bd7ac9f-2d54-4c2c-bbed-db40ac7360ab.png)

**Server Revision**: 
3651

**Comment by Wolffenstein** [comment]
Fixed in rev 3688.
