### ISSUE TITLE
[NPC] Bael'dun Foreman

### ISSUE THREAD

**Issue by Godmatik** [Atlantiss/NetherwingBugtracker#8045]
Currently: 
This NPC spams his "Torch Toss" ability every action and never melees.

How it should work: 
He should throw it once at the start of combat (to apply the debuff), then melee you afterward. Maybe a cooldown on the ability is missing.

https://tbc.wowhead.com/npc=3375/baeldun-foreman#abilities

**Comment by Wolffenstein** [comment]
Fixed in rev 3688.
