### ISSUE TITLE
High Astromancer Solarion - Arcane Missiles

### ISSUE THREAD

**Issue by Godmatik** [Atlantiss/NetherwingBugtracker#8047]
**Currently**
Solarion will only target the tank (or whoever has highest threat) with Arcane Missiles cast

**How it should work**
She should instead always target a random raid member and cast Arcane Missiles on that person. Confirmed on classic, and also note the comments on wowhead

https://www.wowhead.com/tbc/spell=39414/arcane-missiles#used-by-npc

**Comment by Wolffenstein** [comment]
In 2.0 she casts Arcane Missiles on a random target IN FRONT of her (which usually is tank). It got changed to fully random in 2.1
