### ISSUE TITLE
Akiris Reed - drop rate

### ISSUE THREAD

**Issue by Carneyy** [Atlantiss/NetherwingBugtracker#8048]
[//]: # (Enclose links to things related to the bug using http://wowhead.com or any other TBC database.)
[//]: # (You can use screenshot ingame to visual the issue.)
[//]: # (Write your tickets according to the format:)
[//]: # ([Quest][Azuremyst Isle] Red Snapper - Very Tasty!)
[//]: # ([NPC] Magistrix Erona)
[//]: # ([Spell][Mage] Fireball)
[//]: # ([Npc][Drop] Ghostclaw Lynx)
[//]: # ([Web] Armory doesnt work)
[//]: # (To find server revision type `.server info` command in the game chat.)

**Description**: 
https://www.wowhead.com/tbc/item=4029/akiris-reed
It supposed to have 39% while it looks more for 5-10% right now.
**Current behaviour**:
too low drop rate 
**Expected behaviour**: 
It supposed to have 39% drop chance
**Server Revision**:

**Comment by Wolffenstein** [comment]
Fixed in rev 3696.
