### ISSUE TITLE
[NPC][Encounter] Kalecgos - Curse of Boundless Agony is disappearing somehow

### ISSUE THREAD

**Issue by MecAtlantiss** [Atlantiss/NetherwingBugtracker#8049]
**Description**: Instances of Curse of Boundless Agony are somehow disappearing. You can see in the video linked below from Karazhan server that maximum amount of curses in the raid group is 3, but later into the fight there is only 1 curse in the group. I wish I could tell you more about the circumstances of what causes a curse to disappear, but I'm not sure. My first assumption is that it has something to do with no one being nearby to pass the curse onto (e.g. being the last person in dark realm and dying), but this bug happens very consistently each pull so I sort of doubt that's the reason. 

https://www.youtube.com/watch?v=1aXJRIjcYeY

**Current behaviour**: An instance of Curse of Boundless Agony should never stop existing.

**Expected behaviour**: Instances of Curse of Boundless Agony are somehow disappearing from the raid.

**Comment by Nihil48** [comment]
Saw disappearing curses at Karazhan too.
 Didn't make tests but it seemed to me there was just 30sec pass and curse disappear.
So, dispel = curse jump. 30 sec = curse disappear instead

**Comment by Godmatik** [comment]
Resolved, closing
