### ISSUE TITLE
"feel rested" outside of tavern

### ISSUE THREAD

**Issue by samemari** [Atlantiss/NetherwingBugtracker#805]
[//]: # (Enclose links to things related to the bug using http://wowhead.com or any other TBC database.)
[//]: # (You can use screenshot ingame to visual the issue.)
[//]: # (Write your tickets according to the format:)
[//]: # ([Quest][Azuremyst Isle] Red Snapper - Very Tasty!)
[//]: # ([NPC] Magistrix Erona)
[//]: # ([Spell][Mage] Fireball)
[//]: # ([Npc][Drop] Ghostclaw Lynx)
[//]: # ([Web] Armory doesnt work)

**Description**: 
Got message "feel rested" when was outside the tavern in Darkshire. 
**Current behaviour**:

**Expected behaviour**: 
"Feel rested" must appear after spending some time in taverns or capitals only.
**Server Revision**: 
[11:15:42]AtlantissCoreTBC - rev: 2078
[11:15:42]Online players: 45 (max: 47)
[11:15:42]Active connections: 49 (max: 49) Queued connections: 0 (max: 0)
[11:15:42]Server uptime: 2 Hour(s) 7 Minute(s) 46 Second(s).
[11:15:42]Current time: 2018-09-28 10:15:47
[11:15:42]Content Patch: 203.

![wowscrnshot_092818_111243](https://user-images.githubusercontent.com/29822974/46196536-0f657300-c310-11e8-89a5-0eda980fe98c.jpg)

**Comment by Neophrone** [comment]
Feel rested should appear everywhere. But in capital or in tavern u'll gain 4x points of double exp for the same amount of time outside. But outside tavern or city rest bonus should accumulate only when u logged out.

**Comment by Tereneckla** [comment]
You can get rested standing at the wall of the tavern.
![WoWScrnShot_010720_162929](https://user-images.githubusercontent.com/50233983/71906730-f1213080-316a-11ea-8299-046e9046a851.jpg)

**Comment by The14me** [comment]
That's not a bug since u can get rested in the city ( no need to be in the tavern) 
Can be closed.

**Comment by Tereneckla** [comment]
You can't get get rested in Darkshire. Just in the tavern (or slightly outside currently aswell)

**Comment by Wolffenstein** [comment]
"When visiting one of the six main cities (Darnassus, Ironforge, Orgrimmar, Stormwind, Thunder Bluff and The Undercity), players do not need to check into the Inn to rest. Players will however still need to seek an Innkeeper to receive a Hearthstone or to bind themselves to the city. You will still need to rest at an Inn in smaller towns."

The inn areatrigger just checks the radius/AABox, sometimes you can get away with doing stuff like on the screenshot and that's blizzlike.
