### ISSUE TITLE
[Quest] Stinky's Escape

### ISSUE THREAD

**Issue by Godmatik** [Atlantiss/NetherwingBugtracker#8050]
Stinky's Escape quest in Dustwallow Marsh

**Currently:**
NPC Stinky Ignatz appears to be set on passive stance during the escort quest, won't assist you in attacking any mobs, will only attack mobs that attack him first

**How it should work:**
The NPC should assist if a mob is attacking you while nearby, similar to other escort NPCs

https://www.wowhead.com/classic/npc=4880/stinky-ignatz
https://www.wowhead.com/classic/quest=1222/stinkys-escape

**Comment by Wolffenstein** [comment]
Fixed in rev 3696.
