### ISSUE TITLE
Secondary talent tree loss of talents

### ISSUE THREAD

**Issue by ezamosch** [Atlantiss/NetherwingBugtracker#8051]
[//]: # (Enclose links to things related to the bug using http://wowhead.com or any other TBC database.)
[//]: # (You can use screenshot ingame to visual the issue.)
[//]: # (Write your tickets according to the format:)
[//]: # ([Quest][Azuremyst Isle] Red Snapper - Very Tasty!)
[//]: # ([NPC] Magistrix Erona)
[//]: # ([Spell][Mage] Fireball)
[//]: # ([Npc][Drop] Ghostclaw Lynx)
[//]: # ([Web] Armory doesnt work)
[//]: # (To find server revision type `.server info` command in the game chat.)

**Description*: I did bring 44 talents in frost tree. Switched to arcane tree. Put some there, after this switched to the frost tree and saw that all my talents did loss.
![image](https://user-images.githubusercontent.com/48468561/220455862-7fcdca89-5f5a-4d2e-8442-5c090f28d519.png)
![image](https://user-images.githubusercontent.com/48468561/220455885-e846d87f-1a4c-45fe-b4fc-75892f7bc742.png)

**Current behaviour**: talents loss.

**Expected behaviour**: talents should not loss.

**Server Revision**: public test realm TBC

**Comment by Wolffenstein** [comment]
should be fixed now
