### ISSUE TITLE
Talent tree resets

### ISSUE THREAD

**Issue by Raferty** [Atlantiss/NetherwingBugtracker#8052]
[//]: # (Enclose links to things related to the bug using http://wowhead.com or any other TBC database.)
[//]: # (You can use screenshot ingame to visual the issue.)
[//]: # (Write your tickets according to the format:)
[//]: # ([Quest][Azuremyst Isle] Red Snapper - Very Tasty!)
[//]: # ([NPC] Magistrix Erona)
[//]: # ([Spell][Mage] Fireball)
[//]: # ([Npc][Drop] Ghostclaw Lynx)
[//]: # ([Web] Armory doesnt work)
[//]: # (To find server revision type `.server info` command in the game chat.)

**Description**: 
Talent tree resets when multiple clicking on talents

**Current behaviour**:
Reset by multiple clicking on "Heart of the wild", "Survival of the fittest", "Predatory instincts"

**Expected behaviour**: 
must not be reseted

**Server Revision**:

**Comment by Cold-Martijn** [comment]
Does the entire talent tree reset? Or just single talents?

**Comment by Wolffenstein** [comment]
Character name?

**Comment by Raferty** [comment]
Raferty
Resetting the entire talent tree

**Comment by Wolffenstein** [comment]
Can you record it and upload the video here?

**Comment by Godmatik** [comment]
I have reproduced, happens on 2nd spec after 1st spec is made, will make a video

**Comment by Godmatik** [comment]
https://www.youtube.com/watch?v=w-888HrUI1Q

@Wolffenstein 
only tested with druid doing talents listed above

**Comment by Raferty** [comment]
yep, i did same steps

**Comment by Godmatik** [comment]
happens on holy pally as well so not limited to druid, can kind of reproduce but it feels random. tested without learning dual spec and it happened again.

**Comment by Wolffenstein** [comment]
should be fixed now
