### ISSUE TITLE
Dual talent sets spellpower to 0

### ISSUE THREAD

**Issue by Borcsa134** [Atlantiss/NetherwingBugtracker#8053]
**Description**: 
Dual talent specialization sets all the bonus damage and bonus healing to 0,
**Current behaviour**:
When changing talents, spellpower goes to 0 and have to reequip everything. Relog makes it work again.
**Expected behaviour**: 
Spellpower is calculated based on the new talents and baseline from gear.
**Server Revision**: 
3695

**Comment by Borcsa134** [comment]
![image](https://user-images.githubusercontent.com/25614829/220472743-485e2755-076b-4258-9af4-96d8351902e6.png)

**Comment by Godmatik** [comment]
Confirmed - and its not just a visual bug - your sp/healing does actually reduce to 0.

Relogging does solve, no need to equip/unequip gear.

**Comment by Wolffenstein** [comment]
should be fixed now
