### ISSUE TITLE
Battlegear level 70 Pvp Rewards not on the database

### ISSUE THREAD

**Issue by DadSerber** [Atlantiss/NetherwingBugtracker#8054]
[//]: # (Enclose links to things related to the bug using http://wowhead.com or any other TBC database.)
[//]: # (You can use screenshot ingame to visual the issue.)
[//]: # (Write your tickets according to the format:)
[//]: # ([Quest][Azuremyst Isle] Red Snapper - Very Tasty!)
[//]: # ([NPC] Magistrix Erona)
[//]: # ([Spell][Mage] Fireball)
[//]: # ([Npc][Drop] Ghostclaw Lynx)
[//]: # ([Web] Armory doesnt work)
[//]: # (To find server revision type `.server info` command in the game chat.)

**Description**: 
Battlegear level 70 Pvp Rewards not on the database
**Current behaviour**:
Battlegear level 70 Pvp Rewards not on the database
**Expected behaviour**: 
Should be on the database. https://imgur.com/a/rYYBsTj
**Server Revision**:

**Comment by Godmatik** [comment]
Those are only available in patch 2.4, the server is on patch 2.0
