### ISSUE TITLE
Gnomish Battle Chicken

### ISSUE THREAD

**Issue by Peachusftw** [Atlantiss/NetherwingBugtracker#8055]
[//]: # (Enclose links to things related to the bug using http://wowhead.com or any other TBC database.)
[//]: # (You can use screenshot ingame to visual the issue.)
[//]: # (Write your tickets according to the format:)
[//]: # ([Quest][Azuremyst Isle] Red Snapper - Very Tasty!)
[//]: # ([NPC] Magistrix Erona)
[//]: # ([Spell][Mage] Fireball)
[//]: # ([Npc][Drop] Ghostclaw Lynx)
[//]: # ([Web] Armory doesnt work)
[//]: # (To find server revision type `.server info` command in the game chat.)

**Description**: 
[Npc] Gnomish Battle Chicken (https://www.wowhead.com/tbc/npc=8836/battle-chicken) doesn't interact as expected.
**Current behaviour**:
Chicken doesn't engage in melee unless directly hit, doesn't squawk or enrage at all. 
**Expected behaviour**: 
Chicken should act as an guardian npc, i.e.: fight alongside player, should also occasionally enrage and/or buff party with Battle Squawk (https://www.wowhead.com/tbc/spell=23060/battle-squawk) - multiple instances of Battle Squawk stack with one another, as is evident in a multitude of TBC classic videos
**Server Revision**:

**Comment by Wolffenstein** [comment]
Fixed in rev 3700.
