### ISSUE TITLE
Flight Path Issue

### ISSUE THREAD

**Issue by Chunx97** [Atlantiss/NetherwingBugtracker#8056]
[//]: # (Enclose links to things related to the bug using http://wowhead.com or any other TBC database.)
[//]: # (You can use screenshot ingame to visual the issue.)
[//]: # (Write your tickets according to the format:)
[//]: # ([Quest][Azuremyst Isle] Red Snapper - Very Tasty!)
[//]: # ([NPC] Magistrix Erona)
[//]: # ([Spell][Mage] Fireball)
[//]: # ([Npc][Drop] Ghostclaw Lynx)
[//]: # ([Web] Armory doesnt work)
[//]: # (To find server revision type `.server info` command in the game chat.)

**Description**:  Flight path forcing myself to ride flight path mount for an extra period of time.
 ( Was typing to people in game to ensure it was not lag causing this issue )

**Current behaviour**: Honor Hold to Telhamat ( Hellfire ) took roughly 3:30 to dismount.

**Expected behaviour**:  Honor Hold to Telhamat ( Hellfire ) Is roughly a 1:12 Flight path

**Server Revision**:

**Comment by Wolffenstein** [comment]
should be fixed
