### ISSUE TITLE
Flight to Area 52 - stuck on mount

### ISSUE THREAD

**Issue by Godmatik** [Atlantiss/NetherwingBugtracker#8057]
When flying from Shattrath to Area 52, I was stuck on the mount upon landing, see below screenshot.

When I relogged, I was in the middle of Zangarmarsh back on the flight path. When I landed in Area 52 this (second) time, I was still stuck on the mount.

Every relog brought me a bit closer, but everytime I landed, I was still always stuck.

EDIT: 7 or so relogs later, it landed me with no mount.

![WoWScrnShot_022123_221006](https://user-images.githubusercontent.com/37913400/220520168-0c1f94e8-7256-457a-8e1b-10750fd7696b.jpg)

**Comment by Wolffenstein** [comment]
should be fixed
