### ISSUE TITLE
Tempest Keep Attunement

### ISSUE THREAD

**Issue by Godmatik** [Atlantiss/NetherwingBugtracker#8059]
Can currently enter Tempest Keep with no key or attunement complete.

Wasn't sure if intended for PTR only - I tested entering SSC and it wouldn't let me until I finished that particular attunement quest.

**Comment by duzyizly** [comment]
Confirming, You can enter Arcatraz w/o a key.

**Comment by Wolffenstein** [comment]
Fixed in rev 3696.
