### ISSUE TITLE
Spell/Animation delay

### ISSUE THREAD

**Issue by Godmatik** [Atlantiss/NetherwingBugtracker#8060]
When compared to Karazhan server - there is currently a small amount of delay when casting spells + doing animations on the PTR.

Some examples below.

https://cdn.discordapp.com/attachments/1063133089657798730/1077819390222946395/Mind_flay_PTR.mp4

https://cdn.discordapp.com/attachments/1063133089657798730/1077820114675707975/Rec_123.mp4

**Comment by Wolffenstein** [comment]
sanitizer is on
