### ISSUE TITLE
Spell pushback, batching, backlash

### ISSUE THREAD

**Issue by ghost** [Atlantiss/NetherwingBugtracker#8062]
**Description**: Hardcasted CC that breaks on damage (eg. Polymorph) cannot be countered by abilites that have a backlash (self-damage) component (eg. SW:Death) due to lack of spell batching.

**Current behaviour**:

**Expected behaviour**: 

**Server Revision**: **3697**

**Comment by Wolffenstein** [comment]
In general Spell Delay is turned off (besides a few exceptions) so I added SW:D and UA dispel backlash damages to the list in rev 3699.
