### ISSUE TITLE
Racial swap doesn't change Priest race specific spells

### ISSUE THREAD

**Issue by kelsul** [Atlantiss/NetherwingBugtracker#8067]
**Description**: When swapping races with Priest only the general racials are changed, but the race specific spells stay the same. E.g. when swapping from Draenei to Night Elf I gain the NE racials, but keep the spell Symbol of Hope and don't gain Starshards.

**Expected behaviour**: Race specific spells should (probably?) change too.

**Server Revision**: 3695

**Comment by Wolffenstein** [comment]
That is intended (at least for now).
