### ISSUE TITLE
Mana Wraith not affected by slows (fb, imp blizz)

### ISSUE THREAD

**Issue by adzz452** [Atlantiss/NetherwingBugtracker#8069]
[//]: # (Enclose links to things related to the bug using http://wowhead.com or any other TBC database.)
[//]: # (You can use screenshot ingame to visual the issue.)
[//]: # (Write your tickets according to the format:)
[//]: # ([Quest][Azuremyst Isle] Red Snapper - Very Tasty!)
[//]: # ([NPC] Magistrix Erona)
[//]: # ([Spell][Mage] Fireball)
[//]: # ([Npc][Drop] Ghostclaw Lynx)
[//]: # ([Web] Armory doesnt work)
[//]: # (To find server revision type `.server info` command in the game chat.)

**Description**: Mana Wraiths outside Area 52 not able to be slowed by frost abilities

**Current behaviour**: no slows affect the mobs

**Expected behaviour**:  mana wraith's are affected by slows: 11:00 https://www.youtube.com/watch?v=ZPWvEue8iRI&t=659s

**Server Revision**:  3695

**Comment by Wolffenstein** [comment]
Fixed in rev 3696.
