### ISSUE TITLE
[NPC] Not enough Slitherblade Nagas at Sar'theris Strand in Desolace

### ISSUE THREAD

**Issue by Jezofine** [Atlantiss/NetherwingBugtracker#807]
**Current behaviour**:
Slitherblade Naga (id 4711): 1 ashore, 2 or so underwater, scattered around. Too many Slitherblade Warriors and Sorceresses.
Also there's one lost Naga on a far island around (30, 7), should not be there.

**Expected behaviour**: 
More Nagas along Sar'theris Strand shore and under water around ruins at (37, 22).
In [Joana's leveling video](https://youtu.be/WEOf6e6gFZo?list=PLMeJnlp72R7p-X7PgsMFqqjPtcxhF7kB_&t=3071) there are clearly many nagas.
I can't find spawn points from thottbot or wowhead archive so I'll use [Slitherblade Naga (Hellground db)](http://db.hellfire-tbc.com/?npc=4711) since it's pretty accurate.

[From Joana's guide](https://www.joanasworld.com/horde-31-40.html#32-Desolace):
"06) Finish up "Other Fish to Fry": kill the Slitherblade mobs.  The Myrmidon are scattered between the two biggest islands, the Naga are more towards the shore and their are only a few Sorceresses scattered everywhere."
[Areas on map](https://www.joanasworld.com/images/guide/35-desolace.jpg)

**Server Revision**: 2078

**Comment by Kidcudi123** [comment]
This makes sense since I killed a myrmidon and next spawn there was another kind there

**Comment by totaemoeggerli** [comment]
This doesn't make sense. Some mobs aren't part of the [quest](https://www.wowhead.com/quest=6143/other-fish-to-fry) and players will skip them as much as possible. The balance will be off extremly quickly. I searched the whole area for myrmidons and only found two. Now I have to kill mobs and hope they respawn as Myrmidons? That's retarded.

These are the mobs that are part of the quest:
[slitherblade-sorceress](https://www.wowhead.com/npc=4712/slitherblade-sorceress)
[slitherblade-naga](https://www.wowhead.com/npc=4711/slitherblade-naga)
[slitherblade-myrmidon](https://www.wowhead.com/npc=4714/slitherblade-myrmidon)

These are not part of the quest:
https://www.wowhead.com/npc=4716/slitherblade-tidehunter
https://www.wowhead.com/npc=4713/slitherblade-warrior
https://www.wowhead.com/npc=4715/slitherblade-razortail
https://www.wowhead.com/npc=4718/slitherblade-oracle
https://www.wowhead.com/npc=4719/slitherblade-sea-witch

The maps on Wowhead suggest that they have clear distinct spwan loactions (yes, this is post cata). If you want shared spawns please exclude the one required for the quest.

**Comment by aresbrutus** [comment]
FYI, not ALL mobs of the same name shar spawn points, sometimes only 1 half/group will share it. So don't assume when I say, shamans share spawn with warriors, that it does in 5 camps. Maybe it is only in 1 camp. But thanks for the comments, I will do some research on this when I got the time.

**Comment by aresbrutus** [comment]
Fixed in one of the upcoming updates.
