### ISSUE TITLE
Pet despawn range

### ISSUE THREAD

**Issue by Godmatik** [Atlantiss/NetherwingBugtracker#8072]
Pets should despawn when approximately 100 yards away from their master.

Currently that range is set much higher, closer to 160 or more yards.

Most noticeable on Archimonde fight - when a warlock has an infernal out - if they get knocked very far away far their infernal is still active.

https://www.reddit.com/r/classicwow/comments/c6gzkp/classic_question_pet_range/

**Comment by Wolffenstein** [comment]
Fixed in rev 3696.
