### ISSUE TITLE
Black Character Screen

### ISSUE THREAD

**Issue by Fearyii** [Atlantiss/NetherwingBugtracker#8074]
**Description**: 
When logging into the on MacOS there is a problem that causes black character screen that is caused by Warden

**Current behaviour**:
Sometimes the character screen is black and is not letting u login

**Expected behaviour**: 
Should be able to just login with no issues

**Server Revision**: 
There was a fix already done in [4dccd56](https://github.com/vmangos/core/commit/4dccd56e28efb7b609d99562feda3bdce7968fe9)

**Comment by Wolffenstein** [comment]
Try again in rev 3700.
