### ISSUE TITLE
[QUEST] Strained Supplies - not available

### ISSUE THREAD

**Issue by Godmatik** [Atlantiss/NetherwingBugtracker#8076]
Quest "Strained Supplies" not available to be picked up from Sha'nir while at "Hated" reputation level with Aldor - should be able to  improve your Aldor rep.

https://www.wowhead.com/tbc/quest=10017/strained-supplies

Verify that other quest also works as intended (unable to test as character is set at exalted with Scryers)

https://www.wowhead.com/tbc/quest=10024/vorenthals-visions

**Comment by Wolffenstein** [comment]
You need to have "Alliegance to the Aldor/Scryers" (either or) completed.
