### ISSUE TITLE
S3/S4 Arena Vendors are spawned

### ISSUE THREAD

**Issue by Godmatik** [Atlantiss/NetherwingBugtracker#8077]
Ontok Shatterhorn in Shattrath
Big Zokk Torquewrench in Area 52
Grikkin Copperspring in Nagrand
Evee Copperspring in Tanaris
Frixee Brasstumbler in Blades Edge
Drolig Blastpipe + Drelik Blastpipe in Shattrath

The above are currently spawned and selling S4 gear

https://www.wowhead.com/tbc/npc=27668/ontok-shatterhorn
https://www.wowhead.com/tbc/npc=26352/big-zokk-torquewrench
https://www.wowhead.com/tbc/npc=25176/grikkin-copperspring
https://www.wowhead.com/tbc/npc=25177/evee-copperspring
https://www.wowhead.com/tbc/npc=25179/frixee-brasstumbler
https://www.wowhead.com/tbc/npc=27722/drolig-blastpipe
https://www.wowhead.com/tbc/npc=27721/drelik-blastpipe

**Comment by Wolffenstein** [comment]
Fixed in rev 3696.
