### ISSUE TITLE
 Auto Attack starts sharing CD with Auto Shot while Raptor Strike is on CD

### ISSUE THREAD

**Issue by Gornaut** [Atlantiss/NetherwingBugtracker#8078]
**Description**: 
It is well known fact that for both Vanilla and TBC Auto Shot and Auto Attack for hunters are Desynced. 
Due to this fact the unique interaction called melee weaving is possible in both of those expansions.

**Current behaviour**:
Range swing timer and Melee swing timer starts sharing CD when Raptor strike is on CD for Hunters.

Steps to reproduce:
1. Turn off (Uncheck) 'Auto Attack/Auto Shot' in Interface -> Combat;
2. Step into Target's Dummy melee range;
3. Cast Raptor Strike;
4. Step out of Melee zone to be in range of Auto Shot;
5. Cast Auto Shot;
6. While raptor Strike is still on CD as well as Auto Shot Step into melee range again and cast Auto Attack;
7. Auto Attack won't go off until Auto Shot swing timer is reloaded although Melee Weapon Timer is ready.

If Step 3 is omitted and you just Weave Auto shot following by Auto Attack everything works peroperly though.

**Expected behaviour**: 
Auto Attack should go through as soon as Melee Weapon Swing Timer is reloaded no matter if Raptor Strike is on cd or not.
Little Proof from TBC Classic, where the whole concept of melee weaving was based on Swing timers Desyncing.
https://www.youtube.com/watch?v=ylsBOyXFGAE
You can clearly see a guy casting Auto Attack in between Raptor Strikes, while his Auto Shot still reloading.

**Server Revision**: 
3695

**Comment by Wolffenstein** [comment]
Can you record how it currently looks on the PTR?

**Comment by Gornaut** [comment]
> Can you record how it currently looks on the PTR?

Sure, mate. 
Here is the video - https://www.youtube.com/watch?v=Sa1NvYo_qOg
Red timer - Melee Swing Timer
Blue Timer - Range Swing Timer
On the Following Timings 0:10-0:11, 0:23 - 0:25, 0:36-0:37
You can observe the situation when Melee Swing timer is ready, Auto Shot timer is still reloading but you cannot Melee hit Target dummy until Auto Shot fully reloads.

**Comment by Wolffenstein** [comment]
Fixed in rev 3697.
