### ISSUE TITLE
Enhancer Synced swings take up 2 Flurry stacks

### ISSUE THREAD

**Issue by fischerderheld** [Atlantiss/NetherwingBugtracker#8079]
Hi, while i was testing and building my enhacner Ui i relised that synced mainhand offhand(swings within 0,5sec of one anohter) swings take up 2 flurry stacks. In Classic tbc synced swings only took 1 flurry stack. This was also the case in retail tbc I believe but i have no evidense for that. Thanks alot for all the work you are doing.

**Comment by Godmatik** [comment]
Video of proof I found from TBC classic, only need to see the first 30 seconds or so to confirm this interaction does exist there.
https://www.youtube.com/watch?v=UZtUmdm9EIk&ab_channel=Ouro

Going to be harder to find proof from retail TBC but if anyone has it, please provide

**Comment by Wolffenstein** [comment]
that sounds like it might require spell delay, meaning the chances of having this feature in are minimal

**Comment by fischerderheld** [comment]
How about putting an internal cool down on stack consumption of flurry? Could this be a way to fix this?

**Comment by Wolffenstein** [comment]
Fixed in rev 3944.
