### ISSUE TITLE
[NPC] Witherbark Witch Doctor - wrong race totem

### ISSUE THREAD

**Issue by wowthings** [Atlantiss/NetherwingBugtracker#808]
[//]: # (Enclose links to things related to the bug using http://wowhead.com or any other TBC database.)
[//]: # (You can use screenshot ingame to visual the issue.)
[//]: # (Write your tickets according to the format:)
[//]: # ([Quest][Azuremyst Isle] Red Snapper - Very Tasty!)
[//]: # ([NPC] Magistrix Erona)
[//]: # ([Spell][Mage] Fireball)
[//]: # ([Npc][Drop] Ghostclaw Lynx)
[//]: # ([Web] Armory doesnt work)

**Description**: 
[This NPC](https://classicdb.ch/?npc=2555) at Arathi Highlands uses magma totem whenever he engages in combat.
**Current behaviour**:
Sometimes for some reason magma totem uses the visual from the Draenei race.
![wowscrnshot_092818_015551](https://user-images.githubusercontent.com/43504905/46207834-0765fd00-c329-11e8-83e3-1d905423615b.jpg)
![wowscrnshot_092818_015613](https://user-images.githubusercontent.com/43504905/46207833-0765fd00-c329-11e8-8772-e7198b5e4fd5.jpg)

**Expected behaviour**: 
Should be using the horde version.
**Server Revision**: 
2078

**Comment by DarthNekr0s** [comment]
This also happens with Foulweald Totemic npc in ashenvale, his searing totem has draenei appearance

**Comment by xmesaj2** [comment]
fixed in rev 2081
