### ISSUE TITLE
transforming into bear form

### ISSUE THREAD

**Issue by Nechy113** [Atlantiss/NetherwingBugtracker#8080]
Long reaction to the transformation into bear form - https://www.youtube.com/watch?v=uFBYaySd4nA

**Comment by Godmatik** [comment]
The lag/delays on the test server are intended as it is currently in debug mode.

![Debug](https://user-images.githubusercontent.com/37913400/220757992-da918be7-1516-4655-a5ed-de4fb1a96600.png)
