### ISSUE TITLE
[STEAMVAULT] Door Open to 2 Boss

### ISSUE THREAD

**Issue by ImCasual** [Atlantiss/NetherwingBugtracker#8083]
Well i dont have too much to write, just that u can go directly to 2 boss without kill the first one. The door its already open .

**Comment by Wolffenstein** [comment]
???

**Comment by Godmatik** [comment]
I double checked and the door is closed leading to final boss until you kill Hydromancer + Mekgineer and activate their switches, so not sure what he is referring to, can probably be closed

**Comment by ImCasual** [comment]
> I double checked and the door is closed leading to final boss until you kill Hydromancer + Mekgineer and activate their switches, so not sure what he is referring to, can probably be closed

Sorry, to not follow it. But the bugtracker was about the door TO  Mekgineer (2º BOSS), that was open even without u kill Thespia (1º BOSS). The door to final boss, its working as expected

**Comment by Godmatik** [comment]
> > I double checked and the door is closed leading to final boss until you kill Hydromancer + Mekgineer and activate their switches, so not sure what he is referring to, can probably be closed
> 
> Sorry, to not follow it. But the bugtracker was about the door TO Mekgineer (2º BOSS), that was open even without u kill Thespia (1º BOSS). The door to final boss, its working as expected

This is correct, you can do either boss in any order and is intended
