### ISSUE TITLE
Slam/Heroic strike interaction

### ISSUE THREAD

**Issue by Mitoja** [Atlantiss/NetherwingBugtracker#8084]
[//]: # (Enclose links to things related to the bug using http://wowhead.com or any other TBC database.)
[//]: # (You can use screenshot ingame to visual the issue.)
[//]: # (Write your tickets according to the format:)
[//]: # ([Quest][Azuremyst Isle] Red Snapper - Very Tasty!)
[//]: # ([NPC] Magistrix Erona)
[//]: # ([Spell][Mage] Fireball)
[//]: # ([Npc][Drop] Ghostclaw Lynx)
[//]: # ([Web] Armory doesnt work)
[//]: # (To find server revision type `.server info` command in the game chat.)

**Description**: [Spell][Warrior][Slam] Can't use Heroic strike during Slam cast to proc Swordspec talent on Warrior.

**Current behaviour**: Doesn't let you use heroic strike during Slam cast.

**Expected behaviour**:  First 20 seconds of this video : https://www.youtube.com/watch?v=DgVlDAZ1a2c&ab_channel=Konter

**Server Revision**: 3695

**Comment by aplouding** [comment]
Still present on server revision 3701

**Comment by tsu-1** [comment]
This is quite important as it is significant lose of DPS for a warrior in PvE encounters (raids, dungeons).

**Comment by aplouding** [comment]
bump, same here

**Comment by Wolffenstein** [comment]
Fixed in rev 3702.
