### ISSUE TITLE
Druid polearm description bug

### ISSUE THREAD

**Issue by jgv8821** [Atlantiss/NetherwingBugtracker#8085]
**Description**: I went to the Quartermaster Urgronn in Thrallmar and noticed that Blacken Spear polearm was not redded out for me as a druid. I purchased it and could not equip it even though the text is white in the description of the item.  Tried learning polearms from Duelist Larenis but could not.

**Comment by jgv8821** [comment]
Screenshot for more clarity
![Uploading 20230222_210407.jpg…]()

**Comment by jgv8821** [comment]
Screenshot for more clarity:
![20230222_210407](https://user-images.githubusercontent.com/31187540/220806226-ff06af17-5bbf-4cea-928e-1cba9e4c7130.jpg)

**Comment by Wolffenstein** [comment]
PTR-only bug, murloc will no longer teach druids polearms after next update
