### ISSUE TITLE
Stratholme (Baron Door Closed after Killing Ramstein)

### ISSUE THREAD

**Issue by Iluuline** [Atlantiss/NetherwingBugtracker#8086]
[//]: # (Enclose links to things related to the bug using http://wowhead.com or any other TBC database.)
[//]: # (You can use screenshot ingame to visual the issue.)
[//]: # (Write your tickets according to the format:)
[//]: # ([Quest][Azuremyst Isle] Red Snapper - Very Tasty!)
[//]: # ([NPC] Magistrix Erona)
[//]: # ([Spell][Mage] Fireball)
[//]: # ([Npc][Drop] Ghostclaw Lynx)
[//]: # ([Web] Armory doesnt work)
[//]: # (To find server revision type `.server info` command in the game chat.)

**Description**: 
After Killing Ramstein Mindless Undead spawns and attacks the player but after u kill them door not opening for the next Undead wave. I w8 for like 10 mins.
**Current behaviour**:

**Expected behaviour**: 

**Server Revision**:

**Comment by Godmatik** [comment]
Duplicate - Strat currently is mostly stock

https://github.com/Atlantiss/NetherwingBugtracker/issues/5127
