### ISSUE TITLE
Bonus for Heavy Clefthoof set not activated 

### ISSUE THREAD

**Issue by jgv8821** [Atlantiss/NetherwingBugtracker#8087]
[//]: # (Enclose links to things related to the bug using http://wowhead.com or any other TBC database.)
[//]: # (You can use screenshot ingame to visual the issue.)
[//]: # (Write your tickets according to the format:)
[//]: # ([Quest][Azuremyst Isle] Red Snapper - Very Tasty!)
[//]: # ([NPC] Magistrix Erona)
[//]: # ([Spell][Mage] Fireball)
[//]: # ([Npc][Drop] Ghostclaw Lynx)
[//]: # ([Web] Armory doesnt work)
[//]: # (To find server revision type `.server info` command in the game chat.)
![20230222_205508](https://user-images.githubusercontent.com/31187540/220805353-f1c11741-5bde-4be9-a3df-c822e9e76df2.jpg)

**Description**: See picture,  currently have full heavy clefthoof set equip but bonus is grayed out. I do have socketed gems inserted.

**Current behaviour**:

**Expected behaviour**: 

**Server Revision**:

**Comment by jgv8821** [comment]
![20230222_210407](https://user-images.githubusercontent.com/31187540/220805970-629ae12d-a09d-44e0-ab3c-d1ae98bcc739.jpg)
Screenshot for more clarity

**Comment by Wolffenstein** [comment]
It literally says "Requires Leatherworking (350)"
