### ISSUE TITLE
Nether Protection makes warlock immune to NS beams, interrupting absorb

### ISSUE THREAD

**Issue by NeonicSupersonic** [Atlantiss/NetherwingBugtracker#8088]
**Description**: 
Nether Protection proc makes warlock immune to NS beams, preventing absorbing them for a short duration

**Current behaviour**:
Nether Protection proc makes warlock immune to NS beams, preventing absorbing them for a short duration

**Expected behaviour**: 
Nether Protection just like any other sources of immunity should have no interaction with beams

**Server Revision**: 
eb5425213b7e

**Comment by Wolffenstein** [comment]
Can you record a video of that happening? I can't reproduce it
