### ISSUE TITLE
Burning Straw disorient on strawman miniboss in opera sometimes breaks

### ISSUE THREAD

**Issue by NeonicSupersonic** [Atlantiss/NetherwingBugtracker#8089]
**Description**: 
Burning Straw disorient on strawman miniboss in opera sometimes breaks

**Current behaviour**:
Burning Straw disorient on strawman miniboss in opera sometimes breaks while he is continuously attacked by fire spells

**Expected behaviour**: 
permanent disorient

**Server Revision**: 
eb5425213b7e

**Comment by Wolffenstein** [comment]
Fixed in rev 3697.
