### ISSUE TITLE
[NPC] Dangerous! target respawn time

### ISSUE THREAD

**Issue by totaemoeggerli** [Atlantiss/NetherwingBugtracker#809]
[//]: # (Enclose links to things related to the bug using http://wowhead.com or any other TBC database.)
[//]: # (You can use screenshot ingame to visual the issue.)
[//]: # (Write your tickets according to the format:)
[//]: # ([Quest][Azuremyst Isle] Red Snapper - Very Tasty!)
[//]: # ([NPC] Magistrix Erona)
[//]: # ([Spell][Mage] Fireball)
[//]: # ([Npc][Drop] Ghostclaw Lynx)
[//]: # ([Web] Armory doesnt work)

**Description**: 
Targets for the quest [Dangerous!](https://www.wowhead.com/quest=567/deprecated-dangerous)  respawn too fast.
[Clerk Horrace Whitesteed](https://www.wowhead.com/npc=2448/clerk-horrace-whitesteed)
[Farmer Kalaba](https://www.wowhead.com/npc=2451/farmer-kalaba)
[Miner Hackett](https://www.wowhead.com/npc=2450/miner-hackett)
[Citizen Wilkes](https://www.wowhead.com/npc=2449/citizen-wilkes)

**Current behaviour**:
All of them respawn quickly. Clerk Horrace Whitesteed respawned excatly 60sec after killing him the first time. Didn't test the other exactly but I had to kill Farmer Kalaba 4-5 times while doing another quest.

**Expected behaviour**:
Comment about Clerk: By Smorfty (6,804 – 2·21·49) on 2008/02/16 (Patch 2.3.3) 
> He has about 5 min respawn time which is longer than usual

Comment about Miner: By Spitti3 (2,825 – 7·33) on 2009/02/13 (Patch 3.0.9)
>It takes about 6 minutes 30 seconds for him to respawn. 

Comment about Citizen: By restopresto (1,682 – 10·12) on 2012/04/29 **(Patch 4.3.4)**
> ...He has a relatively short respawn rate, around 60-90 seconds,...

**Server Revision**: 
2078

**Comment by aresbrutus** [comment]
This is correct. The reason for these fast respawn rates are that we are expecting a huge wave of players so all the named mobs that are needed for a quest have their respawn rate lowered.
