### ISSUE TITLE
Ethereal Thief trash mobs in kara disarm into unequipped weapons

### ISSUE THREAD

**Issue by NeonicSupersonic** [Atlantiss/NetherwingBugtracker#8090]
**Description**: 
Ethereal Thief trash mobs in kara disarm into unequipped weapons

**Current behaviour**:
Ethereal Thief trash mobs in kara disarm into unequipped weapons

**Expected behaviour**: 
Ethereal Thief trash mobs in kara should not use disarm against target without equipped weapon
https://www.wowhead.com/tbc/npc=16544/ethereal-thief#comments comments confirm it

**Server Revision**: 
eb5425213b7e

**Comment by Wolffenstein** [comment]
"Technically in bear and cat you don't hit with a weapon (hence why druids can tank or dps perfectly fine with 1/350 weapon skill) but you can still receive the disarm effect."
The comments say that you can still get the disarm effect
