### ISSUE TITLE
Paladin Chain Pulling ( Reset agrro range with Concecration tick )

### ISSUE THREAD

**Issue by Chunx97** [Atlantiss/NetherwingBugtracker#8091]
[//]: # (Enclose links to things related to the bug using http://wowhead.com or any other TBC database.)
[//]: # (You can use screenshot ingame to visual the issue.)
[//]: # (Write your tickets according to the format:)
[//]: # ([Quest][Azuremyst Isle] Red Snapper - Very Tasty!)
[//]: # ([NPC] Magistrix Erona)
[//]: # ([Spell][Mage] Fireball)
[//]: # ([Npc][Drop] Ghostclaw Lynx)
[//]: # ([Web] Armory doesnt work)
[//]: # (To find server revision type `.server info` command in the game chat.)

**Description**: Concecration tick among other things should reset the range in which a mob should return to its previous location and determine itself not in combat.

**Current behaviour**: Mobs drop threat once they reach their maximum range regardless of still in combat or not.

**Expected behaviour**: Agro range or drop off range should reset if the mob /npc is hit with a certain spell or hit.

**Server Revision**: https://www.youtube.com/watch?v=ncDGBc7zEkY - Skip to 1 minute will give you a basic understanding of what im trying to explain :)

**Comment by duzyizly** [comment]
https://www.youtube.com/watch?v=Mo-nmAe6rfs&ab_channel=eSane

https://www.youtube.com/watch?v=kYeBkX6bC1k&t=50s&ab_channel=Evolve

**Comment by Wolffenstein** [comment]
Fixed in rev 3699.
