### ISSUE TITLE
Some bosses in Karazhan are immune to bleeding effects

### ISSUE THREAD

**Issue by Mahuhn** [Atlantiss/NetherwingBugtracker#8092]
**Description**: 
As of yesterday, alot of bosses (e.g. Midnight, 4 Adds on Moroes (Moroes is NOT immune), Curator, Aran) in Karazhan were immune to bleeding effects (Lacerate & Rip). A various amount of trash mobs (including, but not limited to: Spectral Charger, Spectral Servent, Phantom Guests, Phantom Valets, Ghostly Stewards) were immune to bleeding effects aswell.

**Current behaviour**:
Alot of mobs (bosses & trash) in Karazhan are immune to bleeding effects.

**Expected behaviour**: 
All those mobs should NOT be immune to bleeding effects. 
Source (TBCC): https://www.youtube.com/watch?v=XAIrLaTOob4
Also its nowhere stated in various WoW DB like WoWHead or wowwiki-archive.fandom that those bosses are immune to bleeding effects.

**Server Revision**: 3696

**Comment by Godmatik** [comment]
TBCC not a great source since they didn't replicate 2.0 features. 

I'm fairly sure that undead and mechanical mobs were immune to bleed before patch 2.4, I remember this being a thing on Karazhan server and after Sunwell released they were vulnerable again, but I will let someone else verify.

**Comment by Scuru** [comment]
TBCC was a nerfed state 2.4.3 patch. This realm will be pre-nerf state, so all mechanical, ghosts e.t.c should be immune to bleed type.

**Comment by Raferty** [comment]
About Midnight
[2.0.10](https://wowpedia.fandom.com/wiki/Patch_2.0.10) Midnight is no longer susceptible to Bleed effects, since he's a skeletal horse.
