### ISSUE TITLE
Badge of the Swarmguard proc rate

### ISSUE THREAD

**Issue by Peachusftw** [Atlantiss/NetherwingBugtracker#8096]
**Description**: Badge of the Swarmguard trinket (https://www.wowhead.com/tbc/item=21670/badge-of-the-swarmguard) has abysmally low proc rate of its stacking component (https://www.wowhead.com/tbc/spell=26481/insight-of-the-qiraji). Several sources indicate an 80% proc rate while ,in reality, it's much closer to 5%, which in turn causes trinket to only rarely achieve its full potential at 6 stacks within its 30s duration.

**Current behaviour**: - Explained above -

**Expected behaviour**: - Proc rate should be 80%, which appears in line with severral TBCclassic-era videos: 

https://www.youtube.com/watch?v=5lIaiCuPk9k&ab_channel=Ahlaundoh  - at 0:13 and 2:54, notice an almost instantaneous acquisition of 6 stacks

https://www.youtube.com/watch?v=dCH-_2g6N_0&ab_channel=DaTruthHurtz - 0:18, a bit slower, albeit still noticeably quick acquisition of 6 stacks

**Server Revision**: 3696

**Comment by Wolffenstein** [comment]
Please retry in rev 3697.
