### ISSUE TITLE
Karazhan - Barnes NPC invisible

### ISSUE THREAD

**Issue by Godmatik** [Atlantiss/NetherwingBugtracker#8098]
When Barnes doing his RP opera speech, he is invisible while in the beam of light.

https://www.wowhead.com/tbc/npc=16812/barnes

![WoWScrnShot_022323_164440](https://user-images.githubusercontent.com/37913400/221047824-a81cb87d-f253-4f63-b642-041e9124b1e2.jpg)

**Comment by Wolffenstein** [comment]
uhh that might be a camera client bug, try rotating it and stuff
