### ISSUE TITLE
[Equipment] Wand shoot randomly cancelling itself

### ISSUE THREAD

**Issue by towneh** [Atlantiss/NetherwingBugtracker#81]
**Description**: 
https://i.imgur.com/MWjIlYM.gif

I can kill several mobs without a problem, and then the wand autoshoot will just cancel on a mob that doesnt have an interrupt mechanic, nor walks out of range after the initial shoots.

**Expected behaviour**: 
Wand should auto shoot until otherwise interrupted or the mob dies.

**Server Revision**: 
2020

**Comment by gunnermaniac** [comment]
Also having this issue, not moving anything in my bags.

**Comment by paoea** [comment]
had this after my wand got resisted or missed

**Comment by Wolffenstein** [comment]
Fixed in rev 2044.
