### ISSUE TITLE
[Core][Login][NPC AI] When you log in there are some brief seconds where you are not able to control nor see your character, but can be killed or attacked within this time frame.

### ISSUE THREAD

**Issue by queeb3** [Atlantiss/NetherwingBugtracker#810]
[//]: # (Enclose links to things related to the bug using http://wowhead.com or any other TBC database.)
[//]: # (You can use screenshot ingame to visual the issue.)
[//]: # (Write your tickets according to the format:)
[//]: # ([Quest][Azuremyst Isle] Red Snapper - Very Tasty!)
[//]: # ([NPC] Magistrix Erona)
[//]: # ([Spell][Mage] Fireball)
[//]: # ([Npc][Drop] Ghostclaw Lynx)
[//]: # ([Web] Armory doesnt work)

**Description**: 
I have been logging in after crashes where I'm surrounded by quite the number of enemies, and while I'm loading in, there is usually a brief pause between the loading screen and everything properly rendering in my game. just for instance when logging in today I was still in a mine with a lot of miners my level that started attacking me as soon as my character spawned in; not rendered, spawned in. this is meaning that I am being attacked in a state at which I cannot defend myself or run away.
**Current behaviour**:
death on login if you are surrounded by a few enemies.
**Expected behaviour**: 
brief few seconds where you are not able to be attacked unless you do attack when logging into the game.
**Server Revision**:

**Comment by Wolffenstein** [comment]
Hmm first time I hear of this issue, need confirmation from other players

**Comment by Manaci** [comment]
Dead issue
