### ISSUE TITLE
Nightbane Skeleton adds missing magic immune

### ISSUE THREAD

**Issue by Godmatik** [Atlantiss/NetherwingBugtracker#8101]
Skeleton adds for Nightbane are missing their pre-nerf magic immunity.

In 2.0 (and on Kara realm) they were immune to all magic damage except holy.

https://www.wowhead.com/tbc/npc=17261/restless-skeleton
https://wowpedia.fandom.com/wiki/Nightbane_(tactics)

**Comment by Wolffenstein** [comment]
Fixed in rev 3697.
