### ISSUE TITLE
Hunter's Pet disappears upon mounting

### ISSUE THREAD

**Issue by Gornaut** [Atlantiss/NetherwingBugtracker#8103]
**Description**: 
Since vanilla Hunter's Pet has been following the player while mounted.
Pretty minor yet annoying thing. However, if it doesn't take too much time to fix this, would be highly appreciated.

**Current behaviour**:
Currently any mounting up causing Hunter's pet to disappear whether it is ground mount or flying mount.

**Expected behaviour**: 
Hunter's pet shoud follow the player while mounted, Pet's abilities should be inactive (greyed out) and Pet shouldn't not be responsive to any Player's commands, just blindly following the Hunter.

Pet should disappear only if:
1. Hunter takes off the ground on Flying Mount (pet disappears the moment player takes off the ground into the air).

Here is the video of Pre-TBC Vanilla, where you can see Hunter's Pet Follows player while mounted on ground mount.
https://www.youtube.com/watch?v=G9X71r5ir_4

I failed to find a video of Pet disappearing upon going into the air from OG TBC, but it was definitely the case in Classic and still is in Wrath Classic. 
Here is the proof from Classic TBC (9:34):
https://youtu.be/sb4kxv2RpZ4?t=574

**Server Revision**: 
3697

**Comment by Peglaa** [comment]
Invalid report, this is blizzlike behavior that was introduced in TBC(the real TBC).

**Comment by RichSteini** [comment]
Pets did not disappear in Classic TBC, but either way i think it is not a big deal if they disappear. They appear again when you dismount and you don't want your pet to do anything while mounted anyways.

**Comment by Peglaa** [comment]
Of course, but this server is not trying to recreate Classic TBC. It is trying to recreate the real, original TBC.

**Comment by Gornaut** [comment]
> Of course, but this server is not trying to recreate Classic TBC. It is trying to recreate the real, original TBC.

What are you talking about?
I provided a prove from OG TBC pre Patch where this mechanic exists, take a look before making misleading comments, please:
https://www.youtube.com/watch?v=G9X71r5ir_4

**Comment by Peglaa** [comment]
OK, it seems I need to be more specific with my wording. This server is not trying to replicate TBC pre Patch, Classic TBC etc. This server is trying to replicate the original 2.4.3 TBC experience(when it comes to systems and mechanics, content is pre nerf and patch based).

**Comment by Gornaut** [comment]
> OK, it seems I need to be more specific with my wording. This server is not trying to replicate TBC pre Patch, Classic TBC etc. This server is trying to replicate the original 2.4.3 TBC experience(when it comes to systems and mechanics, content is pre nerf and patch based).

Let me be more specifc then, this is video dating 4-th April of 2007. I remind you that TBC launch date was 16-th of January 2007.
Now watch from 0:54-0:55
https://www.youtube.com/watch?v=fWccctmMMgk
You can see a Hunter running on Raptor Mount with his bear right next to him.
So, this is a OG TBC behavior. If you have any other videos, patch notes or anything really, feel free to provide them, please.



![Screen_Shot](https://user-images.githubusercontent.com/62441921/221204657-e0799c81-a86f-463f-90de-f5be49e03c82.jpg)

**Comment by Scuru** [comment]
https://wowwiki-archive.fandom.com/wiki/Patch_2.1.0
- Warlock and Hunter pets will now be automatically dismissed when you summon a mount. These pets will return on dismount. This does not affect pet happiness for Hunters.

**Comment by Peglaa** [comment]
^ and also this has been heavily discussed among the community over the years, even after TBC ended: https://www.wowhead.com/forums/topic/pets-health-mana-getting-reduced-by-half-on-dismount-75079#p805994

**Comment by Gornaut** [comment]
> https://wowwiki-archive.fandom.com/wiki/Patch_2.1.0
> 
> * Warlock and Hunter pets will now be automatically dismissed when you summon a mount. These pets will return on dismount. This does not affect pet happiness for Hunters.

I agree when it comes to Patch 2.1.0, which you linked.
![image](https://user-images.githubusercontent.com/62441921/221211762-3ae69f29-d487-43c8-b729-0e191dfc8255.png)

But is not PTR in 2.0 state?

**Comment by Peglaa** [comment]
As I said in the previous comment, the server emulates only content when it comes to 2.0 and content progression. Classes, core mechanics and systems are 2.4.3, aside from minor adjustments and custom features like paladin seals for example.

**Comment by Gornaut** [comment]
> As I said in the previous comment, the server emulates only content when it comes to 2.0 and content progression. Classes, core mechanics and systems are 2.4.3, aside from minor adjustments and custom features like paladin seals for example.

Fair enough. 
If this is the case and that is philosophy behind the server, feel free to close this issue.
