### ISSUE TITLE
Lady Vashj - health set at post-nerf value

### ISSUE THREAD

**Issue by Godmatik** [Atlantiss/NetherwingBugtracker#8105]
**Description**: 
Vashj set at wrong health

**Current behaviour**:
Currently set at around 9.2 million, the version of which exists on PTR appears to be after the 500k health nerf done a couple months into Kara server.

**Expected behaviour**: 
Should be 9710000 pre-nerf (or something around that), confirmed with xD who killed it. Please also verify the MCs are not CCable, this was another nerf done some time on Kara (possibly done in patch 2.1 so it might be alright)

![Screenshot_6](https://user-images.githubusercontent.com/37913400/221230621-b9e922cb-c833-4b0a-a411-8b27c1a11549.png)

**Comment by Wolffenstein** [comment]
Fixed in rev 3699.
