### ISSUE TITLE
Extremelly low droprate on Zhevra Hooves

### ISSUE THREAD

**Issue by AWIDIUS** [Atlantiss/NetherwingBugtracker#8106]
**Description**: Extremelly low droprate on Zhevra Hooves

**Current behaviour**: From aproximatelly 30 Zhevra Runners, I've got 2x Zhevra Hooves regarding this quest https://www.wowhead.com/tbc/quest=845/the-zhevra

**Expected behaviour**: Zhevra Hooves have 31% chance of drop, thus would make sense with less luck to have atleast 1 Hooves per 6 Zhevras, yet current state shows drop chance of 6,65%.

**Server Revision**: 3651

**Comment by AWIDIUS** [comment]
Quest completed averaging around 1 Hooves per 10 Zhevras.

**Comment by Wolffenstein** [comment]
Fixed in rev 3699.
