### ISSUE TITLE
[Spell][Hunter] Revive Pet doesn't not ressurect dead pet if his body disappears

### ISSUE THREAD

**Issue by Gornaut** [Atlantiss/NetherwingBugtracker#8107]
**Description**: 
Currently if pet dies once his icon is visible you can simply resurrect him with Revive Pet which is correct. 
However, if you run away from dead pet's body so that it disappears, you can no longer resurrect it until you use Call Pet first and revive pet after. 
Getting "You do not have a pet message"
![image](https://user-images.githubusercontent.com/62441921/221270882-f7751c32-d3d7-40d7-a05d-a953fd5a2038.png)

**Current behaviour**:
Unable to resurect disappeared Pet's Body without using Call Pet first.

**Expected behaviour**: 
Pet should be ressurectable with Revive Pet without prio using of Call Pet.

Here is a video proof of Dysporia reviving his dead pet, after Pet's body disappeared, successfully without using Call Pet first.
From 7:57: https://youtu.be/dXE_RR5XzE8?t=477
It is Vanilla proof. indeed.
However, i looked through all documented and undocumented changes for patches 2.0 - 2.4.3 and this particular mechanic is nowhere to be mentioned as changed or adjusted, correct me if i am wrong here.

**Server Revision**: 
3697

**Comment by Wolffenstein** [comment]
At some point on retail you couldn't do that, you would have to first summon a dead pet and then resurrect but that could be after TBC so not sure which version should be the appropriate one. The patch notes often don't include stuff like this sadly

**Comment by ghost** [comment]
https://youtu.be/_AathhqIuQA?t=53
https://www.wowhead.com/forums/topic/pet-revive-call-macro-help-needed-2190#p24887
https://www.wowinterface.com/forums/showpost.php?p=95026&postcount=8

https://youtu.be/Ki61EujNcg4?t=11
https://youtu.be/TUzJDwbihg4?t=279
https://youtu.be/zFdeYVpuF8k?t=926
https://youtu.be/RaX68ZPFVsA?t=439
https://youtu.be/hFo_LTldrzg?t=228
https://www.youtube.com/live/c5TRRCai_k4?feature=share&t=6397

**Comment by Gornaut** [comment]
> https://youtu.be/Ki61EujNcg4?t=11 https://youtu.be/_AathhqIuQA?t=53 https://www.wowhead.com/forums/topic/pet-revive-call-macro-help-needed-2190#p24887 https://www.wowinterface.com/forums/showpost.php?p=95026&postcount=8 https://youtu.be/hFo_LTldrzg?t=228

Yeah, the pet icon also disappears when cast starts in the first video you linked with a guy soloing SP. 
So, i guess that was recreated properly in classic as well.

**Comment by ghost** [comment]
http://www.wowgold.hk/macros/hunter-macros.htm (2008-9)
> Revive, Call, or Mend Pet
/cast [target=pet, dead] Revive Pet; [modifier:ctrl] Revive Pet; [nopet] Call Pet; Mend Pet
¡¤The modifier key allows you to hold down Control so this macro will ALWAYS cast Revive Pet. This is to make up for situations where your pet is dead, but not visible.

**Comment by ghost** [comment]
https://www.bluetracker.gg/wow/topic/eu-en/2843685948-hunter-macros-united/
Feb. 15, 2008

#showtooltip [nopet,mod][target=pet,dead] Revive Pet; [nopet] Call Pet; [mod] <Pet Food Name>; Mend Pet
/cast [nopet,mod][target=pet,dead] Revive Pet; [nopet] Call Pet; [modifier] Feed Pet; Mend Pet
/use [modifier] <Pet Food Name>

What it does?
1. This macro calls your pet if he's not out.
2. Revives him if he's dead.
3. Heals him during combat.
4. Feeds him out of combat.
Since the macro system can't tell whether your pet is alive if his corpse isn't around, holding any modifier when you have no pet out will cast Revive Pet. Also, holding any modifier key when your pet is out will heal him instead of feeding.

**Comment by ghost** [comment]
https://macros.wowmatrix.com/hunter-macros/pet#revive_call_then_mend_pet
2008

**Revive, Call then Mend Pet**

This macro will revive pet if it's dead, call pet if it's not out or mend pet.

/cast [modifier] Revive Pet; [target=pet,dead] Revive Pet; [nopet] Call Pet; Mend Pet

**Call or Revive Pet**

This macro will revive pet if it's dead by activating it in conjunction with the alt key, call pet if it's not out or dismiss pet when pressed in conjunction with the control key.

/cast [modifier:alt] [target=pet, dead] Revive Pet; [nopet] Call Pet; [pet, nocombat, modifier:ctrl] Dismiss Pet

**Comment by ghost** [comment]
same on AJ https://web.archive.org/web/20080921185232/http://www.arenajunkies.com/macros/hunter/
`#showtooltip [nocombat, pet, target=pet, nodead, nomodifier] Feed Pet
/cast [nopet, modifier] Revive Pet; [target=pet, dead] Revive Pet; [nopet] Call Pet; [combat][modifier] Mend Pet
/stopmacro [combat]
/cast Feed Pet
/use Clefthoof Ribs`

**Comment by ghost** [comment]
https://web.archive.org/web/20080913174032/http://hunterguide.wikispaces.com/Macro's+and+Addons
2. Cast Revive Pet if it's dead otherwise evaluate the next flag and attempt to cast Call Pet or Mend Pet
/cast [target=pet,dead] Revive Pet; [nopet] Call Pet; Mend Pet

_Known Issues: If the pet body doesn't exist it will fail to revive it, however to solve it we can use modifiers, the same approach the version below is using._

3. Reviving your pet by holding down the ctrl modifier with a mouse click combination, otherwise it will either cast Call Pet or Dismiss pet
/cast [modifier:ctrl] Revive Pet; [nopet] Call Pet; Dismiss pet

**Comment by Gornaut** [comment]
> https://web.archive.org/web/20080913174032/http://hunterguide.wikispaces.com/Macro's+and+Addons 2. Cast Revive Pet if it's dead otherwise evaluate the next flag and attempt to cast Call Pet or Mend Pet /cast [target=pet,dead] Revive Pet; [nopet] Call Pet; Mend Pet
> 
> _Known Issues: If the pet body doesn't exist it will fail to revive it, however to solve it we can use modifiers, the same approach the version below is using._
> 
> 3. Reviving your pet by holding down the ctrl modifier with a mouse click combination, otherwise it will either cast Call Pet or Dismiss pet /cast [modifier:ctrl] Revive Pet; [nopet] Call Pet; Dismiss pet

First macro with target looks really weird to me.
It is written so, as if Revive Pet is a Target Spell, while it is not.
Nevertheless, all sources you provided confirms that Revive Pet, works for both 
1. Dead + Summoned Pet
2. Dead + Not summoned
So there is no need to Call Pet.
The reason, those guys discussing and putting Call pet in their macros is to make them universal to replace Feed, Revive, Call with 1 button macro.

**Comment by ghost** [comment]
[Hunter Vs World 6 - Solo Durnholde Heroic](https://www.warcraftmovies.com/movieview.php?id=36806) by dysphoria
5:55 - 6:02
6:36 - 6:46
8:10 - 8:29
https://www.youtube.com/watch?v=jOJefvLb8Ok

**Comment by Gornaut** [comment]
> At some point on retail you couldn't do that, you would have to first summon a dead pet and then resurrect but that could be after TBC so not sure which version should be the appropriate one. The patch notes often don't include stuff like this sadly

Given so many confirmations of Revive Pet working for both states without the need to call for dead body 369N provided. 
I, for one, vote to make it a default mechanic. If it is possible ofc and doesn’t require too much work for you.
Unless there are solid facts that prove otherwise, ofc.

**Comment by ghost** [comment]
If the pet is dead and it's corpse despawns, you can't Call it, you have to Revive. That's why such macros were needed.

**Comment by Wolffenstein** [comment]
Will be changed in revision 3698.

**Comment by Gornaut** [comment]
> Will be changed in revision 3698.

Thank you, wolf!
