### ISSUE TITLE
High Astromancer Solarian - health set at nerfed value

### ISSUE THREAD

**Issue by Godmatik** [Atlantiss/NetherwingBugtracker#8108]
**Description**: 
High Astromancer Solarian tuning

**Current behaviour**:
Health is currently set at 5,159,500

**Expected behaviour**: 
Pre-nerf health should be 5,511,000, - confirmed with xD
There was a 7% health nerf done on rev 3551 on 11/03/20, which is why the health is set lower.
Also the healing done by the "Solarian Priests" were reduced as well to blizzlike numbers on that same date, and probably need to be adjusted back to their pre-nerf healing values.

https://discord.com/channels/284387487730630657/493160436485849098/773247297726709810
https://www.wowhead.com/tbc/npc=18805/high-astromancer-solarian

**Comment by Wolffenstein** [comment]
Fixed in rev 3699.
