### ISSUE TITLE
[NPC] Hillsbrad Fields NPCs

### ISSUE THREAD

**Issue by totaemoeggerli** [Atlantiss/NetherwingBugtracker#811]
[//]: # (Enclose links to things related to the bug using http://wowhead.com or any other TBC database.)
[//]: # (You can use screenshot ingame to visual the issue.)
[//]: # (Write your tickets according to the format:)
[//]: # ([Quest][Azuremyst Isle] Red Snapper - Very Tasty!)
[//]: # ([NPC] Magistrix Erona)
[//]: # ([Spell][Mage] Fireball)
[//]: # ([Npc][Drop] Ghostclaw Lynx)
[//]: # ([Web] Armory doesnt work)

**Description**: 
Multiple NPCs in the Hillsbrad Fields area flee too fast. Some of the same NPC type flee with normal speed and some change their movements speed while fleeing. Wowhead links:
[Hillsbrad Farmer](https://www.wowhead.com/npc=2266/hillsbrad-farmer)
[Hillsbrad Farmhand](https://www.wowhead.com/npc=2360/hillsbrad-farmhand)
[Hillsbrad Footman](https://www.wowhead.com/npc=2268/hillsbrad-footman)
[Hillsbrad Miner](https://www.wowhead.com/npc=2269/hillsbrad-miner)

**Current behaviour**:
[Hillsbrad Farmer](https://gfycat.com/CornyWhoppingBlacklemur)
[Hillsbrad Farmhand](https://gfycat.com/JollyFantasticKakapo)
[Hillsbrad Footman](https://gfycat.com/AlarmingUnrealisticCrownofthornsstarfish) changes movement speed while fleeing
[Hillsbrad Miner](https://gfycat.com/DisloyalDefiantDassie)

**Expected behaviour**:
NPC should flee with moderate movement speed.

**Server Revision**: 
2078

**Comment by DarthNekr0s** [comment]
https://streamable.com/w3ufs
i have footage of a farmer fleeing to another group in 0.2 sec from the other day on another ticket, relevant to this

**Comment by Easyfraggy** [comment]
There are different types of "fleeing" one is running away in fear, one is running for help. Running for help is not slowed.

**Comment by Kidcudi123** [comment]
Also Dun Garok npcs run for help but should run for away in fear

**Comment by totaemoeggerli** [comment]
clip from [Dun Garok Mountaineer](https://www.wowhead.com/npc=2344/dun-garok-mountaineer) [slow](https://gfycat.com/DamagedMeaslyIndigobunting) [fast](https://gfycat.com/GrandNiceFattaileddunnart) 
weird that this is inconsistent
Priests/Rifleman/Captain act the same way

**Comment by Tereneckla** [comment]
Fixed
