### ISSUE TITLE
[Quest] 10248 You, Robot

### ISSUE THREAD

**Issue by duzyizly** [Atlantiss/NetherwingBugtracker#8111]
**Description**: 
Looks like You don't get score once Negatron is dead.
Quest can not be completed.

**Server Revision**: 
3697

![image](https://user-images.githubusercontent.com/43931626/221377087-e75b7611-b18c-4edb-baec-8cbea31ec6ac.png)

**Comment by Wolffenstein** [comment]
Looks like you're in a raid group

**Comment by duzyizly** [comment]
whoops : )
