### ISSUE TITLE
World Boss respawn timer

### ISSUE THREAD

**Issue by Godmatik** [Atlantiss/NetherwingBugtracker#8113]
**Description**: 
Respawn timer for TBC world bosses (Doomwalker and Doom Lord Kazzak)

**Current behaviour**:
Respawn timer is around 8 days or so currently for TBC world bosses.

**Expected behaviour**: 
The current respawn timer set is too long. TBC world bosses follow the same formula as Vanilla world bosses in classic, I think something similar or a fair approximation would be ideal for the fresh TBC server

The exact respawn windows follow this logic on classic:

1. After server does weekly restart on Wednesdays - there is a 12 hour period where no world bosses are spawned. Once that passes, a 24 hour window occurs where they are guarenteed to spawn before it is up.
2. Once defeated - a world boss will be unable to spawn for 72 hours.
3. Once that time is up, there will be a 48 hour window during which the boss can spawn again.
4. Once defeated - Repeat step 2. If Wednesday reset occurs (usually happens before boss can spawn a 3rd time in a week), go to step 1
(Also if there happened to be a full server crash or shutdown mid-week, not a restart, the respawn windows would go back to step 1)

While the above steps are perhaps a bit convoluted and it may not be ideal to follow the exact classic formula, I still suggest lowering the world boss respawn timers from what they currently are set at.

**Comment by Wolffenstein** [comment]
Can't replicate retail system because we don't have scheduled weekly maintances, so I reducedit  from 7-9d to 3-5d in rev 3699.
