### ISSUE TITLE
[Spell][Paladin]Seal of Righteousness/Seal of Blood + startattack macro deals no damage

### ISSUE THREAD

**Issue by Spartanv** [Atlantiss/NetherwingBugtracker#8116]
[//]: # (Enclose links to things related to the bug using http://wowhead.com or any other TBC database.)
[//]: # (You can use screenshot ingame to visual the issue.)
[//]: # (Write your tickets according to the format:)
[//]: # ([Quest][Azuremyst Isle] Red Snapper - Very Tasty!)
[//]: # ([NPC] Magistrix Erona)
[//]: # ([Spell][Mage] Fireball)
[//]: # ([Npc][Drop] Ghostclaw Lynx)
[//]: # ([Web] Armory doesnt work)
[//]: # (To find server revision type `.server info` command in the game chat.)

**Description**: 
Assuming that player is not buffed with any damaging seal, "macro 1" and "macro 2" result in melee swing without (righteous, blood) seal damage

macro 1:
/cast Seal of Righteousness
/startattack

macro 2:
/cast Seal of Blood
/startattack

**Current behaviour**:
Melee swing without (righteous, blood) seal damage
Combat log:
![image](https://user-images.githubusercontent.com/11991518/221409480-a4a8e260-4294-4e16-8d38-4ad7e706dc38.png)
![image](https://user-images.githubusercontent.com/11991518/221409701-04e1884a-a328-40f5-a5d4-95aa60614a36.png)

**Expected behaviour**: 
Melee swing with (righteous, blood) seal damage
![image](https://user-images.githubusercontent.com/11991518/221409590-ce3b8ab7-a3db-4f97-84d6-2092c2e39fbc.png)
![image](https://user-images.githubusercontent.com/11991518/221409745-e281e762-d2c8-4ea9-a620-8734ea1d8075.png)

**Server Revision**: 
3697

**Comment by duzyizly** [comment]
Actually this happens with every seal so far, might be just a delay/sanitizer issue.

**Comment by Wolffenstein** [comment]
It's due to spell delay, I made a workaround in rev 3699.
