### ISSUE TITLE
Araj's Phylactery Shard

### ISSUE THREAD

**Issue by Carneyy** [Atlantiss/NetherwingBugtracker#8118]
[//]: # (Enclose links to things related to the bug using http://wowhead.com or any other TBC database.)
[//]: # (You can use screenshot ingame to visual the issue.)
[//]: # (Write your tickets according to the format:)
[//]: # ([Quest][Azuremyst Isle] Red Snapper - Very Tasty!)
[//]: # ([NPC] Magistrix Erona)
[//]: # ([Spell][Mage] Fireball)
[//]: # ([Npc][Drop] Ghostclaw Lynx)
[//]: # ([Web] Armory doesnt work)
[//]: # (To find server revision type `.server info` command in the game chat.)

**Description**: 
After we killed https://www.wowhead.com/tbc/npc=1852/araj-the-summoner there is q item https://www.wowhead.com/tbc/npc=1852/araj-the-summoner that can pick up only 1 person.
**Current behaviour**:
https://www.wowhead.com/tbc/quest=105/alas-andorhal
https://www.wowhead.com/tbc/npc=1852/araj-the-summoner
https://www.wowhead.com/tbc/item=17114/arajs-phylactery-shard

Only 1 person can take q item: Araj's Phylactery Shard
**Expected behaviour**: 
Entire party can take q item: Araj's Phylactery Shard
**Server Revision**:

**Comment by Wolffenstein** [comment]
Fixed in rev 3699.
