### ISSUE TITLE
[Dungeon] Shadowfang keep mobs going wild

### ISSUE THREAD

**Issue by DarthNekr0s** [Atlantiss/NetherwingBugtracker#812]
**Description**: two rogues, level 25, 1 warrior level 18, pally level 19, priest lvl 21 running sfk tonight. upon entering courtyard, mobs Wailing Guardsman from upper level targetted onto the warrior - did not run down and pull anything with them but had him in combat. we wiped one pull later so not sure if they would have stuck us in combat rest of the run or not, but they should not be able to detect anything in their range when not on the same floor as them.
upon entering room with Lupine Horror's, the mobs from the stairs above entrance detected warrior and pulled entire room to us. This happened 3 times in total with the mobs pulling onto the priest last time, when she was on the first staircase in that room. Gm Smaily was with us in the dungeon so witnessed it happening except for the first time I believe.

**Current behaviour**: mobs are detecting players that are on different levels to what their patrol is and aggroing 

**Expected behaviour**:  should only be in aggro range of mobs when you are on the same level as them.

**Server Revision**:  2078

**Comment by The14me** [comment]
Confirm about pull part.Maybe related to low war level and bigger Wolf's aggro range.
Possible crash when Arugal MC some player. 3 of 3 time's server crash at this fight(At the end i kill him)

**Comment by Jezofine** [comment]
I was under Arugal's MC once full duration, didn't crash that time.

**Comment by The14me** [comment]
Was Wolf related problem fixed long time a go.If happen again please Re-open.
