### ISSUE TITLE
Plagued Murloc Spine

### ISSUE THREAD

**Issue by Godmatik** [Atlantiss/NetherwingBugtracker#8122]
**Description**: 
Plagued Murloc Spine quest item for "The Plagued Coast"

**Current behaviour**:
Pretty low drop rate, perhaps 20% or so, maybe just terrible RNG but please verify.

**Expected behaviour**: 
40% drop rate

https://www.wowhead.com/tbc/item=22579/plagued-murloc-spine#dropped-by
https://www.wowhead.com/tbc/quest=9149/the-plagued-coast

**Comment by Wolffenstein** [comment]
It has 40% already
