### ISSUE TITLE
Open world mobs keep resetting after getting hit

### ISSUE THREAD

**Issue by Mahuhn** [Atlantiss/NetherwingBugtracker#8123]
**Description**: 
If you hit mobs in the open world they instantly reset, drop combat and regenerate to full health. This behavior doesnt occure in dungeons.

**Current behaviour**:
Open world mobs keep resetting

**Expected behaviour**: 
They shouldn't reset

**Server Revision**: 
3699

**Comment by Godmatik** [comment]
appears fixed now

**Comment by Mahuhn** [comment]
Yes, can confirm its fixed now
