### ISSUE TITLE
Blackwing Lair Boss : Razorgone the Untamed endless adds spawn

### ISSUE THREAD

**Issue by vertria** [Atlantiss/NetherwingBugtracker#8124]
https://www.wowhead.com/tbc/npc=12416/blackwing-legionnaire https://www.wowhead.com/tbc/npc=12420/blackwing-mage https://www.wowhead.com/tbc/npc=12422/death-talon-dragonspawn have unlimited spawns.
should have limited numbers https://wowpedia.fandom.com/wiki/Razorgore_the_Untamed 
In Phase 2, adds spawn in the rooms corners until 40 orcs ([Blackwing Legionnaires](https://wowpedia.fandom.com/wiki/Blackwing_Legionnaire) and/or [Blackwing Mages](https://wowpedia.fandom.com/wiki/Blackwing_Mage) combined) and 12 [Death Talon Dragonspawn](https://wowpedia.fandom.com/wiki/Death_Talon_Dragonspawn) are present.

**Comment by Wolffenstein** [comment]
Fixed in rev 3700.
