### ISSUE TITLE
quest missed :The Dread Citadel - Naxxramas

### ISSUE THREAD

**Issue by vertria** [Atlantiss/NetherwingBugtracker#8127]
npc has no all of the following versions of quests: https://www.wowhead.com/tbc/quest=9121/the-dread-citadel-naxxramas https://www.wowhead.com/tbc/quest=9122/the-dread-citadel-naxxramas https://www.wowhead.com/tbc/quest=9123/the-dread-citadel-naxxramas

**Comment by Godmatik** [comment]
Confirmed - unable to enter Naxx as a result.

QoL suggestion - remove Naxx attunement requirement.

**Comment by NeonicSupersonic** [comment]
Bump, was wondering if it by design or not. Can it be fixed b4 the end of PTR?

**Comment by Godmatik** [comment]
Bump
