### ISSUE TITLE
Fire/Earth Elemental Totem

### ISSUE THREAD

**Issue by Godmatik** [Atlantiss/NetherwingBugtracker#8128]
**Description**: 
Leash range of Fire/Earth Elemental Totems

**Current behaviour**:
Currently they have no leash range or is very far

**Expected behaviour**: 
50 yard leash range

![Leash](https://user-images.githubusercontent.com/37913400/221918807-b7ab7144-7b4a-4aa8-ba1f-2fa31cab690b.png)

https://wowwiki-archive.fandom.com/wiki/Earth_Elemental_Totem

**Comment by Wolffenstein** [comment]
Fixed in rev 3700.
