### ISSUE TITLE
Guild bank money log not showing repair amount

### ISSUE THREAD

**Issue by DarthNekr0s** [Atlantiss/NetherwingBugtracker#813]
**Description**:  money log tab on gbank is only showing repairs selectively

**Current behaviour**: sometimes does not show the amount used

**Expected behaviour**: should show at all times

**Server Revision**:  2078

![untitled](https://user-images.githubusercontent.com/16113944/46209699-dcec6200-c371-11e8-9931-9023aae4ab66.png)

**Comment by Wolffenstein** [comment]
Fixed in rev 2080.
