### ISSUE TITLE
Spell Queue System is not implemented

### ISSUE THREAD

**Issue by Gornaut** [Atlantiss/NetherwingBugtracker#8130]
**Description**: 
One of the OG tbc blizzlike mechanics that was previously implemeted for all previous revs of this project. 
Not only it is a unique interaction, it also makes the whole gameplay feels smoother.

**Current behaviour**:
Currently the spell queue system is not implemented.

**Expected behaviour**: 
One of Original Netherwing Advertisement videos shows this as a unique feature which it actually is:
https://www.youtube.com/watch?v=FXFjvsD7VI4

It is also implemeted on current Karazhan Server - Rev 3651.

It was the OG TBC mechanic (proves in the same link above) and also a thing in Classic TBC.

**Server Revision**: 
3699

**Comment by Wolffenstein** [comment]
It's literally the same code, it works but might be laggy due to sanitizer
