### ISSUE TITLE
[NPC] Jandice Barov - Curse of Blood

### ISSUE THREAD

**Issue by MecAtlantiss** [Atlantiss/NetherwingBugtracker#8131]
**Description**: The boss Jandice Barov in Scholomance is casting an incorrect version of Curse of Blood that causes the victim to take 500 increased physical damage rather than 92 increased physical damage. My only proof it should be 92 is this [wiki page on a January 2008 historical version.](https://wowwiki-archive.fandom.com/wiki/Jandice_Barov?oldid=1101795).

Please see this clip taken on PTR: https://clips.twitch.tv/SleepyPhilanthropicSkirretTinyFace-_xfdUKO_9RfX3ft4

In the clip, I take 10,266 damage from adds for the 22 second window where adds and spawn and I'm not yet dead. That's 466 damage taken per second just from the adds on a level 70 feral druid in the PTR's feral druid and that's with demoralizing roar up. I would've taken approximately 660 damage per second if I didn't demoralizing roar.

**Current behaviour**: Jandice Barov's Curse of Blood causes victim to take 500 increased physical damage. 

**Expected behaviour**: Jandice Barov's Cures of Blood causes victim to take 92 increased physical damage.

**Server Revision**: 3699

**Comment by Wolffenstein** [comment]
Fixed in rev 3700.
