### ISSUE TITLE
[QUEST] Identifying the Brood drop rate

### ISSUE THREAD

**Issue by duzyizly** [Atlantiss/NetherwingBugtracker#8133]
**Description**: 
Quest=1169 Identifying the Brood

Drop rate seems very low (like vanilla values).
Due to comments this quest get revamped in late TBC (like 2.3 mudsprocket patch) and drop rate increased.

https://www.wowhead.com/tbc/quest=1169/identifying-the-brood#comments

**Comment by Godmatik** [comment]
The amount required for each quest item was reduced from 15 to 7 in patch 2.3 with the Dustwallow zone revamp - but just briefly reading through the wowhead comments post patch 2.3 it doesn't seem like the drop rate was changed (check screenshot)

But probably should verify they are set at 33%

https://www.wowhead.com/tbc/item=5841/searing-heart
https://www.wowhead.com/tbc/item=5840/searing-tongue

![drops](https://user-images.githubusercontent.com/37913400/221988687-2e533db4-c2ab-4498-a263-2331a4c6a97f.png)

**Comment by duzyizly** [comment]
Just a reminder that during TBC You were still able to play 1.12 servers on vanilla client (becasue you get 1 free month vanilla play if you bought latest esxpansion) and the "patch number" on thottbot-wowhead prints of date.

![image](https://user-images.githubusercontent.com/43931626/222098348-2ac6454b-dee5-4620-a27a-af3b7b22d386.png)
![image](https://user-images.githubusercontent.com/43931626/222098635-7ca76892-5207-4034-8813-6b4cebfb26ff.png)
![image](https://user-images.githubusercontent.com/43931626/222098986-d1700d00-a111-476e-afbe-cb817e32c7de.png)

**Comment by duzyizly** [comment]
Rev 3071.
