### ISSUE TITLE
Nightbane - Distracting Ash (2.0)

### ISSUE THREAD

**Issue by Godmatik** [Atlantiss/NetherwingBugtracker#8134]
**Description**: 
Nightbane's ability "Distracting Ash" - the 2.0 version that is applied to characters as a debuff during the fight.

**Current behaviour**:
The 2.0 version currently of "Distracting Ash" doesn't appear to function at all - so can be ignored and not dispelled as intended.

**Expected behaviour**: 
It should do as the tooltip states:
"Reduces the range of spells and abilities by 50%."

**Server Revision**: 
3700

It's one of these two IDs I think
https://www.wowhead.com/tbc/spell=30130/distracting-ash
https://www.wowhead.com/tbc/spell=30280/distracting-ash

**Comment by vertria** [comment]
it will be ignored anyway lul

**Comment by Godmatik** [comment]
> it will be ignored anyway lul

Wolf has quite a number of bugs this past week, so not sure why you say that?

**Comment by Godmatik** [comment]
> it will be ignored anyway lul

Maybe so, but still a bug regardless

**Comment by Wolffenstein** [comment]
Fixed in rev 3702.
