### ISSUE TITLE
ROGUE: Sub Talent "Master of Subtlety" - Vanish/Prep Vanish Bug (No dmg increase + bugged stealth)

### ISSUE THREAD

**Issue by yuoyuoki** [Atlantiss/NetherwingBugtracker#8135]
https://www.wowhead.com/tbc/spell=31223/master-of-subtlety#comments
(https://cdn.discordapp.com/attachments/1068821561622155315/1080451419766804570/image.png)
[Master of Subtlety][Rogue] Stealth/Vanish/Preparation(Vanish)
https://www.wowhead.com/tbc/spell=31223/master-of-subtlety#comments
Vanish/Vanish(Preparation) don't apply the damage increase or the 6 seconds of persisted damage increase after breaking stealth.
Using Vanish puts you in stealth and should increase your dmg by 10% and persist after coming out of stealth for 6 seconds.
Atlantiss realm | Content patch : 2.0.3 | Revision: 3699 
Stormforge: Netherwing TBC PTR

**Comment by Wolffenstein** [comment]
Fixed in rev 3702.
