### ISSUE TITLE
Gnomish Battle Chicken's Squawk ability

### ISSUE THREAD

**Issue by Peachusftw** [Atlantiss/NetherwingBugtracker#8137]
**Description**: 
Many thanks to you guys for fixing the chicken, although a single issue still persists.

**Current behaviour**:
[NPC] Gnomish Battle Chicken [https://www.wowhead.com/tbc/item=10725/gnomish-battle-chicken] uses the ability [Spell] Battle Squawk [https://www.wowhead.com/tbc/spell=23060/battle-squawk], Squawks from multiple Chicken don't stack.

**Expected behaviour**: 
Squawks across multiple players' chicken should stack as is evident in numerous TBC classic videos. Notice the buff frame in top-right corner, multiple instances of Battle Squawk are visible: (https://www.youtube.com/watch?v=wOaMjpfnKas&t=4s&ab_channel=Soulstar)
Attempted to replicate said video by having two people summon their chicken. Squawks overwrote one another.

**Server Revision**: 
3701

**Comment by Wolffenstein** [comment]
Fixed in rev 3702.

**Comment by EtheriousNW** [comment]
still not stacking in 3702

**Comment by Wolffenstein** [comment]
Fixed in rev 3706.
