### ISSUE TITLE
[ITEM] Neck Buffs disappear when shifting

### ISSUE THREAD

**Issue by Godmatik** [Atlantiss/NetherwingBugtracker#8138]
**Description**: 
Buffs given by jewelcrafting necklaces

**Current behaviour**:
Shifting in and out of Moonkin form as a druid will remove a JC neck buff from yourself. Possibly occurs with shifting into other forms as well, was only able to confirm as Moonkin. 

**Expected behaviour**: 
Once used - the JC neck buffs should stay active unless time expires, you die, or the person who wears the necklace unequips it.

**Server Revision**: 
3701

Here are the necks:

https://www.wowhead.com/item=24116/eye-of-the-night
https://www.wowhead.com/item=24121/chain-of-the-twilight-owl
https://www.wowhead.com/item=24117/embrace-of-the-dawn

**Comment by Peglaa** [comment]
https://github.com/Atlantiss/NetherwingBugtracker/issues/7929
https://github.com/Atlantiss/NetherwingBugtracker/issues/5942
https://github.com/Atlantiss/NetherwingBugtracker/issues/1949

**Comment by Wolffenstein** [comment]
Fixed in rev 3702.
