### ISSUE TITLE
City of Light

### ISSUE THREAD

**Issue by ghost** [Atlantiss/NetherwingBugtracker#8139]

**Comment by Godmatik** [comment]
Confirmed - it worked this way on TBC classic as well.

Basically the follower Khadgar's Servant appears to despawn when you are far enough away - but it shouldn't.

**Comment by Peglaa** [comment]
This is a core issue then, as this happens with all NPCs if you walk far enough away from them. Same can be observed with escort quests for obvious reasons. I don't know why this NPC in particular doesn't follow this same pattern, could be an exception to the rule mybe or the distance for which this happens for all NPCs on the server is a bit low?

**Comment by Godmatik** [comment]
Perhaps it's a different kind of guardian/escort NPC or something, but I have no idea.

The same is true with quest
https://www.wowhead.com/tbc/quest=10277/the-caverns-of-time

The NPC who 'guides' you despawns if you get too far away here - but on classic you could sit and AFK at the quest giver's spot and wait until he finishes his circle 10 mins later.

**Comment by Peglaa** [comment]
With this logic you could afk escort quests which makes no sense. The only explanation is that these NPCs are exceptions to the rule in which case we gotta find all of them.

**Comment by Peglaa** [comment]
And it would be prudent to make sure these NPCs despawn properly if the player drops the quest and accepts it again, to prevent spamming hundreds into existence.

**Comment by Wolffenstein** [comment]
Fixed in rev 3702.
