### ISSUE TITLE
[Quest][Coldridge Valley] Scalding Mornbrew Delivery

### ISSUE THREAD

**Issue by Moistowelette** [Atlantiss/NetherwingBugtracker#814]
[//]: # (Enclose links to things related to the bug using http://wowhead.com or any other TBC database.)
[//]: # (You can use screenshot ingame to visual the issue.)
[//]: # (Write your tickets according to the format:)
[//]: # ([Quest][Azuremyst Isle] Red Snapper - Very Tasty!)
[//]: # ([NPC] Magistrix Erona)
[//]: # ([Spell][Mage] Fireball)
[//]: # ([Npc][Drop] Ghostclaw Lynx)
[//]: # ([Web] Armory doesnt work)

**Description**: 
In the dwarf/gnome starting area, NPC [Nori Pridestalker] gives the quest for [Scalding Mornbrew Delivery], which has a follow up quest.
https://wow.gamepedia.com/Scalding_Mornbrew_Delivery_(quest)
**Current behaviour**:
When you take the quest a timer starts (5 mins) in which you need to deliver  [Durnan's Scalding Mornbrew] to [Durnan furcutter], when you fail the quest it dissapears and can't be started again from [Nori Pridestalker]. 
**Expected behaviour**: 
When the questtimer runs out and the quest ultimately fails it should be reset after which you should be eligible to pick it up again and start the quest again

**Server Revision**: 
2078

**Comment by Easyfraggy** [comment]
Global issue with timed quests, when they fail, you cannot abandon and pick them up again.

**Comment by Wolffenstein** [comment]
Fixed in rev 2138.
