### ISSUE TITLE
[Quest] Rotting Hearts - Low Drop Rate

### ISSUE THREAD

**Issue by reetarded** [Atlantiss/NetherwingBugtracker#8142]
Killed around 13 and received 2 drops.

https://www.wowhead.com/tbc/quest=9216/rotting-hearts

**Comment by Godmatik** [comment]
Because they are not classified as "quest items", they are probably exempt from the new progressive quest system.

Same as https://github.com/Atlantiss/NetherwingBugtracker/issues/8141

**Comment by reetarded** [comment]
Oh weird don't think I've ever seen an item that has no use other than quest and it be a white item. Maybe wolf can work his magic to let it be group drop shared and buff the drop rate still.

**Comment by Wolffenstein** [comment]
Only pure quest items can have progressive loot and have shared party drops, that's intended.

**Comment by reetarded** [comment]
Well in any case the drop rate is too low compared to wowhead values. You could convert them into actual quest items and there wouldn't really be any harm if you wanted.

**Comment by Wolffenstein** [comment]
Fixed in rev 3702.
