### ISSUE TITLE
[Spell][Troll] Berserking

### ISSUE THREAD

**Issue by mercy-byte** [Atlantiss/NetherwingBugtracker#8143]
[//]: # (Enclose links to things related to the bug using http://wowhead.com or any other TBC database.)
[//]: # (You can use screenshot ingame to visual the issue.)
[//]: # (Write your tickets according to the format:)
[//]: # ([Quest][Azuremyst Isle] Red Snapper - Very Tasty!)
[//]: # ([NPC] Magistrix Erona)
[//]: # ([Spell][Mage] Fireball)
[//]: # ([Npc][Drop] Ghostclaw Lynx)
[//]: # ([Web] Armory doesnt work)
[//]: # (To find server revision type `.server info` command in the game chat.)

**Description**: Berserking Troll Racial not working properly, while being unbuffed and having max health with a 2.6 attack speed, i should always get 2.36 weapon speed after using Berserking.

**Current behaviour**:  Berserking is giving random haste buff going from 10 to 30% at max health and 10 to 45% at low health.

**Expected behaviour**: Scaling from 10% to 30% according to the user %hp missing from 100% to 40% HP

**Server Revision**: [2273][Core] Beta fixes

![WoWScrnShot_030323_150035](https://user-images.githubusercontent.com/38768676/222746620-02e7fd1f-3de8-4958-8e05-bcacdccd0b83.jpg)
![WoWScrnShot_030323_150436](https://user-images.githubusercontent.com/38768676/222746675-eb04a94d-2258-436a-8d13-e674e8f122da.jpg)
![WoWScrnShot_030323_150446](https://user-images.githubusercontent.com/38768676/222746737-365d3a6e-76e6-4f94-bd86-b4f14d1877fe.jpg)
![WoWScrnShot_030323_150507](https://user-images.githubusercontent.com/38768676/222746813-91a36afb-24cd-4b7f-965e-c3d2defbb609.jpg)
![WoWScrnShot_030323_150518](https://user-images.githubusercontent.com/38768676/222746879-67669183-b435-4493-92a3-177247cb80e8.jpg)

**Comment by Wolffenstein** [comment]
Works as intended
