### ISSUE TITLE
[NPC] Short John Mithril

### ISSUE THREAD

**Issue by Godmatik** [Atlantiss/NetherwingBugtracker#8145]
**Description**: 
Two issues with Short John Mithril for Gurubashi Arena in STV

**Current behaviour**:
1. Does wrong script when /yelling his arena announcement, see below screenshot
2. The time he is setting down the chest is incorrect

**Expected behaviour**: 
1. Should instead say:
"Arrr, Me Hearties! I be havin' some extra Treasure that i be givin' away at the Gurubashi Arena! All ye need to do is collect it is open the chest I leave on the arena floor!"
2. The chest appears to be dropped 1 hour earlier than normal, for example it's dropped at 17:00 server time when it should be 18:00. Perhaps incorrect due to daylight savings?

**Server Revision**: 
3701

https://www.wowhead.com/tbc/npc=14508/short-john-mithril#comments

![Short John](https://user-images.githubusercontent.com/37913400/222916256-2dfb82c1-c0a8-46ad-b8a1-3fe384ce053c.png)

**Comment by Massie323** [comment]
To add to this; The line he is using right now comes from the NPC "Lorax" and is part of that NPC's dialogue used in the quest "Lorax's Tale [5126]":

> Player: "My apologies, I did not realize that you could understand what I was saying. What is it you are doing out here?"

> Lorax: "What it is that I do, of course. I brood. I lament. I hate, I plot. When that cycle is complete I brood again. What is it you want from me? I have much on my mind."

https://www.wowhead.com/tbc/quest=5126/loraxs-tale

**Comment by Wolffenstein** [comment]
Fixed in rev 3719.
