### ISSUE TITLE
Firework Launcher - incorrect usage of Herbalism

### ISSUE THREAD

**Issue by aplouding** [Atlantiss/NetherwingBugtracker#8146]
![image](https://user-images.githubusercontent.com/76868410/222915815-1c649e8a-05a4-4cc4-a4c5-596c94a535bb.png)
Firework Launcher
https://www.wowhead.com/classic/item=21569/firework-launcher

**Description**: 
Firework launcher needs to use small or big red rockets. Instead it does not work as intended.
**Current behaviour**:
Rightclicking on Firework Launcher changes cursor to herbalism and requires Herbalism to use. Rightclicking on Small Red Rocket in your inventory within melee range of Firework Launcher shows "Requires Firework Launcher" message.
**Expected behaviour**: 
You can use Small or Big Rockets from your inventory to shoot them into the sky.
**Server Revision**: 
3701

**Comment by duzyizly** [comment]
![image](https://user-images.githubusercontent.com/43931626/222931899-645dce7f-0da0-4334-8840-e09b2394866e.png)

**Comment by Wolffenstein** [comment]
Fixed in rev 3830.
