### ISSUE TITLE
[NPC] Innkeepr Delaniel

### ISSUE THREAD

**Issue by Godmatik** [Atlantiss/NetherwingBugtracker#8147]
**Description**: 
Innkeeper Delaniel in starting Blood Elf zone

**Current behaviour**:
Does not sell anything, will only make Falconwing Square your home

**Expected behaviour**: 
Should sell water/food. It's a bit odd since this vendor sells things properly on Kara server.

**Server Revision**: 
3701

https://www.wowhead.com/tbc/npc=15433/innkeeper-delaniel

**Comment by Peglaa** [comment]
Isn't this one of those patch based NPCs? She should start selling in a later patch, I don't recall which one tho. I also don't know if that is something Wolf wants to bind to a patch? I don't see why this random innkeeper should conform to such things, its a pretty minor thing.

**Comment by Godmatik** [comment]
Probably correct, will close for now
