### ISSUE TITLE
Explosive sheep bugs all engineering consumables, relog needed

### ISSUE THREAD

**Issue by aplouding** [Atlantiss/NetherwingBugtracker#8149]
![image](https://user-images.githubusercontent.com/76868410/222936474-6f86cb7a-eb39-473a-b498-70f58baeed9c.png)
Engineering: 150

**Description**: 
Explosive Sheep bugs inventory and attacks like a pet.
**Current behaviour**:
Once created and gets into combat Explosive Sheep attacks with orange numbers. Never explodes. Never despawns. Also once Explosive Sheep is summoned, Engineer needs to relog because all of his engineering consumables (apart from Advanced Target Dummy) are now unusable until then.
Server clears of bugged sheep once player enters instance. All consumables are available to use again from that point.
**Expected behaviour**: 
Once created and gets into combat Explosive Sheep should be exploding once in melee range with enemies or despawning in 3 mins.
https://www.wowhead.com/tbc/item=4384/explosive-sheep

**Server Revision**: 
3701

**Comment by Wolffenstein** [comment]
Fixed in rev 3837.
