### ISSUE TITLE
[Spell] Disarm

### ISSUE THREAD

**Issue by Firroth** [Atlantiss/NetherwingBugtracker#815]
[Spell] Disarm

**Current behaviour**:
![screenshot_1](https://user-images.githubusercontent.com/43505196/46209556-72fe9900-c32e-11e8-8a19-e35f9392f0c4.png)

As you can see on this screenshot my crit chance is 13.40%, after I get disarmed it drops to 8.76% (unarmed skill) - works like it should, except the fact that WHEN disarm duration ends and my normal weapon comes back, my crit chance doesn't go up back to 13.40%, it stays on (unarmed) one 8.76% until i remove my weapon and equip it again to get back to my 13.40%.

Here is a screenshot showing I have no longer disarm effect on me, my entire eq+wep equiped but crit is much lower.
![screenshot_2](https://user-images.githubusercontent.com/43505196/46209731-f28c6800-c32e-11e8-8fab-53125947086e.png)

**Expected behaviour**: 
After disarm ends critical strike chance should go back to normal, not stay on "unarmed skill" one.

**Server Revision**: 
2078

**Comment by Pennywise4569** [comment]
Removing and putting my weapon back on doesn't reset my crit back to it's normal value, I have to relog. Noticed this after being disarmed by Grimtotems in Thousand Needles.

**Comment by Azalen** [comment]
I'd say this could be considered a critical bug. Good catch!

**Comment by Wolffenstein** [comment]
Fixed in rev 2080.
