### ISSUE TITLE
Compact Harvester Reaper

### ISSUE THREAD

**Issue by aplouding** [Atlantiss/NetherwingBugtracker#8150]
[//]: # (Enclose links to things related to the bug using http://wowhead.com or any other TBC database.)
[//]: # (You can use screenshot ingame to visual the issue.)
[//]: # (Write your tickets according to the format:)
Engineering: Compact Harvest Reaper Kit 175 skill

**Description**: 
Compact Harvester Reaper is not attacking enemies. Probably does not have proper AI.

**Current behaviour**:
Compact Harvester Reaper moves to attack only after player attacks, not when player is in combat. Also once Compact Harvester Reaper reaches enemy, it just stands there and never attacks. Also it does not despawn after 10 mins.

**Expected behaviour**: 
Compact Harvester Reaper should attack all enemies within his aggro range and if player gets into mobs aggro range Compact Harvester Reaper should go and attack the mob. It should also despawn after 10 mins.

**Server Revision**: 
3701

**Comment by aplouding** [comment]
update: 
*Description*
Despawning too fast

*Current behaviour:*
now the compact harvester properly approaches enemy and attacks enemy. However once the combat is over, it despawns even if it is within few seconds of an ended fight.

*Server revision:*
3711

**Comment by Wolffenstein** [comment]
Fixed in rev 3837.
