### ISSUE TITLE
Lightning overload

### ISSUE THREAD

**Issue by Redburn-AdamParr** [Atlantiss/NetherwingBugtracker#8151]
[//]: # (Enclose links to things related to the bug using http://wowhead.com or any other TBC database.)
[//]: # (You can use screenshot ingame to visual the issue.)
[//]: # (Write your tickets according to the format:)
[//]: # ([Quest][Azuremyst Isle] Red Snapper - Very Tasty!)
[//]: # ([NPC] Magistrix Erona)
[//]: # ([Spell][Mage] Fireball)
[//]: # ([Npc][Drop] Ghostclaw Lynx)
[//]: # ([Web] Armory doesnt work)
[//]: # (To find server revision type `.server info` command in the game chat.)

**Description**: 
Lightning overload should proc on the initial target but can proc of 1st or 2nd bounce when using chain lightning
**Current behaviour**:
Procs randomly on any of the three targets hit by chain lightning
**Expected behaviour**: 
Should proc on initial target
**Server Revision**:

**Comment by tsu-1** [comment]
From https://github.com/Atlantiss/NetherwingBugtracker/issues/2007 reply https://github.com/Atlantiss/NetherwingBugtracker/issues/2007#issuecomment-450528312

I think previous thread was closed by mistake. **The research people done stated that LO can't proc from LO which I think is correct.** When using Chain Lightning, LO can't proc from LO but have a chance to proc from targets affected by Chain Lightning ~~only once per Chain Lightning.~~.

~~Meaning, when our CL affects 3 targets, each of the target have a chance to roll for a LO proc, but only one proc should go out.~~ Meaning, each target affected by Chain Lighting have a separate chance to proc LO **but LO can't proc from LO!**

EDIT: Further verified with Classic TBC Shaman discord discussions.

**Comment by tsu-1** [comment]
Thanks to Dionizodors (from Discord) as he found the following thread:
https://us.forums.blizzard.com/en/wow/t/with-somechanges-in-mind-maybe-fix-chain-lightning-in-classic-tbc/1206585/23

**Comment by ghost** [comment]
https://github.com/Aeded/BCC_Buglist/issues/88

**Comment by taigaqt** [comment]
*pyong*

**Comment by Hevymode** [comment]
This should be changed to flat 20% chance to proc LO on spell cast if possible. It never made sense and people from blizzard who ive been talking to agreed to change this, they just never delivered as with other promises.

**Comment by Aeded** [comment]
This should be changed to flat 20% chance to proc LO on spell cast if possible. It never made sense and people from blizzard who ive been talking to agreed to change this, they just never delivered as with other promises.

**Comment by ghost** [comment]
Never made sense why?

**Comment by Aeded** [comment]
> Never made sense why?

Because single target CL has only 6.6% to proc LO, which is flat out nerf for pvp and vast majority of pve. You trade being very minisculy better for heroic cleaving for being worse at everything else.
Thats why they wanted to change this, because you are expecting to have 20% chance to proc LO as tooltip says, not this weird thing

**Comment by ghost** [comment]
The spell is clearly meant to be used against multiple targets. If it does more single target damage than single target spells, that's a different problem.

**Comment by Godmatik** [comment]
Fixed in upcoming spell proc rework branch
