### ISSUE TITLE
[Item][Balebrew Charm] maiden not serving beers

### ISSUE THREAD

**Issue by aplouding** [Atlantiss/NetherwingBugtracker#8152]
**Description**: 
Dissapointment.
**Current behaviour**:
Using trinket spawns Black Brewmaiden as expected. Once character waves at her he does not get any Brew (https://www.wowhead.com/tbc/spell=48249/brewfest-brew-toss) into his inventory. Brewmaiden was waving back I believe but I cannot find proof of that.
**Expected behaviour**: 
Use: [Right Click to summon the Black Brewmaiden, who will smite your foes with your empty tankards. Wave at her for Brewfest Brew!](https://www.wowhead.com/tbc/spell=48042/summon-the-black-brewmaiden)
Also Brewmaiden should be levitating in holy light as shown in this yt video and holding tankards. https://www.youtube.com/watch?v=h50LQLmOC0k
I also expect her to have more than 84hp - I was not able to get any hp number anywhere. She also should use spell "Bitter Brew" https://www.wowhead.com/tbc/spell=48208/bitter-brew) while fighting.

**Server Revision**: 
3701

**Comment by Godmatik** [comment]
I am fairly certain Brewfest was not scripted on Atlantiss

**Comment by aplouding** [comment]
Is it planned to be scripted?

**Comment by Godmatik** [comment]
Closing for now, will reopen if/when Wolf decides to script this Holiday
