### ISSUE TITLE
A Mysterious Tome

### ISSUE THREAD

**Issue by Carneyy** [Atlantiss/NetherwingBugtracker#8153]
[//]: # (Enclose links to things related to the bug using http://wowhead.com or any other TBC database.)
[//]: # (You can use screenshot ingame to visual the issue.)
[//]: # (Write your tickets according to the format:)
[//]: # ([Quest][Azuremyst Isle] Red Snapper - Very Tasty!)
[//]: # ([NPC] Magistrix Erona)
[//]: # ([Spell][Mage] Fireball)
[//]: # ([Npc][Drop] Ghostclaw Lynx)
[//]: # ([Web] Armory doesnt work)
[//]: # (To find server revision type `.server info` command in the game chat.)

**Description**: 
https://www.wowhead.com/tbc/item=28552/a-mysterious-tome
**Current behaviour**:
Drops for 1 person in group
**Expected behaviour**: 
All party members can loot it from the same mob drop.
**Server Revision**:

**Comment by Wolffenstein** [comment]
Will not be changed.
