### ISSUE TITLE
Zeth'Gor Must Burn!

### ISSUE THREAD

**Issue by Carneyy** [Atlantiss/NetherwingBugtracker#8154]
[//]: # (Enclose links to things related to the bug using http://wowhead.com or any other TBC database.)
[//]: # (You can use screenshot ingame to visual the issue.)
[//]: # (Write your tickets according to the format:)
[//]: # ([Quest][Azuremyst Isle] Red Snapper - Very Tasty!)
[//]: # ([NPC] Magistrix Erona)
[//]: # ([Spell][Mage] Fireball)
[//]: # ([Npc][Drop] Ghostclaw Lynx)
[//]: # ([Web] Armory doesnt work)
[//]: # (To find server revision type `.server info` command in the game chat.)

**Description**: 
https://www.wowhead.com/tbc/quest=10792/zethgor-must-burn
**Current behaviour**:
Torch doesn't give credit for all party members.
**Expected behaviour**: 
Torch give credit for all party members (if you want to promote party leveling)
**Server Revision**:

**Comment by Wolffenstein** [comment]
Will not be changed.
