### ISSUE TITLE
[Warrior] Sword Specialization

### ISSUE THREAD

**Issue by ghost** [Atlantiss/NetherwingBugtracker#8155]
**Description**: Extra attacks gained through Sword Specialization are not working properly.

**Current behaviour**: Despite queueing Next Swing Ability (Heroic Strike/Cleave) extra attacks do not benefit from them.

**Expected behaviour**: Extra attacks should act as a normal auto-attack therefore using Next Swing Abilities (Heroic Strike/Cleave) on hit.
[Sword Specialization]: The change to Sword Specialization making its extra attacks appear in yellow has been reverted. Extra attacks will appear in white and act like any auto-attack. They will no longer reset the swing time of your weapon. Rage awarded will be calculated by damage dealt as with any normal auto-attack.
https://wowwiki-archive.fandom.com/wiki/Patch_2.1.2#Warriors
**Server Revision**:3702

**Comment by ghost** [comment]
![11141122141121](https://user-images.githubusercontent.com/84371650/223196404-ac1831ad-e51e-41c3-9cb8-3a0360a5dc47.PNG)

**Comment by tsu-1** [comment]
https://github.com/Atlantiss/NetherwingBugtracker/issues/8084 Related.

Guy from the linked video in that issue says exactly about it: https://www.youtube.com/watch?v=DgVlDAZ1a2c&ab_channel=Konter

**Comment by Wolffenstein** [comment]
Fixed in rev 3705.
