### ISSUE TITLE
Resto Shaman Earth Shield

### ISSUE THREAD

**Issue by bpain711** [Atlantiss/NetherwingBugtracker#8157]
[//]: # (Enclose links to things related to the bug using http://wowhead.com or any other TBC database.)
[//]: # (You can use screenshot ingame to visual the issue.)
[//]: # (Write your tickets according to the format:)
[//]: # ([Quest][Azuremyst Isle] Red Snapper - Very Tasty!)
[//]: # ([NPC] Magistrix Erona)
[//]: # ([Spell][Mage] Fireball)
[//]: # ([Npc][Drop] Ghostclaw Lynx)
[//]: # ([Web] Armory doesnt work)
[//]: # (To find server revision type `.server info` command in the game chat.)

**Description**: 
Restoration Shaman earth shield stack internal cooldown
**Current behaviour**:
While doing dungeons, it appeared that there was no cooldown on the earth shield stack reduction with my tank going from 6 stacks to 1 or 0 in the initial hits from the mobs.
**Expected behaviour**: 
There is typically an internal cooldown on the heal/stack reduction. I am unsure if it is supposed to be a 2 or 3 second ICD. But multiple stacks, let alone nearly all of the stacks, should not all be munched at the same time and should only be one stack at a time.
**Server Revision**:

**Comment by Wolffenstein** [comment]
Fixed
