### ISSUE TITLE
[Spell] Mana Tap

### ISSUE THREAD

**Issue by Godmatik** [Atlantiss/NetherwingBugtracker#8158]
**Description**: 
Mana tap (blood elf racial)

**Current behaviour**:
Aura gained when using mana tap now shows as a debuff - still appears to function properly.

**Expected behaviour**: 
Should show as a buff

**Server Revision**: 
3702

https://www.wowhead.com/tbc/spell=28734/mana-tap

**Comment by Wolffenstein** [comment]
Fixed
