### ISSUE TITLE
[Core] The UnitBuff() function is failing under certain circumstances

### ISSUE THREAD

**Issue by MecAtlantiss** [Atlantiss/NetherwingBugtracker#8159]
**Description**: 

The player's client is unable to determine time of expiration from the UnitBuff() api function if the player logs out and back into the game. In other words, it appears the expiration time of certain buffs is not able to be known by the client unless the buff was applied in the current session of playing.

To recreate this on PTR, first use Elixir of the Sages (item id 13447). Then run this script:

```
for i = 1,40 do
    local name, _, _, _, _, expirationTime = UnitBuff("player", i)
    if name ~= nil and name == "Elixir of the Sages" then
        if expirationTime == nil then
            DEFAULT_CHAT_FRAME:AddMessage("nil")
        else
            DEFAULT_CHAT_FRAME:AddMessage(expirationTime)
        end
    end
end
```

It will correctly return the expiration time of the buff.

Now log out and back in. Run the script again. It will return `nil`.

I confirmed that this problem existed even after disabling all addons.

**Current behaviour**: UnitBuff() fails to return expiration time of certain buffs that existed on the unit at time of log-in.

**Expected behaviour**: UnitBuff() should return expiration time of buffs regardless of when they were applied.

**Server Revision**: 3702

**Comment by Godmatik** [comment]
Fixed in next update.
