### ISSUE TITLE
[Quest][NPC][Loot][Professions][Cooking] In Soothing Turtle Bisque! you are meant to kill the snapjaws in the river, but the drop chance on the meat they drop is really low.

### ISSUE THREAD

**Issue by queeb3** [Atlantiss/NetherwingBugtracker#816]
[//]: # (Enclose links to things related to the bug using http://wowhead.com or any other TBC database.)
[//]: # (You can use screenshot ingame to visual the issue.)
[//]: # (Write your tickets according to the format:)
[//]: # ([Quest][Azuremyst Isle] Red Snapper - Very Tasty!)
[//]: # ([NPC] Magistrix Erona)
[//]: # ([Spell][Mage] Fireball)
[//]: # ([Npc][Drop] Ghostclaw Lynx)
[//]: # ([Web] Armory doesnt work)

**Images**:
https://imgur.com/a/KrXMAKm
**Description**: 
I killed the entire length of the river from ocean to plaguelands and ended up with only 9 turtle meat, not to mention this item is not only a quest item it turns into a cooking ingredient.
**Current behaviour**:
9 turtle out of the entire river with like 30 turtles spanning the stream.
**Expected behaviour**: 
at least 15 out of 30 should have been got.
**Server Revision**: 
increase drop chance just slightly as it was now i still got 9 to drop, but that is still really low for a cooking ingredient not only a quest item.

**Comment by The14me** [comment]
Duplicate https://github.com/Atlantiss/NetherwingBugtracker/issues/720
