### ISSUE TITLE
[KARA] Nightbane Restless Skeletons missing Immolation Aura (2.0)

### ISSUE THREAD

**Issue by Godmatik** [Atlantiss/NetherwingBugtracker#8160]
**Description**: 
Nightbane restless skeleton adds

**Current behaviour**:
They do not use Immolation Aura (2.0) ability, making the fight much easier than intended.
They are also immune to slowing effects (such as frost trap)

**Expected behaviour**: 
Should use Immolation Aura - a 2.0 only ability.
They also shouldn't be immune to slowing effects - at least they weren't on last server, see below video. Perhaps making them magic immune also made them slow immune in error?

**Server Revision**: 
3702

https://www.wowhead.com/tbc/npc=17261/restless-skeleton
https://www.wowhead.com/tbc/spell=37059/immolation

https://www.bilibili.com/video/BV17a4y1L7PR/

**Comment by Wolffenstein** [comment]
Well you can't be both immune to magic and slowable by magic effects, it's either or

**Comment by Godmatik** [comment]
Well - guess the pally will just have to tank them straight up then and not kite *shrug*

**Comment by Wolffenstein** [comment]
Immo aura fixed
