### ISSUE TITLE
[KARA] Big Bad Wolf

### ISSUE THREAD

**Issue by Godmatik** [Atlantiss/NetherwingBugtracker#8161]
**Description**: 
Big Bad Wolf encounter in Karazhan

**Current behaviour**:
Big Bad Wolf does not chase the target afflicted with "Red Riding Hood" - he stays aggroed on the tank

**Expected behaviour**: 
Should chase the person who receives the Red Riding Hood debuff

**Server Revision**: 
3702

https://www.wowhead.com/tbc/npc=17521/the-big-bad-wolf#abilities;mode:n10
https://www.wowhead.com/tbc/spell=30753/red-riding-hood

**Comment by Wolffenstein** [comment]
Fixed
