### ISSUE TITLE
[KARA] Curator Loot

### ISSUE THREAD

**Issue by Godmatik** [Atlantiss/NetherwingBugtracker#8162]
**Current behaviour**:
Curator drops 2 tier pieces and 2 pieces of loot

**Expected behaviour**: 
Should only be 1 tier and 1 piece of loot. Rest of Kara bosses drop the appropriate amount of loot, so I guess just this one was missed

**Server Revision**: 
3702

**Comment by Wolffenstein** [comment]
Fixed in rev 3705.
