### ISSUE TITLE
[AURA] mind control on players breaking randomly after some seconds

### ISSUE THREAD

**Issue by ghost** [Atlantiss/NetherwingBugtracker#8164]
**Description**: 
I duelled on two clients, undead rogue vs undead priest and cast mind control on the rogue. After channeling for some seconds the effect randomly ends for no apparent reason. To reproduce just duel and cast mind control.
**Current behaviour**:
mind control breaks randomly after x seconds of channeling
**Expected behaviour**: 
mind control should not randomly break by itself and instead last for the full channel duration
**Server Revision**: 
AtlantissCore2 rev. ec733d4287a2 (auras_2023 branch)

**Comment by ghost** [comment]
[Heartbeat resist](https://www.wowhead.com/tbc/spell=10912/mind-control#Flags:~:text=Stops%20auto%2Dattack-,Heartbeat%20Resist,-Dismiss%20Pet%20First)
If you steer the target 30+ yd away it will break 100%

**Comment by ghost** [comment]
heartbeat resist is not in the game so it is most likely related to the recent aura rework

**Comment by Godmatik** [comment]
I'm pretty sure heartbeat resist is present, I have seen CCs break early.

**Comment by ghost** [comment]
pve or pvp? i casted 50 entangling roots on a target(enemy player in pvp) with nature resistance gear equipped and had 0 break early

**Comment by Godmatik** [comment]
PvE - can't speak for PvP

**Comment by ghost** [comment]
this bug report is of course related to pvp, if this was a pve test it would have been stated in my initial bug report

**Comment by Godmatik** [comment]
Obviously - I just initially assumed heartbeat resist was present on both.

**Comment by ghost** [comment]
"Heartbeat resists are present in Burning Crusade Classic and were present throughout all of the original Burning Crusade."
[Blind breaking early in arena](https://streamable.com/49y3op)
[Blind breaking early in arena 2](https://www.youtube.com/watch?v=PQAIxsnp9DE)
[Blind breaking early in arena 3](https://www.youtube.com/watch?v=BMg-1Kgz-CA)

**Comment by Wolffenstein** [comment]
Heartbeat resist and/or distance from the caster, intended
