### ISSUE TITLE
Blood Elf Bandit - not in game

### ISSUE THREAD

**Issue by Carneyy** [Atlantiss/NetherwingBugtracker#8165]
[//]: # (Enclose links to things related to the bug using http://wowhead.com or any other TBC database.)
[//]: # (You can use screenshot ingame to visual the issue.)
[//]: # (Write your tickets according to the format:)
[//]: # ([Quest][Azuremyst Isle] Red Snapper - Very Tasty!)
[//]: # ([NPC] Magistrix Erona)
[//]: # ([Spell][Mage] Fireball)
[//]: # ([Npc][Drop] Ghostclaw Lynx)
[//]: # ([Web] Armory doesnt work)
[//]: # (To find server revision type `.server info` command in the game chat.)

**Description**: 
https://www.wowhead.com/tbc/npc=17591/blood-elf-bandit#map
**Current behaviour**:
Blood Elf Bandit - not in game
**Expected behaviour**: 
Stealthing Blood Elf Bandit in correct locations from link
**Server Revision**:

**Comment by Wolffenstein** [comment]
They are pooled and have random spawns
