### ISSUE TITLE
[DB/Druid] incorrect Nature's Grace proc

### ISSUE THREAD

**Issue by Onsty** [Atlantiss/NetherwingBugtracker#8166]
**Description**: [I've reported this one like a month ago](https://github.com/Atlantiss/NetherwingBugtracker/issues/8039#issue-1551790788), and seems like you've removed wrong proc

<img width="403" alt="image" src="https://user-images.githubusercontent.com/44346265/223504473-204142dd-3627-45a9-bae2-98bd4596d836.png">

The one that proc on-cast — **correct**
The one that proc on-hit — **incorrect**

Now on PTR it procs on-hit

**Current behaviour**: on-hit proc

**Expected behaviour**: on-cast proc

**Server Revision**: 3702

**Comment by Wolffenstein** [comment]
oops

**Comment by Wolffenstein** [comment]
Please retry in rev. 3703.

**Comment by Onsty** [comment]
@Wolffenstein still procs on-hit in 3703

https://user-images.githubusercontent.com/44346265/223661216-caad1f3f-426d-4257-87ab-0b8b4f01d6a0.mp4

**Comment by Godmatik** [comment]
Fixed with upcoming spell proc branch update
