### ISSUE TITLE
Totem of Wrath is not adding spell hit rating

### ISSUE THREAD

**Issue by ForStateSake** [Atlantiss/NetherwingBugtracker#8167]
[//]: # (Enclose links to things related to the bug using http://wowhead.com or any other TBC database.)
[//]: # (You can use screenshot ingame to visual the issue.)
[//]: # (Write your tickets according to the format:)
[//]: # ([Quest][Azuremyst Isle] Red Snapper - Very Tasty!)
[//]: # ([NPC] Magistrix Erona)
[//]: # ([Spell][Mage] Fireball)
[//]: # ([Npc][Drop] Ghostclaw Lynx)
[//]: # ([Web] Armory doesnt work)
[//]: # (To find server revision type `.server info` command in the game chat.)

**Description**: 
1000 Scorch performed with a level 70 Mage, with no equip, no talents and only a Totem of Wrath (flat 3% spell hit rating). The target was a level 70 target dummy (expected 4% miss rate with 0% spell hit, 1% with 3% spell hit).

**Current behaviour**:
Output from Recount:
Recount - Hostile Attacks
Scorch 1001 60547 (100%)
Recount - Hostile Attacks: Scorch
Hit 899 (90%) (Min: 56 Avg: 62 Max: 68)
Crit 54 (5.4%) (Min: 84 Avg: 93 Max: 102)
Resist 48 (4.8%) ( Avg: 0)

**Expected behaviour**: 
Resist rate around 1%.

**Server Revision**: 
Atlantiss Atlantiss realm | Content patch: 2.0.3 | Revision: 3702

<img width="1504" alt="Screenshot 2023-03-07 alle 23 28 47" src="https://user-images.githubusercontent.com/11272777/223569896-8f194006-7075-473a-8217-9cd2bb05b45b.png">

**Comment by Wolffenstein** [comment]
Fixed
