### ISSUE TITLE
Warlock fear bugged AF in pvp

### ISSUE THREAD

**Issue by budgebudge** [Atlantiss/NetherwingBugtracker#8168]
[//]: # (Enclose links to things related to the bug using http://wowhead.com or any other TBC database.)
[//]: # (You can use screenshot ingame to visual the issue.)
[//]: # (Write your tickets according to the format:)
[//]: # ([Quest][Azuremyst Isle] Red Snapper - Very Tasty!)
[//]: # ([NPC] Magistrix Erona)
[//]: # ([Spell][Mage] Fireball)
[//]: # ([Npc][Drop] Ghostclaw Lynx)
[//]: # ([Web] Armory doesnt work)
[//]: # (To find server revision type `.server info` command in the game chat.)

**Description**: 
Warlock fear in PVP is 9 secs and the 2nd one is 3 seconds. its totally wrong. should be 10 - then 6 or so - then 4 or so

**Current behaviour**:

**Expected behaviour**: 

**Server Revision**:

**Comment by Godmatik** [comment]
#4678
An open thread with a lot more data than presented here regarding fear and it potentially being weaker than intended.

**Comment by Wolffenstein** [comment]
2nd one is supposed to be 5s not 6s. Also the initial duration is properly set to 10s, hovering over will display 9s because the timer (in milliseconds) already started by the time your client received the duration update. Either way DR fixed
