### ISSUE TITLE
[Warrior Quest] Essence of the Exile

### ISSUE THREAD

**Issue by Azalen** [Atlantiss/NetherwingBugtracker#817]
**Description**: 
https://classicdb.ch/?quest=1714
https://web.archive.org/web/20071102164143/http://wow.allakhazam.com:80/db/quest.html?wquest=1714

**Current behaviour**:
Droprates for the Essences are too low. Especially Thundering Charm seems way off (lower than 20% atm), Burning Charm could be okay, Cresting Charm a bit low.

**Expected behaviour**: 
[Thundering Charm should have 45% drop chance](https://web.archive.org/web/20071027091922/http://wow.allakhazam.com:80/db/mob.html?wmob=2762)
[Burning Charm should have 38% drop chance](https://web.archive.org/web/20071026061727/http://wow.allakhazam.com:80/db/mob.html?wmob=2760)
[Cresting Charm should have 38% drop chance](https://web.archive.org/web/20071226221703/http://wow.allakhazam.com:80/db/mob.html?wmob=2761)

**Server Revision**: 
[2078]

**Comment by aresbrutus** [comment]
This will be fixed in one of the next updates.
