### ISSUE TITLE
Diminishing Returns Bug 2nd and 3rd Cast

### ISSUE THREAD

**Issue by yuoyuoki** [Atlantiss/NetherwingBugtracker#8170]
Diminishing Returns Bug, 1st cast works, 2nd Cast is Short and 3rd cast doesn't exist.

**Comment by Godmatik** [comment]
Which.spells? Need to provide more info

**Comment by budgebudge** [comment]
i think every spell? roots, clone, fear, etc

**Comment by Godmatik** [comment]
Should be the following:

https://www.reddit.com/r/wowservers/comments/6iyogm/comment/djajjvw/

**Comment by ghost** [comment]
i do not think it is that complicated. the server is lagging really hard and every button you press is super delayed. cast a fear on someone and you will notice the debuff applies 1-2 seconds after finishing the cast so i would assume it is not an issue on the server release

**Comment by budgebudge** [comment]
it is definitely bugged as of now. first cast is 10 seconds and the 2nd one is like 3 seconds. its 100% wrong. 
talking fear here. same concept applies to other cc spells

**Comment by Wolffenstein** [comment]
Fixed
