### ISSUE TITLE
Stealth range bugged

### ISSUE THREAD

**Issue by budgebudge** [Atlantiss/NetherwingBugtracker#8171]
[//]: # (Enclose links to things related to the bug using http://wowhead.com or any other TBC database.)
[//]: # (You can use screenshot ingame to visual the issue.)
[//]: # (Write your tickets according to the format:)
[//]: # ([Quest][Azuremyst Isle] Red Snapper - Very Tasty!)
[//]: # ([NPC] Magistrix Erona)
[//]: # ([Spell][Mage] Fireball)
[//]: # ([Npc][Drop] Ghostclaw Lynx)
[//]: # ([Web] Armory doesnt work)
[//]: # (To find server revision type `.server info` command in the game chat.)

**Description**: 
stealthed targets (lvl 70 feral druid, same level) can not be seen by a warlock with paranoia unless he is in very very close distance). this means that paranoia is redundant. stealthed targets will always get their opener even if blatantly walking into a lock with paranoia.

almost no difference to non-paranoia use!
**Current behaviour**:

**Expected behaviour**: 

**Server Revision**:

**Comment by budgebudge** [comment]
almost no difference to non- paranoia use

**Comment by Godmatik** [comment]
I believe the stealth formula is an approximation since at the time it was calculated there was no classic to reference, so if you have proof or videos of what it is that would be helpful for Wolf.

**Comment by Godmatik** [comment]
It's also possible paranoia is just straight up bugged after the aura rework

**Comment by budgebudge** [comment]
No Paranoia, Rogue comes straight into my face: (see both pictures for the difference when he can be seen or he cant be seen)
https://media.discordapp.net/attachments/642753348503863312/1083047044937175090/image.png?width=1241&height=700
https://media.discordapp.net/attachments/642753348503863312/1083047195659468852/image.png?width=1246&height=700

With Paranoia, rogue comes straight into my face: (see both pictures for the difference when he can be seen or he cant be seen)
https://media.discordapp.net/attachments/642753348503863312/1083047847336869898/image.png?width=1243&height=700
https://media.discordapp.net/attachments/642753348503863312/1083047961170280598/image.png?width=1250&height=700

Keep in mind it was all standing still, if any of us moved there is 0 reaction time, even with paranoia.

we tried in duels and i spammed a macro to unstealth him, even when not even trying to come from the side/behind, he just ran frontally into me, i had no chance of unstealthing him. this means that any rogue can approach even warlocks with paranoia from any angle without getting punished. 

seems like stealth is just straight up too strong. check the difference between 1st and 2nd picture without paranoia. its crazy close and he doesnt even try to approach from the side/behind. just blatantly frontal.

**Comment by Wolffenstein** [comment]
Continents also have less frequent stealth updates, for best results test in arenas/bgs.
