### ISSUE TITLE
[Tempest Keep] Solarian - Wrath of the Astromancer

### ISSUE THREAD

**Issue by Godmatik** [Atlantiss/NetherwingBugtracker#8172]
**Description**: 
Solarian Wrath of the Astromancer debuff - we discussed this a bit already but figured it would be easier if I just made a bug report/suggestion post here

**Current behaviour**:
1. Wrath of the Astromancer debuff from Solarian will not affect those who have Divine Intervention buff or Flask of Petrification buff - even though it already goes through immunities such as Divine Shield. This makes the fight significantly easier than intended.
2. Players targetted with Wrath of the Astromancer can dodge it completely by using Feign Death, Vanish, or casting Divine Intervention on someone else (pally suiciding themselves) - while potentially blizzlike, this also reduces fight difficulty and turns it into more of an RNG encounter.

**Expected behaviour**: 
1. Wrath of the Astromancer should affect individuals regardless of what immunity status on them, including petri flask and divine intervention buff
2. SUGGESTION - consider Solarian recasting Wrath of the Astromancer immediately if the original intended target drops combat (feign death, etc)

EDIT: Having it be instant cast honestly would solve all these issues, even if its not blizzlike

**Server Revision**: 
3702

**Comment by Wolffenstein** [comment]
To be fair I like players using their abilities to work around encounter mechanics, I think that's pretty cool. I'll maybe patch 1) and leave 2) alone

**Comment by Godmatik** [comment]
Sounds fair to me, I think the Petri flask and DIs are for sure the biggest issue. If left alone an entire raid will flask every cast and make the fight a joke.

**Comment by Wolffenstein** [comment]
Please test in rev 3705.
