### ISSUE TITLE
Windfury totem + dualwielding interaction

### ISSUE THREAD

**Issue by Peachusftw** [Atlantiss/NetherwingBugtracker#8173]
**Description**: 
Windfury Totem should replicate a melee swing with an increased Attack power value given by the totems rank.

**Current behaviour**:
For whatever reason, Windfury attacks caused by WF totem procs deal less damage than their mainhand swing counterparts, more in line with offhand swings (which are unrelated to WF totem procs, as they only affect main hand slots.

Please understand that average damage of melee attacks is calculated across all melee attacks, with offhands dealing about half as much damage, meaning the real value of average mainhand damage in recount is about halfway between displayed average and displayed maximum. 
Notice the difference between melee damage ranges and windfury totem proc damage ranges in these recount segments

https://i.imgur.com/vsqq9X0.png

I believe this has something to do with dual talent specs. Ive been encountering this issue on and off during this PTR. It doesnt necessarily happen all the time but it certainly happens more often than not.

**Expected behaviour**: 
WF totem swings should be dealing higher damage than melee swings

**Server Revision**: 
3703

**Comment by Godmatik** [comment]
Rev 4015 - Confirmed.

What is happening is that the AP bonus is not applied onto the extra attack when windfury totem procs, rather the AP is carried over into the next melee attack. 

So the extra AP is not entirely lost, it is just not being placed properly into the correct attack.

**Comment by Godmatik** [comment]
TODO: Check again after weapon proc rework is released

**Comment by Godmatik** [comment]
Fixed in upcoming weapon proc rework branch
