### ISSUE TITLE
Dual Spec button vanishes after reload UI

### ISSUE THREAD

**Issue by Foodlenz** [Atlantiss/NetherwingBugtracker#8176]
Basically the title here.

The right click menu option is not there after using **/rl** to reload your UI when changing addons etc.

![image](https://user-images.githubusercontent.com/72258441/223926588-f042543d-390b-4a8b-a93d-28746055858d.png)

Relogging puts it back as an option.
![image](https://user-images.githubusercontent.com/72258441/223926711-13f54b6f-79a9-4e41-94ab-c0cae1d65f71.png)

**Comment by Wolffenstein** [comment]
I don't think I can do anything about it, you can always use .dualspec command if you don't want to relog
