### ISSUE TITLE
Dual Spec Macros

### ISSUE THREAD

**Issue by Savageferret** [Atlantiss/NetherwingBugtracker#8177]
[//]: # (Enclose links to things related to the bug using http://wowhead.com or any other TBC database.)
[//]: # (You can use screenshot ingame to visual the issue.)
[//]: # (Write your tickets according to the format:)
[//]: # ([Quest][Azuremyst Isle] Red Snapper - Very Tasty!)
[//]: # ([NPC] Magistrix Erona)
[//]: # ([Spell][Mage] Fireball)
[//]: # ([Npc][Drop] Ghostclaw Lynx)
[//]: # ([Web] Armory doesnt work)
[//]: # (To find server revision type `.server info` command in the game chat.)

**Description**: 
When a macro's name contains a space, it's removed from the action bars when switching specs. To reproduce, create a macro named "healing touch" and place it into an action bar. Switch specs, then switch specs again. The macro will removed from the action bar, and this message will appear in chat
![image](https://user-images.githubusercontent.com/127389763/223969443-4333e708-780f-46c9-b2b9-71a1eb5d9860.png)
Renaming the macro to "healingtouch" remedies the issue

**Current behaviour**:
Switching specs is sensitive to macro name

**Expected behaviour**: 
Swapping spec works with all macro names

**Server Revision**:  3703

**Comment by Wolffenstein** [comment]
Fixed in rev 3704.
