### ISSUE TITLE
The Grimtotem Weapon

### ISSUE THREAD

**Issue by Carneyy** [Atlantiss/NetherwingBugtracker#8178]
[//]: # (Enclose links to things related to the bug using http://wowhead.com or any other TBC database.)
[//]: # (You can use screenshot ingame to visual the issue.)
[//]: # (Write your tickets according to the format:)
[//]: # ([Quest][Azuremyst Isle] Red Snapper - Very Tasty!)
[//]: # ([NPC] Magistrix Erona)
[//]: # ([Spell][Mage] Fireball)
[//]: # ([Npc][Drop] Ghostclaw Lynx)
[//]: # ([Web] Armory doesnt work)
[//]: # (To find server revision type `.server info` command in the game chat.)

**Description**: 
https://www.wowhead.com/tbc/quest=11169/the-grimtotem-weapon
**Current behaviour**:
not counting for group
**Expected behaviour**: 
group credits for kills
**Server Revision**:

**Comment by Wolffenstein** [comment]
Fixed in rev 3705.
