### ISSUE TITLE
Brilliant Wizard Oil not stacking with Firestone. (Gamebreaking fire warlock bug)

### ISSUE THREAD

**Issue by Soujin1337** [Atlantiss/NetherwingBugtracker#8180]
[//]: # (Enclose links to things related to the bug using http://wowhead.com or any other TBC database.)
[//]: # (You can use screenshot ingame to visual the issue.)
[//]: # (Write your tickets according to the format:)
[//]: # ([Quest][Azuremyst Isle] Red Snapper - Very Tasty!)
[//]: # ([NPC] Magistrix Erona)
[//]: # ([Spell][Mage] Fireball)
[//]: # ([Npc][Drop] Ghostclaw Lynx)
[//]: # ([Web] Armory doesnt work)
[//]: # (To find server revision type `.server info` command in the game chat.)

![image](https://user-images.githubusercontent.com/127469471/224227516-d66bbf77-88ef-4850-a8b4-18ad35927117.png)

Blizzlike videos for proof:

https://www.youtube.com/watch?v=OCSHaq8XbkU

https://www.youtube.com/watch?v=ek7QRMamf1Y

https://www.youtube.com/watch?v=sdrHyMOhcOU

https://www.youtube.com/watch?v=cea8CQRVTcw

Logic proof: Master Firestone removes your wand slot and gives you 30 fire damage. It would make no sense to wear a Firestone which is what you do in Classic if it's removing your 36 spell damage + 14 critical chance oil.

**Description**: 
When putting on a wizard oil on your weapon, whether you  were wearing a Master Firestone in your Wand slot (bis for fire warlocks) or if you put it on afterwards, the firestone's "melee fire damage" portion will overwrite the wizard oil. Resulting in around a 45 DPS loss which makes the spec not viable. Not blizzlike.
**Current behaviour**:
Wizard Oil gets overwritten by Master Firestone passive melee damage portion.
**Expected behaviour**: 
Wizard Oil should not be overwritten.
**Server Revision**:

**Comment by ghost** [comment]
None of your videos show both Firestone and Brilliant Wizard Oil active.
Also:
![firestone](https://user-images.githubusercontent.com/84371650/224533942-65cb4d8d-3aff-4ac3-9e50-5033c1f75653.PNG)
![firestone2](https://user-images.githubusercontent.com/84371650/224534200-28c1c41e-b195-4e73-8233-9450a435cac7.PNG)

**Comment by Soujin1337** [comment]
> None of your videos show both Firestone and Brilliant Wizard Oil active. Also: ![firestone](https://user-images.githubusercontent.com/84371650/224533942-65cb4d8d-3aff-4ac3-9e50-5033c1f75653.PNG) ![firestone2](https://user-images.githubusercontent.com/84371650/224534200-28c1c41e-b195-4e73-8233-9450a435cac7.PNG)

All of the links show a 60 minute buff top right of the screen with is the oil enchant. The fire stone does not provide that, it provides a 5 seconds buff that refreshes every 5 seconds.

The logic proof should be more than enough. But here are some WLOGS of top parsing players using firestone and having weapon oil on at the same time: https://classic.warcraftlogs.com/reports/LBfAPQ1WprHDqakV#fight=4&type=summary&source=16

People are replacing wands that give around 25 EP worth of stats for a 30 SP firestone in CLASSIC if losing 36 sp + 14 crit is worth 5 sp, then idk what to tell ya.

Brilliant WIzard Oil gives 36 SP and 14 CRIT which not only 6 SP more but also 14 more crit.

Trying to say with a straight face that the entire Classic playerbase (including my 2-3 months in classic in the #1 WF guild) using a 30 SP firestone to gain 5 SP over other wands just to lose out on a WHOLE 36 SP and 14 Crit makes absolutely no sense and this conversation should not need to go any further.

Here's a picture of the wowhead also saying the firestone is bis giving more proof (aside from the massive amount of wlogs) that people are using the firestone and that it's a 45 EP worth of stat dps loss if they are wearing a firestone, according to you.
![image](https://user-images.githubusercontent.com/127469471/225014842-3eee4f68-834c-4c5e-8aa1-22ba7ab19f3d.png)

**Comment by Wolffenstein** [comment]
Fixed in rev 3708.
