### ISSUE TITLE
Siphon Life not snapshotting Improved Shadow Bolt

### ISSUE THREAD

**Issue by Soujin1337** [Atlantiss/NetherwingBugtracker#8181]
[//]: # (Enclose links to things related to the bug using http://wowhead.com or any other TBC database.)
[//]: # (You can use screenshot ingame to visual the issue.)
[//]: # (Write your tickets according to the format:)
[//]: # ([Quest][Azuremyst Isle] Red Snapper - Very Tasty!)
[//]: # ([NPC] Magistrix Erona)
[//]: # ([Spell][Mage] Fireball)
[//]: # ([Npc][Drop] Ghostclaw Lynx)
[//]: # ([Web] Armory doesnt work)
[//]: # (To find server revision type `.server info` command in the game chat.)
![image](https://user-images.githubusercontent.com/127469471/224235379-484443ad-625a-47dc-ba7f-dadf82f5b52e.png)

Sources: 

https://www.wowhead.com/tbc/guide/classes/warlock/dps-rotation-cooldowns-abilities-pve
https://youtu.be/W2Qg6x_SKTY?t=507 (crix kekw)

**Description**: 
When Siphon Life is cast during Improved Shadow Bolt, and Improved Shadow Bolt wears off, Siphon Life is not snapshotted with the 20% increased damage. This is not how SL works in Blizzlike as it should be one of the only dots in the game that snapshot with ISB.
**Current behaviour**:
Siphon Life does not keep doing 20% more damage after Improved Shadow Bolt is down if it was put up while Improved Shadow Bolt was on boss.
**Expected behaviour**: 
Siphon Life should keep the 20% damage amplification through its entire duration if cast while ISB is up.
**Server Revision**:

**Comment by Wolffenstein** [comment]
Fixed in rev 3705.
