### ISSUE TITLE
Insignia of the Horde

### ISSUE THREAD

**Issue by Traneqq** [Atlantiss/NetherwingBugtracker#8182]
Brave Stonehide  and Sergeant Ba'sha
<Officer Accessories Quartermaster>
 dont have [Insignia of the Horde](https://www.wowhead.com/tbc/item=18853/insignia-of-the-horde) (5000 honor 5 min cd)  and https://www.wowhead.com/tbc/item=37865/medallion-of-the-horde (8000 honor 2 min cd)

**Comment by RobinWW** [comment]
Well you linked the epic one that comes way later but this one should be added https://www.wowhead.com/tbc/item=28239/medallion-of-the-horde

The 5 min CD one is classic one should be there as well but at the start of tbc the Blue 2 min CD should be available
