### ISSUE TITLE
[Talent][Shaman][Enhancement Tree] Flurry

### ISSUE THREAD

**Issue by Healweed** [Atlantiss/NetherwingBugtracker#8183]
**Description**: 
As of now i was testing shaman enhancement tree  on each very talent and i came across with this Flurry bugged one which found it weird and tested on all ranks of the talent itself and they are giving wrong values for each rank. I came to test with a 2.7s weapon so it made me more easier to have better results on testing. This is a major issue as for enhancement this is a buff that's really valuable to us.

**Current behaviour**:
As of now these are the current behaviour on how flurry is acting. Note that the attack speed values are just a sample of what the current values are atm on a 2.7s weapon without any other haste/attack speed modifiers with exception of flurry

Flurry 1/5 is giving 9%  > Attack speed from 2.7s to 2.45s( **incorrect value**)

Flurry 2/5 is giving 13% > Attack speed from 2.7s to 2.35s (**incorrect value**)

Flurry 3/5 is giving 19% > Attack speed from 2.7s to 2.25s(**incorrect value**)

Flurry 4/5 is giving 20% > Attack speed from 2.7s to 2.16s(**incorrect value**)

Flurry 5/5 is giving 23% > Attack speed from 2.7s to 2.08s(**Incorrect value**)

**Expected behaviour**: 

Flurry 1/5 should give 10% ( Correct timer would be 2.43s)
https://www.wowhead.com/tbc/spell=16256/flurry

Flurry 2/5 should give 15% ( Correct timer would be 2.95s)
https://www.wowhead.com/tbc/spell=16281/flurry

Flurry 3/5 should give 20% ( Correct timer would be 2.16s)
https://www.wowhead.com/tbc/spell=16282/flurry

Flurry 4/5 should give 25% ( Correct timer would be 2.025s)
https://www.wowhead.com/tbc/spell=16283/flurry

Flurry 5/5 should give 30% ( Correct timer would be 1.81s)
https://www.wowhead.com/tbc/spell=16284/flurry

**Server Revision**: 
PTR 3706

**Comment by ghost** [comment]
https://wowpedia.fandom.com/wiki/Attack_speed?oldid=1503268#Attack_speed_calculation

**Comment by Healweed** [comment]
> https://wowpedia.fandom.com/wiki/Attack_speed?oldid=1503268#Attack_speed_calculation

You linked an attack speed calculation where in itself it's the same scenario of **what's** supposed to be on the correct values.
Furthermore the values arent by 2-3-4 digits but by a large margin  missing!

**Comment by Peachusftw** [comment]
The current values are indeed correct, 30% haste doesnt translate to 30% faster swings, its a proportional increase to what an attack with 0 haste wouldve been. With 30% haste youre expected to hit roughly 30% more often than what youd be hitting with no haste. Notice that this doesnt equal to "your attack speed x 0.7" but rather "your attack speed / 1.3".

Just like a 100% haste doesnt make you attack at an infinite speed, but makes you attack twice as fast instead (your attack speed / 2 = half your attack speed)

Following this formula, a 5/5 flurry results in a 23% reduction of your swing timer, which is on your case 2.7s => 2.08s, which again matches the currect behaviour

**Comment by Peachusftw** [comment]
>30% haste doesnt translate to 30% faster swings

Come to think of it, it actually does.

**Comment by Healweed** [comment]
> The current values are indeed correct, 30% haste doesnt translate to 30% faster swings, its a proportional increase to what an attack with 0 haste wouldve been. With 30% haste youre expected to hit roughly 30% more often than what youd be hitting with no haste. Notice that this doesnt equal to "your attack speed x 0.7" but rather "your attack speed / 1.3".
There's zero haste involvement 😆 😆 😆 😆 😆 
> 
> Just like a 100% haste doesnt make you attack at an infinite speed, but makes you attack twice as fast instead (your attack speed / 2 = half your attack speed)

But since when does Flurry gives haste? And what does haste have to do with this?
As far im concerned and aware, haste has jackshit on this where the stat itself hastens the character(attack speed, spellcasting speed and ranged speed on top of shortening ur GCDs). 

The only thing that does is affecting your swing timer. That's about it

**Comment by Peachusftw** [comment]
Regardless of what it actually is, anything that speeds up your swings does so proportionally. 30% haste/attack speed buff (whatever you want to call it) will always result in a 23% swing speed increase because it doesnt lower the time between your swings by 30% but rather lets you hit 30% more often. 2.7 = 1 swing and then 2.08 + 0.62 (which is 2.08*0.3) = 1 swing and an extra 3/10th of a swing.

**Comment by Wolffenstein** [comment]
It's working correctly.
