### ISSUE TITLE
Can't enter Outland lvl 1 - Could in Blizzlike

### ISSUE THREAD

**Issue by Soujin1337** [Atlantiss/NetherwingBugtracker#8185]
[//]: # (Enclose links to things related to the bug using http://wowhead.com or any other TBC database.)
[//]: # (You can use screenshot ingame to visual the issue.)
[//]: # (Write your tickets according to the format:)
[//]: # ([Quest][Azuremyst Isle] Red Snapper - Very Tasty!)
[//]: # ([NPC] Magistrix Erona)
[//]: # ([Spell][Mage] Fireball)
[//]: # ([Npc][Drop] Ghostclaw Lynx)
[//]: # ([Web] Armory doesnt work)
[//]: # (To find server revision type `.server info` command in the game chat.)

**Description**: 
Not possible to enter Outland right now or get summoned to Outland below level 50 I think.
**Current behaviour**:
Not be able to enter/get summoned at level 1
**Expected behaviour**: 
Should be able to enter/get summoned at level 1
**Server Revision**:

**Comment by tsu-1** [comment]
This is Blizzlike. You could not enter outland if you weren't at least level 58.

**Comment by Wolffenstein** [comment]
Intended even if not 100% blizzlike
