### ISSUE TITLE
Lowered Training Costs?

### ISSUE THREAD

**Issue by Foodlenz** [Atlantiss/NetherwingBugtracker#8188]
Not a bug a such, but lowered training costs haven't been enabled on the PTR to account for the increased leveling speed.

![image](https://user-images.githubusercontent.com/72258441/224527993-e70a996c-4909-4b1d-858a-28a624017ea0.png)

Where as the same spell is 4c on the Karazhan realm.

**Comment by Foodlenz** [comment]
Oh, it seems auto learning spells as you level is in effect.

Is this something that'll be on live realms?

**Comment by adzz452** [comment]
No, reduced cost on live

**Comment by Godmatik** [comment]
Sounds like he just needs to port over the reduced costs from Kara realm before live happens.

**Comment by Wolffenstein** [comment]
It's just a config option. Should be enabled on PTR now.
