### ISSUE TITLE
Missing quest in Dustowallow Marsh on Karazhan.

### ISSUE THREAD

**Issue by AWIDIUS** [Atlantiss/NetherwingBugtracker#8189]
**Description**:  NPC Brogg isn't offering me quest "Spirits of Stonemaul Hold" https://www.wowhead.com/tbc/quest=11159/spirits-of-stonemaul-hold although you don't need to complete any prerequisite quest to obtain this particular quest.

**Current behaviour**: NPC Brogg isn't offering me quest "Spirits of Stonemaul Hold" https://www.wowhead.com/tbc/quest=11159/spirits-of-stonemaul-hold although you don't need to complete any prerequisite quest to obtain this particular quest.

**Expected behaviour**:  NPC Brogg should be offering quest "Spirits of Stonemaul Hold" regardless on completion of other quests, but only be gated behind 35 level requirement,

**Server Revision**: 3651

**Comment by AWIDIUS** [comment]
UPDATE: Quest "Spirits of Stonemaul Hold" is dependant upon completion of "The essence of enmity" quest.

**Comment by Godmatik** [comment]
Although none of the wowhead comments specifically mention "Essence of Enmity" as being a necessary pre-quest, I think it's pretty fair to assume if you read the quest descriptions - the NPC talks about building a totem and once you do so from previous quest, he has you use it.
