### ISSUE TITLE
Skeleton Finger. The totem of infliction. [Quests] [Quest item]

### ISSUE THREAD

**Issue by Neophrone** [Atlantiss/NetherwingBugtracker#819]
[//]: # (Enclose links to things related to the bug using http://wowhead.com or any other TBC database.)
[//]: # (You can use screenshot ingame to visual the issue.)
[//]: # (Write your tickets according to the format:)
[//]: # ([Quest][Azuremyst Isle] Red Snapper - Very Tasty!)
[//]: # ([NPC] Magistrix Erona)
[//]: # ([Spell][Mage] Fireball)
[//]: # ([Npc][Drop] Ghostclaw Lynx)
[//]: # ([Web] Armory doesnt work)

**Description**: Quest [The totem of infliction], drop rate for [Skeleton finger] is extremely low, killed about 25-30 [Skeletal Warrior] [Skeletal Mage] got only 2 [Skeleton finger].

**Current behaviour**: Drop rate for [Skeleton finger] to low.

**Expected behaviour**: Actual wowhead link don't show drop rate, but I found wayback machine link of old (2007) wowhead version. Drop rate from  [Skeletal Mage] and [Skeletal Warrior] should be 17-18% (every 5-6 mobs).
https://web.archive.org/web/20070509205107/http://www.wowhead.com:80/?item=2378#00Rz

**Server Revision**: 2078.

**Comment by Firroth** [comment]
I didn't have such problem, I dropped all in 10-12min or so on the same mobs which you did, so either some new rev. broke it or you just have bad luck.

**Comment by Neophrone** [comment]
> I didn't have such problem, I dropped all in 10-12min or so on the same mobs which you did, so either some new rev. broke it or you just have bad luck.

Looks like you right. After reporting this problem got mine in 10mins.
