### ISSUE TITLE
Extremely low droprate of "Southsea pirate hat" on Karazhan.

### ISSUE THREAD

**Issue by AWIDIUS** [Atlantiss/NetherwingBugtracker#8190]
**Description**: Extremely low droprate of "Southsea pirate hat".

**Current behaviour**: I've managed to get one "Southsea pirate hat" out of 18 mobs, resulting in rough drop chance of 5,55% of "Southsea pirate hat" per mob.

**Expected behaviour**: "Southsea pirate hat" drop chance should range approximatelly between 29% to 35%, depending on which mob is killed.  https://www.wowhead.com/tbc/item=20519/southsea-pirate-hat

**Server Revision**: 3651
![WoWScrnShot_031223_102602](https://user-images.githubusercontent.com/45521546/224536223-d0ab0f02-92c7-4dc1-80d4-08136b5bdf6b.jpg)

**Comment by AWIDIUS** [comment]
UPDATE: Quest completed by killing about 67 pirates (+-2), thus making it around 28,9%-30,7% drop chance of hat per mob, which I would consider appropriate, taking in count the absolute unluck on first 18 mobs, which should be solved with implementing "Progressive Quest Loot Chance".

**Comment by Godmatik** [comment]
If you playing on Karazhan realm , it hasn't been updated with the new features, I think Wolf is done updating that server

**Comment by AWIDIUS** [comment]
Well, there is no feature to start from lvl 1 on PTR and I've been told there is no need for that, so I'm testing all leveling content on Karazhan. Etherious told me that Karazhan is pretty much what it is gonna be when it launches.

**Comment by Godmatik** [comment]
Wolf changed it recently so you start as lvl 1 on PTR now

**Comment by tsu-1** [comment]
Checked just now. Quest item drops way more often than OP says. I got 5 hats in 10 mob kills.
