### ISSUE TITLE
[Warrior] Sword Specialization

### ISSUE THREAD

**Issue by ghost** [Atlantiss/NetherwingBugtracker#8191]
**Description**: Sword Specialization procced by On Next Melee abilities (Cleave/Heroic Strike) is working improperly.

**Current behaviour**: Sword Specialization procs by Cleave either do no damage or counts as the damage of one of the Cleaves.
When procced by Heroic Strike it does nothing.

**Expected behaviour**: Sword Specialization procs by On Next Melee abilities (Cleave/Heroic Strike) should do a white damage attack.

**Server Revision**: 3707
![cleavebug2](https://user-images.githubusercontent.com/84371650/224551587-8a8de302-9583-4e6e-b894-a92fa572df54.PNG)
![cleavebug3](https://user-images.githubusercontent.com/84371650/224551595-2e1ed869-f239-4deb-99f4-eb5c970b9f3c.PNG)
![hsbug](https://user-images.githubusercontent.com/84371650/224551597-c3b4dfa3-4946-4c8c-99e7-ef5ed2943f90.PNG)
![hsbug2](https://user-images.githubusercontent.com/84371650/224551600-65b74ffb-752d-4905-b176-1634eb7d2500.PNG)

**Comment by Wolffenstein** [comment]
Fixed in rev 3708.
