### ISSUE TITLE
[Item] [Pauldrons of Wild Magic]

### ISSUE THREAD

**Issue by AgentMalice** [Atlantiss/NetherwingBugtracker#8192]
[//]: # (Enclose links to things related to the bug using http://wowhead.com or any other TBC database.)
[//]: # (You can use screenshot ingame to visual the issue.)
[//]: # (Write your tickets according to the format:)
[//]: # ([Quest][Azuremyst Isle] Red Snapper - Very Tasty!)
[//]: # ([NPC] Magistrix Erona)
[//]: # ([Spell][Mage] Fireball)
[//]: # ([Npc][Drop] Ghostclaw Lynx)
[//]: # ([Web] Armory doesnt work)
[//]: # (To find server revision type `.server info` command in the game chat.)

**Description**: 
I cannot find the Pauldrons of Wild Magic item id: 32078 with my atlasloot nor when I try to add item with the id.
**Current behaviour**:
Item returns a not found when using .additem
**Expected behaviour**: 
i should get the item in my bags
**Server Revision**:

**Comment by Godmatik** [comment]
Not added until patch 2.1
