### ISSUE TITLE
[Racial Swap] Draenei hit racial

### ISSUE THREAD

**Issue by Godmatik** [Atlantiss/NetherwingBugtracker#8193]
**Description**: 
Draenei hit racial (Heroic Presence/Inspiring Presence) after using Racial Swap

**Current behaviour**:
After a Draenei uses racial swap - their racial hit aura remains for party members - not sure if you have to be in a group at the time you do the swap or not.

**Expected behaviour**: 
Should go away from party members after racial swapping.

**Server Revision**: 
3707

https://www.wowhead.com/tbc/spell=6562/heroic-presence
https://www.wowhead.com/tbc/spell=28878/inspiring-presence

![f58462201a11d850b29fb1487cebadab](https://user-images.githubusercontent.com/37913400/224603194-8898a1e7-d943-4c49-940a-84b34e1e239a.png)

**Comment by Wolffenstein** [comment]
Fixed in rev 3708.
