### ISSUE TITLE
[Item][Nightfall] low proc rate

### ISSUE THREAD

**Issue by aplouding** [Atlantiss/NetherwingBugtracker#8194]
Item https://www.wowhead.com/classic/item=19169/nightfall
**Description**: 
Item has incorrect proc rate. Should be at least 18% or so.
**Current behaviour**:
When attacking figurine 70/73 the item has incorrect proc rate. It should be proccing far more. Please check.
**Expected behaviour**: 
It should proc same as Annihilator.
**Server Revision**: 
3707

**Comment by Godmatik** [comment]
Blizzlike - the proc rate was reduced heavily in TBC

![NightfallProc](https://user-images.githubusercontent.com/37913400/224807108-13db02ba-c2b8-4c5a-89be-bee5aa930f9e.png)
