### ISSUE TITLE
Eskhandar set dont work properly

### ISSUE THREAD

**Issue by BobTschigerillo** [Atlantiss/NetherwingBugtracker#8195]
[//]: # (Enclose links to things related to the bug using http://wowhead.com or any other TBC database.)
[//]: # (You can use screenshot ingame to visual the issue.)
[//]: # (Write your tickets according to the format:)
[//]: # ([Quest][Azuremyst Isle] Red Snapper - Very Tasty!)
[//]: # ([NPC] Magistrix Erona)
[//]: # ([Spell][Mage] Fireball)
[//]: # ([Npc][Drop] Ghostclaw Lynx)
[//]: # ([Web] Armory doesnt work)
[//]: # (To find server revision type `.server info` command in the game chat.)

**Description**: 
4 Piece Set of Eskhandar id: 18202-18205 dosnt work properly.
When "Eskhandar" got summoned he is a level 1 Beast. He should be same level as summoner so "level70" 
With level 1 he misses all attacks and cant debuff the target.

**Current behaviour**:
Level 1 Beast

**Expected behaviour**: 

Level 70 Beast and debuff the target
**Server Revision**: 
![WoWScrnShot_031423_122545](https://user-images.githubusercontent.com/127848722/224987351-cbfd9f82-94c7-41d3-bc11-3ab665aec912.jpg)

**Comment by Wolffenstein** [comment]
Fixed in rev 3708.
