### ISSUE TITLE
[Item][Figurine - Felsteel Boar]

### ISSUE THREAD

**Issue by aplouding** [Atlantiss/NetherwingBugtracker#8196]
**Current behaviour**:
Boar does not use ability Rushing Charge when summoned.
**Expected behaviour**: 
Use: [Summons the Felsteel Boar to fight for you for 30 seconds.](https://www.wowhead.com/tbc/spell=31038/felsteel-boar) (5 Min Cooldown)
Once initiation combat, Felsteel boar should use Rushing Charge (https://www.wowhead.com/tbc/spell=6268/rushing-charge#used-by-npc)
**Server Revision**: 
3707

**Comment by Wolffenstein** [comment]
Fixed in rev 3708.
