### ISSUE TITLE
[Rogue][Class Trainer]Dualwield at level 20, instead of 10.

### ISSUE THREAD

**Issue by Nihaobeachez** [Atlantiss/NetherwingBugtracker#8197]
[//]: # (Enclose links to things related to the bug using http://wowhead.com or any other TBC database.)
[//]: # (You can use screenshot ingame to visual the issue.)
[//]: # (Write your tickets according to the format:)
[//]: # ([Quest][Azuremyst Isle] Red Snapper - Very Tasty!)
[//]: # ([NPC] Magistrix Erona)
[//]: # ([Spell][Mage] Fireball)
[//]: # ([Npc][Drop] Ghostclaw Lynx)
[//]: # ([Web] Armory doesnt work)
[//]: # (To find server revision type `.server info` command in the game chat.)

**Description**: Leveled a bit on PTR and didnt learn Dualwield as rogue on level 10, so i checked Trainer and it was listed as Level 20 (Warrior and Hunter learn it at 20)

**Current behaviour**: Dualwield at level 20

**Expected behaviour**: Dualwield at level 10

**Server Revision**:

**Comment by Wolffenstein** [comment]
Fixed in rev 3708.
