### ISSUE TITLE
[Faerie Fire][26993] Faerie Fire doesnt work properly

### ISSUE THREAD

**Issue by Nihaobeachez** [Atlantiss/NetherwingBugtracker#8198]
[//]: # (Enclose links to things related to the bug using http://wowhead.com or any other TBC database.)
[//]: # (You can use screenshot ingame to visual the issue.)
[//]: # (Write your tickets according to the format:)
[//]: # ([Quest][Azuremyst Isle] Red Snapper - Very Tasty!)
[//]: # ([NPC] Magistrix Erona)
[//]: # ([Spell][Mage] Fireball)
[//]: # ([Npc][Drop] Ghostclaw Lynx)
[//]: # ([Web] Armory doesnt work)
[//]: # (To find server revision type `.server info` command in the game chat.)

**Description**: Leveled on PTR and a level 12 Mob called Blackwood Pathfinder (2167) used Faerie Fire on me, even with the Debuff i could use Stealth

**Current behaviour**: Lets you stealth, even with Faerie Fire on you

**Expected behaviour**: Being hindered to Stealth with Faerie Fire Debuff on you

**Server Revision**:

**Comment by ghost** [comment]
this does not apply to faerie fire cast by players on another player in a pvp environment so it is more likely only bugged for faerie fire debuffs applied by certain npcs

**Comment by Wolffenstein** [comment]
Fixed in rev 3708.
