### ISSUE TITLE
Shadow Vulnerability double-dip doesn't consider player's spell hit chance

### ISSUE THREAD

**Issue by ForStateSake** [Atlantiss/NetherwingBugtracker#8199]
[//]: # (Enclose links to things related to the bug using http://wowhead.com or any other TBC database.)
[//]: # (You can use screenshot ingame to visual the issue.)
[//]: # (Write your tickets according to the format:)
[//]: # ([Quest][Azuremyst Isle] Red Snapper - Very Tasty!)
[//]: # ([NPC] Magistrix Erona)
[//]: # ([Spell][Mage] Fireball)
[//]: # ([Npc][Drop] Ghostclaw Lynx)
[//]: # ([Web] Armory doesnt work)
[//]: # (To find server revision type `.server info` command in the game chat.)

**Description**: 
500 mind flay were cast on a 73-level target dummy.
Spell hit rating = 15.79%

**Current behaviour**:
Mind Flay resist rate: 1.4%
Shadow Vulnerability resist rate: 18.2%

**Expected behaviour**: 
Shadow Vulnerability resist rate around 1%

Note: The same behavior is also observed with frost mage's winter's chill effect.

**Server Revision**: 
Atlantiss Atlantiss realm | Content patch: 2.0.3 | Revision: 3707

<img width="856" alt="Screenshot 2023-03-14 alle 20 40 57" src="https://user-images.githubusercontent.com/11272777/225120986-e0130596-c69a-4f3c-a7e6-e7b33b05dc21.png">

**Comment by Wolffenstein** [comment]
Fixed in rev 3708.

**Comment by ForStateSake** [comment]
Hello @Wolffenstein
I think this has been only partially fixed.
I did the same test and the Shadow Vulnerability miss rate is now at around 12%. I think that spell hit rating talents (Shadow Focus in this case) are still not being taken into consideration.

<img width="825" alt="Screenshot 2023-03-15 alle 08 55 12" src="https://user-images.githubusercontent.com/11272777/225244187-49b304d5-06bb-4ed3-b838-8708281f87d6.png">
