### ISSUE TITLE
[NPC] Archaeologist Adamant Ironheart - Npc Quote minor bug

### ISSUE THREAD

**Issue by Firroth** [Atlantiss/NetherwingBugtracker#82]
[NPC] Archaeologist Adamant Ironheart - Npc Quote minor bug

**Current behaviour**:
It's minor bug, but I guess still counts as one which you want to fix.
After turning in quest: http://wowwiki.wikia.com/wiki/Quest:Rune_Covered_Tablet
Npc which you turned in quest to starts "mini-event" where he talks with said Archeologist.

When archeologist gets to the part: 
"Well, you aren't going to like what I have to tell you, young missy. This tablet is a naga communication. Their leader, Warlord Sriss'tiz, has ordered his naga to take the rest of the island by force."
You''ve like 0.5 second to read this part, which is plain impossible - you can read it easily from chat though, but not from npc's bubble. 

After not even 1s he says his next line:
Till he says next one: "And it looks like he's got reinforcements comin' from Nazjatar!"
Rest works fine, with proper timings.

**Expected behaviour**: 
You should have at least 5-10seconds, to read this part before he says next one. Length depends on how long is said quote.

**Server Revision**: 
2019

**Comment by Wolffenstein** [comment]
Fixed in rev 2022.
