### ISSUE TITLE
[Spell][Paladin] Judgement, Blessing of Might & Devotion Aura

### ISSUE THREAD

**Issue by Anfarru** [Atlantiss/NetherwingBugtracker#8201]
Paladin abilities in TBC Classic, sorted by level requirement (ascending):
https://www.wowhead.com/tbc/spells/abilities/paladin#0+2+20

**Description**: 
The spells Judgement, Blessing of Might and Devotion Aura are not available at starting paladin trainer.

**Current behaviour**:
Devotion Aura not available at level 1, Judgement & BoM not available at level 4.
https://imgur.com/a/4Vlc2kH

**Expected behaviour**: 
Devotion Aura available at level 1, Judgement and BoM available at level 4.
https://imgur.com/a/N8caXZF

**Server Revision**:

**Comment by Wolffenstein** [comment]
If you're testing on PTR then chances are you already know them automatically because autolearning is turned on
