### ISSUE TITLE
[QUEST] Scouring the Desert

### ISSUE THREAD

**Issue by Godmatik** [Atlantiss/NetherwingBugtracker#8203]
**Description**: 
Silithus quest "Scouring the Desert"

**Current behaviour**:
Quest is missing from NPC after turning in the pre-req

**Expected behaviour**: 
Quest should be available

**Server Revision**: 
3709

https://www.wowhead.com/tbc/quest=9422/scouring-the-desert#comments
https://github.com/Atlantiss/NetherwingBugtracker/issues/7438

**Comment by duzyizly** [comment]
https://github.com/Atlantiss/NetherwingBugtracker/issues/7438

**Comment by Wolffenstein** [comment]
Fixed in rev 3837.
