### ISSUE TITLE
[Core] Mobs fan out in too great an angle in front of the player. 

### ISSUE THREAD

**Issue by MecAtlantiss** [Atlantiss/NetherwingBugtracker#8207]
**Description**: A common complaint I hear from prot pallies on Atlantiss servers is that when tanking many mobs the mobs will fan out in such a wide an angle in front of the player that some will even go behind the player and begin to hit them from the back. I believe the angle that mobs fan out is incorrectly too wide.

**Current behaviour**: [Here is a timestamp to a VoD from a player on Karazhan atlantiss server farming a certain pull of mobs in Scholomance. Notice how wide the mobs are fanned out in front of the player. Also notice that a few seconds into the clip a skeleton will go _behind_ the player despite the player moving backwards in an attempt to reposition the mobs in front of him.](https://youtu.be/sG4Hj17-wYc?t=224)

**Expected behaviour**: [Here is a timestamp to a VoD from that same player doing that same pull, but this time it's on classic TBC. Notice how easily the player is able to keep the mobs in front of him. The mobs barely move and they have a narrower angle of fanning out in front of him.](https://youtu.be/k1nqRsIFyvo?t=221)

**Comment by sk6868** [comment]
I am also noticing this problem. As a tank, it is super annoying and is also affecting tab-targetting effectiveness.

**Comment by MecAtlantiss** [comment]
Presumably fixed in #8713. I haven't tested it personally.
