### ISSUE TITLE
[Spell][Tauren] - Wisp Spirit

### ISSUE THREAD

**Issue by Offex7** [Atlantiss/NetherwingBugtracker#8208]
When I took the alliance specialization for the horde. The spell Wisp Spirit doesn't work on my horde. Please fix it so that I can run  after death as Night Elf.

Spell description:
https://www.wowhead.com/spell=20585/wisp-spirit

**Comment by Offex7** [comment]
[https://www.veed.io/view/ebc24481-dbc0-4da5-a725-ef0dc4dbcf11?sharingWidget=true&panel=share](url)

proofs

**Comment by Offex7** [comment]
Proofs:

https://www.veed.io/view/ebc24481-dbc0-4da5-a725-ef0dc4dbcf11?sharingWidget=true&panel=share

**Comment by Wolffenstein** [comment]
Fixed in rev 3712.
