### ISSUE TITLE
[Item][Mark of Vindication]

### ISSUE THREAD

**Issue by aplouding** [Atlantiss/NetherwingBugtracker#8209]
**Description**: 
Paladin interactions with this item.
**Current behaviour**:
Item is working only with initial consecration, holy wrath, exorcism, holy shock.
**Expected behaviour**: 
It should work with:
- Any Judgement.
- Holy Shock.
- Hammer of Justice.
- Repentance.
- Exorcism.
- Holy Wrath.
- Inital Consecration.
**Server Revision**: 
3711

**Comment by Wolffenstein** [comment]
Fixed in rev 3834.
