### ISSUE TITLE
[NPC] Coilfang Priestess (minor)

### ISSUE THREAD

**Issue by Godmatik** [Atlantiss/NetherwingBugtracker#8211]
**Description**: 
Coilfang priestess dialogue

**Current behaviour**:
One of her RP lines is spoken in common language

**Expected behaviour**: 
Should not be spoken in any language

**Server Revision**: 
3712

![watshesaying](https://user-images.githubusercontent.com/37913400/226190325-538cdfc3-d01a-4106-b426-bbb73f3ed1c9.png)

**Comment by Wolffenstein** [comment]
Fixed in rev 3719.
