### ISSUE TITLE
[Spell][Warlock] (Eye of Kilrogg)

### ISSUE THREAD

**Issue by slampig** [Atlantiss/NetherwingBugtracker#8212]
[//]: # (Enclose links to things related to the bug using http://wowhead.com or any other TBC database.)
[//]: # (You can use screenshot ingame to visual the issue.)
[//]: # (Write your tickets according to the format:)
[//]: # ([Quest][Azuremyst Isle] Red Snapper - Very Tasty!)
[//]: # ([NPC] Magistrix Erona)
# [Spell][Warlock] (Eye of Kilrogg)
[//]: # ([Npc][Drop] Ghostclaw Lynx)
[//]: # ([Web] Armory doesnt work)
[//]: # (To find server revision type `.server info` command in the game chat.)

**Description**: 
Pet is not resummoned after eye of kilrogg channel ends
**Current behaviour**:
After eye of kilrogg despawns/dies/is cancelled, previously summoned demon does not return.
**Expected behaviour**: 
pet should be resummoned automatically after eye of kilrogg channel ends, seen in video https://www.youtube.com/watch?v=GfyO1_ujKwU
**Server Revision**: 
3712

**Comment by Wolffenstein** [comment]
Fixed in rev 3714.
