### ISSUE TITLE
[SPELL] Hunter's Mark w/ Improved Hunter's Mark talents

### ISSUE THREAD

**Issue by Godmatik** [Atlantiss/NetherwingBugtracker#8213]
**Description**: 
Hunter's Mark with 1 or more talent points allocated to Improved Hunter's Mark

**Current behaviour**:
Improved Hunter's Mark can be overwritten with non-talented/non-improved Hunter's Mark

**Expected behaviour**: 
Should not be able to be overwritten - should provide error message stating a stronger spell is on the target. There was a similar bug with faerie fire/talented faerie fire that was fixed last server, for reference:

https://github.com/Atlantiss/NetherwingBugtracker/issues/7502

**Server Revision**: 
3712

https://www.wowhead.com/tbc/spell=14325/hunters-mark
https://www.wowhead.com/tbc/spell=19425/improved-hunters-mark

**Comment by Wolffenstein** [comment]
not going to be fixed due to hunter's mark stacks messing it up
