### ISSUE TITLE
Paladin imp blessing talents are broken

### ISSUE THREAD

**Issue by NeonicSupersonic** [Atlantiss/NetherwingBugtracker#8214]
Paladin imp blessing talents are broken
Imp BoM and Imp BoW give no buffs to respected blessings, tested with 5/5imp r2/3/8 BoM and 5/5imp r7 BoW, every single one gives only default value and can be overridden by pala without improved blessings (which instead should get error message "more powerful buff is already active). Similar buffs on other classes may be broken as well, but its just a baseless assumption.
Taletnts should improve respected blessings as described per each rank

AtlantissCore2 rev. 501b67600292 2023-03-19

**Comment by duzyizly** [comment]
Actually... talents are working well but you are not getting error when for example:
You are casting with 0/2 BoW once You have 2/2 BoW already.
So _without talent_ overrides _with talent_.
You are unable to cast lower level - a more powerfull spell is already active (this is correct).

![image](https://user-images.githubusercontent.com/43931626/226395056-6ecaccad-8920-4d39-8409-dbf842845550.png)
![image](https://user-images.githubusercontent.com/43931626/226395651-8704db67-2164-41a7-b333-af7a2936d613.png)

**Comment by duzyizly** [comment]
Same happens with priest buffs: tested with stamina buff and power word shield.

**Comment by NeonicSupersonic** [comment]
Ok then its second part only where unimproved buffs override improved buffs cos I was not looking properly into tooltips when leveling

**Comment by Wolffenstein** [comment]
Should be fixed in rev 3713. Power Word: Shield is not included due to a deliberate choice.
