### ISSUE TITLE
[DB][Core][GM Command] .quest add #id doesn't work

### ISSUE THREAD

**Issue by Sattva-108** [Atlantiss/NetherwingBugtracker#8215]
# **Description**
`.quest add #id` broke for all my accounts. Other players seem to have no problem with it, or they didn't try it.
I need this command for testing purpose.

# **Current behaviour**
![kOTUBdYY0v](https://user-images.githubusercontent.com/74269253/226523807-fc7daaea-52bd-436a-a17e-40cd625ff33d.png)
Whatever Quest ID i try, it doesn't work.

I tried different classes, different accounts, different clients.
`.quest complete #id` works, however.

# **Expected behaviour**
`.quest add #id` should add any quest to any character in PTR.

# **Server Revision**
Netehrwing PTR TBC (`.server info` not working)

**Comment by Wolffenstein** [comment]
idk why it would break for you but it works fine for everyone else

**Comment by Wolffenstein** [comment]
fixed
