### ISSUE TITLE
[Quest] [Mechanic] [Dustwallow Marsh] Recover the Cargo!

### ISSUE THREAD

**Issue by Sattva-108** [Atlantiss/NetherwingBugtracker#8216]
## Recover the Cargo!
**Description:**
When using [Quest Item](https://www.wowhead.com/tbc/item=33044/salvage-kit) on debris underwater there is too high chance to spawn murloc mob. I salvaged 10 times, got 9 murlocs and 1 quest item drop. 
With this pace i would need to kill almost 60 mobs for 1 quest, so i think its bugged and un-completable. 

**How to reproduce:**
Get quest and try to use quest item on debris underwater multiple times.

**How it should work:**
As the Wowhead comment for TBC stated, there should be very low chance of murloc to spawn. He got 2 murlocs in 8 salvages.

![firefox_MbUKs25G2b](https://user-images.githubusercontent.com/74269253/226533223-4dc34747-2694-4d13-a425-ecda10204679.png)

**Useful links:**
[Quest link](https://www.wowhead.com/tbc/quest=11140/recover-the-cargo)
[Mirefin Ambusher - Mob That Spawns](https://www.wowhead.com/tbc/npc=23701/mirefin-ambusher)
Similar issue solved on [Github for TrinityCore](https://github.com/TrinityCore/TrinityCore/issues/25099) with links to **spells used by Quest Item.**

**Comment by Sattva-108** [comment]
I think it's important to fix, as this quest leads to [another chain](https://www.wowhead.com/tbc/quest=11222/warn-bolvar), which is offering you a teleport to Stormwind from Dustwallow Marsh.

**Comment by Sattva-108** [comment]
I tested once more to make sure it's bugged, and i'm pretty sure it is. 
Took me 15 mins to do the quest, 23 times to use quest item, and thats on level 40, on level 35ish i would've died multiple times. 
Without fighting mobs. With fighting mobs would be around 25 minutes for 1 quest. 

https://www.youtube.com/watch?v=EqtcbfzjmO4

**Comment by tsu-1** [comment]
*bump*

**Comment by Wolffenstein** [comment]
Fixed in rev 3730.
