### ISSUE TITLE
Warlock Spell: Nightfall Proc issue

### ISSUE THREAD

**Issue by budgebudge** [Atlantiss/NetherwingBugtracker#8218]
[//]: # (Enclose links to things related to the bug using http://wowhead.com or any other TBC database.)
[//]: # (You can use screenshot ingame to visual the issue.)
[//]: # (Write your tickets according to the format:)
[//]: # ([Quest][Azuremyst Isle] Red Snapper - Very Tasty!)
[//]: # ([NPC] Magistrix Erona)
[//]: # ([Spell][Mage] Fireball)
[//]: # ([Npc][Drop] Ghostclaw Lynx)
[//]: # ([Web] Armory doesnt work)
[//]: # (To find server revision type `.server info` command in the game chat.)

**Description**: 
The Warlock proc nightfall seems too low. has a 4% per tick to proc (if specced 2/2). when applied to 7+ targets on several tests it took a considerable amount of time between procs. is there maybe an internal CD ? that should not be the case i think. or is the proc % just wrong?
**Current behaviour**:

**Expected behaviour**: 

**Server Revision**:

**Comment by duzyizly** [comment]
**There's no internal CD, I was able to get 3x trance in 5 sec.**
Tested with 4x dummy with full corruption (4x6) + 1 tick of drain life - which is 100/25=4 (%).
Everything looks fine.
Sometimes 0 nightfalls, very rarely 2-3.
Most of the time 1 nightfall occurs per 1 test.

![image](https://user-images.githubusercontent.com/43931626/226581700-c5099448-dfcc-406f-b23b-0aa64efe2aa3.png)
