### ISSUE TITLE
Soothsaying for Dummies - profession specs switching

### ISSUE THREAD

**Issue by Peachusftw** [Atlantiss/NetherwingBugtracker#8219]
**Description**: 
To switch Leatherworking n Engineering specialisation, you need to interact with the book "soothsaying for dummies" and pay the fee
**Current behaviour**:
Book offers no dialogue, specialisations cant be switched
**Expected behaviour**: 
Book should offer an option to switch specs for a nominal fee (150g)
**Server Revision**: 
3712

**Comment by Wolffenstein** [comment]
in TBC you have to unlearn the spec first at the trainer you learned it at
