### ISSUE TITLE
[Quest][Dustwallow Marsh] Traitors Among Us

### ISSUE THREAD

**Issue by Firroth** [Atlantiss/NetherwingBugtracker#822]
[Quest][Dustwallow Marsh] Traitors Among Us

**Current behaviour**:
After talking to Deserter Agitator, after he says his random sequence and he stays friendly he doesn't "run away and despawn".

**Expected behaviour**: 
After talking to Deserter Agitator, after he says his random sequence, he should turn hostile and attack the player - works.
OR
If he stays friendly then he should "run away and despawn". - doesn't work.

Here you can see out of 5, 4 turned hostile 1 runned away.

https://www.youtube.com/watch?v=m60ICqgcJLI

Skip to 0:32.

**Server Revision**: 
2078

**Comment by xmesaj2** [comment]
fixed in rev 2081
