### ISSUE TITLE
[Spell][Orc Racial] Blood Fury tooltip issue (after racial swap)

### ISSUE THREAD

**Issue by ghost** [Atlantiss/NetherwingBugtracker#8221]
[//]: # (Enclose links to things related to the bug using http://wowhead.com or any other TBC database.)
[//]: # (You can use screenshot ingame to visual the issue.)
[//]: # (Write your tickets according to the format:)
[//]: # ([Quest][Azuremyst Isle] Red Snapper - Very Tasty!)
[//]: # ([NPC] Magistrix Erona)
[//]: # ([Spell][Mage] Fireball)
[//]: # ([Npc][Drop] Ghostclaw Lynx)
[//]: # ([Web] Armory doesnt work)
[//]: # (To find server revision type `.server info` command in the game chat.)

**Description**: 
The **[Blood Fury]** tooltip doesn't change/update on alliance characters that used the racial swap feature. At every level the tooltip reads "_Increases attack power by 6 ..._ ". Even tho the tooltip is wrong, the spell itself is calculated correctly and is increasing the attack power by the correct amount depending on character level. At level 70 it will provide 282 attack power while the tooltip still shows 6 attack power. On regular horde orc characters the tooltip updates and works correctly. 

**Current behaviour**:
The **[Blood Fury]** tooltip doesn't change/update on alliance characters that used the racial swap feature. At every level the tooltip reads "_Increases attack power by 6 ..._ ".

**Expected behaviour**: 
The **[Blood Fury]** tooltip should change/update with every level. At level 70 it should read "_Increases attack power by 282 ..._ " for example.

**Server Revision**: 
3712 (PTR)

**Screenshots**:

[Blood Fury] tooltip on nightelf hunter at level 70 with racial swap feature:
![blood_fury](https://user-images.githubusercontent.com/128527992/226719280-73a59935-2422-4f65-8d85-1a34caee282e.png)

[Blood Fury] providing correct AP values as it can be seen in aura/buff bar:
![blood_fury2 png](https://user-images.githubusercontent.com/128527992/226719342-dbc74eb6-9039-43da-9b7e-a7144540f08c.jpg)

[Blood Fury] tooltip on regular orc hunter at level 70:
![blood_fury_horde](https://user-images.githubusercontent.com/128527992/226719358-4190845a-824f-41d7-bc1b-100711e455a5.png)

**Comment by Wolffenstein** [comment]
client issue, i cant fix this
