### ISSUE TITLE
Shield greying out in the bag.

### ISSUE THREAD

**Issue by Rockyraccooner** [Atlantiss/NetherwingBugtracker#8224]
[//]: # (Enclose links to things related to the bug using http://wowhead.com or any other TBC database.)
[//]: # (You can use screenshot ingame to visual the issue.)
[//]: # (Write your tickets according to the format:)
[//]: # ([Quest][Azuremyst Isle] Red Snapper - Very Tasty!)
[//]: # ([NPC] Magistrix Erona)
[//]: # ([Spell][Mage] Fireball)
[//]: # ([Npc][Drop] Ghostclaw Lynx)
[//]: # ([Web] Armory doesnt work)
[//]: # (To find server revision type `.server info` command in the game chat.)

**Description**: 
The shield thats used in weapon swap macros bugs out and your unable to use to equip it.

This is an bug I've encountered on tbc classic as well. However it happens a lot more frequently here.

Macro:

/equip Viking Sword of Stamina
/equip Optomatic Deflector 
/equip Bonebiter

**Current behaviour**:
The shield becomes grey in the bag and becomes unusable. Like its beeing used by something.

![image](https://user-images.githubusercontent.com/68907804/227009556-2596ae31-b625-4926-94fe-b665c1a0e432.png)

**Expected behaviour**: 

To stay in default color and be usable.

**Comment by Godmatik** [comment]
Unable to reproduce, and have not heard of anyone else have similar problems
