### ISSUE TITLE
[Quest][Bloodmyst Isle] They're Alive! Maybe...

### ISSUE THREAD

**Issue by Anfarru** [Atlantiss/NetherwingBugtracker#8225]
Description: 
The quest requires you to destroy spider egg sacs to free Expedition Researchers.
https://www.wowhead.com/tbc/quest=9670/theyre-alive-maybe#comments

Current behaviour:
Egg sacs can contain any mob found in the zone, INCLUDING named enemies like Deathclaw, naga Walord Xiz, as well as the local spiders Myst Spinners, Myst Leechers and Zarakh. Furthermore, the sacs can spawn more than one enemy at a time (this seems to happen only when the sac is hit by multiple instances of damage such as Consecration).
https://imgur.com/a/pk6EdFR

Expected behaviour: 
Egg sacs can spawn a lot of Bloodmyst Isle mobs, but not named enemies and no more than 1 enemy.
Video showcases the quest in TBC Classic.
https://www.youtube.com/watch?v=UzWlliLd1hQ&t=199s

Server Revision: 3712

**Comment by Wolffenstein** [comment]
Fixed in rev 3717.
