### ISSUE TITLE
[Quest][RP] Fake RP event should be removed

### ISSUE THREAD

**Issue by Peglaa** [Atlantiss/NetherwingBugtracker#8226]
[//]: # (Enclose links to things related to the bug using http://wowhead.com or any other TBC database.)
[//]: # (You can use screenshot ingame to visual the issue.)
[//]: # (Write your tickets according to the format:)
[//]: # ([Quest][Azuremyst Isle] Red Snapper - Very Tasty!)
[//]: # ([NPC] Magistrix Erona)
[//]: # ([Spell][Mage] Fireball)
[//]: # ([Npc][Drop] Ghostclaw Lynx)
[//]: # ([Web] Armory doesnt work)
[//]: # (To find server revision type `.server info` command in the game chat.)

**Description**: 
The RP event that happens after the player turns in the quest [Blood Elf Plans](https://www.wowhead.com/tbc/quest=9798/blood-elf-plans) should not exist. It's a fake RP event and I dunno who put it there. This will just bottleneck the starting area since the event also removes quest giver flag while it lasts...

**Current behaviour**:

**Expected behaviour**: 

**Server Revision**:

**Comment by Wolffenstein** [comment]
Fixed in rev 3713.
