### ISSUE TITLE
[SSC] Leotheras the Blind - Stuck

### ISSUE THREAD

**Issue by Foodlenz** [Atlantiss/NetherwingBugtracker#8227]
**Description**: Sometimes Leo will get stuck after his whirlwind and be unable to move. I'm unable to reproduce it consistently, seems to happen about 1/3 of the time though.

**Current behaviour**: Leo will **sometimes** get stuck on a point after doing his whirlwind ability.

https://user-images.githubusercontent.com/72258441/227144855-3aef9d37-3ef6-4a94-a90b-8ae9cd685bd8.mp4

**Expected behaviour**: Not get stuck.

**Server Revision**: 
![image](https://user-images.githubusercontent.com/72258441/227145193-5f2e0b91-2aa1-4bb2-8a3e-63fe2250afcc.png)

**Comment by Wolffenstein** [comment]
cant reproduce
