### ISSUE TITLE
Arcane Concentration & r1 blizzard

### ISSUE THREAD

**Issue by user864354** [Atlantiss/NetherwingBugtracker#8231]
[//]: # (Enclose links to things related to the bug using http://wowhead.com or any other TBC database.)
[//]: # (You can use screenshot ingame to visual the issue.)
[//]: # (Write your tickets according to the format:)
[//]: # ([Quest][Azuremyst Isle] Red Snapper - Very Tasty!)
[//]: # ([NPC] Magistrix Erona)
[//]: # ([Spell][Mage] Fireball)
[//]: # ([Npc][Drop] Ghostclaw Lynx)
[//]: # ([Web] Armory doesnt work)
[//]: # (To find server revision type `.server info` command in the game chat.)

**Description**: Mage arcane talent "Arcane Concentration" (clearcasting) isn't proccing off r1 blizzard

**Current behaviour**: tried to r1 blizzard on 50+ pulled mobs multiple times in a dungeon and it doesnt seem to proc the talent on arcane tree "Arcane Concentration"

**Expected behaviour**:  to proc off any dmging spell

**Server Revision**: 3712

**Comment by Wolffenstein** [comment]
the chance to proc is the same regardless of the number of targets, so you were probably just unlucky

**Comment by ghost** [comment]
https://us.forums.blizzard.com/en/wow/t/what-triggers-clearcasting/586689

"I was doing random blizzards in Org, and got a clear cast, so I went on top of bank and got a couple more without dealing any damage. The talent clearly states “after any damage spell hits a target”. Side note, I made sure there was never any creatures."

"Important to note that Clearcasting has an override script exclusively for Blizzard spells. This may be why it procs on cast (and/or what keeps it from proccing on ticks)."

**Comment by ghost** [comment]
it definitely isnt proccing off blizzard at all
