### ISSUE TITLE
[Spell][Priest] Race-specific priest spells still usable after multiple race swaps

### ISSUE THREAD

**Issue by NK801** [Atlantiss/NetherwingBugtracker#8232]
[//]: # (Enclose links to things related to the bug using http://wowhead.com or any other TBC database.)
[//]: # (You can use screenshot ingame to visual the issue.)
[//]: # (Write your tickets according to the format:)
[//]: # ([Quest][Azuremyst Isle] Red Snapper - Very Tasty!)
[//]: # ([NPC] Magistrix Erona)
[//]: # ([Spell][Mage] Fireball)
[//]: # ([Npc][Drop] Ghostclaw Lynx)
[//]: # ([Web] Armory doesnt work)
[//]: # (To find server revision type `.server info` command in the game chat.)

**Description**: 
Created draenei priest, learned all spells from murloc, swapped to dwarf, then human, then draenei again. Desperate Prayer and Feedback are still usable along with all draenei racials/race specific priest spells

Current racials are draenei, feedback visible in top left corner, desperate prayer is on cd - was able to use it
![WoWScrnShot_032323_235642](https://user-images.githubusercontent.com/35541841/227447878-bbad6b4b-6040-4b08-b2e9-d0abdef50568.jpg)

Event better one few minutes later - showing all skills used
![WoWScrnShot_032423_000000](https://user-images.githubusercontent.com/35541841/227448509-a077ab9f-071e-4f1d-b5a3-45e0182d6a2f.jpg)

**Current behaviour**:
Desperate Prayer and Feedback spells usable after swapped draenei - dwarf - human - draenei, along with draenei specific racial/priest spells. There may be race-specific priest spells still usable after swap than i found and reporting here.

**Expected behaviour**: 
Only able to use priest race-specific draenei spells: Chastise and Symbol of Hope. Desperate Prayer and Feedback should be unusable. There may be other combination of race swaps that don't reset properly.

**Server Revision**: 
2023-03-24 8:00 AM CET, don't know where to find server revision

**Comment by NK801** [comment]
Another one, current racials - draenei, swapped through all of them and can use a lot from different races
![WoWScrnShot_032423_002350](https://user-images.githubusercontent.com/35541841/227452884-d0d6e374-d9a6-4473-959a-c6e808b03f09.jpg)

**Comment by fondlez** [comment]
Just tested the race swap combinations of the shared spell priest races. Race swaps no longer either removes access to the shared spells nor keeps adding spells with each new race swap combination.

So, the issues seem to be fixed now. Thanks Wolf!

**Comment by Wolffenstein** [comment]
Fixed, cheers

**Comment by NK801** [comment]
Tested - it works now. Thanks for quick fix.
