### ISSUE TITLE
Darkmoon card: Crusade doesn't proc on DOTs

### ISSUE THREAD

**Issue by ForStateSake** [Atlantiss/NetherwingBugtracker#8234]
[//]: # (Enclose links to things related to the bug using http://wowhead.com or any other TBC database.)
[//]: # (You can use screenshot ingame to visual the issue.)
[//]: # (Write your tickets according to the format:)
[//]: # ([Quest][Azuremyst Isle] Red Snapper - Very Tasty!)
[//]: # ([NPC] Magistrix Erona)
[//]: # ([Spell][Mage] Fireball)
[//]: # ([Npc][Drop] Ghostclaw Lynx)
[//]: # ([Web] Armory doesnt work)
[//]: # (To find server revision type `.server info` command in the game chat.)

**Description**:
When DOTs are applied, the stack is not added to the buff.

**Current behaviour**:
When DOTs are applied, the stack is not added to the buff.

**Expected behaviour**:
When DOTs are applied, one stack is added to the buff.
https://www.wowhead.com/tbc/item=31856/darkmoon-card-crusade#comments

**Server Revision**: 
Stormforge Atlantiss realm | Content patch: 2.0.3 | Revision: 3712

**Comment by Wolffenstein** [comment]
Fixed in rev 3729.
