### ISSUE TITLE
[Quest][Item] Jungle Remedy

### ISSUE THREAD

**Issue by tsu-1** [Atlantiss/NetherwingBugtracker#8236]
[//]: # (Enclose links to things related to the bug using http://wowhead.com or any other TBC database.)
[//]: # (You can use screenshot ingame to visual the issue.)
[//]: # (Write your tickets according to the format:)
[//]: # ([Quest][Azuremyst Isle] Red Snapper - Very Tasty!)
[//]: # ([NPC] Magistrix Erona)
[//]: # ([Spell][Mage] Fireball)
[//]: # ([Npc][Drop] Ghostclaw Lynx)
[//]: # ([Web] Armory doesnt work)
[//]: # (To find server revision type `.server info` command in the game chat.)

**Description**: Drop rate of quest item

**Current behaviour**: Jungle Remedy drop rate is incredibly low.

**Expected behaviour**: Please raise the drop rate of Jungle Remedy. Even with Dynamic drop rate it is still so bad. Killed 10 - no single drop.

**Server Revision**: Current.

**Comment by Wolffenstein** [comment]
Increased in rev 3715. Please don't write "current" as server revision and used the number from .server info instead.
