### ISSUE TITLE
[Hunter] Misdirection charges not consumed

### ISSUE THREAD

**Issue by Godmatik** [Atlantiss/NetherwingBugtracker#8237]
**Current behaviour**:
Misdirection charges are not consumed when you use Distracting Shot or Serpent Sting. A charge is also not consumed when you use an engineering bomb but does misdirect threat, not sure if that is intentional or blizzlike.

**Expected behaviour**: 
Any shot, including all special abilities, should consume 1 charge of Misdirection. Possibly bombs should consume one as well (or not misdirect threat when used).

**Server Revision**: 
3715

**Comment by Wolffenstein** [comment]
Fixed in rev 3717.
