### ISSUE TITLE
Recipe: Runn Tum Tuber Surprise

### ISSUE THREAD

**Issue by Carneyy** [Atlantiss/NetherwingBugtracker#8238]
[//]: # (Enclose links to things related to the bug using http://wowhead.com or any other TBC database.)
[//]: # (You can use screenshot ingame to visual the issue.)
[//]: # (Write your tickets according to the format:)
[//]: # ([Quest][Azuremyst Isle] Red Snapper - Very Tasty!)
[//]: # ([NPC] Magistrix Erona)
[//]: # ([Spell][Mage] Fireball)
[//]: # ([Npc][Drop] Ghostclaw Lynx)
[//]: # ([Web] Armory doesnt work)
[//]: # (To find server revision type `.server info` command in the game chat.)

**Description**: 
https://www.wowhead.com/tbc/item=18267/recipe-runn-tum-tuber-surprise
not in game
**Current behaviour**:
recipe not existing in loot table
**Expected behaviour**: 
add to loot table of mob
**Server Revision**:

**Comment by Wolffenstein** [comment]
It drops but only if a party member has enough Cooking to learn it
