### ISSUE TITLE
Malygen <General Goods> - recipes

### ISSUE THREAD

**Issue by Carneyy** [Atlantiss/NetherwingBugtracker#8240]
[//]: # (Enclose links to things related to the bug using http://wowhead.com or any other TBC database.)
[//]: # (You can use screenshot ingame to visual the issue.)
[//]: # (Write your tickets according to the format:)
[//]: # ([Quest][Azuremyst Isle] Red Snapper - Very Tasty!)
[//]: # ([NPC] Magistrix Erona)
[//]: # ([Spell][Mage] Fireball)
[//]: # ([Npc][Drop] Ghostclaw Lynx)
[//]: # ([Web] Armory doesnt work)
[//]: # (To find server revision type `.server info` command in the game chat.)

**Description**: 
https://www.wowhead.com/tbc/npc=2803/malygen
He supposed to sell [Recipe: Charred Bear Kabobs](https://www.wowhead.com/tbc/item=35564/recipe-charred-bear-kabobs) & [Recipe: Charred Bear Kabobs](https://www.wowhead.com/tbc/item=35564/recipe-charred-bear-kabobs)
**Current behaviour**:
not existing recipes
**Expected behaviour**: 
add recipe to vendor
**Server Revision**:

**Comment by Godmatik** [comment]
Not added until patch 2.4
