### ISSUE TITLE
[NPC] Doomwalker not spawned

### ISSUE THREAD

**Issue by Godmatik** [Atlantiss/NetherwingBugtracker#8241]
**Current behaviour**:
Doomwalker not spawned

**Expected behaviour**: 
He should be spawned, exists in 2.0 (per wowhead comments)

See previous issue I opened on PTR, it was suspected that he patrols entire zone. Confirmed with Etherious (after he manually spawned him on PTR) that he only patrols his small area in front of Black Temple - and just didn't spawn by default for whatever reason.

https://github.com/Atlantiss/NetherwingBugtracker/issues/8058

**Server Revision**: 
3716

**Comment by Wolffenstein** [comment]
![image](https://user-images.githubusercontent.com/1576644/228122992-f2477f76-9bff-4750-a708-c4dd0b37ef55.png)
Someone/Something killed him, I guess that can happen if he wanders around

**Comment by Godmatik** [comment]
Not possible, didn't see his corpse and not enough level 70s yet
