### ISSUE TITLE
Firewing Point - Orb of Translocation while dead to recover body.

### ISSUE THREAD

**Issue by Vfonw** [Atlantiss/NetherwingBugtracker#8243]
**Description**: 
Orb of Translocation used during The Final Code quest https://www.wowhead.com/tbc/quest=10446/the-final-code doesn't work while dead.

**Current behaviour**:
Clicking the Orb of Translocation while dead gives an error saying you're dead and unable to use it.

**Expected behaviour**: 
Being able to use the Orb of Translocation while dead to get back to your corpse in the event you die upstairs.

**Server Revision**: 
3714

**Comment by Wolffenstein** [comment]
The Orb won't work while you're dead (clientside, blizzlike) but you can walk "into" it and the areatrigger there will teleport you to the top.
