### ISSUE TITLE
[Spell][Mage] Blizzard - Not procing clearcasting on tick and initial cast!

### ISSUE THREAD

**Issue by boxitooo6629** [Atlantiss/NetherwingBugtracker#8244]
**Description**: 
Blizzard spell is not procing clearcasting.

**Current behaviour**:
Blizzard spell is not procing clearcasting.
**Expected behaviour**: 
Clearcasting should proc from blizzard dmg ticks and from initial cast.
**Server Revision**:

**Comment by Wolffenstein** [comment]
Fixed in rev 3717.
