### ISSUE TITLE
Root effect ending interrupts cast

### ISSUE THREAD

**Issue by Davids-Sling** [Atlantiss/NetherwingBugtracker#8247]
**Server Revision**: 3714

If a root effect ends on a target that is currently casting a spell, the cast is sometimes interrupted.
Tested with druid roots, but can happen with any root from any source.

https://user-images.githubusercontent.com/129322455/228656551-7ff171ca-b225-444a-b9bc-2f46968258fe.mp4

**Comment by tsu-1** [comment]
Game breaking. *bump*

**Comment by Wolffenstein** [comment]
I can't reproduce it so gonna try different things, please open a new issue if it still happens after rev 3723.
