### ISSUE TITLE
[Core] Auction House is using 15% AH cut due to "Neutral AH" system caused by global shared AH

### ISSUE THREAD

**Issue by Massie323** [Atlantiss/NetherwingBugtracker#8248]
[//]: # (Enclose links to things related to the bug using http://wowhead.com or any other TBC database.)
[//]: # (You can use screenshot ingame to visual the issue.)
[//]: # (Write your tickets according to the format:)
[//]: # ([Quest][Azuremyst Isle] Red Snapper - Very Tasty!)
[//]: # ([NPC] Magistrix Erona)
[//]: # ([Spell][Mage] Fireball)
[//]: # ([Npc][Drop] Ghostclaw Lynx)
[//]: # ([Web] Armory doesnt work)
[//]: # (To find server revision type `.server info` command in the game chat.)

**Description**: 
Any Auction House that you use to list items with, including your own Faction's AHs, will take a 15% cut on successful sales.
This behaviour is only supposed to occur in "neutral" AHs such as the one in Booty Bay and Gadgetzan. But as the feature of "shared AHs" has been introduced to Capital City AHs, it seems they are still using the higher AH cut from the "Neutral AH" logic.
Faction AHs should only take 5% cut - Neutral AHs normally take 15% cut.

**Current behaviour**:
Capital City AHs are taking 15% AH cut on successful sales.

**Expected behaviour**: 
Capital City AHs should take 5% AH cut on successful sales.

**Server Revision**: 
3714

![image](https://user-images.githubusercontent.com/57675820/228705443-f28333b2-0a07-405c-a120-b4d03bbd7cf4.png)

**Comment by Wolffenstein** [comment]
Fix is already pending
