### ISSUE TITLE
[Core] Mobs pathing into/behind players.

### ISSUE THREAD

**Issue by Massie323** [Atlantiss/NetherwingBugtracker#8249]
[//]: # (Enclose links to things related to the bug using http://wowhead.com or any other TBC database.)
[//]: # (You can use screenshot ingame to visual the issue.)
[//]: # (Write your tickets according to the format:)
[//]: # ([Quest][Azuremyst Isle] Red Snapper - Very Tasty!)
[//]: # ([NPC] Magistrix Erona)
[//]: # ([Spell][Mage] Fireball)
[//]: # ([Npc][Drop] Ghostclaw Lynx)
[//]: # ([Web] Armory doesnt work)
[//]: # (To find server revision type `.server info` command in the game chat.)

**Description**: 
Occasionally when a mob attempts to reposition to max-range, something about the positional calculation gets bugged and the mob will instead just use the player's current location as new target position. Max-range reposition checks only happen in an interval of some seconds, and the pattern of the bug seems to be tied to that system.

**Current behaviour**:
Mobs will path into players, usually ending up behind them.

**Expected behaviour**: 
Mobs should move to their melee max-range distance to the player.

**Server Revision**: 
3714

https://user-images.githubusercontent.com/57675820/228707487-0480c788-0b23-44ce-a169-4b91bb6c0d8c.mp4

**Comment by tsu-1** [comment]
Confirm, it happens mostly when you are doing micro-movement with the enemy trying to position them. If you move a little further they won't move behind your back.

EDIT: Found a way to constantly reproduce the issue. It happens when an enemy stands higher than you on the slope terrain. Managed to reproduce it constantly with Pterrodax in Un'Goro and Sappers in the mine under Honor Hold,

**Comment by gforghieri** [comment]
I can confirm also, this happens and very annoying please fix.

hope this is being looked into, mob positioning for tanks is sometimes impossible. It happens also with huge mobs/dragons their pathing is completely messed up and dps cannot properly stand behind them.

**Comment by Wolffenstein** [comment]
Should be better from revision 3743. If it still happens, make another video and open a new ticket (i dont check closed ones).
