### ISSUE TITLE
Warrior Charge

### ISSUE THREAD

**Issue by Mewmewww** [Atlantiss/NetherwingBugtracker#825]
[//]: # (Enclose links to things related to the bug using http://wowhead.com or any other TBC database.)
[//]: # (You can use screenshot ingame to visual the issue.)
[//]: # (Write your tickets according to the format:)
[//]: # ([Quest][Azuremyst Isle] Red Snapper - Very Tasty!)
[//]: # ([NPC] Magistrix Erona)
[//]: # ([Spell][Mage] Fireball)
[//]: # ([Npc][Drop] Ghostclaw Lynx)
[//]: # ([Web] Armory doesnt work)

**Description**: It's an extremely inconsistent issue, but sometimes I feel like, after my charge, my white attack doesn't connect after my swing. I'm not sure if it's due to my movement after charging someone, but it just happens sometimes, and it's slightly annoying.

**Current behavior**: My current rotation is a charge, hamstring into a white attack, but the white attack doesn't sometimes connect ... Again, perhaps my movement.

**Expected behavior**: White attack should at least hit as I land my charge, but it doesn't.

**Server Revision**: 2078

**Comment by Dpthx** [comment]
TBC client has issues sometimes with scrolling combat text and white hits. Are you sure your hit is not landing? Or is it just a visual thing, and at the next swing you hear 2 attacks and 2 instances of damage. (visual bug, if you watch the hp numbers/combat log you'll see that the attack does actually happen).

**Comment by Mewmewww** [comment]
There are not shown any error messages, but i can record it if anyone here knows a good recording program

**Comment by Easyfraggy** [comment]
https://getsharex.com/

Check your combat log when it happens, most likely the visual bug Dpt mentioned above, it is client issue and happens in general in certain situations when you move while auto attacking.

**Comment by Mewmewww** [comment]
I just realised that Easyfraggy and Dpt was right. My bad!

**Comment by wtRCH** [comment]
Closed due to: 

> I just realised that Easyfraggy and Dpt was right. My bad!
