### ISSUE TITLE
[Quest][Desolace] Kodo Roundup not properly giving credit for tamed kodos while grouped

### ISSUE THREAD

**Issue by eunichron** [Atlantiss/NetherwingBugtracker#8250]
[//]: # (Enclose links to things related to the bug using http://wowhead.com or any other TBC database.)
[//]: # (You can use screenshot ingame to visual the issue.)
[//]: # (Write your tickets according to the format:)
[//]: # ([Quest][Azuremyst Isle] Red Snapper - Very Tasty!)
[//]: # ([NPC] Magistrix Erona)
[//]: # ([Spell][Mage] Fireball)
[//]: # ([Npc][Drop] Ghostclaw Lynx)
[//]: # ([Web] Armory doesnt work)
[//]: # (To find server revision type `.server info` command in the game chat.)

**Description**: 
[Quest][Desolace] Kodo Roundup

https://www.wowhead.com/tbc/quest=5561/kodo-roundup

**Current behaviour**:

When returning to Smeed Scrabblescrew with two tamed kodos while grouped, neither player receives credit for their tamed kodo. Credit is given correctly if only one player returns with a tamed kodo while still grouped.

**Expected behaviour**: 

Every character in a group should receive credit for their own tamed kodo.

**Server Revision**: 

3714

**Comment by Wolffenstein** [comment]
You have to talk to the Kodo to get the credit. That said I will extend giving the credit to all nearby party members in rev 3725.
