### ISSUE TITLE
[Core] Shared Quest items feature breaks in certain quests, party members unable to loot the item - "You don't meet the reqruirements to loot that item."

### ISSUE THREAD

**Issue by Massie323** [Atlantiss/NetherwingBugtracker#8253]
[//]: # (Enclose links to things related to the bug using http://wowhead.com or any other TBC database.)
[//]: # (You can use screenshot ingame to visual the issue.)
[//]: # (Write your tickets according to the format:)
[//]: # ([Quest][Azuremyst Isle] Red Snapper - Very Tasty!)
[//]: # ([NPC] Magistrix Erona)
[//]: # ([Spell][Mage] Fireball)
[//]: # ([Npc][Drop] Ghostclaw Lynx)
[//]: # ([Web] Armory doesnt work)
[//]: # (To find server revision type `.server info` command in the game chat.)

**Description**: 
Certain quest involving looting items leads to issues: 
In "[Sunfury Briefings (10328)](https://www.wowhead.com/tbc/quest=10328/sunfury-briefings)" if you are in a party running "Need over Greed" (or Round Robin in general), only some people will be able to loot the "[Sunfury Military Briefing(29545)](https://www.wowhead.com/tbc/item=29545/sunfury-military-briefing)". Other party members may see the item in their loot window, but will be unable to pick the item up, leading to the UI error message "You don't meet the requirements to loot that item.".
Changing Loot system to Free for All allows all party members to loot the item.

Another example I can provide is the quest "[The Blood is Life[9589]](https://www.wowhead.com/tbc/quest=9589/the-blood-is-life)", where every party member may see a "[Fel Orc Blood Vial[23894]](https://www.wowhead.com/tbc/item=23894/fel-orc-blood-vial)" drop, but be unable to loot the item with the same error message mentioned above. Only 1 person is able to loot said blood, meaning the quest item drops essentially use normal vanilla distribution method (the Round-Robin assigned target may loot the vial)

**Current behaviour**:
Quest items are only able to be looted by one or few party members, with others receiving the error message "You don't meet the reqruirements to loot that item." unless loot rules are set to FFA.

**Expected behaviour**: 
With Netherwing feature of "shared quest items", every party member is supposed to be able to loot the quest items without issue.

**Server Revision**: 
3719

https://user-images.githubusercontent.com/57675820/228938496-c746137a-6b80-4d24-8086-cd054c0bd344.mp4

Note that after closing the loot window, I am unable to open the same mob again, and the tooltip in the bottom right displays who the assigned person is that may loot the quest item.

**Comment by Wolffenstein** [comment]
Our system is based on the shared quest item system added by Blizzard in Cataclysm and the flags are backported only for quest items Blizzard deemed as appropriate having the party shared flag. The items you linked in this bug report are not part of that system and we are not planning on adding additional ones.

**Comment by Massie323** [comment]
I mean this makes sense for the Fel Orc Blood Vials, but I would seriously reckon single key items like the missives for "Sunfury Briefings" would be designed with party share in mind, not to mention that looting a missive from 1 mob works fine for multiple party members, just not **all**, unlike the vials, which are intended to be only looted by 1 person. I'm not going to dig through cata+ footage of people doing the quest though, because there ain't going to be one done in a group.

In any case, the way the loot window currently works combined with the error message leads people to believe it's a bug, and should probably be addressed in some way? If it's not intended to be shared between players, then that still leaves the fact you can just change to FFA to let bugged partymembers loot it anyway.
