### ISSUE TITLE
[NPC][Spell] "Grievous Wounds" not removed upon being fully healed - Rokmar the Crackler - Slavepens

### ISSUE THREAD

**Issue by Massie323** [Atlantiss/NetherwingBugtracker#8254]
[//]: # (Enclose links to things related to the bug using http://wowhead.com or any other TBC database.)
[//]: # (You can use screenshot ingame to visual the issue.)
[//]: # (Write your tickets according to the format:)
[//]: # ([Quest][Azuremyst Isle] Red Snapper - Very Tasty!)
[//]: # ([NPC] Magistrix Erona)
[//]: # ([Spell][Mage] Fireball)
[//]: # ([Npc][Drop] Ghostclaw Lynx)
[//]: # ([Web] Armory doesnt work)
[//]: # (To find server revision type `.server info` command in the game chat.)

**Description**: 
[Rokmar the Crackler](https://www.wowhead.com/tbc/npc=17991/rokmar-the-crackler)'s bleed ability (["Grievous Wounds"](https://www.wowhead.com/tbc/spell=31956/grievous-wound))does not get removed upon being fully healed.

**Current behaviour**:
"[Grievous Wounds](https://www.wowhead.com/tbc/spell=31956/grievous-wound)" remains on the target despite being fully healed.

**Expected behaviour**: 
"[Grievous Wounds](https://www.wowhead.com/tbc/spell=31956/grievous-wound)" should be instantly removed upon being fully healed

**Server Revision**: 
3719

https://user-images.githubusercontent.com/57675820/228990020-ea1729f3-4069-44e6-b68d-ebed69387705.mp4

**Comment by Wolffenstein** [comment]
Health check for Grievous Wounds removal is performed at the next DoT tick, that player got damaged and lost his full health status before that happened. And yes, it's blizzlike if I remember correctly.
