### ISSUE TITLE
Warlock pets gone after mounting/dismounting (apparently a known issue while on SMV)

### ISSUE THREAD

**Issue by WarlockKalz** [Atlantiss/NetherwingBugtracker#8256]
**Description:** Warlock pets randomly disappear on mount/dismount, only pattern that I noticed is that the chance gets higher the longer you are using a mount, only happens on SMV or shortly after leaving the zone
Tested with every pet except Felguard
After searching for related issues, I found this one which fits the case
#(https://github.com/Atlantiss/NetherwingBugtracker/issues/7904#issue-802814019)

**Current behaviour:** Warlock pets randomly disappear (not 100% chance), after mounting/dismounting on SMV

**Expected behaviour:** Warlock pets are automatically summoned when you dismount, in the same state they were in when you used your mount.

**Server Revision:** 3719

**Comment by Wolffenstein** [comment]
Does it happen only in Shadowmoon? Can you post a screenshot of an area where that occurs next time?

**Comment by Peglaa** [comment]
https://www.wowhead.com/tbc/item=30719/spectrecles
 this is the first item I think of whenever there's something fishy going on in Shadowmoon, maybe its connected and being applied to pets and that causes them to spazz out? @WarlockKalz can you confirm if you ever used this item?

**Comment by WarlockKalz** [comment]
Sorry been a bit busy

I tested some areas where this happened and its no longer the case, so it might be related to the quests I was doing
@Peglaa yes I was doing the whole Teron questline, and also the one where you summon a totem to kill elementals:
https://www.wowhead.com/tbc/quest=10458/enraged-spirits-of-fire-and-earth

Pet was gone at least twice in every spot where you need to go and kill elementals (all 4 of them), but also happened around Teron Gorefiend questline, on the Altar of Shadows

Will give it another go and try to reproduce today

**Comment by Wolffenstein** [comment]
Fixed in rev 3754.
