### ISSUE TITLE
There is no current way of removing Soul Link from your pet regardless if it dies unless you literally respec and never use it again. Blizzlike behavior is that it should disappear from pet when it dies and you have to re-cast soul link.

### ISSUE THREAD

**Issue by Soujin1337** [Atlantiss/NetherwingBugtracker#8257]
[//]: # (Enclose links to things related to the bug using http://wowhead.com or any other TBC database.)
[//]: # (You can use screenshot ingame to visual the issue.)
[//]: # (Write your tickets according to the format:)
[//]: # ([Quest][Azuremyst Isle] Red Snapper - Very Tasty!)
[//]: # ([NPC] Magistrix Erona)
[//]: # ([Spell][Mage] Fireball)
[//]: # ([Npc][Drop] Ghostclaw Lynx)
[//]: # ([Web] Armory doesnt work)
[//]: # (To find server revision type `.server info` command in the game chat.)

**Description**: 
Soul Link does not disappear from pet after they die. In blizzlike, it disappears and you have to re-cast the spell when it is back.
**Current behaviour**:
Pet dies, summon pet again, soul link comes back up on both of you as soon as you summon it.
**Expected behaviour**: 
Pet dies, summon pet again, soul link is no longer a thing unless you recast it.
**Server Revision**: 

This is a bigger issue than it seems since pets keep dying in dungeons due to this. Especially imps.

**Comment by Wolffenstein** [comment]
Fixed in rev 3724.
