### ISSUE TITLE
Searing totem & Shattered Hand Champion

### ISSUE THREAD

**Issue by Romisu** [Atlantiss/NetherwingBugtracker#8258]
[//]: # (Enclose links to things related to the bug using http://wowhead.com or any other TBC database.)
[//]: # (You can use screenshot ingame to visual the issue.)
[//]: # (Write your tickets according to the format:)
[//]: # ([Quest][Azuremyst Isle] Red Snapper - Very Tasty!)
[//]: # ([NPC] Magistrix Erona)
[//]: # ([Spell][Mage] Fireball)
[//]: # ([Npc][Drop] Ghostclaw Lynx)
[//]: # ([Web] Armory doesnt work)
[//]: # (To find server revision type `.server info` command in the game chat.)

**Description**: NPC: Shattered Hand Champion. Location: Shattered Halls

**Current behaviour**: Prioritizes killing Searing Totems over hitting the threat target. Tested also on 2 last bosses, they behave as expected.

**Expected behaviour**: Should ignore Searing totems

**Server Revision**:

**Comment by Wolffenstein** [comment]
There's nothing in their AI that would cause them to prioritize Searing Totems, would require more info
