### ISSUE TITLE
[Dungeon] OHF Escort gauntlet - Multiple copies of packs spawning on top of eachother

### ISSUE THREAD

**Issue by Massie323** [Atlantiss/NetherwingBugtracker#8259]
[//]: # (Enclose links to things related to the bug using http://wowhead.com or any other TBC database.)
[//]: # (You can use screenshot ingame to visual the issue.)
[//]: # (Write your tickets according to the format:)
[//]: # ([Quest][Azuremyst Isle] Red Snapper - Very Tasty!)
[//]: # ([NPC] Magistrix Erona)
[//]: # ([Spell][Mage] Fireball)
[//]: # ([Npc][Drop] Ghostclaw Lynx)
[//]: # ([Web] Armory doesnt work)
[//]: # (To find server revision type `.server info` command in the game chat.)

**Current behaviour**:
During the "Escape from Durnholde" escort segment with Thrall, sometimes the event will spawn the next pack of mobs multiple times on top of eachother.

**Expected behaviour**: 
Each pack should only spawn once.

**Server Revision**: 
3719

https://user-images.githubusercontent.com/57675820/229188788-82c5b327-9afa-474c-8fe3-4ce9187d8de9.mp4

Video showcasing a normal pack during escort with 4 mobs and afterwards a bugged pack with 8 mobs (the next pack after the bridge also had 8 mobs).

**Comment by Wolffenstein** [comment]
Fixed in rev 3722.
