### ISSUE TITLE
Formations are bugging out.

### ISSUE THREAD

**Issue by samemari** [Atlantiss/NetherwingBugtracker#826]
[//]: # (Enclose links to things related to the bug using http://wowhead.com or any other TBC database.)
[//]: # (You can use screenshot ingame to visual the issue.)
[//]: # (Write your tickets according to the format:)
[//]: # ([Quest][Azuremyst Isle] Red Snapper - Very Tasty!)
[//]: # ([NPC] Magistrix Erona)
[//]: # ([Spell][Mage] Fireball)
[//]: # ([Npc][Drop] Ghostclaw Lynx)
[//]: # ([Web] Armory doesnt work)

**Description**: 
Human cavalry in Arathi Highlands stuck on the road and charging every 1-2 sec

**Expected behaviour**: 
Run on the road from ally camp to Stromgarde Keep and back, charge into horde players or undead courier with escort
![screenshot 25](https://user-images.githubusercontent.com/29822974/46223447-15814100-c35c-11e8-80b5-97ab3e4547ed.png)

**Server Revision**: 
[20:21:05]AtlantissCoreTBC - rev: 2078
[20:21:05]Online players: 76 (max: 78)
[20:21:05]Active connections: 78 (max: 79) Queued connections: 0 (max: 0)
[20:21:05]Server uptime: 1 Hour(s) 22 Minute(s) 28 Second(s).
[20:21:05]Current time: 2018-09-28 19:21:10
[20:21:05]Content Patch: 203.

**Comment by aresbrutus** [comment]
Can't reproduce, need more info.

**Comment by Tenoutoften** [comment]
Not sure what causes them to be stuck, but I uploaded a [video of agroing them](https://www.youtube.com/watch?v=Qt8OR2ocTRc&feature=youtu.be). Once agroed they chase "forever". Did a .gps & .npc info in the video

NPCs are [[NPC]Lieutenant Valorcall#2612]https://db.excalibur.ws/?npc=2612 & [[NPC]Stromgarde Cavalryman#2738](https://db.excalibur.ws/?npc=2738).

**Comment by totaemoeggerli** [comment]
Lieutenant Valorcall was stuck at Stromgarde entrence with only one of the Cavaleryman.
![Lieutenant Valorcall](https://imgur.com/IUWxSoC.jpg)

The other Cavaleryman was stuck at Hammerfall. He didn't engage until I attacked him. He didn't reset and I pulled him to Stromgarde.
![Cavaleryman](https://imgur.com/kFHVsn6.jpg)

![Clip](https://thumbs.gfycat.com/ParchedDependableJumpingbean-size_restricted.gif)
https://gfycat.com/gifs/detail/ParchedDependableJumpingbean
I'm in combat with the mob from Hammerfall at the start of the clip. You can see that I aggro Vallorcall and the other add long before I am in aggro range (they were stuck at the gate). After I killed one of the Cavaleryman the other one despawns and Lieutenant returns to the position at the gate and contunies his patrol.

**Comment by totaemoeggerli** [comment]
I uploaded another video to my youtube because it was pretty long: https://youtu.be/zxGmoXE7-UU
at [1:40](https://youtu.be/zxGmoXE7-UU?t=1m38s) you can see that one of the adds doesn't reset. I ran back to the patrol and they aggroed long before entering normal aggro range. You can also see that the forsaken bodyguards respawned and run around without attacking the stromgard mobs, They despawned later.
I found the Forsaken Courier later without Bodyguards, not sure how much time passed but not enough for it to respawn and walk all the way here again.
![courier](https://imgur.com/cWo9Id3.jpg)

**Comment by maxturtlesc2** [comment]
Another footage of Lieutenant Valorcall and his adds being completely bugged.
<a href="https://www.dropbox.com/s/iw5c70lxuoz6lgo/2018-10-16_10-12-16.mp4?dl=0">https://www.dropbox.com/s/iw5c70lxuoz6lgo/2018-10-16_10-12-16.mp4?dl=0</a>

**Comment by aresbrutus** [comment]
https://github.com/Atlantiss/NetherwingBugtracker/issues/1064
https://github.com/Atlantiss/NetherwingBugtracker/issues/1710

**Comment by netherwingbta** [comment]
Also affecting https://www.wowhead.com/quest=10922/digging-through-bones
They get stuck on top of eachother and don't assist with attacking mobs.
![wow 2018-11-02 12-27-13-62](https://user-images.githubusercontent.com/43872263/47913263-be5f1680-de9b-11e8-9950-87440e20e987.jpg)

**Comment by aresbrutus** [comment]
https://github.com/Atlantiss/NetherwingBugtracker/issues/2458

**Comment by Tenoutoften** [comment]
https://github.com/Atlantiss/NetherwingBugtracker/issues/3378 same issue with the [NPC]Hand of Argus Swordsman#17704 ID;1,2,3,4,5. I think it might have to do with one of the NPCs dying.

**Comment by Tereneckla** [comment]
Fixed
