### ISSUE TITLE
[Dungeon] [NPC] OHF Epoch Hunter gauntlet - First pack of Infinite Dragonkins using wrong Spells (Human Form spells)

### ISSUE THREAD

**Issue by Massie323** [Atlantiss/NetherwingBugtracker#8260]
[//]: # (Enclose links to things related to the bug using http://wowhead.com or any other TBC database.)
[//]: # (You can use screenshot ingame to visual the issue.)
[//]: # (Write your tickets according to the format:)
[//]: # ([Quest][Azuremyst Isle] Red Snapper - Very Tasty!)
[//]: # ([NPC] Magistrix Erona)
[//]: # ([Spell][Mage] Fireball)
[//]: # ([Npc][Drop] Ghostclaw Lynx)
[//]: # ([Web] Armory doesnt work)
[//]: # (To find server revision type `.server info` command in the game chat.)

**Description**: 
Upon beginning the last gauntlet in OHF with the Infinite Dragonkins, the first pack is made up of 3 Tarren Mill NPCs that will transform into their Dragonkin form. This pack however retains their Human-form spells, such as Serpent Sting for the Tarren Mill Lookout (AKA Infinite Defiler), -50% Mortal Strike for the Tarren Mill Guardsman (AKA Infinite Slayer (which should use a -25% MS version)) and Concussive Blow for the Tarren Mill Protector (AKA Infinite Saboteur).

**Current behaviour**:
First pack of Infinite Dragonkins is using their previous Human-form spells.

**Expected behaviour**: 
First pack of Infinite Dragonkins should use their Dragonkin-form spells.

**Server Revision**: 
3719

https://user-images.githubusercontent.com/57675820/229193079-03fb2fd1-93fd-4dff-b336-40c373fd26b3.mp4

Video showcasing Serpent Sting on me, and MS & Concussive Blow on tank (although I haven't hovered over the MS to check which version it is using, the -50% heal or the -25% heal one).

**Comment by Wolffenstein** [comment]
Fixed in rev 3723.
