### ISSUE TITLE
[Dungeon] [NPC] Erozian not offering teleport back into Caverns of Time after accepting "Return to Andormu"

### ISSUE THREAD

**Issue by Massie323** [Atlantiss/NetherwingBugtracker#8261]
[//]: # (Enclose links to things related to the bug using http://wowhead.com or any other TBC database.)
[//]: # (You can use screenshot ingame to visual the issue.)
[//]: # (Write your tickets according to the format:)
[//]: # ([Quest][Azuremyst Isle] Red Snapper - Very Tasty!)
[//]: # ([NPC] Magistrix Erona)
[//]: # ([Spell][Mage] Fireball)
[//]: # ([Npc][Drop] Ghostclaw Lynx)
[//]: # ([Web] Armory doesnt work)
[//]: # (To find server revision type `.server info` command in the game chat.)

**Description**:
After killing the Epoch Hunter and letting the RP event between Tabetha & Thrall finish, handing in the quest "Escape from Durnholde" and **accepting the followup quest "Return to Andormu"**, Erozian is supposed to give you the dialogue option to teleport you back to Caverns of Time, instead of having to manually ride back to the exit.

**Current behaviour**:
After killing the last boss & accepting "Return to Andormu" Erozian is offering no dialogue option.

**Expected behaviour**: 
After killing the last boss & accepting "Return to Andormu", Erozian should offer the player to teleport out to CoT.

**Server Revision**: 
3719

https://user-images.githubusercontent.com/57675820/229198153-3b93fd14-3520-4bf4-b9d9-9b359e004ea8.mp4

Video showcasing lack of dialogue option.

References:
Burning Crusade Classic: https://youtu.be/P2Ut9SovGUw?t=1501
[Wiki](https://wowwiki-archive.fandom.com/wiki/Escape_from_Durnholde_Keep) mentioning the teleport: 
![chrome_tjo7nbe5Nv](https://user-images.githubusercontent.com/57675820/229197167-d07f3c3a-ea09-4e89-8412-5e8111f6f87b.png)
**Retail** WoW comment from patch 7.3.2. talking about existance of the teleport & hints that it's conditionally tied to something and not always available (= tied to quest): https://www.wowhead.com/npc=18723/erozion#comments:id=2540343

**Comment by Wolffenstein** [comment]
Fixed in rev 3723.
