### ISSUE TITLE
[NPC/Spell] Winterfall Pathfinder - Faerie Fire

### ISSUE THREAD

**Issue by Kuszki** [Atlantiss/NetherwingBugtracker#8262]
[//]: # (Enclose links to things related to the bug using http://wowhead.com or any other TBC database.)
[//]: # (You can use screenshot ingame to visual the issue.)
[//]: # (Write your tickets according to the format:)
[//]: # ([Quest][Azuremyst Isle] Red Snapper - Very Tasty!)
[//]: # ([NPC] Magistrix Erona)
[//]: # ([Spell][Mage] Fireball)
[//]: # ([Npc][Drop] Ghostclaw Lynx)
[//]: # ([Web] Armory doesnt work)
[//]: # (To find server revision type `.server info` command in the game chat.)

**Description**: Spell [Faerie Fire](https://www.wowhead.com/tbc/spell=16498/faerie-fire) cast by [Winterfall Pathfinder](https://www.wowhead.com/tbc/npc=7442/winterfall-pathfinder) doesn't prevent using stealth.

**Current behaviour**: Spell victim is allowed to use stealth.

**Expected behaviour**: While affected, the target cannot use stealth or invisibility.

**Server Revision**: 3721

**Comment by Wolffenstein** [comment]
Fixed in rev 3728.
