### ISSUE TITLE
Chain effects such as multishot and chain lightning should not hit behind player.

### ISSUE THREAD

**Issue by Aeded** [Atlantiss/NetherwingBugtracker#8264]
**Description**: 
Chain effects should not be hitting behind caster

**Current behaviour**:
Chain effects are hitting behind caster
**Expected behaviour**: 
Chain effects should not be hitting behind caster
https://www.youtube.com/watch?v=4okg6BmVoGM&t=15s
**Server Revision**: 3719

**Comment by fondlez** [comment]
Your report is not clear. 

If you mean the Chain Lightning the boss was casting, their abilities can do almost anything and I see no direction restriction in this 30 yard ability (assuming Wowhead is correct): https://www.wowhead.com/tbc/spell=15659/chain-lightning

**Comment by Aeded** [comment]
https://youtu.be/lOHOp-s6__g?t=678
no it should be a general behaviour, chain spells (demaging) dont chain behind caster
But for example chain heal should be able to bounce off behind caster

**Comment by Wolffenstein** [comment]
Fixed in rev 3730.
