### ISSUE TITLE
Mind control

### ISSUE THREAD

**Issue by buccypappa** [Atlantiss/NetherwingBugtracker#8265]
Can't use any mob spell with this just auto attack (I was able to use mob spells back in the day, and in TBC Classic too). 
Additionally it does not cause any fall damage to mobs but it should.

**Comment by Godmatik** [comment]
Can't speak about fall damage, but I definitely can use the mob spells when doing MC

**Comment by Wolffenstein** [comment]
I've never heard of mobs taking fall damage and the rest works as intended.
