### ISSUE TITLE
Priest Prayers

### ISSUE THREAD

**Issue by ghost** [Atlantiss/NetherwingBugtracker#8267]

**Comment by Wolffenstein** [comment]
?? Can you elaborate?

**Comment by Godmatik** [comment]
Are they too low level maybe @R0gerWilco

**Comment by Godmatik** [comment]
Are you all level 70s? What classes?

Dungeon groups I have been in with priests have been using prayer of fortitude with no issue so far.

**Comment by tsu-1** [comment]
I think he means raid group @Godmatik .

You have to buff separately each group when in raid/battleground. Also they might have the buff already?

**Comment by buccypappa** [comment]
Same here. Can't use prayers, usually just for myself. I have to use separately the stam buff for group members.
