### ISSUE TITLE
[SL] 3rd boss patrol pack

### ISSUE THREAD

**Issue by Romisu** [Atlantiss/NetherwingBugtracker#8268]
[//]: # (Enclose links to things related to the bug using http://wowhead.com or any other TBC database.)
[//]: # (You can use screenshot ingame to visual the issue.)
[//]: # (Write your tickets according to the format:)
[//]: # ([Quest][Azuremyst Isle] Red Snapper - Very Tasty!)
[//]: # ([NPC] Magistrix Erona)
[//]: # ([Spell][Mage] Fireball)
[//]: # ([Npc][Drop] Ghostclaw Lynx)
[//]: # ([Web] Armory doesnt work)
[//]: # (To find server revision type `.server info` command in the game chat.)

**Description**:  The Patrolling pack in Shadow Labyrinth, next to the 3rd boss Grandmaster Vorpil, paths incorrectly. The patrol should path in front of the altar/ledge the boss is standing on, then kneel and move around to the other side in a circular pattern. 

**Current behaviour**: The patrol never moves in front of the altar/ledge. After reaching the far left side, instead of moving down, it paths back to the other side. 

**Expected behaviour**:  The patrol should path in front of the altar/ledge the boss is standing on, then kneel and move around to the other side in a circular pattern. This correct pathing can be seen in the TBC classic video linked as evidence. (start at 28.54)

https://youtu.be/ht9781OYx6M?t=1734
**Server Revision**:

**Comment by Wolffenstein** [comment]
Fixed in rev 3729.
