### ISSUE TITLE
[NPC/BOSS] [SPELL] Swamplord Musel'ek

### ISSUE THREAD

**Issue by gun4axb** [Atlantiss/NetherwingBugtracker#8269]
**Description**: 
Encountered a bug during a heroic run in underbog.

**Current behaviour**:
After disengaging combat / wiping, the boss' traps do not disappear, thus, if you step into them it makes the entire party in combat and killing everyone, so you have to run back again. Had 1 trap that was invisible, but can't pinpoint an accurate reason for that.
**Expected behaviour**: 
Traps should disappear after disengaging combat.

![image](https://user-images.githubusercontent.com/97943252/229304227-e3503bb0-3a73-47da-9417-6af2d74a070d.png)

**Server Revision**: 
3728

**Comment by Wolffenstein** [comment]
Fixed in rev 3729.
