### ISSUE TITLE
[Quest][Dustwallow Marsh] Thresher Oil 

### ISSUE THREAD

**Issue by Firroth** [Atlantiss/NetherwingBugtracker#827]
[Quest][Dustwallow Marsh] Thresher Oil https://www.wowhead.com/quest=27217/thresher-oil

**Current behaviour**:
This quest is available now on beta.

**Expected behaviour**: 
Since I heard, you're aiming for emulating from patch to patch and start from 2.0, then this quest should be disabled till patch 2.3.

https://www.wowhead.com/item=33126/thresher-oil#objective-of
Shows when it was added. Also comments prove it too. 
Patch notes from 2.3 also show it.
http://wowwiki.wikia.com/wiki/Patch_2.3.0
![screenshot_1](https://user-images.githubusercontent.com/43505196/46223701-537a6700-c354-11e8-9df0-05a7c116e12b.png)

Well I guess most quests there should be disabled (as 50quests were added).

**Server Revision**: 
2078

**Comment by Dpthx** [comment]
Mudsproket will be available on launch. You can't just revert the client to older maps and you can't remove it either.

**Comment by Peglaa** [comment]
The decision was the leave dustwallow as it is I think, since it greatly helps with the leveling gap and most players decide to go there and level. Its vanilla so, anything to make it easier and more player friendly.

**Comment by aresbrutus** [comment]
Yes, levelling experience will be 2.4.3.
