### ISSUE TITLE
[NPC][Zul'Farrak] Gahz'rilla

### ISSUE THREAD

**Issue by tsu-1** [Atlantiss/NetherwingBugtracker#8270]
[//]: # (Enclose links to things related to the bug using http://wowhead.com or any other TBC database.)
[//]: # (You can use screenshot ingame to visual the issue.)
[//]: # (Write your tickets according to the format:)
[//]: # ([Quest][Azuremyst Isle] Red Snapper - Very Tasty!)
[//]: # ([NPC] Magistrix Erona)
[//]: # ([Spell][Mage] Fireball)
[//]: # ([Npc][Drop] Ghostclaw Lynx)
[//]: # ([Web] Armory doesnt work)
[//]: # (To find server revision type `.server info` command in the game chat.)

**Description**: [Gahz'rilla](https://www.wowhead.com/classic/npc=7273/gahzrilla)

**Current behaviour**: When you summon the boss, it goes out of the water correctly and then when it reaches the point where he should stop, he goes back to the water and out again. (then he stops correctly)

**Expected behaviour**: Go out of the water once.

**Server Revision**: 3728

**Comment by Wolffenstein** [comment]
Blizzlike
