### ISSUE TITLE
[Dungeon][NPC] Black Morass - Sa'at displaying 2 gossips about Chrono-boon instead of only 1

### ISSUE THREAD

**Issue by Massie323** [Atlantiss/NetherwingBugtracker#8272]
[//]: # (Enclose links to things related to the bug using http://wowhead.com or any other TBC database.)
[//]: # (You can use screenshot ingame to visual the issue.)
[//]: # (Write your tickets according to the format:)
[//]: # ([Quest][Azuremyst Isle] Red Snapper - Very Tasty!)
[//]: # ([NPC] Magistrix Erona)
[//]: # ([Spell][Mage] Fireball)
[//]: # ([Npc][Drop] Ghostclaw Lynx)
[//]: # ([Web] Armory doesnt work)
[//]: # (To find server revision type `.server info` command in the game chat.)

**Description**: 
After finishing the Black Morass quest chain, any subsequent runs, the NPC Sa'at will have 2 gossip lines related to generating a Chrono-beacon, when he should only have one option.

**Current behaviour**:
Sa'at has 2 gossip lines, with the first one ("I have lost my beacon) being intended to appear after attempting to request another beacon after deleting the first one.

**Expected behaviour**: 
Only "I require a beacon." should appear for the first request, and "I have lost the beacon and require another one" should appear for subsequent requests.

**Server Revision**: 
3728

![Wow_QQabAvnYbW](https://user-images.githubusercontent.com/57675820/229317029-a8dfa428-eec5-4fd9-ab70-a2688617401c.jpg)

**Comment by Wolffenstein** [comment]
Fixed in rev 3729.
