### ISSUE TITLE
[Spell][Priest] Shadowfiend keeps PW:Shield from previous summon.

### ISSUE THREAD

**Issue by Vfonw** [Atlantiss/NetherwingBugtracker#8273]
**Description**: Shadowfiend seems to keep Power Word: Shield when it doesn't die, but just despawns from timer running out.
Also noticed it stays on aggressive every time it's summoned no matter if manually set to defensive or passive mode.

**Current behaviour**: Shadowfiend keeps buff(s?) it had when it despawns from timer running out.

**Expected behaviour**: Not sure if it's intended, but probably isn't?

**Server Revision**: 3728

**Comment by Wolffenstein** [comment]
Fixed in rev 3729.
