### ISSUE TITLE
[Core][Mob] Running away last hit

### ISSUE THREAD

**Issue by tsu-1** [Atlantiss/NetherwingBugtracker#8274]
[//]: # (Enclose links to things related to the bug using http://wowhead.com or any other TBC database.)
[//]: # (You can use screenshot ingame to visual the issue.)
[//]: # (Write your tickets according to the format:)
[//]: # ([Quest][Azuremyst Isle] Red Snapper - Very Tasty!)
[//]: # ([NPC] Magistrix Erona)
[//]: # ([Spell][Mage] Fireball)
[//]: # ([Npc][Drop] Ghostclaw Lynx)
[//]: # ([Web] Armory doesnt work)
[//]: # (To find server revision type `.server info` command in the game chat.)

**Description**: Mobs hit you from great distance

**Current behaviour**: When you are running away from mob, and even get out of his melee range, he will hit you last time just before losing aggro even though he might be 100 yards away.

**Expected behaviour**: Not hit when not in melee range.

**Server Revision**: 3728

**Comment by Wolffenstein** [comment]
clientside blizzlike bug
