### ISSUE TITLE
[Event][Stranglethorn Vale] Stranglethorn fishing extravaganza

### ISSUE THREAD

**Issue by runnerbois** [Atlantiss/NetherwingBugtracker#8276]
**Description**: Every sunday server time at 2 to 4 PM, there should be a fishing event in Stranglethorn Vale.

**Current behaviour**: The event doesn't start at all.
![sunday](https://user-images.githubusercontent.com/63441201/229355667-7152ac3d-8c69-4828-ab66-8b7cf6b8f533.jpg)

**Expected behaviour**: The event should start with the NPC announcing it and Tastyfish spawning around STV.

**Server Revision**:  3728

**Comment by Godmatik** [comment]
https://github.com/Atlantiss/NetherwingBugtracker/issues/960

**Comment by Wolffenstein** [comment]
Fixed in rev 3787.
