### ISSUE TITLE
[Quest][Nagrand] Blessing of Incineratus

### ISSUE THREAD

**Issue by Anfarru** [Atlantiss/NetherwingBugtracker#8278]
Link to quest: https://www.wowhead.com/tbc/quest=9805/blessing-of-incineratus
Item provided by quest: Living Fire

**Description**: 
Quest item Living Fire cannot be used in the southern hut.
Hut location: https://imgur.com/a/os09rKn

**Current behaviour**:
The quest item does not work anywhere inside or near the hut.

**Expected behaviour**: 
The quest item should be useable anywhere inside the hut.

**Server Revision**: 
3728

**Comment by Wolffenstein** [comment]
![image](https://user-images.githubusercontent.com/1576644/229469557-be9f071a-2ee2-452a-b5ed-f6bdfc9b2853.png)
Works fine for me.

**Comment by Wolffenstein** [comment]
Fixed in rev 3729.
