### ISSUE TITLE
[Core] Instances not resetting on their own

### ISSUE THREAD

**Issue by Godmatik** [Atlantiss/NetherwingBugtracker#8279]
**Current/Expected behaviour**:
Instances don't appear to reset on their own when everyone has exited it. 

As I understand based on what I have read and also observed from classic - it should reset 30 minutes or so after everyone is not inside. But this is not happening and it can only happen if either a manual reset is done or the lockout resets (for heroics and such)

**Server Revision**: 
3728

https://wowwiki-archive.fandom.com/wiki/Instance_reset#:~:text=A%20hard%20reset%20is%20when,cannot%20be%20hard%20reset%20manually.

**Comment by Wolffenstein** [comment]
Hopefully fixed in rev 3729.
