### ISSUE TITLE
[Spell][Mocking Blow] Corporal Keeshan

### ISSUE THREAD

**Issue by Mewmewww** [Atlantiss/NetherwingBugtracker#828]
[//]: # (Enclose links to things related to the bug using http://wowhead.com or any other TBC database.)
[//]: # (You can use screenshot ingame to visual the issue.)
[//]: # (Write your tickets according to the format:)
[//]: # ([Quest][Azuremyst Isle] Red Snapper - Very Tasty!)
[//]: # ([NPC] Magistrix Erona)
[//]: # ([Spell][Mage] Fireball)
[//]: # ([Npc][Drop] Ghostclaw Lynx)
[//]: # ([Web] Armory doesnt work)

**Description**: Corporal Keeshan spells

**Current behaviour**: Using Mocking blow but mobs arent taunted.

**Expected behaviour**: Should be taunted

**Server Revision**: 2078

**Comment by Evolvee** [comment]
![image](https://user-images.githubusercontent.com/1942409/46300618-7438fb80-c5a4-11e8-82a1-a93328e22aca.png)

**Comment by Wolffenstein** [comment]
Fixed in rev 3389.
