### ISSUE TITLE
[NPC] Farahlon Crumbler

### ISSUE THREAD

**Issue by Godmatik** [Atlantiss/NetherwingBugtracker#8280]
**Current behaviour**:
Farahlon Crumblers - which are the adds that spawn off of Farahlon Giants in Netherstorm when you fight them, if they reset they don't ever despawn.

**Expected behaviour**: 
They should eventually despawn if they are reset and not killed off

**Server Revision**: 
3728

https://www.wowhead.com/tbc/npc=21077/farahlon-crumbler

![Crumbler](https://user-images.githubusercontent.com/37913400/229388726-75893080-ef98-4e6f-b479-8240f8c85d32.png)

**Comment by Wolffenstein** [comment]
Fixed in rev 3729.
