### ISSUE TITLE
[Loot][Enchanting] Disenchanting loot is lost if the loot window is closed.

### ISSUE THREAD

**Issue by Vfonw** [Atlantiss/NetherwingBugtracker#8282]
**Description**:  If the window with the shard/dust/essence from a disenchant is closed either by action or DC, the loot is gone. I think it used to auto-loot into your bags in this case.

**Current behaviour**: Disenchant loot is gone if the loot window is closed in any way.

**Expected behaviour**: The contents of the disenchant loot window goes into your bag if you have room if it is closed.

**Server Revision**: 3728

**Comment by Wolffenstein** [comment]
That change was made in later expansions, in TBC the loot is lost once you close the disenchant window.
