### ISSUE TITLE
[Spell][Priest] Mind Vision has no way of being cancelled.

### ISSUE THREAD

**Issue by Vfonw** [Atlantiss/NetherwingBugtracker#8283]
**Description**:  Mind Vision has no way of being cancelled, forcing the user to sit the full 1 minute duration to resume control of your character.

**Current behaviour**: Esc, Moving, Jumping, Rightclicking, /stopcasting -  nothing seems to be able to break the effect on the Priest casting it.

**Expected behaviour**: While using Mind Vision, movement should still move your character, and therefore stop the cast since it's a channel being interrupted by your characters movement. 
Esc or /stopcasting should also work. 

**Server Revision**: 3728

**Comment by Wolffenstein** [comment]
Fixed in rev 3729.
