### ISSUE TITLE
[NPC] Death Knight Darkreaver

### ISSUE THREAD

**Issue by Anfarru** [Atlantiss/NetherwingBugtracker#8284]
**Description**: 
NPC Death Knight Darkreaver is required for the fast paladin mount. He is supposed to use abilities.
https://www.wowhead.com/tbc/npc=14516/death-knight-darkreaver#abilities;mode:normal

**Current behaviour**:
He does nothing but auto attack every 1.5 seconds.
Recount showing damage sources: https://imgur.com/a/Okfslc0

**Expected behaviour**: 
He should attack less often and use some abilities.

**Server Revision**: 
3728

**Comment by EtheriousNW** [comment]
Fixed in strat rework
