### ISSUE TITLE
[Quest][Alchemy] Master of Elixirs 

### ISSUE THREAD

**Issue by runnerbois** [Atlantiss/NetherwingBugtracker#8287]
**Description**:  You have to loot 10 [essences](https://www.wowhead.com/tbc/item=31753/essence-of-infinity) from [keepers](https://www.wowhead.com/tbc/npc=21104/rift-keeper) and [lords](https://www.wowhead.com/tbc/npc=21140/rift-lord) that spawn each wave.

**Current behaviour**: Sometimes the essences cannot be looted, even if I'm the only one with the quest in the instance: 
![WoWScrnShot_040323_201139](https://user-images.githubusercontent.com/63441201/229593657-3de291a5-b12f-4828-8673-6868eb7a51e6.jpg)
![WoWScrnShot_040323_200454](https://user-images.githubusercontent.com/63441201/229593677-147164f0-9103-49e1-9642-bbc06a2e184c.jpg)
![WoWScrnShot_040323_193814](https://user-images.githubusercontent.com/63441201/229593724-674321d7-37ba-493e-90ea-e29526b39827.jpg)
![WoWScrnShot_040323_194001](https://user-images.githubusercontent.com/63441201/229593804-6d5da17c-e5bd-4e25-ae88-05c2261efdd4.jpg)

**Expected behaviour**: I should be able to loot the quest items off the mobs.

**Server Revision**:   3728

**Comment by Godmatik** [comment]
Confirmed, work-around is to set it to FFA loot.

Doesn't seem to always happen either.

**Comment by Godmatik** [comment]
Only bugs in heroic

**Comment by Godmatik** [comment]
I think it's attempting to loot share if someone else is an alchemy in the group even if they aren't on the quest

**Comment by Wolffenstein** [comment]
Fixed in rev 3759.
