### ISSUE TITLE
Shields are too small on Undead Male

### ISSUE THREAD

**Issue by Asparagoose** [Atlantiss/NetherwingBugtracker#8288]
**Description**: 
Shields are too small on Undead when sheathed on the back. In combat, the size is correct, but worn on the back out combat, it shrinks and looks awful. This significantly impacts how it feels to play Undead Warrior etc.

Example pictures: https://imgur.com/a/3wghbWh

**Current behaviour**:
Shields are too small when sheathed / worn on the back.

**Expected behaviour**: 
Shields should be larger when sheathed on Undead Male characters

**Server Revision**: 
3728

**Comment by Wolffenstein** [comment]
its clientside and not a bug...
