### ISSUE TITLE
Allow summons to Netherstorm/TK as long as the person getting summoned has riding learned. Same way you cannot summon someone into HCS that doesn't have key.

### ISSUE THREAD

**Issue by Soujin1337** [Atlantiss/NetherwingBugtracker#8289]
[//]: # (Enclose links to things related to the bug using http://wowhead.com or any other TBC database.)
[//]: # (You can use screenshot ingame to visual the issue.)
[//]: # (Write your tickets according to the format:)
[//]: # ([Quest][Azuremyst Isle] Red Snapper - Very Tasty!)
[//]: # ([NPC] Magistrix Erona)
[//]: # ([Spell][Mage] Fireball)
[//]: # ([Npc][Drop] Ghostclaw Lynx)
[//]: # ([Web] Armory doesnt work)
[//]: # (To find server revision type `.server info` command in the game chat.)

**Description**: 
Right now, the game feels incredibly bad doing any TK dungeon due to summons. Whether someone has to repair mid deep run or having to summon someone hearthing to shatt etc. If we are going to have a custom server option of no-summon due to flying mount, can we at least have a custom fix to allow IF they have a flying mount learned. Same way you cannot summon people without key into HC's.
**Current behaviour**:

**Expected behaviour**: 

**Server Revision**:

**Comment by Godmatik** [comment]
FYI it was not a "custom server option" this was Blizzlike in original TBC until patch 2.4 that you could not summon to the zone, 

Blizz just didn't follow the proper patches for classic and so this was overlooked by them (among many other things)

**Comment by Godmatik** [comment]
FYI it was not a "custom server option" this was Blizzlike in original TBC until patch 2.4. I believe Blizz even had that in classic for a while.

**Comment by Wolffenstein** [comment]
Neither a bug nor a custom option
