### ISSUE TITLE
[NPC] Missing Reef Sharks in Theramore docks.

### ISSUE THREAD

**Issue by Firroth** [Atlantiss/NetherwingBugtracker#829]
[NPC] Reef Shark https://www.wowhead.com/npc=12123/reef-shark

**Current behaviour**:
They aren't in-game now.

**Expected behaviour**: 
They should be in-game now swimming in Theramore docks rather than https://www.wowhead.com/npc=4388/young-murk-thresher and removed and swapped with https://www.wowhead.com/npc=4388/young-murk-thresher when patch 2.3 goes live.

![screenshot_2](https://user-images.githubusercontent.com/43505196/46223985-3eea9e80-c355-11e8-899d-012edff0e592.png)
![screenshot_3](https://user-images.githubusercontent.com/43505196/46224010-54f85f00-c355-11e8-8292-0c94576ac55a.png)

**Server Revision**: 
2078

**Comment by aresbrutus** [comment]
The sharks have already been added in the game. Theramore sharks are https://www.wowhead.com/npc=5434/coral-shark#comments

Reef sharks never were in Theramore: https://i.imgur.com/ofp9qjl.png

But the Theramore sharks are there!

**Comment by Firroth** [comment]
I'm 100% sure there were a couple of sharks in theramore docks before patch 2.3
If someone fallen from the dock / boat he mostly died then by those, before he reached the land.

You are right, they were named Coral sharks but smaller versions and lvl 42+ elite. I thought it was reef sharks cause I saw today huge shark (around gruul/magtheridon's size xD) swimming around dustwallow marsh (elite 62lvl I think since it had ?? lvl") so I thought it didn't had "smaller" and "lower lvl" versions of it.

Only video I found showing a shark in docks is this one:  
https://www.youtube.com/watch?v=5eLNGfELRLM
Too bad he lived long enough to show only 1 swimming around the docks, since there were at least 5-6 for sure.

But I'm pretty sure anyone who played alliance during vanilla / pre 2.3 patch will remember it, asked on guild chat today, and a lot of people confirmed it.

**Comment by aresbrutus** [comment]
We added 3 sharks nearby, but only 1 patrols under it right now. If there is more proof I can take a look at it . But we are not going to replace 2.3 mobs with pre-2.3 mobs just because.

**Comment by Firroth** [comment]
I don't know if this will be good proof enough, since it's from another private server - from vanilla. But on it you can see "28 sharks" total in theramore.

https://vanilla-twinhead.twinstar.cz/?npc=5434#.

Will try to look for more proofs, but since during "vanilla/tbc" videos were scarce cause of bad computers back then, it will be pretty hard if not impossible.

**Comment by Easyfraggy** [comment]
The problem with these is that they interfere with quest added in 2.3 in the bay area if you add them all. In fact in 2.3 they were all removed, We chose to keep some for that vanilla nostalgia of getting killed by sharks, but really messes up the thresher quest if you add them all.

**Comment by aresbrutus** [comment]
Retail map pre-2.3 https://i.imgur.com/EiwCVZ8.jpg

So yeah, confirming that they were there but like Easy said, we are keeping 2.4.3 version of levelling so we won't add them back. Thanks for the report though.
