### ISSUE TITLE
[Hunter] Pet skillbook missing, pet doesn't have abilities

### ISSUE THREAD

**Issue by Niselle** [Atlantiss/NetherwingBugtracker#8290]
[//]: # (Enclose links to things related to the bug using http://wowhead.com or any other TBC database.)
[//]: # (You can use screenshot ingame to visual the issue.)
[//]: # (Write your tickets according to the format:)
[//]: # ([Quest][Azuremyst Isle] Red Snapper - Very Tasty!)
[//]: # ([NPC] Magistrix Erona)
[//]: # ([Spell][Mage] Fireball)
[//]: # ([Npc][Drop] Ghostclaw Lynx)
[//]: # ([Web] Armory doesnt work)
[//]: # (To find server revision type `.server info` command in the game chat.)

**Description**: 
No pet's spellbook tab or any of his skills on pet bar. Happens to all of my pets, I only see their tab once per pet right after taming it, after first dismiss or deposit to stable they disappear

![image](https://user-images.githubusercontent.com/129809569/229659521-10127b98-c76b-4e8c-a31d-60fb55114a9a.png)

**Comment by Godmatik** [comment]
You need to complete the taming quest completely by going to the main city, such as:
https://www.wowhead.com/classic/quest=6081/training-the-beast

**Comment by Niselle** [comment]
I did finish it, I have rewards for finishing that chain which is training pet, feeding and reviving it

**Comment by ivvivvi** [comment]
> You need to complete the taming quest completely by going to the main city, such as: https://www.wowhead.com/classic/quest=6081/training-the-beast

Obviously they already finished the quest, since they can tame/dismiss pets. And you can see the rare spawn lion on screen.

**Comment by Godmatik** [comment]
Tame and dismiss pets are abilities you learn when you do the taming quest.

The other abilities you learn such as feed pet and beast skills you don't get until you turn it in at the class trainer in your main city. I just leveled a hunter and it's correct.

**Comment by Godmatik** [comment]
Yeah you are correct I misunderstood.

Can you disable all addons and see if it is still the case? Also - with the game client closed - delete the cache folder.

I just leveled a hunter and don't have the same issues, also we have hundreds and hundreds of hunters on the server so if this was a widespread problem it would've been reported a long time ago.

**Comment by Niselle** [comment]
Thanks for trying to help, I tried both things, neither helped.. Of all the hunters on the server it had to happen to me, just my luck

**Comment by Godmatik** [comment]
I would suggest DMing Etherious in the discord, he is the head GM and can maybe take a closer look for you.
