### ISSUE TITLE
Dual Spec Rank issues

### ISSUE THREAD

**Issue by Bugsterport** [Atlantiss/NetherwingBugtracker#8292]
[//]: # (Enclose links to things related to the bug using http://wowhead.com or any other TBC database.)
[//]: # (You can use screenshot ingame to visual the issue.)
[//]: # (Write your tickets according to the format:)
[//]: # ([Quest][Azuremyst Isle] Red Snapper - Very Tasty!)
[//]: # ([NPC] Magistrix Erona)
[//]: # ([Spell][Mage] Fireball)
[//]: # ([Npc][Drop] Ghostclaw Lynx)
[//]: # ([Web] Armory doesnt work)
[//]: # (To find server revision type `.server info` command in the game chat.)

**Description**:
When using your Dualspec feature there is a bug whenever you respec.
**Current behaviour**:
If you have multiple ranks of a spell on your action bar it will default all of those spells to the max rank
**Expected behaviour**:
The Spell set on the action bar should be the same rank if i respec or not

**Comment by Wolffenstein** [comment]
already fixed
