### ISSUE TITLE
Veteran Uzzek Quest [Def Stance]

### ISSUE THREAD

**Issue by Xozell** [Atlantiss/NetherwingBugtracker#8293]
[//]: # ([Enclose links to things related to the bug using http://wowhead.com or any other TBC database.]
[//]: # (You can use screenshot ingame to visual the issue.)
[//]: # (Write your tickets according to the format:)
[//]: # ([Quest][Azuremyst Isle] Red Snapper - Very Tasty!)
[//]: # ([NPC] Magistrix Erona)
[//]: # ([Spell][Mage] Fireball)
[//]: # ([Npc][Drop] Ghostclaw Lynx)
[//]: # ([Web] Armory doesnt work)
[//]: # (To find server revision type `.server info` command in the game chat.)

**Description**:  Veteran Uzzek Quest not seen at any trainer
https://www.wowhead.com/tbc/quest=1505/veteran-uzzek

**Current behaviour**: It can't be found at any of the warrior trainers (according to wowhead)

**Expected behaviour**:  should be seen after lvl 10

**Server Revision**:

**Comment by gun4axb** [comment]
Uzzek is in the Barrens slightly south after crossing the bridge that leads to barrens.

61, 21 Barrens https://www.wowhead.com/tbc/npc=5810

**Comment by Wolffenstein** [comment]
This quest can only be done if you haven't already completed "Speak with Dillinger" quest.
