### ISSUE TITLE
deadly poison damage bug

### ISSUE THREAD

**Issue by mayday2013** [Atlantiss/NetherwingBugtracker#8294]
[//]: # (Enclose links to things related to the bug using http://wowhead.com or any other TBC database.)
[//]: # (You can use screenshot ingame to visual the issue.)
[//]: # (Write your tickets according to the format:)
[//]: # ([Quest][Azuremyst Isle] Red Snapper - Very Tasty!)
[//]: # ([NPC] Magistrix Erona)
[//]: # ([Spell][Mage] Fireball)
[//]: # ([Npc][Drop] Ghostclaw Lynx)
[//]: # ([Web] Armory doesnt work)
[//]: # (To find server revision type `.server info` command in the game chat.)

**Description**: 
this poison hits for 1000+ everu tick, probably doing full dmg in 1 tick, not 6
**Current behaviour**:
deals 6 times more mdg
**Expected behaviour**: 
normal dmg
**Server Revision**: 
https://youtu.be/2SHrfIyLJKQ video

**Comment by mayday2013** [comment]
he might have bugged it somehow

**Comment by tsu-1** [comment]
Spell Power rogue, maybe scalling is off? https://logs.stormforge.gg/character/netherwing/zusu

**Comment by Godmatik** [comment]
Deadly poison currently has a 50% co-efficient from spell damage, according to this post:

https://github.com/Atlantiss/NetherwingBugtracker/issues/7985

No idea if blizzlike or not.

**Comment by Wolffenstein** [comment]
Fixed in rev 3732.
