### ISSUE TITLE
Auction full scan with QueryAuctionItems getAll parameter set to true does not work

### ISSUE THREAD

**Issue by RichSteini** [Atlantiss/NetherwingBugtracker#8295]
[//]: # (Enclose links to things related to the bug using http://wowhead.com or any other TBC database.)
[//]: # (You can use screenshot ingame to visual the issue.)
[//]: # (Write your tickets according to the format:)
[//]: # ([Quest][Azuremyst Isle] Red Snapper - Very Tasty!)
[//]: # ([NPC] Magistrix Erona)
[//]: # ([Spell][Mage] Fireball)
[//]: # ([Npc][Drop] Ghostclaw Lynx)
[//]: # ([Web] Armory doesnt work)
[//]: # (To find server revision type `.server info` command in the game chat.)

**Description**: 
Using QueryAuctionItems with getAll parameter set to true does not do anything even though CanSendAuctionQuery does return true for the canMassQuery parameter. 

API description links for the functions/events:
[QueryAuctionItems](https://web.archive.org/web/20100106000804/http://wowprogramming.com/docs/api/QueryAuctionItems)
[CanSendAuctionQuery](https://web.archive.org/web/20100105225043/http://wowprogramming.com/docs/api/CanSendAuctionQuery)
[AUCTION_ITEM_LIST_UPDATE event](https://web.archive.org/web/20110524011459/http://wowprogramming.com/docs/events/AUCTION_ITEM_LIST_UPDATE)

Simple (addon) source code to reproduce the behaviour (use /testaddon to send query):
```
local TestAddon = CreateFrame("frame", "TestAddonFrame");

-- Register slash commands
SLASH_TEST1 = "/testaddon"
SlashCmdList["TEST"] = function(msg)
	local canQuery, canQueryAll = CanSendAuctionQuery()
	if canQueryAll then
		QueryAuctionItems ("", nil, nil, 0, 0, 0, 0, 0, 0, true);
	else
		print("Cannot query all")
	end
end

local function TestAddon_OnEvent(self, event, ...)
	if event == "AUCTION_ITEM_LIST_UPDATE" then
		print("Fullscan received")
		local numBatchAuctions, totalAuctions = GetNumAuctionItems("list")
		for i = 1, numBatchAuctions do
			local name, texture, count, quality, canUse, level, minBid, minIncrement, buyoutPrice, bidAmount, highestBidder, owner, sold = GetAuctionItemInfo("list", i)
			-- parse items
		end
	end
end

-- Register events
TestAddonFrame:SetScript("OnEvent", TestAddon_OnEvent);
TestAddonFrame:RegisterEvent("AUCTION_ITEM_LIST_UPDATE")
```

**Current behaviour**:
Right now after calling QueryAuctionItems with getAll parameter set to true the event "AUCTION_ITEM_LIST_UPDATE" never fires and either the game crashes or the player gets disconnected after approx. 1-2 minutes. When the auction house window is closed during the scan, then logging out does not work and in general no in-game interactions seem to work anymore.

**Expected behaviour**: 
When CanSendAuctionQuery returns true for the canMassQuery parameter then QueryAuctionItems can be called with getAll parameter set to true and a single page with all auction listings can be retrieved after "AUCTION_ITEM_LIST_UPDATE" fires.
![grafik](https://user-images.githubusercontent.com/50737013/229869012-26c093bd-2a3e-416a-bc9d-a1ba8d39b350.png)

**Server Revision**:
3730

**Comment by Wolffenstein** [comment]
Fixed in rev 3732.
