### ISSUE TITLE
[PvP][Warsong Gulch] Allied Flag Carrier invisible

### ISSUE THREAD

**Issue by Nihaobeachez** [Atlantiss/NetherwingBugtracker#8296]
[//]: # (Enclose links to things related to the bug using http://wowhead.com or any other TBC database.)
[//]: # (You can use screenshot ingame to visual the issue.)
[//]: # (Write your tickets according to the format:)
[//]: # ([Quest][Azuremyst Isle] Red Snapper - Very Tasty!)
[//]: # ([NPC] Magistrix Erona)
[//]: # ([Spell][Mage] Fireball)
[//]: # ([Npc][Drop] Ghostclaw Lynx)
[//]: # ([Web] Armory doesnt work)
[//]: # (To find server revision type `.server info` command in the game chat.)

**Description**:  Recently it was changed that the Flag Carriers appears 45 seconds after he picked up the Flag on the Map, but currently its not just for the Enemy Flag, but also for the allied one

**Current behaviour**:  Both Flag Carries are 45 seconds invisible.
![image](https://user-images.githubusercontent.com/96308500/229927802-db722a39-46f6-4d5c-973e-b7ad5b75d48e.png)
 Pink Spot in the South (1) is our Flag Carry

**Expected behaviour**:  Allied Flag Carrier should be seen on the Map

**Server Revision**:

**Comment by Wolffenstein** [comment]
Fixed in rev 3732.
