### ISSUE TITLE
[Spell] Dispelling Shadows Embrace in MT HC with Grounding Totem up kills the totem.

### ISSUE THREAD

**Issue by Vfonw** [Atlantiss/NetherwingBugtracker#8297]
**Description**: Dispelling [Shadows Embrace](https://www.wowhead.com/tbc/spell=34922/shadows-embrace) on a friendly player while a grounding totem is present from a shaman in the party will first target the totem, despite the dispel being a helpful dispel on a friendly player with the debuff.
Shadows Embrace is cast by Nexus Terror.

**Current behaviour**: Dispelling Shadows Embrace cast by Nexus Terror from a friendly target while a Grounding Totem is present in the party makes the Grounding totem take the dispel, killing the grounding totem and forcing a 2nd gcd use to dispel the debuff from a friendly player.

**Expected behaviour**: A friendly grounding totem shouldn't ground a friendly dispel to remove a debuff.

**Server Revision**: 3728

**Comment by adambcurrier** [comment]
Had this happen to me just now in a Mana Tombs run. Dispelling Shadows Embrace would kill the totem, create a combat text notification to that effect, and then require a second dispel. It did not happen with other hostile spell effects like Immolate during the run.

**Comment by Wolffenstein** [comment]
Was fixed
