### ISSUE TITLE
[Quest][Item] Bloodpetal Poison - Gorishi Sting

### ISSUE THREAD

**Issue by tsu-1** [Atlantiss/NetherwingBugtracker#8299]
[//]: # (Enclose links to things related to the bug using http://wowhead.com or any other TBC database.)
[//]: # (You can use screenshot ingame to visual the issue.)
[//]: # (Write your tickets according to the format:)
[//]: # ([Quest][Azuremyst Isle] Red Snapper - Very Tasty!)
[//]: # ([NPC] Magistrix Erona)
[//]: # ([Spell][Mage] Fireball)
[//]: # ([Npc][Drop] Ghostclaw Lynx)
[//]: # ([Web] Armory doesnt work)
[//]: # (To find server revision type `.server info` command in the game chat.)

**Description**: Gorishi Sting quest item drop rate https://www.wowhead.com/classic/item=22435/gorishi-sting

**Current behaviour**: Currently even with the dynamic quest item drop rate system added, the drop rate is really terrible. I killed 8 mobs for only 1 sting.

**Expected behaviour**: Drop rate of Gorishi Sting should be increased.

**Server Revision**: 3732

**Comment by Wolffenstein** [comment]
It's already higher than wowhead
