### ISSUE TITLE
Character naming parameters not set

### ISSUE THREAD

**Issue by Maginerk** [Atlantiss/NetherwingBugtracker#83]
[//]: # (Enclose links to things related to the bug using http://wowhead.com or any other TBC database.)
[//]: # (You can use screenshot ingame to visual the issue.)
[//]: # (Write your tickets according to the format:)
[//]: # ([Quest][Azuremyst Isle] Red Snapper - Very Tasty!)
[//]: # ([NPC] Magistrix Erona)
[//]: # ([Spell][Mage] Fireball)
[//]: # ([Npc][Drop] Ghostclaw Lynx)
[//]: # ([Web] Armory doesnt work)

**Description**: 
Currently looking at a character with the name "?"
**Current behaviour**:
A player is named "?"
**Expected behaviour**: 
Names should not be allowed to have symbols in them and must be at least 3 characters long
![wowscrnshot_092218_194548](https://user-images.githubusercontent.com/43503422/45922660-5979cf00-bea0-11e8-961f-985772ca407a.jpg)

**Server Revision**:

**Comment by Emtec** [comment]
Need only config reload.
