### ISSUE TITLE
[Quest][Angry Scytheclaws] The last raptor feather is very hard to get

### ISSUE THREAD

**Issue by jason-christian-92** [Atlantiss/NetherwingBugtracker#830]
[//]: # (Enclose links to things related to the bug using http://wowhead.com or any other TBC database.)
[//]: # (You can use screenshot ingame to visual the issue.)
[//]: # (Write your tickets according to the format:)
[//]: # ([Quest][Azuremyst Isle] Red Snapper - Very Tasty!)
[//]: # ([NPC] Magistrix Erona)
[//]: # ([Spell][Mage] Fireball)
[//]: # ([Npc][Drop] Ghostclaw Lynx)
[//]: # ([Web] Armory doesnt work)

**Description**: The quest requires 3 feather from any sunscale raptors. I have obtained 2 feathers within 5-6 raptors, but haven't got the last feather, despite killing raptors from the raptor den and the breeding ground where the egg lies twice (30+). I do not know whether it's just my luck or something wrong with drop rate

**Current behaviour**: The last feather has very very small drop chance

**Expected behaviour**: Feathers should be obtainable with the same chance each.

**Server Revision**: Forgot the revision, but this problem has been there since 27.Sept.2018

**Comment by Dpthx** [comment]
you were just lucky to get the first two fast.

**Comment by Jezofine** [comment]
#376

**Comment by aresbrutus** [comment]
Duplicate.
