### ISSUE TITLE
Auction house full scan with QueryAuctionItems getAll parameter set to true only yields the first 50 items

### ISSUE THREAD

**Issue by RichSteini** [Atlantiss/NetherwingBugtracker#8300]
[//]: # (Enclose links to things related to the bug using http://wowhead.com or any other TBC database.)
[//]: # (You can use screenshot ingame to visual the issue.)
[//]: # (Write your tickets according to the format:)
[//]: # ([Quest][Azuremyst Isle] Red Snapper - Very Tasty!)
[//]: # ([NPC] Magistrix Erona)
[//]: # ([Spell][Mage] Fireball)
[//]: # ([Npc][Drop] Ghostclaw Lynx)
[//]: # ([Web] Armory doesnt work)
[//]: # (To find server revision type `.server info` command in the game chat.)

**Description**: 
Auction house full scan with QueryAuctionItems getAll parameter set to true still does not work as expected, it returns the correct amount of totalAuctions, but numBatchAuctions is not equal to totalAuctions as it should be.

API function links (different reference with more information):
[GetNumAuctionItems](https://wowwiki-archive.fandom.com/wiki/API_GetNumAuctionItems?oldid=1020054)
[GetAuctionItemInfo](https://wowwiki-archive.fandom.com/wiki/API_GetAuctionItemInfo?oldid=1722981)
[QueryAuctionItems](https://wowwiki-archive.fandom.com/wiki/API_QueryAuctionItems?oldid=1566002)

**Current behaviour**:
The event "AUCTION_ITEM_LIST_UPDATE" fires now correctly when QueryAuctionItems is called with getAll parameter set to true, but when querying ```numBatchAuctions, totalAuctions = GetNumAuctionItems("list")```, then numBatchAuctions is only equal to 50 instead of being equal to totalAuctions, i.e., only the first 50 listings are obtainable (you can only query with ```getAll = true``` every 15 mins, so you cannot query multiple pages that way). This is also consistent when ```GetAuctionItemInfo("list", i)``` with ``` i > 50``` is called then it returns always nil, even though ``` totalAuctions > 50 ``` (everything above 50 is not included in the batch).

**Expected behaviour**: 
When "AUCTION_ITEM_LIST_UPDATE"  fires then ```numBatchAuctions == totalAuctions``` (the entire auction house in one single page) if QueryAuctionItems was called with ```getAll = true```. One single page means that you can obtain all items of the auction house in a single batch with a single QueryAuctionItems function call with getAll parameter set to true. Note: This behaviour is only correct for the getAll query, if ```getAll = false```, then ```numBatchAuctions <= 50``` is indeed correct. 

**Server Revision**: 
3732

**Comment by Wolffenstein** [comment]
I honestly don't know how to solve this, the AH packet just doesn't accept more than 50 items in one bulk, If I send the entire thing in one go the client dies. I would have to see a video of how it works in classic/2007

**Comment by RichSteini** [comment]
Was it implemented like that before i reported it yesterday? I don't really understand what the video can/should show, you could only derive how long a full scan took in 2007? Maybe they have sent multiple events for one getAll query with smaller batches, but the wiki does not really suggest anything like that. The question is: Can you server side successively add data to the client side listing, what i mean by that is as an example if i am parsing listing number 1-1000 right now (first batch) and you send the second event with number 1001-2000 listing, is it possible that the 1-1000 data stays available after the second batch has been sent (without handshake you would have to keep the data available since you don't know if the client is done parsing already)? Is it just about the amount of data or could maybe throttling the datastream server side solve the issue?

There always exists the client side workaround of course, where i just send a non-filtered (empty) auction query for all pages, but i am not sure whether the server would even allow that, as an example right now there are 35000 listings on the auction house, so 35000/50 means 700 queries, would that be allowed in a reasonable amount of time (~30 seconds or something)? How would you have intended it to be handled client side for the way it is implemented right now server side, send ```QueryAuctionItems ("", nil, nil, 0, 0, 0, 0, 0, 0, true)``` x700 with adjusted page argument?

**Comment by Wolffenstein** [comment]
Please try again in rev. 3749.
