### ISSUE TITLE
[Spell][Rogue] Cold Blood + Mutilate only guaranteeing Mainhand to crit

### ISSUE THREAD

**Issue by Massie323** [Atlantiss/NetherwingBugtracker#8302]
[//]: # (Enclose links to things related to the bug using http://wowhead.com or any other TBC database.)
[//]: # (You can use screenshot ingame to visual the issue.)
[//]: # (Write your tickets according to the format:)
[//]: # ([Quest][Azuremyst Isle] Red Snapper - Very Tasty!)
[//]: # ([NPC] Magistrix Erona)
[//]: # ([Spell][Mage] Fireball)
[//]: # ([Npc][Drop] Ghostclaw Lynx)
[//]: # ([Web] Armory doesnt work)
[//]: # (To find server revision type `.server info` command in the game chat.)

**Description**: 
Using Mutilate with Cold Blood active will only guarantee the Mainhand to 100% critically strike, leaving the offhand with normal crit-chance.

**Current behaviour**:
Mutilate + Cold Blood only crits with MH.

**Expected behaviour**: 
Mutilate + Cold Blood should crit with both hands.

**Server Revision**: 
3732

**Comment by tsu-1** [comment]
I might have found the weirdest proof of that. Here is the image from wowhead (tbc) exactly showing Mutilate and Cold Blood behaviour. You can see that the rogue used Cold Blood by the looks of blue sphere around his hands.

Source: https://www.wowhead.com/tbc/spell=34412/mutilate#screenshots:id=14946

![image](https://user-images.githubusercontent.com/11255782/232233841-11ea1ba7-35d9-4add-81d9-959f97c090da.png)

**Comment by tsu-1** [comment]
https://www.wowhead.com/tbc/spell=34412/mutilate#comments:id=9983

**Comment by Wolffenstein** [comment]
Fixed in rev 3830.
