### ISSUE TITLE
[PvP][Warsong Gulch]Allied Flag Carrier invisble on the Map, Enemy not

### ISSUE THREAD

**Issue by Nihaobeachez** [Atlantiss/NetherwingBugtracker#8303]
[//]: # (Enclose links to things related to the bug using http://wowhead.com or any other TBC database.)
[//]: # (You can use screenshot ingame to visual the issue.)
[//]: # (Write your tickets according to the format:)
[//]: # ([Quest][Azuremyst Isle] Red Snapper - Very Tasty!)
[//]: # ([NPC] Magistrix Erona)
[//]: # ([Spell][Mage] Fireball)
[//]: # ([Npc][Drop] Ghostclaw Lynx)
[//]: # ([Web] Armory doesnt work)
[//]: # (To find server revision type `.server info` command in the game chat.)

**Description**:  https://github.com/Atlantiss/NetherwingBugtracker/issues/8296

**Current behaviour**:  Enemy Flag visible on the Map right after they pickup the Flag. Allied one invisible on the Map.
![image](https://user-images.githubusercontent.com/96308500/230251346-ad2cff9b-7010-4098-b8f6-580c02308043.png)

**Expected behaviour**: Enemy shouldnt be visible right after they pickup Flag. Allied one should be.

**Server Revision**: 3732

**Comment by Wolffenstein** [comment]
bruh

**Comment by Wolffenstein** [comment]
Fixed in rev 3733.
