### ISSUE TITLE
[General][NPC] Caster NPC detection

### ISSUE THREAD

**Issue by tsu-1** [Atlantiss/NetherwingBugtracker#8305]
[//]: # (Enclose links to things related to the bug using http://wowhead.com or any other TBC database.)
[//]: # (You can use screenshot ingame to visual the issue.)
[//]: # (Write your tickets according to the format:)
[//]: # ([Quest][Azuremyst Isle] Red Snapper - Very Tasty!)
[//]: # ([NPC] Magistrix Erona)
[//]: # ([Spell][Mage] Fireball)
[//]: # ([Npc][Drop] Ghostclaw Lynx)
[//]: # ([Web] Armory doesnt work)
[//]: # (To find server revision type `.server info` command in the game chat.)

**Description**: Caster NPCs behaviour when stealthed players gets detected

**Current behaviour**: When stealthed/prowled player gets detected by an NPC who is a caster, It will target you (get you in combat) but won't perform any action until you get really close or attack the mob.
![image](https://user-images.githubusercontent.com/11255782/230477802-2c473a1e-53b7-477c-b9a8-1886cf6b1aab.png)

Notice that I am in stealth.

**Expected behaviour**: I expect mob to get me out of stealth if he targets me and force me into combat.

**Server Revision**: 3732

**Comment by Wolffenstein** [comment]
![image](https://user-images.githubusercontent.com/1576644/230772523-b21f28c3-0643-4496-bdb6-4f6019a4c273.png)
nope, must have been something else
