### ISSUE TITLE
Hunter's Mark

### ISSUE THREAD

**Issue by Krmacha** [Atlantiss/NetherwingBugtracker#8306]
Greetings. I wanna report a bug for Hunter's Mark. Once you apply Hunter's mark on target, you can't re apply it until effect expire. So for example if my hunter's mark expires in 45 seconds, I can't re apply it until those 45 seconds expire, or otherwise until effect is over. So I'm only able to use it on same target once every 2 minutes.

**Comment by Godmatik** [comment]
This is because when you attack a target with hunter's mark, there a progressive ranged AP buff you get on it, as the tooltip indicates. And the system is currently setup so a weaker Hunter's mark won't overwrite a more powerful one.

Not sure if blizzlike/intended though.

**Comment by Krmacha** [comment]
Can you fix it please? It's not intended to be that way.

**Comment by Wolffenstein** [comment]
Fixed in rev 3741.
