### ISSUE TITLE
[Core] Parry

### ISSUE THREAD

**Issue by Kuszki** [Atlantiss/NetherwingBugtracker#8307]
[//]: # (Enclose links to things related to the bug using http://wowhead.com or any other TBC database.)
[//]: # (You can use screenshot ingame to visual the issue.)
[//]: # (Write your tickets according to the format:)
[//]: # ([Quest][Azuremyst Isle] Red Snapper - Very Tasty!)
[//]: # ([NPC] Magistrix Erona)
[//]: # ([Spell][Mage] Fireball)
[//]: # ([Npc][Drop] Ghostclaw Lynx)
[//]: # ([Web] Armory doesnt work)
[//]: # (To find server revision type `.server info` command in the game chat.)

**Description**: Parry can occur only while weapon is equipped according to [this](https://www.wowhead.com/tbc/spell=3127/parry).

**Current behaviour**: You can parry attack unarmed (no weapon equipped), probably works while disarmed (didn't test yet). Tested on Warrior without any weapon.

**Expected behaviour**: Parry can occur only if weapon is equipped.

**Server Revision**: 4082

**Comment by Wolffenstein** [comment]
Fixed in rev 3739.
