### ISSUE TITLE
Skinning bug

### ISSUE THREAD

**Issue by Romisu** [Atlantiss/NetherwingBugtracker#8308]
[//]: # (Enclose links to things related to the bug using http://wowhead.com or any other TBC database.)
[//]: # (You can use screenshot ingame to visual the issue.)
[//]: # (Write your tickets according to the format:)
[//]: # ([Quest][Azuremyst Isle] Red Snapper - Very Tasty!)
[//]: # ([NPC] Magistrix Erona)
[//]: # ([Spell][Mage] Fireball)
[//]: # ([Npc][Drop] Ghostclaw Lynx)
[//]: # ([Web] Armory doesnt work)
[//]: # (To find server revision type `.server info` command in the game chat.)

**Description**: There is a bug related to skinning mobs that makes mobs unskinnable. If you are in a party or a raid and the monster drops an item that is rolled for, no monster can be skinned afterwards, if the other items that the mob dropped were looted before the roll was settled. This bug is particularly annoying with autoloot and solo hunting while forming a dungeon group or while in a dungeon.  

**Current behaviour**: Monster becomes unskinnable, if while in a party or a raid, other drops are looted from a skinnable monster, prior to an item roll being settled. Note that this bug does not apply to monsters, that dropped only the item that was rolled for.

**Expected behaviour**: All skinnable monsters should be skinnable regardless of the order the items were looted in.

**Server Revision**:

**Comment by Wolffenstein** [comment]
Fixed in rev 3834.
