### ISSUE TITLE
[Core][PvP] Racial Change visual overrides Shapeshifting models.

### ISSUE THREAD

**Issue by Massie323** [Atlantiss/NetherwingBugtracker#8310]
[//]: # (Enclose links to things related to the bug using http://wowhead.com or any other TBC database.)
[//]: # (You can use screenshot ingame to visual the issue.)
[//]: # (Write your tickets according to the format:)
[//]: # ([Quest][Azuremyst Isle] Red Snapper - Very Tasty!)
[//]: # ([NPC] Magistrix Erona)
[//]: # ([Spell][Mage] Fireball)
[//]: # ([Npc][Drop] Ghostclaw Lynx)
[//]: # ([Web] Armory doesnt work)
[//]: # (To find server revision type `.server info` command in the game chat.)

**Description**: 
Shapeshifted players (i.e. Druid forms/Ghost Wolf/Sheep) appear in their Racial Changed form. 

**Current behaviour**:
Shapeshifted players (i.e. Druid forms/Ghost Wolf/Sheep) appear in their Racial Changed form.

**Expected behaviour**: 
Players should appear in their Shapeshifted form.

**Server Revision**: 
3732

![Wow_kAQzzsNcsB](https://user-images.githubusercontent.com/57675820/230645877-0622be3f-7c25-420d-95b0-1565cba0a84a.png)
Screenshot showcasing a Nightelf-druid that Race-changed to Tauren, using Traveling Form but without the respective model.

**Comment by Wolffenstein** [comment]
Fixed in rev 3733.
