### ISSUE TITLE
[Battleground] You keep Berserker after leaving Battleground

### ISSUE THREAD

**Issue by tsu-1** [Atlantiss/NetherwingBugtracker#8312]
[//]: # (Enclose links to things related to the bug using http://wowhead.com or any other TBC database.)
[//]: # (You can use screenshot ingame to visual the issue.)
[//]: # (Write your tickets according to the format:)
[//]: # ([Quest][Azuremyst Isle] Red Snapper - Very Tasty!)
[//]: # ([NPC] Magistrix Erona)
[//]: # ([Spell][Mage] Fireball)
[//]: # ([Npc][Drop] Ghostclaw Lynx)
[//]: # ([Web] Armory doesnt work)
[//]: # (To find server revision type `.server info` command in the game chat.)

**Description**: Battleground buffs

**Current behaviour**: You keep the buffs from Battleground (Berserker/Speed/Regen) when BG finishes or you leave.

**Expected behaviour**: All Battleground related buffs should be cleared from the player when he leaves the instanced environemnt.

**Server Revision**: 3732

Was first Penetrant.

**Comment by Wolffenstein** [comment]
Fixed in rev 3738.
