### ISSUE TITLE
[Quest] Cleansing of the Orb of Orahil

### ISSUE THREAD

**Issue by ThaddeusMozart** [Atlantiss/NetherwingBugtracker#8313]
**Description**: 
Part of a warlock chain; timed quest in Dustwallow. Quest on wowhead: https://www.wowhead.com/classic/quest=4961/cleansing-of-the-orb-of-orahil
**Current behaviour**:
Warlock timed quest is causing game to crash. Game continues to immediately crash on login until quest timer expires, then the crashes end.
**Expected behaviour**: 
Not crashing
**Server Revision**: 
3732

**Comment by Godmatik** [comment]
Disable quest helper add-on
