### ISSUE TITLE
Elemental totems do not despawn after elemental dies

### ISSUE THREAD

**Issue by Aeded** [Atlantiss/NetherwingBugtracker#8314]
**Description**: 
Fire and earth elemental totems do not despawn after elemental dies
**Current behaviour**:
Fire and earth elemental totems do not despawn after elemental dies
**Expected behaviour**: 
Fire and earth elemental totems should despawn after elemental dies
https://www.youtube.com/watch?v=9uzvlvDzEs0&t=354s
elemental dies, totem on the bridge despawned
**Server Revision**: 3732

**Comment by Wolffenstein** [comment]
Fixed in rev 3838.
