### ISSUE TITLE
[core] auras should be gained / removed on spell cast succes not on spell hit

### ISSUE THREAD

**Issue by Aeded** [Atlantiss/NetherwingBugtracker#8315]
**Description**: 
Theres is a core issue where all auras are being gained on removed when spell lands rather then when spell is succesfully casted
For example  [Quagmirran's Eye] procs when lightning bolt reaches target, instead of when its succesfuly casted.
Another example is that Clearcasting aura is consumed when lightningbolt reaches target, instead of when its succesfuly casted

**Current behaviour**:
Effect auras are gained/removed on spell hit rather then spell cast
**Expected behaviour**: 
Effect auras should be gained/removed on spell cast success
**Server Revision**: 3732

**Comment by Wolffenstein** [comment]
It's a proc settings issue for those specific spells, not a global issue. Core-wise I have no way to distinguish between on-cast/on-hit procs because the proc data for spells only expects a harmful spell being done. You would have to report each of those separately
