### ISSUE TITLE
Mage Water Elemental

### ISSUE THREAD

**Issue by ghost** [Atlantiss/NetherwingBugtracker#8316]
Water Elemental can cast Water Bolts while under the effect of Psychic Scream.
No other effects were on the elemental when this happened today.
Revision: 3732

**Comment by tsu-1** [comment]
@th0-1 are you able to provide footage of that happening?

**Comment by ghost** [comment]
No, I didn't record the gameplay. It took place in Arathi Basin. The elemental was rapidly changing it's facing direction as it was shooting the bolts at me, while feared.

**Comment by Wolffenstein** [comment]
Can't reproduce
