### ISSUE TITLE
Steamvaults - Bugged mob can not find path - causes wipes

### ISSUE THREAD

**Issue by Godmatik** [Atlantiss/NetherwingBugtracker#8317]
**Description**: 
Re-upping an issue present on past two servers, hopefully a simple fix as it is wiping SV groups.

**Current behaviour**:
There is a pack of four mobs behind a pillar that is pulled when doing the standard route in the dungeon, however one of them gets stuck and is unable to find a path - the engineer - unless the tank moves into melee range of it. What happens is that "stuck" mob ends up aggroing one of the water elemental patrol packs and the group will likely wipe.

**Expected behaviour**: 
The mob should have a path when pulled and not be stuck behind a pillar.

**Server Revision**: 
3732

https://github.com/Atlantiss/NetherwingBugtracker/issues/3165
![image](https://user-images.githubusercontent.com/37913400/230732286-85cdd72c-76c2-4dd0-a13e-9aa5773345a0.png)

**Comment by Wolffenstein** [comment]
It is not a simple fix

**Comment by Wolffenstein** [comment]
Fixed in rev 3737.
