### ISSUE TITLE
Quest Tracker displays incorrect number of quest items obtained (possible fix included)

### ISSUE THREAD

**Issue by natiewow** [Atlantiss/NetherwingBugtracker#8318]
Quest tracker displays incorrect number of quest items, which breaks addons like QuestHelper. This issue was [fixed on Atlantiss](https://github.com/Atlantiss/NetherwingBugtracker/issues/6351) but appeared again on Stormforge.

**Comment by Wolffenstein** [comment]
Fixed in rev 3736.
