### ISSUE TITLE
[Spell][Shaman] Windfury Weapon

### ISSUE THREAD

**Issue by Healweed** [Atlantiss/NetherwingBugtracker#8319]
**Description**: 
I've been starting to notice that sometimes doing windfury weapon would lead to use instead rockbitter (even if you don't have it on your bars or just not binded at all). This can be frustrating as you may not notice that you have the wrong imbue for a certain amount of time

**Current behaviour**:

Doing Windfury Weapon would occasionally imbue with the wrong spell on the weapons (Rockbitter Weapon)

**Expected behaviour**: 
Windfury should be applied with the correct imbue(as well as the rank itself)

**Server Revision**: 
3732

**Comment by Wolffenstein** [comment]
??

**Comment by Healweed** [comment]
I don't know how it comes to happen but there's random times that does it. Like i said Rockbitter isnt on the bars or even binded and still does it but idk whats causing it

**Comment by Massie323** [comment]
Did you get mind-controlled at any point (I.e. Shadowlabs, Slavepens)? The mind-control AI will instantly apply Rockbiter to your weapons.

**Comment by Godmatik** [comment]
I've leveled as shaman before and never experienced, could be one of your add-ons maybe, also close game and delete cache folder

**Comment by Wolffenstein** [comment]
Not enough info for me to do anything.
