### ISSUE TITLE
Battle shout

### ISSUE THREAD

**Issue by Mewmewww** [Atlantiss/NetherwingBugtracker#832]
[//]: # (Enclose links to things related to the bug using http://wowhead.com or any other TBC database.)
[//]: # (You can use screenshot ingame to visual the issue.)
[//]: # (Write your tickets according to the format:)
[//]: # ([Quest][Azuremyst Isle] Red Snapper - Very Tasty!)
[//]: # ([NPC] Magistrix Erona)
[//]: # ([Spell][Mage] Fireball)
[//]: # ([Npc][Drop] Ghostclaw Lynx)
[//]: # ([Web] Armory doesnt work)

**Description**: Battle shout use

**Current behaviour**: Lower level battle shout overwrites stronger battle shout

**Expected behaviour**: Stronger battleshout should not be overwritten by lower level battle shout

**Server Revision**: 2078

**Comment by wtRCH** [comment]
Probably class-wide issue.

**Comment by Wolffenstein** [comment]
Fixed in rev 2145.
