### ISSUE TITLE
[Zone] Shattered Sun Offensive NPCs in Shattrath

### ISSUE THREAD

**Issue by tsu-1** [Atlantiss/NetherwingBugtracker#8320]
[//]: # (Enclose links to things related to the bug using http://wowhead.com or any other TBC database.)
[//]: # (You can use screenshot ingame to visual the issue.)
[//]: # (Write your tickets according to the format:)
[//]: # ([Quest][Azuremyst Isle] Red Snapper - Very Tasty!)
[//]: # ([NPC] Magistrix Erona)
[//]: # ([Spell][Mage] Fireball)
[//]: # ([Npc][Drop] Ghostclaw Lynx)
[//]: # ([Web] Armory doesnt work)
[//]: # (To find server revision type `.server info` command in the game chat.)

**Description**: Shattrath City NPCs

**Current behaviour**: Aldor Neophyte, Aldor Marksman, Aldor Anchorite, Grand Anchorite Almonen, Harbinger Haronem, Harbinger Argomen have wrong faction tied to them.

**Expected behaviour**: These NPCs should be Aldor faction related instead of Shattered Sun Offensive, before the patch that introduces the rep.

**Server Revision**: 3732

**Comment by tsu-1** [comment]
Update:
1. Emissary Mordin should also have his faction changed to Aldor.

**Comment by Wolffenstein** [comment]
will not be changed
