### ISSUE TITLE
[Spell] Shaman Clearcasting 

### ISSUE THREAD

**Issue by Massie323** [Atlantiss/NetherwingBugtracker#8322]
[//]: # (Enclose links to things related to the bug using http://wowhead.com or any other TBC database.)
[//]: # (You can use screenshot ingame to visual the issue.)
[//]: # (Write your tickets according to the format:)
[//]: # ([Quest][Azuremyst Isle] Red Snapper - Very Tasty!)
[//]: # ([NPC] Magistrix Erona)
[//]: # ([Spell][Mage] Fireball)
[//]: # ([Npc][Drop] Ghostclaw Lynx)
[//]: # ([Web] Armory doesnt work)
[//]: # (To find server revision type `.server info` command in the game chat.)

**Description**: 
Currently, Shaman's "Clearcasting" talent has a problem depending on how many stacks you have:
At 2/2 stacks of Clearcasting, it will only consume a stack upon a spell landing - This actually means if you have a Lightning Bolt traveling, and you crit with any Shock before it lands, said Lightning Bolt will consume a stack of Clearcast upon landing.
Alternatively, if you trigger a "Clearcast" proc with a CL or LB and a "Lightning Overload" proc, the Lightning Overload copy will consume a stack of a 2/2 Clearcast.

At 1/2 stacks of Clearcasting, it will only consume a stack upon a spell cast - which is the expected behaviour.

Additionally, there seems to be a visual issue (idk if it's client-based), where refreshing the proc will fail to display 2 stacks of the buff.

**Current behaviour**:
2/2 Clearcast gets consumed on Spell-Hit

Refreshing CC at 1 stacks will continue to display 1 stack (but correctly act as having 2).

**Expected behaviour**: 
2/2 and 1/2 Clearcast should always be instantly consumed per Spell-**cast**

Refreshing CC at 1 stack should display 2 stacks.

**Server Revision**: 
3732

https://user-images.githubusercontent.com/57675820/230795570-050f69c5-f86f-4028-b83e-07b410b1d59e.mp4

Video showcasing first Lightning Bolt consuming a CC stack on HIT, and second Lightning Bolt consuming a CC on CAST.

https://user-images.githubusercontent.com/57675820/230796019-21e0627c-3ac2-4ac3-a601-512dd459f444.mp4

Video showcasing CL crits applying a new CC proc, but still being displayed as a single stack - which doesn't disappear after casting a Shock.

**Comment by gun4axb** [comment]
https://youtu.be/UpjQRzSBnwI?t=47 

bugtracker is correct. The stack should be consumed on cast and should properly display if there are 2 stacks available.

**Comment by Godmatik** [comment]
More info is here:

https://github.com/Atlantiss/NetherwingBugtracker/issues/3601

Last comment on it states that it is perhaps a visual issue only
