### ISSUE TITLE
Mag. Summon Water Elemental

### ISSUE THREAD

**Issue by Alitros** [Atlantiss/NetherwingBugtracker#8323]
Hello my friends, 
Talent
https://www.wowhead.com/tbc/spell=31687/summon-water-elemental 

In the list of effects of the target spell 
https://www.wowhead.com/tbc/spell=33395/freeze
Summon-water-elemental talent 

It is displayed as an ally effect, this is not correct, Which means it does not show the time for which the effect is applied using the Omni CC addon.

**Comment by Wolffenstein** [comment]
Fixed in rev 3834.
