### ISSUE TITLE
Diplomacy racial

### ISSUE THREAD

**Issue by alandrar** [Atlantiss/NetherwingBugtracker#8325]
**Description**: Hello, diplomacy racial doesn't work on certain quests like "https://www.wowhead.com/tbc/quest=10298/hero-of-the-brood"
i'm human and my friend is gnome with switched racials to human. so it is not just for switched guys
**Current behaviour**: i gave us just 8000 rep

**Expected behaviour**: i guess, it should give us 8800 rep.

**Server Revision**: 3732

**Comment by tsu-1** [comment]
confirmed: https://www.wowhead.com/tbc/quest=10298/hero-of-the-brood#comments:id=114079

**Comment by Wolffenstein** [comment]
Fixed in rev 3741.
