### ISSUE TITLE
Gruul - Hateful strike visual

### ISSUE THREAD

**Issue by Godmatik** [Atlantiss/NetherwingBugtracker#8326]
**Current behaviour**:
Gruul does not do any visual cue when he does hateful strike ability on melee player who is 2nd on threat

**Expected behaviour**: 
Gruul should - very briefly - face the player he is using hateful strike on, before turning back and resuming melee on the highest threat target

**Server Revision**: 
3732

https://www.youtube.com/watch?v=qYJbPHZ9CIg&t=186s&ab_channel=Tetsu

**Comment by Wolffenstein** [comment]
Fixed in rev 3742.
