### ISSUE TITLE
Enchant Weapon - Major Healing visual bug?

### ISSUE THREAD

**Issue by Exacerbate** [Atlantiss/NetherwingBugtracker#8327]
![image](https://user-images.githubusercontent.com/9903804/231167985-9445205b-50a0-4254-a47b-9eedbc15e545.png)

Had my weapon "The Ancient Scepter of Sue-Min" enchanted with "Enchant Weapon - Major Healing" last night.
When inspecting my own weapon, I noticed the text of "+81 healing spells and +27 damage spells" was not green, but it was white and only says "81 healing spells". 

Now if I shift click the weapon to inspect or or compare it to itself, the text on the comparison appears correctly. I know it's a visual bug only because I was able to calculate the healing gained/lost when equipping/unequipping the item.

**Comment by Wolffenstein** [comment]
Bonus spell damage on many healing items was not added until patch 2.3.
