### ISSUE TITLE
Mark of Conquest trinket - proc rate way too high

### ISSUE THREAD

**Issue by SrryHunters** [Atlantiss/NetherwingBugtracker#8328]
**Current behaviour**:
Proc rate or Mark of Conquest trinket is much too high compared to blizzlike, like every 3rd/4th ranged shot, being abused by hunters in raids and they never go out of mana as a result.

**Expected behaviour**: 
Wowhead comments seem to indicate it's probably should be 3 PPM, but more research or data from classic might be needed. It needs to be drastically lowered from what it currently is though.

https://www.wowhead.com/wotlk/item=27921/mark-of-conquest#comments

**Comment by Wolffenstein** [comment]
Fixed in rev 3741.
