### ISSUE TITLE
Mobs bugged in Steamvaults 

### ISSUE THREAD

**Issue by RaptoRSec** [Atlantiss/NetherwingBugtracker#8329]
there is a problem pulling an specific pack of nagas behind a corner next to the doorway where there are 2 nagas placed there, this pack of nagas are bugged because when are pulled by the tank or any dps, there is one who just don't move and cause Water patrol get aggroed also and makes insta wipe that pull, this is the way to skip some mobs easy, i want to mention this bug was present since launch of Netherwing from Atlantiss and this never been fixed since now and all players now this pack is normal to get wiped.

**Comment by Godmatik** [comment]
Already fixed, just not live on servers yet
