### ISSUE TITLE
Pack of mobs with unlinked target

### ISSUE THREAD

**Issue by Erodraeda** [Atlantiss/NetherwingBugtracker#833]
[//]: # (Enclose links to things related to the bug using http://wowhead.com or any other TBC database.)
[//]: # (You can use screenshot ingame to visual the issue.)
[//]: # (Write your tickets according to the format:)
[//]: # ([Quest][Azuremyst Isle] Red Snapper - Very Tasty!)
[//]: # ([NPC] Magistrix Erona)
[//]: # ([Spell][Mage] Fireball)
[//]: # ([Npc][Drop] Ghostclaw Lynx)
[//]: # ([Web] Armory doesnt work)

**Description**: 
A mob that should be linked to the pack wasn't, in Razorfen Downs
**Current behaviour**:
![screenshot_496](https://user-images.githubusercontent.com/40346279/46228499-a21a0800-c338-11e8-8e4a-dfbc863bb336.png)
![screenshot_497](https://user-images.githubusercontent.com/40346279/46228822-b579a300-c339-11e8-8333-3dc908c49dcd.png)
![screenshot_498](https://user-images.githubusercontent.com/40346279/46228967-451f5180-c33a-11e8-8553-6e5123680dd5.png)
![screenshot_499](https://user-images.githubusercontent.com/40346279/46229062-a515f800-c33a-11e8-910a-7a7bd1c82125.png)
![screenshot_500](https://user-images.githubusercontent.com/40346279/46229160-0c33ac80-c33b-11e8-9992-718b3108f110.png)
![screenshot_501](https://user-images.githubusercontent.com/40346279/46229161-0c33ac80-c33b-11e8-8686-cb868d58739f.png)
**Expected behaviour**: 
Should have been pulled together, the mobs alone on the screenshots.
**Server Revision**:

**Comment by Tereneckla** [comment]
Fixed
