### ISSUE TITLE
[NPC] Stromgarde Defender evades when fighting on Stromgarde bridge

### ISSUE THREAD

**Issue by eunichron** [Atlantiss/NetherwingBugtracker#8331]
[//]: # (Enclose links to things related to the bug using http://wowhead.com or any other TBC database.)
[//]: # (You can use screenshot ingame to visual the issue.)
[//]: # (Write your tickets according to the format:)
[//]: # ([Quest][Azuremyst Isle] Red Snapper - Very Tasty!)
[//]: # ([NPC] Magistrix Erona)
[//]: # ([Spell][Mage] Fireball)
[//]: # ([Npc][Drop] Ghostclaw Lynx)
[//]: # ([Web] Armory doesnt work)
[//]: # (To find server revision type `.server info` command in the game chat.)

**Description**: 
The Stromgarde Defender that pats over the bridge in Stromgarde evades when fought on the bridge.

**Current behaviour**:
Aggro the Stromgarde Defender that pats over the bridge. It evades when it reaches the bridge.

**Expected behaviour**: 
Mob will not evade when fought on the bridge.

**Server Revision**: 
2434
![WoWScrnShot_041123_175228](https://user-images.githubusercontent.com/5695721/231307390-fefa149b-748e-43bd-b372-a6e2d7039116.jpg)
![WoWScrnShot_041123_175234](https://user-images.githubusercontent.com/5695721/231307394-4a5e90c6-039d-4234-8396-3831ab65f154.jpg)

**Comment by Wolffenstein** [comment]
Fixed with mmaps 3.0
