### ISSUE TITLE
Pets dont despawn if Petclasses die

### ISSUE THREAD

**Issue by Nihaobeachez** [Atlantiss/NetherwingBugtracker#8332]
[//]: # (Enclose links to things related to the bug using http://wowhead.com or any other TBC database.)
[//]: # (You can use screenshot ingame to visual the issue.)
[//]: # (Write your tickets according to the format:)
[//]: # ([Quest][Azuremyst Isle] Red Snapper - Very Tasty!)
[//]: # ([NPC] Magistrix Erona)
[//]: # ([Spell][Mage] Fireball)
[//]: # ([Npc][Drop] Ghostclaw Lynx)
[//]: # ([Web] Armory doesnt work)
[//]: # (To find server revision type `.server info` command in the game chat.)

**Description**: Only noticed it during PvP right now, but Hunter pets dont disappear once the Hunter gets killed while being mounted.

**Current behaviour**: If you kill a Hunter while he's mounted and has no Pet available, the Pet spawns after the Hunter dies and stays till he releases his body and gets into Ghostform. He may even have still control over it, didnt test it tho
![image](https://user-images.githubusercontent.com/96308500/231427863-77b09479-030c-4438-83d0-931780c299b2.png)

edit : Same applies for Warlock

**Expected behaviour**: Pet should despawn?

**Server Revision**: 3744

**Comment by Massie323** [comment]
To add to this:
> He may even have still control over it

Unless the pet is set to passive, it will respond normally and attack you until killed, despite the Pet-owner being dead.

**Comment by Wolffenstein** [comment]
Fixed in rev 3759.
