### ISSUE TITLE
[QoL] [Feature request] .join command

### ISSUE THREAD

**Issue by Kuszki** [Atlantiss/NetherwingBugtracker#8334]
[//]: # (Enclose links to things related to the bug using http://wowhead.com or any other TBC database.)
[//]: # (You can use screenshot ingame to visual the issue.)
[//]: # (Write your tickets according to the format:)
[//]: # ([Quest][Azuremyst Isle] Red Snapper - Very Tasty!)
[//]: # ([NPC] Magistrix Erona)
[//]: # ([Spell][Mage] Fireball)
[//]: # ([Npc][Drop] Ghostclaw Lynx)
[//]: # ([Web] Armory doesnt work)
[//]: # (To find server revision type `.server info` command in the game chat.)

**Description**: Currently after finishing activity joined by ".join xxx" command player is teleported to place where he joined (typed command). This behavior is quite annoying while for eg. avg. wait time for bg is long (eg. 10-15 minutes). If purpose of this QoL feature is to apply players chance to perform other activities while waiting in queue, then its not the way it should work. In my opinion better way is to spawn player after finishing bg/arena in place where he entered rather where he signed himself into queue. Of course this must be discussed - its only my point of view.

**Current behaviour**: Player is spawned in place where he signed into bg/arena.

**Expected behaviour**: Player is spawned in place he entered bg/arena.

**Server Revision**: 3744

**Comment by Kuszki** [comment]
EDIT: this feature work as "Expected behaviour" from my post, but sometimes it seems to works like "Current behaviour" from my post.

**Comment by Nihaobeachez** [comment]
Never happened to me. I always spawn where i enter, not where i sign up.

**Comment by Kuszki** [comment]
It happened to me few times, but for now i didn't find any way to reproduce it. If i find any clues i will add them in this thread. For now it work fine.
