### ISSUE TITLE
Battle Squawk - buff from Gnomish Battle Chicken

### ISSUE THREAD

**Issue by Godmatik** [Atlantiss/NetherwingBugtracker#8338]
**Description**: 
Battle Squawk buff from chicken engineer pet

**Current behaviour**:
Increases ranged attack speed in addition to melee (AKA works on Hunters)

**Expected behaviour**: 
Should only increase melee attack speed

**Server Revision**: 
3745
https://www.wowhead.com/classic/item=10725/gnomish-battle-chicken
https://www.wowhead.com/classic/spell=23060/battle-squawk

**Comment by Wolffenstein** [comment]
![image](https://user-images.githubusercontent.com/1576644/231840604-1ebe7865-6c89-4020-9bcd-1e0138047306.png)
I don't know how you tested it but it does not, it only applies SPELL_AURA_MOD_MELEE_HASTE.
