### ISSUE TITLE
[NPC] mob density in Charred Vale too high

### ISSUE THREAD

**Issue by totaemoeggerli** [Atlantiss/NetherwingBugtracker#834]
[//]: # (Enclose links to things related to the bug using http://wowhead.com or any other TBC database.)
[//]: # (You can use screenshot ingame to visual the issue.)
[//]: # (Write your tickets according to the format:)
[//]: # ([Quest][Azuremyst Isle] Red Snapper - Very Tasty!)
[//]: # ([NPC] Magistrix Erona)
[//]: # ([Spell][Mage] Fireball)
[//]: # ([Npc][Drop] Ghostclaw Lynx)
[//]: # ([Web] Armory doesnt work)

**Description**:
Some mobs in the Charred Vale in Stonetalon Mountain are too abundant
[Furious Stone Spirit](https://www.wowhead.com/npc=4035/furious-stone-spirit#comments)
[Enraged Stone Spirit](https://www.wowhead.com/npc=4034/enraged-stone-spirit#comments)
[Fledling Chimaera](https://www.wowhead.com/npc=4031/fledgling-chimaera#comments)
[Singed Basilisk](https://www.wowhead.com/npc=4042/singed-basilisk#comments)
There are very few wowhead comments about those mobs. I think that is because only few of them existed and only the Chimaera is involved in a [quest](https://vanilla-twinhead.twinstar.cz/?quest=1701). This is a warrior quest and most players skip it.
Most striking is the absence of comments about the Furious Stone Spirit. Their ability is extremly powerful and players would complain/warn in the comments. I don't think that more then 1-2 were active in the area.

**Current behaviour**:
All four mobs exist in great numbers in the area. Most notably are the Furious Stone Spirits. They seem to spawn in pairs too which is extremly unsual. 

**Expected behaviour**:
Wowhead comment about abundance of Furious Stone Spirit:
```
By Boshnak (18,966 –  2·22·120)  on 2007/06/18 (Patch 2.1.1) |   |  
These things aren't that abundant in the areas indicated on that screenshot. 
I've found very few.
```

Wowhead comment aboput basilisks and chimaera shareing spawn points (you can remove half of each and the area is still packed with mobs).
```
By Rahkitty (1,209 – 16) on 2010/02/13 (Patch 3.3.2)
These share a spawn with the Basilisk in the area.
```

joana levelin impression with time stamp [1](https://youtu.be/fUAbNkBmBHE?t=40m33s) [2](https://youtu.be/B5Dbl1Qs4Qs?t=1m9s)

**Server Revision**: 2078

**Comment by aresbrutus** [comment]
They actually already share spawn points, maybe that is why it looks like there are an abundance of a specific npc.

**Comment by totaemoeggerli** [comment]
That might justify the chimaera and basilisks. But there are still too many Furious Stone Spirits. And they shouldn't be there in pairs.

**Comment by aresbrutus** [comment]
Fixed in one of the next updates.
