### ISSUE TITLE
Error 134

### ISSUE THREAD

**Issue by BGV044** [Atlantiss/NetherwingBugtracker#8340]
[//]: # (Enclose links to things related to the bug using http://wowhead.com or any other TBC database.)
[//]: # (You can use screenshot ingame to visual the issue.)
[//]: # (Write your tickets according to the format:)
[//]: # ([Quest][Azuremyst Isle] Red Snapper - Very Tasty!)
[//]: # ([NPC] Magistrix Erona)
[//]: # ([Spell][Mage] Fireball)
[//]: # ([Npc][Drop] Ghostclaw Lynx)
[//]: # ([Web] Armory doesnt work)
[//]: # (To find server revision type `.server info` command in the game chat.)

**Description**: I am cosntatly having troubles with 2 areas in Kalimdor : Dustwollow Marsh and Thousend Neddles, where the game crashes and it wont load in the game with that character. Error window pops up " ERROR #134 (0x85100086) Fatal Condition" 
I looked it up and in the Logs folder is says :"ERROR - No Repair URL: World\Maps\Kalimdor\Kalimdor_38_42.adt, 0-1759371"

So far only fix i was able to find is unstucking the character, but as soon as i go or pass trough by flypath in one of those areas it will crash again showing the same error. I've tryed deleting chache , disable / deleting addons ,runing game as administrator,  reinstaling game... nothing seems to fix it.

**Current behaviour**:

**Expected behaviour**: 

**Server Revision**:

**Comment by Godmatik** [comment]
Error 134 is typically caused by a corrupt client or corrupt files. Remove the client and download a fresh one.

**Comment by Wolffenstein** [comment]
Clientside issue, download a different client and if the issue persists, ask in our discord's #support channel.
