### ISSUE TITLE
[Sethekk Halls HC] Ravenguards after first boss join the fight when engaging boss.

### ISSUE THREAD

**Issue by Vfonw** [Atlantiss/NetherwingBugtracker#8341]
**Description**:  Happened in 3 seperate runs. First pull of first boss in Sethekk Halls heroic pulls the Ravenguards in the doorway behind first boss. Typically it happens when he spawns his first set of adds. We even attempted to pull boss from range and stand in the door to previous room, same result, even in the hallway before boss room.

**Current behaviour**: Pulling first boss in Sethekk Halls Heroic often chains to Ravenguards from the pack AFTER first boss, making the boss fight almost a guaranteed wipe.

**Expected behaviour**:  Ravenguards shouldn't be linking to First boss on pull.

**Server Revision**: 3744

**Comment by Wolffenstein** [comment]
Hmm, there isn't really any linking there so not sure how that happens. Can you record a video next time and post it here?

**Comment by tsu-1** [comment]
Sounds like adds that spawn during the fight aggro them.

**Comment by Vfonw** [comment]
He didn't pull them this time. We pulled the boss all the way out into the hallway from previous room before pushing him to spawn first adds.
Trying to test next run if people are willing to wipe once for the recording.

**Comment by Foodlenz** [comment]
Are you a warrior? 
The chainlightning the boss casts doesn't seem to have a max jump range (or it has a very big one if it does) and it's also not effected by line of sight.

I spell reflected it, it pulled the Ravenguards. We wiped.
Ran back, circled room, killed ravenguards. Pulled boss.
I spell reflected it again. Seemed fine, then all the mobs from the floor above show up and stomp us. (it must have jumped through the roof??)
Ran back. Pulled boss. Didn't use spell reflect. Profit.

**Comment by Vfonw** [comment]
Yeah had different warrior tanks in all the runs, also using spell reflect. Very likely the boss casts chain lightning first time around same time the adds pop out at 90%.

**Comment by DendengForever** [comment]
Hi! 

I am warrior tank. I was SH hero 2x and happend every time, every pull. 

So we decided to skip him and kill those guards. We killed them and pulled the boss. So insted of those 2 ravenguard, the whole next come after us! Happend every pull. So we full clear dung and then come after this boss.

**Comment by Godmatik** [comment]
Does it still happen if you don't use spell reflect?

**Comment by DendengForever** [comment]
That is something, what is waiting for me to check. But without spell reflect it is litle harder to counter spawned adds. Will try today.

**Comment by DendengForever** [comment]
Confirmed. We are just in and I did not use Spell reflect and encounter went normal as always.

**Comment by Godmatik** [comment]
@Wolffenstein Why was this closed? Is it fixed?

Appears to be caused due to spell reflecting the boss's chain lightning, it causes it to have unlimited range
