### ISSUE TITLE
[Quest] The Dread Relic - No extra mobs spawning

### ISSUE THREAD

**Issue by Massie323** [Atlantiss/NetherwingBugtracker#8342]
[//]: # (Enclose links to things related to the bug using http://wowhead.com or any other TBC database.)
[//]: # (You can use screenshot ingame to visual the issue.)
[//]: # (Write your tickets according to the format:)
[//]: # ([Quest][Azuremyst Isle] Red Snapper - Very Tasty!)
[//]: # ([NPC] Magistrix Erona)
[//]: # ([Spell][Mage] Fireball)
[//]: # ([Npc][Drop] Ghostclaw Lynx)
[//]: # ([Web] Armory doesnt work)
[//]: # (To find server revision type `.server info` command in the game chat.)

**Description**: 
For the quest ["The Dread Relic" (10877)](https://www.wowhead.com/tbc/quest=10877/the-dread-relic) , after picking up the quest item from the chest, you are supposed to be surrounded by dozens of "[Dread Relic Thrall](https://www.wowhead.com/tbc/npc=22369/dread-relic-thrall#comments)" 's. Right now, nothing spawns and you can leave with the quest item uncontested.

**Current behaviour**:
No extra mobs spawning after looting quest item.

**Expected behaviour**: 
Player gets surrounded from a safe distance by "Dread Relic Thrall"s after looting the quest item.

**Server Revision**: 
3750

![image](https://user-images.githubusercontent.com/57675820/232209670-0c437e9d-cb46-46f8-8689-db029b5f3908.png)
This is how it's supposed to look.

**Comment by Godmatik** [comment]
Confirmed.

Attached report shows a video of the event

https://github.com/Atlantiss/NetherwingBugtracker/issues/7583

**Comment by EtheriousNW** [comment]
Fixed in 3846
