### ISSUE TITLE
Evoker's Helmet of Second Sight

### ISSUE THREAD

**Issue by blobom** [Atlantiss/NetherwingBugtracker#8343]
[//]: # (Enclose links to things related to the bug using http://wowhead.com or any other TBC database.)
https://www.wowhead.com/tbc/item=31104/evokers-helmet-of-second-sight
[//]: # (You can use screenshot ingame to visual the issue.)
[//]: # (Write your tickets according to the format:)
[//]: # ([Quest][Azuremyst Isle] Red Snapper - Very Tasty!)
[//]: # ([NPC] Magistrix Erona)
[//]: # ([Spell][Mage] Fireball)
[//]: # ([Npc][Drop] Ghostclaw Lynx)
[//]: # ([Web] Armory doesnt work)
[//]: # (To find server revision type `.server info` command in the game chat.)

**Description**: 
As the title suggests, the item of the same name, headwear that is supposed to "Allow the bearer to see the ghosts of Shadowmoon valley" is not working.
**Current behaviour**:
The spirits, gorefiend bosses and such do not show up just like they do while you wear Spectacles
**Expected behaviour**: 
You should be able to see all those mobs and creatures just like when you are wearing the Spectacles you get from the quest.
**Server Revision**:

**Comment by Wolffenstein** [comment]
![image](https://user-images.githubusercontent.com/1576644/232244647-f09d952f-2e56-47c7-aba3-7e995df6f78c.png)
It works as intended. There are two types of Shadowmoon Ghost Invisibility, this item grants vision of the 2nd one while the quest Spectrecles show the first type of ghosts.
