### ISSUE TITLE
Sweeping Strikes [warrior]

### ISSUE THREAD

**Issue by viallthind** [Atlantiss/NetherwingBugtracker#8344]
After update 15.04.2023  my sweeping strikes works differently. when i use sweeping strikes and ww on groups of mobs only 1 sweeping strikes proc.  we test it with a few warriors and it looks the same as mine

**Comment by tsu-1** [comment]
@viallthind Do `.info` ingame and include "server revision" number.

Also https://www.wowhead.com/tbc/spell=12328/sweeping-strikes#comments:id=203573 ?

**Comment by Wolffenstein** [comment]
Nothing was changed, it works exactly the same and this report gives me zero information.

**Comment by alandrar** [comment]
wasn't it on patch 2.3.3  that change ?
