### ISSUE TITLE
[Spell][Paladin] Greater Blessings are "casted" on too low lvl players 

### ISSUE THREAD

**Issue by Deprot80** [Atlantiss/NetherwingBugtracker#8345]
[//]: # (Enclose links to things related to the bug using http://wowhead.com or any other TBC database.)
[//]: # (You can use screenshot ingame to visual the issue.)
[//]: # (Write your tickets according to the format:)
[//]: # ([Quest][Azuremyst Isle] Red Snapper - Very Tasty!)
[//]: # ([NPC] Magistrix Erona)
[//]: # ([Spell][Mage] Fireball)
[//]: # ([Npc][Drop] Ghostclaw Lynx)
[//]: # ([Web] Armory doesnt work)
[//]: # (To find server revision type `.server info` command in the game chat.)

**Description**: Greater Blessings should ONLY be casted on level 70 players but currently you can cast them on lower level players too, it consumes the symbol of kings reagent and also costs mana, the caster makes the animation but the target doesn't actually receive the buff.

**Current behaviour**: I cast Greater Blessing of Might on a 68lvl warrior and he doesn't get the buff, but i lose my reagent and mana.

**Expected behaviour**: Game should not allow me to cast Greater Blessings on targets below level 70.

**Server Revision**: 3751

**Comment by Godmatik** [comment]
Fixed now, can be closed

**Comment by EtheriousNW** [comment]
Fixed a while back.
