### ISSUE TITLE
Shadow Vulnerability spell hit not fully fixed

### ISSUE THREAD

**Issue by Godmatik** [Atlantiss/NetherwingBugtracker#8347]
**Current behaviour**:
A fix was done during PTR on spell hit not being recognized in regards to certain debuffs such as shadow vulnerability - but it looks like after the fix was applied only spell hit from gear is being considered now - not spell hit from talents such as Shadow Focus (+10% hit for shadow priests)

See:
https://github.com/Atlantiss/NetherwingBugtracker/issues/8199

**Expected behaviour**: 
Spell hit from all sources should be considered when applying debuffs such as Shadow Vulnerability and Winter Chill, not just from gear.

**Server Revision**: 
3750

**Comment by Wolffenstein** [comment]
Fixed in rev 3760.
