### ISSUE TITLE
Target Dummy from Engineering not giving parts back

### ISSUE THREAD

**Issue by sasadubi** [Atlantiss/NetherwingBugtracker#8350]
**Description**: 
Current Target Dummy that is created by Engineering is bugged.
It does not give appropriate engineering mats back and it's not appropriate level.
This is the first Dummy that's being trained at 85 skill.
![Dummy](https://user-images.githubusercontent.com/49869412/232307869-b75db470-e44e-47a6-9229-606c358bbed6.png)

**Current behaviour**:
Currently what is wrong with this dummy is:
- It's level 72, with 17k hp, (Remember this is small dummy for 85 engineering skill)
- I've used 20 of dummies, never got any vanilla engineering mats, instead I got one gray mail chest for lvl 67, ID of item = 25373 according to wowhead)

**Expected behaviour**: 
Back in the day and in WoW classic, when used, this dummy was level 15-20 and attracting nearby targets or self-destroying in 15sec if not destroyed. When destroyed, it would give back low level engineering mats and also had a chance for giving Fused Wiring which is heavily used in Engineering and for creating current vanilla Repair bots which are only one available in the game.
This dummy should be level 20, proof at: https://www.youtube.com/watch?v=tUMuuS-FQm0&ab_channel=Mmrrggll  check at 1:25 of video.

**Conclusion of this issue**
Currently, Fused Wiring recipes are camped by Bots or Gold sellers with probably knowing all the timers. These recipes are sold in Everlook and Shattrath by respective Engineering supplies NPC's. This makes Fused Wiring extremely rare at a price of 30g each, and you need x2 for single repair bot that is only thing available in game cause TBC one is not yet available in the game.
Fixing this dummy, would make players to be able to make ton of these bots and create some Fused Wirings out of them, because we cannot get a recipe for it anyway. I've been looking at AH for 7 days now, and vendors, it's impossible to buy one.

Thank you!

**Server Revision**: 
3751

**Comment by Godmatik** [comment]
See for more info:
https://github.com/Atlantiss/NetherwingBugtracker/issues/2882

**Comment by sasadubi** [comment]
Info says its fixed, but it's not, just used 25 of these dummies, 0 loot.
But thank you for reference. Tagged Wolf.

**Comment by sasadubi** [comment]
CC @Wolffenstein

**Comment by sasadubi** [comment]
Bump

**Comment by Wolffenstein** [comment]
Fixed in rev 3757.
