### ISSUE TITLE
[SPELL][MAGE]BLIZZARD NOT SLOWING ON FRIST TICK!

### ISSUE THREAD

**Issue by boxitooo6629** [Atlantiss/NetherwingBugtracker#8351]
**Description**: 
BLIZZARD IS NOT SLOWING ON FIRST TICK VS STEALTH 
**Current behaviour**:
BLIZARD IS NOT SLOWING ON FRIST TICK VS STEALTH
**Expected behaviour**: 
BLIZARD SHOULD BE SLOWING ON FRIST TICK EVEN TARGET IS ON STEALTH
**Server Revision**:

**Comment by Wolffenstein** [comment]
Fixed in rev 3757.
