### ISSUE TITLE
Spell delay ( might be related to ping )

### ISSUE THREAD

**Issue by blenzus** [Atlantiss/NetherwingBugtracker#8354]
[//]: # (Enclose links to things related to the bug using http://wowhead.com or any other TBC database.)
[//]: # (You can use screenshot ingame to visual the issue.)
[//]: # (Write your tickets according to the format:)
[//]: # ([Quest][Azuremyst Isle] Red Snapper - Very Tasty!)
[//]: # ([NPC] Magistrix Erona)
[//]: # ([Spell][Mage] Fireball)
[//]: # ([Npc][Drop] Ghostclaw Lynx)
[//]: # ([Web] Armory doesnt work)
[//]: # (To find server revision type `.server info` command in the game chat.)

**Description**: Every spell feels like its delayed by 0.5~s.

**Current behaviour**: Whenever you press a keybind for a spell to be cast, it takes a subtle little time before it goes off, example : as a mage when i press my keybind for blizzard and instantly mouseclick the area i want to blizzard it doesn't go off, you have to press, wait a fraction of a second, then you can mouseclick the area and get your blizzard.

**Expected behaviour**: It should be instant, at least, that's how it was on classic and other well-known pservers, even instant spells take a little time to go off.

**Server Revision**:

**Comment by Godmatik** [comment]
There's no spell delay or spell batching active on this server, sounds like a ping or add-on issue on your end

**Comment by blenzus** [comment]
> There's no spell delay or spell batching active on this server, sounds like a ping or add-on issue on your end

How would I go about to find out which one is causing problems? I tried disabling all my addons and still having the issue.
