### ISSUE TITLE
Crusader aura while running without mount

### ISSUE THREAD

**Issue by Haerys** [Atlantiss/NetherwingBugtracker#8356]
[//]: # (Enclose links to things related to the bug using http://wowhead.com or any other TBC database.)
[//]: # (You can use screenshot ingame to visual the issue.)
[//]: # (Write your tickets according to the format:)
[//]: # ([Quest][Azuremyst Isle] Red Snapper - Very Tasty!)
[//]: # ([NPC] Magistrix Erona)
[//]: # ([Spell][Mage] Fireball)
[//]: # ([Npc][Drop] Ghostclaw Lynx)
[//]: # ([Web] Armory doesnt work)
[//]: # (To find server revision type `.server info` command in the game chat.)

**Description**: 
I was playing with a friend, we were both on our mounts and i had crusader aura activated. Then we took a fly from point A to point B, and when we arrived my friend still had the crusader aura buff active but he wasn't on his mount. So basically he was running way faster than me

**Current behaviour**:
Crusader aura not getting canceled when you take a fly while on mount

**Expected behaviour**: 
Crusader aura buff should cancel everytime you unmount

**Server Revision**:

**Comment by Wolffenstein** [comment]
Why would it be cancelled?
