### ISSUE TITLE
Bug related to getting out of water while swimming (breathing)

### ISSUE THREAD

**Issue by dudensen1** [Atlantiss/NetherwingBugtracker#8357]
**Description**: Bug related to getting out of water while swimming and trying to breathe.

**Current behaviour**: When you swim up trying to get out of water, you character remains underwater slightly and you continue to be unable to breathe. If you again turn the camera upwards and move or simply press jump you can get out of the water.

**Expected behaviour**: Your character should get out of the water after you swim upwards without the need for more actions.

**Server Revision**: 3751

**Comment by Godmatik** [comment]
I believe this is intended for the 2.4.3 client, on classic it works differently because they use the legion client, but I will let someone else verify.

**Comment by tsu-1** [comment]
2.4.3 you have to jump to get out of the water.

**Comment by dudensen1** [comment]
Yeah you are right, I just checked on a vanilla server and it's the same.
