### ISSUE TITLE
[Core][NPC][Karazhan] Nightbane pathing back & forth Alhamdulillah

### ISSUE THREAD

**Issue by Massie323** [Atlantiss/NetherwingBugtracker#8358]
[//]: # (Enclose links to things related to the bug using http://wowhead.com or any other TBC database.)
[//]: # (You can use screenshot ingame to visual the issue.)
[//]: # (Write your tickets according to the format:)
[//]: # ([Quest][Azuremyst Isle] Red Snapper - Very Tasty!)
[//]: # ([NPC] Magistrix Erona)
[//]: # ([Spell][Mage] Fireball)
[//]: # ([Npc][Drop] Ghostclaw Lynx)
[//]: # ([Web] Armory doesnt work)
[//]: # (To find server revision type `.server info` command in the game chat.)

**Description**: 
Mobs in general still have a tendency to move into players, and then instantly run back to max range (compared to the previous slanted terrain related issue of mobs walking into players and staying there). Example below showcases Nightbane.

**Current behaviour**:
Mobs pathing into players & walking back to max range.

**Expected behaviour**: 
Mobs staying at max range.

**Server Revision**: 
3751

https://user-images.githubusercontent.com/57675820/232613919-cc9c66ff-384f-4bb2-8a9e-0f45e6a348bc.mp4

**Comment by Godmatik** [comment]
Was resolved some months ago - closing
