### ISSUE TITLE
Cannot rearrange items in bags while dead

### ISSUE THREAD

**Issue by asatorrr** [Atlantiss/NetherwingBugtracker#836]
[//]: # (Enclose links to things related to the bug using http://wowhead.com or any other TBC database.)
[//]: # (You can use screenshot ingame to visual the issue.)
[//]: # (Write your tickets according to the format:)
[//]: # ([Quest][Azuremyst Isle] Red Snapper - Very Tasty!)
[//]: # ([NPC] Magistrix Erona)
[//]: # ([Spell][Mage] Fireball)
[//]: # ([Npc][Drop] Ghostclaw Lynx)
[//]: # ([Web] Armory doesnt work)

**Description**: While dead or in ghost form any attempt to rearrange items in your bags produces a "you can't do that when you're dead" message.

**Current behaviour**:

**Expected behaviour**: 

**Server Revision**: 2078

**Comment by Easyfraggy** [comment]
Working as intended.
