### ISSUE TITLE
[Stratholme][Spell] Cadaver Worms stacking multiple times

### ISSUE THREAD

**Issue by Massie323** [Atlantiss/NetherwingBugtracker#8360]
[//]: # (Enclose links to things related to the bug using http://wowhead.com or any other TBC database.)
[//]: # (You can use screenshot ingame to visual the issue.)
[//]: # (Write your tickets according to the format:)
[//]: # ([Quest][Azuremyst Isle] Red Snapper - Very Tasty!)
[//]: # ([NPC] Magistrix Erona)
[//]: # ([Spell][Mage] Fireball)
[//]: # ([Npc][Drop] Ghostclaw Lynx)
[//]: # ([Web] Armory doesnt work)
[//]: # (To find server revision type `.server info` command in the game chat.)

**Current behaviour**:
"[Cadaver Worms](https://www.wowhead.com/classic/spell=16143/cadaver-worms)" cast by "[Mangled Cadaver](https://www.wowhead.com/classic/npc=10382/mangled-cadaver)" is stacking multiple times, when it should only 1 debuff should be applied at max.

**Expected behaviour**: 
The debuff should only apply once.

**Server Revision**: 
3751

**Comment by MoonSeYoun** [comment]
#7922

**Comment by Wolffenstein** [comment]
Fixed in rev 3783.
