### ISSUE TITLE
Rip-Blade Ravager does not change colors

### ISSUE THREAD

**Issue by AntriX1337** [Atlantiss/NetherwingBugtracker#8361]
[//]: # (Enclose links to things related to the bug using http://wowhead.com or any other TBC database.)
[//]: # (You can use screenshot ingame to visual the issue.)
[//]: # (Write your tickets according to the format:)
[//]: # ([Quest][Azuremyst Isle] Red Snapper - Very Tasty!)
[//]: # ([NPC] Magistrix Erona)
[//]: # ([Spell][Mage] Fireball)
[//]: # ([Npc][Drop] Ghostclaw Lynx)
[//]: # ([Web] Armory doesnt work)
[//]: # (To find server revision type `.server info` command in the game chat.)

**Description**: The Rip-Blade Ravagers do not change colors at all. Once tamed, they always appear in the purple variant even if the pre-taming variant is the orange one for example.  (https://www.wow-petopia.com/classic_bc/look.php?id=crawler-multi-orange-purple-var2)

**Current behaviour**: Rip-Blade Ravager permanently has the purple variation.

**Expected behaviour**: Rip-Blade Ravager is supposed to change colors randomly each time it's summoned.

**Server Revision**: 3751

**Comment by Wolffenstein** [comment]
Fixed in rev 3830.
