### ISSUE TITLE
[Core] Mind Controlled by AI

### ISSUE THREAD

**Issue by Godmatik** [Atlantiss/NetherwingBugtracker#8363]
**Current behaviour**:
When mind controlled by an AI, you use talents that you aren't specced into. For example, I cast Vampiric Touch as a holy priest when MCed by Blackheart the Inciter in Shadow Labs instance.

I was using my secondary spec and my primary spec is shadow, maybe that is related to this issue, but maybe not.

**Expected behaviour**: 
You shouldn't use inactive talents when mind controlled.

**Server Revision**: 
3751

**Comment by Wolffenstein** [comment]
Fixed in rev 3837.
