### ISSUE TITLE
S1 Offsetitems missing

### ISSUE THREAD

**Issue by fischerderheld** [Atlantiss/NetherwingBugtracker#8364]
[//]: # [(Enclose links to things related to the bug using http://wowhead.com or any other TBC database.)](https://www.wowhead.com/tbc/item=32993/generals-ringmail-sabatons)
(https://www.wowhead.com/tbc/item=32991/generals-ringmail-bracers)
(https://www.wowhead.com/tbc/item=32992/generals-ringmail-girdle)

**Description**: 
We seem to be missing some season 1 items. For example the Mail healing offsets.
**Current behaviour**:
The vendor is not selling the s1 mail healing offset items. See wowhead links.
**Expected behaviour**: 
During S1 I would expect S1 mail healing offset items to be sold by the offset vendor
**Server Revision**:

**Comment by Godmatik** [comment]
The wowhead comments say they shouldn't exist? Sounds like an item Blizz made but decided not to implement

**Comment by fischerderheld** [comment]
So restoshamans have to wear leather/cloth offset pieces? Might not be blizzlike but i think every spec should get their respective offset. As far as i can tell only restoshamans are left out.

**Comment by Godmatik** [comment]
Up to Wolf on whether he wants to implement them I suppose, it's not technically a bug though, so we just wait and see

**Comment by tsu-1** [comment]
Will be added. Missed them by accident, sorry.

**Comment by tsu-1** [comment]
@Wolffenstein added. Can be closed.
