### ISSUE TITLE
Midsummer decorations in Shattrath

### ISSUE THREAD

**Issue by Godmatik** [Atlantiss/NetherwingBugtracker#8366]
**Description**: 
How did no one notice this before?

**Current behaviour**:
Midsummer decorations are up in Shattrath

**Expected behaviour**: 
Should not be

**Server Revision**: 
3757

An example:

![Midsummer](https://user-images.githubusercontent.com/37913400/233411458-2d4e1388-4857-474c-9d2a-c8ecfa38f867.png)

**Comment by Wolffenstein** [comment]
Fixed in rev 3759.
