### ISSUE TITLE
Quest Zalazane Hexed Trolls trolls

### ISSUE THREAD

**Issue by Mellish13** [Atlantiss/NetherwingBugtracker#8367]
[//]: # (Enclose links to things related to the bug using http://wowhead.com or any other TBC database.)
[//]: # (You can use screenshot ingame to visual the issue.)
[//]: # (Write your tickets according to the format:)
[//]: # ([Quest][Azuremyst Isle] Red Snapper - Very Tasty!)
[//]: # ([NPC] Magistrix Erona)
[//]: # ([Spell][Mage] Fireball)
[//]: # ([Npc][Drop] Ghostclaw Lynx)
[//]: # ([Web] Armory doesnt work)
[//]: # (To find server revision type `.server info` command in the game chat.)

**Description**: 
Quest Zalazane hexed troll counter not working as intended.
**Current behaviour**:
I´ve killed around 20 Hexed Trolls and the counter never left 2/8
**Expected behaviour**: 
Counter going up to intended value after each kill.
**Server Revision**: 
![image](https://user-images.githubusercontent.com/131387249/233423854-bfa4c123-b63a-49aa-b0cd-54169b72120a.png)

**Comment by Godmatik** [comment]
visual bug only with your quest add-on, you do have it completed, go turn in quest
