### ISSUE TITLE
Bugged trinket 

### ISSUE THREAD

**Issue by zetryz** [Atlantiss/NetherwingBugtracker#8368]
[//]: # (Enclose links to things related to the bug using http://wowhead.com or any other TBC database.)
[//]: # (You can use screenshot ingame to visual the issue.)
[//]: # (Write your tickets according to the format:)
[//]: # ([Quest][Azuremyst Isle] Red Snapper - Very Tasty!)
[//]: # ([NPC] Magistrix Erona)
[//]: # ([Spell][Mage] Fireball)
[//]: # ([Npc][Drop] Ghostclaw Lynx)
[//]: # ([Web] Armory doesnt work)
[//]: # (To find server revision type `.server info` command in the game chat.)

**Description**: 
https://www.wowhead.com/tbc/item=27900/jewel-of-charismatic-mystique
**Current behaviour**:
Doesn't wipe threat at all according to my omen.
**Expected behaviour**: 
Reduces threat.
**Server Revision**:

**Comment by Wolffenstein** [comment]
Serverside threat data is not sent to players in TBC and addons like Omen only guess the current threat. Spell works correctly
