### ISSUE TITLE
Spell Pushback

### ISSUE THREAD

**Issue by ghost** [Atlantiss/NetherwingBugtracker#8369]
**Current behaviour**: Spell casting can be pushed back infinitely.
(versus a hunter with pet and snake trap, youre never getting a spell off)

**Expected behaviour**: After 5th hit, the caster should become immune to pushback.

**Server Revision**: 3758

> PUSHBACK
When your health physically drops as a result of direct damage, the spell you are currently casting is subject to pushback. Pushback increases the length of time it takes to cast your spell and is very predictable.
&nbsp;
**For a spell with a cast time, the first hit you take while casting that spell increases your cast time by a max of 1.0s. The second hit 0.8s, the third 0.6s, then 0.4 and finally 0.2s. If you are hit more than five times in a single spell cast, you are immune to pushback.** Pushback is determined on a per-spell basis. You cannot be pushed back more than the spells total cast time; e.g. if you are 0.1s into casting a fireball and you receive a hit, your cast time will go to 3.0s, not 3.9s.
&nbsp;
Channeled spells, like Evocation, work a little differently. Each instance of pushback will remove from your channel half the channel time left. Since Evocation ticks every 2 seconds over an 8-second channel, this means that you can actually lose more or less than half the channeled time left depending on when you get pushback.
&nbsp;
DoT damage does not cause pushback. Damage that is (fully) shielded or absorbed does not cause pushback. You cannot be affected by pushback during the effects of Icy Veins.

**Comment by Wolffenstein** [comment]
Can you find another source? I don't remember there being any cap on pushback hits in Vanilla/TBC.

**Comment by Godmatik** [comment]
Every source I read says that spell pushback cap was added in WotLK, and that there was no limit before then.

Can you provide a link to your quote?

**Comment by ghost** [comment]
https://legacy-wow.com/tbc-mage-guide/?spell=25122#ftoc-pushback

I will go through some videos tommorow.

Can you link a source saying that spell pushback cap was added in WotLK please.

**Comment by ghost** [comment]
https://youtu.be/A4NL-GEoKEY?t=360
that's 6 or 7 (with the talent...)

https://www.youtube.com/watch?v=sRl4FLAMeLY
classic tbc

it really took them 4 years
