### ISSUE TITLE
Data Rescue

### ISSUE THREAD

**Issue by Mewmewww** [Atlantiss/NetherwingBugtracker#837]
[//]: # (Enclose links to things related to the bug using http://wowhead.com or any other TBC database.)
[//]: # (You can use screenshot ingame to visual the issue.)
[//]: # (Write your tickets according to the format:)
[//]: # ([Quest][Azuremyst Isle] Red Snapper - Very Tasty!)
[//]: # ([NPC] Magistrix Erona)
[//]: # ([Spell][Mage] Fireball)
[//]: # ([Npc][Drop] Ghostclaw Lynx)
[//]: # ([Web] Armory doesnt work)

**Description**: Not given the opportunity to proceed further to machine B in gnomeregan

**Current behaviour**: Not given the opportunity to proceed further to machine B in gnomeregan

**Expected behaviour**:  Should be given the opportunity to proceed further to machine B in gnomeregan

**Server Revision**: 2078

**Comment by tcberk12** [comment]
did you do the first punch card outside the instance?

**Comment by aresbrutus** [comment]
Confirmed. Right clicking any Matrix Punchograph 3005-A with the item 9279 in your bag should provide the player with the item 9280

**Comment by Azalen** [comment]
I don't understand whats the issue. Quest worked for my party on alliance side two days ago. Only (minor) issue was the white card still dropping even though the yellow card was in the inventory already but other than this it worked like it should have.

**Comment by Easyfraggy** [comment]
Another report on same issue: https://github.com/Atlantiss/NetherwingBugtracker/issues/1049

**Comment by Tereneckla** [comment]
Fixed
