### ISSUE TITLE
Corpses do not automatically release after 6 minutes. 

### ISSUE THREAD

**Issue by KyleStulen-1** [Atlantiss/NetherwingBugtracker#8370]
[//]: # (Enclose links to things related to the bug using http://wowhead.com or any other TBC database.)
[//]: # (You can use screenshot ingame to visual the issue.)
[//]: # (Write your tickets according to the format:)
[//]: # ([Quest][Azuremyst Isle] Red Snapper - Very Tasty!)
[//]: # ([NPC] Magistrix Erona)
[//]: # ([Spell][Mage] Fireball)
[//]: # ([Npc][Drop] Ghostclaw Lynx)
[//]: # ([Web] Armory doesnt work)
[//]: # (To find server revision type `.server info` command in the game chat.)

**Description**: 
If someone is dead on the ground for 6 minutes they do not automatically release. 

**Current behaviour**:
Corpse stays on ground in raid taking a raid spot. 

**Expected behaviour**: 
Corpse releases after 6 minutes. 

**Server Revision**:

**Comment by Wolffenstein** [comment]
The code specifically disables auto-release in instances, do you have some classic/retail proof that it should still auto-release?

**Comment by Wolffenstein** [comment]
I changed it to release for non-grouped players in rev. 3773.
