### ISSUE TITLE
[Hunter] Cannot Viper Sting shapeshifted targets

### ISSUE THREAD

**Issue by bluemanguy112** [Atlantiss/NetherwingBugtracker#8372]
**Description**: 
It is not possible to apply Viper Sting to Shapeshifted Targets (e.g. Druids in Cat or Bear Form)

**Current behaviour**:
Error message is displayed.

**Expected behaviour**: 
You should be able to apply Viper Sting to shapeshifted targets (it still should not drain mana ofc)
https://clips.twitch.tv/AmusedHelplessOpossumKippa-03n3ZW05UzPxij6S

**Comment by Wolffenstein** [comment]
Fixed in rev 3760.
