### ISSUE TITLE
[Rogue] Cloak of Shadows incorrectly provides immunity to Hunter Stings and Arcane Shot

### ISSUE THREAD

**Issue by bluemanguy112** [Atlantiss/NetherwingBugtracker#8373]
**Description**: 
Cloak of Shadows incorrectly provides immunity to Hunter Stings and Arcane Shot

**Current behaviour**:
Upon trying to apply any Hunter Sting (Scorpid Sting, Serpent Sting, Wyvern Sting) or Arcane Shot during Cloak of Shadows an "Immune" message is shown.

**Expected behaviour**: 
You should not be able to Immune any Stings or Arcane Shot.

https://clips.twitch.tv/SpookyCrispyBasenjiRalpherZ-ZJ0WzWCbq_uURYbQ
^Dispell and damage of arcane shot during Cloak of Shadows.
Same thing applies to all Stings.

**Comment by ghost** [comment]
Wand attacks are spells too, apparently

**Comment by Wolffenstein** [comment]
I dont understand this report, do you mean the resist chance from CoS or what?

**Comment by bluemanguy112** [comment]
All hunter shots are considered physical. Therefore it is not possible to resist/immune hunter stings and arcane shot. When I tested it, serpent stinging rogue during cloak displayed "immune" in the combat log.

**Comment by Godmatik** [comment]
Can't speak about stings - but arcane shot is arcane is it not? At least on arcane immune mobs it does not work, and the school of magic listed in wowhead clearly states it is Arcane.

**Comment by bluemanguy112** [comment]
Check: https://clips.twitch.tv/SpookyCrispyBasenjiRalpherZ-ZJ0WzWCbq_uURYbQ 
You can clearly see that not only does Arcane Shot deal damage but it also dispells the Priestbuff.

Please don't make me look through hours of VoD... it is pretty common knowledge that you can Cloak Stings off but you do not gain immunity to them being reapplied during Cloak.

**Comment by Wolffenstein** [comment]
Uhh Serpent Sting is MASK_NATURE not physical. Cloak of Shadows also applies a hidden, brief (one update batch) immunity to all non-physical spell schools. Are you sure you haven't had an immune during that short period?

**Comment by bluemanguy112** [comment]
> Uhh Serpent Sting is MASK_NATURE not physical. Cloak of Shadows also applies a hidden, brief (one update batch) immunity to all non-physical spell schools. Are you sure you haven't had an immune during that short period?

Never heard of that brief immunity? Mind providing me with a source of that? This most definitely was not a thing in TBC classic, however, I do not want to rule out that it existed in original TBC and simply ended up being negilible in duration due to the client update of classic.

**Comment by Godmatik** [comment]
![cloak](https://github.com/user-attachments/assets/53755662-7fe4-4ad3-a8ea-1ae1ab096493)

Seems fixed now, closing
