### ISSUE TITLE
[ITEM] Stabilized Eternium Scope requires 375 Engi to be present in order for it drop

### ISSUE THREAD

**Issue by Godmatik** [Atlantiss/NetherwingBugtracker#8374]
**Description**: 
Stabilized Eternium Scope pattern from Attumen in Karazhan

**Current behaviour**:
Only drops if a 375 Engineer is present. 

**Expected behaviour**: 
Should drop from boss if you have an engineer in the raid of any skill level. 

https://www.wowhead.com/tbc/item=23809/schematic-stabilized-eternium-scope#dropped-by

![engi](https://user-images.githubusercontent.com/37913400/233845745-388893e6-61cc-45f5-af7e-456169dae85e.png)

**Server Revision**: 
3758

**Comment by Wolffenstein** [comment]
Fixed in rev 3760.
