### ISSUE TITLE
[Spell][Mage] Arcane Missiles sometimes does not cast the last missile

### ISSUE THREAD

**Issue by Mintey** [Atlantiss/NetherwingBugtracker#8376]
[//]: # (Enclose links to things related to the bug using http://wowhead.com or any other TBC database.)
[//]: # (You can use screenshot ingame to visual the issue.)
[//]: # (Write your tickets according to the format:)
[//]: # ([Quest][Azuremyst Isle] Red Snapper - Very Tasty!)
[//]: # ([NPC] Magistrix Erona)
[//]: # ([Spell][Mage] Fireball)
[//]: # ([Npc][Drop] Ghostclaw Lynx)
[//]: # ([Web] Armory doesnt work)
[//]: # (To find server revision type `.server info` command in the game chat.)

**Description**: 
Arcane Missiles sometimes does not cast the last missile. It seems to happen more often when AM is cast directly after another spell, but it can happen when cast completely alone as well. This testvideo was done with 5/5 Improved Arcane Missiles. 

https://user-images.githubusercontent.com/11920749/233860033-10d4ad61-3779-4094-b3c2-90cfa8d0487e.mp4

**Current behaviour**:
Arcane Missiles sometimes does not cast all of its missiles, even when no spell-pushback has occurred. 

**Expected behaviour**: 
Arcane Missiles always casts all its missiles, unless spell-pushbacked. 

**Server Revision**: 
3758

**Comment by tsu-1** [comment]
Is it possible that it spell pushbacked you but didn't show on the bar though?
Would be nice to have a video on some dummy boss, where you don't get hit at all.

**Comment by Mintey** [comment]
Even if thats the case, then the Improved Arcane Missiles talent isnt working properly, since it should remove all pushback. Like i said in the discription, i had it maxed on this video. 

That said, i'll see if i can get a clean video without getting hit just to remove that variable as well.

**Comment by Godmatik** [comment]
Tried to reproduce and still unable to
Even used a shitload of haste effects and heroism, still always does all 5 missiles.
The only thing at the moment cancelling the last missile is leeway, which is a separate bug and has its own issue open.

If you are able to reproduce this and it's not leeway related, please post and I can reopen.
