### ISSUE TITLE
[NPCs] Outland mobs that should start with 0 mana not fully fixed

### ISSUE THREAD

**Issue by Godmatik** [Atlantiss/NetherwingBugtracker#8378]
**Current behaviour**:
Several Outland mobs currently start with full mana bar -This issue was said to be fixed on PTR in rev 3660. The mana regen is indeed disabled but they still start with 100% mana when you engage them which isn't intended.

**Expected behaviour**: 
All NPCs listed in the below resolved github issue should start with 0 mana when spawned/reset.

**Server Revision**: 
3758

https://github.com/Atlantiss/NetherwingBugtracker/issues/2604

**Comment by Wolffenstein** [comment]
Fixed in rev 3830.
