### ISSUE TITLE
Epic PvP Gem Bug

### ISSUE THREAD

**Issue by budgebudge** [Atlantiss/NetherwingBugtracker#8380]
[//]: # (Enclose links to things related to the bug using http://wowhead.com or any other TBC database.)
[//]: # (You can use screenshot ingame to visual the issue.)
[//]: # (Write your tickets according to the format:)
[//]: # ([Quest][Azuremyst Isle] Red Snapper - Very Tasty!)
[//]: # ([NPC] Magistrix Erona)
[//]: # ([Spell][Mage] Fireball)
[//]: # ([Npc][Drop] Ghostclaw Lynx)
[//]: # ([Web] Armory doesnt work)
[//]: # (To find server revision type `.server info` command in the game chat.)

**Description**: 
if socketed this gem into gear and purchased a second time, it cant be put into the bank or moved in inventory. also: if u relog, the gem disappears completely. Edit: it gets sent to me automatically it seems. however, i cant pick it up since unique?
**Current behaviour**:

**Expected behaviour**: 

**Server Revision**: 
![image](https://user-images.githubusercontent.com/2218363/234126664-a0cff231-6717-4b72-94de-1417a2c0139e.png)

**Comment by Godmatik** [comment]
Looks like the bug here is that it shouldn't be able to be purchased a 2nd time since the gem is Unique

**Comment by tsu-1** [comment]
Should be Unique-Equipped.

itemID `27679`

https://www.wowhead.com/tbc/item=27679/sublime-mystic-dawnstone

**Comment by Wolffenstein** [comment]
Fixed in rev 3772.
