### ISSUE TITLE
Shatter messes up my threat meter

### ISSUE THREAD

**Issue by Sasab94** [Atlantiss/NetherwingBugtracker#8381]
[//]: # (Enclose links to things related to the bug using http://wowhead.com or any other TBC database.)
[//]: # (You can use screenshot ingame to visual the issue.)
[//]: # (Write your tickets according to the format:)
[//]: # ([Quest][Azuremyst Isle] Red Snapper - Very Tasty!)
[//]: # ([NPC] Magistrix Erona)
[//]: # ([Spell][Mage] Fireball)
[//]: # ([Npc][Drop] Ghostclaw Lynx)
[//]: # ([Web] Armory doesnt work)
[//]: # (To find server revision type `.server info` command in the game chat.)

**Description**: 
After using soul shatter, my threat meter reduces threat. Works like a charm, and i pull boss with 60%(-60% on threat meter) lower threat than tank. I've tried multiple threat meters ( omen, diamond, etc) , happens same on every. I get agro without even being first on threat.
**Current behaviour**:
Getting agro without showing on threat meter(showing 60% less threat than needed to pull).
**Expected behaviour**: 

**Server Revision**:

**Comment by Godmatik** [comment]
Server can't fix issues regarding add-ons not showing threat proper, those add-ons are using estimations and not actual server data
