### ISSUE TITLE
Sporeling snack recipe is missing

### ISSUE THREAD

**Issue by Red86** [Atlantiss/NetherwingBugtracker#8382]
**Description**: 
The sporeling snack recipe is missing.
**Current behaviour**:
Right now the sporeling snack recipe is not being sold by the sporeggar quartermaster.
**Expected behaviour**: 
The recipe should be available for purchase. In the past there was this issue raised:
https://github.com/Atlantiss/NetherwingBugtracker/issues/5058
The answer back then was that the recipe was introduced in 2.1. However if we check the comments on the wowhead page:
https://www.wowhead.com/tbc/item=27656/sporeling-snack#comments

There are thottbot comments dated 2007/01, patch 2.0.5 so, before 2.1.

**Comment by Godmatik** [comment]
Bump.

Would be nice to add this in.

**Comment by Wolffenstein** [comment]
Fixed in rev 3825.
