### ISSUE TITLE
[Spell][Rogue] Vanish not trackable

### ISSUE THREAD

**Issue by tsu-1** [Atlantiss/NetherwingBugtracker#8383]
[//]: # (Enclose links to things related to the bug using http://wowhead.com or any other TBC database.)
[//]: # (You can use screenshot ingame to visual the issue.)
[//]: # (Write your tickets according to the format:)
[//]: # ([Quest][Azuremyst Isle] Red Snapper - Very Tasty!)
[//]: # ([NPC] Magistrix Erona)
[//]: # ([Spell][Mage] Fireball)
[//]: # ([Npc][Drop] Ghostclaw Lynx)
[//]: # ([Web] Armory doesnt work)
[//]: # (To find server revision type `.server info` command in the game chat.)

**Description**: Rogus Vanish ability tracking

**Current behaviour**: Vanish ability when used is not being tracked by any cooldown tracking addons. Maybe missing action from combat log?

**Expected behaviour**: Vanish cooldown should be trackable by AddOns.

**Server Revision**: 3762

**Comment by Godmatik** [comment]
Was fixed recently
