### ISSUE TITLE
Alliance PvP vendor

### ISSUE THREAD

**Issue by Romisu** [Atlantiss/NetherwingBugtracker#8384]
[//]: # (Enclose links to things related to the bug using http://wowhead.com or any other TBC database.)
[//]: # (You can use screenshot ingame to visual the issue.)
[//]: # (Write your tickets according to the format:)
[//]: # ([Quest][Azuremyst Isle] Red Snapper - Very Tasty!)
[//]: # ([NPC] Magistrix Erona)
[//]: # ([Spell][Mage] Fireball)
[//]: # ([Npc][Drop] Ghostclaw Lynx)
[//]: # ([Web] Armory doesnt work)
[//]: # (To find server revision type `.server info` command in the game chat.)

**Description**:  Captain Dirgehammer, the alliance Armor Quatermaster sells mostly horde pvp items instead of alliance pvp items.

**Current behaviour**: Most of the items sold by the vendor are using the name and model General, which is the Horde version of the same pvp item.

**Expected behaviour**:  Alliance PvP vendors should sell Marshal gear, which has the alliance only item models.

**Server Revision**:

**Comment by tsu-1** [comment]
Doesn't matter. Can be closed. Gear looks the same for either Horde/Alliance. It's just a name difference. No need to bother as from next season it's Veteran for both factions.
