### ISSUE TITLE
[Item][Priest] Earring of soulful meditation and Bangle of endless blessings, on-use does not stack.

### ISSUE THREAD

**Issue by Vfonw** [Atlantiss/NetherwingBugtracker#8387]
**Description**: [5376](https://github.com/Atlantiss/NetherwingBugtracker/issues/5376) issue is still present on current revision.

**Current behaviour**: Using both [Bangle of Endless Blessings](https://www.wowhead.com/tbc/item=28370/bangle-of-endless-blessings) and [Earring of Soulful Meditation](https://www.wowhead.com/tbc/item=30665/earring-of-soulful-meditation) makes the 2nd used one overwrite the 1st used one. 

**Expected behaviour**: Both on-use effects should be able to be active at the same time.

**Server Revision**: 3762

**Comment by tsu-1** [comment]
Confirmed.

https://www.wowhead.com/tbc/item=30665/earring-of-soulful-meditation#comments:id=66795:reply=294249

**Comment by Godmatik** [comment]
Duplicate
