### ISSUE TITLE
fix the drop rate for rare items

### ISSUE THREAD

**Issue by sepehr-72** [Atlantiss/NetherwingBugtracker#8388]

**Comment by Godmatik** [comment]
the XP rate has nothing to do with drop rates.

Since you failed to provide a wowhead link, here is one for Wolf to review:

https://www.wowhead.com/tbc/item=13926/golden-pearl#contained-in-item

**Comment by sepehr-72** [comment]
> 
> 
> 
> 
> https://www.wowhead.com/tbc/item=13926/golden-pearl#contained-in-item

hey thanks for helping me sir i really appreciate it

**Comment by sepehr-72** [comment]
w

**Comment by sepehr-72** [comment]
> 
> 
> 
> 
> https://www.wowhead.com/tbc/item=13926/golden-pearl#contained-in-item

hey thanks for helping me sir i really appreciate it but a game master ingame told me that this bug maybe because of xp rate
btw please look at the screenshot that i attached to understand why i cant send wowhead links
![Untitled](https://user-images.githubusercontent.com/121827953/235006930-594879d0-d312-4849-b7a0-8ca44e3d5141.jpg)

**Comment by Godmatik** [comment]
I dont know why a GM told you that, they must've been mistaken.

As I said, the XP rate only affects experience and nothing else.

Very likely the drop rate just doesn't match values from classic and needs to be fixed.

**Comment by sepehr-72** [comment]
![image](https://user-images.githubusercontent.com/121827953/235254801-a70cc7b6-d60f-4dda-bc67-309be862ed74.png)

a wise person told me everything after the "but" should be ignored by the listener
i hope someone fix this because they advertise their pserver with good experience
