### ISSUE TITLE
[Karazhan][NPC][Spell] Shade of Aran - Dragonbreath into Magnetic Pull glitched movement

### ISSUE THREAD

**Issue by Massie323** [Atlantiss/NetherwingBugtracker#8389]
[//]: # (Enclose links to things related to the bug using http://wowhead.com or any other TBC database.)
[//]: # (You can use screenshot ingame to visual the issue.)
[//]: # (Write your tickets according to the format:)
[//]: # ([Quest][Azuremyst Isle] Red Snapper - Very Tasty!)
[//]: # ([NPC] Magistrix Erona)
[//]: # ([Spell][Mage] Fireball)
[//]: # ([Npc][Drop] Ghostclaw Lynx)
[//]: # ([Web] Armory doesnt work)
[//]: # (To find server revision type `.server info` command in the game chat.)

**Description**: 
If you are under the effects of Aran's Dragon Breath and you get pulled in for his Arcane Explosion, you regain control over your Character's movement while still debuffed, but upon expiration of Dragon's Breath, you are teleported back to your position before the Magnetic Pull.

**Current behaviour**:
Dragon Breath during Arcane Explosion will teleport you to a previous position on expiration.

**Expected behaviour**: 
I don't know exactly what the correct behaviour would be, whether the disorentation would cause you to ignore the pull, or if you would wander around disoriented inside Aran for the full duration.

Certain people have also said that Aran was hotfixed in patch 2.0 to not cast Dragon's Breath before his major abilities (Flame Wreath/Blizzard/Arcane Explosion), so the issue may be more underlying.

**Server Revision**: 
3762

https://user-images.githubusercontent.com/57675820/234998865-c92d86bb-7199-4b6a-8a24-4b52213a56bc.mp4

**Comment by Wolffenstein** [comment]
Fixed in rev 3830.
