### ISSUE TITLE
[Item] Blade of Eternal Darkness

### ISSUE THREAD

**Issue by Mewmewww** [Atlantiss/NetherwingBugtracker#8390]
[//]: # (Enclose links to things related to the bug using http://wowhead.com or any other TBC database.)
[//]: # (You can use screenshot ingame to visual the issue.)
[//]: # (Write your tickets according to the format:)
[//]: # ([Quest][Azuremyst Isle] Red Snapper - Very Tasty!)
[//]: # ([NPC] Magistrix Erona)
[//]: # ([Spell][Mage] Fireball)
[//]: # ([Npc][Drop] Ghostclaw Lynx)
[//]: # ([Web] Armory doesnt work)
[//]: # (To find server revision type `.server info` command in the game chat.)

**Description**: Blade of Eternal Darkness has a chance on giving mana to the caster after damage from ability. 

**Current behaviour**:
Seed of corruptions explosion doesn't seem to give mana on AOE targets when it should whereas in classic it does. 
**Expected behaviour**: 
Should give mana when the explosion of the seed of corruption occurs, where each individual target has a chance to proc it. https://www.youtube.com/watch?v=LDcqsGAPsGA&ab_channel=Zqi

Can find more videos if need be! 
**Server Revision**: 
3762

**Comment by Wolffenstein** [comment]
Fixed in rev 3773.
