### ISSUE TITLE
[TK] Kael'thas phoenix timing

### ISSUE THREAD

**Issue by Godmatik** [Atlantiss/NetherwingBugtracker#8391]
The 2.0 version of Kael'Thas (pre-nerf) fight should spawn a phoenix a few seconds after he becomes active. (He should also use a flamestrike immediately once he is active)

Currently does not and just follows the standard phoenix spawn timer. I remember seeing this on PTR and forgot to report it.

Video from classic:
https://www.youtube.com/watch?v=Zv5yCCTluDQ&t=460s&ab_channel=Action

Rev 3762

**Comment by Wolffenstein** [comment]
Fixed in rev 3773.
