### ISSUE TITLE
Blades Edge Mountain quest - Ride the Lightning

### ISSUE THREAD

**Issue by Cyrez85** [Atlantiss/NetherwingBugtracker#8393]
[//]: # (Enclose links to things related to the bug using http://wowhead.com or any other TBC database.)
[//]: # (You can use screenshot ingame to visual the issue.)
[//]: # (Write your tickets according to the format:)
[//]: # ([Quest][Azuremyst Isle] Red Snapper - Very Tasty!)
[//]: # ([NPC] Magistrix Erona)
[//]: # ([Spell][Mage] Fireball)
[//]: # ([Npc][Drop] Ghostclaw Lynx)
[//]: # ([Web] Armory doesnt work)
[//]: # (To find server revision type `.server info` command in the game chat.)

**Description**: Quest item doesnt work on mount, if you abandon the quest and retake it it doesnt work, think it requires a server reset for the item to function but then as soon as you mount it breaks the item again

**Current behaviour**: item bugs out

**Expected behaviour**: previously you could mount unmount etc and reuse the item

**Server Revision**:

**Comment by Cotyle** [comment]
Playing as druid, the item fails when shapeshifting too.

**Comment by Godmatik** [comment]
Can reuse the item just fine with no issue
Probably fixed with aura rework
