### ISSUE TITLE
[Quest] Araj's Scarab - Araj's Phylactery unlootable

### ISSUE THREAD

**Issue by honilbych** [Atlantiss/NetherwingBugtracker#8394]
Link: (https://www.wowhead.com/classic/quest=5804/arajs-scarab

**Description**: 
After killing Elite mob, he spawns his Phylactery from which player should get quest item.
**Current behaviour**:
Phylactery cannot be looted and error " Invalid Target " is only reaction from doing so
**Expected behaviour**: 
Player should be able to open Phylactery like any other box/chest in game.
**Server Revision**: 
Revision : 3763

I have tried it several times. Same broken results everytime. This final quest from chain is for Key to Scholomance dungeon.

**Comment by Godmatik** [comment]
Works just fine for me and I did this quest quite recently, 

I would suggest closing game and deleting cache folder. If that doesn't work, disable addons.

**Comment by honilbych** [comment]
My 2 other guildmates has same problem. I will try your suggestion anyway

**Comment by Godmatik** [comment]
Well perhaps something broke in last couple of days

**Comment by Massie323** [comment]
Did you happen to be in a raid-group while attempting to loot the phylactery? Can't do quests while in a raid.

**Comment by honilbych** [comment]
No comment for this troll question.

**Comment by Godmatik** [comment]
Just tested - was able to loot it no problem.

So very likely cache or addon issue

![Araj](https://user-images.githubusercontent.com/37913400/235546958-b50c41a5-4a43-41bb-a3d3-1cc483143ab7.png)

**Comment by honilbych** [comment]
Turned off all addons, deleted cache once more and same result again. INVALID TARGET 
![image](https://user-images.githubusercontent.com/98527128/235634583-b145ab1c-29cf-418f-9f09-33f6d545338c.png)

BTW I did this quests on many servers ( Endless, new Endless , Sunstrider ) I am key collector and never had this kind of problem.

**Comment by honilbych** [comment]
It's still bugged.

**Comment by EtheriousNW** [comment]
This is 100% a cache issue. Delete cache and it'll work.
