### ISSUE TITLE
Execute being bugged

### ISSUE THREAD

**Issue by Rockyraccooner** [Atlantiss/NetherwingBugtracker#8395]
[//]: # (Enclose links to things related to the bug using http://wowhead.com or any other TBC database.)
[//]: # (You can use screenshot ingame to visual the issue.)
[//]: # (Write your tickets according to the format:)
[//]: # ([Quest][Azuremyst Isle] Red Snapper - Very Tasty!)
[//]: # ([NPC] Magistrix Erona)
[//]: # ([Spell][Mage] Fireball)
[//]: # ([Npc][Drop] Ghostclaw Lynx)
[//]: # ([Web] Armory doesnt work)
[//]: # (To find server revision type `.server info` command in the game chat.)

**Description**: 

Execute beeing bugged.

**Current behaviour**:

You have to do x2 globals of Execute for it to do damage

**Expected behaviour**: 

Should only need to be 1 gcd for it to execute

**Server Revision**:

**Comment by Wolffenstein** [comment]
cant reproduce

**Comment by Rockyraccooner** [comment]
If im streaming and i catch this bug that happens quite frequently. I will post clips until its fixed. 

I cba looking through my vod but im sure you'll find more of the bug there.

https://clips.twitch.tv/SolidAuspiciousReubenSSSsss-SKOO-VanxxUf3_mm

@Wolffenstein
