### ISSUE TITLE
[Dungeon] Auchenai Crypts heroic

### ISSUE THREAD

**Issue by swoer** [Atlantiss/NetherwingBugtracker#8396]
[//]: # (Enclose links to things related to the bug using http://wowhead.com or any other TBC database.)
[//]: # (You can use screenshot ingame to visual the issue.)
[//]: # (Write your tickets according to the format:)
[//]: # ([Quest][Azuremyst Isle] Red Snapper - Very Tasty!)
[//]: # ([NPC] Magistrix Erona)
[//]: # ([Spell][Mage] Fireball)
[//]: # ([Npc][Drop] Ghostclaw Lynx)
[//]: # ([Web] Armory doesnt work)
[//]: # (To find server revision type `.server info` command in the game chat.)

**Description**: 
Packs before the last boss link to each other whenever you pull one.
**Current behaviour**:
The mobs are linked.
**Expected behaviour**: 
The pack should one by one.
**Server Revision**: 
3763

**Comment by Wolffenstein** [comment]
Intended
