### ISSUE TITLE
[NPC] Vashj despawn/reset

### ISSUE THREAD

**Issue by Godmatik** [Atlantiss/NetherwingBugtracker#8398]
**Current behaviour**:
After you either all wipe to the Vashj encounter or reset it - she currently runs back to the middle of her original spawn point. This is causing issues because if someone still has Static Shock debuff on them, she constantly pulls and resets again until the debuff goes away

**Expected behaviour**: 
When resetting, she should completely despawn and then re-appear at her spawn points 30 seconds later. This will prevent the issues of her pulling repeatedly after a reset if someone still has a debuff. See below video.

https://www.youtube.com/watch?v=WjwWLQl8dtg&t=565s&ab_channel=PhilGreenfly

**Server Revision**: 
3763

**Comment by Wolffenstein** [comment]
I can't easily add evade despawn due to the script being old so i will just make it remove the static charge on evade

Fixed in rev 3764.
