### ISSUE TITLE
[Spell][Hunter] Aspect of the Pack not applying to low level chars

### ISSUE THREAD

**Issue by Massie323** [Atlantiss/NetherwingBugtracker#8399]
[//]: # (Enclose links to things related to the bug using http://wowhead.com or any other TBC database.)
[//]: # (You can use screenshot ingame to visual the issue.)
[//]: # (Write your tickets according to the format:)
[//]: # ([Quest][Azuremyst Isle] Red Snapper - Very Tasty!)
[//]: # ([NPC] Magistrix Erona)
[//]: # ([Spell][Mage] Fireball)
[//]: # ([Npc][Drop] Ghostclaw Lynx)
[//]: # ([Web] Armory doesnt work)
[//]: # (To find server revision type `.server info` command in the game chat.)

**Description**: 
Aspect of the Pack should not have any level restrictions for people in the party with a hunter.
I don't know why in #4273 , a single quote of a guy who is unsure "it probably doesnt work on low levels" is taken as proof, when the top comment specifically says "Works on all levels", and additionally gets replied to during TBC patch that the quoted comment is false
![chrome_3T8l4tgvIT](https://user-images.githubusercontent.com/57675820/235469490-d43579cc-25c3-4b8a-92bb-6aaedceea536.png)

![chrome_nVqtsROTNS](https://user-images.githubusercontent.com/57675820/235469501-fefdaa69-2715-4958-9816-b57d65df72b8.png)

**Current behaviour**:
Aspect of the Pack does not work on low level players.

**Expected behaviour**: 
Aspect of the Pack should apply to low level players.

**Server Revision**: 
3763

**Comment by Massie323** [comment]
Crusader Aura appears to suffer from the same issue where low lvl chars don't receive it unless meeting the level requirement of the aura. However, for this one I can't find an explicit WoWhead comment confirming how it should work.

**Comment by Wolffenstein** [comment]
Fixed in rev 3764.
