### ISSUE TITLE
[NPC] Black Dragon Whelp in Redridge Mountains - Missing Spawn

### ISSUE THREAD

**Issue by tcberk12** [Atlantiss/NetherwingBugtracker#840]
**Description**: 
There is a missing Black Dragon Whelp spawn in the Redridge Canyons. This is the gnoll-infested area just north of Lakeshire, more specifically just outside the canyon entrances where many Redridge Brutes and Mystics are.

**Current behaviour**:
No Black Dragon whelp spawns among this camp. These whelps are all across Redridge and drop items for the quest [Underbelly Scales](https://www.wowhead.com/quest=122/underbelly-scales)

I quested in this area for 10-15 minutes and stood here for the duration I wrote this ticket with no sight of the spawn.

**Expected behaviour**: 
There should be at least 1 Black Dragon whelp spawn up in this area, from what I can tell. 

[Retail proof of a player encountering a Black dragon whelp in this area.](https://www.youtube.com/watch?v=cCvrVQAMZGU#t=3m35s)

Not proof, but Classic db says [this mob has a respawn point of 23.8,35.2](http://classicdb.ch/?npc=441#comments).

**Server Revision**: 
2078

**Comment by aresbrutus** [comment]
Confirmed, will be added in one of the next updates
