### ISSUE TITLE
[Spell][Priest]Holy Nova ripping aggro from mobs with 0 threat

### ISSUE THREAD

**Issue by Massie323** [Atlantiss/NetherwingBugtracker#8400]
[//]: # (Enclose links to things related to the bug using http://wowhead.com or any other TBC database.)
[//]: # (You can use screenshot ingame to visual the issue.)
[//]: # (Write your tickets according to the format:)
[//]: # ([Quest][Azuremyst Isle] Red Snapper - Very Tasty!)
[//]: # ([NPC] Magistrix Erona)
[//]: # ([Spell][Mage] Fireball)
[//]: # ([Npc][Drop] Ghostclaw Lynx)
[//]: # ([Web] Armory doesnt work)
[//]: # (To find server revision type `.server info` command in the game chat.)

**Description**: 
While Holy Nova correctly generates 0 threat for both damage and healing done, it seems to still rip aggro on mobs that have 0 threat on them from a 2nd person. Think of someone face-pulling a mob or a chain-pull where mobs target a person that otherwise has 0 threat.

The priest will rip aggro in any interaction with Holy Nova, whether he hits both tank & mob, only the tank, or only the mob - If there is 0 threat on the mob, the priest will rip aggro with Holy Nova.

**Current behaviour**:
Holy Nova rips aggro from 0 threat mobs.

**Expected behaviour**: 
Holy Nova should not cause aggro changes.

**Server Revision**: 
3763

https://user-images.githubusercontent.com/57675820/235492023-41d299bd-c175-4430-95a0-46f827d15de6.mp4

**Comment by Wolffenstein** [comment]
Fixed in rev 3772.

**Comment by Massie323** [comment]
based
