### ISSUE TITLE
[Spell] channeling spells cancel after targeting smth out of range

### ISSUE THREAD

**Issue by RatOnMe** [Atlantiss/NetherwingBugtracker#8401]
**Description**: targeting someone out of range while channeling a cast (checked with arcane missiles that requires a target and blizzard that isnt) will result in canceling cast
outrange required to cancel a cast seems to be any outrange for npc-targeting spells and like 100y+ for ground-targeting spells
when cast was canceled, there is still a visual effect for it (in case of blizzard) or no effect (in case of missiles)
if moving, there will be a sound of interrupted cast
[on screen: no cast bar (should be right near mana bar), blizzard drops on polyed wolf but doesnt break it, targeted wolf is somewhere near open world visibility max range](https://cdn.discordapp.com/attachments/958331741624483902/1102855943366135858/image.png)
almost not a problem outside bgs but a cancer inside
prob mind flay hellfire rain of fire hurricane tranquility will have the same issue
bandaging self (havent checked bandaging some1 else) or channeling evocation (doesnt need any target) is not affected by this bug

**Current behaviour**: targeting someone out of range while channeling a cast (checked with arcane missiles that requires a target and blizzard that isnt) will result in canceling cast

**Expected behaviour**: targeting someone out of range while channeling a cast shouldnt interrupt it

**Server Revision**: right from launch, last check 3763

**Comment by Wolffenstein** [comment]
Fixed in rev 3961.
