### ISSUE TITLE
[Spell] mortar:reloaded

### ISSUE THREAD

**Issue by RatOnMe** [Atlantiss/NetherwingBugtracker#8403]
**Description**: goblin engi cant learn mortar: reloaded recipe from any (goblin or general) engi teachers

**Current behaviour**: goblin engi cant learn mortar: reloaded recipe from any (goblin or general) engi teachers

**Expected behaviour**: goblin engi can learn mortar: reloaded recipe from any (goblin or general) engi teachers

**Server Revision**: right from lunch last check 3763

**Comment by Wolffenstein** [comment]
Fixed in rev 3764.
