### ISSUE TITLE
flying machine and turbo-charged flying machine

### ISSUE THREAD

**Issue by RatOnMe** [Atlantiss/NetherwingBugtracker#8404]
**Description**: [yep its not a bug but how about letting engineers fly on lovely crafted precious things instead of shitty stock wyverns/gryphons](https://github.com/Atlantiss/NetherwingBugtracker/issues/2789)

yep u dont allow to craft epic googles and i can understand it (well, kinda can, cuz it pales in comparison to bs craft weapons)
but crafting a mount instead of buying one isnt a gamebreaking thing

**Comment by Godmatik** [comment]
This github is for bugs, suggestions should go on discord
