### ISSUE TITLE
[ITEM] Staff of Natural Fury (Mana Cost)

### ISSUE THREAD

**Issue by Niglathag** [Atlantiss/NetherwingBugtracker#8405]
[//]: # (Enclose links to things related to the bug using http://wowhead.com or any other TBC database.)
[//]: # (You can use screenshot ingame to visual the issue.)
[//]: # (Write your tickets according to the format:)
[//]: # ([Quest][Azuremyst Isle] Red Snapper - Very Tasty!)
[//]: # ([NPC] Magistrix Erona)
[//]: # ([Spell][Mage] Fireball)
[//]: # ([Npc][Drop] Ghostclaw Lynx)
[//]: # ([Web] Armory doesnt work)
[//]: # (To find server revision type `.server info` command in the game chat.)

**Description**: 
[Staff of Natural Fury] dont reduce the mana cost for your shapeshifting spells properly.
Link: [Https://www.wowhead.com/tbc/item=31334/staff-of-natural-fury](url)

**Current behaviour**:
Bear = 580 > 440
Cat = 580 > 440
Travel = 215 > 75
Aquatic = 215 > 75
Flight = 215 > 75

Just and example with my Cat form:

![NO](https://user-images.githubusercontent.com/68473571/235702744-18cbaa82-c41b-4e5b-8523-bf2c8061d972.png)
![SI](https://user-images.githubusercontent.com/68473571/235701492-f91ff3eb-009e-4c9c-82e1-25ed74259767.png)

**Expected behaviour**: 
Since the item reduces the "BASIC" mana cost, it should look like this:
Bear = 580 > 380
Cat = 580 > 380           
Travel = 215 > 15
Aquatic = 215 > 15
Flight = 215 > 15.

**Server Revision**: 
3762

**Comment by Godmatik** [comment]
It is less I'm assuming because you have the 30% mana reduction for shapeshifting talents, so I believe it is intended, but will let someone else verify

**Comment by Godmatik** [comment]
Wowhead comments agree, the 200 mana reduction is before any talents (Natural Shapeshifter), so this doesn't appear to be a bug
