### ISSUE TITLE
([Spell][Mage] Water Elemental)

### ISSUE THREAD

**Issue by Portabless** [Atlantiss/NetherwingBugtracker#8406]
([Spell][Mage] Water Elementall)

**Description**: Water elemental does not respond to being put to passive like it should. When you cast with your water elemental and set it to passive it is supposed to cancel cast and move towards player, you may need to put it on follow but usually you have your pet on follow by default. 

**Current behaviour**: Water Elemental keeps casting to finish cast, breaks sheeps, attacks when its not suppose to(pet dies to unresponsiveness, example shade of aran when he does arcane explosion).

**Expected behaviour**:  Water Elemental is supposed to cancel when you put it to passive nomatter what the previous setting was on aggresive/defensive/passive. So even if it is already on passive and you have manually used keybind or clicked attack on your pet bar you should be able to put passive and it stops.

**Server Revision**:  3763

**Comment by Wolffenstein** [comment]
Fixed in rev 3764.
