### ISSUE TITLE
[ITEM] Golden Pearl (Drop Rate)

### ISSUE THREAD

**Issue by sepehr-72** [Atlantiss/NetherwingBugtracker#8407]
Description:
[Golden Pearl] drop rate is too high and its not normal at all. a game master confirmed its not standard like blizzard, he asked me to write the problem here because developers can fix this bug
Link: https://www.wowhead.com/tbc/item=13926

Expected behaviour:
https://nexushub.co/wow-classic/items/golden-pearl

**Comment by Wolffenstein** [comment]
Fixed in rev 3764.
