### ISSUE TITLE
PWS Invalid Target

### ISSUE THREAD

**Issue by ghost** [Atlantiss/NetherwingBugtracker#8408]
**Description**: 

**Current behaviour**: Getting `Invalid Target` error when trying to apply Power Word: Shield on some teammates in battlegrounds. Never had this issue before, so its probably new.
This is the macro im using:
```
/stopcasting [harm]
/cancelaura [harm]Power Word: Shield
/cast [help]Power Word: Shield(Rank 12);Shadow Word: Death(Rank 1)
```

**Expected behaviour**: 

**Server Revision**: 3763

**Comment by Godmatik** [comment]
Do they have weakened soul debuff?

**Comment by ghost** [comment]
BTW it's not just PWS... other spells are affected too, like Prayer of Mending.
Potentially caused by the racial swap feature. If you pick an alliance race and your target swapped to (a different) horde race.

**Comment by Wolffenstein** [comment]
Does this happen in arenas as well? Also a video would be nice, or at least a screenshot of who is trying to cast it on who (so I can reproduce the same swapped races which I believe is the issue)

**Comment by Wolffenstein** [comment]
Fix pending in rev 3771

**Comment by ghost** [comment]
still happening in BGs, no idea why
