### ISSUE TITLE
[Shattered Halls][NPC] Shattered Hand Houndmaster not using emote when cleansing debuffs

### ISSUE THREAD

**Issue by Massie323** [Atlantiss/NetherwingBugtracker#8410]
[//]: # (Enclose links to things related to the bug using http://wowhead.com or any other TBC database.)
[//]: # (You can use screenshot ingame to visual the issue.)
[//]: # (Write your tickets according to the format:)
[//]: # ([Quest][Azuremyst Isle] Red Snapper - Very Tasty!)
[//]: # ([NPC] Magistrix Erona)
[//]: # ([Spell][Mage] Fireball)
[//]: # ([Npc][Drop] Ghostclaw Lynx)
[//]: # ([Web] Armory doesnt work)
[//]: # (To find server revision type `.server info` command in the game chat.)

**Description**: 
Shattered Hand Houndmaster has an obscure mechanic where they will remove ALL debuffs from nearby mobs and yell "You cannot stop us!". Right now, however, they will only do the emote once, when they should yell it every time they dispel the debuffs.

**Current behaviour**:
Shattered Hand Houndmaster isn't doing his /yell every time he dispells.

**Expected behaviour**: 
Shattered Hand Houndmaster should yell "You cannot stop us!" each time he dispels everyone.

**Server Revision**: 
3763

https://user-images.githubusercontent.com/57675820/236069059-f9a4db08-91f1-4533-bda9-abf67819a2e8.mp4
Video showcasing current behaviour

https://youtu.be/luwriRn_eQ8?t=259
Video showcasing correct behaviour (on Wotlk patch)

**Comment by Wolffenstein** [comment]
Fixed in rev 3767.
