### ISSUE TITLE
[Weapon] Rivenspike and Bashguuder

### ISSUE THREAD

**Issue by Ingenerstr** [Atlantiss/NetherwingBugtracker#8411]
[//]: # (Enclose links to things related to the bug using http://wowhead.com or any other TBC database.)
[//]: # (You can use screenshot ingame to visual the issue.)
[//]: # (Write your tickets according to the format:)
[//]: # ([Quest][Azuremyst Isle] Red Snapper - Very Tasty!)
[//]: # ([NPC] Magistrix Erona)
[//]: # ([Spell][Mage] Fireball)
[//]: # ([Npc][Drop] Ghostclaw Lynx)
[//]: # ([Web] Armory doesnt work)
[//]: # (To find server revision type `.server info` command in the game chat.)

**Description**: https://www.wowhead.com/tbc/item=13286/rivenspike , https://www.wowhead.com/tbc/item=13204/bashguuder . 

**Current behaviour**: Both weapons have very very low procs "Punctures target's armor lowering it by 200. Can be applied up to 3 times". At the moment it almost doesn't work. 1 proc in 500-600 hits. Even if you attack level 55 mobs. There shouldn't be such a low procs on these weapons.

**Expected behaviour**: Increase the chance of proсs on these weapons.

**Server Revision**:

**Comment by Wolffenstein** [comment]
Fixed in rev 3767.
