### ISSUE TITLE
[TK] Solarian melee

### ISSUE THREAD

**Issue by Godmatik** [Atlantiss/NetherwingBugtracker#8413]
**Description**: 
Solarian fight in Tempest Keep

**Current behaviour**:
Solarian occasionally throws in melee swings in between casts (during her caster form). Also causes issues that if someone pulls threat from main tank, she will for a split second move to that individual attempting to melee.

**Expected behaviour**: 
As far as I am aware, she should never melee, should only spam cast arcane missiles to targets in front of her (in between her other special abilities)

**Server Revision**: 
3764

**Comment by Wolffenstein** [comment]
afaik not a bug same as Aran
