### ISSUE TITLE
[Spell][Warrior] One-handed weapon specialization does not appear to affect Shield Slam (possibly other spells)

### ISSUE THREAD

**Issue by Xpd1** [Atlantiss/NetherwingBugtracker#8414]
**Description**: 
While browsing through ElitistJerks protection warrior guide article from 2007 (https://web.archive.org/web/20150802020137/http://forums.elitistjerks.com/topic/18617-the-protection-guide/) i noticed a statement:
 
"It should be noted that 1HWS will increase the damage done by all of your offensive abilities by 10% - this includes shield slam, devastate, HS, etc. It will strictly speaking, be better point-for-point than cruelty. However, in a threat build, you would have both talents anyway."

And the way talent was worded also appears to imply all physical spells are affected by it.

**Current behaviour**:
From my limited testing ability it appears One-handed weapon specialization is only affecting white swings, my auto attacks were properly modified by 10% while shield slam (and possibly other spells) did not appear to be modified at all.
**Expected behaviour**: 
According to the article, all offensive spells are supposed to be affected by 10% physical damage increase of One-handed weapon specialization.

**Server Revision**: 
3765

**Comment by Wolffenstein** [comment]
Fixed in rev 3767.
