### ISSUE TITLE
Pets while MCed

### ISSUE THREAD

**Issue by Godmatik** [Atlantiss/NetherwingBugtracker#8418]
**Current behaviour**:
Pets can sometimes target yourself and kill you when you are mind controlled by Vashj, see below screenshot

**Expected behaviour**: 
Should not

**Server Revision**: 
3766

![petszzz](https://user-images.githubusercontent.com/37913400/236698153-e961a53e-c334-4f1c-a738-e7493525a542.png)

**Comment by Wolffenstein** [comment]
Maybe fixed in rev 3767. If not then make a new issue please
