### ISSUE TITLE
([Spell][Rogue] Cloak of Shadows and Gruul's Shatter

### ISSUE THREAD

**Issue by AndrewNB41191** [Atlantiss/NetherwingBugtracker#8419]
([Spell][Rogue] Cloak of Shadows and Gruul's Shatter
**Description**: 
Cloak of shadows is not working properly with gruuls shatter
**Current behaviour**:
Using Cloak of Shadows currently removes the increasing slow from shatter and instantly freezes you in place. 5 sec later you get damaged as usual.
**Expected behaviour**: 
Using Cloak should remove the slow and give you the 5 seconds to reposition yourself at normal speed. and then you freeze in place and shatter. It appears that improved sprint (100%chance of removing movement impairing effects) works properly. This worked properly on the last version of this server i played (Netherwing 1)
**Server Revision**: 
server revision #3766

**Comment by Wolffenstein** [comment]
Fixed in rev 3837.
