### ISSUE TITLE
Mob, Spawn point, Alterac Mountains

### ISSUE THREAD

**Issue by Erodraeda** [Atlantiss/NetherwingBugtracker#842]
[//]: # (Enclose links to things related to the bug using http://wowhead.com or any other TBC database.)
[//]: # (You can use screenshot ingame to visual the issue.)
[//]: # (Write your tickets according to the format:)
[//]: # ([Quest][Azuremyst Isle] Red Snapper - Very Tasty!)
[//]: # ([NPC] Magistrix Erona)
[//]: # ([Spell][Mage] Fireball)
[//]: # ([Npc][Drop] Ghostclaw Lynx)
[//]: # ([Web] Armory doesnt work)

**Description**: 
Dalaran Summoner (2358, ID. 3) spawning on top of the window, and can't attack him because of line of sight.
**Current behaviour**:
![screenshot_502](https://user-images.githubusercontent.com/40346279/46236231-2ded5d80-c354-11e8-9258-67349d94535c.png)
![screenshot_503](https://user-images.githubusercontent.com/40346279/46236232-2ded5d80-c354-11e8-97e8-1032e3ac87d8.png)
**Expected behaviour**: 
Shouldn't be spawned there.
**Server Revision**:

**Comment by aresbrutus** [comment]
Will be fixed in one of the next updates.
