### ISSUE TITLE
Battleground que issue

### ISSUE THREAD

**Issue by Nexmijus** [Atlantiss/NetherwingBugtracker#8420]
[**Description**:]After battleground ends, and you try to join queue again it gives message "You are not in a battleground".

**Current behaviour**:After battleground ends, and you try to join queue again it gives message "You are not in a battleground".

**Expected behaviour**: n/a

**Server Revision**: n/a

**Comment by Godmatik** [comment]
Unable to reproduce.

Perhaps was fixed
