### ISSUE TITLE
[Spell][Priest] Mind Flay channel instantly breaks, but debuff remains on target

### ISSUE THREAD

**Issue by Massie323** [Atlantiss/NetherwingBugtracker#8421]
[//]: # (Enclose links to things related to the bug using http://wowhead.com or any other TBC database.)
[//]: # (You can use screenshot ingame to visual the issue.)
[//]: # (Write your tickets according to the format:)
[//]: # ([Quest][Azuremyst Isle] Red Snapper - Very Tasty!)
[//]: # ([NPC] Magistrix Erona)
[//]: # ([Spell][Mage] Fireball)
[//]: # ([Npc][Drop] Ghostclaw Lynx)
[//]: # ([Web] Armory doesnt work)
[//]: # (To find server revision type `.server info` command in the game chat.)

**Description**: 
Casting Mindflay will occasionally instantly cancel the channel, but still apply the debuff to the target, dealing full damage.

**Current behaviour**:
Casting Mindflay will occasionally instantly cancel the channel, but still apply the debuff to the target, dealing full damage.

**Expected behaviour**: 
Mindflay channel shouldn't randomly break (outside of resists etc.).

**Server Revision**: 
3766

https://user-images.githubusercontent.com/57675820/236837399-4983b2c0-9e3c-4277-9a5f-cf5050bf8835.mp4

**Comment by Godmatik** [comment]
More info also presented here:
https://github.com/Atlantiss/NetherwingBugtracker/issues/7630

This affects all channeled abilities

**Comment by Godmatik** [comment]
Fixed some months ago - closing
