### ISSUE TITLE
Warsong Gulch flag carrier bug

### ISSUE THREAD

**Issue by Nexmijus** [Atlantiss/NetherwingBugtracker#8422]
**Description**: Enemy flag carrier runs in place and cannot be attacked by meele attacks,only by ranged or spell attacks, gives out of range speech.

**Current behaviour**:

**Expected behaviour**: 

**Server Revision**:

**Comment by Godmatik** [comment]
?

**Comment by Wolffenstein** [comment]
no idea what this means
