### ISSUE TITLE
feral druids not benefiting from Fel Mana Pots in feral form. 

### ISSUE THREAD

**Issue by DMN7** [Atlantiss/NetherwingBugtracker#8423]
[//]: # (Enclose links to things related to the bug using http://wowhead.com or any other TBC database.)
https://www.wowhead.com/tbc/guide/classes/druid/feral/dps-consumables-raid-buffs-pve
[//]: # (You can use screenshot ingame to visual the issue.)
https://imgur.com/a/saFNhON
[//]: # (Write your tickets according to the format:)
[//]: # ([Quest][Azuremyst Isle] Red Snapper - Very Tasty!)
[//]: # ([NPC] Magistrix Erona)
[//]: # ([Spell][Mage] Fireball)
[//]: # ([Npc][Drop] Ghostclaw Lynx)
[//]: # ([Web] Armory doesnt work)
[//]: # (To find server revision type `.server info` command in the game chat.)

**Description**: 
feral druids not benefiting from Fel Mana Pots in feral form
**Current behaviour**:
when using the mana pot we dont regen mana in feral form.
**Expected behaviour**: 
as posted in the wowhead guide its the best potion to use for powershifting feral druids.
**Server Revision**:

**Comment by Peglaa** [comment]
This is done with powershifting macros, no? As far as I'm aware cat and bear form can't use pots in TBC. You would use a macro to shift you out of form, use the potion and then shift back.

**Comment by DMN7** [comment]
yes you use a macro with powershifting and using a pot gets you out of form, but since fel mana pot gives you a timed mana release, you should be still getting mana back in feral form. like how we get mana from judgement of wisdom, mana totem, blessing of wisdom, ect in feral form

**Comment by Wolffenstein** [comment]
Can you record a video? I just used the potion, went into cat form with near 0 mana and once the effect ended I left the cat form and had ~3k mana so seems to be working fine?

**Comment by DMN7** [comment]
> Can you record a video? I just used the potion, went into cat form with near 0 mana and once the effect ended I left the cat form and had ~3k mana so seems to be working fine?

sorry im stupid, this totally works it was just my addon. its working fine! ty

**Comment by Godmatik** [comment]
you can close the report yourself just FYI :)
