### ISSUE TITLE
[NPC] AOE Pulls in open world

### ISSUE THREAD

**Issue by marcinkroszel** [Atlantiss/NetherwingBugtracker#8425]
[//]: # (Enclose links to things related to the bug using http://wowhead.com or any other TBC database.)
[//]: # (You can use screenshot ingame to visual the issue.)
[//]: # (Write your tickets according to the format:)
[//]: # ([Quest][Azuremyst Isle] Red Snapper - Very Tasty!)
[//]: # ([NPC] Magistrix Erona)
[//]: # ([Spell][Mage] Fireball)
[//]: # ([Npc][Drop] Ghostclaw Lynx)
[//]: # ([Web] Armory doesnt work)
[//]: # (To find server revision type `.server info` command in the game chat.)

**Description**: 
Hi, aoe pulls in the open world are impossible because mobs reset.

**Current behaviour**:
When pulling multiple mobs in the open world while I keep attacking them e.g. (casting blizzard rank1 or consecration rank1) they reset after running too far away from their initial spawn location.

**Expected behaviour**: 
I should be able to pull multiple mobs in the open world if I keep attacking them.
Here is a video example, see from 2:38:00 how the author begins the pull and then keeps casting consecration to gather more mobs in one spot.

https://www.youtube.com/watch?v=v5gf6aDvcOw&ab_channel=GetCarried

If needed I can provide more examples. I was also playing on TBC Classic before Wrath came out and such pulls were possible.

**Server Revision**: 
3766

**Comment by Wolffenstein** [comment]
Fixed in rev 3773.
