### ISSUE TITLE
[AQ20]Ossirian The Unscarred continues to resist spell school despite debuffed by Crystal

### ISSUE THREAD

**Issue by Massie323** [Atlantiss/NetherwingBugtracker#8426]
[//]: # (Enclose links to things related to the bug using http://wowhead.com or any other TBC database.)
[//]: # (You can use screenshot ingame to visual the issue.)
[//]: # (Write your tickets according to the format:)
[//]: # ([Quest][Azuremyst Isle] Red Snapper - Very Tasty!)
[//]: # ([NPC] Magistrix Erona)
[//]: # ([Spell][Mage] Fireball)
[//]: # ([Npc][Drop] Ghostclaw Lynx)
[//]: # ([Web] Armory doesnt work)
[//]: # (To find server revision type `.server info` command in the game chat.)

**Description**: 
Ossirian is normally neigh immune to every spell school (bar holy). But if you click one of the Crystals, he will receive a random debuff to a school, decreasing his resistance and also doubling the damage received from that school.
Right now however, it seems like the resistance is not properly reduced, resulting in something like 8 spells being fully resisted/heavily partial resisted in a row, although if it doesn't resist it correctly does double damage

**Current behaviour**:
Ossirian continue to heavily resist his weakened school.

**Expected behaviour**: 
Ossirian's weakness school resistance should be reduced by 100%

**Server Revision**: 
3766

**Comment by Wolffenstein** [comment]
Fixed in rev 3830.
