### ISSUE TITLE
Mana-Etched 4-set bonus is not working

### ISSUE THREAD

**Issue by Hollycz** [Atlantiss/NetherwingBugtracker#8428]
**Description**: 
Blue set called **Mana-Etched** 4-set bonus is not working
**Current behaviour**:
Mana-Etched 4-set bonus doesnt proc 110 spelldamage and healing for 15 seconds at all. (tested 5 days during load of dungeons and pvp on character - Unholy)
**Expected behaviour**: 
Mana-Etched 4-set bonus should have a chance to gain 110 spelldamage and healing for 15 seconds.
**Server Revision**: 
3766

**Comment by Godmatik** [comment]
https://www.wowhead.com/tbc/spell=37619/spell-power-bonus#comments

2% proc chance, doesn't appear to have any ICD

**Comment by Wolffenstein** [comment]
Fixed in rev 3786.
