### ISSUE TITLE
Target Dummy not exploding

### ISSUE THREAD

**Issue by Foodlenz** [Atlantiss/NetherwingBugtracker#8429]
**Description**: Target dummy should explode after a certain time if it hasn't died from enemy damage.

**Current behaviour**: Target dummy will follow you if it aggro's a mob and then you kill that mob before it kills the target dummy.

https://github.com/Atlantiss/NetherwingBugtracker/assets/72258441/629bd968-6cc6-4fd8-a1df-e829a80a5737

**Expected behaviour**:  Target dummy should 1) Stationary. 2) Explode after a given time.

**Server Revision**: 3766

**Comment by Wolffenstein** [comment]
Fixed in rev 3773.
