### ISSUE TITLE
Inconsistencies with epic pvp gems properties

### ISSUE THREAD

**Issue by Red86** [Atlantiss/NetherwingBugtracker#8430]
Hi,
I used my honor to buy two gems:

-Smooth Ornate Dawnstone
-Inscribed Ornate Topaz

I am already using both gems in my gear but I wanted to buy more in the prevision of future upgrades to have them ready.

I could buy the gems just fine however, while I am able to move Inscribed Ornate Topaz around my inventory and to/from the bank, I cannot do the same with the Smooth Ornate Dawnstone.

Trying to move it from one bag to another in my inventory or trying to move it to the bank will result in a "Can't carry anymore of those items" message. I tried to relog and the gem was gone from my inventory and bank so, I tried to buy it again only to be met with same error "can't carry anymore of those items"

I noticed then I had mail from Customer Support who had mailed me both of the gems that had vanished. However I cannot get them out of the mail due to the same "can't carry anymore of those items" error.

There seems to be an inconsistency in how the rules for those two gems are being handled. Smooth ornate dawnstone is labeled as "unique" whereas Inscribed ornate topaz is "unique-equipped".

If the gem is indeed unique, the server should prevent you from buying it if you're already using it or have it in your bags/bank.

**Comment by Godmatik** [comment]
Issue has already been reported, hopefully fixed soon.

https://github.com/Atlantiss/NetherwingBugtracker/issues/8417
https://github.com/Atlantiss/NetherwingBugtracker/issues/8380

**Comment by Wolffenstein** [comment]
Fixed in rev 3772.
