### ISSUE TITLE
KT - Phoenix spawn evade

### ISSUE THREAD

**Issue by Godmatik** [Atlantiss/NetherwingBugtracker#8431]
**Current behaviour**:
If an Phoenix egg hatches in the middle of Gravity Lapse in final phase, and the phoenix spawns while everyone is still in the air, it will permanently evade, stay in place, and not chase anyone after you land.

**Server Revision**: 
3770

**Comment by Godmatik** [comment]
https://clips.twitch.tv/TentativeDelightfulEggplantPhilosoraptor-cwFgrsXAz7wWyyV-

**Comment by Wolffenstein** [comment]
Fixed in rev 3834.
