### ISSUE TITLE
KT - Legendary Weapons did not expire

### ISSUE THREAD

**Issue by Godmatik** [Atlantiss/NetherwingBugtracker#8432]
**Current behaviour**:
After 15 minutes were passed, legendary weapons in the Kael'thas fight not expire. Rather, the timer was refreshed to 15 minutes and the weapon was still equipped. I used an oil on it if that makes any difference.

**Expected behaviour**: 
Should expire after 15 minutes

**Server Revision**: 
3770

**Comment by Wolffenstein** [comment]
Fixed in rev 3772.
