### ISSUE TITLE
KT - Legendary Shield corpse does not despawn, sometimes bow as well

### ISSUE THREAD

**Issue by Godmatik** [Atlantiss/NetherwingBugtracker#8433]
**Current behaviour**:
In the Kael'thas fight - when the shield is killed ("Phaseshift Bulwark"), the lootable corpse should go away after 60 seconds. However it does not and always stays on the ground for several minutes instead. This also sometimes (but not always) occurs with the bow ("Netherstrand Longbow")

**Expected behaviour**: 
All lootable weapons on the ground should despawn after 60 seconds.

**Server Revision**: 
3770

https://www.wowhead.com/tbc/item=30318/netherstrand-longbow
https://www.wowhead.com/item=30314/phaseshift-bulwark

**Comment by Wolffenstein** [comment]
Fixed in rev 3772.
