### ISSUE TITLE
[Item] Annihilator

### ISSUE THREAD

**Issue by MoonSeYoun** [Atlantiss/NetherwingBugtracker#8434]
**Description**: Annihilator should be Main-hand only until swp (2.4 patch) comes out 

**Current behaviour**: Annihilator is One-hand.

**Expected behaviour**: Annihilator should be Main-hand only.

**Server Revision**: 3770
https://www.wowhead.com/tbc/news/new-update-on-burning-crusade-beta-instant-level-70-realm-item-changes-vendors-321794
![23233](https://github.com/Atlantiss/NetherwingBugtracker/assets/130842957/742eba5d-5219-4e01-a1a7-ccc66a15da5a)
https://wowwiki-archive.fandom.com/wiki/Patch_2.4.2
![mainhand](https://github.com/Atlantiss/NetherwingBugtracker/assets/130842957/2a8c0dc2-f5da-4fc5-b741-e36e94a5b678)

**Comment by Wolffenstein** [comment]
Fixed in rev 3772.
