### ISSUE TITLE
[SSC] Lurker - Geyser hitting tank

### ISSUE THREAD

**Issue by Godmatik** [Atlantiss/NetherwingBugtracker#8438]
**Current behaviour**:
Lurker ability "Geyser" has a chance to hit and knockback the main tank.

**Expected behaviour**: 
Lurker ability "Geyser" should not hit the person who has top threat, which is the main tank.

I suspect what is happening is that a ranged DPS has higher threat that the main tank - Lurker can only attack someone in melee range - but this allows the main tank to be eligible for being hit by geyser ability.

**Server Revision**: 
3770

https://www.wowhead.com/tbc/spell=37478/geyser

![Geyser](https://github.com/Atlantiss/NetherwingBugtracker/assets/37913400/675a1035-0795-4fb7-a65d-aad1be1ddb01)

**Comment by Wolffenstein** [comment]
Where did you get the info that it shouldn't target tanks?

Geyser: Randomly attacks any player, causing 3-4k Frost damage to everyone within ~10 yards of the target, as well as a ~10-yard knockback to all affected.

**Comment by Godmatik** [comment]
It was from an obscure website to be honest.

https://www.tentonhammer.com/guides/serpentshrine-cavern-guide-the-lurker-below

When I'm not lazy, I'll review TBC classic logs to see if I can find actual proof

**Comment by Godmatik** [comment]
Got proof that geyser hits tank in classic, closing

:(

**Comment by Godmatik** [comment]
It's confirmed that tanks get hit by geyser =(

Closing
