### ISSUE TITLE
Wand - Switiching Targets issue

### ISSUE THREAD

**Issue by Stilstkin** [Atlantiss/NetherwingBugtracker#844]
[//]: # (Enclose links to things related to the bug using http://wowhead.com or any other TBC database.)
[//]: # (You can use screenshot ingame to visual the issue.)
[//]: # (Write your tickets according to the format:)
[//]: # ([Quest][Azuremyst Isle] Red Snapper - Very Tasty!)
[//]: # ([NPC] Magistrix Erona)
[//]: # ([Spell][Wand) Shoot

**Description**: You cant shoot other mobs while in combat

**Current behaviour**: if you shoot 1 mob and get in combat you, cant shoot other mobs., it says, interupted

**Expected behaviour**:  You should be able to shoot as much mobs as you want regardless beign into combat

**Server Revision**:

**Comment by tcberk12** [comment]
I cannot reproduce this based off your description. I get in combat with 1 mob via wanding, and can transition to wanding another mob I am not in combat with (yet) no problem.

**Comment by Stilstkin** [comment]
Oh, i tested it out couple of times now and it doesnt happen when i right click the mob i want to tag, but when i just left click him it keeps shoting the last target. Idk thats maybe the way it works

**Comment by tcberk12** [comment]
I can reproduce this with left click.

**Comment by Wolffenstein** [comment]
Seems invalid? Please reopen when you have video footage.
