### ISSUE TITLE
[Dungeon][Auchenai Crypts][NPC] Possessors possessing after death

### ISSUE THREAD

**Issue by owliepecks** [Atlantiss/NetherwingBugtracker#8441]
[//]: # (Enclose links to things related to the bug using http://wowhead.com or any other TBC database.)
[//]: # (You can use screenshot ingame to visual the issue.)
[//]: # (Write your tickets according to the format:)
[//]: # ([Quest][Azuremyst Isle] Red Snapper - Very Tasty!)
[//]: # ([NPC] Magistrix Erona)
[//]: # ([Spell][Mage] Fireball)
[//]: # ([Npc][Drop] Ghostclaw Lynx)
[//]: # ([Web] Armory doesnt work)
[//]: # (To find server revision type `.server info` command in the game chat.)

**Description**:  In AC normal, Phantasmal Possessor continues to possess a player after the mob is killed, and the player remains possessed until combat has ended with all other mobs

**Current behaviour**: Player remains possessed for entirety of the fight, even if the possessor is killed.

**Expected behaviour**: I would assume the player should be able to take over their character as soon as the possessor is dead. We have done this dungeon on normal before and never had this issue.

**Server Revision**:

**Comment by Godmatik** [comment]
Just reading the wowhead comments, it sounds blizzlike. 

Lasts one minute and doesn't go away until the duration finishes (or the MCed player dies).

I'll let someone else verify though.
