### ISSUE TITLE
Combat bug at farm on AB

### ISSUE THREAD

**Issue by cardyb27** [Atlantiss/NetherwingBugtracker#8442]
[//]: # ([NPC] Critters at farm in AB
[//]: # ([Spell] Any type of AOE
[//]: # ([Npc]Chickens and rats

**Description**: In AB at farm, there are many critters like chickens and rats. (No not alliance). Whenever someone does AOE at farm like demo shout for example (doesnt kill the critters but tags or activates them) you will stay in combat until you die. This can impact the game at times because you cant mount up and defend the nodes throughout the map.

I'm almost certain that the critters are the issue because I started going around killing all the chickens and rats I could find at farm and eventually when i killed one of the I got out of combat. 

Thanks

**Comment by tsu-1** [comment]
On retail these critters are non targetable, like RP NPCs on those bases.

**Comment by Wolffenstein** [comment]
Fixed in rev 3786.
