### ISSUE TITLE
Malygen not selling Recipe: Juicy Bear Burger

### ISSUE THREAD

**Issue by sevo92** [Atlantiss/NetherwingBugtracker#8444]
[//]: # ([Enclose links to things related to the bug using http://wowhead.com or any other TBC database](https://www.wowhead.com/tbc/npc=2803/malygen).)
[//]: # (You can use screenshot ingame to visual the issue.)
[//]: # (Write your tickets according to the format:)
[//]: # ([Quest][Azuremyst Isle] Red Snapper - Very Tasty!)
[//]: # ([NPC] Magistrix Erona)
[//]: # ([Spell][Mage] Fireball)
[//]: # ([Npc][Drop] Ghostclaw Lynx)
[//]: # ([Web] Armory doesnt work)
[//]: # (To find server revision type `.server info` command in the game chat.)

**Description**: Malygen is not selling Recipe: Juicy Bear Burger and Recipe: Charred Bear Kabobs

**Current behaviour**: Not selling Recipe: Juicy Bear Burger and Recipe: Charred Bear Kabobs

**Expected behaviour**: Malygen should be selling Recipe: Juicy Bear Burger and Recipe: Charred Bear Kabobs

**Server Revision**: 2.4.3

**Comment by Godmatik** [comment]
Not available until patch 2.4, we are currently on 2.0
