### ISSUE TITLE
[Mission: Possible But Not Probable] bugged

### ISSUE THREAD

**Issue by loquatdonut** [Atlantiss/NetherwingBugtracker#8446]
[//]: # (Enclose links to things related to the bug using http://wowhead.com or any other TBC database.)
https://www.wowhead.com/classic/quest=2478/mission-possible-but-not-probable

Even though I have a key - the chest is locked

Picture:
https://imgur.com/a/FiBme0q

**Comment by loquatdonut** [comment]
Picture 2:

https://imgur.com/a/nStoiDq

**Comment by Godmatik** [comment]
As I told you in discord - this is not a bug.
The chest does not use the key, the key is only for the quest.
You unlock the chest with high enough lockpicking -  the wowhead comments say the same
