### ISSUE TITLE
API SetRaidSubgroup Issue

### ISSUE THREAD

**Issue by Demge** [Atlantiss/NetherwingBugtracker#8447]
[//]: # (Enclose links to things related to the bug using http://wowhead.com or any other TBC database.)
[//]: # (You can use screenshot ingame to visual the issue.)
[//]: # (Write your tickets according to the format:)
[//]: # ([Quest][Azuremyst Isle] Red Snapper - Very Tasty!)
[//]: # ([NPC] Magistrix Erona)
[//]: # ([Spell][Mage] Fireball)
[//]: # ([Npc][Drop] Ghostclaw Lynx)
[//]: # ([Web] Armory doesnt work)
[//]: # (To find server revision type `.server info` command in the game chat.)

**Description**: The API function SetRaidSubgroup() is currently experiencing functionality issues, causing problems for AddOns.

**Current behavior**: The SetRaidSubgroup() function is flagged as PROTECTED during combat, preventing non-Blizzard AddOns from calling it. However, there is no documented evidence supporting the protection status of this API function during The Burning Crusade (TBC). 

**Expected behavior**: The SetRaidSubgroup() function should not be marked as PROTECTED during combat, allowing external AddOns to invoke it.

References:

SetRaidSubgroup() API: [Link to WoW Wiki](https://wowwiki.fandom.com/wiki/API_SetRaidSubgroup?oldid=1020137)

**Server Revision**: 3775

**Comment by Wolffenstein** [comment]
I don't have control over which client functions are protected. It's clientside and therefore blizzlike regardless of what (often inaccurate) wowwiki says.
