### ISSUE TITLE
Seals are retarding quite a bit, for me in the US and another paladin much closer to the server host

### ISSUE THREAD

**Issue by LettuceSealTwistPlease** [Atlantiss/NetherwingBugtracker#8448]
[//]: # https://www.youtube.com/watch?v=4q2yAnWn1YU

 Spells: Only Seals seems to be having this issue

**Description**: To make it easier, watch it at .25 speed and you can see all the seals are not actually buffing until 50-60% through the GCD

**Current behaviour**: Seals seem to be lagging while everything else is not showing any kind of hesitation

**Expected behaviour**: They should be buffing pretty much immediately. Lol Now if this is a byproduct of the batching removed to still allow paladins to twist, then thats fine. Just wanted to bring this up since... well it just feels really weird coming from a min/max ret backround.

**Why does any of this actually matter, we're just buff bots right?**: Because Im having to delay a judge that is off GCD otherwise its judging the previous seal and not the 2nd different seal that was just pressed if you judge immediately after swapping seals. If that's too confusing ill make a video on that too.

**Server Revision**:

**Comment by LettuceSealTwistPlease** [comment]
> Honestly i dont know how any rets who pvp here haven't caught this yet. Its pretty much make or break if the wrong seal gets put up only because you casted judgement too fast and needed to wait half a GCD for the new seal to actually be usable.

**Comment by Godmatik** [comment]
Wolf implemented seal twisting like it was on classic, test it tomorrow after server restart and give feedback.

**Comment by LettuceSealTwistPlease** [comment]
Its Perfect. Same with the judgements, you can now judge the correct seal you casted immediately now. The twisting is perfect now.

**Comment by LettuceSealTwistPlease** [comment]
I've noticed judgment cannot be casted when you swap seals now. Unless if you reapply the same seal 2 times then it lets you judge. Asked in world chat and other paladins are noticing the same bug with the judgement.

**Comment by LettuceSealTwistPlease** [comment]
not sure what changed because i didnt notice this initially after the server reboot

**Comment by Godmatik** [comment]
Wolf has stated in discord there was a bug with judgements. It is now fixed however he has reverted the seal twisting back into the original form temporarily until a server update can be done to implement the fix.

**Comment by LettuceSealTwistPlease** [comment]
Gonna close this out, Wolf knows what hes doin.
