### ISSUE TITLE
[Paladin] Judgement of Righteousness can not be resisted

### ISSUE THREAD

**Issue by Godmatik** [Atlantiss/NetherwingBugtracker#8449]
**Current behaviour**:
Paladin's "Judgement of Righteousness" right now can not be resisted in any way on Netherwing.

The resist chance is currently 0%, it can be cast and dealt damage even to a rogue who has cloak of shadows active or any PvE mob regardless of what your hit rating is (melee or spell).

While it is true that Seal of Righteousness damage portion can not be missed/resisted in any way and this is intended, - the judgement should work differently.

**Expected behaviour**: 
Judgement of Righteousness should follow the spell hit table, and be able to resist based on your spell hit vs the target

**Server Revision**: 
3775

![SpellHit](https://github.com/Atlantiss/NetherwingBugtracker/assets/37913400/2c93818c-692f-461c-831e-d94c73c3d16d)
http://web.archive.org/web/20080811083713/http://elitistjerks.com/f47/t21425-paladin_protection/

**Comment by Wolffenstein** [comment]
Fixed in rev 3786.
