### ISSUE TITLE
Blink

### ISSUE THREAD

**Issue by Stilstkin** [Atlantiss/NetherwingBugtracker#845]
[//]: # (Enclose links to things related to the bug using http://wowhead.com or any other TBC database.)
[//]: # (You can use screenshot ingame to visual the issue.)
[//]: # (Write your tickets according to the format:)
[//]: # ([Quest][Azuremyst Isle] Red Snapper - Very Tasty!)

[//]: # ([Spell][Mage] Blink)

**Description**: Blink cant be used in air and animation doesnt match the action

**Current behaviour**: If you blink while jumping or in air or jumping from anywhere it doesnt blink you, it just does the animation and you stay at the same place, also when you blink animation of place where you blinked to appears before you

**Expected behaviour**: When you blink in air it should still teleport you and reset fall., when you blink on ground teleport should happen in the same time as animation of spot you want to blink to, its delayed

**Server Revision**:

**Comment by Wolffenstein** [comment]
Delay is intended and you can only reset fall when you're close to the ground (intended as well).
