### ISSUE TITLE
 Insightfull Eathstorm Diamond not proccing on insta spells

### ISSUE THREAD

**Issue by mafista** [Atlantiss/NetherwingBugtracker#8451]
[//]: # (Enclose links to things related to the bug using http://wowhead.com or any other TBC database.)
[//]: # (You can use screenshot ingame to visual the issue.)
[//]: # (Write your tickets according to the format:)
[//]: # ([Quest][Azuremyst Isle] Red Snapper - Very Tasty!)
[//]: # ([NPC] Magistrix Erona)
[//]: # ([Spell][Mage] Fireball)
[//]: # ([Npc][Drop] Ghostclaw Lynx)
[//]: # ([Web] Armory doesnt work)
[//]: # (To find server revision type `.server info` command in the game chat.)

**Description**: 

**Current behaviour**:
Only proccing on casted spells, like flash of light

**Expected behaviour**: 
It should procc on EVERY spell casted, like buffing, changing aura, every seal hit, vindication

Earliest comment on wowhead about it proccing on instaspells, including seal of light/wisdom autos is patch 2.012
https://www.wowhead.com/tbc/item=25901/insightful-earthstorm-diamond#comments:id=79095

**Server Revision**:

**Comment by mafista** [comment]
Earliest comment on wowhead about it proccing on instaspells, including seal of light/wisdom autos is patch 2.012
https://www.wowhead.com/tbc/item=25901/insightful-earthstorm-diamond#comments:id=79095

**Comment by Wolffenstein** [comment]
Fixed in rev 3785.
