### ISSUE TITLE
Hunter Pet Abilities - Dash/Dive

### ISSUE THREAD

**Issue by Godmatik** [Atlantiss/NetherwingBugtracker#8453]
**Current behaviour**:
If pet abilities "Dash" or "Dive" is set on auto-cast, they will always cast immediately once you enter combat, and will continue to cast on cooldown while you are in combat

**Expected behaviour**: 
These abilities should only auto-cast when you send your pet to attack something, not when you are in a combat state.

**Server Revision**: 
3781

**Comment by Wolffenstein** [comment]
Fixed in rev 3834.
