### ISSUE TITLE
KT - Legendary weapon corpses still not despawning at times

### ISSUE THREAD

**Issue by Godmatik** [Atlantiss/NetherwingBugtracker#8455]
**Current behaviour**:
https://github.com/Atlantiss/NetherwingBugtracker/issues/8433

Doing KT on latest revision - the issue still persists. 
In particular - the corpses of the bow and shield sometimes (not always) do not despawn after 60 seconds. The other weapons it never seems to happen. See below, fight is well into Kael'thas phase but bow still on the ground (and lootable)

![Bow](https://github.com/Atlantiss/NetherwingBugtracker/assets/37913400/410d5981-d62c-4dbf-8652-7b8dacc631f5)

**Server Revision**: 
3781

**Comment by Wolffenstein** [comment]
Fixed in rev 3786.
