### ISSUE TITLE
Enemy Nameplate Castbar Freezes

### ISSUE THREAD

**Issue by n0str3es** [Atlantiss/NetherwingBugtracker#8458]
https://github.com/Atlantiss/NetherwingBugtracker/assets/135039668/3a6966ba-9778-45e4-b34d-bccaa9ab79bc

[//]: # (Enclose links to things related to the bug using http://wowhead.com or any other TBC database.)
[//]: # (You can use screenshot ingame to visual the issue.)
[//]: # (Write your tickets according to the format:)
[//]: # ([Quest][Azuremyst Isle] Red Snapper - Very Tasty!)
[//]: # ([NPC] Magistrix Erona)
[//]: # ([Spell][Mage] Fireball)
[//]: # ([Npc][Drop] Ghostclaw Lynx)
[//]: # ([Web] Armory doesnt work)
[//]: # (To find server revision type `.server info` command in the game chat.)

**Description**: Enemy Castbar on nameplate freezes...i clear cache and deleted wtf folder still same thing

**Current behaviour**:

**Expected behaviour**: 

**Server Revision**:

**Comment by Godmatik** [comment]
Did you get your client from Stormforge website?

**Comment by n0str3es** [comment]
> Did you get your client from Stormforge website?

Yes

**Comment by Wolffenstein** [comment]
clientside issue

**Comment by n0str3es** [comment]
> clientside issue

Nope..client downloaded from stormforge..once i change hertz on settings it buggs

**Comment by Godmatik** [comment]
He means it is an issue with the 2.4.3 client, so not something that can be fixed on his end

**Comment by n0str3es** [comment]
> He means it is an issue with the 2.4.3 client, so not something that can be fixed on his end

I see..any tips on how i can fix this?
