### ISSUE TITLE
Modifier macro for /cast is rather strange

### ISSUE THREAD

**Issue by DirtNoobMLG** [Atlantiss/NetherwingBugtracker#8459]
**Description**: 
/cast modifier macro doesn't work for shift/ctrl, but does for alt
**Current behaviour**:
MACRO 1 (the one I want to use): /cast [modifier:shift] Shadow Word: Pain(Rank 1); Shadow Word: Pain
MACRO 2 (the one that works for some reason): /cast [modifier:alt] Shadow Word: Pain(Rank 1); Shadow Word: Pain
when holding down shift and pressing 5, nothing happens. Just pressing 5 and max rank SWP is cast.
**Expected behaviour**: 
Holding down shift is supposed to cast rank 1 SWP over the max rank one.
**Server Revision**: 3781

**Comment by Godmatik** [comment]
Works just fine for me?

**Comment by Wolffenstein** [comment]
I don't have control over how macros are executed, clientside
