### ISSUE TITLE
warlock pet hearthing

### ISSUE THREAD

**Issue by yokothan** [Atlantiss/NetherwingBugtracker#846]
[//]: # (Enclose links to things related to the bug using http://wowhead.com or any other TBC database.)
[//]: # (You can use screenshot ingame to visual the issue.)
[//]: # (Write your tickets according to the format:)
[//]: # ([Quest][Azuremyst Isle] Red Snapper - Very Tasty!)
[//]: # ([NPC] Magistrix Erona)
[//]: # ([Spell][Mage] Fireball)
[//]: # ([Npc][Drop] Ghostclaw Lynx)
[//]: # ([Web] Armory doesnt work)

**Description**: 
Warlock pets do not hearth with you, nor does it refund the shard used when it dimisses them when you hearth or die and the pet lives.
**Current behaviour**:

**Expected behaviour**: 

**Server Revision**:

**Comment by tcberk12** [comment]
Just hearthed from Astranaar to Auberdine with VW out. Pet did not dismiss but is not next to me nor commandable, must still be in Ashenvale or making a prolonged run over to me.

**Comment by wtRCH** [comment]
Probably happening to Hunter pets too

**Comment by Mentat33** [comment]
Confirming this is happening with Hunter Pets too

**Comment by Wolffenstein** [comment]
Fixed in rev 2194.
