### ISSUE TITLE
Nightbane - Smoking blast during air phase

### ISSUE THREAD

**Issue by Godmatik** [Atlantiss/NetherwingBugtracker#8460]
**Description**: 
Smoking blast is an ability used by Nightbane during the air phase

**Current behaviour**:
Smoking blast is only targeting the tank who had highest threat on him during ground phase.

**Expected behaviour**: 
Smoking blast should target whoever has highest threat during air phase (typically healers). My guess is that threat is not being reset properly when Nightbane flies into the air.

https://www.wowhead.com/tbc/spell=30128/smoking-blast#comments

https://www.youtube.com/watch?v=mPSXJcIRZ18&t=150s&ab_channel=AdamK

See how it is hitting the resto shaman in this old retail video

![Smoking Blast](https://github.com/Atlantiss/NetherwingBugtracker/assets/37913400/fcf37343-ed3d-4687-af59-a7ef0400331c)

**Server Revision**: 
3781

**Comment by Wolffenstein** [comment]
He resets threat both when reaching the flight point as well as when landing and Smoking Blast is set to target top threat person so not sure why it would only target tank

**Comment by Godmatik** [comment]
I am not certain then why it happens - but it is for sure occurs every time I have done this fight

Here is a clip from everyone's favorite warrior - smoking blast only hits him during air phase (he tanks Nightbane during ground phase). He didn't do anything to generate enough threat to be top target.

https://clips.twitch.tv/NimbleGrossBananaDoggo-qAexZieER7OCzPGf

**Comment by Wolffenstein** [comment]
Fixed in rev 3834.
