### ISSUE TITLE
[Spell][Paladin] Greater Blessing of Kings doesn't generate any threat

### ISSUE THREAD

**Issue by Gornaut** [Atlantiss/NetherwingBugtracker#8461]
**Description**: 
According to Blizzard's official statement Gbok should generate threat and, moreover, it should be scaled by Righteous Fury.
There is already an opened but never resolved ticket, concerning this issue: https://github.com/Atlantiss/NetherwingBugtracker/issues/6679

However, now we have offical proof that it is an intended behaviour, which is not implemented on Netherwing atm.
Proof statement from Blizzard:
https://us.forums.blizzard.com/en/wow/t/wow-classic-era-%E2%80%9Cnot-a-bug%E2%80%9D-list-updated-april-22-2021/175887/139

**Current behaviour**:
Gbok generate no threat while casting on party member.

**Expected behaviour**: 
Gbok should generate 114 threat per person buffed.

**Server Revision**: 
3787

**Comment by Wolffenstein** [comment]
Fixed in rev 3801.
