### ISSUE TITLE
[Spell][Core] Water Walking/Levitate causing disconnects when turning while looking downwards (potentially triggering input spam protection)

### ISSUE THREAD

**Issue by Massie323** [Atlantiss/NetherwingBugtracker#8463]
[//]: # (Enclose links to things related to the bug using http://wowhead.com or any other TBC database.)
[//]: # (You can use screenshot ingame to visual the issue.)
[//]: # (Write your tickets according to the format:)
[//]: # ([Quest][Azuremyst Isle] Red Snapper - Very Tasty!)
[//]: # ([NPC] Magistrix Erona)
[//]: # ([Spell][Mage] Fireball)
[//]: # ([Npc][Drop] Ghostclaw Lynx)
[//]: # ([Web] Armory doesnt work)
[//]: # (To find server revision type `.server info` command in the game chat.)

**Description**: 
Effects that let you walk on water and "dive" when mouseturning downwards (Water Walking & Levitate) will reliably disconnect you when looking downwards and rotating your character with rightclick while on **solid ground**.
When rotating your character slowly with rightclick while looking at a downwards angle, you can see that the Character's orientation gets frequently reset (instead of having the feet lag behind while the upper body rotates).
So my guess is the client is spamming the server with some sort of inputs, thus triggering an automatic spam protection disconnect.

**Current behaviour**:
Looking down while buffed with water walking effects and mouseturning on solid ground will prompt a disconnect.

**Expected behaviour**: 
You should be free to spin like a lemon without being disconnected by the server.

**Server Revision**: 
3787

https://github.com/Atlantiss/NetherwingBugtracker/assets/57675820/e05e3e01-a8da-4d9e-ae14-78a91f69570f

https://github.com/Atlantiss/NetherwingBugtracker/assets/57675820/be86229a-50e6-4894-a01a-fc802766410c

**Comment by Wolffenstein** [comment]
clientside
