### ISSUE TITLE
[BG] Joining a party while in BG destroys your frames

### ISSUE THREAD

**Issue by reetarded** [Atlantiss/NetherwingBugtracker#8464]
As title states, joining party destroys your bg frame and I get bugs like when I get out of the bg my party members are ?? and not on the map, party members sending double messages in chat, etc.

**Comment by Godmatik** [comment]
You are also able to have 6 party members in a group if you accept an invite for one while inside a BG.

More info here:
https://github.com/Atlantiss/NetherwingBugtracker/issues/6199

**Comment by Wolffenstein** [comment]
Fixed in rev 3840.
