### ISSUE TITLE
Blizzard / Cone of Cold / Frost nova no slow from stealth

### ISSUE THREAD

**Issue by adzz452** [Atlantiss/NetherwingBugtracker#8465]
When using any frost slowing abilities against a stealthed target it will remove them from stealth and do damage but not apply the slow

This applies for frost nova / blizzard / cone of cold - damage always applies with no slow.

This is probably effecting Frostbite procs aswell.

**Comment by Wolffenstein** [comment]
Should be better after rev 3791.
