### ISSUE TITLE
([Blizzard])([Cone of Cold])([Frost Nova]) [Mage] 

### ISSUE THREAD

**Issue by boxitooo6629** [Atlantiss/NetherwingBugtracker#8466]
**Description**: 
 https://youtu.be/Yh80FKwx5-8

**Current behaviour**:
Bugged in Arena, Currently dueling Cone of Cold and Nova seems 50/50 bugged but in arena is not working video above will prove it. 
 
from 3:10 till 3:50  we have 3 blizzard bugs 
from 11:40 we have 1 blizard bug and in 11:54 and 11:55 

Please watch the video 

Instantcrafd

**Comment by boxitooo6629** [comment]
Cone of Cold does damage but no slow effect it says immune even though rouge is not under the effect of Cloack of Shadows.
Blizard is doing damage but not applying slow on first tick.
Nova sometimes does damage but not apply the root(freeze).

**Comment by Spartanv** [comment]
Can confirm first tick of blizzard is not slowing when under stealth effect
https://github.com/Atlantiss/NetherwingBugtracker/assets/11991518/d3e9e114-6c77-4655-9f48-d715b2bfdaa4

**Comment by boxitooo6629** [comment]
Rouge needs fixing. I don't think problem is mage

**Comment by Spartanv** [comment]
Breaking movement impairing effect lingers for too long when activating vanish. At the end of the video last nova is like 2 seconds after vanish cast.

https://github.com/Atlantiss/NetherwingBugtracker/assets/11991518/273bca33-e9cf-40b8-abe0-a8f1fd3790c2

**Comment by Wolffenstein** [comment]
Should be better after rev 3791.
