### ISSUE TITLE
[Paladin] Blessing of Sanctuary max rank can be learned too early

### ISSUE THREAD

**Issue by Godmatik** [Atlantiss/NetherwingBugtracker#8467]
**Current behaviour**:
At level 60 - you can train Greater Blessing of Sanctuary (rank 1), after you have trained Blessing of Sanctuary (rank 4) - Intended

But buying that greater blessing from trainer automatically is adding Blessing of Sanctuary (rank 5) in your spellbook - Not intended

**Expected behaviour**: 
Blessing of Sanctuary (rank 5) should only be trainable at level 70, and should not be tied to Greater Blessing of Sanctuary (rank 1)

**Server Revision**:
3789

**Comment by Wolffenstein** [comment]
Fixed in rev 3830.
