### ISSUE TITLE
Kael'thas Fight - Conflagration

### ISSUE THREAD

**Issue by Godmatik** [Atlantiss/NetherwingBugtracker#8468]
**Description**: 
Conflagration casted by Grand Astromancer Capernian
https://www.wowhead.com/tbc/spell=37018/conflagration

**Current behaviour**:
If Conflagration is cast on you - and you have legendary staff buff active (https://www.wowhead.com/tbc/spell=36480/mental-protection-field) you will take no damage from the ability.

Clip:
https://clips.twitch.tv/BillowingAmazingWolfDatSheffy-FCesFFQvRnnlAGBk

**Expected behaviour**: 
Even if the legendary staff buff is on you - you should still take ticking fire damage from the conflag if it is cast on you. The only thing the staff buff should do is prevent the disorient effect.

https://www.youtube.com/watch?v=Zv5yCCTluDQ&t=415s&ab_channel=Action

Video from classic - pally tank with star on his head gets hit by Conflagration

**Server Revision**: 
3790

**Comment by Wolffenstein** [comment]
Fixed in rev 3793.
