### ISSUE TITLE
[Karazhan][Opera Event] Romulo & Julianne LOS issue

### ISSUE THREAD

**Issue by owliepecks** [Atlantiss/NetherwingBugtracker#8469]
[//]: # (Enclose links to things related to the bug using http://wowhead.com or any other TBC database.)
[//]: # (You can use screenshot ingame to visual the issue.)
[//]: # (Write your tickets according to the format:)
[//]: # ([Quest][Azuremyst Isle] Red Snapper - Very Tasty!)
[//]: # ([NPC] Magistrix Erona)
[//]: # ([Spell][Mage] Fireball)
[//]: # ([Npc][Drop] Ghostclaw Lynx)
[//]: # ([Web] Armory doesnt work)
[//]: # (To find server revision type `.server info` command in the game chat.)

**Description**: When fighting Romulo & Julianne, sometimes they will be out of line of sight when there is nothing blocking the way

**Current behaviour**: When separating the two, trying to heal the tanks on either side of the stage will sometimes give a "target is not in line of sight" error when there is nothing blocking the way- no props, no candles, etc etc. I tried to do a little research on the issue but didn't find anything, not sure if it's supposed to be like that or not.

**Expected behaviour**: Since there is nothing else on the stage, the error shouldn't come up and you should be able to heal the tanks/damage the mob without worry

**Server Revision**:

**Comment by Godmatik** [comment]
This occurs if you are too close to the back curtain - unsure if blizzlike or not

**Comment by Wolffenstein** [comment]
If it's the curtain, it will be fixed in rev 3793. If not then idk
