### ISSUE TITLE
Orgrimmar - Grom'gol Zepellin Master

### ISSUE THREAD

**Issue by Erodraeda** [Atlantiss/NetherwingBugtracker#847]
[//]: # (Enclose links to things related to the bug using http://wowhead.com or any other TBC database.)
[//]: # (You can use screenshot ingame to visual the issue.)
[//]: # (Write your tickets according to the format:)
[//]: # ([Quest][Azuremyst Isle] Red Snapper - Very Tasty!)
[//]: # ([NPC] Magistrix Erona)
[//]: # ([Spell][Mage] Fireball)
[//]: # ([Npc][Drop] Ghostclaw Lynx)
[//]: # ([Web] Armory doesnt work)

**Description**: 
the NPC 12136, 1, Snurk Bucksquick, yelled that the zep had arrived, but the zep wasn't there
**Current behaviour**:
![screenshot_505](https://user-images.githubusercontent.com/40346279/46238775-fbe4f700-c365-11e8-91fa-20191d5ff914.png)
**Expected behaviour**: 
Should only yell that after the zep had arrived.
**Server Revision**:

**Comment by Wolffenstein** [comment]
Fixed in rev 2100.

**Comment by Anselm123** [comment]
I just had the same issue just now, she yelled and no zep for a while. I thought nothing serious about it but then when i finally got on the zep this happened 

![wowscrnshot_100318_105234](https://user-images.githubusercontent.com/36844570/46400598-24b91380-c6fb-11e8-9929-afdb332c0ccd.jpg)

This was above alterac mountain zone and was like this for 2-3 minutes before it sorted it self out. After i exited the zep it then randomly disapeared.
