### ISSUE TITLE
Kill Command

### ISSUE THREAD

**Issue by SMDFB** [Atlantiss/NetherwingBugtracker#8471]
This ability does not deal damage if the pet is at a distance from the target, even if it reaches the target. But it does cost mana. You will not find in any source that it should be so. It also doesn't say anywhere about the minimum required distance to the target, and that "you'll just waste mana if the pet is far away". Perhaps for this reason, on many servers, KC dealt damage even at a distance from the target.

**Comment by Godmatik** [comment]
Yep confirmed.

More info here:
https://github.com/Atlantiss/NetherwingBugtracker/issues/6632

**Comment by Wolffenstein** [comment]
Fixed in rev 3834.
