### ISSUE TITLE
[Profession] [Engineering] Goggle recipes added in 2.1 TBC not available at trainer

### ISSUE THREAD

**Issue by Fa2ol** [Atlantiss/NetherwingBugtracker#8472]
Currently it is not possible to learn a number of Engineering goggle recipes on the Netherwing Server (patch 2.4.3) - whereas they were added in 2.1 in the Original TBC. I am not referring to Goggle recipes that drop in Sunwell Plateau, but the recipes that should be trainable from the Master Engineering Trainers

Below is the list of Googles missing:

![image](https://github.com/Atlantiss/NetherwingBugtracker/assets/135662864/b42eff6a-ad3b-45dd-a35d-4c899ae3c4ba)

Example below:
https://www.wowhead.com/tbc/spell=41317/deathblow-x11-goggles#comments

You can see from the comments on any of the individual Goggle pages that they should be in the game on patch 2.1

![image](https://github.com/Atlantiss/NetherwingBugtracker/assets/135662864/aed8f782-9fe0-449a-8a9c-4e5178d30367)

This should be trainable at any of the Master Engineering trainers, and craftable at Engineering Level 350. However if you go to any of the trainers the recipes are not available to learn.

Even viewing this in Atlasloot it seems that the item is not available on the server at all:

![image](https://github.com/Atlantiss/NetherwingBugtracker/assets/135662864/ad06b401-1c50-448f-959f-628f3eddb573)

Engineering is quite bad to have without these items, since there are very few perks to having Engineering at all apart from the gadgets - especially compared to something like Blacksmithing where you can get the gear from Master Weaponsmith & Armorsmith or Tailoring where you have the different Cloth Specialization gear

**Comment by Wolffenstein** [comment]
We are at content patch 2.0.3

**Comment by Godmatik** [comment]
For clarity sake @Fa2ol 
The "2.4.3" refers to the client we are using - because it uses that patch number for our spells and talents. But the content follows patch progression and starts at 2.0
