### ISSUE TITLE
[Spell][Pet] Shadowfiend not attacking the target

### ISSUE THREAD

**Issue by tsu-1** [Atlantiss/NetherwingBugtracker#8473]
[//]: # (Enclose links to things related to the bug using http://wowhead.com or any other TBC database.)
[//]: # (You can use screenshot ingame to visual the issue.)
[//]: # (Write your tickets according to the format:)
[//]: # ([Quest][Azuremyst Isle] Red Snapper - Very Tasty!)
[//]: # ([NPC] Magistrix Erona)
[//]: # ([Spell][Mage] Fireball)
[//]: # ([Npc][Drop] Ghostclaw Lynx)
[//]: # ([Web] Armory doesnt work)
[//]: # (To find server revision type `.server info` command in the game chat.)

**Description**: Shadowfiend summoned pet behaviour (PvP combat)

**Current behavior**: Shadowfiend doesn't want to attack a target, even when commanded to. When using `/petattack` he runs to the target and then comes back. The person on the video uses the macro to manage the fiend. This is a high-priority bug as it prevents Priest from regen mana in PvP scenarios. 

https://dl.dropboxusercontent.com/s/jw6xke04h74qpf1/NVIDIA_Share_2023-06-06_17-12-20.mp4

Hard to see, but look top left corner at Priest/Druid around the pillar.

**Expected behavior**: Shadowfiend should properly chase and attack the target priest is ordering it to.

**Server Revision**: 3790

**Comment by Godmatik** [comment]
https://github.com/Atlantiss/NetherwingBugtracker/issues/8375

We think it has to do with pet being on aggressive

**Comment by Wolffenstein** [comment]
Idk how to reproduce, maybe fixed in rev 3792.
