### ISSUE TITLE
[Shaman] Searing Totem

### ISSUE THREAD

**Issue by Godmatik** [Atlantiss/NetherwingBugtracker#8474]
**Current behaviour**:
Damage caused by searing totem is able to proc trinkets/judgement of wisdom and such to benefit the shaman who placed it.

**Expected behaviour**: 
Searing totem damage shouldn't be linked with the shaman - should be linked only to the totem itself.

**Server Revision**: 
3790

**Comment by Wolffenstein** [comment]
Fixed in rev 3797.
