### ISSUE TITLE
[Karazhan][Shade of Aran] Aran is able to use dragonbreath inbetween Massive Magnetic Pull and Charged Arcane Explosion

### ISSUE THREAD

**Issue by ashido96** [Atlantiss/NetherwingBugtracker#8476]
[//]: # (Enclose links to things related to the bug using http://wowhead.com or any other TBC database.)
[//]: # (You can use screenshot ingame to visual the issue.)
[//]: # (Write your tickets according to the format:)
[//]: # ([Quest][Azuremyst Isle] Red Snapper - Very Tasty!)
[//]: # ([NPC] Magistrix Erona)
[//]: # ([Spell][Mage] Fireball)
[//]: # ([Npc][Drop] Ghostclaw Lynx)
[//]: # ([Web] Armory doesnt work)
[//]: # (To find server revision type `.server info` command in the game chat.)

**Description**: 
Currently Shade of Aran is able to use dragon's breath in the middle of his three spell cast sequence of
   a) Magnetic Pull 
   b) Mass slow 
   c) Arcane explosion 

**Current behaviour**:
Shade of Aran casts dragon's breath after magnetic pull (or mass slow?, not sure on the exact sequence). 

**Expected behaviour**: 
Shade of Aran does not dragon's breath people during his 3 spell cast sequence. 

This is PARTICULARLY egregious when Aran does: pyroblast damage lands on players -> magnetic pull -> dragon's breath -> mass slow -> arcane explosion.

**Comment by ashido96** [comment]
I haven't been able to find any evidence of this anywhere. I would assume there would be people raging on blizzard forums about getting crowd controlled when they have to run the edges of the room and I haven't been able to find anything that suggests this spell sequence should be able to exist. I tried to look for stuff in the 2006-2010 age with google search and wasn't able to find any complaints about this idk.

**Comment by Wolffenstein** [comment]
Fixed in rev 3800.
