### ISSUE TITLE
[Item] Blade of Wizardry

### ISSUE THREAD

**Issue by MoonSeYoun** [Atlantiss/NetherwingBugtracker#8478]
**Description**: Blade of Wizardry proc

**Current behaviour**: Blade of Wizardry proc either has no icd or low icd.

**Expected behaviour**:  Proc should have 15% proc chance and 50s cd

**Server Revision**: 3794

https://www.wowhead.com/tbc/item=31336/blade-of-wizardry#comments

![image](https://github.com/Atlantiss/NetherwingBugtracker/assets/130842957/a412f21e-b516-4744-8e7d-897b3714d6eb)

**Comment by Godmatik** [comment]
Would need further research but I am pretty certain the 50s ICD was added in a later patch - and that it has a very short ICD in 2.0 (our current patch)

**Comment by Wolffenstein** [comment]
Fixed
