### ISSUE TITLE
Vashj - Toxic Spores from Bat

### ISSUE THREAD

**Issue by Godmatik** [Atlantiss/NetherwingBugtracker#8479]
**Current behaviour**:
Toxic spore bats have a chance to target a mind controlled player with their toxic spores ability in the Vashj encounter (final phase). When the toxic spores lands and "hits" that mind controlled player - no pool is generated on the ground.

**Expected behaviour**: 
Toxic spore bats should not target mind controlled players.

**Server Revision**: 
3794

**Comment by Wolffenstein** [comment]
It already removes mind controlled players from the pool of possible targets, but since it's a projectile it's possible for the target to become mind-controlled before it lands.
