### ISSUE TITLE
Searing Totem sees stealth

### ISSUE THREAD

**Issue by sasadubi** [Atlantiss/NetherwingBugtracker#8481]
[//]: # (Enclose links to things related to the bug using http://wowhead.com or any other TBC database.)
[//]: # (You can use screenshot ingame to visual the issue.)
[//]: # (Write your tickets according to the format:)
[//]: # ([Quest][Azuremyst Isle] Red Snapper - Very Tasty!)
[//]: # ([NPC] Magistrix Erona)
[//]: # ([Spell][Mage] Fireball)
[//]: # ([Npc][Drop] Ghostclaw Lynx)
[//]: # ([Web] Armory doesnt work)
[//]: # (To find server revision type `.server info` command in the game chat.)

**Description**: 
Searing Totem from shaman, can see Stealth targets and attack them while they are in stealth to put them out of stealth.
Magma totem is pulsating one and it will discover stealth players if they are in proximity of AoE of Magma totem, but not the Searing one.
Searing totem - bugged
Magma totem - working as intended.

**Current behaviour**:
Currently, Searing Totem from shaman, can see Stealth targets and attack them while they are in stealth.

**Expected behaviour**: 
Searing Totem should not see stealth targets.

**Server Revision**: 
3794

**Comment by Wolffenstein** [comment]
Fixed in rev 3796.
