### ISSUE TITLE
[Spell][Mage] Blink

### ISSUE THREAD

**Issue by tsu-1** [Atlantiss/NetherwingBugtracker#8482]
[//]: # (Enclose links to things related to the bug using http://wowhead.com or any other TBC database.)
[//]: # (You can use screenshot ingame to visual the issue.)
[//]: # (Write your tickets according to the format:)
[//]: # ([Quest][Azuremyst Isle] Red Snapper - Very Tasty!)
[//]: # ([NPC] Magistrix Erona)
[//]: # ([Spell][Mage] Fireball)
[//]: # ([Npc][Drop] Ghostclaw Lynx)
[//]: # ([Web] Armory doesnt work)
[//]: # (To find server revision type `.server info` command in the game chat.)

**Description**: Blink behaviour on Blade's Edge Arena

**Current behaviour**: When falling of a bridge and using blink close to the ground, it teleports the mage back to the bridge. 

https://dl.dropboxusercontent.com/s/3keh70gd4u6z9cl/NVIDIA_Share_2023-06-12_02-19-48.mp4

**Expected behaviour**: When jumping off the bridge, it should teleport the mage on the ground instead of back to the bridge.

**Server Revision**: 3790

**Comment by Wolffenstein** [comment]
![image](https://github.com/Atlantiss/NetherwingBugtracker/assets/1576644/25fdee57-8b10-421b-9612-7ed834b0285b)
This looks to me like he was still more or less in line with the bridge height-wise, which in any other case in the world would result in blinking you to whatever ledge you're looking at so I don't think it's a bug.
