### ISSUE TITLE
Stealth not interupting enemy casts

### ISSUE THREAD

**Issue by Torensvk** [Atlantiss/NetherwingBugtracker#8483]
[//]: # ([Spell][Druid/Roge] Prowl/Stealth)

**Description**:  Entering stealth while targeted by enemy who casts spell, but hasnt fired it, still fires, hits and de-stealth

**Current behaviour**: Entering stealth while targeted by enemy who casts spell, but hasnt fired it, still fires, hits and de-stealth

**Expected behaviour**: Entering stealth should work very similar way as Feign Death. Caster doesnt have target chosen, so spell cant be successfully finished. Live version keeps the casting time until end, but if target is still stealthed it doesnt shoot projectile. If the rogue or cat is targeted by pyroblast, they stealth for lets say 1 second and then re-appear and only then the pyroblast finnishes cast it goes of "normally". Right now the spell goes off no matter the state which is different from blizzlike and is a big thing for Druid, Rogues, and even Nelfs

**Server Revision**:

**Comment by Wolffenstein** [comment]
Fixed in rev 3798.
