### ISSUE TITLE
Searing Totem VII attacks me while Invis

### ISSUE THREAD

**Issue by TreeloverxD** [Atlantiss/NetherwingBugtracker#8484]
[//]: # (Enclose links to things related to the bug using http://wowhead.com or any other TBC database.)
[//]: # (You can use screenshot ingame to visual the issue.)
[//]: # (Write your tickets according to the format:)
[//]: # ([Quest][Azuremyst Isle] Red Snapper - Very Tasty!)
[//]: # ([NPC] Magistrix Erona)
[//]: # ([Spell][Mage] Fireball)
[//]: # ([Npc][Drop] Ghostclaw Lynx)
[//]: # ([Web] Armory doesnt work)
[//]: # (To find server revision type `.server info` command in the game chat.)

**Description**:  I rewatched some of my Arena Games and got targeted by Searing Totem while Invis. I was at least 30 feet away and still got attacked. This should not be the case!

**Current behaviour**:

**Expected behaviour**: 

**Server Revision**:

**Comment by Godmatik** [comment]
Already recently fixed - just needs a server restart to implement it
