### ISSUE TITLE
Cant craft frost res legs by NAXX chain quest

### ISSUE THREAD

**Issue by trovi123** [Atlantiss/NetherwingBugtracker#8485]
![WoWScrnShot_061323_122807](https://github.com/Atlantiss/NetherwingBugtracker/assets/136437891/a1dd1748-b074-4e25-8e2d-908d3ed7b42e)
**Description**: hi! i wanted to get frost res legs from quest [The Only Song I Know...](https://www.wowhead.com/tbc/quest=9232/the-only-song-i-know). As i [know](https://www.wowhead.com/classic/npc=16376/craftsman-wilhelm#comments:id=3247923) this quest is avalible after i finished quest [Omarion's Handbook](https://www.wowhead.com/tbc/quest=9233/omarions-handbook). Quest Omarion's Handbook starts by using this book. Book you can get in Naxxramas from NPC Master Craftsman Omarion just by talking to him. So i came to Naxx, but NPC didnt give quest item - Omarion's Handbook. Just for info: i have revered rep with Argent Dawn.

**Current behaviour**: As the result all quest chain and crafting of frost res legs is blocked. 

**Expected behaviour**: Pls repear NPC Master Craftsman Omarion or make quest "The Only Song I Know..." evelible without prequest. 

**Server Revision**: I made tiket in game, but GM couldnt help me. He thought that this quest chain is for bs and tailor crafters, but on this wowhead [screenshot](https://wow.zamimg.com/uploads/screenshots/normal/999781-master-craftsman-omarion.jpg) y can see dialog for NON crafters that gives y Omarion's Handbook.

**Comment by trovi123** [comment]
![Uploading WoWScrnShot_061323_122807.jpg…]()

**Comment by Wolffenstein** [comment]
Fixed in rev 3834.
