### ISSUE TITLE
[The Lurker Below] Missing emote for Spout

### ISSUE THREAD

**Issue by Godmatik** [Atlantiss/NetherwingBugtracker#8487]
**Current behaviour**:
When "The Lurker Below" in SSC is using his Spout ability, he is not doing any emote

**Expected behaviour**: 
He should do an emote when he is casting his Spout ability: "The Lurker Below takes a deep breath!"

https://www.youtube.com/watch?v=bOgVubpALOI&t=123s&ab_channel=OroborusNZ

**Server Revision**: 
3798

**Comment by Wolffenstein** [comment]
Fixed in rev 3800.
