### ISSUE TITLE
Fishing bobber dissappear's

### ISSUE THREAD

**Issue by Johnatanboev** [Atlantiss/NetherwingBugtracker#8488]
Hello, there is issue with fishing, specialy with bobber. 
While is fishing bobber is dissappers in the middle of cast. Then i need to throw again, sometimes is dissapper's few times. Honestly is annoyng becouse sometis im throwing bobber's 4-5 times for 1 catch !
On picture's u can see there is casting but no bobber to catch fish !
Server > netherwing
Ingame name : Joeboev
![4](https://github.com/Atlantiss/NetherwingBugtracker/assets/136710798/1f6177d2-639b-47a2-a322-6b78e113f7c9)
![5](https://github.com/Atlantiss/NetherwingBugtracker/assets/136710798/8f96c26a-d041-4f9e-b1a4-14ce29d03b9e)
![6](https://github.com/Atlantiss/NetherwingBugtracker/assets/136710798/d3831e65-df64-4d13-8e1e-47b268e026b4)

**Comment by Godmatik** [comment]
Basically what happens is that the bobber disappears when you miss a catch - which is intended - but the cast bar remains, which can confuse people.

Same issue as described here:
https://github.com/Atlantiss/NetherwingBugtracker/issues/6782

**Comment by Godmatik** [comment]
How it should work is that the cast should finish fully (which it is doing) but the bobber should not disappear after a catch is missed (which is currently what is happening).

It should still be there and interactable throughout the entire cast (even if you can no longer catch a fish until your next one). It is more-so a visual issue but can be confusing as a result.

Same issue as described here:
https://github.com/Atlantiss/NetherwingBugtracker/issues/6782

**Comment by Wolffenstein** [comment]
Fixed in rev 3830.
