### ISSUE TITLE
drain soul, drain life not being canceled by vanish

### ISSUE THREAD

**Issue by dedestus** [Atlantiss/NetherwingBugtracker#8490]
[//]: # (To find server revision type `.server info` command in the game chat.)

**Description**: 

**Current behaviour**:
if a warlock channels drain soul or drain life on a rogue and the rogue casts his vanish ability the channel will not be interrupted thus breaking the vanish and stealth effect causing the rogue to be visible again
**Expected behaviour**: 
drain soul and drain life channels should stop if the rogue presses his vanish ability and not persist to break it
**Server Revision**: 
3798

**Comment by Wolffenstein** [comment]
Fixed in rev 3803.
