### ISSUE TITLE
[ZG] Gurubashi Axe Thrower missing abilities when mind controlled

### ISSUE THREAD

**Issue by djobf** [Atlantiss/NetherwingBugtracker#8491]
[//]: # (Enclose links to things related to the bug using http://wowhead.com or any other TBC database.)
[//]: # (You can use screenshot ingame to visual the issue.)
[//]: # (Write your tickets according to the format:)
[//]: # ([Quest][Azuremyst Isle] Red Snapper - Very Tasty!)
[//]: # ([NPC] Magistrix Erona)
[//]: # ([Spell][Mage] Fireball)
[//]: # ([Npc][Drop] Ghostclaw Lynx)
[//]: # ([Web] Armory doesnt work)
[//]: # (To find server revision type `.server info` command in the game chat.)

**Description**: 
Gurubashi Axe Thrower in Zul'gurub is missing enrage, whirlwind and throw as abilities when controlled.
**Current behaviour**:
Only autoattack is available as an ability when MC'd by a priest.
**Expected behaviour**: 
Enrage and whirlwind should be usable: [https://www.wowhead.com/tbc/npc=11350/gurubashi-axe-thrower#comments](https://www.wowhead.com/tbc/npc=11350/gurubashi-axe-thrower#comments)
"The plus side to these guys is that they can be mind controlled. You get 3 abilities. Throw (throws 1 axe, just does damage), Enrage (increased melee damage) AND whirlwind!!!!"
**Server Revision**: 
3798

**Comment by Wolffenstein** [comment]
Fixed in rev 3818.
