### ISSUE TITLE
Weapon procc not proccing on absorbs

### ISSUE THREAD

**Issue by mafista** [Atlantiss/NetherwingBugtracker#8492]
[//]: # (Enclose links to things related to the bug using http://wowhead.com or any other TBC database.)
[//]: # (You can use screenshot ingame to visual the issue.)
[//]: # (Write your tickets according to the format:)
[//]: # ([Quest][Azuremyst Isle] Red Snapper - Very Tasty!)
[//]: # ([NPC] Magistrix Erona)
[//]: # ([Spell][Mage] Fireball)
[//]: # ([Npc][Drop] Ghostclaw Lynx)
[//]: # ([Web] Armory doesnt work)
[//]: # (To find server revision type `.server info` command in the game chat.)

**Description**: 

**Current behaviour**:
When initial white swing is absorbed by shields (like priest, mage and lock), proccs like seals, windfury and reckoning cannot happend.

On this screenshot whiteswing is absorbed by PW:shield, seal of blood and reckoning SHOULD procc, but it does not. 
![bug](https://github.com/Atlantiss/NetherwingBugtracker/assets/64267496/7b6f0947-d978-48de-9b7e-6de73634ddb8)

**Expected behaviour**: 
All proccs should happend regardless of initial white swing is absorbed or not. Heres examples from classic tbc where Seals, WF and reckoning is procced and absorbed

![sobabsorb](https://github.com/Atlantiss/NetherwingBugtracker/assets/64267496/c782e36e-613d-4427-ac12-b7308c203fe8)
![sobabsorb2](https://github.com/Atlantiss/NetherwingBugtracker/assets/64267496/de37cfd6-5f3d-4461-bb42-b0a5a2cfad58)
![sobabsorb3](https://github.com/Atlantiss/NetherwingBugtracker/assets/64267496/372264f3-9d61-424e-82ee-882eaa8ec76e)

**Server Revision**:

**Comment by Wolffenstein** [comment]
Fixed in rev 3812.
