### ISSUE TITLE
Hi I'm having issues with two Thick Felsteel Necklaces I'm trying to sell. It says "can't sell item with used charges" but neither of them have ever been used

### ISSUE THREAD

**Issue by Romulus011** [Atlantiss/NetherwingBugtracker#8493]
[//]: # (Enclose links to things related to the bug using http://wowhead.com or any other TBC database.)
[//]: # (You can use screenshot ingame to visual the issue.)
[//]: # (Write your tickets according to the format:)
[//]: # ([Quest][Azuremyst Isle] Red Snapper - Very Tasty!)
[//]: # ([NPC] Magistrix Erona)
[//]: # ([Spell][Mage] Fireball)
[//]: # ([Npc][Drop] Ghostclaw Lynx)
[//]: # ([Web] Armory doesnt work)
[//]: # (To find server revision type `.server info` command in the game chat.)

**Description**: 

**Current behaviour**:

**Expected behaviour**: 

**Server Revision**:

**Comment by Godmatik** [comment]
Can't reproduce, just tested and was able to put one on AH no problems, I also see several other sellers have them on AH

Close game, delete cache folder. Also try disabling add-ons.

**Comment by Romulus011** [comment]
Hi Matik

Clearing cache worked. Thank you!

Kind regards
