### ISSUE TITLE
SSC - Greyheart Shield-Bearer trash mob

### ISSUE THREAD

**Issue by Godmatik** [Atlantiss/NetherwingBugtracker#8494]
**Current behaviour**:
Greyheart Shield-Bearer trash mob only uses charge ability on current threat target if they are out of range.
They also don't appear to be using Avenger's Shield ability

**Expected behaviour**: 
They should target and charge anyone within their threat list if they are out of melee range - not just current tank only. 

See below video from classic, mob charges random target far away, raid stacks on him to avoid charge.
They also target someone random and use Avenger's Shield ability - this might also not be working proper here and needs to be fixed.

https://www.wowhead.com/tbc/spell=38630/shield-charge
https://www.wowhead.com/tbc/spell=38631/avengers-shield

https://www.youtube.com/watch?v=4l46Zm4yd7c&ab_channel=Chacayoyo&t=111m10s

**Server Revision**: 
3789

**Comment by Wolffenstein** [comment]
Fixed in rev 3818.
