### ISSUE TITLE
SSC - Greyheart Tidecaller trash mob (Water Elemental Totem)

### ISSUE THREAD

**Issue by Godmatik** [Atlantiss/NetherwingBugtracker#8495]
**Current behaviour**:
When "Water Elemental Totem" is killed (spawned from trash mob Greyheart Tidecaller), the water elemental it spawned is still active and never goes away unless killed.

**Expected behaviour**: 
If you kill a water elemental totem - then the water elemental linked to it should despawn.

See below classic video which shows this. Also a wowhead comment from prior to 2.1 mentioning this.

https://www.wowhead.com/tbc/spell=38624/water-elemental-totem

https://www.youtube.com/watch?v=4l46Zm4yd7c&t=6670s&ab_channel=Chacayoyo

![Tidecaller](https://github.com/Atlantiss/NetherwingBugtracker/assets/37913400/01590926-2e2e-4c9e-91a8-798ea391c5ee)

**Server Revision**: 
3798

**Comment by Wolffenstein** [comment]
Fixed in rev 3818.
