### ISSUE TITLE
Draenei warrior - Berserker quest

### ISSUE THREAD

**Issue by IFEELHC** [Atlantiss/NetherwingBugtracker#8496]
As Draenei warrior always get game freeze after take quest 'The Islander' for Berserker stance. 

I tried it 4 times and always had to restart pc.

Thanks for your service.

**Comment by Peglaa** [comment]
Disable your quest helper addon. Or better yet, get a better one like pfQuest.

**Comment by IFEELHC** [comment]
It worked! Thank you so much :)
