### ISSUE TITLE
[Quest][Hellfire Peninsula] Striking Back

### ISSUE THREAD

**Issue by Drutol** [Atlantiss/NetherwingBugtracker#8497]
[//]: # (Enclose links to things related to the bug using http://wowhead.com or any other TBC database.)
[//]: # (You can use screenshot ingame to visual the issue.)
[//]: # (Write your tickets according to the format:)
[//]: # ([Quest][Azuremyst Isle] Red Snapper - Very Tasty!)
[//]: # ([NPC] Magistrix Erona)
[//]: # ([Spell][Mage] Fireball)
[//]: # ([Npc][Drop] Ghostclaw Lynx)
[//]: # ([Web] Armory doesnt work)
[//]: # (To find server revision type `.server info` command in the game chat.)

**Description**: 
Midsummer quest [Striking Back](https://www.wowhead.com/tbc/quest=11954/striking-back) is not working.
**Current behaviour**:
Clicking the pillar just shows generic greeting dialog.
**Expected behaviour**: 
By clicking the pillar which is present in the game the giant which is the quest objective should spawn. There should be a dialog option when interacting with the pillar, upon clicking the chat option the giant should spawn. Related video: https://youtu.be/axiCLrDWNJA?t=53
**Server Revision**: 
3806

**Comment by Wolffenstein** [comment]
Quest should not be in the game until 2.4 and will be removed
