### ISSUE TITLE
[NPC][Spell] Viscious Night Web Spider Poison duration of second poison

### ISSUE THREAD

**Issue by naxxwaswotlk** [Atlantiss/NetherwingBugtracker#85]
[//]: # (Enclose links to things related to the bug using http://wowhead.com or any other TBC database.)
[//]: # (You can use screenshot ingame to visual the issue.)
[//]: # (Write your tickets according to the format:)
[//]: # ([Quest][Azuremyst Isle] Red Snapper - Very Tasty!)
[//]: # ([NPC] Magistrix Erona)
[//]: # ([Spell][Mage] Fireball)
[//]: # ([Npc][Drop] Ghostclaw Lynx)
[//]: # ([Web] Armory doesnt work)

**Description**: 
![poisonwow](https://user-images.githubusercontent.com/43506672/45922700-b924aa00-bea1-11e8-9aec-d6ba94d62efb.JPG)
Entry 1555
**Current behaviour**:
when these mobs apply a second poison it sets one of the poison durations to zero for the remainder of its original duration 
**Expected behaviour**: 
duration should not read zero when a second poison is applied on you
**Server Revision**:

**Comment by Wolffenstein** [comment]
Fixed in rev 2055.
