### ISSUE TITLE
Midsummer torch tossing/torch catching, no money for completion

### ISSUE THREAD

**Issue by Godmatik** [Atlantiss/NetherwingBugtracker#8501]
**Current behaviour**:
No money for completing these quests and their respective dailies - possible no exp either, but I was on max lvl character so can't verify.

**Expected behaviour**: 
Should give money/exp for completion, to be scaled with level

ID 11926. 11922, 11731, 11921
11657, 11923, 11924, 11925

**Server Revision**: 
3811

**Comment by Wolffenstein** [comment]
Fixed in rev 3818.
