### ISSUE TITLE
[Paladin][Spell] Reckoning

### ISSUE THREAD

**Issue by bj86** [Atlantiss/NetherwingBugtracker#8503]
Description: Reckoning talent : Gives a 2-10% chance after being hit by any damaging attack that the next **4 weapon swings** within 8 seconds will generate an additional attack.

Current behaviour: Reckoning procs from all of your attacks, be it physical or magical damage. Holy Shield, Consecration and even Thorns will eat the Reckoning stacks. 

Expected behaviour: Reckoning will generate an additional melee swing.

Server Revision: 3881

Proof:

![reckoning](https://github.com/Atlantiss/NetherwingBugtracker/assets/20156183/5e791e03-2471-4525-8576-bd8fadd0871e)

_Originally posted by @bj86 in https://github.com/Atlantiss/NetherwingBugtracker/issues/4939#issuecomment-1604959740_

**Comment by Wolffenstein** [comment]
IIRC it's just a visual bug with recount.
