### ISSUE TITLE
NPC bugged related to defensive stance quest . ( impossible to get as a human right now ) 

### ISSUE THREAD

**Issue by spinzw** [Atlantiss/NetherwingBugtracker#8505]
[//]: # (Enclose links to things related to the bug using http://wowhead.com or any other TBC database.)
[//]: # (You can use screenshot ingame to visual the issue.)
[//]: # (Write your tickets according to the format:)
[//]: # ([Quest][Azuremyst Isle] Red Snapper - Very Tasty!)
[//]: # ([NPC] Magistrix Erona)
[//]: # ([Spell][Mage] Fireball)
[//]: # ([Npc][Drop] Ghostclaw Lynx)
[//]: # ([Web] Armory doesnt work)
[//]: # (To find server revision type `.server info` command in the game chat.)
![bug](https://github.com/Atlantiss/NetherwingBugtracker/assets/137619538/b08a5e97-b8bc-4486-95a5-d68924799bfc)

**Description**: 
Hi there's a NPC bugged in stormwind , he is related to the lvl 10 warrior quest required to have defensive stance ( so really a must have ) here is the link to the NPC on wowhead https://www.wowhead.com/tbc/fr/npc=6090/bartleby , he is named Bartleby . the bug is he is always greyed - out , as if someone else tagged him , but he isn't tagged . i have to duel him for the quest and i did it several times he's always greyed . also i checked with another acount ( my main ) and he appears greyed here too . 
**Current behaviour**:
The NPC is greyed so i take the quest , beat him in a duel but the quest never works.
**Expected behaviour**: 
He should be untagged , i accept the duel duel him and the quest should complete . 
**Server Revision**:

**Comment by Godmatik** [comment]
contact GM in-game and they can reset the NPC

**Comment by tsu-1** [comment]
The issue is, you don't kill the NPC but rather beat him down to low HP and he stops attacking. NPC should reset a "player tag" after the RP is done. So it's won't bottleneck other people and make more work for GMs.

**Comment by tsu-1** [comment]
@Wolffenstein The issue is, you don't kill the NPC but rather beat him down to low HP and he stops attacking. NPC should reset a "player tag" after the RP is done. So it's won't bottleneck other people and make more work for GMs.

**Comment by Godmatik** [comment]
Unable to reproduce, have not had any other humans mention this either. Possibly just a one time rare bug.
