### ISSUE TITLE
Quest: Dead Man's Plea / Stratholme (still bugged, after fix announcement 24.06.23)

### ISSUE THREAD

**Issue by romkaromi** [Atlantiss/NetherwingBugtracker#8506]
[//]: # (Enclose links to things related to the bug using http://wowhead.com or any other TBC database.)
[//]: # (You can use screenshot ingame to visual the issue.)
[//]: # (Write your tickets according to the format:)
[//]: # ([Quest][Azuremyst Isle] Red Snapper - Very Tasty!)
[//]: # ([NPC] Magistrix Erona)
[//]: # ([Spell][Mage] Fireball)
[//]: # ([Npc][Drop] Ghostclaw Lynx)
[//]: # ([Web] Armory doesnt work)
[//]: # (To find server revision type `.server info` command in the game chat.)

Description:

Quest: Dead Man's Plea / Stratholme

NPC: Ysida Harmon

Current behaviour:

I have finished the quest "Dead Man's Plea" (45min Baron Run) twice, but i can't turn in the quest at Ysida Harmon. She is not coming out of cage to turn in the quest.

Expected behaviour:

The NPC is supposed to walk out of the cage with yellow questionmark, so that one can turn in the quest. But she remains in the cage, eventhough the quest is marked as 'complete' in questlog. Tried to do the quest twice now, same issue.

Server Revision:

3811

UPDATE: -> Just completed the 45min Baron again, after the fix was announced today. -> Still the same issue, she is not moving out of the cage and it's not possible to turn in the quest.

**Comment by Godmatik** [comment]
The server is not updated to the latest revision yet, it requires a server restart and these typically happen on Wednesdays.

Type .info to see the in-game rev
