### ISSUE TITLE
Dispell not dispelling player if grounding totem is up inside raid

### ISSUE THREAD

**Issue by Vailennl** [Atlantiss/NetherwingBugtracker#8508]
[//]: # ([Spell][Priest] Dispell)

**Description**: Dipell not dispelling player if there is grouding totem up

**Current behaviour**: In raid when i dispell a player and in the group a shaman has his grouding totem up i dont dispell the player but the totem instead

**Expected behaviour**: Just dispell the player and not the totem because is friendfly

**Server Revision**: Stormforge Netherwing

**Comment by Wolffenstein** [comment]
Fixed in rev 3818.
