### ISSUE TITLE
Fishing during STV Event bug.

### ISSUE THREAD

**Issue by KhronosTheTitan** [Atlantiss/NetherwingBugtracker#8509]
[//]: # (Enclose links to things related to the bug using http://wowhead.com or any other TBC database.)
[//]: # (You can use screenshot ingame to visual the issue.)
[//]: # (Write your tickets according to the format:)
[//]: # ([Quest][Azuremyst Isle] Red Snapper - Very Tasty!)
[//]: # ([NPC] Magistrix Erona)
[//]: # ([Spell][Mage] Fireball)
[//]: # ([Npc][Drop] Ghostclaw Lynx)
[//]: # ([Web] Armory doesnt work)
[//]: # (To find server revision type `.server info` command in the game chat.)

**Description**: 
I fished a Keefer's fish from the STV tourney today, but it double fished/replaced it with a Tastyfish. I downloaded some software and started recording afterwards obviously and was able to capture what happened (obviously not another Keefer's) as proof of the bug I found. Can someone help me with this?
**Current behaviour**:
Occasionally quickly double fishes a node wasting it's resources 
**Expected behaviour**: 
Not double fish
**Server Revision**: 
Netherwing?

**Comment by Wolffenstein** [comment]
What does "double fished" mean?

**Comment by KhronosTheTitan** [comment]
I have a video of it occurring, but essentially it double dips the fishing node (probably standard fishing too?) by "looting" two fish, though only the second gets looted. https://imgur.com/a/F2IZ5CB you'll be able to see it briefly flash right at the beginning from an Oily Blackmouth to Speckled Tastyfish.

I have a longer video that would be easier to scrub through if we an connect on discord.

Essentially it just feels really bad to have finally found the fish after so many attempts but not have been able to loot it.

**Comment by Wolffenstein** [comment]
Fixed in rev 3830.
