### ISSUE TITLE
[Loot][Party] Corpse still showing loot when all items looted in party

### ISSUE THREAD

**Issue by snerfy** [Atlantiss/NetherwingBugtracker#851]
**Description**: 
Corpse of Surveyor Candress (drops Blood Elf Plans) still showing as lootable, even though no items can be looted off the corpse. This occurs while in a party and the other party member loots a starting quest item (Blood Elf Plans).
**Current behaviour**:
![image](https://user-images.githubusercontent.com/43623148/46240029-50d93b00-c36f-11e8-94b5-752e1993829d.png)

**Expected behaviour**: 
Corpse should no longer display as lootable to player.
**Server Revision**: 
2082

**Comment by Manaci** [comment]
Fixed with loot rework
