### ISSUE TITLE
[Rogue] Deadly Throw and Vanish

### ISSUE THREAD

**Issue by Godmatik** [Atlantiss/NetherwingBugtracker#8510]
**Current behaviour**:
If you use deadly throw and then vanish before the projectile lands, you will exit stealth and have vanish buff removed once it does land.

https://gyazo.com/657f1031a3cb79091bbeca73397f7257

**Expected behaviour**: 
Deadly throw landing on a target should not cancel vanish buff

**Server Revision**: 
3811

**Comment by Wolffenstein** [comment]
Fixed in rev 3821.
