### ISSUE TITLE
Curator trash pack can spawn inside pillar

### ISSUE THREAD

**Issue by reetarded** [Atlantiss/NetherwingBugtracker#8511]
The trash pack on the right can spawn inside pillar, the mana wyrms are unable to get out of the pillar when body pulled and will drain mana during the curator fight.

https://www.twitch.tv/videos/1855748923?t=1h26m28s

timestsampe 1hr 26min 28 sec if link doesnt timestamp correctly

**Comment by Godmatik** [comment]
Confirmed - info also here:

https://github.com/Atlantiss/NetherwingBugtracker/issues/7713

**Comment by Wolffenstein** [comment]
Fixed in rev 3830.
