### ISSUE TITLE
(Cooking) vendor/npc issue

### ISSUE THREAD

**Issue by OldxTimer** [Atlantiss/NetherwingBugtracker#8512]
Npc Bale (Horde)
https://www.wowhead.com/tbc/npc=2806/bale#sells;0-1+13-2
that resides in felwood. 

He is currently not selling 
Recipe: Juicy Bear Burger https://www.wowhead.com/tbc/item=35566/recipe-juicy-bear-burger 
Recipe: Charred Bear Kabobs https://www.wowhead.com/tbc/item=35564/recipe-charred-bear-kabobs

"These recipes require 250 skill to learn, and are created from meat found on level 48-56 bears.

** Server Revision - 3811**

This issue was brought up before when the server was on 2.3, but seeing that it's 2.4.3 this should be in the game now right?
https://github.com/Atlantiss/NetherwingBugtracker/issues/6335

**Comment by Godmatik** [comment]
These recipes were not added until patch 2.4

The server is currently on 2.0. 

The "2.4.3" represents the fact that the server uses those talents/spells, but the other content is all progressive (Sunwell would be out now if that wasn't the case)
