### ISSUE TITLE
Kael'thas - Pyroblast loop during Shock Barrier sometimes breaks early

### ISSUE THREAD

**Issue by Godmatik** [Atlantiss/NetherwingBugtracker#8513]
**Current behaviour**:
Occasionally - Kael'thas will only cast pyroblast once when he has shock barrier up - and then does an Arcane Disruption and resumes his normal rotation, even though the shield is still up and the pyroblast was not kicked. Unable to reproduce exactly what causes this.

https://clips.twitch.tv/AdorableHedonisticBubbleteaPJSalt-TBus6ni_hNT1Dpqz

**Expected behaviour**: 
The pyroblast chain must always include 3 casts when shock barrier is applied. The chain is not broken until either pyroblast is kicked (when the shield is taken down) or until the full 3 casts are complete.

**Server Revision**: 
3811

**Comment by Wolffenstein** [comment]
Maybe fixed in rev 3834.

**Comment by Godmatik** [comment]
Since I have opened this thread back in late June, we have not seen this re-occur, nor have I seen similar behavior when watching other guilds fight this on their streams

Seems to be incredibly rare - so I will go ahead and close it for now.
