### ISSUE TITLE
[Silithus] Tactical Task Briefing IX 

### ISSUE THREAD

**Issue by ashido96** [Atlantiss/NetherwingBugtracker#8514]
[//]: # (Enclose links to things related to the bug using http://wowhead.com or any other TBC database.)
[//]: # (You can use screenshot ingame to visual the issue.)
[//]: # (Write your tickets according to the format:)
[//]: # ([Quest][Azuremyst Isle] Red Snapper - Very Tasty!)
[//]: # ([NPC] Magistrix Erona)
[//]: # ([Spell][Mage] Fireball)
[//]: # ([Npc][Drop] Ghostclaw Lynx)
[//]: # ([Web] Armory doesnt work)
[//]: # (To find server revision type `.server info` command in the game chat.)

**Description**: 

**Current behaviour**:
Quest requires you to kill 0/5 Twilight Marauders
When right clicking tactical task briefing IX in inventory the quest text is correct, as well as in quest log it is correct. 
![image](https://github.com/Atlantiss/NetherwingBugtracker/assets/2313143/bdc93b15-d13d-4414-bb6e-9db1817734ee)
This is especially annoying because there's only 4 of these spawned in a pack that wanders the entire zone. 

**Expected behaviour**: 
Quest should require you to kill 0/2 Twilight Marauders 

**Server Revision**: 
https://www.wowhead.com/tbc/quest=8740/twilight-marauders

**Comment by Wolffenstein** [comment]
Fixed in rev 3834.
