### ISSUE TITLE
[Silithus] Twilight Cultist set missing aura 

### ISSUE THREAD

**Issue by ashido96** [Atlantiss/NetherwingBugtracker#8515]
[//]: # (Enclose links to things related to the bug using http://wowhead.com or any other TBC database.)
[//]: # (You can use screenshot ingame to visual the issue.)
[//]: # (Write your tickets according to the format:)
[//]: # ([Quest][Azuremyst Isle] Red Snapper - Very Tasty!)
[//]: # ([NPC] Magistrix Erona)
[//]: # ([Spell][Mage] Fireball)
[//]: # ([Npc][Drop] Ghostclaw Lynx)
[//]: # ([Web] Armory doesnt work)
[//]: # (To find server revision type `.server info` command in the game chat.)

**Description**: 
When you equip the set: https://www.wowhead.com/tbc/item-set=492/twilight-trappings
You do not gain buff/aura: https://www.wowhead.com/tbc/spell=24746/twilight-cultist-disguise#used-by-item-set

**Current behaviour**:
No aura/buff

**Expected behaviour**: 
gain aura/buff

**Server Revision**: 
You should also check auras: 
https://www.wowhead.com/tbc/spell=24748/twilight-cultist-disguise
and 
https://www.wowhead.com/tbc/spell=24782/twilight-cultist-disguise

**Comment by ashido96** [comment]
I don't actually know if this is supposed to be a hidden buff or not apologies. I'm unable to check because of #8516

**Comment by Wolffenstein** [comment]
It's a hidden buff
