### ISSUE TITLE
[Silithus] All Lesser Wind Stones not spawned. 

### ISSUE THREAD

**Issue by ashido96** [Atlantiss/NetherwingBugtracker#8516]
[//]: # (Enclose links to things related to the bug using http://wowhead.com or any other TBC database.)
[//]: # (You can use screenshot ingame to visual the issue.)
[//]: # (Write your tickets according to the format:)
[//]: # ([Quest][Azuremyst Isle] Red Snapper - Very Tasty!)
[//]: # ([NPC] Magistrix Erona)
[//]: # ([Spell][Mage] Fireball)
[//]: # ([Npc][Drop] Ghostclaw Lynx)
[//]: # ([Web] Armory doesnt work)
[//]: # (To find server revision type `.server info` command in the game chat.)

**Description**: 
All six lesser wind stones do not exist.

**Expected behaviour**: 
Lesser wind stones existing. 
https://www.wowhead.com/classic/object=180456/lesser-wind-stone
https://www.wowhead.com/classic/object=180518/lesser-wind-stone
https://www.wowhead.com/classic/object=180529/lesser-wind-stone
https://www.wowhead.com/classic/object=180544/lesser-wind-stone
https://www.wowhead.com/classic/object=180549/lesser-wind-stone
https://www.wowhead.com/classic/object=180549/lesser-wind-stone

**Server Revision**: 
Some reports this were closed as fixed in the past. It does not seem to have been fixed.

**Comment by Godmatik** [comment]
Yep, there is an open issue of this already:

https://github.com/Atlantiss/NetherwingBugtracker/issues/6467

A lot of the Silithus zone needs a revamp at some point.

**Comment by ashido96** [comment]
The only bugs I can verify right now in silithus is that 6 quest scrolls don't give anything when right clicked on. 
And these stones not working. 

All of the normal quests and the rest of the zone are working fine. It's not like it needs a full revamp or anything close to that.

**Comment by Wolffenstein** [comment]
Fixed in rev 3830.
