### ISSUE TITLE
[Silithus][Item: 20809, 21133] Tactical Assignment and Follow Up Tactical Assignment unable to be moved in inventory. 

### ISSUE THREAD

**Issue by ashido96** [Atlantiss/NetherwingBugtracker#8517]
[//]: # (Enclose links to things related to the bug using http://wowhead.com or any other TBC database.)
[//]: # (You can use screenshot ingame to visual the issue.)
[//]: # (Write your tickets according to the format:)
[//]: # ([Quest][Azuremyst Isle] Red Snapper - Very Tasty!)
[//]: # ([NPC] Magistrix Erona)
[//]: # ([Spell][Mage] Fireball)
[//]: # ([Npc][Drop] Ghostclaw Lynx)
[//]: # ([Web] Armory doesnt work)
[//]: # (To find server revision type `.server info` command in the game chat.)

**Description**: 
If tactical assignment or follow up tactical assignment contain a quest giving item that you already have in your inventory. You will be unable to move the tactical assignment or follow up tactical assignment container item in your inventory. 

**Current behaviour**:

**Expected behaviour**: 
Not being blocked from moving the item.

**Server Revision**:

**Comment by Wolffenstein** [comment]
Fixed in rev 3830.
