### ISSUE TITLE
SSC - Water elemental totem - not fully fixed

### ISSUE THREAD

**Issue by Godmatik** [Atlantiss/NetherwingBugtracker#8518]
**Description**: 
For reference:
https://github.com/Atlantiss/NetherwingBugtracker/issues/8495

**Current behaviour**:
Issue only partially fixed. If the water elemental totem is killed, only the FIRST water elemental created by it gets despawned currently. Any additional water elementals created by the totem after the first one are not despawned when the totem is destroyed.

**Expected behaviour**: 
When you destroy a water elemental totem - all mobs spawned from it should be despawned, not only the first one.

**Server Revision**: 
3818

**Comment by Wolffenstein** [comment]
But the totem only summons a water elemental once?

**Comment by Wolffenstein** [comment]
Fixed in rev 3821.
