### ISSUE TITLE
[Loot][Party] Can't loot corpse

### ISSUE THREAD

**Issue by snerfy** [Atlantiss/NetherwingBugtracker#852]
**Description**: 
Corpse showing as lootable but no permission to loot the corpse.
**Current behaviour**:
![image](https://user-images.githubusercontent.com/43623148/46240059-ccd38300-c36f-11e8-8f21-3c34551a5bdd.png)

**Expected behaviour**: 
Corpse should not display as lootable.
**Server Revision**: 
2082

**Comment by Azalen** [comment]
Can confirm. Very tedious to loot stuff in dungeons if not using FFA.

**Comment by Tereneckla** [comment]
Fixed
