### ISSUE TITLE
[Warrior] [Spell] Battle Shout should fade from pets on group swap or pet dismiss

### ISSUE THREAD

**Issue by Easymonka** [Atlantiss/NetherwingBugtracker#8520]
[//]: # (Enclose links to things related to the bug using http://wowhead.com or any other TBC database.)
[//]: # (You can use screenshot ingame to visual the issue.)
[//]: # (Write your tickets according to the format:)
[//]: # ([Quest][Azuremyst Isle] Red Snapper - Very Tasty!)
[//]: # ([NPC] Magistrix Erona)
[//]: # ([Spell][Mage] Fireball)
[//]: # ([Npc][Drop] Ghostclaw Lynx)
[//]: # ([Web] Armory doesnt work)
[//]: # (To find server revision type `.server info` command in the game chat.)

**Description**: 
Battle Shout should fade from pets on group swap or pet dismiss

**Current behaviour**:
Battle Shout stays on pets if you shout in their group and then get swapped to another group. This leads to wrong (unintended) and very bad gameplay where warriors get swapped around to buff pets.

**Expected behaviour**: 
Should fade from pets on either the hunter being swapped out of your group or the warrior being swapped to a different group. Similar to how it already works on other players in the group.

**Server Revision**: 
3819

**Comment by Wolffenstein** [comment]
Fixed in rev 3821.
