### ISSUE TITLE
Wind serpent special attack blocking auto attacks

### ISSUE THREAD

**Issue by Howizter** [Atlantiss/NetherwingBugtracker#8522]
Current behaviour:
Both pets had same group, both were alive whole fight as their owners so expected number of autoattacks should be similar.

https://i.imgur.com/Cfa2WKd.png

https://i.imgur.com/vjbJ2B9.png

Expected behaviour:
Wind serpent should have similar number of autoattack as ravager.

Server Revision:
3819

**Comment by Godmatik** [comment]
Related issue:
https://github.com/Atlantiss/NetherwingBugtracker/issues/7997

**Comment by Wolffenstein** [comment]
Fixed in rev 3837.
