### ISSUE TITLE
[NPC] Rats in Duskwood are untargetable

### ISSUE THREAD

**Issue by Massie323** [Atlantiss/NetherwingBugtracker#8523]
[//]: # (Enclose links to things related to the bug using http://wowhead.com or any other TBC database.)
[//]: # (You can use screenshot ingame to visual the issue.)
[//]: # (Write your tickets according to the format:)
[//]: # ([Quest][Azuremyst Isle] Red Snapper - Very Tasty!)
[//]: # ([NPC] Magistrix Erona)
[//]: # ([Spell][Mage] Fireball)
[//]: # ([Npc][Drop] Ghostclaw Lynx)
[//]: # ([Web] Armory doesnt work)
[//]: # (To find server revision type `.server info` command in the game chat.)

**Description**: 
Rats in Duskwood are untargetable.
Probably a side-effect from making Arathi Basin NPCs untargetable.

**Current behaviour**:
Rats in Duskwood are untargetable.

**Expected behaviour**: 
Rats should be targetable.

**Server Revision**: 
3819

![ApplicationFrameHost_DkKa8H4N5m](https://github.com/Atlantiss/NetherwingBugtracker/assets/57675820/1001d220-b48c-49b4-8793-ac5fccceb249)

**Comment by Massie323** [comment]
This also includes the Black Rats in Molten Core, so I guess it's not zone specific but the NPC types themselves.

![wow_0kASlEnOIE](https://github.com/Atlantiss/NetherwingBugtracker/assets/57675820/af8e50ac-4b75-4d9e-bc57-712205a2e197)

**Comment by Wolffenstein** [comment]
Fixed in rev 3821.
