### ISSUE TITLE
Queue for 3v3 pops while in 2v2 game

### ISSUE THREAD

**Issue by sasadubi** [Atlantiss/NetherwingBugtracker#8525]
[//]: # (Enclose links to things related to the bug using http://wowhead.com or any other TBC database.)
[//]: # (You can use screenshot ingame to visual the issue.)
[//]: # (Write your tickets according to the format:)
[//]: # ([Quest][Azuremyst Isle] Red Snapper - Very Tasty!)
[//]: # ([NPC] Magistrix Erona)
[//]: # ([Spell][Mage] Fireball)
[//]: # ([Npc][Drop] Ghostclaw Lynx)
[//]: # ([Web] Armory doesnt work)
[//]: # (To find server revision type `.server info` command in the game chat.)

**Description**: 
Myself and 2 of my mates were playing 3v3. There was no queue, so I decided to do 2v2 with one of them. I remove the 3rd guy from party and que 2v2, while forgetting to leave que for 3v3.
After we got queue pop for 2v2, we joined arena game, and while buffing, 3v3 que popped. We of course ignored the 3v3 que, and proceeded with 2v2. After that 2v2 game, we found out that 3v3 counted as loss.

**Current behavior**:
Can join 3v3, kick one of the players from the party, que 2v2 and can have 3v3 que pop while being in 2v2.

**Expected behavior**: 
The behavior here should be like in battlegrounds. If I join 2v2, the 3v3 queue should be canceled immediately.
Also, additional information is that on other private servers and TBC Classic, if we were in 3v3 que, and one of people leaves the party, the queue should be canceled also.

**Server Revision**: 
3819

**Comment by sasadubi** [comment]
@Wolffenstein Is it possible to fix this one?

**Comment by Wolffenstein** [comment]
Fixed in rev 3830.
