### ISSUE TITLE
Crusader's Ornamented set issue

### ISSUE THREAD

**Issue by h4x0r93** [Atlantiss/NetherwingBugtracker#8526]
[//]: # (Enclose links to things related to the bug using http://wowhead.com or any other TBC database.)
[//]: # (You can use screenshot ingame to visual the issue.)
[//]: # (Write your tickets according to the format:)
[//]: # ([Quest][Azuremyst Isle] Red Snapper - Very Tasty!)
[//]: # ([NPC] Magistrix Erona)
[//]: # ([Spell][Mage] Fireball)
[//]: # ([Npc][Drop] Ghostclaw Lynx)
[//]: # ([Web] Armory doesnt work)
[//]: # (To find server revision type `.server info` command in the game chat.)

**Description**: 
Hi guys, paladin PVP holy set is not giving an atribute which it should. It have to add bonus spell damage too not just healing
https://www.wowhead.com/tbc/item=35404/crusaders-ornamented-headguard

wowhead item prntscreen
https://prnt.sc/C4EeEWPaGnhi
server item prntscreen
https://prnt.sc/895fXlZWWYXg
**Current behaviour**:
Its giving only healing done
**Expected behaviour**: 
it should give healing done + spell dmg done
**Server Revision**: 3819

**Comment by Godmatik** [comment]
Not a bug.
None of the healing items give spell dmg in this patch, not until patch 2.3 when ZA releases.
