### ISSUE TITLE
[NPC][Spell] Crystalcore Mechanic using Recharge (heal) on non-mechanical targets.

### ISSUE THREAD

**Issue by Massie323** [Atlantiss/NetherwingBugtracker#8527]
[//]: # (Enclose links to things related to the bug using http://wowhead.com or any other TBC database.)
[//]: # (You can use screenshot ingame to visual the issue.)
[//]: # (Write your tickets according to the format:)
[//]: # ([Quest][Azuremyst Isle] Red Snapper - Very Tasty!)
[//]: # ([NPC] Magistrix Erona)
[//]: # ([Spell][Mage] Fireball)
[//]: # ([Npc][Drop] Ghostclaw Lynx)
[//]: # ([Web] Armory doesnt work)
[//]: # (To find server revision type `.server info` command in the game chat.)

**Description**: 
Crystalcore mechanics have a 10k healing beam that they channel on the Crystalcore Devastators & Crystalcore Sentinels.
Right now, however, they may randomly use it on any other target (except themselves), incl. a second Mechanic, or one of the Bloodelves.

**Current behaviour**:
Crystalcore Mechanics use [Recharge](https://www.wowhead.com/tbc/spell=37121/recharge) on non-mechanical targets.

**Expected behaviour**: 
Crystalcore Mechanics should only use Recharge on Mechanical Targets

**Server Revision**: 
3819

![chrome_HmYmTsyEkv](https://github.com/Atlantiss/NetherwingBugtracker/assets/57675820/be8080b9-f54b-4212-a3aa-3f97ef573a3a)

Additional Context:
As you can see by the comment, the Mechanics were also using Sawblades while banished before 2.1.
Obviously, it was a bug (that was quickly fixed), but so is Hydross crushing so idk what you want to make of it.

**Comment by Wolffenstein** [comment]
Fixed in rev 3821.
