### ISSUE TITLE
Flood Protection

### ISSUE THREAD

**Issue by marcinkroszel** [Atlantiss/NetherwingBugtracker#8528]
[//]: # (Enclose links to things related to the bug using http://wowhead.com or any other TBC database.)
[//]: # (You can use screenshot ingame to visual the issue.)
[//]: # (Write your tickets according to the format:)
[//]: # ([Quest][Azuremyst Isle] Red Snapper - Very Tasty!)
[//]: # ([NPC] Magistrix Erona)
[//]: # ([Spell][Mage] Fireball)
[//]: # ([Npc][Drop] Ghostclaw Lynx)
[//]: # ([Web] Armory doesnt work)
[//]: # (To find server revision type `.server info` command in the game chat.)

**Description**: 
Flood protection prevents me from creating Tank Assignment Macros and displaying them in Party chat.

**Current behaviour**:
I am creating a Tank Assignment macro to make my dungeon runs smoother. Unfortunately, I can't do so because of the Flood Protection policy.

The below screenshot shows my macro and then its execution in the chat. Part of it was cut because of the policy.
![image](https://github.com/Atlantiss/NetherwingBugtracker/assets/55636544/720805be-b259-4d02-9b78-1cb7997fd909)

**Expected behaviour**: 
Flood Protection rules should be excluded from Raid and Party chat. 

**Server Revision**: 
3819

**Comment by Wolffenstein** [comment]
Fixed in rev 3821.
