### ISSUE TITLE
bug about Paladin    redemption mission

### ISSUE THREAD

**Issue by gseture** [Atlantiss/NetherwingBugtracker#8529]
Hello, I am Dgost, an Azeroth explorer. I am currently encountering a troublesome problem and need your help. After reaching the level of my Paladin, I am unable to receive redemption missions, as well as trainers from Stormwind, Ironforge, and Twinkle, where humans were born. I am unable to communicate and receive missions. Please help me, thank you!

**Comment by Godmatik** [comment]
You likely missed a part of the chain.

Open a GM ticket in-game and someone can assist you.
