### ISSUE TITLE
[TK] Kael'thas fight - Netherstrand Longbow

### ISSUE THREAD

**Issue by Godmatik** [Atlantiss/NetherwingBugtracker#8530]
**Current behaviour**:
In the Kael'thas fight - after the weapons are summoned in phase 2 - the bow will immediately go to their primary threat and attempt to melee for the first ~5 seconds or so before properly doing ranged attacks. This means a high likelihood of the ranged player tanking it to get 1 shot.

**Expected behaviour**: 
If the target is in ranged - the bow should not be doing melee attacks upon spawn. Should be doing only ranged attacks, as the video below shows:

https://www.youtube.com/watch?v=xEMLQgVeqhQ&t=290s&ab_channel=VinzYo
https://www.wowhead.com/tbc/npc=21268/netherstrand-longbow

**Server Revision**: 
3818

**Comment by Wolffenstein** [comment]
Fixed in rev 3821.
