### ISSUE TITLE
[MAJOR] Lady Vashj

### ISSUE THREAD

**Issue by whistleblowingallday** [Atlantiss/NetherwingBugtracker#8531]
**Current behaviour**:

While Mind Controlled by Persuasion on Phase 3, you can swap your weapon AFTER being Mind Controlled, which will incur GCD. 

People can then SPAM weapon swap to flood the GCD and make the Mind Controlled players do NOTHING. No casts, No meleeing, they do nothing. 

**Expected behaviour**: 

Weapon Swaps shouldn't be allowed while MC'd.

**Server Revision**: 
3819

**Comment by Wolffenstein** [comment]
Fixed in rev 3822.
