### ISSUE TITLE
Gruul - shatter ability becomes desync after resets

### ISSUE THREAD

**Issue by Godmatik** [Atlantiss/NetherwingBugtracker#8537]
**Current behaviour**:
Getting reports that after multiple wipes on Gruul - his shatter ability becomes desynced. People under effects of shatter has the damage dealt too early or stun applied too early or late. Don't have a video but multiple reports of it.

**Expected behaviour**: 
Shatter should act the same every attempt with consistent timers on its ability.

Having the boss evade despawn and respawn upon wipe is probably best solution, when a GM does it manually it fixes the issue

**Server Revision**: 
3822

**Comment by Wolffenstein** [comment]
Fixed in rev 3824.
