### ISSUE TITLE
general's mooncloth boots/bracers/belt too high stamina

### ISSUE THREAD

**Issue by dedestus** [Atlantiss/NetherwingBugtracker#8538]
**Description**: 
general's mooncloth boots/bracers/belt have too high stamina values 
**Current behaviour**:
general's mooncloth boots have 60, bracers 35, belt 60 stamina
**Expected behaviour**: 
general's mooncloth boots should have boots 40, bracers 25, belt 39

https://www.wowhead.com/tbc/item=32975/generals-mooncloth-slippers
https://www.wowhead.com/tbc/item=32974/generals-mooncloth-belt
https://www.wowhead.com/tbc/item=32973/generals-mooncloth-cuffs
**Server Revision**: 
current

**Comment by Wolffenstein** [comment]
3826
