### ISSUE TITLE
[Quest][Azuremyst Isle] Help Tavara

### ISSUE THREAD

**Issue by Agaanii** [Atlantiss/NetherwingBugtracker#8539]
**Description**: 
Tavara, the target priests need to heal for their class quest, does not give credit when healed. Additionally, she stays at full health for a long time, preventing multiple priests from doing their quest.
![image](https://github.com/Atlantiss/NetherwingBugtracker/assets/12824288/b0aef033-ce45-4168-9426-0ee951c4c564)

**Current behaviour**: Tavara is always kneeling in the expected location. Her health is ~80 when walking up, and she can be healed and buffed with PW: Fortitude. None of the healing spells available to Priests give credit for the quest.

**Expected behaviour**: https://www.wowhead.com/tbc/quest=9586/help-tavara
Renew, Lesser Heal, and Gift of the Naaru should all give quest credit.

**Server Revision**: 3822

**Comment by Peglaa** [comment]
Seems this quest still has issues and it's a bad look. Someone should probably take a look at the script, the NPC might not be resetting properly.

**Comment by Wolffenstein** [comment]
From what I can see in the script it should properly give credit if you use Gift of the Naaru (28880) or Lesser Heal R1 (2050), can you try that?

**Comment by Wolffenstein** [comment]
Fixed in rev 3830.
