### ISSUE TITLE
warsong glutch major bug

### ISSUE THREAD

**Issue by h4x0r93** [Atlantiss/NetherwingBugtracker#8540]
[//]: # (Enclose links to things related to the bug using http://wowhead.com or any other TBC database.)
[//]: # (You can use screenshot ingame to visual the issue.)
[//]: # (Write your tickets according to the format:)
[//]: # ([Quest][Azuremyst Isle] Red Snapper - Very Tasty!)
[//]: # ([NPC] Magistrix Erona)
[//]: # ([Spell][Mage] Fireball)
[//]: # ([Npc][Drop] Ghostclaw Lynx)
[//]: # ([Web] Armory doesnt work)
[//]: # (To find server revision type `.server info` command in the game chat.)

**Description**: 
Guys in WSG the flags are not showing properly, sometimes enemy take the flag and we cannot track where is our flag, and it happens 8/10 times... they just cap the flag and we dont know who is carrying the flag and where
**Current behaviour**:

**Expected behaviour**: 
it shoudl show the picked up flag
**Server Revision**: 
3826

**Comment by Godmatik** [comment]
When flag is taken, it does not show immediately on map, that is intended.

**Comment by h4x0r93** [comment]
but I got situation when they have taken the flag and not showed up the whole time, I know that it should not show in the flag building, but if you leave it it should be on the map but it doesnt happen, enemy capped the flag 3 times and we didnt see it the whole time on the map
