### ISSUE TITLE
Viper sting does not work

### ISSUE THREAD

**Issue by nmc2012** [Atlantiss/NetherwingBugtracker#8542]
[//]: # ([Spell][Hunter] Viper Sting)

**Description**: 
My Viper Sting Rank 1/2 does not drain any mana, completely useless for me. Anyone noticed similar?

**Comment by Godmatik** [comment]
Tested both rank 1 and rank 2 - both are draining mana as intended.
Are you attempting to use this on a mob who is immune to poison perhaps?

**Comment by nmc2012** [comment]
Thanks. It does not work on any mobs I have encountered so far, including humanoid caster NPCs. I am not sure what the issue could be, as it indeed seems to be working for any other hunter I have asked ingame :/

**Comment by Godmatik** [comment]
If it only affects you, then you will probably have to show a video or something to demonstrate. Is it possible one of your addons is not showing enemy mana properly?

**Comment by Wolffenstein** [comment]
Seems like a personal problem. Closing.
