### ISSUE TITLE
[SSC] Water Elemental Totem only despawning last add summoned if destroyed

### ISSUE THREAD

**Issue by Massie323** [Atlantiss/NetherwingBugtracker#8543]
[//]: # (Enclose links to things related to the bug using http://wowhead.com or any other TBC database.)
[//]: # (You can use screenshot ingame to visual the issue.)
[//]: # (Write your tickets according to the format:)
[//]: # ([Quest][Azuremyst Isle] Red Snapper - Very Tasty!)
[//]: # ([NPC] Magistrix Erona)
[//]: # ([Spell][Mage] Fireball)
[//]: # ([Npc][Drop] Ghostclaw Lynx)
[//]: # ([Web] Armory doesnt work)
[//]: # (To find server revision type `.server info` command in the game chat.)

**Current behaviour**:
If the Water Elemental Totem spawns more than 1 add, only the last add gets despawned and the first one remains (potentially due to banish?)

**Expected behaviour**: 
All adds associated to a totem should disappear when that totem is destroyed.
**Server Revision**: 
3826

**Comment by Godmatik** [comment]
Yes banished add should get despawned.

However the totem spawning more than 1 add seems intended:

![waterele](https://github.com/Atlantiss/NetherwingBugtracker/assets/37913400/9ea86b31-ce13-4c9e-ae54-4284c54eafba)

**Comment by Massie323** [comment]
Updated original post + video footage:


https://github.com/Atlantiss/NetherwingBugtracker/assets/57675820/b258bfbd-e73c-4e9a-b1e5-b1029437f559

**Comment by Godmatik** [comment]
Btw auto-attack turning off when attacking totem is another bug

https://github.com/Atlantiss/NetherwingBugtracker/issues/6571

**Comment by Godmatik** [comment]
Duplicate with another issue, so closing this one
