### ISSUE TITLE
[PVP] After crowd control effects expire - unable to continue movement

### ISSUE THREAD

**Issue by Godmatik** [Atlantiss/NetherwingBugtracker#8544]
**Current behaviour**:
If you have an input pressed to move and are put into any crowd control effect or roots effect - and that CC breaks due to expiration, trinket, or other methods - you no longer move forward again unless you re-press that input.

https://gyazo.com/37589cb1913ce1cc569c012c808b23d1

**Expected behaviour**: 
CCs should not cancel your movement input completely.

**Server Revision**: 
3826

**Comment by Wolffenstein** [comment]
Fixed in rev 3828.
