### ISSUE TITLE
[Professions][Fishing] Bites happen far too deep into the channel (1-2 second left)

### ISSUE THREAD

**Issue by Massie323** [Atlantiss/NetherwingBugtracker#8545]
[//]: # (Enclose links to things related to the bug using http://wowhead.com or any other TBC database.)
[//]: # (You can use screenshot ingame to visual the issue.)
[//]: # (Write your tickets according to the format:)
[//]: # ([Quest][Azuremyst Isle] Red Snapper - Very Tasty!)
[//]: # ([NPC] Magistrix Erona)
[//]: # ([Spell][Mage] Fireball)
[//]: # ([Npc][Drop] Ghostclaw Lynx)
[//]: # ([Web] Armory doesnt work)
[//]: # (To find server revision type `.server info` command in the game chat.)

**Description**: 
The potential bites for fishing currently can happen as late as 1 second left on the channel, which makes it impossible to react when fishing semi-afk with your attention elsewhere. You can see in the video that the first bite starts its animation with 1.7 seconds left & the sound cue itself peaks at 1.0 seconds left.
Meanwhile, on Classic TBC, bites would happen at the latest with ~5 seconds left, giving you ample time to react to the worst case.

**Current behaviour**:
Bites happen with 1-2 seconds left on the channel.

**Expected behaviour**: 
Latest bites should happen with at minimum 5-4 seconds left on the channel.

**Server Revision**: 
3827

https://github.com/Atlantiss/NetherwingBugtracker/assets/57675820/255f35a8-231a-4d50-a35c-4e92bdfbbd4e

**Comment by Wolffenstein** [comment]
Fixed in rev 3830.
