### ISSUE TITLE
[Tauren] Tauren hitbox/combat reach is smaller for Tauren Warrior than all other Taurens.

### ISSUE THREAD

**Issue by Easymonka** [Atlantiss/NetherwingBugtracker#8546]
**Description**: 

**Current behaviour**:
https://youtube.com/clip/UgkxmVJyZDN9-ADa3sNITdwFnX8eLBF7wN1f
On the video you can see me (Tauren male t5 warrior shoulders) trying to reach max melee range and getting out of range while the other tauren in the video Bonker with hydross shoulders is still hitting the boss with no problems while standing further away.

Both characters are currently Tauren Male.
Bonker is a character created as Tauren male original with Orc Racials currently. Has bigger range than Easymonkey.
Easymonkey is a character created as Orc female originally race changed via website to Tauren male with human racials currently. 

We did further testing with the help of a GM and it turns out that the issue is that Tauren Warrior in general is not getting the increased melee range from being Tauren, but Shaman, Druid and Hunter still do.

**Expected behaviour**: 
Same melee range/reach for all Taurens.

**Server Revision**: 3827

**Comment by Wolffenstein** [comment]
Fixed in rev 3830.
