### ISSUE TITLE
ZF mobs resetting on their own 

### ISSUE THREAD

**Issue by RouatbiZack** [Atlantiss/NetherwingBugtracker#8548]
[//]: # (Enclose links to things related to the bug using http://wowhead.com or any other TBC database.)
[//]: # (You can use screenshot ingame to visual the issue.)
[//]: # (Write your tickets according to the format:)
[//]: # ([Quest][Azuremyst Isle] Red Snapper - Very Tasty!)
[//]: # ([NPC] Magistrix Erona)
[//]: # ([Spell][Mage] Fireball)
[//]: # ([Npc][Drop] Ghostclaw Lynx)
[//]: # ([Web] Armory doesnt work)
[//]: # (To find server revision type `.server info` command in the game chat.)

**Description**: when u try to pull a bunch of mobs together and drag them to a spot not so far away  half of them or more evade and reset 

**Current behaviour* *:mobs resetting while still in combat

**Expected behaviour* *: mobs not resetting and will follow u till u leave the dungeon 

**Server Revision**:

**Comment by Wolffenstein** [comment]
Need recording

**Comment by Godmatik** [comment]
Duplicate
