### ISSUE TITLE
Heartbeat resist in PvP environment

### ISSUE THREAD

**Issue by dedestus** [Atlantiss/NetherwingBugtracker#8552]
**Description**: 

Heartbeat resist should be present in PvP even if all involved characters have reached the hit cap for their abilities. Currently from the testing I did on live and PTR server when it was opened it seems like heartbeat resist is not present after reaching the hit cap as well as it is only present for certain abilities even if no hit is used or if the target character that you CC has a high amount of resist. Tested with nature resistance stack and entangling roots cast on a 0% hit chance druid on PTR before launch. I did not record any of these tests as I initially planned to report it but if you test it yourself you should get similar results. Priest Mind Control spell seems to be affected by heartbeat in PvP.

**Current behaviour**:

No heartbeat resists on certain abilities as well as no heartbeat resist after reaching hit cap.

**Expected behaviour**: 

Heartbeat resist should still happen even after reaching the hit cap, especially against targets with high or higher amounts of resistances against the used spell school, for example nature resistance against entangling roots.

Some classic TBC clips with heartbeat resists in PvP. 
https://www.twitch.tv/mirlol/clip/FaintMoldySquidTriHard-QAWDhmsEmNXU_hkc?filter=clips&range=all&sort=time

https://streamable.com/49y3op

https://www.youtube.com/watch?v=PQAIxsnp9DE

https://us.forums.blizzard.com/en/wow/t/sooo-heartbeat-blind/1074043/14

**Server Revision**: 
Current

**Comment by bluemanguy112** [comment]
While I applaud the servers decision to mimic how TBCC worked I think this feature (along with frost novas not breaking) should not be added. There was a petition in TBCC to remove it as well which explains it much better than I could. If you check the comments of people that signed the petition you will find pretty much every high rated player agreeing that heartbeat is generally not a good thing for TBC arena.

https://www.change.org/p/classic-dev-team-remove-heartbeat?utm_source=share_petition&utm_medium=custom_url&recruited_by_id=e492eb60-7885-11ec-9a20-8f8c303de571

**Comment by dedestus** [comment]
Why should we handpick the mechanics of TBC or TBC Classic that we want to implement on the server? Of course this favors certain classes more than others, same as with the recently applied change to Flare or debuffs like Frost Trap, that the majority of the playerbase would probably also not approve as well as other mechanics but there has not been a poll on that.

Also we currently have all of the Engineering gear active in arena as well so where do you want to draw the line? There are always changes that some people want to keep or not keep based on their personal benefit/preference and as a result some of the incorrectly working mechanics do not even get reported.

**Comment by bluemanguy112** [comment]
Indeed, I generally agree with your sentiment. However, heartbeat was pretty much unaninmously disliked by the PvP community in TBCC. And if you read the petition you can see why. It promotes defensive gameplay and punishes people for playing offensive.

**Comment by dedestus** [comment]
I am not here to judge individual playstyles or approaches to the game, I just wanted to report a broken game mechanic that does benefit some people more than others yet should be implemented in the game if you want to follow the path the server has taken. Now the report is available and it is up to Wolfenstein to decide whether he wants to adjust this and keep it in the game or not.

**Comment by bluemanguy112** [comment]
You are right, however, since heartbeat mostly affects pvp the opinion of people like hydra/mir/chas/avizura among others on the topic should be taken into consideration.

**Comment by dedestus** [comment]
None of these people play on the current server, additionally they have all "survived" and enjoyed? TBC Classic even with heartbeat being present and they have all reached multiple rank 1 titles on their respective classes regardless.

Because TBC games are rather slow paced I would say it is easier to play around a possible heartbeat and reset the game state depending on the comp you play of course and this again leads to discussing who benefits the most of this change and who does not.

The players you mentioned are mostly playing rogue comps or being rogues it is more than understandable that they do not approve heartbeat resist as they are impacted by it a lot in every comp they play. If you ask different players you will get different opinions, I guess there was a reason blizzard kept it in the game despite this "poll"?

I do agree it is a hard topic to decide on, personally I am fine with either way since I also enjoyed classic even with heartbeat.

**Comment by bluemanguy112** [comment]
1. People playing it "anyway" isn't really an argument at all. More like, they played it - despite - such a bad mechanic. There is simply no substitute to wow arena, only retail, so ofcourse people smiled through the pain.
2. You're making my point for me. I quote what I wrote in the petition: "Also, as the author mentioned, it is a common misconception that this mechanic leads to shorter arena games - due to an overall reduction in CC - when the exact opposite is true. Heartbeat encourages a defensive style of play and can severely punish teams that try to play offensively (e.g., your CC chain will be broken randomly and prematurely). As a result, most teams currently play very defensively, as the risk-reward equation makes it not worth it for some teams to ever play offensively."
3. Rogues can actually be considered somewhat as benefactors, since their heightened senses talent makes them more prone to heartbeat CC whilst they are only very limitedly negatively impacted by this with blind being the only ability that I am aware of that is affected by heartbeat. Classes with spammable CC are affected the most Mage/Lock/Druid.

**Comment by dedestus** [comment]
TBC Classic had multiple questionable mechanics implemented that, depending on who you asked, people appreciated in the game and others fought for a removal or fix as soon as possible. After seeing changes like lingering Flare debuff and Frost Trap getting implemented we should push for all of the TBC Classic mechanics that we know existed, it is also a controversial change which most people questioned in the heartbeat poll would not want to see in the game. People playing against Hunters cried for a fix on this basically every game they were matched against a Hunter, yet you pushed it here to get it implemented.
The same applies to pushing a fix for the "base stun resist chance" which caused quite some drama in the Discord.

We had mages being able to blink while under the effect of garrote + kidney shot due to it being "blizzlike" but so far I have not seen anyone report it here and most people knew about this mechanic on classic.

Rogues do mostly pair up with the classes you mentioned to play together in arena, as in rogue/mage, rogue/druid or even rogue/lock, as well as some meta comps consisting of Rogue/Warlock/Druid or Rogue/Mage/Priest so they will feel the impact of heartbeat too. But not only they will be affected by it, the opposing team will be affected equally.

Instead of handpicking the mechanics you want to see on the server we should implement all of them or none.

**Comment by tsu-1** [comment]
We have it implemented so you can negate the heartbeat resists, if you are hit capped and many people like that balance.

This won't be changed to how it worked on Classic TBC. In theory, it should work the way you've described, in practice, this is something people do not favor and makes already RNG-focused PvP even more random.

**Comment by dedestus** [comment]
This is not correct, currently heartbeat is not active in PvP at all regardless of your hit rating or spell penetration or resistance of the target you cast on. If it is active it may only be for certain abilities but not for all that should be affected by a possible heartbeat. To test cast Entangling Roots on a high nature resist target while having 0% hit and 0 spell pen on your druid and you will see that there will not be a single heartbeat resist to end the CC early.  I did not test any other abilities. So if you are not willing to fully implement heartbeat then at least adjust it to the state you believe it should be in and perform tests for other abilities that should be affected by it.

**Comment by dedestus** [comment]
Any update on this matter? If not fully implement heartbeat possibly revisit the current design to fix heartbeat resists on 0 hit 0 spell pen if it is not working for every ability that should be affected currently?

**Comment by tsu-1** [comment]
It's active for all spels above 12 sec duration, mind control and demon enslave. (PvE focused) I don't think adding it to PvP is a good change that many people would be envy of.

**Comment by dedestus** [comment]
For all spells that last longer than 12 seconds by default or can be modifier to last up to 12 or longer than 12 seconds like Hunter Freezing Trap? Because I have yet to see a Freezing Trap break early to heartbeat as well, the only spell I can confirm it working correctly on is Mind Control. So possibly Freezing Trap is not affected by it but should be if talents to increase the duration are used? The talent in question is "Clever Traps" increasing the Freezing Trap duration to 13 seconds.

Seems like there is a lot of confusion about how the mechanic should work on the server and if it is even active and under which circumstances it is active. Could we get a more detailed post on this or a possible adjustment then?

And again - there are possibly a lot of mechanics that people believe to be not good for PvP or that they do not envy having in the game yet they are present and everyone has to deal with them. It is all coming down to your personal preference.
