### ISSUE TITLE
[Hunter] Flare - odd little delay on the initial flare pulse

### ISSUE THREAD

**Issue by bluemanguy112** [Atlantiss/NetherwingBugtracker#8553]
**Description**: 
Flare appears to have a tiny delay from being cast-> actual effect on the initial usage. 

**Current behaviour**:
There appears to be a tiny 0.2-0.5sec delay on the initial flare pulse resulting in situations in which a Rogue can Vanish->Cheapshot despite flare being used simulatiniously/earlier. I can only assume that somebody tried to tie it closer to the visual spell effect. Blizzard addressed this in TBCC by having the flare displayed on the ground instantly to give more visual clarity of where the flare is.

**Expected behaviour**: 
The initial flare pulse should have 0 delay and essentially work like a mage pet nova. 

On a side note (and I haven't tested this myself) the actual flare effect is also bigger than the visual - as you can also see in the Clip below. Some other Pservers decided to make the Flare visual bigger to give better visual feedback. Blizzard did not do that however.

https://clips.twitch.tv/AbrasiveSneakyLouseRitzMitz-xZ0_fBLJqxdN3lPg

**Comment by Godmatik** [comment]
The updated flare is not yet applied to the server, we are still on rev 3827, didn't Wolf modify it? 

Or if this issue is unrelated, then disregard

**Comment by bluemanguy112** [comment]
That was in regard to the pulse once flare is placed. This is a seperate issue and concerns the initial pulse.

**Comment by Wolffenstein** [comment]
Not a bug, Flare was delayed back to first batch update back in OG 2007 (which is already way shorter than the default as it would normally take projectile land time)
