### ISSUE TITLE
[Fishing] Patch of Elemental Water not fishable

### ISSUE THREAD

**Issue by Massie323** [Atlantiss/NetherwingBugtracker#8555]
[//]: # (Enclose links to things related to the bug using http://wowhead.com or any other TBC database.)
[//]: # (You can use screenshot ingame to visual the issue.)
[//]: # (Write your tickets according to the format:)
[//]: # ([Quest][Azuremyst Isle] Red Snapper - Very Tasty!)
[//]: # ([NPC] Magistrix Erona)
[//]: # ([Spell][Mage] Fireball)
[//]: # ([Npc][Drop] Ghostclaw Lynx)
[//]: # ([Web] Armory doesnt work)
[//]: # (To find server revision type `.server info` command in the game chat.)

**Description**: 
The elemental water pools in Azshara seem to have a jank hitbox or something, causing bobbers inside the pool to yield generic ocean loot, instead counting as pool catches. Occasionally the bobber lands in a position where it seems to properly land in the pool & roll its loottable (+ depleting the pool).

https://www.wowhead.com/tbc/object=180753/patch-of-elemental-water

**Current behaviour**:
Bobbers inside the pool don't count and give generic ocean loot instead.

**Expected behaviour**: 
Bobbers landing in the pool should give the pool's loottable.

**Server Revision**: 
3827

https://github.com/Atlantiss/NetherwingBugtracker/assets/57675820/e2c6343e-db90-4775-830b-81c8badd9274

**Comment by Wolffenstein** [comment]
Fixed in rev 3834.
