### ISSUE TITLE
Felguard   mana regen and glancing blow issues

### ISSUE THREAD

**Issue by JaceEverwood** [Atlantiss/NetherwingBugtracker#8557]
[//]: # (Enclose links to things related to the bug using http://wowhead.com or any other TBC database.)
https://www.youtube.com/watch?v=AsawSLSNm84   at 34:50
[//]: # (You can use screenshot ingame to visual the issue.)
[//]: # (Write your tickets according to the format:)
[//]: # ([Quest][Azuremyst Isle] Red Snapper - Very Tasty!)
[//]: # ([NPC] Magistrix Erona)
[//]: # ([Spell][Mage] Fireball)
[//]: # ([Npc][Drop] Ghostclaw Lynx)
[//]: # ([Web] Armory doesnt work)
[//]: # (To find server revision type `.server info` command in the game chat.)

**Description**: 
In The official TBC felguard got 10 times the mana regen (91 vs 9 in combat regen , and 195out of combat) and while a glance happen it only reduces 25% damage, not 85%. 

**Current behaviour**:
felguard only getting 9 mana regen during combat and 25mana/5 out of combat.
felguard is getting glancing blows way more often and got its damage reduce by 85%

**Expected behaviour**: 
felguard should be getting 91 mana/5 regen during combat and 195mana/5 out of combat.
felguard should be having less chance on glancing blows and damage reduction from glancing bow should be 25%

**Server Revision**:

**Comment by Godmatik** [comment]
Cant speak about mana regen, but aren't glancing blows dependent on the mobs you are attacking?

What level are you and what level are the mobs?

**Comment by Peglaa** [comment]
Felguard was known to have mana issues even in early wotlk if you have him using all his spells on cd. I'm not sure if the value is correct on the server tho, but I do believe you are supposed to play around mana feed when it comes to your felguard.

https://www.wowhead.com/tbc/spell=30146/summon-felguard#comments:id=87250
https://www.wowhead.com/tbc/spell=30146/summon-felguard#comments:id=3367643
https://www.mmo-champion.com/threads/649679-Felguard-mana-issues
https://gamefaqs.gamespot.com/boards/534914-world-of-warcraft/50868068
https://www.wowhead.com/forums/topic/felguard-mana-issues-56935

**Comment by Peglaa** [comment]
Also there was talk on cc bugtracker about pet mp5 being too high and they most likely should inherit the warlocks mp5 but nothing came of it I think, so it's still up in the air.

**Comment by Wolffenstein** [comment]
"felguard only getting 9 mana regen during combat and 25mana/5 out of combat."
Currently on Netherwing there is no distinction between being in combat or not when it comes to Felguard being in combat or not. Where are those values even coming from??

Also what's the source for that glancing blow reduction?

**Comment by Godmatik** [comment]
No source provided
