### ISSUE TITLE
Bundle of Nether Spikes

### ISSUE THREAD

**Issue by Godmatik** [Atlantiss/NetherwingBugtracker#8559]
**Current behaviour**:
Bundle of Nether Spikes - ammo from legendary bow in KT fight - do not despawn from bags when you die, only despawn when you release spirit. So you can get resurrected after a wipe and keep them for next attempt.

https://www.wowhead.com/tbc/item=30320/bundle-of-nether-spikes

**Expected behaviour**: 
Should despawn upon death - same as the weapons

**Server Revision**: 
3828

**Comment by Wolffenstein** [comment]
Fixed in rev 3836.
