### ISSUE TITLE
[NPC] Affray Spectator

### ISSUE THREAD

**Issue by wtRCH** [Atlantiss/NetherwingBugtracker#856]
[//]: # (Enclose links to things related to the bug using http://wowhead.com or any other TBC database.)
[//]: # (You can use screenshot ingame to visual the issue.)
[//]: # (Write your tickets according to the format:)
[//]: # ([Quest][Azuremyst Isle] Red Snapper - Very Tasty!)
[//]: # ([NPC] Magistrix Erona)
[//]: # ([Spell][Mage] Fireball)
[//]: # ([Npc][Drop] Ghostclaw Lynx)
[//]: # ([Web] Armory doesnt work)

**Description**: Some Affray Spectators are facing wrong way.

![image](https://user-images.githubusercontent.com/11255782/46240605-79caf180-c3aa-11e8-867b-2b0c54401d14.png)

**Comment by Wolffenstein** [comment]
no

**Comment by tcberk12** [comment]
:(

**Comment by wtRCH** [comment]
My bad, sorry
