### ISSUE TITLE
Quest Supplying the Front

### ISSUE THREAD

**Issue by aja318** [Atlantiss/NetherwingBugtracker#8560]
[Supplying the Front](https://www.wowhead.com/tbc/quest=1578/supplying-the-front)

**Description**: 
Quest can not be completed.
**Current behaviour**:
Talking to NPC ending the quest, [Thorvald Deepforge](https://www.wowhead.com/tbc/npc=6030/thorvald-deepforge) with all required items inside the bahs with character it's impossible to complete the quest.

**Expected behaviour**: 
Carrying all of required quest items should allow completion of the quest

**Server Revision**: 
3827
![WoWScrnShot_071823_060037](https://github.com/Atlantiss/NetherwingBugtracker/assets/50706692/f367b7d8-1942-464c-b610-3bfee00d15b8)

**Comment by Godmatik** [comment]
Put the items in your bank and take them back out, see if that fixes it

**Comment by aja318** [comment]
It did fix the problem, thanks.
