### ISSUE TITLE
[Spell] [Rogue] Master of Subtlety

### ISSUE THREAD

**Issue by KreepAK** [Atlantiss/NetherwingBugtracker#8561]
[//]: # (Enclose links to things related to the bug using http://wowhead.com or any other TBC database.)
[//]: # (You can use screenshot ingame to visual the issue.)
[//]: # (Write your tickets according to the format:)
[//]: # ([Quest][Azuremyst Isle] Red Snapper - Very Tasty!)
[//]: # ([NPC] Magistrix Erona)
[//]: # ([Spell][Mage] Fireball)
[//]: # ([Npc][Drop] Ghostclaw Lynx)
[//]: # ([Web] Armory doesnt work)
[//]: # (To find server revision type `.server info` command in the game chat.)

**Description**: 
 [Master of Subtlety] talent is not working

**Current behaviour**:
No 10% dmg buff when in stealth. No 10% dmg buff for 6 seconds after breaking the Stealth
**Expected behaviour**: 
Permanent 10% dmg buff during stealth. 6 seconds 10% buff after breaking the stealth
**Server Revision**: 
3827

**Comment by Godmatik** [comment]
https://github.com/Atlantiss/NetherwingBugtracker/issues/8135

Was said to be fixed in March - might need to re-test

**Comment by Wolffenstein** [comment]
It works fine

**Comment by KreepAK** [comment]
Yesterday, when I was reporting, there was no dmg increase while in stealth or for 6 seconds after breaking the stealth as well as no buff was shown. Today, I also see no buff icon, but in stats dmg is increased.
