### ISSUE TITLE
[Silithus][Mob] Earthern Templar does not become attackable

### ISSUE THREAD

**Issue by ashido96** [Atlantiss/NetherwingBugtracker#8562]
[//]: # (Enclose links to things related to the bug using http://wowhead.com or any other TBC database.)
[//]: # (You can use screenshot ingame to visual the issue.)
[//]: # (Write your tickets according to the format:)
[//]: # ([Quest][Azuremyst Isle] Red Snapper - Very Tasty!)
[//]: # ([NPC] Magistrix Erona)
[//]: # ([Spell][Mage] Fireball)
[//]: # ([Npc][Drop] Ghostclaw Lynx)
[//]: # ([Web] Armory doesnt work)
[//]: # (To find server revision type `.server info` command in the game chat.)

**Description**: 
After an Earthern Templar is spawned from a Lesser Wind Stone it does not become attackable and does not attack players. 
https://www.wowhead.com/tbc/npc=15307/earthen-templar

**Expected behaviour**: 
Earthern Templar is attackable after being summoned

**Server Revision**: 
3835

**Comment by Wolffenstein** [comment]
Should be fixed next time you summon him.
