### ISSUE TITLE
Rocketboots +Flag carrying doesnt work.

### ISSUE THREAD

**Issue by fischerderheld** [Atlantiss/NetherwingBugtracker#8563]
[//]: # ([Enclose links to things related to the bug using http://wowhead.com or any other TBC database.](https://www.youtube.com/watch?v=jqC9mIxMU8k))

**Description**: 
Hey there, i noticed that on this server we cant use rocketboots + Flag. Once you use rocketboots you drop the flag. 
Also when under the influence of the rocketboots, the buff, you cannot pick up the enemy flag. At first i thought its like this on purpose but a few people in discord claimed it might be a bug to counter speedhacking or similar. I provied a link form wow tbc in 2007 where a hunter flys the flag with rocketboots and parachute cloak.
**Current behaviour**:
Rocketboots buff drop flag. rocketboots buff prevents you from picking up the flag.
**Expected behaviour**: 
I should be able to keep the flag even when using rocketboots
**Server Revision**: 
dont know what server revision is :/

**Comment by Wolffenstein** [comment]
![image](https://github.com/Atlantiss/NetherwingBugtracker/assets/1576644/e348b339-5229-40bb-8846-72a5a8dde5ea)
From 2.4.0 patch notes.
