### ISSUE TITLE
[NPC] Dungeon mobs still dropping incorrect gold amounts

### ISSUE THREAD

**Issue by MecAtlantiss** [Atlantiss/NetherwingBugtracker#8564]
**Description**: Re-opening #8556, because it is not fixed still. 

![image](https://github.com/Atlantiss/NetherwingBugtracker/assets/16357005/f28a5b5d-4cb6-4fb8-bd71-d7f02ff62e47)

There is a secondary fix posted in the changelog, but it has no server revision id. However, it comes before a server revision 3836 change, so I assume the secondary fix is already in and did not fix the issue either.

![image](https://github.com/Atlantiss/NetherwingBugtracker/assets/16357005/69e461c3-c781-451f-9561-0ddf462a6603)

Here are the names of the mobs killed in the pull from the loot screenshot above, but there are many other mobs also in Stratholme with bugged gold drops:

![image](https://github.com/Atlantiss/NetherwingBugtracker/assets/16357005/571edfe3-eb24-426b-8ef0-b2773b9d0d99)

**Server Revision**: 3836

**Comment by Wolffenstein** [comment]
Will be fixed next time you enter a fresh Stratholme instance. Also keep in mind the change will affect elite mobs the most. Skeletal Guardians/Berserkers are not elite and will drop far less money than the elite mobs.
