### ISSUE TITLE
[NPC] Stratholme mobs aren't respawning when the dungeon is reset

### ISSUE THREAD

**Issue by MecAtlantiss** [Atlantiss/NetherwingBugtracker#8565]
**Description**: I killed mobs in Stratholme. I went outside Stratholme. I reset instances. When I went into a freshly reset instance of Stratholme, the Magistrate Barthilas mob was reset, but none of the mobs I had killed in the prior instance were respawned in the new instance. Mobs that I did not kill in prior instance were spawned though.

![image](https://github.com/Atlantiss/NetherwingBugtracker/assets/16357005/760a5471-8dad-4151-9f66-7a04e880dd20)

**Current behaviour**: Mobs killed in a prior instance are not respawned upon creation of a new instance.

**Expected behaviour**: Mobs should respawn when an instance is reset.

**Server Revision**: 3836

**Comment by Wolffenstein** [comment]
Works fine for me, your instance reset must have failed for whatever reason.

**Comment by MecAtlantiss** [comment]
Okay I will try again later and see if I can reproduce. I will close this issue at that point if the issue goes away for me.
