### ISSUE TITLE
Profession Boost - you can boost any low level to 375

### ISSUE THREAD

**Issue by Godmatik** [Atlantiss/NetherwingBugtracker#8566]
**Current behaviour**:
You can use the shop profession boost on any character as long as they have learned one, this allows low level characters to get instant 375 well below level 50.

Example of a twink who abused this to get high lvl engineer gear:
https://logs.stormforge.gg/character/netherwing/kittenmitten

**Expected behaviour**: 
Should probably add a level 50 requirement (at the minimum) for the profession boost in shop

**Comment by Wolffenstein** [comment]
we know
