### ISSUE TITLE
[PvP] - Dispel not working properly on debuffs

### ISSUE THREAD

**Issue by Godmatik** [Atlantiss/NetherwingBugtracker#8569]
**Current behaviour**:
When you dispel a player, it will remove the debuff from them and they can act normally if CCed - but the debuff itself still remains on the player frame and there is still a debuff slot.

See below video, look at the warrior, roots is dispelled and he can charge/move, but the roots itself is still on the ground and it still says he has roots debuff in his frame. People have reported similar behavior for sheep/fear

https://gyazo.com/f9aacedec1a7ec75374d67e0f60d6741

**Expected behaviour**: 
When dispelled, it should remove the debuff from the player frame

**Server Revision**: 
3838

**Comment by Wolffenstein** [comment]
Fixed in rev 3839.
