### ISSUE TITLE
[Spell][Paladin] Seal of Crusader not decreasing melee attack damage

### ISSUE THREAD

**Issue by anonyReporter** [Atlantiss/NetherwingBugtracker#857]
**Description**: 
Seal of Crusader does not decrease melee attack damage. 
**Current behaviour**:
![image](https://user-images.githubusercontent.com/43623148/46240820-2a210180-c37b-11e8-889b-a38ad908e709.png)

**Expected behaviour**: 
Seal of Crusader should decrease melee attack damage, as per the spell description:

> Fills the Paladin with the spirit of a crusader for 30sec, granting 36 melee attack power. The Paladin also attacks 40% faster, **but deals less damage with each attack.** Only one Seal can be active on the Paladin at any one time.

**Server Revision**: 
2083

**Comment by Wolffenstein** [comment]
Fixed in rev 2137.
