### ISSUE TITLE
[PvP] - Pet buffs/debuffs in arena

### ISSUE THREAD

**Issue by Godmatik** [Atlantiss/NetherwingBugtracker#8570]
**Current behaviour**:
When you enter/exit an arena, pets will retain all buffs/debuffs from outside the arena. This allows you to pre-buff the pet before entering when it should not be intended.

**Expected behaviour**: 
All debuffs/buffs on pet should be removed when you enter and exit the arena

**Server Revision**: 
3838

**Comment by Wolffenstein** [comment]
cannot reproduce
