### ISSUE TITLE
[PvP] - Dispel does not stop drinking/eating

### ISSUE THREAD

**Issue by Godmatik** [Atlantiss/NetherwingBugtracker#8571]
**Current behaviour**:
Using dispel on a PvP target sometimes does not stop them from drinking/eating. Mass dispel seems to always work.

**Expected behaviour**: 
Dispel should stop someone from drinking/eating when it lands

**Server Revision**: 
3838

**Comment by Wolffenstein** [comment]
Fixed in rev 3839.
