### ISSUE TITLE
Can't join arena cause combat bug

### ISSUE THREAD

**Issue by sasadubi** [Atlantiss/NetherwingBugtracker#8574]
[//]: # (Enclose links to things related to the bug using http://wowhead.com or any other TBC database.)
[//]: # (You can use screenshot ingame to visual the issue.)
[//]: # (Write your tickets according to the format:)
[//]: # ([Quest][Azuremyst Isle] Red Snapper - Very Tasty!)
[//]: # ([NPC] Magistrix Erona)
[//]: # ([Spell][Mage] Fireball)
[//]: # ([Npc][Drop] Ghostclaw Lynx)
[//]: # ([Web] Armory doesnt work)
[//]: # (To find server revision type `.server info` command in the game chat.)

**Description**: 
Sometimes, if I'm in world pvp, in combat, and arena que pops, I cannot join.

**Current behaviour**:
Cant join arena que if the que pops during world pvp combat. I even tried vanish and stealth, and /reload.

**Expected behaviour**: 
I should be able to join arena when I leave combat.

**Server Revision**: 
3840

**Comment by sasadubi** [comment]
happened again....-29 easy cause i cannot join que.

I found interesting thing which is combat visual bug and i think its related to the issue in which i cannot join arena.
So here, I have no target, I'm out of combat as you can see on stealth, but my character is in "battle stance" in terms of animation.
![noTarget](https://github.com/Atlantiss/NetherwingBugtracker/assets/49869412/fb1fd2eb-dbe0-4b68-9e3c-5e851f58bdaf)

**Comment by Godmatik** [comment]
Intended not to be able to join queue when in combat.
