### ISSUE TITLE
[NPC] Siltfin Oracle + Siltfun Hunter

### ISSUE THREAD

**Issue by Godmatik** [Atlantiss/NetherwingBugtracker#8575]
**Current behaviour**:
Silftfin Oracle + Siltfun Hunter not using any abilities - only doing melee
Also they do not flee at low health

**Expected behaviour**: 
Oracle - Should use Lightning Shield and Wrath
Hunter - Should use Throw

https://www.wowhead.com/tbc/npc=17191/siltfin-oracle#abilities
https://www.wowhead.com/wotlk/npc=17192/siltfin-hunter#abilities

**Server Revision**: 
3840

**Comment by Peglaa** [comment]
![image](https://github.com/Atlantiss/NetherwingBugtracker/assets/15163719/57c77498-1638-4a46-9d8d-63d3ddcf53e3)

**Comment by Godmatik** [comment]
Only some oracles are bugged, others are using abilities properly. No idea why.

None of the hunters are using throw though (at the least the few I tested)

**Comment by EtheriousNW** [comment]
Fixed in 3846
