### ISSUE TITLE
[NPC] Lesser Scorching Totem from Bristlelimb Shaman

### ISSUE THREAD

**Issue by Godmatik** [Atlantiss/NetherwingBugtracker#8576]
**Current behaviour**:
When the Bristlelimb Shaman uses its totem, that totem does no actions at all

**Expected behaviour**: 
Should attack you similar to a shaman's searing totem

https://www.wowhead.com/tbc/spell=32968/scorching-totem#summons

**Server Revision**: 
3840

**Comment by Wolffenstein** [comment]
Fixed in rev 3944.
