### ISSUE TITLE
[Spell][Hunter] Counterattack DR

### ISSUE THREAD

**Issue by tsu-1** [Atlantiss/NetherwingBugtracker#8577]
[//]: # (Enclose links to things related to the bug using http://wowhead.com or any other TBC database.)
[//]: # (You can use screenshot ingame to visual the issue.)
[//]: # (Write your tickets according to the format:)
[//]: # ([Quest][Azuremyst Isle] Red Snapper - Very Tasty!)
[//]: # ([NPC] Magistrix Erona)
[//]: # ([Spell][Mage] Fireball)
[//]: # ([Npc][Drop] Ghostclaw Lynx)
[//]: # ([Web] Armory doesnt work)
[//]: # (To find server revision type `.server info` command in the game chat.)

**Description**: Counterattack Hunter spell DR category.

**Current behaviour**: Currently Counterattack is in the Controlled Root category.

**Expected behaviour**: Counterattack root should not DR with anything not even with itself.

**Server Revision**: 3840

**Comment by Wolffenstein** [comment]
Fixed in rev 3841.
