### ISSUE TITLE
[NPC] Blacksilt Seer wrong level

### ISSUE THREAD

**Issue by Godmatik** [Atlantiss/NetherwingBugtracker#8578]
**Current behaviour**:
Blacksilt Seer are currently lvl 12-13 murloc mobs in "The Bloodwash" - they feel very misplaced with Blacksilt Warrior mobs who are lvl 16-17 in the same area

**Expected behaviour**: 
So I looked it up and they should instead be level 15-17
https://www.wowhead.com/tbc/npc=17330/blacksilt-seer

**Server Revision**: 
3840

**Comment by EtheriousNW** [comment]
Fixed in 3846
