### ISSUE TITLE
[Core] Accept Queue when in Combat

### ISSUE THREAD

**Issue by tsu-1** [Atlantiss/NetherwingBugtracker#8579]
[//]: # (Enclose links to things related to the bug using http://wowhead.com or any other TBC database.)
[//]: # (You can use screenshot ingame to visual the issue.)
[//]: # (Write your tickets according to the format:)
[//]: # ([Quest][Azuremyst Isle] Red Snapper - Very Tasty!)
[//]: # ([NPC] Magistrix Erona)
[//]: # ([Spell][Mage] Fireball)
[//]: # ([Npc][Drop] Ghostclaw Lynx)
[//]: # ([Web] Armory doesnt work)
[//]: # (To find server revision type `.server info` command in the game chat.)

**Description**: Summoned (Accepting Queue) into Battleground/Arena when in combat.

**Current behaviour**: You can accept a Battleground/Arena queue (Summon/Join Game) when in combat.

**Expected behaviour**: Shouldn't be able to accept a queue when in combat.

![image](https://github.com/Atlantiss/NetherwingBugtracker/assets/11255782/5200fa56-8c7c-4139-82b9-0cbc55450df8)

**Server Revision**: 3840

**Comment by Godmatik** [comment]
https://github.com/Atlantiss/NetherwingBugtracker/issues/8574

In this github the person says he can't join arena when in combat? 
Not sure if there is some sort of addon/other issue at play here

**Comment by Godmatik** [comment]
Tsu you can close this, Wolf fixed it
