### ISSUE TITLE
Researchers don't run away when freed from webs for They're Alive! Maybe...

### ISSUE THREAD

**Issue by csjansen** [Atlantiss/NetherwingBugtracker#858]
[//]: # (Enclose links to things related to the bug using http://wowhead.com or any other TBC database.)
[//]: # (You can use screenshot ingame to visual the issue.)
[//]: # (Write your tickets according to the format:)
[//]: # ([Quest][Azuremyst Isle] Red Snapper - Very Tasty!)
[//]: # ([NPC] Magistrix Erona)
[//]: # ([Spell][Mage] Fireball)
[//]: # ([Npc][Drop] Ghostclaw Lynx)
[//]: # ([Web] Armory doesnt work)

**Description**: 
Researchers don't run away when freed from webs for They're Alive! Maybe...
**Current behaviour**:
After being freed from webs, they just stand there until they despawn a while later.
**Expected behaviour**: 
Pretty sure they are supposed to say thank you and run off.
**Server Revision**:

**Comment by Evolvee** [comment]
rev Xd

made them run + added more texts + corrected language
