### ISSUE TITLE
Kael'thas Fight - Need to kick Pyroblast twice

### ISSUE THREAD

**Issue by Godmatik** [Atlantiss/NetherwingBugtracker#8582]
**Current behaviour**:
After a recent fix was put in - likely from https://github.com/Atlantiss/NetherwingBugtracker/issues/8513 - KT will cast the pyroblast a 2nd time after it is kicked, and you need to kick it again to stop the cast. See the below clip. I think the script is trying to force the 3rd pyroblast to go through.

https://clips.twitch.tv/QuaintBeautifulMangoGOWSkull-GZ6wfOReEsw9MtA7

**Expected behaviour**: 
Only need to kick pyroblast once to end the chain

**Server Revision**: 
3840

**Comment by Wolffenstein** [comment]
I reverted it for now so I'll reopen the other issue
