### ISSUE TITLE
[PVP] Grounding Totem interaction with Seals/Judgement

### ISSUE THREAD

**Issue by Godmatik** [Atlantiss/NetherwingBugtracker#8583]
**Current behaviour**:
If a judgement is active on a shaman from a seal - and he puts down a grounding totem - refreshing the judgement with melee attacks will instead dispel the judgement effect entirely and it eats the grounding totem.

https://youtu.be/XMzAnEpq778

**Expected behaviour**: 
The grounding totem should not have any interaction with judgements being refreshed

**Server Revision**: 
3841

**Comment by Wolffenstein** [comment]
Fixed in rev 3961.
