### ISSUE TITLE
DMT door bug/ Tribute and king loot vendor values

### ISSUE THREAD

**Issue by cubix2rube** [Atlantiss/NetherwingBugtracker#8585]
**Description**: 
when i try to to open last door of DMT and quickly/accidentally click it again, it never opens back and needs another key, also DMT tribute and king loot is lower than as it was in classic and in OG tbc, the barbarous blade for example was 7g according to my addon, then when i vendor it, it was 60silver fix these prices please, this will greatly helps us non-strat farmers, also fix dmt tribute king buffs it just aint working

**Comment by Godmatik** [comment]
The sell value is correct - the vendor value was reduced to 65s79c starting in TBC.

https://www.wowhead.com/tbc/item=18520/barbarous-blade#dropped-by

**Comment by Godmatik** [comment]
Door issue was fixed in https://github.com/Atlantiss/NetherwingBugtracker/issues/8615
And the sell value of the blade was addressed.

Only thing remaining is DMT tribute buffs issue, probably will be addressed whenever Wolf gets around to fully re-scripting the dungeon

**Comment by Godmatik** [comment]
DMT tribute issue will be fixed when Wolf has time to fully rebuild the dungeon, closing
