### ISSUE TITLE
Quest Ride the Lightning/Repolarized Magneto Sphere

### ISSUE THREAD

**Issue by aja318** [Atlantiss/NetherwingBugtracker#8587]
[Repolarized Magneto Sphere](https://www.wowhead.com/tbc/item=30818/repolarized-magneto-sphere)
[Ride the Lightning](https://www.wowhead.com/tbc/quest=10657/ride-the-lightning)
**Description**: 
Quest item Repolarized Magneto Sphere can no be used more than once without reloging.
**Current behaviour**:
When using Repolarized Magneto Sphere shield allowing capturing lightning strikes will appear but once it's dismissed it can not be applied again without logging out from character and logging back in. Attempts to apply shield again show no reaction except dismissing of currently active mount. It is possible to activate item once per loging on the character.
**Expected behaviour**: 
It should be possible to apply shield after item finish cooldown.
**Server Revision**: 
3841

**Comment by Godmatik** [comment]
Duplicate #8393
