### ISSUE TITLE
Canceling effect of  [Figurine - Nightseye Panther] doesn't cancel animation of panther

### ISSUE THREAD

**Issue by sasadubi** [Atlantiss/NetherwingBugtracker#8588]
[//]: # (Enclose links to things related to the bug using http://wowhead.com or any other TBC database.)
[//]: # (You can use screenshot ingame to visual the issue.)
[//]: # (Write your tickets according to the format:)
[//]: # ([Quest][Azuremyst Isle] Red Snapper - Very Tasty!)
[//]: # ([NPC] Magistrix Erona)
[//]: # ([Spell][Mage] Fireball)
[//]: # ([Npc][Drop] Ghostclaw Lynx)
[//]: # ([Web] Armory doesnt work)
[//]: # (To find server revision type `.server info` command in the game chat.)

**Description**: 
JC trinket -  [Figurine - Nightseye Panther], while used, causes animation of little panther to follow the owner (the person who used the trinket). However if a rogue wants to vanish, and he cancels the panther effect, the ingame little panther stays for the duration of trinket left.
This causes big issues in world pvp and arenas for rogues, because if they want to vanish, while trinket is canceled, they actually can but panther following it's owner, indicates where the rogue is, so it's easy to Flare him, Blizzard, Nova, any AoE effect ofc.

**Current behaviour**:
Upon Canceling  [Figurine - Nightseye Panther], the panther still stays active.

**Expected behaviour**: 
Upon Canceling  [Figurine - Nightseye Panther], the panther should be **despawned.**

**Server Revision**: 
3841

**Comment by Wolffenstein** [comment]
Fixed in rev 3855.
