### ISSUE TITLE
Auto-Shot Bug on newest revision

### ISSUE THREAD

**Issue by Echoxias** [Atlantiss/NetherwingBugtracker#859]
**Description**: 
Auto-Shot bug occurred again managed to record it, tried to attack the mob and repeatedly tried to shoot it but wouldn't complete.  Could be because the mob was bugged but it has also occurred on mobs that. weren't bugged.  Here's the video https://www.youtube.com/watch?v=NEUp1mFjrYw
**Current behaviour**:
Auto-Shot repeatedly gets canceled and doesn't complete.
**Expected behaviour**: 
Auto-Shot completes fully
**Server Revision**: 
[2083]

**Comment by Easyfraggy** [comment]
We need reproduction steps, could you explain what you did leading up to the bug?
