### ISSUE TITLE
Arcane shot, Kill Command, Steady Shot finish cast, and movement all delay auto even when completing before auto is meant to fire

### ISSUE THREAD

**Issue by spacct** [Atlantiss/NetherwingBugtracker#8592]
[//]: # (Enclose links to things related to the bug using http://wowhead.com or any other TBC database.)
[//]: # (You can use screenshot ingame to visual the issue.)
[//]: # (Write your tickets according to the format:)
[//]: # ([Quest][Azuremyst Isle] Red Snapper - Very Tasty!)
[//]: # ([NPC] Magistrix Erona)
[//]: # ([Spell][Mage] Fireball)
[//]: # ([Npc][Drop] Ghostclaw Lynx)
[//]: # ([Web] Armory doesnt work)
[//]: # (To find server revision type `.server info` command in the game chat.)

**Description**: As mentioned in the title, arcane shot, kill command, steady shot completing (meaning not the cast start, but specifically when it completes beyond a certain point but still before auto should fire), and even movement (ie: when moving between auto shots, if you stop moving even 0.5 seconds before auto is supposed to cast, it is still delayed) all delay auto shot firing. 

Baseline (without issues from instant casts/movement/steady completion):
![normal auto behavior](https://github.com/Atlantiss/NetherwingBugtracker/assets/104590778/1c285e83-3b3a-47cd-a174-c5ea01525de8)

**Current behaviour**: 
Arcane Shot:
![instants delay auto shot](https://github.com/Atlantiss/NetherwingBugtracker/assets/104590778/cfcad9e8-a016-42a8-964c-e112f3ed7502)

Kill Command:
![kill command delay auto shot](https://github.com/Atlantiss/NetherwingBugtracker/assets/104590778/3454dad8-790b-4599-a71c-bc2af1ab8068)

Steady Shot:
![steady shot delay auto shot](https://github.com/Atlantiss/NetherwingBugtracker/assets/104590778/8550a399-f3de-4aa8-8c24-354d6f25e6ef)

Movement:
![movement delay auto shot](https://github.com/Atlantiss/NetherwingBugtracker/assets/104590778/70ec8d73-b951-4bb0-8f43-9a149672ad37)

**Expected behaviour**:  Instant cast abilities should never delay or impact auto shot in any way whatsoever. If steadyshot completes the cast before auto shot is meant to fire, autoshot should still fire. If movement is completed before the 0.5 second autoshot cast time, the auto should fire on time. (See smooth autoshot behavior above and TBC Classic behavior below)

TBC Classic Behavior:
![TBC Classic behavior](https://github.com/Atlantiss/NetherwingBugtracker/assets/104590778/87de5233-53ab-456d-b429-d1e20d5c1718)

**Server Revision**:

**Comment by Godmatik** [comment]
Related:

https://github.com/Atlantiss/NetherwingBugtracker/issues/3738

**Comment by Wolffenstein** [comment]
This might break some things but we'll see. Fixed in rev 3851.

**Comment by spacct** [comment]
no evidence given, however, can confirm.

Auto shot should be affected by haste, and when stopping moving, there should be, at least, the wind-up (based on haste level) for the auto shot. IE: if auto shot cast time is 0.35 seconds based on haste, movement would need to end 0.35 seconds before autoshot cd passes for it to shoot without delay. 

If movement extends past that point, then the entire 0.35 second auto shot cast time should take place before it is fired.

Auto shot casting while moving (on direction change; become stationary momentarily on direction change):
![Netherwing Autoshot Casts While Changing Direction (Instant)](https://github.com/Atlantiss/NetherwingBugtracker/assets/104590778/afb5c21d-4861-4d74-af5f-ba8c4b080bef)

Auto shot casting virtually instantly when stopping moving right before it is meant to cast (meaning no wind-up was made whatsoever):
![Netherwing Autoshot Casts Without Haste-Affected Wind-up (Instant)](https://github.com/Atlantiss/NetherwingBugtracker/assets/104590778/71c46312-583c-409b-9489-db3f2ee766be)

**Comment by spacct** [comment]
no evidence guy. dont be a lazy a$$ next time and post evidence. or dont post.
