### ISSUE TITLE
[Bug] Some Healing Items still provide Bonus Damage

### ISSUE THREAD

**Issue by Tzeentch123** [Atlantiss/NetherwingBugtracker#8593]
https://cdn.discordapp.com/attachments/1063133316909371522/1135688101256245359/image.png

https://cdn.discordapp.com/attachments/1063133316909371522/1135688101562425394/image.png

https://cdn.discordapp.com/attachments/1063133316909371522/1135677998629134368/image.png

PvP Healing weapon is the one on screenshots, apparently Head/Leg enchants also do this

**Comment by Tzeentch123** [comment]
upon further testing it appears all item slots except trinkets do this, tested pve items in all slots. Headpiece only seems to apply the +12 from the healerenchant

**Comment by Tzeentch123** [comment]
Its possible some of it is a visual bug, the above screenshots show it clearly isnt in all cases

**Comment by Tzeentch123** [comment]
https://prnt.sc/hgczZ6FDZbmG (no items) 
https://prnt.sc/JEAX7DZGlVSR   (some healer boots)

The weird part is the damage gained doesnt give the amount it would in 2.3 patch, at least not in all cases (starting 2.3 these boots should provide 25 damage without gems/enchants, they give 9)

**Comment by Wolffenstein** [comment]
Fixed in rev 3844.
