### ISSUE TITLE
[Spell][Shaman] Earth Shield

### ISSUE THREAD

**Issue by SpaceCaramel** [Atlantiss/NetherwingBugtracker#8594]
[//]: # (Enclose links to things related to the bug using http://wowhead.com or any other TBC database.)
[//]: # (You can use screenshot ingame to visual the issue.)
[//]: # (Write your tickets according to the format:)
[//]: # ([Quest][Azuremyst Isle] Red Snapper - Very Tasty!)
[//]: # ([NPC] Magistrix Erona)
[//]: # ([Spell][Mage] Fireball)
[//]: # ([Npc][Drop] Ghostclaw Lynx)
[//]: # ([Web] Armory doesnt work)
[//]: # (To find server revision type `.server info` command in the game chat.)

**Description**: 
Earth Shield spell power coefficient is too high

**Current behaviour**:
Currently healing with 877 bh and purification (+10% healing talent) 904 if earth shield applied to shaman himself

= ( 270 (base) + 877 (bh) * 0,6271 (?) (spell power coefficient)) * 1.1 (?) (talent) = 904
Looks like it twiced for shaman if casted on himself. Maybe Purification talent calculated twiced

https://imgur.com/a/hGWsRLr

**Expected behaviour**: 
Spell power coefficient should be 285.7% / 10 (it was down from 10 to 6 charges later) = 0,2857 

if Earth Shield applied to another player spell power coefficient become 0,285 (which is correct)
= (270 base + 963 (bh) * 0,285 (spell power coefficient) ) * 1.1 = 599

https://imgur.com/a/8stPsDg

https://wowwiki-archive.fandom.com/wiki/Spell_power_coefficient?oldid=1492745

**Server Revision**: 3841

**Comment by SpaceCaramel** [comment]
I tried to reset talents to drop +10% healing talent (Purification)

And without talent healing
= (270 base + 877 (bh) * 0,5701 (spell power coefficient) = 770

With talent healing increased by 17%, i dont know how

Don't have too much gold for tests at horde

**Comment by SpaceCaramel** [comment]
Tested again: if Earth Shield applied to another player spell power coefficient become 0,285
Looks like it twiced for shaman if casted on himself

**Comment by Wolffenstein** [comment]
Fixed in rev 3844.
