### ISSUE TITLE
[Spell Queue System] Adjustments

### ISSUE THREAD

**Issue by Gornaut** [Atlantiss/NetherwingBugtracker#8595]
**Description**: 

**Currently the way Spell Queue mechanic is implemented on Netherwing is the following:** 
Any **spell with cast time** can be queued 400 ms before previous cast of the same spell is finished (correct me if it is a different value from 400 ms but point still holds). 
Good examples are - _Paladin's Holy Light, Mage's Frost/Fire Bolts and etc_. 
And for those kind of spells it is now working as intended.

However, there are few things that are not taken into account (not implemented), if we compare how the current Spell Queue system is implemented on Classic WoW:

**1) Spell Queue should work for any instant spells as well as spells with cast time,** 

**the way it should work is the following:** 
Assume you used Arcane Shot on Hunter and your Arcane Shot CD is currently ticking.
Now, if you press new Arcane Shot 400 ms before the previous one's CD fades, the new Arcane Shot is Queued and Launched Immediately upon previous Arcane Shot CD fades.

**EXAMPLES:**
**How it works with Spell Queue Window set to maximum 400 ms on Classic WoW:**
You can clearly see next Arcane Shot is queued when pressed withing 400 ms window.
https://youtu.be/Oeq04urfmjo

**How it works with Spell Queue Window set to minimum 0 ms on classic WoW (Same as currently on Netherwing):**
Same interaction but with Window set to 0 ms. Arcane Shot no longer queued and only Fires after CD fades,
https://youtu.be/Vx5KfqHb_5E

**How it works on current Netherwing revision 3841:**
Works same as with 0 ms window on classic. Arcane Shot is not queued and only Fires after CD fades,
https://youtu.be/Cdy8Uscqgr0

**2) If GCD is currently ticking, and you casted **ANY** Spell (either it is Instant Spell or Spell with Cast Time) it should be put into Spell Queue if you pressed the button 400 ms prio to GCD going off;**

**EXAMPLES:**
**How it works with Spell Queue Window set to maximum 400 ms on Classic WoW:**
Serpent Sting is queued while GCD is ticking, when pressed 400 ms before GCD fades.
https://youtu.be/pb_7KBj1HNk

**How it works with Spell Queue Window set to minimum 0 ms on classic WoW (Same as currently on Netherwing):**
Serpent Sting no longer queued while GCD is ticking.
https://youtu.be/nPkOOZ2zRRI

**How it works on current Netherwing revision 3841:**
Serpent Sting is not queued while GCD is ticking.
https://youtu.be/eUmLoJWXBsA

**3) Spell Queue was originally implemeted to reduce the need to adjust the rotation to deal with different input lag people may have.** Input lag may greatly vary, depends on your location, ISP and lots of different factors. 
a) If for one person 400 ms Spell Queue may be a blessing, since his/her normal ping is above 200 (as example).
b) For another person 400 ms Spell Queue window can be deadly long. For example, as a skilled Mage with low latency, let's say 20 ms, you do not want the Spell Queue to be 400 ms, cause you can easily add spell without GCD in those 400 ms window (for example Counter Spell).

**So, my point is:** 
the way it is currently implemented on Classic WoW is the most versatile way, where you have a command wich adjusts the Spell Queue Window for any of your characters:
1)  _/console SpellQueueWindow 300_ - to set your Spell Queue Window on 300 ms in this case;
2) _/dump GetCVar("SpellQueueWindow")_ - to check your current Spell Queue Window.

Spell Queue Window can be set between 0 to 400 ms. And any player can adjust the value for his particular input lag, playstyle and etc etc. 
So, if it is technically possible, i would suggest adding such command to Netherwing as well, to make it **much smoother** experience for all kind of players.

**Current Netherwing implementation seems to be only partial:**
1) Affecting only Spells with cast time, reducing that the input lag issue for casters/healers but **not reducing** it for the rest of the classes. 
2) Spell window seems to be Hard Coded to be 400 (or whatever the current value is) for everyone, not taking into account that some people may want to reduce it.

Jokes aside it is a killer feature that few actual pservers ever tried to implement and it is such QoL change that it can be a decisive point for some peope to stay on a server where it works so smooth compared to competitors.

Some links:
1) How Spell Queue System is implemented on classic - http://thedefiantguild.com/forums/discussion/15431.html
2) Proof that this system was first implemeted in OG TBC and mentioned in Patch Note - https://wowpedia.fandom.com/wiki/Patch_2.3.0     ("_Client spell cast requests are now sent to the server even if your player is already casting another spell. This eliminates the need for /stopcasting in macros to compensate for latency._")

**Server Revision**: 
3841

**Comment by Godmatik** [comment]
Nice detailed post!

As a heads up - when the first server was developed years ago (well before classic TBC), they did have a spell batching system all setup, however disabled it because after testing - I believe they found that players were not in favor of it. 

So I think the scripting of it is in place and can be flipped on - it is just not in use - maybe it is something that can be revisited though?

**Comment by ghost** [comment]
> As a heads up - when the first server was developed years ago (well before classic TBC), they did have a spell batching system all setup, however disabled it because after testing - I believe they found that players were not in favor of it.

Was it set to 400ms? That would explain the dislikes.

I think somewhere between 200 and 250 ms is the sweet spot, not feeling too sluggish and enabling all the interactions that depend on spell delay.

"The average reaction time to visual stimulus is around 250 milliseconds, and most people seem to be hard capped at around 190-200 ms with training."

**Comment by Wolffenstein** [comment]
I can't implement those things because the TBC client doesn't allow them, please don't compare it with Classic TBC because Classic client was built on top of Legion architecture which had those things added as features directly. I can only allow some lag tolerance IF I receive a spell packet from the client but most of the time it's your client blocking you from casting a spell, not me.

In rev 3844 I made a small change to allow some degree of GCD threshold provided the client actually sends a spell cast request, though I doubt it will change much since it was hard to trigger that when I was testing locally. Maybe it will be more generous with actual high latency.
