### ISSUE TITLE
Misdirection

### ISSUE THREAD

**Issue by Godmatik** [Atlantiss/NetherwingBugtracker#8596]
**Current behaviour**:
Explosive Trap - when combined with misdirect - should use up all charges when the trap activates and does so - however it appears only damage done to 3 mobs with the trap is being misdirected.

**Expected behaviour**: 
The damage done to ALL enemies by the explosive trap trigger should properly misdirect threat to the tank or whoever the ability was used on, even if it is more than 3 targets.

Reference below reddit thread from classic TBC, where a couple of people have confirmed this interaction:

![Explosive](https://github.com/Atlantiss/NetherwingBugtracker/assets/37913400/70d63e5c-5331-4095-a8ce-41032de467e7)

https://www.reddit.com/r/classicwow/comments/o84ipv/psa_misdirection/

**Server Revision**: 
3841

**Comment by Wolffenstein** [comment]
Fixed in rev 3844.
