### ISSUE TITLE
Auto Shot and Multi Shot Cast Times Needs to be Affected by All Haste Including BM Talents / Quiver etc.

### ISSUE THREAD

**Issue by spacct** [Atlantiss/NetherwingBugtracker#8598]
[//]: # (Enclose links to things related to the bug using http://wowhead.com or any other TBC database.)
[//]: # (You can use screenshot ingame to visual the issue.)
[//]: # (Write your tickets according to the format:)
[//]: # ([Quest][Azuremyst Isle] Red Snapper - Very Tasty!)
[//]: # ([NPC] Magistrix Erona)
[//]: # ([Spell][Mage] Fireball)
[//]: # ([Npc][Drop] Ghostclaw Lynx)
[//]: # ([Web] Armory doesnt work)
[//]: # (To find server revision type `.server info` command in the game chat.)

**Description**: Auto Shot and Multi Shot are taking too long to fire. From looking at frame by frame video, it appears that auto shot is taking 0.5 seconds to cast. That means it is not being affected by quiver haste and beast master talented haste (and likely other forms of haste as well). Auto shot should be affected by all forms of haste.  As can be seen by the below clips from TBC Classic, both auto and multi shots should be affected by all forms of haste decreasing their respective baseline casts below 0.5 seconds.

**Current behaviour**:
Netherwing behavior:
![steady shot delay auto shot](https://github.com/Atlantiss/NetherwingBugtracker/assets/104590778/617d315e-a02c-4cea-b0b4-f5ad94e63fe2)

**Expected behaviour**: 
Auto shot cast time should be affected by beast mastery 20% haste talent, quiver haste, improved aspect of the hawk, rapid fire, and all other forms of haste.

TBC Classic Hasted Auto Shot (0.1 second):
![TBC Classic Auto Hasted](https://github.com/Atlantiss/NetherwingBugtracker/assets/104590778/24fda586-9abd-41df-bf67-d078e7f183ae)

As compared with TBC Classic Un-Hasted Auto Shot and Un-Hasted Multi Shot (0.3 seconds):
![TBC Classic Auto Un-Hasted](https://github.com/Atlantiss/NetherwingBugtracker/assets/104590778/abe25884-a389-4d2b-bb65-6d6bc38430d9)

**Server Revision**:

**Comment by Godmatik** [comment]
No proof was provided, so here is video from classic:

https://www.youtube.com/watch?v=1sGyzdNE0PI

Seems to confirm that the auto-shot wind-up window should be lowered from the default 0.5 seconds and affected by the haste.

EDIT: looks like he added details from classic to his original post

**Comment by Wolffenstein** [comment]
Fixed in rev 3850.
