### ISSUE TITLE
Inferno (warlock spell)

### ISSUE THREAD

**Issue by Dettoamid** [Atlantiss/NetherwingBugtracker#8599]
[//]: # (Enclose links to things related to the bug using http://wowhead.com or any other TBC database.)
[//]: # (You can use screenshot ingame to visual the issue.)
[//]: # (Write your tickets according to the format:)
[//]: # ([Quest][Azuremyst Isle] Red Snapper - Very Tasty!)
[//]: # ([NPC] Magistrix Erona)
[//]: # ([Spell][Mage] Fireball)
[//]: # ([Npc][Drop] Ghostclaw Lynx)
[//]: # ([Web] Armory doesnt work)
[//]: # (To find server revision type `.server info` command in the game chat.)

**Description**: 
The infernal bug is divided into 4 parts
1. When an infernal falls on an area, the spell does not deal area damage and does not stun enemies for 2 seconds (as written in the tooltip)https://imgur.com/E5g4Wzi  https://www.wowhead.com/classic/spell=1122/inferno
I don't know about the Burning Crusade, but on Lich King, the damage when falling on the area also depends on the spell turn of the warlock, which is 100% spd https://wowwiki-archive.fandom.com/wiki/Spell_power_coefficient
2.Infernal when falling into the area does not obey the warlock for 5 minutes (as written in the tooltip) https://imgur.com/a/Q77nW45
3.Melee damage from hand has poor base damage, if you take other demons, then they deal much more damage at times. Since I don't have spell power yet, I'm not sure if infernal is still scaling spell power warlock https://imgur.com/a/aTQFAlF
4.the infernal must be immune to fire damage and fear/horror effects. There is no Fear Immunity or Horror effect on this server.
immunity to fear and fire damage he has since classic vanilla, this is a video from the official blizzard server flamegor
https://www.youtube.com/watch?v=KVe3__UwhZQ
**Current behaviour**:
https://www.youtube.com/watch?v=wPAM5lNOIq4
**Expected behaviour**: 
This is a video of how infernal is currently working on the Stormforge server, in this video you can see all 4 problems that I described above

**Server Revision**: 
2.4.3 Stormforge
![Снимок экрана 2023-08-08 184827](https://github.com/Atlantiss/NetherwingBugtracker/assets/57749042/9e02a1ad-97e7-4c15-a720-f429c4aa4b02)

**Comment by Godmatik** [comment]
Confirmed on points 1 and 2, more info here:
https://github.com/Atlantiss/NetherwingBugtracker/issues/2229

Regarding 3rd point though, from what I recall last server, the infernals had higher than normal damage output compared to classic. It might be a scaling inaccuracy.

**Comment by Dettoamid** [comment]
[Godmatik]
infernal hits much less than voidwalker, it shouldn't be like that, when I played vanilla classic and then burning crusade blizzard classic, infernal always hit 2 times stronger than felguard
I need to buy a subscription to vanilla classic and download warlock again, but I don't want to do that

**Comment by Dettoamid** [comment]
about why the infernal and doomguard hit much harder than on the burning crusade, there is a patch notes
Wrath of the Lich King [Patch 3.0.2](https://wowpedia.fandom.com/wiki/Patch_3.0.2) (2008-10-14): Cooldown reduced to 15 minutes, down from 1 hour. Duration reduced to 1 minute, down from 5 minutes+. Health increased by 30%, damage increased by 60%, and armor increased by 30%.

**Comment by Dettoamid** [comment]
https://wowpedia.fandom.com/wiki/Infernal_(warlock_minion)

**Comment by Dettoamid** [comment]
to tell the truth, I thought the infernal would work here, since there are sources from where to get the base, and this is vanilla classic, but alas, my desire to play here has disappeared after this bug, because with the help of this spell I will not have dps in pve and will not be like 3 pets in pvp

**Comment by Godmatik** [comment]
I am just referencing last TBC server a couple years ago - when infernals were used on Archimonde and Brut they were dealing roughly double damage compared to classic, So that's why I thought it was scaling issue with end-game gear/stats affecting the pet.

And I mean if you quitting over a single issue then alright I guess, bugs are fixed pretty quickly here this server, just check the changelog on discord, I would advocate for a bit of patience, but w/e

Al

**Comment by Dettoamid** [comment]
well, I will monitor periodically, if there are any positive changes, then I will continue to improve my character with pleasure

this problem kills my tactics in both pve and pvp

**Comment by Godmatik** [comment]
Infernal was fully rewritten a couple of months ago - resolved. Closing
