### ISSUE TITLE
There doesn't appear to be enough spawns of Mutated Tanglers and too many spawns of Enraged Ravagers

### ISSUE THREAD

**Issue by csjansen** [Atlantiss/NetherwingBugtracker#860]
[//]: # (Enclose links to things related to the bug using http://wowhead.com or any other TBC database.)
[//]: # (You can use screenshot ingame to visual the issue.)
[//]: # (Write your tickets according to the format:)
[//]: # ([Quest][Azuremyst Isle] Red Snapper - Very Tasty!)
[//]: # ([NPC] Magistrix Erona)
[//]: # ([Spell][Mage] Fireball)
[//]: # ([Npc][Drop] Ghostclaw Lynx)
[//]: # ([Web] Armory doesnt work)

**Description**: 
There doesn't appear to be enough spawns of Mutated Tanglers and too many spawns of Enraged Ravagers
**Current behaviour**:
There is a quest to kill 10 of the tanglers and there only appears to be 8 spawns on the island and like 60 spawns of Ravagers
**Expected behaviour**: 
Even them out a bit?
**Server Revision**:

**Comment by aresbrutus** [comment]
They are supposed to share spawn points. Will be fixed in one of the upcoming updates.
