### ISSUE TITLE
[Hunter] Entrapment and Improved Wing Clip on same DR

### ISSUE THREAD

**Issue by bluemanguy112** [Atlantiss/NetherwingBugtracker#8600]
**Description**: 
Entrapment and Improved Wing Clip share DR.

**Current behaviour**:
Entrapment and Improved Wing Clip currently share DR with each other.entr

**Expected behaviour**: 
They obviously should not share DR with each other. As far as I know, entrapment pretty much is off any DR category and only shares a DR timer with itself.

**Comment by Wolffenstein** [comment]
Can I get some source on that?

**Comment by Wolffenstein** [comment]
Fixed in rev 3847.

**Comment by ghost** [comment]
Source: Trust me bro

https://youtu.be/E94eBCCJwvo?t=193 (enemy priest; 3:14,3:28)
https://youtu.be/x4zOLZOtbGM?t=348 (enemy mage; 5:53,6:09)
