### ISSUE TITLE
Warp-Spring Coil , rogue trinket Internal Cooldown bugged

### ISSUE THREAD

**Issue by spinzw** [Atlantiss/NetherwingBugtracker#8603]
[//]: # (Enclose links to things related to the bug using http://wowhead.com or any other TBC database.)
[//]: # (You can use screenshot ingame to visual the issue.)
[//]: # (Write your tickets according to the format:)
[//]: # ([Quest][Azuremyst Isle] Red Snapper - Very Tasty!)
[//]: # ([NPC] Magistrix Erona)
[//]: # ([Spell][Mage] Fireball)
[//]: # ([Npc][Drop] Ghostclaw Lynx)
[//]: # ([Web] Armory doesnt work)
[//]: # (To find server revision type `.server info` command in the game chat.)

**Description**: 
There is a problem with the internal cooldown of the rogue trinket " Warp-Spring Coil " ( https://www.wowhead.com/tbc/item=30450/warp-spring-coil ) 

the internal cooldown is supposed to be 30 seconds , based off official warcraftlogs , and i also experienced that on private servers before . here is a screenshot of a log that shows it ( the buff last 15 seconds , and then is off for 15 seconds before proccing again , the fight lasted 1:30 min , u can see it procced 3 times , and the uptime is about 50% ) 
[](url)
![Capture d’écran 2023-08-11 143758](https://github.com/Atlantiss/NetherwingBugtracker/assets/137619538/5c35156b-9d43-4af8-a368-310612fffd1b) 
 
![Capture d’écran 2023-08-11 144307](https://github.com/Atlantiss/NetherwingBugtracker/assets/137619538/64d48caf-bbfb-4b0e-a488-9b4a5f55b2ce)

 here is also a screenshot from 2007 that shows that it was the same as TBC classic back in the days , 15 years ago 

**Current behaviour**:

right now the trinket procs , and then procs again 45 seconds later , which is a 33% uptime instead of 50%
**Expected behaviour**: 
the trinket should proc, and then proc again 30 seconds later giving a 50% Uptime
**Server Revision**:

**Comment by Wolffenstein** [comment]
Check changelog, it will be fixed in rev 3848.
