### ISSUE TITLE
Shadowfiend

### ISSUE THREAD

**Issue by ghost** [Atlantiss/NetherwingBugtracker#8604]
.

**Comment by Godmatik** [comment]
An attempted fix was already done here:

https://github.com/Atlantiss/NetherwingBugtracker/issues/8473

I'm guessing Wolf will need more details or steps to reproduce.

**Comment by Wolffenstein** [comment]
need more information, video or anything

the only reasons for Shadowfiend to drop its target in the code currently are:
- shadowfiend cannot actually see/detect the target
- the target is not a valid attack target for the shadowfiend
- the target is CC'd

**Comment by ghost** [comment]
.

**Comment by Wolffenstein** [comment]
It actually was not race change related (or at least I think so), but an issue with player controlled flag not being applied when you first summon the Shadowfiend.

Will be fixed in rev 3852, thank you for testing and the information.
