### ISSUE TITLE
[Spell][Priest] Divine Spirit

### ISSUE THREAD

**Issue by Weuyn** [Atlantiss/NetherwingBugtracker#8606]
[//]: # (Enclose links to things related to the bug using http://wowhead.com or any other TBC database.)
[//]: # (You can use screenshot ingame to visual the issue.)
[//]: # (Write your tickets according to the format:)
[//]: # ([Quest][Azuremyst Isle] Red Snapper - Very Tasty!)
[//]: # ([NPC] Magistrix Erona)
[//]: # ([Spell][Mage] Fireball)
[//]: # ([Npc][Drop] Ghostclaw Lynx)
[//]: # ([Web] Armory doesnt work)
[//]: # (To find server revision type `.server info` command in the game chat.)

**Description**: 
Divine spirit is not being dispelled on raid/party after spec swap
**Current behaviour**:
people are using the shadow priest to do the IDS buff on the raid
**Expected behaviour**: 
buffs should be removed on spec swap for balance reasons
**Server Revision**: 
3841

**Comment by Godmatik** [comment]
I believe Wolf said this was not possible to fix with dual spec as it stands, it can clear it for yourself but not others, but I will let him verify.

**Comment by Wolffenstein** [comment]
Can't do anything about it, it's just a side-effect of dual spec
