### ISSUE TITLE
Naxxramas: Teleport to Sapphiron and Kel'Thuzad

### ISSUE THREAD

**Issue by Raferty** [Atlantiss/NetherwingBugtracker#8607]
[//]: # (Enclose links to things related to the bug using http://wowhead.com or any other TBC database.)
[//]: # (You can use screenshot ingame to visual the issue.)
[//]: # (Write your tickets according to the format:)
[//]: # ([Quest][Azuremyst Isle] Red Snapper - Very Tasty!)
[//]: # ([NPC] Magistrix Erona)
[//]: # ([Spell][Mage] Fireball)
[//]: # ([Npc][Drop] Ghostclaw Lynx)
[//]: # ([Web] Armory doesnt work)
[//]: # (To find server revision type `.server info` command in the game chat.)

**Description**: 
Teleport to Sapphiron and Kel'Thuzad not working

**Current behaviour**:
after killing all the bosses, the runes near the portal did not activate and the teleport did not work. I spoke with GM Bee an hour later and he told me that few bosses are still alive.

**Expected behaviour**: 
after killing all the bosses, a teleport to the last two bosses should be activated

**Server Revision**: 
3841

**Comment by Tholin44** [comment]
And one more bug, if u die inside of naxx and then release, you are not able to enter the instance anymore - "portal" (the platform which should teleport you in) does nothing. 

We had to join BG.

**Comment by Godmatik** [comment]
Naxx needs a full rework at some point, closing for now.
