### ISSUE TITLE
Wrong spell queueing causing GCDs

### ISSUE THREAD

**Issue by ploplopploplop** [Atlantiss/NetherwingBugtracker#8608]
[//]: # (Enclose links to things related to the bug using http://wowhead.com or any other TBC database.)
[//]: # (You can use screenshot ingame to visual the issue.)
[//]: # (Write your tickets according to the format:)
[//]: # ([Quest][Azuremyst Isle] Red Snapper - Very Tasty!)
[//]: # ([NPC] Magistrix Erona)
[//]: # ([Spell][Mage] Fireball)
[//]: # ([Npc][Drop] Ghostclaw Lynx)
[//]: # ([Web] Armory doesnt work)
[//]: # (To find server revision type `.server info` command in the game chat.)

**Description**: Casting Elemental Mastery followed by Chain Lightning sometimes causes a GCD and no Chain Lightning cast, as if it was interrupted. It appears that the server inputs the Chain Lightning first and then Elemental Mastery, which interrupts the Chain Lightning cast and causes the GCD. I believe the same issue has been reported for other classes with other spells before. Video attached where you can see I press Elemental Mastery then Chain Lightning, both spells are triggered but in the wrong order. I imagine it's a client issue and not a server issue but seems like a pretty major problem. And I imagine it goes unnoticed for a lot of players. For example using a trinket + instant ability where there is no interrupt but the instant ability is triggered before the trinket. Pretty bad dps loss. I guess castsequence macros for everything could be the solution.

**Current behaviour**:

**Expected behaviour**: 

https://github.com/Atlantiss/NetherwingBugtracker/assets/140337833/20f27c28-e34b-454e-b57a-6f892ab29f94

**Server Revision**:

**Comment by ploplopploplop** [comment]
I just had the same interrupt problem happening with a casequence macro so I guess nobody is safe...

**Comment by Wolffenstein** [comment]
should be fixed
