### ISSUE TITLE
[SSC] Coilfang Frenzy don't spawn if you have pet

### ISSUE THREAD

**Issue by Godmatik** [Atlantiss/NetherwingBugtracker#8609]
**Current behaviour**:
If you have a pet summoned while inside the water in SSC - Coilfang Frenzy never spawn on you.

**Expected behaviour**: 
Coilfang Frenzy fish should spawn on you when you are swimming in the water before killing Lurker, even if you have a pet/companion out.

https://www.wowhead.com/tbc/npc=21508/coilfang-frenzy

**Server Revision**: 
3854

**Comment by Wolffenstein** [comment]
Fixed in rev 3855.
