### ISSUE TITLE
[Quest / BiS Item] Can't retrieve Wrath of Cenarious reward 

### ISSUE THREAD

**Issue by StaticHispanic** [Atlantiss/NetherwingBugtracker#8610]
[//]: # (Enclose links to things related to the bug using http://wowhead.com or any other TBC database.)
[//]: # (You can use screenshot ingame to visual the issue.)
[//]: # (Write your tickets according to the format:)
[//]: # ([Quest][Azuremyst Isle] Red Snapper - Very Tasty!)
[//]: # ([NPC] Magistrix Erona)
[//]: # ([Spell][Mage] Fireball)
[//]: # ([Npc][Drop] Ghostclaw Lynx)
[//]: # ([Web] Armory doesnt work)
[//]: # (To find server revision type `.server info` command in the game chat.)

**Description**: 
The Champion's Battlegear quest in Silithus isn't showing up.

**Current behaviour**:
In Silithis, questgiver Vargus isn't giving a quest called Champion's Battlegear. 
In addition to that, there are SOME repeatable quests you need to farm to earn 'badges' for the quest, but once you've completed it once, it says "You're already on this quest" when you try to complete it again.

**Expected behaviour**: 
Questgiver Vargus is supposed to give a quest called Champion's Battlegear, which drops an AoE BiS called Wrath of Cenarious.

![Quest3](https://github.com/Atlantiss/NetherwingBugtracker/assets/142506452/2daa619f-d924-4216-a5a4-305ee10d8baa)
 

**Server Revision**:

**Comment by Wolffenstein** [comment]
Fixed in rev 3855.
