### ISSUE TITLE
Pre-spamming Multi-shot Before GCD Completes Triggers the following GCD Without Casting the Ability

### ISSUE THREAD

**Issue by spacct** [Atlantiss/NetherwingBugtracker#8612]
[//]: # (Enclose links to things related to the bug using http://wowhead.com or any other TBC database.)
[//]: # (You can use screenshot ingame to visual the issue.)
[//]: # (Write your tickets according to the format:)
[//]: # ([Quest][Azuremyst Isle] Red Snapper - Very Tasty!)
[//]: # ([NPC] Magistrix Erona)
[//]: # ([Spell][Mage] Fireball)
[//]: # ([Npc][Drop] Ghostclaw Lynx)
[//]: # ([Web] Armory doesnt work)
[//]: # (To find server revision type `.server info` command in the game chat.)

**Description**: Spamming multishot in anticipation of GCD ending can cause an entire GCD to be eaten without the cast going through.

Repost of this (link below): skills without global cd provoke a global cd every now and then. no idea what the cause is, but it happens daily. not very often, but reproducable, with or without addons activated. happens on both icy veins and counterspell.

Huge threads here: 
https://github.com/Atlantiss/NetherwingBugtracker/issues/5578
https://github.com/Atlantiss/NetherwingBugtracker/issues/7424
https://github.com/Atlantiss/NetherwingBugtracker/issues/7069

Reposting as this is an active issue. 

**Current behaviour**: e.g. spamming frostbolt, castin icy veins, global cooldown, next frostbolt

https://gfycat.com/PerfumedBewitchedHapuka

If you spam cast any spell (frostbolt here) you will get another action is in progress and GCD doesn't go off
If you spam conjure, there are no errors and the global cooldown starts again even if you're still casting

![Netherwing GCD Loss on Multi-Shot Cast](https://github.com/Atlantiss/NetherwingBugtracker/assets/104590778/745b8e04-33e1-4298-a423-22b6b1c2f636)
(there is a 2nd hunter (Night Elf) in this group that casts Multi-shot. If you dont pay close attention you may miss that. The Dwarf (this POV) fails to successfully cast Multi-shot)

**Expected behaviour**: You should be able to chaincast frostbolt, icy veins, frostbolt. you should also be able to spam your following cast prio to GCD completing with the risk of an entire GCD being eaten without a cast going through.

**Server Revision**:

**Comment by spacct** [comment]
@Wolffenstein 

Is this problem ever going to be addressed? It dates back to previous servers as well (as mentioned in the original post).

If not, please say so.

**Comment by Godmatik** [comment]
He was busy with 2.1 preparations and also fixing server lag on peaks with his optimizations last few weeks, I'll shoot him a DM reminder soon if needed, I agree this bug is very annoying.

**Comment by spacct** [comment]
@Wolffenstein this post is now 1 month old.

**Comment by Godmatik** [comment]
I DMed him about it yesterday, so hopefully it is resolved soon

**Comment by Wolffenstein** [comment]
Fixed in rev 3869.
