### ISSUE TITLE
Disarm

### ISSUE THREAD

**Issue by molkendan** [Atlantiss/NetherwingBugtracker#8614]
Current behaviour:
You can currently Disarm anything unless it's immune to disarm.

Expected behaviour: 
Using Disarm on a unit that does not have any weapons like a snake or bear etc should give the error message "Target has no weapons equipped" 
![Disarm error message tbc](https://github.com/Atlantiss/NetherwingBugtracker/assets/142650521/d18e980d-cd97-46ea-b44e-4eaa8af3eb0c)
Screenshot from Classic when a warrior used Disarm on Murmur

Server Revision: 
3854

**Comment by Wolffenstein** [comment]
Fixed in rev 3855.
