### ISSUE TITLE
Doors

### ISSUE THREAD

**Issue by molkendan** [Atlantiss/NetherwingBugtracker#8615]
Description: 
Doors currently can be spam clicked

Current behaviour:
Doors like Shade of Aran door or Shadow Labyrinth door can be spamclicked by all players

Expected behaviour: 
Doors like this should use a flag to prevent being clicked again for a few seconds called "GO_FLAG_IN_USE"

Server Revision: 
3854

**Comment by Godmatik** [comment]
Confirmed - this affects all doors even like the one in scarlet monastery cathedral. Should have a 3 second or so cooldown

**Comment by Wolffenstein** [comment]
Fixed in rev 3855.
