### ISSUE TITLE
[Item] Demon Forged Breastplate life-leech scaling too high

### ISSUE THREAD

**Issue by Massie323** [Atlantiss/NetherwingBugtracker#8616]
[//]: # (Enclose links to things related to the bug using http://wowhead.com or any other TBC database.)
[//]: # (You can use screenshot ingame to visual the issue.)
[//]: # (Write your tickets according to the format:)
[//]: # ([Quest][Azuremyst Isle] Red Snapper - Very Tasty!)
[//]: # ([NPC] Magistrix Erona)
[//]: # ([Spell][Mage] Fireball)
[//]: # ([Npc][Drop] Ghostclaw Lynx)
[//]: # ([Web] Armory doesnt work)
[//]: # (To find server revision type `.server info` command in the game chat.)

**Current behaviour**:
Demon Forged Breastplate effect currently scales 1:1 **per tick** (1 spelldmg = 4 total dmg+healing), so a ratio of 4. This is way too high, as it gives you neigh invulnerability in cases like Stratholme boosts, making bigger pulls easier than smaller pulls.

**Expected behaviour**: 
DFB should scale with a ratio of 0.4. 

https://www.wowhead.com/tbc/item=12628/demon-forged-breastplate#comments:id=3180782

**Server Revision**: 
3854

**Comment by Wolffenstein** [comment]
Fixed in rev 3855.
