### ISSUE TITLE
[NPC] Attacking Scryer/Aldor Flightmasters will spawn both Faction's Gryphons/Wyverns & stay indefinitely until entering combat once

### ISSUE THREAD

**Issue by Massie323** [Atlantiss/NetherwingBugtracker#8617]
[//]: # (Enclose links to things related to the bug using http://wowhead.com or any other TBC database.)
[//]: # (You can use screenshot ingame to visual the issue.)
[//]: # (Write your tickets according to the format:)
[//]: # ([Quest][Azuremyst Isle] Red Snapper - Very Tasty!)
[//]: # ([NPC] Magistrix Erona)
[//]: # ([Spell][Mage] Fireball)
[//]: # ([Npc][Drop] Ghostclaw Lynx)
[//]: # ([Web] Armory doesnt work)
[//]: # (To find server revision type `.server info` command in the game chat.)

**Description**: 
Pulling a Scryer or Aldor Flightmaster will spawn both an Enraged Gryphon and an Enraged Wyvern, one of which will of course be hostile and one friendly. The hostile one will automatically aggro on you, but after dropping combat once, will immediately despawn. The friendly one will stay indefinitely with proximity aggro active, meaning the next opposing faction player landing at the crossfaction flight path will immediately aggro the Enraged mount. Both NPCs not only move at 300% speed, making them unavoidable, but also come with 18k HP + hit like a truck, making fighting them rather difficult.

**Current behaviour**:
Crossfaction Flightmasters spawn both factions' Enraged NPC "guards" if attacked.

**Expected behaviour**: 
Should only spawn the one hostile to the player.

**Server Revision**: 
3854

https://www.youtube.com/watch?v=n3LMiIQSdfc

**Comment by Godmatik** [comment]
https://github.com/Atlantiss/NetherwingBugtracker/issues/6976

Related

**Comment by Wolffenstein** [comment]
Fixed in rev 3855.
