### ISSUE TITLE
[Item][Profession] Karazhan Mechanical units not immune to Gnomish Universal Remote

### ISSUE THREAD

**Issue by Massie323** [Atlantiss/NetherwingBugtracker#8618]
[//]: # (Enclose links to things related to the bug using http://wowhead.com or any other TBC database.)
[//]: # (You can use screenshot ingame to visual the issue.)
[//]: # (Write your tickets according to the format:)
[//]: # ([Quest][Azuremyst Isle] Red Snapper - Very Tasty!)
[//]: # ([NPC] Magistrix Erona)
[//]: # ([Spell][Mage] Fireball)
[//]: # ([Npc][Drop] Ghostclaw Lynx)
[//]: # ([Web] Armory doesnt work)
[//]: # (To find server revision type `.server info` command in the game chat.)

**Description**: 
[Gnomish Universal Remote](https://www.wowhead.com/classic/item=7506/gnomish-universal-remote) normally has a very limited range of non-immune Mechanical targets, making it a farily useless item. However a bunch notorious Mechanical units in this server are not immune. Primarily, both the Mechanical sentinel mob types in Karazhan, [Arcane Watchman](https://www.wowhead.com/tbc/npc=16485/arcane-watchman) and [Arcane Protector](https://www.wowhead.com/tbc/npc=16504/arcane-protector), can be freely mind-controlled, making quick work of magic-immune mana worms and the [Fel Reaver Sentry](https://www.wowhead.com/tbc/npc=19400/fel-reaver-sentry) in Hellfire Peninsula - Abyssal Shelf can be mind-controlled, allowing you to oneshot any player near Thrallmar.

**Current behaviour**:
Karazhan Mechanical units & Fel Reaver Sentry are not immune to Gnomish Universal Remote.

**Expected behaviour**: 
Mentioned mobs should be immune.

**Server Revision**: 
3854

https://www.youtube.com/watch?v=9gRS3u3Sl-4

**Comment by Wolffenstein** [comment]
Fixed in rev 3855.
