### ISSUE TITLE
[Shaman][Spell][Item] Sentry Totem + Steam Tonk Controller allows you to climb steep walls, clip through objects/doors and teleport large distances.

### ISSUE THREAD

**Issue by Massie323** [Atlantiss/NetherwingBugtracker#8619]
[//]: # (Enclose links to things related to the bug using http://wowhead.com or any other TBC database.)
[//]: # (You can use screenshot ingame to visual the issue.)
[//]: # (Write your tickets according to the format:)
[//]: # ([Quest][Azuremyst Isle] Red Snapper - Very Tasty!)
[//]: # ([NPC] Magistrix Erona)
[//]: # ([Spell][Mage] Fireball)
[//]: # ([Npc][Drop] Ghostclaw Lynx)
[//]: # ([Web] Armory doesnt work)
[//]: # (To find server revision type `.server info` command in the game chat.)

**Description**: 
After placing a Sentry Totem and using a Steam Tonk Controller, while the camera is set to the Tonk, you can right-click your Sentry Totem buff to swap the camera. This will however swap the camera to your character instead of Sentry Totem, allowing you to move while channeling the Steam Tonk Controller. In this mode, you can also climb extremely steep inclines without sliding off.
Until you cancel the effect of the Steam Tonk, your character will not appear to be moving. From an outsider's perspective, one can only see the Steam Tonk move, and if the Sentry Totem buff is toggled, the Steam Tonk will teleport between its "normal" position, and the position of your client-side character. Since your character is technically never moving, far away objects such as doors never render, allowing you to simply walk through them. Once behind with your client-side character, you can cancel the Steam Tonk effect and the next time you move, the server will update your position to the client-side position, effectively teleporting you.

**Current behaviour**:
Swapping Sentry Totem camera angle during Steam Tonk switches the 2nd Camera to your character & enables controls.

**Expected behaviour**: 
Swapping Sentry Totem camera angle during Steam Tonk should switch to the Sentry Totem.

https://github.com/Atlantiss/NetherwingBugtracker/assets/57675820/b36a0524-db32-48e9-93ea-0ab7e863a27f

https://github.com/Atlantiss/NetherwingBugtracker/assets/57675820/9a4bf9fb-7246-40cd-88a3-d90af2675b70

![imag43e](https://github.com/Atlantiss/NetherwingBugtracker/assets/57675820/d1b3cd77-5873-427b-a488-61fdafcc13e5)

**Server Revision**: 
3854

**Comment by Wolffenstein** [comment]
Fixed in rev 3855.
