### ISSUE TITLE
[Spell] Icy Chill enchant has full scaling after lvl 60

### ISSUE THREAD

**Issue by Massie323** [Atlantiss/NetherwingBugtracker#8621]
[//]: # (Enclose links to things related to the bug using http://wowhead.com or any other TBC database.)
[//]: # (You can use screenshot ingame to visual the issue.)
[//]: # (Write your tickets according to the format:)
[//]: # ([Quest][Azuremyst Isle] Red Snapper - Very Tasty!)
[//]: # ([NPC] Magistrix Erona)
[//]: # ([Spell][Mage] Fireball)
[//]: # ([Npc][Drop] Ghostclaw Lynx)
[//]: # ([Web] Armory doesnt work)
[//]: # (To find server revision type `.server info` command in the game chat.)

**Description**: 
[Icy Chill](https://www.wowhead.com/tbc/spell=20029/enchant-weapon-icy-chill) applies its full effect to enemies past lvl 60, instead of suffering a -4% penalty per level above.

**Current behaviour**:
Icy Chill applies full effect (-25% attack speed, -30% slow) to enemies above lvl 60.

**Expected behaviour**: 
Icy Chill should apply scaled effects (-15% attack speed, -18% slow) at lvl 70.

**Server Revision**: 
3854

![wow_IW14nkPwTq](https://github.com/Atlantiss/NetherwingBugtracker/assets/57675820/aaeac961-77d7-4304-81e1-33f1ad051f41)
Icy Chill

![wow_RDIfnrI61M](https://github.com/Atlantiss/NetherwingBugtracker/assets/57675820/7be53574-bd6a-43a9-91fd-52f67c8521fd)
Thunder Clap

![wow_cHtNPRaMfm](https://github.com/Atlantiss/NetherwingBugtracker/assets/57675820/e9af46c0-4428-432f-bc8a-8347bc96c665)
Imp. Thunder Clap

![wow_nxrnff6vNG](https://github.com/Atlantiss/NetherwingBugtracker/assets/57675820/1026dd75-13cb-4e20-b878-a8adfc37047e)
Base Reference

**Comment by Wolffenstein** [comment]
Source for the lvl 70 slow values?

**Comment by Godmatik** [comment]
No source provided, closing
