### ISSUE TITLE
[Spell] Mind Control teleporting caster to target for a milisecond on expiration

### ISSUE THREAD

**Issue by Massie323** [Atlantiss/NetherwingBugtracker#8622]
[//]: # (Enclose links to things related to the bug using http://wowhead.com or any other TBC database.)
[//]: # (You can use screenshot ingame to visual the issue.)
[//]: # (Write your tickets according to the format:)
[//]: # ([Quest][Azuremyst Isle] Red Snapper - Very Tasty!)
[//]: # ([NPC] Magistrix Erona)
[//]: # ([Spell][Mage] Fireball)
[//]: # ([Npc][Drop] Ghostclaw Lynx)
[//]: # ([Web] Armory doesnt work)
[//]: # (To find server revision type `.server info` command in the game chat.)

**Description**: 
When Mind Control expires on a target, the priest will teleport to them for a very brief moment. This is not a mere "visual inaccuracy", as the priest will be in range for melee attacks and spells during that brief moment. This works in both PvE and PvP. Especially in PvE, if you mind-control an NPC and the swing timer is ready, you will always eat an instant melee hit after the Mind Control.

**Current behaviour**:
Mind Control expiration teleports priest to target for very brief moment.

**Expected behaviour**: 
Priest shouldn't be teleported.

**Server Revision**: 
3854

https://github.com/Atlantiss/NetherwingBugtracker/assets/57675820/82425de2-4701-457e-8ff0-b3bd27a445c5

Maybe related to #7552

**Comment by Godmatik** [comment]
This occurs as well with Hunter spell Eyes of the Beast + Warlock Eye of Killrog.

**Comment by Wolffenstein** [comment]
Fixed in rev 3855.
