### ISSUE TITLE
Getting Sapped while in combat (cheating?)

### ISSUE THREAD

**Issue by Papito1337** [Atlantiss/NetherwingBugtracker#8623]
Hello, i got sapped while i was in combat two times in a row vs the same team, they are abusing or cheating i guess

I've recorded second time he did this: https://streamable.com/umroqc

**Comment by Godmatik** [comment]
You are not actually in combat - the UI just shows that when you are attempting to melee someone out of range, you can test this on any PvE mob, right click out of range and it will show 'in combat' for the UI when you are not.

**Comment by Papito1337** [comment]
I wish i had ss of combat log, im sure that i was still in combat, i checked combat log twice back then, forgot to ss this
