### ISSUE TITLE
[Item]Grimesilt Outhouse Key quest item is not shared loot drop

### ISSUE THREAD

**Issue by fondlez** [Atlantiss/NetherwingBugtracker#8624]
**Description**: 
[Grimesilt Outhouse Key](https://www.wowhead.com/tbc/item=11818/grimesilt-outhouse-key), which starts a quest and is a unique item, is not a shared loot drop in a group.

**Current behaviour**:
Not shared loot drop.

**Expected behaviour**: 
Shared loot drop like other group quest items.

**Server Revision**: 
Stormforge Netherwing | Content patch: 2.0.3 | Revision: 3854

**Comment by Wolffenstein** [comment]
Intended.
