### ISSUE TITLE
War Master Voon bugged

### ISSUE THREAD

**Issue by nabermert** [Atlantiss/NetherwingBugtracker#8625]
[//]: # (Enclose links to things related to the bug using http://wowhead.com or any other TBC database.)
[//]: # (You can use screenshot ingame to visual the issue.)
[//]: # (Write your tickets according to the format:)
[//]: # ([Quest][Azuremyst Isle] Red Snapper - Very Tasty!)
[//]: # ([NPC] Magistrix Erona)
[//]: # ([Spell][Mage] Fireball)
[//]: # ([Npc][Drop] Ghostclaw Lynx)
[//]: # ([Web] Armory doesnt work)
[//]: # (To find server revision type `.server info` command in the game chat.)

**Description**: War Master Voon is bugged

**Current behaviour**: he is stunning all 2-3 seconds

**Expected behaviour**: normal?

**Server Revision**:

**Comment by Godmatik** [comment]
wowhead comments mentions that his "Throw Axe" ability knocks you down, the spell details indicates that it is a 2 second stun

https://www.wowhead.com/wotlk/spell=16075/throw-axe

![knocksdown](https://github.com/Atlantiss/NetherwingBugtracker/assets/37913400/7af90e4d-e198-4dc2-a1e6-5f1d18db7edf)

**Comment by Wolffenstein** [comment]
Fixed in rev 3944.
