### ISSUE TITLE
[2.1 PTR] - Hyjal/BT - Drop too much loot

### ISSUE THREAD

**Issue by Godmatik** [Atlantiss/NetherwingBugtracker#8627]
**Current behaviour**:
Hyjal and BT currently drop too much loot from bosses, a custom buff given to the raids a few months after the patch release on the last server.

Azgalor/Mother/Counil are giving 3 tier pieces + 2 items.
Illidan/Archimonde are giving 3 tier pieces + 3 items.
All other non-tier boss are giving 3 non-tier drops.

**Expected behaviour**: 
It should be only 2 item drops per non-tier boss and 1 item + 2 tier drops from those bosses who can drop tier (I think 2 item + 2 tier drops for Illidan and Archimonde)

![tier1](https://github.com/Atlantiss/NetherwingBugtracker/assets/37913400/06b88d6f-34f5-4fc4-896a-18f3596bfdcf)

![Tier2](https://github.com/Atlantiss/NetherwingBugtracker/assets/37913400/ebdecc5b-4923-4067-9c63-2f6585a2af74)

**Server Revision**: 
3855

**Comment by Wolffenstein** [comment]
Fixed in rev 3856.
