### ISSUE TITLE
[2.1 PTR] Hyjal - All dead Human/Orc NPCs should respawn

### ISSUE THREAD

**Issue by Godmatik** [Atlantiss/NetherwingBugtracker#8628]
**Current behaviour**:
After killing Rage Winterchill - all of the dead human NPCs do not respawn after talking with Jaina to start the Anetheron trash waves
The same is true of the orc NPCs after defeating Kaz'rogal - they are not respawning when you start the Azgalor trash with Thrall

**Expected behaviour**: 
When talking with Jaina or Thrall to start the next boss trash waves - all dead human/orc NPCs should fully respawn

https://www.youtube.com/watch?v=qvQmLlN2Rzs&t=15m20s

NPCs dead after Rage is killed, respawned after talking with Jaina

**Server Revision**: 
3855

**Comment by Wolffenstein** [comment]
Fixed in rev 3856.
