### ISSUE TITLE
[2.1 PTR] Hyjal - Azgalor - Doom

### ISSUE THREAD

**Issue by Godmatik** [Atlantiss/NetherwingBugtracker#8629]
**Current behaviour**:
If player goes offline or leaves raid instance (hearthstone) with doom debuff during Azgalor encounter, then a doomguard is not spawned. In the case of the offline player, will log back in alive with no debuff.

**Expected behaviour**: 
Doomguard should probably be spawned automatically if someone with debuff tries to cheese their way out of the raid

**Server Revision**: 
3855

**Comment by Wolffenstein** [comment]
Fixed in rev 3856.
