### ISSUE TITLE
Young Goretusk using rushing charge continuously in melee. 

### ISSUE THREAD

**Issue by Dosdaltherir** [Atlantiss/NetherwingBugtracker#863]
**Description**:
The npc "Young Goretusk" that can be found in Westfall will continuously use the ability "Rushing Charge" while within melee range.
**Current behaviour**:
The npc "Young Goretusk" is using the ability "Rushing Charge" while within melee range.
**Expected behaviour**: 
The npc "Young Goretusk" should only use the ability "Rushing Charge" if the enemy player is outside of melee range.
**Server Revision**: 
2083

**Comment by Mikik3jr** [comment]
Not just the Young Goretusk, but every boar that has that ability.

**Comment by Easyfraggy** [comment]
https://github.com/Atlantiss/NetherwingBugtracker/issues/457
