### ISSUE TITLE
[2.1 PTR] - Rumsey Rum and other drinks should not stack with food buffs

### ISSUE THREAD

**Issue by Godmatik** [Atlantiss/NetherwingBugtracker#8630]
**Current behaviour**:
Currently, Rumsey Rum + other drinks are still stacking with food buffs on the 2.1 PTR.

**Expected behaviour**: 
They should not stack starting in patch 2.1. From patch notes:

![Rumsey](https://github.com/Atlantiss/NetherwingBugtracker/assets/37913400/19b5b935-220f-48cd-8d13-5b440dd09dd3)

And although it sounds like this might only affect food buffs that give stamina, a wowhead comment states that these drinks should not stack with ANY food buff:

![FoodBuff](https://github.com/Atlantiss/NetherwingBugtracker/assets/37913400/eecd2092-05d0-4ded-afb6-6ffeb22d4312)

**Server Revision**: 
3855

**Comment by Wolffenstein** [comment]
Fixed in rev 3861.
