### ISSUE TITLE
[2.1 PTR] - Anetheron Voice clips missing

### ISSUE THREAD

**Issue by Godmatik** [Atlantiss/NetherwingBugtracker#8631]
**Current behaviour**:
Anetheron is missing voice clips + yells for a few of his abilities

**Expected behaviour**: 
Infernal - "Let fire rain from above!" or "Earth and sky shall burn!" (Should yell this AFTER his ability is done casting)

Carrion Swarm - "The swarm is eager to feed." or "Pestilence upon you!"

Sleep - "You look tired...." or "Sweet dreams."

https://www.wowhead.com/wotlk/npc=17808/anetheron#sounds;mode:n25

https://www.youtube.com/watch?v=ha6FkoIhRK0

In watching this classic video, it looks like occasionally he skips the voice clip for carrion swarm/sleep, so maybe some type of blizzlike bug there. But he always seemed to do if for Infernal.

**Server Revision**: 
3855

**Comment by Wolffenstein** [comment]
Fixed in rev 3856.
