### ISSUE TITLE
UnitBuff function returns no duration/expiration for player buffs with duration upon relogging

### ISSUE THREAD

**Issue by RichSteini** [Atlantiss/NetherwingBugtracker#8632]
[//]: # (Enclose links to things related to the bug using http://wowhead.com or any other TBC database.)
[//]: # (You can use screenshot ingame to visual the issue.)
[//]: # (Write your tickets according to the format:)
[//]: # ([Quest][Azuremyst Isle] Red Snapper - Very Tasty!)
[//]: # ([NPC] Magistrix Erona)
[//]: # ([Spell][Mage] Fireball)
[//]: # ([Npc][Drop] Ghostclaw Lynx)
[//]: # ([Web] Armory doesnt work)
[//]: # (To find server revision type `.server info` command in the game chat.)

**Description**: 
Title pretty much says everything. It doesn't matter which buff you apply as long as it has a duration from what i have tested so far. Video reference that shows the bug: https://youtu.be/dtPVQq3n-A0. Only addon used in this case is !Compatibility to get a print implementation. I also tried it without any addons and it yields the same result. You can test it with this command without addons installed, which should give the duration of the first buff: /run DEFAULT_CHAT_FRAME:AddMessage(select(5, UnitBuff("player", 1)))
**Current behaviour**:
UnitBuff only returns proper duration/expiration when the buff is freshly applied. After relogging UnitBuff returns nil for both values.
**Expected behaviour**: 
UnitBuff should always return the proper duration/expiration even after relogging. I tested it on Smoulderforge and it works there as expected.
**Server Revision**: 
3855

**Comment by Godmatik** [comment]
More information also here:

https://github.com/Atlantiss/NetherwingBugtracker/issues/8159

Not certain why Mec closed this issue, but its not resolved

**Comment by Godmatik** [comment]
Fixed in next update.
