### ISSUE TITLE
[2.1 PTR] - Black Temple - Ashtongue Mystic - Windfury totem

### ISSUE THREAD

**Issue by Godmatik** [Atlantiss/NetherwingBugtracker#8634]
**Current behaviour**:
When windfury totem is destroyed from Ashtongue Mystic - the windfury buffs only dissipate from the Mystic itself and not any other NPCs that are along with him.

In addition - there are two "buffs" when a windfury totem is dropped. One says "windfury weapon", the other is "windfury" with a green siphon life buff icon, and an extra one gets added in with each new totem dropped.

![WFwep](https://github.com/Atlantiss/NetherwingBugtracker/assets/37913400/5c2de2eb-b219-4d92-9c99-257c4e4171c3)
![WF](https://github.com/Atlantiss/NetherwingBugtracker/assets/37913400/229c241f-68bb-4051-bb69-6d8c6346e5ef)

**Expected behaviour**: 
Windfury buff should be removed from all mobs when the totem is killed - not just from the Mystic that placed the totem.

https://www.wowhead.com/tbc/npc=22845/ashtongue-mystic#abilities;mode:n25

**Server Revision**: 
3855

**Comment by Wolffenstein** [comment]
Fixed in rev 3856.
