### ISSUE TITLE
Eternal Quintessence - suggestion

### ISSUE THREAD

**Issue by Tholin44** [Atlantiss/NetherwingBugtracker#8637]
[//]: # (Enclose links to things related to the bug using http://wowhead.com or any other TBC database.)
[//]: # (You can use screenshot ingame to visual the issue.)
[//]: # (Write your tickets according to the format:)
[//]: # ([Quest][Azuremyst Isle] Red Snapper - Very Tasty!)
[//]: # ([NPC] Magistrix Erona)
[//]: # ([Spell][Mage] Fireball)
[//]: # ([Npc][Drop] Ghostclaw Lynx)
[//]: # ([Web] Armory doesnt work)
[//]: # (To find server revision type `.server info` command in the game chat.)

Would it be possible to remove CD from Eternal Quintessence? (https://www.wowhead.com/classic/item=22754/eternal-quintessence)

Its for Molten Core to disable runes so we can kill Majordomo and Ragnaros, its kinda long quest chain and ppl wont/dont wanna do it.
There is 7 runes to disable in MC and it would take 7hours/every week.

Without CD we would be able to clear MC every week without waiting 1h for 1 rune.

**Comment by Wolffenstein** [comment]
Removed in revision 3883.
