### ISSUE TITLE
[2.1 PTR] - Small fix needed for Anetheron voice clip

### ISSUE THREAD

**Issue by Godmatik** [Atlantiss/NetherwingBugtracker#8638]
**Current behaviour**:
When casting Inferno - Antheron currently says his voice line at start of cast

**Expected behaviour**: 
Should say his voice line at END of cast

https://www.youtube.com/watch?v=ha6FkoIhRK0&t=88s

**Server Revision**: 
3856

**Comment by Wolffenstein** [comment]
Fixed in rev 3857.
