### ISSUE TITLE
[2.1 PTR] - Black Temple - Priestess of Torment

### ISSUE THREAD

**Issue by Godmatik** [Atlantiss/NetherwingBugtracker#8639]
**Current behaviour**:
Basically just review this below linked bug report - I confirm it is still active

https://github.com/Atlantiss/NetherwingBugtracker/issues/6932

**Expected behaviour**: 
Priestess of Torment should not stop attacking after casting her shell

**Server Revision**: 
3856

**Comment by Wolffenstein** [comment]
Fixed in rev 3857.
