### ISSUE TITLE
[Quest] Bloody Bone Necklaces 

### ISSUE THREAD

**Issue by despairr1** [Atlantiss/NetherwingBugtracker#864]
[//]: # (Enclose links to things related to the bug using http://wowhead.com or any other TBC database.)
[//]: # (You can use screenshot ingame to visual the issue.)
[//]: # (Write your tickets according to the format:)
[//]: # ([Quest][Azuremyst Isle] Red Snapper - Very Tasty!)
[//]: # ([NPC] Magistrix Erona)
[//]: # ([Spell][Mage] Fireball)
[//]: # ([Npc][Drop] Ghostclaw Lynx)
[//]: # ([Web] Armory doesnt work)

**Description**: 
Extremely low drop rate. Farmed well over 200 and got 9 so far for a quest that requires 25.
**Current behaviour**:
LOW LOW LOW Drop Rate
**Expected behaviour**: 
Bring it up atleast a little, its insanity. 
**Server Revision**: 
2083

**Comment by Jezofine** [comment]
Drop is pretty low, but I didn't have that much problem farming it. Maybe bad luck
[Thottbot](http://thottbot.com:80/i3915)

**Comment by aresbrutus** [comment]
Fixed in one of the upcoming updates.

**Comment by Tamezz** [comment]
I got a big problem with this quest. I got the 25 quest items but the vendor didnt accept them.
I got a SS for that: [https://imgur.com/Jqmy35x](url)
