### ISSUE TITLE
[2.1 PTR] - Hyjal - Inferno in trash packs occasionally fails to spawn

### ISSUE THREAD

**Issue by Godmatik** [Atlantiss/NetherwingBugtracker#8640]
**Current behaviour**:
If a Giant Infernal attempts to spawn/land on an NPC that is an evade state (typically because they are resetting to their position after fighting a mob from previous wave) - like a tauren - it will not spawn at all for that wave

**Expected behaviour**: 
Giant Infernal should always spawn

**Server Revision**: 
3856

**Comment by Wolffenstein** [comment]
Fixed in rev 3857.
