### ISSUE TITLE
[2.1 PTR] - Hyjal - Wrong mobs on certain wave

### ISSUE THREAD

**Issue by Godmatik** [Atlantiss/NetherwingBugtracker#8641]
**Current behaviour**:
Wave 6 of 8 for Kaz'rogal trash packs - only spawns 6 gargoyles and 1 frost wyrm

**Expected behaviour**: 
Should be 8 gargoyles and 1 frost wyrm

![Kazrogal](https://github.com/Atlantiss/NetherwingBugtracker/assets/37913400/9562c915-52b1-4e86-a5d2-9e4f95260dd2)

https://www.youtube.com/watch?v=DOAzEVfEKBE&t=615s

**Server Revision**: 
3856

**Comment by Wolffenstein** [comment]
Fixed in rev 3857.
