### ISSUE TITLE
[2.1 PTR] - Hyjal - Kaz'rogal - Voice line

### ISSUE THREAD

**Issue by Godmatik** [Atlantiss/NetherwingBugtracker#8642]
**Current behaviour**:
Missing voice line + /yell when he casts Mark of Kaz'rogal

**Expected behaviour**: 
Should use voice line + /yell when casting Mark of Kaz'rogal

https://www.wowhead.com/tbc/npc=17888/kazrogal#sounds;mode:n25

**Server Revision**: 
3856

**Comment by Wolffenstein** [comment]
Fixed in rev 3857.
