### ISSUE TITLE
[2.1 PTR] - Naj'entus - Horseshoe Swipe

### ISSUE THREAD

**Issue by Godmatik** [Atlantiss/NetherwingBugtracker#8643]
**Current behaviour**:
Naj'entus currently has ability "Horseshoe Swipe"

**Expected behaviour**: 
Can not find this ability either on wowhead classic or logs, appears that he should not have it.

I do see it when I search retail wowhead + look at timewalking strategies for it. I guess for some reason it was added to him at a later expansion?

https://www.wowhead.com/tbc/npc=22887/high-warlord-najentus#abilities;mode:n25
https://classic.warcraftlogs.com/reports/PcQ7RApLqVCh36HX#fight=39&type=damage-done&hostility=1&source=313

**Server Revision**: 
3856

**Comment by Wolffenstein** [comment]
intended

**Comment by Godmatik** [comment]
Why do none of these classic logs have it then o.O

Is this an ability on his spell list Blizz forgot to activate?
