### ISSUE TITLE
[2.1 PTR] - Teron Gorefiend aggro range

### ISSUE THREAD

**Issue by Godmatik** [Atlantiss/NetherwingBugtracker#8645]
**Current behaviour**:
Aggro radius is very small for Teron Gorefiend boss in BT

**Expected behaviour**: 
Should probably be bigger

![image](https://github.com/Atlantiss/NetherwingBugtracker/assets/37913400/2545ed6c-1eb9-4f38-b3bf-20f83a72240b)

**Server Revision**: 
3857

**Comment by Wolffenstein** [comment]
Intended

**Comment by Godmatik** [comment]
Yeah my bad, was same on TBC original and classic
