### ISSUE TITLE
[2.1 PTR] - Anetheron Infernal Spawn (suggestion)

### ISSUE THREAD

**Issue by Godmatik** [Atlantiss/NetherwingBugtracker#8646]
**Current behaviour**:
Anetheron's Infernal casting spawn can be dodged completely with a flask of petrification, divine intervention, cloaking field (engi trinket), feign death, and vanish

**EDIT: Also a person who goes offline use the disconnect macro can also stop cast**

**Expected behaviour**: 
Similar to Solarian - I am suggesting to disable flask of petrification + divine intervention at the very least - since the Infernals are a major aspect of the fight and removing them completely with everyone bringing flask of petri and/or paladins makes it a snoozefest encounter.

And if someone goes offline when target with it - IMO it should be summoned regardless

**Server Revision**: 
3857

**Comment by Wolffenstein** [comment]
Fixed in rev 3860.
