### ISSUE TITLE
[2.1 PTR] - Illidari Council dropping too little loot

### ISSUE THREAD

**Issue by Godmatik** [Atlantiss/NetherwingBugtracker#8647]
**Current behaviour**:
Illidari Council after recent revision now drops 1x non-token item and 1x tier piece. Only two of the 4 bosses were lootable.

![image](https://github.com/Atlantiss/NetherwingBugtracker/assets/37913400/724af323-3c13-4695-bb34-78a9e38d135c)

**Expected behaviour**: 
Should be 1x non-token item + 2x tier piece

**Server Revision**: 
3857

**Comment by Wolffenstein** [comment]
Fixed in rev 3860.
