### ISSUE TITLE
[2.1 PTR] - Thrall dropped gold in Hyjal

### ISSUE THREAD

**Issue by Godmatik** [Atlantiss/NetherwingBugtracker#8648]
**Current behaviour**:
Thrall died in Mount Hyjal - was able to loot him and receive 250g before his corpse despawned

**Expected behaviour**: 
Should not be able to loot Thrall. Didn't verify if you could do the same to Jaina.

EDIT: yep Jaina too

**Server Revision**: 
3857

**Comment by Wolffenstein** [comment]
Fixed in rev 3860.
