### ISSUE TITLE
[2.1 PTR] - Rage Winterchill - Icebolt

### ISSUE THREAD

**Issue by Godmatik** [Atlantiss/NetherwingBugtracker#8649]
**Current behaviour**:
Rage Winterchill does not target the individual he is casting Icebolt on

**Expected behaviour**: 
Rage Winterchill should target the individual he is using Icebolt on - even though it's an instant cast ability.

https://www.wowhead.com/tbc/spell=31249/icebolt
https://www.youtube.com/watch?v=kydGz9GfWSY&t=18s

**Server Revision**: 
3857

**Comment by Wolffenstein** [comment]
Fixed in rev 3866.
