### ISSUE TITLE
[NPC] Thistlefur Avenger and Shaman stacking spawn

### ISSUE THREAD

**Issue by tcberk12** [Atlantiss/NetherwingBugtracker#865]
**Description**: There is a pair of Thistlefur furbolg (1 shaman, 1 avenger) that have a stacked spawn in Ashenvale.

**Current behaviour**:
<img width="779" alt="screen shot 2018-09-29 at 12 13 37 am" src="https://user-images.githubusercontent.com/43530009/46242352-e8915600-c37c-11e8-9bdd-b3689fc59f08.png">

NPC info/ID can be seen in the chat.

**Expected behaviour**: 
Spawns should not be stacked/standing within each other.

**Server Revision**: 
2083

**Comment by aresbrutus** [comment]
Fixed in one of the upcoming updates.
