### ISSUE TITLE
[2.1 PTR] - Giant Infernal tauntable

### ISSUE THREAD

**Issue by Godmatik** [Atlantiss/NetherwingBugtracker#8650]
**Current behaviour**:
Giant Infernal (Hyjal trash wave mob) are not tauntable

**Expected behaviour**: 
They should be tauntable

https://www.youtube.com/watch?v=qvQmLlN2Rzs&t=3420s

**Server Revision**: 
3857

**Comment by Wolffenstein** [comment]
Fixed in rev 3860.
