### ISSUE TITLE
[2.1 PTR] - Archimonde - Boss has a very hard time moving

### ISSUE THREAD

**Issue by Godmatik** [Atlantiss/NetherwingBugtracker#8652]
**Current behaviour**:
Archimonde has a very difficult time moving.

First ~20 seconds of encounter he moves with tank, but after he casts second doomfire (or so) he no longer is moving.

**Expected behaviour**: 
He should be able to move around entire encounter if the tank moves and not just stand still at times.

Classic video showing him moving as needed with the tank:
https://www.youtube.com/watch?v=YlMFFTwZTJ8

**Server Revision**: 
3857

**Comment by Wolffenstein** [comment]
Fixed in rev 3860.
