### ISSUE TITLE
[Enchant] Healing Power to ring not stackable

### ISSUE THREAD

**Issue by khah97** [Atlantiss/NetherwingBugtracker#8655]
[//]: # (Enclose links to things related to the bug using http://wowhead.com or any other TBC database.)
[//]: # (You can use screenshot ingame to visual the issue.)
[//]: # (Write your tickets according to the format:)
[//]: # ([Quest][Azuremyst Isle] Red Snapper - Very Tasty!)
[//]: # ([NPC] Magistrix Erona)
[//]: # ([Spell][Mage] Fireball)
[//]: # ([Npc][Drop] Ghostclaw Lynx)
[//]: # ([Web] Armory doesnt work)
[//]: # (To find server revision type `.server info` command in the game chat.)

**Description**: Upon manually adding all of my characters +heal i came to the number 2070 but realized i have 2050 +heal on my character screen as well as the armory (this is not a cache issue as i previously thought because i tried a fresh client as well). Both of my rings are enchanted with +20 healing, when i unequip both and then equip only ONE, regardless of which ring i equip, the first one adds the proper healing to the character (base + enchant), but when i equip the second ring, regardless of whichever it is, it only adds its base healing power to the character and the +20 healing from the enchant is missing. This leads me to think these enchants are not stacking and maybe are being treated as unique. I am at 1982 BH and equip a ring with 68 BH + 20 BH from enchant, after equipping it i get to 2050 BH whereas the correct value would be 2070 BH. See screenshot attached: 
![image](https://github.com/Atlantiss/NetherwingBugtracker/assets/143663894/e7caca4c-239e-4425-ad19-35c7136ee3b7)
![image](https://github.com/Atlantiss/NetherwingBugtracker/assets/143663894/e00aa6bc-f788-40be-bcfe-352e9a2b4c6c)

**Current behaviour**: Only 1/2 ring enchants are adding 20 bonus heal to the character

**Expected behaviour**: ring enchants should collectively add 40 bonus healing to the character

**Server Revision**:  3859

**Comment by Godmatik** [comment]
Was a bug in old server and fixed, but looks like it's back
https://github.com/Atlantiss/NetherwingBugtracker/issues/2779

**Comment by khah97** [comment]
It seems the other ring also loses its +20 healing sometimes, until re-equipped

**Comment by Wolffenstein** [comment]
Fixed in rev 3861.
