### ISSUE TITLE
[Hunter] - Wind-up for auto-shot now set at 0s

### ISSUE THREAD

**Issue by Godmatik** [Atlantiss/NetherwingBugtracker#8657]
**Current behaviour**:
After fix applied from:
https://github.com/Atlantiss/NetherwingBugtracker/issues/8598

Auto-shot now can be cast instantly after moving once the swing timer is up, there is no wind-up needed whatsoever

**Expected behaviour**: 
The wind-up should be 0.5s by default and reduced by haste, but should not get down to 0s

**Server Revision**: 
3860

**Comment by Wolffenstein** [comment]
https://github.com/Atlantiss/NetherwingBugtracker/issues/8592 this issue claimed that movement shouldn't delay autoshot

**Comment by Godmatik** [comment]
My classic knowledge is basically zero, but the follow-up comments after that issue was closed seems to indicate that it should

I will let others who have more knowledge comment on this ...

![autoshot](https://github.com/Atlantiss/NetherwingBugtracker/assets/37913400/63bfaa0a-0610-413b-865f-0571fe610795)

**Comment by Wolffenstein** [comment]
Fixed in rev 3861.
