### ISSUE TITLE
Verdant Sphere - Adal's Song of Battle

### ISSUE THREAD

**Issue by Godmatik** [Atlantiss/NetherwingBugtracker#8659]
**Current behaviour**:
After turning in Verdant Sphere for quest from killing KT  - RP occurs but no buff is given.

https://www.wowhead.com/tbc/quest=11007/kaelthas-and-the-verdant-sphere

**Expected behaviour**: 
Should provide 2 hour buff to everyone inside Shattrath and TK instances

https://www.wowhead.com/tbc/spell=39953/adals-song-of-battle

Previously reported here - https://github.com/Atlantiss/NetherwingBugtracker/issues/6627

**Server Revision**: 
3860

**Comment by Wolffenstein** [comment]
Fixed in rev 3864.
