### ISSUE TITLE
[Quest] [Mob] [The Tower of Althalaxx (Part 4, Glowing Soul Gem)

### ISSUE THREAD

**Issue by Unfairy** [Atlantiss/NetherwingBugtracker#866]
Dark Strand Cultist and Dark Strand Adept's Imp and Voidwalker not disappearing after death of mobs.
As Imp and Voidwalker not mobs themselfs but summoned creatures they suppsoed to disappear after caster's death. Fair for every mob using Summon ability.
Entry: 3725, 3728.

**Comment by wtRCH** [comment]
Summoned creatures such as Imps and Voidwalkers disappear on evade. Please check and comment in this issue or open new one, if summons don't disappear after evade.
