### ISSUE TITLE
Doom Lord Kazzak - Mark of Kazzak

### ISSUE THREAD

**Issue by Godmatik** [Atlantiss/NetherwingBugtracker#8660]
**Current behaviour**:
When Kazzak is engaged, he will only apply "Mark of Kazzak" debuff repeatedly to one target unless that target goes out of range of him.

**Expected behaviour**: 
Kazzak should apply the debuff to a random target each cast.

https://www.wowhead.com/tbc/spell=32960/mark-of-kazzak

**Server Revision**: 
3860

**Comment by Wolffenstein** [comment]
It's set to SPELL_TARGET_RANDOM_WITH_MANA

**Comment by Godmatik** [comment]
Well did you test it with multiple mana users? He definetly it only using it one person repeatedly

**Comment by Wolffenstein** [comment]
Fixed in rev 4029.
