### ISSUE TITLE
[Hunter] Major Frost Trap Bug

### ISSUE THREAD

**Issue by bluemanguy112** [Atlantiss/NetherwingBugtracker#8661]
**Description**: 
Having multiple Frost Traps triggered only applies a visual with no effect for the 2nd Frost Trap upon re-entering it.

**How to reproduce**:
Use Frost Trap(1)->wait 30sec for Trap CD->Trigger Frost Trap(1)->Use Frost Trap(2)->Trigger Frost Trap(2)->Run out of the effect of Frost Trap(2)->Run back into Frost Trap(2)->No snare

**Expected behaviour**: 
You should be able to have multiple Frost Trap at the same time.

**Comment by Wolffenstein** [comment]
Fixed in rev 3865.
