### ISSUE TITLE
[2.1 PTR] - Mother Shahraz issues after reset

### ISSUE THREAD

**Issue by Godmatik** [Atlantiss/NetherwingBugtracker#8665]
**Current behaviour**:
After Mother Shahraz is reset from dragging her too far (to evade her) - there are problems with combat not resetting for multiple members who didn't die. Next pull this causes aggro to carry over from previous attempt.

**Expected behaviour**: 
Combat should be cleared for all upon reset. 
Perhaps despawn her upon evade?

**Server Revision**: 
3861

**Comment by Wolffenstein** [comment]
Fixed in rev 3864.
