### ISSUE TITLE
[2.1 PTR] - Illidan - Flames of Azzinoth spawn locations

### ISSUE THREAD

**Issue by Godmatik** [Atlantiss/NetherwingBugtracker#8667]
**Current behaviour**:
Flames of Azzinoth spawn locations (phase 2 of Illidan) appear to be a bit too random, sometimes the fire ele can spawn very close to the raid on top of the grating, potentially killing somebody that isn't the tank on spawn

**Expected behaviour**: 
In the several classic videos I have reviewed, the glaives are always very close to the same spot - the fire eles never spawn near the grate.

https://www.youtube.com/watch?v=ZHiqIzEv86Y

**Server Revision**: 
3861

**Comment by Wolffenstein** [comment]
Fixed in rev 3864.
