### ISSUE TITLE
[Netherstorm Quest] Battle-mage Dathric, Abjurist Belmara, Cohlien Frostweaver, Conjurer Luminarth

### ISSUE THREAD

**Issue by Mewmewww** [Atlantiss/NetherwingBugtracker#8668]
[//]: # (Enclose links to things related to the bug using http://wowhead.com or any other TBC database.)
[//]: # (You can use screenshot ingame to visual the issue.)
[//]: # (Write your tickets according to the format:)
[//]: # ([Quest][Azuremyst Isle] Red Snapper - Very Tasty!)
[//]: # ([NPC] Magistrix Erona)
[//]: # ([Spell][Mage] Fireball)
[//]: # ([Npc][Drop] Ghostclaw Lynx)
[//]: # ([Web] Armory doesnt work)
[//]: # (To find server revision type `.server info` command in the game chat.)

**Description**: 
[//]: # ([Quest][Netherstorm] Battle-Mage Dathric
[//]: # ([Quest][Netherstorm] Abjurist Belmara
[//]: # ([Quest][Netherstorm] Cohlien Frostweaver
[//]: # ([Quest][Netherstorm] Conjurer Luminrath

**Current behaviour**:
As you use the items, their ghosts does the RP-dialogue, but the quest doesn't complete in your questlog therefore uncompleteable. 

**Expected behaviour**: 
The RP seems to work, but you just don't get the credit for them when you rightclick their respective items. 

**Server Revision**: 
3862

**Comment by Wolffenstein** [comment]
Fixed in rev 3864.
