### ISSUE TITLE
Shartuul Transporter (Netherwing TBC)

### ISSUE THREAD

**Issue by Mikex840** [Atlantiss/NetherwingBugtracker#8669]
Phase 1:
- Teleporter Shield health is not displayed
- Mighty Whirlwind occasionally cancels itself

Phase 2:
- Gan'arg are falling under the ground and evade bug back to their spawn points. They can tab targeted and killed but do not interact properly with the event.
- Consume Essence deals damage to Gan'arg and the healing number shows on the demon portrait, but the health bar doesn't actually change.

Phase 3a:
- The Gan'arg that were stuck in the ground from Phase 2 do not despawn as intended.
- Cast bars for all abilities (Pyroblast, Shadowbolt, Frostbolt, Shadow Form, Fire Form, Frost Form) are not being displayed.
- Eye of Shartuul is casting Dark Glare much more often than it should.

Phase 3b:
- Dreadmaw move speed is faster than it should be.
- Dreadmaw's emote + charge is not applying a debuff

Phase 3c:
- Shartuul is spawning eye tentacles more often than intended.

General:
- Iceblock is not reflecting spell damage as intended
- Flame Buffet is not increasing the damage of any other spells regardless of how many stacks are applied. The tooltip states it increases fire damage done by 5000 and with 10 stacks applied pyroblast was hitting for 20k - 22k
- Event demons are targetable by other players. Hostiles can be debuffed/CC'd (example: a player can dual-box a warlock to chain fear on dreadmaw to avoid damage or curse of tongues on Shartuul to make iceblocking incinerate far easier) and controlled demons can be buffed (example: priest healing/pain suppression, shaman totems, etc). Not sure if this is intended or not, I never thought of this before.
- Forge Camp Wrath cannon firebombs can hit and deal heavy damage to controlled demons (Opposing factions can grief by using a flying mount and hovering over controlled demon to intentionally aggro the cannons and kill the demon to end the event early)

I have another darkrune ready, if a GM wants to watch me do the event to see the bugs message Mikex840 on discord.

**Comment by Godmatik** [comment]
Biggest issue right now is that the demon you control sometimes does not respawn properly and isn't there - only a GM can respawn it or a server crash/restart fixes it.

**Comment by Healweed** [comment]
Bump

**Comment by Godmatik** [comment]
Closing - consolidating all information into one thread
