### ISSUE TITLE
[Ability] [Class mechanics] Stealth / Prowl on body pull range.

### ISSUE THREAD

**Issue by Unfairy** [Atlantiss/NetherwingBugtracker#867]
Sometimes when you are on the border range of body pull of mob using Prowl (probably fair for stealth also) you pull mob for about a second but as Prowl was already used, mob going evade.
Not sure where this problem come from but you either supposed to engage in combat and not be able to go prowl OR go prowl without pulling mob even for a second.
![prowl evade](https://user-images.githubusercontent.com/41975070/46242885-2c607b80-c3ce-11e8-81c6-45d74066a074.gif)

**Comment by Easyfraggy** [comment]
Duplicate https://github.com/Atlantiss/NetherwingBugtracker/issues/295
