### ISSUE TITLE
[Core][API] specific events are constantly firing when they nominally should not

### ISSUE THREAD

**Issue by fondlez** [Atlantiss/NetherwingBugtracker#8670]
**Description**: 
Some events are firing frequently and consistently when they are not expected to fire at all. This makes them almost unusable as a client API element, e.g. in addons.

Is this a client issue or server-side issue?

**Current behaviour**:
UPDATE_SHAPESHIFT_FORM and CURRENT_SPELL_CAST_CHANGED are constantly firing, e.g. every mana power regen tick for at least as long as a player has current mana less than maximum mana.

Tested on a druid on both Live and PTR.

**Expected behaviour**: 
CURRENT_SPELL_CAST_CHANGED	
Fires when a spell cast starts or stops. Fires 4 times when the spell cast starts. Also remember that some things that you might not think of are considered spell casts. These include item crafting, mining, skinning, ect.

UPDATE_SHAPESHIFT_FORM
Fires whenever your shapeshit event occures [sic].

Source: https://web.archive.org/web/20080607025149/http://wowprogramming.com/docs/events

**Server Revision**: 
Live: 3862

**Comment by Wolffenstein** [comment]
From what I can see in the client. both of these events are triggered by update function, meaning they fire every client update tick. Not a server issue at the very least and likely intended behaviour.
