### ISSUE TITLE
Swapping Weapons While Autoshot Active Bugged

### ISSUE THREAD

**Issue by spacct** [Atlantiss/NetherwingBugtracker#8677]
[//]: # (Enclose links to things related to the bug using http://wowhead.com or any other TBC database.)
[//]: # (You can use screenshot ingame to visual the issue.)
[//]: # (Write your tickets according to the format:)
[//]: # ([Quest][Azuremyst Isle] Red Snapper - Very Tasty!)
[//]: # ([NPC] Magistrix Erona)
[//]: # ([Spell][Mage] Fireball)
[//]: # ([Npc][Drop] Ghostclaw Lynx)
[//]: # ([Web] Armory doesnt work)
[//]: # (To find server revision type `.server info` command in the game chat.)

**Description**: 
Right clicking on a weapon in bags while autoshot is active will not equip it.

**Current behaviour**:
Upon investigation, this occurs due to autoshot being active. Weapons will not equip with /equip macros or via right clicking them in your bags.

Tested while simply auto shot attacking Dr. Boom. You cannot swap weapons with a right click while you are autoshot attacking. You have to deactivate autoshot somehow (via detargeting or using esc key) in order for right-clicking a weapon in inventory to swap.

For whatever reason, de-equipping items while auto shot is active does work, just not the other way around.

**Expected behaviour**: 
When right-clicking a weapon it should be equipped.

**Server Revision**:

**Comment by Wolffenstein** [comment]
Fixed in rev 3879.
