### ISSUE TITLE
Reapplying Hunter's Mark Resets the Attack Power Gain (and shots sometimes do not register the AP gain at all)

### ISSUE THREAD

**Issue by spacct** [Atlantiss/NetherwingBugtracker#8680]
[//]: # (Enclose links to things related to the bug using http://wowhead.com or any other TBC database.)
[//]: # (You can use screenshot ingame to visual the issue.)
[//]: # (Write your tickets according to the format:)
[//]: # ([Quest][Azuremyst Isle] Red Snapper - Very Tasty!)
[//]: # ([NPC] Magistrix Erona)
[//]: # ([Spell][Mage] Fireball)
[//]: # ([Npc][Drop] Ghostclaw Lynx)
[//]: # ([Web] Armory doesnt work)
[//]: # (To find server revision type `.server info` command in the game chat.)

**Description**: 
Hunter's Mark (HM) is dropping all AP gains when it is reapplied rather than refreshing the buff and keeping the AP gains.

Also, if you watch closely, you will see that (at 23-24 seconds left on the HM buff) a shot hits which acts as if the AP gain is with a fresh HM rather than a fully buffed one (10 AP added on every ranged hit to target up to a total of 440). My hypothesis is that this is happening because the ranged hit is not registering the additional AP from the buffed HM.

**Current behaviour**:
(Apologies for the low quality, but this site does not allow gifs above a certain size to be uploaded. I wanted sufficient evidence for both of my above bugs to be encapsulated by a single gif, so I sacrificed color).

![Hunter's Mark Dropping AP Randomly and at Reapplication](https://github.com/Atlantiss/NetherwingBugtracker/assets/104590778/7c65be08-185d-461d-81da-96a4a13f9969)

**Expected behaviour**: 
Hunter's Mark should retain all of the AP gains when it is refreshed rather than resetting it back from 0. Also, it should never lose the additional ranged AP gained rather than randomly losing that additional attack power.

**Server Revision**:

**Comment by Wolffenstein** [comment]
Fixed in rev 3867.
