### ISSUE TITLE
[Hyjal] Archimonde - Delayed "Finger of Death" casts

### ISSUE THREAD

**Issue by Godmatik** [Atlantiss/NetherwingBugtracker#8681]
**Current behaviour**:
Archimonde will occasionally have delayed casts on his Finger of Death ability when his primary threat target is out of range. This typically seems to happen after he cast an ability just previously (like fear, curse, air burst etc)

In the clip below, you can see this interaction twice. The main tank (Niyeev) was knocked back by an airburst from someone too close to him, Archimonde did not cast on him for several seconds. 

Then a hunter - Xeike - took aggro 12 seconds into the clip - but Archimonde did nothing to him for ~15 seconds until he finally killed him with Finger of Death

https://clips.twitch.tv/SmilingPhilanthropicPancakeBlargNaut-3i0CT9CVYn76fDkb

**Expected behaviour**: 
If the primary threat target is out of range  - he should immediately finger of death them constantly.

https://www.wowhead.com/tbc/spell=32111/finger-of-death

**Server Revision**: 
3866

**Comment by Wolffenstein** [comment]
Fixed in rev 3867.
