### ISSUE TITLE
Warden whitelist for wowchat

### ISSUE THREAD

**Issue by Minnona** [Atlantiss/NetherwingBugtracker#8682]
[//]: # (Enclose links to things related to the bug using http://wowhead.com or any other TBC database.)
[//]: # (You can use screenshot ingame to visual the issue.)
[//]: # (Write your tickets according to the format:)
[//]: # ([Quest][Azuremyst Isle] Red Snapper - Very Tasty!)
[//]: # ([NPC] Magistrix Erona)
[//]: # ([Spell][Mage] Fireball)
[//]: # ([Npc][Drop] Ghostclaw Lynx)
[//]: # ([Web] Armory doesnt work)
[//]: # (To find server revision type `.server info` command in the game chat.)

**Description**: 
Hey, currently [wowchat](https://github.com/fjaros/wowchat) connection gets refused if the platform set to Mac. Switching it to Windows makes Warden block it and eventually disconnect the bot.
Wowchat is a great tool and it would've been nice if you guys could whitelist it. Thanks!

More info: https://github.com/fjaros/wowchat/issues/94

**Comment by Godmatik** [comment]
Send DM to Crysis, he can whitelist it for you
