### ISSUE TITLE
Spell Hit and mechanic Resistance

### ISSUE THREAD

**Issue by ewj69** [Atlantiss/NetherwingBugtracker#8683]
**Current behaviour**: Resistance to certain mechanics (Fear, Silence,..) can be negated by excessive Spell Hit. As a side effect, this also leads to less flexibility in talent builds.

**Expected behaviour**: https://us.forums.blizzard.com/en/wow/t/all-talents-that-reduce-spell-resists-in-pvp-no-longer-works-since-phase-2/1114096/5
> - Excess spell hit can no longer be used to cancel out the effects of talents that resist certain mechanics, such as Unbreakable Will.
>   - This rule was introduced in patch 2.4.0 of original Burning Crusade, and we’ve based all other underlying game mechanics and formulas on patch 2.4.3.

**Server Revision**: 3866

**Comment by Wolffenstein** [comment]
will not be changed
