### ISSUE TITLE
Warsong Gulch time limit (suggestion for improvement)

### ISSUE THREAD

**Issue by ewj69** [Atlantiss/NetherwingBugtracker#8684]
**Current behaviour**: WSG matches are limited in duration to 22 minutes. This frankly does nothing to improve the WSG experience (arguably the opposite). Below, in the comment, you can see the PvP Manager's reasoning for why this change was implemented.

**Suggested solution**: Get rid of the custom time limit and the Honor gained from kills. Increase Honor gain from completing battleground objectives.

(Patch 2.4.0) Warsong Gulch: When both flags are held, the flag carriers will receive 50% increased damage done to them after approximately 10 minutes and 100% increased damage after approximately 15 minutes. [also limits movement speed to 100%]

Focused/Brutal Assault timers can also be decreased if necessary.

(edit) Also removing Badges of Justice and the other non-pvp rewards from the daily quest "A Call to Battle" would help reduce the amount of AFK players as they'd have no incentive to join and leech/stay afk.

**Server Revision**: 3866

**Comment by Wolffenstein** [comment]
Up to tsu. I'm not changing it without his agreement
