### ISSUE TITLE
Hunter deadzone and racial swap

### ISSUE THREAD

**Issue by ewj69** [Atlantiss/NetherwingBugtracker#8685]
Racial Swap creates a small deadzone for hunters where they can neither shoot or melee. Frequently occurs while "melee-weaving". Observed as a Night Elf male with Orc racials. I haven't tested other combinations.

**Server Revision**: 3866

**Comment by Wolffenstein** [comment]
need video

**Comment by Wolffenstein** [comment]
https://github.com/Atlantiss/NetherwingBugtracker/assets/1576644/f19c58f8-7558-4fab-a650-fd53bb81d5a6

Since you're not willing to be serious and provide an actual video to showcase the issue (since I can't reproduce it) im closing it
