### ISSUE TITLE
Feign Death Bugs and Wont Start 30 Second CD Making it Unusable

### ISSUE THREAD

**Issue by spacct** [Atlantiss/NetherwingBugtracker#8687]
[//]: # (Enclose links to things related to the bug using http://wowhead.com or any other TBC database.)
[//]: # (You can use screenshot ingame to visual the issue.)
[//]: # (Write your tickets according to the format:)
[//]: # ([Quest][Azuremyst Isle] Red Snapper - Very Tasty!)
[//]: # ([NPC] Magistrix Erona)
[//]: # ([Spell][Mage] Fireball)
[//]: # ([Npc][Drop] Ghostclaw Lynx)
[//]: # ([Web] Armory doesnt work)
[//]: # (To find server revision type `.server info` command in the game chat.)

**Description**: 
Sometimes Feign Death will lock up and will not begin its 30 second CD on use. This prevents it from being used for entire boss fights.

**Current behaviour**:
See Feign Death bugged out following boss fight. It was bugged out after first use and wasnt able to be used again during the entire boss fight. Now, after leaving combat entirely, it still cannot be used.
![Feign Death CD Not Ticking - FD Unusable](https://github.com/Atlantiss/NetherwingBugtracker/assets/104590778/1797e507-9f3c-4280-aed4-4024661622cc)

**Expected behaviour**: 
Feign Death should always begin its 30 second cooldown when used so that it can be used again after 30 seconds.

**Server Revision**:

**Comment by Godmatik** [comment]
Have heard of this bug before but never personally experienced it, heard it was very rare. EDIT: person it happened to also it occurred during Teron fight, dunno if coincidence.

I have only seen a bug where sometimes feign death is used and actually worked, but visually doesn't show the 30 sec cooldown, typically if you use it in middle of steady shot macro. Possibly related.

**Comment by spacct** [comment]
This bug is not fight specific. It is also not triggered by steady shot macro.

**Comment by Godmatik** [comment]
During Teron fight today - I attempted to use feign death and was unable to while the constructs were alive, then was able to use it after they died. Possibly related (or maybe a separate issue)

**Comment by Godmatik** [comment]
Testing again - I can confirm Feign death is having some occasional issues on Teron fight - I suspect some odd interactions with the constructs when they are spawned.

Can not reproduce on any other fight.

**Comment by Wolffenstein** [comment]
Should be fixed
