### ISSUE TITLE
Elite quest bugged in Hellfire Peninsula

### ISSUE THREAD

**Issue by spinzw** [Atlantiss/NetherwingBugtracker#8688]
[//]: # (Enclose links to things related to the bug using http://wowhead.com or any other TBC database.)
[//]: # (You can use screenshot ingame to visual the issue.)
[//]: # (Write your tickets according to the format:)
[//]: # ([Quest][Azuremyst Isle] Red Snapper - Very Tasty!)
[//]: # ([NPC] Magistrix Erona)
[//]: # ([Spell][Mage] Fireball)
[//]: # ([Npc][Drop] Ghostclaw Lynx)
[//]: # ([Web] Armory doesnt work)
[//]: # (To find server revision type `.server info` command in the game chat.)

**Description**: 
The quest " Natural Remedies " https://www.wowhead.com/tbc/quest=10351/natural-remedies  is 100% bugged , i just saw between 10 to 15 players trying to summon the boss , all by pressing the item ( the seed ) that summons the blood elf that talk , and then , the giant is supposed to spawn , but he never does arrive .
**Current behaviour**:
We use the seed ( that has only 1 charge ) the charge is used , the blood elf appears , talks , and then nothing .
**Expected behaviour**: 
We use the seed , the charge is used , the blood elf appears , talks , and then the elite appears .
**Server Revision**:

**Comment by Godmatik** [comment]
Works fine - just saw a group summon it with no issues

![WoWScrnShot_091323_094614](https://github.com/Atlantiss/NetherwingBugtracker/assets/37913400/a5fd12a4-9053-47e3-b621-d608124a960c)

**Comment by spinzw** [comment]
well , glad it's fixed cause i can assure you , few hours ago , there was groups of people waiting , all trying their seed ,  and no one was getting any boss . at least 10 to 15 people . i'm gonna go test it again see if it works :)

**Comment by spinzw** [comment]
it is happening again . come back and look right now if u wanna see   3 players of this huge horde group tried to summon the boss with the seed , same thing happened that i described earlier.

the boss never appeared . now everyone is here waiting 


![zefzf](https://github.com/Atlantiss/NetherwingBugtracker/assets/137619538/62feef79-3130-49cd-85d8-705be88890bd)

**Comment by spinzw** [comment]
![fzefezf](https://github.com/Atlantiss/NetherwingBugtracker/assets/137619538/2d2f4d5c-dabe-4a1b-ba44-9fe8211fced5)
( when i say a lot of players , i mean , look . everyone is stacking here because the quest bugs ) the exact same thing happened 4 hours ago , 15 players were stacked here aswell with the quest not working .

**Comment by spinzw** [comment]
And now it is working again randomly .
