### ISSUE TITLE
[Item]Some weapons with only +healing ("healing done by spells and effects") provide a damage bonus

### ISSUE THREAD

**Issue by fondlez** [Atlantiss/NetherwingBugtracker#8689]
**Description**: some healing weapons in the current patch are providing a damage bonus.

**Current behaviour**:
[[Lightfathom Scepter]](https://www.wowhead.com/tbc/item=30108/lightfathom-scepter)
[[Gladiator's Salvation]](https://www.wowhead.com/tbc/item=32451/gladiators-salvation)
[[Vengeful Gladiator's Salvation]](https://www.wowhead.com/tbc/item=33743/vengeful-gladiators-salvation)
[[Light's Justice]](https://www.wowhead.com/tbc/item=28771/lights-justice)
[[Shard of the Virtuous]](https://www.wowhead.com/tbc/item=28522/shard-of-the-virtuous)
[[Hand of Eternity]](https://www.wowhead.com/tbc/item=23556/hand-of-eternity)

all provide a damage bonus (40% of the +healing).

Tested on PTR.

**Expected behaviour**: before content patch 2.3, +healing should provide no damage bonus. After content patch 2.3, there is a damage bonus of approximately 1/3 of the +healing.

**Server Revision**: 
PTR: 3866

**Comment by fondlez** [comment]
I do not know if healing enchants are meant to provide a damage bonus or not, even if the text show as such. However, after testing the Glyph of Renewal and Golden Spellthread, the head enchant does not provide a damage bonus, while the leg enchant does. They both use the same text format/style of description for the bonuses, so this is confusing while one provides a damage bonus but the other does not.

**Comment by gun4axb** [comment]
![image](https://github.com/Atlantiss/NetherwingBugtracker/assets/97943252/6ef2d3b7-a9dc-4942-83cb-feaccc1a8afb)

https://wowwiki-archive.fandom.com/wiki/Patch_2.3.0#General

![image](https://github.com/Atlantiss/NetherwingBugtracker/assets/97943252/deace092-a6a6-46af-9395-1d37292b9cb7)
![image](https://github.com/Atlantiss/NetherwingBugtracker/assets/97943252/7128c31f-cc34-4cfd-b472-b4b3607ff5a9)
![image](https://github.com/Atlantiss/NetherwingBugtracker/assets/97943252/40ece864-6369-4448-94b0-47c58fabfda7)
![image](https://github.com/Atlantiss/NetherwingBugtracker/assets/97943252/84cc0dd4-1724-4fca-945d-60502ad20622)
![image](https://github.com/Atlantiss/NetherwingBugtracker/assets/97943252/92d43230-3ede-4111-9cac-ccd7291eb885)


-------------------------------------------------------------------------


![image](https://github.com/Atlantiss/NetherwingBugtracker/assets/97943252/cf07dad2-8bb8-46f1-a50c-a2b4913d6a03)
![image](https://github.com/Atlantiss/NetherwingBugtracker/assets/97943252/aec0eebb-9bb5-4859-b6af-0f3bb6d38871)
![image](https://github.com/Atlantiss/NetherwingBugtracker/assets/97943252/33bb2bfb-b31d-4197-b0e2-a4cdff00dc4f)
![image](https://github.com/Atlantiss/NetherwingBugtracker/assets/97943252/f4e7ab34-92b9-4557-97fb-cae148ff8f44)

Should also change tooltips for non-weapon items.

**Comment by Wolffenstein** [comment]
Fixed in rev 3879.
