### ISSUE TITLE
After the today`s reset,plateau is bugging,the zone with water elementals.For example,you can see the pure water,but when i try to get close to it,it dissapears.Like its layered or something.Help plz,thanks!

### ISSUE THREAD

**Issue by bul021** [Atlantiss/NetherwingBugtracker#8690]
[//]: # (Enclose links to things related to the bug using http://wowhead.com or any other TBC database.)
[//]: # (You can use screenshot ingame to visual the issue.)
[//]: # (Write your tickets according to the format:)
[//]: # ([Quest][Azuremyst Isle] Red Snapper - Very Tasty!)
[//]: # ([NPC] Magistrix Erona)
[//]: # ([Spell][Mage] Fireball)
[//]: # ([Npc][Drop] Ghostclaw Lynx)
[//]: # ([Web] Armory doesnt work)
[//]: # (To find server revision type `.server info` command in the game chat.)

**Description**: 

**Current behaviour**:

**Expected behaviour**: 

**Server Revision**:

**Comment by Godmatik** [comment]
Issue is with new instance border

**Comment by Godmatik** [comment]
its fixed now
