### ISSUE TITLE
BT - Reliquary of Souls - Emotes

### ISSUE THREAD

**Issue by Godmatik** [Atlantiss/NetherwingBugtracker#8693]
**Essence of Suffering** - uses wrong emote when using Enrage spell.
Currently says "Essence of Suffering goes into a Frenzy!"
Should instead say "Essence of Suffering becomes enraged!"
https://www.youtube.com/watch?v=aJiqaFUQ1qs&t=65s

**Essence of Anger** - missing emote when he casts Seethe ability, also looks like a small animation he does is also missing
Should say "Essence of Anger seethes in anger!"

https://www.youtube.com/watch?v=aJiqaFUQ1qs&t=270s

**Comment by Wolffenstein** [comment]
Fixed in rev 3868.
