### ISSUE TITLE
BT - Mother Shahraz - Enrage emote missing

### ISSUE THREAD

**Issue by Godmatik** [Atlantiss/NetherwingBugtracker#8694]
**Current behaviour**:
At 10% health, Mother Shahraz does her weird soft enrage that doesn't have a buff icon (intended) - however she is not using an emote when she should.

**Expected behaviour**: 
There should be an emote:
"Mother Shahraz becomes enraged!"

https://www.youtube.com/watch?v=N7brMZWEN0o&t=229s

**Server Revision**: 
3867

**Comment by Wolffenstein** [comment]
Fixed in rev 3868.
