### ISSUE TITLE
BT - Gathios the Shatterer - Mana

### ISSUE THREAD

**Issue by Godmatik** [Atlantiss/NetherwingBugtracker#8695]
**Current behaviour**:
Gaithos the Shatter - even with the buffed mana pool, still tends to run out of mana for his abilities after about 8 minutes into the fight.

**Expected behaviour**: 
Watching classic videos - he actually shouldn't use mana for his spells at all. Also none of the other three council members use mana for their abilities. But regardless, if you want to keep it as is, just buff his mana again up to 2 million, that way he won't go OOM before enrage.

https://www.youtube.com/watch?v=5CgZFHonpGU

**Server Revision**: 
3867

**Comment by Wolffenstein** [comment]
Fixed in rev 3868.
