### ISSUE TITLE
BT - Illidan fight - Missing a few yells

### ISSUE THREAD

**Issue by Godmatik** [Atlantiss/NetherwingBugtracker#8696]
When Illidan uses his soft enrage (final phase), he is not using his yell:
"Feel the hatred of ten thousand years!""
https://www.wowhead.com/tbc/sound=11470/a-blcktmple-illidan-08

When Illidan uses his hard enrage (after 15 mins), he is not using his yell:
"You've wasted too much time mortals, now you shall fall!"
https://www.wowhead.com/tbc/sound=11474/a-blcktmple-illidan-12

When Maiev drops a trap, she is missing her yell:
"There shall be no prison for you this time!"
https://www.wowhead.com/tbc/sound=11495/a-blcktmple-maiev-05

**Server Revision**: 
3867

**Comment by Wolffenstein** [comment]
Are you sure those aren't just unused voice lines from the game files?

**Comment by Wolffenstein** [comment]
![image](https://github.com/Atlantiss/NetherwingBugtracker/assets/1576644/afa86cb5-3b7e-43ea-b352-9adef3da3884)

**Comment by Wolffenstein** [comment]
Fixed in rev 3868.
