### ISSUE TITLE
[Spell] [Druid] Regrowth Downrank buff override

### ISSUE THREAD

**Issue by elliotmendiola** [Atlantiss/NetherwingBugtracker#8697]
**Description**: 
Regrowth is not properly maintaining the stronger version of the heal over time effect.  This makes it harder for resto druids to heal tanks in times of intense damage as a common strategy for tank healing was to maintain max rank regrowth heal over time effect and spam lower rank regrowth to conserve mana while getting a lot of healing in, then following up with a swiftmend at the end of the regrowth duration.

**Current behaviour**:
Regrowth rank 9 overrides max rank regrowth heal over time effect

**Expected behaviour**: 
Regrowth rank 10 heal over time effect should stay on the target without refreshing duration
Regrowth rank 9 instant heal effect should still be applied

**Server Revision**: 
3867

**Comment by elliotmendiola** [comment]
Yeah both of those links verify this

It is currently not working properly on netherwing.

**Comment by Wolffenstein** [comment]
Fixed in rev 3875.
