### ISSUE TITLE
[Quest][Wetlands] Uncovering the Past (Gorm Fragment)

### ISSUE THREAD

**Issue by Healweed** [Atlantiss/NetherwingBugtracker#8698]
**Description**: 
Currently there's only 3 out of 4 objects that are able to be looted. 4th one. 
The 4th one is Gorm Fragment which is lootable from a vase and currently it's not respawning. All other fragments are avaliable to be lootable which is fine.

**Current behaviour**:
Interactable Object that contains Gorm Fragment doesn't respawn

**Expected behaviour**: 
Should spawn

**Server Revision**: 
3867

**Comment by Godmatik** [comment]
Never had an issue with this quest with the alts I did it with - each relic has multiple spawn points, check the area up above next to the named Raptor (Sarltooth?) and the cliffs below that

**Comment by Healweed** [comment]
> Never had an issue with this quest with the alts I did it with - each relic has multiple spawn points, check the area up above next to the named Raptor (Sarltooth?) and the cliffs below that

The object is missing from it's respawn place. Has been for over 30min. The other 3 objects are working fiine

**Comment by Godmatik** [comment]
There are multiple places it can spawn is what I am saying, not just one

**Comment by Godmatik** [comment]
Not sure which fragment you looking for specifically, but I found them both.

Issue can be closed

![vase2](https://github.com/Atlantiss/NetherwingBugtracker/assets/37913400/563c9dd4-4415-48bd-ae39-03c1ceca9f24)
![vase](https://github.com/Atlantiss/NetherwingBugtracker/assets/37913400/ad0336dd-d4cf-43c2-9504-0048af9051fc)
