### ISSUE TITLE
[NPC] Zanzil Zombie

### ISSUE THREAD

**Issue by mbzz88** [Atlantiss/NetherwingBugtracker#870]
**Description**: Mob has an incorrect version of spell.

**Current behaviour**: Mob has both https://www.wowhead.com/spell=7102/contagion-of-rot and https://www.wowhead.com/spell=56707/contagion-of-rot
(they stack too ;( ) (also may have gotten this wrong, and that the spreading version is the 2nd one, but I don't think so)
![wowscrnshot_092918_194553](https://user-images.githubusercontent.com/43509267/46242837-80488000-c421-11e8-8136-6863d3811c43.jpg)
![wowscrnshot_092918_194554](https://user-images.githubusercontent.com/43509267/46242839-8179ad00-c421-11e8-8df4-3ddcc867ab32.jpg)

**Expected behaviour**: Only this version https://www.wowhead.com/spell=7102/contagion-of-rot

**Comment by The14me** [comment]
try to reproduce but nothing happen,only  7102 was on me.

**Comment by mbzz88** [comment]
Hmm so I went back to try to reproduce this, the original source is definitely 7102, but after standing next to my pet while it's getting hit for 20 minutes resulted in 0 procs from the spread, so if the spell that is spread to allies on hit is also 7102, then this may just be a UI error.
But my attack speed with both buffs was slower than just with the single buff, so I dunno.

**Comment by The14me** [comment]
Work just fine now.
