### ISSUE TITLE
BT - Dragonmaw Sky Stalker

### ISSUE THREAD

**Issue by Godmatik** [Atlantiss/NetherwingBugtracker#8701]
**Current behaviour**:
Dragonmaw Sky Stalker - trash mob in BT - deals only 1 damage with Immolation ability

**Expected behaviour**: 
Should deal more than 1 damage

![Immolation](https://github.com/Atlantiss/NetherwingBugtracker/assets/37913400/8bb6a446-43e6-414d-9c68-01e45087abdb)

https://www.wowhead.com/tbc/npc=23030/dragonmaw-sky-stalker#abilities;mode:n25

**Server Revision**: 
3869

**Comment by Wolffenstein** [comment]
Fixed in rev 3879.
