### ISSUE TITLE
BT - Teron Gorefiend - Loot can occasionally not drop

### ISSUE THREAD

**Issue by Godmatik** [Atlantiss/NetherwingBugtracker#8702]
**Current behaviour**:
When you defeat Teron Gorefiend - there is a very rare chance that he drops no loot.

This seems to occur if a ghost you are controlling gets the final hit.

**Expected behaviour**: 
Should always drop loot

**Server Revision**:
3869

**Comment by Wolffenstein** [comment]
Fixed in rev 3879.
