### ISSUE TITLE
BT - Mother Shahraz - Saber Lash

### ISSUE THREAD

**Issue by Godmatik** [Atlantiss/NetherwingBugtracker#8703]
**Current behaviour**:
Mother Shahraz appears to be using Saber Lash way too infrequently, every 30-60 seconds

**Expected behaviour**: 
In reviewing logs from classic, it should be every 8-10 secs or so

![cleave](https://github.com/Atlantiss/NetherwingBugtracker/assets/37913400/b03fc359-eac4-4058-8ce1-3519a24187a8)

![saberlash2](https://github.com/Atlantiss/NetherwingBugtracker/assets/37913400/9f8fc8de-cac9-49dc-badb-ca5c49fd02b4)

**Server Revision**: 
3869

**Comment by Wolffenstein** [comment]
It's an 85% proc chance when dealing melee damage through either a melee swing or a melee ability (with 5s icd). If you dodge every attack it will simply not proc
