### ISSUE TITLE
BT - Mother Shahraz - Saber Lash follow-up

### ISSUE THREAD

**Issue by Godmatik** [Atlantiss/NetherwingBugtracker#8704]
**Current behaviour**:
Following up on https://github.com/Atlantiss/NetherwingBugtracker/issues/8703

It looks like as you explained it - currently if the tank Mother is attacking does a dodge/miss/etc on the Saber Lash cast - then it does not get cast at all on anyone in front of her. EDIT: Looks like a blocked attack also prevents it

**Expected behaviour**: 
According to classic logs - even if the main tank does not get hit by Saber Lash, it should still proc and get used on the off-tanks or whoever is standing in front of Mother. Then they get a chance to avoid or take the hit as well.

See the below two logs of Saber Lash damage taken events - both are tanks doing the fight at the same time (the time stamps match). First one is from Feral druid named "Pahs" who is main tanking her, and the second one is from "Starhammer" who is off-tank and standing in front of the boss. 

When "Pahs" dodges the Saber Lash, it still goes through and attempts to hit whoever else is in front of her with the cleave.

![SaberLash](https://github.com/Atlantiss/NetherwingBugtracker/assets/37913400/38e50d34-1144-4552-9fbf-dc2d985015e2)

![SaberLash2](https://github.com/Atlantiss/NetherwingBugtracker/assets/37913400/7e4cc79c-d9a4-48f9-8b5f-89281a248eb7)

**Comment by elliotmendiola** [comment]
I played both in classic and retail tbc.  As far as I can remember this is a difference between classic and original release.  We had a bear tank with 100% dodge tank mother, and we had 2 holy priests be the other "tanks"

This was because they would not get ported anymore and could spam heals when people did

**Comment by Godmatik** [comment]
I'll research a bit more, but this sounds seriously sus. Never seen that tactic in any old video nor even heard of it. Also - you can not have 100% dodge as that stat has diminishing returns. 

And if such a thing did even exist it sounds more like a temporary bug and the classic version is more accurate (since it bases abilities off the 2.4.3 client)

**Comment by Wolffenstein** [comment]
Fixed in rev 3879.
