### ISSUE TITLE
Troll racial Berserking

### ISSUE THREAD

**Issue by ghost** [Atlantiss/NetherwingBugtracker#8706]
.

**Comment by Godmatik** [comment]
![randomvalue](https://github.com/Atlantiss/NetherwingBugtracker/assets/37913400/1efb6533-b375-411e-a41e-ec2cc192c260)

The above ^ was a report about it in a previously closed github thread from last server

I can't find any evidence of what this "random value" is - or why that is intended.

**Comment by Wolffenstein** [comment]
Fixed in rev 3873.
