### ISSUE TITLE
Rocket Boots Xtreme cloth version

### ISSUE THREAD

**Issue by ewj69** [Atlantiss/NetherwingBugtracker#8708]
Blizz screwed clothie engineers back then, you don't have to make the same mistake. I don't see a reason to keep them out until the last patch, nor adding them having any negative impact on the game.

Patch 2.4.0
A new recipe has been added for Rocket Boots Xtreme Lite, a cloth version of the Rocket Boots Xtreme. This pattern drops from Mechano-Lord Capacitus.

**Comment by Wolffenstein** [comment]
Will be added in rev 3871.
