### ISSUE TITLE
Archimonde respawn timer

### ISSUE THREAD

**Issue by Godmatik** [Atlantiss/NetherwingBugtracker#8709]
**Current behaviour**:
When Archimonde despawns (from wipe) - it takes him 5 minutes to respawn

**Expected behaviour**: 
Should take 30 seconds

Can see it in this meme video
https://www.youtube.com/watch?v=o2thG7neNkI&t=105s

**Server Revision**: 
3869

**Comment by Wolffenstein** [comment]
![image](https://github.com/Atlantiss/NetherwingBugtracker/assets/1576644/5651018c-57e0-49d1-a73b-960a7b1178dc)
![image](https://github.com/Atlantiss/NetherwingBugtracker/assets/1576644/baea8b25-152f-4b6b-a677-2ddb55672fbb)
It's at least 2 minutes in the video you've shown and I specifically set it to 5 minutes when I scripted it for a reason (I probably tested it on retail myself). Intended.
