### ISSUE TITLE
[Warrior Quest] Cyclonian

### ISSUE THREAD

**Issue by Azalen** [Atlantiss/NetherwingBugtracker#871]
**Description**: 
https://web.archive.org/web/20071102082228/http://wow.allakhazam.com:80/db/quest.html?wquest=1712
https://classicdb.ch/?quest=1712

**Current behaviour**:
Droprate of the Tusks seems to low. Sadly I don't know how to proof this since it is a quest item and thus never shows correctly on any database. But since Database shows 11% on ALL drops (not only for people on the quest) I'd suggest a droprate of at least 25% if not more.

More input is welcome. Took me ~3h to farm them all for the quest and this seems very heavy.

**Server Revision**: 
[2083]

**Comment by aresbrutus** [comment]
Fixed in one of the upcoming updates.
