### ISSUE TITLE
Hunter - Haste effect on auto-shot

### ISSUE THREAD

**Issue by Godmatik** [Atlantiss/NetherwingBugtracker#8710]
**Current behaviour**:
When you gain any haste effect - your auto-shot speed as Hunter is updated immediately, So if you were halfway to next auto-shot and something like DST procs, that auto-shot timer will be sped up to the new haste value for the final half right away.

**Expected behaviour**:
Haste values should be applied on the next auto-shot, not the current one

https://www.youtube.com/watch?v=BT270SIJtLY&t=55s

Quick Shots procs - no change in auto-shot speed, updates to newest speed in following auto-shot

https://www.youtube.com/watch?v=1sGyzdNE0PI&t=405s

Classic video showing same behavior

**Server Revision**: 
3869

**Comment by Wolffenstein** [comment]
Fixed in rev 3874.
