### ISSUE TITLE
[Core] Mob fanning behavior

### ISSUE THREAD

**Issue by ashido96** [Atlantiss/NetherwingBugtracker#8713]
[//]: # (Enclose links to things related to the bug using http://wowhead.com or any other TBC database.)
[//]: # (You can use screenshot ingame to visual the issue.)
[//]: # (Write your tickets according to the format:)
[//]: # ([Quest][Azuremyst Isle] Red Snapper - Very Tasty!)
[//]: # ([NPC] Magistrix Erona)
[//]: # ([Spell][Mage] Fireball)
[//]: # ([Npc][Drop] Ghostclaw Lynx)
[//]: # ([Web] Armory doesnt work)
[//]: # (To find server revision type `.server info` command in the game chat.)

**Description**: 
When mobs are unable to find a location in the normal fan curve around a player they will instead stand inside the players hitbox and always hit them from behind. 

This also happens with the normal add tanking location for A'Lar flinging your add tank across the room sometimes. (second screenshot to be added during next raid week). 

**Current behaviour**:
Mobs standing inside players hitbox and attack them from behind when a player stands in a corner. 

**Expected behaviour**: 
Mobs should not move to inside the players hitbox and attack them from the back when the mob's spot on the normal fan curve is blocked by terrain. 

**Server Revision**: 
3869

![mob fanning bug report](https://github.com/Atlantiss/NetherwingBugtracker/assets/2313143/1ee9d96b-e0af-43bd-9f57-7610c6bee56d)

**Comment by Godmatik** [comment]
Confirmed, more info here:

https://github.com/Atlantiss/NetherwingBugtracker/issues/8207
https://github.com/Atlantiss/NetherwingBugtracker/issues/5468

**Comment by Wolffenstein** [comment]
Fixed in rev 3879.
