### ISSUE TITLE
BT - Illidan - sometimes a bit unresponsive in movement

### ISSUE THREAD

**Issue by Godmatik** [Atlantiss/NetherwingBugtracker#8714]
**Current behaviour**:
After Illidan uses shear ability or flame crash, he stands in place for several seconds at times and does no action.

This makes it more difficult to readjust his position since he will not follow the tank while he does so. Especially detrimental for trying to move him into traps.

**Expected behaviour**: 
Should be able to move immediately after these abilities are cast and follow the tank if he moves out if melee range

**Comment by Wolffenstein** [comment]
Can't reproduce, he moves normally for me.

**Comment by Godmatik** [comment]
It definetly occurs, possibly when he is queueing one ability into the other.

I'll work on finding a VOD
