### ISSUE TITLE
BT - Illidan - small visual issue

### ISSUE THREAD

**Issue by Godmatik** [Atlantiss/NetherwingBugtracker#8715]
**Current behaviour**:
If Illidan is in demon form, and is pushed to 30% for transition (maiev/shadow prison RP), he will come out of it in human form but will not be wearing his glaives, so he will be slapping the tank with his hands.

**Expected behaviour**: 
Should attack with his glaives and not look so ridiculous

**Comment by Wolffenstein** [comment]
Fixed in rev 3879.
