### ISSUE TITLE
Archimonde - No action while target is mid-air

### ISSUE THREAD

**Issue by Godmatik** [Atlantiss/NetherwingBugtracker#8717]
**Current behaviour**:
If the primary threat target (tank) is mid-air due to airburst - Archimonde does no action until he lands (he stands in place for several seconds)

https://clips.twitch.tv/TangentialDeterminedShieldKeyboardCat-XwSqIa-HxNBpnF6L

**Expected behaviour**: 
He should still use Finger of Death is someone is out of range, even if its vertical range

**Server Revision**: 
3877

**Comment by Wolffenstein** [comment]
It already checks 3d distance

**Comment by Godmatik** [comment]
But you saw in the clip Archi is doing no action for several seconds after someone close to tank air bursted him? He only spammed finger of death as soon as tank landed
