### ISSUE TITLE
Illidan - Flame of Azzinoth - Missing enrage

### ISSUE THREAD

**Issue by Godmatik** [Atlantiss/NetherwingBugtracker#8718]
**Current behaviour**:
If a Flame of Azzinoth charges someone (like the other tank in the below clip) who is more than 25 yards away - it is not enraging

https://clips.twitch.tv/ReliableDelightfulCrabsMoreCowbell-Icvo1IP8O8__UEQS

**Expected behaviour**: 
If a Fire Ele charges someone, it should go enrage

![Enrage](https://github.com/Atlantiss/NetherwingBugtracker/assets/37913400/4859169b-4d08-430c-9731-ff60714b2b1c)

**Server Revision**: 
3877

**Comment by Wolffenstein** [comment]
Fixed in rev 3879.
