### ISSUE TITLE
Elixir of Dream Vision Not Usable with Summoned Creatures

### ISSUE THREAD

**Issue by spacct** [Atlantiss/NetherwingBugtracker#8719]
[//]: # (Enclose links to things related to the bug using http://wowhead.com or any other TBC database.)
[//]: # (You can use screenshot ingame to visual the issue.)
[//]: # (Write your tickets according to the format:)
[//]: # ([Quest][Azuremyst Isle] Red Snapper - Very Tasty!)
[//]: # ([NPC] Magistrix Erona)
[//]: # ([Spell][Mage] Fireball)
[//]: # ([Npc][Drop] Ghostclaw Lynx)
[//]: # ([Web] Armory doesnt work)
[//]: # (To find server revision type `.server info` command in the game chat.)

**Description**: 
Elixir of Dream Vision is not currently usable with summoned creatures. 

**Current behaviour**:
When attempting to use Elixir of Dream Vision with a summoned creature, you get the error message "you already control a summoned creature"

**Expected behaviour**: 
In vanilla, tbc and wotlk (as well as wow classic, tbc classic and wotlk classic) using this elixir with a summoned creature would dismiss the creature on use (see youtube link below for an og wotlk clip)

https://www.youtube.com/watch?v=-OsDZE7Utv8

**Server Revision**:

**Comment by Wolffenstein** [comment]
Fixed in rev 3879.
