### ISSUE TITLE
Faction rep (Booty Bay/Bloodsail Buccaneers)

### ISSUE THREAD

**Issue by mbzz88** [Atlantiss/NetherwingBugtracker#872]
**Description**: Bloodsail mobs in STV do not give goblin rep

**Current behaviour**: These mobs do not give Booty Bay (and other goblin factions) reputation. eg. https://www.wowhead.com/npc=1561/bloodsail-raider should give 5 rep (until honored), killing it only decreases Bloodsail Buccaneers rep.

**Expected behaviour**: Increase goblin faction rep on killing mobs https://www.wowhead.com/faction=21/booty-bay

**Comment by Jezofine** [comment]
Not sure about Thottbot accuracey, but it shows only +Booty Bay rep:
[Bloodsail Swashbuckler](http://web.archive.org/web/20100812060504/http://thottbot.com:80/c1563)
[Bloodsail Raider](http://web.archive.org/web/20100814031143/http://thottbot.com:80/c1561)

**Comment by Evolvee** [comment]
https://wowwiki.fandom.com/wiki/Mobs_which_affect_reputation_with_Steamwheedle_Cartel

> If somebody completes a quest or **gets any reputation points from one member**, they will receive 50% of the reputation points towards the other three members also!

**Comment by Wolffenstein** [comment]
They do give reputation, but only up to neutral. Wowwiki says they should until Friendly.

**Comment by Wolffenstein** [comment]
Fixed in rev 3369.
