### ISSUE TITLE
Feign Death Resist Chance on Boss Fights Far Above Normal

### ISSUE THREAD

**Issue by spacct** [Atlantiss/NetherwingBugtracker#8720]
Feign death resist chance on many boss fights is far above expected 17%. 

Reliquary of Souls and Supremus are 2 examples (30% and 26% respectively). This same behavior is not found in fights like Kaz'rogal.

Some speculation on what may be the cause of this: This may be due to npcs/mobs that are not part of the encounter or NPCs that exist for coordinates of abilities like supremus volcanoes having an effect on the resist chance. It also may be because a resist from an additional out of range npc prevents the feign death animation (and maybe this affects other mobs ability to be affected by the feign). It is not absolutely clear what is causing the increased resist chance, but these things should not be impacting boss fight mechanics.

Whatever the case, there is an improper interaction occurring on many bosses that may be due to mob proximity or npc interaction (or may be caused by something else) that is affecting feign death resists.

**Comment by Godmatik** [comment]
Yeah something is up - about 2000ish tests were performed so I think the sample size is large enough to warrant a review. 

Invisible triggers or something else is affecting/adding to the FD resist calculation for certain fights.

**Comment by Wolffenstein** [comment]
Fixed in rev 3879.
