### ISSUE TITLE
Pet Damage Modifiers

### ISSUE THREAD

**Issue by spacct** [Atlantiss/NetherwingBugtracker#8721]

**Comment by Wolffenstein** [comment]
I don't know where they got those numbers from and how accurate they are, not to mention Blizz unified a lot of this stuff over the patches so 2.0.10 data may not have been correct at 2.4.3.

**Comment by spacct** [comment]
Pet damage modifiers existed in og vanilla as well as classic and classic tbc.

What kind of data would you need to serve as backup if the original post is insufficient?
