### ISSUE TITLE
Darkmoon Card: Madness grants non class related auras

### ISSUE THREAD

**Issue by yesgodx** [Atlantiss/NetherwingBugtracker#8722]
**Description**: 
Darkmoon Card: Madness grants all auras regardless of class.
**Current behaviour**:
As tried this trinket on hunter, I received "Dementia" or "Megalomania" auras upon a killing blow.
**Expected behaviour**: 
Neither "Dementia" or "Megalomania" are listed as hunter class specific auras granted by Darkmoon Card: Madness according to https://wowhead.com/tbc/item=31859/darkmoon-card-madness
**Server Revision**: 
3877

**Comment by Wolffenstein** [comment]
Fixed in rev 3879.
