### ISSUE TITLE
[Item][Proc Conditions] EVERYTHING procs Tome of Fiery Redemption

### ISSUE THREAD

**Issue by ashido96** [Atlantiss/NetherwingBugtracker#8728]
[//]: # (Enclose links to things related to the bug using http://wowhead.com or any other TBC database.)
[//]: # (You can use screenshot ingame to visual the issue.)
[//]: # (Write your tickets according to the format:)
[//]: # ([Quest][Azuremyst Isle] Red Snapper - Very Tasty!)
[//]: # ([NPC] Magistrix Erona)
[//]: # ([Spell][Mage] Fireball)
[//]: # ([Npc][Drop] Ghostclaw Lynx)
[//]: # ([Web] Armory doesnt work)
[//]: # (To find server revision type `.server info` command in the game chat.)

**Description**: 
Getting portaled out of a dungeon after the 1 minute expires procs Tome of Fiery Redemption. 
Using dual-spec procs Tome of Fiery Redemption
Summoning players at summoning stone procs Tome of Fiery Redemption

edit: crafting felsteel stabilizers should not proc Tome of Fiery Redemption

**Expected behaviour**: 
Not doing that. 

**Server Revision**: 
7386

**Comment by Godmatik** [comment]
Source would be nice - some things like Insightful meta gem proc from literally anything, so it's not inconceivable some trinket would do the same. 

I only spent a minute checking and found the below from wowhead, but the list is not exhaustive

![tomeoffiery](https://github.com/Atlantiss/NetherwingBugtracker/assets/37913400/cd91382a-9707-4ecf-9701-68b11b2813b1)

**Comment by Godmatik** [comment]
![workingasintended](https://github.com/user-attachments/assets/8142350a-059b-4208-ac8a-eacfd01b9b78)

Looks like it is working as it is supposed to

Closing
