### ISSUE TITLE
a chest_item (Raptorbane armor)

### ISSUE THREAD

**Issue by vladp915** [Atlantiss/NetherwingBugtracker#8729]
[//]: # (Enclose links to things related to the bug using http://wowhead.com or any other TBC database.)
[//]: # (You can use screenshot ingame to visual the issue.)
[//]: # (Write your tickets according to the format:)
[//]: # ([Quest][Azuremyst Isle] Red Snapper - Very Tasty!)
[//]: # ([NPC] Magistrix Erona)
[//]: # ([Spell][Mage] Fireball)
[//]: # ([Npc][Drop] Ghostclaw Lynx)
[//]: # ([Web] Armory doesnt work)
[//]: # (To find server revision type `.server info` command in the game chat.)

**Description**: 
it says when the chest item is equipped and while fighting beasts an attack power should be increased by 30.

**Current behaviour**: 
i've got two screenshots -- before fighting a beast my attack power is 169 and during the fighting it is still 169;

<img width="640" alt="attack_power_1" src="https://github.com/Atlantiss/NetherwingBugtracker/assets/134797213/75ec699c-4915-4e64-b3df-a9d8071500e4">
<img width="640" alt="attack_power_2" src="https://github.com/Atlantiss/NetherwingBugtracker/assets/134797213/2b6912a0-50e3-42b2-bc2b-b3d8574802da">

**Expected behaviour**:
if i'm not wrong, then my attack power should be -- 169+30 = 199. 

**Server Revision**:

**Comment by Godmatik** [comment]
Pretty sure it's blizzlike that it doesn't show the increased AP in your character sheet but it does function
