### ISSUE TITLE
[NPC] Keeper Ordanus

### ISSUE THREAD

**Issue by totaemoeggerli** [Atlantiss/NetherwingBugtracker#873]
[//]: # (Enclose links to things related to the bug using http://wowhead.com or any other TBC database.)
[//]: # (You can use screenshot ingame to visual the issue.)
[//]: # (Write your tickets according to the format:)
[//]: # ([Quest][Azuremyst Isle] Red Snapper - Very Tasty!)
[//]: # ([NPC] Magistrix Erona)
[//]: # ([Spell][Mage] Fireball)
[//]: # ([Npc][Drop] Ghostclaw Lynx)
[//]: # ([Web] Armory doesnt work)

**Description**: 
[Keeper Ordanus](https://www.wowhead.com/npc=4273/keeper-ordanus) spawns treants during fight.

**Current behaviour**:
[No treants spawn during the fight](https://gfycat.com/FearlessImaginaryArcherfish)

**Expected behaviour**: 
By Nosrac (3,612 – 1·4·20) on 2007/01/30 (Patch 2.0.6)
> He's very easy to Kill, it's his body guards that are tough..
After about 15 Seconds He will spawn 3 (ish) level 16 Treants and repeat that every 5 seconds. ...

**Server Revision**: 2083

**Comment by aresbrutus** [comment]
on 2007/02/23 (Patch 2.0.8)
`just to clarify its the adds that spawn the treants not Ordanus himself`

on 2009/01/30 (Patch 3.0.8)
`It was nerfed in 2.4 (the patch where they made a TON of the quests easier, and nerfed most of the old-world elites). But yeah, there are no more Treant adds.`

**Comment by wtRCH** [comment]
Patch 2.4 change, added label for future use (if needed). 

Closed due to post nerf leveling on the server.
