### ISSUE TITLE
Big Iron Fishing Pole

### ISSUE THREAD

**Issue by Theeworldrevisited** [Atlantiss/NetherwingBugtracker#8730]
[/Item/]: # [Desolace - The Veiled Sea][Sar'Theris Strand] Big Iron Fishing Pole

**Description**:  Created a ticket requesting information if the Big Iron Fishing Pole was still a random drop from a Shellfish Trap in Desolace.  I had farmed them several times in WoW, but spent several hours farming in Netherwing and had multiple items drop, but never the pole.  The GM responded that there was no history of the pole being a drop from there and it might be missing or an issue preventing it from dropping.  The GM recommended I create an issue here.  I apologize if I've failed to create this ticket appropriately.

[https://www.wowhead.com/classic/item=6367/big-iron-fishing-pole#contained-in-object](url)

**Comment by fondlez** [comment]
There is no other source for that item and it certainly exists on Netherwing, since here it is on the Auction House:

![image](https://github.com/Atlantiss/NetherwingBugtracker/assets/98790400/53e5f57d-e32e-4eaa-8f30-73039ff97f5a)

**Comment by Theeworldrevisited** [comment]
Was informed by the GM that there was no record of a drop of that item from the Shellfish Traps, as indicated by Wowhead.  I was told to list it on Bugtracker.  Obviously, it seemingly exists, but must have dropped from an alternate source not listed?  "Working as intended" doesn't really fit.

**Comment by DFOXpro** [comment]
I got this afte 1 hour farming 
![Capture du 2023-10-18 17-38-35](https://github.com/Atlantiss/NetherwingBugtracker/assets/5248241/86d49e8d-d9b2-4af9-8647-80403d232ac3)
 so this ticket can set as close I suppose
