### ISSUE TITLE
Physical Pet Abilities (bite, gore, etc.) Not Scaling with Buffs/Debuffs

### ISSUE THREAD

**Issue by spacct** [Atlantiss/NetherwingBugtracker#8732]
Physical pet abilities are not scaling properly with buffs/debuffs. Armor penetration and attack power bonuses should affect all physical pet abilities.

**Comment by ghost** [comment]
I can confirm that. As of right now **Bite** is dealing like no damage compared to Lightning Breath (Serpent).

**Comment by spacct** [comment]
Correct. And this is even though Bite has more tooltip damage, and should be benefitting from a huge number of boss debuffs (expose armor, sunder, expose weakness, imp hunters mark) as well as pet buffs (might, kings, motw, strength/agi scrolls) etc.

**Comment by Wolffenstein** [comment]
Those spells do not have an attack power coefficient in TBC - they simply do not scale with AP until wotlk (you can compare tbc and wotlk versions of them on wowhead, AP coeff is displayed there). Lightning Breath on the other hand scales with SP in TBC.

**Comment by Godmatik** [comment]
Yes but shouldn't they still be impacted by sunder armor and such?
