### ISSUE TITLE
[Spell][Paladin] Flash of light

### ISSUE THREAD

**Issue by B1indLife** [Atlantiss/NetherwingBugtracker#8733]
[//]: # (Enclose links to things related to the bug using http://wowhead.com or any other TBC database.)
[//]: # (You can use screenshot ingame to visual the issue.)
[//]: # (Write your tickets according to the format:)
[//]: # ([Quest][Azuremyst Isle] Red Snapper - Very Tasty!)
[//]: # ([NPC] Magistrix Erona)
[//]: # ([Spell][Mage] Fireball)
[//]: # ([Npc][Drop] Ghostclaw Lynx)
[//]: # ([Web] Armory doesnt work)
[//]: # (To find server revision type `.server info` command in the game chat.)

**Description**: 
Healing bonus is not working for my paladin.
**Current behaviour**:
My flash of light skill says it heals for 458 to 513. I have a healing light talent that increases the amount healed by flash of light by 12%. Thus, when my character is completely undressed, the average amount of healing for 6 spells is 576. (586+575+588+552+584+576)/6=576. 
![WoWScrnShot_101123_214021](https://github.com/Atlantiss/NetherwingBugtracker/assets/147757523/fd224c1d-1585-4e0d-aaad-b4e4c0be134c)
When my character is dressed, albeit poorly, the average amount of healing for 6 spells is 854. (863+835+882 +828+887+829)/6=854. 
![WoWScrnShot_101123_214458](https://github.com/Atlantiss/NetherwingBugtracker/assets/147757523/608392fe-6691-4dc4-874c-9855155cf773)
My bonus healing is 660, magic damage bonus is 297. So my average heal should be 660+576=1236. And it seems that bonus healing does not work, only magic damage bonus is taken instead.
**Expected behaviour**: 
Flash of light should use bonus healing not only magic damage bonus.
**Server Revision**: 
3880

**Comment by fondlez** [comment]
That's not how healing bonus works. All spells have built in spell modifiers, even excluding downranking modifiers. You don't just get 100% of your healing bonus applied to all your spells! As a general rule, only sufficiently long duration Heal over Time spells (HoTs) or channels get 100% spell modifiers.

Flash of Light, which is a short 1.5s cast, has a modifier of [42.9%](https://www.wowhead.com/tbc/spell=27137/flash-of-light) (shows as "SP mod: 0.429" under Wowhead's datamining of client files, for example).

So, the actual bonus you get from gear to Flash of Light (Rank 7), before talents, buffs or other changes are applied in the example above of Bonus Healing of 660 is 660 x 42.9% = **283.14** (283 rounded down).

854 - 576 = 278

which is within the variance of only 6 samples.

**Comment by B1indLife** [comment]
No more questions. Thanks a lot.
