### ISSUE TITLE
[Battleground] Eye of the Storm ghost issues

### ISSUE THREAD

**Issue by tsu-1** [Atlantiss/NetherwingBugtracker#8735]
[//]: # (Enclose links to things related to the bug using http://wowhead.com or any other TBC database.)
[//]: # (You can use screenshot ingame to visual the issue.)
[//]: # (Write your tickets according to the format:)
[//]: # ([Quest][Azuremyst Isle] Red Snapper - Very Tasty!)
[//]: # ([NPC] Magistrix Erona)
[//]: # ([Spell][Mage] Fireball)
[//]: # ([Npc][Drop] Ghostclaw Lynx)
[//]: # ([Web] Armory doesnt work)
[//]: # (To find server revision type `.server info` command in the game chat.)

**Description**: Eye of the Storm Battleground

**Current behaviour**: When being a ghost and falling down into the void you are not being teleported back to the nearest graveyard.

**Expected behaviour**: When fell to the void, be ported to the nearest graveyard.

**Server Revision**: 3880

**Comment by Wolffenstein** [comment]
![image](https://github.com/Atlantiss/NetherwingBugtracker/assets/1576644/d763283d-7ad1-4feb-bf27-76dca0106fcd)
works fine
