### ISSUE TITLE
Blood Fury Consumes a Misdirection Charge

### ISSUE THREAD

**Issue by spacct** [Atlantiss/NetherwingBugtracker#8736]
[//]: # (Enclose links to things related to the bug using http://wowhead.com or any other TBC database.)
[//]: # (You can use screenshot ingame to visual the issue.)
[//]: # (Write your tickets according to the format:)
[//]: # ([Quest][Azuremyst Isle] Red Snapper - Very Tasty!)
[//]: # ([NPC] Magistrix Erona)
[//]: # ([Spell][Mage] Fireball)
[//]: # ([Npc][Drop] Ghostclaw Lynx)
[//]: # ([Web] Armory doesnt work)
[//]: # (To find server revision type `.server info` command in the game chat.)

**Description**: 
Using Blood Fury (Orc Racial) with Misdirection on a target consumes 1 charge of the available 3.
**Current behaviour**:

**Expected behaviour**: 
Blood Fury, and other non-damaging abilities should never consume Misdirection charges.
**Server Revision**:

**Comment by Wolffenstein** [comment]
Fixed in rev 3931.
