### ISSUE TITLE
[2.3 PTR] - ZA Prisoners Timer

### ISSUE THREAD

**Issue by Godmatik** [Atlantiss/NetherwingBugtracker#8739]
**Current behaviour**:
During last server - ZA timer was nerfed (increased) a few months in.

**Expected behaviour**: 
5 additional minutes was added to the timer when defeating Akil'zon in rev 3625, - need to remove this 
(adds 10 minutes currently, should only be 5).

![3625](https://github.com/Atlantiss/NetherwingBugtracker/assets/37913400/c50a1e81-b87e-472b-a2c8-4a613fa2c85b)

**Comment by Wolffenstein** [comment]
changed
