### ISSUE TITLE
[World] Battered Chests not having any loot.

### ISSUE THREAD

**Issue by Unfairy** [Atlantiss/NetherwingBugtracker#874]
Last 3 Chests I looted didnt had any loot in them at all.
Looted 2 in Ashenvale and 1 in Redridge. Chests in Darkshore seemed fine.
Also, not sure, but I think they are supposed to disappear after some time if someone looted them but not looted everything, so they can reset.

**Comment by The14me** [comment]
Duplicate https://github.com/Atlantiss/NetherwingBugtracker/issues/478
