### ISSUE TITLE
cannt learn skill Redemption for some wrong choice

### ISSUE THREAD

**Issue by dojoc** [Atlantiss/NetherwingBugtracker#8740]
hi im pala player playying netherwing relam.when i do the quest The Tome of pinity i give up this quest and cannt do it again,so i cannt learn the skill named Redemption which is very important for pala.my account is chandob relem is netherwing and my character name is Holyholy.Thanks for your help!

**Comment by Godmatik** [comment]
You will need to open a GM ticket in-game
