### ISSUE TITLE
[Hunter Pets] - No base critical strike chance or critical strike gained from agility

### ISSUE THREAD

**Issue by Godmatik** [Atlantiss/NetherwingBugtracker#8741]
**Current behaviour**:
A hunter pet currently has 0% base critical strike chance.
In addition - the agility value that the pet has does not offer any additional critical strike

Tested with two different pets

0% critical strikes (no 10% BM crit talent)
![image](https://github.com/Atlantiss/NetherwingBugtracker/assets/37913400/6b971aea-207f-42e3-8a78-4270756f7b7d)

Close to 10% critical strikes (with 10% BM crit talent)
![image](https://github.com/Atlantiss/NetherwingBugtracker/assets/37913400/9510b418-6093-4228-913e-527d1b1a2706)

**Expected behaviour**: 
Hunter pets should have some base critical strike chance, I believe it is 5%
In addition - the agility stat on a hunter pet should also provide it with critical strike. Right now buffing it with an agility scroll serves no purpose.

**Server Revision**: 
3888

**Comment by Wolffenstein** [comment]
Fixed in rev 3936.
