### ISSUE TITLE
[Spell][Mage] Molten Armor - Deals damage though anything

### ISSUE THREAD

**Issue by Shanrolol** [Atlantiss/NetherwingBugtracker#8742]
[//]: # (Enclose links to things related to the bug using http://wowhead.com or any other TBC database.)
[//]: # (You can use screenshot ingame to visual the issue.)
[//]: # (Write your tickets according to the format:)
[//]: # ([Quest][Azuremyst Isle] Red Snapper - Very Tasty!)
[//]: # ([NPC] Magistrix Erona)
[//]: # ([Spell][Mage] Fireball)
[//]: # ([Npc][Drop] Ghostclaw Lynx)
[//]: # ([Web] Armory doesnt work)
[//]: # (To find server revision type `.server info` command in the game chat.)

**Description**: 
Mage spell https://www.wowhead.com/tbc/spell=30482/molten-armor deals damage through immunities
**Current behaviour**:
When you hit a mage with a Molten Armor buff in PvP, it can do its damage though magic damage immunity, like https://www.wowhead.com/tbc/spell=31224/cloak-of-shadows, or complete immunity to any attack, like https://www.wowhead.com/tbc/spell=1020/divine-shield, as shown on the screenshot attached below.
**Expected behaviour**: 
The damage from hitting the mage should be bypassable by immunity effects, while those last.
**Server Revision**: 
3888
![65666](https://github.com/Atlantiss/NetherwingBugtracker/assets/16698440/234606a0-9060-4d65-8003-2aacd5fbf0f3)

**Comment by Wolffenstein** [comment]
Fixed in rev 3931.
