### ISSUE TITLE
[2.3 PTR] Zul'aman - RP ending "celebration" missing

### ISSUE THREAD

**Issue by Godmatik** [Atlantiss/NetherwingBugtracker#8744]
**Current behaviour**:
After defeating Zul'jin, nothing happens

**Expected behaviour**: 
After defeating Zul'jin - NPCs are supposed to show and celebrate. Playing music, drums, cheering, laughing, other related things. I believe it depends also on which NPCs you chose to free from the frogs.

https://www.youtube.com/watch?v=goZQV2TCBu4

**Server Revision**: 
2.3 PTR

**Comment by Wolffenstein** [comment]
only npcs you freed during the prisoner execution event will show up
