### ISSUE TITLE
TBC server have a Bug with hunter`s pet

### ISSUE THREAD

**Issue by ddlin888** [Atlantiss/NetherwingBugtracker#8745]
[//]: # (Enclose links to things related to the bug using http://wowhead.com or any other TBC database.)
[//]: # (You can use screenshot ingame to visual the issue.)
[//]: # (Write your tickets according to the format:)
[//]: # ([Quest][Azuremyst Isle] Red Snapper - Very Tasty!)
[//]: # ([NPC] Magistrix Erona)
[//]: # ([Spell][Mage] Fireball)
[//]: # ([Npc][Drop] Ghostclaw Lynx)
[//]: # ([Web] Armory doesnt work)
[//]: # (To find server revision type `.server info` command in the game chat.)

**Description**: 
In the last two weeks,TBC server have a Bug with hunter`s pet
**Current behaviour**:
Hunter`s pet cant use Eyes of the Beast to control it,except let the pet stop follow and have a 20 yards distance.This BUG already effect RAID BWL cant control Razorgore the Untamed.
**Expected behaviour**: 
Hunter can use Eyes of the Beast to control pet normally
**Server Revision**: 
3891
![WoWScrnShot_102823_224051](https://github.com/Atlantiss/NetherwingBugtracker/assets/149252525/21bf351b-574e-4d22-b805-74217965a62a)

**Comment by Godmatik** [comment]
Confirmed - eyes of the beast does not work, when attempting to use it, control of pet is lost instantly.

Tested with three different pets. 

The original poster mentioned Razorgore - so might be a bug in general with controlling things (eye of killrog may also be impacted, etc)

**Comment by Wolffenstein** [comment]
Fixed in rev 3893.
