### ISSUE TITLE
[Spell] Heroism buff is sometimes removed from players too early

### ISSUE THREAD

**Issue by MecAtlantiss** [Atlantiss/NetherwingBugtracker#8749]
**Description**: The Heroism buff is sometimes being removed from players too early. It doesn't appear to be an issue of hitting the buff limit.

**Current behaviour**: Here are two clips of this happening:

https://clips.twitch.tv/EnthusiasticBelovedSwanYouWHY-JTX8lSkACVMjRdAy

https://clips.twitch.tv/AdventurousObeseShieldFUNgineer-c0Q_me2gZNgtLqDw

Could it be caused by Mother Shahraz's "Prismatic Aura: Nature" debuff, since Heroism is a nature spell? It's a stretch, but it's all I can think of. I'm trying to find this bug happening on other bosses but no success yet.

**Expected behaviour**: I don't believe Heroism should be removed in these cases.

**Server Revision**: 3897

**Comment by Godmatik** [comment]
![Cillostatue](https://github.com/Atlantiss/NetherwingBugtracker/assets/37913400/07ac0b8e-c622-4090-8aa4-3e094e8c893a)

**Comment by Godmatik** [comment]
Looks like due to being tucked into the statue object, lust/heroism grows your character's model, can't grow into the statue, so the game force cancels it.

**Comment by MecAtlantiss** [comment]
![image](https://github.com/Atlantiss/NetherwingBugtracker/assets/16357005/9216909a-c87c-43b9-8f0f-45277f222e65)
