### ISSUE TITLE
[Quest][Stonetalon Mountains] Boulderslide Ravine

### ISSUE THREAD

**Issue by ghost** [Atlantiss/NetherwingBugtracker#875]
**Description**: The quest has 2 objectives. Investigate the cave (1st) and Gather 10 crystals (2nd).

**Current behavior**: You take credit for the 1st objective only when 2nd is finished. I was at the upper side of the cave when that happened.

**Expected behaviour**: Take credit for the 1st objective when you reach near the water of the cave and not when you gather all the crystals.

**Server Revision**: 2083

**Comment by Retinus** [comment]
server rev 2094

Same issue with [#442](https://github.com/Atlantiss/NetherwingBugtracker/issues/442)

442 should be opened

**Comment by duzyizly** [comment]
fixed in 3391 (duplicate).
