### ISSUE TITLE
Verdant Orb RP - strings missing in text

### ISSUE THREAD

**Issue by Godmatik** [Atlantiss/NetherwingBugtracker#8750]
**Current behaviour**
See below screenshot, strings are improper in 3rd line, Adal RP after turning in Verdant Sphere

**Expected behaviour**: 
Should be %n and %g (not $)
Should say his or her based on character's gender

![image-17](https://github.com/Atlantiss/NetherwingBugtracker/assets/37913400/1e3d206d-a678-4359-a36f-0e3a54b69972)

**Comment by Godmatik** [comment]
![2nd](https://github.com/Atlantiss/NetherwingBugtracker/assets/37913400/e76c963a-43dd-469b-b6e2-d3bf5e7e3f1c)

Either it was fixed or the original screenshot only happens under certain circumstances

**Comment by Wolffenstein** [comment]
It's possible the player just leaves, blizzlike bug
