### ISSUE TITLE
Regrowth hot is not stacking

### ISSUE THREAD

**Issue by Aksh1232** [Atlantiss/NetherwingBugtracker#8751]
Description:
When first druid use Regrowth on target second Refrowth from other druid dont leave hot on target. The higher efect has priority and overwrites the lower one.

Current behaviour: 
https://www.youtube.com/watch?v=7weYmM2WPs8&ab_channel=XyzYXZ

Expected behaviour:
Regrowth hots from difrent druids should stack on one target.

**Comment by Godmatik** [comment]
Confirmed - possibly a side effect of this fix done last month:

https://github.com/Atlantiss/NetherwingBugtracker/issues/8697

**Comment by Wolffenstein** [comment]
Fixed in rev 3910.
