### ISSUE TITLE
([Collision Issue][Arathi Basin][Berserking Buff][Door is too small])

### ISSUE THREAD

**Issue by Bakuretsux2lalala** [Atlantiss/NetherwingBugtracker#8752]
**Description**: 
There is a colision issue in arathi basin pvp map, where as a tauren, if you walk into the random buff hut near the farm flag in Arathi Basin, you will become stuck and unable to exit. if you shrink you can escape - but noggenfoggers doesn't always shrink you. 
**Current behaviour**:
Currently if you enter the buff hut @ Farm on Arathi Basin map if you pick up a berserking buff as tauren, you will become stuck until the buff is over or you shrink yourself.  
**Expected behaviour**: 
a tauren should be able to walk out of the buff hut after obtaining berserking, but the size increase makes it impossible.  Perhaps adjusting the collision of the doorframe would help or making it a bit wider so large character models can walk back out again.
**Server Revision**: 
3910

**Comment by Wolffenstein** [comment]
I can't adjust the collision because it's handled clientside, the server doesn't control that at all. I don't know if it's some blizzlike client bug or not but there's nothing I can do about it

**Comment by Bakuretsux2lalala** [comment]
is there someway you could reduce how big taurens get in this zone or with the buff in general, until we can exit safely?
