### ISSUE TITLE
"Field Duty" - Horde Quest

### ISSUE THREAD

**Issue by salane8** [Atlantiss/NetherwingBugtracker#8755]
[//]: # (Enclose links to things related to the bug using http://wowhead.com or any other TBC database.)
[//]: # (You can use screenshot ingame to visual the issue.)
[//]: # (Write your tickets according to the format:)
[//]: # ([Quest][Azuremyst Isle] Red Snapper - Very Tasty!)
[//]: # ([NPC] Magistrix Erona)
[//]: # ([Spell][Mage] Fireball)
[//]: # ([Npc][Drop] Ghostclaw Lynx)
[//]: # ([Web] Armory doesnt work)
[//]: # (To find server revision type `.server info` command in the game chat.)

**Description**: Horde quest Filed Duty in Silithus is not doable. https://www.wowhead.com/classic/quest=8731/field-duty#comments

**Current behaviour**:After you recive documents to be sign, first you need to right click on them to prepere them.
After that you speak with Krug Skullsplit and accpet assigment. Fight begins with gigantic bug. 
After you win and Krug Skullsplit survives he has silver mark above his head and if you speak with him he 
suppose to sign documets for you, but he dont. Insteed after bug disapears if you click again another fight begins.
And you can fo it again and again with no result...

**Expected behaviour**: After you defeat Bug (Hunter-Killer) Krug Skullsplit should sign your documents.

**Server Revision**: Netherwing

**Comment by Wolffenstein** [comment]
Fixed in rev 3931.
