### ISSUE TITLE
Supremus - Molten Flame

### ISSUE THREAD

**Issue by Godmatik** [Atlantiss/NetherwingBugtracker#8756]
**Current behaviour**:
Molten Flame ability from Supremus has a chance to target only the tank or melee, the resulting flame path is etiher very short or just one patch of flame and hardly hits anyone

https://clips.twitch.tv/CrispyDiligentSowMrDestructoid-XgbZYWHWKqfYJl6M

**Expected behaviour**: 
In every classic video I have watched, the molten flame has a path whenever spawned and is always at least several patches long/reaching out toward a ranged DPS or healer. 

Pretty sure that Supremus should prefer to target someone in range with this ability rather than someone in melee.

**Server Revision**: 
3910

**Comment by Wolffenstein** [comment]
Fixed in rev 3931.
