### ISSUE TITLE
Illidan Shadow Demon can kill you without reaching you (under certain circumstances)

### ISSUE THREAD

**Issue by Godmatik** [Atlantiss/NetherwingBugtracker#8760]
**Description**: 
Illidan Shadow demon adds during Demon phase of encounter

**Current behaviour**:
When the shadow demons spawn during demon phase and target someone - if that individual they are tracking dies due to some other circumstance that is not due to the demon reaching him (such as flame burst) - the demon will select a new player, kill him instantly (without physically reaching him), and then target another new player and move toward him.

https://www.twitch.tv/matik35/clip/SweetGlutenFreeMarjoramStrawBeary-c0-1cTYNtJhnUMP7?featured=true&filter=clips&range=24hr&sort=time

(Demon marked as X - person he was targeting died to Illidan's shadow blast - the shadow demon then insta killed someone new - before selecting and moving to a different new target)

**Expected behaviour**: 
If someone dies while being target by shadow demon, then the shadow demon should target someone new and move towards him as normal.

**Server Revision**: 
3914

**Comment by Wolffenstein** [comment]
Nope, something else killed them not the Shadow Demon. Shadow Demon needs to be in melee with its specific, paralyzed target to cast the instakill

**Comment by Godmatik** [comment]
You can clearly see in the clip and with my descriptions he did not die from something else. Also this is not some isolated incident, other guilds have experienced the same bug.

Guess I will include death log/combat log next time it happens ...

**Comment by T0mken** [comment]
Bump
