### ISSUE TITLE
[BT] - Illidan movement is unresponsive when spell queued or after spell cast.

### ISSUE THREAD

**Issue by Godmatik** [Atlantiss/NetherwingBugtracker#8761]
**Current behaviour**:
Follow-up of https://github.com/Atlantiss/NetherwingBugtracker/issues/8714

Illidan has difficulty moving to the tank after casting a spell and/or queued preparing to cast a new spell (Shear, Flame Crash, Draw Soul)

https://clips.twitch.tv/UnsightlyBloodyWalrusUWot-P81RsBug2vpCsSE_

**Expected behaviour**: 
Should move fluently when not casting

**Server Revision**: 
3914

**Comment by Wolffenstein** [comment]
clip missing

**Comment by Godmatik** [comment]
https://clips.twitch.tv/UnsightlyBloodyWalrusUWot-P81RsBug2vpCsSE_

**Comment by Godmatik** [comment]
The clip does not work when linking it in github for some reason, will DM it

**Comment by Tholin44** [comment]
It does work .. copy it with _ at end, lol.

**Comment by Wolffenstein** [comment]
Fixed in rev 3943.
