### ISSUE TITLE
The Maker Blood Furnance

### ISSUE THREAD

**Issue by Vinbaz123** [Atlantiss/NetherwingBugtracker#8764]
[//]: # ([NPC] The Maker)

The Maker in Blood Furnance does aggro reset everytime he casts a Mind controll. It makes him impossible to solo since he reset if you are solo, but if you have a friend with you that dies same thing happens.

The Maker in Blood Furnance does aggro reset everytime he casts a Mind controll. It makes him impossible to solo since he reset if you are solo, but if you have a friend with you that dies same thing happens. From what iv read on wowhead he should not be acting this way. 

Not to drop aggro and reset everytime he mind controlls

**Server Revision**:

**Comment by Wolffenstein** [comment]
Fixed in rev 3931.
