### ISSUE TITLE
Cannot craft Primal Mooncloth in Cenarion Thicket

### ISSUE THREAD

**Issue by slamss** [Atlantiss/NetherwingBugtracker#8765]
[//]: # (Enclose links to things related to the bug using http://wowhead.com or any other TBC database.)
[//]: # (You can use screenshot ingame to visual the issue.)
[//]: # (Write your tickets according to the format:)
[//]: # ([Quest][Azuremyst Isle] Red Snapper - Very Tasty!)
[//]: # ([NPC] Magistrix Erona)
[//]: # ([Spell][Mage] Fireball)
[//]: # ([Npc][Drop] Ghostclaw Lynx)
[//]: # ([Web] Armory doesnt work)
[//]: # (To find server revision type `.server info` command in the game chat.)

**Description**: 
Cannot craft Primal Mooncloth in Cenarion Thicket

**Current behaviour**:

Get error when I try to craft Primal Mooncloth in the Cenarion Thicket Moonwell
**Expected behaviour**: 
This should work

**Server Revision**: 
server 2.2 - client 2.4.3

**Comment by Wolffenstein** [comment]
Fixed in rev 3917.
