### ISSUE TITLE
Ethereal Mutagen does not have any effect.

### ISSUE THREAD

**Issue by iDreamInBinary** [Atlantiss/NetherwingBugtracker#8766]
[//]: # (Enclose links to things related to the bug using http://wowhead.com or any other TBC database.)
[//]: # (You can use screenshot ingame to visual the issue.)
[//]: # (Write your tickets according to the format:)
[//]: # ([Quest][Azuremyst Isle] Red Snapper - Very Tasty!)
[//]: # ([NPC] Magistrix Erona)
[//]: # ([Spell][Mage] Fireball)
[//]: # ([Npc][Drop] Ghostclaw Lynx)
[//]: # ([Web] Armory doesnt work)
[//]: # (To find server revision type `.server info` command in the game chat.)

**Description**: 
The Ethereal Mutagen you can buy off the Shop Pet "Ethereal Soul-Trader" does not have the desired effect. item id 38291
**Current behaviour**:

The item is consumed on use, but does not change the look of the targeted Non-combat pet.

**Expected behaviour**: 

The targeted non-combat pet should be transformed into a small protean horror.

**Server Revision**: 
Stormforge Netherwing | Content patch: 2.2.0 | Revision: 3914

**Comment by Wolffenstein** [comment]
![image](https://github.com/Atlantiss/NetherwingBugtracker/assets/1576644/74913704-96a0-49c9-b4db-0f88e5731339)
It works fine for me, can you record it please?
