### ISSUE TITLE
Broodlord Mandokir has Fear ability

### ISSUE THREAD

**Issue by sasadubi** [Atlantiss/NetherwingBugtracker#8768]
**Description**: 
Broodlord Mandokir casts Fear on MainTank, which is a mechanic he shouldn't have.
Ton of resources on internet such as: https://www.icy-veins.com/wow-classic/bloodlord-mandokir-guide-strategy-abilities-loot

**Current behaviour**:
Broodlord Mandokir has Fear ability.

**Expected behaviour**: 
Broodlord Mandokir should NOT have Fear abiltiy.

**Server Revision**: 
3914

**Comment by Wolffenstein** [comment]
Fixed in rev 3931.
