### ISSUE TITLE
 [Three Kings of Flame]

### ISSUE THREAD

**Issue by Kvazimodoo** [Atlantiss/NetherwingBugtracker#8769]
Hi i have been trying to do this quest which is required to contunie with gatherin dungeon set 2 but the fire mob in silthus who need to by summon if you have honored reputation with cenarion hold a set of twilight cultists + medalion which is part from another quest so when u get all that (and make in mind that for 1 summon your twilight se being use get disaperd + the medalion from the quest) you summon the mob but in netherwing i do 30 summons never saw then fire mob request to be killed and loot the item called Cinder of cynders can you fix it by making it spawns because we get multiply times all other elemntals but not the Duke of Cynders which is the fire requested mob for the quest thanks.

**Comment by Wolffenstein** [comment]
You need the right Signet of Beckoning
