### ISSUE TITLE
Lieutenant Valorcall and adds stuck on Stromgarde bridge

### ISSUE THREAD

**Issue by maronics** [Atlantiss/NetherwingBugtracker#877]
**Description**: 2612 and his two 2738 guards got stuck on the Stromgarde bridge when I killed the dude across of it, so it's probably something that could happen often. I couldn't reset them with feign death or running away and my pet couldn't path to them either. Relog fixed it with my death.

https://i.imgur.com/EEYP8df.jpg

**Expected behaviour**: ...not get stuck.

**Server Revision**: 2083

**Comment by maronics** [comment]
Interestingly only mobs from that side of the bridge seemed to get affected

**Comment by aresbrutus** [comment]
It might be due to their leader dying so they are afk waiting on leader respawn?

**Comment by maronics** [comment]
No, Valorcall is standing there with them. :o

**Comment by Knoox** [comment]
https://github.com/Atlantiss/NetherwingBugtracker/issues/726

**Comment by aresbrutus** [comment]
#826

Duplicate
