### ISSUE TITLE
[API] TRADE_TARGET_ITEM_CHANGED doesn't trigger after enchanting

### ISSUE THREAD

**Issue by Shineslippers** [Atlantiss/NetherwingBugtracker#8770]
[//]: # (Enclose links to things related to the bug using http://wowhead.com or any other TBC database.)
[//]: # (You can use screenshot ingame to visual the issue.)
[//]: # (Write your tickets according to the format:)
[//]: # ([Quest][Azuremyst Isle] Red Snapper - Very Tasty!)
[//]: # ([NPC] Magistrix Erona)
[//]: # ([Spell][Mage] Fireball)
[//]: # ([Npc][Drop] Ghostclaw Lynx)
[//]: # ([Web] Armory doesnt work)
[//]: # (To find server revision type `.server info` command in the game chat.)

**Description**: 
Event `TRADE_TARGET_ITEM_CHANGED` stuck(not trigger) on enchanting. To replicate bug you basically need to full up **PLAYER** trade window once.
![Capture](https://github.com/Atlantiss/NetherwingBugtracker/assets/85256266/229d9e53-4812-40e4-9380-67038704979e)

**Current behaviour**:
When player trigger event `TRADE_PLAYER_ITEM_CHANGED` several times - event `TRADE_TARGET_ITEM_CHANGED` doesn't trigger after enchanting anymore.

**Expected behaviour**: 
Event TRADE_TARGET_ITEM_CHANGED should keep trigger anytime on enchanting.

**Server Revision**: 
3928

**Comment by Wolffenstein** [comment]
![image](https://github.com/Atlantiss/NetherwingBugtracker/assets/1576644/d9078d0f-8467-4a72-833a-1e1d9c8885bd)
It's a clientside bug/behaviour. The server has nothing to do with it
