### ISSUE TITLE
Hyjal - Rage Winterchill occasionally interrupts his own Death and Decay

### ISSUE THREAD

**Issue by Godmatik** [Atlantiss/NetherwingBugtracker#8771]
**Current behaviour**:
Rage can sometimes interrupt his own cast. In clip below you can see he does so to cast Frost Nova on melee.

https://clips.twitch.tv/SillyPiliableSwanSwiftRage-qQGV6TSogKurdh4B

**Expected behaviour**: 
Should never interrupt his Death and Decay ability

**Server Revision**: 
3928

**Comment by Wolffenstein** [comment]
Fixed in rev 3931.
