### ISSUE TITLE
BT - Illidan melees after trap expires in final phase

### ISSUE THREAD

**Issue by Godmatik** [Atlantiss/NetherwingBugtracker#8772]
**Current behaviour**:
When Illidan is stunned by Maiev trap and it expires, he is still active in human form and does another melee or two before changing to demon phase. In below clip you can see him slap our DPS warrior before transitioning

https://clips.twitch.tv/ThoughtfulJoyousAppleKappa-MdM1QaM6r5F2xh5P

**Expected behaviour**: 
Illidan should instantly go demon phase after trap expires, and should not be doing melees

**Server Revision**: 
3928

**Comment by Tholin44** [comment]
Yep ...

https://clips.twitch.tv/ScrumptiousHandsomePelicanFeelsBadMan-lnrl49L6ffzcc9tY

**Comment by Wolffenstein** [comment]
Fixed in rev 3943.
