### ISSUE TITLE
Archimonde - Finger of Death on tank

### ISSUE THREAD

**Issue by Godmatik** [Atlantiss/NetherwingBugtracker#8774]
**Current behaviour**:
Archimonde is a bit sensitive with his Finger of Death skill - can occasionally hit the tank even if they barely move

https://github.com/Atlantiss/NetherwingBugtracker/assets/37913400/16f00c7f-3d5f-4d63-aebb-a196ac15e257

Rev 3933

**Comment by Wolffenstein** [comment]
Range increased in rev 3934.
