### ISSUE TITLE
Warlock pet combat bug

### ISSUE THREAD

**Issue by budgebudge** [Atlantiss/NetherwingBugtracker#8775]
if the warlock pet gets attacked, the lock doesnt get into combat. 
should be the case cuz i was like that on all the original TBC and on classic TBC .

**Comment by budgebudge** [comment]
so basically if pet gets in combat, the warlock should too. if it dispells someone and it gets into combat then the lock should be in combat too. especially since soul link should connect them at all times.

**Comment by Scrynax** [comment]
When warlock pet gets combat you have to get combat from your pet (that's how it worked on classic TBC).

**Comment by Scrynax** [comment]
In classic i believe there was invisible combat after pet got combat, so you couldn't resap warlock after pet got combat.

**Comment by Scrynax** [comment]
https://github.com/Atlantiss/NetherwingBugtracker/issues/8778 I made similiar pet issue with fel hunter devour magic (if it resists pet doesnt get combat).

**Comment by Godmatik** [comment]
For hunter pet it puts the hunter in combat when it gets attacked initially - however you can FD and remain out of combat even if the pet is still attacking/being attacked, seems like a bug as well

**Comment by Wolffenstein** [comment]
Fixed in rev 3958.
