### ISSUE TITLE
[Feast of Winter Veil] The Hero of the Day quest has wrong attributes

### ISSUE THREAD

**Issue by Shineslippers** [Atlantiss/NetherwingBugtracker#8777]
[//]: # (Enclose links to things related to the bug using http://wowhead.com or any other TBC database.)
[//]: # (You can use screenshot ingame to visual the issue.)
[//]: # (Write your tickets according to the format:)
[//]: # ([Quest][Azuremyst Isle] Red Snapper - Very Tasty!)
[//]: # ([NPC] Magistrix Erona)
[//]: # ([Spell][Mage] Fireball)
[//]: # ([Npc][Drop] Ghostclaw Lynx)
[//]: # ([Web] Armory doesnt work)
[//]: # (To find server revision type `.server info` command in the game chat.)

**Description**: 
Quests [The Hero of the Day](https://www.wowhead.com/tbc/quest=8763/the-hero-of-the-day)[id8763] and probably [The Hero of the Day](https://www.wowhead.com/tbc/quest=8799/the-hero-of-the-day)[id8799] has wrong attributes

**Current behaviour**:
Quests is repetable without any requirments.

**Expected behaviour**: 
Repetable once a year during seasonal event and 5g to turn in.

**Server Revision**: 
3933

**Comment by Godmatik** [comment]
I'm also being told the Horde one does not function at all (8799)

**Comment by Wolffenstein** [comment]
Fixed in rev 3938.
