### ISSUE TITLE
devour magic resist doesn't give combat to pet

### ISSUE THREAD

**Issue by Scrynax** [Atlantiss/NetherwingBugtracker#8778]
**Description**: 
Whenever pet attempts to devour magic enemy it should have combat regardless of the spell resisting or not.

**Current behaviour**:
If devour magic resists it doesn't give combat to pet - therefore lock cant get combat from his pet through buffing.

**Expected behaviour**: 
Regardless of devour magic resisting or not, pet gets combat.

**Server Revision**:

**Comment by Scrynax** [comment]
another pet issue https://github.com/Atlantiss/NetherwingBugtracker/issues/8779

**Comment by Wolffenstein** [comment]
Fixed in rev 3944.
