### ISSUE TITLE
Soul link damage doesn't break CC on pet

### ISSUE THREAD

**Issue by Scrynax** [Atlantiss/NetherwingBugtracker#8779]
**Description**: 
Soul link doesn't break breakable CC on pet aka Blind / Gouge...

**Current behaviour**:
Soul link doesn't break breakable CC on pet aka Blind / Gouge...

**Expected behaviour**: 
Soul link breaks breakable CC on pet aka Blind / Gouge...
**Server Revision**:

**Comment by Godmatik** [comment]
Can't find a video but yeah seems confirmed based on this post during WoW classic. It makes logical sense too ofc ...

![blind](https://github.com/Atlantiss/NetherwingBugtracker/assets/37913400/53429eea-9155-44fb-8024-22f9024348f6)

**Comment by Wolffenstein** [comment]
![image](https://github.com/Atlantiss/NetherwingBugtracker/assets/1576644/eb86f76b-ba64-4993-b8fa-b06d9e76b02e)
It already works...

**Comment by Scrynax** [comment]
@Wolffenstein have you tried if the cc breaks on warlocks damage with hellfire?
