### ISSUE TITLE
Sludge and Sloth missing HP/Attack values, maybe other values too

### ISSUE THREAD

**Issue by FrozenBread** [Atlantiss/NetherwingBugtracker#878]
[//]: # (Enclose links to things related to the bug using http://wowhead.com or any other TBC database.)
[//]: # (You can use screenshot ingame to visual the issue.)
[//]: # (Write your tickets according to the format:)
[//]: # ([Quest][Azuremyst Isle] Red Snapper - Very Tasty!)
[//]: # ([NPC] Magistrix Erona)
[//]: # ([Spell][Mage] Fireball)
[//]: # ([Npc][Drop] Ghostclaw Lynx)
[//]: # ([Web] Armory doesnt work)

**Description**: 
I fought Lord Malathrom (ID:503, rare spawn) and the encounter worked fine until the point where mid fight he used his ability Minions of Malathrom (ID:3537). The cast went fine, problem was, that the summons Sloth (ID:2475) and Sludge (ID:2479) were hitting for 1 damage and they died in 1 hit, probably because they had also 1hp. The passive on-hit auras they apply on the player are functioning as intended though.
**Current behaviour**: It seems that they are missing values, and that therefore, the server is giving them a default value of 1 for their stats.

**Expected behaviour**: I am not sure about the hp value, since reading up on the fight, most people say that the adds can be taken down very easily and that he's meant to resummon them every now and them. But they are supposed to have a damage value other than 1 for sure. Couldn't find video proof though.

**Server Revision**: 
[2083]

**Comment by The14me** [comment]
Confirm,spell need some rework ID: 3537
First Minion: Sloth:ID 2475
Second Minion Sludge:ID 2479
Will add more info when find value for the HP/Dmg

**Comment by Wolffenstein** [comment]
Fixed in rev 3410.
