### ISSUE TITLE
Warlock - Drain Soul is incorrectly eligible to proc "Nether Protection" 

### ISSUE THREAD

**Issue by cillo1** [Atlantiss/NetherwingBugtracker#8780]
**Current behaviour**:

When casting drain soul, you roll the 30% proc chance on the talent "Nether Protection" , which description states: 

"After being hit with a Shadow or Fire spell, you have a 30% chance to become immune to Shadow and Fire spells for 4 sec."

https://streamable.com/ekha02

**Expected behaviour**: 

Drain Soul should not be able to proc Nether Protection.

**Server Revision**: 
3933

**Comment by Wolffenstein** [comment]
Fixed in rev 3958.
