### ISSUE TITLE
Warlock - Life Tap Mana Returns incorrectly scaling with Percentage Based buffs.

### ISSUE THREAD

**Issue by cillo1** [Atlantiss/NetherwingBugtracker#8781]
**Current behaviour**:
The mana gained by the Spell "Life Tap" is incorrectly scaling with any percentage based SHADOW DAMAGE or DAMAGE buff

Examples:
Demonic Sacrifice - Succubus - 15% increased Shadow Damage
Soul Link - 5% Increased Damage
Infernal Protection (Kael'thas Boss Legendary Mace buff) - 50% Reduced Shadow Damage

are affecting Life Tap scaling.

Clip of Demonic Sacrifice - Succubus Affecting Life Tap:
https://streamable.com/s62aup

Clip of Soul Link Affecting Life Tap:
https://streamable.com/hobhst

**Expected behaviour**: 
Life Tap Mana Returns should not scale with any % based modifying buff, only the warlocks own Spell Power, and Improved Life Tap talent.

**Server Revision**: 
3933

**Comment by Wolffenstein** [comment]
Fixed in rev 3939.
