### ISSUE TITLE
Fishing - not benefiting from 2x Alliance Perk

### ISSUE THREAD

**Issue by Godmatik** [Atlantiss/NetherwingBugtracker#8782]
Fishing only grants 1 skill up point when successful catch - as opposed to 2 skill up points it should give when playing Alliance.

The fix done on Rev 3928 did not appear to solve the problem.

**Comment by Wolffenstein** [comment]
Fishing works differently since it's based on a number of steps required to gain a skill point. Alliance perk reduces that amount by half.
