### ISSUE TITLE
[2.3 PTR] - Amani'shi Tempest

### ISSUE THREAD

**Issue by Godmatik** [Atlantiss/NetherwingBugtracker#8783]
**Current behaviour**:
Missing ability Thunderclap

https://www.wowhead.com/wotlk/spell=44033/thunderclap

**Expected behaviour**: 
Should use ability Thunderclap:

![tclap](https://github.com/Atlantiss/NetherwingBugtracker/assets/37913400/5d0041ac-bdfc-4e36-aab1-4bd087e2c898)

**Server Revision**: 
3938

**Comment by Wolffenstein** [comment]
Fixed
