### ISSUE TITLE
[2.3 PTR] Soaring Eagle (Akil'zon fight)

### ISSUE THREAD

**Issue by Godmatik** [Atlantiss/NetherwingBugtracker#8784]
**Current behaviour**:
Soaring Eagle health set at 350

**Expected behaviour**: 
Should be closer to 3.5k (or more if you want to buff its health on heroic)

https://www.wowhead.com/tbc/npc=24858/soaring-eagle

**Server Revision**: 
3938

**Comment by Wolffenstein** [comment]
Fixed
