### ISSUE TITLE
[2.3 PTR] Amani'shi Axe Thrower - Axe Volley

### ISSUE THREAD

**Issue by Godmatik** [Atlantiss/NetherwingBugtracker#8785]
**Current behaviour**:
Amani'shi Axe Thrower will never use his Axe Volley ability as long as his primary threat (the tank) is in melee range of him

**Expected behaviour**: 
Even if the primary threat is in melee range - he should still use this ability.

https://www.wowhead.com/tbc/spell=42359/axe-volley
https://www.youtube.com/watch?v=googefOx9RA&t=615s

**Server Revision**: 
3938

**Comment by Wolffenstein** [comment]
He applies a periodic aura on himself that triggers the volley, but the throws will only go to targets 8-40yd away from him

SpellRange: (Id 94) "Sting":
    MinRange = 8
    MaxRange = 40

**Comment by Godmatik** [comment]
I had 2 bodies that were farther away, but he never cast axe volley once on them when the tank was in melee range of him, I think that is preventing him from doing so (but you can see in classic video he does do it)
