### ISSUE TITLE
[2.3 PTR] - Amani'shi Guardian - Missing two abilities

### ISSUE THREAD

**Issue by Godmatik** [Atlantiss/NetherwingBugtracker#8786]
**Current behaviour**:
Amani'shi Guardian is missing his Rend ability

In addition - the wowhead comments state in a couple of places that he should have a dispel for other mobs that are CCed. It's not on his spell list though

https://www.wowhead.com/tbc/npc=23597/amanishi-guardian#abilities;mode:n10

![Dispel](https://github.com/Atlantiss/NetherwingBugtracker/assets/37913400/5274fa89-116f-4b2f-a47b-5a89ba47abf2)

![poly](https://github.com/Atlantiss/NetherwingBugtracker/assets/37913400/de8421fe-8a39-425f-ab36-f123a80ce81b)

**Expected behaviour**: 
Should use rend ability
Should dispel CC of other mobs

**Server Revision**: 
3938

**Comment by Wolffenstein** [comment]
Fixed
