### ISSUE TITLE
[2.3 PTR] Amani'shi Trainer

### ISSUE THREAD

**Issue by Godmatik** [Atlantiss/NetherwingBugtracker#8787]
**Current behaviour**:
Amani'shi Trainer
1 - Does not appear to be using his Incite Frenzy ability on friendly dragonhawk
2 - Has a chance to use sleep ability on the tank with primary threat

https://www.wowhead.com/tbc/npc=23774/amanishi-trainer#abilities;mode:n10

**Expected behaviour**:
Should use Incite Frenzy on a friendly dragonhawk.
Should only use sleep on a non-tank target

**Server Revision**: 
3938

**Comment by Wolffenstein** [comment]
Fixed
