### ISSUE TITLE
[2.3 PTR] Jan'alai - Hatchers + Dragonhawks

### ISSUE THREAD

**Issue by Godmatik** [Atlantiss/NetherwingBugtracker#8788]
**Current behaviour**:
During the Jan'alai fight:

1. The health of both the hatcher and the dragonhawks spawned are even lower than classic values.
Current health of each: 4891
Classic health: 6896

2. In addition - the hatchers for the fight are spawning the dragonhawks way too fast, there is almost no delay between each set of eggs hatching.

**Expected behaviour**: 
Health should be increased of adds, probably even higher than classic for the heroic version.
The hatchers should hatch the eggs much slower

https://www.wowhead.com/tbc/npc=23598/amani-dragonhawk-hatchling
https://www.wowhead.com/tbc/npc=23818/amanishi-hatcher

https://www.youtube.com/watch?v=googefOx9RA&t=24m05s

**Server Revision**: 
3938

**Comment by Wolffenstein** [comment]
Fixed
