### ISSUE TITLE
[2.3 PTR] - Amani Lynx Cub stealth

### ISSUE THREAD

**Issue by Godmatik** [Atlantiss/NetherwingBugtracker#8789]
**Current behaviour**:
All Amani Lynx Cubs are stealthed before pulling them.

**Expected behaviour**: 
They should not be stealthed - even though it is on their wowhead spell list
Only the regular Amani Lynx should be stealthed

https://www.youtube.com/watch?v=googefOx9RA&t=26m15s
https://www.youtube.com/watch?v=tOvwKfQiO5g&t=15m05s

https://www.wowhead.com/tbc/npc=24064/amani-lynx-cub

**Server Revision**: 
3938

**Comment by Wolffenstein** [comment]
Fixed
