### ISSUE TITLE
The totem of infliction

### ISSUE THREAD

**Issue by Mewmewww** [Atlantiss/NetherwingBugtracker#879]
[//]: # (Enclose links to things related to the bug using http://wowhead.com or any other TBC database.)
[//]: # (You can use screenshot ingame to visual the issue.)
[//]: # (Write your tickets according to the format:)
[//]: # ([Quest][Azuremyst Isle] Red Snapper - Very Tasty!)
[//]: # ([NPC] Magistrix Erona)
[//]: # ([Spell][Mage] Fireball)
[//]: # ([Npc][Drop] Ghostclaw Lynx)
[//]: # ([Web] Armory doesnt work)

**Description**: Ghoul fang and skeleton fingers drop rate is alright, but vial of spider venom seems to be very low

**Current behaviour**: Very low droprate on Vial of Spider Venom

**Expected behaviour**: I'd assume i'd at least get 1 in 10 kills, but i don't even get that D:
Perhaps I was just extremely unlucky as I'm currently getting more now, but I won't close it and I'll keep it open for confirmation :)

**Server Revision**: 2083 NW

**Comment by aresbrutus** [comment]
The drop rates are correct, you just have gotten unlucky sadly.
