### ISSUE TITLE
[2.3 PTR] - Domesticate and Tamed Amani Crocolisk interactions

### ISSUE THREAD

**Issue by Godmatik** [Atlantiss/NetherwingBugtracker#8790]
**Current behaviour**:
When mind controlled by the Beast Tamer with his 'domesticate' ability, the Tamed Amani Crocolisk still attack you.

**Expected behaviour**: 
The crocolisk (nor any hostile mob) should not keep attacking you while you are mind controlled

https://www.wowhead.com/tbc/npc=24138/tamed-amani-crocolisk

**Server Revision**: 
3938

**Comment by Wolffenstein** [comment]
Fixed
