### ISSUE TITLE
[2.3 PTR] Hex Lord Malacrass - Drain Power

### ISSUE THREAD

**Issue by Godmatik** [Atlantiss/NetherwingBugtracker#8791]
**Current behaviour**:
Hex Lord did not once use 'drain power' ability during my testing of him.

Maybe it's because I was only testing with 3 bodies - but he should still use it regardless.

**Expected behaviour**: 
Should cast drain power at some point after each wave of Spirit Bolts.

https://www.wowhead.com/tbc/spell=44131/drain-power

**Server Revision**: 
3938

**Comment by Wolffenstein** [comment]
He needs to be at or under 80% hp to cast it
