### ISSUE TITLE
[2.3 PTR] - Amani'shi Scout - aggro link

### ISSUE THREAD

**Issue by Godmatik** [Atlantiss/NetherwingBugtracker#8792]
**Current behaviour**:
You can attack/nuke an Amani'shi Scout from ranged and it won't aggro the linked mobs if it is part of a pack

**Expected behaviour**: 
The scout should be linked with the other mobs if it's part of a pack

https://youtu.be/3qyQSrgpLsg?t=16m5s
(credit to Cillo for sharing from last server)

**Server Revision**: 
3938

**Comment by Wolffenstein** [comment]
Fixed
