### ISSUE TITLE
[2.3 PTR] - ZA Normal Mode - Prisoners not killed off

### ISSUE THREAD

**Issue by Godmatik** [Atlantiss/NetherwingBugtracker#8793]
**Current behaviour**:
The prisoners are not killed off when you have normal mode selected.
Although the timer is not shown - you can still kill the bosses in time, free the prisoner after talking to them, and receive the bonus loot

**Expected behaviour**: 
The prisoners should not be available to be freed in normal mode, and their loot should be inaccessible.

**Server Revision**: 
3938

**Comment by Wolffenstein** [comment]
Fixed
