### ISSUE TITLE
[2.3 PTR] Akil'zon Trash Gauntlet - NPC abilities/spawn timers

### ISSUE THREAD

**Issue by Godmatik** [Atlantiss/NetherwingBugtracker#8794]
The Akil'zon trash "gauntlet" needs some rework - it's a bit undertuned at the moment

**Currently**:
Amani Eagle - missing "Talon" ability
Amani'shi Warrior - missing both "Kick" and "Charge" abilities (they should charge someone random when running to you)

The Eagles first set of spawns happen too late + the new waves after spawn much too slow. 
The first set of warriors spawn too early.

**How it should work**:
After watching some ZA videos, it should be more like this

After alerting the lookout:
First Amani eagle should spawn @ ~30 seconds, and every ~45 seconds after
First Warriors spawn @ ~45 seconds, and every ~60 seconds after

Amani Eagle and Amani'shi Warrior should have abilities linked below (currently missing)

https://www.wowhead.com/tbc/spell=43517/talon
https://www.wowhead.com/tbc/npc=24225/amanishi-warrior#abilities;mode:n10

![Talon](https://github.com/Atlantiss/NetherwingBugtracker/assets/37913400/1d207232-5930-44e8-b86b-650563f909f8)

https://www.youtube.com/watch?v=y36NymVkYFE

**Comment by Wolffenstein** [comment]
Fixed
