### ISSUE TITLE
[2.3 PTR] - Akil'zon

### ISSUE THREAD

**Issue by Godmatik** [Atlantiss/NetherwingBugtracker#8795]
**Current behaviour**:
1. Enrage timer is set at 10 minutes
2. If birds are left alive for too long - they occasionally glitch out and don't fly back up after charging someone
3. A sound file he does is missing when he goes enrage

**Expected behaviour**: 
1. Should be 8 min enrage timer (DBM file says 10 minutes, based on my research that's not correct)
2. Birds should not glitch out
3. Should play the below sound file when enraging

Enrage sound:
https://www.wowhead.com/tbc/sound=12016/a-zulaman-akilzonberserk

Birds:
![WoWScrnShot_121823_170855](https://github.com/Atlantiss/NetherwingBugtracker/assets/37913400/f0c20863-8685-4481-88ab-d42467bf2f7e)

Enrage Timer (from one source) - wowwiki + other sources say basically the same thing, hard to find exact data since hardly anyone wipes to it...

![Enrage](https://github.com/Atlantiss/NetherwingBugtracker/assets/37913400/0ba1491a-9749-4f2c-9e9e-8b0091e56ddc)

**Comment by Wolffenstein** [comment]
Fixed
