### ISSUE TITLE
[2.3 PTR] Incite Frenzy

### ISSUE THREAD

**Issue by Godmatik** [Atlantiss/NetherwingBugtracker#8796]
**Current behaviour**:
The Amani'shi trainer always casts "Incite Frenzy" on himself, but he is an invalid target since he isn't a beast, so nothing happens

![incite](https://github.com/Atlantiss/NetherwingBugtracker/assets/37913400/ee8aeb88-4480-46ca-8081-91e789d0a487)

**Expected behaviour**: 
He should be casting this on a dragonhawk (eligible target), or not using it at all if there are no dragonhawks

https://www.wowhead.com/tbc/spell=43292/incite-frenzy#comments

**Comment by Wolffenstein** [comment]
Fixed
