### ISSUE TITLE
[2.3 PTR] - Startling Roar

### ISSUE THREAD

**Issue by Godmatik** [Atlantiss/NetherwingBugtracker#8797]
**Current behaviour**:
Amani'shi Guardian only uses 'startling roar' the first second or two after aggro, so only works if a CC is applied right away on pull

**Expected behaviour**: 
They should use the ability more often and/or use it when they detect a friendly target is in CC, I think?

https://www.wowhead.com/tbc/spell=43249/startling-roar

**Comment by Godmatik** [comment]
Hardly anyone on classic CCed this shit so it's hard to find details but here's one I found - one of the guardians dispelled a sheep about ~10 seconds after pull

https://www.youtube.com/watch?v=BdfGReokLQs&t=23m05s

**Comment by Wolffenstein** [comment]
Fixed
