### ISSUE TITLE
[2.3 PTR] Zul'jin - couple issues

### ISSUE THREAD

**Issue by Godmatik** [Atlantiss/NetherwingBugtracker#8799]
**Current behaviour:**
1. Ability "overpower" Zul'jin uses in bear form, seems undertuned, deals less than an auto-attack worth of damage, tooltip seems to indicate it should be more?
2. No sound clip when he goes berserk at 10 mins
3. During eagle phase, the spirits were making a bunch of noise and moving while the tornados were out

**Expected behaviour:**
1. Overpower should deal more than auto-attack damage (?)
https://www.wowhead.com/tbc/spell=43456/overpower

2. Sound clip for Berserk at 10 mins (linked below, can't find one for Zul'jin, only the Cata one)
https://www.wowhead.com/sound=24221/vo-za2-daakara-berserk

3. Spirits should just chill and watch the show
https://streamable.com/67t3iv

EDIT:
Classic TBC log of overpower

![overpower](https://github.com/Atlantiss/NetherwingBugtracker/assets/37913400/8711e4f8-0afb-4a13-be44-ea51bd4824cd)

**Comment by Godmatik** [comment]
also looking at classic video, looks like the 'spirit' should fully die after it gives its essence to zul'jin (or whatever...)

**Comment by Wolffenstein** [comment]
Fixed
