### ISSUE TITLE
[Spell] Cat Form/Prowl combat log

### ISSUE THREAD

**Issue by totaemoeggerli** [Atlantiss/NetherwingBugtracker#880]
[//]: # (Enclose links to things related to the bug using http://wowhead.com or any other TBC database.)
[//]: # (You can use screenshot ingame to visual the issue.)
[//]: # (Write your tickets according to the format:)
[//]: # ([Quest][Azuremyst Isle] Red Snapper - Very Tasty!)
[//]: # ([NPC] Magistrix Erona)
[//]: # ([Spell][Mage] Fireball)
[//]: # ([Npc][Drop] Ghostclaw Lynx)
[//]: # ([Web] Armory doesnt work)

**Description**: 
Combat log displays 4 lines  consistently whenever I enter cat form.
Prowl displays either 2 or 3 lines when activated.
https://imgur.com/a/t2rbbcG

**Current behaviour**:
Copy Paste from combat log
```
Angustin's Cat Form is refreshed.
Angustin's Cat Form is refreshed.
Angustin's Cat Form is refreshed.
Angustin gains Cat Form.
```
```
Angustin's Prowl is refreshed.
Angustin's Prowl is refreshed.
Angustin gains Prowl. 
```

**Expected behaviour**: 
I don't think this is how it should be. It's odd that there is inconsistency with Prowl. However, I do not know if this has any affect on gameplay but it seems noteworthy to me.

**Server Revision**: 2083

**Comment by anonyReporter** [comment]
This is the same with seals on Paladins. Will post a screenshot soon.

**Comment by Wolffenstein** [comment]
It has no effect on gameplay
