### ISSUE TITLE
[2.3 PTR] Some small Harrison Jones fixes

### ISSUE THREAD

**Issue by Godmatik** [Atlantiss/NetherwingBugtracker#8800]
1. When starting ZA event - Harrison Jones (24358) currently says "at least 3 of you must assist me", should instead say "at least 5 of you must assist me", maybe he is saying his Cata script?

2. Also, when you talk to him to start the event, he should run full speed straight to the gong. Currently walks slowly to it.

![HarrisonJones](https://github.com/Atlantiss/NetherwingBugtracker/assets/37913400/2be6a94d-f96f-41f5-bc0a-600d4f3d3859)

Classic video showing both of these:
https://www.youtube.com/watch?v=5YjPHwv0HD4&t=25s

**Comment by Wolffenstein** [comment]
Fixed
