### ISSUE TITLE
[2.3 PTR] Koragg and Slither (Hex Lord adds)

### ISSUE THREAD

**Issue by Godmatik** [Atlantiss/NetherwingBugtracker#8804]
**Current behaviour**:
Cold stare ability from Koragg
- Does not jump to raid member after spell/ability is used, it expires after 1 use

Slither - only spams Venom Spit

**Expected behaviour**: 
Cold stare should jump to friendly raid member after spell or ability is used until the stacks expire or is dispelled

Slither should be doing melee attacks with chance to cast deadly poison. Cooldown possibly missing on Venom Spit ability.

https://www.wowhead.com/tbc/spell=43593/cold-stare
https://www.wowhead.com/tbc/npc=24242/slither

classic log:
![Slither](https://github.com/Atlantiss/NetherwingBugtracker/assets/37913400/9175a331-763e-462d-80a2-ca34fb08bec5)

**Comment by Wolffenstein** [comment]
Fixed
