### ISSUE TITLE
[2.3 PTR] Quest - Tuskin' Raiders

### ISSUE THREAD

**Issue by Godmatik** [Atlantiss/NetherwingBugtracker#8808]
**Current behaviour**:
Can pick up this quest right away

**Expected behaviour**: 
Should require pre-req completion of "Promises, Promises..."

https://www.wowhead.com/tbc/quest=11132/promises-promises
https://www.wowhead.com/tbc/quest=11164/tuskin-raiders

![prereq](https://github.com/Atlantiss/NetherwingBugtracker/assets/37913400/2da3abfb-a0d6-4d6f-a8a4-ed710ecd7894)

**Comment by Wolffenstein** [comment]
Fixed
