### ISSUE TITLE
[2.3 PTR] NPC "Griftah" missing

### ISSUE THREAD

**Issue by Godmatik** [Atlantiss/NetherwingBugtracker#8809]
**Current behaviour**:
Can't find this NPC in Shattrath, neither on live realm or PTR

**Expected behaviour**: 
He sells useless jewelry but also starts the following ZA quest (optional breadcrumb) + allows you to finish Playing' With Dolls quest

https://www.wowhead.com/tbc/quest=11130/oooh-shinies
https://www.wowhead.com/tbc/npc=19227/griftah
https://www.wowhead.com/tbc/quest=11195/playin-with-dolls

**Comment by Wolffenstein** [comment]
Fixed
