### ISSUE TITLE
[NPC] Stitches - evades combat

### ISSUE THREAD

**Issue by Buggyswires** [Atlantiss/NetherwingBugtracker#881]
[//]: # (Enclose links to things related to the bug using http://wowhead.com or any other TBC database.)
[//]: # (You can use screenshot ingame to visual the issue.)
[//]: # (Write your tickets according to the format:)
[//]: # ([Quest][Azuremyst Isle] Red Snapper - Very Tasty!)
[//]: # ([NPC] Magistrix Erona)
[//]: # ([Spell][Mage] Fireball)
[//]: # ([Npc][Drop] Ghostclaw Lynx)
[//]: # ([Web] Armory doesnt work)

**Description**: 
[NPC] Stitches - evades combat

**Current behaviour**:
Stitches (ID 412) evades combat after killing Watcher Jordan (ID 887)

https://youtu.be/D_fLPwvSMY4

**Expected behaviour**: 
He should continue to invade Darkshire

**Server Revision**:

**Comment by Tereneckla** [comment]
Fixed
