### ISSUE TITLE
[2.3 PTR] Drums not updated

### ISSUE THREAD

**Issue by Godmatik** [Atlantiss/NetherwingBugtracker#8810]
**Current behaviour**:
Drums of Battle, Drums of Restoration, Drums of War, Drums of Speed still have 1 second cast time and 10 yard range on 2.3 PTR

29529, 29531, 29528, 29530

**Expected behaviour**: 
Starting in patch 2.3, they should be instant cast and 40 yard range

(still says 1 sec cast-time on wowhead because blizzard changed how it works for classic and added the 'greater' drums)

**Comment by Wolffenstein** [comment]
Remind me to do it during 2.3 launch since I have to do it manually

**Comment by Wolffenstein** [comment]
Fixed
