### ISSUE TITLE
[2.3 PTR] Drain Power ability - Hex Lord

### ISSUE THREAD

**Issue by Godmatik** [Atlantiss/NetherwingBugtracker#8812]
**Current behaviour**:
Hex Lord currently uses his drain power always right after spirit bolts (if he is below 80% health). This means the first drain power use can be delayed unintentionally if he is brought below 80% well before the next spirit bolt cast

**Expected behaviour**: 
He should use his drain power ability immediately once he hits 80% health - and then use it again every 30 seconds
(If he is mid-cast spirit bolts when brought below the threshold - he uses it right after it is finished)

Cast @ 80%:
https://www.youtube.com/watch?v=googefOx9RA&t=52m20s
30 seconds later:
https://www.youtube.com/watch?v=googefOx9RA&t=52m50s

![Drain](https://github.com/Atlantiss/NetherwingBugtracker/assets/37913400/f0476d20-457f-4580-bbcb-fe012234d8e4)

https://www.wowhead.com/tbc/spell=44131/drain-power

**Comment by Wolffenstein** [comment]
Fixed
