### ISSUE TITLE
Illidan - No shear animation under certain circumstances

### ISSUE THREAD

**Issue by Godmatik** [Atlantiss/NetherwingBugtracker#8815]
**Current behaviour**:
If Illidan attempts to cast Shear and
1 - Has soft enrage active (maybe hard enrage as well dunno)
2- Is moving
There will be no shear animation done

https://clips.twitch.tv/ChillySingleSrirachaFailFish-T2Vo1X3yvSchKG0C

**Expected behaviour**: 
There should be shear animation done always when it is cast.

It was reported as well here:
https://github.com/Atlantiss/NetherwingBugtracker/issues/6320

**Server Revision**: 
3940

**Comment by Wolffenstein** [comment]
animations are clientside
