### ISSUE TITLE
Formula: Enchant Weapon - Major Spellpower

### ISSUE THREAD

**Issue by Godmatik** [Atlantiss/NetherwingBugtracker#8817]
**Current behaviour**:
Requires you to have 350 enchanting before the recipe is able to drop

**Expected behaviour**: 
Per wowhead comments, all you need is enchanting for it to drop, you don't need 350

![350](https://github.com/Atlantiss/NetherwingBugtracker/assets/37913400/6fead6ad-10cc-4312-a2b0-bca2c969d1d4)

![3502](https://github.com/Atlantiss/NetherwingBugtracker/assets/37913400/d282f81a-9fd8-41ee-8d78-2b7dfcfa02bc)

**Server Revision**: 
3940

**Comment by Wolffenstein** [comment]
Fixed in rev 3942.
