### ISSUE TITLE
Tome of Divinity

### ISSUE THREAD

**Issue by Godmatik** [Atlantiss/NetherwingBugtracker#8818]
**Current behaviour**:
Human quest for Resurrect

If you turn in quest "The Tome of Divinity", book is put in your bags, but you abandon the quest, you will no longer have a book at all, and can't get a new one from the NPC, only a GM can assist you at this point.

**Expected behaviour**: 
Should be able to get new book from questgiver if you abandon the quest or delete the book

https://www.wowhead.com/wotlk/item=6775/tome-of-divinity#comments

![tome](https://github.com/Atlantiss/NetherwingBugtracker/assets/37913400/926fbecb-2eb2-4a4c-aab1-faf9fc327aeb)

**Server Revision**: 
3940

**Comment by EtheriousNW** [comment]
fix is live
