### ISSUE TITLE
([NPC] Shadowpine Catlords - Pet does only regain health back very slowly - normal?

### ISSUE THREAD

**Issue by Rebelyna** [Atlantiss/NetherwingBugtracker#882]
**Current behaviour**:
The pets of the Shadowpine Catlords only regain their health back very slowly after dropping out of combat, making it possible to reattack them at low health when they reach their original spot.

**Expected behaviour**: 
NPC pets should regain their health back at the same rate as their master when dropping out of combat.

**Server Revision**: 
2083

**Comment by The14me** [comment]
May need other rework
Same issue https://github.com/Atlantiss/NetherwingBugtracker/issues/169

**Comment by Tenoutoften** [comment]
This is a core issue and happens globally.
I recorded it [here](https://www.youtube.com/watch?v=AOZKWV0j1D0&feature=youtu.be), server rev 2395

**Comment by Tereneckla** [comment]
Go to #293
