### ISSUE TITLE
[2.3 PTR] - Jan'ali double fire breath

### ISSUE THREAD

**Issue by Godmatik** [Atlantiss/NetherwingBugtracker#8820]
**Current behaviour**:
Jan'ali will occasionally cast a second fire breath immediately after doing a first fire breath, which has the potential to one shot someone with back-to-back damage

**Expected behaviour**: 
Should not do double breath

https://clips.twitch.tv/DeadGiftedGrasshopperPunchTrees-Bgk0N7HgXPlQOT5Q

https://www.wowhead.com/tbc/spell=43140/flame-breath

**Comment by Wolffenstein** [comment]
Fixed
