### ISSUE TITLE
[2.3 PTR] Hex Lord not doing drain power at all

### ISSUE THREAD

**Issue by Godmatik** [Atlantiss/NetherwingBugtracker#8821]
**Current behaviour**:
After a recent fix you did, Hex Lord now no longer casts Drain Power buff/debuff.
Was it perhaps because we pushed him to 80% while he was doing spirit barrage? (If that situation occurs, he should cast it immediately after it is over)

(https://clips.twitch.tv/SmallEvilDillTheTarFu-w-hMcvcWQW-x3Cc-)

**Comment by Wolffenstein** [comment]
Fixed
