### ISSUE TITLE
[2.3] PTR - Zul'jin - Energy Storm - Channeled abilities

### ISSUE THREAD

**Issue by Godmatik** [Atlantiss/NetherwingBugtracker#8823]
**Current behaviour**:
During Zul'jin's Eagle phase - you can use channeled abilities (such as arcane missiles) and take no damage.

**Expected behaviour**: 
Channeled spells should still proc the energy storm, one blast of damage for every tick that occurs

![ticks](https://github.com/Atlantiss/NetherwingBugtracker/assets/37913400/88488476-4ca6-42d9-8c8e-212e8aed7246)

**Comment by Wolffenstein** [comment]
This comment does not match the proc flags of the spell and it doesn't make much sense for it to work that way. I don't trust it one bit, you would have to find a classic video to prove it.

 16384 (0x4000) - Deal Helpful Spell
 65536 (0x10000) - Deal Harmful Spell
