### ISSUE TITLE
[2.3 PTR] - Amani'shi Flame Caster - Conflagration

### ISSUE THREAD

**Issue by Godmatik** [Atlantiss/NetherwingBugtracker#8825]
**Current behaviour**:
Amani'shi Flame Caster keeps trying to use an ability called Conflagration but nothing happens when used

**Expected behaviour**: 
I am pretty sure this was added in their Cata version, can't find any evidence of this ability in TBC videos. Just need to remove it from their spell list or deactivate them from using it (right now it's just a visual anyway and nothing happens)

https://www.wowhead.com/tbc/npc=23596/amanishi-flame-caster#abilities;mode:n10

**Comment by Wolffenstein** [comment]
Fixed in rev 3942.
