### ISSUE TITLE
Talent: Feral Aggression 

### ISSUE THREAD

**Issue by Raferty** [Atlantiss/NetherwingBugtracker#8828]
**Description**: 
Talent **Feral Aggression** doesnt'work

**Current behaviour**: 
5/5 talent decrease 248 ap

**Expected behaviour**:  
Should decrease +40% ap. 248 + 99.2(40%) = 347.2

**Server Revision**:  3940

5/5 
![Screenshot_18](https://github.com/Atlantiss/NetherwingBugtracker/assets/5391023/ef10de19-ff45-409a-a4cc-c6739c49c38a)

0/5
![Screenshot_19](https://github.com/Atlantiss/NetherwingBugtracker/assets/5391023/1896ae7c-b71d-4f8a-a95f-9597abb7cd18)

**Comment by Godmatik** [comment]
The bonus from talents is not shown on buff/debuff tooltip, this is blizzlike.

Same is true for example buff yourself with mark of the wild, and you have improved from talents, it will tell you stats of base mark of the wild, but the actual improved stats are applied.
