### ISSUE TITLE
[2.3 PTR] Jan'alai - resetting him

### ISSUE THREAD

**Issue by Godmatik** [Atlantiss/NetherwingBugtracker#8829]
**Current behaviour**:
When you reset Jan'alai - any dragonhawks still alive from the fight do not despawn.

https://clips.twitch.tv/HotStormyEmuRitzMitz-8fIgvTFrHwHDadeF

**Expected behaviour**: 
The dragonhawks and hatchers should despawn as well when resetting the fight

**Comment by Wolffenstein** [comment]
Fixed
