### ISSUE TITLE
Ward of Laze (totem) has mob AI.

### ISSUE THREAD

**Issue by Jezofine** [Atlantiss/NetherwingBugtracker#883]
**Current behaviour**:
[Ward of Laze](https://www.wowhead.com/npc=2667/ward-of-laze) used by [Mosh'Ogg Witch Doctor](https://www.wowhead.com/npc=1144/moshogg-witch-doctor#comments) can be afflicted and destoryed by dots, can be feared and will run around.

**Expected behaviour**:
Totems can be destroyed only by direct damage attack/spells, but not by tick or aoe damage; cannot be affected by fear.

**Server Revision**: 2083

**Comment by The14me** [comment]
Related 
https://github.com/Atlantiss/AtlantissTBCBT/issues/2375
https://github.com/Atlantiss/AtlantissTBCBT/issues/2081

**Comment by Retinus** [comment]
Adding that totem stays alive even if you kill the mob

**Comment by xmesaj2** [comment]
fixed in rev 2334
