### ISSUE TITLE
BT - Illidari Nightlord Shadow Inferno

### ISSUE THREAD

**Issue by Godmatik** [Atlantiss/NetherwingBugtracker#8831]
**Current behaviour**:
Illidari Nightlord's "Shadow Inferno" ability deals too low of damage

**Expected behaviour**: 
The Shadow Inferno ability should deal increasing damage with every tick

https://www.wowhead.com/tbc/spell=39645/shadow-inferno

![Inferno](https://github.com/Atlantiss/NetherwingBugtracker/assets/37913400/152145d1-1f70-4aa4-b303-f1458ebef373)

**Server Revision**: 
3940

**Comment by Wolffenstein** [comment]
Fixed in rev 3942.
