### ISSUE TITLE
[2.3 PTR] Normal mode default for raid group

### ISSUE THREAD

**Issue by Godmatik** [Atlantiss/NetherwingBugtracker#8833]
**Current behaviour**:
When you create a raid group from a party - your dungeon difficulty automatically switches to normal (even if it was set to heroic before converting to raid).

https://streamable.com/iz832v

**Expected behaviour**: 
Consider having it either remain on the difficulty it was before it is converted to raid - or default it to heroic after raid conversion (for ZA)

**Comment by Wolffenstein** [comment]
Fixed
