### ISSUE TITLE
[2.3 PTR] Resetting Zul'jin

### ISSUE THREAD

**Issue by Godmatik** [Atlantiss/NetherwingBugtracker#8834]
When you pull the Amani'shi Savages in front of Zul'jin and he resets - the savages don't reset. 

Which causes the resulting odd behavior as you can see while you are killing the savages (he keeps engaging and instant resetting):

https://clips.twitch.tv/AcceptableSmoggyPuffinPogChamp-FYxxxxMOQkylRZrs

**Comment by Wolffenstein** [comment]
Fixed
