### ISSUE TITLE
Flask of Petrification

### ISSUE THREAD

**Issue by Godmatik** [Atlantiss/NetherwingBugtracker#8837]
**Current behaviour**:
When used - Flask of Petrification will also drop any aggro onto you, similar to Divine Intervention, and if you are only one with aggro, the mobs will drop combat and reset.

**Expected behaviour**: 
Although you are invulnerable  - after the flask effect ends any aggro you had should be restored. The mobs should keep attacking you if there is no other target (similar to Divine Shield)

If entire group or raid uses petri flasks, it should not cause the mobs to evade/reset

https://www.wowhead.com/classic/item=13506/flask-of-petrification

![aggro](https://github.com/Atlantiss/NetherwingBugtracker/assets/37913400/4b122506-c665-4172-9fc6-c42fe6bb88bc)

**Server Revision**: 
3940

**Comment by Wolffenstein** [comment]
![image](https://github.com/Atlantiss/NetherwingBugtracker/assets/1576644/7ac8808f-9f07-4b50-8fa6-35d1adc77f16)

**Comment by Wolffenstein** [comment]
![image](https://github.com/Atlantiss/NetherwingBugtracker/assets/1576644/4638c5df-8a5f-43b3-835d-f0812a028fbb)

**Comment by Wolffenstein** [comment]
![image](https://github.com/Atlantiss/NetherwingBugtracker/assets/1576644/de19754a-964a-4659-adcd-23a4954c3bbd)
