### ISSUE TITLE
[2.3 PTR] Jan'alai Hatcher, dragonhawk spawn from wrong side

### ISSUE THREAD

**Issue by Godmatik** [Atlantiss/NetherwingBugtracker#8838]
**Current behaviour**:
Sometimes - a hatcher will hatch an egg + a dragonhawk spawns on the other side of eggs from where he is

https://clips.twitch.tv/FairTastyTurnipTooSpicy-NKwiG_LrNPBxJ0iG

Was reported last server as well - seems rare and not sure how to reproduce though:
https://github.com/Atlantiss/NetherwingBugtracker/issues/7919

**Comment by Wolffenstein** [comment]
Fixed in rev 3944.
