### ISSUE TITLE
Dark Coffer Runs not possible

### ISSUE THREAD

**Issue by Beefcurtain** [Atlantiss/NetherwingBugtracker#8839]
[//]: https://www.wowhead.com/classic/guide/blackrock-depths-brd-dark-coffer-run

**Description**: Just curious if Dark Coffer Runs are possible in Blackrock Depths. I went in last night, clicked on the 'Dark Keeper Portrait' but wasn't able to click on the 'Dark Keeper Nameplate' which is what activates the spawn of one of I think 6 Dark Keepers. I'd like to be able to get the 'Lesser Arcanum of Resilience' which isn't possible without acquiring a 'Burning Essence' from the dark coffer. 

**Current behaviour**: No Magnifying Glass icon appears on the 'Dark Keeper Nameplate' location after opening the 'Dark Keeper Portrait' therefore not spawning one of 6 dark keepers somewhere in the instance

**Expected behaviour**: Magnifying Glass Icon should appear after opening the 'Dark Keeper Portrait' notifying you which keeper has spawned and where he is located.

![WoWScrnShot_122923_070309](https://github.com/Atlantiss/NetherwingBugtracker/assets/155174940/ad431fdf-622f-4e82-a6aa-5eaecdea0a9b)

**Comment by Beefcurtain** [comment]
https://www.wowhead.com/classic/guide/blackrock-depths-brd-dark-coffer-run

**Comment by Godmatik** [comment]
Known issue

https://github.com/Atlantiss/NetherwingBugtracker/issues/7978
https://github.com/Atlantiss/NetherwingBugtracker/issues/1471

A full rescripting of BRD is on the main developer's to-do list, a lot of the dungeon needs rework

**Comment by Beefcurtain** [comment]
Id imagine that since this is a known issue since 2018 that its likely to not get fixed any time soon. Thanks for the update Matik!
