### ISSUE TITLE
Escort quest

### ISSUE THREAD

**Issue by Stilstkin** [Atlantiss/NetherwingBugtracker#884]
[//]: # (Enclose links to things related to the bug using http://wowhead.com or any other TBC database.)
[//]: # (You can use screenshot ingame to visual the issue.)
[//]: # (Write your tickets according to the format:)
[//]: # ([Quest][Azuremyst Isle] Red Snapper - Very Tasty!)
[//]: # ([NPC] Magistrix Erona)
[//]: # ([Spell][Mage] Fireball)
[//]: # ([Npc][Drop] Ghostclaw Lynx)
[//]: # ([Web] Armory doesnt work)

**Description**:  If you fail an escort quest and abandon it, you cant get it again, no quest mark above NPC

**Current behaviour**: Cant get the quest again after failing and Abandoning it

**Expected behaviour**: You should be able to do it as manya times until you finish it

**Comment by totaemoeggerli** [comment]
same issue here https://github.com/Atlantiss/NetherwingBugtracker/issues/365 and here https://github.com/Atlantiss/NetherwingBugtracker/issues/381
