### ISSUE TITLE
Bug Quest line Blacksmithing WeaponMaster 

### ISSUE THREAD

**Issue by Opsy05** [Atlantiss/NetherwingBugtracker#8841]
![WoWScrnShot_010124_134552](https://github.com/Atlantiss/NetherwingBugtracker/assets/155367594/40053fe7-9d74-470a-ba95-23e06be5d0ab)

(https://www.wowhead.com/tbc/npc=11176/krathok-moltenfist)

iI don't see any Q on the Blacksmithing profession for weaponMaser specialization

**Comment by Godmatik** [comment]
Its not bugged many people are weaponsmiths.

Open a GM ticket ingame, they can assist you

**Comment by Godmatik** [comment]
Ok I take it back, it is bugged.

Looks like it's related to dropping armorsmith and switching specializations.

https://github.com/Atlantiss/NetherwingBugtracker/issues/2896
