### ISSUE TITLE
[2.3 PTR] Amani Snake

### ISSUE THREAD

**Issue by Godmatik** [Atlantiss/NetherwingBugtracker#8846]
**Current behaviour**:
Amani Snakes spawned from Snake trap in Hex Lord fight, melee for single digit damage and don't do any abilities

**Expected behaviour**: 
https://www.wowhead.com/wotlk/npc=24338/amani-snake#abilities;mode:n10

**Comment by Wolffenstein** [comment]
Fixed in rev 3948.
