### ISSUE TITLE
[2.3 PTR] New frog NPCs don't do anything when freed

### ISSUE THREAD

**Issue by Godmatik** [Atlantiss/NetherwingBugtracker#8847]
**Current behaviour**:
https://github.com/Atlantiss/NetherwingBugtracker/issues/8807

When one of those 4 NPCs are freed - nothing happens

https://streamable.com/0bj4fo

**Expected behaviour**: 
They should say stuff + give you goodies

**Comment by Wolffenstein** [comment]
Fixed in rev 3948.
