### ISSUE TITLE
Interact cursor with objects - lights up at wrong distance

### ISSUE THREAD

**Issue by Godmatik** [Atlantiss/NetherwingBugtracker#8849]
**Current behaviour**:
I noticed that when you interact with an object, typically for gathering something for quest, it lights up at the wrong distance away. 

When you attempt to collect the item, you get an "out of range" error and need to move in slightly closer

https://streamable.com/mpjtl5

**Expected behaviour**: 
Either the distance to loot objects needs to be increased, or (more than likely) the interact cursor changing colors need to be fixed to the appropriate distance

**Server Revision**: 
3951

**Comment by Wolffenstein** [comment]
Video doesn't work

**Comment by Godmatik** [comment]
Deleted it at some point, will reopen when I test again and have a new one
