### ISSUE TITLE
[Quest][NPC] Test of Endurance/Grenka Bloodscreech

### ISSUE THREAD

**Issue by totaemoeggerli** [Atlantiss/NetherwingBugtracker#885]
[//]: # (Enclose links to things related to the bug using http://wowhead.com or any other TBC database.)
[//]: # (You can use screenshot ingame to visual the issue.)
[//]: # (Write your tickets according to the format:)
[//]: # ([Quest][Azuremyst Isle] Red Snapper - Very Tasty!)
[//]: # ([NPC] Magistrix Erona)
[//]: # ([Spell][Mage] Fireball)
[//]: # ([Npc][Drop] Ghostclaw Lynx)
[//]: # ([Web] Armory doesnt work)

**Description**: 
Only [Grenka Bloodscreech](https://www.wowhead.com/quest=1150/test-of-endurance#comments) should spawn when opening the boxes. 
And she uses Deafening Screech too often or duration is to high.
She is part of the quest [Test of Endurance](https://www.wowhead.com/quest=1150/test-of-endurance#comments).

**Current behaviour**:
3 waves of harpys spawn when you open the chest. [She uses her silencing ability too often](https://gfycat.com/FrightenedSplendidAfricanjacana). The debuff that runs out at the start of the clip is from another mob.

**Expected behaviour**: 
Fugu on 2008/01/13 (Patch 2.3.2)
> verified. as of 2.3, only grenka spawns when you break the crates. 

Didn't find any information on the Deafening Screech. You can see in the clip that it has a druation of 8sec and she cast it again after  about 11sec.  This seems abit too powerful/not intended.

**Server Revision**: 2083

**Comment by aresbrutus** [comment]
Confirmed that her screen CD should be higher, but the version will be likely kept.

**Comment by Jezofine** [comment]
There are multiple waves of harpies
[Wowhead comments]9https://www.wowhead.com/quest=1150/test-of-endurance#comments)

**Comment by Evolvee** [comment]
rev Xd

**Comment by totaemoeggerli** [comment]
Reopen this issue please. I wasn't clear enough that there are two issues. One is fixed the other isn't.
With the changes to group quests in 2.3 only Grenka Bloodscreech should spawn.

> By ajenia (433 – 1·4) on 2007/11/14 (Patch 2.3.0)
`This quest is no longer classified as a group quest or as needing 2 players..with the recent patch they made it a solo-able quest now. Grenka is lvl 30 now and easy kill.  `

>Zhifu on 2007/11/15 (Patch 2.3.0)
`Yep, no waves at all now. Just fight your way there, pop a box and she'll come all by herself.`

https://clips.twitch.tv/InexpensiveSavoryManateePanicVis not me btw

**Server Rev:** 2229

**Comment by Evolvee** [comment]
@aresbrutus give me entry/gps of these barrels...

**Comment by aresbrutus** [comment]
```
[Harpy Foodstuffs]
ENTRY: 20447 ID: 3
```

**Comment by Evolvee** [comment]
rev yummy
