### ISSUE TITLE
Demonfork wrong working

### ISSUE THREAD

**Issue by Perva4** [Atlantiss/NetherwingBugtracker#8851]
[//]: # https://www.wowhead.com/wotlk/item=12621/demonfork#comments
[//]: #https://imgur.com/a/w0hK2R5
[//]: # (Write your tickets according to the format:)
[//]: # weapon demonfork don't have scaling with spell power.
[//]: # -
[//]: # 
[//]: # 
[//]: # 
[//]: # 

**Description**: this weapon must have scaling with spell power 10%

**Current behaviour**:

**Expected behaviour**: 

**Server Revision**:

**Comment by Wolffenstein** [comment]
Fixed in rev 3956.
