### ISSUE TITLE
Druid - Faerie Fire

### ISSUE THREAD

**Issue by ghost** [Atlantiss/NetherwingBugtracker#8852]
.

**Comment by Wolffenstein** [comment]
![image](https://github.com/Atlantiss/NetherwingBugtracker/assets/1576644/c2e09da6-08db-45ad-bc9b-bb22c7b3d710)
Which ranks did you test it on? For me I either overwrite the current one with a more powerful spell or am unable to cast a weaker one.

**Comment by Wolffenstein** [comment]
Fixed
