### ISSUE TITLE
ZA - Nalorakk sometimes can not be engaged

### ISSUE THREAD

**Issue by Godmatik** [Atlantiss/NetherwingBugtracker#8854]
**Current behaviour**:
On the final trash pack before Nalorakk (bear boss) - if you mind control one of the Medicine Men, and allow the other mobs to kill it (so the NPCs get the killing blow on him essentially), after clearing the trash pack - Nalorakk will not be able to be engaged. The group will have to soft reset the raid to fix.

Rev 3955

**Comment by Wolffenstein** [comment]
Fixed in rev 3956.
