### ISSUE TITLE
Zuljin - Visual bug between phases

### ISSUE THREAD

**Issue by Godmatik** [Atlantiss/NetherwingBugtracker#8855]
**Current behaviour**:
During transition between Lynx Phase and Dragonhawk phase - if Zuljin begins casting Claw Rage right as transition occurs @ 20%, the RP for him to transform won't occur and he will visually appear in human for for rest of fight. 

Have seen it twice now.

https://www.youtube.com/watch?v=4MKmMtPfLoA&t=2h9m30s

![VisualBug](https://github.com/Atlantiss/NetherwingBugtracker/assets/37913400/62b5b011-e85f-4ecc-9396-d7e23b54c6f7)

Rev 3955

**Comment by Wolffenstein** [comment]
Fixed in rev 3956.
