### ISSUE TITLE
SH Heroic -  Ravenguards after first boss join the fight when engaging (Reopen)

### ISSUE THREAD

**Issue by Godmatik** [Atlantiss/NetherwingBugtracker#8856]
You closed last issue but it's not resolved (per post I saw on discord)

https://github.com/Atlantiss/NetherwingBugtracker/issues/8341

The issue appears to be caused because the warrior tank is using spell reflect on the boss's chain lightning ability, and apparently the chain part has unlimited range and pulls in other mobs.

Rev 3955

**Comment by Wolffenstein** [comment]
Fixed in rev 3956.
