### ISSUE TITLE
ZA Quest - "Promises, Promises"

### ISSUE THREAD

**Issue by Godmatik** [Atlantiss/NetherwingBugtracker#8858]
**Current behaviour**:
Budd's map despawns after several minutes of the first person looting it. 

It will instant respawn after loot - but after some time eventually will just despawn for rest of ID

https://www.wowhead.com/tbc/item=33013/budds-map-of-zulaman

**Expected behaviour**: 
Budd's map should never full despawn. After it respawns it should stay spawned.

**Server Revision**: 
3955

**Comment by Wolffenstein** [comment]
Fixed in rev 3956.
