### ISSUE TITLE
Zul'jin Eagle Phase - no zap on arcane missiles

### ISSUE THREAD

**Issue by Godmatik** [Atlantiss/NetherwingBugtracker#8859]
**Current behaviour**:
If a mage casts arcane missiles during the Eagle phase of Zul'jin, he never gets zapped by any of the tornadoes

**Expected behaviour**: 
A mage should get zapped one time when he casts arcane missiles. Same with any other channeled ability (works fine for spells like mind flay)

**Comment by Wolffenstein** [comment]
Fixed in rev 3956.
