### ISSUE TITLE
[NPC] Felguard Annihilator should not be immune to banish. 

### ISSUE THREAD

**Issue by ashido96** [Atlantiss/NetherwingBugtracker#8860]
[//]: # (Enclose links to things related to the bug using http://wowhead.com or any other TBC database.)
[//]: # (You can use screenshot ingame to visual the issue.)
[//]: # (Write your tickets according to the format:)
[//]: # ([Quest][Azuremyst Isle] Red Snapper - Very Tasty!)
[//]: # ([NPC] Magistrix Erona)
[//]: # ([Spell][Mage] Fireball)
[//]: # ([Npc][Drop] Ghostclaw Lynx)
[//]: # ([Web] Armory doesnt work)
[//]: # (To find server revision type `.server info` command in the game chat.)

old 2.0.10 comments saying it is not immune to banish 
https://www.wowhead.com/tbc/npc=17400/felguard-annihilator#comments

**Description**: 

**Current behaviour**:

**Expected behaviour**: 
banishable

**Server Revision**:

**Comment by Wolffenstein** [comment]
![image](https://github.com/Atlantiss/NetherwingBugtracker/assets/1576644/adf8587b-5e86-4f73-bead-6bc3839c54d3)
Unless I'm missing something they are not immune to banish already.
