### ISSUE TITLE
Flame Wrath don't have scaling with spell power

### ISSUE THREAD

**Issue by Perva4** [Atlantiss/NetherwingBugtracker#8861]
https://www.wowhead.com/tbc/item=11809/flame-wrath#comments; https://www.wowhead.com/tbc/spell=16559/flame-wrath; https://www.wowhead.com/tbc/spell=16560/flame-wrath#comments
https://imgur.com/a/o19AYRh ; https://imgur.com/a/hwLCpQB ; https://imgur.com/a/qwFYQqg

**Description**: The item Flame Wrath have proc effect https://www.wowhead.com/tbc/spell=16559/flame-wrath  (Envelops the caster with a Fire shield for 15 sec and shoots a ring of fire dealing 130 to 170 damage to all nearby enemies.) Fire Shield Don't have scaling with Spell power,  but must have  100% . (https://www.wowhead.com/tbc/spell=16560/flame-wrath)

**Current behaviour**: Fire Shield Don't have scaling with Spell power

**Expected behaviour**: Fire Shield must have scaling with spell power 100% 1:1  according to wowhead

**Server Revision**: 3956
![coment2](https://github.com/Atlantiss/NetherwingBugtracker/assets/156111501/2f896f3b-455a-4395-8a64-f08998692f15)

**Comment by Wolffenstein** [comment]
![image](https://github.com/Atlantiss/NetherwingBugtracker/assets/1576644/286ec905-a73b-48bd-a220-6e6935993241)
It doesn't have any coefficient in the classic spell data, not sure if that comment can be trusted

**Comment by Perva4** [comment]
allow me to disagree... 
https://www.youtube.com/watch?v=HqEyr_4Ya2k (TBC classic )
https://www.youtube.com/watch?v=tbVpsgPPUMw ( TBC classic)
https://www.youtube.com/watch?v=iH_HnGyFplI ( this video from wow classic  but this work and in wow TBC )  its about all 
items what have scaling with spell power


![flame wrath coments2](https://github.com/Atlantiss/NetherwingBugtracker/assets/156111501/64864bc6-beaf-4bba-95d9-9ff223feb3cb)

https://www.wowhead.com/tbc/item=11809/flame-wrath#comments

**Comment by Perva4** [comment]
![WoWScrnShot_011524_002101](https://github.com/Atlantiss/NetherwingBugtracker/assets/156111501/55738481-9c1a-4c87-98b9-89ea28e3484d)

I'm talking about the buff that is given for 15 seconds

**Comment by Godmatik** [comment]
Why did you close the issue? Did you misclick?

If you want it fixed you will have to re-open it.

**Comment by Perva4** [comment]
> Why did you close the issue? Did you misclick?
> 
> If you want it fixed you will have to re-open it.

yes i misclick (

**Comment by Godmatik** [comment]
You can reopen it

**Comment by Perva4** [comment]
> You can reopen it

ty

**Comment by Perva4** [comment]
> ![image](https://private-user-images.githubusercontent.com/1576644/298399735-286ec905-a73b-48bd-a220-6e6935993241.png?jwt=eyJhbGciOiJIUzI1NiIsInR5cCI6IkpXVCJ9.eyJpc3MiOiJnaXRodWIuY29tIiwiYXVkIjoicmF3LmdpdGh1YnVzZXJjb250ZW50LmNvbSIsImtleSI6ImtleTUiLCJleHAiOjE3MDcxMzc5MTQsIm5iZiI6MTcwNzEzNzYxNCwicGF0aCI6Ii8xNTc2NjQ0LzI5ODM5OTczNS0yODZlYzkwNS1hNzNiLTQ4YmQtYTIyMC02ZTY5MzU5OTMyNDEucG5nP1gtQW16LUFsZ29yaXRobT1BV1M0LUhNQUMtU0hBMjU2JlgtQW16LUNyZWRlbnRpYWw9QUtJQVZDT0RZTFNBNTNQUUs0WkElMkYyMDI0MDIwNSUyRnVzLWVhc3QtMSUyRnMzJTJGYXdzNF9yZXF1ZXN0JlgtQW16LURhdGU9MjAyNDAyMDVUMTI1MzM0WiZYLUFtei1FeHBpcmVzPTMwMCZYLUFtei1TaWduYXR1cmU9YTM3YWNhMzJmYjlmOWUzNTQyYjA2ZmZlMGYxMGEzYjE5NTIzMjM1Nzk2ZTZlOWU4NzlhM2Q4OGMzY2Y1ZDAwNSZYLUFtei1TaWduZWRIZWFkZXJzPWhvc3QmYWN0b3JfaWQ9MCZrZXlfaWQ9MCZyZXBvX2lkPTAifQ.pPW0zxIFzJzeMYDLGMGt6MmxRAu85payG84Jp-J4-XE) It doesn't have any coefficient in the classic spell data, not sure if that comment can be trusted

I am waiting for your answer

**Comment by Wolffenstein** [comment]
Fixed in rev 3973.
