### ISSUE TITLE
Every quest that gives "Alliance rep" Only gives rep to a single faction instead of all alliance races

### ISSUE THREAD

**Issue by ghost** [Atlantiss/NetherwingBugtracker#8863]
[//]: # (Enclose links to things related to the bug using http://wowhead.com or any other TBC database.)
[//]: # (You can use screenshot ingame to visual the issue.)
[//]: # (Write your tickets according to the format:)
[//]: # ([Quest][Azuremyst Isle] Red Snapper - Very Tasty!)
[//]: # ([NPC] Magistrix Erona)
[//]: # ([Spell][Mage] Fireball)
[//]: # ([Npc][Drop] Ghostclaw Lynx)
[//]: # ([Web] Armory doesn't work)
[//]: # (To find server revision type `.server info` command in the game chat.)

**Description**: 
https://www.wowhead.com/tbc/quests/min-level:2/min-req-level:11?filter=1;469;0#0+2+3+13

This list of 19 quests, of which I have had 3 tested, are all supposed to get the amount of rep they display to each race on alliance side, as of right now they only give that amount to one race and the others just then the standard 1/4th spillover rep instead. This makes getting to exalted with gnomergan very difficult as there are less than 100 quests total for them, so you have to fill in with spill over rep from other races and these quests that give rep to all, but as those do not work it might not even be possible without cloth turn ins.
**Current behavior**:
When turning in one of the quests on this list, you get the rep amount shown just for one of the 5 playable races and 1/4th of that in spillover
**Expected behavior**: 
You are supposed to get the amount of rep shown with each race, if it says "500 alliance" it means all 5 races get 500 rep each (before rep bonuses)
**Server Revision**: 
3956

**Comment by Godmatik** [comment]
Similar issue occurs with Horde quests.

https://github.com/Atlantiss/NetherwingBugtracker/issues/7644

**Comment by Wolffenstein** [comment]
Might be just a visual bug/limitation in TBC from what I recall? Check that it actually did not reward the rep by comparing the values instead of relying on what it shows in chat

**Comment by ghost** [comment]
I have an addon that replaces the existing rep reward display with it's own which will tell me about spill over rep as well. It's only giving me spill over rep (150) on a 500 (600 with 20% bonus) quest turn in.

**Comment by Wolffenstein** [comment]
Fixed in rev 3970.
