### ISSUE TITLE
[Eye of the Dead] 

### ISSUE THREAD

**Issue by Kn1eDD** [Atlantiss/NetherwingBugtracker#8864]
https://www.wowhead.com/tbc/item=23047/eye-of-the-dead
[Item] Eye of the Dead

**Current behaviour**: Increases healing done by up to 450 and damage done by up to 150 for 30 sec.

**Expected behaviour**: Increases healing done _**by the next 5 spells**_ by up to 450 and damage done by up to 150 for 30 sec.

**Server Revision**: 3956

**Comment by Wolffenstein** [comment]
Fixed on the auras branch.
