### ISSUE TITLE
Mind controlled Amani'shi Flame Caster - Conflagration

### ISSUE THREAD

**Issue by Godmatik** [Atlantiss/NetherwingBugtracker#8866]
**Current behaviour**:
When mind controlling an Amani'shi Flame Caster, you can use their conflagration spell on bosses and it disorients them

**Expected behaviour**: 
Bosses should be immune to disorient effect of conflagration

**Server Revision**: 
3956

**Comment by Wolffenstein** [comment]
Fixed in rev 3957.
