### ISSUE TITLE
Budd's Map

### ISSUE THREAD

**Issue by Godmatik** [Atlantiss/NetherwingBugtracker#8868]
**Current behaviour**:
Quest item still despawns after sometime, issue is not resolved.

https://github.com/Atlantiss/NetherwingBugtracker/issues/8858

![image](https://github.com/Atlantiss/NetherwingBugtracker/assets/37913400/ff6ec846-a313-4dfa-b1cc-cac80107292a)

**Server Revision**: 
3956

**Comment by Wolffenstein** [comment]
idk then cant reproduce

**Comment by Godmatik** [comment]
Seems like it happens toward end of a run after everyone is done with ZA they go back for map and its not there. Maybe it is related to the prisoner being freed and/or his nearby chest being looted, or the bear boss being defeated, or all bosses being defeated? Just throwing out ideas, will try to mess around on PTR sometime to reproduce

**Comment by Wolffenstein** [comment]
Maybe will be fixed in rev 3957. If not, reopen.
