### ISSUE TITLE
[NPC] Baron Bloodbane

### ISSUE THREAD

**Issue by Godmatik** [Atlantiss/NetherwingBugtracker#8869]
This rare mob currently exists in Eastern Plaguelands.

Was not added in until Cataclysm

https://www.wowhead.com/tbc/npc=10819/baron-bloodbane

**Comment by Wolffenstein** [comment]
![image](https://github.com/Atlantiss/NetherwingBugtracker/assets/1576644/aca493c3-75c2-4732-8c67-7cde2b17a001)
what's funny is he has all the data in the bestiary

**Comment by Godmatik** [comment]
Blizz must have forgot to add it in, ah well
