### ISSUE TITLE
[Core] Stuck in sitting animation after drinking

### ISSUE THREAD

**Issue by Sinyr** [Atlantiss/NetherwingBugtracker#887]
[//]: # (Enclose links to things related to the bug using http://wowhead.com or any other TBC database.)
[//]: # (You can use screenshot ingame to visual the issue.)
[//]: # (Write your tickets according to the format:)
[//]: # ([Quest][Azuremyst Isle] Red Snapper - Very Tasty!)
[//]: # ([NPC] Magistrix Erona)
[//]: # ([Spell][Mage] Fireball)
[//]: # ([Npc][Drop] Ghostclaw Lynx)
[//]: # ([Web] Armory doesnt work)

**Current behaviour**:
Tested this with a friend.

After eating/drinking, other players stay visually stuck in the sitting animation while standing in place, even after moving then stopping in place again. This lasts until the player casts a spell, but can otherwise last indefinitely. You don't see this if it happens to you, only other players do.

However, the bug is not only visual, but it also prevents the affected player from using any emotes (or at least those with animations). So even though you're not visually stuck on your end, you still can't use emotes until you cast a spell.

**Expected behaviour**: 
After standing up after eating/drinking, players shouldn't return to the sitting animation automatically and should be able to use emotes.

**Server Revision**: 
2083

**Comment by totaemoeggerli** [comment]
this can happen the other way around https://imgur.com/a/rnp137H

**Comment by Manaci** [comment]
Fixed
