### ISSUE TITLE
Underground Assault quest gives NO rep

### ISSUE THREAD

**Issue by ghost** [Atlantiss/NetherwingBugtracker#8871]
[//]: # (Enclose links to things related to the bug using http://wowhead.com or any other TBC database.)
[//]: # (You can use screenshot ingame to visual the issue.)
[//]: # (Write your tickets according to the format:)
[//]: # ([Quest][Azuremyst Isle] Red Snapper - Very Tasty!)
[//]: # ([NPC] Magistrix Erona)
[//]: # ([Spell][Mage] Fireball)
[//]: # ([Npc][Drop] Ghostclaw Lynx)
[//]: # ([Web] Armory doesnt work)
[//]: # (To find server revision type `.server info` command in the game chat.)

**Description**: 
https://www.wowhead.com/tbc/quest=2040/underground-assault I just turned in this quest and got literally no rep at all for it.
**Current behaviour**:
Gives no rep at all.
**Expected behaviour**: 
500 rep for stormwind and Gnomer (before rep bonuses)
**Server Revision**: 
3956

**Comment by Wolffenstein** [comment]
Fixed in rev 3970.
