### ISSUE TITLE
[Surefooted] Hunter talent 

### ISSUE THREAD

**Issue by Ceehz** [Atlantiss/NetherwingBugtracker#8878]
Talent, hunter survival specialization **[Surefooted]** : https://www.thegeekcrusade-serveur.com/db/?spell=24283

### **Description**: 

Since the last patch **[Surefooted]** no longer adds the extra hit to the character's information stats. This was previously the case.
I'm not even sure  if the extra hit is taken into consideration or if it's just a visual issue but there is definitely a problem with it

Screenshot :

**[Surefooted]** on : https://imgur.com/a/bS98r9h (same with melee hit)
**[Surefooted]** off : https://imgur.com/a/lYhri1D

I tried on PTR and Netherwing realm the problem remains unchanged on both

**Comment by Godmatik** [comment]
Talents that increase your hit have never been reflected in the character sheet and this is intended (blizzlike), you can see the same for any other class that has +hit% or +spell hit% talents. 

The 'hit rating" shown in your sheet only reflects what you gain from gear.
