### ISSUE TITLE
[ZA] Prisoner bonus loot handling incorrect

### ISSUE THREAD

**Issue by Godmatik** [Atlantiss/NetherwingBugtracker#8879]
**Current behaviour**:
When you open a chest from a prisoner - currently what item pool is selected is based on how many chests you have opened.

For example if I killed (in this order) Eagle --> Bear --> Dragonhawk --> Lynx bosses all before the timer expired, thus saving all four prisoners, if I open up the chest from Lynx prisoner first (4th boss killed), it will show me the loot from the first set of prisoner items. 

**Expected behaviour**: 
What type of loot is rewarded from the prisoner chest should be based on what order you killed the bosses in - not what order you open the chests.

Again going to earlier example of Eagle --> Bear --> Dragonhawk --> Lynx bosses killed before timer expired
Lynx was killed last (4th), so the loot from the Lynx prisoner chest should always be the bear (4th prisoner saved reward)

You can see this in the below classic video.

https://www.youtube.com/watch?v=googefOx9RA&t=2460s

**Server Revision**: 
3958

**Comment by Wolffenstein** [comment]
Fixed in rev 3963.
