### ISSUE TITLE
Wrong Stats on Item

### ISSUE THREAD

**Issue by Sweetycake24** [Atlantiss/NetherwingBugtracker#8880]
[//]: # (Enclose links to things related to the bug using http://wowhead.com or any other TBC database.)
[//]: # (You can use screenshot ingame to visual the issue.)
[//]: # (Write your tickets according to the format:)
[//]: # ([Quest][Azuremyst Isle] Red Snapper - Very Tasty!)
[//]: # ([NPC] Magistrix Erona)
[//]: # ([Spell][Mage] Fireball)
[//]: # ([Npc][Drop] Ghostclaw Lynx)
[//]: # ([Web] Armory doesnt work)
[//]: # (To find server revision type `.server info` command in the game chat.)

**Description**: Wrong Stats on Blade of Twisted visions

**Current behaviour**: 
![Screenshot_2024-01-28-09-43-01-60_40deb401b9ffe8e1df2f1cc5ba480b12](https://github.com/Atlantiss/NetherwingBugtracker/assets/157956656/758cf9b8-b4de-4a54-afb1-7223bfcf184f)
![IMG20240128092138](https://github.com/Atlantiss/NetherwingBugtracker/assets/157956656/9b0d8f4c-6c19-4a8b-b646-893c4a9a3729)

**Expected behaviour**: 

**Server Revision**:

**Comment by Sweetycake24** [comment]
Stats on Logs seems to be correct and alligned to websites, whle in game i have different version of the item

**Comment by Godmatik** [comment]
Was resolved on discord - issue can be closed.

It is because the item changes stats between patches 2.3 and 2.4
