### ISSUE TITLE
[Quest][Fishing Daily] Shrimpin' Ain't Easy

### ISSUE THREAD

**Issue by Shineslippers** [Atlantiss/NetherwingBugtracker#8883]
[//]: # (Enclose links to things related to the bug using http://wowhead.com or any other TBC database.)
[//]: # (You can use screenshot ingame to visual the issue.)
[//]: # (Write your tickets according to the format:)
[//]: # ([Quest][Azuremyst Isle] Red Snapper - Very Tasty!)
[//]: # ([NPC] Magistrix Erona)
[//]: # ([Spell][Mage] Fireball)
[//]: # ([Npc][Drop] Ghostclaw Lynx)
[//]: # ([Web] Armory doesnt work)
[//]: # (To find server revision type `.server info` command in the game chat.)

**Description**: 
By quest [Shrimpin' Ain't Easy](https://www.wowhead.com/tbc/quest=11668/shrimpin-aint-easy) players have to fish up [Bloated Barbed Gill Trout](https://www.wowhead.com/tbc/item=35313/bloated-barbed-gill-trout)

**Current behaviour**:
There is no [Bloated Barbed Gill Trout](https://www.wowhead.com/tbc/item=35313/bloated-barbed-gill-trout) in fish table while quest is in log
**Expected behaviour**: 

There is should be [Bloated Barbed Gill Trout](https://www.wowhead.com/tbc/item=35313/bloated-barbed-gill-trout) if you have quest in log

**Server Revision**: 
3959

**Comment by Godmatik** [comment]
confirmed

**Comment by Wolffenstein** [comment]
should be fixed now
