### ISSUE TITLE
Mage Frostnova Bugged in PvP

### ISSUE THREAD

**Issue by budgebudge** [Atlantiss/NetherwingBugtracker#8884]
**Description**: 
Mages can frostnova from the bottom of blades edge on top of the pillar.

**Current behaviour**:
mage stood on the bottom of the pillar and froze a character standing upstairs.

**Expected behaviour**: 
it should not freeze people on top of a pillar....

**Comment by Wolffenstein** [comment]
Fixed in rev 3960.
