### ISSUE TITLE
Kreeg's Stout Beatdown

### ISSUE THREAD

**Issue by Godmatik** [Atlantiss/NetherwingBugtracker#8885]
**Current behaviour**:
25 spirit drink shows as a debuff when you drink it after recent aura changes

**Expected behaviour**: 
Should show as a buff

https://www.wowhead.com/classic/item=18284/kreegs-stout-beatdown

**Server Revision**: 
3959

**Comment by Wolffenstein** [comment]
Fixed in rev 3960.
