### ISSUE TITLE
[Quest] Learning to Fly

### ISSUE THREAD

**Issue by Godmatik** [Atlantiss/NetherwingBugtracker#8886]
**Current behaviour**:
Ever since latest patch - this quest keeps popping up for players - even if they already completed it. It also prevents use of flight master unless you accept it, and being told as well the quest re-appears on the NPC again after a server restart.

https://www.wowhead.com/tbc/quest=11497/learning-to-fly

**Expected behaviour**: 
If someone already has completed this quest, the NPC should not provide it

**Server Revision**: 
3959

**Comment by Wolffenstein** [comment]
don't know how to reproduce

**Comment by Godmatik** [comment]
Part of this report was based on 2nd hand sources, I thought I recalled it as well, will gather more concrete data sometime and re-open
