### ISSUE TITLE
Scholomance - No Gandling spawn

### ISSUE THREAD

**Issue by Godmatik** [Atlantiss/NetherwingBugtracker#8887]
All six side room bosses were cleared, but Darkmaster Gandling did not spawn

Rev 3959

**Comment by Wolffenstein** [comment]
![image](https://github.com/Atlantiss/NetherwingBugtracker/assets/1576644/9ab1f579-9111-4d15-bbdc-d469cdbba858)
Works fine for me, requires you to kill the following bosses:
    ENCOUNTER_LORD_ALEXEI_BAROV,
    ENCOUNTER_DOCTOR_THEOLEN_KRASTINOV,
    ENCOUNTER_THE_RAVENIAN,
    ENCOUNTER_LOREKEEPER_POLKELT,
    ENCOUNTER_INSTRUCTOR_MALICIA,
    ENCOUNTER_ILLUCIA_BAROV,

**Comment by Godmatik** [comment]
Will re-open if it occurs again
