### ISSUE TITLE
[NPC][Paladin][Need research] Paladin trainers not teaching Parry

### ISSUE THREAD

**Issue by Sinyr** [Atlantiss/NetherwingBugtracker#889]
[//]: # (Enclose links to things related to the bug using http://wowhead.com or any other TBC database.)
[//]: # (You can use screenshot ingame to visual the issue.)
[//]: # (Write your tickets according to the format:)
[//]: # ([Quest][Azuremyst Isle] Red Snapper - Very Tasty!)
[//]: # ([NPC] Magistrix Erona)
[//]: # ([Spell][Mage] Fireball)
[//]: # ([Npc][Drop] Ghostclaw Lynx)
[//]: # ([Web] Armory doesnt work)

**Current behaviour**:
None of the paladin trainers in Azuremyst Isle (including Exodar) teach Parry. 

I don't have any proof that they should, hence the research tag. I didn't really notice that I was missing Parry at first. Since I quested in Bloodmyst Isle, the first time I visited a non-Draenei trainer was at 22 and it was very strange to me that they offered to teach me Parry and that it's available since level 8.

**Expected behaviour**: 
Possibly all paladin trainers should teach Parry.

**Server Revision**: 
2083

**Comment by Tenoutoften** [comment]
[[Spell]Parry#3127](https://db.excalibur.ws/?spell=3127)

**Comment by Wolffenstein** [comment]
Fixed in rev 2921.
