### ISSUE TITLE
[rogue][ruthlessness talent] proc combats player with slice and dice

### ISSUE THREAD

**Issue by dedestus** [Atlantiss/NetherwingBugtracker#8890]
**Description**: 

to reproduce spam slice and dice in a duel or on another player while being 3/3 ruthlessness spec and after do it without being specced into it. you will notice that after the talent procs and awards you 1 combo point you and your target will enter combat state.

https://www.twitch.tv/videos/2052980547 tested on ptr, video includes pressing slice and dice with ruthlessness specced and without at the end. same behavior on live server but i did not record on live

**Current behaviour**:

3/3 ruthlessness 60% chance to gain a combo point after using a finisher puts the player and his target into combat state after proccing which causes you and your target to enter combat after pressing slice and dice.

**Expected behaviour**: 

not exactly sure how this interacts with other combo point generating abilities but i think all of them besides slice and dice cause the player and his target to enter combat state anyway.
but pressing slice and dice should not put the player nor his target into combat.

**Server Revision**: 
3964

**Comment by Godmatik** [comment]
Related issue, yes it appears you found out what is causing it, very nice

https://github.com/Atlantiss/NetherwingBugtracker/issues/8486

**Comment by Wolffenstein** [comment]
Fixed in rev 3965.
