### ISSUE TITLE
[mage][blink] in ruins of lordaeron arena map

### ISSUE THREAD

**Issue by dedestus** [Atlantiss/NetherwingBugtracker#8893]
**Description**: 

https://www.twitch.tv/videos/2053471516 5 minutes of blinking vs various objects found inside the ruins of lordaeron arena map

**Current behaviour**:

as a mage you can blink through most objects including the grave or other stone tombs found inside the arena map

**Expected behaviour**: 

im not 100% sure but it looks like you should not be able to blink through every object and end up on the other side of them.

**Server Revision**: 

3963 (ptr) could not test on live yet because of maximum 3 accounts logged in limitation (need 4 to start arena match) but i have seen this happen on live server which is why i decided to do more testing

**Comment by Wolffenstein** [comment]
Should work better after rev 3967.
