### ISSUE TITLE
Quest Lunar Fireworks gives no rep

### ISSUE THREAD

**Issue by ghost** [Atlantiss/NetherwingBugtracker#8894]
[//]: # (Enclose links to things related to the bug using http://wowhead.com or any other TBC database.)
[//]: # (You can use screenshot ingame to visual the issue.)
[//]: # (Write your tickets according to the format:)
[//]: # ([Quest][Azuremyst Isle] Red Snapper - Very Tasty!)
[//]: # ([NPC] Magistrix Erona)
[//]: # ([Spell][Mage] Fireball)
[//]: # ([Npc][Drop] Ghostclaw Lynx)
[//]: # ([Web] Armory doesnt work)
[//]: # (To find server revision type `.server info` command in the game chat.)

**Description**: 
https://www.wowhead.com/tbc/quest=8867/lunar-fireworks Currently this quest gives no rep when turned in despite it showing it should on wowhead.
**Current behaviour**:
Quest gives no rep
**Expected behaviour**: 
The quest is supposed to give 75 rep with Cenarion Circle faction (before rep bonuses)
**Server Revision**: 
3966

**Comment by Wolffenstein** [comment]
Fixed.
