### ISSUE TITLE
[Pet] Pet skills no longer show the time remaining on enemy (seduce)

### ISSUE THREAD

**Issue by Dep-warlock** [Atlantiss/NetherwingBugtracker#8895]
**Description**: 
Seduce no longer shows the duration left on the debuff on enemy. This is very problematic because you can't know if there is DR or not.
This bug has appeared for me in late january 2024.
I have not changed anything in my client, and here is some screenshots I got today on this server (after this bug appear for me) and on a test server with the expected behaviour.
If someone could test this and verify it's not my problem, would be great.

**Current behaviour**:
![depseduce](https://github.com/Atlantiss/NetherwingBugtracker/assets/159042486/e2340bd0-05b9-4702-9753-c072af4ef470)

**Expected behaviour**: 
![deptestman](https://github.com/Atlantiss/NetherwingBugtracker/assets/159042486/286b88fa-b342-479f-a8f5-d870acb3ce98)

**Note on the images**:
There is OmniCC addon on both of these. OmniCC shows up properly for my skills, thats not the problem here.
The default UI has this clock animation on the icons but it doesn't show up here at all.

**Server Revision**: 
3966

**Comment by Wolffenstein** [comment]
Fixed in rev 3967.
