### ISSUE TITLE
Lunar Festival - Elune's Blessing

### ISSUE THREAD

**Issue by Godmatik** [Atlantiss/NetherwingBugtracker#8896]
**Current behaviour**:
Elune's Blessing 1 hour buff - which you can receive after defeating Omen - provides a 10% buff to all stats, so it operates exactly the same way as Blessing of kings does

**Expected behaviour**: 
Per info from classic - it should only buff 10% of BASE stats

https://www.reddit.com/r/classicwow/comments/etcdp7/flair_of_fireworks_a_raiderpvpers_guide_to/

> EDIT: Elune's Blessing increases your BASE STATS by 10%, meaning it ignores the stats from your armor and talents. This buff is not as useful as assumed and is not worth the time it takes to get it for raiding.

**Comment by Wolffenstein** [comment]
base stats = stamina, intellect, spirit, strength, agility
it works correctly

**Comment by Wolffenstein** [comment]
It got changed by 2.4.3 and works exactly like Blessing of Kings, it just shouldn't stack.

Fixed
