### ISSUE TITLE
[Quest][Eversong Woods]Whitebark's Memory

### ISSUE THREAD

**Issue by Kentamentiu** [Atlantiss/NetherwingBugtracker#89]
[//]: # (Enclose links to things related to the bug using http://wowhead.com or any other TBC database.)
[//]: # (You can use screenshot ingame to visual the issue.)
[//]: # (Write your tickets according to the format:)
[//]: # ([Quest][Azuremyst Isle] Red Snapper - Very Tasty!)
[//]: # ([NPC] Magistrix Erona)
[//]: # ([Spell][Mage] Fireball)
[//]: # ([Npc][Drop] Ghostclaw Lynx)
[//]: # ([Web] Armory doesnt work)

**Description**: 
The provided item [Old Whitebark's Pendant] is only usable on a very specific spot near the runestone.

**Current behaviour**:
You can only use the pendant on 37.6, 86.1

**Expected behaviour**:  You should be able to use the pendant all around the runestone, as long as you are close to it.

**Server Revision**: 
2020

**Comment by Wolffenstein** [comment]
Fixed in rev 2026.
