### ISSUE TITLE
[Druid][Interface] Dire Bear Form spell button doesn't replace Bear Form

### ISSUE THREAD

**Issue by wowthings** [Atlantiss/NetherwingBugtracker#890]
[//]: # (Enclose links to things related to the bug using http://wowhead.com or any other TBC database.)
[//]: # (You can use screenshot ingame to visual the issue.)
[//]: # (Write your tickets according to the format:)
[//]: # ([Quest][Azuremyst Isle] Red Snapper - Very Tasty!)
[//]: # ([NPC] Magistrix Erona)
[//]: # ([Spell][Mage] Fireball)
[//]: # ([Npc][Drop] Ghostclaw Lynx)
[//]: # ([Web] Armory doesnt work)

**Description**: 
At lvl 40 when you buy the spell it should replace the bear form.
**Current behaviour**:
Dire Bear Form is the second spell, tried deleting cache and wtf just to make sure but stays the same.
![wowscrnshot_092918_155532](https://user-images.githubusercontent.com/43504905/46246633-3bacec80-c401-11e8-943d-6138b6cd8f60.jpg)
**Expected behaviour**: 
There should be only the most powerful spell in the row.
**Server Revision**: 
2083

**Comment by Peglaa** [comment]
http://wowwiki.wikia.com/wiki/Dire_Bear_Form?oldid=1221689
some proof that it should actually replace the regular bear form

-This is essentially a more powerful version of Bear Form, and learning it prevents the Druid from using Bear Form.

**Comment by Kiperr** [comment]
```sql
DELETE FROM spell_ranks WHERE first_spell_id IN (5487,33943);
INSERT INTO spell_ranks (first_spell_id,spell_id,rank) VALUES
(5487,5487,1),
(5487,9634,2),
```

**Comment by Evolvee** [comment]
rev xdd
