### ISSUE TITLE
Lunar Festival Harbinger does not give additional Lunar Festival Invitations

### ISSUE THREAD

**Issue by ghost** [Atlantiss/NetherwingBugtracker#8901]
[//]: # (Enclose links to things related to the bug using http://wowhead.com or any other TBC database.)
[//]: # (You can use screenshot ingame to visual the issue.)
[//]: # (Write your tickets according to the format:)
[//]: # ([Quest][Azuremyst Isle] Red Snapper - Very Tasty!)
[//]: # ([NPC] Magistrix Erona)
[//]: # ([Spell][Mage] Fireball)
[//]: # ([Npc][Drop] Ghostclaw Lynx)
[//]: # ([Web] Armory doesnt work)
[//]: # (To find server revision type `.server info` command in the game chat.)

**Description**: 
https://www.wowhead.com/tbc/item=21711/lunar-festival-invitation "I was worried about the duration timer of 24 hours, but I noticed that the person who gives you the invitation has a "Please give me another invitation" option when you talk to them. So even if it does go away, you can get another one.
" Top comment on wowhead. https://www.wowhead.com/tbc/spell=26375/create-lunar-festival-invitation https://www.wowhead.com/tbc/npc=15895/lunar-festival-harbinger
**Current behaviour**:
Lunar Festival Harbinger does not offer additional Lunar Festival Invitations even if you no longer posses one.
**Expected behaviour**: 
After your first Lunar Festival Invitation from the quest expirers, Lunar Festival Harbinger is supposed to have a dialog option to give you another, and this persists all the way until the event ends.
**Server Revision**: 
3967

**Comment by Wolffenstein** [comment]
Fixed in rev 3970.
