### ISSUE TITLE
Gnomish Death Ray - Does not work

### ISSUE THREAD

**Issue by Godmatik** [Atlantiss/NetherwingBugtracker#8902]
**Current behaviour**:
Using Gnomish Death Ray properly deals self-damage while charging - but at the end of it's channel, deals no damage to its target

https://streamable.com/b3vped

https://www.wowhead.com/classic/item=10645/gnomish-death-ray#comments

Rev 3967

**Comment by Wolffenstein** [comment]
Fixed in rev 3968.
