### ISSUE TITLE
Mage clearcasting - Proccing on each AoE hit

### ISSUE THREAD

**Issue by Godmatik** [Atlantiss/NetherwingBugtracker#8903]
**Current behaviour**:
Mage clearcasting once again has a chance to proc on each enemy hit when doing AoE. It appears that the new aura branch broke this.

An issue about it was brought up previously:
https://github.com/Atlantiss/NetherwingBugtracker/issues/6130

Rev 3967

**Comment by Nuy** [comment]
Blizzard seems fine tho but bugged with Arcane Explosion resulting in Arcane mages having perma clearcasting during AoE DPSing what's giga-broken.

**Comment by Wolffenstein** [comment]
Fixed in rev 3968.
