### ISSUE TITLE
[Pet] Gore ability not benefitting from debuffs (such as sunder armor)

### ISSUE THREAD

**Issue by Godmatik** [Atlantiss/NetherwingBugtracker#8906]
**Current behaviour**:
Testing Ravager pet ability "Gore" on a lvl 73 dummy on PTR - it appears that sunder armor (and likely other debuffs) are not impacting the damage of this. 

This may also be impacting other pet physical abilities such as Claw and Bite.

Normal melee hits from pet seem to be benefitting properly.

Gore casts with 0 sunders up:
![ravagergorenosunder](https://github.com/Atlantiss/NetherwingBugtracker/assets/37913400/fbf23bf0-a871-4266-8d87-a1c4a299c10a)

Gore casts with 5 sunders up:
![ravagergoresunder](https://github.com/Atlantiss/NetherwingBugtracker/assets/37913400/6d86795d-6dce-4260-b1a8-409a2aab6932)

**Expected behaviour**: 
Ravager's gore ability (+ other pet physical abilities) should benefit from debuffs but currently do not. This is part of the reason wind serpent is still outperforming ravagers for DPS in a raid setting.

**Server Revision**: 
3963 (on PTR)

**Comment by Wolffenstein** [comment]
![image](https://github.com/Atlantiss/NetherwingBugtracker/assets/1576644/60020655-512a-4ad8-a482-b964331b1078)
It works fine, you can see the damage isn't reduced by armor with 5 stacks of Sunder Armor until Sunder expires. The problem with Gore and the other pet abilities like that is the high base variance which is bigger than the difference just removing armor accomplishes, so your test results will vary wildly:

![image](https://github.com/Atlantiss/NetherwingBugtracker/assets/1576644/b4e3732e-f697-4316-9b44-98fea7fd3d80)
