### ISSUE TITLE
Establishing New Outposts towers can not be captured

### ISSUE THREAD

**Issue by ghost** [Atlantiss/NetherwingBugtracker#8907]
[//]: # (Enclose links to things related to the bug using http://wowhead.com or any other TBC database.)
[//]: # (You can use screenshot ingame to visual the issue.)
[//]: # (Write your tickets according to the format:)
[//]: # ([Quest][Azuremyst Isle] Red Snapper - Very Tasty!)
[//]: # ([NPC] Magistrix Erona)
[//]: # ([Spell][Mage] Fireball)
[//]: # ([Npc][Drop] Ghostclaw Lynx)
[//]: # ([Web] Armory doesnt work)
[//]: # (To find server revision type `.server info` command in the game chat.)

**Description**: 
https://www.wowhead.com/tbc/quest=9664/establishing-new-outposts additionally, the version of this quest given to horde players is completely MIA as their quest giver for it is nowhere to be seen. I don't know his name or the name of their quest, this is the link to the Alliance quest.
**Current behaviour**:
The towers can not be captured by either faction while standing at them
**Expected behaviour**: 
The towers should function like the ones in Hellfire Peninsula and pop up a bar that moves toward your faction's color while standing at the tower.
**Server Revision**: 
3968

**Comment by Wolffenstein** [comment]
Fixed in rev 3970.
