### ISSUE TITLE
Ancient Treasure in Uldaman after last boss does not spawn

### ISSUE THREAD

**Issue by ghost** [Atlantiss/NetherwingBugtracker#8908]
[//]: # (Enclose links to things related to the bug using http://wowhead.com or any other TBC database.)
[//]: # (You can use screenshot ingame to visual the issue.)
[//]: # (Write your tickets according to the format:)
[//]: # ([Quest][Azuremyst Isle] Red Snapper - Very Tasty!)
[//]: # ([NPC] Magistrix Erona)
[//]: # ([Spell][Mage] Fireball)
[//]: # ([Npc][Drop] Ghostclaw Lynx)
[//]: # ([Web] Armory doesnt work)
[//]: # (To find server revision type `.server info` command in the game chat.)

**Description**: 
https://www.wowhead.com/tbc/object=141979/ancient-treasure#comments;mode:normal
**Current behaviour**:
The chest is missing
**Expected behaviour**: 
The chest should be there after the boss is killed
**Server Revision**: 
3968

**Comment by Godmatik** [comment]
Duplicate - but yeah confirmed.
**https://github.com/Atlantiss/NetherwingBugtracker/issues/7264**

**Comment by tsu-1** [comment]
I think this is intended, no chest spawns in azeroth dungeons.

**Comment by Wolffenstein** [comment]
> I think this is intended, no chest spawns in azeroth dungeons.

it is not

**Comment by ghost** [comment]
Chests spawn in almost every damn instance pre BC what are you talking about? And this one specifically is for Uldaman after the last boss, it's a unique chest that only this instance has in it's final room that always has a few greens and other things inside it.

**Comment by ghost** [comment]
Fuck this server and fuck you guys.
