### ISSUE TITLE
Lucky Rocket Cluster does not give buff

### ISSUE THREAD

**Issue by ghost** [Atlantiss/NetherwingBugtracker#8910]
[//]: # (Enclose links to things related to the bug using http://wowhead.com or any other TBC database.)
[//]: # (You can use screenshot ingame to visual the issue.)
[//]: # (Write your tickets according to the format:)
[//]: # ([Quest][Azuremyst Isle] Red Snapper - Very Tasty!)
[//]: # ([NPC] Magistrix Erona)
[//]: # ([Spell][Mage] Fireball)
[//]: # ([Npc][Drop] Ghostclaw Lynx)
[//]: # ([Web] Armory doesnt work)
[//]: # (To find server revision type `.server info` command in the game chat.)

**Description**: 
https://www.wowhead.com/tbc/item=21744/lucky-rocket-cluster https://www.wowhead.com/tbc/spell=26522/lunar-fortune
**Current behaviour**:
When you use Lucky Rocket Cluster, it just flies off in a random direction and gives no buff
**Expected behaviour**: 
When you use Lucky Rocket Cluster near a cluster Launcher, it should go into it and give everyone nearby a buff for 250 HP
**Server Revision**: 
3968

**Comment by Wolffenstein** [comment]
Fixed in rev 3970.
