### ISSUE TITLE
Melnan Darkstone is MIA in Ironforge

### ISSUE THREAD

**Issue by ghost** [Atlantiss/NetherwingBugtracker#8911]
[//]: # (Enclose links to things related to the bug using http://wowhead.com or any other TBC database.)
[//]: # (You can use screenshot ingame to visual the issue.)
[//]: # (Write your tickets according to the format:)
[//]: # ([Quest][Azuremyst Isle] Red Snapper - Very Tasty!)
[//]: # ([NPC] Magistrix Erona)
[//]: # ([Spell][Mage] Fireball)
[//]: # ([Npc][Drop] Ghostclaw Lynx)
[//]: # ([Web] Armory doesnt work)
[//]: # (To find server revision type `.server info` command in the game chat.)

**Description**: 
https://www.wowhead.com/tbc/npc=14842/melnan-darkstone#map
**Current behaviour**:
The NPC is nowhere to be seen.
**Expected behaviour**: 
The NPC should spawn when the faire is setting up and be up until it leaves, walk his set path the whole time and offer his quest.
**Server Revision**: 
3968

**Comment by Godmatik** [comment]
Related - the Org NPC exists but during Faire setup phase, has no patrol path setup:

https://github.com/Atlantiss/NetherwingBugtracker/issues/8255

**Comment by Wolffenstein** [comment]
Fixed in rev 3970.
