### ISSUE TITLE
Argent Dawn Commission can not be reobtained after being deleted.

### ISSUE THREAD

**Issue by ghost** [Atlantiss/NetherwingBugtracker#8912]
[//]: # (Enclose links to things related to the bug using http://wowhead.com or any other TBC database.)
[//]: # (You can use screenshot ingame to visual the issue.)
[//]: # (Write your tickets according to the format:)
[//]: # ([Quest][Azuremyst Isle] Red Snapper - Very Tasty!)
[//]: # ([NPC] Magistrix Erona)
[//]: # ([Spell][Mage] Fireball)
[//]: # ([Npc][Drop] Ghostclaw Lynx)
[//]: # ([Web] Armory doesnt work)
[//]: # (To find server revision type `.server info` command in the game chat.)

**Description**: 
https://www.wowhead.com/wotlk/item=12846/argent-dawn-commission#comments
**Current behaviour**:
If you delete it, no NPC will restore it for you
**Expected behaviour**: 
If deleted, one of 3 NPCs will restore it for you, the same NPCs you obtained it from via the quest(s) at the horde/alliance camps in western or at Light's hope in Eastern plaguelands. These NPCs are https://www.wowhead.com/wotlk/npc=11039/duke-nicholas-zverenhoff https://www.wowhead.com/wotlk/npc=10839/argent-officer-garush and https://www.wowhead.com/wotlk/npc=10840/argent-officer-pureheart
**Server Revision**: 
3968

**Comment by Wolffenstein** [comment]
Fixed in rev 3970.
