### ISSUE TITLE
Scourge Champion can not drop Fetid Skull if you already have one in your bags

### ISSUE THREAD

**Issue by ghost** [Atlantiss/NetherwingBugtracker#8913]
[//]: # (Enclose links to things related to the bug using http://wowhead.com or any other TBC database.)
[//]: # (You can use screenshot ingame to visual the issue.)
[//]: # (Write your tickets according to the format:)
[//]: # ([Quest][Azuremyst Isle] Red Snapper - Very Tasty!)
[//]: # ([NPC] Magistrix Erona)
[//]: # ([Spell][Mage] Fireball)
[//]: # ([Npc][Drop] Ghostclaw Lynx)
[//]: # ([Web] Armory doesnt work)
[//]: # (To find server revision type `.server info` command in the game chat.)

**Description**: 
https://www.wowhead.com/tbc/quest=5206/marauders-of-darrowshire https://www.wowhead.com/tbc/npc=8529/scourge-champion#comments https://www.wowhead.com/tbc/item=13157/fetid-skull I just killed every single Scourge Champion in the zone and only got one skull, from my first kill. Upon using it and killing another, I instantly looted my second. This tells me It was not just bad luck, but a bug.
**Current behaviour**:
The mob in question can not drop a skull if you already have one in your bags. 
**Expected behaviour**: 
They can drop skulls even if you already currently have one in your bags
**Server Revision**: 
3968

**Comment by Wolffenstein** [comment]
Fixed in rev 3970.
