### ISSUE TITLE
Festival Dumplings quest is not repeatable

### ISSUE THREAD

**Issue by ghost** [Atlantiss/NetherwingBugtracker#8914]
[//]: # (Enclose links to things related to the bug using http://wowhead.com or any other TBC database.)
[//]: # (You can use screenshot ingame to visual the issue.)
[//]: # (Write your tickets according to the format:)
[//]: # ([Quest][Azuremyst Isle] Red Snapper - Very Tasty!)
[//]: # ([NPC] Magistrix Erona)
[//]: # ([Spell][Mage] Fireball)
[//]: # ([Npc][Drop] Ghostclaw Lynx)
[//]: # ([Web] Armory doesnt work)
[//]: # (To find server revision type `.server info` command in the game chat.)

**Description**: 
https://www.wowhead.com/tbc/quest=8863/festival-dumplings 
**Current behaviour**:
The quest for Festival Dumplings is a one time quest
**Expected behaviour**: 
The quest for Festival Dumplings should be repeatable
**Server Revision**: 
3968

**Comment by Wolffenstein** [comment]
Fixed in rev 3970.
