### ISSUE TITLE
Quests that give Steamwheedle Cartel rep only give rep for one of the 4 factions

### ISSUE THREAD

**Issue by ghost** [Atlantiss/NetherwingBugtracker#8915]
[//]: # (Enclose links to things related to the bug using http://wowhead.com or any other TBC database.)
[//]: # (You can use screenshot ingame to visual the issue.)
[//]: # (Write your tickets according to the format:)
[//]: # ([Quest][Azuremyst Isle] Red Snapper - Very Tasty!)
[//]: # ([NPC] Magistrix Erona)
[//]: # ([Spell][Mage] Fireball)
[//]: # ([Npc][Drop] Ghostclaw Lynx)
[//]: # ([Web] Armory doesnt work)
[//]: # (To find server revision type `.server info` command in the game chat.)

**Description**: 
https://www.wowhead.com/tbc/quest=4726/broodling-essence example quest. https://www.wowhead.com/tbc/quests/min-level:1?filter=1;169;0#0+2+3+13 list of all their quests.
**Current behaviour**:
Quests that say they give Steamwheedle Cartel rep only give rep to one of the 4 and the other 3 get spillover rep instead.
**Expected behaviour**: 
Quests that say they give Steamwheedle Cartel rep should give the displayed rep to each of the 4 goblin factions
**Server Revision**: 
3968

**Comment by Wolffenstein** [comment]
Fixed in rev 3970.
