### ISSUE TITLE
The Battle of Darrowshire event does not start

### ISSUE THREAD

**Issue by ghost** [Atlantiss/NetherwingBugtracker#8916]
[//]: # (Enclose links to things related to the bug using http://wowhead.com or any other TBC database.)
[//]: # (You can use screenshot ingame to visual the issue.)
[//]: # (Write your tickets according to the format:)
[//]: # ([Quest][Azuremyst Isle] Red Snapper - Very Tasty!)
[//]: # ([NPC] Magistrix Erona)
[//]: # ([Spell][Mage] Fireball)
[//]: # ([Npc][Drop] Ghostclaw Lynx)
[//]: # ([Web] Armory doesnt work)
[//]: # (To find server revision type `.server info` command in the game chat.)

**Description**: 
https://github.com/Atlantiss/NetherwingBugtracker/issues/1279 This has a bug report for it from 2018 so I am just remaking one now for it. https://www.wowhead.com/tbc/quest=5721/the-battle-of-darrowshire The event for this quest is completely non existent and thus can not be completed. This quest is massive and takes like 10 min to complete and has lots of stuff that occurs during it including multiple bosses, waves of different trash mobs and dialog from many of the contributing NPCs. This quest is important not only for it's epic grandeur but also the following quest rewards a fat chunk of rep, which is the main reason why I want to do it.
**Current behaviour**:
Using the item places it down like it should but nothing happens after, then shortly later the placed item despawns. It is supposed to stay there until the end.
**Expected behaviour**: 
Once you use the quest item at the well in Darrowshire, a epic event is supposed to take place that is very complicated and super script heavy, ending with defeating the Corrupted Redpath and then speaking to his ghost at the well.
**Server Revision**: 
3968

**Comment by EtheriousNW** [comment]
There aren't any sniffs for this quest as far as I'm aware, which makes it unlikely to be scripted any time soon. No need to make a duplicate thread for it.
