### ISSUE TITLE
Tenacious Earthstorm Diamond wrong work

### ISSUE THREAD

**Issue by Perva4** [Atlantiss/NetherwingBugtracker#8917]
https://www.wowhead.com/tbc/item=25898/tenacious-earthstorm-diamond#created-by-spell; https://www.wowhead.com/tbc/spell=32844/lesser-heroism
https://imgur.com/a/yOJnMK4

Spell : https://www.wowhead.com/tbc/spell=32844/lesser-heroism 

**Description**:"Sometimes heals bearer of 120 to 180 damage when damaging an enemy in melee."

**Current behaviour**:this is item have low lvl proc effect (40-60)

**Expected behaviour**: Must have proc 120 to 180 and not shure maybe have scaling with Spell Healing
**Server Revision**: 3968

![WoWScrnShot_021324_164204](https://github.com/Atlantiss/NetherwingBugtracker/assets/156111501/bf36dbcb-d900-4e28-81d3-807c16bc4665)
![Lesser Heroism1](https://github.com/Atlantiss/NetherwingBugtracker/assets/156111501/a4d4f884-a7ac-448f-9900-0a9f8471ab70)
![2222](https://github.com/Atlantiss/NetherwingBugtracker/assets/156111501/2427af5f-e3c9-454e-acb0-3fc1d5cefc03)

**Comment by Wolffenstein** [comment]
![image](https://github.com/Atlantiss/NetherwingBugtracker/assets/1576644/a785c956-f075-4283-8cde-bbb2e14910cf)
Works correctly, Blizzard just fucked up and put the wrong spell id in the tooltip so it says it will heal for more than the actual spell it triggers does.
