### ISSUE TITLE
Thunder Clap bug

### ISSUE THREAD

**Issue by Xykyta1** [Atlantiss/NetherwingBugtracker#8918]
[//]: # ([Spell][warrior] thunder clap)

Warrior's thunderclap doesnt slow attack speed. Any lvl of ability, with/without talent in arms tree "improved thunder clap", in testing, the speed doesnt decrease at all.  
Maybe it started when I got/changed the second specialization.
Tested on different mobs. The mobs deals same number of attacks in 30 seconds with/without debuff.

**Comment by Wolffenstein** [comment]
![image](https://github.com/Atlantiss/NetherwingBugtracker/assets/1576644/79a39ccc-47d3-4673-807a-a2e3e44b60d2)
It does work properly, but Thunder Clap is only 10%, a 2s attack timer becomes 2.2s, it's not that big of a difference
