### ISSUE TITLE
Certain Wastewander mobs in Tanaris do not grant Gadgetzan rep when killed.

### ISSUE THREAD

**Issue by ghost** [Atlantiss/NetherwingBugtracker#8919]
[//]: # (Enclose links to things related to the bug using http://wowhead.com or any other TBC database.)
[//]: # (You can use screenshot ingame to visual the issue.)
[//]: # (Write your tickets according to the format:)
[//]: # ([Quest][Azuremyst Isle] Red Snapper - Very Tasty!)
[//]: # ([NPC] Magistrix Erona)
[//]: # ([Spell][Mage] Fireball)
[//]: # ([Npc][Drop] Ghostclaw Lynx)
[//]: # ([Web] Armory doesnt work)
[//]: # (To find server revision type `.server info` command in the game chat.)

**Description**: 
https://github.com/Atlantiss/NetherwingBugtracker/issues/7527 found a report from 2020 so am linking to it here.
**Current behaviour**:
On top of the stuff listed in the issue above, I personally experienced 3 mobs that did not give rep with Gadgetzan when killed despite being below the threshold where it would stop. Those being https://www.wowhead.com/tbc/npc=5615/wastewander-rogue https://www.wowhead.com/tbc/npc=5617/wastewander-shadow-mage and https://www.wowhead.com/tbc/npc=5623/wastewander-assassin
**Expected behaviour**: 
All pirate/Wastewander mobs in a zone with a goblin town should give rep to that specific goblin's town+50% spillover for the other 3, up to 11999/12k honored, but still give spillover rep with the other 3 even past honored.
**Server Revision**: 
3968

**Comment by Wolffenstein** [comment]
Fixed in rev 3973.
