### ISSUE TITLE
Quests that scale with lvl (class quests) do not award gold for completing them at max lvl

### ISSUE THREAD

**Issue by ghost** [Atlantiss/NetherwingBugtracker#8921]
[//]: # (Enclose links to things related to the bug using http://wowhead.com or any other TBC database.)
[//]: # (You can use screenshot ingame to visual the issue.)
[//]: # (Write your tickets according to the format:)
[//]: # ([Quest][Azuremyst Isle] Red Snapper - Very Tasty!)
[//]: # ([NPC] Magistrix Erona)
[//]: # ([Spell][Mage] Fireball)
[//]: # ([Npc][Drop] Ghostclaw Lynx)
[//]: # ([Web] Armory doesnt work)
[//]: # (To find server revision type `.server info` command in the game chat.)

**Description**: 
https://www.wowhead.com/tbc/quest=7646/the-divination-scryer This is but one example of a quest in question. Most class quests scale with the player's level, thus completing these at max lvl should award gold as if it was a level 70 quest completed, but currently award none. I turned in this specific quest and was awarded with nothing and the follow up, the last in the chain, says it will also award me with nothing. However if a quest is to reward gold it will usually say under the rewards, for example the quest Establishing New Outposts prior to lvl 70 would have rewarded me with 90s, but at 70 now says it will award me with 1g 47s. So the fact the follow up says no rewards tells me it wont give any. This also makes me assume ALL class quests that scale with level will also not award gold, despite there being comments on wowhead that state they DO. Any quest on wowhead who's level is said to be "-1" means the quest(s) scale with the player's level in terms of xp given for completion.
**Current behaviour**:
The quests in question do not give gold once max lvl (70
**Expected behaviour**: 
The quest(s) should work like normal quests and give gold at max lvl (70)
**Server Revision**: 
3971

**Comment by Wolffenstein** [comment]
Fixed in rev 3973.
