### ISSUE TITLE
Accepting the quest The Forging of Quel'Serrar gives the wrong item

### ISSUE THREAD

**Issue by ghost** [Atlantiss/NetherwingBugtracker#8922]
[//]: # (Enclose links to things related to the bug using http://wowhead.com or any other TBC database.)
[//]: # (You can use screenshot ingame to visual the issue.)
[//]: # (Write your tickets according to the format:)
[//]: # ([Quest][Azuremyst Isle] Red Snapper - Very Tasty!)
[//]: # ([NPC] Magistrix Erona)
[//]: # ([Spell][Mage] Fireball)
[//]: # ([Npc][Drop] Ghostclaw Lynx)
[//]: # ([Web] Armory doesnt work)
[//]: # (To find server revision type `.server info` command in the game chat.)

**Description**: 
In it's current form, you have 20min after accepting the quest to down Onyxia and use the item, instead of obtaining the base item, having her breath on it, then obtain the heated version and using that on her corpse.
**Current behaviour**:
Accepting the quest gives the player https://www.wowhead.com/tbc/item=18488/heated-ancient-blade
**Expected behaviour**: 
Accepting the quest should give the player https://www.wowhead.com/tbc/item=18489/unfired-ancient-blade
**Server Revision**: 
3972

**Comment by Wolffenstein** [comment]
Fixed in rev 3973.
