### ISSUE TITLE
Quest - Mission possible but not probable

### ISSUE THREAD

**Issue by Godmatik** [Atlantiss/NetherwingBugtracker#8924]
Rogue quest - there is some issue with kill tracking that occurs whenever a rogue is running a quest addon. It will keep the tracking stuck at 1/2 for one or more of the needed mobs.

Turning off the quest addon does resolve the issue, but it is only this specific quest that causes problems for them and thus lots of confused requests on Discord that it is "bugged".

Is the kill tracking for this quest handled differently compared to others that causes it to break with addons - any way to resolve this?

https://www.wowhead.com/classic/quest=2478/mission-possible-but-not-probable

**Comment by Wolffenstein** [comment]
I don't see anything weird or specific about this quest so dunno 🤷
