### ISSUE TITLE
Redemption quest not completeable

### ISSUE THREAD

**Issue by ghost** [Atlantiss/NetherwingBugtracker#8925]
[//]: # (Enclose links to things related to the bug using http://wowhead.com or any other TBC database.)
[//]: # (You can use screenshot ingame to visual the issue.)
[//]: # (Write your tickets according to the format:)
[//]: # ([Quest][Azuremyst Isle] Red Snapper - Very Tasty!)
[//]: # ([NPC] Magistrix Erona)
[//]: # ([Spell][Mage] Fireball)
[//]: # ([Npc][Drop] Ghostclaw Lynx)
[//]: # ([Web] Armory doesnt work)
[//]: # (To find server revision type `.server info` command in the game chat.)

**Description**: 
https://www.wowhead.com/tbc/quest=5742/redemption
**Current behaviour**:
After accepting the quest you can't talk to Tirion to finish it
**Expected behaviour**: 
After accepting the quest, talking to Tirion should give you dialog options, going through all of those will complete the quest.
**Server Revision**: 
3972

**Comment by Godmatik** [comment]
You need to do /sit I believe
