### ISSUE TITLE
[Spell][Rogue][Paladin] Cloak of Shadows is giving resistance to Judgement of Justice

### ISSUE THREAD

**Issue by Spartanv** [Atlantiss/NetherwingBugtracker#8926]
**Description**: 

Judgement of Justice should be completely unresistable

**Current behaviour**:

Currently Cloak of Shadows is giving resistance to Judgement of Justice.

**Expected behaviour**: 
![image](https://github.com/Atlantiss/NetherwingBugtracker/assets/11991518/59cd04d2-8658-4e3b-9fb2-7c05f7259420)
https://www.wowhead.com/tbc/spell=31895/seal-of-justice#comments:id=10388:reply=27742
Video from TBC classic with time stamp included
https://youtu.be/ThnIN3GHaAs?t=4055

**Server Revision**: 3972

**Comment by ghost** [comment]
Also Vanish, Improved Sprint, and likely other similar abilites can remove JoJ (tested on PTR).
https://youtu.be/HuuhBW_fxeE?feature=shared&t=423
07:04 Rogue Vanished to Cheap Shot, JoJ still up.

**Comment by Wolffenstein** [comment]
Fixed in rev 3974.
