### ISSUE TITLE
[API] Normal mode kills for T5/T6 raids still counted as "heroic" on Stormforge Logs

### ISSUE THREAD

**Issue by Godmatik** [Atlantiss/NetherwingBugtracker#8927]
The normal/heroic distinction works fine for Zul'aman - but for any tier 5 or tier 6 boss kill if was done on normal, it is still labeled as "heroic" in the API.

Examples:
https://logs.stormforge.gg/netherwing/log/netherwing/219838
https://logs.stormforge.gg/netherwing/log/netherwing/221414

**Comment by Wolffenstein** [comment]
Fixed in rev 3974.
