### ISSUE TITLE
Saber mounts are bigger than they should be, code wise

### ISSUE THREAD

**Issue by ghost** [Atlantiss/NetherwingBugtracker#8928]
[//]: # (Enclose links to things related to the bug using http://wowhead.com or any other TBC database.)
[//]: # (You can use screenshot ingame to visual the issue.)
[//]: # (Write your tickets according to the format:)
[//]: # ([Quest][Azuremyst Isle] Red Snapper - Very Tasty!)
[//]: # ([NPC] Magistrix Erona)
[//]: # ([Spell][Mage] Fireball)
[//]: # ([Npc][Drop] Ghostclaw Lynx)
[//]: # ([Web] Armory doesnt work)
[//]: # (To find server revision type `.server info` command in the game chat.)

**Description**: 
During 2021 I personally tested mount sizes for the basic 100% speed racial mounts of each race while being ridden on a Male cow and gote man shaman. For the purpose of this test I was also a shaman for the 30% size buff during hero/lust. On their instant 80 pvp only server, they have a vendor that gives you all the basic race mounts, the open world is empty so I can go to Stormwind as horde without anything getting in my way. I used hero/lust and wedged myself into the doorway of the bank in Stormwind and the only mounts able to be ridden there were the horde wolf mount and the Alliance saber mount. Now the thing is this is a 3.3.5 server, but I find it hard to believe that the bank in SW and vanilla mounts would change much between 2.4.3 and 3.3.5.

In addition, I also tested over 350+ mounts during legion in an even smaller crevice I found in suramar, using toys to increase my size. This is a very important mater that I care about and have put a lot of time into testing these sorts of things. You may ask me for 2.4.3 proof, but I would also ask YOU for proof it does NOT work the way I am describing, as from my experiments there are a handful of different mouse 'sizes' that have nothing to do with the actual visual size of the mount as one of the biggest mounts in the game is considered a 'tiny' mount in retail and that is the horde 2017 Blizzcon zeplin mount. I will now go over some of these different mount sizes.
First is the 'tiny' size, this does not at all increase the player size when ridden so anything you can fit into unmounted you can while on these mounts. Pre wrath there are none, but examples of these mounts are the chopper mounts from eng in wrath and the 2 person flying rocket from RAF added in wrath as well as the 2017 blizzcon mounts.
Next is the 'small' these mounts increase the player size a small amount but not by much, examples are the Saber and Wolf mounts.
Next is the 'medium' These are mounts like the Horse or Raptor mounts.
Next is the 'large' examples of these are the Kodo and Belf hawk strider mounts.
Finally we have the 'huge' mounts which once again don't exist in BC, examples are the mammoth mounts.

It may not even be a problem with the mounts but instead a problem with the buildings or something else, but I have no idea as I'm not a coder.
**Current behaviour**:
The Saber mounts on alliance are bigger than they should be, code wise. 
**Expected behaviour**: 
Saber/Wolf mounts, even when ridden by a Male Tauren/Gote man with hero buffs, should be still small enough to fit inside doorways as small as what the Stormwind Bank doorway is.
**Server Revision**: 
3973

**Comment by ghost** [comment]
So I just tested it and it is a mount issue, saber and charger are same size code wise in water. I get dismounted at exact same spot when walking into crystal lake in Elwynn, behind goldshire. The saber should dismount you first as it is smaller, and the charger, being bigger should allow you to go deeper into the water before it dismounts you.

**Comment by Wolffenstein** [comment]
WotLK introduced SMSG_MOVE_SET_COLLISION_HGT opcode which is used by the server to adjust player's collision, in WotLK private server cores it's sent when you mount and dismount, likely to achieve the result you're after.

2.4.3 client DOES NOT have support for this. All collision calculations and control for players is handled client-side. From the server perspective I have no way of making you fit through there if the client does not let you. All I do is change your UNIT_FIELD_MOUNTDISPLAYID field to whatever mount you're trying to get on and that's it, the rest is all on the client.

Dismount in water is a completely different thing and depends on how the core calculates the periodic detection of whether you are in water or not. Nothing to do with collision.
