### ISSUE TITLE
Teleport: Stormwind spell has you facing wrong way after teleport, unlike it's portal version.

### ISSUE THREAD

**Issue by ghost** [Atlantiss/NetherwingBugtracker#8929]
[//]: # (Enclose links to things related to the bug using http://wowhead.com or any other TBC database.)
[//]: # (You can use screenshot ingame to visual the issue.)
[//]: # (Write your tickets according to the format:)
[//]: # ([Quest][Azuremyst Isle] Red Snapper - Very Tasty!)
[//]: # ([NPC] Magistrix Erona)
[//]: # ([Spell][Mage] Fireball)
[//]: # ([Npc][Drop] Ghostclaw Lynx)
[//]: # ([Web] Armory doesnt work)
[//]: # (To find server revision type `.server info` command in the game chat.)

**Description**: 
https://www.wowhead.com/tbc/spell=3561/teleport-stormwind
**Current behaviour**:
You face 180 the wrong way and blinking will put you at the far end of the room where that teleporter does nothing and is just cosmetic/set decoration
**Expected behaviour**: 
After self teleporting, you should be facing out of the room so simply blinking is enough to get you to the next room
**Server Revision**: 
3973

**Comment by Wolffenstein** [comment]
Fixed in rev 3974.
