### ISSUE TITLE
Goreclaw the Ravenous can't be skinned

### ISSUE THREAD

**Issue by maronics** [Atlantiss/NetherwingBugtracker#893]
See title. Mob ID 23873

Patch 2.4.0 (2008-03-25): Goreclaw the Ravenous can now be skinned.

**Server Revision**: 2083

**Comment by Shanghi** [comment]
He'll be skinnable after revision 2221. Since non-TBC areas in Azeroth are using 2.3+ versions of everything, I guess he should always be skinnable instead of waiting until 2.4.
