### ISSUE TITLE
The Ring of Blood quests requires you to be friendly with the nagrand reps

### ISSUE THREAD

**Issue by ghost** [Atlantiss/NetherwingBugtracker#8930]
[//]: # (Enclose links to things related to the bug using http://wowhead.com or any other TBC database.)
[//]: # (You can use screenshot ingame to visual the issue.)
[//]: # (Write your tickets according to the format:)
[//]: # ([Quest][Azuremyst Isle] Red Snapper - Very Tasty!)
[//]: # ([NPC] Magistrix Erona)
[//]: # ([Spell][Mage] Fireball)
[//]: # ([Npc][Drop] Ghostclaw Lynx)
[//]: # ([Web] Armory doesnt work)
[//]: # (To find server revision type `.server info` command in the game chat.)

**Description**: 
[The Ring of Blood](https://www.wowhead.com/tbc/quest=9962/the-ring-of-blood-brokentoe#comments) this is the first quest in the chain, https://www.wowhead.com/tbc/npc=18471/gurgthock this is the guy that gives all the quests. Nowhere on either page mentions anything about needing to be friendly with the factions to pick up his quests.
**Current behaviour**:
The quest chain requires you to be friendly with the alli/horde base in nagrand
**Expected behaviour**: 
The quest chain has nothing to do with rep with either faction's bases in Nagrand
**Server Revision**: 
3973

**Comment by Godmatik** [comment]
Technically it requires you to be neutral right now.

But I agree that I can't find any evidence that this should be a requirement.

**Comment by Wolffenstein** [comment]
Fixed in rev 3974.
