### ISSUE TITLE
Crit to def capped tank

### ISSUE THREAD

**Issue by alandrar** [Atlantiss/NetherwingBugtracker#8933]
**Description**: I've been "critted" by Illidari Blood Lord 72lvl Elite to overcapped tank (540 defense) - https://www.wowhead.com/tbc/npc=23397/illidari-blood-lord 
This is not first case, but this one i didn't forget to screen shot
**Current behaviour**: Crits overcapped tank

**Expected behaviour**: Shouldn't crit

**Server Revision**: 3975

![stats](https://github.com/Atlantiss/NetherwingBugtracker/assets/58438160/2ec46879-47a0-4788-9de0-6e4a240f19a1)
![Crit](https://github.com/Atlantiss/NetherwingBugtracker/assets/58438160/b44b1177-a965-4392-9534-3d8d2e1daa01)

**Comment by Godmatik** [comment]
Did this occur to you today, or did this also happen previously before the server update?

**Comment by alandrar** [comment]
It happend even before update, cca 1-2 months ago, but this exact crit was 18.2.2024

**Comment by Godmatik** [comment]
Interesting, having played a tank and also raided for a long time, I have never once experienced this or heard of anyone else with a similar problem, so guess I can't offer any further information.

**Comment by alandrar** [comment]
any new info ? will you try to fix it ?

**Comment by Godmatik** [comment]
Unable to reproduce this, please provide a video or screenshot of the crit occurring if you can

**Comment by alandrar** [comment]
Hey, it’s not possible it occurs randomly i’d have to record 24/7, but
never mind… i’m not playing the warr anymore, so i don’t care

út 2. 7. 2024 v 0:24 odesílatel Matik ***@***.***> napsal:

**Comment by Godmatik** [comment]
Will close for now then, have talked to several tanks and no one has experienced this issue that are defense capped.
