### ISSUE TITLE
Viper sting does not break Freezing Trap

### ISSUE THREAD

**Issue by Godmatik** [Atlantiss/NetherwingBugtracker#8934]
Viper sting when used on a target with freezing trap should break the trap with the mana drain tick.

This was reported previously and fixed, but it's possible the new aura branch broke it again.

EDIT: I am being told all mana drain effects should break all forms of CC similar to as if you are dealing damage.

https://github.com/Atlantiss/NetherwingBugtracker/issues/3994

**Comment by Wolffenstein** [comment]
![image](https://github.com/Atlantiss/NetherwingBugtracker/assets/1576644/855030e4-9afc-45dd-9406-c8260685bfd3)
it works fine
