### ISSUE TITLE
Mage self teleport: Stormwind spell still not correct positioning, farther back in room than should be

### ISSUE THREAD

**Issue by ghost** [Atlantiss/NetherwingBugtracker#8936]
[//]: # (Enclose links to things related to the bug using http://wowhead.com or any other TBC database.)
[//]: # (You can use screenshot ingame to visual the issue.)
[//]: # (Write your tickets according to the format:)
[//]: # ([Quest][Azuremyst Isle] Red Snapper - Very Tasty!)
[//]: # ([NPC] Magistrix Erona)
[//]: # ([Spell][Mage] Fireball)
[//]: # ([Npc][Drop] Ghostclaw Lynx)
[//]: # ([Web] Armory doesnt work)
[//]: # (To find server revision type `.server info` command in the game chat.)

**Description**: 
So after the fix from before to make you face the right direction, somehow this also had us move back in the room we teleport into. Currently when I use my personal teleport spell, I get put at exactly 38.66 80.25 according to my tomtom addon. When I use my portal spell I get put at exactly 38.01 80.84. Both spells should have the same exact coords and direction when porting in. 
https://www.wowhead.com/tbc/spell=3561/teleport-stormwind https://www.wowhead.com/tbc/spell=10059/portal-stormwind
**Current behaviour**:
The teleport version puts you farther back in the room than the portal version.
**Expected behaviour**: 
Both the portal and teleport versions should put you in the exact same spot
**Server Revision**: 
3975

**Comment by Wolffenstein** [comment]
it's the portal one that's wrong

**Comment by Wolffenstein** [comment]
fixed
