### ISSUE TITLE
Rep from Blood Furnace instance on normal mode incorrect

### ISSUE THREAD

**Issue by ghost** [Atlantiss/NetherwingBugtracker#8939]
[//]: # (Enclose links to things related to the bug using http://wowhead.com or any other TBC database.)
[//]: # (You can use screenshot ingame to visual the issue.)
[//]: # (Write your tickets according to the format:)
[//]: # ([Quest][Azuremyst Isle] Red Snapper - Very Tasty!)
[//]: # ([NPC] Magistrix Erona)
[//]: # ([Spell][Mage] Fireball)
[//]: # ([Npc][Drop] Ghostclaw Lynx)
[//]: # ([Web] Armory doesnt work)
[//]: # (To find server revision type `.server info` command in the game chat.)

**Description**: 
I hit honored while mid run in Furnace so the first boss for sure gave rep as I was friendly still, but the 2nd and 3rd bosses did not. And the felguards with hammers were still giving rep. https://www.wowhead.com/tbc/npc=17400/felguard-annihilator these are the felguards. The bosses are https://www.wowhead.com/tbc/npc=17377/kelidan-the-breaker https://www.wowhead.com/tbc/npc=17380/broggok and https://www.wowhead.com/tbc/npc=17381/the-maker
Notice that on the felguard page it says "stops at friendly" this means 5999/6k friendly, where as the boss pages do not have that and should give rep all the way to max even on normal. We then did a ramparts run and I got NO rep at all from trash or bosses. 1st boss https://www.wowhead.com/tbc/npc=17306/watchkeeper-gargolmar 2nd boss https://www.wowhead.com/tbc/npc=17308/omor-the-unscarred and 3rd boss(s) https://www.wowhead.com/tbc/npc=17537/vazruden as you can see on these pages they also do not say they stop giving rep either.
**Current behaviour**:
Some trash mobs still are giving me 6 rep (with 20% bonus) while the bosses are giving no rep at all now
**Expected behaviour**: 
The bosses are the only mobs that keep giving rep past 5999/6k friendly
**Server Revision**: 
3978

**Comment by Godmatik** [comment]
https://github.com/Atlantiss/NetherwingBugtracker/issues/8572

Info here as well

**Comment by ghost** [comment]
Fuck this server and fuck you guys.
