### ISSUE TITLE
[Warrior][Spell] Missing skill interaction between Sweeping Strikes and Execute

### ISSUE THREAD

**Issue by FrozenBread** [Atlantiss/NetherwingBugtracker#894]
[//]: # (Enclose links to things related to the bug using http://wowhead.com or any other TBC database.)
[//]: # (You can use screenshot ingame to visual the issue.)
[//]: # (Write your tickets according to the format:)
[//]: # ([Quest][Azuremyst Isle] Red Snapper - Very Tasty!)
[//]: # ([NPC] Magistrix Erona)
[//]: # ([Spell][Mage] Fireball)
[//]: # ([Npc][Drop] Ghostclaw Lynx)
[//]: # ([Web] Armory doesnt work)

**Description**: 
Sweeping strikes mirrors all direct damage attacks from the player warrior into the closest target of that one receiving the original hit.

**Current behaviour**: I've tested several skills, Heroic Strike, Cleave, Slam, Autoattack, and so far they are mirroring the attack correctly to the nearest target of the hit receiver, except for Execute. Execute should be no exception, all damage attacks should be mirrored by Sweeping Strikes, even the damage from Hamstring is being correctly mirrored, and not applying any debuffs, as it should be.

**Expected behaviour**: When Sweeping Strikes buff is up and Execute is used, a mirror hit should hit the nearmost target of the Execute target

**Server Revision**: 
[2083]

**Comment by Easyfraggy** [comment]
WoW Icon 16x16 Patch 1.11.0 (20-Jun-2006): This spell has a number of fixes: When used in conjunction with Execute and the second victim is below 20% health, they will be hit with the full Execute amount. If the second victim is not below 20% health, they will be hit with normal melee swing damage; If the ability you are using does not deal damage, it will not use a charge of Sweeping Strikes; The extra attack it generates when used with Whirlwind now has the correct damage range; The additional attacks generated by this ability will now properly take into account the armor of the second target.

Are you saying that execute doesn't do a normal swing from SS when secondary mob is over 20% hp?

**Comment by FrozenBread** [comment]
It doesn't, no hit on the secondary mob whatsoever, just on the primary target.

**Comment by Easyfraggy** [comment]
I just tested it aswell, y if secondary mob is above 20% there should be a normal swing. Not a full execute. However below 20% it should be full execute damage.

**Comment by FrozenBread** [comment]
Yeah, that is correct, thank you for finding more specific facts on it

**Comment by Wolffenstein** [comment]
Fixed in rev 2390.

**Comment by liek0r** [comment]
I was just about to open a new issue about this. 

It's not fixed in rev 2604.

https://streamable.com/ibasj

In the clip, mirrored damage are as follows: 

* Auto for 187
* Slam for 221
* Auto for 154
* Slam (crit) 392

Execute ignored.

**Comment by liek0r** [comment]
@Wolffenstein please reopen.

**Comment by Easyfraggy** [comment]
I think this was fixed with the execute rework? Not sure tho!

**Comment by webbelito** [comment]
Do we have any update on this issue?

**Comment by Tereneckla** [comment]
![image](https://user-images.githubusercontent.com/50233983/71910869-069a5880-3173-11ea-8ac1-b4cb1190010a.png)
Collidus was low HP
The Wildhammer Guard is full.
