### ISSUE TITLE
Effect  Storm Gauntlets  wrong work

### ISSUE THREAD

**Issue by Perva4** [Atlantiss/NetherwingBugtracker#8940]
https://www.wowhead.com/tbc/item=12632/storm-gauntlets#created-by-spell ; https://www.wowhead.com/tbc/spell=16615/add-lightning-dam-weap-03
![Light](https://github.com/Atlantiss/NetherwingBugtracker/assets/156111501/67de01cc-b507-4ba5-bdfb-c45733d7cc4f)
spell=16615

**Description**: Equip : Adds 3 Lightning damage to your melee attacks.

**Current behaviour**: This is 3 damage is physical school  damage and  does not affect trigger talent Retribution *Vengeance* or trinket * Hand of Justice* or effect axe Dark Edge of Insanity.. or another...  this  is 3 damage in general, it does not affect anything, does not trigger effects, talents, etc
**Expected behaviour**: this 3 damage is physical school and must have be effect to start procs or talant what
video : https://www.youtube.com/watch?v=v0JBlG9g9yY&t=68s 
**Server Revision**: 3975

**Comment by Wolffenstein** [comment]
Fixed in rev 3979.
