### ISSUE TITLE
Mana Drain Trigger (Black Grasp of the Destroyer)

### ISSUE THREAD

**Issue by Perva4** [Atlantiss/NetherwingBugtracker#8941]
https://www.wowhead.com/classic/spell=27522/mana-drain-trigger
![ttrr](https://github.com/Atlantiss/NetherwingBugtracker/assets/156111501/5ea60de4-eb78-4c14-9841-6b5eff4bec82)
![oopp](https://github.com/Atlantiss/NetherwingBugtracker/assets/156111501/037a211a-0d01-43f4-8bdc-378d80df30e7)
spell=27522

**Description**: On successful melee or ranged attack gain 8 mana and if possible drain 8 mana from the target.
Thiss spell have EffectBonusCoefficient 1 

**Current behaviour**: does not scale with spell power
**Expected behaviour**: should scale with spell power

**Server Revision**: 3975

**Comment by Wolffenstein** [comment]
Fixed in rev 3979.
