### ISSUE TITLE
Netherbloom Pollen can give negative effects despite them being removed in 2.1

### ISSUE THREAD

**Issue by ghost** [Atlantiss/NetherwingBugtracker#8942]
[//]: # (Enclose links to things related to the bug using http://wowhead.com or any other TBC database.)
[//]: # (You can use screenshot ingame to visual the issue.)
[//]: # (Write your tickets according to the format:)
[//]: # ([Quest][Azuremyst Isle] Red Snapper - Very Tasty!)
[//]: # ([NPC] Magistrix Erona)
[//]: # ([Spell][Mage] Fireball)
[//]: # ([Npc][Drop] Ghostclaw Lynx)
[//]: # ([Web] Armory doesnt work)
[//]: # (To find server revision type `.server info` command in the game chat.)

**Description**: 
https://www.wowhead.com/tbc/spell=28712/netherbloom-pollen#comments only comment specifies that all of the negative effects from picking Netherbloom were removed. https://www.wowhead.com/tbc/search?q=Netherbloom%20pollen#uncategorized-spells here is a list of all 10 effects. The ones which are negative effects were removed in patch 2.1.
**Current behaviour**:
All 10 Netherbloom effects exist in game
**Expected behaviour**: 
Only the positive effects should still exist for picking a Netherbloom
**Server Revision**: 
3978

**Comment by Wolffenstein** [comment]
Which negative one did you get? There's only positive ones in the code.

**Comment by ghost** [comment]
I got several, first one I got was -50 str, then -50 int and as a mage that was super annoying. I am pretty sure I got -50 agi as well but don't remember, was not in netherstorm long. The ones that are benefits are supposed to be buffs, not debuffs. And the debuff when I had it said my stats were reduced, not increased. I picked like 2 or 3 of them and only got the debuffs.

**Comment by Godmatik** [comment]
![netherbloom pollen](https://github.com/Atlantiss/NetherwingBugtracker/assets/37913400/076bb577-3fe5-4c88-9163-1e240520dfbd)

**Comment by Godmatik** [comment]
[Patch 2.1.0](22-May-2007): Netherbloom no longer causes negative effects, although the positive effects happen less frequently. Additionally, the effects will not replace one another.

**Comment by ghost** [comment]
Fuck this server and fuck you guys.
