### ISSUE TITLE
A Donation of Runecloth - rep turn-in for Trolls

### ISSUE THREAD

**Issue by Godmatik** [Atlantiss/NetherwingBugtracker#8943]
**Current behaviour**:
https://www.wowhead.com/classic/quest=7836/a-donation-of-runecloth

Quest is giving you Orc reputation

**Expected behaviour**: 
Should give you Troll reputation

**Server Revision**: 
3978

**Comment by Wolffenstein** [comment]
![image](https://github.com/Atlantiss/NetherwingBugtracker/assets/1576644/8b30bcaf-5264-46ff-8ece-d5c58e8fa063)
The one you linked works fine.

**Comment by Wolffenstein** [comment]
Fixed in rev 3979.
