### ISSUE TITLE
NPCs on Zepplins are constantly breaking.

### ISSUE THREAD

**Issue by Godmatik** [Atlantiss/NetherwingBugtracker#8944]
![npcs](https://github.com/Atlantiss/NetherwingBugtracker/assets/37913400/27d21473-023d-49d2-8f65-e650e91eb0c2)

Org to STV and Org to UC Zepplin almost always has all the NPCs stacked and stuck like this. Didn't check UC to STV Zep

Rev 3979

**Comment by Godmatik** [comment]
Similar issue with NPCs on boats

**Comment by Wolffenstein** [comment]
Fix pending
