### ISSUE TITLE
[API] T5/T6 Difficulty still not showing properly in Stormforge Logs

### ISSUE THREAD

**Issue by Godmatik** [Atlantiss/NetherwingBugtracker#8947]
![image](https://github.com/Atlantiss/NetherwingBugtracker/assets/37913400/faaeac18-5163-4165-98a2-ed5eabc2059e)

![image](https://github.com/Atlantiss/NetherwingBugtracker/assets/37913400/00a6e4f5-7f90-44d8-91f8-5f3b3d7b8288)

The above images are from Query.

According to him, the difficulty (0) of the API from fights is coming over as 10man, and so it defaults to 25m Heroic for these encounters

**Comment by Wolffenstein** [comment]
Fixed in rev 3980.
