### ISSUE TITLE
Blueleaf tubers

### ISSUE THREAD

**Issue by Mewmewww** [Atlantiss/NetherwingBugtracker#895]
[//]: # (Enclose links to things related to the bug using http://wowhead.com or any other TBC database.)
[//]: # (You can use screenshot ingame to visual the issue.)
[//]: # (Write your tickets according to the format:)
[//]: # ([Quest][Azuremyst Isle] Red Snapper - Very Tasty!)
[//]: # ([NPC] Magistrix Erona)
[//]: # ([Spell][Mage] Fireball)
[//]: # ([Npc][Drop] Ghostclaw Lynx)
[//]: # ([Web] Armory doesnt work)

**Description**: Squirrels should dig up Blueleaf tubers.

**Current behavior**: They do dig up blueleaf tubers, but they currently go to despawned, picked up tubers and they end up not picking it up . at the last boss of the dungeon, once jumping down the cliff, your squirrels won't follow you down. I tried to resummon only to have it fail.

**Expected behavior**: Should find new tubers instead of despawned ones. Squirrels should follow you down the cliff but they dont.

**Server Revision**: 2083 NW

**Comment by lordsval** [comment]
I just ran RFK and couldn't find any blueleaf tubers with my gopher out. Not that important but I guess it could be misleading or annoying.

**Comment by Tereneckla** [comment]
To clarify this:
Current: The gopher runs to the nearest tuber spawnpoint, no matter if a tuber has respawned there already.
Expectation: The gopher ignores the despawned tuber and picks the nearest spawned tuber to reveal.
https://www.youtube.com/watch?v=S9lrdq0AeoM


I don't know if gophers should follow you down cliffs, but currently if you jump down a cliff with a summoned gopher you can't summon a new one.
