### ISSUE TITLE
Nightmare Vine debuffs you when picked up

### ISSUE THREAD

**Issue by ghost** [Atlantiss/NetherwingBugtracker#8950]
[//]: # (Enclose links to things related to the bug using http://wowhead.com or any other TBC database.)
[//]: # (You can use screenshot ingame to visual the issue.)
[//]: # (Write your tickets according to the format:)
[//]: # ([Quest][Azuremyst Isle] Red Snapper - Very Tasty!)
[//]: # ([NPC] Magistrix Erona)
[//]: # ([Spell][Mage] Fireball)
[//]: # ([Npc][Drop] Ghostclaw Lynx)
[//]: # ([Web] Armory doesnt work)
[//]: # (To find server revision type `.server info` command in the game chat.)

**Description**: 
https://www.wowhead.com/tbc/object=181280/nightmare-vine#comments Top comment "Looting a Nightmare Vine will now properly no longer apply poison when the node is looted."
**Current behaviour**:
When picking up a Nightmare Vine you are poisoned by https://www.wowhead.com/tbc/spell=28721/nightmare-pollen#comments Nightmare Pollen
**Expected behaviour**: 
As of patch 2.4.3, which this server is supposed to be off of, it no longer poisons you.
**Server Revision**: 
3979

**Comment by Godmatik** [comment]
![nightmare vine](https://github.com/Atlantiss/NetherwingBugtracker/assets/37913400/2c30f101-c18f-462e-80b5-d827c40c7320)

This reply comment states that it is still happening. 

Unlike your netherbloom report, I don't see any documented evidence that the poison was removed at some point in TBC.

![vine](https://github.com/Atlantiss/NetherwingBugtracker/assets/37913400/cb767e57-2fef-414d-8951-271a0ab4c006)

**Comment by Godmatik** [comment]
The change was made in patch 2.4.3

We are in patch 2.3 currently. The server is based on 2.4.3 for player spells/talents/abilities only, the reason of content is progressive and roughly follows original TBC timeline.

**Comment by Godmatik** [comment]
That change was made in patch 2.4.3

We are in patch 2.3 currently. The server is based on 2.4.3 for player spells/talents/abilities only, the release of content along with other changes are progressive and roughly follows original TBC timeline. (similar to how a Wrath client is 3.3.5, but a fresh server starts with 3.0 for things like smelt titansteel cooldown)

**Comment by ghost** [comment]
Fuck this server and fuck you guys.
