### ISSUE TITLE
Retribution auro flicking on and off

### ISSUE THREAD

**Issue by ghost** [Atlantiss/NetherwingBugtracker#8952]
[//]: # (Enclose links to things related to the bug using http://wowhead.com or any other TBC database.)
[//]: # (You can use screenshot ingame to visual the issue.)
[//]: # (Write your tickets according to the format:)
[//]: # ([Quest][Azuremyst Isle] Red Snapper - Very Tasty!)
[//]: # ([NPC] Magistrix Erona)
[//]: # ([Spell][Mage] Fireball)
[//]: # ([Npc][Drop] Ghostclaw Lynx)
[//]: # ([Web] Armory doesnt work)
[//]: # (To find server revision type `.server info` command in the game chat.)

**Description**: 
When I party with my friend his paladin, and he uses retribution aura, it flickers on and off as a buff to me.

Please mention, the pally is 70 and my char 50, thus I get a 1 rank lower aura.

**Current behaviour**:
at least retribution aura flickers on and off

**Expected behaviour**: 
it stays on as long as I am in range

**Server Revision**: 
Netherwing 3979

** extra **
I remove cache everytime before I launch the game.

**Comment by Perva4** [comment]
that and i see on Trushot Aura oh Pet Hunter ....

**Comment by ghost** [comment]
Also in the combat log you see it adding and fading as well, at a very high ratio.

**Comment by Godmatik** [comment]
![fghfhgfh](https://github.com/user-attachments/assets/ef7a6789-4ab6-4af8-a0ca-f506f7898f8e)

I do not see it flickering on and off in my buffs however (default UI) and it seems to function just fine

Visual issue only with combat log - occurs only if you have an aura that is using downranked version automatically on lower level. This applies to all buff auras, not just retribution aura.

**Comment by Godmatik** [comment]
Fixed in next update
