### ISSUE TITLE
Hellfire Fortifications initial quest for Alliance not available

### ISSUE THREAD

**Issue by ghost** [Atlantiss/NetherwingBugtracker#8955]
[//]: # (Enclose links to things related to the bug using http://wowhead.com or any other TBC database.)
[//]: # (You can use screenshot ingame to visual the issue.)
[//]: # (Write your tickets according to the format:)
[//]: # ([Quest][Azuremyst Isle] Red Snapper - Very Tasty!)
[//]: # ([NPC] Magistrix Erona)
[//]: # ([Spell][Mage] Fireball)
[//]: # ([Npc][Drop] Ghostclaw Lynx)
[//]: # ([Web] Armory doesnt work)
[//]: # (To find server revision type `.server info` command in the game chat.)

**Description**: 
The horde have both the first quest and the daily they can do for a total of 6 marks on their first day doing it, if they do them both, the alliance do not seem to have that. I am not able to pick up the quest on my mage, I was just given the daily instead. https://www.wowhead.com/tbc/quest=13408/hellfire-fortifications#comments the first quest and https://www.wowhead.com/tbc/quest=10106/hellfire-fortifications the daily quest. You will probably notice that it says "added in 3.3" but if that is the case then why do the horde have the quest? I know for a fact I did it on my paladin before I faction changed, I got 6 tokens my first day in hellfire on him. https://www.wowhead.com/tbc/npc=18266/warrant-officer-tracy-proudwell This is the NPC.
**Current behaviour**:
The NPC only offers the daily, no initial quest
**Expected behaviour**: 
You should have to complete the initial quest first before unlocking the daily after.
**Server Revision**: 
3980

**Comment by Godmatik** [comment]
Did you faction change the character? Might have something to do with this bug

**Comment by ghost** [comment]
No, my mage was always alliance.

**Comment by ghost** [comment]
Fuck this server and fuck you guys.
