### ISSUE TITLE
[Quest] I can't open an Ethereum Prison whereas I got an Ethereum Prison Key

### ISSUE THREAD

**Issue by philippehenri-gosselin** [Atlantiss/NetherwingBugtracker#8956]
Realm where you noticed the issue: Netherwing

Description: I can't open an Ethereum Prison whereas I got an Ethereum Prison Key

Current behaviour: I can't open an Ethereum Prison whereas I got an Ethereum Prison Key. I click on an Ethereum Prison: doesn't work. I click on a Ethereum Prison Key, I got a mouse cursor for interaction, but I can't use it on an Ethereum Prison. When I pass my cursor over an Ethereum Prison, I don't have a sub message in the tooltip telling it requires an Ethereum Prison Key for opening.

Expected behaviour: I can open an Ethereum Prison with an Ethereum Prison Key

**Comment by Godmatik** [comment]
Unable to reproduce, and not heard of anyone else experiencing this issue.

Try deleting cache folder with the game client closed, and also disable addons
