### ISSUE TITLE
help pls

### ISSUE THREAD

**Issue by skrillexkratta** [Atlantiss/NetherwingBugtracker#8957]
[//]: # (Enclose links to things related to the bug using http://wowhead.com or any other TBC database.)
[//]: # (You can use screenshot ingame to visual the issue.)
[//]: # (Write your tickets according to the format:)
[//]: # ([Quest][Azuremyst Isle] Red Snapper - Very Tasty!)
[//]: # ([NPC] Magistrix Erona)
[//]: # ([Spell][Mage] Fireball)
[//]: # ([Npc][Drop] Ghostclaw Lynx)
[//]: # ([Web] Armory doesnt work)
[//]: # (To find server revision type `.server info` command in the game chat.)

**Description**: 
kara loot
**Current behaviour**:
 [Ring of Recurrence] i miss clicked and equiped shud be to my guild member can you guys pls help me reset the ring so i can give to him 
  ingame name snorke
![image](https://github.com/Atlantiss/NetherwingBugtracker/assets/162764901/106d0ce6-af7f-4802-bee1-0ff47650a0e6)

**Comment by skrillexkratta** [comment]
snorkel *

**Comment by Godmatik** [comment]
Open ticket ingame for a GM to help you.
