### ISSUE TITLE
[NPC] Pesterhide Snarler

### ISSUE THREAD

**Issue by totaemoeggerli** [Atlantiss/NetherwingBugtracker#896]
[//]: # (Enclose links to things related to the bug using http://wowhead.com or any other TBC database.)
[//]: # (You can use screenshot ingame to visual the issue.)
[//]: # (Write your tickets according to the format:)
[//]: # ([Quest][Azuremyst Isle] Red Snapper - Very Tasty!)
[//]: # ([NPC] Magistrix Erona)
[//]: # ([Spell][Mage] Fireball)
[//]: # ([Npc][Drop] Ghostclaw Lynx)
[//]: # ([Web] Armory doesnt work)

**Description**: 
[Pesterhide Snarler](https://www.wowhead.com/npc=4249/pesterhide-snarler) uses [Intimidating Growl](https://www.wowhead.com/spell=6576/intimidating-growl) too early or it shouldn't use it at all.
There are only 2 comments about this mob but there are many comments about [Steelsnap](https://www.wowhead.com/npc=4548/steelsnap#comments) (who is escorted by two Pesterhide Snarler) and the [quest](https://www.wowhead.com/quest=1131/steelsnap) associated with it. From 126 comments only 2 mention the ability, both during/after WotLK. 

By Vonara (9,914 – 2·19·64) on 2010/06/03 (Patch 3.3.3)
> His adds have an ability called Intimidating Growl that will send you RUNNING. You get around a 100% movement increase and you run around feared. It's a bit different from most fears, but you'll have to witness it to really see why.

By Clousy (6,501 – 1·13·37) on 2010/10/18 (Patch 4.0.1)
> ...I started attacking after two Growls - got Steelsnap down with little trouble ...

This is a really unique ability because it makes you run faster and it makes the fight with Steelsnap alot harder. If it was in the game during TBC someone would have commented on it druing tbc.

**Current behaviour**:
[Mob uses his ability around 8sec into the fight](https://gfycat.com/ImpossiblePrestigiousAsianelephant)

**Expected behaviour**: 
I've found 3 encounters with this mob in Joana's videos: [1 and 2](https://youtu.be/FG8pkhreZjU?t=9m15s) and [3](https://youtu.be/FG8pkhreZjU?t=16m46s). Those are relativly long fights but there is no Fear on the player or the pet.

**Server Revision**: 2083

**Comment by The14me** [comment]
both comment u post are from 3.0 or 4.0+
Spell is correct,but may need more delay or cast.

**Comment by Evolvee** [comment]
@aresbrutus @Easyfraggy @The14me bestiary link pls

**Comment by Easyfraggy** [comment]
![image](https://user-images.githubusercontent.com/36134067/46262724-94fe4400-c505-11e8-8eef-b9b6e0d67522.png)

**Comment by Evolvee** [comment]
eh, i will delay it a little bit more

nice report though, good effort 👍 

rev xdd
