### ISSUE TITLE
Logs

### ISSUE THREAD

**Issue by slamss** [Atlantiss/NetherwingBugtracker#8960]
[//]: # (Enclose links to things related to the bug using http://wowhead.com or any other TBC database.)
[//]: # (You can use screenshot ingame to visual the issue.)
[//]: # (Write your tickets according to the format:)
[//]: # ([Quest][Azuremyst Isle] Red Snapper - Very Tasty!)
[//]: # ([NPC] Magistrix Erona)
[//]: # ([Spell][Mage] Fireball)
[//]: # ([Npc][Drop] Ghostclaw Lynx)
[//]: # ([Web] Armory doesnt work)
[//]: # (To find server revision type `.server info` command in the game chat.)

**Description**: 
Need to fix logs for <Wasted Potential> for some dates:

**Current behaviour**:
Black temple 14.02.2024: should be heroic instead of normal
MH 15.02.2024: should be heroic instead of normal
MH 03.03.2024 Should be normal instead of heroic
Proof is in the loot table (quantity)

**Expected behaviour**: 

**Server Revision**:

**Comment by Godmatik** [comment]
you need to DM Query on the discord to have them fixed

**Comment by slamss** [comment]
"Your message could not be delivered. This is usually because you don't share a server with the recipient or the recipient is only accepting direct messages from friends."
Also doesn't respond when tagged. Guess I'll give up.
