### ISSUE TITLE
[Spell][Paladin] Judgement / Seal of the Crusader

### ISSUE THREAD

**Issue by ghost** [Atlantiss/NetherwingBugtracker#8964]
[//]: # (Enclose links to things related to the bug using http://wowhead.com or any other TBC database.)
[//]: # (You can use screenshot ingame to visual the issue.)
[//]: # (Write your tickets according to the format:)
[//]: # ([Quest][Azuremyst Isle] Red Snapper - Very Tasty!)
[//]: # ([NPC] Magistrix Erona)
[//]: # ([Spell][Mage] Fireball)
[//]: # ([Npc][Drop] Ghostclaw Lynx)
[//]: # ([Web] Armory doesnt work)
[//]: # (To find server revision type `.server info` command in the game chat.)

**Description**: 
Sometimes unable to use Judgement with Seal of the Crusader active, it is greyed out like there was no active seal. If I then use another seal and judge, I can judge crusader again. asked in world and got response they have the same issue.
**Current behaviour**:
use Seal of the Crusader, can't use Judgement
**Expected behaviour**: 
use Seal of the Crusader, use Judgement
**Server Revision**: 
3980

**Comment by Godmatik** [comment]
Can you provide a video please?

I am unable to reproduce, nor have I heard of anyone else having this issue.

**Comment by Godmatik** [comment]
Talked to a few Paladins, no one has experienced this.

If you provide video or a way to reproduce it - I will reopen
