### ISSUE TITLE
[2.4 PTR] - Exile

### ISSUE THREAD

**Issue by Godmatik** [Atlantiss/NetherwingBugtracker#8965]
Exile, when cast by Aldor or Scryer guards, will banish you temporarily but won't teleport you out afterward.

https://www.wowhead.com/tbc/spell=39533/exile

**Comment by Wolffenstein** [comment]
![image](https://github.com/Atlantiss/NetherwingBugtracker/assets/1576644/ef2200e5-5729-4ffa-87e2-edb68481c29d)
works fine for me

**Comment by Godmatik** [comment]
i'll record video and open up new issue some later
