### ISSUE TITLE
[2.4 PTR] Dawnblade Hawkrider

### ISSUE THREAD

**Issue by Godmatik** [Atlantiss/NetherwingBugtracker#8969]
These mobs have a chance to hit you and your pets with their firebolts when you are not engaged with him.

I AFKed on classic for a while near a bunch of them and they never once hit me, only hit the NPCs

https://www.wowhead.com/tbc/npc=25063/dawnblade-hawkrider#comments

**Comment by Wolffenstein** [comment]
fixed
