### ISSUE TITLE
[2.4 PTR][NPC] Erratic Sentry

### ISSUE THREAD

**Issue by Godmatik** [Atlantiss/NetherwingBugtracker#8970]
1. They use their suppression and electrical overload abilities when they are not in melee range of you - should only use those abilities if it can hit you.
2. They are using self-repair ability in combat-  they should only do so out of combat (along with capacitor overload) - basically it is an RP thing.
3. Should briefly stun itself when using electrical overload

https://www.wowhead.com/tbc/npc=24972/erratic-sentry#comments

https://streamable.com/qmy0fv

**Comment by Wolffenstein** [comment]
video gone btw

**Comment by Godmatik** [comment]
https://streamable.com/wvzhlv

**Comment by Godmatik** [comment]
Fixed now
