### ISSUE TITLE
[2.4 PTR][NPC] Felblood Initiate

### ISSUE THREAD

**Issue by Godmatik** [Atlantiss/NetherwingBugtracker#8971]
1. Their idle out-of-combat animation is slightly off - they should be draining power on the suspended terrorguard
2. They spam yell every few seconds their RP lines, I sat AFK in that area on classic and with all of them alive i saw a /yell once every couple of minutes or so.
3. After using fel siphon on one and the channel ends, it takes an extra ~5 seconds for it to transform - should happen immediately

https://www.wowhead.com/tbc/npc=24918/felblood-initiate

**Comment by Wolffenstein** [comment]
fixed
