### ISSUE TITLE
[2.4 PTR][NPC] Incandescent Fel Spark

### ISSUE THREAD

**Issue by Godmatik** [Atlantiss/NetherwingBugtracker#8972]
1. Incandescent Fel Spark model seems a bit wrong? Should have a red-ish hue to them. Think it was changed in patch 2.4. (below screenshot shows what it looks like on classic)
2. The Incandescent Fel Spark use Flames of Chaos skill but then instantly interrupt their own ability. They also use the ability even if you aren't in melee range of them.

https://www.wowhead.com/tbc/npc=24918/felblood-initiate#abilities

![Fel Spark](https://github.com/Atlantiss/NetherwingBugtracker/assets/37913400/381c3ee3-525b-42fa-b66e-785047212a51)

**Comment by Wolffenstein** [comment]
fixed
