### ISSUE TITLE
[2.4 PTR][NPC] Abyssal Flamewalker

### ISSUE THREAD

**Issue by Godmatik** [Atlantiss/NetherwingBugtracker#8973]
Missing ability "Immolation" - aura that periodically hits you for ~150 damage unresisted.

EDIT: Correction - he does have it, however you can dispel it off (cant do so on classic)

https://www.wowhead.com/tbc/npc=25001/abyssal-flamewalker#comments;mode:n25

**Comment by EtheriousNW** [comment]
fix is live
