### ISSUE TITLE
[2.4 PTR][NPC] Unleashed Hellion

### ISSUE THREAD

**Issue by Godmatik** [Atlantiss/NetherwingBugtracker#8974]
His rain of fire ability currently is a channeled ability.
Should instead be an instant ability and he can keep meleeing while it is going off

Yeah says channeled ability on wowhead I dunno ...

https://www.wowhead.com/tbc/spell=20754/rain-of-fire

https://streamable.com/tt6tzh

**Comment by Godmatik** [comment]
https://streamable.com/era2p0

Updated video link

**Comment by Wolffenstein** [comment]
![image](https://github.com/Atlantiss/NetherwingBugtracker/assets/1576644/8a718937-494d-44fc-94a1-fb2bcc06c8d8)
no he should not be meleeing

**Comment by Wolffenstein** [comment]
![image](https://github.com/Atlantiss/NetherwingBugtracker/assets/1576644/b472362b-5af6-4588-8898-3f6365324a7a)
no he should not be meleeing
