### ISSUE TITLE
[2.4 PTR] - Sunblade Mage Guard - Glaive Throw

### ISSUE THREAD

**Issue by Godmatik** [Atlantiss/NetherwingBugtracker#8975]
Glaive Throw should have a 2 second stun associated with its spell.

https://www.wowhead.com/tbc/spell=44478/glaive-throw#comments

There's a wowhead comment that it was nerfed in 2.4.3, but we aren't quite there yet even when Sunwell launches - I believe the stun portion should be restored (at least for heroic?)

**Comment by Wolffenstein** [comment]
Fixed in rev 3983.
