### ISSUE TITLE
[2.4 PTR] Sunblade Physician - Prayer of Mending

### ISSUE THREAD

**Issue by Godmatik** [Atlantiss/NetherwingBugtracker#8976]
When Prayer of Mending is cast and a charge is used up, if it is the only mob alive with it, the buff will stay on the target and 1 charge is expelled, meaning the same target will heal for 5 charges.

It should be same as priest Prayer of Mending - if 1 charge is used up but the PoM has no one to jump to, it should be removed.

https://www.wowhead.com/tbc/npc=24687/sunblade-physician#abilities;mode:normal

**Comment by Wolffenstein** [comment]
fixed on spell rework branch
