### ISSUE TITLE
[2.4 PTR] Sunblade Imp

### ISSUE THREAD

**Issue by Godmatik** [Atlantiss/NetherwingBugtracker#8977]
Sunblade Imp (Sunblade Warlock's minion) is doing melees only. He should be spamming firebolts like a warlock imp typically does.

https://www.wowhead.com/tbc/npc=24815/sunblade-imp
https://www.youtube.com/watch?v=g5oA9_0s8CY&t=135s

**Comment by Wolffenstein** [comment]
Fixed in rev 3983.
