### ISSUE TITLE
[2.4 PTR] Selin Fireheart

### ISSUE THREAD

**Issue by Godmatik** [Atlantiss/NetherwingBugtracker#8978]
Some bugs were already reported to you by Lajka - just the ones that weren't already reported:

1. He is missing Drain Mana ability (heroic only)
2. Fel Crystal should be 13.972 health in heroic
3. When he absorbs a crystal, the emote "Selin Fireheart begins to channel a crystal..." is showing up twice (sometimes three times), he also saying his voiceline about being a god duplicated.

https://www.wowhead.com/tbc/npc=24722/fel-crystal#abilities;mode:normal

![twice](https://github.com/Atlantiss/NetherwingBugtracker/assets/37913400/1889625a-af48-4dcf-bc9f-169ec5e10585)

![Drain Mana](https://github.com/Atlantiss/NetherwingBugtracker/assets/37913400/7e7fc6e1-5a6a-4e3a-81ae-8a1790b1c9cf)

**Comment by Wolffenstein** [comment]
3 should be fixed

**Comment by Wolffenstein** [comment]
Fixed
