### ISSUE TITLE
[2.4 PTR] - Etherum Smuggler

### ISSUE THREAD

**Issue by Godmatik** [Atlantiss/NetherwingBugtracker#8979]
When using his blink ability - Ethereum Smuggler uses arcane explosion one time then resumes melee.

Should spam his arcane explosion 3 times after blinking.

https://www.wowhead.com/tbc/npc=24698/ethereum-smuggler#comments;mode:normal

https://www.youtube.com/watch?v=C7nMa-cM4pI&t=925s

**Comment by Wolffenstein** [comment]
fixed
