### ISSUE TITLE
Message in a bottle

### ISSUE THREAD

**Issue by Thorgrimme** [Atlantiss/NetherwingBugtracker#898]
[//]: # (Enclose links to things related to the bug using http://wowhead.com or any other TBC database.)
[//]: # (You can use screenshot ingame to visual the issue.)
[//]: # (Write your tickets according to the format:)
[//]: # ([Quest][Message in a bottle)
[//]: # ([NPC] King Mukla)
[//]: # ([Spell][Mage] Fireball)
[//]: # ([Npc][Drop] Ghostclaw Lynx)
[//]: # ([Web] Armory doesnt work)

**Quest is lvl 42, while the quest mob is a lvl 51 elite, also quest is marked as a soloable quest**: 

**Current behaviour**:

**Expected behaviour**: 

**Server Revision**:

**Comment by aresbrutus** [comment]
#862

Duplicate.
