### ISSUE TITLE
[2.4 PTR] Priestess Delrissa fight

### ISSUE THREAD

**Issue by Godmatik** [Atlantiss/NetherwingBugtracker#8980]
1. Most of the adds tested do not use "Drink Healing Potion" at low health, but they should
2. **Ellrys Duskhallow** - health and mana too low. Should be 22356 health and 18930 mana (heroic)
3. **Apoko** - Windfury totem not working? At least when he placed it, I didn't see any extra hits from any of the mobs or buff either.
4. **Priestess Delrissa** - mana too low, should be 18930. Never once saw her attempt to use Power Word; Shield on herself or allies.
5. **Priestess Delrissa + Apoko** - they never attempted to heal allies, but they should. They will only heal themselves when damaged.
6. **Kagani Nightstrike** - is able to use backstab even if you are facing him. Never saw him attempt to use Kidney Shot.
7. **Zelfan** - health too high, should be 22,356 (heroic).
8. **Warlord Salaris** - health too high, should be 36,677 (heroic). 
9. **Yazzai** - Health and mana too low, should be 29,342 health + 18930 mana (heroic).
8. Her death speech "Not what I had... planned" should only be stated after the entire encounter is completed (her + her 4 allies dead), not when she personally dies. (yep she can say it beyond the grave lol)

Sources are all wowhead and a few classic videos I watched, can link if needed.

**Comment by Wolffenstein** [comment]
Fixed
