### ISSUE TITLE
[2.4 PTR] - Kael'thas Sunstrider (MGT)

### ISSUE THREAD

**Issue by Godmatik** [Atlantiss/NetherwingBugtracker#8981]
1. Throws fireballs every GCD unless interrupted. Per classic videos I watched (one linked below), he seems to only sometimes use fireball. Occasionally will chain 2-3 together, but typically will melee and then throw one in.
2. When putting up shield and casting pyroblast, he turns not toward the player he is using it on, but rather toward the entrance
3. Phoenix + Egg wrong health in heroic. Should be 34,930 and 6986 (respectively)
4. When Phoenix dies and egg is formed - you can still visually see and target the phoenix.
5. During air phase - the spheres are meleeing when they reach you. They should only do proximity arcane damage.

https://www.youtube.com/watch?v=Vw3JPrfWleU

**Comment by Wolffenstein** [comment]
Fixed
