### ISSUE TITLE
[2.4 PTR] - Kalecgos - Portal Delay

### ISSUE THREAD

**Issue by Godmatik** [Atlantiss/NetherwingBugtracker#8982]
Everytime someone enters a Kalecgos portal, there should be a 1 second or so delay until someone else can click on it. Right now there is no delay present. If a cooldown is not set it can potentially lead to cheesing the encounter.

This was reported previously last server:

https://github.com/Atlantiss/NetherwingBugtracker/issues/6767

**Comment by Wolffenstein** [comment]
fixed
