### ISSUE TITLE
[2.4 PTR] - Kalecgos - Sathrovarr the Corruptor hitbox

### ISSUE THREAD

**Issue by Godmatik** [Atlantiss/NetherwingBugtracker#8983]
Hitbox of the demon is incredibly small, causes issues for melee/tank, but also causes the NPC Kalecgos to position oddly inside the boss's model at times when the demon's position is shifted.

Classic shows the demon should have a normal sized hitbox:

https://www.youtube.com/watch?v=Asd_NyJnZEk&t=1m50s

**Comment by Wolffenstein** [comment]
fixed
