### ISSUE TITLE
Tracking stuff like mailbox or bankers gets reset after every relog

### ISSUE THREAD

**Issue by ghost** [Atlantiss/NetherwingBugtracker#8988]
[//]: # (Enclose links to things related to the bug using http://wowhead.com or any other TBC database.)
[//]: # (You can use screenshot ingame to visual the issue.)
[//]: # (Write your tickets according to the format:)
[//]: # ([Quest][Azuremyst Isle] Red Snapper - Very Tasty!)
[//]: # ([NPC] Magistrix Erona)
[//]: # ([Spell][Mage] Fireball)
[//]: # ([Npc][Drop] Ghostclaw Lynx)
[//]: # ([Web] Armory doesnt work)
[//]: # (To find server revision type `.server info` command in the game chat.)

**Description**: 
Because these things are not technically spells that can be found on wowhead I can't really link to them. This also makes any information about them near non existent.
**Current behaviour**:
Your tracking gets reset after logging out if it's not a class tracking spell like track humanoids.
**Expected behaviour**: 
When you select a form of tracking whether stuff like hunter tracking or stuff like mailbox, it should stay tracked upon a relog.
**Server Revision**: 
3980

**Comment by ghost** [comment]
Fuck this server and fuck you guys.

**Comment by Godmatik** [comment]
What a child.

BTW this is blizzlike for 2.4.3 (TBC), wasn't changed until Wrath to stay on permanently after relog

**Comment by ghost** [comment]
Fuck you too.
