### ISSUE TITLE
Steelsnap waypoint

### ISSUE THREAD

**Issue by Mewmewww** [Atlantiss/NetherwingBugtracker#899]
[//]: # (Enclose links to things related to the bug using http://wowhead.com or any other TBC database.)
[//]: # (You can use screenshot ingame to visual the issue.)
[//]: # (Write your tickets according to the format:)
[//]: # ([Quest][Azuremyst Isle] Red Snapper - Very Tasty!)
[//]: # ([NPC] Magistrix Erona)
[//]: # ([Spell][Mage] Fireball)
[//]: # ([Npc][Drop] Ghostclaw Lynx)
[//]: # ([Web] Armory doesnt work)

**Description**: Running through cliffs.

**Current behaviour**: Running through cliffs.

**Expected behaviour**: Waypoint shouldnt make him go through cliff haha: https://imgur.com/a/yI01oQa

**Server Revision**: 2083 NW

**Comment by aresbrutus** [comment]
Works just fine for me. Reply if you come across this again. 

https://gfycat.com/DisfiguredPeacefulAnemone
