### ISSUE TITLE
[2.4 PTR] Sunwell Trash reports

### ISSUE THREAD

**Issue by Godmatik** [Atlantiss/NetherwingBugtracker#8990]
1. Sunblade Protector mobs have no proximity threat when 'deactivated'
Even if they are 'deactivated' near the walls with no scout activating them - they still have proximity threat and should pull if you get too close to them. The aggro range is fairly small though.

https://www.youtube.com/watch?v=nIeMv4yQVPs&t=325s

2. Sunblade Scout when pulled should /yell "Enemies spotted! Attack while I try to activate a Protector!"

https://www.youtube.com/watch?v=nIeMv4yQVPs&t=115s

3. Sunblade Slayer - Scatter Shot and Slaying Shot abilities always targets the tank. 
Per warcraftlogs, the slayer should use it on a target that is not his primary threat.

![slaying and scatter](https://github.com/Atlantiss/NetherwingBugtracker/assets/37913400/7443f57a-c837-4fb2-946a-f4d613241e67)

4. Sunblade Dawn Priest - looks like they never cast Renew on themselves, only allies, seems they should be able to though.

![renew](https://github.com/Atlantiss/NetherwingBugtracker/assets/37913400/cd17bd1c-8535-4730-9908-ad8751be9d06)

5. Fire Fiend (summon from Sunblade Cabalist) health too low - should be 11,178 (or more if you wish - since rest of trash has its health buffed)

Can't test any of the other trash at the moment since stuck @ Brutallus

**Comment by Wolffenstein** [comment]
Regarding 3) Slaying Shot is random, can target the tank too

**Comment by Wolffenstein** [comment]
4) works 
![image](https://github.com/Atlantiss/NetherwingBugtracker/assets/1576644/e9ba9298-f13b-49a9-85ba-540cdfedaa3d)

**Comment by Godmatik** [comment]
Understood on 4.

Please check slaying shot again plaese, just tested again with 3 characters, let him do it ~20 times, he always hits the primary threat target.

**Comment by Wolffenstein** [comment]
fixed
