### ISSUE TITLE
[2.4 PTR] Brutallus RP scene stuck

### ISSUE THREAD

**Issue by Godmatik** [Atlantiss/NetherwingBugtracker#8992]
The intro RP for Brutallus, after he says "I will crush you!" - nothing happens, can't proceed any further

![WoWScrnShot_032324_122303](https://github.com/Atlantiss/NetherwingBugtracker/assets/37913400/96a88249-3ed4-441b-88f4-c21deb8b9c79)

**Comment by Wolffenstein** [comment]
fixed
