### ISSUE TITLE
[Hunter] Feign Death triggers  Autoshot CD

### ISSUE THREAD

**Issue by disis24** [Atlantiss/NetherwingBugtracker#8993]
Feign Death triggers  Auto shot CD

**Comment by Godmatik** [comment]
Yeah confirmed, I figured it was intentional though, so I always FDed right after an auto

EDIT - per classic reddit, seems intended?:

![FD](https://github.com/Atlantiss/NetherwingBugtracker/assets/37913400/1e17074d-69ea-40e1-aa49-a2b4a5c2e124)

**Comment by disis24** [comment]
In vanilla (lvl60) yes, but not in TBC

**Comment by disis24** [comment]
Can see here : https://youtu.be/e8nFBwWxey0?si=X_55nIrNt4yyLwPQ&t=29
around 30sec, his auto shot cd is not reseted
