### ISSUE TITLE
[2.4 PTR] Heroic Kalecgos - Sparks in Melee

### ISSUE THREAD

**Issue by Godmatik** [Atlantiss/NetherwingBugtracker#8995]
Sparks are still targeting and spawning on melee - even at very start of encounter when everyone is in the up realm and there are more than enough bodies in ranged.

**Comment by Wolffenstein** [comment]
huh

**Comment by Wolffenstein** [comment]
oh i know why, im fucking dumb

**Comment by Wolffenstein** [comment]
should be fixed
