### ISSUE TITLE
[2.4 PTR] Kalecgos - Blink

### ISSUE THREAD

**Issue by Godmatik** [Atlantiss/NetherwingBugtracker#8996]
Mage blink is still having issues on the Kalecgos platform - you don't always blink in the proper direction you are facing.

Sometimes it will blink you sideways or backwards. The blink always teleports you, but the direction is random.

From what I was told - charger/intercept works proper now.

**Comment by Wolffenstein** [comment]
How do I reproduce?

**Comment by Godmatik** [comment]
I'll ask our mage to try and get a video or something

**Comment by Wolffenstein** [comment]
should be fixed
