### ISSUE TITLE
[2.4 PTR] Kalecgos + Sathrovarr sometimes move randomly.

### ISSUE THREAD

**Issue by Godmatik** [Atlantiss/NetherwingBugtracker#8997]
Not sure how to describe it really or reproduce -  but occasionally - the Dragon or Demon will move in a random direction for a couple of seconds before going back on the main tank.

See below clips.

https://clips.twitch.tv/IcyCreativeElephantDancingBaby-mLi0VXw0K0jyBrU-

**Comment by Godmatik** [comment]
https://www.twitch.tv/cillo/v/2101573481?sr=a&t=9647s

**Comment by Wolffenstein** [comment]
should be fixed hopefully
