### ISSUE TITLE
[Hunter] Can't Shoot my shot

### ISSUE THREAD

**Issue by John-Johnston** [Atlantiss/NetherwingBugtracker#9]
https://www.youtube.com/watch?v=BQt-JMRU5TI  
Unable to Shoot, right-click autoattack seems to have fixed it

**Comment by Easyfraggy** [comment]
Theres a client bug with 2.4.3 where sometimes you get locked from using abilities, usually clicking the ALT button on your keyboard solves the issue.

**Comment by Easyfraggy** [comment]
If you can add some new info on this reopen the bug. Seems to be the ALT bug specified above.
