### ISSUE TITLE
[priest] scream

### ISSUE THREAD

**Issue by despairr1** [Atlantiss/NetherwingBugtracker#900]
[//]: # (Enclose links to things related to the bug using http://wowhead.com or any other TBC database.)
[//]: # (You can use screenshot ingame to visual the issue.)
[//]: # (Write your tickets according to the format:)
[//]: # ([Quest][Azuremyst Isle] Red Snapper - Very Tasty!)
[//]: # ([NPC] Magistrix Erona)
[//]: # ([Spell][Mage] Fireball)
[//]: # ([Npc][Drop] Ghostclaw Lynx)
[//]: # ([Web] Armory doesnt work)

**Description**: 
https://media.discordapp.net/attachments/495622706671386634/495622830763802625/WoWScrnShot_092918_174046.jpg?width=978&height=612
https://cdn.discordapp.com/attachments/495622706671386634/495623564758745108/WoWScrnShot_092918_175101.jpg
https://cdn.discordapp.com/attachments/495622706671386634/495629930496000000/WoWScrnShot_092918_181142.jpg
https://cdn.discordapp.com/attachments/495622706671386634/495630117083676674/WoWScrnShot_092918_181423.jpg
Guildy said - the combat log shows 4 enemies been under fear, yet some of them are still hitting me. after have talked with Ids he got the same issue with rank 1 of psychic scream. I think the combat log as the icon above the head of enemies show enemies that are actually not fear, that's why they still can hit me
Scream is fearing more enemies than it should. Reporting for a guildy.
**Current behaviour**:
Fears too may
**Expected behaviour**: 
Only supposed to fear 2 i think
**Server Revision**: 
2083

**Comment by Jezofine** [comment]
Rank 1 affects 3 targets visually but only 2 of them flee. 
Rank 2 affects 4 targets visually but only 3 of them flee.
Look like it alpplis to +1 target but don't make it flee.

**Comment by SahrFR** [comment]
Actually as you can see on the 3rd and 4th pics above, rank 1 could affects 4 targets visually and in the combat log, but only 2 of them flee.

**Comment by Jezofine** [comment]
I clearly get 3 affected targets for rank 1, rechecked on lowlevel mobs so fear would not be resisted.

**Comment by Wolffenstein** [comment]
Fixed in rev 2399.
