### ISSUE TITLE
[2.4 PTR] Leotheras - Mind controls broken + Leo stuck

### ISSUE THREAD

**Issue by Godmatik** [Atlantiss/NetherwingBugtracker#9007]
Two bugs I noticed

1. When someone gets mind controlled from not killing their demon, they just sat there and didn't attack at all, not even when I attacked them.
2. Leo is getting stuck and not moving toward me after whirlwinds

https://streamable.com/3fxrqp

**Comment by Godmatik** [comment]
Mind control issue is global on all bosses that have it.

**Comment by Wolffenstein** [comment]
Can't reproduce whirlwind bug

**Comment by Godmatik** [comment]
Maybe it only happens when people are mind controlled, and Leo ends whirlwind after targeting one of them. I don't think he should target MC people in the first place with it.

I'll do more tests to try and reproduce

**Comment by Wolffenstein** [comment]
MC Fixed
