### ISSUE TITLE
Distract bug. [Rogue] [Spells] [NPC]

### ISSUE THREAD

**Issue by Neophrone** [Atlantiss/NetherwingBugtracker#901]
[//]: # (Enclose links to things related to the bug using http://wowhead.com or any other TBC database.)
[//]: # (You can use screenshot ingame to visual the issue.)
[//]: # (Write your tickets according to the format:)
[//]: # ([Quest][Azuremyst Isle] Red Snapper - Very Tasty!)
[//]: # ([NPC] Magistrix Erona)
[//]: # ([Spell][Mage] Fireball)
[//]: # ([Npc][Drop] Ghostclaw Lynx)
[//]: # ([Web] Armory doesnt work)

**Description**: When you use rogue ability [Distract] on mob that not in combat, and after that you starting to fight this mob, mob will not moving and will stand in place where he was when you used [Distract] on him even if you'll run away from him. Lasts for 10secs (duration of [Distract]).

**Current behaviour**: Mobs aren't moving if they were affected by [Distract] before you start fighting with them.

**Expected behaviour**: Mobs should follow you in combat even if they were affected by [Distract].

**Server Revision**: 2083.
![distract](https://user-images.githubusercontent.com/43533040/46247788-3065bb00-c419-11e8-8d4f-3edc0b017b60.gif)

**Comment by Wolffenstein** [comment]
Fixed in rev 2092.
