### ISSUE TITLE
[2.4 PTR] RoS

### ISSUE THREAD

**Issue by Godmatik** [Atlantiss/NetherwingBugtracker#9012]
1. Some odd issues occurring with 'Fixate' debuff in phase 1 of RoS fight, sometimes im being attacked when I dont have it, sometimes I am not being attacked when I do have it (see below video)

2. Spite ability in final phase does no damage

https://www.wowhead.com/wotlk/spell=41376/spite

https://streamable.com/8riz6m

**Comment by Wolffenstein** [comment]
Fixed
