### ISSUE TITLE
[2.4 PTR] ZA Bugs

### ISSUE THREAD

**Issue by Godmatik** [Atlantiss/NetherwingBugtracker#9013]
1. Akil'zon Static Disruption - when used, two stacks of the nature damage debuff get applied to you instead of just one
2. Nalorakk - He never used Mangle on main tank during human form.
3. Jan'alai - When starting his bombs, he doesn't teleport you like he should. Also - his flame breath is only attacking the main tank, he never selects a different target.

**Comment by Wolffenstein** [comment]
From 2.4.0 onwards he only teleports players that aren't close to him

**Comment by Wolffenstein** [comment]
Fixed
