### ISSUE TITLE
[2.4 PTR] Blind - Parried?

### ISSUE THREAD

**Issue by Godmatik** [Atlantiss/NetherwingBugtracker#9014]
![Blindparried](https://github.com/Atlantiss/NetherwingBugtracker/assets/37913400/ef8dd311-8e58-4c24-8149-cb2badac4381)

**Comment by Wolffenstein** [comment]
His Blind is a melee ability, it can be parried

**Comment by Xykyta1** [comment]
> His Blind is a melee ability, it can be parried

Melee attack with range 10 yards?)
https://www.wowhead.com/tbc/spell=34694/blind
https://wowclassicdb.com/tbc/spell/34694
https://db.moonwell.su/?spell=34694

I doubt it
