### ISSUE TITLE
[NPC] [Spell] Witherbark Witch Doctor - Wrong Totem

### ISSUE THREAD

**Issue by Firroth** [Atlantiss/NetherwingBugtracker#902]
[NPC] Witherbark Witch Doctor https://www.wowhead.com/npc=2555/witherbark-witch-doctor
[Spell] Magma Totem https://classicdb.ch/?spell=8190

**Current behaviour**:
For some reason now he uses "Searing Totem", when in previous rev. he used correct totem.
#808 
![screenshot_1](https://user-images.githubusercontent.com/43505196/46247908-79664100-c412-11e8-84cb-25d29182533b.png)

**Expected behaviour**: 
He should use Magma Totem https://classicdb.ch/?spell=8190

![screenshot_2](https://user-images.githubusercontent.com/43505196/46247904-78351400-c412-11e8-9f50-43f5f08fdb39.png)

**Server Revision**: 
2083

**Comment by xmesaj2** [comment]
Wowhead lists https://www.wowhead.com/npc=2555/witherbark-witch-doctor#abilities Searing Totem, and this one has horde model, classicdb shows magma which has dreanei model. So, which one is actually correct?

**Comment by Firroth** [comment]
By looking at comment on wowhead, other vanilla DB's etc. they list magma totem. Perhaps it's just a mistake made on wowhead with searing one.

**Comment by xmesaj2** [comment]
beastiary also shows magma totem, will change it back with next update

**Comment by totaemoeggerli** [comment]
The NPC is still using Searing Totem and it doesn't attack the player
Additionally it uses the wrong race totem (reported here: https://github.com/Atlantiss/NetherwingBugtracker/issues/808)
and it replaces the searing totem with Healing Ward vice verca
I don't see any reason why this would be the case, alot of other mobs use two totems without replacing one with the other

**Comment by xmesaj2** [comment]
2128
