### ISSUE TITLE
Rage decay

### ISSUE THREAD

**Issue by Xykyta1** [Atlantiss/NetherwingBugtracker#9021]
[//]: # https://www.wowhead.com/tbc/resource/rage-1

**Description**: rage decay out of combat faster than it should be

**Current behaviour**: rage decay ticks every 2 secs, every tick 3 rages constantly. with talent https://www.wowhead.com/tbc/spell=12296/anger-management every tick 2 rages constantly.

**Expected behaviour**: rage decay ticks every 2 secs. rage decay cycle of ticks "2, 3" (2 rage, 3 rage, 2, 3, 2, 3...). With talent https://www.wowhead.com/tbc/spell=12296/anger-management cycle of ticks "2, 2, 2, 2, 2, 1, 2, 2, 2, 2, 2, 2, 1".

Videos for example.
TBC Classic cycle "2, 3" (without talent):
https://youtu.be/Y4yJ4vrNyos?t=1060

TBC Classic cycle "2, 2, 2, 2, 2, 1, 2, 2, 2, 2, 2, 2, 1" (with talent):
https://youtu.be/iGi9FxLG8Gs?t=175

TBC from 2007y. I found one video with almost good resolution, set 480p quality. U can see tick for 1 rage only, that means this warrior had talent anger managment.
Here rage dawn from 60 to 59:
https://youtu.be/hPh9JFpP0n8?list=PLLS_8oKfvVCHQWUwHrK3ySJMBo-eN4ldP&t=67

Here ticks "2, 2, 2, 1", rage left: 17, 15, 13, 12:
https://youtu.be/hPh9JFpP0n8?list=PLLS_8oKfvVCHQWUwHrK3ySJMBo-eN4ldP&t=193

**Server Revision**: 3980

**Comment by Godmatik** [comment]
Fixed in new aura branch update, being pushed to live servers soon
