### ISSUE TITLE
Maim shares DR with hybernate

### ISSUE THREAD

**Issue by budgebudge** [Atlantiss/NetherwingBugtracker#9022]
maim = controlled stun effect
hybernate = disorient effect

these two are not supposed to DR each other....

**Comment by Wolffenstein** [comment]
![image](https://github.com/Atlantiss/NetherwingBugtracker/assets/1576644/7616e741-f9b8-430c-83c4-ec750e506c26)
![image](https://github.com/Atlantiss/NetherwingBugtracker/assets/1576644/9bf42947-8d80-48c4-a0f2-57dc18a0c963)

**Comment by budgebudge** [comment]
relying on tbc classic should not be the norm. too much fucked up stuff there that was just fixed along the way (if even fixed at all). see sticky novas as a base spell that they fucked up and corrected (at least) 2 times themselves. they had no idea what was in original tbc and how spells/formulas worked. you should rely on original TBC, not on that classic dogversion of the game. hence, these both images proove nothing except relying on tbc classic as valid source is a big mistake.
