### ISSUE TITLE
Shaman. Talent Resorative totem. Heal

### ISSUE THREAD

**Issue by Xykyta1** [Atlantiss/NetherwingBugtracker#9023]
talent Restorative Totems: Increases the effect of your Mana Spring and Healing Stream Totems by 25%.
https://www.wowhead.com/tbc/spell=16208/restorative-totems

Problem: Talent increases healing more than it should be
---
Zero bonus healing
![char stats](https://github.com/Atlantiss/NetherwingBugtracker/assets/159961699/b8d4a53e-4349-4e05-b9a7-378ce4d97e78)

Base heal by totem 18 per 2 secs - correct.
![healtotembase wo tal](https://github.com/Atlantiss/NetherwingBugtracker/assets/159961699/8e4440d1-e356-480d-88b3-92df96ac40ff)

With talent https://www.wowhead.com/tbc/spell=16208/restorative-totems should be 18 * 1.25 = 22.5 or 22/23 per tick
Look at tooltip - correct
![тотем хил тултип](https://github.com/Atlantiss/NetherwingBugtracker/assets/159961699/c0b8d064-5239-43be-b5bf-2489660650ad)

Look at real numbers - 27 per tick
![реал цифры тотема](https://github.com/Atlantiss/NetherwingBugtracker/assets/159961699/97dcc69a-13ab-4a3b-b8d0-0084409f093e)

---

Added 212 bonus heal
![212 бх](https://github.com/Atlantiss/NetherwingBugtracker/assets/159961699/7343615e-d44d-42b5-8b16-7f31e2fd5c8c)

Without talent healing by totem per tick should be: 18 + 212 * 0.045 = 27.54
![бх тотем](https://github.com/Atlantiss/NetherwingBugtracker/assets/159961699/a91e61da-b498-4e1c-9f68-98772ca009e5)
Ok

With talent 27.54 * 1.25 = 34.45
![бх 212 + талант](https://github.com/Atlantiss/NetherwingBugtracker/assets/159961699/3dd6e1ce-aae8-40f4-9bbe-d6144aaf4c1f)

**Server Revision**: 3980

**Comment by Godmatik** [comment]
Rev 4020 - still an issue

Looks like the effect of the talent is being produced twice for the healing stream totem.

The bonus for mana spring totem is correct.

**Comment by Godmatik** [comment]
Fixed with recent spell clean-up
