### ISSUE TITLE
Arathi NPC Patrol

### ISSUE THREAD

**Issue by despairr1** [Atlantiss/NetherwingBugtracker#903]
[//]: # (Enclose links to things related to the bug using http://wowhead.com or any other TBC database.)
[//]: # (You can use screenshot ingame to visual the issue.)
[//]: # (Write your tickets according to the format:)
[//]: # ([Quest][Azuremyst Isle] Red Snapper - Very Tasty!)
[//]: # ([NPC] Magistrix Erona)
[//]: # ([Spell][Mage] Fireball)
[//]: # ([Npc][Drop] Ghostclaw Lynx)
[//]: # ([Web] Armory doesnt work)

**Description**: 
Forsaken Body Gaurds that pat through arathi were hovering 
![hovering mobs](https://user-images.githubusercontent.com/43509262/46248143-13aa9280-c3db-11e8-8edf-e09a4b65c7e3.png)

**Current behaviour**:
Hovering
**Expected behaviour**: 
Walk normal
**Server Revision**: 
2083

**Comment by aresbrutus** [comment]
This is due to the formation leader seeking.

**Comment by Easyfraggy** [comment]
hardlinked mobs (formations) shouldnt reset if 1 of them is still in combat

**Comment by despairr1** [comment]
They didn't reset when I vanished.

**Comment by Tereneckla** [comment]
Fixed
