### ISSUE TITLE
[2.4 PTR] Battle Shout range

### ISSUE THREAD

**Issue by Godmatik** [Atlantiss/NetherwingBugtracker#9030]
Battle shout (untalented) right now appears to be less than 20 yard range for allies.

**Comment by Wolffenstein** [comment]
PTR or live?

**Comment by Godmatik** [comment]
PTR

**Comment by Godmatik** [comment]
![mec](https://github.com/Atlantiss/NetherwingBugtracker/assets/37913400/e5db0cb8-103e-4754-a273-a975e1e3e2a2)

**Comment by Wolffenstein** [comment]
Any specific class/race/racial swap/location? It works fine for me

**Comment by Godmatik** [comment]
Disregard
