### ISSUE TITLE
[2.4 PTR] Quest - Taking the Harbor

### ISSUE THREAD

**Issue by Godmatik** [Atlantiss/NetherwingBugtracker#9031]
Dawnblade Summoner - Some of them have their imps summoned when engaged - some of them do not. They also should be spamming spells basically every GCD (based on classic)

Dawnblade Blood Knight - When using their Judgement of Wrath, it does not consume their seal as it should.

**Comment by Wolffenstein** [comment]
Fixed in rev 3983.
