### ISSUE TITLE
[2.4 PTR] Felmyst

### ISSUE THREAD

**Issue by Godmatik** [Atlantiss/NetherwingBugtracker#9033]
1. The custom tooltips don't show when Felmyst is in normal mode.

2. Missing voice line when she goes into the air:
"I am stronger than ever before!"

3. During air phase - Felmyst faces the target she has aggro on right before and while the breath happens. This causes her to look a bit odd when she is doing breath on other side of the room, for example (see below clip). Looking at classic videos, she will target the main tank in air only very briefly in-between breaths, but will drop target while doing her movement into breath animation - so she will always look straight ahead. (classic video below)

https://streamable.com/ryoncn

![Felmyst2](https://github.com/Atlantiss/NetherwingBugtracker/assets/37913400/722d18dc-2229-4fb4-bd4e-44d59cde2e1f)

![airphase](https://github.com/Atlantiss/NetherwingBugtracker/assets/37913400/fde4bdb1-3424-427c-8a72-7ea1cd26724c)

https://www.youtube.com/watch?v=14KsCJtRCfM&t=105s

**Comment by Godmatik** [comment]
Felmyst is going back to facing the tank a second or two after encapsulate is cast, she should face the encapsulate target the entire time I believe

**Comment by Godmatik** [comment]
During air phase - her first breath on the south side does not work

**Comment by Wolffenstein** [comment]
Updated tooltips are only sent after Kalecgos is defeated as not to override his Arcane Buffet (technical limitation) so you probably switched to normal without killing him

**Comment by Wolffenstein** [comment]
Fixed in rev 3984.
