### ISSUE TITLE
[2.4 PTR] Item - Timbal's Focusing Crystal & Shadow Affinity

### ISSUE THREAD

**Issue by adambcurrier** [Atlantiss/NetherwingBugtracker#9036]
I don't think that the Shadow Bolt proc from Timbal's Focusing Crystal (https://www.wowhead.com/tbc/item=34470/timbals-focusing-crystal) is benefiting from the priest talent Shadow Focus, which reduces a target's chance to resist our shadow spells by 2% per talent point.

![image](https://github.com/Atlantiss/NetherwingBugtracker/assets/108972597/a579bc52-d247-4c82-8d55-dcd2c5a1c684)

This was done on a level 73 Test Dummy by a shadow priest with 8% spell hit rating from gear, and 8% shadow spell hit rating from talents. The character is at the 16% hit cap with an unavoidable 1% chance to miss left over. At 11% the resist rate is out of line with all my other spell resists. I only got two Mind Flay resists out of 240+ casts in the above spell breakdown. I just want to note that I was using .cd macroed into every Mind Flay cast so I could get more procs of the trinket for that test.

I think the trinket should benefit from hit talents.

**Comment by Wolffenstein** [comment]
Despite the description, Shadow focus only applies to Priest spells/talents. See:
![image](https://github.com/Atlantiss/NetherwingBugtracker/assets/1576644/f4b73803-2698-48ce-a5db-c73eb1b8f341)
