### ISSUE TITLE
[PTR] Release Spirit --> Pull Boss

### ISSUE THREAD

**Issue by Godmatik** [Atlantiss/NetherwingBugtracker#9039]
There's an old bug present still even on PTR that will make the idea of releasing spirit and being in front of the boss sadly not very viable in Sunwell.

When you release spirit, you are for less than a split second, 'alive' at the spot you died in, and will aggro the boss if you are in range of him, before it moves you to the revive spot.

**Comment by Wolffenstein** [comment]
Fixed in rev 3984.
