### ISSUE TITLE
Blade Flurry. [Rogue] [Spell]

### ISSUE THREAD

**Issue by Neophrone** [Atlantiss/NetherwingBugtracker#904]
[//]: # (Enclose links to things related to the bug using http://wowhead.com or any other TBC database.)
[//]: # (You can use screenshot ingame to visual the issue.)
[//]: # (Write your tickets according to the format:)
[//]: # ([Quest][Azuremyst Isle] Red Snapper - Very Tasty!)
[//]: # ([NPC] Magistrix Erona)
[//]: # ([Spell][Mage] Fireball)
[//]: # ([Npc][Drop] Ghostclaw Lynx)
[//]: # ([Web] Armory doesnt work)

**Description**:[Blade Flurry] hits do less damage than main attack. Looks like [Blade Flurry] hits scaling with target's armor twice. I mean main attack scales with armor of first target and then [Blade Flurry] hit take in account actual damage of main attack and scale it with armor of the second target. (Look combat log on the screenshot).

**Current behaviour**: [Blade Flurry] do less damage than main attack (scales with target's armor twice).

**Expected behaviour**: [Blade Flurry] hits should scale only with armor of second target.
 For example: I'm fighting 2 mobs. This mobs are the same (2x [Forest Moss Creeper], both lvl 21). I'm hitting first mob with [Sinister Strike] (it should deal 120 damage to the target with 0 armor) but it's scale with first mob armor and dealing 80 damage. [Blade Flurry] hit should deal the same damage(120) to target with 0 armor, but it's scale with second mob armor and dealing 80 damage too( because second mob is same for first and they have same ammount of armor). 

**Server Revision**: 2083.
![wowscrnshot_092918_190506](https://user-images.githubusercontent.com/43533040/46248162-81c47900-c41e-11e8-9309-24e8ee80d902.jpg)

**Comment by Easyfraggy** [comment]
Strange this works fine for Sweeping Strikes.

![image](https://user-images.githubusercontent.com/36134067/46249569-b7239380-c42b-11e8-97db-048ae5791d4a.png)

**Comment by Neophrone** [comment]
Still works wrong. I posted it month ago, bug confirmed, high-prio-issue, but still no fixes.

**Comment by Nicemann1089** [comment]
push

**Comment by AndrewNB41191** [comment]
i think ive observed additional bugs with blade flurry besides the one mentioned. should i wait for this to be fixed or do some testing and post here/separate issue

**Comment by Wolffenstein** [comment]
Fixed in rev 2366.

**Comment by Neophrone** [comment]
Still buged. 
Rev.: 2382.

**Comment by Easyfraggy** [comment]
Seems to be doubledipping armor - 
If you hit Mob A and Mob B damage on Mob A should be calculated from Mob A armor and damage on Mob B should be calculated from Mob B armor only.

Same armor dmg A=B
A higher armor dmg A<B
B higher armor dmg A>B

**Comment by Wolffenstein** [comment]
Fixed in rev 2400.
