### ISSUE TITLE
Daily Quest not working - Sunfury Attack Plans

### ISSUE THREAD

**Issue by foxkrm** [Atlantiss/NetherwingBugtracker#9042]
[//]: # (Enclose links to things related to the bug using http://wowhead.com or any other TBC database.)
[//]: # (You can use screenshot ingame to visual the issue.)
[//]: # (Write your tickets according to the format:)
[//]: # ([Quest][Azuremyst Isle] Red Snapper - Very Tasty!)
[//]: # ([NPC] Magistrix Erona)
[//]: # ([Spell][Mage] Fireball)
[//]: # ([Npc][Drop] Ghostclaw Lynx)
[//]: # ([Web] Armory doesnt work)
[//]: # (To find server revision type `.server info` command in the game chat.)

**Description**: 
Quest item for the  samenamed quest [Sunfury attack plans](https://www.wowhead.com/tbc/quest=11877/sunfury-attack-plans) not drop. Something goes wrong there.

**Comment by Godmatik** [comment]
Works just fine for me

**Comment by adambcurrier** [comment]
Sometimes it just takes 44 mob kills to get it to drop. Feels bad for a 10% listed drop chance but it will drop eventually.

**Comment by Godmatik** [comment]
Maybe it's just a problem of droprate then

**Comment by foxkrm** [comment]
Its working fine. Closed
