### ISSUE TITLE
Netherspite beams do not attach and detach properly

### ISSUE THREAD

**Issue by sk6868** [Atlantiss/NetherwingBugtracker#9044]
**Description**: 
Netherspite beams do not attach and detach properly

**Current behaviour**:
You have to move too far for the beam to detach from you.  Sometimes you are exactly crossing the beam with noone behind you yet the beam is not intercepted.

**Expected behaviour**: 
You move 10 meters and the beam detaches from you.

**Server Revision**:

**Comment by Godmatik** [comment]
Sounds like some beam like projectiles are wider than intended after patch.

On discord they were saying Lurker's spout ability is much wider than it should be

**Comment by sk6868** [comment]
In correction to the original post, the expected behavior should be that the beam should detach when you are 2-3 meter away (sideways) from the line from the beam portal to the boss

**Comment by sk6868** [comment]
> Sounds like some beam like projectiles are wider than intended after patch.
> 
> On discord they were saying Lurker's spout ability is much wider than it should be

can you link the issue?

**Comment by Godmatik** [comment]
> > Sounds like some beam like projectiles are wider than intended after patch.
> > On discord they were saying Lurker's spout ability is much wider than it should be
> 
> can you link the issue?

I am saying you are correct, it is bugged. The Spout thing was mentioned on discord.

**Comment by Godmatik** [comment]
Was fixed a while ago
