### ISSUE TITLE
[PTR][SWP][NPC] Felmyst immune to attacks

### ISSUE THREAD

**Issue by buza-me** [Atlantiss/NetherwingBugtracker#9045]
[//]: # (Enclose links to things related to the bug using http://wowhead.com or any other TBC database.)
[//]: # (You can use screenshot ingame to visual the issue.)
[//]: # (Write your tickets according to the format:)
[//]: # ([Quest][Azuremyst Isle] Red Snapper - Very Tasty!)
[//]: # ([NPC] Magistrix Erona)
[//]: # ([Spell][Mage] Fireball)
[//]: # ([Npc][Drop] Ghostclaw Lynx)
[//]: # ([Web] Armory doesnt work)
[//]: # (To find server revision type `.server info` command in the game chat.)

[NPC] Felmyst

**Description**: 
1. Raid is at the Dead Scar, Sunwell Plateau heroic.
2. Brutallus is Dead.
3. Felmyst is spawned.
4. Everyone in a raid logs out.
5. Anyone from the raid logs back into the game.
5. Boss is not reachable by spell casts and presumably by ranged weapon attacks, I don't have a hunter to test. The game responds with "the target is too far away" error.
**Current behaviour**:
Players that log in after every raid member logs out are not able to attack or cast spells at Felmyst.
**Expected behaviour**: 
Players that log in after every raid member logs out should be able to attack or cast spells at Felmyst.
**Server Revision**: 
3984

**Comment by Godmatik** [comment]
Just tested using your same exact steps, was able to pull Felmyst no problem after logging back in.

I am using a Hunter.

Unless I am missing something here...

**Comment by buza-me** [comment]
I'm using a priest. Let me double check, I had a "wipe" before logging out, but it was consistent. Maybe it is only for spells though.

**Comment by buza-me** [comment]
I mean double check if wipe is required to bug that thing

**Comment by buza-me** [comment]
Nope wipe is not required. Can't cast spells at Felmyst after steps listed in the description. Fresh ID tested. @Godmatik

**Comment by Godmatik** [comment]
Maybe you can record it or something.

I once again followed your steps, and this time I used a priest instead of a hunter, and was able to pull her no problems.

https://streamable.com/gqfrfj

**Comment by buza-me** [comment]
https://drive.google.com/file/d/1NFtYphhfP9v516Mxfl69mljnqXZsMNG_/view?usp=sharing
Idk maybe it is because I have less people than you in the raid or something.

**Comment by Godmatik** [comment]
I see you were able to get a cast off though, so it is working? Looks like she just outranged it?

**Comment by buza-me** [comment]
No, before log out I was showing that I can cast from that spot. After log in I could not cast from that same spot, and if you look at smite button it is not red.
