### ISSUE TITLE
Feign Death bugged in new zone/instances all over again

### ISSUE THREAD

**Issue by spacct** [Atlantiss/NetherwingBugtracker#9047]
[//]: # (Enclose links to things related to the bug using http://wowhead.com or any other TBC database.)
[//]: # (You can use screenshot ingame to visual the issue.)
[//]: # (Write your tickets according to the format:)
[//]: # ([Quest][Azuremyst Isle] Red Snapper - Very Tasty!)
[//]: # ([NPC] Magistrix Erona)
[//]: # ([Spell][Mage] Fireball)
[//]: # ([Npc][Drop] Ghostclaw Lynx)
[//]: # ([Web] Armory doesnt work)
[//]: # (To find server revision type `.server info` command in the game chat.)

**Description**: Feign Death bugged in new zone/instances. Tested in MGT N/HC and SWP (PTR).

**Current behaviour**: In the new zone/instances, Feign Death buff is retained even when following it with an action (attack/drink etc.) so long as that action isn't movement. To remove the buff (and initiate the cd), you have to either right-click to remove the buff or move your character. 

**Expected behaviour**: Feign Death buff should be removed on any subsequent action (attack/drink/movement etc.) in the new zone/instances, and the cd should be initiated at the same time the buff is removed.

**Server Revision**:

**Comment by Wolffenstein** [comment]
Can you record it?

**Comment by spacct** [comment]
Also happening in ZA. So appears to not be isolated to new zone/instances

**Comment by spacct** [comment]
![image](https://github.com/Atlantiss/NetherwingBugtracker/assets/104590778/bad1162e-0f4c-40e3-ad30-8942a24d3d2a)

Drinking while Feign Death buff active in shadow lab

**Comment by spacct** [comment]
Appears this issue stopped occuring. Not clear why. Closing this
