### ISSUE TITLE
[Isle of Quel'Danas] Blizzard_CombatLog LUA Errors

### ISSUE THREAD

**Issue by adambcurrier** [Atlantiss/NetherwingBugtracker#9048]
Ever since the Shattered Sun Staging Area was made a sanctuary I'm being bombarded with LUA errors literally from the second I land. Probably every 3 or 4 seconds a new count pops up. As far as I'm aware Blizzard_CombatLog is a client default "addon" that I can't disable and probably should not delete.  I did log out and delete my cache before logging back in just to make sure that wasn't the issue. The errors persisted.

```
Message: ...ace\AddOns\Blizzard_CombatLog\Blizzard_CombatLog.lua:2704: bad argument #3 to 'strreplace' (string expected, got nil)
Time: 04/22/24 12:56:10
Count: 47
Stack: [C]: ?
...ace\AddOns\Blizzard_CombatLog\Blizzard_CombatLog.lua:2704: in function <...ace\AddOns\Blizzard_CombatLog\Blizzard_CombatLog.lua:2112>
...ace\AddOns\Blizzard_CombatLog\Blizzard_CombatLog.lua:3368: in function 'CombatLog_AddEvent'
...ace\AddOns\Blizzard_CombatLog\Blizzard_CombatLog.lua:3380: in function <...ace\AddOns\Blizzard_CombatLog\Blizzard_CombatLog.lua:3378>
```

I know from experience that eventually my client will tell me that my addons are experiencing a large number of errors and could eventually reload on its own. I do plan to spend a fair amount of time here and would prefer not to hide LUA errors or have that happen. Not sure what's going on or if it's fixable but I figured I'd toss it out there.

**Comment by adambcurrier** [comment]
Deleting the Blizzard_CombatLog addon folder throws an application error as soon as I submit my login information to log in.

**Comment by adambcurrier** [comment]
Yesterday in attempts to fix this I deleted my cache (didn't work) and then deleted the Blizzard_CombatLog addon folder. After I deleted that addon I got non-stop application errors in a row when trying to log in.

I just redownloaded a fresh client off the Stormforge website and as soon as I log back in, with no addons at all and no cache folder, I get these same LUA errors.

**Comment by Wolffenstein** [comment]
Fix pending
