### ISSUE TITLE
[NPC]Tunnel Rat Kobold

### ISSUE THREAD

**Issue by Unryzen** [Atlantiss/NetherwingBugtracker#905]
**Description**:
Tunnel Rat Kobold mobs in Loch Modan don't use the spell (aura) called Thrash correctly and do maybe 2-3 times more damage than supposed. It was also the case on another private project.

**Current behaviour**:
Currently they have multiple Thrash (https://wowgaming.altervista.org/aowow/?spell=12787) aura applied, and the 2 extra swings are added to every hit from them. See combat log on screenshot 
(https://imgur.com/a/2zrwauT)

**Expected behaviour**: 
They supposed to have only 1 Thrash aura applied and the aura has a 35% chance proc rate.

**Server Revision**: 
2083

**Comment by The14me** [comment]
Damage is correct.
Confirm for missing Trash ID : 12787

**Comment by Evolvee** [comment]
they have only 1 thrash aura and the current chance is 15%
