### ISSUE TITLE
Force Reactive Disk - Bugged (lowered) dmg

### ISSUE THREAD

**Issue by Adroloth93** [Atlantiss/NetherwingBugtracker#9050]
Hi, this happened maybe 1 week or just few days ago - Force Reactive Disk shield stopped working properly. Now its dmg its completely bugged. It looks like that now it can does just some amount of aoe dmg that means, that the more mobs player have on him the lower dmg it couse. Normal function is that it should do 25-35dmg to each target after each block (it crits usually for 50-60dmg. At this point when I use it it does on big pulls just 4-6 (crits) per target which is hilarious. Please fix this bug. Thanks for your time. Before few days or it was like 1 week ago, it was  working properly.

**Comment by Godmatik** [comment]
![aaaaa](https://github.com/user-attachments/assets/cc07b7d9-15a3-4c1e-82e0-bf9a091054c7)

Seems to work just fine for me in Rev 4017
Possibly fixed with aura rework

**Comment by Adroloth93** [comment]
Hi just tested it in dungeon, and its not working ... If u want to test it
somewhere u need to pull like 20-40mobs there you can see if its working as
it should or not - if you pull like just up to 5-10mobs you will notice
just light diff in dmg but on 20-40 mobs it usually does max 6-7dmg per
target and there u really see it

št 8. 8. 2024 o 21:03 Matik ***@***.***> napísal(a):

**Comment by Adroloth93** [comment]
Now I saw that pic - usually it was hitting on my paladin (probably even to
SP scale bonus) around 50-70crits on target. thats the difference.

ne 11. 8. 2024 o 12:24 Miloš Pajan ***@***.***> napísal(a):
