### ISSUE TITLE
Items you can not equip are shown in wrong text color

### ISSUE THREAD

**Issue by Godmatik** [Atlantiss/NetherwingBugtracker#9051]
For example if there is a weapon that is too high of level for you to use, or its a weapon you don't have proficiency to use (you didn't train axes yet, but you have an axe in your bag), it should show as red text. 

Instead it shows as white text, as if you can equip it (even though if you try it won't allow you as expected)

**Comment by drewk8** [comment]
Can confirm on CP 2.4.0 revision 3987, mail armor appears "white" for Druids (at lvl 6)

**Comment by Wolffenstein** [comment]
Fixed in rev 3993.
