### ISSUE TITLE
Game dont count Ogrila's Ray catching 

### ISSUE THREAD

**Issue by trovi123** [Atlantiss/NetherwingBugtracker#9053]
![image](https://github.com/Atlantiss/NetherwingBugtracker/assets/136437891/d2e760c8-3fa3-4526-a0b8-6b8ff4111667)

**Comment by trovi123** [comment]
restart/quest drop didnt help

**Comment by Godmatik** [comment]
spoke with Wolf on this one, will be fixed after server update
