### ISSUE TITLE
Webwood Lurker - Web

### ISSUE THREAD

**Issue by Godmatik** [Atlantiss/NetherwingBugtracker#9054]
Shapeshifting into and out of bear does not clear the "Web" debuff from Webwoob Lurker (1998)

Maybe this impacts other NPC root debuffs also?

**Comment by Wolffenstein** [comment]
Only spells with MECHANIC_ROOT can be removed by shapeshifting, this one doesn't have it.

**Comment by Godmatik** [comment]
Interesting why it wouldn't be, I'll verify on classic sometime

**Comment by Wolffenstein** [comment]
check on classic and report back, its possible that its not a valid approach at all
