### ISSUE TITLE
Illidan - a couple of bugs

### ISSUE THREAD

**Issue by Godmatik** [Atlantiss/NetherwingBugtracker#9061]
1. When Maiev blinks and drops trap, she moves at giga speed back to her original position, thus dropping the trap right on Illidan

2. After trap expires, Illidan moves a couple of seconds before going demon. It's an old bug - he should instantly go to demon form after trap expires.

**Comment by Wolffenstein** [comment]
1. Fixed in rev 3988.

**Comment by Godmatik** [comment]
2 seems to be fixed also, closing
