### ISSUE TITLE
[Paladin][Spell] Spiritual Attunement - doesn't give mana back or random value

### ISSUE THREAD

**Issue by Nawakland** [Atlantiss/NetherwingBugtracker#9064]
[//]: # (Enclose links to things related to the bug using http://wowhead.com or any other TBC database.)
[//]: # (You can use screenshot ingame to visual the issue.)
[//]: # (Write your tickets according to the format:)
[//]: # ([Quest][Azuremyst Isle] Red Snapper - Very Tasty!)
[//]: # ([NPC] Magistrix Erona)
[//]: # ([Spell][Mage] Fireball)
[//]: # ([Npc][Drop] Ghostclaw Lynx)
[//]: # ([Web] Armory doesnt work)
[//]: # (To find server revision type `.server info` command in the game chat.)

**Description**: 
Spiritual Attunement is not giving mana back when the heal being used on the paladin bring the paladin to full health.
It works as long as the paladin is not brough up to maximum health.
Example: Paladin is at 50% health, heal crits him and brings him to 100% health, paladin does not gain mana back.
And according to the log it gives back random mana value too, should be 10%.

https://www.wowhead.com/tbc/spell=33776/spiritual-attunement

**Current behaviour**:
Take a look at the screenshot.
Give mana back unless the heal is bringing paladin to maximum health.
And according to the log it gives back random mana value too, should be 10%

![WoWScrnShot_050124_205309](https://github.com/Atlantiss/NetherwingBugtracker/assets/56754835/cbde27f9-a890-4ba5-92ab-fa9162975a2a)

**Expected behaviour**: 
 The paladin would gain mana back equal to the amount of health healed despite if the heal heals him to full.
 Mana value should be 10% of the paladin health recovered.

**Server Revision**:

**Comment by Nawakland** [comment]
![01_Spiritual Attunement_bug](https://github.com/Atlantiss/NetherwingBugtracker/assets/56754835/e8c3b3b8-12dd-44f7-bf98-9858dfc4c3a1)
![02_Spiritual Attunement_bug](https://github.com/Atlantiss/NetherwingBugtracker/assets/56754835/b1f0b8d1-efb1-4613-8475-f76606805d2f)
![03_Spiritual Attunement_bug](https://github.com/Atlantiss/NetherwingBugtracker/assets/56754835/349d3570-c16b-46d2-b002-18bb40b8a288)
![04_Spiritual Attunement_bug](https://github.com/Atlantiss/NetherwingBugtracker/assets/56754835/76fba355-1263-4d71-84e5-56687dee1013)

1 : No health, no mana.
2 : 3113 healed - 313 mana back instead of 311
3 : 4804 healed - 184 mana back instead of 480
4 : 3359 healed - no mana back instead of 178 (1789 health recovered)

**Comment by Wolffenstein** [comment]
Fix pending
