### ISSUE TITLE
[Spell][Druid] Tree of Life

### ISSUE THREAD

**Issue by khah97** [Atlantiss/NetherwingBugtracker#9065]
[//]: # (Enclose links to things related to the bug using http://wowhead.com or any other TBC database.)
[//]: # (You can use screenshot ingame to visual the issue.)
[//]: # (Write your tickets according to the format:)
[//]: # ([Quest][Azuremyst Isle] Red Snapper - Very Tasty!)
[//]: # ([NPC] Magistrix Erona)
[//]: # ([Spell][Mage] Fireball)
[//]: # ([Npc][Drop] Ghostclaw Lynx)
[//]: # ([Web] Armory doesnt work)
[//]: # (To find server revision type `.server info` command in the game chat.)

**Description**: 
Tree of Life does not apply the bonus healing received from the druid's spirit.

**Current behaviour**:
No extra healing received.

**Expected behaviour**: 
Extra healing should be received based on 25% spirit of the Tree of Life.

**Server Revision**: 
3987

![bug1](https://github.com/Atlantiss/NetherwingBugtracker/assets/143663894/6fbd32f1-fc95-4824-8036-ea4c91ad3df4)
![bug2](https://github.com/Atlantiss/NetherwingBugtracker/assets/143663894/2ff784b5-bdf3-4546-806c-33ef2162a3dd)

**Comment by khah97** [comment]
*Note* I **re-applied** lifebloom after shifting to tree form

**Comment by Wolffenstein** [comment]
Fixed in rev 3989.
