### ISSUE TITLE
Prayer of Mending visual bug

### ISSUE THREAD

**Issue by Mintey** [Atlantiss/NetherwingBugtracker#9067]
[//]: # (Enclose links to things related to the bug using http://wowhead.com or any other TBC database.)
[//]: # (You can use screenshot ingame to visual the issue.)
[//]: # (Write your tickets according to the format:)
[//]: # ([Quest][Azuremyst Isle] Red Snapper - Very Tasty!)
[//]: # ([NPC] Magistrix Erona)
[//]: # ([Spell][Mage] Fireball)
[//]: # ([Npc][Drop] Ghostclaw Lynx)
[//]: # ([Web] Armory doesnt work)
[//]: # (To find server revision type `.server info` command in the game chat.)

**Description**: 
Currently when Prayer of Mending bounces from target to target, the visual effect always comes from the priest who initially cast it, regardless of who had the buff previously. The target it bounces to is visually correct, but the source is not. 

**Current behaviour**:
Prayer of Mending bounces always visually comes from the priest. 

**Expected behaviour**: 
Prayer of Mending boucnes comes from the target that had prayer of mending on it. 

**Server Revision**: 
3988

**Comment by Godmatik** [comment]
Confirmed.

Someone also mentioned a prayer of mending bounce puts them in combat during PvP - but not sure about that one

**Comment by Wolffenstein** [comment]
Fixed in rev 3992.
