### ISSUE TITLE
Movement increases AoE range

### ISSUE THREAD

**Issue by Godmatik** [Atlantiss/NetherwingBugtracker#9068]
When standing still, AoE abilities done by players are the proper range.

When moving, there appears to be some sort of leeway that develops and the range of AoE abilities is increased by roughly 2 yards. This is inconsistent with classic, movement leeway should not increase AoE range.

**Comment by Wolffenstein** [comment]
https://old.reddit.com/r/classicwow/comments/c3twx9/aoe_leeway_has_been_fixed/ ?

**Comment by Godmatik** [comment]
This is what I get for misunderstanding what people in pvp channel are saying.
