### ISSUE TITLE
Black Bow of the Betrayer Not Proc'ing at Correct Rate

### ISSUE THREAD

**Issue by spacct** [Atlantiss/NetherwingBugtracker#9069]
[//]: # (Enclose links to things related to the bug using http://wowhead.com or any other TBC database.)
[//]: # (You can use screenshot ingame to visual the issue.)
[//]: # (Write your tickets according to the format:)
[//]: # ([Quest][Azuremyst Isle] Red Snapper - Very Tasty!)
[//]: # ([NPC] Magistrix Erona)
[//]: # ([Spell][Mage] Fireball)
[//]: # ([Npc][Drop] Ghostclaw Lynx)
[//]: # ([Web] Armory doesnt work)
[//]: # (To find server revision type `.server info` command in the game chat.)

**Description**: Black Bow of the Betrayer is not restoring mana on all shots. 

**Current behaviour**: When shots (auto, steady, arcane, multi, etc.) are done 1 at a time, in isolation, this bug doesnt not appear. However, when doing a simple rotation of auto shot -> steady shot, only half the mana is regen'd. This is reflected in the combat log (see below snip). 

Note: this test was done while not at 100% mana to ensure that having full mana was not the cause of the bug.

I believe this bug may be indicative of a problem with many chance on hit procs (trinkets like dst, other trinkets and class talents, etc). For whatever reason, many hits are not registering with the proc chances.

![image](https://github.com/Atlantiss/NetherwingBugtracker/assets/104590778/9fdd9dd5-d2c5-43b8-a808-4b391ed936b0)

**Expected behaviour**: All shots should restore 8 mana irrespective of whether done in isolation or if done in a rotation. Something is causing shots to be uncounted when mana regen should be taking place. I believe it is likely that this is also the case with Judgement of Wisdom, however this is harder to test due to the chance on hit nature of JoW rather than the guaranteed mana regen of Black Bow. 

50 auto shot hits and 50 steady shots hits resulted in 456 mana restored which means 57 out of 100 shots restored the intended 8 mana or a 57% rate rather than 100%. Rather than 456 mana restored, these 100 shot hits should have restored 800 mana. On raid boss encounters (requiring many hundreds of shots), this difference creates a huge impact.
![image](https://github.com/Atlantiss/NetherwingBugtracker/assets/104590778/8aef55e5-c913-48a0-9708-b0f3a83bb6c4)
![image](https://github.com/Atlantiss/NetherwingBugtracker/assets/104590778/3533c679-6eed-4d7a-8b03-5d49313bf866)
![image](https://github.com/Atlantiss/NetherwingBugtracker/assets/104590778/826be337-41a8-4da6-93bc-e0d815842ec1)

<img width="679" alt="image" src="https://github.com/Atlantiss/NetherwingBugtracker/assets/104590778/4a0e6c98-317a-423c-ae93-d84ce40988e6">
https://www.wowhead.com/tbc/spell=46939/black-bow-of-the-betrayer

**Server Revision**:

**Comment by Wolffenstein** [comment]
Fixed in rev 3991.
