### ISSUE TITLE
[Druid] Parried

### ISSUE THREAD

**Issue by NotATester** [Atlantiss/NetherwingBugtracker#907]
[//]: # (Enclose links to things related to the bug using http://wowhead.com or any other TBC database.)
[//]: # (You can use screenshot ingame to visual the issue.)
[//]: # (Write your tickets according to the format:)
[//]: # ([Quest][Azuremyst Isle] Red Snapper - Very Tasty!)
[//]: # ([NPC] Magistrix Erona)
[//]: # ([Spell][Mage] Fireball)
[//]: # ([Npc][Drop] Ghostclaw Lynx)
[//]: # ([Web] Armory doesnt work)

**Description**: Parried as a Druid [https://imgur.com/a/YRwECgi]

**Current behaviour**: I parried a Bristleback Interlopers spell "Muscle Tear"

**Expected behaviour**: Druids can't parry
Keep up the good work lads!
**Server Revision**:

**Comment by Wolffenstein** [comment]
Fixed in rev 2091.
