### ISSUE TITLE
Dragonspine Trophy Not Proc'ing at Correct Rate

### ISSUE THREAD

**Issue by spacct** [Atlantiss/NetherwingBugtracker#9071]
[//]: # (Enclose links to things related to the bug using http://wowhead.com or any other TBC database.)
[//]: # (You can use screenshot ingame to visual the issue.)
[//]: # (Write your tickets according to the format:)
[//]: # ([Quest][Azuremyst Isle] Red Snapper - Very Tasty!)
[//]: # ([NPC] Magistrix Erona)
[//]: # ([Spell][Mage] Fireball)
[//]: # ([Npc][Drop] Ghostclaw Lynx)
[//]: # ([Web] Armory doesnt work)
[//]: # (To find server revision type `.server info` command in the game chat.)

**Description**: Dragonspine Trophy not proc'ing at correct rate

**Current behaviour**: On first test, tested 100 attacks (auto shot -> steady shot), without proc'ing dragonspine trophy. The odds of this occuring is 0.00002 (assuming a 10% proc rate). Test was performed with several minutes prior to action (meaning the item was not on any sort of internal cooldown).

I have performed multiple tests using this method with similar results. A video of this length wont fit as a link here.

Something is going on with proc rates. It seems to be especially affected when using auto shot -> steady shot (1:1 rotation). Please see my previous bug reports on Judgement of Wisdom and Black Bow of the Betrayer proc rates. Something is causing hits to not register for procs correctly.

**Expected behaviour**: Dragonspine Trophy (if I'm not mistaken) should have a 10% proc rate when not on it's internal cooldown. 

**Server Revision**:

**Comment by Wolffenstein** [comment]
Fixed in rev 3991.
