### ISSUE TITLE
Go For the Throat not Proc'ing at Correct Rate

### ISSUE THREAD

**Issue by spacct** [Atlantiss/NetherwingBugtracker#9073]
[//]: # (Enclose links to things related to the bug using http://wowhead.com or any other TBC database.)
[//]: # (You can use screenshot ingame to visual the issue.)
[//]: # (Write your tickets according to the format:)
[//]: # ([Quest][Azuremyst Isle] Red Snapper - Very Tasty!)
[//]: # ([NPC] Magistrix Erona)
[//]: # ([Spell][Mage] Fireball)
[//]: # ([Npc][Drop] Ghostclaw Lynx)
[//]: # ([Web] Armory doesnt work)
[//]: # (To find server revision type `.server info` command in the game chat.)

**Description**: Hunter talent Go For the Throat is not proc'ing at correct rate.

**Current behaviour**: Go for the throat hunter talent is only proc'ing some of the time, rather than 100% of the time (see combatlog picture below).

Something is going on with proc rates. I'm not sure if it is only for Hunters (see my previous several posts) or if it is affecting all classes. This issue may be something related to ranged hits not registering properly for procs, or it may be physical hits in general.

5 critical ranged hits resulting in only 2 Go For the Throat procs.
<img width="311" alt="image" src="https://github.com/Atlantiss/NetherwingBugtracker/assets/104590778/fff519a2-e13a-4b7b-90f3-ff74c93ebeb1">

**Expected behaviour**: Go for the throat should proc on 100% of ranged critical hits.

<img width="665" alt="image" src="https://github.com/Atlantiss/NetherwingBugtracker/assets/104590778/0e81f6cb-0e28-4930-b2e6-4aa9872075d1">
https://www.wowhead.com/tbc/spell=34950/go-for-the-throat

**Server Revision**:

**Comment by Wolffenstein** [comment]
Fixed in rev 3991.
