### ISSUE TITLE
Amani dragons agro range

### ISSUE THREAD

**Issue by trovi123** [Atlantiss/NetherwingBugtracker#9074]
yesteray in ZA we did scip between bear and dragon boss with jumping from hut to pilar. Priveous runs and on PTR now dragons could not be body pulled on pilar. Yesterday we pulled them on pilar and wiped. https://www.youtube.com/watch?v=AJ0NbtZXRYY&t=1190s
PTR now:
![image](https://github.com/Atlantiss/NetherwingBugtracker/assets/136437891/99dc9ab7-c160-466a-a7a5-bdf629f51196)

**Comment by trovi123** [comment]
any info?

**Comment by Godmatik** [comment]
It happens if someone is too close to the dragons when jumping pillars. 

Their aggro range seems just fine to me and I was able to make the jump without aggroing them (as long as you do it proper)
