### ISSUE TITLE
Judgement of Wisdom Proc Rate Unchanged Following Server Update - Not Solved by Change to Steady Shot

### ISSUE THREAD

**Issue by spacct** [Atlantiss/NetherwingBugtracker#9076]
[//]: # (Enclose links to things related to the bug using http://wowhead.com or any other TBC database.)
[//]: # (You can use screenshot ingame to visual the issue.)
[//]: # (Write your tickets according to the format:)
[//]: # ([Quest][Azuremyst Isle] Red Snapper - Very Tasty!)
[//]: # ([NPC] Magistrix Erona)
[//]: # ([Spell][Mage] Fireball)
[//]: # ([Npc][Drop] Ghostclaw Lynx)
[//]: # ([Web] Armory doesnt work)
[//]: # (To find server revision type `.server info` command in the game chat.)

**Description**: Judgement of Wisdom proc rate unchanged and below expected following closed bug report and server update. (https://github.com/Atlantiss/NetherwingBugtracker/issues/9070)
<img width="820" alt="image" src="https://github.com/Atlantiss/NetherwingBugtracker/assets/104590778/449280d3-bfe6-4688-9a0b-6f9072523c17">
<img width="191" alt="image" src="https://github.com/Atlantiss/NetherwingBugtracker/assets/104590778/74ddbd8f-9ba4-413c-a104-7e23d81c30f9">

**Current behaviour**: Tested on PTR following server update. Judgement of Wisdom still proc'ing at lower than expected rate. Appears to be unaffected by change to steady shot.

Ranged Test (using auto shot and Steady Shot):
171 hits, 4,292 mana restored (58 procs); 33.92% proc chance.

Combat log for reference on most recent Judgement of Wisdom test on PTR following server update (ranged only)
![image](https://github.com/Atlantiss/NetherwingBugtracker/assets/104590778/7c79e12b-19a0-48a0-a40f-19e1140a9805)

Melee attack (white hits only) test yielding 10,730 mana (145 procs) across 505 melee white hits for a rate of 0.2871 (28.71% chance to proc):
![image](https://github.com/Atlantiss/NetherwingBugtracker/assets/104590778/6a6f1590-31dc-4144-bee8-3d884072ef27)
![image](https://github.com/Atlantiss/NetherwingBugtracker/assets/104590778/d0a4a259-4382-4676-b578-850603f1f24a)

Melee attack white hit combat log for reference:
![image](https://github.com/Atlantiss/NetherwingBugtracker/assets/104590778/d51be69e-5bfe-4da9-a874-b05f92c029b6)

For additional information regarding this bug: Prior to the update, I used the Faceless logs mentioned in my previous post comment to compare procs for Enhancement Shaman melee attacks and damaging spells (to investigate if this lower proc rate issue is isolated to Hunter), and the proc rate for the Shaman for Judgement of Wisdom was: 103 Judgement of Wisdom procs, 383 attacks hit for a 26.89% proc chance.

**Expected behaviour**: All attack and spell hits against an enemy with Judgement of Wisdom debuff should have a 50% chance to proc the mana gain.

**Server Revision**:

**Comment by Wolffenstein** [comment]
Fixed in rev 3993.

**Comment by spacct** [comment]
Tested quicky 101 ranged attacks. 57 procs for a 56% proc rate on this small sample. Appears fixed
