### ISSUE TITLE
[2.4 PTR] Sunwell Trash bugs, second half of raid

### ISSUE THREAD

**Issue by Godmatik** [Atlantiss/NetherwingBugtracker#9077]
All screenshots from logs listed below

**Shadowsword Lifeshaper**
Only uses drain life on tank, should use it on a random person (46466)
Missing ability "Health Funnel" (46467)

**Shadowsword Soulbinder** 
"Domination" ability bugged - does nothing (46427)

**Oblivion Mage**
Spams flame buffet non-stop and never does melee attacks. If a tank is in melee range, they should do melee every so often. If no tank in range, then they should spam their flame buffet.

**Chaos Gazer**
Missing ability Drain Life (46291)

**Cataclysm Hound**
He is only targeting the tank with Cataclysm Breath. He should target someone random in melee range instead and apply it as a cone to that direction.
In addition, looking at logs, the breath should apply 1-3 random debuffs on you. Instead it is currently applying 4-5 or so at once.

Gate to KJ closed so can't test the Shadowsword Guardians

![lifeshaper](https://github.com/Atlantiss/NetherwingBugtracker/assets/37913400/45ca80b4-9307-4288-8bc2-22cbaabf2a66)

![Funnel](https://github.com/Atlantiss/NetherwingBugtracker/assets/37913400/0093d2f6-f76a-4dcc-9bea-4ad805c1671e)

![flamebuffet](https://github.com/Atlantiss/NetherwingBugtracker/assets/37913400/f8941f01-3cf0-43e2-9faa-7eb7c4ebf62c)

![Hound](https://github.com/Atlantiss/NetherwingBugtracker/assets/37913400/7e7addcc-2069-40b4-bb62-18d58ff364c1)

**Comment by Wolffenstein** [comment]
![image](https://github.com/Atlantiss/NetherwingBugtracker/assets/1576644/385d994e-a2c3-49b1-b388-52b8f24a60e2)
they just cant cast it on themselves (SPELL_ATTR1_EXCLUDE_CASTER)

**Comment by Wolffenstein** [comment]
![image](https://github.com/Atlantiss/NetherwingBugtracker/assets/1576644/0bd199df-4eee-4bb7-8a8b-7ae5ac416088)
It won't work if you're testing it solo

**Comment by Wolffenstein** [comment]
Chaos Gazer casts Drain Life but only on a non-tank target (so will not happen if you're solo) and only when hes under low hp threshold

**Comment by Wolffenstein** [comment]
Fixed in rev 3999.
