### ISSUE TITLE
[Quest][Stranglethorn Vale] Troll Witchery

### ISSUE THREAD

**Issue by kudryashov-n** [Atlantiss/NetherwingBugtracker#908]
[//]: # (Enclose links to things related to the bug using http://wowhead.com or any other TBC database.)
[//]: # (You can use screenshot ingame to visual the issue.)
[//]: # (Write your tickets according to the format:)
[//]: # ([Quest][Azuremyst Isle] Red Snapper - Very Tasty!)
[//]: # ([NPC] Magistrix Erona)
[//]: # ([Spell][Mage] Fireball)
[//]: # ([Npc][Drop] Ghostclaw Lynx)
[//]: # ([Web] Armory doesnt work)

**Description**: 
Low droprate.
**Current behaviour**:
Insanely low droprate of quest items. I killed 26 mystics and got none of the quest item.
https://classicdb.ch/?item=2466
**Expected behaviour**: 

**Server Revision**:

**Comment by aresbrutus** [comment]
The drop rate has already been corrected to blizzlike values in a previous rev. The drop rate is supposed to be pretty bad for this quest.
