### ISSUE TITLE
Target Self

### ISSUE THREAD

**Issue by ghost** [Atlantiss/NetherwingBugtracker#9081]
[//]: # (Enclose links to things related to the bug using http://wowhead.com or any other TBC database.)
[//]: # (You can use screenshot ingame to visual the issue.)
[//]: # (Write your tickets according to the format:)
[//]: # ([Quest][Azuremyst Isle] Red Snapper - Very Tasty!)
[//]: # ([NPC] Magistrix Erona)
[//]: # ([Spell][Mage] Fireball)
[//]: # ([Npc][Drop] Ghostclaw Lynx)
[//]: # ([Web] Armory doesnt work)
[//]: # (To find server revision type `.server info` command in the game chat.)

**Description**: Target Self function is not working correctly if the user has a pet.

**Current behaviour**: It alternates between player and pet.

**Expected behaviour**:

**Server Revision**:

**Comment by Godmatik** [comment]
sounds intended

![target self](https://github.com/Atlantiss/NetherwingBugtracker/assets/37913400/845f66fc-935f-4d37-8920-06ae3c332b91)

**Comment by Wolffenstein** [comment]
clientside anyway
