### ISSUE TITLE
Spell Leeway

### ISSUE THREAD

**Issue by ghost** [Atlantiss/NetherwingBugtracker#9082]
[//]: # (Enclose links to things related to the bug using http://wowhead.com or any other TBC database.)
[//]: # (You can use screenshot ingame to visual the issue.)
[//]: # (Write your tickets according to the format:)
[//]: # ([Quest][Azuremyst Isle] Red Snapper - Very Tasty!)
[//]: # ([NPC] Magistrix Erona)
[//]: # ([Spell][Mage] Fireball)
[//]: # ([Npc][Drop] Ghostclaw Lynx)
[//]: # ([Web] Armory doesnt work)
[//]: # (To find server revision type `.server info` command in the game chat.)

**Description**: Leeway mechanic is not working for spells.

**Current behaviour**: 

**Expected behaviour**: 

**Server Revision**: 3993

**Comment by Godmatik** [comment]
tested it a few times - works just fine for me

https://streamable.com/8r5905

**Comment by ghost** [comment]
@Godmatik you weren't at max range, see the action button indicator

**Comment by Godmatik** [comment]
I was, here is another test. 

I am at max range of spell (30y), target starts moving after my cast begins, see how the icon goes red as if out of range, but mind blast still gets off

https://streamable.com/xqcpyu

**Comment by ghost** [comment]
Weird, that didn't work for me. What about AOE spells, do you get extra range while moving?

**Comment by Godmatik** [comment]
AoE spells has 2 yard movement leeway built in, yes.

If you are not experiencing this, probably need to see a clip

**Comment by ghost** [comment]
I'm not experiencing leeway on any type of spell (live realm). Mind Flay breaks instanly when i move out of max range. As a channeled spell it should get around 5 yards of leeway talented.

**Comment by Godmatik** [comment]
I'll test mind flay as well later on PTR when I'm back home

**Comment by Mintey** [comment]
I did some testing with a friend outside of SW on the live realm (rev 3996) and here are the clips. Conclusions we drew were that there were no leeway on any cast spells (neither heals nor damaging abilities), but there is a slight one on arcane missiles (did not test other channelled abilities). 

https://github.com/Atlantiss/NetherwingBugtracker/assets/11920749/13b4aea0-a1da-49ee-b7b8-551f58577849


https://github.com/Atlantiss/NetherwingBugtracker/assets/11920749/8416c438-719b-4a73-98ad-de98c7147cf6


https://github.com/Atlantiss/NetherwingBugtracker/assets/11920749/608cd2ac-f34e-41cd-b6c7-6fa8b8675b44
