### ISSUE TITLE
Arathi Basin assaulting

### ISSUE THREAD

**Issue by ghost** [Atlantiss/NetherwingBugtracker#9083]
[//]: # (Enclose links to things related to the bug using http://wowhead.com or any other TBC database.)
[//]: # (You can use screenshot ingame to visual the issue.)
[//]: # (Write your tickets according to the format:)
[//]: # ([Quest][Azuremyst Isle] Red Snapper - Very Tasty!)
[//]: # ([NPC] Magistrix Erona)
[//]: # ([Spell][Mage] Fireball)
[//]: # ([Npc][Drop] Ghostclaw Lynx)
[//]: # ([Web] Armory doesnt work)
[//]: # (To find server revision type `.server info` command in the game chat.)

**Description**: Assaulting gets interrupted if enemy team captures the node during the attempt.

**Current behaviour**:

**Expected behaviour**: 

**Server Revision**: 3993

**Comment by Godmatik** [comment]
I don't really understand.

So basically you mean if you are mid capping a flag in AB to try and recapture a base and the timer runs out because enemy takes control of base, so the capping stops - isn't that intended?

**Comment by ghost** [comment]
Yes and no its a bug.

**Comment by Godmatik** [comment]
How is it a bug though? Just the fact that it is interrupted? If it's not interrupted and the cast bar finishes after enemy recaptured base, what happens?

**Comment by Wolffenstein** [comment]
Can we get a source/proof that it's a bug? A retail/classic video will do

**Comment by Godmatik** [comment]
No proof provided, I can't find any, and OP deleted his github acct.

Closing
