### ISSUE TITLE
[Rogue] Opportunity talent bonus damage

### ISSUE THREAD

**Issue by Spartanv** [Atlantiss/NetherwingBugtracker#9088]
**Description**: 
Opportunity talent is boosting abilities like ambush, garrote etc more than 20%
https://www.wowhead.com/tbc/spell=14075/opportunity#comments
Whole talent tree link:
https://www.wowhead.com/tbc/talent-calc/rogue/0053201--5502330302321213501351
**Current behaviour**:
On player 16k armor 360 resi: 
With opportunity 5/5: Ambush 2.8k - 3k crits
Without talent: Ambush 1.5k - 1.7k crits
**Expected behaviour**: 
Opportunity talent should boost abilities like ambush by 20%.
In this video from tbc classic this rogue plays with exactly same talent tree that I linked with Opportunity 5/5
Talents: time stamp:
https://youtu.be/872jnH5R6U4?t=93 
Ambush on another rogue time stamp: 3.1k
https://youtu.be/872jnH5R6U4?t=232
**Server Revision**: 
3995

**Comment by Wolffenstein** [comment]
Fixed in rev 3996.
