### ISSUE TITLE
Pet aggressive stance

### ISSUE THREAD

**Issue by ghost** [Atlantiss/NetherwingBugtracker#9089]
[//]: # (Enclose links to things related to the bug using http://wowhead.com or any other TBC database.)
[//]: # (You can use screenshot ingame to visual the issue.)
[//]: # (Write your tickets according to the format:)
[//]: # ([Quest][Azuremyst Isle] Red Snapper - Very Tasty!)
[//]: # ([NPC] Magistrix Erona)
[//]: # ([Spell][Mage] Fireball)
[//]: # ([Npc][Drop] Ghostclaw Lynx)
[//]: # ([Web] Armory doesnt work)
[//]: # (To find server revision type `.server info` command in the game chat.)

**Description**: Its just not working

**Current behaviour**: Pets ignore nearby hostile units, as if set to passive

**Expected behaviour**: 

**Server Revision**: 3995

**Comment by Wolffenstein** [comment]
It technically works but the aggro radius is incorrectly very small.

Fixed in rev 3996.
