### ISSUE TITLE
Zeppelin Visual Bug

### ISSUE THREAD

**Issue by RandomGuyFromDiscordServer** [Atlantiss/NetherwingBugtracker#909]
[//]: # (Enclose links to things related to the bug using http://wowhead.com or any other TBC database.)
[//]: # (You can use screenshot ingame to visual the issue.)
[//]: # (Write your tickets according to the format:)
[//]: # ([Quest][Azuremyst Isle] Red Snapper - Very Tasty!)
[//]: # ([NPC] Magistrix Erona)
[//]: # ([Spell][Mage] Fireball)
[//]: # ([Npc][Drop] Ghostclaw Lynx)
[//]: # ([Web] Armory doesnt work)

**Description**: 
You can see it in the video, that zeppelin bugged. https://clips.twitch.tv/PuzzledAgitatedAmazonUncleNox
**Current behaviour**:

**Expected behaviour**: 

**Server Revision**:

**Comment by wtRCH** [comment]
Already known issue.
