### ISSUE TITLE
Elemental Overload procs trigger Elemental Mastery critical strike

### ISSUE THREAD

**Issue by kire374** [Atlantiss/NetherwingBugtracker#9093]
[//]: # (Enclose links to things related to the bug using http://wowhead.com or any other TBC database.)
[//]: # (You can use screenshot ingame to visual the issue.)
[//]: # (Write your tickets according to the format:)
[//]: # ([Quest][Azuremyst Isle] Red Snapper - Very Tasty!)
[//]: # ([NPC] Magistrix Erona)
[//]: # ([Spell][Mage] Fireball)
[//]: # ([Npc][Drop] Ghostclaw Lynx)
[//]: # ([Web] Armory doesnt work)
[//]: # (To find server revision type `.server info` command in the game chat.)

**Description**: 
This was also a problem in a closed thread that was supposedly fixed in 2019, but is definitely happening on Stormforge Netherwing server, so I will copy the text.
Elemental Mastery (Elemental Shaman talent tree) triggers a critical strike from spell casts, such as Chain Lightning, Shock spells, Lightning bolt etc.
Lightning Overload (Elemental Shaman talent tree) talent gives a 4-20% chance to cast a second similar spell that costs no mana and deals half damage.

The problem with these two is, when you cast a spell, and turn on Elemental Mastery after the first cast, to cast another 100% crit spell, IF the first cast triggers Lightning Overload, it produces another cast of a smaller spell and that smaller proc triggers the Elemental Mastery 100% critical strike. You not only lose the cooldown, but the damage you wanted to do with the big second spell.

**Current behaviour**:
Lightning overload procs trigger Elemental Mastery 100% critical strike and uses up the cooldown.
**Expected behaviour**: 
Lightning overload procs should not trigger elemental mastery's effect.
**Server Revision**:

**Comment by Wolffenstein** [comment]
Fixed in rev 3999.
