### ISSUE TITLE
[Quest] Teron Gorefiend, I am...

### ISSUE THREAD

**Issue by Godmatik** [Atlantiss/NetherwingBugtracker#9094]
Quest is completable but it's just bugged.

Your character is transformed into a wisp after starting the quest, but should not be.
Krasius the Ancient Watcher attacks your character instead of the Teron creature you are controlling.
All heals you do from the drain life ability is applied to your character instead of Teron.

https://streamable.com/pip454

**Comment by Wolffenstein** [comment]
Fixed in rev 3999.
