### ISSUE TITLE
Volley

### ISSUE THREAD

**Issue by Godmatik** [Atlantiss/NetherwingBugtracker#9099]
Using hunter spell "Volley" while having Aspect of the Cheetah or Pack active will cause you to daze yourself

**Comment by spacct** [comment]
this is actually hilarious and should be left as is

**Comment by spacct** [comment]
It is July. How has this not been fixed lol?

**Comment by Godmatik** [comment]
Because past few months, Wolf has been focused on revamping some major systems and setting up + scripting cross-faction

**Comment by Godmatik** [comment]
Got fixed a while ago, just forgot to close this out
