### ISSUE TITLE
Deeprun Tram

### ISSUE THREAD

**Issue by Piledriversn** [Atlantiss/NetherwingBugtracker#910]
There was only 2 cars on the Tram and not 3. 
![image](https://user-images.githubusercontent.com/43560552/46247932-13f55e80-c3d8-11e8-9d3e-535f318ac80b.png)
https://www.youtube.com/watch?v=81a_6Wygrmc
(Disclaimer the music is very loud)

**Comment by Sinyr** [comment]
Only 1 train is also possible

![image](https://user-images.githubusercontent.com/9539181/46309936-28934b80-c5be-11e8-9412-a767412a115d.png)

**Comment by Wolffenstein** [comment]
Fixed
