### ISSUE TITLE
.instance difficulty 0/1 does not update instance info properly

### ISSUE THREAD

**Issue by buza-me** [Atlantiss/NetherwingBugtracker#9102]
**Description**: 
It is impossible to make a decent WA/DBM mod for both difficulties because instance difficulty info is static unless changed using the character portrait menu. /reload does not help.
**Current behaviour**:
After changing the raid difficulty with ".instance difficulty", GetInstanceInfo() return values and the difficulty indicated in the character menu are not updated.
**Expected behaviour**: 
After changing the raid difficulty with ".instance difficulty", GetInstanceInfo() return values and the difficulty indicated in the character menu should be updated.
**Server Revision**: 
live idk, PTR - 4000

**Comment by Godmatik** [comment]
![soundslike](https://github.com/Atlantiss/NetherwingBugtracker/assets/37913400/0b92b26d-8396-423e-92ab-8683c4142efe)

Sounds like from this statement, it is not possible to fix. It would be nice if he could I agree though. Will let Wolf comment on the matter to verify though.

**Comment by buza-me** [comment]
Ah, I see. Well, if it is possible to fix it, it would be great.

**Comment by Wolffenstein** [comment]
Will be changed in rev 4002.
