### ISSUE TITLE
The Sleeper Has Awakened - bug

### ISSUE THREAD

**Issue by Davkacz** [Atlantiss/NetherwingBugtracker#9104]
[//]: # (Enclose links to things related to the bug using http://wowhead.com or any other TBC database.)
[//]: # (You can use screenshot ingame to visual the issue.)
[//]: # (Write your tickets according to the format:)
[//]: # ([Quest][Azuremyst Isle] Red Snapper - Very Tasty!)
[//]: # ([NPC] Magistrix Erona)
[//]: # ([Spell][Mage] Fireball)
[//]: # ([Npc][Drop] Ghostclaw Lynx)
[//]: # ([Web] Armory doesnt work)
[//]: # (To find server revision type `.server info` command in the game chat.)

**Description**: after take the quest, the game freezes. I tried it several times.
![bugg](https://github.com/Atlantiss/NetherwingBugtracker/assets/170537474/17a0191e-d457-4259-9a93-76bffa70c7d7)

**Current behaviour**:

**Expected behaviour**: 

**Server Revision**:

**Comment by Godmatik** [comment]
It's because of your Quest Helper addon.

This addon sucks really bad and freezes for timed quests. Remove it. I recommend pfQuest.

Not a bug, can be closed
