### ISSUE TITLE
3.3.5a Spell Power

### ISSUE THREAD

**Issue by ghost** [Atlantiss/NetherwingBugtracker#9109]
[//]: # (Enclose links to things related to the bug using http://wowhead.com or any other TBC database.)
[//]: # (You can use screenshot ingame to visual the issue.)
[//]: # (Write your tickets according to the format:)
[//]: # ([Quest][Azuremyst Isle] Red Snapper - Very Tasty!)
[//]: # ([NPC] Magistrix Erona)
[//]: # ([Spell][Mage] Fireball)
[//]: # ([Npc][Drop] Ghostclaw Lynx)
[//]: # ([Web] Armory doesnt work)
[//]: # (To find server revision type `.server info` command in the game chat.)

**Description**: +Healing and +Spell Damage are displayed as +Spell Power

**Current behaviour**:

**Expected behaviour**: 

**Server Revision**: 4002

**Comment by Godmatik** [comment]
should be fixed now, can close
