### ISSUE TITLE
[NPC][Paladin][Stormwind] Paladin trainers in SW are not able to reset talents

### ISSUE THREAD

**Issue by Ylette** [Atlantiss/NetherwingBugtracker#911]
[//]: # (Enclose links to things related to the bug using http://wowhead.com or any other TBC database.)
[//]: # (You can use screenshot ingame to visual the issue.)
[//]: # (Write your tickets according to the format:)
[//]: # ([Quest][Azuremyst Isle] Red Snapper - Very Tasty!)
[//]: # ([NPC] Magistrix Erona)
[//]: # ([Spell][Mage] Fireball)
[//]: # ([Npc][Drop] Ghostclaw Lynx)
[//]: # ([Web] Armory doesnt work)

**Description**: Every class trainer should have the possibility to reset the talents on the player's request.

**Current behaviour**: The Paladin trainers in Stomwind do not have a talent reset option (the trainers in Ironforge don't have this problem).
![bug](https://user-images.githubusercontent.com/43707486/46249129-52b10600-c424-11e8-97f6-98a6e689797b.jpg)
![bug2](https://user-images.githubusercontent.com/43707486/46249131-6197b880-c424-11e8-8b88-c26639d4d569.jpg)

**Expected behaviour**: The trainers should have this option.

**Server Revision**: 2083

**Comment by toto6** [comment]
Fixed in Server Revision 2150
