### ISSUE TITLE
self-dispel

### ISSUE THREAD

**Issue by ghost** [Atlantiss/NetherwingBugtracker#9110]
[//]: # (Enclose links to things related to the bug using http://wowhead.com or any other TBC database.)
[//]: # (You can use screenshot ingame to visual the issue.)
[//]: # (Write your tickets according to the format:)
[//]: # ([Quest][Azuremyst Isle] Red Snapper - Very Tasty!)
[//]: # ([NPC] Magistrix Erona)
[//]: # ([Spell][Mage] Fireball)
[//]: # ([Npc][Drop] Ghostclaw Lynx)
[//]: # ([Web] Armory doesnt work)
[//]: # (To find server revision type `.server info` command in the game chat.)

**Description**: Dispel Magic directed at oneself will attempt to remove buffs

**Current behaviour**:

**Expected behaviour**: `Nothing to dispel`

**Server Revision**: 4002

**Comment by Godmatik** [comment]
fixed now, download latest 3.3.5 patch
