### ISSUE TITLE
Priest Levitate

### ISSUE THREAD

**Issue by ghost** [Atlantiss/NetherwingBugtracker#9113]
There's no elevation. Caster remains grounded and movement speed is seemingly reduced.

client: 3.3.5a
revision: 4002

**Comment by Godmatik** [comment]
Confirmed but visual issue only.
Priest still will walk across water and float when falling from high altitude

**Comment by ghost** [comment]
Nah, you get stuck on small obstacles (stairs, rocks) which normally doesn't happen. Also the movement speed issue.

**Comment by Godmatik** [comment]
Try again with new patch, think it's fixed

**Comment by Wolffenstein** [comment]
Will be fixed after next server update
