### ISSUE TITLE
[Quest][Isle of Quel'Danas] The Air Strikes Must Continue - 11533 - 3.3.5 client

### ISSUE THREAD

**Issue by Pavelow1806** [Atlantiss/NetherwingBugtracker#9114]
[//]: # (Enclose links to things related to the bug using http://wowhead.com or any other TBC database.)
[//]: # (You can use screenshot ingame to visual the issue.)
[//]: # (Write your tickets according to the format:)
[//]: # ([Quest][Azuremyst Isle] Red Snapper - Very Tasty!)
[//]: # ([NPC] Magistrix Erona)
[//]: # ([Spell][Mage] Fireball)
[//]: # ([Npc][Drop] Ghostclaw Lynx)
[//]: # ([Web] Armory doesnt work)
[//]: # (To find server revision type `.server info` command in the game chat.)

**Description**: 
Using the provided quest item **Arcane Charges** (34475 [wowhead](https://www.wowhead.com/tbc/item=34475/arcane-charges)) (seen in screenshots below) results in the error message "You are in the wrong zone."

![image](https://github.com/Atlantiss/NetherwingBugtracker/assets/33148421/53c054e4-ce24-4c74-8abd-ee7bac693273)
![image](https://github.com/Atlantiss/NetherwingBugtracker/assets/33148421/2a8ff514-58da-4730-93b2-2058837d0571)

**Current behaviour**:
You are in the wrong zone error message, unable to use quest item to complete quest.

**Expected behaviour**: 
Quest item usable to complete quest.

**Server Revision**:

**Comment by Pavelow1806** [comment]
I relogged the 2.4.3 client and it works fine

**Comment by Wolffenstein** [comment]
redownload the patch
