### ISSUE TITLE
[Item] Green items not displaying stats - 3.3.5 client

### ISSUE THREAD

**Issue by Pavelow1806** [Atlantiss/NetherwingBugtracker#9115]
[//]: # (Enclose links to things related to the bug using http://wowhead.com or any other TBC database.)
[//]: # (You can use screenshot ingame to visual the issue.)
[//]: # (Write your tickets according to the format:)
[//]: # ([Quest][Azuremyst Isle] Red Snapper - Very Tasty!)
[//]: # ([NPC] Magistrix Erona)
[//]: # ([Spell][Mage] Fireball)
[//]: # ([Npc][Drop] Ghostclaw Lynx)
[//]: # ([Web] Armory doesnt work)
[//]: # (To find server revision type `.server info` command in the game chat.)

**Description**: 
Some random greens aren't displaying stats in the new 3.3.5 client.

**Current behaviour**:
![image](https://github.com/Atlantiss/NetherwingBugtracker/assets/33148421/503a26d1-a353-4632-a3e1-39aab91d19c5)
![image](https://github.com/Atlantiss/NetherwingBugtracker/assets/33148421/76ba2a1b-e075-4e16-a9d2-af0e990ced20)

**Expected behaviour**: 
![image](https://github.com/Atlantiss/NetherwingBugtracker/assets/33148421/36927b26-d947-479b-a7d9-2fbfb51ad3b1)
![image](https://github.com/Atlantiss/NetherwingBugtracker/assets/33148421/e94eb230-c176-4f98-b06f-9bcd7c105c78)

**Server Revision**:

**Comment by Pavelow1806** [comment]
*only some green items have this happen to them

**Comment by Wolffenstein** [comment]
Fixed, redownload the patch
