### ISSUE TITLE
[Druid] Boomkin T5 set bonus doesn't work (4 pieces)

### ISSUE THREAD

**Issue by Onsty** [Atlantiss/NetherwingBugtracker#9120]
4 pieces t5 bonus doesn't work for balance druid
Tested on ptr
500 starfire casts
500 starfire casts with swarm
It's literally same numbers
![Group 1321316952](https://github.com/Atlantiss/NetherwingBugtracker/assets/44346265/54507b04-c84c-44fb-9d77-c7b1308e3345)

**Expected behaviour**: should increase Starfire damage by 10% against targer afflicted by moonfire or swarm

**Server Revision**: 4003

**Comment by Wolffenstein** [comment]
Fixed in rev 4015.
