### ISSUE TITLE
Grand Warlock Nethekurse ( First Boss of SHH Dungeon )

### ISSUE THREAD

**Issue by Sirgunter** [Atlantiss/NetherwingBugtracker#9121]
[//]: # https://www.wowhead.com/tbc/es/npc=16807/brujo-supremo-malbisal#abilities;mode:normal

[//]: # Grand Warlock Nethekurse
[//]: # Dark Spin

**Description**: This is the first boss of the SHH dungeon. The last time I did this boss in heroic mode, at the last moment when the boss is close to dying, he performs his "Dark Spin" causing physical damage if you are stuck to him and casting shadow spells randomly at the party. dungeon. The boss only did physical damage, but did not cast the shadow spell.

Atte. Tuerconi / Grangrimbli

**Current behaviour**:

**Expected behaviour**: 

**Server Revision**:

**Comment by Godmatik** [comment]
Confirmed.

Happens if he is moving when he reaches the 20% threshold.

https://github.com/Atlantiss/NetherwingBugtracker/issues/8285

**Comment by Sirgunter** [comment]
yersterday i did SHH again. Still bug that boss and the hallway. The part of the archers with fire arrows

**Comment by Godmatik** [comment]
I reminded Wolf about both of these SHH bugs, he is busy at the moment revamping a major system, but will get to it after that.

**Comment by Godmatik** [comment]
Wolf fixed this in rev 4015
