### ISSUE TITLE
SHH Dungeon Heroic and Normal mode Shattered Hand Archer  ( Hallway )

### ISSUE THREAD

**Issue by Sirgunter** [Atlantiss/NetherwingBugtracker#9122]
[//]: # https://www.youtube.com/watch?v=PQIt63gvEOo ( start minute 38:00 video ) https://www.wowhead.com/tbc/es/zone=3714/las-salas-arrasadas#npcs

[//]: # Shattered Hand Archer
[//]: # fire arrow , explosion , and fire in the ground

**Description**: In the SHH Dungeon in heroic/normal mode, there is a part that is in a long hallway. When the party players advance through this hallway, in the background there are some archers who must shoot us incendiary arrows, which do area damage and leave fire on the ground. I have done this dungeon in heroic / normal mode and previously it worked correctly on the server. day 10/9/2024, it does not work correctly in either of the two heroic/normal modes. The archers shoot the arrows, but they cause no damage, nor do they leave fire on the ground.

Atte.Tuerconi / Grangrimbli

**Current behaviour**:

**Expected behaviour**: 

**Server Revision**:

**Comment by Godmatik** [comment]
Probably broke after spell rework and no one bothered to report it.

**Comment by Godmatik** [comment]
Wolf fixed this in rev 4015
