### ISSUE TITLE
Blood Furnace Dungeon (Heroic) . First Boss " The Maker " ( No Cast Spell "Slime Spray" Posion damage )

### ISSUE THREAD

**Issue by Sirgunter** [Atlantiss/NetherwingBugtracker#9123]
[//]: # https://www.youtube.com/watch?v=M4fFTs_5RjA

[//]: # ([NPC] The Maker)

[//]: # (Slime Spray)

**Description**: Hello. On Netherwing server, I have done the Blood Furnace dungeon in normal/heroic mode. The first boss we face is called "The Maker" among the skills he casts is one with poison damage called "slime spray". Day 9/6/2024, I did the dungeon and he didn't cast that spell "Slime Spray"

Atte. Tuerconi / Grangrimbli

**Current behaviour**:

**Expected behaviour**: 

**Server Revision**:

**Comment by Godmatik** [comment]
What you linked he does not even do the fight, just explains it.

I watched several classic videos, both normal and heroic, of groups actually fighting The Maker, and can not find any evidence that such an ability exists, nor is it on his spell-list on wowhead.

Do you have a video of this boss actually using it?

**Comment by Godmatik** [comment]
No response, and I still can't find any evidence. If you see any please post it when you can.

Closing.

**Comment by Sirgunter** [comment]
https://www.youtube.com/watch?v=M4fFTs_5RjA

Hi Matik.

This is the same Video that i posted on the bugtracker.

Starting at minute 3:50 of the video, "The Maker" said boss is detailed.

And i perfectly remember that in Netherwing before adding client 3.3.5,
"The Maker" (boss) cast this spell.

I hope you can fix it.

thanks you very much for your reply

**Comment by Godmatik** [comment]
As I stated to you, he does not actually do the fight in this video - he just describes the abilities.

I have watched several classic videos, and do not see that this ability exists.

I need proof from a classic video showing The Maker actually casting this Slime Spray spell
