### ISSUE TITLE
[SWP] Eredar Twins shadow images not using dark strike

### ISSUE THREAD

**Issue by Onsty** [Atlantiss/NetherwingBugtracker#9125]
Shadow images not using dark strike

https://youtube.com/clip/UgkxchEYcwLJ_U3l9eMa8mhwqJI1_-0iUqrm?si=kPOdJvpxf7Q57Z9G

**Server Revision**: 4006

**Comment by Wolffenstein** [comment]
Fixed in rev 4009.
