### ISSUE TITLE
Divine favor does not consume after using holyshock

### ISSUE THREAD

**Issue by AcexHkx** [Atlantiss/NetherwingBugtracker#9126]
[Spell][Paladin] Divine Favor
https://www.wowhead.com/tbc/es/spell=20216/favor-divino
https://www.wowhead.com/tbc/es/spell=20473/choque-sagrado
**Description**: 
Divine favor does not dissapear after the usage of Holy shock
**Current behaviour**:
Divine favor remains after the usage of holy shock always getting the critic buff
**Expected behaviour**: 
Divine favor should be gone after the usage of holy shock
**Server Revision**: 
Netherwing
![image](https://github.com/Atlantiss/NetherwingBugtracker/assets/172915184/3dc8031d-112a-4d22-8bdf-f2c68f0f5849)

**Comment by Wolffenstein** [comment]
Fixed in rev 4007.
