### ISSUE TITLE
[Warlock] Ritual of Summoning costs double mana

### ISSUE THREAD

**Issue by AiAnswer3213** [Atlantiss/NetherwingBugtracker#9127]
**Description**: 

https://www.wowhead.com/tbc/spell=698/ritual-of-summoning

Here's the ritual of summoning spell.
![summoning](https://github.com/Atlantiss/NetherwingBugtracker/assets/169561811/d13236c8-9643-4732-83ff-db6a14de9ec7)

It says it costs 300 mana. But when you cast it it reduces your mana by 600 instantly.
There's some weird behavior where you can cast it and it will reduce your mana after and decide you don't have enough mana anymore, so it breaks.

**Server Revision**: 
4006

**Comment by Wolffenstein** [comment]
Fixed in rev 4008.
