### ISSUE TITLE
Resilience % changed with 3.3.5 client (it's lower)

### ISSUE THREAD

**Issue by AcexHkx** [Atlantiss/NetherwingBugtracker#9129]
**Description**: 
Resilience on my shaman is less if I use the LK client

**Current behaviour**:
With TBC cliente resilience it's over 10%
With LK client resilience it's under 10%

**Expected behaviour**: 
Should not change

**Server Revision**: 
Netherwing
![image](https://github.com/Atlantiss/NetherwingBugtracker/assets/172915184/fb15b1db-d6bb-45dc-8418-3e814bbd50c5)
![image](https://github.com/Atlantiss/NetherwingBugtracker/assets/172915184/b62c48d1-4e38-4e4f-ba14-36e3561a65b9)

**Comment by Wolffenstein** [comment]
It's just a visual bug, the server uses the TBC percentage for calculations
