### ISSUE TITLE
[NPC] Don't remember the name but I got link

### ISSUE THREAD

**Issue by Kidcudi123** [Atlantiss/NetherwingBugtracker#913]
https://gyazo.com/36012fe9af562066176b854855d229dd

This NPC never resetted properly so I was stuck in combat forever and couldnt kill it either

**Comment by Easyfraggy** [comment]
Just a protip if you have win10 or osx you can screenshot directly to github, for win10 you simply hold win+shift+s and mark the area you want to SS and then ctrl+v into the text where you want to put it.

**Comment by xmesaj2** [comment]
killed it normally and can run away, was that something else maybe?

**Comment by Kidcudi123** [comment]
did I link the specific npc or just the mob name in general? Maybe I should've used .gps

**Comment by Easyfraggy** [comment]
Entry = mob type eg Skullsplitter Scout and ID is the specific spawn ID of the mob. So yes you linked the specific mob.

**Comment by The14me** [comment]
There are total 7 mob's with that ID.Killed all...never stuck in combat.If happen again or have more info please Re-open.
