### ISSUE TITLE
Guild bank remaining withdrawals shows wrong values

### ISSUE THREAD

**Issue by AiAnswer3213** [Atlantiss/NetherwingBugtracker#9132]
**Description**: 
We talked about this with someone on discord #tbc-support. 
For me the issue happens in first guild bank tab in one guild.
I can't replicate the issue in my other guild.
And for another person it happens on different tab.

**Current behaviour**:
When I deposit, move items or withdraw in guild bank tab 1, it changes the daily withdrawals counter to a wrong value.
Here's an example of when I have used up all the daily withdrawals, so **none** is the real value.

![none](https://github.com/Atlantiss/NetherwingBugtracker/assets/169561811/1cdd1a12-4223-46e0-933c-853dcd2462d8)

And now when I move one item in the gbank.

![6stacks](https://github.com/Atlantiss/NetherwingBugtracker/assets/169561811/28b22472-8076-4410-bb56-e8141056ab06)

It doesn't let me take any more items, and you can get it to show the true value again by switching to tab2 and back to tab1.

---------------------

The bug goes the other way also. When I have 25 withdrawals left and I move one items, it shows I have only 6 withdrawals left when I haven't made any.

---

I will comment if I find any patterns in this. Right now it seems to depend on the guild you're in.

**Server Revision**: 
4013
2.4.3 client
Disabled all addons for this test

**Comment by AiAnswer3213** [comment]
I looked up how the default UI works for this. You can find it here:
https://github.com/MOUZU/Blizzard-WoW-Interface/blob/d162a4c0d198a4381b5b6573d975635ed7316702/2.4.3/AddOns/Blizzard_GuildBankUI/Blizzard_GuildBankUI.lua#L120

I wrote this macro, which is how the default UI gets the number of remaining withdrawals from the wowapi.
`/run local name, icon, isViewable, canDeposit, numWithdrawals, remainingWithdrawals = GetGuildBankTabInfo(1); DEFAULT_CHAT_FRAME:AddMessage(remainingWithdrawals);`

This returns the wrong value, same as in the pictures.

Some kind of issue* with the `GetGuildBankTabInfo(tabNum);` ?

**Comment by Wolffenstein** [comment]
Fixed in rev 4014.
