### ISSUE TITLE
Druid Flight Form

### ISSUE THREAD

**Issue by ghost** [Atlantiss/NetherwingBugtracker#9135]
https://discord.com/channels/859389663957352468/1063133089657798730/1256581648980512850

https://wowpedia.fandom.com/wiki/Swift_Flight_Form?oldid=1617540
> This replaces your [[Flight Form]](https://wowpedia.fandom.com/wiki/Flight_Form) like Dire Bear replaces Bear; if you are in flight form when you hand in the [final quest](https://wowpedia.fandom.com/wiki/Quest:Vanquish_the_Raven_God), it is removed from you.

https://youtu.be/ZwQuUb29Ulg?feature=shared&t=977

**Comment by EtheriousNW** [comment]
Fixed in whatever the next revision will be
