### ISSUE TITLE
[NPC] Crag Boar - clipping

### ISSUE THREAD

**Issue by Mentat33** [Atlantiss/NetherwingBugtracker#914]
[//]: # (Enclose links to things related to the bug using http://wowhead.com or any other TBC database.)
[//]: # (You can use screenshot ingame to visual the issue.)
[//]: # (Write your tickets according to the format:)
[//]: # ([Quest][Azuremyst Isle] Red Snapper - Very Tasty!)
[//]: # ([NPC] Magistrix Erona)
[//]: # ([Spell][Mage] Fireball)
[//]: # ([Npc][Drop] Ghostclaw Lynx)
[//]: # ([Web] Armory doesnt work)

**Description**: Crag Boar is clipping into ground

**Current behaviour**: CLIP!
![crag boar clip](https://user-images.githubusercontent.com/43624877/46250119-fb01a300-c401-11e8-8dd1-5bf5b98e2c71.png)

**Expected behaviour**: NO CLIP!

**Server Revision**:

**Comment by aresbrutus** [comment]
Fixed in one of the upcoming updates.
