### ISSUE TITLE
Heroic Old Hillsbrad Foothills Thrall not Respawning After Dying

### ISSUE THREAD

**Issue by spacct** [Atlantiss/NetherwingBugtracker#9140]
[//]: # (Enclose links to things related to the bug using http://wowhead.com or any other TBC database.)
[//]: # (You can use screenshot ingame to visual the issue.)
[//]: # (Write your tickets according to the format:)
[//]: # ([Quest][Azuremyst Isle] Red Snapper - Very Tasty!)
[//]: # ([NPC] Magistrix Erona)
[//]: # ([Spell][Mage] Fireball)
[//]: # ([Npc][Drop] Ghostclaw Lynx)
[//]: # ([Web] Armory doesnt work)
[//]: # (To find server revision type `.server info` command in the game chat.)

**Description**: read the title

**Current behaviour**: read the title

**Expected behaviour**: Thrall should respawn. 2 days in a row and Thrall wont respawn after dying. Not sure wtf is wrong with this but waste hours in this place just to have Thrall not respawn on a wipe so whole group just has to sit around waiting for a GM before inevitably disbanding.

**Server Revision**:

**Comment by Godmatik** [comment]
If he dies 3 times in heroic then the run is over and he will not respawn - this is intended and is pre-nerf (on classic it did not exist)

**Comment by spacct** [comment]
Thrall died once and would not respawn

**Comment by Godmatik** [comment]
I can't reproduce it, killed Thrall on PTR and he respawned until his 3rd death.

Where did he die specifically?

**Comment by Godmatik** [comment]
Tested it again on PTR, he still is reviving for me

If it happens again, please let me know where it happens and I will try to reproduce.
