### ISSUE TITLE
KJ Breath Not Making Player Immune to Slow

### ISSUE THREAD

**Issue by spacct** [Atlantiss/NetherwingBugtracker#9145]
[//]: # (Enclose links to things related to the bug using http://wowhead.com or any other TBC database.)
[//]: # (You can use screenshot ingame to visual the issue.)
[//]: # (Write your tickets according to the format:)
[//]: # ([Quest][Azuremyst Isle] Red Snapper - Very Tasty!)
[//]: # ([NPC] Magistrix Erona)
[//]: # ([Spell][Mage] Fireball)
[//]: # ([Npc][Drop] Ghostclaw Lynx)
[//]: # ([Web] Armory doesnt work)
[//]: # (To find server revision type `.server info` command in the game chat.)

**Description**: KJ Breath Not Making Player Immune to Slow

**Current behaviour**: KJ Breath: Haste Not Making Player Immune to Slow. Flame Dart slow and Breath: Haste can exist simultaneously, but the slow of the Flame Dart prevails over the immunity.

**Expected behaviour**: 
![image](https://github.com/Atlantiss/NetherwingBugtracker/assets/104590778/848f88e9-8b43-4d29-9f63-4f1ff21ed1ad)

<img width="539" alt="image" src="https://github.com/Atlantiss/NetherwingBugtracker/assets/104590778/72195fff-3157-440b-a63a-6fed698368a6">

Even if Flame Dart debuff is on a player (with movement speed slow debuff), the immunity from KJ Breath: Haste should make the player immune to slow effects as well as increase their movement speed.

**Server Revision**:

**Comment by Godmatik** [comment]
You are only immune to the slow effect of the flame dart if you have the breath buff up BEFORE the application.

If you receive breath buff AFTER the application of flame dart, it will not remove that debuff. Only the shield will remove the debuff at the point (or something that removes movement impairing effects like freedom)

Classic video showing this - got flame dart debuff, received breath buff a few seconds after, still had flame dart.

https://www.youtube.com/watch?v=T--9fd0tNsk&t=450s

**Comment by spacct** [comment]
I didnt say it should remove the debuff. Read more carefully next time. I said it should make you immune. You should retain the debuff, but the immunity should last the duration of Breath: Haste.

The immunity prevents you from gaining a new debuff, but gaining the breath wont dispel an existing debuff. Even though the debuff still exists, the buff itself makes the player immune to slow effects, thus negating the effect of the debuff (while not removing it).

**Comment by Godmatik** [comment]
Yep my bad - reopening

**Comment by spacct** [comment]
Did some more research on this looking for similar effects that do not remove existing debuffs and you were right. Looks like the immunity only prevents new debuffs from being added and has no overwriting effect on existing debuffs. 

For comparison: Same as with Free Action potion. You gain immunity, but since it does not clear existing debuffs, you remain snared. And since Breath: Haste does not have a 'Remove Auras on Immunity' flag (like FAP), you remain snared even while you have the buff.
