### ISSUE TITLE
Kil'jaedan and Nether Protection

### ISSUE THREAD

**Issue by Godmatik** [Atlantiss/NetherwingBugtracker#9146]
Just see below clip.

Shadow bolts from the Shadow orbs is constantly proccing Nether Protection, making the warlock immortal in the KJ fight (until the images spawn to melee him).

Pretty sure Nether Protection needs some sort of internal cooldown to prevent this.

https://clips.twitch.tv/BeautifulUnusualCocoaDerp-SS_nCYdqovPaAiHu

**Comment by Godmatik** [comment]
Looking at classic logs closer - shield orb shadowbolt should not proc nether protection

**Comment by Wolffenstein** [comment]
Fixed
