### ISSUE TITLE
Guardian's Silk Footguards not giving 49 stam

### ISSUE THREAD

**Issue by hederob** [Atlantiss/NetherwingBugtracker#9147]
**Description**:  Guardian's Silk Footguards not giving 49 stam

**Current behaviour**: Guardian's Silk Footguards are giving 35 stam but displays as 49 on the item, but not in character pane. Tested with Shattrath Jumpers with 6 stam gem and no enchant, stam does not change. So either shattrath jumpers providing 43 stam or Pvp boots providing 35 stam

**Expected behaviour**:  Should give 49 stam. 

**Server Revision**:  1415

**Comment by Godmatik** [comment]
Resolved on discord - his meta socket was disabled
