### ISSUE TITLE
Warsong Outrider - Ashenvale

### ISSUE THREAD

**Issue by Mewmewww** [Atlantiss/NetherwingBugtracker#915]
[//]: # (Enclose links to things related to the bug using http://wowhead.com or any other TBC database.)
[//]: # (You can use screenshot ingame to visual the issue.)
[//]: # (Write your tickets according to the format:)
[//]: # ([Quest][Azuremyst Isle] Red Snapper - Very Tasty!)
[//]: # ([NPC] Magistrix Erona)
[//]: # ([Spell][Mage] Fireball)
[//]: # ([Npc][Drop] Ghostclaw Lynx)
[//]: # ([Web] Armory doesnt work)

**Description**: Non-walking/riding warsong outrider in ashenvale

**Current behaviour**: Standing still close to the road at azshara and forest song.

**Expected behaviour**: Should patrol, but doesn't. https://imgur.com/a/3hlZxuD

**Server Revision**: 2086 NW

**Comment by Mewmewww** [comment]
I didn't see anyone nearby, but this could possibly be the case

**Comment by The14me** [comment]
Work just fine now.Just as Easy say...when talk to her he stop for like a 5 min.

**Comment by CryingEnder** [comment]
Update, this is not fixed yet.
