### ISSUE TITLE
[Alliance] Druid ClassQuest  "Body and Heart" spawns the Mob twice

### ISSUE THREAD

**Issue by Crashdummyy** [Atlantiss/NetherwingBugtracker#9152]
[//]: # (Enclose links to things related to the bug using http://wowhead.com or any other TBC database.)
[//]: # (You can use screenshot ingame to visual the issue.)
[//]: # (Write your tickets according to the format:)
[//]: # ([Quest][Azuremyst Isle] Red Snapper - Very Tasty!)
[//]: # ([NPC] Magistrix Erona)
[//]: # ([Spell][Mage] Fireball)
[//]: # ([Npc][Drop] Ghostclaw Lynx)
[//]: # ([Web] Armory doesnt work)
[//]: # (To find server revision type `.server info` command in the game chat.)

**Description**: 
The Druid class quest [ Body and Heart](https://www.wowhead.com/classic/quest=6001/body-and-heart) to obtain the Bear form spawns the questmob twice upon using the [moondust](https://www.wowhead.com/classic/item=15208/cenarion-moondust)

**Current behaviour**:
The Quest mob [Lunaclaw] spawns twice.

**Expected behaviour**: 
Only one instance of the [Lunaclaw] object is generated

**Server Revision**: 
4016

[Lunaclaw]: https://www.wowhead.com/classic/npc=12138/lunaclaw

**Comment by Godmatik** [comment]
Fixed in Rev 4017
