### ISSUE TITLE
Deeprun Rat Roundup

### ISSUE THREAD

**Issue by Godmatik** [Atlantiss/NetherwingBugtracker#9161]
**Current behaviour**:
Charming the rats works fine, but you don't get quest completion when you bring them to Monty

**Expected behaviour**: 
Charming rats to Monty should give you quest credit

**Server Revision**: 
4020

https://www.wowhead.com/classic/quest=6661/deeprun-rat-roundup

**Comment by Godmatik** [comment]
Actually in classic - you get credit immediately for charming a rat, not when you turn them back in to Monty.

So, same should be done here.

**Comment by EtheriousNW** [comment]
looks like a wolf issue. woof

**Comment by Godmatik** [comment]
Fixed next server update =)
