### ISSUE TITLE
[Spell][Warrior] Spell reflecion doesn't give threat

### ISSUE THREAD

**Issue by VasiliyZalupin** [Atlantiss/NetherwingBugtracker#9163]
**Description**: Reflected with warrior's [Spell Reflection](https://www.wowhead.com/tbc/spell=23920/spell-reflection) spells don't give threat. 
Measured with Stormforge Threat meter addon.

**Server Revision**: 4020

**Comment by Godmatik** [comment]
Thanks for the report - it also wasn't showing the damage numbers properly above target (even though damage was dealt) - both are fixed on next server update
