### ISSUE TITLE
[Warrior] Weapon swap removes Shield Block and Shield Wall

### ISSUE THREAD

**Issue by VasiliyZalupin** [Atlantiss/NetherwingBugtracker#9164]
[//]: # (Enclose links to things related to the bug using http://wowhead.com or any other TBC database.)
[//]: # (You can use screenshot ingame to visual the issue.)
[//]: # (Write your tickets according to the format:)
[//]: # ([Quest][Azuremyst Isle] Red Snapper - Very Tasty!)
[//]: # ([NPC] Magistrix Erona)
[//]: # ([Spell][Mage] Fireball)
[//]: # ([Npc][Drop] Ghostclaw Lynx)
[//]: # ([Web] Armory doesnt work)
[//]: # (To find server revision type `.server info` command in the game chat.)

**Description**: 
swapping between one-handed weapons removes shield related buffs like [Shield Block](https://www.wowhead.com/tbc/spell=2565/shield-block) and [Shield Wall](https://www.wowhead.com/tbc/spell=871)

**Expected behaviour**: 
Swapping the one-handed weapon shouldn't affect shield related buffs unless the shield is being unequipped/swapped.

**Server Revision**: 
4020

**Comment by Godmatik** [comment]
Should be fixed with today's update.

**Comment by Godmatik** [comment]
Correction, not fixed in today's update, but will be in the next one
