### ISSUE TITLE
[NPC] Zul'Jin doesn't stop attack during the Lynx Rush

### ISSUE THREAD

**Issue by VasiliyZalupin** [Atlantiss/NetherwingBugtracker#9165]
[//]: # (Enclose links to things related to the bug using http://wowhead.com or any other TBC database.)
[//]: # (You can use screenshot ingame to visual the issue.)
[//]: # (Write your tickets according to the format:)
[//]: # ([Quest][Azuremyst Isle] Red Snapper - Very Tasty!)
[//]: # ([NPC] Magistrix Erona)
[//]: # ([Spell][Mage] Fireball)
[//]: # ([Npc][Drop] Ghostclaw Lynx)
[//]: # ([Web] Armory doesnt work)
[//]: # (To find server revision type `.server info` command in the game chat.)

**Description**: 
Zul'Jin doesn't stop his attack during the [Lynx Rush](https://www.wowhead.com/tbc/spell=43152/lynx-rush), leading to any less than mail+shield wearing raid members getting oneshotted.

**Expected behaviour**: 
As stated in the ability effects

Apply Aura: Mod Melee Attack Speed - %
Value: -6000%

Which should lead to essentially stopping regular attacks.

**Server Revision**: 
4020

**Comment by Godmatik** [comment]
Unable to reproduce. Zul'jin does not do any normal melee attacks during Lynx Rush.

Need to see proof or video and then I will re-open.

![lynxrush](https://github.com/user-attachments/assets/371b5229-fea3-41ff-8bac-cd8362650b66)

![2](https://github.com/user-attachments/assets/a1b94a24-346d-43eb-9cc6-9c349c64dcc1)

![3](https://github.com/user-attachments/assets/5e369241-1edf-4128-9c75-47bbc3854daa)
