### ISSUE TITLE
[Minor issue] Venture Co. Strip Miner - lvl. 40-41 - wrong spell + spell spam

### ISSUE THREAD

**Issue by XC-ahhaVA** [Atlantiss/NetherwingBugtracker#9167]
[//]: # (Enclose links to things related to the bug using http://wowhead.com or any other TBC database.)
https://www.wowhead.com/tbc/npc=674/venture-co-strip-miner#abilities

[//]: # (You can use screenshot ingame to visual the issue.)

https://ibb.co/wS4v10P

[//]: # ([NPC] Venture Co. Strip Miner)
[//]: # ([Spell][Paladin/Misc?] Devotion Aura)

**Description**: 
The npc is spamming the devotion aura on and off continuously.
According to wowhead he should not have that spell.

**Current behaviour**:
When in combat they just use it non stop and immediately turn it off.

**Expected behaviour**: 
According to wowhead they should throw dynamites instead.

**Server Revision**: 
Stormforge Netherwing | Content patch: 2.4.0 | Revision: 4021

**Comment by Godmatik** [comment]
It's the venture co foreman that has the devoution aura, which is intended.

But the aura flickering on and off constantly is a bug - looks like it occurs only when the foreman goes out of range of another goblin. I'm not even sure if his aura should be affecting anyone besides himself unless they are in combat with them?

https://www.wowhead.com/cata/npc=675/venture-co-foreman#abilities

**Comment by EtheriousNW** [comment]
Seems fine, it's flicking because the aura has a 30yd range and he patrols, some of them will often be in and out of that radius. It applies to the other goblins because they're the same faction, other mobs would not be affected. This also works as intended unless someone has other evidence.
