### ISSUE TITLE
Spellstealing Arcane Blast in MGT bugs cast speed

### ISSUE THREAD

**Issue by iDreamInBinary** [Atlantiss/NetherwingBugtracker#9168]
[//]: # (Enclose links to things related to the bug using http://wowhead.com or any other TBC database.)
[//]: # (You can use screenshot ingame to visual the issue.)
[//]: # (Write your tickets according to the format:)
[//]: # ([Quest][Azuremyst Isle] Red Snapper - Very Tasty!)
[//]: # ([NPC] Magistrix Erona)
[//]: # ([Spell][Mage] Fireball)
[//]: # ([Npc][Drop] Ghostclaw Lynx)
[//]: # ([Web] Armory doesnt work)
[//]: # (To find server revision type `.server info` command in the game chat.)

**Description**: Spellstealing the Arcane Blast buff from the mages in MGT will increase your cast speed after the buff wears off. Its fixed only after relogging and happens every time.

**Current behaviour**:
Cast speed is not properly reverted back to normal after the stolen arcane blast buff wears off, you can end up with a cast time of 5+ seconds for 1 blast.

**Expected behaviour**: Cast speed is reverted to the normal value after the buff wears off.

**Server Revision**: 
4021

**Comment by Godmatik** [comment]
Thanks for the report - fixed on next server update
