### ISSUE TITLE
Vanish didn't get me out of combat

### ISSUE THREAD

**Issue by Erodraeda** [Atlantiss/NetherwingBugtracker#917]
[//]: # (Enclose links to things related to the bug using http://wowhead.com or any other TBC database.)
[//]: # (You can use screenshot ingame to visual the issue.)
[//]: # (Write your tickets according to the format:)
[//]: # ([Quest][Azuremyst Isle] Red Snapper - Very Tasty!)
[//]: # ([NPC] Magistrix Erona)
[//]: # ([Spell][Mage] Fireball)
[//]: # ([Npc][Drop] Ghostclaw Lynx)
[//]: # ([Web] Armory doesnt work)

**Description**: 
I aggroed an extra mob, accidentaly. Because of that, I vanished, expecting to get out of combat. But what happened is that the mob reset to it's position, and would aggro and get out of me every second. The mob, this time, was 1059, 1.
**Current behaviour**:
https://clips.twitch.tv/ObeseFilthyPrariedogHeyGirl
**Expected behaviour**: 
Should just get out of combat, reset and go bag to it's patrolling.
**Server Revision**:

**Comment by Wolffenstein** [comment]
Fixed in rev 2090.
