### ISSUE TITLE
Prayer of mending aggro

### ISSUE THREAD

**Issue by Soulkreep** [Atlantiss/NetherwingBugtracker#9170]
[Spell][Priest] Prayer of Mending
https://www.wowhead.com/tbc/spell=33076/prayer-of-mending#comments

**Description**: 
Noticed yesterday when I was healing on my priest was casting prayer of mending on the tank before the pull tank would run in and as soon as the mobs hit him and prayer of mending proceed they would start running to me
**Current behaviour**:
Prayer of Mending aggro is given to the priest that initially cast it.
**Expected behaviour**: 
Aggro should be given to the target that was healed
**Server Revision**:

**Comment by Godmatik** [comment]
Thanks for the report - will be fixed tomorrow with next server update.
