### ISSUE TITLE
Trash mobs from Supremus spawn on Illidan after kill

### ISSUE THREAD

**Issue by erick289777** [Atlantiss/NetherwingBugtracker#9174]
https://github.com/user-attachments/assets/3e5504e3-51ad-44bf-b5de-0f2d2b2b2d14

[//]: # (Enclose links to things related to the bug using http://wowhead.com or any other TBC database.)
[//]: # (You can use screenshot ingame to visual the issue.)
[//]: # (Write your tickets according to the format:)
[//]: # ([Quest][Azuremyst Isle] Red Snapper - Very Tasty!)
[//]: # ([NPC] Magistrix Erona)
[//]: # ([Spell][Mage] Fireball)
[//]: # ([Npc][Drop] Ghostclaw Lynx)
[//]: # ([Web] Armory doesnt work)
[//]: # (To find server revision type `.server info` command in the game chat.)

Description:
After killing Illidan and attempting to loot him, trash mobs from the Supremus room spawned near Illidan’s corpse and started attacking us. One of the mobs was untargetable and continued attacking and chasing us even though the fight was over.

Current behaviour:
When Illidan is killed, trash mobs from the Supremus room unexpectedly spawn at his location. They attack the raid group, and one of the mobs was untargetable, but it was still able to deal damage and chase players.

Expected behaviour:
After Illidan is killed, no additional mobs should spawn at his location. Players should be able to loot Illidan without interference from any new enemies. All mobs should be targetable.

Server Revision:
4022

**Comment by Godmatik** [comment]
Do you have video available from just before the trash mobs appeared?

**Comment by erick289777** [comment]
@Godmatik Unfortunately no. I would have uploaded that one otherwise

**Comment by Godmatik** [comment]
Got it, we can't really determine why this happened or reproduce it - but we attached a debug log to these mobs so if it happens again it will give us exact data and on what is causing them to be pulled, so if you see it again please let us know!

**Comment by Godmatik** [comment]
Issue has been identified - will be fixed on next server update.
