### ISSUE TITLE
Feral powershifting

### ISSUE THREAD

**Issue by George-91** [Atlantiss/NetherwingBugtracker#9175]
**Description**:  powershifting macro for feral druids /cast !Cat Form stopped working correctly, most probably after the latest server-restart (Online for 10h47m58s), because it works perfectly till yesterday

**Current behaviour**: it won't show up back the "cat form hotbar" after re-casting the "/cast !Cat Form" .
![obrázek_2024-10-10_115609891](https://github.com/user-attachments/assets/9360cb40-6335-4074-a82e-af3283421549)

temp fix for this is only this macro:
/cancelaura Cat Form
/cast Cat Form

**Expected behaviour**:  /cast !Cat Form should recast the cat form when there is a mana and showup back the cat form hotbar aswell

**Server Revision**:  4022

**Comment by Godmatik** [comment]
Thanks for the report - we are aware of the issue and a fix is pending.

You will need to manually powershift for the moment until resolved.

**Comment by GraveofBears** [comment]
Thank you, this has been driving me crazy all morning

**Comment by Godmatik** [comment]
Server restarting in 25 minutes with fix

**Comment by George-91** [comment]
Thanks for the fix, now it works perfectly again after restart <3
