### ISSUE TITLE
Stormguard Cavalrymen - stuck?

### ISSUE THREAD

**Issue by Mewmewww** [Atlantiss/NetherwingBugtracker#918]
[//]: # (Enclose links to things related to the bug using http://wowhead.com or any other TBC database.)
[//]: # (You can use screenshot ingame to visual the issue.)
[//]: # (Write your tickets according to the format:)
[//]: # ([Quest][Azuremyst Isle] Red Snapper - Very Tasty!)
[//]: # ([NPC] Magistrix Erona)
[//]: # ([Spell][Mage] Fireball)
[//]: # ([Npc][Drop] Ghostclaw Lynx)
[//]: # ([Web] Armory doesnt work)

**Description**: Stromguard Cavalrymen not moving

**Current behaviour**: They're not moving.

**Expected behaviour**: They probably should be moving https://imgur.com/a/skB9u1O

**Server Revision**: 2086 NW

**Comment by The14me** [comment]
Work perfect now.After combat reset too.
