### ISSUE TITLE
[quest] creating the pendant - summoned mini-boss is friendly, not turning into humanoid

### ISSUE THREAD

**Issue by duzyizly** [Atlantiss/NetherwingBugtracker#9182]
**Description**: 
during quest https://www.wowhead.com/tbc/quest=10567/creating-the-pendant#comments
You are supposed to find 6 claws from nearby mobs and summon Harbinger of the Raven (first he is a raven then turns into a humanoid - that drops required quest item https://www.wowhead.com/tbc/item=30706/harbingers-pendant.)

**Current behaviour**:
He's not turning red or metamorhing, unable to attack. Quest can not be completed.
![WoWScrnShot_102424_143234](https://github.com/user-attachments/assets/39238962-31ea-47f6-8462-37773921ee86)

**How it should work*
https://www.youtube.com/watch?v=8SbWkGh_JVQ

**Server Revision**: 
PTR 4022

**Comment by Godmatik** [comment]
Fixed in Rev 4023
