### ISSUE TITLE
OHF - Thrall is stucked during weapon pick up phase

### ISSUE THREAD

**Issue by duzyizly** [Atlantiss/NetherwingBugtracker#9185]
![WoWScrnShot_110524_162209](https://github.com/user-attachments/assets/be4b5960-e17b-4d25-80ed-d45a2444685d)
![WoWScrnShot_110524_162510](https://github.com/user-attachments/assets/335bf4d2-ecde-403f-aab3-308c2b14ac90)

**Server Revision**: 
4023

**Comment by Godmatik** [comment]
Did you happen to kill the NPC inside that he is supposed to punch? I've done that before in my PTR tests by accident.

He will be stuck if that happens, need to .respawn him before the RP begins, and he should respawn automatically also if you wipe from thrall dying.

**Comment by duzyizly** [comment]
hmmm i need to recheck

**Comment by duzyizly** [comment]
Yeah, my bad
 I killed armorer by mistake
