### ISSUE TITLE
[Quest][Darkshore] Electropellers

### ISSUE THREAD

**Issue by Moistowelette** [Atlantiss/NetherwingBugtracker#919]
[//]: # (Enclose links to things related to the bug using http://wowhead.com or any other TBC database.)
[//]: # (You can use screenshot ingame to visual the issue.)
[//]: # (Write your tickets according to the format:)
[//]: # ([Quest][Azuremyst Isle] Red Snapper - Very Tasty!)
[//]: # ([NPC] Magistrix Erona)
[//]: # ([Spell][Mage] Fireball)
[//]: # ([Npc][Drop] Ghostclaw Lynx)
[//]: # ([Web] Armory doesnt work)

**Description**: 
In this quest you are supposed to fish for electropellers inland at this location:  
![wowscrnshot_092918_231222](https://user-images.githubusercontent.com/43673624/46250586-b8f65280-c43d-11e8-9120-d7ce8dd544c5.jpg) 
Electropellers in general do have a fairly low droprate, but after half an hour or so of fishing none of them dropped. Either the droprate is too low or they are currently not added to this part of the map

**Server Revision**: 
2086

**Comment by Wolffenstein** [comment]
Fixed in rev 2145.
