### ISSUE TITLE
Manaforge Duro - NPCs are not fighing against each other

### ISSUE THREAD

**Issue by duzyizly** [Atlantiss/NetherwingBugtracker#9198]
Blood elves in Manaforge Duro should be fighting against Nether Anomalies, they just stand with agressive pose.
Anyways, same happens to Sporeggar NPCs in Zangarmarsh (spawning glen and cave)

![WoWScrnShot_121724_125213](https://github.com/user-attachments/assets/702cdda9-49fe-4ecd-bd12-1e769a4d049b)

![WoWScrnShot_121724_125522](https://github.com/user-attachments/assets/c7e319ac-e7c9-4690-bfe6-098df18ceb7a)

**Server Revision**: 
4024

**Comment by Godmatik** [comment]
Duplicate 
https://github.com/Atlantiss/NetherwingBugtracker/issues/2662
