### ISSUE TITLE
[Pet] Surf Crawler Spells

### ISSUE THREAD

**Issue by DoctorRaymos** [Atlantiss/NetherwingBugtracker#92]
> Discord user Buskmurvel#2939

Reporting that his pet crab should have the ability to learn Claw by now, but has not.

Picture as reference: https://gyazo.com/3a639575577b5ffd30d0176e3684c512

**Comment by Wolffenstein** [comment]
Proof?

**Comment by DoctorRaymos** [comment]
Will this work? http://www.tentonhammer.com/guides/wow-hunter-guide-pet-skill-list-page-3

Ctrl+F - Claw

**Comment by DoctorRaymos** [comment]
Hmm looks like this can be closed, player reporting user error.
