### ISSUE TITLE
[Quest] King of the foulweald

### ISSUE THREAD

**Issue by Kidcudi123** [Atlantiss/NetherwingBugtracker#920]
You have to be level 60 to do this quest w/o dying

**Comment by DarthNekr0s** [comment]
can confirm, can't even kill the first furlbog that spawns without getting overrun by the rest of them

**Comment by BezawitNW** [comment]
Also another issue, which I think might/should be a bug since this is a group quest- only the person that initiates the quest can loot the totem from the final boss. Meaning you would have to repeat this event for every person in the party to get credit.

**Comment by BezawitNW** [comment]
Just re-did this quest and the timers + waves seem perfect compared to the retail video now. However one last possible issue is the last boss:

Chief Murgut

Drops an item on the ground (Murgut's Totem), which you have to loot to complete the quest. Only one person in the party can loot this, which I'm not sure is suppose to happen? So you would need to do this event multiple times in a party for each party member to pick the loot up.

**Comment by Shanghi** [comment]
The whole group and more (which is how it should be even if lazy non-grouped people didn't help) will be able to loot it in revision 2462. It sounds like the rest is ok now so I'll close this, but if the waves/timers are still messed up it can be reopened!
