### ISSUE TITLE
Trueshot Aura bugged

### ISSUE THREAD

**Issue by Kingofassassin** [Atlantiss/NetherwingBugtracker#9201]
i am lvl 64 and trueshot aura still not passive even a long time ago i unlocked this passive spell, and it should be everywhere even at solo or party friends

**Comment by Godmatik** [comment]
![trueshot](https://github.com/user-attachments/assets/8dbc61fc-caa1-4b3c-a053-7dc0605fd79d)

Works fine for me.

It's not passive, you must activate it.

Can you provide screenshot?

**Comment by Kingofassassin** [comment]
in Sheilun MoP Stormforge, But what i see you are in different private servers

in MoP the spells are learning for free

**Comment by Godmatik** [comment]
This is the TBC tracker, not MOP
