### ISSUE TITLE
[Quest][Thousand Needles] Hardened Shells low drop rate

### ISSUE THREAD

**Issue by totaemoeggerli** [Atlantiss/NetherwingBugtracker#921]
[//]: # (Enclose links to things related to the bug using http://wowhead.com or any other TBC database.)
[//]: # (You can use screenshot ingame to visual the issue.)
[//]: # (Write your tickets according to the format:)
[//]: # ([Quest][Azuremyst Isle] Red Snapper - Very Tasty!)
[//]: # ([NPC] Magistrix Erona)
[//]: # ([Spell][Mage] Fireball)
[//]: # ([Npc][Drop] Ghostclaw Lynx)
[//]: # ([Web] Armory doesnt work)

**Description**: 
drop chance for hardened shells seems too low
https://www.wowhead.com/quest=1105/hardened-shells

**Current behaviour**:
Can't say how many turtles I've killed to finish the quest. Had really bad luck early on but drop chance chance overall seems to be low. My guess is 20-25%.

**Expected behaviour**: 
This isn't the quest from the shimmering flats that players complain about traditionally.
This quest items drops alot better on other servers.

**Server Revision**: 2086

**Comment by aresbrutus** [comment]
Drop rates are corrected for blizzlike values and work right now.
