### ISSUE TITLE
Forsaken Bodyguard. [NPC]

### ISSUE THREAD

**Issue by Neophrone** [Atlantiss/NetherwingBugtracker#922]
[//]: # (Enclose links to things related to the bug using http://wowhead.com or any other TBC database.)
[//]: # (You can use screenshot ingame to visual the issue.)
[//]: # (Write your tickets according to the format:)
[//]: # ([Quest][Azuremyst Isle] Red Snapper - Very Tasty!)
[//]: # ([NPC] Magistrix Erona)
[//]: # ([Spell][Mage] Fireball)
[//]: # ([Npc][Drop] Ghostclaw Lynx)
[//]: # ([Web] Armory doesnt work)

**Description**: [Forsaken Bodyguard] can stack after they entered combat and then left it (watch video). Also if one Bodyguard is killed and the others left combat - dead Bodyguard will respawn instantly.

**Current behaviour**: [Forsaken Bodyguard] stack after leaving combat.

**Expected behaviour**: Should work as common mobs, dead bodyguard shouldn't respawn instantly.

**Server Revision**: 2086.
![bg](https://user-images.githubusercontent.com/43533040/46250913-b996e500-c44d-11e8-8c06-9660544f575f.gif)

**Comment by Tereneckla** [comment]
Fixed
