### ISSUE TITLE
[Quest] Cyclonian

### ISSUE THREAD

**Issue by manslaughter** [Atlantiss/NetherwingBugtracker#923]
**Description**: Famed quest for Warriors to get their whirlwind weapon post level 30.

**Current behaviour**:
1. Get quest "Hunt for Yenniku" from Grom'gol base camp.
2. Get quest "Cyclonian" from the Warrior level 30 quest chain.
3. Collect 30 Bloodscalp Tusks, 8 Liferoot, and create the Essence of the Exile.
4. You will not be able to complete Cyclonian despite having all the objectives completed.  Even vendoring the Liferoot and buying it back or relogging does not give quest completion.
5. If you abandon Hunt for Yenniku and get the tusks again, you are able to complete Cyclonian.

**Expected behaviour**: You can complete Cyclonian.

**Server Revision**: 2086

**Comment by Wolffenstein** [comment]
Fixed
