### ISSUE TITLE
[NPC] [Spell] Syndicate Sentry - Missing skills

### ISSUE THREAD

**Issue by Firroth** [Atlantiss/NetherwingBugtracker#924]
http://wowwiki.wikia.com/wiki/Syndicate_Sentry

[NPC] Syndicate Sentry https://classicdb.ch/?npc=2243#abilities
[Spell] Shield Wall https://classicdb.ch/?spell=15062, Shield Bash https://classicdb.ch/?spell=11972

**Current behaviour**:
Right now he has zero skills, does nothing except meele dmg.

**Expected behaviour**: 
Should shield bash player during casting any spell, and shield wall himself up when low on hp.

**Server Revision**: 
2086

**Comment by The14me** [comment]
Cant confirm,work great for me.

**Comment by Evolvee** [comment]
rev xdd

**Comment by UNB34TEN** [comment]
Shield bash CD is equal to its effect lengths (supposed to be 16-20 sec)

**Comment by Evolvee** [comment]
rev 2699
