### ISSUE TITLE
[NPC] [Behavior] Blackrock Ambusher 

### ISSUE THREAD

**Issue by GetoBoyz** [Atlantiss/NetherwingBugtracker#928]
[//]: # (Enclose links to things related to the bug using http://wowhead.com or any other TBC database.)
[//]: # (You can use screenshot ingame to visual the issue.)
[//]: # (Write your tickets according to the format:)
[//]: # ([Quest][Azuremyst Isle] Red Snapper - Very Tasty!)
[//]: # ([NPC] Magistrix Erona)
[//]: # ([Spell][Mage] Fireball)
[//]: # ([Npc][Drop] Ghostclaw Lynx)
[//]: # ([Web] Armory doesnt work)

**Description**: NPC Blackrock Ambusher [https://www.wowhead.com/npc=9522/blackrock-ambusher](url) in The Burning Steppes is incorrectly neutral.

**Current behaviour**: This NPC appears neutral while the other varieties of Blackrock orc nearby are hostile.

**Expected behaviour**:  I believe this NPC should be stealthed and aggressive.

**Server Revision**:

**Comment by The14me** [comment]
Please add some proof about that.

**Comment by aresbrutus** [comment]
http://wowwiki.wikia.com/wiki/Blackrock_Ambusher
https://www.wowhead.com/npc=9522/blackrock-ambusher#comments

**Comment by GetoBoyz** [comment]
To be completely honest, I can't remember if they should be stealthed or even aggressive. But it makes sense they would be.
![wowscrnshot_093018_104133](https://user-images.githubusercontent.com/43591086/46258762-eecb2380-c49d-11e8-9837-c33a32f85080.jpg)

Here's the rest of the Blackrock mobs for evidence sake.
![wowscrnshot_093018_104723](https://user-images.githubusercontent.com/43591086/46258811-3c479080-c49e-11e8-96b9-d74417fa33ea.jpg)
