### ISSUE TITLE
[NPC] [Quest] Courier Hammerfall - The Reason For the Season

### ISSUE THREAD

**Issue by Mentat33** [Atlantiss/NetherwingBugtracker#929]
[//]: # (Enclose links to things related to the bug using http://wowhead.com or any other TBC database.)
[//]: # (You can use screenshot ingame to visual the issue.)
[//]: # (Write your tickets according to the format:)
[//]: # ([Quest][Azuremyst Isle] Red Snapper - Very Tasty!)
[//]: # ([NPC] Magistrix Erona)
[//]: # ([Spell][Mage] Fireball)
[//]: # ([Npc][Drop] Ghostclaw Lynx)
[//]: # ([Web] Armory doesnt work)

**Description**: Courier Hammerfall (Entry: 10877, SpawnID - (Entry: 10877, Id:1) is giving out the quest "The Reason for the Season" which is a Feast of Winter Veil Quest

**Current behaviour**: Giving out quest at wrong time

**Expected behaviour**: Should only be handing out this quest during Feats of Winter Veil 

**Server Revision**:

**Comment by Shanghi** [comment]
This should be fixed in revision 2121.
