### ISSUE TITLE
[Uldaman][Archaedas] Had a stroke

### ISSUE THREAD

**Issue by Knoox** [Atlantiss/NetherwingBugtracker#930]
**Event didnt work, spammed worse than a chinese gold farmer. Didnt attack**: 

**Server Revision 2086
![wowscrnshot_093018_042656](https://user-images.githubusercontent.com/18479169/46252543-55364e80-c46a-11e8-8a20-451b1f0c4fca.jpg)
**:

**Comment by Easyfraggy** [comment]
Already known that this boss is stock.

**Comment by Wolffenstein** [comment]
Fixed in rev 2099.
