### ISSUE TITLE
[Uldaman][NPC] Unlinked

### ISSUE THREAD

**Issue by Knoox** [Atlantiss/NetherwingBugtracker#931]
**Unlinked earthen before last boss**: 

**Server Revision 2086
![wowscrnshot_093018_042443](https://user-images.githubusercontent.com/18479169/46252553-772fd100-c46a-11e8-903c-73787a3a006d.jpg)
**:

**Comment by Evolvee** [comment]
none of them are linked

its a pure chain pull...

they should all be linked?

**Comment by Evolvee** [comment]
Need info on the linking...

**Comment by Easyfraggy** [comment]
Yes they should all be linked

**Comment by Evolvee** [comment]
all like, dwarfs + statues and everything in the room?

**Comment by Evolvee** [comment]
![image](https://user-images.githubusercontent.com/1942409/46560171-061d6d00-c8f3-11e8-9596-f12501c4fb4f.png)
everything in here
or just the dwarfs

**Comment by Easyfraggy** [comment]
yep they are mostly nonelites

**Comment by Evolvee** [comment]
the stone reward is elite 🤕

**Comment by Evolvee** [comment]
linked in rev Xd
