### ISSUE TITLE
[Uldaman][Obsidian Sentinel] Dots works on a mechanical construct?

### ISSUE THREAD

**Issue by Knoox** [Atlantiss/NetherwingBugtracker#932]
**Read description**: 

**Server Revision 2086
![wowscrnshot_093018_032257](https://user-images.githubusercontent.com/18479169/46252566-9c244400-c46a-11e8-8008-b1c613a7e1e1.jpg)
**:

**Comment by The14me** [comment]
https://www.wowhead.com/npc=7023/obsidian-sentinel#comments:id=254599

**Comment by Easyfraggy** [comment]
> https://www.wowhead.com/npc=7023/obsidian-sentinel#comments:id=254599

I don't understand - what is it in that comment that you link it for?

**Comment by Tereneckla** [comment]
Fixed
