### ISSUE TITLE
[Uldaman][The Dwarfs] Unlinked

### ISSUE THREAD

**Issue by Knoox** [Atlantiss/NetherwingBugtracker#933]
**Olaf is the one we know 100% is unlinked, borderline impossible to test the other two**: 

**Server Revision 2086
![wowscrnshot_093018_031025](https://user-images.githubusercontent.com/18479169/46252595-0e952400-c46b-11e8-885e-bc8c66971677.jpg)
**:

**Comment by Evolvee** [comment]
rev 2538
