### ISSUE TITLE
[Professions] fishing bobber glitching

### ISSUE THREAD

**Issue by DarthNekr0s** [Atlantiss/NetherwingBugtracker#936]
**Description**:  fishing seems to glitch out occasionally (wasnt able to pinpoint what caused this) and the bobber stays behind in the water after your cast ends. the bobber still shakes about as if you were casting as well, and this behaviour seems to interrupt your current cast midway through. 
here is video of how it was acting: https://streamable.com/dm0tu

**Current behaviour**: bobber stays in the water and behaves like it's still being cast, interrupting your current cast

**Expected behaviour**:  bobber should always fade away after a failed fish attempt

**Server Revision**: 2086

**Comment by xmesaj2** [comment]
2128

**Comment by Kidtoucher** [comment]
the bobber is sometimes disappearing, making it impossible to click it and loot any fish.

**Comment by Kidtoucher** [comment]
its still happening, but not as frequently anymore.
