### ISSUE TITLE
Quest: Hunt for Yenniku / Cyclonian

### ISSUE THREAD

**Issue by kkumbaya** [Atlantiss/NetherwingBugtracker#937]
[//]: # (Enclose links to things related to the bug using http://wowhead.com or any other TBC database.)
[//]: # (You can use screenshot ingame to visual the issue.)
[//]: # (Write your tickets according to the format:)
[//]: # ([Quest][Azuremyst Isle] Red Snapper - Very Tasty!)
[//]: # ([NPC] Magistrix Erona)
[//]: # ([Spell][Mage] Fireball)
[//]: # ([Npc][Drop] Ghostclaw Lynx)
[//]: # ([Web] Armory doesnt work)

**Description**: Both mentioned quests require Bloodscalp tusks dropped by Bloodscalp trolls.

**Current behaviour**: Got 1 tusk in 15 kills. Possible connection with having both Cyclonian and Hunt for Yenniku quests active.

**Expected behaviour**: Classic.db shows 80% drop rate, I remember them dropping from almost every kill.

**Server Revision**: 2086

**Comment by The14me** [comment]
Related
https://github.com/Atlantiss/NetherwingBugtracker/issues/871
https://github.com/Atlantiss/NetherwingBugtracker/issues/923

**Comment by aresbrutus** [comment]
Classic DB is wrong, it is just stock values. If you want to show retail values you would have to archive for thottbot/allakhazam/wowhead. The drop rate has already been corrected to blizzlike values in the latest update.
