### ISSUE TITLE
[NPC] Wastewander Rogue

### ISSUE THREAD

**Issue by mbzz88** [Atlantiss/NetherwingBugtracker#938]
**Description**: NPC in stealth not hidden
http://db.hellfire-tbc.com/?npc=5615

**Current behaviour**:
![wowscrnshot_093018_191638](https://user-images.githubusercontent.com/43509267/46254057-cbc46200-c4e5-11e8-81e4-6fa84d11ff40.jpg)
Not all of the mobs are like this, stealth is working correctly on some
Casting Hunter's Mark on them, then removing it seems to fix it: https://youtu.be/4IxG_R22tL8
**Expected behaviour**: Only visible from short range

**Comment by The14me** [comment]
Confirm with shaman.
Rev: 2086

**Comment by Firroth** [comment]
This isn't the issue with only those. I've seen the same thing in Alterac Mountains on Syndicate Spy // Assassin's. They were in "prowl" but I could see them from 30y+. Arathi Highlands is the same in this regard in Stormgarde keep, mobs were 4-5lvls higher than me and still saw them from long distance in their stealth.

**Comment by Wolffenstein** [comment]
Fixed in rev 2095.
