### ISSUE TITLE
Rescue 00X-22/FE!

### ISSUE THREAD

**Issue by Piledriversn** [Atlantiss/NetherwingBugtracker#939]
![image](https://user-images.githubusercontent.com/43560552/46254178-a8030c80-c450-11e8-8ba5-e0c9de2d8471.png)
[//]: # ([Quest][Feralas] Rescue 00X-22/FE! )
[//]: # ([NPC] 00X-22/FE)(Robot Chicken)
**Current behaviour**:He doesn't aggro at all the mobs near him.

**Expected behaviour**: He should attack every hostile mob near him.

**Server Revision**:

**Comment by mbzz88** [comment]
Same issue with OOX-09/HL!.
Also the spawning mobs do not aggro onto the chicken, allowing you to skip the ambushes by staying out of aggro range

**Comment by Evolvee** [comment]
https://github.com/Atlantiss/AtlantissTbcBTOLD/issues/1178

**Comment by wowthings** [comment]
Weird, I just did that quest and he aggro the mobs near him, even the first wave, but doesn't attack if you aggroed first.
And was going to say that, thanks Evolve, the quest finishes too early.

**Comment by Evolvee** [comment]
Yea its a cata version of the quest. When I was scripting feralas Pegla linked me cata video of the escort and I though its legit TBC so... we have that for now, but I will rescript it dw :D

**Comment by Firroth** [comment]
On Rescue OOX-09/HL! in Hinterlands version, at least there spawn 1 ambush owlkin and later 1 ambush troll, when it should be 3 owlkins, and 3 trolls during entire quest.

**Comment by Azalen** [comment]
Did Feralas quest today; Two mobs spawned, I killed it, the quicken survived, moved 2y more then it was flying away without rewarding quest done. Super weird. Feralas btw

**Comment by Neophrone** [comment]
Did this quest few minutes ago. Chicken move the right path, but still, she didn't attack mobs, and mobs didn't attack her. Ambush appeared 2 times, both had only 1 mob spawned, should by 3. You can avoid every fight simply by avoiding aggro range of mobs or following chicken in stealth. Also a little cosmetic bug, in the end of escort ( shore of the Hinterlands for me) - chicken said about prepration to move to BB, after that she just disappeared, but it should fly away like a rocket. =)

**Comment by Evolvee** [comment]
its waiting for @Wolffenstein to implement assist react state

**Comment by KevinTyrrell** [comment]
Current behavior footage shown here:

https://clips.twitch.tv/UglyObliviousPizzaKevinTurtle

**Comment by Evolvee** [comment]
its nice right :D :D

**Comment by aresbrutus** [comment]
https://github.com/Atlantiss/NetherwingBugtracker/issues/3678
