### ISSUE TITLE
[Spell][Hunter] Concussive Shot

### ISSUE THREAD

**Issue by Thugli** [Atlantiss/NetherwingBugtracker#94]
**Description:**
Sometimes when I use concussive shot, the ability goes on CD but does not actually go off.
**Current behaviour**:
Occasionally concussive shot goes on CD but does not actually go off.
**Expected behaviour**: 
Concussive shot should always work
**Server Revision**:

**Comment by wtRCH** [comment]
Merged with https://github.com/Atlantiss/NetherwingBugtracker/issues/93
