### ISSUE TITLE
Rogue Spell, Distract radius

### ISSUE THREAD

**Issue by Erodraeda** [Atlantiss/NetherwingBugtracker#940]
[//]: # (Enclose links to things related to the bug using http://wowhead.com or any other TBC database.)
[//]: # (You can use screenshot ingame to visual the issue.)
[//]: # (Write your tickets according to the format:)
[//]: # ([Quest][Azuremyst Isle] Red Snapper - Very Tasty!)
[//]: # ([NPC] Magistrix Erona)
[//]: # ([Spell][Mage] Fireball)
[//]: # ([Npc][Drop] Ghostclaw Lynx)
[//]: # ([Web] Armory doesnt work)

**Description**: 
The radius of the spell seems to be a little bit under the green area that appears when you use it.
**Current behaviour**:
The effect applies on a radius lesser than the one that the spell should be
**Expected behaviour**: 
Apply the effect on the exact radius of the green area on the spell
**Server Revision**:

**Comment by Neophrone** [comment]
The radius of Distract is ok. The problem in mobs' hitboxes. Mob will not be affected by Distract, if green area didn't touch the center of mob's hitbox. I don't know it is normal, or it should work even if edge of hitbox was in area. (First video - small part of Distract area cover mob's hitbox and cover the center of hitbox - works fine. Second video - bigger part then first time of Distract area cover mob's hitbox but doesn't cover the center of hitbox - doesn't work.
![distract 1](https://user-images.githubusercontent.com/43533040/46255724-5e92db80-c4a9-11e8-864e-cc8be595e7e0.gif)
![distract 2](https://user-images.githubusercontent.com/43533040/46255754-f42e6b00-c4a9-11e8-95df-e95e8ad72cf7.gif)

**Comment by Erodraeda** [comment]
I had that problem, but the radius does, in fact, look lower than it should be, sometimes, even covering more of the hitbox

**Comment by Neophrone** [comment]
> I had that problem, but the radius does, in fact, look lower than it should be, sometimes, even covering more of the hitbox

Pretty sure radius is fine. If Distract doesn't affected the mob with fully covered hitbox - this mean that mob was in LOS.

**Comment by Easyfraggy** [comment]
The question is if distract should affect combat reach or only center of hitbox.

**Comment by SwiftieTBC** [comment]
https://youtu.be/-upbUldmt38?t=34s should effect from combat reach not center

**Comment by Easyfraggy** [comment]
So is this currently using combat reach or center of hitbox?
