### ISSUE TITLE
[NPC][Pathing]Jailor Marlgen#2428 Doesn't run away after netting you if his back is against the wall

### ISSUE THREAD

**Issue by Tenoutoften** [Atlantiss/NetherwingBugtracker#942]
**Description**: 
After Jailor Marlgen#2428(https://db.excalibur.ws/?npc=2428#abilities) nets#6533(https://db.excalibur.ws/?spell=6533) you, he wont run away if he has his back somewhat close to a wall(example: https://i.gyazo.com/86d1e916babe1acd5326e074eac3ba3b.png) in order to shoot#6600(https://db.excalibur.ws/?spell=6660) you. 

https://www.wowhead.com/npc=2428/jailor-marlgen#comments:id=90067  (Patch 2.1.0)
> Caution is to be taken when confronting this mob, he does not hit all that hard (30-ish on Leather) but will occasionally use a Net ability after which he will back out and use Ranged Attacks that hit for numbers in the upper thirties. When he backs away, it is likely he will pull more enemies which will probably slaughter you before you can close the gap between the Jailor and yourself as the Net wears off.
> 
> It is advised to clear any possible enemy he could pull onto you when he runs.

.npc info
https://i.gyazo.com/7fad927fb38cd43dfe660683e42b69c4.png

**Expected behaviour**: 
I'd expect he would be clever enough to kite to the sides

**Server Revision**: 
2086

**Comment by Tenoutoften** [comment]
I think the correct labels are movement rather than spell... there isn't anything wrong with his spells as far as I can tell, it's just that he wont kite if his back is somewhat close to a wall

**Comment by Easyfraggy** [comment]
I believe this is blizzlike, would need evidence that mobs should run away even though back is against a wall.

**Comment by Wolffenstein** [comment]
Where do you expect him to go though?

**Comment by Easyfraggy** [comment]
Need some pretty solid evidence of this behavior to do so. Reopen if you find some.
