### ISSUE TITLE
[Item] Spiked Collar

### ISSUE THREAD

**Issue by Mikik3jr** [Atlantiss/NetherwingBugtracker#943]
[//]: # (Enclose links to things related to the bug using http://wowhead.com or any other TBC database.)
[//]: # (You can use screenshot ingame to visual the issue.)
[//]: # (Write your tickets according to the format:)
[//]: # ([Quest][Azuremyst Isle] Red Snapper - Very Tasty!)
[//]: # ([NPC] Magistrix Erona)
[//]: # ([Spell][Mage] Fireball)
[//]: # ([Npc][Drop] Ghostclaw Lynx)
[//]: # ([Web] Armory doesnt work)

**Description**:
This item is dropped by this NPC: https://www.wowhead.com/npc=503/lord-malathrom 
![image](https://user-images.githubusercontent.com/43505031/46255236-08b73700-c49b-11e8-80be-1b27604c347d.png)

**Current behaviour**:
The felhunter that is summoned is really low on level. When I summoned it I pulled the entire room with it. It dealt only 1 dmg, and died after 2 hits:
![image](https://user-images.githubusercontent.com/43505031/46255230-ef15ef80-c49a-11e8-9a55-a82b90013793.png)
![image](https://user-images.githubusercontent.com/43505031/46255234-fb9a4800-c49a-11e8-8812-14d14ae64edd.png)

**Expected behaviour**: 
![image](https://user-images.githubusercontent.com/43505031/46255270-55027700-c49b-11e8-8d46-bd732ce68261.png)
According to wowhead comments it should be on higher level.
**Server Revision**: 
2086

**Comment by Evolvee** [comment]
rev xdd
