### ISSUE TITLE
[NPC][Spell] Drywhisker Kobold - Missing Skill

### ISSUE THREAD

**Issue by Firroth** [Atlantiss/NetherwingBugtracker#944]
[NPC] Drywhisker Kobold https://www.wowhead.com/npc=2572/drywhisker-kobold
[Spell] Strike https://www.wowhead.com/spell=11976/strike

**Current behaviour**:
Doesn't use any skills.

**Expected behaviour**: 
Should use [Spell] Strike https://www.wowhead.com/spell=11976/strike

**Server Revision**: 
2086

**Comment by The14me** [comment]
Not suppose to have it.If bring any proof,please re-open the issue.

**Comment by Easyfraggy** [comment]
![image](https://user-images.githubusercontent.com/36134067/46256991-d0bbee00-c4b2-11e8-9353-364cbe14be70.png)

Noabilities in bestiary
