### ISSUE TITLE
[NPC][Spell] Cresting Exile - Missing Frost Armor

### ISSUE THREAD

**Issue by Firroth** [Atlantiss/NetherwingBugtracker#946]
[NPC] Cresting Exile http://wowwiki.wikia.com/wiki/Cresting_Exile
[Spell] Frost Armor https://www.wowdb.com/spells/12544-frost-armor

**Current behaviour**:
Doesn't use Frost Armor. 

**Expected behaviour**: 
Should use Frost Armor, along with frost nova.

**Server Revision**: 
2086

**Comment by The14me** [comment]
Confirm,missing Frost Armor
https://www.wowhead.com/npc=2761/cresting-exile#comments:id=337241
Frost Armor ID: 12544

**Comment by Evolvee** [comment]
rev xdd
