### ISSUE TITLE
[Quest][Thousand Needles] Protect Kanati Greycloud

### ISSUE THREAD

**Issue by DeltaLoads** [Atlantiss/NetherwingBugtracker#947]
Quest - http://wowwiki.wikia.com/wiki/Quest%3AProtect_Kanati_Greycloud
**Description**: 
Quest Protect Kanati Greycloud is auto completed just by accepting it
**Current behaviour**:
Quest auto completes without doing anything
**Expected behaviour**: 
You should defend Kanati against 3 of centaurs
**Server Revision**: 
2086

**Comment by Jezofine** [comment]
Quest completed for me after killing 2/3 centaurs.

**Comment by Manaci** [comment]
Fixed
