### ISSUE TITLE
[NPC] Fozruk - missing elite status and increased hp (pre 2.3).

### ISSUE THREAD

**Issue by Firroth** [Atlantiss/NetherwingBugtracker#948]
[NPC] Fozruk http://wowwiki.wikia.com/wiki/Fozruk

**Current behaviour**:
Fozruk is not elite, and doesn't have higher hp pool.

**Expected behaviour**: 
Before patch 2.3 he had elite status, and higher hp pool.
http://wowwiki.wikia.com/wiki/Fozruk

![screenshot_2](https://user-images.githubusercontent.com/43505196/46256392-a9f9b980-c4aa-11e8-8167-4429c053c476.png)

**Server Revision**: 
2086

**Comment by The14me** [comment]
Leveling part(elite's etc) are 2.4.3
