### ISSUE TITLE
Rattlecage Skeletons Respawn

### ISSUE THREAD

**Issue by Zeref09731** [Atlantiss/NetherwingBugtracker#95]
[//]: # (Enclose links to things related to the bug using http://wowhead.com or any other TBC database.)
[//]: # (You can use screenshot ingame to visual the issue.)
[//]: # (Write your tickets according to the format:)
[//]: # ([Quest][Azuremyst Isle] Red Snapper - Very Tasty!)
[//]: # ([NPC] Magistrix Erona)
[//]: # ([Spell][Mage] Fireball)
[//]: # ([Npc][Drop] Ghostclaw Lynx)
[//]: # ([Web] Armory doesnt work)

**Description**: Rattlecage skeletons respawn was being reported as high within in-game chat shortly after launch.  Not sure if already addressed or confirmed, but thought I'd report it in case.
NPC - https://classicdb.ch/?npc=1890#drop

**Comment by Wolffenstein** [comment]
It should be much better after revision 2022.
