### ISSUE TITLE
[NPC] Marez Cowl

### ISSUE THREAD

**Issue by Firroth** [Atlantiss/NetherwingBugtracker#950]
[NPC] Marez Cowl https://wow.gamepedia.com/Marez_Cowl

**Current behaviour**:
1. Doesn't use Shadowbolt or corruption, as you can see on the screen from my combat log.
![screenshot_4](https://user-images.githubusercontent.com/43505196/46256543-7ae44780-c4ac-11e8-9dea-3af56c40babc.png)

2. Only spawns behind the house on lower level of Stormgarde Keep. (Killed her 4 times, and every time she spawns in the same place.)

**Expected behaviour**: 
1. Should use spell shadowbolt and corruption.  https://www.wowhead.com/spell=9613/shadow-bolt
https://www.youtube.com/watch?v=b_4gT97ah4E&feature=youtu.be&t=3m54s
https://www.youtube.com/watch?v=vXDdKwEODdc&feature=youtu.be&t=12s

2. Should spawn randomly in one of the two places.
![screenshot_2](https://user-images.githubusercontent.com/43505196/46256603-27262e00-c4ad-11e8-84e9-bbcd74263df7.png)

**Server Revision**: 
2086

**Comment by The14me** [comment]
Video's about the spell's are after TBC so its not a proof.
About spawn point's https://www.wowhead.com/npc=2783/marez-cowl#comments:id=112548:reply=25729 ,but still may be right.

**Comment by Evolvee** [comment]
rev xdd
