### ISSUE TITLE
[NPC][Arathi Highlands] Stormgarde Keep 

### ISSUE THREAD

**Issue by Firroth** [Atlantiss/NetherwingBugtracker#952]
**Current behaviour**:
Syndicate Magus are wrongly positioned, making this quest extremely hard if not impossible you are trying to solo it. You pull 2 bosses + 2 mages.

![screenshot_5](https://user-images.githubusercontent.com/43505196/46257334-1d55f800-c4b8-11e8-90ed-78ef845bfede.png)

**Expected behaviour**: 
Mobs should be positioned in a way, that you can clear everything without pulling boss pack.

Also in one of the rooms below, there is no NPC's, when there should be 2.

Positioning and missing mobs can be seen here:
https://www.youtube.com/watch?v=RxA-Jmc3Wf4

**Server Revision**: 
2086

**Comment by aresbrutus** [comment]
Fixed in one of the upcoming updates.
