### ISSUE TITLE
[Quest][Druid] Body and Heart

### ISSUE THREAD

**Issue by sifiuocz** [Atlantiss/NetherwingBugtracker#953]
quest - https://db.excalibur.ws/?quest=6002
**Description**: 
When the quest item is used (Cenarion Lunardust - https://db.excalibur.ws/?item=15710) there is a chance that the the NPC doesnt spawn (Summon Lunaclaw - https://db.excalibur.ws/?spell=19138).

**Current behaviour**:
The NPC can spawn but its not 100% probable. I needed to abandon and retake the quest.  I am not sure what is the cause of the bug. It may have been caused by me standing far away from the game object (Moonkin stone - https://db.excalibur.ws/?object=177525) where the quest item is used.

**Expected behaviour**: 
It should spawn the NPC every time

**Server Revision**: 
2086

**Comment by Omarthegreatone** [comment]
Was the spirit alredy up, from another druid trying to do it?

**Comment by sifiuocz** [comment]
I didnt see any spirits but i could be wrong.

**Comment by Tereneckla** [comment]
5 tries, 5 summons
