### ISSUE TITLE
[Quest] Zapped Giants

### ISSUE THREAD

**Issue by mbzz88** [Atlantiss/NetherwingBugtracker#954]
**Description**: Zorbin's Ultra-Shrinker http://db.hellfire-tbc.com/?item=18904 causes giants http://db.hellfire-tbc.com/?npc=5360 http://db.hellfire-tbc.com/?npc=5361 http://db.hellfire-tbc.com/?npc=5359 to have the level-up animation when shrunk. Animation does not occur 100% of the time.

**Current behaviour**: Level-up animation

**Expected behaviour**: No animation https://www.youtube.com/watch?v=wvq1kmg9LHE

**Server Revision**: 2086

**Comment by Evolvee** [comment]
https://github.com/Atlantiss/AtlantissTbcBTOLD/issues/1697

**Comment by Evolvee** [comment]
known issue with updating NPC template
