### ISSUE TITLE
[Quest][Drop][Ability] Satyr Slaying!

### ISSUE THREAD

**Issue by Unfairy** [Atlantiss/NetherwingBugtracker#955]
Bleakheart Hellcaller's summon {Imp or Voidwalker} not disappearing after his death.

Satyr Horns drop seems much lower than its suppsoed to be. (Around 90%)

**Comment by Jezofine** [comment]
[Satyr Horns](http://web.archive.org/web/20081015010802/http://thottbot.com:80/i5481), I'd say drop is a bit higher than it should on some satyrs.

**Comment by aresbrutus** [comment]
The drop rate of satyr horns has already been corrected so it should be good now.

**Comment by aresbrutus** [comment]
This was fixed already.
