### ISSUE TITLE
[Profession][Core]Fishing Pools.

### ISSUE THREAD

**Issue by Rickybobby90** [Atlantiss/NetherwingBugtracker#957]
[//]: # (Enclose links to things related to the bug using http://wowhead.com or any other TBC database.)
[//]: # (You can use screenshot ingame to visual the issue.)
[//]: # (Write your tickets according to the format:)
[//]: # ([Quest][Azuremyst Isle] Red Snapper - Very Tasty!)
[//]: # ([NPC] Magistrix Erona)
[//]: # ([Spell][Mage] Fireball)
[//]: # ([Npc][Drop] Ghostclaw Lynx)
[//]: # ([Web] Armory doesnt work)

**Description**: Fishing pools respawns are working incorrectly.

**Current behaviour**: Upon a pool being fished out, it despawns properly. However, when the pool respawns, you no longer receive items from the pool until the server is restarted.

**Expected behaviour**: When a pool respawns, you should be able to fish up new items relative to the pool.

**Server Revision**: 2094

**Comment by Leksa88** [comment]
To my understanding this is similar to how herbs and ore veins are bugged and are disabled because of that.

**Comment by Manaci** [comment]
Fixed
