### ISSUE TITLE
[Quest] Wandering Shay

### ISSUE THREAD

**Issue by mbzz88** [Atlantiss/NetherwingBugtracker#958]
**Description**: Quest does not work http://db.hellfire-tbc.com/?quest=2845

**Current behaviour**: NPC does not follow player, remains standing at start. Using quest item has no effect. http://db.hellfire-tbc.com/?item=9189

**Expected behaviour**: NPC should follow player

**Server Revision**: 2086

**Comment by Evolvee** [comment]
https://github.com/Atlantiss/AtlantissTBCBT/issues/1805

**Comment by Evolvee** [comment]
fixed in rev xdd
