### ISSUE TITLE
[Quest][Wetlands] A Grim Task

### ISSUE THREAD

**Issue by Needorfeed** [Atlantiss/NetherwingBugtracker#959]
**Description**: 
Balgaras, the quest-npc to kill, doesnt seem to spawn.

**Current behaviour**:
Nowhere to be found.

**Expected behaviour**: 
Should spawn in the south camp of the two southeast.

**Server Revision**:

**Comment by The14me** [comment]
Have 3 spawn point's.Check him this morning and was on the one of them.
https://www.wowhead.com/npc=1364/balgaras-the-foul#comments:id=24703:reply=2930
