### ISSUE TITLE
[Core][NPC] Mobs won't run around obstacles.

### ISSUE THREAD

**Issue by Silun** [Atlantiss/NetherwingBugtracker#96]
[//]: # (Enclose links to things related to the bug using http://wowhead.com or any other TBC database.)
[//]: # (You can use screenshot ingame to visual the issue.)
[//]: # (Write your tickets according to the format:)
[//]: # ([Quest][Azuremyst Isle] Red Snapper - Very Tasty!)
[//]: # ([NPC] Magistrix Erona)
[//]: # ([Spell][Mage] Fireball)
[//]: # ([Npc][Drop] Ghostclaw Lynx)
[//]: # ([Web] Armory doesnt work)

**Description**: Some(?) mobs won't run around obstacles, as exemplified by the Defias Thugs in the human starting area.

[Screenshots](https://imgur.com/a/PMmb3NH)

**Current behaviour**: Mobs will run through fences or over them, either climbing on top of them or just going straight through when they are chasing a player.

**Expected behaviour**: Mobs should run around obstacles such as fences.

**Comment by Wolffenstein** [comment]
It's blizzlike. On retail mobs can go through most fences like that.
