### ISSUE TITLE
[Quest][Core][Event][NPC] Stranglethorn Fishing Extravaganza

### ISSUE THREAD

**Issue by Rickybobby90** [Atlantiss/NetherwingBugtracker#960]
[//]: # (Enclose links to things related to the bug using http://wowhead.com or any other TBC database.)
[//]: # (You can use screenshot ingame to visual the issue.)
[//]: # (Write your tickets according to the format:)
[//]: # ([Quest][Azuremyst Isle] Red Snapper - Very Tasty!)
[//]: # ([NPC] Magistrix Erona)
[//]: # ([Spell][Mage] Fireball)
[//]: # ([Npc][Drop] Ghostclaw Lynx)
[//]: # ([Web] Armory doesnt work)

**Description**: Multiple issues regarding the event. Fishing pools should depawn on the coast lines of STV, and spawn only Speckled Tastyfish pools for the duration of the event.

**Current behavior**: At 14.00 server time, the event was not announced in STV by the event organizer. Fishing pools of all types still appearing during the event. The issue in my other fishing report are affecting Tastyfish pools also. Lastly, when the quest "Master Angler" is complete, the NPC Riggle Bassbait dies.

**Expected behavior**: Riggle Bassbait should announce the event withing STV at 14.00 server time. Only Speckled Tastyfish pools available on the coast of STV during the event time. Riggle Bassbait should walk away and despawn, allowing Jang, to receive fish from players for the repeatable.

**Server Revision**: 2094

**Comment by GerryBrown** [comment]
Does this being in a closed milestone mean that it is no longer on the todo list? This issue is still persisting today on server revision 3106

**Comment by Evolvee** [comment]
it is on todo list, its just not a priority

**Comment by Wolffenstein** [comment]
Fixed in rev 3787.
