### ISSUE TITLE
[NPC][Drop][Wetlands] Crocolisks have wrong loot

### ISSUE THREAD

**Issue by scarabadookie** [Atlantiss/NetherwingBugtracker#961]
[//]: # (Enclose links to things related to the bug using http://wowhead.com or any other TBC database.)
[//]: # (You can use screenshot ingame to visual the issue.)
[//]: # (Write your tickets according to the format:)
[//]: # ([Quest][Azuremyst Isle] Red Snapper - Very Tasty!)
[//]: # ([NPC] Magistrix Erona)
[//]: # ([Spell][Mage] Fireball)
[//]: # ([Npc][Drop] Ghostclaw Lynx)
[//]: # ([Web] Armory doesnt work)

**Description**: 
Crocolisks in wetlands, especially 1417 Young Crocolisk drop things they shouldn't.

**Current behaviour**:
They are dropping Rough Crocolisk Scale, Crocolisk Meat and Partially Digested Meat in addition to their regular loot table.

**Expected behaviour**: 
They shouldn't drop any of the above, see [](url)https://web.archive.org/web/20071206034939/http://thottbot.com:80/c1417 

**Server Revision**: 
2086

**Comment by Shanghi** [comment]
This should be fixed in revision 2152.
