### ISSUE TITLE
Rogue Gouge spell 

### ISSUE THREAD

**Issue by DemonHunter1992** [Atlantiss/NetherwingBugtracker#962]
[//]: # (Enclose links to things related to the bug using http://wowhead.com or any other TBC database.)
[//]: # (You can use screenshot ingame to visual the issue.)
[//]: # (Write your tickets according to the format:)
[//]: # ([Quest][Azuremyst Isle] Red Snapper - Very Tasty!)
[//]: # ([NPC] Magistrix Erona)
[//]: # ([Spell][Mage] Fireball)
[//]: # ([Npc][Drop] Ghostclaw Lynx)
[//]: # ([Web] Armory doesnt work)

**Description**: When i cast Gouge, when the effect finish i get hit by a mob one more time even if i am far away.

**Current behaviour**: mob hit me after gouge even if i am 20 yards away

**Expected behaviour**: mob start running to me without hitting me 

**Server Revision**: 2086

**Comment by Wolffenstein** [comment]
Could you record this happening? I would be very grateful

**Comment by DemonHunter1992** [comment]
ill try i need to download obs

**Comment by Easyfraggy** [comment]
You can also get https://getsharex.com/ to record and upload gifs easily to gfycat.

**Comment by DemonHunter1992** [comment]
[2018-10-01 22-24-10.zip](https://github.com/Atlantiss/NetherwingBugtracker/files/2435520/2018-10-01.22-24-10.zip)

**Comment by DemonHunter1992** [comment]
maybe it's X-Perl bug , clearly shows 44 white dmg on portrait, but now i saw the actual hp not going down, idk

**Comment by Easyfraggy** [comment]
Okay so what happens is a client bug that melee damage isn't shown in scrolling combat text instantly sometimes. This is client issue and cannot be fixed. The damage you took was before the gouge.
