### ISSUE TITLE
[Dungeon][Blackfathom Deeps] Azshara event + Altar of the Deeps bug

### ISSUE THREAD

**Issue by Unfairy** [Atlantiss/NetherwingBugtracker#965]
There is inproper amount of adds summoned in the end of the dungeon near Azshara statue.
There is suppsoed to be:
4 turtles
4 crabs
2 elementals
and about 8 non-elite humanoid crabs
reference: 
https://youtu.be/Ss0pKe6Q2JY?t=337

Also. The Altar of the Deeps in the end of the dungeon got locked for us after one party member used it so other party memebers wasnt able to get the buff.
![altar of the deeps _ locked](https://user-images.githubusercontent.com/41975070/46259381-01168300-c4d9-11e8-891c-65561c2e5bb3.jpg)

**Comment by Tereneckla** [comment]
Fixed
