### ISSUE TITLE
[Core][major cities]Undercity Elevators are broken and gone.

### ISSUE THREAD

**Issue by queeb3** [Atlantiss/NetherwingBugtracker#966]
[//]: # (Enclose links to things related to the bug using http://wowhead.com or any other TBC database.)
[//]: # (You can use screenshot ingame to visual the issue.)
[//]: # (Write your tickets according to the format:)
[//]: # ([Quest][Azuremyst Isle] Red Snapper - Very Tasty!)
[//]: # ([NPC] Magistrix Erona)
[//]: # ([Spell][Mage] Fireball)
[//]: # ([Npc][Drop] Ghostclaw Lynx)
[//]: # ([Web] Armory doesnt work)

**Description**: 
well, the elevator is missing and all sides
**Current behaviour**:
no elevator
**Expected behaviour**: 
need the up and down ride back
**Server Revision**:

**Comment by The14me** [comment]
They are here for me https://imgur.com/a/CzOksuT

**Comment by queeb3** [comment]
> They are here for me https://imgur.com/a/CzOksuT

ah i just relogged and now im underneath it lol

**Comment by queeb3** [comment]
wierd how i could not see them at all though

**Comment by The14me** [comment]
closed then : )
