### ISSUE TITLE
[Quest][Darkshore] Journey to Astranaar

### ISSUE THREAD

**Issue by Moistowelette** [Atlantiss/NetherwingBugtracker#967]
[//]: # (Enclose links to things related to the bug using http://wowhead.com or any other TBC database.)
[//]: # (You can use screenshot ingame to visual the issue.)
[//]: # (Write your tickets according to the format:)
[//]: # ([Quest][Azuremyst Isle] Red Snapper - Very Tasty!)
[//]: # ([NPC] Magistrix Erona)
[//]: # ([Spell][Mage] Fireball)
[//]: # ([Npc][Drop] Ghostclaw Lynx)
[//]: # ([Web] Armory doesnt work)

**Description**: 
Journey to astranaar requires you to travel to astranaar in Ashenvale.
**Current behaviour**:
  In it's current iteration Fiora Longears doesn't give the quest at the appropriate level.
**Expected behaviour**: 
The quest is listed at starting level 18 (https://db.excalibur.ws/?quest=1133) while I'm already level 20 it is still showing up as a grey quest.
**Server Revision**: 
2094

**Comment by Evolvee** [comment]
it has 18 level requirement in DB currently

**Comment by Shanghi** [comment]
The higher level quest you can't take is [Highperch Venom](https://www.wowhead.com/quest=1135/highperch-venom) (1135), which should be removed if we'll have the 2.3+ version of Fiora Longears.

If you couldn't get Journey to Astranaar at all, is it possible you did one of the quests Evolve listed? I was able to get it normally at level 18 just now.

**Comment by Moistowelette** [comment]
I had travel to Astranaar in my questlog at the time

**Comment by Shanghi** [comment]
This should be fixed in revision 2121.
