### ISSUE TITLE
"Tender" treants evade when you swim.

### ISSUE THREAD

**Issue by ircfelix** [Atlantiss/NetherwingBugtracker#969]
**Description**: 

**Current behaviour**:
"Tender" treants in the Blood Elf starting area evade if you swim in the pool next to https://tbc-twinhead.twinstar.cz/?object=180510 .

**Expected behaviour**: 
They shall follow and painfully crush thee.

**Server Revision**: 
2094

**Comment by Peglaa** [comment]
Probably just missing inhabit type for these specific NPCs. Did you notice this happening with any other NPCs? If not, post the ID of the specific NPC for which this happens.

**Comment by Tenoutoften** [comment]
Probably talking about these Tender#15271(https://db.excalibur.ws/?npc=15271)

**Comment by ircfelix** [comment]
I just checked it again: They only reset if you swim in the pool next to https://tbc-twinhead.twinstar.cz/?object=180510 (updated original report)

**Comment by Evolvee** [comment]
are we sure they should be able to swim?

**Comment by Wolffenstein** [comment]
I'm pretty sure they should, but pathing is bugged there for some reason

**Comment by ircfelix** [comment]
In the sea west of the area they do swim.

**Comment by ircfelix** [comment]
Maybe the water at that place is too deep?

**Comment by duzyizly** [comment]
still a thing as 20.06.2020
ptr rev 3392
both feral tenders and tenders stuck once enter the pool (35:28 eversong woods).
but they can swim in the sea (next to the pool).

![WoWScrnShot_062020_120238](https://user-images.githubusercontent.com/43931626/85199287-b3662d80-b2ee-11ea-9773-3202109197c3.jpg)
![WoWScrnShot_062020_120300](https://user-images.githubusercontent.com/43931626/85199288-b4975a80-b2ee-11ea-88b6-b30f737c3311.jpg)
![WoWScrnShot_062020_120425](https://user-images.githubusercontent.com/43931626/85199289-b52ff100-b2ee-11ea-8f3e-081278c7dd16.jpg)
![WoWScrnShot_062020_120446](https://user-images.githubusercontent.com/43931626/85199290-b52ff100-b2ee-11ea-844f-e3cbdd97116c.jpg)
![WoWScrnShot_062020_120540](https://user-images.githubusercontent.com/43931626/85199291-b5c88780-b2ee-11ea-8a5e-33bcb60d07c9.jpg)
![WoWScrnShot_062020_120542](https://user-images.githubusercontent.com/43931626/85199292-b6611e00-b2ee-11ea-9011-6a75bd9afba1.jpg)
![WoWScrnShot_062020_120649](https://user-images.githubusercontent.com/43931626/85199293-b6611e00-b2ee-11ea-9f31-1ba0a85a44e3.jpg)
![WoWScrnShot_062020_120652](https://user-images.githubusercontent.com/43931626/85199295-b6f9b480-b2ee-11ea-81d7-eaab16ae3f81.jpg)









![WoWScrnShot_062020_120238](https://user-images.githubusercontent.com/43931626/85199264-7732cd00-b2ee-11ea-87d6-121d8044ed32.jpg)
![WoWScrnShot_062020_120300](https://user-images.githubusercontent.com/43931626/85199265-7863fa00-b2ee-11ea-8e63-bbe89a20adcb.jpg)
![WoWScrnShot_062020_120425](https://user-images.githubusercontent.com/43931626/85199266-78fc9080-b2ee-11ea-94fb-7eb75db11bb9.jpg)
![WoWScrnShot_062020_120446](https://user-images.githubusercontent.com/43931626/85199267-79952700-b2ee-11ea-8afa-5d79e0a14730.jpg)
![WoWScrnShot_062020_120540](https://user-images.githubusercontent.com/43931626/85199268-79952700-b2ee-11ea-8540-26b4a95c65b7.jpg)
![WoWScrnShot_062020_120542](https://user-images.githubusercontent.com/43931626/85199269-7a2dbd80-b2ee-11ea-992b-ae9f3ec0de9f.jpg)

**Comment by Wolffenstein** [comment]
Fixed in rev 3393.
