### ISSUE TITLE
[Other] Rested XP on portrait

### ISSUE THREAD

**Issue by leon12345** [Atlantiss/NetherwingBugtracker#97]
[//]: # (Enclose links to things related to the bug using http://wowhead.com or any other TBC database.)
[//]: # (You can use screenshot ingame to visual the issue.)
[//]: # (Write your tickets according to the format:)
[//]: # ([Quest][Azuremyst Isle] Red Snapper - Very Tasty!)
[//]: # ([NPC] Magistrix Erona)
[//]: # ([Spell][Mage] Fireball)
[//]: # ([Npc][Drop] Ghostclaw Lynx)
[//]: # ([Web] Armory doesnt work)

Description: Describe the problem
rested xp shows as being rested even when you walk out the inn (on your portrait)
Current behaviour: What happens
https://gyazo.com/7513d834d0af764eeb83a0deb6eb204b
top left: portrait shows I am getting rested xp, this persists however long I wait outside of the inn or how far I run. relogging fixes this.

Expected behaviour: What should happen instead
once you walk out of an inn's rested zone your portrait should no longer show you are being rested
Steps to reproduce the problem:

go to Blood Watch on Azuremyst Isle
walk into the building with the npc Caregiver Topher Loaal in it, observe your portrait before and during walking into this building
walk out of the building and observe your portrait
Revision: Current server version (you can see current server revision by typing ".server info" command in the game chat) 2019

note: I have not confirmed whether or not I am still gaining rested XP while my portrait shows it but I am outside of the inn, I can log out instantly even outside of the inn while the bug is active.

**Comment by Peglaa** [comment]
Can confirm. This has been an issue for a long time now. The rested buff will only disappear if you relog or if you enter a new area of the zone. Think its only visual but not sure.

**Comment by toto6** [comment]
Fixed in Server Revision 2032
