### ISSUE TITLE
Resuce 00x-09/HL!

### ISSUE THREAD

**Issue by Piledriversn** [Atlantiss/NetherwingBugtracker#970]
![image](https://user-images.githubusercontent.com/43560552/46260309-d2cd7f00-c4a9-11e8-9107-bb3b8ff327ba.png)

[//]: # ([Quest][Hinterlands] Resuce 00x-09/HL!)
[//]: # ([NPC] 00x-09/HL)

**Current behaviour**: The robot chicken didn't attack anything. He didn't stop till we got to the coast. He did have the correct dialog when npc's were summoned during quest.

**Expected behaviour**: He should assist in combat.

**Server Revision**:

**Comment by Tenoutoften** [comment]
Homing Robot OOX-09/HL#7806(https://db.excalibur.ws/?npc=7806)
questID 836 https://db.excalibur.ws/?quest=836

**Comment by wtRCH** [comment]
Global (Core?) issue with all escort quest NPCS

**Comment by Jezofine** [comment]
{Tanaris chicken](https://www.wowhead.com/quest=648/rescue-oox-17-tn#comments) ddin't react to any roaming mobs or scripted ambushes, neither did spawned mobs attacked chicken.

**Comment by kudryashov-n** [comment]
Confirm chicken behavoiur. It doesn't attack anything while escorting, neither roaming mobs nor spawned mobs
![wowscrnshot_100618_115458](https://user-images.githubusercontent.com/43183825/46569685-1704c780-c961-11e8-94cd-95267ca7f54f.jpg)
![wowscrnshot_100618_115620](https://user-images.githubusercontent.com/43183825/46569686-1704c780-c961-11e8-9599-130ad99be354.jpg)

**Comment by Hoidel** [comment]
At the moment, the chicken disappears when the first pack was encountered. Couldn't tape it though.

**Comment by Hoidel** [comment]
Tried it again. The chick doesnt respond to attackers as reported before, but it disappears when it goes about 25-30 yards from you. When it despawns, the quest isn't failed, but the chick respawns at it's original location.

**Comment by aresbrutus** [comment]
https://github.com/Atlantiss/NetherwingBugtracker/issues/3678
