### ISSUE TITLE
[NPC]Farmer Getz#2403 missing alternative spawning positions

### ISSUE THREAD

**Issue by Tenoutoften** [Atlantiss/NetherwingBugtracker#971]
**Description**: 
Farmget Getz#2403(https://db.excalibur.ws/?npc=2403) missing two alternative spawn positions indicated by wowhead comments below. I killed him 6 times and he kept spawning in the small house.

https://www.wowhead.com/quest=527/deprecated-battle-of-hillsbrad#comments:id=61747 (Patch 2.0.12)

>  I found Getz in a house right next to the cow barn (somewhat northish) at 36,39. So far from my reading, he's either:
> - In the field near that loc
> - In the cow barn near that loc
> - In the house near that loc

https://www.wowhead.com/quest=527/deprecated-battle-of-hillsbrad#comments:id=53940 (Patch 2.0.10)

> Seems Farmer Getz got several spawn points. I remember from the first character I leveled I found him in the middle of the field as mentioned above, however, this time he was standing in the little house east of the field (around 36,40).

https://www.wowhead.com/quest=527/deprecated-battle-of-hillsbrad#comments:id=200947 (Patch 2.3.0)

> Getz does not just spawn in the barn. i sat n WATCHED him spawn in the middle of the field. So take ur pick. and be watchful.

https://www.wowhead.com/npc=2403/farmer-getz#comments:id=46808 (Patch 2.0.10)
> Found him in the **barn(35, 37)** and in the small house east of there(36, 39)

**Current behaviour**:
Farmer Getz#2403(https://db.excalibur.ws/?npc=2403) is currently only spawning in the small house (36.8, 39.3)

**Expected behaviour**: 
Expecting these 3 different spawn positions:
**Barn(35, 37)** (https://www.wowhead.com/npc=2403/farmer-getz#comments:id=46808 (Patch 2.0.10))

**Small house(36.8, 39.3)**(https://www.wowhead.com/npc=2403/farmer-getz#comments:id=46808 (Patch 2.0.10))

**Middle of the field(34.4, 40.7) Guessing coords for this one, but I think it is fair to assume it is this field rather than the others.

**Server Revision**: 
2094

**Comment by aresbrutus** [comment]
Fixed in one of the upcoming updates.
