### ISSUE TITLE
[Movement] Jumping + delayed S

### ISSUE THREAD

**Issue by Kidcudi123** [Atlantiss/NetherwingBugtracker#972]
If you jump and then press S delayed you make mobs not hit you (melee ofc)

**Comment by Easyfraggy** [comment]
Gonna need a video of this https://getsharex.com/ if you dont have recording software.

**Comment by Easyfraggy** [comment]
https://github.com/Atlantiss/NetherwingBugtracker/issues/1037 same issue but with gifs!

**Comment by wtRCH** [comment]
GIFs from #1037 by @unfairy
![image](https://user-images.githubusercontent.com/11255782/46309334-5d9e9e80-c5bc-11e8-99e4-0c4e51f8cda2.png)
![image](https://user-images.githubusercontent.com/11255782/46309339-60998f00-c5bc-11e8-9770-7a0f4d1e86f1.png)

**Comment by Wolffenstein** [comment]
Fixed in rev 2109.
