### ISSUE TITLE
[NPC]Farmer Ray#232 Missing alternative spawn spot

### ISSUE THREAD

**Issue by Tenoutoften** [Atlantiss/NetherwingBugtracker#974]
**Description**: 
Farmer Ray#232(https://db.excalibur.ws/?npc=232) missing alternative spawn spot, currently only spawns on the second level in the house at 33.25, 34.73

https://www.wowhead.com/npc=232/farmer-ray#comments:id=237507 (Patch 2.3.3)
> He spawns outside the house aswell

https://www.wowhead.com/quest=527/deprecated-battle-of-hillsbrad#comments:id=61747 (Patch 2.0.12)
> Farmer Ray I found in the doorway of the house where you give Stanley the Elixer of whatever.

https://www.wowhead.com/quest=527/deprecated-battle-of-hillsbrad#comments:id=138004 (Patch 2.1.3)
> Farmer Ray is outside a barn, next to a dog/wolf named "Stanley"

https://www.wowhead.com/quest=527/deprecated-battle-of-hillsbrad#comments:id=213232 (Patch 2.3.0)
> Don't remember where I found Farmer Ray, but I do know he was not in a house.

**Current behaviour**:
Only spawns on the second level in the house at 33.25, 34.73

**Expected behaviour**: 
Expected to be able to spawn just outside the house as well as the second floor that he currently spawns at: https://i.gyazo.com/0c1eb33d5a8b5b57c9080d1de7126f8f.jpg did .gps at this position, 32.88, 35.34

**Server Revision**: 
2094

**Comment by aresbrutus** [comment]
Fixed in one of the upcoming updates.
