### ISSUE TITLE
[NPC] [Razonfen Kraul] Agathelos the Raging

### ISSUE THREAD

**Issue by Arnamik12** [Atlantiss/NetherwingBugtracker#975]
**Current behaviour**:
Agathelos the Raging 4422 just stands around when the shield goes down patrolling back and forth

**Expected behaviour**: 
He should charge at you from the back when you run into his area
https://youtu.be/mnJu0UYaflo?t=241

**Server Revision**: 
2094

**Comment by Evolvee** [comment]
rev xdd
