### ISSUE TITLE
[NPC][Loot]Hillsbrad Apprentice Blacksmith#2265 too low weapon drop rate

### ISSUE THREAD

**Issue by Tenoutoften** [Atlantiss/NetherwingBugtracker#978]
**Description**: 
[Hillsbrad Apprentice Blacksmith#2265](https://db.excalibur.ws/?npc=2265) is suppose to frequently drop items that [he sells:](https://db.excalibur.ws/?npc=2265#sells)

[Cudgel#2492](https://db.excalibur.ws/?item=2492)
[Gladius#2488](https://db.excalibur.ws/?item=2488)
[Large Axe#2491](https://db.excalibur.ws/?item=2491)
[Stiletto#2494](https://db.excalibur.ws/?item=2494)
[Tomahawk#2490](https://db.excalibur.ws/?item=2490)
[Two-handed Sword#2489](https://db.excalibur.ws/?item=2489)
[Walking Stick#2495](https://db.excalibur.ws/?item=2495)
[Wooden Mallet#2493](https://db.excalibur.ws/?item=2493)

Based upon wowhead comments:
> [For Alliance characters, this vendor sells some of the fastest low-level weapons in the game. If you are looking to increase your weapon skill, be sure to visit him. - (Patch 3.0.1)](https://www.wowhead.com/npc=2265/hillsbrad-apprentice-blacksmith#comments:id=368282)

> [Interestingly enough, anything that he sells as a vendor he drops as loot. He's the only mob in the game that will drop such items. - (Patch 3.0.1)](https://www.wowhead.com/npc=2265/hillsbrad-apprentice-blacksmith#comments:id=397898)

I am not certain about the percentages. Killing [Hillsbrad Apprentice Blacksmith#2265](https://db.excalibur.ws/?npc=2265) on Lightbringer(over a year ago) could drop multiple weapons from a single NPC, looks like they researched this with archived Allakhazam database: Searched up  [Two-handed Sword#2489](https://db.excalibur.ws/?item=2489) which had [33.55%](https://web.archive.org/web/20050217222511/http://wow.allakhazam.com:80/item.html?witem=2489)

**Current behaviour**:
Quite rarely drops what he sells.

**Expected behaviour**: 
Expected to very frequently drop low quality weapons that he sells.

**Server Revision**: 
2094

**Comment by Easyfraggy** [comment]
Already reported here https://github.com/Atlantiss/NetherwingBugtracker/issues/580

**Comment by Tenoutoften** [comment]
I have linked to Allakazham archived

**Comment by aresbrutus** [comment]
Not good enough information.

Sometimes the stats are skewed like that. The item the guy sells never dropped in game, they are sell only items.

http://web.archive.org/web/20081017212713/http://thottbot.com:80/i2489
http://wowwiki.wikia.com/wiki/Two-handed_Sword

**Comment by Tenoutoften** [comment]
If the items never dropped in-game then they should be removed, because they currently drop.

**Comment by aresbrutus** [comment]
Fixed in one of the upcoming updates.
