### ISSUE TITLE
[NPC] Mottled Worg - Stuck In Tree

### ISSUE THREAD

**Issue by Ceago** [Atlantiss/NetherwingBugtracker#980]
**Description**:   Mottled Worg at The Dead Field in Silverpine stuck in tree.

**Current behaviour**:  In tree.  Evades when attacked.

**Expected behaviour**:  not in tree

**Server Revision**: 203
![wowscrnshot_093018_163831](https://user-images.githubusercontent.com/43499757/46262458-99a80580-c4cf-11e8-91a1-69170c86ef5d.jpg)

**Comment by aresbrutus** [comment]
Fixed in one of the upcoming updates.
