### ISSUE TITLE
[Spell][Druid] Maul when disarmed

### ISSUE THREAD

**Issue by sifiuocz** [Atlantiss/NetherwingBugtracker#981]
spell id: https://db.excalibur.ws/?spell=6807
**Description**: 
When disarmed and Shapeshifted to Bear form while maul is actived for the next swing it gets deactivated. Whenever Maul is pressed during the disarm duration it activates but doesnt go off on the next swing.

**Current behaviour**:

**Expected behaviour**: 

**Server Revision**: 
2094

**Comment by Easyfraggy** [comment]
I believe druids should be immune to disarm entirely while in shapeshift (except moonkin).

**Comment by Wolffenstein** [comment]
Fixed in rev 2140.
