### ISSUE TITLE
The Torch of Retribution

### ISSUE THREAD

**Issue by Thorgrimme** [Atlantiss/NetherwingBugtracker#982]
[//]: #https://classicdb.ch/?quest=3454
[//]: # (You can use screenshot ingame to visual the issue.)
[//]: # (Write your tickets according to the format:)
[//]: # ([Quest][The Torch of Retribution)
[//]: # ([NPC] Magistrix Erona)
[//]: # ([Spell][Mage] Fireball)
[//]: # ([Npc][Drop] Ghostclaw Lynx)
[//]: # ([Web] Armory doesnt work)

**Description**: The torch doesnt appear after Kalaran Windblade has made it, so you'r not able to turn in the quest and pick up the torch to continue the questline.

**Current behaviour**:

**Expected behaviour**: 

**Server Revision**:

**Comment by Thorgrimme** [comment]
It did appear after i dropped the quest, picked it up again and talked to the npc.

**Comment by zhuk90** [comment]
I confirm, the quest is not working: the torch does not appear next to the NPS

**Comment by Ofecks** [comment]
The torch object didn't spawn for me initially, but after I relogged it was there.

**Comment by Manaci** [comment]
Fixed
