### ISSUE TITLE
[Spell] Withering Poison

### ISSUE THREAD

**Issue by Kidcudi123** [Atlantiss/NetherwingBugtracker#984]
This NPC spell should not give me multiple debuffs but refresh it instead. Scorpid Reaver/Terror does it

**Comment by Kidcudi123** [comment]
Each has 3 min duration , each has -agi -str. If I were to farm scorpions I'd have 0 agi after im even half done lol surely Blizzard wasnt this harsh!

**Comment by SwiftieTBC** [comment]
https://www.wowhead.com/spell=13884/withering-poison#comments 
both comments imply that it does stack

**Comment by Kidcudi123** [comment]
oh damn

**Comment by Evolvee** [comment]
k that sums this report up xd
