### ISSUE TITLE
[Quest][Bloodmyst Isle] Constrictor Vines/The Bear Necessities drop rate low

### ISSUE THREAD

**Issue by anonyReporter** [Atlantiss/NetherwingBugtracker#985]
**Description**: 
Drop rate on constrictor vines and elder brown bear flanks is very low.
**Current behaviour**:
Drop rate is very low, killed 10 Elder Brown Bears and Mutated Constrictors with no quest item drops.
**Expected behaviour**: 
According to wowhead - 
- Elder Brown Bear Flank is a 48% drop rate
- Constrictor Vines is a 38% drop rate

NPC Bear info: Entry 17348 Id: 18
NPC Constrictor info: Entry 17344 Id: 13

**Server Revision**: 
2097

**Comment by Easyfraggy** [comment]
Wowhead is not a great source, use web archive from 2007/8 instead for example:

http://web.archive.org/web/20070513205555/http://www.thottbot.com:80/i23994

**Comment by aresbrutus** [comment]
Drop rates are correct.
