### ISSUE TITLE
[Quest] "The Missing Diplomat" Part 16-17.

### ISSUE THREAD

**Issue by Neophrone** [Atlantiss/NetherwingBugtracker#986]
[//]: # (Enclose links to things related to the bug using http://wowhead.com or any other TBC database.)
[//]: # (You can use screenshot ingame to visual the issue.)
[//]: # (Write your tickets according to the format:)
[//]: # ([Quest][Azuremyst Isle] Red Snapper - Very Tasty!)
[//]: # ([NPC] Magistrix Erona)
[//]: # ([Spell][Mage] Fireball)
[//]: # ([Npc][Drop] Ghostclaw Lynx)
[//]: # ([Web] Armory doesnt work)

**Description**: After completing the quest The Missing Diplomat part 16, Jaina, Archmage Tervosh and 1 more NPC appearing right near the place where you defeated Private Hendel (target of quest part 16), 
you can finish the quest ( Archmage Tervosh), and he should give you next part of this quest chain, but they are disappear before I took the next part of quest chain. After that I moved to Theramore, to Jaina's tower, I found her, Archmage Tervosh here. Above  Archmage Tervosh you can see exclamation point, but I can't take quest from him, and above Jaina you can see question mark, but I can't finish quest with her too. (Watch video).
**Current behaviour**: NPCs disappear to fast, not enough time to take next part. After that NPCs bugging, so you can't continue quest chain.

**Expected behaviour**: More times to take next quest. Even if NPCs disappear - they should give next part of quest chain in tower.

**Server Revision**: 2094.
![the missing diplomat](https://user-images.githubusercontent.com/43533040/46262733-18bc2e80-c50e-11e8-8d87-87b1424574f6.gif)

**Comment by Evolvee** [comment]
someone give me entries of quest related NPCs, especially quest giver where the quest is rewarded that launches this event

**Comment by Neophrone** [comment]
> someone give me entries of quest related NPCs, especially quest giver where the quest is rewarded that launches this event

Quest part #16 http://db.hellfire-tbc.com/?quest=1324. Start quest - [Private Hendel], end quest - [Archmage Tervosh]. When this quest is rewarded - event is starting. You can finish this quest, but can't take next.
Quest part#17 http://db.hellfire-tbc.com/?quest=1267. Start quest - [Archmage Tervosh], end quest - [Jaina Proudmoore]. This quest unable to take after event.

**Comment by tcberk12** [comment]
Archmage Tervosh just disappeared on me too.

I had just completed http://db.hellfire-tbc.com/?quest=1265 by speaking to him at Sentry Point, but he disappeared before I could accept http://db.hellfire-tbc.com/?quest=1266 

Got about halfway thru reading quest text before he disappeared.

**Comment by aresbrutus** [comment]
@Evolvee The issue that tcberk had is at Sentry point tower with the quest http://db.hellfire-tbc.com/?quest=1265

I guess it is just a matter of increasing the timer before he despawns there after he appears.

**Comment by Evolvee** [comment]
its 1 minute -.- how can u be so slow pepepains

**Comment by Evolvee** [comment]
I increased the timer on despawn in that Tower but, whats the first post in this bugreport about  @aresbrutus ?

**Comment by aresbrutus** [comment]
1 is Sentry point you fixed, the other is Jaina + others spawning at Private Hendel camp but IDK if their despawn is also fast or not. Last time I checked it was just fine. I don't expect people to go AFK right after defeating the guy anyway so yeah.

**Comment by Evolvee** [comment]
I just dont know what to do :D :D 

![image](https://user-images.githubusercontent.com/1942409/46879224-b801ef80-ce45-11e8-99c4-50523ad635f3.png)


lf for comment like this xd

**Comment by aresbrutus** [comment]
I will do the quests and comment here if something is wrong, else close it.

**Comment by aresbrutus** [comment]
I just did the quest and there are a few changes needed.

When you accept http://db.hellfire-tbc.com/?quest=1324 the guy and his bodyguards turn hostile. Once you defeat private Hendel, Jaina and co appear. 

1. But the 2 bodyguards running away should also say this when they start running away: `It's Proudmoore! Get out of here!` https://i.imgur.com/pnzx2s1.jpg

2. The archmage should cast the bubble on private hendel giving him stun emote and after a while he should disappear as if he is getting TPd to the tower. Can be seen here: https://youtu.be/6XeuwJnqSd4?t=481 and https://youtu.be/DjLvJElJP6U?t=63

3. This one is weird but, it seems that after rewarding http://db.hellfire-tbc.com/?quest=1324 the next quest should be given by Proudmore only http://db.hellfire-tbc.com/?quest=1267 The quest works as like those instant take and reward quests where you click accept and you get the q rewarded to you.

The quest text should be: 
```
Let me be first to thank you for all you've done, $n. You have been an incredible blessing to my people and the people of Stormwind. I am sorry I couldn't make your acquaintance under better circumstances.

Understand also that I cannot overtly thank you for your efforts, but I assure you again, it is appreciated.

When you visit Theramore in the future, seek me out and I shall try to keep you appraised of the situation.

Thank you again, $n.
```

Can be seen here: https://i.imgur.com/t4NPj38.png

**Comment by shuvit** [comment]
I'm having the exact same issue as shown in OPs gif as of 15.01.2019 after subduing Private Hendel.

**Comment by Bronag** [comment]
I have exactly the same issue as OP. We did the quest as a group, could not interact with NPCs while other group member was returning quest. When I finally managed to speak to NPC, he disappeared. Now bug situation is as in OPs video.
BTW, any chance ingame to continue the quest chain?

**Comment by Tereneckla** [comment]
If you fail to pickup [the quest#1267](https://wowwiki.fandom.com/wiki/Quest:The_Missing_Diplomat_(17)) immediately after turning in the previous part(by the npc next to Hendel despawning, you abandoning it or just pressing escape when you are offered it) you still can't take it again. And the situation as described by the OP occurs.

**Comment by UncleSweaty** [comment]
Exact same issue happened to my on Karazhan realm, 23/08. My friend tried the quest today while in the party with me and is also not able to continue with the quest.
Would there be any way to continue with this quest chain via a GM intervention or something?

**Comment by netbean2** [comment]
hello, even at revision 3606 this still happens.
Furthermore i cannot even see the UI window mentioned at ticket : https://github.com/Atlantiss/NetherwingBugtracker/issues/7311

**Comment by Godmatik** [comment]
Duplicate #7311
