### ISSUE TITLE
[Spell] [Druid] Mark of the Wild shows HP bug

### ISSUE THREAD

**Issue by Spaztick** [Atlantiss/NetherwingBugtracker#987]
**Description**: 
Any MotW that gives attributes (Rank 2 or over) will show a bugged HP bar.

**Current behaviour**:
Buffing with MotW Rank 2 or above shows an HP bar of something like 98/<max HP>. Health is not show to regenerate above 100; I suspect it's showing the percentage of health rather than absolute numbers and is purely a visual bug. It is not addon related as this was tested with several people with all addons disabled. Does not seem to affect NPCs.

**Expected behaviour**: 
Health bars not to show 100/<max HP> or something similar but instead keep a "nearly full" HP bar.

**Server Revision**: 
I dunno I'm a shitposter not a coder.

**Comment by Spaztick** [comment]
![motw](https://user-images.githubusercontent.com/29140342/46262770-74b19380-c4cb-11e8-82f2-87dc35a5df2b.jpg)

**Comment by Peglaa** [comment]
I think there is a simple solution to this. Instead of wasting time on fixing it, just remove %HP and use real numbers. (:

**Comment by Spaztick** [comment]
This is without %HP displayed, I always show raw numbers.

**Comment by totaemoeggerli** [comment]
I have the same [issue](https://gfycat.com/AcidicBoilingCommongonolek)
but this isn't restricted to druids: https://github.com/Atlantiss/NetherwingBugtracker/issues/175
-> duplicate

**Comment by Dosdaltherir** [comment]
I can concur that this problem persists.
Rev: 2169

**Comment by Wolffenstein** [comment]
Fixed in rev 2211.
