### ISSUE TITLE
[Quest][Stonetalon Mountains] Gerenzo's Orders

### ISSUE THREAD

**Issue by Sinyr** [Atlantiss/NetherwingBugtracker#988]
[//]: # (Enclose links to things related to the bug using http://wowhead.com or any other TBC database.)
[//]: # (You can use screenshot ingame to visual the issue.)
[//]: # (Write your tickets according to the format:)
[//]: # ([Quest][Azuremyst Isle] Red Snapper - Very Tasty!)
[//]: # ([NPC] Magistrix Erona)
[//]: # ([Spell][Mage] Fireball)
[//]: # ([Npc][Drop] Ghostclaw Lynx)
[//]: # ([Web] Armory doesnt work)

**Description**: 
I'm talking about this part of the chain: https://www.wowhead.com/quest=1090/gerenzos-orders

**Current behaviour**:
While in a party, when a player starts this quest, other players do get the prompt to accept it, but after the event finishes, only the player who started the quest gets quest credit.

**Expected behaviour**: 
All players in the party should get quest credit when the event completes.

**Server Revision**: 
2094

**Comment by Evolvee** [comment]
rev xdd
