### ISSUE TITLE
[NPC][SPELL] Bleeding Horror aura chance needs to be reduced.

### ISSUE THREAD

**Issue by aresbrutus** [Atlantiss/NetherwingBugtracker#99]
http://db.hellfire-tbc.com/?npc=1529

http://db.hellfire-tbc.com/?spell=3235

Chance of this seems to be high, should be set to 15%

rev: 2020

**Comment by xmesaj2** [comment]
Trigger spell (3322) Rancid Blood. Chance = 15

RNG?
