### ISSUE TITLE
[Quest] You are Rakh'likh, Demon teleporter

### ISSUE THREAD

**Issue by mbzz88** [Atlantiss/NetherwingBugtracker#991]
**Description**: Rune of the Defiler ports you without quest item. http://db.hellfire-tbc.com/?object=153204

**Current behaviour**: Standing on the portal rune without the quest item www.wowhead.com/item=10757/ward-of-the-defiler will port player to the top of the mountain

**Expected behaviour**: Teleport only works if player has Ward of the Defiler in inventory

**Server Revision**: 2094

**Comment by ttghnw** [comment]
I've seen this happen on vanilla private servers, you can use the port without having the q, not sure if it's blizzlike.

**Comment by Evolvee** [comment]
rev xdd
