### ISSUE TITLE
Noxious Lair Investigation

### ISSUE THREAD

**Issue by Thorgrimme** [Atlantiss/NetherwingBugtracker#992]
[//]: # https://classicdb.ch/?quest=82
[//]: # (You can use screenshot ingame to visual the issue.)
[//]: # (Write your tickets according to the format:)
[//]: # ([Quest]Noxious Lair Investigation)
[//]: # ([NPC] Magistrix Erona)
[//]: # ([Spell][Mage] Fireball)
[//]: # ([Npc][Drop] Centipaar Insect Parts)
[//]: # ([Web] Armory doesnt work)

**Description**: Very low drop rate, killed about 15-20 of the random mobs that should drop the quest item, with 0 items dropping. Should be close to 80 % drop rate according the the db i linked.

**Current behaviour**:

**Expected behaviour**: 

**Server Revision**:

**Comment by aresbrutus** [comment]
Fixed in one of the upcoming updates.
