### ISSUE TITLE
[Item] Thick Black Claw

### ISSUE THREAD

**Issue by mbzz88** [Atlantiss/NetherwingBugtracker#993]
**Description**: Thick Black Claw http://db.hellfire-tbc.com/?item=20611 is dropping for players not on the quest (shaman class quest)

**Current behaviour**: Dropping for players not on quest

**Expected behaviour**: Only drops for players doing Spirit Totem quest http://db.hellfire-tbc.com/?quest=8412

**Server Revision**: 2094

**Comment by Evolvee** [comment]
should be fixed in rev `xdd`
