### ISSUE TITLE
Can't switch trinkets that are "unique-equipped" from slot

### ISSUE THREAD

**Issue by Erodraeda** [Atlantiss/NetherwingBugtracker#994]
[//]: # (Enclose links to things related to the bug using http://wowhead.com or any other TBC database.)
[//]: # (You can use screenshot ingame to visual the issue.)
[//]: # (Write your tickets according to the format:)
[//]: # ([Quest][Azuremyst Isle] Red Snapper - Very Tasty!)
[//]: # ([NPC] Magistrix Erona)
[//]: # ([Spell][Mage] Fireball)
[//]: # ([Npc][Drop] Ghostclaw Lynx)
[//]: # ([Web] Armory doesnt work)

**Description**: 
I couldn't move the trinket that I have, which is "unique-equipped" to another slot, without unequipping it and equipping again
**Current behaviour**:
![2018-09-30_21-49-07](https://user-images.githubusercontent.com/40346279/46265210-bd347580-c4fa-11e8-8d37-af8014b9d383.gif)
**Expected behaviour**: 
Should be able to move the trinket to another slot.
**Server Revision**:

**Comment by Wolffenstein** [comment]
Fixed in rev 2111.
