### ISSUE TITLE
[NPC] Deathcage Sorcerer runs back into melee range

### ISSUE THREAD

**Issue by Zadiel** [Atlantiss/NetherwingBugtracker#996]
[//]: # (Enclose links to things related to the bug using http://wowhead.com or any other TBC database.)
[//]: # (You can use screenshot ingame to visual the issue.)
[//]: # (Write your tickets according to the format:)
[//]: # ([Quest][Azuremyst Isle] Red Snapper - Very Tasty!)
[//]: # ([NPC] Magistrix Erona)
[//]: # ([Spell][Mage] Fireball)
[//]: # ([Npc][Drop] Ghostclaw Lynx)
[//]: # ([Web] Armory doesnt work)

**Description**: 
Deathcage Sorcerers in Ghostlands will run away from the player after rooting them with Frost Nova, but will sometimes run back into melee range to cast Frostbolt.
**Current behaviour**:
Deathcage Sorcerer roots the player with Frost Nova, runs 5 yards away, then runs back into melee range to begin casting Frostbolt
**Expected behaviour**: 
Deathcage Sorcerer roots the player with Frost Nova, then runs out of melee range to cast Frostbolt
**Server Revision**: 
2094?

![deathcage sorc bug](https://user-images.githubusercontent.com/5055893/46266232-ae01f780-c4fb-11e8-8a0e-7df67db657cb.gif)

**Comment by Easyfraggy** [comment]
I think it happens when the mob gets meleed after starting to run away.

**Comment by Tenoutoften** [comment]
Uploading a video where this occurs, as a blood elf and without hitting [Hillsbrad Councilman#2387](https://db.excalibur.ws/?npc=2387#abilities) video can be found [here](https://www.youtube.com/watch?v=Jv5kIMpwODQ&feature=youtu.be)

**Comment by Tereneckla** [comment]
Fixed
