### ISSUE TITLE
[Zul Farrak][NPC] Unlinked mobs

### ISSUE THREAD

**Issue by Knoox** [Atlantiss/NetherwingBugtracker#997]
**Read title**: 

**Server Revision 2100**: 
![wowscrnshot_100118_013414](https://user-images.githubusercontent.com/18479169/46266420-5a110600-c52f-11e8-9c06-1bc021918809.jpg)

**Comment by Firroth** [comment]
Gonna add 2 more missing links.

- 2 mobs near the tents, should pull with those near bonfire.

![2018-10-12_13-32-45](https://user-images.githubusercontent.com/43505196/46883376-277ddc00-ce52-11e8-9c41-5b353b41cd27.gif)

- 4 shadowcasters standing "near" this fountain should be all linked together.
https://gfycat.com/pl/upload/results

**Comment by Tereneckla** [comment]
All of those are how it is like now, but I couldn't find anything that they should be linked.
(It does make sense for them to be linked though.)

**Comment by Evolvee** [comment]
fixed in next rev
