### ISSUE TITLE
[Badlands][NPC]Placement

### ISSUE THREAD

**Issue by Knoox** [Atlantiss/NetherwingBugtracker#998]
**Title**: 

**Server Revision 2100
![wowscrnshot_093018_222941](https://user-images.githubusercontent.com/18479169/46266439-8167d300-c52f-11e8-8fad-3c3f0238578a.jpg)
**:

**Comment by ttghnw** [comment]
LUL Hey!! cats like to climb...stuff... :P

**Comment by aresbrutus** [comment]
Weird how no one noticed it so far!

Fixed in one of the upcoming updates.
