### ISSUE TITLE
[Badlands][Quest] Broken Alliances

### ISSUE THREAD

**Issue by Knoox** [Atlantiss/NetherwingBugtracker#999]
**The two drakes, according to recound has about 2400 health each(Level 50 elite), whilst the mobs around the pillar(Used for summoning) has about 5400 health(level 43 elite)**: 

**Server Revision 2100**: 
![wowscrnshot_093018_222600](https://user-images.githubusercontent.com/18479169/46266511-e3283d00-c52f-11e8-8aa2-7afd3e93c5b3.jpg)

![wowscrnshot_093018_222619](https://user-images.githubusercontent.com/18479169/46266494-cab82280-c52f-11e8-9f63-5522b5da6615.jpg)
![wowscrnshot_093018_222606](https://user-images.githubusercontent.com/18479169/46266499-cc81e600-c52f-11e8-9249-044a7b6f6f33.jpg)

**Comment by mbzz88** [comment]
That's how it's supposed to be, was changed in 2.4 so the spawned mobs are 50 non elite, the random elites around the place are more difficult.

**Comment by The14me** [comment]
Please add some proof about this mob's. Thx!

**Comment by mbzz88** [comment]
Was 2.3 sorry, but http://wowwiki.wikia.com/wiki/Patch_2.3.0
"Many elite creatures and quests in the level 1-60 experience have been changed to accommodate solo play. "
And https://www.wowhead.com/quest=717/tremors-of-the-earth

By Xeroth (308 –  2·5)  on 2008/03/28 (Patch 2.4.0) |   |  As of patch 2.4 quest spawns two level 50's. They are no longer elite. This quest is now fairly easy for the reward.
Last edited by Xeroth on 2008/03/28 (Patch 2.4.0)
Onciebuns on 2008/03/29 (Patch 2.4.0)
Confirmed no longer elite, the mobs around it still are, they're actually as hard as both of the dragons for the quest now, but you can pull the dragons 1 by 1 without even clearing if you find a good spot.

**Comment by Evolvee** [comment]
We arent doing "pre-nerf" vanilla leveling(apart few exceptions)... atleast for now...

what exactly is the issue in here?

**Comment by Easyfraggy** [comment]
So is this actually an issue?

**Comment by The14me** [comment]
its suppose to be like that.
